### ISSUE TITLE
Multiple parameters in the postman request is not reflected when running request in postman console runner

### ISSUE THREAD

**Issue by maheshcts97** [a85/POSTMan-Chrome-Extension#10000]
**Describe the Issue**
Multiple parameters in the postman request is not reflected when running request in postman console runner

**Steps to Reproduce**
1. Add multiple Query params  in the request.
2. multiple Query params are appended to the request URL and it is sucessfully executed.
3. Add the request to a collection and run them from runner console.
4. Only one parameter is appended to the request URL.
5. When I looked at the JSON file for the collection, I could see that query parameters are disabled which is incorrect

**Screenshots or Videos**

**Environment Information**

 - Platform Type: Postman client
 - Postman Version: Version 7.36.5
 - Operating System: Windows 64

**Comment by giridharvc7** [comment]
Can you check if you've saved the request after adding the query parameters before running them from the runner?

**Comment by shubhbhargav** [comment]
@maheshcts97 Are you still facing this issue? Did you try out what @giridharvc7 recommended?

**Comment by DannyDainton** [comment]
Hey @maheshcts97  👋🏻

I'm going to close this issue due to inactivity - If you're still facing the issue in the latest version we can reopen this and investigate further.
