### ISSUE TITLE
YAML indentation is 2 spaces, but OpenAPI 3.0 editor uses 4 spaces on newline

### ISSUE THREAD

**Issue by charlesritchea** [a85/POSTMan-Chrome-Extension#10003]
**Describe the Issue**

YAML is quite explicit in it's indentation rules: 2 spaces
Yet the OpenAPI 3.0 editor adds a 4 space indent on newline.

**Steps to Reproduce**

Create an OpenAPI 3.0 API with YAML file and add a newline after a property

**Environment Information**

 - Platform Type: Linux
 - Postman Version: 8.5.1
 - Operating System: Ubuntu 20.10

**Comment by raghumurthy-jayandran** [comment]
@charlesritchea  As per yaml's [official spec](https://yaml.org/spec/1.2.2/#61-indentation-spaces?~::~text=In%20general,%20indentation%20is%20defined%20as%20a%20zero%20or%20more%20space) you are allowed to use zero or more space characters. If you prefer to use two spaces for indentation you always have the flexibility to configure this within postman by navigating to _**Setting icon > General > Editor settings**_. Hope this addresses you'r use case. 
Going ahead and closing this. Thank you!
