### ISSUE TITLE
Sidebar is empty after upgrading to v8

### ISSUE THREAD

**Issue by jiwtir** [a85/POSTMan-Chrome-Extension#10004]
**Describe the Issue**
After upgrading to `v8.5.1` from `v7.36`, there was no tab selected in the Sidebar and I could see the empty view.

**Steps to Reproduce**
- Upgrade from v7 to v8

**Screenshots or Videos**
![telegram-cloud-photo-size-5-6186082615686180170-y](https://user-images.githubusercontent.com/81774460/120886131-fa395a00-c609-11eb-8dc4-a1c47b029e4b.jpg)

**Environment Information**
Postman for Windows
Version 8.5.1
win32 10.0.19041 / x64

**Comment by timbochamp** [comment]
Hi @jiwtir , thanks for the report! I was able to reproduce this as well upgrading from v7.36.6 to v8.6.1. As a workaround, I was able to see the collections sidebar after navigating to another sidebar by clicking one of the other leftmost options (e.g., APIs, Environments) and then navigating back to Collections. Does this work for you as well?

**Comment by jiwtir** [comment]
@timbochamp yes, that works. Thank you! 🍻
