### ISSUE TITLE
Reuse code so pre-request and (post-request) Tests can reuse or link to functions defined elsewhere (as suggested earlier in issue #4058)

### ISSUE THREAD

**Issue by justinmaarschalkerweerd** [a85/POSTMan-Chrome-Extension#10009]
We use Postman for our test automatization. Haveing benefits over SoapUi and the RobotFramework, Postman also has a big drawback I think. And that is code reusability in testscripts. It would make this tooling much more mature if code could be shared across multiple tests by linking from a script location to a file in a different location, or better being able to refer from one testscript to another via function names or someting (like in C# or Java).

So instead of havig to copy script files accross multiple requests (and changing all of them when a bug is found or something needs to be changed). I would like all these requests to be able to refer to the same function. So I just have to maintain in one place. 

Also this shared script locations should also be saveable, so that it is in version control.

**Comment by jauntyjocularjay** [comment]
This. I would love to have this. I have a schema validation class I would like to use in all my tests instead of having to copy 835 lines of code into every test script.

**Comment by postfrzero** [comment]
Hey folks -- Postman v11 rolled out a few weeks ago with support for the new Package Library, which enables you to reuse code by creating and requiring packages within your scripts. Learn more about the Package Library [here](https://blog.postman.com/postman-v11-plans-packaging-updates-2024/#what-is-the-package-library-for-reusable-scripts) or [here](https://learning.postman.com/docs/tests-and-scripts/write-scripts/package-library/).

**Comment by jauntyjocularjay** [comment]
Yes and it is AWESOME thank you so much!
