### ISSUE TITLE
Installed update with multiple windows open and it failed to restore state after restart

### ISSUE THREAD

**Issue by stcalica** [a85/POSTMan-Chrome-Extension#10007]
Reporting on behalf of the user. 

**Describe the Issue**

> I want to report an issue installing an update today. I had multiple postman windows open to various workspaces and with various tabs open and environments selected. I let the update install and restart postman, expecting it to restore all of my windows to their current state. It did for one window, but the others were all left on the Postman homepage tab with no project selected. Frustrated, I selected a project in one of the windows in an attempt to recreate what I had lost, and a bunch of tabs appeared as if it was trying to restore the state of one of my instances of the workspace, but all the tabs are empty and produce a "not found" error in the middle of the tab's pane. I don't need to troubleshoot this, I need to get back to working so I'm just going to rebuild everything, but I wanted to let you know about the problem

**Steps to Reproduce**

1. Open multiple windows of Postman app 
2. Update the application
3. Windows will revert to home screen and lose state from before the update 

**Screenshots or Videos**

**Environment Information**

 - Platform Type: Native app
 - Postman Version: '8.6.1-win32-x64'
 - Operating System: Windows

**Additional Context**

**Comment by numaanashraf** [comment]
@stcalica This is resolved in `v8.6.2`
