### ISSUE TITLE
General Visualizer for JSON to display all data in a table

### ISSUE THREAD

**Issue by K232** [a85/POSTMan-Chrome-Extension#10014]
https://learning.postman.com/docs/sending-requests/visualizer/ describes how to use Visualizer for a different output e.g. of JSON data. According to the documentation, a new template for each JSON is necessary. Would it be possible to have a general template for ALL JSON data, e.g. like https://marketplace.visualstudio.com/items?itemName=RandomFractalsInc.vscode-data-preview ? The structure of the JSON of course differs on each request. So the general visualizer should just display all json data in columns, no special formatting or else.

**Comment by DannyDainton** [comment]
Hey @K232 

There is a template in the `Postman Team Collections` Public Workspace that _could_ provide what you need to visualize the JSON data:

https://www.postman.com/postman/workspace/34f3a42c-18a7-4ad6-83fb-2c05767d63a7/request/3407886-0cd8c17f-45bc-48b0-9be0-cd7d7704425d

**Comment by K232** [comment]
That's cool @DannyDainton ! Many thanks! Maybe you also know: Is there a way to have this automatically included in every GET I do so I needn't paste it into every Test-Section? Or store it in the environment somewhere?

**Comment by DannyDainton** [comment]
All credit for the template should go directly to @sivcan 🏆

You can store the whole thing at the Collection or Folder level and it will be there for each request.

That's obviously based on returning a JSON response each time so if anything else is return it's either not going to show or potentially throw an error.

**Comment by DannyDainton** [comment]
It looks like you have the solution that you require, I'm going to close this one now.
