### ISSUE TITLE
"Save response" for a 3.74 MB response silently fails

### ISSUE THREAD

**Issue by fyvekatz** [a85/POSTMan-Chrome-Extension#10018]
**Describe the Issue**

"Save response" for a 3.74 MB response silently fails

**Steps to Reproduce**
I used the following API from skycanner:  http://partners.api.skyscanner.net/apiservices/geo/v1.0. It needs an apikey.

**Screenshots or Videos**

**Environment Information**

 - Platform Type:       Postman web
 - Postman Version:  Version of 6/10/2021
 - Operating System: Chrome browser

**Additional Context**

No additional context needed, I believe. Looks like we don't save if the response is beyond a certain size threshold. If we're going to not allow this to be saved, 1) we should explicitly fail with a message and 2) we should document the size limit.

**Comment by sathishkumar-thangavel11** [comment]
@fyvekatz we couldn't able to reproduce the issue on "save response" for 3.74MB response. Is it possible to share the logs ?

Note - response size must be smaller than 5MB to **[save as example](https://learning.postman.com/docs/sending-requests/examples/#adding-an-example)**

**Comment by giridharvc7** [comment]
Closing this issue for now as we weren't able to recreate this issue. Feel free to open it again in case you face this.
