### ISSUE TITLE
Request names are being half-hidden with "..." in Postman runner.

### ISSUE THREAD

**Issue by takwing** [a85/POSTMan-Chrome-Extension#10015]
For each API request under a collection, we can name them explicitly.

And uponr running a collection with Postman runner, the request names in the test result page are being half-hidden with "..." (and in extreme case, only a single character of the original request name is shown).  

This makes it extremely hard to locate which test has failed.  This situation did not happen in the v7.x of Postman.

**Comment by DannyDainton** [comment]
Hey @takwing

As you're describing a UI issue and something that you can see with your app instance, could you attach an example of this behaviour, please?

**Comment by takwing** [comment]
As seen in the screenshot, request name "photo collage / 800x420" is shown as "p.."
![xuT6raZljk](https://user-images.githubusercontent.com/342481/121535122-71b92000-ca34-11eb-9735-283b25fbdeb3.jpg)

**Comment by DannyDainton** [comment]
There is only so much space to make use of in that view - The window size, Collection sidebar, length of request name, length of the URL and the folder path to the requests all need to be accounted for. Additionally, The HTTP Method, status code, response timing and sizes need to be on the same line.

I believe that a tooltip is missing from that truncated value, these are present on the URL and folder path is those are truncated and it feels like this should only be on the requests name.

![image](https://user-images.githubusercontent.com/17089546/121544764-de66f700-ca01-11eb-9b7f-18343ba455be.png)

**Comment by malvikach** [comment]
Hi @takwing 

Thanks for the feedback. We have fixed this problem in the latest release of Postman (Version 10.12.0). Request names will not be hidden now as we have moved the URLs to the next line. 

<img width="1057" alt="Screenshot 2023-03-17 at 11 33 46 AM" src="https://user-images.githubusercontent.com/89449769/225825772-dd63579e-5c70-47b1-8f5c-29b38828ef73.png">


We have also added some more improvements to help you with faster navigations and help with debugging post a run:

- You can now click on request names to open the requests from the Collection Runner Results. 
- View request and response details in the Collection Runner Results in a more efficient way. Response Body is also formatted and you can easily search/copy it if needed during debugging an issue.
- We display the request/folder paths on the right-hand pane. The individual components can be clicked to navigate to the given folder quickly.

![ezgif com-optimize (3)](https://user-images.githubusercontent.com/89449769/225825957-463f1cf3-0bb9-4bb8-a0d1-51727d9c659e.gif)

Please Note: The Postman version update is being rolled out, you will get it in the next 2-3 days if you haven't already.

Thanks again for your feedback. We really appreciate it.

Cheers!
Malvika
