### ISSUE TITLE
Cookie header is not sent

### ISSUE THREAD

**Issue by boqapt** [a85/POSTMan-Chrome-Extension#1001]
I have Postman - REST Client (Packaged App) 2.0.15, Postman Interceptor 0.2.9, Chrome Version 41.0.2272.118 m. Postman is opened and Toggle Interceptor button is green in Postman.
I am trying sending a POST request with Cookie header but request is sent without cookie  

Trying to investigate I opened background page of Postman Interceptor and in Console tab saw error "Refused to set unsafe header "Cookie"" (background_page.js:350). Other headers (Content-Length, Accept-Encoding etc. does not cause error and are normally sent). In Network tab I proved that request is indeed sent with all headers except Cookie.

Sometimes there is the same "refused" error for Connection header

**Comment by abhijitkane** [comment]
When the Interceptor is on and enabled in Postman, every request made through Postman is sent to the Interceptor via Chrome's internal messaging API, and the XHR request is made from the Interceptor.

In Chrome, `xhr.setRequestHeader("Cookie"`.. is disallowed. But the interceptor uses another Chrome API to set Cookies for that domain. You should see them in the Interceptor's network tab (see attached).
![screen shot 2015-04-11 at 21 20 00](https://cloud.githubusercontent.com/assets/681190/7102015/8fcac222-e090-11e4-81bd-8f8eda1084ba.png)

If not, can you set a breakpoint at background_page.js:216 and check if it's hit / and the value of `cookies` at that point? What's the string that you're setting in the Cookie header in Postman?
