### ISSUE TITLE
New Integration Request - GoogleAdsAPI

### ISSUE THREAD

**Issue by laad-shikha** [a85/POSTMan-Chrome-Extension#10019]
**Describe your current workflow**
How do you use Postman with the rest of the tools in your stack to achieve your use-case?

**Describe your ideal workflow**
How would you want Postman to integrate with specific products/tools to simplify or enhance your experience?

**Describe alternatives you've considered**

**Additional context**

**Comment by shashankawasthi88** [comment]
@laad-shikha can you please add more details to the Integration request.
