### ISSUE TITLE
Save WebSocket requests to collection

### ISSUE THREAD

**Issue by obroomhall** [a85/POSTMan-Chrome-Extension#10027]
**Is your feature request related to a problem? Please describe.**
If a server supports both HTTP requests and web socket requests, it should be possible to save both types into a collection which can then be shared with a team.

**Describe the solution you'd like**
To be able to save web socket requests to collections, allowing for the use of the same collection features expected from saved HTTP requests.

**Describe alternatives you've considered**
Currently it is not possible to save a web socket request, which means each new team member must enter the web socket request details manually.

Previously used web socket requests can then be found in the request history, however, this also prevents the use of collection features, such as using collection variables such as authentication headers.

**Comment by smrtyviks** [comment]
I would like to see this feature too

**Comment by mar-schmidt** [comment]
+1

**Comment by glebsa8** [comment]
For me, websocket support feature without saving option is almost useless (( sad to see the feature in semi-finished state while reading about other shiny new features in the changelog. There's no **decent** websocket GUI client currently on the market with that functionality, so it would be a great opportunity to attract more customers to postman.

**Comment by codenirvana** [comment]
Hey everyone 👋🏻 

We've recently added support for saving and documenting WebSocket requests in collections.
The functionality is already available in the [Postman Web](https://go.pstmn.io/build) and will be rolled out to everyone using the native app with the v9.1 release. You can read more about this release in our [latest blog post](https://blog.postman.com/save-and-document-websocket-requests-in-collections/).

This capability is built as a foundation for our upcoming improvements to support more synchronous and asynchronous protocols. So for the moment, you will need to create a new collection and exclusively store WebSocket requests in them.
We’ll be incrementally adding support for more features like scripting, testing, forking, and more.

Thanks for your continued support and feedback!
