### ISSUE TITLE
New Integration Request - Azure DevOps

### ISSUE THREAD

**Issue by carbisb** [a85/POSTMan-Chrome-Extension#10024]
**Describe your current workflow**
How do you use Postman with the rest of the tools in your stack to achieve your use-case?

**Describe your ideal workflow**
How would you want Postman to integrate with specific products/tools to simplify or enhance your experience?

**Describe alternatives you've considered**

**Additional context**

**Comment by abhijitkane** [comment]
Duplicate of https://github.com/postmanlabs/postman-app-support/issues/9131
