### ISSUE TITLE
Documentation table markdown "Click to Expand" button is not showing up sometimes.

### ISSUE THREAD

**Issue by william-eth** [a85/POSTMan-Chrome-Extension#10026]
I used the postman document feature to write a table markdown to describe API request parameters. Sometimes the table was huge, it will show the  **"Click to Expand"** button to view the whole table.

But in some situations the "Click to Expand" button will disappear. 

For one case is if I clicked the "X" button to close the document and open it again, the table "Click to Expand" button will disappear.

Postman Version: 8.6.2
Platform : mac os big sur

![correct case](https://user-images.githubusercontent.com/17855487/122028185-5c5e4000-cdfe-11eb-9f91-449f4114a958.png)

![abnormal case](https://user-images.githubusercontent.com/17855487/122028132-510b1480-cdfe-11eb-8c24-9b2b1d7291fb.png)

**Comment by Raja-Simha** [comment]
@yaohsien thanks for reporting this issue. We are working on a fix for this and the fix should be out soon.

**Comment by Raja-Simha** [comment]
@yaohsien Closing this issue as this has been fixed. Please re-open if you find the problem to be unresolved.
