### ISSUE TITLE
Postman steals focus when update is available

### ISSUE THREAD

**Issue by Sti2nd** [a85/POSTMan-Chrome-Extension#10022]
**Describe the Issue**

An open Postman window steals focus at random times, ruining my workflow. I believe it is the notification of a new update that is the problem.

**Steps to Reproduce**

1. Have a Postman window open on another screen or next to another window
2. Write continously on your keyboard in another window than Postman
3. When an update is available in the Postman window the focus is shifted to Postman and you notice that you cannot write in the other window anymore because the cursor is gone.

**Environment Information**

 - Platform Type: Postman for Windows
 - Postman Version: 8.6.2
 - Operating System: win32 10.0.19042 / x64

**Comment by Sti2nd** [comment]
Examples of when Postman ruin work:

* When you are in a video call with one screen, and suddenly Postman pops up and takes over the entire screen
* When you are writing a command in terminal and suddenly you are executing random keyboard shortcuts in Postman

**Comment by jviotti** [comment]
Makes sense! Thanks a lot for raising this up. We'll be looking into this soon.

**Comment by twitharshil** [comment]
Closing this as a duplicate for https://github.com/postmanlabs/postman-app-support/issues/9582
