### ISSUE TITLE
Cached global variable

### ISSUE THREAD

**Issue by jonathanfenwick** [a85/POSTMan-Chrome-Extension#1002]
I have a test collection which I have been using for quite happily for few weeks.  

All of a sudden I'm getting a failure where a global variable value that should be being sent in a subsequent test is incorrect, it seems to be using a cached value for the variable value.  

I have debugged on the server side and the value being received is not what would be suspected.  I have written the test in Fiddler and it works absolutely fine.

Please help!

**Comment by abhijitkane** [comment]
@jonathanfenwick Sorry for the delay. Are you still seeing this in v3.0.4?
