### ISSUE TITLE
How to send raw bytes in websocket request

### ISSUE THREAD

**Issue by daanpape** [a85/POSTMan-Chrome-Extension#10025]
Hello,

It's great to see websocket support in Postman. We use our own binary subprotocol but I cannot find how to send raw binary bytes via Postman. I have selected 'Array Buffer' with 'Uint8Array' but whatever I'm entering in the message box it always gets transformed to ASCII encoding instead of my hex bytes.

**Comment by codenirvana** [comment]
@daanpape Thanks for the feedback, I agree that the existing `Array Buffer` implementation is confusing as it sends the ASCII as binary.

How would you prefer authoring binary? I can think of:
1. Hex bytes
2. Base64
3. File upload

**Comment by daanpape** [comment]
Hello @codenirvana, thank you for your response. In the first place I would prefer a hex-editor like experience as this would allow one to write a binary message directly. 

Maybe out of scope for this issue would be the following idea. When one uses the binary message format, most of the time this means that a subprotocol is used. For example MQTT, or in my case our own REST-like websocket protocol. I think it would be nice if we could implement a `preprocessing` hook in `JavaScript`, a so called message parser. This function could return a string which makes a human readable message out of the incoming binary format.

**Comment by codenirvana** [comment]
@daanpape with the latest release, we've updated the binary message authoring experience to accept `Base64` or `Hexadecimal` string input. Can you update your app and confirm if this fixes your issue?

![Screenshot 2021-08-06 at 11 27 08 AM](https://user-images.githubusercontent.com/4865836/128463231-3e332d94-8673-45ac-a505-85c4c043e322.png)

For the custom message parser use case, yes that's on the roadmap (_no eta just yet_) but can you share the binary encoding you are using? is it MessagePack?
