### ISSUE TITLE
Unresolved variables no longer appearing red in query params

### ISSUE THREAD

**Issue by neilstudd** [a85/POSTMan-Chrome-Extension#10028]
**Describe the Issue**

As mentioned in [this forum topic](https://community.postman.com/t/unresolved-variable-highlighting/24854), when a variable cannot be resolved, it normally appears in the Postman UI in red, making it visually clear that there is a problem.

However, in recent builds (observed in 8.6.1 and 8.6.2) the text is not red when it appears within query params or path variables - it's the same tint as a valid/resolved variable.

**Steps to Reproduce**

1. Create a new GET request
2. Add two query params - map one of them to a valid variable, map the other to a non-existent variable
3. Check the colour of both variables in the grid - they're the same

**Screenshots or Videos**

Note that 'invalid-value' is clearly red in the address bar, but in the query params it's the same colour as a resolved variable; I've enclosed clour picker screenshots of both as proof.

![image](https://user-images.githubusercontent.com/7154703/122054233-63c22100-cddf-11eb-90ff-03a420f98bb5.png)

![image](https://user-images.githubusercontent.com/7154703/122054429-923ffc00-cddf-11eb-9bcf-d89954580ba2.png)

![image](https://user-images.githubusercontent.com/7154703/122054488-a1bf4500-cddf-11eb-900a-b433fa83b0b5.png)

**Environment Information**

 - Platform Type: Desktop and web
 - Postman Version: 8.6.1 and 8.6.2
 - Operating System: Windows 10, Mac OSX Catalina 10.15.7

**Comment by malvikach** [comment]
@neilstudd Happy to inform that this issue has been fixed and released on the web. It will be rolled out to the app next week. 
Please feel free to give it a try and update the community thread too.
