### ISSUE TITLE
Tests tab is blank after request returns

### ISSUE THREAD

**Issue by Sigkill9** [a85/POSTMan-Chrome-Extension#1003]
The Tests tab is empty after running a request. 
Running packaged app on mac.
The results show up when running the Test Runner but not in the app.

Thanks.

**Comment by abhijitkane** [comment]
@Sigkill9 Can you send the screenshot and test script (or better yet, the collection file) to help@getpostman.com?

**Comment by Sigkill9** [comment]
I am not sure what happened or why but it just started working again.
Thanks.
