### ISSUE TITLE
JWT/Header tokens is not syncing between devices on the same Postman Account

### ISSUE THREAD

**Issue by kasharaylo** [a85/POSTMan-Chrome-Extension#10035]
I'm using two different devices and the same Postman account.
I set up requests with Bear/JVT/Header tokens and they are not syncing between devices.
This is the big deal for me. I can't switch between devices to test all my things.

Could you please fix this?

**Comment by DannyDainton** [comment]
Hey @kasharaylo 

Could you expand on this, please?

Are the tokens hardcoded in the collections/requests or are you using variables? Which versions and platform are using?

The more details that you can provide the easier it will be for us to assist you with the issue.

**Comment by kasharaylo** [comment]
Hi @DannyDainton 
I'm using hardcoded tokens in requests of my collections.
macOS 11.4, Postman 8.6.2.

**Comment by kasharaylo** [comment]
<img width="912" alt="Screenshot 2021-06-16 at 17 44 50" src="https://user-images.githubusercontent.com/17513326/122240640-99900400-ceca-11eb-8295-bac3cadfa70c.png">
<img width="949" alt="Screenshot 2021-06-16 at 17 45 24" src="https://user-images.githubusercontent.com/17513326/122240677-a1e83f00-ceca-11eb-915f-e81bcad5443e.png">

**Comment by DannyDainton** [comment]
Without syncing the token, it's only within that session. Postman doesn't sync the token by default so it wouldn't be available elsewhere.

You would need to action that from the UI using the orange sync icon.

More information can be found here:

https://blog.postman.com/collaborating-oauth-postman/

**Comment by kasharaylo** [comment]
@DannyDainton Thanks
It works

**Comment by DannyDainton** [comment]
Awesome, I added the blog post to my comment that would explain this better than I just did. 😄 

Going to close this out now.
