### ISSUE TITLE
Not parsing variables in URL

### ISSUE THREAD

**Issue by rameyroad** [a85/POSTMan-Chrome-Extension#10038]
We script most of our request using variables because we have multiple environments (local, QA, Stating, & PROD). This includes the base URL and extended routes as those change between environments. Starting a couple of updates back, the client will sometimes not parse the variables in the URL and instead throw an error that the route cannot be found.

Example:
(GET) {{ApiGatewayBaseUrl}}{{UserSubRoute}}UserActivity/{{userProfileId}}/activity

Locally:
(GET) https://localhost:5001/UserActivity/12345/activity

QA: 
(GET) https://api-qa.company.org/user-api/UserActivity/12345/activity

When calling this locally, where UserSubRoute is just "/", all is good. When running in any other environment, we defer to the **global** value of UserSubRoute, which is "/user-api/", and we get this error in the console:

Error: getaddrinfo ENOTFOUND api-qa.ccl.org{{usersubroute}}user-api

All we're doing is changing the environment drop down.

This seems to work fine when we define UserSubRoute separately for each environment.

I'm using v8.6.2

**Comment by DannyDainton** [comment]
Hey @rameyroad 

Could you provide examples of the failing variable in the environment, please?

Are all the scoped names consistent? `UserSubRoute` vs `usersubroute`.

**Comment by rameyroad** [comment]
Tried to reproduce this morning after a restart and could not. Will reopen if I encounter again.
