### ISSUE TITLE
Providing static dropdown variable values for GET query parameters.

### ISSUE THREAD

**Issue by srinivas-iosdev** [a85/POSTMan-Chrome-Extension#10040]
Can we have a dropdown list of static values to choose for a GET request query parameters?

**Comment by DannyDainton** [comment]
Hey @srinivas-iosdev 

Could you expand on the details of this request and give examples of what's currently not working for you and how this new feature would solve it?

**Comment by DannyDainton** [comment]
Hey @srinivas-iosdev  👋🏻

I'm going to close this issue due to inactivity and lack of details about the requested feature. If you're able to provide more information about the context of the request and some clear examples, we can look into opening this up again.
