### ISSUE TITLE
OpenApi readOnly schemas are included in PATCH request body

### ISSUE THREAD

**Issue by mulyi** [a85/POSTMan-Chrome-Extension#10045]
Hi,

Imported into Postman an OAS3.0 API in YAML format. The schema was validated.
Among other things, the API definition contains read-only schemas (readOnly keyword of OAS3.0).
The read-only schemas are included by Postman in the example PATCH request body.
The correct behavior is to include the read-only nodes only in example GET response and exclude them for PATCH example request body.

<img width="474" alt="Show-summary read-only" src="https://user-images.githubusercontent.com/74120674/122455100-b56fd480-cfb4-11eb-9d65-e434c914149e.PNG">
<img width="533" alt="Patch read-only" src="https://user-images.githubusercontent.com/74120674/122455132-bd2f7900-cfb4-11eb-975d-72348fa78c72.PNG">

Thanks,

Muly

**Comment by VShingala** [comment]
@mulyi Could you check this behavior once now? I was unable to reproduce this issue for below example with `readOnly` property.

API Definition:
<img width="972" alt="image" src="https://user-images.githubusercontent.com/16756296/178034838-70976fd7-4e69-4885-9a4c-a45c151c4070.png">



Generated collection:

<img width="972" alt="image" src="https://user-images.githubusercontent.com/16756296/178034613-553dd84b-ce86-407b-ad74-a98602d3ee0c.png">

**Comment by VShingala** [comment]
@mulyi I'll close the issue for now as we are not able to reproduce it but feel free to open it if you're still facing the issue.
