### ISSUE TITLE
[Version 8.6.2][Mac] There was an error importing this collection. Please try again

### ISSUE THREAD

**Issue by FredaXin** [a85/POSTMan-Chrome-Extension#10046]
**Describe the Issue**

Getting There was an error importing this collection. Please try again. using Version 8.6.2 on Mac.

**Steps to Reproduce**
Click _Run in Postman_  [here on the Shopify Collection. ](https://documenter.getpostman.com/view/3800273/SWLk55pF)

**Screenshots or Videos**
<img width="1777" alt="Screen Shot 2021-06-17 at 5 30 13 PM" src="https://user-images.githubusercontent.com/48503813/122482911-784d1780-cf9f-11eb-8855-88e2a24d03bd.png">

**Environment Information**

 - Platform Type: Desktop
 - Postman Version: Version 8.6.2
 - Operating System: macOS Big Sur Version 11.2.3

**Additional Context**
- The [Shopify Collection](https://documenter.getpostman.com/view/3800273/SWLk55pF) is not working on the Postman web version either. 
- [Similar issues that has been fixed for version 8.03.](https://github.com/postmanlabs/postman-app-support/issues/9519)

**Comment by coditva** [comment]
@FredaXin This is fixed in the latest Postman app and the web version. Please try it out and let us know how it goes. 🎉 
I'm closing this issue but feel free to re-open if you still have issues importing the collection. 🙂
