### ISSUE TITLE
Sync breaks second level folders

### ISSUE THREAD

**Issue by DickSmith** [a85/POSTMan-Chrome-Extension#1004]
I had a collection that had folders within the folder. After syncing and then signing into my account on another machine, all of the items in the 2nd level folders were in the 1st level folder, in a seemingly random order. All the second level folders are now empty.

Luckily I had made a backup on my original machine before trying to sync on a new one, so I don't have to reorganize them, which would have been somewhat tedious since my naming convention was based on the context of the folder they were in and some have similar names.

**Comment by abhijitkane** [comment]
@DickSmith Can you mention your username / email?

**Comment by DickSmith** [comment]
GuestDriven / webmaster@guestdriven.com

**Comment by abhijitkane** [comment]
We made some changes to Postman's local database sometime in September. Any collections created before then might have this problem. We're working on patching up all such data. I'll update this thread soon.

Sorry for the inconvenience.

**Comment by DickSmith** [comment]
I don't know if it's related, but suddenly my Global/Environment Variables are duplicating on sync. In the case of the the Environment Variables, it's just another copy, but in the case of the Global variables it's a duplication in the same section, which is causing it to grow extremely fast, as it doubles what was previously in there, which now includes previous duplications.

If you want, I can open a separate issue.

**Comment by abhijitkane** [comment]
What version of the app are you on? You can find out by going to the Settings window (wrench icon in the top right > About).

Also, which environments do you see duplicates of? We'll push a fix for the globals issue soon.

**Comment by DickSmith** [comment]
I actually made a back up of my corrected variables and collections, uninstalled/reinstalled Postman to 2.0.17 on both of my workstations. I'll give an update when I try to sync later this evening if I am still encountering any issues.

**Comment by a85** [comment]
Should not be happening again. Reach out to us at help@getpostman.com if you face any issues.
