### ISSUE TITLE
Select File button not working on postman desktop

### ISSUE THREAD

**Issue by miracle0930** [a85/POSTMan-Chrome-Extension#10042]
When I was using Postman runner, I cannot click the 'Select File' button on the Data field.

**Describe the Issue**

The Select File Button is not working.

**Steps to Reproduce**

Click Runner, on the bottom-right;
Select any API from Collections;
Click Select File button you then the bug appears

**Screenshots or Videos**

![image](https://user-images.githubusercontent.com/15270493/122399454-64a8ad80-cfad-11eb-8af9-bc7c3ea301d8.png)

**Environment Information**

 - Platform Type: Postman desktop
 - Postman Version: version 8.6.2
 - Operating System: MacOS

**Additional Context**

**Comment by DannyDainton** [comment]
Hey @miracle0930 

Can you please complete the full issue template and include the environment and platform details.

```
<!--
Please read through the [guidelines](https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues) before creating a new issue.
Provide as much information as you can as this will give us the best possible chance to quickly get to the root of the problem.
-->

**Describe the Issue**
<!--
A high-level summary or description of the problem that you're facing.
-->

**Steps to Reproduce**
<!--
A list of steps that can be followed to recreate the issue.
-->

**Screenshots or Videos**
<!--
Please add screenshots or a short video to help visually explain the problem. 
Ensure that the screenshots/videos do not contain any sensitive information such as API keys or Access Tokens. 
-->

**Environment Information**

 - Platform Type: 
 - Postman Version:
 - Operating System:

**Additional Context**
<!--
Please add any other contextual information about the problem, that might be relevant and help explain the issue you're facing.
-->

```

**Comment by miracle0930** [comment]
Thanks, the issue has been updated

**Comment by DannyDainton** [comment]
Thanks for updating the issue - Is it opening the finder if you click the button twice? 🤔

**Comment by miracle0930** [comment]
The problem disappeared after I restarted the postman. So wired.  🤔

**Comment by DannyDainton** [comment]
The way the pointer cursor appears doesn't seem right to me but it was also quite slow to open the file explorer window on my machine. 😢

**Comment by miracle0930** [comment]
Yep, the hover cursor is not correct but at least I can upload the data file. lol

**Comment by timbochamp** [comment]
I logged a bug for the hover cursor; thanks for the report!

**Comment by malvikach** [comment]
This had been fixed sometime back. Please feel free to let us know if you face any other issues with this.
