### ISSUE TITLE
Postman repeatably fails to import Redfish OpenAPI 3 schema

### ISSUE THREAD

**Issue by micahhausler** [a85/POSTMan-Chrome-Extension#10059]
**Describe the Issue**
Attempting to import the Redfish OpenAPI schema repeatably, consistently yields this error: "There was an unexpected error. Please try again"

**Steps to Reproduce**
* Open Postman in browser or macOS application.
* Attempt to import the following URL in a workspace: http://redfish.dmtf.org/schemas/v1/openapi.yaml

**Screenshots or Videos**
<img width="332" alt="Screen Shot 2021-06-22 at 4 54 13 PM" src="https://user-images.githubusercontent.com/791000/122998105-7d281780-d361-11eb-9474-6288c5a379d0.png">

**Environment Information**

 - Platform Type:  app and browser
 - Postman Version: Version 8.6.2 (8.6.2)
 - Operating System: macOS

**Additional Context**
No logs appear in the console.

**Comment by rochanram** [comment]
Tried this issue and it shows the same msg as shown above but it imports the schema.

![image](https://user-images.githubusercontent.com/41307588/123020938-fcc8dd00-d387-11eb-9a49-b0263bf37890.png)

**Comment by VShingala** [comment]
@micahhausler This should be fixed now. Since the collection generated from this definition is on a larger side, Import process may take a bit of time but collection will be created from the provided definition. Feel free to reopen this issue if you face any further problems with it.
