### ISSUE TITLE
Postman - Pre-Request - crypto.js is not producing the correct result when run through the pre-request script

### ISSUE THREAD

**Issue by johnnavarra** [a85/POSTMan-Chrome-Extension#1005]
I'm running this as my script:
// Import the CryptoJS library with jQuery
$.getScript("http://crypto-js.googlecode.com/svn/tags/3.1.2/build/rollups/sha256.js", 
function() 
{

   // Access your env variables like this
   //  var str = STRING;

   // Use the CryptoJS script you imported
   var encryption = CryptoJS.SHA256(str).toString();

   //set output
   postman.setEnvironmentVariable('encryption',encryption );
});

This is the string to be decoded:
ZatJOYFLEZ5zTF-G_VLoZVeWHxSETM2Jkkf1428934076

when I run that through the script i get:
66c61ffbefdf75f16023beb100a1eb6e0658d7356c82dd732d6a0f601bcd03a4
(this is wrong.)

When I run it through the same string through the script manually through an offline web page I get:
0882a0c178503e5de905b5de3eb96c839fc47856e1f5576edfc4673902d18f56
this is correct.

Why is  postman returning something else?

**Comment by johnnavarra** [comment]
It looks like within the postman only, it won't pass/consider my assemble variable as a variable. If I assemble the javascript separately in an html document, the corresponding code looks like it works correctly. (see attached)

This is what I'm investigating: I'm taking three variables to make an encoded signature for my pre-request. Hmac isn't used and encoding to base64 isn't needed.

I've simplified the request to make it easier to read. 
This is the original request using variables. assemble is the request to be hashed. It is constantly moving due to the use of the UTC component in the string. 

When I use SHA256 to create the hash using the variable, I can see that the value changes on each request which is expected, however the resulting hash is wrong. You can verify the value of the hash using an online tool or creating your own using the library. 

// Import the CryptoJS library with jQuery
$.getScript("http://crypto-js.googlecode.com/svn/tags/3.1.2/build/rollups/sha256.js", 
function() 
{
    var utcDate = Math.floor(new Date().getTime() / 1000);
    postman.setEnvironmentVariable("DateUTC", utcDate);

```
var assemble = ("{{publicKey}}"+"{{privateKey}}"+utcDate);
postman.setEnvironmentVariable("assemble", assemble);

var encryption = CryptoJS.SHA256(assemble).toString();
postman.setEnvironmentVariable("Signature", encryption);
```

});

In this request, I've explicitly made the value to be hashed from the contents of the assemble variable. In this case, the resulting hash is as expected. 

// Import the CryptoJS library with jQuery
$.getScript("http://crypto-js.googlecode.com/svn/tags/3.1.2/build/rollups/sha256.js", 
function() 
{
    var utcDate = Math.floor(new Date().getTime() / 1000);
    postman.setEnvironmentVariable("DateUTC", utcDate);

```
var assemble = ("{{publicKey}}"+"{{privateKey}}"+utcDate);
postman.setEnvironmentVariable("assemble", assemble);

var encryption = CryptoJS.SHA256("publicKeyprivateKey1428939563").toString();
postman.setEnvironmentVariable("Signature", encryption);
```

});

My only theory is that the there is some kind of transformation when the contents of assemble are fed into the SHA256.js

**Comment by brodyd** [comment]
Perhaps the use of {{ }} variables is the problem.  These only work as replacements in the URL and Header section.
Any javascript sections need to use enviroment["publicKey"](for example)

**Comment by johnnavarra** [comment]
yup you're right. i need to close this.

On Wed, May 6, 2015 at 11:37 PM, Brody Dunn notifications@github.com
wrote:

> Perhaps the use of {{ }} variables is the problem. These only work as
> replacements in the URL and Header section.
> Any javascript sections need to use enviroment"publicKey"
> http://for%20example
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/a85/POSTMan-Chrome-Extension/issues/1005#issuecomment-99701564
> .

## 

AIM: obliviouslyaware
ICQ: 5147787
googletalk

**Comment by johnnavarra** [comment]
@brodyd I was using the variables wrong like you said.
as a side note, including scripts such as cryptoxx.js  is more efficient when included in the sandbox up front rather than calling the script as needed in my example..

**Comment by IAmBlackHacker** [comment]
use CryptoJS.SHA256(str.toString()).toString();
