### ISSUE TITLE
Find and Replace issues

### ISSUE THREAD

**Issue by VaishnaviChallaPostman** [a85/POSTMan-Chrome-Extension#10058]
**Describe the Issue**

1.Find & Replace > Collections > Open in Builder > {Select anything in right pane}, doesn't open up as expected. 

2.Find and replace filter results having "Open in builder" option if "Request Name" contains the find string, but doesn't if "Folder Name" contains the find string. 

**Steps to Reproduce**

1.Screen record of replication :  https://www.loom.com/share/cc42984d910c44129198ebbb32e09a68 
2.
![image](https://user-images.githubusercontent.com/76939396/122972563-e9306d00-d3ad-11eb-9c28-47ccf01cb8a4.png)

**Additional Context**

This request is already being tracked internally. Raising this here to track publicly.

**Comment by timbochamp** [comment]
Hi @VaishnaviChallaPostman , can you break the second point into its own issue please? Let's track the first one here where they're distinct issues

**Comment by shubhbhargav** [comment]
Closing the issue given that the fix has been shipped out. @VaishnaviChallaPostman Please feel free to let us know if the issue still persists at your end.
