### ISSUE TITLE
No error message when uploading a profile picture above the size limit

### ISSUE THREAD

**Issue by carrrson** [a85/POSTMan-Chrome-Extension#10065]
**Describe the Issue**
When uploading a picture that above the size limit, I did not receive a message that it had exceeded the max size, and it appeared that the upload was successful. I think I had received this type of message for other pictures I tried to upload, so it was unclear why the picture was not persisting on my workspace page until I thought to look at the image size myself.

**Steps to Reproduce**
1. On profile page, hover over profile picture placeholder and click the edit pencil.
2. Upload a picture that exceeds the size limit.
3. It will look like the process completed successfully, but navigating to another page will show that the picture was not persisted. (I also tried this on a couple different days to make sure the system wasn't just taking a long time to update).

**Screenshots or Videos**

I've attached a video showing the process. For reference, the picture I was using in this demo was 957KB

**Environment Information**

 - Platform Type: Postman for Chrome
 - Postman Version: Not sure where to find this on the web version
 - Operating System: Mac OS Catalina 10.15.3

**Additional Context**

https://user-images.githubusercontent.com/20145532/123119744-cb94ef00-d411-11eb-8019-0e7f9357ea11.mov

Sorry for the weird crop on the video, let me know if I can provide any other info. Thank you!

**Comment by ArjunSingh-PM** [comment]
This issue has been resolved.

**Comment by Memoyuna** [comment]
https://dl.pstmn.io/download/version/10.12.9/postman-win64.zip
