### ISSUE TITLE
Inconsistent export and import behavior of cURL for form-data requests

### ISSUE THREAD

**Issue by feeeei** [a85/POSTMan-Chrome-Extension#10068]
**Describe the Issue**
Requests of the form-data category are exported to cURL format, which adds quotes to the value.

But this cURL is imported by raw text, which brings in this quotation mark

**Steps to Reproduce**
1. Export request selection cURL format
2. Import cURL requests via raw text format

**Screenshots or Videos**
![image](https://user-images.githubusercontent.com/8032930/123198904-7bd12900-d4e0-11eb-8aa0-cbccdfd786df.png)
![image](https://user-images.githubusercontent.com/8032930/123198983-9e634200-d4e0-11eb-86d1-616321ed4d67.png)
![image](https://user-images.githubusercontent.com/8032930/123199007-aa4f0400-d4e0-11eb-9c11-4c2fa39efd45.png)

**Environment Information**

 - Platform Type: Postman desktop
 - Postman Version: 8.6.2
 - Operating System: MacOS

**Additional Context**

**Comment by VShingala** [comment]
@feeeei This issue is now fixed with the latest postman app v9.1.2.

**Comment by feeeei** [comment]
@VShingala Thx very much
