### ISSUE TITLE
Request OAuth2 "Authorization Code" with additional url-parameter e.g. login_hint=username

### ISSUE THREAD

**Issue by jwausle** [a85/POSTMan-Chrome-Extension#10064]
As user I want to request a token over a OAuth2 (OpenID) endpoint (grant_type=Authorization_code) where the login form has a pre-filled username.

```
GET https://domain/auth/realms/relam/protocol/openid-connect/auth?response_type=code&state=&client_id=clientid&scope=openid&redirect_uri=https%3A%2F%2Foauth.pstmn.io%2Fv1%2Fcallback&login_hint=username
```

The idea is that the login form(username, password) can pre-fill the username with the given `login_hint`.  This is a feature of [OpenID](https://openid.net/specs/openid-client-initiated-backchannel-authentication-core-1_0.html#auth_request). 

I found no solution to add `login_hint=username` as additional url parameter in the Postman App (v.8.6.2)

<img width="515" alt="Bildschirmfoto 2021-06-23 um 15 17 36" src="https://user-images.githubusercontent.com/1932517/123103304-28a29c00-d436-11eb-873c-b37b2a27985a.png">

**Comment by giridharvc7** [comment]
Can you try adding `login_hint` to your `Auth URL` directly?

**Comment by jaredtbates** [comment]
I think this can be closed now that we have these options available:
<img width="571" alt="image" src="https://github.com/postmanlabs/postman-app-support/assets/2905521/e467c2ff-afe7-4654-b446-6fa7b6ba54cf">

**Comment by abhijeetborole** [comment]
Hey @jwausle, This is now available under the `Advanced` section under OAuth2.0. With these changes, you can now add params to the headers, body and URL for token and refresh requests in the auth code flow. You can also add query params to the auth request. Let us know if you have any issues.

![CustomOauthLow](https://user-images.githubusercontent.com/9638586/232849656-63e0297a-7bc3-4472-8ff3-04cf2f5df95e.gif)
