### ISSUE TITLE
Documentation only shows one Authorization method at the operation level, although OpenAPI allows for defining multiple security types.

### ISSUE THREAD

**Issue by CarrieRaglan** [a85/POSTMan-Chrome-Extension#10076]
REST APIs support several authentication types, documented within OpenAPI through the security schemes. Security is an array of hashmaps, where each hashmap contains one or more named security schemes.

Postman's documentation only shows one Authorization method, and also does not display the securities name or description.
https://spec.openapis.org/oas/v3.0.3#fixed-fields-22

**Steps to Reproduce**
Create documentation from OpenAPI spec with multiple authentication types, security names and descriptions. The documentation will only show one.

security:

- basicAuth: []
- apiKey: []
- apiKey2: []

![image](https://user-images.githubusercontent.com/63308530/123672958-c3afc300-d7f4-11eb-98f4-cef23ed59c2d.png)
![image](https://user-images.githubusercontent.com/63308530/123673007-cc07fe00-d7f4-11eb-82ac-e01554b010a4.png)
[petStoreSecutitySchemes.zip](https://github.com/postmanlabs/postman-app-support/files/6727913/petStoreSecutitySchemes.zip)

**Comment by Raja-Simha** [comment]
Hi @CarrieRaglan, thanks for your input here. We'll see if this can be picked up along with an initiative to enriching documentation with schema information.

**Comment by Raja-Simha** [comment]
@CarrieRaglan As shared with you over email, you can now generate documentation from your OpenAPI 3.0 schema. You can try out the feature as explained [here](https://learning.postman.com/docs/publishing-your-api/documenting-your-api/#generating-api-documentation). Schema documentation supports multiple security options defined for each operation. 

As we make further improvements, we'd love your feedback on API schema documentation. Do share your thoughts with us once you have tried it out. If you'd like to connect and discuss over a call, feel free to schedule one [here](https://calendly.com/raja-postman/office-hours).

**Comment by CarrieRaglan** [comment]
I'm still not seeing this in the Published Documentation that Postman generates?
