### ISSUE TITLE
Run Documentation in Postman not working since Postman v8.7.0 release

### ISSUE THREAD

**Issue by thomaslaurent-ma** [a85/POSTMan-Chrome-Extension#10075]
Hi,

Since the latest Postman update, I can't run the documentation in Postman desktop app.

Thank you for checking

**Comment by postman-staff** [comment]
Hi @mastolo,

Sorry for the hassle here, but happy to help! Could you kindly provide a bit more context/detail about the issue you're reporting? Are you referring to the Run in Postman (https://learning.postman.com/docs/publishing-your-api/run-in-postman/introduction-run-button/) no longer working for v8.7.0? Do you have any URL to a published collection for which you're observing this behaviour? Or any screenshots of the issue? The more information you can provide, the better we'll be able to assist here. Thank you, and looking forward to your response!

via @SabriH10 | Postman Support

**Comment by postman-staff** [comment]
@mastolo Just checking back to see if the issue persists?

Please share the requested details as in my earlier response and we will check this further.

via @Raj-postman | Postman Support

**Comment by thomroger** [comment]
Hi @postman-support, 

Here's the url : https://documenter.getpostman.com/view/8153187/SVfKwAcs?version=latest

Thanks

**Comment by postman-staff** [comment]
@thomroger Thank you for sharing the file. I am able to replicate this issue from my end.

We will check this further and update the thread as soon as we have any further details. Appreciate your patience!

via @Raj-postman | Postman Support

**Comment by postman-staff** [comment]
@thomroger I just wanted to let you know that the issue has been escalated and our team is looking into the same, and I haven't forgotten about you. I'll be sure to provide you with an update here as soon as I get one :)

Feel free to let us know if you have any questions or concerns.

via @Raj-postman | Postman Support

**Comment by thomroger** [comment]
Hi @postman-support,

Any news from this issue ? 
Thom

**Comment by postman-staff** [comment]
Sorry, not yet @thomroger - I'm waiting for an update from the team on this and will let you know as soon as I hear back from them.

via @Raj-postman | Postman Support

**Comment by postman-staff** [comment]
@thomroger Just received an update from the team on this - If possible can you try to unpublish and republish this collection with the same environment and let us know if that helps?

If you do not have access to the original collection, you may try duplicating/ forking the collection and then try publishing the same. Once done try importing the collection/Environment via the "Run in Postman" button and see if that works.

via @Raj-postman | Postman Support

**Comment by thomroger** [comment]
Hi @postman-support,
Everything seems to be working. 
Many thanks,
Thom

**Comment by postman-staff** [comment]
@thomroger Awesome! Glad to know that helped :)

via @Raj-postman | Postman Support
