### ISSUE TITLE
Release 2.0.17 downgraded lodash to 1.3.1

### ISSUE THREAD

**Issue by shawnmarie-zz** [a85/POSTMan-Chrome-Extension#1007]
I have a test suite that is using lodash functions from 3.6.0 that worked yesterday prior to the postman 2.0.17 update.

**Comment by a85** [comment]
@shawnmarie Are you still facing this? Will close this issue otherwise.

**Comment by shawnmarie-zz** [comment]
This has been resolved. Thank you!
