### ISSUE TITLE
ERROR: Couldn’t add documentation to the API Could not generate collection. 

### ISSUE THREAD

**Issue by mtaylorSF** [a85/POSTMan-Chrome-Extension#10085]
**Error Message: Maximum call stack size exceeded when generating Documentation from API**

Error message seen when generating Documentation from an API

**Message Shown:**
```
Couldn’t add documentation to the API
Could not generate collection. Error Message:Maximum call stack size exceeded
```

**Steps to Reproduce**
1. From API - add your graqhql schema (format: GraphQL SDL)
2. Advance to Develop and click "Add Documentation", then Create New
3. Provide a name and then click "Create Documentation" 

**Screenshots or Videos**
![Screen Shot 2021-06-30 at 5 02 49 PM](https://user-images.githubusercontent.com/808523/124045717-1c35ba80-d9c5-11eb-9973-b04e41b16cf5.png)

**Environment Information**

 - Platform Type:  App
 - Postman Version:  8.7.0
 - Operating System: Mac 10.14.6

**Comment by VShingala** [comment]
@mtaylorSF Could you also share the GraphQL API schema that you're working with? Alternatively, You can also mail it to us at help@postman.com and link this GitHub issue link in the mail. It'd help us out in debugging the exact issue.

**Comment by VShingala** [comment]
@mtaylorSF We have fixed a similar issue over here https://github.com/postmanlabs/postman-app-support/issues/10266. As there's been no response for some time, I'll close this issue, feel free to reopen this if you're still facing this issue.
