### ISSUE TITLE
Call in collections not in order when using sync app

### ISSUE THREAD

**Issue by jmatthews79** [a85/POSTMan-Chrome-Extension#1008]
When I subscribe to another users collection, the folders and the calls inside the folder are not in the same order. This causes tests to fail when run in the collection runner. You can reorder the folders by closing the app and reopening after subscribing but the calls in the folder dont reorder. We have to manually reorder hundreds of calls.

**Comment by abhijitkane** [comment]
What version of the Sync app are you using? Also, can you mention the name of a folder who's requests are in the incorrect order?

**Comment by jmatthews79** [comment]
Yes sorry. 
Version 2.0.0.61 (packaged)
OS: win
Architecture: x86-32
Native client architecture: x86-64

CollectionOwner: Ann Denner
Collection Subscriber: energycapjared

Collection: ECO 3.3

**Comment by abhijitkane** [comment]
Can you try unsubscribing and resubscribing? The folder order issue was fixed a few versions ago.

Also, are there any errors in the console when you resubscribe? (22fbe35d-2995-da93-289a-ca4e4caf04da)

**Comment by jmatthews79** [comment]
I unsubscribed and subscribed again. Same issue. The folders reorder to the correct order when i close the app and reopen but the calls inside the folder are still out of order. 
Nothing in the console as I resubscribe. I only see a successful delete when I unsubscribe.

**Comment by abhijitkane** [comment]
Is this happening with all folders, or just one of the folders in the ECO 3.3 collection?

Either way, can you send the name of one folder and the order of requests that you're seeing?

If you re-order the requests in one of the incorrectly-ordered folders, then unsubscribe+resubscribe, do you see the new order? I've been trying to reproduce this with our team's collections, but I haven't seen a problem with the folder order yet.

**Comment by jmatthews79** [comment]
Authentication Folder:
Order should be: Login, Logout, Login after logout

Hmm you are right. If I reorder the calls in the folder then unsubscribe and subscribe it stays in the correct order. I guess I can just reorder them manually once if you cannot reproduce. Thank you for your time though, it is much appreciated.

**Comment by abhijitkane** [comment]
We'll look into why the initial folder order wasn't reproduced correctly. I'll keep this thread updated.

**Comment by jmatthews79** [comment]
Okay thanks!

**Comment by jmatthews79** [comment]
Another note. When we import instead of subscribing then the folders are in order but the calls in the folders are out of order.

**Comment by dmillman** [comment]
I lost 7 requests from a collection because of this Sync bug, and I wasn't using any shared collections.

Before the requests disappeared, I did an export, and the dump listed all of my collection's requests in the order, but only actually included one of the requests.
