### ISSUE TITLE
New Integration Request - Azure DevOps Repos

### ISSUE THREAD

**Issue by sim1986** [a85/POSTMan-Chrome-Extension#10087]
**Describe your current workflow**
We write our tests in postman and manually move them into our Azure DevOps repos

**Describe your ideal workflow**
Postman connects to Azure DevOps repo of choice on a branch of choice. From postman changes in tests can be committed to the branch

**Describe alternatives you've considered**
Use a webhook to call a workflow tool to commit the code to the Azure DevOps repo. This is too impractical

**Comment by abhijitkane** [comment]
Duplicate of https://github.com/postmanlabs/postman-app-support/issues/9131
