### ISSUE TITLE
Could you please add ability to grouping folders and request together in structure

### ISSUE THREAD

**Issue by pifpaf1** [a85/POSTMan-Chrome-Extension#10084]
Could you please add ability to grouping folders and request together in structure
i mean groping requests without folder in the middle and folder on top and folder on bottom?
i mean how can i group folders and request in order 1,2,3,4

![Screenshot_27](https://user-images.githubusercontent.com/20091940/123967200-c3fbba00-d9be-11eb-9ead-32c21a67f7c4.png)

**Comment by appurva21** [comment]
Duplicate of [#7052](https://github.com/postmanlabs/postman-app-support/issues/7052)
