### ISSUE TITLE
Can not upload any file inside working dir on Windows, desktop error dialog shows up instead.

### ISSUE THREAD

**Issue by eugeniopacceli** [a85/POSTMan-Chrome-Extension#10081]
**Describe the Issue**
When I try to upload a file to serve as the binary body of a request or as a file input inside some form-data, I get an odd error window and the upload button halts on the loading animation.

**Steps to Reproduce**
0 - On Windows 10;
1 - Rename "%USERPROFILE%\Postman Agent" to "%USERPROFILE%\Postman" so you can have the accessible file upload folder;
2 - Place png file inside "%USERPROFILE%\Postman\files";
3 - Create some new request, go to Body, select binary and then select the image in the file to upload dialog;
4 - Crashes!

**Screenshots or Videos**
[Full video](https://streamable.com/51dfrm)

**Environment Information**

 - Platform Type: Desktop
 - Postman Version: Postman for Web Version 8.7.0-210616-0800
 - Operating System: Firefox 89 / Windows 10

**Comment by eugeniopacceli** [comment]
Each time the upload fails a new folder with random name is created at "%USERPROFILE%\Postman\files".

**Comment by appurva21** [comment]
Hey @eugeniopacceli! Thanks for reporting this. 

We have released a fix for this, you can try it out by updating your Postman Desktop Agent to its latest version ([v0.3.8](https://www.postman.com/downloads/)).

**Comment by eugeniopacceli** [comment]
Cheers!
