### ISSUE TITLE
On Mac OS, postman app consumes a lot of memory

### ISSUE THREAD

**Issue by xuxingqiang** [a85/POSTMan-Chrome-Extension#10082]
![image](https://user-images.githubusercontent.com/28783649/123894619-0dcdab80-d991-11eb-807e-fe4151a2bb32.png)

As shown in the figure above, the memory usage is close to 1g. I don't think the memory is released after the tab is closed

**Comment by jviotti** [comment]
What version of Postman are you running?

**Comment by xuxingqiang** [comment]
> What version of Postman are you running?

Sorry, I haven't used my PC for development in months. The software version has been updated during the period, so I am not sure which version it is at the moment. But I think this problem exists in various versions since then. I hope the development team can continue to pay attention to the memory usage problem during use, I think, it should be able to reproduce

**Comment by jviotti** [comment]
Merging this with https://github.com/postmanlabs/postman-app-support/issues/4687
