### ISSUE TITLE
Clear Previous Response

### ISSUE THREAD

**Issue by Redhunt2013** [a85/POSTMan-Chrome-Extension#10092]
**Is your feature request related to a problem? Please describe.**
A simple feature request to add a "Clear Response" option.  This helps me greatly when I keep running requests in Postman. I often make the mistake of not sending the request, and I thought I did send the request, and I accidentally look at the response from the previous request, potentially skewing my tests.

**Describe the solution you'd like**
In the response pane, similar to the "Save Response" option on the far right corner, I would like to have a "Clear Response" option.

**Describe alternatives you've considered**
Relaunch the application to clear the response window—very inefficient way.

**Additional context**
If I relaunch the Postman window, the responses are cleared. So I believe it wouldn't be super difficult to implement a simple `clear()` function when the application is running.  Feel free to vote this feature request down.  I thought I would get this ticket in, so some eyes can read the problem we face without a straightforward option.

**Comment by Anuragtech02** [comment]
Hey, @giridharvc7 I'd like to give this try! Can I work on it?

**Comment by 14geronimo** [comment]
This would come quite handy for me when I'm demonstrating executing a query in front of an audience: I will have run the requestjust before presenting to make sure everything was hunky dory; I want to re-execute it “live” without the previous run showing in the Response pane already.

My suggestion for implementation would be to add a third icon "Clear" to the right of the "Copy" and "Find" icons in the response page (below the "Save Response" drop-down).

This topic is also discussed on the Community forum: https://community.postman.com/t/can-i-clear-the-response-without-running-another-request/22866

**Comment by LZapiter** [comment]
Hello, so what happened here? It's been a year and I just want to know if there are any updates, or at least any plugins that I can install for this feature?

**Comment by Redhunt2013** [comment]
Coincidentally, I was taking a look at this issue yesterday, hoping to see some updates but no updates yet.

**Comment by samuelmendezfx** [comment]
I'd love to see this feature implemented

**Comment by bayucandra** [comment]
Was quite a long time wondering that this feature exist. I thought it was just me who can't find this simple feature, was expecting there is a button to clear the response :smile:

**Comment by Redhunt2013** [comment]
@giridharvc7 I am sure you have a lot going on in your space.  Could we ask to include this useful feature in the product?  This will definitely help users.

**Comment by J-Wick4** [comment]
I'm here because I needed clarification as to why there was no way to clear responses. I blew 10 minutes trying to find the answer. Imagine the global collective waste of developers' time of also looking for this answer. ChatGPT said a blue button was next to the "Save Response," but that was a lie.

**Comment by san-ki** [comment]
Anybody working on this?

**Comment by giridharvc7** [comment]
Yes, we'll keep you posted on this. Watch out this space for updates.

**Comment by san-ki** [comment]
I was looking for a open source contribution. do you have any unassigned
open issue that I can give a try?

**Comment by giridharvc7** [comment]
We've released this improvement along with the latest version of Postman (v10.12) - this update is being rolled out and you will be getting it soon. 
We appreciate the patience, and thank you for the feedback. 
![clear](https://user-images.githubusercontent.com/1040583/225614099-3c86cbe7-a0ea-4500-babe-3a1ac3b58eae.gif)

**Comment by san-ki** [comment]
Thank you for the update. This will help a lot.

**Comment by giridharvc7** [comment]
@tomsmith1204  This feature is currently available only when you are signed in.

**Comment by tomsmith1204** [comment]
[giridharvc7](https://github.com/giridharvc7) - thanks for the quick reply. I had just figured that out and deleted my comment before I saw that you had replied.

**Comment by Redhunt2013** [comment]
Thank you, @giridharvc7 and team, for working on this.  This will definitely help users.

**Comment by shroomlife** [comment]
Is there a way to do this programatically within Test scripts?

Like pm.clearResponse()

Is ask cause I would love to have the possibility that the reponse is never shown. I just use a request called "Get Token" that is saving atoken into an environment variable. But when streaming the token can be seen a short time. Is there a way to hide the response?

**Comment by Redhunt2013** [comment]
Thanks to the Postman labs team for working on my request.  This small UI enhancement improves my experience on the tool and encourages to submit more ideas.

**Comment by DSchau** [comment]
@Redhunt2013 so glad to hear! @giridharvc7 and team work hard to keep improving, so we'd love to hear your ideas!

If you'd like to schedule some time with me, we'd love to learn more about how we can improve: https://app.reclaim.ai/m/dschau/quick-meeting

Otherwise, we're just a GitHub issue away!

**Comment by ygeretz** [comment]
> Is there a way to do this programmatically within Test scripts?
> 
> Like pm.clearResponse()

I would also love to see a programmatic option for this. My use case is slightly different. I am demoing a series of calls in Postman. I'd like to clear the previous response programmatically in the Pre-request script so that the output of each call is not "tainted" by the output from the previous call(s). Yes, this can be done manually, but it would be so handy to be able to script this and forget it. Thanks!
