### ISSUE TITLE
The Runner is going to infinite loop when the user run the collection of 3 request

### ISSUE THREAD

**Issue by Rabindra184** [a85/POSTMan-Chrome-Extension#10091]
**Describe the Issue**

The Runner is going to infinite loop when running the collection in a sequence using postman.setNextRequest() method

**Steps to Reproduce**

Step-1: Create a collection and then add 3request with Tests as given below.
![image](https://user-images.githubusercontent.com/46239257/124268519-3bfce800-db57-11eb-91df-b2c4a9917efe.png)
![image](https://user-images.githubusercontent.com/46239257/124268608-5cc53d80-db57-11eb-9efe-8ed8f690a845.png)
![image](https://user-images.githubusercontent.com/46239257/124268750-8c744580-db57-11eb-8561-90d72aa72bf0.png)
Step-2:Now run the collection
![image](https://user-images.githubusercontent.com/46239257/124268811-a9a91400-db57-11eb-9dfc-87dc6fddf0e5.png)
Step-3:It should run in the sequence. But is going in infinite loop
![image](https://user-images.githubusercontent.com/46239257/124269054-03114300-db58-11eb-8f27-65ef55d7ff28.png)

**Screenshots or Videos**

**Environment Information**

 - Platform Type: API
 - Postman Version: Postman v8.7.0
 - Operating System: Windows 10

**Additional Context**

**Comment by DannyDainton** [comment]
Hey @Rabindra184 

It's difficult to see the saved state of the different request tabs you have open in the images that you have provided - This saved state impacts what is run in the Collection Runner. 

Did you previously have something in the Tests section of the Login Request?

Are you able to share the collection file with us so that we can see what's contained in the Collection?

**Comment by Rabindra184** [comment]
[WithWorkflow.postman_collection.zip](https://github.com/postmanlabs/postman-app-support/files/6764144/WithWorkflow.postman_collection.zip)
I have attached file collection file .Please check and let me know.

**Comment by DannyDainton** [comment]
I'm unable to create this issue in the latest version of the platform. If this is still a problem, please create a new issue with the relavent contextual information.
