### ISSUE TITLE
[Postman API] Collection Update endpoint returns 500 error

### ISSUE THREAD

**Issue by taehoshino** [a85/POSTMan-Chrome-Extension#10098]
**Describe the Issue**
Using Postman [API PUT endpoint to update collection](https://www.postman.com/postman/workspace/postman-public-workspace/request/12959542-a42a1615-4b04-44e9-b2ea-e94729d5f4d6) returns a 500 response with the message "Something went wrong with the server" but the collection actually shows that it was updated a few seconds later.

**Steps to Reproduce**
1. Create a Test collection
2. Copy collection id to use it in Update Collection Request
3. Copy and Paste text from json file into PUT Endpoint Body
4. Update the collection name
5. Run Request
6. It should take a bit to run and then return a 500
7. After a few seconds notice collection gets updated

**Additional Context**
This is filed by Product Support and the issue has already been internally tracked. Filing here for public tracking purpose.

**Comment by davidespihernandez** [comment]
Closing this ticket as we actually have tests in place for this endpoint and it works properly. Perhaps it was a punctual error.
