### ISSUE TITLE
SOAP Mock Server reply do not match the correct example response made in the collection

### ISSUE THREAD

**Issue by gagarine** [a85/POSTMan-Chrome-Extension#10093]
**Describe the Issue**
From a SOAP collections I created a mock server. When I run the example request the mock server always reply with the same answer. For SOAP, It's not very clear how the match is done in the collection between request and example answer.

**Steps to Reproduce**

- Create a collection with two post request method
- Create an example for each
- Mock the SOAP server
- Try to query both post method. 

It always return the same response.

I tried to add a SOAPAction  in header and use the "action="#createSubscriber"" or action="createSubscriber" or ...
<img width="1164" alt="Screenshot 2021-07-02 at 18 44 49" src="https://user-images.githubusercontent.com/164074/124305587-969d4080-db65-11eb-8095-5857d40a8d6f.png">

But it always return the getSubscriberResponse response
<img width="999" alt="Screenshot 2021-07-02 at 18 44 31" src="https://user-images.githubusercontent.com/164074/124305554-8c7b4200-db65-11eb-86b5-c2580c6efac5.png">

How it suppose to works?

**Comment by alozta2** [comment]
I can confirm. When you create a mock server out of some collection containing xml examples you only receive one response for any requests.

Here's a simple collection:
`{
	"info": {
		"_postman_id": "",
		"name": "tmp-collection-xml",
		"schema": "https://schema.getpostman.com/json/collection/v2.1.0/collection.json"
	},
	"item": [
		{
			"name": "true",
			"request": {
				"method": "POST",
				"header": [],
				"body": {
					"mode": "raw",
					"raw": "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n<soap:Envelope xmlns:soap=\"http://schemas.xmlsoap.org/soap/envelope/\">\n    <result>test-success</result>\n</soap:Envelope>",
					"options": {
						"raw": {
							"language": "xml"
						}
					}
				},
				"url": {
					"raw": "{{baseUrl}}/test",
					"host": [
						"{{baseUrl}}"
					],
					"path": [
						"test"
					]
				}
			},
			"response": [
				{
					"name": "true",
					"originalRequest": {
						"method": "POST",
						"header": [],
						"body": {
							"mode": "raw",
							"raw": "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n<soap:Envelope xmlns:soap=\"http://schemas.xmlsoap.org/soap/envelope/\">\n    <result>test-success</result>\n</soap:Envelope>",
							"options": {
								"raw": {
									"language": "xml"
								}
							}
						},
						"url": {
							"raw": "{{baseUrl}}/test",
							"host": [
								"{{baseUrl}}"
							],
							"path": [
								"test"
							]
						}
					},
					"_postman_previewlanguage": null,
					"header": null,
					"cookie": [],
					"body": "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n<soap:Envelope xmlns:soap=\"http://schemas.xmlsoap.org/soap/envelope/\">\n    <result>success</result>\n</soap:Envelope>"
				}
			]
		},
		{
			"name": "fail",
			"request": {
				"method": "POST",
				"header": [],
				"body": {
					"mode": "raw",
					"raw": "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n<soap:Envelope xmlns:soap=\"http://schemas.xmlsoap.org/soap/envelope/\">\n    <result>test-fail</result>\n</soap:Envelope>",
					"options": {
						"raw": {
							"language": "xml"
						}
					}
				},
				"url": {
					"raw": "{{baseUrl}}/test",
					"host": [
						"{{baseUrl}}"
					],
					"path": [
						"test"
					]
				}
			},
			"response": [
				{
					"name": "fail",
					"originalRequest": {
						"method": "POST",
						"header": [],
						"body": {
							"mode": "raw",
							"raw": "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n<soap:Envelope xmlns:soap=\"http://schemas.xmlsoap.org/soap/envelope/\">\n    <result>test-fail</result>\n</soap:Envelope>",
							"options": {
								"raw": {
									"language": "xml"
								}
							}
						},
						"url": {
							"raw": "{{baseUrl}}/test",
							"host": [
								"{{baseUrl}}"
							],
							"path": [
								"test"
							]
						}
					},
					"_postman_previewlanguage": null,
					"header": null,
					"cookie": [],
					"body": "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n<soap:Envelope xmlns:soap=\"http://schemas.xmlsoap.org/soap/envelope/\">\n    <result>fail</result>\n</soap:Envelope>"
				}
			]
		}
	],
	"event": [
		{
			"listen": "prerequest",
			"script": {
				"type": "text/javascript",
				"exec": [
					""
				]
			}
		},
		{
			"listen": "test",
			"script": {
				"type": "text/javascript",
				"exec": [
					""
				]
			}
		}
	],
	"variable": [
		{
			"key": "baseUrl",
			"value": "",
			"disabled": true
		},
		{
			"key": "baseUrl",
			"value": ""
		}
	]
}`

My guess is postman fails to detect idential request is made and returns a default response?

**Comment by jjduarte** [comment]
Hi, I'm running the exact same issue. 

What I've found so far is that you can use the header `x-mock-match-request-headers` in the request and set it to `soapaction` alongside  with a `SOAPAction` header that contains the actual action. The `SOAPAction` header must be set in the examples request headers as well. 

Even though this works for me, I was expecting to find a way to match headers without having to send the custom `x-mock-match-request-headers` in the request. My API will call this Mock Server and I dont want it to send custom headers. It would be nice to have a way to set `x-mock-match-request-headers` or `x-mock-match-request-body` as a default behaviour when creating a Mock Server.

**Comment by Dhembla** [comment]
Hey Guys
As mentioned by @jjduarte you can use `x-mock-match-request-headers` or `x-mock-match-request-body` to get the expected response from a mock server, but it's always not feasible to add additional headers to your application.
As part of the Postman team, we are working on building a UI-based solution for this and we are targeting to release it by early Q2, 2022 with other major changes to the mock server UI.

**Comment by akshaydeo** [comment]
I am closing this issue for now. We will update this issue with the new UI-based solution when it's out (which will be pretty soon 🕺 ).

**Comment by marek-binkowski-sim** [comment]
Hi @Dhembla @akshaydeo , any news on the aforementioned UI-based solution?
