### ISSUE TITLE
Collection authorization parameter is duplicated in request on save (if other parameters exist)

### ISSUE THREAD

**Issue by endrx** [a85/POSTMan-Chrome-Extension#10094]
When "Query Params" method is used in Authroization in collection: on request save, inherited from collection Authorization parameter is duplicated as ordinary parameter (if other ordinary parameters exist).

1. Create collection
2. Add Authorization to the collection with type "API key"
3. Fill Key, Value fields with something
4. Select "Query Params" in "Add to" field.
5. Add new request to the collection
6. Add something to URL of the request
7. Add additional parameter to the request
8. Press Ctrl+S to save request. Authorization parameter inherited from Collection is duplicates as ordinary parameter.

 - Postman Version: 8.7.0
 - Operating System: Windows 10

**Comment by DannyDainton** [comment]
Hey @endrx 

Thanks for raising this issue, the team are taking a look at this to investigate what's happening.

We'll update this thread once we have some new information. Thanks again 🏆

**Comment by tumbislav** [comment]
I had the same issue and just upgraded to v8.9.1 (Win10). The issue seems to be fixed, I no longer get duplicate API Key parameters.

**Comment by SonNg2k** [comment]
This bug is now fixed in [Postman v8.9.1](https://www.postman.com/downloads/release-notes/):

> Fixed an issue where authorization param were duplicated on saving the request - GitHub #10094

@appurva21 please close this issue now.
