### ISSUE TITLE
Bug about break line (\n) in body when import cURL command.

### ISSUE THREAD

**Issue by PMExtra** [a85/POSTMan-Chrome-Extension#10090]
Import:
```sh
curl 'http://host' \
  --data-raw $'{\n  "foo": "bar"\n}'
```

Expected body:
```plain
{
  "foo": "bar"
}
```

Actual body:
```plain
{n  "foo": "bar",n}
```

Postman App V8.7.0

**Comment by DannyDainton** [comment]
Hey @PMExtra 

Are you able to provide us with more context for this issue, please?

**Comment by PMExtra** [comment]
Sometimes, I copy a request from Chrome Dev Tools and import to Postman.
The body may contains `\n`, but Postman can't import it correctly.

**Comment by akshaydeo** [comment]
@PMExtra, we had pushed a fix to the importer library. Could you check?

Closing this issue, for now, feel free to re-open if the fix doesn't work as expected 🙂
