### ISSUE TITLE
Postman web broken

### ISSUE THREAD

**Issue by MatteoInfi** [a85/POSTMan-Chrome-Extension#10107]
**Describe the Issue**
I am trying to use postman but after login it does not load anything

There are so many error in the console:

```
Uncaught (in promise) Error: BaseConfigurationService.js:10 Uncaught (in promise) Error: ConfigurationService: Could not get config. Key does not exist
```

```
Error: TelemetryService - Init Failed - TelemetryService is already initialized
    at Object.initializeTelemetryService (init.js:50)
    at Object.t.default [as init] (init.js:19)
    at t.default (VM6581 requester-legacy-a375c58e87fb6ef38eae.min.js:2674)
    at parallel.js:31
    at h (eachOfLimit.js:66)
    at p (eachOfLimit.js:50)
    at onlyOnce.js:12
    at parallel.js:36
    at VM6581 requester-legacy-a375c58e87fb6ef38eae.min.js:2674
    at nrWrapper (11378166-3583dd72-10e2-4a8d-bb6b-dca62f733646:10)
```

```
WorkspaceSessionController~getActiveSession: WorkspaceSession not found in db
```

```
ActiveWorkspaceSessionStore: Initial Hydration Failed twice Error: WorkspaceSessionController~getActiveSession: WorkspaceSession not found in db
    at VM6581 requester-legacy-a375c58e87fb6ef38eae.min.js:23
    at nrWrapper (11378166-3583dd72-10e2-4a8d-bb6b-dca62f733646:10)
```

```
MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 model-events listeners added. Use emitter.setMaxListeners() to increase limit
    at d (https://st-ar.cdn.postman.com/platform-ca6823666aef2affabea.min.js:10:30821)
    at l.addListener (https://st-ar.cdn.postman.com/platform-ca6823666aef2affabea.min.js:10:33103)
    at c.s (https://st-ar.cdn.postman.com/platform-ca6823666aef2affabea.min.js:218:56930)
    at Object.subscribeToEventBus (https://st-ar.cdn.postman.com/requester-legacy-a375c58e87fb6ef38eae.min.js:355:1495006)
    at t.default (https://st-ar.cdn.postman.com/requester-legacy-a375c58e87fb6ef38eae.min.js:2651:10070)
    at https://st-ar.cdn.postman.com/platform-ca6823666aef2affabea.min.js:10:61675
    at h (https://st-ar.cdn.postman.com/platform-ca6823666aef2affabea.min.js:10:65899)
    at p (https://st-ar.cdn.postman.com/platform-ca6823666aef2affabea.min.js:10:65803)
    at https://st-ar.cdn.postman.com/platform-ca6823666aef2affabea.min.js:10:70591
    at https://st-ar.cdn.postman.com/platform-ca6823666aef2affabea.min.js:10:61749
    at https://st-ar.cdn.postman.com/requester-legacy-a375c58e87fb6ef38eae.min.js:2682:239839
    at <anonymous>
    at nrWrapper (https://galactic-space-726305.postman.co/workspace/DoctorWorld-Core~999e15b8-e91e-43a2-8f14-5e91f977d34d/request/11378166-3583dd72-10e2-4a8d-bb6b-dca62f733646:10:23890)
```

**Steps to Reproduce**
- Login to postman
- try to load a route

**What I have already tried**
- Logout and login again
- Clear site data, reload
- Logout, clear site data, login again

**Screenshots or Videos**
![postman_broken](https://user-images.githubusercontent.com/67247621/125021720-6560cb00-e0a5-11eb-9eb4-63ca59af673b.png)

**Environment Information**

 - Platform Type: web
 - Operating System: Chrome Version 91.0.4472.114 (Official Build) (64-bit) - Ubuntu 18.04

**Comment by postman-staff** [comment]
Hi @MatteoInfi,

Thank you for reaching out. Few more details to help us check further:

1) When you say "try to load a route" - does it mean you are trying to click on a request or collection here?
2) Do you have any type of VPN or proxy in use that could impede a connection to Postman? If so can you disable them or try switching to another network as a test to see if that affects anything?

via @Raj-postman | Postman Support

**Comment by MatteoInfi** [comment]
Hello

1. trying to click on a request
2. No VPN or proxy

**Comment by postman-staff** [comment]
@MatteoInfi Thank you!

This looks very similar to an ongoing issue we are tracking internally. I believe this happens randomly in every other workspace right? If possible could you please share the HAR logs to us by submitting a ticket here: https://postman.com/support

Steps to follow:

1. Go to the Postman Web app: https://go.postman.co/home
2. Open DevTools (View > Developer > DevTools)
3. Reload the app (cmd/ctrl + R)
4. Perform the replication steps (_Clicking on the request_)
5. Go to the “Network” tab in the DevTools and click on the “down” arrow to export the logs.

![image](https://user-images.githubusercontent.com/47771757/125095538-e940a480-e0f1-11eb-960a-dee9d1747f1a.png)

Also, if it's particular to only one workspace or collection, the name and ID of the same would help.

**Note: Subject line of the ticket "Logs for Postman web broken GH #10107"**

via @Raj-postman | Postman Support

**Comment by postman-staff** [comment]
@MatteoInfi Could you please provide us below details by submitting a ticket here: https://postman.com/support to assist you further on this?

via @Raj-postman | Postman Support

**Comment by postman-staff** [comment]
@MatteoInfi PLease share the files if at all the issue persists and we will check this further from there.

via @Raj-postman | Postman Support

**Comment by postman-staff** [comment]
Hi @MatteoInfi,

I'll be closing this next on our end as we haven't heard back from you. If the issue persists, please reach out to us by submitting a ticket here: https://www.postman.com/support ​so we can investigate further.

Have a nice day.

via @Raj-postman | Postman Support
