### ISSUE TITLE
Update JSON linting for trailing commas

### ISSUE THREAD

**Issue by cameron-fgx** [a85/POSTMan-Chrome-Extension#1010]
JSON Linting such as the one used on http://jsonlint.com/ would be really helpful as it shows an error when a trailing comma is passed.

**Comment by cameron-fgx** [comment]
A trailing comma in Postman shows as a "hint" and not a warning or an error, this resulted in me losing an hour of debugging.

JsonLint shows this to be an error:

```
{
    "test": "test",
}

Parse error on line 2:
...test": "test",    }
---------------------^
Expecting 'STRING'
```

**Comment by abhijitkane** [comment]
![screen shot 2016-08-01 at 16 34 15](https://cloud.githubusercontent.com/assets/681190/17292179/cf2b5b14-5805-11e6-86a7-d25c67f64276.png)
@cameron-fgx Are you still seeing this issue in the latest version? The request body editor now shows an error for trailing commas.
