### ISSUE TITLE
[Feature request] Common/Reusable code for all collections

### ISSUE THREAD

**Issue by VicKetchup** [a85/POSTMan-Chrome-Extension#10100]
**Is your feature request related to a problem? Please describe.**
Postman allows to put common code for requests and/or folders on either folder or collection levels, which is really helpful in reducing code duplicating and making it easy to expand on the automation, but if you want to use the same code in multiple collections (there are many reasons why more collections may be created) you have to copy/paste and maintain this code in all places.

**Describe the solution you'd like**
Provide ability to create common/reusable code that can be easily referenced in the collection/folder/request Pre-requests and Test sections. 
With the new Postman UI there can be a new section added on left-hand side called something like "Reusable Tests". These can be Workspace specific, but with ability to share, like collections and environments, and can be loaded into newman through a new option "--reusable-tests". If the collection references a reusable test that is not available, the run should throw an error.

**Describe alternatives you've considered**
Storing code in repositories and/or cloud storage solutions, which then can be loaded through pm.sendRequest() and executed using eval().

**Additional context**
N/A

**Comment by postfrzero** [comment]
Hey folks -- Postman v11 rolled out a few weeks ago with support for the new Package Library, which enables you to reuse code by creating and requiring packages within your scripts. Learn more about the Package Library [here](https://blog.postman.com/postman-v11-plans-packaging-updates-2024/#what-is-the-package-library-for-reusable-scripts) or [here](https://learning.postman.com/docs/tests-and-scripts/write-scripts/package-library/).
