### ISSUE TITLE
Send button is missing.

### ISSUE THREAD

**Issue by esoinila** [a85/POSTMan-Chrome-Extension#10118]
There is no Send-button to to press to actually make the request. Here tested with Twitters Postman samples recent tweets samples.

![image](https://user-images.githubusercontent.com/70575390/125638857-501a7192-341a-49ea-8242-5e9db0a95c9d.png)

**Steps to Reproduce**

![image](https://user-images.githubusercontent.com/70575390/125639217-afdc4818-8d82-4c8b-a58e-e5898e1546a4.png)
**Environment Information**

 - Platform Type: Application
 - Postman Version: Latest (see pic)
 - Operating System: Win10Pro

**Comment by DannyDainton** [comment]
Hey @esoinila 👋🏻 

This is the `example` of the request, it's used in the documentation and for setting responses for the Mock Servers.

The `GET Recent search` request looks like the one you would need.

**Comment by esoinila** [comment]
I am not sure what you are saying so I am going to show it with images:
![Bug1](https://user-images.githubusercontent.com/70575390/125644543-c8d6025e-a905-4a57-a350-f7d0814f6017.png)
![Bug2](https://user-images.githubusercontent.com/70575390/125644552-90e16c48-758e-433e-a8e8-7066c22089b0.png)
See here circled in red is where I expect to find the send button. In previous old test I see it (included for reference ... no bug of missing button in that image). With longer twitter query the blue send button is not there.

**Comment by esoinila** [comment]
Oh that was confusing UI (should be marked somehow with greyed out button etc ... looks so much like UI Glitch). Thanks for quick reply.

**Comment by DannyDainton** [comment]
The first image is an `example` tab (The tab icon is different to an HTTP method). You can see that highlighted on the left, under the actual request. You would use this to create an example request for your documentation or you would use these with Mock Servers as the request to a matching request.

The second image is an actual HTTP request, which has the `Send` button. Much the same as if you were to open a new request tab.

More information on Mocks and Documentation can be found here:
- https://youtu.be/n_7UUghLpco
- https://youtu.be/XNVo9WkCoak?t=216

**Comment by DannyDainton** [comment]
I'm going to close this is out for now. I have made an internal request with our design team to see how we can improve this user experience.

Thanks for raising the issue. 🏆
