### ISSUE TITLE
Postman Not converted as required during code conversion

### ISSUE THREAD

**Issue by Iatbzh** [a85/POSTMan-Chrome-Extension#10121]
**Describe the Issue**
Not converted as required during code conversion

**Steps to Reproduce**

For example, I remove the user agent from the header, and I do not remove the user agent from the curl in the code conversion

**Screenshots or Videos**

![image](https://user-images.githubusercontent.com/28798107/125716534-d05c615d-55be-440b-8245-2a6a094c8f9f.png)
![image](https://user-images.githubusercontent.com/28798107/125716719-93a93a9b-d361-441e-b1e6-13a206c500f1.png)

**Environment Information**

 - Platform Type: Windows
 - Postman Version:8.8.0
 - Operating System:Winodows10

**Additional Context**

**Comment by DannyDainton** [comment]
Hey @Iatbzh 

Could you please update the issue with additional steps to reproduce the issue? It's a little difficult to understand what's happening here, with the steps provided.

**Comment by Iatbzh** [comment]
> 嘿@Iatbzh
> 
> 您能否通过其他步骤来更新问题以重现该问题？通过提供的步骤理解这里发生的事情有点困难。
