### ISSUE TITLE
Feature Request: search collections

### ISSUE THREAD

**Issue by johnpc** [a85/POSTMan-Chrome-Extension#1012]
I'd be awesome if I could search within my collections to find a specific request, or globally search all of my collections.

For example, if I have a request that contains "/users" in one of my collections, I should be able to type that in and filter down to only show requests that contain that string

**Comment by johnpc** [comment]
This is implemented in the standalone app, but not on the web page

**Comment by abhijitkane** [comment]
The web-page (legacy app) will likely be phased out by Google soon, and is not being actively developed anymore. This repository continues to serve as an issue tracker, though.
