### ISSUE TITLE
Pre-request script failing

### ISSUE THREAD

**Issue by dmtomczyk** [a85/POSTMan-Chrome-Extension#10125]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

**Postman pre-request script GET request is failing even when the same request succeeds as a 'proper' postman request.**

I have a GET endpoint on my API (Node, Express, NGINX) that is used for returning a JWT for a given user. This request functions properly in several applications and postman proper (not a pre-request script). However, when I try to make the same request as a pre-request script it fails. My ignorant suspicion is a possible issue with Content-Length.

Even when I use the result of the following code execution and try using that for my pm.SendRequest call, it still fails.
```js 
console.log(JSON.stringify(pm.request));
``` 
The request hangs for a while before outputting this to the console:

![image](https://user-images.githubusercontent.com/26173452/125815931-d0f3ea30-d307-460b-9251-eb808ac08ebe.png)

**My Assumption:**
Server-side, I don't even see the request being made from the output of monitoring npm start server.js. 
However, checking /var/log/nginx/access.log shows a 400 error for these pre-request script requests. 

When I remove Content-Length from my request it still fails, but instead of a socket hangup, it fails immediately, and the server's response tells me that I've passed in an invalid username/password, which is the expected output when there is no username or password, implying (to me at least), that the server is unable to read the requests body and that the request is somehow malformed.

### Steps To Reproduce

1. Create my GET request with Postman's UI
2. Add a test case to the request and invoke `console.log(JSON.stringify(pm.request));`
3. Paste the result of that output into `pm.sendRequest(previousOutput)` inside of a pre-request script
4. Execute any arbitrary request in the collection

### Screenshots or Videos

Note: The collapsed section in the image is the Host, which is accurate.
![image](https://user-images.githubusercontent.com/26173452/125816732-a6e9fa14-0e27-4de5-942f-1208c6cfc589.png)

### Environment Information

```markdown
- Operating System: 
    - Windows 10 Client
    - Ubuntu Server 18.04 Server
- Platform Type: 
- Postman Version: v8.7.0
```

**Comment by DannyDainton** [comment]
Hey @dmtomczyk 

Does it work if you were to just send the basic details through in the `pre-request script` rather than the full output of `pm.request`?

```javascript
pm.sendRequest({
    url: "https://your_url",
    method: 'GET',
    header: {
        'Content-Type': 'application/x-www-form-urlencoded'
    },
    body: {
        mode: 'urlencoded',
        urlencoded: [
            { key: "username", value: "USERNAME" },
            { key: "password", value: "PASSWORD" }
        ]
    }
}, function (err, res) {
    console.log(res.json());
});
```

**Comment by dmtomczyk** [comment]
Hey @DannyDainton, thanks for the prompt reply.

Unfortunately, that doesn't work either. A console.log shows `req.body = { }`

**Comment by DannyDainton** [comment]
In the Postman Console, are you seeing that async request being sent? 

You shouldn't need to console log anything as it will just be placed in there like the main request.

**Comment by dmtomczyk** [comment]
@DannyDainton Ah, sorry. My message was really unclear.

I've got this on my api route, server-side, that I was mentioning in my previous reply.
```js
console.log("req.body = ", req.body);
```
Server-side, The output of that inside my terminal is
```js
req.body = {}
```

Client-side, I do see the request being sent in the Postman console. The response sent by the server is still indicating an invalid username/password, because I access those properties with `req.body.username`

**Comment by DannyDainton** [comment]
Is the correct request send through the Postman script?

Are you still seeing the issue in the Postman Console or is it now that your API isn't receiving anything?

Just trying to figure out where the Postman specific issue is 😁

**Comment by dmtomczyk** [comment]
The only difference between this picture and the functional request is that the functioning request has a `Content-Length` header in the request headers.

_Screenshot of the non-functional request in Postman's Console_
![image](https://user-images.githubusercontent.com/26173452/125829727-1b27ed13-e064-47bf-afd3-6db4f7373e15.png)


Edit: Specified where the content length header was

**Comment by dmtomczyk** [comment]
More info:

I sent an equivalent request to the same endpoint twice, only changing the mode that was used for creating the request, and observed different results. Am I missing something stupid, or should these be returning the same bodies?

Endpoint: https://postman-echo.com/get
Mode 1: Proper request in Postman UI
Mode 2: Pre-request script in Postman

**Request 1 (Pre-request script):**
Notice the empty `"args": {}` in the response body here, compared to Request 2.
![image](https://user-images.githubusercontent.com/26173452/126182264-4bb58880-ab37-4eb2-b14b-fc5d0715babb.png)


**Request 2 (Proper Request):**
![image](https://user-images.githubusercontent.com/26173452/126181669-db24e208-c55d-43e0-94c1-43b0cb576bd3.png)

**Comment by adrianteixeira** [comment]
@dmtomczyk same issue here; Have you resolved? I'm trying to make a GET with form-data in pre-requests script, but it's not working. Probably, the lib (pm) don't accept get with body.

> Be alerted that postman cant sent GET with body using the pm lib (pre-requests). This may be usefulness to get token with 'GET operation' when you need pass credentials on body (form-data). 
[Image of pre-request script. It will not work.](https://i.stack.imgur.com/6V7HL.png)

**Comment by dmtomczyk** [comment]
@adrianteixeira Sorry, nope. I just use https://github.com/Kong/insomnia now instead. Not sure what the status of it is on the Postman side of things.

**Comment by codenirvana** [comment]
Duplicate of #10116

This is fixed in the latest version of the Postman app (v9.9.0).

<img width="721" alt="Screenshot 2022-01-17 at 7 13 19 PM" src="https://user-images.githubusercontent.com/4865836/149779779-4aede02c-eeca-4b68-a023-f212e9b9f7f4.png">
