### ISSUE TITLE
Show OAuth2 error_description on Postman console

### ISSUE THREAD

**Issue by Kingdutch** [a85/POSTMan-Chrome-Extension#10124]
**Is your feature request related to a problem? Please describe.**
Colleagues were debugging OAuth2 authentication and got cryptic errors. The error on the Postman console (which is the suggested place to look provided very limited info). When diving into this myself I saw the same error information and the Postman callback URL showed the following image

![image](https://user-images.githubusercontent.com/327697/125768404-124f5c04-dc53-4bb2-a50d-cfdff503ac30.png)

This suggests that everything went okay, but there's still an error.

Upon looking at the URL in by browser I noticed there was critical error information in `error_description`:
```
https://oauth.pstmn.io/v1/callback?state=<redacted>&error=invalid_client&error_description=This+application+requires+you+specify+a+scope+parameter
```

Having that information on the console would've saved quite a bit of time in trying to tweak different things to see what wsa going on.

**Describe the solution you'd like**
Besides `error` the information provided in `error_description` should also be posted back to the Postman Console if the paramters is present.

**Describe alternatives you've considered**
Now that I know this I've told colleagues to look at the return URL as well, but it's not immediately obvious.

**Additional context**
Postman Version 8.7.0 (8.7.0)
OS X 11.4
Using Firefox 89.0.2

**Comment by abhijeetborole** [comment]
Thank you for your patience, with Postman V10.7, the error descriptions for OAuth2.0 flows will now be more verbose as we now parse both error and error_description fields in the Postman console.

<img width="1440" alt="Screenshot 2022-12-14 at 2 07 16 PM" src="https://user-images.githubusercontent.com/9638586/207576142-79e66a45-32ea-43d7-b1be-ef7925e75315.png">
