### ISSUE TITLE
New Integration Request - Azure DevOps Git

### ISSUE THREAD

**Issue by jgraham8524** [a85/POSTMan-Chrome-Extension#10129]
### Describe your current workflow

We store our Endpoints in Collections within our Postman team.

### Describe your ideal workflow

We use Azure DevOps for our deployments and would like to automate testing using our collections during our build & deployment processes.

### Describe alternatives you've considered

Nothing yet other than manually exporting and importing collections into our Azure DevOps Git repos.

**Comment by shashankawasthi88** [comment]
@jgraham8524 have you tried using the Postman APIs to fetch the collection while running these tests rather than manually exporting (https://learning.postman.com/docs/running-collections/using-newman-cli/continuous-integration/). 
Your usecase should work using the APIs. We are considering adding support for Azure DevOps in future releases.

**Comment by shashankawasthi88** [comment]
Hey @jgraham8524, while we are planning to add more repository Integrations soon (GitLab, Azure, etc.) we would want to gain some feedback on the recent release (API Platform with Integrations with repository Integrations). Please check this [blog post](https://blog.postman.com/announcing-new-postman-api-platform/) for more info, and update your app to try it out! The Azure flow would remain the same as GitHub, BitBucket. We would love to know how well the release caters to your use cases. 
You can schedule a call with us using this link - https://calendly.com/shashank-awasthi/api-platform-feedback

**Comment by shashankawasthi88** [comment]
Hi @jgraham8524, we have launched a repository integration with Azure DevOps in App version 9.6.0. Please refer to the [blog post](https://blog.postman.com/the-reimagined-api-first-workflow-for-developers/) for ideal flow and l[earning center docs](https://learning.postman.com/docs/designing-and-developing-your-api/versioning-an-api/#connecting-a-repository) to know how to configure Azure integration.
The Azure DevOps Service (TFS/ on-prem) will follow soon.
