### ISSUE TITLE
Feature Request:  Sync Collections to GitHub

### ISSUE THREAD

**Issue by ghost** [a85/POSTMan-Chrome-Extension#1013]
I would like to be able to store / edit / sync / version my collections using GitHub.

**Comment by benjackwhite** [comment]
Agreed, this would be really useful

**Comment by andrewduckett** [comment]
I'll second this... +1

**Comment by sunib** [comment]
Would be very nice to add explaining links to my own GitHub projects. Would be even nicer to have someway to open up a collection automatically into Postman when users click some link with a Postman collection.

**Comment by LexFrench** [comment]
+1 This would be an incredibly useful feature.

**Comment by duepayer** [comment]
+1

**Comment by 486** [comment]
+1, and I would add: There should be a separation of syncing the collections and your environments. (current sync to postman syncs everything, right?) Because your environment will likely contain passwords, and you don't want to sync this to your github repo.

**Comment by sobtiankit** [comment]
@486: We actually encrypt the environments before storing them in our database. You can find more information about the same here: https://www.getpostman.com/docs/security. In the near future, we will also include support for Client-side encryption.

As for Github integration, we are working on this and will introduce it soon!

**Comment by 486** [comment]
@sobtiankit Thanks for the info - So for your sync service with client-side encryption, this is all perfectly fine, but I think that when you allow people to sync somewhere else, most will realize that they want their credentials / environments not synced or synced somewhere else than the collections (my company and I certainly do).

**Comment by sobtiankit** [comment]
@486 That's a valid concern, and let me get back to you on that. But a quick question, with sufficiently secure client side encryption, there's nothing anyone (with access to the database, as well) can do to decrypt that information given you hold the cipher. Evernote, e.g. works on the same principle. 

We can include the option of disabling environment syncing along with the client-side encryption release, but I wanted some more information from people with similar concerns as yourself.

**Comment by andrewduckett** [comment]
Could we let people choose the sync location(s) independently?  Though github.com makes sense I could see people wanting collections and/or environments synced to a private github (or even git) instance as well.

**Comment by patricksavalle** [comment]
+1

**Comment by boblindman** [comment]
Any update on client side encryption? It's the only reason I'm not using sync yet.

**Comment by abhijitkane** [comment]
@blindman777 Not yet. We've been working on a few other features for Postman. We'll update this thread soon.

**Comment by Nuru** [comment]
@abhijitkane Let me chime in on a few of the issues raised in this thread.

First, I'd like to be able to sync the non-sensitive data everywhere. Your Sync project looks like that would work fine, as would being able to sync them via GitHub or Dropbox or whatever.

Second, I'd like to be able to exclude environments from all syncing so I can put sensitive data in there. 

Third, I'd like to be able to keep environments encrypted at rest on my own computer. 

Encryption is great, but it is far from foolproof, so best practice is what they call "security in depth", using multiple security measures so that an adversary has to defeat more than one to succeed in getting your data. For example, if the data is stored encrypted on your server, all someone needs is to steal or guess my password and they will be able to get my data from your server, regardless of how secure your server is. Likewise, if it is stored in plain text on my computer, any malware will have easy access to it, and it risks leaking out in a backup, or in the repair shop if I take my computer in for repair. 

So for me, I would want environments stored in a locally encrypted file that I could copy or delete as needed, and never have them leave my computer unless I explicitly share that file.

**Comment by who** [comment]
+1

Another alternative:
1. Open source the API that you use for storing collections
2. Allow users to choose different URL for collection storage API

This would allow teams to self-host collection storage APIs, and they could use Github as a backend if they wish.

**Comment by a85** [comment]
@who Postman doesn't just sync Collections but history, environments and almost everything else that we'll add in the future. We have looked at every alternative including Github/Bitbucket/Dropbox/Drive and while dumping data inside these containers works, every other feature we have inside Postman Cloud is not feasible. We have to build our own data store anyway as Github is not the standard for development teams. We'll keep this thread updated with more info.

**Comment by a85** [comment]
Also, keeping data secure is a high priority item. Client side encryption for environments is on its way. We'll keep adding more measures over the coming weeks.

**Comment by who** [comment]
> Also, keeping data secure is a high priority item. 

Your focus on security is great and welcome. However, that approach does require that Postman users trust Postman to keep their environments secure. This trust is a deal-breaker for many teams and companies.

**Comment by who** [comment]
> Postman doesn't just sync Collections but history, environments and almost everything else

@a85 

I am not asking for Postman Sync to be pluggable - just the collection storage/sharing component would be an excellent start.

**Comment by who** [comment]
@a85 

Here's a quick-and-dirty mockup:

![](http://i.imgur.com/5AwsMPO.png)

**Comment by who** [comment]
> We have to build our own data store anyway as Github is not the standard for development teams.

If you make the https://app.getpostman.com/api/collections API public and open source, and then allow users to choose self-hosted collection repositories/servers when sharing collections, you can enable development teams to implement whatever backend datastore they want. As long as their API layer is conforming to the API contract, it doesn't matter how/where the data is stored.

**Comment by a85** [comment]
@who As far as I can say right now, we are working towards this. First step is standardising our Collections format that other people can build on: http://blog.getpostman.com/2015/06/05/travelogue-of-postman-collection-format-v2/

On the trusting Postman part, we are working with several small and large companies. The development world is rapidly changing as the growth of AWS has shown. We haven't had a deal breaker yet but I agree that it won't be the same for every company. We are working on this.

I'd love to get on a call with you/meet in person and discuss our roadmap in more detail. I'm in SF this December. :)

**Comment by anyone-can-test** [comment]
+1
Also, I like "Open source the API that you use for storing collections".

**Comment by dekz** [comment]
I'd like to see just a generic pull from url, read only, no write.

Syncing changes across multiple users is difficult, I'd like to see reads be easy for now.

Even allowing Postman App to support URL file handlers would be a step forward.

```
postman://app/collections/import/url?url=url_to_collection
```

**Comment by a85** [comment]
Coming soon through our Github integration for Postman Cloud users.

**Comment by mjgp2** [comment]
Do you have an expected timeframe @a85 ?

**Comment by lateef531** [comment]
+1
Any update on the timeline when github sync feature will be available?

Also can you please implement the sync has an option to connect to any github i.e. on premise url's like https://github.xyz.company.com

**Comment by sdnts** [comment]
@lateef531 @mjgp2 GitHub integration is now out for Postman Pro teams as @a85 mentioned. You can find it under the `Integrations` link on your dashboard.
