### ISSUE TITLE
Postman Web Sign-in using IE

### ISSUE THREAD

**Issue by Dauthjan** [a85/POSTMan-Chrome-Extension#10131]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the Issue

Postman Sign-In from App uses default browser to sign-in. Currently, due to policy constrains, I'm bound to use IE 11 although has Chrome and Edge available (no permission to change default browser).

IE doesn't support "[sendBeacon](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/sendBeacon)" due to which I'm unable to login to my account. 

Postman App Login supports Token login but not sure how to use it. Please can you enable any fallback for IE or alternative for login? I'm able to login through Edge/Chrome. 

Any specific Postman API that I can hit with my credentials to get the response of "[postman://auth/callback?code=****](postman://auth/callback?code=****)"?

### Steps To Reproduce

1. Start Postman
2. Press "Sign In" button
3. That opens IE by default (not authorized to change default browser)
4. Enter credentials to login
5. Nothing happens -> console shows _object doesn't support property or method 'sendbeacon'_

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/64382459/126044643-c35b4db9-0384-4608-8785-aedea33c9fcd.png)

### Environment Information

```markdown
- Operating System: Windows Server 2016
- Platform Type: Postman Web
- Postman Version: 8.8.0
```

**Comment by ghost** [comment]
@Dauthjan Hi, we have looked into the issue and have deployed the fix for it. You should be able to use IE now, Sorry for any inconvenience caused.

**Comment by Dauthjan** [comment]
@meetSuraj Thanks, that worked!
Thanks a lot team.
