### ISSUE TITLE
v8.8.0 unable to detect internet connection

### ISSUE THREAD

**Issue by Serge-N** [a85/POSTMan-Chrome-Extension#10136]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

Postman is unable to load data because , it says am offline.

### Steps To Reproduce

1. Open Postman v8.8.0 

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/51508252/126447213-de633ed7-32b8-4afa-a736-a68e010cade7.png)

![image](https://user-images.githubusercontent.com/51508252/126447362-7044666e-853f-498b-b43b-de4786720af1.png)

### Environment Information

```markdown
- Operating System: Windows 10
- Platform Type: Native App
- Postman Version: 8.8.0
```

**Comment by ilian-n** [comment]
It same problem for me!
- Operating System: macOS 11.4
- Platform Type: Native App
- Postman Version: 8.8.0

**Comment by SWRHARD** [comment]
same error

+ Operating System: Windows 10
+ Platform Type: Native App
+ Postman Version: 8.8.0

**Comment by SamriddhaBanik** [comment]
Same in linux. 

Operating System: Ubuntu 18.04
Platform Type: Native App
Postman Version: 8.8.0

**Comment by brankopajic** [comment]
Same here.
![image](https://user-images.githubusercontent.com/14924709/126449978-c249fad7-570f-4391-9537-1092b5df7b7f.png)

Postman Version: 8.8.0
OS: MacOS Big Sur 11.4
Platform type: Native app

**Comment by FTC5** [comment]
Same
Postman Version: 8.7.0. and 8.8.0 (Two minutes ago got update)
OS: Windows 10
Platform type: Native app

**Comment by DannyStaub** [comment]
Same here:
Postman Version: 8.8.0 
Postman for Windows
win32 10.0.19042 / x64

From the DevTools (Current View)
```
Failed to load resource: the server responded with a status of 502 ()
app.getpostman.com/api/users/xxxxxxx?app_version=8.8.0&app_target=electron:1 Failed to load resource: the server responded with a status of 502 ()
app.getpostman.com/api/users/xxxxxxx/app_bootstrap?freecollab=true&app_version=8.8.0&app_target=electron&populate_groups=true:1 Failed to load resource: the server responded with a status of 502 ()

Failed to load resource: the server responded with a status of 429 (TOO MANY REQUESTS)
sentry-app.postmanlabs.com/api/22/store/?sentry_key=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx&sentry_version=7:1 Failed to load resource: the server responded with a status of 502 (Bad Gateway)
sentry-app.postmanlabs.com/api/22/store/?sentry_key=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx&sentry_version=7:1 Failed to load resource: the server responded with a status of 429 (TOO MANY REQUESTS)
sentry-app.postmanlabs.com/api/22/store/?sentry_key=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx&sentry_version=7:1 Failed to load resource: the server responded with a status of 502 (Bad Gateway)
```

**Comment by podplatnikm** [comment]
Same here
Postman version: 8.8.0
OS: Mac OS Big Sur 11.4
Platform type: Native app

**Comment by agburov** [comment]
Same issue here.

Operating System: macOS Mojave (version 10.14.6)
Platform Type: Native App
Postman Version: 8.8.0

**Comment by postman-staff** [comment]
Hello,

Sorry to see you are facing issues with using Postman, our team is now investigating the incident with higher priority.
Our status page has been updated to reflect the issue, our team will communicate any updates there -  https://status.postman.com/

I will also update that thread once there's an update, apologies for the inconvenience caused, we really appreciate your patience.
via @nasco-a | Postman Support

**Comment by wuai1024** [comment]
+1 

遇到同样问题了，现在已经没法使用了

**Comment by postman-staff** [comment]
Our team has released a fix, and the issue should now be mitigated.
Can you please restart Postman, and see if it works as intended for you?

We are also actively monitoring the outage and we will continue providing any updates on our status page

Apologies for the inconvenience caused.
Many thanks for your patience.

via @nasco-a | Postman Support
