### ISSUE TITLE
Nothing happens when invoking "Import existing file"

### ISSUE THREAD

**Issue by minimum91** [a85/POSTMan-Chrome-Extension#10137]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

Just downloaded Postmac for the first time. Fresh macOS Mojave 10.14.6 installation from just a couple months back. Clicking **Import an existing file** or invoking **File > Import** just does not work. Nothing happens.

### Steps To Reproduce

1. Open Postman
2. Login
3. Click **Import an existing file** / **Import** file or go to **File > Import** in the menu bar

### Screenshots or Videos

https://user-images.githubusercontent.com/761247/126451615-206a4b5f-0b41-46f3-95cc-76f59ace7bee.mp4

### Environment Information

```markdown
- Operating System: macOS 10.14.6
- Platform Type: Electron App
- Postman Version: 8.8.0 and 8.7.0-canary210611-0747
```

**Comment by DannyDainton** [comment]
Hey @minimum91 

Are you still seeing this issue? 

We're seeing elevated error rates in some services around the time that this was raised.

**Comment by DannyDainton** [comment]
@minimum91 I'm going to close this issue, for now. I've not been able to recreate the issue and I suspect those might have been happening during a recent service outage.

We can also reopen this issue if this is not the case.
