### ISSUE TITLE
Collection Request Name editing and mouse selection when dragging out unselects and turns off edit

### ISSUE THREAD

**Issue by bradthurber** [a85/POSTMan-Chrome-Extension#10134]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

For testing, I will often duplicate a request (Ctrl-D) and then rename the first or last part of the name of the duplicate request by typing Ctrl-E, then I click-drag the mouse over the characters I want to change.  This ticket is regarding the mouse click drag behavior. As long as I stay within the edit box with the mouse, everything is fine, but if I drag beyond the edit box with the mouse, edit mode turns off - which is really frustrating. 

### Steps To Reproduce

1. Select a Request in a Collection
2. Click Ctrl-E to start edit mode.
3. Using your mouse, start click drag to highlighting what you want to change in the edit box. Make sure you highlight clear to the end of the text and keep going outside the edit box.
4. Notice how edit mode just turns off.

### Environment Information

```markdown
- Operating System: Windows 10
- Platform Type: Native app AND Postman Web
- Postman Version: 8.8.0
```

**Comment by Dhembla** [comment]
@bradthurber Sorry for the trouble you had to go through because of this issue. We have fixed this issue, and you can try the new experience on the Postman app version 10.10. Thanks for your patience. 🙇
