### ISSUE TITLE
Pre-request Script

### ISSUE THREAD

**Issue by xxp520** [a85/POSTMan-Chrome-Extension#10142]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request

### Is your feature request related to a problem?

Pre-request Script

### Describe the solution you'd like

I want to set Pre-request Script for all collections

**Comment by DannyDainton** [comment]
@xiaoxiaopeng520 Could you please provide more context about the request and an example of the use case?

**Comment by DannyDainton** [comment]
Closing this issue, we can reopen once more context has been provided.
