### ISSUE TITLE
Delete and remove all collections

### ISSUE THREAD

**Issue by eventhough** [a85/POSTMan-Chrome-Extension#1014]
Feature request: the ability to delete and remove all collections. When I want to import a new data dump it doesn't work if I have existing collections with the same name. There should be a way we can either choose to overwrite all or just remove all collections before importing.

**Comment by a85** [comment]
I doubt we'll have such a kill switch. This is a high risk button. We are improving collection management features consistently and we'll have a look at this again soon.

**Comment by gadelkareem** [comment]
+1

**Comment by ctwagner** [comment]
+1

**Comment by platramos** [comment]
+1 Please add this feature add it would make development on my client engagement much easier

**Comment by BFMarks** [comment]
Adddddd Pleaaaaseee

**Comment by BFMarks** [comment]
We can handle the responsibility.

**Comment by ArunMonySpin** [comment]
+1 . we need this . you know how people do it otherwise right ? un-install and install

**Comment by Bigfootmech** [comment]
Guys, to do this, navigate to

C:\Users\***USERNAME***\AppData\Local\Google\Chrome\User Data\Default\Storage\ext

And delete the folder fhbjgbiflinjbdggehcddcbncdddomop

If you can't find that exact name, look inside them.
There should be a 

> def/Cookies 

file that starts with "SQLite format 3". As well as a 

> def/databases/Database.db

file

You also seem to lose your environments (along with deleting all collections), but not the Proxy, or import location.

To the project manager who decided it's a high risk button: Shame on you.
In World of Warcraft, you can delete characters/items you've sunk hundreds of hours in to, but you have a dialogue where you have to manually type DELETE. Be more creative.

**Comment by gadelkareem** [comment]
@Bigfootmech You are a hero! 
One line for OSX
`mv ~/Library/Application\ Support/Google/Chrome/Default/Storage/ext/fhbjgbiflinjbdggehcddcbncdddomop /tmp/`

This clears all data except for Global vars. Let me know if we can also clear it as well.

**Comment by kurtfm** [comment]
I don't see what the big deal about a delete/reset everything... when you work on multiple projects, different environments, postman can easily become super cluttered.  You don't really know what  you screwed up.  Then you start wishing you could just maintain these stupid tests in regular JSON files and run newman without the pretty UI.... that's a diff topic.

What about...
Use some kind of 'project' space like in your IDE where you would have a segregated set of collections, environments, globals.

Allow us to point to actual files on the file system. Then I can use version control, mess around, revert changes easily.

Since you have backup everything, it seems like the client could use that itself to create an undo on the delete everything.

**Comment by ArunMonySpin** [comment]
I guess the postman team thinks , that all its users are novice and can't take care of such "high risk" buttons if they provide one

**Comment by LucyCookie** [comment]
+1

**Comment by Alexsey** [comment]
We are generation environments and globals dynamically based on actual db values. So this feature would be very helpful. So +1

**Comment by tezizzm** [comment]
While I love, appreciate and frequently use Postman I find the rational of this feature being rejected almost unfathomable.  By and large I would assume you have a somewhat technical user base that can handle a delete button with a "Are you sure? This action is not reversible" confirmation.  As previously mentioned you could even export a "just in case dumbo didn't really mean it" dump to temporary storage.

In my case, we generate swagger API docs that I would like to import to Postman.  I see some of them have minor changes that need to be made.  Now I have to go through 290+ collections and delete them one by one or uninstall and reinstall the application.  It baffles me that you have a tool that is so powerful and embraces automation in so many ways and then it seems like you sabotage it all in the name of saving the user from themselves.

**Comment by sdnts** [comment]
@tezizzm, we're working on multi select within the sidebar, and in my opinion, that would be a lot less riskier. When that gets to our stable channels, you should be just able to Shift+click and delete. :)

**Comment by bhawna2109** [comment]
Hi everyone, we totally understand the use case here. In addition to what @madebysid mentioned, we're working on an idea of 'Workspaces in Postman' which is on similar lines to what @kurtfm suggested. Thus, you can put together a bunch of Postman entities (collections, environments, globals) in a single workspace and define multiple workspaces like these. This will help reduce the clutter because now you'll be working with a single workspace at one point of time and only the relevant entities will be in view.

**Comment by ma198307** [comment]
Hi, the ability to delete all collections would give test cases portability and ease of use. If I have 500  apis and 50 collections to test those. With new  environments feature,  I can use a variable to replace to replace host name in URL. Environment variables gives flexibility to quickly change the hostname  but consider a real world scenario where multiple variables are used in test cases say ip-eth1, ip-eth2, ip-lb, hostname for multihomed server / cluster/ Loadbalancer ips. If these variable needs to be changed frequently across all the test cases,  just updating variable name across 50 collection is a real pain(The only quickest way is take postman dump, replace variables name, delete all 50 existing collection  and re import the updated dump) . So the point is;  having environment level variables is better but it  doesn't give much flexibility.

**Comment by rgasioro** [comment]
I am exporting my collection via settings -> data, and I can see that some old responses are included in the export. How can I clear those?

**Comment by jpoints** [comment]
Delete All Collections would be nice, I like to clear my workspace from time to time. I feel the UI gets clunky when there are too many collections. Also, I go back and forth between postman and newman, so my collections are officially stored within the newman code base. So I am not worried about lost data. 

Workspaces might solve it, but I might have a workspace setup the way I like, but I may want to clear the collections that are currently in it. In this case I would still need to delete all collections.

When I work on an existing endpoint, I import the collection into postman, make changes, export it to newman, and then delete it from postman. 

Some times I want to import all the collections, or I have a bunch of failed collections that I no longer want. In this case I may have 50+ collections in the interface, and it is tedious to delete them. 
(Of course I would want export all collections as well, but that is a separate issue)

Two solution that I see for delete all collections
1. Make it harder to delete all, for example, click delete, type "I know what I am doing" into a prompt.
2. OR, do not officially delete the collection, move the collections into an archive section.

**Comment by stofte** [comment]
Would be very nice with a clear button. I have dozens of collections with no idea whats in them (none of this is sync'ed of course). Half of them are "OtherCollection copy", with randomly modified requests that I really have no desire to keep around.

**Comment by jamielennox** [comment]
Yea, this is unfortunate. I do work for different clients and i just want a reset everything button to clear out all the stuff i don't care about any more and start from fresh. 

If this data was important it would be synced or saved somewhere. Now it's just a bunch of history I have to delete.

**Comment by magsymcgee** [comment]
It's such a shame this hasn't been implemented, I absolutely love postman but it's a massive pain to remove these especially if I don't want to switch workspaces to start again from scratch. Multi Select and delete would be a huge improvement.

**Comment by BrandtSolovij** [comment]
This is the sort of thing that makes me loath postman.

**Comment by jpSimkins** [comment]
I have a paid version and I have a workstation I rarely use. It would not sync, spent over 24 hours and still not synced. The easiest way to fix this was to delete the (on Ubuntu) `~/.config/Postman` directory and restart Postman. Honestly, would love a way to delete all data and resync to my account. Also, different environments per collection.. it's too noisy.

**Comment by s-haralampiev** [comment]
We need this functionality. 👍

**Comment by IanKemp** [comment]
It's rare to see this type of idiocy from an application development team, but what else can you expect from Electron "developers"?

**Comment by pvm30** [comment]
Idiocy and nothing more than idiocy. Why do we have to suffer the statefulness of this application? Every time I start Postman I want to start from scratch and completely clean. I don't give a shit about what I did in a previous session. This is the kind of crap we have to put up with in Chrome with cookies and history and all that bullshit trying to find out who you are and what you are likely to buy
