### ISSUE TITLE
Postman desktop agent is not working behind firewall

### ISSUE THREAD

**Issue by praveendvd** [a85/POSTMan-Chrome-Extension#10148]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

*My question*:

I am trying to use postman web with desktop agent, but i get below error as per main.log

```
[16112][1626862390593][main][warn]["Error while checking for update",{"error":{"message":"request to https://dl-agent.pstmn.io/update/status?channel=stable&currentVersion=0.3.8&arch=64&platform=win64 failed, reason: unable to get local issuer certificate","type":"system","errno":"UNABLE_TO_GET_ISSUER_CERT_LOCALLY","code":"UNABLE_TO_GET_ISSUER_CERT_LOCALLY"},"status":1}]
```

### Steps To Reproduce

Run the agent behind a corporate firewall with self signed certificate 

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/45095911/126863747-65053c26-a89a-4dcf-98b4-ca8b3eb8d5c9.png)

![image](https://user-images.githubusercontent.com/45095911/126863729-20395a82-b9ef-41f3-83c5-77fe013ff9ab.png)

### Environment Information

```markdown
- Operating System:  Win 10
- Platform Type: WebAPP
- Postman Version: 8.8.0
```

**Comment by DannyDainton** [comment]
Hey @praveendvd

Could you update the issue with a new set of images please, seems like these were not uploaded correctly.

**Comment by praveendvd** [comment]
@DannyDainton done

**Comment by jviotti** [comment]
Merging this with https://github.com/postmanlabs/postman-app-support/issues/6053

**Comment by jviotti** [comment]
Also see https://github.com/postmanlabs/postman-app-support/issues/7240
