### ISSUE TITLE
Ability to highlight Environment variables which aren't used in current Collection

### ISSUE THREAD

**Issue by tomaszwojciechowski** [a85/POSTMan-Chrome-Extension#10159]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request

### Is your feature request related to a problem?

When Environment is being used with updated Collections, some variables may be deprecated.

### Describe the solution you'd like

This ability will make maintaining Environment easier.

**Comment by DannyDainton** [comment]
Hey @tomaszwojciechowski 

Could you expand on the details of the feature request and add examples of what you're currently seeing, please?

**Comment by DannyDainton** [comment]
Hey @tomaszwojciechowski 

I'm going to close this issue as the use case is unclear, given the information you have provided.  

If you could expand on the problem statement and share some examples, that would be awesome and we can look to open this again.
