### ISSUE TITLE
Add Version control feature to postman changelog section

### ISSUE THREAD

**Issue by praveendvd** [a85/POSTMan-Chrome-Extension#10152]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request

### Is your feature request related to a problem?

Currently we have to depend on version control systems like git to make sure we don't mess up collection. The changelog feature in postman doesn't allow to reset back to the previous version

### Describe the solution you'd like

It would be great to make the changelog section to have logs on all changes including settings, collection or environment chagnes , script changes etc . And the ability to restore back to a previous log history. 

The change log should act like the git logs which allows user to checkout a specific version and also have a option to delete and squash certain commits to ensure security that secrets are not cached in the commit history by accident

### Describe alternatives you've considered

Using git and using forced git pushes to remove sensitive commit logs

**Comment by DannyDainton** [comment]
Hey @praveendvd 

Most of the change log version control features and the ability to restore the collection back to a certain point, is available in the Team, Business and Enterprise plans.

https://learning.postman.com/docs/collaborating-in-postman/using-workspaces/changelog-and-restoring-collections/#restoring-collections-and-folders

Is that the versioning ability that you are referring too?

**Comment by praveendvd** [comment]
Yes I didn't know it was already available for buissness version thank you Danny

**Comment by praveendvd** [comment]
You can close this thank you
