### ISSUE TITLE
Team Admin should be able to view Private Workspaces.

### ISSUE THREAD

**Issue by Swapnil-getpostman** [a85/POSTMan-Chrome-Extension#10156]
### Is there an existing request for this feature?

- [x] I have searched the existing issues for this feature request

### Is your feature request related to a problem?

There is no way for a Team Admin to list the total "Private Workspaces" created within the team. As of now, the team admin can only view all the Team and Public workspaces at "https://go.postman.co/workspaces".

### Describe the solution you'd like

It would be really helpful if the team admin can have a feature to **only list** the Private Workspaces that exist within the team.

**Comment by akshay-kulkarni-03** [comment]
@Swapnil-getpostman could you let us know what type of user/team need this. The enterprise team can opt for super admin functionality as mentioned [here](https://blog.postman.com/introducing-the-super-admin-role/) through which the super admin can view all the private workspaces present in the team. Could you elaborate customers use-case a little bit better? I don't think we plan to enable this functionality anytime in near future.

**Comment by akshay-kulkarni-03** [comment]
@Swapnil-getpostman with super admin role available on enterprise plans, they can view private workspaces within the team.
