### ISSUE TITLE
Font is too small on Hi-Res displays

### ISSUE THREAD

**Issue by evmin** [a85/POSTMan-Chrome-Extension#1015]
Would appreciate a zoom setting.

**Comment by shamasis** [comment]
You can set the font size in settings. I would agree that it's not a perfect solution, but it should help. :-)

**Comment by evmin** [comment]
I was able to find response font size. Not UI. Is there one?

**Comment by abhijitkane** [comment]
@evmin In the packaged app, you can find an option to change the response size in Settings > Settings > Response Font Size

**Comment by evmin** [comment]
Thank you. I found this one. It does not affect the menus and the general
UI, unfortunately. Sadly it is too small for me as is.

**Comment by a85** [comment]
Available in Postman 3.0 now!

**Comment by stephenjlevy** [comment]
This appears to have regressed in 3.05

**Comment by frankpiva** [comment]
Font is still unreadable; changed font size, didn't do anything. Please add a zoom option for those of us with sub par eyesight.

**Comment by sdnts** [comment]
@frank-productops Can you update to the latest version (v4.6.1)? We added functionality to zoom in/out using `Cmd/+` & `Cmd/-`. That should fix your issue.

**Comment by frankpiva** [comment]
Zoom is working. Have you though about increasing the max zoom? Even at maximum zoom I still find things a little too small.

**Comment by TimothyBramlett** [comment]
May want to add some links to this thread with the `Cmd/+` resolution for some of the older threads.  Just to let people know that there is a fix now.  I almost started searching for a new tools after reading a thread that was eventually locked.

**Comment by a85** [comment]
@TimothyBramlett Feature has been out for a while now. I'll add a comment on other threads. :)

**Comment by betimer** [comment]
Zoom is totally useful, expect to see it.
