### ISSUE TITLE
Bootcamp: 'Add Match' POST request unauthorized

### ISSUE THREAD

**Issue by RyanJMoore10** [a85/POSTMan-Chrome-Extension#10153]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

I followed the instructions described in part 1.2 (add match) to the letter, and it is not continuing the training as in previous requests. Instead, it is giving the 'unauthorized' response, which is the same response as it gave before adding my email as a variable and following the rest of the instructions to set it as match_key. 

The header doesn't get added to the request when I press send, not sure if it stays hidden... 

### Steps To Reproduce

Oops - You got an unauthorized error response! 🚫
When you're sending new data to the API, you will typically need to authorize your requests.

You're going to add an auth key to this request, but instead of entering it manually let's use a variable—this helps minimize visibility of what could be sensitive credentials. Open the Authorization tab for the request—select Inherit auth from parent from the Type drop-down list.

In Collections on the left, select the student expert collection (click … and choose Edit if you're in the app). Open the Authorization tab. Postman will add the API key details to the header for every request using the name match_key and the value specified by the referenced email_key variable.

Add a variable to the collection also via the Edit menu—choosing the Variables tab. Use the name email_key and enter your email address in both value fields. Postman will now append your email address to each request to identify you as the client. Make sure you use the email address you'd like your Postman Student Expert certification awarded to, e.g. don't use your college email because you'll no longer have access to that when you graduate—choose a personal email address you'll continue to have access to.

If you pop back into the collection edit modal Authorization and hover over the {{email_key}} reference you should now see your email address. With your API Key in place, click Send.

### Screenshots or Videos

Oops - You got an unauthorized error response! 🚫

### Environment Information

```markdown
- Operating System: Windows
- Platform Type: Desktop App
- Postman Version: 8.9.1
```

**Comment by DannyDainton** [comment]
Hey @RyanJMoore10 

This appears to be an issue you're having with the Student Expert Training - Can I ask that you raise a new thread on the Postman Community Forum, under the `Training` category and the folks on there will be able to guide you through this training. 

https://community.postman.com/c/training/38

I'm going to close out this issue for now.
