### ISSUE TITLE
Can't compare the object in json array by deleting some fields

### ISSUE THREAD

**Issue by Sriram1404** [a85/POSTMan-Chrome-Extension#10158]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

I have tried to compare the expected Json response with the actual Json response by deleting the id field. But getting Test result as `AssertionError: expected [ Array(2) ] to have the same members as [ Array(2) ]`

```
let expectedJson = {
    "code": 200,
    "data": [
        {
            "id":"U1",
             "name:"Raghu"
        },
        {
             "id":"U2",
             "name:"Raju"
        }
    ],
    "metadata": {
        "TotalRecordCount": 2
    }
}
let actualResponse = pm.response.json();
 for (var i = 0;i < actualResponse.length; i++){
     delete actualResponse.data[i].id;
 }

pm.test("Compare Employment verify GET Result Sets", () => {
    pm.expect(expectedJson.code).to.eq(actualResponse.code);
    pm.expect(expectedJson.data).to.have.deep.members(actualResponse.data);
    pm.expect(expectedJson.metadata).to.include(actualResponse.metadata);
})
```
### Steps To Reproduce

1) Use an endpoint that returns an array of objects along with code and metadata.
2) Try to compare the json result by deleting the id field. 

### Environment Information

```markdown
- Operating System: Windows 10 Pro
- Platform Type: Native App
- Postman Version: 8.9.1
```

**Comment by DannyDainton** [comment]
Hey @Sriram1404 

This doesn't feel like a product bug, from what I can see in your code, it looks more like a javascript syntax issue. 

Can I ask that you create a new thread on the Postman community site and the folks there will be able to help with a solution.

https://community.postman.com/
