### ISSUE TITLE
API endpoint to fetch Billing data of Postman

### ISSUE THREAD

**Issue by VaishnaviChallaPostman** [a85/POSTMan-Chrome-Extension#10162]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request

### Is your feature request related to a problem?

There is no API endpoint to fetch a teams billing data programatically.

### Describe the solution you'd like

An API endpoint to fetch a teams billing data programatically.

### Describe alternatives you've considered

Currenlty,  The invoice will be sent to the billing contact listed on account every month (for monthly teams) on the billing date. Users can update it as per their requirement.

### Additional context

Already being tracked internally. Creating here to track publicly.

**Comment by bpedro** [comment]
Thanks for sharing, @VaishnaviChallaPostman!

**Comment by davidespihernandez** [comment]
The Postman API exposes an endpoint to get information about [billing](https://www.postman.com/postman/workspace/postman-public-workspace/folder/12959542-aa3c5de3-d30b-4082-b4da-5459779b5ba3). 
Please let us know if this is useful for you.
