### ISSUE TITLE
Can't Add New Environment on Chrome 42.0.2311.90 (64-bit) - Ubuntu 14.04.1

### ISSUE THREAD

**Issue by edwardsamuel** [a85/POSTMan-Chrome-Extension#1016]
When I submitted a new environment, the new environment didn't appear in Environments dialog.

![Add new environment dialog](https://cloud.githubusercontent.com/assets/3603637/7227542/0b3449a2-e784-11e4-9907-0caec93f18cc.png)

![Environments dialog after submitted the new environment](https://cloud.githubusercontent.com/assets/3603637/7227544/16504c28-e784-11e4-9cbf-515991e1cbe0.png)

**Comment by abhijitkane** [comment]
@edwardsamuel Are you still seeing this in v3.0.4?

**Comment by edwardsamuel** [comment]
@abhijitkane Nope. Looks good now.
