### ISSUE TITLE
Font is too small

### ISSUE THREAD

**Issue by sasidhar-Eunimart** [a85/POSTMan-Chrome-Extension#10177]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

Hi, I updated my postman, most of my colleague's suggest not to, but I updated, After updating I am searching for API testing tools, I am not blaming the team, it is good, But I am having the worst experience in DARK MODE, Try postman in MacBook air 2017, core i5 5th gen.
![Screenshot 2021-07-30 at 5 55 35 PM](https://user-images.githubusercontent.com/58244882/127652651-388e77ca-a25c-4a69-a96e-08529bc6bc91.png)
The font is too small, and the collection window is not adjustable.
![Screenshot 2021-07-30 at 5 56 23 PM](https://user-images.githubusercontent.com/58244882/127652733-56cdc781-c5c6-4b11-b3d6-366ba837fe12.png)
Check the font.

Please try in MacBook, so that you guys can experience how hard it is, please please please do something.

I am reporting it as BUG, you guys know why

### Steps To Reproduce

1. Open postman

### Environment Information

```markdown
- Operating System: macOS Catalina 10.15.7 (19H1217)
- Platform Type: Native app
- Postman Version: Version 8.9.1 (8.9.1)
```

**Comment by postman-staff** [comment]
Hi,

We have checked the reported concern and would like to infrom you that there is no difference in the font for light & dark mode. Also, can you let us know which screen you are referring to which is not adjustable?

via @ash007-postman | Postman Support

**Comment by sasidhar-Eunimart** [comment]
MacBook AIR 2017 - 13.3-inch (1440 x 900)

I downgraded to the old version..!, (7.36.6) because of font and size, it's not pleasing to the eyes.
![Screenshot 2021-08-05 at 11 16 34 AM](https://user-images.githubusercontent.com/58244882/128297722-53709016-0465-4fd9-887a-221a76146765.png)

**Comment by postman-staff** [comment]
Hi,

Thanks for the revert. We have tagged the respective team to check on this feedback further and provide their inputs. Meanwhile, you can also try Postman web via navigating to this link here: http://go.postman.co and check if this helps you.

You can also contact us via https://www.postman.com/support/ for any other issues. Thank you!

via @ash007-postman | Postman Support
