### ISSUE TITLE
Freezes(DoS) when a significant x-www-form-urlencoded value is passed

### ISSUE THREAD

**Issue by j0nimost** [a85/POSTMan-Chrome-Extension#10175]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

When I tried testing a POST API using the **x-www-form-urlencoded** option, I passed in the value option a large value about 850 bytes in size. Postman completely froze and became unresponsive.

### Steps To Reproduce

1. Open a new tab
2. Choose the POST option
3. Select Body
4. Choose x-www-form-urlencoded
5. Enter a Key 
6. Paste a large object in Value

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/24381727/127638637-6a5d05f1-b661-4a3b-9b3b-eba6df2f938a.png)

### Environment Information

```markdown
- Operating System: Windows 10
- Platform Type: Native App
- Postman Version: 8.9.1
```

**Comment by codenirvana** [comment]
Can you share a scaled-down collection that we can use to reproduce this issue?

Followed the steps you mentioned and sent 10KB value as `x-www-form-urlencoded` to `https://postman-echo.com/post` and it didn't freeze.
