### ISSUE TITLE
API > Develop > Validation does not detect paths deleted from schema

### ISSUE THREAD

**Issue by mbahnmiller** [a85/POSTMan-Chrome-Extension#10182]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request

### Is your feature request related to a problem?

When I update my schema, removing unwanted paths, and re-validate, the validator does not detect that I now have items in my collection that shouldn't be there.

### Describe the solution you'd like

I'd like the validator to recognize the path is missing from the schema and offer to delete the specified item from the collection.

### Describe alternatives you've considered

Manual deletion

**Comment by SaloniV3011** [comment]
Hey @mbahnmiller 
Sorry for the delayed response, I just wanted to check in how I can replicate the same issue you faced, would like to know if you are still facing this issue. If so, could you please share the steps you took.
Thanks!!

**Comment by shashankawasthi88** [comment]
@mbahnmiller can you try this out in the latest Postman version. This should now be fixed.
