### ISSUE TITLE
postman客户端登录后 账号中数据无法同步

### ISSUE THREAD

**Issue by dsdasun** [a85/POSTMan-Chrome-Extension#10186]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

postman客户端登录后 账号中数据无法同步

- 

### Steps To Reproduce

1.登录账号

### Screenshots or Videos

![20210803162611](https://user-images.githubusercontent.com/65879717/127983532-379e96cf-77f7-4c6c-9186-d64d8ad46f1e.png)

### Environment Information

```markdown
- Operating System: 
- Platform Type: 
- Postman Version:
```

**Comment by postman-staff** [comment]
Hi hello,

Thank you for reaching out to Postman.

I understand that you are receiving a connection error in the desktop app, Right?
Sorry for the hassle, happy to assist!

Postman uses Web-Sockets to sync data between clients and our cloud services, and it is likely that the web-socket connection is being interrupted for some reason.

Are you using any of the VPN/proxy/firewall or antivirus applications on your device?
If so, could you please try turning it off or terminating it completely and see if that helps?

Also, could you please try using another network such as a mobile hotspot and see if that helps?

If the issue persists, could you please tell me if you are able to use the web dashboard (go.postman.co) without any problem?

Additionally, if you can send me the application logs and attach it as a zip file to your response email, that would help us to investigate the issue further.
Here is how you can find application logs:
https://support.postman.com/hc/en-us/articles/360047765713-Where-can-I-find-logs-for-the-Postman-Application-

Thanks for your cooperation on this.
I am looking forward to hearing back from you!

via @Lincimary | Postman Support

**Comment by dsdasun** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "postmanlabs/postman-app-support"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月3日(星期二) 下午5:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [postmanlabs/postman-app-support] postman客户端登录后 账号中数据无法同步 (#10186)





 
Hi hello,
 
Thank you for reaching out to Postman.
 
I understand that you are receiving a connection error in the desktop app, Right?
 Sorry for the hassle, happy to assist!
 
Postman uses Web-Sockets to sync data between clients and our cloud services, and it is likely that the web-socket connection is being interrupted for some reason.
 
Are you using any of the VPN/proxy/firewall or antivirus applications on your device?
 If so, could you please try turning it off or terminating it completely and see if that helps?
 
Also, could you please try using another network such as a mobile hotspot and see if that helps?
 
If the issue persists, could you please tell me if you are able to use the web dashboard (go.postman.co) without any problem?
 
Additionally, if you can send me the application logs and attach it as a zip file to your response email, that would help us to investigate the issue further.
 Here is how you can find application logs:
 https://support.postman.com/hc/en-us/articles/360047765713-Where-can-I-find-logs-for-the-Postman-Application-
 
Thanks for your cooperation on this.
 I am looking forward to hearing back from you!
 
via @Lincimary | Postman Support
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by postman-staff** [comment]
Hi hello,

We would need to check with your postman account details on this.
Could you please write to us at help@getpostman.com for further assistance.

Please feel free to reach out to the above mentioned email address with the logs files mentioned.
Thanks!
via @Lincimary | Postman Support

**Comment by dsdasun** [comment]
我需要启用同步功能

**Comment by dsdasun** [comment]
我需要启用同步功能

**Comment by dsdasun** [comment]
我需要启用同步功能

**Comment by dsdasun** [comment]
我希望能够远程帮助我启用，postman账号的同步功能
