### ISSUE TITLE
Restart button to install update not working

### ISSUE THREAD

**Issue by xehpuk** [a85/POSTMan-Chrome-Extension#10195]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

Postman was notifying me that "An update has been downloaded for Postman. Restart now to install the update."
The "Restart" button to the right didn't do anything.

### Steps To Reproduce

1. Wait for the notification that an update has been downloaded.
2. Click the "Restart" button.
3. Ask yourself why nothing is happening.

### Environment Information

```markdown
- Operating System: Microsoft Windows [Version 10.0.19043.1110]
- Platform Type: Native App
- Postman Version: 8.8.0
```

### Additional Context?

The update was to version 8.9.1.

**Comment by postman-staff** [comment]
Hi,

Thank you for writing in and sorry for the hassle. We have reported this issue to the respective team.

We will let you know once we receive any updates on it. Thanks for your patience while we’re fixing it.

via @ash007-postman | Postman Support

**Comment by postman-staff** [comment]
Hi  @xehpuk,

Thank you for your patience! This issue has been fixed with the latest release. Can you please update the app with the latest version and let us know if you need any further assistance.

via @ash007-postman | Postman Support

**Comment by postman-staff** [comment]
Hi @xehpuk,

I'll be closing this from our end as we haven't heard back. If the issue persists, please reach out to us by submitting a ticket here: https://www.postman.com/support.

Have a nice day.


via @ash007-postman | Postman Support
