### ISSUE TITLE
url part from request not added to pm.request.url.host on 8.10.0

### ISSUE THREAD

**Issue by JelenaRy** [a85/POSTMan-Chrome-Extension#10198]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

On folder level there is a pre-request script, which fills the host from environment variables:
pm.request.url.host = pm.environment.get("environmentUrl"); 

On test level there is the second part of url, e.g. :
GET /healthcheck

When Get healthcheck is called, only the pm.request.url.host is used, but not the part in the test, i.e. instead of environmentUrl/healthcheck only environmentUrl is called

### Steps To Reproduce

1. Create an environment variable containing url, called "environmentUrl"
2. Use that environment 
3. On folder level in pre-request script add:
pm.request.url.host = pm.environment.get("environmentUrl"); 
3. Create a new Request, add the second part of the URL, e.g. 
GET /healthcheck
4. Call the new request

Expected to get pm.request.url.host/healthcheck called, got pm.request.url.host called

This worked on 8.9.1 version

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/78737751/128465386-0c90f3b3-8f35-45a2-90b6-570dd455a2c4.png)

### Environment Information

```markdown
- Operating System: Windows Server 2016
- Platform Type: Native App
- Postman Version: 8.10.0
```

**Comment by codenirvana** [comment]
@JelenaRy I understand your use case but this behavior is updated to fix a security vulnerability in our URL parser.

As a workaround, can you add any host (`localhost` etc.) to the URL? We'll fix this issue in the next release.

**Comment by JelenaRy** [comment]
Yes, will do, but would like to have previous behavior(without the security issue of course) when possible. Thank you!

**Comment by postman-staff** [comment]
Hi there,

We're going ahead and closing the support request for now, but we're still here so feel free to respond back to this thread if you have any further queries :)

Best,
Swapnil | Postman, Inc.

Status Page | Learning Center | YouTube | Twitch | Bugs + Feature Requests | Community

* * *

Product Support Business Hours: `Monday, 3:30 AM UTC - Friday, 11:30 PM UTC`

**Comment by JelenaRy** [comment]
Hi,
but the new version with the fix is not yet released? How can this issue be closed?

**Comment by postman-staff** [comment]
My apologies, I was not clearer earlier that, only the support request will be closed for now but the Github issue you've created still remains open, and you can share your feedback anytime. If you wish to keep the support request open as well then I'm happy to keep it. Feel free to respond back to this thread if you have any queries. :)

via @Swapnil-getpostman | Postman Support

**Comment by JelenaRy** [comment]
No worries, just eagerly waiting for the fix. Thank you! :)

**Comment by codenirvana** [comment]
@JelenaRy we've pushed a fix for this in `v8.11.0`. Can you update your app and confirm if this fixes your issue?

**Comment by JelenaRy** [comment]
Yes it is fixed, thank you!

**Comment by postman-staff** [comment]
Thanks so much for the update.

We're going ahead and closing the support request next, but we are still here so feel free to respond back to us on this thread if you have any further queries. :)

via @Swapnil-getpostman | Postman Support
