### ISSUE TITLE
Pull request open button not working

### ISSUE THREAD

**Issue by praveendvd** [a85/POSTMan-Chrome-Extension#10191]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

The pull request open button is not clickable , the link is only on the pull request name

### Steps To Reproduce

1. Create a fork
2. Create a pull request to source
3. Goto pull request history in the source collection
4. try clicking open

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/45095911/128152691-6ea38ff4-07d8-4dc6-801e-0d629b205e46.png)

### Environment Information

```markdown
- Operating System:  win 10
- Platform Type: web and desktop
- Postman Version: Version 8.9.1

win32 10.0.19042 / x64
```

### Additional Context?

The pull request name is clickable

**Comment by neilstudd** [comment]
Hi @praveendvd,

Do you mean the grey `OPEN` text on the right-hand side? This is a status label which shows the current status of the pull request; in your case, your PR is in an 'Open' state. Pull Requests may also be in other states, such as Merged or Declined, depending on their review status.

It probably becomes more apparent if you see other examples in this space:

![image](https://user-images.githubusercontent.com/7154703/128157701-e2d425f5-51b0-4491-bb82-dc1f9af1ee42.png)
 
There is still potentially a UX improvement here (if a user clicked this label, it would not be a surprise to them if it went to the pull request details page). I will feedback this to the team.

**Comment by praveendvd** [comment]
Thanks @neilstudd  that greyed out open doesn't looks like a status . I was trying to click it  for a long time, I thought its a button and is broke .

It would be great if we have any label saying it's a status

**Comment by ankitjaggi** [comment]
Closing this issue since the issue has been resolved. Feel free to open a new one for any other issues.
