### ISSUE TITLE
POST method dropped on redirect

### ISSUE THREAD

**Issue by rickmellor** [a85/POSTMan-Chrome-Extension#102]
When making a POST request to a URI that redirects POSTMan changes the request method to 'GET' and drops the form payload.  Should it not redirect to the new location using the same method and payload?  An example:

<<<<<<<<<<<<<<<<<<<<<<<<<<<< REQUEST <<<<<<<<<<<<<<<<<<<<<<<<<<<<

POST /services/people/rick@test.com HTTP/1.1
Host: 127.0.0.1:4242
Content-Length: 18
Origin: chrome-extension://fdmmgilgnpjigdojojpjoooidkmcomcm
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_1) AppleWebKit/537.1 (KHTML, like Gecko) Chrome/21.0.1180.89 Safari/537.1
Content-Type: application/x-www-form-urlencoded
Accept: _/_
Accept-Encoding: gzip,deflate,sdch
Accept-Language: en-US,en;q=0.8
Accept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.3

test=val&asdf=asdf

<<<<<<<<<<<<<<<<<<<<<<<<<<<< REDIRECT <<<<<<<<<<<<<<<<<<<<<<<<<<<<

HTTP/1.0 301 MOVED PERMANENTLY
Content-Type: text/html; charset=utf-8
Content-Length: 315
Location: http://127.0.0.1:4242/services/people/rick%40test.com/
Server: Werkzeug/0.8.3 Python/2.7.2
Date: Thu, 13 Sep 2012 21:37:31 GMT

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>Redirecting...</title>

<h1>Redirecting...</h1>

<p>You should be redirected automatically to target URL: <a href="http://127.0.0.1:4242/services/people/rick%40test.com/">http://127.0.0.1:4242/services/people/rick%40test.com/</a>.  If not click the link.

<<<<<<<<<<<<<<<<<<<<<<<<<<<< REQUEST <<<<<<<<<<<<<<<<<<<<<<<<<<<<

GET /services/people/rick%40test.com/ HTTP/1.1
Host: 127.0.0.1:4242
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_1) AppleWebKit/537.1 (KHTML, like Gecko) Chrome/21.0.1180.89 Safari/537.1
Accept: _/_
Accept-Encoding: gzip,deflate,sdch
Accept-Language: en-US,en;q=0.8
Accept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.3

**Comment by tshafeev** [comment]
Thats not matches RFC2616 http://tools.ietf.org/html/rfc2616#section-10.3.2 .

Note: When automatically redirecting a POST request after
      receiving a 301 status code, some existing HTTP/1.0 user agents
      will erroneously change it into a GET request.

**Comment by abhijitkane** [comment]
@anvarich @pwm You can use the "Automatically follow redirects" option in the Settings window for this. You'll need to install the Interceptor for this, though.

**Comment by ghost** [comment]
duplicates #1490
