### ISSUE TITLE
Postman Backup cannot be imported on non-packaged app

### ISSUE THREAD

**Issue by DemiTheurge** [a85/POSTMan-Chrome-Extension#1020]
I am unable to import a backup of all data (with multiple collections) since the format doesn't match that of backing up a single collection.  I have tried this on both the packaged and non-packaged versions, the packaged version yields an error while the non-packaged does not.  I am using the latest versions of both (downloaded 4/22/15).

The format created by the backup all data is:
{"version":1,"collections":[{"id":"08f23ea5-0b5c-1ac4-1b58-d72dcadb474c","name":"C2","timestamp":1429703546320,"requests":[{"collectionId":"08f23ea5-0b5c-1ac4-1b58-d72dcadb474c","id":"04b024d5-12d0-ff82-5b08-93bbb565b80a","name":"Test2","description":"","url":"http://localhost/test2","method":"GET","headers":"","data":[],"dataMode":"params","timestamp":0,"responses":[],"version":2}]},{"id":"da18636d-c2d6-574e-0d1e-eee961b9d538","name":"C1","timestamp":1429703542817,"requests":[{"collectionId":"da18636d-c2d6-574e-0d1e-eee961b9d538","id":"a2776cbf-20c4-ca23-760d-7f3273f63ab2","name":"Test1","description":"","url":"http://localhost/test1","method":"GET","headers":"","data":[],"dataMode":"params","timestamp":0,"version":2,"time":1429703578393}]}],"environments":[],"headerPresets":[],"globals":[]}

but the request that fails is:
requester.js:503:
for (var i = 0; i < collection.requests.length; i++) {

where collection has the value listed above, where requests is buried under collections[], and is not a top level element.  It appears there is a step of extracting collections from the backup.collections[] array which has not occurred.

I cannot find any other button to reimport the backup data on either version of the App.

**Comment by DemiTheurge** [comment]
Apparently the import backup data command exists in the packaged app, but does not exist in the non-packaged app.  It is found under Settings -> Data.

**Comment by vanjan** [comment]
I've got a similar problem: I exported all of my collections (from postman 2) to `Backup.postman_dump` and when I try to import it to postman 3 I'm getting the following error: 

```
Failed to import data. Format not recognized.
```

**Comment by abhijitkane** [comment]
@vanjan as @DemiTheurge mentioned, Backup files can be imported by going to Settings>Data>Import.
