### ISSUE TITLE
When changing Access Token property, old value gets exported

### ISSUE THREAD

**Issue by ondrix** [a85/POSTMan-Chrome-Extension#10200]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

when I change the access token value in collection and export the collection, the old value get's exported. 
when I change it in json to new value, import the collection, change it to something else the export will write the value I've changed manually in json.
Other changes in collection (eg. pre-request scripts) exports correctly.

### Steps To Reproduce

Collection -> Authorization -> Access Token 
change access token value

![image](https://user-images.githubusercontent.com/10441393/128476984-ef5aa652-80cd-46b5-bd7d-ff32ea0156e0.png)

Export Collection v2.1 -> old access token value gets exported

![image](https://user-images.githubusercontent.com/10441393/128477315-72ab6e18-9ff0-40c2-ac16-34659964ecbc.png)

### Environment Information

```markdown
- Operating System: Win 11
- Platform Type: Native App
- Postman Version: v8.10.0
```

**Comment by malvikach** [comment]
@ondrix thanks for raising the issue. We are looking at this bug, in the meanwhile I would suggest that you could try to create a duplicate collection using the existing collection upon updating your token value(make sure you have synced your token using the refresh button and saved your collection using save button) and please try to export that collection post that. This worked for me. 
Let us know if you face difficulty with this while we take care of the bug.

**Comment by malvikach** [comment]
@ondrix this is happening because the OAuth2.0 token hasn't been synced using the sync button. Please try to sync your token and save collection and then export the collection. See attached screenshot to identify the sync button. Let us know if you still face the issue.

![image](https://user-images.githubusercontent.com/89449769/132479307-25c69c15-5260-4773-96e7-01b9199ae705.png)

**Comment by timbochamp** [comment]
I'm going to close this where there's the option of manually syncing the token. For resolution into auto-syncing tokens, please follow #2452 and #10112
