### ISSUE TITLE
"Run" option missing on Context menu for Folders and collections

### ISSUE THREAD

**Issue by spotlesscoder** [a85/POSTMan-Chrome-Extension#10204]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request

### Is your feature request related to a problem?

I want to run healthcheck requests on different APIs quickly

### Describe the solution you'd like

When I have a folder with requests, I want to be able to right click the folder in the tree and have an option "run all".

Before the requests are run a confirmation dialog should be displayed for safety reasons as depending on the nature and amount of requests in the folder, the target might otherwise accidentally suffer a denial of service

**Comment by giridharvc7** [comment]
There's a Run option available for Folders, would this work for you? 
<img width="1009" alt="Screenshot 2021-08-09 at 5 22 33 PM" src="https://user-images.githubusercontent.com/1040583/128702027-e11666f2-16d4-4b1b-949e-016c2f749b47.png">

**Comment by spotlesscoder** [comment]
Kind of but I would find it more intuitive to also have it as context menu action too

**Comment by giridharvc7** [comment]
Agreed! This is surely a bug, we'll take it up.

**Comment by m3dbedb** [comment]
the feature does not work in centos 7 with postman 9.6.1

**Comment by robertmryan** [comment]
Any update on this? Where is this on the roadmap?

**Comment by malvikach** [comment]
@robertmryan Our team will be looking into this. We will share the release date for this soon.

**Comment by malvikach** [comment]
@robertmryan Happy to inform you that we have fixed this issue. The run option is now available under the folder context menu on the sidebar. 
<img width="378" alt="Screenshot 2022-06-29 at 2 31 42 PM" src="https://user-images.githubusercontent.com/89449769/176397407-17323eb3-5a9c-4569-884a-dc3cb2b7dfca.png">

We hope this helps! Please feel free to write to us about any other improvement areas. 
Cheers!
