### ISSUE TITLE
Schema Validation fails for responses using a content type containing a wildcard

### ISSUE THREAD

**Issue by elazar** [a85/POSTMan-Chrome-Extension#10213]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

Not sure if it's relevant, but this issue applies to a Postman collection created using https://github.com/postmanlabs/openapi-to-postman.

Here's an example of a response body specification that appears to trigger this issue.

```json
{
    "description": "OK",
    "content": {
        "image/*": {
            "schema": {
                "format": "binary",
                "type": "string"
            }
        }
    }
}
```

Sending a request that has this response triggers the following validation error:

> The response header "Content-Type" needs to be "image/*", but we found "image/png" instead

Per [section 4.7.15.1 of the OpenAPI 3.0.3 specification](https://spec.openapis.org/oas/v3.0.3#fixed-fields-12), specifically the description of the `contentType` field:

> The value can be a specific media type (e.g. application/json), a wildcard media type (e.g. image/*), or a comma-separated list of the two types.

It appears that Postman isn't correctly validating this use case.

### Steps To Reproduce

1. Create a request with a response that uses a wildcard in its content type, similar to the example given above.
2. Send the request.
3. Note that a schema validation issue appears.
4. Click the issue and note the specified error message.

### Screenshots or Videos

![Screenshot indicating a validation issue where the response `Content-Type` header matches the specified wildcard type in the schema](https://user-images.githubusercontent.com/15487/129070847-55601d65-c1ce-4d19-88f1-04594e049ec7.png)

![Screenshot of the schema validation error](https://user-images.githubusercontent.com/15487/129071210-1c94d27b-061e-4d2f-93d8-e68170d0a7f8.png)

![Screenshot from following the draft link scrolled down to reveal the cause of the error](https://user-images.githubusercontent.com/15487/129070844-6432174b-34f3-4e70-b1db-54c75f92a844.png)

### Environment Information

```markdown
- Operating System: Fedora 33
- Platform Type: Native App
- Postman Version: 8.10.0
```

**Comment by VShingala** [comment]
@elazar This issue is now fixed. Feel free to reopen it if you face any further problems.
