### ISSUE TITLE
Collection in my own workspace in our company account- Request are being deleted

### ISSUE THREAD

**Issue by d031342** [a85/POSTMan-Chrome-Extension#10216]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

In our Postman account of our company, when I am using My Workspace and create a collection with its request and environment variables, the request do not show up when I restart Postman.

Also, if I import a Collection, the requests disappear.

The creation of the requests are not displayed in the activity log

### Steps To Reproduce

One would need to check directly 

### Environment Information

```markdown
Postman for Web

Version 8.11.0-210809-1635

Chrome 92 / Mac OS 10.15.7
```

**Comment by postman-staff** [comment]
Hi  @RaquelSpain,

Thank you for reaching out. Can you please send us the screen record of the behavior at help@postman.com , also kindly let us know if you are able to replicate the same on the web- https://go.postman.co/

Looking forward to your response.

via @ash007-postman | Postman Support

**Comment by postman-staff** [comment]
Hi @RaquelSpain,

May I know if the issue still persists? If yes then kindly provide us more details via submitting a ticket here: https://www.postman.com/support

Thanks!
via @ash007-postman | Postman Support

**Comment by postman-staff** [comment]
Hi @RaquelSpain,

I'll be closing this from our end as we haven't heard back. If the issue persists then please reach out to us by submitting a ticket here: https://www.postman.com/support ​so that we can investigate further.

Have a nice day.

via @ash007-postman | Postman Support
