### ISSUE TITLE
Can't delete workspace. You are not permitted to perform the action.

### ISSUE THREAD

**Issue by slishnevsky** [a85/POSTMan-Chrome-Extension#10215]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

I am trying to delete a Workspace that I created before.

For some reason, I get this error from Postman:

**Can't delete workspace You are not permitted to perform the action.**

It is my workspace, that I have created. 

Why can't I delete it?

### Steps To Reproduce

1. From Workspaces menu, selected a workspace created by me
2. Selected "Delete" command from a menu

### Screenshots or Videos

![](https://i.stack.imgur.com/KX8p0.png)

![](https://i.stack.imgur.com/KKu24.png)

### Environment Information

```markdown
- Operating System: Win 10
- Platform Type: Postman Web
- Postman Version: Web Version
```

**Comment by postman-staff** [comment]
Hi there,

Thanks for writing in.

It looks like there is only 2 workspace in your account "Angus Workspace" & "Team Workspace". Please note that there are always 2 default workspaces when the account is created 1) "My Workapce" & 2) "Team Workspace" and these workspaces are default ones and cannot be deleted but can be renamed.

Now I have a doubt that you might have renamed the default "My Workspace" to "Angus Workspace" and now you are trying to delete it, which isn't possible.

Let me know if you have any other queries.

via @Swapnil-getpostman | Postman Support

**Comment by slishnevsky** [comment]
Oh, I see. I think that Angus workspace was created long time ago, about 4 years ago, maybe at that time there was no 2-Workspace policy, or maybe I don't remember renaming it. But it's ok, thank you !

**Comment by postman-staff** [comment]
Yes. Please feel free to respond back to this thread if you have any other queries.

via @Swapnil-getpostman | Postman Support
