### ISSUE TITLE
cannot open google chrome postman app suddenly

### ISSUE THREAD

**Issue by Zuckonit** [a85/POSTMan-Chrome-Extension#10211]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

postman app process is alive, but without ui. i cannot open it event downgrade chrome, restart macos, reinstall postman app. I tried what I can do, but still cannot open it. it's really strange, I can open it 1hour before, I don't know what happen?

### Steps To Reproduce

install chrome postman app, open it

### Environment Information

```markdown
google chrome version: 92.0.4515.107
os: mac os 10.14.4
chrome postman app: 5.5.5
```

**Comment by postman-staff** [comment]
Hi there,

Please note that - Postman's Chrome application is no longer supported & it is being deprecated a long time ago. To know more about the chrome app deprecation refer to the below link:

- https://blog.postman.com/goodbye-postman-chrome-app/

We recommend our users to download and install our native/desktop application which has tons of features that have been largely built out from requests received from our user base. You can download the native/desktop app using the below link. :)

- https://www.postman.com/downloads

Let us know if you have any further queries.

via @Swapnil-getpostman | Postman Support

**Comment by Zuckonit** [comment]
yes, I use chrome app cause it's convenient when cookie is necessary. now I quit chrome postman app and  turn to native one. but I found a bug about InterceptorBridge (the nodejs script), I have one commit for it, is there any repo of InterceptorBridge?

**Comment by vinitshahdeo** [comment]
@Zuckonit The source code for `InterceptorBridge` is not open-sourced. Please share your findings to help@postman.com with the subject as `Findings for GitHub issue #10211`.

**Comment by Zuckonit** [comment]
yes, already

**Comment by Zuckonit** [comment]
yes, already

**Comment by postman-staff** [comment]
Thanks for sharing your feedback and we confirm receiving your request on our support channel.

Feel free to respond back to us if you have any other queries.

via @Swapnil-getpostman | Postman Support

**Comment by Zuckonit** [comment]
ok, cool
