### ISSUE TITLE
"Pretty" response view render time is counted as part of response time.

### ISSUE THREAD

**Issue by toadicusrex** [a85/POSTMan-Chrome-Extension#1021]
I have a restful service method that replies back with about 500 records.  If I render with the "raw" view I get the elapsed time around 20 ms.  If I switch to pretty it jumps to around 350.  What gives?  Why would that be included in the response time?

**Comment by abhijitkane** [comment]
Not able to reproduce. @toadicusrex  Are you still seeing this with v3.0.4?

**Comment by toadicusrex** [comment]
No, it seems to be fixed.  Awesome!  Thank you!
