### ISSUE TITLE
postman crashing after running a request while the api is offline

### ISSUE THREAD

**Issue by nevadex** [a85/POSTMan-Chrome-Extension#10212]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

When I try and execute a request while the api that I am calling is offline, Postman crashes and I cannot hit cancel. If I try to kill it with task manager or with taskkill on cli it opens a ghost instance of postman which takes up no resources but I cannot close it until a system restart. I believe this has something to do with weird caching or from some bug with "keep alive" connections.

### Steps To Reproduce

1. Create any request to any offline service
2. Send the request

### Environment Information

```markdown
- Operating System: Windows 10 20H2
- Platform Type: Windows App
- Postman Version: 8.10.0
```

**Comment by postman-staff** [comment]
Hi @nevadex,

Could you try executing the same request from Postman's Web Application: https://go.postman.co - and see if you are able to get a response for them there?

* * *
For the desktop application, you may try clearing cache as per the article below and see if that helps?


- https://support.postman.com/hc/en-us/articles/360025359014-How-to-resolve-the-Could-not-open-Postman-error-

via @Raj-postman | Postman Support

**Comment by nevadex** [comment]
When sending the request from Postman Cloud, the page does not hang and I am able to cancel the request.

After clearing the desktop cache, the application still hangs and opens a ghost instance that does not close. I tried it with the Postman setting "Request timeout" at 5 seconds but it still crashed.

**Comment by postman-staff** [comment]
@nevadex Since this works alright on the Web, can we try adjusting the below values in Settings:

Increase the `Max response size` to 100 or 0 (Infinity) and also check if the request timeout is set to 0(infinity)? To do this please navigate: `Settings -> General`.

​  ![](https://postman.zendesk.com/attachments/token/CrBiE84H6VycNpPW4Mx7ZrrGK/?name=inline-1758483660.png)​
Once done try sending the request again and let us know how it goes.

* * *
If the issue persists - occurs only for this particular request and if it's publicly accessible then could you send the URL to us via postman.com/support to help us look into it further?

via @Raj-postman | Postman Support

**Comment by nevadex** [comment]
The issue still occurs, with Postman hanging and me having to restart. The issue occurs with any HTTP request method or URI, so to keep my service confidential I will not provide it unless necessary.

**Comment by postman-staff** [comment]
@nevadex Sure, we understand. If this happens with every other endpoint then providing the URL isn't required.

Can you try out on a generic request, say: https://api.spacexdata.com/v2/launches and see if you are able to **Cancel** or get the responses right without the application hanging?

* * *
If at all you continue to see the app hanging for this request as well, then please provide the logs as per the article below by submitting a ticket here: postman.com/support -


- Application Logs: https://support.postman.com/hc/en-us/articles/360025298633-How-to-collect-logs-
- Performance profile recording - here's a Loom recording that should show how to record the same.

Thanks for working with us to identify the underlying issue!

via @Raj-postman | Postman Support

**Comment by nevadex** [comment]
Generic requests work fine. I only get issues when I send a request to a address that exists but has no service or the service is offline. 

main.txt log:
`[22616][1628805805621][main][info]["Quitting app"]` (from last time I used postman)
`[10312][1629126329802][main][info]["Booting Postman 8.10.0, win32-10.0.19042 on x64"]
[10312][1629126329804][main][info]["EventBus~initialize - Success"]
[10312][1629126329805][main][info]["Proxy configuration has not been setup"]
[10312][1629126329806][main][info]["CloudProxyManager~init - Success"]
[10312][1629126329806][main][info]["UpdateHandler~init - Success"]
[10312][1629126330033][main][info]["RuntimeIPCAgent~started: Success"]
[10312][1629126330034][main][info]["LeaderSelection: Initialized successfully"]
[10312][1629126330152][main][info]["GPU detected VID 4318 DID 8578 ACTIVE false"]
[10312][1629126330152][main][info]["GPU detected VID 5140 DID 140 ACTIVE false"]
[10312][1629126330165][main][info]["Bootstrap-models~bootstrap - Success"]
[10312][1629126330207][main][error]["Error encountered while creating root CA",{"name":"Error","message":"Could not find openssl on your system on this path: openssl","stack":"Error: Could not find openssl on your system on this path: openssl\n    at C:\\Users\\Neev\\AppData\\Local\\Postman\\app-8.10.0\\resources\\app.asar\\node_modules\\pem\\lib\\openssl.js:237:23"}]
[10312][1629126330212][main][error]["Error generating rootCA certificate for HTTPS proxy",{"name":"Error","message":"Could not find openssl on your system on this path: openssl","stack":"Error: Could not find openssl on your system on this path: openssl\n    at C:\\Users\\Neev\\AppData\\Local\\Postman\\app-8.10.0\\resources\\app.asar\\node_modules\\pem\\lib\\openssl.js:237:23"}]
[10312][1629126330437][main][info]["window-manager~newSharedWindow: Shell loaded"]
[10312][1629126332065][main][info]["Main~AppEvents - Received booted event for process shared"]
[10312][1629126333944][main][info]["UpdateHandler~app-update-events - Received event",{"name":"checkForElectronVersionUpdated","namespace":"appUpdate"}]
[10312][1629126333951][main][info]["Main~AppEvents - Received booted event for process requester"]
`

Please let me know if I still need to submit all logs to postman/support or anything else.

**Comment by postman-staff** [comment]
@nevadex There should be a total of 6 files that should be zipped and sent to us. Let us check that part later, before that since the issue only occurs for offline or Internal API/Requests - I have a hunch that it could be related to the endpoint without any issues from the application. Few things to check further:


- Can you change the Network (to Mobile hotspot) and send requests - see if that helps?
- Can you try disabling GPU as mentioned in the [detailed steps here](https://github.com/postmanlabs/postman-app-support/issues/4594#issuecomment-391601621)?
- If the issue persists even after that, try [disabling hardware acceleration](https://learning.postman.com/docs/getting-started/settings/#gpu-hardware-acceleration) from the Help menu in Windows and see if that helps?

 ![](https://postman.zendesk.com/attachments/token/w5S2se8SCz9mAV8HX8wSZueBo/?name=inline-1849830974.png)​

Thanks for your cooperation on this.
I am looking forward to hearing back from you!

via @Raj-postman | Postman Support

**Comment by postman-staff** [comment]
@nevadex Just following up here. Let me know if the steps provided in my earlier response helped.

via @Raj-postman | Postman Support

**Comment by nevadex** [comment]
Sorry about the holdup, got busy.

I could not try mobile hotspot because my computer does not support WiFi.
Creating an env var to disable GPU did not fix the problem either. 
Disabling hardware acceleration unfortunately did not fix the problem as well.

**Comment by postman-staff** [comment]
@nevadex Sure, no issues.

Do you see the CPU usage maxed for the application by any chance? It would be great to have the application and net logs sent over to us by submitting a ticket here: https://www.postman.com/support - to help the team look into it further.

These details as below should provide additional insights required for the team:


> 1. Application Logs: https://support.postman.com/hc/en-us/articles/360047765713
> 2. [Console and Network logs.](https://www.youtube.com/watch?v=dORm5942QiA)
> 3. **Netlogs**: Launch the application using the following commands from the terminal on windows:
>
> `​C:\Users<username>\AppData\Local\Postman\Postman.exe --log-net-log="C:\Users<user-name>\Postman\postman-net.log" `
>
>   You can follow this [screen-record here](https://www.youtube.com/watch?v=ImTcK3RxByY) for reference or and share logs as per both methods to help us assist you further on the same.


via @Raj-postman | Postman Support

**Comment by postman-staff** [comment]
@nevadex Feel free to send over the logs by submitting a ticket here: https://www.postman.com/support and we will take a further look into it.

via @Raj-postman | Postman Support

**Comment by nevadex** [comment]
[Ticket-ID]
I also uploaded the logs here:
[Removed]

A couple changes:
I could not get Network and Console logs because they crashed along with the main application.
In the process Postman updated from 8.10.0 to 8.11.1
The issue only exists with me trying to send a request to a locally hosted service, with the exception that instead of requesting localhost, I request my local ip (192.168.20.227). Postman crashes when said service is offline.

**Comment by postman-staff** [comment]
@nevadex Thank you for sharing the logs. We will process this request next via ticket.

I've also edited your comment to redact the logs attached from this public thread here :)

via @Raj-postman | Postman Support

**Comment by nevadex** [comment]
Alright, thank you.
