### ISSUE TITLE
Api -> Generate Collection -> Request value not egual example Api parameter when example = 0

### ISSUE THREAD

**Issue by ThierryRassat** [a85/POSTMan-Chrome-Extension#10229]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

Hello Teams Postman,

Thank you for your fantastic tool!

I have this problem from Postman ( Windows 10 Application)

I create an API in which I put for example this parameter:

                    {
                        "name": "unlock",
                        "in": "query",
                        "description": "Forcer la deconnexion : 1 oui 0 non. 0 par defaut",
                        "required": true,
                        "schema": {
                            "type": "integer",
                            "format": "int32"
                        },
                        "example" : 0
                    }

In "example" if I put 1 and generate the collection then I will see in the query the value 1. 
But if I put 0, the value is -58475495? Do you think this is a bug?
I really want to see 0 in value, not -58475495

Kind Regards,
Thierry

### Steps To Reproduce

Create a Api with this parameter

                    {
                        "name": "unlock",
                        "in": "query",
                        "description": "Forcer la deconnexion : 1 oui 0 non. 0 par defaut",
                        "required": true,
                        "schema": {
                            "type": "integer",
                            "format": "int32"
                        },
                        "example" : 0
                    }
Generate Collection
See the result request and the value in parameter

### Environment Information

```markdown
- Operating System: Windows 10
- Platform Type: Microsoft
- Postman Version: 8.10.0
```

**Comment by ThierryRassat** [comment]
I choose "OpenApi 3.0"

**Comment by VShingala** [comment]
@ThierryRassat Thanks for reporting the issue! We were able to reproduce the issue and we'll start working on the fix for this.

**Comment by VShingala** [comment]
It'll be available with the next release of App but keeping issue open for now.

**Comment by DannyDainton** [comment]
Hey @VShingala, 

Did this get resolved with that release? Could this be closed now?

**Comment by VShingala** [comment]
@DannyDainton This is fixed now! I've verified the same so closing it now.

**Comment by VShingala** [comment]
@ThierryRassat Issue is fixed now. Feel free to open it if you're facing any further issues with it.
