### ISSUE TITLE
Getting Error: write ECONNABORTED on localhost request

### ISSUE THREAD

**Issue by adamijk** [a85/POSTMan-Chrome-Extension#10225]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

I am getting "Could not send request" on my localhost request I have tried to change the proxy http and https, but still i'm getting same issue, I spent hours to resolve the issue.
Please help, thanks in advance 
Error: write ECONNABORTED

![image](https://user-images.githubusercontent.com/26709821/129676584-80a8321f-b49e-4cc3-ba1b-39217d53aece.png)

### Steps To Reproduce

1. Open new tab and hit http://localhost:8080/abc

### Environment Information

```markdown
- Operating System: Windows
- Platform Type: 
- Postman Version: Postman v7.26.0
```

**Comment by xk0der** [comment]
@adamijk I would start debugging this from the server side. Check your server logs to find out why it is aborting the connection. Postman is just letting you know that the server aborted the connection you made.

Do other API calls to this server work fine? If it's this one single call failing, all the more reason to check things on the server side.

Also, check to see if generating the cURL command for you request and running it via command line gives you similar behaviour as Postman.

_Refer to_ https://learning.postman.com/docs/sending-requests/generate-code-snippets/ _on how to generate cURL code for your Postman request_

**Comment by DannyDainton** [comment]
Closing this out due to inactivity, if you're still facing the issue in the latest version of the platform, please open a new issue with the relevant information.
