### ISSUE TITLE
New Integration Request - <UiPath>

### ISSUE THREAD

**Issue by Tchuissi** [a85/POSTMan-Chrome-Extension#10227]
### Describe your current workflow

It's my first time using Postman

### Describe your ideal workflow

I would like to pull out data from UiPath to create automated dashboard with Power Query/BI

**Comment by shashankawasthi88** [comment]
@Tchuissi thanks for raising the request. Can you expand on your use case a bit more? How do you see the Postman fitting into this workflow?
