### ISSUE TITLE
When i requested to 'localhost' host, the Postman sends SYN to IPv6, and then connects to IPv4.

### ISSUE THREAD

**Issue by heli-os** [a85/POSTMan-Chrome-Extension#10221]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

When I send a requested to 'localhost' host, it attempts to connect without having a Request Header in IPv6 (probably SYN).

Why is it working like this? Isn't it common to send either IPv4 or IPv6 requests?

If [::1] is a host, it is normal (including request headers).
If 127.0.0.1 is a host, it is normal (including request headers).

### Steps To Reproduce

1. Open the Postman App
2. Set up Request
    * Method: Any(i tried GET / POST)
    * URL: http://localhost:8080/test?asdasdas=afdasfads
3. Send a Request

### Environment Information

```markdown
- Operating System: MacOS 11.4
- Platform Type: Native App
- Postman Version: 8.10.0
```

**Comment by DannyDainton** [comment]
Closing due to age and inactivity. If this is still an issue you're facing in the latest version of the platform, we can look at reopening this again.

**Comment by montdidier** [comment]
The reason this happens is because localhost exists in both ipv6 (as ::1) and ipv4 (as 127.0.0.1). It checks first to see if an ipv6 connection is available as RFC  3484 states
prefer ipv6 over ipv4 if both resolve and system supports ipv6. This is done with a connection check.

**Comment by heli-os** [comment]
@montdidier OMG! Thank you for your comment.
