### ISSUE TITLE
Switching between two different login/profiles shows error message "Something wrong in fetching data"

### ISSUE THREAD

**Issue by Pricilla09** [a85/POSTMan-Chrome-Extension#10222]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

I use two different Postman accounts, one with my official email ID and another with my personal email ID. I used to switch between them and work. After the recent upgrade I noticed an error message displayed in the bottom right "Something wrong in fetching data", whenever I switch, from personal account to office account and vise-versa too. Also the issue seems sporadic. 

Though I haven't noticed any different/issues with my collections so far. That just seems a notification and disappears in a while. 

### Steps To Reproduce

1. Try to create two different Postman account.
2. Try to switch from one profile to another.

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/71498483/129472332-9c84e142-004f-437d-ae48-fb752a8d3dd2.png)
![image](https://user-images.githubusercontent.com/71498483/129475250-fa7080d7-82ba-4622-b0f1-bc683c7e1ebe.png)

### Environment Information

```markdown
- Operating System: Win 10
- Platform Type: Native App
- Postman Version: v8.10.0
```

### Additional Context?

My Official account is using Postman Business plan and we use Team workspace.

**Comment by postman-staff** [comment]
Hi @Pricilla09

Thank you for reaching out to Postman.

I understand that you are receiving an error message that says "something went wrong while fetching the data" while switching different accounts within the desktop app, Right?

Sorry for the trouble, happy to assist!

I tried replicating from my end and see that the same error message appears while switching different accounts within the desktop app. At the same time replicating it on the web app does not show any error message.

I will circle back with the team and get back to you with further updates on this.
Thanks for your patience while we’re fixing this issue.

Please let us know if there is anything else I can do to help you in the meantime.

via @Lincimary | Postman Support

**Comment by postman-staff** [comment]
Hi @Pricilla09,

Thank you for reporting this bug , it seems that we need to escalate this to get it fixed. could you please write to us at help@getpostman.com along with the log file attached and mentioning the Github ID(10222).

Refer to the doc if you need additional help finding Postman's logs, please see this article.
Network logs and Browser console HAR logs

Please feel free to reach out to the above mentioned email address with the logs files mentioned.Thank you!

via @Lincimary | Postman Support

**Comment by postman-staff** [comment]
Hi @Pricilla09,
Thank you for flagging this with us.

We have escalated this case to your engineering team, and the team is working on it. I will keep you posted on any updates on this.

Your patience is much appreciated!

Best regards,
Lincimary​ | Product Support Engineer

Status Page | Learning Center | YouTube | Twitch | Bugs + Feature Requests | Community

* * *

Product Support Business Hours: `Monday, 3:30 AM UTC - Friday, 11:30 PM UTC`

**Comment by postman-staff** [comment]
Hi @Pricilla09,

Sorry that it is taking a longer time than expected.

Our Engineering team is working towards the fix and it will be merged into production as soon as possible, we will keep you posted once I have any updates on this.

We appreciate your patience. Thank you so much!

via @Lincimary | Postman Support

**Comment by postman-staff** [comment]
Hi @Pricilla09,

Thank you so much for your patience. Sorry for the radio silence.

The reported issue is now fixed and deployed into production. Update the application to the latest version (v9.0) to check and see if that works for you.

 As of now, I'm going ahead and closing this conversation, but I’m still here so feel free to give me a shout if you have any further queries :)

Thank you for sharing your feedback.

via @Lincimary | Postman Support
