### ISSUE TITLE
Add GitHub sign in method

### ISSUE THREAD

**Issue by mStirner** [a85/POSTMan-Chrome-Extension#10220]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request

### Is your feature request related to a problem?

no

### Describe the solution you'd like

Add GitHub as sign-in method to a postman account. 
Goggle is already there, should not be to hard to ad GitHub support.

![Screenshot 2021-08-14 at 13-19-55 Postman - Sign In](https://user-images.githubusercontent.com/5003424/129444720-d40e0e90-4052-41f8-97f2-8cbdf6c06187.png)

Add here a button/option to sign in with GitHub

### Additional context

Already to many accounts. Nearly every Developer has a GitHub account.

**Comment by ArjunSingh-PM** [comment]
We do not have plans to enable GitHub sign-in in the near future.

**Comment by ArjunSingh-PM** [comment]
We do not have plans to enable GitHub sign-in in the near future. Closing for now.

**Comment by ArjunSingh-PM** [comment]
We do not have plans to enable GitHub sign-in in the near future. Closing this issue for now.

**Comment by ArjunSingh-PM** [comment]
We do not have plans to enable GitHub sign-in in the near future. Closing for now.
