### ISSUE TITLE
Headers in Preview are lying

### ISSUE THREAD

**Issue by geon** [a85/POSTMan-Chrome-Extension#1022]
The preview shows only the headers _set_ by postman, not the headers that will actually get sent. Chome adds referer, user-agent and such.

I just lost a whole day of work trying to figure out why a web service wasn't working.

**Comment by abhijitkane** [comment]
If you click on 'Limitations' (to the right of HTTP request and Curl), there's a popup which says that 'Automatic headers sent by Chrome cannot be previewed'. Chrome sends headers based on the user's settings, cookies, and the Chrome version, and there's no way for us to be aware of these headers in Postman.
