### ISSUE TITLE
Incorrect Mock Server count shown over the App UI

### ISSUE THREAD

**Issue by Swapnil-getpostman** [a85/POSTMan-Chrome-Extension#10232]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

I'm seeing an incorrect mock server count over the Workspace Overview page and when I navigate the mock server tab then there are no mock servers present.

Screenshot 1

<img width="1306" alt="mock1" src="https://user-images.githubusercontent.com/52168965/130001750-69609330-2efa-490d-b0b0-2581ca3ae6c5.png">

Screenshot 2

<img width="1086" alt="mock2" src="https://user-images.githubusercontent.com/52168965/130001762-86969f4c-61ca-413b-a765-a2fd829d3ee0.png">

### Steps To Reproduce

1. Open the app 
2. Navigate the workspace Overview page and you see the mock server count and after navigating the mock server tab in the same workspace there are no mock servers seen.

### Environment Information

```markdown
- Operating System: Windows
- Postman Version: 8.6.2
```

### Additional Context?

Looks like the mocks don’t exist but the references maintained by Workspaces are still present. 

Filed by Postman Support on behalf of a user report internally.

**Comment by akshay-kulkarni-03** [comment]
Hi @Swapnil-getpostman  , our workspace overview section was revamped and the inconsistencies reported in the above screenshot were also fixed as part of that. 
Feel free to re-open this issue in case you face the issue again.

**Comment by sameddin** [comment]
Still reproducible for me. Postman v9.14.11

![image](https://user-images.githubusercontent.com/13615527/157495163-184efd15-5f9e-42a3-8556-5f4c30928a9f.png)

**Comment by sony-mathew** [comment]
Hey @Swapnil-getpostman @asi-postman

I hope you're doing well! I took a closer look at this issue and noticed that the concern you raised is no longer relevant after our recent workspace overview revamp. As a result, I'm going to close this issue for now.

However, if you still have concerns or if this revamp didn't quite address your needs, please don't hesitate to reopen this issue. I'm here to help and want to make sure you're able to get the most out of our workspace.

Thanks for your understanding, and I look forward to hearing from you if you need further assistance!
