### ISSUE TITLE
Add better UI feedback for restricted headers. (Cookies not sent to server)

### ISSUE THREAD

**Issue by celesteking** [a85/POSTMan-Chrome-Extension#1023]
Write this damn thing in docs on first page, please. So other people don't waste time. Thanks.

**Comment by a85** [comment]
Did you even see the docs? http://getpostman.com/docs/requests

**Comment by celesteking** [comment]
Apparently, I didn't get to that. It would be extremely handy if you could highlight the header box in RED when one of those header names are entered into the box and, possibly, disable the SEND button.

**Comment by shamasis** [comment]
@celesteking we released a canary version of our Mac app that allows you to send restricted headers. http://blog.getpostman.com/2016/06/14/introducing-postman-runtime-more-power-better-control/
