### ISSUE TITLE
Postman API: include uid and name properties for mocks and monitors when querying workspace resources

### ISSUE THREAD

**Issue by carrrson** [a85/POSTMan-Chrome-Extension#10236]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request

### Is your feature request related to a problem?

Currently, when using the Postman API request to get a single workspace, `https://api.getpostman.com/workspaces/{{workspace_id}}`, the response includes `uid` and `name` properties for collections and environments, but for mocks and monitors, only an `id` property is returned. 

This `id` property seems to work to query and delete the resource in place of the `uid` when querying and deleting the resources, but the documentation is unclear about this. So not a huge deal, but would be great to have a name returned here in the workspace overview. 

current response:
```
 "workspace": {
        "id": "xxx",
        "name": "My workspace",
        "type": "team",
        "description": null,
        "collections": [
            {
                "id": "xxx",
                "name": "My Collection",
                "uid": "xxx"
            }
        ],
        "environments": [
            {
                "id": "xxx",
                "name": "a very good env",
                "uid": "xxx"
            }
        ],
        "mocks": [
            {
                "id": "xxx"
            }
        ],
        "monitors": [
            {
                "id": "xxx"
            }
        ]
    }
}
````

### Describe the solution you'd like

Return a `name` and `uid` property for mocks and monitors when querying a single workspace using the Postman API. Could also be good to update the Postman API documentation to note that the `id` works in place of the `uid` property to query/delete these resources as well. 

### Describe alternatives you've considered

I know that you can use this `id` property to query for the full resource details if they are truly needed, so this is super low priority and would just be a convenience to cut out an extra step. Thank you!

**Comment by davidespihernandez** [comment]
Hi, @carrrson!
This is already done. Please check our documentation and examples for the `GET workspaces` endpoint [here](https://www.postman.com/postman/workspace/postman-public-workspace/example/12959542-1ff78a54-2643-4f71-b63c-8bd9d07442e5).
