### ISSUE TITLE
Postman crashes when RENDERING reponses bigger than 100 kb

### ISSUE THREAD

**Issue by JoaoPedroMDP** [a85/POSTMan-Chrome-Extension#10235]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

I know that there are some issues about Postman crashing with large responses, but mine is not that large (saw that latest version supports even 500mb!), just 400kb.

While i was looking in htop trying to find the cause i found that the renderer proccess was steadly using 101% of one of my cores. So basically the problem is not about the size of request, it's about rendering a complicated view.

I made a Mocky with the response i was trying to render in Postman, so you can reproduce in your PCs
https://run.mocky.io/v3/ada97887-484d-4a8a-9c82-231b58edb2d7

I tried to open it with my Graphics card but no success

### Steps To Reproduce

1. Use this [mock](https://run.mocky.io/v3/ada97887-484d-4a8a-9c82-231b58edb2d7) to render a view in postman.

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/34918112/130072235-e92662e2-beeb-4949-8129-0722b292ac2c.png)

### Environment Information

```markdown
- Operating System: Ubuntu 20.04
- Platform Type: Native App, installed by Snap
- Postman Version: Version 7.36.5

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   39 bits physical, 48 bits virtual
CPU(s):                          4
On-line CPU(s) list:             0-3
Thread(s) per core:              2
Core(s) per socket:              2
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           142
Model name:                      Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
Stepping:                        9
CPU MHz:                         800.004
CPU max MHz:                     3500,0000
CPU min MHz:                     400,0000
BogoMIPS:                        5799.77
Virtualization:                  VT-x
L1d cache:                       64 KiB
L1i cache:                       64 KiB
L2 cache:                        512 KiB
L3 cache:                        4 MiB

RAM: 16 gb

Graphics Card: NVIDIA Corporation GM107 [GeForce 940MX] (rev a2)
```

**Comment by postman-staff** [comment]
Hi @JoaoPedroMDP,

Just checked this from my end and looks like I was able to get this right in the latest version of the application (Version 8.10.0).  Do check if you are in the latest version, if not try updating and see if that helps.

 ![](https://postman.zendesk.com/attachments/token/5YVVJR3cFJn3T0mJpk1oGxgZX/?name=inline323389876.png)

To let you know, the processor issues are already being tracked in these threads: #6723 and [#​7870.](https://github.com/postmanlabs/postman-app-support/issues/7870) If you have an account with Postman then you should be able to get around this situation by testing it on Postman Web: https://go.postman.co/home. Postman web enables you to use all the features on the Web as in the app.

via @Raj-postman | Postman Support

**Comment by postman-staff** [comment]
@JoaoPedroMDP Just following up here. Let me know if the steps provided in my earlier response helped.

via @Raj-postman | Postman Support

**Comment by postman-staff** [comment]
Hi @JoaoPedroMDP,

I'll be closing this next on our end as we haven't heard back. If the issue persists, please reach out to us by submitting a ticket here: https://www.postman.com/support ​so we can investigate further.

via @Raj-postman | Postman Support
