### ISSUE TITLE
Cannot use POSTMAN in my mac having high sierra

### ISSUE THREAD

**Issue by gautam-ravi** [a85/POSTMan-Chrome-Extension#10230]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

After I updated my POSTMAN from an old version to 8.10.x (which is the latest) am not able to use it. It crashes whenever I click on SEND

### Steps To Reproduce

1. Update POSTMAN from an old version (I think I was having 7.x
2. Restart postman, when postman opens, in your collections - select an API and click on SEND
3. POSTMAN app gets crashed everytime.

### Environment Information

```markdown
- Operating System: macOS High Sierra ver 10.13.6
- Platform Type: Mac OSX
- Postman Version: v8.10.0
```

**Comment by postman-staff** [comment]
Hi  @gautam-ravi,

Request you to please provide the logs as explained in this article: https://support.postman.com/hc/en-us/articles/360047765713-Where-can-I-find-logs-for-the-Postman-Application- by submitting a ticket to us: http://postman.com/support. We will check this further from there.

Additionally, you can try Postman web - https://go.postman.co/ to get yourself unblocked.

via @ash007-postman | Postman Support

**Comment by postman-staff** [comment]
Hi @m3dbedb,

We haven’t heard back from you. If the issue still persists then I would request you to please provide the requested logs by submitting a ticket via: http://postman.com/support to further investigate the issue.

via @ash007-postman | Postman Support

**Comment by postman-staff** [comment]
Hi @m3dbedb,

I'll be closing this conversation from our end as we haven't heard back. If the issue persists, please reach out to us by submitting a ticket here: https://www.postman.com/support ​so that we can investigate further.

Have a nice day.
via @ash007-postman | Postman Support
