### ISSUE TITLE
Multiple Content-Type headers in request headers when generate collection from openapi definition causes problem with validation

### ISSUE THREAD

**Issue by Aikain** [a85/POSTMan-Chrome-Extension#10241]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

When I created the collection from openapi definition, I noticed that two content-type headers were found in the request header information.

Requests work, but validation points to an issue. And if I make the recommended changes, the Content-Type headers are missing and body is 'none'. Another validation show that everything is fine even body is missing.

### Steps To Reproduce

1. Create API: OpenAPI 3.0 & YAML
2. Define:
```yaml
openapi: 3.0.0
info:
  version: 1.0.0
  title: Test

paths:
  /test:
    post:
      summary: Test
      requestBody:
        $ref: '#/components/requestBodies/Test'
      responses:
        '200':
          description: OK

components:
  requestBodies:
    Test:
      content:
        application/json:
          schema:
            type: object
            properties:
              test:
                type: string
```
3. Generate collection (Develop > Dokumentation > Add documentation)
4. Click validate
5. Reviews issues: select all changes and confirm changes to collection
6. Try to validate again
7. Go to watch request body and headers in collection

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/5877174/130324623-66d8aaf2-ef30-45f8-8966-ab78ddab1a02.png)
![image](https://user-images.githubusercontent.com/5877174/130324633-013e9588-8d82-41eb-b402-ba8af361ed4c.png)

After validation:
![image](https://user-images.githubusercontent.com/5877174/130324649-53ec29e3-debc-43a2-b04b-67269e2af830.png)

After "Select all changes" and "Confirm Changes to Collection":
![image](https://user-images.githubusercontent.com/5877174/130324702-5e3cc330-f550-42e2-a455-af6e510d66d3.png)
![image](https://user-images.githubusercontent.com/5877174/130324716-516c6e02-56cf-49e8-9fba-28cbddaf5d9b.png)
![image](https://user-images.githubusercontent.com/5877174/130324721-fadb518c-02d8-4d7f-9904-974643a14332.png)

### Environment Information

```markdown
- Operating System: Windows 10 Pro N, 21H1
- Platform Type: Native App
- Postman Version: 8.10.0
```

**Comment by VShingala** [comment]
@Aikain This should be fixed now. Feel free to open this issue if you're still having any issues on this.
