### ISSUE TITLE
"Share environment" default options are in different sequence in web vs app

### ISSUE THREAD

**Issue by ash007-postman** [a85/POSTMan-Chrome-Extension#10248]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

Share environment - default options are in changed sequence in web vs app which creates confusion for the users. These options should be unified across.

Application:
![image](https://user-images.githubusercontent.com/41741228/130616456-432c3592-7dc6-4160-911b-dc4f9868e4a6.png)

Web:
![image](https://user-images.githubusercontent.com/41741228/130616497-56cf9d0c-8210-4d56-92b9-d571c2e58dd3.png)

### Steps To Reproduce

1. Go to Environments
2. From the dropdown click on share environment 
3. Select the respective workspace 
4. There are two options **Share and remove environment from current workspace** & **Share environment**

### Environment Information

```markdown
- Operating System: 
- Platform Type: 
- Postman Version:
```

**Comment by malvikach** [comment]
Hi @ash007-postman please check the version of the app as well . I wasn't able to replicate it on the latest version (v8.12).

**Comment by ash007-postman** [comment]
Hi @malvikach, yes I can no longer see this issue with the latest version. Thanks 🙌

**Comment by malvikach** [comment]
@ash007-postman would it be possible to check what version you were using earlier? we might still need to check if its a bug

**Comment by ash007-postman** [comment]
Hi @malvikach It was 8.6.1.
