### ISSUE TITLE
Generated Axios code missing config parameter

### ISSUE THREAD

**Issue by nikita-fuchs** [a85/POSTMan-Chrome-Extension#10247]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

Generated JS / Axios POST request code throws the following error: 
`Error [ERR_FR_MAX_BODY_LENGTH_EXCEEDED]: Request body larger than maxBodyLength limit`

In my case, it's a `multipart request`, not sure if that makes a difference.

One option parameter is missing in the generated code to solve the issue: 

```
var config = {
    ...
    maxBodyLength: Infinity,
    ...
}, 
```
maybe someone else has a better idea.

### Steps To Reproduce

1. Generate multipart POST request with axios
2. generate code for Javascript -> Axios 
3. Receive error: `Error [ERR_FR_MAX_BODY_LENGTH_EXCEEDED]: Request body larger than maxBodyLength limit`

### Environment Information

```markdown
- OSX 
- Postman 8.10
- axios 0.21.1
```

**Comment by shubhbhargav** [comment]
@nikita-fuchs Can you please share a screenshot / video recording of the issue to help us debug this better?

**Comment by DannyDainton** [comment]
Hey @nikita-fuchs 

Could you please provide the required details for us to triage the issue? If this is no longer an issue for you, we can close this out.

**Comment by nikita-fuchs** [comment]
<img width="1164" alt="image" src="https://user-images.githubusercontent.com/11761828/158992741-9813a8bf-8419-4930-bca7-8cf6eb43a8d7.png">

Hey, sorry for not getting back faster. Not sure if the screenshot adds more clarification or confusion, but to summarise this issue again: The `Axios` library shown here has a _default_ upload size limit of 10MB. This means that the generated code will **fail** for files >10 MB. To prevent this, the shown `config` object needs an additional property added to prevent requests from failing, which is this one: 
```
var config = {
    ...
    maxBodyLength: Infinity, <----- add this to the generated code output
    ...
}, 
```

**Comment by dhwaneetbhatt** [comment]
Hi @nikita-fuchs, I confirmed that this has been fixed a while back. Closing this issue, feel free to reopen if problem persists.
