### ISSUE TITLE
Duplicate global variables do not save or switch current values

### ISSUE THREAD

**Issue by lflucasferreira** [a85/POSTMan-Chrome-Extension#10249]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

Hi there,

I just found out a bug when trying to save my global variables (I do not know if it happens in the environment variables panel).

I recorded it in order to help you see what is going on.

There are two scenarios where I save the variable and it is deleted or switched between the enabled and the disabled variables having the same variable name.

### Steps To Reproduce

1. Open the global variables panel
2. Add two variables having the same name
3. Reproduce what is in the next section (screenshots or videos)

### Screenshots or Videos

Scenario 1 - The current value is deleted:

https://user-images.githubusercontent.com/5920654/130635101-ed6e6295-304b-4551-bd6b-279f3598ff8b.mp4

Scenario 2 - The disabled current value is saved into the enabled variable and vice-versa:

https://user-images.githubusercontent.com/5920654/130635133-7bf6dbee-e219-47f3-9af9-c9b3e9516012.mp4

### Environment Information

```markdown
- Operating System: Ubuntu 18.04.5 LTS
- Platform Type: Postman for Linux | linux 5.4.0-80-generic / x64
- Postman Version: Version 8.11.1
```

**Comment by B-Rinat** [comment]
Hi,

I am having the exact same issue. Please help.

- Operating System: Windows 10
- Platform Type: Postman for Windows | win32 10.0.19043 / x64
- Postman Version: Version 8.11.1

**Comment by timbochamp** [comment]
Thanks for reporting! We're investigating this and will provide updates when this is resolved

**Comment by Raj-postman** [comment]
Just to add to the initial report, 

- The current value of the Global variables isn't saved the first time.
- The value gets saved the second time.
- Issue is only present for current value and not initial value.
- Reproducible both on App and Web.
- It looks like a visual bug since the values get saved when we look through the quick view. [Reference video here.](https://www.loom.com/share/ca6a0eccaf9b45bb84a34c6ea6d02664)

**Comment by Raj-postman** [comment]
Marking this to `Closed` since the issue is now resolved 💯
