### ISSUE TITLE
Unable to launch Postman v8.10.0 after update

### ISSUE THREAD

**Issue by nekogal** [a85/POSTMan-Chrome-Extension#10243]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

I'm unable to load Postman client on Windows Server 2016 Datacenter, after updating to v8.10.0. I'm stuck at a black loading window, and the app doesn't launch.

No problems on Windows 10.

### Steps To Reproduce

1. Update Postman app to v8.10.0
2. Click on Postman icon to launch

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/89377686/130403343-b705d4b7-9c89-498c-b4bf-dac7e4b3bd51.png)

### Environment Information

```markdown
- Operating System: Windows Server 2016 Datacenter
- Platform Type: Desktop App
- Postman Version: 8.10.0
```

**Comment by postman-staff** [comment]
Hey @nekogal!

Thanks for getting in touch!

Recently we have started seeing such issues and looks like you'll need to make some changes to the GPU settings. Could you try launching the Postman desktop app with GPU settings disabled and see how it goes?

Disabling GPU rendering for Postman generally allows the app to run successfully. To do so, you'll need to add a Windows environment variable: `POSTMAN_DISABLE_GPU`, with the value: `true`

For your reference, please follow the below steps:

1. Open: `Advanced system settings `

 ![](https://s3.amazonaws.com/postman-static-getpostman-com/postman-docs/Troubleshootwindows6.1.png)

2. Navigate to: `Environment Variables `
 ![](https://s3.amazonaws.com/postman-static-getpostman-com/postman-docs/Troubleshootwindows6.12.png)

3. Add a new system variable with the name: `POSTMAN_DISABLE_GPU`, and the value: `true `
 ![](https://s3.amazonaws.com/postman-static-getpostman-com/postman-docs/Troubleshootwindows6.1+(1).png)

4. Click OK to _save_ then Logout and Login back or Restart your PC and Postman app as well.

You can also find the steps to disable GPU here and we also have documentation for the same.

Let me know if that helps. Looking forward to your response.
via @taehoshino | Postman Support

**Comment by nekogal** [comment]
The suggested fix works! Thanks!

**Comment by postman-staff** [comment]
Excellent! Glad to hear it worked!

Thanks again for reaching out! Have a great day!

via @taehoshino | Postman Support
