### ISSUE TITLE
App fails to Sync

### ISSUE THREAD

**Issue by jrummell** [a85/POSTMan-Chrome-Extension#1024]
I've been having an issue with the app version (not in a Chrome tab) over the past few days. Whenever I open Postman, it displays the Syncing indicator for a while and then says that it fails. This would only be a minor inconvenience, but most of my POST values are now missing from my collections.

**Comment by abhijitkane** [comment]
We'll be pushing an update today that should resolve most of the in-app issues. What does the error message say?

**Comment by jrummell** [comment]
I think it just says "Not in sync", but I'll have to wait until it gives up again. It might be related to my internet connection dropping every now and then.

**Comment by jrummell** [comment]
![notinsync](https://cloud.githubusercontent.com/assets/495979/7298953/f5a9edc0-e9a0-11e4-9f23-bab2585a23b3.PNG)

**Comment by jrummell** [comment]
Seems to be working fine today. Thanks!
