### ISSUE TITLE
JSON data in "pretty" mode is displayed incorrectly if it contains Unicode character eg \u0022

### ISSUE THREAD

**Issue by nxandrzej** [a85/POSTMan-Chrome-Extension#10255]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

Postman application incorrectly displays json data in "pretty" mode if it contains unicode character eg \u0022

{ "result" : [["2021-08-26T14:08:58", "an\\u0022antest", 1266, "antest", null, null, 4049, 1, null, null, "328661", "72734", 9, null, 4357, null, 0, null]] }

A character \u0022 is converted to "
In RAW mode, the data is presented correctly and there is no problem when the data is loaded, eg 
var jsonData = JSON.parse (responseBody);
The problem only affects the display of data in "pretty" mode.

Best regards,
Andrew

### Steps To Reproduce

1. Respons tab in "pretty" mode
2. Server respons  contain unicode characters eg \u0022
{ "result" : [["2021-08-26T14:08:58", "an\\u0022antest", 1266, "antest", null, null, 4049, 1, null, null, "328661", "72734", 9, null, 4357, null, 0, null]] }

### Screenshots or Videos

![Screenshot_1](https://user-images.githubusercontent.com/89587226/130967162-78b85294-08b8-484b-bfad-b4f38520e505.png)

![Screenshot_2](https://user-images.githubusercontent.com/89587226/130967194-e8911079-fdcc-4f5a-b8b0-fec3d7d73891.png)

### Environment Information

```markdown
Postman for Windows
Version 8.11.1
win32 10.0.19043 / x64
```

**Comment by postman-staff** [comment]
Hi @nxandrzej

Thanks for sharing your report.

Just want to update you that we are already tracking this issue internally and our team is working on it. Feel free to share any other updates that you may have over this thread.

via @Swapnil-getpostman | Postman Support

**Comment by nxandrzej** [comment]
Thank you very much!

wt., 28 cze 2022 o 17:17 Saeed Gatson ***@***.***> napisał(a):
