### ISSUE TITLE
Request is working with wrong  Session ID

### ISSUE THREAD

**Issue by urmi-patel1905** [a85/POSTMan-Chrome-Extension#10250]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

While testing JIRA REST APIs, I am creating a bug in the Jira platform and I have created a session-id for the same but with the wrong session-id, the request is working fine.

### Steps To Reproduce

Open new request.
given session-id in the header.
Hit the post request
Again change the session id.
Hit same post request with changed session id.
the 

### Screenshots or Videos

https://user-images.githubusercontent.com/81142658/130729993-b3a1bc8c-12ef-4429-8e67-509bbbf88f02.mov

### Environment Information

```markdown
- Operating System: Mac OS X 19.6.0 / x64
- Platform Type: Native App
- Postman Version: Version 8.1.0
```

**Comment by xk0der** [comment]
Hey @urmi-patel1905 👋  you should be able to use the Postman-Console to verify if the right header value was sent. If you are using the native app, the console can be accessed by navigating to the menu `View` > `Show Postman Console`
In both the native app and web-app, you can access the console by clicking on the "console" icon located at the bottom right.

_Console button_
![Screen Shot 2021-08-25 at 5 24 07 PM](https://user-images.githubusercontent.com/21366/130731330-c5f4b5e2-402a-40aa-832a-449db0c3c783.png)

In the console, expand the request you want to check and then expand the "Request Header" section for this request and verify the Cookie header's value that was sent. If the right value is shown in the console. You should verify at your server's end to understand what may be going wrong.

_Example Console Screenshot_
![Screen Shot 2021-08-25 at 5 25 37 PM](https://user-images.githubusercontent.com/21366/130731428-1de8e5be-eb16-4a04-a2b2-54cca5974764.png)


Do share the console's screenshot if the console shows the wrong value too.

Reference: https://learning.postman.com/docs/sending-requests/troubleshooting-api-requests/#using-the-console

**Comment by urmi-patel1905** [comment]
It is giving wrong in the console also.

<img width="1440" alt="Screenshot 2021-08-25 at 11 13 52 AM" src="https://user-images.githubusercontent.com/81142658/130733529-6ec96247-f976-42c3-ab47-e9195c7efd57.png">

**Comment by xk0der** [comment]
@urmi-patel1905 try saving the request by clicking on the save button after making changes and then send the request. Check the console again and see if the updated values is shown.
![Screen Shot 2021-08-25 at 6 04 56 PM](https://user-images.githubusercontent.com/21366/130735218-0f0d6647-1a59-42ab-9523-e150d2a396a0.png)


In your initial report you have mentioned the Postman version as `8.1.0` can you confirm that once? 
Postman's latest version is `8.11.1` - download that if you are not on the latest version and see if that one works fine for you.
https://www.postman.com/downloads/

**Comment by postman-staff** [comment]
@urmi-patel1905 We are hoping that the information last shared was helpful. Let us know if the issue persists.

via @Raj-postman | Postman Support

**Comment by postman-staff** [comment]
@urmi-patel1905 We will be closing this from our end as we haven't heard back. If the issue persists, please reach out to us by submitting a ticket here: https://www.postman.com/support ​to investigate further.

Have a nice day.

via @Raj-postman | Postman Support
