### ISSUE TITLE
Postman test script for json schema validation failing for some custom format types in json schema

### ISSUE THREAD

**Issue by raghav19** [a85/POSTMan-Chrome-Extension#10256]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

Postman Schema validation using the following method is failing with validation error in tests. The schema is part of pre-request script which saves the schema object as a collection variable.

```
pm.test("Validate response schema", function () {
   pm.response.to.have.jsonSchema(pm.collectionVariables.get("create_key_schema"));
});
```
Similar way this also occurs for another type `uint8`. Is it like, jsonSchema validation in postman is inclined only for Javascript based backend APIs?

### Steps To Reproduce

1. Create a schema as below screenshot
2. Set it as a collection variable object
3. use the above test in tests tab and run
4. The error given in the screenshot is observed

### Screenshots or Videos

Schema:
![image](https://user-images.githubusercontent.com/21075059/130992066-8194e6fe-cc20-4592-868b-e9bf77c89f16.png)

Error:
![Uploading image.png…](https://aws1.discourse-cdn.com/business6/uploads/getpostman/original/2X/2/29dcf7f1620105310b3b759c89234a5363fe3b80.png)

### Environment Information

```markdown
- Operating System: Windows 10
- Platform Type: Native App
- Postman Version: 8.11.1
```

**Comment by xk0der** [comment]
Hey @raghav19 👋  looks like the "Error" screenshot didn't come through. Please do edit the description and attach it again.

**Comment by raghav19** [comment]
@xk0der Updated the image

**Comment by postman-staff** [comment]
Hi @raghav19,

Would you be able to send us the schema via submitting a ticket here: https://www.postman.com/support
to investigate further?

Thanks!

@ash007-postman

**Comment by postman-staff** [comment]
Hi @raghav19,

We haven’t heard back from you, would you be able to send us the schema via submitting a ticket here: https://www.postman.com/support so that we can investigate further.

via @ash007-postman | Postman Support

**Comment by postman-staff** [comment]
Hi @raghav19,

I'll be closing this from our end as we haven't heard back. If the issue persists, please reach out to us by submitting a ticket here: https://www.postman.com/support ​to investigate further. Have a nice day.

via @ash007-postman | Postman Support
