### ISSUE TITLE
Return Array of IDs Inline

### ISSUE THREAD

**Issue by eliduke** [a85/POSTMan-Chrome-Extension#1025]
I am creating an internal API end-point that returns all of the foreign_key records for a given user, and I would love to be able to return the arrays of ids for each model (posts, comments, likes, etc) inline for better readability. Currently it looks like this...

```
"posts": [
  114,
  116,
  117,
  118,
  119,
  120,
  121,
  122,
  123,
  124,
  125,
  126,
  403
],
"comments": [
  553,
  638,
  639,
  640,
  641,
  642
]
```

But with 20+ models with potential foreign_key colums and some of those having 40 or 50 records (or more!), the list can get very long and hard to read at a glance. What I would prefer would look something like this:

```
"posts": [
    114, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 403
],
"comments": [
    553, 638, 639, 640, 641, 642
]
```

or even better:

```
"posts": [114, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 403],
"comments": [553, 638, 639, 640, 641, 642]
```

For now I just converted the array into a string, which returns this:

```
"posts": "[114, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 403]",
"comments": "[553, 638, 639, 640, 641, 642]"
```

It's not a huge deal, and I think I found a decent solution, but just wanted to throw it out there.

Thanks for making such an awesome product!

**Comment by a85** [comment]
Closing this as we plan to enable this using plugins.
