### ISSUE TITLE
Postman client won't start - disableGPU setting is set to undefined

### ISSUE THREAD

**Issue by thecodepapaya** [a85/POSTMan-Chrome-Extension#10252]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

Postman desktop application does not open at all. It was working perfectly until yesterday when it suddenly stopped working. When clicking on the application icon from the application drawer, nothing opens up. Tried to open Postman via command line with command 'postman' but received a response
```
The disableGPU setting is set to undefined
Not disabling GPU

(postman:32267): Gtk-WARNING **: 22:58:46.157: cannot open display: :0
```

### Steps To Reproduce

1. Install Postman with `snap install postman`.
2. Start Postman by clicking the application icon from the drawer or type `postman` in the command line.

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/42690541/130837515-c8d9b838-f5fb-42f3-83e9-4f91699e619d.png)

### Environment Information

```markdown
- Operating System: Ubuntu 21.04
- Platform Type: Native app
- Postman Version: 8.11.1
```

### Additional Context?

- Tried setting the environment variable ```POSTMAN_DISABLE_GPU=true``` but there was no change.
- Also tried ```postman --disable-gpu``` but it didn't help either.
- There is a slight increase in CPU utilization for a few seconds just after I click on the application icon and then it comes back to normal.
- I'm not sure but could be related to #8605 
- Installing/reinstalling the application and deleting `~/.cache/Postman` didn't help. Tried rebooting the OS between reinstalls but that didn't help either.

**Comment by postman-staff** [comment]
Hi @thecodepapaya

Thanks for writing and sorry to see you are having trouble using your Postman app.

 If you are still facing the issue then we would like to investigate further and we will need App logs, your email ID & other details. Since GitHub being a public platform it is not good to get those details on this thread from you for security reasons.

To assist you further - could you open a new support request from our support channel using this link - https://www.postman.com/support/, please? Also, do not forget to add this GitHub issue number and your GitHub username in the support request description to make it easy for us to track. We will wait to hear back from you on our support channel.

Meanwhile, to get you unblock i just wanted to check have tried using our Postman on Web version? It simply works on your Web browser and it has the same UI & feature sets like that of the desktop app and I know you will like it.

- http://go.postman.co/
- http://web.postman.co/


via @Swapnil-getpostman | Postman Support

**Comment by aleskiewicz** [comment]
I have the same issue. Version 8.1.1 was released recently on snapcraft (https://snapcraft.io/postman), and I think it is an issue with this version.

Reverting to previous release allows me to open postman, but it requires new sign-in (probably a snap thing)

`snap refresh --channel=v7/stable postman`

**Comment by 1bitphoenix** [comment]
Hi @thecodepapaya,
This issue is related to change in wayland settings in recent snap.  We're sorry for this inconvenience. 
You can run the application using `DISABLE_WAYLAND=1 postman` till we raise a proper fix for it.

Thank you

**Comment by andreatera** [comment]
just confirming that @1bitphoenix workaround works perfectly for me.. At least I can run latest version on latest Ubuntu..

**Comment by dorrogeray** [comment]
@1bitphoenix workaround works for me as well. :heavy_check_mark:

**Comment by thecodepapaya** [comment]
> You can run the application using DISABLE_WAYLAND=1 postman till we raise a proper fix for it.

The workaround is working for me too.

**Comment by postman-staff** [comment]
Thanks for the update and glad to know the workaround worked for you all.

We are going ahead and closing only the support request but the GitHub request will still be open, so feel free to respond to this thread if you have any other queries.

via @Swapnil-getpostman | Postman Support

**Comment by thecodepapaya** [comment]
Just updated to postman version `8.12.0` and the issue seems to be resolved. The application is working as expected.

**Comment by eaccmk** [comment]
> Just updated to postman version `8.12.0` and the issue seems to be resolved. The application is working as expected.

Not anymore working anymore in **8.12.2** on REHL **8.x**
$snap list | grep postman
postman  8.12.2    147    v8/stable      postman-inc*  -
```

**Comment by eaccmk** [comment]
even after adding **DISABLE_WAYLAND=1** still does not work.
Shouldn't it be as simple as  `$snap run postman` :thinking: @postman-support 

:warning:  This issue has started surfacing in latest release :exclamation:  , failing in **REHL 8.x**

```sh
$snap version
snap    2.51.7-1.el8
snapd   2.51.7-1.el8
series  16
rhel    8.4
```

and **postman** version `postman  8.12.2`
```sh
$snap list | grep postman
postman  8.12.2    147    v8/stable      postman-inc*  -
```

**Comment by postman-staff** [comment]
@eaccmk Could you share a screenshot of the window you see during launch? Is it grayed out blank space after opening the application?

Although this one is for windows, can you check [this article here](https://support.postman.com/hc/en-us/articles/360026088854-Postman-is-stuck-on-the-load-screen) and see if this helps in any way?

via @Raj-postman | Postman Support

**Comment by eaccmk** [comment]
> @eaccmk Could you share a screenshot of the window you see during launch? Is it grayed out blank space after opening the application?
> 
> Although this one is for windows, can you check [this article here](https://support.postman.com/hc/en-us/articles/360026088854-Postman-is-stuck-on-the-load-screen) and see if this helps in any way?
> 
> via @Raj-postman | Postman Support

After a reboot it worked. 

I had no issues with the launch, it was about the error messages 
```diff
- GPU setting is set to undefined
```

from my side its solved now :white_check_mark:

**Comment by postman-staff** [comment]
@eaccmk Thank you!
Glad to know you are all set now :)

via @Raj-postman | Postman Support

**Comment by andrewsleeman24** [comment]
I had the same problem running in ubuntu 20.04
```
andrew@gigahost:~/Apps$ postman 
The disableGPU setting is set to undefined
Not disabling GPU

(postman:391141): Gtk-WARNING **: 18:56:20.298: cannot open display: :0

```
 I followed **aleskiewicz** advice above.
```
root@gigahost:~# snap refresh --channel=v7/stable postman
postman (v7/stable) 7.36.5 from Postman, Inc. (postman-inc✓) refreshed
```
I now seem to be working but when started from the command line I get stuff like the following

```
andrew@gigahost:~/Apps$ postman 
(electron) 'getName function' is deprecated and will be removed. Please use 'name property' instead.
Not disabling GPU
Gtk-Message: Failed to load module "canberra-gtk-module"
Gtk-Message: Failed to load module "canberra-gtk-module"
ProtocolHandler~setDefaultProtocolClient: Command failed: xdg-mime default Postman.desktop x-scheme-handler/postman
/bin/sh: 1: xdg-mime: not found

Error org.freedesktop.DBus.Error.Failed: cannot set "default-url-scheme-handler" setting to invalid value "postman"
1631775565799 main info "Booting Postman 7.36.5, linux-5.11.0-34-generic on x64"
1631775565799 main info "EventBus~initialize - Success"
1631775565802 main warn "CloudProxyManager~init: Error while reading proxy configuration from user data - ",{"errno":-2,"code":"ENOENT","syscall":"open","path":"/home/andrew/snap/postman/133/.config/Postman/Postman_Config/proxy","name":"Error","message":"ENOENT: no such file or directory, open '/home/andrew/snap/postman/133/.config/Postman/Postman_Config/proxy'","stack":"Error: ENOENT: no such file or directory, open '/home/andrew/snap/postman/133/.config/Postman/Postman_Config/proxy'"}
1631775565802 main info "CloudProxyManager~init - Success"
1631775565808 main info "UpdateHandler~init - Success"
1631775567540 main info "RuntimeIPCAgent~started: Success"
1631775568519 main info "LinuxAutoUpdater~Cleanup - Initial cleanup successful"
1631775568976 main warn "main~populateInstallationId: Failed to get installationId from appSettings but with no error"
1631775568998 main info "Bootstrap-models~bootstrap - Success"
1631775571175 main info "window-manager~newSharedWindow: Shell loaded"
1631775576227 main info "Main~AppEvents - Received booted event for process shared"
INTERCEPTOR CONNECTIVITY: Connecting to Interceptor Bridge
InterceptorBridge: Trying to connect Native App IPC~Interceptor Bridge
1631775578839 main info "Main~AppEvents - Received booted event for process requester"
IPCClient ~ WindowHandler: New event is received { type: 'window-opened' }

```
It means nothing to me but it might help someone debug some issues. MAYBE
PS. **postman** is a nice package. **thanks**

**Comment by DanNYSPD** [comment]
@1bitphoenix  workaround works in fedora as well

**Comment by linhobs** [comment]
> Hi @thecodepapaya,
> This issue is related to change in wayland settings in recent snap. We're sorry for this inconvenience.
> You can run the application using `DISABLE_WAYLAND=1 postman` till we raise a proper fix for it.
> 
> Thank you

This fixed my issue

**Comment by kitkatsim** [comment]
will there be a permanent fix for this?

**Comment by twitharshil** [comment]
Hey Everyone, 
The proper fix was out with Postman **8.12** releases. Thanks for letting us know that the workaround & the fix works. I am going ahead & closing this ticket

**Comment by mohan990** [comment]
Thank you very much

> I have the same issue. Version 8.1.1 was released recently on snapcraft (https://snapcraft.io/postman), and I think it is an issue with this version.
> 
> Reverting to previous release allows me to open postman, but it requires new sign-in (probably a snap thing)
> 
> `snap refresh --channel=v7/stable postman`

Thanks brother It's working fine now

**Comment by aaron-613** [comment]
Old thread, but same issue..!  Ubuntu 20.04, using snap, and appears to have installed version `10.24.3`:

```
postman           10.24.3        246    v10/stable       postman-inc??   -
```

Server is running in AWS, I'm connecting via a remote desktop connection.  All my other apps all work fine, have installed browsers and IDEs, just postman is complaining:

```
$ postman
The disableGPU setting is set to undefined
Not disabling GPU
No protocol specified
[2290:0319/135529.137694:ERROR:ozone_platform_x11.cc(247)] Missing X server or $DISPLAY
[2290:0319/135529.137781:ERROR:env.cc(226)] The platform failed to initialize.  Exiting.
The futex facility returned an unexpected error code.Aborted (core dumped)
```

There is a `vncserver` running (which is how I can remote desktop) and `$DISPLAY` is set to `:1.0`.
I'm assuming this is issue is thought to be fixed, so is this something new?  Any workarounds..?  Thanks.  Let me know where to find the core if that would help debug, or if you want logs.

**Comment by cah-michael-mcghee** [comment]
Had the same issue with Snap 2.63  Postman 11.14.0.   I tried all the recommended fixes/workarounds and nothing worked.   I am running MobaXterm on Windows laptop and postman on Raspberry PI as a snap.  I changed up my search on the issue and found an hit about Xauthority permission and snaps.  It recommended doing a:
export Xauthority=/home/<user>/.Xauthority      
As soon as I did that it worked.   I added to my .bashrc and restarted and it runs every time.

I also run postman --disable-gpu to stop all the gl_display errors.

Hope this helps others.

**Comment by MiguelBecerra219** [comment]
> I have the same issue. Version 8.1.1 was released recently on snapcraft (https://snapcraft.io/postman), and I think it is an issue with this version.
> 
> Reverting to previous release allows me to open postman, but it requires new sign-in (probably a snap thing)
> 
> `snap refresh --channel=v7/stable postman`

This solved everything for me, thanks
