### ISSUE TITLE
Postman won't allow generation of collections during or after import of some WSDLs

### ISSUE THREAD

**Issue by DawMatt** [a85/POSTMan-Chrome-Extension#10251]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

Importing the attached WSDL in the Postman desktop app will generate an API, but refuses to generate a collection based upon the API. This is regardless of whether requested at import or later via the Generate Collection feature on the Overview tab.

### Steps To Reproduce

1. download the attached [wsdl.txt](https://github.com/postmanlabs/postman-app-support/files/7044860/wsdl.txt) file and rename it to wsdl.wsdl (GitHub won't let me upload an WSDL file)
2. import the WSDL in Postman, selecting Documentation and the "Generate collection from imported APIs" options
3. use the Generate Collection feature to generate a test collection from the imported API

See screenshots below for the configuration and result of steps 2 and 3. Step 3 doesn't generate a collection but does quickly display a hint as to what may be the problem.

### Screenshots or Videos

Step 2 configuration:
![image](https://user-images.githubusercontent.com/476705/130749602-73327075-ecef-4ab4-ae8b-31c6f754f30f.png)

Step 2 result:
![image](https://user-images.githubusercontent.com/476705/130749702-25d21988-bd68-4976-b6a6-dd16f5526056.png)

Step 3 configuration:
![image](https://user-images.githubusercontent.com/476705/130749928-62ae4c49-df0c-45eb-bad8-51b3d19d1908.png)

Step 3 result:
![image](https://user-images.githubusercontent.com/476705/130749997-a92269c3-7f32-4e9c-8c6b-9ef4b42b3250.png)

### Environment Information

```markdown
From Settings -> About:
Postman for Windows
Version 8.11.1
win32 10.0.19042 / x64
```

### Additional Context?

I'd originally expected this issue to be resolved by #10160 as the call stack error was previously returned when following the steps above.

**Comment by VShingala** [comment]
@DawMatt We have identified the corresponding issue and we'll add an update here once it's fixed.

**Comment by DawMatt** [comment]
> @DawMatt We have identified the corresponding issue and we'll add an update here once it's fixed.

Excellent news! I'll keep an eye out for this and be sure to try it once available.

**Comment by VShingala** [comment]
@DawMatt This issue is now fixed with the latest postman app.
