### ISSUE TITLE
Call stack size exceeded when generating collection from GraphQL schema

### ISSUE THREAD

**Issue by MattA48** [a85/POSTMan-Chrome-Extension#10266]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

Maybe duplicate of #8536 (closed after no response - same error message which was thought to be fixed)

Hi,

I've been using Postman to quickly generate GraphQL calls to test once my schema has updated. Following my latest code change, Postman has started failing to generate the collection with the following error:

Couldn’t generate collection
Could not generate collection. Error Message:Maximum call stack size exceeded

### Steps To Reproduce

Add API
Define using the attached schema
Generate Collection From Schema
Test the API -> Generate Collection

### Environment Information

```markdown
- Operating System: MacOS 10.15.7
- Platform Type: Native
- Postman Version: 8.11.1
```

**Comment by MattA48** [comment]
[schema.txt](https://github.com/postmanlabs/postman-app-support/files/7085462/schema.txt)

schema attached

**Comment by postman-staff** [comment]
Hi @MattA48

Thank you for reaching out to Postman.

Thank you for providing the schema specification, I tried importing the schema and testing this from our end, and itseems that I see the same error message.

I will go ahead and circulate this with my team and will get back to you with any updates on this.

Thank you for flagging this, we greatly appreciate it.
Meanwhile please let me know if I can do anything else for you.

via @Lincimary | Postman Support

**Comment by postman-staff** [comment]
Hi @MattA48
Hope all is well at your end!

I have escalated this issue to our engineering team to look into it with priority. I will keep you posted on any updates from the team.

Thanks for your patience while we’re fixing this issue.
Please let me know if there is anything else I can do to help you in the meantime.

via @Lincimary | Postman Support

**Comment by postman-staff** [comment]
Hi @MattA48
Hope you are doing good!

Thank you for your patience, and sorry for the radio silence.

We have good news from our engineers that the fix is deployed and is now available in Beta for testing. It will soon be released to production.

I will keep you posted once the deployed version gets released.
Thank you for your cooperation.

via @Lincimary | Postman Support

**Comment by MattA48** [comment]
Thanks, it seems this problem has disappeared again for us with further schema updates, but good to hear it's fixed

**Comment by postman-staff** [comment]
Hi @MattA48

Thank you for working with us to identify the underlying cause.

Just want to update you that I will keep you posted once this feature gets shipped into production. As of now, I'm going ahead and closing this conversation, but I’m still here so feel free to give me a shout if you have any further queries :)

Thank you for sharing your feedback.

via @Lincimary | Postman Support

**Comment by postman-staff** [comment]
Hi @MattA48

Happy news! The fix is delopyed and released in production.

You can try updating to the latest version(9) and confirm if it works fine.
Win 32: https://dl.pstmn.io/download/version/9.0.4/win32
Win 64: https://dl.pstmn.io/download/version/9.0.4/win64
Mac: https://dl.pstmn.io/download/version/9.0.4/osx
Linux: https://dl.pstmn.io/download/version/9.0.4/linux

Looking forward to your reply.

via @Lincimary | Postman Support

**Comment by postman-staff** [comment]
Hi @MattA48,

I'm going ahead and closing this conversation since the fix is released but I’m still here so feel free to give me a shout if you have any further queries :)

Thank you for sharing your feedback.
Have a great day:)

via @Lincimary | Postman Support

**Comment by MattA48** [comment]
Thanks,

Not in a position to test it right now, but as I said the error went away with further schema changes on our side, so I don't think I can do anything other than test against the original. I'll let you know if there's any problems post upgrade.

**Comment by postman-staff** [comment]
Hi @MattA48,
Sure, I understand your concern, Thank you for letting us know and sharing your feedback!

Feel free to respond to this thread, to reopen the ticket.
Otherwise, reach out again later in time.

Have a nice day:)

via @Lincimary | Postman Support
