### ISSUE TITLE
javascript execution is different

### ISSUE THREAD

**Issue by senjaliya** [a85/POSTMan-Chrome-Extension#1026]
following code in pre-request script gives different result compare to standard javascript execution engine. looks like theres some difference in javascript engine that postman uses.

//http://crypto-js.googlecode.com/svn/tags/3.1.2/build/rollups/hmac-sha1.js
//http://crypto-js.googlecode.com/svn/tags/3.1.2/build/components/enc-base64-min.js

<script src="http://crypto-js.googlecode.com/svn/tags/3.1.2/build/rollups/hmac-sha1.js"></script>

<script src="http://crypto-js.googlecode.com/svn/tags/3.1.2/build/components/enc-base64-min.js"></script>

var hash = CryptoJS.HmacSHA1("testmessage", "2e7dcd2");
alert(hash.toString(CryptoJS.enc.Base64));

if you compare output between this  (https://jsfiddle.net/333VW/) and same code in pre-request script, it is different hash code.

**Comment by senjaliya** [comment]
just found similar issue been reported earlier ( https://github.com/a85/POSTMan-Chrome-Extension/issues/1005 )

Guys, can anyone shade light on if this is right place to report an issue?

**Comment by abhijitkane** [comment]
We're looking into this. I'll update this thread soon.

**Comment by senjaliya** [comment]
cool, Thanks for the update.

**Comment by abhijitkane** [comment]
$.getScript's callback is asynchronous, and is not guaranteed to execute before the request runs. To include custom files in the sandbox, use https://github.com/postmanlabs/postman-app-support/issues/734#issuecomment-70481732
