### ISSUE TITLE
New Integration Request - Goodbarber & Lulu

### ISSUE THREAD

**Issue by NGStechworld** [a85/POSTMan-Chrome-Extension#10269]
### Describe your current workflow

I am trying to integrate GoodBarber app builder with lulu

### Describe your ideal workflow

I have a store on Goodbarber and want orders received on the Goodbarber store to be stored and printed on Lulu

**Comment by shashankawasthi88** [comment]
@NGStechworld can you expand on how you see Postman playing a role in this Integration? Postman Integrations are basically a way for users to extend their API workflows by means of exchanging data between Postman and some other product.
