### ISSUE TITLE
Json request in pre-request script being sent as text/plain

### ISSUE THREAD

**Issue by balmeida-nokia** [a85/POSTMan-Chrome-Extension#10267]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

When doing a JSON request as shown in the code below, the `Content-Type` is set to `text/plain` when the request is actually sent.
Code:
```
function login(){
	console.log("logging in");
	url = pm.environment.get("domain") + pm.environment.get("path_file");

	pm.sendRequest({
		url: url,
		method: 'POST',
		headers: {
            'Content-Type': 'application/json',
		},
		body: {
			mode: 'raw',
			raw: JSON.stringify({
				"version": "2.0",
				"b": "code",
				"c": {
					"c1": "a",
					"c2": "b"
				}
			})
		}
	}, function (err, res) {
		console.log(res);
		let result = JSON.parse(res);
		pm.environment.set("session_key", result.result);
	});
}

if(condition){
    login();
}
```

Here's from the console, how the request looks like (sensitive information has been censored)

![image](https://user-images.githubusercontent.com/83089745/131648774-fe882243-bed2-4e31-b32b-4d7b7514af58.png)

### Steps To Reproduce

1. Create a collection
2. In the collection, create a pre-request script with the function
3. Create a request in that same collection
4. Conditionally run the function
5. Request made by postman is with `text/plain` instead of the one specified (`application/json`)

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/83089745/131648774-fe882243-bed2-4e31-b32b-4d7b7514af58.png)

### Environment Information

```markdown
- Operating System: Windows 10
- Platform Type: Native App
- Postman Version: v8.11.1
```

**Comment by neilstudd** [comment]
Hi @balmeida-nokia,

In your example, you have specified the content type within a section called **headers**. This is incorrect - the section should be named **header**. (`text/plain` is the default fallback when no valid type is detected.)

I replicated your problem with the script specified, and confirmed that if I change the key to **header**, the value is sent correctly.

**Comment by balmeida-nokia** [comment]
Maybe this is the problem.
![image](https://user-images.githubusercontent.com/83089745/131654502-0e48b38d-7f24-4049-ae97-3d6535ab0be2.png)
I'm being suggested a wrong thing in this context

**Comment by DannyDainton** [comment]
Closing this based on the incorrect `header` property being used.
