### ISSUE TITLE
Send Request keyboard shortcut does not work on Windows 10

### ISSUE THREAD

**Issue by 0xtavi** [a85/POSTMan-Chrome-Extension#10265]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

Sending request hotkey does not work. Both CTRL + ENTER and CTRL + ALT + ENTER do not work in Postman. 

The same combinations work in other applications or on OS.

### Steps To Reproduce

1. Open a request
2. Press CTRL + Enter
3. Nothing happens

### Environment Information

```markdown
win32 10.0.19042 / x64
Postman for Windows
Version 8.11.1
```

**Comment by xk0der** [comment]
Hey @0xtavi I was unable to reproduce this issue on a Windows 10 machine with Postman version 8.11.1 installed. Would you be able to share a recording/GIF of what you see at your end?

Also try updating to the latest version (v8.12.0 as of writing this) by downloading it from https://www.postman.com/downloads/ and see if you continue to face the issue.

**Comment by 0xtavi** [comment]
Hello,

I updated to 8.12.0 but the issue persists.

Something that might help, when I press CTRL + Enter in the body I get automatic complete suggestions.

![image](https://user-images.githubusercontent.com/41272467/132027907-c6076285-80ba-49fa-bb86-f24a0b4d88c3.png)

https://user-images.githubusercontent.com/41272467/132027923-172846fe-f957-4f79-9201-c169f386ebe5.mp4

**Comment by postman-staff** [comment]
Hey @0xtavi 👋​ To start with, `Ctrl + Space` will provide suggestions whereas `Ctrl +Enter` sends the request.
Just wanted to confirm you are not comparing `Ctrl + Space`, and the Send button. 
If not, then could you try our web version to check if you are seeing the same behavior - [go.postman.co](go.postman.co)?

I have tried replicating this as well but works fine for me. Below is a link to the screen record for your reference.
https://user-images.githubusercontent.com/76939396/132710656-a1535dc6-6633-4f72-a68a-b01eefc01451.mov

via @VaishnaviChallaPostman | Postman Support

**Comment by 0xtavi** [comment]
Hello...

Yes I was sending CTRL + Space instead of CTRL + Enter. I feel stupid now.

Any way I can bind the send request from CTRL + Enter to CTRL + Space?

Thanks for the support!

**Comment by postman-staff** [comment]
Hey @0xtavi 👋
Unfortunately, shortcuts cannot be modified at this time, but you can view the full list of shortcuts currently supported in the app settings.
https://learning.postman.com/docs/getting-started/settings/#shortcuts
 Please let me know if there is anything else I can help you with :)
via @VaishnaviChallaPostman | Postman Support

**Comment by postman-staff** [comment]
Hey @0xtavi 👋
Closing this thread here. Feel free to re-open if you have any further queries.
Happy developing! Have a good one :)

via @VaishnaviChallaPostman | Postman Support
