### ISSUE TITLE
Basic Auth is not inherited for new request

### ISSUE THREAD

**Issue by boardtc** [a85/POSTMan-Chrome-Extension#10276]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

A request in a collection reports "This request is using No Auth from collection" though the collection is set to Basic Auth

### Steps To Reproduce

1. Create a new collection my_collection
2. On the Authorization tab add **Basic Auth** with a given Username  and **no password**
3. Create a new request in my_collection (the authorization type defaults to inherit auth from parent)
4. Add a URL and click SEND
5. 401 Unauthorised is reported
6. The Authorization tab reports "This request is using **No Auth** from collection my_collection"

### Environment Information

```markdown
- Operating System: Windows 10 Build 1909
- Platform Type: Native App
- Postman Version: v8.12.0
```

**Comment by timbochamp** [comment]
Hi @boardtc , thanks for reporting! I'm not able to reproduce this. Are there other steps you're doing to see this No Auth text instead of Basic Auth?
![Screen Shot 2021-11-14 at 10 01 40 PM](https://user-images.githubusercontent.com/4521134/141711205-ad3e67d9-1f66-4fce-b708-9cf57e02cb3a.png)

(edit: scratch that, we're able to reproduce! We'll look into a fix and provide updates here)

**Comment by boardtc** [comment]
@timbochamp thanks for checking this out. Is there any plan for when this might get added?

**Comment by malvikach** [comment]
@boardtc Could you try this on the latest postman app (v 9.13). We do not see this issue anymore. 
Attaching a video with my observation below, please note that you can check the auth being used in your request using the headers tab on postman, you can also verify this in the code snippet (learn more [here](https://learning.postman.com/docs/sending-requests/generate-code-snippets/)):

https://user-images.githubusercontent.com/89449769/154636179-b1b2a3cb-8927-47bc-9292-ece8f16af493.mov

**Comment by malvikach** [comment]
If you are still facing the problem, feel free to reopen the ticket.

**Comment by IanAber** [comment]
I am using 10.13.5 on a Mac. None of my new requests inherit basic authentication from the collection. They all say yhe authenticaiton inherited is 'none'.

**Comment by diadelpino** [comment]
@giridharvc7 @malvikach  I am also having the same issue as @IanAber on a Mac. My Postman App works fine however it does not inherit the authorization when I sign in. Any workarounds? Ive tried signing out and back in with no luck
