### ISSUE TITLE
Bug Report Report an issue with the Postman platform

### ISSUE THREAD

**Issue by awasall** [a85/POSTMan-Chrome-Extension#10273]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

When I delete a test that I have already written on postman and when I rerun I see that it still keeps the cache of the test that I have already deleted

### Steps To Reproduce

![postmanerror](https://user-images.githubusercontent.com/50166614/131843926-cf99cbdf-4ad5-4a08-bfe2-db284ce1cef3.PNG)

### Screenshots or Videos

![postmanerror](https://user-images.githubusercontent.com/50166614/131844505-a5fbecba-3bc7-44f6-9809-bda48bf36d4e.PNG)

### Environment Information

```markdown
- Operating System: Windows
- Platform Type: Native App /Postman
- Postman Version: Postman v8.12.0 is the latest version.
```

**Comment by xk0der** [comment]
@awasall try saving the request by clicking the "Save" button and see if sending the request after that still shows you the deleted test.

_The save button is located on the top right, just above the send button for the request_
<img width="110" alt="Screen Shot 2021-09-03 at 5 24 48 PM" src="https://user-images.githubusercontent.com/21366/131954792-72d53acd-db71-443e-9ff5-da2a82096aff.png">

**Comment by awasall** [comment]
@xk0der i did it and i did it again but i still have the same problem

**Comment by postman-staff** [comment]
Hi @awasall

I tried to replicate and it worked as expected for me. After making the changes in my test scripts tab I saved my request and clicked on the sync button so that my latest changes get saved & synced.

Would it be possible to share the screen record of the behavior that you are observing? I find loom to be very useful for screen recording. Please make sure to redact the sensitive information that you have in your collection OR you can simply create a random test collection with some test cases.

via @Swapnil-getpostman | Postman Support

**Comment by awasall** [comment]
as if I had written two tests while the first one I already deleted I even tried to delete the caches on postman but and I tested what you told me but it does not work
![capturePostman](https://user-images.githubusercontent.com/50166614/132213151-aa203c9d-f2d7-4d8e-814a-783daef6fe39.PNG)

**Comment by Swapnil-getpostman** [comment]
Hi @awasall 

I'm sharing the screen record while I replicated it, please have a look and let me know if you have any other queries. 

https://user-images.githubusercontent.com/52168965/132216241-f8277fd9-4050-4c81-8ae9-ade314bd47a7.mp4

If this is something you are not referring to, then could you please share with us the screen record of the behavior you are observing? I find loom - https://www.loom.com/download to be very useful for screen recording.

**Comment by awasall** [comment]
we don't have the same problem but I'll show you the video capture that I made if you look closely in the Test part I wrote a single laba test and I named it "Status code is 404" but when you click on run I see in the Test result part at the bottom left it still keeps the same test that I had already deleted, that's my problem

https://user-images.githubusercontent.com/50166614/132219199-e52ebdf6-a9aa-497b-bc97-971db89e07be.mp4

**Comment by postman-staff** [comment]
@awasall Thank you for the recording you've provided. We tried to test this from our end again but unfortunately, we were unable to replicate the same. May I know if this is happening only for this particular collection?

If yes, could you try to test this collection/request from Postman Web: https://go.postman.co/home?

If you receive the same error, then most probably there is a test defined on the collection or folder level test script which could be causing it.
If not, then please share the collection with us (if possible) via http://postman.com/support to help us check this from our end.

via @Raj-postman | Postman Support

**Comment by postman-staff** [comment]
@awasall Just following up here to see if the issue persists. Let us know if the steps provided in our earlier response helped.

via @Raj-postman | Postman Support

**Comment by awasall** [comment]
Hello i fixed the problem by trying to delete the parent directory and recreate it and it worked and thanks for air help too

**Comment by postman-staff** [comment]
@awasall Awesome! Thanks for letting us know.

via @Raj-postman | Postman Support
