### ISSUE TITLE
Postman app is not saving session after login

### ISSUE THREAD

**Issue by iwex** [a85/POSTMan-Chrome-Extension#10279]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

Hello! Postman app is not saving session after login

### Steps To Reproduce

1) Open Postman
2) Click Sign In
3) Choose an account in the browser - Now we signed in Postman App
4) Close Postman
5) Open it once again - we are logged out.

### Environment Information

```markdown
- Operating System: Manjaro
- Platform Type: Native app
- Postman Version: 8.11.1
```

**Comment by postman-staff** [comment]
Hi there,

Thanks for sharing your feedback.

I tried to replicate it and I could save my account session after I login to the app. I'm on the latest version v8.12.0 of the app.
To store and keep your account session - are you ​checking the option "Keep me signed in" while you are logging into your postman app?

 ![](https://postman.zendesk.com/attachments/token/fAz26xmz7Pp5jBSXeRAU4RUnl/?name=signed_in.png)​


In addition, please do update (Settings->Update) the app to the latest version if you haven't already.

via @Swapnil-getpostman | Postman Support

**Comment by iwex** [comment]
@postman-support Yes, I checked that option, but it remembers me in browser and not in Postman app.

**Comment by xk0der** [comment]
@iwex I see you are on an Arch Flavour Linux Distro. Did you download the app directly from here: https://www.postman.com/downloads/ or installed it via snap? (Or any other channel?)

**Comment by iwex** [comment]
@xk0der tried both ways: direct download and install from AUR

**Comment by iwex** [comment]
cleaned .config/Postman dir and retried - now everything is ok
