### ISSUE TITLE
Trying to import json gets a parse error

### ISSUE THREAD

**Issue by pushpesh4u** [a85/POSTMan-Chrome-Extension#1027]
I am trying to import a collection into postman. This collection is a backup of an existing collection by doing "Download all data".

When trying to import the backup file, it fails in parsing the JSON!.

![postman](https://cloud.githubusercontent.com/assets/1575349/7313048/3f17b1e0-ea73-11e4-9259-eeb6a5e51e58.png)

I verfied the json in jsonlint.com and it is valid.

OS - Ubuntu 14.04 LTS
Chrome - Version 42.0.2311.90 (64-bit)
Downloaded the app from chrome store.

**Comment by abhijitkane** [comment]
The backup file is meant for import in the packaged app (https://chrome.google.com/webstore/detail/postman-rest-client-packa/fhbjgbiflinjbdggehcddcbncdddomop?hl=en), not the legacy Postman application.
