### ISSUE TITLE
Cannot add version tag to collection

### ISSUE THREAD

**Issue by luhova** [a85/POSTMan-Chrome-Extension#10271]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

I have an API with multiple versions. Yesterday the latest one was 2.3.1. I have added this version tag (2.3.1) to one of the collection's changelogs and have published this version (2.3.1) of the documentation a couple of days ago. Yesterday, I made some changes to the documentation, I saw the changes in the changelog and I tried adding the 2.3.1 version tag to the latest change. Then, I got the error _**The collection is already linked to an API Version**_ . I got really confused and I decided to try removing the 2.3.1 version tag from the already tagged changelog. I successfully removed the 2.3.1 version tag and I checked that the latest tagged changelog is with 2.3.0 version. Afterwards, I tried adding the 2.3.1 version tag to the latest changelog, but I got the same error  _**The collection is already linked to an API Version**_ , although I saw in the changelog that there is no change tagged with the 2.3.1 version. Then, I deleted the 2.3.1 version from API's versions, cause I decided maybe I done something wrong when creating this version. I tried adding the 2.3.0 version tag to my latest changes, but I keep getting the same error. Now, when I open the API's info, I see that the linked documentation is with version CURRENT. I see the prompt **_To link this documentation to a version of your API, add a version tag._** but I am not able to do this.
I tried creating a new API and a corresponding new documentation, but I keep getting the same error.

### Steps To Reproduce

1. Create an API.
2. Create new documentation for this API.
3. Make changes to the documentation.
4. Add version tag.

### Screenshots or Videos

![Screenshot from 2021-09-02 11-18-13](https://user-images.githubusercontent.com/7593768/131808720-49bb82a3-9432-499f-947a-3fc3b8f934c1.png)
![Screenshot from 2021-09-02 11-18-40](https://user-images.githubusercontent.com/7593768/131808731-e2469333-dc40-4c6c-94ef-fdc28d909a42.png)
![Screenshot from 2021-09-02 11-18-53](https://user-images.githubusercontent.com/7593768/131808734-4dc92b59-6920-4fc5-8713-a568c1448c2d.png)
![Screenshot from 2021-09-02 11-19-06](https://user-images.githubusercontent.com/7593768/131808742-936bff38-9f7b-4bc5-b13a-e7d03d887f49.png)

### Environment Information

```markdown
- Operating System: Ubuntu 20.04
- Platform Type: Postman Web
- Postman Version: 8.12.0-210827-0330
```

**Comment by abhijitkane** [comment]
@luhova Thanks for the detailed report. We're working on some updates around this flow, and should have a resolution soon. 
Could you expand on the rest of your workflow, specifically, what it would have looked like if the 2.3.1 tag had been added to the collection?

**Comment by luhova** [comment]
My most up to date documentation would have the 2.3.1 version tag and this way I would have been able to successfully republish the documentation with the recent changes. Now I was forced to republish the documentation with the CURRENT version.

**Comment by abhijitkane** [comment]
Got it - we're working on a slightly different way of handling this, and should have an update out soon.

**Comment by luhova** [comment]
Thank you for your fast replay! I am looking forward to this update.

**Comment by eyalgrossdev** [comment]
@abhijitkane  What changed and why? And why were users not notified of the change? It never used to be like this and now we can't tag documentation with the appropriate version!

**Comment by DLTKMonBlaza** [comment]
Any updates on this one? This issue is greatly impacting our API documentation releases. Thanks.

**Comment by abhijitkane** [comment]
@Mon-Blaza @eyalgrossdev @luhova Creating version tags to different API versions from the collection changelog should be possible now.

**Comment by eyalgrossdev** [comment]
@abhijitkane yes it is. Care to explain what happened? This is a pretty fundamental feature that disappeared / changed / broke overnight and caused quite a headache.

**Comment by abhijitkane** [comment]
@eyalgrossdev We're in the process of making updates to this flow which should start rolling out soon. This was a side-effect of the change that unintentionally leaked out. Apologies for the disruption in the workflow.

The next update should provide a more streamlined way of locking documentation to fixed states of collections.

**Comment by DLTKMonBlaza** [comment]
Thanks for the update, @abhijitkane! We're now able to add version tags again.

**Comment by abhijitkane** [comment]
Everyone - the latest release (Postman v9) changes this flow a little bit. Versions now represent parallel lines of development for an API, and releases represent the state of the API version at a point in time. You can also "view" releases (this will show you snapshots of the API definition and any collections in the release).

For the workflows discussed above, you'll need to create a release on your API version (described here - https://learning.postman.com/docs/designing-and-developing-your-api/versioning-an-api/#working-with-api-releases). Once this is done, you'll be able to create documentation/mock servers/monitors by specifying any of the release tags created on the collection. Version tags that have already been created in older versions of Postman will continue to show up while creating documentation.

We'd love to hear your thoughts on the new workflow once you've had a chance to try it out. A more complete explanation of changes can be found at https://blog.postman.com/announcing-new-postman-api-platform/.

**Comment by luhova** [comment]
Hello, today I tried to create a new release. I added a new endpoint to the API, updated the documentation and now I want to update the published one. I tried creating a new release, but I got this error 

> No revisions found for modelId: < model-id-here >


![Screenshot from 2021-10-01 18-42-06](https://user-images.githubusercontent.com/7593768/135649105-72921111-68fc-43b3-adbf-6191e9de9afd.png)

**Comment by luhova** [comment]
@abhijitkane could you help me with the aforementioned issue? How could I create a new release and therefore be able to republish my updated documentation?

**Comment by luhova** [comment]
@abhijitkane I found out that for newly created API I successfully can create a new release, however for the old one - I get the above error - No revisions found for modelId: < model-id-here > . I don't understand what this error means and how could I fix it. @Mon-Blaza @eyalgrossdev did you try creating a release for your APIs?

**Comment by abhijitkane** [comment]
@luhova Releases can be created from the "create release" link in changelog on the right side. This should be visible if you've selected the API version

![Screenshot 2021-10-06 at 5 06 29 PM](https://user-images.githubusercontent.com/681190/136195162-321d2e1f-645c-46d5-83b8-b62fc1336412.png)

We're looking at the `No revisions found` error - let me get back to you on that.

**Comment by luhova** [comment]
@abhijitkane Yes, I see the "create release" link, but then I get this error.

![Screenshot from 2021-10-06 14-39-02](https://user-images.githubusercontent.com/7593768/136195551-08d02e18-fb41-4d2c-aeb5-9c1dcd51366c.png)

**Comment by abhijitkane** [comment]
@luhova Can you send a screenshot of the "info" section of the right context bar? (It's the one under the changelog tab that you've selected). You can send it to help@postman.com and reference this thread, since it might contain sensitive information.

**Comment by luhova** [comment]
@abhijitkane I just sent the email.

**Comment by abhijitkane** [comment]
Thanks - we'll get back to you.

**Comment by abhijitkane** [comment]
@luhova This shouldn't happen for newer APIs you create. For the existing API, you can resolve this by making a small change to the schema - something as small as adding a space/newline should do.

**Comment by luhova** [comment]
@abhijitkane yes, that worked. Thank you!
