### ISSUE TITLE
Cannot add existing collection to API Designer as Contract Test

### ISSUE THREAD

**Issue by darrencapner** [a85/POSTMan-Chrome-Extension#10283]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

I am unable to add an existing collection to an existing API in the designer. The collection was added previously in the API designer. When I removed it, I am not able to add it again.

### Steps To Reproduce

API Designer is version 1.4.2. There is no collection currently attached to the contract tests. There exists a collection in the workspace. The collection in the workspace was attached to the API Designer under contract tests until a new version was created and then selected to carry over the contract tests. A new collection was created after this action with the new version as a suffix in the collection name and this new collection was attached to the API Designer contract test section. I wanted the original collection attached to the API Designer under contract test, so I removed the new collection from the API Designer contract test section.

I had removed the new collection that was generated when creating the new version. Currently there is the original collection listed in the 'Collections' area. This original collection was created and updated since before 2021.

1. Go to API Designer, contract test section
2. Click 'Add Contract Test' button
3. Click 'Add existing contract test' option.
4. From dialog, click drop-down menu. There is no collections to choose from with drop-down indicating 'There are no collections in this workspace'.

### Screenshots or Videos

API Designer with latest api version of 1.4.2.
![image](https://user-images.githubusercontent.com/30915037/132354366-a3f8df2c-463c-4856-a7cc-a7b211bcbe45.png)

API Designer with trying to add collection that exists in the workspace.
![image](https://user-images.githubusercontent.com/30915037/132354382-b1951e6a-3f0b-4d6a-a3a8-43069d7e879e.png)

Collection that exists in the workspace.
![image](https://user-images.githubusercontent.com/30915037/132354401-a2018686-7568-4aa6-a35f-a50cff554c86.png)

Previous version of the API with collection in the contract testing section of the API.
![image](https://user-images.githubusercontent.com/30915037/132354453-70e7a494-4d10-4f1c-bb33-0658f3e8fb44.png)

When trying to tag the existing collection with the version 1.4.2, the version does not exist in the list to choose from. Why is that?
![image](https://user-images.githubusercontent.com/30915037/132354477-7d26d375-fb08-43e6-92da-694789ab878d.png)

### Environment Information

```markdown
- Operating System: Windows 10
- Platform Type: Postman Web
- Postman Version: Sept 1, 2021
```

### Additional Context?
Postman Community Posting under Help: https://community.postman.com/t/cant-add-existing-collection-to-api-as-contract-test/27302

**Comment by 5thdimensional** [comment]
Based on your description, what I believe is happening is that the collections in the workspace are already associated with a previous version of the API. There is a 1:1 mapping between a collection and an API version that is being enforced, which could explain why you aren't seeing any collections in the drop down when trying to add them to a new API version. 

We'll be introducing some functionality soon which will help make managing the relationship between collections and API versions easier. However, in the interim there are a couple of options are available to you:

1. **Migrate the collection(s)** to the 1.4.2 version. To do this you will need to first remove the link between the collection and the previous API version. this will allow the collection to be visible when selecting the option to "add an existing collection" to the 1.4.2 version. 
2. **Duplicate/copy the collection(s)** and link to the 1.4.2 version. This will simply require duplicating the collection and then linking it to the version. I recommend putting the version in the collection name so that it is easier to identify, such as "[1.4.2] My Collection". 

We'll look into the last issue you reported with 1.4.2 not appearing as a selectable version tag option.

**Comment by darrencapner** [comment]
Going through all API versions and removing the Contract Test collection allowed me to add the collection to the 1.4.2 API version. Functionality must have changed to make a Collection a 1:1 mapping to an API as my other versions of API were associated to the same collection (which I now removed).

**Comment by darrencapner** [comment]
Is the intention to always have a duplicate collection created when a new API version is created? This other done manually or done automatically when carrying over collections from a previous version when a new API version is created?

If that is the case, my understanding then is the Collections will grow to have many similar collections that only differ by version. This might become unruly if there are Contract Tests, Integration Tests, Documentation, etc. and multiple of each, one for each version.

**Comment by abhijitkane** [comment]
@darrencapner Apologies for the delayed response. The latest release (Postman v9) changes this flow a little bit. Versions now represent parallel lines of development for an API, and **releases** (new construct) represent the state of the API version at a point in time. You can also "view" releases (this will show you snapshots of the API definition and any collections in the release).

Collections can only belong to one version at a time, but you can create a release on your API version (described here - https://learning.postman.com/docs/designing-and-developing-your-api/versioning-an-api/#working-with-api-releases). Once this is done, you'll be able to create documentation/mock servers/monitors by specifying any of the release tags created on the collection. Version tags that have already been created in older versions of Postman will continue to show up while creating documentation. A more complete explanation of changes can be found at https://blog.postman.com/the-new-postman-api-platform/.

Happy to chat more about this to understand your workflow better. We want to make sure this updated product evolves to support the way you develop and maintain your internal/external APIs. Feel free to schedule a call via https://calendly.com/abhijit_kane/30min anytime.
