### ISSUE TITLE
Unable to drag and drop one folder to the another folder

### ISSUE THREAD

**Issue by mnsharma** [a85/POSTMan-Chrome-Extension#10282]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

I am working in my private workspace and trying to drag and drop the one collection of folder to the another folder but it's not working. 

### Steps To Reproduce

1. Create a collection of folder A
2. Now create a new folder B
3. Drag and drop the folder A into the folder B
4. It will not work

### Screenshots or Videos

https://user-images.githubusercontent.com/45871784/132330033-b88dcbfe-75e5-491e-8564-69704e47d5e8.mp4

### Environment Information

```markdown
- Operating System: win32 10.0.19043 / x64
- Platform Type: Postman App
- Postman Version: 8.12.1
```

**Comment by xk0der** [comment]
@mnsharma from the video, looks like you were trying to drag one collection into another? That would not work. You should be able to drag individual folders and requests from inside one Collection to another.

Do clarify if the video didn't capture what your were trying to do.

**Comment by xk0der** [comment]
Closing as there was no further follow-up!
