### ISSUE TITLE
New Integration Request - Azure DevOps

### ISSUE THREAD

**Issue by sundipnair** [a85/POSTMan-Chrome-Extension#10280]
### Describe your current workflow

I would like the ability to backup my APIs, collections and other artefacts to ADO repos.

### Describe your ideal workflow

Ideally I can have gates to merge my changes to ADP repo. Also ability to work on feature using a feature branch. This then gets tested and promoted to master.

### Describe alternatives you've considered

SwaggerHub has got this integration.

**Comment by shashankawasthi88** [comment]
@sundipnair Thanks for raising the request, we would be considering Azure DevOps integration soon. Will post on this thread for updates.

**Comment by esbenbach** [comment]
An Azure Devops integration similar to your github integration would be very welcome indeed, this would allow us to keep postman collections (and APIs) versioned together with the code being developed instead of relying on manual export/import and the rather poor fork/merge support.

**Comment by sundipnair** [comment]
> @sundipnair Thanks for raising the request, we would be considering Azure DevOps integration soon. Will post on this thread for updates.

**Comment by sundipnair** [comment]
@shashankawasthi88 , thanks for the response. When you have more information on at least a proposed ETA, it would be great if you can share this.

**Comment by shashankawasthi88** [comment]
@sundipnair we will definitely share the information as soon as we have dates available. Ill keep this thread open for now and will post the updates on this thread itself.

**Comment by shashankawasthi88** [comment]
Hey @sundipnair , while we are planning to add Azure repository Integrations soon we would want to gain some feedback on the recent release (API Platform with Integrations with repository Integrations). Please check this [blog post](https://blog.postman.com/announcing-new-postman-api-platform/) for more info, and update your app to try it out! The Azure flow would remain the same as GitHub, BitBucket. We would love to know how well the release caters to your use cases.
You can schedule a call with us using this link - https://calendly.com/shashank-awasthi/api-platform-feedback

**Comment by shashankawasthi88** [comment]
@sundipnair @esbenbach and others following this thread, can you please confirm what AzureDevOps deployment do you folks have DevOps Services (MS Cloud Hosted) or DevOps Server / TFS (Self Hosted)

**Comment by esbenbach** [comment]
Devops cloud hosted for my part.

**Comment by michaelhachen** [comment]
MS Cloud hosted. Would love to have this integration!

**Comment by stefania-santimbrean** [comment]
I am also looking forward to integration with DevOps Repos (cloud in my case). Do you happen to have an approximate timeline/release date for when it's going to be available?

**Comment by R-Lamberson** [comment]
MS Azure DevOps cloud hosted

**Comment by tcukanoot** [comment]
Also looking forward to this integration

**Comment by shashankawasthi88** [comment]
Hi @sundipnair @tcukanoot @R-Lamberson @stefania-santimbrean @michaelhachen, we have launched a repository integration with Azure DevOps (cloud repo) in App version 9.6.0. Please refer to the [blog post](https://blog.postman.com/the-reimagined-api-first-workflow-for-developers/) for ideal flow and [learning center](https://learning.postman.com/docs/designing-and-developing-your-api/versioning-an-api/#connecting-a-repository) to know how to configure Azure integration.
The Azure DevOps Service (TFS/ on-prem) will follow soon.
