### ISSUE TITLE
Sending application/json along with a file using form-data

### ISSUE THREAD

**Issue by ridoo** [a85/POSTMan-Chrome-Extension#1028]
I couldn't find out how to change the content-type for a form field which is being send along when attaching a file. There is only `Text` and `File` choosable from dropdown.

![image](https://cloud.githubusercontent.com/assets/881756/7343206/c6c3bf74-ecbe-11e4-8610-3e2886fb66aa.png)

Isn't possible at all to pass the content-type of each form field so that the request contains

```
POST /service/documents/upload HTTP/1.1
Host: localhost:8080
Accept: application/json
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

----WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="document"; filename="add-document_document.docx"
Content-Type: application/vnd.openxmlformats-officedocument.wordprocessingml.document


----WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="content"
Content-Type: application/json

{   "applicationId": "[07007EE1-24F4-11E3-95F2-9C8E991CF810}"
----WebKitFormBoundary7MA4YWxkTrZu0gW
```

**Comment by a85** [comment]
This unfortunately is not possible as per the HTTP spec itself.
