### ISSUE TITLE
After find and replace, the request in the runner still uses the old data

### ISSUE THREAD

**Issue by sunlongv587** [a85/POSTMan-Chrome-Extension#10292]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

After using the find and replace function, when the runner executes, the data in the request is still the data before replace. I think this may be a bug

### Steps To Reproduce

1. Create a new collection;

2. Create a request;

3. Replace the existing text of the request with find and replace;

4. Open runner and run in the new collection;

5. When a bug occurs, the data in the runner is still the data before replacement;

### Environment Information

```markdown
- Operating System: MacOS Big Sur 11.5.2
- Platform Type: Native App
- Postman Version: 8.12.1
```

**Comment by DannyDainton** [comment]
Hey @sunlongv587

You would need to save any requests that have changes in them (you will see an orange dot in the request tab), for the runner to pick up those new details.

**Comment by sunlongv587** [comment]
I'm sure I saved the modified request, but it still has problems. And I can still reproduce it now. I think you can follow my steps to reproduce the bug.

**Comment by postman-staff** [comment]
@sunlongv587 Just tested this from my end and we were unable to replicate it from our end. [Here is the screen recording](https://www.loom.com/share/b5c0797a4cac4fb285ec154a4154eab2) for reference. Could you check and let us know if this is how you have been attempting to use this?

You may also try to check this on Postman Web: https://go.postman.co/home and see if that helps.

via @Raj-postman | Postman Support

**Comment by postman-staff** [comment]
@sunlongv587 Just following up here to see if the issue persists. Let us know if Postman Web helped identify the error in this case.

via @Raj-postman | Postman Support
