### ISSUE TITLE
Postman response preview always changing to HTML

### ISSUE THREAD

**Issue by ghost** [a85/POSTMan-Chrome-Extension#10293]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the Issue

Preview dropdown is changing to HTML every new request after clicking "SEND" button.
Not critical, but it is annoying.
![Screenshot_1](https://user-images.githubusercontent.com/68637510/132945505-e10bfb65-671a-45e4-8731-24edb4776993.jpg)
![Screenshot_2](https://user-images.githubusercontent.com/68637510/132945506-286b70fe-e579-4d7d-a8bd-dd1c629f9fdd.jpg)

### Steps To Reproduce

1. Make simple request to api server, that responses with json
2. Change preview dropdown HTML -> JSON
3. Click again
Preview dropdown is changing to HTML again and this is annoying

### Environment Information

```markdown
- Operating System: Windows 10
- Platform Type: Native App
- Postman Version: 8.12.0
```

**Comment by xk0der** [comment]
@cyberfrogg as the first step to troubleshoot, I would recommend checking the response headers.
Look for `Content-Type` and see what the value is. It must be `text/html` for Postman to auto select HTML.

![Screen Shot 2021-09-13 at 1 41 21 PM](https://user-images.githubusercontent.com/21366/133011883-4fd29e20-4da6-4ec5-94c4-ba82ce189b80.png)

If things are still not working - do provide a screenshot of your response headers.

**Comment by DannyDainton** [comment]
Closing due to age and inactivity. If this is still an issue you're facing in the latest version of the platform, we can look at reopening this again.
