### ISSUE TITLE
TypeError: Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by chrberSTO** [a85/POSTMan-Chrome-Extension#10296]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

Trying to post a request I get 400 and TypeError: Cannot read property 'split' of undefined

I can not understand where this comes from, as the error is so generic.

### Steps To Reproduce

1. Send POST request: {{url}}/services/oauth2/token

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/80685133/133221454-1d108a10-ad0d-4f59-a5d0-2c54b5c21891.png)

### Environment Information

```markdown
- Operating System: MacOS
- Platform Type: NoteBook
- Postman Version: Version 8.12.1
```

**Comment by DannyDainton** [comment]
Hey @chrberSTO 

Do you have any scripts in the Pre-request or Tests tabs? This could be at the Collection, Folder or Request level.

**Comment by chrberSTO** [comment]
Hi Danny, you are right, this is where it originates from:

since I have a authentication failure, the response i most likely empty or none existent. I copied the request way back from some SalesForce Set and did not know that they had put scripts into the requests.
Thank you for your help.

This ticket can be closed.

I do not know how to fix this script, but that has nothing to do with this issue: 

var jsonData = pm.response.json();
var id = jsonData.id.split('/');
pm.environment.set("_accessToken", jsonData.access_token);
pm.environment.set("_endpoint", jsonData.instance_url);
pm.environment.set("_userId", id.pop());
pm.environment.set("_orgId", id.pop());
