### ISSUE TITLE
Github integration not working on branches containing forward slashes

### ISSUE THREAD

**Issue by faggionluca** [a85/POSTMan-Chrome-Extension#10291]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

Enabling the two way sync github integration doesn't not work if the specified branch name contains a forwards slash  
example : `feature/api-feature`. Every other branch name works

The file get updated only on github when a change happens in postman but the other way around

### Steps To Reproduce

1. Create or import an API 
2. From the define tab click on the `Connect Repository` button
3. Follow the procedure to add the Github integration (Access token, repo specification)
4. On the `Integration Created` page add the webhook to the repo and click `Add API version`
5. Specify a branch name that contains forwards slashes in the name for example `feature/test` (the branch must of course exist on the repo)
6. The file get created in the repo
7. Edit the file locally and push it to the repo
8. Postman doesn't not sync the file when the commit get pushed

### Environment Information

```markdown
- Operating System: Windows 10
- Platform Type: Native APP and Postman Web
- Postman Version: 8.12.1
```

### Additional Context?

Webhook payload is correctly delivered with 200 response

**Comment by shashankawasthi88** [comment]
@darkimage thanks for bringing this up. We are looking into the issue.

**Comment by abhijitkane** [comment]
@darkimage This was fixed a few weeks ago. Feel free to reopen if you're still seeing this 😄 .
