### ISSUE TITLE
Path parameter defined in APIs module not replaced with example value in collection

### ISSUE THREAD

**Issue by ngmmartins** [a85/POSTMan-Chrome-Extension#10294]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

Created an API (OpenAPI 3.0) using yaml file and I have a path parameter with an example value defined. When I generate a collection the value is not replaced with my example.

I have uploaded the relevant screenshoots. As you can see in the generated collection the Path Variable organizationID does not have the example value of 1. On the other side this works for header parameters. In this case the Content-Type is set, as it is also visible.

### Steps To Reproduce

You can create an API from the attached 'test.txt' file and generate a collection from there. Please rename the file to test.yaml because I'm not allowed to upload with that extension.
[test.txt](https://github.com/postmanlabs/postman-app-support/files/7153608/test.txt)

### Screenshots or Videos

<img width="512" alt="Screenshot 2021-09-13 at 11 37 24" src="https://user-images.githubusercontent.com/13188231/133069749-e6ecc2c9-5b12-4b08-beca-d9c330e3101d.png">
<img width="434" alt="Screenshot 2021-09-13 at 11 37 55" src="https://user-images.githubusercontent.com/13188231/133069757-5f1ee99e-8ea3-45b3-9976-7146aa22000a.png">
<img width="1250" alt="Screenshot 2021-09-13 at 11 38 49" src="https://user-images.githubusercontent.com/13188231/133069759-3daaa0ec-e64e-446f-9a6c-b705c39cfc12.png">
<img width="1254" alt="Screenshot 2021-09-13 at 11 39 04" src="https://user-images.githubusercontent.com/13188231/133069760-d5f27091-5426-4d72-b794-3180e53f4e3f.png">

### Environment Information

```markdown
- Operating System: Mac OS 11.2.3
- Platform Type: Native App
- Postman Version: 8.12.2
```

**Comment by umeshp7** [comment]
@ngmmartins Thank you for reporting this. 
We were able to reproduce this. We'll update here as soon as we release a fix for this.

**Comment by VShingala** [comment]
@ngmmartins This issue is now fixed with the latest postman app.
