### ISSUE TITLE
Not able to import wsdl file

### ISSUE THREAD

**Issue by vineetydv** [a85/POSTMan-Chrome-Extension#10298]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

Even though Postman support the import of wsdl files now, I am not able to import the wsdl file for my webservice. The same wsdl file can be imported successfully in other tools like SOAP UI. Please check the error i get below, 

"Error while importing WSDL 1.1: Converting circular structure to JSON --> starting at object with constructor 'Object' | property 'properties' -> object with constructor 'Object' | property 'OutboundDeliveryExecution' -> object with constructor 'Object' | property 'properties' -> object with constructor 'Object' --- property 'properties' closes the circle".

Please help
[odec.zip](https://github.com/postmanlabs/postman-app-support/files/7161191/odec.zip)

### Steps To Reproduce

Extract the attached zip file and import the wsdl file into postman. you will get an error on import

### Environment Information

```markdown
- Operating System: Windows 10
- Platform Type: Native App
- Postman Version: 8.12.2
```

**Comment by VShingala** [comment]
@vineetydv You should be able to import specification mentioned here successfully now. Feel free to reopen this issue if you still face further problems.
