### ISSUE TITLE
Collection Documentation not saving reliably

### ISSUE THREAD

**Issue by thomasinc** [a85/POSTMan-Chrome-Extension#10290]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

In postman desktop for MAC (Version 8.12.1 (8.12.1))
and earlier versions as well

Attempts to save changes to collection documentation are not always successful

Seems to recover after restart of postman but is fustrating

### Steps To Reproduce

Attempt updating collection documentation

Possibly lots of tabs open

### Environment Information

```markdown
- Operating System: MacOS Big Sur 11.5.2
- Platform Type: Desktop for Mac
- Postman Version: (8.12.1)
```

**Comment by Raja-Simha** [comment]
@thomasinc request you to update to the latest Postman App and let us know if you are still facing this issue. We released some fixes relevant to your issue.

Closing this for now. Please reopen if the issue persists.
