### ISSUE TITLE
Chrome 44-dev alert on the packaged postman webstore page: This item has been disabled in Chrome 

### ISSUE THREAD

**Issue by iki** [a85/POSTMan-Chrome-Extension#1029]
Error (top yellow alertbar): This item has been disabled in Chrome.
URL: https://chrome.google.com/webstore/detail/postman-rest-client-packa/fhbjgbiflinjbdggehcddcbncdddomop
Chrome version (latest dev):  44.0.2376.0 dev-m (64-bit) / Win8 x64

**Comment by abhijitkane** [comment]
Are you able to install other Chrome apps?

**Comment by iki** [comment]
Yes, have apps installed including the original [Postman REST Client](https://chrome.google.com/webstore/detail/postman-rest-client/fdmmgilgnpjigdojojpjoooidkmcomcm), ie. not the packaged app.

Also can install other apps from webstore now.

The error allows enabling and installing the app, but does not give any additional detail.

IMO, it may be related to packaged apps deprecation ~ https://blog.chromium.org/2014/06/migrate-your-legacy-packaged-apps-to.html

**Comment by abhijitkane** [comment]
@iki Are you still facing this issue? Users have been able to install the app w/o a problem.

**Comment by iki** [comment]
@abhijitkane Yes, I do. Can't you reproduce it in latest dev-channel chrome 45.0.2454.6?

Your users mostly don't use the dev-channel, which only means the issue will hit them in few months.

**Comment by a85** [comment]
We recommend moving to the new packaged app. We have added a huge banner in the app to ask people to move.
