### ISSUE TITLE
Monitor Environment Selection Does Not Display Fork Name

### ISSUE THREAD

**Issue by alexmbrown** [a85/POSTMan-Chrome-Extension#10302]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

When selecting an environment from the dropdown while creating/editing a monitor the fork name is not displayed. This can be confusing for end users because they will see multiple entries for the same environment and not be able to distinguish between them.

### Steps To Reproduce

1. Create an environment
2. For the environments
3. Create a monitor
4. The forked environment name doesn't display

### Screenshots or Videos

![Screen Shot 2021-09-15 at 2 03 23 PM](https://user-images.githubusercontent.com/10518702/133493856-cf9f6a30-2fbb-43ea-9c05-5d9ed263cdc9.png)

### Environment Information

```markdown
- Operating System: OSX 11.2.3
- Platform Type:  Native App & Postman Web
- Postman Version: 8.12.2
```

**Comment by charlie-postman** [comment]
@alexmbrown Thank you so much for reporting the issue. We are aware of the UX improvement opportunity that fork labels are missing in the environment dropdown list in the monitor creation/editing flow. We will triage and prioritize the fix for the issue.

**Comment by kartikjain26** [comment]
@alexmbrown This should be fixed in Postman app and web now.
