### ISSUE TITLE
Update the embedded Chrome version from v87

### ISSUE THREAD

**Issue by RichardRadford** [a85/POSTMan-Chrome-Extension#10309]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request

### Is your feature request related to a problem?

Our IT infrastructure blocks old versions of Chrome and we cannot use the anymore

### Describe the solution you'd like

Keep the embedded chrome more up todate

**Comment by jviotti** [comment]
Closing this, as Postman v9 runs on Chromium v91
