### ISSUE TITLE
Feature Request: Create read-only variables

### ISSUE THREAD

**Issue by llaslo** [a85/POSTMan-Chrome-Extension#1030]
In the standalone client, I use functionality quite frequently to highlight a key in the results and to set that to a local or global variable.  Sometimes I accidentally overwrite the value of the wrong variable.  It would be great if you could create a constant that can't be overwritten.

**Comment by vkaegis** [comment]
@llaslo With "current values" for variables, you can now assign a value in the session while keeping the original value of the variable intact. Hope this solves your problem for now. Closing this issue, feel free to open another if you have more feedback around this.
