### ISSUE TITLE
Post 9.0.1 x64 fails to export collection details

### ISSUE THREAD

**Issue by ScottJAditazz** [a85/POSTMan-Chrome-Extension#10304]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

Export acts like it works.  However, the content of the json file has empty or null entries for every item.

### Steps To Reproduce

1. Click ... after selecting a collection in the tree
2. Export using default option 2.1.  (same results with 2.0 option)
3. Examine contents of json file

### Screenshots or Videos

![Export](https://user-images.githubusercontent.com/60925825/133779439-cfdc7cb6-8a20-487a-b787-f75d4690747e.PNG)

### Environment Information

```markdown
- Operating System: Windows 10 Enterprise
- Platform Type: x64
- Postman Version: Several, currently 9.0.1
```

### Additional Context?

I have never been able to get a successful export.

**Comment by giridharvc7** [comment]
@ScottJAditazz can you confirm if you have saved the requests in your collection?

**Comment by postman-staff** [comment]
Hey @ScottJAditazz
Just checking here to see if you are still facing any issues :)

via @VaishnaviChallaPostman | Postman Support

**Comment by postman-staff** [comment]
Hey @ScottJAditazz
Hope you are doing good. Since it has been a while and we haven't heard back from you, just letting you know that I'm going ahead and closing the support thread here.
If you still need any help, feel free to re-open or reach out again later.
via @VaishnaviChallaPostman | Postman Support
