### ISSUE TITLE
HTTP method labels are not correctly displayed in collections

### ISSUE THREAD

**Issue by kevinadhiguna** [a85/POSTMan-Chrome-Extension#10311]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

Hi, I created a number of requests that I save in a collection in Postman.
However, in my opinion, labels which describes methods are incorrectly displayed.

Expected behavior : 
`POST` requests are labelled as `POST`, not `GET`. Same goes to `PUT` requests.

### Steps To Reproduce

1. Download the app for Linux 64-bit
2. Extract the zip file and navigate to the Postman directory
3. run `./Postman`
4. Create a collection
5. Name a request, select method (`GET`, `POST`, etc.), then run it.
6. See the method is labelled as `GET` even though it is a `POST` or `PUT` request (It works properly but the labels are wrong).

### Screenshots or Videos

This is how it looks : 

![image](https://user-images.githubusercontent.com/43397636/134125558-6b389a79-9c75-400f-9545-f82c77a94285.png)

`POST` and `PUT` methods are reflected as `GET` in the collections tab.

### Environment Information

```markdown
- Operating System: Ubuntu 20.04
- Platform Type: Native App
- Postman Version: v9.0.2
```

**Comment by DannyDainton** [comment]
Hey @kevinadhiguna 

The requests in the Collection are in a _saved_ state, you have made changes to those requests in the builder and currently, have _unsaved_ changes (the orange dots)

Once saved, the requests will all match.

**Comment by kevinadhiguna** [comment]
My bad, big thanks to @DannyDainton ! It worked : 

![image](https://user-images.githubusercontent.com/43397636/134130453-5dc801f1-6064-4661-a84e-f11c00322ea8.png)
