### ISSUE TITLE
Upon Launching Postman, All Collection Variables Are Enabled By Default

### ISSUE THREAD

**Issue by StrohmyerTR** [a85/POSTMan-Chrome-Extension#10310]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

When Postman is closed and reopened, collection variables are automatically enabled (checkboxes are checked).

I maintain a collection in which the variables act as a sort of configuration file. There are a number of variables which I would like to remain disabled (un-checked) unless I manually update them and save the collection. It is quite a bother to have to go back and uncheck the correct boxes and save before using the collection.

Potentially related issue:

This may be linked to another issue I have been noticing - I did not try and search to see if this portion has been logged already;

Having a number of requests / folders / collections open, then closing and reopening the Postman application, most requests which were open prior to closing the application display "Request not found", folders display "Folder not found", and collections display "Collection not found". They must be individually reopened. See attached screenshots. 

### Steps To Reproduce

1. Open Postman application
2. Create a new collection 'Test Collection'
3. Add a collection variable 'Control_Variable' with an initial and current value of 'foo'
4. Add a collection variable 'Test_Variable' with an initial and current value of 'bar'
5. Uncheck the box next to 'Test_Variable'
6. Save the collection

> See setup.jpg

6. Close Postman
7. Reopen Postman
8. Open (or reopen, if issue #2 from above occurs) the collection
9. Click the variables tab

**Expected result**: 'Control_Variable' remains checked, 'Test_Variable' remains unchecked.

**Actual Result**: 'Control_Variable' remains checked, 'Test_Variable' is checked.

> See result.jpg

![setup](https://user-images.githubusercontent.com/59581911/134037873-d38a8ded-99d8-4888-8c76-02b45f9a7f2f.jpg)
![result](https://user-images.githubusercontent.com/59581911/134037922-400f785d-1de7-4e86-8641-218bdd9dd247.jpg)

### Screenshots or Videos

![collection_not_found](https://user-images.githubusercontent.com/59581911/134037253-4e28d142-8a96-406e-b014-b02bf628d7f9.jpg)
![folder_not_found](https://user-images.githubusercontent.com/59581911/134037254-0bbe228a-052c-4868-8bd0-5508f377114d.jpg)
![request_not_found](https://user-images.githubusercontent.com/59581911/134037255-c756c9cc-176d-405a-8d1e-f83443628ced.jpg)

### Environment Information

```markdown
- Operating System: Windows 10
- Platform Type: Native App
- Postman Version: v9.0.2
```

### Additional Context?

I apologize if this should be split into two separate issues. Let me know if I need to make any adjustments.

**Comment by malvikach** [comment]
@StrohmyerTR thanks for the raising this issue and for the details to replicate the issue. I am able to reproduce it at my end and our engineering team will look into this.

For the other issue that you mentioned where postman doesn't load the folders and collections on opening- It would help if you could create a separate issue for the same and provide some more details around it.

**Comment by timbochamp** [comment]
This issue of collection variables being enabled by default on relaunch should now be resolved when trying the steps to reproduce on the latest app version (v9.14)! 

Please feel free to open a second issue with tabs showing as not found if you're still able to reproduce. I tried some scenarios with closing and relaunching, as well as deleting the collection/request/example of an open tab; but I'm unable to see the "not found" error tab on relaunch.
