### ISSUE TITLE
pm.response.timings is always undefined

### ISSUE THREAD

**Issue by lepinay** [a85/POSTMan-Chrome-Extension#10312]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

pm.response.timings is always empty but based on the documentation http://www.postmanlabs.com/postman-collection/Response.html we should be able to extract timingPhases for responses.

### Steps To Reproduce

The following test will show that timing information is always undefined:

```
pm.sendRequest({url:'https://postman-echo.com/get', time:true } , function (err, response) {
    console.log(pm.response.timings);
    console.log(pm.response.timingPhases);
});
```

### Environment Information

```markdown
- Operating System: Windows
- Platform Type: Native App
- Postman Version: 9.0.3
```

**Comment by coditva** [comment]
@lepinay `pm.response.timings` is not valid API. The documentation that you've linked to is for `postman-collection` package. This is not exactly the same as the `pm` API provided in the Pre-request and Tests scripts. The documentation for `pm` API is [Postman Learning Center > Postman JavaScript Reference](https://learning.postman.com/docs/writing-scripts/script-references/postman-sandbox-api-reference).

Let me know if there are any more concerns. 🙂

**Comment by lepinay** [comment]
Hi @coditva,

Yes, this same documentation  then refers to this link for further details: https://www.postmanlabs.com/postman-collection/Response.html

![image](https://user-images.githubusercontent.com/2689930/135424921-6bbaf23b-234b-43d4-a1ba-3f775a70ac8e.png)

But basically I'm just trying to access the firstByte response time for my tests, I guess it should be possible to get this information since it's displayed in the UI:

![image](https://user-images.githubusercontent.com/2689930/135425219-80f35dfc-e38c-4f97-89ee-67ceeba2e368.png)

So i'm a bit confused ;)
