### ISSUE TITLE
Can not set path variable value in pre-request script

### ISSUE THREAD

**Issue by chxiaowu** [a85/POSTMan-Chrome-Extension#10315]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

example url :  /api/:userId/detail

get： pm.request.url.variables.get('userId');

but no function pm.request.url.variables.set("userId" , "123456") to dynamic set userId in script.

### Steps To Reproduce

N/A

### Environment Information

```markdown
- Operating System: Win10
- Platform Type: 
- Postman Version: Postman v9.0.3
```

**Comment by chxiaowu** [comment]
find a way but complex to use.
    `var path_var_item = { 
        "key": "userId", 
        "value" : pm.environment.get("userId"),
        "type": "string" 
    };
    pm.request.url.variables.upsert(path_var_item);`

**Comment by cwdabba** [comment]
@chxiaowu @postman-support You made my day. I was literally struggling to do this.

It would be nice if the Postman Team had the following way to set the Query Params / Path Variables

pm.request.url.variables.set("variable to override" , "value")

**Comment by coditva** [comment]
@chxiaowu @chxiaowu There is a way to do this. Simply set the value to be a variable. Then in the pre-request script you can simply write:
```javascript
pm.variables.set('userId', '123');
```

![image](https://user-images.githubusercontent.com/8445768/135068170-dbb56739-e02e-4477-a4dc-66f7e0fdd7ef.png)

Let me know if there are any more doubts. 🙂

**Comment by cwdabba** [comment]
@coditva Hi one query. Using **pm.variables** it sets the variable on the **local level** right?
