### ISSUE TITLE
Selecting large form-data file crashes app 

### ISSUE THREAD

**Issue by billy-g** [a85/POSTMan-Chrome-Extension#1031]
I have a 250 MB IPA file -- selecting it with the file picker consistently crashes the packaged app.

**Comment by senjaliya** [comment]
having large sized response like ( audio/image ~ 2mb) also crashes the app.
- just another memory related issue

**Comment by abhijitkane** [comment]
@senjaliya what version of Postman are you using?

**Comment by senjaliya** [comment]
@abhijitkane 
Here is the version detail from settings tab.
Version 2.0.25 (packaged)
OS: mac
Architecture: x86-64
Native client architecture: x86-64

**Comment by a85** [comment]
Closing this as a duplicate of #555. Will be tracked there.
