### ISSUE TITLE
Variable suggestions are prompted only for the first attempt

### ISSUE THREAD

**Issue by Raj-postman** [a85/POSTMan-Chrome-Extension#10316]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

The variable suggestions tooltip does not show up until the tab is closed and re-opened again.

In params tab or headers, whenever you click on the value of a key then type {{ you can see environments or variables prompted. After clicking out of the box and upon re-attempting to enter variables, no suggestions are shown making it inconsistent.

### Steps To Reproduce

- Select an environment.
- Open a new request and enter the value in Param.
- You see that the variables are prompted.

![image](https://user-images.githubusercontent.com/47771757/134288372-6546305f-7b71-4281-8c4b-26e0bf6c69da.png)

- Click away and click back in to enter the variable, they show none.

![image](https://user-images.githubusercontent.com/47771757/134288402-b6e3bfc5-89f9-4f49-a615-1de9aa57b93d.png)

### Screenshots or Videos

- [Screen-record for reference.](https://www.loom.com/share/4c39d4c89676421c960831a39e66075b)

### Environment Information

```markdown
- Operating System: MacOS
- Platform Type: App and Web
- Postman Version: v.9.x
```

### Additional Context?

_Filed by Product Support_

This issue is already being tracked by the team internally, this issue is to let users who are facing a similar issues be notified upon the fix.

**Comment by malvikach** [comment]
This has been fixed in postman web and will be fixed in the app next week.
