### ISSUE TITLE
Not receiving Postman API Monitor dailySummary/weekly Summary notification

### ISSUE THREAD

**Issue by pearlp-123** [a85/POSTMan-Chrome-Extension#10320]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

Not receiving Postman API Monitor dailySummary/weeklySummary notification.

Though I have the Notification Preferences set correctly in my Postman Account, I am not receiving the API Monitor dailySummary/weekly Summary notification to my email.

I am receiving the error/failure emails , when there is a failure. But finding no luck with dailySummary/weeklySummary notifications.

Will this monitor summary include only the Scheduled runs or should also the manual runs?

### Steps To Reproduce

Create a Postman Collection
Configure a API Monitor for the created collection
Run the monitors manually and through automatic scheduler
Check if the daily Monitor Summary and the weekly monitor summary are triggered to your email

Note: Notification Preferences should be opted (via Email for both)
Daily summaries of all my monitors
Weekly summaries of all my monitors

### Environment Information

```markdown
- Operating System:macOS Big Sur 11.3.1 
- Platform Type: Native App
- Postman Version: Version 8.12.2
```

**Comment by DannyDainton** [comment]
Hey @pearlp-123 

Is this still an issue for you in the latest version of the platform?

**Comment by DannyDainton** [comment]
Hey @pearlp-123  👋🏻

I'm going to close this issue due to inactivity - If you're still facing the issue in the latest version we can reopen this and investigate further.
