### ISSUE TITLE
AZURE ADO 

### ISSUE THREAD

**Issue by riione** [a85/POSTMan-Chrome-Extension#10329]
### Describe your current workflow

Need to integrate postman tool with ADO Azure dev ops

### Describe your ideal workflow

Need to integrate postman tool with Azure Devops

### Additional context

Can v have direct integration of Postman tool with Azure Devops

**Comment by shashankawasthi88** [comment]
Duplicate of https://github.com/postmanlabs/postman-app-support/issues/10280

**Comment by shashankawasthi88** [comment]
@riione can you subscribe to this issue - https://github.com/postmanlabs/postman-app-support/issues/10280. We shall be posting updates on the Azure DevOps Integration on the same. It would also be great if you could explain your exact use case on that thread itself.
