### ISSUE TITLE
Getting "null" error during postman variable assignment 

### ISSUE THREAD

**Issue by fazligungor** [a85/POSTMan-Chrome-Extension#10325]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

I'm trying to assign variables while writing tests on Postman. While I can assign some variables, I get "null" in others. How can I solve this problem?

### Steps To Reproduce

1) https://restful-booker.herokuapp.com/booking

2) let response=pm.response.json;

pm.environment.set("BookID" , response.bookingid)

### Screenshots or Videos

![Null_Error_Fazli_gungor](https://user-images.githubusercontent.com/87184447/134532752-a82b6afa-2bca-40b7-b73b-9d1aa3ff92ae.png)
![Postman_FazliGungor](https://user-images.githubusercontent.com/87184447/134532758-3f68f548-4a4b-4792-9038-416d519c2694.JPG)

### Environment Information

```markdown
- Operating System: Postman
- Platform Type: Windows 
- Postman Version: 9.0.3
```

**Comment by DannyDainton** [comment]
Hey @fazligungor 

The response is an _array_ so you would need to specify which object, with `bookingid` within it, you require.

```
// To get the first one
console.log(pm.response.json()[0].bookingid)

// To get the second
console.log(pm.response.json()[1].bookingid)
```

Hopefully that helps :D

**Comment by fazligungor** [comment]
Hey Danny,

It works! I wrote this steps;

**console.log(pm.response.json().bookingid);

let response=pm.response.json;
pm.environment.set("BookID" , pm.response.json().bookingid);**

But When I write this I didn't identify the [0],[1]. I only have 1 bookingid answer. That's why I wrote nothing in "[]".

Why did you write 0,1 ? How can I use this items ?

Thank you for your help and patience.

Best regards.

Fazli.

**Comment by DannyDainton** [comment]
Hey @fazligungor 

This doesn't feel like a question relating to a specific product issue - Can I ask that you raise a question over on our Community forum, please?

https://community.postman.com

I'm going to close this issue out and continue the conversation over there.
