### ISSUE TITLE
Disable Exponential Notation?

### ISSUE THREAD

**Issue by pluttrell** [a85/POSTMan-Chrome-Extension#1032]
Is there a way to disable Postman from displaying numbers in exponential notation?

For example this number: 58983722842913976635313634912396295137
Is displayed as:  5.8983722842913976635313634912396295137e+37 in pretty view.

Thanks.

**Comment by abhijitkane** [comment]
We're working on a UI revamp, and this fix is part of that version. It should be out soon.

**Comment by abhijitkane** [comment]
@pluttrell Can you confirm this fixed in v3.0.4?
