### ISSUE TITLE
Error “Cannot find protocol in those namespaces” 

### ISSUE THREAD

**Issue by marvin-SL** [a85/POSTMan-Chrome-Extension#10331]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

Hello,
I tried to import some WSDL file but I’ve got this error: Cannot find protocol in those namespace
Some ppl resolved this issue by updating, but for me it doesn’t work. The WSDL files work in SOAPUi.

Do you have an idea ?
thanks

### Steps To Reproduce

It seems that some WSDL file work, but i don't know why. Unfortnulatly it's a private API and i'm not allowed to upload the files

### Environment Information

```markdown
- Operating System: Windows 10
- Platform Type: native app
- Postman Version: 9.0.3


Version 9.0.3
win32 10.0.19043 / x64
```
```


### Additional Context?

_No response_

**Comment by NogrTL** [comment]
Same issue

Works fine in SoapUI. 
Postman creates the API, bun unable to generate collection

Message it states `Error while importing WSDL: Cannot find protocol in those namespaces`

```
Postman for Windows
Version 9.0.5
win32 10.0.19043 / x64
```

[WSDL](https://gist.github.com/NogrTL/a0d6230ecb71b28847d48f63deda10a1)

**Comment by DannyDainton** [comment]
Hey @NogrTL / @marvin-SL 

Is this still an issue for you in the latest version? I was able to import the linked WSDL schema and create an API and Collection.

<img width="1679" alt="image" src="https://user-images.githubusercontent.com/17089546/158987151-77813438-1a01-4aea-8b8b-649a6bb87231.png">

If this is no longer a problem, can we close this issue?

**Comment by DannyDainton** [comment]
Hey @marvin-SL / @NogrTL  👋🏻

I'm going to close this issue due to inactivity - If you're still facing the issue in the latest version we can reopen this and investigate further.

**Comment by marvin-SL** [comment]
> Hey @marvin-SL / @NogrTL 👋🏻
> 
> I'm going to close this issue due to inactivity - If you're still facing the issue in the latest version we can reopen this and investigate further.

Sorry for the late reply. Yes it works now ! Thanks
