### ISSUE TITLE
Everlasting Reload

### ISSUE THREAD

**Issue by KittyGarrison** [a85/POSTMan-Chrome-Extension#10337]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

While making a fork of a collection while doing the 30 days of Postman Challenge I noticed that sometime I would end up in a redirect loop. I found I was able to reproduce the bug only when I clicked on the "Fork Collection" button. I was NOT able to reproduce by hitting the enter key while in the fork name field.

### Steps
1. While signed in to an user account
1. Navigate to https://www.postman.com/postman/workspace/30-days-of-postman-for-developers/collection/14433307-761cd6ce-4539-481b-a9a8-8edc8a5c62ac?ctx=documentation
1. Select the three dots to the right of a collection name ("Day 08: Run a collection" for example) _Select "create a fork"
1. Type a name into the "Fork Label" field
1. Use your mouse to click on the "Fork Collection" button
### Expected
I am navigated to the workspace that contains my fork
### Actual
I am navigated to the workspace that contains my fork but then navigated back to the 30 days collection and back again in an endless loop

### Screenshots or Videos

https://user-images.githubusercontent.com/11085480/135318129-7446611c-a073-4c3a-bebe-8cba585e794f.mov

### Environment Information

```markdown
- Operating System: macOS 10.15.7
- Platform Type: Chrome web app
- Postman Version: most recent in prod
```

### Additional Context?

I was able to reproduce on a friend's Mac too

**Comment by KittyGarrison** [comment]
This seems to only happen when a user click the fork collection with the mouse but not the enter button

**Comment by postman-staff** [comment]
Hi @KittyGarrison

Thank you for reporting this to us. We are able to replicate this issue from our end and will keep you posted in this thread as soon as we have any updates on the same.

While testing this, I observed that the issue occurs only when we try to fork collection to a Public workspace. Hence, if the page refresh doesn't help you - please try switching this workspace to either "Team or Personal" and then switch it back to "Public" for the final submission. Hope this helps!

via @Raj-postman | Postman Support

**Comment by Raj-postman** [comment]
@KittyGarrison Happy to update you that the team has now fixed this issue. Feel free to let us know if the issue persists.
