### ISSUE TITLE
cannot sync

### ISSUE THREAD

**Issue by finalight** [a85/POSTMan-Chrome-Extension#1033]
the postman client cannot sync

i keep login/logout and it still shows "fail to sync"

![screenshot from 2015-04-29 10 00 48](https://cloud.githubusercontent.com/assets/4475526/7383705/a2edd190-ee56-11e4-8f6a-b0deb14c036f.png)

**Comment by SamvelRaja** [comment]
:+1:

**Comment by abhijitkane** [comment]
@finalight The service is up. Can you try again?

**Comment by finalight** [comment]
nope, still doesn't work, same result as the screenshot i posted above

must i logout and login back to see the sync?

**Comment by abhijitkane** [comment]
Were you able to sync earlier? You can try logging out and logging in, but we don't see any errors. Might be a temporary network issue somewhere.

**Comment by finalight** [comment]
okay, now it's even worst; I can't login to my account anymore

**Comment by abhijitkane** [comment]
What error are you getting? Are you getting an incorrect password error, or a connectivity error, or is the login window not opening?

**Comment by TheBabaYaga** [comment]
:+1: also have this syncing problem... can login / logout but does not sync

It has worked tho

**Comment by abhijitkane** [comment]
@NoScopie @finalight Are you still seeing this issue?

**Comment by finalight** [comment]
i still do see it sometimes and I don' tknow why it keep asking me to force resync

because of that reason, i lost quite a few end points that I've made so far

I'm the only one using the POSTMAN client (one man team) and yet I have this problem

**Comment by abhijitkane** [comment]
@finalight Can you try signing out and signing back in? You should take a backup (Settings > Data > Download) before you sign out if you feel some data might not have been synced properly.

**Comment by TheBabaYaga** [comment]
@abhijitkane I am using the beta version now and there the syncing is even worse, requests get deleted, requests are moved, etc etc... but I just export to json atm

**Comment by finalight** [comment]
Already did many times but it still doesn't work
And yes I force resync several times since the first time resync fails
appears

**Comment by a85** [comment]
Please email us at help@getpostman.com for Sync issues. The platform is quite stable now and we have been able to support thousands of users concurrently.
