### ISSUE TITLE
Postman no longer remembers that window was maximized after restarting

### ISSUE THREAD

**Issue by KBulmer** [a85/POSTMan-Chrome-Extension#10340]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

Title. It started in some v8 version right before v9 was released.

### Steps To Reproduce

1. Maximize window
2. Restart Postman

### Environment Information

```markdown
- Operating System: Windows 10
- Platform Type: Native App
- Postman Version: v9.0.5
```

**Comment by b5414** [comment]
Same 

---

The app cannot be opened maximized

- Operating System: win10 latest
- Postman Version: `920` win32 10.0.19043 / x64 _+ prev_

https://imgur.com/pV4jrQo

**Comment by dsanders11** [comment]
I'm looking into this issue. I've tested older versions of Postman and confirmed that the behavior first changed in v8.8.0

**Comment by KBulmer** [comment]
Issue was fixed in v9.15.0. I just updated to v9.15.3 and the issue is back.

**Comment by KBulmer** [comment]
Updated to v9.16.1 and it seems the issue is fixed again. 🙂

**Comment by RaisinTen** [comment]
Thanks for the confirmation, closing! :)
