### ISSUE TITLE
https://dl.pstmn.io/download/latest/osx not serving `9.0.5`

### ISSUE THREAD

**Issue by gdams** [a85/POSTMan-Chrome-Extension#10345]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

Looking at the [release notes](https://www.postman.com/downloads/release-notes/) the latest version is `9.0.5` but https://dl.pstmn.io/download/latest/osx is still serving `8.12.4`

See https://github.com/Homebrew/homebrew-cask/pull/112110 for context

### Steps To Reproduce

```bash
url https://dl.pstmn.io/download/latest/osx --head | grep content-disposition
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0  126M    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
content-disposition: attachment; filename=Postman-osx-8.12.4-x64.zip
```

### Environment Information

```markdown
- Operating System: macOS
- Platform Type: Any
- Postman Version: latest
```

**Comment by gdams** [comment]
Please can somebody take a look at this, it's blocking postman on homebrew. CC @shashankawasthi88

**Comment by m3dbedb** [comment]
Same issue for windows 32

**Comment by numaanashraf** [comment]
This is resolved now. This can happen when we are in the middle of rolling out a new version and haven't made the version available for direct downloads yet.
