### ISSUE TITLE
Problem in getting image in POSTMAN - HTTP GET request

### ISSUE THREAD

**Issue by geethakr5959** [a85/POSTMan-Chrome-Extension#1034]
Hi,

Whenever i try to send "Http - GET" request to get the jpeg image from my server, I am facing issue that the image is properly not displayed.  I wasted a whole day and realize that, When I try the same in POSTMAN App launcher, I can get the image perfect. Please help me to solve the issue to get the image in POSTMAN REST CLIENT.

Thanks and Regards,
Geetha.

**Comment by a85** [comment]
@ggeetha Is this still happening for you?

**Comment by a85** [comment]
Fixed in the latest version.
