### ISSUE TITLE
are you ever going to care about M1?

### ISSUE THREAD

**Issue by voltuer** [a85/POSTMan-Chrome-Extension#10346]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request

### Is your feature request related to a problem?

you said you were going to add support early 2021, however you haven't

### Describe the solution you'd like

to have postman run natively on M1

### Describe alternatives you've considered

switching to another app

**Comment by jviotti** [comment]
Closing this ticket, as Postman does support macOS arm64 already!
