### ISSUE TITLE
A calculate block

### ISSUE THREAD

**Issue by anudeepmedicharla** [a85/POSTMan-Chrome-Extension#10350]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request

### Is your feature request related to a problem?

Created from: https://community.postman.com/t/user-feedback-postman-flows/28121/56?u=anudeep

### Describe the solution you'd like

> A ‘calculation’ block would be great for when we need to generate output based on something such as adding two number fields together and then doing validation on that.

**Comment by Anand-Keshavan** [comment]
The evaluate block should take care of this. Can be closed
