### ISSUE TITLE
An accumulate block

### ISSUE THREAD

**Issue by anudeepmedicharla** [a85/POSTMan-Chrome-Extension#10351]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request

### Is your feature request related to a problem?

> Would really like it if we were able to create object variables. That way you can have an object that populates as the process goes along - ending in a final object ready for output.

> As for the final point, I’ll explain with an example. I work with student data that makes three calls - The first gets a list of students. The second gets the courses for each student. The third gets the grades for each course. My goal is to build an object variable that contains the student name, course name, grades, and then print it out to the terminal. I’ve been able to mock this by using the ‘Combine’ block and grabbing variables in the first/second step.

> Essentially I’m trying to make an object made up of variables that were collected during the process. Again, this is kind of doable with the ‘Combine’ block, however, it feels a tad clunky, since those blocks can only accept 2 data inputs at a time, which means they have to be chained if more than 2 sets of data needs to be combined.

> Hope my explanation helps! Thank you again.

### Describe the solution you'd like

An accumulate block maybe? That keeps collecting data as and when you pass variables or data to it.

### Describe alternatives you've considered

Combine block, but it is ineffective with more than 2 inputs.

**Comment by saswatds** [comment]
This has already been solved using the Collect block.
