### ISSUE TITLE
Parse xml to JSON

### ISSUE THREAD

**Issue by anudeepmedicharla** [a85/POSTMan-Chrome-Extension#10353]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request

### Is your feature request related to a problem?

Created from: https://community.postman.com/t/user-feedback-postman-flows/28121/62?u=anudeep

> Is there a way of parsing XML into JSON?

### Describe the solution you'd like

Be able to convert XML data to JSON and vice-versa

**Comment by saswatds** [comment]
We support this in the request block by body-type selection.
