### ISSUE TITLE
Unable to validate 'null/undefined' values

### ISSUE THREAD

**Issue by anudeepmedicharla** [a85/POSTMan-Chrome-Extension#10355]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request

### Is your feature request related to a problem?

Created from: https://community.postman.com/t/user-feedback-postman-flows/28121/61?u=anudeep

> there does not seem to be a way to validate json null/undefined values
![image](https://user-images.githubusercontent.com/16399370/136163680-a5b6d048-4c4a-42a5-915b-e6e2e5c0c4b1.png)

### Describe the solution you'd like

Be able to validate even null or undefined values

**Comment by saswatds** [comment]
This block has been replaced with Evaluate block with support for FQL.
