### ISSUE TITLE
“create variables” step only offers variables that are explicitly used in the request.

### ISSUE THREAD

**Issue by anudeepmedicharla** [a85/POSTMan-Chrome-Extension#10352]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request

### Is your feature request related to a problem?

Created from: https://community.postman.com/t/user-feedback-postman-flows/28121/54?u=anudeep

> “create variables” step only offers variables that are explicitly used in the request. If I have “auth inherit from parent” on request, and the parent uses a variable, that variable is not offered in the box “create variables”

### Describe the solution you'd like

I should be able to send variables to the collection if a request is inheriting auth

**Comment by the-docta** [comment]
thx for picking up my request

**Comment by rabbah** [comment]
This is fixed.
