### ISSUE TITLE
Issues with the 'create variable' block

### ISSUE THREAD

**Issue by anudeepmedicharla** [a85/POSTMan-Chrome-Extension#10354]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

Created from: https://community.postman.com/t/user-feedback-postman-flows/28121/60?u=anudeep

> I can consistently make Flows crash by defining a Variable block with a Constant value of [\"test\"] and assigning to a variable. And unfortunately, when flows crash there is no way to recover them, as they crash every time they are opened. Having to start from scratch sucks, so maybe a way to undo/recover from outside the flows (in addition to fixing the string bug).
> 
> And additionally, there does not seem to be any way to define Arrays in variables as far as I can tell. Any json structure I define in a Variables block is of type Any, even though the value is Repeated. So For-Each blocks will not accept type Any

### Steps To Reproduce

Refer to the description

### Environment Information

```markdown
- Operating System: 
- Platform Type: 
- Postman Version:
```

**Comment by SterlingChin** [comment]
This issue has been fixed.

Set and Get Variable Blocks as well as Data/Information Blocks are available to use in Flows and persist on Flow failure.
