### ISSUE TITLE
Be able to import a folder/collection as a single unit

### ISSUE THREAD

**Issue by anudeepmedicharla** [a85/POSTMan-Chrome-Extension#10357]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request

### Is your feature request related to a problem?

Created from: https://community.postman.com/t/user-feedback-postman-flows/28121/25?u=anudeep

> I currently have multiple folders with steps for my flow:
> 
> Folder 1 has 3 Restcalls and a prerequisite step (on the folder) which is super important to setup the data
> Folder 2 has 2 Restcalls with a prerequisite which is also important.
> 
> I am missing an option to select complete folders to be executed.
> 
> So in my flow i would just do Folder 1 ----> Folder 2

### Describe the solution you'd like

Be able to select folders/collections that can execute as a single unit within a flow

**Comment by rabbah** [comment]
This is now possible. From the flows tab, you can import a collection.
