### ISSUE TITLE
"View collection in the public workspace first if you'd like to." not working when using run in Postman Button

### ISSUE THREAD

**Issue by pranav-davar** [a85/POSTMan-Chrome-Extension#10367]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

After creating a live Run in Postman button from Public workspace for a collection, it is redirecting to JSON error response as below
{"name":"paramMissingError","level":"verbose","event":"Request query param should have entityType and entityId","timestamp":1633719797587,"entity.name":"run-button-service: production","entity.type":"SERVICE","hostname":"pm-public-link-service-production-b.i-0e903abfecaad0c45","trace.id":"963c2405c137993d69924f0cd2c956d8","span.id":"431c989741b6b0d9","entity.guid":"MjY2NTkxOHxBUE18QVBQTElDQVRJT058MTE1MjY5MTMzMQ"}

### Steps To Reproduce

1. Click on Run in Postman Button.
2. Click on **View collection** in the public workspace first if you'd like to.

### Screenshots or Videos

![bug1](https://user-images.githubusercontent.com/30888879/136613183-97b584ae-b1ad-4447-90f3-61d9cefc65a3.gif)

### Environment Information

```markdown
- Operating System: Windows
- Platform Type: Web
- Postman Version: 9.0.5
```

**Comment by Vashanth** [comment]
@cipherwizard9 This issue has been resolved now, can you please check it out and confirm

**Comment by Vashanth** [comment]
It's fixed now, we've closed this issue, please do reopen if you find any problem

**Comment by pranav-davar** [comment]
Thank you @VaishnaviChallaPostman, it is working now. Sorry for the delayed response.
