### ISSUE TITLE
Feature Request: Adding colored HTTP method name to collection runner status

### ISSUE THREAD

**Issue by ykartsev** [a85/POSTMan-Chrome-Extension#1036]
Hello, dear POSTMAN developers!

We are frequently using Collection Runner tool and would be really useful to see colored label of HTTP method to the left of running test name, just like it's done in collection list itself:
<img src="https://cloud.githubusercontent.com/assets/3834742/7415286/d7154582-ef25-11e4-8d80-822ad7dc368f.png" alt="is now" width="100" height="36">

Right now it's like this: 

<img src="https://cloud.githubusercontent.com/assets/3834742/7415285/d6e6b2d0-ef25-11e4-9c4c-a0261ede918d.png" alt="is now" width="390" height="160">

Thank you very much in advance!

**Comment by a85** [comment]
Closing this as the design of the runner has changed a lot. We will allow full customization of colors soon.
