### ISSUE TITLE
getPathWithQuery() return extra `?` when there is unchecked params

### ISSUE THREAD

**Issue by junior** [a85/POSTMan-Chrome-Extension#10362]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

Using the getPathWithQuery() returns the path with `?`, even if there's no params checked. This affects pre-processing of the correct url and paths for operations like http-signatures.

The behavior only happens if there's unchecked params. If there's no params at all, the issue does not happen.

It's really easy to reproduce.

Same issue if use `getPathWithQuery({ ignoreDisabled: true })`

### Steps To Reproduce

1. Create a GET request (e.g.: http://dummy.restapiexample.com/api/v1/employees)
2. Include the pre-request script: `console.log(pm.request.url.getPathWithQuery())`
3. Making the call will show on the console the path with query correctly (e.g.: **"/api/v1/employees"**)
4. Add a test param and disable/uncheck
5. Making the call will show on the console the path with query with the extra "?" (e.g.: **"/api/v1/employees?"**)

### Environment Information

```markdown
- Operating System: MacOS
- Platform Type: Native App (Same behavior with Postman Web)
- Postman Version: 9.0.5
```

### Additional Context?

Indirect related to #7945

**Comment by postman-staff** [comment]
Hey @junior,

Thanks for flagging this issue!

We have escalated this issue to our engineering team to look closely, and as soon as we hear back from them I will keep you posted!

Thanks again for reaching out! Please let me know if you have any other questions in the meantime.

via @taehoshino | Postman Support

**Comment by postman-staff** [comment]
Hey @junior,

Thanks so much for your patience!

Our engineering team has released the fix in Postman Web already and the fix will also be included in the next version of Desktop app (v.9.9.1), which will be rolled out this week.

May I request you to confirm the fix on Postman Web or on the Desktop app after the version update?
Thanks so much for your cooperation. I look forward to hearing back on how you go.

via @taehoshino | Postman Support

**Comment by postman-staff** [comment]
Hey @junior,

I hope all is well! I just wanted to follow up on my previous message.

Please let me know if you are still facing this issue. Otherwise, I am going ahead and close this issue for now.

Have a great day and thanks for using Postman!

via @taehoshino | Postman Support

**Comment by junior** [comment]
Hello, just tested with the v9.10.1 and worked.
<img width="469" alt="image" src="https://user-images.githubusercontent.com/551007/151086929-ab6364e1-54e2-4ff7-80e8-c00b9e874b54.png">

Many Thanks @taehoshino @postman-support 

I'm closing the issue now.
