### ISSUE TITLE
Proxy CA certificate missing X509 Basic Constraint CA:TRUE

### ISSUE THREAD

**Issue by KrishnaST** [a85/POSTMan-Chrome-Extension#10369]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the Issue

Android 11 devices are not accepting CA certificates with missing X509 CA Basic Constraint.  Android 11 will show error "**private key required to install a certificate**" when tried to install certificate.

[Reference ](https://android.stackexchange.com/a/238859/353913)

Postman certificate with missing X509 CA Basic Constraint looks like
![image](https://user-images.githubusercontent.com/9427954/136702682-6e37f49c-e32d-4390-a74e-2ea246adf50b.png)

Certificate With  X509 CA Basic Constraint looks like
![image](https://user-images.githubusercontent.com/9427954/136702654-4c92d400-d0fd-4c22-b20d-5e80559ab1e7.png)

### Steps To Reproduce

1. Install Postman generated certificate from directory "**%AppData%\Roaming\Postman\proxy**" in android 11 device using "Install A CA Certificate" option.

### Environment Information

```markdown
- Operating System: Windows 10
- Platform Type: Windows App
- Postman Version: Postman v9.0.5
```

**Comment by shashankawasthi88** [comment]
@KrishnaST thanks for raising this. We are aware of this issue and rolling out a fix very soon. Will keep this thread updated for the same.

**Comment by shashankawasthi88** [comment]
@KrishnaST this should be solved with Postman's latest release (v 9.1). For supporting this, you will have to regenerate and then reinstall the certificate. Please follow the steps here for the same. The steps to do the same is mentioned in the proxy modal within the product. Please let us know if there are any other issues. Closing this ticket for now.

**Comment by KrishnaST** [comment]
Thank you. Is version 9.1 released to public.

**Comment by shashankawasthi88** [comment]
@KrishnaST We are rolling out the release already, please check in Settings > Update to check for the updates.
