### ISSUE TITLE
Unable to reach to local server via Postman, browser works fine

### ISSUE THREAD

**Issue by fthyildirim** [a85/POSTMan-Chrome-Extension#10360]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

{
"card":[
    {"buttons": "'SEPETTE %30 İNDİRİM 69,90 TL'",
    "content": "Erkek Standart Kalıp Basic 3'lü Paket T-shirt 1000.",
    "icons": "star','star', 'star', 'star', 'star",
    "imageUrl": "https://productimages.hepsiburada.net/s/120/300-400/110000069562350.jpg/format:webp",
    "subtitle": "'199,80 TL'",
    "title": "'CMBCOMBİNE MİCHAİL'"}
]

}

### Steps To Reproduce

![image](https://user-images.githubusercontent.com/66695748/136248272-cbe63836-e506-46ff-8951-b6a7ea2a66ee.png)

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/66695748/136247979-4c2a5349-3789-4d9a-83a4-a464b31ee02c.png)

### Environment Information

```markdown
- Operating System: 
- Platform Type: 
- Postman Version:
```

### Additional Context?

Can you help me?

**Comment by xk0der** [comment]
Hey @fthyildirim  👋 
This doesn't look like a Postman bug.
you seem to be using different ports from what I see in the screenshots.

In your browser the port is `4200` while in Postman you used `3000`
Check your server configuration (and code) to make sure you are using the right port for your API calls.

Such how-to questions are better suited for our Postman Community Forum https://community.postman.com/ I invite you to post any future queries at the forum - you would get a faster response! :) 

Good luck with your current project 👍
