### ISSUE TITLE
Interceptor not capturing PATCH body

### ISSUE THREAD

**Issue by antoniovivalda** [a85/POSTMan-Chrome-Extension#10361]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

Hello, 

Using the Interceptor in conjunction with Google Chrome plugin, does not record the Body of PATCH requests
It works fine with the other types of methods

Thanks

### Steps To Reproduce

1. Start Interceptor
2. Capture Requests
3. Open Google Chrome
4. Navigate on a site and record a PATCH API call
5. Check the recorded API on Postman

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/16292409/136284163-3fb11572-5dc1-4849-9964-0376c79cd83b.png)

### Environment Information

```markdown
- Windows
- Native App
- Postman Version: 9.0.5
```

### Additional Context?

NA

**Comment by postman-staff** [comment]
Hi there,

Thanks for writing in.

Would it be possible for you to share the screen record indicating it works for other requests and not working for PATCH requests? Also, do share with us your endpoints/requests for us to give a try.

via @Swapnil-getpostman | Postman Support

**Comment by vinitshahdeo** [comment]
Hello @antoniovivalda,

This issue seems similar to #9752. We'll keep you posted there.
(cc: @Swapnil-getpostman)

**Comment by postman-staff** [comment]
Hi there,

Just wanted to update you that we are going ahead and closing only the support-automation request here, but the GitHub request/thread will still be open, so feel free to respond on this thread if you have any other queries.

Best,
Swapnil | Postman, Inc.

Status Page | Learning Center | YouTube | Twitch | Bugs + Feature Requests | Community

* * *

Product Support Business Hours: `Monday, 3:30 AM UTC - Friday, 11:30 PM UTC`

**Comment by DannyDainton** [comment]
Duplicate of https://github.com/postmanlabs/postman-app-support/issues/9752
