### ISSUE TITLE
Collaborator unable to merge changes after the PR has been approved once

### ISSUE THREAD

**Issue by CatalinVoineag** [a85/POSTMan-Chrome-Extension#10374]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

We have a main collection that our team raises pull requests against and we want to allow every collaborator to merge his/her own changes if the PR has been approved at least once. 

The main collection has the `Approve once` checkbox checked under the `Merge Checks` section. But our collaborators cannot merge their changes after one approval.

From my understanding of the documentation, once any collaborator/admin in the collection gets one approval for his PR, he/she should be able to merge the change into the main collection.

### Steps To Reproduce

1. Create a collection and set the tick the `Approve once` checkbox in the Manage Roles section of the collection, under `Merge Checks`
2. Invite another user and set it to a collaborator role
3. The collaborator creates a fork of the main collection and submits a pull request to review
4. Another collaborator or the collection editor approves that PR
5. At this point, the collaborator that created the PR cannot merge his changes into the main collection.

### Screenshots or Videos

Main collection Mange Roles settings:
![image (1)](https://user-images.githubusercontent.com/11318084/137104571-a3b1b82d-31db-4c2c-90d4-170e55fe9df3.png)

After one approval the PR still cannot be merged: 
![Screenshot 2021-10-13 at 09 08 36](https://user-images.githubusercontent.com/11318084/137104651-8645a118-053a-4c12-92e7-a9114e702933.png)

### Environment Information

```markdown
- Operating System: OS X 11.4 Big Sur
- Platform Type: Native App and Web
- Postman Version: 8.12.4
```

**Comment by DannyDainton** [comment]
As the user doesn't have Editor access on the destination Collection, they wouldn't have permission to change it. This is shown here in the PR flow but the same would be if that User tried to directly edit the destination Collection.

I think the copy on the _Set merge checks_ can be improved here to reflect which role can merge the changes. 

For that Collection, you could set the Team role to Editor to allow folks on the Team to change the destination Collection or give individual users the Editor permission to limit the number of people who can make changes?

**Comment by ankitjaggi** [comment]
@CatalinVoineag Did @DannyDainton's answer solve the issue for you?

**Comment by CatalinVoineag** [comment]
Yes, sorry. Thank you for answering 💯 👍🏻
