### ISSUE TITLE
"Uncaught RangeError: Maximum call stack size exceeded" if field is empty in csv data file

### ISSUE THREAD

**Issue by pbellchambers** [a85/POSTMan-Chrome-Extension#1037]
Hi I'm getting the following "Uncaught RangeError: Maximum call stack size exceeded" if I try and use a CSV data file in the collection runner where some fields are null.

The tests just hang and the following error is in the developer console:

![20150501141346-developer tools - chrome-extension___fhbjgbiflinjbdggehcddcbncdddomop_test_runne](https://cloud.githubusercontent.com/assets/6773269/7430516/51ef93a2-f00c-11e4-9d10-20412b5cec02.png)

As far as I can tell it relates to whenever it encounters an empty field in the data file. Is this the expected behaviour? I was expecting it to insert an empty string or something for empty data.

**Comment by pbellchambers** [comment]
Workaround: Enclose all fields in the csv file in quotes.

**Comment by SamvelRaja** [comment]
@pbellchambers it is fixed in our latest update. Can you check the same and let us know is it still happening from your end and close the issue.
