### ISSUE TITLE
Error in Monitoring: Binary file load error: file resolver not supported

### ISSUE THREAD

**Issue by DivyaMoryani** [a85/POSTMan-Chrome-Extension#10375]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

I have searched , Its already raised by other users but closed without fixing ( Reference -> https://github.com/postmanlabs/postman-app-support/issues/5439) hence raising it again: 

Requirement : I have a PUT Request endpoint and a file in Binary Request body, When I run the Monitoring Job I get this : 
![image](https://user-images.githubusercontent.com/65155227/137295948-bad62837-c7d3-40e2-bf1d-5b50d9b1056b.png)

All good when I execute locally using Collection Runner. 

### Steps To Reproduce

1. Upload any file ( .mp4) in binary Request Body in PUT Request. 
2. On executing in Monitor -> I get the below error due to which the tests fail : 

Step 1 : 

![image](https://user-images.githubusercontent.com/65155227/137296305-1b7eec6c-eb01-4d3b-9dc3-9a32492dc7e1.png)

Step 2: 
![image](https://user-images.githubusercontent.com/65155227/137296424-692788b3-9758-4d70-acf3-0399ca9948e7.png)

### Environment Information

```markdown
- Operating System: OS X 18.7.0 / x64
- Platform Type: Postman Monitoring
- Postman Version:  9.0.5
```

**Comment by xk0der** [comment]
Closing as duplicate of #8480 - File uploads via Monitor isn't supported yet.
