### ISSUE TITLE
Global variable values not reflecting after save

### ISSUE THREAD

**Issue by thirumalaicb** [a85/POSTMan-Chrome-Extension#10373]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

The values entered or modified for any global variables are does not show/reflect the value and resets to the old one.
https://www.loom.com/share/82dc8e3cc29c44c883af772210d8d452

### Steps To Reproduce

1. Open Globals environment variables.
2. Add global variables and values.
3. Save it.

Expected: The values are saved.
Actual: The values resets to an old value, i.e. blanks.

4. Modify one of the value.
5. Save it.

Expected: The modified value is persisted.
Actual: The old value entered in step 2 is shown.

### Environment Information

```markdown
- Operating System: Mac OSX Big Sur (11.5.2)
- Platform Type: Native App
- Postman Version: 9.0.3
```

**Comment by DannyDainton** [comment]
Hey @thirumalaicb,

I've been able to recreate this on my side and have raised an internal issue with the team. 

Thank you for reporting! 🏆

**Comment by DannyDainton** [comment]
Hey @thirumalaicb 

I just did a quick check of the open issues and this looks like a duplicate of one raised. https://github.com/postmanlabs/postman-app-support/issues/10249

I'm going to close this and track the progress on that issue.
