### ISSUE TITLE
像fiddler一样自动设置代理

### ISSUE THREAD

**Issue by Git0503** [a85/POSTMan-Chrome-Extension#10371]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request

### Is your feature request related to a problem?

手动设置代理会导致部分网页无法访问，还要打开Internet选项，取消勾选“为 LAN 使用代理服务器”。每次都这样设置一遍非常的麻烦。

### Describe the solution you'd like

像fiddler一样，启动即自动设置代理，无需手动设置

**Comment by VShingala** [comment]
@Git0503 

We've added support for simplifying the starting proxy session.

Using the latest Postman application, with each time you start proxy session on MacOS and Windows operating systems. Proxy settings will be set automatically.

> 我们添加了对简化启动代理会话的支持。
> 使用最新的 Postman 应用程序，每个代理会话在 MacOS 和 Windows 操作系统上启动。代理设置将自动设置。
