### ISSUE TITLE
Unable to see resolved/unresolved variables while editing in Key-Value Editor

### ISSUE THREAD

**Issue by ritwijsinha** [a85/POSTMan-Chrome-Extension#10370]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

There are two issues with the UI of variable resolution:

1. The color for the variable highlight is that of an unresolved variable (red) while I'm not editing, however it's fine the first time I click it and go to the editing mode.
2. If I go to the editing mode the second time, it's not highlighted at all; nor does it show the variable's values if I hover.

### Steps To Reproduce

1. Open a saved request with a variable in Key-Value Editor (For me it was in Headers)
2. Click on a cell in Key-Value editor
3. Click outside
4. Click on the cell again

### Screenshots or Videos

https://user-images.githubusercontent.com/19693841/136808988-682009f8-f4b4-43dc-999f-f160f34bd891.mov

### Environment Information

```markdown
Operating System: macOS Big Sur 11.4
Platform Type: Native App
Postman Version: 9.0.5
```

**Comment by malvikach** [comment]
@ritwijsinha I am able to replicate the issue. Our team will be looking into this bug.

**Comment by malvikach** [comment]
This issue has now been fixed and is available on web. We will also be rolling this out to app soon.
