### ISSUE TITLE
Monitoring Error : Binary file load error: file resolver not supported

### ISSUE THREAD

**Issue by DivyaMoryani** [a85/POSTMan-Chrome-Extension#10376]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request

### Is your feature request related to a problem?

Yes, This feature is related to the problem I raised here : https://github.com/postmanlabs/postman-app-support/issues/10375. 

### Describe the solution you'd like

The file in the binary Request body should be able to Upload  and not return any error message in Monitoring tests. '

![Uploading image.png…]()

### Describe alternatives you've considered

We cannot have any alternative for now as we need to execute it across multiple regions. 
It works fine via Collection Runner, but our requirement is to execute across regions every hour , so we need this fix in Monitoring job.

**Comment by xk0der** [comment]
Closing as duplicate of #8480 - File uploads via Monitor isn't supported yet.
Please add any further comments at the linked issue.
