### ISSUE TITLE
If clear the Console, it logs the request for multiple times.

### ISSUE THREAD

**Issue by xolghadr** [a85/POSTMan-Chrome-Extension#10382]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the Issue

When sending a request it will log the request into console. But when I clear the console, new requests get logged twice and if I clear the Console again they will get logged three times and so on.

### Steps To Reproduce

1. Open the request tab.
2. enter required data.
3. send the request.
4. clear the console.
5. send the request again.

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/46192891/137757372-70aa9ae1-cec7-4eb2-9437-5f7ad83e1f19.png)

### Environment Information

```markdown
- Operating System: Windows 10
- Platform Type: Native App
- Postman Version: 9.0.7
```

**Comment by timbochamp** [comment]
This should now be resolved on the latest Postman for Web and on the app v9.1.3 with no duplicate console logs appearing as a result of having multiple Postman Flows tabs open!
