### ISSUE TITLE
Empty path variable changes from a "" to null value

### ISSUE THREAD

**Issue by wiskaso** [a85/POSTMan-Chrome-Extension#10381]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

The issue occurs when I update the name of the path variable with no value in a duplicated request, save it and export the collection.  This causes the duplicated request's value to change from "" to null.

Example: 

`https://api.service.com/builds/:buildId`
- I create the following request to get info about a particular build.
- I choose to leave the path variable's value empty/unset.

The export of `:buildId` path variable correctly looks like this:

```
{
	"key": "buildId",
	"value": ""
}

```

I duplicate it, change the path to the new location and lastly update the path variable name to something more meaningful:

`https://api.service.com/folders/:folderId`

The export of the `:folderId` path variable looks like this:
```
{
	"key": "folderId",
	"value": null
}
```

I discovered this when importing a Postman collection in to a power platform connector.  Validation passes but when attempting to use the connector in Power Automate I kept getting a validation error. So definitely a Microsoft issue in the sense that their validation is inconsistent......

Having said that, I still believe this is a bug as its two different behaviors.  

### Steps To Reproduce

Create a new request
Create a path variable with no value assigned
Duplicate this request
Change the path variable name to something else
Save and export the collection

### Environment Information

```markdown
- Operating System: win32 10.0.19042 / x64
- Platform Type:  Postman for Windows
- Postman Version: 9.0.7
```

**Comment by postman-staff** [comment]
Hello @wiskaso,
Thanks for flagging this.
I have tried to replicate the behaviour but I was unable to, each time I tried I ended up with "**null**" value for the unset path variables, and there was consistency in the results.

Those are the steps I followed: Create a new request -> add path variable -> Duplicate the request -> Change the path variable of the duplicated request -> Export the collection.
That's the output I received:
 ![](https://postman.zendesk.com/attachments/token/6Q46MnU1xMBXu2GjHniXPLcQf/?name=inline-1094191690.png) ![](https://postman.zendesk.com/attachments/token/FwKy2xSxdbccH2L6OLNPxNf6A/?name=inline-865172760.png)​​

In both cases I'm ending with the same output file, however, I might be missing something with the replication steps, can you please confirm if they are the same?

Best Regards,
Atanas

Status Page | Learning Center | YouTube | Twitch | Bugs + Feature Requests | Community

* * *

Product Support Business Hours: `Monday, 3:30 AM UTC - Friday, 11:30 PM UTC`

**Comment by wiskaso** [comment]
@postman-support 

Thanks for getting back to me so quick.

I have to apologize, I followed the instructions I laid out and sure enough what you said is correct so I had to re-trace my steps more carefully.  It turns out I was just assigning a test value to the path variable, saving it (I like to save my work), completing my testing, deleting the test value and saving it again.   I like to leave the values empty because it makes it easier to import and prepare for general use.

So what I was doing is the following:
1. Create request
2. Create path variable
3. Assign path variable value and save
4. Delete value and save
5. Export collection

Exporting after step 2:
![image](https://user-images.githubusercontent.com/27371887/137809225-00780a0a-590b-4c6e-9256-e4aee3121712.png)

Export after step 3:
![image](https://user-images.githubusercontent.com/27371887/137809413-0de574b2-765f-4bfc-a825-aa2b8787eaf3.png)

Export after step 4:
![image](https://user-images.githubusercontent.com/27371887/137809838-d5f00270-124c-4aa2-b27b-9f386a1acaf7.png)

**Comment by postman-staff** [comment]
Hi @wiskaso
Thanks for the update, and for the revised reproduction steps - we really appreciate all the details.
I've tried replicating the behavior and indeed I ended up with different output, even though in both cases the path variable was empty.

After following one of the flows  I ended up with a "**null**" reference in the exported file, and then after following the other flow I ended up with an empty string **value:""**​
 ![](https://postman.zendesk.com/attachments/token/d0ixEq0IywecPCS0w22PBitM8/?name=inline286143081.png)
 ![](https://postman.zendesk.com/attachments/token/um8RDwFMekd4oiNlsGPYAwbM6/?name=inline-476703549.png)​
Indeed it looks like a discrepancy because that's a different behavior for the same value, so I'll raise this to our engineering team to review it.

As a temporary workaround, since both values are "falsy",  is there any way for you to validate based on that when trying you are trying to connect to the service you are using.

Once again, thanks for raising this, I'll keep you updated.
via @nasco-a | Postman Support

**Comment by wiskaso** [comment]
Hey support,

No worries on that.  Now that I understand this behaviour on postman's side I can easily clean it up by editing the collection file just before I create the custom connector. .. Looking forward to the resolution!  Thanks.

**Comment by postman-staff** [comment]
Hi @wiskaso
Thanks for writing back.
I just wanted to let you know that we have already alerted our engineers regarding the issue.

We'll keep you posted for any updates.
Once again thanks for flagging this to us.
via @nasco-a | Postman Support

**Comment by sandeep-singh-pstmn** [comment]
@wiskaso This has been fixed in the latest release.
