### ISSUE TITLE
全局变量保存失败 (Global variable saving failed)

### ISSUE THREAD

**Issue by NanGuoWang** [a85/POSTMan-Chrome-Extension#10386]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

在编辑全局变量时第一次保存不生效,第二次生效

### Steps To Reproduce

1.设置全局变量页面,编辑某一个变量的值
2.点击保存,仍显示上一次的值
3.再次编辑,点击保存  才会保存

### Environment Information

```markdown
- Operating System: win10
- Platform Type: postMan-web
- Postman Version:  9.0.7
```

**Comment by shamasis** [comment]
Translation (using Apple Translate):

The first saving does not take effect when editing global variables, and the second time takes effect.

1. Set the global variable page and edit the value of a variable.

2. Click Save to still display the last value.

3. Edit again and click Save to save

**Comment by malvikach** [comment]
This seems to be happening on the current values field only, also while the value does get saved(reflected upon refreshing the page), the UI seems to show the unsaved value until 'Save' button is clicked again.

**Comment by timbochamp** [comment]
I think this is a duplicate of #10249 which should be fixed soon. Please feel free to reopen at the same time!
