### ISSUE TITLE
can we have a single delay within a collection?

### ISSUE THREAD

**Issue by JohnnyTripod** [a85/POSTMan-Chrome-Extension#1038]
Sometimes I need a long delay after an api call to ensure a subsequent call will have relevant data. I can specify a delay when starting the Collection Runner but that is for every single call. Any advice on 'custom' delays?

Johnny

**Comment by brodyd** [comment]
We add a nasty piece of code to the end of the test we want a delay after.

``` javascript
function pausecomp(millis)
 {
  var date = new Date();
  var curDate = null;
  do { curDate = new Date(); }
  while(curDate-date < millis);
}

pausecomp(environment['sleep-interval']);
```

It is annoying but it does work - It would be lovely if it was built in though.

**Comment by JohnnyTripod** [comment]
Cool. Thanks, brodyd!

**Comment by ghost** [comment]
This hack is nice but uses a lot of CPU. Is there any other alternative available?

**Comment by brodyd** [comment]
Not that we've tried yet - but we have been thinking about calling an external API that delays its response but I'm not convinced that will even be possible inside postman.

**Comment by shamasis** [comment]
Yes @brodyd that would work. Checkout echo.getpostman.com delay endpoint.

**Comment by caitsithx** [comment]
@shamasis could you elaborate more on echo.getpostman.com delay endpoint?

**Comment by caitsithx** [comment]
sleep(1000) works for me.

**Comment by sdnts** [comment]
@caitsithx Postman Echo is a test service. [Here](http://echo.getpostman.com/#f-509e-efe0-686d-eed4b3d2f1f0) are docs for the delay endpoint.

**Comment by caitsithx** [comment]
I was mis-understanding it's for delay. thanks @shamasis

**Comment by Armanda888** [comment]
I tried the Postman Echo, when I send curl command at that page, it delayed a few seconds, and return :
curl --request GET --url https://echo.getpostman.com/delay/3 -H 'content-type: multipart/form-data; boundary=---011000010111000001101001'
{"delay":"3"}
, but when I test with postman, here is the curl command the postman generates: 
curl -X GET -H "Content-Type: multipart/form-data" -H "boundary: ---011000010111000001101001" -H "Cache-Control: no-cache" -H "Postman-Token: c41f10f8-b98a-738e-d0d5-c97bb4219232" "https://echo.getpostman.com/delay/3" 
it return Internal Server Error, why it doesn't work at Postman?

**Comment by Afbcary** [comment]
My collection approaches this problem by using the max delay time on the postman endpoint

https://echo.getpostman.com/delay/10

Then I check if my process has finished running. If it hasn't, I setNextRequest to delay 10 more seconds.

`if (responseData.status === "PENDING_VERIFICATION"){`
   `postman.setNextRequest("Wait 10 seconds for example to process");`
    `}`

After 5 minutes I fail a test and end execution.

**Comment by shamasis** [comment]
@a85 should be easily addressed using asynchronous scripts and setTimeout

**Comment by thizanetti** [comment]
@shamasis could you provide an example of how to do that? I've been looking all over, but as far as I can tell setTimeout is not available in postman's sandbox.

**Comment by abhijitkane** [comment]
@thizanetti @Afbcary with the latest version of Postman (5.2.x), you can simply add a `setTimeout(function(){}, 2000);` anywhere in your test script to add a 2 second delay before the next request.

**Comment by testmonger** [comment]
v 6.0.9
request: https://echo.getpostman.com/delay/10
response: This service has moved to https://postman-echo.com

as indicated, this works:
https://postman-echo.com/delay/10

**Comment by m3dbedb** [comment]
In my case (postmal 6.3.5) the only local desigion that works is this:

> var t = new Date().getTime();
> while (new Date().getTime() < t + 10000);

**Comment by dugcool** [comment]
> v 6.0.9
> request: https://echo.getpostman.com/delay/10
> response: This service has moved to https://postman-echo.com
> 
> as indicated, this works:
> https://postman-echo.com/delay/10

What "testmonger" wrote is the answer, we had been using this in our code in Postman Ver: 6.6.1 and it works beautifully in a production setting.

**Comment by maxbet111** [comment]
I solve this problem to add this string in prerequest requst tab in postman -  var time = setTimeout(function(){}, [90000]);

**Comment by adityakap** [comment]
I stumbled upon this thread trying to find a way to iterate on a request...
> until I get a certain number of objects on the response (after a background async process is done) OR 
> exit the test with fail after waiting a finite amount of time. 

Here is my approach... 

I added the following function and set a collection var on the first request of the test case ..

This creates a collection variable with a dateTime value 10m in future.
```
var addmin =  function (dt, minutes) {
    return new Date(dt.getTime() + minutes*60000);
}

pm.collectionVariables.set("cvar_futureTime", addmin(new Date, 10));
```

Couple of requests after above request, I have this request named "FindMyPackage".. I wrote the following in Tests tab


```
let findPackageResponse = JSON.parse(responseBody);
let currentDateTime = new Date();

if (findPackageResponse.length<1){
    if (currentDateTime>Date.parse(pm.collectionVariables.get("cvar_futureTime")))
    {
        console.log("My Package is not available even after waiting for 10m. Request: \n"+ pm.request.url.getRaw());
        pm.expect.fail("My Package not available even after waiting for 10m");
        //postman.setNextRequest(null);
    }
    setTimeout(function(){}, 10000);
    postman.setNextRequest("FindMyPackage");
}
```

This is working but smh it feels like there is a better way to do this. Please advice
