### ISSUE TITLE
Couldn't access this workspace You don’t have permission to access this workspace.

### ISSUE THREAD

**Issue by SanthanaRamaraj** [a85/POSTMan-Chrome-Extension#10388]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

I use to access my workspace without any issues. But i had play around the team workspace and changed my setting and edit role permission accidentley. after some time i lost my enitire workspaces and trying access my old workspace i am getting  fllowing message. Can you please someone help to revover my workspace and recover date?
I Couldn't access this workspace
You don’t have permission to access this workspace.

![image](https://user-images.githubusercontent.com/92961994/138378994-23b3b2cb-c321-49a0-abe4-07a3421af4e4.png)

### Steps To Reproduce

1. Login to Postman with username and password
2. Go to WorkSpace Tab
3. Select /click - My Workspace

![image](https://user-images.githubusercontent.com/92961994/138379241-7d3e3785-cbb5-4770-a15a-5e61a277f5d1.png)

### Environment Information

```markdown
- Operating System: Windows 10
- Platform Type: Desktop app
- Postman Version: v9.1.1 is the latest version
```

**Comment by sujayvenaik** [comment]
Hey @SanthanaRamaraj

Can you open a support ticket with all the relevant details (like workspaceIds/name) and someone should pick it up from there to assist you on this.

Please raise a ticket at https://postman.com/support or by emailing us at help@postman.com.
Thank you, we'll be keeping an eye out for your ticket.

**Comment by akshay-kulkarni-03** [comment]
@SanthanaRamaraj can you please raise ticket at [https://postman.com/support](https://postman.com/support).

**Comment by Denis-Tsybulin** [comment]
Removal of Postman local data solved issue in my case
