### ISSUE TITLE
Request URLs intermittently getting truncated upon request send

### ISSUE THREAD

**Issue by johnnyman727** [a85/POSTMan-Chrome-Extension#10383]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

Intermittently, I've noticed that HTTP requests will get sent with a portion of the URL I entered truncated. A subsequent request sent to the same URL (nothing changed except hitting "Send" again will use the entire URL.

My server was responding with 404 errors and I thought there was a server-side issue. When I investigated, I saw that my server was receiving partial URLs (with 1 - 4 characters at the end missing). I confirmed by looking in the History tab of Postman and, sure enough, it documented that the URL that was sent was not complete.

In my experience, it happens more reliably when you change the URL and hit send in quick succession. My uneducated guess is that it's related to local or remote syncing. 

### Steps To Reproduce

1. Open up a new DB request
2. Make a valid request to a server
3. Rapidly type another valid URL and hit send

### Environment Information

```markdown
- Operating System: macOS Big Sur
- Platform Type: Native App
- Postman Version: 8.5.1
```

**Comment by shubhbhargav** [comment]
@johnnyman727 Can you please share a recording / screenshot of the issue to help us debug this further? Also do let us know if upgrading to the latest app (9.12.2) fixes the issue.

**Comment by johnnyman727** [comment]
@shubhbhargav Thanks for popping in to help. Apologies, I don't have time right now to try to reproduce. Feel free to close the issue and I'll comment back here if it ever happens again. FWIW, I've been using Postman pretty regularly the past week and haven't had the problem.
