### ISSUE TITLE
Two emphasized words next to each other render incorrectly

### ISSUE THREAD

**Issue by galvao** [a85/POSTMan-Chrome-Extension#10396]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

If you type two emphasized words next to each other in the documentation pane they show up without the blank space between them in the preview.

### Steps To Reproduce

1. Open the documentation pane for a request;
2. Type two emphasized words next to each other, separated by a blank space, e.g.: *foo* *bar*
3. Click the "preview" button.

### Environment Information

```markdown
- Operating System: Linux (Fedora 33)
- Platform Type: App
- Postman Version: 9.1.1
```

**Comment by Swapnil-getpostman** [comment]
Hi @galvao 

I tried to replicate and it worked as expected for me. I'm attaching the screen record for your reference. 

https://user-images.githubusercontent.com/52168965/138814705-9080e431-b41d-4453-82d7-494dba7da489.mp4

My apologies, if this is not something you are referring to then do share with us the screen record of the behavior you are observing.

Also, are you able to replicate the same over [Postman on the Web version](https://go.postman.co/)?

**Comment by galvao** [comment]
Hi @Swapnil-getpostman. Thank you for the quick reply.

I haven't tested on the web, only using the desktop app. You can see the video in th link below (Sorry about the video resolution, hopefully you'll be able to watch it):

https://drive.google.com/file/d/1lwIoF9s5NLDCLmpffeV33ZIQx5Xf3yCq/view?usp=sharing

**Comment by Swapnil-getpostman** [comment]
Hi @galvao 

To have space between two words, then do refer to the below screen record. Hope this helps!

https://user-images.githubusercontent.com/52168965/139195676-afba510b-1b8d-4f06-8d58-e2d5f1b55a2c.mp4

**Comment by galvao** [comment]
Ah, thank you! That's a very clever workaround! =)

**Comment by postman-staff** [comment]
Hi @galvao

Thanks for the update. :)

We are going ahead and closing only the support request now but the GitHub request will still be open, so feel free to respond to this thread if you have any other queries.

via @Swapnil-getpostman | Postman Support
