### ISSUE TITLE
Run Collection stops after errors

### ISSUE THREAD

**Issue by markbullock-mbo** [a85/POSTMan-Chrome-Extension#10391]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request

### Is your feature request related to a problem?

I tried to run a collection and some requests failed due to connection refused or request url is empty. This stops the run.

### Describe the solution you'd like

Either don't ever stop the collection run until all requests complete
OR give me a setting to choose whether or not to stop on errors.

**Comment by giridharvc7** [comment]
Duplicate of #3360 . Closing this here to track it there.
