### ISSUE TITLE
win10 64版本无法打开个人工作空间 ，测试网页版正常打开。

### ISSUE THREAD

**Issue by sakiyo** [a85/POSTMan-Chrome-Extension#10395]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

点击Workspaces->My Workspace 控制台就报错了。

### Steps To Reproduce

1.click Workspaces
2.click My Workspace

### Environment Information

```markdown
- Operating System: win10 64
- Platform Type: 
- Postman Version:9.0.8
```

### Additional Context?

![Screenshot_4](https://user-images.githubusercontent.com/13010515/138558785-155df9ee-ed82-4ee2-baef-f6192df0e6cc.png)
![Screenshot_3](https://user-images.githubusercontent.com/13010515/138558788-87f57f24-cdf0-4a91-ab6f-46bdf104e6f2.png)

**Comment by DannyDainton** [comment]
Hey @sakiyo 

Are you still seeing this issue after signing out of the app and signing back in? 

I've tried to recreate the issue using Windows 10 and version 9.0.8 of Postman, I'm able to open the Workspace in the app.

![image](https://user-images.githubusercontent.com/17089546/138672876-01cec996-0bc8-4f2e-872d-7d0431985254.png)

**Comment by sujayvenaik** [comment]
@sakiyo is this issue resolved for you?

I'll close this thread because of inactivity, but feel free to leave a comment or raise a ticket at https://postman.com/support or by emailing us at help@postman.com.

Thank you.
