### ISSUE TITLE
validating a json response for a test

### ISSUE THREAD

**Issue by JohnnyTripod** [a85/POSTMan-Chrome-Extension#1039]
Here is my response for an api call I have. I want to verify that that 14.99 response was returned.
{
"status_code": 1,
"response_data": {
"start_date": 1428116640,
"end_date": 1430708640,
"history": [
{
"type": "visit charge",
"id": "2a8fc9b4-ca20-43cc-a314-64487645dc60",
"date": "2015-05-03 18:39:26",
"merchant_id": "e8cec5de-34f7-4a0c-b0d5-abe522938c70",
"merchant_name": "GameStop",
"components": [
{
"type": "loyalty",
"amount": "5.0000",
"id": "d8f1790c-fd1f-4134-9fa9-7aa97486c307"
},
{
"type": "card",
"amount": "9.9900",
"id": "63e54e82-5c67-486d-9f5e-89f0e86b38a2",
"last_four": "2183"
}
],
"amount": "14.99"
},
{
"type": "visit charge",
"id": "19f79ec7-c7b9-41f1-8a7e-5483da5ba904",
"date": "2015-05-03 18:38:59",
"merchant_id": "e8cec5de-34f7-4a0c-b0d5-abe522938c70",
"merchant_name": "GameStop",
"components": [
{
"type": "card",
"amount": 0,
"id": "63e54e82-5c67-486d-9f5e-89f0e86b38a2",
"last_four": "2183"
}
],
"amount": "0.00"

 What is the js to verify that? There are multiple responses so how do I verify the first one? I have this so far but it fails:

var data = JSON.parse(responseBody);
tests["Check that checkout happened"] = data.response_data.history.amount[0] == 14.99;

Johnny

**Comment by abhijitkane** [comment]
history is the array, not amount.
try `tests["Check that checkout happened"] = data.response_data.history[0].amount == 14.99;`

**Comment by JohnnyTripod** [comment]
Perfect. Thanks.
