### ISSUE TITLE
GraphQl interfaces now can implement interfaces

### ISSUE THREAD

**Issue by Ciloe** [a85/POSTMan-Chrome-Extension#10405]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

When I past a graphql Schema, I have a error on implements. Postman say that implement can't be on interface.

**BUT**

Since the spec in October 2021, it's now possible : 
https://spec.graphql.org/October2021/#sec-Interfaces
https://github.com/graphql/graphql-spec/blame/October2021/spec/Section%203%20--%20Type%20System.md#L1147-L1156

### Steps To Reproduce

1. Create a new API Graphql
2. Past this Schema
```grahql
schema {
  query: Query
}
type Query {
  post (id: String): Post
}

interface NodeInterface {
  id: ID!
}

interface Post implements NodeInterface {
  id: ID!
  identifier: Int!
  content: String!
}

type PostDestination implements NodeInterface & Post {
  id: ID!
  identifier: Int!
  content: String!
  introduction: String!
}
```
3. See an error on implement in Post interface

### Environment Information

```markdown
- Operating System: MAC OSX
- Platform Type: Native App
- Postman Version: 9.0.7
```

**Comment by SterlingChin** [comment]
The new GraphQL client is in open beta and fully supports the Oct. 21 spec. I followed your steps to reproduce in the new client and am not seeing the error on implement.

![graphql-issue-test](https://user-images.githubusercontent.com/8900638/221686597-47a7ef95-2d98-4725-9743-1eaf58cc04fe.gif)
