### ISSUE TITLE
form-data type="file" isnt saved properly in collections

### ISSUE THREAD

**Issue by zvaehn** [a85/POSTMan-Chrome-Extension#1040]
the key keeps but the chosen file disappears and you have to select it over and over again after switching back from another saved request.

**Comment by abhijitkane** [comment]
The current Chrome app platform prevents us from saving a handle to the file with the request.

**Comment by abhijitkane** [comment]
Closing as duplicate of https://github.com/postmanlabs/postman-app-support/issues/1113
