### ISSUE TITLE
Latest Canary is a major version behind Stable

### ISSUE THREAD

**Issue by Fydon** [a85/POSTMan-Chrome-Extension#10413]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

The latest Canary release for Windows 10 is v8.12.0-canary210820-1135. The latest Canary download for all platforms is at most v8.10.0. The latest stable download is v8.12.5, but it updates to v9.1.3. Has Canary been abandoned? If not, would it be possible to have it updated to at least the latest stable?

This is particularly a problem due to Let's Encrypt only being fixed in v9.0.5 and so broken in the latest Canary.

### Steps To Reproduce

1. Download latest Canary
2. Let it update

### Environment Information

```markdown
- Operating System: Windows 10
- Platform Type: Native App
- Postman Version: v8.12.0-canary210820-1135
```

**Comment by jonycheung** [comment]
@Fydon We have recently updated Canary https://www.postman.com/downloads/canary/ Please reopen if this is still an issue.
