### ISSUE TITLE
Lost all my request endpoints on changing folder

### ISSUE THREAD

**Issue by joshjo** [a85/POSTMan-Chrome-Extension#10412]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

I had all my endpoints inside one folder. Then I decided to organize them and create some folders. I moved the endpoints to different folders and start using them, they worked normally. Today I open Postman, and all the endpoints I moved to new folders were gone. The tabs were open saying that the request does not exist. I cannot recover any of them, as they are not in the old folder, and they are not even in the trash. This is really annoying. 

### Steps To Reproduce

1. Create a folder
2. Create multiple requests endpoints in the same folder
3. Create a new folder
4. Move all the endpoints to the new folder.
5. Close the app
6. Open the app again.

### Environment Information

```markdown
- Operating System: Linux
- Platform Type: Native App
- Postman Version: 8.12.5
```

**Comment by postman-staff** [comment]
Hi @joshjo,

We are unable to replicate the issue from our end. May I request you to please update the app to the latest version and let me know if this is still an issue?  Also, can you navigate to the web version- https://go.postman.co/ and check if it's working as expected? Thanks!

via @ash007-postman | Postman Support

**Comment by postman-staff** [comment]
Hi,

I hope that our response to the raised query was helpful.

Do keep us posted if any further assistance is required from my end on any other concern, on the same grounds.

Thank you!

Regards,
Asha Singh

Status Page | Learning Center | YouTube | Twitch | Bugs + Feature Requests | Community

* * *

Product Support Business Hours: `Monday, 3:30 AM UTC - Friday, 11:30 PM UTC`

**Comment by postman-staff** [comment]
Hi @joshjo,

Just letting you know that I'm going ahead and closing this conversation in the absence of required information. If you still need help, just respond, otherwise, please feel free to reach out again later!

Have a great day!

via @ash007-postman | Postman Support
