### ISSUE TITLE
API changelog not working

### ISSUE THREAD

**Issue by br-tyler-milner** [a85/POSTMan-Chrome-Extension#10421]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

The API changelog is not working. When trying to load or refresh it, I get a `There was a problem loading the changelog` error (see attached screenshot and video).

![image](https://user-images.githubusercontent.com/78233128/140526010-d84b1bd1-9d9e-4e21-b082-73af8eef1705.png)

In Postman for the web, I'm able to open the changelog, but it doesn't refresh with changes that have been made.

### Steps To Reproduce

1. Open Postman
2. Make a change to an API (e.g. modify schema)
3. Open the Changelog
4. Observe the "there was a problem" error

### Screenshots or Videos

https://user-images.githubusercontent.com/78233128/140525837-7db50ee6-0fac-4c7e-a1b1-58c684407b8e.mov

### Environment Information

```markdown
- Operating System: macOS 11.6.1
- Platform Type: Native App / Postman Web
- Postman Version: 9.1.3
```

### Additional Context?

This isn't the first time that this has happened. I saw this happen last year with #9220.

**Comment by shivangibajpai12** [comment]
@br-tyler-milner Thanks for reporting the issue. Could you confirm the following -

1. Is it still happening?
2. Is it reproducible for multiple APIs or just this one?

Could you also share the API and API version id here or send them to help@getpostman.com?

**Comment by br-tyler-milner** [comment]
Yes, it is still happening for me. I first noticed it yesterday.

It is reproducible for multiple APIs across multiple workspaces. Here is the information for the Demo API that I just created that is having this issue:
- API id: f6bfed83-b833-4a10-815b-60bf8cd02848
- Version id: 80dc6c82-e44a-413c-9d3a-2dc08351515a

**Comment by shivangibajpai12** [comment]
@br-tyler-milner Thanks for sharing the details. Would it be possible to invite us(shivangi.bajpai@postman.com) to a demo workspace with this API?

**Comment by br-tyler-milner** [comment]
@insomniac12 Changelog is working now for this workspace. Closing issue...
