### ISSUE TITLE
Cannot detach Postman Console window after the latest update

### ISSUE THREAD

**Issue by ThisNoName** [a85/POSTMan-Chrome-Extension#10426]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

Previously, console can be viewed inline, or detached in a separate window via View - Postman Console, but that's no longer the case.  Users tester11 and MarioG8 on Stackoverflow pinpointed the last working version was 9.0.9

[How to detach Postman console into a separate window](https://stackoverflow.com/questions/69757314/how-to-detach-postman-console-into-a-separate-window/69757513?noredirect=1#comment123535281_69757513)

### Steps To Reproduce

On Windows, up until Postman 9.0.9, console can be viewed inline, or detached using View - Postman Console.  After that, both action lead to inline view.  

### Environment Information

```markdown
- Operating System: 
- Platform Type: 
- Postman Version:
```

**Comment by malvikach** [comment]
@ThisNoName could you try this after the latest version update and let me know if you still see this issue. (Latest version 9.1.3 )

I tried to replicate this on my end and it seems to be working for me. Happy to look into this further if you are still facing it.

**Comment by ThisNoName** [comment]
@malvikach Thanks for the follow up.  Just tried on two separate Windows 10, version 1909 and 21H1.  Download and install Postman-win64-8.12.5-Setup.exe.   View - Show Postman Console open up new windows in original version and 9.0.9 update.  After update to 9.1.3, the same action only expand the console panel in main screen.

Also tried on Windows 2016, 1607.  Fresh install, no account, no project, same result.

**Comment by malvikach** [comment]
@ThisNoName  Thanks for the info, we tested this on our end. 

This is the expected behavior when you are using the scratchpad. (On scratchpad, we do not support detaching of console from version 9.1 onwards) . 

I would request you to sign in using your account and try this again on one of your workspaces. You should be able to detach the console. (We have tested this on a windows machine and are positive about the behavior). If you still face the issue, we will need to investigate this further.

Do let me know your feedback.

**Comment by ThisNoName** [comment]
Thanks, looks like that's the cause, but kind of an odd restriction.  I stop using signed in account a while back because there's no easy way to export projects, and it wiped out everything I got upon signed out without warning.  Maybe that has changed since.  Either way, really appreciate your help.

**Comment by malvikach** [comment]
@ThisNoName Thanks for your response. I am going to take the Exporting/Sharing data from postman has been made really easy in last few releases. You can export collections,environments as json and also share it with other team members and collaborate live with them on your projects. Do check

**Comment by malvikach** [comment]
@ThisNoName  Thanks for your response. 

I am going to take the liberty to talk to you about Exporting/Sharing data from postman. This has been made really easy in last few releases. You can export collections,environments as json and also share it with other team members and collaborate live with them on your projects. Do check out our learning center [docs](https://learning.postman.com/docs/getting-started/importing-and-exporting-data/#exporting-postman-data). 

Besides this, you can also integrate with git now. Read more [here](https://learning.postman.com/docs/integrations/available-integrations/gitlab/)

I hope this information helps you. I would love for you to try these out and let us know if these solve your usecases. Thanks again.

**Comment by srajamohan** [comment]
This is the worst decision to restrict the users to detach console. What benefit it is providing to Postman? I can see slowly moving towards monopoly

**Comment by seerazz** [comment]
This doesn't work on windows 11, although i already signed in to postman

**Comment by vincenzo-scia** [comment]
Please consider changing the expected behaviour and make console detaching available again on scratchpad mode. Come on, this restriction appears to have no sense ...thank you.
