### ISSUE TITLE
"Save Response" seems to ignore case of filename in specific conditions

### ISSUE THREAD

**Issue by eap-nutanix** [a85/POSTMan-Chrome-Extension#10425]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

When trying to save a from "Save Response", Postman seems to ignore case, at least when the first letter is uppercase.

### Steps To Reproduce

1. Send a HTTP command that generates some output
2. Use Save Response -> Save to file with filename "True.json"
3. Use Save Response -> Save to file with filename "true.json"
4. Postman pops up warning saying that "True.json" already exists

### Screenshots or Videos

![Screen Shot 2021-11-05 at 9 19 59 AM](https://user-images.githubusercontent.com/46230899/140764343-1cd97e75-cfbf-4930-b2f6-59acd925b556.png
![image (15)](https://user-images.githubusercontent.com/46230899/140764581-75e074e2-ef43-4b50-b34a-61cc35752eb6.png)
)

### Environment Information

```markdown
- Operating System: MacOS 11.2.3
- Platform Type: Macbook Pro
- Postman Version: 9.1.3
```

### Additional Context?

A colleague confirms that this also happens under Windows as well

**Comment by malvikach** [comment]
@eap-nutanix thanks for taking time and providing us feedback on the above. However, this is a limitation of Mac OS. 

You could try to check this by creating a file on your desktop and then create another file with the same name but a different case. 

Please let us know if you still find some concerns on this, we will be happy to help. 

For now, I will be closing this issue.
