### ISSUE TITLE
CSV File not recognized

### ISSUE THREAD

**Issue by dhoyt** [a85/POSTMan-Chrome-Extension#1042]
I am running a postman collection via newman in a node js file. I have this ...

// define Newman options 
var newmanOptions = {
    envJson: "api1.postman_environment",
    dataFile: "DELETE_USERS.csv",
    iterationCount: allUsers.length-1,
    responseHandler: "TestResponseHandler",
    asLibrary: true, 
    outputFile: log_fileName,  
    stopOnError: true
}

When the collection runs, the CSV datafile is not being recognized as a CSV file and the variable substitution fails. Is there some setting that I have to use to indicate that is it a CSV file that is being used ?

Note: When running the same collection via the collection runner, when I choose the same CSV file, I get an error saying that it couldn't determine the type of file and then I have to actually choose CSV via the dropdown.

**Comment by abhijitkane** [comment]
Some users have reported problems with Unix/Windows-style line endings. Can you try opening the file in SublimeText or any other editor, and save it with 'utf-8' encoding?

**Comment by dhoyt** [comment]
I just tried it using Sublime and it didn't seem to make a difference.

**Comment by abhijitkane** [comment]
Can you send the CSV file to help@getpostman.com

**Comment by dhoyt** [comment]
sent

**Comment by abhijitkane** [comment]
Weird..I'm able to import the file in the collection runner and in Newman without a problem.

We'll continue investigating and let you know if we manage to find something. The Collection Runner not being able to identify it as a CSV file points to an encoding issue though.

Do you face the same problem if you manually create a new CSV file and try to import it in the runner?

**Comment by dhoyt** [comment]
The collection runner doesn't recognize a JSON file either so it's not just the CSV file.

**Comment by Watje** [comment]
I'm having exactly the same problem. Did you manage to find out what was wrong with the CSV?

**Comment by dhoyt** [comment]
I haven't ... I had to change it to use a JSON file as input
