### ISSUE TITLE
Typo in Code snippet for Python for midi file mime

### ISSUE THREAD

**Issue by boltomli** [a85/POSTMan-Chrome-Extension#10432]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

In the sample `audip` should be `audio`.

```
files=[
  ('file',('116918.mid',open('/C:/Users/xxxx/xxxx.mid','rb'),'audip/midi'))
]
```

### Steps To Reproduce

1. Upload a midi file
2. Open Code snippet
3. Switch to Python

### Environment Information

```markdown
- Operating System: Windows 11
- Platform Type: Native App
- Postman Version: 9.1.3
```

**Comment by VShingala** [comment]
@boltomli This issue has been fixed with latest version of Postman App v11.6.


![Image](https://github.com/user-attachments/assets/4324fa64-53ca-4049-ada9-d7d5e84140ae)

We're closing this issue for now but feel free to re-open it if you face any further problems with the fix.
