### ISSUE TITLE
OAuth 2.0 Authorization Code and Authorization Code with PKCE does not log request to Auth URL

### ISSUE THREAD

**Issue by bradydean** [a85/POSTMan-Chrome-Extension#10434]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

The authorization code flow sends a request to the Auth URL but that request/response is not logged in the console.
It does log the Access Token URL request, but I'm expecting the authorization request to come first.

### Steps To Reproduce

1. Open a request tab
2. Open the authorization tab
3. Select OAuth 2.0
4. Select Authorization Code or Authorization Code with PKCE
5. Fill in remaining details for the IDP and client
6. Click Get New Access Token
7. Sign in through browser
8. Look at the console.

### Environment Information

```markdown
- Operating System: Fedora 35
- Platform Type: Native App
- Postman Version: v9.1.3
```

**Comment by bradydean** [comment]
To add a bit more context to this issue, I also believe there is another issue in Postman while it performs the authorization code flow. In my use case, I have an audience set under the advanced tab. Postman is attaching the audience value to the request to the Access Token URL, but my understanding is that the audience value should be attached to the request to the Auth URL. I cannot verify Postman does this or not because the request isn't logged. I use Auth0 as my IDP and they expect the audience value to be set in the request to the Auth URL. Attaching the audience value to the request to the Access Token URL does nothing. If Auth0 receives an audience value they issue a JWT. If they do not receive an audience value they issue an opaque token, which as been my experience. That leads me to believe Postman is not attaching the audience value to the request to the Auth URL.

**Comment by postman-staff** [comment]
Hey @bradydean,

Thanks for reaching out! I'm happy to help.

When using the  'Authorize using Browser'  in the Authorization Tab, the calls will be logged in the Browser. Since the request is not sent via Postman, it won't be logged in the Postman console.
 ![](https://postman.zendesk.com/attachments/token/bpNwF4EE8AFEQDejpzyikhrXI/?name=Screen+Shot+2021-11-15+at+11.20.35+AM.png)



 ![](https://postman.zendesk.com/attachments/token/caOYtsUtoWzY0bE2FH98w5OUl/?name=AuthorizeviaBrowser+%281%29.png)

However unticking the 'Authorizing using Browser' and going through the authorization flow should log the calls as expected in the console.

 ![](https://postman.zendesk.com/attachments/token/DMBoFDVCDIg8gDqo4WzshcK6K/?name=AuthorizedirectlyonPostman+%281%29.png)

Can you please open the dev tools in your browser window if using 'Authorize using Browser' to see if the calls are being logged as expected or Authorize directly in Postman and check the Postman Console?

Please let me know if I've missed anything here.

Thank you!  :)

via @nrmartell | Postman Support

**Comment by bradydean** [comment]
@postman-support After unchecking 'Authorizing using Browser' I can now see the request. (I didn't even think about the browser sending that request lol).

However, this request is missing the `audience` query parameter (I have it specified in the advanced settings). Auth0 will not issue the token I am expecting unless the audience is provided to the Auth Url.

Here is [Auth0's docs](https://auth0.com/docs/authorization/flows/call-your-api-using-the-authorization-code-flow) detailing the parameters available for the query.

**Comment by postman-staff** [comment]
Hi @bradydean

Thanks for following up! Glad to hear we've got one behavior accounted for.

If possible can you share the screenshots of your advanced options tab where the audience parameter is set and the full output of the response from the Postman Console. Please feel free to redact any sensitive details from there.

Thanks! :)

All the best,

Natalie
Technical Support Engineer, Postman

Status Page | Learning Center | YouTube | Twitch | Bugs + Feature Requests | Community

* * *

Product Support Business Hours: `Monday, 3:30 AM UTC - Friday, 11:30 PM UTC`

**Comment by bradydean** [comment]
![postman](https://user-images.githubusercontent.com/88594046/142090407-77ed3f0e-2f05-4d19-9010-f2028b0b12ae.png)
Here's the full details for the requests.

```
GET https://xxxxx.us.auth0.com/authorize?response_type=code&client_id=xxxxxx&redirect_uri=https%3A%2F%2Foauth.pstmn.io%2Fv1%2Fcallback&code_challenge=xxxxxxx&code_challenge_method=S256: {
  "Request Headers": {
    "upgrade-insecure-requests": "1",
    "user-agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Postman/9.1.3 Chrome/87.0.4280.88 Electron/11.1.1 Safari/537.36",
    "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
    "sec-fetch-site": "none",
    "sec-fetch-mode": "navigate",
    "sec-fetch-user": "?1",
    "sec-fetch-dest": "document",
    "accept-encoding": "gzip, deflate, br",
    "accept-language": "en-US",
    "cookie": "xxxxxx"
  },
  "Response Headers": {
    "alt-svc": "h3=\":443\"; ma=86400, h3-29=\":443\"; ma=86400, h3-28=\":443\"; ma=86400, h3-27=\":443\"; ma=86400",
    "cache-control": "no-store, max-age=0, no-transform",
    "cf-cache-status": "DYNAMIC",
    "cf-ray": "6af4feeb4e10e222-ORD",
    "content-length": "156",
    "content-type": "text/html; charset=utf-8",
    "date": "Wed, 17 Nov 2021 00:55:50 GMT",
    "expect-ct": "max-age=604800, report-uri=\"https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct\"",
    "location": "https://oauth.pstmn.io/v1/callback?code=xxxxxxxx",
    "ot-baggage-auth0-request-id": "6af4feeb4e10e222",
    "ot-tracer-sampled": "true",
    "ot-tracer-spanid": "3d665fbb5fb0bee9",
    "ot-tracer-traceid": "0949435a16d19def",
    "pragma": "no-cache",
    "server": "cloudflare",
    "set-cookie": [
    ],
    "strict-transport-security": "max-age=31536000",
    "vary": "Accept, Accept-Encoding",
    "x-auth0-requestid": "a4a51fca0a8b5a40b0a4",
    "x-content-type-options": "nosniff",
    "x-ratelimit-limit": "300",
    "x-ratelimit-remaining": "299",
    "x-ratelimit-reset": "1637110551"
  }
}
POST https://xxxxx.us.auth0.com/oauth/token: {
  "Network": {
    "addresses": {
      "local": {
        "address": "192.168.1.16",
        "family": "IPv4",
        "port": 60588
      },
      "remote": {
        "address": "104.16.171.253",
        "family": "IPv4",
        "port": 443
      }
    },
    "tls": {
      "reused": false,
      "authorized": true,
      "authorizationError": null,
      "cipher": {
        "name": "TLS_AES_128_GCM_SHA256",
        "standardName": "TLS_AES_128_GCM_SHA256",
        "version": "TLSv1/SSLv3"
      },
      "protocol": "TLSv1.3",
      "ephemeralKeyInfo": {},
      "peerCertificate": {
        "subject": {
          "country": "US",
          "stateOrProvince": "California",
          "locality": "San Francisco",
          "organization": "Cloudflare, Inc.",
          "commonName": "us.auth0.com",
          "alternativeNames": "DNS:*.guardian.us.auth0.com, DNS:*.edge.tenants.us.auth0.com, DNS:*.us.auth0.com, DNS:us.auth0.com"
        },
        "issuer": {
          "country": "US",
          "organization": "Cloudflare, Inc.",
          "commonName": "Cloudflare Inc ECC CA-3"
        },
        "validFrom": "Sep 21 00:00:00 2021 GMT",
        "validTo": "Sep 20 23:59:59 2022 GMT",
        "fingerprint": "0F:1F:6A:19:49:C4:38:D7:1D:50:D7:47:01:53:F7:6C:68:FF:C9:E0",
        "serialNumber": "0fc08a7d6f7ee83266230eefb7b4ee88"
      }
    }
  },
  "Request Headers": {
    "content-type": "application/x-www-form-urlencoded",
    "authorization": "Basic xxxxx",
    "user-agent": "PostmanRuntime/7.28.4",
    "accept": "*/*",
    "cache-control": "no-cache",
    "postman-token": "xxxxxx",
    "host": "xxxxxxxx.us.auth0.com",
    "accept-encoding": "gzip, deflate, br",
    "connection": "keep-alive",
    "content-length": "254",
    "cookie": "xxxxxxxx"
  },
  "Request Body": {
    "grant_type": "authorization_code",
    "code": "xxxxxxxxxxx",
    "redirect_uri": "https://oauth.pstmn.io/v1/callback",
    "audience": "https://ticketing-service/",
    "code_verifier": "xxxxxxxxxxxxxx",
    "client_id": "xxxxxxxxxxxxxxx"
  },
  "Response Headers": {
    "date": "Wed, 17 Nov 2021 00:55:51 GMT",
    "content-type": "application/json",
    "transfer-encoding": "chunked",
    "connection": "keep-alive",
    "cf-ray": "6af4feefebbb2d4c-ORD",
    "cache-control": "no-store",
    "strict-transport-security": "max-age=31536000",
    "vary": "Accept-Encoding, Origin",
    "cf-cache-status": "DYNAMIC",
    "expect-ct": "max-age=604800, report-uri=\"https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct\"",
    "ot-baggage-auth0-request-id": "6af4feefebbb2d4c",
    "ot-tracer-sampled": "true",
    "ot-tracer-spanid": "410ed4626077e878",
    "ot-tracer-traceid": "6d6561b01d08f115",
    "pragma": "no-cache",
    "x-auth0-requestid": "c591176d5f6e5ade3708",
    "x-content-type-options": "nosniff",
    "x-ratelimit-limit": "30",
    "x-ratelimit-remaining": "29",
    "x-ratelimit-reset": "1637110552",
    "server": "cloudflare",
    "content-encoding": "br",
    "alt-svc": "h3=\":443\"; ma=86400, h3-29=\":443\"; ma=86400, h3-28=\":443\"; ma=86400, h3-27=\":443\"; ma=86400"
  },
  "Response Body": "{\"access_token\":\"xxxxxxxxxx\",\"expires_in\":86400,\"token_type\":\"Bearer\"}"
}
```

**Comment by postman-staff** [comment]
Hey @Bradydean,

Thanks for providing all of those details. Can you try using the audience in the AuthURL as a query parameter when using the PKCE Grant type? It looks like with this grant type, in Auth0, expects audience in AuthURL.

I'm circling back with our team internally on this as well. Hope this gives you a workaround for the time being.

via @nrmartell | Postman Support

**Comment by bradydean** [comment]
@postman-support This is working for now.

**Comment by postman-staff** [comment]
Appreciate your patience here. At this time we are currently following guidelines/standard from IANA which mentions OAuth Parameters usage location in the `Token Request` only.

Adding it to the auth request would not be following the standard. Our team will be looking into a more customizable Auth to see if it is feasible, but at this time we are following the guidelines mentioned previously. We appreciate your time in bringing this to our attention and providing all of the requested details.

Have a great day!

via @nrmartell | Postman Support
