### ISSUE TITLE
Left Panel Menu Position When Full Of Items

### ISSUE THREAD

**Issue by philostler** [a85/POSTMan-Chrome-Extension#1043]
Postman Sync Version 3.0.0.20 (packaged)
OS: mac

When the left panel has with enough items to reach the bottom of the window, selecting the menu button presents the menu off the bottom of the panel, requiring the user to scroll to reach it.

![screen shot 2015-05-05 at 09 52 44](https://cloud.githubusercontent.com/assets/244198/7469825/9feb7e4e-f30f-11e4-8dd0-cf35dbfa53fe.png)
![screen shot 2015-05-05 at 09 52 47](https://cloud.githubusercontent.com/assets/244198/7469826/a10925e2-f30f-11e4-9319-161179206962.png)

**Comment by a85** [comment]
This has been fixed in the latest release.
