### ISSUE TITLE
Allow use of query parameters in mock example body

### ISSUE THREAD

**Issue by HugoSart** [a85/POSTMan-Chrome-Extension#10435]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request

### Is your feature request related to a problem?

When writing API mocks, it's very crucial sometimes that the response body matches the provided query arguments. For example, if I provide an object id in a query parameter, I should be able to provide a response with the same object id.

### Describe the solution you'd like

Support for query parameters variables in body variables when creating API mocks.

**Comment by akshaydeo** [comment]
Hi @HugoSart, thank you for reaching out to us with this feature. We are working on a few feature sets which should cover this use case. The tentative release time is in Q1 2022. 

We will keep you updated with our progress around this feature :).

**Comment by Dhembla** [comment]
Hey @HugoSart, As per our latest app release(v10.7), we have added support for template helpers that can be used while authoring examples and helps you access request data(headers, body, query params and path segments) in mock responses. You can read more about the feature [here](https://blog.postman.com/introducing-support-for-templating-in-postman-mock-servers/).
Please give it a try and let us know if the solution meets your needs. Thanks for your patience. 🙇
