### ISSUE TITLE
Decode JWT's in tests. To test value of JWT claims.

### ISSUE THREAD

**Issue by cluda** [a85/POSTMan-Chrome-Extension#1044]
Should be able to decode JWT's in tests. To test value of JWT claims.

**Comment by benhowes** [comment]
I'm using this kind of gist as a workaround: https://gist.github.com/benhowes/ebf9d2f905d7744e7aa093afe19ddbcd

It would be great to be able to leverage a built in library for this. It would also be cool if there was a way you could add some scripts to the collection which let you define utilities to use in all tests of that collection. Might be a more flexible approach to start off?

----

Edit, it's mentioned in a comment on that gist that the following snippet works in postman >6.7

```
function jwt_decode(jwt) {
    var parts = jwt.split('.'); // header, payload, signature
    return JSON.parse(atob(parts[1]));
}
```

**Comment by knightpfhor** [comment]
As mentioned in a [comment on that gist](https://gist.github.com/benhowes/ebf9d2f905d7744e7aa093afe19ddbcd#gistcomment-2811160), as of Postman 6.7 it is possible to parse the payload of a JWT with two lines of code.

**Comment by codenirvana** [comment]
Closing as this can be solved using the workaround mentioned in https://github.com/postmanlabs/postman-app-support/issues/1044#issuecomment-230813374

**Comment by weitzhandler** [comment]
Would be nice if this functionality is built into Postman.
Thank you!
