### ISSUE TITLE
Addition features requirement | Suggestion | HTTP | GET

### ISSUE THREAD

**Issue by nitish166** [a85/POSTMan-Chrome-Extension#10445]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request

### Is your feature request related to a problem?

# Context about the issue:

- We were working on one of the API-related issues and we need the URL for the whole HTTP address + access token(bearer token) + header (API) auto-generated. on the postman.

- Below screenshot shows that how actually fetching the data from the API using token along with the header.

- ![image](https://user-images.githubusercontent.com/22726452/141928304-20942a40-8cc7-4ced-a90b-40bf8ff5314a.png)

- But, we need the whole URL auto-populated in the sequence manner so, we would be able to fetch the data through google chrome or other browsers as well.

### Describe the solution you'd like

# Expected result
-  HTTPS + token + header

**Comment by DannyDainton** [comment]
Hey @nitish166 

It's not clear what you're asking for here - Could you please add more context and information to the feature request?

Closing this issue, we can look at reopening it once the required information has been provided.
