### ISSUE TITLE
Code Generation Error: Unable to generate server boilerplate. Try again later.

### ISSUE THREAD

**Issue by konnor-willison-deepsee** [a85/POSTMan-Chrome-Extension#10444]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

From any api I try to generate code from in postman, I get the error: Unable to generate server boilerplate. Try again later.

I don't see any issues with the schema, no issues with permissions, I can generate other things from this api just fine, but the code generation in Java errors out. This happens with any API in our workspace.

### Steps To Reproduce

1. Open API tab
2. Select an API
3. Select a version of the selected API
4. Select code generation
5. Select Java - JAX-RS
6. Select generate code
7. See error

### Environment Information

```markdown
- Operating System: macOS Monterey Version 12.0.1
- Platform Type: Native APP
- Postman Version: 9.1.3
```

**Comment by abhijitkane** [comment]
@konnor-willison-deepsee Can you send the redacted OpenAPI definition, and the version ID to help@postman.com? That'll help us isolate and fix this issue faster. The version ID can be found on the right sidebar:

<img width="1369" alt="Screenshot 2021-11-29 at 10 53 19 AM" src="https://user-images.githubusercontent.com/681190/143925953-688809f4-325e-40cd-9d49-25107e46bf6e.png">.

**Comment by konnor-willison-deepsee** [comment]
I just attempted this again and it's generating the code now. I'm on postman v 9.1.5 now which might be why it is now working? @abhijitkane do you still want that information?

**Comment by abhijitkane** [comment]
@konnor-willison-deepsee Yep - it should be helpful. It was probably a temporary issue of some kind, but I'd like to be sure. Glad to hear the code generation flow is working now, though.

**Comment by umeshp7** [comment]
Closing this, as not reproducible anymore.

@konnor-willison-deepsee do reach out to us if you face this issue again :). Thank you!
