### ISSUE TITLE
JSON Post request changing content length to 0 upon redirect

### ISSUE THREAD

**Issue by UA55** [a85/POSTMan-Chrome-Extension#10440]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

I have a JSON Post request that is redirected to another endpoint. The request body is correct JSON format and is not null. 
After redirect Content Length is changed to 0 and I get a 400 Invalid JSON response.

FYI : My request type is not changing to GET. The redirect call is still a Post request
I have all the settings turned on for the redirect call. 

Issue is that my request body is not passed on the redirect call.

### Steps To Reproduce

I have a JSON Post request that is redirected to another endpoint. The request body is correct JSON format and is not null. 
After redirect Content Length is changed to 0 and I get a 400 Invalid JSON response.

FYI : My request type is not changing to GET. The redirect call is still a Post request
I have all the settings turned on for the redirect call. 

Issue is that my request body is not passed on the redirect call.

### Environment Information

```markdown
- Operating System: Windows 10
- Platform Type: Postman desktop app
- Postman Version: v9.1.3
```

**Comment by malvikach** [comment]
@UA55 thanks for writing to us. I wanted to understand your issue a bit better. Please help me with more information and possibly an example (screenshot/video or request json that I can import).  

Are you calling the redirect request from within the postman's test script section? Also, where does the content length starts to show 0, is it on the postman app or someplace else? 

You could also open your Console from Postman's app (open view-> show postman console) and check the logs on what's happening to provide us more details.

**Comment by UA55** [comment]
I have an API endpoint (endpoint A) that is redirecting to a second API endpoint (endpoint B) What I want to achieve is to send the request body from my API call to endpoint A and that be redirected to API (B). 

When I call Endpoint B directly with the same request body it works fine. But I want to test the redirection works so I have to find a way to send the request body to endpoint A and make sure it passes the same request to endpoint on redirect call to endpoint B.
my content type is application/JSON
I am viewing the call on postman console and following are the results:
Endpoint A: 
Response code: 302 Found
content length 138 
Endpoint B:
Response code: 400 Invalid JSON
Content length: 0

Request Body:
[
{
“Param1”: “abc”,
“Param2”:[
{
“Xyz”:”1.0”,
“Abc”:”test”,
“Cde”:0,
“Def”:”01/01/2000 01:01:00”
}
]
}
]
I have the following settings on:
F

**Comment by malvikach** [comment]
@UA55 thanks for the details. 

I would request you to check the settings for 'automatically follow redirects'. You can find this under 'Settings' -> General (Headers) -> 'Automatically follow redirects' 
This setting should be turned on. 

Please let me know if this setting is already ON. If not, I would request you to turn this ON and test your requests again. 

Let me know if this helps.

**Comment by UA55** [comment]
I have that setting turned on both the postman level and request settings level

**Comment by malvikach** [comment]
@UA55 thanks for all the information. 

This might be a bug, we will look into this further and get back to you.

**Comment by UA55** [comment]
Thanks so much

**Comment by codenirvana** [comment]
@UA55 we've pushed a fix for this in the latest version of the Postman app (v9.9.0). Can you update your app and confirm if that fixes your issue?
