### ISSUE TITLE
Duplicating collection item will use incorrect dupe info on v9.1.5

### ISSUE THREAD

**Issue by dh-pt** [a85/POSTMan-Chrome-Extension#10454]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

![image](https://user-images.githubusercontent.com/74234607/142721071-60dc8268-8a0f-426f-b14b-cc64bc4e4e99.png)

Every time I duplicate a collection element, the name is correct but anything inside is wrong, showing a 3rd-party element instead. See attached screencast.

I tried closing and opening back up the app. This didn't used to do it - I only updated today after updating again not that long ago (not sure how long ago exactly, but I updated when it asked - assuming "last release version" before v9.1.5).

### Steps To Reproduce

1. Duplicate item
2. See correct title, but incorrect inner info

### Screenshots or Videos

![WA0OK35mnp](https://user-images.githubusercontent.com/74234607/142721177-11c52f08-83da-43cc-93f3-a66cd385da30.gif)

### Environment Information

```markdown
- Operating System: Win11 stable
- Platform Type: 64 bit
- Postman Version: v9.1.5
![image](https://user-images.githubusercontent.com/74234607/142721202-b477f4d4-197f-4aed-9aeb-7e3c81fd7fe7.png)
```

**Comment by dh-pt** [comment]
To add: Copy+Paste (CTRL+C, CTRL+V) _also_ reproduces this bug - not just dupe.

**Comment by DannyDainton** [comment]
It's not visible from the gif but could you also show the tabs, please?

If you have unsaved changes, it's going to duplicate the saved collection with those changes.

**Comment by DannyDainton** [comment]
Hey @dh-pt 

Closing this issue as it's unclear what is happening here from the information provided. Happy to reopen if more contextual information is shared. A recording showing the whole app would also be helpful to see the issue.
