### ISSUE TITLE
Unable to access app when second monitor is removed

### ISSUE THREAD

**Issue by cleytoncoro** [a85/POSTMan-Chrome-Extension#10455]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

Postman saves its last window position to reopen in that position later.

But if my last window position was my second monitor, and I remove this monitor, next time I open Postman, the window opens in last position, and my mouse can't move it back to my first screen.

**Workaround to solve this problem (tested in windows 10):**
1. Change your monitor resolution. Window will be back to your primary screen.
2. Restore your monitor resolution.

### Steps To Reproduce

1. connect a second monitor;
2. open Postman and drag it to the second monitor;
3. close postman;
4. remove second monitor;
5. reopen postman;

### Environment Information

```markdown
- Operating System: windows 10
- Platform Type: native app
- Postman Version: 8.12.1
```

**Comment by jviotti** [comment]
Merging this with https://github.com/postmanlabs/postman-app-support/issues/2833
