### ISSUE TITLE
CAN'T MAKE POST REQUEST

### ISSUE THREAD

**Issue by parima001rs** [a85/POSTMan-Chrome-Extension#10456]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

When I make a post request, it's loading and loading and not showing any result.
I'm using version 9.1.5.

I tried using Postman build online using Postman Agent. It's not working.

### Steps To Reproduce

1. Open Postman application
2. Make a post request

### Screenshots or Videos

![Screenshot (103)](https://user-images.githubusercontent.com/65702724/142754814-1a53870e-67e9-4fab-b57f-6c92380fd10c.png)
)

### Environment Information

```markdown
- Operating System: Windows 11
- Platform Type: Native App and Postman Web
- Postman Version: 9.1.5
```

**Comment by DannyDainton** [comment]
Hey @parima001rs

Are you able to make a POST request to `https://postman-echo.com/post`
