### ISSUE TITLE
Cannot sign in with google account (Packaged App)

### ISSUE THREAD

**Issue by peter-steiner-accedo** [a85/POSTMan-Chrome-Extension#1045]
Its not possible to sign in with google account in the Packaged App.
Error message mentions connectivity, however my machine have internet access. 

![postman_google_sing_in](https://cloud.githubusercontent.com/assets/1508533/7474724/71771ea4-f343-11e4-9ba8-6ed8a7c59f0c.png)

![screenshot 2015-05-05 16 19 37](https://cloud.githubusercontent.com/assets/1508533/7474583/97ece862-f342-11e4-95e5-4bf31669be31.png)

**Comment by abhijitkane** [comment]
The issue has been resolved. Can you check?
