### ISSUE TITLE
Annoying updates, no way to disable fully

### ISSUE THREAD

**Issue by sryze** [a85/POSTMan-Chrome-Extension#10451]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

Postman downloads a new update every week or so. 

My internet connection is not great, and I don't want to let Postman download updates, unless I approve it. But it's not possible to disable updates completely in Settings or to make the app ask before updating. 

### Steps To Reproduce

1. Open Postman
2. Wait a few days
3. Open Postman again

### Environment Information

```markdown
- Operating System: All
- Platform Type: All
- Postman Version: All
```

**Comment by jviotti** [comment]
Closing as a duplicate of https://github.com/postmanlabs/postman-app-support/issues/6999
