### ISSUE TITLE
Postman has a terrible UI: discuss

### ISSUE THREAD

**Issue by ghost** [a85/POSTMan-Chrome-Extension#10459]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request

### Is your feature request related to a problem?

This isn't really a feature request, but it's not really a bug either.

When Postman "did less stuff", it was much easier to navigate and understand. But it's now not just an API-driving tool, it does a whole load of other things (albeit with varying degrees of success IMO). However, instead of the UI being redesigned to introduce these new features intuitively, it feels like things are just added wherever there's space on the screen - a dropdown here; a scrolled area within an area within an area there; a vertical list of cryptic icons; a billion different ellipses and context menus. It's not intuitive in the slightest.

In some cases, the choice to add yet another ellipsis seems to be utterly obtuse - for example, select a node within a collection and you get a horizontal bar showing the path, with Run and Save links at the far right of it, then an ellipsis. And in the ellipsis menu is...one entry, Delete. Who creates a drop-down menu with one option in it?

It feels like the UI aspect hasn't been separated from the software engineering part. A dev adds a new feature and then finds somewhere on the screen to bung a link or an icon or another ellipsis menu. Sometimes I don't want to close Postman in case the ellipses are breeding in the dark and another five will appear next time I launch it.

We use a lot of dev tools and the two which have the worst interfaces are Postman and Jira. And I don't think anyone wants to be classified in the same bracket as Jira.

I guess I'm asking two questions:

1.  Does anyone else struggle to navigate around Postman?
2. Is there any plan to look at improving the UI and specifically, making it a bit more intuitive?

### Describe the solution you'd like

A decent UI!

### Describe alternatives you've considered

This lot: https://www.g2.com/products/postman/competitors/alternatives

**Comment by ghost** [comment]
Just to add: for the first time, I had conflicts on a merge for a fork and I just sat and cry-laughed because that interface is literally IMPOSSIBLE to use on a collection with more than 2 or 3 endpoints. I mean, really, it's just chaos. It's asking me to choose between two different versions of a collection endpoint and it appears to be showing me raw json from the internal implementation of the calls.

**Comment by ghost** [comment]
Merging forks is so bad (lack of feedback, no busy icon, random errors) that we are currently looking at alternatives.

**Comment by armin-em** [comment]
I absolutely struggle to navigate through Postman's UI. odd element positioning and terrible grouping.

**Comment by mithereal** [comment]
i second the worst ui ever, if you happen to change 1 char anywhere on the ui it syncs up ohnline and you lose ctr-z it is INSANE, trying to collab with ppl in the same company, settings get overwritten every 5 mins,  sooo much technical debit, thanks, this has now become the worst tool in the developer space for its intended failed purpose.

**Comment by StanleySathler** [comment]
One thing that bothers me a lot is when you run tests for an entire collection, HTTP methods are colored. `DELETE` is red, which often makes me think the test failed.

![image](https://user-images.githubusercontent.com/11931916/181340363-c729f8da-4866-4860-b133-183d899cddf9.png)

**Comment by Vovour** [comment]
Why was this issue closed? Has anything changed? For example, the "issue" with the Run, the Save and the ellipsis button opening a drop down menu with only one entry still exists in version 9.31.19.

And I could collect other strange things that are more paint full for me... For example, why can be line wrapping disabled in the response body panel but not in the request panel? Why does the response panel have the button for quick search in body and the request panel not? Why is the most important button – the Test Results button with the number of succeeded/failed tests – hidden in a drop down menu once the response panel is not width enough but the Save Response button is still there despite it's very rarely used?

**Comment by depeter** [comment]
If ever there was a reason not to use postman for me it's because of this. The frustration this tool is generating is never seen before for me. Do something about this please.

Improvement suggestions:
When an element is disabled, indicate that it is!
Create a clear difference between an input field, a button and a label!

I mean, this shouldn't be said, this should be obvious.

**Comment by nextep** [comment]
It's 2023 and i can't right click to paste in a variable field.

**Comment by sprive** [comment]
> Why was this issue closed? Has anything changed? 

No. But Postman devs routinely close issues in order to keep the metrics looking spiffy for their investors. They are judged on it.

The only reason to use Postman is if it is the only source of documentation/examples, and if there's too much inertia to do things right. Otherwise, Just use Python + Requests module.

**Comment by sljinlet** [comment]
Way +1 from me. I find the Postman UI to be one of the most confusing things I've ever had to work with, and I've been doing this for a long time.

**Comment by sprive** [comment]
For those who have the ability to choose their development tools - 
I've found **[Restfox](https://github.com/flawiddsouza/Restfox/releases)** to be a breath of fresh air. RestFox is exactly what Postman USED to be (before Postman embarked on a campaign of enchittification).

**Comment by zhengjun-li** [comment]
Yes I agree, the flow and UX in Postman is really wack. It feels irritating and difficult to use. To do what you want, you have to be aware of so many gotchas and weird user flows. For an example, why can't I search for text in the Variables list on the right? Why is everything collected into tabs and weird menus that are disconnected?
