### ISSUE TITLE
Want to change the installation path during the installation process

### ISSUE THREAD

**Issue by hlmd** [a85/POSTMan-Chrome-Extension#10458]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request

### Is your feature request related to a problem?

Want to change the installation path during the installation process.
Because we are using a Windows computer, the system disk may not have enough memory, or classify applications like obsessive-compulsive disorder.

### Describe the solution you'd like

The installation path can be selected on Windows during installation

**Comment by jviotti** [comment]
Closing as a duplicate of https://github.com/postmanlabs/postman-app-support/issues/3897
