### ISSUE TITLE
Import Collection does not work

### ISSUE THREAD

**Issue by nkev** [a85/POSTMan-Chrome-Extension#10450]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

![image](https://user-images.githubusercontent.com/5410916/142562392-a04c209b-6a62-48d5-84ad-00388c2f9e5f.png)

### Steps To Reproduce

1. "Download All" from one mac into a text file.
2. Copy that text file to another mac
3. drag the text file to "Import From Disk" dialog
4. "The Collection has been imported" message appears but nothing gets imported.

### Environment Information

```markdown
- Operating System: Monterey 
- Platform Type: Mac OS 
- Postman Version: Cannot find it in Chrome extension!
```

**Comment by DannyDainton** [comment]
Hey @nkev 

This is a very old version of Postman - Have you tried the same action on the latest version?

You can either download the native app for your OS from here: https://www.postman.com/downloads/ or use the Web version of the platform: https://go.postman.co

**Comment by postman-staff** [comment]
@nkev Do let us know if @DannyDainton latest comment was able to get everything sorted for you. The latest release should get you unblocked and have access to Postman again

via @asi-postman | Postman Support

**Comment by nkev** [comment]
It's ok, I used another open source product.
