### ISSUE TITLE
WYSIWYG/Markdown editor strips HTML comments

### ISSUE THREAD

**Issue by jeffski** [a85/POSTMan-Chrome-Extension#10463]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

The new WYSIWG editor strips HTML comments from the documentation description.

We added custom metadata inside HTML comments in our descriptions when Markdown was the only available editor. This was used by another application that imported the Postman Collection.

The previous version we used allowed the HTML style comments. Now with the new WYSIWYG version they are all gone and can no longer be added. When you switch to the Markdown editor and add an HTML comment, save, exit and return to the editor the comments are removed.

Not happy as it took days to set up all the metadata, now it is gone and our application can no longer work.

Using version 9.2.0

### Steps To Reproduce

1. From any request, open the Documentation panel and click the pencil icon to edit.
2. Select `Classic Markdown editor`
3. Type an HTML comment like: `<!-- hello -->`
4. Click save
5. Click on the pencil edit icon again
6. Select `Classic Markdown editor`
7. HTML comment has disappeared

### Screenshots or Videos

![Annotation 2021-11-25 130834](https://user-images.githubusercontent.com/1064199/143365419-bf8f0a0d-5df3-4c1d-991b-afa17c9d9d1e.png)

Try saving this, comments are stripped. Previously we were able to embed JSON metadata in here used by another application. Now all our metadata has gone for 100's of endpoints.

### Environment Information

```markdown
- Operating System: Windows 10
- Platform Type: Desktop
- Postman Version: 9.2.0
```

**Comment by jeffski** [comment]
It seems that the comments are being saved - if I export the collection then the comments are there.

The editor must not be rendering/displaying them however when I return to the editor. So, when you click save the description is saved without the comments.

It appears the main issue is that the comments are not being displayed when loaded, they are actually in the data store.

**Comment by Raja-Simha** [comment]
@jeffski thanks for bringing this to our notice. The new Postman editor does not have complete support for html tags as shown by the warning message 

![image](https://user-images.githubusercontent.com/45988836/143396399-694442d5-277c-445c-a152-686ad6d429cc.png)

and explained in our [onboarding guide](https://cooper.postman-beta.co/workspace/Documentation-x-WYSIWYG~fa134431-cc73-467b-8cf8-685abdfe6ef1/documentation/86379-cd2abd80-a8ab-4e9c-91fc-073ebadacf59).

However, we are looking into your problem with HTML comments and will get back to you with more details. Until then I suggest you use the 'Classic Markdown editor' to avoid any data loss.

**Comment by jeffski** [comment]
Hi, thanks for the quick response. In my screenshot above you can see I am using the `Classic Markdown editor`. That seems to be where the issue is. When I return to the markdown editor after saving the HTML comment then it has disappeared.

**Comment by iquabius** [comment]
When I click the pencil icon to edit a block it *opens the WYSIWYG editor by default.*

**How can I disable it?**

I'm having trouble keeping an embeded "Run in Postman" button in the documentation.

I copy & paste the "Markdown friendly" code into a documentation block and save it:

```md
[![Run in Postman](https://run.pstmn.io/button.svg)](https://app.getpostman.com/run-collection/6675956-7b745858-b4ec-4313-891c-52785ae4e7dd?action=collection%2Ffork&collection-url=entityId%3D6675956-7b745858-b4ec-4313-891c-52785ae4e7dd%26entityType%3Dcollection)
```

But when I go back to edit that block the beta editor messes it up and it transforms into this:

```md
[](https://app.getpostman.com/run-collection/6675956-7b745858-b4ec-4313-891c-52785ae4e7dd?action=collection/fork&collection-url=entityId=6675956-7b745858-b4ec-4313-891c-52785ae4e7dd&entityType=collection)

[![](https://run.pstmn.io/button.svg)](https://app.getpostman.com/run-collection/6675956-7b745858-b4ec-4313-891c-52785ae4e7dd?action=collection/fork&collection-url=entityId=6675956-7b745858-b4ec-4313-891c-52785ae4e7dd&entityType=collection)
```

Then into this on the next edit:

```md
[](https://app.getpostman.com/run-collection/6675956-7b745858-b4ec-4313-891c-52785ae4e7dd?action=collection/fork&collection-url=entityId=6675956-7b745858-b4ec-4313-891c-52785ae4e7dd&entityType=collection)

[](https://app.getpostman.com/run-collection/6675956-7b745858-b4ec-4313-891c-52785ae4e7dd?action=collection/fork&collection-url=entityId=6675956-7b745858-b4ec-4313-891c-52785ae4e7dd&entityType=collection)

[![](https://run.pstmn.io/button.svg)](https://app.getpostman.com/run-collection/6675956-7b745858-b4ec-4313-891c-52785ae4e7dd?action=collection/fork&collection-url=entityId=6675956-7b745858-b4ec-4313-891c-52785ae4e7dd&entityType=collection)
```

And so on, **indefinitely**...

I have to keep an eye on it everytime I edit that block.

**Comment by kamaraj-p** [comment]
@jeffski The issue has been fixed. Closing the issue. 

@iquabius we are working on a default editor option in settings. Thanks for your patience.
