### ISSUE TITLE
Issue Using Env Vars Inside Another Env Vars in Postman

### ISSUE THREAD

**Issue by PFaz540** [a85/POSTMan-Chrome-Extension#10464]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

If I'm using an env variable inside another env variable, Postman doesn't always see the inherited env var.
You can see this via console.log

![image](https://user-images.githubusercontent.com/44571878/143567170-7f833c43-be02-4a47-a911-fbf5d9565825.png)

`console.log(pm.environment.get("uk_domain"))`
`//https://dev.{{ticket}}.gear4music.com`

Rather than:
`//https://dev.PMN-123.gear4music.com`

My use case is that we can't delete cookies from our domains in a pre-request script since our domains env vars are inheriting one common env var.

### Steps To Reproduce

1. create an env variable `name: paul`
2. create a second env variable `message: Hello {{name}}`
3. Make a request to anywhere but have `console.log(pm.environment.get("message"))`
4. Notice `message: Hello {{name}}` is returned in the console rather than `message: Hello Paul`

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/44571878/143582744-a661db7e-b239-4dfc-b9f4-834e190b6d10.png)

![image](https://user-images.githubusercontent.com/44571878/143582688-c648818c-d63c-40bc-bad2-595f372e4555.png)

### Environment Information

```markdown
- Operating System: Mac Big Surr 11.6
- Platform Type: Native App
- Postman Version: 9.2.0
```

### Additional Context?

At my current place of work, a website environment is created for testing JIRA tickets.
Let's say it's this: https://dev.PMN-123.gear4music.com
Were PMN-123 is the JIRA ticket number.
In Postman, I have all my web domains in environment variables
To make things easier, I have the ticket number in its own variable and that value is inherited into the domain variables.

![image](https://user-images.githubusercontent.com/44571878/143567170-7f833c43-be02-4a47-a911-fbf5d9565825.png)

Postman doesn't seem to handle env vars within env in certain scenarios

In my test script, if I were execute:
`console.log(pm.environment.get("uk_domain"))`

it would literally output the below in the console, without including the actual value of our 'ticket' env var:
`//https://dev.{{ticket}}.gear4music.com`

This starts to become a problem if I want to remove cookies from those domains as in a script.
It will literally see the uk_domain as `https://dev.{{ticket}}.gear4music.com` rather than `https://dev.PMN-123.gear4music.com`

..Hopefully I've explained that well enough

**Comment by DannyDainton** [comment]
Hey @PFaz540 

As that's just the `string` value saved in the value field, you would need to wrap it in `.replaceIn()` to resolve the variables

```javascript
console.log(pm.variables.replaceIn(pm.environment.get('message')));
```

An example with your URL syntax:

![image](https://user-images.githubusercontent.com/17089546/143587977-d5c25696-3104-40ee-b97d-989ea035c11d.png)

**Comment by PFaz540** [comment]
Awesome. That deals with my problem 👍🏻 
Cheers @DannyDainton 
This ticket can be closed now

**Comment by giridharvc7** [comment]
@PFaz540 An alternate approach would be to store `ticket` in a Global Variable or Collection variable (outside your current environment), in case you cannot use pre-request script.
