### ISSUE TITLE
installing themes in macOS

### ISSUE THREAD

**Issue by ahmetcetin** [a85/POSTMan-Chrome-Extension#10465]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

I've purchased Contempt themes, in email and in the readme in the package, it says:

```
To import a theme:

* In Postbox navigate to Preferences | Options > Display > Themes
* Click the Import button
* Navigate to the desired .json theme file
```

Problem is, there is no Import button in preferences in Mac. Can you suggest how can I import the themes in Mac?

### Steps To Reproduce

open preferences in Mac version

### Screenshots or Videos

![CleanShot 2021-11-26 at 18 09 29](https://user-images.githubusercontent.com/5046786/143614367-5b9fc593-9530-4290-8033-852563af1aac.png)

### Environment Information

```markdown
- Operating System: macOS Monterey 
- Platform Type: m1
- Postman Version: 9.2.0
```

**Comment by DannyDainton** [comment]
Hey @ahmetcetin 

Are you sure it means Postman? In the instruction steps, it mentions `Postbox`.

Are you sure it's not this https://www.postbox-inc.com/

**Comment by DannyDainton** [comment]
@ahmetcetin I'm going to close this issue as I don't think it's Postman that you were looking for here. 

If that's not the case we can reopen the issue and take it forward if you're able to provide some more information.
