### ISSUE TITLE
Pretty JSON slow down the whole app

### ISSUE THREAD

**Issue by tonyluj** [a85/POSTMan-Chrome-Extension#1046]
It's ok to pretty small json response. But it will slow down the whole POSTMan app when json response is larger than 100KB.

Chrome Version 42.0.2311.90 (64-bit) / Archlinux

**Comment by abhijitkane** [comment]
What version of Postman are you using?

**Comment by tonyluj** [comment]
I am using:
Version 2.0.25 (packaged)
OS: linux
Architecture: x86-64
Native client architecture: x86-64

**Comment by a85** [comment]
This should not be happening on the latest version of the app since we moved to Ace Editor for JSON rendering.
