### ISSUE TITLE
New Integration Request - Salesforce

### ISSUE THREAD

**Issue by Esrarahman** [a85/POSTMan-Chrome-Extension#10467]
### Describe your current workflow

Salesforce 

### Describe your ideal workflow

Goal:  To be able to provide secure access of Salesforce data to another system.

Data to access:  Lets use the Contact object (Last Name field only to ensure we aren’t exposing any private information).

So, lets do it this way:  Your endpoint should take in a single character ‘A’ for example, and should return all last names that start with ‘A’

### Describe alternatives you've considered

nothing at the moment 

### Additional context

please document the steps involved in setting up your endpoint as well as any limitations/considerations that you identify.

We will also need to know what are our quotas in terms of data transfer per month.

How does Salesforce enforce security (credentials, tokens etc.)

**Comment by shashankawasthi88** [comment]
@Esrarahman Postman Integrations are meant to solve workflows where Postman interacts with other software for API development and maintenance. The problem statement is out of that context. I'll go ahead and close this, feel free to reopen if you feel otherwise, giving more context.
