### ISSUE TITLE
Cannot save documentation on collections or requests

### ISSUE THREAD

**Issue by dschemp** [a85/POSTMan-Chrome-Extension#10477]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

Postman does not save documentation in the documenation tab on requests or collections. When pressing `Save` nothing happens; `Cancel` works as intended, reverting to the old state of the written documentation.

### Steps To Reproduce

1. Create a new collection or request
2. Click on "Documentation" on the right side
3. Edit the documentation
4. Try clicking "Save"

### Environment Information

```markdown
- Operating System: Windows 10
- Platform Type: Native App
- Postman Version: 9.3.1
```

### Additional Context?

I have tried reinstalling Postman clearing all data. This started happening with the latest update as far as I know; it worked before.
EDIT: I have reinstalled Postman 9.2.0 and it seems to work again.

**Comment by fysidm** [comment]
Same here.

Just updated to 9.3.1, and clicked Save button when editing documentation, but nothing happened...

**Comment by Raj-postman** [comment]
@dschemp @fysidm Just tried to replicate this from my end but wasn't able to get the error. [Screen-record for reference here.](https://www.loom.com/share/ed230e6b41d3423ba639e6739bdea2c2).

Can you check the recording and let us know if there is any step we are missing that leads to this issue?

**Comment by dschemp** [comment]
@Raj-postman As far as I could see you did everything right. I have [recorded the issue](https://ttm.sh/eoY.mp4) aswell to show you how it looks

**Comment by Raj-postman** [comment]
Thank you for the recording @dschemp - it looks like the issue exists on ScratchPad. We will be looking into this further and updating this thread soon.

**Comment by robatwabbi** [comment]
I there a status on the investigation into this issue?

**Comment by Raj-postman** [comment]
@robatwabbi Apologies but this hasn't been fixed yet. Our team will update this thread once resolved. Appreciate your patience.

**Comment by robatwabbi** [comment]
Thank you for the status
________________________________

**Comment by kamaraj-p** [comment]
The issue is resolved. The fix will be available with the next update v9.9.2. Thanks for your patience.

**Comment by Gibbo3771** [comment]
On version 9.15.5 here. My requests don't even save fully, the **Tests**/**Params** tabs just have an indefinite orange dot. Is this related?

**Comment by kamaraj-p** [comment]
Hi @Gibbo3771, thanks for reaching out. I don't think this is related but just to confirm can you please attach a screenshot of the issue.

**Comment by AxelGuignard** [comment]
Hi, I have the same issue in v10.0.32. I'm working on the desktop app in a team workspace, and when either I or a coworker change the index.json and save, it doesn't update the documentation page for anyone.

**Comment by akshaydeo** [comment]
@AxelGuignard I am not able to reproduce this issue at my end.

Here are the steps I followed:
1. Import an Open API 3.0 schema file.
2. Updated an endpoint (path) in the schema file.
3. Click on Definition to see if the changes are reflected. And they were reflected.
 
<img width="569" alt="image" src="https://user-images.githubusercontent.com/1050029/196916068-0516295e-7e44-407f-90a6-90788ca78f21.png">


Just to be sure, I have a few questions.

1. When you say `index.json`, which schema type are you referring to? Currently, we support schema documentation for Open API 3.0.
2. When you say the documentation page is not updated, are you referring to schema documentation (the one you see after clicking on Definition) or the collection documentation (the one you see in the context bar for a collection)?

**Comment by AxelGuignard** [comment]
@akshaydeo
We use the Open API 3.0 schema, and I am talking about the schema documentation.

I don't know if it is relevant but I don't see the "ROOT" label next to index.json

Also when I update the schema, I sometimes see this message pop in the Definition:
![image](https://user-images.githubusercontent.com/28559138/196919030-7665afc6-5e14-4ad5-a049-2383e490fd2b.png)
Even after I clicked the save button.
When I close and reopen the tab, the message disappears.

**Comment by AxelGuignard** [comment]
For info, we just managed to solve the issue by copying the schema documentation into a newly created API.
The "ROOT" label now appears next to the new index.json.
We figured the issue might originate from the migration between V.9 and V.10 of Postman, but it is only a supposition.
We lost a lot of time trying to make things work, so I hope our solution will help someone.
