### ISSUE TITLE
Disable update prompt at startup

### ISSUE THREAD

**Issue by kannankeril-watchguard** [a85/POSTMan-Chrome-Extension#10473]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request

### Is your feature request related to a problem?

I get prompted at startup to update. I see no option to disable this. 

### Describe the solution you'd like

I would just like to use Postman without being nagged into installing every minor update. Please provide an option to disable this in Settings.

### Describe alternatives you've considered

Not using Postman.

**Comment by jviotti** [comment]
Hey @kannankeril-watchguard ,

The normal variant of the Postman desktop application auto-updates by default and there is no way to disable such functionality. However, we do support an Enterprise variant of the Postman application (https://learning.postman.com/docs/administration/managing-enterprise-deployment/) that provides a higher-level of control. The Postman Enterprise app is available for Windows and will be available for macOS very soon.
