### ISSUE TITLE
Postman desktop app doesn't update the response in Pretty tab

### ISSUE THREAD

**Issue by sud8079** [a85/POSTMan-Chrome-Extension#10472]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

Postman desktop app doesn't update the response in Pretty tab. No matter how many times you click.
In raw tab it works fine.

### Steps To Reproduce

1. fire 1 get request in postman and in response select the Pretty tab.
2. fire next request response is not updated. 

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/88364361/144219333-4ba63e7a-0078-4e16-b0c1-1e6326628d72.png)

### Environment Information

```markdown
- Operating System: Windows 10
- Platform Type: Native App
- Postman Version: 9.2.0
```

### Additional Context?

none

**Comment by sud8079** [comment]
This is very old issue and I have seen multiple forums people facing this issue. Please fix this.
Thanks!!

**Comment by DannyDainton** [comment]
Hey @sud8079 

From the image, I can see that the response looks like just plain text and not really something that could be prettified (JSON/XML)

Have you tried a different endpoint or maybe using `https://httpbin.org/anything` to see how the response should be displayed in that section?

**Comment by sud8079** [comment]
Hi,

Yes this is only a plain response but still it should update the content. I
tried also with the *http://httpbin.org/anything
<http://httpbin.org/anything>* url and observed the behavior is same.
There is some random char in the response's headers section that doesn't
change in the Pretty tab. If you switch to another tab it works fine.

This in response: "X-Amzn-Trace-Id":
"Root=1-61a7541f-269d89bd4f99abf937749cce",


Regards
=========
Sudarshan

**Comment by DannyDainton** [comment]
> Yes this is only a plain response but still it should update the content

I'm not sure what you mean, what should the plain text response be updated too?

> There is some random char in the response's headers section that doesn't
change in the Pretty tab

I'm also not sure what you mean by these either. 

Can you please provide a short recording of the behaviour that you're seeing, it's a little difficult to know what's happening in the UI on your side, without some visual examples.

**Comment by DannyDainton** [comment]
@sud8079 Is this still an issue for you?

**Comment by DannyDainton** [comment]
Hey @sud8079  👋🏻

I'm going to close this issue due to inactivity - If you're still facing the issue in the latest version we can reopen this and investigate further.
