### ISSUE TITLE
Rest API call in Postman gets internal server error but not that rest api works correct in browser 

### ISSUE THREAD

**Issue by nikhilpatiltest** [a85/POSTMan-Chrome-Extension#10475]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

{
    "timestamp": "2021-12-02T09:34:59.824+00:00",
    "status": 500,
    "error": "Internal Server Error",
    "exception": "java.lang.ClassCastException",
    "message": "org.springframework.security.web.authentication.WebAuthenticationDetails cannot be cast to java.util.Map",
    "path": "/Demo"
}

### Steps To Reproduce

Rest API call

### Environment Information

```markdown
- Operating System: 
- Platform Type: 
- Postman Version: 
Windows 11 
Postman for Windows
Version 9.3.0
win32 10.0.22000 / x64
```

### Additional Context?

Thanks in Advance ..!
any leads would be appreciated

**Comment by DannyDainton** [comment]
Hey @emmadavis16 

This looks like a response coming from your API's endpoint, this isn't something that Postman is returning. 

I'm not sure there is going to be a lot that we can do here.

**Comment by nikhilpatiltest** [comment]
Ok sure thanks for the reply..!

**Comment by oluwatrillions** [comment]
I am having the same issue. API request from client side works fine, but Postman returns error 500
