### ISSUE TITLE
When duplicating request, open duplicate not original

### ISSUE THREAD

**Issue by carlmaritz** [a85/POSTMan-Chrome-Extension#10470]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request

### Is your feature request related to a problem?

When duplicating a request, a tab opens for the original request. This often causes one to edit the request thinking it's the new file resulting in lost information.

### Describe the solution you'd like

When duplicating a request, simply open a tab for the new request and not the original.

**Comment by DannyDainton** [comment]
Hey @carlmaritz 

Duplicating the request is done via the requests context menu, on the sidebar. This makes a copy of the request. 

![image](https://user-images.githubusercontent.com/17089546/144100157-30b51b77-7fba-43fc-9561-88d6d6b9a430.png)

Right-clicking the tab and selecting `Duplicate Tab` doesn't create a _copy_ of the request. 

> Duplicating a tab does not mean creating a second request to the same endpoint—when you duplicate a tab any edits you make will affect the original request.

https://learning.postman.com/docs/getting-started/navigating-postman/#tabs

**Comment by carlmaritz** [comment]
Hey @DannyDainton, this is true but my issue is with the next part as the request which you duplicate opens in a new tab instead of the newly created copy. As I have some more time I can detail this below:

First step: Duplicate a request.
![Initial Action: Duplicate a Request](https://user-images.githubusercontent.com/78422028/144111092-2002bfc2-e1a1-46b9-80f0-612804335b2f.png)

Current outcome: A tab is opened containing the request which is duplicated.
![Actual Outcome: A tab opens up with original request.](https://user-images.githubusercontent.com/78422028/144111090-0cf72255-d27c-4229-a183-9364f86fdf9a.png)

Desired outcome: A tab is opened that contains the duplicate request. Possibly with the focus set to the name field for easy renaming.
![Desired Outcome: A tab opens up with the duplicate request.](https://user-images.githubusercontent.com/78422028/144111087-e8f19466-a924-4a83-8537-a0934b25f982.png)

In my opinion this would improve productivity as one would often want to interact with a newly created duplicated request instead of the original.

**Comment by DannyDainton** [comment]
Hey @carlmaritz 

The images and the flow you described made me understand the issue more - I wrongly assumed it was and duplicate tab vs a duplicate request.

I think this is more of a bug than a feature request, if you were to do the same duplicate action for the Collection, an environment or an example these would open the copy version of the entity and not the original.

The originals seem to open for the folders and the requests when duplicating, it doesn't feel consistent with the rest of the platform.
