### ISSUE TITLE
Import: Missing example data when importing OpenAPI 3.03

### ISSUE THREAD

**Issue by AJ-BM** [a85/POSTMan-Chrome-Extension#10474]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

We have an auto generated schema generated directly from our codebase using Django Rest Framework with the DRF Spectacular library. When we import it to postman the request bodies dont have the example values in them. Would be nice if they would be populated with the example data of the first example in the examples list

There is a closed issue that looks similar here: https://github.com/postmanlabs/postman-app-support/issues/7477

### Steps To Reproduce

1) Generate a OpenAPI 3.0.3 schema with examples in it
2) Import it to postman
3) See that there are no example values in the request bodies

### Screenshots or Videos

Screenshot of endpoint, how it looks in Postman after importing:
![image](https://user-images.githubusercontent.com/78352730/144396618-d8c1d517-d4eb-4af7-af4c-1523542565b7.png)

What i would be expecting: 

![image](https://user-images.githubusercontent.com/78352730/144397560-58143f7b-5099-4be1-a578-9d48866b3726.png)

### Environment Information

```markdown
- Operating System: Ubuntu 21.04
- Platform Type: Native App
- Postman Version: 
Postman for Linux
Version 7.36.5
linux 5.11.0-40-generic / x64
```

### Additional Context?

Here i have included a full copy of the endpoint from our generated raw schema (anonymized). When used with Swagger-ui we nicely get the examples attached to each request body automatically so that our API consumers without further ado can try out communicating with our API. But when we try and import it to Postman we dont get our example values into the request bodies.

With the below endpoint i would expect to get the example values of the first example filled into postman under the values for each key in the request body, like i have described above in the 2nd. screenshot :)

<pre>
/Our/Unique/endpoint/route:
    post:
      operationId: a unique id
      description: |-
        a long and good description
      tags:
      - blabla
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OurCoolSchema'
            examples:
              OurCoolExample:
                value:
                  Keynumber 1: '{ "type": "LineString", "coordinates": [ [ 24.369429095215196,
                    77.215260792384441 ], [ 11.36925, 23.21543 ] ] }'
                  Keynumber 2: 42
                summary: a good summary
                description: A really good description
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/OurCoolSchema'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/OurCoolSchema'
        required: true
      security:
      - someSecurituSettings
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OurCoolResponse'
          description: ''
</pre>

**Comment by VShingala** [comment]
@AJ-BM Your use case is certainly achievable with the current import flow with the following steps.

1. Due to many different use cases, we have added options to tweak certain behaviors. Options are as below and can be accessed while importing/generating collections under Show advanced options dropdown.

Make sure you've selected `Example` for the 2 options mentioned in the below image. This makes sure instead of placeholder values like `<integer>`, actual examples are picked up.

![image](https://user-images.githubusercontent.com/16756296/150352499-01a797ad-56dc-450e-b4de-110c816d4d71.png)

2. In the schema you mentioned, examples are not mentioned for content-type `application/x-www-form-urlencoded`. Make sure they are available.

With 2 mentioned steps, I was able to get the expected behaviour by you in generated collection. Below is schema for more idea.

```
openapi: "3.0.0"
info:
  version: 1.0.0
  title: Swagger Petstore
  license:
    name: MIT
servers:
  - url: http://petstore.swagger.io/v1
paths:
  /Our/Unique/endpoint/route:
    post:
      operationId: a unique id
      description: |-
        a long and good description
      tags:
      - blabla
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OurCoolSchema'
            examples:
              OurCoolExample:
                value:
                  Keynumber1: '{ "type": "LineString", "coordinates": [ [ 24.369429095215196,
                    77.215260792384441 ], [ 11.36925, 23.21543 ] ] }'
                  Keynumber2: 42
                summary: a good summary
                description: A really good description
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/OurCoolSchema'
            examples:
              OurCoolExample:
                value:
                  Keynumber1: '{ "type": "LineString", "coordinates": [ [ 24.369429095215196,
                    77.215260792384441 ], [ 11.36925, 23.21543 ] ] }'
                  Keynumber2: 42
                summary: a good summary
                description: A really good description
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/OurCoolSchema'
        required: true
      responses:
        '201':
          content:
            application/json:
              schema:
                type: string
          description: ''
components:
    schemas:
        OurCoolSchema:
            type: object
            properties:
                Keynumber1:
                    type: string
                Keynumber2:
                    type: integer
```

Feel free to re-open the issue if you face any further difficulties.
