### ISSUE TITLE
Reopen #5502

### ISSUE THREAD

**Issue by nsp** [a85/POSTMan-Chrome-Extension#10476]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request

### Is your feature request related to a problem?

Multiple commenters have requested that issue #5502 be reopened, and there has been no response.

### Describe the solution you'd like

A maintainer to reopen the issue and address it.

### Describe alternatives you've considered

I thought about commenting on #5502, but see that there have been comments from Nov 2020 to Nov 2021, all unanswered.

**Comment by kd-at-mi** [comment]
@nsp @postman-support
There has been very little feedback on this, is it get worked on?  I think at the scale we are going we will need to find a another product that has this support.  Postman is a great product, but this is a key feature.

Thanks!
Here is one of our use case examples
https://github.com/postmanlabs/postman-app-support/issues/5502#issuecomment-1160577590

**Comment by DannyDainton** [comment]
The linked issue has been reopened. Closing this one.
