### ISSUE TITLE
Tabs Failing to reopen

### ISSUE THREAD

**Issue by p6345uk** [a85/POSTMan-Chrome-Extension#10487]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

Occasionally when I open postman I am confronted with 

![image](https://user-images.githubusercontent.com/4558013/145408671-4a55656f-5e17-4ee2-8e9c-10cde8f5e068.png)

It looks like it has lost every thing I'm working on

However if I switch workspace to my personal one then back to the team one they are now populated as expected

e.g.

![image](https://user-images.githubusercontent.com/4558013/145409080-6ef7207b-c7a8-466e-a8db-f690be7263dd.png)

### Steps To Reproduce

Open Postman.

### Environment Information

```markdown
- Operating System: Windows 10 Patched to latest
- Platform Type: Native App
- Postman Version: 9.3.1

4k display if that makes a difference
```

**Comment by postman-staff** [comment]
Hi **@****p6345uk****,**

Can you try to logout/login and check if that helps.

Additionally, clearing cache also helps in cases like these hence can you try to clear local files for your Postman installation as mentioned in this article here https://support.postman.com/hc/en-us/articles/4410785125271  and let me know if this helps?


via @ash007-postman | Postman Support

**Comment by DQJ0521** [comment]
v9.4.1 the problem still exist，
![378e67fe65808e99f10df10f22e334a](https://user-images.githubusercontent.com/47734905/146188052-640d6448-f34e-4bf2-82ef-594c33b86279.png)

**Comment by p6345uk** [comment]
Yup gave it a good go. followed the steps twice and still persists

@DQJ0521 I thought it was just me as no one had raised it already.

Hopefully they fix soon

**Comment by postman-staff** [comment]
Hi @p6345uk,

Can you try clicking on the new tab and see if that helps? If the issue still persists then would you please share your app's logs (%appdata%\Postman\logs.) via submitting a ticket via https://support.postman.com/hc/en-us/requests/new.

 ![](https://postman.zendesk.com/attachments/token/LBoxUlWK1oXJQhAGGCmyr9h1w/?name=image.png)

Also, can you try to unblock yourself by using the web version https://go.postman.co/ and see if this helps?

via @ash007-postman | Postman Support

**Comment by postman-staff** [comment]
Hi @p6345uk,

We haven’t received the requested information. Let us know if the web version helped you, also as requested kindly send us the apps logs via https://support.postman.com/hc/en-us/requests/new to investigate the issue further.

Thanks!

via @ash007-postman | Postman Support

**Comment by p6345uk** [comment]
Looks like its fixed in the new version :)

**Comment by postman-staff** [comment]
Hi @p6345uk,

That's great to hear that it's been sorted with the latest version :). I will be closing this thread here. Feel free to reach to us for any further assistance. Thanks!

Have a great year ahead.

via @ash007-postman | Postman Support
