### ISSUE TITLE
Full set of queries does not start in a collection in GUI mode

### ISSUE THREAD

**Issue by flexey-i** [a85/POSTMan-Chrome-Extension#10485]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

When trying to run on a mac os through the interface in a desktop application, the runner ignores some of the selected requests.

### Steps To Reproduce

Open app
Import a collection with over 360 queries and over 1400 tests (contains folders and requests)
Import environment for this collection
Select a collection in the list and the desired environment
Press RUN
Select by checkboxes all requests and directories with requests within the collection
Set launch parameters as in the screenshot below
Run

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/65505493/145369130-ee342d37-d141-431b-9b44-8decb36be164.png)

### Environment Information

```markdown
- Operating System: Mac OS Monterey 12.0.1 
- Platform Type: native app 
- Postman Version: 9.3.1
- Hardwere : RAM 16Gb \ Intel Core i5 4CPU
```

### Additional Context?

When running through Newman, we get the result: 367 requests and 1457 tests

When running through the GUI, we get the result: 304 requests and 849 tests

**This problem doesn't reproduce on Win10**

**Comment by postman-staff** [comment]
Hello @**flexey-i**

Thanks for reaching out. I'm happy to help! Does exporting and reimporting the collection affect anything? Do you notice the same behavior if you use the web app on the Mac to run the collection?

Would you be able to provide screenshots for the expected results on the windows machine and the discrepancy on Mac Os machine. A full screenshot of the entire collection runner results along with the newman run would be helpful.

Appreciate your cooperation!

via @nrmartell | Postman Support

**Comment by flexey-i** [comment]
Hello!

No, reimport does not change behaviour.
When using the web version on mac os, everything works fine.

Yes, of course, I will attach screenshots and additional information.

**Comment by malvikach** [comment]
Hi @flexey-i 👋 
I am closing this ticket due to inactivity. Please feel free to reopen if you are still seeing this issue. Do help us with additional context that helps us understand the problem better. 
Cheers!
Malvika
