### ISSUE TITLE
Image response preview not working

### ISSUE THREAD

**Issue by reno184** [a85/POSTMan-Chrome-Extension#1048]
Hi,
I just download postman, and It's seem that the image response preview is not working ?

thank in advance

reno184

**Comment by abhijitkane** [comment]
Are you still seeing this in v3.0.4 of Postman?

**Comment by bfitzsimmons** [comment]
I'm seeing it as of 3.0.13.

**Comment by abhijitkane** [comment]
@bfitzsimmons Can you share any publicly-accessible URL which reproduces the problem?

**Comment by bfitzsimmons** [comment]
Sure thing.
http://globe-views.com/dcim/dreams/lion/lion-06.jpg

**Comment by bfitzsimmons** [comment]
Are there settings for the app that toggle the image preview? I didn't see any, but thought I'd ask anyway.

**Comment by abhijitkane** [comment]
http://postimg.org/image/8ibws4la9/
Seems to work for me. Can you check Postman's console for any errors when you send the request - http://blog.getpostman.com/2015/06/13/debugging-postman-requests/ ? Also, the network tab will show the exact request/response payloads.

**Comment by bfitzsimmons** [comment]
It looks like I'm able to see the image preview after turning the Interceptor off. I don't even know what that thing does yet, not why it was turned on in the first place.

**Comment by abhijitkane** [comment]
The Interceptor is used to stream requests from the browser into Postman, and be able to read/write cookies.
You can install the Interceptor from https://chrome.google.com/webstore/detail/postman-interceptor/aicmkgpgakddgnaphhhpliifpcfhicfo?hl=en
Docs - http://blog.getpostman.com/2014/11/28/using-the-interceptor-to-read-and-write-cookies/, https://www.getpostman.com/docs/capture

**Comment by bfitzsimmons** [comment]
After turning on the dev. tools, and turning off the Interceptor, I'm able to both see the call in the dev. tools and see the image preview.

**Comment by bfitzsimmons** [comment]
Okay, @abhijitkane I'll check it out when I either have the time, or require the functionality.

Thanks for your -- very quick -- help.

**Comment by Arrow7000** [comment]
I've just seen this thread. I had the same problem and for some reason turning the interceptor off does work. Is this a bug or a feature?

**Comment by a85** [comment]
@Arrow7000 I'd recommend switching to our native apps.

**Comment by mattbits** [comment]
can confirm this behavior is happening in Mac native client v4.9.2 and disabling interceptor is workaround.

**Comment by koreyba** [comment]
The same happens for me now on Windows desktop app v. 4.9.3.
I don't know how to disable Interceptor in the desktop version.

I tried to use Chrome app and disable Interceptor but it didn't help too.

**Comment by hakimio** [comment]
Even with interceptor disabled html preview doesn't show images...

**Comment by sdnts** [comment]
Guys, are the Content-Type headers in your responses correct? I've been testing this with `http.cat/200`, and all images preview properly.

**Comment by hakimio** [comment]
"Content-Type:image/svg+xml"
Image set using CSS background property.

**Comment by GauthamBanasandra** [comment]
I'm facing this issue too. I've a simple go http server which responds with `Content-Type: image/png` when I hit this endpoint from Postman, I just see the image but unable to view the raw response.

**Comment by sujayvenaik** [comment]
Hey @GauthamBanasandra 
We do not show the raw response for media type responses, what I can do is go ahead and create a feature request for you for this.

**Comment by GauthamBanasandra** [comment]
@sujayvenaik I think it'll be really useful. Thanks.

**Comment by mulder999** [comment]
v10.9.4 and still it does not refresh properly for SVG when parameters change in URL.
Need to download image/vector as workaround.
