### ISSUE TITLE
Collection Documentation - Broken Hyperlink Support for Spaces

### ISSUE THREAD

**Issue by carlmes** [a85/POSTMan-Chrome-Extension#10482]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

When creating documentation for a Postman collection, I cannot copy/paste a hyperlink containing `%20` characters (spaces). 

For example this link `http://devopsserver.com:8080/tfs/My%20Financial%20Projects/ProjectName/_workitems/edit/159657` gets mangled when copy / pasting. It's also impossible to edit it using the Postman hyperlink editor, the broken format is reverted when applying the change.

### Steps To Reproduce

1. Open the Documentation for a Postman collection
2. Paste a hyperlink containing special characters (`%20` space)
3. Observe mangled unreadable documentation

### Screenshots or Videos

Inserting a hyperlink, then clicking save button:
<img width="429" alt="image" src="https://user-images.githubusercontent.com/10638247/145279539-503ec5ff-ec1d-46dc-a53f-f9f2f0f207d3.png">

Mangled documentation:
<img width="347" alt="image" src="https://user-images.githubusercontent.com/10638247/145279619-25c8ca58-b426-44f6-8ce7-97b9f15faf45.png">

### Environment Information

```markdown
- Operating System: Windows 10
- Platform Type: Native App
- Postman Version: 9.3.1
```

### Additional Context?

Attempting to fix the broken hyperlink using the link edit function doesn't resolve the problem.

**Comment by Raja-Simha** [comment]
Hey @carlmes thanks for bringing this to our notice. We will look into this issue and keep you posted.

**Comment by kamaraj-p** [comment]
This issue is now resolved. Thanks @carlmes for taking the time to report this.
