### ISSUE TITLE
Feature Request: get response time metrics for N times

### ISSUE THREAD

**Issue by ghost** [a85/POSTMan-Chrome-Extension#10499]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request

### Is your feature request related to a problem?

This is a feature request

### Describe the solution you'd like

Make N times request, show the response time for a result as a table

### Additional context

![image](https://user-images.githubusercontent.com/278153/145922934-de2e6aa5-7623-4e58-9cbc-eca0db514d41.png)

**Comment by ghost** [comment]
This request is for a common task, if we want to quick measure our API is slow or fast.
We do not need a very heavy tools, PostMan just did the great job. 

We need put things together, for better comparing.

**Comment by giridharvc7** [comment]
@cnmade 
If this is for a request, you can put this request in a collection and run the collection with the said `n` iterations. You will get an output like so
<img width="1064" alt="Screenshot 2021-12-28 at 4 19 01 PM" src="https://user-images.githubusercontent.com/1040583/147558708-c6cfee92-f713-4ef3-8752-7b143d6a1662.png">

Do you need this for benchmarking purposes?

**Comment by ghost** [comment]
@giridharvc7 thanks for tips。
