### ISSUE TITLE
Postman doesn't allow selection of environment in publish section

### ISSUE THREAD

**Issue by vishnu-wednesday** [a85/POSTMan-Chrome-Extension#10491]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

Postman when publishing documentation or Edit Published Documentation doesn't allow selection of environments. It shows No Environments in the drop down!

This seems to be a JS error as far as I can see in the console. Would be great if you could fix this. 
![environment](https://user-images.githubusercontent.com/89914586/145576241-9def71e8-adfb-4e79-a53c-0efd0cc1c4d5.png)

### Steps To Reproduce

Create a collection documentation that relies on an environment
Try to publish a documentation for the collection and try to select the environment from the drop down. 

### Screenshots or Videos

Would more than happy to add if needed. 

### Environment Information

```markdown
- Operating System: Linux/Ubuntu
- Platform Type: Mozilla Firefox
- Postman Version: 9.3.1
```

### Additional Context?

Would be great to get this sorted out. Having to share environments separately is a pain.

**Comment by Raja-Simha** [comment]
@vishnu-wednesday This issue has been fixed in the latest version of app and on web. Closing the issue but feel free to reopen if you still find the issue unresolved.

**Comment by vishnu-wednesday** [comment]
Can confirm that this is fixed now. Thanks for the quick turnaround!
