### ISSUE TITLE
Can't search anymore.

### ISSUE THREAD

**Issue by cs12110** [a85/POSTMan-Chrome-Extension#10496]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

When I using postman `Find and replace` function, and it doesn't work any more.

I found this function is very useful for me. but when I upgraded the version >= v9.0, I can't search any request by that(Using Everything mode).But switch to collections mode, it can do the job well.

Please, sir, would you mind spend some times to check out what happened?

### Steps To Reproduce

1. open postman app
2. using `Find and replace` function(on the left bottom of the app)
3. input any request url
4. click the `Find` button

### Screenshots or Videos

Error:

<img width="1324" alt="err01" src="https://user-images.githubusercontent.com/12764287/145746136-034f628a-5168-4915-8f5e-fff643fae107.png">

Work:

<img width="1214" alt="suck" src="https://user-images.githubusercontent.com/12764287/145746142-15ecd83f-3bf1-4ab4-94d1-92c909fe901e.png">

### Environment Information

```markdown
- Operating System: mac
- Platform Type: osx
- Postman Version: Postman v9.4.1
```

**Comment by postman-staff** [comment]
Hey hi,

Thank you so much for flagging this with us.

I am checking with the team internally on this and will get back to you with the updates from the engineering team.

Meanwhile, we appreciate your patience!

via @Lincimary | Postman Support

**Comment by p6345uk** [comment]
Getting a similar issue in the windows version.
Additionally in the windows version the "open in builder" doesn't work

**Comment by postman-staff** [comment]
Hi there,
Thank you for reporting this.

Sorry that it is taking a quite long time than expected. I will keep you posted here once I get the update from the engineering team.
Thank you so much for your patience in this regard.

via @Lincimary | Postman Support

**Comment by ChristineP2** [comment]
I just updated to v 9.6.1 and I am seeing this issue. I tried rebooting after the update to see if that would help.

Console error:
```
vendor-ui.js:4681 Uncaught (in promise) TypeError: Cannot read property 'info' of undefined
    at vendor-ui.js:4681
    at Rt (vendor-ui.js:4881)
    at Function.Aa [as map] (vendor-ui.js:4881)
    at d (vendor-ui.js:4881)
    at fa (vendor-ui.js:4881)
    at vendor-ui.js:4881
    at Lt (vendor-ui.js:4881)
    at bo (vendor-ui.js:4881)
    at Gn.value (vendor-ui.js:4881)
    at bo (vendor-ui.js:4881)
    at qn.Vn.toJSON.Vn.valueOf.Vn.value (vendor-ui.js:4881)
    at r.getTargetTabs (vendor-ui.js:4681)
    at r.handleFind (vendor-ui.js:4681)
    at r.handleFind (vendor-ui.js:4681)
    at c.handleClick (vendor-ui.js:4642)
    at Object.s (vendor-ui.js:2)
    at m (vendor-ui.js:2)
    at vendor-ui.js:2
    at b (vendor-ui.js:2)
    at st (vendor-ui.js:2)
    at it (vendor-ui.js:2)
    at lt (vendor-ui.js:2)
    at ht (vendor-ui.js:2)
    at P (vendor-ui.js:2)
    at z (vendor-ui.js:2)
    at $t (vendor-ui.js:2)
    at Xt (vendor-ui.js:2)
    at t.unstable_runWithPriority (vendor-ui.js:2)
    at Yo (vendor-ui.js:2)
    at D (vendor-ui.js:2)
    at Kt (vendor-ui.js:2)
    at HTMLDocument.r (vendor-ui.js:4881)
```

I don't know if you noticed, but it seems [you might be overwhelming your APM](https://sentry-app.postmanlabs.com/api/22/store/?sentry_key=8fb2d5d1749642eface793d3dd93a6d8&sentry_version=7) `Failed to load resource: the server responded with a status of 429 (TOO MANY REQUESTS`  

Ok, wow, there's a lot here.  If you aren't seeing it and need me to send it, just let me know.

**Comment by postman-staff** [comment]
Sorry that you are facing 429(too many requests) error while updating the application.

Are you using the Linux platform?

If yes then, Could you please try to use the postman snap application and see if that unlocks you?
(Snap application automatically updates itself, you dont have to worry about the updates anymore)

via @Lincimary | Postman Support

**Comment by ChristineP2** [comment]
Hi!  I'm using a Mac, not Linux. Here are some samples of what I'm seeing

![Open_Application part-1](https://user-images.githubusercontent.com/984648/147146520-bad34872-bd34-4e78-8a39-228daa88a578.png)
![Open_Application part-2](https://user-images.githubusercontent.com/984648/147146524-bcdce906-ec1f-4ee8-92a6-d71079a036d4.png)
![Click_find_replace_attempt_find](https://user-images.githubusercontent.com/984648/147146498-f6c42243-f4af-489b-940e-2f2fb042335d.png)
![Wake_after_sleep](https://user-images.githubusercontent.com/984648/147146525-cbda05bb-d46d-4bed-a1af-619890b1208d.png)
 
There seems to be a lot going on in the Devtools Current View console. Let me know if you need more comprehensive information.  This is just a brief snapshot.  The more I worked yesterday, the more new issues arose.

**Comment by ChristineP2** [comment]
Update: I had a coworker check their search and it worked.

Since it worked for them, I uninstalled postman, went into Mac Library's Cache (`rm -r com.postmanlabs.mac`, `rm com.postmanlabs.mac.ShipIt`), Application Support (rm -r Postman), then reinstalled postman and I was once again able to find and replace.

It would be nice to not lose that functionality at all, but at least you can get it back.

Note: Just deleting the Mac Library Cache will not solve the problem.  If you reinstall postman and are still logged in, then find/replace probably will still not be working.

**Comment by cs12110** [comment]
> 
Miss, would you mind tell where the folders(`com.postmanlabs.mac`,`com.postmanlabs.mac.ShipIt`) it is? I can't find on my mac, silly me. It the path is `/Library`?

**Comment by postman-staff** [comment]
Hey hi,
Sorry for the delayed response.

If you are looking for the Postman installation folders and backup files then you can find them under the following directory

`~/Library/Application Support/Postman `​ for macOS

I would also like to keep you informed that  `/Library` and` ~``/Library `are different.

Feel free to reach back out if you need anything else. I'd be more than happy to help:)
via @Lincimary | Postman Support

**Comment by ChristineP2** [comment]
Sorry, I may not have been clear.  

I was able to resolve the problem reported by @cs12110. In order to resolve that issue, I uninstalled postman, deleted the aforementioned cache directories and reinstalled postman.  Once I took those steps, I was once again able to use find/replace.

My first message ended up being unrelated, but it was basically that your logs have a lot of chatter and errors and seem to be sending a lot back to Sentry.  It might be worth looking into that chatter.

**Comment by postman-staff** [comment]
Thank you for clarifying.

Glad that your problem was sorted out.

Thank you for flagging this, we greatly appreciate it.
Please let me know if I can do anything else for you

via @Lincimary | Postman Support

**Comment by ChristineP2** [comment]
So, when I upgraded and the find/replace stopped working, it seems like that relates to the caches.  I wonder if cleaning up whatever caused the issue could be automated? If not, at least there is a work around, but it would be nice if we didn't have to uninstall/delete/reinstall to resolve whatever conflict prevents find/replace from functioning after upgrade.

Anyway, hope this gives you some avenues to explore on that front.  Good luck :)

**Comment by postman-staff** [comment]
Thank you so much for sharing your feedback on this.

I will forward it to our engineering team to check and address it, they are still working towards the fix. I will also keep you posted on any updates from the team.

via @Lincimary | Postman Support

**Comment by cs12110** [comment]
> So, when I upgraded and the find/replace stopped working, it seems like that relates to the caches. I wonder if cleaning up whatever caused the issue could be automated? If not, at least there is a work around, but it would be nice if we didn't have to uninstall/delete/reinstall to resolve whatever conflict prevents find/replace from functioning after upgrade.
> 
> Anyway, hope this gives you some avenues to explore on that front. Good luck :)

Upgrade the postman version to `Postman v9.7.1`, the function is back to normal.

It's back(make me cry like a little child.jpg). 

Thanks for the detail of solve the problems. 

Have a nice day. :"}

**Comment by postman-staff** [comment]
Awesome, thanks for letting me know!
If you’re all set, that’s great - I will go ahead and mark this situation `Solved`.

Please let me know if you need anything else. I'd be more than happy to help.

Have a great day:)

via @Lincimary | Postman Support

**Comment by p6345uk** [comment]
Still broken for me in Windows version

**Comment by postman-staff** [comment]
Hi **@**p6345uk,


Fix has been pushed in the version 9.7.0 release, Could you please confirm if you are on the latest version and still facing issues?


via @Lincimary | Postman Support

**Comment by postman-staff** [comment]
Hi,

Just letting you know I’m still here so feel free to give me a shout if you’re still running into any issues.

via @Lincimary | Postman Support

**Comment by postman-staff** [comment]
Hi there,

Just letting you know that I'm going ahead and closing this conversation. If you still need help, just respond to this ticket to re-open it. Otherwise, please feel free to reach out again later!

Have a great day:)

via @Lincimary | Postman Support
