### ISSUE TITLE
Response body not displaying anything

### ISSUE THREAD

**Issue by Kingsconsult** [a85/POSTMan-Chrome-Extension#10498]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

I am having this issue, this is an endpoint that I use every day in the last 4 months, except this morning, I discovered that my postman just updated to v9.4.1 (the latest)
![image](https://user-images.githubusercontent.com/46958081/145795081-117ba1b6-0004-415a-bd8d-cf7d781cab53.png)

This is the error message I am getting when I check **view/Developer/Show Devtools(Current View)**
![image](https://user-images.githubusercontent.com/46958081/145795605-3c1a6231-9a54-4425-877a-56b7e4128ded.png)

### Steps To Reproduce

1. open postman and run my existing endpoints

### Environment Information

```markdown
- Operating System:  Windows
- Platform Type: windows 10
- Postman Version: v9.4.1
```

**Comment by postman-staff** [comment]
Hi there,

Are you seeing this issue over your specific request or all the requests? Do you get any response after sending the request using Postman on Web - https://go.postman.co/ version?

Can you try sending the below sample POST & a GET request respectively and see if you are able to get the response for these requests? Please refer to the below screenshot for reference.

POST - https://postman-echo.com/post

​ ![](https://postman.zendesk.com/attachments/token/l0fsSlcorHmERC6GUz80Mi2ud/?name=POST.png)


* * *

GET - https://postman-echo.com/get

​​ ![](https://postman.zendesk.com/attachments/token/usM8Fd9HG7Uu1iBPUQsF2xQJK/?name=GET.png)

Let me know how it goes.

via @Swapnil-getpostman | Postman Support

**Comment by Kingsconsult** [comment]
I have to uninstall and restart the postman before it was finally resolved

**Comment by postman-staff** [comment]
Thanks for the update.

I'm assuming the issue has been resolved for you. Let me know if you require any further assistance and if you are all set then with your permission, can I close this request?

via @Swapnil-getpostman | Postman Support
