### ISSUE TITLE
Description field background does not adopt dark mode (on edit) 

### ISSUE THREAD

**Issue by HeikoKramer** [a85/POSTMan-Chrome-Extension#10495]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

The **description field** background in the **save request** form does not adopt the proper dark mode background in **edit mode**.
So the background color is nearly the same as the text color (slightly brighter), when entering a description – and therewith basically not readable. 

### Steps To Reproduce

1. Open a new Request Tab
2. Save / Save As
3. Click "Add description"

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/68162050/145709127-cb9d9ab1-d191-4ce4-9ce5-49dcd5d6ce4e.png)

### Environment Information

```markdown
- Operating System: Linux Mint 20.2 x86_64
- Platform Type: Native App
- Postman Version: Postman for Linux, Version 8.12.2, linux 5.11.0-41-generic / x64)
```

**Comment by chrisdeso** [comment]
I was able to reproduce this on MacOS 11.5.2 (20G95) as well

Loom – [https://www.loom.com/share/de83ae6d87a541bc9694a674393d870f](https://www.loom.com/share/de83ae6d87a541bc9694a674393d870f)

Routing this through support.

**Comment by postman-staff** [comment]
Hey @HeikoKramer 

I have tried replicating this in the latest version and in the Web Version. It looks like this issue is not being seen.
Could you please try to update your application to the latest version and let us know if you are still seeing the same?


https://user-images.githubusercontent.com/76939396/145951996-7d9849fa-344c-4602-b19f-7c3a725bc502.mov


via @VaishnaviChallaPostman | Postman Support

**Comment by diivi** [comment]
@postman-support clicking inside the description box triggers this issue for me

**Comment by postman-staff** [comment]
Hey **@diivi**
Thanks for flagging it.
I am able to replicate this. I am sorry for missing this step earlier - @HeikoKramer.
I will raise this internally and get back to you with any updates on this.
Thanks for your patience.

via @VaishnaviChallaPostman | Postman Support

**Comment by twitharshil** [comment]
Hey @HeikoKramer 

Thanks for reporting the issue! A fix for this is implemented & planned to be out soon with the next minor version release for the postman application (v9.14.0)

**Comment by postman-staff** [comment]
Hey @HeikoKramer 👋
Happy to let you know that this is fixed in the latest version :)

via @VaishnaviChallaPostman | Postman Support
