### ISSUE TITLE
Javascript in Test éditor

### ISSUE THREAD

**Issue by SimonDaigneault** [a85/POSTMan-Chrome-Extension#1049]
This treatment : 

var dataRaw = '{"result":"Succeed","message":"Allo"}';

var toto = JSON.parse(responseBody,function (k, v) 
                                                                    {if(k==="Allo" {return "";} return v;});

The containt of "JSON.stringify (toto)" is always
"'{"result":"Succeed","message":"Allo"}'; " in Postman

instead of

 '{"result":"Succeed","message":""}'; as in Newman

It's ok with NEWMAN but not work in Postman

**Comment by abhijitkane** [comment]
Thanks for pointing this out - we'll fix this in the next release.

**Comment by abhijitkane** [comment]
Fixed in the latest versions. The 2nd argument to JSON.parse is respected.
