### ISSUE TITLE
Enhancement request to implement Pull feature request for Environment

### ISSUE THREAD

**Issue by ash007-postman** [a85/POSTMan-Chrome-Extension#10504]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request

### Is your feature request related to a problem?

At the moment, when users try to Fork the environment and then Pull changes from the parent fork, the "Create pull request" option cannot be used since it's disabled. Requesting to include the option such that users can benefit this feature similar to the way it is enabled to collections

### Describe the solution you'd like

The only way as of now is to manually migrate the changes or create duplicates hence it would be great to have Pull request feature for environments. 
![image](https://user-images.githubusercontent.com/41741228/146327420-f375af94-ab3d-4ef1-a614-58a391df644b.png)

**Comment by ankitjaggi** [comment]
We launched the ability to use Pull Requests for Environments with the latest version.  You can find all the information in this [blog post](https://blog.postman.com/introducing-environment-forking-and-pull-requests/).
