### ISSUE TITLE
Getting an error using postman web app with aws cognito

### ISSUE THREAD

**Issue by alexei-moneyr** [a85/POSTMan-Chrome-Extension#10501]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

I'm having an issue trying to authenticate with aws cognito from web app.

It's working from the desktop app.
For some reason address of login is wrong

https://XXXXXX-XXXXXX.auth.eu-west-1.amazoncognito.com/error?error=redirect_mismatch&client_id=7ml3csmgir3h0bi76r6XXXXXX

this i'm getting from web app

https://mXXXXXXg-moXXXXXge.auth.eu-west-1.amazoncognito.com/login?response_type=token&client_id=7ml3csmgir3h0bi76XXXXX&scope=openid&redirect_uri=https%3A%2F%2Flocalhost

this from the desktop app

same settings in the authorization tab. 

### Steps To Reproduce

Open API from web client and trying to authenticate

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/82156498/146039704-7950ae78-8218-4d83-9d86-c507b8843e0b.png)

### Environment Information

```markdown
- Operating System: windows/mac
- Platform Type: native/web
- Postman Version: 9.4.1
```

**Comment by DannyDainton** [comment]
This issue appears to be very contextually specific to your project, if you're able to recreate the issue away from that and can share details to enable us to recreate the problem on are side, we can investigate further. For now, I'm going to close this.
