### ISSUE TITLE
Research doesn't work anymore and can't close all tabs at once

### ISSUE THREAD

**Issue by vbeaudoin19** [a85/POSTMan-Chrome-Extension#10502]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

After one update around 1 month back, I can't no longer use the option to 'close all tabs' at once. I need to close all them manually or by using the option to 'close all other tabs' then close the last one.

Around the last week or so, the research doesn't work anymore, nothing is happening when I click on 'find'.

I check the update regularly and reboot my PC.

### Steps To Reproduce

See the description issue

### Environment Information

```markdown
- Operating System: W10 v19044.1348
- Platform Type: Software
- Postman Version: v9.4.1
```

**Comment by DavidDeks** [comment]
The "Close All Tabs" and "Force Close All Tabs" don't work for me either.
![image](https://user-images.githubusercontent.com/53012236/147995769-4e56f832-8931-493e-820c-c389fa363c68.png)

Using macOS BigSur version 11.6.2
Postman Version: 9.7.1

**Comment by p6345uk** [comment]
Same for me in Windows
Windows 10
Version 9.7.1

**Comment by vbeaudoin19** [comment]
Go see : https://support.postman.com/hc/en-us/articles/4410785125271

My problem was resolved by adding " old" to the Postman folder.

Watch out, it will erase your 'current value' in the Postman environment variable. Be sure to save them before processing.
