### ISSUE TITLE
Request access to request body in pre-request script

### ISSUE THREAD

**Issue by dmillman** [a85/POSTMan-Chrome-Extension#1050]
I need access to the request body in the pre-request script.

**Comment by dmillman** [comment]
Request.js line 546 seems to be the issue:
`else if (dataMode === "binary") {`
`data = "";`

**Comment by abhijitkane** [comment]
Thanks for pointing this out. We'll fix this in the next release.

**Comment by abhijitkane** [comment]
@dmillman The `request.data` property is available in the pre-request script sandbox. Can you confirm?

**Comment by dmillman** [comment]
Still doesn't work when dataMode === "binary"

**Comment by abhijitkane** [comment]
Ah..forgot this was only for binary data. That's too large to be read into Postman directly. Allowing access to the entire uploaded file makes it impossible to upload large files. Will need to wait till we figure out a better way of doing this.

**Comment by faragorn** [comment]
Would be great to hear any updates on the issue? Is it possible to get access at least to: file_content_type, file_size and name? Thanks

**Comment by mvkrish** [comment]
is it possible to update the request.data?, for example say usually i send 10 input but for a quick test i need to send only one.

**Comment by Misiu** [comment]
@abhijitkane  any news on this?
This is old feature request, but it is still valid and important (I think that not only to me).
I need to access full raw request body to calculate hash (https://stackoverflow.com/questions/49509612/postman-access-full-request-body-to-calculate-hash-in-pre-request-script)

maybe You could add some additional details to request object (that is available in pre-request script)?
content type, content length, couple of hashes from request body (MD5, SHA1, SHA2).

What do You think? Is it doable?

**Comment by Misiu** [comment]
@abhijitkane I found this:  https://github.com/postmanlabs/postman-request/blob/master/lib/oauth.js#L64
It looks like postman-request can calculate hash from body.
Can this hash be available globally inside request object? or allow us to access request body inside pre-request scripts.

Right now I can't create requests that upload small files, because I can't calculate hash from body 😕

**Comment by kamalaknn** [comment]
Hi @Misiu 

We have exposed the request body in pre-request script through `pm.request.body`. This is an instance of `http://www.postmanlabs.com/postman-collection/RequestBody.html`.

You can consume this to read the request body. However we do not support mutating the body from script yet. 

The `pm.*` API is only supported in the Native apps. Here's the complete documentation - https://www.getpostman.com/docs/v6/postman/scripts/postman_sandbox_api_reference

**Comment by Misiu** [comment]
@kamalaknn awesome news :)
I'll modify my pre-request script and hopefully everything will work fine.

**Comment by Misiu** [comment]
@kamalaknn sadly this isn't working as needed. I need to calculate hash from whole RAW request body.
Please take a look at: https://github.com/postmanlabs/postman-app-support/issues/4377

When I inspect `pm.request.body` for `form-data` request I get JSON tree.

![snap 2018-03-28 at 09 19 12](https://user-images.githubusercontent.com/1741838/38014516-5556d53a-3269-11e8-9ae3-1441e955c42a.png)

I need to calculate hash of full body that is seen in fiddler. Any ideas how to do in in Native App?

**Comment by kamalaknn** [comment]
We don't give access to the contents of the files in `pre-request` scripts, for a few reasons.

1. We want to delay loading file contents to right before the request is sent.
2. The request body is not actually resolved until the `pre request` scripts are completed. So even if we wanted to we can't give the actual body of the request in `pre-request` scripts.

You can post your requirements in the [Postman Community](https://community.getpostman.com/) to get a broader feedback on how the community is solving these kinds of problems.

Over the long term, we intend to allow users to define/add custom authentication methods.

**Comment by Misiu** [comment]
@kamalaknn I'm in the middle of posting my question in Postman Community.
Currently I've build app in C# to test that endpoint security, but ideally I'd like to avoid creating that app and move everything to Postman.

Custom authentication methods would be awesome. When You implement them please remember that some of them (HMAC) need to calculate hash of full request body, even when You send files.

**Comment by bdawada** [comment]
@Misiu  Did you get response in postman community. I am trying to do something similiar.

**Comment by Misiu** [comment]
@bdawada unfortunately no. 
I'm migrating my collection to [Insomnia](https://insomnia.rest/) for tests, because it is very similar and from what I found it should work there.

**Comment by Misiu** [comment]
@bdawada Yes I got response (https://community.getpostman.com/t/calculate-hash-from-full-raw-request-body/1320/4)
This might get added but not as an official option.

**Comment by Misiu** [comment]
@kamalaknn thank You for update.
Currently I'm using my own C# app to test my API, but I'd like to create PostMan collection and share it with other developers (not everyone is using C#).

Custom authentication methods sounds interesting, but please remember that some of them require access to full request body (in my case I need to calculate hash from whole raw body)
