### ISSUE TITLE
Unable to open application on Windows 10.

### ISSUE THREAD

**Issue by Keki91** [a85/POSTMan-Chrome-Extension#10517]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

v9.6.1 - Application will not start on Windows 10.

Also: https://community.postman.com/t/postman-wont-start-windows-10/4386/11

- I have deleted every reference to Postman in AppData (both Local and Roaming)
- Tried launching by running as administrator
- Tried adding disable gpu in environment variables
- Nothing is being written to AppData/Roaming
- Tried giving "everyone" permission to appdata/roaming/postman

Nothing opens in Task Manager

### Steps To Reproduce

1. Try to open application
2. Nothing happens.

### Environment Information

```markdown
- Operating System: Windows 10 - 21H2
- Platform Type: Native App
- Postman Version: 9.6.1 or 9.3.0 Canary 1
```

**Comment by jviotti** [comment]
I believe this is an instance of https://github.com/postmanlabs/postman-app-support/issues/8974, so I'll close it so we can continue the conversation here. Can you try running the app as an admin? We'll re-open if that doesn't work

**Comment by Keki91** [comment]
It was running as an admin. 

However, it's started working automatically again as soon as it installed an updated version about 3 days later.
