### ISSUE TITLE
runner does not stop after manual termination

### ISSUE THREAD

**Issue by m3dbedb** [a85/POSTMan-Chrome-Extension#10518]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

If you have postmansetNextReques with unreachable condition you may need to stop runner manually
Postman 9.6.1 does not stop execution when I push "stop run" button

### Steps To Reproduce

create collection with 2 steps:

step 1

step 2

with tests:

    var i=1
    if (i<10) postman.setNextRequest('step1');

run the collection, wait several second and press stop run

in my case I have to wait for 4000 iterations until execution stops

### Environment Information

```markdown
- Operating System: centos 7 with latest updates
- Platform Type: i5 machine
- Postman Version: 9.6.1
```

**Comment by shubhbhargav** [comment]
@m3dbedb Can you please share the following to help us debug this further:
- A recording for the issue happening live -- in-case the collection contains sensitive information, please do remove the same and share it on `help@postman.com`
- [if possible] a scaled down version of the collection that is facing this issue -- you can share it on `help@postman.com` itself

We tried reproducing it at our end but weren't able to. Sharing the collection below that we used.

[Github 10518.postman_collection.json.zip](https://github.com/postmanlabs/postman-app-support/files/7777225/Github.10518.postman_collection.json.zip)

**Comment by shubhbhargav** [comment]
@m3dbedb I am closing off this ticket for now but feel free to reach out here if the issue persists. We will re-open the ticket and look into it.
