### ISSUE TITLE
New Integration Request - <product name>keen

### ISSUE THREAD

**Issue by mrsagansay** [a85/POSTMan-Chrome-Extension#10516]
### Describe your current workflow

push postman to monitor result

### Describe your ideal workflow

result to keen stream for API base

**Comment by abhijitkane** [comment]
@mrsagansay Can you elaborate what you mean by `API base`? We supporting sending monitor results to Keen (https://learning.postman.com/docs/integrations/available-integrations/keen/), but there are currently no other events from the API that are sent.

**Comment by mrsagansay** [comment]
Hi hello Kane..I'm very sorry, and I apologize for confusing you, anyway, we just forgot those, my mistake,Thanks 
    On Thursday, December 23, 2021, 05:03:26 PM GMT+8, Abhijit Kane ***@***.***> wrote:  
 
 


@mrsagansay Can you elaborate what you mean by API base? We supporting sending monitor results to Keen (https://learning.postman.com/docs/integrations/available-integrations/keen/), but there are currently no other events from the API that are sent.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
