### ISSUE TITLE
9.6.1 Graphql variables dont send if to long

### ISSUE THREAD

**Issue by custj** [a85/POSTMan-Chrome-Extension#10514]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

Using the either the desktop app or web version, on the prior postman version version I was able to have a long json set of variables (depth -4) that would then send with my graphql  mutation/queries.  Now some of the longer variable sets dont get passed when I view the "code snippet" of the request.  If I trim down the length of the variables, they do eventually appear in the "code snippet" and then work as expected.

### Steps To Reproduce

1. Create request body of graphql
2. Paste mutation in query
3. Paste variables in query
4. open "code snippet" - if variable string is to long, snippet wont recognize and thus variables wont be sent with request

### Screenshots or Videos

Screenshot length of variables that wont work
![Postmanvariableissue1PNG](https://user-images.githubusercontent.com/90636471/146989796-edff10a5-b9d2-4328-85d8-eb657afe4df8.PNG)

Screenshot of trimmed down set of variables that will work
![Postmanvariablesissue2](https://user-images.githubusercontent.com/90636471/146989847-36591ead-0c0c-4c8b-a6c8-5dcd9a9afbcc.PNG)

### Environment Information

```markdown
- Operating System: Windows 10 Business
- Platform Type: Both
- Postman Version: 9.6.1
```

**Comment by shubhbhargav** [comment]
@custj I tried replicating the same but wasn't able to do so. Sharing the screenshot below. I've 2 hypotheses here:

- It could be OS specific (I tested it out on Mac) -- I will see if it's reproducible on Windows 10
- Maybe the `GraphQL Variables` JSON was malformed

Can you please share the exact JSON that you used for the variables? I tried to mimic it as much as possible but maybe I am missing something.

<img width="922" alt="Screenshot 2021-12-26 at 8 48 23 PM" src="https://user-images.githubusercontent.com/41579749/147412555-4672b980-a95e-47f5-9816-fa181d6a1a35.png">

**Comment by shubhbhargav** [comment]
@custj I am closing this ticket as of now. Please feel free to let us know if you are still facing the issue. We will re-open the ticket and debug / resolve accordingly.
