### ISSUE TITLE
JavaScript is executed on inline events

### ISSUE THREAD

**Issue by ebenpack** [a85/POSTMan-Chrome-Extension#1051]
JavaScript is executed on inline events attached to html elements returned in Postman responses. E.g., if a request is made to retrieve the following html file, it will result in an infinite loop which consumes a large amount of resources and locks up the tab.

```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Document</title>
</head>
<body>
    <img onerror="this.src='//example.com/defaultimg.jpg'" src="//example.com/img.jpg">
</body>
</html>
```

In this example, since it uses a protocol relative url, the request to default image will be made to filesystem://example.com/defaultimg.jpg, which will necessarily fail. This triggers `onerror`, which makes another request to filesystem://example.com/defaultimg.jpg, which triggers `onerror`, which... ad infinitum.

Aside from just locking up the tab, this also allows seemingly arbitrary execution of JavaScript for any given request made through Postman. E.g. the image element above could be replace by this, which would result in 'foo' being printed to the user's console:

```
<img onerror="console.log('foo'); " src="//badurl">
```

It appears as if this JavaScript is sandboxed by an iframe, which probably mitigates this issue to an extent, but regardless it seems like Postman probably shouldn't be allowing this JS to execute.

**Comment by abhijitkane** [comment]
You're right - all JS execution in the preview iframe needs to be disabled. We'll work on fixing this issue soon.

**Comment by SamvelRaja** [comment]
This has been fixed in the latest app, hence closing it.
