### ISSUE TITLE
Not able to commit Postman collection changes to Azure DevOps Repo

### ISSUE THREAD

**Issue by stefania-santimbrean** [a85/POSTMan-Chrome-Extension#10511]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

Hello,

I was looking for a way to version my collection in an Azure DevOps repository so I followed this issue #10280 and tried now to do it. I see we need to version an API and link a collection to that API, which is what I did, but I encounter an issue with versioning the collection because of the Git conflicts. I am not able to Push the changes in the collection.

Am I missing something? Is it not possible to version the collection like this?

Looking forward to some help with this,
Kind regards,
Stefania

P.S.: Many thanks for the integration with DevOps Repos!

### Steps To Reproduce

1. Followed these steps to create an API: https://learning.postman.com/docs/designing-and-developing-your-api/creating-an-api/
2. Followed these steps to connect to my Azure DevOps Repository: https://learning.postman.com/docs/designing-and-developing-your-api/versioning-an-api/#connecting-a-repository
3. Create a Collection to version it, steps shown with screenshots below.

### Screenshots or Videos

2. Connecting to my Azure DevOps repository
![image](https://user-images.githubusercontent.com/74544010/146906895-0b829bd4-b667-4c95-98ec-22769b11e1ff.png)
3. Press on Generate Collection
![image](https://user-images.githubusercontent.com/74544010/146907249-f46a3e99-e192-4c5f-a373-905c2b5b1b97.png)
4. Then again on Generate Collection:
![image](https://user-images.githubusercontent.com/74544010/146907331-8a42e10c-0a6a-45a8-8da4-b62325967247.png)
5. Postman collection generate successfully:
![image](https://user-images.githubusercontent.com/74544010/146907880-6fe89d8e-1cba-4798-847c-a2bb61978d6b.png)
6. Press on Commit and push
![image](https://user-images.githubusercontent.com/74544010/146907965-f630aa1e-1f6a-4c30-8a00-da1e1e01de99.png)
7. Add commit message and press on Commit and push changes:
![image](https://user-images.githubusercontent.com/74544010/146908075-d8048f07-4566-494b-a4c3-42172bb5e8d7.png)
8. Delete one test from there:
![image](https://user-images.githubusercontent.com/74544010/146908222-62bbd2fa-79a1-4614-9a5d-5c0722fb6d34.png)
9. Go to versioning and press again on Commit and push changes, but prompted to Pull changes first, so press on Pull changes:
![image](https://user-images.githubusercontent.com/74544010/146908332-f6e4888d-f41f-4d46-ac77-788f623905fc.png)
10. Select Keep local file and press on Pull Changes:
![image](https://user-images.githubusercontent.com/74544010/146908456-c879f1ee-409a-48b4-a737-0d56f1955bb7.png)
11. Successfully pulled changes appears and I see 1 commit in versioning, but the push was not executed:
![image](https://user-images.githubusercontent.com/74544010/146908832-2d98dc4d-ff6f-4cc0-86b1-7bf59eb22108.png)
I can see in Postman just the initial commit of the Postman collection
![image](https://user-images.githubusercontent.com/74544010/146908934-5911e345-b659-4f43-944f-e1b7291fd753.png)
12. Tried to also repeat the process but again it tells me to Pull and the Push is not executed afterwards. And the pop-up automatically closes.

### Environment Information

```markdown
- Operating System: macOS Big Sur
- Platform Type: Native App
- Postman Version: 9.6.0
```

**Comment by shashankawasthi88** [comment]
@stefania-santimbrean thanks for raising the issue. We are looking into it and shall respond on the same thread soon.

**Comment by abhijitkane** [comment]
@stefania-santimbrean This should be addressed now - pull/push operations should work as intended.

**Comment by stefania-santimbrean** [comment]
> @stefania-santimbrean This should be addressed now - pull/push operations should work as intended.

@abhijitkane many, many thanks. I can confirm in 9.6.1 the issue is resolved! :D

Thanks for the quick fix!
Kind regards,
Stefania
