### ISSUE TITLE
Auto detect gRPC service and method if gRPC server reflection is open

### ISSUE THREAD

**Issue by Halimao** [a85/POSTMan-Chrome-Extension#10524]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request

### Is your feature request related to a problem?

Auto detect gRPC service and method if gRPC server reflection is open

### Describe the solution you'd like

If gRPC server reflection is open, after filling the grpc server url, auto detecting the gRPC server and method

**Comment by arsotirchellis** [comment]
+1.  In order for a grpc gui tool to be useful it needs to support reflection and auto detect proto definitions

**Comment by codenirvana** [comment]
@arsotirchellis we've already started working on adding support for server reflection and it will be released in a few days 🤞🏻

Stay tuned!

**Comment by aditanase** [comment]
@codenirvana Just saw this in 9.9.0 update, was super excited. It seems to be working at a general level, however on our backend I'm only seeing 2 out of 15+ services detected. Not sure how those specifically got selected.
Tested side by side with GrpcUI which shows everything correctly.

**Comment by aditanase** [comment]
Added https://github.com/postmanlabs/postman-app-support/issues/10569

**Comment by appurva21** [comment]
Hey everyone!

Really appreciate the early feedback and we are glad to let you know that Postman now supports Server Reflection in gRPC requests.

**To get started**:
1. Open gRPC request
2. Enter server URL
3. In the adjacent dropdown, select the "More ways to load services and methods" -> "Use server reflection"

![server reflection](https://user-images.githubusercontent.com/24985700/149727738-310259e2-027a-451d-afd6-68f6ca0e5ed8.gif)

Give it a whirl and let us know your thoughts.

I'll be closing out this issue but feel free to file a new issue in case you encounter a bug or have some feedback for us. Thanks!
