### ISSUE TITLE
JSON numbers are truncated to integers in pretty mode

### ISSUE THREAD

**Issue by adam-vioozer** [a85/POSTMan-Chrome-Extension#1052]
# The problem

The following raw output:
![screen shot 2015-05-07 at 21 50 53](https://cloud.githubusercontent.com/assets/6304466/7523256/39af7568-f503-11e4-8a49-4005a2df58f4.png)

Is converted to rounded-down integers in pretty format:
![screen shot 2015-05-07 at 21 50 42](https://cloud.githubusercontent.com/assets/6304466/7523255/39aa8ff8-f503-11e4-9cc5-230df636c108.png)
# Steps to reproduce:

Call https://storage.googleapis.com/maps-devrel/google.json and show the output in raw and pretty modes.

**Comment by abhijitkane** [comment]
@adam-vioozer Can you confirm this fixed in v3.0.4?
