### ISSUE TITLE
Make Postman Desktop version easier to see.

### ISSUE THREAD

**Issue by ebebpl** [a85/POSTMan-Chrome-Extension#10527]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request

### Is your feature request related to a problem?

I clicked all the Desktop menus but nowhere I could see the installed version. Since I wait for major version releases before upgrading so will be helpful to know current installed version. 
Update: Found version number under Settings->About. But still maybe helpful to have under Help->About.

### Describe the solution you'd like

Most software usually show installed version in Help->About but its not there in Postman.

**Comment by timothydillan** [comment]
The option exists on the latest version of Postman. 
<img width="689" alt="Screen Shot 2021-12-30 at 13 50 40" src="https://user-images.githubusercontent.com/88418007/147725288-1ef7a9fa-3953-48ac-8eb9-be3bea33f6de.png">

**Comment by ebebpl** [comment]
Thanks for the info!
