### ISSUE TITLE
Postman Code Dart Dio Library

### ISSUE THREAD

**Issue by TorbenHammes** [a85/POSTMan-Chrome-Extension#10521]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request

### Is your feature request related to a problem?

No, there is no problem.

### Describe the solution you'd like

Ich habe gesehen, dass es im Code-Generator dart/http gibt, jedoch wäre es großartig, eine dart/dio Integration zu haben.
https://pub.dev/packages/dio 

Vielleicht ließe sich das noch einrichten :-D 

Grüße aus Berlin.

**Comment by aman-v-singh** [comment]
Codegen support for Dart-Dio will be [available](https://github.com/postmanlabs/postman-code-generators/pull/710) in Postman App with July Release.
