### ISSUE TITLE
Don’t expand request when clicking on name

### ISSUE THREAD

**Issue by SimonVillage** [a85/POSTMan-Chrome-Extension#10525]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request

### Is your feature request related to a problem?

The sidebar with the requests should provide a clear overview of all the requests in a collection.

<img width="279" alt="image" src="https://user-images.githubusercontent.com/1446685/147646557-53796a16-c778-4135-9378-de3ad2c1f61d.png">

When clicking on the name of a requests, this requests expands if any response is saved within this requests which makes it confusing and hard to keep track of the requests.

<img width="279" alt="image" src="https://user-images.githubusercontent.com/1446685/147646617-21442fa0-9402-4636-8e29-244ff5c1ad38.png">

### Describe the solution you'd like

It would be better if the requests only expands if the chevron on the left is clicked.

### Additional context

https://user-images.githubusercontent.com/1446685/147646702-4a4e8ca9-1815-4238-bdf0-4a369eb3e76b.mov

**Comment by giridharvc7** [comment]
@SimonHausdorf 
Can you elaborate on this, please 

> this requests expands if any response is saved within this requests which makes it confusing and hard to keep track of the requests.

**Comment by SimonVillage** [comment]
If you have a response saved under a request, it will expand if you click either onto the request name or the chevron. However, to collapse it you can only click on the chevron.

If you just want to go through a few requests without checking the saved responses, then you expand them right away when clicking on their name.

I think there are two good solutions for this:

1. Expand and collapse the saved responses only if the chevron is clicked
2. Expand the saved responses once the request is clicked and collapse them if unfocused.

**Comment by aefendim** [comment]
Another solution would also be to only expand on double click, like you would open a folder.

**Comment by giridharvc7** [comment]
Requests don't open by default anymore. To view the examples, you'll need to explicitly select the arrow/chevron. 
Let me know if this works for you. Closing this issue for now.
