### ISSUE TITLE
Support using server certificate for gRPC

### ISSUE THREAD

**Issue by amirmd76** [a85/POSTMan-Chrome-Extension#10533]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request

### Is your feature request related to a problem?

Right now you'd have to add the certificate of the server to the Certificates to be able to use TLS alongside gRPC, otherwise getting "13 INTERNAL" error. This become a pain specially when using Lets Encrypt certificates which have to be updated every 90 days.

### Describe the solution you'd like

It'd be nice to be able to use the certificate provided by the server automatically, like in [BloomRPC](https://github.com/bloomrpc/bloomrpc).

**Comment by leftbin-swarup** [comment]
also it should be possible to disable hostname verification to support private certificates which is not supported in [BloomRPC](https://github.com/bloomrpc/bloomrpc) but is supported in [Wombat](https://github.com/rogchap/wombat)

**Comment by korotin** [comment]
@amirmd76 you don't have to add server's certificate to Postman, just add [LE root certificate](https://letsencrypt.org/certificates/) (I added self-signed one, it's really doesn't matter here). That way you don't need to update certificate in Postman every 3 months.

**Comment by amirmd76** [comment]
@korotin That's not really a neat workaround, it'd be great if Postman added support for this feature like BloomRPC or other gRPC GUI clients (like Kreya).

**Comment by korotin** [comment]
@amirmd76 can't argue with that.

But it's worth to mention that BloomRPC have exactly the same [issue](https://github.com/bloomrpc/bloomrpc/issues?q=is%3Aissue+is%3Aopen+let%27s+encrypt)  with at least some of LE certs. You're lucky if BloomRPC works well for you :)

**Comment by Breefield** [comment]
Having this issue as well, unable to use a self-signed certificate it seem 🤔

**Comment by larsduelfer** [comment]
Same problem here, a solution for this would be awesome!

**Comment by moshest** [comment]
Just want to share that **gRPCurl** solves it with a single `-plaintext` flag indicate if the connection should be TLS or not: https://github.com/fullstorydev/grpcurl#invoking-rpcs


**If anyone still try to figure out how to setup postman with self-signed certificate:**
1. Generate a self-signed certificate:
```
openssl req -x509 -nodes -days 5000 -subj '/CN=localhost' -newkey rsa:2048 -keyout client.key -out client.crt
```
2. Open postman settings >> Certificates
3. Add new certificate with the hostname and the port you're trying to connect 
4. Select `client.crt` and `client.key` for CRT and KEY files
5. Save

I hope it helps!

**Comment by sharooksubana** [comment]
> Just want to share that **gRPCurl** solves it with a single `-plaintext` flag indicate if the connection should be TLS or not: https://github.com/fullstorydev/grpcurl#invoking-rpcs
> 
> **If anyone still try to figure out how to setup postman with self-signed certificate:**
> 
> 1. Generate a self-signed certificate:
> 
> ```
> openssl req -x509 -nodes -days 5000 -subj '/CN=localhost' -newkey rsa:2048 -keyout client.key -out client.crt
> ```
> 
> 2. Open postman settings >> Certificates
> 3. Add new certificate with the hostname and the port you're trying to connect
> 4. Select `client.crt` and `client.key` for CRT and KEY files
> 5. Save
> 
> I hope it helps!

Even after giving the self-signed certificate 
It's throwing an error **"The service is currently unavailable. Make sure you are using the correct URL and have the certificates configured (if required)."**

**Comment by moshest** [comment]
@sharooksubana what's the error details you see? Note that you shouldn't add "https://" or any other protocol to the url, just "hostname:port".


You can also verify with **gRPCurl** that the server is working properly.

**Comment by sharooksubana** [comment]
> @sharooksubana what's the error details you see? Note that you shouldn't add "https://" or any other protocol to the url, just "hostname:port".
> 
> You can also verify with **gRPCurl** that the server is working properly.

@moshest thanks for the replay,
I have not added "https://"  or any protocol to the URL this is the URL I had given **"localhost:5001"**, I also verified using gRPCurl there it is working fine.
Below is the error I saw in postman
**The service is currently unavailable. Make sure you are using the correct URL and have the certificates configured (if required).** and status code is 14 UNAVAILABLE

**Comment by codenirvana** [comment]
@sharooksubana @moshest we've simplified the TLS configuration flow and I hope that will fix your issue.

The fix will be available soon in Postman v9.25, here's a sneak peek:

![Screenshot 2022-07-08 at 10 52 05 AM](https://user-images.githubusercontent.com/4865836/177922544-a1690989-7e1f-481b-8c8a-77556dc829a7.png)

**Comment by sharooksubana** [comment]
@codenirvana , what about invoking the method using a secured connection does a self-signed certificate doesn't work for invoking a method

**Comment by codenirvana** [comment]
@sharooksubana self-signed certificates will work the same way, you can optionally enable server certificate verification (requires CA to be configured).

I will share more details after the release, stay tuned!

**Comment by sharooksubana** [comment]
> @sharooksubana @moshest we've simplified the TLS configuration flow and I hope that will fix your issue.
> 
> The fix will be available soon in Postman v9.25, here's a sneak peek:
> 
> ![Screenshot 2022-07-08 at 10 52 05 AM](https://user-images.githubusercontent.com/4865836/177922544-a1690989-7e1f-481b-8c8a-77556dc829a7.png)

hi @codenirvana, I just updated the postman, and now it's working but I wanted to know what exact changes were done are you internally passing any postman certificate for establishing a secure connection?

**Comment by codenirvana** [comment]
@sharooksubana glad it worked for you!
No, we're not adding any special certificate. The issue was that the intent to establish a TLS connection was not obvious.

---

Now, you can toggle the lock icon to specify the server's connection preference (TLS or plaintext):

![Screenshot 2022-07-30 at 11 02 59 PM](https://user-images.githubusercontent.com/4865836/181935198-ee83a883-bc24-4272-b183-643b16813910.png)

For self-signed certificates, we skip certificate verification by default which you can optionally enable via request settings:

![Screenshot 2022-07-30 at 11 04 08 PM](https://user-images.githubusercontent.com/4865836/181935255-92e2c68b-ec89-40be-9ce3-7c9cdd20aaac.png)

When server certificate verification is enabled for self-signed certificates, you need to add the custom CA in Settings:

<img width="741" alt="Screenshot 2022-08-01 at 11 27 46 AM" src="https://user-images.githubusercontent.com/4865836/182082197-c338b6e3-bf94-4a2a-8536-c8fb9b7de14e.png">

Finally, for mTLS connection you can configure client certificates for the server in Settings:

![Screenshot 2022-07-30 at 11 06 11 PM](https://user-images.githubusercontent.com/4865836/181935353-e3ebbb78-494c-4983-ace6-f7e10b9de2a1.png)

I hope most of the use cases got unblocked with the latest release.
If you still face any issues connecting to your gRPC server, feel free to raise a new bug report.

**Comment by Breefield** [comment]
Hey @codenirvana I appreciate your help on this issue!
I still have a frustration with the self-signed certificate solution.

I need to connect to many different hosts (50+), and if setting up a self-signed cert for TLS then you have to add each host + certs in the preferences. If Postman could use the certificate provided by the server automatically then no configuration step would be needed at all.

**Comment by codenirvana** [comment]
@Breefield host + certs are needed only for mTLS connections, for a regular TLS connection with a self-signed cert you don’t have to configure anything.

Please let me know if I misunderstood your use case.
