### ISSUE TITLE
Error parsing JSON: undefined

### ISSUE THREAD

**Issue by jacob-israel-turner** [a85/POSTMan-Chrome-Extension#1053]
Whenever I try to send back a boolean `false` value in JSON format, I receive the following error:

![JSON error](http://i1383.photobucket.com/albums/ah307/JIsraelTurner/Selection_028_zpsxr2bichi.png)

When I return boolean `true` value, I don't receive the error.

I'm using a Node/Express/Mongo backend.

**Comment by abhijitkane** [comment]
Thanks for pointing this out - we'll fix this in the next release.

**Comment by abhijitkane** [comment]
@jacob-israel-turner Can you confirm this fixed in v3.0.4?

**Comment by jacob-israel-turner** [comment]
@abhijitkane Sorry for the late response, crazy week.  I can't remember the exact original context, but I just tested receiving false in every imaginable way and they were all handled correctly.  Looks good! :+1:
