### ISSUE TITLE
Feature request: Make Collection Documentation SEO Friendly

### ISSUE THREAD

**Issue by Lincimary** [a85/POSTMan-Chrome-Extension#10539]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request

### Is your feature request related to a problem?

There is a problem with generating Postman API docs, since Postman takes collection description as markdown text, and puts all text in description meta tag (HTML -> head -> meta tag), there is no way to set the content of that tag.

We do not have a feature in postman to take the whole collection description as content of the tag. It is not SEO-friendly.

### Describe the solution you'd like

Sorry that we do not have this option for the moment to make Collection Documentation SEO Friendly.

**Comment by arlemi** [comment]
We've added the ability to add SEO metadata in the latest version of Postman (v10.13), try it out! 

More info here: https://learning.postman.com/docs/publishing-your-api/publishing-your-docs/#making-your-documentation-public
