### ISSUE TITLE
Find and Replace Doesn't Replace

### ISSUE THREAD

**Issue by DavidDeks** [a85/POSTMan-Chrome-Extension#10537]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

Find and Replace isn't replacing values.

### Steps To Reproduce

1. Select "Find and Replace" from the bottom left
2. Enter a search term in "FIND"
3. Select a Collection under "Choose entities to find in" (Currently selecting "Everything" doesn't work for me. Similar to issue [10496](https://github.com/postmanlabs/postman-app-support/issues/10496), even though upgrading their Postman version solved their issue, it still doesn't work for me).
4. Select "Find" button
5. Enter term under "REPLACE WITH"
6. Check "Select all".
7. Select "Replace in ## selected" button
8. Open one of the requests to verify the value was not replaced.

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/53012236/147998986-3021804e-3f71-4cb4-a021-d54acea158bc.png)

### Environment Information

```markdown
- Operating System: macOS BigSur 11.6.2
- Platform Type: Desktop Application
- Postman Version: 9.7.1
```

**Comment by p6345uk** [comment]
Still broken for me in windows version too

**Comment by DavidDeks** [comment]
Clearing my local data fixed this issue for me.
See: https://support.postman.com/hc/en-us/articles/4410785125271#h_01FJBXQM8B6RXQB09WVECY2V85
