### ISSUE TITLE
Add support for googleapis protobufs in gRPC

### ISSUE THREAD

**Issue by amirmd76** [a85/POSTMan-Chrome-Extension#10532]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request

### Is your feature request related to a problem?

Right now we need to download the googleapis protobuf defenitions and put it next to the proto files in order to use it. (For example: [annotations.proto](https://github.com/googleapis/googleapis/blob/master/google/api/annotations.proto)). Even then it wouldn't work properly since the annotations.proto itself is importing `google/api` and thus needs the `google/api` directory inside `google/api` directory (or a symlink).

### Describe the solution you'd like

It's be great to support this builtin. Or at least support having an artifactory for frequently-used proto files.

**Comment by codenirvana** [comment]
@amirmd76 you can now specify the `google/api` directory as an "Import path" to fix this issue, refer to https://github.com/postmanlabs/postman-app-support/issues/10547#issuecomment-1062765631.

Can you update your app and confirm if this fixes your issue?

---

Postman v9.16 and above have in-built support for the following well-known Protobufs:

```
- google/api/annotations.proto
- google/api/http.proto
- google/protobuf/api.proto
- google/protobuf/descriptor.proto
- google/protobuf/source_context.proto
- google/protobuf/type.proto
- google/protobuf/any.proto
- google/protobuf/duration.proto
- google/protobuf/empty.proto
- google/protobuf/field_mask.proto
- google/protobuf/struct.proto
- google/protobuf/timestamp.proto
- google/protobuf/wrappers.proto
```
