### ISSUE TITLE
gRPC Should support Pre-request and Test scripts (at least for unary requests)

### ISSUE THREAD

**Issue by uschwag** [a85/POSTMan-Chrome-Extension#10534]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request

### Is your feature request related to a problem?

In many situation it is either necessary to set result data to a variable or to get data from a variable to provide it as input to the next result. E.g. A Login requests provides a session id which following requests need to provide.  

### Describe the solution you'd like

Best would be a similar way as Postman (and Newman) use for all other kinds of requests.

### Additional context

Requests need to be saved for this as the "coming soon" which isn´t possible so far.

**Comment by appurva21** [comment]
Hey @uschwag!

With the latest release of Postman, you can now add scripts to your gRPC requests. Head to our [Learning Center](https://go.pstmn.io/docs-grpc-scripts) to know more.
![navigating-to-grpc-scripts](https://user-images.githubusercontent.com/24985700/185069734-522a4d31-0d1e-4531-982e-fd743b7a5bb5.gif)

**Comment by bzaruk** [comment]
@appurva21 - for some reason I am able to run a Pre-request script and set up a Collection Variable (for setting up a token) for REST request, but when I have the same script run as a `Before Invoke` script in a gRPC request it fails with the error message of:
```
code: "ECONNRESET"
name: "Error"
message: "socket hang up"
stack: "Error: socket hang up
    at connResetException (node:internal/errors:691:14)
    at TLSSocket.socketOnEnd (node:_http_client:471:23)
    at TLSSocket.emit (node:events:402:35)
    at TLSSocket.emit (node:domain:475:12)
    at endReadableNT (node:internal/streams/readable:1343:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)"
```

Do you have any idea why?

**Comment by uschwag** [comment]
@bzaruk sorry no idea, think you should open a new request for this issue.
