### ISSUE TITLE
Search in requests' urls for a keyword

### ISSUE THREAD

**Issue by ghost** [a85/POSTMan-Chrome-Extension#10531]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request

### Is your feature request related to a problem?

Knowing the url of an API in an app, I can't search in Postman for requests that call this API by searching for a keyword from the API's url. 

### Describe the solution you'd like

I want the search feature to also search the requests' urls. If Postman is searching titles only, that's not good enough. Users can enter anything for a title which makes searching based on title not dependable. URLs are a lot more dependable because only a specific url can be used. Not anything like the request's title.

### Describe alternatives you've considered

Exporting the collections and searching the exported files.

**Comment by giridharvc7** [comment]
@thenrich2009 Just to confirm, you are doing this on `1` and not on `2` ?
<img width="978" alt="Screenshot 2022-01-03 at 2 50 11 PM" src="https://user-images.githubusercontent.com/1040583/147918282-a5bc5778-21d1-4d41-9eb7-7242ba90e878.png">

**Comment by ghost** [comment]
I was using 1. I used 2 and got some results but when I click on the title which is hyperlinked, it doesn't go to that request. Nothing happens. Shouldn't it jump to that request?
My workaround is to copy the title from the result of 2 and paste it in 1 to find the requests.

**Comment by aravind-arun** [comment]
We are sorry for the experience that you had. Can you help us reproduce this issue. The universal(global) search bar on the Postman header has the ability to search for any text in the  request URL (Ctrl + K is the shortcut). We also have filters in the universal search bar to filter the search results to show only requests.
<img width="1512" alt="request-path-search" src="https://user-images.githubusercontent.com/119476416/211786966-387b2d99-1b3d-4969-97b0-2c63288707e1.png">

**Comment by ranjan-sh** [comment]
The search dropdown (number 2) supports request URL search, along with filters. Closing the issue.
