### ISSUE TITLE
"GET /collections" is not listing all collections from all workspaces

### ISSUE THREAD

**Issue by valentinbeggi** [a85/POSTMan-Chrome-Extension#10535]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

When using Postman API's "GET /collections" request, only collections from 2 out of ~10 workspaces are retrieved.

Details:

We have built a CI/CD extensively using Postman monitoring features and the 6 developers of our team each have their own workspace. There is a Master Workspace from which collections are automatically forked, on new git branch creation, to dev workspace. CI/CD has Admin rights on each developer's workspace.
At some point of the dev workflow we make a GET call to `https://api.getpostman.com/collections` in order to get a list of all collections from all workspaces. However, the response we receive only shows the collections from the Master workspace and from one of the Dev's workspace (X). If another dev (Y) makes the call, he will still only be able to list Master workspace collections and X's collections.

We are currently tackling this issue by only using two workspaces: Master and X, but this fix is really inconvenient, and since the team is growing fast it will only be worse.

### Steps To Reproduce

1. Create ~10 workspaces including a Master workspace with ~10 collections.
2. Create forks of Master collections with the API on all other workspaces, (we are using the following code to do so)
```ts
const url = new URL(POSTMAN_BASE_URL);
  url.pathname = ["/collections/fork", collectionId].join("/");
  url.searchParams.append("workspace", workspaceId);

  const response = await fetch(url.href, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      "X-Api-Key": postmanAPIKey,
    },
    body: JSON.stringify({ label }),
  });

```
3. Try to list collections, only the collections coming from 2 workspaces should be retrieved (we are using the following code to do so)
```ts
  const listCollectionsUrl = new URL(POSTMAN_BASE_URL);
  listCollectionsUrl.pathname = "/collections";

  const listCollectionsResponse = await fetch(listCollectionsUrl.href, {
    method: "GET",
    headers: {
      "Content-Type": "application/json",
      "X-Api-Key": postmanAPIKey,
    },
  });
```

### Environment Information

```markdown
- Operating System: MacOS
- Platform Type: Postman API
- Postman Version: 9.71
```

**Comment by bpedro** [comment]
Hi @valentinbeggi,

Thanks for reporting this issue in great detail.

We're currently triaging it and I'll get back to you soon with more details.

**Comment by bpedro** [comment]
@valentinbeggi, I wasn't able to reproduce the issue you describe in my setup.

Can you provide the following details?

- Are each of the developers able to access each other's workspaces and the collections therein?
- Is the `GET /collections` request made by each of the developers using their Postman API keys, or is the request made by your CI/CD process using its own Postman API key?
- What happens when you make a `GET /workspaces/{workspaceId}` request to one of the devs workspaces? Can you read the workspace and get the list of collections inside?

Thanks.

**Comment by olivermonaco** [comment]
I am currently experiencing this issue. What is the criteria for "The /environments endpoint returns a list of all environments that belong to you.."? I tried subscribing and watching multiple collections that I have access to, but can only access one collection. Thanks in advance

**Comment by shubhbhargav** [comment]
@olivermonaco Can you please reach out to us via `help@postman.com` and share more details about the issue, specifically around which collection are you unable to access via the `GET /collections` endpoint?

**Comment by bpedro** [comment]
More relevant information has been shared on https://github.com/postmanlabs/postman-app-support/issues/10617
