### ISSUE TITLE
GRPC  `Couldn't import protobuf definition`

### ISSUE THREAD

**Issue by ryan961** [a85/POSTMan-Chrome-Extension#10530]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

![image](https://user-images.githubusercontent.com/32825698/147735755-e0f5566c-e358-4be2-ad7c-91973d5620c4.png)
![image](https://user-images.githubusercontent.com/32825698/147735780-5de0885b-aad1-4a48-ae21-bcdb610abe37.png)
how can i make it work?

### Steps To Reproduce

![image](https://user-images.githubusercontent.com/32825698/147735914-31a646b8-67f0-4917-b977-d75005e0d76d.png)

### Environment Information

```markdown
- Operating System: 
- Platform Type: 
- Postman Version:
```

**Comment by shamasis** [comment]
Just a quick precursory set of questions before the rest of the team deep dives in your issue? Is it only this protofile that fails to open or every protofile results in this error? Can you try putting a proto file in your documents directory that has full filesystem permissions and attach that?

**Comment by ryan961** [comment]
> Just a quick precursory set of questions before the rest of the team deep dives in your issue? Is it only this protofile that fails to open or every protofile results in this error? Can you try putting a proto file in your documents directory that has full filesystem permissions and attach that?

Thank you for reply. It looks like he can't load the `import ...` path in the file.
![image](https://user-images.githubusercontent.com/32825698/147808964-1c8d76b9-182b-4f7c-87e2-ac1c16e6c593.png)
But it is not a necessary option for functionality，can add options for `mark directory as resource root` like it?
![image](https://user-images.githubusercontent.com/32825698/147809130-1ef51b3e-83e5-4532-be63-1d6cfdbd26ce.png)

**Comment by zeesattar** [comment]
+1

**Comment by RichurLiu** [comment]
I have the same problem.

**Comment by cliffliang** [comment]
Seeing the same. We use BloomRPC that allows you to specify import paths where you have common protos in a different base path that are imported by others. Similar to what Ryalu is suggesting with marking directories as resource roots.

As a followup, it'd be great when selecting a method that the message field is pre-populated with a sample message. Maybe with a warning that existing text will be replaced.

**Comment by aditanase** [comment]
Same here, although wanted to make sure you are considering multiple roots as part of this effort, our protos are split across 2 packages (internal and public, with internal depending on public).

**Comment by maaland** [comment]
Seeing the same with an `import "validate/validate.proto";` from a directory outside of the repository.

**Comment by jankrynauw** [comment]
#10547 related with a few more examples on how **Import Paths** are handled in other applications.

**Comment by codenirvana** [comment]
Duplicate of #10547

With the latest version of the Postman app, you can now specify the "Import paths" along with the root proto file.

![Screenshot 2022-03-09 at 3 33 31 PM](https://user-images.githubusercontent.com/4865836/157595174-4ad997ac-ba03-4e7e-8622-7321f0f725ba.png)

Please update your app and share the feedback.

**Comment by Vadzimkuzmenka94** [comment]
I solved this problem by using BloomRPC.
Initially, this application also did not want to work, but to solve the problem I had to click on import path and specify the path to the "protos" folder, one step back from it (in my case). In reality, the file is located at .../main/protos/shared
![image](https://github.com/postmanlabs/postman-app-support/assets/85760475/27d493e4-00ac-433e-85aa-78aab37e5532)
![image](https://github.com/postmanlabs/postman-app-support/assets/85760475/1af69f73-5e5a-4851-ba3e-aad1d3bde19d)
![image](https://github.com/postmanlabs/postman-app-support/assets/85760475/5bd3a112-ec13-4d32-ac70-6414a71daf2d)
