### ISSUE TITLE
Duplicating request in subfolder, duplicates wrong request

### ISSUE THREAD

**Issue by KotieSmit** [a85/POSTMan-Chrome-Extension#10542]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

I have requests in subfolders upto 3 levels deep.

When I try to duplicate a request in a sub folder, it duplicates the wrong request

        
       See screenshots and video

### Steps To Reproduce

example:

```
root
|_ folder1 
   | - sub_folder_1 
                              - request 1
                              - request 2
   |_ sub_folder_2
        |_ sub_sub_folder_1 
                                           - request 3
```
        In above example, duplicating request 3, creates a duplicate of request 1, where the name is correct, but the contents is equal to request 1
<img width="1304" alt="Screenshot 2022-01-05 at 15 42 19" src="https://user-images.githubusercontent.com/2812182/148227590-820e95ec-a5e1-4f1d-b233-f383ccc7a546.png">
![Uploading Screenshot 2022-01-05 at 15.41.33.png…]()

### Screenshots or Videos

<img width="1222" alt="Screenshot 2022-01-05 at 15 40 53" src="https://user-images.githubusercontent.com/2812182/148227604-b636f377-16e8-48f3-889b-d60500c03169.png">
<img width="1304" alt="Screenshot 2022-01-05 at 15 42 19" src="https://user-images.githubusercontent.com/2812182/148227644-a346a29a-5f36-4e78-92a2-34e510fd4e1d.png">
<img width="1409" alt="Screenshot 2022-01-05 at 15 41 33" src="https://user-images.githubusercontent.com/2812182/148227653-aec827ff-ae82-4cc5-9fec-b447520fcf9f.png">
<img width="1222" alt="Screenshot 2022-01-05 at 15 40 53" src="https://user-images.githubusercontent.com/2812182/148227657-754968eb-db0b-4be6-85cf-8d39ac8ad53a.png">

https://user-images.githubusercontent.com/2812182/148228049-e5f993cd-8a90-4ba2-b5a3-424b90c9162a.mov

### Environment Information

```markdown
- Operating System: MacOS Montery
- Platform Type: Native
- Postman Version: 9.3.1
```

**Comment by DannyDainton** [comment]
Hey @KotieSmit 

It looks like you have many tabs with unsaved changes (the orange dot on the tab) - Could you save all of your work/changes in the Colleciton and then run through the steps again, to see if that solves this issue, please?

**Comment by KotieSmit** [comment]
@DannyDainton 

I did as requested.

The problem does not happen anymore.

Thank you for the very fast response.

If you feel this not a non issue, feel free to close.

**Comment by DannyDainton** [comment]
Awesome. The video helped as I could see the full app window. The static images didn't show the tab state.

If you have a request saved and then you make changes to it - You're duplicating the saved request, rather than the one with unsaved changes.
