### ISSUE TITLE
Environment change does not update Code snippets on the right hand side 

### ISSUE THREAD

**Issue by Cazaimi** [a85/POSTMan-Chrome-Extension#10546]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

In the Postman app, Changing the active environment when the code snippet view of a request is open does not update the code snippet with the new environment. The code snippet view needs to be closed and reopened again to bring that change into effect. 

### Steps To Reproduce

Pre-requisites 
- A request with an environment variable 
- Two different environments containing that variable, with ideally different values

Steps 
1. Select environment-1
2. Open the code snippet view for the request 
3. Change the environment to environment-2
4. The code snippet does not get updated with the latest environment values 

### Screenshots or Videos

https://user-images.githubusercontent.com/13660453/148388156-f4ac7c50-a2c5-4a07-9230-83fce23dd62a.mov

### Environment Information

```markdown
- Operating System: Mac OS Monterey Version 12.1
- Platform Type: Native App and Postman Web
- Postman Version: Version 9.6.1 (9.6.1)
```

### Additional Context?

Ideally, the code snippets should update dynamically and a user should not have to click around more than that, which is necessary.

**Comment by NileshMSD** [comment]
This is working as a part of the May 2023 release. Thank you @shubhbhargav and Postman team.
