### ISSUE TITLE
403 Forbidden error

### ISSUE THREAD

**Issue by gauravpunj14** [a85/POSTMan-Chrome-Extension#10541]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

GET token request working - ending with status code 200
POST request to server failing with status 403

Same POSTMAN user for the same POST request is working at different IP / location. 

what could be possible reason for the same?

### Steps To Reproduce

Can't share

### Screenshots or Videos

Can't share

### Environment Information

```markdown
Json payload
```

### Additional Context?

Nothing

**Comment by shubhbhargav** [comment]
Hey @gauravpunj14, can you please reach out to us with more details on `help@postman.com`? Following would help debug the issue further:

1. Is this a Postman API call that is failing or an endpoint that you own?
2. If possible, can you please share a video with the behaviour mentioned above?

----
In-case the endpoint is owned by you, you can check the security configuration of the server where it is hosted. It might be allowing only specific IPs / locations to have access. Also if you are using a VPN, maybe try once with a disabled VPN.

**Comment by shubhbhargav** [comment]
@gauravpunj14 I am closing this ticket as of now. Please feel free to let us know if you are still facing the issue. We will re-open the ticket and debug / resolve accordingly.
