### ISSUE TITLE
Does "Concatenate Block" can be a multiple input block, that has more than two inputs ?

### ISSUE THREAD

**Issue by Feixu2015** [a85/POSTMan-Chrome-Extension#10548]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request

### Is your feature request related to a problem?

When I need run some parallel api, then I need wait all of them done. Does "Concatenate Block" match this need? Otherwise, are you plan to support this feature?

### Describe the solution you'd like

match the need I described

**Comment by saswatds** [comment]
Hey @Feixu2015 , thanks a lot for trying out Flow. I had tried answering this in one of our discussions https://github.com/postmanlabs/postman-flows/discussions/105#discussioncomment-1721429 Have a look if this is helpful, else I will be glad to help you out with your usecase

**Comment by Feixu2015** [comment]
> Hey @Feixu2015 , thanks a lot for trying out Flow. I had tried answering this in one of our discussions [postmanlabs/postman-flows#105 (reply in thread)](https://github.com/postmanlabs/postman-flows/discussions/105#discussioncomment-1721429) Have a look if this is helpful, else I will be glad to help you out with your usecase

Thanks a lot, I would try it.
