### ISSUE TITLE
Why not do a Windows client

### ISSUE THREAD

**Issue by tonycody** [a85/POSTMan-Chrome-Extension#1054]
Why not do a Windows client

**Comment by a85** [comment]
On the horizon. We will be announcing it soon.

**Comment by tonycody** [comment]
when ?

**Comment by a85** [comment]
Windows native apps are available now:

64-bit: https://dl.pstmn.io/download/latest/win?arch=64
32-bit: https://dl.pstmn.io/download/latest/win?arch=32
