### ISSUE TITLE
Issue being ignored

### ISSUE THREAD

**Issue by TheDirigible** [a85/POSTMan-Chrome-Extension#10545]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

Reposting because this issue is being ignored for years. https://github.com/postmanlabs/postman-app-support/issues/3518#issuecomment-1006511951

### Steps To Reproduce

https://github.com/postmanlabs/postman-app-support/issues/3518#issuecomment-1006511951

### Environment Information

```markdown
- Operating System: 
- Platform Type: 
- Postman Version:
```

**Comment by DannyDainton** [comment]
I've left a [comment on the original issue](https://github.com/postmanlabs/postman-app-support/issues/3518#issuecomment-1006627708) to help us understand the problem, in the latest version of the platform.

**Comment by TheDirigible** [comment]
The original is still closed though, so I fear it will continue to be ignored.

**Comment by codenirvana** [comment]
@TheDirigible re-opened the original issue. 
Can you share the steps we can use to reproduce this issue?
