### ISSUE TITLE
GRPC Allow setting import paths for protobuf files

### ISSUE THREAD

**Issue by JDeuce** [a85/POSTMan-Chrome-Extension#10547]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request

### Is your feature request related to a problem?

When importing a protofile it might contain import statements to reference other proto files.

Those import files will fail to work unless they use absolute paths.

### Describe the solution you'd like

Should be able to specify a list of directories for protobufs to import from and a root directory for protobuf includes.

**Comment by tdarci** [comment]
Our protobuf files are nested in directories. When bringing one of these files into Postman, we encounter this error: `Error: ENOENT: no such file or directory` for all our `import` statements. Seems that we need to be able to set `proto_path` so that Postman can find all these imports. Other ideas?

**Comment by jankrynauw** [comment]
I'm really excited about this gRPC capability!

Looking at the [protoc](https://github.com/protocolbuffers/protobuf#protocol-compiler-installation) compiler, it accepts `--proto-path`, `-IPATH` or simply `-I` which allows one to add the imported protos. 

<img width="544" alt="Screenshot 2022-02-03 at 09 21 57" src="https://user-images.githubusercontent.com/18016598/152298663-67ddc778-0456-4e8b-b26e-016ce1c7aa2b.png">

For example, we use many of the google common protos in our proto files: 
```
syntax = "proto3";

package myapp.v1;

import "google/api/annotations.proto";
import "google/protobuf/empty.proto";
import "google/protobuf/field_mask.proto";
import "google/api/client.proto";
import "google/api/field_behavior.proto";
import "google/api/resource.proto";
import "google/longrunning/operations.proto";
import "google/protobuf/timestamp.proto";
import "google/type/date.proto";
...
```

Most applications making use of gRPC, have an **_Import Paths_** option which allows one to add absolute paths at application level.  Standard practise is to keep a copy of the imported protos in your local development environment.  For example we run the following command to get a local copy of the google common protos (`google/api/...`, `google/type/...`):
`git clone https://github.com/googleapis/googleapis.git $HOME/.../google/proto`

Here a few examples:

**BloomRPC**
--
<img width="729" alt="Screenshot 2022-02-03 at 09 28 43" src="https://user-images.githubusercontent.com/18016598/152299687-a1579598-837b-4dac-ae16-855f0d6ac463.png">

**Goland**
--
![Screenshot 2022-02-03 at 09 30 55](https://user-images.githubusercontent.com/18016598/152299827-18d11a37-5856-46d7-ad54-4358ed0d7d48.png)

**Protoc CLI example** (making use of `-I`)
--
`protoc ... -I=$HOME/.../google/proto -I=$HOME/.../myotherprotos/proto /Users/jankrynauw/.../v1/*.proto`

**Import Paths** is a key component of working with gRPC and protos.

Is there a current workaround or plans to add _**Import Paths**_ capability?

**Comment by andreas-kuoppa** [comment]
I was just looking for this feature @JDeuce described myself. This need to be implemented asap, really important for the grpc functionality of Postman to take off.

**Comment by JoshuaWise** [comment]
Hey everyone, we are actively working on supporting this, and we'll be able to roll it out soon 😌

**Comment by codenirvana** [comment]
Hey everyone 👋🏻

With the latest version of the Postman app, you can now specify the "Import paths" along with the root proto file.

![Screenshot 2022-03-09 at 3 33 31 PM](https://user-images.githubusercontent.com/4865836/157419484-38a6f378-b0af-4cab-90b7-4a85e147fe7a.png)

Please update your app and share the feedback.

**Comment by Alcas1** [comment]
You're unable to save these imports which is very annoying. Not sure if this is planned to be addressed but I couldn't find an issue/ticket for this anywhere

**Comment by codenirvana** [comment]
@Alcas1 can you please report a [new issue](https://github.com/postmanlabs/postman-app-support/issues/new/choose) with more details?
