### ISSUE TITLE
Can't import/export files due to broken system dialogs

### ISSUE THREAD

**Issue by natenho** [a85/POSTMan-Chrome-Extension#10551]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

The screen for importing collection files are showing very strange characters and I'm unable to select a file, it is impossible to distinguish one file from another. Actually any system dialog opened from Postman is broken. I have no trouble with other Electron based apps like Slack for example, only Postman behaves like that.

### Steps To Reproduce

1. Install using `snap install postman`
2. Select File-Import-Upload Files

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/4236481/148608458-ff52903c-87a7-45f4-82e4-7def3547fd63.png)
![image](https://user-images.githubusercontent.com/4236481/148610166-8ea63846-c902-4281-ba25-8d5be4a895da.png)

### Environment Information

```markdown
- Operating System: Linux Mint 20.2
- Platform Type: Native App
- Postman Version: Version 8.12.5
linux 5.13.0-1022-oem / x64
```

### Additional Context?

The system is configured to encrypt user folder, I don't know if there is something related to that, but it is good to mention.

**Comment by postman-staff** [comment]
Hi @natenho ,

Our engineers are currently reviewing the issue, it seems to be occurring with snap installations in certain circumstances, while it's possible this is related to the snap store, we are also checking if there' a culprit on our end.

We noticed that clearing Linux's font cache usually helps in such situations, would you be able to try clearing your front's cache and see whether the issue gets solved:


`sudo rm /var/cache/fontconfig/* `
`rm ~/.cache/fontconfig/* `
`fc-cache -r`

Please let us know how it goes.

via @nasco-a | Postman Support

**Comment by natenho** [comment]
Hi, clearing the font cache worked! Dialog fonts are visible again:

![image](https://user-images.githubusercontent.com/4236481/149636275-a867d76f-40bd-44fa-837a-78defe123c43.png)

Thank you!

**Comment by postman-staff** [comment]
Hello @natenho

Thanks for the update! Great to see that clearing the font cache helped.

As it seems like everything is back into a working state now, I'll go ahead and mark the ticket as solved.

Feel free to reach back in case you need our assistance at any given time.
via @nasco-a | Postman Support

**Comment by se-thomas** [comment]
Hey! I'm still having the same issue after clearing the font cache and reinstalling Postman (via snap)

Postman:
Version 9.31.22
UI Version 9.31.22-ui-221031-1419

Running on:
Ubuntu 22.04.1 LTS (64-bit), 5.15.0-52-generic

**Comment by maktsakalis** [comment]
Hello!
Same here, problem insists even after clearing the font cache and reinstalling Postman (via snap)

Postman:
Version 9.31.0

Running on:
Manjaro Linux 22.0.0  (64-bit), 5.15.78-1

**Comment by lgolubenkobit** [comment]
After clearing font cache i can't see fonts on file's dialog

Postman version 10, installed by snap
Running on Manjaro

**Comment by adamgomes** [comment]
> 

Similar setup here, too. Installed Postman 9.31.0 via snap on Manjaro 22.0.0. Only difference from maktsakalis is I'm on a newer kernel (not that it should matter):
10:21:22 gomer@callisto ~ → uname -r
6.0.11-1-MANJARO

**Comment by abarbosa-godaddy** [comment]
Same issue. Also running on Manjaro.

**Comment by spielcrypto** [comment]
me too same issue in Manjaro

**Comment by psmgeelen** [comment]
Same here! Ubuntu 23.04 Kernel: 6.2.0-20-generic

**Comment by seyfer** [comment]
clearing cache doesn't help on ubuntu 23.04

**Comment by LokeshBoran** [comment]
> @seyfer 

Did you find any solution ? I am also facing same in ubuntu 23.04 
Tried clearing cache, but not worked!

**Comment by jviotti** [comment]
A while ago, we dug into this (see https://github.com/postmanlabs/postman-app-support/issues/10449) and identified that this is an upstream issue with Snaps themselves.

While we cannot fix the issue from our side, there are various workarounds discussed in the Ubuntu issue tracker (https://bugs.launchpad.net/ubuntu/+source/chromium-browser/+bug/1864365 and https://bugs.launchpad.net/snapd/+bug/1877109) that seemed to have worked for other people. Hopefully it gets properly fixed by Snaps themselves at some point!

**Comment by aguiraf** [comment]
Same here,
Postman version 10, installed by snap,
on Ubuntu 23.10

**Comment by seyfer** [comment]
> > @seyfer
> 
> Did you find any solution ? I am also facing same in ubuntu 23.04 Tried clearing cache, but not worked!

I use standalone Postman, which does extract in the directory. 
The downside - there is no quick way to launch it. But the fonts are working.

**Comment by maxidev** [comment]
same issue here ubuntu 24.04

**Comment by lguisadom** [comment]
![image](https://github.com/user-attachments/assets/bc120529-5635-40d3-b261-b753f2939740)
same issue here Ubuntu 22.04.5 LTS

**Comment by bytes-max** [comment]
Problem exists still in 2025 :-)

**Comment by greenorca** [comment]
Same problem. 
Postman Version 10.24.27 (via snap) on Xubuntu 2404.02 

Cleaning the fontconfig caches as described above does not help.
