### ISSUE TITLE
Postman Export Modal Appears Completely Broken in ManjaroLinux

### ISSUE THREAD

**Issue by inf1nite-lo0p** [a85/POSTMan-Chrome-Extension#10557]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the Issue

I just installed the postman snap on Manjaro Linux. (One of) The entire point of snaps is eliminating the need to keep track of dependencies and all that, and I'm not sure if this is a dependency issue or what, but the export window (The modal which opens up when you want to select a path to export a collection) is not showing fonts:

![Screenshot_20220111_132452](https://user-images.githubusercontent.com/67554982/148920878-6fe1d3ea-ab4b-40c7-8f61-c4d1546ed93b.png)

### Steps To Reproduce

1. Right-click on a collection
2. Click on Export
3. Click Export

### Environment Information

```markdown
- Operating System: ManjaroLinux 21.2.1
- Platform Type: Native App
- Postman Version: 8.12.5
```

**Comment by jviotti** [comment]
Merging this with https://github.com/postmanlabs/postman-app-support/issues/10449
