### ISSUE TITLE
Response is too large to be saved in the request example (server mock)

### ISSUE THREAD

**Issue by yurii2004** [a85/POSTMan-Chrome-Extension#10553]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

I'm trying to mock server responses. I've created a few requests with examples inside them. But when I'm using a very large json (about 14000000 chars) as the server response I simply can't save the example and use it.
<img width="306" alt="Screenshot 2022-01-10 at 16 06 08" src="https://user-images.githubusercontent.com/12534175/148788332-51b45639-015b-443b-a9c6-40a397af0e02.png">
.

### Steps To Reproduce

1. Create a request in the collection
2. Create an example for the request
3. Add a large json data inside the example response
4. Try to save this example using the save button

### Environment Information

```markdown
- Operating System: macOS Monterey 12.0.1
- Platform Type: Native App
- Postman Version: 9.8.2
```

**Comment by Dhembla** [comment]
@yurii2004 Thank you so much for reaching out to us. Postman currently allows saving a maximum of 5MB of data as example responses. You can read more about examples here - https://learning.postman.com/docs/sending-requests/examples/#adding-an-example.
Can you please help us understand your use-case as to why you want to store larger responses? cc @giridharvc7 @malvikach

**Comment by DannyDainton** [comment]
Hey @yurii2004 

I'm going to close this issue, it's not clear what your use case is and why you would need to store larger responses. If you can provide more context we can take another look and reopen the issue.

**Comment by honglou2001** [comment]
I encounter the same problem. For some business scenarios, an example size bigger than 10M or 20M is very common.

**Comment by fvox13** [comment]
@DannyDainton this artificial limit is aggravating when trying to provide examples of certain API endpoints to developers, especially if the API is not always accessible to them.    Many modern business APIs provide tens of megabytes of JSON data in their responses.    It is unclear as to why a limit exists in the application at all.

**Comment by domradom** [comment]
for me too. I would like to save a response which is more than 20MB just for business requirements.

**Comment by mDehning** [comment]
This issue not only comes up when saving an example but also when you just want to display the response from the api to read specific fields. Any script I want to use there will fail.

**Comment by ghost** [comment]
Actually, postman still prevents from saving an example that is less than 5MB (4.6MB)

**Comment by herostoky** [comment]
why is this closed ?
May-2025 and still cannot save the mock API response.

**Comment by ghost** [comment]
Guess, they can't support it. @yurii2004 @DannyDainton can you re-open the issue? see the above comments mentioning that people need it

**Comment by fvox13** [comment]
We ended up moving on from Postman.  Lots of great alternatives that don't have this limitation.
