### ISSUE TITLE
Dragging a secret environment entry to a different position reveals the value

### ISSUE THREAD

**Issue by thinkedem** [a85/POSTMan-Chrome-Extension#10556]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

When I rearrange the environment values, dragging a secret value will reveal the actual value while the type remains secret; as if I have clicked on the "reveal" icon.

### Steps To Reproduce

1. Open an environment
2. Make sure you have several entries added
3. Set one entry (with any non empty value) type to secret
4. Drag that entry to a different position using the drag bar on the left side
5. The value is now revealed as if clicked on the eye icon on the right side

### Environment Information

```markdown
- Operating System: macOS 12.1
- Platform Type: Native app
- Postman Version: 9.8.2
```

**Comment by malvikach** [comment]
@thinkedem Thanks for taking the time to bring it to our attention.
Our team is looking into this and we will get back to you on this. Will let you know if we need any more details.

**Comment by KiraElric007** [comment]
Hello @thinkedem!
Thank you for letting us know. We were able to reproduce this issue. We are working to resolve this issue.

**Comment by malvikach** [comment]
@thinkedem  Hello, we are happy to inform you that this issue has been fixed. 
Please feel free to let us know if you face any other problems while using the secret variable type.
