### ISSUE TITLE
Flows - Action after last item in For Each block

### ISSUE THREAD

**Issue by uricholiveira** [a85/POSTMan-Chrome-Extension#10554]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request

### Is your feature request related to a problem?

No

### Describe the solution you'd like

After iterate on all items, create another flow to execute other block.

**Comment by DannyDainton** [comment]
Hey @uricholiveira 

As this relates to the Flows feature, could you open up a ticket on that repo, please?

https://github.com/postmanlabs/postman-flows

Adding as much detail as possible will help the team understand the use case and the problem that the new feature will solve.
