### ISSUE TITLE
<title>Provide a remark field for Variable

### ISSUE THREAD

**Issue by siddh78** [a85/POSTMan-Chrome-Extension#10558]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request

### Is your feature request related to a problem?

When defining variable in various level, like Environment / Collection etc. It is good to have a remark field, which wll describe the purpose of the variable. It is more of a Useability point rather major enhancement. However it will be a good enhancement for documentation.

### Describe the solution you'd like

Provide a New field next to each variable field, called remark. Where user will be able to document the purpose of the variable.

### Describe alternatives you've considered

API Documentation / Comment in pre-request script / Test Script. But not a great option.

**Comment by giridharvc7** [comment]
Duplicates #6714
