### ISSUE TITLE
Unable send file in form data (first field)

### ISSUE THREAD

**Issue by hosseinhojjatyar** [a85/POSTMan-Chrome-Extension#10564]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

Hello
I use Postman v9.8.3 and when I try to send files, first field always is empty

![Capture](https://user-images.githubusercontent.com/67653777/149344221-1d77838b-da65-4aa8-a7cb-19b8bd53d15f.PNG)

in the server side I got nothing

![Capture5](https://user-images.githubusercontent.com/67653777/149344493-07897e57-8296-4376-9eb4-7e4cb54ce702.PNG)

when I send two files

![Capture2](https://user-images.githubusercontent.com/67653777/149344809-b10eb254-ac65-49b9-9101-740c5443c858.PNG)

I got only the second file

![Capture3](https://user-images.githubusercontent.com/67653777/149345084-27a6f31d-ef2b-483c-862e-a2ad9ff04bdc.PNG)

and when I send three files

![Capture6](https://user-images.githubusercontent.com/67653777/149345351-f3e38806-4abc-4940-8716-a7d9e33b6545.PNG)

I got only the second and third files

![Capture4](https://user-images.githubusercontent.com/67653777/149345493-6ead566e-7688-4006-85a6-7e9a38c5e72a.PNG)

### Steps To Reproduce

Send file - form-data

### Environment Information

```markdown
- Operating System: Win10
- Platform Type: Postman Desktop
- Postman Version: 9.8.3
```

**Comment by malvikach** [comment]
Hi @hosseinhojjatyar We had recently discovered a bug related to form-data in request body. I am suspecting the issue you are facing might have something to do with it. I would request you to update to the latest postman version 9.9.2 and give the above issue a try again.

Let me know if you still face this. Additionally, let me know what the size of the first file in your response body is and if the filesystem permissions are in place for postman to read the file.

Will be happy to dig deeper into it and have our dev team look at it.

Really appreciate you providing us the details and screenshots to understand this better.

**Comment by hosseinhojjatyar** [comment]
Hi @malvikach,
I updated Postman (v9.9.3) and it works very well.
Thank you

**Comment by malvikach** [comment]
@hosseinhojjatyar glad it works now!! Please feel free to write to us if you face any other issues.
