### ISSUE TITLE
collection restore from trash fails

### ISSUE THREAD

**Issue by Bel4TST** [a85/POSTMan-Chrome-Extension#10567]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

i deleted my collection accidently so it was moved to trash.
when i tried to recover the collection  it throws exception. so i closed and reopened my postman application.
now my collection is not in trash too
![bug](https://user-images.githubusercontent.com/97727622/149477886-82a5ceb2-f728-41d8-9b07-85062e1e8950.png)

### Steps To Reproduce

open postman
go to my workspace
try running and editing collection request
delete request
import new request with same name
edit new collection name
try to import old collection
error occur
close and restart postman application
trash seems empty.
windows 10 , postman v9.8.3

### Environment Information

```markdown
- Operating System: windows 10
- Platform Type: desktop application
- Postman Version: v9.8.3
```

**Comment by DannyDainton** [comment]
Hey @Bel4TST 

Could you try and refine the steps to reproduce the issue please or create a short video showing the error that you're seeing.

In the Image, the Collection you have in the red box is also present in the left sidebar (Has the same name) so I'm unsure what you're trying to show in the picture.

**Comment by Bel4TST** [comment]
the one in collection side box is my new collection with same name . i was trying to restore the one i moved to trash before that. it failed so i imported a new one. any ways i got it back after 2hr's. thank you sir for helping
![image](https://user-images.githubusercontent.com/97727622/149505362-1f691483-9027-454e-ada8-6ac9b155cf12.png)
