### ISSUE TITLE
Is there any postman api for Single Request document share and collections document share?

### ISSUE THREAD

**Issue by kings1990** [a85/POSTMan-Chrome-Extension#10568]
### Describe your current workflow

Jetbrain Intellij  plugin (Fast Request)
So far，my plugin can export collections to postman!
And a have an idea,
i have single request and collections request, want to integration postman to share request and collections request.

![image](https://user-images.githubusercontent.com/8969637/149491069-46d3b5bc-44ff-4ec1-9b1a-a9917e07d37c.png)

![image](https://user-images.githubusercontent.com/8969637/149491124-e424511c-b6f3-4a3d-a27f-6671a01d39e1.png)

### Describe your ideal workflow

get some apis to publish request and collections, get an document url that not need to login
example [https://documenter.getpostman.com/view/7522038/UVXjJFb3](https://documenter.getpostman.com/view/7522038/UVXjJFb3)

**Comment by Raja-Simha** [comment]
Duplicate of #7833
