### ISSUE TITLE
Folders don't have custom subdirectory naming 

### ISSUE THREAD

**Issue by Lauren-Gill** [a85/POSTMan-Chrome-Extension#10561]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request

### Is your feature request related to a problem?

Instead of, for example, "https://api-docs.stuart.com/#634b1d7e-2f5f-402a-9ff8-0c5fa967bc67" we'd like to have "https://api-docs.stuart.com/jobs". This /name in the URL currently only works for a flat directory without folders, and for header 1 titles. More flexibility in this area would create a much better experience. 

### Describe the solution you'd like

Instead of, for example, "https://api-docs.stuart.com/#634b1d7e-2f5f-402a-9ff8-0c5fa967bc67" we'd like to have "https://api-docs.stuart.com/jobs". This /name in the URL currently only works for a flat directory without folders, and for header 1 titles. More flexibility in this area would create a much better experience.

**Comment by Raja-Simha** [comment]
Duplicate of #5706
