### ISSUE TITLE
Anchor tags don't work

### ISSUE THREAD

**Issue by Lauren-Gill** [a85/POSTMan-Chrome-Extension#10560]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

Anchor tags don't work and just send to the top of the document for published documentation. It seems to particularly happen in the single column layout. 

### Steps To Reproduce

add an anchor tag to your published API documentation, and then try to use it on the published documentation using single column layout 

### Environment Information

```markdown
- Operating System: 
- Platform Type: 
- Postman Version:
```

**Comment by kamaraj-p** [comment]
Hi @Lauren-Gill , thank you reporting the issue. We are working on it and will release a fix in the upcoming week.

**Comment by kamaraj-p** [comment]
The issue is resolved @Lauren-Gill
