### ISSUE TITLE
Share collection: upload/update doesn't function

### ISSUE THREAD

**Issue by yurik** [a85/POSTMan-Chrome-Extension#1056]
When trying to share existing collection the Update button doesn't function at all. Using account socialqa_us.

**Comment by abhijitkane** [comment]
@yurik What version of Postman are you using? 

Can you check the console (http://blog.getpostman.com/index.php/2014/01/27/enabling-chrome-developer-tools-inside-postman/) for any errors that might show up when you click 'Update'?

**Comment by yurik** [comment]
Using this version:
Version 2.1.1 (packaged)
OS: mac
Architecture: x86-64
Native client architecture: x86-64

getting this error:
POST https://www.getpostman.com/collections?is_public=false&user_id=22657&access_token=2a73b5d8cf09e41ddc44 500 (Internal Server Error)
send @ jquery.min.js:4
f.extend.ajax @ jquery.min.js:4
(anonymous function) @ requester.js:12343
Backbone.Model.extend.executeAuthenticatedRequest @ requester.js:12326
Backbone.Model.extend.uploadCollection @ requester.js:12339
(anonymous function) @ requester.js:3293(anonymous function) @ requester.js:3266
cursorRequest.onsuccess @ requester.js:20421

thanks,
Yuriy

**Comment by abhijitkane** [comment]
We'll update the app to show a proper error message. This may have been due to your access token being invalid. Can you try logging out, logging in, and retrying?

**Comment by yurik** [comment]
Thanks, 
that fixed it.
