### ISSUE TITLE
Client Certificates get deleted on Postman update

### ISSUE THREAD

**Issue by apuri123** [a85/POSTMan-Chrome-Extension#10565]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

When postman is updated installed client certificates are no longer there in settings and need to be re-added. 

### Steps To Reproduce

1. install an older version than the current of postman.
2. go to settings.
3. install client certificate.
4. update to latest version of postman.
5. go to certificates in settings. (they will no longer be there)

### Environment Information

```markdown
- Postman for Mac
- Version 9.8.3
- Architecture arm64
- Platform OS X 20.6.0
```

**Comment by postman-staff** [comment]
Hello @apuri123,
Thanks for writing in.

I've tried replicating the issue, but I was unable to

I did follow your steps, and downgraded to an earlier version of Postman, added client certificates, and then ran the updater to update to the latest version.
However, it does seem that the client certificates I added before triggering the update are still here

 ![](https://postman.zendesk.com/attachments/token/WO8tJ0kQvzBCEamwrPhozhxBG/?name=image.png)
Would you be able to let me know if you're seeing anything wrong with the steps I took? I might be missing something here.

Thank you. Looking forward to your response

via @nasco-a | Postman Support

**Comment by postman-staff** [comment]
Hello @apuri123,

I hope you're doing well. I'm checking in if you had the chance to go through our last reply?
If yes would you be able to let us know if we're missing anything in the replication steps, as we were unable to replicate the certificate issue on our end?

Thank you.
via @nasco-a | Postman Support

**Comment by postman-staff** [comment]
Hello @apuri123,
I hope that you are doing great.

Since we haven't heard from you in a while, and we fail to reproduce the issue I will go ahead and mark this ticket as **Closed**

If any further questions or issues arise, please do not hesitate to reach us back at any given time.

via @nasco-a | Postman Support
