### ISSUE TITLE
Env values getting replaced with older values for single user

### ISSUE THREAD

**Issue by puneet-mishra** [a85/POSTMan-Chrome-Extension#10576]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

I have been testing my APIs with postman using my development environment, 
After taking the code live, I switched to Production environment to test the APIs, but after each API call, the environment variable is getting reset to older value(value being used in development environment).

https://www.loom.com/share/c072246aa9694f70b6d6c3c627beaac2

### Steps To Reproduce

Just set the env val to some value X, fire the API call, env val gets changed to previous env's val

### Environment Information

```markdown
- Operating System: macOS Monterey
- Platform Type: mac
- Postman Version: Version 9.8.3 (9.8.3)
```

**Comment by puneet-mishra** [comment]
1. I have tried duplicating the collection and checking there
2. I have tried signing out and signing in 
3. I have also tried clicking on persist val for the env val

**Comment by puneet-mishra** [comment]
https://github.com/postmanlabs/postman-app-support/issues/8807 this was for team, but in my team only I am testing this API

**Comment by malvikach** [comment]
Hi @puneet-mishra thanks for writing to us. 

I checked out your video, it seems once you send your request, the current value of the variable changes to something that was previously set. I wanted to clarify that the current values of your variable are not sycned with our database. The current values only reside as session values for your usage. Hence, it seems that the request you are sending might be changing the current value. 

 I have a few questions:

- Are you using any test/pre-request script logic that might be effecting the current values (using pm.environment.set() ) 
- Could you share the sample request/collection so I can understand the problem better

**Comment by puneet-mishra** [comment]
Located the issue, thanks for quick support. Closing the ticket.
