### ISSUE TITLE
Change the color of "Console - Request / Response body editor" button 

### ISSUE THREAD

**Issue by KristofNalesnyik** [a85/POSTMan-Chrome-Extension#10579]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request

### Is your feature request related to a problem?

The "Console - Request / Response body editor" button has a very similar color as the background.
I have a display setting where I hardly see it. There were times I thought that the button had been removed.

### Describe the solution you'd like

Please change the color of the button to white / light gray / orange.

**Comment by DannyDainton** [comment]
Hey @nalesnyik 

Could you please include an image and the build version where you see the issue?

**Comment by KristofNalesnyik** [comment]
Hi @DannyDainton,

Version 9.9.3 | Architecture x64 | Platform win32 10.0.22000
Theme: dark.
With max contrast, it is kinda visible, but color change make it even more visible.

<img width="116" alt="image" src="https://user-images.githubusercontent.com/58170691/149962530-ee7e9605-8e3a-4673-91ea-8e4c399ff5a1.png">

**Comment by chris-torruella** [comment]
Hello @KristofNalesnyik thank you for your feedback. 
Currently, the text meets the AA 7:4:1 accessibility standard in terms of contrast for normal text size. However, we understand that it may still need more contrast for your specific use case.

We suggest trying out **the new High Contrast Themes** we recently released with Postman V11. They might be beneficial for your needs. Please let us know how it works out for you!

Thank you once again for your valuable input.
