### ISSUE TITLE
Export option unavailable on the dropdown options on environments in sidebar

### ISSUE THREAD

**Issue by olegv2022** [a85/POSTMan-Chrome-Extension#10577]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

The Environment can't be opened in the tab.
So, the "Export" action is unavailable.

### Steps To Reproduce

1. Select an environment.
2. Click on the "eye" icon. Nothing happens.
3. By the click on the environment the tab doesn't open too.
4. The "Export" item is absent in the 3dot menu

### Screenshots or Videos

https://user-images.githubusercontent.com/97892854/149776562-c151fded-dc27-447f-a627-4bda9db70bb8.mp4

![2022-01-17_152155](https://user-images.githubusercontent.com/97892854/149776806-97fa2374-fc25-4d74-aa47-ce503b3e25b4.png)

### Environment Information

```markdown
- Operating System: Win 10 x64
- Platform Type: Native App
- Postman Version: 9.9.0, 9.9.1
```

**Comment by VaishnaviChallaPostman** [comment]
@olegv2022 Could you please confirm if the "Always open requests in new tab" option from the Settings > General tab is toggled ON? If not, can you toggle it ON to see if it affects anything?
![image](https://user-images.githubusercontent.com/76939396/150760964-3600ba4b-dda1-491b-9c09-339ef92430fe.png)

**Comment by olegv2022** [comment]
Yes, the option wasn't set. I change this and Environments are opened in the tab. But I didn't change the option before and a few versions ago it worked.

**Comment by malvikach** [comment]
We are tracking this issue [here](https://github.com/postmanlabs/postman-app-support/issues/9608)
Closing this as this is a duplicate
