### ISSUE TITLE
GRPC should support protobuf descriptors in addition to `.proto` and server reflection

### ISSUE THREAD

**Issue by aditanase** [a85/POSTMan-Chrome-Extension#10570]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request

### Is your feature request related to a problem?

Yes, currently both proto import and server reflection are broken. 
- Importing a proto with import statements will break (#10547)
- Using reflection does not present all services (#10569)

### Describe the solution you'd like

Allow us to upload the `.pb` protobouf descriptor

**Comment by codenirvana** [comment]
Both the linked issues were resolved earlier this year, and the support for gRPC and Protobuf APIs improved a lot with v10.

I hope this workaround is no longer needed since the Protobuf descriptors are not collaborative and result in schema drift problems.
