### ISSUE TITLE
Cannot send binary files larger than ~200k

### ISSUE THREAD

**Issue by superstator** [a85/POSTMan-Chrome-Extension#1057]
Since getting the latest update (2.1 packaged), I'm unable to send binary files in a request unless it's a very small file; I have a 174k sample that works, but anything larger that I've tried does not. When a larger file is selected, clicking Send does nothing - no error, no ui updates, and no request sent (verified by watching Fiddler traffic). Any ideas?

**Comment by abhijitkane** [comment]
Can you check with the latest version - 2.1.1?

**Comment by superstator** [comment]
Yes, it looks to be fixed now. Thanks!
