### ISSUE TITLE
Unable to sync as tab in settings remains empty

### ISSUE THREAD

**Issue by akloeber** [a85/POSTMan-Chrome-Extension#1058]
I'm not able to activate syncing for a collection as the sync pane of the settings dialog remains empty:
![bildschirmfoto 2015-05-10 um 20 44 58](https://cloud.githubusercontent.com/assets/968308/7555752/72c3bfea-f755-11e4-8568-f2d92a1c3ffc.png)

I already tried restarting, log out, log in, etc. but with no effect. Furthermore I observe some errors in the console (maybe this is related):
![bildschirmfoto 2015-05-10 um 20 47 30](https://cloud.githubusercontent.com/assets/968308/7555768/e787ff9e-f755-11e4-9565-7aed355d664b.png)

**Environment**:
Version 2.1.1 (packaged)
OS: mac
Architecture: x86-64
Native client architecture: x86-64

**Comment by abhijitkane** [comment]
@akloeber Are you still seeing this issue in v3.0.4?

**Comment by akloeber** [comment]
Meanwhile it works.
