### ISSUE TITLE
Unable to import WSDL, if it contains import of external schema definitions (error: "The element or type could not be found undefined")

### ISSUE THREAD

**Issue by arattur** [a85/POSTMan-Chrome-Extension#10588]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

It seems that WSDL import is not working and generated SOAP request body has following error:
`<?xml version="1.0" encoding="utf-8"?>
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
  <soap:Body>
    <error>The element or type could not be found undefined</error>
  </soap:Body>
</soap:Envelope>`
if trying to import a WSDL which includes import of other external schemas, f.ex.:
`
...
<xs:import namespace="http://x-road.eu/xsd/xroad.xsd" schemaLocation="http://x-road.eu/xsd/xroad.xsd"/>
<xs:import namespace="http://www.opengis.net/gml" schemaLocation="http://schemas.opengis.net/gml/3.1.1/base/gml.xsd"/>
<xs:import namespace="http://www.w3.org/2005/05/xmlmime" schemaLocation="http://www.w3.org/2005/05/xmlmime"/>
....
`

### Steps To Reproduce

1. In Postman Desktop (PM) app click on _Import_ button
2. PM displays _Import modal_
3. Click on _Link_
4. PM displays _Import by URL_
5. Paste for example following URL "https://www.x-tee.ee/catalogue-data/EE/EE/GOV/70009445/metsaregister/7.wsdl" in URL field and click _Continue_
6. PM displays _Import file Options_
7. Click _Import_
8. PM displays _Import complete : 1 API and 1 collection were imported. They'll show up in the sidebar in just a few seconds._
9. Click on left menu item _Collections_
10. PM displays list of collections
11. Click on just imported collection name
12. PM displays list of imported SOAP POST requests
13. Click on some request name, f.ex. _findUsage_
14. PM display _Params view_ of a request;
15. Click on _Body_
16. PM displays _Body Raw view_ and following error:
`<?xml version="1.0" encoding="utf-8"?>
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
  <soap:Body>
    <error>The element or type could not be found undefined</error>
  </soap:Body>
</soap:Envelope>`

### Screenshots or Videos

![PM_UI_Request_with_error](https://user-images.githubusercontent.com/34676396/150113709-e404775a-5e60-43fd-b30d-03cf92b7932c.png)
![WSDL_import](https://user-images.githubusercontent.com/34676396/150113995-2057bb07-5d8b-4a35-8073-e9afd858a60a.png)
![PM_UI_Import_Object_object](https://user-images.githubusercontent.com/34676396/150113739-c0a4bbc1-a765-459b-b0e6-71ce3f7b32be.png)
![PM_Developer_Tools](https://user-images.githubusercontent.com/34676396/150113762-102a6689-f182-43dc-b67c-b791ee552dd7.png)

### Environment Information

```markdown
- Operating System: Ubuntu 20.04
- Platform Type: Native App
- Postman Version: 9.8.3
```

### Additional Context?

This issue seems to be the similar to the issue [10179](https://github.com/postmanlabs/postman-app-support/issues/10179). Based on the comments in that issue, as I understand, import of external schema definitions should.

I have tested several other WSDL imports (WSDL files are available f.ex. here: [https://www.x-tee.ee/catalogue/EE](https://www.x-tee.ee/catalogue/EE) at the bottom of a page click on Show all sybsystems. to get more WSDL links) and I receive the same error. If i try to import these WSDL-s in SoapUI then SOAP request are generated without errors.

I have checked Postman logfile _renderer-requester.log_ and no error is logged during import.

I  have spotted, that if during WSDL import I click on _Show advnaced settings_ then "[object Object]" is displayed in _Source URL of definition_ field and I can't change it.

**Comment by akshaydeo** [comment]
@arattur We are looking into this issue.  I will keep this issue updated 🙇

**Comment by VShingala** [comment]
@arattur Thanks for reporting the issue.

Currently, we are not supporting remote references to schemas. (imports where schemaLocation is not a local file). We are working on supporting it in the future but currently, we do not have any ETA on it.

ATM, you can overcome this by resolving these imports to local files and import schema via `Import > Folder` flow.

For example, you can try importing [this WSDL specification](https://github.com/VShingala/api-schema/tree/master/WSDL%20Folder%20example) which has all imports locally.

**Comment by arattur** [comment]
OK, thank you for reply.

**Comment by dpfDvlpr** [comment]
@VShingala I'm working with Postman v10.6.7 and I want create a request and response automatically using the option import WSDL.
I try import the WSDL specification that you say, but it don't work the import, I obtain  the error "Something went wrong while importing some elements, try import them again."
![image](https://user-images.githubusercontent.com/120661508/207895746-90bf7dfe-5303-4e89-bbef-6d15944a100b.png)

I also try Import -> Folder when I have a file .wsdl and a file .xsd with locally reference in wsdl file "<wsdl:import location="example_xsd0.xsd" namespace="http://tempuri.org/"/>". In this scenary, I can import the wsdl but I obtain the error describe above "The element or type could not be found undefined".

The import->Folder only work fine when I have only one wsdl file with the schema in there.

Can you help me with this situation?

**Comment by VShingala** [comment]
@dpfDvlpr Thanks for reporting the issue!

As this issue was resolved already and it seems issue you're facing is due to multi-file definitions could you create a separate new issue for this? You can also link this issue over there.

We were able to reproduce the issue as well but to also confirm it could you also share the definition that you're working with in order for us to reproduce the issue with that definition in that issue as well?

**Comment by angusdenton** [comment]
I don't believe that this issue is resolved at all for Import-->Folder 
I have made my XSD amd WSDL both local in a folder 
In the WSDL the schemaLocation clearly refers to the local folder
and the file names match.

<?xml version="1.0" ?>
<definitions xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata" xmlns:tns="http://www.timeedit.se/timeedit3/version3" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:ns1="http://schemas.xmlsoap.org/soap/http" name="timeedit3" targetNamespace="http://www.timeedit.se/timeedit3/version3" xmlns="http://schemas.xmlsoap.org/wsdl/">

`<types>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <xsd:import namespace="http://www.timeedit.se/timeedit3/version3" schemaLocation="./TE_SOAP_V3_B.xsd"/>
</xsd:schema>
</types>`

PS SOAPUI has no problem importing the folder and reading it correctly so I think the XML structure is fine

**Comment by sbieri1** [comment]
I have the exaxt same issue. I am currently using PM Desktop v10.21.14. With the folder import, none of the file references like

```
<xs:import namespace="http://someUrl.com/Schemas/Soa/2006-03/Exceptions"
                       schemaLocation="SoaExceptions.xsd"/>
```
can be resolved.

As @angusdenton already mentioned, I am also able to import my file with PS SOAPUI.
