### ISSUE TITLE
Mock server call log displays empty json body for content-type 'fhir+json'

### ISSUE THREAD

**Issue by ruthdiasoft** [a85/POSTMan-Chrome-Extension#10589]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

I send a request with content-type 'application/fhir+json' and with a body that contains a json message.
This body is then displayed as '{}' in the call log.

If I use 'application/json' the message is correctly displayed.

It would be nice if at least always the raw body could be seen in case postman doesn't know how to render the body.

### Steps To Reproduce

Create a mock server.
Send a request with content-type 'application/fhir+json'  and a body {"foo":"bar"}

Wait for the call log to display this request.
Now the request body is shown as {} instead of {"foo":"bar"}

### Screenshots or Videos

with 'fhir+json' it shows empty body:
![image](https://user-images.githubusercontent.com/98026490/150126172-845ba9fe-e2b4-42f2-a5d1-7c5190e87bf2.png)

with only 'json' it shows correctly:
![image](https://user-images.githubusercontent.com/98026490/150126087-fe68fb93-0212-4522-b789-17d7658346f5.png)

### Environment Information

```markdown
- Operating System: Ubuntu 21.10
- Platform Type: Native App
- Postman Version: 9.9.2
```

**Comment by Dhembla** [comment]
@ruthdiasoft Thank you so much for reaching out to us. We have released a fix from our side for this issue. Can you please verify it on your end and confirm the same?
Thanks
<img width="572" alt="Screenshot 2022-04-25 at 10 55 44 AM" src="https://user-images.githubusercontent.com/75123575/165025880-8031be55-b10f-4fb8-b102-411a854f4f4f.png">

**Comment by ruthdiasoft** [comment]
Yes, thanks!
