### ISSUE TITLE
GRPC C-Style comments inside messages and services are treated as invalid syntax

### ISSUE THREAD

**Issue by tiolan** [a85/POSTMan-Chrome-Extension#10592]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

Comments in C-style `/* comment */` are generally valid in protobuf.
https://developers.google.com/protocol-buffers/docs/proto#adding_comments

In the test I used a .proto that as /* comments in front of services and messages - which seem to be fine.
There are also /* comments within a message and within a service definition.
They lead to the error message described below.
I cannot tell whether it is valid syntax to have those comments inside messages and services - but at least protoc does not complain.

### Steps To Reproduce

When using the new gRPC (beta) functionality in Postman and importing this .proto, the error described below is displayed.

Protofile:
```
message Message
{
    string field1 = 1;  /// Comment
    string field2 = 2;  /// Comment
    /*
     * @exclude
    uint64 commented_field = 3;  /// Comment
     */
    string field3 = 4; /// Comment
}
```

### Screenshots or Videos

Error message from Postman:

Error: illegal token '*' (/src/<wiped>.proto, line 44)

### Environment Information

```markdown
- Operating System: Ubuntu 20.04
- Platform Type: Native App
- Postman Version: v9.9.3
```

**Comment by JoshuaWise** [comment]
A fix for this has been implemented, and should be part of our next app release! 🎉

**Comment by codenirvana** [comment]
This is fixed in the latest version of the Postman app.

**Comment by seongheum-choi** [comment]
Hello, I met a bug related to this issue on postman Version 9.29.2

So I want to share you.

if I use comments like this
```proto
// c++ style comment                 <- one new line between comments
/* c style comment start
  blahblah
*/
```
postman cannot parse this file

but if I add one more new line, it works normally.

I just added one more new line.

I hope this information to help Postman,

Apologize for my poor English, thank you, have a good day
