### ISSUE TITLE
Auth2 custom request parameters

### ISSUE THREAD

**Issue by perevernihata** [a85/POSTMan-Chrome-Extension#10599]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request

### Is your feature request related to a problem?

We are using Auth0 as our identity provider. Inside auth0 there is a way to configure custom "connection" (connection is the relationship between Auth0 and a source of users - https://auth0.com/docs/authenticate/identity-providers). 
Currently,  you should specify a query string parameter `connection`, whenever you want Auth0 to use specific user pool, and there is no way to do that via postman authorization code flow:
![image](https://user-images.githubusercontent.com/4924933/150709658-ac047c6f-5a9d-47dc-bb37-3b08afaa0839.png)

![image](https://user-images.githubusercontent.com/4924933/150709935-9ce0ec79-4cbb-4d29-a25a-d38e88e4dc41.png)

### Describe the solution you'd like

I would like to be able to add custom parameters to auth2 authorization code flow

### Describe alternatives you've considered

None

**Comment by giridharvc7** [comment]
Thanks for reporting this. 
Are you able to add `connection` to the `Auth URL` as a parameter?

**Comment by perevernihata** [comment]
in real application - yes, but not through postman - I tried to add `&connection=XXX` to some of the existing parameters, but postman is too smart - all data is URL encoded

**Comment by perevernihata** [comment]
any progress on this one? what would you suggest us to do with auth0 integration?

**Comment by abhijeetborole** [comment]
Hey @perevernihata, This is now available under the `Advanced` section under OAuth2.0. With these changes, you can now add params to the headers, body and URL for token requests in the auth code flow. You can also add query params to the auth request. Let us know if you have any issues.

![CustomOauthLow](https://user-images.githubusercontent.com/9638586/232849656-63e0297a-7bc3-4472-8ff3-04cf2f5df95e.gif)
