### ISSUE TITLE
[Postman Agent] Is there anyway to run postman-agent detached from the terminal on linux?

### ISSUE THREAD

**Issue by NateSwanson7** [a85/POSTMan-Chrome-Extension#10593]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

I'm using the new web interface, but I need the postman-app for making requests to my localhost. Everything works as expected, but I'd prefer to be able to run postman-agent in the background? Is there any option I can pass on the cli when running postman-agent so I don't have the process bound to a terminal window? 

### Steps To Reproduce

1. Open terminal
2. Navigate to Postman Agent directory
3. Run `postman-agent`

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/31102449/150377790-c60b12bf-8156-4640-bc7a-d7a183a06a5c.png)

### Environment Information

```markdown
- Operating System: Ubuntu 21.10
- Platform Type: Postman Agent
- Postman Version: 0.4.3
```

**Comment by jviotti** [comment]
@NateSwanson7 I believe you could run:

```sh
$ nohup postman-agent
``` 

The `nohup` command detaches the child process from the terminal session.

**Comment by DannyDainton** [comment]
Closing this issue based on the suggested command above.
