### ISSUE TITLE
Code for C# RestSharp is generated incorrectly

### ISSUE THREAD

**Issue by saturnsjazz** [a85/POSTMan-Chrome-Extension#10591]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

With the update to Restsharp v107 most of the client options are moved to RestClientOptions from IRestCleint.  This is how you can instantiate the client using the simplest possible way: 

var options = new RestClientOptions("https://api.myorg.com") {
    Timeout = -1
};
var client = new RestClient(options);

instead of:

var client = new RestClient("https://api.myorg.com");
client.Timeout = -1;

The IRestResponse interface is now deprecated. You get an instance of RestRequest or RestRequest<T> in return.

Please feel free to reach out if you have any questions.

### Steps To Reproduce

1. Generate C# - Restsharp code from any API.  

### Environment Information

```markdown
- Operating System: Windows 11
- Platform Type: Native App
- Postman Version: v9.9.3
```

**Comment by msdiniz** [comment]
@saturnsjazz is absolutely right about deprecated and now, incorrect code.
The snippet provided has other errors too; instead of:
```
var request = new RestRequest(Method.GET);
...
...
IRestResponse response = client.Execute(request);
Console.WriteLine(response.Content);
```
it should be:
```
var request = new RestRequest();
...
...
var response = client.ExecuteAsync(request);
Console.WriteLine(response.Result);
```

**Comment by Aeroverra** [comment]
It has been quite a while since this issue started happening. Will this be fixed anytime soon?

**Comment by OvidiuMuresan578** [comment]
No, this wont be fixed. It's coming from postman and the type of the response is "Task<RestResponse>"

**Comment by saturnsjazz** [comment]
@OvidiuMuresan578 What do you mean it won't be fixed?

**Comment by sy-huss** [comment]
I've found that most of the code generated by Postman is now obsolete. For beginners using Postman they need to be careful not to use the code generation tool as it is not maintained.

**Comment by Narzard** [comment]
Generating the request code is one of the best features of Postman. I hope this gets resolved soon.

**Comment by carellot** [comment]
Hi, 
The snippet continues to generate wrong,
Any news about it?
Thanks.

**Comment by StuartHemming** [comment]
Not only this, but the sample uses the deprecated interface `IRestResponse`.

**Comment by GarryLowther** [comment]
This image shows the current state of play:
1. Postman is generating C# code using RestSharp - code shown in image
2. This code does not compile with latest RestSharp
3. Latest nuget package is shown in image
4. Visual Studio errors are shown in image

![image](https://user-images.githubusercontent.com/5684253/203789372-5539a3e8-c690-4a30-900e-9133998541b5.png)

**Comment by danielicy** [comment]
install restsharp version 106.15.0 and MAGIC!! it compiles!

**Comment by sakher** [comment]
Please!!!! fix this ASAP. the C# code you generate is full of issues.
We have to deal with customers all the time because of this :(

using System;
using RestSharp;
namespace HelloWorldApplication {
  class HelloWorld {
    static void Main(string[] args) {
      var client = new RestClient("https://url");
      **client.Timeout** = -1; --> doesn't exist - you need to pass configuration object instead.
      **var request = new RestRequest(Method.POST);** -->             var request = new RestRequest("resource", Method.Post);
      request.AddHeader("Accept", "application/json");
      request.AddHeader("Authorization", "Basic ..............");
      request.AlwaysMultipartFormData = true;  **// we expect request.MultipartFormQuoteParameters = true; to be added to generate exactly the same request ...**
      request.AddParameter("param", "xxxxxxxxxx");
      request.AddParameter("param2", "xxxxxxxxxx");
      IRestResponse response = client.Execute(request);
      Console.WriteLine(response.Content);
    }
  }
}

**Comment by StuartHemming** [comment]
It appears that the Postman Team have lost all interest in support

**Comment by akshaydeo** [comment]
@StuartHemming @sakher @saturnsjazz @GarryLowther we are looking into this issue on priority right now 🙇‍♂️ Apologies for delay in prioritising this issue 🙏

**Comment by umeshp7** [comment]
Hey folks! Apologies for not getting back on the thread earlier. We had identified this issue sometime back and had started working on updating the Restsharp code as well. 
We will be soon merging this and should be available in an upcoming release and on web. We will update the thread when it is available 🙇🏼

**Comment by sakher** [comment]
Big thanks guys, glad to see this progress!
Ideally the code generated should have the exact same effect as running it from the Postman UI

**Comment by neerajmehtausa** [comment]
> Hey folks! Apologies for not getting back on the thread earlier. We had identified this issue sometime back and had started working on updating the Restsharp code as well. We will be soon merging this and should be available in an upcoming release and on web. We will update the thread when it is available 🙇🏼

Are you still working on this issue? I just tried using the C# snippet code in a C# Solution, I had to deal with the timeout and iRestResponse. If I comment out the timeout line and I change the iRestResponse to RestResponse, I could run the code but I did not get any response. It does not do anything.

**Comment by TimZander** [comment]
I am also interested in this being fixed. What is the status?

**Comment by StuartHemming** [comment]
> I am also interested in this being fixed. What is the status?

Apparently, the status is "we couldn't care lass, ay least, that seems to be the impression that they are trying to give

**Comment by sakher** [comment]
Hi guys- this is quite a big problem for us, please help us resolving this ASAP.
This has been here for more than a year !

**Comment by umeshp7** [comment]
@sakher @StuartHemming The fix has been merged to the postman-code-generators module already. And will be available in the upcoming release of the postman app. 
We will share an update here as soon as this is generally available in the postman app. 

Thank you for your patience
cc @webholik @VShingala

**Comment by TimZander** [comment]
What is your release cycle? Is this a 2 week or 6 month Timeline?

**Comment by webholik** [comment]
@sakher @TimZander The fix is now available in the latest version of Postman App.

**Comment by RobertAdomex** [comment]
Yes! And it works now, thank you!
