### ISSUE TITLE
Large number being rounded in the response.

### ISSUE THREAD

**Issue by omkarkhair** [a85/POSTMan-Chrome-Extension#1059]
In the published version of Postman client for Chrome I noticed that large numbers in a JSON response are being rounded. Screenshot below with Chrome's network and Postman response being compared.

![capture1](https://cloud.githubusercontent.com/assets/1644919/7565836/bd747118-f810-11e4-8664-7fdce7d851ab.PNG)

**Comment by abhijitkane** [comment]
This has been solved in the packaged app - https://chrome.google.com/webstore/detail/postman-rest-client-packa/fhbjgbiflinjbdggehcddcbncdddomop?hl=en
