### ISSUE TITLE
<<Cannot open request>>

### ISSUE THREAD

**Issue by michael120288** [a85/POSTMan-Chrome-Extension#10606]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

I updated Postman for the latest version and now my Postman cannot open any requests.  MacBook Pro m1 Max

### Steps To Reproduce

1. Open Postman
2. Open Workspace
3. Open any collection
4. Open any request

### Environment Information

```markdown
- Operating System: Monterey 12.1 
- Platform Type: Native App / Postman Web
- Postman Version: 9.10.1
```

**Comment by postman-staff** [comment]
Hi @michael120288,

Could you please try clearing your local cache for Postman, to see if that helps - as it might be a local issue with the installation?

Before clearing your local cache, please verify once in the web application that all of your data is synced, and in case you can see all of your data on the web, please follow the steps listed below :




**How to clear/rename Postman's local files**


- https://support.getpostman.com/hc/en-us/articles/360025359014

Please let us know how it goes, and in case you need any further assistance while following the steps.

via @ash007-postman | Postman Support

**Comment by postman-staff** [comment]
Hi @michael120288,

May I know if you were able to resolve the issue by clearing the cache as mentioned earlier? Let me know if you still need assistance on the same. Thanks!

via @ash007-postman | Postman Support

**Comment by StephanSchu** [comment]
Hi,

I was facing the same issue after migrating from an Intel MacBook to an M1 Max MacBook and clearing the local files resolved the problem.

**Comment by postman-staff** [comment]
Hi @michael120288,

Thanks for letting us know👍🏼

via @ash007-postman | Postman Support
