### ISSUE TITLE
Description column selection does not persist

### ISSUE THREAD

**Issue by noahmonster** [a85/POSTMan-Chrome-Extension#10605]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

When using the Params or Headers tab for a request, I want to hide the "Description" column. I can do this just fine. However, the selection of this value seems to only stay around until I quit the application. When I start the application back up, the "Description" column shows up again. 

This can be frustrating.

### Steps To Reproduce

1. Open an existing request in a tab
2. Go to the Params or Headers tab within the request
3. Click the ellipsis and deselect the "Description" column
4. Quit Postman
5. Restart Postman
6. Open the request from step 1
7. Go to the Params or Headers tab within the request

See that the "Description" column is visible.

### Environment Information

```markdown
- Operating System: macOS Monterey (12.0.1)
- Platform Type: Native App
- Postman Version: Version 9.10.1
```

**Comment by giridharvc7** [comment]
@noahmonster thanks for reporting and apologies for the trouble. Can you confirm if you are saving the request after updating the description?

**Comment by noahmonster** [comment]
@giridharvc7 Removing the description column does not show the request as needing to be saved. However, making a different change to the request and saving it doesn't seem to have any affect on this behavior.

**Comment by giridharvc7** [comment]
Got it, My bad I misunderstood this. 
I understand, there needs to be some sort of `user preferences` when it comes to the Postman UI itself. We'll take this as a feature request

**Comment by markbullock-mbo** [comment]
I agree this behavior is annoying, especially with the seemingly ever-decreasing working space due to buttons on the left side, buttons on the right side, path and buttons between the request tab and url, and the buttons in the footer.

**Comment by mick-net** [comment]
I agree too. When opening a Request my main focus of interest is on the Param's Key and Value columns, but the description column (Which I never use) takes up most space by default.

**Comment by yosefham** [comment]
Same feeling here, the Description column is barely used. 
if possible, I would prefer to make it disabled by default (like the Content-Type column in form-data).

**Comment by minhthong095** [comment]
Could you Postman Team make it close persistently please? Thank you

**Comment by sladjo** [comment]
Please implement this feature. I don't know how many times a day I click it off because it bothers me so much.

**Comment by Sesota** [comment]
8 months have been passed and no progression is recorded on this issue. I know it's a bad behavior to spam the issue trying to remind; but I think Postman team needs this reminder.

**Comment by Konstantin-X** [comment]
Very annoying behavior, especially since sometimes the state of the hidden description column is saved, but then something happens - and it appears again.

**Comment by jonatancompiani** [comment]
Very annoying, specially when working on small screens. A feature to hide it by default would be great also...

**Comment by andrespolanco** [comment]
I agree this behavior is annoying

**Comment by pavdro-ttl** [comment]
bump :)

**Comment by sladjo** [comment]
One more hint, if the "Two-Pane View" is used, the description column is even more annoying because the horizontal space is even more limited.

**Comment by viktorhanssonminut** [comment]
I'll bump this too since nothing seems to be happening

**Comment by demotodo** [comment]
Very eager to get this new feature in short time!!

**Comment by big-omega** [comment]
@giridharvc7 Any progress on this? Got the same trouble too, hope there exists a global setting to enable/disable it, thanks!

**Comment by nhat** [comment]
The description column should really be hidden by default.

**Comment by veraciousnottaken** [comment]
The same

Postman for Windows
Version 10.4.5
UI Version 10.4.5-ui-221122-0258
Desktop Platform Version 10.1.2
Architecture x64
OS Platform win32 10.0.19044

**Comment by quangtt-rks** [comment]
The same here, this behavior is annoying

**Comment by alvinobarboza** [comment]
Same here, too much of an annoyance. Should be hidden by default or add where to hide by default for all.

**Comment by richard-bridgeman** [comment]
Can we have it turned off by default please, I hate it

**Comment by murilosdv** [comment]
Man, if we could have something to persist the removal of the description, that'd be great. It's really, really annoying having to disabled it every single time.

**Comment by Dhembla** [comment]
Hey Folks,
Sorry for the trouble that you had to go through because of this issue. We have added this capability as part of our latest release, v10.9, and from now on, you will be able to hide the description column and the selection will persist across sessions. The release is being rolled out and will be available in the next few days.
Thanks for your patience 🙇
