### ISSUE TITLE
Proto file import from chromium not working

### ISSUE THREAD

**Issue by karsep5** [a85/POSTMan-Chrome-Extension#10604]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

Importing proto files from chromium source code throws error https://source.chromium.org/chromium/chromium/src/+/main:components/autofill/core/browser/proto/server.proto

There was an error while importing the protobuf definition. Go through the details to know more.
Error: illegal token 'message'

### Steps To Reproduce

1. Select "New"
2. Go to "Choose a way to load services and methods"
3. Choose "Import protobuf definition from local file"
4. Select the downloaded version of the file https://source.chromium.org/chromium/chromium/src/+/main:components/autofill/core/browser/proto/server.proto
5. Select Open 

### Environment Information

```markdown
- Operating System: Windows
- Platform Type: Native App
- Postman Version: v9.10.0
```

**Comment by JoshuaWise** [comment]
A fix for this has been implemented, and should be part of our next app release! 🎉

**Comment by codenirvana** [comment]
This is fixed in the latest version of the Postman app.
