### ISSUE TITLE
Filter variables

### ISSUE THREAD

**Issue by etgregor** [a85/POSTMan-Chrome-Extension#10602]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request

### Is your feature request related to a problem?

It would be very helpful to be able to filter variables by name/values. 

I have to configure many variables ( more than 50), and sometimes i try to reuse a variable, bus this work is complicated because y cant find an specific variable. I try to find a variable by name but the variable grid isn't in order, not to mention finding a word that I think I have used; thats a hard work.

### Describe the solution you'd like

Enable filter the variable grid

### Describe alternatives you've considered

You just add a search input in every column of variables grid in that I can type some words or characters and the grid will be filter by that word..

if thats complicate, you can add a single input searchbox  like this:

https://speedysense.com/demo/javascript-filter-table-data/

### Additional context

https://speedysense.com/demo/javascript-filter-table-data/

**Comment by etgregor** [comment]
![2022-01-24_17-10-10](https://user-images.githubusercontent.com/6732389/150913071-872e8592-f5a7-4b73-8fbe-f66279494f92.png)

**Comment by malvikach** [comment]
@etgregor thanks for writing to us. Variable filtering is in our radar. However, I can't promise an ETA yet. 

While our team picks this up, we would like you to try out postman on [web](https://www.postman.com/) On the web, you could utilize the browser (CMD+F) for this.

Please feel free to let us know if you are facing any other issues while working with postman.

**Comment by IanLamon** [comment]
In addition to filtering for variables, it would be great to be able to sort variables alphabetically.

**Comment by Tony20221** [comment]
I would like to see filtering and sorting in the list of environment variables.

**Comment by vedkribhu** [comment]
@etgregor @Tony20221 @IanLamon 
In our latest release v10.10, we have introduced filtering support in the variables list. Do let us know your feedback.
![Screenshot 2023-02-15 at 12 29 24 PM](https://user-images.githubusercontent.com/37595282/219372350-4848186b-1a06-4b7d-bf44-14312927f46a.png)

In addition, we are also working on adding sorting functionality which should be available in our next release which is next month.
