### ISSUE TITLE
Set default response format

### ISSUE THREAD

**Issue by ecaldwell** [a85/POSTMan-Chrome-Extension#1060]
Most of the APIs I work with deal in JSON. Each time I send a request I have to toggle from HTML to JSON to properly parse the response body. 

It would be ideal if I could set JSON as the default format for displaying the response body. 

![screen shot 2015-05-12 at 9 40 05 am](https://cloud.githubusercontent.com/assets/240542/7588404/dd0bd492-f88a-11e4-8caf-9ea154df3c87.png)

**Comment by abhijitkane** [comment]
There's a Language detection setting in the Settings modal which you can set to JSON. Other than that, Postman sets the default type depending on the Content-Type header that's sent by the server.

**Comment by ecaldwell** [comment]
That did the trick, thanks!

**Comment by malayladu** [comment]
Yeah..that did the trick for me too :)

Thanks!

**Comment by bachalarz** [comment]
Thanks!

**Comment by murthyteja** [comment]
Thanks, updating the Language Detection setting under General Tab and Request section, did the trick

**Comment by sainathsr** [comment]
Thanks , this really saved a lot of frustration when dealing with repeated requests

**Comment by mvducatti** [comment]
Thank you very much!

**Comment by malith-gammanpila** [comment]
> **Thanks , this really saved a lot of frustration when dealing with repeated requests**

**Comment by salman240** [comment]
Thanks Man!

**Comment by Eternalculture** [comment]
Thanks a lot. You made my day.

**Comment by willysvarela** [comment]
Thanks =). Saved my time

**Comment by AlanSealtiel** [comment]
Thanks :100:  :1st_place_medal:

**Comment by faizy-ahmed** [comment]
> There's a Language detection setting in the Settings modal which you can set to JSON. Other than that, Postman sets the default type depending on the Content-Type header that's sent by the server.

This really worked for me! Thanks mate for the help.

**Comment by kfly212** [comment]
Thanks!!!!

**Comment by sahuadarsh0** [comment]
thanks

**Comment by fzs1994** [comment]
Thanks Man!!

**Comment by danemesis** [comment]
lol, killer feature :D thanks!

**Comment by FinnAwe** [comment]
Cheers! mate!

**Comment by navhaxs** [comment]
Good to know! Would've been nice if there was a 'Auto-detected' text hint next to the dropdown UI, or 'Auto' as the default dropdown option... I've been manually selecting JSON for every request for over a year!

**Comment by ahmfarisi** [comment]
Thx buddy !

**Comment by Binozo** [comment]
Thanks!

**Comment by ManuelCrovetto** [comment]
You made me use Postman again. THANK YOU.

**Comment by hsiong** [comment]
Thanks a lot. This truly solved my problem

**Comment by hufeng903** [comment]
thanks , save my time

**Comment by harshitshakya123** [comment]
> There's a Language detection setting in the Settings modal which you can set to JSON. Other than that, Postman sets the default type depending on the Content-Type header that's sent by the server.

Thanks, It works.
