### ISSUE TITLE
GraphQL SDL support for repeatable directives

### ISSUE THREAD

**Issue by MattA48** [a85/POSTMan-Chrome-Extension#10614]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request

### Is your feature request related to a problem?

I am trying to consume our GraphQL schema generated by .NET / HotChocolate library and it's failing due to not accepting repeatable on a directive

### Describe the solution you'd like

Support for repeatable on directives for GraphQL SDL

### Additional context

Repeatable directive in GraphQL draft spec: https://spec.graphql.org/draft/#sec-Type-System.Directives
GraphQL repeatable directive PR: https://github.com/graphql/graphql-spec/pull/472

The segment of SDL that is failing in Postman (red squiggle on repeatable - expected 'on')
`directive @authorize("The name of the authorization policy that determines access to the annotated resource." policy: String "Roles that are allowed to access the annotated resource." roles: [String!] "Defines when when the resolver shall be executed.By default the resolver is executed after the policy has determined that the current user is allowed to access the field." apply: ApplyPolicy! = BEFORE_RESOLVER) repeatable on SCHEMA | OBJECT | FIELD_DEFINITION`

**Comment by SterlingChin** [comment]
The new GraphQL client is in [open beta](https://blog.postman.com/announcing-postmans-new-graphql-client/) and fully supports the Oct. 21 spec. I was unable to reproduce the red squiggle on `repeatable` when copy/paste the code from above into the new client.
