### ISSUE TITLE
changes in collections resulting from Moving directories are not saved

### ISSUE THREAD

**Issue by khessels** [a85/POSTMan-Chrome-Extension#10616]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

I have 2 main directory trees within a collection (trees are called V1 and V2)
When i create a sub directory in one tree, all goes well. When i restart the app and move sub dirs from one tree to the other and then restart the app, the move changes have not been persisted.
Seems like changes related to moving subdirectories from one tree to another are not always being saved.

### Steps To Reproduce

Create two main subdirs and add subrees to each main tree.
save and exit app
open app again & move some subdirs from one tree to another
exit app
open app again and see move changes have not been persisted. 

### Environment Information

```markdown
- Operating System: ubuntu
- Platform Type: Native app
- Postman Version: latest
O
```

### Additional Context?

It happens to me when dirs are identical in name, but that could be coincidence

**Comment by DannyDainton** [comment]
Hey @khessels 

I've not been able to recreate this issue in the latest version, if this is still a problem for you could you create a short recording of the issue, please? This will us to visualise the behaviour.

Closing this issue for now.
