### ISSUE TITLE
Request Description field's content can't be deleted

### ISSUE THREAD

**Issue by devdrops** [a85/POSTMan-Chrome-Extension#1061]
I noticed today the following problem:
1. Open Postman (packaged app);
2. Go to any Request, and click on Edit;
3. Delete all contents from the Request Description field;
4. Click on Edit.
5. Repeat 2. for the same Request you've edited;
6. Check that the Request Description field have the same contents as before.

**Evidence:** http://screencast.com/t/ri85Pzdb

Is there any pull request for this behaviour?

**Comment by abhijitkane** [comment]
We'll push a fix for this soon.

**Comment by devdrops** [comment]
:+1:

**Comment by devdrops** [comment]
Fixed at Version 3.0.4 (packaged).
