### ISSUE TITLE
Empty tabs

### ISSUE THREAD

**Issue by dractw** [a85/POSTMan-Chrome-Extension#10622]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

After arestart there is a couple of used previously tabs doesn't load and unable to force close.

### Steps To Reproduce

1. Create a tab
2. Create a tab duplicate
3. Restart Postman

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/10141593/151818775-5a6d5e5c-75a3-41bb-bcfd-416c7dc0146f.png)

### Environment Information

```markdown
- Operating System: OSX 11.4
- Platform Type: Native
- Postman Version: 9.11.0
```

**Comment by Raj-postman** [comment]
Hi @dractw - Could you follow the steps mentioned in this thread here: https://github.com/postmanlabs/postman-app-support/issues/10634#issuecomment-1031088794

Note: Please make sure to save the tabs before performing the action to avoid any Data loss.

**Comment by Raj-postman** [comment]
@dractw Hoping that the earlier response was helpful. Resolution was also confirmed by other user facing a similar issue https://github.com/postmanlabs/postman-app-support/issues/10634#issuecomment-1039768635. 

Let us know if you need any further assistance on this case
