### ISSUE TITLE
gRPC: Add metadata to requests for server reflection

### ISSUE THREAD

**Issue by griggsca91** [a85/POSTMan-Chrome-Extension#10627]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

When I try to get the services and methods via Server Reflection, any metadata that I defined is not being passed in.

### Steps To Reproduce

1. Open gRPC request tab
2. Add a new metadata field
3. Attempt to get the proto details via reflection
4. See that the metadata is not passed through

### Screenshots or Videos

<img width="650" alt="Screen Shot 2022-02-02 at 2 09 41 PM" src="https://user-images.githubusercontent.com/7272667/152221390-5a4a94ee-fc71-4815-91ac-4efaa932c66c.png">

### Environment Information

```markdown
- Operating System: OSX
- Platform Type: Native App
- Postman Version: 9.11.0
```

**Comment by appurva21** [comment]
@griggsca91 Thanks for writing in! 

Currently, we do not support directly passing metadata in Server Reflection. We'll take this up but meanwhile, you can use the `Authorization` tab to pass on the metadata-based credentials with your method call.

![image](https://user-images.githubusercontent.com/24985700/152283042-b0d23c6b-e02f-420a-918b-aa58b15a6290.png)

Note: You'll need to have SSL/TLS configured to use the `Authorization` tab as it is not recommended to send credentials over an unencrypted channel.

**Comment by griggsca91** [comment]
> @griggsca91 Thanks for writing in!
> 
> Currently, we do not support directly passing metadata in Server Reflection. We'll take this up but meanwhile, you can use the `Authorization` tab to pass on the metadata-based credentials with your method call.
> 
> ![image](https://user-images.githubusercontent.com/24985700/152283042-b0d23c6b-e02f-420a-918b-aa58b15a6290.png)
> 
> Note: You'll need to have SSL/TLS configured to use the `Authorization` tab as it is not recommended to send credentials over an unencrypted channel.

Thanks for the quick reply! Unfortunately that's not possible at the moment without some significant work since we don't support TLS locally and don't have a certificate to provide, will have to wait for this feature until then.

**Comment by MrLimelab** [comment]
I will add that that's not only needed for authorization, there is some routing rules using headers so we are unable to reach correct pod in cluster without headers
Also grpcui supports headers but it's not very useful with authorization
grpcui -reflect-header 'grpc:feature-stand-1' -reflect-header 'feature-stand-1:debug' -plaintext 127.0.0.1:9000

**Comment by codenirvana** [comment]
@MrLimelab I understand your use case. We are working on it and will let you know when it's released.

Do you have a similar requirement of sending different reflection and request metadata?

**Comment by MrLimelab** [comment]
At this moment we don't need different headers for grpc request and reflection and i'm not sure that this will be required in the future. 
Looks like overhead. For our case same metadata for reflection and grpc call will be enough

**Comment by yuankaiyu** [comment]
We use a gateway that routes traffic to the corresponding server based on a header value, so we need the header for the reflection call as well. 
Well actually same situation as @MrLimelab 
Please help support this feature! Thank you very much.

**Comment by appurva21** [comment]
Hey everyone! We have added support for metadata in the server reflection call. 

This is being rolled out as part of v10.6.0 and should be available for everyone by early next week.

**Comment by piavgh** [comment]
Thanks a lot, struggled for 1h until I found this issue
