### ISSUE TITLE
Ubuntu: Mouse/Pointer size is incorrect when view is scaled

### ISSUE THREAD

**Issue by cornopaez** [a85/POSTMan-Chrome-Extension#10628]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

Hello all. This bug is more cosmetic than anything else.
In Ubuntu 20.04 LTS, when the display is scaled up to 200%, the mouse/pointer within the Postman view stays at the default size. If you have a 4K monitor with the view scaled, it means all text and windows looks great... but you end up with a tiny pointer.

### Steps To Reproduce

1. Set the display to be 4K within Ubuntu and scale to 200%
2. Open Postman
3. Try and find the tiny pointer in the screen within the Postman window

### Screenshots or Videos

![Expected](https://user-images.githubusercontent.com/10913230/152374470-e24faa89-97ad-4fd5-8a6e-2dabed7c5f76.jpg)
![Small](https://user-images.githubusercontent.com/10913230/152374475-c0880f42-87da-4da1-a452-4cc4b37cf8dc.jpg)

### Environment Information

```markdown
- Operating System: Ubuntu 20.04.3 LTS (all updates as of 2/3/22)
- Platform Type: Native App
- Postman Version: v9/Stable channel, 9.9.3
```

**Comment by jviotti** [comment]
Thanks a lot for letting us know about this issue and for the detailed report. We'll be taking a look into this one very soon!

**Comment by jviotti** [comment]
Looking into this, I found that this issue has been reported here: https://github.com/postmanlabs/postman-app-support/issues/10030. Closing this one and we can continue the discussion on the other issue!
