### ISSUE TITLE
Change order of websocket requests

### ISSUE THREAD

**Issue by natgra** [a85/POSTMan-Chrome-Extension#10629]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request

### Is your feature request related to a problem?

Websocket requests are ordered by time of creation. Ordering websocket requests manually is currently not possible.

### Describe the solution you'd like

It would be great if a postman user could re-order the requests within a collection in a different order manually, similar to REST requests.

As an example:
<img width="253" alt="order-requests-01" src="https://user-images.githubusercontent.com/10546494/152396366-8256e14e-ca51-4e90-ab61-3eddcd453fab.png">

New order:
<img width="245" alt="order-requests-02" src="https://user-images.githubusercontent.com/10546494/152396399-76225859-46ca-42d1-aa24-9a2678ead5e7.png">

**Comment by appurva21** [comment]
Hey @NatGra ! This is now supported in the latest version of the Postman app.

**Comment by natgra** [comment]
Awesome, thank you! 🥇
