### ISSUE TITLE
No GRPC option in my postman

### ISSUE THREAD

**Issue by moashxer** [a85/POSTMan-Chrome-Extension#10623]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

Hi,

I am using the postman v9.11.0 free version, there is no GRPC option available in my app 
Reference: https://blog.postman.com/postman-now-supports-grpc/

### Steps To Reproduce

1. Open new tab
2. In building blocks there should be GRPC option available in mine it doesn't

### Screenshots or Videos

![Screenshot_20220131_221314](https://user-images.githubusercontent.com/87684755/151836306-28c13b4f-e425-4efd-a547-391bd6bd3111.png)

### Environment Information

```markdown
- Operating System:  Ubuntu 20.04
- Platform Type: Native App
- Postman Version: v9.11.0
```

**Comment by numaanashraf** [comment]
Hi @moashxer. It seems like you are on the Scratch Pad. gRPC is available only in workspaces at the moment.

**Comment by dominikjeske** [comment]
Are there any plans for enable this in Scratch Pad? I see no reason for this restriction.
