### ISSUE TITLE
User-Agent header is not customizable

### ISSUE THREAD

**Issue by max-voloshyn** [a85/POSTMan-Chrome-Extension#1062]
Postman always send value from Chrome's metadata, where it was launched.
Custom value is displayed in "Preview" mode(UI), but actually isn't passed to end-point.

Postman About:

> Version 2.1.1 (packaged)
> OS: mac
> Architecture: x86-64
> Native client architecture: x86-64

**Comment by abhijitkane** [comment]
User-Agent is a restricted header. You need to use the Interceptor to send it - http://blog.getpostman.com/2014/02/11/postman-v0-9-6-access-cookies-and-restricted-headers-plus-better-testing/
