### ISSUE TITLE
GET /collections/{collectionId} should return fork status

### ISSUE THREAD

**Issue by valentinbeggi** [a85/POSTMan-Chrome-Extension#10625]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

`GET /collection/{collectionId}` is not returning information about the fork status of the requested collection (forked from, fork label ...) whereas `GET /collections` does.

It would make sense for `GET /collections/{collectionId}` to contain at least as much information as `GET /collections`

### Steps To Reproduce

1. Make a request to `GET /collection/{collectionId}`, you should not see any details about the fork status of the collection.
2. Make a request to  `GET /collections`, you should get a response containing fork status. See example below
```ts
{
            "id": "d3ab4bdc-75e5-4abf-87ed-185a62a94fc8",
            "name": "[E2E] Shiva",
            "owner": "17393253",
            "createdAt": "2021-11-17T09:07:36.000Z",
            "updatedAt": "2022-02-01T08:49:31.000Z",
            "uid": "17393253-d3ab4bdc-75e5-4abf-87ed-185a62a94fc8",
            "fork": {
                "label": "preprod",
                "createdAt": "2021-11-17T08:42:32.000Z",
                "from": "17393253-4abe0054-a9e2-491e-a989-7a4d95e473b1"
            },
            "isPublic": false
}
```

### Environment Information

```markdown
- Operating System: MACos
- Platform Type: Desktop
- Postman Version: 9.10.1
```

### Additional Context?

Additional informations in #10617

**Comment by bpedro** [comment]
Thanks for creating this issue, @valentinbeggi. We will implement the changes that you mention.

**Comment by bpedro** [comment]
Hi again, @valentinbeggi. This is an update to let you know that we have implemented a fix and we're currently testing it. I will update again once the fix hits production. Thanks.

**Comment by valentinbeggi** [comment]
Hello @bpedro !
Nice thank you for your speed! 🤩

**Comment by bpedro** [comment]
Hi, @valentinbeggi. The fix is now in production. Please let me know if it's working as you expected. Thanks.

**Comment by valentinbeggi** [comment]
@bpedro Just tested it, works like a charm ! Thank you 🎉
