### ISSUE TITLE
Changes to API Definition failing to be found during revalidation of Documentation

### ISSUE THREAD

**Issue by jubbp** [a85/POSTMan-Chrome-Extension#10632]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

When editing an API definition, changes to the definition are not displayed after running a revalidation and are then not updated in the Documentation.

The only way I've found to force the issue is to generate new documentation.

### Steps To Reproduce

1. edit API definition (I've tried both web app and macOS version - I'm editing in JSON)
2. switch to Documentation Tab
3. Click "Issues found", then "Validate Again",
4. Click "Issues Found", then "Review Issues"
5. No issues are found
<img width="1542" alt="Screen Shot 2022-02-04 at 8 26 55 am" src="https://user-images.githubusercontent.com/21004063/152451796-be3bfd04-c3f8-4e7e-ad4f-5e6fa70e64b1.png">
 

### Environment Information

```markdown
- Operating System: MacOS 12.2
- Platform Type:  Native App 
- Postman Version: 9.8.3
```

**Comment by Raja-Simha** [comment]
@jubbp We are currently working on generating documentation from your API definition directly. This feature will be available for all users soon. Once available, we would love to hear your feedback and if it resolves your problem.

**Comment by VShingala** [comment]
@jubbp Thanks for reporting the issue!, Could you share your API specification or trimmed down version with the same issues so we can take a further look here?

**Comment by akshaydeo** [comment]
@jubbp could you please share the API id / Schema for us to test please 🙏 ? Thank you :)

**Comment by sony-mathew** [comment]
Hey @jubbp,

We understand your concerns and challenges with your use case. We've been working on improving our schema authoring experience and have introduced live preview alongside the editor. This feature allows you to see the changes you make live in the right context bar.

![Screenshot 2024-09-02 at 11 22 38 PM](https://github.com/user-attachments/assets/813d87c2-2c31-493f-b1a1-31cd0be5a507)

To specifically address the validation issues, you can more about it here: [Viewing validation issues](https://learning.postman.com/docs/designing-and-developing-your-api/developing-an-api/validating-elements-against-schema/#viewing-validation-issues)

You can learn more about the live preview and its updates here: [Preview schema documentation](https://learning.postman.com/docs/designing-and-developing-your-api/developing-an-api/defining-an-api/#preview-schema-documentation). 

We hope this resolves your issue. If you have any further concerns or questions, please feel free to reopen this discussion. We're here to help and support you.
