### ISSUE TITLE
How Expand View Summary Postman Runner

### ISSUE THREAD

**Issue by rilham97** [a85/POSTMan-Chrome-Extension#10639]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

I tried to create many iterations, but I can't see all of the progress (only until iteration 32). I can't scroll right / left the screen to

### Steps To Reproduce

1. Open Postman Runner
2. Set iteration with many numbers (e.g: 100)
3. Run the collection
4. See result using View Summary instead of View Result

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/28677129/152888703-9849b525-5fab-4224-b1a3-7e563fda4269.png)

### Environment Information

```markdown
- Operating System: Mac OS Monetary
- Platform Type: Desktop
- Postman Version: Version 9.12.1
```

**Comment by shubhbhargav** [comment]
Hi @rilham97, thanks for raising the issue. I am unable to reproduce it at our end. Can you please share a screen recording of the issue? This will help debug this better.

**Comment by DannyDainton** [comment]
Closing this issue as we're unable to reproduce it on the latest version of the platform. If you are still having issues, we can look at reopening this again.
