### ISSUE TITLE
Environment variable not being resolved when sending request

### ISSUE THREAD

**Issue by malvikach** [a85/POSTMan-Chrome-Extension#10644]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

Description
I have an environment variable "urlApi" defined w/ a value of "http//localhost:5050". The environment variable is then used in a request as {{urlApi}}. When the request is sent the follow error message is displayed indicating the variable is not being resolved to the proper url. All of the requests worked w/ this env variable until Postman was upgraded to the current version.

There was an error connecting to %7B%7BurlApi%7D%7D/api/v1/geoserver/inventorypoints?extent.x1=-7902186.581849624&extent.y1=5178452.208557574&extent.x2=-7899324.970603597&extent.y2=5180121.8798939455.

### Steps To Reproduce

This issue was originally reported on: https://github.com/postmanlabs/postman-app-support/issues/6001. However, it had been fixed. 

We still see some users updating that they have faced this issue. Unfortunately, Postman team has not been able to reproduce this issue. 

If you are facing this issue, I would request you to please share the steps to reproduce it.  (preferably a screenshot / video where you have selected the environment with the variable but it's failing when you send the request)

### Environment Information

```markdown
- Operating System:
- Platform Type:
- Postman Version:
```

**Comment by DannyDainton** [comment]
Closing this issue for now but if you're experiencing this issue in the latest version, please share the steps to recreate and some screenshots, this will enable us to investigate further.
