### ISSUE TITLE
Rest API endpoint for tracking license usage

### ISSUE THREAD

**Issue by zoltang01** [a85/POSTMan-Chrome-Extension#10642]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request

### Is your feature request related to a problem?

Hi, 

This is related to problem [#97330], tracking license usage.

### Describe the solution you'd like

I was looking for an exposed endpoint in the api that would allow us to view the current license count.

We were looking into creating a tool to monitor license usage and I was after a way of linking Postman to this

### Describe alternatives you've considered

Only alternative I know is to use the license count on the manage team page.

**Comment by bpedro** [comment]
Thanks for sharing this feature request, @zoltang01. Can you share more details about how you would use the response of a license usage API endpoint?

**Comment by zoltang01** [comment]
Hi Bruno,

Thanks for getting back to me. It wasn't anything really complicated to be honest. I'm looking into a project to put together an automated tool that monitors license counts for our various tools.
I was hoping it would be possible to link Postman to this. It would basically call the endpoint and return the license count to the tool. 

thanks a loot,
Zoltan

**Comment by zoltang01** [comment]
We have a lot of different tools and having something that can just run and return a quick license count would be really useful.

**Comment by bpedro** [comment]
Thanks for clarifying, @zoltang01. Your use case makes perfect sense.

**Comment by ozcanoguz** [comment]
Hello everyone,

There is already raised issue from today as well : https://github.com/postmanlabs/postman-app-support/issues/11529

From my point of view, regardless from "own monitoring" of license usage, Postman itself should provide it and track/monitor teams as they already detect it very quickly.

I think tracking should apply and automated alerts should be disposed for the workspace/team members that they are about to reach account limits ? Wouldn't it be better for your product portfolio as well, bringing such automation as a feature ?

**Comment by davidespihernandez** [comment]
Hi! The Postman API exposes a [/me](https://www.postman.com/postman/workspace/postman-public-workspace/example/12959542-c29dcc78-e7c3-4cc5-9df1-afbf7f286bb1) endpoint that returns the current usage for the requesting user (the Postman API key used in the request).
Please check the example provided to see which type of usage you can monitor.
If you need any additional information, please feel free to add a new comment on this ticket.
