### ISSUE TITLE
Request headers are not captured with Postman proxy

### ISSUE THREAD

**Issue by rubydev** [a85/POSTMan-Chrome-Extension#10649]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

Hello,

when I want to capture requests from mobile device (IOS) via Postman Proxy, all requests are captured included cookies. Problem is, that request headers missing (for example mobile app user-agant).

### Steps To Reproduce

I followed all instructions [here](https://learning.postman.com/docs/sending-requests/capturing-request-data/capture-overview/), requests are captured, response headers are there, but request headers missing.

### Screenshots or Videos

<img width="1278" alt="screenshot 4" src="https://user-images.githubusercontent.com/599358/153367165-3eb5f991-d47f-4c0e-a947-376f6983314f.png">

### Environment Information

```markdown
- Operating System: OSX Big Sur 11.6.3 
- Platform Type: Native App
- Postman Version: 9.13.1
```

**Comment by abhijitkane** [comment]
@rubydev thanks for reporting this - we'll look into this. Are request headers captured if you use the proxy via your browser (instead of a mobile device)?

**Comment by shashankawasthi88** [comment]
@rubydev can you also confirm if the headers are present in the in-session view (click on the arrow below the request that is captured to expand. You have details of the requests and response there)

**Comment by rubydev** [comment]
@abhijitkane I tried capture requests via Interceptor (and Chrome plugin) and it is same, no headers.

@shashankawasthi88 Yes, in the in-session view are headers there in both cases (via proxy with mobile device and interceptor with browser).

**Comment by shashankawasthi88** [comment]
@rubydev thanks for the confirmation. We are working on the issue and will update this thread once the fix is released.

**Comment by shashankawasthi88** [comment]
@rubydev this should be fixed with the latest release.
