### ISSUE TITLE
Add autosave feature 

### ISSUE THREAD

**Issue by vec715** [a85/POSTMan-Chrome-Extension#10655]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request

### Is your feature request related to a problem?

is it so difficult to implement an autosave feature? People have been waiting for this for years.

### Describe the solution you'd like

Add fucking autosave feature!!!

**Comment by DannyDainton** [comment]
@milkiweed There is absolutely no need or reason to use that kind of language.
