### ISSUE TITLE
35 requests aded when copying request from one collection to another

### ISSUE THREAD

**Issue by stevemcmillen** [a85/POSTMan-Chrome-Extension#1065]
I had one collection with 8 requets in it.  I copied this to another collection with 33 requests in it.  But 35 copies of the request was copied into the target collection.

If you have access to my account, its these files (send direct msg to me and I'll provide more details)
Source collection: "Social" Target collection: "Add Like"
Dest Collection: zEMail

Note: Using Postman Sync. I've seen other odd behavior such as all requests from 'User/Account" collection showing up in top level of postman collections panel but only on one machine (this dissapeared after I loged in and out).  I also found that an extra collection was added to Postman (the name was "User' and the contents was all items from the "User collection / Account folder".  To resolve that I deleted the extra user collecton (Note: I did that right before the duplicates copying issue reported in this bug so maybe its related).

**Comment by abhijitkane** [comment]
Can you send your userID / email that you use to sign in to help@getpostman.com?

**Comment by stevemcmillen** [comment]
Sure.  its **\* / ***

Note: this is for the postman sync account at 

---

— Steve

**Comment by abhijitkane** [comment]
We've deleted the duplicate requests .The issue with multiple requests being saved has been fixed with version 3.0.0.22 of the app. Let me know if you see it after you update the app.

**Comment by stevemcmillen** [comment]
Thanks!  Update applied on startup and I see the correction now. Thanks 
for the quick help!!

**Comment by stevemcmillen** [comment]
This issue recurred.  I'm on 3.0.0.22.   This time there are 38 of same item created.  same account as last time if you still have that.  Duplicated items are in 'DB/ES"

**Comment by abhijitkane** [comment]
@stevemcmillen Sorry for the trouble. We've deleted the duplicates, and pushed out v3.0.0.23 of the app.

**Comment by stevemcmillen** [comment]
Thanks!

**Comment by stevemcmillen** [comment]
Confirm fixed.  thanks again.
