### ISSUE TITLE
'Secret' Environment variables still exposes the hidden values in Newman's HTML Reports as well as Console's Request Body

### ISSUE THREAD

**Issue by SiddheshSawant** [a85/POSTMan-Chrome-Extension#10654]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues

### Describe the Issue

Environment/Global Variables we set as Secret does masks the variable values in Environment quick look area.
But when we are actually using these in requests and run it or executing collections using Newman..
After Execution-
In reports, the Request Body shows the actual value we marked Secret for variable.
Same happens when Response Body in console.

### Steps To Reproduce

1. Set new Environment variable with Secret type.
2. Use that variable in request.
3. Run the request.
4. Open postman console.
5. In Console, check for the Request Body of recently executed request.
6. See the Secret variable shows the value without masking it with ******
7. Run particular collection with Newman and generate HTML report.
8. The generated report shows the value without masking it with ******

### Environment Information

```markdown
- Operating System: macOS Monterey v12.1
- Platform Type: Desktop Platform
- Postman Version: 9.13
```

**Comment by DannyDainton** [comment]
Hey @SiddheshSawant

There is currently an open issue created for the Console view:

https://github.com/postmanlabs/postman-app-support/issues/10650

This would also be the case for areas such as the code snippet generator and the documentation etc. 

The masking of the variable is only on the client side to aid in the prevention of sensitive values being seen during screen sharing or _over the shoulder_ attacks. This is not a value that the variable is saved/synced as, this is the reason why you see them in the Newman HTML reports.

Depending on the reporter that you as using, some have the ability to hide certain values or omit the entire request/response body from the final report.

**Comment by DannyDainton** [comment]
Closing this as the issue has been captured in #10650
