### ISSUE TITLE
Feature Request: Set environment variable from popover

### ISSUE THREAD

**Issue by rsweetland** [a85/POSTMan-Chrome-Extension#10653]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request

### Is your feature request related to a problem?

Much efficiency could be gained if the user could set the current value of the env var in this popover:

<img width="329" alt="image" src="https://user-images.githubusercontent.com/81267/153629884-131b6fd4-40c4-4108-8fdf-0107a84213c6.png">

Currently, setting the current value of an env var requires:
* Opening env
* Visually looking for the right env vars....dozens sometimes (cmd + f not supported)
*  Click tiny pencil icon
*  Closing dialog, then going back top request

With only a few env vars it's not problem. With many, it's quite annoying.

### Describe the solution you'd like

While hovering over the env var, a popover dialog is conveniently shown. I would like a text input field there.

### Describe alternatives you've considered

The popover could have a link that opens the env and highlights the proper line to edit.

**Comment by malvikach** [comment]
@rsweetland Thanks for writing to us about this.

I agree that this will definitely help improve productivity!! It also seems that since you are dealing with a lot of environment variables, searching variables is a problem for you. Let me know if you would be up for a short discussion about the issues you are facing. Feel free to drop me a note on _malvika.chaudhary@postman.com_ and I will coordinate a time to speak with you. 
Thanks again.

**Comment by GauthierPLM** [comment]
I would love to see this added too, to ease the workflow with environment variables.

**Comment by skatikia** [comment]
Hi all! This took a while, but I'm glad to announce the completion of our work on this! 🎉

With Postman **V11.14**, we have rolled out multiple improvements to our variables interface, including **the ability to update variable values on the go**.

![edit-value](https://github.com/user-attachments/assets/45aed08c-2982-47e2-9833-d30ddf2e1e3e)

I hope you like this change as much as we do! Update your app to start working with this change and many more, and let us know what you feel ([over a call](https://calendly.com/shobhit-katikia/meet-with-shobhit) or just drop an email to [shobhit.katikia@postman.com](mailto:shobhit.katikia@postman.com)).

[Check out the Postman V11.14 release note](https://arc.net/l/quote/vtemyulc)
