### ISSUE TITLE
update lost data

### ISSUE THREAD

**Issue by lfpdev** [a85/POSTMan-Chrome-Extension#10659]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues

### Describe the Issue

update every day, fuck!!!!!!!!!!!!

### Steps To Reproduce

update every day, fuck!!!!!!!!!!!!

### Screenshots or Videos

update every day, fuck!!!!!!!!!!!!

### Environment Information

```markdown
- Operating System: 
- Platform Type: 
- Postman Version: update every day, fuck!!!!!!!!!!!!
```

### Additional Context?

update every day, fuck!!!!!!!!!!!!

**Comment by numaanashraf** [comment]
Hi, we are facing a service outage and our teams are working on getting the service back up. Please follow https://status.postman.com/incidents/bm5gvvvp5y12 for latest updates on the outage.

This is unrelated to an application update and all your Postman data will be accessible as soon as the service is restored.
