### ISSUE TITLE
On deleting Collection, deleted collection appears and then disappears from the workspace

### ISSUE THREAD

**Issue by nikhilbisht** [a85/POSTMan-Chrome-Extension#10651]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the Issue

Whenever I am deleting any collection from the workspace, first it appears after deleting it and then it disappears

### Steps To Reproduce

1. Open postman desktop app
2. Go to any workspace where collection already exists
3. Now delete any collection
4. **Actual Result**: Observe that after collection is deleted, first it appears on workspace and then disappears.

### Screenshots or Videos

![Uploading collection flickers on deleting it.gif…]()

### Environment Information

```markdown
- Operating System: windows 10
- Platform Type: Native App
- Postman Version: 9.13.1
```

**Comment by giridharvc7** [comment]
@nikhilbisht This is fixed on the web version, can you check and let us know if it works as expected for you? 
The app update will follow up soon

**Comment by nikhilbisht** [comment]
@giridharvc7 Yes, it is working fine on the web.

**Comment by giridharvc7** [comment]
Glad it worked :) Closing this ticket for now! Feel free to open another one if you have any feedback/issues
