### ISSUE TITLE
Creating new api from desktop app returns "SyncRequestService~request: Undefined response"

### ISSUE THREAD

**Issue by Reund0** [a85/POSTMan-Chrome-Extension#10656]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues

### Describe the Issue

Hi.
I wanted to create an API from left side menu in windows app (latest version).
but after submiting, it returned `SyncRequestService~request: Undefined response` error.
and I don't know what's wrong.

### Steps To Reproduce

1. Click api section
2. Click create an api link
3. Submit info
4. return `SyncRequestService~request: Undefined response` error

### Environment Information

```markdown
- Operating System: Windows 10
- Platform Type: Desktop Windows App
- Postman Version: 9.13.1
```

**Comment by abhijitkane** [comment]
@Reund0 In your Windows app, can you confirm if this happening each time / after restarting Postman, and if you're seeing the modal window pictured here?

<img width="580" alt="Screenshot 2022-02-15 at 12 13 53 PM" src="https://user-images.githubusercontent.com/681190/154007098-a85629db-888c-4b54-896a-08bdf7655e4a.png">

To unblock, you can try the web version at https://go.postman.co/ for now.
