### ISSUE TITLE
Ghost tabs - Forever loading, unable to close

### ISSUE THREAD

**Issue by xStoryTeller** [a85/POSTMan-Chrome-Extension#10667]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues

### Describe the Issue

Today I was cleaning up some open tabs I had in postman, saving them to collections and closing them. Afterwards I noticed that I suddenly had a load of "ghost tabs" that indicate they are loading but show no data and are not able to be closed. Restarting didn't help.

### Steps To Reproduce

Unsure. All I did was save some tabs and close them afterwards, but I am unsure if I can replicate this because there are a lot of "ghost tabs" and I can't see if I add to the pile.

### Screenshots or Videos

https://user-images.githubusercontent.com/996131/154220617-7ddf4669-437f-4791-afd4-23427a7e7cbc.mov

### Environment Information

```markdown
- Operating System: Mac OS 11.4
- Platform Type: Native App
- Postman Version: 9.13.2
```

**Comment by DannyDainton** [comment]
Hey @xStoryTeller 

We had a similar issue raised - A possible resolution was talked about in the issues thread.

https://github.com/postmanlabs/postman-app-support/issues/10634

**Comment by xStoryTeller** [comment]
I can confirm that logging in and out fixed the issue, no additional steps were necessary. If I find a way to reproduce I will update this issue. 

I did however notice that those tabs were actual unsaved tabs, which means they are now gone. This isn't the end of the world for me, but it could be for someone else. So closing issue this because re-logging and losing data "fixes" it doesn't seem right, there is an underlaying issue here that has apparently happend at-least 3 times.

**Comment by DannyDainton** [comment]
Thank you for confirming @xStoryTeller - I'm going to close this specific issue and keep an eye out for other reports of the behaviour you were seeing. 

If the unsaved requests had been made, those would be in the Workspace history. That would provide a way to recover and save those requests in a Collection again.
