### ISSUE TITLE
Mock Server not returning correct content-type

### ISSUE THREAD

**Issue by hyNic917** [a85/POSTMan-Chrome-Extension#10661]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues

### Describe the Issue

According to the documentation one should be able to:
- Create a collection with a request. 
- Create an example for that request that returns json and includes the header `Content-Type` with value `application/json`
- Create a mock from the request
- Call the mock and get the response AND the response should be formatted as json in the "pretty" tab

The last step of this is not working as expected. When calling this mock the response header uses `*/*; charset-utf-8` for the `Content-Type` and therefore the response is not property formatted in the "pretty" tab.

### Steps To Reproduce

1. Create a new empty collection
2. Add a new request
3. Add an example to the request, that includes `Content-Type` with value `application/json` to the headers
4. Create a new mock server from the collection
5. Call your endpoint against the mock server
6. Check the postman logs to see that the response header `Content-Type` is not set to `application/json`

### Environment Information

```markdown
- Operating System: Windows 10
- Platform Type: Native App
- Postman Version: v9.13.2
```

**Comment by DannyDainton** [comment]
Hey @hyNic917 

Are you also including the `Content-Type` header in the _Response_ headers section or only in the _Request_ headers section?

![image](https://user-images.githubusercontent.com/17089546/154089256-088e9b7a-4428-40a0-8757-5502cddc6255.png)

**Comment by hyNic917** [comment]
Correct, I am incluing `Content-Type` in the headers of the example

![image](https://user-images.githubusercontent.com/99689476/154090167-523631c3-015e-4891-bbfa-a3c5a0a91a9e.png)

**Comment by DannyDainton** [comment]
That looks like you're adding it to the _Request_ Headers.

There is a separate section for the _Response_ Headers (As shown in my image above) where you would need to add the `Content-Type` header for the response body.

**Comment by hyNic917** [comment]
Thank you!!! I was quite certain PEBKAC, but I just couldn't figure out what I was doing wrong. And I didn't originally notice the screenshot difference.
