### ISSUE TITLE
altering the username of an auth configuration does not have any effect

### ISSUE THREAD

**Issue by adamwong246** [a85/POSTMan-Chrome-Extension#10665]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues

### Describe the Issue

I cannot alter the username of a `basic auth` style authorization. I expect to be able to alter the username, then re-run my tests and get different test results. But after changing this username, or even deleting it entirely, then saving and then running the api calls, the response is of stale data. Changing the username seem to have any effect. Even when omitting an auth configuration entirely, the response body shows the same stale data. 

The configuration file can be found here: https://api-ca.metrc.com/Documentation/postman-json

### Steps To Reproduce

Import the json config
Set the username and password
Run an api call
Note the responses
Change the username and save
Re-Run the api call
Note that the response is identical ( it should not show the same results as the previous username)
Delete the username and save
Re-Run the api call
Note that the response is identical ( it should fail for the lack of a username)

If you perform the same procedure with curl, everything is as expected- The first call and the second call have different results and the third call fails the auth.

### Environment Information

```markdown
- Operating System: Mac 11.2.3
- Platform Type: native
- Postman Version: 9.13.2
```

**Comment by malvikach** [comment]
Hi @adamwong246 sorry to hear about your experience. However, to be able to debug this further and understand your problem, I will need some more details from you.

Could you check the attached video and ensure that when you update your auth username, the auth in the header also gets updated. You can check this in the 'Code' option available in the right-side context bar. This will provide you with the exact curl request and you can test using the same. Read more about using code snippet [here](https://learning.postman.com/docs/sending-requests/generate-code-snippets/)

https://user-images.githubusercontent.com/89449769/154227407-b950f2a1-caa8-415c-9a3d-bb6d5200f698.mov


It will also help me if you could attach a screen recording of your issue. If you are using variables inside the auth, I will request you to ensure that the right variable value is being picked up before you send the request.

**Comment by adamwong246** [comment]
Thanks for you support but I was able to figure it out- I did not know that Postman allowed for scoped authorizations. One of the folders was NOT inheriting the auth from its parent, and this "intercepted" my changes that were made at the root.
