### ISSUE TITLE
Code snippet not working with pm.variables

### ISSUE THREAD

**Issue by akira-ito** [a85/POSTMan-Chrome-Extension#10669]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues

### Describe the Issue

Hi there,
I have an environment called DOMAIN, in my collection I use a pre-request script to change a DOMAIN environment during the requests, but when I receive a code snippet the result is not exported with a new value.

### Steps To Reproduce

1. Create a new collection;
2. Access the"Pre-request Scripts" tab;
3. Write the code: 
    `!function loadDomainExample() {
    pm.variables.set("DOMAIN", 'http://new.url/');
    }();`
4. Add a new request to the current collection;
5. In the request URL, fill in {{DOMAIN}}/postman;
6. Create a new Environment;

> 1. Add a new environment with the name DOMAIN;
> 3. Choose the default type
> 3. Set a value to http://old.url/ (this is an example)
> 4. Then save everything.
7. Choose the new Environment you created to send a request;
8. And, Send it.

### Screenshots or Videos

![postman-error](https://user-images.githubusercontent.com/5279421/154325100-50defbb1-83cd-4a95-bc79-b09d42cf61b2.png)

### Environment Information

```markdown
- Operating System: WIndows 10
- Platform Type: Native App
- Postman Version: 9.13.0

===For more informations====
Postman for Windows
Version 9.13.0
Architecture x64
Platform win32 10.0.19042
```

**Comment by DannyDainton** [comment]
Hey @akira-ito

The code snippet generated is based on the static information placed into request. 

This would resolve variables that in may have set within a certain scope but any manipulation of those variables, in the scripting sandbox, wouldn't have any effect on the generated code.

**Comment by DannyDainton** [comment]
Closing this issue as it's working as expected.
