### ISSUE TITLE
500 Value cannot be null. Parameter name: value

### ISSUE THREAD

**Issue by sradouan** [a85/POSTMan-Chrome-Extension#10677]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues

### Describe the Issue

using get method some thing work and some thing give this Error.

{
    "error": {
        "code": "Unknown",
        "message": "Value cannot be null.\r\nParameter name: value  CorrelationId:  891de6d9-7e3e-4b7a-ba17-b46118329234."
    }
}

### Steps To Reproduce

1-open new tab get request method 
2 -copy or writ a get request text 
3-send action

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/7531726/154603873-9bdfc992-4e1f-4342-835c-a557fe6960fc.png)

### Environment Information

```markdown
- Operating System:  Windows 10 Pro
- Platform Type:  Native App / Postman Web
- Postman Version: Postman v9.14.0
```

### Additional Context?

some thing work and some thing give this Error.

**Comment by xk0der** [comment]
This doesn't look like an issue with Postman.

[HTTP Status 500](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/500) indicates an internal server error.

That indicates that the server encountered an error and was unable to properly handle it while processing the request you sent.

You may want to check with the folks who manage `noovelia.com` server to get more understanding of what is going wrong with the server when processing the request you are sending.

Also check the documentation for the API you are using to understand the error message, from what I see the API is expecting a parameter `value` which you likely did not pass.

Do provide more context, if you feel the issue at Postman's end.
Check this article to find information on how to troubleshoot: https://learning.postman.com/docs/sending-requests/troubleshooting-api-requests/

**Comment by sradouan** [comment]
Thanks xK0der.
