### ISSUE TITLE
Add ability for system admin to export private workspace content

### ISSUE THREAD

**Issue by zoltang01** [a85/POSTMan-Chrome-Extension#10675]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request

### Is your feature request related to a problem?

Hi,

I'd like to request a way for an admin user to migrate the contents of a private workspace belonging to a user into a shared one.
This is in the case of a user that has left the organisation and needs to be removed from the system with content possibly held in a private workspace.

### Describe the solution you'd like

Ability to migrate the private workspace to a shared one.

**Comment by akshay-kulkarni-03** [comment]
@zoltang01 could you explain your use-case a little bit better. You can always convert private workspace into a team workspace if needed or provide access to your private workspace to more people. You can check this learning center [doc](https://learning.postman.com/docs/collaborating-in-postman/using-workspaces/managing-workspaces/#changing-workspace-visibility) to know more about updating visibility of a workspace.

Feel free to re-open this issue if you're facing any difficulty or have a different use-case which we need to solve for.
