### ISSUE TITLE
Invalid padding character when importing HAR files using 'Space' indent character

### ISSUE THREAD

**Issue by juan-belmonte** [a85/POSTMan-Chrome-Extension#10678]
### Is there an existing issue for this?

- [x] I have searched the tracker for existing similar issues

### Describe the Issue

When importing a HAR file in Postman and selecting _Space_ as indent character, the result example does not contain whitespaces but the word `Space`.

This issue is not happening when selecting 'Tab'. Examples are correct.

### Steps To Reproduce

1. Export a sequence of requests and responses in Chrome using its DevTools (_Save all as HAR with content_).
2. Import it in Postman with the following advanced options:
    * Set indent character: Space
    * Include cookies from import: Yes
    * Include responses from import: Yes
    * Folder organization: Page
 3. Verify imported collection by expanding it and checking any response example.

### Screenshots or Videos

<img width="201" alt="raw-example-contents" src="https://user-images.githubusercontent.com/88533684/154659681-55f6e0ea-26a0-46e1-a5e0-351076a893b8.png">

### Environment Information

```markdown
- Operating System: macOS Big Sur 11.5.2 (20G95)
- Platform Type: Native App
- Postman Version: 
Version 9.13.2
UI Version: 9.13.2-ui-220214-1351
Desktop Platform Version: 9.13.0 (9.13.0)
```

**Comment by diyaeninan** [comment]
Hi @juan-belmonte, this issue has been fixed in v9.15.4
