### ISSUE TITLE
Empty response is being displayed as "Malformed JSON"

### ISSUE THREAD

**Issue by boazrymland** [a85/POSTMan-Chrome-Extension#1067]
Hi,

I hope this wasn't reported earlier - couldn't find such an issue.

I'm using postman against a restful server. The server API dictates that the response is sometimes in http code 200, or 500, but with no http body.

Postman insists on telling me on those body-less responses that their JSON is malformed - on the 'Pretty' body output, that is. 

Expected result: in my taste, on the 'pretty' output tab, Postman should first check if the response is empty and if so - should render **nothing** in the output.

Thanks!

**Comment by abhijitkane** [comment]
This shows a 'No response received' message now - v3.0.4.
