### ISSUE TITLE
When I delete a collection it reappears

### ISSUE THREAD

**Issue by byrdman** [a85/POSTMan-Chrome-Extension#10671]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues

### Describe the Issue

I right click on a collection and pick delete.  I confirm the delete, it goes away.  Then within 30 seconds it shows back up.

### Steps To Reproduce

1. Right click on a collection
2. Pick delete
3. Confirm the delete
4. Wait 30 seconds or so

### Environment Information

```markdown
- Operating System: Windows 10 
- Platform Type: Native App
- Postman Version: 9.13.2
```

**Comment by byrdman** [comment]
Sometimes if you let it sit for a bit it'll go away again, other times you have to delete it again.

**Comment by giridharvc7** [comment]
This has been fixed in the latest app version that's being rolled out (9.14) and available on the web version, can you please check and let us know @byrdman ?

**Comment by byrdman** [comment]
I concur that it is corrected, thanks for the quick turnaround.
