### ISSUE TITLE
"Find and Replace" deletes body of request

### ISSUE THREAD

**Issue by dberchtold** [a85/POSTMan-Chrome-Extension#10687]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues

### Describe the Issue

when using "Find and Replace" body of request is removed where string is found in body

### Steps To Reproduce

1. open "Find and Replace"
2. search for a string which is also present in body part of some request
3. apply "replace with"
   -> found: stirng is not replaced, but complete body is removed

### Screenshots or Videos

![findReplace](https://user-images.githubusercontent.com/9194415/154951778-35f00b82-451f-4938-a580-fd2cbcad773d.gif)

### Environment Information

```markdown
- Operating System: Windows 11
- Platform Type: Native App
- Postman Version: v9.14.1
```

**Comment by giridharvc7** [comment]
Sorry that you facing this and Thanks for reporting, we will have a look into it.

**Comment by calebruz** [comment]
A similar issue happens to me but instead of the body being removed, most of the URL gets deleted if I have a request open that will be affected by the replace

**Comment by giridharvc7** [comment]
This should be fixed in v9.14.7 and above, can you please check your version/update the app and let us know if this worked for you?
@calebruz @dberchtold

**Comment by shubhbhargav** [comment]
@calebruz @dberchtold Closing this issue for now. Let us know if you are still facing it.

**Comment by dberchtold** [comment]
checked using version v9.14.13 -> issue is solved.
