### ISSUE TITLE
Error: Invalid protocol: https

### ISSUE THREAD

**Issue by okutbay** [a85/POSTMan-Chrome-Extension#10681]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues

### Describe the Issue

Not sure if this is a bug but after i imported the proto file i cannot send request and getting the same error for http and https. Any help would be appreciated. Thanks in advance.

### Steps To Reproduce

1. Add new gRPC request
2. Set URL
3. Add proto file
4. Generate example message
5. Hit invoke

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/30014/154817936-ebc0877f-abfa-4305-8390-eb3e18769814.png)

### Environment Information

```markdown
- Operating System: Windows 10
- Platform Type: Native App
- Postman Version: Postman v9.14.1
```

**Comment by codenirvana** [comment]
@okutbay can you check if removing the protocol from the URL or replacing it with `grpc://` fixes your issue?

**Comment by okutbay** [comment]
thanks @codenirvana it fixed issue for http. 

But when i changed the port to 5001 i got no result
How can i use secure one https->?

![image](https://user-images.githubusercontent.com/30014/154924035-15bb6596-197c-45d9-8195-1cedf840612b.png)

Thanks in advance.

**Comment by lukasvosyka** [comment]
Is SSL support still missing? Facing same issue. I receive a Status 13 INTERNAL.
When I try to use server side reflection over SSL I get this error:
13 INTERNAL: Received RST_STREAM with code 2 triggered by internal client error: Protocol error

Tried different URLs
xxxx.com:443
grpc://xxxx.com:443
https://xxxxx.com

**Comment by codenirvana** [comment]
@lukasvosyka TLS is supported, you need to add client certificates in settings.

<img width="1552" alt="Screenshot 2022-04-01 at 9 09 34 AM" src="https://user-images.githubusercontent.com/4865836/161191015-93f7026a-684e-4d7c-80af-f434f8cb051b.png">
<img width="1552" alt="Screenshot 2022-04-01 at 9 11 50 AM" src="https://user-images.githubusercontent.com/4865836/161191028-10145ef3-9ca4-4946-85b7-cdb49556c320.png">

Just use the TLS port with `grpc://` protocol (`https://` won’t work).
