### ISSUE TITLE
Unable to render fonts in dialog box. Getting square boxes in place of font

### ISSUE THREAD

**Issue by patilpratap** [a85/POSTMan-Chrome-Extension#10688]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues

### Describe the Issue

Dialog boxes like multi part form file browse dialog and the hardware acceleration dialog from the top menu are showing squares instead of fonts.

### Steps To Reproduce

1. Open new request tab
2. Select body
3. Select body type as form-data
4. Select file as the mutli part form type
5. In value section you will get a "select files" button
6. Click on it. A dialog opens with fonts shown as squares

### Screenshots or Videos

![Screenshot from 2022-02-22 20-15-45](https://user-images.githubusercontent.com/11796310/155155729-56b94bf6-8bbf-4288-8abf-554856d1fe19.png)

### Environment Information

```markdown
- Operating System: Ubuntu 20.04
- Platform Type: Native App
- Postman Version: 8.12.5
```

**Comment by leberknecht** [comment]
Also happens on `5.15.19-1-MANJARO` with `Postman v9.13.2`
![image](https://user-images.githubusercontent.com/1165177/155558675-a540bfee-c3ad-4186-a4dc-ce681cdd9a6e.png)
That is the `upload file` dialog

**Comment by jimlinx** [comment]
I had the same issue on Fedora if I installed through Snapstore. Try uninstall and reinstall from Flathub. I had another issue with Slack where I was not able to type Chinese characters with the Snapstore version but worked fine when I switched to Flathub version.

**Comment by RaisinTen** [comment]
> I had another issue with Slack where I was not able to type Chinese characters

@jimlinx were you trying to write on a dialog box?

**Comment by jimlinx** [comment]
@RaisinTen That's right, trying to type into a dialog would just end up as English characters even though the input has been set to Chinese.

**Comment by RaisinTen** [comment]
Thanks for confirming, closing as this is a duplicate of https://github.com/postmanlabs/postman-app-support/issues/10449.

**Comment by dhruvilpirimid** [comment]
For People facing this issue:

Clearing the chromium cache worked for me:
`rm -rf ~/snap/postman/common/.cache`

Close all your active chromium windows (Including Postman) after running this and open again. The issue should be fixed.
[Source](https://bugs.launchpad.net/ubuntu/+source/chromium-browser/+bug/1864365)

**Comment by soorajsprakash** [comment]
![image](https://github.com/user-attachments/assets/02ff5aad-899c-41ee-a54d-45535e31d93d)


Updated to this latest version from snap, and the issue is fixed.

**Comment by tcrawf** [comment]
I cleared the cache. This did not work. Did an upgrade to v11/stable and this did not appear to work. I cleared the cache again and now it works.  Postman appeared to hang the first time it opened the dialogue after clearing the cache, but with some patience I could proceed.

**Comment by OvervCW** [comment]
@tcrawf Thanks, that worked!

For others who installed Postman using snap, here's how you upgrade to v11/stable:

```shell
snap refresh postman --channel=v11/stable
```

**Comment by yahya-aghdam** [comment]
I used custom font with Tweak, and this is fixed it:
```bash
rm -rf ~/snap/postman/common/.cache/fontconfig/
rm -rf ~/snap/postman/*/usr/share/fonts/
rm -rf ~/.cache/fontconfig/
sudo rm -rf /var/cache/fontconfig/*
fc-cache -r -v
```

**Comment by MejanH** [comment]
> rm -rf ~/snap/postman/common/.cache/fontconfig/
> rm -rf ~/snap/postman/*/usr/share/fonts/

Thanks, this helped me
