### ISSUE TITLE
All Postman Request Tests are all failing with JSON.parse() error

### ISSUE THREAD

**Issue by stevemcmillen** [a85/POSTMan-Chrome-Extension#1068]
All the tests I have stored in postman are now failing.  These were working in the previous build.  I was just updated to 3.0.0.23 (worked in 3.0.0.22).

> Test script execution failed
> 
> Error message:
> 
> There was an error during JSON.parse(): Unexpected end of input

This is blocking our test suites.  Bad timing :(

**Comment by abhijitkane** [comment]
The fix for this is out in version 3.0.0.24 (which is out on the Chrome store). This release should smooth things out.
