### ISSUE TITLE
Disable pop-up about automatic updates

### ISSUE THREAD

**Issue by ghost** [a85/POSTMan-Chrome-Extension#10682]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request

### Is your feature request related to a problem?

Whenever app launches it distracts me from doing my job by showing meaningless notification about new version available.

### Describe the solution you'd like

There should be an option to disable any notifications shown by the app

### Describe alternatives you've considered

Switching to less annoying app, maybe Insomnia.

**Comment by numaanashraf** [comment]
@fires3as0n Could you send us a screenshot of the notification you find distracting? We are working on simplifying our update notification currently and this will help us iron out these issues.

**Comment by akshaytate** [comment]
Hi @fires3as0n , thanks for bringing this issue to light.

As of Postman v9.14.8, we have disabled showing the release notes notification for app updates.

Please feel free to reach out in case of any issues / concerns.
