### ISSUE TITLE
Bootcamp lessons stop when opening a request

### ISSUE THREAD

**Issue by august159** [a85/POSTMan-Chrome-Extension#10684]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues

### Describe the Issue

When following any step-by-step tutorial, the next action pop-up does not appear after clicking on a request to open it as instructed. 
Once out of the lesson, the resume button restarts the lesson.
Therefore, I cannot complete any tutorial within the bootcamp.

### Steps To Reproduce

1. Start any lesson from the Bootcamp
2. Follow the instructions until you are asked to open a request by clicking on it
3. Nothing happens. Clicking on Resume lesson brings back to the first step of the lesson

### Screenshots or Videos

https://www.loom.com/share/d0d5197e2d2d4081919001546478df56?sharedAppSource=personal_library

### Environment Information

```markdown
- Operating System: Windows 11 Professionnel Insider Preview build 22533.1001
- Platform Type: Windows application
- Postman Version: Postman v9.13.2
```

**Comment by august159** [comment]
Same behaviour occurs with the browser agent:

- Postman for Web Version 9.14.4-220218-0400
- Chrome 101 / Windows 10

**Comment by willwolfram18** [comment]
I wanted to add that I'm seeing this same issue with the following modules as well.

### Desktop App
Postman Version: 9.14.0
* Debugging and manual testing > Environment variables
* Debugging and manual testing > Global variables
* Designing and mocking APIs > Design an API in a minute
* Designing and mocking APIs > Design an API

### Browser app
Postman version: 9.14.15-220307-1430
Chrome 99 / Windows 10
* Debugging and manual testing > Environment variables
* Debugging and manual testing > Global variables

**Comment by whiteknightjanus** [comment]
I have the same issue occurring in Design an API In a Minute - not sure if it's the same as the reported issue just above, but when I get to the step to open the new environment for the mock server, when I click on the environment drop down, the Bootcamp GUI disappears. Clicking on Continue Learning resets the lesson completely.

Postman Desktop version Version 9.14.12

**Comment by ghost** [comment]
https://user-images.githubusercontent.com/95380158/160397496-b6116032-81ef-4609-abae-8a902bbdbd68.mp4

Here's a video of it happening.

**Comment by mrcaidev** [comment]
Same issue with Postman Desktop v9.17.2 on Windows 11. Many of the bootcamp tutorials stop their instructions in the middle, and I clicked around the app with no further information found.

**Comment by saskiastekelenburg** [comment]
I have this same issue. Is it looked into already?

**Comment by danielbeveridge** [comment]
![image](https://user-images.githubusercontent.com/107993117/174997606-7029a293-f217-4e8d-8de6-4e42ff4f91f9.png)

Can't be completed

**Comment by sivcan** [comment]
Thanks for raising the issues folks. We're working on fixing these internally and I'll update here once all these are fixed.

**Comment by caciulla** [comment]
Having the same issue reported by whiteknightjanus. Desktop version 9.30.1

**Comment by VictoriaBlaustein** [comment]
Same issue as reported by whiteknightjanus. MacOS Desktop version 10.0.40.

**Comment by FunkySwindells** [comment]
Postman v10.9.4

Bootcamp/Designing and mocking APIs the lesson "resumes" from 0% after disappearing at "Click Next" to Create a Mock Server.

This also halts progress on https://learning.postman.com/docs/sending-requests/requests/ "Open the Bootcamp in Postman and follow Designing and mocking APIs to import some requests you can use for exploring Postman." I assume.

**Comment by arlemi** [comment]
Hey there,

I'm closing this issue as the Bootcamp is not available in the app anymore from the March 2023 (v10.12) release.

If you're interested in Postman training courses here's a few resources to check out:
-  [Postman Quickstarts](https://quickstarts.postman.com/) 
-  [Postman Academy](https://academy.postman.com/)
- [Postman Intergalactic webinars](https://www.postman.com/events/intergalactic/)
