### ISSUE TITLE
When importing a duplicate collection and selecting replace, wind up with 2 collections with same name

### ISSUE THREAD

**Issue by byrdman** [a85/POSTMan-Chrome-Extension#10691]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues

### Describe the Issue

When I import a collection that duplicates an existing collection I'm given a prompt to "import as copy or replace".  If I select "replace" I now wind up with 2 collections with the same name.  It used to remove the existing collection first.

### Steps To Reproduce

1. Select import
2. Pick a collection json file that duplicates a collection previously created/imported
3. Select the "replace" option
4. Allow it to import.

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/2364470/155326088-9c1441b1-b603-430d-a5e9-526714262f21.png)

### Environment Information

```markdown
- Operating System: Windows 10
- Platform Type: Native App
- Postman Version: 9.14.1
```

**Comment by giridharvc7** [comment]
While there's a UI bug where it seems like a new collection is being uploaded, we still replace the existing collection. 
Can you try this just once on the web version of the app and let us know if you face this? Also a screen recording would really help if possible

**Comment by giridharvc7** [comment]
@byrdman can you confirm if you still face this issue? If so, please share some logs and also screenshots if possible.

**Comment by byrdman** [comment]
It appears to only happen on "large" collections where the process times out.
Initially it asks if I want to replace or import as a copy, if I select "replace" it does this:
![image](https://user-images.githubusercontent.com/2364470/161979978-a6367844-982a-46e2-8a1e-693fae189314.png)

Sometimes it cleans up after itself quickly, sometimes it takes a while, right now it's stuck like this
![image](https://user-images.githubusercontent.com/2364470/161982373-05a6173a-1474-471c-a9a2-71be71bc3293.png)

Here's the sizes of the collections being imported, notice the 4 that are duplicated are all "large".  They all also initially give a "failed to import" error.  Deleting will also give a "failed to delete" error.
![image](https://user-images.githubusercontent.com/2364470/161981869-bc4cf237-f30e-49ba-b22c-9cd8d50eae0f.png)

**Comment by byrdman** [comment]
This was fixed by the performance updates that happened last fall.
