### ISSUE TITLE
Postman environment variables are not appearing in generated documention

### ISSUE THREAD

**Issue by ats1999** [a85/POSTMan-Chrome-Extension#10699]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues

### Describe the Issue

I have added the below code in collection pre request script
```js
pm.request.headers.add({key: 'x-access-token', value: '{{TOKEN}}'})
```
The header is being sent to the server and it's working. 

But, when I tried to generate documentation, then there is no header value present in the documentation.

![Uploading Screenshot from 2022-02-25 07-07-03.png…]()

### Steps To Reproduce

- Create a environment variable
- use variable in collection
- Generate documention

### Environment Information

```markdown
- Operating System: Ubuntu LTS (20.04)
- Platform Type: Desktop(Native)
- Postman Version: 8.12.5
```

**Comment by DannyDainton** [comment]
Hey @ats1999 

That pre-request script is altering the request headers at runtime (When you hit the Send button) so it wouldn't appear in the documentation. For that header to be in the documentation, it would need to be manually added to the request headers section.

**Comment by ats1999** [comment]
So, basically I need to manually put the headers in all API requests?

**Comment by DannyDainton** [comment]
In the context of the basic documentation generation and for it to be visible in every request, yes. If you're only sending requests and having that script perform an action at runtime, no. 

You can still make a reference to the script in the Collection, Folder or Request description explaining what the script doing, the same for any script in the Collection. This script would be included in the Collection if you're sharing it with other users.

**Comment by DannyDainton** [comment]
Closing this issue for now.

The `Pre-request Script` which is altering the request headers at runtime (When you hit the Send button), wouldn't appear in the documentation.
