### ISSUE TITLE
Attach an image (or color) to environments

### ISSUE THREAD

**Issue by DenDuze** [a85/POSTMan-Chrome-Extension#10690]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request

### Is your feature request related to a problem?

It's not immediately clear against witch environment-settings I'm working when I open PostMan

### Describe the solution you'd like

It would be nice that I coul'd attach an image to every environment and that the background of (a part) of postman shows that image based on the current selected environment to make it visually more clear.
If an image is to difficult maybe a color can also be usefull (but image is better I think)

**Comment by DannyDainton** [comment]
Duplicate of https://github.com/postmanlabs/postman-app-support/issues/8260
