### ISSUE TITLE
Keeps Conflicting, doesn't actually sync, progress lost

### ISSUE THREAD

**Issue by SteveHipolito** [a85/POSTMan-Chrome-Extension#10694]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues

### Describe the Issue

I edit a request, save, sync. Conflict every time after syncing.

Progress is lost every time I close/launch Postman.

### Steps To Reproduce

1. Open any request
2. change something
3. Save
4. Sync
5. Close request
6. Close Postman
7. Launch Postman

Changes are gone.

### Environment Information

```markdown
- Operating System: MacOS Big Sur 11.6.1
- Platform Type: Native App
- Postman Version: 9.14.4
```

### Additional Context?

This started happening Feb 22

**Comment by giridharvc7** [comment]
Thank you for reporting, we are looking into this right away.

**Comment by giridharvc7** [comment]
@SteveHipolito Can you share some screen recording and logs?

**Comment by giridharvc7** [comment]
@SteveHipolito We've raised a hotfix to this issue. Can you confirm if you are facing this problem? Your app would have updated to version 9.14.5, if not - Please close and reopen the app.

**Comment by hkarjala** [comment]
Updated to version 9.14.5 - app restarted (also cache cleared & reloaded) - did also signout / signin just in case.
I'm at least still having the same exact problem. Web -> desktop app direction sync seems to work fine.  App -> Web not, especially when duplicating a request and modifying the copied request.

Not sure if any help, but developer tools console gets following when saving modifications to request at desktop App:

RequestInterfaceV2.ts:167 Uncaught (in promise) Error: Invalid updates for request dataMode
    at Object.<anonymous> (RequestInterfaceV2.ts:167)
    at Generator.next (<anonymous>)
    at RequestInterfaceV2.ts:8
    at new Promise (<anonymous>)
    at r (RequestInterfaceV2.ts:4)
    at Object.t.updateRequest (RequestInterfaceV2.ts:154)
    at i.dispatchUpdate (RequestBufferedStore.ts:7)
    at i.<anonymous> (BufferedItemStore.ts:103)
    at Generator.next (<anonymous>)
    at BufferedItemStore.ts:14
    at new Promise (<anonymous>)
    at o (BufferedItemStore.ts:10)
    at i.processUpdate (BufferedItemStore.ts:89)
    at i.<anonymous> (BufferedItemStore.ts:85)
    at Generator.next (<anonymous>)
    at BufferedItemStore.ts:14
    at new Promise (<anonymous>)
    at o (BufferedItemStore.ts:10)
    at i.update (BufferedItemStore.ts:81)
    at DBResourceWriter.js:162
    at h (DBResourceWriter.js:213)
    at Object.save (DBResourceWriter.js:264)
    at Object.save (ResourceWriter.js:32)
    at Object._save (EditorService.js:212)
    at EditorService.js:320

**Comment by giridharvc7** [comment]
@hkarjala Sorry that you are still facing this issue. Can you help understand what you mean by this?  A Screen recording will really help us out if possible

```
Web -> desktop app direction sync seems to work fine. App -> Web not, especially when duplicating a request and modifying the copied request.
```

**Comment by Soni-Prince** [comment]
Facing the same issue, requests are not saving, I have tried to re-install the postman just worked for a few hours only and then the same issue.

**Comment by giridharvc7** [comment]
@Soni-Prince Sorry that you are facing this issue. We are looking into it as we speak - Can you share some log or screen recording that will help us debug this faster? 

@hkarjala the logs were really helpful. We'll get back to you shortly on this

**Comment by giridharvc7** [comment]
We've released a hotfix v9.14.6 - This should fix it. Can you please try and let us know? @Soni-Prince @hkarjala 
For Updating the app , just close the app and open it again.

**Comment by hkarjala** [comment]
Haven't been able to reproduce the problem with v9.14.6 now - tested in same collection/fork I had issues with in previous versions. Thanks!

**Comment by giridharvc7** [comment]
Thank you @hkarjala. 
@Soni-Prince Let me know if this is fixed for you as well.

**Comment by Soni-Prince** [comment]
Now it's working fine for me.
Thanks.

**Comment by Soni-Prince** [comment]
Again facing the same issue 😔

**Comment by giridharvc7** [comment]
@Soni-Prince Thanks for getting in touch again, Sorry that you are facing this. We are releasing a hotfix soon. Appreciate your patience.

**Comment by giridharvc7** [comment]
We've raised another hotfix, this should be v9.14.7 . Can you check and let us know if you still face this @Soni-Prince

**Comment by giridharvc7** [comment]
Closing the issue for now as this is been handled in v9.14.7+ , please feel free to reopen in case you find conflicts again.
