### ISSUE TITLE
Postman on half-screen without horizontal scrolling

### ISSUE THREAD

**Issue by Sti2nd** [a85/POSTMan-Chrome-Extension#10701]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request

### Is your feature request related to a problem?

On a 1080p when Postman takes half of the screen the Postman UI doesn't fit. A horizontal scroll bar appears which makes it possible to use Postman but a lot more inefficient.

Notice how the UI is cut off on the right side.
![image](https://user-images.githubusercontent.com/6373430/155682595-9d7b366c-820e-47fd-953b-489db01faff4.png)

### Describe the solution you'd like

Make Postman UI work on a half 1080p screen. When hiding the left sidebar there is plenty of room for the UI on the right! I am guessing there is a min-width distance that is too large.

![image](https://user-images.githubusercontent.com/6373430/155683505-a013cc2d-f892-4527-b0fd-e8ba00dd8bc1.png)

**Comment by KeithETruesdell** [comment]
~i think if the URL bar wasn't set to such a massive minimum size this would work~
So there isn't a minimum width.  But setting the element `request-editor__main__url-group` in the file requester.scss (also effects `request-editor__main` ) to have a flex of .5 or .85 I think would solve many headaches.  It may not be the prettiest.  But there is something else that is forcing the horizontal scroll and the window to think it is bigger than it is.

**Comment by hfhchan** [comment]
There's a script capping the width of requester-contents-pane to 1130px. If it could be slightly reduced to 1080px, the window would fit comfortably in a standard 1080p monitor in the vertical orientation (1080 x 1920).

**Comment by diptarag** [comment]
This should be fixed in v10.14
