### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by duong-hspace** [a85/POSTMan-Chrome-Extension#10702]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues

### Describe the Issue

When i download and install it not working

### Steps To Reproduce

1. Download at https://dl.pstmn.io/download/latest/win64
2. Install

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/91865047/155692730-89b05483-2b41-4a2b-aa70-5f07da16ce3d.png)

### Environment Information

```markdown
- Operating System: Window 11
- Platform Type: Desktop
- Postman Version: 9.13.0
```

**Comment by kamalaknn** [comment]
Hey, @duong-hspace 

We are not able to reproduce this issue on our side with the download link you have shared. We would need more information to pinpoint the cause of this issue. 

Could you share the logs with us at `help@postman.com`? You can find the logs here `View -> Developer -> View Logs in Explorer`. Just zip all of the files and send them over to us via email.

It will be great if we can do a screen-sharing session to go over the issue if that works for you.

**Comment by postman-staff** [comment]
Hi @duong-hspace
Thanks for reaching out to Postman Support.

Sorry that you are facing issues while installing Postman but we are happy to help.

To fix the installation issues we can try renaming/clearing the local postman folders and re-install the application. You can find the full instructions for doing so in the below article.
-> https://support.postman.com/hc/en-us/articles/360025359014-How-to-resolve-the-Could-not-open-Postman-error-

If possible you can also try to install our Canary build and see if it works as expected:
https://postman.com/downloads/canary
The canary build will be installed in an entirely separate app/directory – if it works as expected, feel free to continue using it or to uninstall it entirely.

Alternatively, you can also try using our web application(go.postman.co) to unlock you for now.
Hope this helps!

If the issue persists then as mentioned in the previous response we would recommend you to submit a request along with the app logs to check and help further.

via @Lincimary | Postman Support
