### ISSUE TITLE
Sync issues

### ISSUE THREAD

**Issue by TheEzraMiller** [a85/POSTMan-Chrome-Extension#10703]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues

### Describe the Issue

Conflicts on tabs that don't actually have anything to conflict with.

### Steps To Reproduce

It takes quite a few hours to get to it so cannot really film it, but steps I’m following:

- Close all requests
- Open 4 unique requests (I’ve made sure that at no point they are opened in multiple tabs – each only once and only one postman instance is opened)
- Send some of the requests (my request does contain a dynamic variable {{n}} that as a ‘Pre-Req’ get’s set to current date)
- Wait for a few hours without changing anything
- And the requests have all gone into conflicts – also note in my screenshot you can see that even tho active tab is in conflict the save button is disabled since I’ve not changed anything in the request only sent it as is a few times

Hope this helps locating the bug.

### Screenshots or Videos

![image002](https://user-images.githubusercontent.com/2478416/155730203-0f6b6af6-c5f4-4aea-bd5c-292c0afa6142.png)

### Environment Information

```markdown
- Operating System: MacOS 12.2.1
- Platform Type: MacOS
- Postman Version: Version 9.14.1
UI Version: 9.14.1-ui-220218-0300
Desktop Platform Version: 9.14.0 (9.14.0)
```

**Comment by giridharvc7** [comment]
Thanks for reporting this. We are actively tracking this here https://github.com/postmanlabs/postman-app-support/issues/10694

**Comment by giridharvc7** [comment]
@TheEzraMiller  can you try this now? we've fixed it in v9.14.6.
Just close and open your app to update

**Comment by TheEzraMiller** [comment]
On Closing and re-opening the app i got version: “ You are up to date! Postman v9.14.5 is the latest version.” not your mentioned.

**Comment by giridharvc7** [comment]
Can you share your postman id?

**Comment by TheEzraMiller** [comment]
Where do i get that?

**Comment by giridharvc7** [comment]
The email id you use to sign in to your postman account. 
Also, can you try it after a few hours, the update sometimes takes time.

**Comment by TheEzraMiller** [comment]
Just got the new update, will let you know if the issue repeats.

**Comment by giridharvc7** [comment]
@TheEzraMiller Wondering if the issue was fixed for you

**Comment by TheEzraMiller** [comment]
Yes thank you no further issues with this in past few days.
