### ISSUE TITLE
Corrupted Update removes the program from initial folder

### ISSUE THREAD

**Issue by martinlindenberg** [a85/POSTMan-Chrome-Extension#10714]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues

### Describe the Issue

I've installed Postman in a separate folder, named Postman and created a shortcut to easily start that app. As icon for that shortcut i am selecting the app icon which is located somewhere in that folder.

After some days of usage that link's icon disappears and the app cannot be started with that link anymore.
 
What i have found out so far is that the folder is getting renamed from `Postman` to `Postman-1645601205598-old` and the initial Postman folder only contains a fraction of the needed files. It looks like a broken or interrupted update. 

The only fix i know for this issue is to replace the whole folder with a fresh installation. 
But now after having done this for about 4-5 times, i think it is time to rethink that.

Current Postman version: v9.14.7 (issue was also visible in prev. versions)
OS: Ubuntu 21.10 with XFCE

Questions: 
1. Can anyone confirm this issue ?
2. Could it be an update in background which is interrupted when the machine is shut down?
3. Feature request: Is there a way to disable automatic updates completely?

### Steps To Reproduce

* Use Ubuntu with XFCE
* Install Postman to your preferred folder.
* Create a link to the app and use the app icon as icon for your link (makes it easier to see when it happened again)
* use postman regularly
* wait for updates to happen automatically
* your link will lose its icon and postman cant be started with that folder anymore
* postman folder is renamed to `Postman-timestamp-old`

### Environment Information

```markdown
- Operating System: Ubuntu 21.10, XFCE
- Platform Type: Native app -> https://dl.pstmn.io/download/latest/linux64
- Postman Version: v9.14.7
```

### Additional Context?

Maybe the same issue:
https://github.com/postmanlabs/postman-app-support/issues/10698

**Comment by twitharshil** [comment]
Hey @martinlindenberg 

Thanks for reporting the issue! Apologies for the trouble caused from our end. It seems to be a genuine issue & a fix for this is out with the Postman v9.14.0+ onwards. 

Similar ticket https://github.com/postmanlabs/postman-app-support/issues/10679#issuecomment-1046446183
