### ISSUE TITLE
Postman in a secure enviroment - no internet access - problems with Basic Auth Tab

### ISSUE THREAD

**Issue by hagerup** [a85/POSTMan-Chrome-Extension#1071]
All,

I have a client where all servers have no internet access. Thus I moved a newest ChromeStandaloneSetup.exe and POSTMan-Chrome-Extension-0.8.4.12.zip to one server and installed the two.

I do see the PostMan gui in the Chrome browser but all buttons are inactive - if I for instance click "Basic Auth", I'm forced to stay in a (non-functioning) Normal tab.

I'm allowed  start the Chrome as local administrator and I can configure Chrome as I please.

Any suggestions how to move from here? Or pointers to other downloads that will make Postman work here?

FYI: Postman works fine for me in enviroment with internet access - where Postman was installed over the internet.

Cheers from Copenhagen

Martin

**Comment by abhijitkane** [comment]
Sorry for the delay on this. The source code from the repo needs to be built to create a Chrome app. For now. You can take the built app from C:\Documents and Settings*UserName*\Local Settings\Application Data\Google\Chrome\User Data\Default\Extensions\fhb...

If you don't find the app folder there, you can check the path here - http://stackoverflow.com/a/14544700/384155
