### ISSUE TITLE
Unable to load tests/Create new Requests in all Collections

### ISSUE THREAD

**Issue by DivyaMoryani** [a85/POSTMan-Chrome-Extension#10713]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues

### Describe the Issue

I had signed-out and Signed-In postman, I can see all the Collections, but the tests dont load, 
When I try to create a new API Request, It returns : An error occured while fetching permissions. 

### Steps To Reproduce

1. Sign-out
2. Sign-in 
3. Switch to Any workspace -> My Workspace or Teams Workspace. 
4. The Collections load but tests are not loading

### Screenshots or Videos

<img width="374" alt="image" src="https://user-images.githubusercontent.com/65155227/156303740-b87eaa5d-f29e-42ce-a69b-09219dfb6930.png">

![image](https://user-images.githubusercontent.com/65155227/156303823-30f91946-3b4e-4238-917c-e97fc9d5389d.png)

### Environment Information

```markdown
Version 9.14.7

UI Version 9.14.7-ui-220228-1230

Desktop Platform Version 9.14.0

Architecture x64

OS Platform OS X 18.7.0
```

**Comment by giridharvc7** [comment]
Sorry that you are facing this @DivyaMoryani , can you share some logs from the dev console?

**Comment by shubhbhargav** [comment]
@DivyaMoryani Just checking in. Let us know if you are still facing this issue.

**Comment by giridharvc7** [comment]
@DivyaMoryani @Prakash2024 @skirankumars31 Checking in to see if you still face this issue.

**Comment by giridharvc7** [comment]
Closing this as this might have been an intermittent issue. 
Feel free to re-open the ticket if you come across this again
