### ISSUE TITLE
Maximum call stack size exceeded when generating collection from WSDL/API

### ISSUE THREAD

**Issue by Jiarius** [a85/POSTMan-Chrome-Extension#10717]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues

### Describe the Issue

Hi,

This is maybe duplicate of #10266 (closed - same error message which was thought to be fixed)

I'm trying to import a WSDL API for testing. 
Getting the error on API import screen also later in the draft clicking "Generate Collection"

"Couldn't generate collection. Maximum call stack size exceeded."

### Steps To Reproduce

1. File > Import > Link (https://test.lightstone.co.za/avm/webservices/properties.asmx?wsdl)
2. Paste url
3. Select 'Generate collection from imported APIs'
4. Link this collection as 'Test Suite' > Import

### Screenshots or Videos

<img width="835" alt="image" src="https://user-images.githubusercontent.com/46221185/156379552-ea47fa40-97c3-4f72-925b-d50012274577.png">

<img width="360" alt="image" src="https://user-images.githubusercontent.com/46221185/156379616-d5cb680b-ec3a-4bd6-8540-5562119dd862.png">

<img width="980" alt="image" src="https://user-images.githubusercontent.com/46221185/156379409-3e6c0f6c-0a31-438e-a426-c7404d78e579.png">

### Environment Information

```markdown
- Operating System: macOS 10.15.6
- Platform Type: Native App
- Postman Version: 9.14.7
```

**Comment by aranya0** [comment]
[ITEM.wsdl.txt](https://github.com/postmanlabs/postman-app-support/files/8786482/ITEM.wsdl.txt)

Hi

I have the same problem with the wsdl in the attachment. Is there already a solution available?

Thank you.

**Comment by stanislavnastasiu-dev** [comment]
same

**Comment by VShingala** [comment]
@Jiarius @aranya0 @stanislavnastasiu-dev We've identified the issue here and will be fixing it soon. I'll update this thread once it's available.

**Comment by JayHayAdminaccount** [comment]
@VShingala Is there any update on this issue. I am running into the same thing.

**Comment by VShingala** [comment]
Hey @JayHayAdminaccount, for this issue we'll be providing a fix by next week. I'll share the update here as well.

**Comment by akshaydeo** [comment]
Hey @JayHayAdminaccount, sorry for the delay, we are fixing this issue today. I will update this thread with the fixed version of the app.

**Comment by VShingala** [comment]
@JayHayAdminaccount We've already solved one of the issue that caused this, could you check and let us know if it's working. Also if not working, could you share with us the WSDL definition (or a simple version where it's failing), so we can take a detailed look here? 

@Jiarius We've fixed issue that caused the definition mentioned by you to not working. I've verified the import and it's generating collection correctly now.

@aranya0 We're still working on the issue that's causing the failure, we'll update here once that gets fixed as well.

**Comment by VShingala** [comment]
Hey All, we've fixed this issue! For all signed-in users, issue should be solved. And for non-signed users, It's fixed with the latest Postman App version.

I've verified the fix with mentioned WSDL definitions and they all are importing correctly now. I'll be closing this issue for now, feel free to re-open it or add a comment with the issue in case of any further issues with same error.
