### ISSUE TITLE
A "type" property within array fails data type schema validation

### ISSUE THREAD

**Issue by hiqqs** [a85/POSTMan-Chrome-Extension#10726]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues

### Describe the Issue

when trying to use the tiny validator schema type check in a postman test, if the array contains a property of "type" it fails the validation type check.  Is there a way to escape it or something so the validator knows you are using a property of type and not try to parse it or something that looks like it is happening and failing?

### Steps To Reproduce

Simply put this in the Test portion of a postman request... If you uncomment out the first "type" property within the schema.items object you will see it fails the schema validate test against data1.

```
var schema = {
 "items": {
    "type": "object",
    "required": [],
    "properties": {
        "id" : {"type": "string"},
        "name": {"type": "string"},
        "type": {"type": "string"},
        "array": {"type": "array",
            "id": {"type": "string"},
            // "type": {"type": "string"},
            "bug": {"type": "string"},
        }
      }
    }
};

var data1 = [{
        "id": "ID",
        "name": "Test Name",
        "type": "Test Name",
        "array": [
            {
                "id": "GUID",
                "type": "STRING FAKE DATA",
                "bug": "STRING FAKE DATA",
            }
        ]
    }];

pm.test('Schema is valid', function () {
    pm.expect(tv4.validate(data1, schema)).to.be.true;
});
```

### Environment Information

```markdown
- Operating System: macOs Big Sur
- Platform Type: Native App
- Postman Version: `Version 9.14.9
UI Version: 9.14.9-ui-220302-1610
Desktop Platform Version: 9.14.0 (9.14.0)`
```

**Comment by umeshp7** [comment]
@johnhiggs There are two "type" at the same level. You need to put the properties of that array element into an "item" as well.  Something like this:

```
var schema = {
 "items": {
    "type": "object",
    "required": [],
    "properties": {
        "id" : {"type": "string"},
        "name": {"type": "string"},
        "type": {"type": "string"},
        "array": {
            "type": "array",
            "items": {
              "type": "object",
              "required": ["type"],
              "properties": {
                "id": {"type": "string"},
                "type": {"type": "string"},
                "bug": {"type": "string"},
              }
            }
        }
      }
    }
};
```
Can you try this and let us know if it works?

**Comment by shubhbhargav** [comment]
@johnhiggs Let us know if the above solution doesn't work for you. Closing the ticket for now.
