### ISSUE TITLE
Please increase Collection sidebar

### ISSUE THREAD

**Issue by vbeaudoin19** [a85/POSTMan-Chrome-Extension#10725]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request

### Is your feature request related to a problem?

With folder + subfolder (for 2-3 levels) than having the test, we have to shrink the texte, but we are still missing good part for text description for the test.

Currently, with the maximum width established, we are very limited to text that can be entered and not easy to see everything. 
We are obliged to open the test in a tab or to wait a few seconds with our cursor on the test to see its full text.

### Describe the solution you'd like

Being able to expand the bar containing the collections even further would be most appreciated and beneficial to improving the efficiency of our work. 

 Having it increased to 1.5- 2x is current max witdh should be good.

Here some exemples:
- /SMS/conversations/validateCustomerToSendSMS (full texte - only the service)
- /SMS/conversations/validateCustomerToSend... (the view without the text test description)
- .../validateCustomerToSendSMS - Wrong customerKey (How we need to shrink it with text test description)
- .../validateCustomerToSendSMS - Wrong cu.. (the final view with the shrink text)

Thanks

### Additional context

Here's a similar request about increasing the sidebar
https://github.com/postmanlabs/postman-app-support/issues/3975

**Comment by vkaegis** [comment]
@vbeaudoin19 Thanks for reporting! This should be fixed as of v10.8.8. Let me know if you run into any more issues with the resizing of the sidebar.
