### ISSUE TITLE
Running Newman: command line works, Javascript throws an error

### ISSUE THREAD

**Issue by hflocken** [a85/POSTMan-Chrome-Extension#10723]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues

### Describe the Issue

Hi,

I have a collection that I can run successfully using the following command:
`newman run --verbose --insecure --ssl-client-cert /Volumes/Certs/cert.pem --ssl-client-key  /Volumes/Certs/key.pem Tester.postman_collection.json -e Default.postman_environment.json –reporters cli`

As I would like to capture the response body of the request, I'm trying to run Newman with the following script:
```
const newman = require('newman');
const fs = require('fs');

newman.run({
    collection: './Tester.postman_collection.json',
    reporters: 'cli',
    insecure: true,
    sslclientcert: '/Volumes/Certs/cert.pem',
    sslclientkey:  '/Volumes/Certs/key.pem',
    environment:   './Default.postman_environment.json'
}).on('beforeRequest', function (error, args) {
    if (error) {
        console.error(error);
    } else {
        // Log the request body
        console.log(args.request.body.raw);
    }
}).on('request', function (error, args) {
    if (error) {
        console.error(error);
    }
    else {
        // Log the response body
        console.log(args.response.stream.toString());
    }
});
```

However, in this case I get an error about an assertion that fails. 

If would appreciate if somebody could give me a hint what the difference is between the two invocations and why the second one is failing.

### Steps To Reproduce

Run the two invocations that are described above.

### Environment Information

```markdown
- Operating System: Mac
- Platform Type: Newman 5.3.0, Node v17.1.0
- Postman Version: n/a
```

**Comment by DannyDainton** [comment]
Hey @hflocken

This is the repo for the Postman app/desktop platforms. 

Could you please raise this in the Newman repository. 

https://github.com/postmanlabs/newman

---

Something to check on would be the names you're using in the script, as per the documentation it would be these. 

```
sslClientCert
sslClientKey
```

**Comment by hflocken** [comment]
@DannyDainton thanks for the hint - that already fixed my problem
