### ISSUE TITLE
can not use anything about workspace in postman

### ISSUE THREAD

**Issue by 643104191** [a85/POSTMan-Chrome-Extension#10729]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues

#### This state has been going on for several days, since about a few days ago (March 3, UTC+8)
in broswer(with postman agent):
![image|258x177](https://aws1.discourse-cdn.com/business6/uploads/getpostman/original/2X/6/6846f47332c9fd8e9a6528ebc958b038f390a2b6.png)
in desktop(win 10):
![image|264x243](https://aws1.discourse-cdn.com/business6/uploads/getpostman/original/2X/6/6a2914b4178afc7963a416f0e30393aed4b44e90.png)

### Steps To Reproduce

I tried clicking "connect now" and "Retry connection", nothing happens

### Environment Information

```markdown
- Operating System: win 10
- Platform Type: Postman Web & Postman Desktop
- Postman Version: 9.14.10
```

**Comment by montaofficial** [comment]
Mee too!

**Comment by rizkykunuq** [comment]
Me too, just loading when add new request

**Comment by marcobonati** [comment]
Me too, the network works perfectly, the desktop tool seems correctly synchronized but my workspace appears completely empty.

Version 9.14.10
UI Version: 9.14.10-ui-220304-0545
Desktop Platform Version: 9.14.0 (9.14.0)
OS: Mac OS 11.6.4

<img width="267" alt="Screen Shot 2022-03-07 at 09 25 27" src="https://user-images.githubusercontent.com/23502993/156994830-9ce4eb22-940b-4a5b-a883-4c1377d8a23f.png">

<img width="334" alt="Screen Shot 2022-03-07 at 09 25 35" src="https://user-images.githubusercontent.com/23502993/156994866-a03f39a3-f4da-4453-8062-3c9502e2202d.png">

**Comment by 0xf1a** [comment]
Really guys, great job making sure the app can't run without an internet connection. Modern programming is so cool.

**Comment by abhijitkane** [comment]
We're facing a few issues on our internal services. Our teams are working to get systems back up. I'll keep this thread updated as we have more.
Status: https://status.postman.com/

**Comment by bdelan** [comment]
Same...
![Screenshot 2022-03-07 093034](https://user-images.githubusercontent.com/46685785/156995415-9697a789-9362-4911-8c3b-e16df665c249.jpeg)

**Comment by dnkcz** [comment]
same here. Quite a bug when you have no chance to use Postman when offline. Its more anoying when my internet works, but postman have trouble connecting to your services and load data.

**Comment by rhkdwh91** [comment]
me too

**Comment by 643104191** [comment]
This state has been going on for several days, since about a few days ago (March 3, UTC-8)

**Comment by akshay-kulkarni-03** [comment]
Hi All,

We are facing degraded performance and the status for the same can be tracked from here: https://status.postman.com/

**Comment by JhangShengLuo** [comment]
I've got this issue too, seems like if you use postman account everything couldn't loaded.

**Comment by abhijitkane** [comment]
A fix has been put in place, and systems are currently operational. You should be able to see your workspaces' data by reloading the page or restarting Postman.

**Comment by ranistar** [comment]
One more question, is it possible to load saved requests from local without network?

**Comment by 643104191** [comment]
@abhijitkane 
> A fix has been put in place, and systems are currently operational. You should be able to see your workspaces' data by reloading the page or restarting Postman.

is still not work, can anyone give me some help???

**Comment by Raj-postman** [comment]
> is still not work, can anyone give me some help???

@[643104191](https://github.com/643104191) Sure, could you please submit a ticket to us via this link: https://postman.com/support to help us look into this - if there are any issues related to your account.

**Comment by Raj-postman** [comment]
> One more question, is it possible to load saved requests from local without network?

[ranistar](https://github.com/ranistar) If you are mentioning about loading requests from respective workspaces offline, then unfortunately that wouldn't be possible. Postman requires an active internet connection to load data stored in workspaces but you may switch to `ScratchPad` that lets you work offline.

<img width="240" alt="image" src="https://user-images.githubusercontent.com/47771757/157010916-62254d7b-5d7e-47b0-8d26-dfc2d435604c.png">

**Comment by DannyDainton** [comment]
Closing this out as the issue as the service is back up and running.
