### ISSUE TITLE
Json link value in /collections response 

### ISSUE THREAD

**Issue by tomwoodcock1981** [a85/POSTMan-Chrome-Extension#10727]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request

### Is your feature request related to a problem?

We are developing a solution to aid non- technical team members to run our collections via Newman.

It's also a time saving issue to avoid copy and pasting paths to .json files that need to be stored locally.

### Describe the solution you'd like

Could the API be updated so upon calling the /collections endpoint the collection object includes the current value assigned to the JSON link?

This would be really useful. Thanks.

### Describe alternatives you've considered

We are aware of the runner within Postman itself but our CI has a stage to run our collections via Newman and we need to replicate this earlier in the dev cycle.

**Comment by DannyDainton** [comment]
Hey @tomwoodcock1981 

Just trying to gather some information.

It appears you can currently call the Postman API and get the Collection details from the `/collections/{{collection_uuid}}` - Is that correct?

Are you aware that you can use the same URL with Newman? The same as you would for the exported Collection file and the static JSON Link but with the Postman API URL, it's the most up to date version of the Collection. Once that's in place on your CI system, you wouldn't need to change or update anything. 

```
newman run https://api.getpostman.com/collections/{{collection_uuid}}?apikey={{postman_api_key}}
```

**Comment by tomwoodcock1981** [comment]
Hello @DannyDainton 

Thank you for the prompt reply I really appreciate it. 

We're aware of the collection uid and passing that into the `/collections/{{collection_uid}}` call. I wasn't aware of the newman call hitting this endpoint as you've specified above.

But, this doesn't quite address what we're looking to do. Our workspaces/collections are constantly being updated and we were trying to find a way to eliminate the need for 'exporting' collections, as well as creating/utilising X-Api-Key in command line runs and automating the creation of these calls to aid all team members.

This above would require someone to hit `/collections` to obtain the uid to then GET a single collection. We were hoping to GET `/collections` then iterate over these to get the JSON Link so people could do an easy search on the collection(s) name they wish to run. But, the JSON link value isn't provided at present.

At the moment we can use `token.SelectToken("name").Value<string>())` to spit out what's being ran from the collection object:

`{{
  "collections": [
    {
      "id": "030be5fd-5c1d-4f40-ac86-5f441237ce5a",
      "name": "12-Suppliers",
      "owner": "1271260",
      "createdAt": "2020-09-02T01:52:50Z",
      "updatedAt": "2020-09-02T02:31:33Z",
      "uid": "1271260-030be5fd-5c1d-4f40-ac86-5f441237ce5a",
      "isPublic": false
    },`

Could the current JSON Link be made available in this object? I appreciate it's a static snapshot of the collection from what I've read.

Thanks again for your time and feedback Danny.

**Comment by DannyDainton** [comment]
Hey @tomwoodcock1981 

Each of the entities in the platform will have an `info` section in the right context menu, that displays the uuid. 

<img width="1306" alt="image" src="https://user-images.githubusercontent.com/17089546/157221912-1264d386-584f-445e-9aa3-b63cfe95789e.png">

There shouldn't really be a need to hit the `/collections` endpoint to find that single id. The JSON link is kind of the same as the JSON file that you would export, it just happens to be in a URL hosted by us. Both methods are static, as you mentioned, and would need a physical UI action to update it (either exporting another file or hitting the update button), if you made a change in the Collection. 

The Postman API always returns the most up to date sync'd version of that collection and the uuid wouldn't change so you can use that in a CI tool to run the collections, you can then make changes to the Collection in the Postman app and Newman would run those newly saved changes. 

If the JSON link was provided in that object it would still be a static Collection and you would still need to manually update the link every time you made a change. That's the beauty of using the Postman API to get the current up to date details. Also, the JSON link is a public URL, anyone with that can see your collection and all the details within it but the Postman API is behind a level of Authentication.

**Comment by tomwoodcock1981** [comment]
The link being public and the protection provided by the API is key and I wasn't aware the uid was visible in the info! Trying to keep up with your contextual menus....I'll find Jimmy Hoffa in here one day ;)

Thanks again for your help mate as to the path of least resistance with all this.

**Comment by tomwoodcock1981** [comment]
One final question @DannyDainton - can the environment uid be passed into `/environments/{{uid}}` in the same as the collection in the newman command line??

**Comment by DannyDainton** [comment]
Yep, that can be passed too.

```
newman run https://api.getpostman.com/collections/{{collection_uuid}}?apikey={{apiKey}} -e https://api.getpostman.com/environments/{{environment_uuid}}?apikey={{apiKey}}
```

More information about Newman can be found here - https://github.com/postmanlabs/newman

**Comment by tomwoodcock1981** [comment]
Top man @DannyDainton thanks for your help!
