### ISSUE TITLE
Monitors: Request run manually results in 500 response but same request in monitor produces 200 response

### ISSUE THREAD

**Issue by shai-zmora-sp** [a85/POSTMan-Chrome-Extension#10724]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues

### Describe the Issue

The same request is run: 
1. manually (or as part of a collection)
2. as part of a Monitor manual run.

Issue:
The request consistently fails (returns a 500 response code) when run manually and the service has been confirmed as down. 
When the same exact request is run as part of a Monitor (running that entire collection including the previously run request), the request returns a 200 which a FALSE positive which undermines the purpose of the monitor.

### Steps To Reproduce

1. Create a collection with Request-A. 
2. Run the collection from Postman "Collections" tab.
3. Result: Request-A returns a 500 response code
4. Create a monitor for that collection(containing Request-A)
5. run the collection manually: 
6. ISSUE: Monitor passes health check with NO ISSUE and returns a 200 response code for Request-A

### Environment Information

```markdown
- Operating System: Windows 10
- Platform Type: Native APP
- Postman Version: 9.14.10
```

**Comment by DannyDainton** [comment]
Hey @shai-zmora-sp 

Is this still an issue that you're facing - The details that you have given are very contextual to you, it would be difficult for us to recreate that using a different Collection and Requests. 

Are you able to provide more details, screenshots or a short video so that we can see what's happening from your side, please?

**Comment by DannyDainton** [comment]
Hey @shai-zmora-sp  👋🏻

I'm going to close this issue due to inactivity - If you're still facing the issue in the latest version we can reopen this and investigate further.

**Comment by shai-zmora-sp** [comment]
Hi @DannyDainton 
I'm sorry I missed the response for this. 
I reproduced the issue multiple times on the same day it occurred. However, I have not been able to reproduce to date. 
Thank You !
Shai
