### ISSUE TITLE
Duplication of a nested folder does not copy ALL of its contents.  

### ISSUE THREAD

**Issue by RealExtraTomato** [a85/POSTMan-Chrome-Extension#10722]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues

### Describe the Issue

Duplication of nested folders more than 3 deep is recreated. But upon viewing the contents of said folders the contents of each call GET, POST, PATCH etc is empty.

Duplication of nested folders 2 deep is fine.

### Steps To Reproduce

Structure of my collection 

Folder 1
>> Folder 2
>>>>Folder 3
>>>>>>API Calls 

If I duplicate folder 3 the structure is recreated but upon viewing the individual API calls there is no Params, Body, Tests etc. Only a few Headers exist.

If I move Folder 3 out from under Folder 2 and under Folder 1 like the below
Folder 1
>> Folder 2
>> Folder 3
>>>>API Calls 

Duplication works without issue.

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/100955785/156801685-ce54c172-ca9e-4727-bb4e-e81bfb8adc8d.png)

![image](https://user-images.githubusercontent.com/100955785/156801928-469fbc7a-c900-4fb9-b360-484c029aae9a.png)

### Environment Information

```markdown
- Operating System: win32 10.0.19044
- Platform Type: 9.14.0
- Postman Version: 9.14.9
```

**Comment by giridharvc7** [comment]
Thanks for reporting this @RealExtraTomato , we are looking into this. 
Meanwhile can you share some logs from dev console if possible?

**Comment by jan-marten** [comment]
Hi there, I am stumbling into a similar problem here and am in contact with e-mail support.

Steps from my side to reproduce it;

* Create a new folder
* Duplicate an existing request which contains a URL, params, auth, headers...
* Move that duplicated request to the new folder
* Rename it to something logical, save it and close the tab to ensure it is saved properly
* Now duplicate that request too
* New request is empty

However, after restarting Postman it is there.

Reproducable on Postman version 9.14.13 and v9.12.2-canary.

**Comment by quaqua** [comment]
I'm reorganising our collections and constantly experiencing similar behaviour:

1. create a new folder in a collection
2. Move or Duplicate->Move a request into that folder
3. Open that request -> EMPTY
    - url gone
    - body params gone
    - tests gone

You cannot reproduce always. It happens arbitrary (most times, when duplicating, but now also when moving a request) but at least 50% of duplicating/moving requests into folders.

Postman for Mac Version:
Version 9.14.7
UI Version: 9.14.7-ui-220228-1230

EDIT:
It seems, this is a bug related to the desktop version. When taking a look into the web-browser version of postman, all the empty requests are actually there (moved/duplicated) properly (including all expected values/url/tests)

can the other reporters @jan-marten and @RealExtraTomato confirm that?

**Comment by giridharvc7** [comment]
@quaqua @jan-marten @RealExtraTomato We are looking into this, this will be fixed soon.

**Comment by giridharvc7** [comment]
To unblock yourself, please restart the app 😅 This should help before we send out a fix for this.

**Comment by giridharvc7** [comment]
We've raised a fix, this should available in v9.15.1. Please check and let us know if it works for you

**Comment by DannyDainton** [comment]
Hey @quaqua / @jan-marten / @RealExtraTomato 

Has this now solved the issue you were facing? If so, can we close this out?

**Comment by jan-marten** [comment]
@DannyDainton - After installing the updated v9.15.1 I could not reproduce it anymore. Thanks.

**Comment by DannyDainton** [comment]
Thanks for the response @jan-marten 🏆

I'm going to close this issue now, we can reopen it again if people are still facing issues in the latest version.
