### ISSUE TITLE
Monitor values of an API

### ISSUE THREAD

**Issue by kankernl** [a85/POSTMan-Chrome-Extension#10731]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request

### Is your feature request related to a problem?

I want to get a notification if some values changes

### Describe the solution you'd like

I wonder if it possible to configure a monitor that does specific calls and checks if there are changes since last call. I am not talking about whether he api is available, I want to check the output of the API-call.

For example the output is as below, and that the monitor checks if any of the values has changed

{
"year": 2021,
"yearSurvival": 2019,
... 

}

### Describe alternatives you've considered

It is in some way similar to a Prometheus/Grafana combo.

**Comment by abhijitkane** [comment]
@kankernl Yep - you can use global or environment variables. https://community.postman.com/t/passing-environment-variable-between-monitor-runs/3194 explains how you can do this. Essentially, use the environment as a data store between successive runs of your monitor, where you can check if the new value differs from the one in your environment.

Our community (https://community.postman.com/) can help with any questions around implementation.
