### ISSUE TITLE
Basic auth false value displayed

### ISSUE THREAD

**Issue by zfatih** [a85/POSTMan-Chrome-Extension#10734]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues

### Describe the Issue

When using collection variables for Basic auth fields(ex. username: {{CLIENT_ID}}, password: {{SECRET}}), the value displayed in auth header is base64 encoded "{{CLIENT_ID}}:{{SECRET}}" and not the values themselves. This can be confusing as this is not the value being sent to a server.

### Steps To Reproduce

1. Open a new request
2. Make 2 collection variables: CLIEND_ID and SECRET with values "admin" and "pass"
3. Chose Basic Auth for Authorization and put defined variables as Username and Password
4. Value for Authorization request header is not parsed from values, but from names(instead of "YWRtaW46cGFzcw==", "e3tDTElFTlRfSUR9fTp7e1NFQ1JFVH19" is shown)

### Environment Information

```markdown
- Operating System: Windows 10
- Platform Type: Native App
- Postman Version: v9.14.10
```

**Comment by coditva** [comment]
@zfatih Thanks for reporting. I've marked this as bug. We'll post any updates on this ticket.

**Comment by pixeldoc2000** [comment]
~~Basic Auth is also not working with Environment Variables with/without Type secret.~~

~~Looks like this is still not fixed 😢~~

It did work after restarting PostMan, WTF?

**Comment by vedkribhu** [comment]
This looks like an issue where you might not have saved the collection variables before sending the request.
