### ISSUE TITLE
Request body payload is not loaded in Native app when pasting cURL in My Workspace/Import/Row text

### ISSUE THREAD

**Issue by gomotest-covCheckerRuKeyQ9W8E7R6T5Y** [a85/POSTMan-Chrome-Extension#10733]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues

### Describe the Issue

Request body payload is not loaded in the desktop app when pasting cURL in My Workspace/Import/Row text.
I tried to compose a request in the postman desk app copying a request from Chrome Dev Tool.
It works in the web version but doesn't work in the desk version.

### Steps To Reproduce

1. Paste the cURL request to My Workspace/Import/Row text in the desk app

![2022-03-07_20-02-57](https://user-images.githubusercontent.com/51805531/157049164-543f94db-7cfd-47ae-8c1b-eb4c54d025f7.png)

2. Click on the Continue button

![2022-03-07_20-04-29](https://user-images.githubusercontent.com/51805531/157049273-3deaae95-0f12-45e9-a9a3-855f918b80a8.png)

3. Observe that body payload is empty

![Desktop app  Incorrect request loading_](https://user-images.githubusercontent.com/51805531/157046351-117992fd-94ac-4a34-a97b-b8cfac4c75fb.png)

4. In web app request is loaded correctly:

![Web app  Corract request loading](https://user-images.githubusercontent.com/51805531/157046356-ddd91c7c-e416-4624-b149-5c1e8552c2e1.png)

### Request example

[cURL request.txt](https://github.com/postmanlabs/postman-app-support/files/8198008/cURL.request.txt)

### Environment Information

```markdown
- Operating System: Windows 10 
- Platform Type: Native App/Postman Web
- Postman Version: 9.0.9
```

### Additional Context?

I've found sort of duplicats for this issue, but it is still unresolved, so I decided to create a new one to highlight it)
Here the previous bugs reported: [#8126](https://github.com/postmanlabs/postman-app-support/issues/8126), [#7895](https://github.com/postmanlabs/postman-app-support/issues/7895)

**Comment by DannyDainton** [comment]
Hey @gomotest-covCheckerRuKeyQ9W8E7R6T5Y 

I see that you're using an older version of the Desktop app - Could you update and try again with the latest version, please?

I used your CURL snippet and I can see the payload in the request:

<img width="1477" alt="image" src="https://user-images.githubusercontent.com/17089546/157049393-2652c8aa-ac30-4f77-b59e-b4f8a4b92080.png">

**Comment by gomotest-covCheckerRuKeyQ9W8E7R6T5Y** [comment]
Thank you for the answer!
I've updated the app, restarted it (showed the new version in comment) but still, have the same problem

**Comment by DannyDainton** [comment]
The latest version of the desktop app is `9.14.10` but it looks like you have `9.0.9`, from your comment.

You can get the latest version from https://www.postman.com/downloads/

**Comment by gomotest-covCheckerRuKeyQ9W8E7R6T5Y** [comment]
The app was updated till not the latest version the first time. Now it works correctly. Thank you!
