### ISSUE TITLE
I can't access Postman's workspace

### ISSUE THREAD

**Issue by ivanaa995** [a85/POSTMan-Chrome-Extension#10730]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues

### Describe the Issue

I can't access any of 3 workspaces in Postman since this morning. I got picture with info: Request not found. We cold not find the request you are looking for. and in part for adding requests there is info: Couldn’t fetch your data
Just a faulty wire. Your data is safely synced to Postman’s servers.
After clicking on "Refresh" button, issue is still present. Does anybody knows how should I fix it?
I don't have any environments or any requests that I used on Friday

### Steps To Reproduce

/

### Screenshots or Videos

![postman](https://user-images.githubusercontent.com/90684759/156995770-abc54172-fb52-467e-8d8a-68c9a634e4a4.png)

### Environment Information

```markdown
- Operating System: Windows 10
- Platform Type: Postman Web
- Postman Version:  9.14.10
```

**Comment by lrseryou** [comment]
I have the same problem

**Comment by maximejosien** [comment]
I have the same problem with the postman app

**Comment by Nicqiang** [comment]
I have the same problem

**Comment by GroundLand** [comment]
I have the same problem

**Comment by abhijitkane** [comment]
We're facing a few issues on our internal services. Our teams are working to get systems back up. I'll keep this thread updated as we have more. Status: https://status.postman.com/

**Comment by hxy112292** [comment]
Oh my God. I have the same problem. Help!!!!

**Comment by mkdreams** [comment]
me too....

**Comment by kaniou** [comment]
me too.. ✋🏼

**Comment by JhangShengLuo** [comment]
same problem here, desktop app or web app, show me the same error.

**Comment by abhijitkane** [comment]
A fix has been put in place, and systems are currently operational. You should be able to see your workspaces' data by reloading the page or restarting Postman.

**Comment by Tuki277** [comment]
everything is working again :D 
![image](https://user-images.githubusercontent.com/58626944/157003479-3fb9d0d0-6a45-453d-bcce-1c20fe92e532.png)

**Comment by ivanaa995** [comment]
yes, now is working fine, thank you!

**Comment by DannyDainton** [comment]
Closing this issue as the service is back up and running.
