### ISSUE TITLE
Why can I load Collections data offline, but not get request details?

### ISSUE THREAD

**Issue by 643104191** [a85/POSTMan-Chrome-Extension#10739]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues

### Describe the Issue

postman web
![image](https://user-images.githubusercontent.com/27074730/157207175-27947bfd-88b0-4427-9ea1-6cbb736954b0.png)
postman desktop
![image](https://user-images.githubusercontent.com/27074730/157210050-8bc21727-99dc-48f2-8bbc-1ccb9d8c3f81.png)

### Steps To Reproduce

I have checked the problem by following the instructions below, but still can't solve my problem
[https://support.postman.com/hc/en-us/articles/4412971069847-Unable-to-load-data-as-you-re-offline](https://support.postman.com/hc/en-us/articles/4412971069847-Unable-to-load-data-as-you-re-offline)

### Environment Information

```markdown
- Operating System: win 10
- Platform Type: Desktop App & Postman Web
- Postman Version: 9.14.11
```

**Comment by kamalaknn** [comment]
Hey @643104191 

It looks like your app might be having trouble creating a WebSocket connection to Postman servers.

Is this a persistent issue or does your app load the requests after delay?

Could you share the logs from `View -> Developer -> Show logs in Explorer` with us? You can zip all the contents of the logs directory and forward them to `help@postman.com`. We can take a closer look at why your app is having trouble connecting.

**Comment by Raj-postman** [comment]
Resolved this issue via Support ticket 🤝
