### ISSUE TITLE
Can't login from desktop app - Using google account.

### ISSUE THREAD

**Issue by wcatalansuazo** [a85/POSTMan-Chrome-Extension#10732]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues

### Describe the Issue

Sign in -> sign with google account(in browser ) -> error.
```
500
Something went wrong. Our engineers are working on fixing this as soon as possible.

Request Trace: 848120535f60faa055301d6045eecadd

[Back to login](https://identity.getpostman.com/accounts)
```

### Steps To Reproduce

1. In the postman app click Sign in
2. IN browser select login with google account
3. error is displayed.

### Environment Information

```markdown
version 9.14.10
UI Version: 9.14.10-ui-220304-0545
Desktop Platform Version: 9.14.0 (9.14.0)
operation system: macOs monterrey, macbook pro
```

**Comment by BruceZhang1993** [comment]
same error using google account

**Comment by chenyonghui100** [comment]
me too

**Comment by vdcardenas** [comment]
Me too :-/

**Comment by vdcardenas** [comment]
It's working fine again

![image](https://user-images.githubusercontent.com/18684822/157002696-6f85a950-4708-4166-8b43-7d8b75ed2324.png)

**Comment by Swapnil-getpostman** [comment]
We are experiencing some downtime and our Engineering team is working quickly to get everything back up and running. I will keep you posted on any updates I get from engineering. Also, our status page has been updated to track this here: https://status.postman.com/ 
 
I appreciate your patience while we get this sorted! Thank you!

**Comment by wcatalansuazo** [comment]
now it is working :D thanks !

**Comment by DannyDainton** [comment]
Closing this issue as the service is back up and running.
