### ISSUE TITLE
Feature request: Raw body editor JSON lint and pretty

### ISSUE THREAD

**Issue by uocnb** [a85/POSTMan-Chrome-Extension#1073]
It would be great if request raw body editor support pretty JSON data.

**Comment by mikesigs** [comment]
It used to work on an older version. It's even still shown in the docs. https://www.getpostman.com/docs/responses#viewing

**Comment by abhijitkane** [comment]
@mikesigs The link you posted is for the response section. The response section still supports Pretty view for JSON. 
The request raw body editor supports JSON formatting, but not automatic prettification like the response section.

**Comment by mikesigs** [comment]
Okay. I see it now. I was wondering why the new version would have removed a feature. Makes more sense now. Well I will just sit here patiently waiting for the new feature then.

BTW - Thanks for this awesome tool (and your quick response)!

**Comment by sdnts** [comment]
This should be possible now. You can prettify JSONs in the raw body by selecting the correct format using the dropdown next to the body type selector. Linting should be automatic, but you can prettify using the shortcut (Cmd + B)
