### ISSUE TITLE
Can not view application version

### ISSUE THREAD

**Issue by KES777** [a85/POSTMan-Chrome-Extension#10742]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request

### Is your feature request related to a problem?

I want to know version of my Postman

### Describe the solution you'd like

Most applications have menu item: `Help->About`

### Describe alternatives you've considered

`./Postman --version`

**Comment by DannyDainton** [comment]
Hey @KES777 

There are 2 different places in the app where you can view the version information.

You can go to `Settings (The cog icon) > About`

<img width="1686" alt="image" src="https://user-images.githubusercontent.com/17089546/159031759-75c90aac-d17e-4318-83ca-9c73a2b936c3.png">

Open the `About Postman` option from the apps menu (Windows would show this slightly differently)

<img width="433" alt="Screenshot 2022-03-18 at 15 29 01" src="https://user-images.githubusercontent.com/17089546/159032785-ee456226-3940-401e-b479-55b88cde695d.png">

**Comment by KES777** [comment]
Thank you, but these are so unusual places... 

>Most applications have menu item: `Help->About`

**Comment by ricardograca-scratch** [comment]
It seems there's no "About Postman" on the Linux version, so the only option is to use `Settings > About` which is not very common so I also had to google how to find the app version, which landed me on this page. Can this feature request be reopened?
