### ISSUE TITLE
Binding values directly in the API url does not get evaluated

### ISSUE THREAD

**Issue by danciaclara** [a85/POSTMan-Chrome-Extension#10748]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues

### Describe the Issue

If you bind widget values in the api url, it evaluates to no value.

### Steps To Reproduce

1. Add an input widget with a random value (eg: baz)
2. Create an API and in the url bind the value of the input widget like this `http://foo/bar?{{Input1.text}}`
3. We would expect the value to evaluate as http://foo/bar?baz, but it shows http://foo/bar

### Environment Information

```markdown
- Operating System: 
- Platform Type: 
- Postman Version:
```

**Comment by DannyDainton** [comment]
Hey @danciaclara

I believe you have created this in the wrong repository. I'm going to close this out now but can reopen if this is a feature request.

If so, can you provide more context about your usecase, please?

**Comment by danciaclara** [comment]
@DannyDainton I'm so sorry about this. Yes this was posted incorrectly
