### ISSUE TITLE
Method is automatically changed after 301 redirect

### ISSUE THREAD

**Issue by nulLeeKH** [a85/POSTMan-Chrome-Extension#10744]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues

### Describe the Issue

# Summary
Postman uses only GET method after 301 redirect.

# Cases
### postman
**_This screenshot has been deleted to protect sensitive information._**
### server log
**_This screenshot has been deleted to protect sensitive information._**
### curl
**_This screenshot has been deleted to protect sensitive information._**
### server log
**_This screenshot has been deleted to protect sensitive information._**
### postman
**_This screenshot has been deleted to protect sensitive information._**
### server log
**_This screenshot has been deleted to protect sensitive information._**

### Steps To Reproduce

1. Use nginx to make reverse proxy
2. Use certbot to generate certificate
3. Use certbot-managed redirect
4. Send any(except GET) request to the server with HTTP protocol

### Environment Information

```markdown
- Operating System: macOS Monterey(v.12.2)
- Platform Type: Native App
- Postman Version: 9.0.9
```

**Comment by coditva** [comment]
@nulLeeKH I think this might be because of the "Follow Original HTTP Method" setting turned off. You can enable it for the request by going to the "Settings" tab in the request.

<img width="865" alt="image" src="https://user-images.githubusercontent.com/8445768/157647135-f5021d2e-2b61-4351-a846-2bfa7c21a67c.png">

**Comment by shubhbhargav** [comment]
@nulLeeKH Did the above recommendation work?

**Comment by nulLeeKH** [comment]
I tried it. But, it doesnt work properly.

**_This screenshot has been deleted to protect sensitive information._**
**_This screenshot has been deleted to protect sensitive information._**

When I use that option, method was corrected. But, body contents did not delivered.

**Comment by shubhbhargav** [comment]
@nulLeeKH Looks like the server gave a 5XX (500 Internal Server Error) without a body. Can you check the error on your backend server?

**Comment by nulLeeKH** [comment]
Please check the server log.
The request body did not reach to server.

**Comment by shubhbhargav** [comment]
@nulLeeKH Can you share the screenshot of Console (bottom left corner) once you send a request? You can follow these steps to do the same:

1. Open Console from the bottom left corner
2. Try sending a request
3. Take the screenshot and share


This will help debug whether the 5XX is happening on the first request itself or afterwards. I checked the same on my end and could verify that the body was in-fact forwarded. Sharing the screenshot below. If you see the expanded request, it has the body being forwarded from the first unexpanded request.

<img width="1435" alt="Screenshot 2022-03-17 at 2 45 51 PM" src="https://user-images.githubusercontent.com/41579749/158776932-e327d8b1-d5a4-48a0-8e0d-0e29ef7df856.png">

**Comment by nulLeeKH** [comment]
I found the cause!

**_This screenshot has been removed to protect sensitive information._**
This is the raw log when I send request with https.

**_This screenshot has been removed to protect sensitive information._**
And this is the raw log when  I send request after 301 redirect.



Content-Length is improperly-entered after 301 redirect.
That's why my express server cannot parse it correctly.

**Comment by shubhbhargav** [comment]
@nulLeeKH Just to be on the same page, do you mean the redirected call is NOT sending the Content-Length from Postman? If yes, can you please share the console logs generated when you make this call?

**Comment by nulLeeKH** [comment]
Of course yes!

```
POST {DOMAIN}: {
  "Network": {
    "addresses": {
      "local": {
        "address": "{IP_ADDRESS}",
        "family": "IPv4",
        "port": 52351
      },
      "remote": {
        "address": "{IP_ADDRESS}",
        "family": "IPv4",
        "port": 80
      }
    }
  },
  "Request Headers": {
    "content-type": "application/json",
    "user-agent": "PostmanRuntime/7.29.0",
    "accept": "*/*",
    "cache-control": "no-cache",
    "postman-token": "4ca9efb2-c42d-4120-adda-9d7e32ff662a",
    "host": "{SERVICE_DOMAIN}",
    "accept-encoding": "gzip, deflate, br",
    "connection": "keep-alive",
    "content-length": "30"
  },
  "Response Headers": {
    "server": "nginx/1.14.0 (Ubuntu)",
    "date": "Tue, 05 Apr 2022 13:12:24 GMT",
    "content-type": "text/html",
    "content-length": "194",
    "connection": "keep-alive",
    "location": "{SERVICE_URL}"
  }
}
POST {SERVICE_URL}: {
  "Network": {
    "addresses": {
      "local": {
        "address": "{IP_ADDRESS}",
        "family": "IPv4",
        "port": 52352
      },
      "remote": {
        "address": "{IP_ADDRESS}",
        "family": "IPv4",
        "port": 443
      }
    },
    "tls": {
      "reused": false,
      "authorized": true,
      "authorizationError": null,
      "cipher": {
        "name": "ECDHE-RSA-CHACHA20-POLY1305",
        "standardName": "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256",
        "version": "TLSv1/SSLv3"
      },
      "protocol": "TLSv1.2",
      "ephemeralKeyInfo": {},
      "peerCertificate": {
        "subject": {
          "commonName": "{SERVICE_DOMAIN}",
          "alternativeNames": "DNS:{SERVICE_DOMAIN}"
        },
        "issuer": {
          "country": "US",
          "organization": "Let's Encrypt",
          "commonName": "R3"
        },
        "validFrom": "Mar  9 08:12:43 2022 GMT",
        "validTo": "Jun  7 08:12:42 2022 GMT",
        "fingerprint": "C8:B9:07:92:74:E1:D8:3D:FA:52:90:F9:EF:8B:89:80:EC:69:A8:84",
        "serialNumber": "04940534ac56f14cf37aae016ec8197d5a6e"
      }
    }
  },
  "Request Headers": {
    "content-type": "application/json",
    "user-agent": "PostmanRuntime/7.29.0",
    "accept": "*/*",
    "cache-control": "no-cache",
    "postman-token": "4ca9efb2-c42d-4120-adda-9d7e32ff662a",
    "accept-encoding": "gzip, deflate, br",
    "connection": "keep-alive",
    "content-length": "30",
    "referer": "http://{SERVICE_DOMAIN}/pu/reg",
    "host": "{SERVICE_DOMAIN}"
  },
  "Request Body": "{\n    \"phone\": \"{PHONE_NUMBER}\"\n}",
  "Response Headers": {
    "server": "nginx/1.14.0 (Ubuntu)",
    "date": "Tue, 05 Apr 2022 13:12:24 GMT",
    "content-type": "application/json; charset=utf-8",
    "content-length": "11",
    "connection": "keep-alive",
    "x-powered-by": "Express",
    "access-control-allow-origin": "*",
    "etag": "W/\"b-0T4nBHYn9L6TGSjAViOpBlidSJA\""
  },
  "Response Body": "{\"code\":-1}"
}
```

**_This log has been masked to protect sensitive information._**

**Comment by codenirvana** [comment]
@nulLeeKH Can you please update the Postman app to the latest version (v9.15) and check if that fixes your issue?

We’ve fixed the _"Follow original HTTP Method"_ behavior [recently](https://github.com/postmanlabs/postman-app-support/issues/10440#issuecomment-1014555537) to preserve the request body for non-307/8 redirects.

**Comment by nulLeeKH** [comment]
This problem has been resolved!
I'm so appreciative of your kindness!
