### ISSUE TITLE
Flows fails parsing response

### ISSUE THREAD

**Issue by yongsrepos** [a85/POSTMan-Chrome-Extension#10747]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues

### Describe the Issue

Hi,
The issue has been well discussed and confirmed by a Postman team member. Please refer to this discussion: https://github.com/postmanlabs/postman-flows/discussions/255#discussioncomment-2309579

The purpose of this ticket is to follow up on above discussion.
Thanks!

BR,
Yong

### Steps To Reproduce

Covered in this discussion: https://github.com/postmanlabs/postman-flows/discussions/255#discussioncomment-2309579

### Environment Information

```markdown
- Operating System: macOS Big Sur
- Platform Type: Desktop
- Postman Version: 9.14.11
```

**Comment by DannyDainton** [comment]
Hey @yongsrepos 

Thanks for raising the issue. We'll update this thread once we have more information to share. 🙏🏻

**Comment by yongsrepos** [comment]
Thanks, @DannyDainton ! The fix will definitely bring great value to our use case. Look forward to it.
