### ISSUE TITLE
[9.14.10] [Mac] There was an error importing this collection. Please try again.

### ISSUE THREAD

**Issue by handsome-nium** [a85/POSTMan-Chrome-Extension#10741]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues

### Describe the Issue

Getting "There was an error importing this collection. Please try again". using version 9.14.10 on Mac. 
The issues is when going through "Run in postman" button from the documentation exposed web: https://api.crypto.nium.com/ 
Using the backed up collection JSON works.

### Steps To Reproduce

Click Run in Postman here - https://api.crypto.nium.com/

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/94123015/157434145-b64c0692-64bb-45dd-8093-e594e6902d4f.png)

### Environment Information

```markdown
- Operating System: macOS Monterrey 12.0.1
- Platform Type: Desktop
- Postman Version: 9.14.10
```

**Comment by bhargavkaranam** [comment]
Hey @handsome-nium,

You should be able to import this collection via Run in Postman now.

**Comment by shubhbhargav** [comment]
Hey @handsome-nium, please feel free to let us know if you are still facing this issue. Closing it for the time being.
