### ISSUE TITLE
Postman miscalculates transfer start?

### ISSUE THREAD

**Issue by swedkg** [a85/POSTMan-Chrome-Extension#10746]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues

### Describe the Issue

I'm using cUrl to repeat the same request 10 times, time_starttransfer is around 12 seconds.
Postman reports it to be 57 seconds

cUrl is using --silent --output /dev/null flags

![image](https://user-images.githubusercontent.com/9026763/157614498-4e578a06-e544-4dac-a159-09b8b69d78e0.png)
![image](https://user-images.githubusercontent.com/9026763/157615239-40e89f09-5162-418e-8e5c-392ec4f73db8.png)

### Steps To Reproduce

1. Make a request with a big enough response
2. Compare with cUrl

### Environment Information

```markdown
- Operating System: Windows Server 2012 R2/ Windows 10
- Platform Type: Native App
- Postman Version: 9.14.0/8.12.5
```

**Comment by sandeep-singh-pstmn** [comment]
@swedkg I have created the mock server(https://ff92e197-f259-447d-a7bc-fd1a910aeba7.mock.pstmn.io/data) with a delay of 30 sec. That means the 1st byte will return after 30 sec so the **time_starttransfer** or **start transfer** should be around 30 sec

> **time_starttransfer** is just before cURL reads the first byte from the network (it hasn't actually read it yet). time_starttransfer - time_appconnect is practically the same as Time To First Byte (TTFB) from this client.
> 
> [Timing web requests with cURL and Chrome](https://blog.cloudflare.com/a-question-of-timing/) 

used the above mock server in both places in Postman and in terminal
for both the case, I got the start transfer time of around 30

<img width="410" alt="Screenshot 2023-06-16 at 7 27 52 AM" src="https://github.com/postmanlabs/postman-app-support/assets/85243040/7567e2bc-6ce7-4a1d-abd2-e904b73d853c">
<img width="902" alt="Screenshot 2023-06-16 at 7 28 22 AM" src="https://github.com/postmanlabs/postman-app-support/assets/85243040/0143f7f1-6834-4210-9d79-a4d1326c3589">

https://github.com/postmanlabs/postman-app-support/assets/85243040/89fea267-5351-41b9-87f6-a4cfaef0104a


Note : curl used  in the terminal to print **time_starttransfer**
**`curl -w "%{time_starttransfer}\n" -o /dev/null -s 'https://ff92e197-f259-447d-a7bc-fd1a910aeba7.mock.pstmn.io/data'`**

@swedkg can you give some more context about the API which you are using

**Comment by sandeep-singh-pstmn** [comment]
@swedkg closing this issue for the time being. If the issue arises again, feel free to reopen it.
