### ISSUE TITLE
using token as variable in postman

### ISSUE THREAD

**Issue by Abhinay12** [a85/POSTMan-Chrome-Extension#1074]
i just wanted to use access_token as a variable........................... give me some solution.

**Comment by abhijitkane** [comment]
Our documentation is located at https://www.getpostman.com/docs/. Is there any specific use-case that you're facing a problem with?

**Comment by Abhinay12** [comment]
![capture15](https://cloud.githubusercontent.com/assets/11586616/7794902/06522614-02ed-11e5-8959-708a27dd0dcb.PNG)

i want this access_token as variable how can i do this..................................

**Comment by abhijitkane** [comment]
You can try setting an environment variable as explained in the documentation. It'll then be available to use as {{access_token}}, or whatever you name your variable.

**Comment by Abhinay12** [comment]
i have try this but it is not working can u send me one screen shot for
this issue

**Comment by dhoyt** [comment]
Hope this helps and is what you are looking for ...

![image](https://cloud.githubusercontent.com/assets/10944880/7938676/d3bbfa30-0914-11e5-8a2d-dc8e0000a1c2.png)

![image](https://cloud.githubusercontent.com/assets/10944880/7938821/77e2e34e-0915-11e5-951e-a5e0c62d1770.png)

This is setting an environment variable in an "environment" file and will be available to all your endpoints, in all your collections, that use/run the particular "environment".

**Comment by dhoyt** [comment]
This is setting the same environment variable but it will only be set when that particular endpoint is run. Because it is set in the Pre-request script, it will be set before the endpoint is executed.

![image](https://cloud.githubusercontent.com/assets/10944880/7939027/c8f86e06-0916-11e5-9c61-b1228255d10e.png)

**Comment by Abhinay12** [comment]
in 1 st fig i have just created one schema for my response body and in
postamn i want to comapre the schema with my response Body i am not able to
solve this issue can u solve my issue and send me one screenshot for this

**Comment by dhoyt** [comment]
Can you show what you have done and we can go from there ?

**Comment by Abhinay12** [comment]
i have send request from postman and get the response body

this is my response Body
{
- "studentId": "1",
- "studentName": "Rohith",
- "fromDate": "01-4-2015",
- "toDate": "30-4-2015",
- "absent_dates": [ ],
- "total_absent_days": "0",
- "total_working_days": "22",
- "present_days": "22"

}
which i get after sending the request
now i have generated schema for it from here http://jsonschema.net/#/

now i want to compare this schema with my response body
i am using tiny validator for json Data
is it correct ..............
or just tell me how to compare this and what is the use of this tiny
validator for json data i have search it but i can't get the
solution..............

**Comment by dhoyt** [comment]
In the Pre-request script window ...

``` javascript
var yourSchema = 
{
YOUR SCHEMA STUFF GOES HERE
}

postman.setEnvironmentVariable("yourSchema", JSON.stringify(yourSchema));
```

In the Tests window ...

``` javascript
var jsonresponseData = JSON.parse(responseBody);

var validJSON = tv4.validate(jsonresponseData, JSON.parse(environment.yourSchema));

if(!validJSON) {
    tests["TEST FAILED - your JSON Schema"] = validJSON;    
    tests["TEST FAILED - tv4 error Code = "+tv4.error.code] = validJSON;
    tests["TEST FAILED - tv4 dataPath = "+tv4.error.dataPath] = validJSON;
    tests["TEST FAILED - tv4 message = "+tv4.error.message] = validJSON;
    tests["TEST FAILED - tv4 schemaPath = "+tv4.error.schemaPath] = validJSON;
}
else {
    tests["TEST PASSED - your JSON Schema"] = validJSON;    
}

console.log(tv4.error);
```

**Comment by Abhinay12** [comment]
thanku sir
i have one more issue
The JSON file needs to be an array of key/value pairs. The keys are used as
variable names while the values are replaced inside requests.
sir i want to compare my response body with variables is it possible to do
so

**Comment by Abhinay12** [comment]
i am currently testing Api in postman  i have one api
/app/getHomework/student/$studentId/$dateAssigned
and these two variables $studentId and $dateAssigned  this will take values
like

/app/getHomework/student/1/04-06-2015
/app/getHomework/student/2/06-06-2015
at one time we r sending only for student having id 1
at a time it is possible that lots of user can hit this api so i want to
make it dynamically so that every user while hitting this url will get
corresponding data
