### ISSUE TITLE
Sync Conflicts - should use time collections are edited to determine the latest?

### ISSUE THREAD

**Issue by intellix** [a85/POSTMan-Chrome-Extension#1075]
So this weekend I've been on my laptop and working on a Collection, creating lots of tests etc. It was fully Synced.
I come to work and login to my account to benefit from Sync. I'm greeted by a dialog explaining that I have a lot of conflicts and need to resolve them (the changes I made). Rather than pick them I:
- Disabled Sync
- Deleted everything
- Enabled Sync

Boom! Sync has now regarded everything being deleted as up-to-date.

Rather than getting a dialog asking to resolve conflicts and essentially merge things, shouldn't it just have  replaced everything I had locally with what was on the server? Especially since what was on the server was much more recent. 

When I get home I'll disable internet on my laptop and export everything so I don't lose everything. I assume Sync will delete everything and then I can just re-import.

**Comment by julian-pani** [comment]
Seeing the same thing even on the same computer: after making changes and seeing "In Sync", when closing and reopening the Postman app it is saying there is a conflict to resolve.

Might be a different issue but worth mentioning: I have experienced a few times that my app is showing "In Sync" but when I close it and then reopen it, all my latest changes are lost, and overwritten by a previous state. No conflict resolution popup appears.

Version 3.0.0.5 (packaged)
OS: win
Chrome version: 43.0.2357.81 m (up to date)

**Comment by a85** [comment]
@intellix Sorry about the issue. It's hard to determine what users would like to Sync and what not if someone is working on two different computers at the same time with useful data on both systems. It might be an old system you enable Sync on but have the latest data on say an office computer. However, once your changes are on Sync, we back it up and your data is not lost. We tested out the system with almost 40 users in parallel before rolling it out to production but edge cases do occur.

@julian-pani Can you email us at help@getpostman.com with your account details? Will help you resolve this.
