### ISSUE TITLE
There was an error importing this collection. Please try again.

### ISSUE THREAD

**Issue by bedirhan** [a85/POSTMan-Chrome-Extension#10758]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues

### Describe the Issue

There are similar issues and always worked by having the latest release. But I'm on the latest release.

`You are up to date! Postman v9.14.13 is the latest version.`

### Steps To Reproduce

Click on Run in Postman here -> https://documenter.getpostman.com/view/7726481/S1TWzcX6?version=latest 

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/686074/158364940-276caa89-621f-4e93-801b-467a897fe118.png)

### Environment Information

```markdown
- Operating System: Windows 10 Pro
- Platform Type: Native App / Postman Web
- Postman Version: Postman v9.14.13
```

**Comment by Raja-Simha** [comment]
@bedirhan Thanks for reporting this issue. I can reproduce the issue. We will investigate and get back to you with an update.

**Comment by bhargavkaranam** [comment]
Hey @bedirhan,

You should be able to import this collection via Run in Postman now.

**Comment by bedirhan** [comment]
thanks for the fast response. it works now.

**Comment by WalterDias** [comment]
Same is happening on: https://documenter.getpostman.com/view/2669002/SWE84xMd

What was the solution to the problem @bhargavkaranam and @bedirhan

**Comment by AntonGsv** [comment]
Same - https://docs.api.onbuy.com/
