### ISSUE TITLE
Postman Api Endpoint Documentation WYSWIG Editor does not work with XML

### ISSUE THREAD

**Issue by Toumash** [a85/POSTMan-Chrome-Extension#10756]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues

### Describe the Issue

Cannot paste xml into the new wyswig documentation editor

### Steps To Reproduce

1. Open new request tab
2. Give it a name
3. Save it under some name
4. Open up the documentation panel on the right
5. Make sure you have WYSWIG beta editor opened not "classic markdown editor"
6. Copy below xml into the system clipboard

```xml
<xml>sad-pepe.jpg</xml>
```
7. Paste it into the documentation WYSWIG editor
8. The text is gonna say "sad-pepe.jpg" instead of the whole xml

### Screenshots or Videos

![postman-wyswig-bug](https://user-images.githubusercontent.com/9840635/158241408-27881caf-558c-49ed-86e0-797ac4ddb7aa.gif)

### Environment Information

```markdown
- Operating System: Windows 10
- Platform Type: Native App
- Postman Version: 9.14.13
```

**Comment by kamaraj-p** [comment]
Hi @Toumash , thanks for reporting this issue. This is due to whitelisting of only specific tags due to security concerns. Will check with the security team regarding  whitelisting `xml` tags and keep you posted.

**Comment by Toumash** [comment]
Oh, so you have some advanced copy&paste mechanism there? 
Then dont bother, the problem was originally with xml results from the endpoints, so no particular root element there, 
Impossible to whitelist If thats the case i would just close the issue.

The root cause is that i couldn't find and "code block" thing in the new editor, but its there.
