### ISSUE TITLE
Azure DevOps missing from code repository import

### ISSUE THREAD

**Issue by marc-wilson** [a85/POSTMan-Chrome-Extension#10757]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues

### Describe the Issue

When creating a new Api, you can select the option to import. On the import dialog, you can import from file, folder, link, raw text or code repository.

When selecting code repository, only GitHub and Bitbucket are present.

<img width="421" alt="image" src="https://user-images.githubusercontent.com/19480392/158276298-e5a67f4f-df1f-4f9a-955d-ffb3516e453e.png">

On an an existing Api, you can connect to a repository by selecting the drop down. In this drop down, there are more options present.

Are the lists just off or is there some sort of difference here?

<img width="236" alt="image" src="https://user-images.githubusercontent.com/19480392/158276414-bd3481e8-8817-4fee-bc09-74b4dd3a9dfd.png">

### Steps To Reproduce

1. Open postman
2. Select API's (create a new one if you don't have any)
3. Select Connect Respository
4. Observe Azure DevOps options

1. Open postman
2. Select Import
3. Select Code repository option in dialog
4. Observe there is no Azure DevOps option

### Environment Information

```markdown
- Operating System: MacOS
- Platform Type: Monterey 12.2.1
- Postman Version: 9.14.6
```

### Additional Context?

It would be nice if Azure DevOps was supported in postman.

**Comment by shashankawasthi88** [comment]
@mswilson4040 we have updated the flow for the existing API to give the ability for you to choose your API schema. That is essentially what you do while importing the schema from the repository. I would suggest creating an API in postman, connecting it to the Azure DevOps repo. The first PULL that you perform will allow you to choose an existing schema.

**Comment by marc-wilson** [comment]
Thanks, @shashankawasthi88. Three questions
1. Are you saying to create an empty API and then connect the repository?
2. Will there be support just like GitHub/Bitbucket on the import dialog in the near future?
3. For postman to automatically pick up the schema, does the swagger file need to be kept within the repository or can it be a link instead?

I was able to get it working, but down the road, if we wanted to import another repository/api, it'd be nice to just have the import wizard support DevOps.

**Comment by shashankawasthi88** [comment]
1. Yes, create an empty API and connect. The subsequent Pull will allow you to select the schema file from the repo.
2. We are trying to harmonize the flow of importing the APIs while connecting to the repository. So you might not see the exact same import option but the functionality will be provided.
3. Just for the import you could use the import via link that we have today. The repository integration provides a way for you to collaborate with your team across Postman and repository where the changes can be pushed in both directions, hence the file needs to be there in the repo.

**Comment by petkostas** [comment]
I think this is the same as my request, may be good to update the documentation or provide the link initially for importing.
https://github.com/postmanlabs/postman-app-support/issues/10811

**Comment by shashankawasthi88** [comment]
@petkostas yes this is similar to https://github.com/postmanlabs/postman-app-support/issues/10811, we are trying to optimize the import flow further, hence would keep the ticket open and communicate when we have updates.

**Comment by shashankawasthi88** [comment]
@mswilson4040 @petkostas - the import for the Azure DevOps has now been added.
