### ISSUE TITLE
Generating a collection from a .yaml with deepObjects yields unexpected results

### ISSUE THREAD

**Issue by ericdehmel** [a85/POSTMan-Chrome-Extension#10752]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues

### Describe the Issue

While generating a collection using an API specification I stumbled upon two issues with deepObjects:

- List nested inside deepObjects are generated as _deepObject[list][0]=value_ and _deepObject[list][1]=value_. I would have expected it to be deepObject[list]=value,value
- If a deepObject has a property called _length_ it will be interpreted as array and generate multiple parameters like _deepObject[i]_ up to the number that is set as example for  the _length_ property.

### Steps To Reproduce

1. Click on _Import_
2. Select the .yaml file:
```
openapi: 3.0.1
info:
  title: Demo
  version: "1.0"
paths:
  /get:
    get:
      operationId: someRequest
      parameters:
        - $ref: '#/components/parameters/DeepObjectNestedList'
        - $ref: '#/components/parameters/DeepObjectLengthParameter'
      responses:
        '200':
          description: Response on success.
components:
  parameters:
    DeepObjectNestedList:
      name: deepObjectNestedList
      in: query
      required: false
      style: deepObject
      schema:
        $ref: '#/components/schemas/DeepObjectNestedList'
      explode: true     
    DeepObjectLengthParameter:
      name: deepObjectLengthParameter
      in: query
      required: false
      style: deepObject
      schema:
        $ref: '#/components/schemas/DeepObjectLengthParameter'
      explode: true      
  schemas:
    DeepObjectLengthParameter:
      type: object
      properties:
        length:
          nullable: true
          type: integer
          format: int32
          minimum: 1
          example: 20    
    DeepObjectNestedList:
      type: object
      properties:
        nestedList:
          $ref: '#/components/schemas/NestedList'
          example: someValue,anotherValue  
    NestedList:
      nullable: true
      type: array
      items:
        type: string
        pattern: '[A-Z]{2}|[A-Z]{2}-[A-Z0-9]{1,3}'    
```
3. In advanced settings, use _Example_ to generate request parameters

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/93250152/158127402-8caf47fe-d0b3-4ecb-962c-20635b4b1df9.png)

### Environment Information

```markdown
- Operating System: Windows 10
- Platform Type: Native App
- Postman Version: 9.14.0
```

**Comment by VShingala** [comment]
@ericdehmel Thanks for reporting the issue!

As I understand OpenAPI specification doesn't mention the behavior of `array` under `deepObject` style ([source](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.3.md#style-examples)). This means currently, `array` is treated as an object and thus the behavior of each element is mentioned separately.

As for issue 2, Is the expected behavior to have the following key-value?
```
Key: deepObjectLengthParameter[length]
Value: 20
```

**Comment by ericdehmel** [comment]
As you have guessed I expected to get _deepObjectLengthParameter[length]=20_.

**Comment by VShingala** [comment]
@ericdehmel This issue should now be fixed. Feel free to reopen if you face any further problems.
