### ISSUE TITLE
Not able to use the values from external data sheet in request URL while running API collection

### ISSUE THREAD

**Issue by Marutikokane** [a85/POSTMan-Chrome-Extension#10754]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues

### Describe the Issue

While running API collection by using external data sheet variables (excel sheet >converted to .csv file) am not able to fetch those values in request URL, its asking unresolved variable create to access it.

### Steps To Reproduce

1. Create data sheet with some variables like endpoints
2. Go to the collection runner and select respective datasheet
3. Run the collection 
4. Observe the error message while running the collection

### Environment Information

```markdown
- Operating System: 64
- Platform Type: 
- Postman Version: Postman v9.14.13
```

### Additional Context?

How to run the collection using variables from external file that used in request url

**Comment by postman-staff** [comment]
Hi @Marutikokane

Just tested this from my end and was unable to arrive at the issue. Would it be possible for you to share more information regarding this, such as screenshots and files used to check the issue?

Please feel free to submit a ticket to: https://postman.com/support and share the details as requested to help us assist you further.

via @Raj-postman | Postman Support
