### ISSUE TITLE
Custom sandbox - Add support for md5 or a possibility to include custom JS files

### ISSUE THREAD

**Issue by andyHa** [a85/POSTMan-Chrome-Extension#1076]
Could you include crypto-js to the standard libraries or add a possibility to include own libraries to add further functions like "md5".

**Comment by a85** [comment]
CryptoJS is available now in the Postman sandbox. Ability to add custom JS files will come soon and is being tracked in another bug.

**Comment by edanhauon** [comment]
Hi,

So how can I calculate md5 for a file using CtyptoJS in postman sandbox?

thanks.
