### ISSUE TITLE
[Incident][Resolved] Postman 9.15.1 shows a blank white screen

### ISSUE THREAD

**Issue by cyphercookie** [a85/POSTMan-Chrome-Extension#10763]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues

### Describe the Issue

When opening postman no main landing page loads and there is no way to get it to load. I get the bar at the top with all the drop down menu's for Postman but nothing I click on loads the main landing page.

have had to revert to version 6 to get anything to appear on screen.

### Steps To Reproduce

1. open postman

### Environment Information

```markdown
- Operating System: 12.2.1
- Platform Type: macOS
- Postman Version: 8.12.4 & 9.15.0
```

### Additional Context?

I have gone through and deleted the presences from ~/Library/Application Support/ & ~/Library/Preferences and this still did not fix the issue.

**Comment by ritikBhandari** [comment]
Can I resolve this issue if an existing issue is not present?

**Comment by cyphercookie** [comment]
what do you mean by "is not present"?

**Comment by ritikBhandari** [comment]
I mean if this issue is something which is not similar to any existing one, can i resolve it?
Because if there is a similar one present, then i think there's no need to resolve this separately.

**Comment by cyphercookie** [comment]
if that is the case yes. Can you also point me to the issue so I can review?

**Comment by ritikBhandari** [comment]
Though I didn't find any issue simliar to this one right now, I'll inform if I find later.

**Comment by JoseALermaIII** [comment]
I've got the same on Windows 10 after upgrading:
![Postman9.15.1-Windows10.png](https://user-images.githubusercontent.com/11242372/158873744-45ef0703-e04d-41ac-99c6-dd9a1651d909.png)

I've tried uninstalling, then reinstalling Postman 9.15.1, but it's still the same. I might need to delete application data.

```
Windows 10 21H1 19043.1586
Postman version: 9.15.1
```

**Comment by giridharvc7** [comment]
@JoseALermaIII @cyphercookie Could you send us your [app logs](https://support.postman.com/hc/en-us/articles/360025298633-How-to-collect-logs) here or to [help@postman.com](mailto:help@postman.com)? It'll help us triage and resolve this issue fast.

**Comment by giridharvc7** [comment]
Also, @JoseALermaIII @cyphercookie are you using scratchpad?

**Comment by mrlemki** [comment]
> @JoseALermaIII @cyphercookie Could you send us your [app logs](https://support.postman.com/hc/en-us/articles/360025298633-How-to-collect-logs) here or to [help@postman.com](mailto:help@postman.com)? It'll help us triage and resolve this issue fast.

I've sent mine via email with this ticket title in the subject.

**Comment by sparcbr** [comment]
I've got the same problem, a blank window with only the menus, No option from the menu works.
When postman opens not even the animation loader shows.
I'm running the lastest version on Ubuntu (Version 9.15.1). I downloaded the tgz from postman website. The same happens with postman installed from snap.
I've got the following messages when running in the terminal:

```
❯ ~/Postman/Postman
The disableGPU setting is set to true
Disabling GPU
Setting disableGPU to true
[3665:0317/162621.911034:ERROR:gpu_init.cc(453)] Passthrough is not supported, GL is disabled, ANGLE is 
Main~createDefaultWorkingDir - Default working dir creation already attempted
1647545181950 main info "Booting Postman 9.15.1, linux-5.13.0-35-generic on x64"
1647545181952 main info "EventBus~initialize - Success"
1647545181955 main info "Proxy configuration has not been setup"
1647545181955 main info "CloudProxyManager~init - Success"
1647545181961 main info "UpdateHandler~init - Success"
1647545182279 main info "RuntimeIPCAgent~started: Success"
1647545182281 main info "LinuxAutoUpdater~Cleanup - Initial cleanup successful"
1647545182282 main info "LeaderSelection: Initialized successfully"
1647545182283 main info "VersionDependencyService: Initialized successfully"
1647545182313 main info "Bootstrap-models~bootstrap - Success"

```

**Comment by giridharvc7** [comment]
@mrlemki @sparcbr Want to quickly confirm if you use just the Scratchpad or do you also sign in to the app

**Comment by sparcbr** [comment]
> @mrlemki @sparcbr Want to quickly confirm if you use just the Scratchpad or do you also sign in to the app
I wasn't logged in, and yesterday it was working. I'm almost certain I didn't install or change anything. It's very weird..

**Comment by akhakpouri** [comment]
This also occurs when I upgraded from version `9.14.13` to `9.15.1`. I had to uninstall Postman, find an older version of postman, `v. 9.3.0` then proceeded to upgrade to `9.14`. 
After upgrading to version `9.14`, I supposed the next version was going to be `9.15.1` again. But, to my surprise, the next version Postman was upgraded to was `9.14.14`. Postman `9.14.14` doesn't exist in the [release-notes](https://www.postman.com/downloads/release-notes/) page.

![image](https://user-images.githubusercontent.com/4137746/158883321-28aba958-c4ec-49f9-83a2-8053f68a710d.png)

**Comment by giridharvc7** [comment]
We are looking into the issue in priority,  apologies for the inconvenience. 
Meanwhile, you can unblock yourself by downloading the 9.14.x. Here are the download links 
[Windows](https://dl.pstmn.io/download/version/9.14.0/win64)
[Mac](https://dl.pstmn.io/download/version/9.14.0/osx_64)
[Mac M1](https://dl.pstmn.io/download/version/9.14.0/osx_arm64)
[Linux](https://dl.pstmn.io/download/version/9.14.0/linux)

**Comment by polar-nik** [comment]
Have the same issue, just blank screen.

![Снимок экрана 2022-03-17 225236](https://user-images.githubusercontent.com/12606182/158884921-ad9f14c1-e780-4206-a3ab-7dc9d37e6b2c.jpg)

Windows 11 21H2
Postman 9.15.1

**Comment by giridharvc7** [comment]
@inickolay Could you send us your [app logs](https://support.postman.com/hc/en-us/articles/360025298633-How-to-collect-logs) to [help@postman.com](mailto:help@postman.com)? It'll help us triage and resolve this issue fast.

**Comment by proutek** [comment]
I have deleted app-9.15.1 folder and postman now starts just fine.
Now I'm on app-9.15.0.

**Comment by giridharvc7** [comment]
@proutek @inickolay can you share some logs from the dev tools? Specifically BOTH from the Current Shell and Current View
<img width="507" alt="Screenshot 2022-03-18 at 2 06 09 AM" src="https://user-images.githubusercontent.com/1040583/158890815-b7b75bb1-db49-46d1-8e6e-b04a86519a57.png">
Would be amazing if you can get on a call with us, will really help us debug this quickly.

**Comment by JoseALermaIII** [comment]
Hi @giridharvc7, 

> Also, @JoseALermaIII @cyphercookie are you using scratchpad? 

No, I don't use ScratchPad - I'm always online and logged in.

>@JoseALermaIII @cyphercookie Could you send us your app logs here or to help@postman.com? It'll help us triage and resolve this issue fast.

I'll work on sending the app logs. Thanks for looking into it!

_edit:_ App logs sent with this issue as the subject

**Comment by sparcbr** [comment]
On current shell there is this on console:
```
Uncaught TypeError: Cannot read properties of undefined (reading 'app')
    at Module../js/electron/ElectronService.js (shell.js:2)
    at r (shell.js:2)
    at Module.<anonymous> (shell.js:2)
    at Module../js/modules/services/ShellCrashReporter.js (shell.js:2)
    at r (shell.js:2)
    at Module../js/apps/boot/bootShellCrashReporter.js (shell.js:2)
    at r (shell.js:2)
    at Module.<anonymous> (shell.js:2)
    at Module../js/apps/shell/init.js (shell.js:2)
    at r (shell.js:2)
```

Current view does'n open anything when I click this option

**Comment by giridharvc7** [comment]
@sparcbr Thank you, this helps a lot. Are you on Windows?

**Comment by mrlemki** [comment]
> > @mrlemki @sparcbr Want to quickly confirm if you use just the Scratchpad or do you also sign in to the app
> > I wasn't logged in, and yesterday it was working. I'm almost certain I didn't install or change anything. It's very weird..

Yes I'm just on the scratchpad.

**Comment by sparcbr** [comment]
> @sparcbr Thank you, this helps a lot. Are you on Windows?
Ubuntu 21.10

**Comment by sparcbr** [comment]
I changed the shell to clean bash to see if it would make a difference but it didn't.  (I use zsh)

**Comment by numaanashraf** [comment]
Hey folks, we've identified the issue and are working on releasing a patch for this in a short while. For now, the recommended solution is to downgrade to the latest 9.14.x version via the links here.

https://github.com/postmanlabs/postman-app-support/issues/10763#issuecomment-1071294592

We'll post further updates here and on https://status.postman.com/incidents/fk7gt91s60vk

**Comment by numaanashraf** [comment]
We've released a patch to address the blank screen issue in v9.15.2. Please download & install this latest version from www.postman.com/downloads. Closing this issue.

**Comment by JoseALermaIII** [comment]
Upgrading from 9.14.0 to 9.15.2 worked for me.

Thanks for the prompt fix!

**Comment by kapakym** [comment]
Thank you, it works!

**Comment by cyphercookie** [comment]
I can confirm that the new version has fixed the issue! :) Many thanks fox fixing it so quickly!

**Comment by polar-nik** [comment]
> @proutek @inickolay can you share some logs from the dev tools? Specifically BOTH from the Current Shell and Current View <img alt="Screenshot 2022-03-18 at 2 06 09 AM" width="507" src="https://user-images.githubusercontent.com/1040583/158890815-b7b75bb1-db49-46d1-8e6e-b04a86519a57.png"> Would be amazing if you can get on a call with us, will really help us debug this quickly.

I'm sorry, I had to fix bugs urgently and hand over the work, and I just rolled back to the previous version of the application :(

**Comment by knofiller** [comment]
Install Postman-win64-9.15.2 and not able to change log out or change account. When click on my icon, all drop down menu (account settings, Notification Preferences, active session, sign out) not able to click.

**Comment by lipp23** [comment]
Still broken....

**Comment by giridharvc7** [comment]
@lipp23 Can you share some recordings etc of this pls?

**Comment by lipp23** [comment]
Sorry, my fault. Running as root caused the issue...

**Comment by surennarayan** [comment]
now again same problem after 2 years the blank screen

**Comment by ANNaA55** [comment]
Добрый день! Аналогично - белый кран, приходится пользоваться веб-версией 

![Image](https://github.com/user-attachments/assets/67667675-2b50-4854-89b5-e989abeec3e7)

**Comment by LouisGameDev** [comment]
If you see a blank screen, logging out of the app and logging back in seems to resolve the issue for me. I hadn’t used Postman in years, and it appears the old login session was causing the white or blank home screen bug.
