### ISSUE TITLE
"mutate" not work in method "VariableList.substitute"

### ISSUE THREAD

**Issue by curiosity-hyf** [a85/POSTMan-Chrome-Extension#10769]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues

### Describe the Issue

The `mutate` not work in method `VariableList.substitute(obj, overrides, mutate)`.

### Steps To Reproduce

1. Create an `Environment`
<img width="807" alt="image" src="https://user-images.githubusercontent.com/16988840/159119322-3ea2c657-31e7-4f86-9e8d-1b58f599aa2d.png">

2. Write `Pre-request Script`
<img width="723" alt="image" src="https://user-images.githubusercontent.com/16988840/159119369-b78a6bf5-0278-4807-951a-3cedc516643c.png">

3. Console View
<img width="347" alt="image" src="https://user-images.githubusercontent.com/16988840/159119387-cf1403a6-22a4-4d77-bbcf-64564c4a0346.png">

<hr>

Expected: 
`obj1` -> `["any"]`, `obj2` -> `[{bar: "{{var}}"}]`

### Environment Information

```markdown
- Operating System: Mac OS 11.5
- Platform Type: Native App
- Postman Version: 9.15.0
```

### Additional Context?

Related document and code:
http://www.postmanlabs.com/postman-collection/VariableList.html#substitute
http://www.postmanlabs.com/postman-collection/collection_variable-list.js.html#line43

http://www.postmanlabs.com/postman-collection/Property.html#.replaceSubstitutionsIn
http://www.postmanlabs.com/postman-collection/collection_property.js.html#line239

**Comment by DannyDainton** [comment]
Hey @curiosity-hyf 

What's your usecase here? 

It's unclear what you're trying to do, could you expand on the details, please?

**Comment by curiosity-hyf** [comment]
Hey @DannyDainton
I want to access the full request url which contains the environment variable (Ex `http://{{server}}/{{var1}}/{{var2}}`).
So I try `pm.environment.values.substitute(pm.request.url, null,  false)`. It's works but also changes the original `pm.request.url`.

**Comment by DannyDainton** [comment]
Is this something you could use to access that value:

```
pm.variables.replaceIn('http://{{server}}/{{var1}}/{{var2}}') 
```

https://learning.postman.com/docs/writing-scripts/script-references/postman-sandbox-api-reference/#using-variables-in-scripts

**Comment by curiosity-hyf** [comment]
Thank you, it works!

Could update Docs If `mutate` no longer works in method `VariableList.substitute`?

**Comment by DannyDainton** [comment]
To use the full Collection SDK in the sandbox, you would need to require the module.

https://learning.postman.com/docs/writing-scripts/script-references/postman-sandbox-api-reference/#using-external-libraries

As it looks like you're now seeing what you expect, I'm going to close out this issue.
