### ISSUE TITLE
Postman does not support saving gRPC imported files as API Definitions

### ISSUE THREAD

**Issue by Alcas1** [a85/POSTMan-Chrome-Extension#10767]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request

### Is your feature request related to a problem?

Every time postman closes or crashes I need to setup gRPC calls from scratch because it can't be saved when using files with multiple imports.

### Describe the solution you'd like

Multiple file imports should be save-able as an API definition 

### Describe alternatives you've considered

I've tried copying and pasting everything from other files into this proto file to avoid imports. But this is not feasible short-term or long-term. It's too hard to maintain for an actual product development lifecycle.

### Additional context

![Screen Shot 2022-03-18 at 2 48 21 PM](https://user-images.githubusercontent.com/1725146/159066308-60b030fc-81f5-4c86-9b8f-febcab4698b6.png)

**Comment by codenirvana** [comment]
We've added support for importing multi-file API definitions.
Though you can’t edit imported proto files from Postman just yet... we will unblock editing very soon!

For now, you can re-import to update your saved API.
