### ISSUE TITLE
Error opening anything in the collection: TypeError: e.push is not a function

### ISSUE THREAD

**Issue by koriit-kontakt** [a85/POSTMan-Chrome-Extension#10762]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues

### Describe the Issue

I cannot open anything in my collection, including the collection itself - the tab breaks and shows Something Went Wrong. 

Interestingly only one of my collections is affected but if I open it in a tab, I cannot open anything anymore in that tab.

The only error log I could find that consistently appears is:
```
scratchpad.js:477 TypeError: e.push is not a function
    at scratchpad.js:71
    at Array.reduce (<anonymous>)
    at l (scratchpad.js:71)
    at u (scratchpad.js:71)
    at render (scratchpad.js:71)
    at $ (scratchpad.js:2)
    at scratchpad.js:2
    at me (scratchpad.js:2)
    at e.track (scratchpad.js:2)
    at r.l [as render] (scratchpad.js:2)
    at Wo (scratchpad.js:2)
    at Bo (scratchpad.js:2)
    at Ss (scratchpad.js:2)
    at yc (scratchpad.js:2)
    at mc (scratchpad.js:2)
    at sc (scratchpad.js:2)
    at scratchpad.js:2
    at t.unstable_runWithPriority (scratchpad.js:2)
    at Qi (scratchpad.js:2)
    at Ji (scratchpad.js:2)
    at Yi (scratchpad.js:2)
    at cc (scratchpad.js:2)
    at Le (scratchpad.js:2)
    at Pe (scratchpad.js:2)
    at Ie (scratchpad.js:2)
    at Lt (scratchpad.js:2)
    at x.initializeContributions (scratchpad.js:375)
    at scratchpad.js:375
```
After pretty print:
```
e.prototype.instrumentConsole = function() {
                "console"in Ze && ["debug", "info", "warn", "error", "log"].forEach((function(t) {
                    t in Ze.console && B(Ze.console, t, (function(n) {
                        return function() {
                            for (var r = [], i = 0; i < arguments.length; i++)
                                r[i] = arguments[i];
                            var a = {
                                category: "console",
                                data: {
                                    extra: {
                                        arguments: Z(r, 3)
                                    },
                                    logger: "console"
                                },
                                level: u.fromString(t),
                                message: D(r, " ")
                            };
                            "assert" === t && !1 === r[0] && (a.message = "Assertion failed: " + (D(r.slice(1), " ") || "console.assert"),
                            a.data.extra.arguments = Z(r.slice(1), 3)),
                            e.addBreadcrumb(a, {
                                input: r,
                                level: t
                            }),
                            n && Function.prototype.apply.call(n, Ze.console, r)  // apparently offending line
                        }
                    }
                    ))
                }
                ))
            }
```
```
function l(e) {
        if (!e)
            return;
        return e.variables.reduce(((e,t)=>!1 === t.enabled || !0 === t.disabled ? e : e.push({ // apparently offending line
            scope: "collection",
            name: t.key || "",
            value: t.value,
            sessionValue: t.sessionValue
        })), [])
    }
```
The problem appears in scratchpad no matter if I am logged in or not (though I couldn't get the error to be logged after logging in).
The problem does not appear if I import the collection to a workspace.

### Steps To Reproduce

1. Open scratchpad
2. Import the collection
3. Open the collection or any request in it

I did not try to reproduce the issue on clean Postman installation.

[DCC.postman_collection.json.zip](https://github.com/postmanlabs/postman-app-support/files/8285024/DCC.postman_collection.json.zip)

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/75976467/158804792-49e6b8a3-b593-4668-8cf0-f1d03962c598.png)

### Environment Information

```markdown
Postman for Windows
Version 9.15.0
Architecture x64
Platform win32 10.0.19044

Scratchpad 
Logged in + Logged out
```

### Additional Context?

I have not changed the collection in any way to make it broken. I believe Postman auto-updated today and after that, I couldn't open the collection.

**Comment by Ghosty-chan** [comment]
Same here, Updated to v9.15.0 (from v9.14.)

In my case, I've used Variable "on" Variable in one Collection.
Most of my collections use those "dynamic" variable references..

To Reproduce (ScratchPad, but I assume its same behaviour on logged-in):
- Create New Collection
- Open Collection Variables and enter:
  - testvar: {{testvar2}}
- Select next line / new variable... tada' something went wrong. (Unresolved Variable may causing it!?)

Nice that the changelogs include some bugfixes & Cookies.. 
but no reference about "THIS"..

**Comment by npu-sword** [comment]
Same problem here...
Revert to previous version for me: https://dl.pstmn.io/download/version/9.14.0/win64

**Comment by Rob-Barrow** [comment]
Same for me - no collections can be opened after upgrading to 9.15.0 on my Mac today, all I get on screen is:
**Something Went Wrong
Postman has encountered an error. If this problem persists, contact us at help@postman.com**
I urgently need access to my collections again, which I had this morning... is there a roll-back process we can use? 

'About' states:
Postman for Mac
Version 9.15.0
Architecture x64
Platform OS X 20.6.0

**Update:**
rolled back to 9.14.0 for Mac and all okay again:
https://dl.pstmn.io/download/version/9.14.0/osx
Many thanks [npu-sword](https://github.com/npu-sword) for the download location!

**Comment by RalfNaujokat** [comment]
Bad news is,
postman automatically downloads the 9.15.0 version
and installs it on next start...
You cannot disable minor updates in the settings.

**Comment by giridharvc7** [comment]
Thanks for reporting, We have found the issue and we are raising the hotfix for the same. 
Sorry for the inconvenience

**Comment by Rob-Barrow** [comment]
> Bad news is, postman automatically downloads the 9.15.0 version and installs it on next start... You cannot disable minor updates in the settings.

You can always do this to block all Postman updates to the app while they are working on fixing it:
**sudo chflags -R schg Postman.app**
... although you have to bear in mind the following:
_The schg flag can be used to lock a file or folder. However, this flag can only be set by the root user or an admin user using sudo. And once set, it is much harder to unset it, so it is more permanent. The schg flag can only be unset in single-user mode (restart your Mac and hold down Command-S after the chime)._

**Comment by mminot-yseop** [comment]
Argl, too bad I saw that after wasting hours scrapping data and reinstalling, and trying the `snap` version.
Also strange that https://dl.pstmn.io/download/version/9.14.0/linux64 works but not the equivalent for v9.14.13 (AFAICT).

**Comment by mrlemki** [comment]
Same problem for me. Adding more than one variable to a non-workspace collection breaks it.

**Comment by giridharvc7** [comment]
We've raised a hotfix and its available at v9.15.1 , please try and let us know if you face any issues!

**Comment by jshea** [comment]
It's not working for me. After the update was applied I now get a blank window. I uninstalled, downloaded the 9.15.1 installer, installed and still get a blank window.
![image](https://user-images.githubusercontent.com/2157922/158876479-eaa9b26d-cb37-4ba6-b00c-4cfa8ad831a8.png)

**Comment by mminot-yseop** [comment]
Same here. “Restart now” button in settings after the update was downloaded, and got a blank window.
![image](https://user-images.githubusercontent.com/36635838/158876568-dd788b4f-4f5a-4d34-b04e-5758293de74e.png)

Couldn’t quit it gracefully; had to kill it.
Edit: Argl, the “nice” kill left it running in the background with a CPU at 100% 😅 Had to send signal 9.

**Comment by mrlemki** [comment]
Yeah same for me. 9.15.1 is a blank window.

**Comment by giridharvc7** [comment]
Looking into this right away, looks like this might be related to https://github.com/postmanlabs/postman-app-support/issues/10763

**Comment by RalfNaujokat** [comment]
Same here, delete cache and restart does not help

**Comment by numaanashraf** [comment]
@RalfNaujokat @mrlemki @mminot-yseop @jshea Could you send us your [app logs](https://support.postman.com/hc/en-us/articles/360025298633-How-to-collect-logs) to help@postman.com? It'll help us triage and resolve this issue fast.

**Comment by RalfNaujokat** [comment]
done

**Comment by giridharvc7** [comment]
We are looking into the issue in priority, apologies for the inconvenience.
Meanwhile, you can unblock yourself by downloading the 9.14.x. Here are the download links
[Windows](https://dl.pstmn.io/download/version/9.14.0/win64)
[Mac](https://dl.pstmn.io/download/version/9.14.0/osx_64)
[Mac M1](https://dl.pstmn.io/download/version/9.14.0/osx_arm64)
[Linux](https://dl.pstmn.io/download/version/9.14.0/linux)

**Comment by giridharvc7** [comment]
Have pinned #10763 . Please use that ticket to follow.

**Comment by numaanashraf** [comment]
We've released the fix for this issue and the [blank screen issue](https://github.com/postmanlabs/postman-app-support/issues/10763) in v9.15.2. Please download this version from www.postman.com/downloads. 

Closing this issue.
