### ISSUE TITLE
Cannot remove the broken API data from Private API Network

### ISSUE THREAD

**Issue by doyard** [a85/POSTMan-Chrome-Extension#10770]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues

### Describe the Issue

Cannot delete a broken API item from Private API Network.

Click The API folder  will recieve an error notification. "Cannot parse the response as json"
The Remove button in the menu of the API folder is disabled and shows a message, "Only Editors of this API can remove it from the network".

But No such API in the list of APIs sidebar.

### Steps To Reproduce

Cannot reproduce.

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/93499036/159149494-56b9f3ec-27be-4a9c-9014-01f384bc7206.png)

### Environment Information

```markdown
- Operating System: macOS 12.2.1 (21D62)
- Platform Type: Desktop/Web
- Postman Version: 9.14.14
```

**Comment by bhargavkaranam** [comment]
Hey @chamhaw,

Could you please shoot an email to help@postman.com with the API id that's causing this issue? We'll take a look. You can also just use the Copy link option and forward the link in the email.

**Comment by vashanth-s** [comment]
@doyard Feel free to reopen the issue if it still exists
