### ISSUE TITLE
"Host" auto-generated heade keeps on being check again

### ISSUE THREAD

**Issue by thedude4ever** [a85/POSTMan-Chrome-Extension#10774]
hello, when I uncheck the "Host" auto-generated header, it keeps on being check again. This happens only when I use a variable for endpoint, could you please give me some help? thanks a lot

![image](https://user-images.githubusercontent.com/83371417/159493269-7bdf9ae6-19c4-4db5-a818-ebe98f91e664.png)
![image](https://user-images.githubusercontent.com/83371417/159493664-db638b03-998c-45ee-92f2-49a5a880942f.png)
![image](https://user-images.githubusercontent.com/83371417/159493871-4ef151fb-b468-4faa-9481-5cef5b710474.png)

_Originally posted by @thedude4ever in https://github.com/postmanlabs/postman-app-support/issues/8800#issuecomment-1075187515_

**Comment by DannyDainton** [comment]
Hey @thedude4ever 

Can you also please provide the Steps to Reproduce the issue and the Environment details.

**Comment by thedude4ever** [comment]
$ should be removed, closed
