### ISSUE TITLE
GraphQL schema auto-fetch fails if auth set to "Inherit auth from parent"

### ISSUE THREAD

**Issue by joe-highnote** [a85/POSTMan-Chrome-Extension#10773]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues

### Describe the Issue

GraphQL schema auto-fetch fails if auth set to `Inherit auth from parent`. Setting auth to `Basic` on the request itself allows auto-fetch to work as expected.

### Steps To Reproduce

1. Configure parent with auth for child requests
2. Create child GraphQL request and set auth to `Inherit auth from parent`
3. Set `Auto-fetch` for the schema
4. Error is displayed (no detail appear in console): `Could not auto-fetch. Make sure Authorization, URL, & selected environment are valid. Check console for more details.`
5. Update auth for request to `Basic` and supply credentials as are configured in parent
6. Auto-fetch will now work as expected

### Environment Information

```markdown
- Operating System: macOS 12.1
- Platform Type: Native App
- Postman Version: 9.15.3
```

**Comment by DannyDainton** [comment]
Hey @joe-highnote 

Thanks for raising the issue 🏆 , I've been able to reproduce the problem on my side.

We'll update the thread with any additional information once we have some to share. 🙏🏻

**Comment by dsstewa** [comment]
@DannyDainton  @joe-highnote  

I would like to add some additional details to this bug. It also appears the schema auto-fetch does not recognize any variables either. 

Meaning if I have the following in the URL `{{my-api-base-url}}` the schema autofetch will attempt to grab the schema from `https://{{my-api-base-url}}`. 

This is also happening when auth is not inherited, so if a variable is set for the auth key it will transmit the `Authorization {{my-api-key}}}`.

**Comment by joe-highnote** [comment]
@dsstewa That is interesting. I am not seeing the behavior you describe. I have my URL pulling from an environment variable and it works as long as I have the auth set directly on the request and not inherited.

![image](https://user-images.githubusercontent.com/90255568/162042312-c8e5554b-4681-46b5-af4a-8afb6a74d16a.png)

**Comment by dsstewa** [comment]
@joe-highnote When I go to hit schema re-fresh button I get the following error in my console: 

![image](https://user-images.githubusercontent.com/45477783/162043998-6e39ca4c-52b2-425e-a76f-b7fbfd4a6246.png)

![image](https://user-images.githubusercontent.com/45477783/162044534-1878c9d6-fbc4-4770-aafb-ab39c7fe233c.png)

Version 9.15.10
UI Version: 9.15.10-ui-220331-0650
Desktop Platform Version: 9.15.2 (9.15.2)

**Comment by bo55vxr** [comment]
The issue is not restricted to "Inherit from Parent", I have my Authorisation settings as `Type ="Bearer Token"` and `Token = "{{myGraphToken}}"` - The Authorisation header is being sent as `Bearer {{myGraphToken}}`

https://stackoverflow.com/questions/71795540/postman-graphql-schema-fetch-authorisation

**Comment by moon-sam** [comment]
The variables issue seems to have been flagged in https://github.com/postmanlabs/postman-app-support/issues/10806

**Comment by giridharvc7** [comment]
This is fixed with v9.18.2. Feel free to open this if you still face this issue

**Comment by cinchy-m** [comment]
@giridharvc7 The [download page](https://www.postman.com/downloads/) displays `Version 9.18.2` but both Mac download options (https://dl.pstmn.io/download/latest/osx_arm64 and https://dl.pstmn.io/download/latest/osx_64) download `v9.16.0` which is actually skipping 3 versions, according to the [release notes](https://www.postman.com/downloads/release-notes/).

How can we download `9.18.2`?

**Comment by Shereef** [comment]
I updated what I had installed and it worked after that
I had to check for update manually

**Comment by cinchy-m** [comment]
Thanks @Shereef, manual update check from within the app worked.

**Comment by bo55vxr** [comment]
Did this fix resolve the `{{variable}}` substitution issue

**Comment by orome** [comment]
I have 9.19.3 and my scream are not syncing (though I have no trouble sending and getting the expected results).
