### ISSUE TITLE
Get request is getting truncated

### ISSUE THREAD

**Issue by ghost** [a85/POSTMan-Chrome-Extension#1077]
Below Get Request Truncated
GET /servoy-service/rest_ws/mod_rest/ws_job_reports/e90b5aebf1311a6c1ebb69bf9c53fc318072624c60c55525/reportNumber=14&jobId=580450&level=3&getDataSet=true&getChart=false&detailedInfo=true&page=1&useCache=false&region=&state=PA&zip={{temp_ HTTP/1.1

Should be this

GET /servoy-service/rest_ws/mod_rest/ws_job_reports/e90b5aebf1311a6c1ebb69bf9c53fc318072624c60c55525/reportNumber=14&jobId=580450&level=3&getDataSet=true&getChart=false&detailedInfo=true&page=1&useCache=false&region=&state=PA&zip={{temp_ zip3}}  HTTP/1.1

**Comment by a85** [comment]
Not able to replicate.
