### ISSUE TITLE
Postman display Blank Screen

### ISSUE THREAD

**Issue by FuzzyDee** [a85/POSTMan-Chrome-Extension#10772]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues

### Describe the Issue

I click to open Postman from my Taskbar
expect the postman app to open and load all my collections
Actually displaying blank screen.
when i click the X to close the window it is not closing but when I click __ to minimise the window it does minimise the window.
On the blank screen I click File to open a collection nothing happen file explorer is not opening.
<img width="953" alt="blankpostman" src="https://user-images.githubusercontent.com/20218539/159325814-4bfa2125-3a40-4ebb-8e6f-52bd0a9a927b.PNG">

### Steps To Reproduce

I click to open Postman from my Taskbar
expect the postman app to open and load all my collections
Actually displaying blank screen.
when i click the X to close the window it is not closing but when I click __ to minimise the window it does minimise the window.
On the blank screen I click File to open a collection nothing happen file explorer is not opening.
<img width="953" alt="blankpostman" src="https://user-images.githubusercontent.com/20218539/159325814-4bfa2125-3a40-4ebb-8e6f-52bd0a9a927b.PNG">

### Screenshots or Videos

<img width="953" alt="blankpostman" src="https://user-images.githubusercontent.com/20218539/159325912-05fd52cc-bc71-4c90-a061-e7c6a482cf86.PNG">

### Environment Information

```markdown
- Operating System: Windows 10.0.19042
- Platform Type: Native App
- Postman Version: Postman 9.8.3
```

### Additional Context?

Very weird not sure if it's the new update that ruin the previous version

**Comment by numaanashraf** [comment]
@FuzzyDee This looks like a duplicate of this #10763. Could you follow the steps detailed here and let us know if the app works for you? https://github.com/postmanlabs/postman-app-support/issues/10763#issuecomment-1071909372

**Comment by numaanashraf** [comment]
Duplicate of #10763
