### ISSUE TITLE
Feature Request - Add support for multiple values (dropdown list) for environment variables

### ISSUE THREAD

**Issue by jorgemuza** [a85/POSTMan-Chrome-Extension#10775]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request

### Is your feature request related to a problem?

In the Environments section whenever each variable can only have ONE value at a time, it would be cool to have an option to either have a single value or a dropdown list of values, that way you can define multiple test scenarios whenever the value of a particular variable needs to change.

### Describe the solution you'd like

In the Environments section whenever each variable can only have ONE value at a time, it would be cool to have an option to either have a single value or a dropdown list of values, that way you can define multiple test scenarios whenever the value of a particular variable needs to change.

**Comment by daltontouch** [comment]
I would also like to see this, would add a lot of value to the product for my team.

**Comment by alessio4tech** [comment]
This would be a very useful feature

**Comment by preethammavin** [comment]
Hey, have you tried using passing a data file with CSV values? For scenario-based testing, we support them on the collection runner. https://learning.postman.com/docs/running-collections/working-with-data-files/

This helps you preview as well as multiple iterations done for different scenarios.

**Comment by 27shutterclicks** [comment]
I believe the idea is to be able to SELECT values from a dropdown list in the variables section of the collection runner. Right now, I have a spreadsheet with many IDs and I have to switch from the spreadsheet to the variables to keep copying and pasting values from one to the other. It gets tiring fast. 

It would be much easier to specify a path to the spreadsheet and have a (searchable) dropdown for the variable to be selected as needed.

This would be similar to how a list of possible variables appear when you type {{ in the value field of the Params tab or even in the request url field.

**Comment by andrewbezzina** [comment]
yes please put in this feature

**Comment by sushantkadam17** [comment]
Is there  any update on this feature ?

**Comment by sushantkadam17** [comment]
@giridharvc7 &  @preethammavin  : Any update on this feature ?

**Comment by o15a3d4l11s2** [comment]
Isn't this similar to https://github.com/postmanlabs/postman-app-support/issues/4525?

**Comment by sandeep-singh-pstmn** [comment]
tracking it here https://github.com/postmanlabs/postman-app-support/issues/4525
