### ISSUE TITLE
Odata call returns sometimes wrong Response and disappeared requets

### ISSUE THREAD

**Issue by Jannik-JungDMS** [a85/POSTMan-Chrome-Extension#10783]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues

### Describe the Issue

Sometimes, requests via an Odata interface return completely different values than expected. After a restart, the expected values are available when the request is executed again.
The error only occurs with Postman, when executed via our web app the expected values are returned.
When debugging the error, no other values could be observed than those given. In addition, postman "deletes" individual requests from an existing collection from time to time. After several restarts of the application they appear again.

### Steps To Reproduce

1. Open existing Odata request
2. filter bei Id
3. Sometimes it returns wrong values (sometimes this error also occurs when I run Postman over night and execute than the request)
4. Restart Postman

### Environment Information

```markdown
- Operating System: Windows 11
- Platform Type: 
- Postman Version: 9.15.4
```

### Additional Context?

Many other people use this Request and many of them have the same Issue

**Comment by DannyDainton** [comment]
Hey @Jannik-JungDMS 

Are you able to provide more details about the issue please, this will help us try to reproduce the problem.

**Comment by Jannik-JungDMS** [comment]
> Hey @Jannik-JungDMS
> 
> Are you able to provide more details about the issue please, this will help us try to reproduce the problem.

Unfortunately not. We got this issue some times and can't find a way to reproduce this issue after restart postman.

**Comment by DannyDainton** [comment]
Thanks for the reply @Jannik-JungDMS 

I'm going to close out this issue for now, if you are still facing a problem and can provide a reliable set of steps the reproduce the issue - we can look to open it again.
