### ISSUE TITLE
All My collections are not lost as the New UI does not render properly in the chrome.

### ISSUE THREAD

**Issue by koolsip-cap** [a85/POSTMan-Chrome-Extension#1078]
All My Saved collections are not lost as the New UI does not render properly in the chrome.

Chrome Version: 43.0.2357.81 m

Post Man Version
Version 3.0.0.1 (packaged)
OS: win
Architecture: x86-32
Native client architecture: x86-64

**Comment by abhijitkane** [comment]
There was an issue with version 3.0.0.1 of the app. You can upgrade to the latest version by going to chrome:/extensions, enabling 'Developer Mode', and clicking 'Update extensions now'

**Comment by rayjezek** [comment]
I solved this by removing and re-adding the extension.
