### ISSUE TITLE
Postman proxy forwards requests to localhost but does not save them

### ISSUE THREAD

**Issue by GNUGradyn** [a85/POSTMan-Chrome-Extension#10788]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues

### Describe the Issue

When enabling the proxy in postman and intercepting a request to localhost, the request will be forwarded to localhost, but it will not be displayed in the capture.

### Steps To Reproduce

1. Click "Capture Requests" in the bottom right
2. Click "Enable Proxy"
3. Add the proxy to your web browser
4. If in firefox, go to about:config and enable network.proxy.allow_hijacking_localhost (this will proxy localhost traffic)
5. Navigate to a page on `localhost`
Notice the page loads.
6. Click "Disable proxy"
7. Navigate to a page on `localhost`
Notice the page no longer loads. This proves localhost requests are in fact going thru postman.
8. Click "Enable Proxy" again and click "Start Capture"
9. Navigate to your page on `localhost` again
Notice the page loads, but the request is not listed in postman.
10. Navigate to a normal page on the web
Notice the page loads and the request is listed in postman as expected. This proves the debug session is working.

### Environment Information

```markdown
- Operating System: Windows 10 Pro 21H2
- Platform Type: Native App
- Postman Version: Version 9.15.4
```

### Additional Context?

I'm not certain this is related, but this seems to have happened around the same time I setup postman to intercept HTTPS traffic (which does work)

**Comment by shashankawasthi88** [comment]
@GNUGradyn Thanks for raising this. The team is working on this and shall revert to the thread soon.

**Comment by shashankawasthi88** [comment]
@GNUGradyn this should be fixed now. Can you restart your app once and try the same flow. I'll close the ticket for now. Feel free to open if it does not work for you.
