### ISSUE TITLE
Cannot import OpenAPI(swagger.json) v.3.0.1 generated by .Net5 Web API

### ISSUE THREAD

**Issue by mdjorov** [a85/POSTMan-Chrome-Extension#10780]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues

### Describe the Issue

I'm trying to import JSON file generated by swagger / .net5 web api. I've tried to import it as file, as raw text and as a link. But I'm receiving an error: Format not recognized. No modifications are made in the file. 
I'm adding the json file as TXT because JSON extension is not supported for upload.
[swagger.txt](https://github.com/postmanlabs/postman-app-support/files/8332353/swagger.txt)

### Steps To Reproduce

1. Open Postman
2. Import
3. File->OpenAPI
4. Select file - swagger.json generated by the API
5. Open the file

### Environment Information

```markdown
- Operating System: Windows 10
- Platform Type: Native App
- Postman Version: 9.15.2
```

**Comment by DannyDainton** [comment]
Hey @mdjorov 

The file doesn't include a `version` so it looks like it's failing to import. 

Adding something like this to the file will allow it to be imported.

```json
{
  "openapi": "3.0.1",
  "info": {
    "version": "0.0.1",
    "title": "TouchSale Portal orders"
}
```

<img width="948" alt="image" src="https://user-images.githubusercontent.com/17089546/160170129-62ef93e8-1f18-4f38-92b8-46e10d296ec8.png">

**Comment by mdjorov** [comment]
@DannyDainton , with version added, the file was imported.
If it's possible, add more descriptive error messages what is wrong.

**Comment by BrutalBirdie** [comment]
Still an Issue.

**Comment by akshaydeo** [comment]
@mdjorov we are now looking into improving these error messages. Closing this issue for now as it solved your problem 🙂 .
@BrutalBirdie please create a new issue if you are facing any issues while importing data 🙇‍♂
