### ISSUE TITLE
Monitor doesn't work properly when inheriting authorization credentials from the collection 

### ISSUE THREAD

**Issue by areliBam** [a85/POSTMan-Chrome-Extension#10787]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues

### Describe the Issue

I have a collection with a monitor. When the credentials are set at the collection level, and the requests inherit the credentials, the requests get a 200 response, but digging into the API side, it looked like the credentials were not working. I changed this so that the credentials were directly set at the request level instead. Now when the monitor is triggered, the requests are working fine. It seems that the credentials don't actually get passed down into the requests when a monitor runs. (Granted you can ignore the response given by the API since the core issue was that the credentials weren't working rather than how the error was handled) Thought I should let you know!

### Steps To Reproduce

1. Create a Collection with some requests to hit an API
2. Set the Basic Auth that the requests will need at the collection level
3. Create a monitor linked to that collection
4. Trigger the monitor, confirm on the API that the requests did not succeed
5. Add Auth to each request individually instead, same Basic Auth credentials
6. Trigger the monitor, watch the requests succeed

### Environment Information

```markdown
- Operating System: Windows 10
- Platform Type: Postman Desktop App
- Postman Version: v9.15.4
```

**Comment by DannyDainton** [comment]
Hey @areliBam 

I'm unable to recreate this issue, the basic auth that I've set at the collection level is being used correctly. Are you able to share more details or images of the failure that you're seeing?

Is there are logging that you have showing that the value is not getting passed to your API? 

You could add something like `console.log(pm.request)` to the `Tests` section of your request to see those details in the Monitor logs.

**Comment by areliBam** [comment]
Hi @DannyDainton! 

I don't have the logging anymore from when this wasn't working but I do have some extra details. In my collection, I'm modifying the way that the requests are being called, so instead of doing so sequentially, the next request is being set depending on the data received by the monitor.

My first request is an Echo, so I can route based on the data. The next request originally inherited the credentials from the "parent" but this is where the call was failing. I could try to duplicate the collection and roll back to the broken version if you'd like, are you just wanting to see the request when this failed?

Thanks!
Areli

**Comment by DannyDainton** [comment]
Hey @areliBam 

If you can provide anything that could help us to replicate the issue that would be very helpful. Even if this is just a scaled back Collection that shows the error happening when run locally, a video of the error or any screenshot showing the failure points.

Without all that, it's very difficult for us to replicate the problem and investigate further.

**Comment by godfrzero** [comment]
Closing for now since we can't recreate the issue.
