### ISSUE TITLE
"Open file" feature (not import)

### ISSUE THREAD

**Issue by inacss** [a85/POSTMan-Chrome-Extension#1079]
Hi,
We work with PostMan (+Newman) for testing purpose on our CI server. 
We are a team, using GIT as VCS. And we found some problem modifying our collection with the actual system of "import/export" file. (we have to re-import the file each time to include new eventual development. And some of us forget that!). Why not directly work on the file (a simple open/save)?
It will be more simple for all of us.

PS: we don't want to use the "Team" feature of Postman. As a commercial enterprise, we cannot put our API test on an outside repository (some kind of security... My superior wont let me do that).

Thanks

**Comment by a85** [comment]
@inacss I understand. We'll have an on-premise version soon for the Team feature. Directly working on files has several issues that became blockers in building a collaboration product. We'll keep this thread updated in the future.

**Comment by matejar** [comment]
+1

**Comment by matejsp** [comment]
+1

**Comment by a85** [comment]
Unfortunately, we don't have plans for file based editing of data any time soon. If our roadmap changes, I'll update these issues.
