### ISSUE TITLE
gRPC : Allow Save for the requests

### ISSUE THREAD

**Issue by gh-abhicha** [a85/POSTMan-Chrome-Extension#10797]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request

### Is your feature request related to a problem?

No

### Describe the solution you'd like

Allow the ability to Save requests ( and even group them ) and share them with others.

**Comment by Alcas1** [comment]
Is this covered already by https://github.com/postmanlabs/postman-app-support/issues/10767?

**Comment by codenirvana** [comment]
@Alcas1 Yes, partially.

The ability save gRPC requests in a collection will be out very soon.
However, importing a multi-file Protobuf definition (as Postman API) is something we are actively working on and will let you know once it’s supported.

**Comment by nikitacrit** [comment]
@codenirvana any good news?

**Comment by appurva21** [comment]
Hey @nikitacrit @achaturvedi-am ! We have enabled saving gRPC requests in Collections and is available on Postman Web. We'll be rolling it out on the native app (v.9.17.0) this week as well.

**Comment by shamasis** [comment]
Hello 👋,

We have recently released the ability to save GRPC requests in collections. Simply hit the “save” button on a GRPC request and follow the collection creation through the dialog box that opens.

With this, we have also enabled support to create folders for collections with GRPC request (though some more work is left to provide folder level descriptions, etc)

On top of this, you can use the sharing features to now share links to the collections with others.
