### ISSUE TITLE
Searching for a collection shows "Couldn't find this workspace"

### ISSUE THREAD

**Issue by ankit-m** [a85/POSTMan-Chrome-Extension#10796]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

I am trying to search for a collection (particularly for Google Calendar) the public API network. However, when I search using Universal search and click on the first result, it shows an error state named "Couldn't find this workspace"

### Steps To Reproduce

1. Type in google calendar in the universal search bar
2. Click on the first search result (https://web.postman.co/workspace/undefined/collection/297806-c9fbea86-bb29-4f62-b173-97ec510668fe)
3. Behold the error state

Note the `undefined` in the URL.

<img width="810" alt="image" src="https://user-images.githubusercontent.com/9019878/160448226-ab23fdcd-3b5e-490c-a8d4-ba4f3d18a4bc.png">

### Operating System

macOS

### Postman Version

9.15.6

### Postman Platform

Postman App

### Additional Context?

I am on a free plan without a team.

**Comment by ankit-m** [comment]
Update: This collection was in "My workspace" and I had forgotten about it. I would expect Postman to switch to that workspace instead of showing an error.

**Comment by DannyDainton** [comment]
Hey @ankit-m 

Is this still an issue for you? If so, would you be able to update the steps to recreate the issue, please?

Were you in a Public Workspace at the time and then selecting the Collection that was part of your Personal Workspace?

**Comment by DannyDainton** [comment]
Closing this out for now but can look to reopen it again once more information is provided.
