### ISSUE TITLE
Inject attribute value in body post request using global environment variables, but it not work on postman 9.15.2

### ISSUE THREAD

**Issue by tkltsague** [a85/POSTMan-Chrome-Extension#10790]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues

### Describe the Issue

Inject attribut  value in body post request using global environnment variables, but it not work on postman 9.15.2

### Steps To Reproduce

Use global environnment virable to inject attribut value in request body. 
exceute the request and inspect the request body.

### Environment Information

```markdown
- Operating System: macOS Monterey 12.13
- Platform Type: Native App 
- Postman Version: 9.15.2
```

**Comment by DannyDainton** [comment]
Hey @tkltsague

Can you please provide the script that you're using to do this and some screenshots or a short video showing the issue.

**Comment by KSCooke** [comment]
@DannyDainton I believe I am having the same issue.

Essentially this auth process had been working before the latest Chrome update. Post update the environment variables being passed to the collection are being read as strings as you can see in the console at the bottom of the window. If I replace the variables with their values they work correctly. I can also hover over the variables and see that postman is seeing that each of the variables is set with the correct values.

![Postman Issue](https://user-images.githubusercontent.com/5185055/160164909-ef840d4c-8230-4081-9e5c-be943c1fef51.png)

**Comment by DannyDainton** [comment]
Hey @KSCooke 

Can you raise a separate issue please, the original posting doesn't mention many of the things that you are in terms of authorisation helpers and updated chrome versions. I don't want to mix these two just in case they are different.

When raising your issue could you please include the environment details and also the updated version of chrome that you're using, please. 🙏🏻

**Comment by KSCooke** [comment]
Sure I'll do that now.

**Comment by tkltsague** [comment]
After more investigation I saw the same variable in  collection scope with empty value. some body created it manually end forget you clean before save collection, After this there is not possible to inject value when using the same variable name  with global scope.
