### ISSUE TITLE
Only some collections are loaded

### ISSUE THREAD

**Issue by EvertonSA** [a85/POSTMan-Chrome-Extension#10791]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Collections will not load on a desktop client and canary client.

Some collections are sucessfully loaded, but there are a lot of collections missing.

it supposed to have more than 30 collections but it only show less than 10

![image](https://user-images.githubusercontent.com/30481051/160168364-4f4cb737-7fab-4527-9aa9-f4fc7714b8f9.png)

### Steps To Reproduce

Open postman (desktop or web browser) and your collections will partially load.

### Operating System

windows and linux 

### Postman Version

Postman v9.12.2-canary and  Postman v9.15.6 

### Postman Platform

Postman App

**Comment by EvertonSA** [comment]
the issue seems to be resolved. But it would be great to know if there was some instability in the backend

**Comment by postman-staff** [comment]
Hi hello,

Thank you for writing in!
We are sorry for the inconvenience that you have faced with our application.

We have received similar reports on this over the weekend and our engineering team has deployed a possible fix for the issue you had experienced.

Can you please check to see if you still encounter the reported issue?

You will need to revisit the workspace where the data (collection or environment) is located or restart/reload the web or native app.

We appreciate your patience while our team resolved the problem.
Let me know if you have any more queries or concerns.
via @Lincimary | Postman Support

**Comment by postman-staff** [comment]
Hey hi,

Just letting you know I’m still here so feel free to give me a shout if you’re still running into any issues.
via @Lincimary | Postman Support
