### ISSUE TITLE
[Incident] Something went wrong error in v9.15.7

### ISSUE THREAD

**Issue by numaanashraf** [a85/POSTMan-Chrome-Extension#10795]
We are investigating elevated reports of Postman for Desktop apps v9.15.7 intermittently crashing with 'Something went wrong' error.

We've paused the rollout of v9.15.7 version, while we investigate this further. If you are impacted by this issue, follow the steps below to revert your app to the last known stable version (v9.15.6)

1. Go to 'Help' menu
2. Click on 'Clear Cache and Reload'

Ongoing incident: https://status.postman.com/incidents/1gcxqpxtbd3v

### Steps To Reproduce

1. Open v9.15.7 app

### Operating System

Windows, macOS & Linux

### Postman Version

v9.15.7

### Postman Platform

Postman App

**Comment by olddustysocksunderthecouch** [comment]
The only way I was able to resolve this issue on mac was by:
1. deleting my existing (but broken) Postman app, 
2. downloading an older version via this link https://dl.pstmn.io/download/version/9.14.0/osx64. 
3. You may need to remove local cache if it's still not working after steps 1 and 2. [See instructions here](https://support.postman.com/hc/en-us/articles/4410785125271-How-to-remove-local-data)

The Postman Download page indicates that you're downloading version v9.15.6 but actually it's v9.15.2 which is broken.
