### ISSUE TITLE
Unable to open requests on single/double clicking on the request from a collection from the Collections Tab

### ISSUE THREAD

**Issue by beb-midigator** [a85/POSTMan-Chrome-Extension#10807]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Same issue as https://github.com/postmanlabs/postman-app-support/issues/7399

(I can't re-open this closed bug)

```
I started seeing this on Version 9.15.6 after I restored my M1 MacBook Pro from Time Machine.

I do not see any ~/Library/Application Support/Postman or /Library/Application Support/Postman and changing "Always open requests in new tab" didn't help either.
```

**Describe the bug**
Unable to open requests on single/double clicking on the request from a collection from the Collections Tab. However, if I right-click on the request and open in a new tab, then the request opens up properly.
Unable to open Examples on single/double clicking on the examples dropdown. The drop-down opens properly, however, the examples don't open.

**Expected behavior**
Single/double-clicking on any request should open up that request. Same goes for examples

### Steps To Reproduce

1. Go to Any collection
2. Click on any request
3. Nothing happens
4. Open any request with an example
5. Click on Examples dropdown from the top right corner
6. Click on a request's example, nothing happens.
7. There is no way to open up an example.

### Operating System

macOS X 12.3

### Postman Version

9.15.6

### Postman Platform

Postman App

### Additional Context?

This issue only happened after I restored my MacBook from a Time Machine backup

**Comment by giridharvc7** [comment]
Thanks for reporting this @beb-midigator . Can you clarify a couple of things for me
- Are you using Scratchpad? 
- Can you share a video of this some logs from the dev console?

**Comment by beb-midigator** [comment]
Hi @giridharvc7 , thanks for getting back to me!

I am not using scratchpad.  I don't see any logs in the dev console, but I will attach the logs I see updating from the ~/Library/Application\ Support/Postman/logs/ directory.

[main.log](https://github.com/postmanlabs/postman-app-support/files/8390970/main.log)
[renderer-requester.log](https://github.com/postmanlabs/postman-app-support/files/8390972/renderer-requester.log)
[renderer-console.log](https://github.com/postmanlabs/postman-app-support/files/8390973/renderer-console.log)
[renderer-shell.log](https://github.com/postmanlabs/postman-app-support/files/8390974/renderer-shell.log)

**Comment by beb-midigator** [comment]
I see this in 9.15.10 as well.

I tried the older version 9.15.0 and do **not** see this bug/issue

**Comment by beb-midigator** [comment]
I accidentally wiped out my 19.15.0 install and so downloaded another copy (from https://mac.filehorse.com/download-postman/21094/download/) and it is showing the same bug/issue now. Odd...

**Comment by beb-midigator** [comment]
any update on this?  My testing of sites inside our VPN is dead in the water until this is fixed. thanks

**Comment by coditva** [comment]
@beb-midigator Can you also share a screen-recording of the issue?

Would also like to know if you are able to replicate this issue on the web as well? https://go.postman.co

**Comment by beb-midigator** [comment]
@[coditva](https://github.com/coditva) 

Here is a screen capture of the Postman desktop app. I can open collections but nothing happens when I click on a request, or if I try and right-click and "open in tab"

This issue does not happen in the web-based Postman

https://user-images.githubusercontent.com/98483858/164028728-0d8fac35-0f26-4248-a36f-b1fea10e8cbd.mov

**Comment by coditva** [comment]
@beb-midigator Thanks for sending the recording and info. Can you try clearing the local storage cache and restarting the Postman app? The steps to clear the local storage cache can be found [this Postman Help Center document](https://support.postman.com/hc/en-us/articles/4410785125271-How-to-remove-local-data). Do let me know how this works out.

**Comment by beb-midigator** [comment]
that did it!!! thank you so much
