### ISSUE TITLE
Postman uses environment variable instead of collection variable

### ISSUE THREAD

**Issue by antonm1989** [a85/POSTMan-Chrome-Extension#10809]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

If there are environment and collection variables added with the same name - Postman takes environment value by default however according to documentation it should first consider collection variable as the narrowest scope.

### Steps To Reproduce

1. Add variable with the same name to environment and collection scope, for example: pm.environment.set("variable_name", "value1"); pm.collectionVariables.set("variable_name", "value2");
2. Try to use the variable in request URL, for example: GET baseUrl/{{variable_name}}
3. See that environment value1 is used however expected is collection value2

### Operating System

macOS

### Postman Version

9.15.8

### Postman Platform

Postman App

### Additional Context?

The same issue is with Postman Web and newman CLI.

**Comment by DannyDainton** [comment]
Hey @antonm1989 

The Environment Variable would be a narrower scope than the Collection Variable.

> In order from broadest to narrowest, these scopes are: global, collection, environment, data, and local.

More information can be found here:
https://learning.postman.com/docs/sending-requests/variables/#variable-scopes

![image](https://user-images.githubusercontent.com/17089546/161280555-cd4de1f1-dae3-4362-aa72-7b37a63517ed.png)

I'm going to close this issue as it's working as expected.
