### ISSUE TITLE
Couldn't get a response

### ISSUE THREAD

**Issue by SimbaNyaruwata** [a85/POSTMan-Chrome-Extension#10801]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

![Screenshot (7)](https://user-images.githubusercontent.com/47856609/160806008-60a1592d-3c50-4cb2-a9d1-8197573f5220.png)
I am running my asp.net core web api that has whatsapp bot as one of its message controller. When I try to send a message using Postman  "POST http://localhost:44381/api/Messages" with body as shown on the picture it give an error
Error: read ECONNRESET 

### Steps To Reproduce

![Screenshot (10)](https://user-images.githubusercontent.com/47856609/160807877-ab501451-7db9-4e24-bed6-dc1ccf0a7062.png)

### Screenshots or Videos

![Screenshot (8)](https://user-images.githubusercontent.com/47856609/160807234-7c5c8676-a9c4-4b65-96f7-42bb035ffbff.png)
![Screenshot (9)](https://user-images.githubusercontent.com/47856609/160807319-5bef1f07-025a-4f19-98b8-1df9c5cace44.png)
![Screenshot (10)](https://user-images.githubusercontent.com/47856609/160807465-2cfd7f85-b367-4149-84b9-527990ce68d0.png)

### Operating System

Windows 10

### Postman Version

8.9.1

### Postman Platform

Postman App

### Additional Context?

POST http://localhost:44381/api/Messages
Error: read ECONNRESET
Request Headers
Content-Type: application/json
User-Agent: PostmanRuntime/7.28.2
Accept: */*
Cache-Control: no-cache
Postman-Token: cf077517-deaa-48aa-811e-bb6db4ca5a1f
Host: localhost:44381
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
Request Body

**Comment by DannyDainton** [comment]
Hey @DeadShot263,

Are you getting the same when making a POST request from the terminal when using curl? 

You could use the code snippet generator in the right side context bar to recreate the request.

**Comment by SimbaNyaruwata** [comment]
Thanks @DannyDainton. I cleared the error it had something to do with my urls
