### ISSUE TITLE
Auto generated header out of sync with global variable. 

### ISSUE THREAD

**Issue by bascomb** [a85/POSTMan-Chrome-Extension#10810]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Value of auto-generated header not up to date with value of variable.

### Steps To Reproduce

Create a request.
Authorization Tab: add Api Key with value {{myvar}} (i.e. global variable named myvar that doesn't exist yet) 
Click create new var.
I add an "initial value" of "asdf".
Later I add a "current value" of "somethingelse".
I execute the request and it behaves unexpectedly.
I notice the auto generated header has value "asdf"
I force reloading, notice the auto generated header matches "somethingelse" and the request behaves as expected.

### Screenshots or Videos

f

### Operating System

mac os monterey

### Postman Version

9.14.14

### Postman Platform

Postman App

**Comment by DannyDainton** [comment]
Hey @bascomb 

Thanks for raising the issue.

Could you expand on the details of these steps please:

```
Later I add a "current value" of "somethingelse". - How are you adding this? With a script or manually? Is the initial value of asdf still set?
I execute the request and it behaves unexpectedly. - Not sure what _unexpectedly_ means?
I notice the auto-generated header has value "asdf" - Di you nothing this in the request headers? The Postman Console?
I force reloading, notice the auto generated header matches "somethingelse" and the request behaves as expected. - Not sure what you mean by _force reloading_? Did you Persist All?
```

It would really help us if you could share screenshots or a short video so that we can reproduce the issue you're facing.

**Comment by DannyDainton** [comment]
Hey @bascomb 

I'm closing this out due to inactivity, if more details and clear reproducible steps are provided we can look at opening this again.
