### ISSUE TITLE
Environment files being overwrote every few hours with an old version

### ISSUE THREAD

**Issue by jmatthews79** [a85/POSTMan-Chrome-Extension#10813]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

We have several environment files we use and for the last month the environment files keep getting overwritten with an old version of the file. Postman support stopped responding to emails. This is not the first time this has happened to our organization. It is causing our pipelines to fail as vars keep getting deleted. 

This morning I had to re-add the same vars 3 times within 4 hours. 

### Steps To Reproduce

1. Open env file
2. Add new var
3. Within an hour they will be overwritten
4. Sync is on

### Operating System

MacOS

### Postman Version

Version 9.14.14

### Postman Platform

Postman App

### Additional Context?

Using both web and native app

**Comment by giridharvc7** [comment]
@jmatthews79 Thank you for reporting this here and sorry that you are facing this trouble. Here is what can help us debug this issue further. 
- Please ensure you have the latest version of Postman, I believe this is 9.15.2+ 
- Send us a recording and console logs from the developer console if possible so that we can understand what is happening.

**Comment by jmatthews79** [comment]
@giridharvc7 

I am using **Postman Native**:
- Desktop Platform Version 9.15.2
- Mac Version Version 9.15.10

and **Postman Web**:
- Version 9.15.11-220329-1125
- Chrome 99 / Mac OS 10.15.7

There is nothing in console logs except things like:
`Error: getaddrinfo ENOTFOUND {{clientreportschedulerbaseurl}}` because the vars from the environment file are disappearing.  I won't be able to get a video of it because it happens over a few hour period. I add vars to environment file then they disappear some time later. 

Here is a link to a video of how I add my vars to the environment file. Sync is active. https://recordit.co/rA1OaaOVhx

**Comment by jmatthews79** [comment]
@giridharvc7

This has happened 5 times in the last hour.

**Comment by xk0der** [comment]
Hi @jmatthews79 While our engineering team investigates this, I want to apologies for the bad support-experience you had with Postman support. 

I want to review the support ticket you have with us but unfortunately, I was unable to track your support-request internally. 

Please do provide the Ticket ID from your interaction with us. 

Thank you!

**Comment by jmatthews79** [comment]
Hi @xk0der the request was 100913. It looks like there may be a fix in the works as of yesterday.

**Comment by apoorvgupta03** [comment]
Hey @jmatthews79 , I think this must've been fixed, can you confirm once?

**Comment by jmatthews79** [comment]
@apoorvgupta03 yes this seems to have been fixed. thank you!

**Comment by apoorvgupta03** [comment]
thanks for the confirmation :)
