### ISSUE TITLE
Setting environment variables from pretty print JSON responses no longer works

### ISSUE THREAD

**Issue by Xlator** [a85/POSTMan-Chrome-Extension#1081]
In the previous version, I could select a value in the pretty JSON response from a request, right click, "Set: environment" -> "variable". In the latest version, this no longer seems to work. When I check the environment in the manager the variable I attempted to set is blank. It still works if I do it from the "raw" or "preview" tabs, but finding the correct value can be difficult in large result sets.

**Comment by abhijitkane** [comment]
This has been fixed in version 3.0.0.5 of the app. You can update it by going to chrome:/extensions, checking 'Developer Mode', and clicking 'Update extensions now'

**Comment by Xlator** [comment]
My thanks!
