### ISSUE TITLE
gRPC server reflection error - no such type: .google.protobuf.Empty

### ISSUE THREAD

**Issue by toddlindner** [a85/POSTMan-Chrome-Extension#10815]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

When utilizing gRPC server reflection, it usually works, but one server is giving an error and the details links shows one error:

no such type: .google.protobuf.Empty

### Steps To Reproduce

1. Open a new request tab
2. Click New
3. Enter server uri and port
4. Click Use Server Reflection

### Operating System

Windows 10

### Postman Version

9.15.10

### Postman Platform

Postman App

**Comment by sohenk** [comment]
same problem

**Comment by appurva21** [comment]
Hey @toddlindner @sohenk ! 

Looks like there is an incorrect import in the concerned Protobuf. Could you try replacing `"google/protobuf/Empty.proto"` with `"google/protobuf/empty.proto"` and see if that fixes the issue?

**Comment by toddlindner** [comment]
@appurva21 - Thanks.  I actually cant reproduce the issue anymore after upgrading to 9.18.2.  So, good news?
