### ISSUE TITLE
Import from Gitlab

### ISSUE THREAD

**Issue by petkostas** [a85/POSTMan-Chrome-Extension#10811]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request

### Is your feature request related to a problem?

Currently in order to import Gitlab hosted API schemas you can only do it manually, after that you can connect your repository to the schema.
It is a bit weird not being able to import but being able to connect to a Gitlab repository to sync your schema and collection.

![image](https://user-images.githubusercontent.com/3758537/161263929-f1a248c0-8b6d-4a13-acab-48c5246c1ea7.png)

### Describe the solution you'd like

Add support for importing existing schemas from Gitlab repositories.
![image](https://user-images.githubusercontent.com/3758537/161264392-cb6c5005-1a32-4962-a2cb-a775f39c12e7.png)

**Comment by shashankawasthi88** [comment]
@petkostas the connect to repository flow shall also allow you to import the API schema within Postman. After connecting to the repository, the subsequent PULL from the repo will allow you to mark your schema file in the repository.

**Comment by petkostas** [comment]
@shashankawasthi88 

> @petkostas the connect to repository flow shall also allow you to import the API schema within Postman. After connecting to the repository, the subsequent PULL from the repo will allow you to mark your schema file in the repository.

are you referring to an upcoming change? as I see only the ability to connect to the repository after I have created or imported a Schema file.

**Comment by petkostas** [comment]
I can confirm that what you describe indeed works but feels a bit hidden and weird (due to the fact that there is a button there for the other Git repositories).
You can close this ticket if you feel it doesn't add currently any value.

**Comment by shashankawasthi88** [comment]
@petkostas we understand that this is not the most optimal behavior. Will keep the ticket open as we optimize this flow, and post on the thread if we have updates.

**Comment by shashankawasthi88** [comment]
@petkostas the import from GitLab cloud has been added to the product.
