### ISSUE TITLE
New Integration Request - <product name>

### ISSUE THREAD

**Issue by gembalisridharinn** [a85/POSTMan-Chrome-Extension#10826]
### Describe your current workflow

I am trying to connect my Innovapost bitbucket repo

### Describe your ideal workflow

Push collections to git

### Describe alternatives you've considered

no alternative at present

**Comment by abhijitkane** [comment]
@gembalisridharinn Have you tried out our integration with Git (GitHub, Bitbucket, Azure, GitLab are supported) - https://learning.postman.com/docs/integrations/available-integrations/github/#api-sync-with-github? Feel free to reopen in case you find your use-case unaddressed, or post on our community (https://community.postman.com/).
