### ISSUE TITLE
API Documentation fills in with random values from an OpenApi definition

### ISSUE THREAD

**Issue by Jakar510** [a85/POSTMan-Chrome-Extension#10829]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

When generating a collection from an OpenApi definition, it fills in with random values.

- Strings are usually populated with random Latin phrases (according to google translate)
- Numbers (integers, doubles, floats) are random values
- Dates are random

An example is below:

	{
		"String1": "cillum ut",
		"String2": "sed ipsum elit exercitation eiusmod",
		"Enum": 0,
		"Integer": -37653805,
		"Float": -28322226.311210708,
		"Double": 607788.993085937,
		"Bool": false,
		"Date": "1963-03-20T09:55:39.852Z"
	}

Is there a way to change this behavior? Such as setting it to the default values (empty string, zero for numbers, etc).

### Steps To Reproduce

1. Create an OpenApi definition and add it to an Api
2. create documentation collection
3. go to any request and look the default sample json.

### Operating System

Windows

### Postman Version

9.15.8

### Postman Platform

Postman App

**Comment by DannyDainton** [comment]
Hey @Jakar510 

This seems similar to something previously raised, more information can be found here https://github.com/postmanlabs/postman-app-support/issues/9866#issuecomment-826515949
