### ISSUE TITLE
Postman Packaged App 3.0.05 crashes Chrome 43.0.2357.81

### ISSUE THREAD

**Issue by chantelope** [a85/POSTMan-Chrome-Extension#1082]
I was using an older version of the packaged app until the last hour, this was frequently crashing so I updated to the latest version. The app will open and then crash chrome within a minute

Using on a Windows 7 machine

**Comment by abhijitkane** [comment]
@chantelope were you signed in to the Sync service in the older version?

Also, can you try restarting Chrome? None of the other users on this version are reporting problems.

**Comment by chantelope** [comment]
Yes I was, I have restarted several times with the same issue recurring

**Comment by chantelope** [comment]
I have uninstalled/reinstalled, seems to have resolved the issue
