### ISSUE TITLE
There was an error importing this collection. Please try again

### ISSUE THREAD

**Issue by WalterDias** [a85/POSTMan-Chrome-Extension#10825]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

I'm not able to import the https://documenter.getpostman.com/view/2669002/SWE84xMd API to the postman.

### Steps To Reproduce

Access https://documenter.getpostman.com/view/2669002/SWE84xMd
Click on the Run in Postman
Import to an Collection
Error occur

### Operating System

Windows

### Postman Version

9.15.10

### Postman Platform

Other

### Additional Context?

Ocours in all platforms

**Comment by VaishnaviChallaPostman** [comment]
Hey @WalterDias 
It looks like there is an issue with the environment attached to the documentation. 
Could you please try to import it with [this](https://go.postman.co/network/import?collection=2669002-e4c270d4-afa1-4116-8285-23f6c16d5c9d-SWE84xMd) link? [This link imports the collection without the environment]

**Comment by akshaydeo** [comment]
@WalterDias, Could you check if import works for you with the fix @VaishnaviChallaPostman suggested? 🙇 

> I will close the issue for now; if you think it still doesn't solve the issue, feel free to re-open it 🙇
