### ISSUE TITLE
New Integration Request - CodeFresh

### ISSUE THREAD

**Issue by shraddhakul** [a85/POSTMan-Chrome-Extension#10827]
### Describe your current workflow

Our company currently uses CodeFresh to handle all build and deployment tasks. We need to integrate our postman automation framework to CodeFresh CI/CD.

### Describe your ideal workflow

For every build - we would like to hook up our framework with CodeFresh so we can trigger our tests with each build -

**Comment by shashankawasthi88** [comment]
@shraddhakul thanks for raising the request. Can you elaborate more on the workflows? What exactly do you mean when you say 'hook up'. Postman tests can be run in your pipeline using [Newman](https://www.npmjs.com/package/newman).

**Comment by shraddhakul** [comment]
I see, no problem. I am relatively new to Postman. Our objective is to
trigger our postman automated scripts through CI/CD builds. I noticed on
https://learning.postman.com/docs/integrations/ci-integrations/ - there are
elaborated steps for Circle CI and Travis. Our company uses Code Fresh for
builds and deployments. Was checking to see if this is feasible with
CodeFresh?

**Comment by shashankawasthi88** [comment]
@shraddhakul - yes it should be possible using Newman CLI - https://learning.postman.com/docs/running-collections/using-newman-cli/command-line-integration-with-newman/
