### ISSUE TITLE
Unable to access workspace after changing visibility from Public to Team

### ISSUE THREAD

**Issue by cyrielle-hada** [a85/POSTMan-Chrome-Extension#10839]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

**Issue created by Postman**

After changing the visibility of a workspace from Public to Team, I don't have access to my workspace
![cant access my workspace](https://user-images.githubusercontent.com/47351631/162912231-32606a58-16a2-422a-acdd-6d38c48291da.png)

There is a known issue where public workspaces created under an individual account before joining a Postman team don't get properly converted into a team workspace, which then causes a failure if you try to switch the visibility to your workspace from "Public" to "Team". 

If you experience this issue, [submit a support request](https://support.postman.com/hc/en-us/requests/new/) to get unblocked. 

### Steps To Reproduce

1. Create a Public workspace under a single Postman account
2. Join a Postman team
3. Update visibility from Public to Team. 
4. Try to access workspace and see the error "Couldn't access this workspace"

### Operating System

Any 

### Postman Version

9.15.12

### Postman Platform

Postman App

### Additional Context?

Issue created by Product Support

**Comment by akshay-kulkarni-03** [comment]
@claireriley would you be able to share a video or something about the issue you have been facing? This will help us triage this faster.

**Comment by claireriley** [comment]
@akshay-kulkarni-03 @cyrielle-hada wrong C name 😄

**Comment by akshay-kulkarni-03** [comment]
@cyrielle-hada would you be able to share a video or something about the issue you have been facing? This will help us triage this faster.

**Comment by akshay-kulkarni-03** [comment]
@cyrielle-hada closing this issue, feel to re-open if you face any problem!
