### ISSUE TITLE
Set environment variable from right-click menu clears the variable

### ISSUE THREAD

**Issue by jblankfeld** [a85/POSTMan-Chrome-Extension#1083]
Hi,
I'm using Postman 3.0.0.2 and I can not set environment variables (or global variables) from the right-click contextual menu.
Instead, it clears it with an empty value.

Is it just me having the issue ?

**Comment by abhijitkane** [comment]
This has been fixed in version 3.0.0.5 of the app. You can update it by going to chrome:/extensions, checking 'Developer Mode', and clicking 'Update extensions now'

**Comment by DarthOpto** [comment]
I am having this problem in 4.0.1

**Comment by abhijitkane** [comment]
@DarthOpto this was a regression in our 4.0.1 release. We've fixed this internally, and will be rolling out the fix to users by tomorrow.

**Comment by DarthOpto** [comment]
@abhijitkane Thank you very much got on this morning and everything was working again. Thank you so very much.
