### ISSUE TITLE
Incorrect interface placement if Windows taskbar resides on top.

### ISSUE THREAD

**Issue by owk444** [a85/POSTMan-Chrome-Extension#10834]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Hello

May be I'm little strange man, but I prefer to place a Windows (10) taskbar on the top of the screen.

When the Postman starts, it always opened under taskbar every time, and some menus are hidden by taskbar. To resolve this issue I must to move the taskbar down the desktop, maximise Postman window, and move the taskbar back. Every day, every time. 

The Postman after closing don't remember a window position in windowed mode, and not remember if closed in maximized mode. 

This issue sometime exists in the other apps, like Chrome, and can be fixed by next actions:
1. Move the taskbar to down.
2. Move the app window to down.
3. Close the app window.
4. Move the taskbar to up back.
5. Open an app again. It started in the position, remembered in the moment of closing app.
6. If an app closed in maximized mode, it re-opens in maximized mode again.

But not Postman.

Please correct this issue.

Thank you

### Steps To Reproduce

1. Place Windows 10 taskbar to top.
2. Open the Postman.
3. Look at result.

### Screenshots or Videos

<img width="1753" alt="image" src="https://user-images.githubusercontent.com/25277652/162618119-256c19ae-2fa3-4e30-b35a-bd21a66e0f55.png">

### Operating System

Windows 10

### Postman Version

9.15.10

### Postman Platform

Postman App

**Comment by jviotti** [comment]
Thanks a lot for reporting this @owk444 !

Do you see similar behavior from other Windows apps, or just Postman? If so, how do other apps behave (for reference)?

**Comment by dsanders11** [comment]
This should be fixed in Postman version v9.16.0 and newer, so I'm closing this. If you're still seeing the issue on the latest version of Postman, leave a comment and feel free to ping me, thanks!

**Comment by owk444** [comment]
> This should be fixed in Postman version v9.16.0 and newer, so I'm closing this. If you're still seeing the issue on the latest version of Postman, leave a comment and feel free to ping me, thanks!

Yes, it fixed, the Postman save correct position in both modes, windowed and maximized. All works fine, thank you!
