### ISSUE TITLE
Broken After Upgrade

### ISSUE THREAD

**Issue by duepayer** [a85/POSTMan-Chrome-Extension#1084]
So, I just tried opening the app after not using it to find that it had been automatically updated. Unfortunately the upgrade didn't go well because I can't login nor access any of my collections. Really need some help fixing this so I can finish some work. Disappointed in you guys. Please help ASAP!

![bad-postman-upgrade](https://cloud.githubusercontent.com/assets/412227/7869939/a1329dae-053a-11e5-9b7c-5c291f34f68c.PNG)

**Comment by a85** [comment]
@duepayer We pushed an update several hours ago. Can you force an update by going to chrome://extensions?

**Comment by a85** [comment]
The version number should be 3.0.0.5

**Comment by duepayer** [comment]
That worked. Thanks!
