### ISSUE TITLE
New Integration Request - Vehicle Function Access V1 - Collection

### ISSUE THREAD

**Issue by shorooqhasan** [a85/POSTMan-Chrome-Extension#10843]
### Describe your current workflow

TBD

### Describe your ideal workflow

TBD

**Comment by shashankawasthi88** [comment]
@shorooqhasan Can you expand on what exactly are the expectations from this integration? Filling out the template will help us design the integration better.

**Comment by shashankawasthi88** [comment]
@shorooqhasan Closing this for now. Feel free to open with more details.
