### ISSUE TITLE
Allow for Public Workspaces Even if a Team You Are a Part of Isn't Public

### ISSUE THREAD

**Issue by Julian88Tex** [a85/POSTMan-Chrome-Extension#10845]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request

### Is your feature request related to a problem?

When you have Public workspaces and then join a team and the team doesn't have a public profile, your Public workspaces switch to personal and cannot be switched back to Public. This is an issue if you are part of other projects that need to remain public, but you'd also like to be on a team that does not wish to have a Public profile.

### Describe the solution you'd like

Separate any association or dependencies on team settings from other unrelated workspaces that are not part of the team.

### Describe alternatives you've considered

I suspect #7150 may fix this issue depending on how it is implemented.

### Additional context

- I've written into support and confirmed this is not possible.

**Comment by ramji367** [comment]
Hey @Julian88Tex, I am a Product Manager from Postman working on https://github.com/postmanlabs/postman-app-support/issues/7150. I would like to understand your use case better since it is unique. 

Would you be open to a quick zoom call to discuss? You can use [this link](https://calendly.com/ramji-postman/30min) to select a time that works best for you.

**Comment by Julian88Tex** [comment]
> Hey @Julian88Tex, I am a Product Manager from Postman working on https://github.com/postmanlabs/postman-app-support/issues/7150. I would like to understand your use case better since it is unique. 
> 
> 
> 
> Would you be open to a quick zoom call to discuss? You can use [this link](https://calendly.com/ramji-postman/30min) to select a time that works best for you. 

Would be happy to :) just signed up.

**Comment by Julian88Tex** [comment]
> Hey @Julian88Tex, I am a Product Manager from Postman working on #7150. I would like to understand your use case better since it is unique.
> 
> Would you be open to a quick zoom call to discuss? You can use [this link](https://calendly.com/ramji-postman/30min) to select a time that works best for you.

Hey, on our zoom call now. Let me know if this time no longer works for you. I just emailed you so feel free to respond there. Thanks!

**Comment by akshay-kulkarni-03** [comment]
Hi @Julian88Tex , when you have a public workspace associated with a team in order for other users to know which team this workspace belongs, the team needs to have public profile so our users can validate the authenticity of the APIs.

**Comment by Julian88Tex** [comment]
@akshay-kulkarni-03 this is regards to workspaces that are not associated with a Team but rather your own. This issue came up because I had workspaces on my account not associated with any team but when I joined a new company and added my user to that Team, my non-related public workspaces became private. This created disruption to a project I was working on that was open source and was relying on one of my workspaces.
