### ISSUE TITLE
Map Team URL to SSO Login Page

### ISSUE THREAD

**Issue by nasco-a** [a85/POSTMan-Chrome-Extension#10840]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request

### Is your feature request related to a problem?

Whenever we are signing in via SSO we always have to type in the full domain name of the team, and this might be a time-consuming task, especially with bigger domain names.

E.g if I navigate to the SSO login page I would have to fill in my domain in order to proceed with the sign-in.

### Describe the solution you'd like

Navigating directly to the team URL for example myexampledomain.postman.co would ideally take me to a login page for that specific team, so I can proceed directly with the SSO sign-in.

### Describe alternatives you've considered

An alternative option might be to have the domain prefilled in the domain field if the sign-in is triggered by navigating to the team's URL.

### Additional context

This feature is being tracked internally - submitted by support for public tracking

**Comment by ArjunSingh-PM** [comment]
@nasco-a: While we work to improve this flow further, teams can use the following URL to navigate directly to the team's auth page which includes the SSO option.

https://identity.getpostman.com/enterprise/login/authchooser?team=<TEAM_DOMAIN>

**Comment by Nierae01** [comment]
We managed to implement SSO. But during our tests we found out that we have to specify the Team domain every time after we closed (or after 30 days) the application. Can't this be bypassed?

**Comment by ArjunSingh-PM** [comment]
Any URL of the form https://<TEAM_DOMAIN>.postman.co/*, will lead to the authentication page for that team directly. 

For example,  the URL https://postman.postman.co/ opens the authentication page for the Postman team
