### ISSUE TITLE
No minimize,Restore,Move,Close buttons

### ISSUE THREAD

**Issue by qasimhoosain321** [a85/POSTMan-Chrome-Extension#10846]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Cannot see the minimize,Restore,Move,Close buttons on Postman v9.15.13 on Windows 10. Unable to move the window from my laptop screen to my monitor either

![image](https://user-images.githubusercontent.com/103636024/163356971-c5db8d9d-edfa-4979-8d85-f50e463b7e17.png)

### Steps To Reproduce

1.Open Postman

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/103636024/163357010-e0c44dc3-8890-4cb4-86e5-65dc5e6d4da0.png)

### Operating System

Windows 10

### Postman Version

9.15.13

### Postman Platform

Postman App

**Comment by jviotti** [comment]
Hey @qasimhoosain321 , thanks for reporting. Closing this as a duplicate of https://github.com/postmanlabs/postman-app-support/issues/10834.
