### ISSUE TITLE
Provide a way to show a list of currently opened tabs and be able to jump to one.

### ISSUE THREAD

**Issue by brenthale** [a85/POSTMan-Chrome-Extension#10842]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request

### Is your feature request related to a problem?

I often have 10+ tabs open and it is very difficult to bounce back and forth between tabs that I know are already up.  I'm looking for a way to help me navigate my open tabs.

### Describe the solution you'd like

I would like to right-click on any tab and see a pull-right option called "Currently Open Tabs" which would be similar to "Recently Closed Tabs" when you select the 3 dots to the right of the '+" button on the tab row.   The pull-right would be wide enough to show a good chunk of the title of each tab.   Selecting one would jump you directly to that tab and bring that tab into view on the tab bar.

### Describe alternatives you've considered

Add another menu item titled "Currently Open Tabs" directly under "Recently Closed Tabs" when you select the 3 dots to the right of the '+" button on the tab row.   The pull-right would be wide enough to show a good chunk of the title of each tab.   Selecting one would jump you directly to that tab and bring that tab into view on the tab bar.

**Comment by savbran** [comment]
No further news on this feature? Still no list of currently opened tabs? This is very important. Thanks in advance for the attention.

**Comment by jgraaf33** [comment]
this would be really useful to have! please implement this. What would also be helpful already is a scrollbar to navigate through the tabs more quickly than having to click the arrow

**Comment by navigiljshuusko** [comment]
Please check **Chrome Search tabs** for a good reference how this could be done.

**Comment by aoyama-val** [comment]
One of the causes of the inconvenience is that only a few characters are displayed as tab name when there are many tabs open.
It might be good if we could either of

- set the minimum width of the tab 
- display tabs in multiple rows
- display open tabs in sidebar just like VSCode Explorer's `OPEN EDITOR` and project files.

**Comment by martinezFisi** [comment]
> One of the causes of the inconvenience is that only a few characters are displayed as tab name when there are many tabs open. It might be good if we could either of
> 
> * set the minimum width of the tab
> * display tabs in multiple rows
> * display open tabs in sidebar just like VSCode Explorer's `OPEN EDITOR` and project files.

"display tabs in multiple rows" would be perfect for me, I work in that manner at Intellij

**Comment by chris-torruella** [comment]
Hey everyone, exciting news! ⭐
We've just introduced **Tab Search**, a new step in our journey to improve tabs UX and management at Postman. Now, you can easily read the entire name of all your opened tabs, regardless of their number.

**What's New:**
1. Dropdown display with all of your tabs.
2. Recently closed section for easy recovery.
3. Search bar for quick tab access.
4. Moved "Close all tabs" options to right-click tab menu to gain more tab bar space.

![demo](https://github.com/postmanlabs/postman-app-support/assets/120389184/d9c85ca4-ada9-4660-90e3-8b0ee33f0251)

Give it a try and let us know what you think. Your feedback is key to help us taking Postman to the next level! 🚀
