### ISSUE TITLE
Environment tab goes into a conflict state on the desktop app

### ISSUE THREAD

**Issue by malvikach** [a85/POSTMan-Chrome-Extension#10841]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

The environment goes into a conflict state in the desktop app versions 9.15 and 9.16. 

### Steps To Reproduce

1. Open an environment
2. Edit and save the environment
3. Close the app without quitting it. 
4. Open the app again
5. The environment tab is in a conflict state

### Screenshots or Videos

https://user-images.githubusercontent.com/17089546/162952001-d95222c0-06b1-468d-a858-c867335162ef.mp4

### Operating System

Mac/Windows/Linux (not tested for windows and linux)

### Postman Version

9.15 and 9.16

### Postman Platform

Postman App

**Comment by vedkribhu** [comment]
Fix is out for this with v9.15.13
