### ISSUE TITLE
Cookies won't save

### ISSUE THREAD

**Issue by DeviNoles** [a85/POSTMan-Chrome-Extension#10847]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Whenever I add a new cookie it won't save.

### Steps To Reproduce

1. Make new request
2. Add cookie
3. Save cookie

### Operating System

Windows

### Postman Version

9.15.13

### Postman Platform

Postman App

### Additional Context?

Tried on Postman App and Postman Web. Also had my coworker try and he was able to replicate it.

**Comment by DannyDainton** [comment]
Hey @DeviNoles 

Can you provide a short recording of this behaviour in the latest version of the platform? 

It's going to be difficult to replicate this issue, given the information and steps to reproduce that you have provided.

**Comment by DannyDainton** [comment]
Closing this due to lack of context and information. A short recording of the problem or a more complete set of reproduction steps will help us to investigate the issue you're facing, without those it's difficult to progress anything here.
