### ISSUE TITLE
Issue with OAuth 2.0 and ADFS vNext

### ISSUE THREAD

**Issue by rbrayb** [a85/POSTMan-Chrome-Extension#1085]
Using the OAuth2 functionality with ADFS vNEXT (running in an Azure VM) which supports OAuth2,

When I try and "Get Access Token", get error:

URL is: 

https://www.getpostman.com/oauth2/start?authorization_url=https://xxx.cloudapp.net/adfs/oauth2/authorize&access_token_url=https://xxx.cloudapp.net/adfs/oauth2/token&client_id=yyy&client_secret=&scope=profile openid&app_id=fhbjgbiflinjbdggehcddcbncdddomop

When I click on URL, get 500 error - URL is:

https://www.getpostman.com/oauth2/callback?code=X6DNW17LDk2xyikelvZsOg.jcFeIKVn0ggkADx_JzbmjNymJXo......RL7t7QepLO1id7i4MavC3VK47Od3foTHNRCehe9l71PikNKRQIl60kdkdijy-8HJ6PAQ6NEbAZemXekQDitBmOrtmFr_w0R145a8un36ReB6PDDD3kYI56G1EJSj7SvMvHPGdDr9TRNTpSd7hasjeRPPjGDo--JAIDwqGOGx6r8q9Dj3-n9Gvpw&state=447206

**Comment by rbrayb** [comment]
Update - played around with the scope. Works best if no scope but still same problem. If I add a scope e.g. email then get an ADFS error message:

The client 'xxx' is forbidden to access the resource 'urn:microsoft:userinfo' with scope 'email'.

Where does that urn come from?

**Comment by a85** [comment]
Not sure. A lot of these errors depend on the backend implementation and OAuth 2.0 is notoriously different across different implementations.

**Comment by rbrayb** [comment]
Checked that no proxies were involved. Now I get a blank pop-up window - you can see it in the image - close button arrowed. When I close the window, get error as above.
![screen shot 05-29-15 at 11 07 am](https://cloud.githubusercontent.com/assets/5341999/7873200/3e1aa66c-05f3-11e5-857a-179dae1985a9.PNG)

**Comment by rbrayb** [comment]
I wonder - could that pop-up be the "Confirm permissions / Consent"?

**Comment by a85** [comment]
No. That's the OAuth login flow pop up. Something is going wrong between the flow between Postman's server and the authentication server. Usually that's due to a different set of values being sent by the authentication server.

**Comment by rbrayb** [comment]
Agreed – it you  want I can give you a login to that VM and you could trace the messages yourself?

Happy to help and now that ADFS (which is the basis for Microsoft federation) supports these protocols more people are going to try this.

Thanks,

**Comment by abhijitkane** [comment]
@rbrayb Sure, that'd be great. Happy to help.

**Comment by rbrayb** [comment]
Cool - could you please contact me privately at my Github handle AT g m a i l.

I will set it up and send credentials next week.

Thanks,

**Comment by RonakThakkar** [comment]
Did that blank pop-up problem solved? I have the same issue.

**Comment by abhijitkane** [comment]
@RonakThakkar What Postman version are you using?

**Comment by RonakThakkar** [comment]
I solve the issue. Problem was that I need to specify ?resource=<resourceurl> after Authorize URL and if not specified this windows open and shows nothing. Fortunately after closing the windows, it give me debug URL where i could find the error.
