### ISSUE TITLE
OpenAPI 3.0 is not importing oauth2 configuration

### ISSUE THREAD

**Issue by cblavier** [a85/POSTMan-Chrome-Extension#10854]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

When importing an API describing an oauth2 security flow (of type `clientCredentials` with empty scopes and a `tokenUrl`) the api authorization is not configured properly in Postman.

### Steps To Reproduce

Import following file as an openapi JSON:

```json
{
  "components": {
    "responses": {},
    "schemas": {},
    "securitySchemes": {
      "oauth2": {
        "flows": {
          "clientCredentials": {
            "scopes": {},
            "tokenUrl": "https://myserver.com/oauth2/token"
          }
        },
        "type": "oauth2"
      }
    }
  },
  "info": { "title": "API", "version": "0.2" },
  "openapi": "3.0.0",
  "paths": {},
  "security": [{ "oauth2": [] }],
  "servers": [{ "url": "https://myserver.com", "variables": {} }],
  "tags": []
}
``` 

### Operating System

MacOS

### Postman Version

9.15.11

### Postman Platform

Postman App

**Comment by SahilChoudhary22** [comment]
Hi @cblavier 

Can you share a screenshot or video showing the configuration you're getting and the expected behaviour?

**Comment by cblavier** [comment]
Hey @SahilChoudhary22 

Here is what happens when I import my spec:
[https://share.cleanshot.com/OrGUM1](https://share.cleanshot.com/OrGUM1)

And here is what it is supposed to look like (with grant type & access token url correctly filled in)
[https://share.cleanshot.com/hXZna5](https://share.cleanshot.com/hXZna5)

Best,
Christian

**Comment by SahilChoudhary22** [comment]
Hey again @cblavier ,

I've identified the problem and we'll be working on a fix for it. You'll be kept in the loop regarding future updates on the issue and will be informed when the issue gets fixed 👍.

**Comment by andreideznan** [comment]
Hello Postman team,
Is there a timeframe by when do we expect a fix?

**Comment by SahilChoudhary22** [comment]
> Hello Postman team, Is there a timeframe by when do we expect a fix?

Hi @andreideznan, actually there was reprioritisation of tasks due to some imminent releases, because of which some bug fixes had to be postponed beyond our control. But now we're back on this issue and you can expect to see it in production within the next few weeks. Stay tuned!

cc : @cblavier

**Comment by andreideznan** [comment]
Hi guys,
Many thanks. It works as it should.
