### ISSUE TITLE
Main window is blank after fresh install

### ISSUE THREAD

**Issue by z0d1ac-RU** [a85/POSTMan-Chrome-Extension#10851]
### Is there an existing issue for this?

- [x] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Hi!

After fresh install Postman looks like this:
![image](https://user-images.githubusercontent.com/15731594/163854053-832dc21b-36aa-4966-8aaf-3bd1c5b200dc.png)

Updating and disabling hw acceleration do nothing, logs are fine.
But, my user name is "r2$om1an#" and it seems to be the issue, take a look:
![image](https://user-images.githubusercontent.com/15731594/163854354-dee4800b-065b-4430-8879-8440428182f9.png)

Thanks!

### Steps To Reproduce

0. Windows Server 2012 R2, 16GB RAM, App is 9.15.2, Username ends on "#" ("r2$om1an#" in my case)
1. Perform fresh install of Postman (9.15.2 now)
2. Launch app

### Operating System

Windows Server 2012 R2

### Postman Version

9.15.2

### Postman Platform

Postman App

**Comment by paulius-miksys** [comment]
I have the same issue on MAC. Postman version 9.15.2

**Comment by jviotti** [comment]
Thanks for the report. We'll be looking into this soon. @paulius-miksys what is your OS username? Does it have non-alphanumeric characters too?

**Comment by bavulapati** [comment]
This should now be fixed with the latest update. Please update your app and feel free to open this issue in case you still see it.

**Comment by z0d1ac-RU** [comment]
Site states that latest version is 9.18.2, however version 9.16.0 is being downloaded from https://dl.pstmn.io/download/latest/win64
Hence can't verify that issue is being fixed or not :(

**Comment by bavulapati** [comment]
@z0d1ac-RU We have fixed the issue where the version reflected on the release notes and the artefact downloaded was different. 
Can you please take another look.? The latest on the website should have the fix. Please update your app and feel free to open this issue in case you still see it.
