### ISSUE TITLE
Cannot share a collection from a team workspace with a personal workspace

### ISSUE THREAD

**Issue by ian-weir** [a85/POSTMan-Chrome-Extension#10857]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

When trying to "share" a collection from a team workspace with a personal workspace, the personal workspaces are disabled. I should be able to share the collection so I can work on it individually without affecting other teammate
![Screen Shot 2022-04-20 at 2 11 42 PM](https://user-images.githubusercontent.com/14279981/164314704-58e52dab-1848-4b56-adc5-78db163f629f.png)

### Steps To Reproduce

1. Create a collection in a team workspace
2. Click on the collection and hit 'Share'
3. Select 'Move collection' at the bottom of the modal
4. Personal workspaces are disabled

### Operating System

MacOS

### Postman Version

9.15.11

### Postman Platform

Postman App

### Additional Context?

The reason I'm doing this is this was the suggestion on this old Question: https://github.com/postmanlabs/postman-app-support/issues/7498#issuecomment-552106374

but the workaround suggestion no longer works. If there is a way to share collections but maintain separate environments (so teams aren't clobbering each others env variables) then that would also be great. Thanks in advance!

**Comment by DannyDainton** [comment]
Hey @ian-weir 

This is by design, you cannot move elements from a Team Workspace to a Personal Workspace. 

You can `fork` the Collection or Environment into a Personal Workspace and have your own version of it.

https://learning.postman.com/docs/collaborating-in-postman/version-control/#forking-postman-entities

**Comment by ian-weir** [comment]
@DannyDainton 

This feels like a weird solution to me. Forking it will mean I would have to refork to get any changes to the shared collection? Basically the use case is I want to share the collection with my team but not the environment because we all have our own local deploys and AWS environments. So if I fork it I get that but my collection could get stale. If I work in the shared collection we clobber each other because the environments are shared. Is there something I'm missing because neither of these sound like particularly great solutions.

**Comment by arlemi** [comment]
@ian-weir You wouldn't have to fork the collection every time, you can pull changes from the parent collection whenever you want to work with it. https://learning.postman.com/docs/collaborating-in-postman/version-control/#pulling-updates

This enables everyone in your team to work on their own version of the parent collection, while being able to either pull changes or create pull request back to the parent collection when needed. The previous Share functionality would keep all collections in sync and sometimes create conflicts with several people working on the same collection.
