### ISSUE TITLE
Environment parameter is not updated when using Flow

### ISSUE THREAD

**Issue by sad-frog** [a85/POSTMan-Chrome-Extension#10850]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

I have tried to use Flow functionality to emulate User-scenario. I have passed the environment variable through the requests in flow. I found out that this variable has a static value (perhaps the one, which was saved while creating an Example)

### Steps To Reproduce

1. Send POST (rest) request with an environment variable in request path which is generated random GUID value in Pre-request (i.e. POST someUrl/{{_envId_}})
2. Send POST (soap) with same variable in body (i.e. POST anotherUrl, body <?xml version="1.0" encoding="utf-8"?>....{{_envId_}}) **=>** _envId_ has value which has been used while creating an example for this endpoint.

### Operating System

Windows

### Postman Version

9.15.13

### Postman Platform

Postman App

**Comment by rcduque** [comment]
For some reason Postman team, avoid this functionality to update enviroment variables in flow mode. So maybe this is the issue you have. You can check here the details: https://stackoverflow.com/questions/71113162/why-environment-variable-doesnt-update-in-postman-flow

**Comment by rabbah** [comment]
Environment variables are immutable in Flows.
