### ISSUE TITLE
Search for variables in variable list; sort variables alphabetically

### ISSUE THREAD

**Issue by alirsattar** [a85/POSTMan-Chrome-Extension#10859]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request

### Is your feature request related to a problem?

I often have difficulty finding a given variable in our large collections.

### Describe the solution you'd like

Just give me a text box to search for the variable -- with or without auto-fill.

Or at least let me sort the var list alphabetically.

**Comment by DannyDainton** [comment]
Duplicate of https://github.com/postmanlabs/postman-app-support/issues/10602
