### ISSUE TITLE
All Collections are gone!

### ISSUE THREAD

**Issue by Endy-c** [a85/POSTMan-Chrome-Extension#10863]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

I duplicated a request in my collection and edit it, there's a loading icon at the right of the request (in area 2). The only abnormality is that this loading has disappeared for a longer time than usual. So I didn't care about it. After I finished my editing and save this request(area 1), area 2 was suddenly emptied. You can see there are 7 collections in area 3, but none of them are showed in area 2. I've restarted my client and used web version, the bug still exists and I have no idea how to fix it. And who's that '1 private user' guy in area 4? I didn't invite him to my workshop, and it's not a normal user, there's no link to jump when the mouse hovers.

### Steps To Reproduce

I don't know how to reproduce, because I can't restore my workshop to normal and try it again.
This is important because all of my works have gone!

### Screenshots or Videos

<img width="1616" alt="image" src="https://user-images.githubusercontent.com/28978423/164960322-7cd19fa0-e96c-4a97-964e-bcb4e8e41e72.png">

### Operating System

macOS Monterey(Darwin Kernel Version 21.4.0)

### Postman Version

9.16.1

### Postman Platform

Postman App

### Additional Context?

Postman Platform: I can't choose both of App and Web, they have the same issue.

**Comment by Endy-c** [comment]
Fortunately, I did a data export and import, and collections recovered. After the import, some collections were duplicated. Delete these repetitions, and it will be restored to the original state.

**Comment by postman-staff** [comment]
Hey hi,

Glad that you were able to get the issue sorted out. Thanks for letting us know!
If you’re all set, that’s great. I will go ahead and mark this situation `Solved`.

Feel free to reach out again if you need anything else. We'd be more than happy to help.
Have a great day!

via @Lincimary | Postman Support

**Comment by Raj-postman** [comment]
@Endy-c Also wanted to know if this issue occurred post update?
If possible do share the logs as per [this article here](https://support.postman.com/hc/en-us/articles/360047765713-How-to-open-my-logs-directory) to help us identify the cause of these issues. Thanks!

**Comment by Endy-c** [comment]
@Raj-postman Which log would you want? Or all of them? And how to submit my logs to your team? Because I don't if there's anything private in these logs?
<img width="224" alt="image" src="https://user-images.githubusercontent.com/28978423/165230609-d03d2873-1daa-4959-a659-463c96435481.png">

**Comment by Endy-c** [comment]
@Raj-postman I've send an email with a zip file where my logs in to help@postman.com. Please check.

**Comment by Raj-postman** [comment]
@Endy-c Thank you!
We have received the files.
