### ISSUE TITLE
Can't upload/sync a collection

### ISSUE THREAD

**Issue by yurik** [a85/POSTMan-Chrome-Extension#1086]
Can't upload a collection -> https://www.getpostman.com/collections/c47cb6112c3935b5152e 
user: socialqa_us
user: ykalynovskiy

**Comment by abhijitkane** [comment]
@yurik Can you try duplicating the collection and uploading it?

**Comment by yurik** [comment]
@abhijitkane Duplicating the collection did help. I also cleared Chrome cache and cookies just in case. That didn't help either. Do you need the collection back up file to further debug the issue? Let me know where to send if you need it.

**Comment by yurik** [comment]
Any other steps I can take to further debug the problem?

**Comment by abhijitkane** [comment]
No, it looks to be an issue with the Postman app. We'll push a fix soon.

**Comment by yurik** [comment]
When do you intend to push a fix? One of my teammates hit the same issue with newer version on Postman also.

**Comment by abhijitkane** [comment]
@yurik Are you able to upload with v3.0.4?
