### ISSUE TITLE
Postman Incorrectly read csv file 

### ISSUE THREAD

**Issue by amrit9326** [a85/POSTMan-Chrome-Extension#10867]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

I'm trying to automate in postman and there's one issue I'm struggling with...

Suppose csv file has duplicate column as below

C,A,A,A
x,1,4,7
y,3,5,8
z,3,6,9
Now when I'm trying to upload my csv file to run the collection in preview of data (before run collection) or while printing the pm.iterationData only the first and last column are there , 2nd and 3rd columns are removed with data under those columns as they were the duplicates of 4th column

### Steps To Reproduce

1. create csv file with duplicate column name 
2. upload csv file in collection runner
3. check in preview one column will be shown and other duplicate column will be removed.

### Operating System

Windows

### Postman Version

v9.16.0

### Postman Platform

Postman App

**Comment by DannyDainton** [comment]
Hey @amrit9326 

The way that data files work within the runner is that it uses those column headers (C, A, A, A) as the variable name, this is the name you reference in your Collections. 

Those would need to be _unique_ titles for the runner to know, which Column you wanted to get the values for in each iteration. If you were to use `{{A}}` in a request, which value do you want to use?

The same stripping of the duplicate keys would happen if you were using a JSON data file:

```json
[
	{
		"id": 1, 
		"name": "Danny", 
		"name": "Danny"
		
	}
]
```

<img width="702" alt="image" src="https://user-images.githubusercontent.com/17089546/165515506-8677cb6d-6e99-4b09-9c42-57c813a12d4d.png">


If you rename the columns to have unique names, you would be able to see these in the preview and also be able to use these variables in the Collection.

**Comment by amrit9326** [comment]
Hi @DannyDainton ,

Yes I believe the same but is there any solution for this ?
Below is my requirement .

My request payload suppose looks as below -

{
"name" : "amrit"
"department" : ["IT","CSE","ECE"]
}

as you can see department is array in my request payload so I was preparing the data like below in excel 

name, department, department, department
amrit, IT             ,   CSE,               ECE

but as runner removes the 2nd and 3rd duplicate column I can read amrit and ECE so my request payload would look like as below based on the pre script have written 

{
"name" : "amrit"
"department" : ["ECE"]
}

Please note there can be special character as well in the department so I can't put some delimiter as special character and split it by putting all the department in the same row like below 

name, department
amrit, IT:CSE:ECE

**Comment by DannyDainton** [comment]
You could do something like this:

CSV file
```
name,department
amrit,"""IT"",""CSE"",""ECE"""
```

Request Body
```
{
    "name": "{{name}}",
    "department": [{{department}}]
}
```

Preview

![image](https://user-images.githubusercontent.com/17089546/165522960-481271d7-62ac-4300-ba27-8293569613c9.png)

Request body in the Runner
![image](https://user-images.githubusercontent.com/17089546/165522845-cc5615f5-4e37-405e-8aea-fbfa206cc633.png)

**Comment by amrit9326** [comment]
Hi @DannyDainton  , apologies I didn't explained the issue in more deep , the above will work but the real issue is explained as below ---

 request payload looks as below -  
```json
{
    "name": "amrit",
    "department": [
     {
          "deptName" : "IT"
           "deptID" : 1   
     },
      {
          "deptName" : "CSE"
           "deptID" : 2   
     }
]
}
```

Here I want to get the department in iteration data as object like below so that I can set both `deptName` and `deptID` (base on the loop number)
```javascript
let departmentList = pm.iterationData.toObject().department// ["IT","CSE","ECE"]
and then loop through the list and set both  "deptName" : "IT" and 
           "deptID" : 1   (based on the iteration of the loop)
```
Thanks for the help in advance

**Comment by DannyDainton** [comment]
Hey @amrit9326 

This feels like it's moving more towards a Javascript code tutorial within the sandbox, rather than being a Postman product issue. I don't think that we're going to fix anything in the product based on this issue.

In an effort to reduce the number of these issues in the repo, I'm going to close this out and ask you to raise this as a new topic on the Postman Community forum, please.

https://community.postman.com/

We have an awesome bunch of community members that can advise you here and help you with a solution.
