### ISSUE TITLE
Allow "local" variables to be defined for single request from the GUI

### ISSUE THREAD

**Issue by AtricoSoftware** [a85/POSTMan-Chrome-Extension#10868]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request

### Is your feature request related to a problem?

A complex request makes repeated use of a given value ("version" is a good example).  To change the version, the value needs changed in a number of places (url, filename parameter, etc).  This is an ideal use case for variables
However, this variable has no meaning outside of this request and it therefore makes no sense to store this as global, collection or environment. It would also be useful to see a list of variables defined for this request to get an idea of what is configurable for the request.  The request itself would be clearer as it might not be obvious that part of a url is in fact a configurable value.

### Describe the solution you'd like

A variables tab on the request page, along side and similar to "Params" and "Headers" providing a table of variables used in this request and the ability to edit them.  These would also override any equivalent variables set at a higher scope.
#### example
![image](https://user-images.githubusercontent.com/6891048/165566760-27ea31cf-9dad-4975-9dc7-ca90f3bd2f58.png)

### Describe alternatives you've considered

Global variables can be used but these are separate from the request and could easily lead to issues when common names are used (e.g. "version")

### Additional context

This seems (to me) to be a natural extension of the other scopes of variables

**Comment by giridharvc7** [comment]
@AtricoSoftware We'd love to go over your use case, would you be available for a short call? Feel free to book one using this [link](https://calendly.com/giridhar-vc-postman/)

**Comment by AtricoSoftware** [comment]
> @AtricoSoftware We'd love to go over your use case, would you be available for a short call? Feel free to book one using this [link](https://calendly.com/giridhar-vc-postman/)

Sure, have booked 15m later today (Sorry for delay, I didn't check the notifications until today)
How will we connect? (phone, whatsapp, zoom, etc.)

**Comment by skatikia** [comment]
@AtricoSoftware A bit late, but I'm here with an exciting update!

With Postman **V11.14**, we have rolled out several updates to the variables interface including **the ability to set local values at the request level**. 

You can define a variable using the `{{variable-name}}` syntax without adding to any scopes. This prompts you to enter a value that stays local to the request for as long as the request is open.

![unscoped-variable](https://github.com/user-attachments/assets/2c1f6bc0-d8a4-455d-ab36-8c651906000a)

[Check out the Postman V11.14 release note](https://arc.net/l/quote/vtemyulc)

**Comment by AtricoSoftware** [comment]
Awesome, I hadn't noticed this but the fix is great, thanks
