### ISSUE TITLE
Changing parametres and then saving resets parameter to previous value

### ISSUE THREAD

**Issue by fjuza1** [a85/POSTMan-Chrome-Extension#10861]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Hello world,

After I had changed my parameter, the parameter then reseted to its previous value. This started happening after the new update. Is it related in any way? Another thing is that when I export collection, I get <Error: Too many levels of nesting to fake this schema>

### Steps To Reproduce

1.Changed parametre
2.Saved parameter
3. Value of parameter reseted.

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/104192489/164637390-8adec9c0-4b9c-4d7d-a21d-e6cfdaec1ab1.png)

![image](https://user-images.githubusercontent.com/104192489/164637726-ccc1c1d7-0a99-48f4-9a2a-fb9b11a87958.png)

After saving, it DID reset.
![image](https://user-images.githubusercontent.com/104192489/164638552-62ff16d3-4d6d-4a9f-af1e-1661ef24565a.png)

I appologize in advance that my screenshots are not in engling

### Operating System

WIndows 10

### Postman Version

9.16.0

### Postman Platform

Postman App

### Additional Context?

Parameter that I wrote is NULL in globals, does not exist.

**Comment by giridharvc7** [comment]
Can you send us some logs from the dev console @fjuza1 ?

**Comment by fjuza1** [comment]
I am closing this issue, I had to save request as request and delte old request.
