### ISSUE TITLE
Support groups in tabs (similar to chrome tab groups)

### ISSUE THREAD

**Issue by jagz-hbh** [a85/POSTMan-Chrome-Extension#10866]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request

### Is your feature request related to a problem?

Having tab groups will help out in preventing chaos when we have opened multiple tabs. Tab groups help with organization.

### Describe the solution you'd like

Having tab groups similar to google chrome.

**Comment by DannyDainton** [comment]
Duplicate of https://github.com/postmanlabs/postman-app-support/issues/9615
