### ISSUE TITLE
Bootcamp: Environment Variables tutorial is broken

### ISSUE THREAD

**Issue by adandy91** [a85/POSTMan-Chrome-Extension#10869]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Environment Variables Boot camp tutorial is broken. 
Tutorial stops at 20%/Adding Variable name.

### Steps To Reproduce

1. Click on Bootcamp -> Debugging and manual testing -> Environment Variables
2. Complete the steps up to adding a variable name
3. Click Next

### Screenshots or Videos

https://user-images.githubusercontent.com/101215317/165564241-e916df5c-0a12-4a4e-a9d3-34cd65d9a0d8.mov

### Operating System

macOS

### Postman Version

9.16.1

### Postman Platform

Postman App

**Comment by DannyDainton** [comment]
Hey @adandy91 

This looks like it's been captured here too https://github.com/postmanlabs/postman-app-support/issues/10684#issuecomment-1063141573 

I'm going to close this issue to help centralise the information.
