### ISSUE TITLE
AWS Signature - support credential files and profiles.

### ISSUE THREAD

**Issue by damianh** [a85/POSTMan-Chrome-Extension#10876]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

Currently one can specify an AccessKey, SecretKey etc :
![image](https://user-images.githubusercontent.com/57436/166478906-95476343-217d-4a4c-984c-3b685d53aee5.png)

However, when using temporary credentials which are typically written to `~/.aws/credentials` under a profile, one has to copy and paste these value into postman which gets tedious very quickly.

### Describe the solution you'd like

Support AWS credentials from a AWS Config / Credential file. [S3 Browser](https://s3browser.com/) is a good example of how this might be implemented, including leveraging environment variables:

![image](https://user-images.githubusercontent.com/57436/166487317-f37458fa-b18a-4a2b-b58a-4917bb50f17b.png)

![image](https://user-images.githubusercontent.com/57436/166487470-1f09c1a4-b125-4210-b8c4-305a25d064a9.png)

### Additional context

No additional context, thank you :)

**Comment by jozenstar** [comment]
That's a very important one.
AWS Best Practices on security state that we should use IAM roles for users to assume. The assume-role action generates a pair of temporary credentials, with the default duration of 1 hour. One of use cases is the AWS OpenSearch, which doesn't recognize IAM groups and only allows assigning permissions to IAM users or IAM roles.

I think Postman absolutely needs this feature ASAP!

**Comment by damianh** [comment]
No response from Postman team.
