### ISSUE TITLE
SQL highlighting works in Documentation edit view but disappears once it is saved.

### ISSUE THREAD

**Issue by CodyBontecou** [a85/POSTMan-Chrome-Extension#10871]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

SQL highlighting works in Documentation edit view but disappears once it is saved. 

Edit view:
<img width="616" alt="Screen Shot 2022-04-29 at 11 49 36 AM" src="https://user-images.githubusercontent.com/20440899/166073547-51511fe7-79ae-4fd0-8573-3387d34a2b34.png">

Saved view:
<img width="678" alt="Screen Shot 2022-04-29 at 11 49 43 AM" src="https://user-images.githubusercontent.com/20440899/166073553-ad148347-8397-4ab2-bf83-1ce2f3a9f60c.png">

### Steps To Reproduce

In edit documentation view,

1. Create a code block using three `'s.
2. Select SQL as your block language
3. Type SQL into block. You should now see proper hightlighting.
4. Save documentation edits. SQL code blocks will no longer be highlighted.

### Screenshots or Videos

Edit view:
<img width="616" alt="Screen Shot 2022-04-29 at 11 49 36 AM" src="https://user-images.githubusercontent.com/20440899/166073547-51511fe7-79ae-4fd0-8573-3387d34a2b34.png">

Saved view:
<img width="678" alt="Screen Shot 2022-04-29 at 11 49 43 AM" src="https://user-images.githubusercontent.com/20440899/166073553-ad148347-8397-4ab2-bf83-1ce2f3a9f60c.png">

### Operating System

MacOS

### Postman Version

9.15.13

### Postman Platform

Postman App

**Comment by ajeet-postman** [comment]
@CodyBontecou I can see that this is fixed now. Can you please confirm once?

**Comment by kamaraj-p** [comment]
Verified the fix on production v10.0.31.
