### ISSUE TITLE
Embed Video in Documentation

### ISSUE THREAD

**Issue by mayur-tendulkar** [a85/POSTMan-Chrome-Extension#10872]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

Postman Editor for documentation is in BETA. It either allows embedding images or using Markdown mode.  However, it doesn't allow embedding videos in the documentation.

### Describe the solution you'd like

For documentation purposes, it makes sense to include a video (html5 tag?) and eventually embed the video in the documentation.

**Comment by ankitjaggi** [comment]
@mayur-tendulkar This has now been enabled in the latest version of the App (v10.14)
