### ISSUE TITLE
Postman Duplicate Tab exhibits bizarre behavior

### ISSUE THREAD

**Issue by Experlogix-DEV** [a85/POSTMan-Chrome-Extension#10877]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

In the Postman app, when I duplicate a tab, it creates more like Siamese twins, forever conjoined, that always remain mirror images of each other. After duplicating a tab I wanted to change the JSON payload of the duplicated one and leave all else the same. But when I change the payload (or the name, or the URL, or a header, or anything else), it REACHES OVER to the original and changes that to match.

Who would want it this way? WHY would anyone want it this way? It defeats the purpose of duplication. When I duplicate a tab in Postman I expect that the original and the duplicate are independent of each other and I can change each as needed. This is how duplication works in browser tabs and in all other software I have ever used.

This seems like a bug or a huge design flaw.

### Steps To Reproduce

1. Duplicate a tab.
2. Change something in the duplicated tab.
3. Observe that the original tab has annoyingly changed itself to match the duplicated tab.

### Operating System

Windows 11

### Postman Version

9.17.1

### Postman Platform

Postman App

**Comment by DannyDainton** [comment]
Hey @SouthJordanDev ,

There's a difference between duplicating a request _tab_ and duplicating a _request._ 

> Duplicate Selected Tab: (Desktop app only) Duplicates the current tab. This doesn't create a copy of the request, so when you duplicate a tab any edits you make are reflected in the original request. 

https://learning.postman.com/docs/getting-started/navigating-postman/#tabs

Duplicating a request can be done from the Collection sidebar:
<img width="380" alt="image" src="https://user-images.githubusercontent.com/17089546/166741371-fd107d16-1c78-442f-a01e-9ad12b915185.png">
