### ISSUE TITLE
OpenAPI request body Examples are not loaded when imported

### ISSUE THREAD

**Issue by trajano** [a85/POSTMan-Chrome-Extension#10878]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

I am trying to use openapi to define my API and I'd like Postman to use the values there rather than manually repeating in postman.

Here is a openapi spec doc.

```yaml
openapi: 3.1.0
info:
  title: Spring Cloud Docker Swarm
  version: 3.0.0
  description: |
    An implementation ...
  license:
    name: EPL-2.0
    url: https://www.eclipse.org/org/documents/epl-2.0/EPL-2.0.txt
servers:
  - url: http://localhost:28082
    variables: {}
paths:
  /auth:
    post:
      summary: Authenticate user
      operationId: AuthenticateUser
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AuthenticationCredentials"
            examples:
              good-login:
                summary: Good login
                value:
                  username: good
                  authenticated: true
              bad-login:
                summary: Bad login
                value:
                  username: bad
                  authenticated: false
components:
  schemas:
    AuthenticationCredentials:
      type: object
      properties:
        username:
          type: string
        authenticated:
          type: boolean
```

### Describe the solution you'd like

When I import I should see the examples I created in here 

![image](https://user-images.githubusercontent.com/110627/166495136-9421f3c7-fa71-446e-a54f-7bf6e7f1ea79.png)

### Describe alternatives you've considered

Manually doing it.

### Additional context

Note this is **`examples`** not `example`

**Comment by VShingala** [comment]
@trajano You can choose the value "Example" for the option named "Parameter generation" while importing under "View Import Settings".

![Screenshot 2024-01-29 at 7 22 56 PM](https://github.com/postmanlabs/postman-app-support/assets/16756296/bb3048ca-0b4b-4d97-97cc-fbf1b2f7f1cc)

![Screenshot 2024-01-29 at 7 23 34 PM](https://github.com/postmanlabs/postman-app-support/assets/16756296/24b4c0bf-c5cc-4fbe-843a-b0ff7f56d384)


Also, the mentioned definition by you seems to be an invalid OpenAPI definition. I was able to generate the examples with the mentioned behavior with the following updated definition mentioning responses.


```
openapi: 3.1.0
info:
  title: Spring Cloud Docker Swarm
  version: 3.0.0
  description: |
    An implementation ...
  license:
    name: EPL-2.0
    url: https://www.eclipse.org/org/documents/epl-2.0/EPL-2.0.txt
servers:
  - url: http://localhost:28082
    variables: {}
paths:
  /auth:
    post:
      summary: Authenticate user
      operationId: AuthenticateUser
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AuthenticationCredentials"
            examples:
              good-login:
                summary: Good login
                value:
                  username: good
                  authenticated: true
              bad-login:
                summary: Bad login
                value:
                  username: bad
                  authenticated: false
      responses:
        200:
          description: OK
          content:
            application/json:
              example:
                hello: world
components:
  schemas:
    AuthenticationCredentials:
      type: object
      properties:
        username:
          type: string
        authenticated:
          type: boolean
```

![image](https://github.com/postmanlabs/postman-app-support/assets/16756296/d8d980ab-da72-4fb1-b501-4a5d9acc9c8c)
