### ISSUE TITLE
Postman doesn't load items inside a collection on the sidebar

### ISSUE THREAD

**Issue by atirach-in** [a85/POSTMan-Chrome-Extension#10875]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Postman version 9.17.1 can not fetch file API in folder my workspace please fix issue 

### Steps To Reproduce

1. Open postman
2. Can not fetch file API in folder my workspace

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/52520152/166404429-edfbec23-58e7-413c-8b0b-824af2adb21e.png)
![image](https://user-images.githubusercontent.com/52520152/166404438-f6acff58-6cfe-4617-a270-75480be49497.png)

### Operating System

Windows

### Postman Version

9.17.1

### Postman Platform

Postman App

**Comment by abhijitkane** [comment]
@atirach-in Can you provide additional context about what your workflow is? Are you using the Postman API on api.postman.com, or trying to upload a file while sending a request?

**Comment by atirach-in** [comment]
No, I opened windows postman, then went to my workspace and opened the project folder, it didn't load my APIs in that folder.
![Screenshot_1](https://user-images.githubusercontent.com/52520152/166405721-f6a80415-10ce-4802-8e9b-1f1ef2612941.png)

**Comment by atirach-in** [comment]
I clear cache and reload is fixed issue thanks

**Comment by giridharvc7** [comment]
@atirach-in We are taking this up as a bug. Will keep this thread for future updates and reference.

**Comment by giridharvc7** [comment]
@atirach-in this should now be fixed with the latest update. Please update your app and feel free to open this issue in case you still see it.
