### ISSUE TITLE
Published Docs: Allow Themes

### ISSUE THREAD

**Issue by mayur-tendulkar** [a85/POSTMan-Chrome-Extension#10889]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

Current documentation doesn't support themes (Light, Dark).

### Describe the solution you'd like

Allow users (and publishers) to select themes for their documentation.

**Comment by arlemi** [comment]
We've added the ability to customize the colors for both light and dark theme of published documentation in the latest version of Postman (v10.13), try it out! 

More info here: https://learning.postman.com/docs/publishing-your-api/publishing-your-docs/#making-your-documentation-public
