### ISSUE TITLE
Url parser doesn't parse parameters enclosed in single quotes and treats them as string

### ISSUE THREAD

**Issue by harsimranmaan** [a85/POSTMan-Chrome-Extension#1088]
1. Import swagger json from https://raw.githubusercontent.com/OData/ODataSamples/master/swagger/trippin.json
2. Go to the Airlines('{{AirlineCode}}') node and select 'Get entity from Airlines by key.'
3. Note that in the request url params, {AirlineCode} is not listed. Only {select} is parametrizable.

Expected: Both AirlineCode and select should appear in the Url params.

**Comment by abhijitkane** [comment]
The URL is `http://services.odata.org/V4/(S(cnbm44wtbc1v5bgrlek5lpcc))/TripPinServiceRW/Airlines('{{AirlineCode}}')?$select={{$select}}`
Postman will only recognize the part after the `?` as the query string. Any variables used before the `?` will not be detected as URL params.
