### ISSUE TITLE
Postman Editor Beta Mangles Markdown, Can't Be Disabled

### ISSUE THREAD

**Issue by brandonkirsch** [a85/POSTMan-Chrome-Extension#10883]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

I write Postman documentation using the Classic Markdown editor.  Every time I begin to edit documentation, I am dropped into the new Postman Editor Beta by force.  Then I have to make two clicks to revert back to the Classic Markdown editor **every time** I want to make a change. 

Forcing a beta is annoying and wrong and should be corrected, but there is a bigger problem here:  The Postman Editor Beta is mangling my hand-written Markdown by injecting newline characters where they did not originally exist.

Because I am forced into the Beta Editor, there is no way for me to consistently retrieve & edit my original markdown in our Postman documentation.

Please stop forcing Beta features by default, provide an option to disable them, and most importantly **fix** the Markdown mangling bug that occurs when it is in use.    At the very least: when I skip by the force-fed Beta editor and make no changes to the documentation, then the original Markdown should be left in-tact and not overwritten by the Beta editor.

### Steps To Reproduce

1.  Open a saved request and click the "Documentation" tab
2.  Click the "pencil" icon to edit the Markdown
3.  Change to Classic Markdown editor
4.  Create a header immediately followed by a paragraph of text:
```
#Header
This is a paragraph of text that immediately follows my header.
```
5.  Save the markdown
6. Click the "pencil" icon to edit again.
7. Change to Classic Markdown editor (again)
8. Behold the altered Markdown with unwanted and unnecessary whitespace:
```
#Header

This is a paragraph of text that immediately follows my header.
```

### Operating System

Linux (Fedora 35)

### Postman Version

Help -> About is missing

### Postman Platform

Postman App

### Additional Context?

We are paying subscribers that are sick and tired of Postman The Company breaking our existing workflows with the forced and never-ending stream of changes to Postman The App.

**Comment by kamaraj-p** [comment]
Thanks @brandonkirsch for reporting this. The issue is now fixed. For any special cases that are currently not supported in the Postman editor, you can set the Markdown editor as the default editor. To use this settings please see [this](https://learning.postman.com/docs/publishing-your-api/authoring-your-documentation/#selecting-a-default-documentation-editor)
