### ISSUE TITLE
The possibility of stopping the collection runner at a given step and manually continuing when you are ready

### ISSUE THREAD

**Issue by JWATSU** [a85/POSTMan-Chrome-Extension#10881]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

I have a collection of 100 requests. Sometimes I want to run the first 50, stop and do some manual checking on the responses I have gotten before I do the next 50. This isn't possible right now, at least not with an easy way of doing it. 

### Describe the solution you'd like

For example, make it possible to add a "manual test step" or a pause at a given point in a collection, or in the runner itself. 

### Describe alternatives you've considered

Manually selecting only the first 50 and then select the next 50. This is extremely time consuming and annoying.

**Comment by malvikach** [comment]
@JWATSU It seems like you are interested to add break points in between, validate something and then move the execution forward. 

This [feature request](https://github.com/postmanlabs/postman-app-support/issues/8060) suggests the same. Please feel free to add any further thoughts on this ticket. 

I am closing this ticket as it is similar to the above feature request.
