### ISSUE TITLE
Variable not replaced in body unless followed by a space

### ISSUE THREAD

**Issue by mj-h** [a85/POSTMan-Chrome-Extension#10891]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

When I use a variable in the request body, then the variable is not replaced with its content, unless the variable is followed by a space. This behavior only appears, if the variable is set inside the prerequest script.

Prerequest script:
```
pm.environment.set("test ", "some-string");
```

Message body:
```
This is working: "{{test }}",
This is not working: "{{test}}",
```

### Steps To Reproduce

1. Create a new request
2. Insert the prerequest-script `pm.environment.set("test ", "some-string");`
3. Insert the body `this is a test: {{test}}`. 
4. Send the request once to make sure the prerequest-script is being run
5. Inspect the generated http-request and observe that the variable is not replaced.
6. Modify the body to `this is a test: {{test }}` and observe that it now works.

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/20513065/166944257-0ad75402-eb11-4f83-8c67-57bf648df5b1.png)

![image](https://user-images.githubusercontent.com/20513065/166942197-00977877-4f47-4a73-be31-1ec73bc06698.png)

### Operating System

macOS 12.3.1

### Postman Version

9.16.0

### Postman Platform

Postman App

**Comment by mj-h** [comment]
I just found an important piece of information. Please wait a few minutes for me to update the issue

**Comment by DannyDainton** [comment]
Hey @mj-h 

You're saving that variable _with_ a space at the end of the name `pm.environment.set("test ", "some-string")` and it looks like it's working as expected. 

Here's an example with 2 different variables `{{test }}` and `{{test}}`:
<img width="1335" alt="image" src="https://user-images.githubusercontent.com/17089546/166945775-e567c32e-4a2f-4226-b9db-dd1d0f6ddb17.png">

**Comment by mj-h** [comment]
Yes, I am 🤦 .

Ok, I am going into a corner now and think about some of the choices I made.

It would be great if the built-in-linter would warn against "unusual" variable names -- but I mainly blame myself here.
