### ISSUE TITLE
Pressing {shift}+{tab} when editing query parameters does not move focus to previous field, as expected

### ISSUE THREAD

**Issue by jolsen71** [a85/POSTMan-Chrome-Extension#10890]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

All well designed apps that have multiple input fields on a dialog/page have an established tab order for the fields. Normal/expected behavior is when on a field, pressing the {tab} key will advance focus to the next field in the tab order. Pressing {shift}+{tab} will retreat focus to the previous field in the tab order.  A notable exception is when a text block field has focus and tabbing behavior changed to indenting/outdenting text with the text block.

When editing query parameters for a request, at least in the desktop app, pressing {tab} key will take you to the next field query parameter field in the tab order, as expected. For example, if you're editing a query parameter key and press {tab}, it moves to editing the value. Pressing {tab} again moves focus to the description. Lastly, hitting {tab} again moves you to the next query parameter line. 

However, if you press {shift}+{tab} at any point when a query parameter field has focus, it does not take you to the previous field, it seems to remove focus from the query parameters completely. I'm not sure where the focus goes, but it definitely is no longer focused on anything in the query parameters. It then requires the user to move the pointer/mouse cursor back into the query parameters area and click on a parameter to edit in order to resume editing.

Please fix it so that {shift}+{tab} works as expected, moving the focus to the previous element.

### Steps To Reproduce

1. Open a request tab
2. Click any query parameter "key" field to add a new query parameter or edit an existing one
3. Press {tab} key, and focus should move to next query parameter field ("value")
4. Press {shift}+{tab} combination and the focus should move back to the previous query parameter field, but instead focus seems to go somewhere else/be lost and the user can no longer use the keyboard to navigate and enter query parameters. 

### Operating System

Windows

### Postman Version

9.17.1

### Postman Platform

Postman App

**Comment by timbochamp** [comment]
Thanks for raising this @jolsen71. I logged the feature label to have this looked into by Product where shift+tab is a common hotkey for sure. 

Our current implementation is to use the arrow keys for navigation through key-value cells. I realize this isn't ideal sometimes to have to use the arrow keys to go all the way to the beginning of the input with the left arrow key to access the next left cell (or use the Home key to skip to the start of the input, and then left arrow key)

**Comment by giridharvc7** [comment]
@jolsen71 We've fixed this. Can you check the latest app once and let us know if this experience works fine for you?
