### ISSUE TITLE
Select Files on file type inputs not working

### ISSUE THREAD

**Issue by etsyachristensen** [a85/POSTMan-Chrome-Extension#10892]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

I have an endpoint I'm attempting to send a POST to. This endpoint calls for an input called "image" that is a file type. When I added the "image" key and selected "File" from the drop down the "Select Files" button appears. But when I click the button nothing happens. I can't attach a file.

### Steps To Reproduce

1. Open a new request tab
2. Select the Body tab
3. Select the `form-data` type 
4. Add key "image".
5. Select "File" from the drop down on the right of the key box.
6. Attempt to click on Select Files.

### Screenshots or Videos

I took a screen recording but I have no way to share it with you. Company restrictions prevent me from uploading to Youtube or anything. If you want the video, please provide a location where I can upload it.

### Operating System

macOs

### Postman Version

9.17.1

### Postman Platform

Postman App

**Comment by DannyDainton** [comment]
Hey @etsyachristensen

This should be opening `Finder` on your machine, did it open behind the app or on a different screen?

Do you see the same thing happened on the Web version?

https://go.postman.co

**Comment by etsyachristensen** [comment]
No the web version worked fine. I looked for popups and windows but found nothing. I completely quit the desktop app after using the web version. Upon restarting it worked again.
