### ISSUE TITLE
OAuth2.0 Config with Proxy

### ISSUE THREAD

**Issue by lpendergrass** [a85/POSTMan-Chrome-Extension#10893]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

The OAuth2.0 auth config launches a built in browser if  "Authorize using browser" is unchecked. It does not appear to adhere to configured proxy settings.

### Steps To Reproduce

Configure Proxy Settings in Preferences...

Collection > Edit > Authorization tab
Type: OAuth 2.0
...fill out relevant fields...
uncheck Authorize using browser
Get New Access Token

### Operating System

macOS 12

### Postman Version

9.16.0

### Postman Platform

Postman App

**Comment by timbochamp** [comment]
Thanks for submitting, @lpendergrass. This sounds similar to #10010. Can you confirm whether it is and whether the suggested workaround helps unblock you?

**Comment by lpendergrass** [comment]
Using multiple proxies for testing purproses so that workaround does not address my needs. Will close due to duplicate though.
