### ISSUE TITLE
Could not import openAPI v3 as collection #517

### ISSUE THREAD

**Issue by rajesh-kg-20089** [a85/POSTMan-Chrome-Extension#10898]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Hi,

We have an OpenAPI v3 file that's around 5mb in size with 300+ endpoints. When we try to import this as a collection, the following error is shown.  However, we are able to successfully import this in Swagger Editor.  

Is there a solution or workaround for this?

Also, when we try with a subset of the file(around 2.5mb), we are able to reproduce https://github.com/postmanlabs/postman-app-support/issues/10692

Thanks 

### Steps To Reproduce

1. Import openapi file of size of 5 MB

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/103045298/167102004-dfd9af46-a08c-4f44-bbb8-1e34e6e32905.png)

### Operating System

Linux

### Postman Version

9.17.1

### Postman Platform

Postman App

**Comment by harmonf13** [comment]
Seeing the same error on with a Swagger version 2.0 file as well in Windows Postman version v9.18.1.  It seems like a memory error or something in postman.  I started by cutting down my Swagger file to have a single route and it worked fine.  I slowly added back until eventually it stopped working again.  Then I tried removing and adding random routes to prove there wasn't anything wrong with a specific route.  Eventually by adding or removing one random route I could get it to work or fail with this same error.

**Comment by timbochamp** [comment]
Thanks for reporting this. I've logged an issue for the team to investigate these errors when importing an openAPI v3 file with a large number of endpoints. We'll be in touch should we need more information!

**Comment by rajesh-kg-20089** [comment]
@timbochamp any update on this ?

**Comment by timbochamp** [comment]
@rajesh-k-g sorry for the delay! 

Following #10692's workaround steps that Harsh suggested in https://github.com/postmanlabs/postman-app-support/issues/10692#issuecomment-1144415227 and https://github.com/postmanlabs/postman-app-support/issues/10692#issuecomment-1144416496; could you please share your issue information at help@postman.com so we can look into enabling an optimized flow for your team? The hope is that the import performance optimizations when released will resolve this, but having your use case and data will be useful to ensure that

**Comment by rajesh-kg-20089** [comment]
Hi @timbochamp,

Seems that the issue is resolved now. Thanks for the support :+1: 

P.S. I will send mail with the data to analyze further if needed.

**Comment by VShingala** [comment]
@harmonf13 Could you confirm if issue is solved for you? If not, it'd really help if you can share sample API definition for which issue is happening.
