### ISSUE TITLE
ALL SCRIPTS (test and pre-request) DELETED from request when new postman window is opened in the same workspace as previous

### ISSUE THREAD

**Issue by MerryCello** [a85/POSTMan-Chrome-Extension#10894]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

When I open a new postman window in the same workspace as previous window, all my scripts (test and pre-request) disappear from request tabs (saved in a collection) I had opened. I had taken the time to learn how to make tests with postman, and all that I had is GONE. This is surreal.

### Steps To Reproduce

1. Create some requests and save them to a collection
2. Add some scripts to the requests and save
3. Open new Postman window and select to work in the workspace as where the requests are
4. The scripts will be gone

### Operating System

Windows

### Postman Version

9.17.1

### Postman Platform

Postman App

### Additional Context?

Update: It's worst than I thought. It actually deleted everything in any request open in a tab except for the URLs (so params stayed).

**Comment by MerryCello** [comment]
I have reproduced the issue, and those were the steps for the bug. I tried it again, and can't figure out how to reproduce it anymore with those steps.

**Comment by postman-staff** [comment]
Hey @MerryCello 👋
I have tried to replicate this behaviour but was unable to, unfortunately.
May I request to know if you are able to replicate this actively or is specific to certain requests?

Also, If you have been using this request recently, that is, if you have sent this request recently, it will be saved in History, which you can filter with keywords. The history record will contain the scripts used as well, which you can save back to a collection.

I will wait to hear back from you.

via @VaishnaviChallaPostman | Postman Support

**Comment by MerryCello** [comment]
That's the weird part, I was able to reproduce it only once after the
incident. I don't know what triggered it. Thank you, I didn't know about
the history!

**Comment by postman-staff** [comment]
Hey @MerryCello,
Thanks for the revert and confirmation.
I am going ahead and closing this thread as you are unblocked, but will make sure to keep an eye on any related issues.
Please feel free to reopen if you are facing this issue again.
Have a great day :)

via @VaishnaviChallaPostman | Postman Support

**Comment by mplavsa** [comment]
Hi there, I was able to reproduce this issue multiple times today.

My workflow:
1. Two windows with same workspace
2. Another two windows with same workspace
3. Console window 

One pair info: One window for sending basic requests, second window (if response is 200) is for automation (chaining) 

Issue: 
I was able to reproduce this issue with 6th or 7th opened window (opened for quick edit / save).
Edit or not, saved upon edit or not, I was able to see that scripts, JSON, authentication etc. are missing.

Definitely new windows are causing this issue.

Postman version:  v9.23.3

**Comment by shubhbhargav** [comment]
@bogmarko May I know which windows version are you on? Also would it be possible for you to share a screen recording for this?

**Comment by mplavsa** [comment]
> @bogmarko May I know which windows version are you on? Also would it be possible for you to share a screen recording for this?

Hi, I'm using Windows 10 64bit.
Unfortunately, I can't record this since I'm not sure what triggers it. Very random situation. 
Since my previous post, I'm using now two windows with different workspaces.
I'm tired of copy/paste job due to large number of folders, subfolders, scripts in requests etc. You will understand me. 
Please investigate. Just open few new windows for the same workspace and try to edit test script, or update local or environment variables. I'm sure you will catch it soon or latter.
