### ISSUE TITLE
Request with huge JSON response hangs postman

### ISSUE THREAD

**Issue by henhal** [a85/POSTMan-Chrome-Extension#1089]
If making a request that renders a huge (~thousands of lines) chunk of JSON as the response, POSTMan will simply freeze and has to be force killed. Supposedly it will wake up minutes later when the data is processed, but in the mean time, the cancel request button, close tab button and just about everything is non-responsive.

**Comment by abhijitkane** [comment]
@henhal What version of Postman are you using?

**Comment by henhal** [comment]
Hi @abhijitkane 

Version 3.0.0.4 (packaged)
OS: win
Architecture: x86-32
Native client architecture: x86-64

I updated it today, previously I had the old version with the old look & feel, the issue was present on that version as well though.

**Comment by achoice** [comment]
Same here with a 13 mb JSON response. :( Same URL in Chrome displays it fine.
Version 3.0.0.5 (packaged)
OS: win
Architecture: x86-32
Native client architecture: x86-64

**Comment by jwoodall** [comment]
Not sure if this is the same problem but I get it on a 3.3MB zip file returned happens on 3.0 but not on versions before.

It freezes the response, and if I close the app or tab, postman will cease to work unless I disable it within google chrom.

On OSX 10.10
