### ISSUE TITLE
Status code: 14 UNAVAILABLE,  but no Error Message, no Response Metadata, no Result

### ISSUE THREAD

**Issue by steverawlins-zebra** [a85/POSTMan-Chrome-Extension#10902]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Valid gRPC request, hitting a valid service, always returns "14 UNAVAILABLE" 

### Steps To Reproduce

1. Create  new gRPC request
2. Service is running on localhost:9090
3. Import the protobuf from the local file system
4. Execute Request (response is always "14 UNAVAILABLE")

### Screenshots or Videos

![Postman_14UNAVAILABLE](https://user-images.githubusercontent.com/52328771/167691676-0cd42a5b-969c-4bea-858e-09bf7f75cd86.png)

short video:

https://user-images.githubusercontent.com/52328771/167692474-4cfaf575-06d2-4c95-86ba-721a5342e59b.mov

### Operating System

macOs Catalina 10.15.7

### Postman Version

9.17.2

### Postman Platform

Postman App

### Additional Context?

Our protobuf requires no imports except for the Google built-in empty.proto which is provided automatically in protoc

**Comment by codenirvana** [comment]
@steverawlins-zebra from the error message, it looks like there’s no service running at `localhost:9090`.

I am not able to reproduce this issue, can you verify that:

-  the service is running locally at port `9090`, and
- the certificates (Settings -> Certificates) are configured correctly in accordance with your server.

**Comment by harryKont** [comment]
I am facing the same issue with a gRPC service running on localhost. I have added the localhost certificate under Settings -> Certificates. From the gRPC service logs I can see a connection is established using Tls12 but right after that the client sends a FIN  and  the connection is closed.

**Comment by steverawlins-zebra** [comment]
Our service is running on Google Cloud Platform, in a Kubernetes pod.   We connect to it via port tunneling.  It is running. 

Having tunneled to our service, there is no need for a cert or auth bearer token because the service, which is not public, is open:

"This request does not use any authorization. 
Learn more about authorization"

Our service does not require authorization.

=====
Also:  the grpcurl equivalent functions properly, and note the -plaintext 

Is there a "plaintext" or "http" or "insecure" option I am missing inside the Postman gRPC request?


```
grpcurl -plaintext  -proto private_token.proto localhost:9090  privatetoken.PrivateTokenService.GetToken
{
  "token": "xxx"
}
```

**Comment by harryKont** [comment]
I can also confirm it works for the same server using grpcurl but not with Postman. In my case they both establish a Tls connectio but postman closed the connection right after and call was performed.

**Comment by trunkafunk** [comment]
+1 I can also confirm that hitting a public server endpoint, grpcurl works fine, however postman gives Error 14.

**Comment by vishnu-vardhan-sankarapu** [comment]
Looking to add an option like below in Postman GRPC requests
grpcurl --insecure
Even though SSL certificate verification is disabled in general settings, GRPC request is showing error, status code 14 Unavailable

**Comment by counter2015** [comment]
In my case, I have add custom CA Certificates on Postman, and it will lead to server error like 
```
Illegal request, responding with status '400 Bad Request': Unsupported HTTP method: 
The HTTP method started with 0x16 rather than any known HTTP method. 
Perhaps this was an HTTPS request sent to an HTTP endpoint?
```

After I turned it off, it worked.

**Comment by KarineValenca** [comment]
I'm facing the same issue. Using grpcurl I can do requests without using any certificate. Using postman, I have 14 UNAVAILABLE. 

I tried adding CA certificates, client certificates, and disabling SSL certificate verification, but nothing worked.

Example of my grpcurl request:
grpcurl --v -import-path . --import-path proto/third_party -proto proto/login-api/authentification-api.proto  -d '' myendpoint:443 grpc.AuthAPI/PublicStuff

**Comment by codenirvana** [comment]
Hey everyone,

We've identified the issue with TLS connections, we are working on the fix and will update here soon!

**Comment by Kumaragurusankar** [comment]
@codenirvana - any idea when this will get fixed

**Comment by codenirvana** [comment]
We've simplified the TLS configuration flow with the recent release.

Now, you can toggle the lock icon to specify the server's connection preference (TLS or plaintext):

![Screenshot 2022-07-30 at 11 02 59 PM](https://user-images.githubusercontent.com/4865836/181936996-ae67077b-7fa0-428f-ad6e-874c8d7af4e9.png)

Please refer to this https://github.com/postmanlabs/postman-app-support/issues/10533#issuecomment-1200266682 for more details.

**Comment by Ivan-Parushev** [comment]
I still get the same error. grpcurl works fine. The "solution" from the comment above doesn't work for me.
