### ISSUE TITLE
cannot edit the keys for form-data body

### ISSUE THREAD

**Issue by garg-priyanka** [a85/POSTMan-Chrome-Extension#10907]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

when sending requests with multipart/form-data in the body, the visible key File/Text is not included in request. UI does not let you edit the keys.

### Steps To Reproduce

1. On the body tab select form-data from content type drop down
2. add a new key of File type

### Screenshots or Videos

![Screen Shot 2022-05-11 at 11 45 14 AM](https://user-images.githubusercontent.com/41063942/167892187-1a8ad771-80ec-432f-a715-7e77e59f7ab0.png)

### Operating System

MACOS

### Postman Version

Version 9.17.2

### Postman Platform

Postman App

**Comment by timbochamp** [comment]
Hi @garg-priyanka, thanks for reporting. I'm not sure I follow the issue: are you not able to click the Key cell and enter text like so?

https://user-images.githubusercontent.com/4521134/168355678-8f83ca8a-f4ff-4ae4-b2c3-6491895e2f56.mov

If that's the case, are you able to update to v9.18.2 and revalidate if it's still an issue?

**Comment by garg-priyanka** [comment]
Hi @timbochamp, this issue is resolved in v19.18.2 . thankyou
