### ISSUE TITLE
File>Import and Ctrl+O not responding on Postman v9.18.2/v9.16.0/ v 9.17.1

### ISSUE THREAD

**Issue by Smaruthi28** [a85/POSTMan-Chrome-Extension#10908]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

I have just installed the latest Postman v9.18.2. When I try to File-> Import or even try Ctrl+O no Import screen pops up. I have checked and confirmed that all other options except import is working fine. I have uninstalled and installed the app twice to be sure.

### Steps To Reproduce

1. Open Postman v9.18.2
2. Click File -> Import

### Screenshots or Videos

[PostmanBug.zip](https://github.com/postmanlabs/postman-app-support/files/8672270/PostmanBug.zip)

### Operating System

windows

### Postman Version

9.18.2

### Postman Platform

Postman App

**Comment by timbochamp** [comment]
Hi @Smaruthi28 , thanks for reporting; sorry to hear about this. I tried an update on Windows to v9.18.2 and wasn't able to reproduce. Could you try clearing your local data and see if that resolves the issue with the import modal not appearing? Steps are here:

https://support.postman.com/hc/en-us/articles/4410785125271-How-to-remove-local-data

Linking #9520 as well where this follows a similar trend.

**Comment by pbrumblay** [comment]
I've encountered the same issue, cleaning out the postman folder did not resolve the problem.  
```
Postman for Mac
Version 9.31.16
UI Version 9.31.16-ui-221003-0933
Desktop Platform Version 9.31.0
Architecture arm64
OS Platform OS X 21.6.0
```

**Comment by akshaydeo** [comment]
Related to #11292

**Comment by akshaydeo** [comment]
Related to https://github.com/postmanlabs/postman-app-support/issues/11292
