### ISSUE TITLE
XSS prefix stripping broken in Pretty JSON view

### ISSUE THREAD

**Issue by Graham42** [a85/POSTMan-Chrome-Extension#1090]
If using a prefix of `)]}',` get an error in the Pretty JSON view saying `Malformed JSON: Unexpected ')'`

Edit: for version 3.0.0.5

**Comment by abhijitkane** [comment]
Thanks for reporting this. We'll fix this soon.

**Comment by Graham42** [comment]
I wish that you would make your chrome app open source, this is something I would happily submit a PR to fix, and in the meantime it is hugely detracting from the usability of the app.

**Comment by Graham42** [comment]
This appears to be fixed in v3.0.0.6. Thanks
