### ISSUE TITLE
GRPC - Import protobuf definition from local file isn't saved permanently

### ISSUE THREAD

**Issue by uschwag** [a85/POSTMan-Chrome-Extension#10915]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

If we select and save a protobuf definition as file and have used and saved it, the selection is gone after a restart of the Postman app.
The import path selection is still present but there is another is another problem here. We can only have one selection of protobuf file and import path at once. It is not saved on collection or requests level but is valid for the whole session.
As a tester I need to have different selections of protobuf file and import path either on collection and on request level which are saved permanent.

### Steps To Reproduce

1. Open a new gRPC Request an set protobuf file and import folder with Import protobuf definition from local file
2. Save the request to a collection and close client and reopen
3. setting of protobuf file is gone
4. set it again
5. Open a new gRPC Request an set different protobuf file and import folder with Import protobuf definition from local file different compared to 1.
6. Save the request to a collection
7. Open the gRPC Request of 1.
8. Open Import protobuf definition from local file dialog again
9. Now we have the setting of step 5. in there and not from 1.

### Operating System

Windows 10

### Postman Version

9.18.2

### Postman Platform

Postman App

**Comment by codenirvana** [comment]
@uschwag are you importing Protobuf as Postman API?

**Comment by uschwag** [comment]
Hello, as our proto contains reference to additional files we are forced to 
"Use without Importing".




Gesendet mit der Telekom Mail App



--- Original-Nachricht ---
Von: Udit Vasu
Betreff: Re: [postmanlabs/postman-app-support] GRPC - Import protobuf 
definition from local file isn't saved permanently (Issue #10915)
Datum: 17. Mai 2022, 16:52
An: postmanlabs/postman-app-support
Cc: uschwag, Mention


@uschwag are you importing Protobuf as Postman API?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.￼Message ID: 
***@***.***>

[ { ***@***.***": "http://schema.org", ***@***.***": "EmailMessage", 
"potentialAction": { ***@***.***": "ViewAction", "target": 
"https://github.com/postmanlabs/postman-app-support/issues/10915#issuecomment-1128971661", 
"url": 
"https://github.com/postmanlabs/postman-app-support/issues/10915#issuecomment-1128971661", 
"name": "View Issue" }, "description": "View this Issue on GitHub", 
"publisher": { ***@***.***": "Organization", "name": "GitHub", "url": 
"https://github.com" } } ]

**Comment by trunkafunk** [comment]
+1

**Comment by appurva21** [comment]
Hey @uschwag!  We are working on it. Please follow the thread [here](https://github.com/postmanlabs/postman-app-support/issues/10767) for more updates.

Duplicate of #10767
