### ISSUE TITLE
DELETE Method

### ISSUE THREAD

**Issue by renier-p** [a85/POSTMan-Chrome-Extension#10914]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Hi i have an issue using postman, im taking classes and one of the assigments is do an endpoint using the "delete method" but i cant find it in the method menu. here i add a img of my problem. im new on this and  if you could help me i would be very grateful. thank you

### Steps To Reproduce

1. Open the app
2. Click on the method window 
3. cant find "deleted method"

### Screenshots or Videos

![postman](https://user-images.githubusercontent.com/59789007/168721081-a39d6105-2b80-49c0-ad4d-bf5b1df6f65c.jpg)

### Operating System

Windows 11

### Postman Version

9.18.2

### Postman Platform

Postman App

**Comment by DannyDainton** [comment]
Hey @rainer991

If you type the word `DELETE` in the area where you have `GET` highlighted, you will get an option to add it to the list again.

This list is editable and it must have been previously removed.

https://learning.postman.com/docs/sending-requests/requests/#selecting-request-methods
