### ISSUE TITLE
Text is black in Changelog in Dark theme

### ISSUE THREAD

**Issue by aakash3771** [a85/POSTMan-Chrome-Extension#10913]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Reading Black text in changelog with Postman is impossible with Dark theme on

### Steps To Reproduce

1. Set dark theme on Postman.
2. Open changelog for a collection.
3. try to read

### Operating System

mac os big sur

### Postman Version

9.18.2

### Postman Platform

Postman App

**Comment by timbochamp** [comment]
Thanks for reporting, @aakash3771. I've logged a bug for this to have the text colour corrected while in dark mode. We'll relay an update here once it's fixed!

**Comment by timbochamp** [comment]
This should be fixed as of the app version 9.19.3. Thanks again for reporting!
