### ISSUE TITLE
Parameter value reverting to blank when request saved

### ISSUE THREAD

**Issue by boylec** [a85/POSTMan-Chrome-Extension#10918]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Up until this morning (the last few months) I've had a request in a collection that has a path/parameter set.

The value has always been set to 1.
<img width="1531" alt="image" src="https://user-images.githubusercontent.com/8148174/168886612-691a1adb-54fa-4b4a-aaac-148275def32d.png">

However this morning I opened the collection and the value was blank.

I attempted to set the value back to 1 and save the request but when I click save it reverts it back to being blank!
<img width="1518" alt="image" src="https://user-images.githubusercontent.com/8148174/168886739-5b706454-954a-4141-9ca1-1f0e7b4146da.png">

I've tried:
* A different parameter name
* Different values (non-numbers)
* Signing out and back in
* Forking the collection and making changes against the fork
* Duplicating the request and making the same changes against the duplicate
* Completing copying to a new collection and making changes against the copy

The change log of this workspace shows my changes correctly and does not show any subsequent events reverting the change back to blank.

Help!

### Steps To Reproduce

I can't reproduce this trivially.

### Operating System

macOS

### Postman Version

9.18.2, UI: 9.18.2-ui-220511-0750, Desktop Platform Version: 9.16.0 (9.16.0)

### Postman Platform

Both

### Additional Context?

My workspace is a team workspace. I've revoked all sessions besides my own and still no dice.

**Comment by boylec** [comment]
Note:

Exporting the collection, fixing the parameter up in the raw JSON and reimporting as a new collection allowed the parameter to be set. This is not a solution that unblocks however because this is a collection connection to an API so I can't have that connection be detached.

Note 2:
There is also a situation with this collection where the collection variables that I save sometimes revert every couple weeks with no evidence in the change log of the collection as to how (similar behavior). Could be related?

**Comment by timbochamp** [comment]
Hi @boylec, thanks for reporting. This sounds similar to #10862, so I'm going to close and open a bug there. Could you submit logs and a HAR file if you're able to reproduce this again?

You can refer to these articles on how to collect the logs:

https://support.postman.com/hc/en-us/articles/360038234154-How-to-generate-a-HAR-file-
https://support.postman.com/hc/en-us/articles/360047765713-Where-can-I-find-logs-for-the-Postman-Application-

and where to send them:
https://support.postman.com/hc/en-us/requests/new

Please feel free to comment if you feel the use case isn't the same as #10862, and I can reopen this at the same time
