### ISSUE TITLE
Desktop 9.16 rendering issue - gray screen

### ISSUE THREAD

**Issue by vizakgh** [a85/POSTMan-Chrome-Extension#10911]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

only menu bar and gray screen are visible

hardware acceleration disabled

### Steps To Reproduce

1. open history tab or wait ~1-3 mins on any request tab
2. menu bar and gray screen are visible

### Screenshots or Videos

![Screenshot 2022-05-13 122205](https://user-images.githubusercontent.com/44437566/168253480-e5e7a985-b556-41d3-b055-51e75cc0b46a.jpg)

### Operating System

Win11 10.0.22000 Build 22000

### Postman Version

v9.16.0

### Postman Platform

Postman App

### Additional Context?

hardware acceleration disabled
CPU AMD Rizen
NVIDIA RTX2060 driver 472.39

**Comment by jviotti** [comment]
Thanks a lot for the report. I'll merge this ticket with https://github.com/postmanlabs/postman-app-support/issues/5980 so we can continue to discussion there!
