### ISSUE TITLE
Automatically applying changes to collections doesn't clear API validation issues

### ISSUE THREAD

**Issue by boylec** [a85/POSTMan-Chrome-Extension#10916]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

This has been happening to me for months.

I have an OpenAPI definition and connected Documentation and Test collections to that definition.

When I run validation against either collection Postman indicates that there are issues.

The suggested changes don't appear to actually be changing anything in the the request that is being detected as invalid. I apply the recommended changes anyway and rerun validation against the underlying collection and it still shows the same issues and fix suggestions.

### Steps To Reproduce

This is non-trivial to reproduce. I can provide more info if desired, please let me know what would be useful/required.

### Operating System

macOS

### Postman Version

9.18.2, UI: 9.18.2-ui-220511-0750, Desktop Platform Version: 9.16.0 (9.16.0)

### Postman Platform

Postman App

### Additional Context?

<img width="221" alt="image" src="https://user-images.githubusercontent.com/8148174/168860669-e40602b0-fd9d-4e13-82f4-86f17bb89252.png">

# OpenAPI 3.0 definitions/schemas
```yml
  /checkout/guest:
    post:
      summary: "Guest Checkout"
      operationId: guest-checkout
      parameters:
        - in: cookie
          name: "TV-Cart-ID"
          schema:
            type: string
          required: false
      tags:
        - checkout
      requestBody:
        description: A guest checkout request
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/GuestCheckoutRequest"
            examples:
              GenericGuestCheckoutRequest:
                $ref: "#/components/examples/GenericGuestCheckoutRequest"
components:
  schemas:
    CheckoutRequest:
      type: object
      required:
        - quoteId
      properties:
        quoteId:
          type: string
    GuestCheckoutRequest:
      allOf:
        - $ref: '#/components/schemas/CheckoutRequest'
        - type: object
          required:
              - creditCardPaymentProfileId
              - shippingAddressId
          properties:
              emailAddress:
                type: string
              creditCard:
                $ref: '#/components/schemas/CreditCard'
              mailingAddress:
                $ref: '#/components/schemas/MailingAddress'
    CreditCard:
      type: object
      required:
        - billTo
        - cardNumber
        - expirationDate
      properties:
        billTo:
          $ref: '#/components/schemas/BillingAddress'
        cardNumber:
          oneOf:
            - type: string
              pattern: ^(\d*)$
            - type: string
              pattern: ^(XXXX\d\d\d\d)$
        expirationDate:
          type: string
          pattern: ^([0-9][0-9][0-9][0-9]-(0[1-9]|1[0-2]))$
        cardType:
          type: string
          enum: [visa,mastercard,americanExpress,discover,JCB,dinersClub]
        cardCode:
          type: string
          nullable: true
        isExpired:
          type: boolean
    Address:
      type: object
      properties:
        name:
          type: string
          nullable: true
        line1:
          type: string
          nullable: true
        city:
          type: string
          nullable: true
        region:
          type: string
          nullable: true
          pattern: ^([A-Z][A-Z])$
        postalCode:
          type: string
          pattern: ^(\d\d\d\d\d)$
        company:
          type: string
          nullable: true
        phoneNumber:
          type: string
          nullable: true
          pattern: ^(\d\d\d\d\d\d\d\d\d\d\d?)$
        faxNumber:
          type: string
          nullable: true
          pattern: ^(\d\d\d\d\d\d\d\d\d\d\d?)$
        country:
          type: string
          nullable: true
          enum: [US, null]
        line2:
          type: string
          nullable: true
        line3:
          type: string
          nullable: true
    MailingAddress:
      allOf:
        - $ref: '#/components/schemas/Address'
        - type: object
          required:
            - name
            - line1
            - city
            - region
            - postalCode
            - phoneNumber
            - country
```

# Example request body failing validation
```json
{
  "quoteId": "ABZEF1234A",
  "emailAddress": "test@example.com",
  "creditCard": {
    "billTo": {
      "postalCode": "75167"
    },
    "cardNumber": "4111111111111111",
    "expirationDate": "2027-10"
  },
  "mailingAddress": {
    "name": "Joe Schmoe",
    "line1": "123 Preston Rd",
    "city": "Garland",
    "region": "TX",
    "postalCode": "75167",
    "phoneNumber": "5555551234",
    "country": "US",
    "company": "True Velocity",
    "faxNumber": "5555551234",
    "line2": null,
    "line3": null
  }
}
```

UI view screenshot of infinite invalid loop. Applying recommended changes does not "clear" the request from being marked as invalid on subsequent validation runs. In addition it does not appear that the recommended changes are actually making any changes to the existing body.
<img width="1909" alt="image" src="https://user-images.githubusercontent.com/8148174/168862054-0d8c12ec-a5c4-4677-a5b7-95bdc570e884.png">

**Comment by VShingala** [comment]
@boylec Issue seems to be with the Specification provided. If you take a look at `GuestCheckoutRequest` schema here, there are 2 required properties mentioned here named `creditCardPaymentProfileId` and `shippingAddressId`, but under `properties` no definition for them is provided.

This makes it an invalid schema as any required field should have their definition mentioned. So validator reports collection request/response body as invalid no matter the situation.

You can fix the issue by either removing these properties from `required` or mentioning them under properties with proper definition.
