### ISSUE TITLE
new request: cannot enable Authentification: "this request does not use any authorization"

### ISSUE THREAD

**Issue by ThomasGugler** [a85/POSTMan-Chrome-Extension#10921]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

setup a new grpc call and want to set jwt bearer token: 
Type of Authorization is greyed out..

### Steps To Reproduce

1. New grpc Request
2. Click Authorization Tab
3. Try to Change Authorization: not possible

### Screenshots or Videos

![grpc](https://user-images.githubusercontent.com/9783599/169022669-f3a7f295-a13d-4c3e-b064-b03c474cfdb3.jpg)

### Operating System

Windows

### Postman Version

9.18.2

### Postman Platform

Postman App

**Comment by timbochamp** [comment]
Thanks for reporting, @ThomasGugler. I'll log an issue to investigate if this is bugged or something that needs more effort with grpc still being in beta. We'll report back with an update!

**Comment by appurva21** [comment]
@ThomasGugler You will need to configure the certificates before setting the Authorization for that request. To add the certificate you can:
- Click the "Add Certificate" button under the Authorization tab, or
- Directly got to - Gear Icon on the top right -> Settings -> Certificate tab

**Comment by JohannWeging** [comment]
I have the same problem. I run a local development setup which runs without TLS. It would be nice to not require a self signed certificate. This just complicates the setup off the local environment.

As a workaround for bearer token you can just set the metadata to `authorization: Bearer <token goes here>`.

**Comment by codenirvana** [comment]
This is fixed with the latest version of the Postman app.
You no longer need to configure certificates to add authorization details.
