### ISSUE TITLE
macOS application type

### ISSUE THREAD

**Issue by stlr00** [a85/POSTMan-Chrome-Extension#10923]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

macOS think, that m1 Postman application is a IOS application.

### Steps To Reproduce

1. Open "about this mac"
2. Storage
3. Programs section

### Screenshots or Videos

<img width="1073" alt="image" src="https://user-images.githubusercontent.com/61075639/169032384-b48f9f8e-65de-4d56-a8d8-e52cf79c3daa.png">

### Operating System

macOS

### Postman Version

9.19.2

### Postman Platform

Postman App

**Comment by jviotti** [comment]
Very interesting! Thanks for catching this. I can indeed reproduce:

<img width="1073" alt="Screen Shot 2022-05-18 at 09 21 36" src="https://user-images.githubusercontent.com/2192773/169048626-2bb63e0c-eab0-4555-932c-b79315bc7228.png">

Not sure what causes the OS to think this. It seems like it also thinks that some apps I have, like VLC, are also iOS apps, while correctly detects other ones as Apple Silicon.

**Comment by jviotti** [comment]
There is probably a setting in the `Info.plist` that certain apps use, while others don't. I'll run some comparisons later and post my findings here.

**Comment by stlr00** [comment]
Any news?

**Comment by stlr00** [comment]
Still any news?

**Comment by jviotti** [comment]
@dsanders11 Can you check if this is reproducible with arbitrary Electron apps? If so, sounds like an easy upstream fix

**Comment by stlr00** [comment]
Fixed. System now recognized it like "Apple chip"
