### ISSUE TITLE
CA Certificate for proxy feature is not valid for golang

### ISSUE THREAD

**Issue by OlivierMary** [a85/POSTMan-Chrome-Extension#10926]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

The certificate generated for proxy feature is not valid for golang.

Cause it's not valid for asn1 RFC.

### Steps To Reproduce

You can checks the step in my thread in golang repository: https://github.com/golang/go/issues/52964

### Operating System

macOs

### Postman Version

9.18.2

### Postman Platform

Postman App

### Additional Context?

RFC 5280: https://datatracker.ietf.org/doc/html/rfc5280#section-4.1.2.6

```
Legacy implementations exist where an electronic mail address is
   embedded in the subject distinguished name as an emailAddress
   attribute [[RFC2985](https://datatracker.ietf.org/doc/html/rfc2985)].  The attribute value for emailAddress is of type
   IA5String to permit inclusion of the character '@', which is not part
   of the PrintableString character set.  emailAddress attribute values
   are not case-sensitive (e.g., "subscriber@example.com" is the same as
   "SUBSCRIBER@EXAMPLE.COM").
```

so the email must be the field emailAddress which is in IA5String, and not in the subject.

**Comment by timbochamp** [comment]
Thanks for reporting, @OlivierMary. I've logged a bug for the team to investigate. We'll relay any updates or should we need any other information!

**Comment by tgoodsell-tempus** [comment]
@timbochamp any updates on the investigation into this issue?

**Comment by timbochamp** [comment]
Hi @tgoodsell-tempus, this is unfortunately a lower priority for our team to take up at the moment. We'll relay any updates along when it's resolved. Apologies for the inconvenience here!
