### ISSUE TITLE
"Design an API in a minute" Bootcamp lesson suddenly stops

### ISSUE THREAD

**Issue by mariuskuehnast** [a85/POSTMan-Chrome-Extension#10929]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

When you get to 56% of the "Design an API in a minute" lesson, the lesson does not continue at the "Switch the environment" step after you have switched the environment to the "App Status Checker" environment. There are no more prompts guiding you through the lesson.

### Steps To Reproduce

1. Start the "Design an API in a minute" lesson from the Bootcamp menu at the bottom right of the screen
2. Follow the instructions until you progress to 56% ("Switch the environment")
3. Switch the environment to "App Status Checker"
4. The lesson does not continue

### Operating System

Windows 10

### Postman Version

9.19.2

### Postman Platform

Postman App

**Comment by timbochamp** [comment]
Thanks for reporting, @AnonymousOctopus235. I'm able to reproduce the same and have logged a bug for the team to investigate. We'll relay updates here!

**Comment by vankad24** [comment]
The bug still exist. In "Design an API in a minute" I can get only 38%. I click "Next" and guiding prompts disappear.

**Comment by ChrisLane** [comment]
I've experienced this in both 'Design an API in a minute' and 'Design an API' now, 2 of 2 bootcamp tutorials that I've tried.
Not being able to complete a tutorial is a rather frustrating experience.

Reproduced in version 10.10.6 and on the web app.

**Comment by arlemi** [comment]
Hey there,

I'm closing this issue as the Bootcamp is not available in the app anymore from the March 2023 (v10.12) release.

If you're interested in more Postman training courses here's a few resources you can check out:
-  [Postman Quickstarts](https://quickstarts.postman.com/) 
-  [Postman Academy](https://academy.postman.com/)
- [Postman Intergalactic webinars](https://www.postman.com/events/intergalactic/)
