### ISSUE TITLE
WebSocket subprotocol option is not available can you  add this feature to the current version 

### ISSUE THREAD

**Issue by vinothkrstatiq** [a85/POSTMan-Chrome-Extension#10924]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

https://github.com/mobilityhouse/ocpp
in the above link 
async def main():
   async with websockets.connect(
       'ws://localhost:9000/CP_1',
        subprotocols=['ocpp2.0.1']
   ) as ws:
you can see sub protocol is used this is very importtant 

### Describe the solution you'd like

u can refer about WebSocket sub protocols 

### Describe alternatives you've considered

no alternative

### Additional context

cd

**Comment by timbochamp** [comment]
Hi @vinothkrstatiq, from https://github.com/postmanlabs/postman-app-support/issues/9997#issuecomment-867541855 in #9997, subprotocols should be implemented. I believe you can use the `Sec-WebSocket-Protocol` header with value to negotiate the subprotocol with the server.

If that still isn't working, can you outline with reproducible steps your use case?

**Comment by vinothkrstatiq** [comment]
@timbochamp  i found the answer thanks a lot
