### ISSUE TITLE
Graph API request in Postman App

### ISSUE THREAD

**Issue by MojoMoe** [a85/POSTMan-Chrome-Extension#10930]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

This Graph API request fails in postman (some other Graph API requests are working fine in postman) whereas it works fine in Graph Explorer:

GET https://graph.microsoft.com/v1.0/users?$filter=Department eq 'Finance'

{
    "error": {
        "code": "Authorization_RequestDenied",
        "message": "Insufficient privileges to complete the operation.",
        "innerError": {
            "date": "2022-05-20T17:00:59",
            "request-id": "96c34f44-946c-45d4-a2b1-fbc7b1a1eab6",
            "client-request-id": "96c34f44-946c-45d4-a2b1-fbc7b1a1eab6"
        }
    }
}

I forked Microsoft Graph and setup my environment with the right info for my Azure AD tenant. Also made sure the API permissions have been consented in Azure AD for the app I registered for this.

### Steps To Reproduce

In Postman application for Windows (11)
Microsoft Graph > Delegated > Users > Get users $filter

### Screenshots or Videos

![Screenshot 2022-05-20 180622](https://user-images.githubusercontent.com/34813181/169578147-e83aaf73-cecf-4e0c-9acd-09212116145d.jpg)

### Operating System

Windows 11

### Postman Version

 v9.19.3

### Postman Platform

Postman App

### Additional Context?

The request works fine in graph Explorer:

https://developer.microsoft.com/en-us/graph/graph-explorer

**Comment by timbochamp** [comment]
Hi @MojoMoe, thanks for reaching out. I think this would fall more into a support request for Microsoft Graph if it's to do with your access token settings within Azure/their platforms (found this with some specific config settings that might need to be done for example: 
https://docs.microsoft.com/en-us/answers/questions/197819/34insufficient-privileges-to-complete-the-operatio.html

Searching/posting there or our community site (https://community.postman.com/) to determine whether this is a configuration issue within Postman like a matter of needing to refresh your auth token within Postman or some other step would be the next course to follow.

I'm going to close this out if you could go through those channels first. Feel free to comment with more specific steps if you're able to successfully make this call using a curl in your terminal, while unable to within Postman using the same auth token, and we'd be able to investigate more to log a bug in that case.
