### ISSUE TITLE
Workspace overview shows wrong information

### ISSUE THREAD

**Issue by mariuskuehnast** [a85/POSTMan-Chrome-Extension#10932]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

When returning to a workspace of your team after viewing a public workspace, the "Workspace details" window (info icon at top right of workspace overview) shows the creator of the public workspace under "Created by" on your own workspace.

### Steps To Reproduce

1. Click explore in navigation bar
2. Select a public collection such as the Salesforce APIs
3. Return to your own workspace by clicking "Workspaces" in the navigation bar and selecting one of your own workspaces
4. On the workspace overview page, click the info icon at the top right ("Workspace details")
5. "Created by" shows the creator of the public workspace you visited previously

### Operating System

Windows 10

### Postman Version

9.19.3

### Postman Platform

Postman App

**Comment by akshay-kulkarni-03** [comment]
@AnonymousOctopus235 thanks for reporting! We are triaging this issue from our side and will keep this thread updated on the progress.

**Comment by akshay-kulkarni-03** [comment]
@AnonymousOctopus235 we have identified the root cause of this issue and are currently working on fixing it. Will provide an update once the fix is rolled out.

**Comment by akshay-kulkarni-03** [comment]
@AnonymousOctopus235 this issue has been fixed. If you're using app, would request you to update to the latest version. Closing this issue, feel free to re-open if it still persists.
