### ISSUE TITLE
Adding New API to a Branch with Existing APIs

### ISSUE THREAD

**Issue by jjkirby** [a85/POSTMan-Chrome-Extension#10931]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

So in my personal workspace, I have set up a Github connection where I import some existing OpenAPI files into the workspace.

Next, I want to use the Postman editor to create a new API in that same workspace and then sync it back to the repo/branch of the other APIs I imported. I cannot make a Github connection for the Postman-generated API because Postman claims the branch is in use by another API? 

### Describe the solution you'd like

 If I have a Team shared workspace where some developers use external authoring tools and commit to the repo, then another uses Postman to author,  I think you should be able to sync to that branch.  I understand conflicts potentially but you could always as "are you sure?" to let the developer decide.

### Describe alternatives you've considered

I delete the imported APIs/Collections in Postman (remove connection) then add the new API authored in Postman to the branch

**Comment by abhijitkane** [comment]
@jjkirby Thanks for the detailed explanation. This is a workflow we're reviewing, and I'll try to share an update soon. If you're part of a Postman team, could you reach out to help@postman.com (referencing this issue) with more information about the different collaborators on your API?

**Comment by shashankawasthi88** [comment]
@jjkirby can you please elaborate on how you folks structure the APIs in your repository? It will help us design the system better. You can schedule a call with me using [this](https://calendly.com/shashank-awasthi/v10-feedback?month=2022-09) link. We can discuss the gaps in detail.

**Comment by shashankawasthi88** [comment]
@jjkirby this should now be solved as long as you maintain different folders in the same branch. Closing this for now, feel free to reopen if you still have issues.
