### ISSUE TITLE
gRPC does not support the proxy

### ISSUE THREAD

**Issue by cnjack** [a85/POSTMan-Chrome-Extension#10934]
### Is there an existing issue for this?

- [ ] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Can not use the proxy when call a gRPC service

### Steps To Reproduce

N/A

### Operating System

macOS

### Postman Version

Version 9.19.3

### Postman Platform

Postman App

### Additional Context?

N/A

**Comment by cnjack** [comment]
@shamasis Can you update the status for this one?

**Comment by codenirvana** [comment]
@cnjack no ETA just yet but, we will integrate the proxy configuration soon.

As a workaround, try setting the `https_proxy` or `http_proxy` [environment variables](https://github.com/grpc/grpc/blob/master/doc/environment_variables.md#grpc-environment-variables) to configure your proxy.

You can set these variables globally or via CLI:
`http_proxy=http://127.0.0.1:8080 open /Applications/Postman.app`.

**Comment by cnjack** [comment]
> @cnjack no ETA just yet but, we will integrate the proxy configuration soon.
> 
> As a workaround, try setting the `https_proxy` or `http_proxy` [environment variables](https://github.com/grpc/grpc/blob/master/doc/environment_variables.md#grpc-environment-variables) to configure your proxy.
> 
> You can set these variables globally or via CLI: `http_proxy=http://127.0.0.1:8080 open /Applications/Postman.app`.

Thank you for your response, the environment set is very helpful for me.

**Comment by johnzheng1975** [comment]
Step 1: set env in windows 


Step 2 run Postman-win64-9.21.3-Setup.exe

Step 3, still fail.
Couldn’t use server reflection
There was an error while loading the services and methods using server reflection. Make sure you are using the correct URL and have the certificates configured (if required). Go through 
 to know more.

14 UNAVAILABLE: No connection established

**Comment by codenirvana** [comment]
@johnzheng1975 can you try with the lowercase variable name and prefix the value with the protocol?

e.g, `http_proxy=http://web-proxy.austin.hp.com:8080`

**Comment by cnjack** [comment]
@codenirvana I found the proxy is working now

**Comment by codenirvana** [comment]
@cnjack Yes, thanks for the confirmation!

The custom proxy configuration will be honored while invoking gRPC methods, we'll add support for system proxy soon.
