### ISSUE TITLE
Ability to save response to environment in the WebSocket requests

### ISSUE THREAD

**Issue by Uckpa** [a85/POSTMan-Chrome-Extension#10943]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

Usual response after sending a message via using WebSocket request:
```
{
    "data": "test",
    "session_id": 1234567890,
    "transaction": "any_text"
}
```
It willl be great to save data/session_id/transaction to environment variables. Like it was done for usual POST/GET/... etc requests in the Tests section.
```
e.g.
var jsonDataResponse = pm.response.json();
pm.environment.set("transaction", jsonDataResponse.transaction);
```

### Describe the solution you'd like

Create a section where users can use JS to save/check response

**Comment by codenirvana** [comment]
Duplicate of #10181

@Uckpa we are actively working on adding support for scripting, please follow the original feature request for more updates.
