### ISSUE TITLE
Postman 3.0.0.5 Corrupted Collection

### ISSUE THREAD

**Issue by ross-p** [a85/POSTMan-Chrome-Extension#1094]
So I have a collection with ~ 85 requests in it, organized into ~ 15 folders.

I left Postman running all night, when I came in this morning my entire collection was corrupted.

Only ~ 3 folders remained.  All of the requests were in the root collection, in random order, some of them had even changed names.

I tried to download the latest copy from the server, but that version was also corrupted.

Somehow, Postman not only corrupted my local collection while I was AFK, but it also managed to auto-sync that up and corrupt my "save" on the server.

The corruption issue is bad enough, but auto-save?  I have now lost hours of work trying to reorganize this and verify that the settings of all 85 of these requests are still correct.

Apparently I need to create local backups since you decided to enable auto sync in a buggy implementation.  I did figure out how to disable sync, but the damage is done.

IMO sync should not be enabled by default until you can make sure you aren't corrupting people's work, it does more harm than good.

**Comment by ross-p** [comment]
Follow-up: Some of the requests were definitely deleted from the collection.  :(

**Comment by abhijitkane** [comment]
@ross-p Can you send an email to help@getpostman.com with your username / email?

**Comment by ross-p** [comment]
@abhijitkane done, subject = "Data Corruption issue #1094"

**Comment by nico-incubiq** [comment]
I experienced the same issue. Go to Postman Settings, choose **Force sync**, there will be a **conflict** during sync operation. Fix the conflict by selecting values on the **server**, and then you should get all your previous requests back after a while.

**Comment by cjthomp** [comment]
Same thing happened to me. I'm pissed. This is my livelyhood you're messing with. As of now I regret purchasing your product, all previous goodwill wiped away with this forced upgrade.

**Comment by ross-p** [comment]
@cjthomp It hasn't happened to me since the first time.

However I've been very cautious to make local backups of every revision that I actually want to save, just in case it happens again.  Highly recommend you do the same.

I disabled auto-sync, which maybe is why it hasn't happened to me; it could be something in the sync that causes the corruption.  Pure speculation.

**Comment by cjthomp** [comment]
Strongly suspect it is, I have been getting nearly continuous sync errors over the last couple days. 

Smells like another product compromised to monetize (via the team sub)

**Comment by sobtiankit** [comment]
@cjthomp Can you send us an email at help@getpostman.com with your username? We'll try and help you out.

**Comment by Watje** [comment]
Same happened to me. Couldn't Sync for several days, then this morning it sync'ed and corrupted my collections.

Just like @ross-p I turned off sync, but for whatever insane logic decided to give it one more try and enable sync again. Everything came back as I left it yesterday.

Magical.

**Comment by abhijitkane** [comment]
A lot of stability and performance improvements have been made to Sync. The latest version is v3.0.1.

You can force an update by going to chrome://extensions, enabling 'Developer Mode', and clicking 'Update extensions now'.
