### ISSUE TITLE
New Integration Request - <product name>

### ISSUE THREAD

**Issue by adamatkinso** [a85/POSTMan-Chrome-Extension#10946]
### Describe your current workflow

integrating various app apis

### Describe your ideal workflow

clickup > aircall > clickup

### Describe alternatives you've considered

airtable, hubspot, freshsales, agilecrm, monday

### Additional context

the clickup api is crap

**Comment by shashankawasthi88** [comment]
@adamatkinso please reopen the ticket with additional details. Postman integrations are usually for sending data to and fro from Postman to complete your developer workflows involving Postman and some other tool.

**Comment by adamatkinso** [comment]
Thanks. still learning my way around. I wish I found postman 12 months ago.
