### ISSUE TITLE
Allow searching/sorting variable lists

### ISSUE THREAD

**Issue by jsnhsu** [a85/POSTMan-Chrome-Extension#10950]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

I have over a hundred variables defined in either Global or each Environment variable list which shows chronologically but alphabetically.  It's hard to find a single variable to review or modify, etc...

### Describe the solution you'd like

Hopefully, you can add the feature to make each field is sortable or searchable in the variable list.

### Describe alternatives you've considered

Or something like being able to save the sorted variable list.

**Comment by timbochamp** [comment]
Duplicate of #10602
