### ISSUE TITLE
OpenAPI Documentation Validation Indicates Issues Exist but Shows None

### ISSUE THREAD

**Issue by k98kurz** [a85/POSTMan-Chrome-Extension#10954]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Documentation for APIs specified with OpenAPI will show "Issues found" in the Overview tab, even after hitting "Validate Again", but then there are 0 issues shown after clicking "Review Issues".

### Steps To Reproduce

1. Create an API.
2. Fill out an OpenAPI Specification for the API.
3. Create Documentation from the Overview tab.
4. Click "Validate" on the Documentation from the Overview tab.
5. Click "Review Issues".

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/4357561/170770036-eaf777d5-c903-42a0-b379-c9e740c4b1c7.png)
![image](https://user-images.githubusercontent.com/4357561/170770071-c8a6d57a-a5d4-4d5a-9a13-ac2379ffad5f.png)

### Operating System

Linux

### Postman Version

9.19.0

### Postman Platform

Postman App

### Additional Context?

Restarted app twice. Committed and pushed all changes to the Github integrated branch. Problem persists.

**Comment by postman-staff** [comment]
Hey @k98kurz,
Sorry for the inconvenience.

I have tried to replicate this behaviour but was unable to, unfortunately.
Attached is the screen record of what I have tried according to the steps provided.
Could you please check and let me know if I misunderstood the query.

via @VaishnaviChallaPostman | Postman Support

https://user-images.githubusercontent.com/76939396/176404744-2bff1cf1-8c85-47c6-8a50-3ce792a5c4da.mov

**Comment by VaishnaviChallaPostman** [comment]
Hey @k98kurz,
Hope you are doing good!

If you are still facing this issue, could you please submit a ticket here: https://support.postman.com/hc/en-us/requests/new/ with your OpenAPI specification and collection with us if possible, to help us replicate it on our end?
Please mention the GitHub thread number in the subject to help us identify your ticket. 
Thanks!
