### ISSUE TITLE
Please stop using racist language in the postman interface.

### ISSUE THREAD

**Issue by MirandaBrawnerSavannah** [a85/POSTMan-Chrome-Extension#10955]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

I noticed that Postman uses the term "whitelist" in the "Manage Cookies" interface. This term, and its opposite, "blacklist" should not be used. Terms like this are harmful because they associate white with good and Black with bad. Langston Hughes   illustrates this in his essay "That Word Black" [which you can find here.](https://www.sevanoland.com/uploads/1/1/8/0/118081022/that_word_black.pdf) Instead of calling it a whitelist, we can call it an approved list, accepted list, or allowed list. Many companies, like Apple, are already working to make this change to the language they use. [Here's a link](https://help.apple.com/applestyleguide/#/apsg1a3a0436) to Apple's style guide where they urge developers to use "approved", "accept", "permit",  or "allow" instead of "whitelist". In Postman, the button in the cookies tab that says "whitelist domains" could say "add domains to the accepted list". Clicking on this link opens a menu that also needs to be changed. 

### Steps To Reproduce

1. In the app, create a new request.
2. Click on the "Cookies" button.
3. At the bottom of the cookies interface, there is a button that says "whitelist domains".
4. Clicking this button takes you to a "whitelist domains" interface.

### Screenshots or Videos

The cookies button on the request interface.
<img width="1080" alt="Postman Main Menu" src="https://user-images.githubusercontent.com/56093884/170777719-398d042b-d5d8-4dba-9b80-c31fdacf6a42.png">

The "whitelist domains" button on the cookies interface.
<img width="712" alt="Postman Cookies Window 1" src="https://user-images.githubusercontent.com/56093884/170777819-7e53fdda-d414-4533-9ade-d4fcc269e556.png">

The "whitelist domains" interface.
<img width="716" alt="Postman Cookies Window 2" src="https://user-images.githubusercontent.com/56093884/170778023-b85371a5-ee40-4721-b7e9-83292738356b.png">

### Operating System

macOS

### Postman Version

7.21.0

### Postman Platform

Postman App

**Comment by DannyDainton** [comment]
Hey @MirandaBrawnerSavannah

This has been addressed in the later versions of the platform, I can see that you're using version 7 which is two major versions behind the latest one.

Here's the latest documentation for that area of the product. 

https://learning.postman.com/docs/sending-requests/cookies/#accessing-cookies-in-scripts
