### ISSUE TITLE
Error when launching

### ISSUE THREAD

**Issue by zenkiben** [a85/POSTMan-Chrome-Extension#10952]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

How to fix this issue?
![image](https://user-images.githubusercontent.com/33957533/170572220-28e12c7f-7e93-4d16-8fbe-4281fa6ea8d0.png)

### Steps To Reproduce

launching postman

### Operating System

Window

### Postman Version

9.14.0

### Postman Platform

Postman App

**Comment by zenkiben** [comment]
This issue happen when update latest version

**Comment by kamalaknn** [comment]
Hey @zenkiben 

We are unable to replicate this issue from our end. We would need more information to understand the root cause of this issue. Would it be possible to do a debugging session over a call to help us address the issue faster?

**Comment by zenkiben** [comment]
You can see step by step from video.
https://youtu.be/ghQbhqblGJk

**Comment by postman-staff** [comment]
Hi @zenkiben,

Sorry that you are facing issues while updating the desktop application.

Let me know if you have tried clearing the cache and then re-installing the application?
If not, **I'd first recommend ensuring your work is synced:** **https://go.postman.co/me/collections** **before trying the following**

- https://support.postman.com/hc/en-us/articles/360025359014-How-to-resolve-the-Could-not-open-Postman-error-
You'll want to try the steps to remove local data.
Once that's done, re-install the Postman App.

Also let me know if you have tried our web version, which keeps you unblocked in the meantime. If you haven't tried it yet then give it a try ->  go.postman.co

Thanks for letting me know how this goes.

via @Lincimary | Postman Support

**Comment by zenkiben** [comment]
It's run ok.

**Comment by postman-staff** [comment]
Hi **@**zenkiben,

Super glad that all works now as expected!
Thank you for letting us know.

To identify what caused the problem, we would like to have a look and check with the logs.
Could you please submit a support request with a copy of your app logs?

via @Lincimary | Postman Support
