### ISSUE TITLE
Entered XML code example in Collection Documentation Codeblock shown incorrect

### ISSUE THREAD

**Issue by anvarius94** [a85/POSTMan-Chrome-Extension#10951]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

If you will add Codeblock in collection doumentation and fill it by some XML example - this data will be saved incorrectly after saving.

Before saving:
![image](https://user-images.githubusercontent.com/106316102/170483894-9d01229d-3088-45ae-8324-87d2404f39b7.png)

After saving:
![image](https://user-images.githubusercontent.com/106316102/170484030-5eb10846-09e0-4a9a-bac8-7ca5bff2ac50.png)

### Steps To Reproduce

1. Choose any collection
2. Start editing documentation of collection
3. Switch to Postman editor mode if it was not selected by defauld
4. Add Codeblock
5. Fill Codeblock by some valid XML example
6. Press save button
7. Compare saved XML exampel with entered

### Operating System

Windows

### Postman Version

9.19.3 

### Postman Platform

Postman App

**Comment by kamaraj-p** [comment]
hi @anvarius94, thanks for reporting this issue. This is a known issue where we sanitise any un-allowed html tags due to security concerns. We are working on this to better accommodate valid use-cases. Will keep you posted after discussing with the security team.

**Comment by kamaraj-p** [comment]
This issue is fixed in the latest release v10.12.0. Closing this issue, feel free to reopen if required. 🙏
