### ISSUE TITLE
Prescript cannot set the "false" value for a variable

### ISSUE THREAD

**Issue by VeryArine** [a85/POSTMan-Chrome-Extension#10969]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

When I am declaring variables in pre-scripts, they cannot set the "false" value.

### Steps To Reproduce

1. Create a new variable in collection. for example, x.
2. Open a new request tab.
3. Open a pre-script. Use this : pm.collectionVariables.set("x", false);
4. Fill in the url with any value
5. Click to Send button
6. Check the value of the variable x.

### Screenshots or Videos

https://user-images.githubusercontent.com/106680434/171423173-5783757f-cba4-41c5-9e01-0762c964001d.mp4

### Operating System

Windows 10

### Postman Version

9.20.3

### Postman Platform

Postman App

**Comment by malvikach** [comment]
@VeryArine thanks for writing to us about the above issue! This surely is a bug.

**Comment by ashuvyaspm45** [comment]
@VeryArine Thank you for your patience. This issue is fixed in our latest release. Do try it out and let us know if there is any feedback.
