### ISSUE TITLE
Monitors timeout at 60s

### ISSUE THREAD

**Issue by stephanefv** [a85/POSTMan-Chrome-Extension#10963]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Starting ~12:00 GMT on 30 May 2022, all Postman monitor runs usually lasting >60s are failing by timing-out at the 60s mark with a console error: **"Error: callback timed out"**

Previously, monitors would not timeout even when running 70-240s (<5 min monitor timeout limit).  

IMPACT: this new timeout behaviour makes it impossible to run any monitors that require >60s to complete end-to-end.

Note: this only impacts Collections run inside Monitors. Running the same Collection directly via the "Run" command does not lead to any timeout issues.

### Steps To Reproduce

1. Create Collection "TEST_COLLECTION" containing 7x identical requests: GET https://postman-echo.com/delay/10 
(each taking 10s to run)
2. Run the Collection end-to-end. RESULT: no timeout issues.
3. Create Monitor "TEST_MONITOR" using the Collection.
4. Run Monitor. 
5. RESULT: Monitor fails at 60s mark with 2 errors, "Error: callback timed out" and "Run failed"

**Console Log result:**
> 
-- | 9:15:17 | Preparing run.
-- | -- | --
-- | 9:15:17 | Running...
1 | 9:15:20 | Monitor timeout tests started
2 | 9:15:20 | Delay 10s (1)
3 | 9:15:20 | GET https://postman-echo.com/delay/10
4 | 9:15:31 | Delay 10s (2)
5 | 9:15:31 | GET https://postman-echo.com/delay/10
6 | 9:15:41 | Delay 10s (3)
7 | 9:15:41 | GET https://postman-echo.com/delay/10
8 | 9:15:51 | Delay 10s (4)
9 | 9:15:51 | GET https://postman-echo.com/delay/10
10 | 9:16:01 | Delay 10s (5)
11 | 9:16:01 | GET https://postman-echo.com/delay/10
12 | 9:16:17 | Monitor timeout tests finished
13 | 9:16:17 | Error: callback timed out
-- | 9:16:17 | Run failed.

**EXPECTED RESULT: Monitor successfully completes all 7 "Delay 10s" requests in ~70s.**

Monitor settings:
- Regions: Automatically select regions
- Set request timeout: off
- Set delay between requests: off
- All other options: off

### Operating System

macOS

### Postman Version

9.19.3

### Postman Platform

Both

### Additional Context?

Previous issue (2018) indicates monitors have a 5min timeout limit end-to-end: https://github.com/postmanlabs/postman-app-support/issues/5529

**Comment by DivyaMoryani** [comment]
Facing the same issue. Please fix it ASAP. 
Version 9.20.3-220527-0752

Console Log: 
<img width="539" alt="image" src="https://user-images.githubusercontent.com/65155227/171076642-677294f5-7256-4bda-9b57-e0625c736359.png">

**Comment by aman-postman** [comment]
Hi @stephanefv and @DivyaMoryani,

Thanks for reporting the issue. We acknowledge the issue and are working on a fix at the moment. We will update this thread once the issue is resolved.

**Comment by aman-postman** [comment]
The issue should be fixed now. Please feel free to message on thread if the issue still persists on your end for new monitor runs. Thanks again for reporting the issue!

**Comment by DivyaMoryani** [comment]
Fixed, Works for me now! Thank you 😊

**Comment by stephanefv** [comment]
Fixed, thank you!  Closing issue now.
