### ISSUE TITLE
Feature Request : Support for mock gRPC server and stubs

### ISSUE THREAD

**Issue by cdbyrd** [a85/POSTMan-Chrome-Extension#10968]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

I can define mock servers and stub responses for REST endpoints, but I cannot for gRPC.  I end up needing a separate tool to mock gRPC endpoints, despite the fact that we have an enterprise license for Postman and we do this for REST endpoints all the time.  This creates a need for me to have multiple tools, and drives complexity in our developer experience, testing, and CI/CD processes.

### Describe the solution you'd like

Actually, [microcks.io](https://microcks.io/documentation/using/grpc/#:~:text=In%20order%20to%20use%20gRPC,operations%20of%20the%20gRPC%20Service.) has a feature that does pretty much what I would like to see Postman be able to do natively.  I want to be able to provide a protobuf definition file and have Postman generate mock gRPC interfaces, just like it can do if I feed it an OpenAPI specification for REST endpoints.  

I should be able to define stubbed responses that are triggered based on matching values from the requests.  Since all of this is defined in the proto, the construction of stubs should be pretty straight forward to define a default response and to allow autocomplete when building custom responses based on specific requests.

### Describe alternatives you've considered

* [microcks.io](https://microcks.io/documentation/using/grpc/#:~:text=In%20order%20to%20use%20gRPC,operations%20of%20the%20gRPC%20Service.) -- solution backs into a gRPC mock server from a templated REST mock server defined in a postman collection
* [tokopedia/gripmock](https://github.com/tokopedia/gripmock) -- programmatic mocking, but had some issues with protos that contain imports (essentially all protos outside of hello world example)
* [dushanpantic/grpc-server-mock](https://github.com/dushanpantic/grpc-server-mock) -- programmatic mocking
* [trafficparrot.com](https://trafficparrot.com/tutorials/mocking-and-simulating-grpc.html) -- we already pay an enterprise license for Postman, and I can't justify another for something that I think we should get from Postman

### Additional context

I actually think that many people have this same request for GraphQL mock servers as well.  We actually produce both REST/gRPC APIs from all our services.  We define the API in protobuf and transcode REST/JSON into gRPC.  However, we have a need to test both the REST and the gRPC definitions.  Internally, services communicate with gRPC, so the mock servers would save a lot of development time for teams looking to do integration testing without requiring a full deployment of all microservices.  

We use the annotation feature of protobuf allow automatic [transcoding of REST to gRPC](https://cloud.google.com/endpoints/docs/grpc/transcoding) in a proxy constructed from the protobuf definition.  It would be awesome if Postman could take the protobuf, with the REST annotations, and generate both gRPC and REST mock interfaces from the protobuf definitions.

**Comment by appurva21** [comment]
Hey @cdbyrd! Thanks for sharing your use case in detail. We have already started work on this and should have some updates soon. Stay tuned!

**Comment by shamasis** [comment]
Hello @cdbyrd, It will be cool if you give the automatic mocks a spin.

https://blog.postman.com/postman-mocking-magic-for-grpcs/
