### ISSUE TITLE
Inconsistent content format between syncing vs exporting collections

### ISSUE THREAD

**Issue by helloint** [a85/POSTMan-Chrome-Extension#10967]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

I noticed some difference between the exported postman_collection.json and the GitHub Integration auto sync one.
Please see the screenshot for the difference:
<img width="1775" alt="image" src="https://user-images.githubusercontent.com/4143533/171299793-7bbfa550-2a55-40d7-8f30-9fe7bb3a56cb.png">

I hope these 2 files can be consistent, not sure if it is possible.

### Steps To Reproduce

1. I created a test collection, the name is 'integration-test'
<img width="287" alt="image" src="https://user-images.githubusercontent.com/4143533/171299955-915702a3-13a6-407c-a9b2-ecf3fb7b8a90.png">

2. I created a GitHub repo named `postman`, and in the default `main` branch, I upload the collection configuration I export from Postman App. [Here it is](https://github.com/helloint/postman/blob/main/postman/integration-test.postman_collection.json)

3. I created a new branch named `sync`, to let Postman server to sync collection configuration to GitHub, every time someone update the collection on air.

4. I then created a Postman Sync Integration, see configuration below:
<img width="541" alt="image" src="https://user-images.githubusercontent.com/4143533/171300146-b23ca663-818d-4341-8193-a6b94ccaf43e.png">

5. After the integration created, I manually made a change to the Request in Postman App, and I then see the Postman server pushed a commit to my GitHub. Here is the commit: https://github.com/helloint/postman/commit/4f75788aff26d891035d5e9f146337154aa4974a.

Now you can see the difference:
<img width="1705" alt="image" src="https://user-images.githubusercontent.com/4143533/171300329-830e0e4e-49dd-4598-806c-ecdf2c78c1e0.png">

### Operating System

macOS

### Postman Version

9.18.3

### Postman Platform

Postman App

### Additional Context?

The issue was originally post here https://github.com/postmanlabs/postman-app-support/issues/10820

**Comment by saialekhya-001** [comment]
Hi @helloint,
I'm Alekhya from the Integrations team.

We appreciate your engagement with the [GitHub issue](https://github.com/postmanlabs/postman-app-support/issues/10820) you opened.

We've explored this scenario ourselves and have achieved success in updating the collection JSON on remote platforms and seamlessly importing it into Postman. Our approach involves selecting the 'Replace' option to effortlessly update existing collections in Postman, as illustrated in the screenshot below:
![Screenshot](https://github.com/postmanlabs/postman-app-support/assets/113347652/3a11a494-b768-4d2d-82b2-34a071bc297c)

These are the steps we have followed:
- Create collection backup integration
- Go to the remote repository, copy and update the collection JSON in a text editor.
- Copy the updated collection data.
- Come to Postman, select import, past the raw file copied, and click Import.
- Choose the Replace option when prompted.
- Verify the existing collection is updated with the changes.

If you still encounter any challenges related to differences in the collection JSON keys, please don't hesitate to reach out. We're here to assist you and ensure a smooth experience. Also, do let us know if you have any use cases that will have concerns related to differences in the collection JSON keys.

**Comment by shubhbhargav** [comment]
Closing it off for now. @helloint Feel free to let us know if you still face any issue related to this.

**Comment by helloint** [comment]
Finally get a chance to go back and review this issue. I tried export the collection and enviroment from Postman app, and compare to the file I had from 2 years ago, and it is great to notice the major issue being resolved, just found 2 remain small issue:
1. The collection.json now has `"_exporter_id": "1465xxxx"` in "info". This is understandable, but I will prefer to remove it before submit to Git.
2. The environment.json has:
```
	"_postman_exported_at": "2024-04-11T02:49:16.554Z",
	"_postman_exported_using": "Postman/10.24.17"
```
Of cource I will also manually remove it before submit file to Git...
