### ISSUE TITLE
Option to set default tab that opens when selecting a Request

### ISSUE THREAD

**Issue by bombillazo** [a85/POSTMan-Chrome-Extension#10961]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

When opening a Request, it defaults to the params or query depending on the type of HTTP method. This makes editing or using multiple requests very tedious if the tab one uses most of the time is any other tab (such as the body tab). Even after saving the request with the desired tab in view, closing it, and opening it later the view reverts to the default.

### Describe the solution you'd like

Different from #2086 which proposes to have the currently hardcoded default tab be arbitrarily changed to another tab (and not configurable in the app), this solution proposes having an inheritable global, per collection, and/or per request option to override the default tab that is shown when opening a request. This way one could for example select "Body > Raw" as the preferred way to open a POST request. It would be great if one can set the default per HTTP methods as well (Body tab for POSTs, Params for GET, etc).

**Comment by Kanika637** [comment]
I would like to work on this, could you please guide me toward it @bombillazo

**Comment by andrew-y0u** [comment]
Why is it closed? It would be nice to have!
