### ISSUE TITLE
Clicking on a Request in Workspace does nothing on M1 Macbook Pro

### ISSUE THREAD

**Issue by mitchhf** [a85/POSTMan-Chrome-Extension#10966]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed
Could be a dupe of: https://github.com/postmanlabs/postman-app-support/issues/10460

*Canary build does work!*
```
Version 9.20.3
UI Version: 9.20.3-ui-220527-0647
Desktop Platform Version: 9.19.0 (9.19.0)
```
-
### Describe the Issue

On a brand new M1 Macbook Pro attempting to bring the editing part of the screen doesn't work.  Here's a screenshot that shows the page.  Clicking on a request (i.e. List Users) doesn't do anything.   Clicking on "Open Workspace Overview" or "Get"  or the other 2 icons' do anything either.

<img width="1171" alt="Screen Shot 2022-05-31 at 9 47 54 AM" src="https://user-images.githubusercontent.com/12447276/171189108-f78f5785-d148-4785-8c0c-7cb66c5ff6bb.png">

### Steps To Reproduce

Bring up Postman on an M1 Macbook Pro
Bring up existing workspace
Click on a request.
The request should come up and be editable but this does not happen.

### Operating System

macOS 12.4 (Apple M1 Max)

### Postman Version

Version 9.20.3

### Postman Platform

Postman App

### Additional Context?

Web app works fine on this machine.  This problem is only on the macos app.

**Comment by jviotti** [comment]
Thanks a lot for reporting this! Let's keep the discussion focused on the other ticket, as they are similar enough to risk discussing the same things twice! 

I see you already linked this issue to the other one, which is great, as we will be able to see this one in there too!
