### ISSUE TITLE
Very heavy battery usage!!

### ISSUE THREAD

**Issue by Samraw003** [a85/POSTMan-Chrome-Extension#10965]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Postman app is draining my battery very very fast!!!

### Steps To Reproduce

Just run the app 

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/13114616/171178399-83c2e4f6-5839-4327-b04d-b9e2c967a1e0.png)

### Operating System

Windows 11 PRO

### Postman Version

9.19.3 

### Postman Platform

Postman App

**Comment by kamalaknn** [comment]
Hey @Samraw003 

Could share give us some more details to help us understand what could be causing this? Are you working on a workspace that has many or large collections? Are you using collection runner in the background while you are seeing this?

It would be helpful if you could capture a screen recording of what the Postman app is doing while you are experiencing high battery usage. Please attach screen recording and logs from ` View -> Developer -> View logs in Explorer` to `help@postman.com` so I can take a deeper look.

**Comment by NathanD19** [comment]
Getting the same issue on win 11 pro. Postman is open/minimized. Using large workspace with many collections.

![image](https://user-images.githubusercontent.com/26264463/173169558-580afeb4-80e2-46ac-9583-b225ee7be9ea.png)

**Comment by Samraw003** [comment]
Hi,

I have 3 collections with 6-7 requests in each, however, these were not
active. Resultset of each was quite small.

Apologies, I cannot share the developer log as I am using the web
version now and have already installed the app.

Regards



Digital Transformation of QMS & Processes


*Sammeer*
Founder
+91 9 <+91+9719275759>967961616
***@***.***
www.Optimium.in



[image: https://www.linkedin.com/in/sammeersraawat/]
<https://www.linkedin.com/in/sammeersraawat/>

**Comment by kamalaknn** [comment]
@NathanD19 Could you share logs from `View -> Developer -> View logs in Explorer` with us by email to `help@postman.com`? Do share this issue link in the email so we can follow up with this.

**Comment by NathanD19** [comment]
Thanks @kamalaknn. I've sent through the logs.

**Comment by kamalaknn** [comment]
@NathanD19 @Samraw003 We have pushed a fix for this in 10.18. Could you update your app and try it out? Let us know if you still see any issues.

**Comment by eklect** [comment]
I am also having this issue. It drained my battery today and didn't respect my system (laptop) going to sleep when I closed my lid. it did about 30% of background computing while the laptop was in my bag and drained about 25% of my charge. However, nothing was running in Postman that should have caused this issue. 

This bug severely pissed me off as I had to cut a meeting short because I had no juice and was traveling without power, and the Postman Desktop App was the culprit.  Please fix this.

Otherwise, give me your code from 2014, that shit worked flawlessly.

**Comment by numaanashraf** [comment]
@eklect I understand the frustration this has caused. Could you share your app logs to understand what might have caused this on your device? 

You can get the logs via the steps detailed here - https://support.postman.com/hc/en-us/articles/360025298633-How-to-get-logs-from-the-Postman-Desktop-app#h_01G396RG1PATWM520KV442RCSJ
