### ISSUE TITLE
Setting Environment variables doesn't work

### ISSUE THREAD

**Issue by ocot2** [a85/POSTMan-Chrome-Extension#1097]
Trying to set Environment variables via right-click --> Set as:  The values don't get transferred to the appropriate variable within the environment

**Comment by abhijitkane** [comment]
Are you copying values from the Response pretty-view? If yes, we're aware of this problem and will push a fix in the next release.

**Comment by ocot2** [comment]
Yes I was, sorry my search didn't anything fruitful.  Thanks.

On Mon, Jun 1, 2015 at 12:44 PM, Abhijit Kane notifications@github.com
wrote:

> Are you copying values from the Response pretty-view? If yes, we're aware
> of this problem and will push a fix in the next release.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/a85/POSTMan-Chrome-Extension/issues/1097#issuecomment-107631618
> .

## 

Travis R. O'Connor

Associate Solutions Engineer

Brightcove, Inc. http://www.brightcove.com/

290 Congress St., Boston, MA 02110

P: 617 500 4947

**Comment by MrBan** [comment]
As a temporary workaround you can switch from Pretty-view to Raw-view. It works

**Comment by abhijitkane** [comment]
@ocot2 Can you confirm this fixed in v3.0.4?

**Comment by ocot2** [comment]
Did this reappear?  I'm having problems having {{VARIABLE}} get pulled from the Environment to put into the call.  https://oauth.brightcove.com/v3/client_credentials?origin_account_ids={{account_id}} didn't work but when I replaced the variable to be https://oauth.brightcove.com/v3/client_credentials?origin_account_ids=1234567890, it works.

**Comment by abhijitkane** [comment]
@ocot2 Are you entering this in the main URL bar, or in the Oauth2 form?

**Comment by ocot2** [comment]
In the main URL bar, not the OAuth2 form.  I found with one of my environments, variables aren't being pulled properly into either the Pretty-View Body or main URL bar.  Only hardcoding the values was I able to get success.

**Comment by abhijitkane** [comment]
Is this only happening for one environment? Can you try adding a global variable and see if that's replaced?

Also, what version of Postman are you on?
