### ISSUE TITLE
X-mock-match-request-body not matching examples - not working with Content-Type = application/x-www-form-urlencoded

### ISSUE THREAD

**Issue by DSinghXM** [a85/POSTMan-Chrome-Extension#10973]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

This issue is similar to closed issue https://github.com/postmanlabs/postman-app-support/issues/8335#issue-600146124
but as disused in the closed issue it only works for Content-Type= 'Content-Type: application/json; charset=utf-8'
Currently we have Content-Type= application/x-www-form-urlencoded
And passing x-mock-match-request-body as true returns with following error. I already checked the content-type and other headers are same on both request and example.
{
    "error": {
        "name": "mockRequestNotFoundError",
        "message": "Double check your method and the request path and try again.",
        "header": "No matching requests"
    }
}

### Steps To Reproduce

Create a request with content-Type as application/x-www-form-urlencoded
pass x-mock-match-request-body as true and match with existing example. 

### Operating System

windows

### Postman Version

9.20.3

### Postman Platform

Postman App

**Comment by jlpoveda-jt** [comment]
Hello there! Any update on this? Thanks!

**Comment by Dhembla** [comment]
@DSinghXM I tried body matching for content-Type as application/x-www-form-urlencoded and it is working as expected. You can check the video for the same [here](https://drive.google.com/file/d/1cZCeNXFjHafQLspTFA5upreHuLmzkzY_/view?usp=sharing).
Can you please check if you are adding the content-type header in examples?

**Comment by Dhembla** [comment]
@DSinghXM Can you please verify if you are still facing the issue?

**Comment by Dhembla** [comment]
@DSinghXM, I am closing the issue; please feel free to reopen it if you still face the issue. 🙇
