### ISSUE TITLE
Navigating between runner results and collection

### ISSUE THREAD

**Issue by robertmryan** [a85/POSTMan-Chrome-Extension#10978]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

The problem is that it that as collections get large, it is surprisingly complicated to correlate a test in the runner interface and the request in the collection.

### Describe the solution you'd like

* When looking at the runner test results, it would nice if I could navigate to the relevant request with a single click. 
  * Perhaps the context menu (which shows “Request URL”, “Request Headers”, “Request Body”, “Response Headers”, and “Response Body” had another option “Navigate to Request” or “Open Request”)
* Ideally, it would be nice if when I navigated to that request, the body of the response (which is practically impossible to use in that small context menu) was included in the “Response” panel of that request.

### Describe alternatives you've considered

* Some alternative UI implementations:
  * Alternatively have a button that I could use to navigate to the associated request (though it should be near the left side of the request’s results, because if you have very wide screen (to read all this info) it is hard to line up with the request)
  * Alternatively have the ability to "select" a runner result and then have main menu option and/or keyboard shortcut to open the associated request
* Part of the problem is that the folder structure for the request in question in the runner output is buried in a single line of text, after the request name and request URL
  * The folder name doesn't align from line, making it harder to glance at it and know which subfolder it came from (esp an issue if you have many nested subfolders)
  * The folder name text field is single line, so it often gets cut off so you don't have a prayer for knowing which request it was for
* It would be terrific if the runner output mirrored the collapsable folder structure of the collection. This way, I could visually see where the request was in my collections’ folder structure. That strikes me as harder than just giving me some button or context menu to jump to the associated request in the collection.
* I can collapse the left panel so I can see more of the folder structure that I'm navigating to, but obviously once the panel on the left is collapsed, I can't navigate there.

**Comment by malvikach** [comment]
Hi @robertmryan thanks for reaching out to us and letting us know your feedback. Really appreciate the details.

We have seen similar requests [7525](https://github.com/postmanlabs/postman-app-support/issues/7525)  and [9651](https://github.com/postmanlabs/postman-app-support/issues/9651). You might be interested in checking them out too. 

To summarize, these are the improvements you would like to see:

- Ability to open the request from the run results view

- Ability to see the response body clearly 

- Ability to view the folder structure (tree hierarchy) in the runner results

We have taken note of these. I am marking this as a feature improvement and will share updates with you when we pick this up. 

Please feel free to mention if I have missed something. Thanks.

**Comment by robertmryan** [comment]
No, I think you captured it. Thank you for following up.

**Comment by malvikach** [comment]
Hi @robertmryan 👋 

Glad to inform you that in the recent release (Postman version 10.12.0) we have addressed the concerns you mentioned:
- You can now click on request names to open the requests from the Collection Runner Results. This will help with faster navigation while debugging and fixing a problem.
- View request and response details in the Collection Runner Results in a more efficient way. Response Body is also formatted and you can easily search/copy it if needed during debugging an issue. 
- We also display the request/folder paths on the right hand pane. The individual components can be clicked to navigate to the given folder quickly. 

![ezgif com-optimize (3)](https://user-images.githubusercontent.com/89449769/225819499-e236a1f0-4046-4182-9f45-dd726de717bc.gif)

We hope that this helps in your workflows. The ability to view the tree hierarchy visually is something we will evaluate if it is still needed based on feedback. I am closing this ticket, but please feel free to let us know your experience. 

Please Note: The Postman version update is being rolled out, you will get it in the next 2-3 days if you haven't already. 

Thanks again for your feedback. We really appreciate it. 

Cheers!
Malvika

**Comment by robertmryan** [comment]
Hey, I appreciate you getting back to me. Nice improvement.

But, with all due respect, please convey your to executive team that this is just too little, too late.

The new Postman pricing scheme (with insanely low monthly limits as to how many tests we can run on our own hardware) is no longer viable for small operations. I can no longer recommend Postman for any of my clients.

But thank you for your time.
