### ISSUE TITLE
Selecting Portman folder when importing no longer shows files

### ISSUE THREAD

**Issue by yowhatsshakin** [a85/POSTMan-Chrome-Extension#10976]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

When trying to import collections and/or environments, selecting the postman related folder where we keep these things no longer list the available files

### Steps To Reproduce

On Windows :
1- Open Postman version 9.19 or 9.20
2- Click the Import button
3- Select the Folder tab in the UI
4- Click "Choose folder from your computer"
5- Navigate to the relevant folder
6- Click "Select Folder"

### Operating System

Windows

### Postman Version

9.20.3

### Postman Platform

Postman App

**Comment by ajhanson** [comment]
I'm having the same issue.

v9.20.3 will not import all files from folder, we have to choose import files and select them separately from the folder and subfolders.

**Comment by vinukumar-vs** [comment]
I am also facing the same issue. I am using the latest version of postman(v9.21.2)

> Unable to find any files to import. Double check your repository and branch.

I have uploaded the exported JSON collection to github. Now I am trying to import the file from Github into the Team workspace. So that team can commit the JSON collection file changes to GIthub & will get synced to postman(auto).

**Comment by snazeergit** [comment]
I am too facing the same issue.

**Comment by vinukumar-vs** [comment]
It's not working in the standalone postman tool. But it is working fine in web-postman(postman web application). 

The changes in web-postman will sync to desktop postman tool.

**Comment by carlbray** [comment]
I still had 9.14 linux downloaded and was able to successfully able to import folders.

**Comment by timbochamp** [comment]
Thanks for reporting! I'm able to see the same on Windows and have logged a bug. We'll report back with updates here

**Comment by Cordifhyura** [comment]
Same in 9.19.0, I can import the folder with drag-and-hold, but it can't be triggered by click "Choose folder from your computer"

**Comment by jigsawnz** [comment]
Same in 9.25.2, Postman for linux. Drag and drop works but not by selecting a folder to import.
Update 09/11/22 - Updated to **10.1.2.** Drag and drop works but not by selecting a folder to import.

**Comment by akshaydeo** [comment]
@jigsawnz If you aim to import schema from the folder in Postman 10.x, we have a new flow for it.


![Image](https://github.com/postmanlabs/postman-app-support/assets/1050029/aafa304d-bd84-4c4e-a03d-2f923d889d28)

You must check "Import OpenAPI files" from the bottom of the forms to import as API. Import flow automatically detects relevant files that are required. 

I am closing this issue for now. Please reopen if you are still facing this issue.
