### ISSUE TITLE
Mock server doesn't invoke correct example if calling from non-postman app

### ISSUE THREAD

**Issue by hungdao-testing** [a85/POSTMan-Chrome-Extension#10970]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

The Mock server doesn't invoke correct example if called from the non-postman app, which is the browser or 3rd party service 

### Steps To Reproduce

**Precondition**
- I have a collection with 2 requests, each has at least 3 examples with different names (and response code)
![image](https://user-images.githubusercontent.com/51052135/171526386-2084e81c-6725-4f89-8280-0b6a8786f667.png)

- The mock server is created with this collection (generated mock_url:  `https://0f2e9505-c112-4664-88e5-5f8f206c5ba4.mock.pstmn.io`)

**Steps**:
- Call the api `Call124`  with header `x-mock-response-name` = `404-124`  by Postman tool with `url is mock_url `
=> **PASSED**. The response return correct example I defined and the mock log shows the correct header 
![image](https://user-images.githubusercontent.com/51052135/171525803-16202ce4-572c-47ce-8a8f-509a492578e4.png)

![image](https://user-images.githubusercontent.com/51052135/171526005-f7e1cae6-eb05-46c3-9203-3096144f5ed2.png)

- Call the api  `https://0f2e9505-c112-4664-88e5-5f8f206c5ba4.mock.pstmn.io/get?test=124`  by entering on the browser 
=> FAILED. It returns incorrect example which is `500 Error` and the mock-log doesn't show the configured header
![image](https://user-images.githubusercontent.com/51052135/171525623-3e6b5da4-833c-4c82-9bae-193b3176e308.png)

![image](https://user-images.githubusercontent.com/51052135/171526050-6b04df39-e8b6-4740-8dcb-a58318adbfd7.png)

Expectation:
- No matter what the mean (Postman, browser, forwarding to 3rd party service) we are using, the mock should invoke correct example 

### Operating System

Win 11

### Postman Version

v9.20.0

### Postman Platform

Postman App

**Comment by DannyDainton** [comment]
Hey @hungdao-testing

How are you specifying the `x-mock-response-name` header in the 3rd party service?

By removing/disabling that in the Postman call, is that returning the same `500` Status Code example?

**Comment by hungdao-testing** [comment]
@DannyDainton ,
I don't/cannot configure the `x-mock-response-name` header in the 3rd party service (because of out of control). The team just provide the configuration page for me to configure 3rd-party service. Then, I replace the REAL url by the `postman mock url`. 

To simulate the 3rd-party I used the public postman `https://postman-echo.com/get?test=124` just for more information for you to investigate.

**Comment by hungdao-testing** [comment]
@postman-support :
Just scan the document of the Postman page and try few cases, then realize that to let Postman_Mock server decide which saved example is used we need to modify the header request (e.g. `x-mock-response-name=something`) of the actual call. In my case, I added the `x-mock-*` to the saved example **NOT the request (because of my permission not allow my to access the code to do)**.  Therefore, it doesn't work as expectation. So far, I think my issue not actual bug for the current Postman version. 

However, I would like suggest Postman could support a way to NOT modify the request header, and redirect the request to the saved example based on the configuration of the example (as in my case), or have a mapping file on Mock_server to control. The first reason is to prevent the attacking or security violence; the second is for the `black-box` QA (the ones who don't have permission to modify the Dev's code as I am) to control the testing more effectively.

I think my issue is related to the concern in here https://github.com/postmanlabs/postman-app-support/issues/8534

**Comment by sony-mathew** [comment]
Hi @hungdao-testing ,

I hope you're doing well! After reviewing your issue, I believe it's closely related to a previous issue which we are already tracking (#8534). To provide a more comprehensive solution, I'm going to mark this ticket as closed and encourage you to continue the conversation over there. This will allow us to keep all relevant information in one place and ensure a more efficient resolution.

If you have any further questions or concerns, please don't hesitate to reopen this ticket or reach out to us. We're always here to help.
