### ISSUE TITLE
Convert a team space to personal workspace

### ISSUE THREAD

**Issue by mpowrie** [a85/POSTMan-Chrome-Extension#10974]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

I converted a personal to a team workspace so  I could share it with a colleague. 
That collaboration is over, and I've since been invited to another team.

When I try to join the new team, I get an error that I need to leave the old team before accepting an invite.
So to accept the invite, I want to first convert my old shared "team" workspace to a personal workspace.

### Describe the solution you'd like

I would like to be able to convert a team workspace back to a personal workspace

### Describe alternatives you've considered

I was able to copy the team workspace to a personal workspace after much faffing about with the instructions on copying workspaces via the Postman API per the below thread, but it would have been a much nicer experience to be able to do this in the postman GUI.
https://community.postman.com/t/converting-team-to-personal-workspace/3284/3

**Comment by akshay-kulkarni-03** [comment]
@mpowrie we already have an existing issue open for this: [https://github.com/postmanlabs/postman-app-support/issues/9806](https://github.com/postmanlabs/postman-app-support/issues/9806). I am closing this in favor of that and would request you to watch that issue for more updates.
