### ISSUE TITLE
Unable to export environment file in standalone mode using windows app

### ISSUE THREAD

**Issue by VoloBro** [a85/POSTMan-Chrome-Extension#10983]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

In the latest version of postman Version 9.19.0 I am unable to export the environment file unless I am connected to the cloud workspace. 

Our security team do not allow us to upload the environment file to the 3rd party cloud. 

Is there any options to work around this limitation?

### Steps To Reproduce

1. Import the environment file
2. Go to the Environments tab
3. Right click on the Environment that you want to export 

Actual: the option to export environment file is disabled and require logging into workspace and uploading the file

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/14946112/172665031-e2a8ee76-0cfe-423d-91d1-8a5c4a8dfac9.png)

### Operating System

Windows

### Postman Version

9.19.0

### Postman Platform

Postman App

**Comment by DannyDainton** [comment]
Hey @VoloBro 

The option to export the environment wouldn't be part of the left sidebar, with the environment tab open you should see a _3 dots_ option on the right. The export option can be found there. 

This is an image take from the learning center:

![environment-manage-roles-v9.1.jpg](https://user-images.githubusercontent.com/17089546/172819982-a65c0889-32f6-4f72-8e69-9b08bf49d2d6.jpg)

https://learning.postman.com/docs/sending-requests/managing-environments/#working-with-environments-as-a-team

**Comment by VoloBro** [comment]
That works, thank you for getting back so quick.
