### ISSUE TITLE
Unable to merge fork back into source

### ISSUE THREAD

**Issue by seelaman** [a85/POSTMan-Chrome-Extension#10989]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

We have forked a branch off our develop one and want to merge it back into develop, getting the following error

Also mentioned in [issue 6397](https://github.com/postmanlabs/postman-app-support/issues/6397) which has been closed.

### Steps To Reproduce

1. Create a new forked branch
2. make changes to fork
3. Merge changes, updating the destination (the original source)

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/8989886/172936434-71a4f109-c01e-4e12-be9b-21c07bef7991.png)

### Operating System

Ubuntu 22.04

### Postman Version

9.20, also tried the snap install which is 9.19

### Postman Platform

Both

**Comment by kartikjain26** [comment]
@seelaman We were unable to reproduce this issue on our end.
Can you write to us at [https://support.postman.com/hc/en-us/requests/new](url) with your user and collection details.

**Comment by ankitjaggi** [comment]
Closing this ticket due to inactivity. Feel free to reopen it if the issue persists.
