### ISSUE TITLE
Links to documentation tags aren't working. Links open random pages.

### ISSUE THREAD

**Issue by samwfulwider** [a85/POSTMan-Chrome-Extension#10986]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Our postman documentation has multiple different links within the content to other pages in the documentation. These links, when clicked, open a new window and put users in random areas of the documentation. I've checked multiple times and the tags for each link match the tag of each folder, but for some reason it doesn't quite connect. If you could assist with this, it would be greatly appreciated. Thanks!

### Steps To Reproduce

1. Open the SmartWitness 2.1 API Documentation 
2. Go to **Let's Get Started** > **Standards and Security** > **API Filters**
3. Click on GET GetGPSData link. This can be found at https://api2.smartwitness.co/#a97ea83d-ac66-d483-5811-c8dfceb20fce, or when in the documentation at **Devices** > **GET GetGPSData**
4. It will send you to a different API request, and not GET GetGPSData.

### Screenshots or Videos

[documentation_link_issue.zip](https://github.com/postmanlabs/postman-app-support/files/8871185/documentation_link_issue.zip)

### Operating System

Windows

### Postman Version

9.20.3

### Postman Platform

Both

**Comment by samwfulwider** [comment]
There is a workaround with changing the column layout for the page, but there is still a bug here that I can't quite figure out.

**Comment by ajeet-postman** [comment]
@samwfulwider This issue is fixed. Can you please confirm if you are still facing this issue?
