### ISSUE TITLE
macOS native application auto-capitalizes query params when typed

### ISSUE THREAD

**Issue by aforty** [a85/POSTMan-Chrome-Extension#10984]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

In the native app (not sure if this happens anywhere else) query params are auto-capitalized when typed in, turning "include" into "Include" which my server then obviously can't handle, the change is also so subtle visually that it took me forever to track down what the issue was. Must be some OS-level autocorrect feature that is not explicitly turned off.

### Steps To Reproduce

1. Launch Postman on macOS
2. Start a new request and go into the Params tab
3. Start typing "include" as a key and you'll see it auto-capitalized to "Include"

### Screenshots or Videos

https://user-images.githubusercontent.com/523683/172670123-7527781e-d837-4863-a21e-6ab013abafdd.mov

### Operating System

macOS 12.4

### Postman Version

9.20.3

### Postman Platform

Postman App

**Comment by timbochamp** [comment]
Hi @aforty, I'm not able to reproduce this behaviour. Do you have any software that would auto-capitalize with that pop-up that shows between the 0 and 1-second mark of your recording? I believe even having the macOS setting in "Keyboard > Capitalize words automatically" shouldn't even auto-capitalize within the app

**Comment by aforty** [comment]
@timbochamp Maybe this general macOS keyboard setting? There is a way to explicitly not respect this option on text fields.

<img width="643" alt="Screen Shot 2022-06-23 at 4 17 09 PM" src="https://user-images.githubusercontent.com/523683/175392054-f1fbd83e-8267-476e-bfcf-5e1d70c2a4a7.png">

**Comment by timbochamp** [comment]
Right, that's the setting I mean. When unselecting that setting, do you still see words being auto-capitalized within Postman?  I'm wondering if there's a regression where previously the Postman app would not auto-capitalize on older macOS versions even when that setting is enabled.

**Comment by aforty** [comment]
Oops... I had an auto-replace rule for `i` to `I`. So this is completely on me and nothing to do with either of those settings. Nevermind.
