### ISSUE TITLE
it's not clear there is more than one example

### ISSUE THREAD

**Issue by arilishu** [a85/POSTMan-Chrome-Extension#10998]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

If you are watching the examples, is not clear if there is more than 1 example, because there is no dropdown or any icon that expresses that.

### Describe the solution you'd like

Add "∇" to the example name, so every customer can understand clicking there, will find more examples.

### Describe alternatives you've considered

Instead of the text, we can display a button, but the ∇ icon will be consistently with the header, where you can display different environments, or switch between displaying single/double columns.

### Additional context

I guess if you add in a method a few examples, and then in the documentation want to see all that examples, you will see it's not easy to understand that you have to click on the title.

![image](https://user-images.githubusercontent.com/1785576/173408999-dd5de8f0-20a3-4ac8-bdd0-a8dbd3180b73.png)
![image](https://user-images.githubusercontent.com/1785576/173409013-d42cc336-d12c-482d-8eab-e7994355395b.png)

**Comment by tkrajewski89** [comment]
Please resolve this as it is very confusing to the end users.

**Comment by ishan-ks** [comment]
@arilishu @tkrajewski89 Thanks for reporting this issue. We are actively looking into this and will fix this soon.

**Comment by akshaydeo** [comment]
This fix is available on public documentation :) 

<img width="1250" alt="image" src="https://user-images.githubusercontent.com/1050029/204725581-05c87219-e574-43d8-9c3e-b565f96d72e6.png">
