### ISSUE TITLE
jsonp respond no pretty view?

### ISSUE THREAD

**Issue by fenta23** [a85/POSTMan-Chrome-Extension#1099]
jsonp responds are not recognized anymore.

Error:
Malformed JSON: Unexpected 'j'

App Version:
Version 3.0.0.5 (packaged)
OS: mac
Architecture: x86-64
Native client architecture: x86-64

**Comment by abhijitkane** [comment]
We'll push a fix in the next release.

**Comment by abhijitkane** [comment]
@fenta23 Can you confirm this fixed in v3.0.4?
