### ISSUE TITLE
Which file holds the Workspace Settings

### ISSUE THREAD

**Issue by g3mni** [a85/POSTMan-Chrome-Extension#10997]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Due to the information security requirements of the company.We would like to determine whether workspace is "public" or "team" by checking the setting of workspace setting in the desktop app by MDM.
 I have found that changes to the workspace Visibility (change "team" to "public")are submitted to the server via the "update" button, but the configuration for this workspace Visibility is definitely saved locally file.In macOS,I've looked for the documents in /Users/user_name/Library/Application Support/Postman/Partitions, but I can't find what I want.
Could you please tell me which file holds the Workspace Settings? That file, I can read Workspace Settings.
Hope reply

### Steps To Reproduce

Nothing to say here

### Screenshots or Videos

![screenshot-20220614-003950](https://user-images.githubusercontent.com/21138928/173402741-ab55de2a-ca86-4b61-afdf-037576736413.png)

### Operating System

macOS/Windows

### Postman Version

9.21.2

### Postman Platform

Postman App

**Comment by numaanashraf** [comment]
@g3mni The visibility of a workspace is not stored in any files on the end users device. We recommend using the Postman API to get the type of the workspace and check if they are "public". 

https://www.postman.com/postman/workspace/postman-public-workspace/request/12959542-f027a0fa-9012-4654-a65d-2b751a3154a9

**Comment by DannyDainton** [comment]
I don't believe that the `visibilityStatus` of the Workspace is currently exposed via the Postman API. The request would currently return the `type`, which could be personal or team.

**Comment by david-espi-hernandez** [comment]
Hi! 
The `visibility` field will be added soon (hopefully in a release this week) in the Postman API workspace detail response.

**Comment by DannyDainton** [comment]
Thanks for the update @david-espi-hernandez 🏆

I knew it was coming but wasn't quite sure on the dates. Great stuff!

**Comment by rubenbaraut** [comment]
The ticket is done and the code is working in production. Thanks!
