### ISSUE TITLE
Increase limit of nested resources in schema

### ISSUE THREAD

**Issue by roobee15** [a85/POSTMan-Chrome-Extension#10999]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

When you Import a spec and a collection is generated but examples are not all generated. 
Instead, the following error is seen "Too many levels of nesting to fake this schema"
increasing the limit to more than 10 will help mitigate this issue. 

### Describe the solution you'd like

Increase limit of nested levels allowed. 

### Additional context

Currently as a workaround, you can turn off Optimize Conversion setting, which should prevent the deeper layers of nesting from being populated with "Too many levels of nesting to fake this schema". However, many members don't know this option and admins cannot be asking all users to install a module and run from CLI.
![import settings](https://user-images.githubusercontent.com/91977660/173417112-0993a644-dff2-4acc-ad41-1fcec4cab7bf.png)

**Comment by CarrieRaglan** [comment]
"Optimize conversion" is ON by default, most users have no idea what this actually means. Most users leave this on not knowing that not only affects performance but will also change how the examples are generated.

With "Optimize conversion" ON (the default setting)
`
{
	"level1": [{
		"level2": {
			"value": "<Error: Too many levels of nesting to fake this schema>"
		}
	}]
}
`

With "Optimize conversion" OFF
`
{
	"level1": [{
		"level2": [{
			"level3": [{
					"value": "<Error: Too many levels of nesting to fake this schema>"
				},
				{
					"value": "<Error: Too many levels of nesting to fake this schema>"
				}
			]
		}]
	}]
}
`

**Comment by ScottFN** [comment]
Is this being addressed? 'Optimize conversion' = OFF does not solve this problem

**Comment by venkatrao225** [comment]
@postman-support do you have any plans to fix this issue?

**Comment by voodooism** [comment]
Optimize conversion doesn't work for me. I use collection from here: https://developer.mastercard.com/mdes-digital-enablement/documentation/api-reference/

**Comment by venkatrao225** [comment]
I could mitigate the issue with command line tool

https://www.npmjs.com/package/openapi-to-postmanv2

`$ openapi2postmanv2 -s spec.yaml -o collection.json -p -O folderStrategy=Tags,requestParametersResolution=Example,optimizeConversion=false,stackLimit=50
`

stackLimit argument helps to mitigate the issue.

**Comment by mikej96** [comment]
I've run into this as well. Ended up having to re-work API definitions by adding unnecessary duplication of properties so that Postman can load sample responses. At the end of the day end users of an api spec have grown to depend on this functionality, so having example responses that fully load by default ended up being more important than a non-redundant spec.

**Comment by tr4nquillo** [comment]
turning off Optimize conversion does not work on the web version as well.

**Comment by VShingala** [comment]
@roobee15 @CarrieRaglan @ScottFN @voodooism @leiferksn 

https://github.com/postmanlabs/postman-app-support/issues/10928#issuecomment-1506992681

> Hey Everyone, with the recent Postman app release v10.12. We've made changes to how we generated the collection from OpenAPI definitions. To solve this issue, we've made many performance improvements and have removed the default option called Optimize conversion which was restricting the amount of nested data that was resolved.
>
> We've also increased this limit till which we used to resolve nested data by 3 times (Now, we resolve till 30 levels of nested schema objects instead of the previous 10 levels).
>
> Please, let us know your feedback on this if you're still facing this issue. We'll keep this issue open for some time to collect more feedback.

Sorry for the late reply here! I'll be closing this issue in favor of mentioned issue which is still open and is same. Do share your feedback there if you're still facing this problem.
