### ISSUE TITLE
Duplicate tab without overriding original tab

### ISSUE THREAD

**Issue by JustinJohnWilliams** [a85/POSTMan-Chrome-Extension#10991]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

no

### Describe the solution you'd like

On the MacOS desktop client when I click "Duplicate Tab" in the right click menu an exact copy of my tab opens up, as expected. However, when I make changes in the new tab and save the new tab, the original tab also reflects the changes and therefore creates a conflict. It would be nice if there is behavior that reflects that way my browser works in this regard. Duplicating a tab will have the same data, but is not a reference to the original. 

### Describe alternatives you've considered

My current work around is to always "Save As", which is not ideal.

**Comment by timbochamp** [comment]
Hi @JustinJohnWilliams, thanks for reporting! This has been brought up in the past in #9663 and #10877. The wording is a bit deceptive, but duplicating a tab does not mean creating a second request to the same endpoint. When you duplicate a tab, any edits you make will affect the original request:

https://learning.postman.com/docs/getting-started/navigating-postman/#managing-tabs

Duplicating a request is done by selecting it in the sidebar with a right-click > Duplicate, or a Ctrl+D/cmd+D hotkey once selected. Going to close this where this is how the Duplicate Tab functionality is intended.
