### ISSUE TITLE
New Integration Request - <GitHub actions>

### ISSUE THREAD

**Issue by suchand-talview** [a85/POSTMan-Chrome-Extension#11000]
### Describe your current workflow

Bring build runs from Github actions to Postman and configure Newman to run Postman collections on your GitHub actions pipeline.

### Describe your ideal workflow

Bring build runs from Github actions to Postman and configure Newman to run Postman collections on your GitHub actions pipeline.

**Comment by shashankawasthi88** [comment]
Hi @suchand-talview , thanks for raising the request. We are in process of designing the integration and understanding the user workflows. Will it be possible for you to get on a call to discuss your workflows? You can use the [link](https://calendly.com/shashank-awasthi/30min) to schedule a meeting with us.

**Comment by shashankawasthi88** [comment]
@suchand-talview let us know if you are still interested in this request. We are in process of building this and would like to validate it with a few customers.

**Comment by shashankawasthi88** [comment]
@suchand-talview this has now been added in Postman V10. If you want to know in detail how the GHAction and the GitHub Repository integration works, you can schedule a call with me [using](https://calendly.com/shashank-awasthi/v10-feedback?month=2022-09) this link.

**Comment by suchand-talview** [comment]
> @suchand-talview this has now been added in Postman V10. If you want to know in detail how the GHAction and the GitHub Repository integration works, you can schedule a call with me [using](https://calendly.com/shashank-awasthi/v10-feedback?month=2022-09) this link.

Thanks for the message. I managed with Newman.
