### ISSUE TITLE
Feature request: Copy function to copy entire request settings.

### ISSUE THREAD

**Issue by lewisdavidcole** [a85/POSTMan-Chrome-Extension#1100]
I often copy/paste all of the URL, request type (GET,POST) and the request body, for the purpose of passing on to fellow workers. It would be nice to have this as an additional copy feature. I know there is a Copy button for the request/response, but not that captures the URL and request type (and maybe headers?).

**Comment by a85** [comment]
We recommend sharing a request through Collections with your co-workers. http://getpostman.com/docs/collections
