### ISSUE TITLE
502 Bad Gateway Errors (Beginning 08.June.2022)

### ISSUE THREAD

**Issue by i-wrestle-tests** [a85/POSTMan-Chrome-Extension#11001]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

I have test suite collections set up and monitor scheduled to run them between 0500-0800 M-F.  They have been executing just fine, until the morning of 08.June, when they began failing with 502 Bad Gateway Errors. The results are also inconsistent, some will pass and others will get the 502 error.  

I began by researching the Postman Community to see if others had ideas, but there haven't been any responses - https://community.postman.com/t/502-bad-gateway-errors-beginning-08-june-2022/36120 

### Steps To Reproduce

I have not been able to reproduce the exact steps to generate the error either.

This occurs with the collections set up on monitor and those run adhoc via the Runner.  I've even experienced the error when sending individual requests - it will fail with 502 first and then upon retry it will succeed.

We have not made any changes on our end and I've reviewed our internal logs and there aren't any errors that align with the above.

Logs included from one of my test suite collections, showing the inconsistent results.
[08June2022_ConsoleLog.txt](https://github.com/postmanlabs/postman-app-support/files/8899539/08June2022_ConsoleLog.txt)
[09June2022_ConsoleLog.txt](https://github.com/postmanlabs/postman-app-support/files/8899540/09June2022_ConsoleLog.txt)
[10June2022_ConsoleLog.txt](https://github.com/postmanlabs/postman-app-support/files/8899541/10June2022_ConsoleLog.txt)
[13June2022_ConsoleLog.txt](https://github.com/postmanlabs/postman-app-support/files/8899542/13June2022_ConsoleLog.txt)
[14June2022_ConsoleLog.txt](https://github.com/postmanlabs/postman-app-support/files/8899543/14June2022_ConsoleLog.txt)

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/106683067/173573527-8a01f475-7936-4317-a6b8-c10eabfa8337.png)

### Operating System

Windows

### Postman Version

Version 9.21.2; Desktop Platform Version 9.19.0

### Postman Platform

Postman App

**Comment by i-wrestle-tests** [comment]
502 errors continue, today with examples of ones that were working.  Could I get assistance please, because the errors, and their inconsistency, are adversely impacting my tests and making it difficult to use your product/service.  This has been occurring for over a week, now.
![image](https://user-images.githubusercontent.com/106683067/173823237-f0a5d82e-9e55-4c3b-9745-bec41efaaa68.png)
![image](https://user-images.githubusercontent.com/106683067/173823361-2e88756e-41df-4971-a1f8-fcfcdcbe38d5.png)
![image](https://user-images.githubusercontent.com/106683067/173823448-37cd9401-eee4-4a53-88c9-3fb5864c1fbf.png)
![image](https://user-images.githubusercontent.com/106683067/173823504-686dc020-d6d2-4199-ac22-9c48c93b34f1.png)

**Comment by timbochamp** [comment]
Hi @i-wrestle-tests, thanks for reaching out. It might be something you've already explored to check with the host of that endpoint, but the 502 errors suggest to me that there's some issue with the https://api.uat.cryptopay3.com endpoint being unavailable. 

I don't think this is specific to Postman Monitors at first glance, so I'm going to close this out. If you're able to consistently access this endpoint outside of the Monitor executions, could you send your logs along to support@postman.com? The steps to do so are here:
https://support.postman.com/hc/en-us/articles/360025298633-How-to-collect-logs-in-the-Postman-Desktop-app
