### ISSUE TITLE
Not able to click links in the response

### ISSUE THREAD

**Issue by selvakumar0309** [a85/POSTMan-Chrome-Extension#1101]
After the V3 update, I am not able to click links in the response. I use the latest Chrome (43) and Ubuntu

**Comment by johnnavarra** [comment]
I am seeing this as well.

**Comment by abhijitkane** [comment]
This is a limitation of Ace-editor (the plugin we're using to render JSON responses). We're working on a way to make links clickable.

**Comment by abhijitkane** [comment]
@selvakumar0309 Can you confirm this fixed in v3.0.4?

**Comment by selvakumar0309** [comment]
Hi there, yes it is fixed in v3.0.4

Thankyou

**Comment by jtenar** [comment]
Facing the same issue on version 4.8.0
win / x86-64
Chrome 53.0.2785.143
