### ISSUE TITLE
Bootcamp: Debugging and manual testing unable to complete

### ISSUE THREAD

**Issue by bilalhasson** [a85/POSTMan-Chrome-Extension#11011]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Trying to go through the bootcamps to learn how to use postman, however when trying to continue with the lesson I get to collection variables and then the next step doesn't appear

<img width="223" alt="Screenshot 2022-06-16 at 10 58 45" src="https://user-images.githubusercontent.com/68790383/174045791-ca1ec5a1-245d-42dd-85f9-a5fa6ad51dad.png">

### Steps To Reproduce

Bootcamp -> Debugging and manual testing -> Collection variables. Try to complete those steps to the end

### Screenshots or Videos

https://user-images.githubusercontent.com/68790383/174053921-e6aa2cc9-caa6-47e9-a982-754fdc23e070.mp4

### Operating System

Mac OS Platform OS X 21.5.0

### Postman Version

9.21.2

### Postman Platform

Postman App

**Comment by Avidsphere** [comment]
I've been having a similar issue with several other bootcamp lessons.

**Comment by arlemi** [comment]
Hey there,

I'm closing this issue as from the March 2023 release of Postman, the Bootcamp is not available in the app anymore.

If you're interested in more Postman training courses here's a few resources I recommend checking out
-  [Postman Quickstarts](https://quickstarts.postman.com/) 
-  [Postman Academy](https://academy.postman.com/)
- [Postman Intergalactic webinars](https://www.postman.com/events/intergalactic/)
