### ISSUE TITLE
Anchor links in the expanded tables are not working properly in the Postman Web Documentation

### ISSUE THREAD

**Issue by rostykzub** [a85/POSTMan-Chrome-Extension#11013]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

My documentation is stored on https://developers.recman.no/ domain
And if I paste https://developers.recman.no/#e1695b17-6b58-4207-9975-dfd01760a844 link into the table and try to open it while this table is expanded - nothing is happening.

You are actually navigated to the appropriate anchor but the problem is that the expanded table view is not closed after you pressed the link and it becomes an overlay for the content of the page...

### Steps To Reproduce

1. Create a documentation that has a table of more than 10 rows
2. Pasted an anchor link into a table
3. Publish your documentation
4. Open the published documentation in the web browser
5. Expand the table created in the Step 1 (click 'View more')
6. Click the link from the Step 2
7. Notice that no actions are performed

_**Note:** After closing the expanded table view - you may notice that you are actually taken to the anchor position on the webpage._

### Screenshots or Videos

![bug postman](https://user-images.githubusercontent.com/51949386/174129931-cdd5883a-162c-41f8-992e-7f4751dadd25.gif)

### Operating System

macOS 11.5.2

### Postman Version

Version 9.21.2

### Postman Platform

Postman Web

### Additional Context?

I've searched for a similar issues in your tracker and found similar issue that was already closed: [https://github.com/postmanlabs/postman-app-support/issues/5180](https://github.com/postmanlabs/postman-app-support/issues/5180)

But as you can see - the issue wasn't fully fixed since it is still present with an anchor links.

**Comment by akshaydeo** [comment]
@rostykzub, thanks for reporting this issue. The issue here is that anchor navigation is happening on the main page. Due to the fullscreen modal, it's not visible. 

We are working on a quick fix to handle this scenario :). I will update this issue as soon as we have fix live 🙇‍♂️ 

We are launching a new, improved UX for all the elements soon, which will handle these cases more intuitively 🙂

**Comment by ishan-ks** [comment]
@rostykzub I can see that this issue is fixed now. Can you also check once and let us know?
