### ISSUE TITLE
Pull Request Still Showing Active After Merge

### ISSUE THREAD

**Issue by dcdraper** [a85/POSTMan-Chrome-Extension#11012]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

I have merged the PR and deleted the source, yet the target collection still shows the PR as open.  I want to be able to delete the PR or clear it out some way but I cannot.

### Steps To Reproduce

I cannot repro it. How can I remove the PR that was already merged?

### Operating System

Windows 11 Business

### Postman Version

9.21.0

### Postman Platform

Postman App

**Comment by MoBBsKiLLz** [comment]
I having the same issue. Additionally, whenever I Merge a branch in it gets stuck on the merge screen and doesn't show if it was merged or not. My work around is to restart Postman.

**Comment by kartikjain26** [comment]
@dcdraper You can access the pull request and go ahead with declining it if your changes are already merged.

**Comment by ankitjaggi** [comment]
Closing this issue for now. Feel free to reopen it if the solution provided does not work for you.
