### ISSUE TITLE
Update Placeholder text in Schemas to Variable format

### ISSUE THREAD

**Issue by nrmartell** [a85/POSTMan-Chrome-Extension#11015]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

Right now when a user imports a schema the placeholder text for authorization is formatted as such `<Bearer Token>` Users would expect something in variable format to begin working quicker.

### Describe the solution you'd like

Modify placeholder text to variable format such as `{{Bearer_Token}}` so users can get up and running quicker

### Additional context

Filing on behalf of Org

**Comment by VShingala** [comment]
@nrmartell We're tracking this over [here](https://github.com/postmanlabs/openapi-to-postman/issues/643). We already have fix ready for this that should be available in production soon. As such I'll close this issue and will add an update on the linked issue.
