### ISSUE TITLE
New Integration Request - <product name>

### ISSUE THREAD

**Issue by AsiwajuDev** [a85/POSTMan-Chrome-Extension#11021]
### Describe your current workflow

None is available. It is a new project aimed to unify different collections of API endpoints and will be managed from a custom Admin portal

### Describe your ideal workflow

Admin login to the custom-built portal, Create a new collection of the API endpoints and add various individual endpoints with their types. Admin then sets the permission of users who will have access to do that (this will be controlled from my own end here as I will have to reference the collection in my database mapping the user role)

**Comment by shashankawasthi88** [comment]
@AsiwajuDev Postman integrations are aimed to integrate Postman with other software used in the developer ecosystem. Any custom solutions can be built using the Postman APIs (https://learning.postman.com/docs/developer/intro-api/). I am closing this request for the same reason.
