### ISSUE TITLE
Pre-request Script http request body lost

### ISSUE THREAD

**Issue by brantyou** [a85/POSTMan-Chrome-Extension#11037]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

When I use the pre request script to obtain the token through the pre request interface, I find that the requested body is lost.

pre request script 
```javascript
const req = {
    url: 'http://' + pm.environment.get('url') + '/xxx/xx/login',
    method: 'POST',
    body: {
        "key": "166645eef2204d7f940ccea7682xx123",
        "value": "000000"
    },
    header: 'Authorization:Basic MTM5OTk5OTk5OTk6MTIzNDXX'
};

pm.sendRequest(req, function (err, response) {
    var data = response.json();
    pm.environment.set('__token', data.tokenType + ' ' + data.accessToken);
});
```

request console log, see the screenshots

### Steps To Reproduce

1. add request
2. enter Pre-request script
3. add request with body
4. see console log

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/4221504/175850505-a906e35d-77e1-45ab-a11f-9aba24d94eea.png)

### Operating System

Windows

### Postman Version

9.22.4

### Postman Platform

Postman App

**Comment by DannyDainton** [comment]
Hey @brantyou,

The syntax that you're using isn't correct so it wouldn't show that in the console. The `body` would need to be passed as a certain _type_, this is just an example as I'm unsure what body type your endpoint requires:

```javascript
    body: {
        mode: 'raw',
        raw: {
        "key": "166645eef2204d7f940ccea7682xx123",
        "value": "000000"
        }
    }
```

![image](https://user-images.githubusercontent.com/17089546/175898372-22f3cc55-ece0-49a3-b839-d0d4a9e007a7.png)

**Comment by brantyou** [comment]
> Hey @brantyou,
> 
> The syntax that you're using isn't correct so it wouldn't show that in the console. The `body` would need to be passed as a certain _type_, this is just an example as I'm unsure what body type your endpoint requires:
> 
> ```js
>     body: {
>         mode: 'raw',
>         raw: {
>         "key": "166645eef2204d7f940ccea7682xx123",
>         "value": "000000"
>         }
>     }
> ```
> 
> ![image](https://user-images.githubusercontent.com/17089546/175898372-22f3cc55-ece0-49a3-b839-d0d4a9e007a7.png)

**Comment by brantyou** [comment]
> Hey @brantyou,
> 
> The syntax that you're using isn't correct so it wouldn't show that in the console. The `body` would need to be passed as a certain _type_, this is just an example as I'm unsure what body type your endpoint requires:
> 
> ```js
>     body: {
>         mode: 'raw',
>         raw: {
>         "key": "166645eef2204d7f940ccea7682xx123",
>         "value": "000000"
>         }
>     }
> ```
> 
> ![image](https://user-images.githubusercontent.com/17089546/175898372-22f3cc55-ece0-49a3-b839-d0d4a9e007a7.png)

It works well. It needs to be configured in this way so that the body can be sent normally. Thank you very much! I also hope you can adjust the sample accordingly, so that the people who use it later can also avoid stepping on the pit
