### ISSUE TITLE
Drag and drop feature for requests in collection is not working properly

### ISSUE THREAD

**Issue by sanket3080** [a85/POSTMan-Chrome-Extension#11030]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Suppose we have 10 requests in a collection which are numbered sequentially like Request1, Request2, Request3.... and so on.
If we try to drag Request 4 and drop it between Request 9 and Request 10 it is getting dropped in between Request 5 & 6.  

### Steps To Reproduce

1. Create HTTP requests (Request 1, Request 2, ....)
2. Try to use drag and drop feature to get those request in an random order lets say Request 5 then drop request 1 below request 5.

### Operating System

Windows

### Postman Version

9.22.2

### Postman Platform

Both

**Comment by giridharvc7** [comment]
@sanket3080 Can you share some logs and a screen recording of this?

**Comment by sanket3080** [comment]
@giridharvc7  sure give me 10 mins

**Comment by sanket3080** [comment]
@giridharvc7  This is happening with one of my existing collection I cannot share recording for it as it contains sensitive information. 
I tried a new collection of public APIs but could not reproduce this

**Comment by sanket3080** [comment]
![Drag Drop](https://user-images.githubusercontent.com/64485626/174970989-c3457b33-eefa-4bdc-8101-be1c6beecc75.gif)

**Comment by sanket3080** [comment]
@giridharvc7  Here is the gif that explains the issue

**Comment by sanket3080** [comment]
This is happening when there are multiple folders in collection

**Comment by sanket3080** [comment]
[New Collection.postman_collection.json.zip](https://github.com/postmanlabs/postman-app-support/files/8955482/New.Collection.postman_collection.json.zip)
This is the collection used for recording above GIF

**Comment by giridharvc7** [comment]
Thank you for the details. We are looking into this!

**Comment by giridharvc7** [comment]
We've raised a fix. Should be available with version 9.22.3. It's in the process of roll out.

**Comment by sanket3080** [comment]
@giridharvc7  Thank You

**Comment by giridharvc7** [comment]
@sanket3080 can you confirm if things are working as expected ?

**Comment by sanket3080** [comment]
Yes it is working as expected with v9.22.3
