### ISSUE TITLE
Private workspace ends up without an Admin

### ISSUE THREAD

**Issue by boskomirkic** [a85/POSTMan-Chrome-Extension#11038]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

I have encountered a scenario where Private workspace can end up without admin; it is when the only Private workspace Admin is removed from a team by Team Admin via "Manage team", while there is another Private workspace member who is not an admin. 

### Steps To Reproduce

Setup: Private workspace within a team, with User1 as workspace Admin, and User2 as workspace Viewer or Editor

Steps to reproduce:
1. Team Admin removes User1 from the team via "Manage Team" functionality.

Current behavior:
- System removes User1 from the team and from all team workspaces (Private, Team)
- Private workspace remains Private, with only one member (User2) who is not a workspace Admin

Expected behavior:
- System recognizes the conflict (Private workspace without Admin if the action is executed), requests new workspace Admin to be appointed and doesn't allow removal of User1 until the conflict is solved.

### Operating System

Windows

### Postman Version

9.22.4-220623-1100

### Postman Platform

Postman Web

### Additional Context?

Ticket 7586 (https://github.com/postmanlabs/postman-app-support/issues/7586) solves similar issue (when Admin is leaving the workspace) but doesn't cover the scenario with Admin being forcefully removed from the Team by Team Admin.

**Comment by DannyDainton** [comment]
Hey @boskomirkic

Could you provide a screenshot of the Workspace Settings, that shows that no admin is present, please?

**Comment by boskomirkic** [comment]
Sure @DannyDainton, here it is.

![Screenshot_Postman_no admin_](https://user-images.githubusercontent.com/108119728/177309023-1478433d-f2b5-4417-ba40-1667c0f7e174.jpg)

**Comment by akshay-kulkarni-03** [comment]
@boskomirkic we have created an internal issue for this issue and will be triaging it from our side. Will update this thread once we have identified the root cause and the fix for the same.

**Comment by akshay-kulkarni-03** [comment]
@boskomirkic we have identified the root cause for this issue and fixed it. Feel free to re-open this issue if you encounter it again!
