### ISSUE TITLE
Assertions are getting repeated from 1st request in collection during collection run using postman runner

### ISSUE THREAD

**Issue by sanket3080** [a85/POSTMan-Chrome-Extension#11031]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

When we run collections using collection runner assertions from 1st request in the collection are getting repeated.

### Steps To Reproduce

1. Create a collection
2. Add a HTTP request to any public API I used https://catfact.ninja/fact this in my case.
3. Add assertions to that request here in my test tab body `try{
    var data= JSON.parse(responseBody);
    console.log(data);
    tests["Status code is 200"] = responseCode.code === 200;

}
catch(e)
{
    console.log("Unable to send this request :"+e);
}`

4. Run this collection multiple times using collection run and use different number of iterations.

### Screenshots or Videos

[screen-capture.zip](https://github.com/postmanlabs/postman-app-support/files/8954608/screen-capture.zip)

### Operating System

Windows

### Postman Version

9.22.2

### Postman Platform

Postman App

**Comment by malvikach** [comment]
@sanket3080 thanks for reporting this. Apologies for your experience. 

We are aware of this issue (reported originally [here](https://github.com/postmanlabs/postman-app-support/issues/9862))

The actual test runs only once (you can confirm this via console). This is a UI Bug where the Results shows that the test ran twice even though it only ran once. I understand it might be confusing. Please feel free to try it out and confirm if the test is running more than once for you.

Our team will be picking this up soon. 

I am going to close this ticket and provide updates regarding this bug on the former ticket.
