### ISSUE TITLE
Crash after update

### ISSUE THREAD

**Issue by nashokin** [a85/POSTMan-Chrome-Extension#11035]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Postman crashes after auto update. Using Windows 11 on arm64 device, Surface Pro X. All latest updates, from the release/stable stream is installed.

### Steps To Reproduce

1. Download the latest installer, 9.21.3 in this case
2. Install and run
3. Postman will do the auto update in the background, activating it manually will produce the same issue
4. After restart Postman crashes with an error trace, screenshot attached, also the error json below
[error.zip](https://github.com/postmanlabs/postman-app-support/files/8983780/error.zip)

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/6571738/175756177-9bea0043-4277-481a-b56a-fc91bd8f955b.png)

### Operating System

Windows 11, arm64

### Postman Version

9.21.3

### Postman Platform

Postman App

**Comment by kamalaknn** [comment]
Hey @nashokin could you share the logs from `View -> Developer -> View logs in Explorer` with us through `help@postman.com`?

**Comment by nashokin** [comment]
Started to work fine after latest update v9.23.1, will close this issue and share the logs to email anyway.
