### ISSUE TITLE
Monitoring continues after workspace is deleted

### ISSUE THREAD

**Issue by carlosnizolli** [a85/POSTMan-Chrome-Extension#11039]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Monitor keeps enabling and sending alerts even after deleting the workspace

### Steps To Reproduce

1. Create a workspace
2 . Create a Collection and Monitor
3 . Delete the workspace

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/55762776/175934416-335bb2b2-cb22-4f48-9684-d81e4c4e233c.png)
![image](https://user-images.githubusercontent.com/55762776/175934525-17976fc1-3d54-449d-9a37-30e0b42eccd1.png)

### Operating System

Linux Mint

### Postman Version

8.10.0-canary210729-1340

### Postman Platform

Both

### Additional Context?

Workspace deleted a long time ago, there was another version of postman at this time

**Comment by postman-staff** [comment]
Hi @carlosnizolli,

Sure, we will be happy to help you resolve this case.
Could you submit a support request here: https://support.postman.com/hc/en-us/requests/new which should help us gather user details for the account that continues to see these notifications.

Awaiting your response.

via @Raj-postman | Postman Support

**Comment by postfrzero** [comment]
This should be fixed as of ~July 18.
