### ISSUE TITLE
Environment causes postman to crash repeatedly 

### ISSUE THREAD

**Issue by chantelope** [a85/POSTMan-Chrome-Extension#1103]
I have an environment that stores a large number of variables on some occasions. This causes postman to crash, when I try to restart postman it repeatedly crashes chrome as it tries to load the environment.

The only solution I have found is to reinstall postman each time this happens, is there a limit to the amount of variables that can be stored? Any suggestions how to deal with this?

**Comment by abhijitkane** [comment]
There's no limit. What's the approximate number of variables that you have stored?

**Comment by chantelope** [comment]
I've not been able to recover  any of my collections after the latest reinstall, I emailed my username/email yesterday. Request 1247

**Comment by chantelope** [comment]
This is with sync I must add, I have older versions uploaded to my account

**Comment by chantelope** [comment]
I have tried signing out/in, sync is 'connecting' until I try to force sync. This then generates the below errors:

Failure to sync.Backbone.Model.extend._handleNewSyncResponse @ requester.js:27207(anonymous function) @ requester.js:27132serverResponded @ sails.io.js:362c.onPacket @ sails.io.js:2d.onPacket @ sails.io.js:2c.onPacket @ sails.io.js:2c.onData @ sails.io.js:2d.open.websocket.onmessage @ sails.io.js:2

9:33:33.174 - Sync operation returned malformed message (no message.own): {"headers":{"Access-Control-Allow-Origin":"","Access-Control-Allow-Credentials":"","Access-Control-Allow-Methods":"","Access-Control-Allow-Headers":""},"statusCode":403}Backbone.Model.extend.error @ requester.js:26506Backbone.Model.extend._handleNewSyncResponse @ requester.js:27216(anonymous function) @ requester.js:27132serverResponded @ sails.io.js:362c.onPacket @ sails.io.js:2d.onPacket @ sails.io.js:2c.onPacket @ sails.io.js:2c.onData @ sails.io.js:2d.open.websocket.onmessage @ sails.io.js:2

**Comment by abhijitkane** [comment]
We're seeing heavy loads on our servers which is causing some logins to fail. We're working on stabilizing the system.

That being said, any data that was synced will be on the server, and will be recoverable.

**Comment by chantelope** [comment]
I can now sync. To answer your original question, there are 1600 variables stored in what I believe to be the offending environment

**Comment by chantelope** [comment]
I think this a hardware problem rather than a Postman problem after further investigation, running certain test uses all available memory and crashes Chrome
