### ISSUE TITLE
Rippling x Postman

### ISSUE THREAD

**Issue by Raj-postman** [a85/POSTMan-Chrome-Extension#11045]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

Requesting Postman integration with Rippling.

### Describe the solution you'd like

To be able to manage organisation Postman user accounts through Rippling and enable Single Sign-on for employees.

### Describe alternatives you've considered

None

### Additional context

_Filed by Product Support_

**Comment by ArjunSingh-PM** [comment]
We are happy to inform you that Postman is now available in the Rippling App shop. Here is the direct link for the app - https://app.rippling.com/app-shop/app/postman
