### ISSUE TITLE
Cannot generate collections with examples using Postman public API

### ISSUE THREAD

**Issue by alno74d** [a85/POSTMan-Chrome-Extension#11040]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

When generating a collection from postman GUI I can generate the request parameters based on the schema or the example:
 <img width="626" alt="image" src="https://user-images.githubusercontent.com/16304323/176099311-810bd61f-8242-4fc5-97f6-b5eaa66260e0.png">

But when using the postman API endpoint:
https://www.postman.com/postman/workspace/postman-public-workspace/request/12959542-aab6039a-c565-4c18-b94c-b80381e303ca

I couldn't find which parameter to use to generate the collection with examples instead of schemas:
<img width="635" alt="image" src="https://user-images.githubusercontent.com/16304323/176100652-fe2dc169-1521-4e4b-acd1-bbd26e3fccc8.png">

Could you let me know how to do it with the postman API call ,even if for now we can work with the postman GUI and generate the collection with examples, it will become unsustainable soon?

### Steps To Reproduce

1. Make sure your API has examples defined in its Swagger/OpenAPI defintion
2. Use the API to generate the collection
3. Collection is generated with schema only

### Screenshots or Videos

N/A

### Operating System

macOS

### Postman Version

9.14.0

### Postman Platform

Both

### Additional Context?

N/A

**Comment by shruti-paranjape** [comment]
Thank you for reporting the issue. This feature is now available via the API. You can find all details in this [documentation](https://www.postman.com/postman/workspace/postman-public-workspace/request/12959542-aab6039a-c565-4c18-b94c-b80381e303ca?ctx=documentation).
