### ISSUE TITLE
Save API response to a file

### ISSUE THREAD

**Issue by 46053683LewisB** [a85/POSTMan-Chrome-Extension#11046]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

Good Morning,
I'm using Postman to send requests. The results from one are used as the variable for a second API. The first API produces a series of URi's and i can pick one, but only one, and use it in the second API call. If i create a file manually and use that as part of a collection run all values are acted upon.
The problem is that i can't automate the production of the file from the first API. The only solution seems to be to use Newman CLI, but that needs Node.js and node.js will not run on our build of Windows 10. A build released by the IT department due to policy and security limitations. 

### Describe the solution you'd like

I would like a non node.js way of saving API responses to a file.

Is it something that may be in the development pipeline as a future update, to be a function from within Postman natively itself ?

**Comment by giridharvc7** [comment]
@46053683LewisB Have you considered using Pre-request/test scripts to perform this? You can also create a [Flow](https://learning.postman.com/labs/postman-flows/getting-started/flows-overview/#:~:text=Welcome%20to%20Postman%20Flows%2C%20a,right%20in%20your%20Postman%20workspace.) for this use case

**Comment by 46053683LewisB** [comment]
Hi,
I have, but neither options will produce a .json file from the response of a request without a node.js.  Be great if i'm wrong.
I'm going to see if a mock server may help.
Thanks.

**Comment by giridharvc7** [comment]
Can you help me understand why you need the response to be saved as a file?

**Comment by 46053683LewisB** [comment]
Hi,
Yes of course.  I need to eventually be able to target the response .json file via Power BI.

The API produces a .json body that is a list of records.

Thanks,
Lewis.

**Comment by shubhbhargav** [comment]
@46053683LewisB Unfortunately, Postman as an app doesn't have the access to write files on the system directly. One way to do that would be to run a local server which can write the data to a file.

In this case, you can do the following:

1. Call the APIs that you are calling in Postman as it is
2. Store the response from the API call in Postman runtime variable with something like this `pm.variables.set(...)`
3. Call the local server with the payload as the response from the above request / stored Postman runtime variable
4. Refer to the file created by local server

Let me know if this serves your use-case. :)

**Comment by 46053683LewisB** [comment]
Hi, 
Thank you for this shubhbhargav, but wouldn't this need the node.js ? I am making progress in getting a special build to allow node.js and Newman etc.. but i was still hoping for a more direct solution.

**Comment by shubhbhargav** [comment]
@46053683LewisB Assuming that you are referring to Step 3, no it won't explicitly require node.js. You can use any language to build that local server. For example, in Python, you can do something like this: https://stackoverflow.com/a/13146494

**Comment by 46053683LewisB** [comment]
Hi shubhbhargav,
I appreciate this and will definitely look into the link you provide.  Sadly the issue is the same as Python and similar set ups are outlawed by our Windows build.  This isn't the first time i have been blocked by our build and security and am campaigning for a more open dev platform.  There is weight and appetite for this.  Quite frankly we can't carry on like this. 
I have Python on one of my dev servers but that's restricted by no internet access.
Thank you.

**Comment by shubhbhargav** [comment]
I see. Thanks for the feedback @46053683LewisB. We will see what we can do here in the future but it's unfortunately a limitation as of now. :(

**Comment by 46053683LewisB** [comment]
HI, 
Thank you for your time on this.  I think it would be a very welcomed addition\improvement to an already excellent application.
I am winning my push for a more open dev platform and am hoping soon to be able to try the suggestions made here.
Thanks to you and all contributors for your help and suggestions.
Lewis.
