### ISSUE TITLE
Blank tabs do not close

### ISSUE THREAD

**Issue by mehrdadjavidan** [a85/POSTMan-Chrome-Extension#11044]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Blank tabs are created that do not close. They will duplicated(by clicking Duplicate tab), but not closed, even by Force Close All Tabs.

### Steps To Reproduce

- - -

### Screenshots or Videos

![2022-06-28_16-08-05](https://user-images.githubusercontent.com/31864084/176171531-6b79df3f-d79c-43a8-adf0-a25d3353d81e.png)

### Operating System

Windows

### Postman Version

9.23.1

### Postman Platform

Postman App

### Additional Context?

UI Version 9.23.1-ui-220624-1005

Desktop Platform Version 9.22.2

Architecture x64

OS Platform win32 10.0.19044

**Comment by mehrdadjavidan** [comment]
![2022-06-28_16-08-05](https://user-images.githubusercontent.com/31864084/176171326-95cfb5b2-ecbe-48bf-b45a-06fb339ad321.png)

**Comment by DannyDainton** [comment]
Hey @mehrdadjavidan 

If you use the `Help > Clear Cache and Reload` option, does that remove the tabs?

**Comment by mehrdadjavidan** [comment]
> Hey @mehrdadjavidan
> 
> If you use the `Help > Clear Cache and Reload` option, does that remove the tabs?

Hi,

Yes, solved by `Help > Clear Cache and Reload`

Thanks a lot
