### ISSUE TITLE
Allow specifying Content Type on single part of a Multipart request

### ISSUE THREAD

**Issue by derickson82** [a85/POSTMan-Chrome-Extension#1104]
Currently, when creating form-data, I have the option of specifying Text or File for each key-value pair. I would like to be able to specify the content type per key-value pair.

My particular use case involves posting an image as one part, and json data as another part, and I would like to set the ContentType header on that second part as 'application/json'.

**Comment by a85** [comment]
The Content-Type would still have to be multipart/form-data. You can not have a Content-Type for individual key-value pairs as far as I know. The server handling this requests would only process multipart/form-data properly

**Comment by derickson82** [comment]
Take a look at the spec: https://www.ietf.org/rfc/rfc2388.txt

In Section 3, it indicates that each Part has a Content-Disposition header, and can optionally specify a Content-Type header.

As a server side example, Spring MVC accepts individual parts of a request using the [@RequestPart](http://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/web/bind/annotation/RequestPart.html) annotation, which uses the Content-Type of the part to route to the appropriate message converter.

There is equivalent client side support in Spring's RestTemplate. I'm not sure what support other client libraries in other languages have.

Granted, this isn't a common case, but it is one that I'm using in a REST API that I am developing.

Hope that helps.

**Comment by neoscrib** [comment]
I second this. Just tried to do something similar and noticed that postman leaves the Content-Type header of the individual part blank.

**Comment by odays** [comment]
I would also like to see this implemented as I have the same requirement as above for testing an api

**Comment by ghost** [comment]
Hello, we started using Postman recently, and think it's an awesome tool for visually accessing our API.
Specifying Content-Types for each multipart would be a great feature, since we are sending Commands (as in CQRS) and files together in one request.

UPDATE: Two years later (2017), we changed our API so that we do not need this feature anymore. Instead, binary file data and document metadata are sent in different requests.

**Comment by gandesc** [comment]
+1 for this. I have the exact user case as the OP and can't use Postman for testing it.

Also, one can achieve this with curl:

curl -v -X POST http://localhost:8080/api/file \
        -F 'doc={"hello":"world"};type=application/json'

This makes a POST request as multipart and sets the doc part to be of type application/json.

**Comment by lucasfsousa** [comment]
+1
Same thing here...

**The Content-Type is specified only when the part its a file.**

POST /api/test HTTP/1.1
Host: localhost:8080
Cache-Control: no-cache
Postman-Token: e5f34cda-e0ef-15d6-23d6-eff6698fb776
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

----WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="logo"; filename="Chrysanthemum.jpg"
**Content-Type: image/jpeg**

----WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="text"

xpto
----WebKitFormBoundary7MA4YWxkTrZu0gW

**Comment by ghost** [comment]
+1 for me too.

**Comment by derickson82** [comment]
There is another option for my use case, specifically a 2 part upload, one image and one json file. When both parts are "File" uploads, instead of "Text" for the json, a file with the ".json" extension will have the Content-Type set to "application/json".

While this does work, it also means that I have to select 2 files instead of 1 every time, and the json content is not saved to the collection.

```
POST /multipart/endpoint HTTP/1.1
Host: example.com
Cache-Control: no-cache
Postman-Token: ef87afb9-b9cf-e05f-0e77-9e126a1d45da
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

----WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="imageFile"; filename="test.png"
Content-Type: image/png


----WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="data"; filename="content.json"
Content-Type: application/json


----WebKitFormBoundary7MA4YWxkTrZu0gW
```

**Comment by wind57** [comment]
+1 
curl can do it, would be nice if postman would

**Comment by ghost** [comment]
+1 to this

**Comment by ipsi** [comment]
Exactly the same use case as @derickson82 - this would be very helpful.

**Comment by ghost** [comment]
This would be really useful. For now CURL will have to do. 👍

**Comment by Tillman-Z** [comment]
+1

**Comment by ticklemepierce** [comment]
+1

**Comment by hearlapati-phunware** [comment]
+1

**Comment by benkimball** [comment]
It would be helpful to have this for interacting with the Docusign REST API. Creating a Docusign envelope from a local Word document involves posting to an endpoint with multipart/form-data where the first part must be tagged with `Content-Type: application/json` and the second part is the Word document. In the meantime I will try @derickson82's suggestion of using two local files, one for json and one doc.

**Comment by janpetzold** [comment]
+1

**Comment by cecchisandrone** [comment]
+1

**Comment by ne0d1n** [comment]
+1

**Comment by kimbilida** [comment]
+1

**Comment by eugene-sotirescu** [comment]
+1

**Comment by pokraev** [comment]
+1

**Comment by lakkarajumurali** [comment]
I'm also having the same issue.  The Content-Type: application/json;  should be added to the second part of the form data but it is not getting added.  Is there any other way to add that content-type for the second block?

------WebKitFormBoundaryWkPZB6PYQfS04Pa6
Content-Disposition: form-data; name="file[]"; filename="matter.txt"
Content-Type: text/plain


------WebKitFormBoundaryWkPZB6PYQfS04Pa6
Content-Disposition: form-data; name="metadata"

{"filename": "test1.txt",    "fileType": "plain/text",    "parent":null,    "Type": null,    "state": "fiddlerState",    "sourceType": "type",    "fileDisplayName": null,    "tags": [ "abc" ]}
------WebKitFormBoundaryWkPZB6PYQfS04Pa6--

**Comment by nvnikolov** [comment]
+1

**Comment by samcreate** [comment]
+1

**Comment by bhaupt** [comment]
+1

**Comment by hollinwilkins** [comment]
+1

**Comment by starchen** [comment]
+1

**Comment by fb-datax** [comment]
+1

**Comment by wildest** [comment]
+1 !!

**Comment by newbray** [comment]
+1

**Comment by romanwozniak** [comment]
+1

**Comment by tejaskemkar** [comment]
+1

**Comment by squidcrash** [comment]
+1

**Comment by tadesamson** [comment]
+1
I'm also in support of this.  unable to test my api server using postman due to this restriction.

**Comment by florian-krueger** [comment]
+1

**Comment by stebielli** [comment]
+1

**Comment by GhaythFuad** [comment]
+1
Please support this.

**Comment by brickapi** [comment]
+1

**Comment by dancmc** [comment]
+1

**Comment by ngoossens** [comment]
+1

**Comment by codding-buddha** [comment]
+1

**Comment by albpoz** [comment]
+1

**Comment by Hossrod** [comment]
Ouch, how can this not be supported by now, especially with all these +1. I'm blocked from using Postman for my work right now because of this.

Unfortunately, I tried the suggestion to use File for the json part and point to a file with .json extension, but it still didn't work (the server complains that the json parts content type is `application/octet-stream`) . So not sure if that work around no longer works or I'm doing something wrong.

Curl however works just fine... `-F JSONDATA=@request.json;type=application/json`

**Comment by albpoz** [comment]
Does someone know an alternative tool capable to handle the issue?

**Comment by Hossrod** [comment]
@albpoz, don't know your requirements, OS, etc., but [curl](https://curl.haxx.se/) and [fiddler](http://www.telerik.com/fiddler) are a couple.

**Comment by MarkBramnik** [comment]
+1 here

**Comment by albpoz** [comment]
A good tool able to submit multipart request specifying Conten-Type for every single part is SoapUI

**Comment by markdou812** [comment]
+1

**Comment by artisom** [comment]
+1. Why this request is ignored for  > 2 years. sad face

**Comment by ayampols** [comment]
+1

**Comment by jonathanwiesel** [comment]
+1

**Comment by prinzdezibel** [comment]
+1

**Comment by aceport** [comment]
+1

**Comment by arci** [comment]
+1

**Comment by spati-java** [comment]
@postman-admin  team please help, it seems million of us need this feature. Please fix this issue.

**Comment by abelsromero** [comment]
+1 I think this should be implemented.
Also, it seems weird to me, that even if you add the content-type into a form field, it its ignored by Postman, BUT! when using the `code` -> `curl` feature, the command generated includes it and works fine.

**Comment by pinfrederic** [comment]
+1

**Comment by whotakekajibu** [comment]
+1

**Comment by whotakekajibu** [comment]
[Uploading multiple files each with their own Content-Type is not supported yet.](https://www.getpostman.com/docs/postman/sending_api_requests/requests)

**Comment by lef-nicolas** [comment]
+1 

And the possibility to set our own "ContentID" for each part :)

**Comment by gyuuu** [comment]
+1

**Comment by rdehouss** [comment]
+1

**Comment by vishwasec** [comment]
+1

**Comment by Charles-AndreMartin** [comment]
+1

**Comment by mniyaz** [comment]
+1

**Comment by kitkittan** [comment]
+1

**Comment by vijaykiran225** [comment]
+1 this would be a huge win as so many apis are looking to accept multipart and we could hit it and test it in postman itself.

**Comment by purvesh007** [comment]
+1

**Comment by carlosber** [comment]
+1

**Comment by Arbitrary-T** [comment]
+1

**Comment by javiersuweijie** [comment]
+1

**Comment by shamasis** [comment]
@kamalaknn our requested supports `contentType` with form data. We need to accept it from outside. We need to add another column in UI?

**Comment by TheParad0X** [comment]
+1

**Comment by Nemowxy** [comment]
+1

**Comment by cebbens** [comment]
+1

**Comment by leantorres73** [comment]
+1

**Comment by frahugo** [comment]
+1

**Comment by dcp65** [comment]
Come on guys, with [Swagger Inspector](https://swagger.io/swagger-inspector/) now on the scene, you finally have some competition. Time to give the people what they want.

**Comment by fabriziocucci** [comment]
+1

**Comment by ghost** [comment]
+1

**Comment by andersonkxiass** [comment]
+1

**Comment by mcordeiro73** [comment]
+1

**Comment by Snickdx** [comment]
+1

**Comment by Max-Riley** [comment]
+1

**Comment by pieralexandre** [comment]
+1

**Comment by lgroger** [comment]
+1

**Comment by propi** [comment]
+1

**Comment by aseemgautam** [comment]
+1

**Comment by amberream** [comment]
+1

**Comment by ecsdigitalih** [comment]
+1

**Comment by stoan** [comment]
It would be great if Postman can support this.

Advanced Rest Client supports this

advancedrestclient.com

![image](https://user-images.githubusercontent.com/2737659/39100622-a2efe304-468c-11e8-998c-a961f5ba5bed.png)

**Comment by anujbhatia** [comment]
+1

**Comment by smrnv** [comment]
+1

**Comment by saltysealion** [comment]
+1

**Comment by da-benny** [comment]
+1

**Comment by me2resh** [comment]
+1

**Comment by Macoshark** [comment]
+1

**Comment by SamuelKupferschmid** [comment]
+1

**Comment by 7artur7** [comment]
+1

**Comment by ghost** [comment]
+1

**Comment by asmoker** [comment]
+1

**Comment by ben-sharp** [comment]
+1

**Comment by DallinEvans** [comment]
+1

**Comment by Charles-AndreMartin** [comment]
+1

**Comment by BraianS** [comment]
+1

**Comment by sgornostal** [comment]
+1

**Comment by CapitalDecay** [comment]
+1

**Comment by aalezhnin** [comment]
+1!!!!

**Comment by ionutincau** [comment]
+1

**Comment by pearsontophergopher** [comment]
+1

**Comment by pearsontophergopher** [comment]
+1

**Comment by Kabal163** [comment]
+1

**Comment by renijangkrik2014** [comment]
I would love to understand Http or something else. Because I am currently working on the Internet marketring. To do with my work ... Where can I learn? 

[https://www.obat-asam-lambung.com/](https://www.obat-asam-lambung.com/)

**Comment by kamil-zielinski** [comment]
+1

**Comment by dtsap** [comment]
+1

**Comment by swateek** [comment]
+1

**Comment by vlott** [comment]
+1

**Comment by efreibe** [comment]
+1

**Comment by VR-Architect** [comment]
+1

**Comment by HaoyuBian** [comment]
+1

**Comment by cedric-jonas-kisters** [comment]
+1

**Comment by MinaZakaria** [comment]
+1

**Comment by pkoetzmv** [comment]
+1

**Comment by abelsromero** [comment]
This post is becoming a recurring joke. It'd be nice to have some official response

**Comment by ghost** [comment]
+1

**Comment by shamasis** [comment]
@abelsromero this is official: https://github.com/postmanlabs/postman-runtime/pull/623 ❤️ 

this is going out soon.

**Comment by manishbhatt94** [comment]
Has this feature landed in Postman app? If yes, how to use it?

**Comment by 433845** [comment]
I want to use this feature, if it is in the app, can someone show me a screenshot of how to use it with a form-data widget of type "file"?

**Comment by KingdomOfEnds** [comment]
+1 for me too :) Thanks!

**Comment by KingdomOfEnds** [comment]
**Ninja update:** Not sure if this will help anyone else but there is a workaround for a specific scenario where you have multiple file types / content types being uploaded in a single multipart POST request.

1. Set the Header `Content-Type` to `multipart/mixed`.
1. Select the `form-data` option in `Body`.
1. Convert all of your items into files. String content should become a text file, etc.
1. Add each file by selecting `file`, adding a key name.

This approach doesn't require actually manually specifying each `Content-Type` or `Content-Disposition`. The trick here was to serialize all relevant content into a persistent file type. You can ignore the "convert it into a file" step if it's text :) Hope that helps someone!

**Comment by shamasis** [comment]
This has been fixed in latest Postman App. Have attached screenshot!! If you don't see the content-type column in form-data, then simply select visibility of the column by clicking the three dots on top-right of the table area. :-p

<img width="917" alt="Screenshot 2019-03-18 at 19 25 47" src="https://user-images.githubusercontent.com/232373/54535034-abb12e00-49b3-11e9-8aca-454de95ccadc.png">

**Comment by mrmarcgoldstein** [comment]
Sadly this enhancement did not work for me. Although I could add the Content Type fields, they were not reflected in the outgoing HTTP request:

Entered Values:
![image](https://user-images.githubusercontent.com/49071291/55243174-97342780-5236-11e9-8fe1-58824090014b.png)

Resulting HTTP (from Postman Console):
![image](https://user-images.githubusercontent.com/49071291/55243290-ccd91080-5236-11e9-90df-a33082bca619.png)

**Comment by only-gale** [comment]
What about `Content-ID` for each part?

**Comment by neoscrib** [comment]
Well you didn't specify a use case, but Content-Id is really only useful for email (see https://tools.ietf.org/html/rfc2392). Otherwise you're doing something largely non-standard. Either way, good luck getting Content-Id... It took four years just for Content-Type.

**Comment by simlegate** [comment]
What about `Content-Disposition` for each part?

it seems that there is no field `filename*` in `Content-Disposition` and the field must be provided in some cases.

**Comment by JulienErdogan** [comment]
+1. This just doesn't work for now. Postman does not allow to make proper multipart/mixed requests.

**Comment by constantins2001** [comment]
+1. Content-Disposition needed

**Comment by iasenov** [comment]
Why closed?
I need to send multipart mixed content with some custom headers in each part.
With cUrl it is possible,but not with postman :( :( :(

**Comment by iVova** [comment]
+1
Please, introduce this useful feature.

**Comment by alfredo-rgzm** [comment]
+1

**Comment by dpond** [comment]
+1

**Comment by likhitgatagat** [comment]
+1. Content-Disposition is needed, currently there is no field filename* in Content-Disposition and the field must be provided in some cases.

**Comment by arlemi** [comment]
This is tracked in https://github.com/postmanlabs/postman-app-support/issues/8203, please subscribe to the issue there to be notified when there are any updates. 🙂

**Comment by muscal** [comment]
> #8203
@simlegate ,
Have you been able to find a workaround for adding in `filename` for application/pdf content-types?

**Comment by mrmarcgoldstein** [comment]
Hi,No, unfortunately I have not. I gave up and stopped looking a while ago, but I'm interested if you found a way.. Thanks Marc On 4 Oct 2022 14:54, Alex Levy ***@***.***> wrote:

#8203

Have you been able to find a workaround for adding in filename for application/pdf content-types?

**Comment by SusanTWhite** [comment]
Is there a discord for Postman? I have a problem l think is related to these:
I thought it  was supposed to have been working already. Am I wrong? The GUI has the file defined as type file with keyword file and the request submits and returns with 200 OK, but the generated file isn't getting picking up the file, but instead shows it as undefined (as opposed to null in an invalidly defined param)
![image](https://github.com/postmanlabs/postman-app-support/assets/18631651/91aa8052-afdd-4e59-b736-fefd2f0cd327)

Authorization: Bearer value
User-Agent: PostmanRuntime/7.32.2
Accept: */*
Postman-Token: 583b325d-1ab3-4067-aab9-a348de061e3f
Host: localhost:80
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
Content-Type: multipart/form-data; boundary=--------------------------value
Cookie: jwt=value
Content-Length: value
Request Body
_**file: undefined**_
data: "{
	"field1": "7ca3fd6a-be76-4f9e-be76-17f4a9a11530",
	"field2":"a190acc3-ffa5-4baf-ffa5-aecd5ec8f80b",
	"dataDate": "2024-06-136T13:23:28.348",
}"

**Comment by TsengSR** [comment]
Is this project dead or what? 10 year and such a simple requirement thats essential for testing multipart/form-data with attachment is not implemented yet? Wow...
