### ISSUE TITLE
Variables in raw JSON body strings should be escaped

### ISSUE THREAD

**Issue by francisbooth** [a85/POSTMan-Chrome-Extension#11049]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

When using variables within the raw body of a request sent as JSON, if the variable is passed within a string, I would expect the variable to escaped in the request.

### Steps To Reproduce

1. Create an variable (environment or global), e.g. `foo="\"`
2. Create a request
3. Select "body" tab
4. Choose "raw"
5. Choose "JSON" from the dropdown
6. Add a JSON object to the body, e.g. `{ "foo": "{{foo}}" }`
7. Open the code right sidebar panel ...via the sidebar icon [**</>**]
8. Inspect the request...

_What I see:_ `--data-raw '{ "foo": "\" }'` ← backslash not escaped
_What I would expect:_ `--data-raw '{ "foo": "\\" }'` ← N.B. escaped backslash

### Screenshots or Videos

<img width="943" alt="unescaped-backslash" src="https://user-images.githubusercontent.com/24528667/176456954-80a03786-0b16-4132-ace8-4e5da982cf92.png">

### Operating System

macOS

### Postman Version

9.21.5

### Postman Platform

Postman App

**Comment by francisbooth** [comment]
For more context... this is avoidable by reading the `foo` var and writing it as an escaped string to a temp var via a pre-request script and then adding `escapedFoo` to the JSON body.

This would be inconsistent with vars being contextually escaped in the URL context (for example) though.

**Comment by akshaydeo** [comment]
@francisbooth, thank you for reporting this issue. We are looking into fixing this; I will update the ticket as soon as we push the fix 🙇‍♂
