### ISSUE TITLE
Error when importing a JSON file

### ISSUE THREAD

**Issue by venkatj1983** [a85/POSTMan-Chrome-Extension#11042]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Getting error message on importing json file. When 2 collection got exported and merged into single, after importing the latest json file getting the following error message "Error while importing: format not recognized

### Steps To Reproduce

1. Export a existing collection 1
2. Export a existing collection 2
3. Merge both the collection 1 & 2 through some json merge tools
4. Import the newly merged collection json file.

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/108135236/176157450-943bb85c-fe7f-4608-999a-018ad58119f5.png)

### Operating System

Windows

### Postman Version

9.23.1

### Postman Platform

Postman App

**Comment by DannyDainton** [comment]
Hey @venkatj1983 

Can you elaborate more on point 3, please? What was the final outcome of this merging of the files, can you share a copy of the Collection.

The structure of the Collection needs to be valid for it to be imported, I'm not sure of the merged files structure.

**Comment by akshaydeo** [comment]
@venkatj1983 closing this issue for now. Feel free to reopen if you are still facing this issue 🙇‍♂
