### ISSUE TITLE
gRPC: Display additional payload for errors

### ISSUE THREAD

**Issue by moshest** [a85/POSTMan-Chrome-Extension#11052]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

As solved on https://github.com/postmanlabs/postman-app-support/issues/10670, there is a need to see more detailed information regarding the server error beside the error code or message.

In many cases, Google and other service will return an additional `details` property with more structural data regarding the error occurred. The full spec written by Google is here: https://cloud.google.com/apis/design/errors#error_model

### Describe the solution you'd like

As there is no definition for the `details` property, it would be best if the user will able to see the raw data sent by the server and also parse it given a [predefined list of error payloads](https://cloud.google.com/apis/design/errors#error_payloads) or provide a custom error payload to parse for.

### Additional context

In my own environment I wan't able to see the raw data responded from the server, not even on the console. This make it very hard to debug and see the actual payload returned by the server on errors.

**Comment by codenirvana** [comment]
@moshest can you share an API or a scaled-down local server that we can use to test this behavior?

**Comment by moshest** [comment]
Yes, please check https://grpcb.in for common gRPC use cases.

You can test and see the error details via `grpcurl`:

```bash
# insecure
grpcurl -plaintext -d '{}' grpcb.in:9000 grpc.gateway.examples.examplepb.ABitOfEverythingService/ErrorWithDetails

# TLS
grpcurl -d '{}' grpcb.in:9001 grpc.gateway.examples.examplepb.ABitOfEverythingService/ErrorWithDetails
```

Response:
```
ERROR:
  Code: Unknown
  Message: with details
  Details:
  1)	{"@type":"type.googleapis.com/google.rpc.DebugInfo","detail":"error debug details","stackEntries":["foo:1"]}
```

**Comment by codenirvana** [comment]
@moshest We've added support for decoding additional error details in Postman v9.29.

Currently, we support [error_details.proto](https://github.com/googleapis/googleapis/blob/master/google/rpc/error_details.proto) types. Everything else is represented in binary form.

![Screenshot 2022-08-19 at 4 25 12 PM](https://user-images.githubusercontent.com/4865836/185603853-41cf3fd2-2e61-4d17-9f1a-34b93c35ddba.png)

**Comment by moshest** [comment]
Amazing. Thanks!
