### ISSUE TITLE
gRPC: TLS not enabled when using environment variable on server url

### ISSUE THREAD

**Issue by moshest** [a85/POSTMan-Chrome-Extension#11057]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

When using a variable on gRPC server URL, I see an alert under the "Authorization" tab: "Insecure connection". When switching back to the variable plain value, the warning disappeared and the request made with TLS.

### Steps To Reproduce

1. Create new gRPC request
2. Fill up a secured server url and port (e.g. `grpcb.in:9001`)
3. Open postman settings and setup a certificate for this hostname & port (see [instructions](https://github.com/postmanlabs/postman-app-support/issues/10533#issuecomment-1173052868))
4. Verify warning message under "Authorization" tab disappeared and you can send secured calls
5. Create an environment variable `GRPC_SERVER_URL` with the server url (e.g. `grpcb.in:9001`)
6. Replace the server url with the created variable (e.g. `{{GRPC_SERVER_URL}}`)
7. You will see the warning under "Authorization" tab turning back on and you can't query the server anymore

### Screenshots or Videos

<img width="730" alt="image" src="https://user-images.githubusercontent.com/534911/177042712-a04eecac-2fbf-45a3-bca7-dbe6ca05ecf6.png">
<img width="730" alt="image" src="https://user-images.githubusercontent.com/534911/177042749-4b61106f-bffb-4f04-bd84-70e7cf3bc308.png">

### Operating System

macOS

### Postman Version

9.23.3

### Postman Platform

Postman App

**Comment by codenirvana** [comment]
@moshest Thanks for reporting this issue.

This is fixed along with the recent improvements to the TLS configuration flow.
Refer https://github.com/postmanlabs/postman-app-support/issues/10533#issuecomment-1200266682 for more details.
