### ISSUE TITLE
Environment Globals are not shared using Workspace

### ISSUE THREAD

**Issue by RoyLeibo** [a85/POSTMan-Chrome-Extension#11059]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Hi,

My team has a Workspace account.
We have several environments, each one with its own variables.

We are also using Globals variables since our environments share some similar variables.

I have updated the variables and their value and for some reason, no one on my team can't see their values.
I have tried to update them in both desktop & web apps and it is not working.

*The environment variables were shared successfully.

### Steps To Reproduce

1. Open a shared workspace
2. Create 3 environments with variables
3. Create Globals variables
4. Access the workspace from another account
5. Check if the Global variables has values

### Operating System

macOS

### Postman Version

9.22.2

### Postman Platform

Both

**Comment by DannyDainton** [comment]
Hey @RoyLeibo 

Would you be able to share some visual examples of the UI and the area that this is impacting? As you're describing something you see in the UI, it will help us to understand what you have in front of you.

**Comment by RoyLeibo** [comment]
Hi @DannyDainton, thank you for answering.
This is what I created:
<img width="1583" alt="image" src="https://user-images.githubusercontent.com/42297127/177164892-a08208c1-e9bd-4801-b9ce-b1a9af91afac.png">

And this is what one of my colleagues see:
![image](https://user-images.githubusercontent.com/42297127/177165069-af414b67-b953-4616-af2f-f81aa811df38.png)

**Comment by DannyDainton** [comment]
The `Current Values` are not synced to Postman and are only available to you. That would mean that your teammates wouldn't see them.

> The Initial Value is synced to your account using the Postman servers. It's shared with any collaborators who have access to the environment.
The Current Value is used in your local instance of Postman, and is never synced to your account or shared with your team unless you choose to persist it.

You can either use the `Persist All` option to set _all_ the Current values to the Initial Values or that can be done against each variable if there are ones that you don't want anyone else to see (API Tokens, Passwords, etc.). Once saved, your team will also see these.

**Comment by RoyLeibo** [comment]
@DannyDainton works! thanks

**Comment by DannyDainton** [comment]
Awesome. Closing this one out.
