### ISSUE TITLE
Implement bulk edit option in collection and environment variables

### ISSUE THREAD

**Issue by sseenivasan89** [a85/POSTMan-Chrome-Extension#11058]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

Hi Team,

Implement bulk edit option in collection and environment variables, like what we have for Query Params and Path Params
its bit hard to edit the collection and environment variables if we have the bulk-edit option simply we can remove and update

### Describe the solution you'd like

same as what we have for Query and Path params

![image](https://user-images.githubusercontent.com/44080743/177131129-429dc08b-2515-484e-9750-5436c115be42.png)

**Comment by DannyDainton** [comment]
Same feature request as https://github.com/postmanlabs/postman-app-support/issues/4898 - Closing this is keep everything in a single place.

**Comment by gaston-haro** [comment]
You mean a single place to ignore it
