### ISSUE TITLE
Environnement selection on Mobile 

### ISSUE THREAD

**Issue by gigaga** [a85/POSTMan-Chrome-Extension#11054]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Currenlty, on mobile, from postman web, we can't select environment. The combobox is displayed but immediatly closed. 

### Steps To Reproduce

Select a collection where several environment are defined
Click on "No environment" for select one

### Operating System

Android

### Postman Version

Latest

### Postman Platform

Postman Web

**Comment by gigaga** [comment]
I tried it from several mobile browser like firebox, chrome, edge, brave and opera, samedis issue 😕

**Comment by dev-sharma-08** [comment]
Hey @gigaga,
I am trying to reproduce this but it is working fine. Can you check whether this issue still persists for you, if yes can you please share a recording with us, blurring out any sensitive information?

**Comment by gigaga** [comment]
Hi @dev-sharma-08,
I checked, but I cannot no longer reproduce this issue ;)

Regards
