### ISSUE TITLE
Beautify support for "Pre-Request Scripts"  and "Tests"

### ISSUE THREAD

**Issue by miriyald** [a85/POSTMan-Chrome-Extension#11050]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

Postman supports Running Collections and allows to write "Tests" after receiving response  ad  "Pre-Request Script" in Javascript.

Currently the Javascript code is not formattable within Postman. Postman at this point does syntax checks and recognizes keywords but doesn't enable an option to format the code. 

### Describe the solution you'd like

It would be great if "Beautify " option is enabled for Java Scripts with Postman Environment.

### Describe alternatives you've considered

Manually formatting using other IDE's

**Comment by DannyDainton** [comment]
Hey @miriyald

Does `Ctrl + B` format the test code for you? It's not a button as such but a keyboard shortcut to perform that action.

**Comment by miriyald** [comment]
Hi @DannyDainton Wow, I don't  know that `Ctrl+B`  works for Scripts.
It would be great if editor can have `Beautify` Button/Link. Otherwise there is no-clue about this feature.
![image](https://user-images.githubusercontent.com/89222052/176561510-5d944054-5e23-4d37-b0d8-36b9bb3dd8a5.png)

**Comment by DannyDainton** [comment]
Duplicate of https://github.com/postmanlabs/postman-app-support/issues/9216
