### ISSUE TITLE
Bootcamp: Environment -> Environment Variables Lesson Stops

### ISSUE THREAD

**Issue by russellward** [a85/POSTMan-Chrome-Extension#11056]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Within the Bootcamp Learning track, for Environment Variables at 20% in the lesson simply stops after entering a new variable.

Version 9.23.3
UI Version: 9.23.3-ui-220629-1055
Desktop Platform Version: 9.22.2 (9.22.2)

If you click on Continue Learning you are simply put back to 0% to Create a New Environment

### Steps To Reproduce

1. Open Bootcamp
2. Click on Environment Variables Lesson
3. Follow the lesson:
4. Click on Environments
5. Add a New Environment
6. Give the Environment a name
7. Enter a Variable name as recommended "environment_type"
8. Click Next... 
9. Lesson Stops, prompts disappear

### Screenshots or Videos

<img width="1070" alt="Screenshot 2022-07-02 at 11 05 57" src="https://user-images.githubusercontent.com/54803122/176996102-b8687678-e16d-4547-af6a-ad336e57540d.png">

### Operating System

macOS

### Postman Version

9.23.3

### Postman Platform

Postman App

**Comment by DannyDainton** [comment]
Thanks for raising the issue. 

This lesson is mentioned in the comments.

https://github.com/postmanlabs/postman-app-support/issues/10684#issuecomment-1063141573

Closing as a duplicate.
