### ISSUE TITLE
Sort Collections by "Last modified" not working

### ISSUE THREAD

**Issue by vasujain** [a85/POSTMan-Chrome-Extension#1106]
![screen shot 2015-06-03 at 5 13 06 pm](https://cloud.githubusercontent.com/assets/1364787/7974214/ddcf6dd6-0a13-11e5-9444-e4e48179f9b7.png)

Sort order is broken It shows random sort instead of timestamp based sorting.

**Comment by abhijitkane** [comment]
@vasujain Is sort-by-name working for you?

**Comment by vasujain** [comment]
@abhijitkane Realized, it is broken as well for me.

**Comment by abhijitkane** [comment]
Can you check the console for any errors? You can enable the console by following the steps at http://blog.getpostman.com/index.php/2014/01/27/enabling-chrome-developer-tools-inside-postman/

**Comment by vasujain** [comment]
@abhijitkane looks like it is part of synch issue, there seems to be duplicate ids created which might be because of synch issues i had with postman v3 like othere. Here is a screenie : 
![screen shot 2015-06-10 at 10 44 31 am](https://cloud.githubusercontent.com/assets/1364787/8089636/e85cb020-0f5d-11e5-84e5-d1dd47d94324.png)

**Comment by abhijitkane** [comment]
Hm..these errors are unrelated. We'll investigate and update this thread when we have more.

**Comment by abhijitkane** [comment]
@vasujain Can you confirm this fixed in v3.0.4?

**Comment by vasujain** [comment]
Hi @abhijitkane This issue has been resolved. Folder sort is working as expected. Thank you for fixing it. :+1:
