### ISSUE TITLE
Option to disable sending cookies from cookie jar with pm.sendRequest

### ISSUE THREAD

**Issue by alex-frx** [a85/POSTMan-Chrome-Extension#11065]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

If you try to test something related to cookies. You have to unset theme or clear the jar.

Which can be annoying if you want to keep the cookies for the next request but have separate cookie for the Test script.

### Describe the solution you'd like

A parameter that one could disabel the use of the cookie jar with `pm.sendRequest`

### Describe alternatives you've considered

Disable them in general for `pm.sendRequest` and have the user add them manually if he wants them in the request

**Comment by DannyDainton** [comment]
Hey @alex-frx 

There is a toggle at the request level that disables the cookie jar. 

![Screenshot_20220707_043023.jpg](https://user-images.githubusercontent.com/17089546/177684738-3d743e55-137a-424a-8479-e59bb9755fa2.jpg)

**Comment by DannyDainton** [comment]
Closing this as the feature is currently part of the Postman platform. 

If you're looking at something more global, there is an open feature request where you can upvote this by leaving a thumbs-up reaction. 

https://github.com/postmanlabs/postman-app-support/issues/11008

**Comment by alex-frx** [comment]
Yes i know of the toggle. But this would also disable the cookie for the "normal" http request wouldnt it?

And if you have setup a Test on collection or folder level there isn't the possibility so disable the cookie ja at all (at least i havent found it)

@DannyDainton #11008
