### ISSUE TITLE
pm.sendRequest not sending request in Test if previously unset or clear called on deleted Cookie or empty Cookie-(Jar)

### ISSUE THREAD

**Issue by alex-frx** [a85/POSTMan-Chrome-Extension#11064]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

In a Test I define a _cookie jar_ with:

`const jar = pm.cookies.jar();`

If I call `jar.clear(domain)` and the jar is already empty the script is running but `pm.sendRequest` is not sending a request. 
The same happens if you try to `jar.unset(....)` an already deleted cookie. 

**No error is throw** in the `console `oder the `callback`

---

_The weirdest part is_ if you set some arbitrary cookie before calling `jar.unset(....)` on **another, already deleted cookie** `pm.sendRequest` is sending even technically you did the same as before.

This is very weird behaviour.

### Steps To Reproduce

1. Create a new http request to some endpoint 
2. paste this script in the test
```
const domain = "localhost";
const jar = pm.cookies.jar();

//comment this out and it is working again
//jar.set(domain, "test", "hallo")


//try one or both of this lines:

//jar.clear(domain)
jar.unset(domain, "session")



pm.sendRequest('http://' + domain + ':5000/api/v1/oauth2/token', (error, response) => {
    console.log("sending")
})

console.log("test reached bottom")
```

play with the statments and check the console 

### Operating System

Windows and MacOs 

### Postman Version

9.24.0

### Postman Platform

Postman App

**Comment by DannyDainton** [comment]
Hey @alex-frx

Could you provide some visual examples or a short recording of what you can see on your side, please?

Could you provide details of what you have in the allowedlist in the cookie section, this holds the information about which domains tgat can be used programmatically with `pm.cookies.jar()`.

Is there any more details you can provide about that local service you're hitting?

Are you able to replicate this using a public service that we can use on our side?

**Comment by DannyDainton** [comment]
@alex-frx 

Could you give the steps in this a go, please? Just to confirm that you have access to the cookie jar for that domain.

https://github.com/postmanlabs/postman-app-support/issues/9930#issuecomment-840002856

**Comment by alex-frx** [comment]
yes  i have a call. i will get back to it after it - i already recorded a video but only the postman application an not the console (it was split up). 
The weird thing is i could replicate it a few time than it worked like it should. 
On the domain allow list for eg `google `should it be `google.com` or just `google `and for `localhost `is just `localhost `fine? I have a feeling about it, that it is related to how the permissions are set because it is seems very random. on on `licalhost` it fails every time

**Comment by alex-frx** [comment]
Here it is demonstrated

https://user-images.githubusercontent.com/62759010/177823647-bd9c442b-c2f7-4609-a4d2-769bb852be4c.mp4

@DannyDainton

**Comment by codenirvana** [comment]
@alex-frx Thanks for the screen recording, I am able to reproduce this issue.

Found the bug in our script execution flow but as a temporary workaround, add a dummy `setTimeout` at the top of your script to unblock your use case.

![Screenshot 2022-07-08 at 10 28 00 AM](https://user-images.githubusercontent.com/4865836/177920162-34e5b726-215a-43a7-bf20-9ee592364c29.png)

We'll raise an internal issue to fix behaviour and update the thread once we have more information.

**Comment by apoorvgupta03** [comment]
Hey @alex-frx , can you please confirm if it is working fine at your end, even if you remove the dummy setTimeout we suggested? You can also update the app for latest changes.

**Comment by apoorvgupta03** [comment]
Hey @alex-frx , as it is currently working fine on our end, we're closing the ticket as we couldn't reproduce the reported issue at this time.  We sincerely encourage you to reopen the ticket if you encounter the problem again or if you have any further details that could assist us in resolving it.
