### ISSUE TITLE
Postman crashes with gRPC streaming response

### ISSUE THREAD

**Issue by 5olitude** [a85/POSTMan-Chrome-Extension#11061]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Im giving a live  data as a response with a time delay of one seconds using GRPC SERVER but after few minutes the postman crashes without responding (data around 100 kb in each seconds)

### Steps To Reproduce

*Open a request tab

*send a request to a grpc streaming server (response time delay of 1 sec)

### Operating System

Linux 

### Postman Version

9.14.0

### Postman Platform

Postman App

**Comment by codenirvana** [comment]
@5olitude Can you update the Postman app to the latest version and check if the issue persists?

If yes, please share the steps we can use to reproduce this issue locally.

**Comment by 5olitude** [comment]
@codenirvana 
hey  my postman version is  v9.23.3 and its a stable version i guess .

Steps to reproduce the issue 
*Create a live streaming GRPC server which will continuously broadcasting around 100 to 140 kb of data at every interval of one second or MilliSecond
* Even if I'm sending a small data at every 1 seconds or Milli seconds the same problem occurs after creating a duplicate tab

**Comment by 5olitude** [comment]
@codenirvana  Any updates?

**Comment by codenirvana** [comment]
@5olitude I created a streaming server as per the details shared by you but,
what do you mean by _"after creating a duplicate tab"_?

Can you share a screen recording to understand the flow?

For example, the following is working fine for me:

![gRPC-streaming](https://user-images.githubusercontent.com/4865836/178016953-ab5d27ee-8d8f-4bd5-86e3-a6b2fdf6a29f.gif)

**Comment by DannyDainton** [comment]
@5olitude As we have had no response in the last 10 days, I will close this out.

If you can provide a screen recording, similar to the one @codenirvana created, showing the issue from your side it will help us investigate the problem.

**Comment by jksjaz** [comment]
This is still an issue with the latest version of postman. As soon as I start sending messages over the stream, postman crashes 100% of the time.

This happens with a single stream open as well but you can almost see it crash immediately if you have 2 or more streams open simultaneously.

I'm on an M1 Max with gRPC server on rust (which should not make any difference imo) and service definition connected over reflections.
