### ISSUE TITLE
After desiring for http2 in Postman long after, I hug the somnia. Bye~

### ISSUE THREAD

**Issue by blackist** [a85/POSTMan-Chrome-Extension#11066]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

desiring for http2

### Describe the solution you'd like

go to [somnia](https://insomnia.rest/download)

**Comment by DannyDainton** [comment]
Closing this as this doesn't need to be in the issue tracker.

I completely understand the frustration here but opening this isn't the solution to this problem. 😢

**Comment by blackist** [comment]
> Closing this as this doesn't need to be in the issue tracker.
> 
> I completely understand the frustration here but opening this isn't the solution to this problem. 😢

OK. I am so sorry.
