### ISSUE TITLE
New Integration Request - Hashi Vault

### ISSUE THREAD

**Issue by tbeech-dsg** [a85/POSTMan-Chrome-Extension#11078]
### Describe your current workflow

We use postman for testing APIs, however, when it comes to secrets for service accounts used to access certain APIs we largely have to rely on sharing environments where the recipient of the export has to go fetch the secrets and edit the environment to add back in the various secrets that are required.

### Describe your ideal workflow

Ideally, Postman would integrate with Hashi Vault and provide syntax to reference secrets in environments. This way we can freely share env exports without having to worry if we are sharing secrets insecurely.

### Describe alternatives you've considered

None

**Comment by shashankawasthi88** [comment]
@tbeech-dsg Thanks for raising the request. We shall look into the integration and update the thread as and when we have anything to share.

**Comment by Suhas-Gaikwad** [comment]
Thank you for your patience. We have released a feature for seamless integration with HashiCorp Vault in the release of [Postman v11](https://blog.postman.com/announcing-postman-v11/).

[Check the learning center](https://learning.postman.com/docs/sending-requests/postman-vault/hashicorp-vault/) to learn more about the feature.
