### ISSUE TITLE
Console Open in Editor Button in Dark Theme

### ISSUE THREAD

**Issue by themikeanello** [a85/POSTMan-Chrome-Extension#11074]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

The Open in Editor button in the Console window is difficult to see in the dark theme.

### Steps To Reproduce

1. Issue a request.
2. Select the Console.
3. Expand the Results
4. Review the Open in Editor buttons next to the Request Body (if a request body was provided) and the Response Body (if a response body was received).

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/33702596/178280408-7d02a56d-a24d-40b0-8216-c9f9e76dcc15.png)

### Operating System

Windows 10

### Postman Version

9.24.1

### Postman Platform

Postman App

### Additional Context?

The Open in Editor option is difficult to see on my laptop screen, and much more so on an external monitor.

**Comment by giridharvc7** [comment]
Thank you for reporting. 
This is now fixed in the latest version of Postman 
<img width="146" alt="image" src="https://user-images.githubusercontent.com/1040583/215346222-50ad133d-55d6-4ac2-97b6-854c8cb64905.png">
