### ISSUE TITLE
After executing `pm.collectionVariables.set('key',value)`,I can't get value through `{{key}}` in Headers.

### ISSUE THREAD

**Issue by SlowerDawn** [a85/POSTMan-Chrome-Extension#11070]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

As stated in the title.

### Steps To Reproduce

1.Open a new request tab;
2.use `pm.collectionVariables.set('key',value)` in the Pre-request Script;
3.use `{{key}}` in Headers to get value but receive nothing;

### Operating System

macOS

### Postman Version

9.22.2

### Postman Platform

Postman App

**Comment by DannyDainton** [comment]
Hey @Gittkm

Can you provide some screenshots of the issue, please?

Is the request that you're opening part of a saved Collection? 

Have you tried used a different scope for the variable like `pm.globals.set()`?

**Comment by DannyDainton** [comment]
Hey @Gittkm 

I'm going to close this issue for now, if you are still experiencing the issue we can look at reopening it again, once we received more information.
