### ISSUE TITLE
"unable to delete folder" message when deleting folders in a collection

### ISSUE THREAD

**Issue by bryan-diaz-kushki** [a85/POSTMan-Chrome-Extension#11077]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Postman is not allowing folders to be deleted, the legend "unable to delete folder" appears after a few seconds of having deleted any folder.

* This happens in both web and desktop apps
* This happens across multiple collections and workspaces (public and privates)
* All the members of the team have the same issue.

### Steps To Reproduce

1. Create a folder in a collection
2. Try to delete that folder (a "myfolder Folder was deleted successfully." message will be appear)
3. Wait a few seconds and a second message ("Unable to delete folder") will be appear and the folder will be restore

### Operating System

macos

### Postman Version

9.21.5

### Postman Platform

Both

**Comment by shubhbhargav** [comment]
Hey @bryan-diaz-kushki, can you share some more info with us regarding the collection?

- Is this a new collection or an existing collection?
- What's the approximate size of the folder which is expected to be deleted? (say 1000 requests in the folder)

In addition, if you could share a screen recording of the issue, it would be really helpful to debug further.

**Comment by bryan-diaz-kushki** [comment]
Is an existing collection (public)

There are about 17 subfolders and 71 request

**Comment by shubhbhargav** [comment]
Got it. Can you please share the link of the collection (assuming it is publicly accessible)? Also do let me know the folder that you are trying to delete.

In-case you would like to share this info with us on a separate channel, please reach out to us at `help@postman.com`.

**Comment by vedkribhu** [comment]
@bryan-diaz-kushki can you try deleting this folder in bulk delete? Select some other folder along with this folder and try deleting both.

**Comment by DannyDainton** [comment]
Hey @bryan-diaz-kushki 

Is this still an issue you're facing in the latest version?

**Comment by DannyDainton** [comment]
Hey @bryan-diaz-kushki 

I'm going to close this issue, for now. If you're still facing this issue on the latest version we can look at reopening it again.

**Comment by onigor** [comment]
Had this issue for last 8 month, I had folder that was moved out to separate collection, and I wasn't able to delete it. 
I didn't tried to delete all requests in it and then folder (too many requests close to 100). This is with teams Workspaces, not local copy. 

**But, creating dummy folder and bulk deleting them worked for me**

**Comment by mustaphadem** [comment]
> Had this issue for last 8 month, I had folder that was moved out to separate collection, and I wasn't able to delete it. I didn't tried to delete all requests in it and then folder (too many requests close to 100). This is with teams Workspaces, not local copy.
> 
> **But, creating dummy folder and bulk deleting them worked for me**

thank you for this, I was going insane :)

**Comment by vgashic** [comment]
I had this issue too. Deleting all requests did not help, but Help/Clear cache and reload did.
