### ISSUE TITLE
Runner percentage is not accurate

### ISSUE THREAD

**Issue by ManasaBS22** [a85/POSTMan-Chrome-Extension#11076]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

When I select the 'Runner' option and select some payload to run 100 iterations while executing percentage will be increased according to the number of iterations say when the 10th payload hits it shows 10% like-wise.

But after some percentage, it won't get increased accurately, say 60 runs done it should show 60% but it shows 30-40%.

### Steps To Reproduce

1. Open postman
2. Select Runner
3. Select any payload from the collection
4. Give number of iterations
5. Click on "Run"

### Screenshots or Videos

<img width="1274" alt="Screenshot 2022-07-11 at 8 55 10 PM" src="https://user-images.githubusercontent.com/109093417/178301197-bb6b1030-50b3-4c96-aaee-109cc5015ee7.png">

### Operating System

macOS

### Postman Version

v8

### Postman Platform

Postman App

**Comment by DannyDainton** [comment]
Hey @ManasaBS22 

Thank you for writing in. 

Unfortunately, we're only supporting critical updates to the older versions of the platform.

This particular feature has been removed from the runner, following a UI redesign on V9.

<img width="1302" alt="image" src="https://user-images.githubusercontent.com/17089546/178315378-6c89e8fa-abe3-4a70-ad16-76281dffccbe.png">
 
Download the most up-to-date version here, to enjoy the latest features - https://www.postman.com/downloads/
