### ISSUE TITLE
Collection variables are not being rewriten with new values

### ISSUE THREAD

**Issue by fjuza1** [a85/POSTMan-Chrome-Extension#11089]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

ID for request: 11;
![image](https://user-images.githubusercontent.com/104192489/179476610-c8a41dd1-74df-4580-8bea-26b0e81752dc.png)

VAriable in collection with name should have been rewritten, but is not. JSON path was written in a folder
pm.collectionVariables.set("jazyK_KATEGORIE_ID", x.jazyk_Kategorie[0].jazyK_KATEGORIE_ID);

![image](https://user-images.githubusercontent.com/104192489/179477371-936ac934-cdad-42be-b466-f488ceae365b.png)

Value should have been 11, not 2

Folder has written multiple paths for diffrent requests in a folder

### Steps To Reproduce

Oppenned request
Rewrote value
Value of collection variable was not re-written

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/104192489/179476610-c8a41dd1-74df-4580-8bea-26b0e81752dc.png)
![image](https://user-images.githubusercontent.com/104192489/179477371-936ac934-cdad-42be-b466-f488ceae365b.png)

### Operating System

WIndows 11

### Postman Version

9.24.0

### Postman Platform

Postman App

**Comment by DannyDainton** [comment]
Hey @fjuza1

It's difficult to follow the steps you have to create this issue. 

Where is this set and is there more to the script than just this line?

```
pm.collectionVariables.set("jazyK_KATEGORIE_ID", x.jazyk_Kategorie[0].jazyK_KATEGORIE_ID);
```

If the value comes from the response to a request, how are you collecting that information within a Folder pre-request?

**Comment by fjuza1** [comment]
There are multiple lines of test scripts for diffrent requests within one folder(folder is the location), which has subfolders.
![image](https://user-images.githubusercontent.com/104192489/179678493-0ca6c459-e972-4a64-9147-b605bcc912d3.png)

**Comment by DannyDainton** [comment]
Have you tried isolating the failing line of code?

Does it set the correct value when applied to the test section of that specific request? 

Is it correctly setting all of those values? 

You're not logging the error of the try/catch block anywhere, have you tried logging that to the console to see if anything is happening?

**Comment by fjuza1** [comment]
I get this error
![image](https://user-images.githubusercontent.com/104192489/179697808-00120432-c1c3-45b4-8eb4-d39d62b5dc7c.png)
It is never transakciA_ID(transaction id)
So I cannot have multiple json paths of diffrent requests, why?

I applied dry principle, so I would not have diffrent json paths in diffrent folders or diffrent requests.

AND json paths are correct.After deleting json path of a folder and by puttin it in a request I dont get and error, why so?

Even after redeclaring const x = pm.response.json(), I get 
![image](https://user-images.githubusercontent.com/104192489/179701144-0976b9dc-fd73-4359-a899-5abc2badcd0c.png)

**Comment by DannyDainton** [comment]
The value is `undefined` when the script is run. This would work for each request `const x = pm.response.json()` as they all have a JSON response body but each response looks like it has a different structure.

You have this set at the Collection level in the Tests section, which means it runs after _every_ request in the collection. You have a block of different references relating to different requests in the Collection. 

Every reference in that try/catch block is not part of every response body so it's looking to set something that doesn't exist at the point that it's run.

You would need to either add logic to check that the reference exists before trying to set it or split the block up and apply that at the folder level of those specific groups of requests.

**Comment by fjuza1** [comment]
You would need to either add logic to check that the reference exists before trying to set it or split the block up and apply that at the folder level of those specific groups of requests.

But how?

**Comment by DannyDainton** [comment]
I don't believe that this is an issue with the Postman product so there's not a lot we can do on that side. This is more of a JS code/logic issue or workflow issue, which would be an excellent question to add to our user forum.

https://community.postman.com

Could you raise this on the Postman Community site, please? 

I'm going to close this for now.

**Comment by fjuza1** [comment]
Ok, I will
