### ISSUE TITLE
Scroll down - Stats view 

### ISSUE THREAD

**Issue by MahaSamir** [a85/POSTMan-Chrome-Extension#1108]
On Using Collection runner , View stats .. There's no scroll down option to see the rest of test results , only one page of the first few requests can be displayed ..

**Comment by abhijitkane** [comment]
@MahaSamir Can you confirm this fixed in v3.0.4?

**Comment by numaanashraf** [comment]
@MahaSamir We've rolled out a new design for the collection runner in Postman 4.0. This issue has been addressed in the new design.
