### ISSUE TITLE
Could not login to google account via postman to preview google auth

### ISSUE THREAD

**Issue by agn-7** [a85/POSTMan-Chrome-Extension#11087]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

I have the same issue which is raised in this StackOverflow [post](https://stackoverflow.com/questions/68346231/could-not-login-to-google-account-via-postman-to-preview-firebase-success-respon):

> I am hitting firebase DB by giving all required details (parameters, access token) and I got 200 OK responses. The problem is when I click the next button in the postman to view the response code, It's not responding. Is there any other way to view in postman instead of logging in to the google account?

In fact, I can't use Postman to call an endpoint on behalf of google oauth2 as it needs to pass the google account and submit it which Postman doesn't support the  JS in preview.

### Steps To Reproduce

See error message

### Screenshots or Videos

![image](https://i.stack.imgur.com/064gA.png)

### Operating System

Linux — Ubuntu 22.04

### Postman Version

9.20.0

### Postman Platform

Postman App

**Comment by DannyDainton** [comment]
Hey @agn-7 

Not really sure what you're trying to do here? 

The image shows the rendered result of that specific request, in the `Preview` tab. If you were to view this in the `Pretty` or `raw` tabs, it would show the HTML for that page. 

This is a static visual representation of the response and not something that is going to perform additional calls to log you into anything.

**Comment by agn-7** [comment]
Hi
thanks for the instant response. So in this way, can't I use Postman to test this kind of scenario — calling an endpoint on behalf of google oauth2?

For example, in the browser, I can call the API, and then it redirects to the google auth page which is represented in the Preview section of Postman, and then I put the google account and then catch the data I want which is not possible in Postman.

**Comment by DannyDainton** [comment]
Unfortunately, it's not possible to do this due to JS being disabled in the response Preview tab.

There is an open feature request (#2646) for this to be enabled. I'm going to close this issue and ask that you add your use case to the thread so that we keep all the details centralised.

**Comment by agn-7** [comment]
Thank you for the clarification. I also added the use case in the context.

**Comment by codewithdestiny** [comment]
@>agn-7 

Google Oauth-2 Testing can be done using postman as describe
[https://stackoverflow.com/questions/74619052/how-can-i-test-my-backend-api-against-google-oauth2](here)
