### ISSUE TITLE
Latest reported download version of the app is out of sync with the actual version

### ISSUE THREAD

**Issue by lorand-horvath** [a85/POSTMan-Chrome-Extension#11088]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

The Postman app downloads page `https://www.postman.com/downloads/` serves file names with the version different from the actual version of the downloaded app.
For example, if I download the latest app now, I will get a file named `Postman-win64-9.24.2-Setup.exe` but the actual app is version 9.22.2. This has been happening for a few months, I'm not sure if the devs have noticed the discrepancy, so I hope this will shed light and perhaps a fix can be carried out. Thanks!

### Steps To Reproduce

1. Download app
2. Check version by right-click - Properties  - version
3. Version in file name different from actual version of app

### Operating System

Windows 7 x64

### Postman Version

9.22.2

### Postman Platform

Postman App

**Comment by DannyDainton** [comment]
Hey @lorand-horvath 

Could you also provide a screenshot of the `About` section in the app's settings model, please?

**Comment by lorand-horvath** [comment]
@DannyDainton I'm not sure whether that has much to do or would help with the issue I reported, so I will try to reformulate the problem.
So if I go to `https://www.postman.com/downloads/` and click to download the Windows 64-bit App, the browser will download from `https://dl.pstmn.io/download/latest/win64` the file named `Postman-win64-9.24.2-Setup.exe`, which is supposed to be version 9.24.2.
But when I right click in Windows Explorer and choose Properties on the file, the actual/real version specified on the Details tab is 9.22.2, please see screenshot:
![image](https://user-images.githubusercontent.com/72015221/179491838-6ed44b88-950d-4725-b317-7c6936cb5e2a.png)
I confirm that if I run the installation, version 9.22.2 gets installed indeed, and not 9.24.2 as one would expect from the file name (the app then auto-updates to 9.25.0 which has just been released today, but that's another matter).

I have seen this discrepancy several times before with previous versions as well, the file name version and the actual included app version have been out-of-sync since at least January 2022.

**Comment by DannyDainton** [comment]
I asked for the screenshot of that app's `About` screen, due to us having different versions of the app platform and the UI within that version. It was more to provide more context and information to your reported issue.

This issue is the same/similar to the one reported for the MacOS version - https://github.com/postmanlabs/postman-app-support/issues/11068

**Comment by lorand-horvath** [comment]
Alright, but I still don't understand what the app's version reported on the About page has to do with the issue at hand.

The downloaded file is just badly named. Instead of having the real/actual version present in its name, i.e. 9.22.2, it is incorrectly named 9.24.2, that's all there is to it. And yes, the MacOS version problem is basically the same as I reported here for Windows.

Anyway, here's the screenshot from inside the app's About tab, but please keep in mind that it automatically updated today from 9.22.2 to 9.25.0.
![image](https://user-images.githubusercontent.com/72015221/179517310-c4b79732-8358-4c15-914e-97cce2217cfb.png)

**Comment by lorand-horvath** [comment]
I see the same issue with the latest downloaded file, named `Postman-win64-9.25.1-Setup`, which in fact contains version 9.25.0 of the app.

**Comment by lorand-horvath** [comment]
Version removed from filename as of 2022-08-01. Not the best solution since the version can still be read from file properties. Anyway, closing this as /wontfix.
