### ISSUE TITLE
Unable to set collection variables

### ISSUE THREAD

**Issue by dimitargg92** [a85/POSTMan-Chrome-Extension#11082]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

When trying to set collection variable and then use it in other requests results in error(
undefined). This issue is not happening all the time. For example, I already had 10-15 collection variables set successfully, when this error occured. When I create collection variable manualy and then invoke it, there is no such problem. Is there any storage limit of collection variables limit?

### Steps To Reproduce

1.Set up around 10-15 collection variables with different size
2.Continue to set up collection variable and try to invoke them in other requests/pre-requests

### Operating System

Windows

### Postman Version

9.24.2

### Postman Platform

Postman App

**Comment by DannyDainton** [comment]
Hey @dimitargg92

There are no restrictions on the number of variables, at any scope, that you can have. 

Could you please provide some visual examples of the behaviour you're seeing? A short recording showing the full app window would help us to understand and see the problem better.

Any test scripts that you're using or how you're using the variables in other requests would help too.

**Comment by dimitargg92** [comment]
Hey, for example 
![image](https://user-images.githubusercontent.com/67151547/178746797-05b49d1d-36a1-49f6-945e-ad73bc143c54.png)
saving variable in pre-request script,
which later trying to invoke in another pre-request script
![image](https://user-images.githubusercontent.com/67151547/178747020-dc261fa8-2194-4080-b91a-70b502dd0485.png)

I get an - 'undefined', when I console log it and there is no such variable saved in the Collection variables section

**Comment by DannyDainton** [comment]
Unfortunately, those 2 lines of code in isolation don't really mean anything. We don't have the context of what `profiles` is referencing. 

Can you provide the full script that you have and the way that you're using this in the requests?

Providing a basic scaled-down Collection is probably going to be the easiest way for us to see that running locally.

**Comment by fjuza1** [comment]
AND
+ collection variables dont get overwriten with new values at times.

**Comment by DannyDainton** [comment]
@fjuza1 Is that a different issue? Is that related to this issue? 

As an isolated comment without context, not sure what we can do with that. 

---

@dimitargg92 Do you have the rest of the information that we require in order to debug your reported issue?

**Comment by fjuza1** [comment]
yes related. When old values of variables in collection are not updated with new values at times

**Comment by DannyDainton** [comment]
@fjuza1 Can you create a new issue please, follow the template and provide all the details of what you're seeing? 

As you're describing a UI-based issue, a screen recording or images will help us to see what you can see.

**Comment by DannyDainton** [comment]
Hey @dimitargg92 

Are you able to provide the additional details for this issue, if not, I'm going to have to close this out.

**Comment by fjuza1** [comment]
No additional detail, can it be closed now

**Comment by DannyDainton** [comment]
Thanks, @fjuza1 but this wasn't an issue you created initially, you posted about an unrelated problem.

@dimitargg92 I'm going to close this as I haven't received any response for the information needed to debug this issue.
