### ISSUE TITLE
New Request Button

### ISSUE THREAD

**Issue by edmundssteven** [a85/POSTMan-Chrome-Extension#1109]
Wherever the button or other UI element that creates a new request is, I don't think it is prominent enough. I haven't been able to find it, and have to duplicate a previously existing request in order to create a request. Maybe it's just me though. If someone could let me know where it is I'd appreciate it.

**Comment by abhijitkane** [comment]
What version of Postman are you using? You can click the 'Reset' button to clear the current request, and that effectively creates a new request.

**Comment by edmundssteven** [comment]
I'm using Version 2.1.6 (packaged). If I use the reset button then it removes all of the authorization headers, and furthermore removes the "Save" button from the interface. I guess since I want those authorization headers, duplicating pre-existing requests is the way I'll have to go.

**Comment by abhijitkane** [comment]
A new request will have no Authorization headers by default. The save button is only meant to update requests that are already in a collection. To save a new request, you can use the 'Add to Collection' button.

**Comment by a85** [comment]
We have the new tab button that initializes from a blank state. If you want to re-use any existing part of a request, you'll have to duplicate the request and make changes.
