### ISSUE TITLE
When we zoom out the postman app under view the header section of setting and notification icons are not responsive

### ISSUE THREAD

**Issue by sseenivasan89** [a85/POSTMan-Chrome-Extension#11097]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

in Postman app version **v9.25.0** 
when i set the **zoom out (ctrl+-)** the header section of setting and notification icons are not working when i click those buttons

### Steps To Reproduce

1. Open postman application
2. Goto view menu and select the **zoom out** options
3. Click on the **Setting** (gear icon on the header section)
4. Click on the **Notification** (bell icon on the header section)
5. Click on the **Invite button** on the header section
6. Click on the **Profile** icon on the header section 

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/44080743/179671076-0f8414ba-b3f5-4409-84fb-392d812740b8.png)

### Operating System

Windows

### Postman Version

9.25.0

### Postman Platform

Postman App

**Comment by VaishnaviChallaPostman** [comment]
@sseenivasan89 Closing this as this issue is being tracked here: https://github.com/postmanlabs/postman-app-support/issues/11104 
Please subscribe to that GH thread to avoid missing any updates.
Thanks!
