### ISSUE TITLE
Validating against schema of body

### ISSUE THREAD

**Issue by fjuza1** [a85/POSTMan-Chrome-Extension#11090]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

1. Name of my custom name  of a  request get re-written
2. Values of body get re-written, even though, nothing new was added.

### Describe the solution you'd like

1. If name of request in api schema do not match with my custom name, ignore name as an error.
Anytime i give custom name, I want when I update collection with one click, I would like my custom name to remain.
2. I would like in my body´s values to not get rewritten, but if something new was added into a body, compare only differences and add what is new(diffrent).To sort of work like a diff tool. 

### Describe alternatives you've considered

Postman could include their own diff tool

### Additional context

Values get re-written in a body
![image](https://user-images.githubusercontent.com/104192489/179480186-cf620077-b981-4156-9962-16939dfe6c13.png)
![image](https://user-images.githubusercontent.com/104192489/179480096-007e39dc-b251-4d31-9698-dc2abdf7eb75.png)
![image](https://user-images.githubusercontent.com/104192489/179480498-294b7dca-9de0-4f25-8314-7b82e881af97.png)

**Comment by VShingala** [comment]
@fjuza1 Thanks for reporting the issue!

Could you also provide us with the corresponding schema for the OpenAPI definition? You can simply provide the sample definition with which this issue is happening or specifically request body schema for the mentioned endpoint. It'll help us debug this better.

**Comment by shashankawasthi88** [comment]
@fjuza1 this should be fixed with the latest version of Postman. Can you please try out the flow and let us know if the problem still exist.

**Comment by fjuza1** [comment]
The thing is now, when collection was updated, the body was deleted
Previously: 
![image](https://user-images.githubusercontent.com/104192489/228156512-7721ff06-1378-41a4-96ee-bbf14ebce9c1.png))
After: 
![image](https://user-images.githubusercontent.com/104192489/228156203-dacd94fb-f2af-4259-b6f4-081260364499.png)
