### ISSUE TITLE
Authorization configured for collections not correctly inherited by requests within collections

### ISSUE THREAD

**Issue by demdante** [a85/POSTMan-Chrome-Extension#11099]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

I recently created a collection for the [Open Secrets API](https://www.opensecrets.org/open-data/api), and configured the api key which the api uses for authorization under the "authorization" tab of the collection, since I want all of the requests contained within that collection to inherit the authorization configured in the collection.  Below, you can see the how how I configured the authorization settings (with the key redacted of course):

![2022-07-19 00_45_17-Postman](https://user-images.githubusercontent.com/64720591/179666910-5166cf4e-926b-49b4-b373-fef82aec7812.png)

The request that I created is configured to inherit auth from parent.  When I run the request when it is configured to inherit its authorization configuration from its parent, this is the response that I get:

![2022-07-19 00_53_24-Postman](https://user-images.githubusercontent.com/64720591/179667788-936e7659-bd8d-4cb3-9a79-77befc350b85.png)

So, you might think that the issue is with the way that I configured the request, right?  Well, no.  Its not.  I know because if I take the exact same authorization information that I configured in the collection and configure the authorization for the individual request with the authorization configuration pulled from the collection, the query runs perfectly:

![2022-07-19 00_57_22-Postman](https://user-images.githubusercontent.com/64720591/179675638-10b9fdc7-6a6b-4195-b2ae-46eb51616d76.png)

Just to be clear here, the only difference between the two queries is that the authorization for the query moved from the collection level to the request level.  Its the same configuration settings, it is just assigned directly to the request rather than the request inheriting it from the collection.  This indicates to me that there is something that is not working in regards to the authorization inheritance, but I am unsure as to the degree of the issue.   For example, does it apply when the authorization type is configured as "API Key", or does it apply to all inheritance regardless of the type?  And if the answer to the previous question is that it is only applicable to API Key authorization types, does it apply only when the authorization is configured to append the key/value pair as a parameter at the end of the api request, or does it also occur when the key/value pair is configured in the header of the request?  I do not know the answer to these questions, but I can tell you that, as far as the authorization inheritance is broken for the specific configuration that is displayed in the very first picture.  I can also say that I used fiddler to capture both postman requests: the request that was sent when the request inherited its authorization from the collection (collection_auth.txt) and the request that was sent when the authorization is configured directly within the request and does **not** inherit from the collection (request_auth.txt).  I have, of course, redacted all instances of the api key from the txt files, and will attach them to this issue.

### Steps To Reproduce

1. Create a collection and configure the authorization settings in the collection as an API Key type and configure the authorization to add the key/value pair to the end of the query as a parameter (See first picture in "Describe the issue section")
2. Create a new request within the collection whose authorization settings you just configured and configure the authorization settings for the request to inherit auth from parent.
3. Configure the request so that it sends a valid request.  I would recommend using the [Open Secrets API](https://www.opensecrets.org/open-data/api), as you can create an account and obtain an api key for free and you can recreate the exact requests that I ran which resulted in the problem by simply reviewing the pictures I posted under the "Describe the issue" section
4. Send the request

### Screenshots or Videos

See "Describe the issue" section.  All the pictures you could possibly need are in that section.

### Operating System

Windows

### Postman Version

9.25.1

### Postman Platform

Postman App

### Additional Context?

I have zipped the logs for both requests as described in the "Describe the issue" section in the attached archive.  I will also post each individual log as a gist, so use whichever is most convenient.
### request_auth.txt
[link 1](https://gist.githubusercontent.com/demdante/c26d3682bfa9a54125887f60fbd3096b/raw/ea8c5ba7ac7d1fed9cc7bd12efdfceda8a361fda/request_auth.txt)
[link 2](https://gist.github.com/demdante/c26d3682bfa9a54125887f60fbd3096b)

### collection_auth.txt
[link 1](https://gist.githubusercontent.com/demdante/320a15ba029a843924e8b28eb0742b20/raw/d99fb07e5198ad06ab12bf30a61f4df2804a9198/collection_auth.txt)
[link 2](https://gist.github.com/demdante/320a15ba029a843924e8b28eb0742b20)

[requestinfo.zip](https://github.com/postmanlabs/postman-app-support/files/9137959/requestinfo.zip)

**Comment by abhijeetborole** [comment]
Hey @demdante , thanks for reporting this issue. We were not able to reproduce the issue by following the steps you provided. 

However, it looks like the collection changes are not saved in the screenshots. If these unsaved changes contain the auth configuration, these will not be picked up by the request unless you save the collection tab. Could you verify if these changes are saved and try sending the request again?

If this doesn't help, could you share the collection with us at `help@postman.com` to help us debug further? Do mention this issue in the mail.

**Comment by demdante** [comment]
> Hey @demdante , thanks for reporting this issue. We were not able to reproduce the issue by following the steps you provided.
> 
> However, it looks like the collection changes are not saved in the screenshots. If these unsaved changes contain the auth configuration, these will not be picked up by the request unless you save the collection tab. Could you verify if these changes are saved and try sending the request again?
> 
> If this doesn't help, could you share the collection with us at `help@postman.com` to help us debug further? Do mention this issue in the mail.

You are right.  I didn't save the request, and that was the problem.  Closing this issue.
