### ISSUE TITLE
"Save All" button for open tabs

### ISSUE THREAD

**Issue by twb2077** [a85/POSTMan-Chrome-Extension#11096]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

No

### Describe the solution you'd like

Please provide a "Save All" button for open tabs in the dropdown shown in the screenshot
![2022-07-18_10-39-06](https://user-images.githubusercontent.com/47541759/179617970-d9432d99-7cf2-4002-bc33-04b7f9d00826.png)
.

**Comment by DannyDainton** [comment]
Duplicate of https://github.com/postmanlabs/postman-app-support/issues/10935
