### ISSUE TITLE
pm-icon on the header section is not visible clearly in postman web

### ISSUE THREAD

**Issue by sseenivasan89** [a85/POSTMan-Chrome-Extension#11098]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

**pm-icon** on the invite button on the header section is not visible clearly in postman web

### Steps To Reproduce

1. Launch postman web
2. Check the **pm-icon** on the **invite** button
3. Check the pm-icon is clearly visible

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/44080743/179673509-e2ac5ee5-8381-4fe9-88a4-a6d26c1efbc4.png)

### Operating System

Windows

### Postman Version

9.25.1

### Postman Platform

Postman Web

**Comment by DannyDainton** [comment]
Hey @sseenivasan89 

I'm unable to see this happening on my account 
<img width="1334" alt="image" src="https://user-images.githubusercontent.com/17089546/179717179-4e9a2004-a402-41c6-b39d-c8772ffb4a84.png">

However, I am using a mac. 🤔 Are you using a specific browser or is the screen a certain size? Is there a specific type of Workspace that you're in?

**Comment by sseenivasan89** [comment]
Hi @DannyDainton,

please find the details here (the pm-icon (human icon) on my screen is not in white color like what i see on your screen)

![image](https://user-images.githubusercontent.com/44080743/179726685-b00cc6d1-474e-4d1c-8f4c-b26916ffad47.png)

**Comment by DannyDainton** [comment]
I ask @arlemi to check this on his Windows machine, he's not seeing the same thing.

![image](https://user-images.githubusercontent.com/17089546/179730533-412f3f67-514e-4b2e-b731-fb6f2430301a.png)

Can you do a hard reset or clear the cache, to see if that helps here. Not really what else to suggest 🤔

**Comment by sseenivasan89** [comment]
@DannyDainton - i cleared cache and reset the browser setting and tried and i could see the same in thing in chrome but its look normal in other browsers i tried

**Comment by DannyDainton** [comment]
Not really sure what we can do here - @arlemi was using the same browser version on the same OS and he's able to see the correctly displayed icon. 🤔

**Comment by sseenivasan89** [comment]
@DannyDainton - we can ignore and close this
