### ISSUE TITLE
9.25.1 Update Has Difficult to Access Toolbar Buttons

### ISSUE THREAD

**Issue by acgritt** [a85/POSTMan-Chrome-Extension#11104]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

With the menu bar not displayed in the 9.25.1 update the toolbar buttons to the right of the Notification icon are very difficult to access. This makes it hard to access the Account, Minimize, Maximize and Close buttons. The buttons are only clickable when you mouse over the very bottom of the button.
![image](https://user-images.githubusercontent.com/10471937/180027680-475fe2e5-deb2-434f-8494-253d2ddc76ae.png)

### Steps To Reproduce

1. Update to latest 9.25.1
2. Try to click Minimize, Maximize or Close from the Center of the icon.

### Operating System

Widnows 10

### Postman Version

9.25.1

### Postman Platform

Postman App

**Comment by wyssaj** [comment]
I'm seeing the same behavior on Windows 11.

**Comment by diptarag** [comment]
@acgritt @wyssaj 

Do you see any error on console? Also, what's the behavior when you hover over the buttons?

Is it possible to share a screen recording?

**Comment by ivan-gospodinov** [comment]
I am seeing the same - Win10, Postman v9.25.1 
No errors in the console. You can click on the minimize/maximize/close buttons only if you move the mouse pointer to their edges.
Attached images - when the mouse pointer is centered on the button - the button is not clickable; and when the mouse pointer is on the edge and the button is shown in red color and can be clicked

![postman_close_button_not_accessible](https://user-images.githubusercontent.com/44980817/180424851-98a13890-7e56-4af3-847b-d3537c498feb.jpg)
![postman_close_button_access](https://user-images.githubusercontent.com/44980817/180424861-b8567ea9-e08c-4ca9-9d1a-18d7b496abea.jpg)

**Comment by diptarag** [comment]
@ivan-gospodinov 
Hey

Thanks for providing the detail.

A few questions -

1. Is this happening consistently or only after certain action? 
2. What about team dropdown, account dropdown or any other options on header? They are consistently clickable?
3. Can you try to resize you window and check if the behavior is still same?
4. Also, can you check if you can access the application menu? If you can access, then can you check the console of shell as well?
![ShellDevTools](https://user-images.githubusercontent.com/2277198/180437254-f47a4baa-a38f-45fa-a7eb-0ad3a6883d73.png)

**Comment by acgritt** [comment]
@diptarag 
1. It is happening consistently, even after minimizing/maximizing the window.
2. The Account Dropdown, Team Dropdown, minimize, maximize and close all have the issue. Everything to the left of that is fine. However, I have noticed that it is difficult to drag the window around. You can click and drag just to the right of the Explore option but if you click in any of the blank space around the search box (which there is alot of) it won't drag the window as one would expect unless you click in the little space that would run above the toolbar options (Home, Workspaces, etc).
3. Still the same after resizing the window.
4. Looked at the console shell and no errors were displayed there for either the dragging or clicking the options.

**Comment by diptarag** [comment]
@acgritt 
We are trying to reproduce the issue at our end. 

Can you please -

1. Check if the app is draggable if you click and drag on the close button or team dropdown?
2. Share your exact OS version? The screenshot of About section of settings modal would be very helpful.

Also are you available for a quick call? I could run some tests and try to get to the root of the problem

**Comment by acgritt** [comment]
@diptarag 
1. Interestingly enough I can click on the min/max/close button and drag the window. All of the ones that have the issue being clicked I am able to use to drag the window.
2. 
![image](https://user-images.githubusercontent.com/10471937/180500349-59d4c488-c10a-49d9-9200-74abc127d27e.png)

I should be available later today for a quick call. About 3 PM Central Time (US)

**Comment by diptarag** [comment]
@acgritt 

Thank you for providing the detail. Sorry I missed the time slot, let me know when you are available next. I will share an invite.

**Comment by dani-fadli** [comment]
In my case, I can't even use the search bar, view settings and notifications, and change accounts. Temporarily, I use the web version with Desktop Agent.

**Comment by diptarag** [comment]
@dani-fadli 
The Home, Workspace, API Network, Explore links work fine?

Would you be available for a quick call? We are trying hard to reproduce the issue at our end

**Comment by diptarag** [comment]
We are able to reproduce the issue for zoomed in app. We are working on a fix.
In the meantime, if you reset the zoom level then the header buttons should work fine.

![ResetZoom](https://user-images.githubusercontent.com/2277198/180708396-b6bbbea6-bf40-4dc9-b9be-9f56236f9982.png)

**Comment by AncuL001** [comment]
seems like this has been fixed on 9.25.2 for me, other than that the cursor doesn't turn into "link select" mode when hovered on the middle of the "manage accounts" icon (still clickable tho)

https://user-images.githubusercontent.com/16044057/180971824-13034872-1a98-4f0e-a61a-e8c7f3b2cec4.mp4

**Comment by kamalaknn** [comment]
Update: This issue has been fixed and is available in 9.25.2. Please let us know if you're still facing issues.

**Comment by acgritt** [comment]
Much better now. I didn't even realize I had it zoomed in. Hazards of running a 40" 4K monitor I guess. Thanks for the fix.

**Comment by dotnetshaheen** [comment]
I am facing this problem in postman v10.11.1

![1](https://user-images.githubusercontent.com/57038350/223023619-540ef717-579d-4974-897d-7e465f5db566.JPG)
