### ISSUE TITLE
New Integration Request - <product name>

### ISSUE THREAD

**Issue by kannanramesh-1977** [a85/POSTMan-Chrome-Extension#11106]
### Describe your current workflow

by sending post method.

"error": {
        "message": "Unknown path components: /messages `\n  -H 'Authorization: Bearer 

### Describe your ideal workflow

by sending ack to customer

**Comment by DannyDainton** [comment]
Hey @kannanramesh-1977 

I'm not sure what it is that you're reporting here, can you elaborate more, please?

**Comment by DannyDainton** [comment]
Closing this as it doesn't seem like a valid request and may have been opened by mistake.
