### ISSUE TITLE
Crash on connecting ws:// with Socket.IO selection

### ISSUE THREAD

**Issue by NguyenVanCong1902** [a85/POSTMan-Chrome-Extension#11109]
### Is there an existing issue for this?

- [x] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

My postman app 9.25.0 is crashed while trying to connect local websocket with 'Socket.IO' type on Window 10 Pro

### Steps To Reproduce

1. I created new WebSocket Request
2. I connect my localhost websocket with 'Raw' option => connected
3. I connect my localhost websocket with 'Socket.IO' option => connected, then Postman is Crashed (i tried many many times, but still crashes)

### Operating System

Window 10 Pro

### Postman Version

9.25.0

### Postman Platform

Postman App

**Comment by shamasis** [comment]
@NguyenVanCong1902 ... is it predictably reproducible? @codenirvana and I were having a conversation and could not reproduce it. Could you send us some crash logs or more info that will help isolate the conditions of failure?

@ishanSinghal3 @ronork take this forward please. :-)

**Comment by NguyenVanCong1902** [comment]
@shamasis I tried to reproduce this issue. But today i can't reproduce it anymore. idk why 😔. Now i could connect with Socket.IO normally. Thanks you all

**Comment by ishanSinghal3** [comment]
No problem @NguyenVanCong1902. Just let us know if you find something in future
