### ISSUE TITLE
Documenter issue with RTL responses

### ISSUE THREAD

**Issue by ghost** [a85/POSTMan-Chrome-Extension#11107]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Postman publish documentation does not render RTL text correctly in the browser, with an example JSON value in Arabic for example. Meanwhile, the text is rendered correctly in the application

### Steps To Reproduce

1. Create new collection
2. Create a request with example response that contains JSON values in RTL language (e.g., Arabic)
3. Publish the collection documentation and view in browser

### Screenshots or Videos

In Postman app ( the correct representation of the text )
![image](https://user-images.githubusercontent.com/108212248/180139266-47082793-1299-488a-8830-f4b8ae1e3252.png)

In browser published documentation ( Wrong representation of the text, it seems the text in reverse order )
![image](https://user-images.githubusercontent.com/108212248/180139235-92e92a23-0a06-4574-8bc3-65488f8be230.png)

### Operating System

Windows

### Postman Version

9.24.2

### Postman Platform

Postman App / Online documenter

### Additional Context?

Text in Arabic "تم استرجاع البيانات بنجاح"

**Comment by kamaraj-p** [comment]
Hi @a7md0-99 , the issue is not reproducible anymore. Can you please confirm?

![App](https://user-images.githubusercontent.com/95747804/220309162-ab96fb70-6bec-4443-a5f4-c01ef0038099.png)
![Published documentation](https://user-images.githubusercontent.com/95747804/220309169-718e539d-d5f3-4044-b901-1241826485b5.png)

**Comment by kamaraj-p** [comment]
Closing this issue as it is not reproducible anymore. Please feel free to re-open if this is still happening.
