### ISSUE TITLE
Trim the URL before making a call

### ISSUE THREAD

**Issue by mohsen1** [a85/POSTMan-Chrome-Extension#1110]
If I put a URL with leading or trailing spaces, trim it before making the request. 

For example: `http://www.google.com` should be trimmed to `http://www.google.com`

**Comment by abhijitkane** [comment]
What version of the app are you using? This feature is there in https://chrome.google.com/webstore/detail/postman-rest-client-packa/fhbjgbiflinjbdggehcddcbncdddomop?hl=en

**Comment by mohsen1** [comment]
Hmm.. I was using this https://chrome.google.com/webstore/detail/postman-rest-client/fdmmgilgnpjigdojojpjoooidkmcomcm?hl=en

The new one does not have the issue. The older one in store is confusing, maybe you want to take it down. I'm closing this issue since it's not an issue in this project.
