### ISSUE TITLE
Flow crashes Send

### ISSUE THREAD

**Issue by PedroCostaMudey** [a85/POSTMan-Chrome-Extension#11110]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

While a Flows flow is running if a connection between block it's severed the next time the flow runs it will allow unconnected blocks and will run but gets stuck on the first block. Also if you try Send a normal collection query it also Send but do nothing other then show the spinner. 

### Steps To Reproduce

1. create a flow with several blocks
2. run flow
3. while is running sever a connection to block making it isolated of all others (try terminal)
4. stop run and run again

### Operating System

macOS

### Postman Version

9.13.0

### Postman Platform

Postman App

**Comment by DannyDainton** [comment]
Hey @PedroCostaMudey 

It would be great to get a short recording of the behaviour that you're seeing, helps to visualise the problem.

**Comment by SterlingChin** [comment]
This issue has been fixed in the latest version of Flows (`v10.12.5`). Unless you stop a Flow while it's running, you cannot delete, move, or otherwise change the Flow being run.
