### ISSUE TITLE
Unable to upload csv file

### ISSUE THREAD

**Issue by GV8** [a85/POSTMan-Chrome-Extension#1111]
Hi,
I am trying to upload csv data using Rest API service. Service accepts data in text/csv format. When I POST the csv data with header pasting it to raw-Text data on POSTMAN app, it does work with no issues. However I am not able to do the same using file instead of copy-pasting data.
Can someone please help me on this? 
Thanks,
GV

**Comment by abhijitkane** [comment]
You'll need to look up the API documentation on this. Are you able to successfully send the file using cURL?

**Comment by GV8** [comment]
Hi Abhijit,

Thanks for your reply! I did go through the API guide. It's for Eloqua using it's Bulk API 2.0. It does support csv import. Using cURL all other operations are working fine except csv file import. That's the reason trying to see if it can be done through POSTMAN. As mentioned, POSTMAN imports the data when it is added directly as csv text in the call, but not sure how to make postman to read the data from file instead. I tried specifying file as @path/filename.csv. Error received with this approach is same with POSTMAN as well as cURL. Can you please confirm the way I'm sending data file to POSTMAN is correct?

Thanks,
GV8

**Comment by abhijitkane** [comment]
This is an API limitation - if it does not support file uploads, then there's nothing that Postman can do about it. We'll be able to help if you're able to upload the file using cURL, but not using Postman.
