### ISSUE TITLE
Documentation Examples Should Show Status Code

### ISSUE THREAD

**Issue by Spider-ant** [a85/POSTMan-Chrome-Extension#11122]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

When you go to view documentation for a collection it will show examples. You can provide a status code for your example but it does not appear when viewing the documentation.
I may want to have more than one example.
e.g.
One good example showing results with a status of "200 OK".
Another bad example showing results with a status of "400 Bad Request".

### Describe the solution you'd like

1. When I view the documentation for a collection I would like for it to show more than one (response) example.
2. The examples should show the status code given to that example.
3. Examples with a status code of "200 OK" should show the status code in green, indicating to the reader of the documentation that it is a success result.
4. Examples with a status code of "400 Bad Request" should show the status code in red, indicating to the reader of the documentation that it is a failed result.

**Comment by ankitjaggi** [comment]
@Spider-ant This has been fixed in the latest version of the App (Postman v10.13).
