### ISSUE TITLE
All options are not displayed when right-clicking on a gRPC request by TouchPad

### ISSUE THREAD

**Issue by nuuura** [a85/POSTMan-Chrome-Extension#11120]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

A different number of features are displayed depending on how the context menu is called

### Steps To Reproduce

1. Go to Collections Tab
2. Add collection with grpc request on mac
3. Right-click by touchpad on grpc request
4. Click on button "3 dot"
AR for 3 step: A drop-down menu of two items (Rename, Duplicate) opens and does not match the overall design of the application
ER: A drop-down menu looks like in 5 step and considers 3 possibilities: Rename, Duplicate, Delete

### Screenshots or Videos

https://user-images.githubusercontent.com/22709651/181236449-a0231456-d313-411d-aced-b787daa15afa.mov

### Operating System

macOS BigSur 11.6.4, Apple M11

### Postman Version

9.25.2

### Postman Platform

Postman App

**Comment by codenirvana** [comment]
This is fixed in the latest version of the Postman app.
