### ISSUE TITLE
Allow GET requests to include a request body

### ISSUE THREAD

**Issue by jimjh** [a85/POSTMan-Chrome-Extension#1112]
Some services, such as [elasticsearch](https://www.elastic.co/guide/en/elasticsearch/guide/current/_search_with_query_dsl.html), use request bodies in GET requests.

This is a request to allow GETs to include a request body, just like POSTs and PUTs.

**Comment by abhijitkane** [comment]
This is currently a Chrome limitation. You cannot include a request body for GET requests. Will re-open when we have a way of circumventing this.
