### ISSUE TITLE
Slack integration for monitor always posting to channel

### ISSUE THREAD

**Issue by HgIain** [a85/POSTMan-Chrome-Extension#11126]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

I have a slack integration for a monitor that I've configured to only run for first 3 failures/1st success, but it's always posting when they succeed

### Steps To Reproduce

Slack integration looks like this:
![image](https://user-images.githubusercontent.com/62030951/181738739-e6b10252-d89a-4431-8f0f-06b03137d1c5.png)
But output I see in Slack looks like this:
![image](https://user-images.githubusercontent.com/62030951/181738828-98576e0d-43c1-4cf7-8c77-15cacbab7313.png)

I've tried setting and unsetting the option for setting the notification frequency and I've tried removing and readding the integration to no effect. 

### Operating System

Windows 11

### Postman Version

9.26.3

### Postman Platform

Both

**Comment by shashankawasthi88** [comment]
@HgIain thanks for raising the issue. We are looking into it and shall update the thread on any progress.

**Comment by zinok** [comment]
Is there any estimated resolution time for this?

**Comment by Atishay4294** [comment]
Hi @HgIain and @zinok - This issue has been addressed.
Can you confirm if the slack integration for monitors is working as expected?

**Comment by shashankawasthi88** [comment]
Closing this for now. Please re-open if the issue still exists.

**Comment by okey** [comment]
Hi @shashankawasthi88, this issue appears resolved for the Slack integration, but the same problem continues to occur for the custom webhooks integration. Would you prefer a new issue or to reopen this one?

**Comment by shashankawasthi88** [comment]
@okey thanks for raising this. No need for new ticket, ill reopen this and track the progress here itself.

**Comment by Atishay4294** [comment]
@okey - This issue has been addressed on the custom webhook and Microsoft Power Automate integrations as well.
Can you confirm if it is working as expected?

**Comment by okey** [comment]
@Atishay4294 it now appears to be working as expected, thanks
