### ISSUE TITLE
Allow test suite collections to include only part of schema requests

### ISSUE THREAD

**Issue by miquecg** [a85/POSTMan-Chrome-Extension#11128]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

I'm using collections to organize tests according to API flows. So for instance, a collection runs several tests over a group of endpoints, describing one specific scenario or flow, and another collection runs totally different tests over the same endpoints for another scenario.

I can duplicate requests on different collections to achieve the desired organization, problem is that I must include every path in the schema on every collection to have a clean validation, although those request may not have been exercised at all.

### Describe the solution you'd like

I would allow test suite collections to have any number of requests from a schema and ideally remain valid in structure.

### Describe alternatives you've considered

It looks like [Postman Flows](https://learning.postman.com/labs/postman-flows/getting-started/the-interface/) could really allow flexibility mixing and matching requests for testing, but I think it doesn't work with Newman yet, which is a problem on CI environments.

**Comment by shashankawasthi88** [comment]
@miquecg with the latest release, we have updated the validation logic to account for this use case. Look at the [docs](https://learning.postman.com/docs/designing-and-developing-your-api/developing-an-api/adding-api-elements/#keeping-a-collection-in-sync-with-an-api) to know more about the feature/ improvements. Closing this ticket for now, feel free to reopen this if needed.
