### ISSUE TITLE
Always sending POST request as GET

### ISSUE THREAD

**Issue by mba8487143** [a85/POSTMan-Chrome-Extension#11131]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

I am facing issue in calling POST request with postman. My POST request is received on server side as GET. I also checked it with an online tool its working fine with that tool but on POST man with same environment causing error. 

### Steps To Reproduce

Open a new tab.
Call this API using POST method **https://www.myamall.com/api/public/login** and get token in user data.

**Testing Credentials:**
email: bilawaali512@gmail.com
password: BaliG@143

And using Bearer token Authentication you can call API  in new tab **http://www.myamall.com/api/public/user/address-save** 
**Method:** POST
**Body:** raw(json)
**Payload:** 
`{
    "first_name": "Bamidele",
    "last_name": "Loveson",
    "email": "xamaranoconcept@gmail.com",
    "mobile_no": "+92301234567",
    "address": "River Park Estate",
    "city": "Abuja",
    "state": "FCT",
    "country": "Nigeria",
    "zip_code": "  7"
}`
Then you will see error in response.

### Screenshots or Videos

[Video Demo](https://www.loom.com/share/3e4f96f963984e87a1ef72794bab2072l)
Here in the video you can see I am calling POST request using postman, there is error of method Not Allowed. But with same environment I am calling same request using an online tool and its working fine.  

### Operating System

Windows 11

### Postman Version

9.26.4

### Postman Platform

Both

**Comment by DannyDainton** [comment]
Hey @mba8487143 

Does the request send as POST if you enable the `Follow original HTTP Method` setting? 

![Screenshot_20220730_193406.jpg](https://user-images.githubusercontent.com/17089546/181937260-5b1dbe6d-b6ea-4217-86a0-c7c3bfcec25c.jpg)

**Comment by DannyDainton** [comment]
@mba8487143 Did this solve your issue?

From your video, it's difficult to see all the requests being made and know if a redirect is happening somewhere along the flow. If it does, that could account for the change in the HTTP method.

**Comment by DannyDainton** [comment]
Hey @mba8487143 

I'm going to close this issue, for now, if this solution didn't solve the problem we can look at reopening it again.

**Comment by WatanabeThiago** [comment]
My postman is updated, but dont have "Follow original HTTP method" option
![image](https://user-images.githubusercontent.com/50850299/182844541-3029df2c-ab3a-4424-9403-42a181ada938.png)


My version:
![image](https://user-images.githubusercontent.com/50850299/182844706-c5f9bc05-fd57-4ba9-8111-358e3bacc5f6.png)

**Comment by DannyDainton** [comment]
The option would be under the request settings and not the global settings:

<img width="2124" alt="image" src="https://user-images.githubusercontent.com/17089546/182869810-bbf8ea99-3380-42d2-bdbd-660d01bf625f.png">

**Comment by ChrisMiami** [comment]
I am working with an API that I wrote, which issues a 307/Redirect.  When I POST an invocation to this URL, the redirect is sent correctly (if I disable redirects, I see the URL).  When I have Follow Redirects set to ON as well as Follow original method ON as well as Follow Authorization Header ON, I get "Too many redirects" which indicates to me that the method is being changed from POST to GET (my 'invalid url' handler redirects to '/' which is not available on this server so 'too many redirects' is a common result).  

There's no real useful logging available inside Postman to confirm or contest this. The DevTools console doesn't show network traffic of requests issued by the user, and the Postman console just shows a red request and I cannot find any networking history to confirm the change in method or the Locations of the redirects.

**Comment by ChrisMiami** [comment]
By other means, I was able to determine that the Location header is expected to have a protocol in it, so "server.domain/path" becomes "https://server.domain/path" and then all is well, redirects are followed and method is reused.
