### ISSUE TITLE
Postman windows desktop app dev tool opens on cntrl+shift+i

### ISSUE THREAD

**Issue by vamon-7** [a85/POSTMan-Chrome-Extension#11133]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Postman windows desktop app dev tool opens on Ctrl+shift+i i think which should happen on production env.

### Steps To Reproduce

1. open postman
2. ctrl+shift+i

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/72333387/182105539-181d4570-71e2-4b9e-bbc9-d04750f920dc.png)

### Operating System

windows

### Postman Version

9.23.3

### Postman Platform

Postman App

**Comment by DannyDainton** [comment]
Hey @vamon-7 

I'm not sure what problem you're reporting here - could you elaborate more, please?

**Comment by DannyDainton** [comment]
Hey @vamon-7 

Closing this issue due to lack of information, we can look at reopening if more context is provided.
