### ISSUE TITLE
Saving a request does not save the form-data file

### ISSUE THREAD

**Issue by cristinakiss** [a85/POSTMan-Chrome-Extension#1113]
Version: 3.0.0.5

When I try to save a request having in body a form-data of file type, I chose the file but it is not saved. I would expect to have the path to the file saved and maybe displayed on the UI. This would permit me to navigate between requests and find the file I used for a specific POST.

**Comment by abhijitkane** [comment]
This is a currently a chrome limitation. Postman does not have access to the file path, not can it read from paths that have been saved.

**Comment by cristinakiss** [comment]
Do you think this can be fixed in the future?

**Comment by johnnavarra** [comment]
technically you could do this in collection runner as a data driven test, with each body (payload) as a separate line item in the csv.

**Comment by abhijitkane** [comment]
@cristinak Not really, not till Postman is a Chrome application.

**Comment by emcga** [comment]
Has this issue been fixed? I am writing many tests and would like to be able to save the file path.

**Comment by comster** [comment]
This appears to still be the case with v3

**Comment by Shyri** [comment]
It is still happening

**Comment by goneneren** [comment]
Still not saving.. :/

**Comment by sdnts** [comment]
This isn't possible in the Chrome App because this would be a security breach for any modern browsers, who do not provide the client with the entire path to an uploaded file.

On the native apps though, it is. Support for it is on the roadmap.

**Comment by a85** [comment]
@madebysid Can we keep this as under the "Feature" label?

**Comment by premctl** [comment]
@abhijitkane   @madebysid Can you provide us update on how soon can we have this support on the app?

**Comment by sdnts** [comment]
@premsompura While this isn't a part of our immediate roadmap, you can follow https://trello.com/b/4N7PnHAz/postman-roadmap-for-developers for updates :)

**Comment by premctl** [comment]
@madebysid Thanks but I have found a hack :)

**Comment by abhijitkane** [comment]
This is not part of our immediate roadmap. You can use Newman as a workaround: http://blog.getpostman.com/2014/11/15/using-newman-to-run-collections-with-file-post-requests/

**Comment by grandcamel** [comment]
@premsompura Would you be so kind as to share your hack/workaround for this issue?

**Comment by silvervesi** [comment]
Found a workaround. Export the collection, then open the exported json file in notepad and edit:

```
					"formdata": [
						{
							"key": "ucert",
							"type": "file",
							"src": ""
						},
```

src will be empty, add the full path with backslash characters escaped: C:\\Users\\silverv\\Desktop\\testcerts\\testcert.cer

Now, import the collection back to Postman, either as a copy or overwriting the previous one. Now, Postman will still not show this file in Request body, nor will it work when you run this particular request, but it will work when you run the whole collection. However, trying to view response headers or response body will randomly crash Postman. Weird, but this method still beats having to manually click through n+1 tests.
