### ISSUE TITLE
Client certificate with host with space in the beginning

### ISSUE THREAD

**Issue by onetuser** [a85/POSTMan-Chrome-Extension#11149]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Adding client certificate in the settings (for mtls requests) with host name with space in the beginning (' some.host') neither removes the space automatically nor visually detectable and the certificate does not work.
The space needs either be detectable or be removed automatically from host.

### Steps To Reproduce

1. send request to some mtls resource which requires client certificate without this certificate configured in settings. Server responses that no correct certificate is sent.
2. Add correct certificate in the settings with host name with space in the beginning. (' some.host') and send request again. Get the same response as in p.1:  no correct certificate was sent.  (Tested with p12 certificates with password)
3. Do the same as p.2 but with correct certificate with host without space ('some.host'). Now requests work.

### Operating System

Linux

### Postman Version

9.21.5

### Postman Platform

Postman App

**Comment by arlemi** [comment]
This was fixed in the last version of Postman (v10.12). Please update and let us know if you're still facing the issue!
