### ISSUE TITLE
Collection runner is not processing my request

### ISSUE THREAD

**Issue by johnnavarra** [a85/POSTMan-Chrome-Extension#1114]
My collection runner seems to be just stalled now. Nothing seems to be happening and it is stuck at "sending request message"

this is my endpoint:
/Information/Vehicles/Attributes/BaseVehicleID/{{BaseVID}}/BaseVehicle/Attributes

My prerequest script:
data.Model_Year = parseFloat(data.Model_Year);
data.Iteration = parseFloat(data.Iteration);
data.BaseVID = parseFloat(data.BaseVID);
var publicK = environment.publicKey;
var privateK = environment.privateKey;
var utcDate = Math.floor(new Date().getTime() / 1000);
var assemble = (publicK+privateK+utcDate);
var encryption = CryptoJS.SHA256(assemble).toString();
postman.setEnvironmentVariable("Signature", encryption);
var Authorization = ("MWS"+" "+"{{publicKey}}"+":"+encryption);

this is the only thing in the console.log
test_runner.js:16458 Sending request message 6ea1979f-bec1-e6a4-26f2-27709cd7393b

network tab only shows the loading.gif as the processing factor.

performing the request in standard packaged postman is successful with no issue.

**Comment by abhijitkane** [comment]
What version of the app are you running? Is the interceptor enabled?

**Comment by johnnavarra** [comment]
I'm using
Version 3.0.0.5 (packaged)
OS: _win_
Architecture: _x86-32_
Native client architecture: _x86-64_

_Interceptor is enabled :_

_test_runner.js:266 Initialize interceptor_

On Fri, Jun 5, 2015 at 10:51 AM, Abhijit Kane notifications@github.com
wrote:

> What version of the app are you running? Is the interceptor enabled?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/a85/POSTMan-Chrome-Extension/issues/1114#issuecomment-109318011
> .

## 

AIM: obliviouslyaware
ICQ: 5147787
googletalk

**Comment by abhijitkane** [comment]
There's an issue with the collection runner when the interceptor is on - we'll be pushing a fix soon.

**Comment by abhijitkane** [comment]
Fixed in 3.0.2.
