### ISSUE TITLE
API Generate Collection does not support inheriting auth from parent collection

### ISSUE THREAD

**Issue by mtaylorfsmb** [a85/POSTMan-Chrome-Extension#11145]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

I am using Postman to define an API. Within the OpenAPI spec I am defining OAuth with scopes as the authentication. Each endpoint may require different scopes. After defining the API if you save and then generate a collection from it then ideally the individual requests should inherit their authentication from the collection but instead each request is set to require OAuth. 

That means that after generating a collection you have to then open each request and change it to inherit from the parent collection otherwise collection-level authentication doesn't work.

Maybe I'm missing something here but I want to define the OpenAPI spec such that each endpoint may have different scope needs but the generated collection should configure this at the collection level and then have all requests inherit from it. If a particular endpoint needs a custom scope then that could be a problem but at least for us we request all available scopes in the collection.

### Steps To Reproduce

Here's a stripped down YAML definition.

```
openapi: 3.0.0
info:
  title: test
  version: 2.0.0

security:
  - client_auth: []

paths:
 
  "/v1/products":
    post:
      responses:
        "200":
          description: Success
      security:
        - client_auth:
            - write

  "/v1/products/{id}":
    parameters:
      - $ref: "#/components/parameters/idParam"

    get:
      tags: ["Members"]
      responses:
        "200":
          description: Success
      security:
        - client_auth:
            - read

components:
  securitySchemes:
    client_auth:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: "/connect/token"          
          scopes:
            read: Read products.
            write: Update products.

  parameters:   
    idParam:
      name: id
      in: path
      required: true
      schema:
        type: integer
```

1. Add as an API
2. Save and then generate a collection. I use `Api Documentation` as the type but I don't know that it matters.
3. Open the generated collection. Notice the `Authorization` tab for the collection doesn't recognize any of the auth stuff as far as scope goes. You have to enter this by hand.
4. . Go to any of the generated requests and then go to their `Authorization` tab. Notice that the type has been set to `OAuth 2.0` instead of just inheriting from parent.

### Operating System

Windows 10

### Postman Version

9.26.0

### Postman Platform

Postman App

**Comment by rohendra** [comment]
Facing similar issue. One of the endpoints needs to unauthenticated but published api doc in postman shows same auth requirement for all endpoints.
Interestingly, when you define API schema and then view documentation for it, it shows auth info as per spec. But if you create collection (which is required for publishing created API doc), then auth requirement for at endpoint level is lost.

**Comment by Rajesh-KG** [comment]
Facing the same issue. The authorization for the collection should be inherited from the parent folder by default. Individual requests may override the authorization if they need.

**Comment by bekabaz** [comment]
Any updates here? This is completely breaking the ability for me to setup automated testing.

**Comment by VShingala** [comment]
@mtaylorfsmb @rohendra @Rajesh-KG @bekabaz You can choose an option while importing OpenAPI definition named `Always inherit authentication`. This will make sure that only collection info at global level is picked up rather then individual requests.

![Screenshot 2024-08-07 at 3 02 08 PM](https://github.com/user-attachments/assets/90879d2f-118f-49d6-9d2a-43a8bb560525)

![Screenshot 2024-08-07 at 3 02 40 PM](https://github.com/user-attachments/assets/057b0593-51c2-484c-933c-01cd5d19a3f8)

Please try it out and let us know your thoughts if it resolves issues you have.

**Comment by VShingala** [comment]
Hey folks, I'll be closing this issue since related use-case can be solved with steps I mentioned in above comment. Feel free to let us know here in case you face any further issues with the mentioned option and use-case.
