### ISSUE TITLE
console.log is full of undefined messages

### ISSUE THREAD

**Issue by johnnavarra** [a85/POSTMan-Chrome-Extension#1115]
Received interceptor response for msgId: 9ee1ff6a-e741-6a32-8d1b-20d166a0e1c7
requester.js:16504 Saving response in tab undefined

This is new in v3. This makes the console.log extremely full as I use it to display loaded csv data for export to be analysed.

**Comment by abhijitkane** [comment]
We've cleaned up a lot of console log messages in the latest version - 3.0.4.

**Comment by numaanashraf** [comment]
@johnnavarra Fixed in version 4.0+
