### ISSUE TITLE
wrong IP address can make the request succeed

### ISSUE THREAD

**Issue by allenzt** [a85/POSTMan-Chrome-Extension#11165]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Hi maintainers,

I use the wrong IP address wrong IP address(added a dot fellow the IP address) can make the request succeed, is is a bug or feature?
Request is as below:
```sh
https://192.168.10.1.:60000/v1/gnss/refresh
```

Thanks in advance!

### Steps To Reproduce

1. open the tab
2. use url `https://192.168.10.1.:60000/v1/gnss/refresh` https://192.168.10.1.:60000/v1/gnss/refresh

NOTE:
IP address is  **192.168.10.1.** (add a dot)

### Operating System

Windows

### Postman Version

9.27.0

### Postman Platform

Postman App

**Comment by DannyDainton** [comment]
Hey @allenzt 

Postman is just giving you the ability to be able to send a request, if the server accepts that input and responds, it's more on the implementation side of the API. Postman isn't really aware of any of that. 

I'm going to close this issue as I don't feel that there is anything we would be changing here. If this leads to other behaviour that could require a product change, please reach out again and we can look at investigating further.

**Comment by allenzt** [comment]
IP address is `192.168.2.1.`(IP address is followed by a dot) instead of `192.168.2.1`.  Why can an apparently wrong IP address successfully send a request? @DannyDainton
