### ISSUE TITLE
Backup does not save collections

### ISSUE THREAD

**Issue by Graham42** [a85/POSTMan-Chrome-Extension#1116]
version 3.0.0.3

Steps to reproduce:
1. Have multiple collections with multiple folders and calls.
2. Open settings
3. Go to the Data tab
4. Click Download under Export data and save the file
5. Open the saved file and see the empty collections array

**Comment by abhijitkane** [comment]
@Graham42 Is this still happening with v3.0.4?

**Comment by Graham42** [comment]
Appears to be fixed
