### ISSUE TITLE
Code Generated OAuth 1.0a incorrect signature with URL-encoded parameters

### ISSUE THREAD

**Issue by agreenberg18** [a85/POSTMan-Chrome-Extension#11167]
### Is there an existing issue for this?

- [x] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

OAuth 1.0 Signature generation produces an incorrect hash when the URL params contain URL-encoded parameters when creating code snippets. The request will work in postman, but result in an auth error when generating the corresponding cURL (or any other language).

### Steps To Reproduce

To Reproduce

1. Create a request using OAuth Authentication Headers
HMAC-SHA1,
Consumer Key a,
Consumer Secret b,
Access Token 123,
Token Secret abc,
Timestamp 123,
Nonce 3
2. Add a GET request to `https://ads-api.twitter.com/11/stats/accounts/xxxxxxxx/active_entities?end_time=2022-08-01T00:00:00Z&entity=CAMPAIGN&start_time=2022-06-01T00:00:00Z`
3. Generate cURL </>

### Operating System

macOS

### Postman Version

9.27.2

### Postman Platform

Postman App

**Comment by sandeep-singh-pstmn** [comment]
@agreenberg18 When I used the Flicker API for Oauth1, it worked fine for me. I created a curl and used it in Postman and the terminal, and both times it worked.
can you please confirm if the issue still persists in your end

https://github.com/postmanlabs/postman-app-support/assets/85243040/5df49c8a-78df-4161-bcb4-d4a40dcaa1ee

**Comment by sandeep-singh-pstmn** [comment]
@agreenberg18 closing this issue for the time being. If the issue arises again, feel free to reopen it.
