### ISSUE TITLE
Can not turn off INITIAL VALUE and CURRENT VALUE columns

### ISSUE THREAD

**Issue by SemyenSoldatenko** [a85/POSTMan-Chrome-Extension#11166]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Can not configure UI to have only one column in environment configuration. **Value**.

* I don't want CURRENT VALUE
* I don't want INITIAL VALUE
* I don't need any related garbage in the interface, like Persist ALL, Reset ALL.

I need only one simple column VALUE. Like it was before!

### Steps To Reproduce

Can not configure UI to have only one column in environment configuration. **Value**.

* I don't want CURRENT VALUE
* I don't want INITIAL VALUE
* I don't need any related garbage in the interface, like Persist ALL, Reset ALL.

I need only one simple column VALUE. Like it was before!

### Screenshots or Videos

 Can not configure UI to have only one column in environment configuration. **Value**.

* I don't want CURRENT VALUE
* I don't want INITIAL VALUE
* I don't need any related garbage in the interface, like Persist ALL, Reset ALL.

I need only one simple column VALUE. Like it was before!

### Operating System

macOS

### Postman Version

9.14.0

### Postman Platform

Both

### Additional Context?

Can not configure UI to have only one column in environment configuration. **Value**.

* I don't want CURRENT VALUE
* I don't want INITIAL VALUE
* I don't need any related garbage in the interface, like Persist ALL, Reset ALL.

I need only one simple column VALUE. Like it was before!

**Comment by DannyDainton** [comment]
Hey @SemyenSoldatenko 

The variables UI has been displayed that way since ~2018, I'm unsure what you mean by "Like it was before".

As you have decided the repeat the same information in each of the fields and not provide any constructive or actionable information, I'm going to close this issue.
