### ISSUE TITLE
The latest version does not support exporting V1

### ISSUE THREAD

**Issue by yewanji** [a85/POSTMan-Chrome-Extension#11171]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

The latest version does not support exporting V1, so our interface cannot be imported directly into YAPI

### Steps To Reproduce

none

### Operating System

WINDOW

### Postman Version

 9.0.9

### Postman Platform

Postman App

**Comment by DannyDainton** [comment]
Hey @yewanji 

This was removed when the major version went from v7 > v8:

> You will only be able to export and import a collection in v2 format. This will help us in providing you with an integrated experience with the Postman toolchain. You can find more information about this [here](https://go.pstmn.io/collection-v1-format-removal).
