### ISSUE TITLE
Postman can't return the error messages we needed, but return "Parse Error: Response overflow"

### ISSUE THREAD

**Issue by ErnstIngmar** [a85/POSTMan-Chrome-Extension#11179]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

When you send a request, you get some error message from the server, postman won't return the error messsage, but return "Parse Error: Response overflow"

### Steps To Reproduce

1. Open a new request tab
2. Send the request 
3. See the response tab view 
4. See error message: Parse Error: Response overflow

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/12929063/184107125-b606e3a0-481c-40fb-889a-75c9bda46b4e.png)

### Operating System

Edge 104 / Windows 10

### Postman Version

Version 9.28.2-220811-0343  

### Postman Platform

Both

**Comment by ErnstIngmar** [comment]
Postman for Web  Version 9.28.2-220811-0343

**Comment by DannyDainton** [comment]
Hey @ErnstIngmar 

Your request/response would be very specific to your context - We're going to be unable to recreate this same behaviour, given the steps you have provided as it wouldn't be the same for _any_ request being sent from Postman.

Can you update the issue and provide more details about the request that you're sending and the response message that you were expecting to see returned, please?

**Comment by ErnstIngmar** [comment]
### Steps To Reproduce
I want to check all the server mesasges be returned correctly , when the specific value in body is wrong or not surport in your api. 

1. Open a new request tab
2. In the request body, set one value be wrong data, which your api don't surport, Then Send the request 
3. See the response tab view 
4. See error message: Parse Error: Response overflow —— > here , the server had returned detail error messages, I can see the returned values from jMeter, but I can't see it in postman.

I guess, this just a similar bug like "Parse Error: Header overflow"

**Comment by DannyDainton** [comment]
What is the returned value you're expected to see in Postman? That request is very contextual to your server.

Can you provide an example of what's returned in Jmeter? 

If I make the same request to say `https://postman-echo.com/post` I'm not going to see that error because it's not going to your server.

**Comment by ErnstIngmar** [comment]
When I send a post request with body {  "id": null}, set id value to be null,.

My server return the error message: "Param [id] is Empty", I can see this message in JMeter correctly.

But Postman just returned "Parse Error: Response overflow" , not the correct message .

It's not the correct message from the server. just an error from  postman.

**Comment by dev-sharma-08** [comment]
@ErnstIngmar,
Sorry for the late response, we are unable to reproduce this error with the information that you have provided. Can you provide us with a demo server code (zip file) that can reproduce this error, so that we can look into this further?

**Comment by ximki** [comment]
> 

if I return a StatusCode(MyCode,MyError) from my Api it shows the same error "Response overflow", you can reproduce the issue as easy as that :)

**Comment by dev-sharma-08** [comment]
@ximki, Can you help us with how are you sending this to API, and what does this function `StatusCode` do? It would be helpful if you could provide a sample code for your server excluding any sensitive information.

**Comment by ximki** [comment]
> 

 StatusCode is a method of AspNetCore.MVC.baseController 
it was problem with the api implementation I think, because tried with another API and it returned the result as expected with the status code and error description :)

**Comment by dev-sharma-08** [comment]
@ximki, I am glad to know that it worked. For now I am closing this issue, feel free to open this if you encountered this issue again.

**Comment by sanjay306** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the tracker for existing similar issues and I know that duplicates will be closed
> 
> ### Describe the Issue
> When you send a request, you get some error message from the server, postman won't return the error messsage, but return "Parse Error: Response overflow"
> 
> ### Steps To Reproduce
> 1. Open a new request tab
> 2. Send the request
> 3. See the response tab view
> 4. See error message: Parse Error: Response overflow
> 
> ### Screenshots or Videos
> ![image](https://user-images.githubusercontent.com/12929063/184107125-b606e3a0-481c-40fb-889a-75c9bda46b4e.png)
> 
> ### Operating System
> Edge 104 / Windows 10
> 
> ### Postman Version
> Version 9.28.2-220811-0343
> 
> ### Postman Platform
> Both
> 
> ### Additional Context?
> _No response_

Hi,
   When I enter wrong inputs in postman I want  to return error message but, It showing 200 ok
   please clear my doubt
