### ISSUE TITLE
Invite workspace invalid email error count displays the incorrect count of errors

### ISSUE THREAD

**Issue by sseenivasan89** [a85/POSTMan-Chrome-Extension#11173]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

when i tried to invite the people to my workspace from **Invite** button on header, and selected the **Add from file** option and uploaded the txt file (attached for reference) actually it has **4 invalid emails** but the postman error shows **only 2 email is invalid**

### Steps To Reproduce

1. Open the postman web
2. Click on invite button on header
3. Select the add from file option
4. Upload the file (txt) with some invalid emails
5. Check the invalid email count in the error 

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/44080743/183858091-1e2bea34-1608-4f31-a5dd-2aec1358983e.png)

### Operating System

Windows

### Postman Version

9.28.1-220808-1444

### Postman Platform

Postman Web

### Additional Context?

Attached the txt file for reference
[TestPostman.txt](https://github.com/postmanlabs/postman-app-support/files/9298427/TestPostman.txt)

**Comment by DannyDainton** [comment]
Hey @sseenivasan89 

Thanks for raising this. The puralisation in that error message is wrong so we'll need to fix that but the count is based on unique emails, rather the overal number. As you have 3 blank emails, it's counting that as one invalid.

I'm going to raise this with the team to understand what the expectation/behaviour should be here.

**Comment by sseenivasan89** [comment]
Hey @DannyDainton 

Yes the pluralization also wrong it should be **2 emails are invalid**

Thanks !!

**Comment by akshay-kulkarni-03** [comment]
Hi @sseenivasan89 , thanks for reporting this! We will triage this from our side and post updates once we have identified the issue at our end.

**Comment by akshay-kulkarni-03** [comment]
Hi @sseenivasan89 , we have fixed this issue. Let us know if you face it again.
