### ISSUE TITLE
Pull Changes not pulling all changes from master branch

### ISSUE THREAD

**Issue by bdlee420** [a85/POSTMan-Chrome-Extension#11177]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

We have a request that has a body: x-www-form-urlencoded with a few key/value pairs. If we add a new key/value pair or change an existing one in the master branch you can't pull those changes to other forks.  In the fork, it does tell you there are changed, but then when you Pull Changes, it doesn't actually pull anything.  You have to delete your fork and create a new one or manually make the changes.

This is a major issue in the source control functionality as it is not easy to catch and can create lots of issues with the wrong requests being sent.

### Steps To Reproduce

1. Create new collection
2. Add new request with Body = x-www-form-urlencoded
3. add 1 key value pair
4. save request
5. fork collection
6. make a change to the key/value in the original collection, save it
7. try to pull changes into the fork
8. see that it doesn't pull the changes.

### Operating System

Windows

### Postman Version

9.27.2

### Postman Platform

Postman App

**Comment by ankitjaggi** [comment]
@bdlee420 I tried reproducing the issue with the steps you provided, but I don't see the issue. Will it be possible for you to send a screen recording of the same problem to help@postman.com for better debugging?

**Comment by bdlee420** [comment]
Video sent, thanks.

**Comment by bdlee420** [comment]
I am now on version  v9.29.4 and this issue has been resolved. Thanks you for the quick fix.
