### ISSUE TITLE
Segfault on chromium

### ISSUE THREAD

**Issue by tomibennett** [a85/POSTMan-Chrome-Extension#1117]
It happens every time I click on the SignIn button: here's the [report](https://gist.githubusercontent.com/magneto/6263e740df46ae914872/raw/8a79ff3aeb4d8bdd778e55870f25d6a3782d29ab/mac%20generated%20report)

**Comment by abhijitkane** [comment]
@magneto Can you check if this is still happening with v3.0.4? We haven't been able to reproduce this on Ubuntu/Chromium.

**Comment by tomibennett** [comment]
can't test right now on Mac but it's working perfectly on Arch/Chromium. I keep you up to date on Mac ASAP
