### ISSUE TITLE
Creating an uptime monitor option is missing in the recent version of postman

### ISSUE THREAD

**Issue by sseenivasan89** [a85/POSTMan-Chrome-Extension#11172]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Earlier i have created uptime monitor in my workspace and now **i dont see the option to create an uptime monitor option**s in my postman web

### Steps To Reproduce

1. Open postman in web
2. Goto monitors tab
3. Click on create monitors
4. Right should the uptime monitor option is not found

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/44080743/183852212-316c19ba-c919-4de2-b384-0b2c3e0e0221.png)

### Operating System

Windows

### Postman Version

9.28.1-220808-1444

### Postman Platform

Postman Web

**Comment by DannyDainton** [comment]
Hey @sseenivasan89 

Just wanted to provide you with more context, this is an extract from a discussion on the repo that we were using to capture feedback for uptime monitors.

> The beta period for Uptime monitors has now ended. Existing Uptime monitors will continue to function as before, but it is no longer possible to create new Uptime monitors.

https://github.com/postmanlabs/uptime-monitors/discussions/24

cc @godfrzero

**Comment by DannyDainton** [comment]
Closing this as it was actively removed (Details in the discussion thread mentioned above) and is not just _missing_ from the UI.
