### ISSUE TITLE
Flows are failing to pass values into variables and durables

### ISSUE THREAD

**Issue by daviddriver-enactor** [a85/POSTMan-Chrome-Extension#11180]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Since updating to version 9.28 (I believe from 9.26), the flows I have been using are not behaving as expected. In all cases, it appears as if data is not being assigned when it use to. This can be seen easiest with loops that fail to loop, where they are only invoked once. Values are not being passed into request variables. Durables are not appearing in the output of a terminal. Flows can also hang when trying to create a durable after a send request, even though the response can be output to a terminal. 

The flows also appear to be read-only in places. So new blocks can be added, but I can't seem to select requests or environments from drop-downs or change the output for terminals. But that sounds like a separate issue since I wouldn't expect to have to edit existing flows.

### Steps To Reproduce

1. Create a new flow
2. The flow should consist of `Create Data`, `Loop Over List`, `Send Request`, `Create Durables`, and `Terminal`
3. Create Data should be a list of 5 strings, `ListItem1`, `ListItem2`, `ListItem3`, `ListItem4`, `ListItem5`
4. `Send Request` should have a variable called `ListItemName`, which takes in the variable from `Loop Over List`
5. The variable should be resolved in the body of the request being sent, so the JSON will show if the value has been set
6. `Create Durables `should store the status code from the `Send Request`

The expectation is that the terminal will have 5 new entries after the flow is run, with each having a value set in the durables

### Operating System

macOS

### Postman Version

9.28

### Postman Platform

Postman App

**Comment by xhocquet** [comment]
I am seeing the same issue:

1. Create a "Create Data" block containing a list with a single string item
2. Create a connected "Loop Over List" block
3. Create a connected "Send Request"
4. If you open up the Send Request variables, the data from the list does not appear in the possible selections for "Current Value". I've also tried manually writing references to `/data` and other tries including nested fields on an object, and none make it through.

**Comment by rabbah** [comment]
Flows supports latched variables now which solves this problem a different way.
