### ISSUE TITLE
500 Internal Server Error is displaying for Visualizer when we send request for Postman2OpenAPI

### ISSUE THREAD

**Issue by srinivasskc** [a85/POSTMan-Chrome-Extension#11182]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

POST https://demo.postmansolutions.com/postman2openapi
The Visualizer is displaying 500 Internal Server Error

Which is shared in the https://www.youtube.com/watch?v=VcSBuM3aR74 

### Steps To Reproduce

Followed the steps as in the video. https://www.youtube.com/watch?v=VcSBuM3aR74 
and sent the request  - POST https://demo.postmansolutions.com/postman2openapi

Actual Result: 500 Internal server error.

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/26836928/184281148-b6826964-e791-4ae4-8273-d6fd089fe1d9.png)

### Operating System

Windows

### Postman Version

 9.28.0

### Postman Platform

Postman App

### Additional Context?

POST /postman2openapi HTTP/1.1
Content-Type: application/json
User-Agent: PostmanRuntime/7.29.2
Accept: */*
Cache-Control: no-cache
Postman-Token: bc0d5e92-af8e-4483-b576-07efxxxxxxxx
Host: demo.postmansolutions.com
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
Content-Length: 246471
 
The console only showsrequest bodies smaller than 10 KB inline. To view the complete body, inspect it by clicking  Open.
HTTP/1.1 500 Internal Server Error
Date: Fri, 12 Aug 2022 03:40:22 GMT
Content-Type: application/json
Content-Length: 35
Connection: keep-alive
Apigw-Requestid: WuzBfjl9iYcEJwA=
 
{"message":"Internal Server Error"}

**Comment by DannyDainton** [comment]
Hey @srinivasskc 

This doesn't look like a _product_ issue with the Postman platform and has more to do with the resource, created by Gbadebo Bello and Garrett London, throwing the error. You would see the same thing if you made the same request outside of Postman.

I'm going to close this issue and ask that you raise it on the [Postman Community](https://community.postman.com/) site and if you tag Kevin Corbett, who will have more context. This is the [live stream thread.](https://community.postman.com/t/postman-live-exploring-postman-collection-converters-august-11th-2022/37943)
