### ISSUE TITLE
variables being transmitted in plain text

### ISSUE THREAD

**Issue by JamesDevOpsShipman** [a85/POSTMan-Chrome-Extension#11187]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

We have secrets in postman, set as a secret type, and in Azure KeyVault that we need to use. The problem is when the request is sent the value in that secret is easy to see.

### Steps To Reproduce

1. create a secret, I don't think scope matters
2. create a simple request that uses that secret
3. the expanded details of the request displays the secret

### Operating System

Windows 10

### Postman Version

9.26.8

### Postman Platform

Postman App

### Additional Context?

I looked through documentation and was not able to find an answer to this issue.

**Comment by DannyDainton** [comment]
Hey @JamesDevOpsShipman 

The secret variable type in Postman is more of a UI-based masking feature, it doesn't change value when/if used in a request.

>we address vulnerabilities resulting from mistakenly sharing your tokens and secrets to an unintended audience while screen sharing or live streaming. Masking your sensitive data will also help you avoid threats such as over-the-shoulder attacks.

https://blog.postman.com/introducing-secret-variable-type-in-postman/

**Comment by DannyDainton** [comment]
Hey @JamesDevOpsShipman 

I'm going to close this issue as it's currently working as it was intended, this might not be how you would have hoped though.

Could you raise a new Feature Request containing the details of how you're like to see the feature being used? The more context and examples that you can provide the better 🏆
