### ISSUE TITLE
Postman not opened on M1 Mac MacBook Air 12.5

### ISSUE THREAD

**Issue by mandaputtra** [a85/POSTMan-Chrome-Extension#11191]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Can't open postman after download and unzipping

### Steps To Reproduce

1. Download latest postman app (not the canary) for M1
2. Unzip
3. Open it
4. App not opening

### Operating System

MacOS

### Postman Version

Latest, from download pages

### Postman Platform

Postman App

**Comment by jviotti** [comment]
Hi @mandaputtra ,

What do you get if you try to open the app from the Terminal? For example:

```sh
$ /Applications/Postman.app/Contents/MacOS/Postman
```

**Comment by mandaputtra** [comment]
It's turns out that I can open it that way. And after that I can open it normally 🙃 Damn software ~ so confusing.
