### ISSUE TITLE
Feature Request: Support gRPC prefix path on URL 

### ISSUE THREAD

**Issue by daneshvar** [a85/POSTMan-Chrome-Extension#11192]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

We use Envoy to routing and clustering our back-end services and we use prefix for routing between the services and some gRPC tools such as Kreya and BloomRPC support path on request URL but Postman doesn't support URL path and when I use prefix path on the URL like "grpc://localhost:1337/api" Postman raise error "Failed to parse DNS address dns:localhost:1337/api"

### Describe the solution you'd like

gRPC for calling methods use a string such as: /packagename.ServiceName/MethodName so if we have a request URL for example "grpc://localhost:1337/api" you can parse this URL and use host name and port (localhost:1337) for make connection to server and  if exists a path in the URL (/api in this URL) add into start of the method name before call it like as /api/packagename.ServiceName/MethodName.

thank you so much.

**Comment by codenirvana** [comment]
@daneshvar Are you trying to connect to a gRPC-Web server?

**Comment by daneshvar** [comment]
I don't think that Postman supports gRPC-Web now, I have a gRPC request, not a gRPC-Web, but I have a prefix path before the gRPC method's name like this: grpc://example.com:8080/api
I know it's not part of standard gRPC, but it's usable and several tools like Kreya support it.
For example, I can do a request on Kreya like this: grpc://example.com:8080/api.
The standard gRPC library in Go doesn't support this feature, but we added it to the Go gRPC library with use of a middleware that adds my path prefix (/api) into the start of the gRPC method's name before it is invoked.

**Comment by N0N4M3pl** [comment]
Hi.
I have same problem and I would like to upvote this issue.
If I set URL for example as `abc.domain.com/api` then postman shows "_Service unavailable ... Name resolution failed for target abc.domain.com/api_"

**Comment by DavidHsaiou** [comment]
HI,
Same here

**Comment by dumkin** [comment]
Hi.
I have same problem and I would like to upvote this issue.

**Comment by codenirvana** [comment]
Hey everyone, can someone share a demo repository to reproduce this behavior locally to fast-track the fix?

**Comment by erdemkayatr** [comment]
Hi Everyone;
When will solve this problem? Do you have any ideas? :)

**Comment by appurva21** [comment]
Hey everyone! We have added support for prefix path in gRPC server URLs. 

This is being rolled out as part of v10.6.0 and should be available for everyone by early next week.
