### ISSUE TITLE
GraphQL Test fails as expected when run manually but passes in collection tests 

### ISSUE THREAD

**Issue by JESii** [a85/POSTMan-Chrome-Extension#11199]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

I’m creating my first tests around a graphQL collection. I started by creating two simple tests to ensure that a query executed successfuly and did not contain an “errors” element.

I tested this against a single query by modifying the query parameters to generate an error and ran the two tests – I got a test failure as expected.

When I run the entire collection using these same two tests, that particular query passes even though it failed when tested manually.

### Steps To Reproduce

1. Create a graphql query
```
  query GET_CLIENT_NAMES($id: ID!, $asOfDate: ID!) {
    data: GetClient(id: $id, asOfDate: $asOfDate) {
      displayName
    }
  }
```

2. Create graphql query variables;
```
{
    "id": "AMEI",
    "asOfDate": 1653980400
}
```

3. issue the query against http://localhost:7071/graphql and get the following:
```
{
    "data": {
        "data": {
            "displayName": "AMEI"
        }
    }
}
```

pm.response.text() => `{"data":{"data":{"displayName":"AMEI"}}}`

4. Modify the query variable to generate an error:
```
{
  "errors": [
    {
      "message": "Cannot access client: AMEX",
      "locations": [
        {
          "line": 2,
          "column": 5
        }
      ],
      "path": ["data"],
      "extensions": {
        "code": "FORBIDDEN",
        "exception": {
          "stacktrace": [
            "ForbiddenError: Cannot access client: AMEX",
            "    at GetClient (file:///Users/jseidel/ppg/hall/client-graphql-server/src/graphql/resolvers/client/queries/getClient.js:36:11)",
            "    at processTicksAndRejections (internal/process/task_queues.js:95:5)"
          ]
        }
      }
    }
  ],
  "data": {
    "data": null
  }
}
```

5. Create test scripts to test for errors
```
pm.test("Ensure 200 status code", function() {
    pm.response.to.have.status(200);
})
console.log('pm.response.json()', pm.response.json());)
console.log('pm.response.text()', pm.response.text());
pm.test("Response does not contain errors response", function () {
    pm.expect(pm.response.text()).to.not.include("errors");
});
```

6. Run the tests on the successful query; get the following response:
![2022-08-18 at 1 45 PM](https://user-images.githubusercontent.com/486/185491487-fb0344be-7ddb-4e7a-b5be-32962edcdbd5.png)
7. Run the tests on the failing query; get the following resonse:
![2022-08-18 at 1 46 PM](https://user-images.githubusercontent.com/486/185491879-cbd96e48-4214-4cb9-a046-8606b3324d9e.png)
8. Now create. those same tests in the collection of which this query is a member
8a. Successful response tests work as expected and show passing results.
8b. Failing response tests also show both tests passing which is incorrect.
![2022-08-18 at 1 52 PM](https://user-images.githubusercontent.com/486/185492835-644f8f34-73eb-4b1e-b25a-3ed7553b9b22.png)

There's gotta be something I'm doing wrong...

### Operating System

MacOS

### Postman Version

9.21.5

### Postman Platform

Postman App

**Comment by DannyDainton** [comment]
Hey @JESii

Something that catches people out in some of the requests that are getting run are in an unsaved state.

That would show as passing or failing  when run manually (depending on the expected outcome) but could show something different when run in the collection runner. The collection runner isn't aware of any changes made in the requests until they have been saved. 

Can you confirm that all requests in the collection have been saved?

**Comment by JESii** [comment]
Thanks, Danny… I checked and the collection was saved

**Comment by JESii** [comment]
Oh... I went back and re-read your comment. The collection had been saved; the query I was using as a test had been saved... but other queries had not been saved. When I went back and made sure every query in the collection was saved and ran the test, then it ran OK -- i.e., failed the expected test.
Thanks very much...
