### ISSUE TITLE
Importing a json file throws an error

### ISSUE THREAD

**Issue by iuliia-eagle** [a85/POSTMan-Chrome-Extension#11195]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Attempting to import a json file (or json raw text) taken from a Swagger page will throw an error: 'format not recognized'.

### Steps To Reproduce

1. Select Import button
2. Select json file
3. Observe error is immediately thrown
4. Observe same behavior when user selects paste raw text option

### Screenshots or Videos

https://user-images.githubusercontent.com/57791709/185149895-ef664e52-d5d9-4929-82ab-ec2bc44364e0.mp4

### Operating System

 Windows 10

### Postman Version

9.28.2

### Postman Platform

Postman App

**Comment by DannyDainton** [comment]
Hey @iuliia-eagle 

Could you share the file or the raw text of the Collection you're trying to import, please?

**Comment by DannyDainton** [comment]
Hey @iuliia-eagle 

We're still waiting on the file that you used that will help us triage this issue - It's going to be difficult to take this further without that information.

**Comment by Saver3011** [comment]
Hey @iuliia-eagle 
Is the import working now? If not, please provide the JSON file.

**Comment by DannyDainton** [comment]
@iuliia-eagle I'm going to close this issue, if you're able to provide the information that's been requested we can open it up again.
