### ISSUE TITLE
GRPC - Error with existing and and API after Update to Postman v9.29.0

### ISSUE THREAD

**Issue by uschwag** [a85/POSTMan-Chrome-Extension#11201]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

After the Update to Postman v9.29.0 we receive on every existing gRPC request an unspecified error: "Something Went Wrong
Postman has encountered an error." . 
Other requests than gRPC work. To be sure that other problems are not the reason we tested with GRPCUI and it works there. We also deletedthe API in Postman and created it from scratch but that did't help either

### Steps To Reproduce

Open any gRPC Request and invoke it.

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/91600653/185621779-158225fa-bb5f-4770-9b96-4a24eb2d1f75.png)

### Operating System

Windows 10

### Postman Version

9.29.0

### Postman Platform

Postman App

**Comment by DannyDainton** [comment]
Hey @uschwag,

Thank you for raising this issue 🏆  - I've forwarded it to the team and they are investigating the matter. We will update this thread once we have more information.

**Comment by codenirvana** [comment]
@uschwag We've identified the issue and working on the fix.

Can you confirm that this is not happening for new gRPC requests?

**Comment by uschwag** [comment]
@codenirvana it is indeed so. Only existing requests don't work anymore but if I create a new one and select everything again it works although it is nearly a copy of the existing one.

**Comment by codenirvana** [comment]
@uschwag Thanks for the confirmation.

We're releasing a new version with the fix. I'll let you know once it's available.

**Comment by codenirvana** [comment]
@uschwag We've pushed a fix for this in `v9.29.3`. Can you please update your app and confirm if that fixes your issue?

**Comment by uschwag** [comment]
@DannyDainton the issue is fixed with v9.29.3, Thanks a lot to all for reacting so fast.
