### ISSUE TITLE
major performance issues with 9.29.3

### ISSUE THREAD

**Issue by byrdman** [a85/POSTMan-Chrome-Extension#11207]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

After updating to 9.29.3 there are several major issues occurring:
1 - can no longer double left click on a request and have it open a tab to run, edit, etc.  only way to open it is to right click and select edit
2 - can no longer double left click on a collection and have it open a tab to run, edit, etc.  Right clicking and picking edit doesn't even open collections.  There is therefore no way to maintain collection level authentication, pre-request scripts, tests, etc.

### Steps To Reproduce

upgrade to 9.29.3
attempt to maintain existing requests or collections

### Operating System

Windows

### Postman Version

9.29.3

### Postman Platform

Postman App

**Comment by byrdman** [comment]
What is super weird is it only seems to affect 1 machine.  I've tried uninstalling Postman and reinstalling, this didn't fix it.

**Comment by byrdman** [comment]
on further investigation, it only happens if I'm signed into my Postman account, if I sign out so it doesn't try to sync data to the cloud everything works as expected.  Are there logs I can look at to see what my network might be blocking?

**Comment by kamalaknn** [comment]
Hey @byrdman 

1. Are you seeing slowness in specific actions on the sidebar or does this happen across all actions in Postman? Is this particular to Postman or do you see general slowness in other applications on your system? Could you share a screen-recording of the issue?
2. You can check the network activity from `View -> Developer -> Show Devtools (Current View)`. Note that some of the activity might be happening over a WebSocket connection to Postman servers. Do you see any errors in the devtools console?
3. Could you confirm if you are still seeing the issues after you logout and login?

**Comment by byrdman** [comment]
@kamalaknn The main actions it affected were:
Selecting a collection to either let me setup a run or possibly edit the pre-request scripts or authentication bits
Selecting a request to either edit it or run a single request

I unfortunately can't attach a screen-recording as the issue seems to have gone away once I signed out of my account.  

After signing out of my account and back in the problem appears to have gone away.  Perhaps there was some cached data that was cleaned up?  I will say several of my collections are massive (I have 4 that in their exported form are > 1MB (1.7, 2.8, 3.0, and 7.3 to be exact).  These used to timeout during the import process, that issue also seems to have gone away.

Is there a way to "clean the local cache" without going through the signout / signin loop?

**Comment by kamalaknn** [comment]
@byrdman Thanks for the update. 

From your description, it looks like the problem may not be performance related, but some action could have led to the state of your tabs getting corrupt. Logging out should have cleared this state and fixed the issue. 

Let us know if you see this again.
