### ISSUE TITLE
Newman: Give more information to help find syntax errors

### ISSUE THREAD

**Issue by ColdCerealAtWork** [a85/POSTMan-Chrome-Extension#11203]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

I have a large collection that complains about a syntax error when I try to run it on my Linux server. All it tells me is 
 001.  SyntaxError                                                                                                                                                         
                       Unexpected token .                                                                                                                                  
                       at prerequest-script                                                                                                                                
                       inside "Collection Utilities / Auth / Retrieve New Token"     

The problem is my pre-request tab has a ton of code in it and works fine on my Windows machine.

### Describe the solution you'd like

if the error included the entire line, or even the line number that contains the error it would be really helpful in troubleshooting my syntax issue.

**Comment by DannyDainton** [comment]
Hey @KristianAtVsp

This is the tracker for all Postman App related issues and feature requests. 

Newman has its own repository, could I ask that you raise this on there, please.

https://github.com/postmanlabs/newman

I'm going to close this issue now.

**Comment by ColdCerealAtWork** [comment]
@DannyDainton apologies, moving the request now.
