### ISSUE TITLE
I have APIs which I can't remove (from possible runaway interceptor session)

### ISSUE THREAD

**Issue by DougMaisells** [a85/POSTMan-Chrome-Extension#11208]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

On my POSTMAN workspace, at one time I had an interceptor running in Chrome and in Postman.   I had over 2000+ APIs.   I was able to painfully delete most of them.   There are still about 99 which I cannot delete.  If I delete invidiually, I got a confirmation as well as an error message yet the API remains

### Steps To Reproduce

1. When I view my workspace, I have APIs which got there errantly from the interceptor
2. Cannot bulk delete , hangs when press delete button on modal
3. deleting invidually gives success and error message yet API remains

### Operating System

MacOS Monterey 12.5.1

### Postman Version

9.29.3

### Postman Platform

Postman App

### Additional Context?

nothing

**Comment by postman-staff** [comment]
Hi @DougMaisells,
Thanks for reaching out! I am more than happy to assist you with the issue!

As I understand it, you're encountering an issue when trying to delete APIs.

Do you know if you encounter the same error when doing it from the browser? Can you try it from the web app from the workspaces, they can be accessed from the URLs below.

go.postman.co/me/apis

On the other note, I just want to share with you, that we are already looking at options of bulk edit/delete for API's and environments to make them more efficient and more accessible. Our engineers are publicly tracking the feature here:
https://github.com/postmanlabs/postman-app-support/issues/11116

Feel free to add your comments and subscribe to the issue so that you will be notified when there is any movement in the issue.

Let us know if you have any questions.

via @Lincimary | Postman Support

**Comment by DougMaisells** [comment]
![99_bottles_of_apis_on_the_wall](https://user-images.githubusercontent.com/12070836/186192359-3e30dc27-c9e3-4a8f-bea5-c48b373de95f.png)

**Comment by postman-staff** [comment]
Hi @DougMaisells,
Thank you for writing back!

From the screenshot, I see that you are in the Collections tab and pointing out requests under a folder.
Is the API that you are trying to delete reflects here: [go.postman.co/me/apis](go.postman.co/me/apis)
Do you see any errors while deleting?

Could you try moving the API to any other workspace and then attempt deleting it?

You can also try deleting it through Postman API and see if it helps?
https://www.postman.com/postman/workspace/postman-public-workspace/request/12959542-fed26b03-2f38-456f-bdfc-23cd13738316

If you’re still facing this issue, can you please try to [submit a support request](https://support.postman.com/hc/en-us/requests/new/) with the Github thread information along with the below details:

- Screen record of the behaviour
- A copy of your [app logs](https://support.postman.com/hc/en-us/articles/360025298633-How-to-collect-logs-)

Looking forward to your response.

via @Lincimary | Postman Support

**Comment by DougMaisells** [comment]
https://user-images.githubusercontent.com/12070836/186447686-7086d7be-4a96-4ca8-8914-ffb5ed94b996.mp4

**Comment by DougMaisells** [comment]
Same error with either site listed in the request.   Seems like there are 99 stubborn APIs at the end of this listing which cannot be deleted.  You can't click the Delete button on the modal either if you select multiple APIs.

**Comment by postman-staff** [comment]
Hi @DougMaisells,
Thank you for providing the requested details.

I guess we need to escalate to the engineering team along with the app logs to check on this further. As mentioned previously, could you please login a ticket(https://support.postman.com/hc/en-us/requests/new/) with us so that we can continue investigating?

Also, please send over the console logs and app logs so our team can check the case further ( https://support.postman.com/hc/en-us/articles/360047765713-Where-can-I-find-logs-for-the-Postman-Application- )

Thank you for your cooperation on this issue, looking forward to your response.

via @Lincimary | Postman Support

**Comment by DougMaisells** [comment]
https://support.postman.com/hc/en-us/requests/116138?page=1

I’ve done as you asked and included logs and two screencasts.  I can’t spend any more time on this.  Please provide a fix.  Thanks


From: Postman Support ***@***.***>
Date: Wednesday, August 24, 2022 at 10:39 PM
To: postmanlabs/postman-app-support ***@***.***>
Cc: Doug Maisells ***@***.***>, Mention ***@***.***>
Subject: Re: [postmanlabs/postman-app-support] I have APIs which I can't remove (from possible runaway interceptor session) (Issue #11208)
[EXTERNAL]

Hi @DougMaisells<https://protect-us.mimecast.com/s/I0FkCOYZKzF6xAQ2hEzqkO?domain=github.com>,
Thank you for providing the requested details.

I guess we need to escalate to the engineering team along with the app logs to check on this further. As mentioned previously, could you please login a ticket(https://support.postman.com/hc/en-us/requests/new/<https://protect-us.mimecast.com/s/je8xCPNYLAu7X4V5C0ZtMm?domain=support.postman.com>) with us so that we can continue investigating?

Also, please send over the console logs and app logs so our team can check the case further ( https://support.postman.com/hc/en-us/articles/360047765713-Where-can-I-find-logs-for-the-Postman-Application-<https://protect-us.mimecast.com/s/J2lVCQWOMBC5P6ZNfM7Hy-?domain=support.postman.com> )

Thank you for your cooperation on this issue, looking forward to your response.

via @Lincimary<https://protect-us.mimecast.com/s/iBAhCR6LNDIAWrZgtO2R3Q?domain=github.com> | Postman Support

**Comment by DougMaisells** [comment]
Postman,
I tried to post a screen recording from SnagIt but it says the file is too large.  Definitely reproducible at the site below.
See attached.
Doug M

From: Postman Support ***@***.***>
Date: Wednesday, August 24, 2022 at 4:59 AM
To: postmanlabs/postman-app-support ***@***.***>
Cc: Doug Maisells ***@***.***>, Mention ***@***.***>
Subject: Re: [postmanlabs/postman-app-support] I have APIs which I can't remove (from possible runaway interceptor session) (Issue #11208)
[EXTERNAL]

Hi @DougMaisells<https://protect-us.mimecast.com/s/1KpwCJ6PBrI7Mj3vUVdMXZ?domain=github.com>,
Thank you for writing back!

From the screenshot, I see that you are in the Collections tab and pointing out requests under a folder.
Is the API that you are trying to delete reflects here? go.postman.co/me/apis<https://protect-us.mimecast.com/s/7Qx-CKr6DvcjpRzNCvcXPi?domain=go.postman.co>
Do you see any errors while deleting?

Could you try moving the API to any other workspace and then attempt deleting it?

You can also try deleting it through Postman API and see if it helps?
https://www.postman.com/postman/workspace/postman-public-workspace/request/12959542-fed26b03-2f38-456f-bdfc-23cd13738316<https://protect-us.mimecast.com/s/mTW8CL9PEwcJ8zyrTPEndJ?domain=postman.com>

If you’re still facing this issue, can you please try to submit a support request with the Github thread information along with the below details:

  *   Screen-record of the behaviour
  *   A copy of your app logs

Looking forward to your response.

via @Lincimary<https://protect-us.mimecast.com/s/5uqOCM89GxTQmnM1HWlbHE?domain=github.com> | Postman Support

**Comment by xk0der** [comment]
Closing this GitHub issue.
@DougMaisells I've followed-up with you internally. 
Accept our apologies for the delay in addressing this issue.
