### ISSUE TITLE
Generate Collection when importing openapi yaml doesnt work

### ISSUE THREAD

**Issue by araeuchle** [a85/POSTMan-Chrome-Extension#11210]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Hey guys, 
i updated my Postman to Version 9.27.0 on Ubuntu 22.04 LTS and i found a weird bug in Postman. 
When i want to import an openapi formatted yaml file Postman is able to generate an api from it. 
Then we have the Checkbox to generate automatically a collection from it but this feature stopped working. The collection never shows up. 

What i tried so far was reinstalling postman, creating a new account, adding new workspaces. Nothing worked so far. Collection never showing up. A workaround i found is to click on the api and go to Generate Collection. This works but requires more clicks and is super uncomfortable. 

Any hints on what we can do to solve this issue?

Thanks in advance.

### Steps To Reproduce

1. Download https://raw.githubusercontent.com/OAI/OpenAPI-Specification/main/examples/v3.0/petstore.yaml. 
2. Click Import 
3. Choose the downloaded petstore.yaml file 
4. Click Generate Collection 
5. The Success screen shows API and Collection where generated. API shows up, collection doesnt  

### Operating System

Ubuntu 22.04 LTS

### Postman Version

9.27.0

### Postman Platform

Postman App

**Comment by devloberto** [comment]
I have the same behavior with Postman v7 (installed from snap on Kubuntu 22.04 LTS) and also on the postman website.

_Infos about the desktop app:_
> Postman for Linux
> Version 7.36.7
> linux 5.15.0-46-generic / x64

**Comment by DannyDainton** [comment]
Hey folks,

Appreciate you raising this! 🏆 I've forwarded this on to the teams to investigate further. Any updates will be posted here once we have some information to share.

**Comment by umeshp7** [comment]
@araeuchle Could you share a recording of the error being reproduced? Also if you could try updating the app. We recently fixed a bug around URL imports this could be related to that. 

@thecijal The version you have mentioned is quite old. Will you be able to update to the latest version or use Postman on web? 

https://user-images.githubusercontent.com/31915995/186124849-732eb349-c549-4693-b31f-f18c0b58b838.mov

Here is the recording for the petstore URL being imported^

**Comment by araeuchle** [comment]
@umeshp7 

Yes but now try do the same with downloaded file over the File Import. 
For us this doesnt work. We use Postman with openapi.yaml files we have in our system so we have no links which we want to import. We can only use the file import. The petstore link was just an example :) 

What @thecijal did was trying if the issue exists on an old version as well which was confirmed with that. 

I will try to do a screen recording later during the day.

**Comment by umeshp7** [comment]
My bad. I tried the import and the import itself was successful but the collection didn't show up. 
I have raised this issue with the concerned team and we will be looking into this.

**Comment by araeuchle** [comment]
@umeshp7  Thank you very much man! also great to have so fast responses! didnt expected that! :)

**Comment by koen-loyens** [comment]
I have the same issue.
When I go to the API, draft, test. There is a link to the collection but the collection is apparently in a different workspace en I don't have access to that workspace.

**Comment by umeshp7** [comment]
@koen-loyens @araeuchle @thecijal This issue has been fixed. Please try re-loading your workspace or try importing again. The collections should show up. 

cc Thanks to: @DannyDainton @barshan23

**Comment by devloberto** [comment]
It works now with postman v9 on Kubuntu 22 :)
Thanks a lot !

**Comment by araeuchle** [comment]
I can also confirm it works now again! Thank you very much guys! great work! :)

**Comment by koen-loyens** [comment]
I works now, thx
