### ISSUE TITLE
Unable to PULL CHANGES into a specific Fork

### ISSUE THREAD

**Issue by bdlee420** [a85/POSTMan-Chrome-Extension#11211]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

We have created a Fork off of a master collection. We made several changes to that Fork and are now trying to PULL CHANGES into it as other things have been modified in the master collection.  We receive this message: “Merging is in progress...", but it is never actually merged.  Several developers have tried this on the Web and Desktop app and receive the same message.  This is a really urgent issue as it blocks us and I don't really see a workaround for this. 

### Steps To Reproduce

I don't know how reproducible this is other on this one Fork. Our other Forks are working fine and merge within seconds.

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/8396279/186232553-90498864-425a-4689-8e30-3a231d893b25.png)

### Operating System

Windows

### Postman Version

9.29.5

### Postman Platform

Postman App

**Comment by postman-staff** [comment]
Hi @bdlee420,
Thank you for contacting Postman Support. I'm happy to help!

I understand that you are seeing issues with pulling changes from a fork and it is happening when you make any change with one particular collection fork, Right?
Let me know the size of the source collection?

Just to confirm you have been facing the same problem on both the Desktop app and also on our web app- go.postman.co? could you please do a test by creating a new collection and fork and seeing if the changes are merged or not being detected?

If you're able to replicate the issue both on the Postman web app and the desktop app then can you [please submit a support request](https://support.postman.com/hc/en-us/requests/new/) along with the following information:

- Github issue number
- Screen recording of what you are experiencing on the particular forked collection? We find [loom.com](http://loom.com/) helpful for this.
- A copy of your [app logs](https://support.postman.com/hc/en-us/articles/360025298633-How-to-collect-logs-).

Do not hesitate to reach out if you need any further assistance. Looking forward to your response!
via @Lincimary | Postman Support

**Comment by bdlee420** [comment]
The collection has about 1000 Requests inside it.  It has happened to a couple of forks of that size.  It is failing on both the Web and Desktop versions.  I haven't been able to replicate it with smaller collections as of now.

**Comment by postman-staff** [comment]
Hi @bdlee420,
Thank you for writing back!

I understand that issue occurs for a larger collection of about 1000 Requests. Would it be possible for you to share the collection export(via support ticket) with us so that we can check to replicate it?

As mentioned previously could you please submit a ticket(https://support.postman.com/hc/en-us/requests/new/) with us sharing the app logs to investigate further?

via @Lincimary | Postman Support

**Comment by bdlee420** [comment]
Because it was a time sensitive issue, we had to delete the master branch and recreate it using his forked branch.  It is unfortunate that we had to do it but we needed to resolve it. Because of this, I am unable to provide the data you are asking for.  As a general ask, we need to be able to rely on Pulling Changes to work every time.

I do have another branch that is letting me "Pull Changes", but when I do it says "No new changes to pull. Your forked collection is up to date.".  But it usually only lets you "Pull Changes" if there are actual changes.  Should I create a new issue for this? Or should I submit a postman ticket for that with a video?

**Comment by postman-staff** [comment]
Yes, sure I understand it.

Is that creating a pull request always shows 0 changes even though it indeed has changes?
If yes then we would ideally recommend you to submit a new ticket with us along with the video recording and HAR logs? (Do check out the below article on how to capture browser logs for your reference.

- https://support.box.com/hc/en-us/articles/360043696054-How-to-Generate-Network-Captures-for-Troubleshooting)

via @Lincimary | Postman Support
