### ISSUE TITLE
Feature to remove yourself from a not self-owned public workspace

### ISSUE THREAD

**Issue by arnav-deep** [a85/POSTMan-Chrome-Extension#11216]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

In my Workspaces list, I can see many public workspaces someone else (the owner) gave me access to. I am no longer using a few of those workspaces, which clutters my Workspace list. Their owners do not even use those Workspaces, and the only way to remove them from the Workspace list from my account is to contact the owner of the workspace and have them remove my access.

### Describe the solution you'd like

A feature in the Workspace settings to remove self (when not an admin but just have basic read access) from the Workspace.

### Describe alternatives you've considered

An alternative is to reach out to the Workspace owners who gave me access but the Workspaces may be years old and the owner account may or may not be in use.

**Comment by akshay-kulkarni-03** [comment]
@arnav-deep thanks for reporting your issue! As of today, the workspace switcher shows you the workspaces recently visited by you. The list is not populated based on who gave you access etc but rather which all workspaces which you visited recently. Could you clarify, what does `workspace list` mean? Is it the switcher/drop-down that you see on top or you are referring to `View all workspaces` page?

**Comment by akshay-kulkarni-03** [comment]
Hi @arnav-deep , closing this issue feel free to re-open if you face any problems.
