### ISSUE TITLE
Sluggish response with UI

### ISSUE THREAD

**Issue by morrisnc** [a85/POSTMan-Chrome-Extension#1121]
I am using Postman 3.x and today the response of the UI especially in History and Builder is extremely sluggish.  The collections I have saved seem to be ok, but when I double click on an entry taking me into the builder the sluggishness begins again.  Any ideas?

**Comment by morrisnc** [comment]
After using this more I think it is related to Collections as the 'Add to Collections' button is extremely slow to appear after clicking on any item in the history list.  Ideas how to fix collections?

**Comment by abhijitkane** [comment]
Is this still happening with v3.0.4?

**Comment by numaanashraf** [comment]
@morrisnc Could you update to our latest 4.0+ version and let us know if this problem still exists?
