### ISSUE TITLE
environment variable "current" value keeps being removed 

### ISSUE THREAD

**Issue by mottipazlazar** [a85/POSTMan-Chrome-Extension#11229]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

1. I have environment set with few variables, one of them called apiKey.
the initial and current values are displayed and saved under env  tab.
2. I then have 1 request /login using few  of the env variables, including apiKey in the body >> calling it pass successfully >> one of the body params are then set as env var, using this code:
var jsonData = JSON.parse(responseBody);
postman.setEnvironmentVariable("sessionToken", jsonData.sessionToken);

3. I then have another request called /users that doesn't use apiKey but uses sessionToken as a request header >> calling it pass successfully >> 
4 BUG: the apiKey current value is then disappearing from the env, and next calls for /;llogin fail on it as it is missing.

it is reproducing every time, when i call /users request.

### Steps To Reproduce

1. set env vars
2. call /login using one of the env vars >> success
3. call /users
4. the environment variable "current" value keeps being removed from env vars and /login call fails.

### Screenshots or Videos

https://user-images.githubusercontent.com/32642069/187879712-712f5194-1e4e-4241-b86a-82d501b4aae6.mov

### Operating System

macOS

### Postman Version

9.30.1

### Postman Platform

Postman App

**Comment by mottipazlazar** [comment]
UPDATE: changing apiKey env var name to something different (e.g. "apiKey_second") , and saving it, works around this issue

**Comment by shubhbhargav** [comment]
@mottipazlazar Can you confirm once if the variable `apiKey` is being used anywhere? (maybe on the collection level scripts)

If you can share the collection with this, we can debug into this further. You can share the same with us at help@postman.com

**Comment by mottipazlazar** [comment]
Hi’ I’m not sure what you mean by “collection level scripts, but I think it is not used elsewhere.

From: shubhbhargav ***@***.***>
Date: Thursday, 1 September 2022 at 20:55
To: postmanlabs/postman-app-support ***@***.***>
Cc: mottipazlazar ***@***.***>, Mention ***@***.***>
Subject: Re: [postmanlabs/postman-app-support] environment variable "current" value keeps being removed (Issue #11229)

@mottipazlazar<https://github.com/mottipazlazar> Can you confirm once if the variable apiKey is being used anywhere? (maybe on the collection level scripts)

If you can share the collection with this, we can debug into this further. You can share the same with us at ***@***.******@***.***>

**Comment by shubhbhargav** [comment]
I see. Is it possible for you to share the collection over email with us, to help debug this further? You can share it at help@postman.com.

**Comment by mottipazlazar** [comment]
Any update please?
Any workaround please?

we can have an online session if it helps.
thanks

From: מוטי פז לזר ***@***.***>
Date: Tuesday, 6 September 2022 at 6:26
To: postmanlabs/postman-app-support ***@***.***>, postmanlabs/postman-app-support ***@***.***>
Cc: Mention ***@***.***>
Subject: Re: [postmanlabs/postman-app-support] environment variable "current" value keeps being removed (Issue #11229)
Can’t share it from security reasons, sorry


Motti Lazar
________________________________

**Comment by mottipazlazar** [comment]
Hi,
Sorry for the trouble - my bad.
I had some leftover test script that removed this value.
Closing the issue

**Comment by mottipazlazar** [comment]
Can’t share it from security reasons, sorry


Motti Lazar
________________________________
