### ISSUE TITLE
Renaming any of the files in a connect repo and pulling them into Postman does some bad things

### ISSUE THREAD

**Issue by c0dezer019** [a85/POSTMan-Chrome-Extension#11223]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

If you rename the schema on local FS and pull it into Postman, it will register as DELETED and delete the Schema inside Postman, causing you to have to recreate the API. If you rename collections file, it will also register as DELETED and the next time you push from within Postman it will add a new collections file.

### Steps To Reproduce

1. Connect repo to Postman API.
2. Do initial pull.
3. Commit and push (can place anywhere in repo for this, doesn't matter where you place the schema and collections file)
4. Realize Darth Vader is your father.
5. Rename schema (or Collections...or both!) file out of panic.
6. Check for latest updates
7. Pull recent changes.

### Screenshots or Videos

I'd prefer not to do this again, it's a headache.

### Operating System

Windows

### Postman Version

9.30.0

### Postman Platform

Postman App

**Comment by shashankawasthi88** [comment]
@c0dezer019 can you retry this in the latest version of the app to see if the issue still exists? We have made a bunch of improvements in the product, this issue should not exist anymore. Let us know your findings.

**Comment by shashankawasthi88** [comment]
@c0dezer019 closing this for now, feel free to re-open if you still feel there are issues.
