### ISSUE TITLE
URL is deleted only in the request box but the URL is not getting clear in the  "Text box above the Request URL".

### ISSUE THREAD

**Issue by NisanthPaulin** [a85/POSTMan-Chrome-Extension#11228]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

URL is deleted only in the request box but the URL is not getting clear in the  "Text box above the Request URL".

### Steps To Reproduce

1. Open Postman
2. Enter the URL and select GET method 
3. Click Enter
4. The data will show in the Response tab
5. Now Clear the URL and Click enter
6. Data were showing in the response tab
 
Actual : The data was not cleared in the "Text box above the Request URL".
Expected: It should clear in the "Text box above the Request URL" too.

Note: Facing the bug occasionally, Not at everytime

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/112611918/187854431-4b4a5684-81bc-405e-aa95-bd33d0e168c3.png)

### Operating System

Windows10

### Postman Version

v9.29.0

### Postman Platform

Postman App

### Additional Context?

No

**Comment by DannyDainton** [comment]
Hey @NisanthPaulin 

The _URL_ that you can see at the top of the request is the `name` that you have given the request when it was saved. By default, this is prepopulated with the information from the URL.

You may have seen this data getting removed from the top of the request but this would only have been while the request was in an unsaved state (never been saved to a Collection) and removing it all would have shown `Untitled Request`.

This to me, appears to be working as expected so I'm going to close this for now.
