### ISSUE TITLE
GRPC Couldn't import .proto file There was an error while importing the Protobuf definition. import from multiple drives

### ISSUE THREAD

**Issue by Kolyamba-mamba** [a85/POSTMan-Chrome-Extension#11222]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

when loading .proto file containing:
syntax = "proto3";

import "to.proto";
import "facade_to.proto";
import "google/protobuf/timestamp.proto";

the error "Couldn't import .photofile" occurs There was an error while importing the Protobuf definition. import from multiple drives"

error - ![BiEp25t59zI](https://user-images.githubusercontent.com/36818700/187482596-33081aa0-6fbd-43b9-a366-2225c54d3346.jpg)
the directory used - ![kTmeU5WKuVM](https://user-images.githubusercontent.com/36818700/187482610-48df8946-77d2-4969-b443-83cbc996a24b.jpg)

### Steps To Reproduce

1. create several proto files so that one of them contains imports of others
2. create a postman grpc request
3. select the proto file that has the imports 
4. click next
5. observe the error

### Operating System

windows

### Postman Version

9.30.0

### Postman Platform

Postman App

**Comment by codenirvana** [comment]
This is fixed in the latest version of the Postman app.
