### ISSUE TITLE
Filter doesn't work in V3

### ISSUE THREAD

**Issue by mercibe** [a85/POSTMan-Chrome-Extension#1122]
The « Type to filter » box that allowed us to filter our API endpoints in V2 does not work anymore in V3. There seems to be something filtering but I cannot find any logic behind it.

Filter is a key piece for navigation in Postman and is now at the top left corner ou the UI. Great idea... if it could work like before...

Thank you very much in advance for bringing back the excellent V2 filter box.

**Comment by abhijitkane** [comment]
We made a few updates in the filter:
1. If a collection name matches your search term, all its children (folders+requests) remain visible.
2. If a folder name matches your search term, the requests in the folder will be shown, but not requests that are outside the folder.
3. If a request matches your search term, its parent folder and collection will be shown.

We'll be pushing this fix out soon.

**Comment by abhijitkane** [comment]
@mercibe Can you confirm this fixed in v3.0.4?

**Comment by mercibe** [comment]
Yes, it is fixed!  I forgot to mention it after I happily discovered it 
few days ago, sorry. The only difference with previous versions is that 
collections and folders containing filter matches stay closed if they 
are closed when applying filter. I think that the initial default 
behavior of always opening collections and folders when a least one of 
their children matches the filter is better from a usability point of view.

Thank you VERY much for your excellent tool and service!

Mercibe
