### ISSUE TITLE
The box of 'Existing collection' in 'Add request to a collection' is too small to select.

### ISSUE THREAD

**Issue by sungjun001** [a85/POSTMan-Chrome-Extension#1123]
The box of 'Existing collection' in 'Add request to a collection' is too small to select.

I want resize box or when mouse over show full name.
![add_collection_error](https://cloud.githubusercontent.com/assets/12808063/8050880/87603b74-0eaf-11e5-99fd-4e2281c436ca.JPG)

**Comment by vkaegis** [comment]
Hey @sungjun001, we've changed the input field for selecting a collection in our recent versions, could you check if this solves your problem?
