### ISSUE TITLE
Support pm.sendRequest in gRPC scripts.

### ISSUE THREAD

**Issue by olaforest** [a85/POSTMan-Chrome-Extension#11232]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

In HTTP requests pre-request script, it is possible to send http requests with `pm.sendRequest` to perform actions before the request (e.g. retrieve a fresh access token for authentication/authorization), but it seems like the function is not supported in gRPC `Before Invoke` request scripts (see below).

<img width="1177" alt="Screen Shot 2022-09-01 at 2 37 06 PM" src="https://user-images.githubusercontent.com/8661356/188017565-0d6d31f3-a25f-43b0-b892-19f4793793fa.png">

### Describe the solution you'd like

Support the function `pm.sendRequest` to send HTTP requests in gRPC scripts.

### Describe alternatives you've considered

Checked available [external libraries available in scripts in postman](https://learning.postman.com/labs/postman-api-client/grpc-client/writing-scripts/postman-sandbox-api/#using-external-libraries) to see if one of them supported HTTP requests, but couldn't find any that did.

**Comment by codenirvana** [comment]
@olaforest Thanks for the feature request, it’s already on our roadmap.

Can you please share more details about your workflow with `pm.sendRequest`?

**Comment by olaforest** [comment]
Our gRPC APIs require to send a JWT token in the metadata of each requests for authentication and authorization purposes. For security reasons, the TTL on the tokens is very small, hence, when developing those APIs, it's very cumbersome to keep having to generate new tokens and having to manually update them in Postman environment/global variable(s). I'm trying to create a pre-request/before invoke script in Postman to verify if the token is expired, and if so, automatically retrieve a new one and set it up in the variables accordingly, however, retrieving a new token involve making an http call to another service, which is where `pm.sendRequest` would come in handy.

I'm glad to see this feature is already on the Postman team's roadmap. Do you have a ballpark estimate on when this feature will be released?

Side question: In the available external libraries in script in Postman mentioned above, is there a libraries that facilitates processing Json Web Tokens (JWT)? I don't recall seeing one that does.

Thanks!

**Comment by olaforest** [comment]
Any news, or followup reply?

**Comment by olaforest** [comment]
@codenirvana @DannyDainton Any news on the above questions?

**Comment by codenirvana** [comment]
@olaforest Sorry for the delayed response. We’ll enable this by the end of this month. 🤞🏻

**Comment by appurva21** [comment]
Hey @olaforest! Support for `pm.sendRequest` in gRPC scripts is now available in the latest version of Postman 🎉 . Do give it a try and let us know your thoughts!

![send-http-request](https://user-images.githubusercontent.com/24985700/199671230-f7540d2c-abf4-4ea5-bb9d-c225dbe28e02.gif)

**Comment by olaforest** [comment]
@appurva21 @codenirvana This is awesome! Thanks you Postman team!
