### ISSUE TITLE
Uploading Files Error Due To File Path Being Added

### ISSUE THREAD

**Issue by Antonio-Bellifemine** [a85/POSTMan-Chrome-Extension#11230]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

I have a test that is uploading a document and has been working fine up until this morning. I tried to re-upload the file and re-do the query but the issue seems that the variable is undefined due to postman creating a new directory every time I upload a new file. 
---
![Screen Shot 2022-09-01 at 8 16 28 AM](https://user-images.githubusercontent.com/44248634/187911670-014fd745-716e-45d2-84d8-2cca5a0f4d24.png)
---
Here you will see the file path is as specified by postman in the settings
![Screen Shot 2022-09-01 at 8 17 03 AM](https://user-images.githubusercontent.com/44248634/187911758-6ede7928-4600-4cfa-b847-d65b6c2f70d4.png)
---
and here you will see after I select the file to upload it created a new directory separate from the default one postman is pointing to and causes undefined on my docum
<img width="775" alt="Screen Shot 2022-09-01 at 8 18 20 AM" src="https://user-images.githubusercontent.com/44248634/187912008-8b301993-85ba-4322-ab0e-f30a3fbab5af.png">
ent variable 

### Steps To Reproduce

Grapgh QL, not REST but not sure it makes a difference in this case
---
1. set up a test to upload a document
2. make sure the file is in the default postman repo
3. upload the file in the postman body form area
4. notice the file path postman adds a new directory leading to an error

### Operating System

Chrome 104 / Mac OS 10.15.7

### Postman Version

Version 9.30.1-220831-0502

### Postman Platform

Postman Web

### Additional Context?

This happend on web and platform

**Comment by Antonio-Bellifemine** [comment]
@DannyDainton Hi it's been quite some time since I opened this. I am ubnsure what the problem is. can you please update me? I have a whole suite of tests that rely on document uploads.

**Comment by ashuvyaspm45** [comment]
Hey, @Antonio-Bellifemine, sorry that you are facing this issue. Can you share your test script? So I can understand the flow. 
If you can share the screen recording that would be great.

**Comment by apoorvgupta03** [comment]
Hey @Antonio-Bellifemine , so sorry if you faced this issue. Can you please tell if this is still happening at your end? We tried uploading files from Postman-Web and its working fine for HTTP and GraphQL requests

**Comment by apoorvgupta03** [comment]
Hey @Antonio-Bellifemine, we are currently closing this but please feel free to reopen this ticket and help us reproduce this scenario by sharing resources like the test script or a screen recording.
Also you can try our latest GraphQL Client and let us know if the issue still happens.
