### ISSUE TITLE
Opening an existing request in a tab is consistently crashing

### ISSUE THREAD

**Issue by harryi3t** [a85/POSTMan-Chrome-Extension#11234]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

When I try to open any request in the tab it's always crashing. Also, I am seeing this error in the console `Maximum call stack size exceeded`

### Steps To Reproduce

Just try to open the request by clicking on it

### Screenshots or Videos

https://user-images.githubusercontent.com/5207331/188068366-8f72484f-9fd0-4094-b445-e56e690a334d.mov

### Operating System

Mac

### Postman Version

9.30.1-220831-0502

### Postman Platform

Postman Web

**Comment by giridharvc7** [comment]
@harryi3t Can you share the console logs?

**Comment by numaanashraf** [comment]
@harryi3t Could you also try temporarily disabling any Chrome Extensions like Jam (https://chrome.google.com/webstore/detail/jam/iohjgamcilhbgmhbnllfolmkmmekfmci) and let us know if that mitigates the issue?

**Comment by harryi3t** [comment]
Hey, I just tried restarting my browser and it worked.
I think I can close the ticket now. If it happens again, I can re-open with more details. 
Thanks!
