### ISSUE TITLE
Changelog shows PR merged, but does not show changes or link to PR

### ISSUE THREAD

**Issue by thoma01** [a85/POSTMan-Chrome-Extension#11231]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

When viewing the changelog for a collection, the entry for merging a forked collection PR back into the base collection does not have enough information.

```
Merged changes from <forked collection> to collection <base collection>
```

There is no list of changes to see what was changed in the merge, nor is there any link or reference to the pull request that got merged.

### Describe the solution you'd like

One of either;

- A list of the changes that were made in the pull request
- A link/reference to the pull request that was merged so the changes can be viewed there

**Comment by kartikjain26** [comment]
Thanks for the inputs @thoma01 . We are working towards enriching changelog. Will keep this updated.

**Comment by kartikjain26** [comment]
@thoma01 Details about Merged changes should be available now in Changelog if you expand the Merge log, which should show you a list of changes if you merge a Pull request or Merge changes directly.

We are working on including the pull request information too in Changelog.
