### ISSUE TITLE
Long workspace names are not shown completely while forking a collection.

### ISSUE THREAD

**Issue by Swapnil-getpostman** [a85/POSTMan-Chrome-Extension#11239]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

While forking a collection to the team or personal workspace, then the workspace which has long names is very difficult to select, and it becomes tough to differentiate the long workspace names. The current UI has half of the empty space, and workspace names are cut short.
Attaching the reference screenshot.

<img width="443" alt="workspace_visibility_screenshot" src="https://user-images.githubusercontent.com/52168965/188441946-80903f2b-5d61-47b2-a8dc-72b2fee9727c.png">

### Steps To Reproduce

As described in the screenshot attached.

### Operating System

macOS

### Postman Version

Version 9.28.3

### Postman Platform

Both

**Comment by kartikjain26** [comment]
@Swapnil-getpostman Hey this issue is fixed. Can you verify once.
