### ISSUE TITLE
Unable to load my postman, shows "Unable to load workspaces"

### ISSUE THREAD

**Issue by rmohan25** [a85/POSTMan-Chrome-Extension#11245]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Have been facing issues with loading my postman and their requests. shows "Unable to load workspaces" and I am unable to access any of the requests. This is blocking 

### Steps To Reproduce

Open postman and access workspaces. shows "Unable to load workspaces"

### Operating System

macOS

### Postman Version

9.30.4

### Postman Platform

Postman App

**Comment by numaanashraf** [comment]
@rmohan25 Could you restart your app and let us know if you are still facing this issue? We had an outage yesterday which has been resolved since - https://status.postman.com/incidents/v7mpllv9782s

**Comment by rmohan25** [comment]
Multiple restarts are done. No use
________________________________

**Comment by DannyDainton** [comment]
Hey @rmohan25 

Are you still facing this issue?

**Comment by akshay-kulkarni-03** [comment]
Hey @rmohan25 as mentioned above there was an intermittent issue due to which workspaces were not loading up. This should no longer be happening. Feel free to re-open if you face any issue.

**Comment by ArmanKoke** [comment]
Hi all, have same issue on debian 12, Postman v10.12.13, no proxy no vpn, not loads from today

**Comment by ariypriy** [comment]
I had the same issue, try logging out of the local app and then signing back in again - this seemed to fix it for me. My authentication was via "sign in with Google", at a guess I imagine the authentication token had expired.

**Comment by TimothyGCY** [comment]
Me as a Windows user, resolved this by

1. Close Postman
2. `Win` + `R`
3. Key in `%AppData%`
4. Delete folder `Postman`
5. Relaunch Postman
6. Login to existing account

**Comment by soutong** [comment]
https://github.com/postmanlabs/postman-app-support/issues/11245#issuecomment-1630672606
thanks,solve my problm

**Comment by olenahuk** [comment]
Having same issue currently, suggestion above didn't help unfortunately.

What already tried:
Reboot.
Reinstall completely.
Relogin.
Load all I need on browser version but it complains there is no app running.

It works perfectly fine couple of days ago.

**Comment by BilalSaeedAlam** [comment]
It sometimes happened due to internal services, team of Postman aware of these things and fix the issue ASAP. For such kind of issues we can check community.
https://community.postman.com/

**Comment by ced1check** [comment]
Having this issue now, can't use postman at all :(

**Comment by BilalSaeedAlam** [comment]
> Having this issue now, can't use postman at all :(

![image](https://github.com/user-attachments/assets/74c26395-0423-48e8-a7a9-86717a452b96)

**Comment by BilalSaeedAlam** [comment]
@ced1check you can use Thunderclient till then. Untill service is back.

**Comment by ced1check** [comment]
Seems to be back on :D

**Comment by BilalSaeedAlam** [comment]
Yes, service is back @ced1check

**Comment by linnminhtet23** [comment]
<img width="1512" alt="Screenshot 2024-09-11 at 9 46 02 PM" src="https://github.com/user-attachments/assets/c7d48a09-7baa-4f13-84dc-f791519edfd9">

I'm facing this kinda issue. I cannot enter into the postman collection. Restart also not working.

**Comment by vijayants** [comment]
> <img alt="Screenshot 2024-09-11 at 9 46 02 PM" width="1512" src="https://private-user-images.githubusercontent.com/50839019/366519125-c7d48a09-7baa-4f13-84dc-f791519edfd9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxMDc2NjcsIm5iZiI6MTcyNjEwNzM2NywicGF0aCI6Ii81MDgzOTAxOS8zNjY1MTkxMjUtYzdkNDhhMDktN2JhYS00ZjEzLTg0ZGMtZjc5MTUxOWVkZmQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEyVDAyMTYwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM3ZThjMzA0YjAxZDYyMDQ4N2Q3ZWZhYWYyNDYxMWY4NTdkNTM1ZDYyNDkyMTM5YWQ3MTIzNjgzNzQ5YTM0MzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.A5oayL00Lr8FEhl6IApCVg9AfWDPMfgaovsLjjZsWhc">
> I'm facing this kinda issue. I cannot enter into the postman collection. Restart also not working.

@linnminhtet23, is it still happening? Can you provide your env. details (e.g. OS, processor, RAM, app version etc.)?

**Comment by sony-mathew** [comment]
Hey @linnminhtet23 
Thank you for reporting the issue. To help us investigate further, could you please confirm whether the issue persists across both the web app (https://identity.getpostman.com/login) and the desktop app? Additionally, could you please provide the version and OS details of your desktop app that @vijayants has already asked for? This information will help us better understand the issue and provide a more accurate solution. Also, I noticed that the screenshot you attached shows an 'Error' message instead of 'Online' in the bottom left corner. 

<img width="377" alt="Screenshot 2024-09-13 at 9 07 16 AM" src="https://github.com/user-attachments/assets/ea4f91cd-e9f3-475f-976d-44f875af079d">

**Comment by liuyaox** [comment]
sign out, then setting -> general -> turn off "SSL certificate verification", and then sign in again.

It works for me
