### ISSUE TITLE
Collection name in 'Collections' is too small to select.

### ISSUE THREAD

**Issue by sungjun001** [a85/POSTMan-Chrome-Extension#1124]
Collection name in 'Collections' is too small to select.

There is a limit to increase the maximum. 
I want no maximum to increase.

![collection_list_error](https://cloud.githubusercontent.com/assets/12808063/8050924/426a0d00-0eb0-11e5-9691-d6f3e2d08e44.JPG)

**Comment by aditikul** [comment]
@sungjun001 Closing this since it should be fixed in the latest app. Let me know if otherwise, thanks.
