### ISSUE TITLE
Parse response from websocket request and save into variable

### ISSUE THREAD

**Issue by guyver30** [a85/POSTMan-Chrome-Extension#11249]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

no

### Describe the solution you'd like

Sometimes it's necessary to save part of a json response of a websocket into a variable, to be used for other websocket requests (ex session_id)

### Describe alternatives you've considered

no alternatives

**Comment by appurva21** [comment]
Hey @guyver30! We will enable this via scripts in websocket request. You can follow #10181 for further updates on this.
