### ISSUE TITLE
gRPC request does not use metadata field x-filter-fields=false

### ISSUE THREAD

**Issue by uschwag** [a85/POSTMan-Chrome-Extension#11240]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Since updating from v9.30.1. to v9.30.3 I recognize that metadata field x-filter-fields=false anymore.
It works with gRPCUI and I can still request all fields by explicitly referencing them.

### Steps To Reproduce

1. Any gRPC request
2. set metadata in request to x-filter-fields=false
3. send request  should response all fields and not only those requested explicitly

### Operating System

Windows 10

### Postman Version

9.30.3

### Postman Platform

Postman App

**Comment by codenirvana** [comment]
@uschwag Can you share an endpoint that we can use to reproduce this issue? Or, share the screen recording demonstrating the issue.

**Comment by uschwag** [comment]
No, I can't share an endpoint due to security and to share a screen recording does not show something because now the data isn't coming back and I can't reach older versions. Is it possible to see in logs what metadata is exactly send?

**Comment by codenirvana** [comment]
@uschwag I used an echo endpoint, and the metadata is sent correctly.

![Screenshot 2022-09-06 at 1 13 14 PM](https://user-images.githubusercontent.com/4865836/188576381-9bb90e4a-c266-48ad-ab32-31d9b5f10aa3.png)

Also, there's no change in the gRPC request sending flow in v9.30.
Can you check if this behavior change is on the server side?

**Comment by uschwag** [comment]
@codenirvana, it could indeed be also a server change but using GRPCUI as client still works. Need to do further investigation.

**Comment by uschwag** [comment]
It was a mixture of missing data and my fault not to know that Postman strictly doesn't emit default values. 
I would therefore highly support #11233. 
1. This would make Postman more comparable to other tools.
2. A common test case can also be handled better, "show me all fields where the server does not provide any data".
