### ISSUE TITLE
after opening a tab in a new window the first window's tabs are empty

### ISSUE THREAD

**Issue by stevegroom** [a85/POSTMan-Chrome-Extension#11254]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

I wanted to have a side-by-side comparison of two tabs. So I was happy to find there is multiple window support. The second window opened ok, the first window was not changed until I opened a new tab in the second window. Then my GraphQL query in the first window disappeared. 

### Steps To Reproduce

**1 Open postman**
<img width="1680" alt="Pasted Graphic" src="https://user-images.githubusercontent.com/2097486/189472372-59430f0d-de9e-4f72-92b4-f1f8e75df857.png">

open tabs were restored - I'm running some GraphQL tests

**2 Open new window**
<img width="459" alt="Postman File Edit View Window Help" src="https://user-images.githubusercontent.com/2097486/189472397-3d1713ec-532c-480f-b25c-84e5c675efbd.png">

**3 second window opens** 
<img width="1680" alt="Pasted Graphic 2" src="https://user-images.githubusercontent.com/2097486/189472400-fde47993-9933-44cf-a7d7-39299a417a00.png">

no environment selected yet

**4 Open workspace** 
<img width="483" alt="Postman File Edit View Window Help" src="https://user-images.githubusercontent.com/2097486/189472428-7f233e1a-eb32-48fb-97fd-9f49e36f791e.png">

This is the same workspace as window 1

**5 Open a tab in window 2**
<img width="360" alt="Respons" src="https://user-images.githubusercontent.com/2097486/189472473-77a17e30-f42e-4d28-9c24-ae385407baab.png">

**6 New tab opens in window 2**
<img width="1680" alt="Pasted Graphic 5" src="https://user-images.githubusercontent.com/2097486/189472483-b4e199f5-0509-4d3f-ba23-a2bf65b470a9.png">

**7 Tab in window 1 now empty**
<img width="1680" alt="Pasted Graphic 6" src="https://user-images.githubusercontent.com/2097486/189472491-3802ed37-7fb7-47a5-b5f1-f3c95b8a725f.png">

**8 Reopening tab in window 1 does not help** 

### Operating System

MacOS

### Postman Version

9.31.3

### Postman Platform

Postman App

**Comment by apoorvgupta03** [comment]
Hey @stevegroom , can you please confirm if you are still facing this issue?
Can you please try updating the app and try once again?

**Comment by stevegroom** [comment]
I am sorry, but I do not have any developments to test against - currently assigned non dev work.

**Comment by apoorvgupta03** [comment]
We tested this on our end and it's working fine now, closing this ticket. 
Please feel free to report any such findings in the future.
