### ISSUE TITLE
Cannot load workspaces for corporate (paid) client in AWS WorkSpaces; but dedicated PC works fine

### ISSUE THREAD

**Issue by FuadEfendi** [a85/POSTMan-Chrome-Extension#11253]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Using corporate account (licensed to 50 users), this URL doesn't load:
https://ABC-Foo.postman.co/workspaces

At the same time, my personal workspace loads fine:
https://XYZ-Bar.postman.co/workspaces

Other team members with AWS Workspace also have the same issue. I initially suspected licensing issue, but after killing all active sessions, the issue still exists. Also, there is specific account which many users use concurrently. Users with dedicated PC/Mac don't have any issues, but users with Amazon WorkSpaces have.

I suspect Firewall / IP tables; but note it works for my personal "XYZ-Bar". It also can't be licensing issue because users with dedicated workstations don't have any issue.

From Chrome Console, I can see this this connection fails:
https://clientstream.launchdarkly.com/eval/xxxxxxxxx
- no response

Perhaps it is failure at AWS settings?

### Steps To Reproduce

Using corporate account (licensed to 50 users), this URL doesn't load:
https://ABC-Foo.postman.co/workspaces

At the same time, my personal workspace loads fine:
https://XYZ-Bar.postman.co/workspaces

Using Amazon WorkSpaces: fails

Dedicated PC: works fine

### Operating System

Amazon WorkSpace Windows Server 2016 Datacenter

### Postman Version

9.14.0

### Postman Platform

Both

### Additional Context?

The same issue with Web and App

Simple test: https://ABC-Foo.postman.co/workspaces fails to load

**Comment by postman-staff** [comment]
Hi @FuadEfendi
Thank you for reaching out.

I understand that accessing both team workspace and personal workspace under VDI and PC fails loading, Is that right?

Could you please help me with the exact error message that you see while accessing your workspace in the VDI Amazon WorkSpace(cloud-based virtual desktop)?
Screenshots would be great!

Do you have any type of VPN or proxy in use that could impede a connection to Postman? If so can you disable them or try switching to another network as a test to see if that affects anything?

Let us know if you have any further queries - happy to help!
via @Lincimary | Postman Support

**Comment by jon-dobisch** [comment]
@FuadEfendi @postman-support Having the same issue. Was there a fix for this?

**Comment by FuadEfendi** [comment]
It was some "bad weather" at Amazon.

I asked @postman-support  explicitly this question:
```
From Chrome Console, I can see this this connection fails:
https://clientstream.launchdarkly.com/eval/xxxxxxxxx
```

But they ask me to make publicly available screenshots of our corporate Postman instance. Right now it magically works for me but it doesn't work for some other team members, I assume they use different Amazon datacenters. Most team members use Amazon WorkSpaces; those having dedicated laptops do not have such issues.

**Comment by postman-staff** [comment]
Hi hello,

May I know if you are behind a captive-based web gateway authentication mechanism? You may refer to this link here to know more about this.

If yes then could you please give our Canary build a try and let us know if that helped: https://postman.com/downloads/canary

On the Canary app, Click on Help -> Setup Web Gateway Support and proceed with authenticating your proxy -> Check if the connection has been established.

 Looking forward to your response!

via @Lincimary | Postman Support

**Comment by jon-dobisch** [comment]
@postman-support For this issue, if I was looking to whitelist the Postman desktop app so that Workspaces isn't blocked by our corporate proxy, what is the **base URL** that I would need to **whitelist**?

**Comment by postman-staff** [comment]
Hi hello,
Thank you for following up.

If the connection is blocked due to a firewall/proxy then please whitelist the following domains on your network firewall to allow WebSocket connections for Postman

*.getpostman.com
*.postman.co
*.pstmn.io
*postman.com

By default webSocket connections use the same ports as HTTP (80) and HTTPS (443).

Let us know if you have any further queries - happy to help!
via @Lincimary | Postman Support
