### ISSUE TITLE
Runner file upload filters by default on .json files

### ISSUE THREAD

**Issue by WykhoW** [a85/POSTMan-Chrome-Extension#11251]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Couldn't find the .csv file I wanted to upload in postman runner.

Took me a moment, as I was only seeing many folders listed, to figure out there was a file-type filter applied with value "`Custom files (*.json)`" at the bottom right of the window (Windows 11).

Now I got it ... but find it very painful having to move the mouse to the opposite from where I should select the file and have to do two clicks to switch json to CSV, while I never used json format to do batch processing (mostly inputing data from XL files or DB extracts).

Can you please remove this filter (leave "All" file type by default), or add more (if Windows allows this) such as csv,txt ... ?

### Steps To Reproduce

1. Right click on collection folder
2. Select "Run folder"
3. Click "Select File"
4. See windows explorer listing folders in default "Download" folder, with json file type filter applied by default

### Screenshots or Videos

![2022-09-09 13_23_04-Postman](https://user-images.githubusercontent.com/98850003/189342843-f1bc6005-b1ff-41e7-83e6-30917729e206.png)

### Operating System

Windows 11

### Postman Version

v9.31.0

### Postman Platform

Postman App

**Comment by JuliaGNH** [comment]
Is there a solution to this as find very cumbersome to change to all files as I use .csv's

**Comment by malvikach** [comment]
@WykhoW @JuliaGNH 👋  

thanks for sharing the feedback. 

You can update your Postman app version to the latest version (10.18) and let us know if you still face this issue. 

We verified that the issue does not exist on the latest app version for Windows and MAC platforms. 

Looking forward to hearing from you.

**Comment by malvikach** [comment]
Feel free to reopen if you still face the issue. 

Cheers!
Malvika
