### ISSUE TITLE
Typo in console

### ISSUE THREAD

**Issue by ihsan6133** [a85/POSTMan-Chrome-Extension#11256]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

If response body is more than 10kb, the message shown is "The console only response bodies smaller than 10 KB inline. To view...",
It should be The console only **shows** response bodies..."

### Steps To Reproduce

1. Open a new request tab
2. Send a normal get request to www.youtube.com
3. Inspect the console, 
4. click raw log

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/69343917/189594537-839bef53-6686-4347-a4f5-9f8d93d26b43.png)

### Operating System

Windows

### Postman Version

9.14.0

### Postman Platform

Postman App

**Comment by giridharvc7** [comment]
This is now fixed, please update to the latest app version (v10.x) to view these changes!
