### ISSUE TITLE
Export "Mock Server Call Log" as JSON

### ISSUE THREAD

**Issue by patricksouth** [a85/POSTMan-Chrome-Extension#11250]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

Select one or more entries that appear in the "Mock Server Call Log" and export as JSON to file. 

![image](https://user-images.githubusercontent.com/10768324/189248179-96d94cd9-e2a0-47cf-8971-6a5911807708.png)

the problem, is that I can't export entries in the "Mock Server Call Log". Expanding individual log entries, copying and pasting isn't an alternative.

### Describe the solution you'd like

1. The ability to select the log type (from Request Headers, Request Body, Response Headers, Response Body). 
2. Then select individual (or all) log entries in the "Mock Server Call Log".
3. Export selected log entries & type to a file in one of several formats.

Suggested formats: JSON, XML, RAW, text

### Describe alternatives you've considered

there is no alternate solution within Postman.

**Comment by Dhembla** [comment]
Hey @patricksouth, You can use [Call logs API ](https://www.postman.com/postman/workspace/postman-public-workspace/request/12959542-f25efa16-1813-4279-8a89-a94ba968533e) to get the desired data. Please give it a try and see if it solves your use case.
Thanks 🙇

**Comment by mike-mccormick** [comment]
Hey @Dhembla, I'm facing the same issue, and the response from the `call-logs` endpoint doesn't contain the headers, or body from the request that was made to the mock server. 

![image](https://user-images.githubusercontent.com/2361501/212360909-d40da86e-b17e-4f93-b4e2-768d2c39a0d8.png)

In addition to the OP's query, there's also another three comments on the [postman.com call logs feature announcement blog post](  https://blog.postman.com/introducing-postman-mock-call-logs/)  asking for the same thing.

**Comment by Dhembla** [comment]
@mike-mccormick You can send an additional `include` param while fetching the call logs. This query parameter accepts the "request.headers", "request.body", "response.headers", and "response.body" as values. You can refer [this](https://www.postman.com/postman/workspace/postman-public-workspace/example/12959542-66d6e32e-a5bb-4dae-8a0b-db98b6d5f399) example to learn how to use it.
Please try it out and let me know if you face any issue. 🙇

**Comment by sony-mathew** [comment]
Hey @patricksouth and @mike-mccormick , I believe that our documentation and the new capabilities should help address your concerns and provide a better experience for you. 

> You can send an additional include param while fetching the call logs. This query parameter accepts the "request.headers", "request.body", "response.headers", and "response.body" as values. You can refer [this](https://www.postman.com/postman/workspace/postman-public-workspace/example/12959542-66d6e32e-a5bb-4dae-8a0b-db98b6d5f399) example to learn how to use it.


This should help resolve your current issue. If there's anything else we can do to assist you, please let us know. If you have any further questions or concerns, please feel to reopen this ticket.
