### ISSUE TITLE
Need markdown table syntax support.

### ISSUE THREAD

**Issue by liaosankai** [a85/POSTMan-Chrome-Extension#1125]
![2015-06-09_134428](https://cloud.githubusercontent.com/assets/82476/8051344/efd915d8-0ead-11e5-8345-abcb6778c943.jpg)

Result:

![2015-06-09_134555](https://cloud.githubusercontent.com/assets/82476/8051346/f43bee3e-0ead-11e5-8ec4-6ad4ffa4c580.jpg)

**Comment by a85** [comment]
@abhijitkane This should happen automatically through the markdown renderer right?

**Comment by abhijitkane** [comment]
Should, but doesn't

**Comment by mm-gmbd** [comment]
I'm guessing this is because Markdown tables aren't actually native to markdown, but are a part of [Github Flavored Markdown](https://help.github.com/articles/github-flavored-markdown/#tables). Still would really like support for this.

**Comment by deldrid1** [comment]
+1 for Github Flavored Markdown.  By using a modern renderer this should come for free...

**Comment by numaanashraf** [comment]
@liaosankai @mm-gmbd @deldrid1 GFM support has been added in version 4.0+, which fixes this issue.
