### ISSUE TITLE
SOAP API doesn't create collection on POSTMAN but works on SOAPUI

### ISSUE THREAD

**Issue by Sanjay500-500** [a85/POSTMan-Chrome-Extension#11267]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Hi I am trying to create collection for this particular wsdl file- https://service4.ultipro.com/services/BiStreamingService? . But the file works fine on SOAPUI. Can anyone explain what I am doing wrong here?

### Steps To Reproduce

1. Import
2. Add Link
3. Hit Import - Creation fails

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/93577222/190063494-361165bb-216d-4ee1-bd2a-7f9542251ff6.png)

### Operating System

Windows 10

### Postman Version

 9.31.5

### Postman Platform

Postman App

**Comment by hrhv** [comment]
Hi @Sanjay500-500, firstly - thank you so much for raising this issue to us and helping us make Postman better for you and other developers.

We appreciate your patience and help. Would like to share that we have released a fix for this and it should now ideally work for you! 🙇🏻 (Attaching a screen recording for the same)

https://user-images.githubusercontent.com/52413945/211011572-3e35c87d-5d31-4e91-afa0-4aac39090fa3.mov

On a slightly different note, I see you were on Postman v9. If you haven't already, do try out Postman v10 ([announcement here](https://blog.postman.com/announcing-postman-v10/)) for a whole new experience in your API journey 🎉

In case you still face an issue importing, please feel free to open an issue / re-open this.
