### ISSUE TITLE
Postman 9.18.3 how to enable disable the TLS for grpc requests

### ISSUE THREAD

**Issue by fabsdevops** [a85/POSTMan-Chrome-Extension#11260]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

How can I enable /disable TLS for  URL requests

### Steps To Reproduce

1 . No lock button to enable or disable tls for postman grpc beta requests

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/72412777/189751511-51d1ff36-b2a7-4469-a6cf-c187a6c62f88.png)

### Operating System

windows

### Postman Version

9.18.3

### Postman Platform

Postman App

### Additional Context?

nothing

**Comment by appurva21** [comment]
Hey @fabsdevops ! Can you update your Postman app to the latest version and try again? You should see the TLS toggle adjacent to the URL input. You can also head over to our [Learning Center](https://learning.postman.com/labs/postman-api-client/grpc-client/grpc-request-interface/#tls-toggle) to know more about working with TLS in gRPC request.

**Comment by appurva21** [comment]
@fabsdevops, I am closing this issue since we haven't heard back from you. Feel free to re-open if you are still facing the issue.
