### ISSUE TITLE
New Relic integrations failed to configure Monitor API performance

### ISSUE THREAD

**Issue by thefishermanhacker** [a85/POSTMan-Chrome-Extension#11261]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Postman offers two ways to configure the New Relic integrations:
1. Monitor API performance.
2. Post monitoring results.

The integration located below:
https://<YOUR_SUBDOMIN>.postman.co/integrations/service/apm_new_relic

I tried to configured option 2 - _Post monitoring results - Send your monitor run metrics to New Relic_
The attempt was failed because in the backend the request doesn't contains _Api-Key_ as mentioned in New Relic documentations. https://docs.newrelic.com/docs/apis/graphql-api/getting-started/introduction-new-relic-graphql-api#authentication

Therefore an error will be throw from New Relic and the configuration will be failed.

`{"error":{"title":"Error encountered at New Relic","message":"Something went wrong at New Relic.","name":"newRelicError","statusCode":403,"details":{"errors":[{"message":"Please provide an API key via the `Api-Key` header.\nhttps://docs.newrelic.com/docs/apis/graphql-api/getting-started/introduction-new-relic-graphql-api#authentication\n"}]}}`

### Steps To Reproduce

1. Open your account on postman.co.
2. Go to https://<YOUR_SUBDOMAIN>.postman.co/integrations/service/apm_new_relic.
3. Chose the first option _Monitor API performance_.
4. Open your devtool on chrome and click on the Network tab.
5. Fill in the form and click _Authenticate and Proceed_.
6. Check the response and you'll see 
`{"error":{"title":"Error encountered at New Relic","message":"Something went wrong at New Relic.","name":"newRelicError","statusCode":403,"details":{"errors":[{"message":"Please provide an API key via the `Api-Key` header.\nhttps://docs.newrelic.com/docs/apis/graphql-api/getting-started/introduction-new-relic-graphql-api#authentication\n"}]}}`

### Screenshots or Videos

<img width="1900" alt="Screen Shot 2022-09-13 at 12 19 29" src="https://user-images.githubusercontent.com/3106554/189863622-e1f80332-67a8-4d08-af32-2b977d6cb600.png">

### Operating System

macOS

### Postman Version

9.31.6-220912-1309

### Postman Platform

Both

**Comment by shashankawasthi88** [comment]
@thefishermanhacker can you ensure that you put the User-API-key and not the INGEST-LICENSE key in the 'Monitor API performance - https://docs.newrelic.com/docs/apis/intro-apis/new-relic-api-keys#user-key
In the 'Post monitor result' form, we need the INGEST-LICENSE key.

**Comment by thefishermanhacker** [comment]
@shashankawasthi88 with User-API-key it worked.
I guess the only bug here is in the UI which should notify/alert that it needs the User-API-key and not the INGEST-LICENSE.

**Comment by shashankawasthi88** [comment]
Agreed, well update the UI. Closing this for now. Thanks
