### ISSUE TITLE
Postman API - Schema Security Validation: 5xx response codes

### ISSUE THREAD

**Issue by maticardenas** [a85/POSTMan-Chrome-Extension#11269]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

When trying out the Schema Security Validation API (https://api.getpostman.com/security/api-validation) for an OAS file, I see that I get multiple warnings with: 

```
"message": "Operation should return a 5xx HTTP status code"
```

This currently is thrown for almost all of our OAS as we don't return 5xx response codes, because we consider we're just exposing unhandled behavior. Additionally, neither `spectral` nor `redocly`, widely used tools that we've tried out see as an error/warning not having `5xx` responses (they do for `4xx`, which makes sense).
This validation is also in the [learning center](https://learning.postman.com/docs/api-governance/api-definition/openapi3/#get-operations-should-have-a-500-status-code-for-the-response), perhaps it is a good idea to evaluate if it's correct to leave these warnings or add a corresponding explanation why is it suggested to make explicit `5xx` responses as there seem to not many positive reasons.

### Steps To Reproduce

1. Perform a `POST` request to `https://api.getpostman.com/security/api-validation` for a specified OAS schema, which is missing `5xx` response codes in one or more of its requests.
2. One or multiple warnings will be returned, including following message:

```
 "message": "Operation should return a 5xx HTTP status code"
```

### Operating System

macOS

### Postman Version

9.30.1

### Postman Platform

Postman App

**Comment by davidespihernandez** [comment]
Thanks for taking the time to write this!
In this case, the Postman API uses the configured security rules. Enterprise plans can [configure the API security rules](https://learning.postman.com/docs/api-governance/configurable-rules/configuring-api-security-rules/). Other plans can't do that, and use the default rules.
