### ISSUE TITLE
Feature Request: Double click on saved Request to execute

### ISSUE THREAD

**Issue by KotieSmit** [a85/POSTMan-Chrome-Extension#1126]
It would be nice to have the ability to double click on a request and have it to execute immediately.

**Comment by a85** [comment]
@KotieSmit Thanks for the suggestion. We are cleaning up UI actions for a major update. We'll see if this can be implemented.

**Comment by aditikul** [comment]
@KotieSmit Currently we have a shortcut to execute a request immediately. You can press Enter to send the request if you are in the URL field. However if you are somewhere else in the UI you can Cmd/Ctrl+Enter to immediately send the request. Closing this since it helps solve your issue.
