### ISSUE TITLE
Single backtick code block text is kinda smaller than its normal counterparts

### ISSUE THREAD

**Issue by yadunandanbhat** [a85/POSTMan-Chrome-Extension#11277]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

See the below image for an example. And no my zoom size is 100%, so there is no zoom issue.
I think the single backtick code block's text size should be increased in ratio to be on the same level as the regular text.

### Steps To Reproduce

1. Open documentation
2. Select Postman Editor
3. Write some code inside the "` `" code block
4. Check the size difference

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/54680617/190621200-78e53450-491c-4dea-99fe-6f196a35c03f.png)

### Operating System

Windows

### Postman Version

9.31.6

### Postman Platform

Postman App

**Comment by kamaraj-p** [comment]
Hi @yadunandanbhat, thanks for feedback. The issue is now fixed.
