### ISSUE TITLE
Visualize result tab freezed after switch to another window

### ISSUE THREAD

**Issue by SoiTrang** [a85/POSTMan-Chrome-Extension#11275]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Visualize result tab freezed after switch to another window and switch back, cannot interact with data, scrollbar stuck, ...

### Steps To Reproduce

1. Make a request with visualizer script enabled.
2. After receive response, switch to Visualize tab in the Body tab of Response pane. The visualize result will display as expected.
3. Switch to another window (app).
4. Switch back to Postman app.
5. The Visualize tab is freezed, cannot interact with data, scrollbar stuck, ...
6. Switch to any of other tabs of Postman and switch back to Visualize tab, and it works again.

### Operating System

Windows 10 21H2

### Postman Version

9.31.6

### Postman Platform

Postman App

**Comment by dev-sharma-08** [comment]
@SoiTrang  sorry that you are facing this issue. However, I am unable to replicate this on my side. Can you confirm that this issue is still reproducible in the latest version of the app?

**Comment by SoiTrang** [comment]
@dev-sharma-08 
Now I've upgrade to Windows 11, and with the latest Postman version, this bug is not occur again, thanks for your reply.
