### ISSUE TITLE
comparing response body with my Database data in postman

### ISSUE THREAD

**Issue by Abhinay12** [a85/POSTMan-Chrome-Extension#1127]
i got my response body after sending request from api and now i want to compare my response body with my database ..........
 can u plz give me proper solution for this.....................

**Comment by johnnavarra** [comment]
parse the response and output to the console.

**Comment by Abhinay12** [comment]
Sir can u send me one screenshot

**Comment by johnnavarra** [comment]
Well i'm not sure how what you're expecting for an output

but you can use this as a basic guideline for a test:
assuming your output is in json:

//parse the response body and set to a variable
var response = JSON.parse(responseBody);

//set a variable from the outpyt
var Job_ID = response.Body.JobItem.JobID;

//output to console
console.log(Job_ID);

then compare that output to your database value.

Conversely, if you have access to the collection runner, you can make a data driven test where the data is an output from the database and perform a test comparing the two.

That test can be output to the console.log and then exported as a csv.
