### ISSUE TITLE
Auto detect theme

### ISSUE THREAD

**Issue by milad-kamali** [a85/POSTMan-Chrome-Extension#11272]
### Is there an existing request for this feature?

- [x] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

No

### Describe the solution you'd like

Please add auto detect theme feature to postman to change theme according to windows theme.

**Comment by DannyDainton** [comment]
Duplicate of https://github.com/postmanlabs/postman-app-support/issues/5817
