### ISSUE TITLE
Gentle suggestion: consider switching from Electron to Tauri

### ISSUE THREAD

**Issue by tgross35** [a85/POSTMan-Chrome-Extension#11274]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

The Postman application is quite large. It's not the end of the world, but ~500 MB is still quite a lot for a mostly frontend app, and a fair chunk of that size comes from Electron

### Describe the solution you'd like

Take a look at Tauri ([repo link](https://github.com/tauri-apps/tauri)) which is a more or less drop-in replacement for electron. The tl;dr is that it uses the system's webview/webkit instead of shipping the entire browser engine with each executable. It may not work in Postman's case, but is at least worth taking a glance at.

**Comment by jviotti** [comment]
Hi @tgross35 ,

Thanks for the suggestion! I do feel your pain and we have indeed experimented with alternatives :)

Tauri looks great, but the main deal breaker here is that the process orchestrating the web views has to be written in Rust. As you might imagine, the corresponding JavaScript-based Electron main process implementation we have at Postman right now is pretty large, and would be very non-trivial to port it all to Rust.

We work closely with Electron (Postman has a bunch of people representing the company on its governance) to try to make things better. That said, we are actually experimenting with native web views on the side to get a better sense of how that would compare to Electron's embedded Chromium in Postman itself.

Hopefully we will have some cool stuff to show at some point, so stay tuned! :)

**Comment by tgross35** [comment]
Understood, thank you for the detailed follow up!
