### ISSUE TITLE
All requests are shown as `GET` in the collection tree view

### ISSUE THREAD

**Issue by OldrichDlouhy** [a85/POSTMan-Chrome-Extension#11286]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

In the workspace, collection tree view, all requests are shown as `GET` requests even when the requests use other method, e.g. `POST`. The correct method is displayed only after the mouse click

### Steps To Reproduce

1. Open Postman with workspace
2. Open collection
3. Open folder in the tree view
4. Notice all requests are marked as `GET`

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/8403048/191419743-3a1e8a46-bcb9-44f9-aded-adafaa61e451.png)
![image](https://user-images.githubusercontent.com/8403048/191419863-59a82e66-bc60-437a-8bfc-16f7fd4a37cb.png)

### Operating System

Windows

### Postman Version

9.31.9

### Postman Platform

Postman App

### Additional Context?

Postman for Windows

Version 9.31.9
UI Version 9.31.9-ui-220920-1616
Desktop Platform Version 9.31.0
Architecture x64
OS Platform win32 10.0.18363

**Comment by giridharvc7** [comment]
Appreciate reaching out here @OldrichDlouhy. This looks like a bug, we'll look into this and get back to you soon.

**Comment by parthverma1** [comment]
@OldrichDlouhy I tried reproducing the error but was unsuccessful. Can you share a screen recording showcasing this behavior or detailed steps to reproduce the conditions which resulted in the error?

**Comment by OldrichDlouhy** [comment]
@parthverma1 - For reproduction steps, I simply start the Postman, go to the collection, wait till it loads and then the issue manifests.

Few notes though:
 - it does not happen in scratch pad
 - often the collection is shown empty or some subfolders are missing and shows only after a while, so I suspect the behavior to be related to download/caching of data from servers

https://user-images.githubusercontent.com/8403048/192228172-eb267495-7ada-4a2c-a3e2-bed59f5a84f0.mp4

**Comment by apoorvgupta03** [comment]
Hey @OldrichDlouhy, can you please check if this issue still persists? 
You can also update the app for better UX improvements.

**Comment by OldrichDlouhy** [comment]
Hello,

I did not saw the issue for some time. 

For what it is worth, this is Postman version I use at the moment:
Postman for Windows
Version 10.14.8
UI Version 10.14.8-ui-230602-2200
Desktop Platform Version 10.14.2
Architecture x64
OS Platform win32 10.0.19044

**Comment by sony-mathew** [comment]
Hey @OldrichDlouhy 

We hope this resolves your issue. If you have any further concerns or questions, please feel free to reopen this discussion. We're here to help and support you.
