### ISSUE TITLE
Bullet list does not work at all in postman editor 

### ISSUE THREAD

**Issue by vmouse** [a85/POSTMan-Chrome-Extension#11285]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

It is impossible to use bullet lists in the documentation editor.

### Steps To Reproduce

1. Open any published Collection (with public access from Internet)
2. Click an existing request
3. Click Documentation  icon on the right side to open Documentation tab
4. Start editing of the request documentation
5. Click "Unordered list" icon on the editor toolbar
6. Create a several list items (create several items on sublevels)
7. Click Save
8. Open the documentation URL in Chrome browser. Look at completely destroyed list (no bullets, no line feeds)

### Operating System

macOS

### Postman Version

9.31.9

### Postman Platform

Postman App

**Comment by dudikrisher** [comment]
Same happen to me, this is really annoying as the default editor for documentation is  "Postman Editor":
![image](https://user-images.githubusercontent.com/879781/193564957-6302d800-c755-466f-8e25-cee06b8c9580.png)

and when switching to "Markdown Editor" the bullet list is already corrupted. 

steps:
1. create unordered list
![image](https://user-images.githubusercontent.com/879781/193565245-c3de17e7-3c32-4aef-a221-80fa929d86e4.png)


2. save it , display is corrupted:
![image](https://user-images.githubusercontent.com/879781/193565413-b9d62200-1a04-4c19-b420-162a2b2b99a0.png)

3. Edit it, switch to markdown editor :
![image](https://user-images.githubusercontent.com/879781/193565593-38ff3237-25d0-4377-9ba2-275fe00a4548.png)

4. fix list via the MD editor:
![image](https://user-images.githubusercontent.com/879781/193565724-0bcbbdb8-622a-4d53-a18e-6bab91a3eaa0.png)

5. Save, disaply is OK:
![image](https://user-images.githubusercontent.com/879781/193565822-e6f6944f-0530-41db-ba26-be09f7f4a086.png)

6. edit 
![image](https://user-images.githubusercontent.com/879781/193566112-75b0095f-7a4c-44d4-ba2c-546a32ac29ca.png)

7.switch to MD editor :-( 
![image](https://user-images.githubusercontent.com/879781/193566222-f2f56e6c-29ea-4194-ae77-3d152acdb7cb.png)

**Comment by kamaraj-p** [comment]
Thanks for reporting the issue. The issue is fixed in v9.31.22+.
