### ISSUE TITLE
Pretty response malformed JSON for Angular escape tags

### ISSUE THREAD

**Issue by zaalbarxx** [a85/POSTMan-Chrome-Extension#1128]
Hello!
In the previous release of your plugin there was no problem with parsing JSON as pretty when it was preceded by
    )]}',
characters which are used by AngularJS for safe JSON. In v3 version the JSON is considered as malformed and thus it is far harder to work with it. Is there a chance to fix it ?

**Comment by abhijitkane** [comment]
We'll be adding support for this in v3.0.3.
