### ISSUE TITLE
How to use a different value than accessToken in postman Oauth2 authentication?

### ISSUE THREAD

**Issue by TheInvoker** [a85/POSTMan-Chrome-Extension#11284]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

I am using postman oauth2 feature to authentication on MSALv2, but the problem is is takes the `accessToken` value from the response value.

I would like it to use another property called `idToken`. Is there a way I can write a script or something that will then replace the value?

### Describe the solution you'd like

A new field that specifies the property name to take from the return object. Default value should be the `accessToken`.

### Describe alternatives you've considered

Pre script, but not sure how to code it.

**Comment by giridharvc7** [comment]
Appreciate reaching out here @TheInvoker . We are currently tracking this [here](https://github.com/postmanlabs/postman-app-support/issues/8231). While there's no current way to automatically pull the `id_token` data. They show up in here in the `Manage tokens` section.

You can access this section like so

<img width="692" alt="image" src="https://user-images.githubusercontent.com/1040583/191421695-bf332d8a-b378-4495-855e-7318cde51c79.png">

<img width="903" alt="image" src="https://user-images.githubusercontent.com/1040583/191421768-9e681e3b-0483-4c39-8e9d-d7dd626f236e.png">

I don't have an id token here, but if there is one, it'll show up here

**Comment by TheInvoker** [comment]
@giridharvc7  I see a lot of users wanting this feature on that thread. Is there a ETA for this feature, or roadmap?

**Comment by jankratochvilpostman** [comment]
@giridharvc7 is this implemented / could we close this?

**Comment by giridharvc7** [comment]
Yes, this is now implemented. Please update to the latest version of Postman to get this feature :)
