### ISSUE TITLE
Ability to export Postman Flows

### ISSUE THREAD

**Issue by DimiTech** [a85/POSTMan-Chrome-Extension#11289]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

 no

### Describe the solution you'd like

As a Postman user,
I want to be able to export my **Postman Flows**,
So that my colleague can import and use the **Flows** that I created.

**Comment by samay-v** [comment]
Hey @DusanDimitric You can move Flows between workspaces or have your colleague fork it in their workspace. That should satisfy your usecase 👍🏽 

![image](https://user-images.githubusercontent.com/28357106/191510205-838f5748-6015-4d58-b741-61b3e97652c7.png)

**Comment by sriramramanathan** [comment]
Will the feature to export Flows be available sometime or not at all? We would like to have it merged into our Github repo

**Comment by rabbah** [comment]
This is not currently planned.
