### ISSUE TITLE
Issue in Using socket API

### ISSUE THREAD

**Issue by navneetgarggate6** [a85/POSTMan-Chrome-Extension#11293]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

I have socketio server where I defined a event without any parameter or only one parameter.
But postman not allowing send event without message (arg). How can we do that?

@sio.on('testEvent')
def testEvent(sid):

Also when I checked Acknowledge checkbox getting following issues on clicking on Binary Acknowledgement

### Steps To Reproduce

1. Open new web socket request
2. connect to socket server
3. checked Acknowledge checkbox
4. emit a event
5. click on Binary message

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/16791876/191972818-7a88c7a9-dd08-4f1e-9dd2-530fb0bd8c53.png)
![image](https://user-images.githubusercontent.com/16791876/191972908-8365e461-c0be-44be-8ae6-2c50896517d9.png)

### Operating System

Windows

### Postman Version

9.31.9

### Postman Platform

Postman App

**Comment by appurva21** [comment]
@navneetgarggate6 Thanks for reporting the issue! I am able to reproduce the tab crash at our end and will get this fixed in the upcoming release.

Also, we are already tracking the request to send Socket.io messages with no arguments. You can follow the thread here  #10621 to get further updates on this.

**Comment by appurva21** [comment]
@navneetgarggate6 This is fixed in the latest version of the Postman App.
