### ISSUE TITLE
Server error when trying to connect to a github repository from postman

### ISSUE THREAD

**Issue by liliana-iriarte-tierconnect-com** [a85/POSTMan-Chrome-Extension#11290]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

When trying to connect postman with a GitHub repository, a message appears indicating that something went wrong with the server.

I was using a personal and paid account for both postman and GitHub

### Steps To Reproduce

1. I logged in to postman with a personal account.
2. I import a GitHub repository 
3. The schema was added successfully to the postman
4. I connected to my personal GitHub account successfully.
5. I made some changes to the schema and commit to the repository without any problem.
6. I changed the yml file content on Github
7. I went back to the postman and click on the pull option
8. The schema field disappeared from the postman
4. I tried to connect to the GitHub repository again and an error indicated that something went wrong with the server displayed. (see video attached)

### Screenshots or Videos

https://user-images.githubusercontent.com/14276884/191559649-6acd689d-2b76-4cfb-8a6f-42eabaf5f1d9.mp4

### Operating System

windows

### Postman Version

9.31.9

### Postman Platform

Both

### Additional Context?

The first time I connected my company postman account (paid account) to the GitHub repository it worked smoothly. I changed the connection to my GitHub company account and the server error appeared.

I created a new postman account with a different personal email and follow the steps mentioned before and everything worked until I pull the changes from the postman app.

Attached find the logs. 
[renderer-requester.log](https://github.com/postmanlabs/postman-app-support/files/9618707/renderer-requester.log)

**Comment by shashankawasthi88** [comment]
@liliana-iriarte-tierconnect-com thanks for raising this. We are looking into the bug. 
While we solve the bug, we have launched a new version of this integration in our [V10 release ](https://blog.postman.com/announcing-postmans-redesigned-api-builder-with-native-git-support/) which we are rolling out slowly. You can set up a call with us using [this](https://calendly.com/shashank-awasthi/v10-feedback), I can present you the flow and also help enable the new experience.

**Comment by shashankawasthi88** [comment]
@liliana-iriarte-tierconnect-com this is solved in the latest version of the Postman App. Please give it a try and let us know if the issue still persists. Closing this issue for now.
