### ISSUE TITLE
Postman as a packaged web application?

### ISSUE THREAD

**Issue by epinapala** [a85/POSTMan-Chrome-Extension#1129]
This is more of a question than issue. Pardon me if this is a worng place.

I like Postman Rest client chrome addon very much. I am looking to build a REST API test console, for a handful of Web services we developed. This would be a web application and would like to know if its possible to use Postman source code to make it to work as a web application on all modern browsers.

**Comment by shamasis** [comment]
@epinapala have you had a look at our command line cousin called [Newman](https://github.com/a85/Newman)? It can be used as a JS module and you could whip up a small UI around it.

**Comment by epinapala** [comment]
Hi @shamasis  thanks for your reply. I am actually looking to implement the entire rest client as a web application. Not sure how newman can be of a use for this. Can you eloborate?

**Comment by a85** [comment]
We are currently focusing on native apps. Web apps can't ping to localhost or internal services and won't add much value.
