### ISSUE TITLE
Support for customs themes.

### ISSUE THREAD

**Issue by JrSchmidtt** [a85/POSTMan-Chrome-Extension#11297]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

Currently in postman we have two theme options dark and light would be better if we had other theme options. 

### Describe the solution you'd like

It could be something like a config json to choose color pallet.

**Comment by DannyDainton** [comment]
Duplicate of https://github.com/postmanlabs/postman-app-support/issues/4318
