### ISSUE TITLE
Import popup not coming

### ISSUE THREAD

**Issue by 09samit** [a85/POSTMan-Chrome-Extension#11292]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

After launch postman I try to import but no import popup coming.
Tried File > Import and Cmd + O but no action getting.

Environment -
Postman version 10.0.8
MacOS Monterey version 12.2.1 
Apple M1 Pro.

Note: I find that similer issue is find in pervious versions and that bug has been closed but with the latest version its coming again. 

### Steps To Reproduce

1. Launch postman app
2. Go for  File > Import
3. Click Cmd + O
4. Import screen is not coming

### Operating System

MacOS Monterey version 12.2.1 

### Postman Version

10.0.8

### Postman Platform

Postman App

**Comment by akshaydeo** [comment]
Hi @09samit, thanks for reporting the issue. We are actively looking into it. 

Meanwhile, could you please share app logs by zipping the files you see using View -> Developer -> View Logs in Finder?  You could send the file to `akshay.deo(at)postman.com`

<img width="586" alt="image" src="https://user-images.githubusercontent.com/1050029/191947014-3c8269d5-770e-4644-9aeb-a6ac530d425a.png">

**Comment by akshaydeo** [comment]
Also, quick question: Are you trying to import using the menu/shortcut from the app's home page or a workspace? 

If you are trying from the Home page, these shortcuts won't get triggered as we need to import APIs/Collections in the context of a workspace.

**Comment by elbowdonkey** [comment]
I downloaded Postman for M1 about 10 minutes ago and I'm seeing the same thing on an M1 Mac.

Whether I go to File > Import, or press Command+O, the dialog to select a file to import doesn't even popup. I've been watching logs as I try and not seeing any entries made there. I can include them still if asked though.

**Postman version(s):**
Version 9.31.9
UI Version: 9.31.9-ui-220920-1616
Desktop Platform Version: 9.31.0 (9.31.0)

**Machine/Env:**

MacBook Pro (14-inch, 2021)
M1 Pro, 32GB
macOS 12.6

**Comment by akshaydeo** [comment]
Hi @elbowdonkey, are you on the workspace tab or the app's Home tab? Import modal will only appear if you are on the Workspace tab. Could you confirm this? 🙇‍♂️

**Comment by elbowdonkey** [comment]
I can confirm the import dialog appears once on the Workspace tab.

It'd be really useful if, when selecting the menu item or pressing Command+O, rather than simply doing nothing some sort of message came up describing what must be done. That'd have saved me from trying to troubleshoot the issue this morning, only to find this GitHub issue after burning an hour. Maybe even remove the menu item entirely. It's available as a button when on the Workspace tab already.

**Comment by VShingala** [comment]
@09samit @elbowdonkey We have now introduced support for handling imports on Home / Workspaces page. You'll now be directed to the correct workspace of your choice for import.

Feel free to open the issue again or if you face any further issues with the import.


![Image](https://github.com/postmanlabs/postman-app-support/assets/16756296/ef7f6064-2614-4a25-8ecf-18c61b0d21ed)
