### ISSUE TITLE
Export Test Results Feature 

### ISSUE THREAD

**Issue by dabbank** [a85/POSTMan-Chrome-Extension#1130]
A reason to license postman would be to have the results be exported.
It is missing in the documentation but named in the jetpack extension features.

The use case: we need to attach the results in another Defect-Management Tool to be Revision-Safe.

a complete html representation would be ok, but as a zip for example.

Is there anything already? Does the console offers such export?

**Comment by johnnavarra** [comment]
You can but you have to rely on the javascript and tests. 
As an example. I'm testing a service response for only the presence of a field.
I have  do/while/if statements generating console.log statements so it looks like this in the console.log
SuperPartNumber not found in section 0
SuperPartNumber not found in section 1
SuperPartNumber not found in section 2
SuperPartNumber not found in section 3
SuperPartNumber not found in section 4
SuperPartNumber not found in section 5
SuperPartNumber not found in section 6
SuperPartNumber not found in section 7

you can right click and "save as" in the console log and it saves it as a csv that you can open in excel. This works as a manual test.

Another strategy using the collection runner as a data driven test, testing each scenario on each line of the csv. The key is to make sure the test outputs to the console log so you can export and see the results in one big csv.

**Comment by dabbank** [comment]
Thanks, 
it's a temporary solution. One is also to record network traffic , console.log and save it as HAR . console log is not a proven way to see what you actually did for testing.

There is a save as for a single test, why not a save as for collection?
A nice representation would be nice :D

**Comment by johnnavarra** [comment]
True, but you can parse the response body and output that to the console.log

**Comment by a85** [comment]
You can export test results inside the Collection Runner. The data is available as a JSON file. Let me know if you are not able to find this out. Being used by a lot of users to integrate with their existing reporting systems.

**Comment by amylovejoy** [comment]
Can you explain exactly how to export the test results inside the collection runner? Ideally, I'd like to run the collection and export all console.logs to a file automatically. Can this be done?

**Comment by nchaluse** [comment]
I second amylovejoy's comment...

**Comment by ju40268** [comment]
I ran into this problems as well! I know the test results could be exported manually by clicking the button on the GUI, but I would like run the integration tests at some specific frequency and get the raw test result stored somewhere. Is it now implemented to exported the test result somewhere automatically? Thanks!
