### ISSUE TITLE
Copying a request from one collection and pasting it in another does not paste its data

### ISSUE THREAD

**Issue by singhravi1** [a85/POSTMan-Chrome-Extension#11306]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

I copied three requests from one collection and pasted them in another but when opened them in the new collection, the url, body, params etc. everything is blank.
I can confirm that I saved the requests in the original collection.

### Steps To Reproduce

1. Create requests in a collection with url, params, body etc.
2. Save the requests
3. Create another collection
4. Cope multiple requests from one collection to the new collection
5. Open the requests from the new collection
6. See that the requests details are not visible

### Operating System

MacOs

### Postman Version

Latest

### Postman Platform

Postman App

**Comment by giridharvc7** [comment]
Can you share some logs please, along with the app version @singhravi1

**Comment by singhravi1** [comment]
Hi @giridharvc7 ,
The version is 9.31.13
I unfortunately cannot reproduce this now.
I'm closing this ticket for now. Please reopen if required. Thanks!
