### ISSUE TITLE
Wrong request types on postman collection 

### ISSUE THREAD

**Issue by Jplus2** [a85/POSTMan-Chrome-Extension#11319]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

The type of the requests inside a collection has wrong type (for me POST requests are branded as GET requests).

### Steps To Reproduce

1. Create a collection
2. Add requests to the created collection
3. Change request type from GET to POST

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/5361093/193484724-cc0ede9b-dd59-451b-b548-eb35c3d6492e.png)

### Operating System

Windows 10

### Postman Version

9.31.0 

### Postman Platform

Postman App

**Comment by DannyDainton** [comment]
Hey @Jplus2

Were those requests created as a duplicate of the first request or were they completely blank tabs each time?

It appears like you have unsaved changes for those misslabelled tabs so I suspect they were duplicates, saving them will show the correct method.

**Comment by Jplus2** [comment]
You are right, I might have missed the unsaved indicator. Saving it does update the request type. Thanks!
