### ISSUE TITLE
setNextRequest by requestId broken in forked collection

### ISSUE THREAD

**Issue by dberchtold** [a85/POSTMan-Chrome-Extension#11310]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

In forked Collections "Scripting workflows" are broken when using requestId in statements like this: `postman.setNextRequest("54a7a811-ca08-46d9-8a4e-d10e942e6948")` 

**Reason**: in the forked collections the IDs of the requests are different from the ones in the original collection

Related Documentation
[forking-postman-entities](https://learning.postman.com/docs/collaborating-in-postman/version-control/#forking-postman-entities)
[scripting-workflows](https://learning.postman.com/docs/writing-scripts/script-references/postman-sandbox-api-reference/#scripting-workflows)

### Steps To Reproduce

1. create collection which includes `postman.setNextRequest(requestId:String)`  statements
2. create a fork of the collection
3. run the forked collection

Result: workflow is broken 

### Operating System

Windows

### Postman Version

v9.31.13

### Postman Platform

Postman App

**Comment by DannyDainton** [comment]
Hey @dberchtold 

Could you provide an example of the script you're using (the position of where you place that statement make a difference) and where you're getting the request Id from, please?

**Comment by dberchtold** [comment]
Hi @DannyDainton 
here an example of such a collection
https://www.getpostman.com/collections/198cc7a841c73d6240bf

![image](https://user-images.githubusercontent.com/9194415/193550458-133aee3f-c634-4246-8c3b-77f55e5d0180.png)

**Comment by DannyDainton** [comment]
The Forked Collection/Folders/Requests wouldn't have the same `ids` as the original, as this is its own entity and not the _same_ entity. 

If you're using that function, you could use `postman.setNextRequest('end')` which would go to that request in the flow on both Collections (Forked and Original).

**Comment by dberchtold** [comment]
In my original collection I had reqeusts with identical names. So referencing by name is ambiguous. Therefore I thought it would be a good idea to use ID instead. But now it looks like this is not good if using forks.
I already changed the collection to use unique names for requests which are used in setNextRequest() calls.

When creating the ticket I was just wondering if there maybe is some other solution where i still could use some ID - but turns out there isn't

I would suggest to update the Docu by adding some warning that when using ID the workflow will break in forked collection because ID will change.
[scripting-workflows](https://learning.postman.com/docs/writing-scripts/script-references/postman-sandbox-api-reference/#scripting-workflows)

**Comment by DannyDainton** [comment]
You're creating a brand new Collection by forking the other one, it wouldn't have the same `Id`. It's not a limitation or some functionality missed, it would be the same if you create 2 new separate Collections in the Workspace, these would have different `Ids`.

You could use something similar as this method to capture the request ids and save them as variables:

```
//script in another request calls:
//pm.environment.set('next', pm.info.requestId)
postman.setNextRequest(pm.environment.get('next'));
```

All of the documentation is open source so if you're like to raise a PR for that change, a member of that team can take a look and move that forward. 🏆 

https://github.com/postmanlabs/postman-docs/blob/develop/src/pages/docs/writing-scripts/script-references/postman-sandbox-api-reference.md

I'm going to close this issue as there isn't any change that we would be making on the product side.
