### ISSUE TITLE
The ability to clear the 'Mock Server Call Log'

### ISSUE THREAD

**Issue by achrapko** [a85/POSTMan-Chrome-Extension#11315]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

Mock Server Call Log items are unable to be removed or cleared, causing clutter when running tests.

### Describe the solution you'd like

Currently, the Mock Server Call Log does not have a way to clear either a single, or all items for a given Mock Server. It would be nice to be able to clear these so I can keep results of various test runs cleaner.

### Describe alternatives you've considered

The only current alternative is to delete the Mock Server, and recreate it, but this requires adjusting configurations in other applications being tested to point at the new Mock Server URL.

**Comment by greglow-sdu** [comment]
Yes, this is one of the first things I went looking for, and ended up Googling for ages trying to find an answer. I did a test to make sure the server worked, but then couldn't find any way to remove the test call. Seemed odd to need to remove the server (and reconfigure everything) just to clear the log.

**Comment by NeilShadrach** [comment]
Just arrived here while searching for the same feature

**Comment by shikhar-codes** [comment]
Hi everyone, this ability has been added in the latest release - v10.22.0 
Do give it a try 🎉

**Comment by iamdman** [comment]
> Hi everyone, this ability has been added in the latest release - v10.22.0 Do give it a try 🎉

where dont see it I am in v11

**Comment by shikhar-codes** [comment]
@iamdman you would be able to see the delete icon for every log in your mock tab / workbench as can be seen in the below screenshot. Do refer to the [mock learning centre](https://learning.postman.com/docs/designing-and-developing-your-api/mocking-data/setting-up-mock/#viewing-mock-calls:~:text=receive%20example%20responses.-,Viewing%20mock%20calls,-You%20can%20view) where we have mentioned details around it. 

If it is not there in your case, please let us know. 

![image](https://github.com/user-attachments/assets/2dfe5298-1177-4934-8977-76a9dd2e54d6)

**Comment by iamdman** [comment]
> @iamdman you would be able to see the delete icon for every log in your mock tab / workbench as can be seen in the below screenshot. Do refer to the [mock learning centre](https://learning.postman.com/docs/designing-and-developing-your-api/mocking-data/setting-up-mock/#viewing-mock-calls:~:text=receive%20example%20responses.-,Viewing%20mock%20calls,-You%20can%20view) where we have mentioned details around it.
> 
> If it is not there in your case, please let us know.
> 

Yes I have that button for each request, but you need a **clear all** button because I have been deleting the logs for about 30 minutes, I have over 2000 to go through.

**Comment by Ludogo** [comment]
Can you please add a button to purge all logs ?  I would be so great !!!

**Comment by thanhqb13293** [comment]
We need a button to purge all logs, please.

**Comment by Josh18C** [comment]
@iamdman, @Ludogo, @thanhqb13293 

I created a new issue for what we are all asking for here: https://github.com/postmanlabs/postman-app-support/issues/13333
