### ISSUE TITLE
Deep linking to a folder in a collection of documentation does not anchor correctly

### ISSUE THREAD

**Issue by mredding999** [a85/POSTMan-Chrome-Extension#11313]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Here is the deep link to a folder in my documentation collection that includes the #ID generated by Postman:
https://documenter.getpostman.com/view/7580355/VUxNQ7Uv#aa14fdaa-a6a1-4779-bb3b-cfb5e9df135a

Screenshot, and notice how the "Country" header for the folder is near the bottom of the screen:
![image](https://user-images.githubusercontent.com/108549550/193299770-0a774b17-c24a-4487-a312-cf71a05744ef.png)

Now click on the Country folder on the left hand side.  The Country jumps to the top, as it should. But why doesn't the deep link do the same thing? The URLs are the exact same.  

Any workaround for this?

### Steps To Reproduce

See above.

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/108549550/193300165-105022ac-cd53-46e2-ac27-6eb3bcb8798e.png)

### Operating System

Windows

### Postman Version

Web Cloud

### Postman Platform

Postman Web

### Additional Context?

None

**Comment by ajeet-postman** [comment]
@mredding999  This issue is fixed. Can you please confirm  if you are still facing this?

**Comment by mredding999** [comment]
Hi Ajeet,

The issue is not fixed.  When I deep link to a folder that is down in the middle of a collection or near the bottom the anchor missed really bad, to the point where the folderheading is not even displayed on the page at all...you have to scroll way down to get to it.  What other info do you need?

Thanks,

Mark

________________________________
