### ISSUE TITLE
 Digest authorization does not increase the NC value

### ISSUE THREAD

**Issue by accountnujen** [a85/POSTMan-Chrome-Extension#11326]
### Is there an existing issue for this?

- [x] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

second request does not increase NC, although according to RFC it should have been increased, otherwise the request will return a 401 error, which actually happened.

### Steps To Reproduce

1. Create Collection
2. set Digest authorization 
3. Create HTTP request
4. Create second HTTP request
5. Run Collection
6. Open console

### Screenshots or Videos

![iiii](https://user-images.githubusercontent.com/91395439/193949715-79607d5f-944e-48a1-8341-b75e7ae2e0b6.png)

### Operating System

Windows

### Postman Version

10.0.15

### Postman Platform

Postman App

### Additional Context?

I created a collection and set up Digest authorization in it. I created 2 queries, but the second query ends with an error. If you open the console, you will see that the second request does not increase NC, although according to RFC it should have been increased, otherwise the request will return a 401 error, which actually happened.

**Comment by shubhbhargav** [comment]
@accountnujen Can you please confirm if the `nonce` value across the two requests is same? For Digest Auth, the client needs to get the nonce value from the server first and the `nonce-count` needs to be incremented if the client is using the same nonce value.

In Postman, we always get a new `nonce` value for each request which ensures that `nc=0000001` works because every request is treated as a new request.

**Comment by accountnujen** [comment]
> In Postman, we always get a new nonce value for each request which ensures that nc=0000001 works because every request is treated as a new request.

This sentence contradicts itself.

If postman makes a new query every time and uses a new nonce, why didn't he make 4 queries: 401, 200, 401, 200? Why did it stop at the 3rd request with the 401 error? So it's still making the first request to get the nonce and postman is trying to maintain the session, but it can't (judging by the same NC).

nonce is the same. you can look at the requests. Apparently Postman forgot to do Digest authorization according to RFC. There is a button, but it doesn't work.

![iiii](https://user-images.githubusercontent.com/91395439/194449074-7300ac9f-b217-47ba-bbf1-7271b8816beb.png)

**Comment by shubhbhargav** [comment]
@accountnujen You are right. It should have made 4 requests. That's what I am seeing at my end. One difference that I saw is that the Auth header is being sent in the above screenshot shared in the above comment while in my case that was not the case.

Can you share the above request / collection with us at `help@postman.com`? We will need to debug how the Authorization header is being set here.

<img width="1512" alt="Screenshot 2022-10-06 at 7 10 00 PM" src="https://user-images.githubusercontent.com/41579749/194451858-f6497fe6-a282-4738-a668-e7cbf09668df.png">

**Comment by sandeep-singh-pstmn** [comment]
@accountnujen We are happy to inform you that the issue has been resolved with the latest update (v11.1.0). Please update your application and verify the fix.

https://github.com/postmanlabs/postman-app-support/assets/85243040/17ddb833-3010-4b67-9376-2229645f78e4
