### ISSUE TITLE
need option for always show params in new UI

### ISSUE THREAD

**Issue by cognisent** [a85/POSTMan-Chrome-Extension#1132]
I apologize if this has already been reported. I went through a few pages and performed a search, but there are a lot of open issues.

In the old interface, the query and URL parameters were always shown:

![image](https://www.getpostman.com/img/docs/source/3.png)

In the new interface, every time I want to see them or change them, I have to click the **Params** button:

![image](https://cloud.githubusercontent.com/assets/1672405/8085964/f7872a64-0f60-11e5-9fbb-01a9e652b814.png)

This essentially adds an additional click to the majority of the things that I use Postman for. Additionally, the fact that parameters are not always shown but headers are shown seems backwards to me. I am _significantly_ more likely to want to tinker with url/query parameters than I am to want to tinker with headers.

Could Params not just be another one of the available tabs? Maybe a setting for this? This change is, in my opinion, a step backwards in the usability of this tool.

Thanks for your time.

**Comment by a85** [comment]
This has been changed since Postman 4.0+
