### ISSUE TITLE
Using x-mock-response-name disables wildcard resolving in response

### ISSUE THREAD

**Issue by mlaffargue** [a85/POSTMan-Chrome-Extension#11323]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Having a request :
`GET {{url}}/example/{{objectId}}`

And an example "SUCCESS" with as response :
`{"objectId": "{{objectId}}" }`

If I call the mock server with GET .../example/test123, the response is as expected :
`{"objectId": "test123" }`

However if I add the header `x-mock-response-name: SUCCESS`, then the response is :
`{"objectId": "{{objectId}}" }`

I need to have test123 not the wildcard, and I need to choose example by name.

### Steps To Reproduce

Create a request `GET {{url}}/example/{{objectId}}`, add a header `x-mock-response-name: SUCCESS`
Create a mock server with this request inside.

Create an example "SUCCESS" with response `{"objectId": "{{objectId}}" }`

Run the request, the response has the wildcard, not the value caught in the URL.

Remove the `x-mock-response-name` header, the response has the value caught in the URL.

### Operating System

Windows

### Postman Version

9.31.14

### Postman Platform

Postman App

**Comment by mlaffargue** [comment]
So, this morning it's working as expected.

I didn't restart anything, not even my computer.
I just sent the requests again (from the same tab that were opened yesterday) and magically the "{{objectId}}" change to what is expected.

Not clear if someone corrected something or if we need to wait for it to make it works.

**Comment by mlaffargue** [comment]
No news on that ?

**Comment by Dhembla** [comment]
Hey @mlaffargue,
Thanks for reporting this issue, and sorry for the hassle you had to go through. A fix for this issue has been released. Please try it out and let me know if the issue persists. 🙇

**Comment by MichaelLaffargue** [comment]
Thanks @Dhembla, it works as expected for me 👍
