### ISSUE TITLE
Keyboard shortcut to change environments

### ISSUE THREAD

**Issue by rockey5520** [a85/POSTMan-Chrome-Extension#11327]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

No

### Describe the solution you'd like

I use most of my development activities using keyboard and keyboard shortcuts using postman are great. There is one more shortcut if available would be super beneficial is being able to switch environment using a shortcut rather than using mouse.

### Describe alternatives you've considered

using mouse

**Comment by vnosach-clgx** [comment]
+1

**Comment by chris-torruella** [comment]
Hi @rockey5520 and @vnosach-clgx . I'm glad to share with you that following on your request we have released the Environments shortcut as part of the latest 10.13.0v of Postman. It will be available to all users in the next few days. The default shortcut combination (which now you can customize anytime) is:
- Mac: ⌥E
- Windows: Alt + E

Hope you find it helpful. Thanks for your patience!
