### ISSUE TITLE
Requests in collection don't always show and cannot be deleted 

### ISSUE THREAD

**Issue by zznty** [a85/POSTMan-Chrome-Extension#11321]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Some of requests are ghosting, they appear in editor after clicking `view docs` and showing 404 error when im trying to delete them.

### Steps To Reproduce

1. create collection
2. in creation modal window add some requests for e.g `GET` `/server/status`
3. after creating you will get **two empty** collections with same name
4. click `view documentation` on both, one will throw `something went wrong` another actually show ghosted requests
5. try to delete one of them
6. see the error

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/94796179/193591321-2d2bec78-52a4-4b0b-991f-250277a2bc34.png)
![image](https://user-images.githubusercontent.com/94796179/193591365-222823b9-3d0f-4495-a2eb-ee6ea228fce9.png)

### Operating System

Windows 10

### Postman Version

9.31.15 desktop, 9.31.18 web

### Postman Platform

Both

### Additional Context?

Actually by duplicating the collection its not preserving such ghosting effect and its able to remove these requests

**Comment by shubhbhargav** [comment]
@zznty Is this issue consistently reproducible for you? If yes, can you please share a screen recording of the steps? I tried to follow the steps mentioned but couldn't reproduce this issue.

**Comment by zznty** [comment]
@shubhbhargav yes, pretty much consistently.

https://youtu.be/S6dhKOhQtL8

**Comment by shubhbhargav** [comment]
Thanks for the info @zznty . We are looking into this on priority.

**Comment by shubhbhargav** [comment]
@zznty We are working on the fix for this. We will update here once it is deployed.

**Comment by ishan-ks** [comment]
@zznty We have rolled out a fix for this issue. Please update the app to the latest version - **Web v9.31.24** or **Desktop v9.31.21** and let us know if the issue is fixed for you as well.

**Comment by zznty** [comment]
seems to be fixed for me too.
thanks, ill close issue then.
