### ISSUE TITLE
Cookies not being set for different domain

### ISSUE THREAD

**Issue by chrisonyohannan** [a85/POSTMan-Chrome-Extension#11335]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Cookie is not being set in spite of the response having a Set-cookie header with a different domain.

### Steps To Reproduce

Perform any http request on a domain, example: abc.com/example, which returns cookie header with a different domain such as:
Set-Cookie: captchaValue=bamwxkh;Domain=.xyz.com;Path=/;Version=1;Secure

This cookie doesn't get stored.

### Operating System

macOS

### Postman Version

10.0.19

### Postman Platform

Postman App

**Comment by postman-staff** [comment]
Hey  @chrisonyohannan
I tried to replicate the behaviour but was unable to get it.

Let me know if you are using any special Use domain names like .local, We have an ongoing issue and it is been tracked in the below thread:
https://github.com/postmanlabs/postman-app-support/issues/10620

Also let me know if you are manually setting cookies via the Cookie Manager, if yes then you have to specify the `Domain` attribute for it to match for subdomains.
Can you try to whitelist domains using scripts in Postman and check if it helps?

References below:

- Scripting with request cookies
- https://www.postmanlabs.com/postman-collection/Cookie.html

Let me how it goes.
via @Lincimary | Postman Support

**Comment by postman-support** [comment]
{{comment_data}}
