### ISSUE TITLE
Desktop agent installer broke all Postman functionality!

### ISSUE THREAD

**Issue by andythedishwasher** [a85/POSTMan-Chrome-Extension#11333]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

I'm having a pretty major issue where I tried to use the installer for the Desktop Agent on Windows 10, but instead of giving me access to the Desktop Agent, it seems to have disabled all Postman requests since the send button in my web client (which turned blue) is now greyed out with the error message "Desktop Agent unavailable". 

### Steps To Reproduce

1. Download Postman-Agent-win64-0.4.7-Setup.exe
2. Run the file
3. Attempt to open desktop client and/or make a request from the web client.

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/95928720/194338437-835b5bd7-c1cf-458a-8db8-6bee86faf19c.png)

### Operating System

Windows 10

### Postman Version

Version 9.31.20-221005-1546  Chrome 106 / Windows 10

### Postman Platform

Postman Web

### Additional Context?

When I look into the settings.json file in the directory where the Postman desktop agent was installed, the value for "downloadedVersion" is null.
When I look in the activity logs, there are several errors that propagate:
 
[main.log](https://github.com/postmanlabs/postman-app-support/files/9725602/main.log)

The ultimate result is that I can't seem to make any requests through Postman at all now. Can someone explain this to me?

**Comment by DannyDainton** [comment]
Hey @andythedishwasher

Are you able to use any of the other agents?

https://learning.postman.com/docs/administration/onboarding-checklist/#setting-up-postman
