### ISSUE TITLE
Missing Title Bar and Menu Bar

### ISSUE THREAD

**Issue by phen-chub** [a85/POSTMan-Chrome-Extension#11332]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

The app no longer has a title bar or menu bar.

### Steps To Reproduce

Open the latest version of the app.

### Operating System

Windows 10

### Postman Version

10.0.15

### Postman Platform

Postman App

**Comment by DannyDainton** [comment]
Can you provide screenshot of the UI behaviour that you can see please?

Are you updating the app from an older version, if so, what was that?

**Comment by phen-chub** [comment]
Yes, just updated from 9 to 10 on one computer.  Still have 9.21.5 on another.

Old:
![image](https://user-images.githubusercontent.com/78876491/194253658-56e534a2-b00a-42d1-8bf4-9e3fd73e3590.png)

New:
![image](https://user-images.githubusercontent.com/78876491/194254411-5027c211-78e8-4ca1-959e-194b6332f13c.png)

**Comment by postman-staff** [comment]
Hi @phen-chub,

Could you share a recording of the issue and the logs and send these over via support ticket: https://support.postman.com/hc/en-us/requests/new - please?

We find loom.com helpful for sharing screen records.
How to get logs from the Postman Web app

via @beatrixSze | Postman Support

**Comment by mennoxx** [comment]
It's not missing. On Windows It has finally been merged together with the header and menu bar is inside the burger menu.
Sadly not on linux, yet, but thats way more complicated.

related: https://github.com/postmanlabs/postman-app-support/issues/5302 https://github.com/postmanlabs/postman-app-support/issues/2412

**Comment by SelectBlinds-JoeS** [comment]
With this new merging, the application is no longer draggable, so I cannot drag it to a different screen.  There is a Minimize and Maximize button in the top right, but no Restore Down.  I really, really want the normal Windows title bar back.

**Comment by mennoxx** [comment]
Your Postman window seems to be in fullscreen mode then. By pressing F11 you should get your restore/maximize button and draggability back.
