### ISSUE TITLE
Can't scroll list of environments

### ISSUE THREAD

**Issue by brentonhouse** [a85/POSTMan-Chrome-Extension#1133]
If you have a lot of environments, you cannot scroll the list.  This also means that you cannot get to the button at the bottom which allows you to manage environments.   

Trying to find work around to at least be able to get to manage so that I can delete some until this issue is fixed.

**Comment by abhijitkane** [comment]
We'll be pushing a fix for this soon.

**Comment by brentonhouse** [comment]
awesome!  thanks!!

**Comment by abhijitkane** [comment]
@brentonhouse Can you confirm this fixed in v3.0.4?

**Comment by brentonhouse** [comment]
Everything is working great!!
