### ISSUE TITLE
I can't delete my Google account.

### ISSUE THREAD

**Issue by kim-mini6** [a85/POSTMan-Chrome-Extension#11339]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

I'm trying to delete my account, but I can't log in to my Google account in the user authentication part.

Even if you enter your Google email password, authentication does not work.

Please refer to the screenshot.

### Steps To Reproduce

Steps To Reproduce

### Screenshots or Videos

![스크린샷 2022-10-10 오전 2 03 31](https://user-images.githubusercontent.com/55689271/194769923-91006003-4ffe-4cc6-951d-7e327eeb9765.png)
![스크린샷 2022-10-10 오전 2 04 38](https://user-images.githubusercontent.com/55689271/194769971-68c055d8-ed6b-4c9a-a56a-38bdb385e1dc.png)

### Operating System

macOS

### Postman Version

10.0.20

### Postman Platform

Postman App

**Comment by ArjunSingh-PM** [comment]
Hello @kim-mini6, do you see an option to `Sign in with Google` at https://identity.getpostman.com/? Could you please try signing in using this option? 
![image](https://user-images.githubusercontent.com/53265429/194806706-7c0ba207-48ee-4fa4-952c-d3053739a130.png)

If you still face issues, please reach out to us at help@postman.com. Thanks!

**Comment by kim-mini6** [comment]
When you unsubscribe, the Sign in with Google button does not appear.

**Comment by ArjunSingh-PM** [comment]
@kim-mini6 We have identified and corrected the issue. You should be able to use the `Sign in with Google` option now.
