### ISSUE TITLE
GraphQl Schema gone with V10

### ISSUE THREAD

**Issue by jSylvestre** [a85/POSTMan-Chrome-Extension#11336]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Using a local API schema, it doesn't appear as a choice with version 10.
If I install the latest WIn 64 from the downloads page, they show up again.

### Steps To Reproduce

Install Version 10, then local schemas do not show up.

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/469010/194649413-daeda4d1-7670-48e1-b12a-a10c0c516c42.png)

### Operating System

Windows

### Postman Version

10.0.20

### Postman Platform

Postman App

**Comment by giridharvc7** [comment]
@jSylvestre Thank you for reporting this issue, we are looking into it right now. Will let you know once we have fixed it here in the same thread

**Comment by giridharvc7** [comment]
We've fixed this bug
You can either check Web v10.0.21-221010-0634 or desktop v10.0.21-ui-221010-0634. 
Just reopen the app for the latest update. 

Please let us know if things are working as expected.

**Comment by jSylvestre** [comment]
@giridharvc7 Yes, looks good now.
Thanks for the quick fix,
-Jason
