### ISSUE TITLE
"Create a schema" endpoint not working

### ISSUE THREAD

**Issue by geogrigor** [a85/POSTMan-Chrome-Extension#11331]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

The `https://api.getpostman.com/apis/{{apiId}}/versions/{{apiVersionId}}/schemas` endpoint always errors out. When calling the endpoint with the example payload from the [documentation](https://www.postman.com/postman/workspace/postman-public-workspace/documentation/12959542-c8142d51-e97c-46b6-bd77-52bb66712c9a) (and replacing the `apiId` and `apiVersionId` values) I get the following error:

```
{
  "error": {
    "name": "paramMissingError",
    "message": "There was an unexpected error adding your API schema. Please try again."
  }
}
```

### Steps To Reproduce

1. Call the `https://api.getpostman.com/apis/{{apiId}}/versions/{{apiVersionId}}/schemas` endpoint with a valid payload

### Operating System

macOS

### Postman Version

10

### Postman Platform

Other

**Comment by akshaydeo** [comment]
@geogrigor, thanks for reporting this issue. We are looking into it 🙇

**Comment by diyaeninan** [comment]
Hey @geogrigor! We were not able to reproduce this issue. Could you confirm whether along with replacing the `apiId` and `apiVersionId` values, the additional fields in the request body (`schema.type`, `schema.language`, `schema.schema`) were also replaced with appropriate values?

This example can be used as a reference for the request body: https://www.postman.com/postman/workspace/postman-public-workspace/example/12959542-9b86241f-725f-4949-b11d-e791f6487452

**Comment by geogrigor** [comment]
Hi @diyaenina, apologies I see now the issue is with my request. I supplied the inner "schema" value but did not nest the payload in an outer "schema" property. Thank you for your help
