### ISSUE TITLE
Feature Request: Support for "Visualisation" in Flows

### ISSUE THREAD

**Issue by harryi3t** [a85/POSTMan-Chrome-Extension#11337]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

No

### Describe the solution you'd like

We can use the visualise feature for a single request. This feature request is for adding support for the same in Flows as well.

If any request in the Flow is using the "pm.visualizer" API to render some preview, right now we can't see that anywhere (maybe the logic is not even running in the Flow mode).

I trust you folks will figure out the best possible UX for this, but here is what I could come up with:

### 1. We can add new section in the "information" sidebar like this:
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/5207331/194699684-35cce3d8-71d6-4173-89f4-54e33d125cee.png">

**Comment by rabbah** [comment]
The Flows output block supports a number of builtin visualizations.
