### ISSUE TITLE
Postman API: Cannot delete folder from collection

### ISSUE THREAD

**Issue by maticardenas** [a85/POSTMan-Chrome-Extension#11334]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Hi, I have created several folders into a public collection we have, however, I'm not able to delete one (through `DEL https://api.getpostman.com/collections/{{collection_id}}/folders/{{folder_id}}`  in which the `id` I had assigned consist of multiple words.

```
{
                "name": "test_folder",
                "item": [],
                "id": "uuuuh one more"
            }
```

So, basically I was able to create it with an `id` with multiple words but it doesn't seem to be found when passed as path parameter. I have tried using `%20` or `+` as separators in the path unsuccessfully. Getting always a `404` response.

Additionally, the folder cannot be deleted through the UI, getting both a successful & unsuccessful attempt to delete pop up when doing so.

![image](https://user-images.githubusercontent.com/12075970/194344523-179c46e4-e412-4891-af7f-8c89f3a925f1.png)

Could you please provide a way to delete the folder through the API, given its ID has multiple words? Or, if it's not possible, could you please delete the folder, as it's part of our public collections it could be misleading to have this empty folder published there.

Collection link: https://www.postman.com/sendcloud-api/workspace/sendcloud-rest-api/collection/17867205-42468079-d6a1-4cf8-9e9f-6d7b1f3cc111?action=share&creator=17867205

Thanks!

### Steps To Reproduce

1. Create a folder with an `id` that consist of multiple words through `POST https://api.getpostman.com/collections/{{collectionId}}/folders` endpoint
2. Attempt to delete it through `DEL https://api.getpostman.com/collections/{{collectionId}}/folders/{{folderId}}` endpoint, trying to use `%20` and `+` as separators for the words.
3. Response is always `404` and folder cannot be deleted.
4. Additionally, through the UI and with the same user, folder is not allowed to be deleted and UI states that it's even not found.

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/12075970/194345452-cd5aad05-3d79-4c3e-810c-4c4ffa3ac40c.png)

### Operating System

macOS

### Postman Version

9.31.0

### Postman Platform

Postman App

**Comment by davidespihernandez** [comment]
Thanks for your question, @maticardenas. Seems to be a bug, we'll look into it.

**Comment by davidespihernandez** [comment]
@maticardenas Can you please post here the exact request (URL, method, body) you used to create the folder? Thanks!

**Comment by maticardenas** [comment]
HI @davidespihernandez , thanks for your reply.

Yes, this is a similar request to the one I performed to create the folder in that collection:

```
curl --location --request POST 'https://api.getpostman.com/collections/42468079-d6a1-4cf8-9e9f-6d7b1f3cc111/folders' \
--header 'Accept: application/vnd.postman.v2+json' \
--header 'x-api-key: <key>' \
--header 'Content-Type: application/json' \
--data-raw '{
  "id": "uuuuh one more",
  "name": "test_folder"
}'
```

**Comment by davidespihernandez** [comment]
Thanks, @maticardenas!

I can confirm the problem is related to the white spaces in the id. If you don't use any white space, you will be able to create and manage the folder without errors.
We are trying to get that folder deleted for you, I'll let you know when that's done.
In addition, we will fix the API to reject ids with blank spaces and will change the documentation accordingly.

Thanks for your time!

**Comment by maticardenas** [comment]
Thanks a lot @davidespihernandez

**Comment by maticardenas** [comment]
Hi @davidespihernandez,

Sorry to bother you again, but was it possible to check the deletion of the folder? I see unfortunately that it's still there and I'm still unable to delete myself through the UI 😢 

Reason I ask, is again, that it's added by mistake in our public collections and given that it's what all consumers check it's not ideal to have a test folder there. 

Thanks!

**Comment by davidespihernandez** [comment]
Hi, @maticardenas.
Sorry about the late response. I've increased the priority of this task. Hopefully, it will be done soon. I'll keep you informed.
Thanks!

**Comment by davidespihernandez** [comment]
Hi, @maticardenas!
Does your user have delete permissions on that collection? I mean, if you try to delete any other folder, is that permitted for you?

**Comment by maticardenas** [comment]
Hi @davidespihernandez,

Yes, my user do have permission to delete folders on that collection. I fact I had created multiple test folders at the beginning and I was able to delete all of them **except** the one with the `id` with multiple words as I had described.

**Comment by davidespihernandez** [comment]
Hi, @maticardenas!
Just to confirm something, can you please perform a GET to the `https://api.getpostman.com/me` endpoint, using your Postman API key as authentication method, and send the user id that the request returns? That's not a secret value...
The request would be something like:

```
curl --location --request GET 'https://api.getpostman.com/me' \
--header 'Accept: application/vnd.postman.v2+json' \
--header 'x-api-key: <YOUR_API_KEY>'
```

**Comment by maticardenas** [comment]
Hi @davidespihernandez ,

This is the user id that request returns:

`"id": 17867205`

**Comment by petkostas** [comment]
Any updates regarding this? we still have a `test_folder` in our **public** collection that we cannot delete that looks awkward and unprofessional.

**Comment by VaishnaviChallaPostman** [comment]
@petkostas Sorry for the delay here. Our team is looking into this issue. Please raise a support ticket[ here](https://support.postman.com/hc/en-us/requests/new/) to share more details to unblock you. 
It would be great if you could include the GitHub issue title and number in the subject to help us identify your ticket. 
We will be taking it forward from there. Thank you!

**Comment by maticardenas** [comment]
@VaishnaviChallaPostman I have created the request (apparently #122778) providing as a title this github issue title with the corresponding number.

**Comment by Raj-postman** [comment]
Marking this to `Closed` as the folder is now removed. Thanks!
