### ISSUE TITLE
Collection Runner - A new Run removes the previously attached data file

### ISSUE THREAD

**Issue by jasonrakers** [a85/POSTMan-Chrome-Extension#11342]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

v10.0.20 seems to be removing the attached data file used in Runner.  Previously, selecting New Run returned to the Runner tab with the existing collection and data file selected.  Now the existing collection is selected, but the data file is removed.  It needs to be re-added after every run.

### Steps To Reproduce

1.Create a Runner tab
2. Attach data file
3. Run job
4. Select New Run to run another collection
5. Notice that the previously used data file is no longer attached.

### Screenshots or Videos

![runner3](https://user-images.githubusercontent.com/45398911/194859859-e7d92ec9-65d4-4287-9ecd-9d2de74969b0.JPG)
![runner2](https://user-images.githubusercontent.com/45398911/194859861-3771484a-dc46-41ca-a26b-72a6ed3ef583.JPG)
![runner1](https://user-images.githubusercontent.com/45398911/194859862-4993b8a2-72fe-47ae-b179-28c783d1a005.JPG)

### Operating System

Windows

### Postman Version

10.0.20

### Postman Platform

Postman App

**Comment by DannyDainton** [comment]
Hey @jasonrakers 👋🏻 

Thank you for raising this issue - I was able to reproduce this using V10. We're going to take a look and see what's happening there.

We'll update the thread once we have more information - Thanks again.

**Comment by ghost** [comment]
Hi, I'd like to add to this. Not only is the attached file removed, the whole new run is reset to default values. Advanced settings checkboxes are reset plus all the APIs in the collection are ticked. Sometimes I only need to run a selection, not the entire collection. It's as if clicking "New run" also does "Reset" at the same time.

**Comment by malvikach** [comment]
hey @jasonrakers @koki-v3 👋 

Glad to update that the above-mentioned issues have been fixed (in Postman version 10.4.2 and above).  

Please let us know if you face any other problems. Thanks again for bringing this to our attention. I am closing this ticket, feel free to reopen it or create a new ticket if needed. 

Cheers!
Malvika
