### ISSUE TITLE
Upgrade to V10 does not update the API when the Collection is updated

### ISSUE THREAD

**Issue by Cindi-QA** [a85/POSTMan-Chrome-Extension#11345]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Upgraded to V10 and now the API and Collection do not match.  I renamed the Collection but it was not updated in the API panel.  I added all my code, tests, variables, etc in the collection but they are not in the APIs.  When I run the collection after the token is set in the start up, all the APIs take a 401 not authorized since they are not updated to the Inherit from Parent in the API panel.  They are all set to Inherit from Parent in the collection panel.

### Steps To Reproduce

1. Upgrade to V10
2. Import API by link using swagger
3. Select to add collection 
4. Update collection with code, tests, variables etc.
5. Run collection

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/97465795/194947761-b9d1a714-072b-42a4-9d12-d20babd869b1.png)
This is my collection with all the code, tests, variables and startup folder added for the Main 617

![image](https://user-images.githubusercontent.com/97465795/194947926-f73881be-34ca-45bf-ab36-df14b332a73b.png)
This is the API panel for my API set.  It was not renamed, start up folder is not there.

![image](https://user-images.githubusercontent.com/97465795/194948090-61cdd88b-99be-40fe-9b7d-d0b9524cc0aa.png)
Example of one of the APIs where it was not updated from the collection.

### Operating System

Windows 11

### Postman Version

10.0.20

### Postman Platform

Postman App

### Additional Context?

This collection was running before the upgrade.  I had three new APIs that were added to the suite so was creating a new Main to use for the collection to run with Newman/NodeJS

**Comment by shashankawasthi88** [comment]
Hi @Cindi-QA with the launch of V10, we have disassociated the collection in API from the collections that you see in the sidebar. When you add a collection, a copy of the collection is created and attached to the API. Now you have two collections, one in the collection sidebar and one in API, they do not have any inheritance/ connection. Refer to the docs [here](https://learning.postman.com/docs/designing-and-developing-your-api/developing-an-api/adding-api-elements/#adding-an-existing-collection) for adding/ copying an existing collection.

**Comment by shashankawasthi88** [comment]
Closing this issue. Feel free to open it if the flow is still unclear.
