### ISSUE TITLE
Duplicate request does not work anymore

### ISSUE THREAD

**Issue by lgext06** [a85/POSTMan-Chrome-Extension#11346]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

The duplicate request function produces a new entry with an empty URL, empty headers. 
It is just a new entry, but nothing is copied from the duplicated request.

### Steps To Reproduce

1. Select a request
2. Duplicate the request
3. check the new entry: there is no URL, no header 

### Screenshots or Videos

original request:
![image](https://user-images.githubusercontent.com/58026893/195018765-f6332cc9-25a3-4a34-b5b0-0e6b3cc64120.png)

Duplicated request: 
![image](https://user-images.githubusercontent.com/58026893/195018822-65eb4fbe-c805-4b60-a824-74e0f42fba98.png)

### Operating System

Windows

### Postman Version

10.0.21

### Postman Platform

Postman App

**Comment by DannyDainton** [comment]
Hey @lgext06

Can you increase the surface area of the images, to include the whole app state, please? 

Also, are you duplicating the request or duplicating the tab?

**Comment by lgext06** [comment]
HI @DannyDainton , 
I'm using the duplicate context menu on the request entry :
![image](https://user-images.githubusercontent.com/58026893/195030778-dc038235-897c-44fa-90e0-4ac83ecfbe6a.png)

**Comment by DannyDainton** [comment]
Did the one where you duplicated it from, still have unsaved changes? Does it have an orange dot in the tab title?

**Comment by lgext06** [comment]
Good question: yes, it does have an orange icon. 
Thus, I tested after saving and it works if the original request is unchanged.
 
But if the original request is modified again, the duplicate will produce empty copy. 

I would expect to have the current values copied, so that I can revert the changes on the original request. 

Not sure if this is a bug, or by design?

**Comment by DannyDainton** [comment]
Not too sure what you mean by this:
> But if the original request is modified again, the duplicate will produce empty copy.

It will duplicate the saved changes for a request, if there are pending changes those won't be duplicated. It won't create an empty tab unless the tab was empty to begin with.

**Comment by lgext06** [comment]
Hello, 
I started recording a video when I realized why I don't understand the behavior.
 
The duplicate request adds the request just below the duplicate one, not at the end of the list. 
This is why I could not see saved changes taken into account, because I was watching the first copy ... 

Now I feel embarrassed to have abuse your time .. but at least I understand the behavior .. 

May I suggest to improve the duplicate behavior : 
- warn when pending changes are present at the moment of the duplicate so the user knows what he's doing
-  like in Windows file copy: if the same name exists, number the duplicate entry (1), (2) , and so on.
*** Copy (3)
*** Copy (2)
*** Copy (1)

to avoid this: 
![image](https://user-images.githubusercontent.com/58026893/195523909-053dbf34-6898-490e-9be6-2b3288569343.png)

Many thanks!

**Comment by DannyDainton** [comment]
If you were to copy the `New Request Copy` Request, it would append the number to the name.

Unlike a file system, Collections/Requests can have the same name so it's not really a direct comparison. 😬

I'm going to close this issue for now.
