### ISSUE TITLE
Postman does not add the Authorization header when "Inherit auth from parent"

### ISSUE THREAD

**Issue by martinstenhoff** [a85/POSTMan-Chrome-Extension#11348]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Postman sometimes does not add the Authorization header with the bearer token for a request that has "Inherit auth from parent"

I can't recall ever having this issue with the 9.x version of the PostmanApp, but now with 10.x, more often than not Postman does not add the Authorization header to a request that has inherit auth.

If I then restart Postman then Postman will add the Authorization header.

How does Postman determine whether to add the bearer token in the Authorization header or not? It seems like it does some kind of check during startup and not at the time of issuing the request.

### Steps To Reproduce

See animated gif attached.

### Screenshots or Videos

![PostmanInheritAuth](https://user-images.githubusercontent.com/21321853/195081280-77e0aa50-1f66-4d34-825e-a0b8ad1c9151.gif)

### Operating System

Windows 11

### Postman Version

10.0.21

### Postman Platform

Postman App

**Comment by giridharvc7** [comment]
@c98 @martinstenhoff Thank you for reporting this issue. This is a bug we are tracking as a high priority, I will keep you posted here. 
In the meantime, to unblock yourself, can you try setting the initial value for the environment, save the environment and try sending the request?

**Comment by ahavensdaxko** [comment]
I can confirm this problem on my client also. Windows 10, Postman client v10.0.22. If I change my Authorization from Inherit auth from parent to explicitly providing the bearer token on that request it works.

**Comment by almesery** [comment]
i confirm this problem also

**Comment by cd-rite** [comment]
I think this may have something to do with the way Postman is resolving its environment variables.... But I can't get it to happen reliably. 
It seems to be truncating the Envvars I'm using to hold our bearer tokens when inheriting auth. It only includes a portion of the token, with an added ellipse....This also happens when hitting the "code" button for the curl version of the request. It even shows up when when exporting a collection for use with newman. It shouldn't even be resolving the variable at this point, but it seems to be. 
Here's a screenshot comparing an export with the previous version (last night) with an export after update (with no other relevant changes made by me) to show what I mean:

<img width="941" alt="image" src="https://user-images.githubusercontent.com/61710958/195213291-5b8da659-a986-4311-9557-6e4014a8c7b6.png">

**Comment by centur** [comment]
Same on MacOS, multiple collections with auth set up as inherit from parent are now broken. Console shows that Current value from selected environment is not replacing env var for Bearer token. Switching a specific call from inherit to the same value of Bearer token with env vars - and it works as expected:
<img width="1146" alt="image" src="https://user-images.githubusercontent.com/720822/195243962-6d592021-d06f-4b2c-a757-5f2daa766e8b.png">

Unfortunately, this is not an option to update all our calls and switch them from "inherit" to explicitly configured same Bearer token. Unnecessary work and 

I'm surprised how such critical blocking bug went past any reasonable testing. Could the latest version changes to be reverted and we can install somewhat functional app ?

OS: macOS Monterey 12.6 (21G115)
Postman Version 10.0.22
UI Version: 10.0.22-ui-221011-0439
Desktop Platform Version: 10.0.1 (10.0.1)

**Comment by giridharvc7** [comment]
@centur Apologies for the experience you are facing. We are working on this bug right now as we speak. I'll keep you posted as soon as we have a fix.

**Comment by giridharvc7** [comment]
We will have a fix in the next few hours, in the meantime, you can download v9.31 through this [page](https://www.postman.com/downloads/). @centur 

We will keep posting updates here as we have progress on the fix in v10.x

**Comment by vedkribhu** [comment]
@centur @martinstenhoff @ahavensdaxko this should be fixed now on 10.0.24. If you (restart your v10 app / reload your browser tab) you should have the fix.

**Comment by Wilhop** [comment]
Postman support asked me to check this issue. Our Basic auth token password was not getting Base64 encoded correctly, but instead the encoded password was just literal bullet signs "•••••••". The password value is defined in Environments.

In our case, updating 10.0.24 fixed the problem. The Authentication header now has the password encoded correctly.

**Comment by martinstenhoff** [comment]
It seems to be better with 10.0.24 now (it seems like it's at least evaluating the environment variable when executing the request), but it is confusing that the UI does not show the current value.
I believe this was the reason I once again, with 10.0.24, saw a missing Authorization header in the PostMan UI.

See attached. The accessToken variable has value "accessToken 2", but the UI shows "accessToken 1". The correct "accessToken 2" value is however sent in the request.

This issue seems to be covered by #11349 so we can close this Auth one. 

![PostmanDoesNotRefreshEnvValues](https://user-images.githubusercontent.com/21321853/195353175-67b5437f-c013-4046-85c9-fc57017f8389.gif)

**Comment by centur** [comment]
@vedkribhu  Can confirm it fixed our issue. Thanks for quick turnaround with this critical issue
