### ISSUE TITLE
Code snippet support Rust ?

### ISSUE THREAD

**Issue by supertrouper** [a85/POSTMan-Chrome-Extension#11340]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

Can code snippets support the Rust language?

### Describe the solution you'd like

Can code snippets support the Rust language?

**Comment by akshaydeo** [comment]
Related https://github.com/postmanlabs/postman-code-generators/issues/192

**Comment by dhwaneetbhatt** [comment]
We've added support for generating Rust code snippets using `reqwest` library in the latest version (v10.13) of Postman. Please feel free to try out this feature. Please provide us feedback on either this repository or feel free to contribute directly via issues/PR on [postman-code-generators](https://github.com/postmanlabs/postman-code-generators) repository for the code snippet feature.
