### ISSUE TITLE
Postman adds unwanted cookie headers automatically

### ISSUE THREAD

**Issue by jbauerrfid** [a85/POSTMan-Chrome-Extension#11358]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Postman collects cookies from previous requests and adds them to subsequent requests.

The only way to prevent this and simulate a fresh session is to go to cookies section and remove all the cookies manually.

Expected behavior:

* Postman should have setting to disable collecting cookies automatically.
* When I need a cookie, I can still extract it from the response headers with a test script, and store it in the environment. Then it is easy to add the cookie to new requests from environment.

### Steps To Reproduce

Run a request which returns a cookie.
Run the same request again.
The first and second requests are not equal, because the second time the cookie header is included.

### Operating System

Windows

### Postman Version

10.0.25

### Postman Platform

Postman App

**Comment by shubhbhargav** [comment]
Hey @jbauerrfid , this is an expected behaviour to ensure that the requests sent to the same domain can share cookies. In-case you would like to disable it, you can follow these steps:

1. Open the request in question and go to the `Settings`
2. Turn `On` the `Disable Cookie Jar` setting

Let us know if this works for you.

**Comment by DannyDainton** [comment]
Hey @jbauerrfid 

Closing this issue, for now, please let us know if the solution provided doesn't work for you.

**Comment by cantonalex** [comment]
> Hey [@jbauerrfid](https://github.com/jbauerrfid) , this is an expected behaviour to ensure that the requests sent to the same domain can share cookies. In-case you would like to disable it, you can follow these steps:
> 
> 1. Open the request in question and go to the `Settings`
> 2. Turn `On` the `Disable Cookie Jar` setting
> 
> Let us know if this works for you.

Still does it when you do this
