### ISSUE TITLE
Import ignoring description from OAS3

### ISSUE THREAD

**Issue by chepa92** [a85/POSTMan-Chrome-Extension#11356]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

![image](https://user-images.githubusercontent.com/31892489/195379017-108fc673-e422-4b07-a4f5-1051c41a37e1.png)
as wrote here it's will take description to name request and this isn't working, opened same request for converter, this should fix this bug.
[https://github.com/postmanlabs/openapi-to-postman/pull/632](url)

### Steps To Reproduce

import schema OAS3 with description field, change in advanced settings Named Request to Fallback, after import you got "path" name and not description.

### Operating System

Windows

### Postman Version

9.31.19

### Postman Platform

Both

**Comment by akshaydeo** [comment]
@chepa92, thank you so much for reporting this bug and sending the PR across. 

We will evaluate the fix and update this ticket as soon as possible. 🙇‍♂️

**Comment by chepa92** [comment]
any news?

**Comment by akshaydeo** [comment]
@chepa92, the fix is ready, and we will be shipping this in the second week of Jan 2023. Thanks for your patience 🙇‍♂

**Comment by SahilChoudhary22** [comment]
@chepa92 This fix was shipped with the version v10.8.0 of the Postman. The description field should now be imported as expected 👍 
cc : @akshaydeo

**Comment by axellejamous** [comment]
Hello, I am writing this reply as I am currently still experiencing this issue. Postman is on version 10.14.8. 
Parameter descriptions are working fine, but body parameter descriptions are still being ignored.
