### ISSUE TITLE
gRPC Collection - After duplicating and renaming request name is still wrong

### ISSUE THREAD

**Issue by uschwag** [a85/POSTMan-Chrome-Extension#11355]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

After duplicating and renaming of a gRPC request the old name is still displayed.
After a restart of the application the right name appears.

### Steps To Reproduce

1. Open a gRPC Collection with requests
2. Duplicate a request, it gets the same name as original (here ListCountries)
3. Rename the request either in Explorer or on request itself (here to Newname)
4. The new name is not displayed on request itself

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/91600653/195363308-698d5761-6e0f-4ce8-95b5-6f092028e545.png)

### Operating System

Windows 10

### Postman Version

10.0.25

### Postman Platform

Postman App

**Comment by codenirvana** [comment]
@uschwag Thanks for reporting this issue. We'll fix this soon.

**Comment by appurva21** [comment]
@uschwag This issue is fixed with the latest release of Postman. Feel free to reach out in case you are still facing any problems.

**Comment by uschwag** [comment]
Thanks a lot for fixing, it works now as expected.
