### ISSUE TITLE
Inherited authentication referencing a secret variable is not added to requests properly

### ISSUE THREAD

**Issue by mamjong** [a85/POSTMan-Chrome-Extension#11352]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

When I add an authorization method to a collection, which references a secret variable from an environment, the value of the variable is not added properly to the request. For example, when using basic auth the base64 decoded authorization header is "username:•••••••". Somehow the literal character used for hiding the value of the secret is added to the request, instead of the actual value.

### Steps To Reproduce

1. Add a secret variable to an environment containing an authorization value.
2. Create a collection with an authorization method referencing the secret.
3. Create a request which inherits its authentication from the collection.
4. Execute the request

### Operating System

Windows

### Postman Version

10.0.20

### Postman Platform

Postman App

### Additional Context?

I use Postman on different devices, so the issue might be related to the synchronisation of secrets between devices.
It might only occur when I use the secret on a different devices from the device where I added it to the environment, but I am not sure.

I started having this issue after upgrading to version 10.0.20.
I had the environments, collections and requests setup on a previous version.

**Comment by giridharvc7** [comment]
Hey @mamjong , we are tracking this in #11348 . Please restart the app for the update and try the flow and let us know if works for you. Closing this for now

**Comment by mamjong** [comment]
Yep, seems to be fixed in patch 10.0.24. Thank you.
