### ISSUE TITLE
Could not directly change default header setting

### ISSUE THREAD

**Issue by jessemoe** [a85/POSTMan-Chrome-Extension#11351]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Could not directly change default header setting

### Steps To Reproduce

1.open a new request tab

### Operating System

windows

### Postman Version

9.14.0

### Postman Platform

Postman App

### Additional Context?

Could not directly change default header setting

**Comment by DannyDainton** [comment]
Hey @nocsg

Without more context and examples of what you're trying to do, its going to be difficult to move this forward.

Please provide additional information to help us understand the issue.

**Comment by DannyDainton** [comment]
Closing this issue, we can revisit this if more information is provided.
