### ISSUE TITLE
Postman is not using system proxy (ubuntu)

### ISSUE THREAD

**Issue by jasco-b** [a85/POSTMan-Chrome-Extension#11369]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Postman is not using system proxy for getting available workspace (collections, environments and others).
I even added proxy to postman setting but no luck

### Steps To Reproduce

set proxy to ubuntu.
use wired connection.
open postman.
Postman will not use proxy

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/12882799/196614222-ee618f6e-d604-4319-b2e2-3dbc9e7a8a65.png)
![image](https://user-images.githubusercontent.com/12882799/196614326-0770ba33-792c-44f3-948e-8dc8d9b72725.png)

### Operating System

linux ubuntu

### Postman Version

9.31.21

### Postman Platform

Postman App

**Comment by jviotti** [comment]
Hi @jasco-b , thanks for reporting!

I believe this is an upstream issue from Electron and Node.js not respecting system proxies by default. @dsanders11 @RaisinTen Can you confirm? Are they tracking this anywhere?

**Comment by RaisinTen** [comment]
@jviotti I'm not aware of any such upstream issue in Node.js but I found an Electron issue that might have some relevance here - https://github.com/electron/electron/issues/26166. For this I would ask - How consistent is the issue? Does it go away after some time?

@jasco-b did you go through https://learning.postman.com/docs/getting-started/proxy? If not, I'd suggest you to go through that and let us know if that resolves this issue.

**Comment by tony-go** [comment]
Hey @jasco-b 

It’s been a while since we last heard from you, so we’re going to close this issue for now.

If this is still a problem or you have more information to share, feel free to reopen the issue, and we’ll be happy to help.

Thank you for your time and for being part of Postman community! 😊
