### ISSUE TITLE
gRPC not working remotely

### ISSUE THREAD

**Issue by vpetreski** [a85/POSTMan-Chrome-Extension#11364]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Postman works correctly on local with gRPC, but not working when I try to use it on my remote gRPC server, reflection and method calls doesn't work at all.

When try to use reflection getting this:

```
Could not load server reflection.
Details: 13 INTERNAL: Received RST_STREAM with code 2 triggered by internal client error: Protocol error
```

If I add protofile and attempt to invoke method, I get the same ^ error.

### Steps To Reproduce

1. Open a new gRPC request tab
2. Add remote server
3. Try to use reflection > ERROR
4. Add protofile manually
5. Try to invoke method > same ERROR

### Operating System

macOS

### Postman Version

10.0.30

### Postman Platform

Postman App

### Additional Context?

Well, my gRPC server is deployed on AWS it's behind ALB and deployed to ECS cluster. I tried to use grpcurl tool and it works without any issue, so it's not up to my setup, it's postman thing. If you need more info please let me know. Thanks!

**Comment by codenirvana** [comment]
@vpetreski, is it a TLS server? If so, try enabling TLS (lock icon).

<img width="354" alt="Screenshot 2022-10-15 at 11 18 17 PM" src="https://user-images.githubusercontent.com/4865836/196000857-c3bb4e1d-126f-4803-a7dd-7d51346428a5.png">

**Comment by vpetreski** [comment]
> @vpetreski, is it a TLS server? If so, try enabling TLS (lock icon).
> 
> <img alt="Screenshot 2022-10-15 at 11 18 17 PM" width="354" src="https://user-images.githubusercontent.com/4865836/196000857-c3bb4e1d-126f-4803-a7dd-7d51346428a5.png">

Yes it is, THANK YOU WORKS LIKE A CHARM!
