### ISSUE TITLE
Should not have a 'bearerformat' property without 'scheme: bearer' being set

### ISSUE THREAD

**Issue by OFark** [a85/POSTMan-Chrome-Extension#11363]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

When importing a Swagger OAS3 json file I get the syntax error:
`Should not have a 'bearerformat' property without 'scheme: bearer' being set`
Even when the Scheme Bearer is set. 

If I change the `"scheme": "Bearer"` to `"scheme": "bearer"` (lower case B) then Postman is happy, but the [schema definition](https://www.iana.org/assignments/http-authschemes/http-authschemes.xhtml) says it should be "Bearer".

### Steps To Reproduce

Import JSON from Swagger OAS3, although I suspect if you write out your own definition it would still have the same problem .

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/4558132/195981587-033645c5-77e0-46a1-ad15-8d6b0828829f.png)

### Operating System

Windows

### Postman Version

10.0.29

### Postman Platform

Postman App

**Comment by OFark** [comment]
Slightly more research says it should be case-insensitive: https://www.rfc-editor.org/rfc/rfc7235#section-2.1

**Comment by srinivasskc** [comment]
I have also encountered this, not sure what I need to do.

**Comment by OFark** [comment]
just change the "scheme": "Bearer" to bearer for now.

**Comment by VShingala** [comment]
@OFark @srinivasskc We have fixed this issue with the latest version of Postman app (v10.8). Have also attached screenshot with the mentioned case for reference.

![image](https://user-images.githubusercontent.com/16756296/214486068-fc82a8d4-78c0-44ea-8e10-d0d35b59da12.png)
