### ISSUE TITLE
Error: Client network socket disconnected before secure TLS connection was established

### ISSUE THREAD

**Issue by moellrich** [a85/POSTMan-Chrome-Extension#11371]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Yesterday everything was running. The web version of postman shows me as well that it works.

Since today I get the error message "Error: Client network socket disconnected before secure TLS connection was established" in Postman.
I updated it. I reinstalled it. I checked SSL settings, Proxy settings and Certificates. Nothing worked.
Even if I switch to "http" instead of "https" I receive strange responses like the following HTML:
```
<html>
<head>
	<title>404 Not Found</title>
</head>
<body>
	<center>
		<h1>404 Not Found</h1>
	</center>
	<hr>
	<center>nginx</center>
</body>
</html>
```

If I try Chrome and use the same GET requests, I get a 403 error, which is the correct answer because I can not sent Authentication-Information in the header via Chrome.

Looks like Postman lost the ability to connect the server.

### Steps To Reproduce

I have no idea. Very strange behaviour.

### Operating System

Windows

### Postman Version

10.0.32

### Postman Platform

Postman App

### Additional Context?

I can not guarantee that it was this way but:
I switched two requests from PUT to PATCH. 
Yesterday with PUT everything worked. I am not sure, if I tried it today too. But after I used PATCH, I always receive those strange responses.

**Comment by postman-staff** [comment]
Hey hi,
Thank you for reaching out.

Are you using VPN/proxy or some corporate device management software? If so, would you please try disabling those and see if there is any change in the behaviour? Also, can you please try using another network such as your mobile hotspot in order to validate if this is a network-related issue?

May I ask if you can leverage the Code generation feature(https://learning.postman.com/docs/sending-requests/generate-code-snippets/#generating-code-snippets-in-postman)  to generate a cURL request and try making that cURL request from your terminal and see if that works? If the same issue occurs, then it isn't a postman-specific issue but could be the server itself.

You can find more details the below doc:
https://support.postman.com/hc/en-us/articles/5876726657943-Fixing-the-error-Client-network-socket-disconnected-before-secure-TLS-connection-was-established

via @Lincimary | Postman Support

**Comment by moellrich** [comment]
Hi,

 

I do not use VPN or a proxy or something similar.

As I wrote: In the evening of the 18th of October it still worked.

 

It is not the server because:

1.	A colleague of me can reach it from his computer.
2.	I can reach it too, if I use the webversion of postman from my computer.

 

I use it on a Windows 10 machine, so I was not able to use your cUrl-test example.

 

Any further ideas?

 

Best regards

 

 

Dr.-Ing. Marc Oellrich

 

www.oellrich-solutions.de <https://www.oellrich-solutions.de/>  – Die Steigerung Ihrer Effizienz ist unser Ziel

 

Oellrich Solutions UG (haftungsbeschränkt)

Hagebuttenweg 13, 38518 Gifhorn
Handelsregisternummer: HRB 205709 | Amtsgericht: Hildesheim | Geschäftsführer: Dr.-Ing. Marc Oellrich

 

Von: Postman Support ***@***.***> 
Gesendet: Donnerstag, 20. Oktober 2022 13:47
An: postmanlabs/postman-app-support ***@***.***>
Cc: Marc Oellrich ***@***.***>; Author ***@***.***>
Betreff: Re: [postmanlabs/postman-app-support] Error: Client network socket disconnected before secure TLS connection was established (Issue #11371)

 

Hey hi,
Thank you for reaching out.

Are you using VPN/proxy or some corporate device management software? If so, would you please try disabling those and see if there is any change in the behaviour? Also, can you please try using another network such as your mobile hotspot in order to validate if this is a network-related issue?

May I ask if you can leverage the Code generation feature(https://learning.postman.com/docs/sending-requests/generate-code-snippets/#generating-code-snippets-in-postman) to generate a cURL request and try making that cURL request from your terminal and see if that works? If the same issue occurs, then it isn't a postman-specific issue but could be the server itself.

You can find more details the below doc:
https://support.postman.com/hc/en-us/articles/5876726657943-Fixing-the-error-Client-network-socket-disconnected-before-secure-TLS-connection-was-established

via @Lincimary <https://github.com/Lincimary>  | Postman Support

**Comment by postman-staff** [comment]
Hey hi,

Could you please provide me the screenshot of the proxy settings in the postman app along with the error message?
Let me know if you have made any recent changes to our DNS settings/network settings?

Can you try turning off the SSL verification on the postman app and check once?

If the problem persists, Can you try running our Canary build to see if this is working as expected? The Canary build will be installed in an entirely separate app/directory.
Postman Canary – https://www.postman.com/downloads/canary/

Looking forward to your response.

via @Lincimary | Postman Support

**Comment by moellrich** [comment]
Sorry for my late response.

I was on holidays.

I just opened Postman again, tried it out and everything works. I have no idea what might have changed. (Restarting Postman I tried before…).

 

As a friend once said: In theory there is only 1 and 0, but in reality there is something in between and that gets you into trouble. 😉

 

Best regards

 

 

Dr.-Ing. Marc Oellrich

 

www.oellrich-solutions.de <https://www.oellrich-solutions.de/>  – Die Steigerung Ihrer Effizienz ist unser Ziel

 

Oellrich Solutions UG (haftungsbeschränkt)

Hagebuttenweg 13, 38518 Gifhorn
Handelsregisternummer: HRB 205709 | Amtsgericht: Hildesheim | Geschäftsführer: Dr.-Ing. Marc Oellrich

 

Von: Postman Support ***@***.***> 
Gesendet: Freitag, 21. Oktober 2022 06:41
An: postmanlabs/postman-app-support ***@***.***>
Cc: Marc Oellrich ***@***.***>; Author ***@***.***>
Betreff: Re: [postmanlabs/postman-app-support] Error: Client network socket disconnected before secure TLS connection was established (Issue #11371)

 

Hey hi,

Could you please provide me the screenshot of the proxy settings in the postman app along with the error message?
Let me know if you have made any recent changes to our DNS settings/network settings?

Can you try turning off the SSL verification on the postman app and check once?

If the problem persists, Can you try running our Canary build to see if this is working as expected? The Canary build will be installed in an entirely separate app/directory.
Postman Canary – https://www.postman.com/downloads/canary/

Looking forward to your response.

via @Lincimary <https://github.com/Lincimary>  | Postman Support

**Comment by postman-staff** [comment]
Hi hello,

Glad that everything is working fine now. In the future, if the same issue occurs and you wanna get help just respond to this ticket to re-open it.

As of now I'm going ahead and closing this conversation but please feel free to reach out again later if you need any other assistance!

Thank you for contacting Postman support.
Have a great day:)

via @Lincimary | Postman Support

**Comment by harshali-mankar** [comment]
Client network socket disconnected before secure TLS connection was established
i get this error when im trying to check my endpoint in postman

**Comment by harshali-mankar** [comment]
![postman](https://github.com/user-attachments/assets/019c9499-de05-465d-808b-0d13230a61a8)
Please any one can tell what is the issue
