### ISSUE TITLE
Show more granular requests times in Mock Server logs

### ISSUE THREAD

**Issue by tomliversidge** [a85/POSTMan-Chrome-Extension#11379]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

The Mock Server logs UI currently displays the requests times in hours:minutes. This makes it difficult to verify/test the exact time that requests were made to the mock endpoints. 
<img width="265" alt="CleanShot 2022-10-21 at 13 02 11@2x" src="https://user-images.githubusercontent.com/1437372/197170161-bd03b507-8ceb-4c23-87b9-4208b9eb6cbb.png">

### Describe the solution you'd like

I would like to be able to see at a minimum the seconds that requests have been sent in the Mock Server logs. Ideally it would be a full UTC timestamp include seconds and milliseconds

**Comment by shikhar-codes** [comment]
Hey @tomliversidge , thanks for this ask. We have made this change available in the latest version. We can now see the time in hours:minutes:seconds format as shown in below screenshot. 🎉 

![image](https://github.com/postmanlabs/postman-app-support/assets/53982388/e908f5bd-45f5-4f01-8c3c-df2411133489)
