### ISSUE TITLE
Visiting a Public Workspace

### ISSUE THREAD

**Issue by lavasb** [a85/POSTMan-Chrome-Extension#11378]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

I wonder why if someone visits a public work space, he or she cannot remove it from his or her workspace?  

### Describe the solution you'd like

I have visited two public work spaces Tray.io Embedded APIs (GraphQL) and Withings Health Solutions.  Every time I login to Postman, these two gets populated to my postman profile and I cannot remove them.  I should be able to remove them but that option is not available.   

### Describe alternatives you've considered

People should be able to delete public work spaces they visited from their profile.  

### Additional context

People should be able to delete public work spaces they visited from their profile.

**Comment by akshay-kulkarni03** [comment]
Hi @lavasb we already have an issue open for this: https://github.com/postmanlabs/postman-app-support/issues/10852

We are already working on improving the workspace switcher experience.
Can we close this and follow the above one for updates?
