### ISSUE TITLE
NTLM Authentication

### ISSUE THREAD

**Issue by letshan** [a85/POSTMan-Chrome-Extension#1137]
Hi guys,

We are developing APIs for internal usage, which based on Microsoft Authentication/Authorization methodology, which is NTLM. Just wondering could you add a new tab on the authentication options as NTLM?

I found this article about NTLM is quite useful if you would like to have a look.
http://www.innovation.ch/personal/ronald/ntlm.html

Regards,

Dan

**Comment by fuksito** [comment]
Would love to have it as well

**Comment by peteski22** [comment]
Negotiate/NTLM would be a massive plus for testing with Postman.

**Comment by henriale** [comment]
+1

**Comment by jeffzmartin** [comment]
This would be great to have

**Comment by peteski22** [comment]
It seems if you use Chrome first it will negotiate etc and postman will use these settings after.. Still would be nice if it was explicit in Postman

**Comment by chief-nerd** [comment]
+1

**Comment by RonakThakkar** [comment]
+1

**Comment by hkrug** [comment]
+1

**Comment by giuliocaccin** [comment]
+1

**Comment by klabbe** [comment]
+1

**Comment by loedeman** [comment]
+1

**Comment by mikedevita** [comment]
:+1:

**Comment by BandoKal** [comment]
+1

**Comment by jaredcnance** [comment]
+1

**Comment by CrannaA** [comment]
It would be great if this were added in such a way that Newman could also use NTLM.

**Comment by tpaivaa** [comment]
+1

**Comment by ChrissiFi** [comment]
+1

**Comment by redkhalil** [comment]
+1
Any update on this? I tried to login via Chrome first but it's not working. Right now I'm left to using curl.

**Comment by guilhermeando** [comment]
+1

**Comment by ChrissiFi** [comment]
I'm working on other projects at the moment so unable to return to this for
a while but maybe you can follow this up with Guilherme who says he's
seeing the same thing?

**Comment by rkilcoyne** [comment]
+1

**Comment by tpkelly** [comment]
+1 especially for Newman support

**Comment by geraldchecka** [comment]
+1
Desperately need this feature to test one of my service.

**Comment by Moulde** [comment]
+1

**Comment by KennethScott** [comment]
+1

**Comment by Gladskih** [comment]
'must have' feature! I've been surprised it's not available in the app.

**Comment by vasko77** [comment]
This feature is absolutely necessary

**Comment by DavidTNguyen** [comment]
+1

**Comment by kccarter76** [comment]
+1

feature is an absolute necessity for testing web api calls in a intranet environment

**Comment by abvincita** [comment]
+1!

**Comment by jimonthebarn** [comment]
+1

**Comment by jimior2** [comment]
+1

**Comment by cvietor** [comment]
+1

**Comment by ChrisBDFA** [comment]
+1

**Comment by thtp** [comment]
+1

**Comment by JacobHansen89** [comment]
+1

**Comment by phriedel** [comment]
+1

**Comment by normanhh3** [comment]
+1

**Comment by Spiralis** [comment]
+1

**Comment by r998877** [comment]
Re-using Chrome's NTLM session worked in the past. But with one of the latest updates it doesn't work anymore.

**Comment by alaczi** [comment]
+1

**Comment by anujbahuguna** [comment]
Chrome's NTLM is no longer working with Postman after latest upgrade of chrome :(

**Comment by justinthings** [comment]
+1

**Comment by evilC** [comment]
A little update on the / Chrome NTLM issue:
Using this version of Postman seems to work with the latest chrome: https://chrome.google.com/webstore/detail/postman-launcher/igofndmniooofoabmmpfonmdnhgchoka?utm_source=chrome-ntp-icon

**Comment by Swazimodo** [comment]
@evilC  this workaround works but I wish there was a way to do this in the packaged version of this app

**Comment by willemdupreez** [comment]
This is the only thing stopping me from using this this app. Shame really.

**Comment by w1ndblow** [comment]
+1

**Comment by ovstetun** [comment]
+1 Need to be able to login using NTLM/STS/ADFS in standalone app

**Comment by CH4NCE** [comment]
+1

**Comment by fragilerus** [comment]
+1
Used to work if I hit the url first from chrome (very annoying). That no longer works :(. I'm back to using curl

**Comment by Crimscent** [comment]
+1

**Comment by cskiwi** [comment]
+1

**Comment by huntmj01** [comment]
+1

**Comment by marcoruval** [comment]
+1

**Comment by TrevorPilley** [comment]
+1

**Comment by Ryanman** [comment]
+1 - Particularly galling since the Chrome plugin functions as other people have mentioned.

Great app though!

**Comment by daBONDi** [comment]
+1

**Comment by scdba** [comment]
+1

**Comment by johnmckay-reward** [comment]
+1

**Comment by RobbyDeLaet** [comment]
+1

**Comment by Voxis** [comment]
+1

**Comment by a85** [comment]
All, we'll make our roadmap about authorization options public soon. Lots of work has gone into the underlying Postman layers to make this possible and we are working on the UI layer now.

**Comment by jarvisuser90** [comment]
+1

**Comment by NielsGregers** [comment]
+1

**Comment by swisscoder** [comment]
+1 
=> as the chrome app will not live forever this becomes more important! Please build it into the Windows App.

**Comment by ThatRendle** [comment]
Why are people still posting `+1` comments on GitHub? There are buttons for that that are much easier for repo owners to engage with.

**Comment by Spiralis** [comment]
@markrendle Where are the buttons to use for this?

**Comment by GordonBeeming** [comment]
@Spiralis it's on the top right of the comment 👍

**Comment by Spiralis** [comment]
@Gordon-Beeming, Ah of course... I somehow never thought of the comment-reactions being used as a response to the thread/issue itself. But I guess comment-reactions to the issue-starter comment could be used to count response, yes.

**Comment by javaman21011** [comment]
So is this thread the reason why PostMan standalone and Chrome app keeps giving me this error?

HTTP Error 401.2 - Unauthorized
You are not authorized to view this page due to invalid authentication headers.

**Comment by fonbrauzen** [comment]
as a workaround:
With Interceptor plugin installed on Chrome and enabled in Postman chrome app NTLM cookies used from Chrome

**Comment by amadeobrands** [comment]
+1

**Comment by GuilhermeMatheus** [comment]
+1

**Comment by Vaccano** [comment]
+1

**Comment by kugaevsky** [comment]
+1

**Comment by nusairi** [comment]
Is there any news about adding NTLM since this post?

**Comment by sdnts** [comment]
We're going to take a look at a more generalized helper for authentication very soon. Will take this up as part of that :)

**Comment by Vaccano** [comment]
@madebysid Excellent!

**Comment by RobbyDeLaet** [comment]
@madebysid Excellent news indeed!

**Comment by yashwanthreddyg** [comment]
+1

**Comment by Mah3** [comment]
+1

**Comment by Spharah** [comment]
+1

**Comment by rajparmar** [comment]
+1

**Comment by toburger** [comment]
+1

**Comment by samayamantri** [comment]
+1

**Comment by coderjoe** [comment]
So I was having this problem using the Chrome App installed from the web store (not bundled native app). Then I installed "Postman Interceptor" and turned it on. Now all of a sudden NTLM auth is working... wat happen? 😮

**Comment by sdnts** [comment]
@coderjoe When you use the interceptor, all requests are sent via the Chrome browser instance you launched the app from. You might have had cookies there that allow you to login to your service.

**Comment by coderjoe** [comment]
@madebysid ah that makes perfect sense. Thanks for helping clear up my confusion. I guess this is a partial workaround for me then. :)

**Comment by aumanjoa** [comment]
+1

**Comment by oferze** [comment]
All of you writing +1 haven't obviously read [this comment](https://github.com/postmanlabs/postman-app-support/issues/1137#issuecomment-250112777)...

**Comment by yuri-martynov** [comment]
+1

**Comment by KozhevnikovDmitry** [comment]
+1

**Comment by ghost** [comment]
+1...this would be really nice to have for testing our internal-use API's!

**Comment by oferze** [comment]
@yuri-martynov @KozhevnikovDmitry @Stealth22 you're trolling right? :)

**Comment by Voxis** [comment]
@oferze probably not I guess :). see when I get into this thread and I see a lot of +1s I would want to add a comment "+1" to support this idea as I did. It could be a "sad" move from some people's perspective. It is totally fine from my perspective, however.

But in the end, no one should tell others what to do what not to do. "Oh you should jump off the bus at this stop not that one so you walk 10 seconds less (you stubborn), why don't you use google map first, you have your phone right?"... **no offense** btw. People are too busy. They just do it. 

The reality is nobody cares lol. We need this great feature added to Postman. ~Why so serious~

**Comment by oferze** [comment]
@Voxis nice psychological observation! Including the _nobody cares lol_. Quote from Metallica: Sad But True.

I guess GitHub wasted their time developing this feature in response to users saying "It's better to aggregate support signals for tickets rather than having eveyone +1'ing like it's a social network"

**Comment by zhrastic** [comment]
+1

**Comment by lynndotconfig** [comment]
+1

**Comment by schmosef** [comment]
+1

**Comment by ghost** [comment]
Quit it with the "+1"s! [Read!](https://github.com/postmanlabs/postman-app-support/issues/1137#issuecomment-250112777)...

**Comment by oferze** [comment]
@rajparmar they have also not read [that](https://github.com/postmanlabs/postman-app-support/issues/1137#issuecomment-279258164). People see an issue and they don't scroll through to see what the state of it is. Just going to the bottom like on Facebook and writing their own +1.

**Comment by coderjoe** [comment]
@oferze it also doesn't help that the feature isn't visible on all platforms.

**Comment by chiragsheta** [comment]
+1

**Comment by fabiante** [comment]
+1

**Comment by prakash-patel** [comment]
+1

**Comment by pagex** [comment]
+1

**Comment by valorl** [comment]
+1

**Comment by dvdtoth** [comment]
+1

**Comment by oferze** [comment]
All of you who are still following this thread (either by reading through it or by just adding another +1 comment instead of marking your vote on the original issue comment), if you want NTLM now there's a tool that's highly competitive to Postman and has this feature: [Insomnia](https://insomnia.rest/).

**Comment by pajics** [comment]
Workaround:
I got this working by running Fiddler first.

Run Fiddler (I'm using 4.6.2.3)
Fiddler Menu: Rule -> Automatically Authenticate = true
Postman: Check that Authorization type = No Auth
Browse api.


https://stackoverflow.com/questions/37341304/pass-ntlm-with-postman

**Comment by rothschild86** [comment]
+1

**Comment by dblock247** [comment]
+1

**Comment by ghiscoding** [comment]
@pajics thanks for the workaround, however it seems that I need `Fiddler` to be opened at all time for `Postman` to work. Is there a workaround for that? My coworker only did it once and doesn't need `Fiddler` at all anymore, but on my side I need all the time :(

**Comment by Snickbrack** [comment]
how things going? Update?

**Comment by drmcclelland** [comment]
+1

**Comment by ciscosupport** [comment]
Leading networking company CISCO launched a service called CISCO SUPPORT service to help its users and it also have a toll free number to provide instant help.
For any problem regarding networking go to 


http://supportnumbers.net/

**Comment by ciscosupport** [comment]
CISCO launched a service called CISCO SUPPORT service to help its users and it also have a toll free number to provide instant help.
For any problem regarding networking go to 

<a href="http://supportnumbers.net/"> Cisco Support</a>

**Comment by pajics** [comment]
@ghiscoding this works as well:
https://sysadminspot.com/windows/google-chrome-and-ntlm-auto-logon-using-windows-authentication/

**Comment by ghiscoding** [comment]
@pajics thanks, that did actually worked :)

For anyone else having similar issues, here's what I did to fix it on my side. Go into the internet security settings and add `http://localhost` (or whatever your endpoint is) as a trusted site, then click on "custom levels" and change the "User Authentication" to "Automatic logon with current user name and password". See below for print screen of what I changed

![trusted_sites](https://user-images.githubusercontent.com/643976/27844012-721ea17c-60e9-11e7-85e8-293420e5665e.png)
![automatic_logon](https://user-images.githubusercontent.com/643976/27844013-7a80ff7c-60e9-11e7-96cd-c876ced9573b.png)

**Comment by RobbyDeLaet** [comment]
Come on guys, be serious for a moment. We are requesting ntlm authentication for 2 (TWO) years now. At the moment I'm forced to use Insomnia because they support ntlm. When is Postman finally going to do something about this issue.

As a consultant I work with clients that only support Windows Authentication, making Postman a useless tool.

**Comment by AndreySurzhan** [comment]
+1

**Comment by lewis-hu** [comment]
4 years and counting.

**Comment by DerekHackett** [comment]
+1

**Comment by rasik210** [comment]
+1

**Comment by Alex-Torres** [comment]
+1

**Comment by Moily** [comment]
Can we be given an ETA for this feature, at the very least?  It would be great to be able to return to Postman.

**Comment by RobbyDeLaet** [comment]
I have contacted support and they promised NTLM authentication in the mid-end October release (this year).

I would have liked that someone from Postman made this reply though.

**Comment by harryi3t** [comment]
The [PR for NTLM](https://github.com/postmanlabs/postman-runtime/pull/390) is merged in runtime
This will be released with Postman 5.3 🎉

**Comment by harryi3t** [comment]
Hi, everyone

Postman 5.3.0 is out with support for NTLM!
Can someone please confirm that this is working as expected?

Thanks

**Comment by RobbyDeLaet** [comment]
A test with a WorkstationID on my personal PC works fine.
I will test with a Domain account asap. I have to request a software update on my clients PC (which can take some time).

**Comment by FelixBoers** [comment]
Works as expected on Windows 10! 
Thanks for this awesome feature. I've waited for this so long!

**Comment by harryi3t** [comment]
Thank you @flex87 and @RobbyDeLaet for confirming the fix and thank you for your patience.
Closing this.

**Comment by fonbrauzen** [comment]
Hmm, I saw this Beta NTLM Auth after release, but now it's gone somehow. Have you changed something?

**Comment by sdnts** [comment]
@fonbrauzen You might have accidentally switched to the Chrome app, NTLM is supported only on native apps for now.

**Comment by bennymeade** [comment]
@harryi3t / Everyone fantastic addition. 

With this NTLM Beta version, should the extracted RestSharp code work in Visual Studio? 
Because in VS I still get "Unauthorized".

(edit) SOLUTION:
using RestSharp.Authenticators;

RestClient client = new RestClient(_baseURL);
client.Authenticator = new NtlmAuthenticator();

**Comment by harryi3t** [comment]
@bennymeade I am afraid that this is not supported yet. 
Generating code snippets only works with simple information like `URL` and `headers`, etc
Currently, it does not take the `authentication` into account.

Please open a new issue for this as a feature request.

**Comment by bennymeade** [comment]
@harryi3t No need for a new issue, it is working.

Once I added client.Authenticator = new NtlmAuthenticator(string username, string password);  to my VS RestSharp project.

**Comment by ikrasnopeev** [comment]
Worked for me in 5.3.2, but stopped working in 5.4.1 and 5.5.0.

In my scenario I'm switching different users during same collection run, e.g.:
loginAsUser1
doSomething1
loginAsUser2
doSomething2
loginAsUser1
doSomething3

NTLM auth scheme is used.
In 5.3.2 I was able to do this by adding fake logins using BASIC auth requests.

So effectively loginAsUserN actually was 2 requests:
loginAsUserN-1 - used BASIC auth
loginAsUserN-2 - used NTLM auth

In 5.3.2 those 2 "UI" requests were effectively shown as 4 request in Postman Console:
1 - Req: authorization:"Basic...
1 - Resp: 401 www-authenticate: NTLM
2 - Req: no authorization header
2 - Resp: 401 www-authenticate: NTLM
3 - Req: authorization: "NTLM {short string}"
3 - Resp: 401 www-authenticate: "NTLM {long string}"
4 - Req: authorization: "NTLM {long string}"
4 - Resp: 200

It looks like in 5.3.2 1st (basic auth) request helps Postman (server???) to forget NTLM session(?) and whole NTLM handshake is triggered from the beginning.
But again - this is working like a charm in 5.3.2.

In 5.4.1 and 5.5.0 it is broken:
1st "loginAsUser1" still is resolved in 4 requests in Postman Console (same as I shown above)

loginAsUser2 is resolved into 3 requests: 1,3 and 4 of above - looks like Postman remembers server will require NTLM so it sends "authorization: "NTLM {short string}"" right away. But this still works for server, so 200 is returned as result of 4th request.

What does not work is my 2nd "loginAsUser1". According to Postman console only 1 and 4 above request are sent: seems like Postman remembers it already did NTML for user1, so it immediately sends "NTLM {long string}" it used in 1st "loginAsUser1" sequence omitting whole NTML handshake sequence. Server doesn't like such approach and returns 401 instead of 200.

Downgraded to 5.3.2 for now. Any way to restore 5.3.2 NTML functionality? I understand that my usecase might be unusual, but maybe make this behavior configurable?

Thanks!

**Comment by sonichanxiao** [comment]
I tried in v6.1.3, doesn't work with SharePoint 2010 hosted Web API services for a GET action, always return 401, have provided domain\username and password

**Comment by harryi3t** [comment]
@sonichanxiao This might be related to the issue https://github.com/postmanlabs/postman-app-support/issues/4711

**Comment by vasavijambula** [comment]
I am having issues with NTLM authentication using postman version 5.3.2?.

Can someone confirm the version of postman where  NTLM is working?

**Comment by s3YwCf2ZbfJG4SHAfjQMAjtsf** [comment]
I tried the NTLM option within Postman and couldn't get it to work.   Using Fiddler Classic in the background with Automatically Authenticate, I could test NTLM situations.
