### ISSUE TITLE
Authorization header uses ••••••• when inheriting

### ISSUE THREAD

**Issue by alee-mt** [a85/POSTMan-Chrome-Extension#11373]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

It looks like inherited authorization of type secret is using the masked character/string `•••••••` as a value. Context and steps to reproduce below.

### Steps To Reproduce

How I'm reproducing this on my own instance:
* Have a collection that sets authorization using bearer token and the token is an environment variable
* Have a request that sets authorization to inherit
* Run that request that fails, in console it shows this in the header:
```
Request Headers
Authorization: Bearer •••••••
```
* Change request authorization to bearer token and using the same environment variable (it's no longer inheriting)
* Request succeeds

In the Environment, the environment variable being used is of type secret.

### Operating System

macOS 12.6

### Postman Version

Version 10.0.22 

### Postman Platform

Postman App

### Additional Context?

![CleanShot 2022-10-19 at 11 27 30@2x](https://user-images.githubusercontent.com/104794844/196774368-3d6b4ca9-2361-4777-bccf-8c04bde2ea1e.png)

**Comment by postman-staff** [comment]
via @ | Postman Support

**Comment by postman-staff** [comment]
Hello Alee,

Thank you for reporting this issue to Postman Support.

I could not reproduce the issue on our end, as a fix for this was rolled out recently as per https://github.com/postmanlabs/postman-app-support/issues/11348.

Can you attempt to update your Desktop app to the latest version and let us know if the issue persists? I did not encounter the problem on V10.0.32.

Alternatively, can you also let us know if you encounter the same issue via our Web App?

If the issue persists, can you also share a screen recording of the reproduction steps so we can further test this on our internal environments?

I look forward to your response!

via @ | Postman Support
