### ISSUE TITLE
your session has expired. please sign in again

### ISSUE THREAD

**Issue by Kalman1605** [a85/POSTMan-Chrome-Extension#11376]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

I cannot login to Postman.
The application continues ask me to login 
![image](https://user-images.githubusercontent.com/4973409/196899764-6d9083fc-6bca-4126-85ec-5755ca04daf1.png)

Before logging out I made a Backup of C:\Users\xxxx\AppData\Roaming\Postman to safe my requests
![image](https://user-images.githubusercontent.com/4973409/196900266-5f175bf3-bce1-4f3e-8b7c-e1287e704e19.png)

Signed-out
I paste back Partitions folder
But when I start Postman continues ask me to login 

Can you help me?
Thanks all
K

### Steps To Reproduce

Log into Postman

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/4973409/196899764-6d9083fc-6bca-4126-85ec-5755ca04daf1.png)

![image](https://user-images.githubusercontent.com/4973409/196900266-5f175bf3-bce1-4f3e-8b7c-e1287e704e19.png)

### Operating System

Windows 11

### Postman Version

Version 10.0.1

### Postman Platform

Postman App

**Comment by postman-staff** [comment]
Hello Kalman,

Thank you for that information and for writing to Postman Support.

I understand you are in a session-expired loop. To ensure you are given accurate and quality support, can you attempt the following:

- Go to the Active Session page and revoke all sessions.
- Remove your local data.

If the issue persists after following the steps above, can you let me know the username or email associated with the Postman account encountering the problem?

I hope the information provided helped resolve your issue. I look forward to hearing from you!

via @ | Postman Support

**Comment by Kalman1605** [comment]
Hi, 

unfortunately, your tips didn’t resolve my problem.

I have two accounts:

*	Email ***@***.*** ***@***.***>                                              username AndreaV
*	Email ***@***.*** ***@***.***>             username Andrea Viola

 

The problem appears using both accounts.

 

Now I’d like to restore my old sessions but my doubt is that I don’t remember if a synced those.

I made a backup of C:\Users\Administrator\AppData\Roaming\Postman  folder.

 

Can you help please?
Thanks
Andrea

**Comment by postman-staff** [comment]
Hello Kalman,

It is great to hear back from you!


We need to take a closer look into this issue. Could you please log a ticket using the support form: `https://www.postman.com/support` And provide the following data to troubleshoot further :

- Screencast/Screenshot of this behavior.
  - We find loom.com to be an excellent tool for this.
- Application logs - Getting Postman logs - https://support.postman.com/hc/en-us/articles/360047765713-Where-can-I-find-logs-for-the-Postman-Application-
- The emails associated with the accounts encountering this issue.
- Could you let me know if you're having this issue on our Web app or just the desktop app?

For some context, sync is enabled for username: AndreaV, but I was unable to locate the account with username: Andrea Viola.

I appreciate your collaboration and will wait to hear back from you!


via @ | Postman Support

**Comment by postman-staff** [comment]
Hello Kalman,

I hope you are doing well!

I will close this ticket, as we have not heard back from you on this issue.

If you need further assistance, don't hesitate to get in touch with us via https://www.postman.com/support. We'd be more than happy to help!

via @ | Postman Support
