### ISSUE TITLE
Collection Runner - on selection of Data, the selected collection changes

### ISSUE THREAD

**Issue by johnnavarra** [a85/POSTMan-Chrome-Extension#1138]
Collection Runner - on selection of Data, the selected collection changes.
1. example I have 8 collections to select from within collection runner
2. select the collection ( position 2)
3. select environment (note selected collection is still position 2)
4. enter iterations (note selected collection is still position 2)
5. select data
6. note that selected collection moves to position 4 (selects the 4th one down) for no reason

**Comment by abhijitkane** [comment]
Is this still happening with v3.0.4?

**Comment by johnnavarra** [comment]
Confirmed fixed
