### ISSUE TITLE
Prism shaves off decimals for double

### ISSUE THREAD

**Issue by cvik77** [a85/POSTMan-Chrome-Extension#11389]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Prism shaves off decimals for double, this makes the response look like an Integer instead of a double
1,0 int the database becomes 1 through prism. 
Expect the body to be immutable, however this does not seem to be the case. 

### Steps To Reproduce

1. send a double through Prism using Get endpoint expecting double to show e.g 1,0
2. Response however shows only e.g 1, makes a double look like an Integer
3. See screenshots

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/49973396/197469671-905c1201-97b2-4cae-bf5a-a9d4a7d100bd.png)
![image](https://user-images.githubusercontent.com/49973396/197469853-af8a7969-fca2-49e4-b27e-bfe08dd906ff.png)

### Operating System

Window10

### Postman Version

v9.31.0

### Postman Platform

Postman App

**Comment by shubhbhargav** [comment]
@cvik77 This looks like an issue with the hosted endpoint itself. You can confirm in the `Console` (at the bottom left) that the server itself is responding with `1` which is shown in the UI.

**Comment by cvik77** [comment]
I am sorry. It is stoplight.io/prism which is the problem. I reported it to the wrongly. Thanks for the respons. Will close it now.
