### ISSUE TITLE
My Postman website blank 

### ISSUE THREAD

**Issue by charlesr1971** [a85/POSTMan-Chrome-Extension#11386]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

When I log into postman.com, I see a blank page, using Mobile Safari 15.0.2 on iPhone 8+ 

### Steps To Reproduce

log into postman.com using Mobile Safari 15.0.2 on iPhone 8+ 
You will see a blank page

### Screenshots or Videos

![543DAEB8-8C56-4130-947C-FA41C1D25ACB](https://user-images.githubusercontent.com/827046/197327287-1ce0bcd0-f11b-403b-81fd-51b36871fd88.png)

### Operating System

iOS 15.0.2

### Postman Version

Website

### Postman Platform

Postman Web

### Additional Context?

n/a

Please add any other contextual information about the problem, that might be relevant and help explain the issue you're facing.
You can attach images or log files by clicking this area to highlight it and then dragging files in.

**Comment by DannyDainton** [comment]
Hey @charlesr1971

Do you see the same on a private or incognito session?

**Comment by charlesr1971** [comment]
Hi Danny

Thanks for the speedy response. 

It doesn’t make any difference. Still blank with an incognito window. 

I was wondering whether I had inadvertently made a bad global setting choice, in my account config section [if there is such a section?]

The problem is, I cannot get into the settings section, because of the blank web page issue. So, it would be impossible to change stuff and see what effect, this has?

**Comment by DannyDainton** [comment]
Are you able to try this on another browser, wanted to check if this is only impacting you on Safari?

**Comment by charlesr1971** [comment]
Well I have tried this in Firefox & Chrome, as well, on my iPhone, but both show a blank web page. This isn’t surprising, considering that both these mobile web browsers use Safari’s core engine. 

If you mean, have I tried it on a desktop browser. No, I haven’t.

**Comment by postman-staff** [comment]
Hi hello,


Thanks for reaching out to Postman Support.

Sorry that you are facing issues while using Postman --- Happy to help.

Do you have the desktop application installed?  Let me know if you are seeing the same behaviour while launching and accessing the postman.


Kindly download the latest app for your platform from here:

- https://www.postman.com/downloads


Let me know if you are using an application called **EndPoint Protector**?
If yes then may I ask you to temporarily disable the software to see if Postman starts working as usual?

Also, Can you try disabling the GPU settings and check if it works?

Ref doc: https://support.postman.com/hc/en-us/articles/360026088854-Postman-is-stuck-on-the-load-screen

If that doesn't work, do give our Canary build a try and let us know if that helped: https://postman.com/downloads/canary



Thank you for your cooperation on this issue. Looking forward to your response!



via @Lincimary | Postman Support

**Comment by charlesr1971** [comment]
This issue is happening on mobile Safari. 
All of the solutions you outline in your last reply, like disabling the GPU settings, cannot be applied to an iPhone?

**Comment by postman-staff** [comment]
Hey hi,
Thank you for responding back.

I am not really sure if it is a compatibility-related issue since you are using the application on your iPhone. Can you try connecting to a different network might be a mobile hotspot or home wifi and check once?

May I request you to clear the browser cache/cookies, restart the browser, and check if you are able to open the app and login to the account?

Looking forward to your response.

via @Lincimary | Postman Support

**Comment by charlesr1971** [comment]
Hi @Lincimary

I have tested it on my desktop Windows 10 laptop and I get the following:

![image](https://user-images.githubusercontent.com/827046/199462894-373ebc58-e206-47cf-8404-9367b1c50998.png)

So, it seems like it is a mobile safari issue?

**Comment by postman-staff** [comment]
Yes, you are right!
It seems to be an issue with mobile compatibility settings. Can you try using Postman for Desktop which runs natively on Apple Silicon and see if it opens as expected?
Ref: https://github.com/postmanlabs/postman-app-support/issues/9346#issuecomment-947573206

Let me know how it goes.
via @Lincimary | Postman Support
