### ISSUE TITLE
Long numerical data in variables is incorrectly loaded in a Collection Run

### ISSUE THREAD

**Issue by IronSwalt** [a85/POSTMan-Chrome-Extension#11387]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

When importing data for a collection run and a variable contains a long string of numbers, the last few characters of the number are ignored and replaced by zeros - see screenshot included here.

### Steps To Reproduce

1. Create a new collection
2. Create a new request in the collection with an arbitrary URL
3. Add a variable to the body of the request
4. Click the "Run" button to start the dialog for running the collection
5. Click the Data section
6. Import the file that contains a variable with a long string (greater than 17 characters) of numbers 
7. Click "Preview" to check how the data file was imported
8. Notice the trailing zeros in the previewed data.

Here's a collection to demonstrate:
[Data Import Bug.postman_collection.zip](https://github.com/postmanlabs/postman-app-support/files/9847025/Data.Import.Bug.postman_collection.zip)

Here's the sample data file with one variable in one row:
[MyOneData.csv](https://github.com/postmanlabs/postman-app-support/files/9847018/MyOneData.csv)

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/14016348/197375807-5152902d-68a3-4bb7-83a8-38432b8ab6c2.png)

### Operating System

Windows

### Postman Version

10.0.35

### Postman Platform

Postman App

**Comment by DannyDainton** [comment]
@shubhbhargav 

Same/similar rounding of numbers. I believe that this is a javascript issue with bigInts but I might be wrong. 

https://github.com/postmanlabs/postman-app-support/issues/11317

**Comment by shubhbhargav** [comment]
You are right @DannyDainton.

@IronSwalt this is because of the limitations of max integer in Javascript. Based on the collection shared, it seems like the value is supposed to be sent as a string in the payload. If that's the case, this limitation can be overcome by converting the integer to a string in the .csv file (by adding double quotes around the value `"`). Let us know if that works for you.

**Comment by IronSwalt** [comment]
Hi there,

Yes, this work-around works for me. 

Thank you.
