### ISSUE TITLE
Environment variable search that gets you to the exact place where you can edit that variable!

### ISSUE THREAD

**Issue by Z-Farook** [a85/POSTMan-Chrome-Extension#11388]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

Yes [see this here!](https://github.com/postmanlabs/postman-app-support/issues/11200)

### Describe the solution you'd like

See the [comment Form Z-Farook here!](https://github.com/postmanlabs/postman-app-support/issues/11200)

### Describe alternatives you've considered

Stop using Postman!!!

### Additional context

N.A.

**Comment by DannyDainton** [comment]
As you have raised this to point at an already open feature request and to a comment you have left on it.

I'm going to close this issue as a duplicate.

**Comment by Z-Farook** [comment]
That is fine but we would love to have it solved!

**Comment by vedkribhu** [comment]
@Z-Farook In our latest release v10.10, we have introduced filtering support in the variables list. Do let us know your feedback.
![Screenshot 2023-02-15 at 12 29 24 PM](https://user-images.githubusercontent.com/37595282/219371788-62c53efd-730a-457b-bcf2-56f988fd4ea4.png)
