### ISSUE TITLE
Update collection from swagger definitions

### ISSUE THREAD

**Issue by neuberoliveira** [a85/POSTMan-Chrome-Extension#11399]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

A few days ago, maybe a week or more, if i update my api definitions, swagger in my case, there was a button to "validade" my docs, collection created from definitions, and then update/sync my collection. So if i add or delete something from definitions file it would reflect in my collection.

But after the update i cant find how to do it anymore

things i try
- connect an github repo, and no yet no success
- (still connected to github) delete previous docs, create a new one, then update the definitions file (inside postman), again docs refuse to update

how the screen was before update
[![how the screen was before update][1]][1]

And now this is my actual screen
[![And now this is my actual screen][2]][2]

```
Postman
Version 10.0.27
UI Version: 10.0.27-ui-221013-1124
Desktop Platform Version: 10.0.1 (10.0.1)
```

  [1]: https://i.stack.imgur.com/8wpVI.png
  [2]: https://i.stack.imgur.com/NfRij.png

### Steps To Reproduce

create a api definitions file
create a collection from definitions
update definitions file

collection should be updated somehow

### Operating System

MAC

### Postman Version

10.0.27

### Postman Platform

Postman App

**Comment by shashankawasthi88** [comment]
@neuberoliveira thanks for bringing this up. We are actively working on this and shall get back to you soon. 
Just to understand your flows better, what sort of updates are you making to your schema for which you want to correspondingly update the collection? Are these new endpoints, updates to existing endpoints, or something else?

**Comment by neuberoliveira** [comment]
sorry for the late answer, miss the notification.

my main use for now is for new endpoints and updates to existing ones.
one approach could be delete and recreate colecction, but i have some vars and tests to handle authetication, so its a bit odd to copy everything on each update

**Comment by shashankawasthi88** [comment]
Thanks! We are actively working on this flow and shall update the thread as and when we have an update.

**Comment by shashankawasthi88** [comment]
@neuberoliveira this feature is now available in the latest Postman release that is being rolled out to all users. Refer the [blog](https://blog.postman.com/build-better-apis-using-the-new-and-improved-api-builder/) and the [document](https://learning.postman.com/docs/designing-and-developing-your-api/developing-an-api/adding-api-elements/#keeping-a-collection-in-sync-with-an-api) to learn more. Feel free to reopen and post the ticket if you have any feedback on the feature.
