### ISSUE TITLE
URL Encoding does not work in Code snippet of cURL

### ISSUE THREAD

**Issue by jluncc** [a85/POSTMan-Chrome-Extension#11391]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

With the new version of Postman (Version 10.0.35), Code snippet of cURL does not url encode automatically. However, url encoding work in console.

### Steps To Reproduce

1. create a request
2. input a param which value like chinese
3. open the Code snippet of cURL
4. the cURL does not url encoding automatically

### Screenshots or Videos

![postman-1](https://user-images.githubusercontent.com/18534759/197682215-01a636a4-96d4-4f41-976c-62e30e92d78b.png)

### Operating System

macOS 12.6

### Postman Version

10.0.35

### Postman Platform

Both

**Comment by LostKatana** [comment]
URL encoding seems to be broken entirely. When using parameters, like doing a search and the search term contains spaces the request is done properly but cUrl snippet is missing encoding as well.
![image](https://user-images.githubusercontent.com/14800164/199593720-7c67649e-27b4-4444-8a90-d079030e78d8.png)

Expected URL: https://duckduckgo.com/?q=where%20is%20my%20space%20encoding
Actual URL: https://duckduckgo.com/?q=where is my space encoding

Postman v10.0.42
OS: Ubuntu 22.04.1 LTS

**Comment by akshaydeo** [comment]
@jluncc @LostKatana thank you for reporting this issue. We are working on a fix. I will update this thread once the fix is available 🙇‍♂️

**Comment by jluncc** [comment]
it seem that this bug fixed in Version 10.10.3?  @akshaydeo

**Comment by VShingala** [comment]
@jluncc @LostKatana Yes, The issue has been fixed with Postman App version >= 10.10.
