### ISSUE TITLE
GraphQL variables not populating

### ISSUE THREAD

**Issue by hassansheikh90** [a85/POSTMan-Chrome-Extension#11390]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

When creating a graphQL query with variables
And assigning a collection variable to the graphQL variable in the graphQL variables pane (e.g { "graphQLVariable": "{{environmentVariable}}"}
The graphQL variable does not get the value of the environment variable

### Steps To Reproduce

1. Create a request
2. Set body to graphQL
3. Create a postman environment variable
4. In the graphQL body, compose a graphQl query with a graphQL variable
5. In the graphQL variables pane, create a json and assign your postman environment variable to the graphQL variable
<img width="991" alt="image" src="https://user-images.githubusercontent.com/102661874/197607235-4d484b6d-6275-449d-9a50-5a9066d0a05b.png">

### Operating System

MacOs Monterey 12.6

### Postman Version

Version 9.31.0 (9.31.0)

### Postman Platform

Postman App

### Additional Context?

Tried on both postman and postman canary, same result

**Comment by DannyDainton** [comment]
Hey @hassansheikh90

Can you clarify where you're setting the variable, please? 

You've mentioned Collection and Environment variables in the same issue. Would you be able to share a screenshot of where you're setting that please?

**Comment by hassansheikh90** [comment]
Hi, on further testing, this works with the normal postman app, and is an issue with postman canary, I have been setting in environment variables, apologies, incorrectly mentioned collection variable, haven't tested with that.

**Comment by DannyDainton** [comment]
As this is not an issue with the main app and only on Canary, I'm going to close this out.
