### ISSUE TITLE
Codeblock JSON syntax not highlighted in documenter

### ISSUE THREAD

**Issue by tkrajewski89** [a85/POSTMan-Chrome-Extension#11395]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

**Result**
The codeblock syntax is not highlighted (grey block of text).

<img width="427" alt="image" src="https://user-images.githubusercontent.com/77440168/198022218-702f2398-5824-4404-bcff-1a3952ce5b45.png">

**Expected result**
Syntax is highlighted according to the code language

<img width="475" alt="image" src="https://user-images.githubusercontent.com/77440168/198022376-2782029e-ee23-4bad-9dc7-e6243e9d50f4.png">

### Steps To Reproduce

1. Go to documentation of the request
2. Add custom description for it
3. Add codeblock with JSON syntax selected
4. Publish docs

### Operating System

MacOS

### Postman Version

Postman Web

### Postman Platform

Postman Web

**Comment by kamaraj-p** [comment]
Hi @tkrajewski89 , thanks for reporting the issue. We are fixing this on priority and will update once we release a fix.

**Comment by kamaraj-p** [comment]
Issue is now fixed in the latest release. Please verify and re-open if needed.
