### ISSUE TITLE
Improvement Request: update bundled lodash library to current version (e.g. 3.9.3)

### ISSUE THREAD

**Issue by thirtified** [a85/POSTMan-Chrome-Extension#1139]
Could you please update the bundled lodash version to the current version 3.9.3, and maybe keep it current?

Every lodash version seems to bring a whole batch of great new features. Especially helpful are the deep getters and setters (https://lodash.com/docs#get and https://lodash.com/docs#set) introduced in v3.7, which allow for testing of nested JSON structures without the burden of testing all intermediate structures for existence.

E.g. instead of 

```
tests["Deep Nesting"] = one && one.two && one.two[0] && one.two[0].three;
```

lodash allows to write

```
tests["Deep Nesting"] = _.get(one, 'two[0].three');
```

Thanks
- Julian

**Comment by aleross** [comment]
+1

**Comment by shamasis** [comment]
Can you try our Canary build - http://blog.getpostman.com/2016/06/14/introducing-postman-runtime-more-power-better-control/

We are updating the entire underlying script execution runtime. It will get into production soon.
