### ISSUE TITLE
Can't run a collection on Postman v10.0.36

### ISSUE THREAD

**Issue by BrainMcS** [a85/POSTMan-Chrome-Extension#11393]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

I have a collection to run for tests - but when we tried to run it, the runner on Postman App or Postman Web shows an empty list of collection instead.

### Steps To Reproduce

1. Have a collection to run
2. Via the Collection Run button, click on it
3. Observe that the Runner shows an empty list of collection, and we could not drag and drop the collection onto it.

### Screenshots or Videos

https://user-images.githubusercontent.com/85135141/197773375-cb952078-e242-4713-a734-ecfa8df0d638.mp4

### Operating System

Windows

### Postman Version

10.0.36

### Postman Platform

Postman App

### Additional Context?

Please see attached video for more context

**Comment by timbochamp** [comment]
Hi @BrainMcS, could you please share the logs (from View -> Developer -> View logs in Explorer) to help@postman.com if you're able to reproduce this consistently with this collection?

I'm logging a bug and alerting the team associated with this as well.

**Comment by BrainMcS** [comment]
Yes, I have been reproducing the bug consistently with me and my colleague. I'll share the logs.

**Comment by BrainMcS** [comment]
@timbochamp log files sent

**Comment by giridharvc7** [comment]
@BrainMcS Just curious, are your APIs migrating?

**Comment by BrainMcS** [comment]
Nope, they are the same APIs as usual.

I have a colleague who managed to run the same collection on her Postman App v 9.31.0

**Comment by giridharvc7** [comment]
Can you once try dragging and dropping the collection into the runner window? We are still trying to reproduce the issue on our end, just wondering if there's a way for you to get you past this bug. Attaching a screen-recording for the same. 

https://user-images.githubusercontent.com/1040583/197804029-bd40ee2d-0ce4-4966-8430-128ce9570c6f.mov

**Comment by BrainMcS** [comment]
Still no luck even after drag and drop. For some reason, it always shows the APIs list every time I do it:

https://user-images.githubusercontent.com/85135141/197804462-09cac25c-300e-4c7f-ba8a-3f4dbe657b08.mp4

**Comment by giridharvc7** [comment]
@BrainMcS Thank you for sharing the logs and trying out the drag drop workflow. 

We've found the underlying issue and we are working on a fix, we will get back to you in some time.

**Comment by giridharvc7** [comment]
@BrainMcS Can you please try now and let us know if things work fine for you? 
Please close and reopen the app for the app to update. 
This should work from Postman v10.0.37

P.S: We still haven't fixed a few edge cases of drag-drop, but the usual places where you'd run the collection should be fixed.

**Comment by BrainMcS** [comment]
Hello @giridharvc7 

After the minor update, I can now run my collections as usual via the usual place where I usually launch the runner.

Still awaiting the fix for the drag and drop issue, but for now, the usual method is fine by us.

Thanks for the swift action!
