### ISSUE TITLE
Postman integration to GitHub backing up collections errors with "Unknown error encountered at Github"

### ISSUE THREAD

**Issue by richardbeacroft** [a85/POSTMan-Chrome-Extension#11396]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Postman integration to GitHub backing up collections errors with "Unknown error encountered at Github"

### Steps To Reproduce

As a GitHub user with full permissions, a "Fine-grained Personal Access Token" is generated with Read and Write access to code, commit statuses, repository hooks, and workflows.

In Postman a GitHub integration is setup using the Personal Access Token and for a repository owned by the organisation to push to the "main" branch.

The integration is successfully setup in Postman, but then shows a status "Failure" with the message "Unknown error encountered at Github".

We are using the free version of GitHub and Postman

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/116741077/198074752-4caf6863-f218-41a2-a4f7-f29b3305db1c.png)

### Operating System

Windows

### Postman Version

10.0.38

### Postman Platform

Postman App

**Comment by shashankawasthi88** [comment]
@richardbeacroft thanks for raising this. We are looking into it.

**Comment by shashankawasthi88** [comment]
Hi @richardbeacroft can you ensure that the PAT you are generating has the access to the repository that you are trying to connect to and also has the following two permissions: -


- Meta-data  - mandatory permission that you can't turn off that allows you to list repos; 
- The Contents Read and Write permission.

**Comment by ahmedmosh** [comment]
@richardbeacroft  @shashankawasthi88   Despite having those permissions enabled in the PAT, I ran into the same problem. However, I generated a new PAT using the "Token(classic)" and it worked perfectly.

**Comment by shashankawasthi88** [comment]
@ahmedmosh yes, Postman only works with Classic tokens for now.
