### ISSUE TITLE
Minimise all collection folders

### ISSUE THREAD

**Issue by ghost** [a85/POSTMan-Chrome-Extension#11406]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

When working with big collections you will have to scroll endlessly through closed and opened folders to find a request. It's hard to find a folder name or request name in this big list. I end up manually closing all my folded out folders again and again to be able to easily navigate the folder menu.

### Describe the solution you'd like

I see multiple solutions:

- A short key to close all folders
- Close all child folders when a parent is closed.

**Comment by giridharvc7** [comment]
Thank you for your patience, We've introduced this feature in v10.13. You can now use `Option+Click` to expand and collapse all children of an element. This work for collections and folders.

https://user-images.githubusercontent.com/1040583/232968843-ecd9e63c-3d65-4bee-ae12-fba2dd55107e.mov
