### ISSUE TITLE
Feature: Enable Dark/Light theme based on OS theme

### ISSUE THREAD

**Issue by adriancuadrado** [a85/POSTMan-Chrome-Extension#11401]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

The problem is that many people want [this feature](https://github.com/postmanlabs/postman-app-support/issues/5817), which should not be that hard to implement, but to this date you didn't even give an ETA [as you promised](https://github.com/postmanlabs/postman-app-support/issues/5817#issuecomment-1020359373).

### Describe the solution you'd like

I'd like to have that feature implemented. C'mon guys the issue was created in 2019. How much do people have to wait to have it? At this pace we will have the _Hollow knight: Silksong_ game released before you implement it.

### Describe alternatives you've considered

Using other open source alternatives like [Hoppscotch](https://hoppscotch.io/) instead. Nice thing we have competition for Postman.

### Additional context

I know this issue will be closed in no time because it's obviously a duplicate of the issue I linked myself. But at least it will raise some awareness and make Postman developers realize how hard we want this particular feature.

**Comment by DannyDainton** [comment]
As you know already, closing this as a duplicate.
