### ISSUE TITLE
Can't access folder created by another user via Postman API

### ISSUE THREAD

**Issue by MitriSan** [a85/POSTMan-Chrome-Extension#11407]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

When i'm trying to access a folder, that were created by another user from the same team, via Postman API, i receive 404 response. However, when i use API key of the creator of this folder, i can see all the information, exactly with the same request. Permissions for both users are the same on workspace level and on collection level. Example request: 
```
curl -I --request GET 'https://api.getpostman.com/collections/17867205-42468079-d6a1-4cf8-9e9f-6d7b1f3cc111/folders/499c13a1-9b07-497f-9cc3-df974d7d8078' \
--header 'X-API-Key: *****' --header 'Accept: application/vnd.postman.v2+json'
```
Workspace ID: `32d98912-bc04-4ab7-973b-b155f742cc8c`

### Steps To Reproduce

1. Create a collection within a workspace of a team
2. Add any folder to this collection
3. Try to get this folder information via Postman API using another teammate key

### Operating System

macOS

### Postman Version

9.31.18

### Postman Platform

Other

### Additional Context?

This issue blocks our team as we are trying to automate some routines with our collections using Postman API.

**Comment by DannyDainton** [comment]
Hey @MitriSan 

Are you able to share a screenshot of the Workspace Settings showing the user's permissions and the Collection's Manage Users with the permissions, please?

**Comment by MitriSan** [comment]
Hi @DannyDainton , thx for your response

1. Permissions on workspace level: 
![image](https://user-images.githubusercontent.com/20190995/199230220-fcb0b978-1779-46a2-b37a-0dfa74b81483.png)
2. Permissions on collection level:
![image](https://user-images.githubusercontent.com/20190995/199230496-9f532f4e-41db-4e99-88ab-927b2d74f5b1.png)

The owner user, which have an access: `matias.cardenas@sendcloud.com, id: 17867205`
Second user, that should have an access, but doesn't: `api@sendcloud.com, id: 10978080`

**Comment by DannyDainton** [comment]
As it's in a Public Workspace, I'm able to view those details with my own API Key:

<img width="1265" alt="image" src="https://user-images.githubusercontent.com/17089546/199272946-62eb6ee7-88dc-4edc-bceb-ff4e48e96603.png">

The issue was that you were not using the UUID (The userId is added to the start of the ID) for the folder `17867205-499c13a1-9b07-497f-9cc3-df974d7d8078` and just using the ID `499c13a1-9b07-497f-9cc3-df974d7d8078`. As the other person created the entity, the ID would work for them.

**Comment by MitriSan** [comment]
Oooh, got it, thanks, makes sense. We'll switch to UUID usage.
