### ISSUE TITLE
pm.expect failure hides all test results

### ISSUE THREAD

**Issue by Benjamin-deVries** [a85/POSTMan-Chrome-Extension#11409]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

In the event that a pm.expect test fails, rather than showing the test to have failed and show the results of the tests (passed ones and failed) the user instead sees a banner indicating: "There was an error in evaluating the test script:  Error: ..."

### Steps To Reproduce

1. Make a new Request
2. Make it a GET (or anything else) to `google.com`
3. Go to the 'Tests' tab
4. Paste this in:
```
pm.test("ensure google exists", () => {
    pm.sendRequest({
        url: 'https://www.google.com',
        method: 'GET',
    }, (err, res) => {
        pm.expect(res).to.have.status(200);
    })
})
pm.test("ensure google page exists", () => {
    pm.sendRequest({
        url: 'https://www.google.com/someRandomPage.html',
        method: 'GET',
    }, (err, res) => {
        pm.expect(res).to.have.status(200);
    })
})
```
5. Click send
6. Click the 'Tests Result' tab

I would expect to see one test result that passed, and the second that failed. Instead i get an error message indicating that at least one of the tests has failed and nothing more.

### Operating System

MacOS

### Postman Version

10.0.41

### Postman Platform

Both

**Comment by DannyDainton** [comment]
The error is shown in the Test Results but it's not expanding on the failure information.

<img width="1602" alt="image" src="https://user-images.githubusercontent.com/17089546/199275866-449359c5-a41f-4def-89c2-7aea8b9480c7.png">

It looks like the Assertion Error is also coming through in the Console.

<img width="1055" alt="image" src="https://user-images.githubusercontent.com/17089546/199274622-def75de3-1efc-47d3-ab0f-ab2d0240ae44.png">

As it's an async request, the rest of the details for that are also in the console with the Assertion Error. 

The actual assertion should probably be something like this so you're targeting the correct part of the response:
```
pm.expect(res.code).to.eql(200)
```

**Comment by Benjamin-deVries** [comment]
Hi Danny, thanks for the response.

I realize that i can go to the console to get the data, but consider how results are displayed if the tests all pass.
<img width="590" alt="Screen Shot 2022-11-01 at 1 42 24 PM" src="https://user-images.githubusercontent.com/70020583/199301526-401db4f5-0349-456e-9923-4d2cd59dab55.png">

Still have the same behavior even after changing to `pm.expect(res.code).to.eql(200)`

**Comment by DannyDainton** [comment]
I understand the problem and agree that it's not a great way to display the information. I was just expanding on the issue and sharing an alternative `pm.expect()` syntax.

**Comment by apoorvgupta03** [comment]
Hey @Benjamin-deVries 

It is definitely a UX fail and we'll keep you updated, in the meanwhile, you can try writing the test like this and it will show as a failed test case, just like you want -: 

```javascript
pm.sendRequest({
    url: 'https://www.google.com/someRandomPage.html',
    method: 'GET',
}, (err, res) => {
    pm.test("ensure google page exists", () => {
        pm.expect(res).to.have.status(200);
    })
})
```
It makes sure that the pm.expect is always executed within the direct scope of pm.test, instead of pm.sendRequest

**Comment by Benjamin-deVries** [comment]
Thanks all, really appreciate it!
