### ISSUE TITLE
Some workspace collection list hidden by "Create a collection for your requests" panels

### ISSUE THREAD

**Issue by colin-stubbs** [a85/POSTMan-Chrome-Extension#11404]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

In our primary "Team Workspace" and in some other workspaces, when first opened for perhaps 2 seconds the full list of collections is displayed.

This then disappears and is replaced by a panel that should only appear if there were zero collections in the workspace, e.g. the "Create a collection for your requests" panel/s.

This is occurring in both the desktop app on Windows, and in the webUI via both Edge and Chrome.

This does not affect all workspaces, only some. I do not know why.

This is a new issue, it was not there on Friday last week, as of today/Monday morning 9am it is now occurring.

Screenshot below.

![Screenshot 2022-10-31 094725](https://user-images.githubusercontent.com/3059577/198907882-4594c3c3-c9d7-4d2e-95ac-61587dbab08f.png)

### Steps To Reproduce

1. Open "Team Workspace" with collections
2. See collection list appear briefly then disappear
3. Stare at "Create a collection for your requests" and wonder WTF this is happening.

### Screenshots or Videos

![Screenshot 2022-10-31 094725](https://user-images.githubusercontent.com/3059577/198907955-8aae1c11-43a8-4908-9016-14e9995775c0.png)

### Operating System

Windows

### Postman Version

9.31.21

### Postman Platform

Both

**Comment by colin-stubbs** [comment]
This is not a problem when using v9.20.0-canary

**Comment by colin-stubbs** [comment]
The ability to Pause and Edit monitors has also disappeared and appears to be related.
Again, it is not a problem when using v9.20.0-canary

**Comment by postman-staff** [comment]
Hello **colin-stubbs****,**

I hope that you are doing well.  Upon further review, we are of a response time issue that occurred on Monday that, unfortunately, may have impacted here.  If you are still encountering this behaviour, could I please request that you log a using the support form: `https://www.postman.com/support`and we will be happy to review your account further.  Apologies for any concerns and inconvenience this issue has caused you.  Thank you very much.

via @loutsiros | Postman Support
