### ISSUE TITLE
Collection runner Error upon loading a Json file and starting test

### ISSUE THREAD

**Issue by Chris-thomson** [a85/POSTMan-Chrome-Extension#1141]
I loaded the following data to my tests:
![image](https://cloud.githubusercontent.com/assets/12848078/8111878/2dccbe3a-105c-11e5-84df-c822b5b070ab.png)
and imported the following from a Json file
[
    {
        "CTURL": "crunch.co.uk:8181/api/support/articles/invoice"
    },
]

The variables are set and the Json is correct and all environmental variables work in a single tests but when the URL is coming from the Json file within collection runner you get the following messages:
![image](https://cloud.githubusercontent.com/assets/12848078/8111951/9f7b8200-105c-11e5-9fdd-2e879b46056e.png)

**Comment by abhijitkane** [comment]
@Chris-thomson can you confirm this fixed in v3.0.4?

**Comment by Chris-thomson** [comment]
Hey Abhijit,

How do i get my hands on v3.0.4 as my current version is v3.0.0.36
(packaged)

On 16 July 2015 at 10:04, Abhijit Kane notifications@github.com wrote:

> @Chris-thomson https://github.com/Chris-thomson can you confirm this
> fixed in v3.0.4?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/postmanlabs/postman-app-support/issues/1141#issuecomment-121889033
> .

## 

_Many Thanks_
_Chris Thomson_
Test Analyst

---

_Crunch_

web: _www.crunch.co.uk http://www.crunch.co.uk/_

twi: @teamcrunch

tel: +44 (0) 33 3311 8001

fax: +44 (0) 33 3311 8002

---

Let Crunch say thank you - _get £50_ for every referral with Crunch²
http://www.crunch.co.uk/crunch-squared/!

---

This email and any files transmitted with it are confidential and intended
solely for the use of the addressee. If you have received this email in
error, please let us know by replying to the sender and immediately delete
this email. In these circumstances, the use, disclosure, distribution or
copying of this information is strictly prohibited.

---

**Comment by abhijitkane** [comment]
3.0.0.36 is the latest team sync version. On prod, it's 3.0.4. 

Are you seeing the issue on 3.0.0.36?
