### ISSUE TITLE
Option to prevent jumping to response

### ISSUE THREAD

**Issue by phillip-haydon** [a85/POSTMan-Chrome-Extension#1142]
My only complaint about Postman is that when you send a request, it auto jumps the screen down to the response. Most of the time I wish the request/response were side by side as there is HEAPS of space.

But the fact it jumps down is so annoying. I leave it as split between the two and it still jumps so I can't see the request.

**Comment by abhijitkane** [comment]
We'll be pushing a fix that disables the auto-scroll behaviour soon.

**Comment by phillip-haydon** [comment]
:heart:

Awesome sauce. Keep up the good work, absolutely love Postman.

**Comment by a85** [comment]
@phillip-haydon You can go to chrome://extensions, enable developer mode and force update an extension. This should update the app to 3.0.0.6 that does not have the auto-scroll behavior.

**Comment by phillip-haydon** [comment]
@a85 - works great now. Thanks a lot! :heart:
