### ISSUE TITLE
Unable to delete request

### ISSUE THREAD

**Issue by cmyllis** [a85/POSTMan-Chrome-Extension#11423]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

There are some requests imported with the interceptor that I cannot delete now.
![image](https://user-images.githubusercontent.com/96247992/200298728-bde2f1e3-dd69-40d2-b2e2-2a68ca953b15.png)
So they are stuck there. Cannot be removed or moved.

### Steps To Reproduce

Not sure exactly how. But the requests were recorder with the interceptor chrome extension.

### Operating System

Windows

### Postman Version

9.31

### Postman Platform

Postman App

**Comment by postman-staff** [comment]
Hello there,

Thank you for raising this issue. I'm happy to help!

To better understand the issue, could you provide the following information?

- Are you encountering this issue in both the Desktop and Web app?
  - If the issue is only on the Desktop App, could you please let me know if you tried to remove the local data to fix the problem?
- What version of Postman are you running?
- What version of the Postman Interceptor are you running?

If the issue persists after removing the local data, please send the following information to https://www.postman.com/support:

- A copy of the Desktop logs.
  - If the issue is persistent on the Web app, please send us a copy of the HAR file as you attempt to delete the requests.
- A screen recording of the issue.
  - We find loom.com to be an excellent tool for this.

I appreciate your collaboration on this, and I look forward to hearing from you!

via @ | Postman Support

**Comment by cmyllis** [comment]
Happens on both.
Here is a video.

https://user-images.githubusercontent.com/96247992/200592023-59fb900f-011f-4364-9e56-5d6547b87e5c.mp4

**Comment by postman-staff** [comment]
Hey Christos,

Thank you for that information; we may need to look into this further, can you please send the following information to https://www.postman.com/support?

- A copy of the Desktop logs.
  - For the Web app, please send us a copy of the HAR file as you attempt to delete the requests.

I appreciate the collaboration and look forward to hearing from you!

via @ | Postman Support

**Comment by cmyllis** [comment]
Nothing is generated when clicking delete. Something is only generated when i am clicking the request.
[desktop.postman.com.har.zip](https://github.com/postmanlabs/postman-app-support/files/9968526/desktop.postman.com.har.zip)

**Comment by postman-staff** [comment]
Hey Christos,

Thank you for that information; As I mentioned, we need to look into this further. Can you please log a ticket using the support form: `https://www.postman.com/support` Do you have the following information?

- Please let us know if updating to Postman v10 resolves the issue.
- A copy of the Desktop logs would also help us troubleshoot, as they generate a log when deleting a request.
- Is this the only collection encountering deletion errors? Or are you unable to delete other requests?

I attempted to recreate the issue and was unable to do so. Hopefully, the information you share will help our investigation; I look forward to your ticket!

via @ | Postman Support

**Comment by cmyllis** [comment]
Cannot update to 10 due to licensing issues. 
A copy is attached in the previous post.
I havent tried recreating the bug in another collection.
I am only unable to delete requests added from the interceptor.

**Comment by postman-staff** [comment]
Hey Christos,

Thank you for sending us that information.

I've created an escalation for our engineering team to take a deeper look. As we await more information, can you provide this information to help with the investigation?

- I understand you are using V9. Can you share which version of Postman V9 you are using?
- Can you provide us with the version of the Postman interceptor you are using?
  - You can find the version by navigating to your extensions.
  - Select Manage extensions
  - Turn on Developer mode on the top right
  - Pressing on details for the Postman Interceptor
- You can also try to update the interceptor if you need to, and let me know if that does solve the issue.

I appreciate all the information and collaboration thus far. I look forward to hearing from you!

via @ | Postman Support

**Comment by postman-staff** [comment]
Hello Christos,

Thank you so much for your patience with this issue.

Our engineering team has identified the issue and is working on a fix. In the meantime, they suggested the following workaround to get the requests deleted:

- You will want to delete the request using postman.com/postman/workspace/postman-public-workspace/request/16473433-a7e03dca-daae-4b07-8a4c-a7499e21e01d
- Add the complete collection ID and remove the first part of the request ID in above.
  - EX: If request ID is `22644198-158c4d96-db66-4425-b0fd-912d52f6e4b9`, only add `158c4d96-db66-4425-b0fd-912d52f6e4b9` as request ID.

I hope this helps eliminate the requests until a complete fix is pushed. Feel free to let me know if you have any questions. I'd be happy to help!

via @ | Postman Support

**Comment by cmyllis** [comment]
Thanks for the reply.

> Requests can't be sent in public workspaces right now – though we're working on that for a future release!Fork this collection to your own workspace to send a request.

The bug is annoying but not that critical. Hopefully a fix is coming to both version 9 and 10. We ll wait until then to recheck if we can delete those.

**Comment by postman-staff** [comment]
You are welcome, Christos,

I'll mark the ticket as `Solved`since we have an open escalation and the GitHub Issue thread.

Please feel free to write to us or raise another GitHub issue if you need any more help.

Have a great rest of your week!

**Comment by postman-support** [comment]
You are welcome, Christos,

I'll mark the ticket as `Solved`since we have an open escalation and the GitHub Issue thread.

Please feel free to write to us or raise another GitHub issue if you need any more help.

Have a great rest of your week!

via @ | Postman Support
