### ISSUE TITLE
Can't see requests in Postman app, however they are available via Postman API

### ISSUE THREAD

**Issue by MitriSan** [a85/POSTMan-Chrome-Extension#11427]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

So, after some programmatic workflow, i've faced several issues:
1. I can't see the request in Postman app, however i can see it via postman API
2. I can see requests in the left bar with request lists, but:
2.1. When i click on a request, it says not found
2.2 All requests in the list are `GET`, however they should have different operations(PUT, DELETE etc.)

The main thing is that the collection is public, so the content should be visible to anyone, but with described scenario even owner of this collection can't see requests in Postman app.

### Steps To Reproduce

1. User A creates a public collection within a public workspace
2. User B, that has an editor permissions, creates a Folder and request in this collection
3. User A and User C(that has an access to this collection also) can't see this request in Postman app, however, can see it via Postman API.

### Screenshots or Videos

1. User see request list on the left, but can't see the exact request(and all requests are GET):
![image](https://user-images.githubusercontent.com/20190995/200380871-49f2da10-39a2-4765-9490-d5e838c85adb.png)
2.User can't see request in Postman app, but can see this request in Postman API:
<img width="355" alt="image" src="https://user-images.githubusercontent.com/20190995/200381110-426cd035-6a2a-4b35-866c-b07600fb3b5d.png">
<img width="990" alt="image" src="https://user-images.githubusercontent.com/20190995/200381390-8be9040e-339a-4b31-a188-d85a21f52df6.png">

### Operating System

macOS

### Postman Version

9.31.18

### Postman Platform

Postman App

### Additional Context?

We are trying to automate workflow for keeping our collections and requests up to date. We created a programmatic user for this purpose, however, when this user performs operations on existing collections, it leads to an unexpected result, such as created requests are not visible. This might be connected to a previous issue i opened - https://github.com/postmanlabs/postman-app-support/issues/11407 - postman app itself doesn't use UUID for requests(or use owner id of collection always). However, it's just my guess

**Comment by shubhbhargav** [comment]
@MitriSan Thanks for providing the detailed context. You are right. The automated workflow request could cause the collection to be in this state. Can you share the payload that the automated user used to make the update call to the collection?

**Comment by MitriSan** [comment]
Hi @shubhbhargav , thanks for quick response. The thing is that we use `Collection individual items` requests to add folders and requests to the collection, e.g.
`POST https://api.getpostman.com/collections/17867205-9fadfe3e-1c62-448c-b56e-8e638332bc83/folders`
with payload:
```json
{
  "name": "Air Waybill (AWB)",
  "folder": "1254052f-7061-4d6f-ba5b-7f1ade1456c3",
  "id": "30e2aa3f-c4ec-4e25-b5bc-2ee736df97d4"
}
```
and for request:
`POST https://api.getpostman.com/collections/17867205-9fadfe3e-1c62-448c-b56e-8e638332bc83/requests`
with payload:
```json
{
    "owner": "10978080", "lastUpdatedBy": "10978080",
    "lastRevision": 27609165121, "folder": "30e2aa3f-c4ec-4e25-b5bc-2ee736df97d4",
    "collection": "17867205-9fadfe3e-1c62-448c-b56e-8e638332bc83", "id": "75bb9e8b-21bc-4ccf-9788-e843c3b7e1a8",
    "name": "Finalizing a box", "dataMode": "raw", "data": null, "auth": null, "events": null,
    "rawModeData": "{\n  'copy_count': 1\n}", "descriptionFormat": null, "description": "****",
    "variables": null, "headers": "Content-Type: application/json\nAccept: application/json",
    "method": "POST", "pathVariables": null, "url": "{{baseUrl}}/box/finalize", "preRequestScript": null,
    "tests": null, "currentHelper": null, "helperAttributes": null, "queryParams": [],
    "headerData": ["***"],
    "pathVariableData": [],
    "protocolProfileBehavior": {"disableBodyPruning": true},
    "dataDisabled": false,
    "responses_order": ["b5430908-92d5-46e5-b8d7-b5bdb2e6f10b", "e9c560b2-6d41-4b44-8b27-d68c96b1508b"],
    "createdAt": "2022-11-07T17:37:47.000Z",
    "updatedAt": "2022-11-07T17:37:50.000Z",
    "dataOptions": 
    {
        "raw": {"language": "json"}
    }
}
```

**Comment by shubhbhargav** [comment]
Thanks @MitriSan. Looks like we are trying to send a few extra fields in the payload for the request which is causing this. Can you try removing `owner` from the payload and see if it works? In the meantime, I will get the list of mandatory fields that we need in the payload and share that with you.

**Comment by MitriSan** [comment]
Hi @shubhbhargav . So i still can see the request via Postman API, and can't see it in the app :(
![image](https://user-images.githubusercontent.com/20190995/200792964-40fd3a21-86df-4747-bceb-adabaab28a06.png)

**Comment by shubhbhargav** [comment]
@MitriSan That's not expected. We are looking into this.

**Comment by shubhbhargav** [comment]
@MitriSan While the team is looking into this, I have found an alternative to bypass the issue. If you create the collection with the collection ID using the programmatic user itself, it would work. Can you give it a try once?

**Comment by MitriSan** [comment]
Hi @shubhbhargav ! Thanks, this approach works, but the issue is that our team wants to manipulate existing collection. And this existing collection has forks and actively used by our customers, so we can't just recreate it.

**Comment by harsh-bansal97** [comment]
@MitriSan we are working on a solution for this and should have it fixed by early next week. Will let you know once it is fixed, thanks.

**Comment by harsh-bansal97** [comment]
@MitriSan this has been fixed now, let me know if you are still facing issues.
Also do note that `owner`, `lastUpdatedBy`, `lastRevision`, `createdAt` and `updatedAt` fields are not needed and you can remove them from the payload.

**Comment by MitriSan** [comment]
@harsh-bansal97 Hi, thanks for the quick fix! However, i think it's more of a feature request - is it possible to return UID for requests, responses and folders in Postman API? Example workflow - list collection to delete requests you want to replace, and you can't use raw IDs from `get collection` response, as you need to extract owner id from collection UID

**Comment by harsh-bansal97** [comment]
@MitriSan thanks for the input, we are aware of this dissonance and it is something we have plans to improve upon but unfortunately I dont have a timeline for you yet. Will check if we can fast-track this and get back.

**Comment by MitriSan** [comment]
@harsh-bansal97 nice, this feature would be really appreciated ! But for this bug i'm closing this issue, as it's fixed
