### ISSUE TITLE
Email address shows as being updated, but then reverts to previous

### ISSUE THREAD

**Issue by n-j-o** [a85/POSTMan-Chrome-Extension#11433]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Each time I update my email address, it shows as being completed successfully but then when I switch teams, it reverts back to the previous email address in all places (including team list, My Profile and invites).

### Steps To Reproduce

1. Open Postman
2. Login with username / password
3. Go to 'View profile'
4. Click 'Edit Profile'
5. Click 'Account'
6. Update email address field with new email and click "Update Email Address"
7. Follow prompts to re-login to Postman for security
8. Complete workflow until returned to Profile
9. Go to 'View profile' and see email address has been updated
10. Click profile icon and switch into another team 
11.  Go to 'View profile'
12. Email address has now reverted and is back to previous one 

### Screenshots or Videos

Loom demonstration: https://www.loom.com/share/5d8567eb71ab4108ba9d30b6dc77c294

### Operating System

macOS / Brave

### Postman Version

10.1.1

### Postman Platform

Both

**Comment by ArjunSingh-PM** [comment]
@n-j-o Thanks for reporting this issue. We have fixed the same and you should be able to update your email for your account. Thanks.
