### ISSUE TITLE
gRPC: "No Root Files" Error

### ISSUE THREAD

**Issue by jschweihs** [a85/POSTMan-Chrome-Extension#11436]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

I am attempting to save an API based on my proto files.  There is a main file that defines services and then it uses separate proto files for message definitions. I am able to make requests if I  use the "Import a .proto" method.  However, if I try and save this proto file as an API, with the intention of reusing it later, I get a "no root files" error.  I do not get any more details on the error and I cannot find any information Google.

<img width="513" alt="Screen Shot 2022-11-09 at 12 02 56 PM" src="https://user-images.githubusercontent.com/6620115/200907318-57686a5b-d31a-4ad0-926f-8dddea4454bc.png">

My project structure looks as follows.  Notice the "ROOT" marker. 

<img width="324" alt="Screen Shot 2022-11-09 at 12 02 48 PM" src="https://user-images.githubusercontent.com/6620115/200907421-b8bd1c17-8924-4b79-b46f-2ce09e0c7962.png">

Please tell me if I am doing something wrong or if there is indeed a bug with the tool.  Thank you.

Edit: Just a note, I have tried moving the travelport_proxy.proto file directly under Definitions, thinking maybe Postman required the root to exist there. This did not seem to solve it.

### Steps To Reproduce

1. Start a new gRPC Request
2. Choose "Import a .proto file" for service definition
3. Provide proto file and any additional import paths required.
4. Hit "Next"
5. Type the name of a new API in the "Select an API" field and hit Import as API

### Operating System

Mac

### Postman Version

10.0.42

### Postman Platform

Postman App

**Comment by codenirvana** [comment]
@jschweihs can you share a scaled-down Protobuf definition that we can use to reproduce this issue?

**Comment by jschweihs** [comment]
Of course, I created a simplified version and this works as expected:

[app.zip](https://github.com/postmanlabs/postman-app-support/files/9974830/app.zip)

This version is 111kb while the full project's proto folder is 44.2MB.  Perhaps the size is the issue?

Edit: Fixed app.zip, was missing a file due to testing.

**Comment by appurva21** [comment]
@jschweihs Thanks for reporting the issue! 
We've identified the cause and working on a fix. We'll update the thread once the fix is released.

**Comment by appurva21** [comment]
Hey @jschweihs! 
We have fixed this issue in the latest release of the Postman app (v10.3.5). Can you restart your app to verify if things are working fine for you?
