### ISSUE TITLE
can't export collection after import from swagger

### ISSUE THREAD

**Issue by potjerodekool** [a85/POSTMan-Chrome-Extension#11439]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

From time to time I have to import an updated swagger (swagger 2.0) file of an external company.
Before when I imported the swagger file a collection was created on the collection tab in postman but not anymore.
Now I have a collection on the api tab.

I can work with that collection but I can't export the collection from the api tab.
Not sure if its the new way of working that the collections are created on the api tab but I need to be able to export the collection. All the request (more then 100) in the api I import need some request parameters, I fill those parameters with some global variables.

What I did before was exporting the collection and then modify then collection with some Java code I have written to fill the request parameters with the global variables. After that I import the modified collection and I am good to go.

What I need is to be able to export a collection from an imported swagger file.

Version 10.2.2
UI Version: 10.2.2-ui-221110-0731
Desktop Platform Version: 10.1.2 (10.1.2)

### Steps To Reproduce

1. Import swagger file

### Operating System

macOs

### Postman Version

10.2.2

### Postman Platform

Postman App

**Comment by DannyDainton** [comment]
Hey @potjerodekool 

Do you use the options in the Import setting to copy the Collection to the Workspace?

<img width="919" alt="image" src="https://user-images.githubusercontent.com/17089546/201374738-246a99f2-b9e1-4425-9c9d-2461a886941d.png">

**Comment by potjerodekool** [comment]
Thanks @DannyDainton. Somehow I have missed that option.

**Comment by potjerodekool** [comment]
Fixed by sugestion

**Comment by potjerodekool** [comment]
Fixed by sugestion.
