### ISSUE TITLE
GRPC request - Can not refresh proto. Refresh button not update proto latest

### ISSUE THREAD

**Issue by PhuocBan** [a85/POSTMan-Chrome-Extension#11432]
### Is there an existing issue for this?

- [ ] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

After I changed proto, I click refresh button but proto not update

### Steps To Reproduce

1. update proto (add new comment, change message, ...)
2. go to grpc request and click `service definition` tab -> refresh button
3. open proto file in postman to check change

### Operating System

mac

### Postman Version

10.1.0

### Postman Platform

Postman App

**Comment by appurva21** [comment]
Hey @PhuocBan! I am not able to reproduce this issue at our end with the given steps. Could you share more detailed steps or a small screen recording to help us understand the issue better?

Also, here is a screen recording depicting the mentioned workflow, which seems to be working fine. Let us know if you are doing anything differently here.

https://user-images.githubusercontent.com/24985700/200747822-5af305cf-f597-46ff-87aa-1df91bbad5f4.mov

**Comment by appurva21** [comment]
@PhuocBan I'm closing this issue as we are not able to reproduce it. Feel free to re-open it in case the issue still persists for you.

**Comment by mikeycrostar** [comment]
This bug still persists, 

do you need logs ? (if yes where can I find them).

my protos are on WSL2 instance.

Version 10.8.6
UI Version 10.8.6-ui-230124-1121
Desktop Platform Version 10.8.0
Architecture x64
OS Platform win32 10.0.19044,

**Comment by codenirvana** [comment]
@mikeycrostar Can you share a screen recording ([like this](https://github.com/postmanlabs/postman-app-support/issues/11432#issuecomment-1308240061)) demonstrating the issue?

**Comment by mikeycrostar** [comment]
Hello, 

the video:
https://user-images.githubusercontent.com/5098986/214584180-e23db08d-4078-4b60-8d6a-8eb158049029.mp4

**Comment by aigimig** [comment]
I had the same problem. Fixed it by deleting the root .proto file definition from the APIs tab and reimporting it again.

**Comment by mikeycrostar** [comment]
Sounds like a workaround, but not a proper solution no ?

**Comment by felipellrocha** [comment]
Just ran into the same issue

**Comment by tommos23** [comment]
I have the same issue

**Comment by ArthurBook** [comment]
Got the same issue... :(

**Comment by markpsiano** [comment]
Same issue
