### ISSUE TITLE
White screen with some JS error

### ISSUE THREAD

**Issue by apurva-xto10x** [a85/POSTMan-Chrome-Extension#11449]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

I was creating a collection with folders and adding requests there, suddenly all the requests that I added faded away abruptly, I went afk for sometime and when came back saw the following on my screen (please refer the screenshot attached)
<img width="1536" alt="Screenshot 2022-11-16 at 2 36 43 PM" src="https://user-images.githubusercontent.com/66248462/202137996-9c4c291c-c7ca-464b-abf7-c20f059605b6.png">

### Steps To Reproduce

Not sure

### Operating System

macOS

### Postman Version

10.0.1

### Postman Platform

Postman App

**Comment by kamalaknn** [comment]
@apurva-xto10x Could you share the [logs](https://support.postman.com/hc/en-us/articles/360025298633-How-to-get-logs-from-the-Postman-Desktop-app)? 

In the meantime you should be able to use postman app on web `go.postman.co`. If you have signed in, all your data should be backed up and you should be able to use them on the browser as well.

**Comment by sk-lstein** [comment]
Hey there! I do also have an issue with Postman which is maybe related to this ticket. 
I found some old ticket about a White Screen issue related to Preview mode of a response. 
I was able to capture some errors from developer console. 

**Steps To Reproduce**

1. Firing a random API call.
2. Click on "Preview" - mode in Response view
3. Window gets white

**Screenshots or Videos**
![Bildschirm­foto 2023-02-22 um 10 04 09](https://user-images.githubusercontent.com/126062168/220572657-93437eb3-1ea3-416b-afdf-9e97c96e64f0.png)

No response

**Operating System**

Latest macOS

**Postman Version**

Version 10.10.7
UI Version: 10.10.7-ui-230222-0618
Desktop Platform Version: 10.10.3 (10.10.3)

Postman Platform

Postman App

Additional Context?
![Bildschirm­foto 2023-02-22 um 10 05 29](https://user-images.githubusercontent.com/126062168/220572977-e7d7e6cc-ade3-4286-947a-453c915d29de.png)

**Comment by giridharvc7** [comment]
Thank you for reporting this. We've found the issue and will keep you posted once we release this as a fix (in the upcoming release)

**Comment by ashuvyaspm45** [comment]
Hey folks, Sorry for the trouble you have to go through because of this issue. We have released a fix for this change and it's being rolled out and will be available to you in next few days. Please give it a try and give us feedback. Thanks for your patience.

**Comment by SuphathatUdomkan** [comment]
https://developers.google.com/speed/public-dns/privacy?hl=th#our_commitment

**Comment by SuphathatUdomkan** [comment]
https://github.com/postmanlabs/postman-app-support/issues/11449#issue-1451188556

**Comment by SuphathatUdomkan** [comment]
https://app.getpostman.com/join-team?invite_code=df95ba83f94275d57337cccee24effa2

**Comment by SuphathatUdomkan** [comment]
curl --location 'https://api-m.sandbox.paypal.com/v1/oauth2/token' \
--data-urlencode 'grant_type=client_credentials'
