### ISSUE TITLE
[Feature] AMF Support and variable-functions

### ISSUE THREAD

**Issue by ghost** [a85/POSTMan-Chrome-Extension#1144]
First, sorry for this silly word "variable-functions" but i dont know how i should name it.
With variable-functions mean, that i can put something like this in the body:
{random:[length:5,OnlyNumbers:true]} which everytime i send it will be replaced with a random numb er with a length of 5.

And amf support is a bit out of the goal, but i will hope that something like this will be available in the Future.

ps: sorry for bad english, i'm german.
pps: i'm new at github, i dont know how to set a label, i'm pretty sure its not complicated to find out how it works, but i have'nt find it.

**Comment by johnnavarra** [comment]
You can use this as a pre-request script to generate a variable number:

function getRandomInt(min, max) {
    return Math.floor(Math.random() \* (max - min + 1)) + min;
}

var randomnum = getRandomInt(1000,9999);
console.log(randomnum);

**Comment by a85** [comment]
Pre request scripts should help here. We are working on a plugin framework to make developing features like this even easier. Closing this for now.
