### ISSUE TITLE
Import unsuccessful

### ISSUE THREAD

**Issue by tanvibajwa** [a85/POSTMan-Chrome-Extension#11445]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Unable to import OpenAPI 3.0.0 to postman v 10.2.2
I am trying to import json definition of API but the import fails almost immediately with the following error:
![image](https://user-images.githubusercontent.com/38383434/201759144-faa7f1e8-f1f6-4700-b73e-9dfa3d1749e8.png)

### Steps To Reproduce

1. Click on Import button
2. Import a json (OpenAPI 3.0.0)
[screen-capture (1).webm](https://user-images.githubusercontent.com/38383434/201760727-4d5a26dc-6f34-4d74-bfb6-45b56fa35e56.webm)

### Operating System

Linux

### Postman Version

10.2.2

### Postman Platform

Postman App

**Comment by SaloniV3011** [comment]
Hi @tanvibajwa 
Could you please share the Open API 3 spec with us if possible? 
I can see in the video attached you tried twice , would like to confirm how many times did you try the Import again option and how many times did the failure occur? 
Would be really helpful if you can share your feedback & concerns on your Import experience. 
Thanks!

**Comment by akshaydeo** [comment]
Hi @tanvibajwa could you share the schema or part of the schema privately here: akshay.deo@postman.com 🙇‍♂️ . This will help us to debug the issue faster 🙂

**Comment by tanvibajwa** [comment]
Hi Saloni

I am not sure if I can share the spec.
I tried to import multiple times and it failed all the time. It imports the
documentation but doesn't create a collection. If I got to APIs to check
the definition, it shows that the json has 273 errors. But that's strange
because i am importing all the collections in the same way and the json
body should be correct.
Here's a screenshot of some of the error messages:
[image: image.png]

**Comment by VShingala** [comment]
@tanvibajwa The image shared by you is not visible, could you upload it on github itself as it seems replying to email doesn't upload it correctly.

**Comment by hbirkdale** [comment]
As an FYI, I also am having this problem. 
Mac OS - Ventura 13.1
Postman client - 10.8.1 

As you can see in my attached spec (which is a CSV file that you need to rename), its Openapi 3.1.0. First off, Postman thinks its OpenAPI 2.0

![image](https://user-images.githubusercontent.com/5109603/214689192-028fec57-db5e-408c-85ed-c2e97c1fcfa0.png)

when I import I get this:
![image](https://user-images.githubusercontent.com/5109603/214689284-f58032dd-924e-48d6-9407-4f5cbf2ed0b4.png)

If I go to the actual API, it does say its  OpenAPI 2.0 and that "Nothing here yet"
![image](https://user-images.githubusercontent.com/5109603/214689484-db9187d0-fcda-435a-a8d9-cb9def9db578.png)

If I change it here to OpenAPI 3.1, things start to fill in:
![image](https://user-images.githubusercontent.com/5109603/214689683-4ed57d87-83ef-4fcb-8c7d-d18b7ee833d1.png)

But no collection is ever created. 

I've attached my spec. You need to rename this to .json, as Github doesn't allow those files to be uploaded.
[LiquidMortgage.csv](https://github.com/postmanlabs/postman-app-support/files/10503640/LiquidMortgage.csv)

**Comment by VShingala** [comment]
@hbirkdale Thanks for reporting the issue! [We are aware of this issue shared by you](https://github.com/postmanlabs/postman-app-support/issues/11617), where OpenAPI 3.1 definitions are imported as OpenAPI 2.0 / Swagger 2.0 definitions. We have fixed the issue with the Postman Desktop app version `>=10.8.6` and latest Postman web as well. The latest releases are available for download.

Also For a workaround, you can manually generate a collection from navigating to menu items for the corresponding API and going to `Add Collection > Generate from definition`.

![image](https://user-images.githubusercontent.com/16756296/215085099-68404c91-19f5-4e29-a85d-7fb3f4782fc6.png)

As for the original issue, it's different as it's for OpenAPI 3.0 definition not importing correctly.

**Comment by hbirkdale** [comment]
Thanks @VShingala! Apologies for hopping on this issue - I thought it was similar. Thanks again.....

**Comment by VShingala** [comment]
@tanvibajwa This should be fixed now. Could you give it a try with latest Postman App? Feel free to reopen the issue if you're still facing this issue.
