### ISSUE TITLE
Some history missing from one Postman instance

### ISSUE THREAD

**Issue by PeterNSkovgaard** [a85/POSTMan-Chrome-Extension#11452]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

I have postman on my Mac and on a different windows machine. For some reason, some of the history on my windows postman app is not synced to my Mac application despite being logged in with the same account on both.

Specifically I have a lot of calls on October 25th and 26th which are only in my history on my windows app whereas my Mac history has nothing at all for these days. Everything before and after is synced perfectly. Also whenever I make new new requests from either machine it syncs it to the other one now as it should.

Both of the applications says that everything is synced and backed up online. I have not (intentionally at least) done anything to filter out some requests on my Mac and I also cannot find a "re-sync" option anywhere. 

I work on my mac all the time, the windows is only for backup purposes so it is only "luck" that the requests are still in my hsitory on the windows machine!

Do you know what I can do to get the Mac history back up to date?

### Steps To Reproduce

I don't know how it has happened, the history is just different between the two instances.

### Screenshots or Videos

Mac: Nov 8 -> March 16
<img width="331" alt="Screenshot 2022-11-17 at 14 17 28" src="https://user-images.githubusercontent.com/97675324/202456728-972d57d1-427a-44e4-a0ee-79df3e37c76b.png">
Windows: Nov 8 -> Oct 25+26
<img width="219" alt="Screenshot 2022-11-17 at 14 18 27" src="https://user-images.githubusercontent.com/97675324/202456911-92fdd36c-bfee-4ee6-bdae-e7a8b4c0bc4c.png">

### Operating System

Mac and Windows

### Postman Version

10.3.4

### Postman Platform

Postman App

### Additional Context?

The postman version info given here is on the mac. My windows is a bit older, but I don't really dare update it yet as I am afraid of losing my history from the windows machine as well!

**Comment by VaishnaviChallaPostman** [comment]
Hey @PeterNSkovgaard 
Sorry to know that you are facing this issue. 

Could you please create a Support Ticket with us [here](https://support.postman.com/hc/en-us/requests/new/) and provide the network logs from mac, to help us investigate better? 
It would be great if you could mention this GH thread ID (GH #11452) in the subject while raising a ticket :) 
Thank you!

**Comment by postman-staff** [comment]
Hey @PeterNSkovgaard,

I wanted to follow up to see if you've had a moment to create a Support Ticket with our team?

Please create the ticket here and provide the network logs from mac, to help us investigate for you.
It would be great if you could mention this GH thread ID (GH #11452) in the subject while raising a ticket :)

Thank you!
via @User_1 | Postman Support

**Comment by PeterNSkovgaard** [comment]
Hi, 

Sorry for missing your reply!! I created a ticket now and put the GH id in the subject. 

\Peter

**Comment by postman-staff** [comment]
Thanks **@****PeterNSkovgaard,**

We will close this thread out and our team will continue the investigations, and keep you updated in the ticket you've created.

Cheers!
via @User_1 | Postman Support
