### ISSUE TITLE
JSON.parse generates an error from JSON generated from the XML conversion.

### ISSUE THREAD

**Issue by johnnavarra** [a85/POSTMan-Chrome-Extension#1145]
in my test:
var jsonObject = xmlToJson(responseBody);
var response = JSON.parse(jsonObject);

Object {message: "There was an error during JSON.parse(): Unexpected token o"}

**Comment by mehtasunny** [comment]
I am trying to do the same thing. I receive this error: JSON.parse(): Unexpected '<'

**Comment by abhijitkane** [comment]
@naughtylion 
My guess is that your server is returning HTML code, for which JSON.parse() throws an error.
Can you add a "console.log(responseBody);" line above the JSON.parse() and check the console (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/)?

**Comment by mehtasunny** [comment]
@abhijitkane 
Here is my console log. It doesn't look like it is returning any HTML-

Render XML response

``` xml
 <Token> 1e321532d </Token>
```

Evaluator.js:163 Object {message: "There was an error during JSON.parse(): Unexpected token <"}

**Comment by abhijitkane** [comment]
If you're using xmlToJson or xml2Json, you don't need to use JSON.parse().

JSON.parse converts a JSON string to an object. xmlToJson/xml2Json will return objects from XML strings.

```
var jsonObject = xmlToJson(responseBody);
console.log(jsonObject);
```

You'll be able to see the contents of jsonObject in the console - http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/

**Comment by mehtasunny** [comment]
@abhijitkane 

Got it. Thanks for resolving my problem.
