### ISSUE TITLE
Postman Interceptor Fails to start session

### ISSUE THREAD

**Issue by kaivalyapendse** [a85/POSTMan-Chrome-Extension#11451]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

We are trying to capture requests using Postman Interceptor. We were able to do so but after updating the Postman we are getting following error: **`Error creating interceptor session`**

### Steps To Reproduce

1. Open postman. Version: 10.3.4
2. Install Interceptor, Interceptor Bridge
3. Start Capture Request.
4. Click on start capture
5. Error is observed.

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/42967267/202486213-4f44912f-8011-458f-b583-fe239a145b79.png)

### Operating System

Windows

### Postman Version

10.3.4

### Postman Platform

Postman App

**Comment by tabs** [comment]
same problem

**Comment by tabs** [comment]
nobody know why?

**Comment by kaivalyapendse** [comment]
@tabs  thanks for confirming that you are also facing the same.

**Comment by rohanamrutkar99** [comment]
Same issue I also observed

**Comment by shashankawasthi88** [comment]
Thanks for raising this folks. Looking into to and will update the thread.

**Comment by shivanimaheshwari10** [comment]
We've identified the issue and working on the fix. You can track updates here - https://status.postman.com/incidents/9279n71n3kvz

**Comment by shivanimaheshwari10** [comment]
We've fixed the issue, please upgrade the app to v10.3.5.

**Comment by kaivalyapendse** [comment]
Thanks @shashankawasthi88  and @shivanimaheshwari10. The issue is resolved and is confirmed by my team as well. Closing this issue.

**Comment by kuhajeyan** [comment]
issue seems resolved thx a lot team

**Comment by shashankawasthi88** [comment]
@kuhajeyan can upgrade the app and try again. The issue has been resolved.
