### ISSUE TITLE
Interceptor doesn't accept new domains

### ISSUE THREAD

**Issue by jaredromano** [a85/POSTMan-Chrome-Extension#11453]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Either from the Chrome extension or in postman I am unable to add new domains on the Sync Cookies tab.  If I click "Add Domain", nothing happens, the domain doesn't get added to the list and no error messages show. 

### Steps To Reproduce

From chrome extension:
1. Go to "Cookies" tab
2. Try and add a new domain

From Postman 
1. Go to Cookies
2. Go to "Sync Cookies" tab
3. Try and add a new domain

### Operating System

Windows

### Postman Version

10.3.4

### Postman Platform

Postman App

**Comment by shashankawasthi88** [comment]
@jaredromano thanks for raising the issue. We are looking into this.

**Comment by shashankawasthi88** [comment]
@jaredromano can you upgrade the app to the latest version and try again? We have fixed this issue in the latest release. Feel free to reopen the ticket if it is still reproducible.
