### ISSUE TITLE
Postman web: Update Email Address fails with message "Only alphanumeric characters and hyphens are allowed in username"

### ISSUE THREAD

**Issue by exe-atewinkel** [a85/POSTMan-Chrome-Extension#11456]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

I need to change the email address of my Postman account, as my old email address is still being forwarded but will be phased out at some point. However, when I try to update my email address in Postman web, it fails.

### Steps To Reproduce

1) In Postman web, go to profile settings -> Account and enter a new email address
2) Click "Update Email Address"
3) Sign in with existing credentials
4) Wait for the sign in to finish and an error message briefly appears in the bottom right corner, with title "Something went wrong" and message "Only alphanumeric characters and hyphens are allowed in username".

### Screenshots or Videos

![postman](https://user-images.githubusercontent.com/24291209/202678282-4bbe891b-9a11-4781-a6ec-c99e7e99e40e.png)

### Operating System

Windows 11

### Postman Version

10.1.2

### Postman Platform

Postman Web

**Comment by DannyDainton** [comment]
Hey @exe-atewinkel 

Tagging Support in this issue, to see if there is anything that can be updated internally to unblock you.

**Comment by postman-staff** [comment]
Hey @exe-atewinkel

Thank you for reaching out.

Sorry to hear that you are unable to update the email address.
I tried replicating the issue but was unable to replicate the issue on the Postman web app.

Could you please submit a support request(https://support.postman.com/hc/en-us/requests/new/) with us so that we will be able to check if the email address you are trying to update is an invalid/wrong email or an existing email?

Thanks!
via @Lincimary | Postman Support

**Comment by ArjunSingh-PM** [comment]
@exe-atewinkel Could you please check whether your existing username only contains alphanumeric characters and hyphens? If not, could you try updating your username before you update your email ID? Thanks.

**Comment by ArjunSingh-PM** [comment]
@exe-atewinkel This issue is not reproducible at our end. I am closing this issue for now as we have not heard back from you. Please let us know if you are still experiencing this issue after modifying the username. Thanks.
