### ISSUE TITLE
openapi2postmanv2 produces the collection without 

### ISSUE THREAD

**Issue by khazamov** [a85/POSTMan-Chrome-Extension#11460]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

The new version of openapi2postmanv2 produces the data without enclosing it into "collection" key

### Steps To Reproduce

1. Download API https://api.criteo.com/2021-07/marketingsolutions/open-api-specifications.json
2. Convert to collection:
openapi2postmanv2 -s 2021-07___oas.json  -o postman_2021-07.json -p -O folderStrategy=Tags,requestParametersResolution=Schema,optimizeConversion=false,stackLimit=50

3. Observe the resulting file postman_2021-07.json . 

The file can be imported via UI, but cannot be imported via API. 

### Operating System

mac

### Postman Version

10.0

### Postman Platform

Postman App

### Additional Context?

can be seen as a feature request too

**Comment by DannyDainton** [comment]
Hey @khazamov 

Could you please raise this as an issue on this repo https://github.com/postmanlabs/openapi-to-postman/issues

As this is not a Postman app-related issue, I will close this for now.
