### ISSUE TITLE
Postman API: check/uncheck query parameters on API.

### ISSUE THREAD

**Issue by maticardenas** [a85/POSTMan-Chrome-Extension#11466]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

We are currently working in some automation using `Postman API`, importing collections from OpenAPI specifications (`POST /import/openapi`) and updating them (`PUT /collections/{collection_uid}`).

What we observe, is that for apis with paths with query parameters, they are always all checked by default, weather they are all required or not. This is not ideal for cases where we have multiple filtering query parameters which are optional and that we most of the time don't want to submit.

![image](https://user-images.githubusercontent.com/12075970/203023370-ebbd7c8b-90df-456d-b437-635174016a10.png)

Is there a way somehow to update collections to make them have their query parameters checked/unchecked? 
When retrieving a json collection I don't see a field on the json structure which could make that possible, i.e:

```
"query": [
                                            {
                                                "key": "parcel_status",
                                                "value": "<integer>",
                                                "description": "Returns parcels that have the requested status. For a list of possible statuses, see the [Parcel statuses](https://api.sendcloud.dev/docs/sendcloud-public-api/parcel-statuses/operations/list-parcel-statuses) endpoint"
                                            },
                                            {
                                                "key": "tracking_number",
                                                "value": "<string>",
                                                "description": "Returns parcels that match a specified tracking number"
                                            },
```

Thanks in advance

### Steps To Reproduce

1. Perform an import of an OpenAPI specification through `POST /import/openapi` endpoint.
2. When imported, requests with query parameters have them all enabled by default.

### Operating System

macOS

### Postman Version

10.3.5

### Postman Platform

Postman App

**Comment by DannyDainton** [comment]
Hey @maticardenas 

Adding this as a feature request - We have the `disabled` property for the `Headers` and `Variables` that control that option via the Postman API but it seems to not be working for Query Params.

**Comment by maticardenas** [comment]
Hi @DannyDainton,

Thanks! Indeed it would be useful to be able to manipulate this somehow.

**Comment by petkostas** [comment]
Do you happen to have any updates on this? some of our consumers need further clarification because optional parameters and headers are enabled by default (and blank), leading to failed requests.

**Comment by maticardenas** [comment]
Hi! Is there any update about this issue?

**Comment by bogdaaamn** [comment]
+1

**Comment by shreyansp** [comment]
+1

**Comment by FlyveHest** [comment]
+1

**Comment by saulotoledo** [comment]
+1

**Comment by davidespihernandez** [comment]
Hi, @maticardenas!
This is working well, as far as I've been testing.
When you retrieve a collection with a request that contains disabled query parameters, this is what you get:

```
{
    "collection": {
        "info": {
            "_postman_id": "XXXXX",
            "name": "GitHub: Test query params request",
            "schema": "https://schema.getpostman.com/json/collection/v2.1.0/collection.json",
            "updatedAt": "2023-11-02T10:43:09.000Z",
            "uid": "XXXXXXXXX"
        },
        "item": [
            {
                "name": "Request with headers and query params",
                "id": "XXXXXX",
                "protocolProfileBehavior": {
                    "disableBodyPruning": true
                },
                "request": {
                    "method": "GET",
                    "header": [
                        {
                            "key": "x-api-key",
                            "value": "apikey",
                            "type": "text",
                            "disabled": true
                        }
                    ],
                    "url": {
                        "raw": "https://postman-echo.com/get?param2=value2",
                        "protocol": "https",
                        "host": [
                            "postman-echo",
                            "com"
                        ],
                        "path": [
                            "get"
                        ],
                        "query": [
                            {
                                "key": "param1",
                                "value": "value1",
                                "disabled": true
                            },
                            {
                                "key": "param2",
                                "value": "value2"
                            }
                        ]
                    }
                },
                "response": [],
                "uid": "XXXXXX"
            }
        ]
    }
}
```
Notice two things here:
- The query attribute in the request returns all the query variables in a list. The disabled ones have a field `disabled=true` in the object. If no disabled field is present, it is not disabled.
- The raw URL field contains only the not disabled parameters. In the example: https://postman-echo.com/get?param2=value2

If you send a `PUT /collections` with this payload but change the raw URL field to contain only the query string parameters you want to be enabled, and also send the disabled parameters with the `disabled=true` field in the query parameter data. The request will be changed properly and the query parameter will appear disabled in the UI.

In addition, the [PUT request](https://www.postman.com/postman/workspace/postman-public-workspace/request/12959542-470056b2-9bf0-4c29-aaf2-81cdcee2310b) also allows changing the field, but in that API the field is called `enabled`. If you pass the right data in the `url` and `queryParams` fields, the request will be updated properly.
