### ISSUE TITLE
Unexpected size limit on post in form value

### ISSUE THREAD

**Issue by scottball1968** [a85/POSTMan-Chrome-Extension#1146]
Using 3.0.0.6 on OS x Yosemite.

I encountered a limit on the form value of a x-www-form-urlencoded POST operation where the complete string being posted was truncated.

The value that I was attempting to add was 922604 characters in length while I was only able to post 524288 characters with POSTMan.

I was able to add the full value to a cocoa form value and post successfully.

**Comment by numaanashraf** [comment]
@scottball1968 This has been fixed in Mac App versions 4.5.0 and up.
