### ISSUE TITLE
GRPC Reflection: Same Proto Requested Multiple Times

### ISSUE THREAD

**Issue by josephdrake-stahls** [a85/POSTMan-Chrome-Extension#11475]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?
When a GRPC Reflection request is made, it appears that postamn will recursively look up proto files found in service definitions and the service definition dependencies.  When this happens, if the same proto file is used as an import in multiple other proto files or service descriptions, then that file is requested each time.  This can lead to the same files being requested 100+ times in a single reflection "batch" (click the "Using Server Reflection" button).

In complex topologies (or in the unfortunate case of visual studio, having the debugger attached), this can lead to timeouts or excessive wait times.  Paired with how postman will refresh the service definitions for each saved grpc request when the app is reopened can cause frustration.

### Describe the solution you'd like

Postman should be able to cache the proto file keyed by its full name per reflection batch per streaming request (currently postman doesn't make reflection requests in a streaming call, but should be considered for future for reverse proxies).  The "GetByFileName" reflection request doesn't contain any metadata to "route" the request, so it can be assumed that within the context of the batch/request, that multiple requests for a filename is the exact same file since the request would be identical.

### Additional context

Postman for Windows
Version 10.4.5
UI Version 10.4.5-ui-221122-0258
Desktop Platform Version 10.1.2
Architecture x64
OS Platform win32 10.0.19044

**Comment by codenirvana** [comment]
@josephdrake-stahls Thanks for reporting this issue.

We've identified the issue and already made a fix to avoid duplicate calls, will let you know once the fix is out.

**Comment by appurva21** [comment]
Hey @josephdrake-stahls!

We have made several improvements around server reflection, including this to improve the overall performance. You should start seeing these from v10.6.0.
