### ISSUE TITLE
On single click postman desktop app is not returning the updated response 

### ISSUE THREAD

**Issue by Indratejreddy** [a85/POSTMan-Chrome-Extension#11479]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

I had to double click every time to get updated response for my api. In my case I faced this issue for put api.

### Steps To Reproduce

1. choose put as api type.
2. give your data in json format for which you want to update.
3. click on send.
4. you will not see updated data from server.
5. again click on send to see updated data from server.
6. Updated response should work on first click but it is taking 2 clicks to do it. this is the bug 

### Screenshots or Videos

https://youtu.be/30HjEmaS6Y0

_No response_

### Operating System

windows

### Postman Version

v10.1.2 

### Postman Platform

Postman App

## I had to double click every time to get updated response for my api. In my case I faced this issue for put api. ##

![image](https://user-images.githubusercontent.com/66834653/203540306-11cfedd9-8878-4938-b169-0341283b2c96.png)

**Comment by DannyDainton** [comment]
@Indratejreddy Are you able to replicate this behaviour on a public endpoint like `https://postman-echo.com/put`?

Your request is very contextual and we have no way of knowing how that request is being handled on that local server. Did the first call return a `200` status code? Is there any logging on the server side that would give you more information about what's happening?

**Comment by Indratejreddy** [comment]
@DannyDainton you can watch video to understand the problem
Video:` https://www.youtube.com/watch?v=30HjEmaS6Y0`

you can clone my repo and try locally if you want to replicate it.

Repo link: https://github.com/Indratejreddy/ToDoApp and try to hit put with some dummy json data.

**Comment by DannyDainton** [comment]
Unless you can provide steps to reproduce the issue using a public API, that we can access rather than your own local project, there is not much we can do here. Do you get the same behaviour using Curl or a different tool?

I'm going to close this for now but if you can demonstrate this is happening with a non-locally implemented solution we can look to open it again.

**Comment by Indratejreddy** [comment]
Fine I will use Swagger. Thanks for your support 👍
