### ISSUE TITLE
<title>how to close automatically floow redirects when user  pm.sendRequest(loginUrl, function (err, response) {         console.log(response)     });

### ISSUE THREAD

**Issue by chungkui** [a85/POSTMan-Chrome-Extension#11478]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

<title>how to close automatically floow redirects when user  pm.sendRequest(loginUrl, function (err, response) {         console.log(response)     });

### Describe the solution you'd like

<title>how to close automatically floow redirects when user  pm.sendRequest(loginUrl, function (err, response) {         console.log(response)     });

### Describe alternatives you've considered

<title>how to close automatically floow redirects when user  pm.sendRequest(loginUrl, function (err, response) {         console.log(response)     });

### Additional context

<title>how to close automatically floow redirects when user  pm.sendRequest(loginUrl, function (err, response) {         console.log(response)     });

**Comment by DannyDainton** [comment]
@chungkui I'm going to close this as there is no information here - If you are reporting a bug or requesting a feature request please provide the necessary context.
