### ISSUE TITLE
Postman 3.0 unusable...

### ISSUE THREAD

**Issue by guy-brion** [a85/POSTMan-Chrome-Extension#1148]
Since I got the 3.0 update, I can't send any request anymore.

I kept my configuration (collections, history, environment) but when I hit the Send button on a request tab nothing happens. I tried with the url https://www.google.fr but nothing happens either.

I have this problem on my company's computer, I'm not the only one having this issue here. Maybe a problem with all the firewalls we have ?

Let me know if you need any information from my side.

Thanks !

**Comment by abhijitkane** [comment]
Can you enable the DevTools (http://blog.getpostman.com/index.php/2014/01/27/enabling-chrome-developer-tools-inside-postman/), and check if you see any error in the console or a request in the network tab?

**Comment by guy-brion** [comment]
Thank you for your help.

Here is a screenshot of the console output after I launched Postman. No errors are added when I hit the Send button :

![pb_postman](https://cloud.githubusercontent.com/assets/1124737/8161090/c9725140-1374-11e5-94b7-49b70bb5e6a8.PNG)

About the Network tab, I have the following error : 

![pb_postman_net](https://cloud.githubusercontent.com/assets/1124737/8177428/e92107c6-1404-11e5-8390-c81c6aff32d4.PNG)

**Comment by johnnavarra** [comment]
that's strange. why is ".map" appended to every url?

**Comment by guy-brion** [comment]
Any ideas about my issue ? :-(

**Comment by sobtiankit** [comment]
Hi,

This is quite odd, I don't see any exception in the console. Can you try uninstalling and reinstalling the app once? I'd HIGHLY recommend creating a backup of your data before doing so, or chrome will delete all your collections on uninstall. You can reimport from the same place.

Also, what version of Windows and Chrome are you using? I'll try replicating the configuration to see if it is reproducible.

![screen shot 2015-06-17 at 8 39 50 pm](https://cloud.githubusercontent.com/assets/547061/8210774/2b751db0-1531-11e5-81b5-4463554a9e36.png)

**Comment by guy-brion** [comment]
Hi sobtiankit,

Thank you for your help. I've uninstalled the app and downloaded it again but it didn't fix my problem :-(

Here is the versions displayed in the About tab of postman's setting : 
Version 3.0.0.6 (packaged)
OS: win
Architecture: x86-32
Native client architecture: x86-64

My configuration is Windows 8.1 Enterprise, 64 bit version, and Chrome 31.0.1650.63.

Hope this helps

**Comment by abhijitkane** [comment]
Some users had reported this problem earlier. We never did manage to get to the bottom of it. There's a workaround, though - 

You can enable the DevTools for Postman (http://blog.getpostman.com/index.php/2014/01/27/enabling-chrome-developer-tools-inside-postman/), and enter the following in the console:

`$('#submit-request').click(function () { pm.request.send("text"); }`

**Comment by guy-brion** [comment]
Thanks !

It's not really convenient but I just have to do it once after launching postman, so it's ok.

I juste had to change it for this :

```
$('#submit-request-big').click(function () { pm.request.send(); })
```

Should I leave this issue open as there is no fix for it yet ?

**Comment by abhijitkane** [comment]
Yes, you can leave it open. We're trying to replicate your exact environment to reproduce the problem.

**Comment by abhijitkane** [comment]
Can you try the solution one user posted here:

https://github.com/a85/POSTMan-Chrome-Extension/issues/712#issuecomment-75361332

**Comment by guy-brion** [comment]
I just checked and I already have the right configuration

**Comment by guy-brion** [comment]
Hi, I just wanted to know if you found where this issue comes from ? With the last update I now have an annoying popup that appears randomly asking me if Javascript is enabled :disappointed: 

Thanks

**Comment by abhijitkane** [comment]
The pre-request scripts and test scripts are run in a different execution context.  For some reason, jQuery isn't being loaded correctly there. Still not sure why.

**Comment by abhijitkane** [comment]
@guy-brion Can you try out the staging version of the app here - https://chrome.google.com/webstore/detail/postman/mgicbpdmnpnfckafakeoiomkjcplfcld

We've added a few debug statements when the app is loaded - checking the console when the app loads should provide some clues.

**Comment by guy-brion** [comment]
Hi, I'm sorry but I couldn't find the time to try the staging version.

But actually my problem is solved because my company finally updated Chrome to the 45 version, and now postman works fine. I guess the previous one was too old.

Thank you for your help !
