### ISSUE TITLE
OAuth2.0 - cannot open settings page

### ISSUE THREAD

**Issue by devin-lo** [a85/POSTMan-Chrome-Extension#11484]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

I can no longer open the OAuth 2.0 page to refresh any of my access tokens.
In fact, I can't even make a new request and then change the authorization type to OAuth 2.0, it just stops and says "Something went wrong"

The issue just started today for me.

Please see the additional details for the Developer Tools console log, which indicates there was an unhandled exception.

### Steps To Reproduce

1. Open a new request tab
2. Go to Authorization
3. Change type to OAuth 2.0

### Operating System

Windows 10 Pro 10.0.19044.1706

### Postman Version

10.5.0

### Postman Platform

Postman App

### Additional Context?

Developer Tools console log shows:

ReferenceError: AetherTooltip is not defined
    at A.getIcon (scratchpad.js:2)
    at A.render (scratchpad.js:2)
    at Bo (scratchpad.js:2)
    at zo (scratchpad.js:2)
    at _s (scratchpad.js:2)
    at vl (scratchpad.js:2)
    at ml (scratchpad.js:2)
    at sl (scratchpad.js:2)
    at scratchpad.js:2
    at t.unstable_runWithPriority (scratchpad.js:2)
    at Za (scratchpad.js:2)
    at Ja (scratchpad.js:2)
    at Ya (scratchpad.js:2)
    at j (scratchpad.js:2)
    at Jt (scratchpad.js:2)
    at HTMLDocument.o (scratchpad.js:483)
(anonymous) @ scratchpad.js:483
as @ scratchpad.js:2
i.componentDidCatch.n.callback @ scratchpad.js:2
mi @ scratchpad.js:2
cs @ scratchpad.js:2
wl @ scratchpad.js:2
t.unstable_runWithPriority @ scratchpad.js:2
Za @ scratchpad.js:2
El @ scratchpad.js:2
sl @ scratchpad.js:2
(anonymous) @ scratchpad.js:2
t.unstable_runWithPriority @ scratchpad.js:2
Za @ scratchpad.js:2
Ja @ scratchpad.js:2
Ya @ scratchpad.js:2
j @ scratchpad.js:2
Jt @ scratchpad.js:2
o @ scratchpad.js:483

**Comment by shubhbhargav** [comment]
@devin-lo Thanks for highlighting the issue. The team is working on the fix for this and it will be rolled out in a few hours for the latest version.
In the meantime, you can download the last stable version from the downloads page: https://www.postman.com/downloads/

**Comment by shubhbhargav** [comment]
@devin-lo We have rolled out a fix for this in desktop version 10.5.2. I am closing this issue for now. Please feel free to let us know if you are still facing this issue.
