### ISSUE TITLE
[gRPC] Unix Domain Socket partially broken

### ISSUE THREAD

**Issue by AlmogBaku** [a85/POSTMan-Chrome-Extension#11483]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

1. I'm able to use "gRPC reflection" with an unix socket
2. However, I can't evict the call itself

### Steps To Reproduce

1. create a gRPC service with `unix:///tmp/grpc.sock` as the address
2. call a method on this RPC

### Screenshots or Videos

![Uploading Screen Shot 2022-11-24 at 15.26.24.png…]()

### Operating System

MacOS

### Postman Version

10.2.2

### Postman Platform

Postman App

**Comment by codenirvana** [comment]
@AlmogBaku Thanks for reporting this.

We've identified the issue and will let you know once the fix is out.

**Comment by appurva21** [comment]
Hey @AlmogBaku!

This is now fixed in the latest version of the Postman app (v10.6.0)
