### ISSUE TITLE
Cannot share public workspace

### ISSUE THREAD

**Issue by jaanli** [a85/POSTMan-Chrome-Extension#11496]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Made a public workspace but the API is not showing up! We need this to collaborate and are currently limited to sending iterations of the API over github only: https://github.com/onefact/payless.health-api/blob/main/schemas/schema.proto instead of the nice Postman app :(

### Steps To Reproduce

1. Create a team workspace.
2. Make the visibility public in workspace settings: 
<img width="1250" alt="image" src="https://user-images.githubusercontent.com/5317244/204734439-5ea33e55-c400-42f3-9807-a5dc50feddc5.png">
3. Create a new API by importing this repository: https://github.com/onefact/payless.health-api/
4. Click on the share workspace link in the team workspace: 
<img width="844" alt="image" src="https://user-images.githubusercontent.com/5317244/204734544-6128d26b-c4ab-4d42-b1dc-b4d74e3a7fe6.png">
The copied link is https://www.postman.com/onefact/workspace/team-workspace
5. Open a new private window, go to the link, and try to click on the API that shows up:
![Uploading image.png…]()

### Operating System

mac

### Postman Version

latest

### Postman Platform

Postman Web

### Additional Context?

Working with @kulnor on this :)

**Comment by shashankawasthi88** [comment]
@altosaar for the consumers to be able to consume your API, you need to publish a version of the same. The 'published versions' are the snapshot of the API (schema and collections) at a point in time. This ensures that the consumers only look at the copy, that the producers are intending them to see see and not look at the head of the development. Documents [here](https://learning.postman.com/docs/designing-and-developing-your-api/versioning-an-api/api-versions/) should be helpful.

**Comment by altosaar** [comment]
Got it, thank you @shashankawasthi88 ! I didn't know we needed to publish first; just did so :) - now it appears fine at https://www.postman.com/onefact/workspace/team-workspace
