### ISSUE TITLE
gRPC variable expansion Incorrect Type error

### ISSUE THREAD

**Issue by Kevin-Kennedy** [a85/POSTMan-Chrome-Extension#11490]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

When using a collection variable with type number (e.g. 42) in a gRPC unary input with type uint32 (e.g. {{myVar}}, postman declares "Incorrect Type. Expected one of integer, null." and prevents the method from being invoked.

The IDE always had the yellow squiggles but was working.  The blocked invokation behaviour started within the past few weeks.

### Steps To Reproduce

1. pm.collectionVariables.set("myVar", 42)
2. Use a unary gRPC request with message input such as { "id": {{myVar}} }

### Operating System

macOS

### Postman Version

10.5.3

### Postman Platform

Postman App

### Additional Context?

<img width="1281" alt="Screen Shot 2022-11-28 at 5 00 22 PM" src="https://user-images.githubusercontent.com/33882621/204399521-1d224f3b-9cbd-4f2e-aab5-92ee387ad152.png">

<img width="1281" alt="Screen Shot 2022-11-28 at 5 03 00 PM" src="https://user-images.githubusercontent.com/33882621/204399532-c54ae69f-6c40-4e91-a65c-d2dc2c6b5a39.png">

<img width="1281" alt="Screen Shot 2022-11-28 at 5 04 15 PM" src="https://user-images.githubusercontent.com/33882621/204399676-25068fbd-ff93-4c76-9c9b-3026ad0bb700.png">

<img width="328" alt="Screen Shot 2022-11-28 at 5 05 41 PM" src="https://user-images.githubusercontent.com/33882621/204399713-7990b7d8-d917-4f19-aea1-0cc2904968d7.png">

**Comment by codenirvana** [comment]
@Kevin-Kennedy Thanks for reporting this issue.

I can reproduce the issue locally, we'll fix this soon!

**Comment by appurva21** [comment]
@Kevin-Kennedy This is now fixed in the latest version of the Postman App (v10.5.6). Feel free to re-open the issue in case you are still facing the problem.
