### ISSUE TITLE
I use to see my workspace flow and now I don't

### ISSUE THREAD

**Issue by natib613** [a85/POSTMan-Chrome-Extension#11498]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Hello,
My workspace is called **BigID Cloud** and I don't see the flows anymore, now what I see is the: "Flows is Coming soon!" message

things that I tried:
1. Re-new my membership in BigID Cloud 
2. Restart postman
3. Reinstall postman
4. Clear cache and reload
5. Open it in postman web
6. Restarting the computer
7. Google the issue

nothing helped

### Steps To Reproduce

1. Open Postman desktop
8. Go to Flows

### Operating System

macOS

### Postman Version

10.5.3

### Postman Platform

Both

**Comment by Lincimary** [comment]
Hello @natib613,
Thank you very much for reaching out to Postman Support. Happy to help.
 
I understand you can no longer access to Flows as it says "coming soon",Right?
Let me know if you have already had existing flows and seems to be missing now after the V10 upgrade?
 
I regret to advise that the behaviour you are experiencing may be related to a known issue, as reported in the GitHub issues thread as follows:
 
Stuck in the waitlist
https://github.com/postmanlabs/postman-flows/discussions/421
 
Apologies for any inconvenience this issue has caused you.  I will reach out internally to our engineering team to help further review your account to recheck the Flows enablement.    I will keep you informed when I have received any feedback.    
 
Please don't hesitate to let me know if you have any queries.

**Comment by natib613** [comment]
Hi @Lincimary it's not the same issue, it's even worse in my case because I don't see flows on the web also.... not on desktop and not on the web 

and yes I see the "coming soon"

**Comment by Lincimary** [comment]
Hi hello, 
Thank you for writing back!

Could you please submit a ticket(https://support.postman.com/hc/en-us/requests/new/) with us along with the GitHub issue number to check and investigate further?

**Comment by natib613** [comment]
Hi @Lincimary I submitted a ticket and hope for a quick response, any ideas to bypass it?

**Comment by Lincimary** [comment]
Thank you for submitting the ticket with us, I will close this conversation for now but we will further communicate with you on the internal ticket.
