### ISSUE TITLE
[feature] compact theme

### ISSUE THREAD

**Issue by cvmocanu** [a85/POSTMan-Chrome-Extension#1149]
I just updated from Postman 2.x to 3.x and the new theme looks good.

But there is one big usability/productivity problem: it takes way too much space.

Please create a compact theme that is optimized for productivity rather than for looks. I am using the light theme (easier on the eyes since all my other programs also have light themes), but you may want to create a compact dark theme also.

Currently most of the vertical space is taken by UI elements. I would rather have more space to inspect the request and response bodies and headers.

The new "Scroll to response" button should be a warning sign. With a compact theme there is less need to scroll.

Suggestions:
- decrease font sizes
- make the items in the list of collections at least 3 times smaller in height. Show the buttons to the right of the text. If they don't fit, collapse them into only one button that displays a menu when clicked. This suggestion optimizes the fact that most monitors are much wider than taller.
- make the top toolbar (the one having the buttons "Builder", "Runner", "Import" etc.) 1/2 (half) of the current height.
- make the request tabs around 1/2 of the current height
- make the method/url/params/send toolbar 1/2 of the current height
- minimize the vertical space between the elements. For example (and there are other places), there is way too much space between the method/url/params/send toolbar and the tab bar with headers/body/authorization
- make the headers/body/authorization tab bar 1/2 of the current height

In general, make it so that we can see more of the request/response and less of the generic UI (buttons, toolbars, tab bars, etc.).

The buttons don't need to be as big. I am using this during development, with a mouse.
I doubt many of us will need to use this on a tablet, where you need big buttons to be able to accurately click them.

**Comment by abhijitkane** [comment]
We'll be releasing a new version in a few days that's a lot more compact, and has the auto-scroll functionality disabled.

**Comment by cvmocanu** [comment]
Cool!
I can't wait to check it out :)

**Comment by cvmocanu** [comment]
I'm looking at the new theme in 3.0.0.9.
It's definitely improved. I no longer click by mistake on the edit (and other buttons) when trying to expand/collapse a collection.

But the current ticket is not yet fixed.
For example, I don't care about the number of requests or the modification date of the collection. Those just make a collection take double space on the vertical. Just one line, as for the folders, should be enough.
The rest of the elements can also be made smaller.

Having a compact theme that maximizes screen space (and thus productivity) would be much appreciated.
Thanks.

**Comment by andersks** [comment]
I would add one more comment to the UI, that is kind of an irritation. Double scrollbars (yuck).

The response window has scrollbars and so does the main window (Packaged app 3.0.2). It appears that the response panel is not being sized appropriately.

**Comment by aditikul** [comment]
@cvmocanu @andersks Can you check on the latest versions? We've worked to improve the spacing while keeping things legible and usable. Thanks.

**Comment by a85** [comment]
Everyone. You can now use Cmd + '-' to zoom out of the entire UI and see more of everything.
