### ISSUE TITLE
Flows escapes & in URLs

### ISSUE THREAD

**Issue by matthewdavidlloyd** [a85/POSTMan-Chrome-Extension#11500]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

When using Flows, I'm using the output of a previous step as the URL for the next request. The URL output from the previous step looks correct, but the URL in the next request escapes & (i.e. has \& in the query string).

This causes me to receive a 400 response from the API I'm using.

### Steps To Reproduce

Create a request:
![image](https://user-images.githubusercontent.com/10047384/204854196-e8258883-1388-457e-ad71-7af4660a2f54.png)

Create a flow:
![image](https://user-images.githubusercontent.com/10047384/204854255-ba034c73-126c-4fe7-9dee-c9bd4d5648c3.png)

Run the flow, and observe that the get request is to: `https://pokeapi.co/api/v2/pokemon?limit=10\&offset=10` and not `https://pokeapi.co/api/v2/pokemon?limit=10&offset=10`

### Operating System

macOS

### Postman Version

10.5.7

### Postman Platform

Postman App

**Comment by SterlingChin** [comment]
This issue has been fixed in the latest version of Flows (`v10.12.5`).

![Screenshot 2023-03-24 at 7 29 10 AM](https://user-images.githubusercontent.com/8900638/227521571-0b014273-1393-40d9-8f2a-ac9dd3ffbf3c.png)
