### ISSUE TITLE
Postman interceptor / client does not process base64 encoded cookies properly

### ISSUE THREAD

**Issue by vsabella** [a85/POSTMan-Chrome-Extension#1150]
Simple repro: send a Cookie header in a request with a cookie value containing an equals sign, such as 

Blah=123;MyCookie=1233== 

Which is a valid set of cookies for RFC6525

Notice that the cookies list on the response set a cookie missing the

**Comment by vsabella** [comment]
Missing the equals signs. This is not coming from the server as viewed through an intercepting proxy (fiddler) but instead from postman. Latest Chrome on MacOS Yosemite

**Comment by vsabella** [comment]
This is from adding the cookie header to a get/post request in Postman packaged, after snooping a valid cookie header from postman interceptor

**Comment by abhijitkane** [comment]
@vsabella Can you confirm this fixed in the latest version of the app / interceptor (v4.4.1 / v0.2.18)?

**Comment by sdnts** [comment]
This should be fixed in the latest version of the app (4.8+). You should be able to create cookies with the `=` sign in their value field.
