### ISSUE TITLE
Non-licensed user administrators

### ISSUE THREAD

**Issue by mfishermvbank** [a85/POSTMan-Chrome-Extension#11501]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

Working under guidance from regulators, we centralized user administration functions in our IT Department and have individuals dedicated to administering user access to all applications. They consume a Postman license in our environment.

### Describe the solution you'd like

A user administrator role that allows for adding/removing licenses and allowing partners into our Postman environment via the Private API Network. These users do not use APIs and need no access to the actual Postman functionality; only the ability to administer access. Since they do not need the Postman functionality itself, it would be good not to consume a license for user administration.

**Comment by ArjunSingh-PM** [comment]
Hi @mfishermvbank, does the following satisfy your request?

While members with a Developer consume a paid slot on your team, team members with only Admin or Billing roles become support users and don’t consume paid slots. **Each team can have two support users**.

Refer: https://learning.postman.com/docs/collaborating-in-postman/roles-and-permissions/

**Comment by mfishermvbank** [comment]
Thanks for getting back to me on this. That does indeed work. I invited an Admin and observed that she consumed a support user instead of a team member license. The role is a little more permissive than I was hoping for, but it addresses our immediate need.
