### ISSUE TITLE
Killing Postman and Chrome when trying to connect to proxy

### ISSUE THREAD

**Issue by KmeCnin** [a85/POSTMan-Chrome-Extension#1151]
A soon as we configure a proxy and click the "Connect" button, both Postman and Chrome windows are closed (instant kill).
The problem persist each time I try this.

**Comment by kresli** [comment]
Same here ( OSX ).

**Comment by pierreprinetti** [comment]
This happens to me when I enable the Postman proxy on a port that's already bound on the system.
OSX here too.

**Comment by sdnts** [comment]
Are you guys still experiencing this on v4.8?

**Comment by alexcaas** [comment]
Not anymore, now is working, tested 5 minutes ago, Thanks

**Comment by sdnts** [comment]
Awesome, closing this :)
