### ISSUE TITLE
Export/Import not working

### ISSUE THREAD

**Issue by lugospod** [a85/POSTMan-Chrome-Extension#11511]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

I am using Postman 10.5.7 (full version details below) and I exported the data using the form on the attached screenshot (export takes me to the Web site, where I waited for export to finish). Once export was finished, I received a ZIP file, which I tried to import. I received an error: "Format not recognized".

![image](https://user-images.githubusercontent.com/29342608/205441742-a24b9419-844e-444a-bccb-5c1cddb1303d.png)
![image](https://user-images.githubusercontent.com/29342608/205441811-1fe1c136-4034-4b4a-b021-78cd70358fcf.png)

Postman:
Postman for Windows
Version 10.5.7
UI Version 10.5.7-ui-221129-1459
Desktop Platform Version 10.5.2
Architecture x64
OS Platform win32 10.0.19045

### Steps To Reproduce

1. Open Settings -> Data
2. Request export
3. Download ZIP file to disk
4. Open Settings -> Data
5. Click on Import
6. Select the downloaded zip file
7. ERROR

### Operating System

Windows

### Postman Version

10.5.7

### Postman Platform

Postman App

### Additional Context?

My goal was to clone the workspace, so I wanted to Export the data, and hopefully use this to import into a new workspace - that is how I got to this problem (I am still not sure if this is the way to go to clone a workspace).

**Comment by DannyDainton** [comment]
Hey @lugospod 

Did you extract the contents of the ZIP file before trying to import it?

**Comment by lugospod** [comment]
Hi @DannyDainton ,
1. I would expect that the format in which the files were exported would be used to import. Seems like a normal process...
2. When You extract you get multiple directories, plus archive file... so I had no idea how would one do that manually without cherry picking files (plus had no idea if archive.json is important or just for show).. I know I can go into one directory and select all the files there and click import, that that is not what I would expect... I have to do the import in multiple actions then...
tnx for the help

**Comment by akshaydeo** [comment]
Hi @lugospod importing a zip file has its security concerns; hence, we have decided not to support zip file imports for the time being. We do support folder imports, though, i.e., you can drop a folder with multiple files and folders within it to import all that data into your Postman workspace.
