### ISSUE TITLE
imported OpenAPI yaml is missing properties

### ISSUE THREAD

**Issue by Daniel-GabrielN** [a85/POSTMan-Chrome-Extension#11519]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

When importing an OpenAPI  yaml schema, the response is missing properties
Using the same yaml in editor.swagger.io, vs code + OpenAPI extension or insomnia, it shows the expected result.

The example should show something like 
```json
{
  "jsonrpc": "2.0",
  "result": [
    {
      "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
      "name": "string"
    }
  ],
  "additionalProp1": {}
}
```

But it only shows
```json
{
  "jsonrpc": "2.0",
  "result": {}
}
```
Here is a sample yaml schema:
```yaml
openapi: "3.0.0"
info:
  version: "1.0.0"
  title: Pet Service
servers:
  - url: "http://localhost:3006"

paths:
  /v1/listPets:
    post:
      summary: Get Pets
      description: Retrieve the list of Pets
      operationId: listPets
      x-rpc-controller: pets
      tags:
        - Pets
      responses:
        "200":
          description: A list of Pets
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/JsonRpcResponse"
                  - type: object
                    properties:
                      result:
                        $ref: "#/components/schemas/ListPetResponse"

components:
  schemas:

    JsonRpcResponse:
      required:
        - jsonrpc
      additionalProperties: true
      properties:
        jsonrpc:
          type: string
          default: "2.0"
          example: "2.0"
          nullable: false

    Pet:
      required:
        - id
        - name
      additionalProperties: false
      nullable: true
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string

    ListPetResponse:
      type: array
      additionalProperties: false
      items:
        $ref: "#/components/schemas/Pet"

```

### Steps To Reproduce

1. Import the yaml schema
2. Navigate to documentation
3. Check sample response body

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/19334360/206019910-25de66ea-b470-4821-81ba-1d957e2f100e.png)
![image](https://user-images.githubusercontent.com/19334360/206020083-d519d31c-9e90-4382-87ea-f96ec31ba7ba.png)

### Operating System

Linux

### Postman Version

10.5.8

### Postman Platform

Postman App

**Comment by haribo256** [comment]
Same issue here, in fact this has been a pain for me. I would love it if Postman understood all my OpenAPI specs

**Comment by akshaydeo** [comment]
@Daniel-GabrielN @haribo256 thanks for reporting this. We are actively looking into this 🙇‍♂️

**Comment by VShingala** [comment]
@Daniel-GabrielN We've fixed this issue. Do try this out and let us know if you're facing any further issue here.

**Comment by Daniel-GabrielN** [comment]
@VShingala just tested this and it works as expected. Thank you and the team for fixing it :+1:
