### ISSUE TITLE
Duplicate collection variable is created if we set the variable by selecting from the 'Set as a variable' list

### ISSUE THREAD

**Issue by MoorthiRaj** [a85/POSTMan-Chrome-Extension#11517]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

If we try to set the variable from the request URL by selecting the existing collection variable (say baseURL) from the 'Set as a variable' list _then the duplicate variable is created in the Collection_.

**Note:** Here, the existing collection variable which we added before has both the **INITIAL VALUE** & **CURRENT VALUE** in it. The newly duplicated collection variable has only the **CURRENT VALUE** in it.

### Prerequisite:

- Ensure a new collection is created

### Steps:
1. Add 2 GET requests in the collection (follow **Postman API Fundamentals Student Expert** collection)
2. Now assign the variable for the baseUrl '_https://library-api.postmanlabs.com_' in the 1st API request
3. Verify a new variable is created in the collection level
4. Then set the baseUrl variable for the 2nd API request by selecting from the list
5. Observe duplicate variable  is created in the Collection

### Screenshots or Videos

![duplicate_collection_variable](https://user-images.githubusercontent.com/59739402/205854490-19582098-de04-45e2-af62-94ce0854c64e.png)

### Operating System

Windows 10

### Postman Version

10.4.2

### Postman Platform

Postman App

**Comment by giridharvc7** [comment]
@MoorthiRaj can you post a short video of what you are doing?

**Comment by MoorthiRaj** [comment]
Hi @giridharvc7 this issue is not reproducing in the Postman version **10.5.8**

We can close this bug
