### ISSUE TITLE
UI icon and Text are completely opposite in their behavior

### ISSUE THREAD

**Issue by Pawan808** [a85/POSTMan-Chrome-Extension#11516]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

When you open any workspace, and then hover on front of any of the below options;
Collections
APIs
Environments

You can see the icon showing is for Download/Export but text is showing as Import

### Steps To Reproduce

1. open any workspace, 
2. Then hover on front of any of the below options;
Collections
APIs
Environments

3. Observe and see the icon showing is for Download/Export but text is showing as Import

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/119920622/205840334-fc7749b2-202f-4efe-b9eb-30f6411db44a.png)

### Operating System

Windows

### Postman Version

10.5.6

### Postman Platform

Both

### Additional Context?

NA

**Comment by jeroen-vanderpoll** [comment]
This issue has been fixed.
