### ISSUE TITLE
SCOPE of the existing collection variable is coming empty in the prompt

### ISSUE THREAD

**Issue by MoorthiRaj** [a85/POSTMan-Chrome-Extension#11520]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

If we try to set the existing collection variable from the list to a new value, then the SCOPE is coming empty in the prompt. This issue is occurring only for the Collection level variable.

### Prerequisite:

- Ensure the Collection is created and it has 1 existing variable with value

### Steps:

1. Open a new request
2. Select the variable from the request URL
3. Mouse over on the collection variable in the prompt
4. Observe **SCOPE** is coming empty

### Screenshots or Videos

![col_scope_not_shown](https://user-images.githubusercontent.com/59739402/206107345-0b4f7e30-8ff4-49e8-a28b-b12e2efd4222.gif)

### Operating System

Windows 10

### Postman Version

10.5.8

### Postman Platform

Postman App

**Comment by DannyDainton** [comment]
Hey @MoorthiRaj 

Thanks for flagging this issue, I've raised in with the team. 🏆

**Comment by apoorvgupta03** [comment]
Hey, this issue has been fixed, please check
