### ISSUE TITLE
Alphabetize methods within a Collection Folder

### ISSUE THREAD

**Issue by thoffmann-fms** [a85/POSTMan-Chrome-Extension#11522]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

When adding a new Request to a Collections folder it ends up at the bottom and dragging it up to the desired position can be tricky if there are a lot of requests.

### Describe the solution you'd like

 It would save quite a bit of time if there was a ... menu on the Folder to sort the Requests alphabetically.  May want to A-Z or Z-A sort, too.
![image](https://user-images.githubusercontent.com/28546239/206232283-8496d245-f968-437e-8117-948117e70953.png)

### Describe alternatives you've considered

Manual dragging of requests.

**Comment by giridharvc7** [comment]
Closing this as this is a duplicate of #5222 , we'll post updates there
