### ISSUE TITLE
Unable to import collection run results

### ISSUE THREAD

**Issue by Raj-postman** [a85/POSTMan-Chrome-Extension#11528]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

After completing a collection run and exporting the results,  unable to import the run results back to Postman
The message seen is: Failed to import collection run.

### Steps To Reproduce

- Execute a collection run
- Export the results
- Attempt to import the same.
- You'll receive the error message.

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/47771757/206441965-2adccfe3-7aa1-42a4-ac91-ed032f1dbc7b.png)

### Operating System

Mac

### Postman Version

Version 10.6.0

### Postman Platform

Both

### User Account Type

Signed In User

### Additional Context?

_Filed by Product Support_
This is already being tracked by the team internally, this request is to let users who are facing similar issues be notified upon the fix.

**Comment by malvikach** [comment]
Hi 👋 
This bug is resolved in Postman version 10.9.0. I will be closing this ticket, please feel free to report in case of any issues faced while importing collection runs.
