### ISSUE TITLE
OAuth 2.0 token with client assertion

### ISSUE THREAD

**Issue by vijay-kr-bandi** [a85/POSTMan-Chrome-Extension#11526]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

acquire azure token using OAuth 2.0 authorization flow has no option to input "client_assertion" (i.e; using certificate instead of secret)

![image](https://user-images.githubusercontent.com/7876511/206312653-f9de2898-5e22-4a70-902d-a43a6ca5e492.png)

![image](https://user-images.githubusercontent.com/7876511/206312338-9c66bf0c-1096-41a3-9edf-3634e25a842d.png)

### Describe the solution you'd like

option to input client_assertion

**Comment by abhijeetborole** [comment]
Hey @VJ1243! Thank you for the patience! We’ve added the ability to customise your OAuth2,0 requests with Postman v10.13.
This is available under the `Advanced` section under OAuth2.0. With these changes, you can now add params to the headers, body and URL for token and refresh requests. You can also add query params to the auth request.

You can use this to attach the `client_assertion`.

![CustomOauthLow](https://user-images.githubusercontent.com/9638586/232849656-63e0297a-7bc3-4472-8ff3-04cf2f5df95e.gif)

If you have any Audience and Resource parameters, you can move them to the new editors with the Move Audience and Resource button.

![MoveAudAndResFlow](https://user-images.githubusercontent.com/9638586/232850201-59d30590-d7c7-41c1-94c7-9a1c77f1757b.gif)

Do let us know if you have any issues.

P.S. - For refresh parameters, these will be stored with the token and any changes will only be considered when you generate a new token

Postman app v10.13 is being rolled out will be available for everyone in couple of days
