### ISSUE TITLE
Stuck when hit https://postman-echo.com/get

### ISSUE THREAD

**Issue by Msarfaraz9m** [a85/POSTMan-Chrome-Extension#11523]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

When i hit Get request of postman with url _https://postman-echo.com/get_ page get stuck with "Sending Request".

I tried uninstalling, deleting all postman file but this issue not resolved.

### Steps To Reproduce

1: Create new Get request
2: Give url as https://postman-echo.com/get
3: Send the request

### Operating System

Windows

### Postman Version

10.5.2

### Postman Platform

Postman App

**Comment by DannyDainton** [comment]
Hey @Msarfaraz9m 

We will require more details and a recording of the behaviour for us to be able to start triaging this issue. 

<img width="1303" alt="image" src="https://user-images.githubusercontent.com/17089546/206438477-7692b955-f65d-40f3-bb27-31bb3405d02f.png">

**Comment by Msarfaraz9m** [comment]
Hi,

Uploading a video

**Comment by Msarfaraz9m** [comment]
If video not clear, or not understandable then let me know,

I will upload pic of setting and configuration

**Comment by Msarfaraz9m** [comment]
after more than one month this issue persists, but today i run console
query in pre-script and then it started working normally . Issue is
resolved in my system,

   - console.log()
   - console.info()
   - console.warn()
   - console.error()

Hopefully, you will be thinking WTH , but yes i am also thinking the same
WTH postman team has done. But this works perfectly without the above
console query now.
Thanks

**Comment by DannyDainton** [comment]
There was no video attached to the thread but also there was no mention of anything related to the console, in the original issue you raised.

Closing this issue as you seem to have things working now.
