### ISSUE TITLE
Additional ways to check for sensitive tokens being exposed in documentation

### ISSUE THREAD

**Issue by lbarry316** [a85/POSTMan-Chrome-Extension#11521]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

I'm having a problem at present because my documentation preview is very slow to load and is unresponsive (I have a Support ticket open about this). I am occasionally seeing the sensitive token warning but unfortunately because my doc preview is not loading fully I cannot scroll through the documentation to see where the highlighted text is indicating where the sensitive tokens are exposed.

### Describe the solution you'd like

It would be good to have an additional way of checking for sensitive tokens. Perhaps a way to export a list containing the sensitive tokens, or a way to click "Next" to cycle through them?

### Describe alternatives you've considered

I've asked Support who have said there is no other method right now to review exposed tokens.

### Additional context

Also, I am seeing the exposed token warning inconsistently - I sometimes see it in the Chrome or Brave browsers (but not always). I don't seem to see it in Firefox at present. Maybe this is related to the issue where my doc preview doesn't seem to fully load.

**Comment by akshaydeo** [comment]
Hi @lbarry316, we have reverted the recent change that might have caused the delay in rendering the complete documentation. 

Could you check again and update the ticket? 🙇‍♂️

**Comment by lbarry316** [comment]
Hi,
I have tested again this morning and the performance is much quicker - thank you for reverting the change.
I am no longer receiving the sensitive token warning so I am going to assume (and hope) it was a false positive due to the other issue.
I think it would still be a "nice-to-have" to be able to export/click next through the list of exposed tokens - but because we supposedly don't have any at the moment, this is not so much of an issue for me anymore.
I'll leave it up to you as to whether you want to leave the ticket open or not.
Thanks,
Lisa
