### ISSUE TITLE
Issue displaying response body in documentation in Postman

### ISSUE THREAD

**Issue by VaishnaviChallaPostman** [a85/POSTMan-Chrome-Extension#11527]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

The response body field is missing in the Postman documentation for Open API 2.0.

### Steps To Reproduce

1. Import the API - https://sign-sandbox.certeurope.fr/v2/api-docs 
2. View documentation
3. Check for the response body
4. Shows "*No response body"* in postman
  ![](https://postman.zendesk.com/attachments/token/CPjb5U6gJV4fBZe2FyB3wpew1/?name=image.png)
5. Even though we can see that in swagger -https://sign-sandbox.certeurope.fr/swagger-ui.html#/Certificate/getUsingGET
  ![](https://postman.zendesk.com/attachments/token/JJVPsBNKf093q2d2cADQrVuOr/?name=image.png)

### Operating System

macOS

### Postman Version

9.13.1

### Postman Platform

Both

### Additional Context?

Already being tracked internally. Raising this here for public visibility.

**Comment by VShingala** [comment]
@VaishnaviChallaPostman We've found the issue. It seems issue is only present with content-type of `*/*`. i.e. In definition all responses have `produces` field set as `*/*`. For a workaround, one can replace it with `application/json` which correctly generates responses for now.

We'll be working on this in meanwhile and let you know once we have fixed this.
