### ISSUE TITLE
Couldn't move collection to the different workspace

### ISSUE THREAD

**Issue by Sanady** [a85/POSTMan-Chrome-Extension#11530]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Trying to move one collection of endpoints to the newly created workspace but it can be done:

### Steps To Reproduce

1. Select the collection
2. Right-click, and press on the option to move
3. Select the workspace
4. Press the button "Move collection"

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/45435799/206479402-b69ee8c3-174c-4415-abd8-7f7a3456b7d2.png)

### Operating System

Windows

### Postman Version

10.5.8

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by preethammavin** [comment]
@Sanady can you write to us at help@postman.com, we can sort this out quickly.

**Comment by xk0der** [comment]
@Sanady we would prefer if you are able to log a ticket from here: https://support.postman.com/hc/en-us/requests/new/ - If that doesn't work, help@postman.com would be okay too. 

Do mention this GitHub issue's ID in the subject or description, so that we can get the full context quickly. Thank you
