### ISSUE TITLE
Didn't get the response from URL endpoint

### ISSUE THREAD

**Issue by heamnthnhk11** [a85/POSTMan-Chrome-Extension#11539]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

When I try to get the information from GitHub, I didn't get the exact response as given by organization url as endpoint. I get this kind of output with status: 200

Endpoint URL : https://{OrgURL}/api/repos/{Orgname}/{reponame}

Request:

{
    "default_branch" : "feature"
}

<!DOCTYPE html>
<html lang="en" data-color-mode="auto" data-light-theme="light" data-dark-theme="dark">

<head>
	<meta charset="utf-8">

	<link crossorigin="use-credentials" media="all"

### Steps To Reproduce

1. Open a new request

### Operating System

Windows

### Postman Version

9.14.0

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by postman-staff** [comment]
Hello **@****heamnthnhk11****,**

Would you be to advise whether this issue persists and provide a screenshot or screen recording of the behaviour?

via @loutsiros | Postman Support
