### ISSUE TITLE
allow for a side widget containing all the env variables used in that request easily changeable

### ISSUE THREAD

**Issue by davingee** [a85/POSTMan-Chrome-Extension#11532]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

N/A

### Describe the solution you'd like

while on a request allow for a side widget containing all env variables in a format that allows to change. have a little toggle to turn on and off the changes. these changes are only local. 

### Describe alternatives you've considered

currently i have to go into the env variable change then go back and change back when done testing

**Comment by skatikia** [comment]
@davingee, I know I'm too late to respond to your request. Sorry about that. But I'm replying with positive news!

I'm excited to let you know that with Postman **V11.14**, we have rolled out several variable updates, including **the ability to view all variables in a request in a single place**.

Click on that button next to the environment selector to bring up the variables pane that bubbles up the variables used in the request and also shows you all the variables accessible to you from different scopes (environments, collections and globals).

![variables-pane](https://github.com/user-attachments/assets/a1e30a7e-2ca1-40b8-b96e-c486de35c25a)

I hope you find this addition as helpful as we do!

Update your app to start working with the new variables pane and many more additions, and let us know what you feel ([over a call](https://calendly.com/shobhit-katikia/meet-with-shobhit) or just drop an email to [shobhit.katikia@postman.com](mailto:shobhit.katikia@postman.com)).

[Check out the Postman V11.14 release note](https://arc.net/l/quote/vtemyulc)
