### ISSUE TITLE
Make multiple requests at the same time parallel

### ISSUE THREAD

**Issue by GregorBiswanger** [a85/POSTMan-Chrome-Extension#11535]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

Several requests in a row are already possible. Several parallel requests would be important for a stress test (multi-thread support). See https://stackoverflow.com/questions/36157105/postman-how-to-make-multiple-requests-at-the-same-time

### Describe the solution you'd like

As is possible with Apache jMeter, for example. In the settings should simply be several threads to choose from.

**Comment by malvikach** [comment]
@GregorBiswanger Hi 👋  

We are looking at building this capability in Postman. Therefore, I want to understand your suggestion better. 

You are looking to run parallel threads that send the requests so you can load test your endpoints. Can you elaborate more on what kind of load you want to simulate (a couple of hundred of parallel threads vs thousands?). Also, are you looking to run these tests from your machine? What kind of output metrics are you interested to look at (Response times/ error rates, anything else etc.) 

I would love to discuss your use case in more detail. 

If you are interested, I would request you to block some time with me to talk about this. You can use [this calendly link](https://calendly.com/malvika-chaudhary/v10-feedback?month=2023-03) to send me an invite. 

Looking forward to your feedback.

Regards,
Malvika

**Comment by GregorBiswanger** [comment]
Hi,

thank you very much for your answer.

Yes, I just need a load test locally. There is already a solution for the cloud with your CLI. But I want to be able to run it locally from the desktop app. To see how my API can handle thousands of connections at the same time and how it behaves. A thousand views in a row wouldn't be that important to me now.

Best,
Gregor

**Comment by malvikach** [comment]
@GregorBiswange  thanks for the response 

I have some early prototypes that I would love to show you and get feedback on. Would you be interested in this? Please drop me a yes here (malvika.chaudhary@postman.com) if you like to. 😄 

Thanks again!

**Comment by malvikach** [comment]
Hi @GregorBiswanger 

Glad to update you that in the latest Postman release (version 10.15.1), we have released the API Performance Testing feature. You can now use Postman to simulate real world traffic and observe your API Performance Metrics.

Read more about this on our blog [here](https://blog.postman.com/postman-api-performance-testing/).

Thanks again for your feedback! Do let us know about your experience of using the feature. 

Cheers!
Malvika
