### ISSUE TITLE
GET request hanging on error even though response comes back immediately (Pretty View Parser error)

### ISSUE THREAD

**Issue by ToshioMagic** [a85/POSTMan-Chrome-Extension#1153]
I'm sending a GET request styled like so:

```
http://{{baseUrl}}/Items?$filter=CatNo eq 'ABC-123'
```

which renders as:

```
http://myURL.com/Items?$filter=CatNo%20eq%20%27ABC-123%27
```

When I click send Postman locks up for about 30 seconds. However, my API server responds immediately with a JSON object that I want (I can see it respond with Fiddler4). But, Postman (after unfreezing) tells me that there's an error and doesn't even run my test scripts. I've tried this for a simliar URL such as:

```
http://myURL.com/OtherItems?$filter=CatNo%20eq%20%271234-XX57%27
```

and Postman displays the response immediately with no problem and runs the test.

The console reads: 

```
15:49:49.344 - Uncaught RangeError: Maximum call stack size exceeded requester.js:26984
    Backbone.Model.extend.errorForce @ requester.js:26984
    window.onerror @ requester.js:26990
```

and

```
Uncaught RangeError: Maximum call stack size exceeded
    (anonymous function) @ jquery.min.js:3
    m.access @ jquery.min.js:3
    m.fn.extend.html @ jquery.min.js:3
    Backbone.View.extend.showJSONPretty_new @ requester.js:20548
    Backbone.View.extend.showJSONPretty_new @ requester.js:20607
    Backbone.View.ex..........etc.
```

That last line "Backbone.View.ex/  /ster.js:20607" is repeated about a hundred times in the error log, which leads me to believe there is a problem with Postman's pretty viewer and not my API or network. I've checked the syntax of the JSON object response and verified that it is correct JSON.

Right now, my workaround for this is to select either the Raw or Preview Tabs in the response Body section before clicking "Send." This allows the tests to run. But, a bug fix would be awesome.

Chrome Version 43.0.2357.124 m
Postman Packaged App Version 3.0.0.6
OS: win
Architecture: x86-32
Native client architecture: x86-64

**Comment by abhijitkane** [comment]
Can you send the raw response to help@getpostman.com?

**Comment by ToshioMagic** [comment]
Works beautifully after update. Thanks!
