### ISSUE TITLE
[Feature] Collection doesn't update when the API Definition is updated - V10

### ISSUE THREAD

**Issue by Postmanaut-Adrian** [a85/POSTMan-Chrome-Extension#11538]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

Feature Request associated with the following tickets: 

- Zendesk: #123887
- Jira: CUE-3467

Problem: Team's are unable to update their collections via API definitions, making the creation of a new collection necessary, which makes it so that any custom requests or elements not part of the definition are lost. 

### Describe the solution you'd like

Enable Element Validation via the API definition. 

This will enable collections to be updated based on changes on the API definition

### Additional context

Postman currently working on this via mentioned tickets.

**Comment by shashankawasthi88** [comment]
Hi All, this feature is now available in the latest Postman release that is being rolled out to all users. Refer the [blog](https://blog.postman.com/build-better-apis-using-the-new-and-improved-api-builder/) and the [document](https://learning.postman.com/docs/designing-and-developing-your-api/developing-an-api/adding-api-elements/#keeping-a-collection-in-sync-with-an-api) to learn more. Feel free to reopen and post the ticket if you have any feedback on the feature.
