### ISSUE TITLE
High cpu usage on Linux

### ISSUE THREAD

**Issue by avinash-sonawane-searce** [a85/POSTMan-Chrome-Extension#11534]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

I'm using Postman 10.5.2 on Ubuntu 22.04.1 LTS. Whenever I open Postman I immediately see CPU usage getting high without doing anything in Postman. This high usage is maintained till I close the Postman. 

I tried disabling hardware acceleration from Help > Disable Hardware Acceleration but it made no difference.

Here's the screenshot of System Monitor:
![postman](https://user-images.githubusercontent.com/114403635/206617029-2188e657-ad77-42a3-941f-bff1fedd56f3.png)

Here's the CPU graph screenshot showing the CPU usage immediately going down as soon as I close Postman:
![postman-2](https://user-images.githubusercontent.com/114403635/206617398-2decd4de-d6c2-4895-b875-f2d3b40c71b1.png)

### Steps To Reproduce

1. Just open Postman on Ubuntu 22.04.1 LTS
2. And look at system monitor

### Operating System

Linux (Ubuntu 22.04.1 LTS)

### Postman Version

10.5.2

### Postman Platform

Postman App

### User Account Type

Signed Out User

**Comment by jviotti** [comment]
Hey @avinash-sonawane-searce What were you doing with Postman at the time? Is the high CPU usage normal no matter what you do, or was it more of a one-off spike?

**Comment by avinash-sonawane-searce** [comment]
@jviotti As I have mentioned in the bug report I just open Postman and immediately CPU usage jumps to ~17-18% and it stays there till I close the Postman. It's not an one-off spike but a continuous high CPU usage by doing absolutely nothing in the Postman. I simply do nothing. Just open the Postman on Linux and take a look at system monitor.

**Comment by avinash-sonawane-searce** [comment]
The CPU graphs going down abruptly in the second screenshot is the exact moment when I close Postman.

**Comment by vitomeuli** [comment]
Same problem here as OP.
Linux XUbuntu 20.04 (XFCE)
Postman v10.6.7.
CPU goes to 17% in graphical process monitor, but htop shows many processes on postman command, the first at 138% of CPU usage.
I simply opened Postman, not doing anything with it.
Disabling hardware acceleration made no difference.

**Comment by phiexz** [comment]
Same problem here
Arch Linux 6.1.6-arch1
Postman version 10.8.0

Just open it and doing nothing
even tried to signing out and remove cache file
same behavior, CPU spike on 138%

**Comment by dalisoft** [comment]
on macOS same bug, i created bug for macOS #11636

**Comment by avinash-sonawane-searce** [comment]
Found the solution: Switch to [Insomnia](https://insomnia.rest/) - a free libre open source drop-in replacement of Postman which supports multiple protocols like HTTP, REST, GraphQL, gRPC, SOAP, WebSockets etc.

Been using Insomnia for a week now.

No more bitcoin mining on my machine! ;-)

**Comment by kamalaknn** [comment]
Hey @avinash-sonawane-searce 

We have addressed one of the common causes for high CPU usage in 10.18. Could you try the latest version?
