### ISSUE TITLE
When running flows give collection variable from API tests as output response

### ISSUE THREAD

**Issue by dchaitu** [a85/POSTMan-Chrome-Extension#11543]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

I have written my code logic in Tests and set a collection variable. But when I am running send request in flows the next block shows collection variables as undefined.

The collection variables are not creating or updating in the flows.

![image](https://user-images.githubusercontent.com/33480220/207270359-fd1e08e1-9462-43c8-8f2a-a32c868a2c72.png)
inflows

### Describe the solution you'd like

Adding a feature that gives API collection variables as output that

### Describe alternatives you've considered

Creating a variable and writing the entire code in FQL in flows will be confusing.

**Comment by RKroeze** [comment]
Same issue with environment and global variables
Updating environment variables using flows not supported -
Updating global variables using flows not supported -

**Comment by rabbah** [comment]
This is working as intended. You can define the variables in the Flow itself and pass/modify them between request.
