### ISSUE TITLE
URL Params truncating "=" when empty so valid query string ?key= becomes ?key

### ISSUE THREAD

**Issue by kcd83** [a85/POSTMan-Chrome-Extension#1154]
For url
- http://www.example.com?key=

Postman parses the url parameters then sends
- http://www.example.com?key

Some frameworks treat the first as empty and the second as missing/null. Which is odd but regardless postman should allow for retaining the = sign in the query string.

Even if only by hacking the Key under URL Params to be "key=". In fact Postman almost supports this workaround as the constructed url on the UI includes the equals sign but the request actually sent does not.

Alternatively a RAW query string option could be wise as the [RFC](http://tools.ietf.org/html/rfc3986#section-3.4) does not restrict the format, it is only HTTP form posts that created the convention of key=value pairs.

Postman is brilliant. I almost missed v3 as logical upgrade to original chrome extension and it has come a long way!

**Comment by abhijitkane** [comment]
We'll add a setting for this in a future release.

**Comment by kcd83** [comment]
Excellent, many thanks

**Comment by ghost** [comment]
Has support for this been scheduled for this? Alternatively, how can we direct people to the previous version?

**Comment by KobeLeysen** [comment]
This should be labeled as a bug.
Newer types of API's use more advanced types of Query parameters. 

RQL queries e.g. example.com/objects?in(fieldname,value1,value2,) are failing because this. (https://github.com/persvr/rql)

**Comment by abhijitkane** [comment]
@KobeLeysen What version of Postman are you using?

**Comment by KobeLeysen** [comment]
4.5.1
OS X 15.6.0 / x64

**Comment by abhijitkane** [comment]
Right. The Chrome app (v4.4.3) handles this correctly. We'll be pushing a fix for the Mac app soon.

**Comment by KobeLeysen** [comment]
@abhijitkane Thanks for the fast response!

**Comment by shamasis** [comment]
This has been fixed and ready for release in Mac app v4.6 tentatively scheduled for today. Will close it once released. Would love to receive a confirmation of the fix then. 😊

**Comment by shamasis** [comment]
This should be resolved now. Closing. Please reopen if otherwise.
