### ISSUE TITLE
Pressing Enter adds a cell to the right

### ISSUE THREAD

**Issue by nikitalk** [a85/POSTMan-Chrome-Extension#11547]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Pressing Enter adds a cell to the right, rather than going to the next row in the cell.

### Steps To Reproduce

1. Create a table
2. Stand in the cell
3. Press Enter

### Screenshots or Videos

![2022-12-14_17-38-43](https://user-images.githubusercontent.com/33490517/207625175-acf0ffe7-d668-4793-85ec-512317780393.png)

### Operating System

Windows

### Postman Version

v10.6.7

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by kamaraj-p** [comment]
Hi @nikitalk , thanks for reporting this issue. We are working on this and it should be fixed in the next release.

**Comment by kamaraj-p** [comment]
This issue is fixed in the latest release v10.12.0. Closing this issue, feel free to reopen if required. 🙏
