### ISSUE TITLE
Customize the OAuth 2.0 refresh token request to send custom parameters

### ISSUE THREAD

**Issue by giridharvc7** [a85/POSTMan-Chrome-Extension#11559]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

Is there a way to also pass back the client_id, client_secret and
redirect_uri on refreshing a token.

Only grant_tyoe and refresh_token are passed in the body. Our API would
like a few more details ;) Googling looks like other APIs also expect these
other fields to be passed back too when refreshing

Posting on behalf of  @davequested

### Describe the solution you'd like

Customize the refresh token request in OAuth flow to send parameters like client_id and client_secret

**Comment by savage-alex** [comment]
Salesforce for example can be configured to require the secret for a refresh https://help.salesforce.com/s/articleView?id=sf.remoteaccess_oauth_refresh_token_flow.htm&type=5

![image](https://user-images.githubusercontent.com/25430683/208108362-73ff1e05-08d4-4f2c-b9aa-4fbef2013ab5.png)

**Comment by davequested** [comment]
It seems pretty standard practice to at least include the client_id and client_secret in the body when using a refresh_token:

https://www.oauth.com/oauth2-servers/making-authenticated-requests/refreshing-an-access-token/
https://auth0.com/docs/secure/tokens/refresh-tokens/use-refresh-tokens

Would be great if we can also have redirect_uri to ;)

**Comment by picpicb** [comment]
It would be a great enhancement for confidential clients which are identified with the client_id parameter.

**Comment by jaytavares** [comment]
This would be really helpful. [Hubspot requires client_id, client_secret, and redirect_uri in addition to grant_type and refresh_token.](https://developers.hubspot.com/docs/api/oauth-quickstart-guide#refreshing_tokens)

**Comment by Tetradeus** [comment]
We are using Okta, and looking at the documentation, it seems that getting a refresh token also requires to send "redirect_uri" and "scope" parameters : https://developer.okta.com/docs/guides/refresh-tokens/main/#use-a-refresh-token

**Comment by IlliaMamonov** [comment]
+1, in my case I need to pass `client_id`, `client_secret`, `scope` in addition to refresh token

**Comment by trenslow** [comment]
I need to be able to pass `client_id` in the request body, as well as choose between basic or post authentication for this feature to work with auth0

related: https://github.com/postmanlabs/postman-app-support/issues/11668

auth0 docs: https://auth0.com/docs/secure/tokens/refresh-tokens/use-refresh-tokens

**Comment by richardsolid** [comment]
Yes please, in my case (Hubspot OAuth) I need to pass `client_id` and `client_secret` . Is there any workaround for refreshing the token automatically?

**Comment by kevin-james-sp** [comment]
Adding another vote - I need `client_id` sent on refresh; it seems logical that when `Send client credentials in body` is enabled, that they should be sent with any token request, whether it's new or refresh

**Comment by picpicb** [comment]
Any updates ?

**Comment by steve-christie** [comment]
+1

Have come across this issue while attempting to use refresh token given by AWS Cognito.

Cognito requires client_id and redirect_uri to be provided in request body in addition to grant_type and refresh_token.

Would be great to see the addition of these fields included automatically when seeking to use both the 'Auto-refresh token' option and the manual refresh option.

Temporary solution has been to use a Pre-request Script to perform a refresh on each request. With a bit of effort I could make this only happen when id_token has expired to save time.

**Comment by battlecow** [comment]
@steve-christie happen to have that script published anywhere? i'm also using cognito

**Comment by steve-christie** [comment]
> @steve-christie happen to have that script published anywhere? i'm also using cognito

@battlecow , here's the script. It'll require the refresh token to be placed into env vars somewhere after you've done the initial auth request, but once it's there, your new id and access tokens will be written into env vars if successful. If you know how to access the current refresh token from the auth tab with a postman keyword or some other function, that would be awesome, as well as writing the new access and id tokens back into the Auth tab rather than using env vars. 

```
tokenUrl = pm.variables.get('access_token_url'),
redirectUri = pm.variables.get('re_directURI'),
clientId = pm.variables.get('client_id'),
refreshToken = pm.variables.get('refresh_token'),
requestOptions = {
    method: 'POST',
    url: tokenUrl,
    body: {
        mode: 'urlencoded',
        urlencoded: [
            {
                key: 'grant_type',
                value: 'refresh_token'
            },
            {
                key: 'client_id',
                value: clientId
            },
            {
                key: 'refresh_token',
                value: refreshToken
            },
            {
                key: 'redirect_uri',
                value: redirectUri
            }
        ]
    }
};

console.log({ requestOptions });

pm.sendRequest(requestOptions, (err, response) => {
  let jsonResponse = response.json(),
      newAccessToken = jsonResponse.access_token;
      newIdToken = jsonResponse.id_token;
      
  console.log({ err, jsonResponse, newAccessToken, newIdToken })
  
  pm.environment.set('access_token', newAccessToken);
  pm.environment.set('id_token', newIdToken);
});
```

**Comment by Sweathered** [comment]
I also need to pass in client_id and client_secret when refreshing a token.  Is this something that the Postman team could implement?  Thanks!

**Comment by kalllol-1** [comment]
**Users are not able to automate authorization code (With PKCE) flow for collections!**

We will very much appreciate an enhancement where you send the  client_id in the Body as well in case you don't want to remove existing Authorization: Basic <base64-encoded-client-id> header if that is working for some orgs
I actually doubt how is that working for any org as there is nothing confidential about client id in authorization code flow as we have to use feature of Callback URL option of https://oauth.pstmn.io/v1/browser-callback. 

I attached a screenshot of where the feature needs to be enhanced by adding client_id as an additional request body key-value pair. here is how success will look like - 

POST https://<auth-server>/access_token
Request Headers
Content-Type: application/x-www-form-urlencoded
Authorization: Basic <client>
Request Body
grant_type: "refresh_token"
client_id: "<client>"
refresh_token: "<token1>"

Response 200
{"access_token":"<token2>","refresh_token":"<token3>","scope":"<scope>","token_type":"Bearer","expires_in":<nnn>}


![refresh-token-screen](https://user-images.githubusercontent.com/117538284/228968089-8fc825e5-7955-4559-b733-5f7a8db348fc.PNG)

**Comment by abhijeetborole** [comment]
Hey everyone! Thank you for the patience! We’ve added the ability to customise your OAuth2,0 requests with Postman v10.13.
This is available under the `Advanced` section under OAuth2.0. With these changes, you can now add params to the headers, body and URL for token and refresh requests. You can also add query params to the auth request.

![CustomOauthLow](https://user-images.githubusercontent.com/9638586/232849656-63e0297a-7bc3-4472-8ff3-04cf2f5df95e.gif)

If you have any Audience and Resource parameters, you can move them to the new editors with the Move Audience and Resource button.

![MoveAudAndResFlow](https://user-images.githubusercontent.com/9638586/232850201-59d30590-d7c7-41c1-94c7-9a1c77f1757b.gif)


Do let us know if you have any issues.

P.S. - For refresh parameters, these will be stored with the token and any changes will only be considered when you generate a new token

Postman app v10.13 is being rolled out will be available for everyone in couple of days
