### ISSUE TITLE
Cascaded Environments

### ISSUE THREAD

**Issue by SudipShresthaCiena** [a85/POSTMan-Chrome-Extension#11552]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

I have localhost, dev, test, DR, and prod environments. Localhost and dev are almost the same except for a few vars. If I add a new variable, I must add it to both environments.

### Describe the solution you'd like

If there was a way to parent-child cascade two environments where the child would use all parents' vars except where they are overridden.

### Describe alternatives you've considered

Keeping two separate environments.

**Comment by ankitjaggi** [comment]
@SudipShresthaCiena You can try using forks to solve this use case. A fork has a direct relationship with its parent environment and has the ability to both pull in changes from the parent as well as merge changes back into the parent. For more information, read [here](https://learning.postman.com/docs/collaborating-in-postman/using-version-control/forking-entities/).

**Comment by SudipShresthaCiena** [comment]
Thank you @ankitjaggi !
