### ISSUE TITLE
Lost Workspaces after updating to new version

### ISSUE THREAD

**Issue by gangavamshikiranoffice** [a85/POSTMan-Chrome-Extension#11554]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

After I update to new version of Postman. I cannot find other workspaces except "My Workspace"

### Steps To Reproduce

1. Select Workspaces from Menu in Postman App
2. Other Workspaces not visible

### Operating System

Windows 10

### Postman Version

10.6.7

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by preethammavin** [comment]
hey, can you write to us at help@postman.com from the same email as your postman account. This shouldn't have happened, we can help you better.
