### ISSUE TITLE
Intuitive API import errors

### ISSUE THREAD

**Issue by VaishnaviChallaPostman** [a85/POSTMan-Chrome-Extension#11565]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

As of now, API imports fail with "Failed to import data, format not recognised" error when the format is incorrect.
 It would be great if we can make this more intuitive by saying what went wrong in that file.

### Describe the solution you'd like

  Make the error messages more intuitive by saying what went wrong in that file.

**Comment by VShingala** [comment]
This issue has been fixed. Any user errors in definition while importing will be shown as tooltip in Import activity indicator. This error can be different depending upon definition type and error type.

Below is sample example showing the error.

![image](https://github.com/postmanlabs/postman-app-support/assets/16756296/a4c02d80-df6c-4ed3-901b-ebfc4a6d1782)
