### ISSUE TITLE
Postman app not launching (NOOB alert)

### ISSUE THREAD

**Issue by DOMcCrea** [a85/POSTMan-Chrome-Extension#1156]
Greetings,

I am completely new to POSTMAN and am struggling even to get it properly installed and running.  I installed version 3.0.0.6 into the Chrome App launcher according to proper procedure (I believe) on a Windows Professional 7 (SP1) laptop (Dell Latitude E5400) using IE 11 as my default browser (Chrome v43 is also loaded).  It took awhile to load but did not complain.  When I launch the app it appears on the task bar but no UI window ever materializes despite the exercise of extreme patience.  I have Googled for resolution (thence my arrival at GitHub) but to no avail thus far.  Any assistance would be appreciated.  Thanks in advance.

David

**Comment by DOMcCrea** [comment]
One additional update, a prior version of Postman (0.8.4.14) loads and runs fine however I need to work with a REST API that requires OAuth2 which this version does not support.  Thanks again in advance for any clues.

David

**Comment by abhijitkane** [comment]
@DOMcCrea Can you try to upgrade to the latest app (3.0.4)? chrome:/extensions -> Enable developer mode -> Upgrade.

**Comment by akhil-agarwal** [comment]
In chrome://extensions/, verify that Postman is enabled. Most likely, it was not.
