### ISSUE TITLE
Option to Roundup the ESIC component

### ISSUE THREAD

**Issue by sanjay141986** [a85/POSTMan-Chrome-Extension#11576]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

We have created a salary component and set a formula for ESIC component for payroll run which is set in salary structure. When we run the payroll, the system is round the amount for same component when we tick the checkbox for "Round to nearest integer" in salary component. When untick the "Round to nearest integer", the system shows values as it comes.

![image](https://user-images.githubusercontent.com/108865344/208818124-752e6987-5cb7-4a7e-8b47-6e004900ffc3.png)

e.g If calculated amount by formula is 100.12, the system shows 100 and if amount is 100.56, it shows 101 when checkbox for "Round to nearest integer" in salary component is ticked.

If we untick the same, the system shows 100.2 in first case and 100.56 in second case.

### Describe the solution you'd like

As per Gov. norm, the ESIC amount should be Round Up and not Round. i.e. in both the above cases, amount should be 101.

![image](https://user-images.githubusercontent.com/108865344/208818193-37eb1974-a590-4ad7-9458-8ad5d29a1de7.png)

**Comment by numaanashraf** [comment]
Hi @sanjay141986. This is the feature and issue tracker for Postman - https://www.postman.com. Your request doesn't seem related to any Postman product. Closing this issue.
