### ISSUE TITLE
Allow Comment in JSON under Body

### ISSUE THREAD

**Issue by hlavingia** [a85/POSTMan-Chrome-Extension#11570]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

Currently, Postman body allow me write JSON with commented line highlighted as green and doesn't show red line for the error but when I post the request it will fail with the error. It would be good if Postman can handle the comment line and allow me to keep few properties commented that I can enable and disable during development and save entire content.

Currently, I need to keep the full JSON object in notepad and copy-paste a few different variations every time. 

If Postman don't want to handle commented lines under body than what is the point of supporting the UI which turns the font to green for those lines.

### Describe the solution you'd like

Currently, Postman body allow me write JSON with commented line highlighted as green and doesn't show red line for the error but when I post the request it will fail with the error. It would be good if Postman can handle the comment line and allow me to keep few properties commented that I can enable and disable during development and save entire content.

Currently, I need to keep the full JSON object in notepad and copy-paste a few different variations every time. 

### Describe alternatives you've considered

I found a temporary solution to do it using Pre-request Script with the following line in it and define json object here with commented line under this tab instead of body. But this step is too cumbersome and see if Postman can provide user friendly solution.
pm.environment.set(“object”, JSON.stringify(object));

**Comment by arvindn05** [comment]
better to support multiple bodies in the request similar to https://github.com/postmanlabs/postman-app-support/issues/11163 IMO or see https://github.com/postmanlabs/postman-app-support/issues/9612

**Comment by ashuvyaspm45** [comment]
Hello @hlavingia 
Thank you for your patience for this feature. We have added the comment support in raw json body editor in latest release (Postman v10.13). Please check this out and give us the feedback.
