### ISSUE TITLE
Option Needed in Salary slip to show the Deduction till Date as similar to Gross Year to Date

### ISSUE THREAD

**Issue by sanjay141986** [a85/POSTMan-Chrome-Extension#11575]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

We are facing an issue when we try to calculate total deduction till date or month. As we are getting details of Total Earnings till Date in Earning case i.e. "Gross Year To Date", we are not getting to know Total Deduction till Date in Deduction case. It is needed to show on Salary Slip as per mandate. We are trying to search the same field on salary slip, we did not get the same.

![image](https://user-images.githubusercontent.com/108865344/208817732-0e526676-b305-4c65-bd84-e49cdc83fb17.png)
the 

### Describe the solution you'd like

Need a field in the Salary slip where it shows the Deduction till date

**Comment by numaanashraf** [comment]
Hi @sanjay141986. This is the feature and issue tracker for Postman - https://www.postman.com. Your request doesn't seem related to any Postman product. Closing this issue.
