### ISSUE TITLE
Missing slack channel while adding new integration 

### ISSUE THREAD

**Issue by Dekunledev** [a85/POSTMan-Chrome-Extension#11577]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

I recently set up a monitor on my team workspace (https://flw-devex-team.postman.co) and I tried to add a slack integration to send my monitor run result to a specific slack channel on my Organizations slack workspace, but after authorising postman I am unable to view the specific slack channel from the channel name drop down.

note that postman has been invited to the channel in question.

### Steps To Reproduce

1. Navigate to monitor details
2. click on "view more options" under send monitor results
3. select slack integration
4. it redirects to the web page and you click on allow 
5. after being authorised, navigate back to the postman app to fill in the new integration details
6. under "channel name" on the new integration form I can't find the specific channel I want the results to be sent to. (even after I invited postman to the channel)

### Screenshots or Videos

<img width="1440" alt="Screenshot 2022-12-20 at 13 24 51" src="https://user-images.githubusercontent.com/98256907/208881219-4ee2e2b5-fd60-479e-bbb5-a3d9f36a2feb.png">

### Operating System

macOS

### Postman Version

10.6.7

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by shashankawasthi88** [comment]
@Dekunledev thanks for raising the issue. We are looking into it and update the thread once we have some updates.

**Comment by Dekunledev** [comment]
Hi Postman
I'm still awaiting feedback on this issue

**Comment by shashankawasthi88** [comment]
Hi @Dekunledev - we are in process of rolling out the fix for this issue. It will take a few more days, we will update the thread as soon as the fix is out.
Thanks

**Comment by shashankawasthi88** [comment]
@Dekunledev this should be addressed now. Feel free to reopen the issue if you are still facing the issue.

**Comment by Dekunledev** [comment]
Thank you @shashankawasthi88 
It worked fine 🤗
