### ISSUE TITLE
Recursive variables are not resolved in scripts

### ISSUE THREAD

**Issue by Skefrep** [a85/POSTMan-Chrome-Extension#11589]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

When using `pm.variables.get("variable_name")` in a pre-request script or a test, the variables are not fully resolved if they are defined by another variable.

### Steps To Reproduce

1. Create an environment variable `foo` valued with `foo_value`
2. Create a second variable `bar` valued with `{{foo}}_modified`
3. In any scripting environment, `pm.environment.get("bar")` will return `{{foo}}_modified` instead of the expected `foo_value_modified`.

### Operating System

Windows

### Postman Version

10.6.7

### Postman Platform

Postman App

### User Account Type

Signed In User

### Additional Context?

This might be especially annoying when writing URLs.

Issue #6613 seems quite similar but only mentions the display, not the scripting.

**Comment by DannyDainton** [comment]
Hey @Skefrep 

Does this work:

```
console.log(pm.variables.replaceIn('{{bar}}'));
```

<img width="803" alt="image" src="https://user-images.githubusercontent.com/17089546/209113815-6d2f3fae-6bdc-4790-a96e-ad55ae694ec3.png">


In the environment file, it's saved as a `string` so it would only get what you have saved in the value. You need to use `.replaceIn()` to resolve any variables that you might have within that string value.

https://learning.postman.com/docs/writing-scripts/script-references/postman-sandbox-api-reference/#using-environment-variables-in-scripts

**Comment by Skefrep** [comment]
Yes, it's working. Thanks for the quick reply!
