### ISSUE TITLE
Protobuf having enums with aliases crashes the gRPC request

### ISSUE THREAD

**Issue by bizantom** [a85/POSTMan-Chrome-Extension#11587]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

I am unable to create a gRPC request on my local gRPC server.

After clicking on New > gRPC request, I enter the URL of the server, I select the API (if already created, either I import the proto file). Then after selecting a method I get the following error:
<img width="469" alt="Screen Shot 2022-12-22 at 9 24 17 AM" src="https://user-images.githubusercontent.com/6225042/209090369-81ff908b-fdf6-4e01-8253-cf1525678631.png">

### Steps To Reproduce

1. Click on the new button
2. Select gRPC request
3. Enter the URL
4. Import the prot file
5 Choose a method

### Screenshots or Videos

https://user-images.githubusercontent.com/6225042/209091486-f18dbeb8-af4d-4644-9150-f60a1f009b3f.mov

### Operating System

macOS

### Postman Version

10.5.8

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by codenirvana** [comment]
@bizantom Could you please share the [logs](https://support.postman.com/hc/en-us/articles/360025298633-How-to-get-logs-from-the-Postman-Desktop-app) along with a scaled-down proto file that we can use to reproduce this issue at [help@postman.com](mailto:help@postman.com).

**Comment by bizantom** [comment]
Here it is!
[_proto.zip](https://github.com/postmanlabs/postman-app-support/files/10285868/_proto.zip)

**Comment by appurva21** [comment]
@bizantom Thank you for sharing the details! 

We have identified the issue and also verified the fix internally. This will be rolled out soon as part of Postman app v10.7.0.

**Comment by bizantom** [comment]
Thanks @appurva21 !
Do you have an idea about the release date of the version v10.7.0 ?

**Comment by shamasis** [comment]
Any day now. 😊

**Comment by appurva21** [comment]
@bizantom Thanks for your patience! The fix is now available in the latest version of the Postman App.

**Comment by JoHyukJun** [comment]
I have exactly the same issue. I attached the log file, so please check it.

Operating System

macOS

Postman Version

v10.7.1

Postman Platform

Postman App

User Account Type

Signed In User

Additional Context?

No response

[postman_logs.zip](https://github.com/postmanlabs/postman-app-support/files/10398838/postman_logs.zip)

**Comment by bizantom** [comment]
Tested and approved!
Thanks @appurva21 .
