### ISSUE TITLE
[feature] request - pre-request script applied to entire collection

### ISSUE THREAD

**Issue by johnnavarra** [a85/POSTMan-Chrome-Extension#1159]
requesting an option to apply a pre-request script to apply to an entire collection. This is helpful in instances where a custom authentication needs to be calculated for a request.

**Comment by jaybillhighway** [comment]
Love to see this added, right now I am cutting and pasting JS code

**Comment by vinise** [comment]
I wish this as well :+1: 
Shouldn't be a good idea to have global script as well? callable insode each request :)
(include external script/library as well)

**Comment by kajo123** [comment]
Yep, I'd love this too!

**Comment by clinch** [comment]
I'd like to see this as well. Basically just need a way to include a chunk of code for both pre-request and also tests and associate it with a collection, rather than an individual request. That would save a lot of cutting and pasting.

**Comment by AramilRey** [comment]
I'd love to have this feature too!!

It would be nice, for example, to add pre-request scripts to the collection and then in each request choose from the scripts added on the collection where it belongs, so if I need to change something from a script I don't need to do it on every request!

**Comment by stevemcmillen** [comment]
[This gitlab issue](https://github.com/postmanlabs/postman-app-support/issues/1180) helped me figure things out: 

I have a single function that I use across many many APIs.  Updating all APIs every time I make a single change to one of the function gets *REALLY* cumbersome.

You can encapsulate the function in a variable stored in globals and then evaluate that in each API you need to use it in

So for example, I have the following stored in "HMAC2" in globals:

    Variable name: "HMAC2"
    Value:  HMAC2 = function() { console.log("TEST HMAC2") }

Just so its super clear here is a screenshot in the globals dialog:

![image](https://cloud.githubusercontent.com/assets/2750330/22634660/e0fcfe0a-ebe0-11e6-8118-2eea361d2b00.png)

Then in the pre-request script you evaluate it as follows:

    eval(postman.getGlobalVariable("HMAC2"));
    HMAC2() // This prints "TEST HMAC2" into the console log

I'm still working out why my real life function gets the following error :(

    SyntaxError: Unexpected end of input

**Comment by sdnts** [comment]
@stevemcmillen Try this: `eval('(' + postman.getGlobalVariable("HMAC2") + ')')`

**Comment by stevemcmillen** [comment]
@madebysid, Thanks. I got it working.

**Comment by carl-parrish** [comment]
+1

**Comment by a85** [comment]
Collection level scripts are now available in Postman 5.5+! Docs at www.getpostman.com/docs coming soon.
