### ISSUE TITLE
Minimize,maximize and close buttons don't appear on title bar when the width of the window is reduced

### ISSUE THREAD

**Issue by emredav** [a85/POSTMan-Chrome-Extension#11594]
### Is there an existing issue for this?

- [x] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

When the width of the application window is reduced, the minimize, maximize, close buttons do not appear

![image](https://user-images.githubusercontent.com/65634861/209687733-26b3d132-fcba-4498-996a-ea04bacc4cdd.png)

It appears when scrolling, but this is not desired in a desktop application. Minimize, maximize, close buttons should always appear.

### Steps To Reproduce

1- Open postman(Version 10.6.0, Architecture x64, Platform win32 10.0.19045)
2- resize(reduce horizontal width)
 

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/65634861/209688055-de284e00-624f-421a-bf2d-2ff651e89a2a.png)

### Operating System

Windows 10 

### Postman Version

10.6.0

### Postman Platform

Postman App

### User Account Type

Signed Out User

**Comment by diptarag** [comment]
Hey @emredav thanks for reporting this, we are already aware of this and actively working towards a better experience. In the meantime, can you please check if you are able to use the maximize, minimize and close buttons when you scroll to right?

**Comment by diptarag** [comment]
The issue should be fixed in v10.14
