### ISSUE TITLE
Bank Balance Chart for multiple accounts

### ISSUE THREAD

**Issue by sanjay141986** [a85/POSTMan-Chrome-Extension#11596]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

Currently, When we make the Dashboard Chart for Banks we can able to make the chart for single Bank only, There is no provision to create a chart for multiple Bank

![Screenshot 2022-12-29 at 1 26 03 PM](https://user-images.githubusercontent.com/108865344/209922238-89e4aefa-24e3-48f5-b4dd-a7a7a267f94a.png)

### Describe the solution you'd like

Required an option to create a Dashboard for multiple bank in single chart

**Comment by giridharvc7** [comment]
@sanjay141986 Have you tried using [Visualizers](https://learning.postman.com/docs/sending-requests/visualizer/) in Postman

**Comment by DannyDainton** [comment]
Hey @sanjay141986 

I'm going to close this as it doesn't appear to be related to the Postman platform. Please provide more details if this isn't the case but for now, I'm going to close the issue.
