### ISSUE TITLE
Minimize,maximize and close buttons style broken window MacOS Ventura

### ISSUE THREAD

**Issue by 0x14Rp** [a85/POSTMan-Chrome-Extension#11598]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

When I opened postman it looks like that buttons overlay on head menu 

Postman version 10.6.0

MacOS Ventura 13.1

### Steps To Reproduce

1. Open Postman
2. Open any other software
3. see the error buttons 

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/20388984/210122681-a2b16f23-4b98-4e32-b73f-42192481243a.png)

### Operating System

MacOS Ventura 13.1

### Postman Version

10.6.0

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by diptarag** [comment]
Hey @0x14Rp thanks for reporting the issue. We are working towards a fix. Can you please check if the traffic lights are in proper position when you switch to a workspace or scratchpad?

**Comment by diptarag** [comment]
The issue should be solved in Postman v10.8+
