### ISSUE TITLE
Empty query body and variables for GraphQL examples in documentation  

### ISSUE THREAD

**Issue by tinkermakar** [a85/POSTMan-Chrome-Extension#11592]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

When saving a GraphQL query as an example, it misses query body in Postman's auto-generated documentation. E.g. when documentation's language is set to curl, the body is exampled like so: `--data-raw '{"variables":{}}'`

### Steps To Reproduce

1. Create new collection 
1. Create new request
1. Add the following data to it:
    - Method: GET
    - URL: https://swapi-graphql.netlify.app/.netlify/functions/index
    - Body type: GraphQL
    - Query:
        ```gql
        query Person($personId: ID) {
          person(id: $personId) {
            id
            name
            gender
            birthYear
          }
        }
        ```
    - GraphQL Variables:
        ```json
        {
          "personId": "cGVvcGxlOjE="
        }
        ```

1. Press Code. The expected Code Snippet in `cURL` should look so:
    ```bash
    curl --location --request GET 'https://swapi-graphql.netlify.app/.netlify/functions/index' \
    --header 'Content-Type: application/json' \
    --data-raw '{"query":"query Person($personId: ID) {\n  person(id: $personId) {\n    id\n    name\n    gender\n    birthYear\n  }\n}\n","variables":{"personId":"cGVvcGxlOjE="}}'
    ```

1. Send the request. Expected response:
    ```json
    {
      "data": {
        "person": {
          "id": "cGVvcGxlOjE=",
          "name": "Luke Skywalker",
          "gender": "male",
          "birthYear": "19BBY"
        }
      }
    }
    ```

1. On the right corner above the response press `Save Response`, then press `Save as Example`
1. press the context menu of the collection, then press `View documentation`
1. Set Language to `cURL` (the issue is present on all languages though)
1. Check the example request's Request section

**Expected result**
The example request's `--data-raw` parameter should be a JSON object that contains `query` and `variable` values, just as the Code snippet mentioned above does

**Actual result:**
The example request's `--data-raw` parameter is empty. It is always set to `'{"variables":{}}'`

### Screenshots or Videos

![Screenshot from 2022-12-24 23-36-42](https://user-images.githubusercontent.com/68788448/209449218-cb2075cb-335b-451b-bb25-151454ce290a.png)
![Screenshot from 2022-12-24 23-37-03](https://user-images.githubusercontent.com/68788448/209449220-28b434cd-3836-41a2-8f72-85b02908ef2f.png)

### Operating System

Linux

### Postman Version

9.31.0

### Postman Platform

Postman Web

### User Account Type

Signed In User

**Comment by sonnd08** [comment]
I still got this issue today. Why this issue being closed?
