### ISSUE TITLE
Ability to copy or duplicate an existing saved request.

### ISSUE THREAD

**Issue by rrice** [a85/POSTMan-Chrome-Extension#116]
As a user, given that I have an existing request.  I'd like to duplicate that request with a new name and be able to edit it.

EDIT: Sorry. I just realized you can "Add to collection" and edit the name. It is not apparent that I can do that, though.

**Comment by ghost** [comment]
Did this ever happen, please?

**Comment by sdnts** [comment]
You have been able to duplicate requests & collections for a while now. Just hover over the request in question, open up the dropdown menu by clicking the three dots on the right end of the request, and choose  `Duplicate`
![screenshot 2016-08-16 10 36 02](https://cloud.githubusercontent.com/assets/7689783/17688484/43bada70-639d-11e6-8021-1d55594c1b2e.png)

**Comment by ghost** [comment]
Thank you for the description and visual. I was looking and clicking all around the tabs, not the sidebar.
