### ISSUE TITLE
When will internationalization be launched?

### ISSUE THREAD

**Issue by qq12157138** [a85/POSTMan-Chrome-Extension#11600]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

You don't know how many users there are in the world, do you?
It's not hard to adapt to internationalization, right?
Why hasn't it been so long?

### Describe the solution you'd like

You don't know how many users there are in the world, do you?
It's not hard to adapt to internationalization, right?
Why hasn't it been so long?

**Comment by numaanashraf** [comment]
Duplicate of #3126
