### ISSUE TITLE
Unable to export JSON collection on Linux app

### ISSUE THREAD

**Issue by dfranklin-at-bg** [a85/POSTMan-Chrome-Extension#11605]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Environment: Ubuntu 18.04, Postman app v9.31.26, installed via snap.

Prior to v10, I used to be able to export a collection as JSON file or as a link. Now, however, I cannot. From the Share dialog box, it requires I update to v10.0.0 but according to the app, I am on the latest version. 

If I click on the "Update" button (even though Settings indeed says I'm on the latest version), it just hangs forever, never updates. 

![no-version-10](https://user-images.githubusercontent.com/91911658/211386356-d68ee99d-4ed4-47de-ae0c-2b26e93fe57c.png)
![never-updates](https://user-images.githubusercontent.com/91911658/211386357-3051e67b-a11e-4c44-aa67-398fdb95f417.png)
![cannot-share](https://user-images.githubusercontent.com/91911658/211386359-db036405-dc6d-4a22-ae01-7ee6d1335802.png)

### Steps To Reproduce

Install app on Ubuntu 18.04
Create a collection
Share the collection
Go to the "Via JSON Link" option (note, in the new release it looks like it's supposed to be called "Via API")
The "Get collection JSON using collection access key" functionality does not work; cannot share; it's saying I need to update the app.

### Operating System

Linux

### Postman Version

9.31.26

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by dfranklin-at-bg** [comment]
Looks like I can get there via the web interface (logged in via Chrome) but it is not an option on the native Linux app. So I'm not completely blocked, but it looks like the Linux app needs to be brought to v10.0.0.

**Comment by DannyDainton** [comment]
The `v10/stable` version as it `10.1.2` on snap. - https://snapcraft.io/postman

Have you tried installing via:
```
snap install postman --channel=v10/stable
```

**Comment by dfranklin-at-bg** [comment]
All good, thank you @DannyDainton this can be closed as Invalid. One little change, I already had v9/stable installed, so it was just snap `refresh` rather than `install`, but all good. :+1: 
> The `v10/stable` version as it `10.1.2` on snap. - https://snapcraft.io/postman
> 
> Have you tried installing via:
> 
> ```
> snap install postman --channel=v10/stable
> ```
