### ISSUE TITLE
Pop up for public account needed to fork not visible when using the fork collection modal/popup

### ISSUE THREAD

**Issue by priyapower** [a85/POSTMan-Chrome-Extension#11603]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

If you are attempting to a fork a collection and it uses the modal/pop up, if your account is not public, you cannot complete this process because you need a public account for your public workspace. This error-handling is a second popup that hides behind the original modal, which makes it difficult to know what is going wrong.

Gif:
![postman_fork_error_handling](https://user-images.githubusercontent.com/49959312/211091736-39766e64-fcc1-4106-b3c5-0c191d45a980.gif)

Images:
* See fork modal
  * <img width="1184" alt="Screen Shot 2023-01-06 at 1 50 47 PM" src="https://user-images.githubusercontent.com/49959312/211091843-c83acc7e-79aa-4ec2-a2dc-80b5e8fd2a68.png">
* After clicking "Fork Collection", the background tints darker, but the user does not know why nothing is happening
  * <img width="1182" alt="Screen Shot 2023-01-06 at 1 50 58 PM" src="https://user-images.githubusercontent.com/49959312/211091959-7d928ecb-f6fd-4deb-9ee9-6b53a697b016.png">
* If I cancel/click exit, then I can see the additional pop up for making account public
  * <img width="990" alt="Screen Shot 2023-01-06 at 1 51 02 PM" src="https://user-images.githubusercontent.com/49959312/211091981-44132dbb-df70-4454-997d-9ca91359560b.png">

### Steps To Reproduce

1. Have a non-public profile
2. Attempt to fork a collection to a public workspace
3. See no visible error handling or information

### Screenshots or Videos

Gif:
![postman_fork_error_handling](https://user-images.githubusercontent.com/49959312/211091736-39766e64-fcc1-4106-b3c5-0c191d45a980.gif)

Images:
* See fork modal
  * <img width="1184" alt="Screen Shot 2023-01-06 at 1 50 47 PM" src="https://user-images.githubusercontent.com/49959312/211091843-c83acc7e-79aa-4ec2-a2dc-80b5e8fd2a68.png">
* After clicking "Fork Collection", the background tints darker, but the user does not know why nothing is happening
  * <img width="1182" alt="Screen Shot 2023-01-06 at 1 50 58 PM" src="https://user-images.githubusercontent.com/49959312/211091959-7d928ecb-f6fd-4deb-9ee9-6b53a697b016.png">
* If I cancel/click exit, then I can see the additional pop up for making account public
  * <img width="990" alt="Screen Shot 2023-01-06 at 1 51 02 PM" src="https://user-images.githubusercontent.com/49959312/211091981-44132dbb-df70-4454-997d-9ca91359560b.png">

### Operating System

macOS

### Postman Version

9.14.0

### Postman Platform

Postman Web

### User Account Type

Signed In User

**Comment by tapanchudasama** [comment]
Hello @priyapower, this issue has been fixed in the latest release of the Postman app. Feel free to create another issue and let us know if you still face any difficulties.
