### ISSUE TITLE
Billing information are not saved 

### ISSUE THREAD

**Issue by michalina-graczyk** [a85/POSTMan-Chrome-Extension#11602]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Billing information are not saved even if I get confirmation

### Steps To Reproduce

1. Go to billing -> Plan and payments
2. Fill all billing informations 
3. Click 'save' button
Result: I got a popup that details are saved
4. On the plan and payments view I can see that the address is empty
5. Click on 'Go edit information' 
Result: The billing information form is still empty 

### Screenshots or Videos

https://watch.screencastify.com/v/wXgJS5zTsPbESfzfnC3T

### Operating System

macO

### Postman Version

10.6.9-221219-0711

### Postman Platform

Postman Web

### User Account Type

Signed In User

**Comment by kokoseo** [comment]
Thank you for bringing this to our attention. Currently, free teams are not able to save billing information because we are not billing for them. We understand that the UX could be more optimal, and we're working on improving it to set better expectations.
