### ISSUE TITLE
OAuth 2.0 authentication using grant type Authorization Code (With PKCE) fails

### ISSUE THREAD

**Issue by johnbigley** [a85/POSTMan-Chrome-Extension#11606]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

When I upgraded to version 10.7.0 the OAuth 2.0 authentication using grant type Authorization Code (With PKCE) fails began to fail. The problem is that when it calls the authorize/token it no longer passed the client_id.

![Screenshot 2023-01-09 162610](https://user-images.githubusercontent.com/45372753/211435083-7d578569-dd63-42b0-bb34-09b30b9a0afc.png)

### Steps To Reproduce

Configure Authentication
![Screenshot 2023-01-09 162403](https://user-images.githubusercontent.com/45372753/211434952-66e63c84-d533-499f-b202-675c40397f7f.png)

Click on Get new Access Token and enter credentials. Get error:
![Screenshot 2023-01-09 162847](https://user-images.githubusercontent.com/45372753/211435051-983b5385-0392-48c6-baef-7e84bc25fdb5.png)

### Operating System

Windows 

### Postman Version

10.7.0

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by giridharvc7** [comment]
@johnbigley It's passed in the header as you have mentioned `Client Authentication` as `Send as Basic Auth Header`. 

Can you try changing the `Client Authentication` to `Send client credentials in body` ? You'll be able to see the client_id in the request body in the console here 
<img width="453" alt="image" src="https://user-images.githubusercontent.com/1040583/211482960-e1ff67c5-7cae-4287-b8dd-810ad0c11833.png">

**Comment by johnbigley** [comment]
@giridharvc7 Thank you for pointing that out. That fixed it.

**Comment by giridharvc7** [comment]
Glad it worked. Closing the ticket. 

When `Send as Basic Auth Header` is set, the client id is sent in the header as a base64 string. I'm guessing some OAuth providers expect this in plain text in the body.
