### ISSUE TITLE
When redirecting due to a 302. Headers must be flushed.

### ISSUE THREAD

**Issue by subramaniank** [a85/POSTMan-Chrome-Extension#1160]
When redirecting to AWS due to a 302, Authorization header is forwarded from the original request.
This causes AWS to throw an error as such.

```
InvalidArgumentOnly one auth mechanism allowed; only the X-Amz-Algorithm query parameter, Signature query string parameter or the Authorization header should be specifiedAuthorization53bf3440-8630-424a-97dd-5774e6ea1886B30BA550CDA621436mRYb/s3DGjmrvHwK8TS8Ppzi2Z9WhT1VvsnNViKKdwqi0vsKx1UcR43+YDA5sMOjif2CqhlEeQ=
```

For reference, https://github.com/request/request merged a similar PR
https://github.com/request/request/pull/1184

Let me know if I can submit a PR and how to go about it.

**Comment by abhijitkane** [comment]
Redirects are handled by Chrome automatically. If you want to stop automatic redirects, you'll need to enable the interceptor and set the 'Automatically follow redirects' setting to No.

**Comment by subramaniank** [comment]
Haven't tried enabling the interceptor, will try it during the weekend. But the problem is not that the redirect is happening. The problem is that the  redirect carries headers from the original request. Is that expected ?

**Comment by abhijitkane** [comment]
Without the Interceptor, the Postman app doesn't know that the redirect is happening. Chrome handles the redirect and sends the final response to Postman.

**Comment by guymaor86** [comment]
I have the same issue, my request is being redirected to AWS, and I don't want to stop automatic redirects. I just want the redirects not to happen with the original headers I sent to the first call.
Am I doing something wrong?
