### ISSUE TITLE
[With Resolution] Json Request Body Bug when request method is POST: Mock Example Matching with json body

### ISSUE THREAD

**Issue by j1i-ian** [a85/POSTMan-Chrome-Extension#11607]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Hello postman !

I'm so very happy with many functions in your product. 

I created a mock server and try to match request body as json but it didn't work.

then, I changed mime type in example to 'text', save it, re-change to 'json'.

It worked to me. anybody there is like my case ?

### Steps To Reproduce

1. Suppose you have already own mock server that turned on request body matching option, collection, example (E1) with json body (raw - json), request (R1)
2. R1 has json body and method is POST. E1 has too.
3. Test mock example is working : it maybe failed.
4. Change E1 Mime type to text (raw - text)
5. revert that. change mime type to json (raw - json)
6. it works.

### Operating System

macOS 12..1 Montery

### Postman Version

10.7.1

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by Dhembla** [comment]
Hey @j1i-ian,
Sorry to hear that you are facing issues while using mock servers. Can you please check once that when you create examples `content-type` header is being set correctly to `application/json` and then try to use the mock server?
Thanks for your patience!

**Comment by j1i-ian** [comment]
Oh, It is ok, I'm your fan frirend.
I found the problem about header setting too.

Now I can mock server example correctly but there is not enough points.
May I hope to implement auto header setting by body data type on Postman ? I'm always backing you Postman team.

@Dhembla

**Comment by sony-mathew** [comment]
Hey @j1i-ian , I see that you have reopened the issue. I hope this is by mistake since there has been no other activity after that. I believe that our documentation and the new capabilities should help address your concerns and provide a better experience for you. If you have any further questions or concerns, please feel to reopen this issue.
