### ISSUE TITLE
OpenAPI 3.1 definition incorrectly imported as OpenAPI 2.0

### ISSUE THREAD

**Issue by domenikk** [a85/POSTMan-Chrome-Extension#11617]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

According to this blog post: [OAS 3.1 support](https://blog.postman.com/postman-now-supports-openapi-3-1/), Postman should support importing OpenAPI 3.1 definition file (or folder).

But, during import process, the version detected is 2.0. If you proceed with the import, it will show an error regarding the collection not being created.

### Steps To Reproduce

1. Open the **Import** dialog and select an *OpenAPI 3.1* definition file or folder (`yaml` or `json` format)
2. In the next screen, the detected **API Type** is *OpenAPI 2.0*, instead of *3.1*
3. Proceed by clicking the **Import** button
4. The definition is created (although wrong version), but the Postman collection is not

### Sample OpenAPI 3.1 definition (copied from Postman sample):
![1](https://user-images.githubusercontent.com/45637107/212078264-f8035075-360a-4c6c-9c3c-f6dead62465a.png)

### Detected version when importing:
![2](https://user-images.githubusercontent.com/45637107/212078338-759eb27c-6811-49a4-af44-b984bcf7ef8f.png)

### Postman collection error:
![3](https://user-images.githubusercontent.com/45637107/212078410-4bef85a6-31c7-4b7e-ae71-74565545c1c7.png)

### Operating System

Linux

### Postman Version

10.7.1

### Postman Platform

Both

### User Account Type

Signed In User

**Comment by ThibaultSelency** [comment]
Same issue here.
3.1.0 recognized as 2.0
3.0 recognized as 3.0

```
Version 10.8.1
UI Version: 10.8.1-ui-230112-0919
Desktop Platform Version: 10.8.0 (10.8.0)
```

Working on 10.6.7

**Comment by dhwaneetbhatt** [comment]
@domenikk @ThibaultSelency I'm not able to reproduce this on given versions using some sample OAS 3.1 schemas that I tried. Would you please share the schema text content which is being wrongly imported as an OAS 2.0 API?

**Comment by domenikk** [comment]
@dhwaneetbhatt The sample I've included in the screenshots is taken from Postman app (**New API** -> **Author Definition from scratch** -> **Choose v3.1 and check "Use a boilerplate (predefined template)"**).  

I'm pasting it here for your convenience:
```yaml
openapi: '3.1.0'
info:
  version: '1.0.0'
  title: 'Sample API'
  description: Buy or rent spacecrafts

paths:
  /spacecrafts/{spacecraftId}:
    parameters:
      - name: spacecraftId
        description: The unique identifier of the spacecraft
        in: path
        required: true
        schema:
          $ref: '#/components/schemas/SpacecraftId'
    get:
      summary: Read a spacecraft
      responses:
        '200':
          description: The spacecraft corresponding to the provided `spacecraftId`
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Spacecraft'
        404:
          description: No spacecraft found for the provided `spacecraftId`
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    SpacecraftId:
      description: The unique identifier of a spacecraft
      type: string
    Spacecraft:
      type: object
      required:
        - id
        - name
        - type
      properties:
        id:
          $ref: '#/components/schemas/SpacecraftId'
        name:
          type: string
        type:
          type: string
          enum:
            - capsule
            - probe
            - satellite
            - spaceplane
            - station
        description:
          type: string
    Error:
      type: object
      required:
        - message
      properties:
        message:
          description: A human readable error message
          type: string
  securitySchemes:
    ApiKey:
      type: apiKey
      in: header
      name: X-Api-Key
security:
  - ApiKey: []
```

I was able to reproduce it with any OpenAPI definition file (`yaml` and `json`), as long as you have `openapi: 3.1.0` at the top.

**Comment by iancharters** [comment]
We're having the same issue.  We have not changed our spec but someone just approached me and told me they're having this exact issue.  I was able to reproduce.  This exact same spec imported as 3.1.0 fine for weeks when I was building and testing the spec a couple months back.

**Comment by dhwaneetbhatt** [comment]
Thanks @domenikk. We're looking into this.

**Comment by dhwaneetbhatt** [comment]
We've rolled out an update to the web and desktop that fixes this issue. Please update to the latest version (v10.8.6).

**Comment by domenikk** [comment]
@dhwaneetbhatt Just tested and it's working ok now. Thank you and the team for the fix

**Comment by iancharters** [comment]
@dhwaneetbhatt It's fixed for us as well.  Thanks for the fast turnaround.
