### ISSUE TITLE
Values are not populating in request while running automated csv file

### ISSUE THREAD

**Issue by VamsikrishnaK2023** [a85/POSTMan-Chrome-Extension#11611]
### Is there an existing issue for this?

- [ ] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Values are not populating in request while running automate CSV file while updated to latest version and restated the system.

Previous we are able to populate the valid request that we provided in the csv file

### Steps To Reproduce

step1: Opened automated collection and clicked on run button.
step2:uploaded the CSV formated test data file.
Step3: After file loaded clicked on the run automated file button.
Step4: Test file excuted successfully.
Step5: In response tab getting valid response.
Step6:In request tab data is not uploading from csv test data file.

### Screenshots or Videos
![2023-01-11 18 14 26](https://user-images.githubusercontent.com/122437383/211809955-44cb5942-a83b-472d-a364-f8ea35d7a47b.png)

### Operating System

windows

### Postman Version

Postman v10.7.0

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by malvikach** [comment]
@VamsikrishnaK2023 Could you provide a screen recording/screenshot walking us through the issue? I am not able to understand the problem based on the above information.

**Comment by VamsikrishnaK2023** [comment]
@malvikach  requested screen shot is placed here
![2023-01-11 18 14 26](https://user-images.githubusercontent.com/122437383/211809955-44cb5942-a83b-472d-a364-f8ea35d7a47b.png)

Expected is after run the csv file, request should be like this
{
    "vehicleDetails": {
        "vehicle no": "TS01ET1221",
        "vehicle Price": "125000",
        "vehicle model": "2012",


Running the API Collections thru CSV file ( which consist of test data)
We are getting the proper response, but when we looked into the request, data is not populating.
For more information please check the screenshots attached here with.
Please let me know if you need any additional information.

Thanks,

**Comment by xk0der** [comment]
@VamsikrishnaK2023  can you provide some more details, so that we can understand how things are setup at your end?

* What does the CSV file look like?
* How is the request body setup?
* Any Pre-Request/Test scripts in use?

If you can share an example CSV with a Test Collection which can reproduce this issues that would be even better. (Make sure to remove any sensitive data from the CSV and Test Collection before sharing here)

**Comment by VamsikrishnaK2023** [comment]
@xk0der  Amit Singh 

Here are the details provided required by you
1. CSV file screen shot
![2023-01-12 11 49 25](https://user-images.githubusercontent.com/122437383/211993534-23a976d6-e800-4927-a719-09882db83427.png)


2.Request body setup screen shot 
![2023-01-12 11 39 50](https://user-images.githubusercontent.com/122437383/211993148-76a50bbc-576d-4387-875f-eab7a7d0900d.png)

3.We use only Test script 
![2023-01-12 11 59 06](https://user-images.githubusercontent.com/122437383/211994087-ef08f25b-da13-4f81-98b7-aa8286b22aa9.png)

Please let me know if you need any additional information.

Thanks,

**Comment by VamsikrishnaK2023** [comment]
Before updating the postman it was working fine, once we updated values are not populating in request

**Comment by malvikach** [comment]
@VamsikrishnaK2023 Thanks for all the details. We are looking into this bug. 
Please feel free to use the previous app version while we fix this problem.

**Comment by VamsikrishnaK2023** [comment]
can you please provide the previous version link to download

**Comment by malvikach** [comment]
@VamsikrishnaK2023 you can download it from [here](https://dl.pstmn.io/download/version/10.6.0/win64)

**Comment by VamsikrishnaK2023** [comment]
@malvikach yesterday i downloaded the previous version from the link you shared and after my work completed i closed the post man and i opened now it is updating automatically to latest version. can i know why it is happing when my automatically updates option is in disabled. how can i use previous version without updates? 

can i know the status of the collection runner bug?

Thank you.

**Comment by KiraElric007** [comment]
Hey @VamsikrishnaK2023 thanks for your patience. We have fixed the issue in the latest version of the Postman App. 
Regarding automatic updates, the option disables major updates to the Postman platform. Minor updates and bug fixes - Ref: https://community.postman.com/t/disable-postman-from-updating/4239/6
Can you please confirm if the issue still persists on the latest version of the app.

Thank you.

**Comment by VamsikrishnaK2023** [comment]
@KiraElric007 Fix was fixed and it is working fine Now. thanks for resolving this issue with in short response time.
