### ISSUE TITLE
XML in documentation editor removes XML when re-editing.

### ISSUE THREAD

**Issue by barnaclejive** [a85/POSTMan-Chrome-Extension#11614]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

I can add ```xml ``` content to documentation and it will appear OK when saved the first time. But, when re-editing the documentation, all the XML in these code blocks is stripped and only contains the plain text content of the original XML.

### Steps To Reproduce

1. Edit collection documentation
2. Insert a code block in XML format using ```xml...
3. Save documentation
4. Edit documentation 
5. See that the code block now only contains the plain text contents of the original XML tags.

### Screenshots or Videos

https://user-images.githubusercontent.com/5251331/211955844-163d283e-0f40-4445-8a83-fee1bd4dec31.mov

### Operating System

macOS

### Postman Version

10.7.1

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by kamaraj-p** [comment]
Hi @barnaclejive , thanks for reporting this issue. The XML tags are getting removed due to sanitisation, but we are working on fixing this as this is a valid use case.

**Comment by kamaraj-p** [comment]
This issue is fixed in the latest release v10.12.0. Closing this issue, feel free to reopen if required. 🙏
