### ISSUE TITLE
Request body in Runner doesn't match the sent request when using data variables from CSV

### ISSUE THREAD

**Issue by TimKelby** [a85/POSTMan-Chrome-Extension#11610]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

When sending requests using the runner, the logged request body shows placeholders for variables that should be substituted from the CSV file used in the run. These variables have actually been substituted in the real request, but they still show as placeholders (e.g. `{{CUSTOMER_ID}}` instead of the actual value used in the request).

See "Screenshots or videos" for an example

### Steps To Reproduce

1. Create a collection with a request, the body of which contains at least one `{{placeholder}}`
2. Create a suitable environment to enable you to send your requests to some endpoint. The endpoint should enable you to log the requests sent to it.
3. Create a CSV file containing a column with the same name as your placeholder. Populate with data.
4. Use the collection runner to run your collection. Select your CSV file as the data source, and run the collection.
5. Look at the request body for any of the requests that were sent.
6. Compare the logged request bodies in Postman with the request bodies as logged by your endpoint.

### Screenshots or Videos

One request body logged by the runner was displayed like this (all data is procedurally-generated dummy data):
![image](https://user-images.githubusercontent.com/122447078/211790554-df8fe2f3-a1f2-4378-a393-96b40585f675.png)

The real request body sent to the API contained this:
```
        "customerType": "Customer",
        "accountId": "NO9419842626050",
        "customerId": "38829603",
```

These variables are all columns in the CSV file used in the collection run. Values that came from environment variables were correctly displayed in the logged request body, placeholders were only shown for values that came from the CSV.

### Operating System

Windows 10

### Postman Version

10.7.1

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by malvikach** [comment]
@TimKelby Thanks for the details! We are looking into this bug.  

We will keep you updated about the fix.

**Comment by malvikach** [comment]
@TimKelby The issue has been fixed now. Please let us know if you face any other problems with this. I am closing the ticket,  feel free to reopen it if you still see issues.
