### ISSUE TITLE
XML is stripped from quotes in documentation editor

### ISSUE THREAD

**Issue by barnaclejive** [a85/POSTMan-Chrome-Extension#11615]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

When using the documentation editor, insert a quote block and add XML content. Save. The XML is stripped and only th plain text content of the original XML remains.

Note that I am only resorting to quote blocks because Markdown XML code blocks have the same issue. I have submitted a bug report for the markdown issue as well.

### Steps To Reproduce

1. Use the documentation editor.
2. Add a quote block.
3. Put some XML content into the quote.
4. Save
5. View documentation 
6. There is no XML in the quote text.

### Screenshots or Videos

https://user-images.githubusercontent.com/5251331/211957385-06046618-98e1-405a-af20-3d4e0a6eb372.mov

### Operating System

macOS

### Postman Version

10.7.1

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by xk0der** [comment]
@barnaclejive Thank you for reporting these! 

The root-cause of this bug maybe same, but I'm keep these separate for now.
Issue reported for the code block is here #11614

**Comment by kamaraj-p** [comment]
Hi @barnaclejive , thanks for reporting this issue. The XML tags are getting removed due to sanitisation, but we are working on fixing this as this is a valid use case.

**Comment by kamaraj-p** [comment]
This issue is fixed in the latest release v10.12.0. Closing this issue, feel free to reopen if required. 🙏
