### ISSUE TITLE
'Lack of Javascript Support' Modal won't dismiss

### ISSUE THREAD

**Issue by DomDomDomDomDom** [a85/POSTMan-Chrome-Extension#1162]
![image](https://cloud.githubusercontent.com/assets/9380277/8278862/c7f23b3a-18c6-11e5-88a1-4d55dfd0001a.png)

Used Postman before running my Virtual Machine and got this message. Then started my virtual machine, could send the request by pressing Enter but the modal still does not dismiss

**Comment by abhijitkane** [comment]
That's odd. Is Javascript enabled for all sites, or is there an exception for Postman?

Either way, to hide the modal, you can enable DevTools for Postman (http://blog.getpostman.com/index.php/2014/01/27/enabling-chrome-developer-tools-inside-postman/), and type this in the console to get rid of the modal:
`$("#modal-no-javascript").modal('hide');`

**Comment by DomDomDomDomDom** [comment]
JS was enabled, think it might be the lack of the VM running that got it confused. Just thought it worth noting since I couldn't dismiss it after I started up my VM

**Comment by abhijitkane** [comment]
@DomDomDomDomDom Can you confirm this fixed in the latest version - v3.0.4?
