### ISSUE TITLE
The Desktop App freezes on a blank page when there is a binary/audio file in the response body

### ISSUE THREAD

**Issue by tel-epat** [a85/POSTMan-Chrome-Extension#11629]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

When a  user sends an API request that returns a content type audio/mpeg (binary) in the response body, the Desktop App crashes and goes blank. 

This started to occur after the last update:
Postman Version 10.8.1
UI Version: 10.8.1-ui-230112-0919
Desktop Platform Version: 10.8.0 (10.8.0)

### Steps To Reproduce

1. Send a GET or POST request that returns an audio/mpeg in the response body (e.g. downloads an audio file or extracts an audio)
2. The request goes through (200), but when the app finishes loading the response body, the app crashes and goes blank.

### Screenshots or Videos

https://user-images.githubusercontent.com/96523074/212716568-03ee677c-ef26-4e97-9f83-6f9f5ae8da40.mp4

### Operating System

macOS Monterey 12.6.1

### Postman Version

Desktop Platform Version: 10.8.0 (10.8.0)

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by danmartuszewski** [comment]
I'm having the same issue 
-  MacOS Venture 13.1
- Postman 10.8.1

**Comment by lawipac** [comment]
it also happens when content-type in the response header is 'video/mp4.', it became a blank screen

**Comment by 01101sam** [comment]
I got some logs in the Dev Console. Here is the actual problem

> I use <https://storage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4> for testing

#### My OS info
```
Postman for Windows

Version 10.8.4

UI Version 10.8.4-ui-230120-0853

Desktop Platform Version 10.8.0

Architecture x64

OS Platform win32 10.0.19044
```

![image](https://user-images.githubusercontent.com/100821827/213921277-38190e49-57c2-4898-92e3-ccc3e3f67b51.png)
^ Seems like after the video fails to load at iframe, it'll go to `desktop-offline.htm` page

![image](https://user-images.githubusercontent.com/100821827/213921327-7dca9743-fe8e-454a-bd50-cf9a3ebc9e46.png)

So I'm guessing there's some problem when handling the `iframe` preview.

Update:
- By using `history.back()` in the dev console I was able to get back to the main UI.
- This problem happenes on every method request when `Content-Type` of `mime type` is `meida`

**Comment by tel-epat** [comment]
That is a very good catch, Sam. Thanks for adding this information.
Hopefully, they will review this issue asap.

ne 22. 1. 2023 v 15:34 odesílatel Sam ***@***.***> napsal:

**Comment by amarsgithub** [comment]
Also facing the same issue here on my Desktop app and web app, here's my OS info: 

```
Windows 11 21H2
Postman Version 10.8.5
Postman UI Version 10.8.5-ui-230123-1055
Desktop Platform Version 10.8.0
Architecture x64
OS Platform win32 10.0.22000
```

**Comment by edouarde1** [comment]
Having the same issue. Postman screen turns blank when receiving and `video/mp4` response. Looks like things run fine when using the postman web client. 

Running Postman for MacOS v10.8.5

**Comment by rklaas-vt** [comment]
I believe my issue is related to this bug as well. 

https://github.com/postmanlabs/postman-app-support/issues/11682

**Comment by rklaas-vt** [comment]
#11682

**Comment by ashuvyaspm45** [comment]
Hey folks, Sorry for the trouble you have to go through because of this issue. We have released a fix for this change and it's being rolled out and will be available to you in next few days. Please give it a try and give us feedback. Thanks for your patience.

**Comment by 01101sam** [comment]
Tested and it's fixed, thank you.

![image](https://user-images.githubusercontent.com/100821827/220907070-036f0c89-651b-48d3-a7f0-609689cf20e3.png)
