### ISSUE TITLE
Failed installation. Postman-win64-7.33.1

### ISSUE THREAD

**Issue by koseysh** [a85/POSTMan-Chrome-Extension#11626]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Hi all.
Can't install Postman on Windows 11 64-bit operating system. 
The given path's format is not supported error. 
Log attached.
[SquirrelSetup.log](https://github.com/postmanlabs/postman-app-support/files/10417032/SquirrelSetup.log)

### Steps To Reproduce

Just installation doesn't work

### Screenshots or Videos

![2023-01-13_21h21_57](https://user-images.githubusercontent.com/114918371/212465406-05a52aa6-dfc3-4afd-8367-8be091e60125.jpg)

### Operating System

Windows

### Postman Version

7.33.1

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by jviotti** [comment]
Hey @koseysh, are you by any chance running Windows on top of a network file system or something like that? What file system is powering `C:\temp`?

**Comment by koseysh** [comment]
@jviotti thanks for reply,
no, I don't. Just usual boring Windows .
![Uploading 2023-01-16_13h07_15.jpg…]()

**Comment by koseysh** [comment]
Figured it out.  Checked out Environment Variables in advanced settings and deleted variable TMP with value  %:\temp. I don't know why and for what it was there, but it solved the problem.
Hope it will help someone.)

**Comment by Ghostofam** [comment]
This also works for me. I was wondering that something is wrong with my windows, but thank God I came here (thanks to qwen search too, who showed me this issue). I deleted the TMP environmental variable for my user but not from my system variables. And then I am abke to install Postman Desktop in my windows 11.
