### ISSUE TITLE
Flow "Loading Dependencies Failed"

### ISSUE THREAD

**Issue by aryu-ki** [a85/POSTMan-Chrome-Extension#11624]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

I have been creating test with Flows.
After creating several flows and leaving my pc for around 10 minutes, I found out that most of my flows are not loading anymore. I tried restarting postman, and half of the errors gone. But still, some flows are unaccessible.

### Steps To Reproduce

It's hard to provide steps to reproduce, since I don't know where I can view logs or even access created flow at all. The error seems random. I haven't every used any external plugins, but I am working in a Workspace, which might fail to upload my flows automatically and then refetched them incorrectly

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/84020506/212287406-c9759165-c711-4b73-86a4-b17bf757479f.png)

### Operating System

Windows

### Postman Version

10.7.3

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by aryu-ki** [comment]
It seems like postman dropped unsaved files for some reason, because I noticed that some of requests have lost their changes too

**Comment by SterlingChin** [comment]
@aryu-ki, we've addressed many performance issues in the latest version of Postman Flows. Can you update your client or app to the latest version (`v10.12.5`) and see if this resolves the issue?

**Comment by aryu-ki** [comment]
Well, sure I will, but I've never stumbled across the issue ever again, so
I guess it was a really rare case
