### ISSUE TITLE
High CPU intensive usage

### ISSUE THREAD

**Issue by dalisoft** [a85/POSTMan-Chrome-Extension#11636]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

I have high CPU usage and it's always/intensive

### Steps To Reproduce

1. Just open Postman
2. Check your Activity Monitor on macOS

### Screenshots or Videos

<img width="1079" alt="image" src="https://user-images.githubusercontent.com/3511344/213128258-cd506e19-2b60-41ad-b8cf-e4799c77f18c.png">

![image](https://user-images.githubusercontent.com/3511344/213128309-3f871a4d-fc0e-4161-be27-a3fa048fb0a2.png)

### Operating System

macOS

### Postman Version

10.8.1

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by kamalaknn** [comment]
@dalisoft 

Thanks for the screenshots. Could you share the system configuration? By any chance are you using Apple silicon chips with `Rosetta` turned on?

Could you also share if your environment has a lot of variables? Do you see the same behaviour if you have no environment selected?

**Comment by dalisoft** [comment]
@kamalaknn 

Thank you for reply. 
My machine is Macbook Pro M1 2020, yes, Apple Silicon but no Rosetta. Only native apps are running. 

Unfortunately i cannot share environment variables due of security reasons but yes, no matter what i to do, same bug. High CPU usage

**Comment by abinici** [comment]
@kamalaknn 

I am also experiencing the same issue on MacOS. No matter what I do, PostMan keeps using around 110% CPU. I run PostMan as native application.

Here are my system info:

Apple M1 Pro
MacOS Ventura 13.0.1
PostMan 10.8.7

Please fix this issue, because I prefer having PostMan opened all the time.

**Comment by dalisoft** [comment]
40 days since the bug report. I would like to help for solving this bug but unfortunately i don't have any test code to fix it

**Comment by dalisoft** [comment]
After release of `v10.13.3` looks like it's fixed. Just make sure clear cache and delete local files. 
Can anyone confirm please?

**Comment by kamalaknn** [comment]
Hey @dalisoft @abinici  We've rolled out a fix for this in 10.18. Please update your apps and let us know if you are still seeing this.

**Comment by abinici** [comment]
@kamalaknn I haven't had this issue for a while now. So it seems to be fixed. Thanks!

**Comment by dalisoft** [comment]
@kamalaknn For me too, for me it's fixed from v10.13.3. Thank you
