### ISSUE TITLE
"No options found" from imported .proto

### ISSUE THREAD

**Issue by khteh** [a85/POSTMan-Chrome-Extension#11635]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

This simple `.proto`:
```
syntax = "proto3";
option csharp_namespace = "MyApp.Ping";
package Ping;
import "google/protobuf/empty.proto";

service SvcPing {
  rpc Ping (google.protobuf.Empty) returns (Pong);
}

message Pong {
  string message = 1;
}
```
When imported, it keeps showing "No options found".

### Steps To Reproduce

Service Definition, choose "Import a .proto file", select a file, choose "Next"

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/3871483/213066920-daa4e745-b3ac-4b19-a859-60a183cb3cf9.png)

### Operating System

Ubuntu 22.10

### Postman Version

9.31.27

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by codenirvana** [comment]
@khteh You must first enter the API name (or select an existing API) to import "ping.proto" in Postman.

![import](https://user-images.githubusercontent.com/4865836/213079038-2167f9c8-15e7-4f7f-9762-834aee69ad90.gif)

I understand that the UX was confusing, so I recommend upgrading to the latest Postman app version.
Closing this, feel free to reopen it if the issue persists for you.
