### ISSUE TITLE
No Font Icons

### ISSUE THREAD

**Issue by awinwood** [a85/POSTMan-Chrome-Extension#1163]
I am using Version 3.0.0.7 (packaged) on windows with version 43 of chrome and the font icons are not appearing on buttons etc. See attached screenshot
![nofonticons](https://cloud.githubusercontent.com/assets/12557064/8302165/5ab366fe-198c-11e5-812f-c6643d9040ed.PNG)

I have tried reinstalling but the issue remains

**Comment by d-floyd** [comment]
I have the same issue. It makes it very hard to use the application. I know the buttons are there.. but I have to click around randomly until it finally lands.

**Comment by a85** [comment]
Seems to be a problem with SVG rendering for Windows. @d-floyd Can you tell me the version you are on?

**Comment by d-floyd** [comment]
3.0.4 version of postman
Version 43.0.2357.134  of Chrome.

**Comment by nstrak** [comment]
I'm seeing this same issue and it makes the system hard to use.  

Postman Version 3.0.5
Chrome Version 44.0.2403.125 m

**Comment by SDohle** [comment]
I had the same issue. Uninstalling Inkscape resolved the problem.

Best regards 
Steffen

**Comment by abhijitkane** [comment]
@nstrak @d-floyd 
Chrome has a default MIME type for svg files that's being overwritten by your system.
You can open your registry (Win-R + regedit), and navigate to HKEY_CLASSES_ROOT.svg, and edit the Content-Type key to "image/svg+xml". Once this is done, restarting Postman should show the icons.

**Comment by nstrak** [comment]
@abhijitkane 
Thanks!  That fixed it.  All of the icon text and commands are back.

**Comment by awinwood** [comment]
@SDohle @abhijitkane 
Confirmed, uninstalling Inkscape reset the mime type in the registry. Either uninstalling Inkscape or editing the registry entry solves this issue
