### ISSUE TITLE
Look forward to a feature to sync the API updates to Swagger "Definition" easily

### ISSUE THREAD

**Issue by briansu2004** [a85/POSTMan-Chrome-Extension#11631]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

The team gave me a swagger file (for an existing API) and asked me to update it.
So I've imported to my Postman.

![image](https://user-images.githubusercontent.com/6775994/212927373-9b485bab-2ced-43a3-9591-f3eae9291717.png)

It had 2 endpoints (`/test1` and `/test2` ).

So I added a new endpoint `/test3` in "Collection"

![image](https://user-images.githubusercontent.com/6775994/212927548-e5cb8b69-e6c3-4ea9-898e-a8d61e4a1210.png)

But I couldn't find an easy way to "sync" this new endpoint to the swagger file.

Do I have to manually add it to the "Paths" section in the swagger file?

### Describe the solution you'd like

I would like a "Sync" (or similar) button or menu item so that I can sync my collection updates to my swagger file.

It would be even better if it can be bi-directional.

**Comment by shashankawasthi88** [comment]
@briansu2004 thanks for raising this request. From what I understand, you are using the Postman collection as a tool for authoring APIs and you want the updates to reflect in the schema as well. I would like to understand your team's usual workflow when it comes to API authoring/ prototyping. How was the initial Swagger file generated

**Comment by briansu2004** [comment]
I don't know - maybe from Java Spring Boot or a different tool.

**Comment by briansu2004** [comment]
It's fine
