### ISSUE TITLE
nested gRPC service request: "Something Went Wrong" error

### ISSUE THREAD

**Issue by psmng** [a85/POSTMan-Chrome-Extension#11630]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

- Error when new nested rpc service is selected
- Single message rpc service works fine

EX)

service TestService {
    rpc TestMethod(Req) returns(Res); // work
    rpc TestNestMethod(Req.Somthing) returns(Res.Something); // error
}

### Steps To Reproduce

1. Click on the new button
2. Select gRPC request
3. Enter the URL
4. Import the prot file
5. Choose a method

### Screenshots or Videos

![스크린샷 2023-01-17 오전 11 15 38](https://user-images.githubusercontent.com/39693451/212808580-289f6f22-2315-4bab-ad58-bcaa1867de83.png)

### Operating System

maxOS

### Postman Version

10.8.1

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by psmng** [comment]
[postman_log.zip](https://github.com/postmanlabs/postman-app-support/files/10431148/postman_log.zip)
- Attach log file

**Comment by codenirvana** [comment]
@JoHyukJun Thanks for reporting this.

Can you share a scaled-down Protobuf file that we can use to reproduce this issue?

**Comment by psmng** [comment]
The cause of the error was found. It seems that an error page occurs when cross-reference occurs between nested objects.

**Comment by JoshuaWisePostmanaut** [comment]
@JoHyukJun This will be fixed in our next release

**Comment by psmng** [comment]
> @JoHyukJun This will be fixed in our next release

Thank you!
