### ISSUE TITLE
After-request Script Tab Feature - Manage Environment Collections (Insert and edit)

### ISSUE THREAD

**Issue by mehmet-erdogdu** [a85/POSTMan-Chrome-Extension#11637]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

No

### Describe the solution you'd like

I want to set the envs using the response values after the request.

For example, after the login request, it will take the login token and set it to env automatically, and the header fields in my other requests will be filled automatically.

I believe we can do this in a tab like after script for each request.

Sample code is below.

![image](https://user-images.githubusercontent.com/44897996/213141743-43e89dc3-69b1-4860-99f6-999ea7494e35.png)

```javascript
//set env feature from response body or cookie
var value = res.data.key
if(value != null && res.status == '200')
{
    set 'envcollectionname'.'Token' = value;
}
```

**Comment by volkanakkoyun** [comment]
This feature can be useful.

**Comment by giridharvc7** [comment]
You can perform this using `pm.environment.get` and `pm.environment.set` more details in this [learning center document](https://learning.postman.com/docs/sending-requests/variables/#defining-variables-in-scripts)

**Comment by mehmet-erdogdu** [comment]
thanks I developed a solution
![image](https://user-images.githubusercontent.com/44897996/213366715-4fe2ae71-0995-4281-ac5d-cbe5bf71b25d.png)
