### ISSUE TITLE
Trying to click a link that should open a browser

### ISSUE THREAD

**Issue by alexandre433** [a85/POSTMan-Chrome-Extension#11638]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

I've recently found out that there's a configuration on Laravel that allows you to do a "dd" (dump & die) that has the path of the dd, and it can be clickable. The issue is that when I click on it in Postman's "preview", I believe it tries to open it and the whole window goes white. If I press Ctrl + Click on the link, it opens a pop up window, that's just white, with menu options.

This issue also happens when I go into Settings > About and click any link that is presented in that window.

### Steps To Reproduce

1. Open a default/fresh laravel project
2. Composer install
3. Go to config/app.php and add the following inside the array (the []) 'editor' => 'vscode' (I've only tested with vscode)
4. A route to test it e.g. `Route::post('test', function () { dd('testing'); return response()->json(); }`
5. Run php artisan serve
6. Go to http://localhost8000/test on postman, and click on path that shows after the dd'd message
![image](https://user-images.githubusercontent.com/10622522/213229186-b2390ded-ccff-414f-a990-f0ff1cbda761.png)
7. Whitness the whitening of your screen

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/10622522/213229591-77f145a6-37e5-4a02-b21d-91d95c619208.png)
![image](https://user-images.githubusercontent.com/10622522/213229660-9534fd4f-6812-4003-a733-dc945d8ef835.png)
![image](https://user-images.githubusercontent.com/10622522/213229834-b303fbbe-e3b1-44e6-ba74-21596c13dc15.png)

### Operating System

Windows 10 Pro N Version 22H2

### Postman Version

10.8.1

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by VaishnaviChallaPostman** [comment]
Hey @alexandre433 👋 
Our team has fixed this issue in version `10.10.8`.
Please feel free to reopen if you are still seeing any issues 🙌
