### ISSUE TITLE
Unable to specify deadline for unary gRPC requests

### ISSUE THREAD

**Issue by cbolik** [a85/POSTMan-Chrome-Extension#11650]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

I'm trying to invoke one of the unary methods of my gRPC service, but the request is immediately aborted with the error "No deadline specified" in Postman's response window. I could not find any way to specify this timeout or deadline in the gRPC request's settings, so tried to specify it as metadata with a key of "deadline" and a value of 600, but still get the same error.

### Steps To Reproduce

1. Create a new gRPC request
2. Using server reflection, select a unary method which requires a [deadline](https://grpc.io/docs/what-is-grpc/core-concepts/#deadlines) to be set
3. Submit the request, see the error message "No deadline specified" show up
4. 

### Operating System

macOS

### Postman Version

13.1

### Postman Platform

Postman App

### User Account Type

Signed In User

### Additional Context?

Using Postman Version 10.8.5

**Comment by codenirvana** [comment]
@cbolik as a workaround, can you try setting `grpc-timeout` metadata with `1000m` (1000 ms) and check if that fixes this issue?

Also, can you share a scaled-down server that I can use to reproduce this issue?
The default deadline is `Infinity`, so I cannot reproduce this locally.

**Comment by EddieLukeAtmey** [comment]
Hi @codenirvana, I also want to ask for a way to set gRPC timeout for postman client (Version 10.10.6). For example, invalid url or server issue (shutdown or something). I tried set timeout in preference but it didn't apply.

**Comment by appurva21** [comment]
Hey @cbolik @EddieLukeAtmey! 

You can now configure the connection deadline under the "Settings" tab in your gRPC request.

![Screenshot 2024-08-14 at 1 47 18 PM](https://github.com/user-attachments/assets/5d4760dd-57bd-4af2-833e-8b69f38590ab)
