### ISSUE TITLE
Import API: allOf and properties are not supported in the schema definition

### ISSUE THREAD

**Issue by MathieuLhomme** [a85/POSTMan-Chrome-Extension#11656]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Hi,
allOf and properties are not supported in the schema definition.
The workaround is to put the properties field in the allOf table. It works but it's not fully compliant with the openAPI specification

### Steps To Reproduce

"schema": {
                                "allOf": [
                                    {
                                        "$ref": "#/components/schemas/Request"
                                    },
                                    {
                                        "properties": {
                                            "announcement": {
                                                "$ref": "#/components/schemas/Announcement"
                                            },
                                            "skipCondition": {
                                                "$ref": "#/components/schemas/SkipCondition"
                                            },
                                            "responseProfile": {
                                                "$ref": "#/components/schemas/BaseResponseProfile"
                                            }
                                        }
                                    }
                                ],
                                
                                "type": "object"
                            }
works whereas
"schema": {
                                "allOf": [
                                    {
                                        "$ref": "#/components/schemas/Request"
                                    }
                                    ],
                                    "properties": {
                                         "announcement": {
                                             "$ref": "#/components/schemas/Announcement"
                                        },
                                        "skipCondition": {
                                                "$ref": "#/components/schemas/SkipCondition"
                                        },
                                        "responseProfile": {
                                            "$ref": "#/components/schemas/BaseResponseProfile"
                                        }
                                    }                               
                                "type": "object"
                            }
doesn't work

### Operating System

Windows

### Postman Version

10.8.6

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by tuftii** [comment]
I've seen similar behaviour with oneOf when describing schemas in responses... both
eg.
     ` responses:
        '403':
          description: Missing or invalid api key or token.
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/responses/InvalidAuthError'
                  - $ref: '#/components/responses/MissingKeyError'
       schemas:
        Errors:
      required:
        - errors
      properties:
        errors:
          description: Basic error template
          type: array
          minItems: 1
          items:
            required:
              - message
            properties:
              message:
                type: string
  responses:
    InvalidAuthError:
      description: Some authentication must be supplied.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Errors'
    MissingKeyError:
      description: Access Denied - Required header 'X-API-Key' is missing.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Errors'`
                  
Does not render the documentation in the definition viewer.

I don't know if I'm missing something, but pretty sure this is the same bug.

(Urgh, sorry for the formatting)

**Comment by akshaydeo** [comment]
Related https://github.com/postmanlabs/openapi-to-postman/issues/417

**Comment by akshaydeo** [comment]
Resolved as part of https://github.com/postmanlabs/openapi-to-postman/issues/417. The fix will be available in the upcoming release in Feb 2023.
