### ISSUE TITLE
Update or release v10 API “versions” using Postman API

### ISSUE THREAD

**Issue by Lincimary** [a85/POSTMan-Chrome-Extension#11651]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

To update or create a release v10 API “versions” using Postman APIs, and without Git integration seems to be a manual process. It would be nice to manage our APIs using Postman APIs since now they are quite a regression in functionality.

### Describe the solution you'd like

Created a v10 API (using the browser), found its schema definition through its relations, updated the schema with a new open API specification, and the last step was to create a release, But it seems that it is not possible
We are able to create a release via UI but failed using Postman API:
![image](https://user-images.githubusercontent.com/76947097/214239023-0b748703-490e-4048-8858-c6da33cc279d.png)

### Describe alternatives you've considered

Postman is already tracking the issue internally, we are creating a new FR for publically tracking. 
Sorry that we don't have an ETA but we have been planning to enable it in an upcoming release.

**Comment by AlexKotsc** [comment]
This is blocking our org from upgrading to v10

**Comment by Lincimary** [comment]
Hey @AlexKotsc, 
This is now fixed and we have also updated the learning centre article on the same.
https://learning.postman.com/docs/developer/postman-api/intro-api/#about-v9-and-v10-apis
