### ISSUE TITLE
xml pretty print issue since 3.0

### ISSUE THREAD

**Issue by holandaleo** [a85/POSTMan-Chrome-Extension#1166]
Since 3.0 update, pretty print for XML responses is adding wrong extra indentation for elements below an element with inline `xmlns:` prefix in attribute.

Use this block as response body:

``` xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<body>
    <test>
        <test1 xsi:nil="true" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" />
        <test2 xsi:nil="true" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" />
    </test>
</body>
```

For this one, postman will mistakenly indent `<test2/>` as a child of `<test1/>`

Environment:
Version 3.0.0.7 (packaged)
OS: win
Architecture: x86-32
Native client architecture: x86-64

**Comment by abhijitkane** [comment]
Thanks for reporting this. We'll fix this in the next release.

**Comment by holandaleo** [comment]
I got 3.0.2 now and looks like the issue has been fixed. Thx.
