### ISSUE TITLE
Postman Desktop Only - Not able to view requests or examples that are nested in folders

### ISSUE THREAD

**Issue by shafer949** [a85/POSTMan-Chrome-Extension#11664]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Not able to click a request within the **Desktop App**, which is nested within a folder structure, and the request opens in a tab. I have to right-click the request and then select Open in Tab. None of the saved examples can be opened anymore. Examples do not have the option to Open in Tab, and double-clicking them doesn't do anything either. Clicking on the example does nothing either.

**Note**: This same structure setup is working as expected in the Postman Web where the requests and examples are viewed in a tab once clicked on. This structure worked fine in the Postman Desktop App until a recent update.

### Steps To Reproduce

1. Log into the Postman Desktop App
2. Create a Collection with the structure pictured below
3. Click on the POST request and notice the request doesn't open in a new tab
4. Click on the example and notice the example doesn't open in a new tab
5. Right click the POST request and select Open in Tab - notice it is now viewable in a tab
6. Right click the example - notice there is not option to view this example in a tab

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/26129170/215112681-ba8cdc0b-8345-4851-ab97-4d8ae96677b3.png)

### Operating System

Windows

### Postman Version

10.8.7

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by giridharvc7** [comment]
@shafer949 can you force close all tabs and try again? 
<img width="271" alt="image" src="https://user-images.githubusercontent.com/1040583/215241153-d338f03c-6e8e-4633-bd95-6d08e3f6da08.png">

**Comment by shafer949** [comment]
@giridharvc7, no tabs are open when this happens. I have tried it with at least one tab open and it still doesn't work. When I did have various tabs open, I did use this option and still experienced the problem.

**Comment by jon-robinson** [comment]
@shafer949 I had this exact issue. Signing out and back in resolved it for me though. Still not sure why or how it happened in the first place though.

**Comment by shafer949** [comment]
@jon-robinson, thank you for the suggestion of signing out and then back into the Desktop App, for whatever reason, today, this fixed my issue. Last week, doing the same thing, however, did not. 🤷‍♂️ 

Closing this issue as it seems to be resolved.
