### ISSUE TITLE
OAuth 2.0 new Auto-refresh token feature always set to basic auth.

### ISSUE THREAD

**Issue by jcbriones** [a85/POSTMan-Chrome-Extension#11668]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

I have an application that uses OAuth to authorize users. While using postman to test the oauth client, I notice that the new feature "Auto-refresh token" when authorization is set to oauth 2.0 does not use what the current configuration is set to. I set the client authentication to `Send credentials in body`. But however when the auto refresh gets triggered, it uses the basic auth in header as the option instead of what I have set in the config.

### Steps To Reproduce

1. Create a new request
2. Select Authorization tab
3. Select type as OAuth 2.0
4. Fill up the information with a valid oauth identity.
5. Set the `Client Authentication` field to `Send client credentials in body`
6. Send `Get Access Token`
7. Authenticate with a valid user for the client.
8. Receives the token and use it.
9. Turn on the `Auto-refresh token`
10. Or you can manually click the `Refresh` link under the token to refresh the token.
11. You either get a response that the client auth was not supported by the server or server may accept both input. But the issue here is that the client authentication config should be used when the auto-refresh or manually clicking refresh is triggered.

### Screenshots or Videos

<img width="1840" alt="SCR-20230128-u4c" src="https://user-images.githubusercontent.com/16768255/215301583-8a1119df-cb05-49c2-b166-7b0b0a7d9772.png">

### Operating System

macOS

### Postman Version

10.8.4

### Postman Platform

Postman App

### User Account Type

Signed In User

### Additional Context?

I can attach a demo client if you want to test this.

**Comment by TheSned** [comment]
I had hoped I could work around this issue with the new features added for #11559, but I could not. I am able to add the needed parameter (client_id) to the request body now, but my identity provider (Okta) responds: `invalid_request, Description: Cannot supply multiple client credentials. Use one of the following: credentials in the Authorization header, credentials in the post body, or a client_assertion in the post body.`

**Comment by abhijeetborole** [comment]
@TheSned @jcbriones Thanks for reporting this issue. We're tracking an issue where Basic Auth is always sent with the refresh token request. I'll update once we have a fix in place.

**Comment by jcbriones** [comment]
Thank you!

**Comment by bradenbiz** [comment]
I am encountering this same issue, but I need to be able to refresh my `accessToken` without sending any `Authorization` header. This is because the auth provider (Amazon Cognito) requires that no `Authorization` headers are sent when the client is public (and therefore, has no client secret). 

Postman automatically adds the basic Authorization header to the refresh request with a value of `Basic {Base64Encode({clientId}:{clientSecret})}`. As you can see, this causes an issue because I have nothing to enter for the `clientSecret`, and so, the auth server returns ("invalid client").

**Comment by leon** [comment]
Same here, trying to build a hubspot app, and they require client_id and client_secret to be present in the request body for both the token creation and token refresh.

As a workaround for the above, I also tried entering the client_id and client_secret in the "Refresh Request" params, but they don't get added to the refresh token request. It felt like the right place to add them...

**Comment by abhijeetborole** [comment]
Hello everyone! We’ve fixed this issue with v10.14. With this change, if you add `client_id` or `client_secret` to token request params/refresh request params, we will not attach the Basic Auth header with the token/refresh request. 

@leon the refresh request params are taken into account when you generate a new token with these params present. For your changes to reflect in the refresh request, make sure to generate a new token.

Do let us know if you face any issues.

P.S. - Postman V10.14 is being rolled out and will be available for everyone in a couple of days.
