### ISSUE TITLE
OPTIONs Request Body

### ISSUE THREAD

**Issue by sarah-micallef** [a85/POSTMan-Chrome-Extension#1168]
Postman does not support request bodies for OPTIONs request. Indeed the Body tab is disabled when the OPTIONS HTTP method is selected (refer to image below).

I haven't yet came across a spec that prohibits an OPTIONs request to have a request body.

![options request](https://cloud.githubusercontent.com/assets/13031039/8326856/5ca8f3e2-1a64-11e5-9a1c-c3486636711e.PNG)

**Comment by a85** [comment]
@abhijitkane Can we enable this and close the issue?

**Comment by abhijitkane** [comment]
@sarah-cassar This has been fixed in v3.0.18.

**Comment by sarah-micallef** [comment]
Great thanks 😁
