### ISSUE TITLE
Ability to update a Collection with an API change is missing in v10 APIs 

### ISSUE THREAD

**Issue by ffffionn** [a85/POSTMan-Chrome-Extension#11688]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Previously, if a new endpoint was added to an API, we simply re-validated a collection and then used Review Issues to add the new endpoint to the collection. This feature seems to be missing from the new v10 UI. 

This is a crucial feature of Postman, as generating a new Collection each time means that any parameters or tests are reset and must be copied over. 

(specifically talking about OpenAPI here)

### Steps To Reproduce

Create an API
Generate a Collection based on that API spec
Add a new endpoint to the API definition
No way to update collection

### Operating System

Linux

### Postman Version

v10

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by shashankawasthi88** [comment]
@ffffionn thanks for raising this. We are actively working on this feature and it is in our short term roadmap. Ill update this thread as soon as we have updates.

**Comment by shashankawasthi88** [comment]
@ffffionn this feature is now available in the latest Postman release that is being rolled out to all users. Refer the [blog](https://blog.postman.com/build-better-apis-using-the-new-and-improved-api-builder/) and the [document](https://learning.postman.com/docs/designing-and-developing-your-api/developing-an-api/adding-api-elements/#keeping-a-collection-in-sync-with-an-api) to learn more. Feel free to reopen and post the ticket if you have any feedback on the feature.
