### ISSUE TITLE
Content-type of multipart/form-data properties not imported

### ISSUE THREAD

**Issue by ikercrg** [a85/POSTMan-Chrome-Extension#11680]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Content-type of multipart/form-data properties not imported

### Steps To Reproduce

1 Import this:

```
openapi: 3.0.0
info:
  version: 1.0.0
  title: Api
paths:
  /v1/products:
    post:
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                image:
                  type: string
                  format: binary
                productCreateRequest:
                   articleNumber:
                  type: string
            encoding:
              image:
                contentType: 'multipart/form-data'
              productCreateRequest:
                contentType: 'application/json'
```

2. In the body, Content-type column, all fields are empty, instead of what it is set in the 'encoding' part.

### Operating System

Windows

### Postman Version

10.9.1

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by VShingala** [comment]
@ikercrg Thanks for reporting the issue! We will be working on fixing this issue with upcoming releases and let you know here once fix is available.

**Comment by webholik** [comment]
@ikercrg The fix for this available in the latest version of Postman App! I am closing this ticket for now, please feel free to reopen if the issue still persists for you.
