### ISSUE TITLE
GraphQL Auto-fetch malfunction

### ISSUE THREAD

**Issue by JimmyRice** [a85/POSTMan-Chrome-Extension#11686]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Postman's GraphQL auto-fetch feature is malfunctioning, which means that when Postman sends an auto-fetch request to the GraphQL endpoint, no Query object appears in the Request Body, resulting in the GraphQL server not being able to correctly process Postman's request for GraphQL documentation.

### Steps To Reproduce

1. Open request tab
2. Switch method to POST
3. Endpoint URL using `https://graphql.anilist.co`
4. Choose Body and using `GraphQL` with `Auto-fetch`

### Operating System

Windows

### Postman Version

10.9.1

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by codenirvana** [comment]
@JimmyRice Thanks for reporting this issue. We've identified the problem, and it will be fixed in the next release.

**Comment by fatihaksoy59** [comment]
I opened this post yesterday btw :)
https://stackoverflow.com/questions/75319932/postman-graphql-schema-refresh-not-working

**Comment by orhan-cmd** [comment]
Please check for updates.

![image](https://user-images.githubusercontent.com/98099231/216569646-5e679743-7618-4146-b5ba-5c2465c988fd.png)

**Comment by giridharvc7** [comment]
@JimmyRice @fatihaksoy59 
We've pushed a hotfix. You should be seeing this fixed with version 10.9.2. Check for updates and/or Just close and open your app

**Comment by JimmyRice** [comment]
Hooray! It's back to normal. Thanks aaaaaaaaaaaaa lot, you guys are awesome!

**Comment by fatihaksoy59** [comment]
Thanks :)
