### ISSUE TITLE
Postman crashing on audio/wav byte response

### ISSUE THREAD

**Issue by rklaas-vt** [a85/POSTMan-Chrome-Extension#11682]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

I have a Postman request that calls my REST API. This endpoint is designed to return bytes of data with a response header from the server of `audio/wav`. With the latest version release `10.8.8`, the audio player in Postman is crashing when the response is received. When I run the same request via the web app, the request is successful and I can playback the audio using the playhead. I've recorded a voice over video of the behavior and attached it to this request. 

Video Example: https://drive.google.com/file/d/1feEfD3ruk41fIOcsVfwC0BhiUjDke6kr/view?usp=drivesdk

### Steps To Reproduce

1. Open a request
2. Call an API endpoint that returns bytes of audio data
3. Application crashes instead of showing the audio playhead

### Screenshots or Videos

Video Example: https://drive.google.com/file/d/1feEfD3ruk41fIOcsVfwC0BhiUjDke6kr/view?usp=drivesdk

### Operating System

MacOS

### Postman Version

Version 10.8.8

### Postman Platform

Postman App

### User Account Type

Signed In User

### Additional Context?

Feel free to contact me at via GitHub if you need any further information. I could also potential provide a temporary API key if you need to call our API. But, I'm hoping you guys are logging this error crash. We are using Postman team workspaces. Here is my user profile.

User Profile: https://www.postman.com/payload-engineer-19114384

**Comment by 01101sam** [comment]
Duplicated #11629

**Comment by PaddyOl** [comment]
Any update on this ( blocking for me) issue ?

**Comment by AleixFerre** [comment]
It crashes on windows aswell.

**Comment by isaacwein** [comment]
i have tha same issue on windows the postman screen gets white I need to kill it from taskmanager

**Comment by giridharvc7** [comment]
Thank you for reporting this. We'll keep this place posted for updates

**Comment by ashuvyaspm45** [comment]
Hey folks, Sorry for the trouble you have to go through because of this issue. We have released a fix for this change and it's being rolled out and will be available to you in next few days. Please give it a try and give us feedback. Thanks for your patience.
