### ISSUE TITLE
"APIs" ribbon UI not updating upon changes introduced via public API

### ISSUE THREAD

**Issue by mxcd** [a85/POSTMan-Chrome-Extension#11685]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

When interacting with the workspace via Postman public API, the "APIs" ribbon does not reflect some of the changes done via public API. In one case, only switching to a different workspace and switching back loads the changes and updates the UI, in another one, only restarting the Postman application triggers a reload of those changes

## Case 1: Changes on OpenAPI Spec
1. Open the "APIs" ribbon in a Postman Workspace
2. Create a new API via Postman public API (`POST /apis`)
3. Create a new schema via Postman public API (`POST /apis/{{apiId}}/versions/{{versionId}}/schemas`)
4. Make changes to the schema in Postman UI
5. Update the schema via Postman public API (`POST /apis/{{apiId}}/versions/{{versionId}}/schemas/{{schemaId}}`)
6. Changes of PUT request are not reflected in Postman UI 
### Workaround
Only switching to a different workspace and switching back updates the definition

## Case 2: Linking a collection to an API
1. Open the "APIs" ribbon in a Postman Workspace
2. Create a new API via Postman public API (`POST /apis`)
3. Create a relation between the API and an existing collection from the "Collections" tab
    `POST /apis/{{apiId}}/versions/{{versionId}}/relations`
    ```
    # JSON body
    {
        "test": [
            "<my collection uuid>"
        ]
    }
    ````
4. Collection is not displayed in "APIs" ribbon under specified API
5. Relation can be queried
    `GET /apis/{{apiId}}/versions/{{versionId}}/test`
    ```
    {
        "test": [
            {
                "id": "<my relation uuid>",
                "name": "<my collection name from Collections ribbon>",
                "updatedAt": "2023-01-31T13:29:41.000Z",
                "collectionId": "<my collection uuid>"
            }
        ]
    }
    ```
6. When trying to use Postman UI to copy the collection manually ("Copy from existing collection"), the collection is not displayed any more (assuming that it is already linked on data level and therefore not displayed as an option for copying)
### Workaround
Only completely restarting the Postman Application shows the Collection in the "APIs" ribbon linked to the respective API

### Trying to add a collection to the API via UI
![image](https://user-images.githubusercontent.com/7310764/216315692-a60f2b5b-4cd4-4a5a-a421-7259a68593a2.png)
### No collection found
![image](https://user-images.githubusercontent.com/7310764/216315888-48b513f8-af65-40a2-88ee-11375f2db868.png)

### Operating System

macOS

### Postman Version

v10.9.1

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by davidespihernandez** [comment]
Hi, @mxcd! 
The APIs in this ticket are deprecated. Please use the new [APIs endpoints](https://www.postman.com/postman/workspace/postman-public-workspace/folder/12959542-1ef9fee3-610f-4cae-8f66-af128b33341b) instead, as those should work properly.
I'm closing this ticket, if you have any problem with the new APIs endpoints, please let me know.
