### ISSUE TITLE
Postman App -> "Search Postman" -> "All of Postman" control and close control does not work

### ISSUE THREAD

**Issue by jeffdafoe** [a85/POSTMan-Chrome-Extension#11698]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

In the "Search Postman" dialogue at the top center of the Postman app, the "All of Postman" control, as well as the close control, no longer work. When hovering over them, the icon does not change to the hand, and when clicking on them, nothing happens. I believe this was introduced in a recent update, as I've used this feature in the past.

### Steps To Reproduce

- Launch postman app
- Click on "Search Postman"
- Click on "All of Postman", nothing happens
- Click on X to close window, nothing happens

The web UI works properly in these 2 cases, the app does not. I've confirmed this issue with someone else at our org, as well.

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/16922080/217019039-c199caec-b423-48f4-b163-41293e341a7a.png)

### Operating System

Windows 10 H2

### Postman Version

10.8.8

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by sony-mathew** [comment]
Thanks for reporting this @jeffdafoe . We are looking into this issue.

**Comment by jeffdafoe** [comment]
This issue is no longer present in the current version, the controls work as expected.
