### ISSUE TITLE
Enable Slack Updates for Status Page

### ISSUE THREAD

**Issue by nrmartell** [a85/POSTMan-Chrome-Extension#11692]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

When there are system issues or outages in Postman it would be nice to have the option to receive updates via Slack.

### Describe the solution you'd like

Enable [Slack Subscriptions ](https://support.atlassian.com/statuspage/docs/enable-slack-subscriptions/) for Status Page updates

### Describe alternatives you've considered

Users can receive emails, but it would be great to receive updates directly in Slack, where users also spend a lot time. of

### Additional context

Filed on behalf of a Postman Team.

**Comment by numaanashraf** [comment]
@nrmartell Slack subscriptions are enabled now.

**Comment by AniX** [comment]
That was quick. Thank you!
