### ISSUE TITLE
Collections do not have any way of being updated after schema changes

### ISSUE THREAD

**Issue by jrobalino** [a85/POSTMan-Chrome-Extension#11705]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Our Postman API objects are linked to GitHub repositories. Any time the OpenAPI spec changes in the repository, we can pull changes into Postman to update our API objects. However, we can no longer validate the collections associated with the API objects. Therefore, we have no way of pushing changes to these collections, which have been forked by hundreds of our users who depend on having the latest Postman collection. This was a breaking change and I understand there is talk about fixing this, but not sure on ETA.

### Steps To Reproduce

See above.

### Operating System

All

### Postman Version

10

### Postman Platform

Both

### User Account Type

Signed In User

**Comment by shashankawasthi88** [comment]
@jrobalino thanks for raising this. This is in our short-term roadmap and the team is already actively working on it. Ill post on the thread as soon as we have an update. Thanks.

**Comment by vmarimuthu** [comment]
Any update on this feature?

**Comment by shashankawasthi88** [comment]
@vmarimuthu @jrobalino this feature is now available in the latest Postman release that is being rolled out to all users. Refer the [blog](https://blog.postman.com/build-better-apis-using-the-new-and-improved-api-builder/) and the [document](https://learning.postman.com/docs/designing-and-developing-your-api/developing-an-api/adding-api-elements/#keeping-a-collection-in-sync-with-an-api) to learn more. Feel free to reopen and post the ticket if you have any feedback on the feature.
