### ISSUE TITLE
New layout is way too padded / spacious

### ISSUE THREAD

**Issue by Redsandro** [a85/POSTMan-Chrome-Extension#1170]
I just got the update for POSTman with the new layout. On my non-uhd laptop, this is way too spacious.

The tabs are bigger. Then there is a huge area that shows just the name of the opened request. Next is the request url with enough padding to fit 3 lines of text. Below that, the tabs (headers, body, e.g.) with a lot of top/bottom padding.

We're not even at the actual body (most used tab) yet, and we''ve already almost used half the screen estate. The response body is barely visible. I scroll a lot more between the two than with the previous version.

I think there should be an option to use a 'compact' type layout in order to make this useful on non-full-hd/uhd screens.

**Comment by sobtiankit** [comment]
Hi,

Can you confirm the version of this app? (Settings > About > Version)
It'll also help us if you'd attach a screenshot of your setup? 

If you're on 3.0.0.6+, we have introduced a compact mode, you can find it in Settings > UI Size and change the dropdown to "Smaller".

**Comment by Redsandro** [comment]
I force updated and now I'm uptodate.

```
Version 3.0.0.7 (packaged)
OS: linux
Architecture: x86-64
Native client architecture: x86-64
```

I enabled the setting and restarted, but I hardly notice a difference.

**Comment by sobtiankit** [comment]
Can you give me a screenshot? We'll add a more compact setting in an update very soon.

**Comment by Redsandro** [comment]
I randomly blurred some things because I'm too lazy to check if there are any company secrets in there. :yum: forgive me.

This is 1600x900, and it already starts to become a bit annoying for big req/res.

![image](https://cloud.githubusercontent.com/assets/1702193/8334859/727f76d8-1a9a-11e5-91e2-f0758ca95e2f.png)

My laptop screen is 1366x768 and it's really annoying.

**Comment by Redsandro** [comment]
In theory you could have a "compact" UI settings with CSS that removes all the excess padding like so:

**Comment by Redsandro** [comment]
In theory you could have a "compact" UI settings with CSS that removes all the excess padding like so:

(This is a mockup, I just cut away some of the padding.)
![image](https://cloud.githubusercontent.com/assets/1702193/8335163/3eb98ff8-1a9c-11e5-868d-39e8c2e73775.png)

I feel like the "smaller" setting only makes the body text a bit smaller and is not very effective.

**Comment by Redsandro** [comment]
This comparison works really nicely on an 'older' (non-hd) laptop.

![image](https://cloud.githubusercontent.com/assets/1702193/8351226/06f41abc-1b2c-11e5-842a-598bb6b26c57.png)

**Comment by midik** [comment]
Here is how it looks at 1920*1080 with "Smaller" UI setting. That's still so spacious...
![postman_242](https://cloud.githubusercontent.com/assets/6795530/8374988/47af5dc4-1c02-11e5-9752-e46943e9fe93.png)

**Comment by Redsandro** [comment]
Is this a joke?

![image](https://cloud.githubusercontent.com/assets/1702193/8436603/bb21367e-1f59-11e5-9a1b-9adb29b28dca.png)

**Comment by sobtiankit** [comment]
Hi @Redsandro 

Can you update to the latest version (3.0.1)? You can force an update by going to chrome://extensions, enabling 'Developer Mode', and clicking 'Update extensions now'. That should fix this.

**Comment by Redsandro** [comment]
Ah that worked :smile: thanks @sobtiankit :+1:

**Comment by sobtiankit** [comment]
Happy to help!

**Comment by midik** [comment]
I've updated to version 3.0.1.... Here is what it looks 3 weeks ago:

![1_202](https://cloud.githubusercontent.com/assets/6795530/8437259/9faf224a-1f66-11e5-8945-77e24d50a3f1.png)

Here is what it looks for now (with "**Smaller**" setting):

![1_251](https://cloud.githubusercontent.com/assets/6795530/8437337/0257ac28-1f67-11e5-9529-3daf733792f1.png)

Could we get "small" and "smaller" looks really smaller?
@sobtiankit, thank you in advance!

**Comment by sobtiankit** [comment]
Noted. We are working on a compact mode as well and will update you soon!

**Comment by Redsandro** [comment]
Compact would be awesome. Like truely oldskool functional compact.

**Comment by mvincenzes** [comment]
another vote for compact

**Comment by ppc52776** [comment]
I also need compact mode. Voted.

**Comment by senao-mis** [comment]
Voted compact mode.
And UI size in wrong result issue remains.

**Comment by Redsandro** [comment]
In my opinion, it's taking too long to roll back the bad choice of user interface. My colleagues tell me to switch to [DHC - REST/HTTP API Client](https://chrome.google.com/webstore/detail/dhc-resthttp-api-client/aejoelaoggembcahagimdiliamlcdmfm). I prefer POSTman though because I'm used to it. But I wish this would be addressed with more of a priority, because as far as I'm concerned, you broke something that used to work.

The **UI Size** setting is completely illusory. I think all that changes are _some_ fonts, by a pixel or so, although the font size is the least important factor (and you can change this anyway).

`Smaller` should reduce the interface widget size and reduce the padding.
`Smallest` should further shrink the interface and nearly diminish the padding.

---

`smallest` expectation vs. reality:
![Expectation vs. Reality](https://cloud.githubusercontent.com/assets/1702193/8351226/06f41abc-1b2c-11e5-842a-598bb6b26c57.png)

**Comment by aditikul** [comment]
@Redsandro Can you please check on the latest updates? We've worked on a more compact version while also trying to keep things legible. Let me know what you think.

**Comment by Redsandro** [comment]
@aditikul Do I need to select it somewhere, or is the theme a one-size-fits-all compact/legible version?

![image](https://cloud.githubusercontent.com/assets/1702193/17327794/58a4a1d4-58ba-11e6-82a4-dfe3a566c49f.png)

I am now on `4.4.3` / `linux / x86-64` / `Chrome 54.0.2810.2`.

It s better than before. Beautiful on high-res. Still spacey on smaller netbooks, but you can't have it all.

Because most of the things you see on screen aren't used after you've "set it and forget it" and you often just change the request and see what happens to the response, would it be an idea to have a special full-screen-ish view where you just have the req on the left and the res on the right, without all the tabs and settings?

You can already hide the sidebar, but you need to scroll between the req and the res, and then scroll within the req and the res. Would be a more speedy workflow if both of them are on screen, and you only need to scroll within the req/res.

**Comment by aditikul** [comment]
@Redsandro Good to know it's better! We're working on improving it further too. Yes we are working on something like a presentation mode that would be full-screen etc. however no ETA on that yet. To solve the scrolling issue to jump btw req and res, you can use the shortcut Cmd+Up or Cmd+Down for now. We are looking at better solutions for this too.

**Comment by Redsandro** [comment]
Those shortcuts don't seem to work for me (Linux). Tried Ctrl, Alt and Shift. They are not in the settings/shortcuts either. Do I need to force update 4.4.3 to a newer version?

It's probably a good idea to (have the option to) automatically jump to the res when it comes in after ctrl+enter or send.

**Comment by a85** [comment]
Everyone. Now you can use the Cmd + '+' shortcuts to zoom in. Cmd + '-' shortcuts to zoom out. This should let you use Postman as per your screen resolution or your use case. We are making more improvements to the UI and allowing more flexibility in moving things around.  (2-pane, 3-pane layouts for example)
