### ISSUE TITLE
Encoding and decoding request params doesnt work

### ISSUE THREAD

**Issue by kuplumosk** [a85/POSTMan-Chrome-Extension#11706]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

When i click encode\decode nothing happens, string doesnt getting encoded\decoded

### Steps To Reproduce

1. Enter a value to request param
2. Select value
3. Right click Encode\Decode
4. ??
5. Profit

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/65289716/217479098-ae5e1e72-e4ff-4577-b8cd-19ae074fe452.png)
Encode was clicked 
![image](https://user-images.githubusercontent.com/65289716/217479158-5a89241a-413e-4314-b380-357920cdb2b0.png)

### Operating System

Windows

### Postman Version

Version 10.9.3

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by MaddyTP** [comment]
Same issue here.

**Comment by postman-staff** [comment]
Hi @kuplumosk

This appears to be a bug and is in-line related to https://github.com/postmanlabs/postman-app-support/issues/11514

via @Raj-postman | Postman Support

**Comment by postman-staff** [comment]
Identified as an issue on this report here: https://github.com/postmanlabs/postman-app-support/issues/11798

Closing this to track on the same thread.
via @Raj-postman | Postman Support
