### ISSUE TITLE
Postman desktop is heavy

### ISSUE THREAD

**Issue by VirajShirwalkar** [a85/POSTMan-Chrome-Extension#11702]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Hi there,
I am using Postman desktop app for a while now and i found that app is heavy when there is other apps running.
(Tried with Chrome+Android Studio+Zoom+Skype+Postman+ (Notepad++))
It doesnt even load on dark mode (which is already set in Postman).
I had to close some apps to let Postman load. It wasted my time on only open-close apps.

Consider feature update: Make Postman "Super Lightweight".

### Steps To Reproduce

Try using dark mode of app and handle with some heavy apps open-close randomly.
Spend some time on it.

### Operating System

Windows 10

### Postman Version

10.9.3

### Postman Platform

Postman App

### User Account Type

Signed In User

### Additional Context?

Try using dark mode of app and handle with some heavy apps open-close randomly.

**Comment by kamalaknn** [comment]
Hey @VirajShirwalkar 

It looks like the Postman app is struggling to launch when the system is under heavy CPU/Memory load. Could you share some more details on your device configuration like, CPU and available memory?

I would love to understand how your development environment is influencing Postman launch experience. Let me know if you are available for a call to help me understand this better.
