### ISSUE TITLE
Unable to display console.log in Postman console if it's inside a function

### ISSUE THREAD

**Issue by florentabily** [a85/POSTMan-Chrome-Extension#11710]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

In a request's test tab, if you call a function that is created inside the collection's prerequest script, I don't see anymore any log created inside the function.
I tried to uninstall and reinstall Postman but I don't get logs anymore in the Postman console.

/!\ Do note that a console.log that is not inside a function is working as before.

### Steps To Reproduce

1) Create a collection
2) Create a request inside the collection, calling GET postman-echo.com/get
3) In collection's prerequest scripts tab, create the following function:
testLog = function testLog () {
    console.log("I want to log this line in the Postman console")
}
4) In the request's test tab, call the function like this: testLog();
5) Send the request
6) Open the Postman console and check if the log is displayed

### Operating System

Windows

### Postman Version

10.9.3

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by chongtaiyet** [comment]
ditto

**Comment by Danil-Zhikharev** [comment]
the same Postman v10.10.6
Windows 10

**Comment by coditva** [comment]
@florentabily @Danil-Zhikharev Thanks for reporting this. We're looking into it. This should be fixed in the next release.

**Comment by danielmadureira** [comment]
+1
I have some pre-request scripts on a collection and calls to `console.log()` do nothing.
I am on Ubuntu 20.04 LTS.

**Comment by antredor** [comment]
@coditva when will the new release with the fix be deployed ?

**Comment by coditva** [comment]
@antredor This will be available with **Postman v10.10.8**. You should get this update in the next few days, if not already.

**Comment by antredor** [comment]
Thank you @coditva, it's indeed already available with latest update and seems to work fine now.
