### ISSUE TITLE
Published documenter page gets unpublished after few seconds

### ISSUE THREAD

**Issue by karaburmication** [a85/POSTMan-Chrome-Extension#11719]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

**Is your request related to a problem? Please describe.**
My public documentation gets gets automatically unpublished after a few seconds.

**Describe the solution you'd like**
The public page should remain published.

**Additional context**
![postman issue](https://user-images.githubusercontent.com/17314795/218275256-b235471c-90c4-4787-b4ce-cb13b775e52b.gif)

### Steps To Reproduce

1. Publish collection
2. Wait 5 seconds
3. Open the public link
4. Get a 404 error instead of public documentation content.

It gets unpublished automatically without any error or warning.

![postman issue](https://user-images.githubusercontent.com/17314795/218275498-2b17d6d1-4316-4ef3-84f2-954fbee86758.gif)

### Operating System

Windows

### Postman Version

10.9.4

### Postman Platform

Postman Web

### User Account Type

Signed In User

**Comment by ekansh-001** [comment]
Hi @karaburmication,
Thanks for reporting & sincere apologies for the issue that you are facing in publishing this collection.
We have now resolved the underlying problem, you can go ahead and try to publish this again and it should work fine for you.
Let us know if you need any other assistance from our side.
