### ISSUE TITLE
Postman opens in new Window instead of a new tab

### ISSUE THREAD

**Issue by Drachenkaetzchen** [a85/POSTMan-Chrome-Extension#1171]
The old Postman did open nicely in a tab, which I much preferred over Postman 2.0 which opens in a new window.

Oddly enough, I can choose where to open the old PostMan:
![postman](https://cloud.githubusercontent.com/assets/162974/8331455/c21086d6-1a88-11e5-9c94-73360605f585.png)

With Postman 2.0, I no longer have that choice:

![postman2](https://cloud.githubusercontent.com/assets/162974/8331467/dd92c392-1a88-11e5-8940-67bb43ab1d47.png)

**Comment by sobtiankit** [comment]
Hi 

This is unfortunately a limitation of the Chrome app platform. All packaged apps open in their own window. Chrome has also deprecated the legacy app platform (the old Postman), which allowed extensions to open in tabs, so we have decided not to invest too many resources into it.

**Comment by khawajaasim** [comment]
@sobtiankit so is there way to do that in new tab rather than desktop window?
