### ISSUE TITLE
Ability to skip endpoint on the pre-request script

### ISSUE THREAD

**Issue by gadelkareem** [a85/POSTMan-Chrome-Extension#1172]
Sometimes we need to skip a request on the collection runner. For ex, user has already done this step and we have the result in our environment vars, so the request is not needed or it could end up as a failed test. Any workaround is welcome..

**Comment by Nahis** [comment]
I'd like to add my vote to this one. In addition or perhaps alternatively having flow control would be good (e.g. test condition and determine which endpoint to run next)

**Comment by raycheung** [comment]
This would advance the usability of postman to the next level by simply allowing this...

**Comment by xlash** [comment]
Is there a javascript command we can issue in pre-request scripts to skip this one?

**Comment by abhijitkane** [comment]
Hi @xlash,
We're working on a custom request flow, but we cannot offer an ETA as on now.

**Comment by xlash** [comment]
I did work around that for now using custom methods.

1- Pre-requests scripts contains a JS sequence-init method which verify status of previous test case. If we should skip the test, I'm changing my url to an  unresolvable entry DO_NOT_EXECUTE_TEST, which gets executed, but not against our servers.

2- Test scripts sets a flag if failed.

Now it's working on our side.

**Comment by abhijitkane** [comment]
@xlash @raycheung @Nahis We have a basic flow control mechanism in the latest versions of Postman - http://blog.getpostman.com/2016/03/23/conditional-workflows-in-postman/

**Comment by xlash** [comment]
Thanks, but i had to build my own.

Guillaume
