### ISSUE TITLE
Characters "{" and "}" are not encoded when they are present in a values for query parameters

### ISSUE THREAD

**Issue by kool79** [a85/POSTMan-Chrome-Extension#11722]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Characters "{" and "}" are not encoded when they are present in a values for query parameters

### Steps To Reproduce

1. Open new request tab
2. Add query parameter ("q") with value "{a b}"
3. Ensure that "Encode URL automatically" for this request == ON
4. Send request
5. Open console to view the actual request.
**_Expected:_** characters "{" and "}" in query parameter are encoded:   ?q=%7Ba%20b%7D
Actual: characters "{" and "}" are not encoded: ?q={a%20b} 
please note that "space" is encoded correctly

### Screenshots or Videos

![scr_2023_02_12T22_53_26](https://user-images.githubusercontent.com/4625317/218336445-b0dee57e-fdcd-41ff-8d08-8e1b9a33bc5b.png)

### Operating System

Windows

### Postman Version

10.9.4

### Postman Platform

Postman App

### User Account Type

Signed In User

### Additional Context?

related issue #8912 #11514

**Comment by sathishkumar-thangavel11** [comment]
@kool79  **"{"** and **"}"** are safe characters as per the [WHATWG standard](https://url.spec.whatwg.org/) and doesn't need explicit encoding. 

It is possible to encode the url parts in the following way  

https://user-images.githubusercontent.com/111063699/218651175-3dc2799a-33a7-4d9f-b685-4b1158efdb0f.mov

**Comment by SmashingQuasar** [comment]
@sathishkumar-thangavel11 

> @kool79 **"{"** and **"}"** are safe characters as per the [WHATWG standard](https://url.spec.whatwg.org/) and doesn't need explicit encoding.
> 
> It is possible to encode the url parts in the following way
> Screen.Recording.2023-02-14.at.11.20.18.AM.mov

Braces (`{` and `}`) must be encoded to interact with AWS, notably SQS and SNS. If you send a `MessageBody` with a non-encoded brace, AWS will response with a Bad Request.
Besides, the WHATWG (in the link you provided) indicates that encoding can be appreciated using Javascript `encodeURIComponent`. Running `console.debug(encodeURIComponent("{"))` in any Javascript terminal will output `%7B`.

You did provide a solution but it requires heavy manual work when developing using Posman through AWS. I see no reasonable explanation to specifically not encode braces.
