### ISSUE TITLE
Setting response body values as variables isn't working

### ISSUE THREAD

**Issue by lsheltonSTO** [a85/POSTMan-Chrome-Extension#11732]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Per the help documentation https://learning.postman.com/docs/sending-requests/variables/#setting-response-body-values-as-variables, it says I can just "Select the text, then right-click or Control-click.".  However, no amount of right-clicking or Control-clicking will give me any menu but the system menu, and for the 30 Day Challenge, I need to overcome this issue.  I think.

### Steps To Reproduce

1.  Open a new request tab
2. Send a successful 200 request to https://randomuser.me/api/
3. Go to t he Response Body
4. Highlight the first name in quotation marks
5. Try to right-click or control-click and see that all that you get is the system menu

### Screenshots or Videos

<img width="743" alt="image" src="https://user-images.githubusercontent.com/76535800/219170111-0701bd02-2f9b-48c3-bb44-8ec7e3899ce7.png">

### Operating System

Windows

### Postman Version

I don't know how to tell that

### Postman Platform

Postman Web

### User Account Type

Signed In User

**Comment by xk0der** [comment]
@lsheltonSTO Context menu to set variables would not work in the Postman browser app.

Download the Postman Desktop app from here: https://www.postman.com/downloads and things should work as expected.

I tested on Postman Desktop app v10.10.1 on MacOS - and I could see the context menu:
<img width="584" alt="Screenshot 2023-02-20 at 1 16 02 PM" src="https://user-images.githubusercontent.com/21366/219984142-72dabb4d-9034-4eb4-84e1-7cdab78eccb5.png">

**Comment by LuisJCU99** [comment]
I am in the app and using MAC OS and it is not working

**Comment by iangiraldo** [comment]
I am also using the desktop app in MacOS and I can confirm that is not working.

**Comment by anhtuta** [comment]
I am using the app on macos and it doesn't work! Here is my version

![image](https://github.com/postmanlabs/postman-app-support/assets/26838239/90a7fcf1-758d-48ee-8173-e92194728f00)

**Comment by aragornfbm** [comment]
Not working for me as well. Running Postman:

Version: 10.17.4
UI version: 10.17.4-ui-230825-0719
Desktop platform version: 10.17.4
Architecture: x64
OS platform: win32 10.0.19045

**Comment by edmerrett** [comment]
Not working for me as well. Running Postman:

```Postman for Mac
Version 
10.17.6
UI version 
10.17.6-ui-230904-0927

Desktop platform version 
10.17.4

Architecture 
arm64

OS platform 
OS X 22.6.0

**Comment by kryptonjohn** [comment]
Just updated to latest version of Postman desktop app for Windows  v11.0.7 and it still does not work.

**Comment by MorelSerge** [comment]
Same here, this doesn't seem to work on MacOS atm either (11.1.3)

**Comment by tilleul** [comment]
Postman 11.18 on Windows. Still not working.
![image](https://github.com/user-attachments/assets/d76bb40d-1195-4fbb-8c56-ffe9579955ea)
