### ISSUE TITLE
Removing text from filter should keep selected request<title>

### ISSUE THREAD

**Issue by maciej-nowicki-cg24** [a85/POSTMan-Chrome-Extension#11736]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

This is a thing that is frustrating me everyday while using postman. I have a non-small collection of requests, organized in many folders. I find some request by putting some text in filter and clicking on result. But usually what I want to do next is to remove the filter and see relevant other requests that are defined next to the one I just found. But when I remove the text from filter, it just collapses everything, deselect the request, and I’m back to square one. It’s so annoying, please stop doing that.
![image](https://user-images.githubusercontent.com/65535499/219658473-8b309dce-1d5c-4987-b523-715f970be749.png)
![image](https://user-images.githubusercontent.com/65535499/219658493-c0a353aa-1523-421c-90ee-eaf1d8fd30a5.png)

### Describe the solution you'd like

Stop deselecting request in left panel view when the filter text is removed. The panel should be still selecting the request.

**Comment by vedkribhu** [comment]
@maciej-nowicki-cg24 thanks for reporting this. This looks like a bug. I can suggest you a hacky workaround meanwhile. When you remove the filter, just switch tabs and your request should be highlighted again in the sidebar.

https://user-images.githubusercontent.com/37595282/219662906-6ca2ec10-fdbb-44a7-8299-2a496c07a775.mov



I will see to it that this gets resolved in our next release

**Comment by maciej-nowicki-cg24** [comment]
That's an amazing workaround, will help me a lot, thanks!

**Comment by maciej-nowicki-cg24** [comment]
I'm happy to report that the bug is gone. Thanks!
