### ISSUE TITLE
[Team Sync Beta] Globals > Import > Select File: Broken / Silently Failing

### ISSUE THREAD

**Issue by rex** [a85/POSTMan-Chrome-Extension#1173]
Hello there Postman team!
#### Preface

Before I get into this let me say first that the new interface is absolutely stunning and getting my team set up on this was painless and adopting this as a permanent solution for us is a no-brainer.
## The Actual Issue

We can't import `*.postman-globals` files in the environment manager. 
#### 1) Open the environment manager, select `Import`

![screenshot 2015-06-24 12 22 14](https://cloud.githubusercontent.com/assets/4247754/8336760/462c530e-1a6c-11e5-8522-90ba3b28493c.png)
#### 2) Select the `*.postman-globals` file

![screenshot 2015-06-24 12 22 23](https://cloud.githubusercontent.com/assets/4247754/8336779/727ec3d8-1a6c-11e5-9d84-8778db3e955e.png)
#### 3) Nothing happens. Which is the issue :)

![screenshot 2015-06-24 12 22 32](https://cloud.githubusercontent.com/assets/4247754/8336790/8a56494a-1a6c-11e5-9d89-602a937480c8.png)
## That Said,

I just wanted to make sure you guys had visibility on this. This is incredible software and doesn't prevent us from using it by any means. We're just sharing some global configs through HipChat now and it's all good.

Thank you for your hard work and **finally** making Postman the freemium application we've all wanted for so long with sync. WITH SYNC. Gosh it's hard to believe it's finally here. :rocket:

**Comment by abhijitkane** [comment]
There's no way to import global files right now - we'll integrate this with the environment importer soon.

**Comment by rex** [comment]
@abhijitkane Awesome, sounds great! Thanks for letting me know :smiley:

**Comment by GarthVader** [comment]
Any idea how soon is soon?  My team is about to start using Team Sync, but after setting up the environment and global variables...there doesn't seem to be any way to automagically share these settings with the whole team.   bummer!

**Comment by abhijitkane** [comment]
@GarthVader Environment files can be imported and exported. You can send the file to your team via email, and they can import it using the 'Manage environments' modal.

We'll also soon be adding collection-level variables. This will let you share selected variables along with the collection itself.

**Comment by jrichard0725** [comment]
@abhijitkane That responds with an "Import undefined" and creates an empty environment. It still does not import globals. It does work for non-global environments though.

**Comment by abhijitkane** [comment]
In Postman, global variables are not technically an environment. We're working on improving the UI and terminology around the environment/global flow

**Comment by brjennin** [comment]
Any idea if this is being worked on? Would love to be able to import globals

**Comment by tomhundt** [comment]
This is still is not working a/o 5/27/16 (11 months later).  Exporting is possible but importing is not.

**Workaround** is to store Globals in a text file and use Bulk Edit and copy/paste back and forth.

**Comment by abhijitkane** [comment]
Tracking at https://github.com/postmanlabs/postman-app-support/issues/2155
Will be pushing a fix in the next release.
