### ISSUE TITLE
"Exporting data to single dump file" feature is gone

### ISSUE THREAD

**Issue by dwiyatci** [a85/POSTMan-Chrome-Extension#11738]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

I used to be able to export data / all my collections to a single dump file (as shown in https://www.youtube.com/watch?v=sCWwOzhUMXE&t=489s), but not anymore since v10.10.3.

Only "Import data" is available now 🫤

### Steps To Reproduce

1. Go to "Settings" > "Data"
2. "Export data" feature is gone.

#### Before ┬─┬ノ( º _ ºノ)
<img width="722" alt="2023-03-24_00-54-31" src="https://user-images.githubusercontent.com/4405796/227304417-4ac7ea19-8769-4234-8db1-410e8d49d004.png">

#### After (╯°□°)╯︵ ┻━┻
<img width="722" alt="2023-03-24_01-02-11" src="https://user-images.githubusercontent.com/4405796/227304494-ab461510-bdbc-469d-a8ce-3236f63ab5e8.png">

### Operating System

macOS

### Postman Version

10.10.3

### Postman Platform

Postman App

### User Account Type

Signed Out User

### Additional Context?

Last working version for me is 10.9.4

**Comment by preethammavin** [comment]
@dwiyatci would love to know what workflow you were achieving through this. We have support for collection and environment export which can be accessed with each element. We had to remove the data dump export due to quality and performance issue caused by that capability.

**Comment by AFwcxx** [comment]
I'm having the same problem.

Postman Version 10.10.3

If that data dump export is removed, is there another way to export all collections without doing it manually one by one?

**Comment by dwiyatci** [comment]
@preethammavin Provided that:
- I have a bunch of collections and environments
- The company prohibits Postman's cloud/sync data functionality (hence the "Signed Out User" account type)
- I wanna share the collections and environments in question

Sharing/exporting each collection/environment one-by-one with my teammates becomes impractical and more than a pain (if not feasible) without this single data dump export capability 🤷🏻

**Comment by grinderX19** [comment]
I work in scratchpad only and I've used this feature to backup my stuff:

- before doing some major changes
- before upgrading to a new major Postman release
- for sharing between office and home PCs

Please restore this functionality.

**Comment by sratzlaff** [comment]
I'm also having the same issue.

I'd like to know the details of the issues encountered with this type of data export referenced by [preethammavin](https://github.com/preethammavin) above.

I never encountered any issues using the export data under settings so I'd like to hear the problems with exporting data this way.

**Comment by Rob-Barrow** [comment]
Same issue is seen for me and my colleagues too with Postman Version 10.10.3 - this was a very important feature for us and to just remove it like that without you engaging with your customers and users to find out how important that feature is to them is extremely poor customer service, and damaging to your customer base relationship. We would also like to know the full reasons why this feature was removed as we also never had any issues with data dump exports. Please restore this functionality.

**Comment by sratzlaff** [comment]
I noticed on the MacOS devices using non-Intel chips, i.e. Apple's M chips, their latest Postman versions 10.10.5 and 10.10.6 both still support this "global" export feature.  The option still exists under the Settings -> Data tab.

However, on Postman 10.10.3, the latest for MacOS Intel devices the feature has been removed. 

So is it only the latest Postman version on the Apple Intel devices where this feature was removed?

**Comment by nicolas-sapaig** [comment]
Same issue on :
Postman for Windows
Version 10.10.8
Architecture x64
Platform win32 10.0.19045

**Comment by sratzlaff** [comment]
Yeah 10.10.8 for MacOS Intel was released yesterday and same issue again.

**Comment by preethammavin** [comment]
Hey, we had to move in this direction as we could not reliably support large export from the application for all data, which was causing issues to our users. Having said that, we understand that users have workflows built on top of integrating Postman collections with your tools, hence we continue to support of collection and environment exports. 

For users who are using collections extensively to work on and collaborate, we suggest using Postman Workspaces so that your data can always stay backed up and available to you. We understand that your company might not allow you to have data in the cloud, in which case, can you write to us at help@postman.com so that we can understand your company's stance better and help you out.

**Comment by AFwcxx** [comment]
Sounds like trying to lock in your users..

**Comment by david-porter-messagemedia** [comment]
Hi!
This is disappointing! It was a very useful feature.

**Comment by evgeniimv** [comment]
So, for me it looks like one more step to get rid the guest mode (along with limitation of amount of collection runs).
The thing is that there are still huge amount of companies which do not support/allow user mode. It's not just our whim or laziness in not creating a user, its about strict regulations.  
Anyway, thanks for all you made so far, seems its time to get to know one of the alternatives like Milkman closer.

**Comment by yonibenitez** [comment]
Not even mentioned in the release notes... Time to think in alternatives.

**Comment by dwiyatci** [comment]
Exactly. Was gonna say that. IMHO:
- The feature should've been **deprecated** first (e.g. by putting a warning message/note in the UI) so that the users were clearly communicated as well as giving them a chance to give feedback, instead of removing the feature abruptly by assuming that no one is _really_ using this functionality without even considering their workflows.
- Even though the feature was decided to be removed in the end, it should've been removed in the next **major release** version, not in the minor one. This would at least give the users a choice if they don't wanna upgrade without making a workaround like https://stackoverflow.com/a/65966655 to remain in the particular minor version (v10.9.4). As unprofessional as it gets, the removal of this feature wasn't even jot down in the [Release Notes](https://www.postman.com/release-notes/postman-app/)!

**Comment by spex66** [comment]
How can I install an older version to Export (dump) all my data as before, so that I **own** the backup as a local json file?
This **hidden-removal** caught me absolutely by surprise and really annoys me.

**Comment by spex66** [comment]
> We had to remove the data dump export due to quality and performance issue caused by that capability.

@preethammavin really *"removed .. due to .."*?

But it is still used for automated backups (at least on win64, history of last ~11) in the exact same json-dump format as formally used?
- `C:\Users\<username>\AppData\Roaming\Postman\backup-2023-03-14T13-06-28.325Z.json`

Anyhow, at least I was able to get a full snapshot of my "single-user postman-life".

**Comment by sratzlaff** [comment]
> > We had to remove the data dump export due to quality and performance issue caused by that capability.
> 
> @preethammavin really _"removed .. due to .."_?
> 
> But it is still used for automated backups (at least on win64, history of last ~11) in the exact same json-dump format as formally used?
> 
> * `C:\Users\<username>\AppData\Roaming\Postman\backup-2023-03-14T13-06-28.325Z.json`
> 
> Anyhow, at least I was able to get a full snapshot of my "single-user postman-life".

MacOS for intel processors ifs the affected version.  Windows and MacOS M processors versions of Postman appear to be unaffected and still have the "full" export option.  Right now, this only affects MacOS running on Intel processor hardware.

Again, why only this OS/HW mix, who knows.  If Postman devs did this for all versions (OS/HW) they'd be getting a lot more negative feedback, I'm sure.

**Comment by formalist** [comment]
@sratzlaff  the options is missing for me also in Windows (ver. 10.12.0)

**Comment by sratzlaff** [comment]
Ah so Postman folks got around to other operating systems then, hmm.  Not good.

**Comment by vkras** [comment]
We need this option back, If it creates issues for some customers just add a disclaimer next to the export "Might fail on extra large exports, use at your own risk". I've never had any issues with it.

**Comment by argenstijn** [comment]
Yes, this option should be included. We cannot use workspace as it;s not allowed. That simple!.  
Export was very handy feature. 

What kind of issues? I would say, resolve them. Now causing a lot of issues for the other users.

**Comment by archive** [comment]
Please bring this feature back. We use it all the time to share collections and environments within the company. I also use it when moving to a new computer and what to do a quick export/import. 

I have 54 collections and 82 env's. Going one by one is not that fun :(

We are not interested in moving into the cloud solution. We like keeping it local and easy.

**Comment by arikast** [comment]
This is a deal-breaker for me.  Being able to efficiently backup my own data locally is a must-have.  Time to switch tools.

**Comment by toby11** [comment]
what a load of rubbish about not being able to export because its causing performance issues - its obvously because you want people to login - give us the option back.

**Comment by zib-ctrl** [comment]
Yes, for me it was an offline backup possibility. Nice to see it when back, but could also live without!

**Comment by tarmotubro** [comment]
I am migrating to a new computer, what a shame this feature is gone and I can't export/import easily. There is not even a bulk export of collections, need to do one by one. I am not buying this "caused problems" stuff.

**Comment by sratzlaff** [comment]
Has anyone here used SoapUI import Postman collection feature?

SoapUI, you need to click File>Import Postman Collection

Just wondering if SoapUI is a viable alternative to Postman?

**Comment by thatbrainiac** [comment]
> @dwiyatci would love to know what workflow you were achieving through this. We have support for collection and environment export which can be accessed with each element. We had to remove the data dump export due to quality and performance issue caused by that capability.

So when will it be back? As it appears, a lot of users need this.

**Comment by yonibenitez** [comment]
If you check the AppData/Roaming/Postman folder you'll see that every time the Postman version is upgraded, it creates a full backup. So this is like the export of Schrödinger, it works when they run it but it doesn't when we do.

But remember guys, it is for your safety. It is not related at all about giving away your data to the company. These are not the droids you are looking for.

**Comment by beedle-** [comment]
Time to migrate from this locked in tools to Insomnia.
Follow https://allsyed.com/posts/postman-to-insomnia/ using the backup file in AppData\Roaming\Postman. (For Microsoft users)
