### ISSUE TITLE
Cannot select OAuth2 token in GraphQL request

### ISSUE THREAD

**Issue by rolaca11** [a85/POSTMan-Chrome-Extension#11737]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

I cannot use an OAuth2 token that I retrieved from the auth server. If I select the already retrieved token, nothing is happening, like if the click event wasn't registered. If I try to use a token that I just retrieved (from the Manage Access Tokens window), I get a notification "Token added", but the Token field in the Authorization tab stays empty.

### Steps To Reproduce

1. Create new GraphQL request
2. Set up OAuth2 authorization
3. Acuqire new access token
4. Click Use token

### Operating System

Pop OS 22.04

### Postman Version

10.10.6

### Postman Platform

Postman App

### User Account Type

Signed Out User

### Additional Context?

I use the unofficial FlatPak version of Postman

**Comment by SterlingChin** [comment]
The new GraphQL client was released into [open beta](https://blog.postman.com/announcing-postmans-new-graphql-client/) as part of `10.10.8`. Can you try this in the new client and see if the issue persists?

**Comment by rolaca11** [comment]
It is still really scuffed. 
- If I'm not signed in, I don't have the option to create a GraphQL Request. I can only import it from a schema file, which creates folders, where I can seemingly use my OAuth 2 tokens 
![image](https://user-images.githubusercontent.com/3016706/221714242-951f6e05-4037-471f-83f6-3d15adac9414.png)


- If I'm signed in, I get to create a GraphQL request, but I have the same issue as I had before: unable to select OAuth tokens. The collection the request is in has no option to configure authorization at all (tab is missing) 
![image](https://user-images.githubusercontent.com/3016706/221714165-b0f62fb2-a6fc-4781-91a5-5426fabe0408.png)

- Still signed in, I can import a graphql schema from a file, in which case Postman creates an API with a few subfolders, where I can specify the authorization method, but it doesn't create a collection for it. 
![image](https://user-images.githubusercontent.com/3016706/221714031-f6796322-549e-4a88-afc7-da9cf8a69b6a.png)

EDIT: btw I used the official package this time, not the unofficial Flatpak version, on Pop os 22.04

**Comment by mattmurph9** [comment]
Same issue for me. Cannot set up Authorization for a collection of graphql requests

**Comment by samarv** [comment]
same for me

**Comment by SterlingChin** [comment]
Thank you for the added context. The team is addressing this issue, and we'll update here when the fix is in.

**Comment by appurva21** [comment]
Hey everyone! This issue is now fixed in the latest version of the Postman app (v10.12.0).

**Comment by rolaca11** [comment]
I'd like to protest: in the latest version, what I see is the UI does react to me clicking on a token in the dropdown, but it doesn't get selected. So functionality-wise, nothing changed. The only thing that did change was the dropdown disappearing when I click a token

**Comment by abhijeetborole** [comment]
@rolaca11 Thanks for reporting this, we're tracking an issue with token selection for unsaved GraphQL requests. Will update here once we have a fix up.

**Comment by mattmurph9** [comment]
It still seems I can't configure the authorization settings for a collection of graphql requests

**Comment by abhijeetborole** [comment]
Hey @rolaca11! the issue with token selection for unsaved GraphQL Requests is now fixed in the latest version of the Postman App (v10.13.0). The update will be available in the next few days.

**Comment by realexcel2021** [comment]
Hi, I'm on version (v11.6.1) and I'm facing the same problem

**Comment by ftreede** [comment]
Hi, I'm on v11.15 and am also experiencing this issue. I'm using the lightweight client. Please reopen this.
