### ISSUE TITLE
Code snippet PHP cURL - empty post fields

### ISSUE THREAD

**Issue by Alexis-Fayeulle** [a85/POSTMan-Chrome-Extension#11730]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

The code snippet generate a not-working code
there is missing POST fields in "PHP - cURL" code generation
then i enter data in "Body" > "form-data", this does not have an effect on code snippet
however, the number of parameters is well taken into account by the commas
but the content is empty
I imagine that it is probably a problem of reading the data in the form

### Steps To Reproduce

1. Open PostMan
2. Write a POST http call with "form data" filled with some data
3. Open Code snippet
4. Select "PHP - cURL"
5. In `curl_setopt_array()` function search for`CURLOPT_POSTFIELDS`
6. This field is `array(,,,)`

### Screenshots or Videos

![Capture d’écran 2023-02-15 à 09 48 14](https://user-images.githubusercontent.com/58552341/218978431-68bd26f1-c47e-4a89-95f1-ca7d988b03e1.png)

### Operating System

macOS

### Postman Version

10.10.3

### Postman Platform

Postman App

### User Account Type

Signed Out User

**Comment by matheusjohannaraujo** [comment]
I am also having this problem for a long time and unfortunately it is not only when I create an HTTP request using the POST verb and assemble the request body using FormData that I have the problem when exporting the request code in the PHP cURL option, this also happens in PHP HTTP_Request2 and PHP pecl_http.

The `CURLOPT_POSTFIELDS` is left with an empty array in all cases.

![image](https://github.com/postmanlabs/postman-app-support/assets/47996428/15ba35df-3fe2-453b-b59c-4ce42e41a0ec)

![image](https://github.com/postmanlabs/postman-app-support/assets/47996428/eaac93ad-8567-4d2e-9618-5cba1ac4283c)

![image](https://github.com/postmanlabs/postman-app-support/assets/47996428/3a418124-6437-45f3-98ff-c4a828e19508)

![image](https://github.com/postmanlabs/postman-app-support/assets/47996428/0cfb3871-250f-4b2e-ab9d-205e020dbc8b)

![image](https://github.com/postmanlabs/postman-app-support/assets/47996428/93f1a233-d703-40c9-a760-203a3228de82)

**Comment by aman-v-singh** [comment]
Closing, as it is fixed.
