### ISSUE TITLE
durable flow step is adding space at end of variable 

### ISSUE THREAD

**Issue by brian-methodical** [a85/POSTMan-Chrome-Extension#11740]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Durable variable parsing is adding a space

<img width="542" alt="Screen Shot 2023-02-19 at 12 06 11 AM" src="https://user-images.githubusercontent.com/101023641/219932035-3a080d8a-96dc-46c6-809b-86c4af7dfffb.png">

<img width="393" alt="Screen Shot 2023-02-19 at 12 06 28 AM" src="https://user-images.githubusercontent.com/101023641/219932041-43455ba5-3da1-4696-867a-a5945130250c.png">

<img width="844" alt="Screen Shot 2023-02-19 at 12 07 59 AM" src="https://user-images.githubusercontent.com/101023641/219932045-58e43f82-4e4d-42e7-a5d1-f5fbc3dac092.png">

### Steps To Reproduce

1. create a durable 
2. check the output on the server side

### Operating System

macOS

### Postman Version

10.1.0

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by SterlingChin** [comment]
With the latest version of [Postman Flows](https://blog.postman.com/postman-flows-the-next-generation-of-software-development/), durables have been removed and replaced by the Get Variable and Set Variable blocks. Please update your client or desktop app to the latest version (`v10.12.5`) and let us know if you are still encountering this issue with the new blocks.

**Comment by rabbah** [comment]
No longer valid, durables deprecated.
