### ISSUE TITLE
Application Postman hangs after running request and clicking "Preview" button 

### ISSUE THREAD

**Issue by Valerii1986** [a85/POSTMan-Chrome-Extension#11742]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Application Postman hangs after running request and clicking "Preview" button 

### Steps To Reproduce

1. Download and Setup Postman
2. Open COVID19-Tracker collection 
3. Run any request 
4. Click "Preview" button at the bottom 
5. Observe result 
![Postman_OW407pWF6s](https://user-images.githubusercontent.com/125874414/220078500-d235f830-2fb9-4ba4-8957-4b8ca2bd2566.gif)

### Screenshots or Videos

![Postman_OW407pWF6s](https://user-images.githubusercontent.com/125874414/220078629-4883ce80-4816-47a3-b3ea-952259fc4d0c.gif)

### Operating System

Win 10 x64 

### Postman Version

10.10.3.0

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by vedkribhu** [comment]
@Valerii1986 thanks for reporting this. I am able to replicate the issue at my end as well, taking a look. Seems related to this particular herukoapp server. Meanwhile, you can try using postman-web where the app is not getting stuck.

**Comment by Valerii1986** [comment]
Thank You

**Comment by ashuvyaspm45** [comment]
Hey folks, Sorry for the trouble you have to go through because of this issue. We have released a fix for this change and it's being rolled out and will be available to you in next few days. Please give it a try and give us feedback. Thanks for your patience.
