### ISSUE TITLE
Unable to create new branch in Azure repos from Postman 10.10.6 on Mac

### ISSUE THREAD

**Issue by chervineb** [a85/POSTMan-Chrome-Extension#11745]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Unable to create new branch in Azure repos from Postman 10.10.6 on Mac. Error received: "Something went wrong while creating the branch"

### Steps To Reproduce

In Postman 10.10.6 on Mac, click on the following:
1. Branching icon at the bottom of the screen
2. Create a new Branch
3. Enter branch name
4. Press enter
5. Error received: "Something went wrong while creating the branch"

### Screenshots or Videos

<img width="390" alt="Screenshot 2023-02-21 at 13 56 31" src="https://user-images.githubusercontent.com/49995379/220311837-7393d036-a205-4801-962b-93430196b13d.png">
<img width="390" alt="Screenshot 2023-02-21 at 13 56 51" src="https://user-images.githubusercontent.com/49995379/220311868-b2992b92-fe5b-4d26-9af8-fd33a0e793ce.png">

### Operating System

Mac

### Postman Version

10.10.6 

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by Alquh** [comment]
This also is happening on the following version. This is a blocker for us. 
![image](https://user-images.githubusercontent.com/5043356/222445486-99c9ae1e-872b-4f69-8593-7159ddd17586.png)

**Comment by nishantpostman** [comment]
Hi @chervineb @Alquh 
Thanks for reporting this issue.
We have now resolved the underlying problem, the flow should work fine for you all.
Let us know if you need any other assistance from our side.

**Comment by chervineb** [comment]
Thank you @nishantpostman !
