### ISSUE TITLE
Postman proxy doesn't work

### ISSUE THREAD

**Issue by dearlordylord** [a85/POSTMan-Chrome-Extension#1174]
I want to test my application API request with deflate content-encoding.

I use this https://github.com/postmanlabs/postman-app-support/wiki/Postman-Proxy with postman. 

I have postman proxy script running and proxy setting inside postmap set up to enabled and localhost:8000

I make http (not https, and no redirection after that) request.

I set Accept-Encoding in postman to 'deflate' and I see it is overridden to 'Postman-Accept-Encoding' in request headers. 

However, request isn't being sent to localhost:8000 and response encoding is still gzip.

Moreover, after I close proxy python script and ensure it isn't running, request from Postman still can be sent and working.

**Comment by a85** [comment]
You would need to set the proxy in your operating system if you haven't done that so.
