### ISSUE TITLE
[usability improvement] after clicking the "Save response" button, focus the name input box

### ISSUE THREAD

**Issue by cvmocanu** [a85/POSTMan-Chrome-Extension#1175]
After clicking the "Save response" button, the focus should be on the name input box to be able to start typing immediately.

**Comment by abhijitkane** [comment]
Thanks for reporting this - we'll push this change in v3.0.5.

**Comment by aditikul** [comment]
@cvmocanu This is fixed. Closing this, thanks for reporting!
