### ISSUE TITLE
Server sent events UI doesn't come up when the content-type of the response is `text/event-stream; charset=utf-8`

### ISSUE THREAD

**Issue by hollowpurple** [a85/POSTMan-Chrome-Extension#11753]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Hey guys,
Thank you for adding support for SSE in Postman! I have started using it and have found an issue that I think might be related to this line of code (I might be wrong) -

https://github.com/postmanlabs/postman-runtime/blob/b7c94a069771d99e432398165eb259eb4d17cd77/lib/requester/requester.js#L365

The event list UI doesn't show up in the case when `content-type` has the value `text/event-stream; charset=utf-8`

Maybe using `.startsWith` would fix this?

### Steps To Reproduce

1. Set the content-type header of the response to `text/event-stream; charset=utf-8`

### Screenshots or Videos

- After appending `charset=utf-8`
![charset-event-stream](https://user-images.githubusercontent.com/82367629/220724506-d8e11661-9903-4f8b-a971-a65f630bcbb4.gif)

- Without appending `charset=utf-8`
![no-charset-event-stream](https://user-images.githubusercontent.com/82367629/220724664-72fc2edc-821f-4dba-a7f9-a602228f888a.gif)

### Operating System

Windows

### Postman Version

10.10.7

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by codenirvana** [comment]
@hollowpurple you are right. Currently, there's a strict `content-type` check. We'll fix this soon.

**Comment by picpicb** [comment]
It would be great to handle both. I found a workaround for my api to remove the charset in the header, but i can’t do that in production env.

**Comment by codenirvana** [comment]
@picpicb Yes, the fix will be released this week with Postman v10.12.

**Comment by appurva21** [comment]
Hey everyone! This issue is now fixed in the latest version of the Postman app (v10.12.0).
