### ISSUE TITLE
Azure DevOps integration breaks after being connected across team workspaces intermittently

### ISSUE THREAD

**Issue by boylec** [a85/POSTMan-Chrome-Extension#11759]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

We have a team of three in a shared team workspace.

We have connected an API to a git repository via the Azure DevOps integration.

This works great, until seemingly randomly one day the API mysteriously loses the connection to git.

Once this happens, both that team member, and the online (browser) version of API experience the same issue, while other team members seem to still "see" the underlying API in their own local desktop applications.

Once the team member disconnects the integration and reinitializes it, the issue goes away. Then inevitably the issue will come back again for a random team member a few days layer.

### Steps To Reproduce

Can't reproduce every time. Its just an issue that shows up randomly.

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/8148174/220958140-32e3415e-b77a-4bf6-96d0-771a099f14b6.png)

### Operating System

macOS or Windows

### Postman Version

Version 10.10.8 UI Version: 10.10.8-ui-230222-0842 Desktop Platform Version: 10.10.8 (10.10.8)

### Postman Platform

Both

### User Account Type

Signed In User

**Comment by boylec** [comment]
Note: We think we found the issue.

When the remote branch is deleted, the postman app basically gets completely stuck. You can't see the API stuff, nor (from what we can tell) can you switch back to the main/master branch once the app is in that state.

Seems like the solution should be: allow the user to switch the remote branch they are pointed at, even when the current remote branch fails to connect (because its been deleted by another team member because the underlying work is actually completed)

Make sense?

**Comment by nishantpostman** [comment]
Hi @boylec 
Thanks for reporting this issue.
We have now resolved the underlying problem, you can go ahead and try out the same flow again and it should work fine for you.
Let us know if you need any other assistance from our side.
