### ISSUE TITLE
Postman's homepage opens a blank page v10.11.0 

### ISSUE THREAD

**Issue by MJayybee21** [a85/POSTMan-Chrome-Extension#11757]
### Is there an existing issue for this?

- [x] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Hello everyone,

I recently updated my version of postman on windows and after the update finished, my postman app gets stuck on a blank home page. It is possible for me to access the "explore" section, but I cannot access my workspace.

I did see other users reporting this problem BUT it was for an older version of postman, I am unsure if this is an issue from my end or if it is something other users are experiencing as well.

The postman website on the other hand is working fine, I am able to access it there but cannot do testings of applications on my localhost :(

### Steps To Reproduce

1- open the postman app on windows (or on a VM that runs on windows OS)
2- check if you get stuck on the main page

### Screenshots or Videos

![postman_issue](https://user-images.githubusercontent.com/114151172/220947534-102a6dac-7570-4191-a349-348fcda8bf04.png)
![postman_issue_n2](https://user-images.githubusercontent.com/114151172/220948346-c38a148f-3114-403e-aaaf-be1c8af1efae.png)

### Operating System

Windows

### Postman Version

10.11.0

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by patricksevat** [comment]
Hi @MJayybee21 , thanks for taking the time to create a report.

I've just tried to replicate this by downloading 10.11.0 on Windows 11 Home x64 and signing in. I do not get stuck and the application works fine for me.

But I'd really like to help you get unblocked so I'd like to request some additional information:

- Could you attach `main`, `renderer-auth`, `renderer-requester` from the logs directory, you can find those by opening the hamburger menu (see 1 in the image below) and clicking on `View Logs in Explorer`
- Additionally, could you also open DevTools, see the screenshots below. You can right click on any message and click on `save as`. If you could attach that as well, that would be very useful

![image](https://user-images.githubusercontent.com/16444755/220975058-086d14bb-7bb2-4db5-9d21-9caa4797143d.png)

![image](https://user-images.githubusercontent.com/16444755/220975429-40099581-de63-46be-b079-0994eb8941ab.png)

**Comment by MJayybee21** [comment]
Hello @patricksevat , thank you very much for helping me in this matter. here are the files requested:
[main.log](https://github.com/postmanlabs/postman-app-support/files/10816409/main.log)
[renderer-auth.log](https://github.com/postmanlabs/postman-app-support/files/10816410/renderer-auth.log)
[renderer-requester.log](https://github.com/postmanlabs/postman-app-support/files/10816411/renderer-requester.log)

**Comment by patricksevat** [comment]
Thanks! I'll take a look and get back to you shortly

**Comment by patricksevat** [comment]
Thanks again for the logs @MJayybee21 , we've found some interesting clues which we are going to investigate further.
As an immediate workaround you could install Postman, [download 10.10.8](https://dl.pstmn.io/download/version/10.10.8/win64) and install that in stead. 

Hopefully that should get you on your way again while we dig deeper

**Comment by patricksevat** [comment]
Sorry, please disregard my previous comment (which I have now deleted).
PS: have you already tried logging out and in again?

**Comment by MJayybee21** [comment]
Hello Again @patricksevat, apologies for my late response

I just logged out and logged back In and the issue was solved thank you very much!

**Comment by patricksevat** [comment]
Hi @MJayybee21 ,

Thanks for the info and happy to hear that the issue was resolved by logging out and in again.

I'll close this ticket, but do let us know if you encounter this issue in the future again
