### ISSUE TITLE
Outline view missing in 3.0.0.9 (packaged)

### ISSUE THREAD

**Issue by postman2014** [a85/POSTMan-Chrome-Extension#1176]
Hi, I work a lot with API's that export filters. I have always heavily used the outline view on the right hand side to navigate large responses and find specific filters. I have tried looking around the packaged app and also searching the documentation, is there a way to restore the outline view? I don't have an old version of the app available to test if it was called something else.

Version 3.0.0.9 (packaged)
OS: mac
Architecture: x86-64

Thanks,

**Comment by abhijitkane** [comment]
The outline view for the XML responses was removed in the new version. The functionality to expand/collapse XML views is still there (the arrow to the right of the line number).

**Comment by a85** [comment]
Closing. This is part of a bigger project now to have custom renderers
