### ISSUE TITLE
Environment variable not set on url Graphql Beta

### ISSUE THREAD

**Issue by Renato66** [a85/POSTMan-Chrome-Extension#11765]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

On the new Graphql Beta using variables at url do not load schema

### Steps To Reproduce

{{api_url}}/graphql // api_url = http://localhost:9000
runs infinity loading
<img width="735" alt="image" src="https://user-images.githubusercontent.com/9284273/221383575-5000b057-3b49-427d-9191-d09fac701e93.png">

http://localhost:9000/graphql
<img width="496" alt="image" src="https://user-images.githubusercontent.com/9284273/221383563-007cc917-3ab9-444e-8726-b70ab531a17e.png">

### Operating System

MacOs

### Postman Version

10.10.9

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by imwexpex** [comment]
https://github.com/postmanlabs/postman-app-support/issues/11766

Same

**Comment by SterlingChin** [comment]
Thank you for reporting this bug. I've been able to reproduce this, and we are tracking a fix for this.

**Comment by appurva21** [comment]
Hey @Renato66 @imwexpex! This issue is now fixed in the latest version of the Postman app (v10.12.0).

**Comment by muhammadsalah** [comment]
The isssue is not fixed in my postman v10.17.4

**Comment by jpamdeth** [comment]
Also broken in Version 10.19.14

**Comment by sshevlyagin** [comment]
Still broken v10.21.9

**Comment by timhall** [comment]
Thanks for continuing to report this issue, I think it's related to https://github.com/postmanlabs/postman-app-support/issues/12456. This has been fixed and is scheduled for the January Postman release. I'll update this thread when the release has been completed.
