### ISSUE TITLE
autosave any change in tabs

### ISSUE THREAD

**Issue by loveyandex** [a85/POSTMan-Chrome-Extension#11771]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

title is clear and enough do it

### Describe the solution you'd like

sdsdj'sd csdc sadc sdc

**Comment by preethammavin** [comment]
https://github.com/postmanlabs/postman-app-support/issues/8195 tracking it here
