### ISSUE TITLE
HTTP_Date not taken into account

### ISSUE THREAD

**Issue by JoMisk** [a85/POSTMan-Chrome-Extension#1177]
Hi,

As per my understanding it seems that when entering in http header "Date" as key and a date "2015-06-25 13:09:07" in UTC as value, the http header when sending the request  "Date → Thu, 25 Jun 2015 13:09:23 GMT" is not taken into account.

Do you have a work arround  solution ?

Thanks for your help,

**Comment by abhijitkane** [comment]
Do you have the Interceptor on? 'Date' is a restricted header, and cannot be sent without the Interceptor.

**Comment by shamasis** [comment]
@JoMisk we released a canary version of our Mac app that allows you to send restricted headers - https://github.com/postmanlabs/postman-app-support/issues/1023

**Comment by abhijitkane** [comment]
@JoMisk Available at http://blog.getpostman.com/2016/06/14/introducing-postman-runtime-more-power-better-control/
