### ISSUE TITLE
Mac desktop app not rendering after login

### ISSUE THREAD

**Issue by gfortin6** [a85/POSTMan-Chrome-Extension#11779]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

I just updated to version 10.11.1 on my MacBook pro running OS Ventura.
I set up the 2FA and since then after login myself on the web, I get redirected to the app and the screen remains empty.
Also i can't move the window. I can just resize it

### Steps To Reproduce

1. open the app
2. click sign in
3. sign in on the web using username, password and 2FA
4. after login get redirected to the app
5. nothing is displayed

### Screenshots or Videos

<img width="746" alt="Screenshot 2023-03-01 at 9 32 15 AM" src="https://user-images.githubusercontent.com/30575183/222170563-314aa236-20cc-4459-965f-5966650d7a0e.png">

### Operating System

macOS

### Postman Version

10.11.1

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by patricksevat** [comment]
Hi @gfortin6 , that's very annoying. I tried to reproduce on Monterey using 2FA, but did not encounter the issue there.
I'll update to Ventura and see if I can reproduce this.

In the mean time, could you please email me your application logs?
You can find them using these instructions: https://support.postman.com/hc/en-us/articles/360025298633-How-to-get-logs-from-the-Postman-Desktop-app#h_01G396RG1PATWM520KV442RCSJ 

You can email me on patrick.sevat@postman.com

**Comment by patricksevat** [comment]
Hi @gfortin6 ,

I've taken a look at the logs and see that the authentication is not going as expected.
Could you follow the steps here and let me know if the issue persists? https://support.postman.com/hc/en-us/articles/360025359014-Troubleshooting-steps-for-Postman-desktop-issues

**Comment by gfortin6** [comment]
Hi Patrick,
So cleaning cache didn’t work, but deleting the postman folder did the trick.
Thanks for your help


From: Patrick Sevat ***@***.***>
Date: Wednesday, March 1, 2023 at 3:34 PM
To: postmanlabs/postman-app-support ***@***.***>
Cc: gfortin6 ***@***.***>, Mention ***@***.***>
Subject: Re: [postmanlabs/postman-app-support] Mac desktop app not rendering after login (Issue #11779)

Hi @gfortin6<https://github.com/gfortin6> ,

I've taken a look at the logs and see that the authentication is not going as expected.
Could you follow the steps here and let me know if the issue persists? https://support.postman.com/hc/en-us/articles/360025359014-Troubleshooting-steps-for-Postman-desktop-issues

**Comment by patricksevat** [comment]
Happy to hear! Closing the ticket
