### ISSUE TITLE
Enable users to ignore security concerns for exposed tokens

### ISSUE THREAD

**Issue by TheYuriG** [a85/POSTMan-Chrome-Extension#11776]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

Not exactly a problem, as this aims to protect users from hurting themselves.

### Describe the solution you'd like

On the emails that Postman sends about Token Exposure concerns, add a link to disable all security warnings for exposing a Token in the current Workspace collection.

I'm aware that you guys are trying to trying to not give us enough rope to hang ourselves, but the Token that I'm using is public to the API and everyone has access to it. You don't need to keep sending me email after email after email telling me I've exposed my token and I need to replace it and then save it as a variable.

We don't need to save it as a variable, there is no need to hide the Token and I would like to stop getting emailed about it. And no, I don't want to save it as a variable either because that will give another step to the people I want to allow to use this Public API.

### Describe alternatives you've considered

Allow somewhere in the Collection settings to enable public Tokens, even if it forces you to confirm twice after acknowledging the potential risks of doing so, if you don't know what you are doing.

### Additional context

Also, consider putting these security emails on a cooldown, I get one every time I save changes to the collection HTTP request. Maybe once every 15, 20, or 30 minutes?

**Comment by TheYuriG** [comment]
25 emails and counting.
Moving the variable to the pre-request field doesn't change anything either.

**Comment by Suhas-Gaikwad** [comment]
@TheYuriG Thanks for the feedback. We are looking into it. We will update this thread once the fix is ready.

**Comment by TheYuriG** [comment]
> We don't need to save it as a variable, there is no need to hide the Token and I would like to stop getting emailed about it. And no, I don't want to save it as a variable either because that will give another step to the people I want to allow to use this Public API.

I managed to get around this by creating two `const` on the pre-request field, then joining them when setting the `Global Variable`. That silenced Postman and the emails for good.

Example code:
```js
const const1 = 'Basi';
const const2 = 'c lettersnumberscharacterstocreatetheauthorizationbasic'
pm.globals.set('token-that-i-will-literally-expose-and-the-cops-cant-do-anything-about-it', const1 + const2)
```

This way I could avoid users from having the same email-spam issue I had while also not forcing them to manually set the same variable themselves.

**Comment by Suhas-Gaikwad** [comment]
We have implemented a fix to reduce the number of emails sent from the Postman Secret Scanner. Additionally, we have introduced [new security updates to the Public API Network:  a new secret-protection policy](https://blog.postman.com/public-api-network-security-updates-secret-protection-policy/). So, we are closing this issue. Thank you.
