### ISSUE TITLE
updated change log

### ISSUE THREAD

**Issue by jungle-boogie** [a85/POSTMan-Chrome-Extension#1178]
Hello,

I am running:
Version 3.0.0.9 (packaged)
OS: win
Architecture: x86-32
Native client architecture: x86-64

But the recent change log at https://www.getpostman.com/changelog

Only has Version v2.0.5. Should I be using 2.0.5?

Thanks!

**Comment by abhijitkane** [comment]
The 3.x versions have not been pushed out to all users. We're ramping up the new version's user-base gradually. Once we start releasing the 3.x series to all users, we'll update the changelog.

As of now, 3.0.0.9 is the latest version.

**Comment by jungle-boogie** [comment]
Hi abhijitkane,

Thanks, I had not realized it was possible to be on different versions.

Thanks!
