### ISSUE TITLE
Error calling api:  EPROTO 64839048:error:1000012e:SSL

### ISSUE THREAD

**Issue by jasonkaisersmith** [a85/POSTMan-Chrome-Extension#11785]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

When calling my api via Postman I am getting the following error:

Error: write EPROTO 64839048:error:1000012e:SSL routines:OPENSSL_internal:KEY_USAGE_BIT_INCORRECT:../../../../src/third_party/boringssl/src/ssl/ssl_cert.cc:607:

"Enable SSL certificate verification" is turned OFF

**Output from console**

GET https://192.168.178.61:8888/api/MonitorValues/Device/4/
Error: write EPROTO 64839048:error:1000012e:SSL routines:OPENSSL_internal:KEY_USAGE_BIT_INCORRECT:../../../../src/third_party/boringssl/src/ssl/ssl_cert.cc:607:
Request Headers
Authorization: Bearer {my token}
User-Agent: PostmanRuntime/7.31.1
Accept: */*
Postman-Token: 981b696b-5f3c-4af2-a568-099d7eb137d0
Host: 192.168.178.61:8888
Accept-Encoding: gzip, deflate, br
Connection: keep-alive

Executing the same api via another program works OK.
Also executing via curl from the command prompt works ok

Below is more details

**Output from curl -v**
curl -v https://192.168.178.61:8888/api/MonitorValues/Device/4/ -H "Accept: application/json" -H "Authorization: Bearer {my token}"
*   Trying 192.168.178.61:8888...
* Connected to 192.168.178.61 (192.168.178.61) port 8888 (#0)
* schannel: disabled automatic use of client certificate
* schannel: using IP address, SNI is not supported by OS.
* ALPN: offers http/1.1
* ALPN: server accepted http/1.1
> GET /api/MonitorValues/Device/4/ HTTP/1.1
> Host: 192.168.178.61:8888
> User-Agent: curl/7.83.1
> Accept: application/json
> Authorization: Bearer {my token}
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Content-Length: 2695
< Content-Type: application/json; charset=utf-8
< Date: Fri, 03 Mar 2023 08:40:39 GMT
< Server: Kestrel
<
{my expected output}
Connection #0 to host 192.168.178.61 left intact

**Output from openssl client call**

openssl s_client -state -connect 192.168.178.61:8888 | openssl x509 -text
SSL_connect:before SSL initialization
SSL_connect:SSLv3/TLS write client hello
SSL_connect:SSLv3/TLS write client hello
SSL_connect:SSLv3/TLS read server hello
Can't use SSL_get_servername
SSL_connect:TLSv1.3 read encrypted extensions
depth=0 {details removed}, CN = 192.168.178.61
verify return:1
SSL_connect:SSLv3/TLS read server certificate
SSL_connect:TLSv1.3 read server certificate verify
SSL_connect:SSLv3/TLS read finished
SSL_connect:SSLv3/TLS write change cipher spec
SSL_connect:SSLv3/TLS write finished
Certificate:
 {details removed}
-----END CERTIFICATE-----
SSL_connect:SSL negotiation finished successfully
SSL_connect:SSL negotiation finished successfully
SSL_connect:SSLv3/TLS read server session ticket
SSL_connect:SSL negotiation finished successfully
SSL_connect:SSL negotiation finished successfully
SSL_connect:SSLv3/TLS read server session ticket

### Steps To Reproduce

Open new request
Enter API
Add bearer token details
Execute command

### Operating System

Windows

### Postman Version

10.11.1

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by postman-staff** [comment]
Hi @jasonkaisersmith,

Thank you for reaching out!
Can you try using the `HTTP` protocol not `HTTPS` to send requests to the server?

via @beatrixSze | Postman Support

**Comment by jviotti** [comment]
I believe this is a limitation of Postman using Electron, which in turns relies on the strict BoringSSL implementation instead of OpenSSL in comparison to i.e. `curl` or other HTTPS-sending programs.

While we don't have a solution at this point, we are working towards using vanilla OpenSSL for our stack, which should solve this problem. I'll tag this issue accordingly and we'll give updates on the state of this!

**Comment by jviotti** [comment]
What OS are you running btw? macOS?

**Comment by jasonkaisersmith** [comment]
Thanks for the update.

The Postman app is running on Windows 10.

**Comment by jasonkaisersmith** [comment]
Thanks for the update.

The Postman app is running on Windows 10.

**Comment by sustainiam** [comment]
I am facing this issue as well.
If I use a public IP(http://xx.xxx.xx.xx:8080/), it gives me this error - and the domain is mapped to another port. Don't know what to do.

**Comment by AythaE** [comment]
I have the same issue with the following environment, I'm able to connect with curl although Postman fails

### Operating System

Ubuntu 22.04.3 LTS

### Postman Version

10.22.13

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by clxppischel** [comment]
We also have this problem still yet.

**Comment by devrsw** [comment]
We also still have this - is this only fixed on Windows? We are using Postman for Mac:

`Error: write EPROTO 1168232811360:error:1000012e:SSL routines:OPENSSL_internal:KEY_USAGE_BIT_INCORRECT:../../../../src/third_party/boringssl/src/ssl/ssl_cert.cc:605:`

"Enable SSL certificate verification" is turned OFF.

**Comment by deepakkale** [comment]
I've created self signed certificate on IIS and when I try to access it outside of our server i.e using browser and postman. I'm seeing same error. It works with http however I want to use https

**Comment by Maritims** [comment]
Should this issue really be closed?

Surely this issue will persist until Postman adopts OpenSSL instead of relying on BoringSSL as indicated by the reply from @jviotti on 2023-03-06?
