### ISSUE TITLE
socks proxy not working  

### ISSUE THREAD

**Issue by starcwl** [a85/POSTMan-Chrome-Extension#11790]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

I have enabled custom proxy configuration.
I use wireshark to capture the tcp stream, I found that postmen send TCP-SYN packet which should have sent a TCP-ACK packet which has socks request info  after four packets. 

![image](https://user-images.githubusercontent.com/12868797/222920040-be860766-8b94-499f-b830-43dea9abe408.png)

### Steps To Reproduce

1. enabled custom socks proxy and set 127.0.0.1:9999
2. send request via postman

### Operating System

macos

### Postman Version

Version 10.11.1

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by postman-staff** [comment]
Hi @starcwl,

Thank you for reporting this to us.

We are trying to test this for the setup. Meanwhile, wanted to verify if you could repeatedly have this reproduced? Are you seeing the same behaviour for the new session?

via @Raj-postman | Postman Support

**Comment by starcwl** [comment]
> Hi @starcwl,
> 
> Thank you for reporting this to us.
> 
> We are trying to test this for the setup. Meanwhile, wanted to verify if you could repeatedly have this reproduced? Are you seeing the same behaviour for the new session?
> 
> via @Raj-postman | Postman Support

Yes, I have updated the app to the latest version. It is still not working, so I wonder if Postman is loading a local library that has a problem. If you can provide some debugging advice, I can try it.

**Comment by postman-staff** [comment]
@starcwl This appears to be due to https://github.com/postmanlabs/postman-app-support/issues/1321

SOCKS5 proxies are not natively supported in Postman. There are a few workarounds where you can implement a proxy server to convert from HTTP proxy to SOCK5, but the set-up would happen outside of Postman. I've included [this thread here](https://stackoverflow.com/questions/47296837/using-socks-proxy-with-postman) for you to refer.

via @Raj-postman | Postman Support

**Comment by starcwl** [comment]
> @starcwl This appears to be due to #1321
> 
> SOCKS5 proxies are not natively supported in Postman. There are a few workarounds where you can implement a proxy server to convert from HTTP proxy to SOCK5, but the set-up would happen outside of Postman. I've included [this thread here](https://stackoverflow.com/questions/47296837/using-socks-proxy-with-postman) for you to refer.
> 
> via @Raj-postman | Postman Support

I have set-up a proxy server at 127.0.0.1:9999 using Charles. The problem is Postman can not send correct Socks handshake packets to my proxy server.

**Comment by postman-staff** [comment]
@starcwl True, as mentioned previously this is because Postman supports only HTTP proxies at the moment.

Currently, Socks proxy isn't supported. You can track the same on this GitHub thread here: https://github.com/postmanlabs/postman-app-support/issues/1321

via @Raj-postman | Postman Support

**Comment by starcwl** [comment]
> 

OK, I get what you mean now.  Postman does not support Socks Proxy; it supports HTTP Proxy.. 
[http-proxy-to-socks](https://github.com/oyyd/http-proxy-to-socks) is works for me.
