### ISSUE TITLE
Document types inconsistent between Postman desktop app and published docs

### ISSUE THREAD

**Issue by alexcochran** [a85/POSTMan-Chrome-Extension#11795]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

I used Postman's WSYWIG editor to author some documentation in the desktop app (Linux_x64, Ubuntu 22.04) and web app. When I put code blocks in the documentation or include sample responses in the accompanying collection and specify a document language (e.g. JSON), it renders the language name properly in the desktop/web apps but not the published documentation website available online.

### Steps To Reproduce

1. Write documentation using Postman Desktop/web apps + the beta WSYWIG Postman Editor
2. Publish documentation (to a publicly available online domain)
3. View code block example and sample response document types in both locations

### Desktop / Web App

![postman](https://user-images.githubusercontent.com/22733754/223178049-aac750a3-9115-4d8d-ba8d-a26bc2987748.png)

### Published (web)

![website](https://user-images.githubusercontent.com/22733754/223178040-57958047-a447-42b7-9489-747502b1c817.png)

--- 

### Desktop

![response_postman](https://user-images.githubusercontent.com/22733754/223177960-23e60285-9eae-4500-98aa-a414250d1c28.png)

### Published (website)

![responsnse_website](https://user-images.githubusercontent.com/22733754/223177869-fee81303-6cdc-4be0-ad0c-44b37592bcfa.png)

### Operating System

Linux

### Postman Version

10.11.1

### Postman Platform

Both

### User Account Type

Signed In User

**Comment by ishan-ks** [comment]
Hey @alexcochran Thanks for reporting this. This seems like a bug. We're actively looking into it and will keep you posted on the progress.

**Comment by ishan-ks** [comment]
This is fixed now.

**Comment by alexcochran** [comment]
Thanks so much! Really appreciate you helping out here.
