### ISSUE TITLE
Checkboxes in the GraphQL client query option get auto-cleared

### ISSUE THREAD

**Issue by Srinu3366** [a85/POSTMan-Chrome-Extension#11797]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Checkboxes in the GraphQL client query option get auto-cleared. It is also not giving me the option to enter input values.

### Steps To Reproduce

1. Create a new request of type GraphQL
2. Provide GraphQL endpoint 
3. Use the GraphQL introspection option
4. Try to query the field by selecting the check. Checkbox gets auto-cleared.
5. I tried using the Postman Echo collection. It works fine if I use the Query GraphQL request, but I have the same issue when I try to run a query from the Introspection request.

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/25985494/223579631-602f6d00-965e-4a26-b3a9-633c06ca1ddc.png)

### Operating System

Windows

### Postman Version

10.11.1

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by SterlingChin** [comment]
A fix for this issue is rolling out with Postman `v10.12.x`. For more information, you can check out [this related issue](https://github.com/postmanlabs/postman-app-support/issues/11777).

**Comment by Srinu3366** [comment]
Thanks, @SterlingChin for getting back quickly. I am closing this issue as it is already being fixed in the next release.
