### ISSUE TITLE
Tests for response time in Collection runner is broken

### ISSUE THREAD

**Issue by fightersmurf** [a85/POSTMan-Chrome-Extension#1179]
Running a Collection with multiple requests and each request has a test for response time, the response time is calculated from start of the collection run, not start of the request.
After a collection has run, if you wait and choose "New run", response Times are way off and don't even start at zero or a reasonable time

**Comment by abhijitkane** [comment]
I'm not able to reproduce this. I created a collection with 3 requests, all GET http://dump.getpostman.com/get
Each request had `console.log(responseTime);` in the test script.

I ran the collection in the collection runner multiple times, by clicking 'New run' after one had finished. Response times for all requests (both in the collection runner window, and the ones printed in the console) were between 350 and 450, and did not show any increasing trend.

I'm running version 3.0.0.9.

**Comment by fightersmurf** [comment]
i use the tests as in the test snippets
tests["Response time is less than 1000ms"] = responseTime < 1000;

**Comment by abhijitkane** [comment]
Can you print them out to the console and check?

To enable the console - http://blog.getpostman.com/2015/06/13/debugging-postman-requests/

**Comment by fightersmurf** [comment]
i have an old run from before the update and exported the results, then extracted the "time" in the results and checked with a new run and a second run after about 20 secs.

here are the results.
old run:
            "time": 496
            "time": 1212
            "time": 156
            "time": 160
            "time": 158
            "time": 101
            "time": 50
            "time": 136
            "time": 98
            "time": 111
            "time": 134
            "time": 88
            "time": 189
            "time": 184

new run
            "time": 214,
            "time": 942,
            "time": 1444,
            "time": 1897,
            "time": 2380,
            "time": 2625,
            "time": 2902,
            "time": 3327,
            "time": 3663,
            "time": 3990,
            "time": 4374,
            "time": 4570,
            "time": 4886,
            "time": 5401,
            "time": 5955,

second run
            "time": 26777
            "time": 26886
            "time": 27014
            "time": 27145
            "time": 27235
            "time": 27355
            "time": 27457
            "time": 27564
            "time": 27686
            "time": 27789
            "time": 27853
            "time": 27945
            "time": 28019
            "time": 28135
            "time": 28205

as you can see in the results, in the new and the second run, times always gets bigger, the second run even started with 26 seconds although the request only took about a second. 
output in the console (via console.log(responseTime);) equals those numbers.

**Comment by abhijitkane** [comment]
Can you import this collection - https://www.getpostman.com/collections/29dde8d0bbd8cfe7a11d, and see if you're able to reproduce the problem?

I've tried a number of times, but the response times never go above 450.

**Comment by fightersmurf** [comment]
imported the collection, same problem. do you have an email where i can send you the test run results exported from collectionrunner?

**Comment by abhijitkane** [comment]
You can send the file to help@getpostman.com

**Comment by fightersmurf** [comment]
i deleted postman app, postman extension and postman interceptor, resynced everything and now it works...i am a bit embarrased :(.
Sorry for all the hassle.
