### ISSUE TITLE
Delete Examples in bulk

### ISSUE THREAD

**Issue by Hamzablm** [a85/POSTMan-Chrome-Extension#11792]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

When I imported open API 2.0 spec into postman. It imported with it a bunch of examples in the requests in created:
![image](https://user-images.githubusercontent.com/32052228/223085194-723a74b4-09cf-4653-b0f5-9f5fe91f25cc.png)
I use the search bar to search for request, and it's annoying to find the examples every time I do a search.

### Describe the solution you'd like

I see two solutions : 
1. When importing an OpenApi 2.0 spec, add a toggle to decide whether I want to import the examples.
2. Bulk remove feature of examples in a collection

**Comment by Hamzablm** [comment]
@

**Comment by vedkribhu** [comment]
We do support bulk delete in examples. Just try bulk selecting the examples with (shift-click / cmd click) and (press del / right-click menu -> delete).
