### ISSUE TITLE
when i signed in to postman the ui is not updating in the postman desktop 

### ISSUE THREAD

**Issue by shiva-sandupatla** [a85/POSTMan-Chrome-Extension#11791]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

I have a newly installed postman, when I tried signing into the account, it redirects me to the browser and completes all the required steps, and redirects me back to the desktop app, my collections are displaying but the account icon not updating shown below.

### Steps To Reproduce

1. open postman
2. click sign in button complete the steps 
3. back to the postman desktop

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/47274553/222952302-0cf610c3-ecf4-4ef7-bba9-792874cece09.png)
![image](https://user-images.githubusercontent.com/47274553/222952317-6b94356c-3edb-4926-826a-38b1b379fbfc.png)

### Operating System

Windows

### Postman Version

10.11.1

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by postman-staff** [comment]
Hi @**shiva-sandupatla**
Thank you for contacting Postman Support.

I understand you cannot log in to the Desktop app as the login redirects fails. Right?
Happy to assist!

Do you happen to be on a workstation with security features (Firewall, VPN, Proxy, Gateway Rules, etc)? This might explain what is occurring, as we need access through such protocols.

Can you try disabling them and check if that affects anything?
I have added a doc below that can help with any firewall issues.
https://learning.postman.com/docs/getting-started/installation-and-updates/#using-postman-behind-a-firewall

Also, If possible can you check with your IT team and try if it would be possible to disable the rule or whitelist the Postman domains?

Let me know how it goes.
Looking forward to your response.

via @Lincimary | Postman Support

**Comment by shiva-sandupatla** [comment]
I have removed all the data folders related to Postman in the C://Users/<USER>/Postman and uninstalled postman. After reinstalling again it is working fine.

**Comment by postman-staff** [comment]
Glad that it works fine now.
Awesome, thanks for letting me know!

If you’re all set, that’s great. I will go ahead and mark this situation `Solved`.

Feel free to reach out again if you need anything else. We'd be more than happy to help.
Have a great day:)

via @Lincimary | Postman Support
