### ISSUE TITLE
EncodeURIComponent - Not working when selected via right click menu

### ISSUE THREAD

**Issue by LicenceGithub** [a85/POSTMan-Chrome-Extension#11798]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Currently running V 10.11.1-Ui230222-1424 - Desktop Platform 10.11.1

It appears the "EncodeURIComponent" when selected via the right click menu is no longer working. Previously, when I used this option you could visibly see the item you were encoding change value within the parameter box. Now this does nothing and the API call fails, so it doesn't appear to just be a visual bug.

If however I click within the paramter field, highlight the full text, then use the ellipses menu and click Encode URI from there it works fine. I can also see it visually changing the parameter value.

### Steps To Reproduce

1. Desktop app - Navigate to Parameter Tab
2. Highlight a value, right click
3. Select EncodeURIComponent

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/91877280/223687262-2bad3d27-59f5-4e1d-b5a2-707b7530e0ef.png)

### Operating System

Windows 11

### Postman Version

10.11.1

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by eekodeerder** [comment]
I have exactly the same issue.  How can I revert to a previous version?

**Comment by postman-staff** [comment]
Hello @LicenceGitHub,
Thank you for taking the time to bring this to our attention. We have engaged our Engineering Team in the investigation. We will keep you updated here once we have any feedback regarding this.

via @MirkaMir | Postman Support

**Comment by postman-staff** [comment]
Hello @LicenceGitHub,

Our Engineering Team has confirmed that this issue is caused by a Bug and is looking into it. We will keep you posted on the progress.

via @MirkaMir | Postman Support

**Comment by giridharvc7** [comment]
We've now fixed this with v10.13. Please give this a try and let us know what you think.

**Comment by LicenceGithub** [comment]
> We've now fixed this with v10.13. Please give this a try and let us know what you think.

Appears to be working again, thanks so much for the quick turnaround.
