### ISSUE TITLE
Unable to set advanced config when using graphQL with AWS Signature authorization

### ISSUE THREAD

**Issue by ashnap123** [a85/POSTMan-Chrome-Extension#11808]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

I am trying to access my graphQL API using AWS Signature authorizer. When using the GraphQL Request I am unable to set the advanced configuration which is causing an error.

![advanced_config](https://user-images.githubusercontent.com/16392756/224695687-99edec3c-8ffd-41f5-ab75-2d8f323f43d8.PNG)

If I try to access the same endpoint set up as regular http request I am able to set the advanced config for the AWS Signature and successfully call the API.

![advanced_config_http](https://user-images.githubusercontent.com/16392756/224696050-f6d1c433-d2a4-4393-85ed-e01c5bf31225.PNG)

### Steps To Reproduce

1. Open a new connection
2. Select GraphQL Request
3. Attempt to set the authorizer to AWS Signature

### Operating System

Windows

### Postman Version

v10.11.2

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by codenirvana** [comment]
@ashnap123 Thanks for reporting this. 

We've identified this issue, and the fix will be released this week with Postman v10.12.

**Comment by appurva21** [comment]
Hey @ashnap123! This issue is now fixed in the latest version of the Postman app (v10.12.0).
