### ISSUE TITLE
GraphQL Request (Beta) variable substitution not working in URL

### ISSUE THREAD

**Issue by joshuapetryk** [a85/POSTMan-Chrome-Extension#11803]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Introspection and queries fail when trying to use variables in the URL path for the new Graph QL requests (Beta).

### Steps To Reproduce

1. Add environment variable of Url = https://localhost:44329
2. Create new Graph QL Request (Beta)
3. Set Request URL to {{Url}}/graphql
4. Observe Introspection times out. (May or may not display error message)
5. Set Request URL to https://localhost:44329/graphql
6. Observe Introspection succeeds immediately

### Operating System

Windows 10

### Postman Version

10.11.2

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by SterlingChin** [comment]
This is a duplicate issue reported [here](https://github.com/postmanlabs/postman-app-support/issues/11765). We are actively working on a fix for this.
