### ISSUE TITLE
Update collection "info" object as a collection individual item

### ISSUE THREAD

**Issue by maticardenas** [a85/POSTMan-Chrome-Extension#11809]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

Currently, we use [collection individual items](https://www.postman.com/postman/workspace/postman-public-workspace/collection/5922408-fa7972ff-5df0-47b2-9bad-4070dbef520a?action=share&creator=6299013) endpoints as part of our automation process for performing updates in our public collection. 
We need to use them as, given our collection is structured in several folders with many requests, collection becomes to big to just perform few updates through the `PUT` endpoint (which takes 100+ seconds to update and throws several connection/timeout errors). 

This works well so far, but the issue we have now is that we want to perform also automated updates to our collection `name` or `description`, but I don't find a way to do so via the available endpoints. Basically, I can't find a way of updating the `info` object of a collection.

```
"info": {
            "_postman_id": "42468079-d6a1-4cf8-9e9f-6d7b1f3cc111",
            "name": "Sendcloud API",
            "description": "This collection can be used to quickly onboard/test our APIs.\n\nIt is automatically synced when there are changes made for our APIs.\n\nYou can find our requests following the same structure that we have at our public documentation: [https://api.sendcloud.dev/docs/sendcloud-public-api/](https://api.sendcloud.dev/docs/sendcloud-public-api/)",
            "schema": "https://schema.getpostman.com/json/collection/v2.1.0/collection.json",
            "updatedAt": "2022-12-01T11:38:49.000Z"
        }
```

### Describe the solution you'd like

A way of updating properties of collections `info` object in an isolated manner (either `PATCH` method, an additional endpoint or whichever way) as using `PUT` endpoint is not feasible when a collection grows in size.

**Comment by davidespihernandez** [comment]
Hi, @maticardenas!
We have added a PATCH endpoint on collections so you are able to update the name or the description of the collection, passing only these fields.
More information can be found here: https://www.postman.com/postman/workspace/postman-public-workspace/request/12959542-24607f03-453e-4936-b544-78d99e05cd19
Please let me know if you have any other problem.

**Comment by maticardenas** [comment]
Hi @davidespihernandez, I have tried and it works like a charm! thanks a lot!
