### ISSUE TITLE
Keep track and display users who perform API calls to Postman's API

### ISSUE THREAD

**Issue by cbautista1002** [a85/POSTMan-Chrome-Extension#11801]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

I would like to be able to see who on my team has executed API calls against the Postman API. Since we're limited to the number of API calls we can make in a month (based on our payment plan) I would like to see if there are outliers on my team (engineers who make many more calls to the Postman API than others).

### Describe the solution you'd like

1. An audit log of who's made which API calls
2. A summary which tells me how many API calls each team member has done

### Describe alternatives you've considered

I have no way of seeing who's made API calls, so I haven't tried any alternatives. I guess I can ask people on my team to keep track but that's not realistic.

**Comment by davidespihernandez** [comment]
Hi! 
You can retrieve the current usage of a Postman user (identified by a Postman API key) by using the [/me](https://www.postman.com/postman/workspace/postman-public-workspace/example/12959542-c29dcc78-e7c3-4cc5-9df1-afbf7f286bb1) endpoint in the Postman API. Notice this returns the usage for that API key.
If different people are using the same Postman API key, we don't have the possibility to distinguish them, as for the Postman API the users are the API key owners.
