### ISSUE TITLE
Cannot Execute Collections by Path with v1.1.0

### ISSUE THREAD

**Issue by frankgreco** [a85/POSTMan-Chrome-Extension#11802]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

```
❯ postman collection run postman/collection.json
/usr/local/bin/postman:413300
            throw new Error(`Unable to read API ID from ./postman/api.
                  ^

Error: Unable to read API ID from ./postman/api.
                Please ensure that the file exists and is readable.
    at Object.extractApiId (/usr/local/bin/postman:413300:19)
    at async /usr/local/bin/postman:470152:21
```

Works in `1.0.7`. Broken in `1.1.0`.

### Steps To Reproduce

1. Try to run a collection by path.

### Operating System

macOS

### Postman Version

1.1.0

### Postman Platform

Other

### User Account Type

Signed In User

### Additional Context?

This is an active production issue causing all builds to fail. How do I pin an older version!

**Comment by xk0der** [comment]
@frankgreco Thanks for reporting this. There was an issue with the latest Postman CLI version 1.1.0 - our team has reverted Postman CLI to the last stable version for now while we investigate the root-cause.

Re-installing by following the instructions here: [Installing the Postman CLI](https://learning.postman.com/docs/postman-cli/postman-cli-installation/) will get you back to the previous stable version and `collection run` will work fine again. 

Please log a new issue if you face any further issues with Postman CLI.
