### ISSUE TITLE
I dont see requests name on block 'send request v1'

### ISSUE THREAD

**Issue by arthurarkhipovoptimax** [a85/POSTMan-Chrome-Extension#11810]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

In all Flows, which contains block 'send request v1' i dont see which request is it.
![image](https://user-images.githubusercontent.com/123624046/224736100-40c558ed-a39c-4a11-b90b-ce8885f664a8.png)

### Steps To Reproduce

1. Open flow with block  'send request v1'
2. Check it

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/123624046/224737150-4a01faee-1393-48a3-98aa-855d19102a46.png)

### Operating System

Linux

### Postman Version

10.11.2

### Postman Platform

Both

### User Account Type

Signed In User

**Comment by SterlingChin** [comment]
Can you please update to the latest version of Postman (`v10.12.5`) and let us know if you're still seeing this issue?
