### ISSUE TITLE
Curl: Add the -L (Follow Redirects) if the 'Automatically follow redirects' setting is enabled

### ISSUE THREAD

**Issue by lewisdavidcole** [a85/POSTMan-Chrome-Extension#1181]
I have the 'Automatically follow redirects' setting set to 'Yes'.
However the curl generated command is lacking the -L option and has to be manually added.

**Comment by shreys7** [comment]
Hey @lewisdavidcole Can you try this in Postman 7.2.1, with the 'Experimental Codegen Mode' flag enabled in Postman's global settings? We've introduced bug-fixes, support for two new languages (JS-Fetch and Powershell), and the ability to configure certain aspects of the generated snippet.

For this particular use-case, there's a separate curl-level 'Follow Redirects' setting, which you can control once you've selected cURL in the language selector.
