### ISSUE TITLE
Postman code snippet generator exposes secret values

### ISSUE THREAD

**Issue by bond-** [a85/POSTMan-Chrome-Extension#11811]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Related to #10650 

If you can embed a button like `show secrets` or something, we can deliberately press to view the secrets, that would help.

### Steps To Reproduce

1. Create a secret variable in a postman environment.
2. Create a request that uses these values.
3. Click on the code button, and all secrets are visible.

### Screenshots or Videos

![rest-request](https://user-images.githubusercontent.com/776647/224743041-6068edc2-c8dc-4765-bf57-f7cb0f40a039.png)
![curl-snip](https://user-images.githubusercontent.com/776647/224743079-02ed9e12-3e90-447e-b080-c578e7cf1c2f.jpg)

### Operating System

Windows

### Postman Version

10.11.1

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by dhwaneetbhatt** [comment]
@bond- thanks for reporting this issue. We will look into it and push updates on this thread.

**Comment by matt-daugherty-dockwa** [comment]
I ran into the same issue, thank you for reporting!

**Comment by dhwaneetbhatt** [comment]
We have fixed this issue in the latest version (v10.14) of Postman. Secret variables are now masked in the code editor.
![Screenshot 2023-05-16 at 15 18 40](https://github.com/postmanlabs/postman-app-support/assets/3478831/2e2cd00e-a66d-45de-9a2d-0cf78e6636cd)
![Screenshot 2023-05-16 at 15 17 38](https://github.com/postmanlabs/postman-app-support/assets/3478831/ab0b895f-bbe1-4fb6-8bde-3546cdba2082)
