### ISSUE TITLE
Generate collection from definition does not work

### ISSUE THREAD

**Issue by adriangarrote** [a85/POSTMan-Chrome-Extension#11827]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

When adding a new API (graphql), and adding its definition, I clicked to "Generate collection from definition". 
It is apparently generating this, as it display a loading icon, but nothing happen. 
I have been waiting for hours and triggering with different approached but nothing is generated. 

<img width="330" alt="image" src="https://user-images.githubusercontent.com/30629328/225864160-64e6aff1-1cef-4667-b217-5bc8c26a445a.png">

### Steps To Reproduce

1. Create new API
2. Add Graphql Definition
3. Add a new collection -> Generate collection from definition

### Screenshots or Videos

<img width="330" alt="image" src="https://user-images.githubusercontent.com/30629328/225864472-30667b9c-5e15-46fc-a389-c0d5d1eb5d7f.png">

### Operating System

macOS

### Postman Version

10.12

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by dhwaneetbhatt** [comment]
Thanks for reporting @adriangarrote. Could you please share your GraphQL schema file here? If it is a private file you could send it to help@postman.com (please mention this GitHub issue in the email).

**Comment by undertakingyou** [comment]
I have the same issue. I am using Postman 10.24.11.

I can generate the collection when I use the SpaceX publicly available graph found here: https://studio.apollographql.com/public/SpaceX-pxxbxen/variant/current/schema/sdl.

When I use the scheme SDL generated by my app it hangs as described by @adriangarrote. This is a recent phenomena, as I have following the steps noted above many times and been able to generate the collection from the definition previously. Further, the schema seems to work fine as I import the same schema into Altair GraphQL Client and it works as expected.

I will email my schema definition file.

**Comment by VShingala** [comment]
@adriangarrote @undertakingyou We have fixed this issue. Could you try generating collection again and let us know if your issue persists?

**Comment by undertakingyou** [comment]
Confirmed that I am able to generate now, thank you.
