### ISSUE TITLE
Urls in Link header still underlined and clickable, but don't generate new request to url in 3.0.

### ISSUE THREAD

**Issue by ngbrown** [a85/POSTMan-Chrome-Extension#1182]
When the headers of a response contained the Link header, pre 3.0 had the ability to click on the linked urls.  In 3.0, the links are still colored and underlined when hovered on, but clicking does not have the expected effect of generating a new request like clicking a url in the body does.

> Link → 
> Link
> Used to express a typed relationship with another resource, where the relation type is defined by RFC 5988
> http://localhost/api/v1/tests?per_page=25&page=2;rel="next",http://localhost/api/v1/tests?per_page=25&page=1;rel="first",http://localhost/api/v1/tests?per_page=25&page=27;rel="last"

**Comment by abhijitkane** [comment]
Ah..that was your pull-request that we merged. We'll re-add this in the next release. 

Thanks for pointing this out, and the original pull-request, of course :)

**Comment by abhijitkane** [comment]
@ngbrown Can you confirm the fix in v3.0.4?
