### ISSUE TITLE
click 'open workspace overview', no response

### ISSUE THREAD

**Issue by stoneLee81** [a85/POSTMan-Chrome-Extension#11832]
### Is there an existing issue for this?

- [ ] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

<img width="978" alt="image" src="https://user-images.githubusercontent.com/18001708/226114097-7a8ddf3e-c500-41f0-b40c-1792e6d9f10f.png">

### Steps To Reproduce

1 open postman
2 choose workspaces
3 click 'open workspace overview'
4 no response

### Screenshots or Videos

null

### Operating System

macOS  Ventura 13.0

### Postman Version

Version 10.11.2

### Postman Platform

Postman App

### User Account Type

Signed In User

### Additional Context?

null

**Comment by akshay-kulkarni-03** [comment]
Hi @stoneLee81 , we were not able to reproduce this issue on the app version specified by you above. Can you send us all the details about this issue along with app logs on help@postman.com? This will help us debug this issue further.
