### ISSUE TITLE
50% of the items are disabled in the "Create New" modal due to missing permissions

### ISSUE THREAD

**Issue by hampuskraft** [a85/POSTMan-Chrome-Extension#11830]
[Deleted for privacy reasons]

**Comment by hampuskraft** [comment]
I can create a new WebSocket request etc., as long as I reload the app and quickly press the button before you arbitrarily disable it.

**Comment by akshay-kulkarni-03** [comment]
Hi @hampuskraft , we identified the issue and working on fixing it. Will update this thread once the issue is fixed.

**Comment by akshay-kulkarni-03** [comment]
Hi @hampuskraft , we have fixed this issue please update your app version and you should not longer be facing this problem.

**Comment by hampuskraft** [comment]
Thanks!
