### ISSUE TITLE
Postman does not sync web and desktop forks 

### ISSUE THREAD

**Issue by Nikita-Filonov** [a85/POSTMan-Chrome-Extension#11839]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Postman does not sync web and desktop forks in workspace

### Steps To Reproduce

Steps

1. Open web Postman
2. Fork some repo
3. Invite team member into your workspace
4. If team member opens web version, then he can see forked collections, if team member opens desktop - **he can not see any forked collections**

### Screenshots or Videos

**The web version**
![image](https://user-images.githubusercontent.com/63447343/226821782-04bfda83-30b1-4172-a93f-2e3112f6fc98.png)

**Where is other repos? They does not get fetched**
![image](https://user-images.githubusercontent.com/63447343/226821913-8063c89a-44e0-4521-a8a9-ea3dc3e28442.png)

### Operating System

Windows

### Postman Version

latest

### Postman Platform

Both

### User Account Type

Signed In User

**Comment by preethammavin** [comment]
@Nikita-Filonov looks like the desktop application is an old and deprecated version. Can you update to the latest version and verify? 

You are not viewing it as the deprecated versions do not support all collections which are created in the newer versions

**Comment by Nikita-Filonov** [comment]
@preethammavin Sure, after updating postman to latest version, everything works fine!
Thank you a lot
