### ISSUE TITLE
Where is preview mode in Postman 3.0?

### ISSUE THREAD

**Issue by who** [a85/POSTMan-Chrome-Extension#1183]
One of the most useful features was was the ability to view the request as curl, in preview mode.  With Postman 3.0, this appears to be gone. Am I correct, or is it hiding somewhere?

**Comment by abhijitkane** [comment]
There's a '< >' button below the Send button. This lets you generate code in a number of languages, and includes raw HTTP and CURL as options.

**Comment by yaowenqiang** [comment]
It's a little hard to find.
