### ISSUE TITLE
Italics in description are being rendered without spaces

### ISSUE THREAD

**Issue by DLTKMonBlaza** [a85/POSTMan-Chrome-Extension#11831]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

For some unknown reason, when markdown text in italics for a documentation in Postman gets published, the spaces are removed.

### Steps To Reproduce

From the editor...
![image](https://user-images.githubusercontent.com/53828568/226070792-e45a802f-ba37-4e2b-a69a-5a0167d1e253.png)

When published...
![image](https://user-images.githubusercontent.com/53828568/226070897-8302c04b-8df3-4613-8220-551cb281170f.png)

### Operating System

Windows

### Postman Version

10.11.1

### Postman Platform

Both

### User Account Type

Signed In User

**Comment by ankitjaggi** [comment]
@Mon-Blaza This issue has been resolved with the latest release. Feel free to reopen the ticket if you still face any problems.
