### ISSUE TITLE
Nested folders within a collection for APIs connected with GitHub do not work

### ISSUE THREAD

**Issue by SatishReddyBethi** [a85/POSTMan-Chrome-Extension#11848]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

I have an API that is connected to my GitHub repo for version control. If I create a collection, then create folder A, then create folder B inside folder A, the folder B is completely unresponsive. 
- I cannot add any requests to folder B
- I cannot move requests into folder B
- I cannot delete folder B
- I cannot delete the collection containing folder B 

### Steps To Reproduce

1. Open APIs tab from the side bar
2. Create new API
3. Connect it to a GitHub repo
4. Add a new collection to the API you just created
5. Create a folder called "folder A" inside the above collection
6. Create a folder called "folder B" inside the above folder A
7. Try to add a request to the folder B

### Screenshots or Videos

<img width="280" alt="image" src="https://user-images.githubusercontent.com/43217754/227052578-0eb48f35-5cec-4e45-bae3-d0cd18053f4d.png">

### Operating System

Windows

### Postman Version

10.12.5

### Postman Platform

Both

### User Account Type

Signed In User

**Comment by shashankawasthi88** [comment]
@SatishReddyBethi thanks for raising this. The team is looking at this on priority.

**Comment by jatin3893** [comment]
Hi @SatishReddyBethi,

This issue is now fixed in the latest release `10.12.7`.
Please do let us know if you still face any issues.

**Comment by SatishReddyBethi** [comment]
The issue got fixed in `10.12.7`. Thank you for the quick response.
