### ISSUE TITLE
setting new value to variable in pre-request does not take effect

### ISSUE THREAD

**Issue by m3dbedb** [a85/POSTMan-Chrome-Extension#11840]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

I need to update customer_id before request would be done.
Variable update does not take effect on pre-request tab.

### Steps To Reproduce

1. Add global variable "customer_id=1"
2. Create a request as listed above:
pre-request tab:
pm.globals.set(pm.globals.get('customer_id')+1);
request: GET http://api.url:8888/api/listcustomer/{{customer_id}}
3. Server return data on customer_id = 1
4. Global variable still contains customer_id = 1
5. customer_id was not updated and request was done with outdated value (1)

### Operating System

windows

### Postman Version

8.6.0

### Postman Platform

Postman App

### User Account Type

Signed Out User

**Comment by VaishnaviChallaPostman** [comment]
Hey @m3dbedb 👋 
It looks like the syntax used to set the global variable is missing the target global variable key. 
The syntax is: `pm.globals.set("variable_key", "variable_value");`
So in your case, it should be something like: `pm.globals.set("customer_id",pm.globals.get('customer_id')+1);`
I hope this helps. Please feel free to re-open if you are still facing any issues 🙌
