### ISSUE TITLE
There is a typo on OAuth 2.0 Authorization pop-up

### ISSUE THREAD

**Issue by kocaturko** [a85/POSTMan-Chrome-Extension#11842]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

While getting an access token for OAuth 2.0 authorization, there is a typo in the message on the "Get new access token" pop-up.

**Actual Result:**
The message is as below:

This dialog box will automatically close once the auth callback is received. Make sure your browser is’t blocking pop-up windows.

**Expected Result:**
The message should be as below:

This dialog box will automatically close once the auth callback is received. Make sure your browser **isn’t** blocking pop-up windows.

### Steps To Reproduce

1. Select the type of the authorization as OAuth 2.0 on the Authorization tab.
2. Fill all required fields for the configuration of the token and click on Get New Acess Token button.
3. Complete the sign in process according to your token configuration.
4. Observe the authorization pop-up.

### Screenshots or Videos

<img width="880" alt="Screenshot 2023-03-22 at 14 07 52" src="https://user-images.githubusercontent.com/33998703/226916508-281c7463-92c0-495d-b36c-33ea2e837fff.png">

### Operating System

macOS

### Postman Version

Version 10.11.1 (10.11.1)

### Postman Platform

Postman App

### User Account Type

Signed Out User

**Comment by VaishnaviChallaPostman** [comment]
Hey @kocaturko 
This is fixed now.
![image](https://github.com/postmanlabs/postman-app-support/assets/76939396/a4c82101-284b-4c24-b485-ada3c53526a3)
Please feel free to re-open if you are still seeing this issue.
