### ISSUE TITLE
New Postman moves 'Send' to far side of window.

### ISSUE THREAD

**Issue by MerlinGuy** [a85/POSTMan-Chrome-Extension#1185]
The previous version of Postman had the 'Send' button on the left side of the detail pane. This allowed the user to select a curl command, move the mouse a short distance, and then send with another mouse click.  The new location of the 'Send' button means the user has to move their mouse from one side of the application to the other each time they wish to execute a different command.  I can execute the curl by hitting the 'Enter' key but this means I need to take my hand off the mouse.  Very, very inefficient.  Poor UI design.

Is there anyway to move the 'Send' button back to the left side of the pane?

Thanks,

Jeff

**Comment by a85** [comment]
Unfortunately no. The problem with the existing Send button was that it would jump up/down with the rest of the interface. With large request bodies, this would be a huge pain. You can use the 'Enter' or 'Cmd+Enter' shortcuts if moving the mouse to the edge is a pain.
