### ISSUE TITLE
Button "Run in Postman" does not work

### ISSUE THREAD

**Issue by antoniooptiply** [a85/POSTMan-Chrome-Extension#11859]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

When using the button, and then choosing to open in Web or on Postman Mac app, the import returns an error,not importing anything at all. See attachment.

### Steps To Reproduce

1. open a page that has the button "Run in Postman"
2. choose web of macOs app
3. the import returns an error

### Screenshots or Videos

![Screenshot 2023-03-27 at 08 41 52](https://user-images.githubusercontent.com/126565892/227886929-d5045e1a-d53d-4d79-90cd-caee15503dcb.png)

### Operating System

macOs

### Postman Version

10.12.4

### Postman Platform

Both

### User Account Type

Signed In User

**Comment by gitThingsDone** [comment]
@antoniooptiply thanks for reporting this; we have deployed a fix, and collection imports now succeed for [Optiply API](https://api-documentation.optiply.com/). However, the environment import still fails; we are working on fixing this.
Meanwhile, you can try copying your existing environment variables to collection variables instead (check out https://youtu.be/EKv6n-jY9lU?t=35)
This will help unblock your API consumers. Moreover, they will no longer need to worry about selecting the right environment to resolve variables and send requests.

**Comment by abhinav-ravi** [comment]
Thank you for your patience @antoniooptiply. We have pushed a fix for the issue. You should be able to import the collection + environment using the `Run in Postman` button

**Comment by abhinav-ravi** [comment]
@antoniooptiply can you please confirm if this worked for you?

**Comment by antoniooptiply** [comment]
Hi, this worked. thanks. closing the ticket
