### ISSUE TITLE
After access token is received, getting Session expired or invalid while doing POST for Attachment Object in Salesforce

### ISSUE THREAD

**Issue by saurabhjhajohnlewis** [a85/POSTMan-Chrome-Extension#11852]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

We have a Json file that we import into POSTMAN.
For getting access token, we send POST request /services/oauth2/token and token access token is generated successfully.
While trying to upload a file for POST operation on /services/data/v45.0/sobjects/Supplier, we get "Session expired or Invalid".
401Unauthorized
![image](https://user-images.githubusercontent.com/128808145/227513496-c5e1f36d-47f3-4b9a-bf43-f0b55a171187.png)
![image](https://user-images.githubusercontent.com/128808145/227513610-2a912d25-3c96-4b23-ab29-342d095b28e2.png)

### Steps To Reproduce

1. Import Json file into Postman that has suppliers collection and structure of our files. 
2. First file is configuration details, where we provide client Id, secret, grant type, username, password.
3. POST on https://test.salesforce.com/services/oauth2/token to get access token.
4. Once token is received, we upload file in File Upload section in our file structure. 
5.We get invalid session expired error. 401
![image](https://user-images.githubusercontent.com/128808145/227515932-0672dc09-ca3b-4324-8bab-3f96915ed84d.png)

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/128808145/227516151-c6ced803-09dc-4523-ad0f-5df2f7c99d71.png)

### Operating System

Windows

### Postman Version

10.12.0

### Postman Platform

Postman App

### User Account Type

Signed Out User

**Comment by giridharvc7** [comment]
@saurabhjhajohnlewis This might be because your token is expired. 
Have you tried using Postman's OAuth authentication?

**Comment by saurabhjhajohnlewis** [comment]
Hi @giridharvc7, I tried getting token from OAuth 2.0, I got the token, tried retrieving some case(Object) details with token generated, I got the details.
But, now I want to make POST request on /services/data/v45.0/sobjects/Supplier__c using file upload by giving file in body. 
I get error as INVALID_MULTIPART_REQUEST
![image](https://user-images.githubusercontent.com/128808145/231129723-b059f540-b224-4c6b-b4da-530dfdbc4bce.png)

**Comment by giridharvc7** [comment]
The error code 400 here probably denotes that this is not an Auth-level issue. 
I'm not fully aware of this API, but from the error message, i can tell that the request body is malformed. 
I'm closing this issue as it might not related to Postman. Feel free to re-open it in case it is.
