### ISSUE TITLE
Account creation with existing username or user email does not generate any warning

### ISSUE THREAD

**Issue by tarikkranda** [a85/POSTMan-Chrome-Extension#11856]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

On web user interface creating a new account with existing username or user email does not show any warning (information) to notify user about already existing account. Page looks like stuck with no sign of activity. 

### Steps To Reproduce

On web user interface creating a new account with existing username or user email does not show any warning (information) to notify user about already existing account. Page looks like stuck with no sign of activity. This is tested on Chrome and Firefox latest versions. I had forgot my account in past, this was causing me to generate a new account unnecessarily in the system.

This may be done intentionally for a security reason for not to disclose any information about existing accounts but it would be good to see at least an email notification in the inbox of existing user hence the user understands about already existence of account and does not tend to create a new user. This can decrease waste of time and garbage duplicate users from the same individuals.

### Operating System

windowss

### Postman Version

9.14.0

### Postman Platform

Postman Web

### User Account Type

Signed Out User

**Comment by ArjunSingh-PM** [comment]
Hi @tarikkranda! Thanks for reaching out to us. 

If you try to create an account with an existing email or username, you should see the following inline errors. Are these not showing up for you?

<img width="692" alt="Create account with exisitng username" src="https://user-images.githubusercontent.com/53265429/230916752-2f14e3a6-1723-4884-9b1e-b53802a1910c.png">
<img width="664" alt="Create account with existing email " src="https://user-images.githubusercontent.com/53265429/230916766-dc3b32e2-8cf0-404a-b5aa-84dc004d18f8.png">

**Comment by tarikkranda** [comment]
Hello @ArjunSingh-PM,

Sorry, I missed your previous message. 
Yes it works as expected now. Thank you!
