### ISSUE TITLE
New collection import workflow lost ability to replace vs copy

### ISSUE THREAD

**Issue by byrdman** [a85/POSTMan-Chrome-Extension#11862]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

When importing multiple collections at one time we've lost the ability to tell postman to replace all vs create copies of all.  Importing a single collection still gives this option.

### Steps To Reproduce

Click the import button
Click the files link
Select 2 or more collections to import
Click through, and let the import happen
You now have the original collection plus a copy.

### Operating System

Windows

### Postman Version

10.12.8

### Postman Platform

Postman App

### User Account Type

Signed In User

### Additional Context?

This is a regression from previous behavior (and single import still has this behavior.

**Comment by akshaydeo** [comment]
Hi @byrdman, thanks for reporting this issue. We are working on a fix, I will keep this issue updated 🙇‍♂️

**Comment by dhwaneetbhatt** [comment]
Hi @byrdman, we've fixed this issue in version 10.13 of Postman.

**Comment by byrdman** [comment]
Still broken at 10.13.1

**Comment by byrdman** [comment]
I can confirm that it is indeed fixed at 10.13.1
