### ISSUE TITLE
Saved Response not showing in UI

### ISSUE THREAD

**Issue by ekor15** [a85/POSTMan-Chrome-Extension#1186]
cannot see saved responses.
when exporting the collection I can see that it exists.

**Comment by seldauyanik** [comment]
Same problem

**Comment by gustavohenke** [comment]
:+1:, also facing this problem after updating to v3.

**Comment by abhijitkane** [comment]
We'll be pushing a fix for this today.

For now, you can see the responses by adding a description to the parent request (Edit request > Description)

**Comment by abhijitkane** [comment]
@gustavohenke @ekor15 @seldauyanik Can you confirm the fix in v3.0.4?

**Comment by seldauyanik** [comment]
Fixed.  
Prior saved responses can be seen, new save operations can be performed
Thanks

**Comment by seldauyanik** [comment]
Thanks
