### ISSUE TITLE
Test results not the same between CLI and Run Collection

### ISSUE THREAD

**Issue by antoniooptiply** [a85/POSTMan-Chrome-Extension#11869]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Hi, when running a collection via Postman and then running the same collection with CLI we have failed tests on the last that we don't have on the first. With CLI the tests fail with an AssertionError _expected '3' to deeply equal 3_.
Running the same collection (same test scripts) from Postman those fails don't exist.
Thanks,
António Lagartixo

### Steps To Reproduce

1. Run a collection on Postman where there are test to compare two values
2. Run the same collection but with CLI
3. With CLI the tests failed with: AssertionError _expected '3' to deeply equal 3_ where the same test don't fail with the Postman Runner

### Operating System

macOs and Win10

### Postman Version

10.12.9

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by VaishnaviChallaPostman** [comment]
Hey @antoniooptiply 👋 
I have tried replicating the behaviour mentioned but was unable to.
I see the test pass both in the UI and CLI. 
<img width="1336" alt="Screenshot 2023-03-30 at 2 45 55 PM" src="https://user-images.githubusercontent.com/76939396/228790304-5b674e55-de11-4297-9c0a-60a5dd1fe23d.png">
<img width="904" alt="Screenshot 2023-03-30 at 2 45 13 PM" src="https://user-images.githubusercontent.com/76939396/228791051-90cbb182-4a9b-4d55-9cb5-521d2e176de1.png">

Could you please elaborate more on your test script?

**Comment by antoniooptiply** [comment]
Hi, thanks for taking a look at this.

This is related to a collection that have several request.
On one of the requests we save as a collectionVariable the number of times an attribute occurs in the response:

Let’s say the value is 3.

On a next request we do the same but from a different call.
Then we check if values are the same.


This works. The thing here is that if we run this collection from CLI we have those failed tests (51) but with the Runner we get just 1 error. Again, same collection, and same data.


Detail from Failed from Postman CLI



Antonio Lagartixo
Optiply

**Comment by VaishnaviChallaPostman** [comment]
@antoniooptiply, Thanks for your response!! 
I have tried doing the same, but unfortunately still not able to replicate :( 
Here is the screen recording of what I tried: 
https://user-images.githubusercontent.com/76939396/228811929-18fdff80-1666-41e1-b96f-9cc80779119d.mov

Looking at the error, `AssertionError expected '3' to deeply equal 3`, it looks like the data types of the two values you are comparing aren't matching. We would need to take a look at how you are setting these values and where they are coming from.
If possible, could you please submit a ticket[ here](https://support.postman.com/hc/en-us/requests/new) and share your collection with us(after redacting any sensitive data) to help us take a look at the test scripts and check more on what is going south in your case?
Note: Mentioning this GH thread ID(11869) in the subject if raised would be really helpful for us to locate your ticket 🙌 
Thanks!

**Comment by VaishnaviChallaPostman** [comment]
Hey @antoniooptiply, May I know if you are still facing any issues?
If yes, please submit a ticket[ here](https://support.postman.com/hc/en-us/requests/new) and share the requested details.

**Comment by antoniooptiply** [comment]
no thanks, closing this ticket
