### ISSUE TITLE
Add a collapse-all button in collections view

### ISSUE THREAD

**Issue by pansharm-ms** [a85/POSTMan-Chrome-Extension#11866]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

The problem right now is if we open multiple APIs from different collections the view seems quite chaotic, and we have to minimize the collections' view one by one.
Can you please add a collapse all button (beside + create collection button) so that all the APIs are minimized and we see a clean view again.

### Describe the solution you'd like

The problem right now is if we open multiple APIs from different collections the view seems quite chaotic, and we have to minimize the collections' view one by one.
Can you please add a collapse all button (beside + create collection button) so that all the APIs are minimized and we see a clean view again.

**Comment by giridharvc7** [comment]
Thank you for your patience, We've introduced this feature in v10.13. You can now use `Option+Click` to expand and collapse all children of an element. This work for collections and folders.

https://user-images.githubusercontent.com/1040583/232968843-ecd9e63c-3d65-4bee-ae12-fba2dd55107e.mov
