### ISSUE TITLE
UI size in settings always makes everything bigger.

### ISSUE THREAD

**Issue by selfish** [a85/POSTMan-Chrome-Extension#1187]
When changing the value, even after an app restart, UI Size box will always make everything appear MUCH larger.
This happens regardless of the size selected. Default works.

Version 3.0.0.10 (packaged)
OS: win
Architecture: x86-32
Native client architecture: x86-64
[Chrome 42, windows 7 x64]

**Comment by codeb2cc** [comment]
+1 in OS X Yosemite 10.10.3 with Chrome 43.0.2357.130 (64-bit)

**Comment by abhijitkane** [comment]
Can you update to v3.0.1 of Postman and see if you still face the issue?

chrome:/extensions > Developer Mode > Update extensions now.

**Comment by selfish** [comment]
Looking sharp.
Thanks for the prompt action!
