### ISSUE TITLE
postman not open

### ISSUE THREAD

**Issue by Ekremalpozmen** [a85/POSTMan-Chrome-Extension#11878]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Something Went Wrong
Postman has encountered an error. If this problem persists, contact us at help@postman.com

### Steps To Reproduce

Something Went Wrong
Postman has encountered an error. If this problem persists, contact us at help@postman.com

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/62023846/229076819-23ede03f-0bca-410b-8719-6ac5cb750d1f.png)

### Operating System

windows 10

### Postman Version

1.1.1

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by postman-staff** [comment]
Hello @Ekremalpozmen,

To try to resolve the error, remove the Local Postman data as explained in our help article here: How to remove local data.

Once you have removed (or renamed) the local and roaming Postman folders, please reinstall the latest Postman desktop app from here: https://www.postman.com/downloads/.

If the above doesn't resolve the issue, submit a ticket using the support form: https://www.postman.com/support/ and add the GitHub reference to the header and the desktop app logs.

via @MirkaMir | Postman Support

**Comment by postman-staff** [comment]
@Ekremalpozmen, re-adding the help article link for removing the local data: https://support.postman.com/hc/en-us/articles/4410785125271-How-to-remove-local-data.

via @MirkaMir | Postman Support

**Comment by Ekremalpozmen** [comment]
@postman-staff  Thanks my problem is solved

**Comment by postman-staff** [comment]
@Ekremalpozmen, Great to hear!

via @MirkaMir | Postman Support
