### ISSUE TITLE
Issue switching account in App

### ISSUE THREAD

**Issue by denis-leveque-idnow** [a85/POSTMan-Chrome-Extension#11889]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

I have an individual and a "Teams" account.
On Linux App, if i try to switch account, it opens a window in browser, and the App is waiting for authentication on browser side.
But on browser side, when i choose my other account, it logs in into the browser, and nothing happens in the App, it just waits indefinitely.
At this moment, if I quit the app (file > quit), the app closes but the processes still run and the app won't start again until i kill the processes in command-line.

### Steps To Reproduce

Having 2 accounts:
- Launch Linux App.
- Log in.
- Switch account.
- On browser, log in.
- > here, it should launch Postman in browser and app should be waiting.

### Operating System

Linux (debian 11)

### Postman Version

10.12.10

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by ArjunSingh-PM** [comment]
Hi @denis-leveque-idnow, thanks for reporting this issue. We are actively working to resolve the same. 

For now, can you log out of this account from the browser and login in again, and then try to sign in from the app? Please share if this resolves the issue for you. Thanks!

**Comment by denis-leveque-idnow** [comment]
Hi, thanks for the feedback. It works when loging out from all accounts from web and app and re loging in from app.
