### ISSUE TITLE
postman/chrome crash when trying to choose a file to upload

### ISSUE THREAD

**Issue by bandtank** [a85/POSTMan-Chrome-Extension#1188]
When I try to choose a file, Postman crashes (and also crashes the whole Chrome process) when I click the "Choose Files" button. I saw another bug that had to do with a crash after selecting a file, but I can't even get to that point. Simply clicking the button causes the crash without ever seeing a dialog box. The crash takes 3-4 seconds and the button stays depressed during that time.

I'm using Chrome version 43.0.2357.130 (64-bit) on OSX 10.10.3.

**Comment by a85** [comment]
That's weird. What's the size of the file that you are uploading?

**Comment by nturnley** [comment]
I am seeing this same behavior, the file is ~ 100MB,
I am using Postman desktop app:
Version 3.1.5 (packaged)
OS: win
Architecture: x86-32
Native client architecture: x86-64

Please fix! it is blocking so many operations.

**Comment by shamasis** [comment]
seems like in Postman v4.5+ the app does not crash when uploading large files in form-data mode. The binary mode is still crashing though.
