### ISSUE TITLE
Postman Flows: Youtube Output block stating "this content is blocked. Contact site owner to fix the issue"

### ISSUE THREAD

**Issue by askherconsulting** [a85/POSTMan-Chrome-Extension#11894]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

I am unable to pass a youtube video URL in as a string to an output block with YouTube format and get the block to play the expected video.

### Steps To Reproduce

1. create a string block in Flows
2. add in the string of a Postman video e.g. https://www.youtube.com/watch?v=QYqA1VAoyIA 
3. attach the string block to an output block
4. change the output block type to Youtube
5. play the flow

expected:
Should show video

actual:
shows error message as per title

### Operating System

Windows

### Postman Version

10.12.10

### Postman Platform

Postman App

### User Account Type

Signed In User

### Additional Context?

The flow is a set I made for instructional purposes and can be found here:

https://www.postman.com/beth-marshalls-team/workspace/postman-flows-basic-examples/overview 

See flow 9.

**Comment by romulo-nascimento** [comment]
Hi @askherconsulting.

Thanks for reporting that issue. It should be fixed now.
Please let us know in case you face any other problems.

**Comment by askherconsulting** [comment]
Hey Romulo - Its working perfectly now, thanks so much for fixing so quickly!
