### ISSUE TITLE
After importing a curl, Postman is bricked. "Something went wrong" - even after restart

### ISSUE THREAD

**Issue by RonSijm** [a85/POSTMan-Chrome-Extension#11908]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

I already posted this on the community forum, but figured to crosspost it here, if this is where you're keeping track of bugs:

https://community.postman.com/t/postman-crashes-at-startup-and-cannot-get-it-to-un-crash-without-losing-all-my-collections/46204

### Steps To Reproduce

- Go to %appdata%
- Delete or Rename Postman
- Open postman again, now new data is created.
- Click Skip login, go to app
- Click Import
- Click Raw Text
- Paste the following:
- Click import

````
curl --request POST \
  --url 'https://x' \
  --header 'Authorization: Basic x' \
  --header 'Accept: application/json' \
  --header 'Content-Type: application/x-www-form-urlencoded' \
  --data 'grant_type=client_credentials&scope=x' | jq
````

Note: maybe not everything is relevant in this cUrl, I don't know exactly why it's crashing, but after is crashes all that's available is a screen saying "Something went wrong". 

Deleting %appdata%\postman solves it, but I don't want to delete all my postman settings and collections

### Operating System

Windows 11

### Postman Version

10.12.13

### Postman Platform

Postman App

### User Account Type

Signed In User

### Additional Context?

Postman for Windows
Version 10.12.13
UI Version 10.12.13-ui-230411-0412
Desktop Platform Version 10.12.13
Architecture x64
OS Platform win32 10.0.22621

Edit: I assume there is something wrong with the curl itself, (a colleague send it to me) - but expected behavior would be for postman to throw an error about it - or only import the parts that it can import.   
Not totally brick itself

**Comment by VShingala** [comment]
@RonSijm Thanks for reporting the issue! We were able to reproduce this issue and we're working on fixing it. We should have the fix ready for this with the upcoming release. I'll add more info here once the fix is available.

**Comment by RonSijm** [comment]
Thanks. After some testing I was also able to fix it myself by deleting `%appdata%\Postman\window`

That allowed me back into postman.

**Comment by arlemi** [comment]
This was fixed in the latest version of Postman (v10.13), please update the app and let us know if you're still seeing the issue!

**Comment by cesarvspr** [comment]
When I paste a curl request (a small one) postman freezes. 11.12.0
<img width="1399" alt="image" src="https://github.com/user-attachments/assets/65442ea5-a2d3-4d35-bd74-ebab0bcbd33c">

**Comment by DSchau** [comment]
@cesarvspr can you provide a reproduction? Specifically what would help is the exact cURL command you're using that causes the issue to replicate.

If there's sensitive details you can feel free to obfuscate them or try and share something that replicates the issue that is less sensitive.

**Comment by cesarvspr** [comment]
@DSchau For some reason it's working again. But it was breaking for literary every curl, even the smaller ones. Maybe it was a local issue.
