### ISSUE TITLE
Local variable names instead of values are displayed in the Code snippet after running the request

### ISSUE THREAD

**Issue by Mike-Soft** [a85/POSTMan-Chrome-Extension#11907]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

There was already same issue that was closed without resolution and needs to be reported again:
https://github.com/postmanlabs/postman-app-support/issues/10258

Code snippet is not showing the local variable value that was used in body.

It is impossible to just copy it for any documentation or debugging reasons because of that. 

### Steps To Reproduce

1. Open request.
2. Click on Pre-request Script
3. Declare some variable, for example: pm.variable.set("code", "100")
4. Use the variable "code" in the body.
5. Run the request.
6. Open Code snippet.
7. Verify the "Code" value.

Expected Result: Code value should be displayed.

Actual Result: Variable name is displayed instead of value.

### Screenshots or Videos

This is a screen shot of an issue. After creating a local variable named "country" you can see that code snippet on the top right is showing only variable name. 
I also logged a request body in Pre-req and Test and the result from the console is on the bottom right. As it is understandable the Pre-req script might not have the value of the var I would expect the code snippet to contain the value of the variable as in the logged request body from the tests part

<img width="719" alt="postmanissue" src="https://user-images.githubusercontent.com/49808920/231142230-ae6a662a-2c27-4478-9453-cf7c39e79b90.png">

### Operating System

Windows

### Postman Version

v10.12.13

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by aman-v-singh** [comment]
This is fixed.
