### ISSUE TITLE
How to confirm Postman CLI version is current? 

### ISSUE THREAD

**Issue by robertmryan** [a85/POSTMan-Chrome-Extension#11900]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

I have no way of knowing whether my Postman CLI install is up to date.

### Describe the solution you'd like

I understand [how to install](https://learning.postman.com/docs/postman-cli/postman-cli-installation/) the latest Postman CLI. My question is whether the CLI command warns us if we are out of date. Ideally, it should just tell us if there is a new version. Or, at the very least, offer a new command line option to verify if the current install is up to date.

But the GUI version lets us know when there is a new version available, but I do not know if the CLI does that as well.

### Describe alternatives you've considered

* I can manually check the [CLI release notes](https://www.postman.com/release-notes/postman-cli/) web page (though, that does not instill confidence as that looks like it that is manually-generated post on a web site rather than a system generated artifact of the CI/CD system.

* If we are to rely on this [CLI release notes](https://www.postman.com/release-notes/postman-cli/) web page, it would be good if that page at least had an RSS feed (so that we have a fighting chance to notice the new release).

### Additional context

I would suggest retiring the `curl`-`sh` installation process, and consider a package management implementation that handles versioning for us ([HomeBrew](brew.sh)?).

**Comment by robertmryan** [comment]
Migrated from https://community.postman.com/t/how-to-confirm-postman-cli-version-is-current/46126

**Comment by akshaytate** [comment]
Hi @robertmryan, we show the following message at the end of the command output if an update for a newer version is available. This check is done once a day when any command is executed. Did you see such a notification?
<img width="719" alt="Screenshot 2023-04-11 at 6 50 01 PM" src="https://user-images.githubusercontent.com/102159741/231175554-d18aadc7-274d-4610-b62d-553848d8570e.png">


Could you also confirm what version of Postman CLI you are using? You can do this by using the `postman -v` command.

**Comment by robertmryan** [comment]
@akshaytate said:

> This check is done once a day when any command is executed. Did you see such a notification?

Nope. I originally installed version 1.1.1, but had no way of knowing whether that is the latest or not. 

Good to know that there is a version check happening.

Thanks.

**Comment by julian-alarcon** [comment]
This should be closed then.

**Comment by akshaytate** [comment]
@robertmryan @julian-alarcon Yes, closing this thread as  [this](https://github.com/postmanlabs/postman-app-support/issues/11900#issuecomment-1503344295) answers the queries.
