### ISSUE TITLE
"Send anonymous usage data" reverts back to YES

### ISSUE THREAD

**Issue by dlandis** [a85/POSTMan-Chrome-Extension#1190]
Change to "No" several times and then re-opened Preferences dialog and it was switched back to Yes. This doesn't happen every time...a couple times it stayed as "No" for a while but always switched back to "Yes" eventually. What's the deal?

**Comment by dlandis** [comment]
I would add none of the other settings seem to have this little issue of not staying saved.

**Comment by sobtiankit** [comment]
I just verified, this seems to be a bug that has crept in 3.0.0.10. We're pushing out an update today and it'll be fixed in the update. Sorry about this, and thanks for pointing it out.

**Comment by dlandis** [comment]
Sounds good, thanks for the quick response.

**Comment by sobtiankit** [comment]
fixed in 3.0.1
