### ISSUE TITLE
bug : the last test on skillcheck section shows an error 

### ISSUE THREAD

**Issue by ArslanYM** [a85/POSTMan-Chrome-Extension#11902]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Even though the code is working correctly as it should, the test still produces an error. 

![1](https://user-images.githubusercontent.com/104521101/230716416-5839e2d8-4aac-45b0-988d-c4b56bd847b5.png)

### Steps To Reproduce

Please help

### Screenshots or Videos

Screenshots from my code on postman
## The script 
![script](https://user-images.githubusercontent.com/104521101/230716473-72967799-3245-465d-9bff-6fb6be3e9587.png)

## Body of post req
![3](https://user-images.githubusercontent.com/104521101/230716438-109e3e21-0cb9-4779-bd7c-5f735430886f.png)

## api auth 
![4](https://user-images.githubusercontent.com/104521101/230716439-ce9c5445-f535-42ae-94c1-de868488f726.png)

### Operating System

windows 

### Postman Version

10,12,0

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by ArslanYM** [comment]
Update on this issue : 
test was showing failed but passed the skill test.

**Comment by clairefro** [comment]
@ArslanYM we will go ahead and close this issue as it is not related to the Postman app itself. We can see that you've found the appropriate channel to get help with your issue via our support email and we're happy to continue the conversation there!
