### ISSUE TITLE
Add line separators between requests in collections view

### ISSUE THREAD

**Issue by Redhunt2013** [a85/POSTMan-Chrome-Extension#11926]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

It is not a problem, but it would improve the visual organization of requests within a folder. Currently, there is no way to visually separate groups of requests within a folder. I would like to suggest adding a line separator between groups of requests to make it easier to distinguish between different types of requests.

### Describe the solution you'd like

Provide an option to add a line separator between requests. This could be done either by right-clicking on a request and selecting "Add separator above/below" or by clicking the three dots on the request and selecting "Add separator". This would give users the ability to visually separate groups of requests within a folder.

### Describe alternatives you've considered

None

### Additional context

In some cases, requests of different types or environments are grouped together in the same folder. For example, I may have requests for dev, test, and prod environments within the same folder. Adding a line separator would make it easier to separate these groups of requests visually. See the attached screenshot for an example of how this could look.

![separator](https://user-images.githubusercontent.com/5237704/232139245-652b6661-319a-42d2-973d-30244e81020b.jpg)

**Comment by giridharvc7** [comment]
@Redhunt2013 
> may have requests for dev, test, and prod environments within the same folder.

Have you used the environment features in Postman to solve this problem? This way there will be one request for all three environments and you change the baseURL depending on the environment selected. 

Asking this because, the problem you face seems very specific and there are other solutions for better organizing of requests in a collection. Adding a line seperator, might not help you much as all it does just a visual demarkation.

**Comment by Redhunt2013** [comment]
@giridharvc7  I have not used the environments feature yet.  I will give it a try.  Thank you!

**Comment by giridharvc7** [comment]
Let us know how this goes. I'm closing the issue for now

**Comment by duyn9uyen** [comment]
@giridharvc7, a line separator would still be nice to have because we can group separate related-requests.
