### ISSUE TITLE
If '&curren' present in link on json response is replaced as ¤ on pretty mode

### ISSUE THREAD

**Issue by alexandar** [a85/POSTMan-Chrome-Extension#1192]
when you receive json response

`{
    "link" : "https://test.com?total_amount=123.00&currency=GBP"
}`

and click on the link on the new tab will have `https://test.com?total_amount=123.00¤cy=GBP` link

**Comment by abhijitkane** [comment]
Decode link added due to #301
@alexandar - Thanks for reporting - will fix this in a future release

**Comment by abhijitkane** [comment]
@alexandar - Can you confirm this fix in v3.0.4?

**Comment by alexandar** [comment]
Fixed. Thanks!
