### ISSUE TITLE
Importing swagger which has list of items in security schemes

### ISSUE THREAD

**Issue by Agrawalmahin** [a85/POSTMan-Chrome-Extension#11928]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

When importing a swagger JSON,
I have a list of item in security schema in swagger. 
But when i import the same in postman, only the first item gets imported.

### Steps To Reproduce

1. Import Swagger with multiple security schema
Example : 
```
"securitySchemes": {
            "token": {
                "type": "apiKey",
                "description": "Token ",
                "name": "token",
                "in": "header"
            },
            "aId": {
                "type": "apiKey",
                "name": "aId",
                "in": "header"
            },
            "bId": {
                "type": "apiKey",
                "name": "bId",
                "in": "header"
            },
            "cId": {
                "type": "apiKey",
                "name": "cId",
                "in": "header"
            }
        }
```

2. When you see the api, it will only have token in the headers, and the value will be {{apiKey}}

### Operating System

macOs

### Postman Version

10.12.13

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by akshaydeo** [comment]
Hi @Agrawalmahin , thanks for getting in touch. Could you share the swagger version?

**Comment by Agrawalmahin** [comment]
"openapi": "3.0.1",

**Comment by Agrawalmahin** [comment]
@akshaydeo can you help me out here?

**Comment by aman-v-singh** [comment]
Hey  @Agrawalmahin,
The behaviour you have described is expected, as only one of the security requirement objects needs to be satisfied to authorize a request.

You can read more about it [here](https://spec.openapis.org/oas/v3.0.1#securityRequirementObject:~:text=API.%20The%20list%20of-,values,-includes%20alternative%20security%20requirement).

I am closing this issue, you can re-open it for further discussion.
