### ISSUE TITLE
Can't type decimal point into argument of GraphQL floating point field

### ISSUE THREAD

**Issue by jonesmo** [a85/POSTMan-Chrome-Extension#11931]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

I'm attempting to form a GraphQL mutation by typing input arguments into the Postman web UI.  When I try to type a decimal point into the ARG block for a Float-type field, nothing appears where the decimal point should be.  For example, when I try to type 7.9 into the imdbRating field: (see image)

### Steps To Reproduce

1. Add a new GraphQL Request
2. Connect to a URL and get the schema via introspection
3. Select a mutation
4. Select a Float-type field inside the mutation
5. Try to type a decimal number -- no decimal point appears

### Screenshots or Videos

<img width="1143" alt="Screenshot 2023-04-17 at 12 56 06 PM" src="https://user-images.githubusercontent.com/13224773/232556660-3e859ab3-108a-4ffa-bca6-317eeca2a8ab.png">

### Operating System

macOS

### Postman Version

10.12.12-230410-1611

### Postman Platform

Postman Web

### User Account Type

Signed In User

**Comment by timhall** [comment]
Hi! Thanks for raising this issue, it has been resolved and will be included in the next release.

**Comment by timhall** [comment]
This fix has been released with the September Postman release, thanks again for raising this issue
