### ISSUE TITLE
The app and webapp are freezing when using $ref in muilti-file schemas

### ISSUE THREAD

**Issue by miltonparedes** [a85/POSTMan-Chrome-Extension#11935]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Hello, trying postman for my team and..

The app and webapp are freezing when using $ref in muilti-file schemas, even when the path to the reference is correct this happens and makes it impossible to work with

### Steps To Reproduce

1. Write a multi-file schema
2. Use $ref with any object in another file
3. Try to open the reference

### Screenshots or Videos

https://user-images.githubusercontent.com/7311218/232686639-576bdb50-0eb3-4bf3-bdcc-2bef993f28ef.mov

### Operating System

macOS sillicon

### Postman Version

10.12.13

### Postman Platform

Both

### User Account Type

Signed In User

**Comment by jatin3893** [comment]
@miltonparedes Just checking back on this -> Are you still seeing this bug?
There was a similar bug that we fixed in the April release of postman i.e. 10.13.
