### ISSUE TITLE
Length of Array different if collection run with Runner or CLI

### ISSUE THREAD

**Issue by antoniooptiply** [a85/POSTMan-Chrome-Extension#11938]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Hi, on a particular collection of requests on one of the request we check if an array has elements or not, and will go to the next request based on the result. If the array length is > 0 continue to next request, if not stop the run.
This have diferent outcomes depending on where we run the collection: using the same data, on postman runner, the request will move to the next one has expected, BUT on CLI the collection stops. On the screenshot attached you can see the logs.

### Steps To Reproduce

1. a collection that have a Test where it checks the length of an array and move to the next request if the length is > 0
2. run this collection on Runner and on CLI
3. on Runner the collection will move to the next request (length is > 0), on CLI will not (length is not > 0)

### Screenshots or Videos

![Screenshot 2023-04-18 at 13 40 15](https://user-images.githubusercontent.com/126565892/232785924-8901044d-66ce-4073-a3ab-7a7fe8612039.png)

### Operating System

macOs

### Postman Version

10.12.11

### Postman Platform

Postman App

### User Account Type

Signed In User

### Additional Context?

the code we are using to make the decision is:

`if(Array.isArray(boListIds) && boListIds.length > 0){
    //proceed to check SupplierProduct
    console.log("---------------------------> boListIds.length > 0, SO going to -> Check if BO is duplicated in Logic4");
    postman.setNextRequest('Check if BO is duplicated in Logic4');
}
else{
    console.log("---------------------------> boListIds.length NOT > 0, SO....... STOPING HERE !!!!");
    postman.setNextRequest(null);
}`

**Comment by malvikach** [comment]
Hi @antoniooptiply 

I am unable to replicate this behavior. I tried this [collection](https://www.postman.com/postman/workspace/postman-answers/request/9215231-b07e0953-2f99-41a1-a8b0-5a0eceb56130). 

Both on Postman and on Postman CLI, I see the length of the array as 3. 
<img width="526" alt="Screenshot 2023-04-25 at 3 16 40 PM" src="https://user-images.githubusercontent.com/89449769/234240425-7d8eb80f-46bb-4230-b0b5-a512e851a4a5.png">

<img width="556" alt="Screenshot 2023-04-25 at 3 16 15 PM" src="https://user-images.githubusercontent.com/89449769/234240447-23bfc93d-6908-43c1-a3eb-58248d8b7f97.png">

It would help if you console.log() your array and check the contents of the same. It is possible that the array is not being set for some reason while running on CLI. Let me know your observations.

**Comment by antoniooptiply** [comment]
Thanks @malvikach 
Running the collection, results side-by-side, CLI vs Runner.
Console log for boListIds and boListIds.length are diferent as you can see on the screenshot:
![Screenshot 2023-04-26 at 14 28 45](https://user-images.githubusercontent.com/126565892/234591241-99366a81-1e2d-4d29-8267-57627a20dc9b.png)

Thanks,
António

**Comment by malvikach** [comment]
@antoniooptiply You might want to check how the array is being set and debug the issue. I am suspecting that on Postman CLI the array is not being set as expected due to some reason. (for example: is the array being set through the response of a previous request- if yes, is the request responding the same way- you can console.log() the response and verify the same) 

Both Postman CLI and Postman app use the same underlying library so there should be no difference between a collection run's behavior between the two.

**Comment by malvikach** [comment]
Hi @antoniooptiply 👋  Let us know if you are still facing any issue with the above?

Please feel free to reopen the ticket if yes.
