### ISSUE TITLE
Encoding error in exporting requests from Postman

### ISSUE THREAD

**Issue by rishirdua** [a85/POSTMan-Chrome-Extension#11934]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

I have an entity with id: urn:li:foo:62324 To make a GET call, I set "urn%3Ali%3Afoo%3A62324" in the URL and it works fine.

This gets translated to "urn%253Ali%253Afoo%253A62324&" in the exported CURL

This means the percentage sign is getting encoded, which I don't want.

It seems Postman is making a different curl call from what it is exporting.

I'm fairly confident this is a new issue since this used to work fine.

### Steps To Reproduce

1. Open a new request tab
2. Make a GET call to http://linkedin.com/urn%3Ali%3Afoo%3A62324
3. Look at the corresponding curl generated.

### Screenshots or Videos

See screenshot
![postman-bug](https://user-images.githubusercontent.com/4724852/232636651-21ee314e-6980-4423-b8af-9bd790a2fcac.jpeg)

Version 10.12.13
UI Version: 10.12.13-ui-230411-0412
Desktop Platform Version: 10.12.13 (10.12.13)

### Operating System

Mac

### Postman Version

10.12.13

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by dhwaneetbhatt** [comment]
Thanks @rishirdua for reporting this. We're looking into it and will keep this thread updated.

**Comment by rishirdua** [comment]
Hey @dhwaneetbhatt do you happen to have an ETA for this?

**Comment by dhwaneetbhatt** [comment]
Hey @rishirdua this will be fixed in the May monthly update which should roll out sometime after 15th May. Will update this thread when it starts rolling out.

**Comment by dhwaneetbhatt** [comment]
@rishirdua this issue is fixed in the latest (v10.14) version of Postman. Feel free to reopen this with additional details if the problem still persists.
