### ISSUE TITLE
Feature request: delete environment variable

### ISSUE THREAD

**Issue by wabiloo** [a85/POSTMan-Chrome-Extension#1193]
I'm writing tests for Postman, and would like the ability to delete global environment variables. Is that possible?
They are just temporary ones that need to be saved in order to be used in a chain of requests, but at the end of it, I don't need them anymore, and they clog my environment variable view...

So, a postman.unsetEnvironmentVariable(variableName) would be a great addition...

**Comment by aliyav** [comment]
+1 for this feature.

**Comment by GevaZeichner** [comment]
+1

**Comment by gioid** [comment]
+1

**Comment by ghost** [comment]
+1 .  As an addendum, a command to delete -ALL- environment variables -- e.g. postman.deleteAllEnvironmentVariables() -- would be helpful.

**Comment by a85** [comment]
@shamasis Available in collection-v2?

**Comment by shamasis** [comment]
@a85 - it's a function of runtime. Should be a matter of exposing via postman API. Then the apps would need to honour the deletions.

**Comment by a85** [comment]
@shamasis I believe this is possible now?
