### ISSUE TITLE
Initial environment variables can't be used from Postman app in requests, they are defined as "null" value

### ISSUE THREAD

**Issue by Zheltanoha1** [a85/POSTMan-Chrome-Extension#11936]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

I have environment variable with initial value and I want to use it in my request (not current value, only initial).
But when I run simple request with using {{variable}} then  I see null value in it.
I expect that initial value should be passed in my request from environment variables, but I see that only current value work fine.

### Steps To Reproduce

1. Request GET, url for example https://api.some_portal.com/v2/{{variableName}}
2. I have only initial value for variableName in environment variables
3. Run request
4. I see error  "code": 404,
    "message": "No route found for ..."
because {{variableName}} is null

### Operating System

Windows

### Postman Version

10.13.1

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by arlemi** [comment]
Closing as a duplicate of #7179, please subscribe to the other issue to hear about any updates!
