### ISSUE TITLE
Chrome limits certificate validity period, causing NET::ERR_CERT_INVALID error on Postman

### ISSUE THREAD

**Issue by evibhm** [a85/POSTMan-Chrome-Extension#11949]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

When using Postman to capture network traffic, the generated certificate exceeds the maximum validity period of 398 days set by Chrome, resulting in a NET::ERR_CERT_INVALID error message. Note that the Postman-generated certificate has been added to the trusted certificates in the system.

### Steps To Reproduce

1. Use Postman to capture network traffic and generate a certificate.
2. Add the Postman-generated certificate to the trusted certificates in the system.
3. Attempt to use the generated certificate in Chrome, resulting in a NET::ERR_CERT_INVALID error message.

### Screenshots or Videos

when I use Postman,

![](https://i.imgur.com/P4hGFx2.png)

but, when I use whistle,

![](https://i.imgur.com/OoXNq7Q.jpg)

### Operating System

macOS

### Postman Version

10.13.4

### Postman Platform

Postman App

### User Account Type

Signed In User

### Additional Context?

Chrome limits certificate validity period to improve network security, but Postman generates certificates that exceed this limit, causing errors when capturing network traffic. Although the Postman-generated certificate has been added to the trusted certificates in the system, the error message still appears in Chrome. It is recommended that Postman adheres to Chrome's limitations when generating certificates to facilitate better network operations.

<https://chromium.googlesource.com/chromium/src/+/HEAD/net/docs/certificate_lifetimes.md>

**Comment by VShingala** [comment]
@evibhm Could you check if this issue is still reproducible with latest version of App? (i.e. v11).

If yes, you can follow below steps to regenerate the expired certificate forcefully.

- Quit Postman App if open.
- Head over to `/Users/{{YourUserName}}/Library/Application Support/Postman/proxy`
- Delete `postman-proxy-ca.crt` and `postman-proxy-ca.key` files.
- Reopen Postman app and start the proxy session.

**Comment by VShingala** [comment]
@evibhm We're closing this issue but feel free to reopen it if you face any further problems.
