### ISSUE TITLE
[Team Sync Beta] Saved Responses save post data locally but post data is not shared with the Team

### ISSUE THREAD

**Issue by andy-g** [a85/POSTMan-Chrome-Extension#1194]
When saving responses, the post data is saved locally along with the response data, so clicking on the saved response displays the response as well as updating the post data, so the post can be resent.

Unfortunately, it seems like although the saved response is synced, if another Team member clicks on it they can see the response data but the post data is not updated to show the data sent for that response.

I'm not sure if this is by design, but the advantage of saving both the post and response data would allow multiple variations of calls on a single endpoint rather than needing to create new entries for each variation.

**Comment by abhijitkane** [comment]
I'm not able to reproduce this.

I shared a collection with one POST request, body-type=form-data, but the form-data empty. I sent the request after adding a row to the form-data, and saved the response. (At this point, the request contained an empty form-data array, but the response's saved request had the form-data).

On another team-member's machine, I subscribed to the collection, and clicking on the response populated the form-data fields.

I tried for url-encoded and raw data as well.

It might be that the response was not saved correctly in an earlier version. Can you try updating to 3.0.0.31 (chrome:/extensions > Developer Mode > Update), and try with a new request/response?

**Comment by andy-g** [comment]
I'll give that a go, thanks for the quick response.
