### ISSUE TITLE
Git - API definition don't sync

### ISSUE THREAD

**Issue by carlos-rian-qd** [a85/POSTMan-Chrome-Extension#11944]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

I have a **schema.json** file in my Azure Repo; I created a new API in Postman, imported that file from the repository as the API definition, and created a collection of the API definition... so far, OK!

But when this **schema.json** file in my Azure Repo is changed with a new version, the postman identifies that the repositories have a recent change and pulls the changes. **But it doesn't update the API definition!** Why? It doesn't make sense to me.

### Steps To Reproduce

1. Sign in to Azure Repos
2. Create a new repository
3. Add a new file with OpenAPI schema
4. Create a new API in Postman
5. Import schema from Azure Repo in Postman
6. Once created, try updating the Azure Repo schema file by adding a new endpoint.
7. Go to Postman, try to sync changes
8. You will see that you don't have any changes to your API definition

### Operating System

Windos

### Postman Version

10.12.13

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by shashankawasthi88** [comment]
@carlos-rian-quartile thanks for raising the issue. We are looking into it.

**Comment by shashankawasthi88** [comment]
@carlos-rian-quartile can you share a screen recording of the issue ?

**Comment by carlos-rian-qd** [comment]
@shashankawasthi88 I checked that the file that needs to be updated is in `postman/schemas/file_name.json`, but I was editing the root file in my repo.

It was my need for more attention.

Updating the file inside the Postman folder works as expected.

Thanks for the quick response.

![image](https://user-images.githubusercontent.com/88094994/233390190-1ddd0175-56d9-4230-9110-f6305a791219.png)
