### ISSUE TITLE
Global Search bar (CTRL + K) doesn't show the name of the requests in personal workspaces

### ISSUE THREAD

**Issue by yogesh8130** [a85/POSTMan-Chrome-Extension#11954]
### Is there an existing issue for this?

- [x] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Request name is not shown in global search, see screenshot. 
Only request types are shown.

### Steps To Reproduce

1. Press ctrl + k
2. Search for a request in personal workspace
3. the requests are visible in results but only the request type not the name of the request

### Screenshots or Videos

![Screenshot 2023-04-21 210215](https://user-images.githubusercontent.com/131368934/233684825-04f99bda-69ce-475e-89e0-b88d90c9121e.png)

### Operating System

Windows 10

### Postman Version

10.13.4

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by ranjan-sh** [comment]
HI @yogesh8130 , thanks for bringing it to our attention. The team is looking into this!

**Comment by ranjan-sh** [comment]
This was fixed.
