### ISSUE TITLE
Canonical links in Responses no longer clickable in 3.0

### ISSUE THREAD

**Issue by gitlucky** [a85/POSTMan-Chrome-Extension#1195]
Hi team,
I really enjoy the Postman client. It's a great tool that has increased my productivity in developing and testing REST services. Thumbs up!

I just noticed your new 3.0 version this morning. Although I like your new UI (looks great), I can't say I like losing the ability to click on canonical links from my responses. In 'Pretty' view, these (relative) links were enabled prior to 3.0. I could simply click on them (retaining the headers) and navigate my resources effectively. But that's no longer possible?!

Is there something I missed or is this a regression?

Thanks in advance.
P.

**Comment by abhijitkane** [comment]
Can you update to the latest version (3.0.1)? You can force an update by going to chrome:/extensions, enabling 'Developer Mode', and clicking 'Update extensions now'

**Comment by gitlucky** [comment]
I updated to 3.0.1 but it did not resolve the problem. Still can't click links.
I'm running Version 3.0.1 (packaged) on windows. Here's a sample of such canonical link in my JSON response:
"canonicalLink": "/foo/.common/api/v1/endPointTemplates/1000"

The link used to be highlighted and when clicked it would set the address bar accordingly. 
Note that I use a variable for my Server URL: **{{ServerURL}}**/foo/.common/api/v1/endPointTemplates

**Comment by abhijitkane** [comment]
@gitlucky Can you confirm this fixed in v3.2.8?

**Comment by gitlucky** [comment]
Yes, it works great now! I'm running Version 3.2.9 (packaged).
Thanks for the fix.
