### ISSUE TITLE
Bug report: Able to use "team workspace" feature after free trial period is over without any payment

### ISSUE THREAD

**Issue by karianmash** [a85/POSTMan-Chrome-Extension#11951]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Hi there,

I wanted to report a critical bug on the website that could be potentially costing the company a lot of money. My team and I have noticed that even after the free trial period is over, we are able to continue using the "team workspace" feature. This appears to be happening because we are able to close the modal that notifies us that the free trial is over and we should pay.

This is a serious issue because if other users are also able to bypass the payment prompt and continue using the feature without paying, it could lead to a significant loss of revenue for the company.

I would urge you to investigate and fix this issue as soon as possible to prevent any further financial losses. If there is any additional information that I can provide to help with debugging this issue, please let me know.

Thank you.

### Steps To Reproduce

1. Sign up for a free trial of the "team workspace" feature on the website.
2. Wait for the free trial period to expire.
3. When the modal appears notifying you that the free trial is over and you need to pay to continue using the feature, delete the entire HTML element that contains the modal using the browser's developer tools.
4. You should now be able to access and use all the features of the "team workspace" without any visible indication that the free trial has expired.

### Operating System

Linux

### Postman Version

10.13.4-230419-1536

### Postman Platform

Postman Web

### User Account Type

Signed In User

### Additional Context?

The modal that appears when the free trial period is over is easily dismissive by deleting the entire element that contains the modal from developer tops.

After dismissing the modal, we are still able to access and use all the features of the "team workspace". There is no visible indication that the free trial has expired, and we are able to perform all the same actions as we were during the free trial period.

**Comment by haleygodtfredsen** [comment]
Thank you @karianmash we are actually in the process of fixing this :)

**Comment by karianmash** [comment]
Dear Haley Godtfredsen,

Thank you for letting me know that you're currently in the process of
fixing the issue I reported. I'm glad to hear that the issue is being
addressed, and I appreciate your prompt response.

While I have your attention, I wanted to express my interest in potential
career opportunities with your company. As a Software Engineer, I believe
my skills and experience align with the company's mission and values. I
would be honored to contribute my skills and knowledge to your team and
help drive the company's success.

If there are any job openings or opportunities that match my skills and
experience, I would be grateful for your consideration. Please let me know
if there are any next steps I can take to submit my application or connect
with your HR team or recruiters.

Thank you again for your attention, and I look forward to hearing back from
you.

Best regards,
Ian Macharia

**Comment by supershanesta** [comment]
Any update on this @haleygodtfredsen. I am also having this issue.

**Comment by haleygodtfredsen** [comment]
Hi @supershanesta do you mind emailing [help@postman.com](mailto:help@postman.com), referencing this ticket? We can help you from there. Thank you!
