### ISSUE TITLE
[Advanced Auth Settings] A variable is replaced with its value

### ISSUE THREAD

**Issue by IlliaMamonov** [a85/POSTMan-Chrome-Extension#11958]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

A variable value is replaced with its value after obtaining a token (Advanced Auth Settings).

### Steps To Reproduce

1. Open Collection Auth Settings
2. Add a custom parameter in an Advanced section
3. Use a variable as a value ( an environment variable was used in an example below)
4. Get New Access Token

Actual result:
After a token is obtained, the variable value is displayed instead of the name

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/75385093/234392068-de10dd86-4cee-4915-99fc-5bb38df9e4c1.png)
![image](https://user-images.githubusercontent.com/75385093/234392209-c4e7e23f-f588-4c44-bd33-8b6b7ace00aa.png)

### Operating System

Windows

### Postman Version

10.13.4

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by abhijeetborole** [comment]
Hey @IlliaMamonov, thanks for reporting this issue. We are tracking an issue where the variables show up as resolved in the OAuth2 advanced options when the generated token is not used. I'll update once we have a fix in place.

**Comment by abhijeetborole** [comment]
Hey @IlliaMamonov, we've fixed this issue with Postman v10.14. The resolved variable values will no longer be displayed in the advanced options. 

Do let us know if you face any more issues.

P.S. - Postman v10.14 is being rolled out and will be available for everyone in a couple of days.
