### ISSUE TITLE
Postman Flow - "Copy to clipboard text" or "Select specific text" option in blocks

### ISSUE THREAD

**Issue by darshalesachin** [a85/POSTMan-Chrome-Extension#11974]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

As a postman user, would like to see an option that would allow user to copy specific/whole text into clipboard.
`OUTPUT` block does not allow text selection or copy option.

### Describe the solution you'd like

would love to see either `copy to clipboard` button or simple manual copy paste option that would copy from any block.

### Describe alternatives you've considered

no direct alternative for `output` block.
other option is to use `log` block and then manually copy.

**Comment by noamshvacher** [comment]
Anything new with this request?

**Comment by NeufeRy** [comment]
I hope this feature is added soon. Being able to select or copy all from the output block seems like an easy product sprint and would make flows such a powerful tool. If anything right now this tool is frustrating because you can see that data output right there, but there is now easy way to download, export, or copy it.

**Comment by rabbah** [comment]
We're on it, thought I can't share an ETA yet. Thanks for the feedback.

**Comment by ReflexReaction** [comment]
There are significant overlaps with https://github.com/postmanlabs/postman-app-support/issues/10356 

The ability to extract data from a PostMan flow is critical, thank you.

**Comment by PaulPoinet** [comment]
yep, same request here

**Comment by SaulBurgos** [comment]
same

**Comment by rabbah** [comment]
we have added the ability to copy the entire output block content to clipboard - selecting / searching with the output is not yet ready, you can work around it by using a `select` block with an output block just for the parts you want in the time being? more to come.

https://github.com/postmanlabs/postman-app-support/assets/4959922/ec5e6ecf-7667-4f91-b16c-fac5e14993e6
