### ISSUE TITLE
"No new changes to save" popup doesn't go away after saving a request.

### ISSUE THREAD

**Issue by henryobiaraije** [a85/POSTMan-Chrome-Extension#11975]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Sometimes when you click on the save button, the "No new changes to save" popup doesn't go away and there is no way to remove it.

![postman-issue](https://user-images.githubusercontent.com/45720045/235772441-82ca3a03-94eb-41eb-9441-c5a34e501e28.png)

### Steps To Reproduce

1. Add a new request
2. Save the request
3. Sometimes the toast says"No new changes saved" appears and does not go away. It blocks the "Send" button.

### Screenshots or Videos

![postman-issue](https://user-images.githubusercontent.com/45720045/235773274-1e2887d3-57a1-46ee-9be0-637813f89ca2.png)
 

### Operating System

Windows

### Postman Version

10.13.5

### Postman Platform

Postman App

### User Account Type

Signed In User

### Additional Context?

Sometimes when you click on the save button, the "No new changes to save" popup doesn't go away and there is no way to remove it.

**Comment by vedkribhu** [comment]
@henryobiaraije thanks for reporting this. This is definitely a very irritating issue, we will be fixing this in our next release. In the meantime, you can try using the cmd+s shortcut to save the request and (enter) to run the request.

**Comment by vsaR1SK** [comment]
Issue still reproduce (UI version 10.19.2-ui-231013-1442)

**Comment by IanioMurrayGlobal** [comment]
I am still getting this issue on Postman v11.7.0 using UI version v11.7.0-ui-240730-0645
![image](https://github.com/user-attachments/assets/c9f3ff16-782a-483e-beef-f35062cc22f1)

**Comment by rmoham** [comment]
Hi All,

The issue still persisting since a case has been raised almost year ago.

![image](https://github.com/user-attachments/assets/61438de1-973e-40fd-9690-9d8727b36257)
