### ISSUE TITLE
As a Postman flow user, I want to postman provide some more samples for existing FQL functions

### ISSUE THREAD

**Issue by wangfeifan945** [a85/POSTMan-Chrome-Extension#11970]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

As a user, i want to filter array with objects. But no enough knowledge or sample to follow.
So, want team provide more samples.

https://learning.postman.com/docs/postman-flows/flows-query-language/function-reference/#eval
![image](https://user-images.githubusercontent.com/37173694/235281959-ae140e9f-ddc2-4cc9-83e9-42e1863a5e42.png)

As above sample, now existing samples are almost all-around simple array $filter([1,2,3,4,5], fn($e){ $e>3}) -> [4, 5]
For some more normal object array like below do not have any samples:
[
{
"name": name1},
{
"name":name2}
]

### Describe the solution you'd like

Want team provide some more samples with object array and some other complex array

**Comment by SterlingChin** [comment]
Thank you for the feedback. We are currently in the process of revamping our docs around Flows, ETA around mid-August!

**Comment by rabbah** [comment]
here's an example
```
$filter(list, fn($item) { 
    $item."g:color" = color
})
```
<img width="1160" alt="Screenshot 2024-04-19 at 10 28 06 PM" src="https://github.com/postmanlabs/postman-app-support/assets/4959922/7bf34c44-afad-4e94-b86a-3a5e99d43a0a">

**Comment by rabbah** [comment]
We are adding more examples to the learning center.
