### ISSUE TITLE
Postman Flow - Option to group related flows (Similar to folder structure in collection)

### ISSUE THREAD

**Issue by darshalesachin** [a85/POSTMan-Chrome-Extension#11972]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

As a postman flow user, I would like to group related flows together (similar to folder structure in collection).

### Describe the solution you'd like

would love to see an option similar to folder structure in collection.

### Describe alternatives you've considered

no alternative

**Comment by saswatds** [comment]
Hi @darshalesachin, could you give some insight into what these related flows could look like? By observing the community, we have observed that using the workspace to group together related flows is really effective as well. 

We have recently released the grouping feature within a flow which is a different way of organization in flows. Given that both these feature are almost same I am closing this issue. 

Can reopen the issue if we find a greater need for additional manual organization with folders.

**Comment by darshalesachin** [comment]
Hi @saswatds,
We have lot of different products and APIs, and these serve different purposes. so we have grouped them based on the product/domain in our public postman collection. To group them, we have created folder/sub-folders in public collection.
We wanted to add some Postman Flows for these products/APIs but Flows does not have folder/sub-folders. We have different use-cases and we wanted separate Flows for those and we wanted to group them under a folder/sub-folder based on the product/domain etc.

For e.g.
our public collection structure is - 
```
Collection
├── Product_1
│   ├── API_Request1
│   ├── API_Request2
│   ├── API_Request3
├── Product_2
│   ├── SubFolder_1
│   │   ├── API_Request1
│   │   ├── API_Request2
│   │   ├── API_Request3
│   │   ├── API_Request4
│   ├── SubFolder_2
│   │   ├── API_Request1
│   │   ├── API_Request2
│   │   ├── API_Request3
├── Product_3
│   ├── API_Request1
│   ├── API_Request2
│   ├── API_Request3
└── Product_4
    ├── API_Request1
    └── API_Request2
```

For Flows, we wanted to group them based on product/use-case/uses etc.
Here is what we are looking for -
```
Flows
├── Product_1
│   ├── Usecase_1_flow
│   ├── Usecase_2_flow
│   ├── Usecase_3_flow
├── Product_2
│   ├── SubProduct_1
│   │   ├── Flow_1
│   │   ├── Flow_2
│   │   ├── Flow_3
│   │   ├── Flow_4
│   ├── SubProduct_2
│   │   ├── Flow_1
│   │   ├── Flow_2
├── Product_3
│   ├── Flow_1
│   ├── Flow_2
│   ├── Flow_3
└── Product_4
    ├── Flow_1
    └── Flow_2

```
With current Postman Flows structure, we can not group them in a folder/sub-folder way based on products, so it is going to be bad user experience for our end users. so we are looking for an option on grouping them in organized way.

let me know if you need more details.

Just FYI - We want all our products/APIs under same workspace/collection. so creating separate workspace or collection for each product is not what we want.

**Comment by rabbah** [comment]
Thanks for the additional feedback @darshalesachin - this is helpful to understand your constraints and desired workflow.

**Comment by sdarshale** [comment]
Can you please reopen this

**Comment by rabbah** [comment]
Hi @sdarshale we're discussing this internally. I'll reopen it if warranted and we will take action.

**Comment by darshalesachin** [comment]
@rabbah - We would love this feature where we can organize Flows in Folder structure.

**Comment by darshalesachin** [comment]
looks like this is available now. Thanks Postman for adding this feature.
