### ISSUE TITLE
Performance Test: No logs & troubleshooting help

### ISSUE THREAD

**Issue by vdespa** [a85/POSTMan-Chrome-Extension#11980]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

I was trying out the new Performance Tests on an API and I can't find any way to troubleshoot why the API is not responding during the Performance Test. 

Running the exact same API using a functional test works just fine.

<img width="1304" alt="image" src="https://user-images.githubusercontent.com/1197635/236103913-da676e9d-c9b6-4f6e-89f8-ac0de051e801.png">

It is not possible to see any logs or technical errors. This makes troubleshooting very difficult. 

### Steps To Reproduce

1. Fork the collection "Valentino's Artisan Coffee House":
https://www.postman.com/valentins-team/workspace/postman-in-a-workspace/

2. Create a valid token using the "Register a new client" request and save it as a collection variable.

3. Run the performance test using 1 VU & 1 min.

### Operating System

macOS

### Postman Version

Version 10.13.6-canary01

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by malvikach** [comment]
@vdespa 👋 Thanks for all the details! I am able to reproduce the issue. It seems like the requests from the client were not reaching the server at all (no response times were reported for the requests)

When we dig deeper, It seems that the collection variable is not being resolved in the performance test and hence the base_url is likely empty. We are picking this as a bug. Meanwhile, please use the environment variables to proceed with the testing. 

(We see a similar issue with globals too and that will be picked up as part of this fix as well)

Also on a separate note, we will add some troubleshooting help as subsequent improvements in the product.

**Comment by vdespa** [comment]
@malvikach I am not sure the problem is the variable. I had used the same variable with a different value for localhost and it worked without issues. 

Anyway, my point is that this is not just about figuring out why this is not working but also providing a technical error that allows the user to debug this. Maybe there is a local network issue. Without an error or logs, we can only make guesses.

**Comment by malvikach** [comment]
@vdespa  👍  taking this as feedback for improvement. We will work towards adding more troubleshooting info. 

Will keep you updated here. 

Regards,
Malvika

**Comment by davidd-bounteous** [comment]
2nd'ing this as it is currently tough to debug issues. Looking forward to the updates.

**Comment by malvikach** [comment]
Hi @vdespa @davidd-bounteous 

We have a mock/prototype that we would love to run by you and get some feedback on the experience that we plan to build to solve this problem. Please let me know if you would be available for a quick catchup to discuss about the same. (You can drop me a note on malvika.chaudhary@postman.com and we can setup some time with you) 

Thanks again for the feedback!

Regards,
Malvika

**Comment by Octobeast999** [comment]
using 10.13.9

If anyone has issues with 100% error rate, remove any environment variables and try again. i was using a variable for part of the endpoint url and for an api token. once i removed these are set them manually it worked fine. if it also helps I could pass a variable in the body such as {{$randomFirstName}}, which worked fine. it seems to only have issues with environment/collection variables or so, in this case my API token variable and a baseURL variable.  thank you 🙂

would be a great addition to have some error codes returned.

**Comment by nhsJim** [comment]
Just noticed I was having the issue as well, 100% error rate and I am using variables. 
I will hack a new collection to run on it's own and see what happens. 
Would it be worth renaming this issue to make it stand out more?
I would imagine a lot of people trialing out the performance testing capabilities will be using established collections with variables set up.

**Comment by postfrzero** [comment]
@Octobeast999 @nhsJim Thanks for bringing this to our attention. I've created #12083 to track the issue you've reported since it's likely to be a bug and not just a matter of having an error classification breakdown. We can have the rest of the conversation over there.

**Comment by shreyas-panduranga** [comment]
All, we're now aware of an issue in performance testing feature where when we fetch a value that is stored in the environment, it is truncated to 140 characters. If the values you have been testing with exceeds this limit you will be affected by this issue. Any values shorter than this limit won't be affected and you can continue to keep them in the environment.

We are looking to fix this very soon. Collection variables don't suffer from this issue.

**Comment by malvikach** [comment]
Hi @vdespa @davidd-bounteous 👋 

Glad to inform you that in the latest release of Postman (v 10.17.1), we have introduced this feature. 

We now include request, response information such as headers, bodies in case of errors. You can click on the "errors" tab to see details as shown in below recording:

https://github.com/postmanlabs/postman-app-support/assets/89449769/d59742c0-07fc-4fe1-9161-4b3a6b40333e

Thanks again for your feedback in helping us improve the product!

Cheers
Malvika
