### ISSUE TITLE
Create an API version via postman API not supported in V10 API ?

### ISSUE THREAD

**Issue by kostonou** [a85/POSTMan-Chrome-Extension#11989]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Hello,
i'm currently trying to create a new version of my API through postman api.

I tryed with exemple from [documentation](https://www.postman.com/postman/workspace/postman-public-workspace/documentation/12959542-c8142d51-e97c-46b6-bd77-52bb66712c9a?entity=folder-74aa54b5-9f5f-4ba5-923f-a6c805c14774)
![image](https://user-images.githubusercontent.com/45897955/236482333-b499ad67-d34d-4381-aae9-c791439e065b.png)

It seems that the postman API doesn't work like described because it returns :
`{
    "error": {
        "name": "paramMissingError",
        "message": "Parameter is missing in the request.",
        "details": {
            "param": "version"
        }
    }
}`

So i tryied to discover the needed schema for version, like this :

`
{
    "version": {
    "name": "Release 8.35",
    "releaseNotes": "This is the first public release update."
    },
    "collections":
    [
        {
            "id": "{collectionIdLinkedToMyAPI}"
        }
    ],
    "schemas":
    [
        {
            "id": "{schemaId}"
        }
    ]
}
`

Then I'm facing an http 400 with this message :

`{
    "error": {
        "name": "actionIsNotSupported",
        "message": "This action on API Version is not supported for v10 APIs."
    }
}`

Does anyone know how to create a new version of API through postman API ?

Hope my issue is quite clear :)

Best regards

### Steps To Reproduce

POST https://api.getpostman.com/apis/{apiID}/versions

`
{
    "version": {
    "name": "Release 8.35",
    "releaseNotes": "This is the first public release update."
    },
    "collections":
    [
        {
            "id": "{collectionIdLinkedToMyAPI}"
        }
    ],
    "schemas":
    [
        {
            "id": "{schemaId}"
        }
    ]
}
`

### Operating System

macOS

### Postman Version

10.13.5

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by davidespihernandez** [comment]
Thanks for your question, @kostonou!
Can you please confirm you are sending the `Accept: application/vnd.api.v10+json` header in your request?

**Comment by davidespihernandez** [comment]
@kostonou I've tested the API with an existing API and it works for me.

```
curl --location 'https://api.getpostman.com/apis/560f0dac-5d17-423e-93b5-d2dddea2d3f2/versions' \
--header 'Accept: application/vnd.api.v10+json' \
--header 'Content-Type: application/json' \
--header 'x-api-key: PMAK-XXX' \
--data '{
    "name": "v3.0",
    "releaseNotes": "Automatically created version",
    "collections": [
        {
            "id": "16473433-9e669d8b-6b3a-4020-b4d9-579a93c6efb3"
        }
    ],
    "schemas": [
        {
            "id": "351abdb9-1339-46e0-ab16-350bf5cc6056" 
        }
    ]
}'
```

Are you sure the collection id is correct (linked to the API)? Does that collection appear in the list of collections on the API detail page? Is the schema id correct (the definition id)?

**Comment by kostonou** [comment]
Hi @davidespihernandez, i mixed tests on postman and tests via curl and i forgot to add the header  'Accept: application/vnd.api.v10+json'.

now it works, thanks !
