### ISSUE TITLE
Request Dependencies

### ISSUE THREAD

**Issue by ToddPettit** [a85/POSTMan-Chrome-Extension#1198]
It would be fantastic is saved requests could trigger additional requests to populate required query string param or body data.

Example: If a session token is used for user authentication, it would be awesome if we could map the input value to a value in the response of another endpoint. In this case, lets say I had the following authenticated endpoints: 
Postman label: "Login"
POST ../login
returns {"sessionToken":"ABCDEF"}

Postman label: "Matches"
GET .../matches?sessiontoken={PostmanGlobalObject.Login.sessionToken} <---------
returns {"users":"..."}

In this case I don't need to manually hit /login to fetch the session token in order to hit the /matches endpoint.

**Comment by cangd** [comment]
I support this feature request!

**Comment by kams-mash** [comment]
+1

**Comment by a85** [comment]
This can be accomplished through pre-request scripts/test scripts + environment variables now. Tutorials at blog.getpostman.com
