### ISSUE TITLE
Performance Test: Not starting when using private git synced API collection w/ no logs

### ISSUE THREAD

**Issue by tnitan** [a85/POSTMan-Chrome-Extension#11981]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Attempting to run Performance tests the private collection with id 21240185-669cd287-003f-425f-8aae-0e98605d5f0c results in a "Failed to start run" error (attached screenshot), while Functional tests are working as expected.

- No requests are being displayed in Postman console or Developer console (other than https://bifrost-premium-https-v10.gw.postman.com/ws/proxy).
- No logs are being generated in logs folder.

### Steps To Reproduce

1. Open Postman Canary desktop app
2. Log in to Team Workspace account
3. Go to APIs and select a private Collection
4. Attempt to run Performance test with x users x duration

### Screenshots or Videos

![postman-performance-tests](https://user-images.githubusercontent.com/8640688/236138126-6ca8690f-303a-488b-8cad-2fc791ea255a.JPG)

### Operating System

Windows

### Postman Version

10.13.6-canary01

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by malvikach** [comment]
@tnitan 👋 Thanks for reporting this. This seems to be a bug at our end.

Meanwhile, to unblock you: request you try the performance test with Collections under the 'Collection' tab. 

We will update this thread once the bug is fixed.

Regards,
Malvika

**Comment by tnitan** [comment]
Hey, @malvikach. Indeed, running it from Collection tab starts the test as expected. Thanks!

**Comment by malvikach** [comment]
Hi @tnitan 👋 

This issue is now fixed. Let us know if you still face any issue with this or something else on performance testing. If you like to talk to me over a call to share your experience, here is my [calendar](https://calendly.com/malvika-chaudhary/v10-feedback?month=2023-08). 

Thanks again for your feedback. 

Cheers!
Malvika
