### ISSUE TITLE
No output on performance metrics once performance testing is being executed 

### ISSUE THREAD

**Issue by itay1709** [a85/POSTMan-Chrome-Extension#11997]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Once I run the collection for performance testing with only 1VU (I tried with 2 and 3 as well), no output is showing in the different metrics. Important to mention that the collection runs OK once I use the "functional" tab in the Runner. 

### Steps To Reproduce

1. Run the collection by choosing "performance" tab.
2. Choose the values: 1 for VU and 2 Test duration and press "run".
3. See that no output is shown on the metrics.

*logs and screen shot are attached.

### Screenshots or Videos

![Capture](https://user-images.githubusercontent.com/79468263/237028881-5e01ab33-b87e-4414-99cc-d4d65cea7952.PNG)

### Operating System

Windows

### Postman Version

10.13.6-canary01

### Postman Platform

Postman App

### User Account Type

Signed In User

### Additional Context?

[logs.zip](https://github.com/postmanlabs/postman-app-support/files/11428674/logs.zip)

**Comment by malvikach** [comment]
@itay1709 We pushed a few improvements on our latest Canary release (version 10.13.9-canary01) that improves the process and fixes some of these unexpected bugs on Windows. 

I would request you update the app and give this a try again. Please let us know your findings. 

Regards,
Malvika

**Comment by itay1709** [comment]
@malvikach I can confirm that version 10.13.9-canary01 solved that issue that I had, TNX!
