### ISSUE TITLE
HTML Report generation

### ISSUE THREAD

**Issue by Ardour01** [a85/POSTMan-Chrome-Extension#11995]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

After the performance run is completed, there is no way to share the results. 

### Describe the solution you'd like

I would like to have a HTML / XML report generation of the performance test run.

**Comment by malvikach** [comment]
Hi @Ardour01 ,

Thanks for your feedback. 

We have started work on this. Would love to catchup with you to discuss the designs/thoughts on this. If you are intersted, please do drop me a note at malvika.chaudhary@postman.com or you can grab some time on my calendar [here](https://calendly.com/malvika-chaudhary/v10-feedback). 

Cheers!
Malvika

**Comment by malvikach** [comment]
Hi @Ardour01 👋 

Glad to inform you that we have added this as an improvement on the latest Postman release v10.18. You can now export an HTML report for your performance test. 

<img width="1059" alt="Screenshot 2023-09-19 at 11 17 27 AM" src="https://github.com/postmanlabs/postman-app-support/assets/89449769/060fa9a5-40d2-4ae6-b16f-f61e1bc3ccd7">



Thanks again for your feedback in helping us improve the product. 

Cheers!
Malvika

**Comment by FemonZhang** [comment]
I hope there is also an export function under the folder, perhaps I only want to export a folder under this collection
