### ISSUE TITLE
New Integration Request - Azure repo or individual folder

### ISSUE THREAD

**Issue by javedali-dev** [a85/POSTMan-Chrome-Extension#11998]
### Describe your current workflow

We are working as a team and we have one repo that contains all the untouched collections. Once someone from our team is updating the collection we are manually getting it and importing it. 

### Describe your ideal workflow

Once we have updated a collection in a folder or repo there should be a way to automate the import part of it.

**Comment by shashankawasthi88** [comment]
@javedali-dev Postman's native git connections allows you to version control your APIs using Azure Repos. Please refer to this [link](https://learning.postman.com/docs/designing-and-developing-your-api/versioning-an-api/versioning-an-api-overview/) to know more about how can you connect to Azure and push, pull collections.

**Comment by javedali-dev** [comment]
What I understand after going through that link is it is bidirectional commit means all the local changes will also reflect in the remote repo? If yes we don't want it. 
also it would be great to have automation for local folder as well.

**Comment by shashankawasthi88** [comment]
@javedali-dev what is the reason to get the collections in your repos?  Can you go through the workflows once you have collections in repo.
Also I don't understand the point around 'all local changes', you can selectively push what you want to the repo, work in feature branches, etc.
