### ISSUE TITLE
Performance-Preparing to run takes a lot of time to initialize the test

### ISSUE THREAD

**Issue by sseenivasan89** [a85/POSTMan-Chrome-Extension#11992]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

i have select only 2VU and 1 min execution for performance testing and the Preparing to run takes a lot of time in windows desktop app

### Steps To Reproduce

1. Create a collection
2. And run performance test

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/44080743/236607712-ccefdecb-6009-4baf-a9a3-542baf354521.png)

### Operating System

Windows

### Postman Version

10.13.6 Canary

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by malvikach** [comment]
@sseenivasan89 Thanks for sharing the details. This seems like a bug. 

Would request you to share your application logs from the Canary app. You can follow these [steps](https://support.postman.com/hc/en-us/articles/360025298633-How-to-get-logs-from-the-Postman-Desktop-app) to get the logs. 

Please feel free to email the logs on [support@postman.com](mailto:support@postman.com).  

Thanks!
Malvika

**Comment by MoustafaConan** [comment]
I faced the same issue. 

The application takes a lot of time to prepare the running on a windows desktop and can't start sending requests.

**Comment by malvikach** [comment]
Hi @sseenivasan89 @MoustafaConan We have made some optimizations and improvements to the process. The changes are shipped on our latest canary build (version 10.13.9-canary01).

It would be really helpful if you can update the app and let us know if you are still facing the above issue.

We appreciate your feedback. 

Cheers,
Malvika

**Comment by malvikach** [comment]
Hi,

Closing this issue. Please feel free to provide feedback if you still encounter this. 

Thanks again for your feedback. 

Cheers
Malvika
