### ISSUE TITLE
Performance-Ramp up duration accept the negative values

### ISSUE THREAD

**Issue by sseenivasan89** [a85/POSTMan-Chrome-Extension#11993]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

i tried to run the performance test and when I entered the negative value in the Ramp up duration it accept it

### Steps To Reproduce

1. Update the negative value in Ramp up duration

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/44080743/236608345-8b2bd770-33c3-46c2-ad62-61943b3fe580.png)

### Operating System

Windows

### Postman Version

10.13.6 Canary

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by malvikach** [comment]
Hi @sseenivasan89 This bug has been fixed on our latest canary (version 10.13.9-canary01). 

Thanks for reporting this and helping us identify this edge case!

Regards,
Malvika
