### ISSUE TITLE
Body parameters have disappeared in new version/Sync

### ISSUE THREAD

**Issue by JohnnyTripod** [a85/POSTMan-Chrome-Extension#1199]
In all my Collections, the parameters in the Body have all disappeared. All the other data - headers, scripts, tests -  all seem to be there but Postman 3.0 seems to have wiped out my body parameters. Is this a Sync thing? If I restore from a backup, what file(s) do I need to retrieve?

This is frustrating. Have others experienced the same?

Johnny

**Comment by abhijitkane** [comment]
@JohnnyTripod Can you send an email to help@getpostman.com with your Postman username, and the request names for which the body parameters are missing?
