### ISSUE TITLE
Possibility to export Performance Testing results

### ISSUE THREAD

**Issue by beatrixSze** [a85/POSTMan-Chrome-Extension#12009]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

Performance Testing results are only available within the Postman app and can't be exported.

### Describe the solution you'd like

Possibility to export results to a PDF file.

**Comment by malvikach** [comment]
Hi,

We have added this improvement in our latest release Postman v10.18. Users can export performance test reports in an HTML or PDF format. 

Regards,
Malvika
