### ISSUE TITLE
Postman becomes unresponsive with larger flows

### ISSUE THREAD

**Issue by vahtis** [a85/POSTMan-Chrome-Extension#12002]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

After developing flow with 4 send request and some data processing is unable to open flow. Flow contains maybe 30 blocks. Program will open if left running for an hour.
Looking into task manager shows that mem usage peaks to 3 gb and after that it drops to 1.5 gb.

### Steps To Reproduce

Create flow with multiple send requests and data prosessing blocks

### Operating System

Windows

### Postman Version

10.13.0

### Postman Platform

Postman App

### User Account Type

Signed In User

### Additional Context?

Same thing happens in ppostman web too

**Comment by shamasis** [comment]
@vahtis - we've rolled out some upgrades last week. Can you check if your problem still persists?

Are you trying to process large amount of data (a migration or data pipeline of sorts?) Or is it a complex logic with large number of blocks?

@saswatds can you have a look?

**Comment by vahtis** [comment]
This somehow resolved by waiting long enough and then moving one log-block :)
At the moment I not able to reproduce this.
