### ISSUE TITLE
JWT Authentication not working anymore

### ISSUE THREAD

**Issue by giulioprovasi** [a85/POSTMan-Chrome-Extension#1201]
With the last update of postman I cannot add custom Authorization Headers anymore.

If I pick 'no authentication' and adda custom Authorization Header like this:

```
Authorization: Bearer __TOKEN__
```

The header isn't sent.

Am I doing things the wrong way or is this a bug ?

**Comment by abhijitkane** [comment]
I'm not able to reproduce this.

Can you check the console for errors when you send the request? (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/)

**Comment by giulioprovasi** [comment]
Ok, with the debugger, I see that Authorization headers are sent, but when I log the $_SERVER, the Authorization Header isn't there. If I rename the header Authorization_whatever_ it just works, if I add any header, it works, it just doesn't for the _Authorization_ one, it's really weird.

EDIT: here's a screenshot:

![Postman headers](http://img11.hostingpics.net/pics/158366Sanstitre.png)

**Comment by abhijitkane** [comment]
You can send a GET request to http://dump.getpostman.com/get with your Authorization header.
Whatever headers are received by the server will be echoed in the response body.

**Comment by giulioprovasi** [comment]
Ok you are right, the problem seems to come from the PHP framework I'm using (Laravel).

The headers are retrieved from the $_SERVER var and the Authorization one isn't present, but using the getallheaders() method it show up correctly, I'll take a look on the Laravel github for more clues.

Thank you for your help :)

EDIT: My bad, the problem is that I forgot to update my .htaccess with the following rule:

```
RewriteRule ^ - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
```

Therefore the Authorization header wasn't retrieved by the framework
