### ISSUE TITLE
Received email saying VS Code Extension is available for beta, but not letting me sign in via VS Code

### ISSUE THREAD

**Issue by minoseah629** [a85/POSTMan-Chrome-Extension#12010]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

<img width="645" alt="image" src="https://github.com/postmanlabs/postman-app-support/assets/1980068/bece9ce1-4641-464b-856d-bde6e82e710d">

Postman Team - bam-technologies

<img width="232" alt="image" src="https://github.com/postmanlabs/postman-app-support/assets/1980068/fdfde2be-1422-4b8b-946d-94e63a1acd88">

### Steps To Reproduce

1. Install VS Code Extension available in email (not sure if beta link is public)
2. Click Postman extension 
3. Click Sign in on Postman extension
4. Follow Postman browser login process

### Operating System

Windows 11

### Postman Version

10.13.6

### Postman Platform

Other

### User Account Type

Signed In User

### Additional Context?

Postman VS Code extension version v0.1.1

**Comment by pankajk07** [comment]
Hi @minoseah629, the beta VS Code extension is currently only available for non-enterprise users. I suggest creating a new account to try out the experience or waiting for the stable version to be available if you want to log in with your enterprise account.
