### ISSUE TITLE
Time Division in Postman Extension of VS Code

### ISSUE THREAD

**Issue by amirejaz75** [a85/POSTMan-Chrome-Extension#12014]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

There's currently no time division like in VS Code extension like in actual postman app. By hovering over "Time: ### ms", postman app shows the time division like this:
![Screenshot from 2023-05-16 15-23-36](https://github.com/postmanlabs/postman-app-support/assets/37077032/2c871908-b12e-4b2d-8800-f5cd1a43a51b)
But in VS code extension, it shows nothing. I would like to have this feature in VS code extension as well as this helps to get insights of time taken.

### Steps To Reproduce

Open a new request tab
Make any request
Hover over / Click Time next to Status in response part
There's nothing shown while in postman app it shows time division

### Screenshots or Videos

![Screenshot from 2023-05-16 15-23-36](https://github.com/postmanlabs/postman-app-support/assets/37077032/68f6998d-5732-41a6-8550-8fe9bc072b7f)

### Operating System

Linux

### Postman Version

Latest

### Postman Platform

Other

### User Account Type

Signed In User

**Comment by pankajk07** [comment]
Hey @codingamir, we have added the request and response timing graph in the latest version (`v0.2.0`) of the extension. Please update your extension to try out the feature.
