### ISSUE TITLE
Proxy debug session doesn't capture requests during Performance test

### ISSUE THREAD

**Issue by trevor-webster** [a85/POSTMan-Chrome-Extension#12017]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

When running Performance test, a Proxy debug session isn't capturing any requests.

### Steps To Reproduce

1. Go to Capture requests
2. Via Proxy tab, check save responses
3. Start capture
4. Enable proxy port 5555
5. Go to Runner and select collection to run
6. Run Performance test

### Operating System

Windows

### Postman Version

canary

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by agrwl-harsh** [comment]
Hey @trevor-webster, requests doesn't reflect in the proxy session because currently the load testing tool doesn't honor the proxy settings. We have it on our radar and will be adding capability to honor proxy settings in our load testing tool. We will keep this thread updated.

**Comment by malvikach** [comment]
hey @trevor-webster This issue should be resolved now (on the latest Postman version v10.17.1), please let us know if you are still facing any problems with it. 

Thanks again for your feedback!

Cheers
Malvika
