### ISSUE TITLE
Enable Two-Pane Toggling in VSCode

### ISSUE THREAD

**Issue by mrehanabbasi** [a85/POSTMan-Chrome-Extension#12013]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

The default two-pane view in the VSCode extension is "top and bottom". However, I want it to be side-by-side.

### Steps To Reproduce

1. Open a new request tab

### Operating System

Windows

### Postman Version

v0.1.1

### Postman Platform

Other

### User Account Type

Signed In User

**Comment by pankajk07** [comment]
Hey @mrehanabbasi, we have added the ability to switch between top-down or side-by-side layouts for HTTP requests in the latest version (v0.3.0) of the extension. 
Please update your extension to try out the feature.

**Comment by Quenix** [comment]
Hello, mate

While this option isn't provided I did some workaround I will share with you in case you are interested. Basically you gotta edit extension minified code.

## Step 1:
Open your VS Code extensions folder.
- Windows %USERPROFILE%\.vscode\extensions.
- macOS ~/.vscode/extensions.
- Linux ~/.vscode/extensions.

## Step 2:
Locate and open your Postman DIST folder in VS Code

## Step 3:
Try searching for "Two Pane View" and it may take you directly to the code you want.

## Step 4:
Unminify the code, user whatever it pleases you. Then you might find this portion of code, on mine it is already modified to "horizontal", but in yours should be "vertical". Just swap, save and reload VS Code. All good now!
<img width="375" alt="image" src="https://github.com/postmanlabs/postman-app-support/assets/12365990/f3e5e324-6b07-43e0-bb5e-b57ead70cacd">


I hope that helps you, it was reaaaally bothering me.
