### ISSUE TITLE
Rapid React - Just got in the Preview Today...after enrolling for early access on 4/3/23. 

### ISSUE THREAD

**Issue by homeaidepi** [a85/POSTMan-Chrome-Extension#12011]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

Rapid Reaction:  Collections and Environments both are in "coming soon". Sad day. Right now it shows history of calls (which I've never really used [forgot that was a thing], only really used "collections" in Postman workspace previously)  

It has 'New HTTP Request' button which is clunky imo cause it could be a HTTP(S) request we wind up making. Just call the button "New Request"  
Also no </> button?? Really... In VSCode???  

Well we use Postman to write code right??  With it integrated in the IDE and no ability to use collections or export to code its basically useless.  Sorry not sorry.  

### Describe the solution you'd like

Just call the button **"New Request"** We're aware of what type of request we're making.   Besides that nice to have the Postman IDE tab in vscode there is no </> code button on the right hand side like you get in Postman IDE to easily create a curl or some code implementation example like JavaScript with axios is a big miss.   Perhaps I'm just missing how to do it within this interface without the </> icon and pop out but a big miss and a major purpose of being in a Dev IDE.  

People tend to use Postman to write API code right??  Welp, with it integrated in the IDE and no ability to use collections or export to a basic code representation its basically useless.

### Additional context

Still gotta ways to go imo, but nice to see something is coming along.  I'll highlight the inclusion of 'Pre-request' script is a nice touch, in the VS extension, so you all are close to "code" related features    Also the early access looked identical to PostMan ide but in VSCode.  The new ui is categorized differently so you may need to be more transparent with what folks should expect and use real VSCode screen shots and not early idea renderings.

**Comment by pankajk07** [comment]
@homeaidepi 
We recently released a new update with support for generating code from the request, Collections, and Environment variables. Do check it out and let us know what you think.
