### ISSUE TITLE
Public workspaces are not available in the VS Code extension

### ISSUE THREAD

**Issue by andreea-qa** [a85/POSTMan-Chrome-Extension#12012]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

The public workspaces can not be selected when working with the VS Code extension

### Steps To Reproduce

Preconditions:
Have a Postman account with at least one public workspace. Install the Postman extension in VS Code.

1. Log in to the Postman VS code extension with the account from preconditions
2. Open the Workspaces drop-down

Expected results:
All workspaces are available for selection

Actual result:
Only the private and team workspaces are displayed

### Operating System

Windows 10

### Postman Version

Postman VS extension 0.1.1

### Postman Platform

Other

### User Account Type

Signed In User

**Comment by pankajk07** [comment]
Hi @andreea-qa, thanks for trying out the extension. Currently, we only support loading personal and team workspaces. Eventually, we will provide the ability to load other types of workspaces in future releases.

**Comment by Ntlneo** [comment]
@pankajk07 Please add a note on Workspace section in Postman extension for user know currently Postman only support personal and team workspace

**Comment by theshubhamjoshi** [comment]
Hello @andreea-qa, this issue is now fixed in the latest update of the Postman VSCode extension. Please update to version 0.5.4 to use this feature. Thank you for your patience!
