### ISSUE TITLE
curl code generation should quote URL

### ISSUE THREAD

**Issue by cvmocanu** [a85/POSTMan-Chrome-Extension#1202]
The generation of the curl request does not quote the URL.
This causes problems if the URL contains query parameters because bash interprets the ampersand as the end of one command and the beginning of another.

The URL should be quoted, preferably using single quotes (to makes sure bash doesn't interpret anything).

**Comment by abhijitkane** [comment]
We'll be pushing a fix for this in the next release. Also referenced here - https://github.com/postmanlabs/postman-app-support/issues/1161
Closing this

**Comment by cvmocanu** [comment]
cool, thanks
