### ISSUE TITLE
Favicon for documentation is not working in paid plan (Previous issue has been closed without resolution)

### ISSUE THREAD

**Issue by georgepadayatti** [a85/POSTMan-Chrome-Extension#12038]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

On publishing the documentation in paid plan, the documentation page still uses postman favicon, even when another favicon is configured in Team settings.

[iGrant.io Developer Documentation](https://developer.igrant.io) still uses postman favicon. This is not acceptable in paying plan.

After some checks found that postman favicon is added on top of team favicon.

```html
// postman favicon
<link rel="shortcut icon" href="https://documenter-assets.pstmn.io/favicon.ico">
// team favicon
<link rel="shortcut icon" href="https://res.cloudinary.com/postman/image/upload/v1591948698/team/w51bfdgdh3vjbvrwtyma.ico">
```

So the website is taking the first one over the other.

### Steps To Reproduce

1. Upload custom favicon in Team settings
2. Publish collection documentation
3. Published website still uses postman favicon

### Screenshots or Videos

<img width="1385" alt="Screenshot 2023-05-20 at 9 49 43 AM" src="https://github.com/postmanlabs/postman-app-support/assets/16397960/4cdea21c-b299-4ebd-b176-88f5d4513381">

### Operating System

macOS

### Postman Version

10.14.2

### Postman Platform

Both

### User Account Type

Signed In User

### Additional Context?

Paid user

**Comment by ekansh-001** [comment]
Hey [georgepadayatti](https://github.com/georgepadayatti),

Apologies for the inconvenience you might have faced. I have tested the flow and it is working as expected.
I have attached the screen shot for your document that is showing the custom favicon. 
<img width="1440" alt="Screen Shot 2023-05-23 at 10 53 55 AM" src="https://github.com/postmanlabs/postman-app-support/assets/98813517/9b17412f-2bd0-40aa-bd7f-c09a3599b949">

Please let us know in case you need any other assistance from our side :bow:
