### ISSUE TITLE
Postman Run Results Color Indication not shown for Request Type PATCH and OPTIONS

### ISSUE THREAD

**Issue by SciTechEnthusiast** [a85/POSTMan-Chrome-Extension#12039]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

- Run a postman collection with requests type patch and options
- Color indicators for request type patch and options are missing in run collection results

### Steps To Reproduce

1. Open Postman
2. Create new collection
3. Add requests with types patch and options
4. Run collection 
5. Check for the color coding in the run result

### Screenshots or Videos

![image](https://github.com/postmanlabs/postman-app-support/assets/74421740/f60d606e-6169-4c5e-a23b-6808ade38ff8)
![image](https://github.com/postmanlabs/postman-app-support/assets/74421740/4774a12f-4bb4-43f7-91c6-9bab9327be54)

### Operating System

Windows

### Postman Version

11

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by giridharvc7** [comment]
@SciTechEnthusiast , thanks for reporting this bug. We'll keep you posted on this.

**Comment by sandeep-singh-pstmn** [comment]
I'm closing this, the problem has been fixed.

<img width="852" alt="Screenshot 2023-07-12 at 6 26 46 PM" src="https://github.com/postmanlabs/postman-app-support/assets/85243040/804fe000-dff7-44da-828b-2f62b7c70dfe">
