### ISSUE TITLE
Postman Flow Give "Unexpected token y in json at position 0" for a request which doesn't return json body

### ISSUE THREAD

**Issue by pavitrajain18** [a85/POSTMan-Chrome-Extension#12035]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Scenario: Create Postman flow with concatenating multiple send requests which doesn't return json response body

Expected Result: Should be able to run the postman flow

Actual Result: Getting "Unexpected token y in json at position 0" error for the first request even though response status is 200.

### Steps To Reproduce

1. Create New Flow with concatenating multiple send request block using api which doesn't return json response body
2. Click Run to start the flow
3. Get "Unexpected token y in json at position 0" on flow even though console show to no error and response received for request is 200 OK

### Screenshots or Videos

![Flow Issue](https://github.com/postmanlabs/postman-app-support/assets/101123793/bc530dac-651e-4700-bb49-4b36349ed9cc)

### Operating System

macOS

### Postman Version

10.14.3

### Postman Platform

Postman App

### User Account Type

Signed In User

### Additional Context?

Issue happen for request that doesn't return json response body. Instead returns a text

**Comment by vahtis** [comment]
Yes this one is really annoying. I have a flow with GET, PUT and DELETE. They should be run in series GET, DELETE and PUT, but I have to run PUT and DELETE in parellel for my flow to work.

**Comment by saswatds** [comment]
Hi @pavitrajain18 @vahtis, could you let me know what the value of the response `Content-Type` header is?

**Comment by vahtis** [comment]
@saswatds after checking error in mine is bit different, but the problems stays same.
![image](https://github.com/postmanlabs/postman-app-support/assets/10445226/52625b76-8ae8-4bfa-b733-662d800bf750)
And here is the response
![image](https://github.com/postmanlabs/postman-app-support/assets/10445226/45e126fa-664e-4289-bcb1-5fae8abfac4d)
Response code is 204

**Comment by saswatds** [comment]
@vahtis I see what is happening. The content-type is indeed `application/json` but the body is absolutely empty, therefore the block is crashing trying to parse an empty response. I will make sure we handle this edge-case in the next release.

**Comment by pavitrajain18** [comment]
@saswatds here is the response header in my case:
![image](https://github.com/postmanlabs/postman-app-support/assets/101123793/1eb16f44-f866-453e-8693-c20c990d117b)

**Comment by saswatds** [comment]
@pavitrajain18  Got it. And is the response a valid json? You can use this website to verify https://jsonlint.com/.

**Comment by pavitrajain18** [comment]
@saswatds no response is text
![image](https://github.com/postmanlabs/postman-app-support/assets/101123793/7432ead3-760b-4408-a9a2-447303ac9d80)

**Comment by saswatds** [comment]
Ohk. This seems to be the issue. Your `content-type` header is suggesting that the body is JSON, but in fact it is text. In the `Auto` mode, flow tries to parse your body based on the content-type and it is rightly failing with `Unexpected token y in json at position 0`. Not to worry, we have seen this kind of mistakes and inconsistencies in a lot of API. Until someone fixes the content-type, you can set the `Body Type` setting to `Text` to let flow know that it should not use the content-type to auto parse.

**Comment by pavitrajain18** [comment]
@saswatds i started facing this issue again recently..may be with new update of postman.
As i mentioned earlier, i have api which is returning text instead of json. To fix postman flow i updated the API configuration in flows for body type as text. Even then, i am getting "Unexpected token y in json at position 0" error
here is the screenshot:
![image](https://github.com/postmanlabs/postman-app-support/assets/101123793/083fe4fd-3a70-486f-b98b-89c4d73f28a5)

**Comment by saswatds** [comment]
@pavitrajain18 Thanks for reporting, I will take a look at what has changed.

**Comment by Cackerman55** [comment]
I’m running into the issue identically after trying the above workarounds and setting the Body type to Text. And even though the request response is 200 and successful, the request block stops and prevents further progress in the flow.

is there any update on this issue being resolved? Or is there a workaround in the meantime?

**Comment by rabbah** [comment]
As far as we can test, this is fixed. If there's a specific failing scenario that can be provided as a test (API or Mock endpoint, and flow) we can turn it into a test case.
