### ISSUE TITLE
App: Export collection does not produce file (macOS)

### ISSUE THREAD

**Issue by gingerbeardman** [a85/POSTMan-Chrome-Extension#12037]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Exporting a collection does not produce a file.

Nothing happens after clicking the Export button.

### Steps To Reproduce

1. Create a collection
2. Choose ... > Export menu items
3. Click Export button

Expected
- file should download or prompt to accept download

Actual
- nothing happens

### Screenshots or Videos

![image](https://github.com/postmanlabs/postman-app-support/assets/49612/d8c04c32-d785-4769-89e7-e73b4ab4a81c)

### Operating System

macOS

### Postman Version

12.6.6

### Postman Platform

Postman App 10.14.4

### User Account Type

Signed In User

### Additional Context?

- I had to use the web version in Safari to export my collection

**Comment by giridharvc7** [comment]
Can you please share console logs for this at support@postman.com?

**Comment by gingerbeardman** [comment]
My app just updated to 10.14.4 and now all is well.

Apologies for the false alarm.

I'll keep an eye on it.
