### ISSUE TITLE
Feature Request: Add Support for JSON Vulnerability Protection

### ISSUE THREAD

**Issue by blowsie** [a85/POSTMan-Chrome-Extension#1203]
It would be great if you could add support in for the JSON Vulnerability Protection, as detailed here;
https://docs.angularjs.org/api/ng/service/$http#json-vulnerability-protection.

This support would only be required for the "Pretty View"

I have and use several APIs which implement this, and whilst the request works in post man, It renders like this in JSON view;
![image](https://cloud.githubusercontent.com/assets/308572/8457288/6f64c408-2008-11e5-915f-1c7b6c13802a.png)

Perhaps you could place a small test to see if the string starts with `)]}',\n` ?

Thanks.

**Comment by abhijitkane** [comment]
What version of Postman are you using? 

If you're on 3.0.1, can you send include a sample response which produces this output?
If not, you can try upgrading by going to chrome:/extensions, enabling 'Developer Mode', and clicking 'update extensions now'.

The latest pretty view supports common Anti-XSS prefixes including `while(1);` and `}];`

**Comment by blowsie** [comment]
Thanks for the quick response, I am using 3.0.1.

Here is the example response

```
)]}',
[0,1,2]
```

As said in the question, the angular core uses the prefix `)]}',\n`

Thanks

**Comment by blowsie** [comment]
Just out of curiosity, how long does something like this normally take to be implemented and released?
This is the only thing currently stopping me buying a licence so I can use postman as a testing tool.

**Comment by a85** [comment]
@blowsie We are aiming to be super quick with both our release cycles as well as our ability to reply to comments/issues/requests/questions. :)

**Comment by blowsie** [comment]
Interestingly, I just noticed this is working for some of my requests, but not all.

It seems this works

```
)]}',
{"hello":"world"}
```

Whilst this does not.

```
)]}',
[0,1,2]
```

**Comment by abhijitkane** [comment]
@blowsie The latest version supports Angular's anti-XSS prefixes. Can you confirm?

**Comment by blowsie** [comment]
I can confirm this is working on version 3.0.4, windows.

Thank you very much!
