### ISSUE TITLE
Oauth2 exception "debug" URL is invalid

### ISSUE THREAD

**Issue by james12150** [a85/POSTMan-Chrome-Extension#1204]
I get a "To debug" URL from Postman which points back to a Postman server.  I am told to view the error response via the URL but the response I get in browser is - This webpage has a redirect loop.  

Any ideas what is happening here?

**Comment by abhijitkane** [comment]
Can you send the URL in question to help@getpostman.com?

**Comment by james12150** [comment]
Abhijit,

I’m using Postman 2.

I get the red box saying it “Could not initiate OAuth 2 flow”.  Here is the debug URL – 

 https://www.getpostman.com/oauth2/start?authorization_url=%20&access_token_url=%20&client_id=724abce1-491c-4e69-b295-b04f8ca81045&client_secret=12c6a344-db7b-40a9-b82d-c90f951370cd&scope=&app_id=fhbjgbiflinjbdggehcddcbncdddomop https://www.getpostman.com/oauth2/start?authorization_url=%20&access_token_url=%20&client_id=724abce1-491c-4e69-b295-b04f8ca81045&client_secret=12c6a344-db7b-40a9-b82d-c90f951370cd&scope=&app_id=fhbjgbiflinjbdggehcddcbncdddomop

IE says “This page can’t be displayed”

Chrome says “This page has a redirect loop”.

Thanks for your help.

James

**Comment by abhijitkane** [comment]
What are the authorization and access-token URLs that you're using? If possible, we'll try to use the same OAuth provider and try to reproduce the problem.

**Comment by ghalpert** [comment]
We are experiencing the same problem. How can we solve this?

**Comment by abhijitkane** [comment]
@ghalpert Can you send a screenshot of the OAuth2 screen? (you can fill in garbage values for the client key and secret)

The debug URL you are shown would also help.

@james12150 In your debug URL, the Authorization URL and Access Token URL are empty. Are you sure you're entering them correctly?

**Comment by ghalpert** [comment]
Thanks for the quick response. I'll only be able get that for you tomorrow as the problem is with an associate overseas and she's gone for the day. She is using Chrome under Windows 8 (8.1?). All works well for me, but I'm using OS X.

**Comment by ghalpert** [comment]
We resolved the issue. OAuth2 information was not configured correctly.
