### ISSUE TITLE
Postbot: Error generating tests with prompt

### ISSUE THREAD

**Issue by vdespa** [a85/POSTMan-Chrome-Extension#12049]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Postbot is not generating any tests. Instead, an error appears:

<img width="425" alt="Screenshot 2023-05-24 at 08 33 01" src="https://github.com/postmanlabs/postman-app-support/assets/1197635/e3b8febb-f963-4153-8a83-e27f46a33c47">

### Steps To Reproduce

1. Open Postbot.
2. Inset a prompt: "Write a status code test using pm.expect. "
3. Click on the play button.
4. The error appears after a few seconds.

### Operating System

macOS

### Postman Version

Web

### Postman Platform

Postman Web

### User Account Type

Signed In User

**Comment by abhijitkane** [comment]
Thanks for reporting this @vdespa. We're looking into a few of the failures we saw. Were you eventually able to get this to work?

**Comment by vdespa** [comment]
@abhijitkane It worked only once but after many attempts. However, the suggested prompt "Test for response..." worked with no issues.

**Comment by SterlingChin** [comment]
@vdespa we've made significant improvements to our AI service that were shipped this week. Can you try again and let us know if you're still having issues?

**Comment by vdespa** [comment]
@SterlingChin 

Are these updated made in Postman app version 10.14.9 or do I need to use something else?

**Comment by SterlingChin** [comment]
Yes, the performance updates are in `v10.14.9`. 😄

**Comment by vdespa** [comment]
I am still getting an error when asking to generate a JSON schema.

<img width="435" alt="image" src="https://github.com/postmanlabs/postman-app-support/assets/1197635/38099068-9096-4fa6-990a-0b56b5078b74">

**Comment by SterlingChin** [comment]
Can you provide (if possible) the endpoint or the response schema that you're trying to generate the test for? With the performance updates, there have been a sharp decline in failing test generation, so this may not be related performance. I'm happy to get on a call with you as well.

**Comment by sagarpandyawk** [comment]
Getting same error in  v10.19.15-canary01

**Comment by kylerRenneker** [comment]
@vdespa @sagarpandyawk 

Hello folks! The Postbot team has been working diligently to improve the feature and solve some of these issues. 

If possible, please update your app to the latest app version (v11.x.x). If your on web you should be getting the latest version. 

All of the problems discussed in this issue should be addressed and work as expected for any HTTP request that returns JSON data. 

We look forward to your continued support, usage & feedback of Postbot and its ever expanding feature set! 

Cheers!
