### ISSUE TITLE
Export collection: texts in save file window is not understandable in ubuntu

### ISSUE THREAD

**Issue by birendragurung** [a85/POSTMan-Chrome-Extension#12058]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

When exporting a collection, a window opens to select path to save file. The texts are not recognizable as shown in the attached image.

### Steps To Reproduce

1. On any collection, right click to open menu
2. In the menu, select `Export` which opens a dialog, then click on `Export`

### Screenshots or Videos

![Screenshot from 2023-05-29 15-33-30](https://github.com/postmanlabs/postman-app-support/assets/13505748/addb6f55-60c3-41e8-ad6e-c3391b52fb01)

### Operating System

Linux (Ubuntu 23.04)

### Postman Version

10.14.6

### Postman Platform

Postman App

### User Account Type

Signed In User

### Additional Context?

Postman for Linux

Version 10.14.6

UI Version 10.14.6-ui-230526-0640

Desktop Platform Version 10.14.2

Architecture x64

OS Platform linux 6.2.0-20-generic

**Comment by birendragurung** [comment]
Found a working solution in another issue: https://github.com/postmanlabs/postman-app-support/issues/10688

**Comment by marcandreuf** [comment]
I have the same issue. 


![Image](https://github.com/user-attachments/assets/98f44f3c-28de-4728-a94a-498493be385e)


Operating System
Ubuntu 24.04.2 LTS

Postman Version
Postman for Linux

Version 9.31.30

UI Version 9.31.30-ui-230929-1316

Desktop Platform Version 9.31.30

Architecture x64

OS Platform linux 6.8.0-60-generic

**Comment by igorpupkinable** [comment]
@marcandreuf 

1. Uninstall Postman snap completely
2. Follow [these](https://github.com/postmanlabs/postman-app-support/issues/10688#issuecomment-3384976027) instructions
3. Restart Ubuntu 24 LTS
4. Install **latest** Postman snap (v11.71.7)
5. Open Postman v11 and go to File > Settings
6. Find Location/Workfolder path and click _Choose_. This will trigger fonts cache generation. It will take some time for dialog to open occasionally asking for Terminate or Wait. Keep clicking _Wait_.
7. File open dialog should finally open with correct font and readable text.
8. Close Postman
9. Switch snap channel to v9/stable and install v9.31.30 back.

I could not get it working by skipping step 4 on Ubuntu 24 LTS no matter what I tried.
