### ISSUE TITLE
postman vs code extension:- view request and response side-by-side in postman vs code extension

### ISSUE THREAD

**Issue by sandeeptessell** [a85/POSTMan-Chrome-Extension#12055]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request and I know that duplicates will be closed

#### Postman vs code extension:-
 The request and response viewing panes are part of a vertically scrollable area but I'd rather view the request and response side-by-side, the request on the left and the response on the right.

#### Postman vs code extension:-
 The request and response viewing panes are part of a vertically scrollable area but I'd rather view the request and response side-by-side, the request on the left and the response on the right.

**Comment by kamalaknn** [comment]
@sandeeptessell Thanks for the feedback. We are tracking support for two pane layout within the Postman VS Code extension in #12013 

We are working on this, and will be available to use very soon.
