### ISSUE TITLE
Edit request name

### ISSUE THREAD

**Issue by Rychard** [a85/POSTMan-Chrome-Extension#1205]
Is there some way to _directly_ edit the field shown in the screenshot below?  The request shown was created by duplicating an existing request within a collection.  

![image](https://cloud.githubusercontent.com/assets/2145848/8484171/2c1a2da2-20c4-11e5-8a85-bf22612a4594.png)

As far as I can tell, here's the only way to do it:
![image](https://cloud.githubusercontent.com/assets/2145848/8484256/9b25669e-20c4-11e5-9b54-f02cf3d93d3a.png)

![image](https://cloud.githubusercontent.com/assets/2145848/8484271/af070c8a-20c4-11e5-9fe6-339b215ba47c.png)

To avoid any potential of an "XY Problem", I would like to specify the name of a duplicated request immediately upon duplication.  It would be ideal if I could I would be asked to supply a name for the duplicate rather than it using `<name of existing request> copy`

**Comment by abhijitkane** [comment]
We'll be introducing in-place editing soon. This will enable editing inside the yellow area marked in the first screenshot.

**Comment by Rychard** [comment]
What about the possibility of editing names directly in the left-pane as well?  

![image](https://cloud.githubusercontent.com/assets/2145848/8501448/72d72088-2173-11e5-8b95-77606f4edc73.png)

There are instances where I would have found this very useful; although, I don't think it's asking too much from the user to require that they edit it from the right pane.

I can't imagine that the process of renaming a request is important enough to justify so many entry points, _but_ this may indirectly result in some other usability improvements to the request list (right-click context menu, perhaps?), which I'm definitely in favor of.

**Comment by miguelfc** [comment]
After using Postman repeatedly over the last weeks, this has become a must for me. Too many clicks right now to change a name. Thanks!

**Comment by jhasselkus** [comment]
Unless I'm missing something, there also doesn't seem to be _any_ way to rename a request with name so long that it exceeds the width of the left-hand panel. The little 3-dots in a circle menu prompt won't show in that case.

**Comment by Rychard** [comment]
@jhasselkus Well, from what I see there are a couple alternatives.

Open the Details panel for the collection by clicking the <kbd>&rarr;</kbd> button. to the right of the collection's name.
![image](https://cloud.githubusercontent.com/assets/2145848/12855020/fe27e6bc-cc0a-11e5-82e0-f5b39d1688a0.png)

On this panel you can see _more_ of the title
![image](https://cloud.githubusercontent.com/assets/2145848/12855071/61c47cc6-cc0b-11e5-8b81-1b9425305d29.png)

Hovering over the request will allow you access to the edit command,even when the title is very long.

![image](https://cloud.githubusercontent.com/assets/2145848/12855082/7469a4a0-cc0b-11e5-930b-0ea5be0f9e0f.png)

![image](https://cloud.githubusercontent.com/assets/2145848/12855124/9d2c8bf0-cc0b-11e5-8e14-e4116ab687af.png)

**HOWEVER**

If the name of your collection is too long, good luck...

![image](https://cloud.githubusercontent.com/assets/2145848/12855170/dc0e3436-cc0b-11e5-9371-a816fa992639.png)

Edit: I still can't figure out how to edit the name of the collection I gave the long name to.  I tried increasing the width of the panel on the left, but it seems to have a hard-limit.

**Comment by jhasselkus** [comment]
@Rychard Ah, thanks for the workaround!

**Comment by grifx** [comment]
@Rychard Thanks!

**Comment by stepharr** [comment]
@abhijitkane Is this feature still coming soon?

**Comment by a85** [comment]
@theonestep4 Yep. On our roadmap.

**Comment by vegetableman** [comment]
Closing this, since the current release `4.10` supports inline editing of request names.
