### ISSUE TITLE
VS Code Extension: Can't sign in, receiving: "Storing the account data in the secret storage failed"

### ISSUE THREAD

**Issue by terryaney** [a85/POSTMan-Chrome-Extension#12056]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Trying VS Code extension...after logging in (trusting postman domain) I get 'Storing the account data in the secret storage failed' when I allow extension to open VS code or if I manually paste the token in.  Suggestions?

### Steps To Reproduce

After login, the extension log is:

> (2023-05-27T20:02:16.239Z) [info] [extension] Extension activation started: 1685217736236
> (2023-05-27T20:02:16.269Z) [info] [extension:secretManager] No account data was found
> (2023-05-27T20:02:16.271Z) [info] [extension] Extension activation completed: 1685217736271
> (2023-05-27T20:02:16.271Z) [info] [extension] Extension activation took 35ms
> (2023-05-27T20:02:16.279Z) [info] [extension:sidebar:adapter] fetching a correct html for the view mode: {"viewMode":"login"}
> (2023-05-27T20:02:16.298Z) [info] [extension:secretManager] No account data was found
> (2023-05-27T20:02:17.927Z) [info] [extension:sidebar:manager] set login state to busy
> (2023-05-27T20:02:17.928Z) [info] [extension:auth] Starting the login flow
> (2023-05-27T20:02:24.414Z) [info] [extension:auth] Handing the URL redirect to VSCode
> (2023-05-27T20:02:24.415Z) [info] [extension:auth:client] finalising the auth handover
> (2023-05-27T20:02:24.722Z) [info] [extension:auth] The sign in flow has finished successfully
> (2023-05-27T20:02:24.751Z) [info] [extension:secretManager] No account data was found
> (2023-05-27T20:02:25.289Z) [error] [extension:secretManager] Saving the account data as failed: {"error":{"name":"Error","message":"Not enough memory resources are available to process this command.\r\n"}}
> 

### Operating System

Windows

### Postman Version

0.1.1

### Postman Platform

Other

### User Account Type

Signed In User

**Comment by pankajk07** [comment]
Hi @terryaney, thanks for sharing the logs. Based on the log, it seems that vscode is facing some issues while storing the credentials in the keychain. The VS code troubleshooting guide has a resolution for this issue as mentioned here https://code.visualstudio.com/docs/editor/settings-sync#_windows. 

Can you please try out the steps mentioned in the guide and see if this resolves the issue?

**Comment by AlirezaMoVali** [comment]
> Hi @terryaney, thanks for sharing the logs. Based on the log, it seems that vscode is facing some issues while storing the credentials in the keychain. The VS code troubleshooting guide has a resolution for this issue as mentioned here https://code.visualstudio.com/docs/editor/settings-sync#_windows.
> 
> Can you please try out the steps mentioned in the guide and see if this resolves the issue?

Hey
I had the same issue on Windows and deleting VScode credentials helped. In my case, VSCode has generated a lot of credentials to sync with my Microsoft account.

**Comment by terryaney** [comment]
Yes, this worked.  Thanks.
