### ISSUE TITLE
Opening an older version of the backup file overwrites current data 

### ISSUE THREAD

**Issue by onlyis** [a85/POSTMan-Chrome-Extension#12067]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

I was really shocked by Postman's design. I updated the new version and saw that there was still an old version in the root directory. So I opened the old version, but Postman didn't make a judgment and directly used the old version as a backup for the new version. The backup here is the old version with empty data, which caused me to directly lose all the data. Oh my god, this, I am completely devastated and will no longer use Postman. All the data has been lost, and the design is so frustrating and amazing

### Steps To Reproduce

I was really shocked by Postman's design. I updated the new version and saw that there was still an old version in the root directory. So I opened the old version, but Postman didn't make a judgment and directly used the old version as a backup for the new version. The backup here is the old version with empty data, which caused me to directly lose all the data. Oh my god, this, I am completely devastated and will no longer use Postman. All the data has been lost, and the design is so frustrating and amazing

### Screenshots or Videos

1

### Operating System

win

### Postman Version

10.12.0

### Postman Platform

Postman App

### User Account Type

Signed In User

### Additional Context?

1

**Comment by preethammavin** [comment]
@onlyis if you have signed-in account, do check by signing-in the web. Your data should be backed onto the cloud. In which case you should be able to sign-out and sign back in to access your data. Can you reach out to us at help@postman.com so that we can take a deeper look

**Comment by onlyis** [comment]
its really a pity,and i alway use it offline ,but now my data all lost,because update dont delete older version,and i just try it,you destroyed my week,ohh i dont know how to say,i so pity

**Comment by onlyis** [comment]
=

**Comment by preethammavin** [comment]
@onlyis - if you are using it in a signed-out manner, you can write to our support, and we can try to see if you can find a backup file on your system.

**Comment by onlyis** [comment]
why can't you just say in this,why trouble to write a mail?
