### ISSUE TITLE
The new version 10.12 actually hides all the export functions. Postman, you are really disgusting

### ISSUE THREAD

**Issue by onlyis** [a85/POSTMan-Chrome-Extension#12068]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

The new version 10.12 actually hides all the export functions. Postman, you are really disgusting

### Steps To Reproduce

The new version 10.12 actually hides all the export functions. Postman, you are really disgusting

### Screenshots or Videos

The new version 10.12 actually hides all the export functions. Postman, you are really disgusting

### Operating System

win

### Postman Version

10

### Postman Platform

Postman App

### User Account Type

Signed In User

### Additional Context?

The new version 10.12 actually hides all the export functions. Postman, you are really disgusting

**Comment by preethammavin** [comment]
@onlyis Postman collections and environments are exportable on 10.12 and above. You can access them inside the workspace across all collections.

**Comment by onlyis** [comment]
no on settings data button ,now its not exist,but exist below 10.12

**Comment by onlyis** [comment]
no on settings button and it's --->data button ,now its not exist,but exist below 10.12
---> setting button ----> data button
now only import but no export
