### ISSUE TITLE
Editing request name does not update tab

### ISSUE THREAD

**Issue by Rychard** [a85/POSTMan-Chrome-Extension#1206]
During the process of creating issue #1205, I noticed this.
### Steps to reproduce:
1. Create a collection
2. Add request to the collection.
3. Ensure that the request is open in the right pane, and that its tab is active.
4. Hover over the request in the left pane, and select `Edit` from the context-menu.
   ![image](https://cloud.githubusercontent.com/assets/2145848/8484624/9fc40906-20c6-11e5-9e5f-0593886eed1a.png)
5. Change the name of the request.
6. The name of the tab does not reflect the new name.
   - Navigating between any other open tabs _will_ update the displayed name.
   - Clicking the `+` icon to create a new tab _will not_ update the displayed name. 

![image](https://cloud.githubusercontent.com/assets/2145848/8484536/50dfd73e-20c6-11e5-93e4-e8a35db196c6.png)

**Comment by abhijitkane** [comment]
Thanks for reporting this - we'll fix this in the next release.
