### ISSUE TITLE
Add pre-request-script when exporting the json Collection v2.0 API

### ISSUE THREAD

**Issue by kane1997** [a85/POSTMan-Chrome-Extension#12061]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

I just tried exporting the collection v2.0.

In each of my API request, I have a common or diff pre-request-script, but when I export that and import into a diffirent account of postman, I have to add the pre-request-script one by one.

My pre-request-script are some codes to produce signature. Only if I have signature that I can request the API.

### Describe the solution you'd like

Hope the json file can contain the pre-request-script

**Comment by giridharvc7** [comment]
The collection json does have the pre-request and test scripts as a part of it. Can you send a recording of your workflow? This will help us drill down to the issue.

**Comment by giridharvc7** [comment]
@kane1997 Can you please confirm if this is working for you?

**Comment by giridharvc7** [comment]
Closing this for now, feel free to open it back in case you see this problem persisting.

**Comment by trevorpageeaton** [comment]
I have experienced the same problem. Specifically, when exporting my collection in 2.1 format, the resulting json file did not contain any of my pre-request scripts.

The solution for me hit the 'Save' button (perhaps on the individual request(s) where script has been added/edited) prior to performing the export!

This feels a bit of a "well, duh!" thing to write, but there we go.
