### ISSUE TITLE
Set environment variables as secrets and hide their value

### ISSUE THREAD

**Issue by EvertonMJunior** [a85/POSTMan-Chrome-Extension#12063]
### Is there an existing request for this feature?

- [x] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

In today's home-office world, we are constantly sharing our screens with coworkers, clients and other people. And sometimes the need to change some environment variable comes during those meetings. The problem is, a lot of times variables are sensitive information, and having them showing in plain text right after you open the variables tab or environment tab is a really problematic thing. It's a bummer having to disable columns from showing, or stopping sharing the screen to modify some variable.

### Describe the solution you'd like

It's as simple as allowing to hide a variable's value. You know when you are typing a password and you can't see what's typed at first sight? It's the same idea. Allowing a hide/view button on variables with a persisted state. This way people could hide their secrets, and easily access variables tab without worrying someone might screenshot their screen and get sensitive info.
![image](https://github.com/postmanlabs/postman-app-support/assets/51867881/6346dc9a-aff9-4eb0-a4ab-906873ae3c41)
![image](https://github.com/postmanlabs/postman-app-support/assets/51867881/7c32c3cc-70e6-4ef8-a7ca-68a3c3904b4c)

### Describe alternatives you've considered

Instead of having a button, secure values could only be shown when the input is focused, as happens on AWS Parameter Store.
Unfocused:
![image](https://github.com/postmanlabs/postman-app-support/assets/51867881/6b267190-87f4-4d0a-8efc-5d22b19d07ab)
Focused:
![image](https://github.com/postmanlabs/postman-app-support/assets/51867881/e1a6b96a-3f19-44f9-963f-6db41ee0ef49)

### Additional context

Another parallel is Streamer Mode, on Discord. It hides sensitive info automatically when it detects you are running OBS, for example.

**Comment by preethammavin** [comment]
@EvertonMJunior, you can set a variable to type secret, which masks the values. You can choose to display the variable by triggering against that single variable. You can read more about it [here](https://blog.postman.com/introducing-secret-variable-type-in-postman/)

**Comment by EvertonMJunior** [comment]
Wow, thanks for the fast reply @preethammavin ! Really glad this exists, hadn't seen it 🫠
Thank you!
