### ISSUE TITLE
Editing description of a collection or folder doesn't count as modification causing lose of edit

### ISSUE THREAD

**Issue by zhaowb** [a85/POSTMan-Chrome-Extension#12072]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Currently in Postman, when click on a request or collection or folder, it first shows in italics font to indicate view only, then if click on another one without modification, the 'view only' tab is reused.
Problem is editing description of a collection or a folder seems not count as 'modification' that the tab name stays italics, and if I click on something else, the tab will be reused and my edit will be LOST.
This happens too often (that I forgot to click save and open something else to get something for my editing but lost my editing immediately) and it's becoming annoying to a point that I believe Postman's UX design is not encouraging using the description field or most of Postman users are not using this feature, or I must have been missing something.

### Steps To Reproduce

1. Open a collection (or a folder)
2. Edit description, write anything, not click 'save'
3. Open something else, the same tab is reused
4. Open the collection (or the folder) that has been editing, the unsaved modification is gone.

### Operating System

macOS

### Postman Version

10.14.7

Update: this is fixed in version 10.15.4

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by zhaowb** [comment]
If this is fixed, then perhaps the description field can also be included in 'autosave' feature. I hope.

**Comment by giridharvc7** [comment]
@zhaowb do you have autosave turned on?

**Comment by zhaowb** [comment]
@giridharvc7 with or without autosave, the problem is the same.
Please note the issue is not about autosave. The point is when the description field is in middle of editing, click on another collection/folder/request will reuse the current tab and the editing is lost.

Cheers

**Comment by zhaowb** [comment]
Update: this is fixed in version 10.15.4

With autosave turned on, after editing description (of a collection/folder/request), then click on something else, the edit is saved automatically.
