### ISSUE TITLE
Able to use "team workspace" feature after free trial period is over without any payment

### ISSUE THREAD

**Issue by supershanesta** [a85/POSTMan-Chrome-Extension#12070]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

I have been working on a team workspace in postman and after the free trial it asks me to either upgrade the plan or manage the team to only have 3 other team members (Total of 4). I have removed the other team members so that we now have 4/4 spots taken but it still will not allow me to enter into my collections after doing so.

### Steps To Reproduce

1. Create a Postman Workspace
2. Activate the free trial
3. Add more than 4 members to the team
4. Wait for the free trail to expire
5. See popup on deskop or web. Looks like your trail as ended.

### Screenshots or Videos

![image](https://github.com/postmanlabs/postman-app-support/assets/20649126/2b6596a8-be03-4233-b5be-b37c3e4e04c1)
![image](https://github.com/postmanlabs/postman-app-support/assets/20649126/81b6e0db-f25b-46e8-adc9-2ceb63bea5b7)
![image](https://github.com/postmanlabs/postman-app-support/assets/20649126/7e6ca209-8d44-4e7a-aed0-98ae3fa75970)

### Operating System

Windows

### Postman Version

10.14.7

### Postman Platform

Both

### User Account Type

Signed In User

**Comment by supershanesta** [comment]
Closed because I think I misunderstood the limits of free tier

**Comment by haleygodtfredsen** [comment]
Hi @supershanesta yes, the free tier has 3 users. Please let me know if you have any questions! Thank you :)
