### ISSUE TITLE
Sorting requests within a collection

### ISSUE THREAD

**Issue by Rychard** [a85/POSTMan-Chrome-Extension#1207]
~~Is there some way to sort (be it automatic or manual) requests within a collection?~~

~~The ![image](https://cloud.githubusercontent.com/assets/2145848/8484905/2d42a818-20c8-11e5-857a-6fce7ff93ab3.png) icon appears to only sort the collections themselves.~~

~~A comment on #853 seems to indicate that this was an added feature in the 3.0 release, but I can't seem to find it.~~

**Edit:** Clicking and dragging _seems_ to be the necessary manner of sorting these requests.  That said, there's a minor visual issue when doing this.  Upon starting the drag-drop process, the drag item is shown very far from the position of the cursor.  
- The drag item is attached to the cursor at a constant distance; the distance is quite large.
- When completing the drag-drop action, the item is placed at the position of the cursor.
  - The visual indication for the drop target is shown at the position of the cursor, as expected.

A screenshot will probably explain this more appropriately:
![image](https://cloud.githubusercontent.com/assets/2145848/8485093/48884384-20c9-11e5-8148-8a0ecb0e2900.png)
Note the distance between the drag item (circled) and the cursor/drop-target.

**Comment by abhijitkane** [comment]
@Rychard - we've fixed the issue in the latest version - v3.0.4. Can you confirm?
