### ISSUE TITLE
Performance testing: Performance detail breakdown is not visible after performance run

### ISSUE THREAD

**Issue by sashley29** [a85/POSTMan-Chrome-Extension#12078]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

After running a performance test in Canary, the breakdown of request details is not visible. 

![image](https://github.com/postmanlabs/postman-app-support/assets/49599031/8548f8bf-0691-4452-b15d-8e3e873ab353)

### Steps To Reproduce

1.  Run performance test with 20 VU over 2 minutes
2.  Scroll down to performance details section
3. No details visible

### Operating System

Windows

### Postman Version

10.13.9-canary01

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by malvikach** [comment]
@sashley29 We have not been able to reproduce this issue at our end.

We will need some more details from you to understand this better. Please feel free to drop the following details at [support@postman.com](mailto:support@postman.com):

1. Your email id with which you used the postman canary
2. Collection ID
3. The performance run number where this issue happened.

Also, it would help to know if this issue always occurs for you across multiple runs or it happened once. Is the table visible once the run is completed and not visible during the run?

Regards,
Malvika

**Comment by malvikach** [comment]
Closing this issue. Please feel free to reopen and mention the above details if you are still facing the problem.
