### ISSUE TITLE
Basic Authorization bug report

### ISSUE THREAD

**Issue by nmertzanis** [a85/POSTMan-Chrome-Extension#12074]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

If you create a request and save Basic Auth credentials in that request but then you decide that you actually want to "Inherit auth from parent" and select that option and save it, Postman still uses the previously entered credentials. 

This is probably some if statement that checks for any "local credentials" before inheriting. 

### Steps To Reproduce

1. Open a new request tab
2. Add working credentials with the selection "Basic Auth" (I suspect this will happen with all credential options)
3. Make sure the request works
4. Add different credentials to the parent folder
5. Select "Inherit auth from parent" 
6. Observe the previous response instead of a different one

### Operating System

Windows

### Postman Version

10.14.5

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by giridharvc7** [comment]
@nmertzanis just curious - did this happen because the changes done in folder level were not saved?
