### ISSUE TITLE
attaching files every time a collection runs

### ISSUE THREAD

**Issue by bandtank** [a85/POSTMan-Chrome-Extension#1208]
How do you avoid manually attaching a file to a request? I want to save a picture in a request and I know, for whatever reason, Postman won't save it. How do you work around this? Can I convert the image to text somehow and paste it into a field? If so, how? Part of my automated test flow requires images to be uploaded to an endpoint.

**Comment by abhijitkane** [comment]
You can check out newman (http://npmjs.org/package/newman). You can export your collection from Postman, edit the exported file to reflect the path of your image, and run it via Newman.

Blog post - http://blog.getpostman.com/2014/11/15/using-newman-to-run-collections-with-file-post-requests/
