### ISSUE TITLE
Assigning variables from cookies now have <br/> in strings

### ISSUE THREAD

**Issue by mikefadhl** [a85/POSTMan-Chrome-Extension#1209]
Yesterday when my UI upgraded, I started having <br/> tags in my strings.

Steps to reproduce:
Make a http request
My response goes through the test script which pulls out cookie values which I use in subsequent calls.  When I assign the global variables they have <br/> tags in the string.

My Test Script:
var myslCheck = postman.getResponseCookie("slCheck");
postman.setGlobalVariable("slCheck",myslCheck.value);

![screen shot 2015-07-02 at 3 56 43 pm](https://cloud.githubusercontent.com/assets/10877094/8489678/28d7823e-20d3-11e5-8f14-c437523f398b.png)

Before yesterday I didn't have <br/> tags in the string.

**Comment by abhijitkane** [comment]
Thanks for reporting this. We'll push a fix for this soon.

**Comment by mikefadhl** [comment]
Will this fix be in next release?  When is the next release date?

**Comment by abhijitkane** [comment]
We'll be pushing v3.0.3 by July 13.

**Comment by abhijitkane** [comment]
@mikefadhl v3.0.4 has a fix for this. Can you confirm?

**Comment by mikefadhl** [comment]
Yes it works now
