### ISSUE TITLE
Loading chunk 1237 falied

### ISSUE THREAD

**Issue by rajudev24** [a85/POSTMan-Chrome-Extension#12093]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Loading chunk 1237 failed. (missing: https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/rajud/.vscode/extensions/postman.postman-for-vscode-0.2.0/dist/workspace-switcher/1237.45f74d680f70c9ba.js)

I am trying to open postman extension from VScode but getting this error. 

### Steps To Reproduce

I am trying to access from vscode extension. before it's worked for me but now getting above error

### Operating System

Windows

### Postman Version

latest 

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by pankajk07** [comment]
@rajudev24 It will be really helpful if you can also share a screen recording for the same. It will help us debug the issue faster.

Also, share the version of the Postman extension that is installed. Please have a look at the below screenshot to understand how you can retrieve the version.

<img width="485" alt="image" src="https://github.com/postmanlabs/postman-app-support/assets/44100113/51d1a3e8-9f89-4edf-9b9f-0a799d0baaf4">

**Comment by pankajk07** [comment]
@rajudev24 Can you please update the extension to the latest version and let us know if the issue is still reproducible?

**Comment by pankajk07** [comment]
@rajudev24  I will go ahead and close the ticket, as we did not get any response from your side. Feel free to create a new ticket, if the issue is still reproducible on your side.
