### ISSUE TITLE
Performance testing - Requests using Bearer token fail

### ISSUE THREAD

**Issue by geoff-maddock** [a85/POSTMan-Chrome-Extension#12100]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

I tested out performance testing using May 2023 (v10.13.9-canary01)

Running performance testing against my API with basic auth are successful.
I have a version of the API that requires a bearer token, and those fail 100% when run under "Performance"
If I run the same collection that requires the bearer token with the same environment under "Functional", they pass 100%.

I saw another issue relating to variables not working, so I created a version of the same collection that didn't use variables, and instead hard coded the values such as the token, but that made no difference on it's own - it still failed.  

### Steps To Reproduce

1. Select the collection that uses bearer token for auth
2. Run the collection using "Performance" tab
3. Observe 100% failure

### Screenshots or Videos

n/a

### Operating System

WIndows

### Postman Version

May 2023 (v10.13.9-canary01)

### Postman Platform

Postman App

### User Account Type

Signed In User

### Additional Context?

n/a

**Comment by malvikach** [comment]
Hi @geoff-maddock thanks for your feedback, we are looking into this issue.

**Comment by shreyas-panduranga** [comment]
@geoff-maddock We tried to reproduce the issue by following the steps you provided. But we were not able to hit the issue. We used a simple test API that uses bearer token authentication. The attached video also shows the same. The API succeeds with the bearer token getting passed down. We haven't used anything else. The same collection with the token in the collection variable also works.

If there is anything we have not followed in your steps or you have done anything differently from this, let us know. If you followed the same steps and are still seeing the issue, we might want to take a look at the collection and environment you are using.

Update: Also, we figured out that passing long values like the token in this case, through the environment does not work as expected right now. We will be fixing this. Passing the same through collection variables works.

https://github.com/postmanlabs/postman-app-support/assets/100409385/99854e82-eb13-4abe-b02b-a5e344064fce

**Comment by damenapp** [comment]
Facing the same issue

**Comment by shreyas-panduranga** [comment]
Hi @damenapp @geoff-maddock It would help if one of you could check if you still see this issue on the latest postman production app. We haven't been able to replicate the issue at our end.

**Comment by geoff-maddock** [comment]
I'll test this out today when I have a min

**Comment by geoff-maddock** [comment]
It's working for me now.  Looks good!
