### ISSUE TITLE
Ability to use data files with Performance Testing

### ISSUE THREAD

**Issue by malvikach** [a85/POSTMan-Chrome-Extension#12107]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

Raising this feature request based on user feedback. 

Problem: There is no way to provide data to virtual users such as names/passwords or IP addresses. 

### Describe the solution you'd like

User would like the ability to use a data file to inject data as input for each virtual user. The requests should be sent for each VU pertaining to the data applied. This is similar to how iterations behave for collection runner wrt data files.

**Comment by ColdCerealAtWork** [comment]
This is a must have for load testing some of our API's

**Comment by malvikach** [comment]
Hi @ColdCerealAtWork We are starting to look into this feature improvement. Would be very helpful if you are free for a discussion about this as we research more about it and design a solution. 

Let me know if you are up for this. Please drop me a note at malvika.chaudhary@postman.com and I can set some time for our discussion. 

Regards,
Malvika

**Comment by shishir20may2022** [comment]
This is very much required feature. to test the API with multiple data set.

**Comment by Satyam-Patel** [comment]
I'd like to see this feature :) - To run a data file for performance test - having ability to dynamically change request params during performance test run.

**Comment by malvikach** [comment]
Hi @ColdCerealAtWork @shishir20may2022 @Satyam-Patel 👋 

Glad to inform you that we have recently added a feature that allows you to dynamically set request variables for each virtual user of a Performance Test by using a data file. You can try this feature by updating the Postman app to the latest version (10.19.7). This feature is in trial and we would love to get more feedback from you once you try it:

<img width="1056" alt="Screenshot 2023-10-25 at 1 55 19 PM" src="https://github.com/postmanlabs/postman-app-support/assets/89449769/fc909d26-88a8-4e0f-af1a-e2da3914f055">

You can read further about how to use the feature at our [learning center](https://learning.postman.com/docs/collections/performance-testing/performance-test-data-files/). 

Thanks for giving us feedback, we really appreciate your time. 

Cheers!
Malvika

**Comment by Satyam-Patel** [comment]
Thank you for considering the suggestion and for getting back. Will
definitely give it a try.

Regards,
Satyam

**Comment by BankiHub** [comment]
Hello,

Is there a way to attach the CSV file once, so I don't have to add it every time I run the entire collection set?

Regards,
Murali

**Comment by sangramnithena** [comment]
Hi @malvikach 
            Still we can add a limited data , how can we test the number of maximum active users at which system breaks , also its not very efficient to every time create a custom dataset for each API's , is there any way to check at what different maximum users the system fails ?
