### ISSUE TITLE
Having content overlap issue when i click on  new button on windows application

### ISSUE THREAD

**Issue by pradeepdec28** [a85/POSTMan-Chrome-Extension#12119]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

I observed when i am working on postman i found this content overlapping issue from postman windows application attached screenshot please find below.
**Version : Postman v10.15.0**
<img width="642" alt="postman bug" src="https://github.com/postmanlabs/postman-app-support/assets/97936182/bde8e532-8c5e-4749-99e1-1d333fcada1a">

### Steps To Reproduce

step1 : open postman from windows app 
step 2: click the new button on the left corner adjacent to the import button. Then the dialog box opens where you can see this issue of content overlapping.

### Screenshots or Videos

<img width="642" alt="postman bug" src="https://github.com/postmanlabs/postman-app-support/assets/97936182/6c14a803-dc48-4107-8daa-ee46743fc06a">

### Operating System

windows

### Postman Version

v10.15.0

### Postman Platform

Postman App

### User Account Type

Signed Out User

### Additional Context?

please check

**Comment by sandeep-singh-pstmn** [comment]
@pradeepdec28 this will be fixed in the next update
