### ISSUE TITLE
URL in JSON escape slashes

### ISSUE THREAD

**Issue by kevinvanmierlo** [a85/POSTMan-Chrome-Extension#1211]
I'm using postman for a while now and I'm loving it. One thing that bothers me though is that in every URL in JSON the slashes get escaped. In the old version (non-packaged app) this wasn't the case.

**Comment by SamvelRaja** [comment]
@kevinvanmierlo I tried reproducing the same in the latest app, it is working fine. Kindly reopen the issue if you are facing it still.

**Comment by kevinvanmierlo** [comment]
@SamvelRaja Yeah it's working fine now, thanks! Forgot to close this.
