### ISSUE TITLE
Unable to remove member

### ISSUE THREAD

**Issue by awl-francisco-renteria** [a85/POSTMan-Chrome-Extension#12117]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Team administrators are seeing this error when trying to remove a user from the team.
"Unable to remove member. We need to have new owner to transfer data to when this user leaves the team."

The user is Developer type and has no collections at all. It's an inactive user.

### Steps To Reproduce

Go to https://go.postman.co/team
Hover over the user you'd like to remove
See a generic error message – "Unable to remove member. We need to have new owner to transfer data to when this user leaves the team."

### Screenshots or Videos

![image](https://github.com/postmanlabs/postman-app-support/assets/55823412/8b0351a0-e448-4970-b9f6-4872afa7fa8b)
![image](https://github.com/postmanlabs/postman-app-support/assets/55823412/196fe154-d7c2-4bb9-a691-928fd6bd5038)

### Operating System

Edge 114 / Windows 10

### Postman Version

10.15.1-230614-0638

### Postman Platform

Postman Web

### User Account Type

Signed In User

**Comment by arkwinta** [comment]
Bump, facing the same issue

**Comment by VaishnaviChallaPostman** [comment]
Hey @awl-francisco-renteria  and @arkwinta 
Sorry to see you running into this issue. 
Could you please submit a ticket(https://support.postman.com/hc/en-us/requests/new/) with us so that we will be able to investigate further?
Thanks!

**Comment by VaishnaviChallaPostman** [comment]
Hey @arkwinta and @awl-francisco-renteria 👋 Sorry to hear that!
I’m happy to let you know that the Engineering team has released a fix for this issue.
Could you check and let us know if you are still facing any issues?
