### ISSUE TITLE
[Windows] Postman request URL changes, when clicking on "Body", "Pre-request Script" and others

### ISSUE THREAD

**Issue by pmalecka** [a85/POSTMan-Chrome-Extension#12125]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

It seems that the click target for url auto complete is not removed, when the autocomplete UI is hidden.

This means that clicking on "Body", and "Pre-request Script" (on the bar just below the request URL) and also into the request contents causes the request URL to be changed. Also, the click on the "Body" is not performed.

### Steps To Reproduce

Note: This can be replicated only on collection that has URL auto complete working (I don't know how Postman decides where to offer URL autocomplete)
1. create multiple requests in collection: "/v1/level1", "v1/level1/", "v1/level1/level2", "v1/level1/level2/", "/v1/level1/level2/level3" (and somehow make the URL autocomplete working)
1. Open the v1/level1 request
2. Switch to another request: v1/level1/
3. Define a request body and pre-request script
4. Click on the request "body" button, and observe the URL being changed unexpectedly

### Screenshots or Videos

https://github.com/postmanlabs/postman-app-support/assets/13047492/77ad3765-b9bc-4750-8f11-8b2b54ca3f66

### Operating System

Windows

### Postman Version

10.15.2

### Postman Platform

Postman App

### User Account Type

Signed In User

### Additional Context?

This is a serious UX issue, that can lead to data corruption. Please treat this as high priority. Thank you.

**Comment by lukelliot** [comment]
I'm also having this issue. The suggestion box for the url input isn't visible, but it's still clickable for some reason.

**Comment by kaa-intive** [comment]
Hi guys,
This issue still occurs. I've updated Postman from 10.15.2 to  10.15.5.
It's really annoying. 
I'm creating new request by copying already existing one and changing part or request url. Saving. 
And then URL request changes unexpectedly when switching between body/headers/pre-request script tab.

**Comment by kaa-intive** [comment]
And it's not only on Windows. I'm using MacOS 13.2.1 . Fyi @VaishnaviChallaPostman

**Comment by giridharvc7** [comment]
Thank you for reporting this - we'll get back to you soon.

**Comment by dev-sharma-08** [comment]
We have fixed this bug in the latest web version `10.15.10` and desktop app version `10.15.7`.
Please update your app to the latest version, and feel free to open this again if the issue persists.
