### ISSUE TITLE
GraphQL query beautify is not beautifying

### ISSUE THREAD

**Issue by jonathanazulay-sileon** [a85/POSTMan-Chrome-Extension#12126]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

The beautify feature of GraphQL requests don't really seem to work well.

### Steps To Reproduce

1. Create a new GraphQL request
2. Paste following GraphQL request in query 
```graphql
mutation MutationThing {
    myMutation(input: {
        thing: [],
        thing2: {
            nestedThing: "test",
            evenmorenested: { foo: "bar", bar: "long long long" }
        },
        thirdThing: ["with array"]
    }) {
        id
    }
}
```
3. Click on "Beautify"

### Screenshots or Videos

![Skärmavbild 2023-06-22 kl  10 31 25](https://github.com/postmanlabs/postman-app-support/assets/112399399/c44c0719-77be-4ff5-8672-c763d29ae63b)

### Operating System

macOs

### Postman Version

10.15.2

### Postman Platform

Both

### User Account Type

Signed In User

**Comment by timhall** [comment]
Hi! Thanks for raising this issue, it has been resolved and will be included in the next release.

**Comment by timhall** [comment]
This has been improved in the September release, thanks again for raising this issue
