### ISSUE TITLE
Is it possible in Jetpacks to save response to a local file 

### ISSUE THREAD

**Issue by jetpacksfan** [a85/POSTMan-Chrome-Extension#1212]
Just bought the Jetpacks and are happy with the Collection Features
However when all request finished, all response disappeared as well.
Tried to save the collection result but that's not the response.
is it possible to save the responseBody to a local file automatically?
I don't know how to write the script in 'Tests'. Or is it... impossible?

**Comment by abhijitkane** [comment]
The feature to save responses is not available in the Collection Runner right now. We're working on a feature that will allow you to save complete responses to a file when the collection run is over, but I can't provide a timeframe yet.

**Comment by jetpacksfan** [comment]
Thanks. Getting an offical reponse makes me feel at ease because I don't need to spend countless hours on searching for a rescue any more.
Really wish you can implement it soon because I think it'll be a big big step to real automatic test.
Also I think it's not too hard because you've already implemeted the feature of 'save to clipboard' with one click, why don't you just chain them up and dump it to a dest file?
( Sorry if i'm thinking it too easy )

**Comment by johnnavarra** [comment]
add this to the test:
console.log(responseBody);
after all your tests are run you can right click and save to a csv.

**Comment by jetpacksfan** [comment]
Thank you johnnavarra. Have tried that previously, it works for single request but not for collection.
And actually it's useless in this scenario because for single requests I can directly save contents by 'copy to clipboard' or 'save response' function, while exporting to console I have to find out the contents by filtering the 'log' which is awkward.

**Comment by abhijitkane** [comment]
@jetpacksfan A workaround would be to use Newman (https://github.com/postmanlabs/newman), and write custom code to write to a file when the "request" event is fired - check the "newman.run~events" section.
