### ISSUE TITLE
not able to import environment after creating teams

### ISSUE THREAD

**Issue by praveenrtzen** [a85/POSTMan-Chrome-Extension#12129]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

not able to import environment after creating teams

### Steps To Reproduce

1. created teams
2. try to import environment using file
3. getting error

### Operating System

macOS

### Postman Version

10.15.1

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by dhwaneetbhatt** [comment]
@praveenrtzen could you please try once more? We had an [incident](https://status.postman.com/incidents/8cy9383lb03q) this morning and a lot of services were affected.

**Comment by praveenrtzen** [comment]
yes, now it's working fine.
