### ISSUE TITLE
No working postman app on mac

### ISSUE THREAD

**Issue by eddyjaga** [a85/POSTMan-Chrome-Extension#12130]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Cannot sync workspaces

### Steps To Reproduce

1. Open the app
2. Request not found

### Operating System

MacOS

### Postman Version

10.15.4

### Postman Platform

Both

### User Account Type

Signed In User

**Comment by sahilsalaria811** [comment]
Faced same issue But it's working fine now.
