### ISSUE TITLE
Put Request return 405

### ISSUE THREAD

**Issue by cuencacigars** [a85/POSTMan-Chrome-Extension#1213]
Not allowed. How can I resolve this?

**Comment by abhijitkane** [comment]
The 405 status code indicates that the server does not support PUT requests to the URL that you're using. You'll need to contact the API developer to resolve this.

**Comment by cuencacigars** [comment]
Thanks!

Ana from Cuenca Cigars
www.CuencaCigars.com
1928 Harrison Street
Hollywood, FL 33020
Phone: 866-417-9454
Fax:    954-364-7661

Follow us:

   <https://www.facebook.com/Cuenca.Cigars.Hollywood>
<http://www.facebook.com/l.php?u=https%3A%2F%2Ftwitter.com%2FCuencaCigars&h=JAQF3R8Pj&s=1>

<http://www.facebook.com/l.php?u=http%3A%2F%2Fwww.linkedin.com%2Fin%2Fcuencacigars%2F&h=CAQEGJxUZ&s=1>

<http://www.facebook.com/l.php?u=https%3A%2F%2Fplus.google.com%2Fu%2F0%2Fb%2F104144297863662293917%2F104144297863662293917%2Fposts&h=cAQE_bj_I&s=1>
<http://pinterest.com/cuencacigars/>

...the only place that will put up with your ash...

Receive a free cigar if you leave a review and let us know in your comments
on your next order. Have a nice day!


This e-mail is confidential. If you are not the addressee or an authorized
recipient of this message, any distribution, copying, publication or use of
this information for any purpose is prohibited. Please notify the sender
immediately by e-mail and then delete this message.

**Comment by cuencacigars** [comment]
<p>Hey!</p>

<p>ShippingEasy, the software I use to print all my labels with the best USPS discounts, offers a FREE month to friends of current subscribers (me). All you do is click the link and it will automatically give the first month FREE. I recommend it!</p>

<p>LINK FOR FREE MONTH: http://shippingeasy.com/easyreferral?c=Z9ZE5A68&amp;_s=M</p>

Regards,
ShippingEasy Support
support@shippingeasy.com


shippingeasy.com
855-202-2275
ShippingEasy • 609 Castle Ridge Road • Suite 445 • Austin, TX 78746
