### ISSUE TITLE
Feature request: iterations=0 imply run all records in data file

### ISSUE THREAD

**Issue by sriegel2** [a85/POSTMan-Chrome-Extension#1214]
Postman 3.0.2. It is awkward to run multi-record data files in Collection Runner. I find I must specify the exact number of records in order to ensure all are processed. iterations=0 currently only processes first record and iterations>#records causes last record to be repeated in remaining requests (creating duplicates entries in some web apps). It seems iterations=0 would be straightforward way to indicate that data file implies number of iterations to be done (newman does this).

**Comment by a85** [comment]
Importing the file now automatically detects the records so should not have to set this manually.
