### ISSUE TITLE
gRPC reflection doesn't support JSON mapping maps

### ISSUE THREAD

**Issue by sashayakovtseva** [a85/POSTMan-Chrome-Extension#12146]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

When using server reflection postman recognises message which contains map in JSON mapping format as invalid, even though the same message using .proto import is considered valid. 

According to [docs](https://learning.postman.com/docs/sending-requests/grpc/understanding-grpc-types/) JSON mapping supports map in form `{"k": v}`.

### Steps To Reproduce

1. Launch gRPC server that implements the following
```
syntax = "proto3";

package test.v1;

service TestService {
  rpc Test(TestRequest) returns (TestResponse);
}

message TestRequest {
  map<uint64, uint32> data = 1;
}

message TestResponse {}
```

2. Try to invoke Test method using server reflection with the following body:
```
{
  "data": {"1": 2}
}
```

<img width="1004" alt="image" src="https://github.com/postmanlabs/postman-app-support/assets/20927474/a2329379-660b-4f1d-a954-15f9c175290c">

3. Invoke the same method using .proto import (I launched default UnimplementedTestServiceServer with Go, so status 12 is expected)
<img width="1029" alt="image" src="https://github.com/postmanlabs/postman-app-support/assets/20927474/e15d92a7-471d-4e10-b42b-94abcb4bbdde">

### Operating System

macOS

### Postman Version

10.15.6

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by wluxion** [comment]
Would be great to get this fixed; server reflection is much more convenient than manually updating the proto definition, particularly when prototyping new APIs.

**Comment by alevinval** [comment]
It would be awesome to get this resolved, as @wluxion mentions, reflection is the deal breaker otherwise I might as well use `grpcurl`

**Comment by theyoprst** [comment]
"Use Example Message" button helped me to find a working (but weird) way to call it:

```json
"data": [{
    "key": 1,
    "value": 2
}]
```

**Comment by appurva21** [comment]
Hey folks! 

The latest version of Postman (v11.8.0) now supports the expected JSON representation for `map` fields when using server reflection.

![Screenshot 2024-08-14 at 2 03 58 PM](https://github.com/user-attachments/assets/8b01af12-f634-453f-9816-1bdd55c6a778)
