### ISSUE TITLE
Flows: copying a grouped send request fails to properly resolve variables.

### ISSUE THREAD

**Issue by topicaantje** [a85/POSTMan-Chrome-Extension#12147]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

When a group is copied, the resolution of variables on a send request is done incorrectly, as the variable no longer evaluates to the value dictated by the get variable, but instead resolves to the value {{variablename}}.

### Steps To Reproduce

Scenario:
- put a send request if flows.
- fill one of its variables with a get variable.
- group the request in a group.
- execute the request, variable gets properly filled.
- copy the group, and chain the copy after the original group.
- execute the requests, and watch the second request go wrong.
- input variable gets resolved to {{variablename}}, rather than the value the get variable has.
- if i instead simply create a new request, and give it the same variable, it succeeds...

### Operating System

Windows

### Postman Version

10.15.6

### Postman Platform

Postman App

### User Account Type

Signed Out User

**Comment by rabbah** [comment]
This should be now fixed. If you're still encountering this issue, please share a screenshot or recording if possible so we can create a new test case.
