### ISSUE TITLE
No performance Tab

### ISSUE THREAD

**Issue by fvsadem** [a85/POSTMan-Chrome-Extension#12151]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Hi,

I don't have the performance tab when i would like to run collection tests...
I have a free plan maybe it's not available in this plan ?
Maybe i have to activate something ?

![image](https://github.com/postmanlabs/postman-app-support/assets/55987370/f5adaff6-0d95-4266-bb03-06d9ca493761)

Postman is telling me that i am up to date : V10.14.9
Snap version for ubuntu 22.04 

Thanks

### Steps To Reproduce

1. Select Run Collection from dots options 

### Operating System

Ubuntu 22.04

### Postman Version

10.14.9

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by AdelinaBravo** [comment]
I also have this issue, I'm using v10.15.10

**Comment by malvikach** [comment]
hey @fvsadem @AdelinaBravo Could you try updating the app to the latest version and check? (latest version should be 10.17.1) . Please restart once updated and let me know if you still don't see the tab. 

The tab is available for our free plans also, so you should be seeing the same. 

Regards,
Malvika

**Comment by fvsadem** [comment]
@malvikach 

Version 10.17 solves the problem

Thanks

**Comment by AdelinaBravo** [comment]
Oh I'm not able to download that version yet. Ok, I'll just have to wait until it's enabled for me. Thanks! 
<img width="658" alt="image" src="https://github.com/postmanlabs/postman-app-support/assets/131176671/63021f33-dac0-4b76-9226-4473f951c4a6">
