### ISSUE TITLE
[Postbot]-when tests tab has some variable declaration the generated tests are not created

### ISSUE THREAD

**Issue by sseenivasan89** [a85/POSTMan-Chrome-Extension#12157]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

in the collection I have 2 requests, in that one request I have written some variable declarations in the tests tab
for that request, the tests are not generated

### Steps To Reproduce

1. Have some variable declaration in one request in the tests tab
2. Generate the tests from the collection level
3. Confirm the tests are generated for all the request 

### Screenshots or Videos

![image](https://github.com/postmanlabs/postman-app-support/assets/44080743/35680d63-a6ca-4b6b-84d0-13275cc2e8c7)

### Operating System

Windows

### Postman Version

Version 10.15.6-canary01

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by SterlingChin** [comment]
This is currently the expected interaction for test suite generation using Postbot. If there are scripts (not just tests) associated with request, Postbot will not create additional test scripts for that request.

**Comment by ronork** [comment]
@sseenivasan89 We are working on adding support for these scenarios where there are no tests in the request but it has some existing script like variable declaration.

**Comment by abhijitkane** [comment]
@sseenivasan89 This should be addressed in today's Postman update. Postbot will only skip requests that have actual tests already defined. For variable declarations etc., Postbot will generate tests based on the response it gets.
