### ISSUE TITLE
[Postbot]-Generate tests is not in sync for all the requests we have in collection

### ISSUE THREAD

**Issue by sseenivasan89** [a85/POSTMan-Chrome-Extension#12156]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

when we clicked on the generate test button for a collection that has 2 requests, tests are generated for only one test 

### Steps To Reproduce

1. Open Generate test from collection
2. Clik on generate test button
3. Chek the test generated for all the requests in the collection

### Screenshots or Videos

![image](https://github.com/postmanlabs/postman-app-support/assets/44080743/ae78d6e5-58e5-437e-9639-86f78cac0222)

### Operating System

Windows

### Postman Version

Version 10.15.6-canary01

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by SterlingChin** [comment]
This is the expected interaction when using Postbot to help with test suite generation. If there are existing scripts, Postbot will not create new test scripts.
