### ISSUE TITLE
Incorrect tooltip on body search button

### ISSUE THREAD

**Issue by nachograffione** [a85/POSTMan-Chrome-Extension#12166]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

With the VSCode extension, when I hover over the search button in the body section, it shows "Copy to clipboard" as tooltip.

### Steps To Reproduce

1. Open VSCode with Postman extension installed
2. Open a new request tab
3. Send a request that returns some body data (for example GET http://www.randomnumberapi.com/api/v1.0/random)
4. Hover over the search button in the body section
5. See "Copy to clipboard" tooltip

### Screenshots or Videos

![image](https://github.com/postmanlabs/postman-app-support/assets/37000542/bf852d57-7911-4287-bb3d-395788ce2732)

### Operating System

Windows

### Postman Version

0.3.1

### Postman Platform

Other

### User Account Type

Signed In User

**Comment by pankajk07** [comment]
@nachograffione This is fixed in the extension's latest version (`v0.4.0`). Please update the extension and test out the changes.

Closing this issue as the bug is now resolved.
