### ISSUE TITLE
Can't click requests

### ISSUE THREAD

**Issue by iansul** [a85/POSTMan-Chrome-Extension#1216]
Recently I've started having a lot of trouble selecting the requests I've saved. It makes the postman app almost impossible to use. I can still enter the request manually but I have a bunch of script to evaluate responses, and populate environment variables with those results.

Is anyone else seeing this?

**Comment by iansul** [comment]
Is there any way to debug this? Can I get a console window and see if there are any JS errors?

**Comment by a85** [comment]
Yes. You can get a console window. Instructions here: http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/

**Comment by a85** [comment]
Not sure why you are facing this issue. Things seem to be working fine for me.

**Comment by iansul** [comment]
Not sure if there are "real" errors in here...

unload is not available in packaged apps.(anonymous function) @ extensions::platformApp:17
requester.js:1203 Loaded settings
requester.js:1215 Loaded theme
requester.js:23635 Open latest DB
requester.js:1218 Loaded Database
requester.js:33504 Initialized ThemeManager
extensions::platformApp:17 beforeunload is not available in packaged apps.(anonymous function) @ extensions::platformApp:17
requester.js:1305 Checking for update notifications...
requester.js:975 Initialize interceptor
requester.js:26229 ThemeSettingsTab: Purchase is available
requester.js:1314 Stored version: 3.0.2, currentVersion: 3.0.2
http://fhbjgbiflinjbdggehcddcbncdddomop/socket.io/1/?__sails_io_sdk_version…io_sdk_platform=browser&__sails_io_sdk_language=javascript&t=1436164861317 Failed to load resource: net::ERR_NAME_NOT_RESOLVED
http://fhbjgbiflinjbdggehcddcbncdddomop/socket.io/1/?__sails_io_sdk_version…io_sdk_platform=browser&__sails_io_sdk_language=javascript&t=1436164861374 Failed to load resource: net::ERR_NAME_NOT_RESOLVED
requester.js:26229 ThemeSettingsTab: Purchase is available
requester.js:15261 Purchase saved
sails.io.js:2 WebSocket is already in CLOSING or CLOSED state.b.util.ua.iDevice.d.send @ sails.io.js:2c.packet @ sails.io.js:2c.onHeartbeat @ sails.io.js:2c.onPacket @ sails.io.js:2c.onData @ sails.io.js:2websocket.onmessage @ sails.io.js:2
chrome-extension://fhbjgbiflinjbdggehcddcbncdddomop/js/libs/ace/worker-json.js Failed to load resource: net::ERR_FILE_NOT_FOUND

I'm able to select requests sometimes, but there doesn't seem to be any logic around when the clicks will work.

**Comment by abhijitkane** [comment]
@iansul These errors don't affect the Postman app. Is there nothing else logged when you click on a request but it fails to select?

**Comment by iansul** [comment]
Nope nothing else logged.

I set a breakpoint in
 $collection_items.on("click", ".request-actions-load", function () {
And when the click does actually work I hit the breakpoint.

**Comment by iansul** [comment]
I figured out the issue, I was clicking in the "wrong" place.
Looks like you have to click the title of the request, and not the "request-head-icon"

I suggest you move "request-actions-load" class up to the list item &lt;li&gt; so you can click anywhere in the list item. 

```
<li id="sidebar-request-0039deb2-5c8b-02fe-d69a-52fe582e8e99" class="sidebar-collection-request sidebar-request clearfix">
    <div class="request-head-icon">
        <span class="label label-method sidebar-label-method label-method-POST">
            POST
        </span>
    </div>
    <div class="request request-actions-load sidebar-item-head" data-id="0039deb2-5c8b-02fe-d69a-52fe582e8e99">
        <span class="request-name collection-request-name">
            verifypin
        </span>
    </div>
    <div class="request-actions-wrapper">
```
