### ISSUE TITLE
Postman charging for collection runners

### ISSUE THREAD

**Issue by andrew-jones** [a85/POSTMan-Chrome-Extension#12169]
### Is there an existing issue for this?

- [x] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Why to try squeeze more money out of people.  Since when has there been a limit on the number of runners I can use?  25 is the monthly limit?  Nice one.  Moving to openapi.

### Operating System

All

### Postman Version

10.12.0

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by andrew-jones** [comment]
?

**Comment by Liamhhhhh** [comment]
Are you frustrated with Postman's fees? It's understandable that businesses need to charge to survive. You might want to explore other related tools like [Apidog ](https://www.apidog.com/?utm_source=&utm_medium=blogger&utm_campaign=test1)as alternatives. 
﻿ 
﻿
