### ISSUE TITLE
VSCode extension does not display OAuth token details when using "implicit" grant mode

### ISSUE THREAD

**Issue by pozil** [a85/POSTMan-Chrome-Extension#12176]
**Updated as of 2023-08-18**

### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

In the Postman VS Code extension, when authenticating a collection with the OAuth method and `implicit` grant type, the VS Code extension does not display the OAuth token details like in desktop or web (see screenshots).

I need to see these information as it contain values that are mandatory for completing the auth process (`instance_url`) in my use case (Salesforce Platform APIs). I can't use the extension in the current state.

### Steps To Reproduce

1. Using the VS Code extension, open a collection that is configured with OAuth authentication
2. Click *Generate Access Token*
3. Complete the authentication process using your browser
4. When returning to Postman VS Code extension, Notice the missing OAuth token details that are normally displayed in desktop or web version

#### VS Code
<img width="546" alt="VS Code view" src="https://github.com/postmanlabs/postman-app-support/assets/5071767/dfbc42e5-c55b-4d61-b5b2-81e78c207725">

#### Desktop App
<img width="788" alt="Desktop app view" src="https://github.com/postmanlabs/postman-app-support/assets/5071767/96bcdeb0-2e0a-4d5a-8a3e-0e6fafc0d443">

### Operating System

macOS

### Postman Version

0.6.0

### Postman Platform

Other

### User Account Type

Signed In User

**Comment by pankajk07** [comment]
@pozil We have added the ability to manage your tokens as part of the latest version (`v0.6.0`) of VS Code extension. Please update your extension and try it out.

**Comment by pozil** [comment]
@pankajk07 unfortunately this doesn't solve my problem as the "manage token" modal views are different between VS Code and desktop app. In VS Code only part of the token info is displayed and I'm still missing values that are mandatory for completing the auth process (`instance_url`).
Can you re-open the issue?

# VS Code
<img width="546" alt="VS Code view" src="https://github.com/postmanlabs/postman-app-support/assets/5071767/dfbc42e5-c55b-4d61-b5b2-81e78c207725">

# Desktop App
<img width="788" alt="Desktop app view" src="https://github.com/postmanlabs/postman-app-support/assets/5071767/96bcdeb0-2e0a-4d5a-8a3e-0e6fafc0d443">

**Comment by sandeep-singh-pstmn** [comment]
@pozil just want to confirm which grant type you are using for token generation

**Comment by pozil** [comment]
@sandeep-singh-pstmn we're using OAuth 2.0 with the `implicit` grant type.
For the record, this is the [Salesforce Platform APIs](https://www.postman.com/salesforce-developers/workspace/salesforce-developers/collection/12721794-67cb9baa-e0da-4986-957e-88d8734647e2) collection from the API Network.

**Comment by pozil** [comment]
I updated the issue title and description to reflect the latest info following our conversation.

**Comment by sandeep-singh-pstmn** [comment]
@pozil we have fixed this in the latest release(`v0.6.2`)
Please update your extension and try it out.

**Comment by pozil** [comment]
Thanks for the quick fix. I confirm that the issue is resolved with the new version.
