### ISSUE TITLE
`data` is blank in Pre-request script, but is populated in Test

### ISSUE THREAD

**Issue by clocklear** [a85/POSTMan-Chrome-Extension#1217]
Title says it all.  In version 3.0.2 (packaged) of Postman, I cannot access my `data` variables in prerequest scripts, but I can see them fine in test scripts.  `data` exists, but it is an empty object.

![image](https://cloud.githubusercontent.com/assets/622205/8527385/64205b90-23da-11e5-8e59-00f6bed71c51.png)

**Comment by abhijitkane** [comment]
Is this `data`, or `request.data`? Also, is this in the collection runner, or are you running a single request?

**Comment by clocklear** [comment]
This is `data`, the object that should exist from the imported JSON file.  Also this is in the collection runner.

**Comment by abhijitkane** [comment]
Got it. We'll push a fix for this in the next release.

**Comment by clocklear** [comment]
Thanks for the promptness!

**Comment by abhijitkane** [comment]
@clocklear Can you confirm this fixed in v3.0.4?
