### ISSUE TITLE
Network pane in 3.0.2 only shows posts to Google Analytics

### ISSUE THREAD

**Issue by clocklear** [a85/POSTMan-Chrome-Extension#1218]
I can't seem to find a way around this -- every request I run with jetpacks only shows triggers to GA:

![image](https://cloud.githubusercontent.com/assets/622205/8527452/b061c598-23da-11e5-84c4-fd89e4fa1138.png)

**Comment by abhijitkane** [comment]
Is the Interceptor on? Requests made through the Interceptor won't show up here - http://blog.getpostman.com/2015/06/13/debugging-postman-requests/

**Comment by clocklear** [comment]
Yep, that seems to be it.  I still see the GA posts, but at least I can see my own requests as well.  Thanks!
