### ISSUE TITLE
VSCode extension login TIMEOUT

### ISSUE THREAD

**Issue by danocolombo** [a85/POSTMan-Chrome-Extension#12180]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

I have been using Postman desktop app for years, have many collections and can login fine in my Chrome browser. 
For clarity....
I can open Postman desktop just fine.
I can login into postman.co just fine

When I open VSCode and install the Postman extension, I proceed to click the Sign In button. After a few moments, I get the error:

"Could not login: Network error (connect ETIMEDOUT 10.200.32.110:4438)

Documentation says it uses the same network settings as Chrome, but I can open my chrome browser and login just fine. Where is the 10.200.32.110 coming from??

Here are my Postman.postman-for-vscode-prod.log
(2023-07-24T11:28:58.228Z) [info] [extension] Extension activation started: 1690198138224
(2023-07-24T11:28:58.239Z) [info] [extension] Extension activation completed: 1690198138239
(2023-07-24T11:28:58.239Z) [info] [extension] Extension activation took 15ms
(2023-07-24T11:29:03.329Z) [info] [extension:sidebar:adapter] fetching a correct html for the view mode: {"viewMode":"login"}
(2023-07-24T11:29:05.482Z) [info] [extension:sidebar:manager] set login state to busy
(2023-07-24T11:29:05.482Z) [info] [extension:auth] Starting the login flow
(2023-07-24T11:30:20.513Z) [error] [extension:auth:client] Network error (connect ETIMEDOUT 10.200.32.110:4438)
(2023-07-24T11:30:20.516Z) [error] [extension:auth:controller] retrieving the redirect URL failed: {"error":"Network error (connect ETIMEDOUT 10.200.32.110:4438)"}
(2023-07-24T11:30:20.518Z) [error] [extension:auth] The sign in flow has failed: {"error":{"reason":"Error","details":"Network error (connect ETIMEDOUT 10.200.32.110:4438)"}}
(2023-07-24T11:30:20.519Z) [info] [extension:sidebar:manager] resetting the login state to signin
(2023-07-24T11:33:01.961Z) [info] [extension:sidebar:manager] set login state to busy
(2023-07-24T11:33:01.961Z) [info] [extension:auth] Starting the login flow
(2023-07-24T11:34:16.986Z) [error] [extension:auth:client] Network error (connect ETIMEDOUT 10.200.32.110:4438)
(2023-07-24T11:34:16.987Z) [error] [extension:auth:controller] retrieving the redirect URL failed: {"error":"Network error (connect ETIMEDOUT 10.200.32.110:4438)"}
(2023-07-24T11:34:16.988Z) [error] [extension:auth] The sign in flow has failed: {"error":{"reason":"Error","details":"Network error (connect ETIMEDOUT 10.200.32.110:4438)"}}
(2023-07-24T11:34:16.989Z) [info] [extension:sidebar:manager] resetting the login state to signin
(2023-07-24T11:36:04.297Z) [info] [extension:sidebar:manager] set login state to busy
(2023-07-24T11:36:04.297Z) [info] [extension:auth] Starting the login flow
(2023-07-24T11:37:19.306Z) [error] [extension:auth:client] Network error (connect ETIMEDOUT 10.200.32.110:4438)
(2023-07-24T11:37:19.307Z) [error] [extension:auth:controller] retrieving the redirect URL failed: {"error":"Network error (connect ETIMEDOUT 10.200.32.110:4438)"}
(2023-07-24T11:37:19.307Z) [error] [extension:auth] The sign in flow has failed: {"error":{"reason":"Error","details":"Network error (connect ETIMEDOUT 10.200.32.110:4438)"}}
(2023-07-24T11:37:19.307Z) [info] [extension:sidebar:manager] resetting the login state to signin
(2023-07-24T11:46:10.026Z) [info] [extension:sidebar:manager] set login state to busy
(2023-07-24T11:46:10.027Z) [info] [extension:auth] Starting the login flow
(2023-07-24T11:47:25.047Z) [error] [extension:auth:client] Network error (connect ETIMEDOUT 10.200.32.110:4438)
(2023-07-24T11:47:25.051Z) [error] [extension:auth:controller] retrieving the redirect URL failed: {"error":"Network error (connect ETIMEDOUT 10.200.32.110:4438)"}
(2023-07-24T11:47:25.052Z) [error] [extension:auth] The sign in flow has failed: {"error":{"reason":"Error","details":"Network error (connect ETIMEDOUT 10.200.32.110:4438)"}}
(2023-07-24T11:47:25.057Z) [info] [extension:sidebar:manager] resetting the login state to signin

### Steps To Reproduce

1. Open VSCode
2. Install Postman extension
3. click Sign in

### Operating System

MacOS

### Postman Version

VS Code Ext Version 0.4.1

### Postman Platform

Other

### User Account Type

Signed In User

**Comment by pankajk07** [comment]
Hi @danocolombo, thank you for reporting the issue. We needed some more information regarding the issue to debug and resolve it.

1. Are you behind any proxy?
2. Are you able to login into other VS Code plugins?

**Comment by danocolombo** [comment]
Yes, I am behind a proxy. My Chrome browser uses my Mac network settings

I have multiple VSCode extensions. I do not believe any of them require a remote login.  I did search in VSCode for proxy and found this...
{
    "editor.fontSize": 16,
    "emmet.triggerExpansionOnTab": true,
    "emmet.includeLanguages": {
        "javascript": "javascriptreact"
    },
    "prettier.jsxSingleQuote": true,
    "prettier.singleAttributePerLine": true,
    "prettier.singleQuote": true,
    "prettier.tabWidth": 4,
    "[javascriptreact]": {
        "editor.defaultFormatter": "esbenp.prettier-vscode"
    },
    "[json]": {
        "editor.defaultFormatter": "vscode.json-language-features"
    },
    "http.proxySupport": "on",
    "http.proxyAuthorization": null
}

I guess it might not be clear how to enable VSCode to use my Chrome browser settings.

**Comment by pankajk07** [comment]
@danocolombo Can you try setting the proxy as mentioned in this issue and see if this works 
https://stackoverflow.com/a/37581492

More details around Network and Proxy in VS Code: https://code.visualstudio.com/docs/setup/network

**Comment by ravthiru** [comment]
Iam seeing similar issue when trying to login to postman from VSCode postman plugin 
Here are the logs from Postman.postman-for-vscode-prod.log


(2023-10-05T00:25:08.637Z) [info] [extension] Extension activation started: 1696465508600
(2023-10-05T00:25:09.616Z) [info] [extension] Extension activation completed: 1696465509616
(2023-10-05T00:25:09.616Z) [info] [extension] Extension activation took 1016ms
(2023-10-05T00:25:19.211Z) [info] [extension:sidebar:adapter] fetching a correct html for the view mode: {"viewMode":"login"}
(2023-10-05T00:25:21.582Z) [info] [extension:sidebar:manager] set login state to busy
(2023-10-05T00:25:21.587Z) [info] [extension:auth] Starting the login flow
(2023-10-05T00:25:22.077Z) [error] [extension:auth:client] Network error (Request failed with status code 400)
(2023-10-05T00:25:22.096Z) [error] [extension:auth:controller] retrieving the redirect URL failed: {"error":"Network error (Request failed with status code 400)"}
(2023-10-05T00:25:22.109Z) [error] [extension:auth] The sign in flow has failed: {"error":{"reason":"Error","details":"Network error (Request failed with status code 400)"}}
(2023-10-05T00:25:22.111Z) [info] [extension:sidebar:manager] resetting the login state to signin
(2023-10-05T00:26:38.677Z) [info] [extension:sidebar:manager] set login state to busy
(2023-10-05T00:26:38.679Z) [info] [extension:auth] Starting the sign-up flow
(2023-10-05T00:26:38.681Z) [info] [extension:auth:controller] initiating sign up
(2023-10-05T00:26:38.801Z) [error] [extension:auth:client] Network error (Request failed with status code 400)
(2023-10-05T00:26:38.802Z) [error] [extension:auth:controller] retrieving the redirect URL failed: {"error":"Network error (Request failed with status code 400)"}
(2023-10-05T00:26:38.803Z) [error] [extension:auth] The sign up flow has failed: {"error":{"reason":"Error","details":"Network error (Request failed with status code 400)"}}
(2023-10-05T00:26:38.807Z) [info] [extension:sidebar:manager] resetting the login state to signin
(2023-10-05T00:26:39.957Z) [info] [extension:sidebar:manager] set login state to busy
(2023-10-05T00:26:39.958Z) [info] [extension:auth] Starting the login flow
(2023-10-05T00:26:40.008Z) [error] [extension:auth:client] Network error (Request failed with status code 400)
(2023-10-05T00:26:40.018Z) [error] [extension:auth:controller] retrieving the redirect URL failed: {"error":"Network error (Request failed with status code 400)"}
(2023-10-05T00:26:40.028Z) [error] [extension:auth] The sign in flow has failed: {"error":{"reason":"Error","details":"Network error (Request failed with status code 400)"}}
(2023-10-05T00:26:40.070Z) [info] [extension:sidebar:manager] resetting the login state to signin
(2023-10-05T00:27:44.104Z) [info] [extension:sidebar:manager] set login state to busy
(2023-10-05T00:27:44.108Z) [info] [extension:auth] Starting the login flow
(2023-10-05T00:27:44.181Z) [error] [extension:auth:client] Network error (Request failed with status code 400)
(2023-10-05T00:27:44.183Z) [error] [extension:auth:controller] retrieving the redirect URL failed: {"error":"Network error (Request failed with status code 400)"}
(2023-10-05T00:27:44.184Z) [error] [extension:auth] The sign in flow has failed: {"error":{"reason":"Error","details":"Network error (Request failed with status code 400)"}}
(2023-10-05T00:27:44.186Z) [info] [extension:sidebar:manager] resetting the login state to signin
(2023-10-05T00:28:08.803Z) [info] [extension:htmlProvider] getting console panel HTML
(2023-10-05T00:28:10.562Z) [info] [extension:Console:provider] Message from Console: {"type":"SEND_ANALYTICS","payload":{"action":"init","category":"console","label":"","value":1}}
(2023-10-05T00:28:10.565Z) [info] [extension:Console:provider] Message from Console: {"type":"promise-message","payload":{"uid":"d705f001-b0b4-4c7f-95e1-6e7205cd04c8","originalMessage":{"type":"SESSION_STORAGE","payload":{"method":"getItem","storageType":"KV","key":"::Console:default-timeline"}}}}
(2023-10-05T00:28:10.566Z) [info] [extension:Console:provider] Send message to webview: {"type":"promise-message-d705f001-b0b4-4c7f-95e1-6e7205cd04c8"}
(2023-10-05T00:28:10.695Z) [info] [extension:sidebar:manager] set login state to busy
(2023-10-05T00:28:10.696Z) [info] [extension:auth] Starting the login flow
(2023-10-05T00:28:10.753Z) [error] [extension:auth:client] Network error (Request failed with status code 400)
(2023-10-05T00:28:10.760Z) [error] [extension:auth:controller] retrieving the redirect URL failed: {"error":"Network error (Request failed with status code 400)"}
(2023-10-05T00:28:10.776Z) [error] [extension:auth] The sign in flow has failed: {"error":{"reason":"Error","details":"Network error (Request failed with status code 400)"}}
(2023-10-05T00:28:10.779Z) [info] [extension:sidebar:manager] resetting the login state to signin

**Comment by pankajk07** [comment]
@danocolombo @ravthiru Can you please update the extension to the latest version and try login in again?

**Comment by danocolombo** [comment]
Thank you @pankajk07 - the issue is resolved and I can use the Postman extension in VS code as expected.
