### ISSUE TITLE
VSCode Postman Extension uses the `Initial` value instead of the `Current` environment variable for `Code Snippet`

### ISSUE THREAD

**Issue by okarin-sama** [a85/POSTMan-Chrome-Extension#12184]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Using the `pre-request script` to set the current value of the `environment variable - collection` was always using the `initial` value and not the new value created on the `current` value for code snippet.

### Initial Value

![CleanShot 2023-07-26 at 14 33 30@2x](https://github.com/postmanlabs/postman-app-support/assets/17843586/600550a4-801e-428d-9a32-094df51d6a6e)

### Current Value (will change every-request)
![CleanShot 2023-07-26 at 14 36 27@2x](https://github.com/postmanlabs/postman-app-support/assets/17843586/f9a7fac8-1ab0-4f43-b87c-f90050742a7b)

### Code Snippet (every request)
![CleanShot 2023-07-26 at 14 34 34@2x](https://github.com/postmanlabs/postman-app-support/assets/17843586/8bb5f20e-66d2-4bce-9e63-a02cb0a2e472)

### Steps To Reproduce

1. Set Any `initial value` on the collection variable let's say `HOST` variable.
2. Set Any `current value` on the `HOST` variable but not the same with the `initial value`
3. use `{{HOST}}` as path for a request or body request; any will suffice.
4. Observe that the `initial value` was being use instead of the `current value` inside the `code snippet` 

### Operating System

macOs M1

### Postman Version

0.4.1

### Postman Platform

Other

### User Account Type

Signed In User

**Comment by theshubhamjoshi** [comment]
Hello @okarin-sama, this issue is now fixed in the latest update of the Postman VSCode extension. Please update to version 0.5.4 to use this feature. Thank you for your patience!
