### ISSUE TITLE
VSCode Extension no longer able to change view from top to bottom to side to side.

### ISSUE THREAD

**Issue by ScottConway** [a85/POSTMan-Chrome-Extension#12189]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

In the latest update (0.5.1) to the VS Code extension the button in the request or response panes that allowed toggling from a top to bottom view to a side to side view is no longer available.    

This is also called "Single Paned View" and "Two Paned View" 

### Steps To Reproduce

Update Postman extension in VS Code to 0.5.1

Send a request to a service. 

in request and response panes there is no longer an option to change panel layout.  

### Operating System

mac osX

### Postman Version

0.5.1 vs code postman extension

### Postman Platform

Other

### User Account Type

Signed In User

**Comment by giridharvc7** [comment]
This seems to be a regression. We'll raise a fix soon and keep posted here on this.

**Comment by pankajk07** [comment]
@ScottConway We have released a new version (`v0.5.2`) with the fix. Please update the extension and try it out.

**Comment by ScottConway** [comment]
I just downloaded the new extension and it works perfectly!    Thank you so much for the quick response!!
