### ISSUE TITLE
VSCode Postman Extension does not console.log (no button) or is not console logged in VSCode

### ISSUE THREAD

**Issue by fjuza1** [a85/POSTMan-Chrome-Extension#12187]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

In VScode postman extension there is nothing logged, there is no place for logs to be displayed

![image](https://github.com/postmanlabs/postman-app-support/assets/104192489/50178008-b0bd-4fde-a33b-63c62aa791fb)

### Describe the solution you'd like

Please add console.log tab as it is in Postman App

### Describe alternatives you've considered

Maybe if possible , please allow vscode log to be displayed in vscode itself

**Comment by giridharvc7** [comment]
Thank you for the feedback, we'll be releasing the console soon. We'll keep you posted in this thread as we progress

**Comment by olawalejuwonm** [comment]
Is it live now?

**Comment by SonarSaied** [comment]
yes seems like it is live now.

**Comment by pankajk07** [comment]
@olawalejuwonm Yes this was released as part of latest version(`v0.8.0`) of the extension. Please try it out and share your feedback.
