### ISSUE TITLE
Flows: Evaluate block not leveraging "get variable"

### ISSUE THREAD

**Issue by APidgeonAtb** [a85/POSTMan-Chrome-Extension#12183]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

I have an evaluate block to search and return an ID, based on a previous ID I've saved into a variable.   However, if I use the variable in the evaluate block, I get a null return.  

If I use the ID itself as a string to find the value in my set of arrays, it works fine.

With the value as a string:
<img width="352" alt="Screenshot 2023-07-25 at 2 19 35 PM" src="https://github.com/postmanlabs/postman-app-support/assets/110123838/0325df58-a3cf-4427-9b9d-f2b40240b0eb">

Using variable (which has the same string value set)
<img width="333" alt="Screenshot 2023-07-25 at 2 30 48 PM" src="https://github.com/postmanlabs/postman-app-support/assets/110123838/201239ca-00c7-4a26-8154-41e9c913e4fa">

### Steps To Reproduce

1. Have a call that returns a body that has a set of array values.   My json will respond like so:

<img width="180" alt="Screenshot 2023-07-25 at 2 33 18 PM" src="https://github.com/postmanlabs/postman-app-support/assets/110123838/2e4cff87-3190-4072-99a4-58cfb3600c7c">

2. Out of those 2 values in each record, I need to find a "their_did" value that matches a specific value - then find another ID present in that specific record.  

I've used the evaluate to filter the results to capture that ID in a separate variable.  

This does not work if I use a variable.  But does work if I replace the variable with a string.

### Operating System

MacOS

### Postman Version

Version 10.16.0

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by rabbah** [comment]
I believe this is an FQL quirk, you can assign the variable first

$val := varName;
then use `$val` in the filter expression.
