### ISSUE TITLE
Postman API publishing endpoint

### ISSUE THREAD

**Issue by dmitry-9972** [a85/POSTMan-Chrome-Extension#12192]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

I would like to create a completely automatic flow of creating, uploading to Postman and publishing the API of my project.
I can create API and collection using REST-request to the Postman developers API, but there is no endpoint for publishing this uploaded API. I have to log in to Postman and press "publish".
![image](https://github.com/postmanlabs/postman-app-support/assets/104809763/33a96d75-c1bc-4be3-acbc-a527c628ceaf)

### Describe the solution you'd like

Could you please implement publishing endpoint? Thank you.

**Comment by shivangibajpai12** [comment]
Hi @dmitry-9972,  [here](https://www.postman.com/postman/workspace/postman-public-workspace/request/12959542-46f17127-f197-43b4-83cb-41cbccbdd38c?ctx=documentation) is the publishing endpoint reference which supports the functionality to publish a version in an API.

**Comment by dmitry-9972** [comment]
Hi @insomniac12 , thank you so much, that's what I need.

**Comment by shashankawasthi88** [comment]
@dmitry-9972 there is also a Postman CLI command if you want to achieve this using a CLI - https://learning.postman.com/docs/postman-cli/postman-cli-options/#publishing-an-api-version
