### ISSUE TITLE
Vscode extension, not correct work invirement

### ISSUE THREAD

**Issue by ravshancha** [a85/POSTMan-Chrome-Extension#12198]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

1. sign in with vscode, but no cloneble envirment
2. add new envirment but no full length in request

### Steps To Reproduce

1. signin
2. envirement
3. requst

### Screenshots or Videos

![Screenshot 2023-07-28 at 11 42 57](https://github.com/postmanlabs/postman-app-support/assets/15638322/e58a3094-58c6-40e2-bb53-76efcfb62947)
![Screenshot 2023-07-28 at 11 43 02](https://github.com/postmanlabs/postman-app-support/assets/15638322/b5016be5-538e-4ef2-8b74-1d47d8f43355)

### Operating System

macos vscode extension

### Postman Version

v0.5.2

### Postman Platform

Other

### User Account Type

Signed In User

### Additional Context?

no envirement

**Comment by pankajk07** [comment]
@ravshancha Thanks for reporting the issue. This will be fixed in the upcoming release.

**Comment by theshubhamjoshi** [comment]
Hello @ravshancha , this issue is now fixed in the latest update of the Postman VSCode extension. Please update to version 0.5.4 to use this feature. Thank you for your patience!
