### ISSUE TITLE
Save as response doesn't work

### ISSUE THREAD

**Issue by ranielisilveira** [a85/POSTMan-Chrome-Extension#12193]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

When try to save the response, the tab is looping.

### Steps To Reproduce

When try to save the response, the tab is looping.

### Screenshots or Videos

![image](https://github.com/postmanlabs/postman-app-support/assets/74984047/ac299aaf-ec9b-4fe1-bf83-0e834c299aa4)

### Operating System

LInux

### Postman Version

0.5.2

### Postman Platform

Other

### User Account Type

Signed In User

**Comment by pankajk07** [comment]
@ranielisilveira Thanks for reporting the issue. Can you please answer the following questions to help us debug the issue?

1. Is this issue reproducible with all of the collections or specific collections
2. Is it reproducible every time or intermittently?
3. Does closing and re-opening the VS Code windows solve this issue?

**Comment by ranielisilveira** [comment]
1- Yes
2- Yes
3- No

Em sex., 28 de jul. de 2023 às 03:22, Pankaj Khandelwal <
***@***.***> escreveu:

**Comment by kartikjain26** [comment]
@ranielisilveira Could you update the vscode extension and try this again ?

**Comment by ranielisilveira** [comment]
I forgot about this topic that opens.

I had already updated, uninstalled and installed again.

Basically the problem was in postman itself. Because the interface didn't even open.
As the days went by, it started working again.

**Comment by pankajk07** [comment]
@ranielisilveira Thanks for sharing the update. As the `Save as response` feature is working, I am closing this issue. Feel free to open this issue or create a new one if the problem re-appears or you face any other issue.
