### ISSUE TITLE
Postbot fails to generate tests from a valid JSON response. Says Postbot can only generate scripts for JSON responses at the moment. Postman ver : 10.16.5 on Mac

### ISSUE THREAD

**Issue by soumikchakraborty2010** [a85/POSTMan-Chrome-Extension#12208]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

**Postbot fails to generate tests from a valid JSON response. Says Postbot can only generate scripts for JSON responses at the moment. Postman ver : 10.16.5 on Mac**

I have a JSON response like below. When I ask postbot to generate tests, it fails and says Postbot can only generate scripts for JSON responses at the moment. 
This is a valid JSON response. 
**The response header says Content type : **application/hal+json**** 
Is this because of the content type ? This **application/hal+json.** is represents data in the Hypertext Application Language (HAL) format using JSON as the data structure. HAL is a format that extends JSON to include hypermedia links, which provide navigation and resource linkage information. It's often used for building hypermedia-driven APIs where clients can navigate between resources using these embedded links. 
Postbot does not support this yet ? 
[
    "EMAIL__SHADOW_DETAIL",
    "HTTPSENABLE",
    "EMAIL__SMTP__PASSWORD",
    "SECURITY__PORT_ACCESS__TCP443",
    "PRINT__SUPPLY_NOTIFICATIONS__MAGENTA_CARTRIDGE_NEARLY_LOW_BEHAVIOR",
    "PRINT__POSTSCRIPT__WAIT_TIMEOUT",
    "PAPER__CUSTOM_SCAN_SIZES__CUSTOM1_WIDTH",
    "EMAIL__SMTP__NTLM_DOMAIN",
    "mfp.networkScan.backgroundDetection",
    "EMAIL__ALERTS_WASTE_TONER_NEARLY_FULL_1",
    "GENERAL__CUSTOM_MSG__YELLOW_TONER__MSG_SELECT",
    "PAPER__WEIGHT__LABELS",
    "SECURITY__IPSEC__PRE_SHARED_KEY_AUTHENTICATED_CONNECTIONS__HOST1__ADDRESS"
]

### Steps To Reproduce

Postbot is unable to generate tests from  a JSON response. The content/type in the response header is application/hal+json. 

### Screenshots or Videos

https://github.com/postmanlabs/postman-app-support/assets/109496759/0eb153a7-64aa-424d-9ebf-c8f3f3a2cefe

### Operating System

macOS

### Postman Version

 10.16.5

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by abhijitkane** [comment]
Thanks @soumikchakraborty2010 for reporting this. We're currently working on this, and will share an update soon :)
cc @ronork

**Comment by soumikchakraborty2010** [comment]
**For the time being, I am following an workaround which seems to work for this scenario.** 
I am adding a header in the request **"accept" : application/json**. 
For this the response header after the API call has the header content-type as "application/json" instead of "application/hal+json". And then, the postbot test creation works seamlessly. 

This is not a fix. So, looking forward for a proper fix from Postbot team (c/o @abhijitkane ). 
This I am following as a workaround for now until a fix is available. 
So, posting it here for awareness only.

**Comment by abhijitkane** [comment]
@soumikchakraborty2010 We've pushed out a fix for this in the latest Postman version. Postbot will be able to generate scripts for any JSON response, irrespective of the Content-Type header.

**Comment by soumikchakraborty2010** [comment]
Thanks @abhijitkane !
Will check when the fix is available in next Postman update and close this issue after validation.

**Comment by SterlingChin** [comment]
@soumikchakraborty2010, have you been able to validate that this is no longer an issue? Postman v10.18.8 is the latest version and will include the fix for this issue.

**Comment by soumikchakraborty2010** [comment]
Hi,
Yes. I was able to validate that this is working fine.

Thanks.
