### ISSUE TITLE
Postman App on Windows backend calls uses a User Agent that indicates older browsers that may be blocked

### ISSUE THREAD

**Issue by giwleb** [a85/POSTMan-Chrome-Extension#12209]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

This was reported previously but closed (https://github.com/postmanlabs/postman-app-support/issues/8826)

Our postman app recently refused to start with errors like "that should not happen" or "unable to load data" or simple hangs. Behind the scenes our infosec folks determined that Postman is using User Agents like "Microsoft IE 6.x (Mozilla/4.0..." or "Google Chrome (100.x) (Mozilla/5.0...". Both of these are quite old and no longer allowed by our internet security endpoint software (zscaler) via new policies set by our IT, so Postman will not start

### Steps To Reproduce

Install a tool that will block requests using certain user agents from traversing to the network. We use zscaler. 

### Screenshots or Videos

![image](https://github.com/postmanlabs/postman-app-support/assets/28053992/bfacf16e-cb8f-4259-accb-661111b6aec1)

### Operating System

Windows 11

### Postman Version

10.16.5

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by giwleb** [comment]
Here are images of sampled requests by the apps, and the reported user agent captured (and blocked)

![image (1)](https://github.com/postmanlabs/postman-app-support/assets/28053992/966f7fea-4b22-4e9f-8754-92e447b0b0fe)
![image](https://github.com/postmanlabs/postman-app-support/assets/28053992/b49fd871-252c-4a3b-9b59-65cdd15bf10c)

**Comment by dapperdanhorvath** [comment]
I am also unable to use Postman when Zscaler cloud proxy is active for the same reason. I am on Postman 10.16.9 but it's sending the exact same User-Agent string as you have posted. The only way around this is to create bypass rules for Postman endpoints in Zscaler cloud proxy, which is not ideal. Chrome version 100 is almost 18 months old so it's reasonable that this should be blocked.

As a side note, Electron 18.3.5 hit [EOL](https://www.electronjs.org/docs/latest/tutorial/electron-timelines) on September 27, 2022. This part isn't directly causing an issue but is concerning that Postman appears to still be using it.

**Comment by jlemley** [comment]
See also #12168

**Comment by giwleb** [comment]
Closing a a duplicate of #12168

**Comment by giwleb** [comment]
closing as a duplicate of #12168
