### ISSUE TITLE
Sync Beta - Imported\Shared Collections not appearing in API Library

### ISSUE THREAD

**Issue by rharmaning** [a85/POSTMan-Chrome-Extension#1220]
App version (3.0.0.34)
1. Upload a Collection to be Shared\Synced with your Team via the 'Import' button
2. After Success message, view Team Collections screen to see new Collection

expected: newly upload Collection visible and available for subscription by team members

actual: no new Collection appears uploaded.

Note: When Navigating back to the 'Builder' screen and Team Section, the collection(s) appear to me in the Team section, but they don't appear to my Team members

**Comment by sobtiankit** [comment]
HI @rharmaning 

You need to explicitly share the collection. Hover over the imported collection, click on the 3 dots and click share. There you'll find the option to share either readonly or editable by anyone within the team.

**Comment by sobtiankit** [comment]
Closing issue. Please reopen if any doubts, or mail us at help@getpostman.com.
