### ISSUE TITLE
Fast variable value update (edit variables)

### ISSUE THREAD

**Issue by DenisLutsky** [a85/POSTMan-Chrome-Extension#12217]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

When you need to set a value or edit a variable value you need to 
Select collection > Variables tab > Find and change the value for your variable > Save
Too many moves 

### Describe the solution you'd like

![image](https://github.com/postmanlabs/postman-app-support/assets/116076603/da96669b-2a10-454d-9f99-e7163365369b)
add the button to fast edit in variable overview near the "copy" button

### Describe alternatives you've considered

change variable value type from text to input, to have availability to easily edit variables from address bar ![image](https://github.com/postmanlabs/postman-app-support/assets/116076603/293b5c84-a4cc-4167-8092-35a9b759add9)
the

**Comment by DenisLutsky** [comment]
or at least by pressing CTRL+L-click go to variable in variables list

**Comment by coditva** [comment]
@DenisLutsky Thanks for reaching out! I've noted this as a feature request. We'll notify on this thread when we have updates.

**Comment by KochVA** [comment]
+1

**Comment by arvenfal** [comment]
Can you please update me on the status of the feature request? There are several tickets related to this request, and it would be great if users could change their variables.



https://github.com/postmanlabs/postman-app-support/issues/5006

**Comment by DenisLutsky** [comment]
> Can you please update me on the status of the feature request? There are several tickets related to this request, and it would be great if users could change their variables.
> 
> #5006

on my local machine, I have the latest version and I don't see any changes like I proposed in that issue
![image](https://github.com/postmanlabs/postman-app-support/assets/116076603/b1ae6e19-8c83-4942-ad03-25f9fc15f888)

**Comment by skatikia** [comment]
Hi all! This took a while, but I'm glad to announce the completion of our work on this! 🎉

With Postman **V11.14**, we have rolled out multiple improvements to our variables interface, including **the ability to update variable values on the go**.

![edit-value](https://github.com/user-attachments/assets/d74e78b6-f1e4-4986-b4d8-9d8ae85e4310)

I hope you like this change as much as we do! Update your app to start working with this change and many more, and let us know what you feel ([over a call](https://calendly.com/shobhit-katikia/meet-with-shobhit) or just drop an email to [shobhit.katikia@postman.com](mailto:shobhit.katikia@postman.com)).

[Check out the Postman V11.14 release note](https://arc.net/l/quote/vtemyulc)
