### ISSUE TITLE
[VS Code Extension] Comments into request body

### ISSUE THREAD

**Issue by JuanDCQ-Meli** [a85/POSTMan-Chrome-Extension#12210]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

When I use the Postman app, I can add comments into the body request without getting a 400 answer, but using the VS code extension I got that answer
**Using the Postman App this works fine**
![image](https://github.com/postmanlabs/postman-app-support/assets/121261241/cd86e09b-b5d3-48ba-aef5-d43320591171)

But using the VS code extension i got this
`"message": "Invalid JSON: Unexpected character ('/' (code 47)): maybe a (non-standard) comment? (not recognized as one since Feature 'ALLOW_COMMENTS' not enabled for parser)\n at [Source: UNKNOWN; line: 7, column: 84]"`

### Describe the solution you'd like

It would be nice to be able to include comments into the request body the same way it works in the app

### Describe alternatives you've considered

I've tried using a pre-request Script, adding the content type header with "application/json" value but it still remains the same:
`if (pm?.request?.body?.options?.raw?.language === 'json') { const rawData = pm.request.body.toString(); const strippedData = rawData.replace( /\\"|"(?:\\"|[^"])*"|(\/\/.*|\/\*[\s\S]*?\*\/)/g, (m, g) => g ? "" : m ); pm.request.body.update(JSON.stringify(JSON.parse(strippedData))); }`

**Comment by pankajk07** [comment]
@JuanDCQ-Meli We have fixed this issue in the latest update of the extension. Please update your extension and try it out.
