### ISSUE TITLE
Share collection via "Run in Postman" button has broken link 

### ISSUE THREAD

**Issue by IhorHolovatsky** [a85/POSTMan-Chrome-Extension#12216]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

When sharing collection via "Run in Postman" button, the generated URL link doesn't contain the Postman domain name. 
```https://allvuesystemsundefined```.

Let me know if more information is needed. 
Thanks!

### Steps To Reproduce

1. Open any collection.
2. Click "Share"
3. Open "Via Run in Postman" tab
4. Select "Team" in "Who can view this collection?" question
5. Click "Next"
6. See the link generated in "Embed code" textarea

**Expected Result**: See valid URL link (example: https://allvuesystems.postman.com)
**Actual Result**: Invalid URL link (example: https://allvuesystemsundefined)

### Screenshots or Videos

![image](https://github.com/postmanlabs/postman-app-support/assets/12159879/a63b03bd-4b4f-4a2c-8ae0-489be68bf819)

### Operating System

Windows

### Postman Version

10.16.6

### Postman Platform

Postman App

### User Account Type

Signed In User

### Additional Context?

The collection I'm trying to share is located in the team workspace.

**Comment by bhargavkaranam** [comment]
@IhorHolovatsky Thanks for reporting this. While we push out a fix in the next couple of hours, you can use Postman on web to get unblocked and generate the Run in Postman code (Login to https://allvuesystems.postman.co).

**Comment by bhargavkaranam** [comment]
@IhorHolovatsky This issue should now be fixed, you can update the app and let us know!

**Comment by IhorHolovatsky** [comment]
Yes, it's working, thanks for the super-fast fix @bhargavkaranam!

**Comment by Drishyamalu** [comment]
Reset password instagram account

**Comment by Drishyamalu** [comment]
Accuont is hacked
