### ISSUE TITLE
Add some request api in Postman API

### ISSUE THREAD

**Issue by kings1990** [a85/POSTMan-Chrome-Extension#12225]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

For now, there is no api to create a request by an endpoint or update the request by an endpoint.

I have seen the API here but currently not available.

![image](https://github.com/postmanlabs/postman-app-support/assets/8969637/27c1cf84-22bf-44bb-b4ba-6234d00bb191)

### Describe the solution you'd like

1. Add an endpoint explicitly to import a request.
2. Add an endpoint to update a request by name or id

**Comment by maticardenas** [comment]
@kings1990 I think I've come into the same concern than you, I happened to find an endpoint for this but not within the `Postman API` collection but in the [Collection Individual Items](https://www.postman.com/postman/workspace/postman-public-workspace/folder/16473433-87998c7f-5047-42a5-a5e4-0d60494e6699) one. 

I think that's the one you are looking for?

**Comment by kings1990** [comment]
@maticardenas Thanks very much. It is what I looking for!
