### ISSUE TITLE
the drop-down list is not selected as the main one

### ISSUE THREAD

**Issue by radioactive1337** [a85/POSTMan-Chrome-Extension#12229]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

there is no way to work with keyboard arrows with a drop-down list that is displayed on top of another list (interaction with the list that is in the background)

### Steps To Reproduce

1. create a new request
2. click in the query string
3. type in "{"

### Screenshots or Videos

https://github.com/postmanlabs/postman-app-support/assets/101940002/927706d6-efe1-4a97-87de-acf0df15b58e

### Operating System

windows 11

### Postman Version

10.17.0

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by giridharvc7** [comment]
Thank you for reporting the bug, we'll keep you posted here on the updates.

**Comment by sandeep-singh-pstmn** [comment]
@radioactive1337 this fixed in the latest version you can try
