### ISSUE TITLE
Link disappears after saving in new Postman Editor

### ISSUE THREAD

**Issue by NelliaS** [a85/POSTMan-Chrome-Extension#12221]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

We have recently noticed that with the change of editor, all links in our documentation have become empty (more precisely, when you click on them, the documentation itself opens). When we try to add a link (again), it is removed, just after saving. I am attaching a video. 

### Steps To Reproduce

1. Open a documentation
2. Try to add a link
3. Save
4. Watch your link disappear

### Screenshots or Videos

https://github.com/postmanlabs/postman-app-support/assets/72438679/f5c25a9f-1416-433a-b862-6db55b043b23

### Operating System

macOS (but we tried on Linux as well)

### Postman Version

10.16.8

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by kartikjain26** [comment]
@NelliaS Thanks for reporting this issue. We'll triage it and keep you updated

**Comment by NelliaS** [comment]
> @NelliaS Thanks for reporting this issue. We'll triage it and keep you updated

@kartikjain26 Hello, thanks. Can I ask about expected time horizon for this? Our company documentations lack all the necessary links until this issue is solved...

**Comment by sony-mathew** [comment]
Hey @NelliaS , we have fixed this in the latest version of the Postman app (v10.17). If you don't see the update for this version now, it will be available in the next few days (this is being gradually rolled out at the moment).

**Comment by sony-mathew** [comment]
Hey @NelliaS, this issue is fixed in the latest version of the app. Closing this ticket.
