### ISSUE TITLE
cannot use post command

### ISSUE THREAD

**Issue by itsnitu028** [a85/POSTMan-Chrome-Extension#12226]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

i am not able to post the data.....in browser the data is perfectely stored and fetched...but in postman ..i am getting 'sending a request' and its not sending the data 

### Steps To Reproduce

/*my index.js code*/
import bodyParser from "body-parser";
import express from "express";
import { dirname } from "path";
import { fileURLToPath } from "url";
const __dirname = dirname(fileURLToPath(import.meta.url));

const app = express();
const port = 3000;
app.use(bodyParser.urlencoded({extended:true}));
app.get("/", (req, res) => {
  res.sendFile(__dirname + "/public/index.html");
});
app.post("/submit",(req,res)=>{
    console.log(req.body);
});
app.listen(port, () => {
  console.log(`Listening on port ${port}`);
});
The error is "its not showing any response"

### Screenshots or Videos

![localhost_3000_submit_street=hi pet=hi - My Workspace 11-08-2023 05_17_48](https://github.com/postmanlabs/postman-app-support/assets/128230467/d6f778e3-41fa-4287-8376-43bc5dbe6de0)

### Operating System

windows

### Postman Version

10.17.0

### Postman Platform

Both

### User Account Type

Signed In User

**Comment by sandeep-singh-pstmn** [comment]
@itsnitu028 As I can see from the server data you provided, you are not sending any responses from the server. I have modified the server code. 

```
import bodyParser from "body-parser";
import express from "express";
import { dirname } from "path";
import { fileURLToPath } from "url";
const __dirname = dirname(fileURLToPath(import.meta.url));

const app = express();
const port = 3000;
app.use(bodyParser.urlencoded({extended:true}));
app.get("/", (req, res) => {
res.sendFile(__dirname + "/public/index.html");
});
app.post("/submit",(req,res)=>{
  console.log(req.body);
  res.send(req.body);
});
app.listen(port, () => {
console.log(`Listening on port ${port}`);
});
```


Refer to this video
https://github.com/postmanlabs/postman-app-support/assets/85243040/62431dbe-5af7-401d-a97c-bfc7aed925f0

Please let us know if this resolves the issue
