### ISSUE TITLE
Error - Could not get any response

### ISSUE THREAD

**Issue by sameerpanicker** [a85/POSTMan-Chrome-Extension#1223]
I have 2 DIRECT URLs and a VIP for connecting to these URLs. I am using the latest POSTMAN Client. I am successfully able to hit the DIRECT URLs but when I hit the VIP, I get an  error saying
Could not get any response

I am able to connect to many other services using POSTMAN, only this one is failing. I am able to connect this VIP URL successfully using SOAP UI. Please let me know how can I get this working.

**Comment by sameerpanicker** [comment]
Following up on this..

**Comment by abhijitkane** [comment]
What do you see in the Network tab of the DevTools window? (http://blog.getpostman.com/2015/06/13/debugging-postman-requests/)

Can you try to open the same VIP URL in Chrome? If it shows an SSL error, you might have to import the certificate - http://blog.getpostman.com/2014/01/28/using-self-signed-certificates-with-postman/

**Comment by sameerpanicker** [comment]
The problem was due to the Server Certificate installed on the server. The VIP was configured with a particular named certificated. Once I updated the certificate on the server with the correct one, it worked. Thanks for the help above.

**Comment by geocine** [comment]
This will also happen if an API is returning no status code
