### ISSUE TITLE
Collection Backup Integration with GitLab fails when multiple Integrations are set up

### ISSUE THREAD

**Issue by ayamakh123** [a85/POSTMan-Chrome-Extension#12238]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Hello, 

We have been getting "Unknown error encountered during integration execution."  in the Integrations -> "Backup a Collection" with GitLab repository.
The error is not persistent, it occurs intermittently, without a pattern.
We have noticed that error occurs to collections that have multiple integrations setup for the same repository.

### Steps To Reproduce

1. Add an Backup Integration for a sample collection A to a Gitlab repository R, to folder Postman_Collections.
2. Add another Backup Integration for a same collection A to the same GitLab repository R, to folder Postman_Collections/SubFolder X
3. Add another Backup Integration for a same collection A to the same GitLab repository R, to folder Postman_Collections/SubFolder Y
4. Make updates to Collection A and notice that one (or more) of the three integrations fails.

<img width="285" alt="image" src="https://github.com/postmanlabs/postman-app-support/assets/119963130/cdd5c858-00d5-4bb7-a0a9-6426ee623cc2">
 

### Operating System

Windows

### Postman Version

10.17.2-230814-1237

### Postman Platform

Both

### User Account Type

Signed In User

### Additional Context?

Our use case for integrating same collection to the same repository but different folders: 
We want to run tests in  certain collections in the pipelines based on the different requirements. 
For example, for one type of pipeline we want to run tests from collections A, B, and C; and for another we want to run tests from collections B, E, and D. 
For ease of navigation, we want to group the collections in subfolders, such that in a pipeline we could just specify the subfolder X, instead of having to specify collections A, B, and C. 
Hence, we want to have subfolder X with backed up collections A, B, and C; and subfolder Y with backed up collections B, E, and D.
In the scenario above, collection B becomes backed to two folders within the same repository.

**Comment by aditi-umashankar** [comment]
Hey @ayamakh123 !
Thanks for raising the issue. We are able to reproduce it at our end and looks like this might be due to a race condition in calling Gitlab APIs. 
We are currently working on solving this problem. We will keep you posted once we have a timeline for the same.

**Comment by aditi-umashankar** [comment]
Hey @ayamakh123 !
This issue has been fixed. Could you let us know if your integrations run successfully now?

**Comment by ayamakh123** [comment]
Hello @aditi-umashankar ! 
Actually we are facing issues with regular integrations as of now. New back ups are resulting in empty files being added  (status of integration on the page is marked SUCCESS). And for previous integration we're getting an error message: 
`{"error":{"name":"integrationRunProxyError","details":{"title":"instanceNotFoundError","message":"We could not find the collection you are looking for","model":"collection","model_id":"XXXXXXXXXXX","owner":"XXXXXXX"}}}`

**Comment by aditi-umashankar** [comment]
Hey! Thank you for bringing the issue to our notice. We are currently working on a fix for it. We'll keep you posted on the updates.

**Comment by aditi-umashankar** [comment]
Hello @ayamakh123 !
We've rolled out a fix for the issue. Please let us know if the integration is working as expected or not. Thank you for your patience!

**Comment by jordanfun1** [comment]
Hello @aditi-umashankar, collections are backed up to the repositories now, however the format of the collection JSON is different (e.g. ordering of information, it's all on a single line now, etc.). We expect the integration to be formatted like how it is when it is exported manually as JSON through the Postman UI. Is there a way it could stay consistent with the format it was before?

**Comment by aditi-umashankar** [comment]
Hey @jordanfun1 !
The formatting is fixed - it is no longer on a single line, and it is indented as it was previously.

**Comment by fanthoni02** [comment]
@aditi-umashankar  thanks for fixing the indentation. but I think we do have another issue where the JSON structure is different like what @jordanfun1 mentioned. would it be possible to have the same structure like we do with exporting through the Postman GUI (like previous version / image number 1)? Right now the collection back up outputs the JSON with a different structure (2nd image)

First Image:
![image](https://github.com/postmanlabs/postman-app-support/assets/146248089/2a509297-ee75-4550-b7b1-336d30fe1311)

Second Image:
![image](https://github.com/postmanlabs/postman-app-support/assets/146248089/3b92c368-db41-4294-80de-6911d16acee3)

**Comment by aditi-umashankar** [comment]
We've fixed this now, the format should be the same as before.

**Comment by fanthoni02** [comment]
Thanks @aditi-umashankar

**Comment by aditi-umashankar** [comment]
Thank you @fanthoni02 and @ayamakh123 ! 
Closing this ticket now, but please reach out if you face any other issues and blockers.
