### ISSUE TITLE
If you run collection in postmancli, the test-script modified by postman gui is not reflected.

### ISSUE THREAD

**Issue by goddessbest83** [a85/POSTMan-Chrome-Extension#12237]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

When I executed the postman collection, I was able to check the number of results for it. However, when using postmancli, it was confirmed that the test-script added by postman gui was not included in the total number of results. It was the same when I logged out of cli and logged in again. When testing in cli, one request result shows the test-script result I added well, but the test-script count in the final result does not include what I added, and only the number of previous counts continues to be displayed. Also, if you count and add each request test result, it does not match the final result count.

### Steps To Reproduce

1. Run the postman collection.
2. In postman gui, add the test-script of the request in the corresponding collection.
3. Run the postman collection again.
4. The test-script added in number 2 is displayed in each request progress result, but the test-script count shown in the summary result section at the bottom does not include the result of the test-script added.

### Screenshots or Videos

<img width="623" alt="image" src="https://github.com/postmanlabs/postman-app-support/assets/68605803/1f37c06d-6655-4bfd-a24c-9c9e279824ae">
<img width="453" alt="image" src="https://github.com/postmanlabs/postman-app-support/assets/68605803/9a721e16-e80d-4a0c-997b-ff99a137ec6e">

### Operating System

macOS

### Postman Version

10.16.9

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by malvikach** [comment]
Hi @goddessbest83 Could you also share the command that you are using to run the collection.

**Comment by goddessbest83** [comment]
Hi @malvikach, 
I used this.

postman login --with-api-key {my postman api key}
postman collection run {my collection id} -e {my environment id}

**Comment by malvikach** [comment]
@goddessbest83 the command seems correct. 

Could you send us more details so we can investigate this further- which version of postman cli are you using? 
Could you also check the past runs data under Collection-> Runs-> Functional and share a screenshot with the discrepancy between postman cli results and runner results.

 Eg:
<img width="1001" alt="Screenshot 2023-08-17 at 1 23 37 PM" src="https://github.com/postmanlabs/postman-app-support/assets/89449769/3eb4ac25-2099-4398-af25-792b27f97b68">

**Comment by goddessbest83** [comment]
I think I misunderstood the "test-scripts" part of the "Postman CLI" overall result of the relationship between "pm.test" and "pm.expect" that I write on the "Tests" side. What proceeds as "pm.test" matches the "test-scripts" of the overall result, and what proceeds as "pm.expect" matches the "assertions" of the overall result and seems to be related to "All tests" on the Run side of the Postman GUI, is this correct?

**Comment by malvikach** [comment]
pm.test() matches the Assertions on the CLI Report and the "All Tests" on the GUI


The test-scripts section on the CLI report shows the total number of test scripts that were executed i.e. if your collection has 2 requests then the test-scripts will show a count of 4 because 2 test scripts belong to the 2 requests + a collection level test script is executed along with every request. 
The same logic applies to pre-request scripts as well. You can read more about scripts [here](https://learning.postman.com/docs/writing-scripts/intro-to-scripts/)

Let me know if this clarifies the doubt.

**Comment by goddessbest83** [comment]
I understand "pm.test() matches the Assertions on the CLI Report and the "All Tests" on the GUI". I misunderstood this as the number of test-scripts. Thank you for your time and reply. This is not an issue.
