### ISSUE TITLE
Cannot signin Postman anymore due to auto logging process

### ISSUE THREAD

**Issue by johan974** [a85/POSTMan-Chrome-Extension#12234]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

When signing in, the Postman app starts, I can select an account and am forwarded **automatically**. The postman app restarts (I guess) and I am NOT logged in. So I cannot signin at all. Very annoying .. Even re-installed everything (with the newest version), but it does not help. 

### Steps To Reproduce

1. Start the app. 
2. Signin in 
3. Select account
4. I get a message 'It's great to have you aboard, xxx Redirecting you to the Desktop App... ... the app restarts ... I am NOT signed in ... 
5. Repeat ... at step 1. 

### Operating System

Windows

### Postman Version

10.17.0

### Postman Platform

Postman App

### User Account Type

Signed In User

### Additional Context?

So sigining in gives a problem.

**Comment by pankajkumar005** [comment]
Hello @johan974 
We're sorry for the issues occurring while signing in to the App. Can you sign in after clearing the user app data (**% AppData % /Postman**)?
If this doesn't work, please get in touch with [support@postman.com](mailto:support@postman.com) with the following details. This will help us understand the issue and help you with the resolution.
- App logs (**%AppData%/Postman/logs**) 
  - Make sure the app is closed
  - Delete/cleanup the logs so far.
  - Reproduce the issue
- Har log files
  - Steps: [How to get Har logs](https://support.postman.com/hc/en-us/articles/360025298633-How-to-get-logs-from-the-Postman-Desktop-app#h_01G396RXACNXNC49N49ANFVVPW)
- App settings (**%AppData%/Postman/storage**)
- Is the network access behind a proxy?
- Is there any AntiVirus software running?

**Comment by johan974** [comment]
Thanks a lot, clearing %AppData%/Postman worked!
