### ISSUE TITLE
Cannot use 8099 port

### ISSUE THREAD

**Issue by m0rb1u5** [a85/POSTMan-Chrome-Extension#12236]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Cannot use 8099 port because postman use that port:

![image](https://github.com/postmanlabs/postman-app-support/assets/5566153/554b8495-0fbe-43df-9273-31da2b924415)

### Steps To Reproduce

Use the next commands in Powershell:
- Get-NetTCPConnection -LocalPort 8099
- Get-Process -PID <PID>

### Operating System

Windows

### Postman Version

10.17.1

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by webholik** [comment]
Hi [m0rb1u5](https://github.com/m0rb1u5), this port is used by Postman app to communicate with Postman Interceptor extension. You can use any other port or quit the Postman app to make port 8099 free.

**Comment by Suremotoo** [comment]
> Hi [m0rb1u5](https://github.com/m0rb1u5), this port is used by Postman app to communicate with Postman Interceptor extension. You can use any other port or quit the Postman app to make port 8099 free.

I strongly advise against using port 8099 for Postman as it is not developer-friendly to use commonly used ports. Since Postman communicates internally, why not consider using a less utilized port? The previous version of Postman did not use port 8099, so I hope this can be adjusted promptly.

**Comment by webholik** [comment]
Thank you for the feedback @Suremotoo. We'll take this into account.

**Comment by akshaydeo** [comment]
@Suremotoo thanks for this feedback. We are working on using some other ports in the coming releases. I will update this ticket as soon as its available 🙇‍♂️

**Comment by benhardy** [comment]
experiencing same. makes it impossible to do API testing when i can't change the port. Mac OSX, M1 chip

**Comment by slatlasdev** [comment]
Our local development uses port `8099`, conflicting with Postman. 
Additionally, when starting Postman after the local dev stack is already running, no error message is displayed, Postman just crashes. I had to go to the logs to see what the problem was:

```json
{
  "code": "EADDRINUSE",
  "errno": -48,
  "syscall": "listen",
  "address": "::",
  "port": 8099,
  "name": "Error",
  "message": "listen EADDRINUSE: address already in use :::8099",
  "stack": "Error: listen EADDRINUSE: address already in use :::8099\n    at Server.setupListenHandle [as _listen2] (node:net:1330:16)\n    at listenInCluster (node:net:1378:12)\n    at Server.listen (node:net:1465:7)\n    at new WebSocketServer (/Applications/Postman.app/Contents/Resources/app.asar/node_modules/ws/lib/websocket-server.js:97:20)\n    at Object.initialize (/Applications/Postman.app/Contents/Resources/app.asar/services/websocketServer.js:189:16)\n    at Object.initializeWebSocketServer (/Applications/Postman.app/Contents/Resources/app.asar/services/InterceptorConnection.js:126:21)\n    at /Applications/Postman.app/Contents/Resources/app.asar/main.js:530:33\n    at IpcMainImpl.customListener (/Applications/Postman.app/Contents/Resources/app.asar/sdk/ipc.js:27:7)\n    at IpcMainImpl.emit (node:events:390:28)\n    at IpcMainImpl.emit (node:domain:475:12)\n    at EventEmitter.<anonymous> (node:electron/js2c/browser_init:161:10780)\n    at EventEmitter.emit (node:events:390:28)\n    at EventEmitter.emit (node:domain:475:12)"
}
```

**Comment by BhushanKumarSingh** [comment]
Same issue with me as well after the latest update of Postman it created the issue
I am trying to start the service it throwing an error

Verify the connector's configuration, identify and stop any process that's listening on port 8099, or configure this application to listen on another port.

Is there any way to change to port for Postman in windows?

**Comment by varaisys** [comment]
Port 8099 is hardcoded in postman code websocketServer.js:11, its not configurable!
We were using snap, 'snap revert postman' helped, no such issue in previous version.

**Comment by akshaydeo** [comment]
We have disabled this port usage. You should be able to use 8099 port.

**Comment by vvasin** [comment]
AFAIU, you guys now use the port 15611? It's such a bad luck, but I used this port for personal purposes. I've chosen it randomly, and it took a while to believe it was blocked by the Postman app 😁
