### ISSUE TITLE
Chrome interceptor is not capturing POST or PUT requests

### ISSUE THREAD

**Issue by doubleforte** [a85/POSTMan-Chrome-Extension#12246]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

I've turned on an interceptor session via the Chrome extension (v3.0.0). The Postman app is recording all `GET` requests, but not anything else. 

### Steps To Reproduce

1. Start a new interceptor session with the Chrome extension.
2. Go to https://regex101.com (or wherever, this is just my example)
3. Notice that Postman has captured the initial page load -- a bunch of `GET` requests.
4. Enter some stuff into the fields and click "Save new Regex" in the sidebar. This triggers a `POST` request, which can be verified in the Network tab of the Devtools.
5. Notice that Postman has NOT captured the `POST`.

I've had similar results with `PUT`.

### Operating System

macOS 13.5

### Postman Version

10.17.2

### Postman Platform

Postman App

### User Account Type

Signed In User

### Additional Context?

This used to work, and I don't know when it stopped working. I tried downloading an older version of the app to get around the problem, but it just yelled at me for using an older version and wouldn't do anything until I updated. :( So I guess I'm stuck on the latest.

**Comment by akshaydeo** [comment]
@doubleforte thanks for reporting this issue. We are looking at it on priority. I will keep this thread updated 🙇‍♂️

**Comment by hiruthre** [comment]
Hi, Any ETA for this? Since its most important feature

**Comment by akshaydeo** [comment]
We have found that the request is getting captured but not visible in the recent requests view of the extension. 

For now, if you click on the "View In Postman" button on the interceptor, you can view the corresponding PUT or POST request. cc @agrwl-harsh 

We are working on the fix as we are speaking. We will push the updated extension to the store in the next couple of hours.

**Comment by akshaydeo** [comment]
We have uploaded the fixed build to Chrome Extension Store. It will take a day or two to complete the review. Fixed version is 3.0.1. 

Thank you for using Postman Interceptor 🙇‍♂️

**Comment by doubleforte** [comment]
Great. Thank you for the quick turnaround!

As part of finding a workaround for this, I learned that I can paste an entire curl command (copied from the Network tab) into the Postman url field and it will put all the headers and stuff into the request. Interceptor is easier but this feature is great and I wish I knew sooner. :)
