### ISSUE TITLE
Can't drag and move the requests to different folders

### ISSUE THREAD

**Issue by ShubhamGoswami-1** [a85/POSTMan-Chrome-Extension#12245]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Can't drag and move the requests to different folders. I am talking about the vscode extension package here 

### Steps To Reproduce

1. Make two folders named "ABC" and "XYZ"
2. Make a get request in the "ABC" folder
3. Now let's say you want to move the get request you made in "ABC" to "XYZ"
4. You can't drag and take the request to "XYZ"

### Operating System

Windows

### Postman Version

0.6.0 

### Postman Platform

Other

### User Account Type

Signed In User

**Comment by jackson-moore-87** [comment]
Will this fix be included in an upcoming release? It doesn't look like it was included in 0.16.0.

**Comment by Douda** [comment]
Not included in 0.17.0 either from what I can see.
Still not possible to drag or move requests

Edit : current workaround for me to organize my requests is to open the Postman windows client.
Not ideal, but it's an option as of now

**Comment by arimarsetzer** [comment]
I'm facing the same issue while working in VSCode and this is really annoying, anyone also is facing it?

**Comment by zachbakerdev** [comment]
Still an issue. Should this be reopened or a new issue created?

**Comment by raikoug** [comment]
I can confirm, the problem persists on vscode, everything is up to date.

**Comment by styk-tv** [comment]
not fixed in v1.2.1 (of VSC extension) - this doesn't bother anyone?

CC @sony-mathew since you created label for this before

**Comment by joabe-lucena** [comment]
still not fixed on `v1.2.1` 

A workaround for it is organizing your workspace folders though the postman`s web site
