### ISSUE TITLE
Able to convert the JSON provided to Gzip before sending the request

### ISSUE THREAD

**Issue by jaybhanushali3195** [a85/POSTMan-Chrome-Extension#12243]
### Is there an existing request for this feature?

- [x] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

No

### Describe the solution you'd like

I should be able to paste a JSON in body and that json can be automatically gzip compressed before being posted.

### Describe alternatives you've considered

Pre request script - it cannot modify request

**Comment by sandeep-singh-pstmn** [comment]
https://github.com/postmanlabs/postman-app-support/issues/4079
