### ISSUE TITLE
Google OAuth 2.0 clear credentials

### ISSUE THREAD

**Issue by richarddavenport** [a85/POSTMan-Chrome-Extension#1224]
I was able to successfully authenticate against google's api. Postman opened a window and prompted me to pick one of my google accounts, I picked one and it all worked. Now I would like to try with a different google account, but I am not prompted to pick one. Is there somewhere I can clear out my first google account I connected with?

**Comment by abhijitkane** [comment]
You can enable DevTools (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/), and enter the following in the console:

`chrome.identity.launchWebAuthFlow({'url': 'https://accounts.google.com/Logout?continue=http://google.com', 'interactive': false}, function(){if (chrome.runtime.lastError) {}});`

**Comment by richarddavenport** [comment]
Sweet. I was wondering how to get the developer tools open for the app. Now I can do it for all packed apps. Thanks!

**Comment by abhijitkane** [comment]
Note - In Postman v3.0.2, the Google logout process happens automatically when you click the 'Sign in with Google' button, so you always have the choice of selecting a different account.

**Comment by ghost** [comment]
Is it possible to do something similar in v4.2.0? I can't sign out of my current google oauth account.
