### ISSUE TITLE
Collection "Merge Changes" Diff broken after Postman API Collections PUT of unchanged forked collection

### ISSUE THREAD

**Issue by dswinscoe** [a85/POSTMan-Chrome-Extension#12250]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Sometime in the last 2 weeks, Merge Changes Diff output has changed and now shows all collections contents as "removed" and "added" after a Postman API Collection PUT of an unchanged existing collection, instead of previous output of "no changes."

### Steps To Reproduce

1. Download a forked collection with Postman API Collection GET
2. PUT unchanged collection with Postman API
3. GET collection again and compare locally, to verify the only difference is id/uid.
4. Click Merge changes and note all contents removed and added.
5. Should be no changes, since all that's changed are ids and uids 

### Operating System

macOS

### Postman Version

10.17.2

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by dswinscoe** [comment]
Seems that id and uid are now somehow considered in the diff. This of course renders it useless. 

This bug severely limits the use of Postman API collection updates in team development. Thankfully, forking is still functional, so its possible to fork after PUT to track changes, but PR Review is impossible.

**Comment by sony-mathew** [comment]
@dswinscoe We will take a look into this and get back.

**Comment by dswinscoe** [comment]
@sony-mathew, @AvanishPai  Any progress on this critical issue yet?

**Comment by kartikjain26** [comment]
@dswinscoe We are looking into this issue closely. Will update this thread when the fix is available or a workaround for your workflow.

**Comment by dswinscoe** [comment]
@kartikjain26 It's been a month, and sadly, I see no progress here. Collection version control is such an important functionality, esp. for my automated test framework, and it's surprising to me that this bug hasn't yet been replicated or otherwise documented. Has it been replicated? Some feedback would be highly appreciated. Thank you.

**Comment by dswinscoe** [comment]
The problem persists, and I can only assume with zero feedback or comment that this bug is not on the radar at all. Odd, since you'd think diff'ing collections and change control, regardless of the nature of the change, manual or Postman API, would have much more priority. Some final feedback to close out this issue would be at the very least professional.

**Comment by kartikjain26** [comment]
@dswinscoe We have already released a fix for this issue. With the steps mentioned in the issue I can confirm that the diff where all entities are removed and added is no longer present.
Could you also verify on your end once.

I followed these steps:

1. Download a forked collection with Postman API Collection GET
2. PUT unchanged collection with Postman API
3. GET collection again and compare locally, (Note that when you GET this, there should not be any id/uids changed now)
4. Click Merge changes and note all contents removed and added.
5. Should be no changes, not even ids

cc @sony-mathew

**Comment by dswinscoe** [comment]
@kartikjain26 Thank you so much for the feedback and fix! I can confirm that "Merge Changes" is again functional for the steps indicated in the issue.
