### ISSUE TITLE
Unable to open postman snap package on ubuntu 22.04.3 worked a week ago

### ISSUE THREAD

**Issue by ErikMekiassen** [a85/POSTMan-Chrome-Extension#12259]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

when running sudo snap run postman:
mkdir: cannot create directory '/run/user/0': Permission denied
The disableGPU setting is set to undefined
Not disabling GPU
Authorization required, but no authorization protocol specified
[257678:0823/100233.725950:ERROR:ozone_platform_x11.cc(248)] Missing X server or $DISPLAY
[257678:0823/100233.726000:ERROR:env.cc(225)] The platform failed to initialize.  Exiting.
[0823/100233.732060:ERROR:scoped_ptrace_attach.cc(27)] ptrace: Operation not permitted (1)
Segmentation fault

Im running gnome v42.9 and im using multiple gnome tweaks as well as https://github.com/vinceliuice/WhiteSur-gtk-theme (macOS theme)
but this was set up before the postman issue happened.

the machine has restarted at least once since the last time i managed to run it.

Version?
not sure as i cant open it but it says the folder snap tries to run is 215? 215, current and common folder is empty

just tried to reinstall postman same error

### Steps To Reproduce

- install postman from ubuntu software or possibly snap install postman
- sudo snap run postman

### Operating System

linux

### Postman Version

not sure look in description

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by RaphOb** [comment]
Same here with PopOs

**Comment by ErikMekiassen** [comment]
If you have it installed on snap try sudo snap revert snapd. that fixed it for me.

**Comment by projack1989** [comment]
Postman still not stable on Ubuntu 22.00 until now
I have tried install and uninstal from snap but stil not working and force quit
