### ISSUE TITLE
Feature Request: Documentation Exporter

### ISSUE THREAD

**Issue by ghost** [a85/POSTMan-Chrome-Extension#1225]
If the documentation would be unified/harmonised in some way, an html-export would be awsome.
A perfect example would be something like the swagger-ui: http://petstore.swagger.io/

And btw: A very good buy-argument.

**Comment by syney** [comment]
Strongly agree, its really good Idea

**Comment by a85** [comment]
Closing as duplicate of #204. This is on it's way!
