### ISSUE TITLE
vscode extension doesnt load

### ISSUE THREAD

**Issue by muhammedfurkan** [a85/POSTMan-Chrome-Extension#12254]
### Is there an existing issue for this?

- [x] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

when I click the postman extension logo, extension is saying: "Unable to load items."

I already logged in potman.

### Steps To Reproduce

```
(2023-08-22T11:33:33.931Z) [info] [extension] Extension activation started: 1692704013920
(2023-08-22T11:33:34.041Z) [info] [extension] Extension activation completed: 1692704014041
(2023-08-22T11:33:34.041Z) [info] [extension] Extension activation took 121ms
(2023-08-22T11:34:39.719Z) [info] [extension] Extension activation started: 1692704079706
(2023-08-22T11:34:39.811Z) [info] [extension] Extension activation completed: 1692704079811
(2023-08-22T11:34:39.811Z) [info] [extension] Extension activation took 105ms
(2023-08-22T11:34:40.474Z) [info] [extension:sidebar:adapter] fetching a correct html for the view mode: {"viewMode":"sidebar"}
(2023-08-22T11:34:40.474Z) [info] [extension:htmlProvider] get sidebar HTML
(2023-08-22T11:34:40.553Z) [info] [extension:workspaceContext] Found the record in the cache

```

### Screenshots or Videos

![image](https://github.com/postmanlabs/postman-app-support/assets/9547040/c87acbba-13ce-44f2-8fd3-c8966468296a)

![image](https://github.com/postmanlabs/postman-app-support/assets/9547040/70ca9bba-ba8d-4d8b-930d-a9cd498173b9)

### Operating System

Windows

### Postman Version

v0.6.1

### Postman Platform

Other

### User Account Type

Signed In User

**Comment by pankajk07** [comment]
@muhammedfurkan This seems like an intermittent issue. Can you reload the vs code window and try again? To reload the window run `Developer: Reload window` command from the Command pallette.

**Comment by ebrown5-captioncall** [comment]
I just tried to install it and am getting "Can't install because it's incompatible with your VSCode version" (VSCode 1.71.2)

**Comment by pankajk07** [comment]
@ebrown5-captioncall Postman's vscode extension is compatible with VS Code  version `1.74.0` and above. Please update your VS Code to use the extension.

**Comment by xiaoyu-noveleffect** [comment]
got the same issue. any updates?

**Comment by ebrown5-captioncall** [comment]
Upgrading VSCode fixed it for me.

But I had to download the installer; I couldn't find an "check for updates" option.
________________________________

**Comment by muhammedfurkan** [comment]
I updated latest version vscode still same
```

Version: 1.82.2 (system setup)
Commit: abd2f3db4bdb28f9e95536dfa84d8479f1eb312d
Date: 2023-09-14T05:55:25.390Z
Electron: 25.8.1
ElectronBuildId: 23779380
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.19045
```


![image](https://github.com/postmanlabs/postman-app-support/assets/9547040/07b14795-f80f-415e-8791-d3cb69c2bbe4)

**Comment by muhammedfurkan** [comment]
![image](https://github.com/postmanlabs/postman-app-support/assets/9547040/2e036c5b-db26-440e-bc00-e6db2ce46994)

**Comment by muhammedfurkan** [comment]
![image](https://github.com/postmanlabs/postman-app-support/assets/9547040/a60351f3-e8a4-4c56-a1d9-a3a9a3284fd2)

**Comment by muhammedfurkan** [comment]
![image](https://github.com/postmanlabs/postman-app-support/assets/9547040/6ecd5a31-457b-476d-a720-dbb45304d6eb)

**Comment by muhammedfurkan** [comment]
> @muhammedfurkan This seems like an intermittent issue. Can you reload the vs code window and try again? To reload the window run `Developer: Reload window` command from the Command pallette.

any solution ?

**Comment by pankajk07** [comment]
@muhammedfurkan We would like to set a call to debug this. Please schedule a call with my [Calendly link](https://calendly.com/d/4tv-rh2-6pz/vs-code-debug-session).

**Comment by muhammedfurkan** [comment]
> @muhammedfurkan We would like to set a call to debug this. Please schedule a call with my [Calendly link](https://calendly.com/d/4tv-rh2-6pz/vs-code-debug-session).

can you send me a invitation again ?

**Comment by ethaden** [comment]
I have the same issue on all machines I've tested so far (Linux, Windows, MacOS). Did not get this extension working even a single time yet. :-(

**Comment by muhammedfurkan** [comment]
> I have the same issue on all machines I've tested so far (Linux, Windows, MacOS). Did not get this extension working even a single time yet. :-(

i think there is no solution for this unfortunately

**Comment by stevenh** [comment]
Used to work for me but now refuses to load collections or run requests.
This is reported from the `Runtime status` from the extension view:
```text
request to https://bifrost-extension-https-global.gw.postman.com/list/environment?workspace=7d509abf-87bb-4d0b-8b50-06c07d8bee8f failed, reason: getaddrinfo EAI_AGAIN bifrost-extension-https-global.gw.postman.com
request to https://bifrost-extension-https-global.gw.postman.com/workspace/7d509abf-87bb-4d0b-8b50-06c07d8bee8f/globals failed, reason: getaddrinfo EAI_AGAIN bifrost-extension-https-global.gw.postman.com
request to https://bifrost-extension-https-global.gw.postman.com/history?meta=true&workspace=7d509abf-87bb-4d0b-8b50-06c07d8bee8f&count=50&format=object failed, reason: getaddrinfo EAI_AGAIN bifrost-extension-https-global.gw.postman.com
request to https://bifrost-extension-https-global.gw.postman.com/workspace/7d509abf-87bb-4d0b-8b50-06c07d8bee8f/globals failed, reason: getaddrinfo EAI_AGAIN bifrost-extension-https-global.gw.postman.com
request to https://bifrost-extension-https-global.gw.postman.com/ws/proxy failed, reason: getaddrinfo EAI_AGAIN bifrost-extension-https-global.gw.postman.com
```

**Comment by stevenh** [comment]
In my case my workspace is under WSL2 on Windows, in case that matters.

**Comment by awlobo** [comment]
Same error here, using the latest VSCode version.

**Comment by leshaker** [comment]
same here, latest postman extension and vscode version running on macOS

**Comment by benb-petaf** [comment]
This is so dumb, but it worked for me after weeks of frustration.

I created a new workspace and exported the first collection as a Collection 2.1 file. Importing that file into Postman within VS Code failed. I re-exported the collection as a Collection 2.0 file and imported the file from VS Code - this was successful, so I continued with my other collections. 

When I restarted VS Code the collections are now visible in BOTH workspaces. 

The workspace seems to be syncing correctly. New collections and new items in the collection are passing both ways between VS Code and the Web UI. 

VS Code may have a problem with the 2.1 collection format. 
Postman extension 0.19.1
VS Code 1.87.2 on Windows 10

**Comment by pankajk07** [comment]
@muhammedfurkan Can you please confirm is the issue is still reproducible?

**Comment by muhammedfurkan** [comment]
My problem still persists and has not been fixed. unfortunately

**Comment by asacxyz** [comment]
Opening the Postman application itself and then trying on VSCode again fixed it for me.
