### ISSUE TITLE
VSCode Extension | Disable handleTerminalLink for certain links

### ISSUE THREAD

**Issue by jaikathuria** [a85/POSTMan-Chrome-Extension#12251]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

After installing the Postman VS Code Extension, Not able to use GitHub Pull Request Extension correctly.

Usually, after pushing a new branch to GitHub you get a link in the terminal, something like:
```
remote: Create a pull request for '<somebranch>' on GitHub by visiting:
remote:      https://github.com/jaikathuria/<somerepo>/pull/new/<somebranch>
```

And clicking on the link used to open Github Pull Request Extention which assists in creating the pull request from VS Code itself.

After installing, Postman Extension. This extension is trying to handle all the links from the terminal.
![image](https://github.com/postmanlabs/postman-app-support/assets/13422807/4e1ca531-8fa1-4b1b-8e43-8dd9cb716c62)

It makes sense to open links in postman, but there should be some way to disable certain types of links which I wasn't able to find.

### Steps To Reproduce

1. Install **GitHub Pull Requests and Issues** Exention 
2. Install **Postman** Extention
3. Try to push a new branch to a GitHub repo which will print something like below in terminal
```
remote: Create a pull request for '<somebranch>' on GitHub by visiting:
remote:      https://github.com/jaikathuria/<somerepo>/pull/new/<somebranch>
```
4. Click on the link.

### Screenshots or Videos

![image](https://github.com/postmanlabs/postman-app-support/assets/13422807/078d5d82-7f84-4355-b436-241eb9843bba)

### Operating System

macOs

### Postman Version

Version 10.16.3

### Postman Platform

Other

### User Account Type

Signed In User

**Comment by jaikathuria** [comment]
Maybe having a feature flag to disable `registerTerminalLinkProvider` would solve for immediate fix

**Comment by pankajk07** [comment]
@jaikathuria  we have disabled this feature for now as part of `v0.6.1`. Please update the extension to the latest version and try it out.

**Comment by jaikathuria** [comment]
Amazing, working for now 🙌

It's a good feature though but only along with the support of a whitelist/blacklist of links.

**Comment by pankajk07** [comment]
@jaikathuria Thanks for the feedback. We will be rethinking this feature to provide it in a non-intrusive way.
