### ISSUE TITLE
[VS Code Extension] Provide an option to run collections and not just single tests

### ISSUE THREAD

**Issue by Noor-Hashem77** [a85/POSTMan-Chrome-Extension#12260]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

The problem that I am having is that I am unable to run entire collections in the VSCode extension which is something that is very important for us to be able to do, this makes the vscode tool less useful and almost unusable for our use cases.

### Describe the solution you'd like

We would love it if we could run entire collections within the vscode extension.

**Comment by michaeljoshuaclaro** [comment]
I totally agree. This would be a great feature for the extension!

+1 upvote

**Comment by jlafuente13** [comment]
This is would be awesome. We can maximize more the extension with this. 

+1 upvote

**Comment by danisilver** [comment]
+1 upvote

**Comment by pankajk07** [comment]
@Noor-Hashem77 The ability to run Collections from VS Code is available. Please try it out and share the feedback, if any.
