### ISSUE TITLE
Getting authenticationrequired error even after signing in [Postman VS Code]

### ISSUE THREAD

**Issue by CogginCreations** [a85/POSTMan-Chrome-Extension#12265]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Even after singing in and being able to see my envs and requests, I still get an error of "authenticationrequired".

Nothing jumps out as an error in the logs:

![image](https://github.com/postmanlabs/postman-app-support/assets/8181472/fafd5cea-9ab8-481b-9fe4-c44017f76522)

### Steps To Reproduce

1. Sign in to extension
2. Select a request from your collection
3. See error
4. Be Sad

### Operating System

masOS

### Postman Version

0.6.1

### Postman Platform

Other

### User Account Type

Signed In User

### Additional Context?

This only happens in the postman VS Code Extension

**Comment by pankajk07** [comment]
@CogginCreations Can you share a screen recording of the issue, as that will help us understand the issue clearly?

**Comment by CogginCreations** [comment]
It is for work so I am not sure all I can share.  Here is a screen shot when I am trying to load/view anything in my envs:

![image](https://github.com/postmanlabs/postman-app-support/assets/8181472/21e8a082-b0c2-414c-8a75-feb94e273f7f)


I get a similar image when trying to view any of my saved requests:

![image](https://github.com/postmanlabs/postman-app-support/assets/8181472/9871920a-99f1-4d6b-848f-7d6b3ead6313)

**Comment by pankajk07** [comment]
@CogginCreations Can you please upgrade the extension to the latest version and try login in again?

**Comment by pankajk07** [comment]
@CogginCreations I will go ahead and close the ticket, as we did not get any response from your side. Feel free to create a new ticket, if the issue is still reproducible on your side.
