### ISSUE TITLE
[VS Code Extension] Dynamic Variables not working in Header

### ISSUE THREAD

**Issue by Ronarden** [a85/POSTMan-Chrome-Extension#12264]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Dynamic vraiables are not resolvable in the header (in the vs code extension).
Example:
{{$guid}} 
Error:
Unresolved Variable
Make sure the variable is defined and enabled in the active environment, collection or globals.

### Steps To Reproduce

Select Headers Tab
Put a dynamic variable into the value of a header.

### Operating System

macOS

### Postman Version

0.6.1 (VS CODE Extension)

### Postman Platform

Both

### User Account Type

Signed In User

**Comment by coditva** [comment]
@Ronarden Thanks for reaching out. We don't have dynamic variable resolution support in VSCode right now. We'll be adding this in the future releases. Please stay tuned and extension auto-updates turned on.

However, when you send the request, the variable should be resolved. This should be able to unblock you for now. Can you confirm this behaviour once?

**Comment by pankajk07** [comment]
@Ronarden We have shipped the support for Dynamic variables as part of the latest release (`v0.13.1`) of the Postman's VS Code extension. Please update your extension and try it out.
