### ISSUE TITLE
Postman vs-code extension error: Unexpected Application Error! 404 Not Found

### ISSUE THREAD

**Issue by fchamieh** [a85/POSTMan-Chrome-Extension#12279]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Just installed the postman vs-code extension, logged in via web browser, and the extension shows the error 
Unexpected Application Error!
404 Not Found

![image](https://github.com/postmanlabs/postman-app-support/assets/538830/ac998075-5d94-450b-b134-a78d53273f26)

### Steps To Reproduce

1. Install vs-code
2. install postman extension
3. click on "Sign in"
4. Login via web browser
5. extension shows empty page with error: 

### Screenshots or Videos

![image](https://github.com/postmanlabs/postman-app-support/assets/538830/a47fd0ea-43b6-4d80-93d7-6e6f7279014b)

### Operating System

Linux

### Postman Version

v0.6.2

### Postman Platform

Other

### User Account Type

Signed In User

**Comment by theshubhamjoshi** [comment]
Thank you for reporting this issue @fchamieh. This issue can happen when you are using an older version of Postman and try to sign in to the VSCode extension. To fix this issue, you can try signing in to the latest Postman app and then signin to the Postman VSCode extension.

To diagnose this issue further can you provide us with the email id for your registered Postman account?

**Comment by fchamieh** [comment]
The issue was resolved after I signed in from the Postman app and it asked me something related to My default Workspace. I signed out of postman extension on vs-code, signed in again and it is now working properly.
Thanks.
