### ISSUE TITLE
Moving Postman window to second screen breaks GraphQL window

### ISSUE THREAD

**Issue by kiprasbiel** [a85/POSTMan-Chrome-Extension#12275]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

When working with Postman and having a GQL request window opened if I move the whole application to other monitors, then whole tab refreshes: re-fetches GQL schema, removes my GQL queries and variables, clears my response tab. 

### Steps To Reproduce

1. Open new GQL request tab. 
2. Write your GQL query or build it using the fetched schema.
3. Execute the request.
4. Move whole Postman app windows to another monitor or just resize the app and watch everything refresh.

### Screenshots or Videos

Postman window before resize:
![image](https://github.com/postmanlabs/postman-app-support/assets/44984145/cd497106-e5b8-4ad3-b7a1-96347c6d1b49)

Postman window after resize:
![image](https://github.com/postmanlabs/postman-app-support/assets/44984145/dc3a4033-a3c9-48f1-bb16-d17b32e82d64)

Notice, that when the schema finishes reloading, the previous GQL query is still selected but the actual query field is empty. Executing now results in the same result as before the resizing suggesting that the query is actually there but not visible. 
![image](https://github.com/postmanlabs/postman-app-support/assets/44984145/dd507d90-2509-4d21-adf4-78e869e98cfd)

Now its easier to just close the tab entirely and restart, because there's all sort of strange behaviors happening, when you try to edit the query or remove it

### Operating System

Windows

### Postman Version

10.17.4

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by timhall** [comment]
Hi @kiprasbiel thanks for raising this issue. It has been fixed and is scheduled for the next release of Postman (in about 2 weeks).

**Comment by timhall** [comment]
This was fixed in our September release, thanks again for raising the issue

**Comment by kiprasbiel** [comment]
Bug with not visible GQL query is indeed fixed.
But results still disappear and schema reloads on every screen resize/moving to another screen. Is this expected behavior?

**Comment by kiprasbiel** [comment]
Also, variables do disappear on window size change, but the query still executes correctly which probably means that the variables are still set, but not visible. 
I cannot change/overwrite variables after window size change, query is stuck on old variables and ignores new ones.

**Comment by timhall** [comment]
Thanks for the follow-up, we're working on finding the root cause and will update once it's been fixed

**Comment by timhall** [comment]
Hi @kiprasbiel thanks again for raising this issue, we've sorted out the issue that was causing this and it has been released in Postman 10.21.

**Comment by kiprasbiel** [comment]
Awesome, everything is now working as expected. Thank you.
