### ISSUE TITLE
request logo is not updated

### ISSUE THREAD

**Issue by sarfat96** [a85/POSTMan-Chrome-Extension#12273]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

The logo is not syncronized

### Steps To Reproduce

1. Duplicate a HTTP request tab (example: POST)
2. Select the new copied one and change the HTTP request to another type (example: PUT)
3. See that the request logo is not updated

### Screenshots or Videos

![image](https://github.com/postmanlabs/postman-app-support/assets/25195192/8f31b101-3ee7-4691-b129-2f6aa93e01e3)

### Operating System

Windows 11

### Postman Version

v0.6.1

### Postman Platform

Other

### User Account Type

Signed In User

### Additional Context?

Name: Postman
Id: Postman.postman-for-vscode
Description: Streamline API development and testing with the power of Postman, directly in your favorite IDE.
Version: 0.6.1
Publisher: Postman
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=Postman.postman-for-vscode

**Comment by kartikjain26** [comment]
@sarfat96 Thanks for reporting this issue. Does this happen consistently for you or was this a one off case ?

**Comment by sarfat96** [comment]
> @sarfat96 Thanks for reporting this issue. Does this happen consistently for you or was this a one off case ?

@kartikjain26  this happen consistently, it will be synchronized if I click **Save** or **CTRL + S** only

**Comment by kartikjain26** [comment]
@sarfat96 Thats intended here. The request method that you see in the sidebar is the one that is saved to the server. But the one in the unsaved tab will not reflect in the sidebar unless the tab is saved by Save button or CTRL + S.
