### ISSUE TITLE
Subfolder Sync Issue

### ISSUE THREAD

**Issue by vasujain** [a85/POSTMan-Chrome-Extension#1227]
Postman sync server does not recognizes sub-folders i have created and started putting all requests under the parent folder. Happened couple of times and even after i have updated / synched the issue persists.

**Comment by abhijitkane** [comment]
Are you still seeing this? If so, can you send an email to help@getpostman.com with your userID, the request, and the folder which it should be in?

**Comment by vasujain** [comment]
Hi @abhijitkane i had to do a force sync and have lost a couple of folders. possibly sync was in a bad state or was stuck. Since then i have not experienced this issue.

**Comment by KeynesYouDigIt** [comment]
@abhijitkane @a85 I am having a critical issue with this problem - subfolders are not syncing, eventhough everything else is like the collection name and documentation

Is there a known issue with subfolder sync in the new versions?
