### ISSUE TITLE
Cookie control with collection runs

### ISSUE THREAD

**Issue by nlwillia** [a85/POSTMan-Chrome-Extension#1228]
I'm testing with a service that sets an unwanted session cookie in the response.  If I visit that service in Postman, the cookie is being saved and replayed for later requests.

I've identified several ways to submit a new request without the cookie...
1. Implement a reset feature in the service that clears the cookie and request it from Postman before making a new service request from the domain/path.  (This is not an option if dealing with a 3rd party service.)
2. Route requests through a proxy that strips the Set-Cookie response header.
3. Exit Postman and all instances of Chrome including the background process that Chrome runs in the Windows notification area if the "Continue running background apps when Google Chrome is closed" browser setting is checked.  Then restart.  (Don't think this would work for a non-session cookie.)
4. Install and enable the Interceptor plugin so that the browser's cookie store is used.  Open Chrome to chrome://settings/cookies and manually remove the unwanted cookies before each request.  Setting the Cookie header manually from within Postman in Interceptor mode can override the cookie that is sent (Cookie: unwanted-cookie=), but not remove it from the request completely.

None of these are very convenient.  Is there a better way to forcibly disable any sort of cookie header being sent?

**edit: 2018-04-20** This was originally logged against the Chrome app which has since been [deprecated](http://blog.getpostman.com/2017/11/01/goodbye-postman-chrome-app/) in favor of the [native apps](https://www.getpostman.com/apps).  The native apps don't appear to have the same browser-level constraint that made cookie management in Chrome a non-starter.  There's now a Cookies link that pops a `MANAGE COOKIES` modal where cookies can be added or removed.  This is an improvement as it's now possible to directly remove an unwanted cookie.  Unfortunately there still doesn't seem to be a way to disable cookies entirely.  However, the `Pre-request Script` option is promising as a way to run script to configure things that aren't supported in the UI.  This does not appear to support cookie manipulation, but there's a [recent issue](https://github.com/postmanlabs/postman-app-support/issues/4327) suggesting it.  If that's possible and gets done, then that will become a way to (finally) address this use case.

An aside to all the +1-ers out there, Github has had [reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) for over 2 years now; please use them!

**Comment by richarddavenport** [comment]
I agree. I would love to be able to see the cookies and clear or edit them.

**Comment by b0elter** [comment]
+1

**Comment by abhijitkane** [comment]
This is currently a limitation of the Chrome platform - packaged apps do not have access to Cookies that have been set, nor is there a way to edit/delete them. There are 2 bugs filed on crbug - https://code.google.com/p/chromium/issues/detail?id=236585, https://code.google.com/p/chromium/issues/detail?id=152758

Still waiting for a response on these.

**Comment by dbalabka** [comment]
+1 . My current solution is:
1. Open any page on the same domain in GoogleChrome
2. Open Developer tools(F12)
3. In Developers tool tab Resources clear all cookies before each request :smile: It's very annoying but works
![image](https://cloud.githubusercontent.com/assets/1269372/10283813/04e071ae-6b8a-11e5-93f1-58bdec112539.png)

**Comment by ghost** [comment]
+1 to have the option to send a request without cookies.

**Comment by philals** [comment]
+1

**Comment by tobilarscheid** [comment]
+1

**Comment by divayprakash** [comment]
+1

**Comment by akirayamamoto** [comment]
+1

**Comment by PiWhy** [comment]
+1

**Comment by lshapsa** [comment]
+1

**Comment by cychai** [comment]
+1

[Postman v0.9.6 – Access cookies and restricted headers. Plus better tests!](http://blog.getpostman.com/2014/02/11/postman-v0-9-6-access-cookies-and-restricted-headers-plus-better-testing/)

**Comment by matthewkimber** [comment]
+1

**Comment by mkimont** [comment]
+1

**Comment by dteirney** [comment]
+1

**Comment by jeremypaskalicimpress** [comment]
+1

**Comment by ericcarino** [comment]
+1

**Comment by sdnts** [comment]
Hey guys, cookie management is a limitation of the Chrome platform, but it is possible in the native apps. Could you give them a shot and check if that is easier? You can download our native apps for OSX/Windows/Linux [here](https://www.getpostman.com/apps).

**Comment by dteirney** [comment]
I've been using the native application for some time now. While you can delete cookies manually I can't find any setting or preference to prevent cookies being stored in the first place. This makes it seemingly impossible to use the collection runner and not have the results affected by the cookies that are stored.

**Comment by bkubiak** [comment]
Hey, could you add possibility to disable cookies in Mac OS native app? I can delete them manually, but this is very inconvenient.

**Comment by ayancey** [comment]
+1

**Comment by SidhantDuggal** [comment]
I've been using the native application. I can't find any setting or preference to prevent cookies being stored in the first place. This makes it apparently impossible to use the collection runner without affecting the results ( by the erstwhile cookies ).

**Comment by garmoshka-mo** [comment]
Actually this extension is useless for rails REST testing, though it could be convenient tool, because many cool useful UI-features implemented. 
Hm, why authors of this app are so.. "specific"? Put so much efforts to create application, which can't be used because of small stick in the wheels

**Comment by DanielStoica85** [comment]
@madebysid Any update on this?

**Comment by sdnts** [comment]
Work on making cookies manageable from pre-request / test scripts is underway, I'll let you guys know here when we have something :)

**Comment by testingProjectBangalore** [comment]
Any Updates on this ?

**Comment by kmix** [comment]
Any updates on giving us the ability to manage cookies from pre-request scripts?

**Comment by NabiKAZ** [comment]
As @nlwillia said:

> Setting the Cookie header manually from within Postman in Interceptor mode can override the cookie that is sent (Cookie: unwanted-cookie=)

It's worked and I thinks this is the great solution.
For example if set a cookie with `PHPSESSID` name every time.
Just add a header with `Cookie` as key and `PHPSESSID=` as name.

**Comment by adamtwarner** [comment]
+1
@madebysid any update?

**Comment by Hezek1ah** [comment]
The solution proposed by NabiKAZ did not work in my situation. The cookie value that I assigned was overridden.  @madebysid Any update to managing cookies from pre-request / test scripts?

+1

**Comment by fheidrich** [comment]
+1

**Comment by gemyago** [comment]
+1

**Comment by mesmerizero** [comment]
+1

**Comment by radub** [comment]
+1

**Comment by kozmaz87** [comment]
Unfortunately this renders postman and any such extension unusable for token based authentication testing if one also wants to use cookies for other clients and the auth framework of the backend picks the unwanted cookie up for the cases where it should not be picked up. Unfortunately it is not easy to have fine-grained control over most framework's cookie magic.

**Comment by tahirm** [comment]
+1

**Comment by jonpcunanan** [comment]
+1

**Comment by fheidrich** [comment]
Maybe I'm missing something here, but if I click on the 'Cookies' link and it opens the 'Manage Cookies' window, there I can manually remove cookie individually. So it seems the core functionality is there, and what I wanted was a way to say 'please remove all cookies before sending this request (or all request)'.

**Comment by quicksketch** [comment]
Although it's not perfect, in some cases you might be able to manually set the `Cookie` header to wipe out a cookie value. This may result in multiple Cookie headers being sent to the server, but the application reading the cookies may read the blank cookie instead.

![image](https://user-images.githubusercontent.com/100206/30290113-234c28b4-96e3-11e7-832a-56aede14ac2b.png)

This work-around has worked for me to emulate clearing a cookie value before a request is made.

**Comment by cawoodm** [comment]
My 2 cents: it should be a simple yes/no option under settings to enable/disable cookies. Most APIs and Webservices are stateless and cookies just make problems.

Today, I had requests working until I switched my user (Authorization header). Then everything stopped working with 401 bad credentials. Reason: cookies! The server thought I was still in the session of the old user.

**Comment by ifdattic** [comment]
I agree with @cawoodm that it should be a switch to enable/disable cookies. Working on a token based authentication with a cookie fallback for legacy makes it very hard to test un-authorized request (constantly deleting cookies before each request gets annoying).

**Comment by mkimont** [comment]
Guys, on July 2018 we will have 3th anniversery of this request, I will bring the 5 wine, can somebody bring the food and some entertainment ?

**Comment by tobilarscheid** [comment]
The regular emails I receive from this issue keep reminding me that postman still exists 🤓

**Comment by EricThieme** [comment]
+1 
nice issue... worth to join it to get the "postman is alive ping". ;) 

Stumbled across this issue today and it would really help to delete the cookies. Now I have to skip a few tests in my Postman Runner and make a few weird assumptions to other tests that I can only do because I know the backend implementation...

**Comment by tobilarscheid** [comment]
If only postman was open source... the other day I was dreaming about a postman that uses curl under the hood (instead of the strange chromium stuff)

**Comment by araneforseti** [comment]
+1

Makes even exploratory testing a bear since we have to clear the cookies so often. Weird thing is we weren't affected this issue until recently.

**Comment by d42ohpaz** [comment]
@tobilarscheid re: open source, if I'm not mistaken (and I very well could be), you may want to look at https://github.com/postmanlabs/postman-runtime -- this appears to be the engine that drives Postman.

**Comment by d42ohpaz** [comment]
@madebysid any status on the progress of this issue? 

Similar to working in the Headers/Body tabs of a request, I'd be happy with the ability to toggle on/off a cookie from the "Manage Cookies" UI. Better yet, though understandably a more complex solution, scrap the Manage Cookies UI and create a Cookies tab that sits alongside the Headers/Body tabs. This would allow for a consistent interface, utilize existing elements for toggling on/off specific cookies, allow bulk editing cookies, having presets, and can handle the complexity of setting the various fields of a cookie (i.e., similar to how the Authentication tab handles the Authorization header).

Thoughts?

**Comment by MrGarry2016** [comment]
+1, 

for disabling cookie for the postman

**Comment by marvader** [comment]
+1

**Comment by berkantipek** [comment]
+1

**Comment by Elmeraculous** [comment]
+1

**Comment by dotdet** [comment]
+1

**Comment by YoSev** [comment]
+1

**Comment by savage4pro** [comment]
+1 for disabling all and certain cookies ability!

**Comment by Mihai1706** [comment]
Still no news on this? I have been religiously clearing cookies manually, but recently had to get other developers (including 3rd party) on board. Had to explain them one by one whey they needed to manually clear cookies as they do their requests.

They were all in awe when they heard about why they need to do this and all of them told me "oh but there must be some way to disable them in Postman". So naturally they were even more in awe when I pointed them to this thread to realize that such basic feature is still not implemented in an app like Postman in 2018!

**Comment by Granitosaurus** [comment]
Yup, it's still unbelievable that this feature is not present - it's one of the core basic functionalities.  

Also it's so misleading and implicit. I'm sure I'm not the only one who spent hours debugging requests where I explicitly set cookies in headers tab just for them to be ignored and replaced by cached cookies that can only be found in a tiny "Cookies" hyperlink that contain cookies for every domain postman ever worked with.

Now you have to open up cookies, find your domain, clear all of them by clicking on every cookie one by one, and do this every single time - this is beyond silly.

**Comment by savage4pro** [comment]
@Granitosaurus 
Not applicable solution if you want to use runner.

As mentioned earlier there is workaround - "overriding" Cookie header.
BUT adding this header not really overrides to-send cookies - empty values you've added just concatenates with stored cookies and they are sending to server together (explicit keys first).

Of course, only server-side front/backend application decides what to do with received headers. And it can unexpectedly handle cookies something like this:

![cookies - Postman Console 2018-03-27.png](https://monosnap.com/file/QRKUnF2FZEGVdX9grjbfe4OH1BMstq.png)

**Comment by aldaris** [comment]
I've been recently told that the insomnia rest client allows control over cookies, but their user interface takes a while to get used to. Would be great if postman could implement a basic feature requested ~3 years ago.

**Comment by kristian** [comment]
+1

**Comment by StefH** [comment]
+1

**Comment by mindgrub-mmillford** [comment]
+1

**Comment by MarcMacia** [comment]
+1

**Comment by herath** [comment]
+1

**Comment by dtvuong** [comment]
+1

**Comment by sagarey** [comment]
+1

**Comment by Lambeaux** [comment]
+1

**Comment by ivanyukio** [comment]
+1

**Comment by gorobets-da** [comment]
+1

**Comment by ashishpatel1992** [comment]
+1

**Comment by subwaymatch** [comment]
+1

**Comment by regisbsb** [comment]
+1

**Comment by regisbsb** [comment]
Could somebody hack the https://github.com/postmanlabs/postman-runtime `requester.cookieJar` to false in the native app?

**Comment by ashishpatel1992** [comment]
I am looking to disable only some cookies for the temporary time being. So that I don't need to copy and paste every cookie for a new request.

**Comment by EralpB** [comment]
please give us an option to disable cookies.

**Comment by rzaharenkov** [comment]
please fix it before you close it!

**Comment by jjsty1e** [comment]
why this was remove from the Mid term roadmap? I eagerly hope you guys add this feature to postman mac native apps, thanks very much.

**Comment by plumpNation** [comment]
+1

**Comment by shamasis** [comment]
@codenirvana based on our last review of cookie related issues, let’s add cookie syncing / persisting controls before and after runs. that would unblock a number of related use cases.

**Comment by shamasis** [comment]
We were thinking of ways to address all use cases in this and take this up ASAP. So, here are the thoughts:

We solve it in two parts: (1) Add session control on runner start and stop (2) Add cookie control API within scripts

1. By session control, I mean you get to choose what you want to carry over from the main window when run starts and for every subsequent run.
-- For a run, you can choose to start with a fresh session and that would use initial values for environment and blank cookie jar.
-- You can also choose what to do with cookies when run ends (just like what is available with the "persist variables" feature.)

2. For other use cases where one needs to clear cookies at special points in run as well as on iteration change, etc... we open up pm.cookies or some variant of it that has access to entire Cookie Jar and can be manipulated programmatically at any point.

**Comment by fabOnReact** [comment]
where to find the cookies management in the native app

![postman cookies](https://user-images.githubusercontent.com/24992535/55257384-02deba80-5260-11e9-899f-d5a03232c666.png)

**Comment by Bluscream** [comment]
HOW TO DO THIS?

**Comment by fabOnReact** [comment]
@Bluscream  better not using all caps, please edit your message
the screen is from the postman ubuntu desktop app. The rest is self-explanatory

**Comment by vikiCoder** [comment]
Hello everyone,

We have added the following options in collection runner to provide more control over cookies while running a collection:
- Run collection without using stored cookies
- Save cookies after collection run

These options are available in [Postman App version 7.1.0 or later](https://www.getpostman.com/downloads/). Below is a screenshot showing off these options in runner window.

Screenshot:

<img width="1440" alt="Screenshot 2019-06-12 at 3 46 18 PM" src="https://user-images.githubusercontent.com/16588032/59343432-7fdee380-8d29-11e9-97e6-a48f865f8be3.png">

**Comment by regisbsb** [comment]
@vikiCoder This does not help when you need to clear the cookies as part of a request. It would be very nice just to add cookie manipulation to the script

**Comment by vikiCoder** [comment]
@regisbsb We are working on improving cookies UI in the App with more options to manage cookies as well as allowing cookies control from scripts. There is no final release date for those features yet. Stay tuned for the updates.

**Comment by theLucasAntunes** [comment]
@vikiCoder As a user who rarely uses the Collection Runner, but test individual requests instead, I find this to be a very niche-focused improvement. I'm not saying it's a bad feature, but we could have this setting for each request.. Maybe a simple checkbox inside the existing "Cookies" window.

**Comment by shamasis** [comment]
@KrilMun @regisbsb ... the programmatic access of cookies are being worked upon as I type. :-) You would be able to white-list a set of domains that would be programmatically manipulated. Will release in Canary soon and I hope to get feedback. :-)

**Comment by brettsamann** [comment]
Is there an ETA for that feature? It will be a huge help to some of the workflows I have.

**Comment by codenirvana** [comment]
We've added support for programmatic cookie access in our Canary channel https://www.getpostman.com/canary

Refer https://github.com/postmanlabs/postman-app-support/issues/3312#issuecomment-516965288 for detailed documentation.

Everyone, please try it out and share the feedback.
Will update the thread once we release this on our stable channel.

**Comment by shamasis** [comment]
@brettsamann @KrilMun @regisbsb - would greatly appreciate any feedback around the programmatic access before we roll it out to production in weeks.

**Comment by codenirvana** [comment]
We've added support for programmatic cookie access in the latest version of the Postman app (v7.6.0). Refer https://github.com/postmanlabs/postman-app-support/issues/3312#issuecomment-516965288 for more details.

**Comment by iamkarlson** [comment]
Whoever switch it on by default for all the users made a huge mistake. This is super annoying and cause a lot of troubles already.
