### ISSUE TITLE
VSCode Extension Doesn't work for Vscodium-compatible editors

### ISSUE THREAD

**Issue by Sanger2000** [a85/POSTMan-Chrome-Extension#12288]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

It appears that the login for the Postman extension doesn't work for Cursor nor VSCodium as it gives the error:
Could not login: Network error (Request failed with status code 400)

I suspect this is because the request payload depends on something like the application name being Visual Studio Code. However, it does also work for Visual Studio Code Insiders when testing.

### Steps To Reproduce

1. Open VsCodium or Cursor
2. Install the Postman Extension
3. Press "Sign In"

### Screenshots or Videos

<img width="514" alt="Screen Shot 2023-09-03 at 1 40 49 PM" src="https://github.com/postmanlabs/postman-app-support/assets/17725268/42a091fe-ebb3-48b6-8964-ad5dd4910c67">

### Operating System

MacOS

### Postman Version

v0.6.2

### Postman Platform

Other

### User Account Type

Signed In User

**Comment by tgerbeau** [comment]
Same kind of error on Linux v0.6.2

Could not login: Network error (Request failed with status code 501)

**Comment by xilopaint** [comment]
Can confirm the issue on Cursor.

**Comment by liberty-rising** [comment]
Any update on this?

**Comment by scerelli** [comment]
got the same issue here

**Comment by chad-levesque** [comment]
+1

**Comment by ervinte** [comment]
Confirmed on Azure Data Studio

**Comment by jaysonsosweet** [comment]
Same here !
I actually tried several times but dit not take time to post an issue about it.
Ended up uninstall the extension each time it failed.

Postman version : 0.17.0

Version: 1.85.1 (user setup)
Commit: 0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2
Date: 2023-12-13T09:49:37.021Z
Electron: 25.9.7
ElectronBuildId: 25551756
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.19045

EDITTED:
I think this has something to do with my company proxy (which I already set correctly : http://127.0.0.1:9000).
Maybe it changes headers somehow or something.

I just installed the extension on my personal computer and it worked perfectly.
Here's Vscode about infos:

Version: 1.85.1 (user setup)
Commit: 0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2
Date: 2023-12-13T09:49:37.021Z
Electron: 25.9.7
ElectronBuildId: 25551756
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.19042

They're quite the same as you can see.

**Comment by vedlikeholderen** [comment]
+1

**Comment by lightify97** [comment]
IDE: Cursor (Connected to WSL)

Could not login: Network error (Request failed with status code 400)

**Comment by pankajk07** [comment]
Hey folks, we recently shipped a new version of the extension that supports VS Codium and Cursor IDE. Please update the extension and try it out.

**Comment by kennyMC** [comment]
> Hey folks, we recently shipped a new version of the extension that supports VS Codium and Cursor IDE. Please update the extension and try it out.

Hi, it's still not working in the coder ide (https://github.com/coder/coder)

**Comment by sirkuttin** [comment]
Still seeing this issue. Not working for me on windsurf ide.
