### ISSUE TITLE
Invisible character gets added when running some POST command

### ISSUE THREAD

**Issue by siddhant16** [a85/POSTMan-Chrome-Extension#12284]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

When I'm using postman to run POST commands, I see for some of the commands, an additional garbage value gets added at the end of the URL.

I have 2 screenshots for the issue that I'm facing.
In the postman Screenshot, you can see on the right side the equivalent curl command the postman is generating. The URL looks correct. Then I copied the URL from postman and paste it in my terminal, and suddenly I see an invisible character which is getting added in the URL. 

<img width="1535" alt="Screenshot 2023-08-30 at 3 15 27 PM" src="https://github.com/postmanlabs/postman-app-support/assets/32676924/2b9c52f8-ebe2-4cd3-be01-e142bbdf7e1c">

In the 2nd screenshot, you can see the additional <2029> garbage value gets added.

<img width="951" alt="Screenshot 2023-08-30 at 3 18 11 PM" src="https://github.com/postmanlabs/postman-app-support/assets/32676924/7aa1ad47-cb2c-4495-a5a4-a87fa2292b16">

 This issue causes the URL link to change and doesn't hit the required controller.

### Steps To Reproduce

This issue doesn't occur for all the POST commands.

### Operating System

macOS

### Postman Version

10.17.4

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by xk0der** [comment]
@siddhant16 `U+2029` is the paragraph separator Unicode character.
Most likely the URL was copy-pasted from somewhere and that is where the hidden character comes from. 

Try deleting the URL after selecting all and typing the entire URL manually and check to see if that fixes the issue. Alternatively create a new request and type the same URL manually into that (and setup body-payload header) etc.

Tip: You can check the exact request being sent by checking the [Postman Console](https://learning.postman.com/docs/sending-requests/troubleshooting-api-requests/#debugging-in-the-console)
