### ISSUE TITLE
Test tab lost syntax highlighting

### ISSUE THREAD

**Issue by Jessica-VL** [a85/POSTMan-Chrome-Extension#12292]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

The test tab lost syntax highlighting for postman desktop app
Postman version: 10.17.6
OS: Windows 10

### Steps To Reproduce

1.Open any request tab
2.Go to test tab
3.Write some js code

### Screenshots or Videos

![postman_bug](https://github.com/postmanlabs/postman-app-support/assets/119606357/358226f6-e59a-42eb-b792-c026036bd7e1)

### Operating System

Windows

### Postman Version

10.17.6

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by chadcooper** [comment]
Same on Mac - Ventura 13.4.1

Version 10.17.6
UI Version: 10.17.6-ui-230904-0927
Desktop Platform Version: 10.17.4 (10.17.4)

**Comment by eioquent** [comment]
Everyone on my team has reported the same issue. I upgraded from 10.17.1 to 10.17.6 and ended up seeing the issue they reported as a result.

**Comment by LilianBall** [comment]
I have reinstalled and tested on a previous version, and the issue is still occurring.

**Comment by wojciechGaudnik** [comment]
The same story on:

Postman for Linux
Version 
10.17.6
UI version 
10.17.6-ui-230904-0927

Desktop platform version 
10.17.4

Architecture 
x64

OS platform 
linux 5.13.0-52-generic

**Comment by zJustaGhost** [comment]
The same story here, just open Postman this morning and this happened. Very uncomfortable and hard to see or arrange the code.

**Comment by wojciechGaudnik** [comment]
Works fine on:
Postman for Windows

Version 10.17.3

Architecture x64

Platform win32 10.0.19045

**Comment by rogerckk** [comment]
Same issue in Pre-request Script 

Postman for Windows
Version 
10.17.6
UI version 
10.17.6-ui-230904-0927

Desktop platform version 
10.17.4

Architecture 
x64

OS platform 
win32 10.0.19045

![Snag_16e17d9](https://github.com/postmanlabs/postman-app-support/assets/133816639/21a09ca9-da56-4f22-a278-1622ab4b2770)

**Comment by hower89a** [comment]
I have the same issue and as a part of bug report I may add that I can see that syntax highlighting is being loaded for a brief moment before turning off:

![postman2](https://github.com/postmanlabs/postman-app-support/assets/75138292/3e61994a-616e-4d1b-b9e1-1d94d0b9e9d6)

Also, I tried removing local files from AppData folder (Local and Roaming subfolder) and installing Postman afterwards, but no success either.

@wojciechGaudnik Unfortunately, 10.7.3 doesn't work on my Windows 11 either, so I guess it is not a universal solution.

```
Version 
10.17.3
UI version 
10.17.3-ui-230822-0611

Desktop platform version 
10.17.3

Architecture 
x64

OS platform 
win32 10.0.22621
```

**Comment by giridharvc7** [comment]
We are looking into this, will keep posted in this thread as we progress

**Comment by wojciechGaudnik** [comment]
> I have the same issue and as a part of bug report I may add that I can see that syntax highlighting is being loaded for a brief moment before turning off:
> 
> ![postman2](https://user-images.githubusercontent.com/75138292/265911558-3e61994a-616e-4d1b-b9e1-1d94d0b9e9d6.gif)
> 
> Also, I tried removing local files from AppData folder (Local and Roaming subfolder) and installing Postman afterwards, but no success either.
> 
> @wojciechGaudnik Unfortunately, 10.7.3 doesn't work on my Windows 11 either, so I guess it is not a universal solution.
> 
> ```
> Version 
> 10.17.3
> UI version 
> 10.17.3-ui-230822-0611
> 
> Desktop platform version 
> 10.17.3
> 
> Architecture 
> x64
> 
> OS platform 
> win32 10.0.22621
> ```

On windows 10 it's worked, maybe it's related to UI version ?

**Comment by skopusnik** [comment]
Same issue from this morning in both Postman and Canary for "Pre-request script" and "Tests" tabs.

**Comment by Boost9898** [comment]
I can confirm the issue is also happening over here on Windows 11, Postman Version 10.17.6.

**Comment by giridharvc7** [comment]
We've raised a fix for this issue, you can try reopening the app, and it should work. If it doesn't you can try Clearing Cache and reload from the `Help` section on the menubar. 
<img width="781" alt="image" src="https://github.com/postmanlabs/postman-app-support/assets/1040583/a12c5076-64aa-42ae-8ff8-51ef71e56f29">

**Comment by virtuousvigilnt** [comment]
It's reproducible again. I'm on Windows 11 (10.0.22631 Build 22631) with the latest Postman 11.1.1
![image](https://github.com/postmanlabs/postman-app-support/assets/102950599/d0fb90a7-69ba-48d6-8d46-c2bffb31ee62)

Please let me know if there's something on my end I can do. 

Edit: 
- 'clear cache and reload' did not fix the issue
- 'disable hardware acceleration' did not fix the issue
- Issue was not occurring previous days (same version)

**Comment by virtuousvigilnt** [comment]
Another day, another story. It works as expected now (I'm guessing Postman does not like the date May 15th)
