### ISSUE TITLE
History is totally useless if using variables in URL

### ISSUE THREAD

**Issue by yeshodhan** [a85/POSTMan-Chrome-Extension#1229]
History should capture the actual URL rather than displaying the unparsed URL.

<img width="310" alt="screenshot 2015-07-08 19 09 03" src="https://cloud.githubusercontent.com/assets/2785164/8586584/10bc9316-25a5-11e5-9251-eb43823ca269.png">

**Comment by BrakTalk** [comment]
I second this.  We have multiple environments as code gets promoted towards a release.  Not being able to tell which environment was accessed is a rather profound issue for us.

**Comment by BrakTalk** [comment]
Any update for this issue?  i.e. any potential fix release?

**Comment by a85** [comment]
We don't store actual values due to security issues. We are thinking about storing the environment value that the request was sent with along with tab specific environments that should have the same effect as storing variable values while also ensuring that sensitive values don't show up.

**Comment by yeshodhan** [comment]
If you can save environment values, why not save the urls? Atleast provide an option in settings to enable or disable variable replacement in history?

**Comment by a85** [comment]
The Postman Console shows fully resolved values for each request which you can use instead of the history now.
