### ISSUE TITLE
Inpide poder utilizar la nueva función "PORTS".

### ISSUE THREAD

**Issue by SantiagoEmanuel** [a85/POSTMan-Chrome-Extension#12301]
Type: <b>Bug</b>

Iniciar localmente un proyecto. "pnpm run dev".
Tratar de usar la herramiento "PORTS", hay un error que impide usarlo.

Extension version: 0.7.0
VS Code version: Code 1.82.0 (8b617bd08fd9e3fc94d14adb8d358b56e3f72314, 2023-09-06T22:07:07.438Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-4170 CPU @ 3.70GHz (4 x 3700)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|7.94GB (3.34GB free)|
|Process Argv|. --crash-reporter-id fe7f4d3b-5111-4f2e-a423-28e8fae131c3|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30803844
282f8724:30602487
f6dab269:30613381
a9j8j154:30646983
showlangstatbar:30737416
0bi6i642:30831757
03d35959:30757346
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxptcf:30805731
pythonnoceb:30805159
dsvsc013:30795093
dsvsc014:30804076
diffeditorv1:30821571
dsvsc015:30829745

```

</details>

**Comment by pankajk07** [comment]
@SantiagoEmanuel Can you please share more information regarding the issue with some screenshots or recordings? This will help us understand the issue and provide a proper fix for the same.

**Comment by asmel2020** [comment]
@SantiagoEmanuel  You have to set the public port so that the postman can make requests without problems 

![Captura de tela 2023-09-12 171048](https://github.com/postmanlabs/postman-app-support/assets/80667962/671d5729-84a6-4ccd-b0a4-7e61cc8361b3)

**Comment by asmel2020** [comment]
@SantiagoEmanuel You have to set the public port so that the postman can make requests without problems
![Captura de tela 2023-09-12 171048 (3)](https://github.com/postmanlabs/postman-app-support/assets/80667962/a2bdf99e-1c3f-4dc8-8e45-8c203c8f4fea)

**Comment by pankajk07** [comment]
@SantiagoEmanuel Closing this issue, as we did not get any updates. Please feel free to open a new issue if required.
