### ISSUE TITLE
Unable to Edit Cookies manually in Postman VS Code Extension

### ISSUE THREAD

**Issue by Shashi9503** [a85/POSTMan-Chrome-Extension#12303]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

When I try to edit a cookie e.g. value of "sails.sid" here and save it then it doesn't get saved while in Postman (app) this works fine.

![image](https://github.com/postmanlabs/postman-app-support/assets/72440320/861623e5-9212-4e27-9ee8-5c69613b4679)

### Steps To Reproduce

1. Send GET request to any website in Postman VS Code Extension.
2. Try to edit the cookie and save it.

### Operating System

Windows

### Postman Version

0.7.0

### Postman Platform

Other

### User Account Type

Signed In User

**Comment by pankajk07** [comment]
@Shashi9503 Can you share a screen recording of the issue, as we are not able to reproduce the same at our end.

**Comment by Shashi9503** [comment]
Here is a screen recording of the issue

https://drive.google.com/file/d/1-n1iUuMD-ZLGSY5KopPY8z26ehMcQkJT/view?usp=drive_link

**Comment by pankajk07** [comment]
> Here is a screen recording of the issue
> 
> [drive.google.com/file/d/1-n1iUuMD-ZLGSY5KopPY8z26ehMcQkJT/view?usp=drive_link](https://drive.google.com/file/d/1-n1iUuMD-ZLGSY5KopPY8z26ehMcQkJT/view?usp=drive_link)

@Shashi9503 The file seems to be private. Can you share a public link for the same.

**Comment by Shashi9503** [comment]
> > Here is a screen recording of the issue
> > [drive.google.com/file/d/1-n1iUuMD-ZLGSY5KopPY8z26ehMcQkJT/view?usp=drive_link](https://drive.google.com/file/d/1-n1iUuMD-ZLGSY5KopPY8z26ehMcQkJT/view?usp=drive_link)
> 
> @Shashi9503 The file seems to be private. Can you share a public link for the same.

@pankajk07 I made it public. You can access now

**Comment by ivan-demchenko** [comment]
Hello @Shashi9503,
Thank you for reporting this issue. We have just pushed a fix for this issue in the latest v0.9.0 release. Please update your extension to the latest version and try this flow out!
