### ISSUE TITLE
VSCode Extension - Error: loading webview

### ISSUE THREAD

**Issue by ArnoBuschmann** [a85/POSTMan-Chrome-Extension#12306]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

The Postman VSCode sidebar panel ist not showing up, when reopening VSCode without logging out of Postmans VSCode extension before closing VSCode.

### Steps To Reproduce

1. )When being logged in to Postman in the VSCode extension, it works nicely, but when I close VSCODE, without logging out and opening VSCode again, the Postman panel in the sidebar doesn't load. The error then is:

```
Error loading webview: Error: Could not register service worker: InvalidStateError: Failed to register a ServiceWorker: The document is in an invalid state..
```

2. To get in again, I have to logout within the Postman extension, close VSCode, oben VSCode again and login again.

### Operating System

Linux

### Postman Version

0.7.0

### Postman Platform

Other

### User Account Type

Signed In User

**Comment by pankajk07** [comment]
@ArnoBuschmann Can you check if there is another VS Code process that is running? If yes, can you kill them and retry opening VS Code. For more details https://stackoverflow.com/a/69316961

**Comment by starball5** [comment]
See also https://github.com/microsoft/vscode/issues/192965

**Comment by pankajk07** [comment]
@ArnoBuschmann Can you please confirm if the issue is resolved or not?

**Comment by pankajk07** [comment]
@ArnoBuschmann I will go ahead and close the ticket, as we did not get any response from your side. Feel free to create a new ticket, if the issue is still reproducible on your side.
