### ISSUE TITLE
Could not login: Network error (Request failed with status code 403)

### ISSUE THREAD

**Issue by tgerbeau** [a85/POSTMan-Chrome-Extension#12308]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Sign-in not working (behind proxy) 

### Steps To Reproduce

- Install Postman extension for VScode (for Linux) 
- Click on "Sign In" button  
- Error message : Could not login: Network error (Request failed with status code 403)

### Operating System

Linux

### Postman Version

0.7.0

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by pankajk07** [comment]
@tgerbeau  Can you try setting the proxy as mentioned in this issue and see if this works
[stackoverflow.com/a/37581492](https://stackoverflow.com/a/37581492)

More details around Network and Proxy in VS Code: [code.visualstudio.com/docs/setup/network](https://code.visualstudio.com/docs/setup/network)

**Comment by pankajk07** [comment]
@tgerbeau Can you please confirm if the suggest steps resolved the issue or not?

**Comment by pankajk07** [comment]
@tgerbeau I will go ahead and close the ticket, as we did not get any response from your side. Feel free to create a new ticket, if the issue is still reproducible on your side.
