### ISSUE TITLE
Can't export all collection data

### ISSUE THREAD

**Issue by zhongjixiuxing** [a85/POSTMan-Chrome-Extension#1230]
I goto settings page to export my all data, but in true, export first collection data, other collection is can't to export....

**Comment by abhijitkane** [comment]
What version of the app are you using? 
Also, can you check the console for any errors? http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/

**Comment by zhongjixiuxing** [comment]
![image](https://cloud.githubusercontent.com/assets/8935235/8591123/bf2b0cbc-2658-11e5-9e8f-8e855d41a539.png)

**Comment by abhijitkane** [comment]
Can you try to update to the latest version and check? (chrome:/extensions -> Enable Developer Mode > Update extensions now)

**Comment by zhongjixiuxing** [comment]
i alread is latest version and enable developer mode , the bug issue is not solve....
![image](https://cloud.githubusercontent.com/assets/8935235/8592608/5bb4dcb6-2663-11e5-906d-8c6812fc9262.png)

**Comment by abhijitkane** [comment]
The latest version is v3.0.2, not 3.0.0.5. If you click the "Update button" (Under the developer mode checkbox), Postman should update to v3.0.2.

**Comment by zhongjixiuxing** [comment]
is ok, thans to your answer...
