### ISSUE TITLE
Inconsistent Response Formatting in Postman Extension VSCode

### ISSUE THREAD

**Issue by codewithleader** [a85/POSTMan-Chrome-Extension#12315]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

- Issue Summary:

When making a new request in the Postman extension for VSCode and selecting "pretty" and "JSON" in the response area, the formatting switches back to HTML unexpectedly.

### Steps To Reproduce

1. Open Postman extension in VSCode.
2. Create a new request.
3. In the response area, select "pretty" and "JSON" formatting.
4. Make the request.

- Expected Behavior:
The response formatting should stay consistent with the selected settings ("pretty" and "JSON") throughout the request.

- Actual Behavior:
The response formatting changes back to HTML, which is unexpected and can be confusing when working with JSON responses.

### Screenshots or Videos

Screenshots:
Before
![Screenshot1](https://github.com/postmanlabs/postman-app-support/assets/62060473/bb4533ce-d05e-4ed7-ab10-fba11fad07b5)

After
![Screenshot2](https://github.com/postmanlabs/postman-app-support/assets/62060473/ef6e59dc-549f-4ae6-b6f7-38b51911e7f0)

### Operating System

Windows 10 Home 64bit

### Postman Version

Postman Extension Version: 0.8.0

### Postman Platform

Other

### User Account Type

Signed In User

### Additional Context?

VSCode Version: 1.82.1
Postman Extension Version: 0.8.0
Operating System: Windows 10 Home 64bit

Thanks!

**Comment by pankajk07** [comment]
@codewithleader The formatting is auto-selected based on the `content-type` header received in the response object. In this most probably the content type is being set as HTML due to which the response section is formatting the data as HTML. Can you please check the `Content-type` in the Response Headers section?
