### ISSUE TITLE
Keyboard shortcuts for changing tabs in Postman packaged app

### ISSUE THREAD

**Issue by jussiarpalahti** [a85/POSTMan-Chrome-Extension#1231]
Postman does not seem to honor any of the standard nor non standard keyboard command for changing tabs I could think of. I tested on OS X and Linux, and only way I can change tabs seems to be point and click. Just supporting Ctrl + Tab would go a long way. Is there any option for this?

Also, it would be nice Postman could restore a session including already opened tabs and what not. Chrome does this for its own tabs.

**Comment by abhijitkane** [comment]
We'll add shortcuts for tab navigation in a future release.

**Comment by jussiarpalahti** [comment]
OK, thank you. Good to know!

**Comment by aditikul** [comment]
Hi,

We've added shortcuts for switching between tabs. Please update to the latest version of the Chrome App or the Mac Beta to get this update. 

Thanks!

**Comment by abhijitkane** [comment]
@jussiarpalahti For OSX, You can use `Cmd+Shift+[` and `Cmd+Shift+]`.

**Comment by jussiarpalahti** [comment]
Thank you, I can confirm it works.

However, on finnish keyboard this shortcut becomes Cmd+Shift+Alt+8 which is less than ideal...

I can't seem to find any way change shortcuts...

**Comment by benlind** [comment]
If you are on a Mac you can manually override the Postman next/previous keyboard shortcuts via System Preferences:

1. Go to System Preferences > Keyboard, select App Shortcuts in the sidebar, and click the plus icon.
2. Select Postman from the App dropdown and enter "Next Tab" or "Previous Tab" as the Menu Title. Select the Keyboard Shortcut input and press the key combination you want to use (in my case Ctrl + Tab or Ctrl + Shift + Tab).
