### ISSUE TITLE
You've reached the limit of 3 APIs and cannot create more

### ISSUE THREAD

**Issue by sarah-jay-peper** [a85/POSTMan-Chrome-Extension#12317]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

When trying to import a new gRPC proto file and assign it to a new API, I get the error: "You've reached the limit of 3 APIs and cannot create more". In this particular workspace I don't have a single gRPC API. (In another workspace I have 5 existing gRPC APIs and also cannot create more)

![Screenshot 2023-09-14 at 15 17 02](https://github.com/postmanlabs/postman-app-support/assets/7265825/2fab1c5f-af99-4f77-8b43-137d42d5d8b4)
,

### Steps To Reproduce

1. click on 'new' in the workspace view, choose gRPC, 
2. click 'select method' 
3. 'import a .proto file'
4. add a proto file
5. 'next'
6. 'select an API'
7. error appears

### Operating System

macOS

### Postman Version

10.17.7

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by shashankawasthi88** [comment]
@jay-peper can you reach out to support (help@postman.com). We can help unblock you.
