### ISSUE TITLE
Postman Flows problem

### ISSUE THREAD

**Issue by furkan-altun** [a85/POSTMan-Chrome-Extension#12320]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

We have been using the Postman basic plan for a long time. However, the basic plan could no longer meet our needs. That's why we upgraded our current plan to an annual professional plan. In this way, everyone in the team could use flows.
(Postman Flows allows users to create API chain requests.)

Before making a purchase, We asked the postman team about the professional plan package details via opening a ticket. They stated that all team members will have access to the flows. However, after purchasing, they stated there was a mistake, and only those with the flow-editor role could use it.

![image](https://github.com/postmanlabs/postman-app-support/assets/34065538/9638624e-6d2d-4e58-b2b2-768f88740cfb)

![image](https://github.com/postmanlabs/postman-app-support/assets/34065538/d5d8df53-3610-44b1-9ade-0b4e339d3cc9)

![image](https://github.com/postmanlabs/postman-app-support/assets/34065538/0d4955eb-5441-4459-aeff-8cc289af735c)

We were paying $14 per person for the Basic plan. When we switch to the professional plan, this fee becomes 29 dollars. We must also pay an additional $20 per person for the flow editor role.

So, Postman want us to pay 15+20 dollars more to use Postman flows. We opened many tickets regarding the issue but have not gotten any results. We advise those who are considering purchasing Postman Flows to be careful. Never buy a membership based on the tickets you opened on Postman.

### Describe the solution you'd like

Fee refund or free flow editor role for everyone in the team.

### Describe alternatives you've considered

Postman flows should be runable on all members of professional plan.

**Comment by SterlingChin** [comment]
@furkan-altun, thank you for bringing this to my attention.

**Comment by rabbah** [comment]
Hi @furkan-altun - we've worked with the support team to address your concerns and I trust we have a satisfactory resolution in the works now. 

As you know now and for posterity, as of this September 15, Flows is available on all basic and professional plans now. More Flows products updates are covered in this blog post https://blog.postman.com/postman-flows-updates-plus-a-peek-into-the-ai-powered-future.

**Comment by furkan-altun** [comment]
Thanks for your support and refund process.
Also, it is important to enable users to use flows in all plans.
