### ISSUE TITLE
Invalid GraphQL Response

### ISSUE THREAD

**Issue by tim-hanssen** [a85/POSTMan-Chrome-Extension#12322]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

Since the new update it's not possible to display the raw body sent by a server if the request is done in GraphQL mode. The response shows an postman error "Received an invalid GraphQL response". This is very annoying when debugging GraphQL server errors.

### Describe the solution you'd like

Setting to make it possible to view the raw body.

**Comment by codenirvana** [comment]
@tim-hanssen Can you share the Postman app version where you notice this behaviour?

**Comment by tim-hanssen** [comment]
Sure! I'm using `Version 10.18.2 (10.18.2)`  @codenirvana

**Comment by codenirvana** [comment]
Can you share the steps to reproduce this issue? Any public endpoint to test this?

**Comment by tim-hanssen** [comment]
I think this happens when the content type is not matching `application/json`, simple request like a health check request, without a query triggers the same error

**Comment by tim-hanssen** [comment]
Still exists in `Version 10.18.10 (10.18.10)`

**Comment by timhall** [comment]
Hi @tim-hanssen I've found the source of the issue and I'm fixing it now. I'll update this issue once it's been released.

**Comment by timhall** [comment]
This was fixed in v10.20, thanks again for reporting the issue.
