### ISSUE TITLE
Global Variables are not being read on submission.

### ISSUE THREAD

**Issue by johnnavarra** [a85/POSTMan-Chrome-Extension#1233]
Example 
url: {{URL}}/Integration/Shops/{{ShopID}}
URL exists as an environment variable
ShopID exists as a global variable

If I generate a code snippet, it populates ShopID within the URL, however actually submitting the url will not work resulting in a 400 Bad Request.

**Comment by abhijitkane** [comment]
I have two global variables (no environment selected):
p1 = dump.getpostman.com
p2 = get
Setting the URL to {{p1}}/{{p2}} gives the correct response. 
What's the request URL in the network tab of DevTools (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/)?

**Comment by johnnavarra** [comment]
Hmm
It shows as this:
https://qat2-api.motor.com/v1/Selectline/Workflow/Integration/Shops/%011532/Active/Jobs?include=D,E,V

not sure where the %01 is coming from in the url. I'll get back to you. I
think there's somethign wrong with this variable.

On Thu, Jul 9, 2015 at 3:43 PM, Abhijit Kane notifications@github.com
wrote:

> I have two global variables (no environment selected):
> p1 = dump.getpostman.com
> p2 = get
> Settings the URL to {{p1}}/{{p2}} gives the correct response.
> What's the request URL in the network tab of DevTools (
> http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/
> )?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/postmanlabs/postman-app-support/issues/1233#issuecomment-120123170
> .

## 

AIM: obliviouslyaware
ICQ: 5147787
googletalk

**Comment by johnnavarra** [comment]
It was a bad variable. Thanks for your help!

On Thu, Jul 9, 2015 at 3:47 PM, John Navarra jnavarra@gmail.com wrote:

> Hmm
> It shows as this:
> 
> https://qat2-api.motor.com/v1/Selectline/Workflow/Integration/Shops/%011532/Active/Jobs?include=D,E,V
> 
> not sure where the %01 is coming from in the url. I'll get back to you. I
> think there's somethign wrong with this variable.
> 
> On Thu, Jul 9, 2015 at 3:43 PM, Abhijit Kane notifications@github.com
> wrote:
> 
> > I have two global variables (no environment selected):
> > p1 = dump.getpostman.com
> > p2 = get
> > Settings the URL to {{p1}}/{{p2}} gives the correct response.
> > What's the request URL in the network tab of DevTools (
> > http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/
> > )?
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/postmanlabs/postman-app-support/issues/1233#issuecomment-120123170
> > .
> 
> ## 
> 
> AIM: obliviouslyaware
> ICQ: 5147787
> googletalk

## 

AIM: obliviouslyaware
ICQ: 5147787
googletalk
