### ISSUE TITLE
Error when creating integration

### ISSUE THREAD

**Issue by bugaeva98** [a85/POSTMan-Chrome-Extension#12338]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

There are 4 integrations in the list of integrations

the integration limit per user is 5 pieces.

Expected result: The fifth integration was created without errors When creating your separate integration, the user will know about the error: You have reached the limit of the number of integrations you can create.

Expected result: The fifth integration was created without errors

### Steps To Reproduce

1. 4 integrations have been created
2. Create a fifth integration

### Screenshots or Videos

![image](https://github.com/postmanlabs/postman-app-support/assets/77605074/ea31568f-bd92-4244-999b-7b2f3452b13f)

![image](https://github.com/postmanlabs/postman-app-support/assets/77605074/aa358804-8cea-4634-ba5c-610c7c56d80d)

### Operating System

Windows

### Postman Version

10.18.4

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by bugaeva98** [comment]
additional Steps To Reproduce:

1. 5 integrations have been created
2. Remove one integration
3. Create a fifth integration

**Comment by saialekhya-001** [comment]
Thanks for bringing this to our notice!
We will work on the fix and will keep you posted once we have updates.

**Comment by saialekhya-001** [comment]
Hey @bugaeva98,
We are looking at the root cause of the issue and working on a fix for it. Meanwhile, we have mitigated the issue for now to unblock you from creating integrations. Do let us know if you are able to create integrations or not.
Thanks for your patience!

**Comment by bugaeva98** [comment]
@saialekhya-001, Thank you for the quick solution of the problem. I managed to create a fifth integration.
