### ISSUE TITLE
Updated to new version CLEAR ALL MY LOCAL COLLECTIONS

### ISSUE THREAD

**Issue by tanyaofei** [a85/POSTMan-Chrome-Extension#12331]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Well, I don't known why you guys update my postman, and all my local collections was clear. You guy SHOULD NOT do things like this!!!!

### Steps To Reproduce

Mad

### Operating System

macos

### Postman Version

10.18.2

### Postman Platform

Postman App

### User Account Type

Signed Out User

### Additional Context?

MAD!!!!!

**Comment by ST185103** [comment]
The same in Windows version.

**Comment by Shineson1001** [comment]
Hi,
if you want to use collections, you **have to** sign up here: [Create Postman Account](https://identity.getpostman.com/signup)
And you have to import your local data to the cloud inclusive all of your usernames/passwords/auth-token ... it is ridiculous.
![grafik](https://github.com/postmanlabs/postman-app-support/assets/22273771/7bf6c488-abf8-4f18-8f8b-73fa47c6a8c6)

There are backups of your local data under: %userprofile%\AppData\Roaming\Postman

The Cloud is useless for me. Bye bye postman

**Comment by jacobsorme** [comment]
Had the same thing happen to me, my Postman is basically a blank. Lost 50+ collections. All I see are some recent requests in history. How can I recovery my Collections? This is truly a disaster.

**Comment by jacobsorme** [comment]
See this link: https://community.postman.com/t/latest-update-of-postman-on-macos-erased-all-collection-data/52126 for how to recover.

I will not accept having my collections and requests in the Cloud. Anyone knows if this https://insomnia.rest/ is any better?

**Comment by giridharvc7** [comment]
Your collections are safe. The recommended way to move forward is to sign up, which will automatically migrate your collections and environments to Postman cloud. You also have an option to export all your collections and environments to a file. You can read more about our data security policy and FAQs over [here](https://blog.postman.com/announcing-new-lightweight-postman-api-client/)

Specifically about the auth passwords, we encourage you to use variables (Environment or collections). The variables values stored in the `Current value` section are local to your machine, and are never synced to Postman cloud, and the `Initial value` section can optionally be used, which is synced to Postman cloud to aid collaboration. More info You can read more about our data security policy and FAQs over [here](https://blog.postman.com/announcing-new-lightweight-postman-api-client/)

<img width="414" alt="image" src="https://github.com/postmanlabs/postman-app-support/assets/1040583/bd4fefaf-0693-432f-be5d-b42d2b3c1c83">

**Comment by baronvertigovongrahamthesecondofsealand** [comment]
To be quite frank, there is zero need for an API client like this to require an online account. This is placing artificial limitations on the users, and removing functionality that used to be standard. And then changing the offline client to a "lightweight" one with the useful features disabled.. its just a farce. You may have a good business reason for doing so, but we have good reason to stop using this client because of it.
