### ISSUE TITLE
MQTT topic unsubscribe didn't stop receiving messages

### ISSUE THREAD

**Issue by vordimous** [a85/POSTMan-Chrome-Extension#12343]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

While testing the new MQTT support i noticed my topic subscription wasn't having an effect on the behavior.

### Steps To Reproduce

Not sure exactly. I was sub/unsubbing a lot to test out some connection logic and ended up in this state.

### Screenshots or Videos

![image](https://github.com/postmanlabs/postman-app-support/assets/3012311/e6ad6dac-ec1e-4557-9f25-f2ba08a12381)

### Operating System

macOS

### Postman Version

10.18.4

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by jonathanhaviv** [comment]
Thanks for reporting this @vordimous. Will look into this and let you know once we have a solution.

When trying to reproduce this on my end could you let me know a bit more about the connection and frequency of incoming messages on the topic you're unsubscribing from?

**Comment by jonathanhaviv** [comment]
@vordimous also would you be able to share your full subscription list?

**Comment by vordimous** [comment]
Hi @jonathanhaviv thank you for getting back to me. I can share the MQTT simulator I was using to produce all of these messages. I am using Postman for our quickstart, which is also when I ran into this bug: https://docs.aklivity.io/zilla/latest/tutorials/quickstart/kafka-proxies.html

I was testing the connection and reconnection to our MQTT broker from Postman. I subbed and unsubbed frequently while connecting and disconnecting.

**Comment by jonathanhaviv** [comment]
Thanks @vordimous! I'm still having some issues with reproducing this on my end. Are you able to share the request with me that you were trying out?

Btw love this MQTT simulator!

**Comment by vordimous** [comment]
The project is really nice and the author is friendly: https://github.com/DamascenoRafael/mqtt-simulator

**Comment by vordimous** [comment]
> I'm still having some issues with reproducing this on my end. Are you able to share the request with me that you were trying out?

I haven't seen the issue again. It could have been that our MQTT broker sent a strange connection signal. I wanted to report it in case your team had seen something similar.

**Comment by jonathanhaviv** [comment]
Okay, thanks for the heads up. I'm going to close this for now and if you notice it again don't hesitate to let us know!
