### ISSUE TITLE
Srolling Bug 

### ISSUE THREAD

**Issue by syney** [a85/POSTMan-Chrome-Extension#1234]
We are using description in collections. But when its littlebit longer, its not possible sroll that. (Mac - Yosemmite) :/ (Sorry for czech in screenshots) 

![snimek obrazovky 2015-07-10 v 10 47 46 2](https://cloud.githubusercontent.com/assets/6173402/8615332/1809c10e-26f2-11e5-9e0a-84d3ba020812.png)
![snimek obrazovky 2015-07-10 v 10 42 42](https://cloud.githubusercontent.com/assets/6173402/8615333/180da6ca-26f2-11e5-85e8-a99ac79a95ce.png)

And also i dont like edit collection window - when you click next to a window, it disappears and not save. Remember that we are writing this desription when we stare into the our code. (You know, its not safe work :D) 

Are you planning site for more information, more comprehensive wiki?

Or have you issue report console? Something like 

Best Regards! 
Tomas

**Comment by abhijitkane** [comment]
Thanks for reporting this - we'll fix the scrolling issue in a future release.

We're working on a more comprehensive collection information section - follow https://twitter.com/postmanclient for updates.

**Comment by jormaechea** [comment]
I don't think this is a `Usability` issue. This is more likely a bug. I have my collection description and it doesn't fit in normal desktop screens.  
I have two consequences:  
1. Description cannot be read 
2. Collection's request aren't displayed as well as their descriptions.

I really expect this to be solved..

**Comment by numaanashraf** [comment]
Fixed in v4.0
