### ISSUE TITLE
Proxy debug session "Response Time" alphabetical sorting

### ISSUE THREAD

**Issue by goto1134** [a85/POSTMan-Chrome-Extension#12346]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Sorting by `Response Time` is alphabetical. It should be by time value in milliseconds.

### Steps To Reproduce

1. Run a proxy debug session
2. Collect request the magnitude of ms, tens of ms, hundreds, and minutes
3. Sort by `Response Time`

### Screenshots or Videos

![image](https://github.com/postmanlabs/postman-app-support/assets/9569795/b3c51bab-fba7-4678-ad0a-bd0dde2e3c9e)

### Operating System

macOs

### Postman Version

10.18.6

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by VShingala** [comment]
@goto1134 Thanks for reporting the issue! We're working on a fix for this and will inform here once this is fixed.

**Comment by VShingala** [comment]
@goto1134 This issue has been fixed with latest Postman App. Feel free to re-open the issue if you're facing any further problem with the fix.
