### ISSUE TITLE
Mqtt postman CLEAN_START is not set in the CONNECT packet

### ISSUE THREAD

**Issue by bmaidics** [a85/POSTMan-Chrome-Extension#12342]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

By default in an MQTT connection, clean session is on in the settings. But Postman is not setting it in the MQTT CONNECT packet.
Turning it off, and then on again works, and Postman is sending the correct CONNECT packet

### Steps To Reproduce

Connect to an MQTT broker using Postman with clean_session on in the settings (default)
In Wireshark the CONNECT packet is sent with clean_session flag 0.

### Screenshots or Videos

![image](https://github.com/postmanlabs/postman-app-support/assets/25647251/e1ecbbbc-206a-4c9e-94f3-2144eb6d1715)
![image](https://github.com/postmanlabs/postman-app-support/assets/25647251/df290d65-9a4a-4f9a-a372-37660487daba)

### Operating System

macOs

### Postman Version

10.18.4

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by jonathanhaviv** [comment]
Thanks for reporting this @bmaidics! Looking into it now and will let you know once we release a fix.

**Comment by jonathanhaviv** [comment]
Hey @bmaidics, just wanted to let you know that we have released a fix for this in our October release (v10.19). Let us know if you have any other issues or feedback!
