### ISSUE TITLE
MQTT: Dynamic Topics (Variables)

### ISSUE THREAD

**Issue by sam-innes** [a85/POSTMan-Chrome-Extension#12354]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

At the moment we have a team of developers who all have their own IOT stacks. With these stacks, we're able to use Postman with forked collections to set up individualised requests to test our feature sets.

We use MQTT as our predominant messaging technology so, given that we already use Postman for rest consumption, this was very much welcomed in our team.

However, unlike with HTTP requests we can't appear to use dynamic topics (i.e. topics using variables). This causes an issue for us because we can't set up generic collections to be used for individual stacks.

### Describe the solution you'd like

It would be useful if MQTT topics were dynamic - at the moment they don't appear to support variables in the same way that other types of requests do. It would also be useful to be able to do collection forks in the same way as HTTP collections - but one step at a time!

**Comment by jonathanhaviv** [comment]
Hi, @sam-innes we have this support in our internal roadmap and hope to have it out soon.

Also, would we be able to schedule a call with you to better understand your and your team's MQTT workflows?

**Comment by jonathanhaviv** [comment]
Hey @sam-innes just wanted to follow up with you and let you know that in our October Release (v10.19) we added variable support for topics! Let us know if you have any issues or additional feedback but going to close this out for now. Thanks!
