### ISSUE TITLE
Removed collections

### ISSUE THREAD

**Issue by adver89** [a85/POSTMan-Chrome-Extension#12356]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

After running application Postman updated itself and removed all my collections without asking question

### Steps To Reproduce

1. Run Postman
2. Search for collections
3. Collections doesn't exists anymore

### Operating System

Windows

### Postman Version

10.18.2

### Postman Platform

Postman App

### User Account Type

Signed Out User

**Comment by giridharvc7** [comment]
You can read more about these changes in the blog [here](https://blog.postman.com/announcing-new-lightweight-postman-api-client/). 
Your collections are safe. 
On signing up or Signing in your collections are automatically synced with Postman cloud. 
If you don't wish to choose this path, you can alternatively export your collections.

**Comment by icyerasor** [comment]
Export in the "brand-new lightweight API client" aka "force users to upload files to postman cloud / aws" works as it did before:
`Burgermenu -> File -> Settings -> Data -> Export Data`

You also can find the last backups in your local app data folder. i.e. for Windows it usually is `%USERPROFILE%/AppData/Roaming/Postman/` -> `C:\Users\UserName\AppData\Roaming\Postman` there should be some Files named `backup-yyyy-mm-ddTHH-mm-ss.SSSZ.json` that include your collections, requests, etc.

Note that once you sign in with an account, your local collections will automatically be uploaded, possibly "exposing" confidential information.
