### ISSUE TITLE
Capture requests in firefox using postman intercepter

### ISSUE THREAD

**Issue by amrithasilva** [a85/POSTMan-Chrome-Extension#12364]
### Describe the Issue

I have installed postman desktop application. i added postman interceptor add-on both firefox and chrome. There is no issue with chrome. but it doesn't work in firefox. interceptor bridge also there. but it keeps capturing empty requests.
 Firefox version : 118.0 (64-bit)

### Steps To Reproduce

1.Install postman add-on Firefox
2.Click start capture 
3.Open postman desktop app using popup link
4.check interceptor bridge enabled
5.browse the urls
6.No requests capture 

### Screenshots or Videos
![image](https://github.com/postmanlabs/postman-app-support/assets/78518047/f5dacda1-c98c-4dcc-834d-617c1bdc6dd6)

### Operating System

Linux Mint 20.2

### Postman Version

10.18.9

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by agrwl-harsh** [comment]
@amrithasilva, InterceptorBridge is no longer required to use the interceptor. It appears that the Firefox extension lacks the necessary permissions to capture requests. Could you please check if it has the required permissions?

The option `Access your data for all websites` should be checked.

<img width="1512" alt="image" src="https://github.com/postmanlabs/postman-app-support/assets/99398960/ea6966f2-535d-4bad-859d-478196b03bd7">

**Comment by amrithasilva** [comment]
> @amrithasilva, InterceptorBridge is no longer required to use the interceptor. It appears that the Firefox extension lacks the necessary permissions to capture requests. Could you please check if it has the required permissions?
> 
> The option `Access your data for all websites` should be checked.
> <img alt="image" width="1512" src="https://user-images.githubusercontent.com/99398960/271475078-ea6966f2-535d-4bad-859d-478196b03bd7.png">

That was the issue.Access your data for all websites. Now it works. thanks
