### ISSUE TITLE
OAuth 2 refresh request headers aren't sent during auto-refresh

### ISSUE THREAD

**Issue by Reprevise** [a85/POSTMan-Chrome-Extension#12363]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

For auth to work, we have to set the `User-Agent` header for token requests. When setting a header in the Refresh Request parameter table, you'll see that it's not sent when you request an authorized endpoint **and your token is expired**, however it is sent when you click the "Refresh" underlined button that's right next to the "Expires at X today" text. When I sent an authorized request and my token is expired, I get an error because the `User-Agent` header wasn't updated to what I had set it to in the config.

### Steps To Reproduce

1. Create a collection with a request that requires an OAuth 2.0 access token.
2. Configure OAuth 2.0 in the collection's Authorization tab
3. Ensure the "Auto-refresh token" option is switched on
![Auto-refresh token option slider](https://github.com/postmanlabs/postman-app-support/assets/25782944/b19a2843-6fa1-49cf-bc86-339ac8e84223)
4. Under "Advanced", add a `User-Agent` header value and ensure "Sent In" is marked as "Request Headers"
![Refresh Request parameters table for OAuth 2.0](https://github.com/postmanlabs/postman-app-support/assets/25782944/b143300d-914c-40c6-aef2-a6ab28082ba0)
5. Send a request when your access token is expired so that Postman goes to auto-refresh it.
6. You'll see in the request headers in the logs that the `User-Agent` header is still "PostmanRuntime/X."

### Operating System

Windows 11

### Postman Version

10.18.9

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by abhijeetborole** [comment]
Hey @Reprevise, thanks for reporting this issue. Postman takes a snapshot of the headers when the token is generated as this token is stored locally and available across collections and workspaces. Changes to the refresh request parameters will reflect when you generate a new token. Could you try to:
1. Add the `User-Agent` header to the `Refresh Request` as you've done already
2. Generate a new access token with the headers added.
3. Now refresh the access token -> Your headers should be sent.


https://github.com/postmanlabs/postman-app-support/assets/9638586/b075b68f-2cfa-47e2-b358-93d719c62b59

**Comment by Reprevise** [comment]
Closing this issue as I can no longer reproduce it.
