### ISSUE TITLE
Request will not terminate

### ISSUE THREAD

**Issue by logbon72** [a85/POSTMan-Chrome-Extension#1236]
I tried connecting to a REST API which I'm working on currently working on and the the request continued indefinitely and will not terminate. 

On further investigation, I discovered that it was because I had disabled the Interceptor plugin in chrome, but still left the Interceptor on in Postman.

**Comment by abhijitkane** [comment]
Hm..You can't enable the Interceptor in Postman if it's disabled in Chrome, but once it's enabled in Postman, disabling it in Chrome will lead to this behavior. We'll add a check for this soon.

**Comment by logbon72** [comment]
Yes, that was exactly how it happened, I spent so much time debugging my server application, because I thought that was where the problem was from.
