### ISSUE TITLE
List Dynamic variables on VSCode extension

### ISSUE THREAD

**Issue by gersanco** [a85/POSTMan-Chrome-Extension#12375]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

When I try to use [dynamic variables](https://learning.postman.com/docs/writing-scripts/script-references/variables-list/) on the app I can see the full list when I type  `{`

<img width="417" alt="image" src="https://github.com/postmanlabs/postman-app-support/assets/12337026/d1dd9f27-b249-48f4-945a-3c510bbe72c5">

However, I can't do the same on VSCode extension. Despite that it works but I need to know the exact name.

![image](https://github.com/postmanlabs/postman-app-support/assets/12337026/82ac590a-ec92-4767-b562-b1cd51d620f3)

### Describe the solution you'd like

List those dynamic variables on the VSCode extension with the info as Postman app.

**Comment by pankajk07** [comment]
@gersanco This feature is available in the extension. Please try it out.
