### ISSUE TITLE
Bug - Export data doesn't work

### ISSUE THREAD

**Issue by saisn-kr** [a85/POSTMan-Chrome-Extension#12384]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

postman.co/me/export doesn't complete the process. It stays 'zipping' forever. 

### Steps To Reproduce

1. open settings > data > request export data
2. takes to the website 
3. click export data

### Screenshots or Videos

![pm export issue](https://github.com/postmanlabs/postman-app-support/assets/74375444/36f2dd47-5cfa-4041-ab03-b9a7a73aeb2e)

### Operating System

Windows

### Postman Version

10.18.9

### Postman Platform

Postman Web

### User Account Type

Signed In User

**Comment by sony-mathew** [comment]
Hey @saisn-kr , thank you for reporting this. We will take a look at this and get back to you.

**Comment by aquibjr-postman** [comment]
Hey @saisn-kr , sorry for the late response. We have worked on improving reliability of the export feature. Please try the export again and let us know if it still gets stuck.

**Comment by aquibjr-postman** [comment]
Closing this ticket for now. Please feel free to reopen if you face this issue again.
