### ISSUE TITLE
Headers with Pre-request values are not updating

### ISSUE THREAD

**Issue by eallenvii** [a85/POSTMan-Chrome-Extension#1238]
Hello, i'm working with a api and trying to test out some of its edges and i noticed a couple of things:

1) I cannot see in postman itself what the actual request was (including header values generated, etc), nor can i developer tools
2) When i wireshark the request the header values are very old!  They do not update at all.  The header values i have are dynamic and should regenerated on every request.

Here is more information:

<img width="600" alt="screenshot 2015-07-10 13 06 41" src="https://cloud.githubusercontent.com/assets/7996528/8628071/950e9bb8-2704-11e5-9e4d-5d0ec68d31a1.png">
<img width="600" alt="screenshot 2015-07-10 13 05 53" src="https://cloud.githubusercontent.com/assets/7996528/8628074/95128912-2704-11e5-8739-22de5c02e16b.png">
<img width="600" alt="screenshot 2015-07-10 13 04 41" src="https://cloud.githubusercontent.com/assets/7996528/8628073/9511d706-2704-11e5-91c3-775976912c06.png">
<img width="600" alt="screenshot 2015-07-10 13 01 24" src="https://cloud.githubusercontent.com/assets/7996528/8628072/950f24de-2704-11e5-831a-db779b6a10af.png">

**Comment by abhijitkane** [comment]
You have an async function in the pre-request script section. The pre-request script is executed synchronously, and any the behavior of async callbacks is not defined. When the getScript callback is executed, the request has already been sent.

To add a custom JS file to the sandbox, you can try this - https://github.com/postmanlabs/postman-app-support/issues/734#issuecomment-70481732

**Comment by eallenvii** [comment]
Awesome!  Thank you very much, my hours of googling was failing me hard.

Postman is a great, great product, keep up the good work.
