### ISSUE TITLE
Feature request: disable clickable URLs in pretty view

### ISSUE THREAD

**Issue by cnanney** [a85/POSTMan-Chrome-Extension#1239]
These are pretty useless as they currently are:
1. They open a new Postman tab, not a browser tab.
2. They don't have the same "link" context menu as Chrome, that has some useful options:
   ![image](https://cloud.githubusercontent.com/assets/195134/8636057/736ea076-2811-11e5-96aa-72600275dc2b.png)
3. Makes it hard to select the actual text of the url without clicking the link and opening a new tab.

Maybe if you added a modifier, like CTRL would make the url clickable, but otherwise it is just text. Otherwise, I'd prefer the ability to disable them altogether.

**Comment by cnanney** [comment]
There is also a problem with URL detection:

![image](https://cloud.githubusercontent.com/assets/195134/9207460/6d6ef0a6-4033-11e5-8f1e-15dce0440840.png)

It sees the bulk of that string as a URL after the first `/`. The ability to not create clickable links at all would be great.

**Comment by curtisgibby** [comment]
See also #2030
