### ISSUE TITLE
Group Environment and Collection exports

### ISSUE THREAD

**Issue by stephens2424** [a85/POSTMan-Chrome-Extension#124]
It would be great if you could export environment variables and collections at the same time, into the same file. I'm looking to use this at work with people who aren't the most advanced when it comes to manual requests like this. 

It would be even better if you could leave certain things blank in the environment export and have the extension prompt you upon import to fill in that information. That would be great for a field like API key.

I may work on this myself, but I thought I'd put it here for centrality's sake.

**Comment by jainprash** [comment]
+1.... This is a must needed feature, for multiple collection groups. Atleast a default environment for a given collection, would be good start

**Comment by veee-hao** [comment]
what's the status now ?  Does this feature being implemented ?
