### ISSUE TITLE
MQTT - Use variables in message

### ISSUE THREAD

**Issue by hatamiarash7** [a85/POSTMan-Chrome-Extension#12405]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

It's not possible to use variables in MQTT messages.

### Steps To Reproduce

1. Create a variable in the collection
2. Create an MQTT request
3. Use the variable in the message
4. Sendthe 

### Screenshots or Videos

<img width="478" alt="image" src="https://github.com/postmanlabs/postman-app-support/assets/16325641/840598d7-e500-4677-8400-06cab812cbb7">

### Operating System

macOS

### Postman Version

10.18.11

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by jonathanhaviv** [comment]
Hi @hatamiarash7 thanks for reporting this. I'm having some trouble trying to reproduce this. Are you changing environments after connecting to an MQTT broker? For each connection, the client will use the environment selected at the time of connection not at the time of send.

Let me know if this helps or if you have any information that might help us debug this. Thanks!

**Comment by hatamiarash7** [comment]
I think this problem was fixed in later versions. It's working in version `10.19.2`.
