### ISSUE TITLE
oauth 1.0a callback field

### ISSUE THREAD

**Issue by alexzm1** [a85/POSTMan-Chrome-Extension#1240]
The callback field is an optional field for oauth 1.0a authentication, it would be great to support this parameter.

**Comment by alexzm1** [comment]
I've found that this field is even required for 1.0a it is explained in the oauth documentation, point 6.1.1
http://oauth.net/core/1.0a/#auth_step1

**Comment by dogeviper** [comment]
Hi, have you guys taken a look at this? I am working with an OAuth flow that requires the callback url to be specified. Also, is there a way to manually add the callback url field in the meantime?

**Comment by bradparks** [comment]
Insomnia supports callback, and is an opensource cross platform REST client:

https://github.com/getinsomnia/insomnia

**Comment by mohitranka** [comment]
This has been released in the lastest Postman app V7.27. Please upgrade and give it a go!
