### ISSUE TITLE
Creating a global / collection level function

### ISSUE THREAD

**Issue by BozhidarIvanov02** [a85/POSTMan-Chrome-Extension#12413]
### Describe your current workflow

Currently, if I want to reuse a function I would need to copy - paste it in every single request. However, in my case, these are just the four same functions, and it is quite pointless to have them spread around 300 requests.

### Describe your ideal workflow

Would be ideal, a new feature is integrated regarding the creation of a global / collection level functions, which can be used in the requests later on ( could already be done).

### Additional context

I have already looked into the issues, which has been around for quite a while, but did not find a solution yet, correct me if I am wrong.

**Comment by BozhidarIvanov02** [comment]
Found out a similar request from another user just now, which dates from 2 weeks ago, you can close the issue with some new information regarding the feature or alternative workarounds. Thanks!

**Comment by malvikach** [comment]
Hi @BozhidarIvanov02 👋 

Thanks for sharing the feedback on this! We are researching more about such use cases and would love to understand how you wish to use such functions. 

Would you be available for a call with us. Here is a [link](https://calendly.com/d/4dx-j7y-n5j/postman-api-testing-reusable-scripts-and-functions) to our calendars that you can use to block some time. 

Looking forward to speaking with you!

Cheers,
Malvika

**Comment by postfrzero** [comment]
Hey folks -- Postman v11 rolled out a few weeks ago with support for the new Package Library, which enables you to reuse code by creating and requiring packages within your scripts. Learn more about the Package Library [here](https://blog.postman.com/postman-v11-plans-packaging-updates-2024/#what-is-the-package-library-for-reusable-scripts) or [here](https://learning.postman.com/docs/tests-and-scripts/write-scripts/package-library/).
