### ISSUE TITLE
Extension won't install in Windows due to 'to resolve:' filename being invalid

### ISSUE THREAD

**Issue by ghost** [a85/POSTMan-Chrome-Extension#1241]
OS: Windows 8.1
Chrome version: 43.0.2357.132 m

When installing Postman through the Chrome Web Store, I was greeted with the error: "Package is invalid. Details: 'Could not unzip extension'."

Some googling revealed that this can be caused by an invalid filename inside the .crx, so I used http://chrome-extension-downloader.com/ to grab the .crx, then opened it up to find a "to resolve:" file inside.

Colons aren't valid filename characters in Windows, so I extracted all of the files except for "to resolve:", then used the Load unpacked extension in chrome://extensions to install Postman, which worked fine.

I imagine this might be a problem for anyone trying to install the extension using Windows.

**Comment by a85** [comment]
Thanks! We are looking in into this.

**Comment by pwae** [comment]
I have the same issue on Windows 7 as well, same version of Chrome.

**Comment by abhijitkane** [comment]
@pwae @raayle We've updated Postman to v3.0.4. Can you try updating/installing now?

**Comment by ghost** [comment]
It's working fine now, thanks!
