### ISSUE TITLE
[Desktop] JSON Response Prettier stuck at formatting... & returns unformatted data

### ISSUE THREAD

**Issue by keithfy96** [a85/POSTMan-Chrome-Extension#12414]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

On the Desktop version of postman, the JSON response appears as a single line instead of being formatted properly. 

The web version works fine, to illustrated the example have inserted some photos using a simple books api 
https://www.abibliadigital.com.br/api/books

![image](https://github.com/postmanlabs/postman-app-support/assets/107264025/e36aa554-937a-49ab-870b-13625753001f)

When doing the same on my desktop app this is the resulting out, furthermore the "Formatting..." alert continues to be present and does not complete. 

![image](https://github.com/postmanlabs/postman-app-support/assets/107264025/a6d04873-e246-406a-b4a6-7916c83d6014)

The same problem occurs for all api calls on my desktop application

### Steps To Reproduce

Send a get request to https://www.abibliadigital.com.br/api/books on the desktop version of postman

### Screenshots or Videos

![image](https://github.com/postmanlabs/postman-app-support/assets/107264025/4fe1387b-519b-484b-8dc0-9d349fd4a88c)
![image](https://github.com/postmanlabs/postman-app-support/assets/107264025/279f7227-5d01-445c-a032-4bf18a3bb887)

### Operating System

Windows

### Postman Version

10.19.5

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by sathishkumar-thangavel11** [comment]
@keithfy96  Can you try updating the postman desktop app to the latest version and check this once again ?

**Comment by sunnyape** [comment]
I have the same issue.

JSON responses in the Pretty panel are rendered as a single line. If I switch to one of the other formats, such as Raw, then switch back to Pretty, I get the correct formatting:

![Postman Pretty JSON format bug](https://github.com/postmanlabs/postman-app-support/assets/32824881/de880426-320f-4400-a991-7affb1ec41b6)

I'm running Postman v10.21.9  on Win11 64bit and

**Comment by artsakenos** [comment]
Same issue.
Postman v10.21.9 on Win11 64bit
Confirm that in order to solve it, need to switch to another tab (e.g., raw) and back again the pretty formatting is restored.

**Comment by keithfy96** [comment]
Ended up reformatting my com and the new installation had no issue lol sorry can't try to replicate this again

**Comment by charlesritchea** [comment]
This is happening for me, if I switch from JSON to Raw then back it is fixed, so might be a change detection issue?

**Comment by Seamain** [comment]
I have the same problem. My Postman version is v10.22.9 and it's running on Windows 11 64-bit.

**Comment by samarthgulati** [comment]
Hello, we have the fix rolled out as part of v10.23.1 of the app. Kindly relaunch your app or refresh the webpage to ensure you get the latest version running. Let me know if you are still facing the issue.
