### ISSUE TITLE
Monitors broken in latest release (v10.19)

### ISSUE THREAD

**Issue by mark-attridge** [a85/POSTMan-Chrome-Extension#12422]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

I've been manually running monitors for the past few weeks to implement test coverage for our APIs.  It was running fine in the Postman App up until yesterday (10/18/2023), but then today (10/19/2023) I'm getting errors.

Mainly the ERROR: read ECONNRESET.

No code has changed on our APIs.  Just been adding new test coverage into my collection and then running via monitors.  I see that Postman was upgraded on my environment yesterday (10/18), likely after I had completed work for the day. 

I can hit our APIs using normal means (browser using Swagger and our front-end app), and I can run individual endpoints in Postman without problems.  But once I try to run even a single endpoint in a monitor, I get the error above.

Any thoughts on what may have changed in the v10.19 update with respect to monitors?

### Steps To Reproduce

Create a monitor for a collection.  Manually run the monitor.  See ECONNRESET error.

### Operating System

Windows 10 Pro

### Postman Version

10.19

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by mark-attridge** [comment]
I should also add the same ECONNRESET errors occur when running the collection through a GitHub workflow using Newman.  Every single endpoint in the collection fails.

**Comment by codenirvana** [comment]
@mark-attridge Can you share a scaled-down collection that we can use to reproduce this issue?
I tried with the `https://postman-echo.com/get` endpoint, and the Monitors are working fine.

Also, can you share the Newman and Node.js versions used in your GitHub workflow?

**Comment by mark-attridge** [comment]
Inexplicably, I ran my monitor again this morning, and it works!!  No changes on my end since yesterday when I posted this ticket.  So something along the line has fixed itself.  Strange indeed.  I will close the ticket, but will re-open if the problem returns.
