### ISSUE TITLE
VSCode extension not saving environment variable in collection's bearer token authorization

### ISSUE THREAD

**Issue by tedmed** [a85/POSTMan-Chrome-Extension#12428]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

In VSCode when using environment variable in collection, specifically in bearer token authorization, after saving the collection, the filled in token variable is not saved and disappears after saving.

Checked the web version, where this exact same procedure works without an issue.

### Steps To Reproduce

1. create token environment variable
2. open collection
3. choose bearer token authorization in authorization tab
4. use {{token}} in the blank space for token
5. save the collection (I use Ctrl + S)

### Operating System

Linux

### Postman Version

0.12.1

### Postman Platform

Other

### User Account Type

Signed In User

**Comment by dizzyjaguar** [comment]
I'm having the same issue

**Comment by pankajk07** [comment]
@tedmed This issue was fixed. Please update your extension and try it out. Feel free to open the ticket or create a new one if the problem persists.

**Comment by newpen** [comment]
I still got he same issue. Environment variables can't be used as a token under the Authorization tab?
