### ISSUE TITLE
Everyone can access someone's api..

### ISSUE THREAD

**Issue by EverybodyBusiness** [a85/POSTMan-Chrome-Extension#12430]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

In Search bar of windows POSTMAN application, anyone can access someone's api .

### Steps To Reproduce

In Search bar of windows POSTMAN application, anyone can access someone's api .

### Screenshots or Videos

![image](https://github.com/postmanlabs/postman-app-support/assets/102199931/df1d34ac-43e9-4d74-a274-333ae3c73e2e)

### Operating System

Windows

### Postman Version

19 Sep 2023, 6:08 PM by

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by giridharvc7** [comment]
These are public APIs that published by users so others can get benefitted out of this. Postman's search feature searches though our Public API Network as well. 
Learn more about Postman's Public API network [here](https://learning.postman.com/docs/getting-started/first-steps/exploring-public-api-network/) and access the Public API Network [here](https://www.postman.com/explore)
