### ISSUE TITLE
Collections are multiplying themselves

### ISSUE THREAD

**Issue by patricksavalle** [a85/POSTMan-Chrome-Extension#1244]
Don't know how or when. Did not try to reproduce, but I notice that while working with Postman my collections are multiplying :)

Very quickly after restarting, they appear again.

<img width="1220" alt="screen shot 2015-07-14 at 13 27 40" src="https://cloud.githubusercontent.com/assets/701331/8672173/29754cb4-2a2c-11e5-9356-12462ba8dbc6.png">

**Comment by abhijitkane** [comment]
Do you see any errors in the console - http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/?

Signing out and signing back in should restore your app to the correct state.

**Comment by patricksavalle** [comment]
I see already duplicate collections right after I import a set of 10 collections. Into an empty Postman. Every time different duplicates.

**Comment by abhijitkane** [comment]
@patricksavalle Do you see any errors in the console - http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/?
Can you mail the file you're importing to help@getpostman.com?

**Comment by patricksavalle** [comment]
No. No errors. The files I am importing are here: https://github.com/mobbr/mobbr-api-tests

What I do is import them all at once.

**Comment by abhijitkane** [comment]
https://github.com/mobbr/mobbr-api-tests/blob/master/balances.json, 
https://github.com/mobbr/mobbr-api-tests/blob/master/invoices.json, 
https://github.com/mobbr/mobbr-api-tests/blob/master/keywords.json, 
and https://github.com/mobbr/mobbr-api-tests/blob/master/domains.json all appear to have the same data - namely a collection called 'Mobbr Keywords API Test'

**Comment by patricksavalle** [comment]
Really? But still as you see on my screenshot, the other collections /payments multiple too. I will look into the scripts you mentioned. I was still organizing them, but this could explain a lot of my confusion :)

**Comment by abhijitkane** [comment]
Do you also see the problem if you import them one at a time?

**Comment by patricksavalle** [comment]
I will try to figure this out completely in a few hours!
