### ISSUE TITLE
Increase session timeout of Mac Client

### ISSUE THREAD

**Issue by asthinasthi** [a85/POSTMan-Chrome-Extension#12451]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

I am frequently logged out of Postman. I have to do SSO sign in and it takes forever!

It is affecting productivity. I have started using Insomnia even though we pay for Enterprise Postman.

### Describe the solution you'd like

Give users ability to control session timeouts.

### Describe alternatives you've considered

Other tools like Insomnia

**Comment by numaanashraf** [comment]
@asthinasthi Session timeouts are configured by the admins of your Postman Enterprise team and it seems your team admins might have configured a short timeout. 

Could you write to us at help@postman.com with your team domain and account details? We can verify this at our end.
