### ISSUE TITLE
Postman for VS Code: Could not login: Network error (certificate signature failure)

### ISSUE THREAD

**Issue by FaCoffee1984** [a85/POSTMan-Chrome-Extension#12467]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Upon launching Postman in VS Code, I cannot log in nor can I create a new account. An error window pops up with the message: `Could not login: Network error (certificate signature failure)`

![image](https://github.com/postmanlabs/postman-app-support/assets/60174218/978208b2-6b43-4349-b6c4-cabe8d9f8365)

### Steps To Reproduce

1. Open VS Code
2. Install Postman extension
3. Open Postman extension
4. Click "Sign In" or "Create Account"
![image](https://github.com/postmanlabs/postman-app-support/assets/60174218/f226617a-3e50-43c3-958d-3b2668766a4f)

### Operating System

Windows

### Postman Version

0.13.1

### Postman Platform

Other

### User Account Type

Signed Out User

### Additional Context?

This is what the extension logs show relative to the last attempt I made:
```
(2023-11-10T13:22:30.244Z) [info] [extension:sidebar:manager] set login state to busy
(2023-11-10T13:22:30.244Z) [info] [extension:auth] Starting the login flow
(2023-11-10T13:22:30.339Z) [error] [extension:auth:client] Network error (certificate signature failure)
(2023-11-10T13:22:30.340Z) [error] [extension:auth:controller] retrieving the redirect URL failed: {"error":"Network error (certificate signature failure)"}
(2023-11-10T13:22:30.341Z) [error] [extension:auth] The sign in flow has failed: {"error":{"reason":"Error","details":"Network error (certificate signature failure)"}}
(2023-11-10T13:22:30.343Z) [info] [extension:sidebar:manager] resetting the login state to signin
```

**Comment by v0rts** [comment]
I have the same issue

**Comment by pankajk07** [comment]
@FaCoffee1984 @v0rts Are you trying to log in from vs code behind a proxy? Please check out the resolution suggested in the following ticket and try to log in again https://github.com/Microsoft/vscode/issues/3492 .

**Comment by pankajk07** [comment]
@FaCoffee1984 Can you please confirm if the above solution resolves the issue or if it is still reproducible?

**Comment by pankajk07** [comment]
@FaCoffee1984 I will go ahead and close the ticket, as we did not get any response from your side. Feel free to create a new ticket, if the issue is still reproducible on your side.
