### ISSUE TITLE
Clicking on an example tab already open runs the request

### ISSUE THREAD

**Issue by Ian1971** [a85/POSTMan-Chrome-Extension#12465]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

If I have an example tab open already. Then click to a different tab, and back to the example tab it runs the request without pressing send.

### Steps To Reproduce

1. Run an example tab
2. Click on a different tab
3. Click back on the example tab

### Operating System

Windows

### Postman Version

10.19

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by vedkribhu** [comment]
@Ian1971 this should be fixed now in v10.21. Let me know if you are still facing this issue.
