### ISSUE TITLE
Leaving Postman open on M1 Mac results in performance tab disappearing 

### ISSUE THREAD

**Issue by YuewenForumsys** [a85/POSTMan-Chrome-Extension#12462]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

I left Postman to run a couple of tests on M1 MAC. However, when I awake the screen the observe that the performance tab disappeared. Uninstall/install and login/log out the Postman does not help me to solve the issue. FYI, I am using latest version of Postman: 
10.19.7

### Steps To Reproduce

1. Navigate to the run view.
2. Observe that there is no performance tab. 

### Screenshots or Videos

![Screen Shot 2023-11-08 at 10 03 19 AM](https://github.com/postmanlabs/postman-app-support/assets/135069708/753aba06-f21d-46df-8c6e-93ebcdd3d4e5)

### Operating System

macOS

### Postman Version

10.19.7

### Postman Platform

Both

### User Account Type

Signed In User

**Comment by YuewenForumsys** [comment]
Resolved by the support team.

**Comment by Ploryyy** [comment]
> Resolved by the support team.

May I ask how this question was finally resolved?
