### ISSUE TITLE
Interceptor installed but Cookies tab still shows "Install free Interceptor..." 

### ISSUE THREAD

**Issue by mringer** [a85/POSTMan-Chrome-Extension#1246]
New to this app, installed it and the interceptor, which worked briefly then reverted back to the preinstall state. I've un/reinstalled both several times, restarted chrome, the laptop, etc. Not sure what else to try.

Google Chrome   43.0.2357.134 (Official Build) (64-bit)
Revision    8f3081cb09276898e725262e5ca6ec7746757188-refs/branch-heads/2357@{#499}
OS  Mac OS X 
Blink   537.36 (@198523)
JavaScript  V8 4.3.61.38
Flash   18.0.0.209
User Agent  Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.134 Safari/537.36

![screen shot 2015-07-14 at 2 20 59 pm](https://cloud.githubusercontent.com/assets/2614536/8681508/c9f6c204-2a35-11e5-8776-f7a1041d80f7.png)

**Comment by abhijitkane** [comment]
Can you go to chrome:/extensions and check what versions of Postman and Interceptor you have?

**Comment by mringer** [comment]
Thanks for the quick reply!

Postman 3.0.4
Postman Interceptor 0.2.10

**Comment by abhijitkane** [comment]
Hm..the Interceptor is clearly working, as you're able to receive the response with the Interceptor turned on. Not sure why the cookies section isn't detecting the change. Can you try this - 

Open the DevTools window for Postman(http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/), go the the Console, and enter this:
`$("#response-cookies-not-found-message").hide(); $("#response-cookies").show();`

**Comment by mringer** [comment]
OK, so after I entered that, the tab contents switched to the Cookie table header but, with no rows in the table. Sending the same request again reverts the style back to #response-cookies-not-found-message. Strange.

**Comment by mringer** [comment]
![screen shot 2015-07-14 at 3 07 04 pm](https://cloud.githubusercontent.com/assets/2614536/8682271/0483a442-2a3a-11e5-8e4b-15d6b944e2b3.png)

**Comment by abhijitkane** [comment]
Ah..the Interceptor message displays if there are no cookies in the response. We'll fix this in the next release. 
For now, can you make a few GET request to, say, http://google.com and check if the response cookies populate?

**Comment by mringer** [comment]
OK, that works I see cookies. Looks like it's working correctly, I was just confused by the empty tab style.

**Comment by mringer** [comment]
Thanks for clearing that up for me!

**Comment by abhijitkane** [comment]
No problem. Thanks for pointing out the incorrect message.

**Comment by AdrianTP** [comment]
I am unsure whether I should file a new issue, but I am having this same problem. The thing is, though, that even when I should be receiving a cookie, I do not.

My configuration is the following:
Apple Mac OS X 10.9.5
Google Chrome Version 44.0.2403.125 (64-bit)
Postman 3.0.5
Postman Interceptor 0.2.11

I have tried uninstalling and reinstalling the extensions, to no avail. The cookies tab never populates. I do not have this issue with the "Postman - REST Client 0.8.4.16" Chrome Extension.

**Comment by abhijitkane** [comment]
@AdrianTP Do you see the cookies when you hit the same URL through the Chrome extension?

To check whether the interceptor is able to access the cookies, go to chrome:/extensions, search for the Interceptor, and click "background.html". In the console, type
`chrome.cookies.getAll({url:"YOUR-URL-HERE"}, function (cookies) {console.log(cookies)});`

**Comment by AdrianTP** [comment]
@abhijitkane I am able to get the cookies in the Chrome Extension version of Postman.

Running the given JavaScript line in the console does return an array of objects with the cookies that are currently set for that domain, so it looks like the Interceptor is working. Perhaps the miscommunication is between the Interceptor and the Postman 3.0 application. I don't think it's my Mac's firewall, because I turned that off and it still doesn't work.

**Comment by abhijitkane** [comment]
@AdrianTP Just making sure - Have you enabled the Interceptor in Postman? (Top-right corner of the first screenshot in this thread)

If the Interceptor is enabled, and you're able to make requests and see responses, the cookies should show up.

**Comment by AdrianTP** [comment]
@abhijitkane I swear I did that, but I must have been in a hurry and missed the click or something because it was indeed not enabled. Sorry for missing something so obvious. :(

It works now.
