### ISSUE TITLE
Clicking through saved responses breaks the UI.

### ISSUE THREAD

**Issue by mkpenrod05** [a85/POSTMan-Chrome-Extension#1247]
After saving a few responses for any given request, the UI breaks after trying to click through them. 

![savedresponseview](https://cloud.githubusercontent.com/assets/4269702/8683424/f8a24930-2a2f-11e5-9975-0b932e6e69ab.png)

Here is capture of the console errors being thrown:

![consoleerrors](https://cloud.githubusercontent.com/assets/4269702/8683437/0fbb72ae-2a30-11e5-8471-662c042ebb87.png)

**Comment by abhijitkane** [comment]
@mkpenrod05 Sorry for the delay on this. We've made a number of fixes in the response viewer. Can you confirm this fixed in the latest version - 3.2.8?
