### ISSUE TITLE
CMD+E doesnt work in ENVIRONMENTS

### ISSUE THREAD

**Issue by abn-dev-01** [a85/POSTMan-Chrome-Extension#12471]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

CMD+E doesnt work in ENVIRONMENTS

### Steps To Reproduce

1. open Environment 
2. choose one of it ( I have local, w1, w2 ) 
3. click cmd+E (macOS) 
4. nothing 
5. this works in Requests very well 

### Operating System

macOS

### Postman Version

10.20.0

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by DSchau** [comment]
Hello!

Thanks for opening this issue. Indeed, this seems to be a bug. I've added the appropriate labels to this ticket and we've added it to the backlog to fix in the future and will do our best to let you know when that happens.

Until then, while it's a bit non-ideal, right click and rename does work on an environment.

Thank you!

**Comment by nikhilweee** [comment]
Can confirm that this is a dealbreaker indeed. I'm on windows and <kbd>CTRL</kbd> + <kbd>E</kbd> doesn't work either.

**Comment by Harsh1796** [comment]
Hello @abn-dev-01 ! 

Thanks so much for reporting the bug! We've just pushed a fix in our latest app update `v10.22`. Could you please update your app and let us know if you're still experiencing the issue?
