### ISSUE TITLE
POSTMAN for VS Code: Ability to re-arrange the requests under the collection

### ISSUE THREAD

**Issue by SrikanthKuruva** [a85/POSTMan-Chrome-Extension#12475]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

The ability to re-arrange the requests under a collection will help me to run the collection in the desired sequence.

### Describe the solution you'd like

the ability to re-arrange the requests under a collection will help me to run the collection in sequence

### Describe alternatives you've considered

login to postman via browser and re-arrange the requests

**Comment by indraneel-postman** [comment]
Hi @SrikanthKuruva 
We have added support for re-arranging requests and folders in and across the collections via drag and drop. You can update the Postman Extension to v1.3.0 to make use of the same.
