### ISSUE TITLE
Fix typo in Pull Requests

### ISSUE THREAD

**Issue by Tithugues** [a85/POSTMan-Chrome-Extension#12476]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

There is a typo in Pull Request:
![image](https://github.com/postmanlabs/postman-app-support/assets/1165150/417a0b69-ad23-4528-b13c-722ed45450b3)

As you can see, it's written `Langauge` instead of `Language`.

### Steps To Reproduce

* Fork an existing collection
* Add a request
* Create a pull request

### Operating System

Linux

### Postman Version

10.20.0

### Postman Platform

Both

### User Account Type

Signed In User

**Comment by shikhar-codes** [comment]
Hey @Tithugues this is fixed now. Thanks for reporting.
