### ISSUE TITLE
Flows - Override response content type

### ISSUE THREAD

**Issue by andrejpavlovic** [a85/POSTMan-Chrome-Extension#12484]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

I'm trying to parse the response body of a `Send Request` block that returns valid JSON, but whose 'Content-Type` response header is unfortunately set to `text/javascript` instead of `application/json`. As a result, using `Select` block to get a value from the JSON object doesn't work.

### Describe the solution you'd like

There should be an easier way to override response content type - maybe in the `Send Request` block, so that subsequent block that depend on `Success` output, can handle the response as valid JSON.

### Describe alternatives you've considered

As a workaround, I've switched to using `Evaluate` block instead of `Select` block, where I can call `$jsonParse(body)` on the response body and then get the value as JSON.

Screenshot below for reference:
![2023-11-20_160304](https://github.com/postmanlabs/postman-app-support/assets/983644/e0b248a1-d072-4778-99d9-689130d33554)

### Additional context

I've opened up this issue in case anyone else gets stuck on trying to use requests in Flows that don't return correct JSON headers.

**Comment by saswatds** [comment]
Hi @andrejpavlovic the advanced setting to force parse the response is now available. In the auto mode it tries to parse based on the content-type header, but it can be overridden now. 
<img width="436" alt="SCR-20240515-ihhp" src="https://github.com/postmanlabs/postman-app-support/assets/8796447/c9458cce-1ee8-4ac8-bdb7-bef2250479a8">
