### ISSUE TITLE
When use postman tests POST Request gets Error: aborted,but tests GET Request is OK

### ISSUE THREAD

**Issue by lijie990822** [a85/POSTMan-Chrome-Extension#12483]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

In local we devlop this with windows PC and test local with jdk and tomcat。We deploy the project in Online Server with Linux OS and jdk environment，use tomcat to start this server.Test local server in windows no mantter GET or POST Request is OK,BUT the Online server In Linux is wired.GET method is OK ,the POST method is get Wrong message" Error: aborted" .
I tried change local code,but useless,but isnt the right way to change,and search this question find no right answer.W

### Steps To Reproduce

1. In local we devlop this with windows PC and test local with jdk and tomcat.

2. We deploy the project in Online Server with Linux OS and jdk environment，use tomcat to start this server.

3. Test local server in windows no mantter GET or POST Request is OK,

4. BUT and the Online server In Linux is wired.GET method is OK ,the POST method is get Wrong message" Error: aborted" .

5.  Error message:Error: aborted

### Operating System

windows linux

### Postman Version

10.1.2

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by sandeep-singh-pstmn** [comment]
@lijie990822 Thanks for reaching out can you please share the following details 

- Does the same request work with CURL? If yes, can you share the output?
- If possible, can you share the collection with us at [support@postman.com](mailto:support@postman.com) to debug and reproduce
- can you share the postman logs as well in [support@postman.com](mailto:support@postman.com)

**Comment by sandeep-singh-pstmn** [comment]
Closing the issue for now. Feel free to reopen it
we are tracking this https://github.com/postmanlabs/postman-app-support/issues/10933 here as well
