### ISSUE TITLE
MQTT environment variable doesn't work when refering to webscoket protocol

### ISSUE THREAD

**Issue by prshendra** [a85/POSTMan-Chrome-Extension#12481]
### Is there an existing issue for this?

- [x] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

When I use environment variable that refer to `ws://` or `wss://` in the MQTT "Enter URL" input field and hit "Connect" button, the connection status will keep "Connecting" indefinitely. However, when I don't use environment variables (i.e putting literal `ws://test.mosquitto.org:8080`), it can connect successfully.

Screenshot when using websocket env variables in URL field:
<img width="1005" alt="Screen Shot 2023-11-20 at 1 11 36 PM" src="https://github.com/postmanlabs/postman-app-support/assets/95399111/41225a3e-8ec4-4e0e-b44a-a35fd683e331">

Screenshot when NOT using env variables in URL field:
<img width="1010" alt="Screen Shot 2023-11-20 at 1 12 48 PM" src="https://github.com/postmanlabs/postman-app-support/assets/95399111/29418aa8-0093-4851-93d1-4c4222aa1272">

### Steps To Reproduce

1. Select `Environments` from left panel.
2. Create new environment. Name it whatever you like e.g. `MQTT`
3. Select the `MQTT` environment and create new variables for holding mqtt broker address e.g. `host`, set it to a websocket protocol e.g. `ws://test.mosquitto.org:8080`
4. Create new MQTT request
5. In the environment selector on top-right side, select the `MQTT` environment.
6. Use the `host` env variables created earlier in the "Enter URL" field. i.e. type `{{host}}`.
7. Click "Connect" button
8. In the connection status below, it will say "Connecting" indefinitely.

### Operating System

macOS

### Postman Version

10.20.0

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by prshendra** [comment]
For env variables that refer to `mqtt://` protocol this issue is not happening.

**Comment by jonathanhaviv** [comment]
Hi @prshendra thanks for flagging this! We're working on a fix and will let you know once it has been released.
