### ISSUE TITLE
Collection Runner 'Performance' tab is missing

### ISSUE THREAD

**Issue by semaxwell-clgx** [a85/POSTMan-Chrome-Extension#12489]
### Is there an existing issue for this?

- [x] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

My postman desktop app is missing the 'Performance' tab in the collection runner (as shown in this [blog post](https://blog.postman.com/postman-api-performance-testing/)).

This issue seems similar to https://github.com/postmanlabs/postman-app-support/issues/12151, however I am running the latest postman version of 10.18.2. Checking for updates reveals nothing newer to upgrade to. 

### Steps To Reproduce

1. Right click an existing collection with requests
2. Select 'Run Collection'
3. Observe the 'Performance' tab is missing. 

### Screenshots or Videos

<img width="523" alt="image" src="https://github.com/postmanlabs/postman-app-support/assets/82240958/1bb33b55-757d-4248-9f59-bd7628333d91">

### Operating System

macOS

### Postman Version

10.18.12

### Postman Platform

Postman App

### User Account Type

Signed In User

### Additional Context?

I am using an enterprise license. Is it possible this feature can be controlled via an admin setting and I should be reaching out to a plan administrator instead?

**Comment by ankurk85** [comment]
+1 
Performance tab missing Missing on Mac OS

Version 10.20.0
UI Version: 10.20.0-ui-231018-1251
Desktop Platform Version: 10.20.0 (10.20.0)

**Comment by victor-fialkin-paylocity** [comment]
probably the same issue: https://github.com/postmanlabs/postman-app-support/issues/12540

**Comment by postfrzero** [comment]
Hey folks -- Performance Testing is a recently released capability and is not available on the Enterprise plan yet, as noted on [the Pricing page](https://www.postman.com/pricing/) and in [the Learning Center](https://learning.postman.com/docs/collections/performance-testing/testing-api-performance/).

**Comment by pm7y** [comment]
A year later and it's still missing on the enterprise plan.
