### ISSUE TITLE
Markdown level 3 headers are not accessible in dark mode

### ISSUE THREAD

**Issue by pozil** [a85/POSTMan-Chrome-Extension#12486]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

When using a level 3 header in markdown, the displayed text is not accessible in dark mode: the text is dark grey on a black background. See attached screenshot.

### Steps To Reproduce

Type any text as a level 3 header such as `### Hello` and view the result in dark mode.

### Screenshots or Videos

![Screenshot 2023-11-22 at 13 04 09](https://github.com/postmanlabs/postman-app-support/assets/5071767/73c41c2d-b6d5-4c1b-ac4c-84dc45820fa3)

### Operating System

macOS 14.1.1 + Chrome latest version

### Postman Version

10.18.11-231017-1121

### Postman Platform

Postman Web

### User Account Type

Signed In User

**Comment by jellevandevelde** [comment]
@pozil Thanks for the feedback. We have updated the styling of our heading levels to ensure they're now accessible in dark mode also.
