### ISSUE TITLE
Choose File in Body section does not reload data if file is changed

### ISSUE THREAD

**Issue by vsabella** [a85/POSTMan-Chrome-Extension#1249]
Repro steps:
Create a request
Select "Binary" as the body
Choose the file
Submit the file
Edit the file
Submit the file again

Notice how the file data doesn't change.

If you try to choose the same file again, it will also not update. If you choose a different file, then choose the file once more, it updates.

Mac OS X Yosemite 10.10.4

**Comment by maxiwheat** [comment]
+1 on this one, I get it on Windows too. Very annoying.

**Comment by jmartigny** [comment]
Same here and I agree, this is very annoying

**Comment by a85** [comment]
I believe this has been fixed in the latest Postman version on Chrome and Mac.

**Comment by SamvelRaja** [comment]
@jmartigny  @maxiwheat @vsabella It has been fixed in our internal build will be available in the next release.

**Comment by SamvelRaja** [comment]
@jmartigny @maxiwheat @vsabella It is been fixed in our latest 4.7.2 version 😄
