### ISSUE TITLE
No mqtt option in new

### ISSUE THREAD

**Issue by MI-Class** [a85/POSTMan-Chrome-Extension#12495]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

No mqtt option in new
![1](https://github.com/postmanlabs/postman-app-support/assets/32660445/0afc16ff-278b-44b7-b2c3-5bb439b070d2)

### Steps To Reproduce

1.Open New Tab

### Operating System

macos

### Postman Version

10.20.3

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by appurva21** [comment]
Hey @MI-Class ! Thanks for writing in. 

I looked into the mentioned issue but can't reproduce it. The MQTT option is available on the latest App version (v10.20.3).

Can you help us with more details on how you ran into the issue? Was this previously working for you?

![image](https://github.com/postmanlabs/postman-app-support/assets/24985700/aca9c136-6242-4d0d-83ee-02328bc7c0f1)

**Comment by MI-Class** [comment]
![1](https://github.com/postmanlabs/postman-app-support/assets/32660445/8d61c65c-751e-4f72-a66f-dc6f377685a9)
in the past, I can create mqtt tags, which can be seen from the history, and now I can use the mqtt test by opening the history, but I cannot create a new one.
My computer is MacOS Ventura 13.6

**Comment by appurva21** [comment]
To help us debug:

1. Are you seeing any errors in the Console tab (_View > Developer > Show DevTools_) when clicking on the "New" button?

2. Can you share the logs from the desktop app? You can find the steps here: https://support.postman.com/hc/en-us/articles/360025298633-How-to-get-logs-from-the-Postman-Desktop-app

**Comment by timhall** [comment]
Hi @MI-Class are you able to see MQTT requests in collections? You can try to add an MQTT request to a collection with the "..." actions menu:

<img width="570" alt="Screenshot 2023-11-27 at 11 19 19 AM" src="https://github.com/postmanlabs/postman-app-support/assets/1211148/ab27ba9e-c2f1-4d1d-a31e-1b62a05963d3">

**Comment by MI-Class** [comment]
> To help us debug:
> 
> 1. Are you seeing any errors in the Console tab (_View > Developer > Show DevTools_) when clicking on the "New" button?
> 2. Can you share the logs from the desktop app? You can find the steps here: https://support.postman.com/hc/en-us/articles/360025298633-How-to-get-logs-from-the-Postman-Desktop-app

This is what I looked like when I first opened the developer tools.
![1](https://github.com/postmanlabs/postman-app-support/assets/32660445/8a67a11e-6685-4d0d-af55-519d6d8e303d)
After I cleaned up the error, I started clicking new.
![2](https://github.com/postmanlabs/postman-app-support/assets/32660445/2216b0d8-44cf-4fc3-ab0c-7ff5c98fb78b)
这是日志
[renderer-requester.log](https://github.com/postmanlabs/postman-app-support/files/13482229/renderer-requester.log)
[main.log](https://github.com/postmanlabs/postman-app-support/files/13482230/main.log)

**Comment by MI-Class** [comment]
> Hi @MI-Class are you able to see MQTT requests in collections? You can try to add an MQTT request to a collection with the "..." actions menu:
> 
> <img alt="Screenshot 2023-11-27 at 11 19 19 AM" width="570" src="https://private-user-images.githubusercontent.com/1211148/285938460-ab27ba9e-c2f1-4d1d-a31e-1b62a05963d3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExMzM4MTcsIm5iZiI6MTcwMTEzMzUxNywicGF0aCI6Ii8xMjExMTQ4LzI4NTkzODQ2MC1hYjI3YmE5ZS1jMmYxLTRkMWQtYTMxZS0xYjYyYTA1OTYzZDMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTEyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzExMjhUMDEwNTE3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDRjOWIwMjZhY2IxMDBlZTA4YzExNmViOTU2NjE0ODQwZDUxYjg4YTBiMDg1YjlhNjNkZWI1MDg5ZDFhNzg2MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.HoG_xJUhMOMl2rD0uukPHXoEkivkEWdVA0VdV51l1AQ">

Yes, I can see the previous mqtt request in the history, because I can still use it before, but there is no mqtt option in the new version update. I can only use the request before modification found in the history.

**Comment by appurva21** [comment]
@MI-Class We are not able to recreate this issue at our end on the latest Postman v11.8.0. Feel free to re-open this issue if you are still facing the problem.
