### ISSUE TITLE
Request not working in Postman but working in curl

### ISSUE THREAD

**Issue by this-Aditya** [a85/POSTMan-Chrome-Extension#12492]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Below Is the screenshot of the request from Curl: 

<img width="643" alt="curl_request" src="https://github.com/postmanlabs/postman-app-support/assets/98681758/d7797324-958a-43a1-874b-9702ec200a5b">
 
This post request is working fine in curl, but whenever I try to do these types of requests in Postman It gives me error.
Here is the screenshot for the postman request: 

<img width="635" alt="postman_request" src="https://github.com/postmanlabs/postman-app-support/assets/98681758/7b123615-29d6-4b39-a3b9-4ab3dce7a5af">

Headers used in this request are: 

<img width="628" alt="postman_headers" src="https://github.com/postmanlabs/postman-app-support/assets/98681758/d6bd7f81-1302-4547-877a-7b2c38c2afd9">

### Steps To Reproduce

1. Open the Postman app.
2. Use the Post Request as mentioned in the screenshots.
3. Create the same request using curl.
4. Working fine on curl and giving the response.
5. But not giving proper response in postman.
6. The request in the screenshots requires access_token in exchange for authorization_code. The authorization_code is not expired while making a postman request. 
7. But giving error: 
`{
    "error": "access_denied",
    "error_description": "Unauthorized"
}`  in postman

### Operating System

Windows 

### Postman Version

10.20.3

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by sandeep-singh-pstmn** [comment]
@this-Aditya, Thanks for reaching out to us, it seems like you are using form-data(multipart/form-data) to send the body, but In cURL, when using the -d flag, the data is sent as application/x-www-form-URL-encoded([link](https://curl.se/docs/manpage.html#-d))
Please ensure you are using that
one other thing: if you paste the curl in the URL bar, it will automatically convert it into Postman req. You can see this in the video as well. 

https://github.com/postmanlabs/postman-app-support/assets/85243040/912f7409-7a54-4c54-9eca-28237fe69bed

Closing the issue for now. Feel free to reopen.

**Comment by this-Aditya** [comment]
Many Thanks @sandeep-singh-pstmn it is working now.
