### ISSUE TITLE
<need option to add bearer token for all request of a collection items in single click>

### ISSUE THREAD

**Issue by karthicksakthi500** [a85/POSTMan-Chrome-Extension#12496]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

yes , adding bearer token to all, and change url to all 

### Describe the solution you'd like

need option to add bearer token for all request of a collection items in single click, i have a collection which is working on some site , and we receive evry request with same address(website name ) manually with first and next the api name , now problem is iwant to check in localhost  with every time need to add and change localhost in every request and bearer token for all everytime , i need option single click tpo add bearer token for all requests ,and to change all localhost instead of websire base url. it will be great if you considering on this, ineed  as it is the collection , 

### Describe alternatives you've considered

need option to add bearer token for all request of a collection items in single click, i have a collection which is working on some site , and we receive evry request with same address(website name ) manually with first and next the api name , now problem is iwant to check in localhost  with every time need to add and change localhost in every request and bearer token for all everytime , i need option single click tpo add bearer token for all requests ,and to change all localhost instead of websire base url. it will be great if you considering on this, ineed  as it is the collection ,

**Comment by giridharvc7** [comment]
You can set the Collection/Folder's Authorization as `Bearer` and all its requests can `Inherit from Parent` . 
<img width="1083" alt="image" src="https://github.com/postmanlabs/postman-app-support/assets/1040583/7e50a44f-91e7-4557-a879-5c35c7fbfc03">
