### ISSUE TITLE
No warning when forking into a public workspace

### ISSUE THREAD

**Issue by martynfrank** [a85/POSTMan-Chrome-Extension#12494]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

When forking a collection and linked environment files, the "Fork collection" screen may default select a public workspace. Without clicking the workspace, there is no warning on the screen that the forked content will become public.
![image](https://github.com/postmanlabs/postman-app-support/assets/4399105/146d5837-1b71-4324-992c-194937562f12)

I understand that if the dropdown is clicked, then an icon indicating it is public with an info tooltip is shown. However, if the default workspace is public, then users are unlikely to click the dropdown.

The lack of warning leads to users mistakenly forking collections into public workspaces and subsequently exposing sensitive information.

### Steps To Reproduce

1. Setup postman user with one public workspace (unsure of the rules as to which is selected by default on the Fork collection screen, but I have observed it being a public one, even when private ones exist)
2. Fork a collection as that user
3. View the lack of warning on the 'Fork collection' screen

### Screenshots or Videos

![image](https://github.com/postmanlabs/postman-app-support/assets/4399105/a2f00c20-d6db-469b-8d3a-04094326adf9)

### Operating System

Windows

### Postman Version

10.20.3-231120-0418

### Postman Platform

Postman Web

### User Account Type

Signed In User

**Comment by kartikjain26** [comment]
@martynfrank I agree with this. We'll look into this and come up with a fix/better UX in upcoming releases. Will keep you posted.

**Comment by kartikjain26** [comment]
@martynfrank Hey, this is now available on latest app/web-app.

**Comment by martynfrank** [comment]
Thank you. I appreciate your responsiveness. I had a play with it and liked the new info banner.

**Comment by mgeoffriau** [comment]
Can anyone share an example or documentation for the new banner? I see no difference in the UI in the Windows 10.24.24 app or the web app.
