### ISSUE TITLE
Postman MQTT Subscription Issue with Wildcard '#' in EMQX 3.5.1

### ISSUE THREAD

**Issue by fish-can** [a85/POSTMan-Chrome-Extension#12497]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

I'm encountering difficulties when attempting to use Postman for MQTT subscriptions with the wildcard '#' in EMQX version 3.5.1. 
The wildcard subscription doesn't seem to be functioning as expected.

### Steps To Reproduce

1. Open Postman:
  Launch Postman and navigate to the MQTT request.

2. Configure Request:
  Set up the request with the necessary details (server, port, etc.).

3. Specify Topic with Wildcard:
  Subscribe to a topic using the wildcard '#' in the topic string.

4. Attempt Subscription:
  Execute the request and observe the behavior.

### Screenshots or Videos

![image](https://github.com/postmanlabs/postman-app-support/assets/9313825/7c5707be-d8bb-4602-9a25-995075c23bb5)

### Operating System

macOS

### Postman Version

10.20.3

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by jonathanhaviv** [comment]
Hi @fish-can, thanks for reporting this. Can you provide more clarity on the EMQX version you're using? I couldn't find 3.5.1 on the [EMQX downloads page](https://www.emqx.io/downloads?os=macOS), but I just tried setting up a server using version 5.3.1 and could connect and subscribe.

Based on the error code in the QoS section, it looks like you're getting a `Not Authorized` error code. Can you upgrade your EMQX version and provide more information on your setup? It might be a permissions issue on the server side.

![image](https://github.com/postmanlabs/postman-app-support/assets/53003885/271b3f61-baec-43e5-ab2c-7b9b6147de73)

**Comment by fish-can** [comment]
My bad, my emqx version is 5.3.1, and run on OrbStack(1.1.0)

![OrbStack/Image](https://github.com/postmanlabs/postman-app-support/assets/9313825/8da26b23-15e5-4abc-ae03-a122efeeee10)

After enabling authentication, i can use postman to subscribe tpoic '#'.

![EMQX/Dashboard/Authentication](https://github.com/postmanlabs/postman-app-support/assets/9313825/f8df962f-e6a2-4fd9-ae60-8450b1af058c)

![Postman/MQTT](https://github.com/postmanlabs/postman-app-support/assets/9313825/c3891f4a-2246-4d5e-8e42-ee223d15d9c7)
