### ISSUE TITLE
Sync collections, environments, and settings with Google

### ISSUE THREAD

**Issue by stephens2424** [a85/POSTMan-Chrome-Extension#125]
Extensions can use Chrome Sync now. It would be great if collections, environments, and settings sync'd alongside my other Chrome stuff.

More info here: http://developer.chrome.com/extensions/storage.html

**Comment by anthonycmain** [comment]
That would be a good idea/feature. We are planning on setting up a separate
shared POSTMan account so we can share everything through that

On 28 December 2014 at 12:31, Tom Hall <notifications@github.com> wrote:

> It'd be great to be able to configure postman to use a specific JSON data
> file, e.g. one that resides within a git repo so that a team of devs use
> the same collections/environments/settings, etc.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/a85/POSTMan-Chrome-Extension/issues/125#issuecomment-68205905>
> .
>



-- 

ANTHONY MAIN

EMAIL

PHONE

Managing Director, Co-founder
anthony@thedistance.co.uk

01904 217171

THE DISTANCE

WEBSITE

TWITTER

The Old Sawmill, 52 Skeldergate
York, YO1 6DS
thedistance.co.uk <http://www.thedistance.co.uk/>@thedistancehq
<http://twitter.com/thedistancehq>

Company Reg No 6939899 | Registered Address: The Old Sawmill, 52
Skeldergate, York, YO1 6DS | Vat No. 974 0042 33

The information contained in this email and any attachments are intended
only for the named addressee and may contain privileged and confidential
information. If you are not the intended recipient you must not copy,
distribute or take any action and any dissemination is strictly prohibited.
If you have received this email in error please notify the sender
immediately. Although we believe this email and its attachments are virus
free no responsibility can be accepted for any damage caused by any virus
contained therein.

**Comment by rufer7** [comment]
+1

**Comment by naoisegolden** [comment]
+1

**Comment by joanrodriguez** [comment]
+1

**Comment by josephpconley** [comment]
+1

**Comment by nhuray** [comment]
+1

**Comment by tobiasb** [comment]
+1

**Comment by fdellabetta** [comment]
+1

**Comment by a85** [comment]
This feature is rolling out to all users. Please send us an email at help@getpostman.com if you want an invite! Thanks!

**Comment by scarlier** [comment]
+1

**Comment by anthonycmain** [comment]
THE DISTANCE - Year in Review

2015 has been an exciting year for The Distance. We have welcomed many new clients and there has been a major shift in our offering. Now all we do is Apps! 

To celebrate we have just launched the latest iteration of our website, which we'd love you to check out and send us any feedback.

New Website: https://thedistance.co.uk

Revised Company Values: https://thedistance.co.uk/company/company-news/core-company-values/

Why the Change? https://thedistance.co.uk/company/company-news/distances-ecommerce-marketing-division-now-allies/


GROWING THE TEAM

2016 is going to be a year for growth for our team, as we are planning to double the size of the team by this time next year. So if you know anyone looking for an exciting career in the App industry tell them to email jobs@thedistance.co.uk or keep an eye on the page below:

https://thedistance.co.uk/careers/


NEW CLIENTS

NHS - PRASE
Working with Bradford Teaching Hospital, The Distance created an iPad based feedback tool used in hospitals by volunteers to provide greater care for resident patients
https://thedistance.co.uk/portfolio/nhs-prase-app-development/

Camden Market
The Distance are continuing to develop interactive apps which allow the users to explore the market both remotely and while visiting; providing curated experiences through various style verticals.
https://thedistance.co.uk/portfolio/camden-market-app-development/

"The Distance have proven to be invaluable business partners. The Camden Market app was delivered to a high standard, at a fair price and within demanding timescales. Together, their development skill and friendly expert consultancy have been key factors in our ongoing relationship." - Christ @ Camden Market
 
Slimming World
A dietary support app, full of recipes and features to support a healthy lifestyle. Availble on iOS, Android and Kindle
https://thedistance.co.uk/portfolio/slimming-world-app-development/

SafeStyle UK
The Distance are working closely with SafeStyle to help streamline their sales processes, starting with a interactive presentation App for their sales reps.


FROM OUR BLOG

App Audits
With the releases of iOS 9 and Android 6 (Marshmellow) all App owners should be ensuring their Apps are compatible. Want to know how we can help?
https://thedistance.co.uk/mobile-apps/android/ios-android-app-audit/

Mobile Payments
Mobile devices now provide users with the convenience of leaving their bank cards at home. So how can you take advanced of this futurist tech?
https://thedistance.co.uk/mobile-apps/apple-pay-android-pay-mcommerce/

Indexing your App
Google now provides us with the opportunity to index the content within Apps - supporting the statistic that mobile searches now out number desktop! Find out how we can help you can get more Googles.
https://thedistance.co.uk/mobile-apps/google-index-app/


HAVE AN APPY CHRISTMAS!


This email was sent to reply@reply.github.com.
If you are no longer interested you can unsubscribe instantly:
http://emailer.webdynamix.biz/t/y-u-djllldt-jhkujiduhu-d/

**Comment by naoisegolden** [comment]
Mandatory registration into Postman isn't what I would have expected for this, especially with solid solutions like Chrome Sync or even Dropbox _et al_.

**Comment by shamasis** [comment]
The solutions with Dropbox and Chrome Sync isn't as robust as it is thought to be. And with them realtime sync performance blocks good user experience. For example, with the [changes](https://blogs.dropbox.com/developers/2015/11/dropbox-api-v2-launches-today/) and [deprecations](https://blogs.dropbox.com/developers/2015/04/deprecating-the-sync-and-datastore-apis/) dropbox rolled out, it would have further delayed this feature and discouraged us from working to provide this service for free personal use.

Also, outage of these services are not in our hand and basic collaboration that we are trying to provide to ease developer pain while API development is defeated by that.

If you are already registering with Dropbox and Chrome sync, what stops from using Postman registration. Also, it is 1-click with Google login support.

We built the sync service to solve pain points of developers and as we grow, bring API publishers and consumers meet at one point and create standards and seamless collaboration.
