### ISSUE TITLE
Cannot write documentation or generate tests with postbot when the method is a PATCH or PUT.

### ISSUE THREAD

**Issue by alipschutzsecuritize** [a85/POSTMan-Chrome-Extension#12503]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

when i try to generate documentation or test using postbot it fails.
It's only happening when the method is PUT or PATCH, and the response use to be status code 200, or the response is 1.
Not sure if there is a pattern or not.
But on POST / GET i don't have any issue.
<img width="1086" alt="Screenshot 2023-11-28 at 17 03 01" src="https://github.com/postmanlabs/postman-app-support/assets/144057184/18334087-0034-43db-ae37-8b5f07bff0d2">

### Steps To Reproduce

Open a new PATCH/PUT method.
Execute
Go to documentation, use postbot to generate the documentation, you will get this error.
Go to tests, use postbot to generate the tests, you will get this error.

Open a new POST/GET method.
Execute
Go to documentation, use postbot to generate the documentation, you will get the documentation, BTW, i love them!
Go to tests, use postbot to generate the tests, you will get the tests.

### Operating System

MAC

### Postman Version

10.20.3

### Postman Platform

Both

### User Account Type

Signed In User

**Comment by rkstamm** [comment]
Similar issue. "I need a response to perform this action." it says. "Send Request and Continue" button runs the API. API Runs. It repeats the "I need" response. Nothing happens.

**Comment by appsquadz-dilip** [comment]
In my case when i try to add a test it says added test, but nothing is added in the test tab

**Comment by codewithjk** [comment]
Similar issue in post and get method also.
![Uploading Screenshot 2024-03-20 at 6.41.47 PM.png…]()

**Comment by kylerRenneker** [comment]
@alipschutzsecuritize @rkstamm @appsquadz-dilip @codewithjk 

Hello folks! 

First off, thank you for using Postbot! Secondly, apologies for any issues you might have run into. 

This month we actually released a new Postman app versions, v11. As part of that release, the Postbot team has added some new functionality, addressed a handful of bugs, and made improvements in overall stability. 

 If possible, please update your app to the latest v11.x.x app version, and re-test the documentation and test script generation Postbot workflows. Both of those features should be fully supported for HTTP requests, regardless of method type. 
 
 Thanks!

**Comment by sudhanshu-mittal-bigship** [comment]
Hey @kylerRenneker , hope you are doing well!
I have an issue with the updated postman version. Can you please help me how can I fix it?

**Describe the Issue**
when i try to generate documentation or test using postbot it fails.
It's happening when the response use to be status code 200, or the response is 1.
Not sure if there is a pattern or not.
![Postbot Error not generate](https://github.com/postmanlabs/postman-app-support/assets/164166975/17579ec0-487e-4173-b33d-0f689c2d402c)
![Postbot Error Screenshot](https://github.com/postmanlabs/postman-app-support/assets/164166975/ba110f6a-4e42-4b01-bddc-9b844763e258)
![postbot response generate in chat6](https://github.com/postmanlabs/postman-app-support/assets/164166975/0346e269-db57-4389-a383-87b6216eb052)


**Steps To Reproduce**
Open a new POST/GET method.
Execute
Go to documentation, use postbot to generate the documentation, you will get the documentation, BTW, i love them!
Go to tests, use postbot to generate the tests, you will get the tests.

**Postman for Windows Version**
Postman v11.1.14

**UI version**
11.1.14-ui-240521-0853

**Architecture**
x64

**OS platform**
Windows 11 win32 10.0.22631

**Your plan:** 
Basic (Monthly) 

**User Account Type**
Signed In User
