### ISSUE TITLE
Import of collections not possible without login

### ISSUE THREAD

**Issue by 0verEngineer** [a85/POSTMan-Chrome-Extension#12505]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Why are Features like this removed? Stop pushing this shitty vendor lock stuff, it will destroy your company in the long run.

### Steps To Reproduce

1. Install Postman
2. Suffer from bad upper management decisions

### Operating System

All

### Postman Version

10.12.0

### Postman Platform

Postman App

### User Account Type

Signed Out User

**Comment by 0verEngineer** [comment]
Hahaha what a shitty company, i hope everyone will switch to FOSS alternatives.

**Comment by DannyDainton** [comment]
I appreciate that changes in behaviour to any product can cause frustration but creating an issue like this one, is not constructive. The language used and the tone is not needed. That's the reason why I closed it. 

I'm more than happy to continue a more professional constructive discussion, over on our [community forum](https://community.postman.com/) and hear the reasons why creating a free account is not an option for you - This isn't the correct medium for those discussions.
