### ISSUE TITLE
gRPC: Editing and sending messages rapidly results in the incorrect payload being sent

### ISSUE THREAD

**Issue by brunohash** [a85/POSTMan-Chrome-Extension#12504]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Hello,

I'm facing an issue with Postman GRPC and would like to know if anyone else is experiencing this.

My error happens when I send a request passing information to my application using postman grpc. Example, send a request with the following body to your application:

```
{
  "text": "test"
}
```

As soon as it loads, send a new one with random data, such as:

```
{
  "text": "asdasdasteste"
}
```

or

```
{
  "asdsadastext": "test"
}
```

Postman simply sends the first request data to the application:

```
{
  "text": "test"
}
```

### Steps To Reproduce

1. Open your postman.
2. Access an application where you send some data in Message.
3. Send the actual data and as soon as it loads send new random data

```
{
  "text": "test"
}
```

As soon as it loads, send a new one with random data, such as:

```
{
  "text": "asdasdasteste"
}
```

or

```
{
  "asdsadastext": "test"
}
```

Postman simply sends the first request data to the application:

```
{
  "text": "test"
}
```

### Operating System

Windows

### Postman Version

10.20.6

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by appurva21** [comment]
Hey @brunohashimotto, thanks for reporting the issue! 

I was able to replicate it on our end and will update once it's been fixed.

**Comment by ronork** [comment]
Hey @brunohash 
We have fixed this issue in the latest release of the Postman app (v10.22.2). Can you restart your app to verify if things are working fine for you?

**Comment by brunohash** [comment]
Hey, @Ronork. 

I performed the validation, and after the software update, I didn't identify the issue again.
