### ISSUE TITLE
OAuth 2 compatibility with Azure Active Directory

### ISSUE THREAD

**Issue by dylantack** [a85/POSTMan-Chrome-Extension#1250]
When using Azure AD as an identity provider, I get a puzzling error: "Duplicate headers received from server ERR_RESPONSE_HEADERS_MULTIPLE_LOCATION".

Note, this error message flashes quickly, so I had to make a video recording to capture the screenshot.

![postman_duplicate_headers](https://cloud.githubusercontent.com/assets/106996/8688018/3e2f2962-2a4b-11e5-8fa4-3b9e0c970b55.png)

Here's a HAR archive with the requests:  https://dl.dropboxusercontent.com/u/32009546/www.getpostman.com.har

**Comment by nwoolls** [comment]
Any workaround in the meantime?

**Edit:** [workaround](http://windowsitpro.com/azure/q-what-postman-and-how-do-i-use-it-azure)

**Comment by a85** [comment]
@nwoolls Thanks for posting the workaround. We'll see if we can solve this issue as part of the app itself.

**Comment by nwoolls** [comment]
@a85 that workaround is specific to using the PowerShell API for Azure to get the access token. While it does yield a usable access token it is not using an OAuth 2.0 flow.

What I found once we started trying to use the MS Graph API flow is that the auth and token URLs require a "resource" parameter identifying the resource you want to access. Using the following for the authorization URL in Postman was a successful workflow in the end:

https://login.microsoftonline.com/guid-here/oauth2/authorize?resource=https%3A%2F%2Fgraph.windows.net

In this case appending the resource parameter https://graph.windows.net (requesting access to the Graph API) to the URL obtained from the View Endpoints link in the Azure management portal.

**Comment by jongio** [comment]
I've got it to work with the following: http://blog.jongallant.com/2017/03/azure-active-directory-access-tokens-postman/

**Comment by giridharvc7** [comment]
The additional options for OAuth2 , "audience" and "resource" are now available on [Postman Web](https://www.postman.com/home) . Please give it a try, and let us know if you have any feedback or face any issues. This feature will be available in the desktop apps with the 8.3 release
![image](https://user-images.githubusercontent.com/1040583/115075125-3e688200-9f18-11eb-81be-6e9575029cfa.png)
