### ISSUE TITLE
Flow no longer working (doesn't start at all)

### ISSUE THREAD

**Issue by tuesdayMike** [a85/POSTMan-Chrome-Extension#12500]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

I hav several flows configured in Postman Desktop Client. When I hit the "Run" button, the button changes to run state, but no block is executed. No call is made, no log is written. Environment and all other components/requests are in place. The requests of the flow can be run manually from collections without any problems.

### Steps To Reproduce

1. open existing flow in flows pane
2. Hit "Run"
3. wait
4. at some point an "timeout" error is shown inside the first block of the flow. But that took very very long

### Operating System

Windows

### Postman Version

10.20.6 UI 10.20.6-ui-231127-0434

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by tuesdayMike** [comment]
Additional info:

when I run the same flow on my desktop PC (Linux with Postman V 10.19.17 UI 10.19.17-ui-231106-0450) it works as expected

**Comment by ghost** [comment]
Same. I updated to 10.20.6 and see the same behavior listed above.  My co-worker is on 10.19 and the same Flows work just fine for him

**Comment by saswatds** [comment]
Hi @tuesdayMike @tbuck02 we have pushed a hot-fix as `v10.20.7`. There was a bad merge that caused some files to lag behind. This update should have issue fixed.

**Comment by tuesdayMike** [comment]
Thanks, @saswatds that fixed the problem!
