### ISSUE TITLE
All scratch data locked out

### ISSUE THREAD

**Issue by caalip** [a85/POSTMan-Chrome-Extension#12515]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Well, during an outage at my job your program failed me.  From some reason postman turned into ransonware.  And locked out all my data until I signed up for an account.  I signed up for an account and my data is still missing.  This is really low class.  I hope whoever is responsible for this quit out of shame or was fired.  Stop changing things on postman.  Just stop changing things.  Before you changing something think should I change this, and then don't change it.  Get a life.

I wish there was some way to sue you, but I guess you can get away with this.  I hope whoever is in charge gets fired. 

### Steps To Reproduce

1) Log into trusty postman during an emergency.
2) Postman turns into ransomware and steals all your data.
3) Create some account.
4) You data is still stole, despite postman saying you could get it back.

### Operating System

Windows

### Postman Version

I don't know which version is the ransomware version

### Postman Platform

Postman App

### User Account Type

Signed Out User

### Additional Context?

Stop being a-holes.

**Comment by DannyDainton** [comment]
Hey @caalip 

Your data is fully accessible to you via the `⚙️ > Settings > Data` menu options, in either the Lightweight API Client or your Signed in account.

<img width="845" alt="image" src="https://github.com/postmanlabs/postman-app-support/assets/17089546/9d9c96d3-ed68-4064-8849-f68bf4bc34f4">

Were you not presented with this screen which explained this during the update of the app?

![Screenshot 2023-09-22 at 2 52 15 PM](https://github.com/postmanlabs/postman-app-support/assets/17089546/0b4f5a66-2e73-43d4-beb8-5f0fe76e9a4e)

**Comment by caalip** [comment]
I was able to recover my data.  Thank you

**Comment by caalip** [comment]
By the way, maybe you should make this process clearer.  Perhaps, provide instructions for recovering the data.  Or just don't import the data automatically.   Maybe the best case would just make that an option during the signup process.  Like "Would you like to import you old data?" during the sign-up.  Also, I think forcing everything to be like social media is annoying.  Maybe just let the person use the tool locally.  Sorry, I was upset though.

**Comment by caalip** [comment]
Although, in general sorry for being rude.
