### ISSUE TITLE
Save Requests from Interceptor in Order By Timestamp

### ISSUE THREAD

**Issue by aubreefields** [a85/POSTMan-Chrome-Extension#12511]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

When saving requests from Interceptor, the calls are ordered randomly and there is no way to save them in the order of their timestamp. The requests either have to be saved one by one or you have to inspect each URL and manually put the calls in the correct order. This is time consuming and frustrating.

### Describe the solution you'd like

In the pop-up that is displayed when you hit 'Save Requests', there should be an option to 'Organize requests by' 'Timestamps'.
![image](https://github.com/postmanlabs/postman-app-support/assets/98434905/74adaa23-4c17-4b2f-89cf-e80edea16582)

**Comment by Monesh-engagedly** [comment]
I need this feature too when we make a flow its very tough in the sequence

**Comment by RTodd92** [comment]
I also think this would be a nice feature to have. When using Interceptor to capture responses from a workflow where the order of steps is significant, not being able to log the responses chronologically (besides manually) is an unnecessary time/effort sink.

**Comment by brainpop-arielV** [comment]
This used to work fine in older postman versions but has changed for me at least on 10.21.0 

We must have this working again for our company workflow.

Also I'd recommend marking this as a bug and not a feature, since this used to work fine.

**Comment by VShingala** [comment]
@aubreefields @Monesh-engagedly @RTodd92 @brainpop-arielV Thanks for reporting the issue! We're looking into this and I'll update here once we have update on this.

**Comment by VShingala** [comment]
@aubreefields @Monesh-engagedly @RTodd92 @brainpop-arielV We've added support for ordering requests in ascending order of time when captured while creating a collection from the session by default (no specific option in the App is needed to do so). These collection requests will be in the same order as mentioned in the captured session. This functionality also extends to the selection of any option under "Organise request by" and the corresponding folder in the collection will have all requests saved in order of timestamp.

We're closing this issue, but please feel free to give us your feedback or any other problem you might have with this.

**Comment by Monesh-engagedly** [comment]
@VShingala Its capturing in the order

**Comment by miksav** [comment]
Resurfaced. Intercepted requests are again in messy order with v11.7.

**Comment by VShingala** [comment]
@miksav I tested this out with v11.7 and requests are saved to collection in correct order. Below is screenshot of side by side collection generated from session and session itself.

<img width="1624" alt="image" src="https://github.com/user-attachments/assets/81d2b80c-596c-4cd2-95f2-84a9a3c882da">

Would you be able to add more details on how to reproduce it?

**Comment by miksav** [comment]
The orders in session itself are in correct order, but when 'Save Request' they are saved in random order (on left hand side). I'm using Firefox, Windows 11 and now with interceptor version v11.8 (a bit confusing the plugin says v3.2). And thus exporting them also remains in random order.
OS Name	Microsoft Windows 11 Pro
Version	10.0.22631 Build 22631
FF: 129.0.1 (64-bit)
![image](https://github.com/user-attachments/assets/3dd09f8c-6659-4e0b-8959-362a0a26b8da)

**Comment by cantonalex** [comment]
Quite bizarre this isnt default functionality

**Comment by Diego-ABC** [comment]
Not sure if this was addressed. I'm trying to save interceptor requests right now. When I save debug session requests to an existing collection, I don't know what is deciding the order. But when creating a new collection in the "Save Requests" dialog, it does save them in timestamp order.

<img width="1787" height="652" alt="Image" src="https://github.com/user-attachments/assets/e6cf7e67-0480-45a0-8ea0-5089cbe37a61" />
