### ISSUE TITLE
Request body is empty when the send requests are saved through the Postman Inteceptor

### ISSUE THREAD

**Issue by Monesh-engagedly** [a85/POSTMan-Chrome-Extension#12513]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

We are recording the API request through the postman interceptor when we check it in the postman i can see the request body is not adding when we add it to the exisitng collection

### Steps To Reproduce

save the requests in the postman interceptor and add it to the exisiting collection request body not there

### Screenshots or Videos

<img width="790" alt="Screenshot 2023-12-01 at 12 03 01 PM" src="https://github.com/postmanlabs/postman-app-support/assets/151931745/4d5dc7be-69e2-451d-a26d-41f8ad053bf2">

### Operating System

macos

### Postman Version

l0.27

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by webholik** [comment]
@Monesh-engagedly We have released a fix for this. Can you try again and tell us if you're still facing this issue?

**Comment by webholik** [comment]
@Monesh-engagedly We're closing this issue. You can restart it if you still face this problem.
