### ISSUE TITLE
How to use an exist request in the pre-request script?

### ISSUE THREAD

**Issue by 42thcoder** [a85/POSTMan-Chrome-Extension#1251]
Let's see,  I got a request called `Create New User`, which is 'POST http://api-server.dev/users'.

I want to call `Create New User` in the pre-request script of another request called `Get User List`.

How can I do this? Can I write code like this ?

``` js
Postman.call('Create New User')
```

**Comment by abhijitkane** [comment]
No, you cannot modify the order of requests using Pre-request scripts. You'll need to order the requests manually in the collection, and then use the collection runner to run all requests in the collection.

We're working on a way to allow changing the request flow at runtime, but we don't have an ETA on this.
