### ISSUE TITLE
Shortcut "Jump to URL" (CMD + L) does not work

### ISSUE THREAD

**Issue by GennadyGS** [a85/POSTMan-Chrome-Extension#12521]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Unable to navigate to URL using the "Jump to URL" (CMD + L) shortcut

### Steps To Reproduce

Pressing Ctrl+L from any state produces no effect.
Expected behavior: it should navigate to request URL bar:
![image](https://github.com/postmanlabs/postman-app-support/assets/6974233/e69e038c-3855-4dfa-89ab-a10ffec2bdfe)

### Operating System

Windows

### Postman Version

10.20

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by sourabhrathourr** [comment]
Yes @GennadyGS I have been snatching my head from half an hour as why this was not working, seems like this is a bug lol

**Comment by Harsh1796** [comment]
Hello! @GennadyGS 

Thanks so much for reporting the bug! We've just pushed a fix in our latest app update `v10.22`. Could you please update your app and let us know if you're still experiencing the issue?

**Comment by GennadyGS** [comment]
@Harsh1796 
It works now. Thanks a lot!

**Comment by kevgilmore** [comment]
This doesn't work when installing the latest version from the website.

`Version 10.24.19` (Mac Apple Chip)

**Comment by GennadyGS** [comment]
Yes, it stopped working for me as well from some point

**Comment by KochVA** [comment]
Ctrl+L doesn't work in windows too.
![image](https://github.com/postmanlabs/postman-app-support/assets/78483056/0cc4cc15-2d63-4707-9b80-5893a62a4198)

**Comment by GennadyGS** [comment]
Recreated new issue #12798 since current issue is closed.
Please continue conversation there.
