### ISSUE TITLE
Scrolling down a response and clicking save on request shows presets menu

### ISSUE THREAD

**Issue by ratpik** [a85/POSTMan-Chrome-Extension#1252]
![screenshot from 2015-07-15 13 13 07](https://cloud.githubusercontent.com/assets/210420/8693385/6072e9ce-2af4-11e5-899d-9cd95141c4ed.png)

If I have scrolled down a bit and I try to click on the save/add to collection button next to a request, it actually invokes the `Presets` control which is in the background

**Comment by abhijitkane** [comment]
I'm not able to reproduce this. What OS / version of Postman are you using?

**Comment by ratpik** [comment]
Version 3.0.4 (packaged)
OS: linux (Ubuntu)
Architecture: x86-64
Native client architecture: x86-64

**Comment by abhijitkane** [comment]
We haven't been able to reproduce this on Ubuntu. Are you seeing this for every request or only specific ones?

**Comment by ratpik** [comment]
Every request.
