### ISSUE TITLE
Changes to collection variables do not reflect in the Postman Runner performance test runs

### ISSUE THREAD

**Issue by mandar-lad** [a85/POSTMan-Chrome-Extension#12523]
![POST_Pre-RequestScript_IncrementVar](https://github.com/postmanlabs/postman-app-support/assets/95657554/81958ff7-1d94-4979-9c27-5b8204cf2c49)
![GET_Use_IncrementedVar](https://github.com/postmanlabs/postman-app-support/assets/95657554/c8ce0eb3-fdd9-4206-92d0-5b72a61399fa)
![Console_IncrementedVar_IndividualRequets](https://github.com/postmanlabs/postman-app-support/assets/95657554/65bc5e2a-1ae9-417c-9f3e-8fe301e2165d)
![PerformanceTestConfigurations](https://github.com/postmanlabs/postman-app-support/assets/95657554/c45a4282-4c26-49b9-9a7a-367cea396779)

### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

I am using Postman Runner for running performance test. It is however unable to modify collection variables via code set in the Pre-request Script tab of one of the requests in my collection.

I have set below code in the Pre-request Script tab of a POST request -

`let accountId = pm.collectionVariables.get("accountId");`
`++accountId // increment by 1`
`pm.collectionVariables.set("accountId", accountId);`
`console.log("Current value of accountId: " + pm.collectionVariables.get("accountId"));`

When I run this POST Request outside of the Runner, the collection variable “accountId” seen above gets incremented and read via another GET request as well. But when running the collection as part of the performance test, for some reason the pre-script code does NOT seem to be getting executed. At least that’s what the execution results indicate since the accountId remains unchanged.

Am I missing something?

Thank you.

### Steps To Reproduce

1. Set a new collection variable with an initial value (numeric in my case) and a current value.
2. Use this collection variable in a new Request (GET or POST) within a new collection
3. Add code to increment this variable in the Pre-request Script tab, and print the new value to the console
4. Trigger a POST Request to your API using this variable in the request body. The code in Pre-request Script tab and Request gets executed successfully as expected (as observed from the console logs).
5. Trigger a GET Request to your API using the same variable as a query parameter. Request gets executed successfully as expected. 
6. Now create a performance test with the Runner using this collection containing the above two Requests (POST & GET).
7. Set the Virtual users (VU) to 1 and Test Duration of 1 min and run the performance test.
8. The variable being used in the POST Requests does not get incremented, tests fail.

### Screenshots or Videos

Org InfoSec tool is prohibiting me from uploading screenshots (have requested an exception)

### Operating System

MacOs

### Postman Version

10.19.17

### Postman Platform

Postman App

### User Account Type

Signed In User

### Additional Context?

Postman App:
Version 10.19.17
UI Version: 10.19.17-ui-231106-0450
Desktop Platform Version: 10.19.7 (10.19.7)

OS/Environment:
MacOs Ventura version 13.6

Please also refer to a related community post here:
https://community.postman.com/t/collection-runner-prevents-environment-variables-from-being-updated/19969

**Comment by mandar-lad** [comment]
By the way, I tried using a modified version of same JS code on the collection's Pre-request Script tab instead of that for the specific (POST) request, but to no avail. Code snippet below:

`if (request.method === 'POST') {`
`//same code block as shared above`
'} else {
`//other code`
}'

**Comment by nikithaachhini23** [comment]
@mandar-lad Thank you for reaching out to us. The pre-request script being used does get executed in the collection runner and the updated `accountId` will be used for the next request as defined in your collection during the run. However, variables aren't persisted between separate executions done by VUs.

Can you please describe your use-case and what you're trying to achieve? so that we can help you better

**Comment by mandar-lad** [comment]
I was hoping to implement concurrency + load test for my api. The idea is to auto increment accountId value so that requests fired by each of the two VUs gets a unique accountId value per request. I tried having similar set up using the data CSV file approach, but that does not help since it only supports first 100 VUs (for free plan), where each VU picks one row (or elements) from the CSV either ordered (1 row per VU at a time, but it limits me to have only 100 unique values), or random (which is something I do not want).

**Comment by nikithaachhini23** [comment]
Apologies for the delay in reverting back. If I understood the use-case correctly, you mean that for every request that is being hit a unique input need to be used (say for 50 requests - 50 unique account Ids will be used). I'm curious about:
1. If each request has an associated pre-request script using which account id is being updated, how did you validate that the request doesn't have updated account ID?
2. Does each request just needs account ID in an increment fashion or do you just intend to have a different ID used everytime which is why you're incrementing? Like a dynamic [variable](https://learning.postman.com/docs/writing-scripts/script-references/variables-list/) $guid always generates a v4 uuid would that work for your use-case?
3. using a data file, how many rows of data are you testing for currently?

**Comment by mandar-lad** [comment]
No worries. You got that right. Below are my answers to your questions:

1. As I mentioned earlier, by logging account ID values in console which indicated there were repetitions. Also confirmed by observing my application's log
3. Every request fired from postman should have a unqiue accountID (need not necessarily be in an incremental fashion). That was just my way of implementing uniqueness. 
4. With the data CSV approach, I suppose only 100 elements can be used as an ordered list.

**Comment by nikithaachhini23** [comment]
As we don't persist the variables between executions for performance testing, you're seeing repetitions. For your use-case, using data file is the right way to go where, for each request you can provide different value. I understand that there is usage limit based on plans, you might want to consider an upgrade.

**Comment by mandar-lad** [comment]
Not a positive experience. There are other much comprehensive and open source tools. I wanted to evaluate this one, good luck with getting upgrades.
