### ISSUE TITLE
Can't create a PR: UI reports that collection should be in a public workspace whereas it is

### ISSUE THREAD

**Issue by pozil** [a85/POSTMan-Chrome-Extension#12522]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

A contributor to one of my collections is trying to create a PR but they are stuck because of an error. They moved their fork in a public workspace and are trying to create a PR from it but they get an error saying that the forked collection must be in a public workspace.

You can tell from the attached screenshot that the workspace is indeed public by looking at the icon and the fact that anybody (including myself, the PR reviewer) can view the workspace without being part of it.

### Steps To Reproduce

Try to open a PR from this collection:
https://www.postman.com/kp-connect-74623/workspace/kp-connect/pull-request/create?source=28781865-11a7e1f1-00fa-4c86-bfbe-bd31a96eb595&destination=12721794-67cb9baa-e0da-4986-957e-88d8734647e2&entityType=collection&workspace=ccaa10fd-ac0e-46da-8cce-6105601f419c

### Screenshots or Videos

![Screenshot 2023-12-04 at 13 32 39](https://github.com/postmanlabs/postman-app-support/assets/5071767/81e1b2d3-cb32-4d88-9c91-2e4a8717d2b3)

### Operating System

macOS 14.1.1 + Chrome latest version

### Postman Version

10.18.11-231017-1121

### Postman Platform

Both

### User Account Type

Signed In User

**Comment by sony-mathew** [comment]
Let's take a look at this and get back to you @pozil !

**Comment by shikhar-codes** [comment]
Hey @pozil thanks for reporting.

The issue that you are seeing here is because the forked collection exists in the team that only you are part of. This will not block you in adding reviewers and creating the pull request. 

Please confirm if you are able to create the pull request.

We realise the messaging on banner can be better and we will fix it soon.

**Comment by pozil** [comment]
Thanks @shikhar-postman, this is now working as expected but I can swear that it didn't work at the time when the contributor asked for my help in creating the PR. Could it be that there's some latency when we promote a workspace's visibility to Public and that the check on the PR creation page is lagging a bit behind?

**Comment by shikhar-codes** [comment]
@pozil thanks for confirming that you are not blocked and able to create a pull request. 

Initially when your workspace was not public, you might have added reviewers who did not have access to your workspace. 
You can create a pull request without reviewers when your workspace is private / personal.

**Comment by pozil** [comment]
Ok, thanks for looking into this.
