### ISSUE TITLE
Forever Syncing

### ISSUE THREAD

**Issue by ratpik** [a85/POSTMan-Chrome-Extension#1253]
![foreversyncing](https://cloud.githubusercontent.com/assets/210420/8693512/4cab7c3e-2af5-11e5-842e-96c2195ddb1a.png)

Related to the issue of not being able to share a collection. I did see an error message related to the saved response size being too large which might be causing the error and endless loop.

**Comment by abhijitkane** [comment]
What version of Postman are you using?

**Comment by czardoz** [comment]
From the previous issue: 

```
Version 3.0.4 (packaged)
OS: linux (Ubuntu)
Architecture: x86-64
Native client architecture: x86-64
```

**Comment by abhijitkane** [comment]
@ratpik The Syncing... status should disappear after 100 seconds. Are you still seeing this?
