### ISSUE TITLE
Accept only single file when uploading multiple files with form-data.

### ISSUE THREAD

**Issue by Krish-Depani** [a85/POSTMan-Chrome-Extension#12532]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

I am sending POST request with 2 files with VS Code extension as form-data in Body section. when I saw in backend there was only one file. When I tried same with postman app it worked fine.

### Steps To Reproduce

1. Install the Postman VS Code extension.
2. Send a POST request with Body as form-data with 2 files to backend.

### Operating System

Windows

### Postman Version

0.15.0

### Postman Platform

Other

### User Account Type

Signed In User

**Comment by amaldinesh7** [comment]
Fixed in version `1.4.1`
