### ISSUE TITLE
No Collection Sidebar after Update

### ISSUE THREAD

**Issue by entc** [a85/POSTMan-Chrome-Extension#12549]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Since last Update for MacOSX Collection is not shown anymore

### Steps To Reproduce

After Update, the Sidebar with Collections has gone

Onle some kind of a history is shown

Unable to use Postman anymore

### Operating System

macOS

### Postman Version

10.19.7

### Postman Platform

Postman App

### User Account Type

Signed Out User

**Comment by DannyDainton** [comment]
Hey @entc 👋🏻

We announced back in May that we were sunsetting the Scratch Pad feature and introducing the Lightweight API Client.

https://blog.postman.com/announcing-new-lightweight-postman-api-client/

This should have been presented when you updated the version:
<img width="922" alt="Screenshot 2023-10-13 at 15 14 48" src="https://github.com/postmanlabs/postman-app-support/assets/17089546/054714b6-da92-4e23-853c-53ad786fc30c">

To continue using Collections, Environments and a whole load more features you will need to be signed in to an account. 

Your Scratch Pad data can be either Exported from the Lightweight API Client or once you have signed into an account, you can migrate all the data into a new Workspace. This can be done via the `⚙️ > Settings > Data` menu options.

<img width="847" alt="image" src="https://github.com/postmanlabs/postman-app-support/assets/17089546/c4dcdc8f-5f67-4854-9097-b23d3e67b0af">

The signed out version can be still be used if you want to build and make requests using HTTP, WebSocket, gRPC, MQTT, and GraphQL protocols. 

https://learning.postman.com/docs/getting-started/basics/using-api-client/
