### ISSUE TITLE
Content type header does not match body content type

### ISSUE THREAD

**Issue by GreenPatrick2** [a85/POSTMan-Chrome-Extension#12542]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Create an API request with a Body that is RAW/JSON.
The header should automatically set to application/json.
It does not. It remains plain/text.
If you toggle the Body type to text and back to json, the header gets fixed.

### Steps To Reproduce

1. Create a new request
2. Goto Body. Choose RAW & JSON. Add JSON content.
3. Goto Headers. Observe that Content type is set to text/plain (incorrect)
4. Go back to Body. Toggle from JSON to Text and back to JSON.
5. Goto Headers. Observe that Content type is set to application/json (correct)

### Screenshots or Videos

<img width="1010" alt="Screenshot 2023-12-13 at 10 39 20" src="https://github.com/postmanlabs/postman-app-support/assets/104022358/4b01b0c4-13de-40c7-929e-bb5a332b4107">
<img width="1017" alt="Screenshot 2023-12-13 at 10 39 30" src="https://github.com/postmanlabs/postman-app-support/assets/104022358/b75bd5c4-9343-4fbc-a8c3-96a9d6d751ae">

### Operating System

macOS

### Postman Version

10.21.2

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by vedkribhu** [comment]
@GreenPatrick2 thanks for reporting this. I am able to replicate the issue, looking into it.

**Comment by giridharvc7** [comment]
@GreenPatrick2 We've raised a hotfix, please restart your app for the changes to reflect. Let us know if this works as expected for you

**Comment by GreenPatrick2** [comment]
Thank-you for the quick turnaround. I can confirm the fix works.
