### ISSUE TITLE
Sync issue

### ISSUE THREAD

**Issue by moleksyuk** [a85/POSTMan-Chrome-Extension#1254]
Hi,

After a couple of times when my collection was broken again during sync:
1. Disable sync in Chrome App. 
2. Go to profile in https://www.getpostman.com/ and removed all collections there.
3. Enable sync in App again.

And it downloaded and duplicated collections!
![screenshot - 15-jul-2015 13_07_45](https://cloud.githubusercontent.com/assets/793472/8696205/18b91b72-2af3-11e5-88e4-20da4366dca5.png)

Version 3.0.4 (packaged)
OS: win
Architecture: x86-32
Native client architecture: x86-64

Guys one question, could you just add auto-backup of collection to local folder/dropbox/drive because sync is really awful.
I tired to restore/cleanup my collections after each "successful" sync.

Thanks.

**Comment by abhijitkane** [comment]
When you disable Sync, your data is not deleted from our servers. A number of users have accidentally disabled Sync only to want their old data back again.

If you re-enable Sync, all your collections will be re-downloaded from the server.

The collections at https://www.getpostman.com/profile/collections are the ones that you uploaded with the 'Upload and get link' functionality. Once you upload a collection it will always be available at the link unless you remove it from https://www.getpostman.com/profile/collections. 

Deleting the collection from your app will have no bearing on collections that you have uploaded, and removing the collections from https://www.getpostman.com/profile/collections not delete your collections from your sync account.

To check the data that's there in your Sync account, you can logout and log back in. If you feel that your data has not been synced properly, you can take a backup of your data - Settings > Data > Download.

**Comment by moleksyuk** [comment]
Hi @abhijitkane 

How it possible to reset all my collections and sync it from the scratch?

I understand that I can backup my collections manually but it would be great to have automatic backup for it as well. As sync is not stable it will help to restore collections from local backups.

**Comment by abhijitkane** [comment]
To check the data that's there in your Sync account, you can logout and log back in. If you feel that your data has not been synced properly, you can take a backup of your data - Settings > Data > Download before you sign out.

This will clear all your collections, and get your data from the server afresh.

**Comment by chimit** [comment]
Had the same problems few times. Syncing function is very buggy and makes me sad almost every day. Ability to use Dropbox for syncing Postman DB would be very useful.

**Comment by abhijitkane** [comment]
@Chimit What are the exact issues you're facing with Sync?

**Comment by chimit** [comment]
@abhijitkane, every day I see this very often for a long time (few minutes):

![2015-07-29 19 38 08](https://cloud.githubusercontent.com/assets/839349/8956531/726604d2-3629-11e5-8c60-1a6e3206fd0c.png)

Half the time it can't finish syncing (like endless loading), so I have to restart entire app. Sometimes it helps.

Also sometimes after syncing the order of the items changes and becomes random. It's a big headache to reorder all my queries.
Few times I got syncing conflicts without any reasons, because I use Postman from different computers at different times, and click "Sync" button every time when I finish working with it.

**Comment by MF24Dev** [comment]
@abhijitkane, the log-in/log-out magic did not do the trick.

I have the same issue as moleksyuk!
Unfortunately after log-in it downloads all the duplicate collections again, although there are no duplicates on https://www.getpostman.com/profile/collections. Everything seems to be fine there.

All our users get these duplicate collections when they sync.
There must be some server side mismatch.

How can i backup the clean server-side collection configuration, reset all clients and refresh them with the backed-up collections?

**Comment by abhijitkane** [comment]
@MF24Dev The collections shown at https://www.getpostman.com/profile/collections are the ones that you have uploaded (see 'Sharing a collection' at https://www.getpostman.com/docs/collections)

If you see the duplicated collections after you log in, that means they have been created on the server twice. You can send your username, and the names of the duplicate collections, (email to help@getpostman.com) and we'll delete them.

**Comment by moleksyuk** [comment]
Hi @MF24Dev 

This is how I did a clean up:
1. Synced my collection with duplicates.
2. Disable sync.
3. Fixed all duplicates.
4. Did to local backup.
5. Delete everthing from my account in website.
6. And only then enabled sync again.

And time to time do local backup manually.

**Comment by MF24Dev** [comment]
![postman_bug_empty_collection](https://cloud.githubusercontent.com/assets/13658025/9083706/bd4e1686-3b6c-11e5-9547-ec63b18dcc06.png)
@abhijitkane, thanks for the fast answer.
Unfortunately there is another issue comming along with the "duplicate collections", so that i can not send you the names.
After deleting and syncing the first time, empty collections appear along with the named duplicates.
These collections have no name, i can edit all of them, but that is a productivity killer.
I can not reproduce the issue, so i can not say where the problem can be located.

@moleksyuk, i will run your recommendation list and come back for the outcome.

**Comment by MF24Dev** [comment]
I deleted all duplicates and empty collections, made a backup and deleted all collections on https://www.getpostman.com/profile/collections from the account.
Then i enabled sync again and all the corrupted data appeared again.

So my question is now, where do these data come from, when all collections in the account are deleted?

**Comment by sobtiankit** [comment]
@MF24Dev the collections you deleted from the profile are the ones you have explicitly uploaded (regardless of Sync) by clicking on Share and choosing Upload to getpostman.com

Disabling Sync doesn't remove your data from our servers, as it can be a big data loss problem if you disable it accidentally. You can obviously feel free to reach out to us to delete all your synced data from our servers, we will also add this functionality to your account on the Website.

Right now, to solve your problem, keep Sync _enabled_ and delete the duplicate collections one by one. This way they will be deleted from the servers as well and not show up again.

Just to clarify, "All our users get these duplicate collections when they sync." Is your team using a single account to synchronize changes across the team? 

Also, you can send us an email at help@getpostman.com and we can resolve your issues.

**Comment by MF24Dev** [comment]
@sobtiankit, i will send you an email to deleted all data. Afterwards i can reload my backup, right?

Yes we have a shared account.

**Comment by sobtiankit** [comment]
@MF24Dev Yes please send us a support request, with your user id, once we confirm you will be able to reload your backup. To fastrack the process, you can also simply create a new user for yourself and import your collections there. If required, we can migrate your Jetpacks license, if any. 

We also don't recommend multiple users using the same account as it can lead to unpredictable behavior. For collaboration, we have a separate beta program running, details at: https://beta.getpostman.com/intro/
You will observe a significantly improved workflow for teams in the beta.

**Comment by cristian-mocanu-mob** [comment]
I also have duplicates after sync - up to 4 times.

I deleted all collections from remote, cleanup my local collections (delete the duplicates), but the issue appears again.

Because of this, I need to keep sync disabled.
