### ISSUE TITLE
Autosave beta function disappeared

### ISSUE THREAD

**Issue by JB-an** [a85/POSTMan-Chrome-Extension#12554]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

I don’t know since which version Postman’s autosave beta function disappeared.
I didn't find any announcement about closing or withdrawing the beta test.
I like the autosave function very much. I hope I can get this function back or downgrade to an older version.

### Steps To Reproduce

Just open Postman and disappeared.

### Screenshots or Videos

![螢幕擷取畫面 2023-12-20 084718](https://github.com/postmanlabs/postman-app-support/assets/148178237/848bac18-3ceb-494b-8142-c7b82560ced4)
![螢幕擷取畫面 2023-12-20 084735](https://github.com/postmanlabs/postman-app-support/assets/148178237/d6eef323-3eb4-482e-9dcf-1862d9b2df12)

### Operating System

Windows

### Postman Version

10.21.0

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by giridharvc7** [comment]
@JB-an This is odd, and shouldn't be happening. 
Just wanted to confirm if you are signed in to postman?

**Comment by JB-an** [comment]
> @JB-an This is odd, and shouldn't be happening. Just wanted to confirm if you are signed in to postman?

Thks for reponse.
Yes, I'm logged in.
Incidentally, I'm using my company's paid membership account.

**Comment by giridharvc7** [comment]
> Incidentally, I'm using my company's paid membership account.

You must be on the enterprise plan, we haven't released Autosave (which is a beta feature) to enterprise plans yet!

**Comment by JB-an** [comment]
> You must be on the enterprise plan, we haven't released Autosave (which is a beta feature) to enterprise plans yet!

I understand, but I have always used the enterprise version, but I have used the autosave function, which is strange.
I hope that the enterprise version can also experience the autosave function as soon as possible. Thank you for your reply.
