### ISSUE TITLE
Payload not sending to server

### ISSUE THREAD

**Issue by 0nahid** [a85/POSTMan-Chrome-Extension#12550]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

# Issue with Payload Sending in Postman

## Problem Description
I have encountered an issue several times while working with Postman where the payload is not being sent to the Express server properly, especially when using the raw format for JSON.

The problem typically arises when I close Postman and return to work later. Upon reopening, Postman seems unable to receive the JSON payload, requiring me to switch to raw text and then back to JSON format for it to work again. This issue appears to be affecting not only me but also other users.

## Possible Cause
I suspect that the problem may be related to state storage, as the issue consistently occurs when reopening Postman.

## Expected Behavior
Postman should reliably send the JSON payload without requiring the manual switch between raw text and JSON format.

This issue has been a recurring inconvenience, and I believe it would be beneficial to address and resolve it. I plan to submit this as an issue on Postman's GitHub repository for further investigation and potential resolution.

## Steps to Reproduce
1. Close Postman.
2. Reopen Postman.
3. Attempt to send a JSON payload in raw format to an Express server.

### Operating System

macOS

### Postman Version

10.21.0

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by Soumyajit7** [comment]
Recently I've install postman version 10.21.0. I've followed your instructions but could not faced any issues!!
I've attached video recording of my screen, please watch this, and please let me know.
https://github.com/postmanlabs/postman-app-support/assets/35652969/3bfe772e-9519-488f-8a79-be1eaef469c2

**Comment by vedkribhu** [comment]
Hi @0nahid, thanks for reporting this. This looks duplicate of: https://github.com/postmanlabs/postman-app-support/issues/12542. We have fixed the issue, can you check if restarting the app fixes this for you.
