### ISSUE TITLE
Feature Request - Clone an existing request

### ISSUE THREAD

**Issue by ratpik** [a85/POSTMan-Chrome-Extension#1255]
Just the request identifiers like headers, url, params, body content. A new tab can open up with the cloned version of the code.

Lots of times I just end up modifying an existing request saved to a collection and then hitting save which basically ends up erasing my original request.

**Comment by abhijitkane** [comment]
There's a 'Duplicate' option. You can hover over the request in the sidebar, open the actions menu, and click 'Duplicate'.

**Comment by ratpik** [comment]
Got it. Thanks!
