### ISSUE TITLE
access_token not fetched from OAuth 2.O response

### ISSUE THREAD

**Issue by khushlo** [a85/POSTMan-Chrome-Extension#12564]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

- With other version of postman (Version 9.31.27) this Authorization API works fine, even it is working well with other tools, but when we are trying to fetch access token with latest postman or major version 10.X.X, this shows below error for accessing token.

![image](https://github.com/postmanlabs/postman-app-support/assets/53406853/16811bd7-98e8-4ee9-9b55-1acdd1a78b1e)

in response body it gets empty however in older version it gets access token from body itself

### Steps To Reproduce

1. Open Postman and create a GET OAuth 2.O request
2. Enter credentials according to your OAuth sign In 
3. After successfully validation of credentials it supposed to return you an access token
4. Here Postman is unable to fetch token from response

### Screenshots or Videos

![image](https://github.com/postmanlabs/postman-app-support/assets/53406853/16811bd7-98e8-4ee9-9b55-1acdd1a78b1e)

### Operating System

Windows

### Postman Version

10.21.9

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by coditva** [comment]
Hey @khushlo, thanks for writing in. Can you check what is the response in the Postman Console? Can you see the token in the response body?
If the token is not present in the response body, there might be some difference in how the request is sent from Postman v9 and v10. We can compare them to figure out the difference.

**Comment by khushlo** [comment]
Hey @coditva, As I mentioned that in console it shows body is empty with v 10.x.x whereas in v 9.x.x it brings data in body.

**Comment by coditva** [comment]
@khushlo It seems that the token is not sent in the response by the server itself. Can you compare the difference between the requests sent in v9 and v10? Do take a closer look at the request headers and body.

**Comment by khushlo** [comment]
@coditva, we are facing this issue since few months, not only me, my team-mates, along with expert engineers and expert QA are also facing the same. We check everything nothing wrong with the server, and the request collection and environment are same for both of the postman versions V9 and V10.

**Comment by coditva** [comment]
@khushlo I would need a little more info to replicate this. Would be up for a small Zoom call to share screen and debug the issue? Here's my [Calendly link](https://calendly.com/utkarsh-maheshwari-postmanaut/debug-issue-with-postman) – feel free to book any slot that works for you.

cc @abhijeetborole

**Comment by coditva** [comment]
@khushlo Thanks for joining the call. Noting down our findings here:
- The `client_id` is no longer sent in the token request to make it compliant with the spec. See https://github.com/postmanlabs/postman-app-support/issues/8731
- If the server needs the `client_id`, it can still be specified in the auth configurations in the `Token Request` section.
<img width="748" alt="Screenshot 2024-01-04 at 3 16 49 PM" src="https://github.com/postmanlabs/postman-app-support/assets/8445768/eb49e95a-9ccc-4722-8827-785eee08d57f">

Adding the above solved the issue. Closing this ticket.
