### ISSUE TITLE
Option to default to two-pane view in VS Code plugin

### ISSUE THREAD

**Issue by Rich-Hopkins** [a85/POSTMan-Chrome-Extension#12560]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

When I use the Postman desktop app, it stays in the two-pane view that I prefer. In the VS Code plugin, each time I open a new request from a collection, I have to manually select the two-pane view. 

### Describe the solution you'd like

Can you have the VS Code plugin do one of the following?
1. Open one or two panes in the same state as was used most recently 
2. Use a setting to choose which view is the default

**Comment by Quenix** [comment]
Hello, mate

While this option isn't provided I did some workaround I will share with you in case you are interested. Basically you gotta edit extension minified code.

## Step 1:
Open your VS Code extensions folder.
- Windows %USERPROFILE%\.vscode\extensions.
- macOS ~/.vscode/extensions.
- Linux ~/.vscode/extensions.

## Step 2:
Locate and open your Postman DIST folder in VS Code

## Step 3:
Try searching for "Two Pane View" and it may take you directly to the code you want.

## Step 4:
Unminify the code, user whatever it pleases you. Then you might find this portion of code, on mine it is already modified to "horizontal", but in yours should be "vertical". Just swap, save and reload VS Code. All good now!
<img width="375" alt="image" src="https://github.com/postmanlabs/postman-app-support/assets/12365990/f3e5e324-6b07-43e0-bb5e-b57ead70cacd">


I hope that helps you, it was reaaaally bothering me.

**Comment by theWiseAman** [comment]
Nice this is what I was looking for. Thanks!! I think there should be a default settings option to configure the layout according to ones taste.

**Comment by Rich-Hopkins** [comment]
Given that I have switched to Bruno, I no longer need this.

https://www.youtube.com/watch?v=7bSMFpbcPiY

https://www.youtube.com/watch?v=eqf9kD2XPn8

**Comment by rasitayaz** [comment]
We should reopen this issue as it has not been implemented.

**Comment by jabatrox** [comment]
I agree on that
