### ISSUE TITLE
JSON answer Pretty tab

### ISSUE THREAD

**Issue by LuckyTil** [a85/POSTMan-Chrome-Extension#12561]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

JSON answer IS NOT formatted on Pretty tab on the FIRST query after launch Postman.

### Steps To Reproduce

1. Launch Postman
2. Previous session restored. Answer panel selected Body - Pretty tab.
3. Run query.
4. JSON answer IS NOT formatted on Pretty tab.
5. Run the same query one more time.
6. JSON answer formatted OK now.

Please fix step 4.

### Operating System

Windows

### Postman Version

10.21.9

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by vedkribhu** [comment]
@LuckyTil thanks for reporting this. We are able to replicate this and are actively working on fixing this.

**Comment by annasarte** [comment]
Hello! Any news on when this will be fixed? I am on Version 10.22.9
UI Version: 10.22.9-ui-240129-0641
Desktop Platform Version: 10.22.0 (10.22.0

**Comment by jellevandevelde** [comment]
Hi @annasarte! Our team has successfully addressed the issue, and it's set to be included in our upcoming release. I will post an update in this thread as soon as the update becomes available.

**Comment by rcoundon** [comment]
I just wanted to mention here as my issue is very similar but not identical. When I run a request that returns JSON with the Pretty view selected, the response isn't prettified. However, if I then click to Raw and back to Pretty, it is then formatted correctly.
Version 10.22.13
UI Version: 10.22.13-ui-240205-0449
Desktop Platform Version: 10.22.0 (10.22.0)

**Comment by aspiers** [comment]
> However, if I then click to Raw and back to Pretty, it is then formatted correctly.

Same here, and also for my colleague.

**Comment by samarthgulati** [comment]
Hello, we have the fix rolled out as part of v10.23.1 of the app. Kindly relaunch your app or refresh the webpage to ensure you get the latest version running. Let me know if you are still facing the issue.

**Comment by rcoundon** [comment]
Looks good now, thanks!

**Comment by LuckyTil** [comment]
Thanx!
