### ISSUE TITLE
File Uploading Issue

### ISSUE THREAD

**Issue by askarisayed1** [a85/POSTMan-Chrome-Extension#12574]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

So , I Have downloaded the extension of Postman on Visual Code, and it working fine , but when i tried to hit the api along with the file uploads it is giving error, that file not found. But when same api is hit through the postman application it is working.
![Screenshot from 2024-01-10 14-00-15](https://github.com/postmanlabs/postman-app-support/assets/133862423/e5d30114-1d7e-47d9-9e02-e6e0bb6d8a12)

### Steps To Reproduce

1. Open a Request.
2. Select Request Type (Post)
3. Enter the URL and Add the key and Field to it
4. Upload the File, and hit the submit button
5. In Response it will give error file not found.

### Operating System

Linux

### Postman Version

0.17.0

### Postman Platform

Other

### User Account Type

Signed In User

**Comment by sandeep-singh-pstmn** [comment]
@askarisayed1, thanks for reporting this. I can replicate the issue multiple files are not uploading in vscode. Will let you know on this thread once we have a fix for this.

**Comment by dev-yogesh** [comment]
## Encounterd similar issue in vs code extension of postman.

Hi @sandeep-singh-pstmn
 
I observed,
1) Only the first file object comes as part of req.files_
2) All other file objects comes as part of req.body with the value of empty string.
    
![image](https://github.com/postmanlabs/postman-app-support/assets/69033552/5aaf269c-22c6-4ba7-beab-489b6c983669)
