### ISSUE TITLE
System Theme is always light

### ISSUE THREAD

**Issue by moritztim** [a85/POSTMan-Chrome-Extension#12573]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Same issue as this:
https://github.com/shiftkey/desktop/issues/932
No matter what system theme I set, when I select `System Default` in `Themes`, it's always light.

### Steps To Reproduce

1. Set dark theme in system settings
2. `File`>`Settings`
3. `Themes`
4. `System Default`

### Screenshots or Videos

<details>
<summary>Light Mode</summary>

![light mode](https://github.com/postmanlabs/postman-app-support/assets/90388353/8691b09b-6b7e-42aa-92e2-7e4d9310d88e)

</details>

<details>
<summary>Dark Mode</summary>

![dark mode](https://github.com/postmanlabs/postman-app-support/assets/90388353/2461c973-9a3b-4392-b8e3-3d0cb61106e4)

</details>

### Operating System

Linux

### Postman Version

10.19.7

### Postman Platform

Postman App

### User Account Type

Signed Out User

### Additional Context?

Possible solution:
https://github.com/shiftkey/desktop/issues/932#issuecomment-1826914423

More info about my environment:
https://github.com/shiftkey/desktop/issues/932#issuecomment-1755280122

**Comment by chris-torruella** [comment]
@moritz-t-w hello! Looking at [this response](https://github.com/shiftkey/desktop/issues/932#issuecomment-1835736069) seems like this is a solved issue.
Anyway I invite you to try our new app themes as part of V11. Hope you enjoy them! Cheers

**Comment by moritz-t-w** [comment]
> @moritz-t-w hello! Looking at [this response](https://github.com/shiftkey/desktop/issues/932#issuecomment-1835736069) seems like this is a solved issue.
> 
> Anyway I invite you to try our new app themes as part of V11. Hope you enjoy them! Cheers

I posted this issue after the one on github desktop was resolved. Unless you updated the same library in the meantime, this is not necessarily fixed. I can't test it rn tho.

**Comment by moritztim** [comment]
> @moritz-t-w hello! Looking at [this response](https://github.com/shiftkey/desktop/issues/932#issuecomment-1835736069) seems like this is a solved issue.
> 
> Anyway I invite you to try our new app themes as part of V11. Hope you enjoy them! Cheers

I think you're confusing this for the issue with gitbutler.
