### ISSUE TITLE
Error while getting current execution location (pm.execution.location)

### ISSUE THREAD

**Issue by TeymurovFuad** [a85/POSTMan-Chrome-Extension#12589]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Hello

During running our collections from pipeline using newman I am facing an issue
I am trying to get a current execution location using pm.execution.location in pipeline but it will throw an error Cannot read properties of undefined (reading 'location')
Note: it works during a local execution

### Steps To Reproduce

Add console.log(pm.execution.location) to your pre/post request script
Trigger this request in pipeline

### Operating System

Windows

### Postman Version

10

### Postman Platform

Other

### User Account Type

Signed In User

**Comment by postfrzero** [comment]
Support for `pm.execution.location` was added in `newman@6.1.0`. Could you check which version of `newman` you're using in your CI and when running locally?

**Comment by TeymurovFuad** [comment]
I appreciate your response. I apologize for my oversight; I relied on [this](https://github.com/postmanlabs/postman-app-support/issues/6926#issuecomment-1862350688) ticket instead of the documentation, so I did not find information on the necessary version for pm.execution.location. Thank you for pointing it out. I have upgraded to version 6.1, and the functionality is now working as intended.

**Comment by sgws-davidson** [comment]
I have encountered this same issue when running pm.execution.location in a pre-request-script where the request is launched from Visual Studio Code using the latest Postman extension.  

Works perfectly from Postman on desktop, but fails if run from VSCode Postman extensions.

**Comment by TeymurovFuad** [comment]
> I have encountered this same issue when running pm.execution.location in a pre-request-script where the request is launched from Visual Studio Code using the latest Postman extension.
> 
> Works perfectly from Postman on desktop, but fails if run from VSCode Postman extensions.

@sgws-davidson 

İ had the same issue on VS Code. We had a call with postman team and they told (if I am not mistaken) this feature does not work on VS Code for now.
