### ISSUE TITLE
Newman error "stream.js:94, Error: EISDIR, read at Error (native)"

### ISSUE THREAD

**Issue by spiroskgr** [a85/POSTMan-Chrome-Extension#1258]
I downloaded Newman in order to be able to download files using the collection runner. However, after trying to run a collection I always receive the following error:

Iteration 1 of 1
stream.js:94
throw er; // Unhandled stream error in pipe.
^
Error: EISDIR, read
at Error (native)
spyros@spyros-SZ77:~/npm-global/lib/node_modules/newman/bin$

Can you help me on how to proceed? I have not managed to solve it for the last two days.

**Comment by abhijitkane** [comment]
Can you refile this in the Newman issue tracker - https://github.com/postmanlabs/newman/issues?
