### ISSUE TITLE
Secret Variable Exposed in Headers

### ISSUE THREAD

**Issue by ScottAnk** [a85/POSTMan-Chrome-Extension#12580]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

When I use a secret variable in Bearer Token authentication it's exposed as plain text in the Headers tab

### Steps To Reproduce

1. Create environment with a secret variable (activate this environment)
2. Create a collection set to use Bearer Token authorization method (set the token value to the secret variable from step 1)
3. Create a GET request in the collection from step 2
4. View request's Headers tab, the bearer token is visible as plain text
![Screenshot 2024-01-11 170722](https://github.com/postmanlabs/postman-app-support/assets/26013496/3d4b53e7-38c4-457c-9f74-cc808ed53312)
![Screenshot 2024-01-11 170732](https://github.com/postmanlabs/postman-app-support/assets/26013496/6416ae7d-99f6-405b-ba9a-670f3c004ec9)
![Screenshot 2024-01-11 170746](https://github.com/postmanlabs/postman-app-support/assets/26013496/4fd2e6df-777c-49a4-a853-8e1221756ecf)

### Operating System

Windows

### Postman Version

10.21.9

### Postman Platform

Postman App

### User Account Type

Signed In User

### Additional Context?

This seems to apply to all authorization methods I've tried. I'm not part of any shared workspace, so I'm de-facto the highest authority in my app.

**Comment by giridharvc7** [comment]
This is now fixed in the latest version of the app. Please update the app to see these changes. 
Auth information is now hidden in the header and can be toggled to view in plain text. 

https://github.com/postmanlabs/postman-app-support/assets/1040583/6ddb2fd4-a20a-4a50-8170-775340ba0bdd
