### ISSUE TITLE
Graphql schema not loading when using global variable in request authorization

### ISSUE THREAD

**Issue by smestvirishvili** [a85/POSTMan-Chrome-Extension#12599]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

In GraphQL requests when "GraphQL introspection" is enabled, schema only loads when manually inserting bearer token value in authorization method. If global variable is used, then schema loading fails with internal server error. 

### Steps To Reproduce

1. Open GraphQL request
2. In authorization tab insert variable that contains bearer token value
3. Try to load the schema using GraphQL introspection

### Screenshots or Videos

**1. {{lims_token}} global variable contains valid bearer token values**
![image](https://github.com/postmanlabs/postman-app-support/assets/89538577/685ed618-1bc9-4f47-9107-70feef6f8c72)

**2. {{lims_token}} global variable is inserted into graphql request authorization value**
![image](https://github.com/postmanlabs/postman-app-support/assets/89538577/656f31c5-435e-46bf-844c-f06af36c06fe)

**3. Schema fails to load, even though the query works fine**
![image](https://github.com/postmanlabs/postman-app-support/assets/89538577/078dceb7-16e8-4153-85f8-4dab65686881)

### Operating System

Windows

### Postman Version

10.22.6

### Postman Platform

Postman App

### User Account Type

Signed In User

### Additional Context?

Graphql schema loading works only if bearer token value is inserted in authorization field directly.

**Comment by timhall** [comment]
Hi @smestvirishvili thanks for raising the issue and for including so much detail! I'll see what I can find and I'll update this issue when it is resolved.

**Comment by ronork** [comment]
Hey @smestvirishvili 
We have fixed this issue in the latest release of the Postman app (v10.23.1). Can you restart your app to verify if things are working fine for you?

**Comment by smestvirishvili** [comment]
Hello @ronork 
I checked and it works now. Thank you!
