### ISSUE TITLE
Unable to import some collection into Postman tool

### ISSUE THREAD

**Issue by nudasilva** [a85/POSTMan-Chrome-Extension#12595]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

When the collection is a big one, I cannot import it into Postman tool.

It occurs since this afternoon.

### Steps To Reproduce

1. Click on ment / file / import
2. Click on files 'link' link
3. Select a collection in local
=> Importing in progress
=> Import failed

### Screenshots or Videos

![image](https://github.com/postmanlabs/postman-app-support/assets/97691378/8dbe1c79-829f-4cc6-833f-9ff1eefcda6f)

### Operating System

Windows

### Postman Version

10.22.6

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by hbarsquared** [comment]
I am also affected by this. It seems to be related to the size of the file (if I take our large collection and manually delete sections, I can get it to import). This must be a recent change, we use this collection frequently and only now just had issues.

I can also confirm that prior versions of the collection which are known to import fine in previous Postman versions can no longer import. Has there been a recent change to the collection import code?

Edit: Confirmed that I can export a collection already in the workspace, but when I try to import in a new workspace the import fails. I was getting some weird non-responsiveness on the Export command but I can't reproduce after a restart.

**Comment by dmytrokovalevskyi** [comment]
+1

**Comment by ragi-prakash** [comment]
Yes same issues happening. Cant import files and not much information provided. Just says Import Failed. It happens just today. The same collection file i imported yesterday but not possible today.

**Comment by romacvccorp** [comment]
Same issue here... Trying to import a 3,0MB json file collection

**Comment by jamespotz** [comment]
+1

**Comment by VShingala** [comment]
@nudasilva @hbarsquared @dmytrokovalevskyi @ragi-prakash @romacvccorp @jamespotz We've fixed this issue! Could you try again and let us know if it's fixed for you as well.

**Comment by romacvccorp** [comment]
@VShingala Worked fine for me now.

Thank you!

**Comment by hemanthmhhssie** [comment]
Working now
