### ISSUE TITLE
Variable values are not synced from one company account to another

### ISSUE THREAD

**Issue by MelindaSZStoreFeeder** [a85/POSTMan-Chrome-Extension#12590]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

We are in a company and using shared workspaces of the same postman instance.
Me and my boss are using it simultaniously.
When I set an environment variable and save, the other account doesn't see the values populated, only the name of the variable. 

### Steps To Reproduce

1- Have 2 accounts over a shared workspace
2- Create an env. variable with name and value from account 1
3- Check the value of variable from account 2
-----
BUG- there is no variable value populated 

### Operating System

Windows

### Postman Version

10.0.22

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by DannyDainton** [comment]
Hey @MelindaSZStoreFeeder 

In order for your teammates to see the values that you have set, these need to be in the `Initial Value` which is synced. If you have these only in the `Current Value`, only you will see them.

**Comment by MelindaSZStoreFeeder** [comment]
@DannyDainton Thank you very much :) and sorry for the user error<3

**Comment by DannyDainton** [comment]
Anytime - Always here to help! 🏆
