### ISSUE TITLE
Hovering over a tab with mouse to close it shows edit "pencil" icon, but it should show close "x" icon

### ISSUE THREAD

**Issue by invalidred** [a85/POSTMan-Chrome-Extension#1259]
version: Version 3.0.4 (packaged)

To avoid UI confusion:
Hovering over a tab with mouse to close it shows edit "pencil" icon, but it should show close "x" icon.

![image](https://cloud.githubusercontent.com/assets/5270458/8703330/72b8d990-2aea-11e5-9834-faed09527636.png)

**Comment by christatedavies** [comment]
I believe thats to show that you have unsaved changes...

**Comment by invalidred** [comment]
That makes sense, thank you sir.
