### ISSUE TITLE
Request: Save on Send

### ISSUE THREAD

**Issue by christatedavies** [a85/POSTMan-Chrome-Extension#1260]
It'd be nice if there was an option to save the request upon sending it. Possibly a collection/environment setting rather than another button.

Not a biggy, but just would be useful IMO

**Comment by bandtank** [comment]
+1 This can be very annoying.

**Comment by a85** [comment]
We are working on certain changes to the collection + history combo that should eliminate the need for a feature specifically for this. Will update the thread in the future.
