### ISSUE TITLE
Interceptor not found, despite being installed

### ISSUE THREAD

**Issue by toby-griffiths** [a85/POSTMan-Chrome-Extension#1261]
When I view the 'Cookies' tab in the response section it tells me I need to install Interceptor, however when I click the link to the Chrome store, it is telling me it already has it installed.

To confirm… both Postman and the Chrome store browser are operating within the same Chrome user session (can tell from Xdebug cookie settings used).

Any help getting this to work would be appreciated :o)

**Comment by abhijitkane** [comment]
You also need to enable the Interceptor in Postman - icon on the top right (to the left of your username)
Note - If you are not receiving any cookies in the response, the 'Install Interceptor' message is shown. We will fix this part of the UI soon.

**Comment by a85** [comment]
@abhijitkane Interceptor can communicate to Postman using chrome messaging. After the Interceptor is installed, it did send a message back to Postman.

**Comment by abhijitkane** [comment]
If the Interceptor is enabled, but the response doesn't return any cookies, the response cookies tab shows the "Install Interceptor" message. This has to be fixed.

**Comment by a85** [comment]
Ok. Adding this as a bug.

**Comment by abhijitkane** [comment]
Will push a fix in the next release
