### ISSUE TITLE
MQTT Response

### ISSUE THREAD

**Issue by james-prosys** [a85/POSTMan-Chrome-Extension#12612]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

On MQTT Responses the format dropdown, that lists Text, JSON, Binary does not change the display from Text to Hexadecimal.

### Steps To Reproduce

When sending a message you can choose between Text, JSON, Base64, Hexadecimal.
In the response, when binary is received, this is only shown as text as is unreadable.

### Screenshots or Videos

![Capture](https://github.com/postmanlabs/postman-app-support/assets/84966607/3bfcffb0-ec97-44ca-8502-2d0e16612480)

### Operating System

Windows

### Postman Version

10.22.9

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by jonathanhaviv** [comment]
Hi @james-prosys, thanks for reporting this to us. We'll be looking into the issue and let you know if we need additional information or when we have a solution.

**Comment by jonathanhaviv** [comment]
Hi @james-prosys would you be able to share a bit more about the message you are trying to send/receive? What are you expecting to receive or what is the encoding being used? I'm having a bit of trouble trying to reproduce this.

**Comment by jonathanhaviv** [comment]
Hi @james-prosys I wanted to follow up and let you know that we have released a possible fix for this issue. I'm going to close this for now, but if you're still facing this issue on the latest version of Postman please let us know!
