### ISSUE TITLE
Package Library

### ISSUE THREAD

**Issue by DSchau** [a85/POSTMan-Chrome-Extension#12622]
## Description

Great description goes here

## Related issues

Fixes  #4193 Fixes #675

**Comment by romanmeister** [comment]
@DSchau 
Sorry for asking, i could not find anything in the docs, and just stumbled across this issue again. 
How does it fix #4193? How can we access e.g. other requests in the same collection? 

I could not access collection, or other collection requests from within a pre-request script. 

Thanks!
