### ISSUE TITLE
Postman API: GET /environments/ endpoint stopped working

### ISSUE THREAD

**Issue by maticardenas** [a85/POSTMan-Chrome-Extension#12621]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

When performing a call to `GET /environments/` endpoint, including a workspace ID as parameter, I'm getting following response:

```
{
    "error": {
        "name": "syncError",
        "message": "Input parameters are not valid."
    }
}
```

This used to be working fine passing the same workspace ID and with the same token, has something changed about the endpoint or could this please be checked? This is used to properly sync our public collections.

### Steps To Reproduce

1. Perform a `GET` requests to `/environments` endpoint, including `workspace` query parameter
2. Response is `400 - Bad Request`

```
{
    "error": {
        "name": "syncError",
        "message": "Input parameters are not valid."
    }
}
```

### Screenshots or Videos

![image](https://github.com/postmanlabs/postman-app-support/assets/12075970/5cf1a5b7-3a8c-4030-8cba-705fced774cc)

### Operating System

macOS

### Postman Version

10.22.9

### Postman Platform

Other

### User Account Type

Signed In User

**Comment by maticardenas** [comment]
Update: Trying again after a couple of hours it seems to be fixed.

**Comment by Liamhhhhh** [comment]
This was a bug I had encountered before, but fortunately, I also have another interface tool [Apidog ](https://apidog.com/)in use, which is being replaced by two.
