### ISSUE TITLE
post a multipart form-data file get No Content-Type header found!

### ISSUE THREAD

**Issue by hossam4444** [a85/POSTMan-Chrome-Extension#12639]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

post a multipart form-data file with no explicit headers I get No Content-Type header found while the auto-generated headers contain Content-Type multipart/form-data; boundary=<calculated when request is sent>
as follow 
![image](https://github.com/postmanlabs/postman-app-support/assets/57760803/f74d32bf-bf87-4530-b710-50ab0d52bbcd)

### Steps To Reproduce

1. open a new request tap
2. go to the body tap 
3. choose form-data
4. Choose a field file instead of text and choose a .json file
5. don't make any explicit headers 
6. send

### Screenshots or Videos

![image](https://github.com/postmanlabs/postman-app-support/assets/57760803/6ad07cf5-e135-433f-b7b7-c55d414c8fc1)

### Operating System

Linux

### Postman Version

0.18.0

### Postman Platform

Other

### User Account Type

Signed Out User

### Just More details 
- postman platform: VS Code extension.
- More details about the OS: Linux remote machine hosted at AWS EC2 Service.

**Comment by vedkribhu** [comment]
@hossam4444 I am able to see the content-type header when I am trying this flow. Attaching my screen recording. I am suspecting the issue might be in your server code. 

https://github.com/postmanlabs/postman-app-support/assets/37595282/d4a1699f-8d5b-4746-b160-d665d2cf4007
