### ISSUE TITLE
Request: Close all tabs

### ISSUE THREAD

**Issue by nturnley** [a85/POSTMan-Chrome-Extension#1263]
I find the tabs feature completely useless after I have made 20 or so requests and to get it back to a useful state I have to individually close each tab. it would be great to have a close all option.

**Comment by danielamorais** [comment]
I agree 
It's really boring having to close each tab at a time and still have to confirm

**Comment by paolobiavati** [comment]
I agree, please develop this feature.
It could be also useful drag and drop the tabs to change the order.

**Comment by dagronnell** [comment]
Agree.

If only keyboard shortcut worked for confirming the close dialog...

**Comment by aberke** [comment]
Agreed!

**Comment by getvictor** [comment]
Workaround:
1. Open a new Postman window.
2. Close the current one.

**Comment by platramos** [comment]
+1 please add this feature add it would make development on my client engagement much easier

**Comment by schaefml** [comment]
Agree

**Comment by A570343** [comment]
Agreed

**Comment by veeseekay** [comment]
+1 for feature addition

**Comment by tgschulte** [comment]
+1 for feature addition

**Comment by m4ver1k** [comment]
+1 looking forward for this feature.

**Comment by elado** [comment]
:+1:

**Comment by osarigul** [comment]
Please also add 'Close other tabs' option

**Comment by hlubovac** [comment]
+1
and close only tab (last one left) manually as well :)

**Comment by Abhi0725** [comment]
+1 'Close other tabs' option just like SublimeText

**Comment by facundoolano** [comment]
+1

**Comment by LucasES** [comment]
+1

**Comment by javabudd** [comment]
+1

**Comment by jcampbellco** [comment]
+1

**Comment by sidd081-zz** [comment]
+1

**Comment by mtuulu** [comment]
+1

**Comment by swapnildaga17** [comment]
+1 
Close all tabs , Close other tabs would be great

**Comment by aditikul** [comment]
We have added shortcuts so it's less painful to close the save modal - enter to save, esc to dismiss and space for "Don't Save." Hope these shortcuts are working for you. 

A close all tabs + close other tabs option is also on my list but can't give an ETA as of yet. Will update this ticket once it's out in the Mac app and Chrome app. Thanks for pointing this out.

**Comment by kirugan** [comment]
We need this feature very much, can`t wait for it arrival

**Comment by mabuzagu** [comment]
+1

**Comment by m-orsh** [comment]
+1

**Comment by fadighattas100** [comment]
+1

**Comment by a85** [comment]
Everyone. Coming up in 4.9. Closing this for now.

**Comment by vegetableman** [comment]
`Close all tabs` has been added to the latest update of `4.9` ^_^. Check out. 

![tabs](https://cloud.githubusercontent.com/assets/1330851/20857292/cca64e96-b94c-11e6-9502-e27bf9d27a4e.gif)

**Comment by cacti77** [comment]
Err - how do you invoke 'Close all tabs'? The video isn't very clear. I'm using Postman 4.9.2 on Windows 7 (win / x86-32, Chrome 55.0.2883.87). Or has this feature not rolled out to Chrome yet?

**Comment by ferguspl** [comment]
Same issue as above. When will this be available in Chrome?

**Comment by sdnts** [comment]
Guys, the Chrome platform does not allow us to have contextual right-click menus (only generic menus), so unfortunately, there isn't much we can do about this as of now. I'd recommend switching to the native apps, where we have more control.

**Comment by Emmachen** [comment]
Looking forward to see this function rolled out to chrome, I'm using Postman 4.9.2, and can't right click on the delete icon

**Comment by bluesky139** [comment]
Even right click is not work on chrome, I think a normal button or menu item could be added, so chrome users can also use this function too.

**Comment by a85** [comment]
All: I'd request you to move to native apps. Google will close off the Chrome app platform soon and hence we are focusing our efforts on native apps.

**Comment by cpttripzz** [comment]
Not working on Native LInux App

**Comment by hlubovac** [comment]
@vegetableman, I'm using 4.10.5, and I see no "close all tabs" anywhere. Right-click on tabs does nothing.

**Comment by strowk** [comment]
Guys, it's not working in Chrome! If there is no possibility to create context menu, why could not in be done otherwise? We can double click and do very many different kinds of things with our keyboard!

**Comment by strowk** [comment]
Since it's not going to be supported in Chrome I created https://github.com/postmanlabs/postman-app-support/issues/2956 just to make it sure that the problem still exists.

**Comment by hlubovac** [comment]
OK, sorry, I confused the "in-Chrome" with how Postman used to run: literally inside Chrome window. It's still an extension (the way I have it), so I thought that would have been the same thing. Although since some point it launches within a separate window, it's still a Chrome extension (did I say that already), and so I thought that's what you might have meant by "using a native app". I didn't realize then that there is actually a platform-specific installation of this application. Switching to the "native" app...

**Comment by DaBlick** [comment]
+1

**Comment by tomershay** [comment]
+1

**Comment by seanquinn** [comment]
+1

**Comment by MedveDomg** [comment]
+1

**Comment by note** [comment]
Shouldn't it be reopened?

**Comment by bhawna2109** [comment]
This is available in the native apps now! Clicking on the three dots next to the new tab icon (+ icon) brings up a dropdown with options to close and force close all tabs.

![image](https://user-images.githubusercontent.com/14976346/32777840-cb12f95e-c95d-11e7-8734-e2d5bae525e9.png)

**Comment by note** [comment]
@bhawna2109 you're right, sorry for confusion

**Comment by bhawna2109** [comment]
No problem, @note! Let us know if there's anything else we can help with.

**Comment by vircoder** [comment]
@bhawna2109
After updating ubuntu not able to load this native app

![postman erro](https://user-images.githubusercontent.com/33712990/32877671-a0bee228-cac8-11e7-943a-25958071bddb.png)

**Comment by sdnts** [comment]
@vircoder Are you on the native or Chrome app?
Can you open up the DevTools and check if you see any errors there?

**Comment by vircoder** [comment]
No, I am not using chrome extension for postman but it is native app with
ubuntu.
It was working fine some days before on ubuntu 16.04 but when I downloaded
and installed the ubuntu updates it stopped working.
It is still loading loading and loading ...
you can see the screenshot for reference.
