### ISSUE TITLE
Add the ability to swap http/1.x to http/2

### ISSUE THREAD

**Issue by SG23NK23** [a85/POSTMan-Chrome-Extension#12643]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

There is no way to change the version. There are projects in my company that use http/2. Personally, this is vitally necessary for me.

### Describe the solution you'd like

choosing a version

### Describe alternatives you've considered

insomnia...

**Comment by appurva21** [comment]
Hey @SG23NK23! I am closing this as a duplicate. You can follow #2701 and #6242 for further updates on the HTTP2 support.
