### ISSUE TITLE
API tabs need to be in a vertical bar, not in the chrome / browser format

### ISSUE THREAD

**Issue by sidPhoenix17** [a85/POSTMan-Chrome-Extension#12647]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

I have multiple tabs open in postman ( a lot of them historically) and I always need to browse between them. I need an easier interface to move between them.
The global search is not optimised for tab search.

### Describe the solution you'd like

Having an option to move tabs from a horizontal bar to a vertical menu on right or left (either) would be really helpful. Keeping it optional is also cool.

### Describe alternatives you've considered

* Using global search -- but it creates too much noise as there's infinite other stuff.
* There's a down arrow button next to last tab using which i can search. But (a) It's really hard to know until you know it (B) it's too much effort.. A static one would be ideal!!

**Comment by chris-torruella** [comment]
Hi @sidPhoenix17, I'm a Design Manager here at Postman, thanks for your feedback!
Based on your explanation, Tab Search appears to be a suitable solution for your needs (the down arrow button). To address the effort you mentioned, have you considered utilizing the keyboard shortcut? It offers additional flexibility for customization. Feel free to modify it to better suit your preferences. Let me know if this suggestion works for you. Thanks!
<img width="601" alt="Screenshot 2024-02-14 at 15 05 54" src="https://github.com/postmanlabs/postman-app-support/assets/120389184/0dac6a29-61e2-4846-9459-dd6be520d4c4">

**Comment by sidPhoenix17** [comment]
Hi @chris-torruella thank you for sharing about this -- I saw the keyboard search but will require a bit of muscle memory before I can remember it.

Also, generally whenever I launch postman application (say 1-2 times a week), I'm generally going here to do some work on a different tab so almost always requires me to search through the tab -- hence my request for a permanent tab on the sides! 
Your data might say better if that's the general behaviour or not!

**Comment by chris-torruella** [comment]
I understand @sidPhoenix17. Just curious, would "pinning tabs" in Postman be something useful to help your use case? (You can try this experience with right click on a tab in Chrome browser)
