### ISSUE TITLE
VS Code extension does not respect 'Inherit auth from parent' setting

### ISSUE THREAD

**Issue by BieleckiLtd** [a85/POSTMan-Chrome-Extension#12642]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

In Postman desktop when I set 'Inherit auth from parent' it adds Authorization header. When I do the same in the plugin I can see 'This request is using Basic Auth from collection XYZ' message but Authorization header is not being added and I get 403. When I set Basic Auth directly in my request, header is being correctly added.

### Steps To Reproduce

1. Create Environment, add User and Password variables
2. Create Collection, set Basic Auth, use env variables
3. Create Request, set 'Inherit auth from parent'
4. Send request -> receive 401 or 403

### Operating System

Windows

### Postman Version

0.18.0

### Postman Platform

Other

### User Account Type

Signed In User

**Comment by aquibjr-postman** [comment]
This issue has been resolved as of v1.0.3 of the VSCode Extension. Please let us know if you still run into the same issue. @BieleckiLtd 
cc: @kartikjain26 @sony-mathew
