### ISSUE TITLE
View and save responses generated by Runner

### ISSUE THREAD

**Issue by ghost** [a85/POSTMan-Chrome-Extension#1264]
It would be great if Postman could save (for visual inspection) the responses generated by Runner when executing tests for collections.

**Comment by blowsie** [comment]
+1 :+1:

**Comment by blowsie** [comment]
Referencing https://github.com/postmanlabs/postman-app-support/issues/855

**Comment by msignataur** [comment]
+1

**Comment by blowsie** [comment]
It is possible to use chrome dev tools by going to chrome://inspect , however as the original post mentions, It would be great if postman could show this information inline with the tests

**Comment by vegetableman** [comment]
The new postman beta supports viewing logs and responses on a new window which could be accessed through `View > Show Postman Console`. Please let me know if it helps. 
https://chrome.google.com/webstore/detail/postman/peehcbpemhaoijngpfpammccddlbafdl

**Comment by blowsie** [comment]
This does not work when on the runner window

**Comment by vegetableman** [comment]
hey @blowsie, thanks for reporting. The fix will be part of the next release.

**Comment by blowsie** [comment]
No problem, this feature is great :+1:

**Comment by brkr** [comment]
+1

**Comment by sdnts** [comment]
Guys, v4.9 has a new Runner that addressed your feature request :)

**Comment by marmor7** [comment]
@madebysid can you explain a bit how to view responses? 
I still can't find them in Postman Runner 4.10

**Comment by msignataur** [comment]
You can view responses at the run results page, clicking in the name of every iteration.

![screen shot 2017-03-30 at 11 56 11 am](https://cloud.githubusercontent.com/assets/7916444/24510543/e6f3402a-153f-11e7-9024-cc48a13f8e77.png)

**Comment by blowsie** [comment]
@marmor7 i found the desktop installation to be easier to use and more feature complete than the webversion

**Comment by boylec** [comment]
when one exports the results of the runner the response bodies are not exported - was this intentional?

**Comment by krish7718** [comment]
I can see the responses but no option to automatically save the responses to a file.
"Export results" is providing summary and not the responses.

**Comment by kdujmic** [comment]
You can log fail response this way
tests["test that fails"]  = false;
if(!tests["test that fails"]) {
 console.log("Failed response: " + responseBody);
}

then look for it in console log ( chrom app chrome://inspect/#apps)

**Comment by rgasioro** [comment]
Would be nice to see a final screen. For example, my last call produces html, I would like to see a Preview result screen after all is done.
