### ISSUE TITLE
VS Code extension is not resolving environmental variables in request address

### ISSUE THREAD

**Issue by BieleckiLtd** [a85/POSTMan-Chrome-Extension#12655]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Attempting to call the endpoint `{{baseAddress}}/MyResource` through Postman VS Code extension returns `Error: Invalid URI "http:///MyResource"`. However, hovering over the {{baseAddress}} variable in address bar reveals its expected value:

```
[E] baseAddress
https://localhost:5001
Environment
```
### Steps To Reproduce

1. Create Environment, add `baseAddress` variable for example `https://localhost:5001`
2. Create Request, set request URI to `{{baseAddress}}/MyResource`
3. Send request -> receive `Error: Invalid URI "http:///MyResource"`

### Operating System

Windows

### Postman Version

0.18.0

### Postman Platform

Other

### User Account Type

Signed In User

**Comment by hendev1** [comment]
can confirm

**Comment by pankajk07** [comment]
@BieleckiLtd Can you please update the extension to the latest version and try again?

**Comment by pankajk07** [comment]
@BieleckiLtd Can you please confirm if the issue is resolved or not?

**Comment by BieleckiLtd** [comment]
Variables are resolving ok now. Thank you.
