### ISSUE TITLE
Edit requests listed after Runner execution

### ISSUE THREAD

**Issue by ghost** [a85/POSTMan-Chrome-Extension#1265]
Runner lists all requests it executed and shows if they passed or failed.

It would be great if I could click on any of the failed requests to edit/fix them and still be able to go back to the list to find and fix the failed requests.

**Comment by a85** [comment]
@bhawna2109 This is the "Open in builder" interface button.

**Comment by a85** [comment]
Late reply for this but we will be integrating the runner as part of the main Postman process so that users can edit the collection in one tab and run it another.
