### ISSUE TITLE
Pre-request Script use pm.request.getHeaders() Gets a header that is not in effect

### ISSUE THREAD

**Issue by likue** [a85/POSTMan-Chrome-Extension#12659]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Headers add Key as Authorization and Value as xxxxxx, but unchecked so that it does not take effect, but in the Pre-request Script using pm.request.getHeaders() can get the header Authorization normally.

### Steps To Reproduce

1. open new request
2. Headers add key Authorization ,value xxxxxxxx
3. unchecked Authorization  so that it does not take effect 
![Dingtalk_20240219103811](https://github.com/postmanlabs/postman-app-support/assets/45352623/42c4e630-ab11-4d19-b9db-601ebfa2d959)
4. Pre-request Script  write console.log(pm.request.getHeaders())
5. Observation console , It still outputs Authorization

### Operating System

Windows

### Postman Version

10.23.1

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by coditva** [comment]
@likue Thanks for reaching out. By default, if you don't pass any options to the `getHeaders` function, it returns all the headers, enabled + disabled.
If you're looking for only enabled headers, you can pass the `{ enabled: true }` option.
```javascript
console.log(pm.request.getHeaders({ enabled: true }))
```

More info on this: https://www.postmanlabs.com/postman-collection/Request.html#getHeaders
Let me know if you need more help on this. 🙂
