### ISSUE TITLE
Could not login: Network error (Request failed with status code 400)

### ISSUE THREAD

**Issue by magnusart** [a85/POSTMan-Chrome-Extension#12651]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Using the cursor.sh version of vscode I get a network error as soon as I try to login with postman extension. I get no browser window or any other feedback than the popup message with the error. The postman console output is empty. I've tried to reinstall the extension without any success.

### Steps To Reproduce

1. Install Cursor.sh
2. Migrate all settings (not necessary?)
3. Try to sign in or create account in Postman view

### Operating System

macOS

### Postman Version

0.18.0

### Postman Platform

Other

### User Account Type

Signed Out User

### Additional Context?

Works fine is vscode.

**Comment by prakharbhardwaj** [comment]
I have recently migrated to cursor.sh IDE and facing the same error.
<img width="475" alt="image" src="https://github.com/postmanlabs/postman-app-support/assets/15891703/ccbe77c2-bbbe-42a1-8266-a255efb14473">

**Comment by ellis-jc** [comment]
i'm also getting this error still:

Could not login: Network error (Request failed with status code 400)

**Comment by pankajk07** [comment]
Hey @magnusart , @prakharbhardwaj and @ellis-jc , currently we don't support other flavors of the VS Code IDE (eg. Cursor, VS Codium etc) except for the original VS Code and VS Code insiders app.

**Comment by postman-ide** [comment]
Hey @magnusart , @prakharbhardwaj , and @ellis-jc, we recently shipped a new version of the extension that supports VS Codium and Cursor IDE. Please update the extension and try it out.
