### ISSUE TITLE
use a saved response in a test

### ISSUE THREAD

**Issue by bandtank** [a85/POSTMan-Chrome-Extension#1266]
I saved a response in an attempt to use it as part of a test. Is this possible? If so, how do you do it? I searched google and this repo for a while, but I haven't been able to find an answer.

**Comment by bsolosy-syncronex** [comment]
Totally agree.  I need this functionality as well, and so far I have not been able to find a solution.

**Comment by shamasis** [comment]
closing as duplicate of https://github.com/postmanlabs/postman-app-support/issues/1262
