### ISSUE TITLE
When I move the app to the second and minimize it I cant reopen the app

### ISSUE THREAD

**Issue by Jadnemr** [a85/POSTMan-Chrome-Extension#12663]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

I'm using windows 11 23h2

### Steps To Reproduce

1. Open postman
2. Drag the app from screen 1 to screen 2 (using extend projector seetings)
3. minimize postman app
4. click and try to open postamn it wont open anymore

### Operating System

Windows

### Postman Version

10.23.1

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by aareyes96** [comment]
I have the same problem. It is very uncomfortable.

**Comment by parma85** [comment]
I have the same problem. It is very uncomfortable. Any news?

**Comment by SteffenEnz** [comment]
Same for me, very annoying!

Sometimes it is working though but I feel like it is related to the missing button mentioned here:
https://community.postman.com/t/i-am-missing-my-restore-windows-size-button-postman-keeping-to-be-maximized/44512

**Comment by thundron** [comment]
Please see https://github.com/postmanlabs/postman-app-support/issues/12683#issuecomment-1976928727 for a full explanation; we'll use that issue for future updates
