### ISSUE TITLE
Unnecessarily high CPU usage

### ISSUE THREAD

**Issue by KeaganStevens** [a85/POSTMan-Chrome-Extension#12679]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Postman is using about ~40% cpu usage while inactive (not sending any requests). My environment is relatively small, only about 50 requests, with no variables, environments or tests.
I have not send any requests in 6h+ and CPU usage remains high.

What is postman doing while idle that is using so much of my CPU ?
Is there any setting I should be looking at to improve CPU usage ?

### Steps To Reproduce

1. Launch Postman
2. Send request
3. Minimize
4. Check Task manager and see 30% cpu usage constantly.

### Screenshots or Videos

This screenshot was taken with 1 request tab open. Request size 620 bytes. Response size 216 bytes.
![postman-high-consumption](https://github.com/postmanlabs/postman-app-support/assets/47221204/7c144997-a5ca-4df6-950b-67d1366ef993)

### Operating System

Windows

### Postman Version

10.22.2

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by danekszy** [comment]
Hey @KeaganStevens, sorry to hear that you're experiencing this... Thanks for reaching out with the issue and lots of details!
Do you mind checking if `Clear Cache and Reload` option from `Help` in hamburger menu is of any help here? If not, does signing out and in again help?
We have a hunch that it might be some bad local state that got cached and that was reach by some bad combination of updates historically.
If you keep experiencing this issue, please keep us posted and we'll try to dig a bit further!
Thanks again! D.

**Comment by danekszy** [comment]
Also @KeaganStevens, another idea would be for you to use Postman's DevTools (Postman is an Electron application) to record a performance profile and share it with us via email (help@postman.com)... Would you be comfortable doing that?
Thanks! D.

**Comment by KeaganStevens** [comment]
Thanks @danekszy for the quick response. 
I checked now and it seems to be fine for now. CPU usage is at expected levels(idling at 0-1%). 
I do see my Postman version changed and is now 10.23.5. I do not see anything in release notes for this version that seems to relate to this issue but maybe whatever issue I was facing was fixed in the new version ?
