### ISSUE TITLE
Unable to override the `User-Agent` metadata in gRPC requests

### ISSUE THREAD

**Issue by viqueen** [a85/POSTMan-Chrome-Extension#12678]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

I am testing some gRPC endpoints and need to set custom `User-Agent` strings , however , my server always receives the request with a `grpc-node-js/1.8.10` metadata value

<img width="852" alt="Screenshot 2024-02-27 at 13 55 32" src="https://github.com/postmanlabs/postman-app-support/assets/8287312/bca55c66-f99b-48c0-bc4a-f2c08072ac55">

<img width="450" alt="Screenshot 2024-02-27 at 13 54 49" src="https://github.com/postmanlabs/postman-app-support/assets/8287312/e7d07379-3d37-4e67-aad1-b1553e45ae6c">

I suspect this is related to the following issue under the hood https://github.com/grpc/grpc-node/issues/2325 , but wondering if there is a workaround

### Steps To Reproduce

1. create a grpc request
2. navigate to metadata tab and set a custom `user-agent` entry
3. invoke the request

### Operating System

macOS

### Postman Version

10.23.5

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by ronork** [comment]
Hey @viqueen , thank you for reporting the issue.
I was able to reproduce the issue and will provide an update once a fix has been implemented.

**Comment by ronork** [comment]
We have fixed this issue in the latest release of the Postman app (v11.1.0). Can you restart your app to verify if things are working fine for you?

**Comment by appurva21** [comment]
I am marking this as resolved, but if you still face this problem in the latest version, feel free to reopen it.
