### ISSUE TITLE
Program not displaying

### ISSUE THREAD

**Issue by danding-s** [a85/POSTMan-Chrome-Extension#12670]
### Is there an existing issue for this?

- [ ] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

1，Open Postman.
2，Maximize the window.
3，Minimize the program.
4，Program not displaying.

### Steps To Reproduce

1，Open Postman.
2，Maximize the window.
3，Minimize the program.
4，Program not displaying.

### Operating System

Windows 11 22631.3155

### Postman Version

10.23.5

**Comment by franklinamador** [comment]
I have the same problem. The steps to reproduce the error are the same.

Operating System
Windows 11 22631.3155

Postman Version
10.23.5 

Postman Platform
Desktop

**Comment by emreonder** [comment]
Same problem happen.
Same steps applied. Postman run on background but not show any window. Need close program on taskbar and re run program.

Postman Version: v10.23.5
Windows Version: Windows 11 Pro (10.0.22631 Build 22631)

Similar issue #12663

**Comment by jviotti** [comment]
Hey there! Can you post a screenshot of the task manager to see the specific background process that's running? On Windows, we make use of https://github.com/Squirrel/Squirrel.Windows for auto-updates, which starts with a helper binary that then runs the actual application binary. So it could be that it gets stuck there

**Comment by TLevkova** [comment]
> Hey there! Can you post a screenshot of the task manager to see the specific background process that's running? On Windows, we make use of https://github.com/Squirrel/Squirrel.Windows for auto-updates, which starts with a helper binary that then runs the actual application binary. So it could be that it gets stuck there

Hi @jviotti ,
I've been facing the same problem since the last few updates.

Can I ask you to provide the names of the processes you assume are related to the issue? I doubt that anyone will upload a screenshot with a full list from the Task Manager. It will be not only numerous, but it could contain sensitive information as well.

As for the defect, it is fairly easy to be reproduced. If I try to open and minimize the Postman window a few times in a row, Postman remains open on the taskbar but the UI is not displaying anything. This makes me think that it might not be related to the auto-update functionality because I can reproduce it at any given moment.

Postman version: v10.23.5
UI Version: 10.23.5-ui-240220-1406
Windows Version: Microsoft Windows 11 Enterprise (10.0.22621 Build 22621)

**Comment by jviotti** [comment]
Thanks for the additional explanations @TLevkova . @thundron @dsanders11 Is this something you can reproduce? It'd be interesting to know whether this comes from Electron or application logic, so we can route it to the right team

**Comment by nrogers805** [comment]
Same issue here, seems to have started with the last Windows update; KB5034765 & KB5034467

**Comment by CQ-Steve** [comment]
I'm having the same issue on Windows 11 with Postman version 10.23.8.

Reproduceable by minimising the Postman window and then attempting to maximise it again; just a portion of the white top border is shown...

Edition:  Windows 11 Business
Version:  23H2
OS Build:  22631.3155

**Comment by parma85** [comment]
I'm having the same issue on Windows 11.

Nome SO	
Microsoft Windows 11 Pro
Versione	
10.0.22631 build 22631

@jviotti i can reproduce systematically. Can I provide you with some useful details for the resolution?

**Comment by jviotti** [comment]
@parma85 Is it happening just with Postman, or do you get the same issues with other Electron apps like Visual Studio Code, Slack, Microsoft Teams (the old one?), Skype?

**Comment by CQ-Steve** [comment]
> @parma85 Is it happening just with Postman, or do you get the same issues with other Electron apps like Visual Studio Code, Slack, Microsoft Teams (the old one?), Skype?

Just Postman... I can confirm that VS Code is fine, as is Teams (although I have the new one).

**Comment by TLevkova** [comment]
> > @parma85 Is it happening just with Postman, or do you get the same issues with other Electron apps like Visual Studio Code, Slack, Microsoft Teams (the old one?), Skype?
> 
> Just Postman... I can confirm that VS Code is fine, as is Teams (although I have the new one).

Same here. Teams and Slack work just fine.

**Comment by parma85** [comment]
I confirm just Postman...  Slack, VS Code, Teams work fine

I use several software. Only Postman has this problem
![image](https://github.com/postmanlabs/postman-app-support/assets/41440479/b746d327-dcb6-4d41-a4f1-aeb520e8baf4)

**Comment by thundron** [comment]
Thank you everyone for chiming in. Could you all also add your CPU/GPU hardware information and driver version?

**Comment by thundron** [comment]
Also knowing when you noticed this behaviour happening would be extremely helpful. Thanks!

**Comment by parma85** [comment]
CPU: 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz, 2803 Mhz, 4 core, 8 processori logici
Driver version: 10.0.22621.2506

![image](https://github.com/postmanlabs/postman-app-support/assets/41440479/320485de-cc8f-482c-926b-a41d8ab13d60)

**Comment by TLevkova** [comment]
> Thank you everyone for chiming in. Could you all also add your CPU/GPU hardware information and driver version?

Hi @thundron,
![image](https://github.com/postmanlabs/postman-app-support/assets/49494334/239a709c-48b4-4b6c-896c-9ad4ceba918d)
![image](https://github.com/postmanlabs/postman-app-support/assets/49494334/fdff5340-0ce9-4edb-9f61-5ba41398bcbc)

I hope this information will be helpful.

As for the second question, I noticed the behavior more than a week ago.

**Comment by CQ-Steve** [comment]
CPU & GPU info below:
![image](https://github.com/postmanlabs/postman-app-support/assets/145365435/c70c3ace-c0d0-486c-b80d-18f752ee2648)

![image](https://github.com/postmanlabs/postman-app-support/assets/145365435/45333151-6a14-415f-b191-b36ee3b29072)


From memory, I think I first noticed the behaviour after the latest Postman upgrade, as I recall searching for an older installation file in order to roll it back...

**Comment by nrogers805** [comment]
Strange behaviour:

If I move Postman to another screen, not the main Windows screen, I do not have the problem. Move back to main Windows screen, and issue persists. So moving to another screen is temp measure until fixed.

**Comment by parma85** [comment]
thanks to @nrogers805 .. i note the same Strange behaviour.
I have 2 screen, like show in the image
![image](https://github.com/postmanlabs/postman-app-support/assets/41440479/991957f5-fb53-416e-b40d-b7f48fcf7c0f)

I use postman always in #2 screen (the main screen). 
If i minimize Postman in #2 screen, i have the problem. If i minimize Postman in #1 screen (the secondary screen), the minimize works fine.

**Comment by CQ-Steve** [comment]
> thanks to @nrogers805 .. i note the same Strange behaviour. I have 2 screen, like show in the image ![image](https://private-user-images.githubusercontent.com/41440479/308878400-991957f5-fb53-416e-b40d-b7f48fcf7c0f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkyMDEzNTIsIm5iZiI6MTcwOTIwMTA1MiwicGF0aCI6Ii80MTQ0MDQ3OS8zMDg4Nzg0MDAtOTkxOTU3ZjUtZmI1My00MTZlLWI0MGQtYjdmNDhmY2Y3YzBmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI5VDEwMDQxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg1ZDQ5OWU5Y2IxYzYyMWQ0ZDNmOTM1OTAyNjU3NmUyNzMwNzVlNWJjYjQ2MWJmYjZiZGUxNjA3ZTNhMDhlMTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._sZ3jwlDF_HU7G1cKCMpwlIV455oMBUtm_QyDjlv5EY)
> 
> I use postman always in #2 screen (the main screen). If i minimize Postman in #2 screen, i have the problem. If i minimize Postman in #1 screen (the secondary screen), the minimize works fine.

Same behaviour here...! It only seems to be happening on the second screen...

**Comment by jviotti** [comment]
Thanks for the information everybody. To confirm (as we cannot reproduce in our setup yet), did this start happening recently? Do you recall roughly when? It might help us out bisect the changes and pin point the first non-working version.

**Comment by parma85** [comment]
yes, this start happening recently. I presume, from the week 12-18th of this month

**Comment by thundron** [comment]
Thank you all for the valuable information.
Another interesting information would be your Windows version and build version, but before you report back to us, could you please give a look at this video here https://github.com/postmanlabs/postman-app-support/issues/12683#issuecomment-1970756808 ? It shows a tiny window somewhere in the corner of the screen that looks like it's the Postman App - could you please check that you maybe see the same behaviour and can maybe re-maximize it manually?

**Comment by nrogers805** [comment]
> Thank you all for the valuable information. Another interesting information would be your Windows version and build version, but before you report back to us, could you please give a look at this video here [#12683 (comment)](https://github.com/postmanlabs/postman-app-support/issues/12683#issuecomment-1970756808) ? It shows a tiny window somewhere in the corner of the screen that looks like it's the Postman App - could you please check that you maybe see the same behaviour and can maybe re-maximize it manually?

Yes, same behaviour here

**Comment by CQ-Steve** [comment]
> Thank you all for the valuable information. Another interesting information would be your Windows version and build version, but before you report back to us, could you please give a look at this video here [#12683 (comment)](https://github.com/postmanlabs/postman-app-support/issues/12683#issuecomment-1970756808) ? It shows a tiny window somewhere in the corner of the screen that looks like it's the Postman App - could you please check that you maybe see the same behaviour and can maybe re-maximize it manually?


Yes, exactly the same behaviour.. I didn't notice the square in the top left of the second monitor before, but clicking on it does indeed maximise Postman again, meaning that I don't have to restart it, at least..

**Comment by franklinamador** [comment]
> Thank you all for the valuable information. Another interesting information would be your Windows version and build version, but before you report back to us, could you please give a look at this video here [#12683 (comment)](https://github.com/postmanlabs/postman-app-support/issues/12683#issuecomment-1970756808) ? It shows a tiny window somewhere in the corner of the screen that looks like it's the Postman App - could you please check that you maybe see the same behaviour and can maybe re-maximize it manually?

same behaviour

**Comment by parma85** [comment]
> Thank you all for the valuable information. Another interesting information would be your Windows version and build version, but before you report back to us, could you please give a look at this video here [#12683 (comment)](https://github.com/postmanlabs/postman-app-support/issues/12683#issuecomment-1970756808) ? It shows a tiny window somewhere in the corner of the screen that looks like it's the Postman App - could you please check that you maybe see the same behaviour and can maybe re-maximize it manually?
Yes, same behaviour here

I note that problem happen only if postman is full screen.. If reduce the windows in not full screen, the restore works correctly.. in final..
the problem is
- only in the 2# screen (in multi screen)
- only with app open in full screen

**Comment by serdarakyol** [comment]
I'm encountering a similar issue. When I launch Postman, a black screen briefly appears before it closes on its own. I'm running Pop!_OS 22.04 LTS, which is based on Ubuntu.

**Comment by danding-s** [comment]
> Thank you all for the valuable information. Another interesting information would be your Windows version and build version, but before you report back to us, could you please give a look at this video here [#12683 (comment)](https://github.com/postmanlabs/postman-app-support/issues/12683#issuecomment-1970756808) ? It shows a tiny window somewhere in the corner of the screen that looks like it's the Postman App - could you please check that you maybe see the same behaviour and can maybe re-maximize it manually?

same behaviour

**Comment by thundron** [comment]
Please see https://github.com/postmanlabs/postman-app-support/issues/12683#issuecomment-1976928727 for a full explanation; we'll use that issue for future updates
