### ISSUE TITLE
Akamai EdgeGrid Authorization: Incorrect header signature when body larger than 128K

### ISSUE THREAD

**Issue by TimKilpatrick** [a85/POSTMan-Chrome-Extension#12685]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

When a API request using the Akamai EdgeGrid authorization type contains a body exceeding 128KB the signature is computed against the entire body. This results in an invalid signature. The signature should only be done against the first 128KB (131072) of the body for a proper signature.

### Steps To Reproduce

1. Create an API request following the guide for Akamai EdgeGrid
2. Select a file or input a body size greater than 128KB
3. Execute request - Response will be "Invalid Signature"

### Operating System

macOS

### Postman Version

10.19.0

### Postman Platform

Postman App

### User Account Type

Signed In User

### Additional Context?

The Akamai Python EdgeGrid library contains logic to properly reduce the data to sign to 128KB. This may be useful as a reference: https://github.com/akamai/AkamaiOPEN-edgegrid-python/blob/master/akamai/edgegrid/edgegrid.py

**Comment by sandeep-singh-pstmn** [comment]
@TimKilpatrick Thanks for reporting this. I will look into it and provide updates in the same thread.

**Comment by TimKilpatrick** [comment]
Thank you @sandeep-singh-pstmn I am willing to provide testing and validation of any updates to the authorization library for EdgeGrid should you need external validation.

**Comment by TimKilpatrick** [comment]
Apologies this issue is not completed, I accidentally closed and reopened it.

**Comment by sandeep-singh-pstmn** [comment]
@TimKilpatrick, The latest version, v11.1.0, includes support for max body. Please test it and provide feedback.

<img width="1116" alt="Screenshot 2024-05-15 at 4 43 25 PM" src="https://github.com/postmanlabs/postman-app-support/assets/85243040/dd353873-b1ca-4b56-9eda-462642cd57fa">

**Comment by TimKilpatrick** [comment]
Hello @sandeep-singh-pstmn this appears to be working as expected and I am able to verify larger POST bodies in requests do not affect the signature generation. The only concern I would raise is that the value should not be editable. The behavior should be:
* If body < 128K: Use entire body for signature
* if body > 128K: Use first 128K for signature

If a user were to alter this field to say use only 96K of an upload the signature generation would fail validation as the receiving end follows the above logic explicitly.

Regardless, this is a great improvement and will certainly help with end users leveraging Postman for larger uploads to Akamai. Thank you!

**Comment by sandeep-singh-pstmn** [comment]
Certain APIs have different maximum body sizes, so the Akamai library allows for flexible configuration of this field, similar to what we are doing.
