### ISSUE TITLE
Show value of a variable in Body

### ISSUE THREAD

**Issue by akkadaya** [a85/POSTMan-Chrome-Extension#12688]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

When I hover over a variable in Body it does not show a value, meanwhile, in the address bar, it does.

### Describe the solution you'd like

Same behaviour as the address bar when hovering over a variable

**Comment by sandeep-singh-pstmn** [comment]
@akkadaya Thank you for reaching out to us.
We recently added support for showing variable resolution in the raw type request body (for now, JSON only). You can also take a look at the attached video.

If you have any more questions or concerns, please let us know.

https://github.com/postmanlabs/postman-app-support/assets/85243040/b31e79da-48d7-4842-a899-229a48b06dfc

**Comment by akkadaya** [comment]
thank you @sandeep-singh-pstmn, can I ask which version this feature was added to?

**Comment by akkadaya** [comment]
I found it, it was added in [version v10.22](https://www.postman.com/release-notes/postman-app/)
