### ISSUE TITLE
Postman goes off screen on 2 monitors

### ISSUE THREAD

**Issue by bnelissen-orisha** [a85/POSTMan-Chrome-Extension#12687]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

When I use postman with 2 monitors, postman window disappears off screen. It happens only on second monitor, nothing weird on first monitor.

### Steps To Reproduce

1. Open postman on first monitor
2. Move postman on second monitor
3. Maximise window
4. Minimize window
5. Maximize window
6. Postman window disappears and icon is now on first monitor task bar

### Operating System

Windows

### Postman Version

10.23.8

### Postman Platform

Postman App

### User Account Type

Signed In User

### Additional Context?

Windows 11 22H2

**Comment by marselino-george** [comment]
Something similar is happening to me too, not sure if it's the exact same issue. I've noticed frequently when the app goes behind another app or gets minimized then disappears completely. I cannot bring it back where it was and the only option i have is to right click and close it. Then, when i close the app the process is not terminated but rather stays on the process list of the task manager.

**Comment by Batou-Yoshikawa** [comment]
> Something similar is happening to me too, not sure if it's the exact same issue. I've noticed frequently when the app goes behind another app or gets minimized then disappears completely. I cannot bring it back where it was and the only option i have is to right click and close it. Then, when i close the app the process is not terminated but rather stays on the process list of the task manager.

Yes, it looks like it's the same issue. I have the exact same behaviour when I use 2 monitors, it's quite weird and ennoying...

**Comment by seb-bau** [comment]
Same for me. Opening Postman on second screen. When I minimize it, it never comes back. Instead you see the "window-animation" is trying to put it on the first screen but it does not appear there. I have to restart Postman every time I minimized it.
For me the problem does only occur when the window is maximized.
Edit: Nevermind, my problem looks more like #12683

**Comment by bnelissen-orisha** [comment]
When I try to anchor another program on first monitor I can get back Postman.

**Comment by thundron** [comment]
Please see https://github.com/postmanlabs/postman-app-support/issues/12683#issuecomment-1976928727 for a full explanation; we'll use that issue for future updates
