### ISSUE TITLE
Write access to the request object in the pre-request script

### ISSUE THREAD

**Issue by dmillman** [a85/POSTMan-Chrome-Extension#1269]
The request object is available in the pre-request script, but it's read-only.

I want to calculate the hash of my request.data to populate the Content-MD5 header, but I can't change the header in the pre-request script.

Is it possible to change this?

**Comment by abhijitkane** [comment]
You can use variables for this. Set the header to {{hash}}, compute the hash in your pre request script, and set postman.setGlobalVariable("hash", CALCULATED_HASH);
