### ISSUE TITLE
Can't see company organization on GitHub integration screens.

### ISSUE THREAD

**Issue by orhunerd** [a85/POSTMan-Chrome-Extension#12706]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

I can see my personal organizations in "import from GitHub" screen, but not the company organization.

### Steps To Reproduce

Hit import
Select Github
Select organization drop down

### Operating System

macOS

### Postman Version

10.23.10

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by jatin3893** [comment]
Hi @orhunerd 

Can you visit the GitHub settings -> Applications -> Authorized OAuth Apps section
Or click this link directly: https://github.com/settings/applications

You should see the "Postman" app in the list -> Click on the 3 dots menu and then "Revoke"
<img width="953" alt="Screenshot 2024-03-12 at 11 52 38 AM" src="https://github.com/postmanlabs/postman-app-support/assets/3127114/6dae1046-8b23-4013-9f02-90c0dbaa8ee8">

Now when you go back to Postman and try the Import from Repository flow, it will ask you to do the OAuth flow again -> And will present you with the list of Organizations that you are a part of.
You can selectively "Grant" access to the GitHub-orgs that you would want to allow Postman to connect to.

**Comment by jatin3893** [comment]
Closing this for now. Please feel free to reopen if you face any issues.
