### ISSUE TITLE
curl: single quotes not properly escaped

### ISSUE THREAD

**Issue by cvmocanu** [a85/POSTMan-Chrome-Extension#1270]
This is a follow up of #1161.

Simply putting single quotes around everything is not enough.

The following bash command, generated by Postman, is invalid:

``` bash
curl -X PUT -H "Content-Type: application/json" -H "Cache-Control: no-cache" -H "Postman-Token: d976d4e6-9aa7-5854-16a4-aac544e0073b" -d '{
    "name" : "Cristian's piano lessons",
}' 'http://localhost:8080/api/v1/sidekick/merchant'
```

Note that the single quote in `Cristian's piano lessons` is ending the bash string. Single quotes like this needs to be escaped.

Bash has really strage escape rules.
To escape a single quote, you need to close the previous string (with a single quote), put a single quote inside double quotes, and start a string again (with a single quote), like this:

``` bash
curl -X PUT -H "Content-Type: application/json" -H "Cache-Control: no-cache" -H "Postman-Token: d976d4e6-9aa7-5854-16a4-aac544e0073b" -d '{
    "name" : "Cristian'"'"'s piano lessons",
}' 'http://localhost:8080/api/v1/sidekick/merchant'
```

**Comment by trayburn** [comment]
This is the export side equivalent of the import problem mentioned in #1999

**Comment by abhijitkane** [comment]
@cvmocanu This has been fixed in v4.4.2 of the app (Chrome only). Can you update (https://www.getpostman.com/docs/updating) and check?

**Comment by sergeny** [comment]
Curl export is not doing percent-encoding either. I've had "(" and ") "in the URL query string, as in
"http://server?location=point (1,2)", and it should've generated "http://server?location=point+%281,2%29".

**Comment by abhijitkane** [comment]
@sergeny Tracking the encoding issue at #2171.
