### ISSUE TITLE
Moving request from fork to collection irrecoverably deletes all information from request

### ISSUE THREAD

**Issue by joshnoe** [a85/POSTMan-Chrome-Extension#12702]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Moving a request from a fork to a collection (or possibly between collections) deletes all information from the request. The information is not recoverable because Postman does not have undo functionality for this move action.

### Steps To Reproduce

* Create a fork off a collection
* In the fork, create a request, entering a url and request body
* Drag to move this request from the fork to the original collection

Expected: Request is moved and its url and body are retained
Actual: Request is moved, but url and body is deleted. As far as I can tell there's no _undo_ for this action, so your work is completely lost

### Operating System

Windows

### Postman Version

10.23.8

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by kartikjain26** [comment]
@joshnoe Does this happen for all your forked collections ? and it is reproducible ?
If not could you please share more details about your collection and user at [help@getpostman.com](url)

**Comment by sony-mathew** [comment]
Hi @joshnoe 

We understand your concerns and challenges with your use case. We are unable to reproduce this issue at our end. If you are still facing this issue, can you upgrade the Postman App to newest version and try again one more time?

If you have any further concerns or questions, please feel free to reopen this discussion. We're here to help and support you.
