### ISSUE TITLE
When sending a file within a pre-request script as multipart/form-data, Postman does not set the Content-Type header

### ISSUE THREAD

**Issue by SmashingQuasar** [a85/POSTMan-Chrome-Extension#12708]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

I am building an API that has a two-step process.

The first step is to upload a file to the server using `multipart/form-data`.
The second step is to add a JSON payload to this picture by sending a second request.

To automate my Postman collection, I need to be able to do the first step as a pre-request script.

When I try to send the file upload, Postman does not set the Content-Type header to `multipart/form-data` which creates a situation where the server ignores this request since it is not of the right type.

### Steps To Reproduce

Here is the request I am using:

```javascript

    const fileCreationRequest = {
        url: `https://${pm.collectionVariables.get("host")}/foo`,
        method: 'POST',
        body: {
            mode: 'formdata',
            formdata: [
                {
                    key: "file",
                    type: "file",
                    src: "postman-cloud:///1eedcc49-402b-4450-85cb-a92919460e18"
                }
            ]
        },
        auth: {
            type: 'bearer',
            bearer: [
                {
                    type: 'any',
                    value: responseContent.data.token,
                    key: 'token'
                }
            ]
        }
    };
```

### Screenshots or Videos

![image](https://github.com/postmanlabs/postman-app-support/assets/11139591/ea373c7e-51eb-45b2-8c68-d96fd0fc7825)

As you can see, no `Content-Type` header has been set.

### Operating System

Windows

### Postman Version

10.24.1

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by userAdityaa** [comment]
Hello, I have done a little search on this topic and I found that setting the mode from formdata to file can help you. If it didnot helped please tell me I will do some more search on this.

**Comment by userAdityaa** [comment]
Are you correctly putting the file under the body of postman POST request for all the file posted ?

**Comment by SmashingQuasar** [comment]
> Hello, I have done a little search on this topic and I found that setting the mode from formdata to file can help you. If it didnot helped please tell me I will do some more search on this.

Hey, this is not a viable option as the `file` mode refers to sending the file as `binary` which is not possible in my situation.

> Are you correctly putting the file under the body of postman POST request for all the file posted ?

I joined my request in the issue if you want to have a look at it. It's a pre-request script so it does not use the Postman GUI. :)

**Comment by userAdityaa** [comment]
Yes, Please attach the Postman GUI while you use the POST method in the GUI.

**Comment by SmashingQuasar** [comment]
> Yes, Please attach the Postman GUI while you use the POST method in the GUI.

This issue is not related to the GUI. It is within a pre-request script. The request built by the GUI is never ran since the pre-request script does not work.

**Comment by sandeep-singh-pstmn** [comment]
@SmashingQuasar Thanks for reaching out, at present, we do not support uploading files from the script. You may also observe the warning in the console.
```
// using this script
const fileCreationRequest = {
        url: `https://postman-echo.com/post`,
        method: 'POST',
        body: {
            mode: 'formdata',
            formdata: [
                {
                    key: "file",
                    type: "file",
                    src: "postman-cloud:///1eedcc49-402b-4450-85cb-a92919460e18"
                }
            ]
        },
        auth: {
            type: 'bearer',
            bearer: [
                {
                    type: 'any',
                    value: 'val',
                    key: 'token'
                }
            ]
        }
    };
pm.sendRequest(fileCreationRequest, function (err, response) {
    console.log(response.json());
});
```
<img width="1512" alt="Screenshot 2024-03-12 at 7 33 44 PM" src="https://github.com/postmanlabs/postman-app-support/assets/85243040/a9a0ad1b-701e-42a4-833b-57901c735943">

"Workaround for your use case:

1. Create a collection and include two requests(upload file and add JSON). Run the collection, ensuring that the request order is correct.
[testing.postman_collection.json](https://github.com/postmanlabs/postman-app-support/files/14582233/testing.postman_collection.json)


https://github.com/postmanlabs/postman-app-support/assets/85243040/3777daad-c8fe-4a9e-8959-e9cbe62396bc


2. You can use the UI to upload the file and send the second request in the tests.
[testing-2.postman_collection.json](https://github.com/postmanlabs/postman-app-support/files/14582236/testing-2.postman_collection.json)


https://github.com/postmanlabs/postman-app-support/assets/85243040/4d65c088-35f2-42e7-9da8-f04159ae7f43
