### ISSUE TITLE
base 64 encoding of Cyrillic characters in flows

### ISSUE THREAD

**Issue by evgeniyraev** [a85/POSTMan-Chrome-Extension#12714]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

When encoding and decoding Cyrillic characters results is flows.
Тhe text in the example is тест.
Even provided with https://www.base64encode.org it doesn't resolve in the correct result
<img width="1574" alt="image" src="https://github.com/postmanlabs/postman-app-support/assets/5468386/92ca77f3-d6ac-4402-aad9-5109455bba64">

### Steps To Reproduce

1. create a string containing Cyrillic letters
2. encode that string 
3. decode the result of the encode
4. compare the original string

### Screenshots or Videos

<img width="609" alt="image" src="https://github.com/postmanlabs/postman-app-support/assets/5468386/1cbaf53f-ee81-4539-8dcf-72bc2c3de6db">

### Operating System

macOS

### Postman Version

10.24.2

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by rabbah** [comment]
this was fixed some time back
<img width="1180" alt="Screenshot 2024-10-17 at 10 12 31 AM" src="https://github.com/user-attachments/assets/a946edc2-c4f7-4de2-b625-dd5e65075ca6">
