### ISSUE TITLE
Postman request fails with 500, while curl returns 404

### ISSUE THREAD

**Issue by vpanichkin** [a85/POSTMan-Chrome-Extension#12712]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Hey, folks. I have an issue:

While making a call in curl

```
curl --location 'https://46.51.207.246:443/./admin/' -k -I -v
```
the server return 404, however the same request in Postman return 500.

### Steps To Reproduce

1. Go to terminal
2. Call `curl --location 'https://46.51.207.246:443/./admin/' -k -I`
    1. The response returns 404
4. Import the curl to postman
5. Call it via postman
    1. The response returns 500

### Screenshots or Videos

<img width="653" alt="image" src="https://github.com/postmanlabs/postman-app-support/assets/16993030/efa07db1-f137-4848-bd38-49b80578369e">

<img width="1311" alt="image" src="https://github.com/postmanlabs/postman-app-support/assets/16993030/1da32958-80b5-4849-a263-37c245817d45">

### Operating System

macOS with Apple M2 Pro

### Postman Version

10.23.13

### Postman Platform

Postman App

### User Account Type

Signed In User

### Additional Context?

curl version: `curl 8.4.0 (x86_64-apple-darwin23.0) libcurl/8.4.0 (SecureTransport) LibreSSL/3.3.6 zlib/1.2.12 nghttp2/1.58.0`

**Comment by vpanichkin** [comment]
We fixed an issue on our side our target is now not to return 500. The difference between postman and Curl is that curl sanitizes the URL.
![image](https://github.com/postmanlabs/postman-app-support/assets/16993030/cf2b7e2b-12a6-46e4-8c9f-9fa00d082e48)

**Comment by vpanichkin** [comment]
Feel free to close the issue or explain somewhere in the docs that the behaviour differs

**Comment by dev-sharma-08** [comment]
Sure, I am closing this issue for now as it is resolved.
