### ISSUE TITLE
Postman does not add the Authorization header when "API Key"

### ISSUE THREAD

**Issue by micmastest** [a85/POSTMan-Chrome-Extension#12729]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

For Post request sent with Authorization set to 'API Key' Environment or Global variables are not working.
I'm receiving 400

### Steps To Reproduce

1. Open **Environments** and set for env: TEST, variable: **test_key_value** and provide **Current value**
2. Open in **Collection** new request tab
3. Setup body that will be sent
4. Setup **Authorization** to:
Key:x-int-secret
Value:{{test_key_value}}
Add to: Header
5. Send request
6. I'm receiving: 400 Bad Request (For key value written directly without env variables => 201)
![Screenshot from 2024-03-20 17-08-23](https://github.com/postmanlabs/postman-app-support/assets/137426017/db679613-7a89-4e68-b073-e46bacd31252)

### Operating System

Linux

### Postman Version

10.23.12

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by micmastest** [comment]
All works properly. There was another place where something more was required

**Comment by andrebruton** [comment]
> All works properly. There was another place where something more was required

What and where?
