### ISSUE TITLE
Digest Auth not starting second request in certain scenarios

### ISSUE THREAD

**Issue by paulcristiann** [a85/POSTMan-Chrome-Extension#12727]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

The Postman client does not follow up with the second request in Digest Auth scenarios, when the server responds with "digest ......" keyword in header, instead of "Digest .......".

This makes the client remain in the Unauthorized state for each request that comes back with the "digest ..." header set.

The keyword was changed to "Digest" using a Proxy and Postman behaved as usual.

<img width="1403" alt="Screenshot 2024-03-19 at 17 42 13" src="https://github.com/postmanlabs/postman-app-support/assets/26283957/1746db9f-a861-4280-bf7c-aca01e8b8c45">

### Steps To Reproduce

1. Open new request tab
2. Select Digest auth
3. Add username and password
4. Call the API service
5. If the response header is set as "digest ...." the second request does not follow

### Operating System

macOS

### Postman Version

10.24.3

### Postman Platform

Postman App

### User Account Type

Signed In User

```[tasklist]
### Tasks
```

**Comment by sandeep-singh-pstmn** [comment]
@paulcristiann,Thank you for reporting this. I can replicate the issue. As per [RFC-6617](https://datatracker.ietf.org/doc/html/rfc7617#section-2), both the scheme and parameters should be handled in a case-insensitive manner. We are tracking this as a bug and will provide updates on the same thread.

mdn web-docs - https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/WWW-Authenticate#directives

**Comment by sandeep-singh-pstmn** [comment]
@paulcristiann  We have fixed this issue in the latest version of the app.
