### ISSUE TITLE
No Login Screen

### ISSUE THREAD

**Issue by cruizeone1** [a85/POSTMan-Chrome-Extension#12724]
Type: <b>Bug</b>

THe extension does not log in

Extension version: 0.19.1
VS Code version: Code 1.87.2 (863d2581ecda6849923a2118d93a088b0745d9d6, 2024-03-08T15:20:17.278Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|13th Gen Intel(R) Core(TM) i9-13900K (8 x 2995)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: unavailable_off<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|16.00GB (7.20GB free)|
|Process Argv|--crash-reporter-id fe791a5b-aa36-4e20-befd-50fa77900019|
|Screen Reader|no|
|VM|50%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627cf:30244335
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:30979542
d34g3935:30971562
fegfb526:30981948
bg6jg535:30979843
ccp1r3:30958155
dsvsc020:30976470

```

</details>

**Comment by pankajk07** [comment]
@cruizeone1  Can you please share the screen recording and extension logs, as this will help us debug the issue faster and provide the right solution.

You can access extension logs from here

<img width="476" alt="image" src="https://github.com/postmanlabs/postman-app-support/assets/44100113/bc1efb44-eea3-4880-9965-acc009e4304b">

**Comment by pankajk07** [comment]
@cruizeone1 Can you please share the screen recording and extension logs, as this will help us debug the issue faster and provide the right solution.

**Comment by pankajk07** [comment]
@cruizeone1 I will go ahead and close the ticket, as we did not get any response from your side. Feel free to create a new ticket, if the issue is still reproducible on your side.
