### ISSUE TITLE
I cant sign in on Postman from my Visual Studio Code.

### ISSUE THREAD

**Issue by vsseoanePeya** [a85/POSTMan-Chrome-Extension#12723]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

I just installed the Postman extension in my Visual Studio. However, when I attempt to sign in to VS Code, an ""Could not login: Network error(Request failed wit status code 400)" error message appears.

### Steps To Reproduce

1. Open VS Code
2. Open Postam tab
3. Select Sign in

### Operating System

macOS

### Postman Version

V0.19.1

### Postman Platform

Postman App

### User Account Type

Signed Out User

### Additional Context?

.

**Comment by pankajk07** [comment]
@vsseoanePeya Can you please share the version of the VS Code that you are using and the extension logs with us? Please also confirm if you are using VS Code or other versions of VS Code like VS Codium etc.

You can access extension logs from here

<img width="476" alt="image" src="https://github.com/postmanlabs/postman-app-support/assets/44100113/bc1efb44-eea3-4880-9965-acc009e4304b">

**Comment by SamLukeYes** [comment]
> @vsseoanePeya Can you please share the version of the VS Code that you are using and the extension logs with us? Please also confirm if you are using VS Code or other versions of VS Code like VS Codium etc.
> 
> You can access extension logs from here
> <img alt="image" width="476" src="https://private-user-images.githubusercontent.com/44100113/267212599-bc1efb44-eea3-4880-9965-acc009e4304b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3MTExODAsIm5iZiI6MTcxNjcxMDg4MCwicGF0aCI6Ii80NDEwMDExMy8yNjcyMTI1OTktYmMxZWZiNDQtZWVhMy00ODgwLTk5NjUtYWNjMDA5ZTQzMDRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI2VDA4MDgwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU5ZTZhOGE4YTRmMTdiZTdjM2UyZDk4YTgwZjUwYTUxYTcxODhhY2Y1OTI5YTNjODQ0MTI2ZTkxYjU1YjVmZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.V3B2R4Msgvy4ew7Fljs5063zjTfmt4m_8I83M6KRPoI">

I ran into the same issue. I'm using VS Code 1.89.1 and Postman extension 1.0.3 on NixOS. Every time I click Sign In, the following lines appear in the log:

```
(2024-05-26T08:11:59.105Z) [info] [extension:sidebar:manager] set login state to busy
(2024-05-26T08:11:59.105Z) [info] [extension:auth] Starting the login flow
(2024-05-26T08:12:00.429Z) [error] [extension:auth:client] Network error (Request failed with status code 400)
(2024-05-26T08:12:00.431Z) [error] [extension:auth:controller] retrieving the redirect URL failed: {"error":"Network error (Request failed with status code 400)"}
(2024-05-26T08:12:00.431Z) [error] [extension:auth] The sign in flow has failed: {"error":{"reason":"Error","details":"Network error (Request failed with status code 400)"}}
(2024-05-26T08:12:00.432Z) [info] [extension:sidebar:manager] resetting the login state to signin
```

Update: After unsetting environment variables `http_proxy`, `https_proxy` and `all_proxy`, and start `code` in terminal, I'm able to login now.

**Comment by pankajk07** [comment]
@vsseoanePeya Can you please try out the above steps suggested by @SamLukeYes and check if it works? 
Alternatively can you try out setting the `Http: Proxy Support` setting to `override` in VS Code and see if that works?

<img width="1466" alt="image" src="https://github.com/user-attachments/assets/5da3d5b2-de9e-47e4-b8ea-97b983afaae9">

**Comment by pankajk07** [comment]
@vsseoanePeya I will go ahead and close the ticket, as we did not get any response from your side. Feel free to create a new ticket, if the issue is still reproducible on your side.

**Comment by Sky640q** [comment]
Trying to reopen the issue as i have the same issue. I removed the env proxy and tried it but not resolved. 
Vscode: 
```
    Version: 1.105.1 (user setup)
    Commit: 7d842fb85a0275a4a8e4d7e040d2625abbf7f084
    Date: 2025-10-14T22:33:36.618Z
    Electron: 37.6.0
    ElectronBuildId: 12502201
    Chromium: 138.0.7204.251
    Node.js: 22.19.0
    V8: 13.8.258.32-electron.0
    OS: Windows_NT x64 10.0.22631
Postman: 1.17.0 
Tried with older version of postman as well.
