### ISSUE TITLE
New tabs randomly created

### ISSUE THREAD

**Issue by jetpacksfan** [a85/POSTMan-Chrome-Extension#1272]
HI there,
I've written tens of requests in several collections of my POSTMAN.

I found that when tapping on the requests one after another on the left pane (without actually sending requests), a new request tab might appear. When closing the tab, a window pops up asking me to save or cancel the change to the request (but actually I make no change to the request)

This becomes annoying because new tabs keep coming up if working for a period of time. Same issue found by my coworkers who's not exchanging requests with me.

( I found that if a new tab appear due to clicking on another request on the left pane, Postman is actually replacing fields, presumably the 'Tests' fields with the fields belong to another request, which is not the expecting behavior. )

Following is my postman ver:
Version 3.0.4 (packaged)
OS: win
Architecture: x86-64
Native client architecture: x86-64

**Comment by a85** [comment]
Thanks for the bug report. We are looking into this. Other users have reported the issue too and we'll push a fix asap.

**Comment by a85** [comment]
Should be fixed in the latest release.
