### ISSUE TITLE
Remove "You've made new changes" toast

### ISSUE THREAD

**Issue by mlambley** [a85/POSTMan-Chrome-Extension#12736]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

When I make changes to a request, a toast appears telling me to post an update to inform others. I understand that you have a vested interest in encouraging me to use all of the features of Postman, but this toast is intrusive and I want the option for it to be removed.

There is nothing in Settings, and clicking the `X` is only a temporary measure - it will return at a later date

### Steps To Reproduce

1. Make changes to request
2. Press save

### Screenshots or Videos

![new changes](https://github.com/postmanlabs/postman-app-support/assets/17264636/c0d5fa05-f7ee-4bd4-9992-b86b7d9afc19)

### Operating System

Windows

### Postman Version

10.24.7

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by akshay-kulkarni-03** [comment]
Hey @mlambley , thanks for providing the feedback! We are actively working on this and will keep you posted as and when we make progress on this.

**Comment by jamesWongAigniter** [comment]
Confirming that this modal appears on MacOS with Postman 10.24.25

**Comment by AGlezB** [comment]
Still present in 11.3.0
At least add a setting to disable it. Also auto-hide it after a few seconds so I don't have to go and dismiss it every single time.

**Comment by Diuda** [comment]
Hey team, we have made changes in our latest version to not show this toast every time but few times when it is relevant to the user. Please update the App to get this change

**Comment by BrendonOSullivan** [comment]
It still sucks. Please let us turn it off.

**Comment by rob893** [comment]
Echoing what the guy above me said. It still sucks. Let us turn it off.

**Comment by akshay-kulkarni-03** [comment]
Hey all, thanks for the feedback! We have fixed this issue and you will no longer see this nudge. Please ensure you update to the latest version of the app.
