### ISSUE TITLE
Many Synch problems ?...

### ISSUE THREAD

**Issue by paolobiavati** [a85/POSTMan-Chrome-Extension#1274]
I have many many many synch error...

**Comment by abhijitkane** [comment]
@paolobiavati Can you send an email to help@getpostman.com with your Postman username and the exact issue you are facing?

**Comment by paolobiavati** [comment]
Hi,

my user name is "paolobiavati"
email "biavatipaolo@gmail.com"

I have a stable connection but i often got many synch error

[image: Immagine incorporata 1]

2015-07-21 13:44 GMT+02:00 Abhijit Kane notifications@github.com:

**Comment by abhijitkane** [comment]
Can you be more specific? Is there any error message displayed on the screen? Or are you not able to connect to Sync at all? Or have some requests not been synced properly?

A screenshot of your application running would be helpful.

**Comment by paolobiavati** [comment]
i put a screenshot in my previous email....

2015-07-21 18:05 GMT+02:00 Abhijit Kane notifications@github.com:

**Comment by abhijitkane** [comment]
Hm..the github issue tracker might not display attachments from emails. Can you attach it here - https://github.com/postmanlabs/postman-app-support/issues/1274#issuecomment-123517208, or send it to help@getpostman.com?
