### ISSUE TITLE
Flows data between blocks returning <null>

### ISSUE THREAD

**Issue by viktorccs** [a85/POSTMan-Chrome-Extension#12758]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

1. Select block returns null under any nested values.
2. Unable to select path, nor options are being shown to select from output.
3. Only values returned under the body are able to be passed as an output, all other nested values not selectable and returning null values

### Steps To Reproduce

1. Create a request to return body with nested values
2. Select any values inside of an array
3. Output content

### Screenshots or Videos

![image](https://github.com/postmanlabs/postman-app-support/assets/165044172/7e44893b-9e04-464d-b5f9-db3ec3783f85)
![image](https://github.com/postmanlabs/postman-app-support/assets/165044172/e9c86803-327b-456e-8fd6-0787c8b955da)

### Operating System

Windows

### Postman Version

10.24.11

### Postman Platform

Both

### User Account Type

Signed In User

**Comment by viktorccs** [comment]
It has been narrowed down to any nested values under any keys which names contain a period.
Any values past that point are returned "null"

![image](https://github.com/postmanlabs/postman-app-support/assets/165044172/081362eb-2728-441f-b631-261e68e3f2f7)

**Comment by saswatds** [comment]
Hi @viktorccs if your keys have `.`, `/`, `~` in them, you will need to escape these characters using a special sequence. 
|Token|Escape Sequence|
|---|---|
| `~` | `~0` |
| `/` | `~1` |
| `.` | `~2` |

So lets say your object looks like 
```
{
 "someObject": {
    "with~char" : { 
       "with/char": {
          "with.char": {
             "aString": "hi"
          }
       }
    } 
 }
}
```
The query to access `aString` would look like `someObject.with~0char.with~1char.with~2char.aString`

Hope this helps. This query here is an extension to the [JSON Pointer](https://datatracker.ietf.org/doc/html/rfc6901) specification with `.` as an alias to `/`.
