### ISSUE TITLE
DNS Lookup slow on localhost

### ISSUE THREAD

**Issue by dream7prod** [a85/POSTMan-Chrome-Extension#12759]
Hello,

I experience very slow DNS Lookup time when using custom local domain (api.localhost.local) : about 5 seconds.
Everything goes fast (about 9ms) with online apis or using 127.0.0.1.
I need to use local sub-domain for my testings...

Is there a way to force DNS cache ?

Thank you :)

@sandeep-singh-pstmn

![Capture d’écran 2024-03-31 à 19 09 13](https://github.com/postmanlabs/postman-app-support/assets/48924192/03cb03c2-4c74-46f6-82a4-51f72ebc10a9)
![Capture d’écran 2024-03-31 à 19 09 53](https://github.com/postmanlabs/postman-app-support/assets/48924192/11354652-8761-48b3-a42e-8943d8a2603b)

_Originally posted by @dream7prod in https://github.com/postmanlabs/postman-app-support/issues/9466#issuecomment-2028829162_

**Comment by sandeep-singh-pstmn** [comment]
@dream7prod  Thanks for reaching out. In Postman, we do not cache DNS on our side; it's all OS-level caching. You can try this curl command to check DNS lookup time as well:

```
curl -o /dev/null -s -w "DNS Lookup Time: %{time_namelookup}\n" http://api.localhost.local:3000/test
```

I've set up a local server and modified the /etc/hosts file to map` api.localhost.local ` to `127.0.0.1.`, I'm also encountering a 5-second delay in DNS lookup. However, when I replaced the `.local ` with `.dev` and simply used `api.localhost.dev`, the DNS lookup time returned to normal.

Upon further investigation, it appears that the `.local` is commonly associated with mDNS (multicast DNS), which might be causing this.

Let me know if this fixes the issue for you.

https://en.m.wikipedia.org/wiki/.local

<img width="1177" alt="Screenshot 2024-04-07 at 9 09 28 AM" src="https://github.com/postmanlabs/postman-app-support/assets/85243040/d0269ec8-add5-4b3c-a5e3-ffe1ae86178b">

**Comment by dream7prod** [comment]
Awesome ! Changing .local to .dev got me back to 1ms DNS response time.
Thank you !
