### ISSUE TITLE
public workspaces in workspace list

### ISSUE THREAD

**Issue by PackElend** [a85/POSTMan-Chrome-Extension#12754]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

I would like to see watched public workspaces in my workspace list. 
I understand, that previously, those who explored the Public Workspaces found them in the recent list and saturated it.
But how about explicitly star them or add them to a favourites list? 

### Describe the solution you'd like

Have a separate favourite list, watched, or stared public workspaces list.

### Additional context

https://community.postman.com/t/how-to-add-public-workspaces-to-your-workspace-list/59332

**Comment by akshay-kulkarni-03** [comment]
Hi @PackElend , we already have an existing feature request open for the same. I am closing this one in favor of that
https://github.com/postmanlabs/postman-app-support/issues/9655
