### ISSUE TITLE
Feature request: Add a status count to the runner

### ISSUE THREAD

**Issue by blowsie** [a85/POSTMan-Chrome-Extension#1275]
Instead of just a spinney wheel, it would be great if it had a status percentage bar, or even just a status count, for example;
`Running request 4 of 1000`

![image](https://cloud.githubusercontent.com/assets/308572/8802828/ada29e94-2fbb-11e5-842c-f1f011531b33.png)

**Comment by sdnts** [comment]
We've been working on a redesign of the runner which addresses this issue.

The new Runner is on our Canary channel, and you can download it for [OSX](https://dl.pstmn.io/download/channel/canary/osx_64) / Windows ([x86](https://dl.pstmn.io/download/channel/canary/windows_32) or [x64](https://dl.pstmn.io/download/channel/canary/windows_64)) / Linux ([x86](https://dl.pstmn.io/download/channel/canary/linux_32) or [x64](https://dl.pstmn.io/download/channel/canary/linux_32)) / [Chrome](https://chrome.google.com/webstore/detail/postman/loddepljkabcghihdkbkfknabkinanff)

I'd recommend you to join our Slack community [here](https://www.getpostman.com/slack-invite) so you can provide feedback before the runner moves to our stable builds :)

**Comment by sdnts** [comment]
@blowsie The updated Runner is out now with our latest release (4.9) on our native apps and it features a progress bar that should help you gauge how much of your run is completed :)
