### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by michaelakin** [a85/POSTMan-Chrome-Extension#1277]
Postman keeps crashing multiple times per day.  Notification to restart fails to restart applicaiton

**Comment by abhijitkane** [comment]
What's the exact error message that you're seeing?

**Comment by michaelakin** [comment]
Postman has crashed.  Click this balloon to restart the app

**Comment by abhijitkane** [comment]
That's odd. Do you remember taking any specific action that causes this?

**Comment by michaelakin** [comment]
I just had a surgery, so I am using my other hand to use the mouse. Sometimes clicking to try and add a new param does it.  Sometimes a lot of data from my Odata query crashes it.

**Comment by abhijitkane** [comment]
We haven't had this issue reported before - we'll investigate this and keep you updated.

**Comment by michaelakin** [comment]
Ok.  Thanks!
