### ISSUE TITLE
Unexpected Application Error! 404 Not Found

### ISSUE THREAD

**Issue by mobilepadawan** [a85/POSTMan-Chrome-Extension#12777]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

After installed the VS CODE Extension, when I try to open the POSTMAN Extension, the login panel window shows me the message specified in this tittle issue. I disabled, uninstalled, and reinstall also reset but I can't get a way to use it. 🤔

So frustrating bc I used it a lot the past year.

I can use another VS CODE extension w/o problem. Also I am using THUNDER CLIENT and I never find a similar issue like the postman is showing me.

![postman](https://github.com/postmanlabs/postman-app-support/assets/48518539/40e43b97-72be-49dd-87be-67a78864d666)

### Steps To Reproduce

1) Install POSTMAN extension.
2) Check the extension is enabled.
3) Try to start it waiting for the login panel.
4) The error occurs.

### Operating System

macOS

### Postman Version

VS Code extension

### Postman Platform

Other

### User Account Type

Signed Out User

### Additional Context?

Unexpected Application Error! - 404 Not Found

**Comment by mobilepadawan** [comment]
I have VS CODE updated to yesterday to the version 1.22.

**Comment by pankajk07** [comment]
@mobilepadawan Can you please share the following details and logs of the extension?

- Email ID/ username used for sign-in
- Current version of VS Code. You mentioned the version you are using is `1.22` which seems to be a very old version as the current version is `1.88`
- Version of the extension

You can access extension logs from here

<img width="664" alt="image" src="https://github.com/postmanlabs/postman-app-support/assets/44100113/0faa6da1-f3af-4d7d-b65c-5ac88f300c4a">

**Comment by mobilepadawan** [comment]
Hi again.
My email in POSTMAN for login is ferproonline_at_gmail
I can't see anything in the side panel of POSTMAN over VS CODE. The error is the only text it appears when I try to used it.
I'm using **VS CODE version 1.88**. It was automatically updated previous to tried to use POSTMAN extension.
The version of the POSTMAN extension is: 0.19.3
I paste the POSTMAN log:

```
(2024-04-08T11:41:31.980Z) [info] [extension] Extension activation started: 1712576491978
(2024-04-08T11:41:31.982Z) [info] [extension] Extension activation completed: 1712576491982
(2024-04-08T11:41:31.982Z) [info] [extension] Extension activation took 4ms
(2024-04-08T11:41:33.228Z) [info] [extension:sidebar:adapter] fetching a correct html for the view mode: {"viewMode":"sidebar"}
(2024-04-08T11:41:33.228Z) [info] [extension:htmlProvider] get sidebar HTML
(2024-04-08T11:41:33.238Z) [info] [extension:workspaceContext:networkClient] fetch recent workspaces: {"baseUrl":"https://bifrost-extension-https-global.gw.postman.com/ws/proxy"}
(2024-04-08T11:41:34.094Z) [error] [extension:workspaceContext:networkClient] the network call failed: {"context":"Failed to fetch recent workspaces"}
(2024-04-08T11:41:34.096Z) [error] [extension:workspaceContext:networkClient] axios error
(2024-04-08T11:41:34.097Z) [error] [extension:workspaceContext] Failed to fetch the recent workspace from the API: {"type":"OTHER","details":"Failed to fetch recent workspaces: status 403"}
(2024-04-08T11:41:34.098Z) [error] [extension:workspaceContext] Failed to retrieve recent workspaces: {"type":"NETWORK_FAILURE","details":"Failed to fetch recent workspaces: status 403"}
```

<img width="384" alt="image" src="https://github.com/postmanlabs/postman-app-support/assets/48518539/773aa33b-d1d1-4630-b0ca-72ed77125a46">
<img width="384" alt="image" src="https://github.com/postmanlabs/postman-app-support/assets/48518539/255c2e75-feda-498c-b1d1-397a865789f5">

**Comment by pankajk07** [comment]
@mobilepadawan Thanks for sharing the required details. Can you once try to log out and login and see if that resolves the issue while we are looking into the issue on our side?

**Comment by Utg-28** [comment]
@mobilepadawan  Same Issue I was also facing in my mac, but worked after sign-out and again sign-in

**Comment by mobilepadawan** [comment]
@pankajk07 I can confirm after applying a logout followed by a log-in it finally works fine again.

I used to do this extension to teach testing. With this information I'll may guide any student that get the same issue.

Txs for the helping!

![image](https://github.com/postmanlabs/postman-app-support/assets/48518539/1ee85220-031a-420f-bdc0-4a889472bce7)

**Comment by pankajk07** [comment]
@mobilepadawan Glad to hear that your problem was resolved. Anyhow we will keep the ticket open for now, to debug this further and provide a proper fix.
