### ISSUE TITLE
Folders missing after sync

### ISSUE THREAD

**Issue by eappell** [a85/POSTMan-Chrome-Extension#1278]
This morning I was doing a lot of work on a specific API.  While I was adding and editing requests, it was continually syncing, occasionally failing to sync, but generally able to connect.  At one point, Postman said there was a conflict between the server and the local request and asked me to select the correct one.  One had the description of the request set to a GUID, which is not correct, the other had the description set to null, which is also not correct.  I attempted to dismiss the popup, but it just wobbled back and forth and wouldn't let me dismiss it.  So I selected one, and continued working.  Shortly after that, it synced again, and my requests went from 156 to 2!  I lost 5 folders full of requests.  So I looked online and attempted to re-sync using the last backup.  Now that collection says it has 61 requests, which I believe is what it was at before I started working on it this morning, but still only two are being displayed in the collection.  The 5 folders that the collection should have are not being displayed at all:

![image](https://cloud.githubusercontent.com/assets/85969/8809375/15fdb8f8-2f9d-11e5-801d-ef15903ff56c.png)

I've tried restoring my backup, disabling sync, restarting Postman, restarting Chrome, nothing works.  I'd hate to lose several hours worth of work!  I have a feeling that the file used to populate the tool has that GUID, or some other corrupt data in it, which is preventing it from loading.  If I knew where that file was I could at least attempt to edit the description and allow it to load, but I don't know where it is on my local drive.  

BTW, I've also noticed, since researching this, that several of my older collections, which I haven't used for months, are now empty online.  I don't know when that happened, but it's very frustrating to lose data that I thought was being backed up for me.  Luckily, I believe I have backed up my collections locally every week or so, so hopefully I will be able to restore those.

**Comment by abhijitkane** [comment]
@eappell Can you send an email to help@getpostman.com with your Postman username / email?

**Comment by eappell** [comment]
Email sent

**Comment by ttripp** [comment]
I also have a number of collections that have folders where it says something like "10 requests", but only 2 show up and none of my folders are displayed.

**Comment by sobtiankit** [comment]
@ttripp Can you email help@getpostman.com with your Postman username/email? We'd help you out. You can also check the status of your collections also at https://www.getpostman.com/profile/collections
