### ISSUE TITLE
unable to upload file in postman at form-data in VsCode extention

### ISSUE THREAD

**Issue by jeevnesh** [a85/POSTMan-Chrome-Extension#12797]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

unable to upload file in postman at form-data in VsCode extension as shown in the sceenshot no way to for postman to read file inside working directory in extension. no option to change setting as we have in app

### Steps To Reproduce

open new http request in postman vscode extension 
select form-data
try to upload file

### Screenshots or Videos

<img width="1713" alt="Screenshot 2024-04-13 at 9 20 55 PM" src="https://github.com/postmanlabs/postman-app-support/assets/70370506/1df679e1-c86c-4d30-ab05-978a90fbde1c">

### Operating System

macOS

### Postman Version

Postman VS Code Extension Version: 0.19.3

### Postman Platform

Postman Web

### User Account Type

Signed In User

**Comment by Mut1aq** [comment]
Anything new on this issue kinda is a crucial part of development

**Comment by amaldinesh7** [comment]
@jeevnesh @Mut1aq  We’re having trouble identifying the issue from the screenshot. Could you please provide more details?

For instance, are you experiencing issues selecting a single or multiple files? Is it happening before or after sending the request, or are you referring to errors in the console?

Also, if you're not using the latest version of the extension, please update and check if the issue persists.

**Comment by v-hung** [comment]
I also had the same problem, in my case the Postman console didn't have any logs at all

**Comment by Kobayashi-UwU** [comment]
I'm having the same problem, the reinstall extension is not working

**Comment by LLwassim** [comment]
![Screenshot 2024-11-14 at 9 32 51 PM](https://github.com/user-attachments/assets/da2f96b7-40d4-4f37-ae68-bcba3fa3877d)

**Issue Summary:**
After uploading a file from my directory, I experience an endless buffering state, preventing further interaction with the extension. I’ve attached a screenshot showing the issue.

**Steps to Reproduce:**

1. Open the Postman extension in VS Code.
2. Attempt to upload a file from the directory.
3. Observe the endless buffering state.

**Troubleshooting Attempts:**

I’ve tried reinstalling the extension and restarting VS Code, but the issue persists.

**Additional Information:**
This issue began recently, so it may be related to a recent VS Code update.
The issue is happening with both single files and multiple files it will buffer regardless, It is happening before sending the request it will continuously load and buffer. 
The error in the console is **"Form param `track`, file load error: missing file source"**

**Comment by indraneel-postman** [comment]
Hi @LLwassim 
The file selection seems to be breaking with the latest VSCode version 1.95.* 
As of now, you can downgrade your VS Code to an older version like v1.94.2 to mitigate this issue.
We are actively tracking this issue and will update here if there is any development.

**Comment by indraneel-postman** [comment]
We'll be tracking the file upload issue which started occurring from VSCode v1.95.* onwards in the following issue: https://github.com/postmanlabs/postman-app-support/issues/13266
Please follow the same for updates.

This particular parent issue raised by @jeevnesh was raised before VSCode's update, and we are yet to receive further info from them to identify the exact issue they are facing.

**Comment by GalaxyOpen** [comment]
if you just wanna test with postman, forget Postman Extension. Use real postman program. It works  !

**Comment by abhis-10** [comment]
Please can anyone tell me is this issue regarding my postman vs extension or the vs code current version ?

**Comment by pankajk07** [comment]
This issue has been fixed in the extension's latest version (`v1.5.1`). Please update the version and try it out.

**Comment by amunizp** [comment]
Hello, using Postman on VS-code (vs-codium) on ubuntu. file upload was working fine and is working when I downgrade to v1.5.0 
But in v1.5.1 it just silently ignores the list of files I select. 
For example: PUT > Body> form-data I name a key, I select that it is a file. The Value changes to "select Files" I click, select files on the popped up window.  the window closes but where before I would have the path of the files selected I now just have the `select files` button shown. 

Edit: I installed Postman v11.22.0  on linux desktop and the files are uploaded fine through the form.

**Comment by sgit12pro** [comment]
postman extension in vs code is facing issue in file upload due to working directory permission error in vs code ? File name is shown but the file is not uploaded . how to fix?

**Comment by rishavbharti** [comment]
> postman extension in vs code is facing issue in file upload due to working directory permission error in vs code ? File name is shown but the file is not uploaded . how to fix?

@sgit12pro @amunizp Are you on the latest version of VS Code & Postman extension?

**Comment by RafVianney** [comment]
Im using vsiual studio 1.96.2 and had same trouble, said file load error with extension of postman 1.5.1 any fix?

**Comment by mehdad-hussain** [comment]
same here VS Code - 1.96.1, 1.96.2 , Postman - 1.5.1 , file , image could not upload

**Comment by rishavbharti** [comment]
> Im using vsiual studio 1.96.2 and had same trouble, said file load error with extension of postman 1.5.1 any fix?

> same here VS Code - 1.96.1, 1.96.2 , Postman - 1.5.1 , file , image could not upload

@RafVianney @mehdad-hussain 

Could you please help me with the following information:
1. Are you using VS Code or VS Codium?
2. Which operating system are you using?
3. Could you attach a recording of the error?

**Comment by RafVianney** [comment]
1)
![imagen](https://github.com/user-attachments/assets/b4b75b4c-8e13-4c41-ba1c-19853aecab9c)
2)
![imagen](https://github.com/user-attachments/assets/79b65ae9-d53e-448a-91f1-bdd8a5ae1cc1)
3)
![imagen](https://github.com/user-attachments/assets/7d1e1c14-4f44-4804-aad1-9dc34a53236d)
the code that execute and fail. if use the postman aplication, then the code works
![imagen](https://github.com/user-attachments/assets/20c82ee1-fe40-40c5-8d7c-0d7559a58d47)

**Comment by alijalloul** [comment]
Same issue. Used postman agent and it worked fine. Make sure to change the postman folder name in "Users/username/Postman Agent" to "Postman" in order to be able to upload local files while using the Agent

**Comment by RafVianney** [comment]
> Same issue. Used postman agent and it worked fine. Make sure to change the postman folder name in "Users/username/Postman Agent" to "Postman" in order to be able to upload local files while using the Agent

yes i had Postman folder with files inside

**Comment by mrcalifornian** [comment]
Just use Postman App. Do not waste your time trying to make extension work

**Comment by vac-lav** [comment]
The same issue with VS code Postman extension (OS Windows 10). While standalone Postman agent on the same PC works correct.

**Comment by seungdeokhan** [comment]
I'm using cursor. It still does not work.

- postman 1.5.1
- cursor
Version: 0.44.9
VSCode Version: 1.93.1
Commit: 316e524257c2ea23b755332b0a72c50cf23e1b00
Date: 2024-12-26T21:58:59.149Z
Electron: 30.5.1
Chromium: 124.0.6367.243
Node.js: 20.16.0
V8: 12.4.254.20-electron.0
OS: Darwin arm64 24.2.0

**Comment by rishavbharti** [comment]
The above issues have been resolved in the latest version of the extension (v1.6.1). Please update to the newest version and give it a try.

**Comment by AfifaSadiq** [comment]
my vs code shuts down when i click select file in body form-data. 

also in the web verion when i click on select file it allows me to select, doesnt reflect once i select the file

**Comment by rishavbharti** [comment]
@AfifaSadiq Which versions of **Postman extension** and **VS Code** are you using? If they are not the latest versions, can you update them and try again?

**Comment by AfifaSadiq** [comment]
I am using v1.8.1 postman vs code extension and vs code version of 1.98.1

**Comment by rishavbharti** [comment]
@AfifaSadiq 
This issue has been resolved in the latest version of the extension (v1.9.0). Please update to the newest version and give it a try.

**Comment by AfifaSadiq** [comment]
@rishavbharti Its working now, thank you so much.
