### ISSUE TITLE
newman always failed

### ISSUE THREAD

**Issue by jetpacksfan** [a85/POSTMan-Chrome-Extension#1279]
Hi there,
newman always failed in my computer. I did some tests and no matter how I modify it it always returns the error: 
RequestError: f1e3037e-36b0-a096-137f-46c0ebddda6c terminated. Error: ENOTFOUND
I finally did a test, exporting a simplest collection with only 1 request in it, which goes to a link like: www.google.com. environments/globals not used. It runs well on my other computer (windows 7), but always fail on this one (windows 8). Anything I can do?
D:\work\TEST>newman -c test.json.postman_collection_3
Iteration 1 of 1
RequestError: f1e3037e-36b0-a096-137f-46c0ebddda6c terminated. Error: ENOTFOUND

Summary:
## Parent                          Pass Count       FailCount

Collection test                          0               0

Total                                    0               0
newman ver:
1.2.17

**Comment by jetpacksfan** [comment]
No one has ever have the same issue?
![image](https://cloud.githubusercontent.com/assets/13167092/8818001/63dfecf8-307e-11e5-9e2c-18b2b67c47db.png)

Following is the contents of the collection, by opening with notepad:
{
    "id": "6366cd2d-92ae-d336-ad8e-a11fe5113fa1",
    "name": "test_0722",
    "requests": [
        {
            "id": "9c33216b-c8f3-d39b-85e2-8d53907ff773",
            "headers": "",
            "url": "www.google.com",
            "preRequestScript": "",
            "pathVariables": {},
            "method": "GET",
            "data": [],
            "dataMode": "params",
            "version": 2,
            "tests": "",
            "currentHelper": "normal",
            "helperAttributes": {},
            "time": 1437539472377,
            "name": "testreq",
            "description": "",
            "collectionId": "6366cd2d-92ae-d336-ad8e-a11fe5113fa1",
            "responses": []
        }
    ],
    "order": [
        "9c33216b-c8f3-d39b-85e2-8d53907ff773"
    ],
    "timestamp": 1437539350035
}

**Comment by abhijitkane** [comment]
Can you try changing the URL to http://www.google.com?

**Comment by jetpacksfan** [comment]
@abhijitkane Thanks I managed to solve it, by reinstalling the node.js and rebuild the newman.
Previous version: node-v0.12.5
Current version: node-v0.12.7
( node-v0.12.5 works fine on my win7 computer. Somehow donesn't on my win8 one.)
