### ISSUE TITLE
Can't open Postman extension in VS Code after update

### ISSUE THREAD

**Issue by VadimMuhtarov** [a85/POSTMan-Chrome-Extension#12800]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

"Cannot read properties of undefined (reading 'team_users')" error after updating to postman-for-vscode v1.0.0. Tried to reinstalling the extension, without luck.

(2024-04-16T10:44:49.712Z) [error] [extension:sidebar:manager:sidebar] TypeError: Cannot read properties of undefined (reading 'team_users'): {"stack":"TypeError: Cannot read properties of undefined (reading 'team_users')\n    at https://file+.vscode-resource.vscode-cdn.net/Users/Vadim/.vscode/extensions/postman.postman-for-vscode-1.0.0/dist/sidebar/9483.0bfdeefeac20276a.js:238:1332\n    at zt (https://file+.vscode-resource.vscode-cdn.net/Users/Vadim/.vscode/extensions/postman.postman-for-vscode-1.0.0/dist/sidebar/9483.0bfdeefeac20276a.js:238:1988)\n    at Gi (https://file+.vscode-resource.vscode-cdn.net/Users/Vadim/.vscode/extensions/postman.postman-for-vscode-1.0.0/dist/sidebar/8316.f5455e635102fa38.js:2:59082)\n    at Ua (https://file+.vscode-resource.vscode-cdn.net/Users/Vadim/.vscode/extensions/postman.postman-for-vscode-1.0.0/dist/sidebar/8316.f5455e635102fa38.js:2:67929)\n    at To (https://file+.vscode-resource.vscode-cdn.net/Users/Vadim/.vscode/extensions/postman.postman-for-vscode-1.0.0/dist/sidebar/8316.f5455e635102fa38.js:2:106347)\n    at Eu (https://file+.vscode-resource.vscode-cdn.net/Users/Vadim/.vscode/extensions/postman.postman-for-vscode-1.0.0/dist/sidebar/8316.f5455e635102fa38.js:2:97888)\n    at xu (https://file+.vscode-resource.vscode-cdn.net/Users/Vadim/.vscode/extensions/postman.postman-for-vscode-1.0.0/dist/sidebar/8316.f5455e635102fa38.js:2:97813)\n    at mu (https://file+.vscode-resource.vscode-cdn.net/Users/Vadim/.vscode/extensions/postman.postman-for-vscode-1.0.0/dist/sidebar/8316.f5455e635102fa38.js:2:94836)\n    at https://file+.vscode-resource.vscode-cdn.net/Users/Vadim/.vscode/extensions/postman.postman-for-vscode-1.0.0/dist/sidebar/8316.f5455e635102fa38.js:2:46491\n    at t.unstable_runWithPriority (https://file+.vscode-resource.vscode-cdn.net/Users/Vadim/.vscode/extensions/postman.postman-for-vscode-1.0.0/dist/sidebar/8316.f5455e635102fa38.js:2:121676)\n    at Kl (https://file+.vscode-resource.vscode-cdn.net/Users/Vadim/.vscode/extensions/postman.postman-for-vscode-1.0.0/dist/sidebar/8316.f5455e635102fa38.js:2:46200)\n    at Xl (https://file+.vscode-resource.vscode-cdn.net/Users/Vadim/.vscode/extensions/postman.postman-for-vscode-1.0.0/dist/sidebar/8316.f5455e635102fa38.js:2:46436)\n    at Yl (https://file+.vscode-resource.vscode-cdn.net/Users/Vadim/.vscode/extensions/postman.postman-for-vscode-1.0.0/dist/sidebar/8316.f5455e635102fa38.js:2:46371)\n    at cu (https://file+.vscode-resource.vscode-cdn.net/Users/Vadim/.vscode/extensions/postman.postman-for-vscode-1.0.0/dist/sidebar/8316.f5455e635102fa38.js:2:91606)\n    at ya (https://file+.vscode-resource.vscode-cdn.net/Users/Vadim/.vscode/extensions/postman.postman-for-vscode-1.0.0/dist/sidebar/8316.f5455e635102fa38.js:2:63426)\n    at https://file+.vscode-resource.vscode-cdn.net/Users/Vadim/.vscode/extensions/postman.postman-for-vscode-1.0.0/dist/sidebar/8609.b3805cfa063530bf.js:2:710\n    at https://file+.vscode-resource.vscode-cdn.net/Users/Vadim/.vscode/extensions/postman.postman-for-vscode-1.0.0/dist/sidebar/8609.b3805cfa063530bf.js:2:7930\n    at s (https://file+.vscode-resource.vscode-cdn.net/Users/Vadim/.vscode/extensions/postman.postman-for-vscode-1.0.0/dist/sidebar/8609.b3805cfa063530bf.js:2:7700)\n    at https://file+.vscode-resource.vscode-cdn.net/Users/Vadim/.vscode/extensions/postman.postman-for-vscode-1.0.0/dist/sidebar/8609.b3805cfa063530bf.js:2:7871\n    at Array.forEach (<anonymous>)\n    at https://file+.vscode-resource.vscode-cdn.net/Users/Vadim/.vscode/extensions/postman.postman-for-vscode-1.0.0/dist/sidebar/8609.b3805cfa063530bf.js:2:7858\n    at r (https://file+.vscode-resource.vscode-cdn.net/Users/Vadim/.vscode/extensions/postman.postman-for-vscode-1.0.0/dist/sidebar/8609.b3805cfa063530bf.js:2:7711)\n    at https://file+.vscode-resource.vscode-cdn.net/Users/Vadim/.vscode/extensions/postman.postman-for-vscode-1.0.0/dist/sidebar/8609.b3805cfa063530bf.js:2:7848\n    at nrWrapper (<anonymous>:2:29518)","appId":"sidebar","errorElementId":"index-route"}

### Steps To Reproduce

Open Postman extension and login

### Operating System

macOS

### Postman Version

1.0.0

### Postman Platform

Other

### User Account Type

Signed In User

### Additional Context?

Version: 1.88.1
Commit: e170252f762678dec6ca2cc69aba1570769a5d39
Date: 2024-04-10T17:43:08.196Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Darwin arm64 23.4.0

**Comment by qishipengqsp** [comment]
Got the same error

**Comment by AlexisHaddad** [comment]
Same here. Happened after the mac os update.

**Comment by Snakenbake** [comment]
Same here

**Comment by pankajk07** [comment]
@VadimMuhtarov We have identified the issue and working on a fix for the same. We will update the thread, once the fixed version is published.

**Comment by VadimMuhtarov** [comment]
Fixed in v1.0.1, closing the issue

**Comment by pankajk07** [comment]
@VadimMuhtarov @qishipengqsp @AlexisHaddad The issue is fixed and a new version has been published. Please update your extension to `v1.0.1` and try it out.
