### ISSUE TITLE
Postman Only Showing cookies with 'path' value set to exactly the URL requested.

### ISSUE THREAD

**Issue by iamsandesh** [a85/POSTMan-Chrome-Extension#1280]
I observed that Postman is not showing cookies which has its path set to a value other than the exact 'URL' requested.

The changeset which added this feature (https://github.com/postmanlabs/postman-app-support/commit/9f1e65559b7697f5ecfdcf9c82901d0bc6509d22), specifically looks for cookies, which has the 'path' value set to exactly same as the URL requested. This seems to be different from the other REST clients I have used.

This needs to be changed to ensure that all cookies which have the 'path' value set to a subset (or the entire) URL path, needs to be shown. Obviously the 'Domain' has to be the same.

E.g.:
URL requested: http://domain/context/path/subpath1/subpath2/subpath3
All the Cookies with their 'path' value set to one of the following should be returned:
1. http://domain/context/path/subpath1/subpath2/subpath3
2. http://domain/context/path/subpath1/subpath2
3. http://domain/context/path/subpath1
4. http://domain/context/path
5. http://domain/context

**Comment by abhijitkane** [comment]
@iamsandesh Are you sending requests through the Interceptor, or using Postman's own cookie store? http://blog.getpostman.com/index.php/2014/11/28/using-the-interceptor-to-read-and-write-cookies/

**Comment by iamsandesh** [comment]
@abhijitkane I am using the Interceptor v0.2.11. I have Postman v3.0.6. Additionally I also have the Postman Rest Client v0.8.4.16 installed as well.

**Comment by ValeryDubrava** [comment]
I have the same issue.

**Comment by HeathNaylor** [comment]
I have the same issue as well.

**Comment by sdnts** [comment]
We redesigned our Cookie Manager recently, can you update to the latest version (v4.8) and see if you can reproduce this still?

**Comment by PriyaKumaar** [comment]
Hi...how to reset the cookie automatically from second request.

For example:
1.I'm running first request with invalid data the cookie has been set for all the request in collections even i enabled the interceptor.Can please suggest how to handle the cookie in postman collection in detail.

Thanks in advance..!
