### ISSUE TITLE
Upload file using PUT method

### ISSUE THREAD

**Issue by chimit** [a85/POSTMan-Chrome-Extension#1281]
I need to upload a file using PUT method, but PUT method in Postman doesn't support **form-data**.

How to solve it?

**Comment by abhijitkane** [comment]
Postman supports form-data for PUT

![screen shot 2015-07-23 at 13 17 25](https://cloud.githubusercontent.com/assets/681190/8845480/36c2abe2-313d-11e5-8f65-c307e453e3ee.png)

**Comment by chimit** [comment]
Oh, sorry. It seems like it's not a problem of Postman, but server side (Laravel), which handles PUT in some strange way.
