### ISSUE TITLE
Issue with Postman VS Code extension: Only one file sent to server when attaching multiple files

### ISSUE THREAD

**Issue by JavidSumra** [a85/POSTMan-Chrome-Extension#12816]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

When using the Postman VS Code extension, I encountered an issue where only one file is sent to the server, even though multiple files are attached. I am working with Node.js version 20.12.1 and using Multer to handle files with Express. I am a Windows user.

### Steps To Reproduce

1. Open a new request tab in the Postman VS Code extension.
2. In `Body` Select the `form-data` tab.
3. Attach multiple files.
4. Send the request to the server.
5. Observe that only one file is sent, while the others are not.

### Operating System

Windows

### Postman Version

NA (Postman VS Code Extension)

### Postman Platform

Other

### User Account Type

Signed In User

### Additional Context?

I am using Node.js version 20.12.1 and Multer to handle files with Express on the server side.

**Comment by bhavesh70** [comment]
yes i am also facing the same issue

**Comment by pankajk07** [comment]
Duplicate: https://github.com/postmanlabs/postman-app-support/issues/12574

**Comment by JavidSumra** [comment]
> Duplicate: https://github.com/postmanlabs/postman-app-support/issues/12574

Sorry Sir

**Comment by sotibx2022** [comment]
i am having similar issue?
