### ISSUE TITLE
Authorization input hidden on page 

### ISSUE THREAD

**Issue by IsaacAbrahamson** [a85/POSTMan-Chrome-Extension#12822]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

The input for authorization token no longer fully shows on the page when I click into it. Now a tiny little section of the page scrolls which is really annoying because I have to scroll all the way to the bottom to make sure a new line isn't accidentally added.

https://github.com/postmanlabs/postman-app-support/assets/17521691/81f32c5c-55c2-4a90-afe2-94a9933c3066

In a previous version, if the input overflowed it would take up the entire width of the page something like this.

<img width="1154" alt="Screenshot 2024-05-01 at 1 32 53 PM" src="https://github.com/postmanlabs/postman-app-support/assets/17521691/ce337162-d5d4-4ed1-8626-8489aea6e16b">

That was much preferable to a tiny section at the top being scrolled. Ideally, the scrollable section should take up full height.

### Steps To Reproduce

1. Open a collection
2. Go to Authorization tab
3. Enter a very long bearer token
4. Only the top section of the page scrolls rather than seeing the entire input and full height scroll

### Screenshots or Videos

Screenshots included in description.

### Operating System

macOS

### Postman Version

11.0.4

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by sandeep-singh-pstmn** [comment]
@IsaacAbrahamson We have fixed this in the latest version, v11.1.0.
