### ISSUE TITLE
Authorization: Truncated Auth Type Dropdown List

### ISSUE THREAD

**Issue by DBitao** [a85/POSTMan-Chrome-Extension#12823]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

The Auth Type dropdown list is truncated from Bearer Token and above. This happened after updating to version v11.0.5.

### Steps To Reproduce

1. Open a request
2. Go to Authorization
3. Select Auth Type

### Screenshots or Videos

<img width="328" alt="Auth Type Dropdown List" src="https://github.com/postmanlabs/postman-app-support/assets/168701506/aaa1c1ef-cea9-4e4d-9e71-9261898b590d">

### Operating System

Windows

### Postman Version

 11.0.5

### Postman Platform

Postman App

### User Account Type

Signed In User

### Additional Context?

Before the update, the dropdown list looks like this:
<img width="230" alt="Auth Type Dropdown List - Before Update" src="https://github.com/postmanlabs/postman-app-support/assets/168701506/5631fa83-4b64-41eb-94c4-67552c570ce8">

After the update, the top part of the list has been truncated:
<img width="328" alt="Auth Type Dropdown List" src="https://github.com/postmanlabs/postman-app-support/assets/168701506/da32981b-b80b-4c3d-a661-a1a90660c148">

**Comment by sandeep-singh-pstmn** [comment]
@DBitao, Thank you for reporting this. Could you please share a screenshot of the entire screen along with the screen resolution?

**Comment by sandeep-singh-pstmn** [comment]
tracking it here - https://github.com/postmanlabs/postman-app-support/issues/12824
