### ISSUE TITLE
Unable to select the Bearer Token in Auth Type

### ISSUE THREAD

**Issue by Arvindaswamy** [a85/POSTMan-Chrome-Extension#12831]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

In latest update of postman, Auth Type drop-down opening to top.
New --> Authorization --> Auth Type drop down
Due to the drop-down opening to top, few system we can't able to select bearer token option.

<img width="278" alt="image" src="https://github.com/postmanlabs/postman-app-support/assets/162675225/1031f766-ba05-4858-b8a3-7e4ff159df88">

### Steps To Reproduce

In latest update of postman, Auth Type drop-down opening to top.
New --> Authorization --> Auth Type drop down
Due to the drop-down opening to top, few system we can't able to select bearer token option.

### Screenshots or Videos

<img width="278" alt="image" src="https://github.com/postmanlabs/postman-app-support/assets/162675225/98e3b344-cc1a-42ba-96fb-58a4f47f652b">

### Operating System

Windows

### Postman Version

V11

### Postman Platform

Postman App

### User Account Type

Signed In User

### Additional Context?

<img width="278" alt="image" src="https://github.com/postmanlabs/postman-app-support/assets/162675225/e5dc018e-a0d8-491c-82d4-5c4830030148">
<img width="278" alt="postman Auth" src="https://github.com/postmanlabs/postman-app-support/assets/162675225/0ec381b3-fc0c-458f-8d82-c5251accf332">

**Comment by sandeep-singh-pstmn** [comment]
tracking this here https://github.com/postmanlabs/postman-app-support/issues/12824
