### ISSUE TITLE
websocket causing crash in version 11.0.6

### ISSUE THREAD

**Issue by HzAlen** [a85/POSTMan-Chrome-Extension#12837]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Just new a websocket client like ws://localhost，click the Connect button then click the Cancel button will case crash.

### Steps To Reproduce

Just new a websocket client like ws://localhost，click the Connect button then click the Cancel button will case crash.

### Screenshots or Videos

![Snipaste_2024-05-06_10-55-03](https://github.com/postmanlabs/postman-app-support/assets/59987555/28f3651e-fa94-4e75-9c2e-cf1192ec2a0e)

### Operating System

Windows

### Postman Version

11.0.6

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by ronork** [comment]
Hi @HzAlen, I tried reproducing the crash following the steps provided, but couldn't encounter it. Could you share application logs ? This additional information will help us pinpoint the problem. Thanks!
For guidance on retrieving logs, please check: [Postman Desktop app logs](https://support.postman.com/hc/en-us/articles/360025298633-How-to-get-logs-from-the-Postman-Desktop-app)

**Comment by HzAlen** [comment]
[Uploading logs.zip…]()

**Comment by HzAlen** [comment]
@ronork This is my postman log and how to trigger it, I delete requester log before today for confidentiality.

[logs.zip](https://github.com/postmanlabs/postman-app-support/files/15216104/logs.zip)

[20240506_130609](https://github.com/postmanlabs/postman-app-support/assets/59987555/708c75f6-689f-4199-ae24-61430375d132)

**Comment by ronork** [comment]
@HzAlen , thank you for providing the logs.
I was able to reproduce the issue and  we will provide an update once a fix has been implemented.

**Comment by parthverma1** [comment]
This should now be fixed as part of v11.0.12+. Please update your app. Feel free to re-open the issue if you're still facing the same problem.
