### ISSUE TITLE
Postman Version 11.0.5 (grpc) Error: duplicate name 'XYZ' in Type ZzzResponse

### ISSUE THREAD

**Issue by EugeneKomerystiy** [a85/POSTMan-Chrome-Extension#12830]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

When trying to send an GRPC request, an error occurs: Error: duplicate name 'XYZ' in Type ZzzResponse

Proto definition of message Type ZZZ is guaranteed not to contain duplicates
Changing property names does not change anything.
In previous versions (v10.24.3 and 10.24.24-canary01) this problem does not occur.

And it would be great to be able to downgrade.

Thnaks in advance[](url)

### Steps To Reproduce

1. Create a grpc service in proto
2. Add message definition (type)
3. include this type in the response definition
4. Create a grpc request in the Podtman application
5. Import service proto file as API
6. Try sending a request

### Operating System

Windows

### Postman Version

11.0.5

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by appurva21** [comment]
Hey @EugeneKomerystiy! I went through the steps but was unable to recreate the issue. 

Can you share a scaled-down version of your Protobuf that we can use to fast-track this?

**Comment by appurva21** [comment]
I'm closing this issue for now, but if you're still experiencing it in the latest version, please share the previously requested details so we can investigate further.

**Comment by MakDon** [comment]
Met the same issue
