### ISSUE TITLE
Interceptor does not send cookies when Chrome is closed and only the packaged Postman app is open

### ISSUE THREAD

**Issue by corsairmarks** [a85/POSTMan-Chrome-Extension#1283]
I maintain an API application that uses cookies to store a session ID as part of a legacy authentication system.  I use the packaged Postman app with Interceptor for testing the API directly because it is an excellent tool, but I prefer to use Firefox as my browser.  Because of this, I often only have the packaged app open and not Chrome.  Please add support for Interceptor to work while Chrome is closed.

Thanks!

**Comment by corsairmarks** [comment]
Relevant software infos:
- Postman 3.0.5
- Interceptor 0.2.11
- Chrome 44.0.2403.89m

**Comment by abhijitkane** [comment]
This isn't possible right now - the Interceptor extension is not loaded till a Chrome window is open.

**Comment by corsairmarks** [comment]
@abhijitkane Is that a limitation of Chrome, or something that could be implemented by Postman?  I don't have any experience with Chrome extensions, but it might be fun for me to learn and make a contribution to the Interceptor repo.

**Comment by abhijitkane** [comment]
Packaged apps do not have access to Chrome's cookies. Only extensions (like the Interceptor) do. To send Postman's requests through the Interceptor, we use Chrome's message passing API (https://developer.chrome.com/extensions/runtime#method-sendMessage) to communicate b/w Postman and the Interceptor.

One of the following needs to happen to enable sending Cookies using Postman when Chrome is closed:
1.Packaged apps getting access to Chrome's cookie store
2. Extensions running as a background service of some sort
