### ISSUE TITLE
Authorization type window is unresponsive

### ISSUE THREAD

**Issue by jkalinowskizajdak** [a85/POSTMan-Chrome-Extension#12842]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Authorization type window is unresponsive on laptop screens
As a result cannot choose bearer token

### Steps To Reproduce

1. Use postman on laptop screen
2. Open Authorization type window 
3. Cannot choose bearer token

### Screenshots or Videos

![image](https://github.com/postmanlabs/postman-app-support/assets/35449107/ba098623-173b-4840-ba5d-091d9449da6d)

### Operating System

Windows

### Postman Version

11.0.6

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by sandeep-singh-pstmn** [comment]
tracking this here -> https://github.com/postmanlabs/postman-app-support/issues/12824
