### ISSUE TITLE
OAuth1.0a generating invalid signature when sending files

### ISSUE THREAD

**Issue by ghost** [a85/POSTMan-Chrome-Extension#1284]
My understanding of OAuth10.a is that files should not be included in the header, but Postman is using some form of data from the files in the signature generation causing it to not validate on the server.

I can successfully make a post with files by making a post without files, disbaling authentication, and posting using the previously-created header.

**Comment by abhijitkane** [comment]
@cjarrett-hipwood Are you still seeing this in the latest version of the app?

**Comment by tyteen4a03** [comment]
I think I am experiencing this issue. I generated my own signature with the PHP console and can confirm that it does not match the one Postman generated.

**Comment by sdnts** [comment]
@cjarrett-hipwood @tyteen4a03 Can you guys try updating to the latest version (4.7) on the native app and verify if this is fixed?
