### ISSUE TITLE
Basic Auth and No Auth option not available under Authorization drop down.

### ISSUE THREAD

**Issue by A9DC** [a85/POSTMan-Chrome-Extension#12843]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

I recently updated my postman to v11.0.6 and now under the Authorization drop down I do not find  Basic Auth option .  If the request previously had Basic Auth, then it is present . But if I have to add it new then there's no option present. I tried opening it in the website also but couldn't  find the option there also. I tried opening postman in full screen and minimized screen , but nothing helped. I have attached the Screenshot for reference. I heard from the POSTMAN team that it's a bug from their end. So hoping it can be fixed asap.
Link 
![authorization](https://github.com/postmanlabs/postman-app-support/assets/122878453/d7411645-64c9-4177-8766-17d0806404fc)
![Basic Auth](https://github.com/postmanlabs/postman-app-support/assets/122878453/f89390b2-8894-4af8-aac4-803467350989)
:
![Basic Auth](https://github.com/postmanlabs/postman-app-support/assets/122878453/48d8322a-f5de-4b3d-a6e9-3282a527aa37)

### Steps To Reproduce

1. open a new request.
2. Click on Authorization drop down
3. Basic Auth or No Auth is not present in the drop down.

### Screenshots or Videos

![authorization](https://github.com/postmanlabs/postman-app-support/assets/122878453/9d7b70b9-9826-4096-80c5-60026e7c8396)
![Basic Auth](https://github.com/postmanlabs/postman-app-support/assets/122878453/5c40f522-df7e-4766-9eb8-2c0b1bd8aa07)

### Operating System

Windows

### Postman Version

11.0.6

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by sandeep-singh-pstmn** [comment]
tracking this here -> https://github.com/postmanlabs/postman-app-support/issues/12824
