### ISSUE TITLE
Unable to Import from Workspace in VS Code

### ISSUE THREAD

**Issue by wwfiserv** [a85/POSTMan-Chrome-Extension#12848]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

When using the import function in VS Code for a file or folder in a GitHub workspace the application errors "Something went wrong while importing the file". Not sure if impacting but this is a virtual workspace.

We are trying to maintain the Postman Collection for our Developer Documentation and would like to import and save to the Git repository/directory in our Workspace.

### Steps To Reproduce

1. Click Import button
2. Select File or Folder
3. Select respective JSON file or folder containing JSON collection

### Operating System

Windows

### Postman Version

1.0.1

### Postman Platform

Other

### User Account Type

Signed In User

**Comment by indraneel-postman** [comment]
Hey @wwfiserv
Thanks for creating this issue regarding usage in virtual workspaces. We have identified the issue and are working on the fix.

**Comment by indraneel-postman** [comment]
Hi @wwfiserv 
The support for importing files in virtual workspaces has been added in Postman VS Code extension **v1.0.3**. Please update your extension to the latest version. Closing this issue.
