### ISSUE TITLE
Upgrade to Version 11 getting  "Using "_" is deprecated. Use "require('lodash')" instead.

### ISSUE THREAD

**Issue by Cindi-QA** [a85/POSTMan-Chrome-Extension#12850]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

I am getting this on all scenarios that I am running thru the app.  When I searched to fix it I get nothing found.  
![image](https://github.com/postmanlabs/postman-app-support/assets/97465795/a9ff1e82-8b39-4035-80ed-fad065404c86)

### Steps To Reproduce

Open my API/Collection
Run Folder Start up
Runs a process script and the log in scripts.
Results from console
![image](https://github.com/postmanlabs/postman-app-support/assets/97465795/151dfee4-f8ec-4409-99a0-45c5fff4da45)

### Screenshots or Videos

See above

### Operating System

Windows

### Postman Version

V11

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by DannyDainton** [comment]
Hey @Cindi-QA,

The warning that's shown is letting you know what the fix is for that log message.

Previously, you would use lodash in the scripts by using the `_.<method>`. That was actually using an older version of lodash.

To use the newer version and remove the warning (The old way will continue to work for the next couple of major versions), you will need to amend the scripts to use something like this:

```
const lodash = require('lodash');
console.log(lodash.random(10))
```
I've called it `lodash` but you can call it something more appropriate.

**Comment by Cindi-QA** [comment]
Thanks for the reply!  I was able to get this figured out but now it seems it is not liking the toString() method so working on trying to get that worked out but not finding anything useful.  Will keep looking or add a new support item if I can’t find it.

pm.globals.set("response400Tests", response400Tests.toString());

This toString is not working any longer.

Thanks,
Cindi

**Comment by DannyDainton** [comment]
I'm not sure what `response400Tests` is in your context or what the error message is that you're seeing.

Just as a basic example, this works in the latest version using `toString()`
```
const arr = [1, 2, 3];

console.log(arr.toString());
```

**Comment by Cindi-QA** [comment]
Here is the entire code set.  I am generating a random string of characters that are 64 long.
var minmaxsettings = () => {
pm.collectionVariables.set("randomString64", randomString64(STRING_LEN));
//65
function randomString65(length=1) {
    let randomString65 = "";
    for (let i = 0; i < length; i++){
        randomString65 += pm.variables.replaceIn("{{$randomAlphaNumeric}}");
    }
    return randomString65;
}
STRING_LEN = 65
pm.collectionVariables.set("randomString65", randomString65(STRING_LEN));
}
pm.globals.set("minmaxsettings", minmaxsettings.toString());

I also see that STRING_LEN is not supported with this upgrade.


Thanks,
Cindi

**Comment by Cindi-QA** [comment]
All is working now, and I really exceeded my limits just to clean up the code changes needed.  This is on one collection, and I have a really large one that I haven’t even started on yet.

Thank you for your help and direction in both my issues.  You can close this ticket as I have it working for my new collection.

Thanks,
Cindi
