### ISSUE TITLE
Feature Request - Collection variables

### ISSUE THREAD

**Issue by stefan1968** [a85/POSTMan-Chrome-Extension#1285]
So, I have a bunch of requests I use to test my server locally, they're under a Collection called 'Local Server'

Now, I can obviously duplicate the group to create the same requests for says a 'Dev/Staging/Production' server, but I have to go through each request from my base local url to whatever the dev/staging url is.

Even with environment variables set this is tedious. Currently I end up doing a search and replace in the exported JSON.

A great feature would be the ability to assign Collections with a baseURL, so all the requests below them would be relative.

**Comment by abhijitkane** [comment]
We'll be introducing collection-level variables soon, but they'll function similar to environment variables. What's the difficulty you're facing using environment variables?
You can set the url of each request to {{baseURL}}/relativePart, and have 3 environments - Dev/Staging/Prod, each with a different value of baseURL.

**Comment by stefan1968** [comment]
Yes, I understand that. But say I've created 100 requests under the group LocalServer.
I duplicate that group to Staging Server. I still have to hand edit the 100 requests to change the baseUrl, environment variable or not.

**Comment by aat-antoine** [comment]
+1. I think it will be interesting to get environnement feature for each collection and save it in the cloud.

**Comment by wichert** [comment]
Is this feature still planned?

**Comment by sdnts** [comment]
Indeed, you can follow our [product roadmap](https://trello.com/b/4N7PnHAz/postman-roadmap-for-developers) to stay up to date. This feature is planned in the near term.

**Comment by a85** [comment]
This is available now in 5.5+
