### ISSUE TITLE
Ability to use Postman Vault variables in pre/post-scripts

### ISSUE THREAD

**Issue by pbalsara-wk** [a85/POSTMan-Chrome-Extension#12864]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

With the introduction to Postman Vault, I was considering moving all our apiKey variables for our different environments into the vault. I wanted to determine which apiKey should be used depending on the Environment variable selected. (Dev, QA, etc). It seems like there is no way to use Postman Vault variables in pre/post scripts. They can only be used in local, collection, and environment variables. 

### Describe the solution you'd like

I want the ability to allow using Postman Vault variables in the pre/post-script so I can determine which Vault variable to use depending on the Environment I'm testing in. 

### Describe alternatives you've considered

Current option is to just set everything at the Environment level. However, since this is a shared Workspace an Environment for each user per environment (Dev, QA, Prod, etc) needs to be created and this is cumbersome.

```[tasklist]
### Tasks
```

**Comment by slaphead** [comment]
We have the same need. The workarounds do not appear to work either. That is, if I set a Global variable pointing to the vault and then reference the Global variable from the script, it still does not appear to resolve to the value set in the vault.

A more direct way would be ideal.

**Comment by SteffenBraeunig** [comment]
It would be really helpful if there was either a script option (pm.vault) or, even better, if a vault variable could be used as the environment value. This way you can also access different vaults via the environment sets.

**Comment by daniel-luper** [comment]
My team also has the same the need, this feature would be a game-changer!

**Comment by GovindKarthikeyan** [comment]
Most of the use cases relates to these secured values are needed at runtime for usages like chaining requests, pre and post scripting etc. Just exposing these secrets statically won't help in most cases, also there should be a way to keep these secretes according to the environment right now it just ties to one global scope not changing according to the environment you select, we badly need this feature and with out this vault feature is useless for us.

**Comment by Pranav2612000** [comment]
Hello everyone!
We have an exciting update. Vault Support in Scripts is now available from Postman 11.9.
Here's how to use it [ [LINK](https://learning.postman.com/docs/tests-and-scripts/write-scripts/postman-sandbox-api-reference/#using-vault-secrets-in-scripts) ]

**Comment by pbalsara-wk** [comment]
@Pranav2612000 when I click on the link, it goes to this issue, not to a link on how to use it.

**Comment by Pranav2612000** [comment]
> @Pranav2612000 when I click on the link, it goes to this issue, not to a link on how to use it.

Thank you for pointing it out @pbalsara-wk ! I've updated the link now.

**Comment by cleary-wolters-kr** [comment]
We need this feature too

**Comment by Pranav2612000** [comment]
Please be aware that Postman app V11.12 release includes breaking changes related to Postman Vault API in scripts that require updates to your code.

**Key Breaking Changes:**
- Now we only supports the following methods for vault secrets:
    - `pm.vault.get("secretKey")`
    - `pm.vault.set("secretKey","newValue")`
    - `pm.vault.unset("secretKey)`
- You must add the `await` operator before each pm.vault method. Without the operator, the method won't run.
- We no longer supports using pm.variables to access or manipulate vault secrets. You must use pm.vault.
Example:
```
console.log(await pm.vault.get("secretKey"));
await pm.vault.set("secretKey", "newValue");
await pm.vault.unset("secretKey");
```

We apologize for any inconvenience these changes may cause. We believe that the benefits of these updates will far outweigh the initial effort required to migrate.

**Comment by GovindKarthikeyan** [comment]
> Please be aware that Postman app V11.12 release includes breaking changes related to Postman Vault API in scripts that require updates to your code.
> 
> **Key Breaking Changes:**
> 
> * Now we only supports the following methods for vault secrets:
>   
>   * `pm.vault.get("secretKey")`
>   * `pm.vault.set("secretKey","newValue")`
>   * `pm.vault.unset("secretKey)`
> * You must add the `await` operator before each pm.vault method. Without the operator, the method won't run.
> * We no longer supports using pm.variables to access or manipulate vault secrets. You must use pm.vault.
>   Example:
> 
> ```
> console.log(await pm.vault.get("secretKey"));
> await pm.vault.set("secretKey", "newValue");
> await pm.vault.unset("secretKey");
> ```
> 
> We apologize for any inconvenience these changes may cause. We believe that the benefits of these updates will far outweigh the initial effort required to migrate.

Thanks for the update @Pranav2612000 Now with the new release, below logic breaks

  const grandType = await pm.vault.get("grandType");  // It's working

  const clientId = pm.variables.replaceIn(pm.environment.get("cdClientId"));  // Breaking with displaying {{vault:cdClientId}}
  const clientSecret = pm.variables.replaceIn(pm.environment.get("cdClientSecret")); // Breaking with displaying {{vault:cdClientSecretLiveDev}}
console.log(grandType, clientId, clientSecret); // "client_credentials" "{{vault:cdClientId}}" "{{vault:cdClientSecretLiveDev}}"

Please let us know how to get around this breaking change, Thanks
