### ISSUE TITLE
Mock Examples are returning 502 Bad Gateway nginx/1.25.3

### ISSUE THREAD

**Issue by Aditiiert** [a85/POSTMan-Chrome-Extension#12876]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

For a collection, when I mock an API using the mock server URL, the first API mock example returns 200 OK, but 2nd mock example of 2nd API is returning 502 Bad Gateway NGINX.

Steps

Create a collection of APIs
Mock the collection
Create example of the 1st api in the collection, and customize the request and response as per the need, change the endpoint of this api to point to mock server url. Try the mock example, it returns the customized response.
Create example of 2nd API in the collection like 1st API- and customize the request and response as per the need, change the endpoint of this api to point to mock server url. Try the mock example, it returns 502 Bad Gateway NGINX

### Steps To Reproduce

1. Create a collection of APIs
2. Mock the collection
3. Create example of the 1st api in the collection and customize the request and response as per the need, change the endpoint of this api to point to mock server url. 
4. Try the mock example, it returns the customized response.
5. Create example of 2nd API in the collection like 1st API- and customize the request and response as per the need, change the endpoint of this api to point to mock server url. 
6. Try the mock example, it returns 502 Bad Gateway NGINX

### Screenshots or Videos

![image](https://github.com/postmanlabs/postman-app-support/assets/170449149/cdbac666-3576-438a-8612-6e064bb21164)
![image](https://github.com/postmanlabs/postman-app-support/assets/170449149/addc1db8-da15-4a1e-ba39-7f1f6063e4b2)

### Operating System

Windows

### Postman Version

11.1.14

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by shikhar-codes** [comment]
Hi @Aditiiert, we noticed this issue on our server some minutes back and it should have been fixed now. Could you retry hitting the flows once and let us know if it is still a problem you're facing ?

Thanks.

**Comment by Aditiiert** [comment]
Hi @shikharrrrrr I checked the APIs, they are working fine now. Thank you
