### ISSUE TITLE
Connection issue when signing into the app

### ISSUE THREAD

**Issue by fkxq4me50kksl** [a85/POSTMan-Chrome-Extension#12878]
### Is there an existing issue for this?

- [ ] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Click postman login, prompting Unable to connect to our servers, uninstalling and reinstalling it will not solve the problem, and lowering the version will not solve the problem. no network proxy is used
![_20240522133718](https://github.com/postmanlabs/postman-app-support/assets/43986377/7e32760f-659c-4ae2-8cc4-2b527e609a52)

### Steps To Reproduce

1.open postman
2.click sign in

### Screenshots or Videos

https://github.com/postmanlabs/postman-app-support/assets/43986377/6de95f96-eb34-4bfb-9a58-c86a45356ee1

### Operating System

Windows

### Postman Version

11.1.14

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by gerhard-engelbrecht** [comment]
Same issue on Mac

**Comment by fkxq4me50kksl** [comment]
Updated to v11.7.0 ，resolve the issue

**Comment by shipafrika** [comment]
I have same issue with latest version of postamn for mac Intel.

<img width="1173" height="737" alt="Image" src="https://github.com/user-attachments/assets/1e7cb219-0ad8-4168-bcfd-86efb74ccd7b" />
