### ISSUE TITLE
Saving Universal Basic Auth. Creds

### ISSUE THREAD

**Issue by ramGitHub822** [a85/POSTMan-Chrome-Extension#1287]
there needs to be a way to use one universal basic auth. creds. for all requests in one environment. right now we have to go in and set basic auth. creds for every single request so if you can get a universal basic auth. creds per env.  that would help testing a lot of requests in one env. go a lot quicker. 

Thank you. 
![screen shot 2015-07-24 at 11 38 03 am](https://cloud.githubusercontent.com/assets/11445961/8878349/7d857756-31f8-11e5-8eb0-13f92fb02ad8.png)

**Comment by shamasis** [comment]
To be solved with common auth definitions and re-use at folder/collection level
