### ISSUE TITLE
NewMan Html Extra report is not showing the Skipped APIs Count

### ISSUE THREAD

**Issue by PraveenReddy-575** [a85/POSTMan-Chrome-Extension#12884]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

We have some set of APIs using Newman CLI and captured the Excution results in Html Extra report but this report is not showing the accurate data for the Skipped APIs.

### Steps To Reproduce

1.Run some set of APIs using Newman cli and capture in HTML Extra report.
2.The HTML Extra report is not containing the Skipped Tests count.

### Screenshots or Videos

![image](https://github.com/postmanlabs/postman-app-support/assets/170624332/9b4bef11-b708-4f00-9b20-bb98772e6d3f)
The number of requests executed in Iteration1.
![image](https://github.com/postmanlabs/postman-app-support/assets/170624332/b41d6f41-1ef3-477a-a3c4-afb00221b866)
In the above iteration some APIs are not executed which are skipped but the skipped count in the report showing as 0.

### Operating System

Windows

### Postman Version

11.0.12

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by DannyDainton** [comment]
Could you raise this in the correct repository, please?

https://github.com/DannyDainton/newman-reporter-htmlextra
