### ISSUE TITLE
Collection options not visible in the UI

### ISSUE THREAD

**Issue by nlysaght** [a85/POSTMan-Chrome-Extension#1288]
When Postman is visible the collection tool-bar options are not visible. There is no visible indication that you can add/remove collections,
![postman-01](https://cloud.githubusercontent.com/assets/9366307/8878412/b5f8c988-3222-11e5-8835-892b9a660466.PNG).

When you hover over the blank space you do get a tool tip saying "sort collections", "new collection" and if you click where those tool-tips the appropriate UI's display.

This is running on a "Windows 7"x64 desktop.

**Comment by DavePickard1234** [comment]
I have the same issue.  Also the Save icon doesn't show - neither does the drop down arrows on the buttons.  Settings and various options in top right also missing.
![image](https://cloud.githubusercontent.com/assets/13350725/9087309/c5b40c30-3b81-11e5-8320-3be4f922bb8d.png)

Running Windows 7 Enterprise SP1 - 32 bit - Postman 3.0.5 (packaged)

**Comment by numaanashraf** [comment]
@DavePickard1234 @noel-honksw-com Could you let us know your Chrome version too?

**Comment by DavePickard1234** [comment]
Yes it's Version 44.0.2403.125 m

**Comment by numaanashraf** [comment]
@DavePickard1234 we are unable to replicate this issue on our Win7/Chrome 44 setup. Give us some time to do a thorough analysis and get back to you on this.

**Comment by nlysaght** [comment]
Version of Chrome I am using is Version 44.0.2403.130 m, I also have the same issues as described by @DavePickard1234

**Comment by bug-or-feature** [comment]
Same issue. Chrome version 44.0.2403.155

**Comment by melissamahoney** [comment]
Same issue. But oddly enough I can hover where the buttons should be and get the tool tip, then I can click and have them work.
![untitled](https://cloud.githubusercontent.com/assets/14333460/9938213/4b193464-5d32-11e5-99da-dab4ddecebfa.png)
Chrome Version 45.0.2454.93 m on Windows 7

**Comment by abhijitkane** [comment]
@DavePickard1234 @only-andy @melissamahoney
Chrome has a default MIME type for svg files that's being overwritten by your system.
You can open your registry (Win-R + regedit), and navigate to HKEY_CLASSES_ROOT.svg, and edit the Content-Type key to "image/svg+xml". Once this is done, restarting Postman should show the icons.

**Comment by DavePickard1234** [comment]
@abhijitkane My registry entry was at HKEY_CURRENT_USER\Software\Classes.svg - but changing that worked for me.  Thanks!

**Comment by melissamahoney** [comment]
@abhijitkane My registry entry was where you said it was and once I made the edit, Postman displays correctly. Thank you!

**Comment by nlysaght** [comment]
Perfect, that sorted the issue for me also.
