### ISSUE TITLE
not import wsdl

### ISSUE THREAD

**Issue by ottabox002** [a85/POSTMan-Chrome-Extension#12889]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

dfdf

### Steps To Reproduce

fff

### Operating System

Windows

### Postman Version

10.12.0

### Postman Platform

Postman Web

### User Account Type

Signed In User

### Additional Context?

ff

**Comment by DannyDainton** [comment]
Closed due to the lack of information.
