### ISSUE TITLE
How to add Console messages in Html Extra Report

### ISSUE THREAD

**Issue by PraveenReddy-575** [a85/POSTMan-Chrome-Extension#12887]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

We want to print some console messages for data analysis .When we run the same collection through Newman CLI how to print these statements in the HTML Extra report.

### Describe the solution you'd like

Find a feasibility to add console.log() messages in HTML Extra Report.
![image](https://github.com/postmanlabs/postman-app-support/assets/170624332/6487f1de-223a-471f-9414-522940f3ec88)
In the Above picture we have printed messages on postman console but the same messages if we want to show in HTML extra report how to do?

**Comment by DannyDainton** [comment]
Hey @PraveenReddy-575 

This isn't the repo for that reporter as it's a community built custom reporter. The repo can be found here: https://github.com/DannyDainton/newman-reporter-htmlextra

---

The logs can be added using the `--reporter-htmlextra-logs` flag in the Newman command.

<img width="886" alt="image" src="https://github.com/postmanlabs/postman-app-support/assets/17089546/9bab4c26-7687-423e-bdf1-98bfd4fa2056">

You can also find the other avaibale flags either on the project's README file or by using the `newman-reporter-htmlextra -h` command.

<img width="997" alt="image" src="https://github.com/postmanlabs/postman-app-support/assets/17089546/e9d62218-446c-41c7-a7d1-c54d1bbeccd9">
