### ISSUE TITLE
Evaluate html forms response

### ISSUE THREAD

**Issue by apis3445** [a85/POSTMan-Chrome-Extension#12897]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

I have one request that returns and HTML form, I am using cheerio to get some input values and store as environment variables and reuse in another request. In flows I can't update any environment variable, and I tried with the path but doesn't shows the value of all input elements. The path returns: body.!doctype.html.body.form.input.0.@_value with the error when I execute that expression ended unexpectedly

### Describe the solution you'd like

Get values from html form html with cheerio is: $('input[name="myNane"]').val() or some jQuery or javascript code

**Comment by Developer354** [comment]
[]()xAI.com

**Comment by rabbah** [comment]
> In flows I can't update any environment variable

you don't need to do this in flows - you can directly wire the value you extracted from one request response into a variable for a future request.
