### ISSUE TITLE
Regress: After connection to the socket io server all events listen toggles marked as disable automatically

### ISSUE THREAD

**Issue by MaksimKiselev** [a85/POSTMan-Chrome-Extension#12899]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

I use postman to interact with socket io server.

After update Postman the listen toggles now marked as disabled after connect and modify my collections.

### Steps To Reproduce

Step to reproduce:

0) Use latest Postman
<img width="281" alt="image" src="https://github.com/postmanlabs/postman-app-support/assets/4495801/5c02c40c-0076-4d12-9750-b46a3de9545d">

1) Have socket io collection with predefined (and enabled event listeners)
<img width="851" alt="image" src="https://github.com/postmanlabs/postman-app-support/assets/4495801/bbb93d2e-97e0-47fb-93e3-4398c85182b3">

2) Press connect
<img width="860" alt="image" src="https://github.com/postmanlabs/postman-app-support/assets/4495801/12a837d7-90e1-4941-a2a6-b47c2998971e">

*BOOM* :shit: event subscribers successfully subscribed, but listen toggles unmarked and my collection modified.

Expected behaviour: connection to the server should not modify my collection.

### Operating System

macOS

### Postman Version

11.11.14

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by matej-dataqueue** [comment]
I have the same issue, macOS, M3 chip. 

App version 11.1.25

**Comment by Sigma-dev** [comment]
Same issue, Windows 11

App version v11.2.0

**Comment by ronork** [comment]
Hey @MaksimKiselev , thank you for reporting the issue.
I was able to reproduce the issue and we will provide an update once a fix has been implemented. 
cc: @parthverma1

**Comment by raunaqkapoor** [comment]
Thanks for reporting this, same issue
Postman for Mac v11.3.1

**Comment by parthverma1** [comment]
This has been fixed in latest version of Postman (v11.6.1). Feel free to open this issue if the problem recurs.
