### ISSUE TITLE
Response cookies

### ISSUE THREAD

**Issue by vasylnakvasiuk** [a85/POSTMan-Chrome-Extension#1290]
Now I see "Install the free Interceptor extension to send and receive cookies", and I must install one more app/plugin + toggle Interceptor to see cookies from response. It's not good, cause Interceptor help to catch requests with cookies and so on.

Please, show cookies without toggling, and without installation other plugins.

**Comment by abhijitkane** [comment]
This is a limitation of the Chrome platform - packaged apps cannot access cookies stored in Chrome.

**Comment by vasylnakvasiuk** [comment]
But it's not cookies in Chrome, it's cookies which I take from HTTP response ("set-cookie" header). Or not?

**Comment by abhijitkane** [comment]
Ah..sorry, I misunderstood your post. Yes, we need to improve messaging around cookies. Most users only need Cookies set in the Chrome context.

**Comment by a85** [comment]
Better cookie support is available on the OSX version now.
