### ISSUE TITLE
Requests cookies manager

### ISSUE THREAD

**Issue by vasylnakvasiuk** [a85/POSTMan-Chrome-Extension#1291]
Really hard to write/manage requests cookies using "Headers" tab, cause cookies - it's complex header.
Please, add new tab "Cookies" near "Body", "Tests", ... for managing requests cookies and when I add new cookie on this tab, it's sync and automatically appears on "Headers".

Would be nice to see this feature. :)

**Comment by a85** [comment]
This will be available in the Postman native app. Email us at help@getpostman.com to join the beta!

**Comment by a85** [comment]
Available on the OSX app at www.getpostman.com/apps
