### ISSUE TITLE
Collections are not loaded in the VSCode extension

### ISSUE THREAD

**Issue by b92c** [a85/POSTMan-Chrome-Extension#12914]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

The collections that I have in my Postman account are not loaded when logging into my account using the VSCode extension.
The collection in my test account:
![image](https://github.com/postmanlabs/postman-app-support/assets/63520341/55e586e9-f59a-4628-9c63-65d962c14c7e)

But, they are not loaded in the extension:
![image](https://github.com/postmanlabs/postman-app-support/assets/63520341/573733b4-3fab-4e23-84b4-69caa55a1297)

### Steps To Reproduce

1º Have a Postman account with collections
2º Download the Postman extension for VSCode
3º Log in to your account

### Operating System

Linux

### Postman Version

I don't now

### Postman Platform

Other

### User Account Type

Signed In User

**Comment by pankajk07** [comment]
@b92c Based on the screenshots posted in the issue, it seems you are loading different workspaces in the app and the extension. Try to change the workspace in either of them and you should be able to see your collections which are part of the selected workspace

**Comment by b92c** [comment]
@pankajk07 I edit the description issue to show the correct workspace. Check again, please.

**Comment by pankajk07** [comment]
@b92c Can you please share the logs files from the extension. You can access the logs files in the following manner
<img width="636" alt="Screenshot 2024-08-06 at 1 04 37 PM" src="https://github.com/user-attachments/assets/00ed8aac-0691-4b0c-9b8e-00b48baf9e73">

**Comment by b92c** [comment]
@pankajk07 of course bro

```bash
(2024-08-06T14:29:10.434Z) [info] [extension] Extension activation started: 1722954550431
(2024-08-06T14:29:10.562Z) [info] [extension] Extension activation completed: 1722954550562
(2024-08-06T14:29:10.562Z) [info] [extension] Extension activation took 131ms
(2024-08-06T14:30:07.500Z) [info] [extension] Extension activation started: 1722954607496
(2024-08-06T14:30:07.683Z) [info] [extension] Extension activation completed: 1722954607683
(2024-08-06T14:30:07.683Z) [info] [extension] Extension activation took 187ms
(2024-08-06T15:03:19.575Z) [info] [extension:sidebar:adapter] fetching a correct html for the view mode: {"viewMode":"sidebar"}
(2024-08-06T15:03:19.575Z) [info] [extension:htmlProvider] get sidebar HTML
(2024-08-06T15:03:19.599Z) [info] [extension:workspaceContext] Found the record in the cache
```

**Comment by b92c** [comment]
@pankajk07 hi bro, I don't know if had an update about this, but the bug has fixed. Now the collections are loaded correctly. The Postman extension version is the v1.1.0
![image](https://github.com/user-attachments/assets/e97175cd-3a4a-49fd-8cb9-6a1d2bbdebe3)

**Comment by pankajk07** [comment]
@b92c Awesome. I'll go ahead and close the issue. Feel free to open a new one if the problem reoccurs.
