### ISSUE TITLE
Postman not working on latest VSCode Insiders: command 'postman-for-vscode.log.open' not found

### ISSUE THREAD

**Issue by ryan6416** [a85/POSTMan-Chrome-Extension#12923]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

After updating VSCode Insiders to version 1.91.0-insider, Postman extension stopped working, displaying error message: command 'postman-for-vscode.log.open' not found. Before update, Postman was functioning correctly. issue does not occur on regular VSCode version 1.89.1, where Postman works fine.

### Steps To Reproduce

1. Update VSCode Insiders to version 1.91.0-insider.
2. Open VSCode Insiders.
3. Attempt to use Postman extension.
4. Observe error message: command 'postman-for-vscode.log.open' not found.

### Screenshots or Videos

<img width="343" alt="image" src="https://github.com/postmanlabs/postman-app-support/assets/12979345/9fbb03ca-5e2f-47c9-965e-5ddcbe980a97">

### Operating System

macOS

### Postman Version

1.0.3

### Postman Platform

Postman App

### User Account Type

Signed In User

### Additional Context?

macOS 13.5 (Darwin arm64 23.5.0)

**Comment by ryan6416** [comment]
Link to issue created in vscode: https://github.com/microsoft/vscode/issues/214584

**Comment by Ballonjay** [comment]
Please I want a my refund of 5k I made to paystack yesterday because this are all scam

**Comment by Ballonjay** [comment]
9131254003 Ikande eriba desting opay 
Scammers everywhere

**Comment by Ballonjay** [comment]
![Screenshot_20240608-003621_Gallery](https://github.com/postmanlabs/postman-app-support/assets/172086657/3d74b97c-34ce-4be8-b49d-711972427fbe)

**Comment by pankajk07** [comment]
@ryan6416 The underlying issue is due to some recent code changes in the VS Code Insider build. We have created a corresponding [GH issue](https://github.com/microsoft/vscode/issues/214584) in the VS Code repo, and working with the team to fix this issue.

**Comment by pankajk07** [comment]
@ryan6416 The issue is fixed by the VS Code team and the extension works well in the latest Insider Build. Please update your Insider version and try it out.
