### ISSUE TITLE
Postman Desktop app sometimes does not show Menu items

### ISSUE THREAD

**Issue by sameerpremji** [a85/POSTMan-Chrome-Extension#12924]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Hello,

Please see the screenshot attached.

Every now and then, unpredictably, I'll see menu items disappear. If I re-launch the Desktop app, it may or may not appear. It's very erratic and unpredictable.

I have noticed that it occurs often times (not always true) as soon as I update the Desktop app to a newer version. The menu items won't appear until I have to close the app and relaunch it several times. It's like a lottery to get lucky suddenly.

Please fix this bug.

Thanks!
![Screenshot_000140](https://github.com/postmanlabs/postman-app-support/assets/56898590/8a7bdbee-5c79-449a-bd44-8fb8d69d0a9b)

### Steps To Reproduce

1. Launch the latest version of Postman Desktop app on Windows 10 Enterprise (version 22H2)
2. Browse to the menu as shown in the screenshot attached.
![Screenshot_000140](https://github.com/postmanlabs/postman-app-support/assets/56898590/6d574736-b14a-46df-b440-11ce7d8e9ae1)

### Screenshots or Videos

![Screenshot_000141](https://github.com/postmanlabs/postman-app-support/assets/56898590/5ac3136f-424e-4cf3-8ede-b9c18975c4b8)

### Operating System

Windows

### Postman Version

11.1.14

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by dsanders11** [comment]
Duplicate of #12620
