### ISSUE TITLE
postman vs code extension error:   Could not send request Error: Invalid IP address: undefined

### ISSUE THREAD

**Issue by angheloDev** [a85/POSTMan-Chrome-Extension#12928]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

i did everything but still this error persist:

Could not send request
Error: Invalid IP address: undefined

*but it works on my postman standalone app

### Steps To Reproduce

![Screenshot 2024-06-11 024319](https://github.com/postmanlabs/postman-app-support/assets/120046334/1daa2353-3754-403f-815f-12074aa5bcbf)

### Screenshots or Videos

![Screenshot (224)](https://github.com/postmanlabs/postman-app-support/assets/120046334/46f26144-9ec8-4dca-b5bb-1bfcad04b24c)
![Screenshot 2024-06-11 024319](https://github.com/postmanlabs/postman-app-support/assets/120046334/69b80e1f-a096-47ee-a87b-c3c95ffa85e5)

### Operating System

Windows

### Postman Version

v1.0.3

### Postman Platform

Other

### User Account Type

Signed In User

### Additional Context?

what should i do?

**Comment by projetfcjeff** [comment]
Hi. 

I got the same error yesterday. I found a workaround on reddit : [(https://www.reddit.com/r/learnprogramming/comments/1d9jocu/comment/l7i6jh4/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button)]

Assume you are using port 3000, replace http://localhost:3000/ by **http://127.0.0.1:3000/** then it should work (it worked fine for me :-)).

However I have no clue why such a thing happened. Hope it will help.

**Comment by angheloDev** [comment]
oh a loopback address instead of putting localhost

thanks mate that really helped.

**Comment by angheloDev** [comment]
> Hi.
> 
> I got the same error yesterday. I found a workaround on reddit : [(https://www.reddit.com/r/learnprogramming/comments/1d9jocu/comment/l7i6jh4/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button)]
> 
> Assume you are using port 3000, replace http://localhost:3000/ by **http://127.0.0.1:3000/** then it should work (it worked fine for me :-)).
> 
> However I have no clue why such a thing happened. Hope it will help.

oh a loopback address instead of putting localhost

thanks mate this really helped.

**Comment by codewithleader** [comment]
> Hi.
> 
> I got the same error yesterday. I found a workaround on reddit : [(https://www.reddit.com/r/learnprogramming/comments/1d9jocu/comment/l7i6jh4/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button)]
> 
> Assume you are using port 3000, replace http://localhost:3000/ by **http://127.0.0.1:3000/** then it should work (it worked fine for me :-)).
> 
> However I have no clue why such a thing happened. Hope it will help.

Thank!! 😱

**Comment by Rohit2288** [comment]
This solution helped me too , but can anyone tell why such a thing happened.

**Comment by DevSatvik** [comment]
Ah, this solution helped me as well. Not sure why it happened though. I was recently checking with just `localhost` and it seemed to work fine. Thanks :)

**Comment by gymdoorfit** [comment]
Awesome, so idiot to not to try changing localhost to 127.0.0.1 before. But it's working.

**Comment by pankajk07** [comment]
We have identified the issue and it will be fixed in the upcoming release of the extension. Please follow this ticket for the updates regarding this issue https://github.com/postmanlabs/postman-app-support/issues/12939

**Comment by SixtusOnyedibe** [comment]
I almost lost it!. Thanks man!

**Comment by khoaHyh** [comment]
This helped me as well, thanks!!

**Comment by devraj27dec** [comment]
Thanks man this works for me too 🙏

**Comment by temorgan** [comment]
Hi all, unfortunately I'm still encountering the 'invalid ip' persistent issue with my Postman setup when testing an Azure Function app. I'm on a Windows 10 OS with Postman Version: v7.32.1and running locally with the function endpoint at http://127.0.0.1:7071/normalize_excel_data The environment variables are set correctly (verified via command prompt) but even with changing the Postman request URL to http://127.0.0.1:7071/normalize_excel_data and setting the Content-Type header to application/json as well as adjusting tests to expect a 200 status code, JSON content type, and valid JSON response, I'm receiving a response status code as 400 as well as a Content-Type mismatch (application/json vs. expected text/xml). The Schema validation errors indicating null where an object is expected. I'm new to VS Code and have a basic understanding of Python but this is new and was never an issue. I had this running seamlessly before but now I'm stuck with this blasted invalid IP address.

**Comment by ayobamiseun** [comment]
still facing this issue` _macbook ventura_ ``_vscode 1.90.2_`

**Comment by pankajk07** [comment]
@temorgan Can you please clarify if you are using the Postman app or the Postman's VSCode extension? Based on the Postman version provided, it seems you are using a desktop app. If that is not the case, please provide us with the details about the VS Code version and Postman's VS Code extension version.

If you are using the desktop app and facing the issue, please create a new issue.

**Comment by pankajk07** [comment]
@ayobamiseun We recently published a new version of the extension (`v1.1.0`), which has the fix for this issue. Please update the extension and try it out. If the issue persists, feel free to create a new issue.
