### ISSUE TITLE
Secure Websocket connect yields error "self signed certificate"

### ISSUE THREAD

**Issue by TobiasUhmannVoss** [a85/POSTMan-Chrome-Extension#12927]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

I am trying to connect to a secure Websocket server on my ESP32 SoC microcontroller. When connecting, I get the error "self signed certificate" in Postman although I have disabled SSL certificate verification in the settings. Thus, I would expect that the server is not authenticated and that the self signed certificate shouldn't be a problem. Furthermore, I enabled CA certificates in the settings and added the server certificate as PEM file. But even then I get the error. I can connect to a non-secured Websocket server and successfully used the same certificate to connect to an HTTPS server on the ESP32.

When using a certificate A on the server that I signed with a self signed certificate B, and adding the self signed certificate B to Postman's CA certificates, the error message changes to "unable to verify the first certificate". When I check the server certificate with OpenSSL I get an "Verification: OK": `openssl s_client -CAfile ~/my_root_cert_b.crt -showcerts 192.168.0.59:443`

The server logs don't indicate any error:

```
I (11123) esp_https_server: performing session handshake
I (12083) wss_echo_server: New client connected 57
I (12243) wss_echo_server: Client disconnected 57
```

- Server Code: https://github.com/espressif/esp-idf/tree/master/examples/protocols/https_server/wss_server
- Server Certificate: https://github.com/espressif/esp-idf/tree/master/examples/protocols/https_server/wss_server/main/certs

### Steps To Reproduce

1. Run the ESP32 wss_server example: https://github.com/espressif/esp-idf/tree/master/examples/protocols/https_server/wss_server
2. Disable SSL certificate verification in Postman
3. Import the PEM server certificate into Postman: https://github.com/espressif/esp-idf/tree/master/examples/protocols/https_server/wss_server/main/certs
4. Connect to wss://192.168.0.59/ws (replace IP) in Postman

### Screenshots or Videos

![image](https://github.com/postmanlabs/postman-app-support/assets/132457815/7ea364ea-c338-4199-b51d-52ce7d5dd7e7)

### Operating System

Windows

### Postman Version

11.1.14

### Postman Platform

Postman App

### User Account Type

Signed Out User

**Comment by parthverma1** [comment]
Hi @TobiasUhmannVoss,

I understand that you've been having trouble using self-signed certificates with Websocket Servers.

The issue description mentions that you are using Postman as a signed out user. Signed out users only have access to the lightweight client, which given its light weight nature doesn't include support for mTLS, custom SSL with websockets. For more power users such as you, the signed in version provides a ton of added features including support for mTLS and custom SSL when using websockets.

I would recommend signing into the app and then try making the request. Upon configuring the certificates that you've provided on a local nginx + websocket server, I was able to successfully connect using the signed in version of the app.

Do update the ticket if this solves your issue.

Thanks

**Comment by TobiasUhmannVoss** [comment]
Thanks! Signing in made it work 👍 I'd adjust the error message though, e.g. "Error: Sign in to use self signed certificate"
