### ISSUE TITLE
about the environments

### ISSUE THREAD

**Issue by mzychaco** [a85/POSTMan-Chrome-Extension#1293]
I have set up a special environments for my request,but it seems to do nothing .
why?
am I making wrong setting?if so,please tell me how to set up the environment correctly?
my email is : chacomo@163.com

**Comment by alexjv89** [comment]
Hi @mzychaco,

Here is the documentation page for environments - https://www.getpostman.com/docs/environments . 
Can you go thought that and let us know if you are still facing issues?
