### ISSUE TITLE
gRPC Request returns Error: Message violates its Protobuf type definition

### ISSUE THREAD

**Issue by Anand911-verteil** [a85/POSTMan-Chrome-Extension#12938]
### Is there an existing issue for this?

- [x] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

The following error occurs when attempting to make gRPC call in Postman after upgrading to v11 (previously on v10).

**Error Message:**
Error: Message violates its Protobuf type definition

Calls to the respective services is not made it throws this error with no other information, verified the types of protobuf used postman was interpreting one of the `Map` fields to as `repeated` and when casting this to as array it worked which is not the actual behaviour of the field in our schema. The error is being logged at the request renderer-requester.log

The issue persists with Postman agent as well.

### Steps To Reproduce

1. Open a gRPC Request in postman
2. Load the required API Service
3. Make sure that the schema has some map fields associated with protobuf schema
4. Invoke the gRPC Request

### Screenshots or Videos

![image](https://github.com/postmanlabs/postman-app-support/assets/151899395/ffd35216-31f6-41bc-894b-83f6cda02c5b)

### Operating System

Linux

### Postman Version

11.2.1

### Postman Platform

Both

### User Account Type

Signed In User

**Comment by appurva21** [comment]
Hey @Anand911-verteil! Thanks for the detailed steps. Unfortunately, I can't see this on our end using the proto below. Could you share a scaled-down version of your proto to help us further investigate this?

```
syntax = "proto2";

package hello;

service HelloService {
  rpc SayHello(HelloRequest) returns (HelloResponse);
}

message HelloRequest {
  required string greeting = 1;
  map<string, int32> data = 2;
}

message HelloResponse {
  required string reply = 1;
}
```

**Comment by Anand911-verteil** [comment]
Hi @appurva21,

Thank you for reaching out. Unfortunately, I am unable to share the proto schema as it is confidential to our company. However, I can provide some more details or assist in any other way that might help you troubleshoot the issue. Please let me know how else I can assist you.

**Comment by jonsor** [comment]
Hi @appurva21
We are experiencing the samme issue.
Tested for versions
- `v11.1.25`
- `v11.2.1`

Example proto:
```proto
rpc DoFoo(FooRequest) returns (FooResponse);

message FooResponse {
    string response = 1;
}

message FooRequest {

    string this_works = 1;
    map<string, string> this_causes_the_error = 5;
}
```

Example request body in postman:
```json
{
    "this_causes_the_error": {
        "test1": "test1",
        "test2": "test2"
    },
    "this_works": "test"
}
```

Error message:
`Error: Message violates its Protobuf type definition`

**Comment by appurva21** [comment]
@jonsor Thanks for the details, I can reproduce this now. We'll update this thread once the fix is out.

**Comment by Anand911-verteil** [comment]
@jonsor Thank you for providing the sample protos. 
In my case, the request format includes a nested message within a map:
```proto
rpc DoFoo(FooRequest) returns (FooResponse);

message FooResponse {
    string response = 1;
}

message FooRequest {
    string this_works = 1;
    map<string, otherMessage> this_causes_the_error = 5;
}

message otherMessage {
   string someText = 1;
}
```

**Comment by nh0znoisung** [comment]
cec

**Comment by sigurd-cp** [comment]
We also experienced the same issue (v11.6.1 mac)
```
message Foo{
   map<int64, int32> mymap = 1;
}
```

> Error: schema is invalid: data/definitions/.Foo/properties/mymap/oneOf/1/items/properties/key/type must be equal to one of the allowed values,

**Comment by appurva21** [comment]
Hey @sigurd-cp!

To help us investigate this, could you provide the below details:
1. When are you running into this error - on loading methods via server reflection / proto file or while invoking the method? (A screenshot would be helpful)
2. If this is while invoking the method, what does your message body look like?
3. What runtime are you using for the gRPC server - Node, Java, Go, etc.?

**Comment by sigurd-cp** [comment]
We are using akka grpc server with server reflection.
The loading of the definition works properly, invoking of other RPCs works but only when this map is used in the request message then this error occurs.

**Comment by appurva21** [comment]
We have rolled out a fix for this with the latest version of Postman (v11.8.0). Please restart the app to get the update.

---

@sigurd-cp We have also identified and fixed the issue you faced with map fields having non-string keys in the latest version. 

Feel free to re-open this issue if the problem recurs.
