### ISSUE TITLE
Default/convert to a POST request when adding a body

### ISSUE THREAD

**Issue by calebmeyer** [a85/POSTMan-Chrome-Extension#12935]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

- Create a new request
- Add a body, like a raw Application/JSON body or a GraphQL body
- Forget to change to POST for the http method
- encounter strange errors from your server

### Describe the solution you'd like

When you add a body, either automatically change to POST, or prompt the user to ask if they want to change to POST/PUT

### Describe alternatives you've considered

I don't know of any other means of solving this, except maybe being able to change the default request method

### Additional context

<img width="998" alt="image" src="https://github.com/postmanlabs/postman-app-support/assets/3342777/08a7e7ab-933a-4b58-8dff-7bef77bc01ad">

**Comment by giridharvc7** [comment]
We do switch HTTP method to post if you start with an empty request and switch to graphQL body type. 

https://github.com/postmanlabs/postman-app-support/assets/1040583/dba32287-e078-48db-9da5-46b62b73c997

or you can use the new graphQL client in Postman


https://github.com/postmanlabs/postman-app-support/assets/1040583/ace503e6-5dfe-436e-b01b-5af257e937aa
