### ISSUE TITLE
postman Icon not visible in Chrom eAPP grid

### ISSUE THREAD

**Issue by roopaeyes** [a85/POSTMan-Chrome-Extension#1294]
Hello,

I have installed Postman App from https://chrome.google.com/webstore/detail/postman,
the website says installed.
But i am unable to see the same icon in Google Chrome App Grid.
Kindly help

Thanks in Advance,

Roopa

**Comment by abhijitkane** [comment]
The link you posted is that for the Chrome Webstore homepage. The current version of Postman is https://chrome.google.com/webstore/detail/postman-rest-client-packa/fhbjgbiflinjbdggehcddcbncdddomop?hl=en, and this has a new icon.
