### ISSUE TITLE
We do not want to sign in before using the app!

### ISSUE THREAD

**Issue by NatiTM** [a85/POSTMan-Chrome-Extension#12946]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

For those of you who are having trouble with postman I found this article which is very useful article in the following link 

https://testfully.io/blog/top-5-postman-alternatives/

Comparison Table
To help you make better decisions faster, We have put together a list of features and their availability. You can use this table to decide what matters for you most and pick your Postman alternative. Once you have a shortlist of tools, you can read the detailed review of each tool below.

Feature | Postman | Testfully | Insomnia | Hoppscotch | Apidog | Thunder Client | Postcode | Rapid API | Firecamp | TestMace | Nightingale | API Tester | curlx | HTTPie | Yaak | RecipeUI
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
Platform | Web & Desktop | Web | Desktop | Web | Web & Desktop | VSCode Extension | VSCode Extension | Mac OS | Web | Desktop | Desktop (Windows) | iOS, Android, Mac OS | Terminal | Web, Desktop, CLI | Desktop | Web & Desktop
Free Plan | Yes | No | Yes | Yes | Yes | Yes | Yes | Yes | Yes | Yes | Yes | Yes | Yes | Yes | Yes | Yes
Premium Plan | Yes | Yes | Yes | Yes | Yes | Yes | No | Yes | Yes | Yes | No | No | No | No | No | No
Coding Skills Required | Yes | No | Yes | Yes | No | No | No | No | Yes | No | No | No | No | No | No | Yes
Restful API support | Yes | Yes | Yes | Yes | Yes | Yes | Yes | Yes | Yes | Yes | Yes | Yes | Yes | Yes | Yes | Yes
GraphQL API support | Yes | Yes | Yes | Yes | Yes | Yes | Yes | Yes | Yes | Yes | No | Yes | Yes | Yes | Yes | No
Soap API support | Yes | No | Yes | No | No | Yes | No | Yes | No | No | No | Yes | Yes | No | Yes | No
Request chaining | No | Yes | No | No | No | No | No | No | No | Yes | Yes | No | No | No | No | No
Environments | Yes | Yes | Yes | Yes | Yes | Yes | No | Yes | Yes | Yes | Yes | No | No | No | Yes | No
Random Data | Yes | Yes | Yes | No | Yes | No | No | Yes | No | Yes | Yes | No | No | No | No | No
API Testing | Yes | Yes | Yes | Yes | Yes | Yes | No | No | Yes | Yes | No | No | No | No | No | No
API Monitoring | Yes | Yes | No | No | No | No | No | No | No | No | No | No | No | No | No | No
CLI | Yes | Yes | Yes | No | Yes | No | No | No | No | Yes | No | No | Yes | Yes | No | Yes
Team Collaboration | Yes | Yes | Yes | No | Yes | No | No | Yes |   |   |   |   |   |   |   |  

</figure><p style="margin:0pt 0pt 0.0001pt;">&nbsp;</p>

### Steps To Reproduce

Install the newer version/s of PostMan

### Operating System

Windows

### Postman Version

newer versions

### Postman Platform

Both

### User Account Type

Signed Out User

**Comment by DannyDainton** [comment]
You can use Postman without signing in to the platform, to build and test your endpoints.

https://learning.postman.com/docs/getting-started/basics/using-api-client/
