### ISSUE TITLE
No Accept HTTP Header generated in code generator

### ISSUE THREAD

**Issue by remkohdev** [a85/POSTMan-Chrome-Extension#1295]
When I set the Accept header in the body tab to text from application/json default, and then look at the sample code via the code generator, the HTTP Header for Accept is not generated/included. This will make the code fail for some API server settings that require the Accept header.

![screenshot_postman_bug_no_accept-header](https://cloud.githubusercontent.com/assets/1062709/8905904/1f77c5be-3438-11e5-8d79-4d868d7cee03.png)

**Comment by abhijitkane** [comment]
I'm not able to reproduce this. The Accept header is reflected in the HTTP preview. 

I'm not sure what you mean by  'Accept header in the body tab'. Headers have a separate tab.

What version of Postman are you running? Are there any errors in the console - http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/?
