### ISSUE TITLE
Variables are not replaced for WS messages

### ISSUE THREAD

**Issue by festo** [a85/POSTMan-Chrome-Extension#12968]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

I just updated the Postman App to `11.2.1` version and it seems it has a breaking change.

Variables are not replaced for websocket messages. I tried it with environment variables and built-in ones like `{{$guid}}`

### Steps To Reproduce

Open a new WS connection and send a message with a variable. Eg:
```json
{
    "test": "{{$guid}}"
}
```

### Screenshots or Videos

![Screenshot 2024-06-27 at 11 59 47](https://github.com/postmanlabs/postman-app-support/assets/1818211/49720828-0e5e-42fb-8a73-1d8ed74d23d7)

### Operating System

macOS

### Postman Version

11.2.1

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by ronork** [comment]
Hey @festo, thank you for reporting the issue.
I was able to reproduce the issue and will provide an update once a fix has been implemented.

**Comment by parthverma1** [comment]
Hey @festo 

I identified the issue and made a quick fix for it. Can you try closing the current tab and re-opening the request. The issue should be resolved.

Thanks

**Comment by festo** [comment]
@parthverma1 I can confirm it works

**Comment by piotr-cz** [comment]
Same problem is with GraphQL Variables
