### ISSUE TITLE
Link Environments with Vault for Context-Aware Secret Management

### ISSUE THREAD

**Issue by christopher-nash** [a85/POSTMan-Chrome-Extension#12962]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

Background: I have defined an Environment for each of our applications' deployment lanes: Production, Beta, Test. I often flip between them throughout the day. After authenticating to a deployment lane, I have a session token which I store as a variable `session_token` within the relevant environment. These sessions only work for one deployed lane (you can't use a token from Beta in Production, etc). It makes it convenient to always reference `{{session_id}}` in a stored request in my collection.

I am excited by the new "[Postman Vault](https://learning.postman.com/docs/sending-requests/postman-vault/postman-vault-secrets/)" recently introduced, but it has no concept / no link between then selected Environment and the Vault. I'm unable to replicate the same type of thing with these session tokens inside it in a convenient way.

-------------

A similar usecase that is easy to imagine might be API keys for some system where a Beta and Production environment exist and have different key, yet the stored request is convenient to just use `{{api_key}}` instead of splitting it out.

-------------

### Describe the solution you'd like

The Environment and the Vault need to be 'linked' somehow.

1) One solution would be to incorporate a "Vault" into each Environment. A portion that is never, ever synced no matter whether you put an Initial or a Current value. Some might find that risky though since its the same UI as values which are sometimes synced.

2) Another would be to have separate vaults that have a dropdown or something where you select the environment where this vault is relevant.

3) A third solution would be to have Vault key names able to be used as Environment variable values. (See "Possible workaround 1" section below for how that might work). It gives the flexibility that values can be used however makes sense by letting Environments reference Vault values. Given the flexibility of this option, although it requires a little more work on a developer's part to set things up by hand, this may be the best option.

-------------

### Describe alternatives you've considered

Possible workaround 1:

I could define 3 vault value: `{{vault:session_id_prod}}`, `{{vault:session_id_beta}}`, `{{vault:session_id_test}}` and manage their values separate like that in a single pane. However, then using them becomes cumbersome.

I thought about the possibility of referencing them inside an Environment Variable. 
* So in my Production environment I would set `{{session_id}` to a value of `{{vault:session_id_prod}}`. 
* Then in my Beta I would set `{{session_id}}` to be  `{{vault:session_id_beta}}`.
* And Test set `{{session_id}}` to `{{vault:session_id_test}}` .

That seemed like a cumbersome, but workable solution. However, it doesn't look like Environment values can reference other Environment or Vault values, so its not possible.

------------------------

Possible workaround 2:

Set Auth header variables on the stored request which you _manually_ toggle on and off. So for a particular request you would have 3 Auth headers, 2 of which are toggled off. The "bulk edit" version of those headers would look like this:
```
Authorization:Bearer {{valut:session_id_prod}}
//Authorization:Bearer {{valut:session_id_beta}}
//Authorization:Bearer {{valut:session_id_test}}
```
This would work, but a developer would have to remember to _manually_ toggle the proper one on for _each request_ they're working on, which gets real cumbersome real fast when dealing with a bunch of different requests... So I don't find this as very acceptable alternative.

-------------

### Additional context

There are similar related requests, but each had slightly different solutions presented which made me decide to make a new request instead:
* https://github.com/postmanlabs/postman-app-support/issues/12707
* https://github.com/postmanlabs/postman-app-support/issues/12864
  * In particular this comment is asking for this exact request: https://github.com/postmanlabs/postman-app-support/issues/12864#issuecomment-2139125347
* https://github.com/postmanlabs/postman-app-support/issues/11330

---------------

I also have a variable set in each Environment which changes the base URL. For example, a saved request might be against "https://{{lane}}.google.com" where `{{lane}}` gets substituted with `www` for Prod, `beta` for Beta, `test-alpha` for Test. This is part of what makes my usecase work so well not needing to alter the variable name for session each time.

**Comment by jonathanhaviv** [comment]
Hi @christopher-nash, thank you for such a thoughtful and thorough feature request. I would love to schedule a call with you to understand better how you're using Postman and help us find the best possible solution to your challenge. I'm sharing my [calendar link here](https://calendly.com/jonathan-haviv-postman/call) and feel free to book a time that works best for you. If none of these times work for you, let me know, and we can try to find something that works! Thank you!

**Comment by jonathanhaviv** [comment]
Hi @christopher-nash, I just wanted to follow up with a workaround that we hope helps with your workflow. 

https://github.com/postmanlabs/postman-app-support/assets/53003885/6d47d37f-1ee5-4a22-acbd-e22812a86412

We know that there are still improvements we can make to this experience and would still love to be able to [book time](https://calendly.com/jonathan-haviv-postman/call) with you for a call so we can continue to improve upon the experience working with vault and environments.

**Comment by christopher-nash** [comment]
@jonathanhaviv Your video describes my `Possible workaround 1:` exactly, but when I tested it locally previously it didn't seem to work. I'll re-test this afternoon and see if I made a mistake somewhere when I was trying it. If that works then, although its a little clunky, that will be good enough to address my usecase need.

**Comment by christopher-nash** [comment]
@jonathanhaviv Retested and it did work.

I suspect in my initial testing that I forgot to click the `Save` button at the top of the Postman Vault: 
![image](https://github.com/postmanlabs/postman-app-support/assets/15619873/d4a2e6ee-e07e-43eb-93f6-7f2b429c1c3e)

Its probably because I'm used to the way you Edit environment Current values and it saves automatically once you leave the field:
![image](https://github.com/postmanlabs/postman-app-support/assets/15619873/467a64e4-70e8-477d-92a7-17c31900dcce)

**Comment by jonathanhaviv** [comment]
Hi @christopher-nash glad it is working, right now. Thanks for the feedback and want to extend the offer to [have a call](https://calendly.com/jonathan-haviv-postman/call) to talk about how we can improve the experience. I'm going to close this ticket for now, but feel free to re-open it if you need anything else.

**Comment by ghost** [comment]
Awsome that this works now, do you have any info on when it will be prossible to use environment variables in a pre-request script? Right now the resolve to the {{vault:ref}} rather than the actual value which makes the impossible to use in a script

**Comment by GovindKarthikeyan** [comment]
@jonathanhaviv But the environment variable not resolved when use like pm.environment.get() api, is it a bug still ?

**Comment by jonathanhaviv** [comment]
@GovindKarthikeyan Could you share an example script of what you're trying to do? If I understand correctly, would it be possible to get the resolved vault variable using pm.environment.get()? pm.environment is used to get the variable from the environment and vault exists separately from your environments.

**Comment by jonathanhaviv** [comment]
@runningmanGBG, I don't have any updates on using vault variables with scripts right now. Will let the team know and once we do have updates will make sure to share them with you. Thank you for the feedback and input!

**Comment by ghost** [comment]
@jonathanhaviv thanks, looking forward to being able to use this in scripts as well since that is the only way I have figured out to solve secure and automatic tokens with Azure

**Comment by GovindKarthikeyan** [comment]
> @GovindKarthikeyan Could you share an example script of what you're trying to do? If I understand correctly, would it be possible to get the resolved vault variable using pm.environment.get()? pm.environment is used to get the variable from the environment and vault exists separately from your environments.

@jonathanhaviv Please find below the example script to auto refresh the token when expired and while getting 401 status back from all request from a folder. This is failing to grab the value from vault (I tried both environment and global both not working)
![image](https://github.com/user-attachments/assets/14a328c9-fa62-4c95-b0d7-1bbf09b7a62c)

**Comment by jonathanhaviv** [comment]
@GovindKarthikeyan @runningmanGBG I have an exciting update! In Postman 11.9 which is releasing this week we have added support for vault variables in scripts.

If you open vault and click on settings:
![image](https://github.com/user-attachments/assets/2baa5bbe-6c49-4092-abce-e86f0998ed9d)

You can toggle on support in scripts:
![image](https://github.com/user-attachments/assets/00f3bc6c-6351-4b79-a8ae-bbd3a1815e9b)

In scripts you can use `pm.vault.get` to access the vault variable you set.
![image](https://github.com/user-attachments/assets/f95c6dea-89b8-4e90-bf05-cf23ec5ea564)

Hope this helps!

**Comment by GovindKarthikeyan** [comment]
Great, Thanks for the quick fix @jonathanhaviv you guys rocks :)

**Comment by ghost** [comment]
@jonathanhaviv Absolutely fabulous, I will update my script and finally have this automated 🤩

**Comment by jimmythomson** [comment]
Hi @jonathanhaviv - while I appreciate that there are workarounds available, this still looks to be an area that could be refined. I have just converted several Postman collections to use Vault due to client requirements, but am now finding myself unable to easily utilise environment specific Vault data seamlessly in the same way as I could with standard environment variable data.

I'm grateful for the speed at which the Postman team have released the Vault functionality, so please don't take this as a complaint. I'd just like to flag this as being an additional piece of functionality that would really ease our transition to using Vault.

Thanks.

**Comment by jimmythomson** [comment]
To elaborate on my previous message, I'm working with Local, Dev, Test, Pre-prod and Prod environments. I have a request that will create an anonymous session for example, which returns me a JWT and a refresh token. Both of these need to be stored in Vault. Doing so as things stand require me to distinguish the Vault variables between the environments in a similar way to what's been described above. The most straightforward way for me to do this is to create a global variable that acts as an identifier for the environment, e.g. `local`, `dev`, `test` etc. Then when I set the Vault secret in my script, I can generate the Vault variable name specific to the active environment. Again, all perfectly possible, just a little more unnatural than I'd like. 

The use of the globals as a proxy for the Vault data then adds a level of indirection that makes the experience more difficult to understand for anyone not familiar with the workarounds put in place.

**Comment by Pranav2612000** [comment]
Please be aware that Postman app V11.12 release includes breaking changes related to Postman Vault API in scripts that require updates to your code.

**Key Breaking Changes:**
- Now we only supports the following methods for vault secrets:
    - `pm.vault.get("secretKey")`
    - `pm.vault.set("secretKey","newValue")`
    - `pm.vault.unset("secretKey)`
- You must add the `await` operator before each pm.vault method. Without the operator, the method won't run.
- We no longer supports using pm.variables to access or manipulate vault secrets. You must use pm.vault.
Example:
```
console.log(await pm.vault.get("secretKey"));
await pm.vault.set("secretKey", "newValue");
await pm.vault.unset("secretKey");
```

We apologize for any inconvenience these changes may cause. We believe that the benefits of these updates will far outweigh the initial effort required to migrate.

**Comment by GovindKarthikeyan** [comment]
Thanks for the update @Pranav2612000 Now with the new release, below logic breaks

const grandType = await pm.vault.get("grandType"); // It's working

const clientId = pm.variables.replaceIn(pm.environment.get("cdClientId")); // Breaking with displaying {{vault:cdClientId}}
const clientSecret = pm.variables.replaceIn(pm.environment.get("cdClientSecret")); // Breaking with displaying {{vault:cdClientSecretLiveDev}}
console.log(grandType, clientId, clientSecret); // "client_credentials" "{{vault:cdClientId}}" "{{vault:cdClientSecretLiveDev}}"

Please let us know how to get around this breaking change, Thanks

**Comment by Pranav2612000** [comment]
Thank you for reaching out @GovindKarthikeyan . We needed to remove vault access in `pm.variables` due to security considerations.
From what you mentioned, my understanding is that the environment variable "cdClientId"  has the value `{{vault:cdClientId}}` which is not being resolved. A way to fix this could be to add the vault secrets to `pm.variables` before calling `pm.variables.replaceIn` .


For instance,
```
const grandType = await pm.vault.get("grandType");

// Add the necessary vault secrets to variables
pm.variables.set("vault:cdClientId", await pm.vault.get("cdClientId"));
pm.variables.set("vault:cdClientSecretLiveDev", await pm.vault.get("cdClientSecretLiveDev"));

const clientId = pm.variables.replaceIn(pm.environment.get("cdClientId"));
const clientSecret = pm.variables.replaceIn(pm.environment.get("cdClientSecret"));
console.log(grandType, clientId, clientSecret);
```
