### ISSUE TITLE
Unicode issue with code editor

### ISSUE THREAD

**Issue by levani** [a85/POSTMan-Chrome-Extension#1296]
There is a weird behaviour when typing some text with unicode in text editor. Please see the attached screencast.

http://cl.ly/c4Lz?_ga=1.188070126.775917716.1438002820

**Comment by abhijitkane** [comment]
Seems to be an underlying issue with ace editor - http://ace.c9.io/#nav=about
Will investigate

**Comment by levani** [comment]
Thanks. I have used ace editor several times in different apps but never noticed similar issue anywhere else.

**Comment by sdnts** [comment]
Is this still happening in the latest Postman app (v4.8)?
Feel free to reopen if it is.
