### ISSUE TITLE
Workspace updates: very laggy text entry UI

### ISSUE THREAD

**Issue by mhmacleod** [a85/POSTMan-Chrome-Extension#12970]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

The new Workspace Updates tab is incredibly buggy when interacting with an Update's Title or description: any text entered can lag for up to 10secs before registering into the text prompts.
Interacting with the dropdowns, change summary etc is somewhat better.

### Steps To Reproduce

1. Open the Updates tab
2. Type text into an update's Title or description
3. Lag ensues, if long string of text is entered, they will all come in 10secs later

### Screenshots or Videos

Can't really post one as it wouldn't capture my physical inputs on my keyboard

### Operating System

Windows

### Postman Version

11.2.26

### Postman Platform

Postman App

### User Account Type

Signed In User

### Additional Context?

My team's workspace is rather large: could this be a cause?
Workspace is "Vessel Performance", user account email "ngohborong@gmail.com"

**Comment by Diuda** [comment]
Thanks a lot @mhmacleod 

We are looking into this. We will provide more updates shortly

**Comment by Diuda** [comment]
@mhmacleod We have fixed this in our latest release. Can you please help us validate this on the latest version that this issue does not persist for you

**Comment by Diuda** [comment]
Closing this issue. Feel free to open this if you are still experiencing the laggy behaviour for workspace updates 😄
