### ISSUE TITLE
Using restricted headers in production

### ISSUE THREAD

**Issue by stevenkader** [a85/POSTMan-Chrome-Extension#1297]
Just a quick question.  I have successfully generated POST using restricted headers and everything is working great with the interceptor.

Question is how is it possible for me to move this to production.  I exported code and added to my chrome app with no success.  Is it possible?

Thx

**Comment by abhijitkane** [comment]
I'm not sure what you mean. If you have a request that needs restricted headers, you'll always need to use the Interceptor to make that request. What code dd you export?

**Comment by stevenkader** [comment]
Thanks for the quick response.
I exported javascript XHR and added to my Chome App... .......I have the interceptor installed but not sure how my app knows to use the interceptor (in Postman we have the switch).  Is there anyway to integrate the Interceptor into my own app (not sure how it actually works).  Just trying to find the cleanest way to have my Chrome App use different User-Agent (mimic iPhone device).  Thanks.

**Comment by abhijitkane** [comment]
The Interceptor will only work with Postman. The Interceptor is a chrome extension (these have some permissions that chrome apps don't), and can send some restricted headers that Chrome apps cannot.

If you want to send the User-Agent header, you can try creating an extension instead of an app.
