### ISSUE TITLE
How to check the error details

### ISSUE THREAD

**Issue by apis3445** [a85/POSTMan-Chrome-Extension#12978]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

I can't generate any test with postbot. I only got an error. How I can debut what is the exact error
![image](https://github.com/postmanlabs/postman-app-support/assets/7475390/c95dd8c6-1a6d-4b70-8338-197e6e91c3cb)

Is there any option to get the code in the postbot chat? and copy to the collection

### Steps To Reproduce

1. Open any request with some tests
2. Click in postbot
3. Clic in add more test

### Operating System

macOS

### Postman Version

11.2.26

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by abhijitkane** [comment]
@apis3445 Thanks for reporting this. Can you email us at help@postman.com from your registered email, citing this issue number?

**Comment by kylerRenneker** [comment]
@apis3445 Good news! We just pushed out a fix for this in v11.2.27

Please update your app to the latest version and try again.

**Comment by apis3445** [comment]
Is working thank you
