### ISSUE TITLE
Prevent accidental deletion of Collection

### ISSUE THREAD

**Issue by fabianrenner** [a85/POSTMan-Chrome-Extension#12988]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

Currently you can delete collections in a workspace without any further confirmation and even with keyboard shortcut.
Since there is no different role assignment possible, each of the team members could accidentally delete a collection.

### Describe the solution you'd like

To prevent accidental deletions, either a delete confirmation (similar to the API deletion procedure, where you have to type the resource name in order to delete) or to introduce another role that does not allow deleting of collections

**Comment by DannyDainton** [comment]
Hey @fabianrenner 

There is a confirmation on deleting the Collection:

<img width="472" alt="image" src="https://github.com/postmanlabs/postman-app-support/assets/17089546/3b156339-1370-4b06-8bf9-90483df8527c">

You would need to physically perform a _delete_ action and then hit another `Delete` button in the modal, to delete the Collection.

Also depending on the plan that you're on, these deleted Collections will be stored in the Trash section for a period of time and can be fully restored back into the Workspace.

<img width="206" alt="image" src="https://github.com/postmanlabs/postman-app-support/assets/17089546/8b1751aa-7c8b-47cc-b0b3-ed23fac9dce0">


https://go.postman.co/trash

<img width="1526" alt="image" src="https://github.com/postmanlabs/postman-app-support/assets/17089546/0943edd0-6d02-41aa-b3d8-43b37c1a97d1">

There as also Role Based Access Controls in place on certain plans with limit what actions can be taken against an element in the Workspace.

https://learning.postman.com/docs/collaborating-in-postman/roles-and-permissions/#team-roles
