### ISSUE TITLE
Postman cannot be installed on Macos 14.5

### ISSUE THREAD

**Issue by didiervdb** [a85/POSTMan-Chrome-Extension#12987]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Downloaded the latest postman.zip, copied the app to the Applications folder, Gatekeeper is blocking Postman
spctl -a -vvv -t install Postman.app
Postman.app: rejected
source=Unnotarized Developer ID
origin=Developer ID Application: Postdot Technologies, Inc (H7H8Q7M5CK)

### Steps To Reproduce

Launch postman on Macos 14.5
Fails

### Operating System

macOS

### Postman Version

14.5

### Postman Platform

Postman App

### User Account Type

Signed Out User

**Comment by Moonshieldgru** [comment]
****

**Comment by tony-go** [comment]
Duplicate, see #13363 :)
