### ISSUE TITLE
gRPC server reflection doesn't work with map fields

### ISSUE THREAD

**Issue by Tommires** [a85/POSTMan-Chrome-Extension#12997]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Postman for Windows Version 11.3.1 после обновления появилась проблема Could not load server reflection
![image](https://github.com/postmanlabs/postman-app-support/assets/175133781/536c03d6-b1a9-45c0-9deb-fed4c349e0d4)

до обновления все работало без проблем

### Steps To Reproduce

новая коллекция
новый grpc запрос
ввожу URL
собираюсь выбрать метод (select a method) но получаю ошибку

### Screenshots or Videos

![image](https://github.com/postmanlabs/postman-app-support/assets/175133781/a48ba32d-0030-44c0-add4-d73185aa2409)

### Operating System

Windows

### Postman Version

11.3.1

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by yurifedoseev** [comment]
I have the same issue with server reflection and golang backend

There're two proto files in different folders
```proto
api/service.proto

syntax = "proto3";
package api;
option go_package = "api";

import "model/data.proto";
import "google/protobuf/empty.proto";

service API {
   rpc SomeRequest(APIRequest) returns (google.protobuf.Empty);
}
message APIRequest{
	string id= 1;
	map<string, model.Data> data_map = 2;	// game element id to store reward
}


model/data.proto:

syntax = "proto3";
package model;
option go_package = "model";

message Data {
  string field_1 = 1;
  string field_2 = 2;
}
```

When I try to fetch server reflection Postman shows me an error:
Details no such Type or Enum in `.api.APIRequest.DataMap.Entry` in type `.api.APIRequest.DataMap.Entry`

Rollback to `v11.2.0` helps to mitigate the issue

**Comment by cmenet-betclic** [comment]
Same here with the last version 11.3.0, we have the feeling it's linked to map<string, string> in the proto
Switching back to version 11.2.0 fix the problem

**Comment by JaneEyre333** [comment]
[yurifedoseev](https://github.com/yurifedoseev) How have you rollbacked to v11.2.0? (can't find such option in Postman Desktop)

**Comment by cmenet-betclic** [comment]
> [yurifedoseev](https://github.com/yurifedoseev) How have you rollbacked to v11.2.0? (can't find such option in Postman Desktop)

Use direct download link for previous version (doesn't seem to be available in Postman)
https://dl.pstmn.io/download/version/11.2.0/win64
https://dl.pstmn.io/download/version/11.2.0/osx64

**Comment by dennis-chequer** [comment]
I am also experiencing the same problem after updating to version 11.3. The same happens with MacOS apps.
<img width="1091" alt="image" src="https://github.com/postmanlabs/postman-app-support/assets/143997074/80390af2-d305-42e3-8dd2-0212dd27063a">

**Comment by dennis-chequer** [comment]
Even if you roll back to 11.2, Postman automatically updates to 11.3, so you need to take an expedient response by modifying the hosts to prevent the update.

In my case ( MacOS )
- downgrade 11.2 app
- modify host ( not to run app ) 
$ vi /etc/hosts
```
# Postman Auto update block
0.0.0.0         dl.pstmn.io
0.0.0.0         sync-v3.getpostman.com
0.0.0.0         getpostman.com
0.0.0.0         go.pstmn.io
```

**Comment by jamendozag** [comment]
I just started to get the same error after the last update, reflection does work via `grpCurl` with the following commands:
* `grpcurl -plaintext localhost:8080 list`
* `grpcurl -plaintext localhost:8080 list <service>`

But trying to load via postman, I get `Could not load server reflection. Details: no such Type or Enum ....` error

**Comment by AlyaxeyAskerka** [comment]
Same issue - service reflection not working after updating to 11.3.1

**Comment by ronork** [comment]
Hey everyone, 
Thank you for reporting this issue. We attempted to reproduce the error using the following proto files but were unable to encounter the same problem:

**service.proto**

```
syntax = "proto3";

package api;

import "model/data.proto";
import "google/protobuf/empty.proto";

service API {
   rpc SomeRequest(APIRequest) returns (google.protobuf.Empty);
}

message APIRequest {
    string id = 1;
    map<string, model.Data> data_map = 2;
}
```

**data.proto**

```
syntax = "proto3";

package model;

message Data {
    string field_1 = 1;
    string field_2 = 2;
}
```

Since many of you are facing this issue, it's likely that we're missing a crucial step. If you have any additional details or steps to reproduce the issue, please share them here. Your input will help us investigate and resolve this problem faster.

**Comment by SlavaUtesinov** [comment]
@ronork hi, try `map<string, string>` instead of `map<string, model.Data>`, Postman version - 11.3.1

**Comment by yurifedoseev** [comment]
@ronork I haven't posted the exact proto because it's huge proto folders with dozens files and models. Let me create a minimum reproduceable example.

**Comment by ronork** [comment]
> @ronork hi, try `map<string, string>` instead of `map<string, model.Data>`, Postman version - 11.3.1

hey @SlavaUtesinov, tried that still working on our end for both windows and macOS.

**Comment by yurifedoseev** [comment]
@ronork here is a minimum example which reproduces the bug for me https://github.com/yurifedoseev/postman-grpc-bug
It's enough to use just `map<string,string>` in this example
Maybe the problem is with the specific version of protobuf-compiler (or any other library) or some import path in proto
I've run my example on Ubuntu 24.04 in WSL2

**Comment by nomad-software** [comment]
It's probably a regression of this bug https://github.com/postmanlabs/postman-app-support/issues/11625 which itself was a regression.

**Comment by ronork** [comment]
Hey @yurifedoseev , Thanks for providing the example, I was able to reproduce the issue and will provide an update once a fix has been implemented.

**Comment by ronork** [comment]
We have resolved this issue in the latest release of the Postman app (v11.3.2). Please update your app to verify if everything is now working correctly.

**Comment by yurifedoseev** [comment]
@ronork all work like a charm. Thank you!

**Comment by Tommires** [comment]
@ronork все работает. Спасибо большое за оперативность!

**Comment by wooln** [comment]
> We have resolved this issue in the latest release of the Postman app (v11.3.2). Please update your app to verify if everything is now working correctly.

There is a new issue in v11.3.2,  the 16UNAUTHENTICATED returned from the server is not recognized. v11.3.1 works fine. #13013
