### ISSUE TITLE
Postman cannot launch

### ISSUE THREAD

**Issue by spiroskgr** [a85/POSTMan-Chrome-Extension#1299]
Hello. I am using Postman, but today I cannot launch the application at all. I do not understand what goes wrong. I uninstalled Google Chrome and installed it again, but the issue is still there and I am not able to open the application.

Could you advice me on what to do? I am using Ubuntu 14.04LTS 64 bit. 

I experience an issue with the right-click on Chrome. Do you think this might be affecting Postman? How can I uninstal Postman?

Thank you in advance for your reply/

**Comment by abhijitkane** [comment]
@elssar is there an alternate way to launch Postman in Ubuntu  / any debugging steps?

**Comment by elssar** [comment]
Hi @spiroskgr, how do you usually launch Postman?

If you use Unity, you can launch postman from the dash. Just open the dash home, type in Postman and click on the app icon.

Or you can try going to `chrome://apps` and try launching Postman from there. If that doesn't work either, then you can try creating a desktop shortcut for Postman by right clicking on the Postman app icon selecting `Create Shortcuts`.

Finally, if all else fails you can try launching from the command line - `/usr/bin/chromium-browser --profile-directory=Default --app-id=fhbjgbiflinjbdggehcddcbncdddomop`

**Comment by spiroskgr** [comment]
Thank you for the reply. I deactivated the extension on the Google Chrome and deleted Postman from there. Afterwards, I downloaded Postman again and everything is fine.

**Comment by ageldt** [comment]
It should be forbidden by law to write software that is doing nothing, not even complaining. 
People who still release such software should go to jail and being forbidden to write code for the rest of their life.

having same issue. Lost an hour for that peace of crap. Better stay with curl don't try postman - save your nerves.

**Comment by a85** [comment]
https://www.youtube.com/channel/UCocudCGVb3MmhWQ1aoIgUQw
