### ISSUE TITLE
Postman hangs with many escaped-double-quotes within a response json string field

### ISSUE THREAD

**Issue by ed-mak** [a85/POSTMan-Chrome-Extension#12990]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

**_Warning that this example curl in postman takes a while to render and will freeze postman in version 11.2.34_** 
[request_that_returns_json_response_with_80k_double-quotes_renders_in_35seconds.txt](https://github.com/user-attachments/files/16090696/request_that_returns_json_response_with_80k_double-quotes_renders_in_35seconds.txt)
[request_that_returns_json_response_with_160k_double-quotes_renders_in_70seconds_or_longer.txt](https://github.com/user-attachments/files/16090699/request_that_returns_json_response_with_160k_double-quotes_renders_in_70seconds_or_longer.txt)

I've encountered a major parsing performance issue for specific json responses. In particular, it appears like postman is having an issue while rendering a large number of escaped double-quote characters (ie `\"`) contained in json-string fields. Could also possibly affect other characters or character sequence. Started about 2 months ago. Prior to this, postman would be able to render these with-minimal or without issues.

I've attached 2x curl requests that easily invokes the performance issue using 80k and 160k double quotes returned in the response. I am utilizing the helpful httpbin api. I know the count sounds like a lot of characters, but prior to this issue, postman used to easily render these. There is no issue with the response time as the above example requests will respond in <1 second from the server. However when rendering, it takes **35seconds and 70seconds+ respectively** on my m1 macbook.

I work with a web application that regularly spits out large json-encoded-text-blobs as a string field in its json response which will naturally contain many of these escaped double-quotes and I suspect that postman's ill rendering is to blame. Frequently, I have to force close postman and is obviously detrimental to my workflow.

Also worth noting that collection runs are unaffected - it's just the rendering of the output when you manually execute a request.

### Steps To Reproduce

Import my 2 curl requests into postman. Run the request and you potentially have to wait over a 30 seconds or a minute for it to render.

### Operating System

macOS

### Postman Version

11.2.34

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by ed-mak** [comment]
Still an issue in 11.3.1 after testing

**Comment by diabhoil** [comment]
Having the same issue on Windows 11 with 11.3.1. Everytime I query my API its stuck with formatting the response. The size of the response is < 1MB. So it should not be that hard. 

Setting "Response -> Body -> Raw" is working for requests once I have executed them, but I can not set this for new requests.

Formatting should run on a Non-GUI Thread and should not block the whole client app. Additionally make it possible to set default response format to "Raw".

**Comment by pn-p** [comment]
I have the same problem with an HTTP response with `Content-Type: application/json; charset=utf-8` containing a bunch of escaped double quotes.

It would be great if auto-formatting (or rendering?) could have a timeout, like if takes longer than 250ms to just go straight back to plaintext.

**Comment by parthverma1** [comment]
Hey @ed-mak, thank you for reporting the issue.
I was able to reproduce the issue and will provide an update once a fix has been implemented.

**Comment by ed-mak** [comment]
Appears to be resolved in 11.7.0. Can you verify that the issue was resolved by the team? @parthverma1

**Comment by chowwinston** [comment]
@ed-mak this was actually resolved in 11.6 😄 
I'll close this issue now but please let us know if you're still experiencing any problems
