### ISSUE TITLE
Add Env Variable That holds the current folder name 

### ISSUE THREAD

**Issue by kemora13conf** [a85/POSTMan-Chrome-Extension#12994]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

No it's not related to a certain problem, actually  it's more of a suggestion.

### Describe the solution you'd like

Some time like i have different roles ex: user, admin... and my endpoint always are something like /user/ressource for the user and /admin/ressource for the admin it would be so helpfull if there by the default an env variable that holds the current folder name

**Comment by giridharvc7** [comment]
You can use the `pm.execution.location` to access the path of your request - which includes the collection and folder details. You can perhaps use this information and store it in a variable or use it as is?

**Comment by kemora13conf** [comment]
Thank you for your response, Mr. Giridhar. The suggestion to use
*pm.execution.location* has resolved my issue. I was able to access the
folder information I needed using this property. I appreciate your help in
providing this solution.
