### ISSUE TITLE
gRPC Reflection loading does not work with version 11.3.1

### ISSUE THREAD

**Issue by anuprak** [a85/POSTMan-Chrome-Extension#13003]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

gRPC Reflection loading does not work with version 11.3.1 and is a hassle. How can i downgrade to the previous version?

### Steps To Reproduce

Load server reflection for any gRPC service. The attached error pops up.

### Screenshots or Videos

![image](https://github.com/postmanlabs/postman-app-support/assets/148472773/0951fec0-9c11-4d9b-9205-96bbc782e355)

### Operating System

Windows

### Postman Version

11.3.1

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by DSchau** [comment]
Hey @anuprak! Thanks for opening this. We're currently rolling out a fix for this and fixing the same issue identified in #12997.

I'll go ahead and close this as duplicate and we'll consolidate discussion / communication when issue is addressed there.

cc @ronork 

Thank you!

**Comment by ronork** [comment]
Hey, @anuprak
We have resolved this issue in the latest release of the Postman app (v11.3.2). Please update your app to verify if everything is now working correctly.

**Comment by anuprak** [comment]
Thank you!! I updated the version and the issue is resolved!
