### ISSUE TITLE
Responses with large json payloads seems to hang entire application 

### ISSUE THREAD

**Issue by reffjitter** [a85/POSTMan-Chrome-Extension#1301]
I am developing a RESTful service that returns the contents of a PDF as a simple json payload. Here is an example.

{"contentType":"application/pdf", "length":1697955, "data":"JVBERi0xLjUNJeLjz9M... lots more data ..."}

When I call this service. I get the response, I even see it in the pretty tab, but the entire Postman application becomes unresponsive. Sometimes it comes back after like 10 minutes. 

I can work around it by killing the chrome thread in the task manager.

I am working on Windows 7 Enterprise.

This seems to be a new issue with the latest version. I was successfully able to test this service on an earlier version. I am now using 
Version 3.0.5 (packaged)
OS: win
Architecture: x86-32
Native client architecture: x86-64

**Comment by scott-nomad** [comment]
I have the same problem.  I have a Base64 encoded image in the JSON response.  I can send it to the REST service but the responses cause the app to hang.  My data size is much smaller - only 90,000 characters and it hangs.

**Comment by arondeparon** [comment]
:+1: 

Same story here. Adding a relatively small base64-encoded file crashes Postman entirely.
