### ISSUE TITLE
Bug: v11.3.2/11.4.0 gPRC does not recognize the 16UNAUTHENTICATED state returned from the server, v11.3.1 works fine.

### ISSUE THREAD

**Issue by wooln** [a85/POSTMan-Chrome-Extension#13013]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Bug: v11.3.2/11.4.0 gPRC does not recognize the 16UNAUTHENTICATED state returned from the server.  v11.3.1 works fine.
- Expect: Status code: 16 UNAUTHENTICATED  Could not authorize the operation Received HTTP status code 401
- Actual: Status code: 13 INTERNAL Received RST_STREAM with code 0

### Steps To Reproduce

1. new grpc request
2. Authorization - Auth Type - No Auth
3. Invoke
4. Check the Response.

### Screenshots or Videos

Actual
![图片](https://github.com/user-attachments/assets/f8e73441-c1d6-41a5-921f-852b4591a292)

Expect
![图片](https://github.com/user-attachments/assets/64d06a64-c7d3-43a1-b624-773546808c6e)

### Operating System

Linux

### Postman Version

11.3.2

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by appurva21** [comment]
Hey @wooln! I tried to recreate this with a local gRPC server in Node that explicitly sent status code 16 with a custom error message: "Received HTTP status code 401", and seems to be working fine on our end.

Could you share a scaled-down version of your server to help us reproduce this?

![image](https://github.com/user-attachments/assets/c555afea-421b-4883-8708-262dd3557646)

**Comment by appurva21** [comment]
I'm closing this issue for now, but if you're still experiencing it in the latest version, please share the previously requested details so we can investigate further.
