### ISSUE TITLE
Array parameters inside url query string are not correctly sent when establishing a websocket connection

### ISSUE THREAD

**Issue by davidmaelfaitAT** [a85/POSTMan-Chrome-Extension#13017]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

When I setup a websocket client connection from postman to my API and use array parameters in the url query string in the form of "wss://hostname?**deviceId=device1**&**deviceId=device2**" then only the last parameter is sent. In this case **deviceId=device2**.

Remarks:
- Missing parameter **deviceId=device1** is confirmed with packet analysis using Wireshark
- Sending the above URL is tested with other weboscket client tools and works as expected (meaning: parsing at API side is correctly done)
- It worked in previous version of postman

### Steps To Reproduce

1. Open new websocket tab
2. Enter url: wss://hostname?deviceId=device1&deviceId=device2
3. Click 'connect'
4. API only receives last parameter deviceId=device2

### Screenshots or Videos

![postman websocket problem](https://github.com/user-attachments/assets/fa8341fd-0f1e-404d-b896-4e1b300279b3)

### Operating System

Windows

### Postman Version

11.4.0

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by parthverma1** [comment]
Hey @davidmaelfaitAT , thank you for reporting the issue.
I was able to reproduce the issue and will provide an update once a fix has been implemented.

**Comment by parthverma1** [comment]
This has been fixed in the latest version of Postman (v11.6.1). Feel free to re-open the issue if the problem recurs.
