### ISSUE TITLE
self-signed certificate in certificate chain

### ISSUE THREAD

**Issue by Abdul8081** [a85/POSTMan-Chrome-Extension#13023]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

self-signed certificate in certificate chain is coming on each time when i am trying to send the otp to my email

### Describe the solution you'd like

I don't know the solution, also I have used the certificate generated by the gogle(refered from the postman -> Add and mange certificate) and inserted it also in the postman certificate as the certificate.pem file, then also it is not working, each time, it's giving me the error of the self-signed certificate in certificate chain, and hence after that, i am unable to test the other things.

### Describe alternatives you've considered

Please help me out, I am literally stuck form last 20 days, on this thing only

### Additional context

Please help me out.

**Comment by Abdul8081** [comment]
Please help someone

**Comment by parthverma1** [comment]
Related to https://github.com/postmanlabs/postman-app-support/issues/13024

**Comment by Jef1SD** [comment]
This says its done but there is no solution? I'm having the same issue.
