### ISSUE TITLE
Add more Binary Data File Types to the Runner

### ISSUE THREAD

**Issue by mnimer** [a85/POSTMan-Chrome-Extension#1302]
In the test runner setup you can select a Data File, but it requires you to select the Data FIle Type of JSON or CSV.  Can you add support for binary file types like image/jpg/png and pdf?

**Comment by abhijitkane** [comment]
@mnimer The CSV/JSON files are for substituting variables for different iterations. To send files with requests while running a collection, you'll need to use Newman - http://blog.getpostman.com/2014/11/15/using-newman-to-run-collections-with-file-post-requests/.
