### ISSUE TITLE
Export Environment Ignores Empty Values 

### ISSUE THREAD

**Issue by cawoodadviceflow** [a85/POSTMan-Chrome-Extension#13033]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

When exporting an environment postman ignores the fact that a value may be empty and sets the default value.

### Steps To Reproduce

Create and environment variable with default "foo" but value empty "". Export it, The value is "foo" instead of "".
This can be an issue when a live/prod environment expects a value to be empty.

### Screenshots or Videos

![image](https://github.com/user-attachments/assets/cd4156c3-1354-4722-8821-03de07f974e9)

### Operating System

Windows

### Postman Version

11.5.0

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by coditva** [comment]
@cawoodadviceflow Hey, thanks for reaching out. It seems from the screenshot that you shared that you have "initial value" set for the environment, but the "current value" is empty. When you export an environment, the "initial value" is the one that is exported in the JSON file.

We're also tracking exporting of current values as a [feature request](https://github.com/postmanlabs/postman-app-support/issues/6728). Closing this one out as a duplicate.
