### ISSUE TITLE
I think there are bug with POST Request.

### ISSUE THREAD

**Issue by dmitry-tuzenkov** [a85/POSTMan-Chrome-Extension#1304]
When sending a POST request, endpoint server receives it like GET.
Please check.

Version 3.0.5 (packaged)
OS: win
Architecture: x86-32
Native client architecture: x86-64

**Comment by abhijitkane** [comment]
Can you follow the steps at http://blog.getpostman.com/2015/06/13/debugging-postman-requests/ and see what requests are being sent in the network tab?

**Comment by bandtank** [comment]
I had what may have been a similar problem. The server I was hitting redirected http requests to https and that somehow caused POSTs to look like GETs. I don't know what was going on exactly, but my issue was resolved by adding an s to the protocol (https).

**Comment by abhijitkane** [comment]
@dmitry-tuzenkov @bandtank To avoid redirects, you'll need to enable the interceptor and set the 'Automatically follow redirects' setting (in Postman) to NO.

Chrome follows all redirects without regard to the original request method, and this is not visible to Postman.

**Comment by avikb** [comment]
The problem still exists.
When you send a POST request and server return 301 (redirect), Postman follow the new url, but send a GET request...
Problem only with POSTs. (PUT, DELETE... work fine)

**Comment by abhijitkane** [comment]
@avikb As mentioned above, you'll need to enable the interceptor and set the 'Automatically follow redirects' setting (in Postman) to NO.

Chrome follows all redirects without regard to the original request method, and this is not visible to Postman.

You can also switch to the native apps (https://www.getpostman.com/apps) that support this without the Interceptor.
