### ISSUE TITLE
response size wrong

### ISSUE THREAD

**Issue by noobjun** [a85/POSTMan-Chrome-Extension#13043]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

sometimes i see wrong response size, it only seems to happen when the response payload is under 1MB 
 for example i have a service returns this payload
`{"took":904,"timed_out":false,"_shards":{"total":16,"successful":16,"skipped":0,"failed":0},"hits":{"total":{"value":10000,"relation":"gte"},"max_score":7.5323896,"hits":[{"_index":"listings","_type":"_doc","_id":"QgRbB5EBnYV256IVvnnE","_score":7.5323896},
.... // there are ~60000 rows of this, but i can't post it all due to size restriction
]

full payload here: https://pastebin.ai/5yr9nuh0s4
the response size should be 913 KB
but postman says it's 71.24 KB

### Steps To Reproduce

1. fire a request to some service which can return a lot of data
2. make sure the data returned by the service is less than 1MB but also not too far from 1MB.
3. check the postman UI strip which displays the wrong data size

### Screenshots or Videos

![image](https://github.com/user-attachments/assets/100950be-1bc4-4909-a62a-a3a826d8831a)

### Operating System

Mac OS Sonoma

### Postman Version

Version 11.5.1

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by parthverma1** [comment]
Hi, 
The response size in the status bar indicates the total size of the response (headers + body). You can hover over the size label to view a breakdown.

The response body size should be equal to Compressed body size if there was any compression. Can you check the response headers table to check if `Content-Encoding` header was received and was one of `br, gzip or deflate`.

We are tracking a similar issue here https://github.com/postmanlabs/postman-app-support/issues/7596

Thanks

**Comment by noobjun** [comment]
> Hi, The response size in the status bar indicates the total size of the response (headers + body). You can hover over the size label to view a breakdown.
> 
> The response body size should be equal to Compressed body size if there was any compression. Can you check the response headers table to check if `Content-Encoding` header was received and was one of `br, gzip or deflate`.
> 
> We are tracking a similar issue here #7596
> 
> Thanks

The server always returned gzip'd response in both cases.

### Bugged
When payload is slightly less than 1MB (about 900KB) it would show
<img width="473" alt="Screenshot 2024-07-31 at 2 23 50 PM" src="https://github.com/user-attachments/assets/0a62dd3c-1e7f-43f2-a13c-d1e0b657b9d8">

### Correct
When the payload is more than 1MB, it would show everything correctly.
<img width="484" alt="Screenshot 2024-07-31 at 2 23 35 PM" src="https://github.com/user-attachments/assets/f41af58d-ecef-4a2f-bd36-6fd52998fe49">


It seems like the latter one is showing the uncompressed size when the former shows the compressed size? I dunno why 1MB threshold makes it behave differently.

**Comment by parthverma1** [comment]
This was related to https://github.com/postmanlabs/postman-app-support/issues/7596 and is now resolved with version 11.8 of the app. I am closing this issue for now. Feel free to re-open the issue if the problem recurs.
