### ISSUE TITLE
Failure when importing collection

### ISSUE THREAD

**Issue by ultraviolex** [a85/POSTMan-Chrome-Extension#13044]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

I am trying to import a collection from a file (file is ~ 4.3mb) using the postman desktop app. Postman is able to start the import but fails before finishing. 

### Steps To Reproduce

1. Open collections tab
2. Click import
3. Select file to import 
4. Choose to import as postman collection
5. Click import

### Screenshots or Videos

![image](https://github.com/user-attachments/assets/e79017cc-85f1-415e-a2d8-68cf1395b540)

### Operating System

macOS

### Postman Version

11.6.2

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by VShingala** [comment]
@ultraviolex Can you try importing this collection again now and see if the issue is resolved?

**Comment by ultraviolex** [comment]
@VShingala resolved, thank you !
