### ISSUE TITLE
Sign in issues (partly Cloudfare related)

### ISSUE THREAD

**Issue by weflower** [a85/POSTMan-Chrome-Extension#13051]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Cannot sign in to the Postman app because of issues with the Cloudfare captcha. On Chrome, the captcha window never loads. On Firefox, it never authenticates and cannot submit issue because of page styling.

### Steps To Reproduce

1. When trying to sign in on Chrome Version 127.0.6533.89 (with extensions disabled):
   1. no recaptcha window appears.

      ![cloudfare-error-chrome](https://github.com/user-attachments/assets/14b36f1e-9f20-4f73-b74a-d5b9557eee78)

   2. Try to sign in regardless and get an error that recaptcha failed:
      ![cloudfare-error-chrome-2](https://github.com/user-attachments/assets/53a673c6-4234-43c7-b8a2-e9cfd008b628)

2. When trying the same sign in on Firefox 128.0.3  (with extensions disabled), recaptcha appears but always fails. Also, if I click "Having issues?" on the recaptcha's failure window, the styling of the page doesn't allow me to scroll down far enough to submit an error report.

   ![2024-08-04_12-45-20](https://github.com/user-attachments/assets/ca68aeba-a4b5-46b4-94fe-4e2d5cdb9233)

### Operating System

Windows

### Postman Version

11.6.1

### Postman Platform

Both

### User Account Type

Signed Out User

**Comment by iamraghuveer** [comment]
facing the same issue, any workaround for this? 
**Update**: Able to login via Firefox

**Comment by waseem-pm** [comment]
@weflower @iamraghuveer We are sorry for the inconvenience. The CAPTCHA error you are getting is usually thrown in situations where Cloudflare detects a potential bot or unusual visitor behavior on your device or network.

Please help us in troubleshooting the issue by following these steps:
- Clear your browser cache and cookies
- Disable all browser extensions
- Ensure that JavaScript is enabled
- Confirm that cookies are enabled
- Try after turning off the VPN or proxy
- Try from a different network

If you are still having issues, please share the [HAR recording](https://support.postman.com/hc/en-us/articles/360038234154-How-to-get-logs-from-the-Postman-web-app) with us. Please do not use your correct Postman login credentials while recording the HAR.

**Comment by weflower** [comment]
@waseem-pm thanks for replying so quickly. 

I've tried all the steps above. VPN-related, I've tried it both ways, but I'm using Cisco Secure Connect for my work VPN, so I need that running. It's never caused this issue before, either.

Does the captcha window appear at all for everyone else on Chrome? My version of Chrome is corporate managed (not sure if that matters), but it's not displaying at all for me. So there's no opporunity to even pass/fail the check.

Fwiw, I had a Cloudfare captcha issues on a different, completely unrelated site yesterday too. So it might be completely on them and there's nothing you can do on that front.

But could you check your HTML/CSS/whatever for if there's a reason it being missing on Chrome and the Firefox issues where I can scroll to the bottom of their popup?

Thanks!

**Comment by waseem-pm** [comment]
Hi @weflower, I'm checking to see if you can log in successfully. If not, please share the HAR file so we can check the issue with Cloudflare's help.

**Comment by weflower** [comment]
@waseem-pm, looks like it's working now. Chrome showed the captcha check (which passed automatically) and I was able to sign in. Thanks for the help!

**Comment by desrod** [comment]
I can confirm that the captcha never shows up under Firefox, TorBrowser or any Gecko based browser, but shows up fine under Chrome and Chrome-based browsers. This is the case with at least the last 10 releases of Firefox and whether I'm on a LAN, WAN or VPN connection. 

However, if I forge my UserAgent string in Firefox, it works, so it appears that Cloudflare (identity.cloudflare.com) or Postman itself, are denying Firefox from logging in for whatever reason. 

Please don't do that. It's 2024, let's try to learn how to work with modern browsers.

**Comment by liteshpatil17** [comment]
@desrod We have tested on Firefox and Tor Browsers and the CAPTCHA is working fine. Could you please share the versions of Firefox and Tor Browser that you are using? Also, could you confirm if you are using any VPN?

To help us troubleshoot the issue, could you try the steps mentioned in [this message](https://github.com/postmanlabs/postman-app-support/issues/13051#issuecomment-2268692822)? If the issue persists, please share a HAR recording with us. When creating the HAR recording, please avoid using your actual Postman login credentials.

**Comment by hindutakkalapalli** [comment]
I had faced the similar issue in my Mac book - recaptcha was hiding/didnt show up and seems cloudflare was blocking the request, I tried with all browsers such as safari, chrome, firefox etc. did clean up cookies, cache as well as enabled cookies, java script etc. Issue finally resolved after updating my Mac book as it was pending update for the sonoma 14.7

**Comment by Kirtishelke17** [comment]
Cannot sign in to the Postman app because of issues with the Cloudfare captcha. the captcha window never loads in all browsers also i am tried using postman web it not reload captcha
