### ISSUE TITLE
Key Stroke Send

### ISSUE THREAD

**Issue by realDavidMeissner** [a85/POSTMan-Chrome-Extension#13055]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

No single-handed way to execute a send.

### Describe the solution you'd like

I recommend incorporating a simple keystroke to send a request. Something like 'ctrl+r' or F5. These are common keystrokes in programs like mysql and mssql for executing queries.

You currently have ctrl+Enter, but that is sort of two handed unless you move your left hand to the right side of the keyboard, which is cumbersome.

### Describe alternatives you've considered

NA

**Comment by jellevandevelde** [comment]
Hi @realDavidMeissner, you can customize the Send Request keyboard shortcut (ctrl/cmd + enter by default) with your preferred key binding in Settings > Shortcuts. Let me know if you face any challenges doing so.

**Comment by realDavidMeissner** [comment]
So sorry to waste your time. I didn't even realize it could be customized. Thanks for the reply.

**Comment by jellevandevelde** [comment]
No worries - feedback and ideas are always welcome! I'll close this issue for now, but free to open a new one if you run into any challenges or have any suggestions.
