### ISSUE TITLE
Increase contrast in Dark theme

### ISSUE THREAD

**Issue by santialbo** [a85/POSTMan-Chrome-Extension#1305]
I really like the dark theme but I feel the contrast between the text and the background is not enough and makes it a little unpleasant. It would be nice if the contrast increased a bit or if and option was added to the settings panel in order to increase it.

**Comment by a85** [comment]
We have a new re-designed dark theme for 4.0+. Let me know what you think!

**Comment by aditikul** [comment]
@santialbo Did you get a chance to check out the updated dark theme? We've worked to improve the contrast issues. Do check out the native Mac app and Windows app too.
