### ISSUE TITLE
SSE not working properly only open and close showing

### ISSUE THREAD

**Issue by Matt2012** [a85/POSTMan-Chrome-Extension#13050]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

I have a supabase edge function that spits out lots of events.

Only the initial connection and close connection showing.

![image](https://github.com/user-attachments/assets/924db70e-7a67-4406-95ea-36cc7cb53691)

### Steps To Reproduce

use postman to request an endpoint that supports SSEs watch streamed response.

### Screenshots or Videos

![image](https://github.com/user-attachments/assets/7c1d241d-e3c5-424f-a5da-6e9b4210b7b1)

### Operating System

Windows

### Postman Version

11.6.2-240731-0006

### Postman Platform

Postman Web

### User Account Type

Signed In User

**Comment by Matt2012** [comment]
Just want to report the issue has gone today. Not sure if you patched or was somehow just a temporary issue I faced.

**Comment by AddisonG** [comment]
I got this when I was accidentally gzipping responses from my server - the data is only decoded on connection close, or after a large enough chunk is sent. Ensure you're not setting `Accept-Encoding`, which **postman does by default** in the headers.
