### ISSUE TITLE
Add API usage property in the API response for the endpoint /me

### ISSUE THREAD

**Issue by guibranco** [a85/POSTMan-Chrome-Extension#13071]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

No, that is not a problem, but it is a user request to enhance an existing feature.

### Describe the solution you'd like

I want to request one property with the `API Usage` count in the Postman API endpoint that returns data from my account.

The information that I'm looking for is already available on this page: https://www.postman.com/billing/add-ons/overview
![image](https://github.com/user-attachments/assets/84a7fc85-9aed-4fc3-ad1e-4c53484e0c95)

It would be nice to have the following (or part of) data:

- Request count (already consumed).
- Request limit (total in the period).
- Reset date (date when the count will be reset to zero again).

### Describe alternatives you've considered

An alternative solution would be to create a new endpoint that will return this data and some other data related to billing details if changing the existing one is not allowed or has some business restrictions.

### Additional context

I have a dashboard that shows the state of my services and other stuff I use. I also use Postman CLI to run some tests in CI pipelines (using GitHub Actions). So, the first reason would be to track the usage in my dashboard without needing to access the Postman Billing page.

Usually, I ran out of calls to Postman before the date it resets (in my case, the 12th of each month). I need to switch off the test steps in GH workflows and switch them back again after they reset.

If I have this information in the API response (like how many requests I still have or if it was exhausted), I can decide in runtime whether or not to run the tests without a human/user/manual intervention like I do right now.

I use a temporary Selenium solution that accesses the billing page and extracts the information. This is not the best solution and can break anytime since the interface or URLs can change.

I can’t see any technical reason API does not include this property. Maybe it is a commercial/business reason?

Originally posted here: https://community.postman.com/t/retrieve-postman-api-usage-from-me-api-endpoint/65357/2.

**Comment by davidespihernandez** [comment]
Hi, @guibranco! Thanks for the feedback!
We expose the [/me endpoint](https://www.postman.com/postman/postman-public-workspace/request/ay0ymqy/get-authenticated-user) that returns the usage info in a response like this:

```
{
    "user": {
        "id": 12345678,
        "username": "taylor-lee",
        "email": "taylor.lee@example.com",
        "fullName": "Taylor Lee",
        "avatar": "https://example.com/user/r5u9qpvmujfjf6lbqmga.jpg",
        "isPublic": true,
        "teamId": 123,
        "teamName": "Test Team",
        "teamDomain": "test-team",
        "roles": [
            "user"
        ]
    },
    "operations": [
        {
            "name": "api_object_usage",
            "limit": 99999999,
            "usage": 8771,
            "overage": 0
        },
        {
            "name": "collection_run_limit",
            "limit": 99999999,
            "usage": 205,
            "overage": 0
        },
        {
            "name": "file_storage_limit",
            "limit": 1,
            "usage": 0.16,
            "overage": 0
        },
        {
            "name": "flow_requests",
            "limit": 100000,
            "usage": 13655,
            "overage": 0
        },
        {
            "name": "performance_test_limit",
            "limit": 99999999,
            "usage": 12,
            "overage": 0
        },
        {
            "name": "postbot_calls",
            "limit": 50,
            "usage": 0,
            "overage": 0
        },
        {
            "name": "mock_usage",
            "limit": 1000000,
            "usage": 119869,
            "overage": 0
        },
        {
            "name": "monitor_request_runs",
            "limit": 15000000,
            "usage": 6544406,
            "overage": 0
        },
        {
            "name": "serverless_requests",
            "limit": 10000,
            "usage": 0,
            "overage": 0
        }
    ]
}
```
Take into account that this request is also counted as API usage.
Does this work for you?

The current usage limits for free and basic plans in the Postman API are 10k and 100k respectively. If you use a free plan, consider upgrading to the next level and getting 10x more requests to the Postman API.
If you need help using the Postman API, please feel free to reach out to us. We have also some blog posts related to the Postman API that can be helpful for you [here](https://blog.postman.com/author/david-espi-hernandez/).

**Comment by guibranco** [comment]
Hi @davidespihernandez, thanks for the reply, but I can't see on the response (in yours and on mine) the field that has the corresponding data that I am looking for. 

This is what I got right now when I call the `/me` endpoint (redacted some personal data):

```json
{
    "user": {
        "id": [REDACTED],
        "username": "[REDACTED]",
        "email": "[REDACTED]",
        "fullName": "Guilherme Branco Stracini",
        "avatar": "[REDACTED]",
        "isPublic": true,
        "teamId": 0,
        "teamDomain": "",
        "roles": [
            "user"
        ]
    },
    "operations": [
        {
            "name": "api_object_usage",
            "limit": 3,
            "usage": 1,
            "overage": 0
        },
        {
            "name": "collection_run_limit",
            "limit": 25,
            "usage": 0,
            "overage": 0
        },
        {
            "name": "file_storage_limit",
            "limit": 20,
            "usage": 0,
            "overage": 0
        },
        {
            "name": "flow_count",
            "limit": 5,
            "usage": 0,
            "overage": 0
        },
        {
            "name": "flow_requests",
            "limit": 5000,
            "usage": 0,
            "overage": 0
        },
        {
            "name": "performance_test_limit",
            "limit": 25,
            "usage": 0,
            "overage": 0
        },
        {
            "name": "postbot_calls",
            "limit": 50,
            "usage": 6,
            "overage": 0
        },
        {
            "name": "reusable_packages",
            "limit": 3,
            "usage": 0,
            "overage": 0
        },
        {
            "name": "test_data_retrieval",
            "limit": 1000,
            "usage": 0,
            "overage": 0
        },
        {
            "name": "test_data_storage",
            "limit": 10,
            "usage": 0,
            "overage": 0
        },
        {
            "name": "mock_usage",
            "limit": 1000,
            "usage": 0,
            "overage": 0
        },
        {
            "name": "monitor_request_runs",
            "limit": 1000,
            "usage": 0,
            "overage": 0
        }
    ]
}
```

As you can see, no information matches the information on the [Billing](https://www.postman.com/billing/add-ons/overview) page I am looking for.

This is the billing page snapshot that I took a few minutes ago and the information I am looking at in the API:

![image](https://github.com/user-attachments/assets/511b7128-1efa-4a93-b630-f05fcae0da0d)

**Comment by davidespihernandez** [comment]
Hi, @guibranco!
I thought it was the `api_object_usage` field, but the information you are getting makes no sense. Let me check what's going on here.
Thanks!

**Comment by guibranco** [comment]
Thanks @davidespihernandez!

**Comment by davidespihernandez** [comment]
One additional question, are you using any specific Postman API endpoints, or all the usage you do is via the Postman CLI (which uses the Postman API under the hoods)?

**Comment by guibranco** [comment]
Except for the `/me` endpoint, which I run manually through the Postman itself, all the other requests come from Postman CLI (via GitHub Actions).

I have things like this in my GH Actions workflow actions:

```yaml
automated-api-tests:
    name: Automated API tests (Postman)
    runs-on: ubuntu-latest
    needs: [deploy, database_migrations]

    steps:

      - name: Install Postman CLI
        if: ${{ vars.POSTMAN_ENABLED == 'true' }}
        run: curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh

      - name: Login to Postman CLI
        if: ${{ vars.POSTMAN_ENABLED == 'true' }}
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}

      - name: Run API tests
        if: ${{ vars.POSTMAN_ENABLED == 'true' }}
        run: postman collection run 23511-e64f4d39-3587-48d5-a005-b466b5aca424 -e 23511-95105c79-d4eb-4388-9ff9-eb5dee83fdcf
```

**Comment by davidespihernandez** [comment]
@guibranco The /me endpoint response now returns an `api_usage` field you can use.
In addition, we are working on returning response headers with the current usage and the limits, so you can avoid the /me call (you will have the information on each Postman API response)

**Comment by guibranco** [comment]
Thanks, @davidespihernandez, amazing!
