### ISSUE TITLE
map<string, string> doesn't work anymore with protobuf - it sends [object Object] arrays 

### ISSUE THREAD

**Issue by cmenet-betclic** [a85/POSTMan-Chrome-Extension#13088]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Hi there!
When using the last version of Postman for Windows (version 11.9.1) with protobuf, my proto contract has a map<string, string>:
`map<string, string> additional_values = 3;`
When sending this payload for additional_values:
`"additional_values": [
  {
    "key": "nisi consequat",
    "value": "veniam"
  },
  {
    "key": "deserunt incididunt",
    "value": "dolor occaecat dolor consequat cupidatat"
  },
  {
    "key": "irure in quis",
    "value": "ullamco qui sed commodo anim"
  },
  {
    "key": "quis id ut",
    "value": "elit esse"
  }
]`
My code (in C#) received these values:
![image](https://github.com/user-attachments/assets/63ee98d8-9e0f-40da-804c-1743f9746266)
I didn't change my code at all, it used to work with one of the previous version.
Any idea?
Thanks

### Steps To Reproduce

1. Have a protobuf contract with a map<string, string> field
2. Send a payload as explained in the description of the issue
3. Receiving an [object Object] array, without any values

### Operating System

Windows

### Postman Version

11.9.1

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by appurva21** [comment]
Hey @cmenet-betclic! I tried to recreate this with a local C# server both via server reflection and proto file, but it seems to work fine for me.

Protobuf:
```
syntax = "proto3";

option csharp_namespace = "GrpcGreeter";

package greet;

service Greeter {
  rpc SayHello (HelloRequest) returns (HelloReply);
}

message HelloRequest {
  map<string, string> additional_values = 1;
}

message HelloReply {
  map<string, string> additional_values = 1;
}

```
Request on server:
![image](https://github.com/user-attachments/assets/92ea6f0e-9baa-457b-a084-579c9d9bdbe9)


Postman:
![image](https://github.com/user-attachments/assets/87dfe163-180d-4927-8cf9-e4492fdca042)


Can you share a scaled-down version of your server to help us investigate this further? 

Also, can you try structuring your payload as key-value pairs and see if that helps:
```
{
    "additional_values": {
       "a": "b",
       "c": "d"
    }
}
```

**Comment by cmenet-betclic** [comment]
Hi @appurva21 ,
Thanks for your quick message. I switched back to version 11.8.1, still the same issue.
I tried your "trick" using key-value pairs and it works fine, thanks!
