### ISSUE TITLE
Fields host divided on Host and Request url

### ISSUE THREAD

**Issue by Ivashkin** [a85/POSTMan-Chrome-Extension#1308]
for testing api on production and local, so as not to duplicate collections can be divided field "URL" on, host and request uri

Example: 
http://api.com/postman
host: http://api.com/
request uri: postman

**Comment by numaanashraf** [comment]
@Ivashkin, We recommend using our `Environments` feature for this use case. You can find more information [here](https://www.getpostman.com/docs/test_multi_environments).

**Comment by aditikul** [comment]
@Ivashkin @numaanashraf Did you try environments? Should be able to solve your request.
