### ISSUE TITLE
Inline editing of enviroment parameters

### ISSUE THREAD

**Issue by paolobiavati** [a85/POSTMan-Chrome-Extension#1309]
Hi, 

It could be glad to edit enviroment parameters from the Quick View popup

**Comment by a85** [comment]
Agree. That's a cool idea.

**Comment by adis-io** [comment]
+1
I like this feature in Insomnia.

**Comment by JohannesRudolph** [comment]
Yes, please! Shouldn't be too hard to implement either and saves a ton of clicks in my daily workflow

**Comment by vkaegis** [comment]
Hey guys, you can now edit the current value of an environment variable from the quick-look window itself. We have some more improvements around this flow scheduled for future releases, so stay tuned. Closing this for now, feel free to open another issue if you have more feedback around this.
