### ISSUE TITLE
<title> postman issue

### ISSUE THREAD

**Issue by muneeb0305** [a85/POSTMan-Chrome-Extension#13106]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

Can anybody help me
Issue in Postman: When I don't log in to Postman and test socket events with a JSON payload, I receive an object. But when I log in to Postman and call socket events, I receive a string.

### Describe the solution you'd like

What i do i sm using mac

**Comment by parthverma1** [comment]
Hi @muneeb0305 
Can you provide some more details and steps to replicate the issue that you are facing? 
After logging in, are you receiving a string as a response from the server or are you receiving a string at the server? 

Also, it is unclear from the description if you are using Websockets or Socket.io, can you please clarify which one are you facing issues with? If it is Socket.io, can you also let us know the version of Socket.io that you are facing issues with?

Thanks
Parth

**Comment by muneeb0305** [comment]
Hi @parthverma1 
I am facing issue only on postman.
I am using socket.io
If i not login to postman.
When i send json from postman i received object which is fine but
When i login to postman and call my socket event same i send json from postman but receive string in nest

Code is working fine i check in window laptops. I am facing it in mac only

**Comment by parthverma1** [comment]
Got it. I was able to replicate the issue, and have enabled a fix for it. It should start working for you again.
Feel free to re-open this issue if the problem recurs.

**Comment by muneeb0305** [comment]
Thank you soo much its working perfectly
