### ISSUE TITLE
All form field entries lost on first sync after update on 3.0

### ISSUE THREAD

**Issue by thirtified** [a85/POSTMan-Chrome-Extension#1311]
All entered form fields in my collections seem to be gone after the automatic update to 3.0 :(.

Unfortunately, this isn't the first time I had to recreate my collections after syncing had messed them up, very annoying work. Could there be a way to make syncing more stable, and maybe an option to undo such sync changes?

Thanks,
- Julian

**Comment by abhijitkane** [comment]
Hi Julian, Can you send an email to help@getpostman.com with your Postman username, and the requests from which data went missing?

**Comment by thirtified** [comment]
Actually, the missing fields turned out to be still contained in the locally exported collection data. And after a Postman restart (or a few?) they showed up again, whew.

Sorry for the alarm, and thanks Abhijit for the quick response.

**Comment by thirtified** [comment]
(Still, you may want to look into getting this behaviour fixed, I guess?)

**Comment by abhijitkane** [comment]
Of course. We'll investigate why this could have happened in the first place.
