### ISSUE TITLE
Setting variable from array

### ISSUE THREAD

**Issue by awright7979** [a85/POSTMan-Chrome-Extension#1312]
Hi, 

I am struggling to extract the data from an array to set as a variable. Our array is returned like this

{
  "policy": [
    {
      "id": 4,
      "name": "Test 3"
    },
    {
      "id": 5,
      "name": "Test 3"
    },
}

and I would like to be able to take the last value, so in this instance 5 and set it as a variable to run through several other tests, with it ultimately being deleted. How do I do this?

Many thanks

**Comment by abhijitkane** [comment]
Check out the docs at https://www.getpostman.com/docs/jetpacks_examples. 

`var data = JSON.parse(responseBody);
tests["Your test name"] = data.value === 100;`

You can parse the response into an object, and use `postman.setEnvironmentVariable("id",data.policy[data.policy.length-1].id)` to store 5 into the environment variable.

You can use console.log() in your tests to print out values for debugging. Check http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for steps to view the console.

**Comment by awright7979** [comment]
Excellent, thank you!

**Comment by awright7979** [comment]
Thank you very much for this, 

How would I then go about setting an object from an array within another array?

{
 "user profile":{
                        "email_address" : "test@test.com",
                          "addresses" : [
                                                 {
                                                   "id":1
                                                  },
                                                {
                                                   "id":1
                                                  },
                                                ]
