### ISSUE TITLE
Rest API called with SOAPUI works but I got an error when I call the API with postman

### ISSUE THREAD

**Issue by iboumedien** [a85/POSTMan-Chrome-Extension#1313]
Hi,

Well done for your great job guys. I'm opening today this issue about some problem I'm facing in my project. I'm exposing API and when I want to test it with postman I got an error, one of my collegue test it with SOAPUI and the API works as expected. 

Can you please share with us some ideas, or if someone faced an error like mine. I test post with other APIs and it works fine really wired.

By the way can you tell if any debug mode exist and how we can use it if that is possible.

Thanks a lot for your help.

Best regards

Ismael :)

**Comment by abhijitkane** [comment]
You can inspect the exact request and response payloads. Check out blog post at http://blog.getpostman.com/2015/06/13/debugging-postman-requests/.

**Comment by iboumedien** [comment]
@abhijitkane Thanks for your answer.
