### ISSUE TITLE
Error message: "Data file format is not right..."

### ISSUE THREAD

**Issue by A570343** [a85/POSTMan-Chrome-Extension#1314]
I was experimenting with using a CSV file for a run in which each parameter is in its own column instead of being one continuous string.

Pass: 
1605+Amphitheatre+Parkway,+Mountain+View,+CA

Fail (Each word is in its own column)
1605   Amphitheatre  Parkway,  Mountain  View,  CA

Attachment:
![data format is not right](https://cloud.githubusercontent.com/assets/13588309/9044566/8f95e912-39eb-11e5-9656-678fc6a3369f.PNG)

**Comment by abhijitkane** [comment]
Hm..we'll fix the error reporting in a future release. Can you send the CSV file (the first few lines would do) to help@getpostman.com?

**Comment by A570343** [comment]
This site doesn't allow me to upload CSV files so I took a screenshot.
![csv 2](https://cloud.githubusercontent.com/assets/13588309/9045033/848ec6d0-39ee-11e5-996c-318d7dde6d53.PNG)

There was another issue I ran into in which the Runner hung after I imported the following CSV file then clicked Run.
![csv](https://cloud.githubusercontent.com/assets/13588309/9044976/35b9e648-39ee-11e5-8e48-f0b486f1db0b.PNG)

**Comment by abhijitkane** [comment]
On an unrelated note - The first line of the file needs to contain the column names - see the file at https://www.getpostman.com/docs/jetpacks_examples (the last line)

I tried using the same data you have, but it worked for me? Can you send it to help@getpostman.com as an attachment?
