### ISSUE TITLE
Unable to See postman extension Interface

### ISSUE THREAD

**Issue by Amit-Sanuria** [a85/POSTMan-Chrome-Extension#13150]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Failed to fetch recent workspaces: received unexpected data from server
![postman-issue](https://github.com/user-attachments/assets/9ed65536-e9ec-4560-8bf0-d6848d283091)

### Steps To Reproduce

1. Add the postman extension to VS code and login.

### Screenshots or Videos

![postman-issue](https://github.com/user-attachments/assets/a233f166-7960-44bd-b659-f734a828383e)

### Operating System

Windows

### Postman Version

v1.2.1

### Postman Platform

Other

### User Account Type

Signed In User

**Comment by pankajk07** [comment]
@kferrone Can you try setting the `Http: Proxy Support` to `override` in VS Code and retry logging in?

<img width="1466" alt="image" src="https://github.com/user-attachments/assets/5da3d5b2-de9e-47e4-b8ea-97b983afaae9">

**Comment by pankajk07** [comment]
@Amit-Sanuria  Can you try setting the `Http: Proxy Support` to `override` in VS Code and retry logging in?

<img width="1466" alt="image" src="https://github.com/user-attachments/assets/5da3d5b2-de9e-47e4-b8ea-97b983afaae9">

**Comment by kferrone** [comment]
This is a duplicate. 
https://github.com/postmanlabs/postman-app-support/issues/13107

**Comment by Amit-Sanuria** [comment]
Thank you. It worked.
