### ISSUE TITLE
curl code behaves differently for basic authentication with redirect

### ISSUE THREAD

**Issue by BE-Code** [a85/POSTMan-Chrome-Extension#13158]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

I am sending a POST request with basic authentication to a test server that uses ngrok. When it was working correctly I copied the cURL code for it, but it failed. This was because it uses `--location` rather than `--location-trusted`. It appears that the default behavior for Postman is to send the authentication each time when automatically following redirects, but this is not reflected in the cURL output. 

### Steps To Reproduce

1. Create a POST Request
2. Go to Authorization tab
3. Set Auth Type to Basic Auth
4. Populate the username and password
5. Send the request to an ngrok url for a server that requires basic auth

### Operating System

macOS

### Postman Version

11.13.1

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by VShingala** [comment]
@BE-Code Thanks for reporting the issue! `--location-trusted` may come with some level of security risk in cases when you're not very certain of host where you're making the request to. As such it doesn't make much sense to change this behavior in all cases. For collection request, you can configure such behaviour with below setting.

![Screenshot 2024-09-27 at 11 54 34 AM](https://github.com/user-attachments/assets/9536fb82-2cc8-46fe-889f-456921a17449)

We considered adding a similar option under cURL snippet settings (see image below) to generate the correct snippet with `--location-trusted`. This setting will persist at user level so you'll not have to keep changing this. Let us know if you have any suggestions to this.

![image](https://github.com/user-attachments/assets/e5394b93-df5f-4da4-a176-86b1f0124cc1)

**Comment by aman-v-singh** [comment]
@BE-Code @VShingala I am closing this issue, Please feel free to re-open this if there are any further comments.
