### ISSUE TITLE
Feature Request: Allow Requests to be persisted to disk when you press save

### ISSUE THREAD

**Issue by kensykora** [a85/POSTMan-Chrome-Extension#1316]
For our development workflow, it would be ideal if when you saved a postman request, it could be persisted to disk automatically without having to hit save, and download the entire collection. This would allow us to easily save requests in version control (Which we can already do) in a way that would allow for logical changes to be sent to git.

Ideally for large projects, where requests gets into the 100's, if these could be split into multiple files that can be named (maybe one file per request or collection folder?) that'd also be preferred.

Additionally, if timestamps could be eliminated from these, that'd be ideal also, since that's just noise in version control.

**Comment by saeliux** [comment]
+1

**Comment by internationalbridgeinc** [comment]
+1

**Comment by a85** [comment]
Postman collections can be exported and put on disk. We don't have any plans in the near term for file-folder driven workflows. Closing this for now as we get through the rest of the issues on the tracker.

**Comment by kensykora** [comment]
@a85 Why? Is there an alternate solution for using Postman in a continuous delivery environment? We would like to persist the tests to version control (as you mentioned, we can export... while this works, it is far from ideal -- Postman cloud isn't a good substitute because it is not under version control) and then have newman run the tests.
