### ISSUE TITLE
API - Invite Group to Workspace

### ISSUE THREAD

**Issue by Ty-R** [a85/POSTMan-Chrome-Extension#13177]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

Yes. Using the API, it is possible to: 
* Create a private workspace ✅ 
* Create a group (through SCIM) ✅
* Add users to a group ✅

But inviting that group to that workspace seems to require the UI, making it manual step.

### Describe the solution you'd like

For the API to be extended to support inviting groups to a workspace. Here's an example to further help visualise:

![image](https://github.com/user-attachments/assets/2bc90653-b4b3-4320-ab9f-52b4bb31d375)

### Describe alternatives you've considered

The only alternative is to invite groups through the workspace settings UI.

**Comment by davidespihernandez** [comment]
Thanks for your question, @Ty-R!
It makes sense to me... I'll check the possibility of exposing this API in the SCIM endpoints.

**Comment by shruti-paranjape** [comment]
Hi @Ty-R, 
you can use the [Workspaces > Roles Patch](https://www.postman.com/postman/workspace/postman-public-workspace/request/12959542-133e2d90-ce1f-4309-ac77-0635bbc24696?action=share&source=copy-link&creator=16034861) request to add a usergroup to a workspace. [Here](https://www.postman.com/postman/workspace/postman-public-workspace/example/12959542-c8656089-e70b-4f02-9f6a-cc2de20b5466?action=share&source=copy-link&creator=16034861) is an example with SCIM Id, you can add using the group id as well.
