### ISSUE TITLE
Setting a variable from an array within an object

### ISSUE THREAD

**Issue by awright7979** [a85/POSTMan-Chrome-Extension#1318]
Hi,

I am struggling to extract the data from an array within an array to set as a variable. How would I set the variable from the ID, listed within address

{
"user profile":{
"email_address" : "test@test.com",
"addresses" : [
                     {
                     "id": 1
                       },
                       {
                     "id": 1
                       },
                       ]

For a single array I use 
var data = JSON.parse(responseBody); 
postman.setEnvironmentVariable("AddressID",data.user_address[data.addresses.length-1].id);

I'm not quite sure how to use the console log as advised yesterday, if that is the answer to this issue.

Many thanks

**Comment by abhijitkane** [comment]
@awright7979 You'll need to use 
```
postman.setEnvironmentVariable("AddressID",data.address[data.addresses.length-1].id);
console.log(environment.AddressID);
```

Console output will show up as described in https://www.getpostman.com/docs/errors
