### ISSUE TITLE
postman app render bug on 21:9 screen or HDR screen(?

### ISSUE THREAD

**Issue by fat-so** [a85/POSTMan-Chrome-Extension#13182]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

https://github.com/user-attachments/assets/48bd60db-189c-4326-abad-dc21a12f2fd3

https://github.com/user-attachments/assets/7f5b6f84-2a44-4ac4-a15b-a8f4e466104c

This is an issue I encountered on Windows 11 (23H2).

I have three monitors:

4K 16:9
2K 21:9
1080P 16:9
As shown in the video, Postman experiences a flickering issue on the 21:9 monitor. (However, screen recording cannot capture this.)

The problematic 21:9 monitor has refresh rate options of 60Hz, 120Hz, 144Hz, and 165Hz available, as well as HDR functionality. But regardless of adjusting the refresh rate or toggling HDR, there's a flickering issue that resembles rendering errors.

The monitor with the issue is the LG UltraGear WQHD 21:9 (34GP63A-B).

This problem does not occur on the other monitors.

Below is the rest of my hardware configuration:

CPU: Ryzen 7 7800X3D
Graphics Card: NVIDIA RTX 4070
Memory: 64GB DDR5 6000MHz

### Steps To Reproduce

1. open postman APP
2. use it on 21:9 monitor

### Screenshots or Videos

https://github.com/user-attachments/assets/48bd60db-189c-4326-abad-dc21a12f2fd3

https://github.com/user-attachments/assets/7f5b6f84-2a44-4ac4-a15b-a8f4e466104c

### Operating System

Windows

### Postman Version

11.15.0

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by numaanashraf** [comment]
@fat-so Could you try disabling Hardware Acceleration and let us know if that improves rendering?

https://learning.postman.com/docs/introduction/troubleshooting-inapp/#hardware-acceleration

**Comment by fat-so** [comment]
@numaanashraf 
thanks, it's fix with disable Hardware Acceleration ,it's work fine now
