### ISSUE TITLE
Team Sync Environment Settings

### ISSUE THREAD

**Issue by Tombo890** [a85/POSTMan-Chrome-Extension#1319]
We are starting to use the team features(syncing api calls) for our team and I'm hoping that we can spread its use across the org. One feature that is missing in the sync though is the ability to include environments in the sync so that we don't manually have to send them to everyone and have them import them. Our environments are somewhat stable but there is always something changing, so for our org this would prove to be extremely important to keep everyone in sync.

**Comment by abhijitkane** [comment]
We'll be introducing a feature that accomplishes this soon, but I can't offer an ETA at the moment.

**Comment by Tombo890** [comment]
That sounds amazing! Our entire team is excited about the update.

**Comment by GarthVader** [comment]
Excellent!  Just downloaded Team Sync and have been searching for that feature to no avail...thought I was missing some documentation.  Looking forward to this much needed addition.  Hopefully, it can be prioritized, as it seems an essential ingredient to efficiently working in team environments.  Muchos gracias!

**Comment by ewoods** [comment]
One workaround I've used successfully is to use the Pre-request script to set my environment and global variables.  The request url can be something like www.google.com -- something quick and available.

For our team, we have one request that sets the global variables. That only needs to be submitted once.  Then we have several other requests, each one of which sets the environment variables for a different environment.  Simply submit the request for the environment you want to start working with, and you're good to go.

**Comment by nextrevision** [comment]
Is this still in progress? I see the ability to create environment templates, but that workflow seems largely unidirectional (create an environment template once, and share it). Modifying that after the fact and distributing the changes seems to also be missing. It would be great to have the ability to sync/commit environment variables between members of the team while maintaining local, unsynced variables for secrets.

**Comment by dhiren-mudgil-olx** [comment]
+1

**Comment by lukasvan3l** [comment]
+1
We don't use the environment settings for authentication credentials, but for URL's to production or test environments. Ideally each team member can modify these and they get synced to all other team members, and monitoring.

**Comment by a85** [comment]
Environment templates are now transitioned off to environments through our new feature called Workspaces. More info here: https://www.getpostman.com/docs/postman/workspaces/intro_to_workspaces
