### ISSUE TITLE
Env.-Collection Variable Bug

### ISSUE THREAD

**Issue by rctann** [a85/POSTMan-Chrome-Extension#13206]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Even though the collection variable I defined was used when making the request, the environment from a previous request remained selected. Since the variable names are the same in both, the request ends up sending the environment's variable values instead of the collection's. However, in the code snippet section, it appears as if the collection variable has been sent. I was able to identify this issue by examining the incoming request during the response generation.

here is the screenshots:
1. When i forget env disabled:
![image](https://github.com/user-attachments/assets/afe48152-72a1-475d-ac68-f4ece93696ac)

2. When i select no env.
![image (1)](https://github.com/user-attachments/assets/39ab1238-b8d2-49bb-9b86-55a91f0b4215)

I prefer collection variable to send before env. 

### Steps To Reproduce

1. Open new collection
2. adding collection variable like "username"
3. open env.
4. adding env. variable like "username"
5. select env. then use variable in request
6. disabled env. then use variable in request

### Operating System

Windows

### Postman Version

11.16.1

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by ronork** [comment]
Your response looks good! Here it is with a minor adjustment for clarity:

Hey @rctann,

I followed your steps but was unable to reproduce the issue. In my request, the environment variable takes precedence over the collection variable when they share the same name, and if the environment is inactive, the collection variable will take precedence. To clarify, Postman prioritizes variable scopes in the following order, from broadest to narrowest: global, collection, environment, data, and local. This is reflected in the video below:

[Watch the video](https://github.com/user-attachments/assets/8d3ffafe-8db1-4658-af3f-2592d350efe2)

For more details on how variable precedence works in Postman, please refer to the documentation [here](https://learning.postman.com/docs/sending-requests/variables/variables/).

If you have any additional information or specific scenarios, please let me know!
