### ISSUE TITLE
Not executing all folders using newman command

### ISSUE THREAD

**Issue by praveenrtzen** [a85/POSTMan-Chrome-Extension#13207]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

I have collection which has 8 folder and sub-folders inside those. when I'm executing this collection ,only 6 folders are getting executed and not remaining 2. Not sure why this is happening, I have multiple collections, only one collection have this problem. Folder structure is correct and everything seems fine.

### Steps To Reproduce

this is my function
```
async executeNewman(serviceName) => {
        var total_assertions = 0;
        var failed_assertions = 0;
        try {
            const collectionPath = await Utils.getCollectionPath(serviceName);
            const environmentPath = await Utils.getCollectionEnvFilePath(serviceName);
            const globals = Utils.getGlobalEnvFile();
            const { summary } = await new Promise((resolve, reject) => {
                newman.run({
                    collection: collectionPath,
                    environment: environmentPath,
                    globals: globals,
                    reporters: ['htmlextra', 'cli'],
                    reporter: {
                        htmlextra: {
                            export: Utils.getReportsPath(),
                        },
                    },
                    exportEnvironment: environmentPath
                }, function (err, summary) {
                    if (err) {
                        reject(err);
                    } else {
                        resolve({ summary });
                    }
                });
            });
            total_assertions = summary.run.stats.assertions.total;
            failed_assertions = summary.run.stats.assertions.failed;

            console.log("total_assertions : " + total_assertions);
            console.log("failed_assertions : " + failed_assertions);
        } catch (error) {
            console.error("Error running Newman:", error);
        }
    }
```

### Operating System

macOS

### Postman Version

11.10.1

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by DannyDainton** [comment]
Hey @praveenrtzen 

Are you able to run only that single Collection with Newman to debug this further?

Does the Collection contain any `setNextRequest()` statements at only level?

**Comment by praveenrtzen** [comment]
Hi,

I have collection something like this
collection
  |
  ---- setup
  |
  ---- folder1 (having apis and some of them have setNextRequest in post
scripts)
  |
  ---- folder 2
  |    |
       --- sub folder 1
  |    |
       --- sub folder 2
  |
  ---- folder 3
  |    |
       --- sub folder 1
  |    |
       --- sub folder 2
  |
  ---- folder 4
  |
  ---- folder 5
  |
  ---- folder 6

and here is function which will execute this collection

```
async test(serviceName) => {
var total_assertions = 0;
var failed_assertions = 0;
try {
const collectionPath = <collection_path>;
const environmentPath = <env_file_path>;
const globals = <global_file_path>;
const { summary } = await new Promise((resolve, reject) => {
newman.run({
collection: collectionPath,
environment: environmentPath,
globals: globals,
reporters: ['htmlextra', 'cli'],
reporter: {
htmlextra: {
export: <report_folder_path>,
},
},
exportEnvironment: environmentPath
}, function (err, summary) {
if (err) {
reject(err);
} else {
resolve({ summary });
}
});
});
total_assertions = summary.run.stats.assertions.total;
failed_assertions = summary.run.stats.assertions.failed;

console.log("total_assertions : " + total_assertions);
console.log("failed_assertions : " + failed_assertions);
} catch (error) {
console.error("Error running Newman:", error);
}
}
```

folder 1 to 4 are executing as expected but folder 5 and 6 are not
executing and cannot see in newman report.

I have around 10 collections like this, but there is no problem with other
collection files, I'm facing problem with this collection only.

**Comment by DannyDainton** [comment]
What does the last request in Folder 4 contain? Can you share the post-response script?

When you run that Collection in the Collection Runner, does it also not run those folders? 

The issue would be in that Collections Folders or Requests - Something, likely a script, will be in there controlling the workflow. Providing more details about the Collection will help here.

**Comment by praveenrtzen** [comment]
I found one issue in my script only , I will fix it from my end and sorry
for this. Thank you so much for your support.

**Comment by DannyDainton** [comment]
Just for clarity - What was the issue?

**Comment by praveenrtzen** [comment]
There was a setNextRequest(api1) line, and this api1 doesn't exist anymore.
so I removed it and now it's working fine.

**Comment by DannyDainton** [comment]
Awesome. I'll close out this issue.

**Comment by praveenrtzen** [comment]
Yes please.
