### ISSUE TITLE
Postman overrides window switching in OS X

### ISSUE THREAD

**Issue by todgru** [a85/POSTMan-Chrome-Extension#1320]
OS X 10.10.2
Chrome Version 44.0.2403.125 (64-bit)
Postman Version 3.0.5 (packaged)

When I {Command-Tab} between Chrome, Postman or other open application windows, any attempt to switch focus back to Chrome is overridden and the Postman App becomes the focus.

When Postman is running:
I am able to switch to other non-Chrome applications from Postman.
I am able to switch from other applications to Postman.
I am unable to switch from other applications to Chrome.
I am unable to switch from Postman to Chrome.

I can override this behavior by using the mouse to click the Chrome window.

**Comment by bobber205** [comment]
+1

**Comment by abhijitkane** [comment]
This is currently a limitation of the Chrome App Platform on OSX. Once Postman is in focus, you can use {Command + ~} to switch between Postman/Chrome.

Command-Tab switches between window groups. Command-Tilde switches within a window group. Postman and the Chrome window are part of the same group on OSX. The behaviour is different on Windows, not sure why.

**Comment by todgru** [comment]
If this is the case, then Postman should not have its own application icon in the Command+Tab popup. Allowing Postman to imply native application behavior when it doesn't implement it correctly causes confusion.

Launching Postman in a Chrome tab is an option since it lacks functionality to behave correctly in OS X as a standalone app. https://github.com/postmanlabs/postman-app-support/issues/366

**Comment by todgru** [comment]
I agree that this is an issues with Chrome and its implementation of plugins. https://groups.google.com/a/chromium.org/forum/#!topic/chromium-apps/RHoijNfs68c

**Comment by Bouke** [comment]
Any plans on a native app for Postman to resolve this issue? It doesn't appear Google is going to fix this problem any time soon.

**Comment by a85** [comment]
We have a Mac app out now people that solves these issues once and for all. Get it here: https://www.getpostman.com/apps

**Comment by juanvillegas** [comment]
thanks, I always hated that soooo much
