### ISSUE TITLE
Response Body Not Refreshing For Visual Studio Code Insider

### ISSUE THREAD

**Issue by YTKme** [a85/POSTMan-Chrome-Extension#13215]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

When sending Request with Response Body, the first Request returns the Response Body correctly, but subsequent Request does not. Have to click off the Response Body tab (like to Headers), and click back to Response Body to reload the Body.

### Steps To Reproduce

1. Launch Request in VSCode Insider
2. Send the Request for first time
3. Update code
4. Send the Request for second time

### Screenshots or Videos

https://github.com/user-attachments/assets/f9978c13-e79f-48ba-b673-bb8a04a1a78b

### Operating System

macOS

### Postman Version

1.3.0

### Postman Platform

Postman VSCode Extension

### User Account Type

Signed In User

### Additional Context?

Information:
* Visual Studio Insider Version: 1.95.0-insider

**Comment by bertek41** [comment]
This also happens in stable version. When I receive JSON response it doesn't format it and response body not refreshing.

Version: 1.95.0 (user setup)
Commit: 912bb683695358a54ae0c670461738984cbb5b95
Date: 2024-10-28T20:16:24.561Z
Electron: 32.2.1
ElectronBuildId: 10427718
Chromium: 128.0.6613.186
Node.js: 20.18.0
V8: 12.8.374.38-electron.0
OS: Windows_NT x64 10.0.22631

Name: Postman
Id: Postman.postman-for-vscode
Description: Streamline API development and testing with the power of Postman, directly in your favorite IDE.
Version: 1.3.0
Publisher: Postman
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=Postman.postman-for-vscode

**Comment by gabrielalmir** [comment]
It doesn't work on the stable version as mentioned. I also noticed that the 'Raw' and 'Preview' tabs work fine; the bug only occurs (for me, at least) on the 'Pretty' tab. Also it doesn't format the output result at all.

Version: 1.95.0 (user setup)
Commit: 912bb683695358a54ae0c670461738984cbb5b95
Date: 2024-10-28T20:16:24.561Z
Electron: 32.2.1
ElectronBuildId: 10427718
Chromium: 128.0.6613.186
Node.js: 20.18.0
V8: 12.8.374.38-electron.0
OS: Windows_NT x64 10.0.22631

Name: Postman
Id: Postman.postman-for-vscode
Description: Streamline API development and testing with the power of Postman, directly in your favorite IDE.
Version: 1.3.0
Publisher: Postman
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=Postman.postman-for-vscode

![image](https://github.com/user-attachments/assets/156aac71-06e9-4ed6-8558-a511effdd63b)

**Comment by martin-d-rentcard** [comment]
I have the same issue and exactly as described by @gabrielalmir , it only occurs in the "pretty" tab.
Version: 1.3.0

I also found out that collapsing and extending the response tab will update the response correctly.

![image](https://github.com/user-attachments/assets/775cf11a-74fc-4679-a004-2f8a9680ba13)

**Comment by ibrahim-sma** [comment]
Currently I am observing 2 issues in my POSTMAN in VS Code APP. Looks like both has open issues 
Issue1: Response body pretty option is not working (Existing Issue #13230 )
Issue2: Glitch in Response received. Same as [#13215 ](https://github.com/postmanlabs/postman-app-support/issues/13215)
Postman always displays the older response, instead of current one.
Steps to Repro Issue2:
- Perform a new Request in VScode. Current State: Request1, Response1
- Perform another request in VSCode for same resource. Current State: Request2, Response1
- Now switch tabs in response body and check the response. Current State: Request2, Response2
Description:
When multiple requests on performed on the same resource, the response is always of the (n-1)th request.

**Comment by alexeychikk** [comment]
I thought I'm going nuts for a minute :)
https://github.com/user-attachments/assets/ff78ad95-c701-4a0a-be51-a136f928072f

**Comment by pankajk07** [comment]
Duplicate of #13230

**Comment by ab-on-git** [comment]
The Issue of Response not refreshing is present in v1.5.0 (MacOS)

**Comment by agas0077** [comment]
works fine on postman 1.16.1 and vscode 1.104

**Comment by kayenp** [comment]
still running into this issue with postman 1.16.2 and vscode 1.104.2

**Comment by rooton** [comment]
Seems like no one even care :)

Postman: 1.16.2
VSC: Version: 1.104.3

**Comment by nategasser** [comment]
Still happening on Postman v 1.17.0 and VSC 1.105.1 (Universal)

**Comment by onesyndrome** [comment]
Still an issue with Postman v 1.18.0 and VSCode v1.106.2

**Comment by antoine-dorard** [comment]
Still happening on Postman v1.19.1 and VSCode v1.109.0

**Comment by yAlqubati** [comment]
Same problem here on VSCode v1.116.0 and Postman v1.19.1

**Comment by m-walters** [comment]
STILL an issue on 1.19.1, Aug 11 2026

**Comment by jedked1313** [comment]
The same bug occurs on version 1.19.1. Switching the response section body from 'pretty' to 'raw' fixes the issue for me.
