### ISSUE TITLE
Postman black screen

### ISSUE THREAD

**Issue by BhoneThantCho** [a85/POSTMan-Chrome-Extension#13217]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

When I open postman,the app is **black screen**.

![Screenshot 2024-10-22 180815](https://github.com/user-attachments/assets/a4aac1cd-09ff-4d45-bdc8-8b1814801223)

After a few minutes,I got this screen[[Figure below](https://github.com/user-attachments/assets/c417b1df-ecd6-4838-9ef0-6238038091b8)].And i can't switch my workspace bcz when i click "Switch to workspace",it is nothing work.

![Screenshot 2024-10-22 180750](https://github.com/user-attachments/assets/c417b1df-ecd6-4838-9ef0-6238038091b8)

**Please help me**

### Steps To Reproduce

And also when i click app bar some btn,nothing work.
Do any other have this issues??

### Screenshots or Videos

.

### Operating System

Windows

### Postman Version

latest version

### Postman Platform

Postman App

### User Account Type

Signed In User

### Additional Context?

.

**Comment by BhoneThantCho** [comment]
.

**Comment by DannyDainton** [comment]
Hey @BhoneThantCho 👋🏻 

That doesn't look like the _latest version_ to me, it look very old. 

Have you taken that from here?

https://www.postman.com/downloads/

**Comment by BhoneThantCho** [comment]
Yep,It is now solved.Bcz of my Internet.Now,I use postman with vpn

**Comment by DannyDainton** [comment]
Are we good to close this now

**Comment by BhoneThantCho** [comment]
Yes, good to close.
