### ISSUE TITLE
Postman extension issue

### ISSUE THREAD

**Issue by techpearlselva** [a85/POSTMan-Chrome-Extension#13211]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

In vs code postman extension is not opening for new http request.

### Steps To Reproduce

1. open the extension
2. Nothing is shown/displayed

### Operating System

Linux

### Postman Version

1.3.0

### Postman Platform

Postman VSCode Extension

### User Account Type

Signed In User

**Comment by pankajk07** [comment]
@techpearlselva, Can you please share a screen recording and more details about the problem? That would help us debug the issue.

**Comment by pankajk07** [comment]
@techpearlselva I am closing the ticket as we did not get more details from your side. Feel free to re-open the ticket whenever you have more details available.
