### ISSUE TITLE
Remove basic auth headers

### ISSUE THREAD

**Issue by stuartrivero** [a85/POSTMan-Chrome-Extension#1322]
Postman continues to send basic auth headers once No Auth is selected.

Steps to reproduce:
- create a request with Basic Auth
- send request
- change dropdown to No Auth
- send request

**Comment by abhijitkane** [comment]
Once you send a request with BasicAuth selected, Postman will add a header. Even if Basic Auth is not selected, you'll need to go to the Headers tab and remove the header that was set earlier.

**Comment by stuartrivero** [comment]
If I remove the header Postman will still send it.
It will only remove it if the credentials are wrong.

**Comment by abhijitkane** [comment]
I'm not able to reproduce this in version 3.0.5.

See the screen recording here - http://tinypic.com/r/20t5quh/8
1. Send a request with No Auth, no header > No header sent in request
2. Add Basic Auth, Send request > Header is added in the request
3. Remove header, remove auth, send request > No header sent in request

**Comment by stuartrivero** [comment]
I see what I'm meant to do following the screen recording, thanks.
However, it makes more sense to me that the header should not be sent if you select No Auth.

**Comment by peletiah** [comment]
I'm still having the issue initially reported by @stuartrivero, even after following the indicated steps. Please see this screencast, where I run postman in the upper and wireshark in the lower half of the screen: https://gfycat.com/HonorableUnfoldedHydra
