### ISSUE TITLE
Response JSON is displayed in a single line instead of pretty format in Postman extension for VS Code

### ISSUE THREAD

**Issue by suetaaaaa** [a85/POSTMan-Chrome-Extension#13231]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

I'm experiencing an issue with the Postman extension in VS Code where JSON responses are being displayed as a single line, even though the Pretty option is selected. Previously, responses were formatted with appropriate indentation, making them easier to read. This problem started recently, and I've confirmed that the Pretty setting is active.

### Steps To Reproduce

1. Open VS Code and launch the Postman extension.
2. Send a request that returns a JSON response.
3. Check the response body – it appears in a single line instead of the expected formatted, pretty version.

### Screenshots or Videos

![image](https://github.com/user-attachments/assets/0e96f278-7842-42c2-876f-7866cf3f1759)

### Operating System

Windows

### Postman Version

1.3.0

### Postman Platform

Postman VSCode Extension

### User Account Type

Signed In User

**Comment by nilaygit-10721** [comment]
can you assign me this issue?

**Comment by suetaaaaa** [comment]
> can you assign me this issue?

What do you mean by "assign"?

**Comment by sarah-gelt** [comment]
+1 same issue here

<img width="1907" alt="image" src="https://github.com/user-attachments/assets/4d8716cb-804d-4f52-aa5c-2cedc9d1813c">


VSCode details
```
Version: 1.95.0 (Universal)
Commit: 912bb683695358a54ae0c670461738984cbb5b95
Date: 2024-10-28T20:16:24.561Z
Electron: 32.2.1
ElectronBuildId: 10427718
Chromium: 128.0.6613.186
Node.js: 20.18.0
V8: 12.8.374.38-electron.0
OS: Darwin arm64 23.6.0
```

Postman plugin details
<img width="976" alt="image" src="https://github.com/user-attachments/assets/058d1f2b-c28f-4a33-82b1-4d8be0492d79">

**Comment by suetaaaaa** [comment]
@sarah-gelt do you sometimes have an empty response body until you switch between the "body", "cookies" and so on tabs?

**Comment by sarah-gelt** [comment]
> @sarah-gelt do you sometimes have an empty response body until you switch between the "body", "cookies" and so on tabs?

Yes, I get that as well.

**Comment by suetaaaaa** [comment]
So, I found the cause of the problem. It was the latest version of VS Code (1.95.1). As soon as I downgraded to 1.94.2, the Postman extension started working correctly.

**Comment by Dev-wonderful** [comment]
> So, I found the cause of the problem. It was the latest version of VS Code (1.95.1). As soon as I downgraded to 1.94.2, the Postman extension started working correctly.

@suetaaaaa I don't think you should close this issue, the postman team still needs to be aware of this problem. We don't know if it's a bug on VS Code side or it is something that was introduced in the new version of VS Code that the postman team needs to account for.

**Comment by Dev-wonderful** [comment]
Never mind this is a duplicate

**Comment by suetaaaaa** [comment]
@Dev-wonderful yeah, you are right.

**Comment by jmaster03** [comment]
Were you guys able to find a solution for this issue?

**Comment by suetaaaaa** [comment]
@jmaster03 you mean solution for the latest VS Code version?

**Comment by jmaster03** [comment]
> @jmaster03 you mean solution for the latest VS Code version?

I mean I'm still receiving the JSON responses in one line and also have an empty response until I switch from Preview to Pretty

**Comment by suetaaaaa** [comment]
> I mean I'm still receiving the JSON responses in one line and also have an empty response until I switch from Preview to Pretty

Did you downgrade you VS Code?

**Comment by jmaster03** [comment]
> > I mean I'm still receiving the JSON responses in one line and also have an empty response until I switch from Preview to Pretty
> 
> Did you downgrade you VS Code?

Oh that actually worked, thank you!

**Comment by pankajk07** [comment]
Duplicate of https://github.com/postmanlabs/postman-app-support/issues/13230

**Comment by seklund** [comment]
VS Code 1.102.0, Postman extension 1.14.0, same problem

**Comment by rishavbharti** [comment]
@seklund 

We're unable to replicate this issue on our end. To help us determine if this is specific to certain system configurations, could you please provide the following details?
1. Operating System and version
2. Processor
3. Available RAM and storage
4. Screenshot(s) of the behavior 
5. Does this issue persist even after reopening the request tab or IDE?

**Comment by rishavbharti** [comment]
Hi @seklund,

If you are still experiencing this issue, would you be open to a quick call to help us understand your setup and demonstrate the issue in your environment?
You can book a time with me here: https://calendly.com/rishav-bharti-postman/30min

Thank you for your help!

**Comment by agas0077** [comment]
Still not working on postman 1.16.1 and vscode 1.104

**Comment by bennich** [comment]
+1 - not working: vscode: Version: 1.104.3, postman: 1.16.2

**Comment by bbracamonte** [comment]
> [@seklund](https://github.com/seklund)
> 
> We're unable to replicate this issue on our end. To help us determine if this is specific to certain system configurations, could you please provide the following details?
> 
> 1. Operating System and version
> 2. Processor
> 3. Available RAM and storage
> 4. Screenshot(s) of the behavior
> 5. Does this issue persist even after reopening the request tab or IDE?

it does not persist on reopening vscode, but after a few responses it breaks again. same thing if you do Developer: Restart Extension Host.
