### ISSUE TITLE
Update tv4 validator ?

### ISSUE THREAD

**Issue by cyrildubus** [a85/POSTMan-Chrome-Extension#1323]
Hi, 

It seems your tv4 validator is not up to date. 

Indeed, it had a bug with null and object comparison, fixed 2 month ago by this commit https://github.com/geraintluff/tv4/commit/ba58a8b231733fe29c11a6a72b7f6f6daf8ebc2c

And I think I'm still running into this bug.

Do you confirm you are not up to date ? If so, can you update ?

Thanks a lot !

**Comment by a85** [comment]
We will update this. @abhijitkane

**Comment by a85** [comment]
@shamasis Can we close this?

**Comment by shamasis** [comment]
Yes. Tv4 is latest in sandbox.
