### ISSUE TITLE
Postman in VSCode doesn't format JSON correctly.

### ISSUE THREAD

**Issue by RichardYusteDAW** [a85/POSTMan-Chrome-Extension#13230]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

I press the pretty option, but it doesn't format the line breaks correctly.

VSCode 1.95

### Steps To Reproduce

1. press the pretty option

### Screenshots or Videos

![Captura](https://github.com/user-attachments/assets/39a04827-97f5-4705-93d0-be1765410063)

### Operating System

Windows

### Postman Version

1.3

### Postman Platform

Other

### User Account Type

Signed In User

**Comment by chemargar** [comment]
Richard, Do you have a temporal solution to this issue? I tried to change to a lower version of this extension but It doesn't work

**Comment by sarah-gelt** [comment]
+1 same issue here

<img width="1907" alt="image" src="https://github.com/user-attachments/assets/4d8716cb-804d-4f52-aa5c-2cedc9d1813c">


VSCode details
```
Version: 1.95.0 (Universal)
Commit: 912bb683695358a54ae0c670461738984cbb5b95
Date: 2024-10-28T20:16:24.561Z
Electron: 32.2.1
ElectronBuildId: 10427718
Chromium: 128.0.6613.186
Node.js: 20.18.0
V8: 12.8.374.38-electron.0
OS: Darwin arm64 23.6.0
```

Postman plugin details
<img width="976" alt="image" src="https://github.com/user-attachments/assets/058d1f2b-c28f-4a33-82b1-4d8be0492d79">

**Comment by eroSilva** [comment]
+1 same issue here

VSCode details
```
Version: 1.95.0 (Universal)
Commit: 912bb683695358a54ae0c670461738984cbb5b95
Date: 2024-10-28T20:16:24.561Z (2 days ago)
Electron: 32.2.1
ElectronBuildId: 10427718
Chromium: 128.0.6613.186
Node.js: 20.18.0
V8: 12.8.374.38-electron.0
OS: Darwin arm64 23.6.0
```

Postman extension version: 
`v1.3.0`

**Comment by bordom** [comment]
+1 same issue here

Postman extension version:
v1.3.0

Running on macOS 14.7
with VSCode:
> Version: 1.95.1
Commit: 65edc4939843c90c34d61f4ce11704f09d3e5cb6
Date: 2024-10-31T05:14:54.222Z (1 day ago)
Electron: 32.2.1
ElectronBuildId: 10427718
Chromium: 128.0.6613.186
Node.js: 20.18.0
V8: 12.8.374.38-electron.0
OS: Darwin arm64 23.6.0

Also it might be worth mentioning that subsequent REST calls do not update the response in the "Pretty" view.
Only the "Raw" view is updated with the new response data.

**Comment by kakhagh** [comment]
same here

Version: 1.95.1
Commit: 65edc4939843c90c34d61f4ce11704f09d3e5cb6
Date: 2024-10-31T05:14:54.222Z
Electron: 32.2.1
ElectronBuildId: 10427718
Chromium: 128.0.6613.186
Node.js: 20.18.0
V8: 12.8.374.38-electron.0
OS: Linux x64 5.15.0-124-generic

however response from _https://postman-echo.com/get?a=1&b=2_ is formatted....

**Comment by duwejeferson** [comment]
Same here, Win 11 with WSL

Version: 1.95.1 (system setup)
Commit: 65edc4939843c90c34d61f4ce11704f09d3e5cb6
Date: 2024-10-31T05:14:54.222Z
Electron: 32.2.1
ElectronBuildId: 10427718
Chromium: 128.0.6613.186
Node.js: 20.18.0
V8: 12.8.374.38-electron.0
OS: Windows_NT x64 10.0.22631

**Comment by Dev-wonderful** [comment]
The temporary solution to this as highlighted in issue #13231 is to downgrade your VS Code version to 1.94.2, I haven't tried it but it works for the person

**Comment by DebbieB1** [comment]
Same.   Seems like this is a recent issue.   I thought I'd clicked a formatting button somewhere and messed things up. 

Version: 1.95.1 (user setup)
Commit: 65edc4939843c90c34d61f4ce11704f09d3e5cb6
Date: 2024-10-31T05:14:54.222Z
Electron: 32.2.1
ElectronBuildId: 10427718
Chromium: 128.0.6613.186
Node.js: 20.18.0
V8: 12.8.374.38-electron.0
OS: Windows_NT x64 10.0.19045

**Comment by Salty-Sailor** [comment]
Due to VSCode being upgraded to version 1.95.1, my current workaround is to downgrade back to 1.94.2. Waiting for the official fix for this bug :)

**Comment by jaysonsosweet** [comment]
Annnnnnnnnnd.... same here.

**Comment by Bejjoeqq** [comment]
Same here :)

**Comment by divergent-synapse** [comment]
Oh, I thought I messed up a setting. Same issue here!

**Comment by DebbieB1** [comment]
Yeah, I wasted a good bit of time trying to figure out what I'd done wrong.  Rolling back to 1.94.2 has me working for now.

Has anyone seen an ETA on this fix?  I'm not sure if I want to turn off automatic updates for now or not so that I don't have to keep rolling back.

**Comment by juliboron** [comment]
+1

**Comment by pankajk07** [comment]
Hey folks, the issue seems to be in the underlying chrome of the latest version (`1.95.1`) of VSCode. We have raised the problem with the VSCode team in [here](https://github.com/microsoft/vscode/issues/233060) and await their response.

As of now the only possible way to mitigate this is to downgrade your VS Code to an older version like `v1.94.2`. 
We are actively tracking this issue and will update here if there is any development.

**Comment by ibrahim-sma** [comment]
Currently I am observing 2 issues in my POSTMAN in VS Code APP. Looks like both has open issues 
Issue1: Response body pretty option is not working (Existing Issue #13230 )
Issue2: Glitch in Response received. Same as [#13215 ](https://github.com/postmanlabs/postman-app-support/issues/13215)
Postman always displays the older response, instead of current one.
Steps to Repro Issue2:
- Perform a new Request in VScode. Current State: Request1, Response1
- Perform another request in VSCode for same resource. Current State: Request2, Response1
- Now switch tabs in response body and check the response. Current State: Request2, Response2
Description:
When multiple requests on performed on the same resource, the response is always of the (n-1)th request.

**Comment by pankajk07** [comment]
Update: The VS Code team has recommended launching the VSCode instance by executing the following command. 

```
code --disable-features=PlzDedicatedWorker
```

Currently, this is the mitigation step for this issue. 
The VS Code team has added the issue to their November milestone and hopefully will be fixed in the next release

**Comment by ibrahim-sma** [comment]
> Update: The VS Code team has recommended launching the VSCode instance by executing the following command.
> 
> ```
> code --disable-features=PlzDedicatedWorker
> ```
> 
> Currently, this is the mitigation step for this issue. The VS Code team has added the issue to their November milestone and hopefully will be fixed in the next release

Thanks @pankajk07 After using this workaround both the issues got resolved #13215 #13230

**Comment by parth-fundrev** [comment]
same issue here

**Comment by bibble235** [comment]
Thanks, suggested fix of running --disable-features=PlzDedicatedWorker worked for me

**Comment by alimr70** [comment]
Same issue. The suggested fix --disable-features=PlzDedicatedWorker didn't work on MacOs

**Comment by pankajk07** [comment]
@alimr70 Can please try the given command after quitting all of the instances of VS Code

<img width="381" alt="Screenshot 2024-11-08 at 10 58 07 AM" src="https://github.com/user-attachments/assets/b18eee75-4a71-4438-b856-e5ea177ee698">

**Comment by vuk-ivanovic-ananas** [comment]
Tnx this helped on mac after turning off vs code

**Comment by dzsoldado** [comment]
Still having the same issue, it only started after updating VS Code

Windows 11
 
Postman:
- Postman VS Code Extension Version: 1.4.1

VS Code:
- Version: 1.95.2 (user setup)
- Commit: e8653663e8840adaf45af01eab5c627a5af81807
- Date: 2024-11-07T11:07:22.054Z
- Electron: 32.2.1
- ElectronBuildId: 10427718
- Chromium: 128.0.6613.186
- Node.js: 20.18.0
- V8: 12.8.374.38-electron.0
- OS: Windows_NT x64 10.0.22631

**Comment by seanodaniels** [comment]
Same issue, and the `--disable-features=PlzDedicatedWorker` workaround worked for me. TY, and I am looking forward to a fix.

> Version: 1.95.2 (user setup)
> Commit: e8653663e8840adaf45af01eab5c627a5af81807
> Date: 2024-11-07T11:07:22.054Z
> Electron: 32.2.1
> ElectronBuildId: 10427718
> Chromium: 128.0.6613.186
> Node.js: 20.18.0
> V8: 12.8.374.38-electron.0
> OS: Windows_NT x64 10.0.22631

**Comment by admin-lafarga** [comment]
@seanodaniels how did you get it to work? 

I'm running from terminal in the correct directory:
`.\Code.exe --disable-features=PlzDedicatedWorker`

but it's still showing the output bad formatted

Which version of the extension are you using?

**Comment by pankajk07** [comment]
@LaFargaYCS  Can you make sure that you close out all instances of VS Code completely before running this command?

**Comment by seanodaniels** [comment]
> @seanodaniels how did you get it to work?
> 
> I'm running from terminal in the correct directory: `.\Code.exe --disable-features=PlzDedicatedWorker`

> 
> but it's still showing the output bad formatted
> 
> Which version of the extension are you using?

I am using Postman extension v1.4.1. 

FWIW, I am on Windows and this is what I did.

- Create a Windows desktop shortcut for VS Code
- Right click on the shortcut and choose Properties
- In the resulting window, enter this into the "Target" field:

`"C:\Users\sodan\AppData\Local\Programs\Microsoft VS Code\Code.exe" --disable-features=PlzDedicatedWorker`

YMMV.

**Comment by lAmirshahinxl** [comment]
same here
I know it reason (It for new vs code version)
I still waiting for new postman release to it automatically fix

**Comment by akiraacs** [comment]
Same error for me.

Version: 1.95.3 (user setup)
Commit: f1a4fb101478ce6ec82fe9627c43efbf9e98c813
Date: 2024-11-13T14:50:04.152Z
Electron: 32.2.1
ElectronBuildId: 10427718
Chromium: 128.0.6613.186
Node.js: 20.18.0
V8: 12.8.374.38-electron.0
OS: Windows_NT x64 10.0.19045

**Comment by GianniCodato-PixartPrinting** [comment]
Same problem here.
Thank you for the workaround
Looking forward to here news about a fix

**Comment by gilbertomarcano** [comment]
Same error here. Workaround didn't work.

**Comment by WorkHardes** [comment]
same issue for me on code version 1.95.3 on arch linux

**Comment by uzbeki** [comment]
any progress?
VSCode version 1.95.3 
Windows 11 x64

**Comment by Perdolique** [comment]
Doesn't work in 

> Postman `1.4.1`
> VSCode `1.95.3`

**Comment by AdaoNatalino** [comment]
Same thing, workaround doesn't work for me.

**Comment by sonht1109** [comment]
Also, did u guys get issue like, the body response still keep showing the previous result when we choose "Pretty" tab? I mean it didnt show the latest result of api regardless of multiple API calling times.

https://github.com/user-attachments/assets/5606cf86-4268-4414-a233-cc5a0edb4f8b

**Comment by pankajk07** [comment]
> Also, did u guys get issue like, the body response still keep showing the previous result when we choose "Pretty" tab? I mean it didnt show the latest result of api regardless of multiple API calling times.
> 
>  Screen.Recording.2024-11-28.at.10.22.43.mov

@sonht1109 That is another side-effect of the underlying VS Code changes that caused the issue mentioned in here.

**Comment by itsjasur** [comment]
Any update?

**Comment by Perdolique** [comment]
Postman extension `v1.5.0` still has this issue.

**Comment by pknrs** [comment]
Still not working as of now, --disable-features=PlzDedicatedWorker workaround works perfectly.

**Comment by farissmechbal** [comment]
Same here.
Postman extension v1.5.0
Version: 1.95.3
Commit: f1a4fb101478ce6ec82fe9627c43efbf9e98c813
Date: 2024-11-13T14:50:04.152Z
Electron: 32.2.1
ElectronBuildId: 10427718
Chromium: 128.0.6613.186
Node.js: 20.18.0
V8: 12.8.374.38-electron.0
OS: Darwin arm64 24.1.0

**Comment by markvu2607** [comment]
same here.

**Comment by abmenzel** [comment]
+1

**Comment by ashoknar** [comment]
+1

**Comment by codewithleader** [comment]
Same here...

**Comment by codewithleader** [comment]
> Update: The VS Code team has recommended launching the VSCode instance by executing the following command.
> 
> ```
> code --disable-features=PlzDedicatedWorker
> ```
> 
> Currently, this is the mitigation step for this issue. The VS Code team has added the issue to their November milestone and hopefully will be fixed in the next release

you're the best! 🚄

**Comment by alex-unruh** [comment]
+1

**Comment by pankajk07** [comment]
The VS Code team has released the new version (`v1.96.0`), which fixes the extension's formatting and stale response issue. Please update your VS code version and continue working on the Postman extension.

**Comment by D-jazic** [comment]
still actual in Pretty response view mode, extension version 1.12.1, Windows 11 (if important)

![Image](https://github.com/user-attachments/assets/b6a40305-e800-41ee-b94b-695c5db12050)

**Comment by agas0077** [comment]
Still not working on postman 1.16.1 and vscode 1.103.2

**Comment by AdrianCarreno** [comment]
> Still not working on postman 1.16.1 and vscode 1.103.2

It did work in the past, but it broke again in the last 2 months.

**Comment by pankajk07** [comment]
@AdrianCarreno The formatting issue is due to an underlying issue in the VS Code platform. We are tracking this issue in here. https://github.com/postmanlabs/postman-app-support/issues/13735#issuecomment-3224065998

As a workaround, please launch your VS Code instance by executing the following command

```
code --disable-features=PlzDedicatedWorker
```

**Comment by datasci-iopsy** [comment]
I can confirm that solution proposed by @pankajk07 worked!

Postman Extension Info:
- Identifier: `postman.postman-for-vscode`
- Version: `1.19.1`
- Last Updated: `22 hours ago` (2025-12-17 ~16:53 CET)
- Size: `124.45MB`

VS Code Info:
```
1.107.0
618725e67565b290ba4da6fe2d29f8fa1d4e3622
arm64
```

**Comment by asavov-roku** [comment]
@pankajk07 this still does not work, including disabling the feature.  Latest everything on MacOS.

**Comment by pankajk07** [comment]
@asavov-roku Can you please try out the solution mentioned in here https://github.com/postmanlabs/postman-app-support/issues/13735#issuecomment-3392298164, and check if that solves the issue?
