### ISSUE TITLE
Allow me to copy the full repsonse to clipboard

### ISSUE THREAD

**Issue by bitbonk** [a85/POSTMan-Chrome-Extension#1324]
In postman in can copy the full http request as plain text using the "Generate Code Snippet" feature (using "HTTP" in the combobox). It would be cool to be able to do the same thing for the response. Allow me to copy the full response (including headers, body, and status code) as text.

I am constantly using this in other tools for docmentation and for comunicating with my team members.

**Comment by a85** [comment]
The Postman Console now gives you the full response that can be copy/pasted: https://www.dropbox.com/s/snd0tvd7vsv1uvj/Screenshot%202017-11-11%2010.43.17.png?dl=0
