### ISSUE TITLE
Colored Banners for Different Environments

### ISSUE THREAD

**Issue by mchandschuh** [a85/POSTMan-Chrome-Extension#13247]
### Is there an existing request for this feature?

- [x] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

It is very easy to accidentally run a request against the run environment. In many systems, different banner colors are used to make it obvious to the user which environment they're executing against.

### Describe the solution you'd like

Any solution that makes it obvious which environment I'm running requests against. My initial thought was similar to how chrome profiles changes the color of the browser window, we could optionally enable environments to change the color of the postman application window with the ability to set colors based on environments. My application has certain colors based on environments so they dev/test teams know which environment they're executing against. I would want to be able to use the same colors in postman for consistency.

### Describe alternatives you've considered

The other things I can think of involve confirmation clicks which would just be annoying, but would also be nice for _really_ sensitive requests that perhaps should never be run against certain environments.

**Comment by skatikia** [comment]
@mchandschuh Thank you for the feedback! This has been on our to-do, and we also have a rough idea of how to solve it. I would love to walk you through our ideas and see if they suit your problem. If you're open to a discussion on this, do book a slot that suits you the best on [this calendly link](https://calendly.com/shobhit-katikia/meet-with-shobhit).

**Comment by giridharvc7** [comment]
Duplicate of https://github.com/postmanlabs/postman-app-support/issues/903

**Comment by kiddynomite** [comment]
I have been looking for the exact same solution and have been following thisince #903.

**Comment by megamax34** [comment]
This is the biggest downfall for the use of Environments in Postman and the repercussions stumble into bigger management issues such as maintaining and syncing a different workspace or collection for each environment. This simple thing is becoming a deal breaker for our org.
