### ISSUE TITLE
Arrays not working in Tests

### ISSUE THREAD

**Issue by boblindman** [a85/POSTMan-Chrome-Extension#1325]
This code used to work before the upgrade to Postman 3.0 (3.0.5 to be specific)

```
var data = JSON.parse(responseBody);

for (i = 0; i <=20; i++) {
  if (data._links[i]) {
    tests[data._links[i].Rel+" = "+data._links[i].Href] = true;
    postman.setEnvironmentVariable(data._links[i].Rel, data._links[i].Href);
  }
}
```

The array component [i] makes it return "undefined". If I fully qualify the data link (such as `data._links.token.href`, it works fine, but that defeats the purpose of this code.  

Any pointers? Or just a bug?

**Comment by abhijitkane** [comment]
Can you try adding a `console.log(data._links)` before your loop? Check http://blog.getpostman.com/2015/06/13/debugging-postman-requests/ for steps to view the console.

If `data._links` is an array, I'm not sure how you're expecting it to have a `token` property.

**Comment by boblindman** [comment]
See the screenshot for the result.
`data._links` is an array of objects. The real issue, as I mentioned, is in Postman 2.0 this worked fine. I made no change and it broke when I upgraded to 3.0

![screenshot_080515_050150_pm](https://cloud.githubusercontent.com/assets/2180106/9097784/ba085938-3b93-11e5-86c7-49945b1bb709.jpg)

**Comment by abhijitkane** [comment]
Hm..that might have been a bug with the older app. 
For now, you can use:

```
for(key in data._links) {
  if(data._links.hasOwnProperty(key)) {
     tests[data._links[key].Rel+" = "+data._links[key].Href] = true;
     postman.setEnvironmentVariable(data._links[key].Rel, data._links[key].Href);
  }
}
```

**Comment by boblindman** [comment]
Thanks for the feedback.  I needed a slight change to your code to get it to work, but it's working well now.  My final version is below in case anyone has a similar issue. 

```
var data = JSON.parse(responseBody);

for(key in data._links) {
  if(data._links.hasOwnProperty(key)) {
     tests[key+" = "+data._links[key].href] = true;
     postman.setEnvironmentVariable(key, data._links[key].href);
  }
}
```
