### ISSUE TITLE
Export Collection directly from APIs Tab

### ISSUE THREAD

**Issue by Adham-Abdelwahab** [a85/POSTMan-Chrome-Extension#13256]
### Is there an existing request for this feature?

- [X] I have searched the existing issues for this feature request and I know that duplicates will be closed

### Is your feature request related to a problem?

In order to export a collection within an API, I must first copy it to collections, then export it.

### Describe the solution you'd like

I would like to have export collection available in the dropdown within the APIs tab. That includes the 3 dots at the top right, not just the 3 dots when hovering over the collection.

### Describe alternatives you've considered

The alternative is to copy the api collection to collections, then export. I think since this can be done then the export feature should carry over easily to collections in the api tab.

### Additional context

Sorry if there is a way of doing this and I didn't find it.

**Comment by shashankawasthi88** [comment]
Hi @Adham-Abdelwahab, thanks for raising the request. Can you expand on your complete workflow - how are you using the API object, why do you need to export the collection, what do you do with the exported collection, etc?

**Comment by Adham-Abdelwahab** [comment]
Hello @shashankawasthi88 , thanks for taking the time to address this.

I am working on an enterprise API with many endpoints but common base paths. I group the endpoints with common base paths into a collection, and have 5 collections in the API.

Documentation is written for each base path, so the grouping is fine. The documentation needs the postman collection posted to it, and in order to do that, I have to copy each collection to collections first.

Since collections can already be exported, I am hoping it would be a small update to add this feature, so made this request.

**Comment by shashankawasthi88** [comment]
@Adham-Abdelwahab can we schedule a short call to discuss this? It will be helpful for us to understand the workflow better and we can suggest some best practices regarding sharing the collections. 
You can schedule a call with me using this [link](https://calendly.com/shashank-awasthi/typed-information-in-collections-clone)

**Comment by Adham-Abdelwahab** [comment]
@shashankawasthi88 , thank you again for taking the time to address this issue. Workspaces is indeed the solution I was looking for.
