### ISSUE TITLE
VS Code extension is too slow when uploading file

### ISSUE THREAD

**Issue by Oluwa-pamilerin** [a85/POSTMan-Chrome-Extension#13251]
Type: <b>Bug</b>

This postman is too slow when uploading a file

Extension version: 1.4.1
VS Code version: Code 1.95.1 (65edc4939843c90c34d61f4ce11704f09d3e5cb6, 2024-10-31T05:14:54.222Z)
OS version: Windows_NT x64 10.0.26100
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|13th Gen Intel(R) Core(TM) i5-1335U (12 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.72GB (2.47GB free)|
|Process Argv|--folder-uri file:///c%3A/Users/oluwa/OneDrive/Desktop/Projects/Bukstagram/Bukstagram_Backend --crash-reporter-id 6ed16849-1ae4-46ba-8d54-8fd0d289b7bf|
|Screen Reader|no|
|VM|80%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
9c06g630:31013171
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31102340
nativerepl1:31139838
pythonrstrctxt:31112756
cf971741:31144450
iacca1:31171482
notype1:31157159
5fd0e150:31155592
dwcopilot:31170013
h409b430:31179529

```

</details>

**Comment by indraneel-postman** [comment]
Hi @Oluwa-pamilerin 

The file selection seems to be breaking with the latest VSCode version 1.95.*
As of now, you can downgrade your VS Code to an older version like v1.94.2 to mitigate this issue.
We are actively tracking this issue and will update here if there is any development.

**Comment by indraneel-postman** [comment]
Hi @Oluwa-pamilerin 
We'll be tracking this issue in https://github.com/postmanlabs/postman-app-support/issues/13266.
Closing this one. Please follow the mentioned issue for updates.
