### ISSUE TITLE
Response is not updated after every new request if seen in pretty mode

### ISSUE THREAD

**Issue by HarromPS** [a85/POSTMan-Chrome-Extension#13260]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Hi, 

I wanted to test some code for my app in vs code using the Postman extension, so I tested my API endpoint with payload and wanted a response. It worked fine, for the correct payload, and I was getting the proper response.

But when tested for the wrong payload, the response was not changed when I was in the pretty view, but the status code was changed to 500. This means everything was working fine, except the response was not updated for new requests.

Then I switched to raw mode, which works fine as it should.

Here

1) works fine for correct data
![correct](https://github.com/user-attachments/assets/94e4db59-519e-4131-a788-6f8e859510d2)

2) Incorrect data is used, the status code is 500, and still response is not refreshed
![wrong1](https://github.com/user-attachments/assets/25fb23b9-0c46-406b-9292-54a10da07e74)

3) response updated when switched to raw mode
![wrong2](https://github.com/user-attachments/assets/bc181b0b-fc48-4dc4-a355-8610e80de376)

4) works fine if working in raw mode 
![wrong3](https://github.com/user-attachments/assets/3600525d-0bb0-49a6-975e-cca6c3f96232)

I think this is a bug with pretty mode.
Please look into this and correct me if I was wrong anywhere.

### Steps To Reproduce

1. Create an API endpoint in Nodejs (mine was in Nodejs) and see in pretty mode.
2. First return a response with data and status 200.
3. Then return an error with status 500.
4. Do the steps 2 and 3 in raw mode again.

### Operating System

Linux

### Postman Version

v1.4.1

### Postman Platform

Postman VSCode Extension

### User Account Type

Signed In User

**Comment by indraneel-postman** [comment]
Hi @HarromPS 
This issue is happening due to an internal change in VSCode from v1.95.1 onwards. There is already an [issue](https://github.com/postmanlabs/postman-app-support/issues/13230) for tracking this and we have raised a bug with Microsoft team as well. Refer to this comment for more info-
https://github.com/postmanlabs/postman-app-support/issues/13230#issuecomment-2458788661
