### ISSUE TITLE
The response is not showing in the beauty format

### ISSUE THREAD

**Issue by admin-lafarga** [a85/POSTMan-Chrome-Extension#13265]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

I'm using version 1.4.1 of VSCode. Everything was working fine until today, but now I can't see my output in a pretty format, which makes it very hard to read. I've restarted VSCode, reinstalled the extension, and even checked with my coworker, who is experiencing the same issue.

I've tried multiple APIs (my own, public APIs...), but the problem persists.
`(2024-11-14T08:31:26.417Z) [info] [extension] Extension activation started: 1731573086412
(2024-11-14T08:31:26.433Z) [info] [extension] Extension activation completed: 1731573086433
(2024-11-14T08:31:26.433Z) [info] [extension] Extension activation took 21ms
(2024-11-14T09:04:12.679Z) [info] [extension:tabs:factory] creating a new untitled request tab
(2024-11-14T09:04:12.679Z) [info] [extension:tabs:factory] making a new identity for the untitled tab
(2024-11-14T09:04:12.679Z) [info] [extension:tabs:factory] creating a new request tab using the identity: {"tabIdentity":{"to":"/workspace/a3808840-6c1e-4d5e-87be-bac07891e073/request/create?requestId=7ddffbad-463b-4a68-8f7d-c9007604a02f"}}
(2024-11-14T09:04:12.680Z) [info] [extension:htmlProvider] getting request workbench HTML
(2024-11-14T09:04:12.761Z) [info] [extension:tabs:factory:tab] revealing the tab: {"id":{"to":"/workspace/a3808840-6c1e-4d5e-87be-bac07891e073/request/create?requestId=7ddffbad-463b-4a68-8f7d-c9007604a02f"}}
(2024-11-14T09:13:52.732Z) [info] [extension:tabs:manager] tab has been closed: {"tabId":{"to":"/workspace/a3808840-6c1e-4d5e-87be-bac07891e073/request/create?requestId=7ddffbad-463b-4a68-8f7d-c9007604a02f"}}
(2024-11-14T09:13:52.733Z) [info] [extension:tabs:factory:tab] dispose the tab
(2024-11-14T09:42:01.810Z) [info] [extension:tabs:factory] creating a new untitled request tab
(2024-11-14T09:42:01.810Z) [info] [extension:tabs:factory] making a new identity for the untitled tab
(2024-11-14T09:42:01.810Z) [info] [extension:tabs:factory] creating a new request tab using the identity: {"tabIdentity":{"to":"/workspace/a3808840-6c1e-4d5e-87be-bac07891e073/request/create?requestId=8a41cbb8-f4f6-4fb9-85c7-a17992cfd9bc"}}
(2024-11-14T09:42:01.811Z) [info] [extension:htmlProvider] getting request workbench HTML
(2024-11-14T09:42:01.848Z) [info] [extension:tabs:factory:tab] revealing the tab: {"id":{"to":"/workspace/a3808840-6c1e-4d5e-87be-bac07891e073/request/create?requestId=8a41cbb8-f4f6-4fb9-85c7-a17992cfd9bc"}}
(2024-11-14T09:50:53.518Z) [info] [extension:tabs:manager] tab has been closed: {"tabId":{"to":"/workspace/a3808840-6c1e-4d5e-87be-bac07891e073/request/create?requestId=8a41cbb8-f4f6-4fb9-85c7-a17992cfd9bc"}}
(2024-11-14T09:50:53.518Z) [info] [extension:tabs:factory:tab] dispose the tab
(2024-11-14T09:50:55.803Z) [info] [extension:tabs:factory] creating a new untitled request tab
(2024-11-14T09:50:55.803Z) [info] [extension:tabs:factory] making a new identity for the untitled tab
(2024-11-14T09:50:55.803Z) [info] [extension:tabs:factory] creating a new request tab using the identity: {"tabIdentity":{"to":"/workspace/a3808840-6c1e-4d5e-87be-bac07891e073/request/create?requestId=559e587b-cd72-4b4c-9185-27e878183390"}}
(2024-11-14T09:50:55.804Z) [info] [extension:htmlProvider] getting request workbench HTML
(2024-11-14T09:50:55.843Z) [info] [extension:tabs:factory:tab] revealing the tab: {"id":{"to":"/workspace/a3808840-6c1e-4d5e-87be-bac07891e073/request/create?requestId=559e587b-cd72-4b4c-9185-27e878183390"}}
(2024-11-14T09:51:20.713Z) [info] [extension:sidebar:adapter] fetching a correct html for the view mode: {"viewMode":"sidebar"}
(2024-11-14T09:51:20.713Z) [info] [extension:htmlProvider] get sidebar HTML
(2024-11-14T09:51:20.738Z) [info] [extension:workspaceContext] Found the record in the cache
(2024-11-14T09:55:38.123Z) [info] [extension:tabs:factory:tab] dispose the tab
(2024-11-14T09:55:38.124Z) [info] [extension:tabs:manager] tab has been closed: {"tabId":{"to":"/workspace/a3808840-6c1e-4d5e-87be-bac07891e073/request/create?requestId=559e587b-cd72-4b4c-9185-27e878183390"}}
(2024-11-14T09:55:38.124Z) [info] [extension:tabs:factory:tab] dispose the tab
(2024-11-14T09:55:41.245Z) [info] [extension] Extension activation started: 1731578141241
(2024-11-14T09:55:41.249Z) [info] [extension] Extension activation completed: 1731578141249
(2024-11-14T09:55:41.249Z) [info] [extension] Extension activation took 8ms
(2024-11-14T09:55:45.425Z) [info] [extension:sidebar:adapter] fetching a correct html for the view mode: {"viewMode":"sidebar"}
(2024-11-14T09:55:45.425Z) [info] [extension:htmlProvider] get sidebar HTML
(2024-11-14T09:55:45.434Z) [info] [extension:workspaceContext] Found the record in the cache
(2024-11-14T09:55:50.265Z) [info] [extension:tabs:factory] creating a new request tab using the identity: {"tabIdentity":{"to":"/workspace/a3808840-6c1e-4d5e-87be-bac07891e073/request/create?requestId=62aab184-ab08-430d-a9dc-c8e8f87c559a","params":{},"options":{"customNavEvent":"VIEW_COLLECTION_FOLDER_REQUEST"}}}
(2024-11-14T09:55:50.266Z) [info] [extension:htmlProvider] getting request workbench HTML
(2024-11-14T09:55:51.362Z) [info] [extension:tabs:factory:tab] revealing the tab: {"id":{"to":"/workspace/a3808840-6c1e-4d5e-87be-bac07891e073/request/create?requestId=62aab184-ab08-430d-a9dc-c8e8f87c559a","params":{},"options":{"customNavEvent":"VIEW_COLLECTION_FOLDER_REQUEST"}}}
`

### Steps To Reproduce

Just send GET request and see the output

### Screenshots or Videos

![imagen](https://github.com/user-attachments/assets/09f7aea7-5a21-4e8e-8f12-f6a0285c9fa9)

### Operating System

Windows

### Postman Version

1.4.1

### Postman Platform

Postman VSCode Extension

### User Account Type

Signed In User

**Comment by indraneel-postman** [comment]
This issue is happening due to an internal change in VSCode from v1.95.1 onwards. There is already an issue https://github.com/postmanlabs/postman-app-support/issues/13230 for tracking this and we have raised a bug with Microsoft team as well. Refer to this comment for more info-
https://github.com/postmanlabs/postman-app-support/issues/13230#issuecomment-2458788661
