### ISSUE TITLE
Never Ending File Upload Animation

### ISSUE THREAD

**Issue by shahin-m-hashim** [a85/POSTMan-Chrome-Extension#13266]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

When adding files locally to test file uploads in my server with postman, am getting a never ending loading animation. i cant select and add files from my system. When trying to add it via binary from the body tag, its infinite loading. Also when i select form-data and set files and add files nothing happens. Something is wrong with the extension.

### Steps To Reproduce

1. Select the new request tab
2. Select the body tab
3. Select binary and try to upload a file
4. Select form-data and add files

### Screenshots or Videos

![Screenshot (800)](https://github.com/user-attachments/assets/f929375f-8afe-4f72-a61d-fb2ad18390ae)

### Operating System

Windows

### Postman Version

1.4.1

### Postman Platform

Postman VSCode Extension

### User Account Type

Signed In User

**Comment by kishoreofficial** [comment]
having the same problem

**Comment by indraneel-postman** [comment]
Hi @shahin-m-hashim 
The file selection seems to be breaking with the latest VSCode version 1.95.*
As of now, you can downgrade your VS Code to an older version like v1.94.2 to mitigate this issue.
We are actively tracking this issue and will update here if there is any development.

**Comment by pankajk07** [comment]
@shahin-m-hashim This issue has been fixed in the extension's latest version (`v1.5.1`). Please update the version and try it out.
