### ISSUE TITLE
vd-code postman bug

### ISSUE THREAD

**Issue by RiteshSingh3628** [a85/POSTMan-Chrome-Extension#13279]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

After sending, request the response is not getting updated and the output screen is also not showing data in pretty manner, even after clicking the pretty button

### Steps To Reproduce

1. create a request in vs code postman extension
2. send the request 
3. response will be generated for the first time on the output screen
4. then change the http request
5. then hit the send button again 
6. the output screen does not get updated

### Operating System

Windows

### Postman Version

1.4.1

### Postman Platform

Postman VSCode Extension

### User Account Type

Signed In User

**Comment by amaldinesh7** [comment]
Duplicate https://github.com/postmanlabs/postman-app-support/issues/13230
