### ISSUE TITLE
Close all Tab

### ISSUE THREAD

**Issue by paolobiavati** [a85/POSTMan-Chrome-Extension#1327]
Why not a  "close all tabs" feature ?

thanks

**Comment by dporch** [comment]
Found an earlier request for this: https://github.com/postmanlabs/postman-app-support/issues/1263

**Comment by hlubovac** [comment]
+1
and close only tab (last one left) manually as well :)

**Comment by vegetableman** [comment]
@hlubovac closing the last tab is fixed. Check out. 
@xcen27 Closing this, as it's a duplicate. Please follow https://github.com/postmanlabs/postman-app-support/issues/1263
