### ISSUE TITLE
Displaying old response in VS Code

### ISSUE THREAD

**Issue by fullstackgod** [a85/POSTMan-Chrome-Extension#13272]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

First time sending any request using VS Code Extension I get a response as it should be. After sending next request to any other endpoint Postman displays me previous response. No matter how many responses I send after the first one it will still be displaying me response to my first request, until I click on any other display type (Raw/Preview/Pretty) in Body tab

### Steps To Reproduce

1. Send any request in VS Code extension.  
2. Look at response (Body -> Raw for example). 
![1st](https://github.com/user-attachments/assets/ca8551f7-32bb-4619-88d2-11bad00d3dda)

3. Send new request to a different end point where you should get a different response (you can send as many new requests as you want) 
![2nd](https://github.com/user-attachments/assets/a1acf076-7d73-4921-afd5-ee4137c6a530)

4. Look at the repsonse and see that it's the same response from your first request.
5. Choose any different display type (Raw/Preview/Pretty) in Body tab. 
![3rd](https://github.com/user-attachments/assets/adde91cf-bce9-4a63-9f3b-7e4e47791dfa)

6. Look at the response again and see that it finally shows the latest one.

 

### Operating System

Linux

### Postman Version

1.4.1

### Postman Platform

Postman VSCode Extension

### User Account Type

Signed In User

**Comment by pankajk07** [comment]
Duplicate #13230

**Comment by vklimov-web-dev** [comment]
> Duplicate #13230

It's not a duplicate of this issue,  the problem is that it won't display a new response **AT ALL** (after sending a new request/requests) until you force the UI to re-render by switching display types

**Comment by pankajk07** [comment]
@vvklimov The underlying root cause is same for both of these issue, hence it has been marked as duplicate and closed.

It can be mitigated with by running the VS Code instance with the given flags
```
code --disable-features=PlzDedicatedWorker
```
