### ISSUE TITLE
Feature Reqeust: Please add "read only" indicator to the API Library screen

### ISSUE THREAD

**Issue by stevemcmillen** [a85/POSTMan-Chrome-Extension#1328]
In the "API Library" view, there is no way I can tell to see if an API is read only.  I'd like to have that there to avoid making a mistake and publishing a library as read-write when I don't want to do so.

As example, here is what I see in this screen:
![postman](https://cloud.githubusercontent.com/assets/2750330/9138648/f69ffb02-3cd9-11e5-9b33-c8b0954b8e19.png)

Thanks!

**Comment by a85** [comment]
I think "read-only" has been changed to "you can view". We need to have a better marker.

**Comment by stevemcmillen** [comment]
Seems "you can view" is only when collection belongs to someone else.  I want to make sure the collections I published are read only.

**Comment by aditikul** [comment]
@stevemcmillen Have the latest updates which allow access control helped? We've worked on improving the language here and making it clearer.

**Comment by stevemcmillen** [comment]
Latest udpates are amazing.  Being able to allow multiple editors per collection is very useful.  And UX is clear now.  I think this can be closed as fully resolved.  Thanks!!
