### ISSUE TITLE
Postman extension on vscode

### ISSUE THREAD

**Issue by olaxy13** [a85/POSTMan-Chrome-Extension#13281]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Failed to fetch recent workspaces: received unexpected data from server

### Steps To Reproduce

1. I installed the postman extension on my Vscode
2. Signed in my workspace 
3. tried to open the extension after try to load for a bit, I got this message: Failed to fetch recent workspaces: received unexpected data from server

### Operating System

Windows

### Postman Version

10

### Postman Platform

Postman VSCode Extension

### User Account Type

Signed In User

**Comment by klewi1983** [comment]
I have the same issue: "Failed to fetch recent workspaces: received unexpected data from server"

![obraz](https://github.com/user-attachments/assets/840e12b2-8ce7-4010-9832-6c5012131e0c)

Logs from console:
````
(2024-12-04T09:09:34.662Z) [info] [extension] Extension activation started: 1733303374647
(2024-12-04T09:09:35.915Z) [info] [extension] Extension activation completed: 1733303375915
(2024-12-04T09:09:35.915Z) [info] [extension] Extension activation took 1268ms
(2024-12-04T09:10:28.485Z) [info] [extension:sidebar:adapter] fetching a correct html for the view mode: {"viewMode":"sidebar"}
(2024-12-04T09:10:28.486Z) [info] [extension:htmlProvider] get sidebar HTML
(2024-12-04T09:10:28.520Z) [info] [extension:workspaceContext:networkClient] fetch recent workspaces: {"baseUrl":"https://bifrost-extension-https-global.gw.postman.com/ws/proxy"}
(2024-12-04T09:10:28.834Z) [error] [extension:workspaceContext:networkClient] the network call failed: {"context":"Failed to fetch recent workspaces"}
(2024-12-04T09:10:28.841Z) [error] [extension:workspaceContext:networkClient] parsing the response failed: {"error":{"issues":[{"code":"invalid_type","expected":"object","received":"string","path":[],"message":"Expected object, received string"}],"name":"ZodError"}}
(2024-12-04T09:10:28.848Z) [error] [extension:workspaceContext] Failed to fetch the recent workspace from the API: {"type":"OTHER","details":"Failed to fetch recent workspaces: received unexpected data from server"}
(2024-12-04T09:10:28.851Z) [error] [extension:workspaceContext] Failed to retrieve recent workspaces: {"type":"NETWORK_FAILURE","details":"Failed to fetch recent workspaces: received unexpected data from server"}
````

**Comment by pankajk07** [comment]
@olaxy13 Can you try setting the `Http: Proxy Support` to `override` in VS Code and retry logging in?

<img width="1466" alt="image" src="https://github.com/user-attachments/assets/5da3d5b2-de9e-47e4-b8ea-97b983afaae9">

**Comment by klewi1983** [comment]
> @olaxy13 Can you try setting the `Http: Proxy Support` to `override` in VS Code and retry logging in?
> <img alt="image" width="1466" src="https://private-user-images.githubusercontent.com/44100113/355361097-5da3d5b2-de9e-47e4-b8ea-97b983afaae9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzODQ0OTIsIm5iZiI6MTczMzM4NDE5MiwicGF0aCI6Ii80NDEwMDExMy8zNTUzNjEwOTctNWRhM2Q1YjItZGU5ZS00N2U0LWI4ZWEtOTdiOTgzYWZhYWU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA1VDA3MzYzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdlYjk1NGZkZDEyN2MyOWM3ZTU4Njc0YjYyZGQ3MDU1ZDVkNjk0M2EzNWZjODQwYWRlOWU4OWJkNjI3MTgyYzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ZQ6azwJjvXRI8hLfHJ8CljETtzIOr-0Du9cdr8v2Hcw">

Your solution worked. I wouldn't have guessed from the logs that it was a proxy issue. Thanks!
