### ISSUE TITLE
Newman- Escaping Backslashes in Environment Variable

### ISSUE THREAD

**Issue by wirsingj** [a85/POSTMan-Chrome-Extension#1329]
Hey,  

I have a collection that runs fine in postman-  but in newman crashes upon reading in an environment variable.   The variable is a sessionID, and can contain back slashes.    It should be noted that this issue doesn't happen the FIRST time I run a collection after downloading it from postman-  only the runs after the first crash:

\K3.... kills it.

y":"CompletedSession","value":"SVpSZhWQEqhESLYRFXQBsk./RX/dNG4f8qHQ\K3om1duzLO

SyntaxError: Unexpected token K
    at Object.parse (native)
    at Object.<anonymous> (/usr/local/lib/node_modules/newman/src/utilities/VariableProcessor.js:113:32)
    at /usr/local/lib/node_modules/newman/node_modules/underscore/underscore.js:73:21
    at Function._.each._.forEach (/usr/local/lib/node_modules/newman/node_modules/underscore/underscore.js:153:9)
    at Object.jsface.Class._processEnvVariable (/usr/local/lib/node_modules/newman/src/utilities/VariableProcessor.js:103:8)
    at Object.jsface.Class.processRequestVariables (/usr/local/lib/node_modules/newman/src/utilities/VariableProcessor.js:132:8)
    at Object.jsface.Class._processUrlUsingEnvVariables (/usr/local/lib/node_modules/newman/src/runners/RequestRunner.js:295:21)
    at Object.jsface.Class._execute (/usr/local/lib/node_modules/newman/src/runners/RequestRunner.js:161:9)
    at null._onTimeout (/usr/local/lib/node_modules/newman/src/runners/RequestRunner.js:222:11)
    at Timer.listOnTimeout (timers.js:119:15)

**Comment by wirsingj** [comment]
Also-  This CompletedSession variable is generated dynamically by the server...    

Though I am still not sure why the first run after downloading the collection works, when the other runs don't.  I was thinking the postman exporter correctly escaped "\" characters, while newman was not when receiving the values-   but it doesn't fix anything to re-export the Postman Environment.

I also find it odd that its throwing this error AFTER it has used this session token in a variable in a header, and received the response:

200 600ms Cart https://*************v1/api/cart
✔ Status code is 200
✔ Has Item
✔ Correct ProductId

undefined:1
QfciUXFH7OrD-k4z3-UC3a.pYxHHhzC8_n88s9ShNI1Moux7KYdJYPzrvPjoesqrSUm\gGNM4ns4DK
^
SyntaxError: Unexpected token g
at Object.parse (native)
at Object. (/usr/local/lib/node_modules/newman/src/utilities/VariableProcessor.js:113:32)

**Comment by wirsingj** [comment]
Also-  This CompletedSession variable is generated dynamically by the server...    

Though I am still not sure why the first run after downloading the collection works, when the other runs don't.  I was thinking the postman exporter correctly escaped "\" characters, while newman was not when receiving the values-   but it doesn't fix anything to re-export the Postman Environment.

**Comment by wirsingj** [comment]
If anyone else is running into this-    add this to your strings before they are used as a hack:

.replace(/\/g , "\\")

Save a copy of the string if you need to change it back after.

EDIT: Because the parsing only fails in Newman, in your JS you may have to decide whether or not you have to manually escape backslashes depending on if you are using postman runner or newman

I used the following to check for this:

//////////////////////////////
//////  In early request:
//////////////////////////////
if (typeof window === 'undefined'){
    postman.setEnvironmentVariable("isNewman", true);
}else{
    postman.setEnvironmentVariable("isNewman", false);  
}

///////////////////////////
//////   Around where token fails:
////////////////////////////////
if(environment.isNewman === true){
    postman.setEnvironmentVariable("SessionToken", environment.SessionToken.replace(/\/g , "\\"));
}

**Comment by wirsingj** [comment]
Just curious if this issue is, or is going to be looked at?

**Comment by a85** [comment]
@wirsingj Will look into this. Thanks for reporting and sorry about the delay!

**Comment by wirsingj** [comment]
Thanks!    

Oddly enough I was able to get rid of the issue  (for now..), without really knowing what solved it-  so it may be hard to reproduce.          I noticed the parse error  only happened for 2 of my ...api/cart calls when I had several in my collection....   

Things I did which "helped" solve:
-Add junk console.log commands in the next requests pre-request scripts (deleted out after it works..)
-Remove requests which triggered parse failure completely, and add them back from a copy  (requests look identical)
-Updated Newman     (though problem persisted a for a while after update)

As I mentioned- the parse errors were odd in that they would occur AFTER sessiontoken (string that contained \ ) was used in the request... 

Sorry this is such an awkward bug to look into-  If I am able to see it again I will post an update.

**Comment by wirsingj** [comment]
Hey-  last I had heard this issue had been fixed on the development side of things, and was just waiting on testing before being released.  Its been a while since I heard that- and after updating I am still having this issue.

Sorry to bother-  just curious about the timeline of this fix.

Thanks!

**Comment by abhijitkane** [comment]
@wirsingj We've fixed this issue - we'll be pushing out a new version of Newman soon with a couple of other fixes. I'll update this thread once the update is pushed.

**Comment by wirsingj** [comment]
Great!  Thanks.

**Comment by abhijitkane** [comment]
@wirsingj Can you confirm that Newman 1.2.19 has the fix?

**Comment by wirsingj** [comment]
Looks good so far-  can't get it to fail with backslashes.  I'll post if it happens again.

Thanks!

**Comment by kajal-kumari-kr** [comment]
Hi Everyone, 
I wanted to pass "12abc&3tjhedje}}0+%ewbjk" as environment variable with newman run command. But it is giving error as "event  not found c&". so, how can i pass the string with any combination of character in environment variable.
