### ISSUE TITLE
 Incorrect Response From request with different parameters VS extension

### ISSUE THREAD

**Issue by harrison542002** [a85/POSTMan-Chrome-Extension#13294]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

So basically, I have a POST request that return list of data. 
When I enter different page number, the data still the same with previous page. 
But when i tried with POSTMAN desktop app, it works. i think it is the problem in POSTMAN VS extension.

### Steps To Reproduce

1. Open POSTMAN VS extension
2. Make two requests on whichever POST url with two different queries that returns data based on different queries.
3. And then, recheck that request in desktop app with different queries.

### Operating System

Windows

### Postman Version

1.4.1

### Postman Platform

Postman VSCode Extension

### User Account Type

Signed In User

**Comment by amaldinesh7** [comment]
Duplicate https://github.com/postmanlabs/postman-app-support/issues/13230
