### ISSUE TITLE
Postman won't display the updated response after making a new request. 

### ISSUE THREAD

**Issue by nithinraj04** [a85/POSTMan-Chrome-Extension#13306]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

No issues when submitting the first request. Then if I submit a new request and receive a new response, postman would still show me the old response. However, the status code would update. In order to see the new response, I have to either click on a different view (like pretty, raw, preview) or click on other response data like cookie and come back to what I actually want to see.

### Steps To Reproduce

1. Open new request tab
2. Send a request (POST in my case) and get a response (body more specifically)
3. Send another request that would generate a different response
4. See that the response hasn't been updated

### Operating System

Windows

### Postman Version

1.5.0

### Postman Platform

Postman VSCode Extension

### User Account Type

Signed In User

### Additional Context?

I am running postman in WSL2

**Comment by postlude** [comment]
@nithinraj04  In my case `code --disable-features=PlzDedicatedWorker` worked.
https://github.com/postmanlabs/postman-app-support/issues/13230

**Comment by nithinraj04** [comment]
@postlude Thanks, it worked for me. It now formats the JSON properly as well. 
However, this is not a permanent fix right?

**Comment by postlude** [comment]
@nithinraj04 Yes, I think https://github.com/postmanlabs/postman-app-support/issues/13230 is solved, then response updating problem also will be solved.

**Comment by pankajk07** [comment]
@nithinraj04 This is another side-effect of the underlying VS Code changes that caused the issue mentioned here. https://github.com/postmanlabs/postman-app-support/issues/13230#issuecomment-2505242319.

Closing this ticket as a duplicate of https://github.com/postmanlabs/postman-app-support/issues/13230
