### ISSUE TITLE
Postman for Mac, cannot add files to a form

### ISSUE THREAD

**Issue by DeanBDean** [a85/POSTMan-Chrome-Extension#1330]
As you can see, unlike the Chrome app I have no ability to select which file I'd like to include in the form on the Mac app

![screen shot 2015-08-07 at 11 30 47 am](https://cloud.githubusercontent.com/assets/6633897/9142933/cc92f936-3cf7-11e5-93ba-a5b6f7dd1af2.png)

**Comment by abhijitkane** [comment]
That's odd - can you open the DevTools Window (View > Toggle Dev Tools), and enter this in the console:
`$(".keyvalueeditor-value-file").css('z-index',9999);`
Are there any errors visible in the console when you open the DevTools window?

If that doesn't work, is this returning any output when entered in the console?
`$(".keyvalueeditor-value-file")`

**Comment by DeanBDean** [comment]
There are errors in the console related to a property files being called from something undefined. Let me know if there's anything else I should check

![screen shot 2015-08-11 at 12 07 49 am](https://cloud.githubusercontent.com/assets/6633897/9189896/08ab802e-3fbd-11e5-87d7-33552497df8d.png)

**Comment by abhijitkane** [comment]
Could you expand the black triangle to the left of the first message?
seems that the file chooser isn't being rendered at all for some reason.

**Comment by DeanBDean** [comment]
Sorry, here is both expanded

![screen shot 2015-08-11 at 12 38 55 am](https://cloud.githubusercontent.com/assets/6633897/9190291/7ccc56aa-3fc1-11e5-861b-79adbe78676d.png)

**Comment by abhijitkane** [comment]
@DeanBDean  Is this returning any output when entered in the console?
$(".keyvalueeditor-value-file")

**Comment by DeanBDean** [comment]
Yes, it is returning the following
![screen shot 2015-08-11 at 12 35 07 pm](https://cloud.githubusercontent.com/assets/6633897/9203484/78b2a7f4-4025-11e5-9b85-7bda626d9805.png)

**Comment by DeanBDean** [comment]
The issue went away with the latest update for Postman for Mac. Thanks so much, I really love Postman

**Comment by abhijitkane** [comment]
@DeanBDean That's odd - all we did was add debugging statements. Let us know if you see it again.
