### ISSUE TITLE
Renaming request resets method to GET with Autosave enabled

### ISSUE THREAD

**Issue by m-terhart** [a85/POSTMan-Chrome-Extension#13314]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

I like the Autosave feature and would like to keep it enabled. I know it's a beta feature.

Since the last update though, the Postman app keeps setting the HTTP method back to GET whenever I rename a request. For instance, I copy a POST request and rename the copy to something else, then Postman changes POST to GET in the copy. This only happens with Autosave on.

### Steps To Reproduce

1. Enable Autosave in the settings
2. Rename a request that has another method than GET
3. The method is reset to GET

### Screenshots or Videos

https://github.com/user-attachments/assets/1feed54c-04de-4aa2-bda5-dc567c525f40

### Operating System

macOS

### Postman Version

11.21.0

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by DannyDainton** [comment]
Hey @m-terhart,

Thanks for raising this - we are aware of the issue and the team is investigating.

We'll update this thread once we have more information 🙏🏻

**Comment by m-terhart** [comment]
Thanks for the quick response, looking forward to a solution

**Comment by VadimMinaev** [comment]
Is there any news?

**Comment by DannyDainton** [comment]
A fix for this issue has being rolled out in the latest version. 🙏🏻

**Comment by m-terhart** [comment]
The issue is fixed indeed, the method stays the same now. Thanks 👍

**Comment by upatidar7** [comment]
It is renaming existing collection requests also I have copied existing collection and it has appended copy to every request to the existing collection
