### ISSUE TITLE
Changelog for Postman Beta

### ISSUE THREAD

**Issue by A570343** [a85/POSTMan-Chrome-Extension#1331]
I recently upgraded to the latest Postman v3.0.6.2. When I go to the Wrench Icon -- Settings -- About then click on Changelog:

> It shows the log for "Version v3.0.5 (packaged) [July 22, 2015]" instead of "Version v3.0.6.2 (packaged) [August 10, 2015."
> 
> You don't need to include the letter "v" in "Version v3.0.5..." as it's redundant.

Where can I find the beta changelog?

**Comment by a85** [comment]
We'll have it up on our website soon. The changelog interface is getting a major overhaul. We have several products and in multiple stages of development and it became difficult to keep everything updated.
