### ISSUE TITLE
Method is not changing in watch list 

### ISSUE THREAD

**Issue by arsiro01** [a85/POSTMan-Chrome-Extension#13326]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

When i select the post method the logo the collection logo does not change

### Steps To Reproduce

1. Open the App 
2. Try for different request

### Screenshots or Videos

![1](https://github.com/user-attachments/assets/5ffc33e9-736b-4ef3-872b-09039d58561d)

### Operating System

Windows

### Postman Version

11.14

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by DannyDainton** [comment]
Hey @arsiro01 

If you duplicate an already saved request, the changes will only reflect once you save the new changes. 

Does it change when you save the changes?

**Comment by arsiro01** [comment]
Yes it is changing.
