### ISSUE TITLE
Changing tabs clears form-data

### ISSUE THREAD

**Issue by luveti** [a85/POSTMan-Chrome-Extension#1333]
Basically when I switch tabs all of the uncommon key/values get removed. Here's a Gyazo of the issue: https://gyazo.com/db808b058f3b689c82a99573d0094ad4

**Comment by abhijitkane** [comment]
@xDarkShadowKnightx Can you check if you see the issue in version 3.0.8 as well?

chrome:/extensions > Enable 'developer mode' > Update extensions now

**Comment by luveti** [comment]
I can't seem to be able to reproduce it. Is 3.0.8 a new version? I didn't actually check what version I was having this issue with (I probably should have!).

**Comment by abhijitkane** [comment]
Yes, we pushed this update today. The fix for the form-data issue was pushed in version 3.0.7.
Closing this now - you can open it if you see the issue again.
