### ISSUE TITLE
when try to import collection not import 

### ISSUE THREAD

**Issue by DevikaIVerma2000** [a85/POSTMan-Chrome-Extension#13346]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

when i try to import colletion of api not import after retry still not import.

### Steps To Reproduce

 click to Import.
Collection Import 
Failed to Import

### Operating System

Windows

### Postman Version

12.2.0

### Postman Platform

Postman App

### User Account Type

Signed In User

### Additional Context?

error got Failed to Import

**Comment by DannyDainton** [comment]
Hey @DevikaIVerma2000,

We're currently investigating an ongoing issue in that area. To keep all the communication in a central place, we're going to update a single issue and close out the other replicated ones. 

Please see this issue for more details, when we have more to share.

https://github.com/postmanlabs/postman-app-support/issues/13339
