### ISSUE TITLE
Collection Import Error

### ISSUE THREAD

**Issue by alok-nucleusteq** [a85/POSTMan-Chrome-Extension#13345]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Getting error or collection already exists while importing a new collection.

### Steps To Reproduce

1. Open new import tab
2. Paste collection endpoint

### Screenshots or Videos

![image](https://github.com/user-attachments/assets/5f0df272-cc91-4880-819b-be2be9a6b561)

### Operating System

Windows

### Postman Version

11.23.1

### Postman Platform

Both Postman App and Web

### User Account Type

Signed In User

**Comment by DannyDainton** [comment]
Hey @alok-nucleusteq,

We're currently investigating an ongoing issue in that area. To keep all the communication in a central place, we're going to update a single issue and close out the other replicated ones. 

Please see this issue for more details, when we have more to share.

https://github.com/postmanlabs/postman-app-support/issues/13339
