### ISSUE TITLE
Failed to import collections from my local but working fine on other systems

### ISSUE THREAD

**Issue by RajarshiAnthology** [a85/POSTMan-Chrome-Extension#13344]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

I am unable to import any collection files to postman from my local hard disk

### Steps To Reproduce

1. Open Postman
2. Click import collection
3. Select any json collection(new/existing)
4. Click Import
5

### Screenshots or Videos

![image](https://github.com/user-attachments/assets/355073cb-2bc0-49c0-85c1-3a8c28b6a885)

### Operating System

Windows

### Postman Version

11.23.1

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by RajarshiAnthology** [comment]
But the same collection can be imported correctly from other systems

**Comment by DannyDainton** [comment]
Hey @RajarshiAnthology,

We're currently investigating an ongoing issue in that area. To keep all the communication in a central place, we're going to update a single issue and close out the other replicated ones. 

Please see this issue for more details, when we have more to share.

https://github.com/postmanlabs/postman-app-support/issues/13339
