### ISSUE TITLE
Unable to import a collection , getting an error message as "import failed"

### ISSUE THREAD

**Issue by jyotirnjn45** [a85/POSTMan-Chrome-Extension#13342]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

1 . Open Postman desktop application 
2 . click on import 
3 . import the files 
4 . then choose the file of collection , then try to import the same collection . 

### Steps To Reproduce

1 . Open Postman desktop application 
2 . click on import 
3 . import the files 
4 . then choose the file of collection , then try to import the same collection . 

### Screenshots or Videos

![image](https://github.com/user-attachments/assets/7e63eac4-3501-4720-82fb-2875868127a9)

### Operating System

Windows

### Postman Version

 11.23.1

### Postman Platform

Postman App

### User Account Type

Signed In User

### Additional Context?

Unable to import a collection , getting an error message as "import failed" - 
![image](https://github.com/user-attachments/assets/065824aa-ee10-4f95-a07e-56e0db1376fe)

**Comment by DannyDainton** [comment]
Hey @jyotirnjn45,

We're currently investigating an ongoing issue in that area. To keep all the communication in a central place, we're going to update a single issue and close out the other replicated ones. 

Please see this issue for more details, when we have more to share.

https://github.com/postmanlabs/postman-app-support/issues/13339
