### ISSUE TITLE
Failed to import json collection on postman

### ISSUE THREAD

**Issue by haseebj412** [a85/POSTMan-Chrome-Extension#13341]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

i am importing a json collection with the different name but it's failing continuously, I tried clearing up postman's chache

### Steps To Reproduce

1. Import a JSON collection

### Operating System

macOS

### Postman Version

11.23.1

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by DannyDainton** [comment]
Hey @haseebj412,

We're currently investigating an ongoing issue in that area. To keep all the communication in a central place, we're going to update a single issue and close out the other replicated ones. 

Please see this issue for more details, when we have more to share.

https://github.com/postmanlabs/postman-app-support/issues/13339
