### ISSUE TITLE
Can not import Postman collection

### ISSUE THREAD

**Issue by suljosahbazovic** [a85/POSTMan-Chrome-Extension#13349]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Can not import Postman collection in the new version for Postman app

### Steps To Reproduce

- Export from Postman collection
- Open other Postman
- Try to import json collection

### Screenshots or Videos

Import Faild - Dismiss

![image](https://github.com/user-attachments/assets/b6949180-9762-472b-a73e-e1864e0f75d2)

### Operating System

Windows

### Postman Version

11.23.1

### Postman Platform

Postman App

### User Account Type

Signed In User

### Additional Context?

Import Faild - Dismiss

Failed to import collection

**Comment by DannyDainton** [comment]
Hey @suljosahbazovic,

We're currently investigating an ongoing issue in that area. To keep all the communication in a central place, we're going to update a single issue and close out the other replicated ones.

Please see this issue for more details, when we have more to share.

https://github.com/postmanlabs/postman-app-support/issues/13339
