### ISSUE TITLE
Cannot import collection

### ISSUE THREAD

**Issue by Rookxc** [a85/POSTMan-Chrome-Extension#13343]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Cannot import collections while everybody else can. I could import before.

### Steps To Reproduce

1. **Drag and drop** collection to postman or go from **settings** or **click import**.

### Screenshots or Videos

![image](https://github.com/user-attachments/assets/876bf906-0666-4600-9f30-69b56512f4ad)
![image](https://github.com/user-attachments/assets/686c399b-a3a7-484e-b16d-d39756d60b8a)

### Operating System

Windows

### Postman Version

11.23.1

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by DannyDainton** [comment]
Hey @Rookxc,

We're currently investigating an ongoing issue in that area. To keep all the communication in a central place, we're going to update a single issue and close out the other replicated ones. 

Please see this issue for more details, when we have more to share.

https://github.com/postmanlabs/postman-app-support/issues/13339
