### ISSUE TITLE
Import getting failed

### ISSUE THREAD

**Issue by AtharvaCrafts** [a85/POSTMan-Chrome-Extension#13347]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

While importing any collection its getting failed 

### Steps To Reproduce

Just import any collections and it gets failed 

### Screenshots or Videos

NA

### Operating System

macOS

### Postman Version

11.22.1

### Postman Platform

Postman App

### User Account Type

Signed In User

### Additional Context?

NA

**Comment by DannyDainton** [comment]
Hey @AtharvaCrafts,

We're currently investigating an ongoing issue in that area. To keep all the communication in a central place, we're going to update a single issue and close out the other replicated ones.

Please see this issue for more details, when we have more to share.

https://github.com/postmanlabs/postman-app-support/issues/13339
