### ISSUE TITLE
Unable to import workspace

### ISSUE THREAD

**Issue by gkvsanjeev** [a85/POSTMan-Chrome-Extension#13340]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Unable to import the workspace

### Steps To Reproduce

1. Import the json file in workspace

### Screenshots or Videos

![image](https://github.com/user-attachments/assets/898af9c5-c4a9-4fc1-bd37-273a9bece5b9)

### Operating System

Windows

### Postman Version

11.23.1

### Postman Platform

Postman App

### User Account Type

Signed In User

### Additional Context?

Unable to import the workspace

**Comment by DannyDainton** [comment]
Hey @gkvsanjeev,

We're currently investigating an ongoing issue in that area. To keep all the communication in a central place, we're going to update a single issue and close out the other replicated ones. 

Please see this iss for more details, when we have more to share.

https://github.com/postmanlabs/postman-app-support/issues/13339
