### ISSUE TITLE
Import failure 

### ISSUE THREAD

**Issue by MinaSamoeul** [a85/POSTMan-Chrome-Extension#13351]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

I use postman version 11.23.1  on windows 10 how ever when I try import form the url like the following (https://localhost:{port}/swagger/v1/swagger.json) it results in import failure and if I download the json file and try to import from that file it still didn't work. I try to use the website version still I get import failure error with no message.

### Steps To Reproduce

I tried to import endpoint from url or from json files still. I kept Getting import failure

### Operating System

Windows

### Postman Version

11.23.1

### Postman Platform

Both Postman App and Web

### User Account Type

Signed In User

**Comment by DannyDainton** [comment]
Hey @MinaSamoeul,

We're currently investigating an ongoing issue in that area. To keep all the communication in a central place, we're going to update a single issue and close out the other replicated ones.

Please see this issue for more details, when we have more to share.

https://github.com/postmanlabs/postman-app-support/issues/13339
