### ISSUE TITLE
Failed to import collection

### ISSUE THREAD

**Issue by ttp24865** [a85/POSTMan-Chrome-Extension#13350]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

导入json文件作为collection，报错Failed to import collection CAPAY API

### Steps To Reproduce

import files and confirm

### Screenshots or Videos

![图片1](https://github.com/user-attachments/assets/774190c4-6de3-4145-8b98-0f8401936a1e)

### Operating System

Windows

### Postman Version

11.23.1

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by DannyDainton** [comment]
Hey @ttp24865,

We're currently investigating an ongoing issue in that area. To keep all the communication in a central place, we're going to update a single issue and close out the other replicated ones.

Please see this issue for more details, when we have more to share.

https://github.com/postmanlabs/postman-app-support/issues/13339
