### ISSUE TITLE
Feature request: Preview URL with variables replaced

### ISSUE THREAD

**Issue by santialbo** [a85/POSTMan-Chrome-Extension#1335]
I use environment variables a lot and I miss being able to copy the URL with variables replaced so I can use it somewhere else.

It would be nice if there was an option to view the actual URL. Maybe it could be a button next to the URL that transform the URL input into a readonly input field with the variables replaced.

**Comment by moleksyuk** [comment]
:+1: 
Also feel lack of this feature when you need to send a link to someone else.

**Comment by a85** [comment]
Possible now with previews in 5.0+
