### ISSUE TITLE
NOt import collection

### ISSUE THREAD

**Issue by PurveshItaliya** [a85/POSTMan-Chrome-Extension#13353]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

[Navchetana.json](https://github.com/user-attachments/files/18164527/Navchetana.json)

i import this file but collection not import why ? sudelnley working stop 

### Steps To Reproduce

hnhhjhn

### Screenshots or Videos

![image](https://github.com/user-attachments/assets/a5f87bc2-3187-4a80-95c9-cb35e2a2f12a)

### Operating System

Windows

### Postman Version

11.23.1

### Postman Platform

Both Postman App and Web

### User Account Type

Signed In User

### Additional Context?

jnytjtyjjbnnbuhuhuihihuhiuhihuhuihuhuihy

**Comment by DannyDainton** [comment]
Hey @PurveshItaliya,

We're currently investigating an ongoing issue in that area. To keep all the communication in a central place, we're going to update a single issue and close out the other replicated ones.

Please see this issue for more details, when we have more to share.

https://github.com/postmanlabs/postman-app-support/issues/13339
