### ISSUE TITLE
import collection from .har, .json, .yml

### ISSUE THREAD

**Issue by masoome-aghayari** [a85/POSTMan-Chrome-Extension#13352]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

i wanna import a an output of type .json or .yml or .har from insomnia to postman and it cannot import it

### Steps To Reproduce

1. Open postman
2. go to a workspace
3. click import
4. select file
5. import

### Operating System

macOS

### Postman Version

11.22.1

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by DannyDainton** [comment]
Hey @masoome-aghayari,

We're currently investigating an ongoing issue in that area. To keep all the communication in a central place, we're going to update a single issue and close out the other replicated ones.

Please see this issue for more details, when we have more to share.

https://github.com/postmanlabs/postman-app-support/issues/13339
