### ISSUE TITLE
Scroll bar hard to see

### ISSUE THREAD

**Issue by mbuquet** [a85/POSTMan-Chrome-Extension#1336]
Using the dark theme, the scroll bar in the results window is difficult to see and only slightly better on the light theme.

![screenshot_081115_121504_pm](https://cloud.githubusercontent.com/assets/5396650/9204370/7fef5d3a-4022-11e5-8d9e-a9205cabfef9.jpg)

This makes it hard to click it to scroll long responses.

Thanks!

**Comment by abhijitkane** [comment]
@mbuquet Apologies for the late response. We've updated the app quite a bit, and the scrollbar has better contrast now.
