### ISSUE TITLE
Show color in request method.

### ISSUE THREAD

**Issue by Kimi-Arthur** [a85/POSTMan-Chrome-Extension#1337]
In "history" list, there different colors for different types of request methods: Green for 'GET', orange for 'POST', red for 'DELETE' etc.

But in the request construction part where you can select the type of request method to use, there is no color.

So I suggest add color for the method in the dropdown (which is grey now), or even change the color of the "Send" button (which is blue now) or the address bar (which is grey now) as a whole.

**Comment by a85** [comment]
We just couldn't agree on the colors and will keep the simple dropdown for now.

**Comment by Kimi-Arthur** [comment]
Just use the same colors in History or Collections.

Sad... I guess you guys just don't want to do this... Never mind...
