### ISSUE TITLE
JSON: URLs with escaped slashes are escaped once more (instead of UNescaped)

### ISSUE THREAD

**Issue by timri** [a85/POSTMan-Chrome-Extension#1338]
For example: when the json response contains:
`{"link":"http:\/\/www.example.com\/"}`
(as displayed in RAW-View)
in Pretty view, this is displayed as:

``` javascript
{
   "link" : "http:\\/\\/www.example.com\\/"
}
```

the legacy-version (0.9???) correctly displays them as:

``` javascript
{
   "link" : "http://www.example.com/"
}
```

**Comment by abhijitkane** [comment]
What version of the app are you on?

**Comment by timri** [comment]
Oh, sorry, forgot to add:
Version 3.0.5 (packaged)
OS: linux
Architecture: x86-64
Native client architecture: x86-64

In case this matters: I'm using chromium from debian jessie:
Chromium    43.0.2357.65 (Entwickler-Build) Built on 8.0, running on Debian 8.1 (64-Bit)

**Comment by abhijitkane** [comment]
Can you try upgrading to the latest version? (chrome://extensions > Enable 'developer mode' > Update extensions now)

**Comment by timri** [comment]
That helped, thanks.
