### ISSUE TITLE
Test script execution failed

### ISSUE THREAD

**Issue by StevenWatremez** [a85/POSTMan-Chrome-Extension#1339]
How can I debug this following error in Postman ? : 

Test script execution failed
Error message:
Cannot read property '$ref' of undefined

I have got 1500 lines of code and 50 "$ref" for this request.

**Comment by StevenWatremez** [comment]
![screen shot 2015-08-12 at 14 26 04](https://cloud.githubusercontent.com/assets/11426754/9223845/17b29610-40fe-11e5-852a-b3a7639fa67b.png)

**Comment by abhijitkane** [comment]
You can add a `console.log($ref);` after every 10 lines to check narrow it down to a set of 10. Once you have isolated a set of 10, you can add the console.log() in each of those references to $ref. To view the console output, check http://blog.getpostman.com/2015/06/13/debugging-postman-requests/

**Comment by StevenWatremez** [comment]
I have the following problem : when I try to console log the $ref, it didn't print. so I try several method to test my error.

**Comment by StevenWatremez** [comment]
In this screenshot I catch the First test where I use the $ref. but no success print instead of the first console.log()
![screen shot 2015-08-13 at 09 56 38](https://cloud.githubusercontent.com/assets/11426754/9245147/de581346-41a1-11e5-884d-a5bdded3b0f3.png)

**Comment by StevenWatremez** [comment]
I comment the test schema for trying to print $ref in the second console.log() but no success.
![screen shot 2015-08-13 at 09 56 56](https://cloud.githubusercontent.com/assets/11426754/9245168/050f053a-41a2-11e5-9662-e918b26c141f.png)

**Comment by abhijitkane** [comment]
Can you mail your entire test script to help@getpostman.com? If $ref is not defined as a variable, I'm not sure why it's throwing an error.

**Comment by StevenWatremez** [comment]
I send it to you.

**Comment by StevenWatremez** [comment]
So you have an idea why the problem is here ?

**Comment by abhijitkane** [comment]
You are referring to functions whose code is in your global variables. If any of those calls is throwing the error, you can try putting individual try..catch block around your `eval()` calls, and see what's throwing the error. Test cases support standard JavaScript, and you can use `console.log()` to help debug.

**Comment by StevenWatremez** [comment]
I put try...catch but I have the same error. I have no throw exception.

**Comment by abhijitkane** [comment]
Until you can isolate the line that's throwing the error, there's nothing we can do to help you. Can you send a sample collection which reproduces the problem?

**Comment by StevenWatremez** [comment]
I found my problem, it was the MAP enum which haven't all value, so the loop crashed. I complete the MAP and it works. Thanks for your help.
