### ISSUE TITLE
Global variables in the OAuth1.0 authentication.

### ISSUE THREAD

**Issue by haridak** [a85/POSTMan-Chrome-Extension#1340]
Can we use global variables for the key and secret values in OAuth1.0 authentication? If yes, could you give an example on how to do so?

**Comment by abhijitkane** [comment]
You just need to use {{variableName}} in the OAuth1.0 form. Make sure that variableName is a global variable, or a variable in the currently selected environment. Docs - https://getpostman.com/docs/environments

**Comment by haridak** [comment]
@abhijitkane 
I did that and got the response "Invalid OAuth Request."
I'm attaching the screenshot of the OAuth form and the global variables.

**Comment by abhijitkane** [comment]
@haridak Please remove the first image that contains your OAuth secret.

An "Invalid OAuth1 request" error need not necessarily mean that the global variables are not being replaced. Try changing your key and secret to some other values and check if the OAuth signature changes. 

To inspect the actual request payload that Postman sends, check http://blog.getpostman.com/2015/06/13/debugging-postman-requests/

**Comment by haridak** [comment]
@abhijitkane 
Authorization:OAuth oauth_consumer_key="%7B%7Bkey%7D%7D"
does it matter that the request header does not replace the key value?  I see  %7B%7Bkey%7D%7D" as  the key in the dev tool when I send the request.
The key and secret work fine if I don't include them through global variables.

**Comment by abhijitkane** [comment]
Do you see the correct values for key and secret if you click on the "x" icon (under the settings icon)? If not, you'll need to save the globals by pressing 'back'.
I tried using Global variables for OAuth1 fields, and they were replaced correctly for me

**Comment by haridak** [comment]
@abhijitkane 
Thanks. The replacement work intermittently, that is, sometimes I get the response and some other times I get the error "invalid request" for the exact same request. I think it is on me to figure this out. 

 I have one more question. The idea is to export the collection by making the key and secret as global variables so that somebody else can run the same collection using newman by changing just the key and secret. But I noticed that the exported JSON file has the key mentioned in the header of each request, and it looks like each request needs to be updated if the key and secret changes. Is there a way around this to make work in such a way that i'll need to replace in one location and the entire JSON gets updated? I hope I am making sense.

**Comment by abhijitkane** [comment]
If you save a request with the header / body fields set to {{key}} and {{secret}}, that's what the exported collection file should contain. Global variables are not included in the collection file.

Are you seeing different behavior?
