### ISSUE TITLE
Runner enhancement

### ISSUE THREAD

**Issue by A570343** [a85/POSTMan-Chrome-Extension#1342]
From my experience, it seems that if I have a CSV file that I want to use during a run and I want to run through all of the rows within the file, I have to set the Iterations to  the number of rows in the file. 

What I'd like to see is a checkbox that says something like "Iterate through all rows." When this checkbox is checked, it would:

> Gray out the Iteration fields
> Override the Iteration number
> Loop through all of the rows in the file

**Comment by davecanderson** [comment]
Perhaps if the iteration count is 0 then iterate over all items in data file. This would be useful in Runner and Newman.

The iteration count couples together the configured steps in our CI build process that use Newman with the test data files which are in source control. 

Adding new lines to the test data in SCM can trigger the CI build but that has no affect until the build scripts are updated. 

Our test team doesn't have access to the build scripts but do have access to the test data.

**Comment by sdnts** [comment]
@davecanderson That's an interesting solution. We're looking into auto-populating the iteration count when you specify a data file.

We're actually working on a redesign of the runner that does exactly this.
The new Runner is on our Canary channel, and you can download it for [OSX](https://dl.pstmn.io/download/channel/canary/osx_64) / Windows ([x86](https://dl.pstmn.io/download/channel/canary/windows_32) or [x64](https://dl.pstmn.io/download/channel/canary/windows_64)) / Linux ([x86](https://dl.pstmn.io/download/channel/canary/linux_32) or [x64](https://dl.pstmn.io/download/channel/canary/linux_32)) / [Chrome](https://chrome.google.com/webstore/detail/postman/loddepljkabcghihdkbkfknabkinanff)

I'd recommend you to join our Slack community [here](https://www.getpostman.com/slack-invite) so you can provide feedback before the runner moves to our stable builds :)

**Comment by sdnts** [comment]
Hey @davecanderson The new Runner is out with our latest version (4.9) on our native apps. This is possible now :D
