### ISSUE TITLE
Install via CLI

### ISSUE THREAD

**Issue by matuteana** [a85/POSTMan-Chrome-Extension#1343]
Hi

I would like to be able to install Postman automatically, via CLI, for a Vagrant based developer VM that I am building. Do you have any guidance to help me please?

The general guidance is here:

https://developer.chrome.com/extensions/external_extensions

And I have also seen that the CRX file could be available here:

http://www.crx4chrome.com/crx/1058/

I have also see the "Testing" section here:

https://github.com/postmanlabs/postman-app-support/wiki

But that does not quite close the loop for me.

Any and all help much appreciated.

Ana

**Comment by a85** [comment]
We have Mac and Windows apps now that can be installed this way. Linux is coming soon.

**Comment by a85** [comment]
All native apps are available on www.getpostman.com/apps
