### ISSUE TITLE
DataFile Usage for different TestCases ; Runner

### ISSUE THREAD

**Issue by prabhukirannarava** [a85/POSTMan-Chrome-Extension#1344]
Hi,

I have two different folders in postman with similar collections. Each folder represents one test case.

I am importing the test data from outside. And is as below.
[
{
    "departureStation": "MAD",
    "carrier": "AB",
    "BusNumber": "1708",
    "ticketNumber": "5069726"
},
{
    "departureStation": "AMS",
    "carrier": "BC",
    "BusNumber": "1238",
    "ticketNumber": "5069726"
}

],

My intention of using this data is to use first set of data for one test case and second set of data for second test case.

But when I run, each test case if iterating twice for each test data.

Is there a way to fulfil my request ?

**Comment by abhijitkane** [comment]
Check the docs at https://www.getpostman.com/docs/jetpacks_running_collections and the blog article at http://blog.getpostman.com/2014/10/28/using-csv-and-json-files-in-the-postman-collection-runner/.

A collection is the first categorization - a collection can have folders and requests, and folders can have requests. A request is one HTTP request (with a method, URL etc). Requests can have a test script, which defines multiple tests.

If you use the JSON file that you've mentioned, you can specify an iteration count of 2 in the runner, and the collection/folder will be run twice - once for each set of data.

**Comment by prabhukirannarava** [comment]
![expectation](https://cloud.githubusercontent.com/assets/3867237/9293002/fd86baba-4417-11e5-8e98-27a5a43278ef.png)
Hi Abhijit,

Thanks for reply.
I have gone through these links before.

I am thinking of using runner in a way testers use it.
Here is my expectation in detail. May be it could be a new feature.

Problem Description: 
I have one collection in which i have two folders. Each folder represents one test case(it has multiple tests written inside it).

I would like to send different data for each test case from outside. But the current situation is that
If I send data either as json or csv, my collection is iterating with the data I provided.
So each folder(a test case) in my collection is running for all the data I mentioned in my data.json file.
But we would want to use single set of data for each folder under my collection.As mentioned in figure.

Can you please let me know if it is already a feature in postman ?

Also I am not sure if we can break iterations when we use newman with jetpacks.

**Comment by prabhukirannarava** [comment]
Hi Abhijit,
Can you please help me with my above question ?

**Comment by abhijitkane** [comment]
In Postman, a collection is a single unit when using the collection runner. It is not possible to use different data files for folders within a collection. You'll need to split your folders into two different collections if you want to use different data files.

Newman has a `-s` option that stops the iteration as soon as a test case fails. You can set any test `tests["ToFail"]=false`, and newman will exit after this request is executed.

**Comment by sursir** [comment]
@abhijitkane 
Should i have multi collection in one project?
