### ISSUE TITLE
Can't click body tab? something i'm missing?

### ISSUE THREAD

**Issue by joshbedo** [a85/POSTMan-Chrome-Extension#1345]
I'm trying to simply change to the body tab and can't? Is their something i have to do first? I couldn't find anything in the documentation.
![](https://camo.githubusercontent.com/81f4911bb91d2821f7c2e94fe5b26ed2cb2c4915/687474703a2f2f636f6e74656e742e73637265656e636173742e636f6d2f75736572732f6a6f73686265646f2f666f6c646572732f4a696e672f6d656469612f64383761386365372d356533342d343263662d613865642d6165303335313036623964362f323031352d30382d31335f303832352e706e67)

**Comment by alexjv89** [comment]
Hi joshbedo, 

GET request does not require a body element. Hence the body tab is disabled. When you change the request type to POST/PUT etc, the body tab is enabled and editable. 

Choose the request type from the drop down (marked in the image). 
![image](https://cloud.githubusercontent.com/assets/2733923/9282631/5caebe12-42eb-11e5-93a8-c2fc1964f989.jpg)

**Comment by joshbedo** [comment]
Oh do'h, sorry didn't notice. Thanks!

**Comment by igorwojda** [comment]
This is unintuitive. You should think about hiding the "body" instead of disabling it or add some tooltip with explanation

**Comment by watadarkstar** [comment]
A tooltip would be nice!

**Comment by khalyomede** [comment]
Would gladly use Body to set my key-value pairs instead of directly passing those to the URL in a GET request. Upvote if you might find this feature useful.

**Comment by unlucio** [comment]
**Any** HTTP request message is allowed to contain a message body, than the purpose of sending it in a get _might_ be debatable, but still the standard allows for it so this seems a bit of an arbitrary choice imho.

**Comment by pagnotta** [comment]
For example Elasticsearch REST API expects the queries in a GET body...

https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-query.html

Right now it is not possible to query Elasticsearch with Postman due to Body disabled in GET.

**Comment by unlucio** [comment]
I'm not sure anyone from postman is actually reading this 🤔

**Comment by kamalaknn** [comment]
Hi @unlucio 

We are tracking this request for a new feature to attach request body with GET request in this [issue](https://github.com/postmanlabs/postman-app-support/issues/2729).

We'll update the original thread when this feature is out.

Thanks for understanding.

**Comment by sanderlissenburg** [comment]
This is still a issue on the linux version.

**Comment by simplenotezy** [comment]
This has been working just fine for me for past few months, but now today when I open postman it is greyed out, and I have lost whatever data I previously had in the "body" section. That's annoying, because it worked fine earlier. Would be very nice to get back.

**Comment by arlemi** [comment]
@simplenotezy Are you using the Postman Chrome extension? If so we've stopped supporting it for a while now, I'd recommend [downloading the app](https://www.postman.com/downloads/) from our website or trying out[ Postman in your browser](https://blog.postman.com/announcing-postman-for-the-web-now-in-open-beta/).

**Comment by simplenotezy** [comment]
@arlemi I am using Postman for Macos version 4.8.3

**Comment by arlemi** [comment]
@simplenotezy The last version of the app is 7.29, looks like yours could use an update. 😄 You can either try to upgrade through the app (though I'm not sure how it worked back then to be honest) or grab the latest version from our website. I'd recommend exporting all your collections prior to switching just in case too.

**Comment by simplenotezy** [comment]
@arlemi ahh haha. Well. It worked fine for my needs. Just really weird it is all of a sudden greyed out, especially since it ain't updated
