### ISSUE TITLE
Rails and Devise support

### ISSUE THREAD

**Issue by kgish** [a85/POSTMan-Chrome-Extension#1348]
I'd like to run tests on a Rails API server which implements Devise authentication.

Basically I need to capture the `token` and `email` json attributes  which are returned when I login:

```
{
    token: "..."
    email: "..."
}
```

and include the `Authentication header` for all following requests:

```
Token token="...", email="..."
```

How can I do this?

**Comment by qx** [comment]
it seems not work current
