### ISSUE TITLE
OAuth 2.0: asking to save whole html page as access token

### ISSUE THREAD

**Issue by aravindkk** [a85/POSTMan-Chrome-Extension#1349]
When I use the Postman chrome extension, for authenticating instagram using Oauth 2.0, I noticed that when Instagram returns a page, Postman is asking me to save the entire html page as an access token. Attaching two screenshots to show issue. 
![issue-1](https://cloud.githubusercontent.com/assets/1815535/9282930/6a71bca0-42ed-11e5-9607-a7c63bbc85f4.png)
![issue-2](https://cloud.githubusercontent.com/assets/1815535/9282931/6d5b50fc-42ed-11e5-84b5-1b654c0c1bf0.png)

**Comment by abhijitkane** [comment]
Do you have the 'request access token locally' option checked? Can you try unchecking that? I'm able to use OAuth2 against Instagram properly.

**Comment by aravindkk** [comment]
When I uncheck it, I get an error:
https://www.getpostman.com/oauth2/callback?code=aface491cb6c4e6b974eaaf0692f70db&state=1201349
By the way, can you tell me the working of 'request access token locally' option? What does it mean when we check it and when we uncheck it?

**Comment by aravindkk** [comment]
Also, aside from what I am doing hopefully wrong, isn't asking to save this whole html content as an access token something that is not intended?

**Comment by abhijitkane** [comment]
Yes, we're investigating why this might have happened.

The checkbox enables you to use OAuth2.0 providers that are not accessible over the internet - something served on localhost, for example.

Can you check your console for any errors when you see the HTML code where the token should be - http://blog.getpostman.com/index.php/2014/01/27/enabling-chrome-developer-tools-inside-postman/?

**Comment by aravindkk** [comment]
When that checkbox is checked, I see no error in the console. The html contents are displayed in the console, that's all. When the checkbox is unchecked, the window shows the error: "Could not initiate OAuth 2 flow. Check debug URL". There are 4 errors in the console when I tried a while back, but now it shows no errors, weird! Has anything changed in the last few minutes?
Edit: Tried again, got the following 4 errors in console, I don't think they are related to the issue:

Attaching the log...

XHR finished loading: POST "https://www.google-analytics.com/collect".
unload is not available in packaged apps.
jQuery loaded. $=function (a,b){return new m.fn.init(a,b)}, jQuery=function (a,b){return new m.fn.init(a,b)}
Backbone loaded. $=function (a,b){return new m.fn.init(a,b)}, jQuery=function (a,b){return new m.fn.init(a,b)}
jQueryNoConflict loaded. $=function (a,b){return new m.fn.init(a,b)}, jQuery=function (a,b){return new m.fn.init(a,b)}
Init loaded. $=function (a,b){return new m.fn.init(a,b)}, jQuery=function (a,b){return new m.fn.init(a,b)}
GET http://fhbjgbiflinjbdggehcddcbncdddomop/socket.io/1/?__sails_io_sdk_version…io_sdk_platform=browser&__sails_io_sdk_language=javascript&t=1439585947356 net::ERR_NAME_NOT_RESOLVED
GET http://fhbjgbiflinjbdggehcddcbncdddomop/socket.io/1/?__sails_io_sdk_version…io_sdk_platform=browser&__sails_io_sdk_language=javascript&t=1439585947450 net::ERR_NAME_NOT_RESOLVED
Loaded settings
Loaded theme
Open latest DB
Loaded Database
Initialized ThemeManager
beforeunload is not available in packaged apps.
Checking for update notifications...
Initialize interceptor
ThemeSettingsTab: Purchase is not available
Stored version: 3.0.7, currentVersion: 3.0.7
XHR finished loading: GET "http://www.getpostman.com/broadcasts".

**Comment by aravindkk** [comment]
Hi, any comments?

**Comment by abhijitkane** [comment]
We'll be pushing a new version with another OAuth2-related fix that some users had reported. The HTML showing up in place of the token is something we haven't seen before. What's the value of "scope" when you try OAuth2 with the Instagram API? Also, can you try using OAuth2 with other providers, like GitHub?

**Comment by abhijitkane** [comment]
@aravindkk Can you update to version 3.0.8 and see if you still face the bug?

**Comment by aravindkk** [comment]
Hi, my version is 3.0.9 now, still issue exists. Please let me know if this is a bug.
![issue-1](https://cloud.githubusercontent.com/assets/1815535/9466676/39f0b08a-4b54-11e5-9245-edb3c5bbfde1.png)
![issue-2](https://cloud.githubusercontent.com/assets/1815535/9466677/39f1009e-4b54-11e5-91db-c3a1d26c93bb.png)

**Comment by abhijitkane** [comment]
@aravindkk Are you still seeing this issue?
