### ISSUE TITLE
Do not require sign-in to Chrome to use

### ISSUE THREAD

**Issue by JamesDunne** [a85/POSTMan-Chrome-Extension#135]
There are precious few good REST client applications on the Chrome Store and this is one of them. Unfortunately, it requires sign-in to Chrome to use. If possible, please do not require this.

**Comment by victor** [comment]
It is now being required to sign-up with Postman before using it. Which is totally inappropriate as the tool will be most often used for work, while people are being requested personal data.

**Comment by sdnts** [comment]
@victor You don't need to have an account to use Postman. When you open the app for the first time, there's a link right below the sign up form that should allow you to start using the app without signing in :)
![screenshot 2017-04-11 15 46 13](https://cloud.githubusercontent.com/assets/7689783/24904488/2cd55f50-1ece-11e7-9ac4-ec3939389b37.png)

**Comment by vijaykumbhoje** [comment]
> Simple REST Client ( https://chrome.google.com/webstore/detail/simple-rest-client/fhjcajmcbmldlhcimfajhfbgofnpcjmb ) does not require sign-in to install. Perhaps there is something in your app's manifest that implicitly requires sign-in? I had assumed that your app uses the end-user's sign-in account details to store history and preferences.
> 
> Regardless, I have never bothered to sign out after signing in to Chrome and that wouldn't be a great workaround because in certain cases it would be inappropriate to sign in in the first place. I can test this on a spare box here. Give me a few minutes and I'll reply back.

The link seems broken
