### ISSUE TITLE
Feature Reqeust: Add method to create symlink / alais to an API definition inside another Collection

### ISSUE THREAD

**Issue by stevemcmillen** [a85/POSTMan-Chrome-Extension#1350]
With test runner, you are supposed to duplicate APIs in a collection in order to run automation against all items in that collection.  But this means you have to copy that API.  I'd much rather have a single copy of the API in one location and create an alias to that API in the test runner collections.

Also, We use POSTMan to publish APIs to the entire team.  We have hundreds of APIs now so as a convenience we create a single collection with the most commonly used APIs.  It would be nice if the "Common" Collection had symlinks to actual APIs instead of a copy of the APIs.

As it is today, when and API is in multiple locations, you have to maintain it everywhere.  But with the notion of an alias, you could avoid this problem.

Note: Changes to an API is most often in the Pre-Request or Post-Request (Tests) scripts.  But we also sometimes add attributes.

**Comment by a85** [comment]
We have finally figured out a better way to do this. Will announce the approach more on our blog soon!

**Comment by a85** [comment]
In an upcoming version, we will have the "replace" feature out soon that should make working with multiple requests of the same type super easy though.

**Comment by simonds** [comment]
Duplicate of #1535 ?
