### ISSUE TITLE
Feature Reqeust: Remember state of expand/collapse button on API Request Description

### ISSUE THREAD

**Issue by stevemcmillen** [a85/POSTMan-Chrome-Extension#1351]
Its nice to add API help on our APIs but this shows up expanded by default which can be really annoying / in the way if you add a lot of information added.

I'd like to suggest one of following changes:
- Remember expanded / collapsed status of the API Help (per user for shared collections )
- Or collapse by default but have a way to make it obvious there is some information there

**Comment by a85** [comment]
This should be fixed already.

**Comment by stevemcmillen** [comment]
Agreed. Working great.  Thanks!
