### ISSUE TITLE
Feature Reqeust: Copy native code in a single step

### ISSUE THREAD

**Issue by stevemcmillen** [a85/POSTMan-Chrome-Extension#1352]
I love the ability to copy the requests and response.  Its very useful when submitting bugs.

But I’d rather see a way to copy request code in 1 step.  Maybe instead of having dropdown in the popup dialog, put dropdown in main app window with a copy button next to it

If you do keep the dialog, then when you open the dialog, then put mouse focus in the text region so I can type Cmd-A and Cmd-C then Esc  (escape should close the dialog)

**Comment by a85** [comment]
This is available in 4.0+! :D

**Comment by stevemcmillen** [comment]
Thanks!  Its nice.    Better if I can dismiss the dialog with escape key :)

On Fri, Mar 18, 2016 at 7:04 AM, Abhinav Asthana notifications@github.com
wrote:

> This is available in 4.0+! :D
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/postmanlabs/postman-app-support/issues/1352#issuecomment-198374612

## 

-- Steve
