### ISSUE TITLE
Feature Reqeust: Standardize Esc / Enter keys for all dialogs

### ISSUE THREAD

**Issue by stevemcmillen** [a85/POSTMan-Chrome-Extension#1353]
Esc key should close all dialogs (w/o saving if applicable) / Enter to close with saving.  

Currently Esc works on some not all.  Does not work on following:
- Env variables quick popup you see when you click the “X” next to selected env in the main window
- The View source code popup

**Comment by a85** [comment]
@stevemcmillen What do you feel about the new shortcuts in 4.0+?

**Comment by stevemcmillen** [comment]
Esc and Cmd-Enter work in some dialogs but not in all cases.  Sometimes
they only work when you get into the dialog like the env dialog but not
once you've gone into one of the environments, and change and pressed
control-Enter.

I think its cleaner for users to use things like Cmd-E for environment
instead of sequence of keys (though I was fine with the sequence).  I often
had to explain to users a couple of times how to press one, let go and then
the other :).

The option for submitting an API of Cmd-Enter is interesting.  I liked just
pressing enter but I guess you had reasons and I can  get used to either.
I did not realized Cmd-Enter was needed at 1st but I have seen other tools
use this.

So in general:
 I like the implementation of Esc and cmd-Enter in dialogs but still a
little inconsistent/buggy
 Using Cmd+<letter> is a better idea for shortcuts in general
 Not so keen on cmd-Enter for submitting API but its ok (though I think
less users will figure it out)

thanks!

On Fri, Mar 18, 2016 at 11:45 AM, Abhinav Asthana notifications@github.com
wrote:

> @stevemcmillen https://github.com/stevemcmillen What do you feel about
> the new shortcuts in 4.0+?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/postmanlabs/postman-app-support/issues/1353#issuecomment-198491072

## 

-- Steve

**Comment by aditikul** [comment]
@stevemcmillen We've fixed most of the bugs around modal shortcuts I think. Will check again. Enter will work to send the request if you are in the URL field, but otherwise its Cmd+Enter if you are somewhere else in the UI where Enter may do something else.

**Comment by stevemcmillen** [comment]
Thanks.  Looks good to me.  Closing.
