### ISSUE TITLE
Inconsistent "Submit" button in Globals dialog reults in easily loosing changes

### ISSUE THREAD

**Issue by stevemcmillen** [a85/POSTMan-Chrome-Extension#1354]
The globals button has a "Back" button and if you don't press it and leave dialog by clicking "x", you loose your changes.  Dialog should have a "Submit" button like other dialogs do.  This inconsistency in the app is very confusing.

btw: These buttons should really be at the top or make the region for variables scrollable and ensure submit buttons always in view at bottom.  

Here is example of the "back" button:
![globalsdialog](https://cloud.githubusercontent.com/assets/2750330/9291580/813fd426-437e-11e5-8503-7970936dab84.png)

And here is example of too many items causing you to have to scroll down every time to see the back button:
![backbuttonhidden](https://cloud.githubusercontent.com/assets/2750330/9291589/e90aa9b4-437e-11e5-95bb-8492ec296a64.png)

**Comment by a85** [comment]
@stevemcmillen Sorry for the delay in replying to this issue. We are fixing this in an upcoming update.
