### ISSUE TITLE
Variable replacement has changed behavior breaking previous assumptions

### ISSUE THREAD

**Issue by stevemcmillen** [a85/POSTMan-Chrome-Extension#1355]
It used to be that a variable could be an empty string and it would be replaced with nothing.

For example, variable "env".  In most env's I set this as ".test" and replace with "myserver{{env}}.real.com"  But in PROD we don't have the Env portion so I would create the env variable and leave it empty.  This used to replace to "myserver.real.com"  (i.e. the empty string was inserted in its place).  Now I get "myservernull.real.com" (not desired).

As a solution I tried to not define the variable in that env but then the replacement does not occur and I ended up with "myserver{{env}}.real.com" after replacement (also not desired.

**Comment by eltone** [comment]
Not being able to specify an empty string for variables is a major weakness in the design. This is especially apparently when using environment specific urls or namespaces.

**Comment by eltone** [comment]
@stevemcmillen I was able to work around this issue by manually editing a postman dump to change the environment settings I wished to be empty to `""`.

**Comment by SamvelRaja** [comment]
<img width="808" alt="screen shot 2017-01-03 at 3 16 26 pm" src="https://cloud.githubusercontent.com/assets/5114052/21604167/a3ab6114-d1c7-11e6-9a03-2161018fa957.png">
@stevemcmillen @eltone  This has been fixed in the latest app. You can have an empty value for an environment. Kindly check the same.

**Comment by stevemcmillen** [comment]
Confirmed fixed
