### ISSUE TITLE
Were did Normal Authentication go (version 3) ?

### ISSUE THREAD

**Issue by SudoPlz** [a85/POSTMan-Chrome-Extension#1357]
I want to use a bearer token but on version 3 of postman there is no Normal authentication.
Why did you remove it?

Thank you.

**Comment by abhijitkane** [comment]
All the old auth helpers are still there. Go to the Authorization tab, and you should see a dropdown with 4 options.

**Comment by SudoPlz** [comment]
Sorry, that was my bad, I had seen those 4 tabs before. Its just that I didn't find a Normal Authentiation tab, but then again, theres the Headers button where I can specify anything I want.
I'm closing this issue immediately. 
Thanks..!
