### ISSUE TITLE
Request Duplication Not Saved Across Multiple Windows

### ISSUE THREAD

**Issue by wirsingj** [a85/POSTMan-Chrome-Extension#1358]
When I have two Postman windows open:
1) In window 1: Duplicate a request in Collection A- and drag to Collection B
2) In window 2:  Put duplicated request in proper order in Collection B, continue work.
3) Close windows.  
4) When postman is reopened,  the duplicated request is no longer in Collection B.

**Comment by abhijitkane** [comment]
Thanks for pointing this out - we'll fix this in the next release.

**Comment by wirsingj** [comment]
Great!  Thanks.

**Comment by abhijitkane** [comment]
@wirsingj Can you confirm if this works correctly in v3.0.9?

**Comment by wirsingj** [comment]
Looks like this is fixed now.   Thanks so much!
