### ISSUE TITLE
selecting hyperlinks in response body Automatically firing new GET request from selection

### ISSUE THREAD

**Issue by tenstriker** [a85/POSTMan-Chrome-Extension#1359]
This is annoying feature. It makes copying text from response body difficult. 
Please have hyperlink feature activated only when user press ctrl or some other key.

**Comment by a85** [comment]
@numaanashraf Can you look into this?

**Comment by abhijitkane** [comment]
@tenstriker Apologies for the delay on this. The latest app (v4.4.3) should let you select a link from the response without it opening in a new tab.
