### ISSUE TITLE
Postman doesn't show body of response if status code is 3**

### ISSUE THREAD

**Issue by efpies** [a85/POSTMan-Chrome-Extension#1361]
However, cURL and other utilities which can send requests do show.

![2015-08-19 19 37 30](https://cloud.githubusercontent.com/assets/1215572/9362576/ed2e766e-46a9-11e5-8df5-bc22f4c6230d.png)

As you see, Content-Length is greater than zero and response time is 200 ms, so this isn't a timeout issue. RFC allows us to send body inside 302 responses. Interceptor is enabled, following redirects is turned off.

**Comment by abhijitkane** [comment]
What's happening here is that the Interceptor is only able to listen for "redirect" events. The actual response body that's returned by the server as part of the 302 is never available to the Interceptor, or to Postman.

This feature was only added to make the user aware that a redirect was happening. Earlier, there would be no indication of this, and Postman would simply show the result of the final, non-redirected HTTP request.

**Comment by AnjolaA** [comment]
I am using postman and I need to get a response code from the 302 Location header. Does it mean this is impossible ?

**Comment by a85** [comment]
Switching to native apps might fix this. The chrome app platform is deprecated.
