### ISSUE TITLE
Add admin role to other users in team

### ISSUE THREAD

**Issue by andy-g** [a85/POSTMan-Chrome-Extension#1362]
Our team has been using the sync beta for a few months now, but it appears that there is no way for me to mark other users of our team as admins. Is this correct or am I missing a setting somewhere.

Thanks

**Comment by sobtiankit** [comment]
@andy-g We dont support multiple admins right now. However, it's on the roadmap and will be available in a month or so.

**Comment by TibGva** [comment]
Hi

I just started to use Postman beta as well, is this feature supported now or can we change the admin of the team ?

**Comment by abhijitkane** [comment]
@ThibautRuy You can change the admin. Send us an email at help@getpostman.com if you wish to transfer admin rights to another user in the team.

**Comment by jackie-ta-avalara** [comment]
We would also like to have multiple admins. This is especially important if team members leave.

**Comment by felipeplets** [comment]
+1 from our side, we need multiple admins feature

**Comment by a85** [comment]
Multi-admin support is available now in the Postman Cloud admin panel.
