### ISSUE TITLE
Dynamic request features

### ISSUE THREAD

**Issue by wirsingj** [a85/POSTMan-Chrome-Extension#1364]
Would it be possible to make requests more dynamic/programmatic?

The easier half of this feature would be to allow for code in the pre-request script to stop the sending of the related request.   For instance-  if I send a request and find that some shopping item has 0 for inventory in stock,  I want to choose to not send the next request which would add it to cart.

The more complicated half of this would be being able to programmatically create requests within a pre/post-request script...   Though this does break the overall model that Postman follows-   there have been many times I have wanted to be able to dynamically send a request(s) to gather data before deciding what values to put in variables.  For example:  Sending some dynamically/programmatically created requests to find out which ProductID I want to set in a variable (maybe by checking inventory counts returned on a few items) before continuing with the collection.

At least being able to cancel a request in the pre-request area based on a condition would be very helpful.      Sometimes I don't want to add an item to the cart if my URL variable is set to a certain location.   And allowing for programmatically generated requests could make the work in the collection more generalized and expandable.

Thanks,
Jeff

**Comment by a85** [comment]
@wirsingj This is coming soon. We are refactoring the app right now to enable this. You will have much more granular control of the order in which you would like to execute requests.

**Comment by abhijitkane** [comment]
@wirsing We have a basic flow control mechanism in the latest versions of Postman - http://blog.getpostman.com/2016/03/23/conditional-workflows-in-postman/

**Comment by wirsingj** [comment]
Thanks!  Very cool.
