### ISSUE TITLE
How to pass/fail test case with multiple steps(api calls)

### ISSUE THREAD

**Issue by mverma-va** [a85/POSTMan-Chrome-Extension#1365]
So we have stuck with this problem which might be a deciding factor for us to move to other tools like SoapUI or Jmeter.
Problem:
Testcase1: Delete a user
Steps:
a. Create a user (one api call, which may have few assertions)
b. Read the above created user (2nd api call, which again may have few assertions)
c. Delete the above created user(3rd api call, which will also have few assertions)
Now our testcase1 will pass when all these three steps pass and all assertions pass and fail if any of the steps/assertion fail.

So let us know what is the approach we should use to construct test case like this and how to make the test case pass/fail and export the result to a report(which we want to do)

**Comment by mverma-va** [comment]
It would be great if you guys let us know when we can expect this feature to be released?

**Comment by mverma-va** [comment]
Any update on this feature

**Comment by shamasis** [comment]
@a85 seems like this is exactly how collections work now. am i missing something?
