### ISSUE TITLE
Clicking on HATEOS links opens a new tab, but does not keep the request parameters

### ISSUE THREAD

**Issue by usubhash** [a85/POSTMan-Chrome-Extension#1367]
Hi,

This is a feature request.

Right now, clicking on a HATEOS link in the response opens a new tab which is good. More good is when the Request properties like header, body etc are also included. Otherwise, I have to copy the whole thing again which is a pain.

Thanks,
Subhash

**Comment by abhijitkane** [comment]
You can preserve the headers by enabling the 'Retain headers on clicking link' setting. Body etc. are not included as of now.
