### ISSUE TITLE
External JSON schema references aren't resolving

### ISSUE THREAD

**Issue by bandtank** [a85/POSTMan-Chrome-Extension#1368]
I'm trying to use the schema shown below:

![screen shot 2015-08-21 at 4 00 59 pm](https://cloud.githubusercontent.com/assets/1170415/9419964/d8d068b0-481d-11e5-8130-c39c9428ff15.png)

which is hosted on S3. I'm trying to reference it in a Postman test as follows:

`"creator": {
                 "$ref": "https://s3.amazonaws.com/ccb-json/model.json#/Models/Minimal_Person"
             },`

but it doesn't work. The reference never resolves and the test always passes. The output of `console.log(creator)` is as follows `Object {$ref: "https://s3.amazonaws.com/ccb-json/model.json#/Models/Minimal_Person"}`.

What am I doing wrong?

**Comment by abhijitkane** [comment]
Currently, the test script sandbox cannot reference any remote resources. You'll need to hard-code the schema in your test script.

**Comment by johnnavarra** [comment]
have you tried using the tiny validator api to pull in remote schemas?

**Comment by mcdan** [comment]
Not surprisinly trying to get tv4 to include the remote schema also fails, I tried in postman with a test like this:
```javascript
var schema = {
  "$schema":"http://json-schema.org/draft-04/schema#",
  "allOf":[
    {
      "$ref":"http://www.jsonschemavalidator.net/api/jsonschemastore/schema?schemaUrl=schema-draft-v4"
    }
  ]
}

var postman_valid = {
	"id" : "test"
};

var postman_invalid = {
	"id": false
};

tests["Valid Data1"] = tv4.validate(postman_valid, schema);
tests["Valid Data2"] = tv4.validate(postman_invalid, schema);

console.log("Validation failed: ", tv4.error);
```
The test result is worryingly a pass. So even though it couldn't really fetch the schema it passes the test.

Loading a remote schema or being able to set in the test in some way is really necessary. Reading up on how data variables work I don't think I could even back door this through there. 

If I want to ensure that my API conforms to the schema I've set out, I should really validate every response against the schema, which means hardcoding the schema in every single test. Which is a real pain.

**Comment by otoniel-isidoro** [comment]
+1

**Comment by lestevaos** [comment]
+1

Same situation here. I'm using the `Swashbuckle.AspNetCore` to generate the `swagger.json` schema in real time and I'm not able to use it.

Thinking about downloading it in a Jenkins pipeline and use the `swagger.json` file as data file to run the collection. Will I be able to use the data file content in the tests panel to `JSON.parse` it to a schema object?

**Comment by hiredgun** [comment]
+1

**Comment by bensullivan** [comment]
+1

**Comment by scholary-tim** [comment]
+1

**Comment by edsonmedina** [comment]
+1

**Comment by jvkaam** [comment]
+1

**Comment by lwohlhart** [comment]
+1

**Comment by ivaaaan** [comment]
+1. Doesn't work even if I have hardcoded schema: 

```
tv4.addSchema('ownerSchema', JSON.parse(pm.environment.get('ownerSchema')));
let cardSchema = JSON.parse(pm.environment.get('cardSchema'));
```

Card schema looks like:

```
{
        "required": ["id", "number",
                    "owner", "paySystem",
                    "balance", "currency",
                    "status", "expireAt"
        ],
        "properties": {
            "id": {
                "type": "string"
            },
            "owner": {
                "$ref": "ownerSchema"
            }
        }
    }
```

**Comment by jooleeanh** [comment]
Spent two hours figuring out why the schema validation tests were always positive even when putting bad schemas... Would it be possible to indicate this lack of feature in the documentation when talking about TinyValidator ?

Is this feature in the works ?

### Work-around

In the pre-request scripts, you can call the url and store the schema in a global or environment variable, to then use it in the test script.
Personally, I created a method (with a random GET url) that fetches all my schemas and stores them in global variables:
```javascript
function attributeSchemaToGlobalVariable(url) {
    var variable = url.replace("https://your-server.com/", "");
    console.log(url);
    console.log(variable);
    pm.sendRequest(url, function (err, res) {
    if (err) {
        console.log(err);
    } else {
        pm.globals.set(variable, res.json())
    }
});
}

attributeSchemaToGlobalVariable("https://your-server.com/jsonSchema/user/detail.json");
attributeSchemaToGlobalVariable("https://your-server.com/jsonSchema/user/basic.json");
attributeSchemaToGlobalVariable("https://your-server.com/jsonSchema/event/basic.json");
```
Which allows me to call the following variables in my test script:
```javascript
var schema = {
    "type": "object",
    "properties": {
        "user": {"$ref":"#/definitions/userDetail"},
        "event": {"$ref": "#/definitions/eventBasic"}
    },
    "definitions": {}
};

schema.definitions["userDetail"] = pm.globals.get("jsonSchema/user/detail.json");
schema.definitions["eventBasic"] = pm.globals.get("jsonSchema/event/basic.json");

pm.test('Schema is valid', function() {
  pm.expect(tv4.validate(JSON.parse(responseBody), schema)).to.be.true;
});
```

EDIT: Be careful when accessing global variables since you're working with a reference.  
For example, any modification to `schema.definitions["userDetail"]` such as:  
```js
schema.definitions["userDetail"]["required"] = ["firstName", "lastName"];
```  
will modify the original global variable, and may screw up your other tests using that same schema.   
I'd recommend the following:  
```js
schema.definitions["userDetail"] = JSON.parse(JSON.stringify(pm.globals.get("jsonSchema/user/detail.json")));
```

**Comment by a85** [comment]
It is possible to call for external URLs in pre-request scripts/test scripts now. We are also going to have first-class schema support for all formats in upcoming versions for Postman. Closing this for now.
