### ISSUE TITLE
How to extract cookie when there are two cookies with same name but different domain

### ISSUE THREAD

**Issue by mikefadhl** [a85/POSTMan-Chrome-Extension#1370]
Here is how I normally extract cookies in my tests section:

var myslCheck = postman.getResponseCookie("slCheck");
postman.setGlobalVariable("slCheck",myslCheck.value);

But what if I have two cookies with the same name but on different domains?  How to I extract the correct one?

Thanks

**Comment by abhijitkane** [comment]
Can you add `console.log(responseCookies);` to your test script and check if there's anything useful there? To view the console - http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/

**Comment by mikefadhl** [comment]
![screen shot 2015-08-25 at 8 04 36 am](https://cloud.githubusercontent.com/assets/10877094/9470294/279fc9b0-4b00-11e5-88bc-6c530ccbbd2a.png)

**Comment by abhijitkane** [comment]
We offer Lodash in the test sandbox. You can extract the cookies that have domain: .nike.com using https://lodash.com/docs#findWhere

**Comment by mikefadhl** [comment]
This worked:

var temp = _.result(_.findWhere(responseCookies, { 'name': 'slCheck', 'domain': 'ecn2-api.nike.com' }), 'value');
postman.setGlobalVariable("slCheck",temp);

Thanks
