### ISSUE TITLE
Postman sync duplicates saved responses

### ISSUE THREAD

**Issue by cameronoxley** [a85/POSTMan-Chrome-Extension#1372]
Sync is causing the "Saved Responses" to display duplicate information multiple times.

Deleting and "Re-syncing" does not resolve the issue.

![screen shot 2015-08-26 at 10 22 27 am](https://cloud.githubusercontent.com/assets/1674847/9488791/9415d8d2-4bdc-11e5-8738-35e7019c2917.png)

**Comment by abhijitkane** [comment]
Can you check the console (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/) for any errors? Your user account doesn't have duplicate responses - can you try signing out and signing in? This should remove the duplicate responses.

**Comment by cameronoxley** [comment]
I've signed in and out (removed local storage) and it seems to have resolved. There are a couple of errors in the console, but because I'm not sure they're related.
![screen shot 2015-08-26 at 1 37 41 pm](https://cloud.githubusercontent.com/assets/1674847/9492445/dd77ee46-4bf7-11e5-82f0-1a6a8c29d2e2.png)

**Comment by abhijitkane** [comment]
Nope, these are unrelated.

**Comment by cameronoxley** [comment]
Great! Guess its resolved then! Thanks.

**Comment by cameronoxley** [comment]
Seems like this issue is a recurring one.
Signing out and signing in does seem to resolve it for a while. Perhaps a bug in the sync?

![screen shot 2015-09-22 at 2 05 16 pm](https://cloud.githubusercontent.com/assets/1674847/10017947/dbb9516c-6132-11e5-93bb-05ea0732d3ba.png)
