### ISSUE TITLE
Multi Log in

### ISSUE THREAD

**Issue by RyanW89** [a85/POSTMan-Chrome-Extension#1373]
Hello,

Can you log in from more then one instance of postman? Im trying to log in to both the team and local versions but it keeps telling me my password is invalid.

Any thoughts?

Ryan

**Comment by abhijitkane** [comment]
Credentials can only be used either on the main app or on the team app (depends on how you created them). Can you try and reset your password through https://www.getpostman.com/forgot-password (for the main app) or https://beta.getpostman.com/forgot-password (for the team app)? 

If that doesn't help, you send the username you're trying to login with to help@getpostman.com.

**Comment by nhg2007** [comment]
Hello, 

I have just started using Postman. How could I write the simple script for login function?
Thank you!

Gam

**Comment by sdnts** [comment]
@nhg2007 If you are talking about logging in to your service, that'll depend on the API itself.
Docs for Postman can be found [here](https://www.getpostman.com/docs/)
