### ISSUE TITLE
Headers are not correct

### ISSUE THREAD

**Issue by optikalefx** [a85/POSTMan-Chrome-Extension#1375]
I use Postman all the time. I was debugging this one call and couldn't replicate it in my code. Even given your code suggestions in the app.

The problem was that you're not showing me all the headers you are actually sending. Using Charles Debug Proxy I'm able to see the real headers. I shouldn't have to use a debug proxy on a request tool.

Please provide the full list of headers when viewing a request. Things like user agent are super important.

**Comment by abhijitkane** [comment]
@optikalefx Postman is a Chrome app, and relies on Chrome's XHR object to make requests. Some headers are automatically added, and Postman cannot inspect them.

Without Charles, you can use Postman's DevTools window to inspect requests - http://blog.getpostman.com/2015/06/13/debugging-postman-requests/

**Comment by optikalefx** [comment]
That's great to know, and helps me not use Charles. For the end user, you're providing code on making the request, but then often those request do not work. If you know your app is a chrome app, you know which headers will be added, and therefore can include them when you let users know how the request was made.

As a way to accomplish this, on startup you could make a request to your own website, and record at that time the request headers. Then you could provide those to the user for subsequent requests.
