### ISSUE TITLE
Auth not being removed from headers when selecting No Auth from the box.

### ISSUE THREAD

**Issue by jdiazcano** [a85/POSTMan-Chrome-Extension#1376]
Authentication is not being removed from headers. I am using PostmanForMac and when selecting No Auth from the combo box.

That led to a password leak (it was basic auth) when synchronising it with the team.

Should be possible to give the option to sync the auth header or not depending on a configuration?

**Comment by abhijitkane** [comment]
We cannot offer the option of choosing what parts of a request need to be synced. The Headers tab shows `(1)` if there is one header in the request.

**Comment by jdiazcano** [comment]
And what about removing the Auth header when selecting No Auth from the box?

**Comment by abhijitkane** [comment]
That's problematic as well..the Auth header may be added manually, or through a pre-request script at runtime. We'll look into a way to tie the helpers and headers together better.

**Comment by SamvelRaja** [comment]
Tracking in #1376

**Comment by shamasis** [comment]
Requests should be made immutable and as such handle this scenario.
