### ISSUE TITLE
OpenID connect support for acr_values

### ISSUE THREAD

**Issue by devployment** [a85/POSTMan-Chrome-Extension#1377]
Are there any plans to support OpenID connect? 

Currently I have a quite specific implementation where I would need to pass `acr_values` to the identity provider. Looks like that this is not possible atm with postman.

See `acr_values` at http://openid.net/specs/openid-connect-core-1_0.html#rfc.section.3.1.2.1

**Comment by abhijitkane** [comment]
@devployment We plan to allow plugins for authentication helpers, but can't offer any ETA on this at the moment.

**Comment by devployment** [comment]
Ok. At least with the interceptor I can re-use an existing authentication as a workaround.

**Comment by balaji-rajan** [comment]
@vkaegis, i'm keen on this piece.. is this still in cart?

**Comment by G3Kappa** [comment]
oof, it's been 5 years already

**Comment by giovinazzo-kevin** [comment]
Er, any updates? Five years have passed already, and this is standard as far as the OpenID specification goes.

EDIT: For the time being, modifying the authorization URL by manually adding `?acr_values=<...>` is enough.

**Comment by giridharvc7** [comment]
You can now send `acr_values` as custom parameters in OAuth2, read more about how you can use it [here](https://blog.postman.com/custom-parameters-oauth-2-token-generation-postman/) and let us know what you think
