### ISSUE TITLE
FEATURE REQUEST:Command-W

### ISSUE THREAD

**Issue by Jaciones** [a85/POSTMan-Chrome-Extension#1378]
Command-W or Ctrl-W closes the current "TAB" not the entire window, like on "chrome" browser.

**Comment by abhijitkane** [comment]
@Jaciones this is currently a limitation of the Chrome platform. We're working on a native Mac app, where we'll be able to implement this.

**Comment by eapen** [comment]
Hangouts app has this behavior for the stand-alone app.

**Comment by a85** [comment]
We just launched the Mac app in beta that should solve all these issues. If you are on OS X, you can get it here: https://www.getpostman.com/apps
