### ISSUE TITLE
Team Sync Beta - Is there a way to recover shared collections/requests once deleted?

### ISSUE THREAD

**Issue by GarthVader** [a85/POSTMan-Chrome-Extension#1379]
In a team environment, we don't want to lose anything by accidental deletion, so is there a way to retrieve deleted collections and individual requests from the server?  If not, I would like to request such a feature, as it seems essential to avoiding catastrophes.

**Comment by abhijitkane** [comment]
We'll be offering versioning capabilities soon - this will include the ability to revert to old/deleted versions of data. We can't offer any ETA on this as of now.

**Comment by a85** [comment]
Yep. We finally have a trash can available through the web dashboard.
