### ISSUE TITLE
Ability to pluggin a pdf viewer for Content-type application/pdf

### ISSUE THREAD

**Issue by nelreina** [a85/POSTMan-Chrome-Extension#1380]
Instead of downloading this response / show the pdf in the response panel

**Comment by faniva** [comment]
Any updates on this?

**Comment by krishnakumar-tce** [comment]
any update on this? this would be very useful to view pdfs inline in response or in console

**Comment by QUDUSKUNLE** [comment]
Any update on this?

**Comment by krishnakumar-tce** [comment]
any update on this? would be awesome to preview pdf responses in postman just like png.

**Comment by Jorgehn1995** [comment]
any update on this in 2020

**Comment by aaronr93** [comment]
@Jorgehn1995 et. al.,
Looks like they closed the project under which this issue lives on 16 Dec 2019.

I created a new issue under an open project: #8040

**Comment by nelreina** [comment]
see comments of @aaronr93
