### ISSUE TITLE
Team Sync Beta - Is there a way to selectively assign read-only access to team members?

### ISSUE THREAD

**Issue by GarthVader** [a85/POSTMan-Chrome-Extension#1381]
For collections, we want to give full update access to developers, but give read-only access to non-developers.  Currently, I only see that shared permissions apply to all team members.  Is there a way to select individually which team members should have read-only access?  If not, I would like to request that option as a feature.

**Comment by abhijitkane** [comment]
This is on our to-do list. We'll be introducing user-level access control soon, but can't provide an ETA right now.

**Comment by a85** [comment]
Access control features are being tested out. Build going in production this week!

**Comment by bartdkmediahuis** [comment]
@a85 : Mind sharing a link to the documentation of this feature in this ticket ? Thanks !
