### ISSUE TITLE
Add or remove Header parameters in pre-request script

### ISSUE THREAD

**Issue by StevenWatremez** [a85/POSTMan-Chrome-Extension#1382]
this is possible to change or remove, with pre-request script, a header parameter ?

**Comment by abhijitkane** [comment]
You can modify the value of a header using environment variables. Use {{variableName}} as your header parameter, and use `postman.setGlobalVariable("variableName", "variableValue");` in your pre-request script.

**Comment by StevenWatremez** [comment]
Yes I know that but I want to change my header when I am in different environment. For example, put an authorization or remove it in header during my pre-request script.

**Comment by StevenWatremez** [comment]
I tried to set my authorization variable with empty string (like that "") but I have an HTTP header error. I just want to remove or add parameters in header during pre-request script.

**Comment by abhijitkane** [comment]
You can use variables in the header name too. {{headerKey}} = {{headerValue}}
Set headerKey to "Authorization" if you want to send it, and to some random header name if you don't.

**Comment by StevenWatremez** [comment]
Your example is about a complete header in variable ? if I have 6 parameters for my first header and 4 in my second header I can put complete header in variable ? and change variable in the header to change complete header ?

**Comment by abhijitkane** [comment]
One header has one key and one value. You'll need to use one variable for the key and one variable for the value.
I'm not sure what you mean by '6 parameters' for a header.

**Comment by StevenWatremez** [comment]
I am not one key and one value in my header. I send the Authorization value, the Content-Type ... etc 
![screen shot 2015-08-31 at 09 43 46](https://cloud.githubusercontent.com/assets/11426754/9574239/2b24a2c6-4fc5-11e5-8ce5-bd0d057a7024.png)
![screen shot 2015-08-31 at 09 44 13](https://cloud.githubusercontent.com/assets/11426754/9574240/2b508292-4fc5-11e5-91f8-4a2b8d02b6db.png)

**Comment by StevenWatremez** [comment]
And in different case, I need to change my header dynamically with pre-request script.

**Comment by abhijitkane** [comment]
Change the Authorization to {{Authorization}}

In your pre request script, use
postman.setGlobalVariable("Authorization", "Authorization"); (if you want to send this header)
or postman.setGlobalVariable("Authorization", "X-Temp-Authorization"); (if you do not want to send it)

To change the value of this header, use 
postman.setGlobalVariable("authorizationHeaderToken", "1234");

**Comment by StevenWatremez** [comment]
Thank you it works fine.

**Comment by placetobejohan** [comment]
You can now add and remove headers in the pre-request script as follows:

`
pm.request.headers.add({ key: "your-key", value: "your-value" });
pm.request.headers.clear("your-key");
`

**Comment by heyallan** [comment]
> You can now add and remove headers in the pre-request script as follows:
> pm.request.headers.clear("your-key");`

Where is `pm.request.headers.clear()` documented? @placetobejohan

**Comment by placetobejohan** [comment]
It seems like it isn't but if I am to trust my previous self it did work at the time.

The [docs](https://learning.postman.com/docs/writing-scripts/script-references/postman-sandbox-api-reference/#scripting-with-request-data) now instruct to use `pm.request.headers.remove()`.

**Comment by heyallan** [comment]
@placetobejohan Thank you ✌️
