### ISSUE TITLE
Environment Boolean Variables are Strings in Postman and Booleans in Newman

### ISSUE THREAD

**Issue by wirsingj** [a85/POSTMan-Chrome-Extension#1383]
When using environment variables, specifically booleans-  they are handled as Strings in Postman,  though when I run the collection/environment in Newman, they are handled as Booleans.

Either way would work well enough-  but they should definitely be consistently handled across Postman-Newman.   

For now I'll just make my if statements a bit more robust.

Thanks!
Jeff Wirsing

**Comment by abhijitkane** [comment]
Thanks for reporting this. We'll push a fix for this soon.

**Comment by wirsingj** [comment]
Awesome, thanks!

**Comment by wirsingj** [comment]
Any progress/update on this issue?  Thanks!

**Comment by abtiddle** [comment]
+1

**Comment by a85** [comment]
@shamasis @numaanashraf Solved in the Mac app with the new format?

**Comment by shamasis** [comment]
@a85 - it's a matter of behaviour change in runtime and it was done. Runtime currently does not purposely type cast in order to maintain compatibility with users who are actually depending on this behaviour reported as bug.

The new PM API should utilise type casting and address this issue.

**Comment by abhijitkane** [comment]
@abtiddle @wirsingj Can you confirm this fixed in the latest version of Postman and Newman?

**Comment by bquack** [comment]
+1 experiencing the same issue with Postman v5.2.0 and Newman v3.8.1

**Comment by BrianKilby** [comment]
+1 experiencing the same issue with Postman v5.2.0 and Newman v3.8.1

**Comment by bhartsfield** [comment]
+1 experiencing the same issue with Postman v5.2.0 and Newman v3.8.1

**Comment by neverfan** [comment]
WTF? 2 years?!!

**Comment by Bloodlog** [comment]
+1 Why?!

**Comment by vinterskogen** [comment]
Because, when you are making a typical POST request you are simulating a usual HTML-form submission. 

Check the "Content-Type" header of the POST request you are making - if it has value of "multipart/form-data" it is so. That means you have the same abilities, which a usual HTML-form has: (1) pass strings, (2) pass files.

On the other hand, sending an AJAX ("Content-Type": "application/json") allow you to pass boolenas, nulls, integers, etc.

**Comment by sdnts** [comment]
Guys, this issue will be solved with variable types. You can follow progress on that [here](https://github.com/postmanlabs/postman-app-support/issues/4173). Closing this for now :)
