### ISSUE TITLE
"Malformed JSON: Bad string" response with long JSON responses

### ISSUE THREAD

**Issue by ghost** [a85/POSTMan-Chrome-Extension#1384]
Our API can respond with long JSON responses (over 500 lines). If and only if the JSON response is over a certain limit, it will fail to show with a "Malformed JSON: Bad string" message.
We have tested the JSON response with jsonlint and PHP via Curl and Java are able to parse our JSON response with no issues.
Only POSTMAN and strangely enough, a Chrome Addon called REST Client, fail. The addon shows invalid characters from line 530 onwards (maybe you use the same library?)
The same data can also be returned paginated by our API, and when it does there are no issues with POSTMAN (provided any page response is under the 530 line limit) so we have ruled out any invalid characters in our data.
Please indicate how we can help you reproduce and fix this issue as we use POSTMAN extensively to test our API and it is driving us crazy.

**Comment by abhijitkane** [comment]
Is there a sample URL you have which works in cURL but not Postman?
We have had reports of Postman responding very slowly for large JSON responses, but not where Postman shows a "Malformed JSON" message.

**Comment by ghost** [comment]
GET with this link (non paginated) fails:

https://api.qounter.com/v1/qBusiness/?bId&uSessionId&dUpdate&tOrder=2&items&page

GET with these links (paginated) DO NOT fail, despite being the same returned data

https://api.qounter.com/v1/qBusiness/?bId&uSessionId&dUpdate&tOrder=2&items=5&page=1
https://api.qounter.com/v1/qBusiness/?bId&uSessionId&dUpdate&tOrder=2&items=5&page=2
https://api.qounter.com/v1/qBusiness/?bId&uSessionId&dUpdate&tOrder=2&items=5&page=3

Headers:

X_Service_Key: 3b91cab8-926f-49b6-ba01-postman
X_Auth_Token: 3b109323-71bb-4363-9113-a95f90258654

**Comment by abhijitkane** [comment]
Seems like an encoding issue. If you use the raw mode (instead of Pretty), you'll be able to see junk characters towards the end. Not sure why curl is able to show the response correctly.

Is there any custom encoding being set on the server side?

**Comment by ghost** [comment]
Thanks for your response. However, we have not set any custom encoding in the server, and the issue is present even with plain text.
Furthermore, if this were a encoding issue, the links that paginate the response would also fail.
But they don't.
With the paginted links, it is THE SAME data that is being returned, just paginated instead of in a single block.

**Comment by ghost** [comment]
Hello guys. Any update on this strange behaviour?

**Comment by abhijitkane** [comment]
Postman's requests are sent through Chrome. When I added all headers that Chrome adds automatically, I could get the junk response characters in curl as well:

```
curl -X GET -H "Accept:application/json" -H "Accept-Encoding:gzip, deflate, sdch" -H "Accept-Language:en-US,en;q=0.8" -H "Cache-Control:no-cache" -H "Connection:keep-alive" -H "DNT:1" -H "Host:api.qounter.com" -H "Postman-Token:97a1643b-5d11-bee1-a448-7b73aa9c18fe" -H "Pragma:no-cache" -H "User-Agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.157 Safari/537.36" -H "X-FirePHP-Version:0.0.6" -H "X_Auth_Token:3b109323-71bb-4363-9113-a95f90258654" -H "X_Service_Key:3b91cab8-926f-49b6-ba01-postman" 'https://api.qounter.com/v1/qBusiness/?bId&uSessionId&dUpdate&tOrder=2&items&page'
```

Adding an "Accept-Encoding: application/json" header resolves this issue. Note that you'll need to install and enable the Interceptor (https://chrome.google.com/webstore/detail/postman-interceptor/aicmkgpgakddgnaphhhpliifpcfhicfo?hl=en, enable using the satellite icon on the top-right of Postman) to include this header.

**Comment by ghost** [comment]
Thanks! Installed interceptor and modified header and it now works in Postman. If I indicate gzip in header it starts returning junk characters once again.
So the Postman issue for us is now closed, since we can just use this modified header in Postman for testing and PHP curl in production.
However, we're wondering what is wrong with our server though since for some reason, gzip compressed responses are including junk characters. I would appreciate any pointers to try to solve this issue for performance reasons.

**Comment by abhijitkane** [comment]
Whatever framework you're using on the server side might automatically be gzipping the responses over a certain length before sending them.

**Comment by jauharibill** [comment]
thanks for this explaination

**Comment by hariom282538** [comment]
This is not a postman problem at all. I got the same error and the reason for that was I was trying to produce @Produces("application/json") but I was actually returning a String. So, just check your code once, whether the method is returning json or not.
