### ISSUE TITLE
Url segments are not replaced with values when generating code snippets

### ISSUE THREAD

**Issue by ronaldsalas** [a85/POSTMan-Chrome-Extension#1385]
I have requests that use url segments, and I have values for them in the request. e.g. https://localhost/api/users/:id, and have id = 9999999 in the Params field. When I tried the Generate Code snippet feature, I see in cURL that :id has been replaced with 9999999 (which is good). But when I tried the other languages, e.g. Ruby, I see that it still used :id in the url ("https://localhost/api/users/:id") and didn't attempt to replace or use a variable for this and use the value I set in the request.

**Comment by abhijitkane** [comment]
Thanks for reporting this - we'll push a fix for this in the next release.

**Comment by abhijitkane** [comment]
@ronaldsalas Can you confirm this fixed in the latest version - 3.0.16?

**Comment by ronaldsalas** [comment]
@abhijitkane I see that it's fixed already in the latest version. thanks!!
