### ISSUE TITLE
Way to allow some validation in the request body in Pre-request script 

### ISSUE THREAD

**Issue by ronaldsalas** [a85/POSTMan-Chrome-Extension#1386]
I'm looking into sharing our Postman collection to other teams internally for them to try out our API and play around with. Since some of our POST requests have JSON payload, and in the off-chance that they didn't review our documentation, they could make some mistakes on the JSON payload. It would be nice if we can validate the request's body in the Pre-request script similar to the Tests section so that it can easily point out errors in the request to the user, even before attempting to send the request.

**Comment by abhijitkane** [comment]
In the pre-request script section, you have access to `request.data` - this holds the string entered in the request body.

You can validate this string as you like, and throw an error if it does not match a particular format. 

eg. if you're expecting JSON only,

```
try {
    JSON.parse(request.data);
}
catch(e) {
    throw {message: "The data was not in JSON format"};
}
```

Relevant docs - https://www.getpostman.com/docs/jetpacks_sandbox

**Comment by ronaldsalas** [comment]
Thanks @abhijitkane. I'll definitely try that.
