### ISSUE TITLE
history does not update when interceptor is enabled

### ISSUE THREAD

**Issue by cyrfer** [a85/POSTMan-Chrome-Extension#1387]
The blog post about using Interceptor shows a user browsing to google.com and Postman's history is updating.

I see no updates to Postman's history after enabling the Interceptor in Chrome.

I would like to set cookies in API requests from Postman, but I am unable to.

**Comment by abhijitkane** [comment]
You'll need to enable the Interceptor in Postman as well - use the satellite icon in the top-right.

To set cookies, you'll need to enable the Interceptor in Postman, and then set a "Cookie" header in your requests.

**Comment by cyrfer** [comment]
Thanks!
