### ISSUE TITLE
oAuth Credentials are not saved for each request

### ISSUE THREAD

**Issue by sineo** [a85/POSTMan-Chrome-Extension#1388]
Before oAuth credentials were save for each request, so you could easily switch between requests and test quickly. Since the latest update that feature has gone. Every time you switch between requests you have to re-enter the oauth credentials.

**Comment by abhijitkane** [comment]
You'll need to enable the 'Save helper data to request' option. If this is selected, oAuth credentials are saved with the request in the tab.
