### ISSUE TITLE
OAuth Access Token Blank

### ISSUE THREAD

**Issue by brodkin** [a85/POSTMan-Chrome-Extension#1389]
I've been debugging this issue on and off for a couple days and I'm still pulling my hair out...

I have a working OAuth 2 server though which other clients are able to successfully authenticate, but Postman can't seem to decode the JSON response correctly in spite of it all being there.

Here is the response when exchanging the code for an access token:
`{"access_token":"Pga6K1oYIMDTtUbV9BJUjWHe7U71IjfPaM7D6qR9","token_type":"Bearer","expires_in":3600}`

Here is what Postman returns:
![screencap](https://cloud.githubusercontent.com/assets/236564/9568799/0245d7a0-4f0a-11e5-95be-1bc4df9d93de.png)

Any thoughts?

**Comment by abhijitkane** [comment]
What version of Postman are you using? (wrench icon in the top-right > settings > about)

**Comment by brodkin** [comment]
Version 3.0.8 (packaged)
OS: mac
Architecture: x86-64
Native client architecture: x86-64

**Comment by abhijitkane** [comment]
Can you update to the latest version (3.0.11) and check? (chrome://extensions > Developer Mode > Update extensions now)

3.0.11 also has a 'request access token locally' feature which lets you use locally hosted / intranet OAuth2 providers.

**Comment by brodkin** [comment]
That totally fixed my problem. I didn't even think to try updating since Chrome usually does a pretty good job of that on its own. Thanks!

**Comment by wimphy** [comment]
I meet the same issue again with version 4.1.1, any idea?
4.1.1
OS X 15.4.0 / x64
