### ISSUE TITLE
Postman as a HTML5 App

### ISSUE THREAD

**Issue by maliayas** [a85/POSTMan-Chrome-Extension#139]
Thanks for your effort on this Chrome plugin.

As long as I see, this app doesn't work in other standards compliant browsers. There seems some chromium dependencies. Do you have a plan to make a fork of this work that will work on Firefox and others. So more developers can make use of it. Or does such a fork exist already?

**Comment by jbclements** [comment]
+1...

**Comment by a85** [comment]
Coming soon using Github's Electron framework. Email us at help@getpostman.com to get on the beta.

**Comment by omeid** [comment]
That still doesn't work with firefox. I use FF as my main browser and it would be not running another browser for Postman (whatever firing up Chrome or Electron).

**Comment by jamesgecko** [comment]
@omeid Chrome apps are deprecated, and Firefox will be moving to a Chrome-like plugin model by the end of the year. The Electron app is the only viable way forward, afaik.
