### ISSUE TITLE
Drag n Drop requests between collections

### ISSUE THREAD

**Issue by A570343** [a85/POSTMan-Chrome-Extension#1390]
I would like the ability to click on a Request in one collection then move or copy it into another collection. If the Request already exists in the target collection then you should prompt the user to overwrite the existing request.

**Comment by sGuid** [comment]
+1  - i would really like to move/copy requests between collections.
I see this is suppose to have been implemented in issue #212, but it doesn't work now.

**Comment by vkaegis** [comment]
Hey guys, looks like we missed closing this issue. This should be working in our native apps now. Feel free to open another issue if you have more feedback around this.

**Comment by turnspike** [comment]
Unless I'm missing something obvious, this is not working on Postman 6.7.4 and macOS 10.14.5. I'm trying to duplicate a request from [an example Okta collection](https://developer.okta.com/reference/postman_collections/) into my project collection. Dragging and dropping does nothing, the request's (⋯) hamburgler menu only shows "Open in New Tab", Edit -> Copy then selecting the request and Edit -> Pasting into the collection does nothing.

I'm trying to clone an API example from their collection into my project collection so I can edit it. I can't find an intuitive UX path to this goal.
