### ISSUE TITLE
Unable to drag n drop a parameter to the top

### ISSUE THREAD

**Issue by A570343** [a85/POSTMan-Chrome-Extension#1391]
I'm constructing a request and I've clicked on Params. I've entered 2 parameters and now I want to move the 2nd parameter to the top position. When I try to move that parameter,the top parameter doesn't switch places with the 2nd parameter.

**Comment by abhijitkane** [comment]
Thanks for reporting this. We'll be pushing a fix for this soon.

**Comment by A570343** [comment]
Glad to hear it. 

Where can I find the changelog for the Postman beta? Currently if I click on Changelog from within the app, it shows me changes to the non-beta application.

**Comment by abhijitkane** [comment]
We only maintain a changelog for the main application at https://getpostman.com/changelog.
The latest version of the beta app is at par with the latest version of the main application in terms of bug fixes.

**Comment by A570343** [comment]
Works some of the time.

> Sometimes when I drag n drop the 2nd param on the 1st, it may switch.
> Always when I drag n hold the 2nd param on the 1st, it will not switch. If I drag n hold on the 1st param then I can move it to the 2nd, 3rd, or 1st param and it will switch.

**Comment by abhijitkane** [comment]
@A570343 Are you still seeing this?

**Comment by A570343** [comment]
Nope, this feature is working for me in v4.1.3.
