### ISSUE TITLE
option to specify charset UTF-8 for Content-Type when using form-data

### ISSUE THREAD

**Issue by coryshrmn** [a85/POSTMan-Chrome-Extension#1392]
It would be nice to specify `charset`. However, users cannot change the `Content-Type` header, since it must include the generated form `boundary`.

For example

```
Content-Type = multipart/form-data; charset=UTF-8; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
```

Without this feature, we cannot POST UTF-8 text fields in a form.

**Comment by makkasi** [comment]
I have the same problem now. Specifying other headers doesn't help.

**Comment by fschwalm** [comment]
Duplicated https://github.com/postmanlabs/postman-app-support/issues/986

**Comment by codenirvana** [comment]
We've added support specifying custom `boundary` and  `charset` in the `Content-Type` header in the latest version of the Postman app (v7.6.0).

**Comment by kauanmocelin** [comment]
After create a custom "Content-Type" and check http request code: the charset=utf-8 is not being there.
Is this still working? Or I need to set "Content-Type" field by field?
Postman v10.19.2
![Selection_328](https://github.com/postmanlabs/postman-app-support/assets/3020794/5f910761-56ce-4d92-bcfe-63c4d0c828ea)
