### ISSUE TITLE
set big number to GlobalVariable is wrong

### ISSUE THREAD

**Issue by kingangelTOT** [a85/POSTMan-Chrome-Extension#1393]
response json {"id":12975268907193777}

var id = data["id"]
postman.setGlobalVariable("id", id);
result :
id=12975268907193776

what's wrong

**Comment by abhijitkane** [comment]
Where are you checking the id from?

Can you send a GET request to dump.getpostman.com/get?a=12975268907193777, with the following test script and check? To view the output in the console, check http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/

```
var data = JSON.parse(responseBody);
postman.setGlobalVariable("numTest", data.args.a);
console.log("Value saved: " + globals["numTest"]);
```

**Comment by kingangelTOT** [comment]
response:
{
  "msg": "post_test",
  "post_test_code": "aaasdfa123412343214",
  "ccc": {
    "abc": "aaaaaaa"
  },
  "array_data": [
    {
      "first": "first_data"
    },
    {
      "second": "second_data"
    }
  ],
  "id": 12975268907193777
}

my Tests script:
var data = JSON.parse(responseBody);
// 从data数据中取key为post_test_code的值,赋值给code
var code = data["post_test_code"]
// 设置全局变量,变量名称是post_test_code,值是code
postman.setGlobalVariable("post_test_code", code);

//同理多层的数据用[][]来获取
var abc = data["ccc"]["abc"]
postman.setGlobalVariable("post_test_abc", abc);

//获取数组中的数据,首先根据key为array_data获取数组,然后根据[0]索引获取第一个数据对象,再获取key为first的数据
var first_data = data["array_data"][0]["first"]

postman.setGlobalVariable("first_data", first_data);

var second_data = data["array_data"][1]["second"]

postman.setGlobalVariable("second_data", second_data);
var id = data["id"]
postman.setGlobalVariable("id", id);

result: 
post_test_code → aaasdfa123412343214
post_test_abc → aaaaaaa
first_data → first_data
second_data → second_data
id → 12975268907193776

**Comment by kingangelTOT** [comment]
when id = 12975268907193778  is right
when id = 12975268907193776 is right

when id = 12975268907193777 is wrong

**Comment by abhijitkane** [comment]
What version of Postman are you running? You can check by going to chrome://extensions/

**Comment by kingangelTOT** [comment]
version is 3.0.12.1

**Comment by abhijitkane** [comment]
I was able to reproduce this. This seems to be a JavaScript issue - 12975268907193777 is automatically converted to 12975268907193776 by JSON.parse(). ....77 is a valid number is JSON, but not in JavaScript. You'll need to modify the server behaviour to send the id as a string.

See "Integer range for Number" in https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number

**Comment by kingangelTOT** [comment]
var data = JSON.parse(responseBody);
var id = data["id"]
console.log("responseBody: " + responseBody);
console.log("data string: "+JSON.stringify(data))
console.log("id: " + data["id"]);
postman.setGlobalVariable("id", id);

result:
responseBody: {"msg":"post_test","post_test_code":"aaasdfa123412343214","ccc":{"abc":"aaaaaaa"},"array_data":[{"first":"first_data"},{"second":"second_data"}],"id":12975268907193777}
data string: {"msg":"post_test","post_test_code":"aaasdfa123412343214","ccc":{"abc":"aaaaaaa"},"array_data":[{"first":"first_data"},{"second":"second_data"}],"id":12975268907193776}

so: 
var data = JSON.parse(responseBody)  is wrong;

**Comment by abhijitkane** [comment]
Yes, this is a JS limitation.

If you go to Chrome's console and type `a= 12975268907193777`, Chrome will return 12975268907193776

**Comment by kingangelTOT** [comment]
thank you

**Comment by anyone-can-test** [comment]
I have the same problem.
So, If I have to use big integer beyond javascript, what should I do?

**Comment by anyone-can-test** [comment]
Can't save big integer as a environment variable, using postman.setEnvironmentVariable
