### ISSUE TITLE
Processing of the HTTP request resulted in an exception

### ISSUE THREAD

**Issue by wfswanepoel** [a85/POSTMan-Chrome-Extension#1394]
Hello,

I have been using postman for months now and I love it. It is awesome but after the new update release I have been getting the following error everytime when I do a PUT or POST request.

{
  "message": "Processing of the HTTP request resulted in an exception. Please see the HTTP response returned by the 'Response' property of this exception for details."
}

I have tested the same request via SWAGGER and Advanced REST Client and it is working with no issues.

**Comment by abhijitkane** [comment]
Can you look at the Network tab in Chrome's DevTools window - http://blog.getpostman.com/2015/06/13/debugging-postman-requests/ and check the exact request/response payload?

Is Postman sending something unexpected?

You can also send a POST request to http://dump.getpostman.com/post and check if the body data is being returned correctly.
