### ISSUE TITLE
URI field doesn't allow a parameter without a value

### ISSUE THREAD

**Issue by A570343** [a85/POSTMan-Chrome-Extension#1397]
We have an API that requires a parameter name but no value. In another Chrome REST called Extension Advanced Rest Client, I can enter: "AdSource=&param2=123" but in Postman, after entering the "=" after AdSource, it automatically removes the "=".

**Comment by a85** [comment]
@abhijitkane This should not happen at all.

**Comment by abhijitkane** [comment]
We removed this last September because a lot of users reported that servers didn't accept `a=&b=` as a valid query string, and only needed `a&b` if `a` and `b` were empty query parameters. Will add a setting for this.

**Comment by A570343** [comment]
Verified as fixed.
