### ISSUE TITLE
The sole tab does not have a close button

### ISSUE THREAD

**Issue by A570343** [a85/POSTMan-Chrome-Extension#1405]
This issue was previously fixed in 3.0.9 but in 3.0.12.1, it's an issue, see attachment.

![sole tab has no close button](https://cloud.githubusercontent.com/assets/13588309/9630408/ff552182-5147-11e5-98b1-d6be37cd11ce.PNG)

**Comment by abhijitkane** [comment]
A close button on the sole tab does not work the same as on other tabs. It's effectively a reset button. We're working on improving UI around tab management, but we're trying to keep meanings of icons consistent across the app.
