### ISSUE TITLE
Edit Collection/Folder/Request - Tab key isn't working

### ISSUE THREAD

**Issue by A570343** [a85/POSTMan-Chrome-Extension#1406]
In the Edit Collection, Folder, or Request popups:

> In the Name field, pressing Shift-Tab doesn't reposition the cursor to any UI elements.
> In the Description field, pressing the Tab key doesn't reposition the cursor, instead it inserts a Tab character.

When the Edit Request popup is displayed:

> In the Request Name field, pressing the Tab key doesn't reposition the cursor.

**Comment by a85** [comment]
This should be fixed in 4.0+
