### ISSUE TITLE
Builder re-layout

### ISSUE THREAD

**Issue by A570343** [a85/POSTMan-Chrome-Extension#1407]
I'd like to request that the UI elements on the Builder page be redesigned/arranged so that they take up less space. 

Suggestions:

> Reduce the size & spacing of the tabs: Authorization, Headers, Body, etc.
> Move the Auth dropdown to be on the same line as Authorization, Headers, Body, etc.

**Comment by a85** [comment]
Try the two-pane layout now in our native apps! :)
