### ISSUE TITLE
Newly saved request feedback

### ISSUE THREAD

**Issue by A570343** [a85/POSTMan-Chrome-Extension#1409]
> Whenever I save a request, the name of that request doesn't show on the Request's tab. If I click on another request then come back, then the name is displayed.
> 
> The name of the request I saved, without a description, is displayed twice. Once in the tab and again on a line above the URI. Personally I'd like to see the second name removed as it's redundant and takes up space.

![request name is displayed twice](https://cloud.githubusercontent.com/assets/13588309/9631180/40e6312c-514d-11e5-9846-e7e2ee87f2c0.PNG)

**Comment by abhijitkane** [comment]
I'm not able to reproduce the behaviour you described. I opened a new tab, entered a URL, and hit save. Entered the request name, and hit 'Add to collection'. The label on the tab changed to the new name. What version of the app are you on?

About the name being shown twice - we'll be fixing the UI around this soon.

**Comment by A570343** [comment]
I'm using 3.0.12.1

**Comment by abhijitkane** [comment]
Can you describe the exact flow that reproduces this problem?
If I open Postman, open a new tab, and save the request to a collection, the tab name changes without me having to switch tabs or requests.

**Comment by A570343** [comment]
I just tried several times and I'm unable to reproduce the issue. If I see it again I' let you know.
