### ISSUE TITLE
Update environment variables from GET/POST response

### ISSUE THREAD

**Issue by ajaydivakaran** [a85/POSTMan-Chrome-Extension#141]
As a user I should be able to update environment variables from a GET response.

e.g
I make an authentication call and receive back a token among other things in the response.
I should be able to update the environment variable (say with the same key) to the value present in the response.

This feature, would save the user from manually updating a number of variables from one request to be used in another request.

**Comment by nchaluse** [comment]
Hello, I don't know if I can request a feature here, I believe it would be nice to be able to edit a variable in the request url, request body or even in tests. To do that, a right click on the variable {{variableName}} could bring up a menu in which we could modify the variable value.
