### ISSUE TITLE
GUI slow to load with many environments

### ISSUE THREAD

**Issue by abeckerman** [a85/POSTMan-Chrome-Extension#1411]
I have over 50 environments that I use Postman with and each time I open the app, the GUI takes a very long time (more than 5 minutes) to be responsive. I'm happy to help provide any log/debug info to help troubleshoot and isolate the root cause of this performance issue, but it makes starting up quite painful when I need to do something quickly.

**Comment by rmabraham** [comment]
This happens to me even with few environments (10). 8 collections. Total amount of requests: 97. The same issue occurs with the runner as well.

**Comment by calebrepkes** [comment]
Happens to me too. Even when using canary. 
Versie 50.0.2641.0 canary
Version 3.2.15 (packaged)
OS: win
Architecture: x86-32
Native client architecture: x86-32

**Comment by andrefreitas** [comment]
Same issue here. I need to wait a couple of minutes to start using postman.

**Comment by a85** [comment]
We have pushed several performance improvements to the app. Is this still happening?

**Comment by abeckerman** [comment]
Yes, I've noticed the significant improvements in the latest version. Nice work! It's way better than waiting many minutes to get going, but after the first few seconds of responsiveness in the app, there's still a ~15s delay in usability before it frees up again.

See this video, which hopefully helps illustrate the experience: http://screencast.com/t/Q4EktLqBddiq

**Comment by mhosman** [comment]
Improvements are obvious but... the UI takes up to 20 seconds or more in a very powerful machine to get started (fastening seatbelts, etc......). This app must be faster.

**Comment by numaanashraf** [comment]
@mhosman We are actively looking into app's launch performance and have more improvements planned for this on our roadmap.

**Comment by prashantagarwal** [comment]
We have released a lot of performance improvements with Postman v6.1.0 which should fix this issue. Thanks.
