### ISSUE TITLE
Quitting the app should check for unsaved changes

### ISSUE THREAD

**Issue by A570343** [a85/POSTMan-Chrome-Extension#1412]
If I make a change to a request then quit the app, it closes without checking for any unsaved changes.

**Comment by mdaloia** [comment]
In Mac OS it's really odd that hitting Cmd+Q by mistake trying to use Cmd+W to close a tab and see Postman being closed without any warning.

As a user I expect that my information is not lost, and if I have temporal unsaved state be warned that I will lost it if I continue closing the app.

Google Chrome resolved this issue adding the setting "Warn Before Quitting" where you need to hold Cmd+Q to actually close it, but they don't have "state" to save.

**Comment by kunagpal** [comment]
Related to #810

**Comment by vegetableman** [comment]
@mdaloia @A570343 The latest update handles the issue you mentioned, by saving the state of the tabs before quitting. Feel free to reopen this issue, if it does not solve your use-case ^_^.
