### ISSUE TITLE
Postman Stopped Working

### ISSUE THREAD

**Issue by eventhough** [a85/POSTMan-Chrome-Extension#1414]
This is going to sound really strange, but for some reason my Postman client just stopped working today. When I click "Send" it just shows "Loading..." and then nothing. It's like it just hangs there. No response.

**Postman version:**

Version 3.0.12 (packaged)
OS: mac
Architecture: x86-64
Native client architecture: x86-64

**Chrome version:** Version 45.0.2454.85 (64-bit)

To make sure it wasn't my own project I tried the [RESTClient](https://addons.mozilla.org/en-Us/firefox/addon/restclient/) add-on in Firefox and it works fine. I've also used curl in my terminal and that works fine as well.

I looked at the dev console for Postman and it shows nothing. The network tab in the dev console registers nothing - no request. Here is the console when Postman loads: https://www.dropbox.com/s/8p3pubfqwhgdk96/Screenshot%202015-09-02%2022.37.39.png?dl=0

Another thing, I tried out a competing client called [Advanced Rest Client](https://chrome.google.com/webstore/detail/advanced-rest-client/hgmloofddffdnphfgcellkdfbfbjeloo?hl=en-US) on Chrome and it's **also not working**! In the console for Advanced Rest Client I am getting these errors:

```
GET http://locahost:3000/devices net::ERR_NAME_NOT_RESOLVED
(-:-) 2015-09-02 22:27:10,094 [ERROR] XMLHttpRequest2 callback::onError
Class$S21: Unknown error
```

Of course I prefer Postman. :smile: 

Things I've tried to no avail:
1. Clear all browsing data (cookies, cache, everything)
2. Reset flags (chrome://flags)

Here's the kicker, I installed an old staging version of Postman from this link: https://t.co/zMJhpdYy6f

And it works! The old version is working fine!

**Old Postman version:**

Version 3.0.10 (packaged)
OS: mac
Architecture: x86-64
Native client architecture: x86-64

Any idea what is going on?

**Comment by abhijitkane** [comment]
The `net::ERR_NAME_NOT_RESOLVED` could indicate an issue with your hosts file. Are you able to make GET requests to other domains (google etc) from Postman?

**Comment by eventhough** [comment]
I just tried this resource: [http://jsonplaceholder.typicode.com/posts](http://jsonplaceholder.typicode.com/posts) and it failed in 3.0.12 but it succeeded in the older version: 3.0.10.

I don't think it's an issue with my hosts file because I have not ever edited it:

```
##
# Host Database
#
# localhost is used to configure the loopback interface
# when the system is booting.  Do not change this entry.
##
127.0.0.1       localhost
255.255.255.255 broadcasthost
::1             localhost
```

**Comment by abhijitkane** [comment]
Can you install the Chrome Canary build and install Postman there?
The Canary build can run alongside your existing Chrome installation.

**Comment by eventhough** [comment]
3.0.12 Works in Canary. **Version 47.0.2500.0 canary (64-bit)**

**Comment by eventhough** [comment]
I switched to a different Chrome user, installed Postman, and it works. I think my Postman must have gotten into some weird state. I just uninstalled and reinstalled Postman on the defective Chrome account and it seems to be working now. I logged in and synced everything back - looks like we are good to go.

Sorry about this...I'm not sure what happened.

**Comment by abhijitkane** [comment]
Cool...let us know if you face any other issues using Postman.
