### ISSUE TITLE
setEnvironmentVariable works, but referencing fails if var is disabled

### ISSUE THREAD

**Issue by id0Sch** [a85/POSTMan-Chrome-Extension#1416]
Hi,
I tried assigning an env. variable during the pre-request script without success.
my url is : http://{{host}}/feed/var?tk={{tk}}
and I tried setting the var that way, but it is not sent in the request.

``` javascript

postman.setEnvironmentVariable("tk", "foo");
```

am I doing anything wrong?
Thanks!

**Comment by abhijitkane** [comment]
Do you have an environment selected in the environment selector (top-right corner)?
If not, you can use `setGlobalVariable` instead of `setEnvironmentVariable`.

**Comment by id0Sch** [comment]
yes, i do have an environment selected

**Comment by abhijitkane** [comment]
1. Is it working when you use `setGlobalVariable`?
2. After you send the request, do you see "tk -> foo" when you click on the "x" button next to the environment name?
3. Can you follow the steps at http://blog.getpostman.com/2015/06/13/debugging-postman-requests/ and check the Network tab to see exactly what Postman is sending?

**Comment by id0Sch** [comment]
1. does indeed work
2. nope (but does work for step 1)
3. my env. var is not there.

btw -> if I set an environemntVariable for one request, what is the proper way to clean it up? adding a removeVariable to the tests?

**Comment by abhijitkane** [comment]
There's no removeVariable function - you'll have to delete it by going to the environments modal.

Can you try creating a different environment and try using that? We haven't had this issue reported before. 

You can also check the error log in the DevTools window for any errors when you send the request.

**Comment by id0Sch** [comment]
okay, I figured it out.
in my env i had tk as disabled, when I created a new env it worked.
is this a proper behaviour?

**Comment by abhijitkane** [comment]
Yes, when you set an environment variable through the script, it sets it regardless of it being enabled/disabled. However, referencing a variable using {{..}} requires the variable be enabled.
