### ISSUE TITLE
First parameter shows in parameter list but not in URI

### ISSUE THREAD

**Issue by A570343** [a85/POSTMan-Chrome-Extension#1418]
I've randomly seen this situation before but I'm not sure how to reproduce it. As you can see from the attachment, the parameter list has two parameters but the first one isn't shown in the URI. I know how to fix it but I'd like to have a fix to prevent this in the first place.

![first parameter isn not shown in uri](https://cloud.githubusercontent.com/assets/13588309/9658239/fbeaceec-5215-11e5-8fb1-f54b7668273f.PNG)

**Comment by abhijitkane** [comment]
The first parameter is likely a path variable. If your URL is of the form `http://website.com/:name`, you can add a path variable (name = Hello), and the URL will be treated as `http://website.com/hello`

When you open a new tab and click on `Params`, the first row in the key-value editor is for path variables.

**Comment by A570343** [comment]
Then something is wrong because when I start to add parameters, it's always to the first parameter and I've never had any issues. A subset of my other requests all have parameters in the first spot and I can manipulate them just fine. I created a new tab and when I click on the Params button, it shows only the URL Parameter Key field.

![url parameter key](https://cloud.githubusercontent.com/assets/13588309/9659480/c87f1212-521e-11e5-9b7a-be299a44a318.PNG)

**Comment by abhijitkane** [comment]
@A570343 Are you still seeing this? If so, can you send a screenshot of this happening in the latest  version of Postman too?
