### ISSUE TITLE
Multiple Select/Share of Collections

### ISSUE THREAD

**Issue by jrichard0725** [a85/POSTMan-Chrome-Extension#1419]
First off - love love love love Postman. It makes our lives so much easier when developing our API.
Thank you so much for building this out.

When I first joined team sync I had several collections I wanted to share with the team.
I couldn't find a way to bulk share collections.
Then after getting the team up and running, I wanted to change the collections from read-only (so they could modify them) and again had to go one by one.

It would be nice if I could select multiple collections, then choose share for all of them at once. Also to be able to toggle the read only for all collections at once.

Thanks.

**Comment by abhijitkane** [comment]
Thanks for your support. We're working on a number of improvements around the team-sharing flow, including user-level access control. Bulk actions on collections is on our to-do list, but I can't offer an ETA at the moment.

**Comment by a85** [comment]
You can now do this using Workspaces: https://www.getpostman.com/docs/postman/workspaces/intro_to_workspaces
