### ISSUE TITLE
URI works in the Advanced Rest Client Chrome extension but not in Postman

### ISSUE THREAD

**Issue by A570343** [a85/POSTMan-Chrome-Extension#1421]
I've included the URI and attached two screenshots that show the URI working in Advanced Rest Client but failing in Postman. Any ideas?

URI used in Postman:
http://veritude.sb.erecruit.com/RestServices/Candidate/Do/Create?CreatedByID=4b5d8fdc-4ae6-404e-92f6-a09766abbf95&EntityID=00000000-0000-0000-0000-000000000E01&FolderGroupID=188&FirstName=Mickey&LastName=Mouse&Email=Mickey.Mouse@unknown.com&AdSource=133&OwnerID=60572f71-ac85-490a-bdc4-8efa7594a801

![create mickey mouse in adv rest client](https://cloud.githubusercontent.com/assets/13588309/9684781/e55bf638-52e7-11e5-9c40-a20fe4c0f798.PNG)

![create mickey mouse in postman](https://cloud.githubusercontent.com/assets/13588309/9684783/eb4049fa-52e7-11e5-9353-b0b46d956bc5.PNG)

**Comment by abhijitkane** [comment]
@A570343 
In Advanced REST Client, you seem to be including the data in the body of the request of the URL. In Postman, they're being added to the URL.

Switch to the "Body" tab next to the Headers tab, select form-url-encoded, and paste the string that's in the 'Payload' field in Advanced REST Client.

**Comment by A570343** [comment]
I tried your suggestion but if I did it right, its still not working.

![failre](https://cloud.githubusercontent.com/assets/13588309/9685763/4bd39c30-52ee-11e5-8be4-d340a6b5c5ce.PNG)

**Comment by abhijitkane** [comment]
Can you follow the steps at http://blog.getpostman.com/2015/06/13/debugging-postman-requests/, and check the network tab for Postman and Advanced Rest Client for the difference between the two request payloads?
You might need to choose raw instead of form-url-encoded, and enter the same string as you did in the first screenshot.
