### ISSUE TITLE
Collections - Endpoints - Description Markdown does not support HTML

### ISSUE THREAD

**Issue by Andrewpk** [a85/POSTMan-Chrome-Extension#1422]
According to the markdown guidelines, html should be allowed in markdown. This is not the case in postman's API "description" field when adding an api to a collection.

Just wanted to let you know since migrating to the new version of postman (a lot of people on a project I was working on used postman v1 - all our APIs were setup as collections, etc., and now the descriptions read as HTML since I've had to upgrade. It looks like the old postman extension is no longer available?).

**Comment by abhijitkane** [comment]
@Andrewpk This has been fixed in v3.2.8 of Postman. Sorry for the delay on this.
