### ISSUE TITLE
Bulk Edit issue

### ISSUE THREAD

**Issue by A570343** [a85/POSTMan-Chrome-Extension#1423]
I had a request with one parameter. I did a Bulk Edit which included several parameters, including the one parameter which already existed. 

> When I tried to move the existing parameter over any of the parameters added via the Bulk Edit, I couldn't.
> 
> None of the Bulk Edit parameters can be moved or deleted.
> 
> When I created a new tab, it automatically inserted the Bulk Edit parameters. 

![existing parameter with move and delete icons](https://cloud.githubusercontent.com/assets/13588309/9685528/f695fe76-52ec-11e5-8ce8-f04bc7fe2bf0.PNG)

![bulk edit without move or delete icons](https://cloud.githubusercontent.com/assets/13588309/9685531/f9b23a02-52ec-11e5-9315-e5b730347ae6.PNG)

**Comment by a85** [comment]
This should be fixed in 4.0+
