### ISSUE TITLE
The new POTSMAN 3.0 does not have the cookies behavior as the old Postman - REST Client 

### ISSUE THREAD

**Issue by ihipop** [a85/POSTMan-Chrome-Extension#1427]
The old `Postman - REST Client` (https://chrome.google.com/webstore/detail/postman-rest-client/fdmmgilgnpjigdojojpjoooidkmcomcm?utm_source=chrome-app-launcher-info-dialog) has a cookies behavior that cookies will auto sync with the browser.
For example, if a API is in a admin dashboard that requires login,I can open a browser tab to login that admin page,then when I back to the `Postman - REST Client`,it is already logged in,I can test the API without to build the cookies in the request header manually,which is very convenience.
Will this feature come back again?

**Comment by czardoz** [comment]
@ihipop Postman 3.0 is a packaged chrome app, which means it does not have access to the browser's cookies. 

You'll have to use the [Postman Interceptor](https://www.getpostman.com/docs/capture) chrome extension. You can also refer to these blog posts which show how to install and use the interceptor:
- http://blog.getpostman.com/2014/02/11/postman-v0-9-6-access-cookies-and-restricted-headers-plus-better-testing/
- http://blog.getpostman.com/2014/11/28/using-the-interceptor-to-read-and-write-cookies/

**Comment by ihipop** [comment]
I seee...
