### ISSUE TITLE
Expect header omitted from request

### ISSUE THREAD

**Issue by vicmosin** [a85/POSTMan-Chrome-Extension#1428]
It seems that somehow Postman ignores the `Expect:100-continue` header in the requests. Tried different server implementations - header is missing. Once I use `cUrl` (generated by Postman btw) - works fine.

**Comment by abhijitkane** [comment]
You need to use the Interceptor to send the "Expect" header. If you begin typing "Expe.." in the header key field, you should see it show up in the "Restricted headers" section.

http://blog.getpostman.com/2014/11/28/using-the-interceptor-to-read-and-write-cookies/

![screen shot 2015-09-07 at 12 59 24](https://cloud.githubusercontent.com/assets/681190/9711319/4db976f4-5560-11e5-95f6-b03415096d38.png)

**Comment by vicmosin** [comment]
Sorry, didn't see that. Closed.
