### ISSUE TITLE
Option to globally search and replace text within Requests

### ISSUE THREAD

**Issue by A570343** [a85/POSTMan-Chrome-Extension#1429]
I have 20+ Requests (all within a Collection) that use an old value which I now must go through manually to find and change. It would be very helpful to have a option to search and replace specific text. I feel this should work for request that have and have not been saved. The search/Replace functionality should display the name of the Request if it's been saved along with the name of the Collection & Folder.

**Comment by cchen408** [comment]
+1

**Comment by bquack** [comment]
+1
It would be very useful to have Find and Replace across an entire collection.

**Comment by bhartsfield** [comment]
+1

**Comment by msilkroad** [comment]
+1

**Comment by knowroozi** [comment]
+1

**Comment by berpel** [comment]
+1

**Comment by jbr3wster** [comment]
+1

**Comment by bytebodger** [comment]
+1

**Comment by swheeler1974** [comment]
+1

**Comment by yael-lorenzo** [comment]
+1

**Comment by OBonio** [comment]
+1

**Comment by ghost** [comment]
+1

**Comment by CoolVoltage** [comment]
+1

**Comment by alfanse** [comment]
+1, please.

**Comment by bhawna2109** [comment]
Hi everyone, we are working on this currently. There is no ETA on this yet, but will update this thread once we have a build ready. Meanwhile, feel free to share your suggestions - your input can help shape this feature :)

**Comment by dehypnosis** [comment]
++++++1

**Comment by yishayn** [comment]
+1

**Comment by yishaycompit** [comment]
+1

**Comment by anna-seredinskaya** [comment]
+1

**Comment by agatheblues** [comment]
+1

**Comment by AbdelrahmanHafez** [comment]
Any updates on this?

**Comment by DollarAkshay** [comment]
+1

**Comment by shrikanth2002** [comment]
This will be a more useful feature to replace the URL's..., 
Looking for the update.. Any info?

**Comment by tomershay** [comment]
+1

**Comment by Ivanello** [comment]
+1

**Comment by sixeyes** [comment]
+1
Disappointed this is taking sooo long.

**Comment by blikblum** [comment]
I created a tool to replace part of the path and the host. See at https://codepen.io/blikblum/pen/WywrGy?editors=1010

It's possible to adapt to different needs. (JS knowledge required)

**Comment by prashantagarwal** [comment]
Hey guys, we are actively working on a feature that will enable you to do bulk replace operations, similar to what editors have as Find & Replace. **Find** feature is already present in Postman and very soon you can perform replace on those found results.

We will be putting this out on our Canary version of the app this week. I will keep you updated about its release.

**Comment by prashantagarwal** [comment]
Hey Everyone we have released this feature on our Canary apps. We would love to have your feedback on this. You can download Canary apps from https://www.getpostman.com/canary
<img width="1199" alt="screen shot 2018-06-06 at 10 45 54 pm" src="https://user-images.githubusercontent.com/3762808/41054279-8f33214c-69db-11e8-98a3-5b5f8bac8cf1.png">

**Comment by skaboy71** [comment]
Just used this.... LOVE !!   ^v^  (ړײ)

**Comment by vkaegis** [comment]
@skaboy71 Awesome. We'll be working on iterating and improving on this feature in the coming versions. Let us know if you have any feedback.

**Comment by pgrandje** [comment]
Where is this feature?  I downloaded Canary, but cannot see how to open Search and Replace.  Am I missing something obvious or is it hidden somewhere?

**Comment by prashantagarwal** [comment]
@pgrandje  click on magnify glass at bottom left in the status bar

**Comment by pgrandje** [comment]
Ahh, there it is!  Thank-you.  I'll try this feature in the next couple of
days.  Thanks for the prompt reply.

**Comment by jamalwalsh** [comment]
Trying this out right now!!! Absolutely belting feature...

**Comment by litzk** [comment]
I can't seem to find the way to replace with regex syntax (groups, white-space manipulation).

Is that feature implemented yet?

**Comment by a85** [comment]
Folks, we found some issues in the previous implementation so this had to be taken out of the production builds. Good news is that this is finally done and coming out in 6.5. Releasing over the next 2 weeks!

**Comment by a85** [comment]
This feature is in production now and rolling out to all users!
