### ISSUE TITLE
Unable to edit a parameter

### ISSUE THREAD

**Issue by A570343** [a85/POSTMan-Chrome-Extension#1430]
I have a working Request (Tab 1) that I made a duplicate of. I opened the duplicate request in a new tab (Tab 2) . I clicked on the Authorization tab and entered the first parameter then I switched back to the first tab (Tab 1). When I clicked on Tab 2, the first parameter field wasn't editable, it showed a circle with a diagonal line through it (I can't capture the circle but you can see that the first line is grayed out).

![first param field uneditable](https://cloud.githubusercontent.com/assets/13588309/9736595/25072afc-5610-11e5-9a68-638b7058b0ba.PNG)

**Comment by abhijitkane** [comment]
This is not a URL parameter (?key=value), but a path variable (erecruit.com/:key/Candidate..). We hope to fix this soon - but it shouldn't affect usage.

**Comment by jcollum** [comment]
+1 happening to me too; the URL path variable editor is disappearing from time to time. That part of the UI really should be split into URL path variables (before the ?) and URL parameters (after the ?). As it is the UI is confusing.

**Comment by a85** [comment]
We have moved to a React based UI layer. This issue should not be happening now.
