### ISSUE TITLE
Request: Ctrl-tab to switch between open tabs

### ISSUE THREAD

**Issue by tsoernes** [a85/POSTMan-Chrome-Extension#1432]

**Comment by abhijitkane** [comment]
@tsoernes In the latest version, you should be able to use Ctrl/Cmd+Shift+{ or [ or ] or } to shift between tabs.

**Comment by a85** [comment]
We have a Mac app out now people that solves these issues once and for all. Get it here: https://www.getpostman.com/apps

**Comment by Mouradif** [comment]
> @tsoernes In the latest version, you should be able to use Ctrl/Cmd+Shift+{ or [ or ] or } to shift between tabs.

o_O Why not Ctrl+Tab like litterally every other app ?
