### ISSUE TITLE
Inconsistent Environment Boolean Behavior 

### ISSUE THREAD

**Issue by wirsingj** [a85/POSTMan-Chrome-Extension#1433]
Related to: https://github.com/postmanlabs/postman-app-support/issues/1383

In a pre-request script I assign an environment variable a boolean value:
postman.setEnvironmentVariable("isProductionURL", true);

Then, in the pre-request script I check the type:

//Returns-  true,  boolean
console.log("PRE-TEST: "+ environment.isProductionURL + typeof environment.isProductionURL)

In the post-request script the same line returns string for type:
//Return-   true, string
console.log("POST-TEST: "+ environment.isProductionURL + typeof environment.isProductionURL)

The value of isProductionURL should always be a Boolean-  no matter if its referenced in the same script as its declaration, and if its being used in Postman, or Newman.

Thanks!

**Comment by abtiddle** [comment]
+1

**Comment by abhijitkane** [comment]
@wirsingj @abtiddle Support for typed variables is coming soon.

**Comment by drpoggi** [comment]
@abhijitkane Any update on this?

**Comment by prashantagarwal** [comment]
@wirsingj @drpoggi @abtiddle We now support this using new pm api to set environment variables.
https://www.getpostman.com/docs/postman/scripts/postman_sandbox_api_reference
