### ISSUE TITLE
Starting Postman always opens a request

### ISSUE THREAD

**Issue by A570343** [a85/POSTMan-Chrome-Extension#1436]
I have a collection with many folder and requests. I can be working on a request, close Postman and when I restart it, it will always show the URL for a specific request, one that I haven't opened previously.

![starting postman](https://cloud.githubusercontent.com/assets/13588309/9876307/18b8aac8-5b83-11e5-9dac-4663540d0b17.PNG)

**Comment by a85** [comment]
This should be fixed in 4.0+
