### ISSUE TITLE
How to execute the same test case, for x variables

### ISSUE THREAD

**Issue by xlash** [a85/POSTMan-Chrome-Extension#1437]
Hi,

I'd like to be able to do combination testing, to change one parameter, but run the same test x times.

For example, to test invalid characters in a request, I have to perform a test for " ±@£¢¤¬¦²¦²³³¼½¾][}{~~{}´­¯".

Is there any way to tell postman to rerun the same test after tests validation completes? I don't mind about a hack method more than an official release.

Thanks

**Comment by xlash** [comment]
I've been able to run multiple time the same test, by changing the 

requester.js::Request.onSend() to do it multiple time, depending on a environment variable being set in my request. The hack is not working correctly, it seems my environment variable are not being saved correctly. 

I also do not think this method will work for Jetpack Runner capabilities.

**Comment by a85** [comment]
@xlash You should be able to use the Collection Runner with multiple iterations taking in values from a CSV/JSON file. http://blog.getpostman.com/2014/10/28/using-csv-and-json-files-in-the-postman-collection-runner/

**Comment by xlash** [comment]
Hi a85,  this doesn't work, because I have a collection of over 300 tests cases, and they will vary on different attributes, and most of them I need to generate dynamically. And I do not want to run all TC against the same iterations. They will be independent.

For example, 1 TC might vary by adding numbers, another one, by varying length, etc. But these 2 tests cases might be run against different object types. And I do not want to run multiple runner, I'm lazy.

**Comment by xlash** [comment]
Ok, final update, I did move this to js/test_runner.js in Request::finishRequestRun(), just before launching another test case. I'm duplicating my current tests cases, and it's subsequences, as many times as needed. Then, in the test case itself, I adjust the data.

The hack is working good for now. With a single line, I can trigger 50 tests variations : 

PreRequestScript :
MY_FRAMEWORK.repeatTC([array_of_data_for each_tests_repetitions]);

**Comment by prabhukirannarava** [comment]
Hi xlash,
I am also having similar requirement to run multiple tests at once.
Can you please share me sample collection ?

hack that you are referring ..is it a framework ?

**Comment by xlash** [comment]
Pretty much a framework.

I now load my framework to test_runner.html and requester.html.

Then in my tests cases, I can specify a new suite of tests. At the top of my tests, I can then specify to run this sequence x amount of time, base on the specific variance.

``` javascript
TC-1 
    Sequence-1 :
                       Pre-request script :
                                  //All my invalid characters for testing, in an array
                                  repetition_data_array = FRAMEWORK.INVALID_CHARACTERS.split(''); 
                                  FRAMEWORK.repeatTC_for(repetition_data_array);
                                  FRAMEWORK.test_init("TC-1","Test case name",['testcategories#1']);
                                  FRAMEWORK.sequence_init("Part1 - Create");
                       Tests :
                                  FRAMEWORK.sequence_end(tests);
      Sequence-2 :
                       Pre-request script  
                                  FRAMEWORK.sequence_init("Part2 - Modify");
                       Tests :
                                  FRAMEWORK.sequence_end(tests);
      Sequence-3 :
                       Pre-request script  
                                  FRAMEWORK.sequence_init("Part3 - Validation");
                       Tests :
                                  FRAMEWORK.sequence_end(tests);
                                  FRAMEWORK.test_exit();

TC-2
```

I now have a separate result screen that pops up, and it display my TC-1 being run x times, each sequence individually, then TC-2.

If that is what you are looking for, I'll publish my code.

**Comment by prabhukirannarava** [comment]
Hi xlash,

Yeah. I am looking for the similar solution. Please publish your code.
Can you please let me know framework details as well ?

Thanks a lot!!

**Comment by xlash** [comment]
See here. Hopefully you have enough details!

https://github.com/xlash/framework_for_automated_TC

**Comment by ceduquey** [comment]
You could try Apibot an easy to use, integration testing tool, that would let you upload data variables on a CSV file, and you could run your test case multiple times.
[http://apibot.co](url)
