### ISSUE TITLE
Add a remark for every param

### ISSUE THREAD

**Issue by lfire** [a85/POSTMan-Chrome-Extension#1438]
add a remark for every param, and so we can set every param's key and value, and then we can mark every params means

**Comment by a85** [comment]
@lfire Check out the blog post. Part of the roadmap: http://blog.getpostman.com/2015/06/05/travelogue-of-postman-collection-format-v2/

**Comment by a85** [comment]
Available in 5.0+

**Comment by lfire** [comment]
Thanks
