### ISSUE TITLE
Requesting Implicit Grant Token only shows empty window

### ISSUE THREAD

**Issue by slamice** [a85/POSTMan-Chrome-Extension#1439]
I've also been using _Postman_ recently for testing OAuth2 with implicit grant. I created a Django application with the [Django Oauth toolkit](https://github.com/evonove/django-oauth-toolkit). The implicit flow works fine when run manually. I mark the redirect url in my app and then try to authenticate it.

However In postman it looks like this:

![screen shot 2015-09-16 at 2 37 41 pm_censored](https://cloud.githubusercontent.com/assets/1047713/9914624/b3489c26-5c80-11e5-8089-e5dd4b577374.jpg)

My url requesting the auth is at the top, and I filled in the client id (nowhere to add the response_type). When I make the request to access the token an empty white window pops up, and that's it. I'm guessing this is my login screen? It's unfortunate that I can't inspect this window to find out what the error could be.

Is there anything I'm doing incorrectly to request the token through OAuth2 (implicit grant)?

**Comment by abhijitkane** [comment]
Since your auth URL is on localhost, can you try checking the 'Request access token locally' checkbox?

**Comment by slamice** [comment]
@abhijitkane tried that, no dice. Same result.

**Comment by abhijitkane** [comment]
You can inspect the window that opens when you click on 'Get access token' by going to chrome://inspect/#apps, and clicking 'Inspect' for the 127.0.0.1 URL.

What do you see when click on the 'debug URL' that's shown?

**Comment by slamice** [comment]
I have the following in Postman:

![image](https://cloud.githubusercontent.com/assets/1047713/9919646/41c3988c-5c9c-11e5-98e3-147d6573869e.png)

I didn't see the 127.0.0.1 URL, so I'm assuming it's the lower one? This is what that looks like inspected:

![image](https://cloud.githubusercontent.com/assets/1047713/9919566/c7d126a2-5c9b-11e5-8076-c8ea319f67b3.png)

**Comment by abhijitkane** [comment]
Can you include a screenshot of the whole DevTools window (including the console)?

**Comment by nass600** [comment]
Did u manage to get this working?

I am getting the same behaviour and receiving from my API "unauthorized_client" due to sending response_type=code.

Any way to select the desired grant type?

**Comment by czardoz** [comment]
Closing this in favor of #1446 

Additional grant types (including client credentials grant) will be tracked there.
