### ISSUE TITLE
How to read the numeric data from response body

### ISSUE THREAD

**Issue by mverma-va** [a85/POSTMan-Chrome-Extension#1440]
Issue: How to read the numeric data from response body. This might be a silly question but not able to figure out the solution yet.

tests["Status code is 200"] = responseCode.code === 200;
if (responseCode.code === 200)
{
var body = JSON.parse(responseBody);
xas = String(1441238400);
tests["val2"] = body.xas.distance === "18.81999999998294"; //this is not working for me
# }

Response Body:
{
  "1441238400": {
    "distance": 18.81999999998294,
    "fuel": 0
  },
  "1441324800": {
    "distance": 21.449999999982026,
    "fuel": 0
  },
  "1441411200": {
    "distance": 21.449999999982083,
    "fuel": 0
  },
  "1441497600": {
    "distance": 12.349999999988825,
    "fuel": 0
  }
}

**Comment by abhijitkane** [comment]
You'll need to use `body[xas].distance`.  `body.xas.distance` will refer to the "xas" property. You can use `console.log(body)`, `console.log(body.xas)`, `console.log(body[xas])` to debug any issues with tests - http://blog.getpostman.com/2015/06/13/debugging-postman-requests/

**Comment by mverma-va** [comment]
Thanks it did work :)
