### ISSUE TITLE
DELETE no longer works in postman

### ISSUE THREAD

**Issue by agschmidt** [a85/POSTMan-Chrome-Extension#1442]
Version 3.0.16 (packaged), OS: win, Architecture: x86-64, Native client architecture: x86-64

DELETE calls no longer work in Postman, the response received is session timeout.

Example call:  {{token_url}}accounts/{{ea_acct}}/external_tools/{{photoroster_id}}

Even if I replace the environment variables with the actual values, I still am not able to delete the item, receiving a session timeout instead. If I enter the same call into Firefox Rest-Client, I am able to delete without a problem. This just started happening recently and I have tried uninstalling/reinstalling Postman, but it doesn't help.

**Comment by abhijitkane** [comment]
Can you try sending a DELETE request to http://httpbin.org/delete?
If that works, you can check http://blog.getpostman.com/2015/06/13/debugging-postman-requests/ for steps on how to inspect request/response payloads.

**Comment by agschmidt** [comment]
Problem solved...disabled interceptor. Thanks for pointing me to the blog post!

**Comment by abhijitkane** [comment]
I'm able to send delete requests through the Interceptor as well. If you need the Interceptor, try updating to the latest versions of Postman and Interceptor, and trying with `DELETE http://httpbin.org/delete`
