### ISSUE TITLE
Import omits raw body data

### ISSUE THREAD

**Issue by eldarkra** [a85/POSTMan-Chrome-Extension#1443]
Hello,

I've used export to create a backup of my collections.
After sometime I've imported the data back but was surprised to see that the raw body data (in my case JSON strings) was missing from my requests.
The backup file has the that so the problem is probably with the import process.

Thanks.

**Comment by abhijitkane** [comment]
Hi @eldarkra 
I'm not able to reproduce this. Can you mail the file in question to help@getpostman.com?

**Comment by eldarkra** [comment]
File sent.
