### ISSUE TITLE
Not able to read env variable using getEnvironmentVariable

### ISSUE THREAD

**Issue by mverma-va** [a85/POSTMan-Chrome-Extension#1445]
Issue:
I have "dist" set to 21.45 in my active environment, but when I run the below test then all three tests fail and not able to get the value of "dist" from env file in Postman. But if I uncomment the line commented below then all three tests pass. 
Why is that, when I already have the variable in my env., why I can't just use it using postman.getEnvironmentVariable ??

Test Script:
if (responseCode.code === 200)
{
var retData = JSON.parse(responseBody);
//day14 = data.date14daysago;
day14 = 1441411200;
dist = retData[day14].distance;
roundDist = parseFloat( dist.toFixed(2) );

//postman.setEnvironmentVariable("dist", roundDist); Below test works if I uncomment this line

tests["Test1"] = roundDist === environment.dist; 
tests["Test2"] = roundDist === environment["dist"]; 
tests["Test3"] = roundDist === postman.getEnvironmentVariable("dist"); 
}

**Comment by mverma-va** [comment]
Postman details:
Version 3.0.16 (packaged)
OS: linux
Architecture: x86-64
Native client architecture: x86-64

**Comment by abhijitkane** [comment]
Can you please use console.log when you face problems in test scripts? `console.log(postman.getEnvironmentVariable("dist"))`; should print 21.45

Environment variables are stored as strings. You'll need to use `tests["Test3"] = roundDist == postman.getEnvironmentVariable("dist");`

**Comment by mverma-va** [comment]
Thanks it worked and I will use console.log in future to debug.
and sorry about "==" and "===" wrong use, since I am new to javascript.

**Comment by GabbyChangSH** [comment]
@abhijitkane  where to check console.log result? I ran it in the postman and newman, but cannot find the output of console.log. Could you point out? Thank you.

**Comment by abhijitkane** [comment]
@DaisySu For newman, it'll be printed in the command line. For Postman, check DevTools - http://blog.getpostman.com/2015/06/13/debugging-postman-requests/

**Comment by jpdenford** [comment]
I know I'm a bit late to the party but alternatively in most cases you could use JSON.parse to parse the string before comparing eg.
`tests["Test"] = roundDist === JSON.parse(environment.dist);`
