### ISSUE TITLE
Support additional grant-types for OAuth2 (password etc)

### ISSUE THREAD

**Issue by jensstalder** [a85/POSTMan-Chrome-Extension#1446]
It seams apigility requires these to be POST? Is postman sending a GET request?; 

```
{"type":"http://tools.ietf.org/html/rfc6749#section-3.2","title":"invalid_request","status":405,"detail":"The request method must be POST when requesting an access token"}
```

**Comment by abhijitkane** [comment]
Postman makes POST request while requesting the access token. You can enable the "Request access token locally" checkbox and check the Network tab - http://blog.getpostman.com/2015/06/13/debugging-postman-requests/

Is it possible that the access token URL you are entering is redirecting to another URL?

**Comment by jensstalder** [comment]
Dev tools seams to simply return a Request URL:data:image/png;base64.. when I do a request.

**Comment by jensstalder** [comment]
Figured it out, sorry my fault. The apigility endpoint for authorizations is /oauth/authorize not just /oauth

will postman support other grant_types in the future? for example password?

```
{
    "grant_type": "password",
    "username": "testuser",
    "password": "testpass"
}
``
```

**Comment by abhijitkane** [comment]
Yes, we're working on additions to the OAuth2 flow, and exploring possibilities of allowing custom plugins. Don't have an ETA on this yet, though.

**Comment by michaelsogos** [comment]
Dear,

There are news about having password grant_type?

**Comment by oleksiyserg** [comment]
any updates on when the implicit grant flow will be supported in Postman?

**Comment by kamalaknn** [comment]
@BukeMan `Authorization Code/Client Credentials/Password/Implicit/` grant types are supported in Postman Native apps starting from `5.3.0`. 

Could you make sure you're on the latest version of Postman Native app and check for OAuth 2 grant types?

**Comment by oleksiyserg** [comment]
@kamalaknn indeed, the implicit grant type is present and is working properly with Azure AD. thank you!

**Comment by jmatelet** [comment]
implicit and authorization code are not working properly with local AS. The window "Request token" stays blank.
The option to retrieve from local is not available in this version...

**Comment by harryi3t** [comment]
@jmatelet Could you open a separate issue for this with more details? I will be happy to debug and solve the bug.
Please include relevant screenshots, console logs (Postman console and Chrome dev console) and if possible, Auth URL and Access token URL too.
