### ISSUE TITLE
Swagger Yaml import - basePath attribute not being included in request url

### ISSUE THREAD

**Issue by ichabodcole** [a85/POSTMan-Chrome-Extension#1447]
I've tried this with multiple files including the swagger-editor examples, and the basePath does not get included in the resulting request urls.

Note this is true when using json format as well. Have tested on 2 macs with same results.

Version 3.0.17 (packaged)
OS: mac
Architecture: x86-64
Native client architecture: x86-64

**Comment by abhijitkane** [comment]
@ichabodcole Are you still seeing this?
