### ISSUE TITLE
Can not connect to Sync

### ISSUE THREAD

**Issue by yankeeinlondon** [a85/POSTMan-Chrome-Extension#1448]
Sometime yesterday I stopped being able to connect to Sync. Is it down? How does one tell? For whatever reasons both my laptop and my desktop can not connect:

![image](https://cloud.githubusercontent.com/assets/980757/10067385/1431091a-6294-11e5-9673-c367ac8dea4f.png)

**Comment by sobtiankit** [comment]
@ksnyde We were under a heavy server load for the last hour. The system has scaled up and you should be able to connect now. I'd recommend a restart of the app to drain any existing failed connections.

**Comment by yankeeinlondon** [comment]
thanks, desktop is now connected and in sync but laptop (which is new) can not connect. I would say this is a different issue though so I'll close this one.

**Comment by abhijitkane** [comment]
@ksnyde Can you try signing out and signing in to Postman on your laptop?

**Comment by yankeeinlondon** [comment]
that worked, thanks!
