### ISSUE TITLE
[FEATURE]: use of environment is uncomfortable

### ISSUE THREAD

**Issue by ailjushkin** [a85/POSTMan-Chrome-Extension#1451]
As a feature request:

Ability to change parameters on the fly (in the popup)

for instance: i have parameter "token"

auth token dies and i should click to environment, then on manage env , then on my environment, then click to the edit box, edit, then save it and then click to close dialog.

This is such an evil behaviour and just to edit one field :)

**Comment by rpajaziti** [comment]
When you edit this environment variable, where do you take that value, i suppose in some login endpoint or something similar?

**Comment by ailjushkin** [comment]
I'm using it in the url, http://...........?token={{token}} , I need to
change {{token}} quite often.

пн, 5 окт. 2015 г. в 12:30, RamadanPajaziti notifications@github.com:

**Comment by arctouch-douglaskazumi** [comment]
@ailjushkin I agree that editing variables in the popup would be nice but in your case, you can do even better if you set up a script to your auth request that updates the environment with the token in the response.

**Comment by ailjushkin** [comment]
Hi, it's 2yrold question, postman grew up alot since I asked it) but thanks
for the answer!

**Comment by vkaegis** [comment]
Hey, looks like we missed closing this issue. You can now edit current values of variables in the environment quick-look. Feel free to open another issue if you have more feedback around this.
