### ISSUE TITLE
[FEATURE]: Add ability to share environments for the entire team

### ISSUE THREAD

**Issue by BradleyDHobbs** [a85/POSTMan-Chrome-Extension#1452]
I just installed postman beta for a couple of users in our company. However, I find myself having to set up the environments every time on every computer. It wasn't too hard as there is export and import options, but there should be a way for the admin to add environments for the entire team and have them accessible to all team members.

**Comment by rpajaziti** [comment]
We found this option needed also for our team, but too bad postman doesnt have it.
What we did is, if someone(other team member) wants to run our endpoints, what he needs to do is just create an empty environment, and just place there only url.
All others we will be generating. For example, after login there is an access_token generated, we place postman.setEnvironmentVariable in tests after body is returned and take that url and place it in environment.
Then use it as Authorization in Headers. All other variables are also generated. We found this practice best as there is no other option.
I hope it helps.

**Comment by felipeplets** [comment]
We have the same feeling as @BradleyDHobbs, we can do it manually, but having it synced would be a great production speed up.

**Comment by pijusn** [comment]
This is the reason I came here. This would be amazing! Plus (this should probably be a separate issue but it will only be needed when shared) it would be cool to enable multiple environments combining and overriding values. Use case for this:

API developer(s) share collections and environments for their service but to use it everyone must have their own API key or token in the environment.

**Comment by a85** [comment]
Thanks for the votes on this feature folks. We are working hard to ship this. We won't have multiple environments combining etc. yet but that is on the roadmap too.

**Comment by eXeDK** [comment]
+1 for this feature

**Comment by Gutbuster** [comment]
+1. Was quite surprised not to see this implemented when we started using team collections.

**Comment by a85** [comment]
We are testing this out in a new version internally. Will be out super soon!

**Comment by a85** [comment]
This is out through environment templates now in Postman Cloud.
