### ISSUE TITLE
[FEATURE]: Add ability to set default environment for a collection

### ISSUE THREAD

**Issue by BradleyDHobbs** [a85/POSTMan-Chrome-Extension#1453]
It would be nice to have the ability to set a default environment for a collection. The user could still change environment if they wanted, but when you first go to a collection and run an API call, you will not have an environment set. Also, you might forget to switch environments when moving from collection to collection. This would make it easier and faster to handle multiple collections/environments in postman

**Comment by gchokeen** [comment]
+1 - I was looking for the same. I have three different environment. So I managing three different collections. because I need to change the api end point each time. if there is a option set default api endpoint to the collection that will be awesome.

**Comment by rpajaziti** [comment]
+1 to this. It would be great, because i allways forgot to select the right environment for a collection.

**Comment by aupp** [comment]
:+1:  I was just googling this feature and found this :)

**Comment by pseglar** [comment]
+1

**Comment by a85** [comment]
Tracking as part of #3205

**Comment by aelimport** [comment]
Wow, this is still much needed feature
