### ISSUE TITLE
Support for OAuth 2.0 Client Credentials flow

### ISSUE THREAD

**Issue by jonaskello** [a85/POSTMan-Chrome-Extension#1454]
Current version of Postman seems to only support getting tokens with code grant flow. Please add client credentials flow too.

**Comment by jimonthebarn** [comment]
This would be awesome. I'd like to second this feature.

**Comment by abhijitkane** [comment]
@jonaskello @jimonthebarn The latest version of the app (3.2.11) has this feature. You'll need to select the 'Client Credentials' grant type in the OAuth2.0 helper.

**Comment by jimonthebarn** [comment]
Thanks a lot.
