### ISSUE TITLE
Synced collection creating duplicates

### ISSUE THREAD

**Issue by datarup** [a85/POSTMan-Chrome-Extension#1456]
Is there a way to remove synced collections from getpostman.com? My collections are all messed up with up to 4 duplicate folders for some of them on getpostman.com. I tried deleting from postman app and 'Force-Sync' but they still persist in getpostman.com and once I sign out and sign back in, I get all the duplicates and deleted collections back.

**Comment by abhijitkane** [comment]
@datarup Can you send an email to help@getpostman.com with your username and Postman application version?

**Comment by datarup** [comment]
Sent! Thanks for the instant response :-)

**Comment by datarup** [comment]
Solved it by deleting in the whole collection and re-syncing from a backup file. thanks @abhijitkane
