### ISSUE TITLE
Swagger import - brackets being turned into html entities

### ISSUE THREAD

**Issue by ichabodcole** [a85/POSTMan-Chrome-Extension#1457]
This happens whether using a json formatted file or yaml.

Expecting:
http://mydomain.com/customers/{{cust_no}}/contact

Getting this:
http://mydomain.com/customers/%7B%7Bcust_no%7D%7D/contact

Version 3.0.17 (packaged)
OS: mac
Architecture: x86-64
Native client architecture: x86-64

**Comment by abhijitkane** [comment]
Thanks for pointing this out. We'll push a fix for this soon.

**Comment by abhijitkane** [comment]
@ichabodcole Can you confirm this fixed in the latest version (4.2.1)?
