### ISSUE TITLE
WADL Import: Header values appended with \n

### ISSUE THREAD

**Issue by raygig** [a85/POSTMan-Chrome-Extension#1458]
During a WADL import a \n is appending to the header value as illustrated below. This was working perfectly about a month ago.

![image](https://cloud.githubusercontent.com/assets/1569098/10147476/335c7a98-65fc-11e5-9e3e-02866dd3371c.png)

**Comment by a85** [comment]
@czardoz Can you look into this please?

**Comment by czardoz** [comment]
yep, will fix this right up

**Comment by raygig** [comment]
Is there any update on this one?

**Comment by abhijitkane** [comment]
@raygig Apologies for the delay on this. We've fixed this in our internal build, and will be pushing the fix in the next release.

**Comment by abhijitkane** [comment]
@raygig Can you confirm this fixed in the latest version of the app (4.2.1)?
