### ISSUE TITLE
WADL Import: Content Type XML not working

### ISSUE THREAD

**Issue by raygig** [a85/POSTMan-Chrome-Extension#1459]
When importing a WADL with a content type text/xml the import will fail. This was working about a month ago.

![image](https://cloud.githubusercontent.com/assets/1569098/10147554/98251f70-65fc-11e5-876a-cbf2b34c0948.png)

But if you change the content type to html/text it works.

![image](https://cloud.githubusercontent.com/assets/1569098/10147731/dc3b296a-65fd-11e5-96b8-d08d93a0118b.png)

**Comment by abhijitkane** [comment]
@raygig Sorry about this. We made a few updates to our importing mechanism in the last release. We'll push a fix for this soon.

**Comment by raygig** [comment]
Thank you

**Comment by abhijitkane** [comment]
@raygig Can you confirm this working now?
