### ISSUE TITLE
Issue in fetching utf-8 charset

### ISSUE THREAD

**Issue by dipeshcct** [a85/POSTMan-Chrome-Extension#1462]
Hello,

I am trying to test REST api which give result in Chinese language. I tried by setting header like "Content-Type:application/x-www-form-urlencoded" and "Accept-Charset:UTF-8" but it don't return proper word. 

Thanks.

**Comment by abhijitkane** [comment]
Can you check the response in the Network tab of the DevTools window - http://blog.getpostman.com/2015/06/13/debugging-postman-requests/? A screenshot would help.

**Comment by dipeshcct** [comment]
I checked response in the Network tab it show an error message
Refused to set unsafe header "Accept-Charset" on this line 
xhr.responseType = responseRawDataType;
        var headers = pm.request.getXhrHeaders(headers);
        for (var i = 0; i < headers.length; i++) {
            xhr.setRequestHeader(headers[i].name, headers[i].value);
        }

**Comment by abhijitkane** [comment]
The Accept-Charset header is a restricted header (https://getpostman.com/docs/requests#headers), and you'll need to enable the Interceptor to send it (https://chrome.google.com/webstore/detail/postman-interceptor/aicmkgpgakddgnaphhhpliifpcfhicfo?hl=en).
