### ISSUE TITLE
  Randomly mixing up file contents and names

### ISSUE THREAD

**Issue by oofpez** [a85/POSTMan-Chrome-Extension#1466]
I’ve found a strange issue when using Postman to make a form-data Files post with multiple files.

Version 3.0.13.1 (packaged)
OS: win
Architecture: x86-32
Native client architecture: x86-64

Api Context:
Handling the request in a WebApi (C#)
public IActionResult PostFiles(Guid id, IReadOnlyList<IFormFile> files)

To replicate:
Make a post, choose form-data, click choose files, submit multiple files in one go.

Result:
The file contents and names in the controller are randomly assigned to each other.

Note:
This does not happen when using a page to make the request, or usingnewman in command-line… only when using Postman.

**Comment by abhijitkane** [comment]
Are you selecting multiple files in the file selector that opens, or adding multiple rows to the form-data editor?

Can you share the exported collection that works in Newman?

**Comment by oofpez** [comment]
I am selecting multiple files in the selector.

relevant post from collection: http://pastebin.com/ZF0rQbxY

**Comment by abhijitkane** [comment]
I was unable to reproduce this - I selected 4 files in the selector, and the filename-contents matched correctly. Can you run something like Charles Proxy (http://www.charlesproxy.com/) and check the payload that's being sent from Postman?

**Comment by oofpez** [comment]
I used fiddler to anaylyze the request for two different sets of files.
The first set contained 11 smallish files, and the request was correct.
 the second set contained 10 larger files (varying between 1kb and 5mb in
size), and their contents were indeed mismatched to the names.

**Comment by a85** [comment]
@madebysid Still valid?
