### ISSUE TITLE
Can't use numeric JSON with Environment Variables in Body

### ISSUE THREAD

**Issue by clinch** [a85/POSTMan-Chrome-Extension#1468]
I have an environment variable called _messageid_ which is a numeric value (int) that I'm trying to send as JSON in my POST request's Body. My request headers are Content-Type=application/json

For example:

Environment variable: **messageid = 3**

``` json
{
    "id": {{messageid}}
}
```

This creates a JSON parsing issue which then prevents the message from sending, even though the environment variable should be properly set prior to the request.

Any suggestions as to how I can make this work? The value of id needs to be numeric, so I cannot simply wrap it in quotes.

**Comment by clinch** [comment]
Solved my own problem. The issue was that I was trying to parse the data in my pre-request script, however, the environment variables and global variables are not set at the point that the pre-request script runs. So I simply swap the variables in myself. Here's the solution: rather than dealing with the raw _request.data_, I made a copy and then search and replace every variable.

``` javascript
var data = request.data;

// Start by searching and replacing environment variables
// (This hasn't happened yet when this script is executing.)
for (var key in environment) {
    data = data.split('{{' + key + '}}').join(environment[key]);
}
for (var key in globals) {
    data = data.split('{{' + key + '}}').join(globals[key]);
}

var jsonObj = JSON.parse(data);
```

**Comment by felipeplets** [comment]
@clinch thanks! This was exactly what I was looking for.

**Comment by tylerw909** [comment]
Is there an equivalent of this method for collectionVariables?  I have not been able to accomplish the same thing through the use of collectionVariables.
