### ISSUE TITLE
Swagger import - BasePath ignored

### ISSUE THREAD

**Issue by RitwikChatterjee** [a85/POSTMan-Chrome-Extension#1469]
Hi,
I think this is a problem:
When I am importing a Swagger definition, the basePath element is ignored.

**Comment by abhijitkane** [comment]
@RitwikChatterjee This bug has been fixed, and we'll be pushing it in the next release of the app.

**Comment by ichabodcole** [comment]
YAY!!!

**Comment by chrisxue815** [comment]
basePath is still ignored if it contains a question mark.
`basePath: /index.php/api/v2`: works.
`basePath: /index.php?/api/v2`: ignored.
