### ISSUE TITLE
Request body can be changed to a body of another request in other tab during undo/redo actions by hotkeys

### ISSUE THREAD

**Issue by alhimic37** [a85/POSTMan-Chrome-Extension#1474]
Version 3.0.17 (packaged)
OS: win
Architecture: x86-32
Native client architecture: x86-64

Steps:
1. Open 2 requests with a raw body in its own tab
2. Make some changes in each body
3. Play with undo/redo actions by hotkeys ctrl-z/ctrl-y

Actual result:
Request body can be changed to a body from another

Expected result:
Each tab has its separate 'buffer' of the request modifications in order to make undo/redo actions correctly

**Comment by abhijitkane** [comment]
@alhimic37 The latest versions of the app have this fixed. Thanks for reporting this.
