### ISSUE TITLE
Feature Request to generate PowerShell 

### ISSUE THREAD

**Issue by roundand** [a85/POSTMan-Chrome-Extension#1475]
I would find it very helpful if Postman could generate PowerShell code, using Invoke-RestMethod (more productive) and / or Invoke-WebRequest (more faithful) which are present in PowerShell 3 [1] or later.

[1] "PowerShell 3.0 is integrated with Windows 8 and with Windows Server 2012. Microsoft has also made PowerShell 3.0 available for Windows 7 with Service Pack 1, for Windows Server 2008 with Service Pack 1, and for Windows Server 2008 R2 with Service Pack 1" https://en.wikipedia.org/wiki/Windows_PowerShell#PowerShell_3.0

**Comment by 3goats** [comment]
plus 1 for this.

**Comment by symeonb** [comment]
Plus 1 for this too

**Comment by elssar** [comment]
We use a 3rd party library to generate code snippets and currently it does not currently support Powershell. I have added a feature request for Powershell -  Mashape/httpsnippet#75

**Comment by whiteboxcode** [comment]
- 1 on this for me too.  Would be a great feature.

**Comment by rarrarrarr** [comment]
+1

**Comment by alastairtree** [comment]
+1

**Comment by rocksolid1974** [comment]
+1

**Comment by srufle** [comment]
+1

**Comment by moose1882** [comment]
+1

**Comment by garethtsnapper** [comment]
+1

**Comment by gitfool** [comment]
👍

**Comment by stevaaa** [comment]
+1

**Comment by plremis** [comment]
+1

**Comment by rusecure** [comment]
+1

**Comment by 123dev** [comment]
+1

**Comment by JuanGilpin** [comment]
+1

**Comment by blueboxes** [comment]
+1

**Comment by portaljacker** [comment]
+1

**Comment by cyberalchemist** [comment]
+1

**Comment by BeardedPrincess** [comment]
+1

**Comment by sabixx** [comment]
+1

**Comment by Smackatoa** [comment]
+1

**Comment by wilddev65** [comment]
+1

**Comment by zosocanuck** [comment]
+1

**Comment by mdcougar** [comment]
+1

**Comment by AlexBevan** [comment]
+1

**Comment by MosheBlumbergX** [comment]
+1

**Comment by symeonb** [comment]
All the people +1 on here should +1 at https://github.com/Mashape/httpsnippet/issues/75 as that is the library that is used .

**Comment by sunmorgus** [comment]
+1

**Comment by ramnov** [comment]
+1

**Comment by ryansonshine** [comment]
+1

**Comment by GeekMustHave** [comment]
+1 More if I could

**Comment by evanextreme** [comment]
+1, keeping the dream alive

**Comment by mgaruccio** [comment]
+1 this would be amazingly helpful

**Comment by koenbud** [comment]
PowerShell would be great! +1

**Comment by mikecg** [comment]
+1

**Comment by terenceng2010** [comment]
+1

**Comment by casey-robertson** [comment]
I'll add mine too!  +1

**Comment by rikbosch** [comment]
+1

**Comment by bobmclaren** [comment]
I just authored a pull request for this.
https://github.com/Kong/httpsnippet/pull/105

Hopefully it gets some legs.

**Comment by ronnysteiner** [comment]
+1

**Comment by mccannical** [comment]
+1

**Comment by KingOfSpades** [comment]
+1

**Comment by kristianthim** [comment]
+1

**Comment by Rudithus** [comment]
+1

**Comment by pldmgg** [comment]
Hopefully this is an easy lift now that Chrome has "Copy as PowerShell" built in -

https://twitter.com/matijagrcic/status/979743034849021953

:)

**Comment by johnib** [comment]
so many likes, so long ago -- any update on the ETA for this? :)

**Comment by ShaneCal** [comment]
+1

**Comment by dbaluguri-exp** [comment]
+1

**Comment by sbryden-mbo** [comment]
+1

**Comment by sbhotika** [comment]
+1

**Comment by Imranonline** [comment]
+1

**Comment by Imranonline** [comment]
Any updates on this ?

**Comment by Jt3kt** [comment]
+1

**Comment by DDriggs00** [comment]
+1, Any updates?

**Comment by red1laref** [comment]
+1

**Comment by NPM8** [comment]
+1, still no update?

**Comment by aappleton** [comment]
+1

**Comment by FallenGameR** [comment]
+1

**Comment by Crucial2K** [comment]
+1

**Comment by gregoirefra** [comment]
+1

**Comment by jager1000** [comment]
+1

**Comment by momotaro98** [comment]
+1

**Comment by atscripter** [comment]
+1

**Comment by kclinden** [comment]
+1

**Comment by drexmogu** [comment]
+1

**Comment by joeygit** [comment]
+1

**Comment by adamtajti** [comment]
+1

**Comment by japena03** [comment]
+1

**Comment by kenmaglio** [comment]
+1

**Comment by NateCrabb** [comment]
+1

**Comment by rvf148** [comment]
+1 This feature is long overdue, please put it on the roadmap!

**Comment by vpinheiro86** [comment]
+1

**Comment by MdeRhoter** [comment]
Huge +1

**Comment by dotnvo** [comment]
+1, would be amazing.

**Comment by kenmaglio** [comment]
I've tried reaching out on twitter to the company, I would contribute and help build this feature if possible. But I don't see any way given the repo's that are exposed already on github, to get to core app to help build support for this.  #sadpanda

**Comment by alexkoppelman** [comment]
+1

**Comment by kenmaglio** [comment]
I've been looking into the [Issue](https://github.com/Kong/httpsnippet/issues/75) filed over on Kong. Trying to get traction there. 

Trying to get the [PR](https://github.com/Kong/httpsnippet/pull/105)  looked at by  @ahmadnassri or  @darrenjennings   over there...

Apparently, this library is what Postman uses to do the code snippets. and @bobmclaren graciously has already coded up support for PowerShell into Kong.

**Comment by kenmaglio** [comment]
@elssar  Please see that Kong now supports PowerShell via  [feat(powershell): add powershell webrequest target #127](https://github.com/Kong/httpsnippet/pull/127).

Can we get someone here at postman to look at their new master and pull in support pretty please!!

@darrenjennings Rocks!   ( you too @bobmclaren )

**Comment by darrenjennings** [comment]
This is now bundled with [httpsnippet@1.16.7](https://www.npmjs.com/package/httpsnippet/v/1.16.7). 

@elssar et al. @ahmadnassri and myself are currently in the process of rejuvenating the httpsnippet project and would up for seeing the improvements your team has made to https://github.com/postmanlabs/httpsnippet-fsless. I will be reviewing the repo and merging in any updates as makes sense. We will be working on a roadmap and refactor also that will allow targets to be their own npm packages.

**Comment by a85** [comment]
Thank you @darrenjennings! We have hundreds of requests around this!

**Comment by kenmaglio** [comment]
@a85 @elssar  Do you guys need someone from the community to take a stab at a PR merge from upstream on the [httpsnippet-fsless](https://github.com/postmanlabs/httpsnippet-fsless) repo?

**Comment by abhijitkane** [comment]
@kenmaglio Are you talking about https://github.com/postmanlabs/httpsnippet-fsless/pull/16/files We're working on a revamp of the code generation feature in Postman. Hope to have an update here in a few weeks.

**Comment by kenmaglio** [comment]
@abhijitkane It would be more to pull in the changes from [httpsnippet@1.16.7](https://www.npmjs.com/package/httpsnippet/v/1.16.7) which now supports PowerShell into the forked version postman uses.

**Comment by kenmaglio** [comment]
@a85 @elssar  Any possibility of movement on this Feature Request?

**Comment by abhijitkane** [comment]
@kenmaglio I've created a PR, but internal testing and releasing into the app will take time.

**Comment by sebastian-tennant** [comment]
+1 on this

**Comment by ziabytes** [comment]
Oh man cant wait

**Comment by VijayendraM** [comment]
+1

**Comment by abhijitkane** [comment]
Everyone - the latest Postman Canary has support for a new set of code-generators, including Powershell and JS-Fetch.

Canary can be downloaded from https://www.getpostman.com/downloads/canary, and run be run side-by-side with your regular Postman app. You'll need to enable the Experimental Codegen mode option in Postman's global settings to see the new language options.

cc @VijayendraM @ziabytes @sebastian-tennant

**Comment by jdrews** [comment]
I pulled down the latest Postman Canary (Postman v7.3.0-canary01) and I don't see powershell as an option. Am I looking in the wrong place?

![image](https://user-images.githubusercontent.com/172766/59703475-f5363280-91c7-11e9-8a94-66576966bebc.png)

**Comment by a85** [comment]
<img width="793" alt="Screenshot 2019-06-18 09 54 49" src="https://user-images.githubusercontent.com/653409/59703647-2eae7400-91af-11e9-95c7-67e2e15df812.png">

@jdrews 
 You need to enable the experimental code gen mode in settings first.

**Comment by jdrews** [comment]
Tada! Thanks
