### ISSUE TITLE
Does not start on Linux mint

### ISSUE THREAD

**Issue by LeoJavaAI** [a85/POSTMan-Chrome-Extension#1476]
It was working fine, now it does not start, all I see is a circular progress bar, what should I do to fix?

**Comment by abhijitkane** [comment]
Can you check the Postman version in chrome://extensions? Also, enable the DevTools (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/) and check the console for any errors.

**Comment by LeoJavaAI** [comment]
These are the errors I get , I am not sure how I should go about resolving them

https://bpaste.net/show/4777fba051b3et

**Comment by abhijitkane** [comment]
We've pushed version 3.0.20 that should fix this. You can go to chrome:/extensions, enable 'Developer Mode', and click 'Update extensions now' to update.

**Comment by LeoJavaAI** [comment]
working now thx
