### ISSUE TITLE
Version 3.0.18 not sending POST data to localhost

### ISSUE THREAD

**Issue by r3oath** [a85/POSTMan-Chrome-Extension#1478]
I'm having trouble sending post data to locally hosted services, where as before it was working perfectly. I hadn't checked the version number while it was working, but I'm currently sitting on version 3.0.18, attempting to send post requests with parameters to a service hosted at localhost:8000. I can confirm there isn't a problem with the service as trying the equivalent requests with CURL etc work as expected.

**Comment by abhijitkane** [comment]
@r3oath Is the Interceptor enabled? If so, this has been fixed in the latest version - 0.2.13.

**Comment by r3oath** [comment]
@abhijitkane Did you get that version number right? My current version is now `3.0.20` and this bug is still present when the interceptor is enabled.

**Comment by abhijitkane** [comment]
@r3oath Sorry, I meant the version of the Interceptor. You're probably on 0.2.12.

**Comment by r3oath** [comment]
@abhijitkane yup you're right, how do I go about updating it? Restarted postman/chrome a few times and haven't received the new version as of yet.

**Comment by abhijitkane** [comment]
Head to chrome:/extensions, enable 'Developer Mode', > Update extensions now.

**Comment by r3oath** [comment]
Awesome, everything is working as expected now.
