### ISSUE TITLE
Browse for file button missing 

### ISSUE THREAD

**Issue by gurra777** [a85/POSTMan-Chrome-Extension#1479]
I think this happened after automatic upgrade to 3.0.19 or 3.0.18

When building a post request with form-data body, there used to be a browse button to select a file for a key-value value of type "File". That button is gone now and no file can be selected.

![missingbutton](https://cloud.githubusercontent.com/assets/1786979/10275071/c4b7f86c-6b44-11e5-94f7-364b8b9ae921.png)

**Comment by abhijitkane** [comment]
@gurra777 Can you try deleting the row (hover over it and click the X button on the right) and adding a new one?

**Comment by gurra777** [comment]
Ah, yes that worked! Thanks!

I forced upgrade to 3.0.20. Issue remains for old request.

**Comment by Londeren** [comment]
I have the same issue in 3.0.20

**Comment by b22n** [comment]
I have the same issue in 3.0.22 for mac
and if I add a new row, I can see the button, but file params not attatched to a request actually

**Comment by abhijitkane** [comment]
@b22n Can you try turning off the Interceptor if it's on? Also, do you see any errors in the console - http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/?

**Comment by b22n** [comment]
@abhijitkane Oh, It works well if I turn off the Interceptor

Console logs below when I turned on the Interceptor.

![default](https://cloud.githubusercontent.com/assets/868971/10355448/105e93b6-6da7-11e5-8896-033e250971d0.png)

**Comment by abhijitkane** [comment]
Great..There's an issue with file uploads through the Interceptor which we'll be fixing soon.
