### ISSUE TITLE
Receiving 200 OK response but 'DUPLICATE HEADERS' error in OAuth2 flow

### ISSUE THREAD

**Issue by SamScholefield** [a85/POSTMan-Chrome-Extension#1480]
I'm running into issues when attempting to obtain an OAuth2 authorization token in Postman for the Google Directory Api (this is for an EDU domain)

I posted full issue description on SO (http://stackoverflow.com/questions/32931954/postman-oauth2-and-google-directory-api) since then I've done some further digging into the actual headers received and notice that I'm getting a 200 OK response from the server. If you guys need any additional information please let me know what it is and I'll provide it.

**Comment by abhijitkane** [comment]
When you click on the debug URL, can you open the DevTools (View > Developer > Tools) and check if any errors show up in the console?

**Comment by SamScholefield** [comment]
The duplicate headers error is only on-screen for a moment, but in that time the following is displayed in the console:

/deep/ combinator is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details.

The rest of the time the console remains clear.

**Comment by abhijitkane** [comment]
In the SO question, you've mentioned that you've set the Authorization and Access token URL to the same value. This is probably incorrect. The Authorization URL is the one that the user is shown (which is working). The Access Token URL is the one to which a back-end POST call is made. 

Try setting the Access Token URL to https://accounts.google.com/o/oauth2/token. If that doesn't help, you'll need to contact Google.

I've replied on the SO post as well.

**Comment by SamScholefield** [comment]
Legendary, switched the access token URL and success! Thanks a lot for your help. I thought it odd that they were the same, couldn't find anything clear in any documentation though.
