### ISSUE TITLE
Allow body in GET requests

### ISSUE THREAD

**Issue by bashok001** [a85/POSTMan-Chrome-Extension#1481]
With advent of elasticsearch REST API, there is a need for body in GET requests too. 

https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-term-query.html

They expect the query to be like:
 curl -XGET {endpoint}/_search -d '{
     "query" : {
         "term" : { "user": "kimchy" }
     }
 }'

Please add this functionality.

**Comment by abhijitkane** [comment]
Closing as a duplicate of https://github.com/postmanlabs/postman-app-support/issues/1112 and https://github.com/postmanlabs/postman-app-support/issues/996

**Comment by abhijitkane** [comment]
@bashok001 
With v2.0 of Elasticsearch, you can send a POST request instead (Last line of https://www.elastic.co/guide/en/elasticsearch/reference/2.0/search-request-body.html)

**Comment by bashok001** [comment]
Thanks @abhijitkane !
