### ISSUE TITLE
[Feature]: enable/disable flag for URL params and Headers

### ISSUE THREAD

**Issue by ailjushkin** [a85/POSTMan-Chrome-Extension#1482]
Would be cool if I could disable URL parameter using a smal button near it insteard of removing it by hands.

**Comment by a85** [comment]
@PositiveAlex This is part of our roadmap.

**Comment by prashantagarwal** [comment]
Hi @PositiveAlex ,
We are tracking this issue #785 . Closing this duplicate issue
