### ISSUE TITLE
Feature: I would like to receive more information from the collection runner

### ISSUE THREAD

**Issue by greedy33** [a85/POSTMan-Chrome-Extension#1483]
For example: In the collection runner, I can see that 4 of the same calls passed, but one failed. However, if I am sending through batch data, I cannot tell which one of the calls failed. It would be great to have more information about the failures.

**Comment by jjurisch** [comment]
Would also like this feature. I know you can use console.log() to add whatever we want to the console, but would be ideal to just be able to expand and see what the actual value was for my failed/passed test. 

For example - to see what the actual status is (other than 500) I basically have to duplicate every line with a console.log like: 

```
console.log('Status Code: ' + responseCode.code);
tests["Status code is 500"] = responseCode.code === 500;
```

It would be nice if we could simply click and expand the Test to see the details about each run: 
![image](https://cloud.githubusercontent.com/assets/492128/12987986/481cad4e-d0c4-11e5-9f41-e10660fa98c4.png)

**Comment by a85** [comment]
We have made several changes to the Collection Runner. This should be possible in the new collection runner design in 5.0+
