### ISSUE TITLE
Add customer text to test window

### ISSUE THREAD

**Issue by chs8788** [a85/POSTMan-Chrome-Extension#1484]
hi,
i would like to add some customer text to test window in postman
usase:
when my test fails then i would like to know the reason like current / expected output that i can add os that i can know the reason

![image](https://cloud.githubusercontent.com/assets/15009390/10330105/ae873514-6ce6-11e5-9f2e-e41b3f2a4bee.png)

**Comment by a85** [comment]
@chs8788 Test reason failures can be added as part of your test string key for now.

**Comment by chs8788** [comment]
@a85 Thanks.can you please give a code snipped as i am new to this

**Comment by a85** [comment]
@abhijitkane Adding this as part of the pm API project.

**Comment by vkaegis** [comment]
Hey guys, looks like we missed closing this. pm.test now supports custom text. Feel free to open another issue if you have more feedback around this.
