### ISSUE TITLE
[FEATURE]: Environment Domains

### ISSUE THREAD

**Issue by felipeplets** [a85/POSTMan-Chrome-Extension#1485]
There is a use case in which I need a mix of environments, what I call "environment domains", for instance the most common is the server and user data. 

Let`s say I have 3 different servers (development, test, production) and 3 user profiles (admin, user, guest), nowadays to test each possible scenario using Postman environments I need 9 different configurations called (development - admin, development - user, etc... ) but if I have environment domains (server and user) I would have only 3 different configurations in each one and to execute the tests I can only combine the environments. 

Example: 
- Environment domain: server
  - environment: development
    - protocol: http
    - host: localhost
    - port: 8080
  - environment: test
    - protocol: http
    - host: 192.168.0.100
    - port: 80
  - environment: production
    - protocol: https
    - host: api.my.com
    - port: 80
- Environment domain: user
  - environment: adm
    - username: felipeplets
    - password: lalala
  - environment: user
    - username: felipeplets2
    - password: 123
  - environment: guest
    - username: felipeplets3
    - password: 

To test in development server with admin user I would select: 
- Environment domain server = development
- Environment domain user = admin

**Comment by a85** [comment]
Thanks for the suggestion! We are trying to re-design the environment functionality and we'll try to incorporate your suggestions.

**Comment by calebrepkes** [comment]
Hey, Im really curious to something like this too. 

Right now Im experiencing that I have three different domains too:
Environment
Application
Language

Maybe its an idea to give the ability to set multiple columns for environment variables. 

I have incorporated Pre-request scripts, in which I make decisions for API's based on the environment picked.

**Comment by a85** [comment]
We recommend using Workspaces now for different configurations. Collections and Environments are shareable across workspaces so this and other configurations should be easy to set up.

**Comment by a85** [comment]
Closing this as we don't envision supporting nested environments any time soon. We have introduced additional scopes with Collection variables so hopefully this should help.
