### ISSUE TITLE
[FEATURE] Body form data as JSON 

### ISSUE THREAD

**Issue by felipeplets** [a85/POSTMan-Chrome-Extension#1486]
To have to develop, maintain and read the JSON body in the raw tab is not easy and can easily lead to mistakes. One option to enhance this is to have a feature to define in the form-data that it shall be sent as JSON object. In this case Postman would convert automatically from the key/value format to JSON format.  

Example: 
## Form data

![screen shot 2015-10-07 at 10 30 12 am](https://cloud.githubusercontent.com/assets/119980/10338830/8c28bce8-6cde-11e5-8d79-7c7c6735e3d7.png)
## Generated raw JSON

![screen shot 2015-10-07 at 10 30 23 am](https://cloud.githubusercontent.com/assets/119980/10338846/ac044b22-6cde-11e5-988d-cec7e3b48970.png)

**Comment by a85** [comment]
We might have plug-ins for this in the future but for now conversions like these will have to be done manually.

**Comment by shirshak55** [comment]
Is this feature going to come ?

**Comment by codenirvana** [comment]
Duplicate of #1104

@shirshak55 https://github.com/postmanlabs/postman-app-support/issues/1104#issuecomment-411693253

**Comment by neoscrib** [comment]
This is not a duplicate of 1104

**Comment by valdis-aglonietis** [comment]
This is not a duplicate of #1104. #1104 allows specification of content type for fields.
#1486 feature allows automatic conversion from body form-data to raw json

**Comment by itsouvalas** [comment]
@a85 Using the form to convert to json would make it an amazing feature indeed. Great work whatsoever guys!
