### ISSUE TITLE
Fonts are still unreadably small on high-pixel-density displays

### ISSUE THREAD

**Issue by jmandel** [a85/POSTMan-Chrome-Extension#1487]
#979 and #1015 get at this issue, but fonts remain unreadably small. Screenshot from my "retina display" macbook below:

![image](https://cloud.githubusercontent.com/assets/313089/10340033/3273a7b4-6cdc-11e5-9a26-184b8e44b9c1.png)

**Comment by a85** [comment]
@jmandel We are looking into this.

**Comment by centur** [comment]
Umm, it's ok on 4k display. Does MacOS has\support DPI scale like Windows 10? It might be OS issue rather than Postmans

**Comment by jmandel** [comment]
I'm using Ubuntu; my normal experience in Chrome is that I can zoom into content with Ctrl-+ (which doesn't work in Postman the packaged app, though it worked in Postman the extension).

**Comment by michaeltarleton** [comment]
I'm also using the Mac Packaged App on a retina display and I've found the UI/Response font size settings but is there a way to adjust the font size of the left bar or the request body?

I changed the UI to bigger and response font size to 16 which helps but I need to also change the font size of the request body.

Btw, thanks for all the hard work to make this awesome app!

**Comment by elmi82** [comment]
Same Issue on Fedora 23 (GNOME Shell 3.18.4) with 4K Monitor or the Retina Display of the MacBook Pro is close to unreadable. Scaling responses works fine, but everything else is way to small. Any plans to allow scaling or at least generally increase font size of the UI via a setting?

**Comment by aditikul** [comment]
@jmandel @elmi82 @michaeltarleton @centur Can you please check if the latest update has fixed this issue for you? Thanks.

**Comment by centur** [comment]
@aditikul it was ok on Windows before as I mentioned

**Comment by elmi82** [comment]
@aditikul: I don't see much difference. I have the feeling that it's slightly better, but still quite hard to read.

**Comment by a85** [comment]
@elmi82 You can now scale up the entire UI using Cmd + '+'. Check out other shortcuts in the Settings screen!

**Comment by elmi82** [comment]
@a85: Works! Great, thanks for fixing this. :+1:
