### ISSUE TITLE
Content-Type for PATCH

### ISSUE THREAD

**Issue by alaindresse** [a85/POSTMan-Chrome-Extension#1488]
Hi,

I would like to set the content type to application/json-patch+json in a patch operation using postman, but when I type my input in the editor, I seem to be limited to the content types available in the dropdown.

Is there a way to insert a content type that is not listed in the dropdown ? I tried to set the content-type in the header, but it does not take precedence on the dropdown value.

Best regards,
Alain

**Comment by abhijitkane** [comment]
I was unable to reproduce this. Image attached.
![screen shot 2015-10-08 at 15 19 19](https://cloud.githubusercontent.com/assets/681190/10363106/1bd3fa32-6dd0-11e5-9a13-32a42a2e1954.png)

If you're using the raw mode, you'll need to manually enter the header value in the Headers tab.

**Comment by alaindresse** [comment]
Thanks for looking into this ?

How do you insert the body for your call ?

Alain

**Comment by alaindresse** [comment]
Hi,

some more info in the  screenshots below.

Best regards,
Alain

**Comment by abhijitkane** [comment]
@alaindresse Are you still facing the issue? Can you try sending a GET request to http://echo.getpostman.com/get with your header, and see if it appears in the response?
