### ISSUE TITLE
Issue with importing postman collections

### ISSUE THREAD

**Issue by xudongzhang** [a85/POSTMan-Chrome-Extension#1489]
While importing postman collections, there seems to be an upper limit on the size of the rawModeData. We have a test case where the rawModeData is a 3000+ lines of JSON string. After importing, the raw tab of the body is blank, whereas for smaller collections, import works as expected and the raw tab is able to show the data. Is this a known issue? Can the development team take a look into this and fix it? I suppose this would be a simple fix. However this can be annoying for large APIs with large data. Thanks.

**Comment by abhijitkane** [comment]
Can you check if there are any errors in the console when you import - http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/?

Also, what version of Postman are you using?

**Comment by xudongzhang** [comment]
I checked and didn't see any error in the console, and I'm using the latest version of postman.

**Comment by xudongzhang** [comment]
It turns out it's not a problem with postman. Closing...
