### ISSUE TITLE
Postman causing 301 redirect which is losing POST data

### ISSUE THREAD

**Issue by scottminter** [a85/POSTMan-Chrome-Extension#1490]
I'm creating a very simple endpoint that sends 3 values as POST data to my localhost.  Only with Postman am I getting a 301 redirect, which is causing my data to be lost.  I'm not having this same issue when I send it through a generic HTML form that I created.  I'm also not seeing a redirect when I go to the URL directly.  Currently on the PHP side all I'm doing is a "print_r($_POST)" and it's empty.  If I send the same data as a GET request it works.  Any suggestions on what is causing the redirect with Postman?  I've seen this question a few times and none of the suggested answers work for me.  I'm using XAMPP on a Mac for deving.  I've included a screen shot of my Postman request. 

Edit: I know this version of the form is only sending 1 value.  After continued failed attempts I changed it down to just one and I simplified my PHP to just "print_r($_POST)".  So my PHP script isn't doing any checks for the 3 values. 

![screen shot 2015-10-08 at 7 49 44 am](https://cloud.githubusercontent.com/assets/5587698/10365423/32b709e0-6d91-11e5-9b5b-af2cb2e98783.png)

**Comment by a85** [comment]
@scottminter Can you try this with Postman 3.0+ available at getpostman.com?

**Comment by scottminter** [comment]
I messed around with it more this morning.  It's possible there's a setting wrong in my XAMPP set up.  But I'm not sure why I can submit to it using an HTML form but not through Postman.  I downloaded and tried using Postman 3.0+ and still am having the same issue.  I'm attaching screen shots of my Postman settings and the code.  Any help is appreciated.  

EDIT: I also tried this as form-data and it still failed. 

![screen shot 2015-10-10 at 10 09 26 am](https://cloud.githubusercontent.com/assets/5587698/10411528/1a0133d8-6f37-11e5-871b-398f385153c0.png)

![screen shot 2015-10-10 at 10 10 22 am](https://cloud.githubusercontent.com/assets/5587698/10411533/2a5f6b8c-6f37-11e5-93de-ae4c31355d1e.png)

**Comment by abhijitkane** [comment]
@scottminter Can you check the Network tab in the DevTools window for Postman (http://blog.getpostman.com/2015/06/13/debugging-postman-requests/) and inspect the exact request that's sent?

You can also try installing and enabling the Interceptor in Postman (https://chrome.google.com/webstore/detail/postman-interceptor/aicmkgpgakddgnaphhhpliifpcfhicfo?hl=en, install using the satelite icon on the top navigation bar)

**Comment by scottminter** [comment]
I figured it out.  I needed to add a / to the end of my URL so it wouldn't redirect.  A 301 redirect will cause a loss of POST data.  So when I requested http://localhost/apiDev it would 301 to http://localhost/apiDev/ and lose all the POST data.  I appreciate your help.

**Comment by Steven-Mark-Ford** [comment]
I also experienced this. I used chrome dev tools to verify that on initial request the post parameters were sent out but then on the subsequent post following the redirect there were no post parameters

**Comment by sdnts** [comment]
@Steven-Mark-Ford According to the HTTP RFC spec, redirection with 301/302 status codes is supposed to be carried out using a GET request, which will cause loss of data.
You can read docs [here](https://www.getpostman.com/docs/handling_redirects). These should be helpful when handling redirects in Postman.

**Comment by shevyf** [comment]
Hi, just to follow up on this, the HTTP 1.1 RFC actually states that responding with a GET request is an error, and a holdover from HTTP 1.0:

```
   If the 301 status code is received in response to a request other
   than GET or HEAD, the user agent MUST NOT automatically redirect the
   request unless it can be confirmed by the user, since this might
   change the conditions under which the request was issued.

      Note: When automatically redirecting a POST request after
      receiving a 301 status code, some existing HTTP/1.0 user agents
      will erroneously change it into a GET request.
```

(from https://www.ietf.org/rfc/rfc2616.txt section 10.3.2)

**Comment by soluwalana** [comment]
I agree with shevyf, this issue should probably be resolved.

**Comment by abhijitkane** [comment]
@shevyf @soluwalana For the Chrome app, the only way to prevent auto-following redirects is to enable the Interceptor and toggle the 'Automatically follow redirects' setting in Postman.  The Chrome app uses the XHR object, which makes it impossible to control this behaviour without the Interceptor installed.

The native apps ([https:/www.getpostman.com/apps](https:/www.getpostman.com/apps)) support this without the Interceptor. However, this setting is agnostic of the request method - setting it to 'off' will prevent automatic redirects for all requests.

**Comment by abhijitkane** [comment]
Our native apps emulate the Chrome app, which always makes a GET call to follow a redirect, irrespective of the original request method.

We'll probably add a config for this once the Chrome app is deprecated.

**Comment by arcseldon** [comment]
As reported [here](https://github.com/postmanlabs/postman-app-support/issues/2722) the Chrome  postman extension on Mac does not work even with the interceptor enabled, and  automatically follow redirects toggled OFF.  :(    This has been a constant source of weakness with the offering.

**Comment by moongq** [comment]
In mycase, I send request with out "https://" so the nginx redirect and lose "post"
I appended "https://" to url and work fine now.

**Comment by Spartakovic** [comment]
why is this marked as closed? Like @shevyf pointed out, it's erroneous behaviour.

**Comment by aashishporwal1** [comment]
> I figured it out. I needed to add a / to the end of my URL so it wouldn't redirect. A 301 redirect will cause a loss of POST data. So when I requested http://localhost/apiDev it would 301 to http://localhost/apiDev/ and lose all the POST data. I appreciate your help.

Thanks , Worked for me too!!
 I was stuck on the same issue from 2 days!
