### ISSUE TITLE
Wrong Content-Type of file upload via form data?

### ISSUE THREAD

**Issue by fletchowns** [a85/POSTMan-Chrome-Extension#1491]
How come the Content-Type for my file upload is set to `application/vnd.ms-excel` ? Is there any way to change it?

```
POST /my/api/endpoint HTTP/1.1
Host: test.madeupdomain.com
Cookie: my_key=my_val
Cache-Control: no-cache
Postman-Token: e7c17c22-e25e-1a8a-6193-26772bfa4c01
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

----WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="upload"; filename="test_file.csv"
Content-Type: application/vnd.ms-excel


----WebKitFormBoundary7MA4YWxkTrZu0gW
```

If I manually run the following cURL command it works fine, but I can't seem to get the equivalent to work in postman:

```
curl -v -X POST https://localhost/my/api/endpoint -H "Cookie: my_key=my_val" --form upload=@test_file.csv
```

**Comment by abhijitkane** [comment]
There isn't any way of specifying content-types for individual form fields yet. We're working on it, but don't have an ETA as of now.

**Comment by fletchowns** [comment]
Ok thanks! Appreciate the quick response @abhijitkane
