### ISSUE TITLE
posting form file doesn't work

### ISSUE THREAD

**Issue by liuqiyuan** [a85/POSTMan-Chrome-Extension#1492]
Plz see `print_r($_FILES);` results empty `Array()` as following

![screen shot 2015-10-08 at 3 07 09 pm](https://cloud.githubusercontent.com/assets/3155179/10381304/7468e7cc-6dce-11e5-9aae-fbed67a1c0bb.png)

What's the problem here?

**Comment by abhijitkane** [comment]
Is the Interceptor on? There's an issue with file uploads through the Interceptor which we'll be fixing in the next release.

**Comment by liuqiyuan** [comment]
Yes, the interceptor was on. What's ETA for this fix?

**Comment by abhijitkane** [comment]
@liuqiyuan We hope to have the new release out by Monday.

**Comment by abhijitkane** [comment]
@liuqiyuan Can you check with version 3.0.24? Form posts for files should work with the Interceptor.
