### ISSUE TITLE
[FEATURE]: Application RESET options in settings

### ISSUE THREAD

**Issue by invalidred** [a85/POSTMan-Chrome-Extension#1493]
It would be nice to have an application RESET option in setting. The reset can have 2 options
1) To wipe out all collections
2) To wipe out all environments
3) To wipe out all collections + environment
4) To wipe changes made to settings
5) To wipe out user settings + collections + environment (to make postman all new again)

**Comment by a85** [comment]
@invalidred Any reason why you need this? You can just uninstall and re-install Postman to reset everything.

**Comment by invalidred** [comment]
Sorry for the late reply @a85. You guys are doing some great work.

For every Rest API we maintain a different postman environments and collection in git. Sometimes switching between different API and collections means manually deleting the old collection and removing the old environment in postman which can be a bit time consuming. It would be nice to have this option through settings. A lot of different applications have reset options and it's something uses have come to expect in settings.

Your suggestion of re-installing postman is time consuming as well and not as elegant as having this options under re-set tab in settings.

**Comment by a85** [comment]
Late in replying this but after thinking a lot about this, we will implement this using the idea of Workspaces. Closing this request for now.
