### ISSUE TITLE
Postman sometimes automatically overwrites collection data

### ISSUE THREAD

**Issue by lnenad** [a85/POSTMan-Chrome-Extension#1494]
Often I would just use a preset request just for the url, and then I would change some of the data or method, sometimes use the same tab for a different request, and every once in a while postman just writes over the old request info and overwrites the data without me ever clicking on save.

**Comment by abhijitkane** [comment]
@lnenad What version of Postman are you running? You can see the version by going to the Settings dialog (top-right corner > Settings > About).

The latest version is 3.0.22.

**Comment by lnenad** [comment]
I am using the latest version.

**Comment by abhijitkane** [comment]
@lnenad Are you still seeing this in 3.2.13?

**Comment by lnenad** [comment]
Haven't seen it in a while tbh. Good job!
