### ISSUE TITLE
where is the public shared collections explorer?

### ISSUE THREAD

**Issue by andreinitescu** [a85/POSTMan-Chrome-Extension#1495]
I remember Postman had a way to explore public shared collections.
It can be very useful when you want to test out some APIs from popular services and someone already created a Postman collection for the service.
Is that still available?
Thanks!

**Comment by forksofpower** [comment]
+1

**Comment by wardhanster** [comment]
+1

**Comment by a85** [comment]
We have restarted work on this. Closing this as a duplicate of #720

**Comment by a85** [comment]
This is available as the Postman API Network in versions 5.5+
