### ISSUE TITLE
Unsaved changes indicator

### ISSUE THREAD

**Issue by jackie-ta-avalara** [a85/POSTMan-Chrome-Extension#1497]
Sometimes I've made changes and then click to another request without remembering to hit save. It would be great if the Save button changed color or had some other indicator so that we could easily tell if there are unsaved changes.

**Comment by abhijitkane** [comment]
@jackie-ta-avalara In the latest version of Postman (v3.0.24), you should see a red dot on the tab that indicates unsaved changes.

![screen shot 2015-10-12 at 22 20 13](https://cloud.githubusercontent.com/assets/681190/10433437/75e968f6-712f-11e5-963c-21419145091b.png)

**Comment by jackie-ta-avalara** [comment]
It looks like the latest on Chrome is 3.0.22, released 10/7/15. I will keep eye out for 3.0.24. Thanks.

**Comment by abhijitkane** [comment]
This was there is 3.0.22 as well. This will only work if your request is saved in a collection.

**Comment by jackie-ta-avalara** [comment]
I see it now. Thanks!
