### ISSUE TITLE
Customizable Content-Type header for JSON bodies

### ISSUE THREAD

**Issue by lontongcorp** [a85/POSTMan-Chrome-Extension#1498]
Postman doesn't send json body with custom header [POST] `Content-Type: application/vnd.api+json`

Spec here, http://jsonapi.org/format/#content-negotiation-clients

**Comment by abhijitkane** [comment]
After you enter the raw body, you can go to the Headers tab and change the 'Content-Type' header to a custom value, including application/vnd.api+json.

![screen shot 2015-10-13 at 12 15 20](https://cloud.githubusercontent.com/assets/681190/10447680/1e0a3276-71a4-11e5-96e9-fa901658a320.png)

**Comment by lontongcorp** [comment]
I tried it.
Sending json in raw body (from regular application/json) with header Content-Type application/vnd.api+json but my server doesn't receive the sent json object as if sending the json with default content-type application/json.

**Comment by abhijitkane** [comment]
Check http://blog.getpostman.com/2015/06/13/debugging-postman-requests/ for steps to view the actual data that Postman is sending. If you send a request with raw data, it should appear in the 'Request payload' section of your request. If the server is not reading the data correctly, you'll need to make a change on the server.

**Comment by lontongcorp** [comment]
Cool, will check deeper too later.

With header application/json, can read posted json, so I think it's working fine. 
Can you also check the differences when you post between those 2 content-type header (with same raw body)?

**Comment by MrSkinny** [comment]
Hi, I'm able to send POST requests with the correct `Content-Type: 'application/vnd.api+json'` set but then the `body` input area reverts back to 'text' and I don't benefit from the JSON linting.  Is there a way to prevent the linter from disabling when you no longer use `application/json` as the Content-Type?

**Comment by pjwerneck** [comment]
Postman is enforcing the value in the Content-Type header according to the language used in the editor. For instance, if I set `Content-Type: application/json-patch+json`, the editor switches to `Text`. If I switch the editor to JSON, Postman sets `Content-Type: application/json`.

I even opened the "Settings" menu for the first time ever, expecting to find something to disable that.

**Comment by jeremytm** [comment]
Are there any plans to add this? Seems it's been open for quite some time.

Could you not either support JSON API official spec, or allow us to add custom content types along with a format for linting?

**Comment by danherd** [comment]
I'm building my first JSON API compliant API and simply cannot believe I can't view pretty-printed responses in Postman if they have the correct JSON API header.

Does this mean I'm going to have to return `application/json` while testing, before reverting to `application/vnd.api+json` when I finally release it?

**Comment by ErnestoIslas** [comment]
It is a `must have`!

**Comment by alohaninja** [comment]
this is definitely a requirement for us - I hope to see this feature done soon, can't be too difficult to implement. 

Supposedly the [desktop postman app used to work](https://chocolatey.org/packages/postman), but I couldn't get it to use a custom content type (e.g. [you must download the standalone postman app as the chrome extension does not fully support this feature yet](https://github.com/postmanlabs/postman-app-support/issues/1221)) 

Neither the chrome extension or desktop app appears to support custom content types @ this point.

**Comment by arashidkargo** [comment]
can anyone tell why I am seeing this error when running postman collection AssertionFailure  Content-Type is application/json at assertion:4

**Comment by PrimeTimeTran** [comment]
I'm getting this error on the stand along app Postman 5.5

**Comment by officer-rosmarino** [comment]
Any updates on this? I am not able to send requests with `application/vnd.api+json`.. Maybe I am missing something?

**Comment by ZooDoo4U** [comment]
So it appears there is still no option for users to have custom media types.  Sure seems there needs to be a way to registers one's own types, kind of bad when postman one's desired content type by setting the message body to "text"...

**Comment by rtablada** [comment]
When setting Content-Type and Accept to `application/vnd.api+json` you can send JSON::API formatted requests, but you do lose formatting.

I would +1 being able to define custom mappings for formatters that wasn't coupled to the headers and even being able to register your own custom `Content-Type`s for quick typeahead would be REALLY helpful and save from some typos.

**Comment by lukepuplett** [comment]
Not sure what the deal is here. So long as I enter the body in the editor, then switch to the headers and set the Content-Type to custom media-type, then it seems to work.

**Comment by rtablada** [comment]
@lukepuplett yes you can go to body and it works but the drop down overrides headers and vice Versa meaning if you have custom media types as used for jsonapi.org or GraphQL you lose either syntax highlighting or your custom content type header. You can go back and forth switching between syntax highlighting and then going back to reset your content type but this adds a lot of time for every change.

**Comment by hellboy81** [comment]
Is there possible to enforce using own `Content-Type` and `Accept Charset` borrowed from `produces` and `consumes` OpenAPI spec for all requests ?

At the moment setting body type to `raw` with `JSON` overrides my own `Content-Type` and `Accept Charset` custom headers.

- Is there possible to define or override own raw types?
- Is there possible to enforece using header from `Headers` tab?

**Comment by saswatds** [comment]
Hi everyone, 
Starting app version 7.7, we automatically detect Content-Type headers like `application/*+json` as language JSON and add proper syntax highlighting. The tight coupling between language and headers have now been reduced. 

Do test it out. Your feedbacks are valuable to us. 

Thanks.

**Comment by rtablada** [comment]
@saswatds thanks for adding the feature to support +json for this, it does solve some problems.

But, I think this feature request still stands. It would be nice if the coupling between body syntax highlighting and content type header were decoupled all together (or maybe a UI to sync them or a way to opt out of this sync).

It seems like a weird side-effect that going to body and using the dropdown changes your headers (without any indication to the user). This may be a useful behavior when a user hasn't set a content-type header however for other usecases it is awkward. Maybe instead of auto setting it showing an alert or some indication to the user that the syntax highlighting and content-type are mismatched.

**Comment by saswatds** [comment]
@rtablada we completely agree with you. 
In the upcoming version of the app we are going to completely decouple the language and content-type header selection. 
We have also added the warning of inconsistency in the current version. 
<img width="439" alt="Screenshot 2019-09-21 at 12 51 18 AM" src="https://user-images.githubusercontent.com/8796447/65353122-f5502f00-dc09-11e9-8beb-4f8adda7bb79.png">
In this particular selection the Content-type was `application/xml` but language selected was `Javascript`.
<img width="254" alt="Screenshot 2019-09-21 at 12 52 43 AM" src="https://user-images.githubusercontent.com/8796447/65353190-26306400-dc0a-11e9-955e-33b1791b4d3e.png">
Also as you can see we have already decoupled headers from the language selections. Just few last mile changes before we completely stop adding any header on language selection.

**Comment by saswatds** [comment]
Hi everyone, a quick update here. In the latest version of the app the language selection and header have been decoupled. The app no longer adds any headers on language selection. Any custom content-type header you add will be respected and if no header is provided then while sending the request a suitable header will be selected for you based on the language. This feature should work as it's supposed to. 

I will be closing this issue now. Feel free to open a new issue if you encounter any problems with this.
