### ISSUE TITLE
Moving the folder from one collection to other...

### ISSUE THREAD

**Issue by prabhukirannarava** [a85/POSTMan-Chrome-Extension#1499]
Hi,

I have multiple collections in my post man account. Each collections has multiple folder with in it.
I am not able to move one folder from one collection to other.
Post man is allowing me to move only one of the step from one collection at a time.
As I have 100s of steps with in same folder it is of more manual work for me to move.
Can you please let me know if there is a short cut ?

**Comment by abhijitkane** [comment]
@prabhukirannarava We're working on a way to transfer folders across collections, but don't have an ETA yet. For now, you'll need to manually move the requests.

**Comment by numaanashraf** [comment]
@prabhukirannarava We've added folder transfer along with a whole host of new features in Postman 4.0

**Comment by jaguth** [comment]
I'm on postman 4.3.0 and i do not see a folder transfer feature.  that feature is not in the current documentation.  was that feature scrapped?

**Comment by abhijitkane** [comment]
@jaguth You can simply drag a folder from one collection to another.

**Comment by jaguth** [comment]
Ah, I see, it has to be a folder **within** a collection (top level folder).  That works for me.  I was trying to move a collection (top level folder) into another collection (top level folder).  Thank you @abhijitkane!

**Comment by JDFagan** [comment]
Seems like one cannot move a top level folder into another top level folder (to make it a subfolder) or even to a subfolder of top level folder (a subfolder of a subfolder).  Would be useful to treat top level folders the same as subfolders from perspective of being able to re-organize..

**Comment by lovelock** [comment]
@JDFagan It's not good to treat them differently

**Comment by JDFagan** [comment]
@lovelock agreed and that was my point I was trying to make (to treat them equally)

**Comment by pilak** [comment]
Hi,
yes should move top folder into top folder and make it subfolder... 
Think about import too if possible
Thank you for the great job :)

**Comment by nagendraprabhu01** [comment]
Hi,
Need the functionality to move entire collection into some other collection.
That would be very helpful.

**Comment by madonahoch** [comment]
That would be very helpful!

**Comment by jen-ren** [comment]
Agreed. We need this!

**Comment by velchev** [comment]
Much needed feature!

**Comment by aviranhanan** [comment]
This feature will change my life!!

**Comment by iaubain** [comment]
I am on PostMan 7.0.7, but this feature of moving top level collection into another top level collection(folder) is still missing and personally I have a lot of collections that I would want to group into one.
Kindly add this feature

**Comment by NaveenBellary** [comment]
I ended up creating a new workspace altogether and that addressed my requirement. 
However, allowing top level folders to be treated the same way as any other sub folder would help a lot!
