### ISSUE TITLE
Httpie

### ISSUE THREAD

**Issue by sbutalia** [a85/POSTMan-Chrome-Extension#1500]
https://github.com/jkbrzt/httpie

Would be cool to get a code generated for Httpie :)

**Comment by tstatler** [comment]
Isn't this already available? e.g.
![screen shot 2015-10-16 at 11 07 29 am](https://cloud.githubusercontent.com/assets/408952/10549478/1e7e7c86-73f6-11e5-9190-8b56e4d93c76.png)

**Comment by abhijitkane** [comment]
@tstatler You're right, slipped my mind. 
@sbutalia Is this what you're looking for?
