### ISSUE TITLE
Body as default tab

### ISSUE THREAD

**Issue by chimit** [a85/POSTMan-Chrome-Extension#1501]
Most of my requests have Body parameters. It's the main part of any request for me. But if I switch to any GET request which doesn't have Body parameters, Authorization tab opens. It's OK, but after that I click on another POST request and see the same - Authorization tab, and every time I have to switch to Body tab. It's very annoying. Please, can you make Body the default tab? Or may be when switch to GET entry do not automatically switch to Authorization tab, but show empty Body tab?

**Comment by alahosky** [comment]
Certainly when POST'ing using Collections, the main (only?) thing you're generally changing is the Body of the post. Config stuff like Authorization, Headers, etc. almost never change for me.

So definitely agree that Body should be the default tab!

**Comment by bhawna2109** [comment]
Hey guys, we're tracking this here - #2086 
Closing this as duplicate.
