### ISSUE TITLE
Unable to open Postman after crash

### ISSUE THREAD

**Issue by chantelope** [a85/POSTMan-Chrome-Extension#1502]
I have run into the problem a few times where I am updating and running a test in Postman, it crashes and then I cannot recover the changes. I usually get around this by reinstalling the application and reworking my changes. Are the local changes stored anywhere?

The only error I can seem to find is in the event viewer:

Faulting application name: chrome.exe, version: 44.0.2403.155, time stamp: 0x55c52663
Faulting module name: chrome.dll, version: 44.0.2403.155, time stamp: 0x55c52136
Exception code: 0x80000003
Fault offset: 0x00542692
Faulting process id: 0x12f0
Faulting application start time: 0x01d10597923f0427
Faulting application path: C:\Program Files (x86)\Google\Chrome\Application\chrome.exe
Faulting module path: C:\Program Files (x86)\Google\Chrome\Application\44.0.2403.155\chrome.dll
Report Id: 08ea485e-718b-11e5-af93-f8b156cc4799

**Comment by abhijitkane** [comment]
After the crash, do the changes not show up when you reload the app (not reinstall)? Do you have the request saved in a collection?

You can check chrome://indexeddb-internals and search for fhbjgbiflinjbdggehcddcbncdddomop to check the files that are used to store Postman's local database.
