### ISSUE TITLE
Clicking on Chrome Takes Me to Postman (Mac)

### ISSUE THREAD

**Issue by ghost** [a85/POSTMan-Chrome-Extension#1503]
On Mac, clicking on Chrome icon on the launcher takes me to Postman when I have both apps running.

**Comment by abhijitkane** [comment]
This seems to be Chrome-level behavior. You'll need to use Cmd + ~ to switch between Chrome and Postman windows.

**Comment by a85** [comment]
We have the Mac app now in beta for getting rid of these issues. You can get it from here. https://www.getpostman.com/apps
