### ISSUE TITLE
"Could not get any response" from servers with SSL issues

### ISSUE THREAD

**Issue by BenSeverson** [a85/POSTMan-Chrome-Extension#1504]
If you send a request to a server that Chrome has an SSL issue with (like hostname not matched to cert), you get the "Could not get any response". This can be worked around by navigating to that URL in a normal Chrome tab and accepting the security risk. Is there anything that can be done from postman to enable the security override from within Postman or at least surface an error that indicates an SSL issue?

AFAIK, there isn't any way to add a permanent security exception in Chrome for some SSL issues like host mismatch. Overriding the security exception only seems to last for the browser session.

repro: GET https://216.58.216.164 (www.google.com but cert does not match direct IP)

**Comment by thirstyfish** [comment]
+1
I have the same issue with my self-signed cert on my dev server.

My SSL cert is generated with the following FQDN to cover subdomains:
*.example.com/CN=example.com

Postman was working happily after I followed this blog post:
http://blog.getpostman.com/2014/01/28/using-self-signed-certificates-with-postman/
but after a few days I had to do the manual override in Chrome to get it working in Postman again.

**Comment by a85** [comment]
SSL certificate settings can now be overridden in the Mac app. Windows/Linux apps coming soon.
