### ISSUE TITLE
Sending the Url Parameters with space in new Postmanis not working properly

### ISSUE THREAD

**Issue by arru507** [a85/POSTMan-Chrome-Extension#1505]
I have sent a URL parameter like ' 270'(space 270) but it takes the trimmed one as only '270' and sending it to API.
In the old postman it is taking correctly.

**Comment by abhijitkane** [comment]
Use %20270 to encode your param with a space. Alternatively, select the space in the URL box, right click > Encode URI Component.

**Comment by arru507** [comment]
But I have stored the data with space in database and I want to retrieve only that record, that is not possible with the '%'.

**Comment by abhijitkane** [comment]
A URL param with `%20` should be interpreted as a space by your server. Feel free to re-open if you still face issues.
