### ISSUE TITLE
POSTman not working

### ISSUE THREAD

**Issue by EasyAsABC123** [a85/POSTMan-Chrome-Extension#1506]
Clicking Send on any HTTP request type does nothing...

I have tried #579 but although the symptoms are the same the fix did nothing, any help would be appreciated.

**Comment by abhijitkane** [comment]
What version of Postman are you using / is the Interceptor enabled?
You can also check the console (http://blog.getpostman.com/2015/06/13/debugging-postman-requests/) for any errors that appear when you click send.

**Comment by EasyAsABC123** [comment]
Interceptor is enabled and installed,
however, I have the request builder completely setup as I did with PostMan v2 (worked fine) but in latest clicking send does nothing.

Using developer tools  found here http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/

I learned that on clicking Send no network traffic is sent

**Comment by abhijitkane** [comment]
Can you try disabling the Interceptor and checking? If it's enabled, requests won't show up in the Networks tab.

**Comment by EasyAsABC123** [comment]
Disabled no difference can't get postman to even send a request of any kind get, post, put

Justin Schuhmann

**Comment by abhijitkane** [comment]
Any errors in the DevTools console when you click Send?

**Comment by EasyAsABC123** [comment]
Interceptor is enabled and installed,
however, I have the request builder completely setup as I did with PostMan v2 (worked fine) but in latest clicking send does nothing.

On closing the window
background.js:23 On closing the window

**Comment by EasyAsABC123** [comment]
This is working fine on other computers just not my work laptop...i'll attempt to remove and readd

**Comment by EasyAsABC123** [comment]
Solution:
chrome://extensions
-> remove postman
install postman 3.x.x.x

Works!

thanks
