### ISSUE TITLE
Feature Request: OAuth 2.0 helper automatically copies token to environment variable

### ISSUE THREAD

**Issue by ronaldsalas** [a85/POSTMan-Chrome-Extension#1507]
I've been sharing my Postman collection to others to demo our API and how OAuth 2.0 works (which we use in our API). I use the OAuth 2.0 helper to get our OAuth2 access_token and refresh_token, but I still have to copy-paste the values to my environment variables (which I named access_token and refresh_token). I added these to my request to 1) demo where to put the access_tokens and 2) as I can't share the OAuth2.0 settings like authorization and token url in the helper with my collection (as far as I know).

Since this is the case, I suggest there's an option where the OAuth2.0 helper will automatically copy and  pick up the resulting auth_token and refresh_token and save it to environment variables. For the initial implementation, I think I am fine with having a predetermined, fixed name of an environment variable i.e. if Postman finds an environment variable named 'auth_token' then copy-paste the value to it.

**Comment by nateritter** [comment]
+1 
Alternatively, I was hoping for an global environment auth procedure and/or collection auth procedure. For instance, either authenticate once for the environment I'm in, or else at least authenticate once for the collection I'm running.

I don't think any of this would be necessary if the OAuth 2.0 process included the usage of a `refresh_token` to regenerate a new `access_token`.  As it stands now, when running a collection, I have to run a call which gets a fresh `access_token` inside each sub-folder (so I can run sub-folders independently if I need to), or write a pre-request script for every call which checks the current `access_token` and gets a new one using a previously received `refresh_token`.

I'm open to suggestions on improving my process, but the simplest thing would be to simply use the given `refresh_token` if available in the helper, IMHO.

**Comment by gareth-a-jones** [comment]
+1 from me.  I'm trying to share the tokens among a large set of calls, and having to paste them into my environment is a pain.  Letting me run auth as part of the environment rather than as part of a call would remove a bunch of clicks every hour.  Adding an automatic refresh token cycle would really make this super productive and get me paying for pro.

**Comment by joshstella75** [comment]
+1
My use-case is similar to @ronaldsalas above.  We have recently moved from using a token based endpoint to using Identity Server 3 which is OAuth 2.0.  With the token endpoint, we were able to store the generated token in an environment variable.  

Currently there are options to _Add token to_ both the Header and the URL.  A 3rd option to copy the _access_token_ and _token_type_ to environment variables would allow us to maintain a similar workflow for our team.  Appending the token to the Header works, but potentially pollutes the headers of our collection with expired tokens.

**Comment by sdnts** [comment]
I'm not sure if adding this to your environment automatically is a good idea.
We are looking at Authentication in our next release though, and we'll look into this :)

Maybe we need to streamline this process a little more. Thoughts @bhawna2109 @a85 ?

**Comment by JDunn3** [comment]
+1
Right now I have a collection feeding off of a data file to iterate, and it runs my oauth request every time and stores in an environment variable. Would be great to be able to automatically handle refreshing the token without having to write it myself in a pre-request script for every request.

**Comment by dmasur** [comment]
+1 we have issues to. Our Dev Team works develop on there own machines and need a token for every machine. Better way would be: store login creds and try to get a new token, if a respond indicates an invalid token. (I think Insomnia does this already)

**Comment by vvs11** [comment]
@ronaldsalas @nateritter @garethj-msft @joshstella75 @JDunn3 @dmasur Could you refer to #9056 and check if the solution meets your requirements? We have pushed the changes to out Canary build for you to try

**Comment by giridharvc7** [comment]
We will not be adding a feature that automatically copies access token, refresh token etc to environment as this is a bad security practise. Instead, please look into #9056, we believe this can solve your problem.
