### ISSUE TITLE
Feature request: Viewing Request body

### ISSUE THREAD

**Issue by elado** [a85/POSTMan-Chrome-Extension#1509]
One thing I’m really missing is to see the content of the request sent.
I use plenty of variables and pre-request scripts that compute variables, and I can’t really see what’s being sent.

As a start, “Copy request to clipboard” (with both headers and body) can be extremely useful.

**Comment by ironicnet** [comment]
I was in the same situation than you, then i saw that there is a "Generate code snippet" option, which gives you the request body (and headers) in plain text

**Comment by Nuru** [comment]
@ironicnet Still, it would be nice to be able to see the actual request sent in a tab along with the response.

**Comment by nrogoff** [comment]
+1

**Comment by jimonthebarn** [comment]
+1

**Comment by a85** [comment]
This is available through the Postman Console now. View > Postman Console in the header menu.
