### ISSUE TITLE
Re-send a request

### ISSUE THREAD

**Issue by RyanW89** [a85/POSTMan-Chrome-Extension#1512]
Hello,

Is there a way to resend a request? My situation is i need to send a request, only once a process back end has finished. I send a status request which returns either In progress or Complete. When complete i want to move on. I have written a test using a global variable So it runs the test, if its in progress adds 1 to the global variable, then i want it to re-run the request. There is then a break if it goes over 10 (With a wait before it send the new request) Anyone know how I can do this?

The only way I can think of is 10 requests, which is messy

**Comment by abhijitkane** [comment]
@RyanW89 Not as of now. We're working on a way to control the request flow which should make this use-case trivial, but can't offer an ETA yet.

You could check out newman (http://npmjs.org/package/newman). Newman can return an exit code of 1 for a failed test, and you can write a small script that continues running your collection till the exit code is 0.

**Comment by a85** [comment]
You can use the postman.setNextRequest function for this now. Details here: http://blog.getpostman.com/2016/03/23/conditional-workflows-in-postman/
