### ISSUE TITLE
[Feature]: Collection-Specific Environments

### ISSUE THREAD

**Issue by mryhmln-ca** [a85/POSTMan-Chrome-Extension#1513]
I typically have completely different environments for each of my collections. For me, it would be nice to have the ability to associate environments with collections as opposed to requiring them all to be global.

**Comment by hlubovac** [comment]
+1
I hate polluting my global env. variables with something that is specific to a collection. I have repetitive long url parts and request header values that I constantly copy-paste-maintain because of this. Thanks.

**Comment by a85** [comment]
Tracking as part of the "Workspaces" feature. #3205
