### ISSUE TITLE
Order of collection folders when exporting

### ISSUE THREAD

**Issue by esbenboye** [a85/POSTMan-Chrome-Extension#1514]
When making `collection-folders` in Postman, the folders are ordered from A to Z, but when exporting them from Postman, they are ordered by creation time. 

E.g. when creating a folder called `Sample-02`, `Sample-03` and `Sample-01` (in that order), Postman will list them correctly as Sample-01, Sample-02 and Sample-03, whereas the exported file will order them `Sample-02`, `Sample-03` and `Sample-01`. This is causing some problems when running the file through Newman and is quite a problem, when you have environment variables that are set in `Sample-01` and used in `Sample-03`. 

The problem can be reproduced by following the mentioned steps in my example and downloading the folder from Postman. When looking at the `.postman_collection` file, the folders are in incorrect order (that is, ordered by creation).  

I've been looking through some issues (only found some issues regarding import, not export) here and searching Google, but with no luck on how to fix this, except to manually editing the `.postman_collection` file, which isn't a viable solution. 

I am running Newman version 1.2.22 and Postman is the newest I could get from Chrome App Store. 

Sample of exported file (I cannot attach it):

``` json
{
    "id": "f89df01b-d1ff-37a0-e086-2ce10c73d7c3",
    "name": "error-test",
    "description": "",
    "order": [],
    "folders": [
        {
            "id": "2c1a2403-576c-2250-b66d-3a4660440540",
            "name": "sample-02",
            "description": "",
            "order": [],
            "owner": "136231"
        },
        {
            "id": "0a062ce8-be72-0d56-7359-e9e957d95598",
            "name": "sample-03",
            "description": "",
            "order": [],
            "owner": "136231"
        },
        {
            "id": "60b27a19-6758-9967-30b0-35d4267dc685",
            "name": "sample-01",
            "description": "",
            "order": []
        }
    ],
    "timestamp": 1445253236868,
    "owner": "136231",
    "remoteLink": "",
    "public": false,
    "requests": []
}
```

I really think that the shown order and the downloaded order should be same, to fix issues with Newman.

**Comment by KumG** [comment]
I have the same problem. Also, it would be very nice to be able to edit the order of the subfolders the same way we can reorder the requests inside a folder. Is it planned ?

**Comment by anton-johansson** [comment]
I have another problem, related to the ordering of the collections of the exported data.
- I export my data
- I commit it in my version control
- I clear all my collections
- I import all my data
- I make some small to a request changes
- I export my data again, to the same file

There are now loads of modifications (not just the small changes I made). @esbenboye mentioned it being sorted by creation time, and that might be the case. I guess the creation time is completely random when importing.

**Comment by abhijitkane** [comment]
@anton-johansson We're working on introducing a new collection format very soon. These issues should  soon be sorted out.

**Comment by OscarGarciaPeinado** [comment]
I have the same problem with the export order... we are awaiting for the new update =)

**Comment by abhijitkane** [comment]
@OscarGarciaPeinado @esbenboye The latest version of the app exports the folders in alphabetical order as well (same as the running order)
@KumG manually ordering folders is still some time away.
