### ISSUE TITLE
No. of requests in a Collection

### ISSUE THREAD

**Issue by Mahesh49** [a85/POSTMan-Chrome-Extension#1515]
Hi, 
1. Is there any restrictions on number requests that I can add to a collection before upload it to Postman?
It seems like the collection stopped updating once it reaches 50 requests. 
1. Each request has any size limit? 
   In few requests I send Base64 image data, and it is around 1mb, when I am trying to upload it to Postman, I get error message saying 413 request entity too large (inspected using console). 

Appreciated for any help. 

Thanks.

**Comment by a85** [comment]
Nope. No limits.
