### ISSUE TITLE
Bug when making a request with <svg> tag present

### ISSUE THREAD

**Issue by JustinSarwer** [a85/POSTMan-Chrome-Extension#1517]
Hello,

I would just like to report an odd bug when typing in a request with a <svg> tag in the URL.

As soon as I type in a complete <svg> tag, the client seems to have a display bug, which I will display below.

![svg_issue](https://cloud.githubusercontent.com/assets/12139080/10620139/6aba4c5c-7747-11e5-81e4-f1d78545e90e.png)

As you can see, the tab icon inflates and gets messed up. Also the URI bar is now un-selectable. 

I tried it with other XML tags, but SVG seems to be the only one to cause this issue.

Small but odd issue. Is it because postman uses SVG?

Thanks,
Justin

**Comment by abhijitkane** [comment]
Thanks for reporting this Justin. This is because we put the value from the URL bar directly into the tab name, so it renders as `<svg>`. We'll fix this in the next release.

**Comment by abhijitkane** [comment]
@JustinSarwer This has been fixed in the latest version of the app - v3.2.8.
