### ISSUE TITLE
Add tooltip for environment variables

### ISSUE THREAD

**Issue by wimdeblauwe** [a85/POSTMan-Chrome-Extension#1518]
It would be great to have a tooltip if you hover over an environment variable either in the URL or in the request body so you can see the actual value that is going to be used in the current environment.

**Comment by felipeplets** [comment]
To highlight the variables with a different background color would also be good, to easily find dynamic values in the editor.

**Comment by scwood** [comment]
I second highlighting the environment variables with a different font color or background color, would help create some visual reassurance.

**Comment by bhawna2109** [comment]
Hey guys, we have an exciting update for you- postman now supports variable highlighting, along with autocomplete and tooltips for variables! It's out on our canary channel, and will hit our stable builds in March.

Latest Canary builds are available here-
OSX: https://dl.pstmn.io/download/channel/canary/osx_64
Windows 32-bit: https://dl.pstmn.io/download/channel/canary/windows_32
Windows 64-bit: https://dl.pstmn.io/download/channel/canary/windows_64
Linux 32-bit: https://dl.pstmn.io/download/channel/canary/linux_32
Linux 64-bit: https://dl.pstmn.io/download/channel/canary/linux_64
Chrome: https://chrome.google.com/webstore/detail/loddepljkabcghihdkbkfknabkinanff/

1. Variable highlighting and tooltip on hover
Variables are highlighted in orange, with unresolved variables shown in red colour. Hovering over a variable shows its current value and the scope. If a variable is unresolved i.e. it does not have a value in the current environment, the tooltip shows the appropriate feedback.
![2 tooltip](https://cloud.githubusercontent.com/assets/14976346/23355675/e4761058-fcfc-11e6-9f9f-039bb1bfbad9.gif)


2. Autocomplete for variables
Type an open curly bracket to bring up the autocomplete menu. For the pre-request scripts and tests section, which uses the ace-editor, entering the first letter of a variable triggers the autocomplete. The menu contains a list of all the variables in the current environment followed by globals. Oh, and there’s more! Navigating through the list also shows the current value and scope for each variable, along with a feedback for overridden variables. 
![1 autocomplete](https://cloud.githubusercontent.com/assets/14976346/23355681/ebdf7b18-fcfc-11e6-896d-384284f375de.gif)



Additionally, we’re introducing a new - and more powerful - data editor in Postman! This new editor is an enhancement to the key-value editor and lets you view and manipulate data in a faster, more effective and elegant manner.
![new data editor](https://cloud.githubusercontent.com/assets/14976346/23355994/367338d0-fcfe-11e6-8f64-8486c7180aa4.gif)

Go ahead, download and let us know what you think.
