### ISSUE TITLE
Postman not launching after resetting chrome flags

### ISSUE THREAD

**Issue by nlvraghavendra** [a85/POSTMan-Chrome-Extension#1519]
Hi,

I've reset all the flags in Chrome and I'm still not able to launch Postman. My chrome version is 34.0.1847.131.

I also tried renaming Chrome's User Data folder and starting afresh. Still the postman is not even launching. Any idea?

**Comment by abhijitkane** [comment]
Can you try updating Chrome to the latest version?

**Comment by nlvraghavendra** [comment]
I can't since it is disabled by our network administrators. Unfortunately I'm stuck in this version and I was using POSTMAN a lot.

**Comment by abhijitkane** [comment]
Was it working for you earlier? Can you try reinstalling Postman? (This will clear any data that you had saved in Postman)

**Comment by nlvraghavendra** [comment]
It was working earlier. But I believe I got recently updated to this version of Chrome. I tried re-installing it numerous times with no luck.

**Comment by abhijitkane** [comment]
Hm..there are hundreds of users on all the recent versions of Chrome. We'll try and reproduce the problem on Chrome 34 and get back to you.
