### ISSUE TITLE
Using Tests how can I compare JSON response to previously saved JSON response from same request?

### ISSUE THREAD

**Issue by akapoor47** [a85/POSTMan-Chrome-Extension#1520]
Please label this as a question
@abhijitkane

**Comment by N0rimaki** [comment]
hows about building hash for every response and compate it or would you need the differences?

**Comment by akapoor47** [comment]
@N0rimaki - Thanks for your reply. 
Yes if there are differences I would like to see them in a separate diff file or somewhat in user friendly way.

**Comment by kanika9190** [comment]
Hi, 
i am facing the same issue, can somebody help on this.

**Comment by abhijitkane** [comment]
@akapoor47 @kanika9190 This isn't supported yet. We've added this to our roadmap, and will take it up for internal discussion soon.

**Comment by Innovolutions-LLC** [comment]
Is there any update on this ask?

**Comment by abhijitkane** [comment]
A response diff view isn't on our roadmap as of now. As a workaround, you can save the previous response to the environment with postman.setEnvironmentVariable(), and compare each response to the previously stored response.
