### ISSUE TITLE
Copy all headers (with values) into newly opened window

### ISSUE THREAD

**Issue by vicmosin** [a85/POSTMan-Chrome-Extension#1521]
Once you click some link within response (at pretty view), a new tab being opened. I think it would be nice to copy all the header's values from original window to a new new one, since in most of the cases (especially within json/hal response) the new request will require the same headers.

**Comment by abhijitkane** [comment]
There's a setting for this - "Retain headers on clicking on links". Check the Settings Modal (wrench icon in the top-right).

**Comment by vicmosin** [comment]
Thanks! You guys are awesome
