### ISSUE TITLE
Maintain file structure through export - import cycle

### ISSUE THREAD

**Issue by schmidlop** [a85/POSTMan-Chrome-Extension#1524]
We are sharing a collection across our development team and every time some one adds a new request and exports the file the new commit has substantially more differences than just the addition of a new request. This makes it impossible (in source control) to see what was added.

I could manage if just the request ids changed but the entire order of the request array changing is a real pain.

**Comment by a85** [comment]
We are working on a new collection format that should solve this. You can also check out our new collaboration service available for Postman account holders.

**Comment by ngleav** [comment]
Any update on this?

**Comment by dorian-marchal** [comment]
Any update on this ?

**Comment by a85** [comment]
@shamasis Can this be closed now?

**Comment by shamasis** [comment]
Yes. Closing it. Now in v2 format, only the changes get updated and uses positional notation similar to any code editor or other file system representations.
