### ISSUE TITLE
Global variables do not resolve in Collection runner

### ISSUE THREAD

**Issue by thirstyfish** [a85/POSTMan-Chrome-Extension#1527]
Hi there,

I use a set of environment variables as well as global variables in my requests.
When I execute the request from the builder, both the global and env variables are resolved correctly.

However, when I start a test run in the collection runner using the same set of requests, only the env variables are resolved correctly, the global variables are sent to the server unresolved (e.g. {{ADMIN_EMAIL}}  ).

I'm selecting the environment and the folder before starting the runner.
Am I missing something, or is this a bug?

Cheers

Version 3.0.25 (packaged)
OS: mac
Architecture: x86-64
Native client architecture: x86-64

**Comment by thirstyfish** [comment]
Having done a bit more testing it seems that the env variable that resolves in the runner is in the address ( {{url}} )
If I remove the global variables in the request body and replace them with env variables, then those won't resolve either when run from the collection runner.

When I'm using url params instead of body params (form-data), both the globals and the env variables resolve OK. So the real issue is with resolving body params in the collection runner.

**Comment by abhijitkane** [comment]
@thirstyfish Are the variables resolved correctly for the "values" in the form-data? We were able to reproduce the problem with the keys - will push a fix in the next release.

**Comment by thirstyfish** [comment]
@abhijitkane: Thanks for looking into it.
I haven't tried using variables as keys, I was trying to use the variables as values in the form-data.
So no, variables used as values in form-data in the runner don't resolve for me.

**Comment by abhijitkane** [comment]
@thirstyfish Is the Interceptor enabled?

**Comment by thirstyfish** [comment]
@abhijitkane Yep, it is

**Comment by thirstyfish** [comment]
@abhijitkane Just tested it, if I turn the Interceptor off, it works fine

**Comment by a85** [comment]
@abhijitkane Bug with the Interceptor?

**Comment by abhijitkane** [comment]
@thirstyfish Can you confirm this fixed in v3.1.1?

**Comment by thirstyfish** [comment]
@abhijitkane: yes, it works now. Thanks for the fix!
