### ISSUE TITLE
postman slow down my system

### ISSUE THREAD

**Issue by avtaniket** [a85/POSTMan-Chrome-Extension#1528]
Hello Geeks,

Whenever I start using postman, my system performance slow down. 

_Below is my system specification_

Version 3.0.25 (packaged)
OS: linux
Architecture: x86-64
Native client architecture: x86-64

**Comment by abhijitkane** [comment]
Do you notice this as soon as you start Postman, or does it only start when you send a request?

You can check Chrome's task manager (Window menu > Task manager) to see if Postman is consuming a lot of CPU.
