### ISSUE TITLE
HTTP:204

### ISSUE THREAD

**Issue by sibalas** [a85/POSTMan-Chrome-Extension#1529]
Hi,
Newman marks the test case status as failed for a valid 204 response.Let me know to over come the issue.

Thanks,
Siva

**Comment by abhijitkane** [comment]
You'll have to provide more details here. What's the test case that you have? If you're checking for a 200 code, a 204 code will naturally return a failure.

**Comment by sibalas** [comment]
Hi,
We are checking for 204 code in the response .Working as expected in Postman but while executing in Newman through command prompt it marking as failure.

Screenshot :  http://prntscr.com/8vu8s7

Thanks,
Siva

**Comment by abhijitkane** [comment]
The 'HPE_INVALID_CONSTANT' is a server error - http://stackoverflow.com/a/21482270/384155. You'll have to check the server logs to see if the payload is something that you don't expect.
