### ISSUE TITLE
Newman-Github

### ISSUE THREAD

**Issue by balaji2711** [a85/POSTMan-Chrome-Extension#1530]
Hi,
Can we bind Newman to TFS or GIT Continuous integration tool.
Thanks,
Balaji.

**Comment by abhijitkane** [comment]
Not sure what sort of integration you need - Newman doesn't offer any integration capabilities by itself.
You can use the `-s` flag to return an exit code of 1 if a test fails, and use this to interface with tools like Jenkins (http://blog.getpostman.com/2015/09/03/how-to-write-powerful-automated-api-tests-with-postman-newman-and-jenkins/).

We're looking for ways to integrate with other tools, but have no concrete timeline yet. Closing this as a non-actionable ticket.
