### ISSUE TITLE
Generate Random Int

### ISSUE THREAD

**Issue by chs8788** [a85/POSTMan-Chrome-Extension#1536]
Hi i am want generate a random value that i can use in my json.
for this is am storing this in a variable but it does not work
can you please let me know the correct way
postman.setGlobalVariable('random1',"{{$randomInt}}");

**Comment by abhijitkane** [comment]
`{{$randomInt}}` is already a variable. You don't need to create a new global variable.
Try sending a GET request to `http://dump.getpostman.com/get?num={{$randomInt}}` - the actual request will be sent with the variable replaced.

**Comment by chs8788** [comment]
Thanks Abhijit,
i would need to store this value of randomInt as i do not want to change this again and want to use it throughout the program

**Comment by pawanrawal** [comment]
Hi, `{{$randomInt}}` is not available in the sandbox as of now. 
You could use `postman.setGlobalVariable('random1', Math.floor(Math.random() * 1000));` , to set a random variable between 0(inclusive) and 1000.

**Comment by vfedorin** [comment]
Hi,
I'm using `{{$randomInt}}` to create a unique Project name.

```
var number = "{{$randomInt}}";
console.log(number);

var projectName = 'TestProject-' + number;
pm.environment.set("projectName", projectName);

var projectCode = 'TP' + pm.globals.get("testProjectNumber");
pm.environment.set("projectCode", projectCode);
```
"TestProject-316" is successfuly created on my portal.
However, I see the following in Test Results.
> PASS 200 OK. Project "TestProject-{{$randomInt}}" added.

How can I solve that? Thanks

**Comment by sivcan** [comment]
@vfedorin - The variables don't resolve in the test script.

However, you can replace your code with this and it'll work for your tests.

```
let number = parseInt(pm.request.url.path[0]); 

// If it's not at 0th position, just do 
// console.log(pm.request.url.path) and check for the position of the random variable.

console.log(number);

var projectName = 'TestProject-' + number;
pm.environment.set("projectName", projectName);

var projectCode = 'TP' + pm.globals.get("testProjectNumber");
pm.environment.set("projectCode", projectCode);
```

**Comment by vfedorin** [comment]
Thanks @sivcan. It turned out that solution in my case is `var number = Math.floor(Math.random() * 1000);` provided by @pawanrawal since I send POST request with parameters in body.

So,
Pre-request script is
```
var number = Math.floor(Math.random() * 1000);

var projectName = 'TestProject-' + number;
pm.environment.set("projectName", projectName);

var projectCode = 'TP' + number;
pm.environment.set("projectCode", projectCode);
```
and Body is
`{"name":"{{projectName}}","code":"{{projectCode}}","description":"Test Project"}`

Thanks guys!
