### ISSUE TITLE
Chrome app not launching on Windows 10

### ISSUE THREAD

**Issue by gokulm** [a85/POSTMan-Chrome-Extension#1538]
I recently upgraded my PC from Windows 8.1 to 10. Since then I'm unable to use Postman, it's launching (I can see it on the task bar), but when I click it nothing happens.

**Comment by abhijitkane** [comment]
Can you try upgrading Chrome / reinstalling Postman?

Reinstalling Postman will cause you to lose all your data, so if you didn't have Sync enabled, try to locate the files listed under "fhbjgbiflinjbdggehcddcbncdddomop" at chrome:/extensions and archive them before reinstall.

**Comment by gokulm** [comment]
Chrome is up to date. I tried re-installing Postman, but no luck.

**Comment by a85** [comment]
@gokulm Sometimes right clicking in the task bar and clicking maximize brings the Postman app back in focus.

**Comment by gokulm** [comment]
I don't see maximize in Windows 10

**Comment by gokulm** [comment]
It's working now. After launching postman, I clicked on it, it showed a small popup without any content (and a blank header for the popup), right clicked on the header and clicked Maximize as @a85  mentioned.

**Comment by heajink** [comment]
Anyone could you please let me know how to adjust the font size on Postmane ? I installed it from Chrome Web Store. I am on the window 10 laptop.

thank you for your help in advance.

**Comment by abhijitkane** [comment]
@heajink Sorry for the delay on this. We now support `Cmd/Ctrl +/-` shortcuts to increase/decrease font size. Feel free to re-open if you still face issues.

**Comment by sdnts** [comment]
You can also increase the editor font sizes by using the Settings page (Wrench icon > Settings > General Tab)

**Comment by cvcnsprakash** [comment]
Struck up with the same issue..app is opened and is shown in taskbar. But when i click it, nothing happens!
Also, if i Press alt+tab, i can see a small rectangle boxed postman window, but when i click it nothing happens. Have tried reinstalling and chrome is uptodate!

Any help is Appreciated!

**Comment by zach-is-my-name** [comment]
Why was this issue closed? The Op was addressing the inability of the window to appear.  I am having this issue, regardless of an unrelated font matter which is not referenced in the title

**Comment by mpbalmeida** [comment]
Having the same problem here.

**Comment by numaanashraf** [comment]
@mpbalmeida Are you facing the same issue that OP posted? About Chrome apps not launching on Windows 10?

**Comment by mpbalmeida** [comment]
@numaanashraf The app appears open in taskbar, but i can't open its windows. i've reinstalled and it continues with the same issue. Yesterday it was ok.

**Comment by pogermano** [comment]
I have the same problem, it is not open on win 10

**Comment by HNeukermans** [comment]
same here

**Comment by milan2404** [comment]
facing the same issue.

Can someone share the solution?
