### ISSUE TITLE
Bought Jetpacks - received in installation code - support request not answered

### ISSUE THREAD

**Issue by PatrickSmout** [a85/POSTMan-Chrome-Extension#1539]
A few days back I bought the Jetpacks.
Until now I didn't receive instalation code(s) neither a reply on my support request.

How shall I proceed from this point on?

**Comment by a85** [comment]
@PatrickSmout Sorry about this. We are looking into it.

**Comment by abhijitkane** [comment]
@PatrickSmout We've associated the purchase with the correct user account and replied to the support request. Sorry for the delay.
