### ISSUE TITLE
docs for path variables are outdated

### ISSUE THREAD

**Issue by jcollum** [a85/POSTMan-Chrome-Extension#1540]
https://www.getpostman.com/docs/requests

It's showing use of {{id}} etc; that doesn't work in the current version. I have a url with `rest/applications/:id/problems` in it, it's working. If I change that to `rest/applications/{{id}}/problems` it fails (passes {{id}} as is, no replacing). 

I'd love to report the version that I'm using but the About menu item is grayed out on Mac. :-1: :angry:

**Comment by a85** [comment]
@jcollum Is that on the Mac app?

**Comment by jcollum** [comment]
> grayed out on Mac

**Comment by abhijitkane** [comment]
@jcollum Sorry about the delay on this - are you still facing this problem?

**Comment by jcollum** [comment]
I'm not sure. I uninstalled the app a while ago.
