### ISSUE TITLE
Get Final Request Body & URL after Rendering vars in sandbox

### ISSUE THREAD

**Issue by gaurish** [a85/POSTMan-Chrome-Extension#1541]
I am working against an API which uses signed requests using `HmacSHA256` of URI Path + Request Body. so I wrote this small Pre-quest script to generate the signature digests:

``` js
var index = request.url.indexOf('/');
var uri_path = request.url.substring(index);
var payload;
if(_.isEmpty(request.data)){
    payload = uri_path;
}else{
    payload = uri_path + request.data;   
}
console.log("Using payload as " + payload)
var hash = CryptoJS.HmacSHA256(payload, environment.secret);
var hashInBase64 = CryptoJS.enc.Hex.stringify(hash);
postman.setGlobalVariable("signature", hashInBase64);
```

The above works nice as long there are no vars in request. But if  there are placeholder variables, for example I am trying to build a sample user registration request, using something like this

``` js
{
  "email": "user{{$randomInt}}@example.com",
  "password": "My Super String Password goes here"
}
```

the above would generate wrong signature as `{{$randomInt}}` is NOT resolved in the request object & is taken literal causing incorrect signature.

Is there a way by which I resolve variables inside request?

**Comment by abhijitkane** [comment]
For now, you'll need to do the replacement yourself. You can use environment.x to resolve the payload:

`payload = payload.replace(/{{(\w*)}}/g,function(str,key) {return environment[key]});`

For the $randomInt part, you'll need to use `Math.floor(Math.random() * 1000)` to generate a random value yourself and insert it into the unresolved string.

We're working on resolving the variables in the pre-request script itself, but don't have an ETA right now.

**Comment by gaurish** [comment]
@abhijitkane
I thought about this before but problem with random is that it's random. so output of `Math.floor(Math.random() * 1000)` in pre request script is going to be different that in actual request. causing sig digest to be invalid. 

 But anyways, I understand that this is not supported now but support will be coming. so looking forward to it.

**Comment by abhijitkane** [comment]
Don't use `{{$randomInt}}`. Set the variable in your pre-request script:

`postman.setEnvironmentVariable("myRandom", Math.floor(Math.random() * 1000));`

and use `{{myRandom}}` in your request.

**Comment by gaurish** [comment]
:+1: Thank you!
