### ISSUE TITLE
Reg - License

### ISSUE THREAD

**Issue by sibalas** [a85/POSTMan-Chrome-Extension#1542]
Hi Team,
Please clarify below quires.
1. We are in need of 5 licenses . We been acquired by a company.Our current  official will be changed latter but present email id will be mapped internally. Will it impact the post man login id? and also 2.Please confirm whether concurrent login is allowed for a particular id 
   3.Whats the validity period for the license. 

Please clarify as soon as possible

Thanks,
Siva

**Comment by abhijitkane** [comment]
1. If the emails are mapped internally, it won't affect your Postman login. Any reset password emails sent to your old email will be forwarded to your new email. 
2. You can login on upto 3 machines using the same login id - https://www.getpostman.com/licenses/postman_jetpacks_addendum
3. The Jetpacks license is valid for life.

**Comment by sibalas** [comment]
Thanks Abhijitkane
