### ISSUE TITLE
Running collection does not update auth settings

### ISSUE THREAD

**Issue by Fr4ncis** [a85/POSTMan-Chrome-Extension#1543]
I have a collection that uses OAuth 1.0 credentials to verify the requests. Unfortunately it seems that running the whole collection instead of the requests one by one the OAuth credentials don't get updated thus getting 401 responses. It also seems that downloading the collection to use it in newman, all details about authorization get lost.

Is it a bug? Is there a workaround for this by using the pre-request scripts?

Thanks, F

**Comment by abhijitkane** [comment]
Can you try checking the 'Auto add parameters' and 'Save helper data to request' checkboxes in the OAuth1.0 section and saving the request?

This will save the helper data with the request, and running the whole collection should refresh the OAuth1 credentials for the requests. Downloading the collection will also contain the helper data, and Newman will be able to generate the signature.

**Comment by Fr4ncis** [comment]
Great, it actually works in Postman! Thanks.

However in newman I get a (unrelated I guess) issue:

Iteration 1 of 1
Obj: "ok"
200 5229ms /healthcheck http://mapi.mysite.localdev/healthcheck
    ✔ Status code is 200
    ✔ Body is correct
/usr/local/lib/node_modules/newman/src/utilities/HelperProcessor.js:415
                p.value = p.value.replace(/&/g, '%26');
                                 ^

TypeError: Cannot read property 'replace' of undefined
    at Object.jsface.Class.setUrlParamStringWithOptBlankValRemoval (/usr/local/lib/node_modules/newman/src/utilities/HelperProcessor.js:415:22)
    at Object.jsface.Class._useOAuth1 (/usr/local/lib/node_modules/newman/src/utilities/HelperProcessor.js:211:10)
    at Object.jsface.Class._useAuthHelpers (/usr/local/lib/node_modules/newman/src/utilities/HelperProcessor.js:29:9)
    at Object.jsface.Class._execute (/usr/local/lib/node_modules/newman/src/runners/RequestRunner.js:166:20)
    at null._onTimeout (/usr/local/lib/node_modules/newman/src/runners/RequestRunner.js:222:11)
    at Timer.listOnTimeout (timers.js:92:15)

fmattia:Documents fmattia$ newman --version
2.0.0-beta.1

**Comment by abhijitkane** [comment]
Hm..that seems to be a bug. Was any of the OAuth1 params set to null? Either way, we'll push a fix in the next Newman release. Thanks for reporting this.

**Comment by Fr4ncis** [comment]
token and tokenSecret are not set for a couple of requests (to get those parameters from the provider), thanks!

**Comment by Fr4ncis** [comment]
OK, it seems that setting environment variables to "" upset newman.

In newman:

https://www.getpostman.com/collections/fc13d501598107a36184

however with the environment below (I removed the consumer key/secret) requests fail (it seems that nonce and possibly timestamp don't get updated).

fmattia:Documents fmattia$ cat prod_env.json 
{
    "id": "c3764e1f-4118-9dce-346c-39d252a88418",
    "name": "MAPI Prod v3.3",
    "values": [
        {
            "key": "apiServer",
            "value": "mapi.vouchercodes.co.uk",
            "type": "text",
            "name": "apiServer",
            "enabled": true
        },
        {
            "key": "apiVersion",
            "value": "v3.3",
            "type": "text",
            "name": "apiVersion",
            "enabled": true
        },
        {
            "key": "consumerKey",
            "value": "xxx",
            "type": "text",
            "name": "consumerKey",
            "enabled": true
        },
        {
            "key": "consumerSecret",
            "value": "xxx",
            "type": "text",
            "name": "consumerSecret",
            "enabled": true
        }
    ],
    "timestamp": 1446487025229,
    "synced": false,
    "syncedFilename": ""
}fmattia:Documents fmattia$

**Comment by haridak** [comment]
I've been running into this error lately when I try to run the calls in terminal using newman. The same json files(API calls and global) worked fine until last week. The calls work fine in postman too.

```
/usr/local/lib/node_modules/newman/src/utilities/HelperProcessor.js:415
                p.value = p.value.replace(/&/g, '%26');
                                 ^
TypeError: Cannot read property 'replace' of undefined. 
```

The version of newman I have is - 1.2.23

Could you provide any inputs  to resolve this?

**Comment by abhijitkane** [comment]
@haridak Feel free to re-open if you're still seeing this.
