### ISSUE TITLE
Code snippets are confusing

### ISSUE THREAD

**Issue by royaldark** [a85/POSTMan-Chrome-Extension#1544]
I upgraded from Postman 2 to 3 today, and despite the very nice new look, I've been frustrated by several changes made, including the "code snippets" feature.

I spent about 10 minutes looking through the interface for the old Preview button and didn't find anything applicable. In fact, I initially thought that Preview might fall under a "pre-request script", and I was pretty annoyed at the (incorrect) idea that I would have to pay $10 for the privilege. 

Finally, after several red herrings, Google brought me to https://github.com/postmanlabs/postman-app-support/issues/1183, which indicates the same effect can be found under code snippets by selecting HTTP from the dropdown. Semantics aside (HTTP requests aren't really code...), I think the UX here is pretty confusing. As a migrating user, I had no idea where to look, and if I were a new user, I would probably never even know the feature existed.

I think the problem is twofold:
1. The code snippets icon is not very accurate or descriptive. Getting raw HTTP request data really has nothing to do with HTML tags.
2. For me, at least, there is an important distinction between code that generates HTTP requests, and the requests themselves. The HTTP code snippet generated is the underlying request that all other code snippets will produce anyway. For this reason, including HTTP as a code snippet doesn't make much sense to me.

I'm sure you guys have spent far longer thinking over these changes than I have, and I'm probably just another curmudgeon annoyed by any change, but I wanted to at least bring this corner of the app up for discussion.

**Comment by a85** [comment]
@royaldark You are absolutely right and sorry about the trouble that you faced. We are changing this into a text button.

**Comment by royaldark** [comment]
@a85 Great to hear! I love the idea of code snippets in general - glad to see this issue will be resolved.

**Comment by aditikul** [comment]
@royaldark This is a text button now, hope this helped!
