### ISSUE TITLE
choose what to sync

### ISSUE THREAD

**Issue by alexthornton** [a85/POSTMan-Chrome-Extension#1545]
Sync is a great feature, but it would be better if we could choose what to sync with the servers. My environments can contain passwords that I don't want synced. It would be helpful to be able to choose specifically which items are being synced to the server.

**Comment by boblindman** [comment]
Agree, either letting me decide what to sync or giving me control of the encryption password (so your team has "zero-knowledge" of my password) could solve this issue.  Until then, I can't use sync

**Comment by nathanboktae** [comment]
+1 this is a deal breaker @alexthornton and we'll end up using Paw over Postman for our team even though I'd rather use Postman.

**Comment by a85** [comment]
This is not on our immediate roadmap in it's current form. However, we are looking at the idea of "workspaces" that will help you create groups of data that might be syncable/non-syncable. We will review this feature request again at that time.
