### ISSUE TITLE
How do I Force Postman to open login screen on clicking "Get Access Token"

### ISSUE THREAD

**Issue by RonakThakkar** [a85/POSTMan-Chrome-Extension#1546]
I am using OAuth 2.0 flow.

I entered required details for OAuth 2.0, clicked "Get Access Token" that opened Azure Active Directory login screen. Now I enter User1 credentials, login was successful and I got token back. Everything worked perfectly.

But now I would like to use User2 for testing. Hence I clicked on "Get Access Token" button again hoping that login screen will be opened and I would be able to enter credentials in there for User2. Instead it seems like Postman remembers the User1 and hence directly got the token back. Is there a way to force sign out and open that login screen again.

**Comment by abhijitkane** [comment]
Can you enable DevTools (http://blog.getpostman.com/2015/06/13/debugging-postman-requests/), go the the console, and enter the following:

```
chrome.identity.launchWebAuthFlow({'url': 'https://login.windows.net/{tenantid or "common"}/oauth2/logout?post_logout_redirect_uri=', 'interactive': false}, function(){ if (chrome.runtime.lastError) { console.log("Azure logout"); }});
```

Replace `{tenantid or common}` with the tenantId (if you have one), or `common`

If that doesn't work, try `https://login.windows.net/common/oauth2/logout?post_logout_redirect_uri=` as the url

**Comment by RonakThakkar** [comment]
I run the command and in next line it says undefined. Then I tried clicking "Get Access Token" button in Postman and it returned token using User1 (old) without opening login screen

**Comment by abhijitkane** [comment]
What's the authorization URL that you're using?

**Comment by RonakThakkar** [comment]
I removed ?post_logout_redirect_uri= and it worked.

Thanks a lot for your support and Postman is really awesome tool.

**Comment by abhijitkane** [comment]
Great..these logout URLs are specific to each OAuth provider, so we can't give a list in the app itself.

**Comment by RonakThakkar** [comment]
I have found Postman documentation quite well. I think you can add these scenario in some of the document.

**Comment by abhijitkane** [comment]
Yep, we're working on revamping the documentation. We should have new content up soon.

**Comment by RonakThakkar** [comment]
Have you implemented these new feature in your Postman?

**Comment by JontyStephan** [comment]
There is a "Cookies" link button under the Send button in Postman. Click that and then remove all the Microsoft cookies. When requesting a new token, it will now ask for login credentials.

**Comment by LaurelGerman** [comment]
Clearing cookies in Postman didn't work for me, but here's a low-tech solution that did (Only tested in Chrome):
After you click Get Access Token and the login screen appears in your browser,
1. Copy the url
2. Open an incognito tab and paste the url
3. Log in via that incognito window

This way, cookies are never saved, and you'll be prompted to log in every time you generate a new token. As long as you never log in thru a non-incognito window, this works!
