### ISSUE TITLE
Problem with fetching huge data around 1 lac row

### ISSUE THREAD

**Issue by rkt** [a85/POSTMan-Chrome-Extension#1547]
It does not works while i am trying to fetch around 1 lac row in json format.  What i need, i need to fetch the 1-7 lac row from my server in json format. But it does not work with it.

Once i tried with  less data like getting 20-50 rows it works fine, but failed with huge data. I have tried almost every given solution at google but no luck.

Any help will be appreciated.

Thanks
Robi Kumar

**Comment by abhijitkane** [comment]
For such volumes of data, Postman will run into memory issues. Postman needs to render JSON in a pretty view, or show it in a text area, and showing such large amounts of data is simply not feasible. You can create the request in Postman, and then use cURL to send the actual request. View the generated cURL command by clicking the Code Snippets button ( </> ), and selecting 'cURL'.

**Comment by a85** [comment]
We recommend using "Send and Download" for large payloads. We are tracking performance issues in other threads.
