### ISSUE TITLE
Postman Beta Icon on Chrome App Launcher 

### ISSUE THREAD

**Issue by felipeplets** [a85/POSTMan-Chrome-Extension#1548]
A small issue is that the Postman Beta Icon has a BETA tag in the dock icon, but as I usually launch Postman from the Chrome App Launcher, both icons, from the productive and beta versions are the same. Would be nice to follow the same icon pattern here.  

![image](https://cloud.githubusercontent.com/assets/119980/10949972/b777e1cc-831c-11e5-8b39-5fc98557de5e.png)
**Dock Icons**

![screen shot 2015-11-04 at 5 46 51 pm](https://cloud.githubusercontent.com/assets/119980/10950018/e90db3f6-831c-11e5-8836-19e7470cfd77.png)
**Chrome App Launcher Icons**

**Comment by felipeplets** [comment]
Also name it as "Postman (BETA)" would be a good thing to ensure the developer know if is using the Beta or the final version. 

![screen shot 2015-11-05 at 4 30 16 pm](https://cloud.githubusercontent.com/assets/119980/10977895/2bdce634-83db-11e5-84f8-a50679ba1a25.png)

**Comment by a85** [comment]
@felipeplets We have closed down the beta now. We'll mark this issue for future beta programs.
