### ISSUE TITLE
Currently History is limited to small size, can we have history like in Advanced Rest Client

### ISSUE THREAD

**Issue by vvsudhir** [a85/POSTMan-Chrome-Extension#1550]
Currently History is limited to small size, can we have history like in Advanced Rest Client

**Comment by a85** [comment]
@abhijitkane History doesn't have any limit right now, does it?

**Comment by abhijitkane** [comment]
@vvsudhir In the latest version of the app, we've removed the restriction on the history count.

**Comment by vvsudhir** [comment]
It's really helpful, thanks a lot for this change [&#X1f603] .

Thanks,

$udhir.
