### ISSUE TITLE
.pdf upload

### ISSUE THREAD

**Issue by sibalas** [a85/POSTMan-Chrome-Extension#1551]
Hi Team,

While  uploading .pdf file  , an error code - "415 Unsupported Media Type" been thrown.Could you please help me to resolve?

Thanks,
Siva

**Comment by abhijitkane** [comment]
You'll have to refer to the API documentation. Are you able to successfully make the request through cURL?

**Comment by sibalas** [comment]
Hi,
Sorry i'm unable to locate the form-data related items in the documentation section and i used advanced rest client tool  for the same request and i don't see any issue in advance rest client tool.

Thanks,
Siva

**Comment by abhijitkane** [comment]
Check https://blog.getpostman.com/2015/06/13/debugging-postman-requests/ to see the exact request payload that Postman sends. You can compare this with the payload from Advanced REST Client.
Without access to the API reference (not Postman reference), it's not possible to debug the issue further.

Also, you can try setting the Content-Type header to application/pdf manually.

**Comment by sibalas** [comment]
Hi,
I had set the Content -Type header to application/pdf manually and uploaded
file for a post request .Still it says " 415 Unsupported Media Type".

Thanks,
Siva

Thanks and Regards,
Siva

**Comment by abhijitkane** [comment]
@sibalas We've made a number of updates to the way Postman handles file uploads. Are you still seeing this issue?
