### ISSUE TITLE
Tests take a lot of time to sync

### ISSUE THREAD

**Issue by alowenst** [a85/POSTMan-Chrome-Extension#1554]
Hi!,

I'm using newman with -u option (collection in URL) and I noticed that it can take up to 10 minutes from the time the test is saved and synced until it actually "catches up" in newman.
This is quite annoying and is causing lots of failures till the updated test is running.

Thanks!

**Comment by abhijitkane** [comment]
@alowenst Depends on the size of the collection and your network. How many requests do you have in this collection?

**Comment by alowenst** [comment]
2 requests, each has a test (if that's makes a difference).
Thanks!

**Comment by abhijitkane** [comment]
Might be a network issue. Postman makes a simple POST call with your collection's JSON representation, and it should be available on the URL instantly.

**Comment by alowenst** [comment]
Thanks for the reply. Checked again and it works OK. Closing.
