### ISSUE TITLE
Feature request : Build random request body using regex patterns given for each field

### ISSUE THREAD

**Issue by deepal** [a85/POSTMan-Chrome-Extension#1555]
I would love to see a feature in Postman where I can set request body fields to be generated randomly each time based on a specified regex (our own dynamic variables). Something like below will be awesome. 

``` javascript
{
    email: {{/[a-z]{6}@[a-z]{7}.com/}},
    firstname: {{/[a-z]{6}/}},
    ipAddress: {/(?:[0-9]{1,3}\.){3}[0-9]{1,3}/}
}
```

which will create the dynamic request body, something like below

``` javascript
 {
  email: "pqrst@example.com",
  firstname: "adsfas",
  ipAddress: "68.239.70.1"
}
```

**Comment by a85** [comment]
Have you checked out pre-request/test scripts inside Postman. It should let you do this.

**Comment by taposoft** [comment]
Hi Abhinav,

Can you please post an example on how to create a dynamic request body which populates JSON objects (not just primitives/Strings).

Appreciate your time.

Example:

My input Data file looks like this. 
[{
    "person": {
        "id": "1",
        "name": "Raghu",
        "zipcode": "500050"
    }
}
{
    "person": {
        "id": "2",
        "name": "Prasad",
        "zipcode": "500051"
    }
}
]

My request body should look like this in each iteration.
"person": {
        "id": "2",
        "name": "Prasad",
        "zipcode": "500051"
    }

Thanks,
Raghu.

**Comment by abhijitkane** [comment]
@gotoraghu
Postman currently supports JSON files with only one level of nesting. "person" has to be an atomic value.
You can use JSON.stringify to create the JSON file, and JSON.parse in your pre-request script.
