### ISSUE TITLE
Runner never finishes when too many server response errors

### ISSUE THREAD

**Issue by LorenzSchumann** [a85/POSTMan-Chrome-Extension#1556]
Steps to reproduce:
- Build a collection with a single request, where the server will return an error code (500 in our case)
- Let the Runner run the collection 150 iterations - it will finish
- Let the Runner run the collection 200 iterations - it will work forever

In our case, the turning point is exactly at 176 iterations. 175 iterations work, while 176 will run forever.

**Comment by abhijitkane** [comment]
@LorenzSchumann Can you check the app version you're on? (chrome://extensions)

Also, check http://blog.getpostman.com/2015/06/13/debugging-postman-requests/ for steps to open the debugger. Are there any errors printed in the collection runner's console after the 176th iteration?

You could also open the Activity Monitor (OSX) or TaskManager (Windows) to see if Postman is taking up too much memory after 150+ iterations.

**Comment by LorenzSchumann** [comment]
Thanks for the fast reply!

I was on **Version 3.1.0.1 (packaged)** (the beta) but I also get the error after installing the latest non-beta **Version 3.1.5 (packaged)**.

Here is a screenshot of the Developer Tools, after the "freeze" happens:

![postman](https://cloud.githubusercontent.com/assets/5647739/11094500/65cb87ce-8890-11e5-9bf0-e14bcdd6ff67.PNG)

**Comment by abhijitkane** [comment]
This is probably due to https://www.chromium.org/throttling. You'll need to start Chrome with the flag specified to disable the auto-throttling by Chrome.

**Comment by LorenzSchumann** [comment]
Works like a charm :) Thank you very much!
But in my opinion that case should still be handled and the execution should continue - so there is still an issue with the error handing in the runner.

**Comment by numaanashraf** [comment]
Not reproducible in Postman Desktop Apps - https://getpostman.com/apps
