### ISSUE TITLE
Google endpoints support

### ISSUE THREAD

**Issue by evra** [a85/POSTMan-Chrome-Extension#1557]
Please, add google endpoints import based on Google API Discovery Service https://developers.google.com/discovery/v1/reference/index 

It would be really helpful to populate collections based on google discovery docs. 

Thanks,
Evgeny

**Comment by a85** [comment]
Postman now contains an API Network to help with API discovery in general. We will hopefully incorporate Google's APIs too soon.

**Comment by slpenza** [comment]
It appears the API Network wasn't able to incorporate Google APIs. Any possibility of reconsidering adding support for Google's API Discovery Services, or other suggestions? Thank you

**Comment by arlemi** [comment]
@slpenza It is up to the API provider to add their APIs to the API Network since it also requires to be kept up-to-date over time. I'd recommend asking on the Google Forums whether they'd consider creating a Postman Collection for their APIs instead. 🙂
