### ISSUE TITLE
Backup_postman dump sharing in teams creates duplicate collection

### ISSUE THREAD

**Issue by llefkowitz** [a85/POSTMan-Chrome-Extension#1558]
Need a better way to have backup_postman.dump, use between team. We use jetpack to write our tests. Changes are saved to backup postman dump. Your documentation says it overwrites the collections when you get a backup postman dump. That is not happening (it looks like it used to).  Now it creates duplicate collections. I would request either you give an option to overwrite data with same collection name or get a way to delete all collection (deleting each collection individually is very cumbersome, nobody has the time)

**Comment by a85** [comment]
Unfortunately, the backup feature service is not mean for team sharing. I'd suggest exporting data manually to share tests or using Postman Cloud.

**Comment by SamvelRaja** [comment]
@llefkowitz The latest app  will finds its availability and shows up the modal to choose between copy as new or replace with old one while importing it.
