### ISSUE TITLE
Hope postman could refresh apis instead of re-import

### ISSUE THREAD

**Issue by smilence86** [a85/POSTMan-Chrome-Extension#1560]
Use postman a few months, It's very good!

there is a suggest for it.
I wrote some apis and shared to my partner, He would re-import it after I edited it. It's not easy to use. 

Please consider to add a refresh button and no need to re-import, thanks~

if api which shared to others can auto refresh is perfect.

**Comment by abhijitkane** [comment]
We have a feature called team sync which does just this :). You can share a collection with your team, and your team-members can subscribe to it. All changes are reflected in real time. More details at https://www.getpostman.com/pricing

**Comment by cpjeanpaul** [comment]
![image](https://user-images.githubusercontent.com/7806714/46759284-a4635700-cc94-11e8-8921-60eb7543a363.png)
