### ISSUE TITLE
How to execute same test for multiple endpoints?

### ISSUE THREAD

**Issue by cameronoxley** [a85/POSTMan-Chrome-Extension#1561]
Hi, 

I'd like to either create a universal "Test Structure" method to verify the response structure across a collection of tests - or - have tests reference a "base" test?

Is there a way to do this?

**Comment by a85** [comment]
Not yet but we are working on it.

**Comment by abhijitkane** [comment]
@cameronoxley As a workaround, you can store JS in environment variables, and use `eval()` in your scripts to get some reusability of test scripts.

We'll soon be introducing collection-level scripts.
