### ISSUE TITLE
Not able to send request

### ISSUE THREAD

**Issue by Pysis868** [a85/POSTMan-Chrome-Extension#1562]
I am using Postman's packaged app version through the Google Chrome framework.

I can enter a sample URL, hit "Send", and nothing happens.  I don't see any Console messages or Network entries in the Chrome Developer Tools, or any error messages in the UI.

I have enabled packaged app debugging, to be able to include that detailed information, via the several instructions contained on this page: [Debugging new Chrome packaged apps](https://stackoverflow.com/questions/12583545/debugging-new-chrome-packaged-apps)

**For comparison**
I also have a problem using the Insomnia REST Client that is also a Chrome packaged app.
Advanced REST Client loads in-browser, not in its own window as a packaged app I believe, and it works.

**Comment by abhijitkane** [comment]
Do you have Javascript enabled? Even if it's not some extensions might still work, but you'll need to add an exception for Postman. https://github.com/postmanlabs/postman-app-support/issues/712#issuecomment-75361332

Also, what version of Postman and Windows/OSX are you on?

**Comment by Pysis868** [comment]
I tried the advice you linked, and at first it did not work, but then it did!  Here are my steps:
1. Added the "file:///.../Extensions/"-style JavaScript allowance rule to Chrome's settings (it was a bit difficult trying to add this for some reason; the entry would not be saved in the table after inputting it and hitting the Enter key.).  Postman did not work.
2. Restarted all of Chrome and its framework.  Postman did not work.
3. Set Chrome to allow all JavaScript.  Postman did not work.
4. Added the "chrome-extension://*/"-style JavaScript allowance rule to Chrome's settings (the first rule had vanished for some reason before I did this).  Postman worked! :)

I hope this post can be helpful to others with its differently-worded title.

Thanks for the specific information to act on!

**Comment by scottwhetzel** [comment]
allowing this "chrome-extension://postman_extension_id/" as a javascript exception worked very well for me.  thanks to the previous writers for revealing this.  It would have been soo helpful if postman had given any error indication regarding the javascript permissions.
