### ISSUE TITLE
pre-request Access Enviroment vars too late for chained requests

### ISSUE THREAD

**Issue by N0rimaki** [a85/POSTMan-Chrome-Extension#1563]
#### Pre-info:

Our server take the whole request body length from { to } and generate some MD5 Hash. 
I must do the same on the Client/postman and add the hash into the Headerfielad als AdditionalInfo.
The Server compares booth hash and grant or deny the access.
Via pre-request Script i get the request body and also create the MD5, store it in some env. var and add it to the Headerfield.. works like a charm.

``` javascript
var rdata = request.data;
var requestLength = JSON.stringify(JSON.parse(rdata)).length;
//console.log(JSON.stringify(JSON.parse(rdata)));
var presharedkey = "foobar";

var AdditionalInfoString = [];
AdditionalInfoString.push(requestLength,presharedkey);
AdditionalInfoString = AdditionalInfoString.join("");

var hash = CryptoJS.MD5(AdditionalInfoString);
postman.setEnvironmentVariable("AdditionalInfo", hash.toString());

//console.log("length "+requestLength);
//console.log("string "+AdditionalInfoString);
//console.log("hash "+hash);
```
#### The Problem:

I store the SessionID from the response in the env. vars. and add it with {{SessionID}} in the next request body. But now the MD5 hash doesn't match anymore because postman add the env. var after the pre-request script and the MD5 will be created with "SessionID":"{{SessionID}}" instead of "SessionID":"348ab8e5-e777-6666-8888-a54e00fadb28" and the Server returns some Error.
#### Solution

**I think the correct order for accessing would be:**
1. replace env. vars in body
2. run pre-request script
3. add Headerfileds
4. perform request
5. Tests

**Postmaninfo:**
Version 3.1.5 (packaged)
OS: win
Architecture: x86-32
Native client architecture: x86-64

**Comment by N0rimaki** [comment]
hi... did the Dev. read the Issues?

**Comment by abhijitkane** [comment]
@T-Norimaki This is a known issue, documented in https://www.getpostman.com/docs/jetpacks_sandbox - `Note: Variables will NOT be resolved in the request object`. We're working on a redesign of the sandbox that should solve this use-case.

**Comment by N0rimaki** [comment]
i'm sorry... didn't read this carefully enough, but i hope you guys will found a solution for this.

**Comment by N0rimaki** [comment]
Hi, is it possible to get a net Status about this Issue?
Thank you

**Comment by taposoft** [comment]
Hi,

I am also in need of this feature. Please let us know if you are working on the solution and any ballpark on when the feature will be available.

Thanks,
Raghu.

**Comment by liweigong** [comment]
also need this feature too.

**Comment by a85** [comment]
@shamasis What's the behavior in the runtime now?

**Comment by shamasis** [comment]
Current runtime updates env variables after every script and during request the latest state is used. This issue should not exist any longer. @madebysid can you do a quick check and confirm?

**Comment by liweigong** [comment]
still not work. 

4.7.0
win / x86-32
Chrome 52.0.2743.116

my pre script like this:

```
var arr = [];

    for(var param in request.data){
        if(param != "sign"){
            arr.push(param);
        }
    }

    arr.sort();

    var str = "";

    for(i=0;i<arr.length;i++){
        if(i == arr.length -1){
            str+=arr[i]+"="+request.data[arr[i]];
        }else{
            str+=arr[i]+"="+request.data[arr[i]]+"&";
        }
    }

    str +="&key="+globals[request.data.name+".key"];

    // Use the CryptoJS script you imported
    var hash = CryptoJS.MD5(str).toString();

    // Set the new environment variable
    postman.setEnvironmentVariable('sign', hash);
```

**Comment by shamasis** [comment]
Can you try in Windows or Mac native apps and let us know if it works for you?

**Comment by sdnts** [comment]
@shamasis Can indeed replicate this issue in the Chrome app. This seems to be fixed on the native apps though.

@N0rimaki @gotoraghu @Liweigong Can you guys try running your collection in the native apps and let us know? (https://www.getpostman.com/apps)
Native apps are now built on top of a newer architecture that is yet to be rolled out on Chrome. (http://blog.getpostman.com/2016/06/14/introducing-postman-runtime-more-power-better-control/)

**Comment by liweigong** [comment]
windows app , x64 and x86 version both tried.  
app version 4.7.0  (auto update after install)

still not work. and even worse.  can't pass the sign verify even not use param {{timestamp}} 

I will try it again later since my computer a bit slow now.

**Comment by liweigong** [comment]
any update?

**Comment by sdnts** [comment]
@Liweigong I'm unable to replicate the original issue on the native apps (I used the same pre-request script). Is it possible for you to upload a simple dummy collection where you can see this misbehaviour? This is the collection I used: [here](https://documenter.getpostman.com/view/214062/gh1563/2MrXo8). Let me know if I'm doing something wrong.
Also, the `timestamp` dynamic variable is referred to as `{{$timestamp}}`, so maybe that's why it wasn't working for you?

**Comment by shamasis** [comment]
This has been implemented in runtime of native apps. Closing.

+ @a85
