### ISSUE TITLE
Clear environment variable snippet shows error

### ISSUE THREAD

**Issue by cameronoxley** [a85/POSTMan-Chrome-Extension#1565]
When inserting the "Clear Environment variable" snippet an error is produced from the default template.

![screen shot 2015-11-13 at 12 31 07](https://cloud.githubusercontent.com/assets/1674847/11144494/b6365380-8a05-11e5-9fc0-f289d6947965.png)

**Comment by abhijitkane** [comment]
Thanks for pointing this out. We'll be pushing out an update today that should fix this.

For now, you can remove the comma and it should work.
