### ISSUE TITLE
Parse a response body in XML and set an environmental variable

### ISSUE THREAD

**Issue by sohira** [a85/POSTMan-Chrome-Extension#1566]
Is there any good example of parsing XML response body and set an environmental variable using JetPacks?  There are many examples using JSON but not for XML.  Thanks for the help...

**Comment by abhijitkane** [comment]
The sandbox documentation is here - https://www.getpostman.com/docs/jetpacks_sandbox

Use the xml2Json(xmlString) function:
`var xmlTree = xml2Json(responseBody);` in the test script. You can then use xmlTree as a normal JS object and set variables.

For the exact format of the `xmlTree` object, you can use `console.log(xmlTree);`. To view the console, check https://blog.getpostman.com/2015/06/13/debugging-postman-requests/

**Comment by jjae2124** [comment]
is there an analogue function to xml2Json in the Sandbox to convert a javascript object (or parts of it) back to XML ?

**Comment by mhGLEIF** [comment]
>>> is there an analogue function to xml2Json in the Sandbox to convert a javascript object (or parts of it) back to XML ?

+1000. I'm regularly swapping XML strings in JSON wrappers and they are JSON-escaped, not XML escaped, so I can't toggle the escapes with my XML editor :-(
