### ISSUE TITLE
newman  - Getting the error message to show on console

### ISSUE THREAD

**Issue by haridak** [a85/POSTMan-Chrome-Extension#1567]
Hi,
We run the API collection through Jenkins on a schedule. Each API call has some tests.
The error message displayed in the console is related to the tests. E.g. if the test is looking for a particular id, the error message displayed in the console is something like - cannot find the id.
Do we have a  way to display the "message" from output if the status_code is 500? That would actually give a better idea about the problem.
Response when run through Postman

```
  "meta": {
    "message": "undefined method `duplicate_gate_code' for #<Ledger:2323232>",
    "status_code": 500,
```

Response when run from console

```
 EXCEPTION - TypeError: Cannot read property 'ledger_id' of undefined
```

**Comment by haridak** [comment]
looking for something like this - 

```
var data = JSON.parse(responseBody);
if(data.meta.status_code === 400)
{
console.log(data.meta.message); 
}
```

**Comment by abhijitkane** [comment]
@haridak The `Cannot read property 'ledger_id' of undefined` error is because you're trying to access `data.<something>.ledger_id`, which fails if the status code is 200.

Your code should work perfectly. Just add a return statement so that the rest of the tests don't execute.

```
var data = JSON.parse(responseBody);
if(data.meta.status_code === 400 || data.meta.status_code === 500)
{
    console.log(data.meta.message); 
    return;
}
```

**Comment by haridak** [comment]
@abhijitkane that's right. 
data.meta.message is "the status code is invalid... blah blah" 

This message does not get displayed on the console though

**Comment by abhijitkane** [comment]
Are you running this is newman? Try adding a `console.log(data);` just after the `JSON.parse()` call and check the data object.

**Comment by haridak** [comment]
I was running in postman.I see the error when I try it in newman. awesome. thanks!

**Comment by abhijitkane** [comment]
In Postman, check https://blog.getpostman.com/2015/06/13/debugging-postman-requests/ for steps to view the console. The collection runner has a separate console.

**Comment by mzky** [comment]
var jsonData = JSON.parse(responseBody);

tests["API_Name_message:"+responseBody] = jsonData.status == "0";//1

console.log("message:"+responseBody);//2
