### ISSUE TITLE
Can't set order of calls in collection with folders

### ISSUE THREAD

**Issue by cameronoxley** [a85/POSTMan-Chrome-Extension#1568]
I have a collection of calls within separate folders.

I'd like to re-arrange the folders manually to execute calls in a specific order so that I can set Environment Variables to be used in subsequent tests.

e.g. I want to be able to call "Login" so that I can set a token before calling "Dashboard"
![collection_runner](https://cloud.githubusercontent.com/assets/1674847/11178649/c151537a-8c56-11e5-996a-da7ef8260806.jpg)

**Comment by KumG** [comment]
I have the same problem. For now, I have to add a number in the collection name. (ex. "01 - Login", "02- Dashboard" ,...) and when I have to add or delete a folder, I have to rename all the others folders...

It would be very nice to be able to change to order of subfolders like it is possible to rearrange the order of the requests inside a folder...

**Comment by stephenliberty** [comment]
Same issue. Very obnoxious.

**Comment by deardooley** [comment]
Same issue. We used a numeric versioning approach as well, though it impacts our ability to generated automated tests.

**Comment by abhijitkane** [comment]
@stephenliberty @deardooley @cameronoxley We're working on a way to order folders. Meanwhile, we have a new feature to control request flow - http://blog.getpostman.com/2016/03/23/conditional-workflows-in-postman/

**Comment by a85** [comment]
Folder reordering will be available soon inside Postman but won't be part of the Collection Runner ordering flow.

**Comment by a85** [comment]
Tracking here: https://github.com/postmanlabs/postman-app-support/issues/682. Feature is coming soon along with multi-level folders.

**Comment by Andacious** [comment]
This should be reopened, I cannot reorder items in a folder after the latest update (v5.1.3).

**Comment by sdnts** [comment]
@Andacious we're tracking this here: #3291, we've isolated the problem and a fix should be out soon :)

**Comment by Andacious** [comment]
Thank you, this is a pretty frustrating issue when creating runner collections. Granted you can set the next request through the script, but its not easy to understand the collection by looking at it.
