### ISSUE TITLE
Adding a request to collection does not update currently selected request

### ISSUE THREAD

**Issue by jimonthebarn** [a85/POSTMan-Chrome-Extension#1569]
When adding new requests to one of my collections I usually start off with an already saved request. When the "new" request gets added the collection will be updated accordingly and the newly created request will even be highlighted in the tree on the left side of postman (which conveys that the request is active). But the detail pane on the right will still show the "old" request.

If often end up "reconfiguring" the request I started off with, and hit safe resulting in a loss of the "old" request. 

IMHO it would be better if adding a request to a collection would not only highlight the added request but also update the details pane on the right to show my newly created request.

Version 3.1.6 (packaged)
OS: win
Architecture: x86-64
Native client architecture: x86-64

**Comment by abhijitkane** [comment]
I was unable to reproduce this. 
1. I had a saved request called "r1". 
2. Re-saved it (Save menu > Add to Collection) as r2. 
3. Updated the URL value and hit 'Save'. Only r2 was updated. r1 still had the correct URL.
Is there a different flow you're following?

**Comment by jimonthebarn** [comment]
Just tried it on my pc at home and it works fine. I encountered the issue on my pc at work though. I'll try again when I get back to work. Fortunately/unfortunately im on vacation now so this will not happen before the start of the next year. :)
