### ISSUE TITLE
Different Delay between each request

### ISSUE THREAD

**Issue by KumG** [a85/POSTMan-Chrome-Extension#1571]
Now, it is possible to add a Delay(ms) between each request.

It would be nice to be able to define a delay for a specific request.

In my case, I have a test collection and after the call of a specific method, I have to wait 1 minute before calling the next request. (synchronization of data)

To do it, I have this code : 

var t = new Date().getTime(); 
while (new Date().getTime() < t + 60000); 

But it is using 100% of the CPU...

Is there a better solution currently?

**Comment by mverma-va** [comment]
You may try something like this to add after/before any api calls
http://fake-response.appspot.com/?sleep=60

**Comment by shamasis** [comment]
duplicate of https://github.com/postmanlabs/postman-app-support/issues/1038
