### ISSUE TITLE
TAB order in Headers is wrong

### ISSUE THREAD

**Issue by askpatrickw** [a85/POSTMan-Chrome-Extension#1574]
When I'm editing a Header, I expect to be able to enter a Header and then TAB over to the Value field.
I think an auto-save kicks in so fast that  I'm kicked up to the URL field, and I have to grab the mouse and click over to the Value field.

Version 3.1.6 (packaged)
OS: win
Architecture: x86-32
Native client architecture: x86-64

**Comment by BWorld** [comment]
I am heaving the same issue as well as my coworkers using postman.

**Comment by agulab** [comment]
I'm having the same issue: after typing a new header and hitting TAB, the focus is lost. It doesn't go to the URL field in my case.

Version 3.2.8 (packaged)
OS: linux
Architecture: x86-64
Native client architecture: x86-64

**Comment by jebeaudet** [comment]
I'm having this problem as well. I also have problem when using the mouse with the dropdown menu, it closes the popup when moving the mouse but only on the first try. I've included a screencast showing the bugs, first time I use tab to switch to the other field and the following times I use the mouse.
http://www.screencast.com/t/SqmudvmxV0

Version 3.2.15 (packaged)
OS: linux
Architecture: x86-64
Native client architecture: x86-64

**Comment by fredboutin** [comment]
Same here when I hit tab the focus is lost and not in the field box.

Version 3.2.15 (packaged)
OS: mac
Architecture: x86-64
Native client architecture: x86-64

**Comment by jebeaudet** [comment]
Seems to be fixed in the latest version.

**Comment by askpatrickw** [comment]
awesome job!
