### ISSUE TITLE
Automatically setting request - headers in pre-request script

### ISSUE THREAD

**Issue by mrudult** [a85/POSTMan-Chrome-Extension#1575]
I've authentication mechanism set up in an application. After authentication all subsequent requests needs a token to be set in header.

I want to run a collection which will automatically set such a header before each request.

How is it possible? 
Currently in the pre-request scripts the `request` object is `read-only`

**Comment by abhijitkane** [comment]
You'll need to add the header as an global variable in each request, and have the first request set the variable (https://www.getpostman.com/docs/environments).

You can use `{{authHeader}}` in all requests, and use `postman.setGlobalVariable("authHeader", "1234");` in the first request.

**Comment by mrudult** [comment]
Okay. But how do I add this `{{authHeader}}` in the request object after I set it up using the `setGlobalVariable` method?

**Comment by abhijitkane** [comment]
It's mentioned in the docs. Just use `{{authHeader}}` in the header value field.

**Comment by mrudult** [comment]
Okay. Thanks. That worked!

**Comment by kineticz** [comment]
Doesn't really solve the problem. The real nice thing would be to configure such key-value pair once for all so that you don't have to set such a variable in EACH request.

**Comment by thanhnk1602** [comment]
@kindlychung I am finding a way to set difference headers for each test case. Do you have any suggested for me? I have no idea to do that
