### ISSUE TITLE
collection runner - new run loses environment

### ISSUE THREAD

**Issue by adampopkiewicz** [a85/POSTMan-Chrome-Extension#1576]
I prepare tests in folder, when start collection runner it initially remembers my current environment and folder, but when going for new run (i.e. after implementing new feature/fixing bug) "no environment" is selected.

it's not big issue since I can select my env, it's annoying and doesn't seem difficult.

**Comment by mstaalesen** [comment]
Just to add to this. If there is no environment chosen and the runner is started, there is no other way than closing it to stop the iteration. Like Adam points out, it's not a big issue, more a "quality of life" improvement.

**Comment by abhijitkane** [comment]
We've fixed this and will be pushing a fix in the next release. If an environment is selected in the Postman window, that'll be set. If not, the environment last used during a run will be set.
