### ISSUE TITLE
Selecting a saved call in the collections overwrites the new tab. Please make new tabs NOT get overriden

### ISSUE THREAD

**Issue by nrogoff** [a85/POSTMan-Chrome-Extension#1577]
When creating a new call definition, you often need to refer to one created previously. However as soon as you click on an existing one in your collection, it just replaces the new one you were editing.
Not only is this confusing, it has often led me to accidentally save the changes and ruin the original saved call.
Please can you make a 'new' tab, not get overwritten when select previous calls from the collection. Rather to spawn a new tab...if that makes sense.

**Comment by abhijitkane** [comment]
@nrogoff There's a setting called 'Open history/collection requests in new tab' which does this.
