### ISSUE TITLE
Ability to URL encode parameters

### ISSUE THREAD

**Issue by khaing211** [a85/POSTMan-Chrome-Extension#158]
% (percentage) is encoded as % instead of %25

**Comment by turchinc** [comment]
thanks for this, a big help for me!

**Comment by hisplan** [comment]
I'm no longer seeing encode/decode option when right-click on text. Has this been removed from the recent version?

**Comment by turchinc** [comment]
I can confirm this (and can no longer use the latest version FML). 
Why doesn't postman just take care of this transparently, at least as an option via settings or something? It seems like a pretty normal expectation and the parameters can be inspected before the request is sent...

**Comment by turchinc** [comment]
The funny thing is the code generated e.g. for node.js is correct:

`var http = require("http");

var options = {
  "method": "GET",
  "hostname": "xxx.xxx.xxx.xxx",
  "port": null,
  "path": "/mc/rs/entityprofile/7923?hello=%7B%22oasdf%22%3A%22asdf%22%7D",
  "headers": {
    "cache-control": "no-cache",
    "postman-token": "2c2148bc-69be-4942-2373-132db5166d8d"
  }
};

var req = http.request(options, function (res) {
  var chunks = [];

  res.on("data", function (chunk) {
    chunks.push(chunk);
  });

  res.on("end", function () {
    var body = Buffer.concat(chunks);
    console.log(body.toString());
  });
});

req.end();`
