### ISSUE TITLE
oAuth 2.0 redirect_url change?

### ISSUE THREAD

**Issue by michaelcurry** [a85/POSTMan-Chrome-Extension#1580]
This morning postman oAuth2.0 "Get Access Token" stopped working for us because of a redirect_url change that seems to have happened.  It seems the fix was to change the redirect_url from: `https://www.getpostman.com/oauth2/callback` to `https://app.getpostman.com/oauth2/callback`.  Was there are recent change that would cause this issue from your end?

Note: Postman states that we should set the redirect_url to `www` not `app` in the application

**Comment by devjack** [comment]
I've just discovered this too.  Manually adjusting the setting against my API key (in this instance) works a treat, contrary to the instructions within Postman.

**Comment by abhijitkane** [comment]
@michaelcurry @devjack
Thanks for reporting this. The OAuth2 flow should work now (retaining www.getpostman.com/... as the redirect URL).

**Comment by devjack** [comment]
Thanks @abhijitkane!
