### ISSUE TITLE
How can i store response array object in environmentvariable and pass it to next request

### ISSUE THREAD

**Issue by prad9** [a85/POSTMan-Chrome-Extension#1583]
Request 1_Response:
{
    "myArrayObject": [
        {
            "key1": "keyValue1"
        },
        {
            "key2": "keyValue2"
        }
    ]
}

Request 1 Tests:
var response = JSON.parse(responseBody);
postman.setEnvironmentVariable("myArrayObjectVariable", response.myArrayObject);

Request 2:
{
    "myArrayObjectFromVariable": "{{myArrayObjectVariable}}"
}

if i set the Request1_response "myArrrayObject"  property to environment variable under tests and access it in next Request2_request the value of "myArrayObjectVariable" environment variable is being sent as  "[object Object],[object Object]" string value which is failing to parse to JSON

I've  tried stringifying myArrayObject in request1_response before setting it to variable but not luck.

Is there a way in POSTMAN to set array objects to environment variables?

**Comment by abhijitkane** [comment]
@prad9 Stringifying should work.

`postman.setEnvironmentVariable("myArrayObjectVariable", JSON.stringify(response.myArrayObject));`

and in request 2,

```
{
"myArrayObjectFromVariable": {{myArrayObjectVariable}}  //double-quotes not needed as it'll be replaced by an object
}
```

**Comment by prad9** [comment]
Thanks for getting back. I've tried the above solution by stringifying array object and set it to environment variable. It sets perfectly as string as expected. But how do i convert it to array object again in the second request from environment variable in the request body?  

Also:
Postman (using latest version) doesnt accept environment variable without double-quotes (refer attached image)

![image](https://cloud.githubusercontent.com/assets/2275674/11462770/480b367a-977d-11e5-91eb-af0a9cc66025.png)

**Comment by abhijitkane** [comment]
The environment variable is evaluated when you send the request. What you have entered in the editor is not valid JSON, but when `{{test_environmentVariable}}` is replaced with `{"key":"value"}`, it will become valid JSON. You can ignore the warning for now.

You can use JSON.parse() to convert the variable back to an array/object.

**Comment by prad9** [comment]
Thanks applying your suggestion resolved my issue.

**Comment by kanishka84** [comment]
I need to use few of the values which i saved as an environment variable inside body of a request which sends a json. Example:
Request 1 gives out response
"value": {
      "_id": "8cc912dd2a60288f466d20562902f629",
      "_rev": "255-42de29459eece1ec0004dec5027d9e0d",
      "ID": "120",
      "post_content": "SBI P.O. 2015, changed",
      "post_title": "SBI P.O. 2015",
      "regular_price": "50",
}

I have saved the entire value in an environment variable
postman.setEnvironmentVariable("productInfo", JSON.stringify(jsonData.value));

Now i want to use "regular_price" in the body of another request is there any way of doing that?
I did this but it did not work

In Request 2
Pre-request Script i have
var order = JSON.parse(environment.productInfo);
Then in the Body i am doing
{
  "data": {
    "shipping": null,
    "tax": 0,
    "taxRate": "null",
    "subTotal": {{order.regular_price}},
    "totalCost": {{order.regular_price}}
}
}

i also tried "totalCost": order.regular_price but it didnt work

**Comment by adekola** [comment]
I'm also having the same issue as @kanishka84 ....can @abhijitkane be of help please?

**Comment by JeffLoo-ong** [comment]
A bit late to the game but @kanishka84  + @adekola , It looks like you're missing a "pm." before your "environment.productinfo" 

It should be "pm.environment.get("productInfo").

**Comment by victorregoz** [comment]
> @prad9 Stringifying should work.
> 
> `postman.setEnvironmentVariable("myArrayObjectVariable", JSON.stringify(response.myArrayObject));`
> 
> and in request 2,
> 
> ```
> {
> "myArrayObjectFromVariable": {{myArrayObjectVariable}}  //double-quotes not needed as it'll be replaced by an object
> }
> ```

I see many people asking the same question, how to save the ARRAY. regardless, people keep answering this with a stringify. why?? I need the array, the reason is that afterwards, I want to make a different request, each one with one array element. The problem is that when you call back this stringify from your globals/enviroment variables, it becomes really hard to iterate since the "stringify" object where you supposedly have to store the array is actually a string, not an array.
