### ISSUE TITLE
Feature: Seach for environment

### ISSUE THREAD

**Issue by Silverbug** [a85/POSTMan-Chrome-Extension#1585]
It would be great if you could search for an environment from the environment drop down at the top right of the screen. 

I currently have over 50 different environments I make use of (and this is growing rapidly) and scrolling through the list to find the one im after can be time consuming. Being able to do a quick inline search with real-time list filtering would speed up getting to the right environment. (see attached screenshot)

![postman-search](https://cloud.githubusercontent.com/assets/1179037/11492502/4aabe5c4-9853-11e5-843f-b0cac7c5c137.png)

**Comment by aditikul** [comment]
Hi! Thanks for reporting this. Totally makes sense and we are working on an update to manage environments in an easier way.

**Comment by a85** [comment]
This feature is available now in Postman!
