### ISSUE TITLE
Don't attempt parsing 204

### ISSUE THREAD

**Issue by elado** [a85/POSTMan-Chrome-Extension#1586]
When getting a 204 with `Content-Length: 0 / Content-Type: application/json` Postman attempts to parse the JSON and shows an error.

![image](https://cloud.githubusercontent.com/assets/51488/11509020/978f96a8-9810-11e5-832a-8350d5f959f5.png)

It shouldn't.

**Comment by abhijitkane** [comment]
There's a `JSON.parse(responseBody);` call in the test script. That will be executed irrespective of the response code. If you want it not to run when the response code is 204, you can check for `responseCode.code` in the test script.

**Comment by elado** [comment]
You are so right. My bad!
