### ISSUE TITLE
Interceptor causes 100% cpu usage and hang

### ISSUE THREAD

**Issue by jscheel** [a85/POSTMan-Chrome-Extension#1587]
Turning on interceptor causes the postman app to completely hang. Running on OSX 10.9.

**Comment by abhijitkane** [comment]
What versions of Postman and the Interceptor are you running? Can you try disabling and re-enabling the Interceptor from chrome://extensions/?

Also, does the CPU jump to 100% as soon as you turn on the Interceptor?

**Comment by jscheel** [comment]
Postman 3.2.2
Postman Interceptor 0.2.13

I'll toggle and let you know if that helps. Seems to happen after a few requests in chrome have occurred.

**Comment by abhijitkane** [comment]
If you're not using Interceptor to stream requests into Postman, I'd suggest clicking on the Interceptor icon in Chrome, and setting the slider to 'Off'.

You'll still be able to use the Interceptor in Postman to send requests.

**Comment by jscheel** [comment]
Yep, I was using it to capture my authenticated requests though.

**Comment by jscheel** [comment]
Actually, now, I don't have interceptor running at all, and just opening postman results in 100% cpu.

**Comment by abhijitkane** [comment]
Can you open the DevTools (http://blog.getpostman.com/2015/06/13/debugging-postman-requests/) and see if there's anything unusual in the console?

**Comment by jscheel** [comment]
Ok, I did a cpu profile, and I think it might have been IndexDB. I deleted the database and reloaded the app, and it runs fine.

**Comment by a85** [comment]
@shamasis @numaanashraf insights?

**Comment by shamasis** [comment]
Seems like https://code.google.com/p/chromium/issues/detail?id=365189 - but not sure if the patch has gone out to latest Chrome yet.

**Comment by a85** [comment]
Seems to have been fixed by Chrome. Will re-open if someone reports this again.
