### ISSUE TITLE
Code Generation not switching languages with OData url

### ISSUE THREAD

**Issue by paulsperanza** [a85/POSTMan-Chrome-Extension#1590]
Using Windows 10

Version 3.2.2 (packaged)
OS: win
Architecture: x86-32
Native client architecture: x86-64

When I switch languages from the drop down the code does not change.

I get this validation error 

field: "data.url"
message: "must be uri format"
value: "http://localhost:46455/api/listlibraryitems?$filter=Type eq 'Language'"

It is because my url is an OData call

**Comment by abhijitkane** [comment]
The code generation library we're using (https://github.com/Mashape/httpsnippet) doesn't seem to support URLs with spaces.

Does this URL work for you - `http://localhost:46455/api/listlibraryitems?$filter=Type%20eq%20'Language'` ?

**Comment by abhijitkane** [comment]
@paulsperanza Can you confirm this fixed in v3.2.8?

**Comment by paulsperanza** [comment]
Yes it is generates the code now.
