### ISSUE TITLE
Edit request closes when all request description selected

### ISSUE THREAD

**Issue by jakubhalun** [a85/POSTMan-Chrome-Extension#1591]
Request edition window closes in the moment when all of request description text gets selected. The same problem occurred for me on two different systems with different Chrome installations. The Chrome version I use here is 46.0.2490.86.

The problem does not occur always. Sometimes few tries are needed to achieve the effect. Like in the linked video, when it occurred with second try:
https://youtu.be/ic0qm62-7yw

**Comment by BorigTheDwarf** [comment]
I have been able to reproduce this consistently by highlighting the text and then moving the mouse outside of the popup window before I "unclick". If you highlight all of the text but keep the mouse within the bounds of the window the windows does not close.

**Comment by abhijitkane** [comment]
Bootstrap seems to detect the click event outside the modal as a trigger to close the modal, even if the click was to end a mouse drag. @a85 - the new app should fix this.
