### ISSUE TITLE
postman-jetpacks is removing escape characters leading to bad request.

### ISSUE THREAD

**Issue by sridhar1982** [a85/POSTMan-Chrome-Extension#1592]
my response contains the following string

```
{
    "hash": "W/\"eyJwcm9maWxlRVRhZyI6IjAxMDY4M2NjMTViOTYyNTY2NjBkYjgyZDk0YjFlZDI4IiwiZGlzcGxheU5hbWVFVGFnIjoiNjFjNWQyMjhmYTc2OWI0MGY4MDgzYWIyMjAwYzA2MzEifQ==\""
}
```

I do the following in tests

```
var data = JSON.parse(responseBody);
postman.setEnvironmentVariable("hash", data.hash);
```

I see the value that is being set as 

```
W/"eyJwcm9maWxlRVRhZyI6IjRiNDBhMGVkOGE5NzNmZjRkMDFkOWY1MTJkYTdmNzcwIiwiZGlzcGxheU5hbWVFVGFnIjoiOWRmZGNhOGQyOGU5MDQ3ZDM3M2M3NzRmMWE0MThkZTcifQ=="
```

NOTE: the missing "\", third character from beginning and the end.

**Comment by abhijitkane** [comment]
`"W/\"eyJ` in JSON represents this string: `W/"tyJ`. The backslash is meant to escape the `"`.
The value set in the globals is correct. If you want to include the backslash in the actual string, use `"W/\\\"eyJ`
