### ISSUE TITLE
Feature Request: Implement GFM Syntax

### ISSUE THREAD

**Issue by mm-gmbd** [a85/POSTMan-Chrome-Extension#1593]
The [https://www.getpostman.com/all_features](Postman feature list) includes "Markdown support for request descriptions" under _Collection_. However, it think it has caught some by surprise (me included), that it is just basic Markdown support rather than for [Github Flavored Markdown](https://help.github.com/articles/github-flavored-markdown/).

This should satisfy issue #1125 (at least), and I would think be somewhat quick to implement with a renderer that supports GFM (I know the Atom editor has a markdown previewer that supports GFM, so that could be one place to start).

**Comment by a85** [comment]
We need to use a new Markdown library.

@abhijitkane Status on this?

**Comment by abhijitkane** [comment]
@a85 Haven't done anything about this yet. Will switch to the one in the documenter.

**Comment by vkaegis** [comment]
Hey, looks like we missed closing this issue. Postman supports complete GFM now.
