### ISSUE TITLE
Random header value not updated correctly if firing requests rapidly

### ISSUE THREAD

**Issue by mstaalesen** [a85/POSTMan-Chrome-Extension#1595]
In my requests I am sending a header value that is random generated. I've noticed that If i send the values rapidly (several per second) with postman, the value is not updated and the previous value is used.

Samplecode / explanation of the issue:

``` javascript
postman.setEnvironmentVariable("exampleHeaderValue", Date.now() + Math.random().toString(36).substring(1));
console.log(postman.getEnvironmentVariable("exampleHeaderValue"))
```

This will give me something similar to the following in the Console.log:

```
1449433554263.cp3duek5ndi2uik9
1449433554884.58jrvpn89wt2csor
1449433554959.1w8zqypptjp58kt9
1449433555177.gqy4jb4oshxe0zfr
1449433555945.0wnmb7ge8pz257b9
```

But looking in request logfile of my application I've seen that some of those values would all be the same, like this:

```
1449433554263.cp3duek5ndi2uik9
1449433554884.58jrvpn89wt2csor
1449433554884.58jrvpn89wt2csor
1449433554884.58jrvpn89wt2csor
1449433555945.0wnmb7ge8pz257b9
```

So for 3 of the requests it did not update the header value that it sent to the server. I also verified that this was not a bug in my application by using Wireshark. The log there shows the exact same behavior. 

If I don't click Send too many times, it will work as intended. And seeing as the log itself was updated with new values per click I think this is a bug.

**Comment by a85** [comment]
@mstaalesen Is this still happening?

**Comment by mstaalesen** [comment]
Yes, I was able to reproduce it last week. (in the chrome app).

**Comment by prashantagarwal** [comment]
@mstaalesen Were you able to reproduce this on any of our native app as well ?

**Comment by mstaalesen** [comment]
@prashantagarwal Not able to reproduce right now, but that might be because every time i send a request it takes 1-3 seconds for the response to be shown. Even though the request itself took 5ms or less. Postman is too sluggish at the moment to confirm that this is solved or not :\
