### ISSUE TITLE
X-FirePHP-Version header added to all outgoing requests.

### ISSUE THREAD

**Issue by raptium** [a85/POSTMan-Chrome-Extension#1596]
I've installed Postman Interceptor Chrome extension and all my outgoing HTTP requests include `X-FirePHP-Version: 0.0.6` in the header.

What is this for?

**Comment by abhijitkane** [comment]
Do you see the header when you make a GET request to http://echo.getpostman.com/get as well?

**Comment by raptium** [comment]
Yes. 

I have to disable Postman Interceptor extension AND RESTART Chrome to make the header disappear.

``` json
{
  "args": {},
  "headers": {
    "host": "echo.getpostman.com",
    "cache-control": "max-age=0",
    "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8",
    "x-firephp-version": "0.0.6",
    "upgrade-insecure-requests": "1",
    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.73 Safari/537.36",
    "accept-encoding": "gzip, deflate, sdch",
    "accept-language": "zh",
    "cookie": "REMOVED"
  },
  "url": "http://echo.getpostman.com/get"
}
```

**Comment by abhijitkane** [comment]
My guess is that another extension is adding the header. When you send the request through the Interceptor, any other installed extension will also be able to add headers. The header should disappear if you disable all extensions except the Interceptor.

**Comment by raptium** [comment]
I've disabled all extensions except the Interceptor, and the header still presents.

`X-FirePHP-Version: 0.0.6` also appears in request dumps referred in the following issues:
#1157 #1441 

So I don't think this is my own problem.

**Comment by raptium** [comment]
I've located the code adding the header in `devtool.js` of the Interceptor. 
This js file is loaded when Chrome devtool is open, therefore the header appears only if devtool panel is open.

**Comment by abhijitkane** [comment]
Got it. Thanks for reporting this. We'll push a fix for this soon.

**Comment by abhijitkane** [comment]
@raptium v0.2.14 has this fix.
