### ISSUE TITLE
Viewing a saved response deletes all request headers

### ISSUE THREAD

**Issue by JamesMessinger** [a85/POSTMan-Chrome-Extension#1597]
This bug is reproducable in the Chrome app and the Mac app.
#### Step 1 - Create a request with at least one HTTP header, and save it to a collection

<img width="740" alt="step 1" src="https://cloud.githubusercontent.com/assets/3453903/11698266/59bf7a4a-9e83-11e5-9d0c-438e045c54b2.png">

---
#### Step 2 - Send the request, and save the response

<img width="746" alt="step 2" src="https://cloud.githubusercontent.com/assets/3453903/11698300/822ebd2e-9e83-11e5-961d-c33bc8dd0911.png">

---
#### Step 3 - Click the saved response link. Notice that all request headers get deleted, and the orange "dirty" dot appears

<img width="742" alt="step 3" src="https://cloud.githubusercontent.com/assets/3453903/11698321/99e24c06-9e83-11e5-949c-1243ad29bd11.png">

**Comment by abhijitkane** [comment]
Thanks for reporting this. Will push a fix by tomorrow.

**Comment by JamesMessinger** [comment]
Thanks, man
