### ISSUE TITLE
Pressing ENTER when saving a response causes full app reload

### ISSUE THREAD

**Issue by JamesMessinger** [a85/POSTMan-Chrome-Extension#1598]
This bug is reproducable on the Mac app (v3.2.2), but **not** on the Chrome app.

When saving a request, when the focus is on the "name" textbox, pressing ENTER on the keyboard triggers the "save" button.  On the Chrome app, it works fine :+1: , but on the Mac app, the ENTER keypress **also** triggers a full-page refresh, which causes the app to reload. :-1: 

<img width="262" alt="screen shot 2015-12-09 at 3 22 44 pm" src="https://cloud.githubusercontent.com/assets/3453903/11699503/3ca9ebf0-9e8a-11e5-94d7-06dbd654ba9a.png">

**Comment by abhijitkane** [comment]
Fixed in the latest version.
