### ISSUE TITLE
Feature request: pluggable collection sharing system

### ISSUE THREAD

**Issue by who** [a85/POSTMan-Chrome-Extension#1599]
Currently, if I wish to share collections with teammates, I have to export the text-based collection file and email/host it somewhere that my team can access. We do not use the Postman cloud-hosted collection sharing, as some of the collections contain sensitive information. I understand that Postman emphasizes  encrypting collection data that it stores, but this still requires me to trust Postman's security protocols, which is a liability.

I propose a solution: 
1. Open source the API that is used to share collections. (Do you have a Swagger spec for this API?)
2. Allow users to define and select custom collection repositories in the Postman tool. These custom repositories would implement the collection API.

Here's a quick mockup:

![](http://i.imgur.com/5AwsMPO.png)

**Comment by evanbr** [comment]
I agree with Who.  This would make sharing among our team much more straight forward without the risk of trusting our sensitive data in the hands of an external company.  Please consider this feature!

**Comment by bugratari** [comment]
This would be a very useful feature for secure collaboration. 
Please consider!

**Comment by SamvelRaja** [comment]
We do have the postman pro feature for team collaboration. Kindly go through it [here](https://www.getpostman.com/docs/postman/team_library/sharing)
