### ISSUE TITLE
Test Runner Feature: Runner can handle dynamically generated tests

### ISSUE THREAD

**Issue by cdanielsen** [a85/POSTMan-Chrome-Extension#1600]
#### Context

I use the test runner to send a request many times with micro variations on the request body with the data file feature/templating features.  While this works fine, I'd like to be able to run dynamically generated tests for each iteration, based on what I expect to happen with each variant request body.
#### Setup

Postman v3.2.2
Windows VM running on Mac OSX El Capitan
Chrome version 47.0.2526.73 m

```
**Request (dumbed down/generalized but qualitatively the same)**
URI:  localhost/api/endpoint (POST)
Request Body:
{
    "Name": {{Name}},
    "Age": {{Age}},
    "Id": {{$guid}}
}

**"datafile.json" Contents**
[
  {
    "TestCase": "ValidRequestReturns200",
    "Assertion": "responseCode.code === 200",
    "Name": "Bob",
    "Age": 12, 
  },
  {
    "TestCase": "MissingNameReturns400",
    "Assertion": "responseCode.code === 400",
    "Name": null,
    "Age": 12, 
  },
  {
    "TestCase": "MissingAgeReturns400",
    "Assertion": "responseCode.code === 400",
    "Name": "Bob",
    "Age": null, 
  }
]

**Tests**
tests[data.TestCase] = eval(data.Assertion);

**Runner Config**
Iterations -> 3
Data -> datafile.json
```
### Result

The runner submits three requests with different request bodies successfully, but only the LAST test is recorded in the `TestRun` view (Passed: 1, Failed: 0).  Interestingly, the `Stats : : Overview` view shows all three tests and their accurate results (3 passing), as does the `Stats : : Requests : : =>` view (3 green dots, but only under one "MissingNameReturns400" column).

It seems like the runner was programmed to expect the same static tests for each request; would it be possible to adjust it to interpret each run's test dynamically/append them to the output instead of overwriting?

Any feedback welcome, including if I'm thinking about this poorly.

**Comment by sdnts** [comment]
@cdanielsen We've been working on a redesign of the Runner that addresses your issue. 

The new Runner is on our Canary channel, and you can download it for [OSX](https://dl.pstmn.io/download/channel/canary/osx_64) / Windows ([x86](https://dl.pstmn.io/download/channel/canary/windows_32) or [x64](https://dl.pstmn.io/download/channel/canary/windows_64)) / Linux ([x86](https://dl.pstmn.io/download/channel/canary/linux_32) or [x64](https://dl.pstmn.io/download/channel/canary/linux_32)) / [Chrome](https://chrome.google.com/webstore/detail/postman/loddepljkabcghihdkbkfknabkinanff)

I'd recommend you to join our Slack community [here](https://www.getpostman.com/slack-invite) so you can provide feedback before the runner moves to our stable builds :)

**Comment by cdanielsen** [comment]
@madebysid Thanks! I use the slack channel regularly. Look forward to seeing the updated runner.

**Comment by sdnts** [comment]
@cdanielsen The new Runner is out with our latest release (4.9) on our native apps. Can you update and check if dynamically generated tests behave properly now?

**Comment by cdanielsen** [comment]
Will do!
