### ISSUE TITLE
Getting the dreaded, "Could not move extension directory into profile" error on install.

### ISSUE THREAD

**Issue by kdd21** [a85/POSTMan-Chrome-Extension#1602]
I'm using the latest Chrome browser on Windows 7 Pro.   I've installed other plugins, in fact I have a boatload of them, though have not installed apps before on this system.  Have also tried disabling my Anti Virus program in case that was causing it.  Googling the error on the web, other apps have had this same problem for other people, but the few solutions suggested haven't worked.   Is it possible to manually move the app into the profile, or is there any sort of more manual install I could try?   At this point, I need something to test my new API, and Postman isn't working...

**Comment by abhijitkane** [comment]
That's odd - we haven't had this problem reported before. For a quick-fix, you can install Chrome Canary (https://www.google.com/chrome/browser/canary.html), and try to install Postman there.

We'll work on figuring out why this might have happened.
