### ISSUE TITLE
Unable to test using Postman because of chrome error - "ERR_SSL_FALLBACK_BEYOND_MINIMUM_VERSION"

### ISSUE THREAD

**Issue by akapoor47** [a85/POSTMan-Chrome-Extension#1605]
For my request postman is saying "Could not get any response"

So from postman when I Copy/Paste link to chrome or directly click I am getting below error in Chrome - 

```
SSL server probably obsolete.
ERR_SSL_FALLBACK_BEYOND_MINIMUM_VERSION
```

Same link works fine in other browsers.

MAC OS Version - OS X 10.10.5
Chrome Version - Version 45.0.2454.99 (64-bit)
Postman version - 3.2.2

@abhijitkane

**Comment by abhijitkane** [comment]
Are you able to make requests to other URLs (on different servers) using Postman?

**Comment by akapoor47** [comment]
Thanks for your reply. 
Yes I am able to and also same collection worked on windows without any issues.

Only difference in my MAC and Windows is Chrome version is 44.0.2403.157 in windows. As far as I understand this eliminates the possibility of having SSL issues in server. Is it something to do with Chrome version in MAC.

**Comment by abhijitkane** [comment]
It's possible Chrome might have disabled support for older SSL versions. That's what a few links seem to indicate - http://venturebeat.com/2014/10/30/google-plans-to-disable-fallback-to-ssl-3-0-in-chrome-39-and-remove-ssl-3-0-completely-in-chrome-40/. We'll look into this and update this thread soon.

**Comment by akapoor47** [comment]
Are there any updates?

**Comment by a85** [comment]
Can you test on Chrome Canary with a copy of Postman?

**Comment by akapoor47** [comment]
@abhijitkane Tried with Canary too, got same error. Any plans to handle this from Postman side?

**Comment by abhijitkane** [comment]
@akapoor47 Is there any publicly-accessible URL that you're able to reproduce the issue with?
