### ISSUE TITLE
Quickly switch variable between common values

### ISSUE THREAD

**Issue by kbhutchinson** [a85/POSTMan-Chrome-Extension#1606]
This is a feature request.

I have a few variables that fall into the following situation: the variable's value is always one of a small list of values, and that list rarely changes.

It would be really nice if there was a way to configure a list of common values for a certain variable that could then be selected easily from within the quickview. That is, in the quickview, next to a variable configured in this way, instead of simply displaying its value, the value would be displayed in a small droplist that could be used to easily change the value to one of the other common values.

Bonus points if the "list of common values" were actually defined separately from the variables, so that I could assign the same list to multiple variables. Then changes to the list would be available to all associated variables.

**Comment by aditikul** [comment]
Thanks for sharing your feedback on this. We are looking into a better management of variables and improving the entire manage env and quickview section. However there is no ETA on this yet. We will update this thread when that happens.

**Comment by a85** [comment]
@kbhutchinson We are working on app wide autocomplete features that should solve your use case. I am closing this issue as it is a subset of the bigger feature.
