### ISSUE TITLE
Login with Google is not working

### ISSUE THREAD

**Issue by gmazzo** [a85/POSTMan-Chrome-Extension#1608]
Since it's updated to version 3, I can't login using my google account:
![image](https://cloud.githubusercontent.com/assets/513566/11767360/cda774cc-a189-11e5-83b3-4a7a19f9461b.png)

Chrome 47.0.2526.80 m
Windows 8.1 Pro x64

**Comment by abhijitkane** [comment]
@gmazzo Can you upgrade to v3.2.5 and check? (chrome://extensions > enable 'Developer Mode' > Update extensions now)
