### ISSUE TITLE
Tabular view option

### ISSUE THREAD

**Issue by gemsuraj** [a85/POSTMan-Chrome-Extension#1609]
Under response formatting options if you can also add 'tabular' view then it will be of great use. 

for reference you can check the view in chrome extention: JSON Prettifier 2.6

![capture](https://cloud.githubusercontent.com/assets/16187340/11775942/5a304754-a269-11e5-92f8-a06f9781fb5d.PNG)

**Comment by a85** [comment]
@aditikul This has been a big feature request from multiple sources over the years.

**Comment by a85** [comment]
Closing as a dup of #519. Will track it there.
