### ISSUE TITLE
Non breaking spaces (&#160;) not displaying in "Pretty view"

### ISSUE THREAD

**Issue by HenrikHL** [a85/POSTMan-Chrome-Extension#1610]
When GETing a result as "application/xml" POSTman seems to trim tags containing a "non-breaking-space" (`&#160;`). It should be mentioned that the encoding is "ISO-8859-1". Is this a feature or is this an error?

POSTman displays my P-tag as:
`<p></p>`
When it should be displayed as:
`<p> </p>`
It does work in "Raw"-view - but since my response is very big (>1MB) the "raw"-view is almost impossible to use...

If this is a feature - is there any way to display actual content of the P-tag in the above example when using the "Pretty"-view? (I have looked in the "Setting" window without success...)

**Comment by abhijitkane** [comment]
@HenrikHL This was a bug with our HTML prettifier. We've fixed this and will include it in the next release. Thanks for reporting this.

**Comment by HenrikHL** [comment]
@abhijitkane Thank you - could you let me know which version it will be fixed in (I am currently using version: Version 3.2.8 (packaged))

**Comment by abhijitkane** [comment]
@HenrikHL Can you confirm this fixed in v.3.2.13?

**Comment by HenrikHL** [comment]
@abhijitkane thank you for fixing this (and sorry for the late reply) - I can confirm it is working now
