### ISSUE TITLE
Feature Request (Collection Runner): Before and After Collection Sripts, or Individual Iterations per Request

### ISSUE THREAD

**Issue by StaticNoiseLog** [a85/POSTMan-Chrome-Extension#1611]
I have a situation where I would like to:

1) first do some initialization work
2) then run a request 100 times
3) finally verify the results of ALL 100 requests in relation to each other (for example: was a running number generated without gaps?)

This is conceptually like JUnit's @BeforeClass and @AfterClass.
I cannot find a way to do this currently in the Collection Runner. Some ideas on how to solve this:

A) Give each Collection a "Pre-request script" and a "Tests" tab. Just like they exist for individual requests.

B) Selection of MULTIPLE collections for running as a "batch". It must be possible to set the number of iterations for each collection individually. I would then simply create three collections. The first one (initialization) and the last one (global test verification) run once. The middle one runs 100 times. The Collection Runner automatically runs all three selected collections in sequence.

C) Specifying the number of iterations not only globally for the collection, but individually per request inside the collection. I would specify 1 iteration for the first request, 100 for the second request and 1 for the last.

I do not have a preference for any of the above suggestions, the sequence is random.

If I am missing something and my requirement can be easily solved with the current version, please feel free to close this feature request. A pointer to a documentation that explains on how to do what I want would be very appreciated in that case.

**Comment by calebrepkes** [comment]
I would like this feature in the future too.

**Comment by cbibbs** [comment]
I need the pre-request as well. The data set for my smoke tests is a single end-point that I'd like to be able to hit and parse the response as an environment variable. That's easy to do now, but I end up hitting that end-point hundreds of times instead of just once. Pretty sloppy.

**Comment by mstaalesen** [comment]
+1

**Comment by anyone-can-test** [comment]
I would like this feature in the future too.

**Comment by sdnts** [comment]
If I understood correctly, what you want to do can be accomplished with `postman.setNextRequest`. ([Docs](https://www.getpostman.com/docs/workflows))

You could have one request (initialization), where you could set environment variables etc and all that stuff. Then move over to the second request and loop over it 100 times (using an environment variable counter maybe), running tests on it to make sure each time the response is as expected. Then, after 100 loops, move over to the third request (clean up), where you could maybe perform more tests / clean up the counter environment variable and all that stuff.

We have been thinking about collection level scripts too, but there is no ETA on that as of now. I'll keep you guys updated here, though.

**Comment by a85** [comment]
This is now available through collection level scripts in the latest apps!

**Comment by MrTact** [comment]
Collection pre-request and test scripts don't actually do what the OP requested. They were looking for  a way to do scripts that run once prior to/after an entire collection run. This would be incredibly useful for, for example, bootstrapping library functions into your test environment, which you probably don't want to do before every single test.
