### ISSUE TITLE
Search not working in docs

### ISSUE THREAD

**Issue by pritianka-zz** [a85/POSTMan-Chrome-Extension#1612]
When I search for a term in the docs search, I see a dropdown of options but when I hit enter it goes away and nothing happens.

**Comment by godfrzero** [comment]
@pritianka Are you hitting enter before selecting a result?

**Comment by pritianka-zz** [comment]
Yes, that's correct

**Comment by godfrzero** [comment]
I'll see if there's a way I can get Swiftype to select the first result by default. :D

**Comment by a85** [comment]
This has been fixed now. Closing the issue. @godfrzero Can you close issues on Github?

**Comment by godfrzero** [comment]
@a85 Nope, lack of permissions :(
