### ISSUE TITLE
Raw: Content-Type: Application/json use wrong type of 'text/plain'

### ISSUE THREAD

**Issue by wesleyolis** [a85/POSTMan-Chrome-Extension#1613]
See the posted items underlined in red are clearly not corrilated with one another.

![postmanbug](https://cloud.githubusercontent.com/assets/2478837/11804995/21e2d616-a311-11e5-9282-510fe3a4d3a6.jpg)

**Comment by a85** [comment]
The JSON dropdown doesn't set the Content-Type in the legacy app. You should switch to the packaged app or the Mac app (www.getpostman.com/apps) where this has been fixed.
