### ISSUE TITLE
How to handle postman redirect url in OAuth2 on server side

### ISSUE THREAD

**Issue by jasollien** [a85/POSTMan-Chrome-Extension#1614]
This is regarding the accessToken POST request sent by postman to my server when authorizing using OAuth2.
Postman sends the following values as form parameters.

code: {{code}}
client_id: {{clientId}}
client_secret: {{clientSecret}}
grant_type: {{grantType}}
redirect_uri: https://www.getpostman.com/oauth2/callback

Postman successfully authorizes my client if I ignore the redirect_uri and return the created accessToken object.

But when instead trying to redirect to the redirect_uri, the access_token field in postman is blank. I have tried setting both access_token and accessToken as query parameters, but no luck.

So the questions are:

1: Why is the redirect_uri passed in to the resource
2: Which parameters should be passed back to the redirect_uri?

**Comment by a85** [comment]
We are reviewing OAuth 2 support right now. OAuth 2 implementations are widely inconsistent and we implemented one that worked with Google, Github etc.

**Comment by harryi3t** [comment]
Hey @jasollien,

If you are trying to implement Oauth2 server side, I would highly recommend reading this RFC https://tools.ietf.org/html/rfc6749

Basically there are 4 types of Oauth2 grant types. Based on the input that you have provided, looks like your are using the `Authorization Code` grant type.
In this, there are 2 calls to be made by the client. First one involves getting the `authorization code` back, which is delivered using a redirection. After getting the code back (I assume this is where you are), you have to make another call passing the credentials and the code. In this call, server has to return the token back. In this call, there is no use of the redirect URL.
So you are right in directly sending the access token.
