### ISSUE TITLE
macro support for URL strings 

### ISSUE THREAD

**Issue by swuphoto** [a85/POSTMan-Chrome-Extension#1615]
Hi,

I have a request to allow customized URL string, e.g. something like

http://www.hostname.com/path/to/request/$(registration_id)/...

If I change the value of registration_id, the request URL needs not to be changed.

**Comment by abhijitkane** [comment]
@swuphoto Check out environments - https://www.getpostman.com/docs/environments
You can use environment variables - `http://www.hostname.com/path/to/request/{{registration_id}}/...` to achieve this. Selecting different environments will replace the value in the URL.
