### ISSUE TITLE
OAuth 2.0 handshake not working

### ISSUE THREAD

**Issue by rlipovski** [a85/POSTMan-Chrome-Extension#1616]
Postman is not able to send a post request to our token endpoint. The request url is looking a little bit weird. I deleted all chrome extensions to be sure they're not interfering somehow. 

![postman_error](https://cloud.githubusercontent.com/assets/11267701/11839904/e56c9974-a3f1-11e5-83e6-a3a1121750ee.JPG)

**Comment by abhijitkane** [comment]
Can you check the Postman version you are on? This should be visible in chrome:/extensions. The latest version is 3.2.5.

**Comment by rlipovski** [comment]
It is the latest version 3.2.5

**Comment by abhijitkane** [comment]
Can you check if there are leading/trailing spaces around your Access Token URL? That would explain this behavior.

**Comment by rlipovski** [comment]
No, the url looks fine. A collegaue of mine has the same postman version which is working.

**Comment by abhijitkane** [comment]
The %20 is the encoding for a space character. I was able to reproduce this by adding a space before my Access Token URL. Can you try copying the URL to a text editor and copying it back to verify that there are no spaces? The font used in the input box doesn't show spaces very clearly.

**Comment by rlipovski** [comment]
We had 3 spaces at the end of the client secret. I removed them in a text editor and now it works fine. Thank you for your help! :) :+1:
