### ISSUE TITLE
Importing using url does not import PATCH method requests

### ISSUE THREAD

**Issue by mverma-va** [a85/POSTMan-Chrome-Extension#1617]
Issue:
I imported collections using the Import->URL option, http://x.x.x.x/swagger/abc-xyz.json
So all the GET, PUT, POST, DELETE requests gets imported except the PATCH method requests.

Is this a bug or broken functionality?

**Comment by a85** [comment]
We'll have to look into this.

**Comment by abhijitkane** [comment]
This is a bug with our swagger converter. It doesn't handle PATCh requests. We've added this to our Todo list.

**Comment by abhijitkane** [comment]
@mverma-va Can you confirm this fixed in 4.1.3?
