### ISSUE TITLE
Cannot configure proxy settings on Mac app 3.2.2

### ISSUE THREAD

**Issue by darcyk** [a85/POSTMan-Chrome-Extension#1619]
No place for hostname on proxy configuration screen to set-up proxy server access
<img width="559" alt="screen shot 2015-12-17 at 16 41 57" src="https://cloud.githubusercontent.com/assets/11159996/11875563/3084e33a-a4dd-11e5-953a-62f2ce81ddfa.png">

**Comment by a85** [comment]
The Mac app acts as the proxy and will be configured to localhost:8080 or your local network IP.

**Comment by darcyk** [comment]
But how to I reconfigure Postman if I want to run it through a network proxy server?

**Comment by guozheng** [comment]
Would be really great if we can add the proxy settings for the Mac app. For the Chrome extension, it can use the Browser proxy setting fine, but not for the Mac app.

**Comment by sworisbreathing** [comment]
Ditto for the native Linux app - there is no documented way to configure the app to work behind an external proxy.

**Comment by sdnts** [comment]
@guozheng @sworisbreathing The native apps honour the system proxy for now. We are working on adding support to configure proxies inside the app itself. Will let you know when it is out.
