### ISSUE TITLE
About Upload File

### ISSUE THREAD

**Issue by aimer1124** [a85/POSTMan-Chrome-Extension#1620]
Postman info:
Version 3.2.6 (packaged)
OS: mac
Architecture: x86-64
Native client architecture: x86-64

This is my Header info
------WebKitFormBoundaryTaM4UUpyxmufv8rH
Content-Disposition: form-data; name="file"; filename="lenin_cat.png"
Content-Type: image/png

------WebKitFormBoundaryTaM4UUpyxmufv8rH
Content-Disposition: form-data; name="fileGroup"

PRODUCT
------WebKitFormBoundaryTaM4UUpyxmufv8rH--

I use interceptor to record the API
<img width="1040" alt="record" src="https://cloud.githubusercontent.com/assets/5865980/11888403/e8a0f3d8-a577-11e5-9484-2fea2ac16641.png">

Then I change the file by postman like this
<img width="1056" alt="changed" src="https://cloud.githubusercontent.com/assets/5865980/11888350/6568c98c-a577-11e5-8106-fa0750f36881.png">
"物理部署图.png" is my local file.

But,it don't work.

**Comment by abhijitkane** [comment]
@aimer1124 Are you able to send the request through any other rest client or cURL?
Also, can you try sending the request with the Interceptor switched off?

**Comment by aimer1124** [comment]
@abhijitkane I switch off interceptor,and it still don't work.The same issue.

And i don't have other tools.

**Comment by abhijitkane** [comment]
@aimer1124 Are you still seeing this?
