### ISSUE TITLE
Closing tab via cmd+w

### ISSUE THREAD

**Issue by mattmcardle** [a85/POSTMan-Chrome-Extension#1622]
Big fan of Postman and use it daily, however the tabbing behaviour really annoys me sometimes.

Conventional behaviour of tabular applications dictates that cmd+t opens a new tab and cmd+w closes a tab. However in postman, cmd+t opens a new tab, but cmd+w closes the entire application. I suspect this is due to it being a chrome app, and is treated as single tab in chrome. If it is the case that it is not possible to implement the cmd+w functionality in the app, then I feel the cmd+t should be removed or at least configurable so that it won't open a new tab.

**Comment by a85** [comment]
Cmd+W closes a tab now in all Postman apps.
