### ISSUE TITLE
Unable to store the response variable in Environment variable

### ISSUE THREAD

**Issue by swathisham** [a85/POSTMan-Chrome-Extension#1623]
Got the answer..Thanks

**Comment by abhijitkane** [comment]
`data` is an array. Use `data[0].DynamicID`.

**Comment by swathisham** [comment]
Still I am getting the value as undefined in the env variable

**Comment by abhijitkane** [comment]
Can you change your test script to the following:

```
var data = JSON.parse(responseBody);
console.log("Data: ", JSON.stringify(data));
console.log("Dynamic ID: ", data[0].DynamicID);
postman.setEnvironmentVariable("DynID", data.DynamicID);
```

You should then be able to open the console (http://blog.getpostman.com/2015/06/13/debugging-postman-requests/). Can you paste the relevant output from the console here?

**Comment by swathisham** [comment]
This issue is resolved
