### ISSUE TITLE
 Long to String Parsing

### ISSUE THREAD

**Issue by swathisham** [a85/POSTMan-Chrome-Extension#1624]
How to parse the env variable to string and use it in the next GET request?

**Comment by swathisham** [comment]
![image](https://cloud.githubusercontent.com/assets/16354764/11966931/c6374f38-a8b3-11e5-8eb7-1c0288f73064.png)

**Comment by abhijitkane** [comment]
Environment variables are already strings. Use `environment.variableName` in your test script to access the variable. I'm not sure what the screenshot is supposed to show. Data is an empty array, and you're trying to access the PhoneID property of an object that doesn't exist.
