### ISSUE TITLE
Data upload  - Support Ticket

### ISSUE THREAD

**Issue by sibalas** [a85/POSTMan-Chrome-Extension#1625]
HI Team,
Need a help.I have  web services for registrations which have 3 separate requests. Step 1,Ste 2 and Step 3 and i need to run them sequentially to create a account .
For each step i need to feed input data(unique values).Please let me know the steps to do this above activity  in Jetpack.

Thanks,
Siva

**Comment by abhijitkane** [comment]
You can use the collection runner for this. Check the blog post at http://blog.getpostman.com/2014/10/28/using-csv-and-json-files-in-the-postman-collection-runner/
