### ISSUE TITLE
Hangs Upon Starting

### ISSUE THREAD

**Issue by glenndarwis** [a85/POSTMan-Chrome-Extension#1626]
Experiencing an issue where, upon startup, Postman hangs and CPU % is at 100 for Google Chrome Helper process. Need to know how to extract collections.

**Comment by abhijitkane** [comment]
@glenndarwis Are you .n the latest version of Postman - 3.2.7? You can check by going to chrome://extensions. If you have Sync enabled, try reinstalling Postman.

The local DB can be found by going to chrome://indexeddb-internals/ and searching for fhbjgbiflinjbdggehcddcbncdddomop. If you can recover the files/folders there, you should be able to recover it later.

**Comment by glenndarwis** [comment]
I do have the latest version installed but I don't have Sync enabled. Big mistake. I couldn't find fhbjgbiflinjbdggehcddcbncdddomop in IndexedDB. Is there another place where the Collections are stored?

**Comment by abhijitkane** [comment]
Can you head to chrome://extensions and search for Postman? Do you see fhbjgbiflinjbdggehcddcbncdddomop or some other ID?

Also, you can follow the steps at http://blog.getpostman.com/2015/06/13/debugging-postman-requests/ and enable DevTools for Postman. Then you'll be able to right click > Inspect element when Postman loads and check for any errors in the console.

**Comment by kryogenic** [comment]
I had this same issue, postman would become unresponsive on startup but if I left it for about 5 minutes it would respond again, though it was noticeably sluggish.

For me all I had to do was clear all the requests in the history tab (use the little garbage can icon) and postman worked like new.

**Comment by dperjar** [comment]
Had same issue, @kryogenic suggestion worked.

**Comment by Arqu** [comment]
Im having the same issue, clearing the history tab does nothing for me. The last few days it was sluggish, now it just hangs. I'm on Mac OS X 10.11 and i notice that in the activity monitor a Chrome Helper Task gobbles up 100% of the CPU. If I kill it postman crashes and it only jumps to 100% if I start postman.

**Comment by dperjar** [comment]
@Arqu If you start it and let it load for ~10 mins or more does it eventually start functioning? That's what I was seeing, perhaps you're seeing a different issue.

**Comment by ckrough** [comment]
I'm having the same issue. Sometimes the chrome app hangs for 5+ minutes on opening. I notice that in these situations, test runs (with the runner) usually fail to execute once it does become responsive.

Postman 3.2.10
Chrome 47.0.2526.111

**Comment by dperjar** [comment]
I don't know if it matters, but I was using the standalone app version of Postman, not a tab in chrome. That shouldn't make much difference I imagine, but could be worth trying if you're in a bind.

**Comment by a85** [comment]
We are continuously improving Postman's performance. Closing this ticket for now.
