### ISSUE TITLE
Hawk authentication port

### ISSUE THREAD

**Issue by prestonvanloon** [a85/POSTMan-Chrome-Extension#1627]
Allow a port to be specified for the hawk authentication header

**Comment by prestonvanloon** [comment]
@czardoz here's a bit more information:

https://github.com/hueniverse/hawk/blob/master/lib/client.js#L92

Ideally, all of those artifact options could be changed. Thanks!

**Comment by czardoz** [comment]
@prestonvanloon thanks! We'll push out a fix the upcoming release :-)

**Comment by prestonvanloon** [comment]
To change the host or port, you have to manipulate the uri. I know that may sound weird, but the use case is that when the request goes through a load balancer, the port could change. In my case, a https request is routed to port 80 after going through a load balancer. The server sees the request came on port 80 but the authorization was signed on port 443 so it rejects the authorization.

**Comment by czardoz** [comment]
@prestonvanloon, ah your use case makes the issue a lot more clearer. 

At first I thought I had missed making a parameter configurable.

The right way to fix this is to configure your load balancer to forward the port to your server using the `X-Forwarded-Port` header, and have the server use this port value when calculating the signature.

**Comment by czardoz** [comment]
Also, you will have to support `X-Forwarded-Proto` too, in all probability :)

**Comment by czardoz** [comment]
Closing this issue, since no changes are required in Postman.

**Comment by danielo515** [comment]
@prestonvanloon as it is true that you can configure your load balancer and/or server better, there are situations where this is not possible, and even not desirable.
I don't see why could not you accept an optional parameter indicating the port that should be used for calculating the mac. 
If you don't want to make this configurable in an easy manner, at least allow the more advanced users to customize this on the pre-request script.

 Regards
