### ISSUE TITLE
File type parameters don't save their values.

### ISSUE THREAD

**Issue by AliSepehri** [a85/POSTMan-Chrome-Extension#1629]
The parameters with file type don't save their values and this cause problems in test `Runner`.

![post](https://cloud.githubusercontent.com/assets/7887290/12014606/c9c7239a-ad44-11e5-8321-a20c83aad689.png)

**Comment by abhijitkane** [comment]
This is currently a restriction of the Chrome app platform. We cannot save references to files. We're working on a native app where we'll be able to overcome this.

**Comment by abhijitkane** [comment]
Closing as a duplicate of https://github.com/postmanlabs/postman-app-support/issues/1113
