### ISSUE TITLE
Could not complete Oauth2.0 login...

### ISSUE THREAD

**Issue by 3kynox** [a85/POSTMan-Chrome-Extension#1630]
Hello Folks,

I set past week a OAuth v2 authentification with Symfony and REST API and everything was working great:
- Client creation using Symfony console
- Manual token generation using that client
- Accessing my REST resources throught this token
- POSTMAN was accessing my resources too correctly once logged with OAuth2.0

Since I merged with my team mate, manually accessing my resources works, but not with POSTMAN where I get the error : 

> Could not complete Oauth2.0 login...

Anyway, after looking a little of what could be wrong, I decided to go back in my last working branch and retry using POSTMAN to authenticate with ... failure results again. I checked also database data but still don't work for a dark reason. I insist on the fact manual commands works correctly.
- **Token generation :** [http://my_local_vhost/app_dev.php/oauth/v2/token?client_id=CLIENT_ID&client_secret=CLIENT_PASSPHRASE&grant_type=client_credentials](http://my_local_vhost/app_dev.php/oauth/v2/token?client_id=CLIENT_ID&client_secret=CLIENT_PASSPHRASE&grant_type=client_credentials)
- **Auth :** [http://my_local_vhost/app_dev.php/oauth/v2/auth?client_id=CLIENT_ID&response_type=token&redirect_uri=https://www.getpostman.com/oauth2/callback](http://my_local_vhost/app_dev.php/oauth/v2/auth?client_id=CLIENT_ID&response_type=token&redirect_uri=https://www.getpostman.com/oauth2/callback)
- **Accessing resource :** [http://my_local_vhost/app_dev.php/api/dossiers?access_token=MY_GENERATED_TOKEN](http://my_local_vhost/app_dev.php/api/dossiers?access_token=MY_GENERATED_TOKEN)

Now if it's possible to get some help, maybe by having a more detailed error message or ways to test further, I would appreciate it.

Thanks anyway !

Regards.

3KyNoX.

**Comment by abhijitkane** [comment]
Since the server is on localhost, you'll need to check the `Request access token locally` option near the `Get access token` button. 
You should then see a popup window when you click the button, and a saved access token when you complete the OAuth2 flow.

**Comment by 3kynox** [comment]
That option is already selected, same results.

When it was working before, forgetting that option was generating **_result:failed**_ after the window popped up and allow button was selected. When option is selected the result was successful.

Now, since it don't work anymore, I don't have any pop-up window that appear (like before) and it throw error "Could not complete Oauth2.0 login" after few seconds. It doesn't matter _Request access token locally_ is selected or not.

**Comment by abhijitkane** [comment]
Can you check the console for any errors? (Details at http://blog.getpostman.com/2015/06/13/debugging-postman-requests/)

Also, what version of Postman are you on? You can check by going to `chrome://extensions`.

**Comment by 3kynox** [comment]
POSTMAN version is 3.2.8.

I checked console quickly before leaving office:

``` js
Unchecked runtime.lastError while running identity.launchWebAuthFlow: Authorization page could not be loaded.
    at Backbone.Model.extend.openLoginFlow (chrome-extension://fhbjgbiflinjbdggehcddcbncdddomop/js/requester.js:70418:24)
    at Backbone.Model.extend.startAuthorization (chrome-extension://fhbjgbiflinjbdggehcddcbncdddomop/js/requester.js:59346:26)
    at c (chrome-extension://fhbjgbiflinjbdggehcddcbncdddomop/js/libs/backbone-min.js:1:2045)
    at a.Events.trigger (chrome-extension://fhbjgbiflinjbdggehcddcbncdddomop/js/libs/backbone-min.js:1:1350)
    at HTMLAnchorElement.<anonymous> (chrome-extension://fhbjgbiflinjbdggehcddcbncdddomop/js/requester.js:60358:20)
    at HTMLAnchorElement.m.event.dispatch (chrome-extension://fhbjgbiflinjbdggehcddcbncdddomop/js/libs/jquery.min.js:3:8549)
    at HTMLAnchorElement.r.handle (chrome-extension://fhbjgbiflinjbdggehcddcbncdddomop/js/libs/jquery.min.js:3:5252)
```

However auth url adress set looks like ok and be the same in POSTMAN than in my manual tests.

I look more further console when back at home.

Thanks for way to check errors.

Regards.

**Comment by abhijitkane** [comment]
If you copy the contents of the Authorization URL and paste them in your Chrome address bar, do you see the login page?

**Comment by 3kynox** [comment]
Yes sir... Not exactly finally, as it asks a client id:

![screen_1](http://i.imgur.com/ZWijpLU.png)

If I give the client id, login show up : 

![screen_2](http://i.imgur.com/kQH9Sjh.png)

After logging successful, I got the aprove / deny buttons : 

![screen_3](http://i.imgur.com/Oq0yyWX.png)

**Comment by abhijitkane** [comment]
Have you prefixed the Authorization URL with `http://`?

**Comment by 3kynox** [comment]
Yup!

![screen_4](http://i.imgur.com/u2ffvwz.png)

**Comment by abhijitkane** [comment]
If there's no client entry in your database, can you try downloading Chrome Canary (https://www.google.com/chrome/browser/canary.html) and try installing Postman there? There might be some state cached in the Chrome sandbox, which is hard to get rid of at the moment.

**Comment by 3kynox** [comment]
Good Morning, doing this ! :)

**Comment by 3kynox** [comment]
Sadly, I get no changes.

I double-checked to launch the correct POSTMAN (using Canary) and close normal Chrome browser : 

![screen_5](http://i.imgur.com/p8q2HhT.png)

**Comment by abhijitkane** [comment]
Is your internet enabled? Even if the OAuth2 server is hosted locally, Postman will need to contact getpostman.com to start the OAuth flow.

Also, you could enter the Authorization URL as `https://github.com/login/oauth/authorize`, and Access Token URL as `https://github.com/login/oauth/access_token`, and dummy values for Client ID and Client Secret, and see if the Github login page shows up.

**Comment by 3kynox** [comment]
Yes, net is up (local server is on the same machine I'm using right now) and github showing login window using dummy values and auth / access_token github url.

**Comment by abhijitkane** [comment]
Can you verify that there are no trailing or leading spaces when you enter the Auth/Access token URLs?

Also, you can try setting the Auth URL to `http://courtier-web-symfony-rest-api/CRM/app_dev.php/oauth/v2/auth` and see if the 'Client not found' page shows up.

**Comment by 3kynox** [comment]
Checked if there is any space, there's none.

Auth URL in chrome browser still asks for Client if not given;
Inside postman while removing client_credentials, same result, still display Could not complete ... and throw console js error about auth page.

**Comment by 3kynox** [comment]
Ready for any help & test purposes.

**Comment by Oleksandr-Tokmakov** [comment]
Hi guys. I have the same issue using Azure Active Directory. Postman just shows "Could not complete OAuth2.0 login" and in console:

```
Unchecked runtime.lastError while running identity.launchWebAuthFlow: Authorization page could not be loaded.
    at Backbone.Model.extend.openLoginFlow (chrome-extension://fhbjgbiflinjbdggehcddcbncdddomop/js/requester.js:70690:24)
    at Backbone.Model.extend.startAuthorization (chrome-extension://fhbjgbiflinjbdggehcddcbncdddomop/js/requester.js:59502:28)
    at c (chrome-extension://fhbjgbiflinjbdggehcddcbncdddomop/js/libs/backbone-min.js:1:2045)
    at a.Events.trigger (chrome-extension://fhbjgbiflinjbdggehcddcbncdddomop/js/libs/backbone-min.js:1:1350)
    at HTMLAnchorElement.<anonymous> (chrome-extension://fhbjgbiflinjbdggehcddcbncdddomop/js/requester.js:60574:20)
    at HTMLAnchorElement.m.event.dispatch (chrome-extension://fhbjgbiflinjbdggehcddcbncdddomop/js/libs/jquery.min.js:3:8549)
    at HTMLAnchorElement.r.handle (chrome-extension://fhbjgbiflinjbdggehcddcbncdddomop/js/libs/jquery.min.js:3:5252)
```

Is it related to that bug or it's my configuration?

**Comment by abhijitkane** [comment]
@Olex What's the Authorization URL that you are using? Can you ensure that there are no leading/trailing spaces in the URL?

**Comment by Oleksandr-Tokmakov** [comment]
Authorization URL - https://login.microsoftonline.com/{my_tenant_id}/oauth2/authorize
Access Token URL - https://login.microsoftonline.com/{my_tenant_id}/oauth2/token

**Comment by Oleksandr-Tokmakov** [comment]
I have solved my issue. In my case I just added resource to Authorization URL:
https://login.microsoftonline.com/{my_tenant_id}/oauth2/authorize?resource={resource_id}

**Comment by netsensei** [comment]
I stumbled on the exact same issue. For future reference, here's a solution.

For each client you add in your Symfony app, you need to set a callback URL for OAuth to work. In the case of POSTman, this callback URL is https://www.getpostman.com/oauth2/callback

Once I configured it on the Symfony side, OAuth started to work.

See: https://github.com/dropbox/dropbox-js/issues/200

**Comment by chenxizhang** [comment]
i meet the same issue @abhijitkane  please take a look

**Comment by maheshambiga** [comment]
I encountered the same issue. However, after adding the following as **scope** it started working. 

https://www.googleapis.com/auth/userinfo.email

Because the client id is created for specific scope.

**Comment by Hack-N-Coded** [comment]
Hello, I have the same problem here. Anybody help?

**Comment by testing-88** [comment]
Hello I have the same issue , any help please ?

**Comment by truonghongtrieu** [comment]
For anyone who comes across this issue, I got the issue resolved by using `https://` , instead of `http://` in the **Access Token URL** field:

<img width="646" alt="Screen Shot 2020-07-14 at 3 02 33 pm" src="https://user-images.githubusercontent.com/12783443/87394931-0d52ce00-c5e3-11ea-85b4-dbd291c0baba.png">
