### ISSUE TITLE
How to compare the env variable and the value in the json response?

### ISSUE THREAD

**Issue by swathisham** [a85/POSTMan-Chrome-Extension#1631]
I want to compare the env variable and a value in the json response.If its not matching it should show an error.

eg: if( environment.varname != response.datavalue)
{
Print or show the test is failed
}

**Comment by elssar** [comment]
Hi @swathisham 

This is how you can test whether a response value matches an environment variable

```
var response = JSON.parse(responseBody);

tests['varname matches datavalue'] = environment["varname"] == response.datavalue;
```

For more on testing in Postman, you can checkout the [documentation](http://www.getpostman.com/docs/writing_tests)
