### ISSUE TITLE
How to retrieve the  value from Nested JSON array?

### ISSUE THREAD

**Issue by swathisham** [a85/POSTMan-Chrome-Extension#1632]
I want to get the value of each EmailID 
```json
[
  {
    "LIJ": "uuuuu480559",
    "Addresses": null,
    "Emails": [
      {
        "EmailID": 2546403,
        "EmailAddress": "testemail@test.com"
      }
    ]
  },
  {
    "LIJ": "mmmm9-42c324c71bb0",
     "Addresses": null,
    "Emails": [
      {
        "EmailID": 2546403,
        "IsDoNotEmail": true,
        "IsLogin": true,
        "EmailAddress": "testemail@test.com"
      },
      {
        "EmailID": 950651,
        "IsDoNotEmail": false,
        "EmailAddress": "abhg.cotter@test.com"
      }
    ]
  }
]
```

**Comment by elssar** [comment]
Hi @swathisham 

I'm guessing you receive this json in the response body.
To get a list of all the email id's returned in the response, you need to add this in your test script

```
var response = JSON.parse(responseBody),
    emailIds = [];

response.forEach(function (obj) {
    obj.Emails.forEach(function (email) {
        emailIds.push(email.EmailID);
    });
});
```

All the `EmailID`'s will be in the array `emailIds`

**Comment by swathisham** [comment]
thank you

**Comment by purnimashanti** [comment]
HI, I WANT TO GET THE VALUE OF FIRST ID.   57ee34ac280000776b0c8b70
{
  "_links": {
    "self": {
      "href": "/self-assessment/4000029889/2016-17/unearned-incomes/57e268ea84000034027579f5/benefits"
    }
  },
  "_embedded": {
    "benefits": [
      {
        "_links": {
          "self": {
            "href": "/self-assessment/4000029889/2016-17/unearned-incomes/57e268ea84000034027579f5/benefits/57ee34ac280000776b0c8b70"
          }
        },
        "id": "57ee34ac280000776b0c8b70",
        "type": "StatePension",
        "amount": 1000,
        "taxDeduction": 400
      },
      {
        "_links": {
          "self": {
            "href": "/self-assessment/4000029889/2016-17/unearned-incomes/57e268ea84000034027579f5/benefits/57ee34ac280000776b0c8b71"
          }
        },
        "id": "57ee34ac280000776b0c8b71",
        "type": "StatePension",
        "amount": 1000,
        "taxDeduction": 400
      },
      {
        "_links": {
          "self": {
            "href": "/self-assessment/4000029889/2016-17/unearned-incomes/57e268ea84000034027579f5/benefits/57ee34ac280000776b0c8b72"
          }
        },
        "id": "57ee34ac280000776b0c8b72",
        "type": "StatePension",
        "amount": 1000,
        "taxDeduction": 400
      },
      {
        "_links": {
          "self": {
            "href": "/self-assessment/4000029889/2016-17/unearned-incomes/57e268ea84000034027579f5/benefits/57ee34ac280000776b0c8b73"
          }
        },
        "id": "57ee34ac280000776b0c8b73",
        "type": "StatePension",
        "amount": 1000,
        "taxDeduction": 400
      },
      {
        "_links": {
          "self": {
            "href": "/self-assessment/4000029889/2016-17/unearned-incomes/57e268ea84000034027579f5/benefits/57ee34ac280000776b0c8b74"
          }
        },
        "id": "57ee34ac280000776b0c8b74",
        "type": "StatePension",
        "amount": 1000,
        "taxDeduction": 400
      }
    ]
  }
}

**Comment by mighty98** [comment]
Guys.. In  this example can someone please help me know how to store email ids of a specific LIJ.
In this example i need to store email ids coming under "LIJ": "mmmm9-42c324c71bb0" alone and not from the whole response

**Comment by Vegapa** [comment]
i want to get the all the values for the brand from the below JSON, How do i get it from postman tool
[
    {
        "brand": "Suncorp",
        "productType": "NPR",
        "productSystemID": "1109890",
        "productSystemPartyID": "09821347"
    },
    {
        "brand": "Suncorp",
        "productType": "OBP",
        "productSystemID": "3456345",
        "productSystemPartyID": "5185644251"
    },
    {
        "brand": "AAMI",
        "productType": "NPR",
        "productSystemID": "P9086754",
        "productSystemPartyID": "1509872364"
    },
    {
        "brand": "GIO",
        "productType": "SUP",
        "productSystemID": "P657832043",
        "productSystemPartyID": "09821347"
    }
]

**Comment by ameersabith** [comment]
someone please explain its answer????

**Comment by ujjalroy1985** [comment]
{
    "inventory": [
        {
            "siteName": "Default",
            "uuid": "89dae40e-9702-4bb3-9d3d-ea4bdc33ea5d",
            "devices": [
                {
                    "cards": [
                        {
                            "uuid": "3404c0e3-3eb7-47fb-a62e-e261374999c1",
                            "name": "10GBE-1STR",
                            "ports": [
                                {
                                    "uuid": "623ddb79-7155-4199-814c-0c76ffefc70a",
                                    "name": "PORT",
                                    "position": 1,
                                    "alias": null
                                }
                            ],
                            "position": 6,
                            "cards": []
                        },
                        {
                            "uuid": "06f19746-8104-40d0-ac96-b0c3bcdf6daf",
                            "name": "10GBE-1STR",
                            "ports": [
                                {
                                    "uuid": "886b477e-a07d-4ffb-a84f-f3ac59b9c091",
                                    "name": "PORT",
                                    "position": 1,
                                    "alias": null
                                }
                            ],
                            "position": 5,
                            "cards": []
                        },
                        {
                            "uuid": "24a8f01d-8258-4f57-8168-4d68d5fe5fd9",
                            "name": "UVRX-4S",
                            "ports": [
                                {
                                    "uuid": "a2c06c6f-5a59-47d7-9f2d-b699bd1a7ed8",
                                    "name": "PORT",
                                    "position": 2,
                                    "alias": null
                                },
                                {
                                    "uuid": "8571e9bd-5ee7-4f20-8ffd-b6c37840ba17",
                                    "name": "PORT",
                                    "position": 1,
                                    "alias": null
                                },
                                {
                                    "uuid": "5b4442ff-6b49-454b-8b82-daa3d0eb2845",
                                    "name": "PORT",
                                    "position": 4,
                                    "alias": null
                                },
                                {
                                    "uuid": "e49efac0-1770-4c6f-bee1-48dd06c6b3ec",
                                    "name": "PORT",
                                    "position": 3,
                                    "alias": null
                                }
                            ],
                            "position": 2,
                            "cards": []
                        },
                        {
                            "uuid": "27b0dc00-02bf-430f-b91b-cc1e8c721743",
                            "name": "1GBE-2STR",
                            "ports": [
                                {
                                    "uuid": "7fd79b71-a7f6-44dc-bf9f-59933e54fd58",
                                    "name": "PORT",
                                    "position": 2,
                                    "alias": null
                                },
                                {
                                    "uuid": "f578fd3c-9f7b-4a9e-8c4e-d283dcef9fce",
                                    "name": "PORT",
                                    "position": 1,
                                    "alias": null
                                }
                            ],
                            "position": 1,
                            "cards": []
                        },
                        {
                            "uuid": "2e23b828-2dca-45b0-b674-41253229beda",
                            "name": "1GBE-2S",
                            "ports": [
                                {
                                    "uuid": "bdf3ffd9-d476-440d-9181-dc1aa0bfe749",
                                    "name": "PORT",
                                    "position": 2,
                                    "alias": null
                                },
                                {
                                    "uuid": "d8cc8506-8333-4c9e-a39f-bcb61c5d2f93",
                                    "name": "PORT",
                                    "position": 1,
                                    "alias": null
                                }
                            ],
                            "position": 4,
                            "cards": []
                        }
                    ],
                    "supervisors": [
                        {
                            "uuid": "050a2fe8-e67b-4f40-a0e2-8fff05146924",
                            "name": "CBS(N)",
                            "position": 7
                        }
                    ],
                    "ports": [],
                    "numberOfRouteTemplates": 0,
                    "uuid": "31eb17c0-ea53-4b6f-a3c0-4e3d86b962dc",
                    "name": "CBS(N)",
                    "modelName": "MD8000SX",
                    "rackPosition": null,
                    "numberOfAlarms": null,
                    "unManaged": false,
                    "rackUnits": null,
                    "pingEnabled": true,
                    "assignedRackUuid": "89dae40e-9702-4bb3-9d3d-ea4bdc33ea5d",
                    "brandName": "Medialinks",
                    "ipAddress": null,
                    "isReachable": true
                }
            ],
            "longitude": null,
            "lattitude": null
        }
    ]
}

From this response how can i capture the value of uuid= 623ddb79-7155-4199-814c-0c76ffefc70a

**Comment by pjamgithub** [comment]
Why is this issue closed?  I don't see a solution?

**Comment by mytestingithub** [comment]
@Vegapa ,@pjamgithub

Looks like thats not complete Json response body,  assuming above response body it will be like this

Here is the code, add this in test window
--------------------------------------------------------
var jsonData = JSON.parse(responseBody);
for(var i=0; i<jsonData.brand.length; i++)
{
   postman.setGlobalVariable("VariableName"+[i], jsonData.brand[i]);   
}

-----------------------
output will be 
VariableName0=Suncorp
VariableName1=Suncorp
VariableName2=AAMI
VariableName3=GIO

**Comment by ArunSNambiar** [comment]
[
    {
        "client_code": 29,
        "known_as": null,
        "title": "Ms",
        "forename": "Audrey",
        "surname": "Murphy",
        "date_of_birth": "1972-04-19T00:00:00Z",
        "gender": "Female",
        "has_photo": false
    },
    {
        "client_code": 40456,
        "known_as": null,
        "title": "Dr",
        "forename": "Arun",
        "surname": "Nambiar",
        "date_of_birth": null,
        "gender": "",
        "has_photo": false
.
.
.
    }
]

This is the response from a postman. I want to identify the 'client_code' of a client which is having its forname='Arun' from the response. How Can I find it.. 
I tried by using json path finder but each time when new client gets created, the index varies.  Please
help. Trying for many days.
@here anybody..please 

@mytestingithub

**Comment by arlemi** [comment]
@ArunSNambiar Please ask this question on the community forum: https://community.postman.com/

**Comment by Faiz1201** [comment]
`[
{
"gender": "male",
"name": "adi"
},
{
"gender": "female",
"name": "lisa"
},
{
"gender": "male",
"name": "michael"
},
{
"gender": "female",
"name": "michele"
}
]`

How to count the length by filtering only count on gender male. Please help.

**Comment by arlemi** [comment]
Since these are not feature requests or bugs, please direct these questions to [our community forum](https://community.postman.com/). I'll lock this thread for now. :)
