### ISSUE TITLE
Environments variables show as errors in raw JSON(application/json) body

### ISSUE THREAD

**Issue by milesje** [a85/POSTMan-Chrome-Extension#1633]
{
    "method": "search",
    "searchParams": {
        "name": {{searchName}},
        "username": {{searchUsername}},
        "date": {{searchDate}}
    }
}

This shows errors on lines 4 & 5
Line 4:
Expected a string and instead saw {.
Expected ':' and instead saw 'searchName'.
Expected a JSON value.

Line 5:
Expected a string and instead saw {.
Expected ':' and instead saw 'searchName'.
Expected a JSON value.
Expected '(end)' and instead saw ','.

**Comment by abhijitkane** [comment]
The errors are due to the text editor not recognising this as valid JSON. Once the variables are replaced, it'll be valid JSON, but that won't show in the text editor. We'll need to update the library to allow `{{..}}` as a string value.

**Comment by 360disrupt** [comment]
Better would be if the `{{}}` is replaced before the body is evaluated. So one can see immediately if e.g. a env variable is missing/invalid.

**Comment by csegyud** [comment]
FYI, enclosing the environment variable placeholder in double quotes solved the problem for me. 
e.g.: `"name": "{{searchName}}",`
(I use Postman v4.10.5 on Windows x64.)
