### ISSUE TITLE
UX bug in Add to Collection feature

### ISSUE THREAD

**Issue by AliSepehri** [a85/POSTMan-Chrome-Extension#1635]
##### Version

```
Version 3.2.8 (packaged)
OS: linux
Architecture: x86-64
Native client architecture: x86-64
```
##### Problem

َ1. Assume that I have a request in my collection and I click on `Add to collection` and I select a path to save the new request:
![add to collection](https://cloud.githubusercontent.com/assets/7887290/12041362/fa4aa270-ae85-11e5-8984-a5c06cf96e8b.png)
2. New request is `selected` in left menu but main section doesn't change to new request.

I and all of my friends have problem with this UX of postman because usually we change wrong request instead of the new request.

**Comment by abhijitkane** [comment]
I'm not able to reproduce this.
I have a request called `r1` saved in a collection `c1`, and have it opened in the main section. When I click 'Add to collection', and save it in a new collection with name `r1-new`, the name in the main section (and the name of the tab) change to `r1-new`. Are you seeing different behaviour?

**Comment by AliSepehri** [comment]
@abhijitkane I and my friends always had this issue. Apparently it is resolved in recent versions. Thank you :)
