### ISSUE TITLE
PUT with Form Data cannot get the value on server side

### ISSUE THREAD

**Issue by stefensuhat** [a85/POSTMan-Chrome-Extension#1638]
Hi,

I'm using postman with PUT method and Form Data type. 

But I can't get the value result send from postman at server. When I change to post it working perfectly.

```
        Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

    ----WebKitFormBoundary7MA4YWxkTrZu0gW
    Content-Disposition: form-data; name="email"

    abc@abc.com
    ----WebKitFormBoundary7MA4YWxkTrZu0gW
    Content-Disposition: form-data; name="password"

    123456
    ----WebKitFormBoundary7MA4YWxkTrZu0gW
    Content-Disposition: form-data; name="password_confirmation"

    123456
    ----WebKitFormBoundary7MA4YWxkTrZu0gW
    Content-Disposition: form-data; name="facebook"

    example
    ----WebKitFormBoundary7MA4YWxkTrZu0gW
    Content-Disposition: form-data; name="twitter"

    example2
    ----WebKitFormBoundary7MA4YWxkTrZu0gW
    Content-Disposition: form-data; name="instagram"

    example3
    ----WebKitFormBoundary7MA4YWxkTrZu0gW
    Content-Disposition: form-data; name="website"

    xample3.com
    ----WebKitFormBoundary7MA4YWxkTrZu0gW
    Content-Disposition: form-data; name="cover"; filename="hosts"
    Content-Type: 


    ----WebKitFormBoundary7MA4YWxkTrZu0gW
```

I'm using Laravel on serverside and try to var_dump the request. But it always empty.

If I change the form data to form-urlencoded it works perfectly but it can't upload a file.

I only have Authorization at my header.

Is it a bug? 

Thanks

**Comment by abhijitkane** [comment]
We haven't had any issues reported with this. Are you able to send PUT requests successfully through cURL?

**Comment by mvelebit** [comment]
For all still seeking help, this is not related to Postman, Laravel has this weird behaviour which **still** hasn't been fixed, send a request with an HTTP POST method, but set a _method PUT flag in order to access your FormData.

**Comment by denitsa-cm** [comment]
@mvelebit even if i add `_method PUT` as part of the form-data - I still cannot access my data on the request. Comes out as `null` (e.g. $request->input('some_key')). Have you encountered this?

**Comment by MohammedAnwar2** [comment]
same problem with me , is there any solution ...?
