### ISSUE TITLE
Embedded videos should not play at all

### ISSUE THREAD

**Issue by octurion** [a85/POSTMan-Chrome-Extension#1639]
Steps to reproduce:
1. Perform a GET request on http://www.rickandmortyadventuresall100years.com/
2. Wait a few seconds (for the video to load in the background)

What happens:
- You can listen to the video's sound (and it's not possible to stop it and/or mute the sound)

Additional information:
- Only tested on Ubuntu 14.04 (with Chromium)

**Comment by abhijitkane** [comment]
Thanks for reporting this. We have a 'preview' mode where you can view the web page. That starts loading even if you're not on the 'preview' tab. We'll fix this in an upcoming release.

**Comment by numaanashraf** [comment]
@octurion This has been fixed in 4.0+ versions.
