### ISSUE TITLE
Feature Request - Change log/version control of API's

### ISSUE THREAD

**Issue by sagiavinash** [a85/POSTMan-Chrome-Extension#1640]
As API's change due to rapid development of features or refactoring. keeping track of changes is tough. Ability to have a timeline of changes would be great. since its version control, git integration would be great instead of building it from scratch for postman.

**Comment by sobtiankit** [comment]
@sagiavinash point well taken. this is something we are actively working on and will be releasing at some point early Q1 this year. Will keep you posted!

**Comment by sagiavinash** [comment]
@sobtiankit awesome to hear that. looking forward to it

**Comment by a85** [comment]
These are available through Postman Pro now. Postman can track version changes and also export to Github etc.
