### ISSUE TITLE
Body Tab of response: take up full height

### ISSUE THREAD

**Issue by luveti** [a85/POSTMan-Chrome-Extension#1642]
Could you guys add a "Expand" button to the body tab? So that when I scroll down it doesn't start scrolling the bottom area before the top area is completely scrolled up. It doesn't feel as intuitive as it could be for long responses, and I find myself moving the mouse over to the side to see more of the response at once. 

Here's a gyazo mp4 of what I mean: https://i.gyazo.com/4a2dd65f6450e355939e88c184b4e01a.mp4

The issue is easily resolved if I move my mouse to the top of the "top area", which you can see in the beginning of the video, but more often than not my mouse gets caught in the response area and scrolls it instead (seen in the second half of the video).

**Comment by aditikul** [comment]
@luveti This should be fixed now. Let me know if otherwise. Do check out the native Mac app and Windows app too. Thanks for reporting.
