### ISSUE TITLE
Runner - data variables in XML POST Body

### ISSUE THREAD

**Issue by pauleck** [a85/POSTMan-Chrome-Extension#1643]
Hi

I'm posting XML to a web service.  I would like to use Runner to send multiple requests using a datafile.  The {{VAR}} syntax works great for JSON but doesn't seem to for XML?  Is this possible?

(Great product by the way!)
Thanks
Paul

**Comment by pawanrawal** [comment]
Hi Pauleck

Thanks for writing in. I would require a bit more information from you on this to help you.

Can you please tell me what is the format of your data file ? Do you mean that data variables work for you when you are sending a POST request with content-type `application/json` and not when the content type is `application/xml` ?

Thanks

**Comment by pauleck** [comment]
Thanks for the reply.

We are posting XML to a service, so content-type is application/xml.  We
want to paramaterize the requests but {{VAR}} doesn't seem to work for XML
but works great for JSON.

Thanks
Paul

**Comment by pawanrawal** [comment]
Hi Pauleck , I have verified this and have not been able to reproduce the issue. The `{{var}}` syntax does work for `application/xml` POST body. Could you please send a mail to help@getpostman.com with the data file and the collection file you are trying to use in the runner so that we can debug this further for you ?

Thanks

**Comment by nickyadvokaat** [comment]
Hey @pawanrawal 

I had some issues with this too. I might help to know that Postman cannot deal with double quotes (") in XML from the imported .csv file. These will be ignored which results in invalid XML data in the body.

I solved this by replacing all double quotes in the XML with single quotes ('). (Which is valid in XML)
