### ISSUE TITLE
Environment variables being parsed as HTML entities

### ISSUE THREAD

**Issue by mpurdon** [a85/POSTMan-Chrome-Extension#1644]
When adding a variable to the environment, it appears to parse `&#9` as a horizontal tab when saving so that:

`x_q=26@jbn-8col3mk&#9a_5t4bkq91x6o=)lvc8(*1^=@^ku5`

is changed to (note the space in the middle):

`x_q=26@jbn-8col3mk   a_5t4bkq91x6o=)lvc8(*1^=@^ku5`

**Comment by abhijitkane** [comment]
@mpurdon Can you confirm this fixed in the latest version of the app?

**Comment by mpurdon** [comment]
Confirmed that this bug is now resolved in the latest version of the app. Thanks!
