### ISSUE TITLE
Mac App Beta: GET request stuck in perpetual Loading state on El Capitan

### ISSUE THREAD

**Issue by VMTrooper** [a85/POSTMan-Chrome-Extension#1645]
Hello Team Postmanlabs,

I am trying to make a simple GET request with the beta app for Mac. However, it is stuck in a perpetual "Loading..." state.

Both curl and Postman Chrome app make the call and get the response in seconds or less. Is there maybe a security setting or something that needs to be changed in El Capitan for the Postman Mac App to work properly?

**Comment by abhijitkane** [comment]
@VMTrooper Can you check the console for any errors - View > Toggle DevTools?
There should be a console tab in the DevTools window. Any errors thrown while sending the request will be listed there.

**Comment by VMTrooper** [comment]
@abhijitkane I tried opening the Console as you suggested.  I didn't see any errors.  Only a warning.  Here are the entries that were displayed after I sent the GET request:

jQuery loaded. $=function (a,b){return new m.fn.init(a,b)}, jQuery=function (a,b){return new m.fn.init(a,b)}
requester.js:12215
Download the React DevTools for a better development experience: https://fb.me/react-devtools
requester.js:14204
Warning: require('react/addons') is deprecated. Access using require('react-addons-{addon}') instead.warning @ requester.js:14204
requester.js:525 Waiting for settins..

**Comment by abhijitkane** [comment]
Not sure why this is happening. Can you try re-downloading the app from here - https://www.getpostman.com/apps?

**Comment by VMTrooper** [comment]
I tried completely removing the app
- /Users/vmtrooper/Library/Application Support/Postman
- /Applications/Postman.app

Then, I re-installed. The result is still the same. My GET request hangs. I'm not doing anything unique, and again, cURL and the Postman Chrome app both work fine.

**Comment by abhijitkane** [comment]
Can you try running the binary from the command line? `open ../Postman.app/Contents/MacOS/Postman`

Any errors in the background process show show up in the terminal.

**Comment by VMTrooper** [comment]
Unfortunately, there are no errors on the command line either.

**Comment by rcchen** [comment]
This is happening to me as well, but I am reasonably certain it has to do with an unsafe localhost cert (trying to hit https://localhost and there's no ability to accept the unsafe cert)

**Comment by abhijitkane** [comment]
@rcchen To add unsafe certs, can you check our blog post at http://blog.getpostman.com/2014/01/28/using-self-signed-certificates-with-postman/? Adding the cert to the OSX keychain should help.

**Comment by rcchen** [comment]
@abhijitkane works now but approach seems rather hacky, would it be possible to support this in a first-class way from Postman? Perhaps a different issue for this, now that it appears this is unrelated to the initial issue

**Comment by VMTrooper** [comment]
It may very well be related since I am running queries against a server with a local host unsafe cert. I will try again after implementing abhijit's suggestion and report of it works

**Comment by numaanashraf** [comment]
@VMTrooper @rcchen We've added an option to disable certificate verification in the Mac App, that should help to run requests against servers with self-signed certificates. You can find the option in `Settings > SSL certificate verification`

**Comment by rcchen** [comment]
Working for me, thanks @numaanashraf!
