### ISSUE TITLE
Postman creating cookies on POST

### ISSUE THREAD

**Issue by mgibeau** [a85/POSTMan-Chrome-Extension#1646]
Hi, running into this issue with Postman.

On POST it's creating extra cookies and setting the path of the request.

This is problematic since the cookie is already set on the root domain, subsequent requests made in the browser are sending both cookies.

I don't think POST response should set cookies unless explicitly told with the Set-Cookie header.

![cookies](https://cloud.githubusercontent.com/assets/1536543/12203900/59d37f2a-b5ff-11e5-8eac-050b498fdeca.png)

Output from curl:

```
curl -H "Content-Type: application/json" -H "Cookie: __REDACTED__=a90e406c1922d146" -X POST -d '{ "id": "1fc5435e-10c5-41d8-83de-7f86994ad134" }' https://__REDACTED__/v2/api/token -vv
*   Trying __REDACTED__...
* Connected to __REDACTED__ (127.0.0.1) port 443 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
* Server certificate: *.__REDACTED__.com
* Server certificate: GlobalSign Domain Validation CA - G2
* Server certificate: GlobalSign Root CA
> POST /v2/api/token HTTP/1.1
> Host: __REDACTED__
> User-Agent: curl/7.43.0
> Accept: */*
> Content-Type: application/json
> Cookie: __REDACTED__=a90e406c1922d146
> Content-Length: 55
>
* upload completely sent off: 55 out of 55 bytes
< HTTP/1.1 200 OK
< Server: nginx/1.6.2
< Date: Fri, 08 Jan 2016 16:32:29 GMT
< Content-Type: application/json
< Transfer-Encoding: chunked
< Connection: keep-alive
< x-powered-by: Undertow
< Vary: Accept-Encoding
<
* Connection #0 to host __REDACTED__ left intact
{"id":"1fc5435e-10c5-41d8-83de-7f86994ad134","value":"ZmY4ZmE1M2QtMGY0NS00ZGY5LTg5M2MtMTY3YWFhN2Y5NjMx"}%
```

**Comment by abhijitkane** [comment]
The Chrome process auto-attaches cookies to any requests Postman sends. To get around this problem, you can enable the Interceptor - http://blog.getpostman.com/2014/11/28/using-the-interceptor-to-read-and-write-cookies/. This way, you'll be able to use the browser's cookie store. You can then clear cookies for this domain from chrome://settings, and be good to go.

**Comment by mgibeau** [comment]
Ok, I'm actually using Interceptor, so my mistake was adding the cookie header. I removed it and it works as expected! Thanks!
