### ISSUE TITLE
"post > body > from-data" is a little confusing for new users

### ISSUE THREAD

**Issue by chiawendt** [a85/POSTMan-Chrome-Extension#1649]
The first time I saw it, I thought "from-data" just means the content-type sent by the every-day html forms, then after a few hours of googling  and packet sniffing I make myself clear about the difference between "multipart/form-data" and "x-www-form-urlencoded". Maybe changing from "form-data" to "multipart/form-data" could alleviate the issue a little?

**Comment by a85** [comment]
We are reviewing the body input editor but it has been around for a while now so we can't change it right away.
