### ISSUE TITLE
Search response: display number of matches

### ISSUE THREAD

**Issue by wzup** [a85/POSTMan-Chrome-Extension#1650]
Hello.

How to enable number of found during search? Now there is no info:

![no number of matches - postman 2016-01-11 10 54 25](https://cloud.githubusercontent.com/assets/3880497/12226129/2e494718-b852-11e5-8108-e752ae6d674e.png)

And this is a screenshot of Sublime Text 3 IDE search, for example:

![number of matches sublime text 2016-01-11 10 56 36](https://cloud.githubusercontent.com/assets/3880497/12226136/441a100e-b852-11e5-870d-f20183194554.png)

This is an essential feature of any search for an app where you work with data.

**Comment by abhijitkane** [comment]
Thanks for pointing this out. The search functionality is currently managed by one of the plugins we're using. We're working on getting this feature in, but have no ETA on this as of now.

**Comment by sun-mir** [comment]
Voting for this too.
Also found https://github.com/postmanlabs/postman-app-support/issues/718

**Comment by bhawna2109** [comment]
@wzup This is now supported in the app.
