### ISSUE TITLE
Question (or bug) - have to manually push Update to see updates in Newman

### ISSUE THREAD

**Issue by bgaillard** [a85/POSTMan-Chrome-Extension#1651]
Hi, 

First I don't know if this issue is the expected behavior or a bug, also this is perhaps a Newman bug. 

Here is my problem, we are working with Newman to do automated testing. We write our assertions in Postman using the Tests tab. 

Each time we update something in the Tests tab and we run Newman manually (in a terminal) our updates are not taken into account.

To make it work we always have to push the "Update" button in the "Upload to getpostman.com" settings of our collection. 

Is this the expected behavior ?

We are using Postman cloud to sync our collecions in our team so we expect the collections to be automatically "Synced". But here it seems their is a difference between "Syncing" and "Uploading" is it the case ?

Thanks in advance for your explanations about this.

**Comment by abhijitkane** [comment]
@bgaillard Yes, for now you'll manually need to Update to run the collection in Newman. Syncing means it has been synced to our servers (for you to access through Postman on any other machine), but the shareable link that you get has to be manually updated. We're working on a always-updated link, but don't have any ETA as of now.

**Comment by hsgfan** [comment]
+1

**Comment by hsgfan** [comment]
@bgaillard: Any update on this? I find it tiresome to update the link in case of changes before we run Newman.

**Comment by a85** [comment]
@hsgfan @bgaillard Synced API collections are available for Postman Cloud plan users. Documentation is available here https://api.getpostman.com/ and http://www.getpostman.com/docs/cloud_api.

**Comment by simonbaudry** [comment]
@a85 We are already using the Cloud plan. 
We are many to work on the same collections but the share link is not updated automatically as explained before by @bgaillard. Only the collection owner can manually do it (he's the only one to have the "share" menu entry).
All the team members have to ask the collection owner to update the share link to get the updates in Newman for our automated tests which is really painfull

**Comment by abhijitkane** [comment]
@simonbaudry The Cloud API that a85 mentioned gives you URLs that the owner does not need to update constantly. Every member of your team gets an API key which can be used to fetch the up-to-date version of the collections. 

You might be referring to the old "www.getpostman.com/collections/1234" style links.

**Comment by a85** [comment]
@simonbaudry Just to add to what @abhijitkane said, you don't need to use the "Share" API links if you are using the Cloud API.

**Comment by simonbaudry** [comment]
@a85 and @abhijitkane my mistake, you are right it works fine with the Cloud API :)

**Comment by bgaillard** [comment]
Hi, as my collegue Simon said we can now run our Newman tests using a collection downloaded with the Cloud API. 

So perhaps this case could be closed (unless you want to leave it opened for users which do not have a Cloud Plan). 

To help a little more here is what we did with Simon in Jenkins. 

``` console
# Postman parameters
POSTMAN_API_KEY=XXXXXXXX
POSTMAN_COLLECTION_UID=XXXXXX-XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX
POSTMAN_COLLECTION_URL=https://api.getpostman.com/collections/${POSTMAN_COLLECTION_UID}?apikey=${POSTMAN_API_KEY}

wget ${POSTMAN_COLLECTION_URL} -O collection.json

COLLECTION_FILE=$WORKSPACE/collection.json
ENVIRONMENT_FILE=$WORKSPACE/my-project/postman/staging.postman_environment
TARGET_DIRECTORY=$WORKSPACE/my-project/target

cd my-project

# Test for the 'users' folder
newman run $COLLECTION_FILE --environment $ENVIRONMENT_FILE --folder users \
       --reporters cli,html,json,junit \
       --reporter-html-export $TARGET_DIRECTORY/html-export-users.html \
       --reporter-json-export $TARGET_DIRECTORY/json-export-users.json \
       --reporter-junit-export $TARGET_DIRECTORY/junit-export-users.xml

...
```

Hope this helps.

**Comment by a85** [comment]
@bgaillard Awesome!

**Comment by rgangal** [comment]
Thanks @a85 @abhijitkane . I was having the same issue and this post really helped :)
