### ISSUE TITLE
Maintain UUIDs on export

### ISSUE THREAD

**Issue by darrylkuhn** [a85/POSTMan-Chrome-Extension#1652]
We're using postman with Jetpacks to perform automated integration/API testing. To do this we export the collection and check it into the projects repo. The issue with this is that currently when we export a collection it appears the UUIDs are changed. This makes it nearly impossible to perform a diff / resolve merge conflicts. To deal with this (and just because it's generally useful) we are using cloud sync however in doing so we have found that tests make their way into master before the code (since the collection changes are instantly sync'd up). These issues are also captured in this [SO thread](http://stackoverflow.com/questions/30437988/how-to-store-postman-collections-in-source-control). What are the chances we could get stable UUIDs? This would make diffing/merging possible so that we can keep collections in our VCS and tie a given set of tests to a specific commit... Thanks,

**Comment by czardoz** [comment]
We will soon start supporting user specified IDs which will not be changed on export, which I think should take care of your use case :)

**Comment by darrylkuhn** [comment]
Great - thanks for the update... any idea on ETA or is it further in the backlog?

**Comment by a85** [comment]
@darrylkuhn Hopefully Feb. We are doing a major re-write of some core components that will making things like maintaining UUIDs possible. We are also working on adding external integrations to Postman Cloud so you can integrate with source control directly without having to export manually.

**Comment by darrylkuhn** [comment]
Awesome - thanks for the update!

**Comment by VasekPurchart** [comment]
Any update on this? Is this coming anytime soon, please? We have almost same issue as described above and since this issue is closed I don't know where to track progress/updates, can you eventually point me somewhere else if this is not the right place, please?
