### ISSUE TITLE
Test runner - set array from json data to request body not happening

### ISSUE THREAD

**Issue by wan54** [a85/POSTMan-Chrome-Extension#1654]
POST API: http://bla/create

in the body type raw of application/json: 

```
{
  "data": "{{dataArray}}"
}
```

json file for test runner:

```
{
  "dataArray": [
    {
      "key1": "1",
      "key2": "2"
    },
    {
      "key1": "11",
      "key2": "12"
    }
  ]
}
```

in the pre-request script:

`postman.setEnvironmentVariable("dataArray", data.dataArray);`

the request fails because the array is not resolved.. the payload sent in the request is

```
{
  "data": "{{dataArray}}"
}
```

instead of 

```
{
  "data": [
    {
      "key1": "1",
      "key2": "2"
    },
    {
      "key1": "11",
      "key2": "12"
    }
  ]
}
```

any specific command to process data array from the json file in the pre-request script?

thanks for your help

**Comment by abhijitkane** [comment]
@wan54 This is not how you use the data file. The file needs a specific format - http://www.getpostman.com/samples/test_data_file.json. The root object has to be an array, with each element being the set of key-value pairs you want in each iteration.

If you don't need different data per iteration, you don't need to use the JSON file. Just enter the payload in the request body itself.

**Comment by windupurnomo** [comment]
I have an issue when using runner and json file contains array. I got error: "Data file format is not right". Here is my json input file:

```
[
	{
		"date": "2018/01/22",
		"customerId": "bb5d68de-c1f2-46c3-bfa1-fc1b2148df61",
		"shopId": "b5764ef3-41a0-47a6-8458-ba94186c7990",
		"products": [
			{"productId": "08eb3f3b-6b07-4246-b426-2b5f655a5493", "quantity": 1}
		]
	},
	{
		"date": "2018/01/21",
		"customerId": "bb5d68de-c1f2-46c3-bfa1-fc1b2148df61",
		"shopId": "b5764ef3-41a0-47a6-8458-ba94186c7990",
		"products": [
			{"productId": "08eb3f3b-6b07-4246-b426-2b5f655a5493", "quantity": 1}
		]
	},
	{
		"date": "2018/01/20",
		"customerId": "bb5d68de-c1f2-46c3-bfa1-fc1b2148df61",
		"shopId": "b5764ef3-41a0-47a6-8458-ba94186c7990",
		"products": [
			{"productId": "08eb3f3b-6b07-4246-b426-2b5f655a5493", "quantity": 1}
		]
	}
]
```

**Comment by sivcan** [comment]
Hi @windupurnomo - You're using the deprecated Chrome App for Postman and I can confirm that the [latest native app for Postman](https://www.getpostman.com/apps) is working perfectly fine with this data file.

I advise you to kindly download the latest native apps for your system. 

Here's the screenshot for the same:
![image](https://user-images.githubusercontent.com/12631777/38764476-7cf8c7a8-3fcd-11e8-907f-5b2fabebbb9b.png)

**Comment by dream891117** [comment]
set environment :
![image](https://user-images.githubusercontent.com/3175825/49265986-5fd38b00-f48f-11e8-9023-dffb18c0d29e.png)
body : 
![image](https://user-images.githubusercontent.com/3175825/49266008-74b01e80-f48f-11e8-97a2-666a793f0484.png) 
runner :
![image](https://user-images.githubusercontent.com/3175825/49266027-885b8500-f48f-11e8-9860-5af133c57cfd.png)

How to use array?

**Comment by sivcan** [comment]
@dream891117 Right now, arrays are not supported
You'll have to stringify your appointment list.
```javascript
pm.environment.set('appointmentArray', JSON.stringify(data.appointment_list));
```

**Comment by jvermach** [comment]
And can you please as well show, how the data source file should look like please (how shall appointment_list be definied?

**Comment by jvermach** [comment]
and especially if I need to send list of objects...

**Comment by jvermach** [comment]
Solution found in: https://community.getpostman.com/t/collection-runner-sending-requests-with-array-of-objects-read-from-data-source-file/4994/4

**Comment by sivcan** [comment]
For people who're going to land up on this issue in the future: 
https://community.getpostman.com/t/sharing-tips-and-tricks-with-others-in-the-postman-community/5123/6?u=sivcan

**Comment by smanjesh** [comment]
It works when I do the following:
1) Set an environment variable where you stringify the incoming array
2) Use the environment variable in the body instead of the source field

For instance, if your input Json looks like following. Note that we have an array field called "benefits"
```
[
  {
      "placeId" : "e3RT",
      "benefits": ["Good place to stay", "Nice eateries around" ]
  },
  {
      "placeId" : "rt4S",
      "benefits": ["Very good neighborhood", "Not much traffic" ]
  }
]
```
In the Pre-request Script tab, add the following line:
`pm.environment.set("env-benefits", JSON.stringify(data.benefits));`

Insert something like this in the body:
```
{
		"placeId": "{{placeId}}",
		"benefits" : {{env-benefits}}
}
```
