### ISSUE TITLE
Curl Snippet - single quotes around URL

### ISSUE THREAD

**Issue by andytaw** [a85/POSTMan-Chrome-Extension#1655]
For example, generating a Curl Code Snippet in Windows:
`curl -X GET -H "Cache-Control: no-cache" -H "Postman-Token: 2cbb78c8-a23e-cbde-7a06-4aaab29e086e" 'http://www.getpostman.com/'`
wraps the URL in single quotes, but other parameters in double quotes.
In Windows (cmd) this results in an error from Curl, which is mildly annoying.

**Comment by czardoz** [comment]
Single quotes around a URL ensure that the URL is not processed by the Shell. What do you think is a better way of handling this in windows?

**Comment by andytaw** [comment]
Apologies if I have disregarded a very good reason for this, but whenever I
generate a Curl snippet all the arguments in the snippet have double-quotes
except the URL. I need to change the single-quotes to double-quotes to make
the snippet work.

**Comment by SamvelRaja** [comment]
@andytaw This has been fixed in versions 4.1+
