### ISSUE TITLE
Pretty formating of response body doesn't remember format when switching between tabs

### ISSUE THREAD

**Issue by pesha** [a85/POSTMan-Chrome-Extension#1656]
If you switch to different tab and then back to previous one then the pretty formatting of response body is set to default HTML. 

Postman version 3.2.9
Chrome version Verze 47.0.2526.106 m
OS Win7

**Comment by abhijitkane** [comment]
@pesha I'm not able to reproduce this. Is this happening each time?
Can you upgrade to 3.2.13 and see if you still face the issue?

**Comment by pesha** [comment]
I'm not sure whether you are checking functionality of main tabs. I meant this tabs (I should have specify them):
![tabs](https://cloud.githubusercontent.com/assets/436475/12576998/f11c7b2c-c417-11e5-8477-c8bcb3e49aaf.jpg)

**Comment by abhijitkane** [comment]
Ah..got it. It won't revert to HTML, but the default preview type for that particular response. If you make a GET request to http://echo.getpostman.com/get, and switch tabs, the response format will revert to JSON. We'll be fixing this in a coming release.

**Comment by atorma** [comment]
Still an issue in Postman 6.1.4. Switching tabs reverts the format to the default for the content type. This makes it a pain to work with apis that respond with a wrong content type (text/html instead of application/json).

**Comment by malith-gammanpila** [comment]
Still having same problem in Postman v6.4.2 "Switching tabs reverts the format to the default for the content type".
