### ISSUE TITLE
UI bug in Chrome Canary

### ISSUE THREAD

**Issue by toomastahves** [a85/POSTMan-Chrome-Extension#1657]
Postman: Version 3.2.9
Chrome Canary Version 49.0.2620.0 canary (64-bit)
OS: Win 10

View appears broken in Chrome Canary. 
Also tried in normal Chrome Version 47.0, works good there.

![canary_bug](https://cloud.githubusercontent.com/assets/7262443/12291819/369fc8d2-b9f2-11e5-9523-ed2a0ef639fe.png)

**Comment by abhijitkane** [comment]
@toomastahves Do you see the issue even after restarting/uninstalling the app?

**Comment by toomastahves** [comment]
Uninstalled and reinstalled app, still same issue.

**Comment by abhijitkane** [comment]
That's odd. Do you see any errors in the console? (http://blog.getpostman.com/2015/06/13/debugging-postman-requests/)

**Comment by toomastahves** [comment]
Yep, error in console.

```
Uncaught TypeError: Failed to execute 'getRandomValues' on 'Crypto': parameter 1 is not of type 'ArrayBufferView'.
```

Maybe its Chrome Canary browser bug. In normal Google Chrome there is no such error, works good there.

![canary_console](https://cloud.githubusercontent.com/assets/7262443/12295270/badfed28-ba08-11e5-8605-8ceeb48aaa66.png)

**Comment by zacechola** [comment]
I can confirm the same for version 49.0.2620.0 canary (64-bit)

**Comment by ZebraFlesh** [comment]
Still seeing this on 49.0.2620.1 (64-bit) on Windows 7 64-bit. Same visual problems and same console output.

**Comment by abhijitkane** [comment]
This seems to be an issue due to the Chrome upgrade. Seems to be working on Chrome 47 but not Chrome 49. We're looking into this and hope to release a fix by today.

**Comment by abhijitkane** [comment]
@ZebraFlesh @zacechola Can you try upgrading to 3.2.10 (chrome://extensions > Enable 'Developer Mode' > Update extensions now) to see if that fixes it?

**Comment by zacechola** [comment]
It is indeed fixed, @abhijitkane. Thanks!
