### ISSUE TITLE
Sync is not working behind a proxy

### ISSUE THREAD

**Issue by anurudda** [a85/POSTMan-Chrome-Extension#1658]
I'm running sync (sync data across devices) behind a network proxy and it is not working. Apparently it's not honoring the global proxy configuration in my system. Login in and upload everything works fine. Only the sync has the issue.
 I'm using 
Ubuntu 14.04 LTS  64bit
Chrome Version 47.0.2526.106 (64-bit)
Postman version 3.2.9

I have also tried restarting and reinstalling postman.

**Comment by mmhy2003** [comment]
I have the same issue, I'm behind corporate proxy and I can't get it to sync despite global proxy settings.

**Comment by rajivverma** [comment]
Same here!

**Comment by sdnts** [comment]
@anurudda @mmhy2003 @rajivverma I've seen some corporate proxies that disable websocket connections. Sync works majorly on WS, can you guys check if this is the problem?

**Comment by rajivverma** [comment]
@madebysid yes you are right, it is a proxy issue. Though the corporate proxy allows the WS at my work place. But the proxy address gets overwritten automatically in windows 10 proxy settings to invalid address I suppose. Check the screen below, if I move the port no. to port no. box and save it, WS works briefly on my machine until something is overwriting the setting back.
![image](https://cloud.githubusercontent.com/assets/19625921/21816170/12eea5d8-d757-11e6-9931-7211d30885f7.png)
