### ISSUE TITLE
Mac Beta freezes on startup, possibly due to sync/update checking

### ISSUE THREAD

**Issue by prashcr** [a85/POSTMan-Chrome-Extension#1659]
Maybe it's the size of my collections and the number of requests/test cases in them, but the Electron app just freezes for about 10s on startup, before becoming usable.
Perfectly reproducible, this happens on every startup.
Have about 200 requests and 250 tests across all my collections.

The Chrome app however, has no such issue.

Using OS X El Capitan 10.11.2

**Comment by abhijitkane** [comment]
@prashcr What version of the app are you using? The latest app version is 3.2.9.1.

**Comment by prashcr** [comment]
Hey, I did a clean uninstall  (didn't check which version) and re-installed the latest one before reading this, and it seems to work fine now.

Thanks!
