### ISSUE TITLE
Layout has somehow been corrupted and I see none of my history.

### ISSUE THREAD

**Issue by tbrentlong** [a85/POSTMan-Chrome-Extension#1661]
The layout when I opened it this morning was showing the sidebar overlaying the main part of the screen, and none of my collections are there.  Was there some sort of change overnight?
![roguepostman](https://cloud.githubusercontent.com/assets/11465123/12309260/901736fa-b9fe-11e5-853e-50edac32fee4.jpg)

**Comment by ZebraFlesh** [comment]
Duplicate of #1657

**Comment by abhijitkane** [comment]
#1657 is solved.
