### ISSUE TITLE
OAuth 2.0 client credentials flow in Postman 3 - get to custom login page but fails. What's missing? 

### ISSUE THREAD

**Issue by Joyce-Stack** [a85/POSTMan-Chrome-Extension#1662]
Hello, 

This is a usability issue really and I'm unclear as how to get around it.  I've once been able to successfully use Postman to make a call to our public API. It uses OAuth 2. I wrote a blog post on it - http://bit.ly/1RQ4ftb - it was all very simple. 

However, I am now trying to use the new updated version to do the same thing and I'm consistently getting that it could not make an access token request as below: 

result → failure
message → Could+not+make+access+token+request

The login screen for our application gets presented but it fails with 401 Unauthorized. What step have I missed?  

Thank you.

**Comment by abhijitkane** [comment]
What version of Postman are you on? (visible in chrome://extensions)

Could you try checking the "Request access token locally" option? If it doesn't work, you can check the error logs in the Console tab of the Developer Tools window (http://blog.getpostman.com/2015/06/13/debugging-postman-requests/). 

If there are no errors, can you mail a set of sample credentials to help@getpostman.com? We'll try to reproduce this at our end.

**Comment by Joyce-Stack** [comment]
Thank you. 

I've sent details to the help email address.  The version of Postman I'm using is 3.2.9.

**Comment by Joyce-Stack** [comment]
Whitespace issue in the token URL.

**Comment by abhijitkane** [comment]
We'll handle leading/trailing spaces better in the next release. Thanks for pointing this out.

**Comment by olee** [comment]
Was there any update on this?
I encountered the same problem.
Is there any fix on this?

EDIT: I got it working by using that local-mode.
