### ISSUE TITLE
Uninstalling Interceptor plugin doesn't turn off interceptor toggle in Postman

### ISSUE THREAD

**Issue by pulkitsethi** [a85/POSTMan-Chrome-Extension#1664]
I had installed interceptor plugin, but then uninstalled it. When I went to postman, none of my calls to my local application server were working. It is not apparent that the reason for this failure is b/c interceptor is still turned on, but the plugin is uninstalled. When I switched the interceptor toggle off in Postman, everything started working again. That took me a while to realize what was going on.

Expected Behavior: Postman checks if interceptor has been uninstalled, or when you uninstall, it turns off/tells you to turn off interceptor on postman.

**Comment by abhijitkane** [comment]
Thanks for reporting this. We'll push a fix for this soon.
