### ISSUE TITLE
PostMan Mac App - Refused to set unsafe header

### ISSUE THREAD

**Issue by krokofant** [a85/POSTMan-Chrome-Extension#1668]
The Mac App for Postman refuses to set the User-Agent. Because this is a Electron based app I was able to override the User-Agent via devtools but it's no pretty solution.

Because this is an Electron app, couldn't the unsafe-limit be overridden?

```
Refused to set unsafe header "User-Agent"
Backbone.Model.extend.send  @   requester.js:3768
Backbone.Model.extend.onSend    @   requester.js:2497
c   @   backbone-min.js:1
a.Events.trigger    @   backbone-min.js:1
(anonymous function)    @   requester.js:50983
(anonymous function)    @   requester.js:4865
(anonymous function)    @   backbone-min.js:1
(anonymous function)    @   lodash.min.js:41
c   @   backbone-min.js:1
a.Events.trigger    @   backbone-min.js:1
(anonymous function)
```

**Comment by abhijitkane** [comment]
The XHR standard blocks this (https://www.w3.org/TR/XMLHttpRequest/#the-setrequestheader%28%29-method). Till we switch to a Node module for sending requests, there doesn't seem to be a way to overcome this.

**Comment by a85** [comment]
Can try this out in Postman Canary now on the Mac: http://blog.getpostman.com/2016/06/14/introducing-postman-runtime-more-power-better-control/
