### ISSUE TITLE
Add GraphQL support

### ISSUE THREAD

**Issue by rayshan** [a85/POSTMan-Chrome-Extension#1669]
Hello,

GraphQL is a query language created by Facebook for describing data requirements on complex application data models. It's frequently used with React and Relay.

References:
http://graphql.org/
IDE: https://github.com/graphql/graphiql

**Comment by tribou** [comment]
I would like to second this issue.  Postman has an opportunity to communicate to an existing GraphQL API using the introspection query and provide auto-complete for queries similar to the existing GraphiQL implementation.  Combined with Postman's existing feature-set of saved queries and environment management, it could make Postman my go-to app for testing during GraphQL API development.

May we get an update as to the consideration of this?

**Comment by a85** [comment]
@tribou We are super interested in extending Postman to things beyond HTTP but have been super swamped with the current workload. :(

**Comment by tribou** [comment]
@a85 I understand, and thank you for the kind response.  A quick clarification... GraphQL can actually communicates with JSON over HTTP using POST calls.  With this being an example GraphQL query:

```
{
  viewer(authToken: "12345") {
    users {
      id
      name
      phone
      status
      createdAt
      updatedAt
    }
  }
}
```

The resulting full example query using `curl` looks like this:

``` sh
curl -XPOST http://localhost:8080/graphql \
  -d '{ "query": "{ viewer(authToken: \"12345\") { users { id name phone status createdAt updatedAt } } }", "variables": null }'
```

Consequently, I'm actually able to use Postman to test and save queries now.  However, the awkward string formatting required to translate the GraphQL query into JSON is what makes it difficult...and provides an opportunity for Postman. 😄

**Comment by a85** [comment]
@tribou Awesome. We'll add this asap.

**Comment by hkgill** [comment]
+1

**Comment by alondahari** [comment]
+1

**Comment by bryantebeek** [comment]
+1

**Comment by daviskoh** [comment]
+1

**Comment by dh94** [comment]
+1

**Comment by a85** [comment]
Sorry about the delay on this folks. This got held up as we have been refactoring parts of the app to enable more modularization. GraphQL is high on our radar overall. I'll update the thread once we have more info to share. Thanks for your patience.

**Comment by DraganKovacevic** [comment]
Are we there yet?

**Comment by ultymike** [comment]
+1

**Comment by BenGale** [comment]
+1

**Comment by cdelgadob** [comment]
+1

**Comment by nithincscubet** [comment]
Can we expect GraphQL file upload support with this feature ?

**Comment by Strutsagget** [comment]
+1

**Comment by atalebagha** [comment]
+1

**Comment by stevenb9** [comment]
+1

**Comment by batjko** [comment]
@nithincscubet I don't think that would make sense, since GraphQL itself has no concept of file uploads yet.

**Comment by tribou** [comment]
@madebysid @numaanashraf @a85 I'd love to get an update on this feature. This issue has been open for a year and a half now; and with the proliferation of GraphQL, I would have expected more progress (or at least more communication).

I think you've got two incredible opportunities for Postman, and you don't need to try to tackle both at once:

1. Support the GraphQL syntax in Postman to send API calls
2. Implement the GraphQL introspection query to provide autocomplete

I would think that item `1` would be more quickly attainable and would actually alleviate most of the pain currently felt when trying to use GraphQL with Postman--just make it easy to type in a GraphQL query and automatically format it into the appropriate JSON for the API call. Item `2` is more for convenience and UX, which would obviously be a huge win and would keep more users in the Postman ecosystem than have them migrate to GraphiQL or similar. However, it doesn't address the current pain like item `1`, so I could understand if item `2` needed to be delayed further.

Please, take a moment to provide us with an update or a link to the current progress.  Thank you!

**Comment by sdnts** [comment]
@tribou This is definitely something we're looking into. I agree that supporting the GraphQL syntax should be quickly doable. 
I'd also suggest looking at out [roadmap](https://trello.com/b/4N7PnHAz/postman-roadmap-for-developers), which we'll update with GraphQL status soon. Thanks for the patience! :)

**Comment by horacehylee** [comment]
+1

**Comment by batjko** [comment]
Just to add inspiration, the way [Insomnia](https://insomnia.rest/blog/introducing-graphql/) does it, is essentially what we're after here.
It even has automatic introspection, so works similarly to GraphiQL (though I haven't been able to make that one work when I briefly tried). But even without that, a simple GraphQL query editor would suffice to start.

![image](https://user-images.githubusercontent.com/7287076/29685364-2d469bf8-890d-11e7-9d19-e7c59b6b9d07.png)

**Comment by webmobiles** [comment]
yes I'm working well with Insomnia, option for variables; auth bearer,  but sync for 5$ monthly,   postman will be paid?

**Comment by consolibyte** [comment]
+1

**Comment by Fohlen** [comment]
This is a crucial tool for every 2017 and 2018 backend engineer. When can we expect that feature to be shipped?

**Comment by cdelgadob** [comment]
Indeed. Specially after Amazon’s native support for GraphQL with AWS AppSync - 
https://aws.amazon.com/es/appsync/

**Comment by Fohlen** [comment]
I was especially referring the trend of serverless architectures because not all of them (erm erm, Lambda!) do ship GraphiQL by themselves.

**Comment by jakubkratina** [comment]
+1

**Comment by cmosboss** [comment]
Any update on this? Insane that this is not a key feature of postman in 2018.

**Comment by a85** [comment]
Everyone,

Thank you for your patience with this feature. We are super excited about GraphQL. Postman is being re-written to operate through a plugin based architecture. This will help us support API design/definition/schema formats (RAML, GraphQL, Swagger - even SOAP) properly and ship updates as soon as versions of these format tick up rather than having to update Postman itself. We want to support schemas as first-class editable entities in Postman so you can update related collections/requests automatically by updating the schema.

Right now we are making some fundamental changes in the code base for performance and stability - this will improve load times, render times as well as sync performance. More updates soon on this thread and on our blog! Lots coming up in 2018!

Abhinav

**Comment by valnub** [comment]
Is there an ETA for this?

Currently we're forced to use Insomnia but we'd much more prefer Postman for automated testing.

**Comment by dashmug** [comment]
I'm using Insomnia for this. But will go back to using Postman once this feature is up.

Make it happen guys!

**Comment by jrichard0725** [comment]
Could really use a postman graph feature. Been holding off on switching my team in hopes this feature will come along soon....not sure how much longer we can afford to wait.

Really need this to come through for our team to stay on Postman...

**Comment by fharper** [comment]
+1

**Comment by mobiustech** [comment]
TIL, postman doesn't support GraphQL. This issue was raised more than 2 years ago...

**Comment by PathToLife** [comment]
Quote from: https://stackoverflow.com/questions/42520663/how-to-send-graphql-query-by-postman
"I think POSTMAN is not made for work naturally with graphql"

Just use: https://insomnia.rest/

POSTMAN is still great though, it's just new protocols and technologies will always happen.
Is the extra development time and increased complexity worth it? ~~~

The UI is pretty complex already imo, learning how to save responses (examples) was a pain.

**Comment by mortik** [comment]
Insomnia is a very good Tool but it lacks a very important feature for me: Tests :) which can also be used to update env vars ^^ and to run complete Collections.

For me it would be enough, as a first step, to have a way to write multiline queries and without a js workaround...

**Comment by joshprice** [comment]
What doesn't seem to have been mentioned yet is the ability to send GraphQL queries as plain text rather than jumping through hoops trying to make it JSON. (You don't get introspection or autocomplete obviously but it's an improvement). Here's how to do it:

> Send a `POST` with a `Content-Type` of `application/graphql` then your body can be a plain text query document (as described here https://graphql.org/learn/serving-over-http/#post-request).

Most GraphQL servers should support this (if not they should).

Some other options worth investigating are:

- https://github.com/OlegIlyenko/graphiql-workspace
- https://github.com/prismagraphql/graphql-playground

For anyone like me who is curious about the status, the Postman support ticket is still listed as "mid term" despite having 72 votes (more might help?).

https://trello.com/c/u4DE4WU8/58-graphql-support

**Comment by macalinao** [comment]
plus one. Insomnia also doesn't support the header preset stuff which is useful for auth tokens in headers.

**Comment by smeijer** [comment]
@macalinao, I'm using auth tokens in headers just fine with Insomnia

**Comment by shahidhk** [comment]
We recently made a tool called graphqurl (https://github.com/hasura/graphqurl) for making GraphQL queries with custom headers etc. It's a CLI that has auto-complete, can open GraphiQL on any endpoint (with support for custom headers), supports subscriptions and can be used as a JS library. Let us know if you find it useful.

`gq https://gentle-anchorage-72051.herokuapp.com/v1alpha1/graphql -i` will open up GraphiQL shown below:
![image](https://user-images.githubusercontent.com/4124733/43960537-f14aa888-9ccf-11e8-88e4-ebbdc615c9d5.png)

**Comment by websitevirtuoso** [comment]
+1

**Comment by mrljdx** [comment]
+1

**Comment by cardosomarcos** [comment]
+1

**Comment by andreas-bergstrom** [comment]
What's the status here? I'd happily support a Kickstarter to get this done. As long as it has the same feature set as Postman for REST, including Tests (which Insomnia lacks).

**Comment by shashikiran797** [comment]
+1

Eagerly waiting for graphql support on postman

**Comment by joelgetaction** [comment]
I would be willing to pay for this ... Any updates or ETA?  :-)

**Comment by cphoover** [comment]
Is this still on the road map??

**Comment by cardosomarcos** [comment]
@cphoover  Yes, it is. You can check the roadmap here: 
https://trello.com/c/u4DE4WU8/58-graphql-support

**Comment by joelgetaction** [comment]
@cardosomarcos thanks for responding.  I took a look at the Trello card but the last activity was August 2017 when it went to "planning" ... That was more than a year ago.

I would like to move my team to a paid Postman plan, however lack of GraphQL support is holding us back.  Any ETA for when this will be done?  We'd rather stick with Postman than switch to another tool, but we really need GraphQL support and I'm hearing this from a lot of other developers as well.  :-)

Thanks!

**Comment by bastos71** [comment]
Any idea of a release date ?

**Comment by rysbilinski** [comment]
+1

**Comment by mehdiraized** [comment]
+1

**Comment by echhung1-zz** [comment]
this is taking a while =(

**Comment by taozhi8833998** [comment]
Any updates on this feature??  I hava to switch to Insomnia for testing graphql api now

**Comment by stedwick** [comment]
Switching to insomnia for now...

**Comment by john-osullivan** [comment]
Postman is much more mature than Insomnia, but I'm working with GraphQL APIs!  Please add the future and take my team's money.

**Comment by chrisneal** [comment]
My team has also switched to Insomnia for GraphQL dev. Frustrating!

**Comment by vicdup** [comment]
Same here, very frustrating...

**Comment by pavel-luhin** [comment]
The same. Any updates or dates?

**Comment by willejs** [comment]
@loopDelicious I see you own the roadmap in Trello... As this is your no.2 most requested features by reactions in github issues, is there a plan to bump this up your product roadmap or address it any time soon? 
https://github.com/postmanlabs/postman-app-support/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+sort%3Areactions

**Comment by Nabellaleen** [comment]
Hey guys, any updates about this feature request ?

This is the second more requested feature : https://github.com/postmanlabs/postman-app-support/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

Maybe you should give a little more attention to it and, at least, answered something ? Anything ? :) Just to help people, teams, to take decisions about their tools, about their plans around the Postman ecosystem.

**Comment by loopDelicious** [comment]
Sorry about the delay folks. Inbuilt support is currently slated for release in Q2. And should have something in our Canary build soon.

As some other people have already mentioned, the latest timing can be referenced on our roadmap: https://trello.com/c/u4DE4WU8, but of course we'll keep everyone here updated as well when it comes out in Canary and then Production.

**Comment by taozhi8833998** [comment]
> Sorry about the delay folks. Inbuilt support is currently slated for release in Q2. And should have something in our Canary build soon.
> 
> As some other people have already mentioned, the latest timing can be referenced on our roadmap: https://trello.com/c/u4DE4WU8, but of course we'll keep everyone here updated as well when it comes out in Canary and then Production.

Keep wating for this feature. Thanks for working on it!!!

**Comment by nixoncode** [comment]
It's 2019 already, Any progress on this?

**Comment by dashmug** [comment]
They said it is slated for release in Q2. Unfortunately, they didn't tell us what year.

**Comment by numaanashraf** [comment]
Thanks for the patience everyone. We are putting the finishing touches on this and making sure that GraphQL requests work consistently in the various individual and team workflows supported by Postman's products, including the Postman App, Newman and Postman Monitors.

Here's a sneak peek of the latest internal build and you can expect the feature to land in Canary in few weeks.

<img width="1428" alt="Screenshot 2019-04-29 at 5 45 17 PM" src="https://user-images.githubusercontent.com/3295568/56895510-e7f1a700-6aa6-11e9-8a76-37513aa8b480.png">

**Comment by nixoncode** [comment]
> Thanks for the patience everyone. We are putting the finishing touches on this and making sure that GraphQL requests work consistently in the various individual and team workflows supported by Postman's products, including the Postman App, Newman and Postman Monitors.
> 
> Here's a sneak peek of the latest internal build and you can expect the feature to land in Canary in few weeks.
> 
> <img alt="Screenshot 2019-04-29 at 5 45 17 PM" width="1428" src="https://user-images.githubusercontent.com/3295568/56895510-e7f1a700-6aa6-11e9-8a76-37513aa8b480.png">

This is actually Pretty Neat, Am excited to see it hit the stable release, Good work so far.

**Comment by Chris533** [comment]
Nice!

**Comment by john-osullivan** [comment]
Huge!! Very excited to help get my team onboarded once this is live 👍

**Comment by dashmug** [comment]
It's Q2 2019! Yehey!

**Comment by joelgetaction** [comment]
@numaanashraf thanks for this!  I was delaying buying a team license for Postman because of its lack of GraphQL support but as soon as this is GA I will go ahead and buy!  :-)

**Comment by dwiyatci** [comment]
I better start learning GraphQL now 😂

**Comment by jronak** [comment]
@codenirvana can you please expedite the release?

**Comment by buddylindsey** [comment]
> Thanks for the patience everyone. We are putting the finishing touches on this and making sure that GraphQL requests work consistently in the various individual and team workflows supported by Postman's products, including the Postman App, Newman and Postman Monitors.
> 
> Here's a sneak peek of the latest internal build and you can expect the feature to land in Canary in few weeks.
> 
> <img alt="Screenshot 2019-04-29 at 5 45 17 PM" width="1428" src="https://user-images.githubusercontent.com/3295568/56895510-e7f1a700-6aa6-11e9-8a76-37513aa8b480.png">

How is that sending data? Is it going to allow for the multipart upload spec? Not having that has been a limitation of other tools. https://github.com/jaydenseric/graphql-multipart-request-spec

**Comment by liaotuo** [comment]
very good!

**Comment by shasti421** [comment]
> Thanks for the patience everyone. We are putting the finishing touches on this and making sure that GraphQL requests work consistently in the various individual and team workflows supported by Postman's products, including the Postman App, Newman and Postman Monitors.
> 
> Here's a sneak peek of the latest internal build and you can expect the feature to land in Canary in few weeks.
> 
> <img alt="Screenshot 2019-04-29 at 5 45 17 PM" width="1428" src="https://user-images.githubusercontent.com/3295568/56895510-e7f1a700-6aa6-11e9-8a76-37513aa8b480.png">

Any update on availability in Canary?

**Comment by a85** [comment]
Folks, we are working on rolling this out to everyone soon. Please check out our blog post about schema support and the general introduction of "APIs" as an abstraction here meanwhile: https://blog.getpostman.com/2019/05/17/postman-7-1-create-apis-directly-within-the-postman-app/

Full GraphQL support looks like this:

<img width="1728" alt="Screenshot 2019-05-18 14 33 07" src="https://user-images.githubusercontent.com/653409/57975231-e4e92880-7979-11e9-8e56-9a846a7fb882.png">

<img width="1728" alt="Screenshot 2019-05-18 14 30 46" src="https://user-images.githubusercontent.com/653409/57975234-f3374480-7979-11e9-90b8-3b6c8711918e.png">

**Comment by kamalaknn** [comment]
Hi everyone,

GraphQL support is now available on the canary channel - [download here](https://www.getpostman.com/downloads/canary)

This version supports

1. Sending GraphQL queries in request body as POST requests
2. Support for GraphQL variables
3. Creating APIs in Postman with GraphQL schema type
4. Query autocompletion integrated with user defined GraphQL schemas, Coming Soon!

Please give it a try and give us your feedback on the tracking thread on our community forum - [here](https://community.getpostman.com/t/graphql-support-in-postman-available-for-early-access-on-canary-channel/5524)

**Comment by tristanMatthias** [comment]
@kamalaknn Thanks so much! This is amazing and much needed.

I'm getting an error when trying to generate collections from a schema.gql file. Thoughts?
![image](https://user-images.githubusercontent.com/2550138/58283642-a2e72a80-7d5d-11e9-9baa-12e3d0d3b25c.png)

**Comment by alfaproject** [comment]
Is there any particular reason you don't support GET requests? I know I can do POST, but some of our saved queries can be cached and therefore can be requested using GET (;

**Comment by kamalaknn** [comment]
Hey @tristanMatthias 

Thanks giving it a try. We are still working on adding support for generating collections from GraphQL schemas - we'll update once they are released.

@alfaproject 

We support sending the GraphQL queries in request bodies for GET(and all methods). Please find the screenshot below.

![Screenshot 2019-05-24 at 11 41 15 AM](https://user-images.githubusercontent.com/8401064/58306582-8f00fe80-7e19-11e9-84cc-f83c2d45d59d.png)

We do not yet support sending GraphQL queries as query parameters. Can you confirm which mechanism you are using?

**Comment by alfaproject** [comment]
Query parameters, so we are able to HTTP cache a full query

**Comment by ljdev1** [comment]
This is great! Thank you!

Quick Question: Will there be GraphQL Schema Docs presented and auto-completion / validation of queries / mutations against the GraphQL Server Schema (not a local schema), like GraphiQL client does?

**Comment by numaanashraf** [comment]
@ljdev1 In our first production release, we'ld have auto-completion of queries & mutations using schemas stored inside APIs in Postman. We are exploring ways to present schema docs and power auto-completion via introspection from server schemas.

**Comment by a85** [comment]
GraphQL support is out in production as part of the 7.2 release. More details to be posted on our blog soon at blog.getpostman.com. Closing this ticket now!

**Comment by galvesribeiro** [comment]
Looking for the blog post. I've made the update but I'm not able to use GraphQL on it yet :(

**Comment by yura3d** [comment]
Thanks for the update.
But in 7.2.0 I don't see 2 important things for GraphQL (or I don't know how to enable them): query check-up and auto-completion for remote GraphQL schemas, like they are made, for example, in Insomnia.
![image](https://user-images.githubusercontent.com/10958696/59553127-3eed0600-8f99-11e9-9b85-5d88496ad867.png)

**Comment by kamalaknn** [comment]
Hey @yura3d 

In Postman, GraphQL autocompletion is available through API schemas. You can find out how to use them [here](https://community.getpostman.com/t/graphql-support-in-postman-available-for-early-access-on-canary-channel/5524/8?u=kamalaknn)

**Comment by yura3d** [comment]
@kamalaknn thanks. But I'm on API development stage and its scheme is very often updated. So, changing the scheme in 2 places (Server and Postman) is not rational solution for me. I will wait for support of introspection, it is really helpful thing in GraphiQL or Insomnia.

**Comment by galvesribeiro** [comment]
@kamalaknn I'm pretty sure that is not what people are looking for. People are looking for replacing GraphiQL/GraphQL Playground with Postman. Forcing people to use a 3rd party thing to get the schema is no sense... 

How difficult is to add a new option on the API to "Import from URL" where people can paste the GraphQL endpoint and it would use introspection to query it?

Also, once the schema is imported, we don't want to remember which fields the schema have... We want to press ctr/cmd+Space and see a list of available fields/operations on that schema based on the scope. Just like we do with the original tools.

Please make those changes asap so postman become usable with graphql...

**Comment by a85** [comment]
@galvesribeiro This is not the final version of the product nor is it trying to replace GraphiQL or other GraphQL tools. I am locking this thread as future feature requests can be filed elsewhere.
