### ISSUE TITLE
 Is it possible to filter transaction log in postman? 

### ISSUE THREAD

**Issue by HRGL** [a85/POSTMan-Chrome-Extension#1672]
```
Is it possible to filter transaction log in postman? by order_commercial_id,product_sku and transaction_type because I would like to see specific order id's and product

Thank you
```

**Comment by abhijitkane** [comment]
@HRGL What do you mean by transaction log? The history items are sortable, as are the requests in a collection. Can you send a screenshot of what you need to sort?

**Comment by HRGL** [comment]
which is related to the Mirakl application TL01 API.
screen shot attached
![tl01 postman](https://cloud.githubusercontent.com/assets/16799374/12455735/a3bb80a8-bf94-11e5-8179-7b341e703963.PNG)

**Comment by abhijitkane** [comment]
You'll need to contact the API Vendor for this info. Postman is a REST Client, and we cannot offer insights into what parameters the API supports.

**Comment by HRGL** [comment]
I first went to them and they replied as below

We are not responsible about Postman Support, we only provide you how to configure it for Mirakl environments.
I advise you to read their documentation or contact their support team : http://www.getpostman.com/support.

Regards,

**Comment by abhijitkane** [comment]
Are you able to achieve this in curl or any other rest client? If yes, we can help you out.
If you want the transaction log for a particular field, you'll need to contact the Mirakl team.

**Comment by HRGL** [comment]
I don't have any idea of curl or any other rest clients which supports mirakl application,please help me on that
thank you

**Comment by abhijitkane** [comment]
You can find documentation for curl here - http://curl.haxx.se/docs/
