### ISSUE TITLE
Remove Accept header unless specified

### ISSUE THREAD

**Issue by g-dx** [a85/POSTMan-Chrome-Extension#1673]
Problem: Cannot send a request _without_ an Accept header.

Background: Currently performing a GET with _no headers set_ using the Postman app on https://www.whatismybrowser.com/detect/what-http-headers-is-my-browser-sending shows the following:

![headers](https://cloud.githubusercontent.com/assets/4189306/12456157/75d942ae-bf96-11e5-89dc-45e43689db98.png)

I understand the Chrome will not allow certain headers to be added, modified or removed before the request is sent (https://developer.chrome.com/extensions/webRequest#life_cycle_footnote) but the Accept header is not one of them.

**Comment by abhijitkane** [comment]
The WebRequest API is different. Accept is added automatically by Chrome.

Browse to `http://httpbin.org`. Open the console (right click > Inspect element).
Enter this in the console: `var xhr = new XMLHttpRequest(); xhr.open("GET","http://httpbin.org/get",true); xhr.send();`
Go to the network tab. You'll see your request, with 'Accept' as one of the request headers.

**Comment by g-dx** [comment]
Are you saying that the Postman Chrome App cannot access the 'chrome.webRequest' API to perform header suppression?

**Comment by abhijitkane** [comment]
That's correct - the API is only available to Chrome extensions, not Chrome apps. The APIs for Chrome Apps are listed here - https://developer.chrome.com/apps/api_index

Postman's Interceptor (http://www.getpostman.com/docs/interceptor_cookies) will be able to use this to block headers, but this feature isn't in our immediate roadmap. We have this in our to-do, but cannot offer  an ETA just yet.

**Comment by g-dx** [comment]
Ok. Thanks for the information.
