### ISSUE TITLE
Postman will not launch, Ubuntu 15.10

### ISSUE THREAD

**Issue by jkahrs595** [a85/POSTMan-Chrome-Extension#1674]
I've used Postman for about a week, but now it won't launch (well, I can't see the window). I'm not sure if Chrome updated, or Postman updated since then.

I can see Postman start up in the Chrome task manager, but can't figure out how to get the GUI to show. Any suggestions? I've tried uninstalling/reinstalling the app with no luck.

**Comment by abhijitkane** [comment]
Any options when you right click on the icon in the dock? @czardoz any Ubuntu-specific tips?

**Comment by jkahrs595** [comment]
I see "Quit", and nothing else. So I can kill the process without going into terminal, but that's about all I can do.

**Comment by jkahrs595** [comment]
Ugh, I got it to work finally. I had to uninstall the app, reboot, start chrome and reinstall the app again.

What a pain!

**Comment by noamhacker** [comment]
did you lose your saved requests/collections, or did those save?

**Comment by kweejee** [comment]
I had this same problem where it stopped launching until I uninstalled, rebooted, then reinstalled.  The console logs would stop showing info after the Google Logout line.

**Comment by a85** [comment]
If you have installation issues, please let us know at help@getpostman.com

**Comment by djgeary** [comment]
Same problem here on with Postman 4.2.1 on Windows 7. I had to reinstall the app and lost all history and collections.

**Comment by domnikl** [comment]
Same problem here with Postman 4.4.1 and Fedora 23
