### ISSUE TITLE
Wadl import not working

### ISSUE THREAD

**Issue by LorandLorincz** [a85/POSTMan-Chrome-Extension#1676]
Hi,

Importing the wadl from pentaho bi-platform doesen't work. I tried import from URL, File and Raw Text.

This is the link to the wadl.
http://javadoc.pentaho.com/bi-platform500/webservice500/application.wadl

Thnaks.

**Comment by abhijitkane** [comment]
You'll need to remove the `wadl:` part. This - http://pastebin.com/raw/Jk3qeWDi - should work. We'll be fixing this bug soon.
