### ISSUE TITLE
Find not working properly?

### ISSUE THREAD

**Issue by czardoz** [a85/POSTMan-Chrome-Extension#1677]
Originally opened by @TimFowle at https://github.com/postmanlabs/newman/issues/317

---

If i perform a search in the results with the latest version of the chrome plugin the search behaves a bit differently to how it used to (from memory):
1. As soon as i type a character it starts to search for that. On long responses this can slow it down greatly as there may be thousands of matches. Im sure it used to wait a little longer so i could type a few characters before it actually searched.
2. If there are multiple results it used to go from one to the next. It now only appears to go to either the first or last entry.

Possibly user error but these appear to be issues.

Thanks

---

**Comment by abhijitkane** [comment]
@TimFowle This appears to be a bug with our search functionality. We'll be pushing a fix for this in the next release.

**Comment by abhijitkane** [comment]
Fixed with v3.2.13.
