### ISSUE TITLE
Feature Request: Count/quantity and indexing for received list of items in response

### ISSUE THREAD

**Issue by sun-mir** [a85/POSTMan-Chrome-Extension#1678]
Here is an example:
<img width="680" alt="count feature in response" src="https://cloud.githubusercontent.com/assets/4091725/12524105/792def12-c163-11e5-956c-d5027acc49d5.png">

Would be extremely useful. Loved Postman client but this feature will make it the best!

**Comment by smwbis** [comment]
+1 This would be an EXTREMELY helpful feature!

**Comment by borbamartin** [comment]
👍 +1 on this one! Really helpful for me!

**Comment by pabloz** [comment]
:+1:

**Comment by diegueus9** [comment]
:+1:

**Comment by fclarat** [comment]
:+1:

**Comment by borbamartin** [comment]
Lots of support on this one @abhijitkane & @a85 !
Do you think it will be possible to include this one on the next update? :)

**Comment by dougludlow** [comment]
👍

**Comment by borbamartin** [comment]
Any updates on this @abhijitkane @a85 ? :) thx

**Comment by sobtiankit** [comment]
Just added this to #2115 

@borbamartin One quick solution for this would be to add this in your test script:

var body = JSON.parse(responseBody);
tests["Posts length is " + body.posts && body.posts.length] = true;

which will show you the array size in the tests tab.

@numaanashraf is this something we can easily add to the response renderer?

**Comment by sdnts** [comment]
Guys, we're working on something very similar to this. Will keep you guys updated on the progress!

**Comment by abrahamduran** [comment]
Any update on this? Seems forgotten :/

**Comment by numaanashraf** [comment]
@AIsaac08, this is on our roadmap. We'll update here when we have an ETA.

**Comment by michaelfrye** [comment]
+1

**Comment by gomnet** [comment]
Do you have any feedback about this request? It would be very appreciate for us to have it available.

Thx in advance.
David.

**Comment by jawinn** [comment]
👍  +1

**Comment by shreyashdholakia** [comment]
👍 +1

**Comment by sudeepto-dutta** [comment]
:+1: +1

**Comment by azariz** [comment]
+1

**Comment by kahneraja** [comment]
lets make this happen!!!

**Comment by marchy** [comment]
Any update on this? Number one gap in Postman for so long. You guys have been doing great things but missing the easy, low-hanging fruit such as this.

Let's get this in the otherwise fantastic product!

**Comment by Magua** [comment]
+1

**Comment by AntoniusGolly** [comment]
Where to put?

var body = JSON.parse(responseBody);
tests["Posts length is " + body.posts && body.posts.length] = true;

Can I execute custom operations on the returned json? E.g. I only want to display the id's of objects that are returned in an JSON array.

[
{ id : 2,
 ..... tons of information
},
{id: 3,
---- tons of information
}
]

I can write a mapper myself, just wanted to ask if there's a callback where I can hook my mapping function.

**Comment by hiasl** [comment]
+1 (and PLEASE bertyhell - don't be so berty)

**Comment by nilsk12** [comment]
Need this so bad

**Comment by mgntrn** [comment]
+1!

**Comment by theholiday** [comment]
+1

**Comment by rodrigolopezguerra** [comment]
+1

**Comment by roman-svystun** [comment]
+1

**Comment by AntoniusGolly** [comment]
Meanwhile, use *Tests* tab to create custom Javascript that's executed on the response. You can write all the funky stuff to your console that you desire. (Adapt the code accordingly + and open Console [Ctrl + Alt + C].)
```
pm.test("return", function () {
    
    var jsonData = pm.response.json();
    
    if(jsonData.length){
        console.log("Found " + jsonData.length + "items:")
        ids = jsonData.map(function(x){
            console.log(
                x.id + " | "  +
                x.created_by.first_name + " | " +
                x.created_by.id + " | " + 
                x.created_by.last_name + " | " +
                x.title.substr(0,10)
             );
            
        });
    }
    
});
```

will result in (example):
```
Found 6 items:
908 | Hero | 132 | Blaster
907 | Spider | 133 | Man
906 | Super | 134 | Man
905 | And | 135 | so forth
904 | Hero | 132 | Blaster
903 | Hero | 132 | Blaster
```

**Comment by supdann** [comment]
+1

**Comment by Sofianio** [comment]
> this is on our roadmap

2 years & still nothing, I'm a bit disapointed :/

**Comment by theholiday** [comment]
Meanwhile I use the following code to count the number of objects in the array that's the response:
```
var jsonData = JSON.parse(responseBody);

pm.test("Array length is: " + jsonData.length, function () {
});
```

**Comment by Sofianio** [comment]
Using tests requires adding the script and customizing it to every Request then checking the count in a different tab ... which isn't fun :/

**Comment by theholiday** [comment]
Sure, but a workaround still.

**Comment by HaoNguyen2409** [comment]
Simple feature with huge utility, don't know why they still don't support this instead of add many features pretty sure 90% users never used.

**Comment by danilotavares** [comment]
+1

**Comment by aronmgv** [comment]
+1 It has been 2 years already LOL.. common :)

**Comment by jhonatasobrinho** [comment]
Please, release this feature soon :(

**Comment by hardcorenik** [comment]
PLEASE COME ON! Implement this feature :)

**Comment by Sofianio** [comment]
Apparently, adding a little "get" & "post" colored tags to the tab bar along with 999 other trivial changes are more important than the count of array children which we actually care about.
... Disappointed

**Comment by abrahamduran** [comment]
What's really funny is how they removed the `Usability` label 😂 
If this is not a good fit to be used, then I don't know what it is.

**Comment by marchy** [comment]
@a85 Abhinav can you PLEASE make this happen?

It's frustrating how such a core feature, which does NOT have high effort associated, can be ignored for so long.

Listen to your damn users man. Seriously.

**Comment by a85** [comment]
@marchy We do listen to our users - which is why the entire Postman team is active on the tracker. What is not possible is personalized attention when there are hundreds of issues. 

While it is easy to see all the people who want a feature, what is not apparent in an issue is the voices of all the people who DON'T want this feature. Adding features comes at a cost: performance, complexity, maintenance cost. When we take up a feature, we are committing to maintaining it through the ENTIRE life of the product. I am surprised actually to see the kind of language in comments here as I'd assume that most people here are software developers who face the same issues in the software  that they work with.

In this for example a key thing to see is that every API in the world does not render JSON. Counting the number of objects has a bazillion connotations depending on response types, what exactly is an array for that format - just to name a few things. We looked at implementing the feature earlier and decided this is better served with either plug-ins or building a data editor that helps us make things more customizable rather than piling on the existing editor - which because of _other_ features is getting slower.

Postman is a product and not a services company to deliver features.

**Comment by Sofianio** [comment]
@a85 
>what is not apparent in an issue is the voices of all the people who DON'T want this feature

Easy, Add toggle in settings disabled by default for "ppl who hate to see array count"

>Counting the number of objects has a bazillion connotations depending on response types...

If it's harder to implement than it seems then say so from the beginning, not 2 years after! ... communication is key

If this was an open source project i'm sure the community would come up with an optimal solution then do a pull request, but it's not the case so we trust on postman's team skills to come up with a solution.

>We looked at implementing the feature earlier and decided this is better served with either plug-ins or building a data editor...

Sooo ... is it gonna be made or not?

**Comment by Sofianio** [comment]
In case it helps, this is what i used in my Tests tab for an API that returns categories with their subcategories

```javascript
var data;
try{
    data = JSON.parse(responseBody);
}
catch(e){
    console.log(e.message);
}

if(!data) return;

function show_count(data, parent){
    var keys = Object.keys(data);
    for(let i=0; i < keys.length; i++){
        key = keys[i];
        if(typeof data[key] != "object") continue;
        if(data[key].length) 
            console.log(parent+"."+key+" has "+data[key].length+" children");
        show_count(data[key], parent+"."+key);
    }
}

show_count(data, 'data');
```
the result:
```
GET localhost:8000/categories
data.categories has 7 children
data.categories.0.subcategories has 5 children
data.categories.1.subcategories has 6 children
data.categories.2.subcategories has 7 children
data.categories.3.subcategories has 3 children
data.categories.4.subcategories has 2 children
data.categories.5.subcategories has 3 children
data.categories.6.subcategories has 5 children
```

I know recursion will fail if the object has like 100 levels of depth, but most of the time it's not the case.

I hope this helps

**Comment by Brunaldo** [comment]
Any update on this guys? It would be nice to have a visual representation so I don't have to check in the 'Tests' tab so see counts...

**Comment by aronmgv** [comment]
@Brunaldo dont expect anything.. bunch of kids just making excuses. Actually one of the worst community support in my experience :/

**Comment by volkanogretmen** [comment]
I tried the workaround @sobtiankit suggested, couldn't get it to work (length was undefined).

This worked for me:
```
var body = JSON.parse(responseBody);
tests["Array length is " + body.length] = true;
```
Example output:
![Screenshot 2019-03-28 at 11 02 32](https://user-images.githubusercontent.com/25029377/55148708-07647f80-5149-11e9-9e72-90053982f9dd.png)

However, this should just be a default feature!

**Comment by ShepSims** [comment]
@a85 Do you know if this feature is still being developed or has it been abandoned?

**Comment by a85** [comment]
Update: We have introduced the ability to visualize API responses in Postman. Documentation here: https://learning.getpostman.com/docs/postman/sending-api-requests/visualizer/. Using this, you can add a "template" for your response and render anything as HTML/CSS/JS. This could include listing quantities, indexing the response in any way, or any other representation of the response. Some examples here: https://explore.postman.com/templates/4424

We will continue making improvements to our editor to show counts around arrays as well as XML/JSON objects but that is going to be a separate activity.

**Comment by Sofianio** [comment]
If someone made a "visualization" of the requested feature please share it here.
Thanks

**Comment by marchy** [comment]
@a85 Thank you for both the update and the direction forward Abhinav.

One thing though, if that is a separate activity - why is this feature request marked as closed (as is with https://github.com/postmanlabs/postman-app-support/issues/2115)?

These are both critical features and have been missing + demanded for years (much less effort than what you guys have put into the vizualizer API.

Please re-open these as it's very confusing having them 'Closed' when they are not very much still open.

**Comment by stevenvdbosch** [comment]
tbh i would also want the requested feature not only in the response but also in the request.

I've made a small mock up which would be cool:
@Sofianio @a85 
![mockup](https://user-images.githubusercontent.com/32450231/70224430-8fc20800-174d-11ea-89ae-30b27eee220c.png)

**Comment by pennstatephil** [comment]
+1

**Comment by BrutalSimplicity** [comment]
Yes, please reopen. You built a wonderful visualization API, but didn't really fulfill this request. I would prefer to *easily* view the size of json arrays in the normal json tab, rather than using the less than obvious visualization API.

**Comment by Trubador** [comment]
@a85  I don't understand why this has been closed and deferred to a visualization tool. This is basic functionality that every API developer needs and it is tedious to paste a response elsewhere and parse it to get the count. What is obstructing the implementation of this functionality?

**Comment by CodeAngry** [comment]
Almost 10 years since this was requested. Maybe you found the technology by now to display a number next to each branch you already parsed and know. Also (based on active JSON line/node) Collapse all Siblings, Expand all Siblings, showing the JSON Path of the current line in the top of the JSON visualizer... Absolutely nothings that would never take 10 years. Unless Microsoft did it. Then it would take 10 years each.

**Comment by marchy** [comment]
@a85 please re-open this issue. Seriously. It was incompetent of you to close this off as completed when it was not even touched. It’s one thing to push off, a whole another one to wrongfully pretend it was done when it was not.
