### ISSUE TITLE
Toggle the authorization-header - removing Basic Auth impossible

### ISSUE THREAD

**Issue by peletiah** [a85/POSTMan-Chrome-Extension#1679]
I'm still having the issue initially reported by @stuartrivero in #1322, even after following the steps indicated by @abhijitkane. Please see this screencast, where I run postman in the upper and wireshark in the lower half of the screen: https://gfycat.com/HonorableUnfoldedHydra

I'm running Version 3.2.12 (packaged)

**Comment by peletiah** [comment]
It just occured to me to try it with a working backend (It always returns a 401 in the screencast). After having logged in successfully once (200 OK), I can no longer reproduce the issue, no matter what I do.

It might be related to the fact that I'm sending two WWW-Authenticate-headers, one line with `Www-Authenticate: JWT` and in a second line `Www-Authenticate: Basic realm="Please log in`.

I'm not sure what is happening, this is somewhat unpredictable, I stumbled over it a few days ago and again today (I've only been using Postman for the past 2 weeks).

I'll report if this occurs again and leave the ticket open for now.

**Comment by a85** [comment]
@peletiah Is this still an issue?

**Comment by peletiah** [comment]
Thanks for inquring! I have not used postman as heavily since. I'll reopen if I stumble over it again!
