### ISSUE TITLE
Moving folders in duplicated collection collapses the collection and making it impossible to open again

### ISSUE THREAD

**Issue by mstaalesen** [a85/POSTMan-Chrome-Extension#1680]
In Postman 3.2.12 with Chrome Version 46.0.2490.71 (64-bit), there is a problem with duplicated folders and collections. If a folder is moved inside a duplicated collection, the whole collection is collapsed and not possible to open again before Postman is restarted. It is possible to use the "(...)" button on the collection and add new folders. After a new folder is created in the (now) buggy Collection, the Collection will expand but only the newly added folder is shown. 

To be able to reproduce:
1: Duplicate a collection and then open the duplicated collection
2: Click a folder and attempt to drag it inside said collection, then release the mouse.
3: The collection will collapse itself and it is not possible to open it anymore.

It also happens when duplicating folders inside a collection:
1: Open a collection with a few folders.
2: Duplicate a folder inside the collection
3: Attempt to move a folder in the collection
4: The collection will collapse itself and it is not possible to open it anymore.

Inspecting the code, there seems to be a problem with said line (collectionID is ofcourse my collection):

```
<div id="collection-children-e587cd21-6953-2c19-e5b8-1131084156a9" class="collection-children" style="display: none;">
```

When I click the collection, it changes from style="display: none;" to style="display: block;" for 0.5 seconds, and then it goes back to style="display: none;". On working collections, it will stay at style="display: block;".

This is the first time I'm seeing this issue, and I've been using Postman for almost a year now.

**Comment by abhijitkane** [comment]
@mstaalesen This bug cropped up due to the folder transfer feature we added. We'd pushed a fix for this on Friday (as part of v3.2.13), but the version doesn't seem to have been published on the webstore yet. I'll update this thread once the new version is available.

**Comment by abhijitkane** [comment]
v3.2.13 should now be available. To upgrade, head to `chrome:/extensions`, enable 'Developer Mode', and click 'Update extensions now'.

**Comment by mstaalesen** [comment]
@abhijitkane Confirmed! Upgrading to v3.2.13 seemed to solve the issue. Thanks :)
