### ISSUE TITLE
side-panel will resize only up to a certain width

### ISSUE THREAD

**Issue by NirLevanon-zz** [a85/POSTMan-Chrome-Extension#1682]
on version 3.2.13 of Postman, I am only able to increase the width of the side-panel to a certain width. The bigger issue is that if my request's title is too long the run and sub-menu buttons get pushed to the end of text, which I can no longer see fully. So the end result is that I have no way of reaching the edit button to change this case.

I'd expect a fix that would do a similar thing to what Newman does when a folder name is above 50 characters - it truncates and adds ellipses (...).

I'd recommend making your HTML such that the run and sub-menu circle buttons are above the text of the component and are floated right to the main component holding both the text and buttons.

Good luck.

**Comment by travisfawcett** [comment]
I agree. I love to be descriptive in my FOLDER descriptions.  Not working for me.  Now all these tests I can't duplicate (well, export, copy, reimport).    Make the left window menu Bigger please!

**Comment by aditikul** [comment]
@NirLevanon @travisfawcett This should be fixed now. Thanks for reporting.
