### ISSUE TITLE
Unable to view .png in Chrome Canary extension or to download

### ISSUE THREAD

**Issue by calebrepkes** [a85/POSTMan-Chrome-Extension#1683]
Hey all, 

<3 Postman

Performing a get call via Postman and the response is an empty body, with a couple of headers:
Content-Disposition → attachment;filename=BlaBla.png 
Content-Type → image/png 

I would like to either view the PNG in the Postman, or get a link to View it in Chrome Canary or to be able to download it. 

Any tips? Been searching the internet for quite a while already.

**Comment by abhijitkane** [comment]
@calebrepkes Can you check the Network tab of the DevTools window (http://blog.getpostman.com/2015/06/13/debugging-postman-requests/)? Here, you'll be able to see the request you're making and the associated response.

Two things that you might want to check for:
1. Content-Length in the "Headers" tab
2. The contents of the Response tab

**Comment by calebrepkes** [comment]
Hey, 

When I'm checking the Network tab I see 4 collect calls. Even though I perform only one call. And what is very curious to me is, that in there I see that the Request URL in DevTools is pointing to something completely different, then the URL im calling in Postman.

**Comment by abhijitkane** [comment]
@calebrepkes The collect calls are made to Google Analytics when certain events in the app are triggered. If you have the interceptor enabled, requests made will not show up in Postman's DevTools window. Can you disable the Interceptor and check?

**Comment by calebrepkes** [comment]
Yes thats the trick: To be able to see an image in Postman, you need to disable Interceptor in the Postman extension. 

You will then directly see the picture in the Postman extension. And like you said @abhijitkane when interceptor is disabled I also see it in the DevTools section. 

I guess there is no way to overwrite Interceptor action for this specific call, from Javascript in the pre-request script?
