### ISSUE TITLE
Selection bug in pop-up windows.

### ISSUE THREAD

**Issue by xxldoctor** [a85/POSTMan-Chrome-Extension#1686]
When I copy some stuff from such pop-up windows as "add request" or "Code", etc I have to select text very accurately, coz if after selection mouse pointer released outside pop-up window - this window will be closed, and I have to reopen it, and reselect text more accurately. It is very annoing sometime

**Comment by grmartin** [comment]
I find i have the same issue. it particularly bad with Markdown. I end up doing all of my markdown work in an editor, then copying it all and ctrl+a, ctrl+v to put it in. i never edit directly within a modal/shadowboxed window.

**Comment by xxldoctor** [comment]
seems fixed to me
