### ISSUE TITLE
Runner multiple iterations just show the result for the first one 

### ISSUE THREAD

**Issue by felipeplets** [a85/POSTMan-Chrome-Extension#1688]
I want to run a postman request N times and compare the performance time in each request and generate some insights based on it.

I've created a Folder only for this specific request, selected it in Runner, and entered the number of iterations I want (100) I run it and the result on the screen is only the HTTP status and time for the first request. After that it keeps running for some time, the same time expected for 100 requests, but even after finished no other result is showed. 

I've tested it in both **Chrome App** and **Mac App** and it seems a bug to me.

Anyone else experiencing the same behaviour?

**Comment by felipecocco** [comment]
+1

**Comment by sdnts** [comment]
@felipecocco @felipeplets We've been working on a redesign of the Runner that addresses this issue.

The new Runner is on our Canary channel, and you can download it for [OSX](https://dl.pstmn.io/download/channel/canary/osx_64) / Windows ([x86](https://dl.pstmn.io/download/channel/canary/windows_32) or [x64](https://dl.pstmn.io/download/channel/canary/windows_64)) / Linux ([x86](https://dl.pstmn.io/download/channel/canary/linux_32) or [x64](https://dl.pstmn.io/download/channel/canary/linux_32)) / [Chrome](https://chrome.google.com/webstore/detail/postman/loddepljkabcghihdkbkfknabkinanff)

I'd recommend you to join our Slack community [here](https://www.getpostman.com/slack-invite) so you can provide feedback before the runner moves to our stable builds :)

**Comment by sdnts** [comment]
@felipeplets @felipecocco The new Runner is out now with the latest release (4.9) on our native apps and you should now be able to look at requests grouped by iterations. :)
