### ISSUE TITLE
cURL command differ in Windows and MAC

### ISSUE THREAD

**Issue by Srajanacharya** [a85/POSTMan-Chrome-Extension#1691]
For a given instance in postman the cURL created by postman is different in Windows and MAC (working fine in MAC, but not in windows). What is the reason? #

**Comment by SamvelRaja** [comment]
@Srajanacharya it would be related to #1655, we have fixed the issue in Mac app  `v4.0` Which will sooner be reflected in the chrome versions as well.

**Comment by SamvelRaja** [comment]
@Srajanacharya we released our latest version `4.1.0` can you update and check it?
