### ISSUE TITLE
Testing like in SoapUI

### ISSUE THREAD

**Issue by arnzel** [a85/POSTMan-Chrome-Extension#1692]
Hi,

in SoapUI i can make tests like this
1. Make some Database Operations(Mongo)
2. Make request A
3. Check Collections contains specific data

Is such a test also possible in postman ?

**Comment by a85** [comment]
@arnzel How do you connect to the MongoDB database? You can do that inside Postman too if the database is available as a REST API.

**Comment by arnzel** [comment]
Hi, for soaup ui i use the jdbc driver for mongo.

the rest api enables only selects, i cant insert data

**Comment by a85** [comment]
Postman is not designed to work with database drivers. It can only work with software that expose an HTTP API.
