### ISSUE TITLE
Allow marking "incomplete" tests in collections

### ISSUE THREAD

**Issue by sethbattin** [a85/POSTMan-Chrome-Extension#1693]
Allow marking tests to have a status that is between passing and failing.  This allows writing tests for incomplete features, or marking tests as otherwise needing future attention without causing a fail result for the whole collection.  Similar to the [@markTestIncomplete annotation in PHPUnit](https://phpunit.de/manual/current/en/incomplete-and-skipped-tests.html).

The use case is for continuous integration, when adding tests to features that have preexisting invalid behavior (for example, the incorrect response code). A failure result is not useful, because it obscures new "real" failures for incoming changes. A passing test is also not useful, because it tests invalid results and provide no indication of a problem.

Related: https://github.com/postmanlabs/schemas/issues/8

**Comment by a85** [comment]
@shamasis Is this available now in the new sandbox?

**Comment by kunagpal** [comment]
@sethbattin This is now possible with the all-new pm API, like so:
```js
pm.test.skip('This test will not be run', function () {
  pm.expect(4).to.equal(4);
})
```

More details here: https://www.getpostman.com/docs/postman/scripts/postman_sandbox_api_reference
