### ISSUE TITLE
tests discrepancies between postman and newman

### ISSUE THREAD

**Issue by alowenst** [a85/POSTMan-Chrome-Extension#1694]
Hi there!

I have a couple of calls with tests defined for both.
First one is creating an artifact in my system and also returns the ID of the artifact. I'm setting an environment variable with the ID of the artifact. 
Second API makes a DELETE request and in the response i'm getting the ID that was set in the first API. My test makes a validation of the field in the response against the value of the environment variable that was saved in the first call.

**Postman returns a passed test but Newman is insisting on failing the test.**

First API test has - 
var jsonData = JSON.parse(responseBody);
postman.setEnvironmentVariable("id", jsonData.id);

Second API has - 
var jsonData = JSON.parse(responseBody);
var id = postman.getEnvironmentVariable("id");
tests["artifact was deleted"] = jsonData.removed_id === id;

Am I missing anything here?
Thanks!

**Comment by czardoz** [comment]
This should not happen ideally.

Can you add these couple of logs to your second test:

```
var jsonData = JSON.parse(responseBody);
console.log("=== JSON Response ===");
console.log(jsonData);
console.log("=== Environment Var ===");
var id = postman.getEnvironmentVariable("id");
console.log(id);
tests["artifact was deleted"] = jsonData.removed_id === id;
```

And paste the output here?

**Comment by alowenst** [comment]
Thanks for the fast reply!
I'm having trouble with opening dev console for postman Mac client. 
How do I open it or alternatively, where should I see those console.log()?

Thanks again

**Comment by czardoz** [comment]
Oops, I meant in Newman, not the Mac app. 

(as an aside, you can open dev tools in the Mac app with "View > Toggle DevTools", or Cmd+ Alt + i)

**Comment by alowenst** [comment]
Found the console for Postman :). 
this is what I have in postman - 
[..]
=== JSON Response ===
VM248:8 Object {data: Object, removed_id: "132165"}data: Objectremoved_id: "132165"**proto**: Object
VM248:9 === Environment Var ===
VM248:11 132165
[..]
so the ID looks the same. 

As for newman.. should it print anything with console.log()? it's not outputting anything except for the regular tests output.. 
When I place console.log() in my first API it does print stuff but it doesn't work for the second API.

200 678ms Delete task [DELETE] https://XXX/132367 //comment - this is the ID that was set as environment variable
    ✔ Status code is 200
    ✗ Artifact was deleted

Another things (might be irrelevant) - I have a few more API calls in between those 2 calls. those are also using the same ID variable but they are successful.

Thanks!

**Comment by alowenst** [comment]
I'm hitting issues and reporting as we go :smile: 
There's a syncing problem between the client and the command line execution when I running NM with -u (collection is on the cloud). I had to locally save the collection and run it. Now i'm seeing console.log() printouts. 

First API response is 
[..]
=== JSON Response ===
{ id: 132370, /// this is the artifact ID
[..]

output as you requested for the second API 
=== JSON Response ===
{ data: { service_id: '8805', task_id: '132370' },
  removed_id: '132370' }
=== Environment Var ===
132370
200 665ms Delete artifact [DELETE] https://XXXX/132370
    ✔ Status code is 200
    ✗ Task was deleted

So the ID's look identical.
Also, I might say that the output is somewhat inaccurate. The additional console logs are added inside the Delete artifact call so why is it printing before it? isn't it more accurate for it to be **after** the Delete artifact [DELETE] https://XXXX/132370 line?
Thanks

**Comment by czardoz** [comment]
Postman does not update the collection link automatically, you will have to click on the collection > Share > "Update Link" to update your changes.

In your first API response, the artifact ID is a number, whereas in the response for the second API, it is a string. Could that be the issue?

**Comment by alowenst** [comment]
This could be the problem. How do I workaround this to see if this is it? cast of some sort?

**Comment by czardoz** [comment]
Yes, something like

```
tests["artifact was deleted"] = jsonData.removed_id.toString() === id.toString();
```

**Comment by alowenst** [comment]
OK.. I used tests["artifact was deleted"] = jsonData.removed_id === String(id); and it worked :smiley: 
Thanks a lot!!

**Comment by alowenst** [comment]
BTW, although the problem is now fixed for me, I suggest that you do fix the root cause for why PM passed the test and NM didn't.
Thanks again.

**Comment by czardoz** [comment]
Yes, a fix will be pushed in the next release of Newman.
