### ISSUE TITLE
Referencing variables within functions does not work

### ISSUE THREAD

**Issue by prakhar-singh** [a85/POSTMan-Chrome-Extension#1695]
```
function givesDescription(value){
if (value == 'Now'){
    postman.setEnvironmentVariable("desc", 'The date is {{now_date}}');
}
else {
    postman.setEnvironmentVariable("desc", 'The date is {{past_date}} and {{now_date}}');
}
}

givesDescription({{var1}})
```

I tried running the above code in Pre-request script. Can we not call environment variables inside function? If yes, is there a workaround for this?

**Comment by jjurisch** [comment]
Looking at https://www.getpostman.com/docs/sandbox, I found: 

**environment:** A dictionary of variables in the current environment. **Use environment["foo"]** to access the value of the "foo" environment variable.

So think you would use something like: 

```
function givesDescription(value){
if (value == 'Now'){
    postman.setEnvironmentVariable("desc", 'The date is ' + environment['now_date']);
}
else {
    postman.setEnvironmentVariable("desc", 'The date is ' + environment['past_date'] + ' and ' +  environment['now_date']);
}
}

givesDescription(environment['var1']);
```

**Comment by prakhar-singh** [comment]
Thanks for the help. :)
I wasn't paying enough attention, I guess.

**Comment by prakhar-singh** [comment]
Thanks for the help. :)
I wasn't paying enough attention, I guess.
