### ISSUE TITLE
Enhancement request - add a shortcut for update link

### ISSUE THREAD

**Issue by alowenst** [a85/POSTMan-Chrome-Extension#1696]
Hey guys!

a keyboard shortcut for **update link** would be very productive. Going into collection settings and hit that button every time is cumbersome. 
Thanks!!

P.S. 
Love your tools!! keep up the good work :smiley:

**Comment by aditikul** [comment]
Thanks! Glad you like our products :) We're looking into better ways to manage and update your links. The Cloud plan (paid plan) is related to this since it keeps everything in sync automatically. Stay tuned for updates to the app.
