### ISSUE TITLE
Having trouble in POstman Collection

### ISSUE THREAD

**Issue by pathikpatel3007** [a85/POSTMan-Chrome-Extension#1698]
I am having some issue with Postman Collection. When I am running collection, won't be able to see how many APi passed and how many failed.

Please see attached screenshot
![capture](https://cloud.githubusercontent.com/assets/12001027/12865003/60c652e0-cc65-11e5-8150-157d1583eae9.JPG)

**Comment by abhijitkane** [comment]
@pathikpatel3007 Have you written tests for your requests? (https://www.getpostman.com/docs/writing_tests)

A 200 OK response for a request will not automatically be treated as a success or response.
