### ISSUE TITLE
Can't Edit/Delete Collection Items if displayed URL wider than left hand side bar

### ISSUE THREAD

**Issue by pjacferreira** [a85/POSTMan-Chrome-Extension#1699]
Hi, 

I started saving my URL to a collection, and then found out that I can't delete or edit the requests if the display of the URL is wider than left hand sidebar (i.e. if the displayed url is truncated).

URLs that fit, display the "..." to edit, the other's don't.

In the attached screenshot, the 1st 3 items of the authentication collection don't display the "...", the last one .../test does.

Also, since there is a limit to how wide I can make the left-hand sidebar, I have now way to edit or delete these requests...

![screenshot](https://cloud.githubusercontent.com/assets/11157900/12871850/62b2093e-cd85-11e5-9923-4048e7da635f.png)

**Comment by abhijitkane** [comment]
@pjacferreira Thanks for reporting this. We're working on a UI revamp, and will certainly include a fix for this.

**Comment by KumG** [comment]
A workaround is to click on the arrow next to the folder title. Then, it is possible to edit/delete the query.

**Comment by pjacferreira** [comment]
@KumG Thank you, that helped a lot.
