### ISSUE TITLE
Feature Request: Ability to add Cookies to Request

### ISSUE THREAD

**Issue by pjacferreira** [a85/POSTMan-Chrome-Extension#1700]
Hi,

I was wondering if it was possible to add cookies to collection item requests (basically extend the request with user defined cookies for testing)?

**Comment by abhijitkane** [comment]
To add cookies, you'll need to use the Interceptor - http://blog.getpostman.com/2014/11/28/using-the-interceptor-to-read-and-write-cookies/

If you have the Mac app (https://www.getpostman.com/apps), you can add cookies from the app itself.

**Comment by pjacferreira** [comment]
Okay, thank you for your reply.

I have postman interceptor installed (version 0.2.16). The Icon seems to different from the stop lights used in the blogs entry, but I assume that is known.

With interceptor active, I still don't have any place to add the cookies, but in the blog they speak of needing JetPacks also, which I don't have, so I assume that that is the problem.

**Comment by abhijitkane** [comment]
@pjacferreira We're now shipping version of Postman with Jetpacks activated. If the Interceptor is enabled on Postman, you just need to add a `Cookie: name=value` header in your request.
