### ISSUE TITLE
License cost

### ISSUE THREAD

**Issue by sibalas** [a85/POSTMan-Chrome-Extension#1701]
Hi Team,
Please let me know the price for postman jet license cost.Earlier it was 10$ and now i could see the changes - https://www.getpostman.com/pricing.

Kindly confirm the cost.

Thanks,
Siva

**Comment by abhijitkane** [comment]
@sibalas Jetpacks is now included in each copy of Postman.The pricing page has been updated to reflect this. Only the Cloud plan is paid.
