### ISSUE TITLE
Mac v4 beta Export data is not working

### ISSUE THREAD

**Issue by stormposse** [a85/POSTMan-Chrome-Extension#1702]
I'm using Yosemite. In the Mac v4.0.0-beta.2 version it seems SETTINGS > Data > Export data is not working? When I click on the orange Download button I don't get the file selector dialog?

**Comment by SamvelRaja** [comment]
Thanks for reporting the problem. The issue has been identified and will be fixed in the next beta update.

**Comment by SamvelRaja** [comment]
Hey @stormposse the fix has been released with our latest update `v4.0.0-beta.3`. Can you cross check this and close the issue.

**Comment by SamvelRaja** [comment]
Closing the issue in reference to v4.0.0
