### ISSUE TITLE
Postman Client beta 4.0 just keeps syncing

### ISSUE THREAD

**Issue by dzuluaga** [a85/POSTMan-Chrome-Extension#1703]
Hi there,

Postman Client Mac version just keeps syncing and doesn't return. Chrome Plugin older version works fine though. 

![postman](https://cloud.githubusercontent.com/assets/1755383/12896093/ed93c4a0-ce54-11e5-97fe-b069b69c7336.png)

Thanks,
Diego

**Comment by abhijitkane** [comment]
@dzuluaga Can you try signing out and signing back in? If this doesn't help, can you shoot us an email at help@getpostman.com?

**Comment by dzuluaga** [comment]
Great! I can see collections showing up. The icon never turns orange though
and it keeps saying syncing. Everything else seems to be working fine.
Thanks guys!

On Mon, Feb 8, 2016 at 11:14 PM, Abhijit Kane notifications@github.com
wrote:

> @dzuluaga https://github.com/dzuluaga Can you try signing out and
> signing back in? If this doesn't help, can you shoot us an email at
> help@getpostman.com?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/postmanlabs/postman-app-support/issues/1703#issuecomment-181740846
> .

## 

Diego Zuluaga | apigee http://www.apigee.com/ | m: +1.415.299.9983 | twitter
@dzuluaga http://twitter.com/dzuluaga @apigee https://twitter.com/apigee
| skype dzuluaga | _Apigee Community http://community.apigee.com/_ for
answers, ideas and support!
"First do it, then do it right, then do it better - this is my mantra for
successfully getting things done. It's all about the iteration." Addy Osmani
https://twitter.com/addyosmani/status/314785735171518464

**Comment by dzuluaga** [comment]
It seems to be working now. Thanks Abhijit!

Please let me know if you want me to close the ticket.
