### ISSUE TITLE
Helpful if you want to check if all your tests are passed

### ISSUE THREAD

**Issue by srbangre** [a85/POSTMan-Chrome-Extension#1704]
Hi,
Just thought this will be easy for those who put lots of assertions/tests in their scripts -
If you have so many tests statements in your script and figure out if all the tests return true or false - It is possible in below way - 

I have 10 tests in my single test case for validation. i need to print console.log if all the tests are passed or true. how to do that - 
//checking if all assertions are passed then print the test case status in console.log

```
var alltests = true;
for (var test in tests) 
{                
    alltests = alltests && tests[test];        
    console.log(test + ": " + tests[test]);            
}    
console.log("all tests " + alltests);
if (alltests)
     {
            console.log("Test case executed successfully")
            console.log("Test case Test001 passed!!")    
        }    
else     {
            console.log("Test case Test001 failed!!")    
}
```

other way is define a global variable -Testvalidation and store the script in it and evaluate this variable before printing the console.log statements. example - 

```
eval(postman.getGlobalVariable("Testvalidation"));
if (alltests) 
    {
    console.log("Test case executed successfully")
    console.log("Test case Test001 passed!!")    
       }    
else 
    {
    console.log("Test case Test001 failed!!")    
      }
```

**Comment by srbangre** [comment]
This is not an issue but a helpful tip for people like me :)

**Comment by ejkdeveloper** [comment]
Thanks a lot for sharing this snippet of the code. It was really helpful in making life easier in validating all the assertions..

**Comment by madhukiranR** [comment]
how to  use this?
