### ISSUE TITLE
"Run in Postman" button in Postman Documentation and public Documentation

### ISSUE THREAD

**Issue by dzuluaga** [a85/POSTMan-Chrome-Extension#1705]
I really like that Postman Documentation generates HTML pages from my collections. However, I noticed that Postman Echo sample includes "Run in Postman" button. How can I include this button in my own documentation? Also, how can I make this page public? so, that anyone can see this page first and then they can import into their collections.

![postman_echo](https://cloud.githubusercontent.com/assets/1755383/12896247/d24987ba-ce55-11e5-9e8f-8899cef04d7a.png)

![nucleus_edge_api_tests](https://cloud.githubusercontent.com/assets/1755383/12896273/ef97cbd8-ce55-11e5-9323-967df105157e.png)

Thanks,
Diego

**Comment by a85** [comment]
The button generation code is now available in the "share" modal. :)
