### ISSUE TITLE
Postman Cloud not detecting conflicts

### ISSUE THREAD

**Issue by dfrommi** [a85/POSTMan-Chrome-Extension#1706]
When multiple users are modifying the same request of a shared collection at the same time, then the result ist unpredictable. Postman cloud doesn't detect the conflict and resolves them or at least warns the user.

We could observe, that either one change wins, overwriting the other user's change, or - even more surprising - both changes kind of win. In the latter case, the change of user A is visible on user B's collection, overwriting B's own change and vice versa. So both users receive the update from the other user while losing their own change.

**Comment by a85** [comment]
@dfrommi This is high on our priority and you should see improvements soon.
