### ISSUE TITLE
Segment Parameters not being replaced under 4.0

### ISSUE THREAD

**Issue by twellspring** [a85/POSTMan-Chrome-Extension#1707]
I just upgraded to postman 4.0 OSX Client ( MacOS 10.11.2 ) and segment parameters are no longer being replaced.

Example: `ord-salt-api-prod-1/servers/:server`

![postman screenshot](https://cloud.githubusercontent.com/assets/9868888/12933018/b66abd80-cf3a-11e5-9bda-526be321de5c.png)

My API log shows the URL with the :server variable still in place
`::ffff:192.168.x.xx - - [09/Feb/2016:22:38:34 +0000] "GET /servers/:server HTTP/1.1" 400 58 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/537.36 (KHTML, like Gecko) Postman/4.0.0-beta.2 Chrome/47.0.2526.73 Electron/0.36.2 Safari/537.36"`

On another laptop on postman 3.2.15.1 OSX Client the same query continues to work

::ffff:192.168.x.xx - - [09/Feb/2016:22:43:22 +0000] "GET /servers/ord-apcdash-web-stage-1 HTTP/1.1" 200 1511 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/537.36 (KHTML, like Gecko) Postman/3.2.15.1 Chrome/45.0.2454.85 Electron/0.34.3 Safari/537.36"

**Comment by oli206** [comment]
Same here, just discovered this feature and when trying to use it in the Mac app, it does not replace the values:

http://{{hsdi}}/hotel-static-data/getHotelStaticInfo/:mode/

results in a HTTP request:

Request URL:http://10.223.2.130:33234/hotel-static-data/getHotelStaticInfo/:mode/

I'm using 4.0.0-beta.2

**Comment by abhijitkane** [comment]
@oli206 @twellspring Thanks for reporting this. We'll fix this in the next release.

**Comment by abhijitkane** [comment]
<img width="860" alt="screen shot 2016-02-16 at 16 00 03" src="https://cloud.githubusercontent.com/assets/681190/13073763/7a0621cc-d4c6-11e5-9905-9ecbf675562d.png">

@oli206 @twellspring Are you still seeing this in the latest version - 4.0.0-beta.3? Seems to be working for me

**Comment by oli206** [comment]
Hi @abhijitkane and thanks for your quick response :)
I've been trying to update to beta 3 for the last two days but something must be wrong with my installation because I download the update, restart the application and it is still on beta 2 (and i'm asked to update again). 

I'll try to make a fresh install and try again

**Comment by oli206** [comment]
It works on 4.0.0-beta.3 
Thanks!
