### ISSUE TITLE
Postman Authentication Token saved empty on 4.0

### ISSUE THREAD

**Issue by dzuluaga** [a85/POSTMan-Chrome-Extension#1708]
Hi there,

Tokens are saved empty when using Authorization feature. See screenshot below. Chrome extension works fine.

<img width="948" alt="postman" src="https://cloud.githubusercontent.com/assets/1755383/12964112/2be15100-d003-11e5-9f50-55c1f979822d.png">

Thanks,
Diego

**Comment by abhijitkane** [comment]
Thanks for reporting this @dzuluaga. We'll be pushing a fix for this soon.

**Comment by SamvelRaja** [comment]
Hey @dzuluaga  the fix has been released with our latest update v4.0.0. Can you cross check this and close the issue.

**Comment by dzuluaga** [comment]
Thanks @SamvelRaja. It works great!
