### ISSUE TITLE
unable to load external js files in postman

### ISSUE THREAD

**Issue by rohan-pulekar** [a85/POSTMan-Chrome-Extension#1711]
I am using postman app and I created a test case in it. My Tests tab has:

> function some_function() {
>     tests["test2"] = responseCode.code === 200;
> }
> some_function();

Postman runs this fine and gives 

> PASS test2

Then I modified the text in my Tests tab to:

> $.getScript("path/to/sample.js", 
> function() 
> {});
> 
> some_function();

And modified sample.js to:

> function some_function() {
>     tests["test2"] = responseCode.code === 200;
> }

When I run it now, I get:

> There was an error evaluating the test script. some_function is not defined

Anyone have any idea what I am doing wrong?
Thanks

**Comment by MTen** [comment]
Well there are a few things here.
It looks like jQuery has been depreciated so your ajax may not exactly work. A good way to check that is by enabling the chrome dev console.
(http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/)

List of sandbox libraries.
https://www.getpostman.com/docs/sandbox

This is a bit of a hack but it will do what you're looking to do

In a pre-request script

```
function httpGet(theUrl)
{
    var xmlHttp = new XMLHttpRequest();
    xmlHttp.open( "GET", theUrl, false ); // false for synchronous request
    xmlHttp.send( null );
    return xmlHttp.responseText;
}
//invoke above method getting the super useful library underscore
var response = httpGet("https://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.8.3/underscore-min.js");

//set the response to a global variable for use anywhere in your project or any other project
//postman sets environment/global variables as strings.
postman.setGlobalVariable("underscore", response);
```

run this in the tests section

```
// short circuits the tests if you receive a failure response code
if(tests["Response Code " + responseCode.code ] = responseCode.code === 200){

// try for the unexpected
  try{
   // use the super dangerous eval to convert the global variable string into a script.
   globals["underscore"].eval

    var didIScore = _.zip(['hi', 'this'], ['is','cool'], ['i', 'just', 'imported', 'underscore'])
    tests[didIScore] = didIScore !== undefined;
  } catch(e) {

    // gives the error message in the tests section of postman 
    tests[e.message] = false;

  }
}
```

now the script is set in your global environment variables so where ever you want to use the script you can just call globals["underscore"].eval and you're good to go :)

Let me know if this solves your issue, and if so we can close it.

**Comment by RJ05** [comment]
I am getting following error while implementing the same.

`There was an error in evaluating the Pre-request Script:  ReferenceError: XMLHttpRequest is not defined`
