### ISSUE TITLE
Authorization type does not save

### ISSUE THREAD

**Issue by weswesley** [a85/POSTMan-Chrome-Extension#1712]
If you save a request into a collection, the Authorization type select box only saves as "No Auth" even if it was saved with it set to "OAuth 1.0" or any other.  The keys and data are stored, but not the option of the select box.

**Comment by SamvelRaja** [comment]
@wesleyalmedia  Can you tell us the app type(Chrome or Mac) and version you are in?
And also I tried to reproduce the same in the latest mac app `4.0.3` app it is working fine.

**Comment by merikan** [comment]
I have the same problem. Running Postman App on Mac
Version: 3.2.20
Updated: February 29, 2016

**Comment by natizlp** [comment]
+1

**Comment by SamvelRaja** [comment]
@wesleyalmeida and @merikan I tried reproducing it in the latest version `4.0.5` it is working fine.
One quick note, did you enabled the **Save Helper data** option before saving the request
![auth1 0](https://cloud.githubusercontent.com/assets/5114052/13738084/4eaff0de-e9e8-11e5-895d-af1af1ca6f1e.gif)

If the problem still persist, can you check the app's console (http://blog.getpostman.com/2015/06/13/debugging-postman-requests/) for any errors? (You'll need to right click on the runner > Inspect element)

**Comment by weswesley** [comment]
Can confirm it works on v 4.1

**Comment by bautrey** [comment]
This seems to have come back on Mac app 4.4.1 for me.

**Comment by bautrey** [comment]
never mind... Save Helper Data seems to make it stick.  Not sure why you'd ever want that not checked...
