### ISSUE TITLE
Disable full screen mode

### ISSUE THREAD

**Issue by JuanCaicedo** [a85/POSTMan-Chrome-Extension#1714]
Is there a way to disable full screen mode for the app and have it open a new tab within Chrome instead? This was the behavior of Postman 2. Full screen mode interferes with my workflow because if I cmd+tab to Chrome, it sometimes switches to Postman :) 

Great project, thanks!

**Comment by a85** [comment]
Chrome apps are now deprecated hence closing this. Check out our native apps www.getpostman.com/apps that solve the Cmd+Tab issue.
