### ISSUE TITLE
Header dropdown/autocomplete disappears when hovering over

### ISSUE THREAD

**Issue by mstaalesen** [a85/POSTMan-Chrome-Extension#1715]
In Postman 3.2.16, if I attempt to add a header to a request, the dropdown disappears as soon as I hover over the field.

Example: 
In "Header" field, enter: "Content". 
The autocomplete/dropdown box appears with suggested values.

As soon as I attempt to select a value (e.g Content-Type), the box disappears. The only way I can select the value I want is by using the cursors on the keyboard. Not a big bug, more an annoying bug.

Chrome version: Version 46.0.2490.71 (64-bit)

**Comment by flexy1994** [comment]
Same here. 
Postman (3.2.16.1) OSX
OSX 10.11.12

**Comment by a85** [comment]
This should be fixed in 4.0+

**Comment by mstaalesen** [comment]
Confirmed!
