### ISSUE TITLE
Update lodash to at least 3.x stable.

### ISSUE THREAD

**Issue by bradobro** [a85/POSTMan-Chrome-Extension#1717]
Currently Postman supplies LoDash 3.6.0. 

Version 4.3.0 is current.

Current stable 3.x is 3.10.1 includes _.get() (new in 3.7.0), which can really DRY up some tests.

```
tests["This excepts and shows up as a briefly flashing pink alert, easy to miss."] = parsedJson.nonexistent.length > 5
tests["_.get() would keep this just an easy-to-see failure"] = _.get(parsedJson, "nonexistent.length", 0) > 5
```

**Comment by a85** [comment]
https://www.getpostman.com/docs/postman/scripts/postman_sandbox_api_reference

**Comment by bradobro** [comment]
Thanks @a85
