### ISSUE TITLE
Desktop client scroll issues

### ISSUE THREAD

**Issue by voidmain** [a85/POSTMan-Chrome-Extension#1719]
I'm using the desktop (Mac) version of Postman and the scrolling makes it almost too painful to use the app. The response textarea is always 50 lines of text and this isn't configurable. After I submit a request, I can only see 20 or less lines of the response. I have to move my cursor to the side of the app, outside of the request body textarea and then scroll the tab down until the full response textarea is visible.

I have to repeat this process in the opposite direction to change the request and then again to view the response. Plus, the width of the area that I can do this tricky little scroll in is about 20 pixels. That makes it really challenging to do this maneuver over and over.

This is a usability killer.

i've attached screen shots as illustrations.

![Viewing and editing request body](https://cloud.githubusercontent.com/assets/377102/13024297/e6d9b940-d1af-11e5-8337-d89771f9545c.png)

![Viewing the response body](https://cloud.githubusercontent.com/assets/377102/13024298/e89605ea-d1af-11e5-9a8c-71ae795eca23.png)

**Comment by glennschmidt** [comment]
I thought I must be the only one having this problem. It's been driving me nuts since early versions of Postman.
I'm also using the Mac desktop version, maybe it is specific to that version.

**Comment by cruisencode** [comment]
I'm having the same issue as well.

**Comment by aditikul** [comment]
@voidmain @glennschmidt @cruisencode Totally understand the issue. We are looking into this however we are using a plugin for the response view which limits what we can do to solve this. For now I would recommend using the shortcut Cmd+Up/Cmd+Down to quickly jump scroll. In the meantime we will work on solving this on a longer term ETA.

**Comment by a85** [comment]
@aditikul The Cmd+Up/Cmd+Down shortcuts do not work after a click in the sidebar area. Can you check this once?

**Comment by ahmetgeymen** [comment]
I think request settings page below the tab should not be scrollable area. Instead the textview that contains the response body is scrollable by default though. The end of the response body textview remains below the window area. You have to scroll down to see the end of it which is painful to figure out how to do.

**Comment by a85** [comment]
Postman now has a two pane view: View > Toggle Two-pane view. The request and response can appear side by side.

**Comment by mfoote** [comment]
i am not seeing... View > Toggle Two-pane view

**Comment by Alton-Powell** [comment]
Click on Settings and then on the General tab you will find "Two Pane View". Turn it on.

**Comment by raketenolli** [comment]
Equally dysfunctional. I cannot scroll inside the response body using my mouse wheel (Windows 10, desktop app).

**Comment by ahmetgeymen** [comment]
After two pane feature is brought, I began to use request view and response view side by side. Seems more effective.

**Comment by mdickin** [comment]
I don't know why this is closed, I still frequently have issues using the scroll wheel inside the response. It seems there's some distinction between scrolling while the cursor is over the left half of the text area versus the right. But then sometimes it doesn't work over the left either.

I'm using Windows desktop v6.6.1

**Comment by yarick** [comment]
I am seeing this issue on OSX as well

**Comment by brcinho** [comment]
I experience the same problem in version 7 on Windows desktop client but only on external monitor, not on my main monitor. In general the scroll stops working in any Postman user control so I have to use scrollbars directly with mouse on external monitor.

My main monitor has scaling to 200%, while external one doesn't have scaling, although I don't know if it is anyhow related to the issue, just trying to give as much inputs...
Os is Windows 10 (1809)

**Comment by cstephen98** [comment]
So how many years to people have to complain about this issue before they fix it?
