### ISSUE TITLE
PostMan not sending any requests or saving in history

### ISSUE THREAD

**Issue by Christoph-Wagner** [a85/POSTMan-Chrome-Extension#1720]
Windows 10 64bit, Chrome 48.0.2564.109 m, Postman 3.2.16 (packaged)

The following errors show up in the console upon starting postman:  
window.localStorage is not available in packaged apps. Use chrome.storage.local instead. (3 times)  
beforeunload is not available in packaged apps. (2 times)  
unload is not available in packaged apps.  

Last log before nothing else happens:
10:52:52.141 - All data exported

The interface is fully functional, I can save requests to the collection and load old requests from history.

But the send / send and download buttons have no effect and nothing gets saved into history. No data transfer shows up in the network tab after initial load (besides assets like images and js).

**Comment by Christoph-Wagner** [comment]
Found #712 fixing this. It probably really should be checked as fracture-point mentioned ;)

**Comment by pravin0** [comment]
Do u get any resolution?? i am facing the same issue..... Thanks
