### ISSUE TITLE
WebDAV methods

### ISSUE THREAD

**Issue by MovGP0** [a85/POSTMan-Chrome-Extension#1721]
The WebDAV commands `COPY` and `DELETE` are available, but others are missing. This includes `PROPFIND`, `PROPWATCH`, `MKCOL`, `MOVE`, `LOCK` and `UNLOCK`, which are the minimal requirements for WebDAV implementations. 

There are even more [WebDAV methods](https://msdn.microsoft.com/en-us/library/aa142917%28v=exchg.65%29.aspx), so it might be useful to let the user type in a method that is not in the list.

**Comment by a85** [comment]
Closing as duplicate of #1710
