### ISSUE TITLE
 No html preview of page when there is a 500

### ISSUE THREAD

**Issue by manjitkumar** [a85/POSTMan-Chrome-Extension#1722]
What i have observed is that postman app is not showing html preview of error response returned by server like it was showing in previous releases.

I have put a syntax error for demonstrating the error for reporting to you. 
I have added a few screenshots to help you understand the issue better. Let me know if i can help further. 

<img width="1280" alt="1" src="https://cloud.githubusercontent.com/assets/5033349/13042305/1f8a4eee-d3e5-11e5-9d5a-d125500fddaa.png">
<img width="1280" alt="3" src="https://cloud.githubusercontent.com/assets/5033349/13042304/1f8a3288-d3e5-11e5-981d-6c52976c1d17.png">
<img width="1280" alt="screen shot 2016-02-15 at 1 02 48 pm" src="https://cloud.githubusercontent.com/assets/5033349/13042306/1f8d61ec-d3e5-11e5-8757-fa37eb27f809.png">

**Comment by SamvelRaja** [comment]
Hey @manjitkumar we have released our latest `v4.0.0` mac app which solves the problem. Can you cross check the same and close the issue?

**Comment by manjitkumar** [comment]
@SamvelRaja @abhijitkane Works with latest version `v4.0.0`. Thanks.
