### ISSUE TITLE
Support Bearer Token Authorization

### ISSUE THREAD

**Issue by b22n** [a85/POSTMan-Chrome-Extension#1723]
It would be useful that support the bearer token on the request Authorization tab.

It's just simple function that add a header for 'Authorization' with 'Bearer ' + token string without OAuth2 flows.

**Comment by rstellar** [comment]
@b22n can't you do this by placing it in the Headers tab with the 'Authorization' key and a prefixing with 'Bearer'?

**Comment by punkstar** [comment]
@rstellar Unfortunately not. When I define a value for "Authorization" in the headers panel it silently ignores it and it doesn't get sent.

**Comment by sdnts** [comment]
@punkstar That shouldn't happen. Which version of the app are you on?

On the native apps, can you open up the Postman Console (Cmd/Ctrl + Alt + C) and resend the request? You should be able to see the headers that are sent with the request.
On the Chrome App, you should be able to open up the Chrome DevTools and check the network Tab (instructions [here](http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/)) to check the request headers.

**Comment by punkstar** [comment]
@madebysid You're right, your comment made my look into this a little closer and it's something else in my stack that's removing this header.  Thanks for the tip on the Postman Console - I didn't know that existed.

**Comment by chenrui333** [comment]
What is the status now?

**Comment by mykhaylo-** [comment]
simple Bearer Authorization with JWT (or any other) token would be great to have. Pleaase consider adding such a simple feature.

**Comment by punkstar** [comment]
@chenrui333 This turned out to be an error on my part and not a bug with the app.

**Comment by sdnts** [comment]
Guys, we're working on a general authentication mechanism, will take this up as part of that :)

**Comment by slooker** [comment]
It's been a few months, and I was curious if there was any update on this?  Without it, I can't use postman to work with anything JWT related.

**Comment by devedetti** [comment]
+1

**Comment by pdrolima** [comment]
Bad. I got this problem at this moment! :(

**Comment by kamalaknn** [comment]
Hi everyone,

We've shipped support for `Bearer` token authorization in Postman `5.3.0`. Please update your apps to the latest version and give it a try.

Please note that this feature is only available on our native apps. Here's the download [link](https://www.getpostman.com/apps).
