### ISSUE TITLE
Dotted menu isn't accesible for large collection/request names

### ISSUE THREAD

**Issue by maxihornes** [a85/POSTMan-Chrome-Extension#1724]
If the request or collection have a long name, the dotted menu is hidden by the scroll. I think it will be more accessible if it always displays the button fixed to the right.

**Comment by oi-io** [comment]
To get rid of a such request, I had to 1.create an empty collection; 2.drag the request to the collection; 3.delete the collection 

just a side note, names won't get that long normally but if you add a request from the history(intercepted from chrome) using the "Add to Collection" menu next to the bin icon. 
You won't be able to add a name for the request, and the url was used as name. so you will more than likely getting a long name.

**Comment by RensPontier** [comment]
The same is applicable for the collection itself. I created (by accident) a collection with a name that doesn't fit the left pane. I can now no longer delete it, for the hover-menu never becomes visible :(

**Comment by oi-io** [comment]
this is fixed in new version.

**Comment by oveits** [comment]
Thanks a lot for fixing this. It works fine.

**Comment by maxihornes** [comment]
Thanks!
