### ISSUE TITLE
Fields (headers, params, fields) jumping moving the cursor over the title

### ISSUE THREAD

**Issue by maxihornes** [a85/POSTMan-Chrome-Extension#1726]
When the request is added to some collection, the fields listing moves horizontally when you move the cursor over the title of the request and the fields.

**Comment by mstaalesen** [comment]
Not sure if this is what you mean, but I've noticed that the URL bar gets a bit wider when hovering over the title of "Body", "Tests" etc. 
![test](https://cloud.githubusercontent.com/assets/14194793/13190342/eb2f95d4-d75c-11e5-964e-416863cbd665.png)

**Comment by mstaalesen** [comment]
A small followup on my comment. The test needs to have a description-text entered for this bug to appear.

**Comment by maxihornes** [comment]
Yes, that is what I mean. It looks that was fixed in 4.0.2.

**Comment by mstaalesen** [comment]
I agree. This issue can be closed now.
