### ISSUE TITLE
global variable is wrongly set in tests

### ISSUE THREAD

**Issue by kalun1988** [a85/POSTMan-Chrome-Extension#1727]
I am using Version 3.2.16 , OS:mac
When I added a request to collection with test
`postman.setGlobalVariable("value-a", JSON.parse(responseBody).value_a);`

and I edit it afterwards to
`postman.setGlobalVariable("value-b", JSON.parse(responseBody).value_a);`

The request will wrongly set both value-a and value-b

**Comment by mstaalesen** [comment]
Is the response (value_a) the same value in both requests? Have you cleared your global variables between editing?
