### ISSUE TITLE
Getting 500 error on using newman to run a suite though same suite works fine via collection runner.

### ISSUE THREAD

**Issue by MayankSe-Kore** [a85/POSTMan-Chrome-Extension#1728]

**Comment by abhijitkane** [comment]
@mayank-sethi Can you please provide some more info here? Any errors in Newman? A screenshot would be helpful too.

**Comment by MayankSe-Kore** [comment]
@abhijitkane no its not giving any error out there. Its just saying 500 internal server error. Surprisingly same suite pass always when we run via collection runner. Dont know wats a difference there.

**Comment by czardoz** [comment]
@mayank-sethi More information is needed to debug the issue. Can you add "console.log(responseBody);" at the top of the test script of the failing request and share the output here?

If your response contains sensitive information, please email it to us at help@getpostman.com

**Comment by mstaalesen** [comment]
Might I add that running newman with the argument -O will give you a verbose log-printout of what has happened. I'm guessing you have some differences in your environment/global variable files (comparing what is imported in Postman and actually stored in the global/environment files you are using with newman)

**Comment by ronteddu** [comment]
I had the same issue @mayank-sethi and the resolution to this was that Postman processes request even when there is no header information that server wants, not the command line Newman. With Newman, it has to specifically tell the server about the header that the server wants. 

In our case I had to add this header: Accept with a value: application/json in Postman, save this and run it again in Newman.

**Comment by sdnts** [comment]
Guys, is this still an issue with the latest Postman App (v4.8.3) and Newman (v3.2.0)?

**Comment by ronteddu** [comment]
Haven't tried the new version but my solution above always worked with no issues so far.
