### ISSUE TITLE
Error with generated NodeJS(Request) code

### ISSUE THREAD

**Issue by galenweber** [a85/POSTMan-Chrome-Extension#1729]
I built this POST request with Postman.

https://www.getpostman.com/collections/395ae4c80aded55f3e5c

I wanted to replicate the request on my node server. I copied the generated NodeJS(Request) and ran it with node, but received this error `"Cannot read property 'hasOwnProperty' of null"`.

I've pasted the generated code below:

```
var request = require("request");

var options = { method: 'POST',
  url: 'http://a073-ils-web.nyc.gov/inmatelookup/ils/pages/common/find.jsf',
  headers: 
   { 'postman-token': '7c2a1bec-a991-89fc-60ee-e03a4f967424',
     'cache-control': 'no-cache',
     'content-type': 'multipart/form-data; boundary=---011000010111000001101001' },
  formData: 
   { 'mainform:sub_maincontent:nysidBKCase': null,
     'mainform:sub_maincontent:fname': 'John',
     'mainform:sub_maincontent:lname': null,
     'mainform:sub_maincontent:birthdate': 'Month',
     'mainform:sub_maincontent:day': 'Day',
     'mainform:sub_maincontent:year': 'Year',
     'mainform:sub_maincontent:searchButton': 'Search',
     mainform_SUBMIT: '1',
     'mainform:_link_hidden_': null,
     'mainform:_idcl': null,
     'javax.faces.ViewState': 'rO0ABXVyABNbTGphdmEubGFuZy5PYmplY3Q7kM5YnxBzKWwCAAB4cAAAAAN0AAhfaWQxNzM1NXB0ABsvaWxzL3BhZ2VzL2NvbW1vbi9maW5kLmpzcHg=' } };

request(options, function (error, response, body) {
  if (error) throw new Error(error);

  console.log(body);
});
```

I believe this is an error with the formData variable, namely that it is undefined.

Thanks for any help.

**Comment by elssar** [comment]
Hi @galenweber, apologies for the late reply.

I have traced the bug to the code generation library we use. It sets undefined form fields to null, which is causing the error, as the `request` library does not expect a form value to be `null` and does not handle it well.

We will try and fix this in a future release. Till then, you can try disabling form fields with no values before generating the code snippet. In this case, the fields `mainform:sub_maincontent:nysidBKCase`, `mainform:sub_maincontent:lname`, `mainform:_link_hidden_`, `mainform:_idcl` should be disabled.

Once those fields are disabled, you'll get a code snippet which works, like this one -

```
var request = require("request");

var options = { method: 'POST',
  url: 'http://a073-ils-web.nyc.gov/inmatelookup/ils/pages/common/find.jsf',
  headers: 
   { 'postman-token': '776429ac-9f76-3154-294a-38cbdd6e7883',
     'cache-control': 'no-cache',
     'content-type': 'multipart/form-data; boundary=---011000010111000001101001' },
  formData: 
   { 'mainform:sub_maincontent:fname': 'John',
     'mainform:sub_maincontent:birthdate': 'Month',
     'mainform:sub_maincontent:day': 'Day',
     'mainform:sub_maincontent:year': 'Year',
     'mainform:sub_maincontent:searchButton': 'Search',
     mainform_SUBMIT: '1',
     'javax.faces.ViewState': 'rO0ABXVyABNbTGphdmEubGFuZy5PYmplY3Q7kM5YnxBzKWwCAAB4cAAAAAN0AAhfaWQxNzM1NXB0ABsvaWxzL3BhZ2VzL2NvbW1vbi9maW5kLmpzcHg=' } };

request(options, function (error, response, body) {
  if (error) throw new Error(error);

  console.log(body);
});
```

To disable a form field, just click on the blue check icon to the left of the field name. On clicking, it should turn gray.

**Comment by sumit1317** [comment]
Hi,
An api call from postman is working perfectly fine, but when I take the code from postman and run it as part of nodejs, it is giving me an error. Code generated by postman is -
var options = { method: 'POST',
url: 'https://uat.nlis.mla.com.au/soap/upload.aspx',
headers:
{ 'postman-token': '52cdfc42-4f0f-fd7c-0e94-3301a3c0e520',
'cache-control': 'no-cache',
'content-type': 'multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW' },
formData:
{ '':
{ value: fs.createReadStream(__dirname + 'nlisMovement.xml'),
options: { filename: 'nlisMovement.xml', contentType: null } } } };
request(options, function (error, response, body) {
if (error) throw new Error(error);
console.log(body);
resolve(body);
});

Attachment file named nlisMovement.xml is -

<SOAP-ENV:Envelope
xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/"
xmlns:nlis="http://www.nlis.com.au/soap/ver2.0/nlis-soap.xsd">
SOAP-ENV:Header
nlis:originator-grp
nlis:userxxxxxx</nlis:user>
nlis:passwordxxxxxxx</nlis:password>
nlis:emailxxxxxx@xxxxxx.com</nlis:email>
</nlis:originator-grp>
nlis:create-date20171201</nlis:create-date>
nlis:create-time135203</nlis:create-time>
</SOAP-ENV:Header>
SOAP-ENV:Body
nlis:P2PTransfer
nlis:transaction-nameMy P2P Transfer</nlis:transaction-name>
nlis:transfer-date20171201</nlis:transfer-date>
nlis:buyer-pic3MRDG099</nlis:buyer-pic>
nlis:free-text2004 Weaners</nlis:free-text>
nlis:nvd-grp
nlis:event-time13:30:00</nlis:event-time>
nlis:nvd-serial-no1009675</nlis:nvd-serial-no>
nlis:pic3WERT546</nlis:pic> nlis:tag-list-grp
nlis:rfid982 123525464162</nlis:rfid>nlis:rfid940 110000856447</nlis:rfid></nlis:tag-list-grp>
</nlis:nvd-grp>
</nlis:P2PTransfer>
</SOAP-ENV:Body>
</SOAP-ENV:Envelope>

I am receiving following error from server.
<SOAP-ENV:Envelope xmlns:SOAP-ENV='http://schemas.xmlsoap.org/soap/envelope/'>SOAP-ENV:BodySOAP-ENV:FaultSOAP-ENV:ClientContent-Type should be set to text/xml</SOAP-ENV:Fault></SOAP-ENV:Body></SOAP-ENV:Envelope>

I have tried setting text/xml inside both header and formData respective locations, but no success. Any guidance and pointers will be highly appreciated.
