### ISSUE TITLE
Collection Runner constantly crashing on Mac OS 10.9.5 

### ISSUE THREAD

**Issue by desygn** [a85/POSTMan-Chrome-Extension#1730]
Hello,

I have been a long time user and am noticing that after I updated my Mac OS 10.9.5 with the latest security updates that the Collection Runner is constantly crashing Postman. It used to crash every so often but now it seems to crash ~60% of the time I run my tests.

Postman version is Version 3.2.16 (packaged) OS: mac

Any ideas?

Art

**Comment by abhijitkane** [comment]
@desygn That's odd - we haven't had this reported before. Does this happen with any collection you try to run?

Can you check the runner's console (http://blog.getpostman.com/2015/06/13/debugging-postman-requests/) for any errors? (You'll need to right click on the runner > Inspect element)

**Comment by desygn** [comment]
It is extremely unstable at this point. I cannot even open the Collection
Runner without it crashing. I just discovered you guys have a native Mac
application. I think I'll just start using that instead of fighting with
this.

Art

**Comment by a85** [comment]
@desygn We have made several changes to the Collection Runner code. Is this still happening for you?

**Comment by desygn** [comment]
Hi there... thanks for the response.

I have changed postman to use windows and I'm actually using the newman
node module now. So it is all good!

Thanks!
Art

**Comment by a85** [comment]
Awesome. Closing this issue then.
