### ISSUE TITLE
Eliminate/disable dimming with modal dialogs

### ISSUE THREAD

**Issue by Alicia-L** [a85/POSTMan-Chrome-Extension#1731]
Version 3.2.16 (packaged) OS: win
Architecture: x86-32
Native client architecture: x86-64

When I open a modal dialog, such as "Generate code snippet" or "New collection" the entire screen starts dimming, including the dialog I just opened. This takes 4-5 seconds and by the end of it the dialog is quite dark and some low-contrast text (such as the light-grey entries in the combobox below) becomes difficult to read.

![image](https://cloud.githubusercontent.com/assets/10558652/13138953/3c8b094c-d62a-11e5-8fa6-d6189b816503.png)

The entire screen is being dimmed so that even if I switch to another application it's still dark and it takes it 4-5 seconds to go back to normal brightness. If I go back to Postman with the modal dialog still open, the screen starts dimming down again. When I finally close the modal dialog, brightness starts going up again and 4-5 seconds later it's back to normal.

A few notes:
- This doesn't happen everywhere. Crazily enough, if I open the "Preferences" dialog, I experience dimming in tabs "Theme", "Data", "Add-ons", "Sync" and "About" but not in tabs "Settings" and "Shortcuts". This is puzzling to say the least.
- This happens regardless of the value of the "Instant dialog boxes" setting.
- This is not the same as issues #560 and #735, which complain about the speed of animations and were resolved by creating the "Instant dialog boxes" setting.

I don't see any reason why the entire screen should be dimmed. Greyed-out background, fair enough, it lets you know that you're in a modal dialog and cannot interact with the background. But why dim everything down? IMO this behaviour should simply be removed, but if for some reason someone thinks it's a good idea to have it, there should at least be a setting to disable this.

**Comment by Alicia-L** [comment]
Ok, I have to take some things back: this is not Postman's fault but rather related to my display. This is a new laptop and I'm not very familiar with it yet, so I didn't know about this "feature".
Even though it's not really Postman's fault that my display has such a strange behaviour, Postman developers may still want to look into it to try to prevent this from happening. I imagine there may be some way to accomplish this since, as I mentioned in my previous post, the problem occurs in some tabs of the "Preferences" dialog and not in others.

I have a Lenovo T550.

System:

<table>
<tr><td>Operating System</td><td>Microsoft Windows 7 Professional</td></tr>
<tr><td>Version</td><td>6.1.7601 Service Pack 1 Build 7601</td></tr>
<tr><td>System Model</td><td>20CK003EMZ</td></tr>
<tr><td>System Type</td><td>x64-based PC</td></tr>
</table>

Display:

<table>
<tr><td>Name</td><td>Intel(R) HD Graphics 5500</td></tr>
<tr><td>PNP Device ID</td><td>PCI\VEN_8086&DEV_1616&SUBSYS_222317AA&REV_09\3&E89B380&0&10</td></tr>
<tr><td>Adapter Type</td><td>Intel(R) HD Graphics Family, Intel Corporation compatible</td></tr>
<tr><td>Adapter Description</td><td>Intel(R) HD Graphics 5500</td></tr>
</table>

Here's how I disable the weird dimming behaviour:
- _Control Panel > Hardware and Sound > Power Options_
- In the currently selected energy plan, click _Change plan settings_ => _Edit plan settings_ opens. 
- Click _Change advanced power settings_ => pop-up _Power Options_ appears
- Expand _Intel(R) Graphics Settings > Intel(R) Graphics Power Plan_ and change _On battery_ and _Plugged in_ to _Maximum Performance_
- Click _OK_ => dialog closes and screen gets brighter (if it wasn't yet at maximum brightness)

After doing this I no longer have the problems I described in my previous post.
Sorry about the confusion, I just hadn't experienced that problem anywhere except in Postman, so I suspected Postman. I hope this helps. If you need any more details about my system let me know.

**Comment by a85** [comment]
Glad it's sorted out @Alicia-L. Closing this ticket. Let us know if you need any help.
