### ISSUE TITLE
DOWNLOAD COLLECTION WITH ENVIROMENTS

### ISSUE THREAD

**Issue by jzeferino** [a85/POSTMan-Chrome-Extension#1733]
hello. when i download a postman collection and import it on another computer the environments don't export too.
i can export them separately but i don't want to do that.
there is any way to export the collection and the associated environments to a single file?

**Comment by ronteddu** [comment]
Currently you can do that by exporting an entire dump. However, this means, all collections, all environments, globals and header presets are saved to the one file. There is no ability to export individual collections with attached environment and/or global file.

**Comment by jzeferino** [comment]
ok thank you.
