### ISSUE TITLE
OAuth header not immediately used

### ISSUE THREAD

**Issue by cawoodm** [a85/POSTMan-Chrome-Extension#1735]
Setup a request with OAuth2 and, the first time I pressed "Send" it did not add the header. Just pressed "Send" again and it did. Seems to be some delay/hesitation in saving/loading the token and I think it needs to be checked as send is clicked.

I can provide a Fiddler dump of the 2 requests if it helps.

**Comment by abhijitkane** [comment]
@cawoodm Can you mention the Postman version you're using?

**Comment by cawoodm** [comment]
I'd just downloaded it so it must be the latest 3.2.17.

I noticed the user needs to click the link/name of the token for it to be added as a header. Possibly this is just unintuitive to new users.

**Comment by sdnts** [comment]
@cawoodm Can you try updating to the latest version (4.8) and check if this is still an issue? Feel free to reopen if it is :)
