### ISSUE TITLE
Can't save {{$guid}} to environment variables using tests any more?

### ISSUE THREAD

**Issue by janpio** [a85/POSTMan-Chrome-Extension#1736]
Hi.

Before it was possible to use `{{$guid}}` as a form data variable (e.g. `transaction_id`) value and then save it to the current environment for later usage in other requests by executing this code in the test:

```
postman.setEnvironmentVariable("transaction_id", request.data.transaction_id);
```

`request` is the request object, `request.data` the form data and `request.data.transaction_id` contained the calculated value of `{{$guid}}`.

Was this behaviour changed in a recent update? Now I get a totally different guid in my environemnt that has nothing to do what was sent to my server.

Is there another solution to use a random value as a test parameter and save it to the environment at the same time?

Thanks.

**Comment by janpio** [comment]
Oh my, now it's getting strange: The exact same behavious that doesn't work when manually executing tests works fine in the Collection runner. Huh?

**Comment by abhijitkane** [comment]
@piotrowski What version of the app are you using?

**Comment by janpio** [comment]
```
Version 3.2.16 (packaged) OS: win
Architecture: x86-32
Native client architecture: x86-64
```

**Comment by abhijitkane** [comment]
I'm not able to reproduce this on 3.2.16. Can you import this collection and see if the test runs for you - https://www.getpostman.com/collections/4afc47d0de913285a2b6?
You'll need to have an environment selected.

**Comment by janpio** [comment]
Ok, will do. Here is my collection where I could reproduce this behaviour:
https://www.getpostman.com/collections/7ede2a9880b32a97e248
Manual execution sends different value, collection runner the same one.

**Comment by janpio** [comment]
@abhijitkane Ran you collection with a empty test environment twice, manually and in the collection runner - see image for result:

![fail-pass](https://cloud.githubusercontent.com/assets/183673/13153010/31bbdd00-d672-11e5-94b5-c60737694633.PNG)

**Comment by abhijitkane** [comment]
@piotrowski Does it work if you change `setEnvironmentVariable` to `setGlobalVariable` and `environment.sampleId` to `globals.sampleId`?

**Comment by janpio** [comment]
No, same behaviour.

(Test with changes: https://www.getpostman.com/collections/996021908981ff7b51f7)

**Comment by abhijitkane** [comment]
Do you see any errors in the console (http://blog.getpostman.com/2015/06/13/debugging-postman-requests/) when you send the request?

**Comment by janpio** [comment]
"You can right click on the main Postman window > Inspect element." never worked worked for me on Windows, so I used chrome://inspect -> Apps to get to the correct window. Hope this is the same thing.

> Do you see any errors in the console when you send the request?
1. No, I don't. I didn't even see the request!
2. So I found out I had this "Interceptor" thing activated. 
3. And Interceptor has its own Developer Tools where I see the request now. But no errors.
4. Wait a minute, I bet "Collection Runner" doesn't use the Interceptor but its own connection, with its own Developer Tools. What happens when I disable it? 
5. Yeah, the test succeeds when I disable the Interceptor!
6. It seems the interceptor was the reason for my problem. With it deactivated I can save {{$guid}} to environment and globals variables again.

Is this intended behaviour or is there a bug/problem with the Interceptor?

**Comment by abhijitkane** [comment]
Ah..got it. There's a bug in the way requests with `{{$guid}}` are sent to the Interceptor. We'll be making a release soon which should fix this.

Thanks a lot for reporting this issue.

**Comment by abhijitkane** [comment]
@piotrowski Are you still seeing this?

**Comment by janpio** [comment]
No. With activated and deativated Interceptor the test both times succeeds.

Did you fix it or did it fix itself?

**Comment by abhijitkane** [comment]
We made a release of the Interceptor two weeks ago with the fix.
