### ISSUE TITLE
Overriding Protected Headers in Mac App

### ISSUE THREAD

**Issue by Dillie-O** [a85/POSTMan-Chrome-Extension#1737]
I apologize if this is in the wrong place. Please direct me accordingly.

I have an API that i'm testing locally, and when I do so I need to specify the appropriate Origin value in my header. When using the Chrome App, I installed the Interceptor plugin, added the Origin to my headers and everything worked fine.

However, this isn't working in the Mac app. I can use the "generate code" feature to verify the origin is in the header, but when I run the debugger on my API, the origin that it receives is "file://"

Is there a different way to override the headers for the Mac app that I'm missing?

Keep up the great work!

**Comment by CestDiego** [comment]
I have the same issue. If it's the local system this should be sending Origin `null` shouldn't it?

**Comment by abhijitkane** [comment]
This is currently a limitation of the XHR object that we use to make requests - https://developer.mozilla.org/en-US/docs/Glossary/Forbidden_header_name. We're working on using native libraries to make requests, but for now, we don't have any control over the origin header.

**Comment by Dillie-O** [comment]
Thanks for following up! I realize it is a bit of a fringe issue, and I have other projects that I'm using the desktop tool with that doesn't require this, but it would be nice to keep the functionality that we have with the Chrome app as much as possible.

Keep up the great work!

**Comment by byteshinobi** [comment]
This is affecting me as well.  The app I'm testing doesn't like the "file://" Origin, so I can't test it w/ the Mac app.  It's probably a misconfiguration in the app, but it'd be nice to be able to change the origin.

Thanks for a great app.  The standalone app will be a great improvement for me.

**Comment by sappenin** [comment]
I have this issue as well -- the weird "file:///" origin header is precluding access to one of my API's because the API requires a valid origin as part of its CORS checks.

**Comment by dan-searle** [comment]
I'm also encountering this issue, and it's seriously limiting what we can use Postman for.

**Comment by stevemcmillen** [comment]
This issue is 100% blocking fo is impacting our use of POSTMan

On Mac App:
Origin: file://

On Chrome App
Origin: chrome://extension...

Can we cause POSTMan to stop sending origin header?   Can this be done for Mac App?  For Chrome App?

**Comment by a85** [comment]
Can be done through the new Postman Runtime. Details here: http://blog.getpostman.com/2016/06/14/introducing-postman-runtime-more-power-better-control/

We have a build available on a channel that we are calling Postman Canary.
