### ISSUE TITLE
Run Button do not download postman

### ISSUE THREAD

**Issue by alvmunoz** [a85/POSTMan-Chrome-Extension#1738]
Hi, we have been reported by some customers that when they click our "Run Button" ( located in this page: https://developer.hotelbeds.com/docs ) after the pop-up is shown, they select the Chrome option, and instead of downloading Postman (cause they don't have it installed) a new tab is opened with the json file.

**Comment by a85** [comment]
@alvmunoz A web page doesn't have the relevant security permissions to detect/redirect based on installed apps just yet. We are adding a header bar on top that will point users to the Chrome/Mac app links. Guessing users are missing the "Open in Web View" warning message right now. https://www.dropbox.com/s/0fl4c51ik8e0787/Screenshot%202016-02-19%2016.19.50.png?dl=0

**Comment by alvmunoz** [comment]
Thanks for the label.

Probably most of the users do not know that to "Open with... Chrome App" they actually need to have the App installed.  

But doesn't sound that you can do much about it.  
Thanks for your help.
