### ISSUE TITLE
How to spell test to check JSON value against a variable.

### ISSUE THREAD

**Issue by kmacharg** [a85/POSTMan-Chrome-Extension#1739]
Hello,

Let me first say I am loving postman, it has been an invaluable tool for testing my teams APIs.

I am trying to write tests using the _JSON value check_ and checking the results are equal to a variable defined in a file, however my test keeps failing and I am wondering if I am just doing some Javascript wrong.

`console.log(tests["Client ID is correct"] = jsonData.data.client_stack_id === "{{client_stack_id}}");`

Is there a different way to reference variables in this circumstance or am I just trying to do something that can't be done.

**Comment by mstaalesen** [comment]
You can't access the variables with '{{var}}' in your tests, that only works in Body. You have to access the environment variable like this: postman.getEnvironmentVariable("client_stack_id")

So in this case:
`tests["Client ID is correct"] = jsonData.data.client_stack_id === postman.getEnvironmentVariable("client_stack_id");`

(If it is a globalvariable, the method is `postman.getGlobalVariable("client_stack_id")`)

Also, if your comparing an integer, I've experienced that you might have to use parseInt() or !isNaN() around  your variable. 

Hope this helps.

edit: 
Just noticed you said variable defined in a file. If you are using a file as a feeder, the data is stored in the object 'data'. Then you could do something like this:

```
serverData = JSON.parse(responseBody); // Added this because I'm not sure what the value of  jsonData.data.client_stack_id actually is.
tests["Client ID is correct"] = serverData.client_stack_id === data.client_stack_id;
```

**Comment by kmacharg** [comment]
@mstaalesen 
Sorry for the slow reply on my part.  This is exactly what I needed.

Thanks for the very speedy reply.
