### ISSUE TITLE
OAuth 2.0 - Could not send request

### ISSUE THREAD

**Issue by abelhabel** [a85/POSTMan-Chrome-Extension#1740]
When using the Authorization feature in Postman 3.2.16 I get this error:

"error getting access token from client_credentials flow. Could not send request"

All fields are filled in except scope. Using Fiddler on windows I can see that neither the "Authorization Url" or the "Access Token Url" are contacted.

Same error on windows and on ubuntu.

**Comment by abhijitkane** [comment]
That message is in the "error" handler for the XHR call. In the client credentials flow, Postman makes a POST request to the access token URL with `data = grant_type=client_credentials&scope=" + scope`

Can you ensure that there are no leading/trailing spaces in the access token URL? Also, you can make the request in Postman yourself. Enter the Access Token URL in the main URL bar, and make a POST request. It's possible the server might be returning a 500 error.

**Comment by abelhabel** [comment]
Sorry for being unspecific.
1. There are no trailing spaces.
2. The url works just fine and returns an access token as json in the body. The url expects an Authorization header with [Basic base64(key:secret)] and [grant_type=client_credentials] in the body.
3. No, see 2.

As I mentioned, Fiddler does not even register postman contacting the access token url. What I can see is that postman contacts the host once on port 403, which I assume is the https handshake. But no other outgoing traffic.

**Comment by abhijitkane** [comment]
If you open the Network tab (http://blog.getpostman.com/2015/06/13/debugging-postman-requests/), you should be able to see an entry made when you start the client credentials flow.

That might help to figure out what's going on.

**Comment by abelhabel** [comment]
Thank you! 

I had a look at that earlier but could not get the console to open. Right clicking seems to be disabled in Postman but I went to chrome://inspect/#apps instead.

Now I can see that Content-Type is application/x-www-form-urlencoded; charset=UTF-8 which Amazon's API Gateway doesn't support. So I will try to map the body to valid json as it comes in to API gateway.

I also see now that OAuth 2 should have Content-Type set to application/x-www-form-urlencoded in the specification: https://tools.ietf.org/html/rfc6749#section-4.4.2

Thank you again for your help.
