### ISSUE TITLE
query: how to verify results when using data files

### ISSUE THREAD

**Issue by rvnath** [a85/POSTMan-Chrome-Extension#1741]
I am a newbie to POSTman, trying to lean / automate a few test cases.  I created a CSV datafile having 3 rows of data.  Tring to test my web service api (http://localhost:port/accservice/balance).

My test data in CSV:

> userid
> user1
> user2
> user3

The web service response is different for each row iteration because 
- user1 is a valid user with balance
- user2 is a non-existing user
- user3 is a forbidden user
  So, my web service returns different responses in each case.  

Now, if I am writing test for a single URL, but with different datasets, is it possible to map the responses correctly?  If so, how to do this?  

Or, should I create 3 different test cases in my collection?

**Comment by mstaalesen** [comment]
Depending on how you have built your API and response messages, it could be possible to do by adding a second column in your CSV-file with response-codes (or messages) that you can check for. If you go a bit more into details about your API, I can attempt to create an example for you.

What does the request look like? (Username in the URL, or in the body of the message? Is it JSON or XML?)
What does the response look like, with examples of the 3 scenarios you mention?

**Comment by elssar** [comment]
Hi @rvnath, like @mstaalesen said, you can add more fields to the CSV, containing the expected response code (and response type, response body if required) for each user. Then in your test, you can check whether the response code matches the expected response code

```
tests["Expected response code"] = responseCode.code === data["responseCode"];
```

Also, this [blog post](http://blog.getpostman.com/2014/10/28/using-csv-and-json-files-in-the-postman-collection-runner/) on how to use CSVs in the collection runner might be helpful.

**Comment by rvnath** [comment]
Thank you. Will check this out.

**Comment by rvnath** [comment]
I am trying to test POST url for authentication.  My URL is like this:
`http://localhost:4500/authenticate`
and the POST data format is a simple json like below.

```
{
    "username":"user_xxx",
    "password":"somesecret"
}
```

I have not yet tried (about to), but is it possible to have variable names using double-curly-braces in a POST data like this?

```
{
    "username":"{{user_xxx}}",
    "password":"{{somesecret}}"
}
```

**Comment by elssar** [comment]
@rvnath yes you can use variables in your post body.

**Comment by rvnath** [comment]
Thanks, it works.  That's fantastic!
