### ISSUE TITLE
Collections are not saved locally

### ISSUE THREAD

**Issue by anilkonduru** [a85/POSTMan-Chrome-Extension#1742]
Should i be logged in every time to use my existing collections? i am loosing all the collections after closing chrome, i remember having collections locally without login...please advice.

**Comment by sobtiankit** [comment]
@anilkonduru Not sure I understand completely. When you sign out AND close the app , it deletes your collections?

**Comment by anilkonduru** [comment]
Sorry if it was confusing. After I close postman and chrome, I am loosing
collections and have to import again, this happens when I don't sign-in. I
thought chrome cache collections for postman no matter user is signed in or
not.

So does it require to be logged in to maintain collections on postman? so
that I can use as soon as I launch it?

Thanks

On Sunday, February 21, 2016, Ankit Sobti notifications@github.com wrote:

> @anilkonduru https://github.com/anilkonduru Not sure I understand
> completely. When you sign out AND close the app , it deletes your
> collections?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/postmanlabs/postman-app-support/issues/1742#issuecomment-186880745
> .

## 

Sent from iPhone

**Comment by abhijitkane** [comment]
@anilkonduru That's odd - we haven't had this reported before. Are you losing all collections when you restart Postman? If so, you might need to reinstall the app - this is probably a case of your local app's database being corrupted in some way.
