### ISSUE TITLE
ERR_SSL_FALLBACK_BEYOND_MINIMUM_VERSION

### ISSUE THREAD

**Issue by anilkonduru** [a85/POSTMan-Chrome-Extension#1743]
Does anyone came across this issue?

SSL server probably obsolete.
ERR_SSL_FALLBACK_BEYOND_MINIMUM_VERSION

**Comment by abhijitkane** [comment]
@anilkonduru Where are you seeing this? A few screenshots would help. Feel free to re-open if you're still facing this.
