### ISSUE TITLE
Ability to see error code and message for failed requests in Collection Runner

### ISSUE THREAD

**Issue by ronteddu** [a85/POSTMan-Chrome-Extension#1745]
Collection Runner when run via GUI from within Postman does a good job at running requests one after the other inside a collection, however, when a request or test fails, there is no ability to view what the error details are (for example ERROR_CODE and ERROR_MESSAGE) as you would when the request is run outside the collection runner.

**Comment by gogonutsss** [comment]
This seems tobe pretty obviousin terms of importance,  any update?

**Comment by sdnts** [comment]
Hey guys, we've been working on a redesign of the Runner that should address your issue.

The new Runner is on our Canary channel, and you can download it for [OSX](https://dl.pstmn.io/download/channel/canary/osx_64) / Windows ([x86](https://dl.pstmn.io/download/channel/canary/windows_32) or [x64](https://dl.pstmn.io/download/channel/canary/windows_64)) / Linux ([x86](https://dl.pstmn.io/download/channel/canary/linux_32) or [x64](https://dl.pstmn.io/download/channel/canary/linux_32)) / [Chrome](https://chrome.google.com/webstore/detail/postman/loddepljkabcghihdkbkfknabkinanff)

I'd recommend you to join our Slack community [here](https://www.getpostman.com/slack-invite) so you can provide feedback before the runner moves to our stable builds :)

**Comment by sdnts** [comment]
@ronteddu @gogonutsss The new Runner is out with our latest version (4.9) on our native apps. Requests sent from the Runner have much more visibility now.
