### ISSUE TITLE
Not showing XML parse issue when response has invalid chars

### ISSUE THREAD

**Issue by praveenb** [a85/POSTMan-Chrome-Extension#1746]
If XML response data contains invalid chars like '&', postman app not showing XML parse issue. 

I've happen to check the response in another restclient app, to see the data issue.  Please fix this issue.

Thank you.

**Comment by abhijitkane** [comment]
@praveenb Can you give an example of such a response?
For me, a XML document like `<a><b c="&">&</b></a>`
renders properly in Postman:

```
<a>
    <b c="&">&</b>
</a>
```

**Comment by praveenb** [comment]
Hi@abhijitkane, Thanks for response
Sorry for the late reply...

Yes, as per given example
`<a>
    <b c="&">&</b>
</a>`

this kind of response fails XML validation as invalid entity name. Please check validation [here](http://www.xmlvalidation.com/) . 

Actually when an API's XML response is invalid (my Android app is crashes when parsing XML data). So if i happen to check the response in Postman, Its auto rendering the response instead of showing XML error. But other restclient showing XML error correctly. Which helps me to easily see the XML data issue.

The valid XML format should be as below 
`<a>
    <b c="&amp;">&amp;</b>
</a>`
(Android app won't crash when parsing)..
Its Just FYI. I thought it may be good feature to have XML validation in Postman too.

Thank you.

**Comment by sdnts** [comment]
@praveenb I tried replicating this in the latest version (4.8) and this looks like it is fixed.
Feel free to reopen if the issue persists :)
