### ISSUE TITLE
Builder tabs do not update its editor window height immediately

### ISSUE THREAD

**Issue by Simonpark819** [a85/POSTMan-Chrome-Extension#1747]
Hello, I just noticed a small bug that I've been experiencing in the postman mac client.

**Steps:**
- Under the "Builder" tab, click into any of the available editor sections (choose tests)
- Type up enough lines of text to extend beyond the current editor height (so you'd have to scroll down)
- Drag and extend the editor height so we can try to see all of our code

**Actual result:**
- The window height successfully extends but the actual editor doesn't seem to extend down with it
- It will only reflect the new change if you click into another section and click back into it

Not a big bug but would be nice to see a fix in the next patch/release!

**Comment by SamvelRaja** [comment]
Thanks for bringing this to our notice. We have found the RC. Will add it in the next release.

**Comment by Simonpark819** [comment]
Awesome!!

**Comment by SamvelRaja** [comment]
@Simonpark819 we have fixed in the latest mac `4.0.3` can you check the same and close the issue.

**Comment by Simonpark819** [comment]
confirmed fixed!
