### ISSUE TITLE
OAuth 1.0 timestamp missing

### ISSUE THREAD

**Issue by jaredhanks** [a85/POSTMan-Chrome-Extension#1748]
I just updated to Postman 4.0 Mac app.  I am noticing the OAuth `timestamp` is blank and it doesn't appear to be updating when making requests.  It appears the `nonce` might also not be updating on each request either.

This works fine in the Chrome extension still (v3.2.17), so wasn't sure if this is something that changed with the 4.0 release or not.

**Comment by abhijitkane** [comment]
@jaredhanks Thanks for reporting this. We've fixed this, and it should be available in the next release.

**Comment by Fr4ncis** [comment]
When I tried to update the Mac app (stable release) it actually downloaded the 4.0 beta breaking all the collection. PLEASE be careful with these changes, people rely on the stable version for their work!

**Comment by abhijitkane** [comment]
The 4.0 beta should only be available through a window that says "experimental build". Furthermore, all your collections should work even after updating to 4.0 beta. What's the issue you're facing with the 4.0 beta?

**Comment by Fr4ncis** [comment]
From the v3 app > "Postman" menu > Check for updates

however, timestamp is not updated and nonce does not get updated, it lost the "auto add" parameter function and "update request" does not regenerate those parameters.

Thanks for the prompt response.

**Comment by Fr4ncis** [comment]
Even from www.getpostman.com it downloads automatically the beta.. :-1: how can I download again the v3 app?

**Comment by abhijitkane** [comment]
@Fr4ncis What's the version number of the app that you're using? v4.0.0 is not the beta.
v3 for the Mac app is no longer available.

**Comment by Fr4ncis** [comment]
ok it makes sense then. v4.0.0 while the browser extension (which is still working) is v3.2.18

let me know, I can provide the collection and keys privately or jump on a call.

**Comment by stloc** [comment]
not possible to use twitter API because of this regression
because Nonce parameter is refresh every time

**Comment by abhijitkane** [comment]
@stloc 
https://dev.twitter.com/oauth/overview/authorizing-requests

```
Nonce
The oauth_nonce parameter is a unique token your application should generate for each unique request. Twitter will use this value to determine whether a request has been submitted multiple times. The value for this request was generated by base64 encoding 32 bytes of random data, and stripping out all non-word characters, but any approach which produces a relatively random alphanumeric string should be OK here.
```

The nonce value is supposed to be a randomly generated alphanumeric string that is supposed to change each time you make a request. I'm able to make requests to the Twitter API via Postman. Can you confirm the version of the app you're using?

**Comment by stloc** [comment]
@abhijitkane 

**twitter generated curl call from https://dev.twitter.com/oauth/tools/signature-generator/12102315 (result OK) :**

curl --get 'https://api.twitter.com/1.1/search/tweets.json' --data 'q=%23bretagne&result_type=popular' --header 'Authorization: OAuth oauth_consumer_key="fEgiyvQs5RkKlpWGER7yjtD4X", oauth_nonce="cb368cfe9c4b6eec05d946e8296ead15", oauth_signature="CwAs6r1Q1Jnk2YYnh69UBIAP6i8%3D", oauth_signature_method="HMAC-SHA1", oauth_timestamp="1458224905", oauth_token="260632610-XMHNzQMsrVfAW5f9cOlZncaKXg43hBMRFiC2iWno", oauth_version="1.0"'

**postman test (KO) :**

curl -X GET -H "Authorization: OAuth oauth_consumer_key="fEgiyvQs5RkKlpWGER7yjtD4X",oauth_token="260632610-XMHNzQMsrVfAW5f9cOlZncaKXg43hBMRFiC2iWno",oauth_signature_method="HMAC-SHA1",oauth_timestamp="1458225256",oauth_nonce="Gi7N3D",oauth_version="1.0",oauth_signature="r4nmjs8dbJOYcoqnYrkwfQesjkU%3D"" "https://api.twitter.com/1.1/search/tweets.json?q=%23bretagne&result_type=popular"

postman version : 4.0.5, ( linux / x86-64 ), ( Chrome 49.0.2623.87 )

**Comment by abhijitkane** [comment]
@stloc Are you still seeing this with v4.4.1?

**Comment by stloc** [comment]
@abhijitkane yes ! and the problem is solved
