### ISSUE TITLE
OAuth 2.0 - Incorrect Authorization header value

### ISSUE THREAD

**Issue by abelhabel** [a85/POSTMan-Chrome-Extension#1749]
Using OAuth 2.0 Authorization with 'Add token to header' using these values:

Client ID: 6CD9WUBZPXV4LJ15VD7A7ZYU7
Client Secret: 52X/nWSkZw0iEJ7iijV4G0f06pxet9MsfBi9HTMSC3s
Scope: 
Grant type: Client Credentials

creates this base64 encoded string in the Authorization header:
Basic NkNEOVdVQlpQWFY0TEoxNVZEN0E3WllVNzo1MlglMkZuV1NrWncwaUVKN2lpalY0RzBmMDZweGV0OU1zZkJpOUhUTVNDM3M=

The correct header should be:
Basic NkNEOVdVQlpQWFY0TEoxNVZEN0E3WllVNzo1MlgvbldTa1p3MGlFSjdpaWpWNEcwZjA2cHhldDlNc2ZCaTlIVE1TQzNz

I can recreate this with similar length of ID and Secret but shorter strings, ie abc, 123, encodes correct.

**Comment by jhnlsn** [comment]
I believe a bug that I am experiencing might be related to this as well?

if either clientId or clientSecret have a `#` value, it is turned into `%23`

fore example:

```
client ID = client1
Client Secret = Password#1
```

my auth server decodes the base64 hash as

`client1:Password%231`

**Comment by skymeyer** [comment]
Same here using the following test client credentials:

```
Client ID: 690eb7ed-2dcf-48d6-887c-78c7f5fb7d39
Client Secret: >TzkfU>dvoBVbn?Et,(Mot<>SK
```

My auth server reports `%3ETzkfU%3EdvoBVbn%3FEt%2C(Mot%3C%3ESK` as the client secret when trying to obtain an access token through postman using the `client_credentials` grant type. Looks like some url encoding action is going on on the client secret.

**Comment by sdnts** [comment]
Hey guys, we've made several improvements to the Auth signature calculation. Can you try updating to the latest version (4.8) and check if this issue is resolved?

**Comment by 1digicoder** [comment]
Issues remains with v4.8. I have the same issue as above, and for me, I'm using the $ sign.

It's being escaped as %24.

This was being used to troubleshoot a PowerShell automation error due to the similar encoding issue. The users were going to use Postman to validate the bug was fixed, when we found a similar bug there.

**Comment by sdnts** [comment]
Hmm, let me investigate this and I'll get back to you here :)

**Comment by sdnts** [comment]
We've identified what was causing this, and will be pushing out a fix in the next release.

**Comment by sdnts** [comment]
Can you guys try updating to the latest version (4.8.3) and see if this issue still persists?

**Comment by 1digicoder** [comment]
This was resolved. I tested with 4.8.3 and its fixed. Thank you.

**Comment by skymeyer** [comment]
This looks ok with here too on 4.9.0, thanks.

**Comment by james-d-elliott** [comment]
The original implementation of this was actually correct. See the following snippet from [RFC6749 Section 2.3.1](https://datatracker.ietf.org/doc/html/rfc6749#section-2.3.1):

> Clients in possession of a client password MAY use the HTTP Basic
   authentication scheme as defined in [[RFC2617](https://datatracker.ietf.org/doc/html/rfc2617)] to authenticate with
   the authorization server.  The client identifier is encoded using the
   "application/x-www-form-urlencoded" encoding algorithm per
   [Appendix B](https://datatracker.ietf.org/doc/html/rfc6749#appendix-B), and the encoded value is used as the username; the client
   password is encoded using the same algorithm and used as the
   password.  The authorization server MUST support the HTTP Basic
   authentication scheme for authenticating clients that were issued a
   client password.
   
Both the client id should be encoded with `application/x-www-form-urlencoded` values. Only then should they be base64 encoded (or sent in the post form).
