### ISSUE TITLE
Request are treated as edited after switching between them

### ISSUE THREAD

**Issue by marrko** [a85/POSTMan-Chrome-Extension#1750]
Hello, I just experienced minor bug in windows Postman client. I have created multiple POST and GET requests.
**Steps:**
- opened POST request with filled body with JSON data
- opened random GET request
- opened another POST request but this time with empty body (body type is set to raw)

**Result:**
Postman client treats the POST request as it has been modified so after choosing another request, it is opened in new tab. 

Can you please take a look at this? After going through multiple requests this way it became confusing and immense.

**Comment by srbangre** [comment]
+1
Its not only with POST requests. Its happening with get requests as well.
I tried restarting Postman and then my windows machine but no use.
Also this is intermittent, meaning it doesn't happen all the time. but its irritating.

this is happening when i open the request from collection and submit the request. the orange circle shows up without changing anything in the request.

**Comment by a85** [comment]
We are pushing a new version of the Chrome app that should fix this along with other issues.

**Comment by srbangre** [comment]
@a85 - there is another problem here. 
I have 2 environments saved. so if i run one test case in env1 and save it.
next time i am switching to env2. this time the orange circle shows up. I did not change anything in the tests still its asking me to save the test.

**Comment by a85** [comment]
This should be fixed in 4.0+
