### ISSUE TITLE
Response JSON pretty print formatting

### ISSUE THREAD

**Issue by ahvonenj** [a85/POSTMan-Chrome-Extension#1751]
Could we have an option to format response JSON pretty print like so that `{` and `[` are always on their own line like so:

Currently:

```
{
  "error": false,
  "code": 0,
  "data": {
    "bundle": {
      "meta": "1"
    }
  }
}
```

How I'd like it:

```
{
  "error": false,
  "code": 0,
  "data":
  {
    "bundle":
    {
      "meta": "1"
    }
  }
}
```

Having `{` and `[` on their own lines makes JSON data significantly easier to read in my opinion. Even better if we could change the amount of tabs / spaces.

**Comment by a85** [comment]
Unfortunately not on the cards any time soon as we are working on a separate data editor. Will look at this thread in the future.
