### ISSUE TITLE
Postman not sending "Content-Type" header

### ISSUE THREAD

**Issue by wszydlak** [a85/POSTMan-Chrome-Extension#1753]
When opening a new tab in Postman, you can see in the _Body_ tab, that default Content-Type is set to **form-data**, but if you send a request, the header is not sent. When you switch to eg. **raw** and then back to **form-data**, then the header will be sent.

Tested versions: 
- 2, 3 - Google Chrome for Mac Os
- 4 - Mac Os

**Comment by abhijitkane** [comment]
@wszydlak Are you still seeing this with the latest versions of the app?

**Comment by wszydlak** [comment]
Yes, when You does'nt fill any form-data (key - value pairs) then header with content type is not being sent
