### ISSUE TITLE
Scroll position resets to the top when re-sending current request

### ISSUE THREAD

**Issue by martinjbaker** [a85/POSTMan-Chrome-Extension#1755]
I'm using 4.0.0 and am not sure when this changed but it used to be that if you had scrolled down the response and pressed Send again, then the previous scroll position would be retained.

This is no longer the case. The scroll position now resets to the top which is super annoying if you're looking at a particular section of a long response!

**Comment by srbangre** [comment]
+1

**Comment by a85** [comment]
Not sure if we ever explicitly stored the scroll position.

**Comment by sankalp0o** [comment]
I just checked it on the latest version and this is no longer the case, hence closing this. Feel free to open this if needed.
