### ISSUE TITLE
Selecting no "No environment" in Collection runner unable to cancel

### ISSUE THREAD

**Issue by KotieSmit** [a85/POSTMan-Chrome-Extension#1756]
When by accident I don't select an environment to use for a collection to run, there is no way to cancel the action.

I have a message "Please wait while your test results are being initialized...."

I have to close the collection runner and re-open

**Comment by sdnts** [comment]
@KotieSmit Is this still happening in the latest app (v4.8.3)? Feel free to reopen if it does.
