### ISSUE TITLE
Response display error

### ISSUE THREAD

**Issue by ghost** [a85/POSTMan-Chrome-Extension#1759]
After making a GET request and getting a the JSON response, when I switch to another tab than body the code is only displayed on the half of the element.

**Comment by SamvelRaja** [comment]
@romainisnel  I tried reproducing your issue but I couldn't it. It might be related to #1747, can you update the app to `4.0.3` and try reproducing the same.
Please let us know if the problem still persist.

**Comment by ghost** [comment]
@SamvelRaja The error is gone since 4.0.3. Problem solved
