### ISSUE TITLE
Oauth Issues in 4.0.2

### ISSUE THREAD

**Issue by sumeetfefar** [a85/POSTMan-Chrome-Extension#1760]
I am facing OAuth issues on Mac App. 

1) OAuth 1.0 'Update Request' call gives `Uncaught TypeError: oAuthParams[i].value.trim is not a function` on Console and never fetches the access token.

2) OAuth 2.0 generates token which is not immediately reflected on token list, It adds the the token in url but when 'Send' in pressed, it gives `Uncaught TypeError: currentHelperProcessor.process is not a function` on console and request never terminates(stuck on 'Loading... / Cancel Request').

App version is 4.0.2

**Comment by Fr4ncis** [comment]
Uncaught TypeError: oAuthParams[i].value.trim is not a function

same issue, this is our collection, /token/generate does not work https://www.getpostman.com/collections/fc13d501598107a36184

**Comment by abhijitkane** [comment]
@Fr4ncis @sumeetfefar Are you still facing these issues?

**Comment by Fr4ncis** [comment]
Not at the moment
