### ISSUE TITLE
Postman Sync alters sorting

### ISSUE THREAD

**Issue by darrylkuhn** [a85/POSTMan-Chrome-Extension#1761]
It appears that when syncing a postman collection some of the requests show up in a different order than originally set. Please let me know what details I can provide to help troubleshoot the issue.

**Comment by sobtiankit** [comment]
Hi @darrylkuhn, did you observe this while importing a collection? You can mail help@getpostman.com with the details and we will investigate from there.

**Comment by darrylkuhn** [comment]
I have followed up via email and will close the ticket here.
