### ISSUE TITLE
Postman Malformed JSON

### ISSUE THREAD

**Issue by parthcodes** [a85/POSTMan-Chrome-Extension#1762]
Hi,

I am trying to test a REST API in my local from Postman, where I am getting following error:

Malformed JSON: Expected 'r' instead of 'e' in "Pretty" tab of the response. **In "Raw" and "Preview" give correct response.**

Can you help me understand what can be a problem here ?

![image](https://cloud.githubusercontent.com/assets/7152857/13376309/e371d408-dd86-11e5-8973-7e6aee838d56.png)

![image](https://cloud.githubusercontent.com/assets/7152857/13376314/1c3c1e56-dd87-11e5-981a-757c674ecc8a.png)

**Comment by abhijitkane** [comment]
@parthcodes The pretty view's JSON mode is meant for JSON responses only. If you change the JSON in the dropdown to text, you should be able to see the response in the pretty view.

Try hitting a URL like http://echo.getpostman.com/get. You'll be able to use the 'JSON' view in the pretty mode.

**Comment by clintfidel** [comment]
make sure what you are passing in is in the right json format.....
it should be like this 
{ 
"title": "coding"
"author": "clintfidel"
}
i solved my own error like this

**Comment by shoaibjdev** [comment]
@clintfidel - Still your JSON is incorrect, A comma is missing after "title": "coding"

I too faced the same issue, and it was missing comma issue during transformation on API Gateway layer.

**Comment by wnmurphy** [comment]
Got same error in Postman without the "Malformed JSON" bit. Clicking on `raw` tab for body showed data was received, turns out it was malformed JSON. If you get this error or something similar, try grabbing the body from the `raw` tab and linting it.
