### ISSUE TITLE
BUG : Copy result to enviroment don't work anymore last version

### ISSUE THREAD

**Issue by paolobiavati** [a85/POSTMan-Chrome-Extension#1764]
In the chrome extension versione I can select a string from the result of an api call anche put the value into an enviroment variable, this is cool.  But I cant't do the same in mac app

**Comment by paolobiavati** [comment]
This feature don't work ALSO in the new chrome extension version.
You right click on a result and the pop up menu say "set >ACTIVE_ENVIROMENT> / <KEY> " but this dont set a value!! please fix this!   it copy a white space instead of the selected string

**Comment by abhijitkane** [comment]
@paolobiavati We've fixed this in our internal build, and we're rolling out the fix in our Chrome version over the next few days.

**Comment by dcc635** [comment]
We are also waiting on this in the Mac app. Thanks for the fix.

**Comment by abhijitkane** [comment]
@dcc635 @paolobiavati Can you confirm this fixed in the latest version?

**Comment by paolobiavati** [comment]
Yes! it works in chrome and mac version!  thanks
