### ISSUE TITLE
Postman Chrome app returns a 500 on HTTPS POST if Chrome debugging flag disabled

### ISSUE THREAD

**Issue by hainna01** [a85/POSTMan-Chrome-Extension#1766]
We are having an issue where we receive a 500 error when attempting to POST to an HTTPS endpoint in one of our APIs.

In part of our debugging we followed [these instructions](http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/) to enable debugging and upon enabling that flag, our request went through and no longer had any issues.

The Mac app initially did not work either, but after the update around 2/25/2016 it started working without issue.

Chrome App Version: 3.2.19
Mac App Version(working): 4.0.2
OS: Mac OSX 10.11.2

**Comment by abhijitkane** [comment]
@hainna01 Enabling DevTools should have had no effect on the request that was sent. What was the error you received? If it's due to an incorrect payload, it might be a bug with Postman. But if what you enter in Postman's UI is what's being sent, then it's probably a server issue.

**Comment by hainna01** [comment]
Unfortunately I cant include the exact request. I can say with certainty that the request didn't work before the debugging flag was enabled, but it works just fine after its enabled. We've been able to reproduce this many times on different computers.

**Comment by abhijitkane** [comment]
If you're getting a 500, there must be some sort of server log that could help explain what went wrong. Unless there's a mismatch between the expected request from Postman and the request that's sent, I'm not sure where to start looking.

**Comment by jordancaradonna** [comment]
where do you access the server logs?
