### ISSUE TITLE
Wrong Status code when interceptor is enabled 

### ISSUE THREAD

**Issue by maryam514** [a85/POSTMan-Chrome-Extension#1769]
I am having 502 bad gateway status code while interceptor is enabled where i need to show 403 forbidden status.
What does that mean and how can i get same status code with interceptor enabled ?

**Comment by abhijitkane** [comment]
@maryam514 The 502 is thrown for the server. You'll need to check the server logs to see why it's being thrown. The difference is because enabling the Interceptor sends the cookies for that domain.
