### ISSUE TITLE
OAuth issue in 4.0.3

### ISSUE THREAD

**Issue by Fr4ncis** [a85/POSTMan-Chrome-Extension#1770]
Postman (Chrome and Mac) v3 work fine.
Postman v4 (Mac) fails.

try /token/generate in:
https://www.getpostman.com/collections/fc13d501598107a36184

environment (I can send you privately consumer key / secret)

{
    "id": "92e77a44-49a2-113f-b754-c2d66e63b624",
    "name": "MAPI Prod v3.5",
    "values": [
        {
            "key": "apiServer",
            "value": "mapi.vouchercodes.co.uk",
            "type": "text",
            "name": "apiServer",
            "enabled": true
        },
        {
            "key": "apiVersion",
            "value": "v3.5",
            "type": "text",
            "name": "apiVersion",
            "enabled": true
        },
        {
            "key": "oauthToken",
            "value": "46f7400fef2fdd57ed65af5c12ac08e7",
            "type": "text",
            "name": "oauthToken",
            "enabled": true
        },
        {
            "key": "oauthTokenSecret",
            "value": "524d26a7f1a6d5646a4b3dc693010610a1fa780e75ca741dc47ed858a050e71b",
            "type": "text",
            "name": "oauthTokenSecret",
            "enabled": true
        },
        {
            "key": "consumerKey",
            "value": "<HIDDEN VALUE>",
            "type": "text",
            "name": "consumerKey",
            "enabled": true
        },
        {
            "key": "consumerSecret",
            "value": "<HIDDEN VALUE>",
            "type": "text",
            "name": "consumerSecret",
            "enabled": true
        },
        {
            "key": "token",
            "value": "74a4b708211d15f7406c05d5a7f83632",
            "type": "text",
            "name": "token",
            "enabled": true
        },
        {
            "key": "randomValue",
            "value": "550",
            "type": "text",
            "name": "randomValue",
            "enabled": true
        },
        {
            "key": "timeNow",
            "type": "text",
            "value": "1456756056",
            "enabled": true
        }
    ],
    "timestamp": 1456828609616,
    "synced": false,
    "syncedFilename": ""
}

**Comment by abhijitkane** [comment]
@Fr4ncis Can you mail the consumer key and secret to help@getpostman.com?

**Comment by Fr4ncis** [comment]
I was told it was fixed in the internal release, is there going to be a new public release soon?

**Comment by abhijitkane** [comment]
@Fr4ncis Are you still seeing this issue?

**Comment by Fr4ncis** [comment]
Did not notice any issues!
