### ISSUE TITLE
Postman freezes

### ISSUE THREAD

**Issue by JuliaFernee** [a85/POSTMan-Chrome-Extension#1771]
After about 6 months of use Postman started failing. The window freezes after 2-3 click actions. Tried to restaret app & os, tried closing everything else in chrome. tried to kill process. tried to turn off inspector. still the same. 
Version 3.2.20 (packaged) OS: win
Architecture: x86-32
Native client architecture: x86-64
Chrome Version 48.0.2564.116 m

**Comment by abhijitkane** [comment]
@JuliaFernee Can you enable DevTools (http://blog.getpostman.com/2015/06/13/debugging-postman-requests/), and check the console for any errors when you open the app and when it freezes?

**Comment by calebrepkes** [comment]
I also had this problem. I closed down most tabs on my browser (windows). 
Made sure all my collections and templates are stored in the cloud part. 

Then removed the extension. Then installed it again. And now its working fine. But I have a strong feeling this is only a workaround. As I have done this now twice.

**Comment by JuliaFernee** [comment]
Yeah, I stopped short reinstalling it becaue in it's current state I can't even backup the collections. Any thoughts how to hack a data backup outside Postman's export?

**Comment by abhijitkane** [comment]
@calebrepkes @JuliaFernee approximately how many collections do you have?
If the app is still freezing on start, can you enable DevTools (http://blog.getpostman.com/2015/06/13/debugging-postman-requests/), and check the console for any errors when you open the app and when it freezes?

**Comment by JuliaFernee** [comment]
15 collections with approx 10-20 items in each. Bear with me I'll do the DevTools  in a bit - my day
job needs my attention

**Comment by calebrepkes** [comment]
I have one collection with 32 request. And in it is various amounts of pre-request code, test code and variables. The freeze happens after roughly 5 seconds. So at first it looks like I can select some stuff. Though i do notice that the pane holding: All - Me - Team is not visible. I have the feeling some process is collapsing. 

Usually I just close my Dell Notepad, with +6 tabs open. Sometimes with tabs of Youtube (meaning memory usage). And do that for more than a week. Then after a couple of days it gets slower and slower. 

I have been checking the console earlier. Because I experienced it earlier already, and have also seen other issues reporting this. But I could not find any noteable error.

**Comment by JuliaFernee** [comment]
Enabled debugging for packed apps in chrome but not able to use it inside Postman - right click on main window unresponsive. Tried to close Postman & open again. It took something like 20 min to open. I will try to reinstall at the expense of loosing collections.

**Comment by calebrepkes** [comment]
@JuliaFernee there have been more reports of this issue. And where to find your collections on the local system. have you checked that route?

**Comment by calebrepkes** [comment]
This is the location on my Windows machine, where my collections should be:
C:\Users[UserAccount]\AppData\Roaming\Chrome\Datadir\Default\Extensions\fhbjgbiflinjbdggehcddcbncdddomop

Though i dont see me collections in there. Maybe because I sync them? @abhijitkane

**Comment by abhijitkane** [comment]
@calebrepkes Is that the location listed in chrome://indexeddb-internals? You should see a .leveldb folder there.

**Comment by JuliaFernee** [comment]
@calebrepkes @abhijitkane Thank you for your tips. I've found it. It is really well hidden. So if i copy contents of these dirs, reinstall postman extension and replace them with saved copies it will work? the contents should be something like chrome-extension_fhbjgbiflinjbdggehcddcbncdddomop_0.indexeddb.leveldb & chrome-extension_fhbjgbiflinjbdggehcddcbncdddomop_0.indexeddb.blob

**Comment by calebrepkes** [comment]
@JuliaFernee Thats at least what I understood, after reading the following blog earlier:
https://github.com/postmanlabs/postman-app-support/issues/569

No not same I see now @abhijitkane . But found the path mentioned there. So I understand now where to find it in the future if I need too.

**Comment by JuliaFernee** [comment]
I have reinstalled postman and have managed to recover my collections. The performance has improved. However, it seems there is an issue with this extention that causes it to degrade over a period of time.
