### ISSUE TITLE
Cookies not readable in MacApp

### ISSUE THREAD

**Issue by calebrepkes** [a85/POSTMan-Chrome-Extension#1772]
Just updated to MacApp 4.0.3. 
Really like the new look and the speediness of the app. 

Just one thing, I cant read the cookies, when using this piece of code:
`postman.getResponseCookie("CookieName");`

Even though when I click on Manage Cookies, I do see the cookies. 
In the left pane I see the host name: 
`server.local`
And on the right pane I see the cookies:
`CookieName=123; path=/test; domain=server.local;`

I have spend a lot of time looking at the Interceptor software already for three days. While in the end I realized that the interceptor part is integrated in the Postman Mac App. :-) :+1:

**Comment by abhijitkane** [comment]
Thanks for reporting this. We've fixed this internally, and will push a fix for this in the next release.

**Comment by calebrepkes** [comment]
Hey @abhijitkane , 

I have not seen this working in version 4.1.0
OS X 15.3.0 / x64

Could it be, because the build in interceptor is not intercepting cookies in the correct order when they are coming from http://localhost?

**Comment by calebrepkes** [comment]
After updating to MacApp 4.1.1
OS X 15.3.0 / x64

I dont see this fixed when im calling getSandbox localhost. But I do see it fixed when calling the below part: 
GET /cookies HTTP/1.1
Host: echo.getpostman.com
Cookie: foo5=bar5
Cache-Control: no-cache
Postman-Token: 5b8b6d9f-ad81-f196-022f-0ca9a7382d8b

So when I echo and put in the header the cookie. It is also returned and I see it in the response 'tab' (besides body and header). Works nice, really accessible. 

Though when Im connected to my localhost:8080 or 127.0.0.1:8080 I dont see the cookies nicely being retrieved. Even though the cookies are send by the server. And when connecting an app to that server, it is able to retrieve the cookies and work with it. 

Your thoughts @abhijitkane

**Comment by abhijitkane** [comment]
@calebrepkes The underlying API has an issue with 'localhost' as a domain. If you make all requests to 127.0.0.1 instead, (while setting the cookies too), it should work.

**Comment by abhijitkane** [comment]
@calebrepkes v4.4.1 of the Mac app fixes this.

**Comment by calebrepkes** [comment]
Hey @abhijitkane , 

Finally got around to confirm it. And yes it works perfectly now with 127.0.0.1. Thnx and keep up the great work.

**Comment by corneil** [comment]
I can confirm that 4.7.1 works with localhost as well as with 127.0.0.1 on Windows desktop.
