### ISSUE TITLE
Lost Collections

### ISSUE THREAD

**Issue by jeremy-walsh-vgh** [a85/POSTMan-Chrome-Extension#1774]
Hey, opened Postman today to find it had been upgraded and all my collections are gone.  Browsed various iterations of this issue report here and don't see a solution that works for me as I don't have access to a backup of this folder.  Is there any way to recover this?  I had a lot of solid gold hits in there.

**Comment by abhijitkane** [comment]
@jeremy-walsh-vgh Can you mention the current version of Postman that you are on? Also, was there a notification saying that you'd been upgraded?

**Comment by jeremy-walsh-vgh** [comment]
@abhijitkane  there were no notifications. I don't know how to tell what version it is.  Its extension url is chrome-extension://fdmmgilgnpjigdojojpjoooidkmcomcm/index.html if that helps.

For some reason, I have 2 extensions now, one that I used to use which is empty.  It has a planet icon with a refresh-looking green arrow over it.  There's also an orange Postman icon with a rocket man on it.

**Comment by abhijitkane** [comment]
The one with the blue icon is the legacy chrome.

If you were using the chrome-extension://fdmmgilgnpjigdojojpjoooidkmcomcm/index.html extension earlier (where your collections were), and if they're empty now, then I'm afraid we can't help. This seems like a case of corruption of the local database.

You could head to `chrome://indexeddb-internals/`, and search for fdmmgilgnpjigdojojpjoooidkmcomcm. If you're able to find any of the folders listed there, we might be able to recover your data.

If you just downloaded the new app (the orange icon one), that will be empty.

**Comment by jeremy-walsh-vgh** [comment]
It is listed, but it is all stuff that was created today :/

Thanks for the help, and for the awesome product.  Very useful.  I will have to back up my collections by hand from now on I guess.
