### ISSUE TITLE
Ability to dynamically generate the request body for POST

### ISSUE THREAD

**Issue by taposoft** [a85/POSTMan-Chrome-Extension#1775]
Hi ,

Can someone please post an example on how to create a dynamic request body which populates JSON objects (not just primitives/Strings).

I tried reading the input data from the test input file and setting that to an environment variable in the pre-request script. I tried with primitives and String and it works fine but as soon as i try to assign a JSON object dynamically in the request body, it doesn't work. 

Appreciate your time.

Example:

My input Data file looks like this. 
[{
"person": {
"id": "1",
"name": "Raghu",
"zipcode": "500050"
}
}
{
"person": {
"id": "2",
"name": "Prasad",
"zipcode": "500051"
}
}
]

This is how my pre-request script looks

postman.setEnvironmentVariable("person", JSON.stringify(data.person));

And this is how request body looks.
{
{{person}}
}

Thanks,
Raghu.

**Comment by abhijitkane** [comment]
@gotoraghu Each element in your JSON file will need to look like this:
```
{
      "person": "{\"id\": \"2\",\"name\": \"Prasad\", \"zipcode\": \"500051\"}"
}
```

and you request body will need to be:
```
{
	"person": {{person}}
}
```
