### ISSUE TITLE
File chosen is deselected from the History's requests

### ISSUE THREAD

**Issue by zvilich** [a85/POSTMan-Chrome-Extension#1776]
Hello,
With The form-data, Body parameters, Choosing a file attribute, choose a file . 
Then selecting another item in the history and returning to the previous item . 
the selected file is gone, "no file chosen".
I am using Mac .
Thanks
Yair 
![image](https://cloud.githubusercontent.com/assets/16776214/13436771/72c1ffc0-dfe9-11e5-8a7f-ca5b7e384ad9.png)

**Comment by abhijitkane** [comment]
@zvilich
This is currently a limitation of the Chrome platform - we store the file reference.

**Comment by zvilich** [comment]
Hi,
The reference for the file is not saved... i.e.
The link or the path. I dont mean the file itself.
Isn't postman only run under chrome?

בתאריך יום ג׳, 26 באפר׳ 2016, 15:47, מאת Abhijit Kane ‏<
notifications@github.com>:

**Comment by abhijitkane** [comment]
Postman does not have access to the path of the file either (only the filename).
It's also impossible to set the value for a file selector element. 
This won't be possible to do till we move out of Chrome.

**Comment by a85** [comment]
There is no sane way to store a reference to files right now.
