### ISSUE TITLE
Errors on Launch

### ISSUE THREAD

**Issue by RicDAC** [a85/POSTMan-Chrome-Extension#1778]
I have uninstalled and reinstalled Postman numerous times and am still facing the following error on launch - can you suggest a work around pls.

![image](https://cloud.githubusercontent.com/assets/17593340/13460928/3595bbcc-e076-11e5-81dd-f14fdbe026bd.png)

(also did an uninstall and reinstal of chrome)

**Comment by abhijitkane** [comment]
@DACRICC is this the first screen you see when you launch Postman? What version of Postman are you on? (The version should be visible in chrome://extensions)

**Comment by RicDAC** [comment]
3.2.20 - thanks

**Comment by abhijitkane** [comment]
Is this the first screen you see when you launch Postman?

**Comment by RicDAC** [comment]
yes

**Comment by abhijitkane** [comment]
When this is open, can you head to `chrome://inspect/#apps` in your browser and click any 'Inspect' link you see under 'Postman'? Any errors should show up in the console.

**Comment by RicDAC** [comment]
ok - no errors that I can see!

**Comment by RicDAC** [comment]
(note - I have the same issue with JSON Editor add-in same error on launch)

**Comment by RicDAC** [comment]
Please close this issue.
issue is linked to Bromium vSentry and impact on Chrome and add-ins when enabled -  thanks for the help yesterday.

**Comment by a85** [comment]
Closed @RicDAC
