### ISSUE TITLE
Right click to uriEncode params not working on mac app

### ISSUE THREAD

**Issue by dmaselbas** [a85/POSTMan-Chrome-Extension#1779]
version 4.0.3

Cant get the right click to uriEncode feature to work anywhere in the app.

**Comment by abhijitkane** [comment]
Thanks @dmaselbas. We're aware of this, and hope to push a fix for this soon.

**Comment by dmaselbas** [comment]
Awesome, thanks for postman! Cant wait for the iOS app :)

**Comment by abhijitkane** [comment]
@dmaselbas Can you confirm this fixed in the latest version?

**Comment by dmaselbas** [comment]
Some quick tests look good to me. Thanks again, this will help a lot.
