### ISSUE TITLE
Importing swagger.json files doesn't import post parameters

### ISSUE THREAD

**Issue by cviebrock** [a85/POSTMan-Chrome-Extension#1780]
I have an API endpoint defined in my Swagger file (some irrelevant details removed):

``` json
"/geocode": {
      "post": {
        "summary": "Geocode a coordinate",
        "parameters": [
          {
            "name": "latitude",
            "description": "The latitide of the location (pos=N, neg=S)",
            "in": "formData",
            "required": true,
            "type": "number",
            "format": "double",
            "minimum": -90,
            "maximum": 90
          },
          {
            "name": "longitude",
            "description": "The longitude of the location (pos=E, neg=W)",
            "in": "formData",
            "required": true,
            "type": "number",
            "format": "double",
            "minimum": -180,
            "maximum": 80
          }
        ],
        "responses": {
           ...
        }
      }
    },
```

When I import that document into Postman (v4.0.3), the endpoint is created, but the "latitude" and "longitude" keys aren't shown in the Body > form-data listing.  This used to be the case when importing Swagger in earlier versions of the app.

Thanks!

**Comment by abhijitkane** [comment]
@cviebrock Thanks for point this out! We'll fix this in the next release. For now, you should be able to import after changing `formData` to `form`.

**Comment by cviebrock** [comment]
Changing that in my `swagger.json` you mean?  Then my file doesn't follow the Swagger specifications
(http://swagger.io/specification/#parameterIn).

I'll wait for the next release. :)

**Comment by cviebrock** [comment]
FWIW, I saw the note in the 4.0.4 release that this was fixed, and indeed those parameters are importing now. However, the issues I mention in #1782 still exist, so there is a fair amount of manual editing that needs to happen after importing a Swagger document.

Thanks!
