### ISSUE TITLE
Imported Swagger path and query parameters imported incorrectly

### ISSUE THREAD

**Issue by cviebrock** [a85/POSTMan-Chrome-Extension#1782]
An endpoint in my swagger.json file contains:

``` json
{
  "/posts/{postId}": {
    "get": {
      "summary": "Get a post",
      "parameters": [
        {
          "name": "postId",
          "description": "The identifier for the post",
          "in": "path",
          "required": true,
          "type": "integer"
        },
        {
          "name": "format",
          "description": "Format for the post",
          "in": "query",
          "required": false,
          "type": "string"
        }
      ]
    }
  }
}
```

Is imported into Postman as:

```
GET http://example.com/posts/{{postId}}?format={{format}}
```

when I think it should be imported as:

```
GET http://example.com/posts/:postId
```

so that the parameters are then editable via the parameter list.  Also, in previous versions, the query string parameters where imported with `{{format}}`, etc. as the default values.  It would be handy if there were no default values set (otherwise, I need to clear them all out before testing a request with Postman).

Thanks!

**Comment by fynixw** [comment]
I have the same issue...

**Comment by cviebrock** [comment]
Still would like to see a fix for this.  The amount of manual editing I need to make on each import is making this a bit painful. 😞

**Comment by abhijitkane** [comment]
@cviebrock @F-12 We'll be pushing a fix for this in the next release.

**Comment by abhijitkane** [comment]
@cviebrock @F-12 This has been fixed in v4.4.2 of the app (Chrome only). Can you update (https://www.getpostman.com/docs/updating) and check?

**Comment by cviebrock** [comment]
Thanks!  I switched to the native OSX app, which is still at 4.4.1, so I'll confirm when the app is updated.

**Comment by cviebrock** [comment]
App was updated to 4.4.2, and path parameters are now imported correctly.  However, all parameters (path, body, etc.), still have silly default values attached to them (i.e. `{{conversationId}}`, `{{content}}`, etc.):

![screen shot 2016-07-11 at 9 44 10 pm](https://cloud.githubusercontent.com/assets/166810/16753637/12f4e352-47b1-11e6-9235-03d89792d43c.png)

I have to manually clear all the unused ones out when I'm testing an endpoint.  Can those not just be left empty?

**Comment by sdnts** [comment]
@cviebrock When you import a Swagger request, there needs to be some sort of default value, which is why we default it to an environment variable with the same name, as we do not have the actual value. It is a fallback to make sure all your parameters are imported correctly.

**Comment by cviebrock** [comment]
The Swagger import isn't a _request_ though.  It's a _specification_ for requests.

I can easily clear out all the `{{ parameter }}` fields manually after an import and then save the endpoint.  So I don't see why you need to fill them in in the first place.

![screen shot 2016-10-18 at 9 06 56 am](https://cloud.githubusercontent.com/assets/166810/19481075/5ebb1136-9512-11e6-82b0-f2cd36db16d2.png)

At the least, some fields may have a `default` value set in the Swagger spec ... why not use that?

It would also be great if file upload fields were imported as such (like `profileImage` and `coverImage` in the above screen shot, which I manually changed after import).
