### ISSUE TITLE
Feature requests: Presentation Mode

### ISSUE THREAD

**Issue by mstaalesen** [a85/POSTMan-Chrome-Extension#1784]
Presentation mode is really about showing the requests and the responses. Often we are using either a TV or a projector while demonstrating new functionality. Before 4.0.0 I had to manually set the size of the text in the request body by doing "inspect element" and changing the font size there.
With presentation mode, it becomes a bit easier, but it is still hard to read on a screen. It would also be nice to have a shortcut for presentation mode (and a way of knowing in the GUI if presentation mode is enabled or not).

Having worked with Postman for quite some time now, I'd like to request the following features:

Feature req 1: 
Keyboard Shortcut for enabling/disabling presentation mode.

Feature req 2:
Make the request-body field configurable, the same way that response body is possible today.

Feature req 3: 
Make it possible to define text-size for both request and response in presentation mode

Feature req 4:
Have some way of displaying if presentation mode is enabled (besides insides the Settings screen).

Feature req 5:
Autohide (or make it configurable) the sidepan during presentation mode.

Feature req 6:
Autohide the Top tab (With Runner, Import, New Postman Window etc) during presentation mode, to make room for the "important parts".

**Comment by aditikul** [comment]
Thanks for reporting this :) We are working on an update to the presentation mode based on a bunch of feedback we have collected. Stay tuned!

**Comment by mstaalesen** [comment]
Should I just close this issue?

**Comment by sdnts** [comment]
@mstaalesen We've added the ability to zoom in/out in the main window, does that help you?
I'm keeping this issue open primarily for the suggestions you've posted, we'll keep those in mind :)

**Comment by mstaalesen** [comment]
To some extent, but its zooming everything and not just the request/response-fields as I was hoping for. (I have to hide the sidepan when I zoom in.)

I am still mainly replacing the CSS with the Developer Tools while holding presentations, which is quite awkward. Especially since the app keeps crashing.

**Comment by a85** [comment]
Presentation mode has been removed and instead you can zoom in/out now with shortcuts!
