### ISSUE TITLE
Usability: Make it easier to distinguish if a collection is opened or not

### ISSUE THREAD

**Issue by mstaalesen** [a85/POSTMan-Chrome-Extension#1785]
As of right now, the difference in color on the Collection pan when selected/opened or not is rather hard to make out. (Especially in the dark theme). It would be nice if the icon for the collection could change from "closed" to "open", and also the background color for the tab be even more "highlighted" so that it is clear that the collection is either opened or closed.

**Comment by mstaalesen** [comment]
Adding gif for a small explanation about what I meant:
![animation2](https://cloud.githubusercontent.com/assets/14194793/13897700/0442ccfc-edbb-11e5-899b-a993e922cdf0.gif)

**Comment by mstaalesen** [comment]
Should I just close this issue?

**Comment by a85** [comment]
@vkaegis Can we have the new icon please! :)

**Comment by a85** [comment]
@mstaalesen We are highlighting the collection now. The new sidebra with multi-level folders will have a new icon soon! Closing this for now.
