### ISSUE TITLE
Cannot add enviroment vars in request body anymore in Postman 4.0.0

### ISSUE THREAD

**Issue by kams-mash** [a85/POSTMan-Chrome-Extension#1787]
I recently updated my chrome to 49.0.2623.75 and as a result postman app was auto-updated to 4.0.0 and now I'm not able to pass environment vars in the request body anymore, i tried both formats below:

My request body is json format.

format 1- this used to work in previous postman app:
`{
  "username": "{{username}}"
}`

format 2:
`{
  "username": {{username}}
}`

Any ideas on how to fix this? or is there a way to rollback postman to previous version?

Thank you.

**Comment by abhijitkane** [comment]
@kams-mash I'm not able to reproduce this. Is the environment selected? Does this work if `username` is a global variable instead?

**Comment by kams-mash** [comment]
Thanks for your quick response on this.  If it helps I'm on (linux/x86-64).

Please see the attached screenshot of the issue, i'm able to reproduce. As you can see in the response the server is sending back the environment var, which indicates that the value substitution for the environment var did not happen in the request body.

I created a global var with the same name (i.e. sso_st) and still it fails (I believe I access global var in the same way as env. var : {{sso_st}})

![screenshot from 2016-03-03 12 11 02](https://cloud.githubusercontent.com/assets/5761399/13508090/5e70ad26-e13a-11e5-9c78-c1bb16b3d864.png)

**Comment by abhijitkane** [comment]
@kams-mash  Are there any errors in the console? (http://blog.getpostman.com/2015/06/13/debugging-postman-requests/)

**Comment by kams-mash** [comment]
Now it works, after I completed the steps to enable dev tools and restarted it started working, I re-tested by disabling the dev tools and it still works. I'm guessing all that was needed was a restart.

When in doubt restart :)

Btw, dev tools is very helpful I can see the request and responses over the wire.

Thanks for your quick help on this.
