### ISSUE TITLE
Collection Runner Subfolders do not work

### ISSUE THREAD

**Issue by jonahpatriarche** [a85/POSTMan-Chrome-Extension#1788]
When running subfolders in Collection Runner:
- some requests in subfolder are NOT sent
- requests from other subfolders ARE sent
  #
  Version: 3.2.20
  OS: Mac

**Comment by abhijitkane** [comment]
@jonahpatriarche Is there a sample collection that you can share that you can reproduce this issue with?

**Comment by jonahpatriarche** [comment]
Probably not. I’m currently testing my API on a local server.

**Comment by jonahpatriarche** [comment]
Perhaps this will help. Here is a collection I tried to run:

I ran the collection once and got this result:

Issues:
- Tests were run from different folders
- The pass/fail counts do not make any sense.
- In many places. the test results do not make sense. GET requests are returning 422 or 201, POST requests are returning 200, etc… I promise that my API does not behave this way.

~Jonah

**Comment by abhijitkane** [comment]
@jonahpatriarche Are you still seeing this in the latest version?

**Comment by jonahpatriarche** [comment]
@abhijitkane Looks like it. I've mostly stopped using Collection Runner, but I ran that same collection a few times today and noticed a couple of things:
- a lot of the problematic requests are ones that I made using "duplicate" in the sidebar
- when I navigate through the side by and use the "Run" button to launch Collection Runner, my requests are mostly executed in order, but If I launch Collection Runner and navigate to a sub-folder, they jump around all over the place.
- I get errors in Runner that don't occur when I run the tests individually.

For instance:

Run alone:
<img width="1882" alt="screen shot 2016-04-26 at 3 25 23 pm" src="https://cloud.githubusercontent.com/assets/12899331/14836195/310e6162-0bc3-11e6-982f-6d4609d7fa33.png">

Run in Collection Runner:
![screen shot 2016-04-26 at 3 23 32 pm](https://cloud.githubusercontent.com/assets/12899331/14836205/43fc8196-0bc3-11e6-99c1-9041fa92d85e.png)

**Comment by abhijitkane** [comment]
@jonahpatriarche We've made a few fixes related to this recently. Can you check if you're still facing the issue in v4.4.1?

**Comment by kgilfilen** [comment]
I am having this problem right now, with 6.7.1.  Looking at the column that shows which request you’re running, it shows requests from other folders. So now my collection runner is not going to the next folder, and I don’t know which request to look at.
