### ISSUE TITLE
Collection tests fail from runner and pass when run individually

### ISSUE THREAD

**Issue by jonahpatriarche** [a85/POSTMan-Chrome-Extension#1789]
When running a collection, requests fail and halt the run, but if the individual requests are run from the editor, they all pass.

Version 3.2.20 (packaged)
OS: Mac

**Comment by abhijitkane** [comment]
Can you check the Network tab in the runner (http://blog.getpostman.com/2015/06/13/debugging-postman-requests/)? Might help to figure out why the requests fail.

**Comment by a85** [comment]
Unverified.
