### ISSUE TITLE
Ability to decrease UI font size in Mac App

### ISSUE THREAD

**Issue by deepal** [a85/POSTMan-Chrome-Extension#1790]
Compared to the chrome packaged app, I see the font size in Mac App is way too large. It's nice if there's a way to decrease the font size of UI, not only response.

**Comment by numaanashraf** [comment]
@dpjayasekara, could you let us know what screen resolution you are using and also share screenshots of both the Chrome App and Mac App?

**Comment by a85** [comment]
This is possible now.
