### ISSUE TITLE
Variables are not replaced in request in v4.0.0 for Windows

### ISSUE THREAD

**Issue by roeschjohannes** [a85/POSTMan-Chrome-Extension#1791]
Since i updated to version 4.0.0 for Windows, postman does not replace variables in request body with their values. Postman always sends the variable with {{...}}. See example with {{SysTenant_ID}} below.
It's impossible to use postman anymore.

**Request Body:** `{
    "uaaURL":"https://{{SysTenant_ID}}.example.com",
    "tenantadminClientID":"tenantadmin",
    "tenantadminClientSecret":"password",
    "clientID":"sb-{{uaaapp}}",
    "clientSecret":"{{clientSecret}}",
    "username":"testuser",
    "samlAttributes":{
        "Groups":["group1"],
        "attribute":["value1"]
    }
}`

**Response Body:** `{
  "token": null,
  "error": "An error occurred during the initialization of the OA2SAMLClient: An error occurred during the initialization of the OA2SAMLClient (identity zone: \"{{systenant_id}}\")"
}`

**Environment Variable:**
`SysTenant_ID = com-t1`

The server obviously receives the variable name instead of its value.

**Comment by abhijitkane** [comment]
@roeschjohannes Can you check is there are any errors in the console when you send the request? (http://blog.getpostman.com/2015/06/13/debugging-postman-requests/)

**Comment by roeschjohannes** [comment]
No, there is no error in console. I already tried to enable and disable dev-tools like in Issue [1787](https://github.com/postmanlabs/postman-app-support/issues/1787) but it does not work.

But there is an error after starting the App.
`window.localStorage is not available in packaged apps. Use chrome.storage.local instead.
     (anonymous function)   @   extensions::platformApp:15`

`beforeunload is not available in packaged apps.
     (anonymous function)   @   extensions::platformApp:15`

**Comment by abhijitkane** [comment]
Can you add the following to your 'pre-request-script`?

```
console.log("Variables in pre-script: " + environment.SysTenant_ID + " , " + environment. uaaapp + " , " + environment. clientSecret);
```

and the following in the tests script:

```
console.log("Variables in post-script: " + environment.SysTenant_ID + " , " + environment. uaaapp + " , " + environment. clientSecret);
```

This should print out the values of the variables in the console when you run the request. Are the correct values being printed out?

**Comment by roeschjohannes** [comment]
Yes. The variables in pre- and post-script are both correct

**Comment by abhijitkane** [comment]
With the environment selected in the UI, can you enter this in the console:

`pm.envManager.getCurrentValue("{{SysTenant_ID}}");`

Does it return the correct, value, or does the replacement not work? Appreciate your help debugging this!

**Comment by roeschjohannes** [comment]
This command returns the correct value.

**Comment by abhijitkane** [comment]
Can you run these 3 commands (one-at-a-time) after you send your request?

`pm.tabManager.getCurrentRequest().get("body").get("data");`
`pm.tabManager.getCurrentRequest().get("body").get("dataMode");`
`pm.tabManager.getCurrentRequest().get("body").get("transformedData");`

The first should return the data with the variables unresolved. The second should return `raw`. The third should return data with the variables resolved.

**Comment by roeschjohannes** [comment]
That commands are also working correct.

**Comment by abhijitkane** [comment]
Can you ensure that the 'Send Postman Token' header is set to ON?

Do you face the same issue even while trying to send URL parameters / Headers that use environment variables? You can send requests to http://echo.getpostman.com/get?param=value to test this.

**Comment by roeschjohannes** [comment]
Send Postman Token is set to ON.
Header parameters with variables inside does not change anything.

I tried to read the request.data variable in console. It has also the correct values.

**Comment by abhijitkane** [comment]
How about this - `pm.tabManager.getCurrentRequest().get("body").setTransformedDataAndGetPayload();`?

This is the actual payload that's set in the XHR request before it's sent. This should be the same as what you see in the Network tab of the DevTools window.

**Comment by roeschjohannes** [comment]
I got the correct Body

**Comment by abhijitkane** [comment]
Is this different from what you see in the 'request payload' section when you click on your request in the Network tab?

**Comment by roeschjohannes** [comment]
i can't find the 'request payload' in network tab.

**Comment by abhijitkane** [comment]
Attaching a screenshot here - 
<img width="1080" alt="screen shot 2016-03-04 at 15 54 33" src="https://cloud.githubusercontent.com/assets/681190/13524476/6ffcd99c-e221-11e5-98db-654dcdc7bcdd.png">

**Comment by roeschjohannes** [comment]
I only get this
![2016-03-04_11-32-41](https://cloud.githubusercontent.com/assets/15650263/13524661/d9a0750e-e1fc-11e5-99b8-91b518f04d2a.png)

**Comment by abhijitkane** [comment]
Ah..can you try running it with the Interceptor disabled?

**Comment by roeschjohannes** [comment]
Thats it. Now it works.

**Comment by roeschjohannes** [comment]
Thanks for your realy fast support.

**Comment by abhijitkane** [comment]
No problem! We'l push a fix for this in the next release.

**Comment by abhijitkane** [comment]
@roeschjohannes Can you confirm this fixed in the latest versions of the app?

**Comment by roeschjohannes** [comment]
Yes, CONFIRM.
Now it works everything fine.
