### ISSUE TITLE
postman pre-request script - can I make a URL hit to get initial data?

### ISSUE THREAD

**Issue by rvnath** [a85/POSTMan-Chrome-Extension#1792]
I have a requirement to test an accounting server api.  The api has a "debit" function.  To test this api correctly, I need to insert some account balance to ensure the account "really" has some balance (via another api) using pre-request script, and then call the current api to do the "debit" operation. 

Is this possible to do so?  If not, then sequencing the test cases in a proper order (such as executing credit test cases first followed by debit) is the only way?

**Comment by abhijitkane** [comment]
@rvnath Sending AJAX requests in the pre-request script section will result in undefined behavior. We cannot guarantee that the actual request will run after your AJAX call completes. For now, the only way to get such a flow to work is to have two requests in the collection.

**Comment by rvnath** [comment]
ok
