### ISSUE TITLE
Can't copy values from Header after 3/3/2016 Update

### ISSUE THREAD

**Issue by tjones788** [a85/POSTMan-Chrome-Extension#1793]
I am no longer able to copy the values from a header field after making a request. Can't install old version manually in Chrome.

**Comment by abhijitkane** [comment]
@tjones788 We'll be pushing a fix for this in a day or two. Thanks for reporting this.

**Comment by tjones788** [comment]
Thank you!!!

**Comment by cnanney** [comment]
Awaiting this fix as well.

**Comment by SamvelRaja** [comment]
The fix had been released with the latest update  **4.0.2**
