### ISSUE TITLE
Ability to set Request Font Size (px)

### ISSUE THREAD

**Issue by mfulton26** [a85/POSTMan-Chrome-Extension#1794]
There is the ability to set the Response Font Size (px) but not the Request Font Size (px). Please add.

**Comment by nikhilvibhav** [comment]
Has this been implemented yet. the request font sizes are really very small on hd displays.. atleast in windows..
[screenshot](http://imgur.com/noKqvKB)

**Comment by sdnts** [comment]
@nikhilvibhav You can use Cmd+/- to zoom in / zoom out of the UI. Can you try that and let me know if the sizes feel better?

**Comment by nikhilvibhav** [comment]
@madebysid it does, but there are a lot of ctrl+ to do, and then again ctrl- to read the response because now it's too big. 
it would be better if we could set a global font size maybe? (small, medium, large, xl). Just a thought.

**Comment by sdnts** [comment]
Changing the font size in itself is something we've been working on, and it'll be out with our next release. I'll keep you updated here :)

**Comment by sdnts** [comment]
Guys, this is possible now. v4.9.2 and up should allow you to change the editor font size :)

**Comment by nikhilvibhav** [comment]
Amazing. Thanks @madebysid!
