### ISSUE TITLE
Ability to reformat request body

### ISSUE THREAD

**Issue by mfulton26** [a85/POSTMan-Chrome-Extension#1795]
I often get unformatted XML/JSON from client/server log viewers and I'd like to be able to paste them into Postman and reformat them instead of pasting them into a third-party app (e.g. an IDE like Eclipse or IntelliJ or some other tool that supports XML), reformatting, copying, and then pasting into Postman.

**Comment by a85** [comment]
@abhijitkane Available in Postman right?

**Comment by abhijitkane** [comment]
@mfulton26 Cmd/Ctrl+B reformats XML and JSON in the request body editor (raw mode only). You'll have to set the correct type for this to work.

**Comment by mfulton26** [comment]
It works great. Thank you!
