### ISSUE TITLE
Ability to view the request and response side-by-side

### ISSUE THREAD

**Issue by mfulton26** [a85/POSTMan-Chrome-Extension#1796]
The request and response viewing panes are part of a vertically scrollable area but I'd rather view the request and response side-by-side, the request on the left and the response on the right.

**Comment by aditikul** [comment]
Hi! Thanks for suggesting this new feature. Can you tell us a bit more about how this can help you, for example is there any specific use case due to which you have this preference?

**Comment by mfulton26** [comment]
Yes, as it is right now if I edit the request body and send the request the response body is only partially shown. If I start scrolling down the response body starts scrolling but I'm still only seeing the upper half of the response. It isn't until I've scrolled all the way to the bottom of the response body that the scrollable area containing the request and response bodies finally scrolls down to reveal the entire response body area. Having a scrollable area inside of another scrollable area is, for me, troublesome. Of the response were simply on the right then I'd be able to view both bodies just fine.

Another use case is that this would make tweaking my request body based on a response easier. I often make a request, inspect the response, and then edit the request and resend to iterate on the request body while I am testing and/or learning a new API.

**Comment by lucasgranberg** [comment]
This would be usefull when working with big screens and for example elasticsearch queries.
As you can see from the screenshot there is a lot of screen-estate unused and I can only see part of the response and the request.
![image](https://cloud.githubusercontent.com/assets/1225253/14640516/8abcdeba-064a-11e6-85bf-bbf8f8e7aed4.png)

**Comment by a85** [comment]
Coming up in 4.9!

**Comment by a85** [comment]
Two-pane layout is now available on native apps!
