### ISSUE TITLE
Ability to snap response pane to the remaining tab area

### ISSUE THREAD

**Issue by mfulton26** [a85/POSTMan-Chrome-Extension#1797]
I like how I can adjust the request pane's vertical height but I cannot adjust the response pane's vertical height. Given a toll enough Postman window size I'd like to force the response pane to use only the space available between the bottom of the request pane and the bottom of the tab/window. Thank you. (Having a scrollable area inside of a scrollable area can be troublesome.)

**Comment by aditikul** [comment]
Hi! Can you share screenshots of the window so we can better understand the issue and how the response pane should be resized based on your screen size/preferences. Unfortunately there is no easy fix for the scroll within a scroll issue in the builder area, though we understand it can be troublesome.

**Comment by mfulton26** [comment]
![image](https://cloud.githubusercontent.com/assets/5588957/14216343/e23933a0-f80d-11e5-9ae3-e900aa313ad6.png)
![image](https://cloud.githubusercontent.com/assets/5588957/14216350/e7ffdd66-f80d-11e5-81b3-e0e382b137c9.png)
![image](https://cloud.githubusercontent.com/assets/5588957/14216356/ebbdc652-f80d-11e5-840c-d7baa34b24a5.png)
![image](https://cloud.githubusercontent.com/assets/5588957/14216359/eed3b20c-f80d-11e5-9262-94ba93aabf05.png)
[video archive](https://github.com/postmanlabs/postman-app-support/files/200151/2016-04-01_13-26-23.zip)

**Comment by a85** [comment]
Two-pane layout is now available on native apps!
