### ISSUE TITLE
query parameters should have an enable/disable button by it's side 

### ISSUE THREAD

**Issue by deodeveloper** [a85/POSTMan-Chrome-Extension#1799]
# query parameters should have an enable/disable button by it's side so that we don't have to delete and type the query parameters again if we trying a GET request with different parameters

**Comment by mfulton26** [comment]
:+1:

**Comment by nathaniel-holder** [comment]
Agreed!  This is implemented for request headers.  I'd use this much more often than the existing functionality that exists for headers.
FYI, this is a dup of issue "URL parameters should have a checkbox like header params" #785

**Comment by prashantagarwal** [comment]
Hi @deodeveloper ,
We are tracking this issue #785 . Closing this duplicate issue.
