### ISSUE TITLE
Correctly decode XML entity references when clicking on links in XML response bodies

### ISSUE THREAD

**Issue by mfulton26** [a85/POSTMan-Chrome-Extension#1800]
Clicking on links in XML response bodies does not properly decode the XML.

e.g. If the raw representation of an XML document contains `<searchURL id="postman">https://www.google.com/#safe=active&amp;q=postman</searchURL>` then clicking on the link should set the request URL in a new tab to https://www.google.com/#safe=active&q=postman but it instead sets it to `https://www.google.com/#safe=active&amp;q=postman</searchURL>`.

**Comment by abhijitkane** [comment]
@mfulton26 Are you still seeing this?

**Comment by mfulton26** [comment]
@abhijitkane I am.

**Comment by atzmon** [comment]
I'm experiencing the same issue.

Here's a screenshot of a very simple XML that demonstrates what the link looks like on mouseover. Notice the blue underline contains the end "URL" tag:

![postman_xml_link](https://cloud.githubusercontent.com/assets/1856275/14941588/5acd3854-0fa9-11e6-88b6-59002f7cfa97.png)

**Comment by abhijitkane** [comment]
@mfulton26 @atzmon Thanks for reporting this. We'll be pushing a fix for this in the next release.

**Comment by abhijitkane** [comment]
@mfulton26 The link detection issue has been fixed (</URL> is no longer detected as part of the link) in the latest version - 4.4.2 - of the app.

**Comment by mfulton26** [comment]
Fix confirmed.
