### ISSUE TITLE
Pretty XML does not decode XML entity references

### ISSUE THREAD

**Issue by mfulton26** [a85/POSTMan-Chrome-Extension#1801]
If an XML response body contains XML numeric or character references should they not be decoded when displayed in the "Pretty" format? This is what web browsers appear to do (e.g. Chrome, Firefox, etc.).

e.g. If the raw representation of an XML document contains `<searchURL id="postman">https://www.google.com/#safe=active&amp;q=postman</searchURL>` then it should be displayed as `<searchURL id="postman">https://www.google.com/#safe=active&q=postman</searchURL>`.

**Comment by abhijitkane** [comment]
@mfulton26 Can you confirm this fixed in v4.4.1?

**Comment by mfulton26** [comment]
I just checked version 4.4.1 and the same issue is present. I would expect `<searchURL id="postman">https://www.google.com/#safe=active&amp;q=postman</searchURL>` to be displayed as `<searchURL id="postman">https://www.google.com/#safe=active&q=postman</searchURL>` in the "Pretty" viewer.

**Comment by sdnts** [comment]
Hey @mfulton26, the pretty view will (and should) never change your API response. The utility of the view is to look at an indented, syntax-highlighted version of the response. As such, we do not do any sort of modification to your response in the pretty view.
As a side note, the preview section should show you the correctly decoded response.

**Comment by mfulton26** [comment]
@madebysid I see: the "Pretty" viewer is scoped to "Pretty" printing the raw content. That makes sense. Thank you for the explanation.

I've created #2419 with a new request as I see now it shouldn't be part of the "Pretty" viewer. Thank you.
