### ISSUE TITLE
JSON Pretty Preview Parse Error With Empty Body

### ISSUE THREAD

**Issue by gavincornwell** [a85/POSTMan-Chrome-Extension#1802]
I'm getting an error in the pretty preview for JSON with empty body responses such as 204 and 202.

This was working fine in 3.x.

I'm using 4.0.4.

<img width="1080" alt="screen shot 2016-03-04 at 21 24 20" src="https://cloud.githubusercontent.com/assets/1194868/13540678/df18871c-e24f-11e5-9b57-845666355bd5.png">

**Comment by abhijitkane** [comment]
Thanks for reporting this. We'll push a fix for this in the next release.

**Comment by abhijitkane** [comment]
@gavincornwell Can you try upgrading to the latest version? (chrome:/extensions > Enable 'Developer Mode' > Update extensions now)

Should be fixed in v4.0.3/4.0.4.

**Comment by gavincornwell** [comment]
I've upgraded to 4.0.5 (packaged Mac version) and I can confirm that I no longer see the error, many thanks for fixing this so promptly.
