### ISSUE TITLE
Post Not working after chrome upgrade

### ISSUE THREAD

**Issue by atkawa7** [a85/POSTMan-Chrome-Extension#1803]

**Comment by deive** [comment]
I am also having a problem after update (see https://github.com/postmanlabs/postman-app-support/issues/1819) this could be the same as your problem? Can you check using the console if you get an error (see http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ if you need help viewing the console)?

**Comment by abhijitkane** [comment]
@atkawa Are you still seeing this?

**Comment by atkawa7** [comment]
@abhijitkane  yes I am still seeing the same error

**Comment by abhijitkane** [comment]
@atkawa7 Can you check the Network tab of the DevTools window (see http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ if you need help viewing the console) for any errors when you send your request?

Also, is the Interceptor enabled?
