### ISSUE TITLE
Right-click to set environment variables does not work in version 4

### ISSUE THREAD

**Issue by rlinyard** [a85/POSTMan-Chrome-Extension#1804]
I often use results from one POST call (say when I receive an Auth Token) to set environment variables. It was very handy to be able to select a portion of the result, right-click, and set an environment variable. It looks like version 4 does not have this functionality. PLEASE bring it back.

**Comment by pella07** [comment]
I'm having the same issue. I can access the shortcut menu used to assign returned values to variables but they don't appear to be stored. I can manually copy them in though through the environment manager menu.

**Comment by rlinyard** [comment]
Yes. I can do the same, but what a pain. 4.0.1 seems to have the behavior you describe, but there is not even a shortcut menu for me in 4.0.4.

**Comment by definesfineout** [comment]
My team is experiencing the same behavior as @pella07 - we can access the context menu, but the value isn't saved to the variable.

**Comment by aeagal** [comment]
Also experiencing this issue on 4.0.1. Variables that I had before the update still work. But if I update them with a new value they do not get into my request. Additionally, new variables do not work.

By 'do not work' I mean that when I highlight some returned text (e.g. auth token) from a post response, right-click and set a variable, the variable gets blanked out. Reproduce these steps, and check the variable under 'manage environments.' It will be blanked out.

![image](https://cloud.githubusercontent.com/assets/7453213/13604690/ecb168a2-e511-11e5-8ab7-b3d8bb6860c2.png)

**Comment by numaanashraf** [comment]
@rlinyard @pella07 @dustinfineout @aeagal We've fixed this issue in our internal build and will be rolling it out over the next couple of days.

**Comment by SamvelRaja** [comment]
@rlinyard @pella07 @dustinfineout @aeagal It had been released with the latest version `4.1.0`

**Comment by definesfineout** [comment]
@numaanashraf @SamvelRaja Thank you!!

**Comment by rlinyard** [comment]
Great - it works!
