### ISSUE TITLE
Variable value isn't being passed in call

### ISSUE THREAD

**Issue by pella07** [a85/POSTMan-Chrome-Extension#1805]
I have a token assigned to a variable and the {{variable}} listed in the header of a GET call. However it doesn't appear that the variable value is being passed because I get a server 500 error. When I paste the actual token into the field instead of the {{variable}} the request works just fine.

**Comment by abhijitkane** [comment]
@pella07 Is the environment selected? You should see `variable -> actual_value` when you click on the icon to the right of the environment selector.

Also, are there any errors in the console - http://blog.getpostman.com/2015/06/13/debugging-postman-requests/?

**Comment by pella07** [comment]
Yes the environment is selected. 

This is the only error I got:

<errorInfo>
<errorCode>500</errorCode>
<errorDescription>Server error</errorDescription>
</errorInfo>

I've attached a screenshot of where I got the error from.

![error](https://cloud.githubusercontent.com/assets/17693577/13584834/5cb97fdc-e50c-11e5-92f6-61835292f0d2.png)

**Comment by abhijitkane** [comment]
@pella07 Any errors in Postman's DevTools window (Console tab)? Also, what version of Postman are you using? I'm not able to reproduce this.

**Comment by pella07** [comment]
I got this error: Failed to load resource: the server responded with a status of 500 (Internal Server Error).

The situation resolves itself when I paste the actual into the field instead of referencing the variable. I tried assigning a different variable name to the field and the error still persists.

**Comment by pella07** [comment]
Here is a code snippet of the GET statement. In the code snippet the variable gets passed in correctly. It only fails when I execute the call.

GET /brands?detail=basic&showhidden=yes HTTP/1.1
Host: <private host URL is normally here>
x-apdm-api-version: 2.0
Content-Type: application/xml
x-apdm-userid: <user id is normally here>
x-apdm-usertoken: Token variable value
Accept: application/xml
Cache-Control: no-cache
Postman-Token: e0fda5a1-9d78-b585-fa14-d2832249ff43

**Comment by abhijitkane** [comment]
@pella07 What version of Postman are you using? Can you attach screenshots of the Postman screen and Postman's console when you send the request?

Also, you can try toggling the Interceptor off and sending the request.

**Comment by pella07** [comment]
@abhijitkane I'm using 4.0.1. I had a look at the server send of the request and I can see that a "%01" has been added to the front of various variables. The "%01" isn't part of the variable and isn't being stored in the variable.

<HOST IP> - - [09/Mar/2016:10:23:56 +1100] "GET /brands/**%01**E5529482-923A-4727-8660-95F6A8A321E0/brandProducts/717A4D5C-C7A9-4284-B7D6-16C2F0CE866D/verificationQuestions HTTP/1.1" 444 0 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36" "<IP ADDRESS>" "24890247430247" "-" "-" "provider_services" 0.000

Does that help?

**Comment by abhijitkane** [comment]
@pella07 %01 is a non-printing character. Can you go to the Manage environments window, and edit your environment - clear out the value of the variable and type it out again, making sure there any no leading or trailing spaces.
If you'd pasted the value from somewhere else, it's possible that one extra non-printing character might have been included.

**Comment by pella07** [comment]
That appears to have solved it. I'll let you know if it crops up again.

Thanks!
