### ISSUE TITLE
x-www-form-urlencoded parameters not properly sent

### ISSUE THREAD

**Issue by michael-andre** [a85/POSTMan-Chrome-Extension#1806]
With Chrome Extension 4.0.0 / Chrome 48.0.2564.116
x-www-form-urlencoded parameters are not properly sent, they are replaced by `[object Object]`

Example request with 2 params :

```
POST http://... HTTP/1.1
Host: localhost:8080
Connection: keep-alive
Content-Length: 31
Cache-Control: no-cache
Content-Type: application/x-www-form-urlencoded
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36
Postman-Token: e5cda3f7-5156-20d9-b803-438513c5bb3e
Accept: */*
Accept-Encoding: gzip, deflate
Accept-Language: fr-FR,fr;q=0.8,en-US;q=0.6,en;q=0.4

[object Object],[object Object]
```

**Comment by abhijitkane** [comment]
@michael-andre Thanks for reporting this. We've fixed this in our internal build, and will rolling the fix out to all users this week.

**Comment by abhijitkane** [comment]
Also, this should work if you switch the interceptor off.

**Comment by michael-andre** [comment]
OK, thanks for the quick feedback
