### ISSUE TITLE
Switching from Pretty to Preview tab, then return to Pretty again issue

### ISSUE THREAD

**Issue by rpajaziti** [a85/POSTMan-Chrome-Extension#1807]
If you have a JSON response type, then switch from Pretty tab to Preview, then return to Pretty again, response text will be like 1/3 smaller, and the whole body will display in there.

**Comment by abhijitkane** [comment]
@RamadanPajaziti Can you mention the Postman version that you're using?

**Comment by rpajaziti** [comment]
Im ussing the lattest, downloaded today, ver: 4.0.4.
Just try with one API that returnes JSON as a type(didnt tryed with others).

**Comment by mstaalesen** [comment]
@abhijitkane I have observed the same behavior, switching from the Response Body (Pretty) to the Tests tab (on response) and back again.

Screenshots to explain:
1. First view of response (74 lines)
![postman_002](https://cloud.githubusercontent.com/assets/14194793/13603609/c640e364-e53e-11e5-9e98-c44c3b34918d.png)
1. Switched to test tab and back again (39 lines and a big blank space below it):
   ![postman_003](https://cloud.githubusercontent.com/assets/14194793/13603623/dad9d83a-e53e-11e5-880d-67c89b94b6e8.png)

Looking at this, it seems that after switching to the Test Tab and back to the Body Tab, Postman sets the default size for showing both request and response. This is the "default" size when showing a request in Postman on my screen:
![postman_005](https://cloud.githubusercontent.com/assets/14194793/13603723/83fb072c-e53f-11e5-87d1-573bf2f69f8c.png)

Currently using Postman 4.0.1 on Ubuntu.

**Comment by SamvelRaja** [comment]
@mstaalesen, RamadanPajaziti Yes, you can expect the fix for this problem as well in the next release. Thanks for bringing to us.

**Comment by SamvelRaja** [comment]
We have released our latest version  **4.0.2**  which would solve this problem. Can you confirm the same ?

**Comment by mstaalesen** [comment]
Confirmed, working in 4.0.2
