### ISSUE TITLE
Where is the option of  Open history/collection requests in a new tab

### ISSUE THREAD

**Issue by ravigajera** [a85/POSTMan-Chrome-Extension#1808]
in this version 
4.0.1
( win / x86-32 )
( Chrome 48.0.2564.116 )

where is the option of **Open history/collection requests in a new tab**

![image](https://cloud.githubusercontent.com/assets/15246318/13569187/864a53ce-e48c-11e5-819b-a647bd15035e.png)

![image](https://cloud.githubusercontent.com/assets/15246318/13569196/8f5219de-e48c-11e5-9f77-a83168093b96.png)

**Comment by johnhenderson** [comment]
+1

**Comment by AhmadMuzakkir** [comment]
+1.

Can I also request a feature when Cmd + Click on a history/collection request, it will open the request in a new tab.

**Comment by thomasruns** [comment]
+1 No idea why this would have been removed

**Comment by aditikul** [comment]
You can now open a request in a new tab with the shortcut Cmd/Ctrl+Shift+click if you click on the request in the left sidebar. Hope this helps. Cmd+click will be used for multiple select later.

**Comment by johnhenderson** [comment]
Thank you! I can do two suggestions to next version:
1. Allow change the shortcut in Settings->Shortcuts
2. Re-Add option to always open the request in new tab

**Comment by aditikul** [comment]
@ravigajera @johnhenderson @thomasruns @AhmadMuzakkir Instead of a setting, this is now available for everyone by default. You can open a request in a new tab with Cmd/Ctrl+Shift+click if you click on a request in the left sidebar. This now works in History too. You can also open the same request in multiple tabs.
