### ISSUE TITLE
OPTIONs Request Body got in NEW version again.

### ISSUE THREAD

**Issue by dgofman** [a85/POSTMan-Chrome-Extension#1810]
That issue was fix in 2015

OPTIONs Request Body #1168

In new update we again cannot pass body by using OPTION method.

Please follow to W3 rule

https://www.w3.org/Protocols/rfc2616/rfc2616-sec9.html

**Comment by abhijitkane** [comment]
@dgofman Thanks for reporting this. We'll be pushing a fix for this in the next release.

**Comment by magnusart** [comment]
@abhijitkane ran into this as well just now, do you have a public release schedule so I know when to expect it to show up?
