### ISSUE TITLE
My account not syncing - its says offline always

### ISSUE THREAD

**Issue by SivaKrishnaKorlam** [a85/POSTMan-Chrome-Extension#1811]
Hi,

I am using postman client with below version:
4.0.0
( linux / x86-64 )
( Chrome 49.0.2623.75 )

I am using my Google account for login and am able to login to account successfully. Issue is, my account sync is not working. When i click on sync button on top right corner, it show that connecting and then in few seconds went back to offline.

Please help me to resolve this issue.

Thanks,
-Shivv

**Comment by abhijitkane** [comment]
@SivaKrishnaKorlam Were you able to use Sync before? We've had reports of corporate proxies interfering with sync connectivity.

**Comment by SivaKrishnaKorlam** [comment]
Yes am.. I just reinstalled my OS two days back.. before am able to connect without any issues.

**Comment by abhijitkane** [comment]
Can you open the DevTools window (http://blog.getpostman.com/2015/06/13/debugging-postman-requests/) and see if there are any errors in the console?

**Comment by SivaKrishnaKorlam** [comment]
tried the steps given in the blog. but i am unable to open Devtools by right clicking on postman client.

**Comment by abhijitkane** [comment]
When the app is open, head to `chrome://inspect/#apps` in your browser. Click `Inspect`. This should open Postman's DevTools window.

**Comment by SivaKrishnaKorlam** [comment]
Thanks for the help abhijitkane :+1: 
i can see these errors from console output:

extensions::platformApp:17 window.localStorage is not available in packaged apps. Use chrome.storage.local instead.(anonymous function) @ extensions::platformApp:17
extensions::platformApp:17 beforeunload is not available in packaged apps.

**Comment by SivaKrishnaKorlam** [comment]
when i clicked on extensions::platformApp:17 i can see this from source code:
- @param {string} messagePrefix text to prepend to the exception message.
  */
  function generateDisabledMethodStub(messagePrefix, opt_messageSuffix) {
  var message = messagePrefix + ' is not available in packaged apps.';
  if (opt_messageSuffix) message = message + ' ' + opt_messageSuffix;
  return function() {
    console.error(message);
    return;
  };
  }

**Comment by abhijitkane** [comment]
Those error messages are expected. Are you behind a corporate proxy in office? If so, can you try connecting from home?

**Comment by SivaKrishnaKorlam** [comment]
sure..i tried to set corporate proxy ..but in my office m not able to access.. any solution on this?

**Comment by SivaKrishnaKorlam** [comment]
i have disabled proxy and tried... its started working.. issue is ..i have applied proxy for system level in my ubuntu desktop. so it's effected to postman as well . I have changed system proxy to none then its working.

Thanks abhijitkane .

**Comment by SamvelRaja** [comment]
@SivaKrishnaKorlam The reason is your corporate proxy needs to allow websocket connection to make sync to work.
