### ISSUE TITLE
Collection Runner Statistics: Filter on "Failed" shows the same result as "All"

### ISSUE THREAD

**Issue by mstaalesen** [a85/POSTMan-Chrome-Extension#1812]
Just ran 3000 requests (500 iterations) with the collection runner and had a problem with ~40% of said requests. Wanted to see some more detailed statistics over just the failed requests, but when i clicked "Failed" on the statistics tab, it shows the same result as "All". The filter for "Passed" is working as it should.

Version: Postman v4.0.1

**Comment by abhijitkane** [comment]
@mstaalesen That's odd - I'm not able to reproduce this. Can you attach screenshots of the 3 states?

**Comment by mstaalesen** [comment]
I forgot to add that I selected one of the requests under the statistics page by clicking the (I) button:
![collection runner_006](https://cloud.githubusercontent.com/assets/14194793/13613885/3d8b1370-e56e-11e5-9e33-9eb62be0a7b0.png)

Then the following happends (1. "All", 2. "Passed", 3. "Failed")
![collection runner_008](https://cloud.githubusercontent.com/assets/14194793/13613903/53fd02a8-e56e-11e5-9469-031eb010e46d.png)

![collection runner_009](https://cloud.githubusercontent.com/assets/14194793/13613910/576abda4-e56e-11e5-9c59-368ca3d047e3.png)

![collection runner_010](https://cloud.githubusercontent.com/assets/14194793/13613913/5aa3c150-e56e-11e5-8a8f-c74ca20c0eab.png)

To conclude: "All" and "Failed" show both passed and failed requests/tests. "Passed" only shows the passed requests.

**Comment by SamvelRaja** [comment]
I hope the Failed results also includes the Requests **passed** in `iteration 1` and **didn't run** in the  `iteration 2`.
If so, we have found an RC and fixed in our internal build, will be available in the next version. 
Can you cross check and let us know is that the scenario happened?

**Comment by mstaalesen** [comment]
Yeah, that sounds to be correct. Sorry for not being clear, but:

All: Shows Passed and Failed Requests
Passed: Shows only Passed Requests
Failed: Shows Passed and Failed Requests

**Comment by SamvelRaja** [comment]
@mstaalesan you update to  **4.0.2**  to get the fix for this.  Thanks for reporting

**Comment by mstaalesen** [comment]
confirmed, working again.
