### ISSUE TITLE
Cannot interact with lower Team Library "View Docs" or "Subscribe" buttons

### ISSUE THREAD

**Issue by joeborysko** [a85/POSTMan-Chrome-Extension#1813]
I cannot interact with some of the bottommost Team Library buttons. When I mouse over the Subscribe or View Docs buttons for the upper collections, these buttons become darker, indicating that I can click on them. These buttons never becomes darker for the lower collections, and likewise clicking on them doesn't result in any noticeable action. In order to click on these, I need to either reduce the Postman window height, or (if possible) scroll down further until they are high enough on the window. See the screenshot below.

![screenshot](https://cloud.githubusercontent.com/assets/11723697/13609673/3a8bfe0c-e517-11e5-9d06-cb89876b7312.png)

**Comment by joeborysko** [comment]
I just noticed that the same issue happens for the dropdown for selecting an environment.
![screenshot](https://cloud.githubusercontent.com/assets/11723697/13611592/8fe51f56-e520-11e5-9805-8a636f93672e.png)

**Comment by numaanashraf** [comment]
@joeborysko Thats odd. Could you let us know your Chrome and OS version?

**Comment by joeborysko** [comment]
@numaanashraf It appears to be an issue with my machine itself, because I just noticed it happening to [SourceTree ](https://www.sourcetreeapp.com/) as well.

Chrome version: 48.0.2564.116
OS: Windows 8

**Comment by joeborysko** [comment]
Restarting my computer resolved this. Sorry for the false bug!
