### ISSUE TITLE
Mac app, CMD+W closes two tabs instead of one

### ISSUE THREAD

**Issue by sebastianarena** [a85/POSTMan-Chrome-Extension#1814]
Hello.
I've been trying for the last few days the "new" Mac app.
It's great!
Having CMD+W closing tabs and warning of unsaved changes is great.
The only problem is that it seems the app is closing two tabs instead of one with a single tab of CMD+W.
Thanks!
Sebastian

**Comment by abhijitkane** [comment]
@kaminoo Thanks for reporting this - we've fixed this in our internal build, and will push out an update tomorrow.

**Comment by sebastianarena** [comment]
@abhijitkane Awesome!!!

**Comment by SamvelRaja** [comment]
@kaminoo you can find the fix for this in our latest  **4.0.2** app
