### ISSUE TITLE
Feature request: Manage Environments - Move Bulk edit to top

### ISSUE THREAD

**Issue by mstaalesen** [a85/POSTMan-Chrome-Extension#1815]
When managing environments, I often tend to mass edit with the "Bulk Edit" feature. The only "problem" I have with the way it is implemented now, is that the button to go into "Bulk Edit"-mode is at the bottom of all the stored environment variables (for both Global and Environment variables). It can be a bit tedious to scroll to the button when I have a long list of stored variables, and it would be a nice quality of life experience if the button could be moved to the top e.g something like this:
![postman_011](https://cloud.githubusercontent.com/assets/14194793/13614168/77fefa8e-e56f-11e5-8ab2-832bc7b87dc1.png)

(Sorry for my poor UX-design skills ;) )

**Comment by xxldoctor** [comment]
+1

**Comment by aditikul** [comment]
@xxldoctor @mstaalesen This should be fixed now. Let me know if it looks different for you, but Bulk Edit should be on top now.
