### ISSUE TITLE
Usability: Confusing with both "Submit" and "Update" buttons available when Bulk editing

### ISSUE THREAD

**Issue by mstaalesen** [a85/POSTMan-Chrome-Extension#1816]
When Bulk editing either environment or global variables, I have more than once clicked the wrong button when I want to store the changes that I made. As it is right now, managing the environment variables in Bulk Edit mode looks like this:

![postman_012](https://cloud.githubusercontent.com/assets/14194793/13614398/88ff405e-e570-11e5-9160-b4228c13716b.png)

As I also wrote in the screenshot, having both buttons present (Submit and Update) like the way it is now is confusing for the users. Which again leads to frustration when the changes that were made are not actually stored as the user thought it would be.

**Comment by xxldoctor** [comment]
+1

**Comment by aditikul** [comment]
@xxldoctor @mstaalesen Thanks for reporting this! Working on a fix right away.

**Comment by mstaalesen** [comment]
Looks better now. Closing.
