### ISSUE TITLE
Postman 4.0.1 copy function removes linefeeds and spaces from JSON

### ISSUE THREAD

**Issue by Atomixx** [a85/POSTMan-Chrome-Extension#1817]
Using the Copy button spaces and line feeds removed from the response body JSON.
![snag-00004](https://cloud.githubusercontent.com/assets/17732378/13619147/d31da772-e587-11e5-9d60-f3ff25c71d81.gif)
![snag-00005](https://cloud.githubusercontent.com/assets/17732378/13619173/f58945b4-e587-11e5-8275-dd4e3d8c02e4.gif)
![snag-00006](https://cloud.githubusercontent.com/assets/17732378/13619302/911ad254-e588-11e5-9573-2e05b54c9a12.gif)

**Comment by abhijitkane** [comment]
@Atomixx Thanks for reporting this. We'll be pushing a fix in the next release.

**Comment by Atomixx** [comment]
Thanks for the quick fix.

**Comment by SamvelRaja** [comment]
@Atomixx we have a fix for this in our latest version  **4.0.2** kindly update and check the same

**Comment by Atomixx** [comment]
Successfully tested
