### ISSUE TITLE
Issues making calls - stuck on "Loading..."

### ISSUE THREAD

**Issue by deive** [a85/POSTMan-Chrome-Extension#1819]
I'm using the Windows Chrome plugin and have just got updated to 4.0.1 ( win / x86-64 ) ( Chrome 48.0.2564.116 ).
Almost all the time this issue is happening, here is the console log:
"requester.js:153692 Uncaught TypeError: Cannot read property 'map' of undefined"

```
_react2.default.createElement(
                'div',
                { className: 'cookie-table-content' },
                cookies.map(function (cookie) {
                  return _react2.default.createElement(_ResponseCookieViewerRow2.default, { cookie: cookie, key: cookie.name });
                })
              )
```

**Comment by SamvelRaja** [comment]
Thanks for bringing this to our notice. We have found the RC. Will release a patch for it in the next version.

**Comment by deive** [comment]
Awesome, thanks!

**Comment by SamvelRaja** [comment]
@deive can you confirm the fix which went on for this issue in **4.0.2**

**Comment by deive** [comment]
Sorry for the delay in response, I have now got version 4.0.5 and this seems to have been fixed, thanks muchly!

**Comment by Ettery** [comment]
I have also had this problem with the native app v.6.2.2.  Reboot didn't help I had to export my collections, uninstall, delete the app folder and re-install.  Back to normal.  Problem seemed to be triggered by a Postman update I installed.
