### ISSUE TITLE
Search/Replace with Dark theme has white font on white background

### ISSUE THREAD

**Issue by mstaalesen** [a85/POSTMan-Chrome-Extension#1820]
It is impossible to see what is written in the search/replace fields when the Dark theme is selected. The font for the text and background are almost (if not exactly) the same color:

![postman_013](https://cloud.githubusercontent.com/assets/14194793/13633905/4c1a58e0-e5f2-11e5-80b7-9cb0ce237174.png)

To be able to see what is written, I have to select it:

![postman_014](https://cloud.githubusercontent.com/assets/14194793/13633908/4f87f5a0-e5f2-11e5-8fa0-a10e083a43b0.png)

**Comment by numaanashraf** [comment]
@mstaalesen Thanks for reporting this. This has been fixed in our internal build and should land in tomorrow's release.

**Comment by mstaalesen** [comment]
Cheers!
