### ISSUE TITLE
Postman not saving values of AWS signature helperAttributes

### ISSUE THREAD

**Issue by willrichboa** [a85/POSTMan-Chrome-Extension#1821]
Just updated to the new version: 4.0.1
( win / x86-32 )
( Chrome 47.0.2526.106 )

All of my aws signature helper values have been wiped out.  Attempts to add them back in seems to work, but when you close and reopen the request they are again missing.  Downloading the collection then shows all of the helperAttributes as empty strings.

ex
"currentHelper": "awsSigV4",
            "helperAttributes": {
                "accessKey": "",
                "secretKey": "",
                "awsRegion": "",
                "serviceName": "",
                "saveToRequest": true
            },

**Comment by abhijitkane** [comment]
@willrichboa Are you checking the 'Save helper data to request' checkbox before saving the request?

**Comment by willrichboa** [comment]
Yes.  If the "Save helper data to request" checkbox is set to false then the request doesn't save the authorization at all.  i.e. it is set to "No Auth".

**Comment by willrichboa** [comment]
I updated to the newest version of chrome and found that the issue remains.
To help clarify what I am seeing I decided to give a step by step breakdown of how this is working.
1. Create a new request or use an existing one.
2. Under the "Authorization" tab: select type of "AWS Signature".
3. Update, "AccessKey", "SecretKey", "AWS Region", and "Service Name" to any values.
4. Select the checkmark on the "Save helper data to request"  so that it is checked.
5. Save the request to a new or existing collection.
6. Close the request tab.
7. Reopen the request.

Expected: the AWS helper values persist.
Observed: the AWS helper values are blank.

**Comment by abhijitkane** [comment]
Got it. We've fixed this in our internal build, and will be pushing out a fix in a day or two.

**Comment by paulsperanza** [comment]
Is this the same issue? - I'm right clicking on the response body to set environment variables and they are not be applied. For example, I have a login function that returns an auth token in the response. When I run another call I get HTTP Error 400. The request is badly formed. I looked at it in fiddler and my authorization header just shows Bearer     (Bearer [] - used brackets to emulate null).

This was all working a few days ago and Postman looks different so it looks like an update happened.

Thanks,
Paul

**Comment by abhijitkane** [comment]
@paulsperanza No, this is a different issue, but this will be fixed in the next release as well :)

**Comment by abhijitkane** [comment]
@willrichboa Can you confirm this fixed in the latest version - 4.1.2?

**Comment by paulsperanza** [comment]
Yes

Paul Speranza

**Comment by willrichboa** [comment]
@abhijitkane It is not saving the "Service Name" value

4.1.2
win / x86-32
Chrome 49.0.2623.87

**Comment by willrichboa** [comment]
Should I open a separate issue for the service name not being saved?

**Comment by abhijitkane** [comment]
@willrichboa Thanks for reporting this. We've fixed this internally, and will push the fix in the next release.
