### ISSUE TITLE
Copying text from a request's description no longer works in 4.0.1

### ISSUE THREAD

**Issue by mdconatser** [a85/POSTMan-Chrome-Extension#1822]

**Comment by mdconatser** [comment]
It was nice being able to copy the full description including markup for a request and paste it into a document to make a quick API document, but this is no longer possible on 4.0.1.

**Comment by abhijitkane** [comment]
Thanks for reporting this. We'll push a fix in the next release.

**Comment by mdconatser** [comment]
Thanks for quickly fixing this in 4.0.2.
