### ISSUE TITLE
new tests taking a long time to sync

### ISSUE THREAD

**Issue by wkuckro** [a85/POSTMan-Chrome-Extension#1823]
I am having the same issue as previously described. It can take an hour sometimes to get a test changed in postman to update for call via url in newman.

https://github.com/postmanlabs/postman-app-support/issues/1554

**Comment by sobtiankit** [comment]
Hi @wkuckro, the -u option works with collections that are explicitly pushed to the server, I.e. Click on the 3 dots next to the collection > Share > Update link. Is that what's taking time?

**Comment by wkuckro** [comment]
yes. I've updated a test, saved the test script, updated the link for the collection, and it's still taking over 30 min so far to run the new test.

I can see the test in another OS's Postman APp, so i know the sync worked at least

**Comment by abhijitkane** [comment]
@wkuckro Do you see the updated test script when you open the URL in your browser (use an Incognito Chrome tab - otherwise Postman will open and import the collection)

**Comment by wkuckro** [comment]
Yes. I see the test in the browser. 

I ran the test in newman again just to check, and the test is not visible there. I am running newman in Ubuntu 14.04 LTS

**Comment by abhijitkane** [comment]
@czardoz Could this be some sort of caching issue with Newman?
@wkuckro When you use the collection in newman, try appending `?random=123` at the end of the URL. That might force newman to re-download the collection.

**Comment by czardoz** [comment]
No, Newman does not cache anything between two different runs. 

@wkuckro, the collection links are not related to Sync. The URLs you use in Newman are handled separately.

**Comment by abhijitkane** [comment]
@czardoz Not newman itself of course, but the Node layer.

**Comment by czardoz** [comment]
No, they're separate processes and do not share anything, unless @wkuckro is using Newman as a library. 

@wkuckro, can you share the exact command you're using to run Newman? (If the collection contains sensitive information, do not share the URL)

**Comment by wkuckro** [comment]
$newman -u `collection link copied from postman`

**Comment by abhijitkane** [comment]
@wkuckro Does appending `?random=123` to the URL help?

**Comment by wkuckro** [comment]
well, i jsut restarted my test machine, and now the issue isn't occurring

I wonder if there is a intermittent updating cache issue somewhere that isn't allowing an update when you call the collection

**Comment by czardoz** [comment]
@wkuckro, are you behind a HTTP proxy or firewall?

**Comment by wkuckro** [comment]
firewall

**Comment by czardoz** [comment]
That's probably what is caching the collection URL. Just add any URL parameter to the collection URL and change it for each run (like @abhijitkane mentioned before). That should bust the cache every time.

**Comment by wkuckro** [comment]
ok thanks

**Comment by abhijitkane** [comment]
@wkuckro We've also added a no-cache header on our API - so your firewall/proxy shouldn't be caching it anymore.
