### ISSUE TITLE
Text could be bigger

### ISSUE THREAD

**Issue by donhmorris** [a85/POSTMan-Chrome-Extension#1824]
Postman 3.0 looks good but it seems to not be fully cooked.
1. Font for choosing format for body in put request are really small. They dont enlarge when you choose a bigger font scheme.
2. The font for the text editor is too small when entering json data 
3. I lied it better when postman was integrated into chrome as a tab. Im usually testing a web page alongside webstorm. It was easier to click a chome tab to go to poastman than it is to switch to another app window.

I would love to use postman 3 but IM going to stick to the older version because of the above issues. It really slows me down. I do like a lot of what has been done in 3.

**Comment by jayonsoftware** [comment]
Yep. I like to see the Font size bigger.

**Comment by aditikul** [comment]
@donhmorris @jayonsoftware Can you check out the latest updates and see if things are better for you? We also have a native Mac app and Windows app now that will help in the switching  issue and should be a smoother experience.

**Comment by a85** [comment]
The entire UI can be zoomed in/out just like a browser window now. Check out Settings > Shortcut to see how. :)
