### ISSUE TITLE
Let pre-request script generate JSON request body

### ISSUE THREAD

**Issue by blowback** [a85/POSTMan-Chrome-Extension#1825]
I'm trying to use API chaining to 1) fetch an object from a GET endpoint 2) modify it in a pre-test script and 3) upload the modified object using a PUT endpoint.

Currently there seems to be no way of doing this. Pre-request scripts only have read-only access to the request object, and you can't use {{...}} style template vars inside the hard-coded request body (well, not without enclosing them in quotes, "{{...}}", which means you can't use them to construct arbitrary bits of JSON).

For example, I use GET to fetch the following object:

```
{
  "deviceId": "447973507287",
  "mappings": [
    {
      "currency": "USD",
      "walletId": "100000001496"
    },
    {
      "currency": "GBP",
      "walletId": ""
    },
    {
      "currency": "EUR",
      "walletId": ""
    }
  ],
  "accountId": "72545925"
}
```

and now I want to set every walletId property to "9999" and PUT it back:

```
{
  "deviceId": "447973507287",
  "mappings": [
    {
      "currency": "USD",
      "walletId": "9999"
    },
    {
      "currency": "GBP",
      "walletId": "9999"
    },
    {
      "currency": "EUR",
      "walletId": "9999"
    }
  ],
  "accountId": "72545925"
}
```

**Comment by blowback** [comment]
In my GET request test script I tried:

``` javascript
var data = JSON.parse(responseBody);
postman.setEnvironmentVariable("deviceMapping", responseBody);
```

and in the PUT request pre-request script I tried:

``` javascript
var deviceMapping = JSON.parse(environment["deviceMapping"]);

deviceMapping.mappings.forEach(function(d) {
    d.walletId = environment["wallet1"]; // wallet1=9999
});

postman.setEnvironmentVariable("updateMappings", JSON.stringify(deviceMapping.mappings));
postman.setEnvironmentVariable("updateAccount", deviceMapping.accountId);
```

And the PUT request body:

```
{
    "deviceId": "447973507287",
   "mappings": {{updateMappings}},
   "accountId": "{{updateAccount}}
}
```

**Comment by abhijitkane** [comment]
@blowback You can try something like this:
In the test script for request 1:

``` javascript
postman.setEnvironmentVariable("deviceMapping", responseBody);
//variables need to be strings
```

In the pre-request script for request 2:

``` javascript
var deviceMapping = JSON.parse(environment["deviceMapping"]);

deviceMapping.mappings.forEach(function(d) {
    d.walletId = environment["wallet1"]; // wallet1=9999
});

postman.setEnvironmentVariable("putBody", JSON.stringify(deviceMapping));`
```

And the body:

```
{{putBody}}
```

**Comment by blowback** [comment]
Aha! Marvellous. Many thanks!

**Comment by loganbeougher** [comment]
@abhijitkane Thank you!!!! Best thing I found on google today!!!!

**Comment by drexler** [comment]
Awesome just what i was looking for!

**Comment by wangjunting** [comment]
![image](https://user-images.githubusercontent.com/13152792/27617239-be476ad6-5be7-11e7-8de3-d4a719c1a25e.png)

how to do this?

**Comment by wangjunting** [comment]
@abhijitkane

**Comment by iexxk** [comment]
@wangjunting "{{putBody}}"

**Comment by othmaan** [comment]
"{{putBody}}" is adding extra "" then request becomes ""{"cusumerNumber": "123"}""

**Comment by sahanabadri** [comment]
I followed the above-mentioned code to set dynamic values for the variables. But I m not able to reset every time, I call the function. How to make the req 2 to wait till req1 is completed... If I get an answer, I will you grateful to you... Many thanks in advance...

**Comment by qb-jaseem** [comment]
Is there any way to autoincrement any variable in postman body or pre request script?

**Comment by dmincf** [comment]
I've managed to create a script that replaces all the variable placeholders from body in the pre-request script:
```javascript
var requestToUpdate = pm.request.body.toString();
console.log("requestToUpdate:" + requestToUpdate);

var elementsToReplace = requestToUpdate.match(/{{.+}}/g);
console.log("elementsToReplace: " + elementsToReplace);

var updatedRequest = requestToUpdate;
elementsToReplace.forEach(function(entry) {
    var variableName = entry.replace("{{", "").replace("}}", "");
    updatedRequest = updatedRequest.replace(entry, pm.variables.get(variableName));
});


console.log("updatedRequest:" + updatedRequest);
pm.request.body = updatedRequest;
```
