### ISSUE TITLE
Postman 4.0.1_File preview formatting error in the test runner

### ISSUE THREAD

**Issue by Atomixx** [a85/POSTMan-Chrome-Extension#1826]
Data source: csv
These defects exist:
- Scroll bar not visible at the bottom
- Headings are centered vertically
- Overlaid presentation of content
- Window data preview very narrow

![snag-00007](https://cloud.githubusercontent.com/assets/17732378/13652198/1cf46386-e64b-11e5-82f1-b6be49cb36c6.gif)
![snag-00008](https://cloud.githubusercontent.com/assets/17732378/13652197/1cf4ab2a-e64b-11e5-9ce1-3613afaa35b5.gif)
![snag-00009](https://cloud.githubusercontent.com/assets/17732378/13652196/1cf25f3c-e64b-11e5-82df-f270436f178b.gif)
![snag-00010](https://cloud.githubusercontent.com/assets/17732378/13652199/1cf58068-e64b-11e5-8af7-b937c5ad2ca0.gif)

**Comment by SamvelRaja** [comment]
@Atomixx Thanks for bringing this to our notice. you can expect a fix in our next release.

**Comment by SamvelRaja** [comment]
@Atomixx we have came up with the latest version  **4.0.2** . Which has the fix for this. Can you confirm the same.?

**Comment by Atomixx** [comment]
**Test Result:**

Scroll bar not visible at the bottom   -   resolved
Headings are centered vertically      -   not fixed
Overlaid presentation of content      -   resolved

[Data.zip](https://github.com/postmanlabs/postman-app-support/files/169976/Data.zip)

![snag-00012](https://cloud.githubusercontent.com/assets/17732378/13715450/17768200-e7d5-11e5-8da1-ef607ada42fe.gif)
![snag-00013](https://cloud.githubusercontent.com/assets/17732378/13715453/1777656c-e7d5-11e5-9080-1d737aa123fc.gif)
![snag-00014](https://cloud.githubusercontent.com/assets/17732378/13715451/1776d0ca-e7d5-11e5-9322-7519d48d65e7.gif)

**For comparing with Version 3.2.20**
![snag-00015](https://cloud.githubusercontent.com/assets/17732378/13715454/1779e4fe-e7d5-11e5-8f00-2136776eec63.gif)
![snag-00016](https://cloud.githubusercontent.com/assets/17732378/13715452/17771238-e7d5-11e5-9932-72607c5ab555.gif)

**Comment by SamvelRaja** [comment]
@Atomix can you update for one last time. The actually fix went in at **4.0.4** it's my mistake mentioning the wrong version😐

**Comment by SamvelRaja** [comment]
@Atomixx Can you cross check and close it ?

**Comment by Atomixx** [comment]
Successfully tested
