### ISSUE TITLE
Remember last preview type

### ISSUE THREAD

**Issue by ghost** [a85/POSTMan-Chrome-Extension#1827]
The latest version dosen´t remember the preview options of the response .

**Comment by abhijitkane** [comment]
@ZStelmo Are you talking about when you re-open the app, or switch tabs?
In the second case, all response options (pretty/raw/preview) are being preserved. Can you also mention the version of Postman that you're using?

**Comment by ghost** [comment]
I´m using the v 4.0.1 and working  in the same tab the response options options always go back to (pretty) i have to click on the (preview) every time that i send the request. 
I´m a PHP developer use a lot of var_dump for debugging , have to change from pretty to preview in all request.

**Comment by SamvelRaja** [comment]
@ZStelmo We missed that in our current version, in the meantime we have implemented in our internal build. Will be available to you in the next version

**Comment by ghost** [comment]
Thanks in advance. ;)

**Comment by SamvelRaja** [comment]
Hey @ZStelmo we have pushed our `4.0.2` update can you check with that. we implemented this missed out feature there

**Comment by ghost** [comment]
The feature is implemented , thanks .
