### ISSUE TITLE
Context menu not working in 4.0.4 on OS X 10.11.3

### ISSUE THREAD

**Issue by andreassiegel** [a85/POSTMan-Chrome-Extension#1828]
No matter where I click in the Postman app on OS X, I don't see any context menu.

Right clicks can only be used for cursor positioning in text fields.

**Comment by abhijitkane** [comment]
@andreassiegelrfid Can you confirm this fixed in the latest app?

**Comment by andreassiegel** [comment]
Looks good! The context menu is back. Thanks! :)
