### ISSUE TITLE
Copying text from a environment properties preview no longer works in 4.0.1

### ISSUE THREAD

**Issue by Maximk0o** [a85/POSTMan-Chrome-Extension#1829]
Steps to Reproduce
1. Click on the eye icon in the right-top corner
2. Try to select text in the appeared dialog 
Expected Results
Text should be able to selecting and copying
Actual Results
Text isn't selectable
Examples
Video: http://screencast.com/t/LfuTKz4w

**Comment by SamvelRaja** [comment]
@Maximk0o This had been fixed in our internal build. Will be out in the next release. Thanks for bringing to our notice.

**Comment by SamvelRaja** [comment]
@Maximk0o we have released the build **4.0.2** can you check the same for your fix.
