### ISSUE TITLE
How do I know this is not a phishing scam?

### ISSUE THREAD

**Issue by bbsimonbb** [a85/POSTMan-Chrome-Extension#1830]
The Postman Oauth2 sign-in-with-google pops in a window without an address bar.You're asking people for their google password, perhaps the most sensitive piece of information they have. And their's no way for the user to verify the destination of this info. This urgently needs fixing.

**Comment by a85** [comment]
That's an API provided by Chrome for OAuth 2 flows. Not sure what we can do here but will look into it.

**Comment by bbsimonbb** [comment]
Show the address bar ?

**Comment by abhijitkane** [comment]
@bbsimonbb This functionality is not exposed by the API that Chrome provides - https://developer.chrome.com/apps/identity#method-launchWebAuthFlow

**Comment by sdnts** [comment]
Opening up the DevTools and checking network traffic should conclusively prove that logging in/out is completely secure.
Closing.

**Comment by bbsimonbb** [comment]
Yup, so I'm being asked to enter my google password into a window that's not a google window, and this window will forward my password to google. How is that not a security breach? Very curious.
