### ISSUE TITLE
Error while importing Curl: Zero or Multiple option-less arguments. Only one is supported (the URL)

### ISSUE THREAD

**Issue by suhaim** [a85/POSTMan-Chrome-Extension#1831]
I get this error when using the following curl

`curl -i -X POST -H "Content-Type: multipart/form-data" -H "Authorization: SIMPLE pass" -F "card={\"text\":\"sometext\", \"userName\":\"%USERNAME%\", \"screenName\":\"screenName\", \"avatarUrl\":\"https://someurl\"};type=application/json" -F "pic=@file.jpg" "https://someurl" -v —insecure 
`

Error while importing Curl: Zero or Multiple option-less arguments. Only one is supported (the URL)

Is there a way around this?

**Comment by Jayuda** [comment]
+1

**Comment by ElSifi** [comment]
+1

**Comment by josephnoall** [comment]
+1

**Comment by abhijitkane** [comment]
@ElSifi @Jayuda @suhaim This curl command can successfully be imported in v4.4.3 of Postman.

**Comment by Varunperla** [comment]
+1

**Comment by dalipkumar703** [comment]
How to get v4.4.3 @abhijitkane ? 
I got same error.

**Comment by sdnts** [comment]
@dalip123 If you're on the Chrome App, you should be able to go to `chrome://extensions`, click on `Update Extensions`. This will update all your Chrome Apps.
If you're on the native app, you should open up Settings (wrench icon on the top right), switch over to the `Update` tab, click on `Check for Updates`, and let Postman install the update.

Once you do, you should be able to check your current app version by heading over to Settings again, in the `About` tab. The latest version as of right now is 4.9.3

**Comment by mchavarriae** [comment]
This is not working on 4.9.3, Anyone has this problem?

**Comment by sdnts** [comment]
@mchavarriae Which URL are you using? You can leave out sensitive info from it, I'm only interested in the overall URL structure.

**Comment by sashberd** [comment]
+1
