### ISSUE TITLE
File uploads stopped working

### ISSUE THREAD

**Issue by xp500** [a85/POSTMan-Chrome-Extension#1833]
The requests generated when posting files are not being created properly.

This is a POST to www.google.com attaching one file as a `form-data`

```
POST  HTTP/1.1
Host: www.google.com
Cache-Control: no-cache
Postman-Token: 27cd9bb8-9008-3b10-3fb2-838926cd1578
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

----WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="undefined"
Content-Type: undefined


----WebKitFormBoundary7MA4YWxkTrZu0gW 
```

I am sure this was working yesterday so I'm not sure if it's the same as #1806

I'm using the Postman app on Windows 10.

**Comment by LaughlinJames** [comment]
I'm seeing the same thing using the Postman app on OSX 10.11.1 El Capitan

**Comment by LaughlinJames** [comment]
One thing I've noticed is that if I remove the file field by clicking the x on that line, then add it back in, choose my file and run the API call, it works immediately.

**Comment by abhijitkane** [comment]
@LaughlinJames @xp500 What version of Postman are you running? The `filename="undefined"` issue should be fixed in the latest versions.

**Comment by LaughlinJames** [comment]
v 4.0.5

**Comment by xp500** [comment]
@abhijitkane v4.0.2

**Comment by abhijitkane** [comment]
@LaughlinJames Are you toggling the Interceptor on/off? After every toggle, you'll need to reselect the file.

**Comment by enekochan** [comment]
Switching the interceptor off fixed the problem for me (version 4.0.5 here). Thanks!

**Comment by xp500** [comment]
This is still broken for me...I don't have the interceptors extension installed.

**Comment by abhijitkane** [comment]
@xp500 What version of Postman are you on now?

**Comment by xp500** [comment]
@abhijitkane Still 4.1.2...there doesn't seem to be a newer one in the Windows Chrome Store

**Comment by abhijitkane** [comment]
@xp500 No, that's the latest version. Can you try removing that particular row in the form-data editor and re-adding the file?
Are you able to make POST requests to http://echo.getpostman.com/post with the file?

**Comment by xp500** [comment]
@abhijitkane Yes, the files are posted correctly.

The problem is the "Generate Code" button which doesn't load the filename properly. For example, if I generate a curl request this is what it does

```
curl -X POST -H "Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW" -H "Cache-Control: no-cache" -H "Postman-Token: 194818cd-2cbe-924b-7e2b-9bc65da98030" -F "file=@[object Object]" "http://echo.getpostman.com/post"
```

Note the `"file=@[object Object]"` which should be `"file=@/path/to/file"`.

With HTTP it directly puts `undefined` (as in my original snippet).

Tried readding the row, using a row other than the first but neither seemed to work

**Comment by abhijitkane** [comment]
Ah..this issue was the filename not being sent at all. We're looking at the issue you mentioned - filenames not included in the generated code.
