### ISSUE TITLE
Interceptor Not working

### ISSUE THREAD

**Issue by elpoisterio** [a85/POSTMan-Chrome-Extension#1834]
With Latest Update interceptor is not showing api in postman client and some issues with client see picture.
Both screenshot taken in a gap of 10 minutes
![screenshot from 2016-03-11 02 49 50](https://cloud.githubusercontent.com/assets/7325457/13684998/69c46370-e734-11e5-92eb-51efadbed32a.png)
![postman](https://cloud.githubusercontent.com/assets/7325457/13684999/69e03a96-e734-11e5-87d9-6bcae872c402.png)

**Comment by abhijitkane** [comment]
@elpoisterio I'm not able to reproduce this. Can you check with the latest version of the app - 4.1.2?

**Comment by elpoisterio** [comment]
the latest version doesn't shows you the recent history. One has to scroll down and then scroll up see the latest history.

**Comment by lal1029** [comment]
I just installed the latest Postman client for mac, along with Postman interceptor. Though the interceptor is clearly working, nothing shows up in the history bar in Postman.

**Comment by abhijitkane** [comment]
@lizerspockzebrafish The Interceptor does not work with the Mac app. You'll need to use the Mac app's proxy for this - https://www.getpostman.com/docs/capture_mac
