### ISSUE TITLE
after update cannot send any requests under ubuntu 15.10

### ISSUE THREAD

**Issue by ta3pks** [a85/POSTMan-Chrome-Extension#1835]

**Comment by numaanashraf** [comment]
@NikosEfthias Please let us know your Postman app version and Chrome version. Also, would it be possible to open the console check if there are any errors there? You can find the steps to open the console [here](http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/).

**Comment by ta3pks** [comment]
@numaanashraf 
http://i.imgur.com/1u4QTEQ.png heres console output theres nothing weird
![test](https://cloud.githubusercontent.com/assets/9097437/13720736/5a37a168-e821-11e5-8d69-85542fe49999.gif) heres the wierd behaviour nothing is happening
heres the chrome version http://i.imgur.com/1R57CFM.png
postman version http://i.imgur.com/kAEsSGN.png

**Comment by abhijitkane** [comment]
@NikosEfthias can you try disabling the Interceptor (satellite icon in the top bar) and sending the request?

**Comment by ta3pks** [comment]
it does work when i disable that @abhijitkane

**Comment by abhijitkane** [comment]
@NikosEfthias Can you try disabling and enabling Postman Interceptor from `chrome:/extensions`? If that doesn't work, you should check for errors in Postman's console when you try to send the request - http://blog.getpostman.com/2015/06/13/debugging-postman-requests/
