### ISSUE TITLE
Windows 7 in dark theme when search in response, text is not visible

### ISSUE THREAD

**Issue by ianomad** [a85/POSTMan-Chrome-Extension#1836]
Steps to reproduce:

Version: win/ x82-32 Chrome 48.0.2564.116 Postman: 4.0.1
Postman dark theme
Make request to any API with json response and try to search in response by text by clicking CTRL + F, start typing text - white text is not visible in white textbox

**Comment by SamvelRaja** [comment]
@ssymbol we have released our latest version which already had the fix for this, can you update your postman and check the same.

**Comment by ianomad** [comment]
@SamvelRaja 
I am looking for an update as chrome plugin, but there is no update yet. What version is it?

**Comment by numaanashraf** [comment]
@ssymbol We are rolling out 4.0.x updates over the course of this week. You should be getting the latest version (4.0.4) over the next couple of days.

**Comment by pconesa** [comment]
same on MAC, nice tool by the way! ;-)...hold on...I switched back to dark theme and now results showed up.

I've relaunched POSTMAN and looks ok!. Weird.
