### ISSUE TITLE
Feature-Request: Session Variables

### ISSUE THREAD

**Issue by roeschjohannes** [a85/POSTMan-Chrome-Extension#1837]
It would be useful, to have a third space to store variables. This space should be in session context. Each time postman is started, this space is created and i can store variables in it. On closing Postman the space will be destroyed.
It would be useful, because i can store many temporary variables, without the need to clean it up.
A function like "postman.clearSessionVariables()" could also be very useful in this context.

**Comment by morrisnc** [comment]
This would be very useful for testing where we pass values between endpoints when running a test in a collection.  An example would be a create runs that passes back an id that is then used to run the next step (endpoint) in the collection to find that user by id.

**Comment by a85** [comment]
You can do this using environment variables: http://blog.getpostman.com/2014/02/20/using-variables-inside-postman-and-collection-runner/

More improvements on this coming soon. Check out the Postman blog: http://blog.getpostman.com/2016/06/14/introducing-postman-runtime-more-power-better-control/

**Comment by jimonthebarn** [comment]
+1

**Comment by mjhaller** [comment]
Environment vars are shared across the team, so they aren't suited for these types of variables.  There doesn't seem to be scope that supports the notion of a session.

**Comment by vkaegis** [comment]
@roeschjohannes @jimonthebarn @mjhaller @morrisnc  It's been a while but we have some concrete work on this idea coming up in the next version. In the meantime, check out the Sessions RFC (https://community.getpostman.com/t/sessions-in-postman/1925). Would love your feedback on this!

**Comment by harryi3t** [comment]
This is released with the latest version of Postman 6.2.3
