### ISSUE TITLE
Markdown support Postman v4.0.2

### ISSUE THREAD

**Issue by sschizas** [a85/POSTMan-Chrome-Extension#1839]
In my documentation of each API i use a lot of the <pre> and ### (fon indicating headings). In v4 they are broken.

**Comment by numaanashraf** [comment]
@n3trino Could you give us a sample description and a screenshot of how it renders within the app?

**Comment by eXeDK** [comment]
Also seems like Postman Documenter (Documentation feature) does not render Markdown.

**Comment by sschizas** [comment]
![screen shot 2016-03-11 at 15 15 47](https://cloud.githubusercontent.com/assets/1173551/13703115/269fd1b6-e79c-11e5-94c0-1d3b031a01f3.png)

**Comment by numaanashraf** [comment]
# test

**Comment by pawanrawal** [comment]
@eXeDK - Could you share the screenshot of the documentation that is generated for you , and the raw description which is not being rendered?

**Comment by eXeDK** [comment]
Just edited the code found that some tabs indenting the code had an effect. It works as expected now.

**Comment by dhoyt** [comment]
Here is what all my documentation looks like now ...

![image](https://cloud.githubusercontent.com/assets/10944880/13704433/ef02f3aa-e769-11e5-93a9-6afd41c6be19.png)

![image](https://cloud.githubusercontent.com/assets/10944880/13704452/144d12da-e76a-11e5-9d87-f47f2825518d.png)

In Documenter ...

![image](https://cloud.githubusercontent.com/assets/10944880/13705725/0f4cdd1e-e770-11e5-818f-b12746d243dd.png)

**Comment by SamvelRaja** [comment]
@dhoyt adding space after #'s would work in new version. Let we check and tell you about supporting without space sooner in this thread itself. And @eXEdk we had included the support for pre in our internal build will roll out the same in the next version

**Comment by eXeDK** [comment]
Thanks a lot @SamvelRaja :-)

**Comment by dhoyt** [comment]
@SamvelRaja ... thanks for the response. Are you saying that you are going to fix the problem by supporting without a space in a future version ?

**Comment by SamvelRaja** [comment]
@dhoyt After the discussion, i am afraid that we are **not** going to support the # followed by contents **without spaces**, as it is not the common way of representing Headings in most of the markdown editors, say github.

**Comment by dhoyt** [comment]
Wow ... So I have to change, by hand, hundreds of collections totaling hundreds if not thousands of endpoints to fix what you already allowed ... not good ... not good at all.

**Comment by eXeDK** [comment]
@dhoyt so you can't write a script to do that? Can't see how your invalid Markdown is Postman's problem.

**Comment by sschizas** [comment]
How about the < pre>< /pre> issue?

**Comment by numaanashraf** [comment]
@n3trino We will be supporting html tags, including `<pre>` in the coming release.

**Comment by SamvelRaja** [comment]
@n3trino the latest update `4.1.0` will support the HTML tag now.
