### ISSUE TITLE
Format RAW request data (pretty it) when selected JSON/HTML/XML

### ISSUE THREAD

**Issue by gregkaczan** [a85/POSTMan-Chrome-Extension#184]
Currently changing body-editor-mode select, highlights code depending on the type. It would be very helpful if code is also formatted (like it is in Pretty tab for response).

What about using current CoreMirror formating?

**Comment by morganthrapp** [comment]
Was this ever implemented? It doesn't seem to work by default, but I could be missing something.

The [latest comment on the PR](https://github.com/postmanlabs/postman-app-support/pull/187#issuecomment-12582193) seems to mention needing to resubmit. Was this ever done or are there plans to do so?

**Comment by sdnts** [comment]
Hi @morganthrapp! This repo no longer holds the actual app code :D
As for the issue itself, you can select your Raw and press `Cmd+B` to `Beautify`. Note that this depends on the format you have selected from the dropdown on the top of the raw request view.

**Comment by morganthrapp** [comment]
Oh, my bad. Should've checked the repo first!

`Cmd+B` works for me. I wasn't aware of that shortcut. Thanks for the help!

Could this be added to the Shortcuts tab in Settings? Or is there another location that lists the shortcuts?

**Comment by cpeeyush** [comment]
Cmd+B works for xml as well ? For me it only works for json not xml.

**Comment by EeeMt** [comment]
`Ctrl+b` works, but why can not find this shortcut at `SETTINGS -> Shortcuts` ?

**Comment by davidpastrana** [comment]
@cpeeyush I was facing the same problem, not being able to format XML as I was not selecting the right "raw" type. Ctrl+B can also work for formatting xml, we just need to select the right type of code from Body > raw, in my case "XML(text/xml)" and then Ctrl+B.
