### ISSUE TITLE
HTTP response Reason Phrase no longer being displayed in version 4 (chrome app) for custom http codes

### ISSUE THREAD

**Issue by sosuke3** [a85/POSTMan-Chrome-Extension#1841]
The latest version seems to have broken/removed the reason phrase for custom http response codes. This worked fine in 3.2.19.

Version 3.2.19:
![3.2.19](http://i.imgur.com/Nfaa5RN.png)

Version 4:
![4](http://i.imgur.com/GUEL5IL.png)

**Comment by abhijitkane** [comment]
@sosuke3 This has been fixed in the latest version. Can you confirm?

**Comment by sosuke3** [comment]
The March 31st release? Yes that seems to have fixed it. Thank you.
