### ISSUE TITLE
# After 4.0.2 update, Interceptor no longer intercepts PUT Messages

### ISSUE THREAD

**Issue by Wijnko** [a85/POSTMan-Chrome-Extension#1842]
Since the Postman update to 4.0.2 the interceptor no longer catches PUT Messages. Before the update the interceptor worked fine, and PUT Messages showed up in the History. Since the update to 4.0.2, PUT Messages do not Show up in the history anymore.

**Comment by abhijitkane** [comment]
@Wijnko Thanks for reporting this. We'll be pushing a fix for this in the next release.

**Comment by abhijitkane** [comment]
@Wijnko Can you confirm this fixed in the latest release?

**Comment by Wijnko** [comment]
Hi abhijitkane, yes, I can see the PUT messases again, thanks a lot! :+1:
