### ISSUE TITLE
4.0.2. Update - Can not DELETE strange line spacing in XML file

### ISSUE THREAD

**Issue by M-Crosscma** [a85/POSTMan-Chrome-Extension#1844]
When I opened Postman today, it appears that it's been upgraded to 4.0.2 (not sure what the last version I had was)

Now, all of my XML files have sporadic line spaces in them, and I can NOT delete them.  Deleting actually ADDS more lines.

**Comment by rburkitt** [comment]
I am also having this issue.
While testing a SOAP web service, I copy a block of xml into the body textbox and extra lines of empty space appear throughout the xml.
I am also on version 4.0.2.

**Comment by ghost** [comment]
I am seeing this same issue on version 4.0.1

**Comment by abhijitkane** [comment]
@rburkitt @Ann25 thanks for reporting this. We're working on this and will release a fix ASAP.

**Comment by M-Crosscma** [comment]
Thank you!  I look forward to a fix ASAP.

**Comment by numaanashraf** [comment]
@M-Crosscma @rburkitt @Ann25 We've pushed v4.0.4 with a fix for this. Do verify and let us know.

**Comment by M-Crosscma** [comment]
Thank you... Updated to version 4.0.5 and issue appears to be resolved.
