### ISSUE TITLE
Header Variable

### ISSUE THREAD

**Issue by cs45977** [a85/POSTMan-Chrome-Extension#1846]
I am attempting to send and authorization header using a environment variable.

The Variable , unfortunately, is sent as a the string literal  '{{apitoken}}'  rather than the value.  
Attached are screen shots demonstrate the issue 

Invalid token Response 
<img width="1273" alt="screen shot 2016-03-11 at 3 47 11 pm" src="https://cloud.githubusercontent.com/assets/561268/13716787/dd60ddfe-e7a2-11e5-886f-5e91686ec1c3.png">

Valid Token Response 
<img width="1266" alt="screen shot 2016-03-11 at 3 46 30 pm" src="https://cloud.githubusercontent.com/assets/561268/13716801/f09c86de-e7a2-11e5-8b0a-c3873dfef6cf.png">

Stack trace Debug showing the interpreted value in my API notice token = '{{apitoken}}'
<img width="827" alt="screen shot 2016-03-11 at 4 05 17 pm" src="https://cloud.githubusercontent.com/assets/561268/13716827/138a3236-e7a3-11e5-9ac2-df2f1df3e347.png">

I am using postman 4.0.5 

any help would be appreciated

**Comment by abhijitkane** [comment]
@cs45977 Can you ensure that there are no non-printing characters before and after "api_token" (both in the headers section, and in the Manage environments modal?

Also, you can add this: `console.log(environment);` to the request test script and send the request. The list of currently active environment variables will be printed in the console (Cmd + Option + I). Is the correct value of `api_token` shown there?

the Network tab will show the exact request payload that was sent.

**Comment by cs45977** [comment]
@abhijitkane I've consoled out the value and in the environment file it is correct but what is being passed in the request is not (see the Authorization header in the Network Tab)

<img width="1238" alt="screen shot 2016-03-14 at 5 49 51 pm" src="https://cloud.githubusercontent.com/assets/561268/13762476/3c256f00-ea0d-11e5-8ab4-f9cfb7014f70.png">
<img width="1260" alt="screen shot 2016-03-14 at 5 47 57 pm" src="https://cloud.githubusercontent.com/assets/561268/13762481/429191a2-ea0d-11e5-91b7-040a881783eb.png">

**Comment by cs45977** [comment]
User Error :(

There was a space when using 
postman.setEnvironmentVariable("apiToken ", apiToken);
fixed with 
postman.setEnvironmentVariable("apiToken", apiToken);

You may want to consider messaging a user when a variable does not have a set value , rather than sending a literal {{foo}} 

Thanks for the help!!
