### ISSUE TITLE
JSON Response Viewer cut

### ISSUE THREAD

**Issue by sormbrek** [a85/POSTMan-Chrome-Extension#1847]
Thank you first for this great application!

Problem: JSON response in pretty print cuts off, scrolls prematurely above the bottom of the panel.

To reproduce: Call an API.  By default, response is shown in "Pretty".  In my example, there are 22 lines shown.  Switch to "Raw", then switch back to "Pretty".  Now JSON is seen only on 12 lines, and cut off there.  However, I can still scroll in that 12 line tall area.  If I call the API again, it goes back to 22 lines.
Another way to fix this is just by resizing the bottom of the window.

It could be that there is a miscalculation in the size of the response area after going back from Raw to Pretty mode.
![postman bug](https://cloud.githubusercontent.com/assets/5048935/13720263/21aee35a-e7b9-11e5-9baa-cf44d6e0aee3.jpg)

**Comment by a85** [comment]
This has been fixed in the latest updates to the app.
