### ISSUE TITLE
How to show result in full screen.

### ISSUE THREAD

**Issue by shahidmau** [a85/POSTMan-Chrome-Extension#1848]
Is there any way to show result in full screen mode? Or at-least we should be able to maximize the output result. Also, is there any way to customize the theme as we do in sublime or other tools? Such as we should be able to change font size, color and background color etc.

**Comment by a85** [comment]
We support a 2-pane layout now. Outside of this we recommend copy/pasting the result or exporting it to a file.

**Comment by thomasazdon** [comment]
Adding to this - even though closed. With Visualizer - a full screen is almost a mandatory requirement.

**Comment by harish-github35** [comment]
@a85 Can you provide a valid reason for why this is so hard to implement, instead of closing it abruptly.
