### ISSUE TITLE
When pinned to start on Windows 10, Chrome app looses its icon

### ISSUE THREAD

**Issue by maciej-szlosarczyk** [a85/POSTMan-Chrome-Extension#1849]
When I pin the Windows app to start menu, it uses the Chrome icon instead of postman one. 
![image](https://cloud.githubusercontent.com/assets/2331765/13721812/07df200c-e83b-11e5-946c-1c6b9d5e1313.png)

In the taskbar or on the desktop the correct icon is used.

**Comment by danielcooperxyz** [comment]
I see a similar issue
![postman](https://cloud.githubusercontent.com/assets/5233036/13854683/9b341592-ec64-11e5-8686-50df2034c6fb.png)

**Comment by numaanashraf** [comment]
@d4nc00per @maciej-szlosarczyk Could you let me know your chrome version? This is an existing issue in Chrome on Windows 10. We'll confirm and get back to you once the fix hits Chrome stable/Canary.

**Comment by numaanashraf** [comment]
Related thread in Chrome forum - https://productforums.google.com/forum/#!topic/chrome/H_G-xgNSkPs

**Comment by maciej-szlosarczyk** [comment]
@numaanashraf: 49.0, the same as in the Chrome issue you pointed out. Thank you for your response.

**Comment by stevo-knievo** [comment]
Same here...
Chrome: Version 52.0.2743.116 m (64-bit)
Postman: 4.4.3

**Comment by ozzy432836** [comment]
We are a certain breed of people that get bothered with things like this :) i tried using a batch file to open it but then you cant change the icon for a batch file...even considered writing a quick app JUST to open the shortcut!

**Comment by a85** [comment]
All, the Chrome app platform has been deprecated by Google (http://blog.getpostman.com/2016/08/23/using-the-postman-chrome-app-implications-from-the-recent-google-announcement/), so I doubt a fix for this is going to come from them. I'd suggest that you move to our native Windows app: www.getpostman.com/apps. Will re-open if we see any update from Google.

**Comment by danielcooperxyz** [comment]
I wondered what was going to happen to postman. Thanks!

**Comment by krogan** [comment]
i originally had the chrome app and uninstalled it and then installed the local client
then the icon went blank as displayed above. irritating!

but on closer inspection, the tile was pointing to a defunct shortcut in:
C:\Users\XXXXXX\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Chrome Apps

I deleted the shortcut to postman in this folder and then re-pinned the Postman app (desktop app)

fixed :-)

**Comment by alexishdezlmL** [comment]
krogan, it worked perfectly, thanks

**Comment by claviering** [comment]
krogan, it worked perfectly, thanks
