### ISSUE TITLE
Post request body is not added to the generated code if not modified 

### ISSUE THREAD

**Issue by soufian044** [a85/POSTMan-Chrome-Extension#1850]
Hello 

generating codes was working good in the past , until today I used it and it didn't generate the body code, I am not sure if there has been a newer version released since then.

so when I generate the code it generate the body as null 
`OkHttpClient client = new OkHttpClient();
Request request = new Request.Builder()
  .url("https://www.oncf-voyages.ma/ResultatsTarifs.aspx")
  .post(null)`

so I pretended like i modified the form and the code is generated correctly 

`RequestBody body = RequestBody.create(mediaType, "_TSM_HiddenField_=zfzcZHdn7E0RE7O04hWIgmKEeWzbwIfqc1IZf73iR7M1&__ASYNCPOST=true&__EVENTARGUMENT=&__EVENTTARGET=&__EVENTVALIDATION=dhrVFLirt1gMnQviCl%2FMGnJcMYWcygZ1ki2VJIOtMzohIEKsU5bCyFOjudd6UYPoA1%2FVS6bquwN1gmjrTum9d5PyoJvGJkPDIgLWfwOv4%2FgM59N4O8rvtptKQEEKK1g41jiXuL4F3....`

is this a bug ? i just want to let you know , good luck

**Comment by abhijitkane** [comment]
@soufian044 Can you mention the Postman version you're on? 
We're not able to reproduce this issue. I clicked on a request (in the left sidebar) that had a x-www-form-urlencoded body, and the generate code button had the correct data.

**Comment by soufian044** [comment]
@abhijitkane  here we go , i am in version 4.0.5 

here , i made a gif animation take a look 
http://i.giphy.com/l2JJuI8WEw61z5B8k.gif

i will try later to uninstall and install again , maybe it's just me

**Comment by abhijitkane** [comment]
@soufian044 Are you still seeing this?

**Comment by soufian044** [comment]
@abhijitkane yes the bug still exist , if you want the body to be included in the generated code you have to click bulk edit and submit without editing anything only then it's included in the generated code otherwise it's just null as i demonstrated in the gif animation

**Comment by soufian044** [comment]
03-jun-2016 the bug still there

**Comment by sdnts** [comment]
@soufian044 We've resolved this issue and will be pushing a fix for this in the next release.

**Comment by vegetableman** [comment]
@kubah The issue has been fixed in the recent release `4.8.3` .  Closing this. Feel free to reopen if the issue still exists ^_^.

**Comment by soufian044** [comment]
Sorry guys but the problem still exists

**Comment by soufian044** [comment]
@vegetableman Sorry guys but the problem still exists , this time I can't even go around it by clicking _bulk edit_

could you please take a look at this ?

**Comment by dregge8** [comment]
I also have the issue when I try to generate the code for Body>Raw.  The entire body field no longer exists, about 7-10 days ago it was working fine.

**Comment by JohnDotOwl** [comment]
Same issue, the code generated for python and other doesnt include the body at all, x-www.form-urlencoded is empty but all the data required are in raw

**Comment by JohnDotOwl** [comment]
For python, it basically doesn't generate the Payload anymore , was working a few weeks ago. Anyway i can downgrade the version?

**Comment by soufian044** [comment]
let me tell you how to go around this bug until it's fixed , try **bulk edit** and then add space and remove it , and try again to generate the code , only then it will generate the full code

**Comment by sdnts** [comment]
Guys, we've fixed this, and will be rolling out a fix in the coming releases.

**Comment by mukkesmarty** [comment]
body is not included in code snippet. postman version = 4.8.3. please fix

**Comment by NathanDotTo** [comment]
Hi

I am also not seeing the body generated for Python Requests code in 4.8.3.

I tried the Bulk Edit of the environment as I think is being suggested above, but that did not work.

Regards

Nathan

**Comment by sdnts** [comment]
@soufian044 @dregge8 @rainbowhat @mukkesmarty @NathanDotTo The latest version (4.9) has fixes that should solve your issue. Can you guys update and confirm?

**Comment by GBrookman** [comment]
just downloaded 4.9 and the payload is populated now for Python requests. Thank you!

**Comment by soufian044** [comment]
Not for me , a made a gif animation to show what i have here , i will upload it later. 
I even tried removing and installing the extension

**Comment by sdnts** [comment]
@soufian044 Is this still reproducible?

**Comment by amriteya** [comment]
@madebysid I am having the same issue of body not being reproduced in Python's request code generation. I am using PostMan version : 4.8.3 and Mac OS X El Capitan (10.11.6).


Has the fix for this been already delivered? I am not facing this issue in Chrome application only in Mac app.


Here are the screenshots for the same.

<img width="1131" alt="request" src="https://cloud.githubusercontent.com/assets/4987564/20979853/47280b0c-bcd4-11e6-8228-9695345051cc.png">

<img width="1125" alt="code-snippet" src="https://cloud.githubusercontent.com/assets/4987564/20979874/5579a738-bcd4-11e6-966d-6acb8c1db015.png">

**Comment by sdnts** [comment]
@amriteyapandey A fix for this was released with 4.9.0. Could you try updating and checking if it works for you?

**Comment by soufian044** [comment]
@madebysid could you guys make sure the problem is fixed before you close the issue ? 

this is the gif animation I told you last time , and the problem is still exist http://g.recordit.co/1zcOqojrTy.gif

**Comment by amriteya** [comment]
@madebysid I updated to 4.9.1 and it is working for me.

@soufian044 In 4.9.1 Java's OkHTTP client is also working and Python's http.client is also working.

**Comment by Komencanto** [comment]
Currently in native desktop version 4.9.2 the issue persists.

![capture](https://cloud.githubusercontent.com/assets/10437726/22229257/7eee6a8c-e18b-11e6-9d44-dd3e28b5e5d1.PNG)

![capture2](https://cloud.githubusercontent.com/assets/10437726/22229303/b5ef2698-e18b-11e6-9187-330a2a66a018.PNG)

OS: Windows 10 Home 

Let me know if I can upload any additional information to help resolve the isue.

**Comment by sdnts** [comment]
@HaydenStanko Looks like you're on the Chrome app. Nevertheless, this is very weird because I can generate the correct code using the Chrome App & the native app for form-data & urlencoded bodies on my end :(
Can you open up the Chrome App's DevTools ([Instructions](http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/)) to check if you find any errors there? A screenshot, if you find something, would be helpful.

**Comment by alecemckinley** [comment]
I am using: 4.9.2, linux / x86-64, Chrome 56.0.2924.76 and can confirm that the problem still persists 
![postman_screenshot1](https://cloud.githubusercontent.com/assets/10871587/22627171/aeadaa08-eb8b-11e6-8c5f-3666c88bca5e.jpg)
![postman_screenshot2](https://cloud.githubusercontent.com/assets/10871587/22627172/aeb19668-eb8b-11e6-993c-852e440e1903.jpg)

**Comment by sdnts** [comment]
@alecemckinley Im pretty sure I misunderstood, but I can see the urlencoded parameters in the `payload` variable on line 7. Is this not what you expect?

**Comment by DirtyJerz** [comment]
Generate code only works for cURL
cURL:
![image](https://cloud.githubusercontent.com/assets/896643/23073839/c5167798-f504-11e6-9c99-128d4666d17b.png)


Python:
![image](https://cloud.githubusercontent.com/assets/896643/23073791/9c4dd748-f504-11e6-8c0a-b706114b84d3.png)


Disable then re-enable of a parameter by way of checkbox adds key but not value to payload:
![image](https://cloud.githubusercontent.com/assets/896643/23073976/4fc0bebc-f505-11e6-8d9a-d8fb701c90c2.png)

console is quiet throughout session.

About:
Postman for Chrome
Version 4.10.2
win / x86-64
Chrome 56.0.2924.87

**Comment by gavinr** [comment]
I am having same issue as @DirtyJerz above.

```
Postman for Chrome
Version 4.10.2
win / x86-32
Chrome 56.0.2924.87
```

**Comment by ramsaymax** [comment]
I'm also having the same issue, what is causing this?

Python requests code gen, in the chrome app

**Comment by soufian044** [comment]
1 year and 1 month and the bug still persists
![image](https://cloud.githubusercontent.com/assets/10144036/25066583/32943286-222a-11e7-9b4f-6f4afb970cef.png)

**Comment by affect** [comment]
I believe I'm getting the same issue.

.post(null)

Version 5.0.2
win7 / x86-64
Chrome 59.0.3071.115

is this fixed?

**Comment by bugmeout** [comment]
```
Postman for Chrome
Version 5.0.2
OS X / x86-64
Chrome 59.0.3071.115
```

>  Except the raw-http request ,other languages to genearate code snippets still set body payload 
 to `payload = ""`  by default.

bug still not be fixed. 

> the trick way to solve this is to `click body section 'bulk edit' ,  re-edit it again` ,everything seems to be right! 

HOPE YOU  GUYS CAN FIXED IT!

**Comment by loskael** [comment]
```
Version 5.1.3
OS X / x86-64
Chrome 60.0.3112.101
```
bug still not be fixed.

> let me tell you how to go around this bug until it's fixed , try bulk edit and then add space and remove it , and try again to generate the code , only then it will generate the full code

when i `bulk edit` it, the item will be right, but the others still wrong.

**Comment by chucktestar** [comment]
```
Postman for Chrome
Version 5.2.0
win / x86-64
Chrome 60.0.3112.113
```
I can confirm this is still present in 5.2.0. @soufian044's [workaround](https://github.com/postmanlabs/postman-app-support/issues/1850#issuecomment-261722907) is still effective as well.

**Comment by jelle-art** [comment]
Still present...

**Comment by a85** [comment]
I can't replicate the issue. Screenshots below:

![screenshot 2017-12-20 11 12 47](https://user-images.githubusercontent.com/653409/34224165-c645ade2-e576-11e7-8016-2ef4a631af5e.png)
![screenshot 2017-12-20 11 12 34](https://user-images.githubusercontent.com/653409/34224166-c65e3600-e576-11e7-967d-a9419d7c9d56.png)

**Comment by XuluWarrior** [comment]
I have just seen this bug.  I'm running Postman v5.5.0 on Windows 7.
I will see if I can reproduce it without sensitive details and post screenshots.

Also, when I click Send on the same request, the form values aren't sent.

**Comment by XuluWarrior** [comment]
Opening and closing Bulk Edit mode as suggested by bulkmeout fixes the issue with the generated code for that request but doesn't fix the Send action.

Opening Bulk Edit mode, making a white space change and deleting, and then closing Bulk Edit mode also fixes the Send action.

**Comment by XuluWarrior** [comment]
I wonder if this bug is related to syncing of requests across devices.  My problematic request was creating in the Chrome App via the Interceptor but didn't work when synced with the native app.

**Comment by XuluWarrior** [comment]
Interceptor does seem to be part of the problem.  I just replicated the issue doing the following

- Enable Interceptor addon
- Enable Interceptor sync in Postman addon
- Enable Sync API request across devices in both Postman addon and native app
- Send a POST request using https://resttesttest.com/
  - METHOD: POST
  - Endpoint: https://httpbin.org/post
  - Parameter Name: testparam
  - Parameter Value: testvalue
- Open the Postman addon History and select the POST request
- Save the request
- Send the request (Notice that the params appear in the response body)
- Open same request in Postman native app
- Send the request (Notice that the form data is empty in the response body)

**Comment by soufian044** [comment]
I confirm what @XuluWarrior said about the interceptor,  you can't reproduce the issue if you create the request manually, the problem appears when you try to generate the code for the intercepted requests using the chrome extensions.

**Comment by frankcastro** [comment]
I am on Mac OS 10.12.6 running Postman 5.5.0. I am having the same issue.  I have a simple GET request, and when I generate the curl code, it always includes -d POST body.  I realized what was happening what that I had saved this GET from an original POST request.  Even though it's now a GET, and you can't access the Body, it still has a body saved.  So just change the GET to a POST, click on Body and delete the body.  Hope this helps.

**Comment by cjangrist** [comment]
+1 if I edit, only my edits are added to request payload. Otherwise it's just empty.

true for me ==> the problem appears when you try to generate the code for the intercepted requests using the chrome extensions.

**Comment by bart-blommaerts** [comment]
Still buggy on 5.3.2 on OS X (Sierra). Bulk edit, adding a space, sending the POST and clicking code afterwards is a functional workaround.

**Comment by tolotrasamuel** [comment]
Problem still persist. Postman for Chrome
Version 5.5.3
win / x86-64
Chrome 67.0.3396.99

**Comment by colingoodale** [comment]
Hi I'm on Windows 10 and this still persists with no clear solutions.

**Comment by cassdeckard** [comment]
+1
