### ISSUE TITLE
Collection Runner freezes if the Folder that is attempted to be executed has changed name AFTER collection runner is started

### ISSUE THREAD

**Issue by mstaalesen** [a85/POSTMan-Chrome-Extension#1851]
1. Start the collection runner from a collection by first selecting the Folder and then "Run".
2. Ensure that said folder is selected in the collection runner and that the correct environment is set
3. Start the collection runner and observer that everything is working as it should.
4. Keep the collection runner open
5. Rename the folder that collection runner just ran
6. Select the new folder in the collection runner
7. Execute the tests again and observe that the Collection Runner window freezes.

The collection runner has to be reopened for it to work again, and it works just fine when attempting to run the tests in the folder that was renamed in step 4. This is reproduceable each time.

Error message from Dev Tools (runner.js:81004):
`Uncaught TypeError: Cannot read property 'length' of undefined
getRequestsInFolder @ runner.js:81004
start @ runner.js:75955
startTestRunWithModel @ runner.js:76930
(anonymous function) @ runner.js:104993
updateParamsWithDataFileAndStartRun @ runner.js:76862
handleStartTest @ runner.js:104980
handleClick @ runner.js:21215
invokeGuardedCallback @ runner.js:4288
executeDispatch @ runner.js:4133
executeDispatchesInOrder @ runner.js:4156
executeDispatchesAndRelease @ runner.js:3588
executeDispatchesAndReleaseTopLevel @ runner.js:3599
forEachAccumulated @ runner.js:4430
EventPluginHub.processEventQueue @ runner.js:3804
runEventQueueInBatch @ runner.js:4459
ReactEventEmitterMixin.handleTopLevel @ runner.js:4475
handleTopLevelWithoutPath @ runner.js:14645
handleTopLevelImpl @ runner.js:14625
Mixin.perform @ runner.js:6619
ReactDefaultBatchingStrategy.batchedUpdates @ runner.js:10639
batchedUpdates @ runner.js:6127
ReactEventListener.dispatchEvent @ runner.js:14756`

Postman v4.0.5 (Ubuntu)

**Comment by SamvelRaja** [comment]
Hey, @mstaalesen i tried reproducing the same in my latest 4.4.1 app, i couldn't able to reproduce the same. I attached the gif of my flow. Let me know if i misses something
![runner-freeze](https://cloud.githubusercontent.com/assets/5114052/16408912/993e9b34-3d38-11e6-8ba9-bf00c5dd5342.gif)

**Comment by sdnts** [comment]
@mstaalesen Can you still reproduce this issue? Feel free to reopen if you are :)

**Comment by mstaalesen** [comment]
Sorry, didn't see this. This seems to have been fixed.
