### ISSUE TITLE
OAuth 2.0 settings not saved in Version 4.0.5

### ISSUE THREAD

**Issue by RonakThakkar** [a85/POSTMan-Chrome-Extension#1852]
Hi,

I am using Postman version 4.0.5

I am calling API using OAuth 2.0 Authorization code Grant Type.

I have selected Type = "OAuth 2.0", enter necessary information like Auth URL, Access Token URL, ClientID, Client Secret and clicked on "Request Token". This gets me token which I use to send API request. Everything works fine.

Next time when I open Postman again and click on "OAuth 2.0" again in dropdown, I find that the information that I entered above is lost.

**Comment by SamvelRaja** [comment]
Hi @RonakThakkar thanks for taking this to our notice. The RC had been found. Will be out in the next version update.

**Comment by alvinchandra** [comment]
Hi @SamvelRaja, i had the same problem with Oauth1 in Postman version 4.0.5. I'm waiting for the next postman update. Big thank's.

**Comment by SamvelRaja** [comment]
@RonakThakkar and @alvinchandra yeah the fix is on it's way. But till that will tell you a dirty trick to access your saved tokens. Just toggle the radio buttons under the PREVIOUSLY USED list column in **OAUTH2** editor, the saved tokens gets visible there now.

**Comment by SamvelRaja** [comment]
@RonakThakkar and @alvinchandra the fix is live in the version `4.1.0` kindly update the version to check it.

**Comment by RonakThakkar** [comment]
Thanks for fixing that.
