### ISSUE TITLE
OAuth2 id_token in Authorization header 4.0.2

### ISSUE THREAD

**Issue by joshboley** [a85/POSTMan-Chrome-Extension#1854]
When my team uses the OAuth2 flow to get a token, our oauth provider return both an access_token and and id_token.  As of version 3.2.20, the id_token would show up in the Postman UI and we could select it and add it to an environment variable easily that would be passed in the Authorization header.  On Friday, some team members were auto-upgraded to 4.0.2.  After this upgrade, the only options we have in the UI are to add the token to the header or add the token to the URL.  This issue with this is that we need the id_token added to the header, but Postman seems to only support adding the access_token to the header.  Therefore, the only way for us to use Postman with oauth2 is to use the dev tools to inspect the returned request and copy and paste the id_token into the header and/or an environment variable.  So, am I missing some feature that would allow us to do this without using dev tools or was this feature removed at some point along the way? If it was removed, it would be nice to have a third radio button that would allow you to see the tokens returned without using dev tools.  Here's a screenshot of how it looked in 3.2.20 when a token was returned.  Thanks so much.

![capture](https://cloud.githubusercontent.com/assets/5840836/13746945/34f5f02e-e9cc-11e5-916a-c4b45467543b.PNG)

**Comment by Wanaco** [comment]
I agree!
This is very frustrating...
Is it in the dev team radar?

**Comment by mel111** [comment]
stoppp sending this crap !!!!!!!!!!!!!!!!!!!!!

**Comment by abhijitkane** [comment]
Yes, @Wanaco, we're working on a fix for this and will try to push it out soon.

**Comment by abhijitkane** [comment]
@Wanaco @joshboley We've pushed updates to the OAuth2 flow in the latest version (4.4.1) that should fix this.

**Comment by dpovey** [comment]
I am currently using Postman 4.10.5 I get a correct id_token but I cannot seem to add it to the request. It only gives me a "Use Token" button when I click on the retrieved token. This will only allow access to the authorization token and not the id_token.

**Comment by lemtzas** [comment]
Version 4.10.7 here. Same issue.

**Comment by Dismissile** [comment]
@abhijitkane This was addressed over a year ago and doesn't seem to be fixed. Are you guys still planning on fixing this?

**Comment by sdnts** [comment]
@Dismissile We're planning on major auth improvements in the near term, this will be a part of that. You can follow our product [roadmap](https://trello.com/b/4N7PnHAz/postman-roadmap-for-developers) for consistent updates :)

In any case, I'll let you guys know here when a fix lands on stable.

**Comment by Dismissile** [comment]
Is it possible to access the token using a Pre-Request script? It’s a huge pain to have to copy the value directly.

**Comment by sdnts** [comment]
@Dismissile If you save the token to an environment variable, you can access it in the pre-request and test scripts.

**Comment by sergey-netdev** [comment]
@madebysid, can you please describe how we do that in "Get New Access Token" dialog?

**Comment by sergey-netdev** [comment]
Any updates on this?

**Comment by htowens** [comment]
I’m also facing challenges with this issue - the Oauth2 authorization option is correctly retrieving both ID and access tokens from AWS Cognito, but I don’t have any option to choose which is used to authenticate, which means constant “unauthorized” errors.

Any updates on a fix? Any workarounds in the interim (assuming we can’t control the tokens returned by the endpoint)?

**Comment by JohnBloom** [comment]
Same problem for me using AWS Cognito. It would be nice if there was a setting somewhere to allow me to indicate what token to use. Currently I have to copy the id token out of the payload and switch the auth to bearer token and paste it in. This is frustrating because it doesnt support the refresh token so I can only use the endpoint for an hour before I have to go through the auth again to get a new token.

**Comment by harryi3t** [comment]
Duplicate of https://github.com/postmanlabs/postman-app-support/issues/492

**Comment by BartusZak** [comment]
Any update?

**Comment by hlubovac** [comment]
This problem is back, evident with v7.16.1

**Comment by payitforwardnow** [comment]
Is there a resolution to this issue? I was hoping to use PostMan for automated testing; however, given the fact that the issue with trying to use id_token has been around for literally YEARS I have to conclude that this might not be the best tool for my company to continue using.

**Comment by fvalmeida** [comment]
The comments in the issue (#6987) clarified some concepts for me, Postman seems to do the right thing:

**Comment by paran0i4** [comment]
Follow up?
