### ISSUE TITLE
Unable to download the test runs from collection runner

### ISSUE THREAD

**Issue by srbangre** [a85/POSTMan-Chrome-Extension#1855]
When i try to download the test runs from collection runner on chrome app for windows, it downloads the whole collection.json file. How do i just download the test runs?? 
app version - 4.0.5
chrome version - 48.0.2564.116

**Comment by sdnts** [comment]
@srbangre You can download a test run using the runner sidebar on the left :)
![screenshot 2016-10-18 17 22 28](https://cloud.githubusercontent.com/assets/7689783/19476567/86e326cc-9557-11e6-8fa1-1f67c5576ad7.png)
