### ISSUE TITLE
4.0.5: Enter isn't sending the request

### ISSUE THREAD

**Issue by ghost** [a85/POSTMan-Chrome-Extension#1856]
I think it would be useful if we can execute the request pressing Enter in the URL, params, headers, etc.

**Comment by uda** [comment]
It was working in pre-v4, why the change?

**Comment by xasx** [comment]
Apparently, `Ctrl+Enter` works here. 

Good enough for me. Consistent with other tools I use, like IntelliJ IDEA (e.g. commit dialog).

**Comment by ajsager** [comment]
I agree, this is already a very missed feature.  Not sure why the keystroke was changed.  Enter is not being used for anything else I can see, so I don't see the need to change this to Ctrl/Cmd+Enter.  Just Enter was so much more natural.

**Comment by ghost** [comment]
The shortcuts list confirms the CTRL+Enter to send the requests. I am good with that.

**Comment by uda** [comment]
+1 but a changes popup for something so fundamental would be nice...

**Comment by ajsager** [comment]
@maxihornes I don't have a problem with the documentation.  I just don't know why they changed the functionality.  The Enter key was not re-purposed to some other action.  It now just does nothing.  There may be a very good reason for the change, but I just can't figure out what it was.

**Comment by xasx** [comment]
Perhaps a requirement from the Chrome framework?

I just remember that the Quit keystroke there is not bound to Ctrl+Q -- probably not only but also because OWA has occupied this binding to mark messages as read -- would be very uncomfortable to close the browser instead.

**Comment by aditikul** [comment]
Hi! Totally understand your concerns. The main issue we faced was that Enter did not work consistently as a shortcut for sending a request. It could not be used to send request if you are editing the pre-request script or tests or doing bulk edit, and would have got in the way when we try to bring in more inline editing functionality in the future. Ctrl/Cmd+Enter made it more consistent. We will definitely ensure that we communicate changes like this better next time.

**Comment by ajsager** [comment]
Thanks @aditikul.  That makes total sense.  I have not utilized the pre-request/tests sections yet, so I had no other reason to ever hit Enter while in Postman other than to send the request.  I appreciate your response, and now that I know the reason behind the change, it makes me feel better about having to hold Ctrl/Cmd while pressing Enter.

**Comment by uda** [comment]
Thanks @aditikul, I agree, before when auto completing a header and hitting enter, it would send the request...

**Comment by aditikul** [comment]
Just an update that now if you are in the URL field and press Enter, the shortcut will work. However if you are anywhere else in the UI then Cmd+Enter is the way to go.
