### ISSUE TITLE
Keyboard shortcut for "close tab"

### ISSUE THREAD

**Issue by otolabqu** [a85/POSTMan-Chrome-Extension#1857]
It seems not to exist as it is now (not listed in settings-shortcuts).

Also, postman behavior is inconsistent with browser behavior: CTRL-T opens a new tab in postman as expected, but CTRL-W closes postman completely, it should just close the current tab.

**Comment by a85** [comment]
This is implemented properly in the Mac app. We can't control the Ctrl+W shortcut on Chrome until the underlying platform gives us access.

**Comment by maurymarkowitz** [comment]
As vegetableman notes above, I suggest the opposite - as a long-time Mac user I found the behaviour of Command-W in Postman very strange. Perhaps what we need is a third command, "close tab or window" that you could bind for those people that want that behaviour.
