### ISSUE TITLE
Globals canot be imported in the app

### ISSUE THREAD

**Issue by didiermichel** [a85/POSTMan-Chrome-Extension#1859]

**Comment by Ekusu1** [comment]
I just wrote a comment on an other issue with a workaround which you could use
Here is the link: https://github.com/postmanlabs/postman-app-support/issues/19#issuecomment-199256066

Should have checked the issues before posting it there... ^^

**Comment by abhijitkane** [comment]
@didiermichel Tracking at https://github.com/postmanlabs/postman-app-support/issues/2155
Will be pushing a fix in the next release.
