### ISSUE TITLE
Feature Request: Report HTTP 302 Redirects

### ISSUE THREAD

**Issue by mikecorcoran** [a85/POSTMan-Chrome-Extension#186]
Hello,

Great tool!  I'll use it often, however, the one feature I was looking for in a HTTP testing tool isn't available :-).

I'm debugging a webapp that uses HTTP Redirects as an active part of the API.  HTTP headers (most notably the actual Location header) contains information relevant to the API, and not the actual content of the resource that we were redirected to.  Currently, if I issue a GET request to http://somewhere/outthere and receive a 302 redirect, Postman will automatically re-issue a request based on the Location header without showing you the value of the new Location.

So, I'm looking for a feature that would allow me to see the actual HTTP 302 Redirect response from the server (including all the headers).  This could be as simple as a "Max number of redirects" setting that I could, for example, set to 0 causing Postman to show the 302 redirect response as-is.  Or, the feature could be the ability to view each individual request and response that occurred as a result of my initial GET request.

Thanks,
Mike.

**Comment by rcrisp** [comment]
+1

**Comment by CharlesWall** [comment]
+1 I need this too

**Comment by abhijitkane** [comment]
@dhergert @rcrisp @CharlesWall 
In the latest versions of the Postman packaged app, you can choose to enable/disable redirects. (Settings > General >Automatically follow redirects). Note that the Interceptor will need to be installed for this to work.

**Comment by dhergert** [comment]
Cool, I had just installed the Interceptor too (which was easy).  I'll give it a try. Thanks!

**Comment by derekgreer** [comment]
Why does there have to be some proxy server involved?  I just want to see the redirect response.  Seems like this should be easy enough.

**Comment by abhijitkane** [comment]
@derekgreer Postman uses Chrome's XHR API to make requests. This does not let us view the 301/302 response. The response available to us is the final response only.

**Comment by samuraitruong** [comment]
The proxy doesn't solve my problem too because I need to capture the OAuth redirect to get token and set it into postman variable. 
Note: I don't have control on server side to capture that token

**Comment by duilio92** [comment]
A quick fix I used to see the 302 redirect is the following:

* Get the code of the request with the cURL option
* Add the **--head** option to that command

When running it from the command line, you will see the 302 redirect that occurred.
