### ISSUE TITLE
My synced postman collections are gone locally and on the site 

### ISSUE THREAD

**Issue by andy-g** [a85/POSTMan-Chrome-Extension#1861]
I was using the Postman Team Sync Beta while the program was in Beta, and all my collections where in there and syncing to the postman cloud.

I realise that the beta program is closed now, so wasn't expecting team sync to work any longer, but I opened the app yesterday and the layout was a bit broken and all  my history and collections were gone.

![image](https://cloud.githubusercontent.com/assets/557065/13770022/da2b1842-ea8c-11e5-88f8-af32aaebd634.png)

I wasn't too phased, I expected they'd all still be online, but after logging into my profile, it's also been reset, all my collections are gone and they've just been replaced with a `Postman Echo` collection.

![image](https://cloud.githubusercontent.com/assets/557065/13770080/40ba4132-ea8d-11e5-97d3-f078d47e73a0.png)

How can I go about recovering my collections, is this due to the team sync decommissioning, or te new collections format, either way, surely my collections should have been left intact?

Please let me know how I can go about recovering my collections & environment variables.

**Comment by abhijitkane** [comment]
@andy-g There's probably an issue with the latest Chrome release that's preventing the app from loading properly. As for your collections and environment, they're still there but not visible on the website. You will need to migrate to Postman Cloud (using the migrate email you should have received earlier) to continue accessing your collections in the main Postman app (https://chrome.google.com/webstore/detail/postman-rest-client-packa/fhbjgbiflinjbdggehcddcbncdddomop?hl=en)

**Comment by andy-g** [comment]
Thanks for the quick response @abhijitkane.

I've upgraded by account to postman cloud (30 day trial), but I don't have any of my collections there. Tried to log in to the site and the app, but even once it's `IN SYNC` there are no collections there.

I'm happy to lose access to other team members collections that were shared with me, but I just want to recover my collections. How can I simply recover my collections?

**Comment by sobtiankit** [comment]
@andy-g Can you send an email to help@getpostman.com from your registered email id on the beta, with your beta and production user ids? I'll restore the data for you.

**Comment by andy-g** [comment]
Thanks @sobtiankit,

I've just sent that mail, please let me know if you need anything else from me.

**Comment by andy-g** [comment]
Thanks so much @sobtiankit. I thought there were quite a few more collections but the ones I'm really interested in are there at least. Thanks for the assistance, I really appreciate it.
