### ISSUE TITLE
Set environment combobox is too small to fit content

### ISSUE THREAD

**Issue by fkranenburg** [a85/POSTMan-Chrome-Extension#1862]
I have a lot of environments to select and some have a bit long name. In previous versions of Postman this was never an issue. But now I have to check the current environment manually by clicking on the combobox and select the environment I need of the list.
1. But there is no indication of the current selected environment in the dropdown list
2. The current selected environment combobox is just too small.

See attached screenshot. Which environment did I select?

![postman environment](https://cloud.githubusercontent.com/assets/5680394/13770201/bca432b0-ea85-11e5-9bf4-de25f704378a.jpg)

**Comment by a85** [comment]
Yep. Understand the issue @fkranenburg. Will get back to you with more details here.

**Comment by SamvelRaja** [comment]
@fkranenburg we have added the tooltip which shows the environment name without clipping in out latest `4.1.0` version. can you update and let us know your experience.

**Comment by fkranenburg** [comment]
Yes, many thanks it works great now. Thank you for the fast fix!
