### ISSUE TITLE
Bulk edit is missing in postman version 4.0.5

### ISSUE THREAD

**Issue by timotiusericks** [a85/POSTMan-Chrome-Extension#1863]
In previous version there is bulk edit in POST body form-data

![screen shot 2016-03-15 at 2 25 48 pm](https://cloud.githubusercontent.com/assets/14273203/13770503/0d0648c2-eaba-11e5-807f-03dd33bfb12a.png)

But, in version 4.0.5, I can't find bulk edit button in form-data

**Comment by abhijitkane** [comment]
@timotiusericks There were a few issues with the way files were handled in the bulk-edit window, so we've removed it for now. We're working on a fix for this, and will try to reinstate it soon.

**Comment by a85** [comment]
It's back!
