### ISSUE TITLE
Font-Size and menu color hack for 4.0.5

### ISSUE THREAD

**Issue by zorker** [a85/POSTMan-Chrome-Extension#1865]
The font size was way to tiny for me before but now with 4.0.5 it is bonkers. You guys hardcoded the font-size per element? Additionally you picked a grey menu font-color on a grey menu.

Had to hack postman via **Chrome inspect App** to fix it
chrome://inspect/#apps

```
html * {
  font-size:100% !important;
}

.collection-sidebar-list-item__request__meta,
.collection-sidebar-list-item__head__requests {
  color:#09f;
}
```

Any way we can write our own themes?

**Comment by a85** [comment]
Can you share the following?
1. Is this the Chrome app or the Mac app?
2. Your screen resolution.

We test on a wide variety of platforms and screens but not possible to test for everything.

**Comment by zorker** [comment]
I use an iMac 27" (~from 2010). On the iMac runs Windows7 via Bootstrap. The app is inside Chrome. My screen resolution is 2560x1440. My Windows display size multiplier is set to 125%.

I will add two screenshots to give you an idea. The one with the grey menu font is the default view. The other one is with my added stylesheet.

http://imgur.com/a/Sn1Fk

My final CSS hack is:

```
html * {
  font-size:100% !important;
}

.collection-sidebar-list-item__request__meta,
.collection-sidebar-list-item__head__requests {
  color:#09f;
}

.collection-sidebar-list-item__head {
  /*background-color:#eee;*/
}

.collection-sidebar-list-item__head.is-hovered {
  background-color:#ffe;
}

.collection-sidebar-list-item__body {
  background:#fafafa;
}

.collection-sidebar-list-item__folder {
    /*border-bottom:1px solid #ddd;*/
}

.collection-sidebar-list-item__body > .collection-sidebar-list-item__folder:last-child {
    border-bottom:0;
}

.collection-sidebar-list-item__folder__head {
    border-bottom:1px solid #eee;
}

.collection-sidebar-list-item__request {
  border-bottom:1px solid #eee;
  background:#fff;     
}

.collection-sidebar-list-item__request.is-selected.is-active {
  background-color:#0af;
}
```

I really do not understand why the app is not written with rem or em sizes. This would give you the opportunity to add a font resizer directly in the app and scale everything from the root font size.

Pixel values are ok for websites where you can enhance the font-size manually via CTRL + mousewheel. You cannot do that in the chrome app for whatever reason. That would solve the problem aswell.

**Comment by a85** [comment]
@zorker You can now zoom in/out of the UI. Shortcuts here:

<img width="701" alt="screenshot 2016-09-10 14 04 34" src="https://cloud.githubusercontent.com/assets/653409/18413558/1b4d72ec-7760-11e6-9bd2-5782f2dd87a7.png">
