### ISSUE TITLE
4.06 still have issues my our collection

### ISSUE THREAD

**Issue by Fr4ncis** [a85/POSTMan-Chrome-Extension#1866]
Hi there, postman has been broken since v4 and we cannot use it. **Can you please make sure you test with our collection**? I provided to support the keys and secrets to test it yourself.

This time it seems that "Authorization > OAuth 1.0 > Add params to header" still adds the params to the body.

V3 of postman works fine.

Collection URL: https://www.getpostman.com/collections/fc13d501598107a36184

**Comment by abhijitkane** [comment]
@Fr4ncis Can you check what version of Postman you're on? I'm not able to reproduce this.

**Comment by Fr4ncis** [comment]
@abhijitkane 4.0.6 try the POST requests, it seems that GET requests work fine. ON postman v3 they all work fine.

**Comment by abhijitkane** [comment]
Works even for POST requests (the signature is added to the header if 'Add params to headers' is set).

Can you check for any errors in the console - http://blog.getpostman.com/2015/06/13/debugging-postman-requests/?

**Comment by Fr4ncis** [comment]
@abhijitkane  In the devtools console everything is fine as it is not reported as an error, calling POST /user/checkemail on our system just replies with 401 
"{
  "error": 3,
  "description": "OAuth details invalid"
}"

it works fine on Postman v3 as stated (right now I have two postmans open, one as mac app v4.0.6 and one as chrome ext v3.x) 

I checked on "Add params to header" and parameters are still on the body. If I call  POST /user/checkemail and remove from the body the parameter "email" "fmattia@rmn.com" then it seems that the OAuth signature is validated but of course the parameter is missing from the request so our server replies with 400 (Bad request):

{
  "description": "Missing parameters"
}

**Comment by Fr4ncis** [comment]
@abhijitkane screenshots at http://we.tl/o2o75cgwLk

**Comment by abhijitkane** [comment]
@Fr4ncis can you confirm if this is sill happening in the latest version? We made a number of fixes to the OAuth1 flow.
