### ISSUE TITLE
Tests with dynamic name marked as failing and passed at the same time?

### ISSUE THREAD

**Issue by Winawer** [a85/POSTMan-Chrome-Extension#1867]
We're running a series of tests on an internal API using the collection runner and a CSV file and a number of the tests are coming back marked as 'fail', but they're marked as passed in the overall report and in the summary of the number of tests beside each entry (see image attached).  

We're almost certain that this is because we were debugging the test itself using a dynamic value in the test name (i.e. test["score: " + response_data.score + " " + data.expected_score] = response_data.score === data.expected_score).  This generates as many entries for the test in the summary as there are data point in the CSV file (i.e. the last 10 lines in the pasted image are all the "score: " test).  When we take that dynamic aspect out of the test name, the names collapse into one entry and they're all marked as passing, just as the last line in the pasted image is.  

![screen shot 2016-03-15 at 11 31 44 2](https://cloud.githubusercontent.com/assets/768583/13781857/b3519ebe-eabc-11e5-95d1-c66f4999765d.png)

**Comment by abhijitkane** [comment]
@Winawer Can you mention what version of the app you're using, and if it's the Chrome app or the Mac app?

**Comment by Winawer** [comment]
Postman for Mac, v4.0.6 (at least in the Check for Updates dialog ... the About dialog still says 4.0.5, which might be a separate bug. :)

**Comment by numaanashraf** [comment]
@Winawer Would it be possible to share screenshots of the version disparity between Check for Updates & About dialog?

**Comment by Winawer** [comment]
@numaanashraf Sure! Taken a few seconds after each other:

<img width="307" alt="version-1" src="https://cloud.githubusercontent.com/assets/768583/13792242/d3864faa-eae8-11e5-87d6-e4bbadf21b23.png">
<img width="491" alt="version-2" src="https://cloud.githubusercontent.com/assets/768583/13792241/d3863fb0-eae8-11e5-9019-67a621e23cb6.png">

**Comment by abhijitkane** [comment]
@Winawer Thanks for reporting this.
As you suspected, the issue was the dynamic test name. If the dynamic names are `score1`, and `score2`, the first one show up as "pass" initially, but changes to "fail" as soon as the 2nd request completes. 
We've made a fix, and will be pushing it out soon. The status will be "fail" iff at least one instance of that test has failed.

**Comment by abhijitkane** [comment]
@Winawer This has been fixed in the latest version - 4.1.2.
