### ISSUE TITLE
Export is changing collection folders sorting

### ISSUE THREAD

**Issue by emmanuel-umana** [a85/POSTMan-Chrome-Extension#1868]
Today I got an update of Postman, the app looks good, but it has a problem that is affecting the way we use it.

The folders in our collection are sorted by name, and we need to export the collection exactly in the same sorting. On this new version, when I export the folders, they have a different order, causing us a lot of errors when running the exported collection with Newman due to new sorting.

Could you help us to solve this???

**Comment by abhijitkane** [comment]
@emmanuel-umana Thanks for reporting this. We'll be pushing a fix for this ASAP.

**Comment by emmanuel-umana** [comment]
@abhijitkane Thanks! Is there a way to downgrade while this bug is solved? 
We really need to export our collection sorted by folders name.

**Comment by SamvelRaja** [comment]
@emmanuel-umana we have released a our latest `4.1.0` version which has the fix for it. Kindly, can you update and check the same.

**Comment by emmanuel-umana** [comment]
@SamvelRaja Exc! thanks!  I just checked and I found its updated to that version, will check and will let you know. Thanks!

**Comment by emmanuel-umana** [comment]
Exc!!!! thank you!!! just in time for one important relase! we really need that one! :-)
