### ISSUE TITLE
Collection Runner Getting Stuck on Initialization 

### ISSUE THREAD

**Issue by xankwondo** [a85/POSTMan-Chrome-Extension#1870]
I have been trying to run my collection with a csv file but the collection does not run, it just gets stuck in the initialization sequence, have restarted computer and tried ~10 times over the last hour (including different csv files). Nothing has appeared in the statistics view either.  

The collection ran successfully before the recent update but this is the first that I've tried it since. 

 4.0.2
( win / x86-32 )
( Chrome 49.0.2623.87 )

**Comment by abhijitkane** [comment]
@xankwondo Can you try upgrading to the latest version - chrome:/extensions, enable 'Developer Mode', click 'Update extensions now'.

If that doesn't help - try checking the console - http://blog.getpostman.com/2015/06/13/debugging-postman-requests/
