### ISSUE TITLE
4.0.5 Language detection set JSON,bug not work

### ISSUE THREAD

**Issue by followztx** [a85/POSTMan-Chrome-Extension#1871]
4.0.5 Language detection set JSON,bug not work.
early version work.

upgrade from early version to 4.0.5, when i change "Language detection",it become not work

**Comment by SamvelRaja** [comment]
@followztx Thanks for reporting to us. It had been fixed in our internal build, will be out in the next version.

**Comment by SamvelRaja** [comment]
@followztx The build is out with as `4.1.0` update can you update your chrome app and check the same.
