### ISSUE TITLE
Selecting Items from Collection in new tab reverts back to open tab from history

### ISSUE THREAD

**Issue by brianpowell** [a85/POSTMan-Chrome-Extension#1873]
*_Issue: *_ You cannot open more than one "Collection" item instance at a time (unless you open multiple windows). Anytime you select a Collection item from the menu with a new tab open, the app just selects the an existing tab with that Collection Item (even if modified) and does not populate the request in the new tab. 

**In Past:** In the Chrome App, you could open multiple instances of Collection items and it was great...  A Single instance of any collection item makes me want to go back to the Chrome App. Very hard to test with only one Collection item instance and even more impossible to run controlled CRUD operations across multiple tabs.

**Recreation:**
- Select collection item (modify it, but does not make a difference)
- open new tab
- Select same collection item
  >> Just reverts back to tab that has the Collection item... Why does it not populate the Collection item into the tab I was on and wanted the request in?

**Comment by abhijitkane** [comment]
@brianpowell We've changed this behaviour in the latest release (4.1.3). Can you confirm?

**Comment by brianpowell** [comment]
I can confirm that this is fixed in 4.1.3 - Thank you!
