### ISSUE TITLE
Wrong time of request

### ISSUE THREAD

**Issue by prih** [a85/POSTMan-Chrome-Extension#1875]
if you make a request with the body (like POST with raw data), and the tab "Body" will be opened at the time of the request - the request is a distortion of time shows 5 times longer, 
![image](https://cloud.githubusercontent.com/assets/3285877/13827502/7abbdbbe-ebc5-11e5-9024-d8238376275c.png)

but if the request to open a tab, such as "Headers", time request becomes correct.
![image](https://cloud.githubusercontent.com/assets/3285877/13827489/7062d4ce-ebc5-11e5-9607-c5203be0ca70.png)

**Comment by numaanashraf** [comment]
@prih Could you let us know your app version? You can find it under _Settings > About_

**Comment by prih** [comment]
@numaanashraf 
4.0.4
( win / x86-32 )
( Chrome 48.0.2564.116 )

**Comment by abhijitkane** [comment]
@prih  Can you check if this is fixed in the latest version?
