### ISSUE TITLE
collections folder

### ISSUE THREAD

**Issue by tonycody** [a85/POSTMan-Chrome-Extension#1876]
When multiple child folder, can have a better level.
Can support to create a more level folder?
![qq 20160317160019](https://cloud.githubusercontent.com/assets/6773121/13839852/69bc593a-ec59-11e5-8caa-b763932aa1e9.jpg)

**Comment by abhijitkane** [comment]
@tonycody This is planned, but there's no timeframe yet.

**Comment by abhijitkane** [comment]
Closing as duplicate of https://github.com/postmanlabs/postman-app-support/issues/907
