### ISSUE TITLE
chrome plugin auto update

### ISSUE THREAD

**Issue by tonycody** [a85/POSTMan-Chrome-Extension#1877]
why can't auto udpate??

always,uninstall. then reinstall.

**Comment by abhijitkane** [comment]
@tonycody Chrome's update process is a mystery to us too. To force an update, you can head to chrome://extensions, enable 'Developer Mode', and click 'Update extensions now'.

**Comment by tonycody** [comment]
Not updated,I'm tried!

**Comment by abhijitkane** [comment]
@tonycode What version are you on? 4.1.3 is the latest version.
