### ISSUE TITLE
Saved response replaces template URL with resolved one

### ISSUE THREAD

**Issue by mahendranv** [a85/POSTMan-Chrome-Extension#1878]
Say my url is
`{{BASE_URL}}/bookmarks/popular-websites`

After opening the saved response it resolved with the actual URL.
`http://mysite.com/bookmarks/popular-websites`

And my request marked as dirty. Accidentally saving this would make my template variable to be gone.

**Comment by abhijitkane** [comment]
@mahendranv We've changed this behaviour in the latest release (4.1.3) - opening a saved request will no longer replace the URL/headers/request body. Can you confirm?

**Comment by mahendranv** [comment]
Sorry for the delay.

It works fine. Thank you.

Regards,
Mahendran V
