### ISSUE TITLE
Testing - add library with RSA encryption and Hex encoding

### ISSUE THREAD

**Issue by mirszy** [a85/POSTMan-Chrome-Extension#1879]
I'd like to use Postman to test my authorization API. First request returns session id. Second request contains encoded sessionId and password. It would be great to have a possibility to do such encryption in pre-request script (e.g. to have access to library like jsencrypt), and encode it to hex.
Currently it's blocking me from using Postman to do my tests.

**Comment by abhijitkane** [comment]
@mirszy The sandbox includes CryptoJS (https://www.getpostman.com/docs/sandbox). Does this have the encryption/encoding functionality you need?

**Comment by mirszy** [comment]
@abhijitkane thanks for your response. Unfortunately I couldn't wait for Postman and I had to start testing my API using other methods. So I didn't have a chance to look closely at the CryptoJS, but it seems it would work. Maybe in some next project I'll check it out.
Thanks and sorry for the late response.

**Comment by qixiaobo** [comment]
> standard and secure cryptographic algorithms. Supported algorithms: AES, DES, EvpKDF, HMAC-MD5, HMAC-SHA1/3/256/512, MD5, PBKDF2, Rabbit, SHA1/3/224/256/512, TripleDES

sorry,no rsa

**Comment by kingwrcy** [comment]
+1,please support RSA  encrypt/decrypt/sign/verify。

**Comment by GuusK** [comment]
RSA signing and verification would be awesome
