### ISSUE TITLE
Issue posting a request with multpartfile

### ISSUE THREAD

**Issue by ghost** [a85/POSTMan-Chrome-Extension#1881]
I'm having an issue after a recent update.
A rest service which has as a parameter an array of multpartfile . When I submit is receiving as a unique file. No changes were made in server side code. And It was working quite well before this update. Help 

![request](https://cloud.githubusercontent.com/assets/4961663/13848542/1ad7685a-ec31-11e5-9685-d8f8532427b2.png)
![response](https://cloud.githubusercontent.com/assets/4961663/13848541/1ad3c02e-ec31-11e5-872a-159cc5b3286f.png)

**Comment by abhijitkane** [comment]
@igorchucky Can you check the Network tab in DevTools to verify the exact payload that was sent?
For the Chrome app, http://blog.getpostman.com/2015/06/13/debugging-postman-requests/
For the Mac app - Cmd+Option+I

**Comment by ghost** [comment]
@abhijitkane Sure. I've checked. It seems is not getting my array of files just getting a unique file. I've used the same request as shows in images sent . 2 files in request parameter file.  Take a look at the payload . Can you help me ?

![error_payload](https://cloud.githubusercontent.com/assets/4961663/13849229/fd2383b8-ec33-11e5-9898-f1a32fa09ce0.png)

**Comment by abhijitkane** [comment]
Got it. We'll be pushing a fix for this in the next release. Thanks for reporting this @igorchucky

**Comment by ghost** [comment]
Thanks @abhijitkane

**Comment by scholary-tim** [comment]
+1 thanks

**Comment by abhijitkane** [comment]
@igorchucky Can you confirm this working in 4.1.0?

**Comment by igorchucky** [comment]
I can confirm this on 21th march, next monday, ok ? As soon as I try this again and reply here for you

**Comment by powersu** [comment]
Before the 4.1.2 release, I had same issue.
I can confirm it's fixed now.

**Comment by ghost** [comment]
Thanks @powersu . I was really having some troubles with this bug. I thought it could be an error in my server side code, but it was not . Great!

**Comment by scholary-tim** [comment]
Hi @abhijitkane - when is 4.2.0 likely to be released? Many thanks for the fast turnaround on this one.

**Comment by scholary-tim** [comment]
Guys, any update on this please? This is a real problem for me at the moment. Many thanks.

**Comment by abhijitkane** [comment]
@tjdurden Are you using the Chrome app? If so, you can upgrade to 4.1.2 (chrome:/extensions > Developer Mode > Update)

**Comment by ghost** [comment]
@abhijitkane @tjdurden I'm using 4.1.2 now , and it's working again. Thanks. Issue solved.
