### ISSUE TITLE
v4.0.5 OAuth 2.0 Input Fields not preserved after closing and re-opening packaged app

### ISSUE THREAD

**Issue by joshboley** [a85/POSTMan-Chrome-Extension#1882]
I hate to log another issue, but noticed that after upgrading to 4.0.5, my OAuth 2.0 input fields get deleted if I close and re-open the packaged app.  Here are the fields I'm talking about:

![capture](https://cloud.githubusercontent.com/assets/5840836/13852511/ba3fade2-ec38-11e5-9007-fa8735ed3dff.PNG)

**Comment by SamvelRaja** [comment]
@joshboley we have released our latest version `4.1.0` which has the fix for it. Kindly can you confirm the same and close the issue?

**Comment by joshboley** [comment]
Yes, this seems to be working now.  However, I am having another issue that I logged here #1900
