### ISSUE TITLE
Requests not saving

### ISSUE THREAD

**Issue by ChrissiFi** [a85/POSTMan-Chrome-Extension#1883]
I've successfully saved 8 GET requests to a collection this afternoon but the 9th hasn't saved.  There's no indication on adding to collection that it hasn't saved but it's not showing in the collection.  Have closed the app and re-opened but no change.  Please advise asap.

**Comment by abhijitkane** [comment]
Can you check the console at http://blog.getpostman.com/2015/06/13/debugging-postman-requests/ for any errors? 
What happens if you open a new tab and try to save that request?

**Comment by ChrissiFi** [comment]
I've tried new tabs and re-opening the app and creating the request from new.  Not familiar with the developer tools but assume top item is latest. I'm getting:
beforeunload is not available in packaged apps.
window.localStorage is not available in packaged apps. Use chrome.storage.local instead.

**Comment by ChrissiFi** [comment]
Cleared logs and tried again - nothing in developer tools this time but still not saving.

**Comment by abhijitkane** [comment]
What version of the app are you using? You should be able to find this in Settings (icon in the top-right) > About.

**Comment by ChrissiFi** [comment]
3.2.20  Been using it about a week and fine until now.  Haven't tried reboot yet - will be closing down in 10.

**Comment by ChrissiFi** [comment]
This is working this morning.
