### ISSUE TITLE
Certificate based authentication support

### ISSUE THREAD

**Issue by matthieugeerebaert** [a85/POSTMan-Chrome-Extension#1884]
We have a legacy ws gateway, offering basic or certificate based authentication. We would be pleased to use the runner in that last context, as we do with soap-ui.

**Comment by daecabhir** [comment]
:+1: I would like to add a few details to my experience with client certificate authentication:
- If I connect to a web service that requires two-way SSL authentication using Postman (2.0 or 3.0) first, I will get a "Could not get any response" error, and no prompt for an SSL certificate
- If I connect to the same web service from a plain Chrome tab first, I will get prompted for the certificate, and be allowed to connect.  If I think connect to that web service using Postman, requests are handled normally.

These are with signed and trusted certificates on the server and in the browser. It would be nice to be able to have Postman detect the situation, and have Chrome prompt for a client SSL certificate.

**Comment by RichardFoo** [comment]
FYI, I've separately filed an [enhancement request](https://github.com/postmanlabs/postman-app-support/issues/1938) for generally better feedback on SSL failures, but client certificates was not something I considered.

**Comment by sdnts** [comment]
Guys, Postman has had support for Client certificate authentication for a while. Could you check out the latest version (4.8.3) and see if this is still an issue? Docs are [here](https://www.getpostman.com/docs/working_with_client_certificates)

**Comment by daecabhir** [comment]
Although this fits the general requirement, it would be _really helpful_ to have Postman accept PKCS#12 files (e.g., .p12) or PEM files that contain both the certificate and private key. Particularly in a more "corporate" environment with enterprise-managed PKI, this is how we tend to receive certificates - not as separate certificate and key files. This actually makes it easier to manage the certs, and eliminates the need to export the certificate and key to separate files.

If this needs a separate enhancement request or additional details / clarification, please holler.

**Comment by sdnts** [comment]
@daecabhir I've gone ahead and created a new feature request #2494 for PFX / P12 for your use case, and will update it accordingly.

Closing this issue as this is resolved. Feel free to reopen if any problems persist.

**Comment by matthieugeerebaert** [comment]
Hello, sorry for the delay, I have just tested it for a real case, it works
great.

Thank you very much

2016-11-25 11:50 GMT+01:00 Siddhant Sinha <notifications@github.com>:
