### ISSUE TITLE
How to generate postman collection through an api ?

### ISSUE THREAD

**Issue by matthieugeerebaert** [a85/POSTMan-Chrome-Extension#1886]
We would like to integrate a postman collection generator, swagger as input parameter, for our service, thus our users can retrieve a nice package, with everything they need to start working on API.

**Comment by czardoz** [comment]
@Treabereeg I've answered your question at #1885 

In short, you can use this: https://github.com/postmanlabs/swagger2-to-postman :smile:

**Comment by a85** [comment]
@Treabereeg Also, we'd love to talk to you about how you are using Swagger and Postman together. We are trying to make this integration better. Let us know if you are interested at help@getpostman.com

**Comment by matthieugeerebaert** [comment]
Great, I should have listed postman project first :)

As we are working on an API Designer ( yes another one ) we want to offer a nice ui integration and a ready to go package to start or speed up realization.

We re just starting with this workflow swagger -> postman, I think we will expose it as "micro service". We worked a lot more by creating collection by hand, using runner and newman ( TM Forum & Orange ). Time to link design and test. We do not want to sync swagger -> postman, we just want a first generation to init the postman collection project, wich will be maintained by hand.

Bu we are also interested in request samples generation and a simple request editor / response check, per usecase ( just a response diff, not the full test feature with code ) for simple test, very easy to edit and play, without javascript knowledge.
