### ISSUE TITLE
Request with unresolvable domain hangs on "Loading..."

### ISSUE THREAD

**Issue by dabfleming** [a85/POSTMan-Chrome-Extension#1887]
I'm using the Chrome App, v4.1.0, on Chrome 48 on OSX.

Attempting to request URL `{{var-name}}/foo` when `var-name` is not set in the environment generates a net::ERR_NAME_NOT_RESOLVED error and the interface hangs on "Loading..." with no indication of what has happened.

I recall that in a recent previous version an error message was displayed that made it easy to realize the variable was not being replaced and correct.

![image](https://cloud.githubusercontent.com/assets/3885717/13884360/02baca86-ed04-11e5-92da-28463cee4b2f.png)

**Comment by abhijitkane** [comment]
@dabfleming Thanks for reporting this. Seems to be an issue with the Interceptor. We'll push a fix for this soon.

**Comment by abhijitkane** [comment]
@dabfleming Can you confirm this fixed in the latest version of the app / interceptor (v4.4.1 / V0.2.18)?
