### ISSUE TITLE
Collection Runner Interface goes crazy

### ISSUE THREAD

**Issue by coolidm** [a85/POSTMan-Chrome-Extension#1888]
When running a collection it appears that after each result is appended to the results pane, the pane gets wider. With larger collections it becomes so wide its no longer reasonable to scroll.  

See the scroll bar at the bottom
![image](https://cloud.githubusercontent.com/assets/16841160/13889144/5c3f5592-ed1b-11e5-890a-466e0cd4f0ff.png)

Version:
4.0.5
( win / x86-32 )
( Chrome 49.0.2623.87 )

**Comment by SamvelRaja** [comment]
@coolidm  we had fixed this in our latest release can you update the app and check the same?

**Comment by coolidm** [comment]
I just checked and it is better but still not resolved. It seems to be impacted by long URL strings.

**Comment by SamvelRaja** [comment]
@coolidm it seems it is working fine in our end. Can you give us a sample Screen shot with the URL?

**Comment by coolidm** [comment]
![postman2](https://cloud.githubusercontent.com/assets/16841160/13950976/80bf7eba-f004-11e5-973d-d5d65cbee606.PNG)
![postman](https://cloud.githubusercontent.com/assets/16841160/13950975/80bd46f4-f004-11e5-8957-25b018c4c71a.PNG)

I can't share the full URL, but the length is around 2,700 characters (I know that's huge). See the screenshots, specifically the scroll bar at the bottom.

**Comment by SamvelRaja** [comment]
@coolidm Thanks for the SS, it helps alot. You will get the fix in the next version.

**Comment by SamvelRaja** [comment]
@coolidm  Can you check the same from your end.. This had been fixed in the latest version
