### ISSUE TITLE
Feature request: Make it possible to select existing Collection/Folder with arrowkeys when saving a request

### ISSUE THREAD

**Issue by mstaalesen** [a85/POSTMan-Chrome-Extension#1889]
As of 4.1.0 it is not possible to use the arrow keys to select the existing Collection or folder that I want to save the request too. Adding this feature would increase my productivity.

![animation](https://cloud.githubusercontent.com/assets/14194793/13894108/d6b026d2-ed64-11e5-804b-fd1563ca652f.gif)

Also, after selecting the Folder (or Collection), the dropdown menu does not disappear. (I have to click outside of the dropdown box for it to dissappear). And if it would be possible to hit Enter to Save that would also be nice.

**Comment by aditikul** [comment]
Thanks for reporting this! This should be fixed in the next update. Arrow keys will now work for the collection selector.

**Comment by oi-io** [comment]
So is it not in 4.1.3 yet?
