### ISSUE TITLE
Oauth 2.0 could not complete login with error "Can't open same-window link..."

### ISSUE THREAD

**Issue by tuantmdev** [a85/POSTMan-Chrome-Extension#1891]
I got this message (in Console of Developer Tool) when request oauth 2.0 token. Any idea to fix this?

I'm using Postman 4.1.2. This is what i'm sending to get token.

```
Auth URL: https://id.mog.net/auth
Access Token URL: https://id.mog.net/api/v1/token
Client ID: 1004293137466914469965
Client Secret: ddRPO1pXB3e3h16T8A6sSUeBIriB6v7yo9cLi8QMsp5aMtXK
Scope: basic
```

**Comment by numaanashraf** [comment]
@tuantmdev Could you let us know your Chrome and Postman app versions and also include a screenshot of the console error, if possible?

**Comment by tuantmdev** [comment]
I'm using Chrome version 49.0.2623.87 (64-bit) on Mac OSX 10.11.3, Postman version 4.1.2. I can not reproduce this bug today but it's still error

![Imgur](http://i.imgur.com/fXHC2hU.png)

**Comment by abhijitkane** [comment]
@tuantmdev Can you provide a sample set of credentials to us at help@getpostman.com so we can try to debug this?

**Comment by tuantmdev** [comment]
Please check your inbox

**Comment by abhijitkane** [comment]
@tuantmdev Confirmed as resolved. Closing issue.
