### ISSUE TITLE
Interceptor crashes constantly

### ISSUE THREAD

**Issue by aquitania99** [a85/POSTMan-Chrome-Extension#1892]
Hi guys!

First of all let me say that I love this tool it's awesome!
However since the last update I've been having many dramas with interceptor. 
Everytime I activate it to run a request to one of the endpoints that need authentication, interceptor crashes and freezes the whole postman. I've tried reinstalling Chrome, Postman, Interceptor and even installed the Postman app for mac, but no luck so far.

My current setup:
Postman version 4.1.2
OS X / x86-64
Chrome 49.0.2623.87

Any ideas about what can I do to get it working again?

Thanks in advance.

Best Regards,

Sergio.

**Comment by abhijitkane** [comment]
@aquitania99 Can you share authentication details (not the actual key/secret, but the helper name/other settings etc)?

**Comment by a85** [comment]
@aquitania99 We are unable to replicate this. I'd suggest moving to the Postman Mac app which doesn't use the Interceptor if you are working with cookies. Closing this until we have further steps to replicate.
