### ISSUE TITLE
Regression: Ability to URL encode parameters (#158)

### ISSUE THREAD

**Issue by turchinc** [a85/POSTMan-Chrome-Extension#1893]
Since apparently I cannot re-open issues, I am creating a new one. 

Ability to encode URL Parameters was created with #158 

Now this option is missing. 

The funny thing is the code generated e.g. for node.js is correct:

```
var http = require("http");
var options = {
"method": "GET",
"hostname": "xxx.xxx.xxx.xxx",
"port": null,
"path": "/mc/rs/entityprofile/7923?hello=%7B%22oasdf%22%3A%22asdf%22%7D",
"headers": {
"cache-control": "no-cache",
"postman-token": "2c2148bc-69be-4942-2373-132db5166d8d"
}
};
var req = http.request(options, function (res) {
var chunks = [];
res.on("data", function (chunk) {
chunks.push(chunk);
});
res.on("end", function () {
var body = Buffer.concat(chunks);
console.log(body.toString());
});
});
req.end();
```

**Comment by numaanashraf** [comment]
@turchinc We are working on this and the option to encode URI via context menus will be added in the coming releases.

**Comment by turchinc** [comment]
please add it back soon. like I said, it was already a feature since #158 and my development depends on it.

**Comment by turchinc** [comment]
this feature is back in my current build

4.1.3
win / x86-32
Chrome 49.0.2623.110

Thanks

**Comment by nickdbush** [comment]
Am I missing something or is there no option to do this in 4.1.3? It would be great if I can as it save so much time when working with services like Parse! Thanks

**Comment by chadsaun** [comment]
It would be fantastic to save all my parameters as url decoded, and then have Postman automatically url encode them.  That way it's easier for me to read the values and play with them.
