### ISSUE TITLE
OAuth 1.0 secret key variables are not reflected/saved after closing and opening the request in v4.1.2

### ISSUE THREAD

**Issue by praveenps071** [a85/POSTMan-Chrome-Extension#1894]
I have parametrized the secret key variable in "manage environment" section and same parameter name is used while sending API request, but after closing and opening the request i'm not able to see the parameter name under the request. this is causing me to enter the variable name for each and every request. This is becoming tedious job. Please address this issue ASAP

Note: After entering the parameters in the OAuth 1.0 field if I open another request in another tab, i'm not able to see the parameters name in the another request. So every time for new API request i had to enter parameter names. This is very very irritating job.

![image](https://cloud.githubusercontent.com/assets/17981825/13917389/53bb701e-ef86-11e5-870d-6b1fc15c279f.png)

**Comment by SamvelRaja** [comment]
@praveenps071 Yeah, this will be fixed in next version of the app.

**Comment by abhijitkane** [comment]
@praveenps071 Can you confirm this fixed in 4.1.3?

**Comment by praveenps071** [comment]
Issue is fixed and it is working as expected. The values are reflecting even after closing and opening the request.
