### ISSUE TITLE
Critical blocker: body text area does not respond correctly to text input/delete

### ISSUE THREAD

**Issue by billpaetzke** [a85/POSTMan-Chrome-Extension#1895]
The ability to write anything or delete anything in the body text area is unpredictable. If the cursor is in one place, the inserted or deleted text character will be somewhere else random. It only applies to body text area. The url text box works fine. My only workaround is to edit my json body in another text editor and copy paste into postman. See before and after image of me trying to delete the last character of an IP address value; it instead deletes the first character. 

Body text area with "raw" and JSON (application/json) seleted for an HTTP POST:
![postman-1](https://cloud.githubusercontent.com/assets/1972564/13921394/e1f5cfd4-ef34-11e5-9645-0ab3773c2e55.PNG)
![postman-2](https://cloud.githubusercontent.com/assets/1972564/13921395/e4752016-ef34-11e5-980c-b0f3279d9123.PNG)

Was ok on Postman 4.0.4 and below--Chrome app for Windows 8.1. Problem started with Postman 4.0.5 and continues through Postman 4.1.2 Chrome app for Windows 8.1.

**Comment by numaanashraf** [comment]
@billpaetzke That's odd. Does it occur every time you try to edit the raw body?

**Comment by numaanashraf** [comment]
@billpaetzke We are unable to replicate this on Postman 4.1.2/Chrome 48/Win 8.1. Would it be possible to check the console and send us a screenshot of any errors there? Steps to access console are detailed [here](http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/).

**Comment by billpaetzke** [comment]
Yes happens every time. I'll check the console...

**Comment by billpaetzke** [comment]
Errors happen upon load of Postman. No errors happen while I insert/delete text in the body text area.

3x: extensions::platformApp:17 window.localStorage is not available in packaged apps. Use chrome.storage.local instead.(anonymous function) @ extensions::platformApp:17
1x: extensions::platformApp:17 beforeunload is not available in packaged apps.

![postman-console-errors](https://cloud.githubusercontent.com/assets/1972564/13922501/d52d2e1e-ef39-11e5-8abe-b9d51235205f.PNG)

**Comment by numaanashraf** [comment]
Thanks @billpaetzke. Those startup warnings are expected. Could you let us know your Chrome version also?

**Comment by billpaetzke** [comment]
4.1.2
win / x86-32
Chrome 49.0.2623.87

What do you advise? I would like to continue using Postman but not sure what else I can do here.

**Comment by a85** [comment]
Can you share a screen recording? @billpaetzke

**Comment by billpaetzke** [comment]
Ok so you want me to record and post a few seconds of the failure to insert and delete characters correctly, is that right?

**Comment by a85** [comment]
Yes. That'll help a lot.

**Comment by billpaetzke** [comment]
Is there a free screen recorder that you recommend for Chrome or Windows?

**Comment by billpaetzke** [comment]
https://www.dropbox.com/s/ccllljo19qys1vs/Untitled%20Screencast.webm?dl=0

I write a line of text and try to delete a word in the middle of the line. I try to insert text at the end of the line. Notice that cursor position quickly moves ahead of where it should be and it totally off.

Here's a pic of the end:
![postman-screenshot-end](https://cloud.githubusercontent.com/assets/1972564/13924715/919cddf8-ef42-11e5-846a-fa0deb19aab6.PNG)

I did the screenshot in body = text, but the same happens for body = application/json.

**Comment by numaanashraf** [comment]
@billpaetzke Thanks for the screen capture. Is the same issue happening in the Pre-request Script or Tests editor also?

**Comment by billpaetzke** [comment]
Yes

**Comment by numaanashraf** [comment]
@billpaetzke Alright, we have a hunch on whats happening now. Could you run the following script inside the console and let us know what it prints? Almost there! :)

```
window.getComputedStyle(document.getElementsByClassName('ace_editor')[0])['font-family']
```

**Comment by billpaetzke** [comment]
window.getComputedStyle(document.getElementsByClassName('ace_editor')[0])['font-family']
"Monaco, Menlo, 'Ubuntu Mono', Consolas, source-code-pro, monospace"

**Comment by billpaetzke** [comment]
Seems like I don't have any of those fonts on my machine. Just checked in Microsoft Outlook while composing an email.

**Comment by abhijitkane** [comment]
@billpaetzke Can you try installing Monaco and Menlo? You'll probably need to restart the app and/or Chrome after installing:
https://github.com/hbin/top-programming-fonts/raw/master/Menlo-Regular.ttf
https://github.com/todylu/monaco.ttf/raw/master/monaco.ttf

**Comment by billpaetzke** [comment]
Ok, guys, we have a winner! It works now after installing Menlo.

So the problem was that my machine did not have your list of expected fonts. Solution: install one of the expected fonts.

I'm assuming that Consolas was your Windows font? I see that people are having issues with that font in Windows 8.1. (That would include me). But I never would have guessed this in a million years. Perhaps include another font for your Windows users that you know 100% will be there. https://www.google.com/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=windows%208.1%20consolas%20font%20missing

**Comment by abhijitkane** [comment]
Right..now that we've isolated the issue, we'll probably end up bundling one of these fonts with the app itself. The component we're using for the text editor only supports monospace fonts.
Thanks for reporting this.
