### ISSUE TITLE
No interpolation in cURL code for x-www-form-urlencoded parameters?

### ISSUE THREAD

**Issue by thirtified** [a85/POSTMan-Chrome-Extension#1896]
Seems that variables don't get expanded when creating cURL code from a x-www-form-urlencoded form. Here is an example of the generated output:

```
curl -X POST -H "Content-Type: application/x-www-form-urlencoded" \
     -d 'grant_type=client_credentials&email={{user_email}}' \
     "https://api.."
```

Tested on a Mac with v4.1.0 (native) and v4.1.2 (Chrome).

**Comment by abhijitkane** [comment]
@thirtified Thanks for reporting this. We've fixed this in our internal build, and will push the fix in the next release.

**Comment by abhijitkane** [comment]
@thirtified Can you confirm this fixed in the latest release?

**Comment by thirtified** [comment]
@abhijitkane Confirmed to work on 4.1.1 (Mac) and 4.1.3 (Chrome) – thanks!
