### ISSUE TITLE
Re-import collection

### ISSUE THREAD

**Issue by Pavel910** [a85/POSTMan-Chrome-Extension#1897]
This is a feature request. Would be great to have a `re-import` action on collections that were imported from URL. We have an automated API documentation for Postman and it is always located on the same URL,  and as we develop our platform the API docs change, and simply clicking re-import would save a lot of clicking and typing.

If not that, at least have Postman remember the last URL that was used to import a collection.

**Comment by a85** [comment]
This is much more complicated to implement and manage over time than it looks. We suggest using the team library feature to collaborate with others or just re-importing from the URL.
