### ISSUE TITLE
OAuth 1 params missing in "Generate code"

### ISSUE THREAD

**Issue by Schweigi** [a85/POSTMan-Chrome-Extension#1898]
When using the "Generate code" feature of v4.1 the OAuth 1 parameters are only copied to the "HTTP" snippet but not to all other snippets (e.g. "cCurl").

Steps:
1. Add "Authorization" => "OAuth 1.0" parameters
2. Go to "Body" => "x-www-form-urlencoded" (the OAuth params should be visible)
3. Click "Generate Code"

Expected:
If e.g. the cCurl snippet is selected then the OAuth1 parameters should be inside the snippet.

**Comment by abhijitkane** [comment]
@Schweigi Can you attach a screenshot of this? Unless the OAuth1 signature has been added to the URL/headers/body, it should not show up in the snippet.

**Comment by Schweigi** [comment]
@abhijitkane 

The OAuth1 signature appears in the body. I attached you some screenshots:

Authorization:
![authenticate](https://cloud.githubusercontent.com/assets/1357884/13935315/0419b7ee-ef74-11e5-9b2a-87e40095fd3d.png)

Request Body - Fields got automatically added when clicking "Update Request" in Authorization screen:
![request body](https://cloud.githubusercontent.com/assets/1357884/13935322/0b5c8824-ef74-11e5-8f62-d3075b4417a1.png)

Now when clicking "Generate Code" the OAuth parameters are visible for the HTTP snippet:
![screen shot 2016-03-21 at 2 51 35 pm](https://cloud.githubusercontent.com/assets/1357884/13935446/92613df6-ef74-11e5-88e4-596cb714c58e.png)

But not for all other snippets like cCurl or Python-Requests:
![screen shot 2016-03-21 at 2 51 50 pm](https://cloud.githubusercontent.com/assets/1357884/13935458/9fd8bc16-ef74-11e5-8851-8889eb004b18.png)
![screen shot 2016-03-21 at 2 51 58 pm](https://cloud.githubusercontent.com/assets/1357884/13935461/a1fb7dd0-ef74-11e5-893f-76e4c286b763.png)

**Comment by abhijitkane** [comment]
@Schweigi Got it. We'll be fixing this in the next release.

**Comment by abhijitkane** [comment]
@Schweigi Can you confirm this fixed in the latest release?

**Comment by Schweigi** [comment]
@abhijitkane It works. Thx a lot!
