### ISSUE TITLE
Enhancement Request: make Generate Code Snippet Type Selection Sticky

### ISSUE THREAD

**Issue by thirtified** [a85/POSTMan-Chrome-Extension#1899]
Would be great if Postman could remember the selected type/language on the Generate Code dialog. As of now (tested on Mac v4.1.0 native and v4.1.2 Chrome) the Generate Code Snippet dialog always starts with showing "HTTP", regardless of what has been selected before. Since I am pretty much always look for the cURL code, I always have to change the selection after opening the dialog.

As an alternative you could make the default type/language selectable in the preferences.

Thanks!

**Comment by mstaalesen** [comment]
+1

**Comment by thirtified** [comment]
Seems to be working, thanks!

(Tested on 4.2.0 on Mac)
