### ISSUE TITLE
import/export environments

### ISSUE THREAD

**Issue by vamsu** [a85/POSTMan-Chrome-Extension#19]
It would be nice if we can import/export environments along with collections.

And also I think global variables that can be used across environments will be very useful.

BTW.. Awesome work, good job!!

**Comment by giannisok** [comment]
export of globals is supported....but not import of globals...
Thanks for the great work anyway!

**Comment by didiermichel** [comment]
That's sad Globals canot be imported.

**Comment by Ekusu1** [comment]
Importing globals would be great, but for now you could use some regex, as a workaround, to create the "bulk"-format which you can then paste in the bulk edit mode
1. remove every line that's not necessary:  
   `^[\t\[\]\{\},\n]*("(type|enabled)": .*\n)?`  ->  ` ` (nothing)
2. get the key-value-pairs:  
   `"key": "(.*)",\n"value": "(.*)",\n`  ->  `$1: $2\n`

Those would convert

``` json
[
    {
        "key": "var1",
        "value": "val1",
        "type": "text",
        "enabled": true
    },
    {
        "key": "var2",
        "value": "",
        "type": "text",
        "enabled": true
    }
]
```

to

```
var1: val1
var2: 

```
