### ISSUE TITLE
4.1.2 - OAuth2 Call Back Url is blank?

### ISSUE THREAD

**Issue by joshboley** [a85/POSTMan-Chrome-Extension#1900]
I opened Postman this morning and my OAuth 2 callback url is blank.  It seems to say that I can set it from the app settings page, but I can't find it anywhere.  Any advice?   Thanks.

![capture](https://cloud.githubusercontent.com/assets/5840836/13933959/04dc8672-ef86-11e5-8c3c-973b7ff17be9.PNG)

**Comment by a85** [comment]
That's weird. Probably a font issue. You should see this: https://www.dropbox.com/s/ez9b1kvl6lz684m/Screenshot%202016-03-22%2010.13.42.png?dl=0

**Comment by abhijitkane** [comment]
@joshboley Can you also check the console for any errors - http://blog.getpostman.com/2015/06/13/debugging-postman-requests/ ?

**Comment by SamvelRaja** [comment]
@joshboley We had found a RC for this, fix will be out in the next version.

**Comment by joshboley** [comment]
If you found a fix, awesome! To answer the other questions...I don't think it would be a font issue because the network tab in dev tools never shows a request being sent.  Also, here's a screenshot of the errors.  They happen when I first open Postman though and seem to be unrelated.  Thanks guys!

![capture](https://cloud.githubusercontent.com/assets/5840836/13952706/314b1e8e-f00e-11e5-8762-ac40cd06b19a.PNG)

**Comment by SamvelRaja** [comment]
@joshboley yes it is a different issue.

**Comment by SamvelRaja** [comment]
@joshboley Can you update the app and check the same from your end. The fix went in on our `4.1.3` itself.
