### ISSUE TITLE
Make return/enter close tab with unsaved data

### ISSUE THREAD

**Issue by NRaf** [a85/POSTMan-Chrome-Extension#1901]
When closing a tab with unsaved data I get a confirm dialog. Pressing enter to accept the dialog does nothing, instead I have to use the mouse. When closing multiple tabs in quick succession this gets a bit tedious.

**Comment by mstaalesen** [comment]
+1

**Comment by aditikul** [comment]
We've added a bunch of shortcuts so you can discard changes, cancel, or save changes when you get that modal. Should be pushed out soon. Stay tuned!

**Comment by vegetableman** [comment]
@NRaf The issue has been fixed on recent versions of the app. Closing this, feel free to reopen if the issue still exists ^_^.
