### ISSUE TITLE
Add "Quick edit" button for currently selected environment

### ISSUE THREAD

**Issue by Shimmi** [a85/POSTMan-Chrome-Extension#1902]
Hi there,
First of all, great work on Postman! Thanks!

I would really appreciate a button next to "View current environment" (The one that shows current environment variables) allowing to edit the current environment.

**Little background**
As I have approx 20 different environments setted-up and as I need to update them somehow often (eg changing variables like User ID) It is starting to be uncomfortable as I have to select Manage environments > find the correct one and then edit it. It would not save such a significant amount of time but think this little amount of code change would bring a big UX improvement on this.

Thank you,
Jiri

**Comment by ghost** [comment]
I think it would be great to have shortcut for it too.

**Comment by RichardFoo** [comment]
+1.  For Globals too.
Perhaps, hyperlink the title of each section (Environment name; Globals), or add an "[Edit]" next to the title lines that opens the right variable editor.

**Comment by a85** [comment]
Edit buttons for environments and globals are available now in the Quicklook view.

**Comment by Shimmi** [comment]
It is awesome! Thank you and the team behind Postman.
