### ISSUE TITLE
pre-request Same key in request.data

### ISSUE THREAD

**Issue by owentin** [a85/POSTMan-Chrome-Extension#1903]
Hi, I followed a post from [stackoverflow](http://stackoverflow.com/questions/12756688/is-it-possible-to-send-an-array-with-the-postman-chrome-extension?answertab=votes#tab-top) to send an array data, and I need to get the data from request.data in pre-request.
But I always get last value with request.data['my_array[]'], how can I get all array data?
Thanks

**Comment by abhijitkane** [comment]
@owentin This is currently a limitation of the app - `request.data` is a JS object, and cannot have more than one value for a property. We're working on changing this so that `request.data['my_array[]']` returns an array.

**Comment by owentin** [comment]
Got it and thanks for quick response.

**Comment by abhijitkane** [comment]
@owentin Can you check the latest version of the app (4.1.3)?

If you have two keys (both named myarray), request.data.myarray will be an array in the prerequest script.

**Comment by owentin** [comment]
@abhijitkane sorry for late reply,
I have tried with version 4.2.1, and it works with myarray[], but not with myarray itself, and the value is like value-1,value-2,
thanks

**Comment by abhijitkane** [comment]
@owentin For a request like the one in the screenshot, `request.data.myarray = ['v1','v2'];`. Are you not seeing this behavior?
![screen shot 2016-05-24 at 14 17 51](https://cloud.githubusercontent.com/assets/681190/15497856/645be3ac-21ba-11e6-8aa2-2232548d4229.png)

**Comment by owentin** [comment]
@abhijitkane sorry, I think I made a mistake, I can get correct value with request.data.myarray and request.data["myarray"],
Thanks
