### ISSUE TITLE
Resizable Request Body Space

### ISSUE THREAD

**Issue by chadcampbell** [a85/POSTMan-Chrome-Extension#1904]
Hello,

I have a feature request. When POSTing a request, I often use the "raw" option to fill out the body. By default, I can make it grow. However, I can't make it shrink. I think it would be useful to be able to have more control over the height of the body area. This would enable developers to see more of the response on a screen.

**Comment by latifrons** [comment]
Agreed! The request area occupies 3/4 on my 1366*768 screen. Each time I fire a request, I have not choice but scroll down the screen to see the results.

**Comment by aditikul** [comment]
Hi! Thanks for reporting this. Can you share screenshots of how this looks like for you? This is a known issue and we are looking into fixing this so that it works properly for all screen sizes and resolutions.

**Comment by chadcampbell** [comment]
@aditikul Sure thing. I've attached a screenshot of Postman after I've executed a request.  Please notice that area that has 

```
{
  "search":"*"
}
```

is as small as I can make it. I'd like to be able to make this area smaller. As you can see, I can't see any of the results of my request without having to scroll down on the window. This becomes very repetitive when you run the same request multiple times.
![postman](https://cloud.githubusercontent.com/assets/5507793/14206389/c6a79e4c-f7e0-11e5-8031-6bee65bfb47c.png)

**Comment by aditikul** [comment]
@chadcampbell Thanks for sharing the screenshot, it helps a lot. Makes sense and this should be fixed soon - you should be able to resize the request area for a smaller height. Stay tuned for updates.

**Comment by chadcampbell** [comment]
@aditikul - I just got an update for Postman on my machine. I noticed this change was in there. It looks great and works well. Thanks for tackling this!

**Comment by aditikul** [comment]
@chadcampbell  Good to know! Glad we could help :)
