### ISSUE TITLE
RAML 1.0 support

### ISSUE THREAD

**Issue by rauar** [a85/POSTMan-Chrome-Extension#1906]
RAML Version 1.0 (RC) has been released a couple of days ago.

**Comment by ElectroLutz** [comment]
Any news on this one?

**Comment by coltonlw** [comment]
+1

**Comment by a85** [comment]
Not yet. Busy with some other issues right now. Hope to have an update here soon.

**Comment by bruno-gelb** [comment]
+1

**Comment by iwex** [comment]
+1

**Comment by antroy** [comment]
+1

**Comment by HuiSou** [comment]
+1

**Comment by cosmolux** [comment]
+1

**Comment by Andrewdtc** [comment]
+1

**Comment by Andrewdtc** [comment]
+1

**Comment by jhaygood86** [comment]
+1

**Comment by arashbi** [comment]
+1

**Comment by stepanbokoc** [comment]
+1

**Comment by rickydutton** [comment]
👍

**Comment by W1R3D-Code** [comment]
+1

This isn't really a feature request is it? you can't claim to support RAML if 9 months after they release version 1.0 you don't support it. Especially when the workaround is to use another 3rd party tool to convert RAML 1.0 to Postman 2.0.

**Comment by comikem** [comment]
Please add support for 1.0.  Great features for reuse in the spec itself but the external tools are lagging badly on parsing and code gen.

**Comment by Kamil1** [comment]
+1

**Comment by jarad-yadallee** [comment]
+1

**Comment by martynas19942** [comment]
+1

**Comment by jenssaade** [comment]
+1

**Comment by frhd** [comment]
+1

**Comment by ghost** [comment]
+1

**Comment by robertmircea** [comment]
+1

**Comment by allanchiou** [comment]
+1

**Comment by ghost** [comment]
+1

**Comment by zolotokrylin** [comment]
+1 🔥

**Comment by ghost** [comment]
+1

**Comment by thoorp** [comment]
+1

**Comment by ducin** [comment]
+1

**Comment by daniil388** [comment]
+1

**Comment by ivanfoong** [comment]
+1

**Comment by PinoEire** [comment]
+1

**Comment by Birowsky** [comment]
well?

**Comment by Damaged-Organic** [comment]
C'mon, guys, it's been a year already. Please, assign somebody to support our sweet RAML 1.0 : )

P.S.: really, this is currently the only thing that stops my team from migrating to RAML (and dumping Swagger, apart from my own tastes, which are RAML by default), as protocol requires demonstration in Postman.

**Comment by jcoplonSE** [comment]
+1

**Comment by mseitner** [comment]
+1

**Comment by foyb** [comment]
+1

**Comment by cjlotz** [comment]
+1

**Comment by fitzy101** [comment]
+1

**Comment by cebor** [comment]
Funny that there are still people on github who post the "+1".

**Comment by ghost** [comment]
@cebor +1

**Comment by udev** [comment]
@cebor I think it's due to lack of an upvote/downvote system? I dunno... At any rate,

**+1**

**Comment by evgenysalnikov** [comment]
+1

**Comment by SandhyaBee** [comment]
+1

**Comment by yuranos** [comment]
+1

**Comment by henrikje** [comment]
+1

**Comment by agluquetc** [comment]
+1

**Comment by Tzaphkiel** [comment]
+1

**Comment by nomadesoft** [comment]
+1

**Comment by PinoEire** [comment]
+1

**Comment by joaogomes44033** [comment]
+1

**Comment by mazerte** [comment]
+1

**Comment by wizzy25** [comment]
+1

**Comment by bruno-gelb** [comment]
still nothing?

+1

**Comment by mgruner** [comment]
+1

**Comment by balazj** [comment]
+1

**Comment by mbuc82** [comment]
+1

**Comment by rfp** [comment]
+1

**Comment by UdoBretz** [comment]
+1

**Comment by rmihael** [comment]
Please, let's stop these "+1". There is "thumbs up" on the issue if you want to vote and "subscribe" if you want to track discussion.

**Comment by stepanbokoc** [comment]
Hi,
what is the plan with this feature? For long time this is one of most requested features but if I look into your [roadmap](https://trello.com/b/4N7PnHAz/postman-roadmap-for-developers) it's not even in 1-year planning board. I find RAML best API description language, but it's lack of tooling is making it hard to use compared to others :-(

**Comment by fg78nc** [comment]
I am surprised why official Postman documentation claims to support RAML 1.0, while it does not.
+1

**Comment by kanduvisla** [comment]
+1

**Comment by gmfc** [comment]
+1

**Comment by spaceageracer** [comment]
+1

**Comment by imhogan** [comment]
+1

**Comment by aasimsyed** [comment]
+1

**Comment by FreddieK** [comment]
+1

**Comment by ghost** [comment]
+1

**Comment by fireantology** [comment]
+1

**Comment by edshadi** [comment]
+1

**Comment by Uelii** [comment]
+1

**Comment by a85** [comment]
Everyone, this is part of a much larger initiative but we are introducing the ability to define APIs in Postman using schemas. You will be able to document schemas for both requests and responses using whatever format you typically use. Postman will then take this as another input in generating docs, building mocks, or adding tests. It looks like this: 

<img width="1552" alt="Screenshot 2019-04-30 14 02 13" src="https://user-images.githubusercontent.com/653409/56995066-8d635400-6b55-11e9-9720-0888d91e4e82.png">

Eventually, this will also allow you to link multiple collections to the same schema and reference individual schemas for each request inside a collection. We feel this is a much more scalable way to handle reusability issues. Essentially this is a kind of request inheritance but instead of doing this from one request in another collection, you'll be doing this through a schema. We will start with OpenAPI and RAML in the beginning but will be extending this to GraphQL and the Collections format itself.

We'd love your feedback!

**Comment by fabiocarvalho777** [comment]
@a85 are you serious?
Have you read what the hundreds of people commenting here are asking?
We want RAML 1.0 support!

The worse thing is, besides ignoring what your users want, you paste a screen shot here showing exactly what your product lacks (RAML 0.8 is there, but not 1.0), and make it sounds like this is a good announcement.

Oh, and then that `We'd love your feedback!`.
Unbelievable.

Postman Product Manager should be fired.

**Comment by a85** [comment]
@fabio I am not sure you read or understood what I am saying.

**Comment by a85** [comment]
@fabiocarvalho777 Also hasn't Mulesoft effectively deprecated RAML after they joined the OpenAPI foundation: https://blogs.mulesoft.com/dev/api-dev/open-api-raml-better-together/. I am not sure where Mulesoft's own support behind RAML is if they aim to support OpenAPI. I haven't seen any updates to RAML as a format over the last 2 years. 

Separately, we wouldn't tolerate incendiary comments like yours on the tracker and it can get you blocked from this repo.

**Comment by ullgren** [comment]
@a85 Just to be clear, in the now deleted, comment you linked to a Mulesoft blog post and had doubts about Mulesofts stands on the support for RAML. In that very blog post you linked Uri Said states 

> ... we are, and will continue to be, committed to supporting the RAML initiative ...

So I believe that is quite clear. Just as postman Mulesoft needs to support many different standards in it's product. 

Also please consider adding the support for RAML 1.0. :-)

**Comment by a85** [comment]
@ullgren I am sure they will continue supporting RAML (0.8 and 1.0) - but it could mean a lot of things - like updates to existing tools or customer support through help channels. I am not sure about future versions/updates to the spec because the blog post by Smartbear here declares victory: https://swagger.io/blog/news/mulesoft-joins-the-openapi-initiative/ and I am not sure if there will be a version 1.1 or version 2.0 for RAML.

**Comment by sarabsilveira** [comment]
It would be really good to import a RAML 1.0 spec to a collection. That's preventing Postman to be used for testing purposes.

**Comment by rsprenkels** [comment]
it has been over three years (!) now, that RAML 1.0 has been around. Postman team, are there plans to support RAML 1.0 at some point, and if yes, when?

**Comment by zthulj** [comment]
+1 ..

**Comment by mprice-mule** [comment]
Can someone confirm if (or when) Postman will fully support RAML 1.0?

**Comment by yearswriter** [comment]
+1 to RAML support, would be neat

**Comment by vanmanhvo** [comment]
Please support RAML 1.0 !

**Comment by VShingala** [comment]
Hello Everyone,

We have added support for importing RAML 1.0 definitions in Postman App v7.16.0. You can head over to Import in top left corner of App and select appropriate flow for importing.

This also includes support for importing API definition with multiple files having external file references using `!include` tags under Import Folder flow.

We've also open-sourced this converter at [raml1-to-postman](https://github.com/postmanlabs/raml1-to-postman). Feel free to give any feedback or report issues over there.

Thanks for the patience.

**Comment by jstoiko** [comment]
@VShingala: this is amazing, great news!

I see that there are some [important limitations](https://github.com/postmanlabs/raml1-to-postman/blob/master/README.md#notes) , specifically the lack of support for RAML Libraries, Overlays/Extensions and anything around inheritance including ResourceTypes and Traits. Those are major features that people use today with RAML so I am afraid that not supporting them may prevent a lot of people from using this plugin. Any plan on a full RAML 1.0 support?

On related note, I see that this plugin does not leverage RAML’s new official parser [`webapi-parser`](https://github.com/raml-org/webapi-parser) which fully supports both RAML 0.8 and 1.0, including all those currently unsupported features listed above, and which also happens to support OAS 2.0 (and now 3.0 as well). Let me know if we can help your team leverage this somehow.

**Comment by VShingala** [comment]
@jstoiko  Sorry for the confusion.

I have updated [README.md](https://github.com/postmanlabs/raml1-to-postman/tree/feature/readme-update) with your concerns. And `raml1-to-postman` module does have support for ResourceTypes and Traits.

As for the support for Libraries, Annotations  and Overlays/Extensions needs much work.

For now use of Includes may solve some use cases where Libraries might be needed. And we will explore `webapi-parser` as viable alternative to [raml-js-parser-2](https://github.com/raml-org/raml-js-parser-2) which is what's used now. 

Will let you know for sure if we need help regarding `webapi-parser`.

**Comment by VShingala** [comment]
RAML 1.0 support is available in App and as API itself. Feel free to report any issues or feature requests you have with conversion at [raml1-to-postman](https://github.com/postmanlabs/raml1-to-postman/).
