### ISSUE TITLE
Postman v4.1.2 stuck at "Sending"

### ISSUE THREAD

**Issue by ChrissiFi** [a85/POSTMan-Chrome-Extension#1909]
At approx 15:45 GMT Postman stopped working.  I'm running a series of tests against an OData API that have worked fine throughout the day but from this point they get as far as "being initialised" in the Runner and "Loading..." in the Builder but then hang.  I've restarted Postman, rebooted my laptop but still nothing's happening.  Urgent assistance is needed as I have a tight deadline.  

Postman updated to 4.1.2 this morning and I've not had problems with it hanging prior to this.  Please advise how I can resolve this - nothing different indicated in Chrome Developer tools.

Many thanks,
Christina

**Comment by ChrissiFi** [comment]
Working again now.

**Comment by abhijitkane** [comment]
@ChrissiFi Great! If you see this again, can you check http://blog.getpostman.com/2015/06/13/debugging-postman-requests/ for any errors?

**Comment by karjoh2525** [comment]
I am having the same issue.  Did it just START working for you?

**Comment by abhijitkane** [comment]
@karjoh2525 Is the Interceptor on? Do you see any errors in the console - http://blog.getpostman.com/2015/06/13/debugging-postman-requests/ ?

**Comment by ChrissiFi** [comment]
Karjoh2525, yes it came back with no intervention from my end - lost 1 1/2
hours productive time :(  The console showed that the get request had been
sent and that data had been retrieved so in theory the 'Loading' message
was erroneous.

**Comment by karjoh2525** [comment]
Thanks so much for your quick response.  In this case, it was my fault.  I did not have the correct ip address set in my host file.  I apologize, but I do appreciate this blog and the info shared!
