### ISSUE TITLE
Changing Toggle sidebar OS X shortcut

### ISSUE THREAD

**Issue by ghost** [a85/POSTMan-Chrome-Extension#1911]
Current Toggle Sidebar OS X shortcut is `Cmd + \`, which is used by default by OS X to show notification center. It would be better to have it on other shortcut, for instance `Cmd + [` - just removing `Shift` from switch to previous tab shortcut seems convenient.

**Comment by aditikul** [comment]
Hi! By default the shortcut cmd+\ for the notification center is turned off in OSX as far as I know so it shouldn't clash. We will look into this further, thanks for suggesting the change.

**Comment by ghost** [comment]
Hmm, you might be correct, though right now I turned off OS X Notification Center Shortcut in system preferences, unfortunately sidebar shortcut in Postman still have no effect.

**Comment by aditikul** [comment]
@danielpigan That's odd, this is working for me. Can you let me know which version you are on in Chrome app or Mac app?

**Comment by ghost** [comment]
Sure.
OS X version: 10.11.4 (15E65)
Postman Mac App version: 4.1.1; OS X 15.4.0 / x64

**Comment by aditikul** [comment]
@danielpigan Can you please check that the shortcut is working for you now? Thanks.

**Comment by ghost** [comment]
Sorry for delay. Shortcut is working fine in current version (4.9.3).
