### ISSUE TITLE
Re-adding active variables shortcut

### ISSUE THREAD

**Issue by ghost** [a85/POSTMan-Chrome-Extension#1912]
In pre-4 Postman versions there was `q` shortcut, which toggled popup with currently active variables, right now accessible by eye icon button right next to environment selection drop down menu. I edit variable values dynamically via tests and it would be great help to be able to check current variables values with shortcut.

**Comment by aditikul** [comment]
Thanks for reporting this! We will definitely add a shortcut for toggling the environment preview popover. Stay tuned for updates.

**Comment by bhawna2109** [comment]
Hey @danielpigan , we have an exciting update for you- postman now supports tooltips which let you view the current value of a variable, along with variable highlighting and autocomplete! It's out on our canary channel, and will hit our stable builds in March.

Latest Canary builds are available here-
OSX: https://dl.pstmn.io/download/channel/canary/osx_64
Windows 32-bit: https://dl.pstmn.io/download/channel/canary/windows_32
Windows 64-bit: https://dl.pstmn.io/download/channel/canary/windows_64
Linux 32-bit: https://dl.pstmn.io/download/channel/canary/linux_32
Linux 64-bit: https://dl.pstmn.io/download/channel/canary/linux_64
Chrome: https://chrome.google.com/webstore/detail/loddepljkabcghihdkbkfknabkinanff/

1. Variable highlighting and tooltip on hover
Variables are highlighted in orange, with unresolved variables shown in red colour. Hovering over a variable shows its current value and the scope. If a variable is unresolved i.e. it does not have a value in the current environment, the tooltip shows the appropriate feedback.
![2 tooltip](https://cloud.githubusercontent.com/assets/14976346/23355675/e4761058-fcfc-11e6-9f9f-039bb1bfbad9.gif)


2. Autocomplete for variables
Type an open curly bracket to bring up the autocomplete menu. For the pre-request scripts and tests section, which uses the ace-editor, entering the first letter of a variable triggers the autocomplete. The menu contains a list of all the variables in the current environment followed by globals. Oh, and there’s more! Navigating through the list also shows the current value and scope for each variable, along with a feedback for overridden variables. 
![1 autocomplete](https://cloud.githubusercontent.com/assets/14976346/23355681/ebdf7b18-fcfc-11e6-896d-384284f375de.gif)


Additionally, we’re introducing a new - and more powerful - data editor in Postman! This new editor is an enhancement to the key-value editor and lets you view and manipulate data in a faster, more effective and elegant manner.
![new data editor](https://cloud.githubusercontent.com/assets/14976346/23355994/367338d0-fcfe-11e6-8f64-8486c7180aa4.gif)

Go ahead, download and let us know what you think.
