### ISSUE TITLE
Open Settings shortcut not working in some places

### ISSUE THREAD

**Issue by ghost** [a85/POSTMan-Chrome-Extension#1913]
Environment: 4.1.0, OS X 15.3.0 / x64

Open Settings `Cmd + ,` shortcut is not working in some places, like for instance when response Pretty edit text field is focused, or when request raw body edit text is focused.

**Comment by mstaalesen** [comment]
This bug is also present in Ubuntu 14.04 with Postman 4.1.2

**Comment by numaanashraf** [comment]
@danielpigan @mstaalesen Thanks for reporting this. We are taking a look at this and should have a fix out soon.

**Comment by a85** [comment]
Working for me now (4.7+). Closing the issue. @mstaalesen Feel free to reopen if you see this in Ubuntu too.
