### ISSUE TITLE
Esc not closing popup if environment was updated

### ISSUE THREAD

**Issue by ghost** [a85/POSTMan-Chrome-Extension#1914]
Environment: 4.1.0, OS X 15.3.0 / x64

Steps to reproduce:
1. Open Manage Environments popup with `Cmd + e`.
2. Select Environment. (Result: Environment variable - value pairs popup is is opened.)
3. Press `Update` button OR use `Cmd + Return` to save changes. (Result: Going back to Manage Environments popup.)
4. Press `Esc` to close Manage Environment popup. (Result: Nothing happens.)

This only occurs when changes to environments are done. Pressing `Esc` without updating closes popup just fine.

**Comment by numaanashraf** [comment]
@danielpigan Thanks for reporting this. We will fix this in the coming releases.

**Comment by mstaalesen** [comment]
This bug is also present in Ubuntu 14.04 with Postman 4.1.2

**Comment by numaanashraf** [comment]
@danielpigan @mstaalesen We have pushed a fix for this issue. Could you update to the latest v4.4 version and verify?
