### ISSUE TITLE
what's wrong with my global env file?

### ISSUE THREAD

**Issue by srbangre** [a85/POSTMan-Chrome-Extension#1916]
Hi,
I created global env file, downloaded it as json and shared it with my teammate. 
he is unable to download it. postman throws some error. But when i try to download it, i get no errors.
Can you please check whats wrong with my env file attached here?
[globals.postman_globals.txt](https://github.com/postmanlabs/postman-app-support/files/185024/globals.postman_globals.txt)

please remove the file extention .txt to see the json file.

**Comment by abhijitkane** [comment]
@srbangre Right now, Postman does not allow importing of global files. These are only usable in Newman (https://npmjs.org/package/newman). 
To import the same data as an environment (rather than globals), your teammate can use this link - https://gist.github.com/abhijitkane/123e27cd48081ffd519c

**Comment by srbangre** [comment]
if i am correct, the link you shared will actually create a new environment in postman.
i already have one env selected to run my scripts. that env file has lots of fields along with endpoints.
how can i use my-globals and other env file at the same time?
also is there any reason postman doesn't allow importing global files?

**Comment by abhijitkane** [comment]
Yes, that will create an environment. We're working on adding globals - the issue is that you can import a new environment (which won't overwrite anything), but importing globals has the potential to overwrite existing data.

**Comment by srbangre** [comment]
that's true for normal env files as well f they have same names. you can probably put a message to be displayed to user when they import the global file saying - 'it will replace your global file. are you sure?'
another way - not sure if this is possible to duplicate the regular env file to globals instead of copying field by field.
So shall i wait for next update for importing global env or modify my scripts now itself?
I am very much impresed with your prompt response. thanks so much :)

**Comment by abhijitkane** [comment]
Importing globals is still a while away.

One thing you can do - import the file as an environment, edit it, scroll to the bottom, and click Bulk Edit.
Copy the values, head to the Globals editor > Bulk Edit > Paste.

**Comment by srbangre** [comment]
cool i can live with that. thanks so much you can close this issue :)
