### ISSUE TITLE
Status reason phrase is not displayed in the new version (4.1.x)

### ISSUE THREAD

**Issue by illinar** [a85/POSTMan-Chrome-Extension#1918]
Previous versions of Postman correctly displayed custom reason phrase returned alongside the status code. New version (observed in 4.1.2) displays the status code but custom reason phrase is nowhere to be found. For example,

> HTTP/1.1 404 This text should appear somewhere

`This text should appear somewhere` is not displayed anywhere in the UI. Note that according to HTTP spec

> Status-Line = HTTP-Version SP Status-Code SP Reason-Phrase CRLF

**Comment by abhijitkane** [comment]
@illinar We've fixed this in our internal build, and will push out a fix soon.

**Comment by kyle7johnson** [comment]
Noticed this as well. Thank you!

**Comment by ghost** [comment]
I have it. Is there any possible way to reveal this kind of response information?

**Comment by abhijitkane** [comment]
@kyle7johnson @SherifRefaat  Can you confirm this fixed in the latest version?

**Comment by ugumba** [comment]
This happens on version 4.7.2 (Windows app).
E.g. my API returns 400 with a descriptive reason.  Postman displays "Bad request".  2 other API testing tools show my custom reason phrase.

**Comment by ghost** [comment]
@abhijitkane No it is not.
