### ISSUE TITLE
Feature Request : Generate to HTML form

### ISSUE THREAD

**Issue by iarief** [a85/POSTMan-Chrome-Extension#1919]
Hi, i know that there's a lot of generated source code for many programming language, but can we have a generated to basic html form? This might be a requirement for some of us that needed to give a testing form to clients of software that we developed. And they usually doesn't want to be troubled by using a terminal (for curl command) or installing any programming language in their pc.

**Comment by abhijitkane** [comment]
@funsterisdafunniest Can you give an example of the sort of snippet you're talking about?

**Comment by a85** [comment]
This needs to be a 3rd-party plugin using the Collections format.
