### ISSUE TITLE
Bulk Edit for Url Params field is not Working in Mac Client (Version 4.1.0 (4.1.0))

### ISSUE THREAD

**Issue by ghost** [a85/POSTMan-Chrome-Extension#1920]
The Bulk edit button removes all the inputted data and only let's the user to add new fields. Already typed in fields could not be edited.

**Comment by numaanashraf** [comment]
@faizanke Thanks for reporting this. We will include a fix in this week's release.

**Comment by ghost** [comment]
@numaanashraf Awesome :) The Bulk Edit button's throughout the Postman app doesn't seem to be working. Kindly have a check.

**Comment by numaanashraf** [comment]
@faizanke Sure. This is fixed in our internal build and is being tested now. You'll get the fix in the next release, which should be out in a day or two.

**Comment by ghost** [comment]
Fixed in Postman Version 4.1.1 (4.1.1) for mac.
