### ISSUE TITLE
Old Postman app doesn't show anything and nothing is working

### ISSUE THREAD

**Issue by ykiran** [a85/POSTMan-Chrome-Extension#1921]
I opened the app (this is the old postman app) today after closing it yesterday.
I see that there is nothing in history, none of the buttons are working when I'm clicking on them and there is a strange scrollbar to the right with an empty window. 
![postman_err_screenshot](https://cloud.githubusercontent.com/assets/5526410/13984995/f443814e-f11f-11e5-9edf-acd26e789c45.jpg)

In addition to that, when I opened the dev tools console, I see the following error:
**requester.js:112 Uncaught TypeError: Cannot assign to read only property 'indexedDB' of object '#<Window>'**

I've attached a screenshot for reference.

**Comment by abhijitkane** [comment]
This is due to a change in Chrome. The app hasn't been updated for over a year. We've stopped supporting this app. You'll need to install the packaged app - https://chrome.google.com/webstore/detail/postman-rest-client-packa/fhbjgbiflinjbdggehcddcbncdddomop?hl=en

**Comment by a85** [comment]
Folks. We can't keep up with changes in the Chrome platform every 6 weeks for the legacy app that we deprecated a year ago. We will see if we can push an update but I'd recommend upgrading.

**Comment by heyyoyo** [comment]
I have the same issue, but will I keep my history and my collections if I upgrade ?
After installing the Postman 3 and now upgraded to 4.1.3, collections and history were empty.

**Comment by guatedude2** [comment]
Is there a way to import my collection from the Postman extension to the app? I can't export my collection from the extension due to this error.

**Comment by abhijitkane** [comment]
@guatedude2 @heyyoyo 

Which Postman Extension do you have - https://chrome.google.com/webstore/detail/postman-rest-client-short/mkhojklkhkdaghjjfdnphfphiaiohkef/reviews?hl=en or https://chrome.google.com/webstore/detail/postman-rest-client/fdmmgilgnpjigdojojpjoooidkmcomcm?hl=en?
The first one is an unauthorized clone of Postman, and we cannot provide support for that. If you're on the second one, head to chrome://extensions, enable 'Developer Tools', and click 'Update Extensions now'. This will update you to 0.8.4.17, and you will be able to access your data.

The new Postman app is available at https://chrome.google.com/webstore/detail/postman-rest-client-packa/fhbjgbiflinjbdggehcddcbncdddomop?hl=en.
