### ISSUE TITLE
Collection Runner only running once?

### ISSUE THREAD

**Issue by advil0** [a85/POSTMan-Chrome-Extension#1922]
I have a collection that I'm running using a CSV file, when it runs, the first iteration runs great but it refuses to run any further iterations, it just stops as if it's done.  Any idea what I'm doing wrong?

**Comment by abhijitkane** [comment]
@advil0 Can you try upgrading your app? If you're on Chrome, chrome://extensions, enable 'Developer Mode', click 'Update extensions now'.

**Comment by advil0** [comment]
I was actually using the Mac app, it was up to date, I downloaded and installed the Chrome app and it is now working, would this be considered a bug?

**Comment by abhijitkane** [comment]
Yep - the Mac app will get the fix this week.

**Comment by prasad0616** [comment]
I had the same issue. Does your collection have number of api's chained together to form a collection. If thats the case pls have the iteration value as n+1, where n is the number of apis chained together to form your collection.

**Comment by abhijitkane** [comment]
@prasad0616 @advil0 Can you confirm this fixed in the latest versions?
