### ISSUE TITLE
Setting the screen loading background color

### ISSUE THREAD

**Issue by riconegri** [a85/POSTMan-Chrome-Extension#1924]
orange is very strong, at least set the intensity of it.

**Comment by WagnerMoreira** [comment]
+1

**Comment by mateusleon** [comment]
I guess this is quite important to guarantee healthy eyes for more time than it's expected for programmers/developers. Good point, indeed.

**Comment by a85** [comment]
The orange is gone but we are trying to just get rid of the loading screen altogether! :)

**Comment by riconegri** [comment]
Could be simpler, the theme of black color, black background, white theme, white background, because black theme fans consume a white background?
