### ISSUE TITLE
Numerous errors in console, causing postman to crash

### ISSUE THREAD

**Issue by nickwb** [a85/POSTMan-Chrome-Extension#1925]
See attached image of errors.

![image](https://cloud.githubusercontent.com/assets/594211/14009790/264d7274-f1db-11e5-9bd8-300591a472b1.png)

I'm not sure when I last used postman, but perhaps ~3 weeks ago it wasn't an issue.

It causes the whole app to crash, see below.

![image](https://cloud.githubusercontent.com/assets/594211/14009819/52c41a38-f1db-11e5-9242-be65148ea0d5.png)

**Comment by nickwb** [comment]
FYI, I resolved by uninstalling from chrome and re-installing. This wasn't ideal, as I was working offline and lost all my collections. I had to restore from a backup.

**Comment by abhijitkane** [comment]
@nickwb This was an older version of Postman that stopped working due to a Chrome update. To update without reinstalling, head to chrome:/extensions, enable 'Developer Mode', and click 'Update extensions now'. This would have preserved your collections.
