### ISSUE TITLE
Duplicated Collections have the same Collection URLs 

### ISSUE THREAD

**Issue by thirtified** [a85/POSTMan-Chrome-Extension#1926]
Choosing "duplicate" on a collection creates a new and separate collection which uses the same shared Collection URL: published changes to either of these collections will overwrite what has been published before, and there is no way to un-link the Collection URL.

Tested on Mac native v4.1.0.

**Comment by abhijitkane** [comment]
@thirtified Thanks for reporting this. We'll be pushing a fix for this in the next release of the app - should be out in a day or two.
