### ISSUE TITLE
Some keyboard shortcuts are currently not working

### ISSUE THREAD

**Issue by mstaalesen** [a85/POSTMan-Chrome-Extension#1929]
It seems that the following keyboard shortcuts are not working as of right now (4.1.2):
ctrl + n (new tab)
ctrl + p (preview)

**Comment by abhijitkane** [comment]
@mstaalesen The shortcut for new tab is Ctrl+T. We're working on shortcuts for new windows.

**Comment by mstaalesen** [comment]
Ok, thanks!

FYI, the Settings screen for shortcuts states ctrl + n:
![image](https://cloud.githubusercontent.com/assets/14194793/14046822/233b528a-f2a4-11e5-88f7-3900f3a6bcfe.png)

**Comment by mstaalesen** [comment]
4.1.3: Preview Request is gone (intended?) and New Tab is now ctrl + T, and new window is now ctrl + n.

Closing this.
