### ISSUE TITLE
Testing API Timeouts

### ISSUE THREAD

**Issue by genaro-picazo** [a85/POSTMan-Chrome-Extension#1931]
Is there a way to test intentional API timeouts via POSTMAN/Newman? I have a request that I expect to timeout, and I would like to add a test case that validates that the request indeed times out. Is that possible?

**Comment by mstaalesen** [comment]
What is "timeout"? 
Postman has an internal timeout setting (default is infinity), but if you attempt to set the timeout to 1 ms, you will see that when POSTMAN decides that the request timed out, it will not give you any possibility to do asserts on the request itself. I do believe it is the same with newman.

I'm a bit curious about the use case for this too. Do you have a defined time a timeout is? Does the server send you an error? (Being a timeout, i assumed no)

I think you need to elaborate a little more if possible.

**Comment by genaro-picazo** [comment]
Closing the request since it doesn't really make sense anymore :)

**Comment by januszm** [comment]
It actually makes sense. @mstaalesen I think what @gpicazo meant is that he wanted to test the server's (API) timeout settings and simulate a "slow client" with Postman. 

Let's say that the server read timeout is set to 3 seconds, it'd be cool if we could tell Postman to throttle the request so it takes 5+ seconds. Something that somewhat resembles network throttling in Chrome Dev Tools.

**Comment by amandadale** [comment]
I second this request! if we could have paths on a mock server that would just hang in order to test that our apps handle connect/read timeouts on http requests correctly

**Comment by svenluijten** [comment]
👍 Being able to throttle requests / simulate slow clients would be very useful. 

@gpicazo can  you re-open this issue? The question is still valid, and it _does_ make sense. 🙂

**Comment by ssaintma** [comment]
I find a way to simulate a client timeout.
Add this pre-request script on your example : `setTimeout(function(){}, 10000); ` to wait 10 seconds before answer.
[Source](https://out-of-memo.blogspot.com/2017/10/postman-set-timeout-think-time-pause.html)

**Comment by spookalucca** [comment]
Agreed. Would like to see this ticket re-opened. @gpicazo can you reconsider please?

**Comment by mtrezza** [comment]
Maybe this is of help to anyone looking for an API that times out: http://httpstat.us

**Comment by jbarbera** [comment]
You can do a normal request with postman and then export the request to any language and add the timeout parameter on the call
