### ISSUE TITLE
Curl: generated snippet in curl doesn't escape $

### ISSUE THREAD

**Issue by akshah123** [a85/POSTMan-Chrome-Extension#1932]
If you have a url like

`
https://www.test.com?$parameter=value
`

It does not properly escape `$` in the url.

It generates:

```
curl -X GET "https://www.test.com?$parameter=value"
```

It should instead do:

```
curl -X GET "https://www.test.com?\$parameter=value"
```

**Comment by abhijitkane** [comment]
@akshah123 For now, can you try choosing Shell > cURL from the menu instead of cURL? This should solve the issue.

**Comment by akshah123** [comment]
Yes, that worked. What is the difference between the two?

**Comment by SimonRingeisen** [comment]
I think this error doesn't only apply to $, but to a wide range to special chars (e.g. a raw body, send with post). 

http://stackoverflow.com/questions/17560858/command-prompt-having-trouble-escaping-quotes-and-braces

**Comment by sdnts** [comment]
Can you guys try updating to the latest version (4.8.3) and see if characters are correctly encoded?
