### ISSUE TITLE
Ctrl-w closes the entire window instead of closing tabs

### ISSUE THREAD

**Issue by johndevedu** [a85/POSTMan-Chrome-Extension#1934]
I am used to the browser method of using the keyboard combination ctrl-w to close tabs. This has the undesirable effect of closing the entire Postman window and losing all tabs. Can you wire ctrl-w to closing the active tab? Thanks!

**Comment by a85** [comment]
We can't until Chrome allows it. If you're on OS X, check out the native app: www.getpostman.com/apps

**Comment by a85** [comment]
Can't do anything on the Chrome app and honestly pretty frustrated with the Chrome platform. Closing this. We'll have Windows/Linux native apps soon.
