### ISSUE TITLE
exporting tests on a collection/request when downloading

### ISSUE THREAD

**Issue by jheld** [a85/POSTMan-Chrome-Extension#1935]
I have a use case where I'm importing (to an external app) a Postman collection of requests with tests for each.

It would be nice to have the tests included on the export/download, so that I may not have to run it twice. Granted the other side would have to include support for parsing those pieces out of the collection, but that's not in this scope since you have no control over that.

**Comment by abhijitkane** [comment]
@jheld If you download a collection, the test scripts are included in the `tests` property for each request.
