### ISSUE TITLE
Default focus on search textbox

### ISSUE THREAD

**Issue by snydercoder** [a85/POSTMan-Chrome-Extension#1937]
Hi Guys,

I love your product!  One thing that would be great is if when you click the magnifying glass to search for text in the response that the search textbox would have focus so the user can start typing their search immediately.  I'm running Postman on OSX El Capitan.

Thanks!
Matt

p.s. If you want to open source it I'd be happy to fork, fix, and PR. ;-)

**Comment by ghost** [comment]
+1
I'm running Postman on Windows 7.

**Comment by numaanashraf** [comment]
@snydercoder @Ann25 Got it! We'll include this in the coming release. In the meantime, you can open the searchbox and autofocus it by using the `Cmd + F` or `Ctrl + F` key shortcut while the response is in focus.

**Comment by prashantagarwal** [comment]
This is fixed in latest Postman app.
