### ISSUE TITLE
Provide more details for SSL failures

### ISSUE THREAD

**Issue by RichardFoo** [a85/POSTMan-Chrome-Extension#1938]
‘SSL Certificate Validation’ - it’s valuable for this to stay defaulted to On (to expose issues early in development), but better error messaging is needed – an SSL failure is a very different problem from a connectivity issue, but in 4.1.0 they are lumped together.

An SSL failure should provide as much detail as possible (server name mismatch, CA not recognized, cert expired, no acceptable cipher, etc.).  A hyperlink to disable the validation would also be handy.
- Click here to review the certificate details, with the problem area highlighted
- Click here to open the settings screen so the parameter can be disabled

**Comment by RichardFoo** [comment]
Loosely similar to a different [enhancement request](https://github.com/postmanlabs/postman-app-support/issues/1884), which is specific to client-side SSL certificates.

**Comment by shamasis** [comment]
@czardoz is there any further scope left to elaborate the SSL failure error message? Does UI show SSL failure messages on response area / like script errors? + @a85

**Comment by czardoz** [comment]
@Richard-Foo SSL failure details are logged in the Postman Console (View > Postman Console), which contain these details.

**Comment by shamasis** [comment]
Postman had added support to show SSL in response area. And added feature to see SSL errors even when SSL validation has been turned off. 

If there are cases of SSL errors that are not captured and we have missed it, please let us know by filing a new issue.

See screenshots below:

<img width="905" alt="image" src="https://user-images.githubusercontent.com/232373/107512687-32390f00-6bcd-11eb-9f41-5e6092451887.png">
<img width="896" alt="image" src="https://user-images.githubusercontent.com/232373/107512724-3bc27700-6bcd-11eb-83f8-5784222dff8c.png">
<img width="901" alt="image" src="https://user-images.githubusercontent.com/232373/107512887-74625080-6bcd-11eb-9175-658ebd846361.png">
