### ISSUE TITLE
Body Tab in Post Request has unsaved changes circle always

### ISSUE THREAD

**Issue by jbelmont** [a85/POSTMan-Chrome-Extension#1940]
When I make a post request in postman and use the raw json radio button the body tab never seems to save at least through the ui it appears not to save my changes in the request. I would expect that when I save this route that the body tab shows as saved too if I have raw json.
![screen shot 2016-03-28 at 10 32 00 am](https://cloud.githubusercontent.com/assets/2974744/14080037/616f6860-f4d0-11e5-8e97-7fb63018ff6f.png)

**Comment by abhijitkane** [comment]
@jbelmont The blue dot next to "Body" indicates that the request has a body, not that it is unsaved.

**Comment by jbelmont** [comment]
@abhijitkane I see what you mean now. I guess I was comparing the behavior I noticed in older postman app versions. I didn't recall seeing the blue dot like this before but yeah that seems like a better indicator than before.
