### ISSUE TITLE
authentication type selection and params are not saved

### ISSUE THREAD

**Issue by vicenteg** [a85/POSTMan-Chrome-Extension#1941]
For a request I can set the authentication type to Basic, then I set the username and password to variables I've created in the environment. I update the request, then click save.

When I leave the request and return, Type has been reset to No Auth, and I need to re-enter authentication information.

**Comment by abhijitkane** [comment]
@vicenteg Are you checking the 'Save helper data to request' checkbox?

**Comment by vicenteg** [comment]
I don't see any such checkbox. Here are my versions:

```
4.1.2
OS X / x86-64
Chrome 49.0.2623.87
```

**Comment by vicenteg** [comment]
Just found it on the authorization panel - had been looking in the settings. Will test and report back. Thanks!

**Comment by vicenteg** [comment]
That took care of it. Thanks.
