### ISSUE TITLE
Postman - REST Client shortcut Not Working 

### ISSUE THREAD

**Issue by ssahni30** [a85/POSTMan-Chrome-Extension#1942]
After my Chrome Canary upgrade to Version 51.0.2692.0 canary (64-bit). Postman have stopped working.
 Postman is not working at all. I am unable to access URL params or headers or any other option. Even send button is not working no request is being generated in network tab of chrome's inspect element.

My console shows this error while opening POSTMAN - 
Uncaught TypeError: Cannot assign to read only property 'indexedDB' of object '#< Window > '

Is there any configuration that needs to be changed now ??

**Comment by numaanashraf** [comment]
@ssahni30 That's odd. Could you let us know your Postman app version and OS version?

**Comment by ssahni30** [comment]
Postman Version: 0.8.4.8 and i am using OS X version 10.11.4 (El Capitan)

**Comment by qmacpit** [comment]
The same thing: 
- Chrome Canary Version 51.0.2703.0 canary
- Win 10
- Postman - REST Client 0.8.4.16

**Comment by heyyoyo** [comment]
Any update on this issue ? Or way to upgrade to new version without loosing history and collections ?

**Comment by heyyoyo** [comment]
In the google chrome console I have the following error:

> requester.js:112 Uncaught TypeError: Cannot assign to read only property 'indexedDB' of object '#<Window>'

But it seems to be a duplicate to this issue:
https://github.com/postmanlabs/postman-app-support/issues/1921

But it is already closed. I hope the developpers of this really nice extension will make a last patch for this version.

**Comment by gkohen** [comment]
Same issue here. Too bad it happened just before a demo we had :(

**Comment by abhijitkane** [comment]
@gkohen @heyyoyo @ssahni30 

Which Postman Extension do you have - https://chrome.google.com/webstore/detail/postman-rest-client-short/mkhojklkhkdaghjjfdnphfphiaiohkef/reviews?hl=en or https://chrome.google.com/webstore/detail/postman-rest-client/fdmmgilgnpjigdojojpjoooidkmcomcm?hl=en?
The first one is an unauthorized clone of Postman, and we cannot provide support for that. If you're on the second one, head to chrome://extensions, enable 'Developer Mode', and click 'Update Extensions now'. This will update you to 0.8.4.17, and you will be able to access your data.

The new Postman app is available at https://chrome.google.com/webstore/detail/postman-rest-client-packa/fhbjgbiflinjbdggehcddcbncdddomop?hl=en.
