### ISSUE TITLE
'Send and Download' base64 encodes binaries. 

### ISSUE THREAD

**Issue by Aaargh20318** [a85/POSTMan-Chrome-Extension#1943]
I was testing a REST interface after I made some modifications to my code and suddenly all the images I saved using postman were base64 encoded. Capturing a request using Wireshark shows the responses from the server _are_ binary, postman is doing the base64 conversion when saving to disk. 

This bug was introduced in a recent release as I used the same scenario a week or so back and at that time everything worked as expected.

Postman should _never_ transform the output in any way when saving to file as it is unexpected behaviour for the user. I already wasted time debugging my server code, trying to figure out why JAX-RS was suddenly base64-encoding images before I figured out the problem was Postman.

**Comment by wspringer** [comment]
Having exactly the same issue.

**Comment by abhijitkane** [comment]
@Aaargh20318 @wspringer What versions of Postman are you using?

**Comment by Aaargh20318** [comment]
I'm using 4.1.2

**Comment by abhijitkane** [comment]
Can you update to 4.1.3 (chrome://extensions > Enable Developer Mode > Update extensions now)? I'm able to download images using Send and Download properly.

**Comment by Aaargh20318** [comment]
4.1.3 works.
