### ISSUE TITLE
When encountering a failed request Postman hangs at loading

### ISSUE THREAD

**Issue by joshlrogers** [a85/POSTMan-Chrome-Extension#1944]
When testing an API that returns a status code signifying a failed request Postman does not complete the request within the UI.  When looking at the inspector you can see that a status code of 404 is returned by the request, for instance, but the Postman screen still says the request is loading.  We have tested across multiple developer machines against different API endpoints and we see the same consistent bug across all of our machines.

**Comment by abhijitkane** [comment]
@joshlrogers What version of Postman are you using? In the latest version (4.1.2), a GET request to `http://httpbin.org/status/404` shows the 404 in Postman.

**Comment by joshlrogers** [comment]
We are on version 4.1.2.

Your link does indeed work for us...so it is possible it is something specific to this particular API then?

When I look at the network tab in Chrome I see this:
![image](https://cloud.githubusercontent.com/assets/6315573/14111800/c21e4c00-f591-11e5-8ae6-e4784fea4a08.png)

These are the response headers:
HTTP/1.1 404 Not Found
Content-Encoding: gzip
Content-Type: application/json
Date: Tue, 29 Mar 2016 14:36:13 GMT
nnCoection: close
Pragma: No-cache
Server: Apache
Vary: Accept-Encoding
X-Mashery-Message-ID: 86dd1216-4878-4ec4-9a29-533ed45d7afc
X-Mashery-Responder: prod-j-worker-us-east-1d-104.mashery.com
Content-Length: 72
Connection: keep-alive

**Comment by joshlrogers** [comment]
Is there some more information I can provide around this to help determine root cause?  We would really like to get these tests going and be able to trust them.

**Comment by abhijitkane** [comment]
@joshlrogers Can you click on the red `1234999` request in the Network tab, and attach a screenshot of that? We've tried to reproduce this with the response headers you mentioned, but couldn't see the problem.

**Comment by joshlrogers** [comment]
This is the screenshot:
![image](https://cloud.githubusercontent.com/assets/6315573/14260963/dc0ce0f4-fa73-11e5-84eb-9f6b60e79d69.png)

**Comment by abhijitkane** [comment]
What about the "Console" tab - any errors there?

**Comment by joshlrogers** [comment]
Just what you can see above in my first screenshot that the api actually returns a 404.  But it seems the resource.js file isn't "catching" it and is just waiting.

**Comment by abhijitkane** [comment]
Is the Interceptor enabled in Postman?

**Comment by joshlrogers** [comment]
It is not.

**Comment by abhijitkane** [comment]
How about this endpoint (returns the same headers as your URL) - http://demo1863006.mockable.io//404test

What's the response body? (some body might be present even for a 404 - screenshot attached)
![screen shot 2016-04-05 at 01 47 43](https://cloud.githubusercontent.com/assets/681190/14261892/792cde1e-fad0-11e5-8800-9163f15c5c88.png)

**Comment by joshlrogers** [comment]
I get a hello.

There are really only two differences between the tests that I can tell.  Besides obviously talking to a different API.

1.) The test that fails is using an HTTPS endpoint
2.) The test that fails is also using an authorization header. It is in the format of Bearer {random string sequence}

Beyond those two differences there aren't really differences in the test themselves.  Here are the request headers we send with the token taken out:

Accept:_/_
Accept-Encoding:gzip, deflate, sdch
Accept-Language:en-US,en;q=0.8
Authorization:Bearer {token}
Cache-Control:no-cache
Connection:keep-alive
DNT:1
Host:api.athenahealth.com
Postman-Token:678ab9b5-0d30-7e03-4b35-7cd7fc2b5d1c
Pragma:no-cache
User-Agent:Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36

**Comment by joshlrogers** [comment]
Has there been any activity toward locating the issue here?

**Comment by abhijitkane** [comment]
@joshlrogers We've tried to reproduce this on multiple APIs across different versions of Postman - but we always see the Failure state. Is there any publicly-accessible API that you can reproduce this problem with?
If not, not really sure how to debug this.

**Comment by joshlrogers** [comment]
We haven't ran into this issue except with this one API but we all experience it.  I will see what I can do about finding a way to replicate this for you.  Thank you for continuing to try.

**Comment by abhijitkane** [comment]
@joshlrogers Feel free to open another issue if there's another API you face this with. Closing this issue as non-actionable for now. Thanks.

**Comment by irislian199092** [comment]
I  came the same problem.Is there any solutions on this?

**Comment by phillijw** [comment]
This started happening for me immediately after removing the interceptor chrome extension. Even after turning off interceptor stuff in postman settings, it still doesn't work

**Comment by peturh** [comment]
The internal Chrome DNS was fucking with me. 

Go to: `chrome://net-internals` 

Click DNS in the left menu and then "Clear host cache"

This solved it for me.
