### ISSUE TITLE
oauth1 with raw body Uncaught TypeError

### ISSUE THREAD

**Issue by ObviouslyGreen** [a85/POSTMan-Chrome-Extension#1948]
I am trying to make a post request that uses oauth1 and takes in a json, and was having trouble. I tested it generically by posting to http://httpbin.org/post and got the same error, so I'm thinking it is a bug.

Uncaught TypeError: Cannot assign to read only property 'value' of {
    "generic": "json"
} requester.js:207138

**Comment by abhijitkane** [comment]
@ObviouslyGreen Can you mention the Postman version you're on? The latest version is 4.1.2.

**Comment by ObviouslyGreen** [comment]
I was running 4.1.0. I updated and it seems to work now. Thanks!
