### ISSUE TITLE
User ACL & Orphaned Collections

### ISSUE THREAD

**Issue by aaronweatherall** [a85/POSTMan-Chrome-Extension#1949]
Hey Team,

We're trialling the cloud and LOVE IT! But we're having a lot of issues with people overwriting collections and then not being able to write when required.

What we'd love to see is ACL (Access Control Lists). That way an admin can grant write access to specific members.

**Use case:**
User 1 administers a LARGE collection of integration tests.
User 2 & 3 (QA) regularly run it to test features. User 3 accidentally writes to the collection and now it's broken for everyone.
User 1 makes the collection READ ONLY.
User 4 (Primary Dev) wants to add new data, but can't because its read only!

There's another issue we're having around orphaned collections. If a user creates a collection then is removed from the team, we no longer have the ability to update that collection. You can't reassign collections to other users.

An ideal here would be that when a collection is shared to a team, it's 'copied' to the team OR it's easy to change ownership of a collection.

**Comment by abhijitkane** [comment]
@aaronweatherall Thanks! Access control lists is something we're working on, and hope to have out soon.
For the orphaned collections - a quick fix for now would be having someone else duplicate the collection and share it with a different name (append `(new)`, for example). This has been a frequent feature request, and is on our roadmap too.

**Comment by a85** [comment]
@aaronweatherall Being tested on our staging environment now.

**Comment by elliotfleming** [comment]
Are there any plans to allow more restrictive controls, such as the ability to only show a shared collection to certain team members instead of all or nothing? Groups?

It would be great to be able to manage multiple teams with one account.

**Comment by a85** [comment]
@elliotfleming Groups are on our roadmap. No ETA yet though. We'll make our roadmap for Postman and Postman Cloud public next month for more clarity.

**Comment by a85** [comment]
Workspaces along with Role Based Access Control features in Postman will solve for this now. More improvements coming soon! No more concept of ownership.
