### ISSUE TITLE
[Bug] Syntax error indicated where there is none

### ISSUE THREAD

**Issue by aqyblitz** [a85/POSTMan-Chrome-Extension#1950]
The context is while chaining JSON response data between two API requests; my goal was to take the entirety of the response data from the first request (GET) and pass it as the body for the second request (POST).

To do this, I stored the response data of the first request as an environment variable and passed it to the second request via the {{variable-name}} syntax in the "Body" tab, under "raw." It indicates a syntax error even though this works perfectly fine.

![bug](https://cloud.githubusercontent.com/assets/5193369/14162153/11d0bc08-f69e-11e5-9b30-06cb602198d3.png)

**Comment by abhijitkane** [comment]
@aqyblitz This is a limitation of sorts with the component we use to render the request body. `{{payload}}` by itself is invalid JSON. It's only valid when replaced with the variable value. The component can only see the `{{payload}}` part, and thinks it's an error.

We're working on a way to get around this, but it shouldn't hamper usability in any way.

**Comment by aqyblitz** [comment]
Yeah, that's what I had figured. It definitely still works, just thought I'd log the bug in case the Postman team wasn't aware of it. Thanks for the prompt response.

**Comment by sryze** [comment]
It still works but can hide real JSON syntax errors behind these sort-of-errors. One workaround I found is to put them in quotes so they become strings, however this may not work for other APIs (I think).

**Comment by abhijitkane** [comment]
@sryze @aqyblitz This should be fixed in the latest version of the app. Can you confirm?

**Comment by aqyblitz** [comment]
Confirmed. Thanks for the good work :)

**Comment by aqyblitz** [comment]
Whoops, didn't mean to close it as well. Hope that was okay.

**Comment by sryze** [comment]
Yes, it's working now. Thanks!
