### ISSUE TITLE
Bulk edited Headers preset causes Body content type defaulting to Text

### ISSUE THREAD

**Issue by designorant** [a85/POSTMan-Chrome-Extension#1951]
Step by step screenshots below. Notice how Body content type changes from JSON to Text in the process.

![postman1](https://cloud.githubusercontent.com/assets/87477/14171856/0bc4bda2-f72d-11e5-87c7-900153d855b0.png)
![postman2](https://cloud.githubusercontent.com/assets/87477/14171859/0bd4dbf6-f72d-11e5-817a-73db23305e64.png)
![postman3](https://cloud.githubusercontent.com/assets/87477/14171858/0bcf6586-f72d-11e5-9c43-b64f1d43bc76.png)
![postman4](https://cloud.githubusercontent.com/assets/87477/14171857/0bcf28dc-f72d-11e5-81a9-8f09d786f600.png)

**Comment by aditikul** [comment]
Thats weird. Looks like a bug. Thanks for reporting it, we are looking into this.

**Comment by sweetw0r** [comment]
Almost the same happened when you try to bulk edit headers:
1. Go to bulk edit 
2. Make you changes
3. Go to body and check it
4. Go back to headers and check them

Expected:
Changes in the headers should remain

Actual: 
Changes in the headers are gone.
![postman_headers_bulk](https://cloud.githubusercontent.com/assets/12688470/17418826/51ae84e4-5a4f-11e6-9da3-59cb97866a47.gif)

**Comment by a85** [comment]
Should be fixed now. Couldn't replicate in 4.8.3
