### ISSUE TITLE
Search and Replace dialog box dissappears when clicking "Replace" and "All"

### ISSUE THREAD

**Issue by mstaalesen** [a85/POSTMan-Chrome-Extension#1952]
When using Search / Replace on e.g the Tests in Postman, the dialog box disappears when I click the Replace button. Not a huge thing, but rather annoying when I want to replace more than 1 thing:

![animation3](https://cloud.githubusercontent.com/assets/14194793/14180646/3d814176-f764-11e5-8715-0153742bfbde.gif)

**Comment by numaanashraf** [comment]
Thanks for reporting this @mstaalesen. We'll include a fix in the next release.

**Comment by sdnts** [comment]
We've fixed this in our internal build, we'll push a fix in the next release :)

**Comment by abhijitkane** [comment]
@mstaalesen This has been fixed in the latest version (4.4.2) of the app. To update - https://www.getpostman.com/docs/updating
