### ISSUE TITLE
Postman not saving values of AWS signature helperAttributes "Service Name"

### ISSUE THREAD

**Issue by willrichboa** [a85/POSTMan-Chrome-Extension#1953]
I never got a response after you closed https://github.com/postmanlabs/postman-app-support/issues/1821.

Create a new request or use an existing one.
Under the "Authorization" tab: select type of "AWS Signature".
Update, "AccessKey", "SecretKey", "AWS Region", and "Service Name" to any values.
Select the checkmark on the "Save helper data to request" so that it is checked.
Save the request to a new or existing collection.
Close the request tab.
Reopen the request.
Expected: the AWS helper values persist.
Observed: the AWS helper value "Service Name" is blank.  

Save the collection.
Open the collection file:
The helperAttributes for that request does not contain a "serviceName" entry.

**Comment by abhijitkane** [comment]
@willrichboa Thanks for reporting this. We've fixed this internally, and will push the fix in the next release.
