### ISSUE TITLE
POST request using Interceptor hangs

### ISSUE THREAD

**Issue by dave-hickson** [a85/POSTMan-Chrome-Extension#1954]
I'm using Postman 4.1.2 on a Windows 8.1 pc.  I'm issuing a POST request with a raw JSON body and a Content-Type of application/json.  The request works fine with Interceptor switched off.  When I switch on Interceptor then the request hangs indefinitely.  I am using Interceptor because I want to view any cookies returned by the server.  Can anyone suggest an alternative way of grabbing the cookie returned by the server following the Postman request?  Thanks.

**Comment by abhijitkane** [comment]
@davehickson Can you try disabling and re-enabling the Interceptor from chrome://extensions and see if that helps?
If not, are there any errors in the Postman console - http://blog.getpostman.com/2015/06/13/debugging-postman-requests/?

**Comment by dave-hickson** [comment]
Disabling and enabling the extension in Chrome did the trick!  Many thanks.
