### ISSUE TITLE
Can't access cookies from native mac app inside Chrome

### ISSUE THREAD

**Issue by nadim** [a85/POSTMan-Chrome-Extension#1955]
Cookies aren't shared between the native mac app and Chrome. I've tried using interceptor for this and enabled the toggles in both interceptor and the native mac app:

Interceptor:
![image](https://cloud.githubusercontent.com/assets/24093/14187797/ffe4f2d0-f741-11e5-97fb-f5820133e06e.png)

Postman Native Mac App:
![image](https://cloud.githubusercontent.com/assets/24093/14187882/6b5c8d70-f742-11e5-84f1-c836b6d649ef.png)

Everything works fine with the Chrome packaged extension, but I prefer the native app due to the weird `⌘-Tab` / `⌘-`` behaviour in Chrome on OS X: https://bugs.chromium.org/p/chromium/issues/detail?id=339239

**Comment by a85** [comment]
Sorry. Cookies are not supposed to be shareable between the Mac app and the Chrome app. We can build a bridge somehow between them but it's not easy. I'd recommend managing cookies within the Mac app. The toggle in the Mac app is for the proxy. We should change this to avoid confusion though.
