### ISSUE TITLE
GUI issue - pointer problem in "body -> raw" section

### ISSUE THREAD

**Issue by toanqc** [a85/POSTMan-Chrome-Extension#1956]
Hello,
Thanks for the great work. I have an issue with the pointer location when I try to write json by myself in the raw section of the body.

For example, I have the following line:
`{
emailBody: "Customer Services Comments and Questions"
}`
When I come to this line and press `End` key. The pointer is jumped into the middle of `n` and `s` of the word `Questions` instead of end of the line and after that I press the `Backspace` then it's actually delete the `s` characters which is fine. But it would be hard if you want to delete some other characters in the middle of the sentence.

Please see the screenshot for more detail
![alt text](http://imgh.us/postman_pointer_issue.png)

P/S: My system
Postman: 4.1.3
linux / x86-64
Chrome 49.0.2623.110

**Comment by abhijitkane** [comment]
@toanqc Are you still seeing this with v4.4.1 of the app?

**Comment by toanqc** [comment]
@abhijitkane : Yes, I just try it today and still have the same issue on v.4.4.1

**Comment by abhijitkane** [comment]
@toanqc How about at https://ace.c9.io/? Ace is the editor we use for our raw body component.

**Comment by toanqc** [comment]
@abhijitkane : oh right, seem like this is the ace editor issue. I have the same problem on Chrome but not Firefox on RedHat 6.7

**Comment by numaanashraf** [comment]
@toanqc Are you still facing this issue in versions 4.7 and up?

**Comment by toanqc** [comment]
@numaanashraf I can't test right now, no longer using RedHat 6.7
