### ISSUE TITLE
Issue with Data driving [Postman & Newman]

### ISSUE THREAD

**Issue by rnair32** [a85/POSTMan-Chrome-Extension#1957]
[Raising as mentioned by Abhinav Asthana]

Web service under test:

METHOD:POST
Request:
{
"levelDataList":"level":1,"value":"INDIA"}]
}

**_My Aim is to use the same as_** - > "levelDataList":[{"level":"{{Level}}","value":"{{Country}}"}]

I am trying to data drive the testing with CSV file with different values for Level & Country. I have created a CSV file with 8 possible combinations in UTF-8 (Using Sublime). CSV created is attached for reference.

I am facing 2 issues - One with Collection Runner and other with NewMan. 

**Collection Runner** - CSV preview is fine and no issues observed. While running from Collection runner, only first scenario is executed and others are not. I.e the test is executed with the first set of data (Both data variable mentioned is substituted with the data provided in the CSV). I am not able to use data['Level'] or data.Level since it's not getting substituted and taken as is. Tried with JSON instead of CSV and observed same behavior.

**NewMan** - With NewMan, same script is running for n times where n is the no of rows in my CSV file - which is my expectation. But issue is only {{Level}} is substituted while {{Country}} is taken as is.

Could you kindly look into the same and advice ?

[Reference.zip](https://github.com/postmanlabs/postman-app-support/files/199020/Reference.zip)

Regards,
RRN

**Comment by rnair32** [comment]
In Newman, all values are substituted and working fine with JSON instead of CSV.

**Comment by abhijitkane** [comment]
@rnair32 
Can you import this collection - https://www.getpostman.com/collections/1a2082643774af380c63
and this CSV: https://gist.githubusercontent.com/abhijitkane/4ad9630b60bd48c12ef691df047067e9/raw/1382cb5b7fe599cb1fceefa15151ea7efcafd2f0/data.csv

Run this in the runner setting Iteration: 4. All 4 tests should pass.

**Comment by rnair32** [comment]
In my scenario, the variables needs to be substituted in body. Will you be able to import the reference (Attached in issue) and advice ? Also a few queries:

1) We need to specify Iterations in order to execute with different data set ? I.e if my CSV contains 50 data combinations, then should i specify 50 as Iteration or will it run depending on the no: of rows in CSV ?
2) How can we access the CSV values using data i.e data['Level'] or data.Level. Will you be able to include few sample in my body script

Thanks in advance.

**Comment by abhijitkane** [comment]
Yes, you'll need to specify 50 in the iteration field to run 50 iterations (even if the CSV file has 50 rows).

In the test script or pre-request script, `data.Level` and `data['Level']` will both work. 

The CSV file I sent was a modified version of your file. The `\n` in the CSV file might cause problems while parsing.

**Comment by rnair32** [comment]
Thanks for the quick support. I will re-check and get back to you.

**Comment by krishna6100** [comment]
I am facing the same issue with .csv files, but with .json data file it is working fine. I also given the number of iterations provided from the entries in the .csv file.
Can anyone help me on this ?
