### ISSUE TITLE
Importing your own link should add a collection that will continue to sync to that link

### ISSUE THREAD

**Issue by prusswan** [a85/POSTMan-Chrome-Extension#1958]
Right now if the collection is deleted (but not the link associated with it), there is no way to reuse that link url, even for other collections belonging to the same user.

**Comment by a85** [comment]
I don't see the need for this. The collection ID is dependent on the collection. A new API will let users manage collection links more easily pretty soon.

**Comment by prusswan** [comment]
Not sure if you understand. The problem is that if I delete the collection locally by mistake, I can't restore it by importing the link and keep it synced with that link, so the link becomes useless as well.
