### ISSUE TITLE
Pretty output sorts Json

### ISSUE THREAD

**Issue by jonathanmorr** [a85/POSTMan-Chrome-Extension#1959]
The "Pretty" output of a received JSON orders the elements from low to High. I tested the order function i implemented in my code and thought it would not work, but in "Raw" mode the elements are ordered as expected. There should be an option to let the user choose if the results in "Pretty" mode should be reordered.

**Comment by abhijitkane** [comment]
@jonathanmorr Can you give an example of a raw response for which the pretty view is ordered differently?

**Comment by jonathanmorr** [comment]
Hi!

Sorry for the late reply, i dont check my emails every day. You can see it
if you make a get request to our API. I created you an apikey with the
rights to retrieve some fake apps.
Request GET

https://v25-stage.app-arena.com/api/v2/apps?exclude=all&orderdesc=appId

with a header entry 'Authorization' => 9KaeDYdeku53DWHSSMqF and you will
see that in the raw output app 11511 is the first entry while in pretty
output it is 11509.

Jonathan

2016-04-26 14:54 GMT+02:00 Abhijit Kane <notifications@github.com>:

**Comment by jonathanmorr** [comment]
This is the ouput of a request, ordered by 'appId' descending. 

![requestexample](https://cloud.githubusercontent.com/assets/16762981/14879098/7c86702a-0d27-11e6-8ac9-7f12dab752f6.png)

The Raw (or Preview) output is in the right order while the pretty shows a ascending order.

**Comment by abhijitkane** [comment]
@jonathanmorr Hm..we're using JSON.parse to beautify the JSON. Since the order of keys isn't guaranteed (http://stackoverflow.com/a/5525820/384155), there's not much we can do here.

`JSON.parse('{"11511":1,"11500":2}')` returns `Object {11500: 2, 11511: 1}`

Closing this as non-actionable.
