### ISSUE TITLE
Import Swagger and Update Collection

### ISSUE THREAD

**Issue by bsapot** [a85/POSTMan-Chrome-Extension#1960]
I have a collection that was created from a swagger import. As services are added I would like the ability to re-import the swagger file and have it add the new services. This a possibility?

**Comment by abhijitkane** [comment]
@bsapot If you have not renamed the collection after importing, you should see a 'replace/copy' option when you re-import the Swagger file. Choosing replace will add the new services.

**Comment by mmercan** [comment]
Replace option not just only adding the new services it also override old ones like removing all tests added is it possible to keep tests or just add the new services ?

**Comment by neowood** [comment]
Same question, how to keep tests when importing?
