### ISSUE TITLE
Add application/graphql in headers dropdown

### ISSUE THREAD

**Issue by joanrodriguez** [a85/POSTMan-Chrome-Extension#1964]
There is already an issue here: https://github.com/postmanlabs/postman-app-support/issues/1669

I suggest to simply add "application/graphql" in the content-type dropdown of POST requests as a quick win for the time being

**Comment by abhijitkane** [comment]
@joanrodriguez  Are you talking about the auto-complete list for header values?

**Comment by joanrodriguez** [comment]
Yes

On 26 avr. 2016, at 04:27, Abhijit Kane <notifications@github.com<mailto:notifications@github.com>> wrote:

@joanrodriguezhttps://github.com/joanrodriguez Are you talking about the auto-complete list for header values?

**Comment by abhijitkane** [comment]
@joanrodriguez Got it. Will include this in the next release.

**Comment by abhijitkane** [comment]
@joanrodriguez Added in v4.2.1
