### ISSUE TITLE
can't avoid following redirects in Mac app

### ISSUE THREAD

**Issue by emattheis** [a85/POSTMan-Chrome-Extension#1967]
With the Chrome app and the interceptor plugin there was the option to avoid automatically following redirects. This is great for validating API responses that are expected to result in a redirect. Unfortunately, it doesn't seem to be an option in the standalone Mac app.

**Comment by abhijitkane** [comment]
@emattheis
Agree. The XHR object auto-follows redirects. We're trying to work around this, but it's still at an experimental stage.

**Comment by abhijitkane** [comment]
@emattheis We've released 'Postman Canary' for Mac which has a setting to let you control this behavior - https://www.getpostman.com/app/postman-osx-canary.

We'll soon be releasing this in the production Mac app.
