### ISSUE TITLE
[Request] Summary from Node.js invocation

### ISSUE THREAD

**Issue by aqyblitz** [a85/POSTMan-Chrome-Extension#1968]
I was wondering if it was possible to have the nice folder-based summary results that the command-line invocation of Newman (newman -c collectionname ...) generates printed to stdout & captured in the output file from the Node.js invocation (aka Newman.execute(....)).

I'm not sure if this is a feature yet or not, but nothing turned up when I dug through the source. I could always manually generate the result summary, but I'm wondering if it's already implemented and I missed it when looking through the repo.

**Comment by abhijitkane** [comment]
@aqyblitz Newman supports exporting reporter output (https://www.npmjs.com/package/newman). Also, if you're using the CLI reporter, you can pipe stdout directly to a file.
