### ISSUE TITLE
Can't disable prompt to save on Mac

### ISSUE THREAD

**Issue by ghost** [a85/POSTMan-Chrome-Extension#1969]
Hi,

this bugs me as this use to be a feature but whenever i modify one of my saved requests to alter parameters it marks the tab as altered. 
This means that whenever i click on another stored request it auto opens a new tab and whenever i close a tab that is altered i have to click 'don't save' every time. I used to be able to disable in settings when i was using windows but i have not been able to find an equivalent setting for mac. This is time consuming, please fix this/tell me how i can fix this myself

**Comment by ArunMonySpin** [comment]
I had also reported the issue on your twitter channel, and was promised a fix pretty soon, but it has been a month already. Why remove something which gives an option to the users ?  I mean why remove a feature which was already there ? Honestly this bug is irritating to me to the extent that I have started to explore for postman like tools.

**Comment by aditikul** [comment]
@cpotter91 @ArunMonySpin We've added shortcuts that should help speed up the flow for the save modal. Enter to save, esc to cancel and space for "don't save." Please update to the latest version and let me know if it works for you. Thanks.

**Comment by ArunMonySpin** [comment]
I am not sure, how is this going to help much.  I basically want the options in the settings page via which I can tell postman to open only one request window at a time and discard the previous window regardless of whether it has changes pending or not.   

Thanks,
Arun Mony
Head Of Engineering
http://getspini.com

+91-963-282-9988

**Comment by a85** [comment]
I don't think we'll have that option. The reason for that is pretty simple and I am not sure why this is so hard to understand: discarding changes automatically makes people lose their fucking work. Go through other issues on the tracker here to see the scope of the problem before demanding features.

We'll look at other flows but I am closing this issue right now.
