### ISSUE TITLE
How do I parse html to json?

### ISSUE THREAD

**Issue by alowenst** [a85/POSTMan-Chrome-Extension#1970]
Hello!!

Is it possible to transform an html response to json and run tests on it? I couldn't find anything around this item.
There are some references saying "yes, you can do it" but nothing beyond that.. 

Thanks!

**Comment by mstaalesen** [comment]
Could you show some examples on what you need to parse?

Perhaps: http://stackoverflow.com/questions/12980648/map-html-to-json can help you?

**Comment by alowenst** [comment]
I have a very simple HTML that returns from one of our Spark applications. it just has application IDs, state, number of workers etc. very straightforward and simple. here's the sample file - [spark-dashboard.txt](https://github.com/postmanlabs/postman-app-support/files/205852/spark-dashboard.txt)

what i'm interested here is the "Running Applications" and "Workers" sections, all columns.
hope this helps.

Thanks

**Comment by abhijitkane** [comment]
@alowenst You can try xml2Json (https://www.getpostman.com/docs/postman/scripts/postman_sandbox) if the response is well-formed XML.

If not, you'll need to write custom code to parse HTML.
