### ISSUE TITLE
Content-Length header must be manually deleted after content changes

### ISSUE THREAD

**Issue by jhalterman** [a85/POSTMan-Chrome-Extension#1971]
Edited this issue based on @czardoz's clarification:

After changing the content for a request, such as form params, the content-length header (if one exists), must be manually deleted before sending the request so that one can be recreated.

It would be much better if `content-length` was auto-generated after changing request arguments. Similarly, though unrelated, it would be great if AWS auth changes were automatically reflected without having to hit `update request`.

**Comment by czardoz** [comment]
Content length is recalculated when the request is sent, so you shouldn't not have to hit the update request button at all :)

**Comment by jhalterman** [comment]
Edited

@czardoz It looks like a content-length header is added, but only if one doesn't exist. So each time the content is changed, you have to manually delete the header before making your request or hitting `update request`.

**Comment by jhalterman** [comment]
...it might help to make this issue a bit more broad. Really, it would be nice if headers were automatically updated without having to delete them. Another place this comes up is when I open a saved request, I have to hit the `update request` button to generate a new `X-Amz-Date` header.

**Comment by abhijitkane** [comment]
@jhalterman - we've fixed the content length issue in our internal build, and will push out the fix in the next release. 
@czardoz Also being tracked at Zendesk#4392

**Comment by abhijitkane** [comment]
@jhalterman Can you confirm this fixed in the latest version of the app?

**Comment by jhalterman** [comment]
Tried it - looks good 👍
