### ISSUE TITLE
Collection items cannot be ordered properly

### ISSUE THREAD

**Issue by pellicano** [a85/POSTMan-Chrome-Extension#1972]
I cannot order by name items inside a collection.

**Comment by abhijitkane** [comment]
@pellicano You can manually drag-and-drop requests to change the order.  The 'sort by name' is only for collections. Postman cannot (and should not) automatically change the order of requests in a collection.

**Comment by pellicano** [comment]
So, "cannot (and should not) is a requirement? There's a possibility to
even consider add sorting request by its names in future?

Thanks.

Em segunda-feira, 25 de abril de 2016, Abhijit Kane <
notifications@github.com> escreveu:

> @pellicano https://github.com/pellicano You can manually drag-and-drop
> requests to change the order. The 'sort by name' is only for collections.
> Postman cannot (and should not) automatically change the order of requests
> in a collection.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/postmanlabs/postman-app-support/issues/1972#issuecomment-214586459

## 

Regards,
Marcelo Pellicano de Oliveira.

**Comment by abhijitkane** [comment]
Not till there's a way to revert changes. Accidentally clicking sort-requests-by-name could mess up the entire collection.
And then users would expect auto-sort-on-rename etc, and a slew of other features. Not marking this as a feature request for now.

**Comment by pellicano** [comment]
I see your point, but why collections can be "messed up" by the current
order button and requests not?
Another point that I see: what's the average number of collections users
normally have? For example, I don't see this been useful for ordering 5
collections but I do see usage for ordering 20/30 requests within each
collection.
Users may expect auto-sort-by-name depending on their UX.
Anyways, this is my opinion.

Thanks Abhijit. Have a great week for you guys!
BTW: awesome tool! Thanks again!

=)

Em segunda-feira, 25 de abril de 2016, Abhijit Kane <
notifications@github.com> escreveu:

> Not till there's a way to revert changes. Accidentally clicking
> sort-requests-by-name could mess up the entire collection.
> And then users would expect auto-sort-on-rename etc, and a slew of other
> features. Not marking this as a feature request for now.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/postmanlabs/postman-app-support/issues/1972#issuecomment-214587708

## 

Regards,
Marcelo Pellicano de Oliveira.

**Comment by bgraw3** [comment]
What about the ordering of folders in a collection? It is obviously by name. It would be nice to be able to manually order them. Or, is there a suggestion on naming?

For example, we have folders "Purchase Numbers, Routing Number, Tracking Numbers." We've had to rename them like "Number | Purchase, Number | Routing, Number | Tracking" to keep them grouped. I really don't want to number or letter them.

 I've seen some questions regarding subfolders. That might help, too.

**Comment by a85** [comment]
@bgraw3 We are working on manual reordering + multiple folders.

**Comment by gregorypease280** [comment]
Postman should have the ability to sort requests in a collection. Preferably as an action selectable from a dropdown menu(The collection sort works fine).

**Comment by abhijitkane** [comment]
@bgraw3 The latest versions of the app support custom folder orders.
@gregorypease280 On Postman, the order of requests changes the way the collection runs for all users of the team - we aren't considering automatic ordering of requests at the moment.
Closing this for now.
