### ISSUE TITLE
Raw Response Headers

### ISSUE THREAD

**Issue by winkelsdorf** [a85/POSTMan-Chrome-Extension#1973]
Hi,

Postman is great! The only thing I really miss is: Raw Response Headers.

Don't get me wrong, presenting them with those arrows is nice. But I am really used to see plain text. For me it takes more time to get through this visually nice list than having a bunch of raw headers.

Feature request: Add showing raw response headers :)

Cheers,
Frederik

**Comment by RobWin** [comment]
+1

**Comment by roeschjohannes** [comment]
Hi Frederik,

couldn't you use "request.headers"?

Regards,
Johannes

**Comment by winkelsdorf** [comment]
Hi Johannes,

you likely mean _"response.headers_", don't you? This feature request is about the _response_ headers. 

What I am asking for is a raw display in the response panel, as this large line spacing and the arrows make it slower _for me_ to see the information I'm looking for. At least if you're used to see the headers in plaintext in your browser, console (curl) etc, you'll know what I'm talking about.

See this picture:
![screenshot_2016-04-21_10_03_00](https://cloud.githubusercontent.com/assets/1413291/14701986/60ec4bc0-07a8-11e6-967e-22e104934571.png)

I'd love to see a button "Raw Headers" next to "Headers".

Like curl in the console does:
![screenshot 2016-04-21 10 14 44](https://cloud.githubusercontent.com/assets/1413291/14702289/e99ad648-07a9-11e6-8536-41b792feed52.png)

Please point me to some UI option, if I'd missed something.

Regards,
Frederik

**Comment by roeschjohannes** [comment]
Ok. I understand. Yes you are right. That would be a nice Feature.

**Comment by winkelsdorf** [comment]
No problem, already thought that this was just a misunderstanding!

Glad, so that's 3 upvotes now :)

**Comment by abhijitkane** [comment]
@aditikul Might make sense to add a pretty/raw option in the response headers as well. Pretty shows the current UI, Raw shows a textarea with the raw response headers.

**Comment by lukeholder** [comment]
This is a big 👍  from me. I use postman to test a request and then copy the response into a mock text file I load during automated tests in my php code. Being able to copy all the headers at once would be a huge time saver.

**Comment by aditikul** [comment]
@abhijitkane Ok adding to the roadmap.

**Comment by rafaelnobrepd** [comment]
This would be a really good addition to the already excellent postman app! I'm also using postman to save stubbed API responses and the raw headers would be super useful.

**Comment by udev** [comment]
+1 for raw response headers!

**Comment by LnsooXD** [comment]
It's very useful for showing a raw HTTP head.

**Comment by jcavalieri** [comment]
👍

**Comment by udev** [comment]
Kind of related... I had a request a while back for a "publish gist" feature. It got shut down without much discussion and the closing comment didn't particularly acknowledge the feature request. Even just having the raw headers would be a nice improvement.

https://github.com/postmanlabs/postman-app-support/issues/2834

**Comment by syntheticzero** [comment]
+1

**Comment by mnannola** [comment]
+1.  Would love to have an easy way to copy the headers out in plain text.  Better yet, an easy way to view the entire response, including headers,  in one section.

**Comment by sdnts** [comment]
Guys, we're working on something that should ease out this use case. I'll let you guys know when we push it to our Canary and stable channels :)

**Comment by TheRealMilagro** [comment]
this would be great. I also need to see the full raw http-request AND response. The only way i know which is near what i want is the postman-console (alt+ctrl+c). But unfortunately it also show request/response in kind of a pretty view, esp. if response is json. Please add possibility to switch into a raw-display mode as well. Thank you :)

**Comment by foaadnami** [comment]
+1

**Comment by a85** [comment]
The full HTTP transaction is available in the Postman console in the desktop apps now. Closing this issue!

**Comment by winkelsdorf** [comment]
@all Thanks for all the support and the countless thumbs up for this request!

@a85 A big thank you for implementing it 🥇

**Comment by Vegapa** [comment]
how do i check for the value of the response headers by writing test case is postman?

**Comment by gerektoolhy** [comment]
P.s. There is a 'raw' and 'pretty' tabs in postman console. `Raw` will give full request/response data unmodified.

**Comment by ahdung** [comment]
@a85 Desktop app can't intercept, need this feature on chrome app, please reopen.

**Comment by rulatir** [comment]
What is implemented is poor substitute for the desired functionality: we want to be able to one-click export the headers in a machine-processable, properly delimited key-value format like CSV.
