### ISSUE TITLE
Better support for matrix parameters in GET

### ISSUE THREAD

**Issue by JohnPelletier** [a85/POSTMan-Chrome-Extension#1974]
I can't seem to find a way to use matrix parameters in a nice readable format like the query parameters have. I love Postman, but without that easy-to-read feature for matrix parameters, it will be hard for me to use this tool for anything in our API. Seems like it would be easy to add, just put a semicolon instead of the original "?", and don't insert &'s in the formatting.

For example, for matrix params such as resolution=YEAR and electricity=KWH:
GET /api-bridge-service/building-model/simulation;resolution=YEAR;electricity=KWH;  HTTP/1.1
Host: api-bridge-service-dev.useast.tni01.com
Content-Type: application/json
Tenant-Id: 9
Authorization: Basic ZWblahblahXOXOXOXO
Accept: application/json
Accept-Encoding: gzip, deflate
Cache-Control: no-cache
Postman-Token: abcdefabcdef-2d39-c346-2ccd-12345678900

**Comment by a85** [comment]
Closing this as we haven't seen traction on this feature request. We are working on modularizing Postman to support plug-ins using which this feature can be built.
