### ISSUE TITLE
Accompany changelog with release dates

### ISSUE THREAD

**Issue by davenewza** [a85/POSTMan-Chrome-Extension#1975]
The changelog available [here ](https://www.getpostman.com/apps#changelog-chrome-app)doesn't indicate when these features and updates were released. 

This is handy for developers who find themselves having to troubleshoot strange bugs. Always check if your software or tools have updated!

**Comment by aditikul** [comment]
@davenewza We're working on this and should be posting an update pretty soon. Thanks for reporting the issue.
