### ISSUE TITLE
Runner - delay between collection iteration

### ISSUE THREAD

**Issue by ohadmuch** [a85/POSTMan-Chrome-Extension#1978]
Hi.
I'm using the OS X app.
In the Runner I can set a delay between the collection requests calls, it's great but I want another delay configuration for the whole collection iteration.
So if I have 3 requests in the collection with delay of 10 seconds between them,  I want that when all 3 are finished to start the next iteration of the collection in delay of 1 minute.

Thanks.

**Comment by abhijitkane** [comment]
@ohadmuch
For now, you can add a single request to httpbin.org/delay/10 to the end of the collection for a 10 second delay. We're working on a new collection format which should enable this.

**Comment by shamasis** [comment]
@a85 present in runtime already.
