### ISSUE TITLE
Didnt pull up the whole collection on subscription

### ISSUE THREAD

**Issue by tahakarimagcocorp** [a85/POSTMan-Chrome-Extension#1979]
I have 83 requests in my collection but it failed to pulled it out, only showing 9 request, I did unsubscribe my collection and restart postman several times but it didn't work 
Please if anyone have any suggestions it would be appreciated 

Thanks 

Taha

**Comment by abhijitkane** [comment]
@tahakarimagcocorp Can you send us an email at help@getpostman.com with your username and Postman version?

**Comment by abhijitkane** [comment]
Followed up on email. Closing issue.
