### ISSUE TITLE
PUT request only works with first version with of postman

### ISSUE THREAD

**Issue by thomasvdbossche** [a85/POSTMan-Chrome-Extension#1982]
I have installed both the first version of postman (https://github.com/postmanlabs/postman-app-support/wiki) and the latest as a chrome extension. After importing my collection, all requests work normally, except for the PUT request, for which I receive a 404 error. All settings (headers, URI, parameters) are identically. 

Since the URIs are confidential, I cannot post them here.

**Comment by abhijitkane** [comment]
@thomasvdbossche Are you able to make a PUT request to http://echo.getpostman.com/put?
Does the imported PUT request work through cURL?

**Comment by thomasvdbossche** [comment]
A PUT request to http://echo.getpostman.com/put works.
However, the PUT request through cURL gives also throws a 404..

Op 8 april 2016 bij 22:40:52, Abhijit Kane (notifications@github.com) schreef:

@thomasvdbossche Are you able to make a PUT request to http://echo.getpostman.com/put?
Does the imported PUT request work through cURL?

**Comment by abhijitkane** [comment]
Is some sort of authentication required? You might need to use the Interceptor - http://www.getpostman.com/docs/interceptor_cookies

**Comment by abhijitkane** [comment]
@thomasvdbossche Did the Interceptor help?
If the Interceptor is off, you can check the Network tab (http://blog.getpostman.com/2015/06/13/debugging-postman-requests/) for more info on the 404.

**Comment by SamvelRaja** [comment]
@thomasvdbossche Closing this now. Kindly open this if you need to anytime 😄
