### ISSUE TITLE
Requests in collection strangely disappeared

### ISSUE THREAD

**Issue by piglei** [a85/POSTMan-Chrome-Extension#1984]
Some saved requests disappeared in my collection, but the number is still correct(I assume).

![screen shot 2016-04-12 at 10 09 52 am](https://cloud.githubusercontent.com/assets/731266/14447914/c21768f8-0096-11e6-893b-254ada99e920.png)

Only 12 requests in list but the number says "20 requests".

**Comment by abhijitkane** [comment]
@piglei Can you try signing out and signing back in? We're looking into how this may have happened.

**Comment by piglei** [comment]
@abhijitkane  This missing requests showed up after signing out and signing back in.

Thanks.

**Comment by RandolphBurt** [comment]
I had the same issue.  I use Postman on multiple machines so this may be a contributing factor.  However, logging out and then signing back in solved it so all is good. :)  Cheers.
