### ISSUE TITLE
Get Collection URL is not working

### ISSUE THREAD

**Issue by rbawachkar610** [a85/POSTMan-Chrome-Extension#1985]
When we click on Share >> Get Link for particular collection, it will show "Fetching Link" ....

but nothing happens after that. We can not see link generated for this collection.

pls help us to sort out this. we need collection link, in order to run the APIs in Newman.

**Comment by rbawachkar610** [comment]
![postman_get collection link](https://cloud.githubusercontent.com/assets/18414034/14451810/9b082f8e-00a7-11e6-9b50-4306a914fe57.jpg)

**Comment by abhijitkane** [comment]
@rbawachkar610 We're looking into why this might be happening. Can you try restarting your app and then trying?

**Comment by rbawachkar610** [comment]
Already tryout with restart option. problem is still there after restart.

**Comment by abhijitkane** [comment]
@rbawachkar610 Can you check the Network tab in the DevTools window and send a screenshot? (http://blog.getpostman.com/2015/06/13/debugging-postman-requests/)

**Comment by rbawachkar610** [comment]
![dev tool](https://cloud.githubusercontent.com/assets/18414034/14483969/24624d10-016a-11e6-825f-5e2f93a8052f.jpg)

**Comment by abhijitkane** [comment]
@rbawachkar610 How about the Console tab (instead of Network)?

**Comment by rbawachkar610** [comment]
![console tab](https://cloud.githubusercontent.com/assets/18414034/14520665/5ca1e8b4-0243-11e6-9389-3111dc4d4188.jpg)

**Comment by abhijitkane** [comment]
@rbawachkar610 How many requests exist in the collection? Can you try duplicating the collection and sharing that?

**Comment by kgarber** [comment]
When I look at the network, I see that I get a 413 Request Entity Too Large.  There are some requests that are quite large, like passing 10k objects in a json.  Is there any work around for this?

**Comment by abhijitkane** [comment]
@kgarber No, we have a limit on our server which prevents large amounts of data from being saved. You could try splitting your collection into 2-3.

**Comment by roquie** [comment]
For large saved responses problem still available. Postman application shows message when I save ~35k rows and (!!) saves it. I remove the saved response, sharing collections work successful now.

May be grant access edit response before user save it?
