### ISSUE TITLE
Collections pointing to localhost:8080 no longer working

### ISSUE THREAD

**Issue by TheIcemanCometh** [a85/POSTMan-Chrome-Extension#1986]
We use a series of collections in Postman Cloud, and we use environment settings to easily switch between environments, to include local development machines using localhost:8080.  On Friday this past week, my collections completely stopped working when pointing to localhost:8080 although they work fine when pointing to other environments.  The same collections appear to work fine for others - the issue appears to be with me for some reason.  

What appears to be happening is the requests aren't even getting "out" of Postman to hit the servers, as I don't get an HTTP error code.  The error I get looks something like this:  
## Could not get any response

This seems to be like an error connecting to {url}.
### Why this might have happened:
- The server couldn't send a response:  Ensure that the backend is working properly
- Self-signed SSL certificates are being blocked: Fix this by turning off 'SSL certificate verification' in Settings > General
- Request timeout: Change request timeout in Settings > General

If I take the {url} presented in the error message and submit the same request using curl, everything works fine, so I know the local server is up and running.  I have also enabled the DevTools, and when I submit a request, it is red under the Network tab, and the response tab on the right pane shows "Failed to load response data".

I have tried exporting and importing, tried the standalone Mac app, restarting my machine, etc. - all to no avail.

I am literally at a standstill with this issue and can't use Postman to test my local changes.  If I use other third party add-ons they work fine, but since we're so heavily invested in Postman for our testing setup, that's not really a viable option.  I have also verified the suggested settings in the error message, and they have no effect.

**Comment by abhijitkane** [comment]
@TheIcemanCometh Can you attach a screenshot of the DevTools' Network tab? 
Also, are there any errors in the DevTools' console?

**Comment by TheIcemanCometh** [comment]
![screen shot 2016-04-12 at 8 24 02 am](https://cloud.githubusercontent.com/assets/1135824/14459782/f5d8a63e-0087-11e6-8381-44e3ed9bf0c7.png)
![screen shot 2016-04-12 at 8 23 34 am](https://cloud.githubusercontent.com/assets/1135824/14459781/f5d62d32-0087-11e6-81a2-2e008fbb7082.png)
![screen shot 2016-04-12 at 8 24 47 am](https://cloud.githubusercontent.com/assets/1135824/14459794/0da6e492-0088-11e6-9d6b-78fbd36a14af.png)

**Comment by abhijitkane** [comment]
How about the Headers tab (instead of Response)?

You can try installing Chrome Canary (https://www.google.com/chrome/browser/canary.html) and install Postman there.

**Comment by TheIcemanCometh** [comment]
![screen shot 2016-04-12 at 8 26 25 am](https://cloud.githubusercontent.com/assets/1135824/14459874/8aabcebc-0088-11e6-8f10-458102f579df.png)

**Comment by TheIcemanCometh** [comment]
I tried installing Canary, and while it does install, it crashes every time I try to start it.  I have also tried uninstalling and reinstalling Chrome itself and that does not seem to have affected anything either.

**Comment by TheIcemanCometh** [comment]
Any updates here?  Is there any other information I can provide for troubleshooting purposes?

**Comment by TheIcemanCometh** [comment]
OK, some further troubleshooting.  I completely uninstalled and re-installed Chrome and that had no effect.  If I paste a test URL into the Chrome browser, I get the following error page:

## The localhost page isn’t working

### localhost didn’t send any data.

ERR_EMPTY_RESPONSE

whereas is I do the same in Firefox, I get an error response from my application like I would expect.

The only thing that **does** appear to work is using another port, like 8181.  If I switch to that, everything works great.  This is a "hack" to get around the issue, but there is definitely something going on here ... and it looks like it's related to Chrome.

**Comment by abhijitkane** [comment]
@TheIcemanCometh Can you disable all Chrome's extensions from chrome://extensions/, and see if that helps?
