### ISSUE TITLE
{{$timestamp}} doesn't work well in request body

### ISSUE THREAD

**Issue by GabbyChangSH** [a85/POSTMan-Chrome-Extension#1987]
While I use "postingDate" : "{{$timestamp}}" in the request body, it pops error message with "Invalid format: \"1460526578\" is malformed at \"8\"". Why timestamp returns 1460526578?

**Comment by abhijitkane** [comment]
@DaisySu Can you try sending a POST request to http://httpbin.org with this payload:

```
{
    "postingDate" : "{{$timestamp}}"
}
```

Screenshot attached.
<img width="850" alt="screen shot 2016-04-13 at 13 31 03" src="https://cloud.githubusercontent.com/assets/681190/14486724/1ccbfada-017c-11e6-95ae-451e6b4c18fb.png">

**Comment by GabbyChangSH** [comment]
Yes, I have send it. And it return the data as your screenshot. But I don't understand what to do to resolve this issue.
![image](https://cloud.githubusercontent.com/assets/17960591/14488056/d28c7f54-0198-11e6-8dc8-6cdf32a9804e.png)

**Comment by abhijitkane** [comment]
@DaisySu $timestamp is supposed to return the current time in the Unix timestamp format (http://www.getpostman.com/docs/environments)

Where are you seeing the "malformed" error? If it's in the server response, you might need to check the server logs, and confirm what the server expects.

**Comment by GabbyChangSH** [comment]
Yes, it's server response. The server accept format including "2016-03-27T16:00:00.000Z", "2016-03-27". That means I should convert the $timestamp to the above format before using in the request body.

**Comment by abhijitkane** [comment]
That's correct - we include SugarJS in the sandbox (http://sugarjs.com/dates), which should let you convert between formats easily.

**Comment by GabbyChangSH** [comment]
OK, Thank you very much.

**Comment by mverma-va** [comment]
@abhijitkane I am new to javascript, can you tell me how to convert the $timestamp from milliseconds to this format "2017-11-26T17:02:26Z" within the request body?

**Comment by mverma-va** [comment]
I got the solution, thanks for sharing sugarjs info.
var temp1 = new Date();
var temp2 = new Date().rewind({hour: 1});
pm.environment.set('iso1', (temp1).toISOString());
pm.environment.set('iso2', (temp2).toISOString());

**Comment by WilliamToro** [comment]
can i have a negative timestamp in postman?
