### ISSUE TITLE
Not possible to move a request to the bottom of a folder

### ISSUE THREAD

**Issue by mstaalesen** [a85/POSTMan-Chrome-Extension#1988]
Currently it is not possible to move a request to the bottom of the folder that it is currently residing in. The only way of doing it is to move it to the second to last from the bottom and then moving the item at the bottom above it:

![animation7](https://cloud.githubusercontent.com/assets/14194793/14490204/cdc6715e-0171-11e6-90e9-2f1f27cd3805.gif)

**Comment by numaanashraf** [comment]
@mstaalesen Hey! Thanks for reporting this. We are looking into this.

**Comment by vegetableman** [comment]
The issue has been fixed for a while. Closing this. Feel free to reopen if this still still exists.
