### ISSUE TITLE
Selecting text in "Edit Folder" and dropping the mouse outside the Dialog closes the window

### ISSUE THREAD

**Issue by mstaalesen** [a85/POSTMan-Chrome-Extension#1989]
If you try to edit a folder, or a request and select all the text with the mouse and then release the click of the mouse outside the dialog box for "Edit folder", the dialog box will close itself.
This does not happen as long as the mouse is released inside the dialog box itself:

![animation6](https://cloud.githubusercontent.com/assets/14194793/14490246/114c22de-0172-11e6-90f4-d5933a2b783c.gif)

**Comment by abhijitkane** [comment]
@mstaalesen This is fixed in the latest version - thanks for reporting this.
