### ISSUE TITLE
Pushing changes in team collection to collection URL link only possible for owner

### ISSUE THREAD

**Issue by jonasa84** [a85/POSTMan-Chrome-Extension#1990]
Hi,

Our team has a team collection with API tests that we run in newman by specifying the collection url.

The problem is that if any team member makes changes to the collection, these changes aren't reflected in the file downloaded from the url. And only the owner of the collection can push the changes to the file by clicking Share -> Update link. This option is not available for the rest of the team.

Is this how it's supposed to work or are we missing something? We would like for all members of the team to be able to push the changes to the file.

**Comment by abhijitkane** [comment]
@jonasa85 - Currently - yes, only the owner can update the link. We'll soon be releasing a Cloud API, which will remove the need to use getpostman.com/collection style links. You'll have a link that is always up-to-date.

**Comment by jonasa84** [comment]
Ok sounds great, thx.

**Comment by a85** [comment]
The Cloud API is out now! Check out docs at https://api.getpostman.com
