### ISSUE TITLE
Add warning message when trying to set a header "Cookie" or "cookie".

### ISSUE THREAD

**Issue by grifx** [a85/POSTMan-Chrome-Extension#1994]
Hey guys,

Could we add a warning when using a header with the key: "Cookie" or "cookie"?
It's not explicit at all that we should use the interceptor while sending the request.

Thanks

**Comment by a85** [comment]
There are lots of flows that intersect with this and we haven't seen any major issues occurring due to people manually adding these headers. Closing for now.
