### ISSUE TITLE
[Feature Request] Setting default option for Generate Code

### ISSUE THREAD

**Issue by TheIcemanCometh** [a85/POSTMan-Chrome-Extension#1995]
As someone who always prefers to use cURL when testing service calls from a command line, I'd like an option in the general Settings to allow me to define which Generate Code Snippet option is selected by default.

**Comment by who** [comment]
+1

I'm always using cURL as well. It would be nice to choose a default.

**Comment by abhijitkane** [comment]
@who @ThelcemanCometh 
Thanks. In the next release, we'll push stickiness for the selected language. Opening the code generation modal will remember the last language you had selected.

**Comment by abhijitkane** [comment]
@who @TheIcemanCometh Can you confirm this fixed in the latest version of the app?

**Comment by TheIcemanCometh** [comment]
It is working as I would expect.  Awesome, and thank you !!
