### ISSUE TITLE
Basic Auth in collections bug

### ISSUE THREAD

**Issue by sebastian121212** [a85/POSTMan-Chrome-Extension#1997]
Running a collection with different basic authorisations makes all requests to use the first request auth, ignoring the following request auth configurations. 
This can be easily reproduced using the default Postman Echo collection:Auth Others, just adding a request with wrong credentials will make all the others ones to fail.

**Comment by abhijitkane** [comment]
@sebastian121212 What's the exact sequence of steps you follow?
In the "Auth: Others" folder, I added another request (called Failing Basic Auth) which uses Basic Auth with username=postman1, password=password1, and saved it.

Sending the Failing Basic Auth request results in an "Unauthorized" response, while sending the original "Basic Auth" request results in a successful response.

**Comment by abhijitkane** [comment]
@sebastian121212 Thanks for reporting this. We'll be pushing a fix for this in the next release.

**Comment by abhijitkane** [comment]
@sebastian121212 Can you confirm this fixed in the latest version of the app?

**Comment by sebastian121212** [comment]
Yes, its working now 👍
