### ISSUE TITLE
[Feature Request]: Setting to Allow Prompt for New Route Name when Duplicating

### ISSUE THREAD

**Issue by tribou** [a85/POSTMan-Chrome-Extension#2000]
I duplicate routes all the time, and it would be great if Postman would prompt me for the new route name automatically instead of manually going in to edit and rename afterwards.  This feature could be enabled by a switch in the settings menu.

**Comment by abhijitkane** [comment]
@aditikul

**Comment by a85** [comment]
With inline editing a prompt is not required anymore.
