### ISSUE TITLE
Missing colon in url when generate request to javascript

### ISSUE THREAD

**Issue by rudnitskih** [a85/POSTMan-Chrome-Extension#2002]
When we add headers with link like "http://googe.com", after generate to any javascript code we get "http//googe.com"
![capture](https://cloud.githubusercontent.com/assets/8848858/14595293/bda918f2-0546-11e6-9b20-6fd0403f8cf4.PNG)
![untitled](https://cloud.githubusercontent.com/assets/8848858/14595292/bda8f4d0-0546-11e6-9ff5-4435514bacbc.png)

Version: 4.1.3
win / x86-64
Chrome 47.0.2526.80

Thank you!

**Comment by abhijitkane** [comment]
@rudnitskih Thanks for reporting this! We've fixed this internally, and will push out a release soon.

**Comment by bcraig83** [comment]
Same issue when generating C# (RestSharp) code snippets.

![image](https://cloud.githubusercontent.com/assets/5794182/14780672/ee9fcfca-0ad5-11e6-971a-118ecef08f9c.png)

**Comment by abhijitkane** [comment]
@numaanashraf Fixed in internal commit 32742af
@bcraig83 - We'll fix this in the next release

**Comment by abhijitkane** [comment]
@rudnitskih @bcraig83 Can you confirm this fixed in the latest version of the app?
