### ISSUE TITLE
Getting server couldn't send a response with the latest Postman client

### ISSUE THREAD

**Issue by jaingajendra** [a85/POSTMan-Chrome-Extension#2005]
I have latest Postman installed in my system. and following are the version taken from the postman.

4.1.3
win / x86-32
Chrome 49.0.2623.112

Problem is All the requests(POST OR GET OR PUT) does not works sometimes. We get the following message

This seems to be like an error connecting to http://192.168.0.10:11880/positions/abc

Why this might have happened:
The server couldn't send a response:
Ensure that the backend is working properly
SSL connections are being blocked:
Fix this by importing SSL certificates in Chrome
Cookies not being sent:
Use the Postman Interceptor extension
Request timeout:
Change request timeout in Settings > General

Please let me know what could be the issue. 

Regards,
Gajendra

**Comment by abhijitkane** [comment]
@jaingajendra Can you check the Network tab in the DevTools window - https://blog.getpostman.com/2015/06/13/debugging-postman-requests/ ?
You'll be able to see the raw request/response payloads here.

**Comment by nikilKaranjit** [comment]
i had same problem and this was due to i forgot to turn on my server

**Comment by chisumo2016** [comment]
![image](https://user-images.githubusercontent.com/9254656/36279540-52f970da-128f-11e8-8470-00501108098d.png)

**Comment by hemantshelar** [comment]
@chisumo2016 did you find any solution?  I am also facing the same problem.  However, I can see this request going our and pulling response in Fiddler.  Must be some Postman UI issue.  I am currently using Postman v5.5.3 (latest version at this point of time)

**Comment by kavya-jain12** [comment]
Was facing the same issue.
 Try running php artisan passport:install --force o server and then run 
php artisan passport:keys --force
This will solve your problem. This happens when you copy data from local to remote database. Re-installing passport on server helps where it generates its own keys and overrides the local keys in database.
