### ISSUE TITLE
Suggestions for improvement of Collection download

### ISSUE THREAD

**Issue by Scottsuen** [a85/POSTMan-Chrome-Extension#2006]
1. having a Keyboard shortcuts for Collection-download would be convienent.
2. if have a setting for default download file, then I need not to select a target file every time
3. downloaded collection name is like this : collection_name.json.postman_collection, why not collection_name.postman_collection.json. For a json document can be syntax highlighted with many editors.

**Comment by abhijitkane** [comment]
@Scottsuen
#1 is tricky - the collection needs to be selected for the shortcut to work, and there's no "collection selected" state right now.

#2 isn't possible in Chrome. Due to a chrome restriction, the app cannot save files without showing the Save File dialog box.

Agree about #3. Will try to push this soon.

**Comment by Scottsuen** [comment]
@abhijitkane Thanks! About #3, also with the environment download.

**Comment by Scottsuen** [comment]
@abhijitkane Thanks! About #3, also with the environment download.

**Comment by Scottsuen** [comment]
@abhijitkane Thanks! About #3, also with the environment download.

**Comment by Scottsuen** [comment]
@abhijitkane Thanks! About #3, also with the environment download.

**Comment by Scottsuen** [comment]
@abhijitkane Thanks! About #3, also with the environment download.

**Comment by Scottsuen** [comment]
@abhijitkane Thanks! About #3, also with the environment download.

**Comment by Scottsuen** [comment]
@abhijitkane Thanks! About #3, also with the environment download.

**Comment by Scottsuen** [comment]
@abhijitkane Thanks! About #3, also with the environment download.

**Comment by Scottsuen** [comment]
@abhijitkane Thanks! About #3, also with the environment download.

**Comment by Scottsuen** [comment]
@abhijitkane Thanks! About #3, also with the environment download.

**Comment by Scottsuen** [comment]
@abhijitkane Thanks! About #3, also with the environment download.

**Comment by Scottsuen** [comment]
@abhijitkane Thanks! About #3, also with the environment download.

**Comment by Scottsuen** [comment]
@abhijitkane Thanks! About #3, also with the environment download.

**Comment by Scottsuen** [comment]
@abhijitkane Thanks! About #3, also with the environment download.

**Comment by Scottsuen** [comment]
@abhijitkane Thanks! About #3, also with the environment download.

**Comment by Scottsuen** [comment]
@abhijitkane Thanks! About #3, also with the environment download.

**Comment by Scottsuen** [comment]
@abhijitkane Thanks! About #3, also with the environment download.

**Comment by Scottsuen** [comment]
@abhijitkane Thanks! About #3, also with the environment download.

**Comment by Scottsuen** [comment]
@abhijitkane Thanks! About #3, also with the environment download.

**Comment by Scottsuen** [comment]
@abhijitkane Thanks! About #3, also with the environment download.

**Comment by Scottsuen** [comment]
@abhijitkane Thanks! About #3, also with the environment download.

**Comment by Scottsuen** [comment]
@abhijitkane Thanks! About #3, also with the environment download.

**Comment by Scottsuen** [comment]
@abhijitkane Thanks! About #3, also with the environment download.

**Comment by Scottsuen** [comment]
@abhijitkane Thanks! About #3, also with the environment download.

**Comment by Scottsuen** [comment]
@abhijitkane Thanks! About #3, also with the environment download.

**Comment by Scottsuen** [comment]
@abhijitkane Thanks! About #3, also with the environment download.

**Comment by Scottsuen** [comment]
@abhijitkane Thanks! About #3, also with the environment download.

**Comment by Scottsuen** [comment]
@abhijitkane Thanks! About #3, also with the environment download.

**Comment by Scottsuen** [comment]
@abhijitkane Thanks! About #3, also with the environment download.

**Comment by Scottsuen** [comment]
@abhijitkane Thanks! About #3, also with the environment download.

**Comment by Scottsuen** [comment]
@abhijitkane Thanks! About #3, also with the environment download.

**Comment by Scottsuen** [comment]
@abhijitkane Thanks! About #3, also with the environment download.

**Comment by Scottsuen** [comment]
@abhijitkane Thanks! About #3, also with the environment download.

**Comment by Scottsuen** [comment]
@abhijitkane Thanks! About #3, also with the environment download.

**Comment by Scottsuen** [comment]
@abhijitkane Thanks! About #3, also with the environment download.

**Comment by abhijitkane** [comment]
@Scottsuen Can you confirm this fixed in the latest version of the app?

**Comment by Scottsuen** [comment]
yes，the issue is fixed. thx @abhijitkane
