### ISSUE TITLE
Bring back the browser-tab version of Postman

### ISSUE THREAD

**Issue by Macoshark** [a85/POSTMan-Chrome-Extension#2008]
I don't like running Postman as a standalone app. I have a couple of issues with it. 
1. The two embedded scroll areas on the main view are difficult to deal with. When I issue a request and get a response its very hard to scroll the page. The scrolling behaviour in OSX is such that at first the entire page scrolls when swipe or scroll with my mouse. Then the mouse cursor goes ontop of the response area and it starts to scroll while the rest of the page stops scrolling. This is a typical web layout problem with nested scrolling areas. This is really frustrating because it means that I can see only a few lines of the response if I don't move the mouse higher up or to the sides so that I can scroll the entire page.
2. Accessing a browser tab is much quicker than a standalone app. This is true in OSX at least because of the idiotic window focus behavior of OSX. 
3. Request body editor has a minimum height that is way too big. This makes the scrolling problem even worse because a lot of the screen is wasted on the mostly empty request body. 
4. The gray color scheme in the left is a bit confusing. It's too difficult to navigate between collections.
5. The standalone app has its own cookies and therefore its own session. This is sometimes a good thing, but I would often prefer to share the cookies from Chrome.

**Comment by a85** [comment]
The Chrome app platform itself is deprecated. Almost all of these issues have been addressed as part of multiple updates to our native apps through the year. We will look at web view based apps in 2017 but right now we can't do anything.
