### ISSUE TITLE
Group failed test together

### ISSUE THREAD

**Issue by dineshk-qa** [a85/POSTMan-Chrome-Extension#2009]
When a collection is run and it has some failed tests, it would be great if the user can have a list of failed tests along with number (currenlty available).
I have a collection with 300 tests and sometimes I have ~30 tests failing but I have to scroll all the way to identify the failed test.
It would be great we have a dedicated section for failed tests in the runner

**Comment by vkaegis** [comment]
@dinesh-domain Hey Dinesh, thanks for the feedback! We've been working on an update to the Runner which, amongst other features, will have filters allowing you to view only those tests which have failed. We're hoping to roll out the update in the coming weeks so stay tuned!

**Comment by sdnts** [comment]
@dinesh-domain We've redesigned the runner and the new Runner has filters that will allow you to do just that. The new Runner is on our Canary channel, and you can download it for [OSX](https://dl.pstmn.io/download/channel/canary/osx_64) / Windows ([x86](https://dl.pstmn.io/download/channel/canary/windows_32) or [x64](https://dl.pstmn.io/download/channel/canary/windows_64)) / Linux ([x86](https://dl.pstmn.io/download/channel/canary/linux_32) or [x64](https://dl.pstmn.io/download/channel/canary/linux_32)) / [Chrome](https://chrome.google.com/webstore/detail/postman/loddepljkabcghihdkbkfknabkinanff)

I'd recommend you to join our Slack community [here](https://www.getpostman.com/slack-invite) so you can provide feedback before the runner moves to our stable builds :)

**Comment by sdnts** [comment]
@dinesh-domain The redesigned Runner is out now with our latest release (4.9) on our native apps. Failed tests can now be filtered so you can look at them separately. Can you update and see if this suits your use case?
