### ISSUE TITLE
Feature-Request: External Collections

### ISSUE THREAD

**Issue by roeschjohannes** [a85/POSTMan-Chrome-Extension#2010]
It would be great to have "external collections" which will be stored on hard disk.

We need to store our collections in a git repo to integrate them in a continuous integration pipeline. We always have to import the collections, make our changes and export them again. Then we can commit them. It would be better to have a collection which is automatically stored in a defined folder an we only need to commit the changes. Also with each pull we get the correct collection from git and we can start working directly with postman without the need of configuring my environment.

**Comment by abhijitkane** [comment]
@roeschjohannes Chrome apps don't give us the ability to read files without user intervention. We could potentially do this in our OSX app, but that would mean considerably spitting the codebase. We soon plan to offer versioning as part of our Cloud offering - https://www.getpostman.com/pricing

Closing this as non-actionable for now.
