### ISSUE TITLE
Pretty / Preview depending on HTTP status code

### ISSUE THREAD

**Issue by misog** [a85/POSTMan-Chrome-Extension#2012]
Hi, it would be great to automatically switch tabs Pretty or Preview depending on HTTP status code.
For example, when working with JSON REST API, when the code is 200 (OK) I want to show Pretty format of JSON response, but if the code is 500 (Server error) or 404 (Not found) I want to render the page - usually the server/framework formats the error with html and css.

...maybe a checkbox or textarea with pairs CODE<space>TAB_ID or CODE:TAB_ID

**Comment by a85** [comment]
I don't think we ever found a way to support this without surprising people. Closing this request.

**Comment by misog** [comment]
If it is optional and/or configurable then it will surprise users only in a positive way. Content-Type and response code could determine the preferred TAB - it should be straightforward to implement and to configure by users in settings.

Moreover, in recent months many developers got angry at Firefox for [removal of HTML preview](https://www.reddit.com/r/firefox/comments/6h7n50/why_was_http_response_preview_removed_from/), so there is some awareness/searching traffic around "pretty previews" as well as flustration. A configurable pretty preview which in effect rapidly saves clicking time could be a popular feature.
