### ISSUE TITLE
Remember window position on Mac

### ISSUE THREAD

**Issue by chforsb** [a85/POSTMan-Chrome-Extension#2014]
Thanks for a great app, but on Mac it doesn't remember the position from the last session (always start in the middle of the screen), and it's kind of standard that an app remember the window position and size between runs.

**Comment by a85** [comment]
Is this on the Mac app or the Chrome app?

**Comment by chforsb** [comment]
In the Mac app.

**Comment by SamvelRaja** [comment]
@AppChris This feature has been available in out latest mac apps. Kindly update your app to the latest to avail that.

**Comment by chforsb** [comment]
Yes, it works, excellent, thanks!
