### ISSUE TITLE
Resize on Mac change the output from json to HTML

### ISSUE THREAD

**Issue by romnycristopher** [a85/POSTMan-Chrome-Extension#2015]
If you are using the the chrome app on mac and you select the pretty view option with the output in JSON if you resize the window the output change from JSON to HTML

**Comment by abhijitkane** [comment]
@romnycristopher I'm not able to reproduce this. Are you facing this every time?
Could you attach/link to a screen recording?

**Comment by romnycristopher** [comment]
Hi @abhijitkane, of course, here is the link:
https://drive.google.com/a/dotspixelstudio.com/file/d/0B09Ziuf54h4qMU9lOWNmc3VPUzg/view?usp=sharing

**Comment by yomr** [comment]
Facing the same issue! I am on EL Capitan!

**Comment by abhijitkane** [comment]
@romnycristopher @yomr We've fixed this internally, and will be pushing a fix out in the next release. Thanks for reporting this.

**Comment by yomr** [comment]
Cool!

**Comment by abhijitkane** [comment]
@romnycristopher @yomr Can you confirm this fixed in the latest version of the app?

**Comment by romnycristopher** [comment]
@abhijitkane the problem is solved! Thanks for the fix!
