### ISSUE TITLE
Global search feature in Postman

### ISSUE THREAD

**Issue by srbangre** [a85/POSTMan-Chrome-Extension#2016]
Hi,
I have 158 requests inside 21 folders in postman. in one of the request i am setting a value of variable in property. i need to search which request i am doing that. How can i find out?
the normal search option in postman searches only the name of the request

**Comment by abhijitkane** [comment]
@srbangre Have added this as a feature request. For now, here's a quick hack:
Download the collection as JSON (click on ... next to the collection name > Download).
Search the downloaded file for your variable name. You should find it in the `tests` property of one of the requests. The request name will appear as a `name` property in the same request.

**Comment by ddeshpande** [comment]
@abhijitkane Would like to suggest an improvement in this feature. Along with being able to search where global or environment variable is being set, would be great if we are able to search where is it being read too.

**Comment by a85** [comment]
Search is available now in the Postman app. "Replace" coming soon.
