### ISSUE TITLE
Any way to track changes?

### ISSUE THREAD

**Issue by darrylkuhn** [a85/POSTMan-Chrome-Extension#2017]
We keep running into sync issues (collections re-ordered, requests re-ordered or missing, etc...) Is there any way to track who last changed a collection, and what the changes were?

**Comment by abhijitkane** [comment]
@darrylkuhn We're introducing a team activity feed really soon. This should help the team keep track of who changed what.
For the missing requests - can you mail us at help@getpostman.com with the owner/collection name? We should be able to restore the request.

**Comment by eric-newton** [comment]
Our team has employed the checkin-to-git repo approach: periodically "download" the collection into a file, then checkin to git.

Would like to see this feature (inaddition to) team activity feed.  A lot of times it more neccesary to "go back to the working copy" then it is to be notified via team acitivty that user B changed something that was incorrect, but how does user A recover it?

**Comment by darrylkuhn** [comment]
@eric-newton We also check into git as you describe... the problem is when you go to do a diff it's damn near impossible since all the UUIDs change. Our test suite is comprised of nearly 500 requests and over 2000 tests. It's a large set so while we can rollback to a previous version, finding out what we changed and "replaying" those changes takes significant time and is quite prone to human error

**Comment by a85** [comment]
Detailed changes for a collection are available in the "Activity Feed". 

<img width="618" alt="screenshot 2016-11-12 18 21 11" src="https://cloud.githubusercontent.com/assets/653409/20237890/db1cae32-a904-11e6-8738-6d4cb69ba200.png">
