### ISSUE TITLE
Add the collection/folder name to test name in xml result.

### ISSUE THREAD

**Issue by anyone-can-test** [a85/POSTMan-Chrome-Extension#2018]
I run collection in Jenkins.
Test name is only request name in xml result (like JUnit).
If I have several folders and requests, then tests is not structured like class/method.

So, I want that test name has request and folder name.
For example.
[collection name].[folder name].[request name]

Thank you.

**Comment by abhijitkane** [comment]
@czardoz Can you move this to Newman? Might belong there.

**Comment by anyone-can-test** [comment]
I didn't know about Newman github.
Ok. I move this issue to Newman.
