### ISSUE TITLE
Support for emoji in the folder names

### ISSUE THREAD

**Issue by nickpestov** [a85/POSTMan-Chrome-Extension#2019]
If I have emojis in the names of folders under a collection, the emoji does not show up on the sidebar. However, if I expand the details of the Collection from the sidebar and then click on the folder name, it will show up there.

P.S. Emojis do show up within Collection names in the Sidebar, but not in the folder names within the Collection.

**Comment by abhijitkane** [comment]
@nickpestov This appears to be an issue because the folder names are displayed in bold. This is a Chromium bug being tracked at https://bugs.chromium.org/p/chromium/issues/detail?id=470655

**Comment by vkaegis** [comment]
Hey @nickpestov, thanks for bringing to our attention! We'll be rolling out a fix for this soon... will let you know once we do.

**Comment by SamvelRaja** [comment]
This been fixed in the latest 4.7.2 release.
