### ISSUE TITLE
Support enter/return key at the URI box

### ISSUE THREAD

**Issue by cpoblete** [a85/POSTMan-Chrome-Extension#2020]
After typing the URI at the URI box, you have to mouse over and click the Send button. To save the mouse over and click action, it would be really nice to just press ENTER or RETURN key to act as "send".

**Comment by mstaalesen** [comment]
Ctrl + Enter will do what you want.

**Comment by cpoblete** [comment]
Although just "Enter" would be awesome, the additional keystroke would suffice.

**Comment by cpoblete** [comment]
As of now, the latest version is accepting just "Enter". This is awesome. Thanks!
