### ISSUE TITLE
My collection is missing some requests

### ISSUE THREAD

**Issue by jlubeck** [a85/POSTMan-Chrome-Extension#2021]
It shows that there are supposed to be 7, but I can only see 2. There should be 7

![Image of bug](https://monosnap.com/file/uQh69U3rK3HJQhCcHiZ33RLtEmS8O5.png)

**Comment by abhijitkane** [comment]
@jlubeck What version of Postman are you using? Can you try logging out and logging in? This should restore the 5 missing requests.

**Comment by jlubeck** [comment]
4.1.3
OS X / x86-64
Chrome 49.0.2623.110

Yup, signing out and back in made it work. Thanks! I left it open though as this would be a workaround to fix the issue, but it shouldn't really happen right?

**Comment by abhijitkane** [comment]
@jlubeck Nope - we'll be pushing a fix for this in the next release.
