### ISSUE TITLE
Postman is not starting (reinstall doesn't help)

### ISSUE THREAD

**Issue by dmitry-saritasa** [a85/POSTMan-Chrome-Extension#2022]
1. Postman was working and then start to complain that certain files missed and now it's not even opening properly
2. Chrome Version 50.0.2661.75 (64-bit)
3. Reset chrome flags to default
4. Removed and installed again the postman through google app store. Didn't help
5. When I try to run it - simply nothing happens, no window open. Doesn't work if I run it as the app or inside Chrome apps launchbar. 

I'm running Fedora 23
Linux DmitryPC 4.4.7-300.fc23.x86_64 #1 SMP Wed Apr 13 02:52:52 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by abhijitkane** [comment]
@saritasa Can you attach a screenshot showing the error message about the missing file?
Also, you can try installing Chrome Canary and installing Postman there.

**Comment by dmitry-saritasa** [comment]
Unfortunately right now - it doesn't display anything. I run the app - and nothing happens, no errors at all. It doesn't start, nothing. What can I do?

**Comment by abhijitkane** [comment]
@saritasa Did Chrome Canary not help?

**Comment by dmitry-saritasa** [comment]
I'm on Linux, and Canary is not available yet on Linux

**Comment by htunlogic** [comment]
I have the same issue on Ubuntu 15.10. Never worked at all. I have just updated chrome and tried installing again, but same thing. It displays icon on launcher, but window does not open.

**Comment by dmitry-saritasa** [comment]
At the same time I can say that on my home fedora 23 it works just fine. But at the office PC - it stopped working recently. Any suggestions/ideas. We have paid plan with you guys.

**Comment by dmitry-saritasa** [comment]
any news @abhijitkane ?

**Comment by abhijitkane** [comment]
@saritasa We've tried a variety of linux machines, including Fedora 23, but we've yet to reproduce the issue. Can you share a screenshot of the "some files are missing" error?

**Comment by dmitry-saritasa** [comment]
the video:
https://www.dropbox.com/s/c7jlvu4z67vy7wd/video_2016_05_05_uu7utnfu.ogv?dl=0

**Comment by czardoz** [comment]
@saritasa can you run this in the terminal and paste the output here?

```
google-chrome --app-id=fhbjgbiflinjbdggehcddcbncdddomop --profile-directory=Default
```

**Comment by dmitry-saritasa** [comment]
(phind) [dmitry:~/Projects/phind](develop)$ google-chrome --app-id=fhbjgbiflinjbdggehcddcbncdddomop --profile-directory=Default
Created new window in existing browser session.
(phind) [dmitry:~/Projects/phind](develop)$

**Comment by czardoz** [comment]
@saritasa 
Can you close all the chrome windows and run that command again? I specifically want to see logs for what happens when the app is launched.

**Comment by lgilz** [comment]
I have the same problem on Ubuntu

**Comment by dmitry-saritasa** [comment]
``` bash
[dmitry:~]$ google-chrome --app-id=fhbjgbiflinjbdggehcddcbncdddomop --profile-directory=Default
[15251:15251:0531/110708:ERROR:background_mode_manager_aura.cc(13)] Not implemented reached in virtual void BackgroundModeManager::EnableLaunchOnStartup(bool)
[15251:15251:0531/110708:ERROR:display_info_provider_aura.cc(30)] Not implemented reached in virtual void extensions::DisplayInfoProviderAura::UpdateDisplayUnitInfoForPlatform(const gfx::Display &, extensions::api::system_display::DisplayUnitInfo *)
[15251:15282:0531/110711:ERROR:simple_version_upgrade.cc(153)] File structure does not match the disk cache backend.
[15251:15282:0531/110711:ERROR:simple_backend_impl.cc(589)] Simple Cache Backend: wrong file structure on disk: /home/dmitry/.config/google-chrome/Default/Storage/ext/fhbjgbiflinjbdggehcddcbncdddomop/def/Cache
couldn't lock 16384 bytes of memory (secret_session): Cannot allocate memory

```

sorry for a late reply - was travelling

**Comment by czardoz** [comment]
@saritasa are you able to open any other Chrome Apps? 

As the log file says, your Chrome is consuming a lot of memory, and is not able to launch Postman because of that.

**Comment by lgilz** [comment]
At least I can open any other app.

**Comment by dmitry-saritasa** [comment]
@czardoz yes I can open other apps, just not postman.

**Comment by czardoz** [comment]
```
[15251:15282:0531/110711:ERROR:simple_backend_impl.cc(589)] Simple Cache Backend: wrong file structure on disk: /home/dmitry/.config/google-chrome/Default/Storage/ext/fhbjgbiflinjbdggehcddcbncdddomop/def/Cache
```

This suggests that your Chrome profile is somehow creating a corrupted version of that file. Can you try installing a build of Chromium browser: https://download-chromium.appspot.com/ and then installing Postman in that?

**Comment by diamondamulet** [comment]
Maybe solved problem,
I have same issue on Windows x64. Removed from chrome and reinstalled the setup downloaded from https://www.getpostman.com that is working well.

**Comment by zmpeterson86** [comment]
I'm on x64 too and I've been waiting 15 minutes for postman to start. Reinstalled and still nothing

**Comment by Goufalite** [comment]
I also cannot start Postman, but I went further : it worked until I created a account after doing things offline for a moment.
It is stucked at the loading page (with the spinning planets gif). But when I go to the console (Ctrl+Shift+I) it says "Could not find default workspace while booting session" and then "Cannot read property 'getShortcuts' of undefined".

Edit : **Solved !**
- Launch Postman and wait for the orbiting planets
- Hit Ctrl+Shift+I
- Go to application tab
- Click on each Storage element (Local Storage, Session Storage **and especially IndexedDB**) and remove everything
- Relaunch!

**Comment by VinyLimaZ** [comment]
@Goufalite I'm with the same problem, but when I hit the developer tools shortcut, nothing happens D:

**Comment by anukul-mohil** [comment]
Had the same problem where app just won't start on ubuntu, deleting the local cache solved the issue.
Local cache location:
>  MacOS: "/Users/<user>/Library/Application Support/Postman" 
Windows: "C:\Users\<user>\AppData\Roaming\Postman" and "C:\Users\ <user>\AppData\Local\Postman"
 Linux: "~/.config/Postman"
Check [this](https://support.getpostman.com/hc/en-us/articles/115005901149-My-Postman-app-won-t-start) for more info.

**Comment by riffadi** [comment]
I have a problem with execute the postman, when I open postman a see the notice 
"Failed execute the postman.
Failed to execute child process “/home/riff/Downloads/Postman/Postman” (No such file or directory).
"

can anyone help me?

**Comment by fossterer** [comment]
> I have a problem with execute the postman, when I open postman a see the notice
> "Failed execute the postman.
> Failed to execute child process “/home/riff/Downloads/Postman/Postman” (No such file or directory).
> "
> 
> can anyone help me?

@riffad1 See the comment above yours https://github.com/postmanlabs/postman-app-support/issues/2022#issuecomment-418602252 . I upgraded to 6.7.1 and I have the same issue. Though I need to figure out what I need to bring back to have all my collections. Instead of deleting the folder, I renamed it to be something irrelevant. @abhijitkane  @czardoz

**Comment by fossterer** [comment]
Found it! Look for a folder named "IndexedDB" inside .config/postman . By copying it from my renamed folder to newly created folder (after starting app once and then closing), I got all my Collections and Tests back.

Still waiting for a response to see how to get Environments etc. back

**Comment by brightintegration** [comment]
Had precisely the same problem on Linux Mint 20 Ulyana. Click the app icon, nothing happens except a spinning mouse cursor for some time. It never even showed the orbiting planets. Installed it through Software Manager and reinstalling it through that did not work either. Finally installed it directly through the downloaded app from the site, and now it works again. It may be some flatpak issue?

**Comment by llamagustin** [comment]
@okebaja 
I have the same problem in Mint 21.2
~/.config/Postman does not exist
reinstalled and still nothing
Did you find any solution?
