### ISSUE TITLE
Is there any way to restore a collection I accidentally deleted

### ISSUE THREAD

**Issue by frank0000** [a85/POSTMan-Chrome-Extension#2023]
I meant to delete a single REST call under the collection but apparently deleted the whole collection.  The "undelete" notification hovered for about 3 seconds - just long enough for me to realize my mistake but disappeared before I could click it.  Is there anything I an do to restore my collection at this point?

**Comment by sobtiankit** [comment]
@frank0000 Do you have Sync enabled? If yes, can you email help@getpostman.com with your account details and we'll help you out.

**Comment by frank0000** [comment]
oh cool thanks @sobtiankit, I'll do that. As a workaround, I was able to restore a bit from History too.

**Comment by abhijitkane** [comment]
Following up over email. Closing this.

**Comment by SubjectiveReality** [comment]
For future visitors...

> We've recently made the collection recovery process self-serve via the online dashboard. Once there, clicking on the icon on the top right, and selecting Trash from the dropdown menu will take you to a page with all of your recoverable collections. 
> https://learning.getpostman.com/docs/postman/collections/managing_collections/#recover-a-collection 

> If the deleted collection was shared to a workspace and isn't populating as a recoverable collection, it may still be in the Personal Workspace from which it was shared.

> If you'd like to revert your collection to a previous state, you can do so by leveraging the collection's in-app activity feed.
> https://learning.getpostman.com/docs/postman/workspaces/activity_feed_and_restoring_collections/
