### ISSUE TITLE
Postman doesn't prompt for client certificate with latest chrome 50

### ISSUE THREAD

**Issue by goldbergjeffrey** [a85/POSTMan-Chrome-Extension#2025]
Postman used to prompt for client cert when making first https connection to a resource.  Now it is not prompting at all.  I have to open Chrome and log into resource first with windows auth in order for my session to be honored.

Looks like this change happened after updating to chrome 50 two days ago.

Thank you for your help.

**Comment by a85** [comment]
Can you tell me the app version number?

**Comment by goldbergjeffrey** [comment]
I'm closing it.  The issue was mine.  Truly sorry.

**Comment by cosbor11** [comment]
+1 

App Version = Version 4.8.0 (4.8.0)

Postman is not prompting for my ClientCert even though Chrome already has,

**Comment by goldbergjeffrey** [comment]
@cosbor11, I am using the Windows client and in order for Postman to use the client cert, I had to enter it into postman settings using pem files.

Hope this helps.
