### ISSUE TITLE
[Feature] additional shortcuts

### ISSUE THREAD

**Issue by lukasoppermann** [a85/POSTMan-Chrome-Extension#2026]
Please add an additional shortcuts for

**edit selected Request** maybe (cmd + r for rename?)

This should trigger for the request currently highlighted on the left (sidebar)

**Comment by BlueInt32** [comment]
+1
Dealing with a lot of requests duplications and renaming makes edition quite tedious.

Why not add
**duplicate selected request** also ?

**Comment by lukasoppermann** [comment]
True @BlueInt32, but should it not rather be **duplicate and edit selected request**?

**Comment by BlueInt32** [comment]
Sure, that could be a way.

**Comment by a85** [comment]
These are available on native apps now: www.getpostman.com/apps
