### ISSUE TITLE
Genetate Code add Markdown support!

### ISSUE THREAD

**Issue by m11y** [a85/POSTMan-Chrome-Extension#2028]
As a programer, we always need to write interface documents, but we also hate to do that.
If postman can generate markdown, we _at least_ can copy parameters to document, making writing docments easier.

Or, gonging further，will postman generate documents with the help of something like DSL, metadata tag etc.

**Comment by abhijitkane** [comment]
@wizwjw The current 'generate code' section shows snippets to actually make the request in a number of languages. Not sure what role markdown can play here.
Postman could, in theory, generate a specific format of markdown for a collection. There's already a auto-documentation service for Cloud users (https://www.getpostman.com/docs/creating_documentation)
