### ISSUE TITLE
setNextRequest & Environment Variables

### ISSUE THREAD

**Issue by stevenmilstein** [a85/POSTMan-Chrome-Extension#2031]
I try setNextRequest based on the example in http://blog.getpostman.com/2016/03/23/conditional-workflows-in-postman/ & understand see it being triggered by responseCode.code.

However, I'm unable to trigger them by Environment Variables. Is it me, or, a limitation?

Thanks

**Comment by abhijitkane** [comment]
@stevenmilstein Not sure what you mean by "triggered by responseCode.code". Calling postman.setNextRequest("requestName") will cause <requestName> to be the next request that'll be executed. You'll need to use the runner to run the whole collection.

**Comment by stevenmilstein** [comment]
On a GET's _Tests_ script;

```
if (responseCode.code === 404) {
    postman.setNextRequest("POST Customer");
} else {
    postman.setNextRequest("PUT Customer");
} else {
   postman.setNextRequest(null);
}
```

works as expected.

I could avoid the GET, if I condition on an environment variable in a previous Step;

```
if (environment.customerID === "null") {
    postman.setNextRequest("POST Customer");
} else {
    postman.setNextRequest("PUT Customer");
} else {
   postman.setNextRequest(null);
}
```

But it doesn't seem to work.

**Comment by abhijitkane** [comment]
@stevenmilstein Calling `setNextRequest` in a pre-request script of request A will just set the _next_ request. Request A will always be executed.
To avoid sending request A, you'll need to put this check in the request that's run _before_ request A.

**Comment by stevenmilstein** [comment]
OK, that works. IMO, it would've been nice to keep the logic encapsulated within each request's Pre-request Script, so I could move them around, or, reuse them more freely.

But it works, so that's pretty good!

Thanks
