### ISSUE TITLE
Large integers aren't represented correctly when replaced

### ISSUE THREAD

**Issue by abhijitkane** [a85/POSTMan-Chrome-Extension#2033]
Pre-request script: postman.setEnvironmentVariable("bigNum", 9098774238709471234);

Use `{{bigNum}}` in the request body. What's actually sent is 9098774238709471000.

Reported in https://postman.zendesk.com/agent/tickets/4555

**Comment by a85** [comment]
Still valid?

**Comment by sdnts** [comment]
Closing as this should have been solved with the data editor.
