### ISSUE TITLE
Shared collection links should render page instead of raw JSON

### ISSUE THREAD

**Issue by NathanHazout** [a85/POSTMan-Chrome-Extension#2034]
In Postman, click Share > Copy URL.

Paste that URL in Chrome (https://www.getpostman.com/collections/63aa4b29c44c5e65ddce).

Expected behavior: Page asking me if I want to open the Postman app.

Actual behavior: Shows me a raw JSON file.

**Comment by abhijitkane** [comment]
@nasht00 Are you using the Postman mac app or Chrome app?
The page asking if you want to open Postman will only show up if you use the run button (https://www.getpostman.com/docs/run_button).

**Comment by NathanHazout** [comment]
Chrome app.
Maybe you are right, for some reason I assumed that sending a direct link to someone would behave the same way.

Feature request maybe?

**Comment by preethammavin** [comment]
@NathanHazout this can be achieved using the public workspaces, where you can share the link directly with your consumers
