### ISSUE TITLE
Request Body Not Updating After Save

### ISSUE THREAD

**Issue by pstricker** [a85/POSTMan-Chrome-Extension#2035]
Postman Version: 4.1.3
OS: Windows 10
Chrome: 50.0.2661.94

I have ran into an issue where I can not edit the body of requests after initial send. I have done a fair amount of searching but have not run into any other threads on the issue. Steps to reproduce are as follows:

Step 1: Send a Postman request that includes a x-www-form-urlencoded body
Step 2: Modify body of Postman request in the editor
Step 3: Click "Save"
Step 4: When I hit "Send", the body of my request has not changed and is sending the exact content of the body from Step 1.

I have seen this occur for both the body of the request and any environment variables set in the Pre-request Script. Not sure if it is related, but I am using the IN SYNC feature.
![capture](https://cloud.githubusercontent.com/assets/3308247/14991174/4ef4a3bc-111d-11e6-8f5e-4b1bcbc407f5.PNG)

**Comment by abhijitkane** [comment]
@pstricker Can you check if the `Send Postman Token Header` setting is enabled?

**Comment by sdnts** [comment]
Hey @pstricker, from the screenshot, it looks like you are still in `Bulk Edit` mode after modifying the request body. As of right now, you need to actually click `Submit` to apply these changes to the request. (You'll see the familiar key-value pairs again with your updates)

We've made changes in our internal build that makes this step unnecessary, and will roll this out in the next update.

**Comment by pstricker** [comment]
@abhijitkane The `Send Postman Token Header` setting was not enabled. Enabling seems to have resolved the problem. Thank you!
