### ISSUE TITLE
Postman is considered a Chrome window

### ISSUE THREAD

**Issue by seangates** [a85/POSTMan-Chrome-Extension#2036]
Currently, when I have Chrome open and Postman open, Postman is treated as a Chrome window. When doing a `command + [back tick]` it is cycled as one of the Chrome windows. This doesn't happen with any other apps created with Electron (e.g. Slack).

Also, when doing a `command + tab` it acts as though it's part of the Chrome window group, which it should not be.

Please fix this so that it works as a standalone app, and is not tied to Chrome in any way.

**Comment by abhijitkane** [comment]
@seangates Are you using the Postman Mac app? If so, this should not occur. Command+` is not handled by Postman's Mac app at all.

If you're using Postman's Chrome app, then you'll see the issue. This a Chrome issue (https://bugs.chromium.org/p/chromium/issues/detail?id=339239), and there's nothing we can do about it for now.

**Comment by seangates** [comment]
Okay. Let me confirm. I have at one point downloaded both.

**Comment by seangates** [comment]
@abhijitkane You are correct. Apparently, my icon in the dock did not get updated when "installing" the native Postman. Maybe that could be part of an install script from you folks?
