### ISSUE TITLE
Cannot override Origin header

### ISSUE THREAD

**Issue by oblogic7** [a85/POSTMan-Chrome-Extension#2037]
I have an origin header specified on my request, but my server is receiving `file://` as the header value instead of the value I set.

![image](https://cloud.githubusercontent.com/assets/453840/15019968/c41b2698-11e5-11e6-84de-bc7870c23ca4.png)

If I copy the curl request, it works as expected, but is broken when request is executed via Postman.

**Comment by abhijitkane** [comment]
@oblogic7 This is currently a limitation in the Postman app. The XHR object doesn't allow the Origin header to be set (https://developer.mozilla.org/en-US/docs/Glossary/Forbidden_header_name). In our Mac app, we'll soon be introducing a workaround for this.

**Comment by oblogic7** [comment]
Great. Thanks for the update.
