### ISSUE TITLE
Shared collections not syncing between team members

### ISSUE THREAD

**Issue by dfmartin** [a85/POSTMan-Chrome-Extension#2038]
Our team is using postman with shared collections and environments.  I have created a collection and shared it.  Others have added some requests.  On each of our machines we are seeing that there are 7 requests.  I am only seeing 2 while another member is seeing 4.  No one is seeing all 7.  One member got all 7 by unsubscribing and resubscribing.  However, as the owner I do not have that open. I have forced a sync via settings but this didn't help.  The only thing that worked was to logout and sign back in.  Is there something we are missing or is this the intended behavior?

Thanks,
David

**Comment by abhijitkane** [comment]
@dfmartin No, the request count should always match the number of requests that show up. We're aware of one issue that causes this - this will be patched up in the next release of the app.
Could you email us at help@getpostman.com with your username or team-name, so we can check if there were any errors specific to your account?
