### ISSUE TITLE
Unable to delete cookie

### ISSUE THREAD

**Issue by zubairk-net** [a85/POSTMan-Chrome-Extension#2039]
Once I get a cookie back from server I am not able to delete it. I tried deleting cookie for same url in Chrome but it didnt get rid of cookie in Postman. I was under assumption that they might be sharing the cookies but thats not the case. Please let me know how to remove a cookie.

**Comment by abhijitkane** [comment]
@zubairk-net To control cookies, you'll need to enable and send requests through the Interceptor (enable via the satellite icon in the navigation bar, install from https://chrome.google.com/webstore/detail/postman-interceptor/aicmkgpgakddgnaphhhpliifpcfhicfo?hl=en).
You'll then be able to control cookies from chrome://settings/cookies
