### ISSUE TITLE
cannot use postman.getResponseCookie in Newman

### ISSUE THREAD

**Issue by bartpowers** [a85/POSTMan-Chrome-Extension#2040]
Hello,

I would just like to stay updated on the issue that this function is not supported via newman.

`postman.getResponseCookie is not a function 200 137ms https://...`

Please let me know if this will be addressed or if i need to work on a different platform to handle these requests.

Thanks!

**Comment by abhijitkane** [comment]
@bartpowers Can you file an issue on the Newman issue tracker - https://github.com/postmanlabs/newman/issues?
