### ISSUE TITLE
Team collection not synchronising?

### ISSUE THREAD

**Issue by Loobs40** [a85/POSTMan-Chrome-Extension#2042]
We are two users sharing a collection using the Cloud. When I update a request  the other user sees the changes immediately. When they update a request I do not see   the changes.  Postman is a new application for us, so can you advise on what the issue may be

thanks

**Comment by abhijitkane** [comment]
@Loobs40 If they update a request, you'll have to close the request if it's open in the builder, and re-open  it from the sidebar. Can you ask your team-member to update the name of the collection or request and see if that's updated in your sidebar?
If not, can you try signing out and signing back in?

**Comment by Loobs40** [comment]
Hi,

It has made no difference.

If I change the name of a request the other user sees the change immediately, but not vice versa. Could this be something to do with profiles ? It may be a coincidence but I have recently changed laptop, would that have an effect ?

thanks

**Comment by abhijitkane** [comment]
@Loobs40 Can you tell me the your username, name of the collection, and name of the request?

**Comment by Loobs40** [comment]
User=loobs40, collection name is Phase1b and I am dealing with requests in folder ‘IDS Intergration Test’. The request name  is Phase1b-SIMH_FMS_Refer_008.  I am still seeing it as Phase1b-SIMH_FMS_Refer_0088 ,

Values have been changed in the request but I am not seeing them . Below is what I see, but the ‘asdf’ has been updated by the other team member to another string

<DataAttribute>
      <Name>48dda42d-4ca5-45d3-8213-a7144b4f83f0</Name>
      <Value>asdf</Value>
    </DataAttribute>

Thanks

Lucy

**Comment by abhijitkane** [comment]
@Loobs40 I think your app will have two collections called Phase1b (One which you own - this will be with a gray icon, one which the other user owns and you have subscribed to - this will be with an orange icon). Can you check the other collection?

**Comment by Loobs40** [comment]
I have renamed the one in grey which is owned by me  to ‘phase1b-old’ so It does not confuse

The other team member and I should only be working on the ‘Team’ collections so we can collaborate with updating . Is that correct ?

Me team member has changed the name  of the request so the last characters  to 00888 but I am still only seeing 0088

**Comment by abhijitkane** [comment]
Hm..the name of the request in our records seems to be Phase1b_SIMH_FMS_Refer_0088. Can you ask your team member to log out, log back in, and then make the change?

**Comment by Loobs40** [comment]
She logged out and logged in and now when she makes updates I can see them. Unfortunately  as a result all updates she has been making this morning have been lost as seemingly her updates were not being saved.

Do you know why this could have happened ? She did not receive any error messages while being logged in to warn her that her updates were not being saved to the cloud

**Comment by abhijitkane** [comment]
@Loobs40 We've identified two possible causes for this, and will be patching them up in the next release of the app.

**Comment by abhijitkane** [comment]
@Loobs40 Can you confirm this working in the latest version of the app?

**Comment by Loobs40** [comment]
Do we need to install a new version of Postman ?

**Comment by abhijitkane** [comment]
What version are you currently on? The version should show up in Settings (wrench icon in the top-right) > About.

**Comment by Loobs40** [comment]
4.2.0
win / x86-64
Chrome 50.0.2661.102

**Comment by abhijitkane** [comment]
That should have all the fixes too. Are you still seeing the issue after logging out and logging in?

**Comment by Loobs40** [comment]
We’ll check today as we use it

**Comment by a85** [comment]
Closing as fixed. Will reopen if this issue occurs again.
