### ISSUE TITLE
Feature to close multiple tabs like in Chrome

### ISSUE THREAD

**Issue by ianomad** [a85/POSTMan-Chrome-Extension#2043]
Feature to close multiple tabs like in Chrome.

Basically it would be really nice to have it like in Chrome (middle mouse to close/close all other tabs/close all tabs on right-left, etc.)

**Comment by SamvelRaja** [comment]
@ianomad  We had included the whole new Context menu which pops up with the options to resolve your problem 😄 
![Uploading Screen Shot 2016-12-02 at 7.30.09 PM.png…]()
