### ISSUE TITLE
Mac Application cookie access from tests snippet

### ISSUE THREAD

**Issue by macpie** [a85/POSTMan-Chrome-Extension#2044]
Hi,

This is a feature request.
It would be real useful if the `postman` object (in the tests snippet) could have access to the cookies.
So that before or after a request I can add/remove/edit a specific cookie.

A concrete example would be to remove a cookie after a logout request.

Thank You!

PS: Love Postman

**Comment by abhijitkane** [comment]
@macpie Can you try the `postman.getResponseCookie("cookieName")` method? You should get an object with the following keys: `"name", "value", "domain", "hostOnly", "path", "secure", "httpOnly", "session", "expirationDate"`

**Comment by macpie** [comment]
This is working for the chrome app but not for the native osx application. The native app as a cookie manager so I was wondering if the `postman` object could include function to manipulate the cookies, a `get` / `delete` should be enough.

**Comment by abhijitkane** [comment]
@macpie It should work for the native app too. Can you attach a screenshot of the cookie as shown in the cookie manager?
What's the URL of the request in whose test script you're making the postman.getResponseCookie call?

**Comment by macpie** [comment]
The `postman.getResponseCookie('sess')` is returning null.

<img width="493" alt="screen shot 2016-05-12 at 16 19 25" src="https://cloud.githubusercontent.com/assets/778101/15233422/6f0fa97a-185d-11e6-9fb8-6e84f26e007f.png">

But it is showing up here:

<img width="701" alt="screen shot 2016-05-12 at 16 19 39" src="https://cloud.githubusercontent.com/assets/778101/15233424/724c35d6-185d-11e6-9aec-5a158253e40b.png">

**Comment by macpie** [comment]
Any update on this?

**Comment by abhijitkane** [comment]
@macpie We'll be pushing a fix for this in the next release of the app.

**Comment by macpie** [comment]
Sweet, thanks!

**Comment by macpie** [comment]
Hi,

I am using v4.4.2 and I still don't see the fix. Is this issue still being worked on?

**Comment by abhijitkane** [comment]
@macpie We pushed a related fix (cookies set in a request were only available in the test script of the next request to that domain). 

This issue seems to be different - the cookie is for 127.0.0.1, but the URL includes a custom port, which is interfering with the cookie detection. We'll fix this in the next release.

For now,
1. Navigate to the directory containing Postman.app in your terminal
2. Run `brew install gnu-sed`
3. Run `gsed -i '276777s/urlObject\.host/urlObject\.hostname/g' Contents/Resources/app/js/requester.js`

**Comment by sdnts** [comment]
@macpie Are you still seeing this in the latest version (4.8)?

**Comment by macpie** [comment]
@madebysid will check. Thanks!

**Comment by macpie** [comment]
``` javascript
{
    domain: "127.0.0.1"
    hostOnly: false
    httpOnly: true
    name: "sess"
    path: "/"
    storeId: "PostmanCookieStore"
    value: "..."
}
```

The `postman.getResponseCookie('sess')` is working thanks!

Back to my original question, is there a way to remove it from test scripts (instead of using UI) ?

**Comment by sdnts** [comment]
@macpie Right now, you can only read cookies on the test script, not remove them, but I'll add this as a feature request :D

**Comment by macpie** [comment]
That be great thanks!

**Comment by codenirvana** [comment]
Closing as we are tracking similar feature request here: #3312

Refer https://github.com/postmanlabs/postman-app-support/issues/3312#issuecomment-516965288 for programmatic cookie access.
