### ISSUE TITLE
Auth -> No auth :: doesn't remove header

### ISSUE THREAD

**Issue by lrozenblyum** [a85/POSTMan-Chrome-Extension#2045]
SCENARIO:
Send a request using Basic Auth
Change Authorization type --> No auth
Send a request

EXPECTED:
No 'Authorization' header is sent when 'No auth' is selected

ACTUALLY:
Old 'Authorization' header is sent

**Comment by abhijitkane** [comment]
@lrozenblyum Hm..the auth helpers only add headers. Once a header has been added, the 'Auth helpers' section cannot remove it. But I see what you mean - we'll try and improve the UX around this.

**Comment by shamasis** [comment]
side-effect fix from: https://github.com/postmanlabs/postman-app-support/issues/1463

**Comment by kamalaknn** [comment]
@lrozenblyum starting from `5.3.1` Postman will not save the headers or URL parameters `Authorization` section adds.

So switching to `No Auth` would clear the Auth header. Also, note that since Postman does not save the auth headers with the request you do not have to manually change the auth to `No Auth`.

Please note that this feature is only available on our native apps.

**Comment by lrozenblyum** [comment]
Thank you!

**Comment by upendrarangudu** [comment]
I still face the same issue with Postman V7.0.6

SCENARIO:
Send a request using Basic Auth
Change Authorization type --> No auth
Send a request

EXPECTED:
No 'Authorization' header is sent when 'No auth' is selected

ACTUALLY:
Old 'Authorization' header is sent

How can I make sure that new auth values are reflected as part of the request?.

**Comment by sujayvenaik** [comment]
Hey @upendrarangudu 
I tried replicating this using our echo endpoint i.e. `http://postman-echo.com/get` which is a ping pong endpoint returns whatever it is sent with.

I had basic auth with some credentials sent the request, checked that the auth header was sent. Changed request to no auth then the auth header was not sent.

Can you test it once again? Or help us with a screen recording so we could exactly replicate this.

**Comment by upendrarangudu** [comment]
Yep..my bad..works fine.
