### ISSUE TITLE
Ability to view the full raw HTTP transaction.

### ISSUE THREAD

**Issue by risingfish** [a85/POSTMan-Chrome-Extension#2047]
This is essentially a re-request of the following ticket: https://github.com/postmanlabs/postman-app-support/issues/119 . That functionality, which is very very useful, seems to of been left out of the the new Postman client. It is especially important now that you can't open a web inspector window in the new client.

**Comment by abhijitkane** [comment]
@risingfish Are you talking about the Mac app? You can go to View>Toggle Dev Tools to open the DevTools window.

**Comment by risingfish** [comment]
Ahh, no I am talking about the Chrome plugin. Did I put this ticket in the wrong place?

**Comment by abhijitkane** [comment]
@risingfish No, you can view the DevTools for the Chrome app too - http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/
