### ISSUE TITLE
Bug in swagger import

### ISSUE THREAD

**Issue by wcandillon** [a85/POSTMan-Chrome-Extension#2048]
The following swagger files:
https://dl.dropboxusercontent.com/u/1487285/swagger-aggregated.json

Give the following output:
https://www.dropbox.com/s/sd591bl7m5hq0an/Screenshot%202016-05-06%2017.38.57.png?dl=0

There is one slash too much: `http:///`

**Comment by abhijitkane** [comment]
@wcandillon Thanks for reporting this. We'll try and push a fix for this soon.
This only happens when the url begins with `{{`. Node's url.resolve function treats `{` and `}` as special characters.

**Comment by abhijitkane** [comment]
@wcandillon Can you confirm this fixed in the latest version of the app (4.2.1)?

**Comment by wcandillon** [comment]
@abhijitkane I cannot get 4.2.1 yet: "You are up to date! Postman v4.2.0 is the latest version."

**Comment by abhijitkane** [comment]
@wcandillon Ah - that's the Mac app. 4.2.0 should have the fix too.

**Comment by wcandillon** [comment]
doesn't work on my side, I see a triple slash

**Comment by abhijitkane** [comment]
@wcandillon Sorry, got the version numbers messed up. 4.2.2 shows the URL correctly. Just imported your dropbox link.

**Comment by wcandillon** [comment]
@abhijitkane still can reproduce it with 4.2.2

**Comment by abhijitkane** [comment]
@wcandillon Can you confirm the version again? I can see only 2 slashes when I import the link.
![swaggerimport](https://cloud.githubusercontent.com/assets/681190/15659449/366d2f0e-26e8-11e6-8bb2-2f94eefdb614.gif)

**Comment by wcandillon** [comment]
@abhijitkane It works great if you import from a link but not if you import the same file downloaded on your computer.

**Comment by abhijitkane** [comment]
@wcandillon That's odd - works for me with a saved file as well. The code flow is exactly the same for links and files.
