### ISSUE TITLE
Get Request Token dynamically when running a collection of API using Collection Runner

### ISSUE THREAD

**Issue by RonakThakkar** [a85/POSTMan-Chrome-Extension#2050]
Hi,

I have several API's in my project that are that are secured using OAuth2.0. I use OAuth2.0 in Postman to call those API's. These works fine when I call them individually in postman and add token by clicking saved token.

But, I have created a collection of those API in Postman. Now problem is that when I run that collection using collection runner, how do I get Request Token dynamically and add them to each request.

**Comment by abhijitkane** [comment]
The OAuth2 tokens are not tied to a request. Once you get the token, you can manually save it into an environment, and then use the variables in the requests.

There's no way to start the manual OAuth2 process during an automatic collection run.

**Comment by RonakThakkar** [comment]
It would be good if there is a possibility to trigger OAuth2 process in some pre-request scripts.

I was thinking to create a first dummy request in collection where I can invoke OAuth2 process in pre-request script and then enter login credentials in window that opens and then save returned token in Global Variable called Authorization which can be used in subsequent request.

It would also be a good idea to extend OAuth2.0 flow to take additional login credentials as input to prevent opening login window.

Combining all above will enable running collection as a part of build without any manual intervention.

As OAuth2.0 is becoming popular in market, this scenario would become a must requirement for those enterprise users that run postman collections as a part of their continuous integration.

I would say Postman is awesome tool and can be even more awesome by adding more feature for integration in continuous integration.

**Comment by ghost** [comment]
I have the same issue. What Ronak is requesting is a must feature to us. We started using Postman which is a great tool but the lack of an automated Oauth2 get token mechanism will force us to find another solution. All of our tests must be automated and having to manually get a toekn is not viable to us

**Comment by dconlisk** [comment]
+1 for this feature

**Comment by Saibobba** [comment]
+1 for this feature. 
Waiting for this feature to be available. 
Right now, even if we are automating the calls, we have to still add the token to every call manually.

**Comment by shamasis** [comment]
Can you try pm.sendRequest in your pre request script and save the token in a variable for now. We upgraded many parts of oauth2 in v5.3 native app and we are assessing the best way to get automated refresh taken care of.

**Comment by pratiks** [comment]
Absolutely a must-have.  +5.

**Comment by safadig** [comment]
ditto

**Comment by Saibobba** [comment]
@shamasis  Yes. For now, i am able to declare a token variable and sending the token into it's value.
It's just one step every time before i make the calls.
Automated refresh could be the best feature !!

**Comment by pratiks** [comment]
The problem with a pre-request is we have 10s of 100s of requests.  Each one will require an update to the pre-request script if our auth mechanism changes.   This is a maintenance nightmare. 

Calling nextRequest() and a subsequent retry is a not a viable solution for semantic checks, etc.

**Comment by shanmugamganesan** [comment]
+1 I am looking forward to have this functionality.

**Comment by amagsomb-ford** [comment]
+1 we need it now! lol

kidding aside, looking forward too on this feature.

**Comment by tegomass** [comment]
Hey guys,
I was looking for something similar. I tried to manage OAuth2 with succession of GET/POST requests, but there are encrypted values generated to send in order to success the authentification that take time to manage, so I finally didn't go further this way.

Instead, I automatize the OAuth2 part and get the token using a browser like headless Chrome (or PhantomJS), then use the token to my postman scripts, without any human interactions (you could integrate that easily to an CI environment like Jenkins, Travis or Teamcity).

On a JS file, do the following : 
- Use [puppeteer](https://github.com/GoogleChrome/puppeteer) to control headless Chrome. You can do click/type actions to simulate an user interaction.
- Store the token in a variable
- Use [newman](https://github.com/postmanlabs/newman) to launch your scripts collection, using the token as a postman global variable

**Hints** : 
```
const puppeteer = require('puppeteer');
const newman = require('newman');

//Puppeteer part - simulate the user interaction with the page
const browser = await puppeteer.launch();
const page = await browser.newPage();
page.goto(url);
page.type(user, account.username);
page.type(pass, account.password);
page.click(connect);
const tokenField = "#token";
page.waitFor(tokenField);
const token = await page.evaluate((tokenField) => document.querySelector(tokenField).value, tokenField);
console.log(token); //here is the token

//launch the postman collection through Newman
newman.run({
        collection: require('./blabla.postman_collection.json'),
        reporters: 'cli',
        environment: postmanFile, //Consider that the token has been added to the file
    }).on('start', function (err, args) {
        console.log('Running a postman collection...');
    })
});
```

Hope this could help.

**Comment by a85** [comment]
Collection level pre-request scripts are available for all sorts of custom flows that can be specified once and will apply for the whole collection. Updating progress on other threads about specific auth behavior.

**Comment by Burbaka** [comment]
In my company, we decided to use [Paw](https://paw.cloud) as they have this out of the box.

**Comment by Kritika2808** [comment]
must have feature in postman +1

**Comment by Guilherme-Sensedia** [comment]
News update in Postman for this?

**Comment by joycebaby** [comment]
We use [Restbird](https://restbird.org/blog/2018/09/01/automate-testing-oauth2.html) our project for they have a solution for this case.

**Comment by bartdk-be** [comment]
> Collection level pre-request scripts are available for all sorts of custom flows that can be specified once and will apply for the whole collection. Updating progress on other threads about specific auth behavior.

@a85 : This thread is still open I guess ? Seems like a must have for many people. I'm wondering why no default implementation is available (thread +2years old ?)

**Comment by lorinc** [comment]
yepp, still open. And while there are tutorials out there how to do this, it is also loud and clear - people are choosing other products, because of the friction Postman adds to this feature

**Comment by dsidirop** [comment]
> The problem with a pre-request is we have 10s of 100s of requests. Each one will require an update to the pre-request script if our auth mechanism changes. This is a maintenance nightmare.
> 
> Calling nextRequest() and a subsequent retry is a not a viable solution for semantic checks, etc.

Well can't argue with this logic. Man has a point here.

**Comment by bartdk-be** [comment]
> > The problem with a pre-request is we have 10s of 100s of requests. Each one will require an update to the pre-request script if our auth mechanism changes. This is a maintenance nightmare.
> > Calling nextRequest() and a subsequent retry is a not a viable solution for semantic checks, etc.
> 
> Well can't argue with this logic. Man has a point here.

@dsidirop / @pratiks : I'm using a pre-request script at the collection level. This works fine, and prevents a maintenance nightmare. Any particular reason this is not an option for your scenario ?

**Comment by d82ej9du7** [comment]
@tegomass hi, one question please. After that you have the "token" value, how do you add it in the file of the enviroment "postmanFile"? 
Thanks you in advance.

**Comment by tegomass** [comment]
@d82ej9du7 Hey, currently, I don't use a file, but an object directly.

...
environment: {
    var1: 'value1',
    token: tokenFromAbove
}
...

**Comment by d82ej9du7** [comment]
> currently

Thanks, i will try :)

**Comment by AarchaKulkarni** [comment]
Hi I am new to Postman and so am I for this forum also.
Can someone tell me how can I automate the running of the post request collectively in the runner. I have something in the header and I am using bearer token and I am using the token generated from this website https://jwt.io/
I believe it oauth

**Comment by AarchaKulkarni** [comment]
So basically Authorization is  Bearer <TOKEN> | Token needs payload {user:   <userID>} and signed with shared secret. Token expires every 5 minutes

**Comment by KreuzigTobias** [comment]
Hey guys,
I am still looking for a way to automate the whole OAuth2 thing, with grant_type: implicit. I thought about the solution of @tegomass, it might work but looks rather hacky, no offense though.

I couldn't find the said tutorials on that matter, @lorinc, if you could help me out there that would be awesome.
> yepp, still open. And while there are tutorials out there how to do this, it is also loud and clear - people are choosing other products, because of the friction Postman adds to this feature

Last but not least +1 for feature
P.S.: @a85, as you can see above there is quite a lot of people looking forward to this feature, me as well. If it is not supported, you will loose a lot of users (professionals) that have to move to some other software, even though, they, as well as me, like Postman a lot. So it would hurt both sides

**Comment by tegomass** [comment]
Hi,
Another solution is to create a web service (e.g. using express.js), then when you call on this webservice, it will do all the trick I described above with puppeteer and returns the token.

In the postman client, simply do a GET on <api>/token, you will receive the token, then you add it to the global/env variables, it should work. 

Cya

**Comment by practition** [comment]
Some posters here are defecting to other tools like Paw and Restbird because they can't pre-request OAuth2 tokens in Postman. Hey Postman team, are you listening to your customers? OAuth2 is too popular to ignore. 
+1 to add this feature

**Comment by BeingSujeetK** [comment]
In OAuth Authorization Code flow, the user fills the form with the client details and clicks the Request Token button, Postman postman prompts the user for login and then generates the token.
In the successive clicks of Request Token button, Postman doesn't prompt the user for login. It remembers.

It would be much convenient for the user if this could be automated through the pre-request scripts.

Also, the "GET NEW ACCESS TOKEN" form details gets updated evenrywhere in Postman if you update in one requests. there must be an option to choose the scope.

**Comment by morrisond91** [comment]
> In OAuth Authorization Code flow, the user fills the form with the client details and clicks the Request Token button, Postman postman prompts the user for login and then generates the token.
> In the successive clicks of Request Token button, Postman doesn't prompt the user for login. It remembers.
> 
> It would be much convenient for the user if this could be automated through the pre-request scripts.
> 
> Also, the "GET NEW ACCESS TOKEN" form details gets updated evenrywhere in Postman if you update in one requests. there must be an option to choose the scope.

Did you ever find out how to automate access token retrieval for authorisation_code client?

In my head, there needs to be a way to gain an authorisation code by supplying creds, then exchange that code for an access token... I cant figure it out!

I have posted a question on StackOverflow https://stackoverflow.com/questions/64229162/postman-access-token-retrieval-using-authorisation-code-grant-type hopefully I'll get some brain dump!

**Comment by aleshamccann** [comment]
Why was this Closed if there is still no solution? I need a way to automate tests without having to manually get an access token through the Postman helper.

**Comment by jacob-haller-roby** [comment]
Hey Postman business execs.

I've tried searching for a valid answer to this problem for a few days.  No results that meet my needs.

Switching to a different service now.  Don't want to, I'm familiar w/ postman, and not eager to learn a new tool.

But hey, you forced me into it.  Good job failing to address a highly requested issue for 4 years, and closing the request thread without a solution.

A+.

**Comment by KeliOC94** [comment]
Hey, 

Currently looking for this functionality to run a test collection and have been unsuccessful, I would love to know if anyone has produced a work around or if postman has added this in the meantime. Considering a new tool now which I would prefer to stay. Thanks!

**Comment by davidbzip** [comment]
Same here, having to manually paste the auth token every time I run tests makes this cumbersome.
