### ISSUE TITLE
REST API to publish the documentation?

### ISSUE THREAD

**Issue by wcandillon** [a85/POSTMan-Chrome-Extension#2051]
We would like to automatize the process of publishing the API documentation.

**Comment by dhoyt** [comment]
This is something that me and my CTO were discussing the other day and were saying it would be great to have this. As soon as Jenkins get done with the build and deploy, we would love to auto publish the API.

**Comment by a85** [comment]
The first version of the Cloud API is out. Documentation here at https://api.getpostman.com (published using Postman Cloud). POST calls coming soon for Collections so you should be able to automate this directly from Jenkins. :)

**Comment by wcandillon** [comment]
This is very cool!

**Comment by wcandillon** [comment]
@a85 I'm looking forward to be able to post/publish collection/documentation.

**Comment by a85** [comment]
POST/PUT routes are coming soon. Should make the entire workflow seamless.

**Comment by wcandillon** [comment]
@a85 Looking forward to it.

**Comment by a85** [comment]
Available in the Postman Pro API now! https://api.getpostman.com
