### ISSUE TITLE
Error while evaluating the Pre-request Script: Failed to execute 'postMessage' on 'Window': An object could not be cloned

### ISSUE THREAD

**Issue by ghost** [a85/POSTMan-Chrome-Extension#2053]
### Error Details

Having issue with the latest update, the Pre-request Script bellow was working well for several weeks but suddenly stopped execution by showing this error:
`Error while evaluating the Pre-request Script: Failed to execute 'postMessage' on 'Window': An object could not be cloned`
It seems more like an internal postman error just happens before starting the Pre-request script:
### Pre-request Script

// Generate A local X-Correlation-Token
postman.setEnvironmentVariable('uniqueCorrelationToken', guid);

function guid() {
  function s4() {
    return Math.floor((1 + Math.random()) \* 0x10000)
      .toString(16)
      .substring(1);
  }
  return s4() + s4() + '-' + s4() + '-' + s4() + '-' +
    s4() + '-' + s4() + s4() + s4();
}

var randomNumber = getRandomInt(990000, 99000000);
postman.setEnvironmentVariable('randomNumber', randomNumber);
postman.setEnvironmentVariable('site', 'www.test.com');

function getRandomInt(min, max) {
    return Math.floor(Math.random() \* (max - min + 1)) + min;
}

**Comment by abhijitkane** [comment]
Change `guid` to `guid()`. In the first line. Environment variables cannot be set to to function definitions.
