### ISSUE TITLE
Please support for POST of file in message body with Content-Type application/octet-stream

### ISSUE THREAD

**Issue by rfyiamcool** [a85/POSTMan-Chrome-Extension#2056]
Thanks

**Comment by codenirvana** [comment]
You can specify the `Content-Type` in the request headers while posting the binary file.

<img width="708" alt="Screenshot 2019-06-27 at 1 54 14 PM" src="https://user-images.githubusercontent.com/4865836/60249826-3246a700-98e3-11e9-87a6-151da56ce325.png">
