### ISSUE TITLE
Feature Request: Track expires_in for OAuth2 access tokens

### ISSUE THREAD

**Issue by mikaey** [a85/POSTMan-Chrome-Extension#2057]
Hello,

I'm running Postman 4.1.3 as a Chrome app.

My company serves up a REST app which is OAuth2-compliant.  When requesting an access token, the response contains a property named `expires_in`, which contains the number of seconds until the access token expires.  It would be nice if Postman had an option to automatically remove access tokens that had expired from the "PREVIOUSLY USED" list (on the Authorization tab).

**Comment by giridharvc7** [comment]
We don't want to remove expired access tokens automatically as people also use postman as a debugging tool. This means that some would expect to test APIs with expired token. With that said, we also have a view which shows expired access token and you can manually delete them. 

<img width="722" alt="Screenshot 2021-04-14 at 3 33 47 PM" src="https://user-images.githubusercontent.com/1040583/114693031-cf800300-9d36-11eb-9a53-029da9075aa9.png">

We will take the essence of this issue and track this under #2452
