### ISSUE TITLE
No "Save helper data to request" option for OAuth 2.0

### ISSUE THREAD

**Issue by mikaey** [a85/POSTMan-Chrome-Extension#2058]
1. Postman version: 4.1.3
2. App: Chrome app
3. OS details: OS X 10.11.4
4. Is the Intercepter on and enabled in the app: No
5. Did you encounter this recently, or has this bug always been there: As far as I can tell, it's always been there
6. Expected behaviour: "Save helper data to request" checkbox is shown when the "Type" drop-down is set to "OAuth 2.0" on the "Authorization" tab, allowing OAuth 2.0 settings to be saved with the request
7. Console logs: N/A
8. Screenshots:

![image](https://cloud.githubusercontent.com/assets/10555491/15152046/838d471a-1699-11e6-8588-1ba3446cc49e.png)

**Comment by abhijitkane** [comment]
The OAuth2 helper doesn't need to 'compute' a signature from the request at runtime (unlike OAuth1 etc.). But it might make sense to store the Oauth2 access token + refresh token with the request, so that the request can be sent with the updated access token each time. Will look into this.

**Comment by mikaey** [comment]
At the very least, it would be nice if the authorization type were saved with the request, so that I don't have to select OAuth 2.0 every time I open my request.

**Comment by harryi3t** [comment]
We are tracking this feature request here https://github.com/postmanlabs/postman-app-support/issues/4636
