### ISSUE TITLE
HTML Tags such as Bold should continue to be supported inside the collection names

### ISSUE THREAD

**Issue by benmalinowski** [a85/POSTMan-Chrome-Extension#2059]
It would be nice for Postman to continue supporting HTML tags inside the collection. In the original postman I was using the bold tags to distinguish between different categories under the collection. See my screenshot below. I read that basic support would be in 4.10 but it doesn't appear to be working for the bold tag. 

Please include the following:
1. Postman Version: 4.13
2. App (Chrome app or Mac app): Chrome
3. OS details: Windows 7
4. Is the Interceptor on and enabled in the app:  no
5. Did you encounter this recently, or has this bug always been there:  Since postman 3.0
6. Expected behaviour*\* see above
7. Screenshots (if applicable)**

![image](https://cloud.githubusercontent.com/assets/10727361/15153236/72d3cf2c-16a6-11e6-8113-4cad51a5bb53.png)

**Comment by abhijitkane** [comment]
@benmalinowski That was a bug in the app. The request name is a simple string, and does not support markdown or HTML. You can use the request description for richer markdown-based formatting.

You can also use folders to categorize requests.
