### ISSUE TITLE
How It supports multi-threading, stress tests

### ISSUE THREAD

**Issue by rplees** [a85/POSTMan-Chrome-Extension#2060]
Mac app How It supports multi-threading, stress tests？

**Comment by mstaalesen** [comment]
As of right now, it doesn't. I think they have said that this is something that they are working on implementing. But I don't work for Postman, so I guess it would be best if they confirmed it too :)

**Comment by shamasis** [comment]
It's been some time to reply to this thread! Apologies for that. The postman app and the runner is designed to send a single request at a time. As such, true load testing is not currently possible. We are work on ways to remotely load test your apis using collections.

Closing this thread. We will post an update when something relevant comes up.
