### ISSUE TITLE
Remember file paths in the request builder

### ISSUE THREAD

**Issue by fstr** [a85/POSTMan-Chrome-Extension#2061]
When working with form-data and the file fields, buggy behavior occurs. See below how to reproduce.
1. Postman Version:
   4.1.3
2. App (Chrome app or Mac app):
   Chrome 50.0.2661.94
3. OS details:
   OS X / x86-64 10.11.4 (15E65)
4. Is the Interceptor on and enabled in the app:
   Yes
5. Did you encounter this recently, or has this bug always been there:
   Just encountered recently. Don't know if it has been there already.
6. Expected behaviour:
   - Each file I choose only belongs to one request and does not influence other requests
   - The file field displays the currently chosen file correctly after a Postman restart
   - It is possible to use the same file after the bug from the first point is fixed
#### step 1
- Create a new collection
- Create a new POST request to `http://echo.getpostman.com/post`
- Set as values in the Body:
  <img width="1348" alt="screen shot 2016-05-11 at 18 04 36" src="https://cloud.githubusercontent.com/assets/285992/15187836/0621861e-17a3-11e6-964c-2a596296ed9e.png">

```
form-data
image: foobar.jpg, type File
text: mytext, type Text
```
- Save the request in your collection
- Send the request, everything works fine, you've sent `foobar.jpg`
#### step 2
- Duplicate the request
- Choose a different file for the image parameter

```
form-data
image: baz.jpg, type File
text: mytext, type Text
```
- Save the request in your collection
- Send the request, everything works fine, you've sent `baz.jpg`
#### step 3 (bug 1)
- Go back to your first request
- The request will now show as `image` parameter in the Body the file `baz.jpg`
- To be expected is to still have the file `foobar.jpg`
- Save the request
- Send the request, it is still sending `foobar.jpg`, although the interface is saying `baz.jpg` will be sent
#### step 4 (bug 2)
- Still being in the first request, now set the `image` parameter in the Body to the file `baz.jpg` from your filesystem (the file you used for the second request initially)
- The request will still send `foobar.jpg`. 
#### step 5 (bug 3)
- Close postman
- Open postman
- The `image` parameter in both requests will be empty in the interface (choose file)
- Both requests are still sending the previously set file

**Comment by Jelloman** [comment]
I've seen similar issues within a single session.  But for me, mostly, Postman 4.2.1 simply never remembers the file I've selected for a file field in the Body.  I have to re-"Choose File..." every time I launch Postman.

**Comment by AndrewNapier** [comment]
We would like to utilise sending large files to one of our end-points as part of our automated test-suite.  The fact that the stored collection won't include the file-path means we can't do this.

Could you please provide some sort of likelihood of this issue being addressed? 

Thanks in advance.

**Comment by shamasis** [comment]
@fstr @AndrewNapier - this feature has now been added to Postman Canary channel and would be our in production soon. More details at https://github.com/postmanlabs/postman-app-support/issues/4320#issuecomment-490749103

Closing this issue since we are at final stages of release tracking on a duplicate thread.
