### ISSUE TITLE
Warn about malformed JSON (feature request)

### ISSUE THREAD

**Issue by coxymla** [a85/POSTMan-Chrome-Extension#2062]
I'm the idiot who just spent a number of hours trying to debug my app  when the problem was that I had used `=` character rather than `:` in my Body.

It's my own damn fault but it would be a good feature if Postman could warn the user that what they are trying to send is malformed.

**Comment by mstaalesen** [comment]
If you have a '=' instead of a ':', Postman will let you know by a Red Square with a white X inside it, on the line that the problem is.

You have to have selected "JSON (application/json)", which is an option above the Body for the request itself.

**Comment by coxymla** [comment]
Thanks for that; guess I should have hovered over it.
