### ISSUE TITLE
Send restricted HTTP headers in Mac app?

### ISSUE THREAD

**Issue by mliq** [a85/POSTMan-Chrome-Extension#2064]
Please include the following:
1. Postman Version: 4.2
2. App (Chrome app or Mac app): Mac App
3. OS details: OSX 10.11.4
4. Is the Interceptor on and enabled in the app: I do not see how to enable it in this app.
5. Did you encounter this recently, or has this bug always been there: Just tried using the Mac app
6. Expected behaviour: Enable Interceptor and work, like in the Chrome app.
7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app): 
   requester.js:204426 Refused to set unsafe header "Origin"_sendRequest @ requester.js:204426(anonymous function) @ requester.js:204278(anonymous function) @ requester.js:205645(anonymous function) @ requester.js:156248(anonymous function) @ requester.js:158711triggerEvents @ requester.js:156289triggerApi @ requester.js:156276eventsApi @ requester.js:156075Events.trigger @ requester.js:156266(anonymous function) @ requester.js:205681
8. Screenshots (if applicable)
   ![image](https://cloud.githubusercontent.com/assets/7573605/15257831/f39cdc5c-190d-11e6-96d1-8e9cbeeca009.png)
   ![image](https://cloud.githubusercontent.com/assets/7573605/15257855/0f1a8272-190e-11e6-9333-9e8570df6314.png)

Some guidelines: 
1. Please file Newman-related issues at https://github.com/postmanlabs/newman/issues
2. If it’s a Cloud-related issue, or you want to include personal information like your username / collection names, mail us at help@getpostman.com
3. If it’s a question (anything along the lines of “How do I … in Postman”), the answer might lie in our documentation - http://getpostman.com/docs.

**Comment by abhijitkane** [comment]
@mliq We'll soon be releasing a version of the Mac app which doesn't have this restriction. For now, using the Chrome app + Interceptor is the only way to send restricted headers.

**Comment by borut-t** [comment]
+1

**Comment by ebomcke** [comment]
Hi @abhijitkane ,

Can you give any information on when this release would be ready? I understand that it might be difficult to pinpoint an exact date, but it would be great to know what 'soon' means (couple of days, weeks, months? ).
By the way, as it's my first time commenting here I'll state this for the record : this is an amazing tool that you built, I had been struggling for years with API doc & testing, since I discovered Postman it made my job so much easier. So thanks !

Cheers,
Etienne

**Comment by shamasis** [comment]
@mliq @borut-t @ebomcke - hey we've gotten ready with a Canary version of our Mac app that has a whole new underlying runtime for sending and requests. 

Now you can send restricted headers like you asked for - it will come to production App soon. You can give it a spin while we smoothen out the rough edges!

http://blog.getpostman.com/2016/06/14/introducing-postman-runtime-more-power-better-control/

**Comment by ebomcke** [comment]
Hey,
Thanks for the heads up @shamasis, I'll check it out asap.
Cheers,
Etienne

**Comment by iMacTia** [comment]
@shamasis just bumped into this issue today.
When will the update come to the standard mac app?

Thanks

**Comment by shamasis** [comment]
@iMacTia - it's out in mac app v4.5.0 👍 closing issue
