### ISSUE TITLE
 Cyrillic characters are displayed incorrectly in profile selector

### ISSUE THREAD

**Issue by acelot** [a85/POSTMan-Chrome-Extension#2065]
1. Postman Version: 4.2.1
2. App (Chrome app): 50.0.2661.102
3. OS details: Windows 10 64-bit
4. Is the Interceptor on and enabled in the app: false
5. Did you encounter this recently, or has this bug always been there: always
6. Expected behaviour: Cyrillic characters are displayed correctly
7. Console logs: n/a
8. Screenshots
   ![postman-cyr-chars-issue](https://cloud.githubusercontent.com/assets/1065215/15275540/7a58ca9c-1af0-11e6-9c50-b4887cce8053.png)

**Comment by abhijitkane** [comment]
@acelot Can you head to https://app.getpostman.com/dashboard/edit, and re-enter your name?
A subsequent app restart should solve this.

**Comment by acelot** [comment]
@abhijitkane Thanks! Problem solved.
