### ISSUE TITLE
very long text field freezes Postman and spikes CPU

### ISSUE THREAD

**Issue by 2x2xplz** [a85/POSTMan-Chrome-Extension#2066]
Postman 4.2.1
win / x86-32
Chrome 50.0.2661.102
I'm on Win7/64-bit with 8gb RAM.
Interceptor installed but not on

When I paste very long text into a Postman form-data field (i.e. submitting very long text input), Postman freezes, CPU usage spikes, and I can't actually send any HTTP requests.

Simple example, create a new request, POST to www.example.com. Click "body," in the first field set "key" to "aaa" and for value, paste the full text of Hamlet (copy from http://shakespeare.mit.edu/hamlet/full.html)  In my case, "Background Page: Postman" now accounts for 40-60% CPU (according to Chrome Task Manager). If I am very patient, perhaps the cursor will allow me to go to another field or to click Send, but it will be extremely slow.

Another example: instead of copying Hamlet, copy and paste the **source code** of https://www.google.com/chrome/browser/desktop/  The length is less than 1/3 of Hamlet (approx 50k characters vs 180k) but it also spikes the CPU significantly and freezes Postman.

I realize an input as long as Hamlet (about 180,000 characters) might be stressful due to its length but Postman did not freeze like this in the past. Postman un-freezes if you switch to "Bulk Edit" mode, however you cannot paste the entire input in this mode (Postman breaks it into multiple lines).

Possibly related to https://github.com/postmanlabs/postman-app-support/issues/1996 ??

**Comment by BrianLaughlan** [comment]
+1

**Comment by vegetableman** [comment]
@2x2xplz @BrianLaughlan Kudos to you guys for reporting this performance issue 👍 . This was a fun one to fix ^_^,  as it turned out to be a chrome issue that could be fixed by disabling spellcheck on input fields (https://bugs.chromium.org/p/chromium/issues/detail?id=237433). 

Could you guys update to the latest version (4.8) and check if this issue still exists?.

**Comment by 2x2xplz** [comment]
@vegetableman  Wow, thanks for making this fix! Just tested on 4.8 (Chrome app, on Win7 x64) and worked great. No lockups after pasting these very long strings.

My workaround was pulling a long string into an Environment Variable via a request, then referencing it on the next request. It allowed the long strings to be usable without ever having to actually paste them directly into the UI. That is still useful but being able to copy/paste long strings directly is extremely important as well.
