### ISSUE TITLE
 in the last version of postman, the globals variables not saved and shown in the globals variables screen when run script from collection runner

### ISSUE THREAD

**Issue by hanyghazal** [a85/POSTMan-Chrome-Extension#2067]
in the last version of postman, the globals variables not saved and shown in the globals variables screen when run script from collection runner, but when run request by request in postman itself it is created and can see it in the globals screen, please this issue effect my tests and my time, can this issue solve as soon as possible because I'm pending 
1. Postman Version: 4.2.1
2. App (Chrome app : win / x86-32  :   Chrome 50.0.2661.102
3. OS details: windows 7 64 bit v1.12.00.AJ B14
4. Is the Interceptor on and enabled in the app: no
5. Did you encounter this recently, or has this bug always been there: in the last version only
6. Expected behaviour: it should be create and update the globals and environment variables when run the collection runner.
7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
8. Screenshots (if applicable)

Some guidelines: 
1. Please file Newman-related issues at https://github.com/postmanlabs/newman/issues
2. If it’s a Cloud-related issue, or you want to include personal information like your username / collection names, mail us at help@getpostman.com
3. If it’s a question (anything along the lines of “How do I … in Postman”), the answer might lie in our documentation - http://getpostman.com/docs.

**Comment by psaswat** [comment]
I am also facing a similar issue. I have my tests in various folders and the global variables seem to work for the folder .  Was a change made to the scope of the global variables? Also as mentioned by @hanyghazal  the UI for global variables is  not getting updated with the values. Any pointers would be helpful. Thanks!

**Comment by open-mdm** [comment]
I got this response from Postman regarding the same issue:

"We made this change in the latest release, with the aim of preventing side-effects from a run. Selecting a collection+environment, and clicking start run should have the same result each time."

I don't know what exactly they mean by this. I assume someone at Postman has the  notion that environment variables should have the same value at the beginning and end of a run? 

How do we pass the response values from one request as request params/body to another if they are in separate collections?  

Is Postman saying our collections need to be atomic?  Why? Now we need to mix different resource tests into the same collection and possibly add hacks to our APIs just to get around some seemingly odd notion that Environment variables are ... well... not variables.

-Mark

**Comment by a85** [comment]
@open-mdm If you persist environment variables then you can't run the suite again with the same values. Which is why every test suite system has a setUp and teardown function. Your collections need to be shared in their entirety and run in the exact same order by every single person and will break for someone else who does not run it in the same order.

Considering that now Postman has made this mistake of having persistence, I believe we will need to add another setting in the Collection Runner or somewhere else.

**Comment by open-mdm** [comment]
If there are env variables that must stay static  for everyone on our team, then we create our own conventions (e.g. naming with "_<name>" -- we haven't had to do that however).  

But we MUST have variables that can be used as intermediate values between collections as they are run in sequence -- these values will be different  from person to person -- and it is understood by the team these are treated as temporary variables. Setting an environment variable that is understood to be a temporary value works perfectly.

As a datapoint, we have very few variables that must be static for everyone -- and everyone knows to not touch them.

To just take away the feature is really a setback.  I've had to load an old version of Postman.

**Comment by a85** [comment]
It's wrong for several reasons which I won't communicate here. Data persistence and global state are known evils and entire books have been written about it - check anything written on Javascript. The problem that I pointed out in my previous comment are severe and you are going to run into them when you try to automate this. Most Postman users avoid this and which is the whole reason for having Collections as a unit.

Again, as I said it's our mistake which has led to use cases like yours.

**Comment by open-mdm** [comment]
And the bigger mistake to just take it out without warning.  You have a real product now and customers don't appreciate being treated like they don't matter.

**Comment by a85** [comment]
Yeah. Sorry about that. This will be back in a future version and you can go back to the older way.

**Comment by open-mdm** [comment]
Np... good to hear. I too do not want to get into a comp sci philosophical debate but if we want to potentially shoot ourselves in the foot, then that is our prerogative. 

Great product btw :^)

**Comment by a85** [comment]
Oh people have blown their heads off and then blamed us. We are not perfect. We make mistakes - which is why this issue tracker exists.

Thanks for being patient.

**Comment by psaswat** [comment]
I went through the comments above. I guess my question is what is the scope of global variables?  Just a description of our test setup . We have similar tests grouped in folders . The earlier tests in the workflow set some global variables which are used by the tests in the next or subsequent folders. After the last update here is the issue which we are seeing . The tests in the same folder where the variables are set seem to be able to use them. However the tests in other folders are not able to see those . The UI where the global variables are displayed is not updated . Is there a post or something which describes what changed with the way the global variables were handled. It would be helpful to figure out what we need to change in our now breaking tests.

**Comment by a85** [comment]
@psaswat They have global scope. Should work across folders. Is this inside the Collection Runner?

**Comment by psaswat** [comment]
Yes .

**Comment by abhijitkane** [comment]
@psaswat Are you selecting individual folders to run in the runner? Or are you selecting the whole collection?

**Comment by psaswat** [comment]
Tried both. Earlier, it used to work for both single folder and entire collection .  Outside the collection runner it seems like its working the way it used to before .

**Comment by abhijitkane** [comment]
@psaswat Can you import this collection - https://www.getpostman.com/collections/b5798ce48bc636a82dd7, and run it _only_ in the runner? 
The request in the first folder sets a global variable which is used by the request in the second folder. Both tests should pass.
<img width="805" alt="screen shot 2016-05-17 at 00 44 29" src="https://cloud.githubusercontent.com/assets/681190/15300876/89e76986-1bc8-11e6-8278-5a6d8152bf7c.png">

**Comment by psaswat** [comment]
The entire collection works. I ran our tests too and for the entire collection, they are working . But if I run the folders one at a time they fail.

**Comment by abhijitkane** [comment]
@psaswat @open-mdm @hanyghazal In v4.2.2 of Postman, we've included a 'Persist Variables' option in the runner that should let you mimic the old behavior.

**Comment by open-mdm** [comment]
Just checked it out.  Thank you!

Keyboard shortcuts coming soon?

**Comment by guboi72** [comment]
Where is the documentation for the "Persist Variables" option ? That could be confusing.

**Comment by guboi72** [comment]
Where is the documentation for the "Persist Variables" option ? That could be confusing.

**Comment by sdnts** [comment]
@guboi72 The `Persist Variables` option will persist your variables from the Runner window to the main Postman window. With this unchecked, all changes to the environment that you make in the Runner window stay there.

Unchecking it has the effect of returning your environment back to the same state it was in before the run started.

Thanks for pointing this out, we'll update our docs to include this as well.
