### ISSUE TITLE
Import collection from json changes GUIDs

### ISSUE THREAD

**Issue by ghost** [a85/POSTMan-Chrome-Extension#2069]
Using Postman 4.2.1 on Chrome App

If you download a collection to json, then import that collection, postman recognizes that it's the same collection and prompts you to overwrite or create a new collection. If you overwrite and then export again, all of the guids are changed. GUIDs should not be changed when importing, especially when overwriting a collection with the same GUID.

**Comment by abhijitkane** [comment]
@bpeikes-tl The issue here is that the IDs are not stripped while exporting. The GUIDs only make sense inside the Postman ecosystem. 

We'll soon be supporting a new collection format that doesn't include IDs when exporting.

**Comment by abhijitkane** [comment]
@bpeikes-tl You can now export in the v2 format which strips IDs while exporting.
