### ISSUE TITLE
run "pmproxy" throw an error

### ISSUE THREAD

**Issue by wshm7366298** [a85/POSTMan-Chrome-Extension#2070]
Please include the following:
1. Postman Version: 4.2.1
2. App (Chrome app or Mac app): Chrome app
3. OS details: win 10
4. Is the Interceptor on and enabled in the app: yes
5. Did you encounter this recently, or has this bug always been there: yes
6. Expected behaviour:
7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
8. Screenshots (if applicable)
   ![1](https://cloud.githubusercontent.com/assets/10624622/15346099/25049000-1ce7-11e6-97d8-a40d7fde00fc.png)
   ![2](https://cloud.githubusercontent.com/assets/10624622/15346101/2c5471ae-1ce7-11e6-8806-76318f322bfd.png)

Some guidelines: 
1. Please file Newman-related issues at https://github.com/postmanlabs/newman/issues
2. If it’s a Cloud-related issue, or you want to include personal information like your username / collection names, mail us at help@getpostman.com
3. If it’s a question (anything along the lines of “How do I … in Postman”), the answer might lie in our documentation - http://getpostman.com/docs.

**Comment by a85** [comment]
The pmproxy tool has been deprecated in favor of the in-built proxy inside Postman native apps. That's much easier to set up and work with. You can get them here: www.getpostman.com/apps
