### ISSUE TITLE
Feature request : Postman cloud modification history

### ISSUE THREAD

**Issue by BlueInt32** [a85/POSTMan-Chrome-Extension#2071]
Team work on postman cloud is great until we need to rollback or just check a mistaken modification made by one of the team member. 
Currently it is possible to version control the collection json files with git for example but it's kind of redundant and we constantly need to import/export collections. 
What about having a collection modification history on the cloud, so that we can track who modified what in a synchronized collection ?
1. Postman Version: 4.2.1
2. App (Chrome app or Mac app): Chrome App
3. OS details: Windows

**Comment by sobtiankit** [comment]
@BlueInt32 very valid points and this is something we are actively working on. On the website, we already have an Activity Feed (https://twitter.com/postmanclient/status/732283654173495296) that lets users who modified what when. This will make it's way into the app in the next release.

That said, what we also have in the works is Revision History, where you'll be able to view/rollback in time to any state of your collection in the past.

You can track the updates in this issue or stay tuned to our Twitter feed for all updates  :)

**Comment by a85** [comment]
Activity feed is out on native apps. Revision history will be out pretty soon!

**Comment by mitchellporter** [comment]
Any update on revision history? Very excited for that functionality.

**Comment by sdnts** [comment]
@mitchellporter It's very close. The ability to restore a collection to an older state is coming soon.

**Comment by mitchellporter** [comment]
@madebysid Awesome thanks for the fast response and definitely looking forward to it cheers!

**Comment by vkaegis** [comment]
Hey guys! We've made an RFC to document our ideas on version control in Postman and it could be relevant to this discussion. Would love your thoughts and feedback on it:

https://community.getpostman.com/t/version-control/2715
