### ISSUE TITLE
Can not search with CAPITAL letter in collection search.

### ISSUE THREAD

**Issue by hirenrojasara** [a85/POSTMan-Chrome-Extension#2072]
I am having one request with TITLE " Authorization POST".

When i am searching with POST, it does not showing any requests in search results.
But when i type post, it is showing results.

Althought i try to find search  with 'a', which mostly included in all requests, it gives results.
But when i search with capital 'A', it does not showing any results.

Please include the following:

Chrome 49.0.2623.87
1. Postman Version: 4.2.1
2. App (Chrome app or Mac app): Chrome App
3. OS details: Xubuntu 16 linux / x86-64
4. Is the Interceptor on and enabled in the app: No
5. Did you encounter this recently, or has this bug always been there: Didnt rememeber
6. Expected behaviour: should allow to search with Capital lettes also.
7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
8. Screenshots (if applicable)
1. ![crop_1](https://cloud.githubusercontent.com/assets/8259826/15349484/d1925a4c-1cf0-11e6-8eda-63769e3a926c.jpg)
2. ![crop2](https://cloud.githubusercontent.com/assets/8259826/15349483/d1926028-1cf0-11e6-9a87-362201f82f44.jpg)

**Comment by abhijitkane** [comment]
@hirenrojasara Right. We've fixed this in our internal build, and will be pushing the fix in the next release.

**Comment by abhijitkane** [comment]
@hirenrojasara Can you confirm this fixed in the latest version?

**Comment by hirenrojasara** [comment]
@abhijitkane Yes. Working Fine. Looks fixed.
