### ISSUE TITLE
Cannot complete Postman installation

### ISSUE THREAD

**Issue by vkelman** [a85/POSTMan-Chrome-Extension#2073]
Please include the following:
1. Postman Version: 4.2.1.
2. App (Chrome app or Mac app): Chrome
3. OS details: Windows 7 64 bit
4. Is the Interceptor on and enabled in the app: n/a
5. Did you encounter this recently, or has this bug always been there:  always

I cannot install Postman. Chrome asks me to allow installation then displays "Checking" indefinitely.

**Comment by abhijitkane** [comment]
@vkelman Can you attach a screenshot? Also, can you try installing the staging version - https://chrome.google.com/webstore/detail/postman-rest-client-packa/mgicbpdmnpnfckafakeoiomkjcplfcld, and check if that works?

**Comment by abhijitkane** [comment]
@vkelman Feel free to open the issue if you're still seeing this.
