### ISSUE TITLE
MRU URLs always revert to history Item when modifying and trying to send via keyboard.

### ISSUE THREAD

**Issue by kaosdg** [a85/POSTMan-Chrome-Extension#2074]
Using Postman Mac App 4.2.0, on El Capitan 10.11.4 (15E65)

When I select a URL from the MRU dropdown, if I then modify that url and send the request via keyboard (command-Enter), the URL will always revert to the unmodified history URL then send the old request.

(I can successfully send the request if I physically click on the send button)

**Comment by abhijitkane** [comment]
@kaosdg Got it. We've fixed this in our internal build, and will be pushing the fix out in the next release.

**Comment by abhijitkane** [comment]
@kaosdg Can you confirm this fixed in 4.2.1?

**Comment by kaosdg** [comment]
@abhijitkane just pulled down 4.2.2, and the issue is corrected
