### ISSUE TITLE
Gui not showing or Postman crash at startup

### ISSUE THREAD

**Issue by Etrunon** [a85/POSTMan-Chrome-Extension#2076]
Please include the following:
Hi, 
I have a problem with which I can't open and use postman. When I click on the Icon or try to launch from terminal, the program seems to open and there is the icon in the launch bar, but I can't see the gui anywhere (alt tabbing show the running program but chosing it has no effect) and it isn't hidden on the screen under something else.
# Postman cannot launch #1299

After reading here I tried to unistall reinstall and launch and nothing happened, even with a reboot in the middle but nothing changed. 
I hope that this is a problem of mine and that I am missing something, if you could please help me =)

Thank you in advance
1. Postman Version: Latest available 
2. App (Chrome app or Mac app): Chrome app
3. OS details: Ubuntu 14.04 64bit
4. Is the Interceptor on and enabled in the app: don't think, Never used it
5. Did you encounter this recently, or has this bug always been there: recently
6. Expected behaviour: I expect Postman to open, but it doesn't and if it do i can't see the gui

**Comment by Etrunon** [comment]
It happened again,

I "solved" installing postman on google-chrome-beta... 

But this afternoon I believe that I accidetally double clicked on the top bar of the app (the one of the os, with the name of the app and the button to close minimize etc)... the app minimized.
I could see the name in the top and the icon in the launcher but yet again all the other UI elements were gone... 
I tried delete the cache, unistall and reinstall the app, chrome itself... I'm quite desperate now... :'(

**Comment by abhijitkane** [comment]
When you open Postman, can you try right-clicking on the icon in the dock/taskbar and see if there's a Maximize option?

@czardoz any thoughts?

**Comment by Etrunon** [comment]
In the Doc, there are only the "Lock to launchbar" and "Quit" option
I could solve again the problem... Unistalling and clearing completely Chrome... But it happened again this morning... It's becoming quite funny xD
In fact this morning when it happened there was a whitepage behind postman... When it disappeared there was a slight shadowing... And it was my little postman!

Maybe it was this all along and I just didn't see it anywhere... Not too funny thought that you can hide completely its window

![screenshot from 2016-06-14 11 11 58](https://cloud.githubusercontent.com/assets/6863419/16037469/ec8d9380-3220-11e6-8683-f3cab56de26c.png)
![screenshot from 2016-06-14 11 11 46](https://cloud.githubusercontent.com/assets/6863419/16037470/ec8e4d2a-3220-11e6-8a37-61e2bc66bf5c.png)

**Comment by shruk** [comment]
this happens to me as well, after I minimize the postman, i can't get gui back! restart the computer, remove from chrome, re add, doesn't work. how can i use the app if I can't get gui showingup?

Postman Version: Latest available
App (Chrome app or Mac app): Chrome app
OS details: windows 7
Is the Interceptor on and enabled in the app: don't think, Never used it
Did you encounter this recently, or has this bug always been there: recently
Expected behaviour: I expect Postman to open, but it doesn't and if it do i can't see the gui

**Comment by a85** [comment]
Issues like these should be solved by Postman native apps available here: www.getpostman.com/apps

**Comment by mbirtwistle** [comment]
On Windows 10, Hold down SHIFT and right click on the postman taskbar icon. A 'Maximise' option then appears which brings back the application.

**Comment by Tiorzfk** [comment]
@mbirtwistle Thankyou so muchhh :D

**Comment by BhavinSan** [comment]
Thanks @mbirtwistle  that does it!

**Comment by pegaltier** [comment]
@mbirtwistle Thanks

**Comment by Asuquo12** [comment]
@mbirtwistle Thanks bro
