### ISSUE TITLE
Hawk authentication fails when using variables

### ISSUE THREAD

**Issue by sqlrob** [a85/POSTMan-Chrome-Extension#2078]
Assuming valid hawk credentials configured in postman,
when going to a hawk authenticated URL that happens to contain a variable (either straight variables such {{baseurl}}, or function like ones such as {{$guid}}), the request returns 401. If the variable/function is expanded by hand into a constant , the request succeeds.

Postman Version: 4.2.1
App (Chrome app or Mac app): Chrome
OS details: Windows 10 x64 10.0.10586, Mac OS X 10.11.4
Is the Interceptor on and enabled in the app: Reproduced both ways
Expected behaviour: Request is authenticated

**Comment by abhijitkane** [comment]
@sqlrob In 4.2.1 - I can see the Auth ID, ext, app, and dlg fields getting replaced. Are you not seeing the same behaviou
![screen shot 2016-05-21 at 15 32 46](https://cloud.githubusercontent.com/assets/681190/15447732/52d62d5c-1f69-11e6-9ce7-b188e08530bc.png)
r?

**Comment by abhijitkane** [comment]
@sqlrob Can you try sending a request as described at http://echo.getpostman.com/#hawk?
![screen shot 2016-05-21 at 16 08 16](https://cloud.githubusercontent.com/assets/681190/15447897/44b21dee-1f6e-11e6-95df-52daeafc80ae.png)

**Comment by sqlrob** [comment]
I wasn't able to reproduce with host variables on your host, but I was able to reproduce with {{$guid}}

![image](https://cloud.githubusercontent.com/assets/926539/15448541/36d656b6-1f2a-11e6-8e4c-d487a7df467f.png)

![image](https://cloud.githubusercontent.com/assets/926539/15448547/7646b1ce-1f2a-11e6-9e82-b51759745cff.png)

**Comment by abhijitkane** [comment]
@czardoz

**Comment by abhijitkane** [comment]
@czardoz

**Comment by sdnts** [comment]
@sqlrob Can you try updating to the latest version (4.7) on the native app and verify if this is fixed?

**Comment by sdnts** [comment]
This should be fixed in v4.7 and up
