### ISSUE TITLE
Oauth 1.0 access token always included in signature even if empty

### ISSUE THREAD

**Issue by ZeWaren** [a85/POSTMan-Chrome-Extension#2079]
1. Postman Version: 4.2.1_0.
2. App (Chrome app or Mac app): Chrome app.
3. OS details: Irrelevant.
4. Is the Interceptor on and enabled in the app: Irrelevant.
5. Did you encounter this recently, or has this bug always been there: Was not present in the legacy app.
6. Expected behaviour: Oauth 1.0 signature is generated correctly.
7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app): Nothing of interest.
8. Screenshots (if applicable)
## Description

If using OAuth 1.0, creating a request with only a consumer token (and no access token) generates an invalid signature.
## What happens

When Postman generates the base string, it always add parameter `oauth_token` even if it's empty.

Example:
Signing the following request with consumer key `5742a6a38f6ec` and consumer secret `5742a6a38fba1`:

```
POST /some/path
Host: whatever.example.com

foo=bar
```

Generates:
`POST&https%3A%2F%2Fwhatever.example.com%2Fsome%2Fpath&foo%3Dbar%26oauth_consumer_key%3D5742a6a38f6ec%26oauth_nonce%3Dr7WcfN%26oauth_signature_method%3DHMAC-SHA1%26oauth_timestamp%3D1463990570%26oauth_token%3D%26oauth_version%3D1.0`
Instead of:
`POST&https%3A%2F%2Fwhatever.example.com%2Fsome%2Fpath&foo%3Dbar%26oauth_consumer_key%3D5742a6a38f6ec%26oauth_nonce%3Dr7WcfN%26oauth_signature_method%3DHMAC-SHA1%26oauth_timestamp%3D1463990570%26oauth_version%3D1.0`

And thus the signature is not correct.
## What should have happened

`oauth_token` should not have been added to the base string.
## Suggestion

Only append `oauth_token` if it's not empty.

In `generateSignature(request, oAuthHelperParams)`:

```
var signatureParams = [{ key: "oauth_consumer_key", value: oAuthHelperParams.consumerKey }, { key: "oauth_signature_method", value: oAuthHelperParams.signatureMethod }, { key: "oauth_timestamp", value: oAuthHelperParams.timestamp }, { key: "oauth_nonce", value: oAuthHelperParams.nonce }, { key: "oauth_version", value: oAuthHelperParams.version }];
if (oAuthHelperParams.token) {
    signatureParams.push({ key: "oauth_token", value: oAuthHelperParams.token });
}
```

**Comment by abhijitkane** [comment]
@ZeWaren Does the 'Add empty params to signature' option help?

**Comment by EpocDotFr** [comment]
I encounter this blocking issue too.

**Comment by ZeWaren** [comment]
@abhijitkane Yes it does.
My bad. That behavior was not the same in the legacy app and I assumed my problem came from there.

**Comment by abhijitkane** [comment]
@ZeWaren Cool..different OAuth1 providers have different server-side implementations - we needed to add a few options to make it work for most services.

**Comment by ZeWaren** [comment]
To add more details: Postman 0.8.4.17 did not consider `oauth_token` when listing the empty parameters, and thus having the checkbox checked did not trigger the behavior I described.
