### ISSUE TITLE
calls leave subfolders and move up one level to collection

### ISSUE THREAD

**Issue by wkuckro** [a85/POSTMan-Chrome-Extension#2080]
Please include the following:

It only started with this collection. It is owned by another user on my team. I've made extensive modifications to it. When i opened it up recently a few things were out of place. I reordered them back. When i had to close and restart my computer recently, ALL the individual calls were outside their subfolders
1. Postman Version: 4.2.1
2. App (Chrome app or Mac app): Chrome 50.0.2661.102
3. OS details: win / x86-32
4. Is the Interceptor on and enabled in the app: YES
5. Did you encounter this recently, or has this bug always been there:Recently
6. Expected behaviour: Collections should maintain order when closing the app and re-opening
7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
8. Screenshots (if applicable)

![image](https://cloud.githubusercontent.com/assets/16108658/15474684/82a18b54-20cb-11e6-9138-d1ae1a2fa781.png)
1. If it’s a Cloud-related issue, or you want to include personal information like your username / collection names, mail us at help@getpostman.com
2. If it’s a question (anything along the lines of “How do I … in Postman”), the answer might lie in our documentation - http://getpostman.com/docs.

**Comment by abhijitkane** [comment]
@wkuckro We made a number of changes to this in the latest version of the app (4.3.2). Can you upgrade to the latest version and see if this happens again?
