### ISSUE TITLE
Apply a transform to URLs when clicking?

### ISSUE THREAD

**Issue by kaosdg** [a85/POSTMan-Chrome-Extension#2083]
This _might_ end up being a feature request, but is there anyway to apply transforms to a URL when clicking on them in Postman?

I do a lot of iOS development, and our feeds return many urls as app-specific URI patterns:
"someapp://{section}/{identifier}"  which would correspond to:
http://api.someapp.com/feeds/version/{section}?id={identifier}&key=apikey

currently I have to do a lot of copy/pasta to work with these.

It'd be nice if I could setup a transform so when I click on the app URI I can get my API url.

**Comment by a85** [comment]
I believe you can use pre-request scripts for use cases like this. Features like this introduce hidden behavior and are not widely applicable. We are working on plug-ins that might make this possible but closing this request in it's current form.
