### ISSUE TITLE
Postman request to EMC ECS

### ISSUE THREAD

**Issue by tee33** [a85/POSTMan-Chrome-Extension#2084]
Please include the following:
1. Postman Version: 4.2.0
2. App (Chrome app or Mac app): Mac app
3. OS details: 10.11.5
4. Is the Interceptor on and enabled in the app: No
5. Did you encounter this recently, or has this bug always been there: Recently, using aws signature to provide id/key to do a GET on EMC ECS.  
6. Expected behaviour:  
   Does PostMan support EMC ECS? 
   <Error>
   <Code>InvalidArgument</Code>
   <Message>Invalid Argument</Message>
   <RequestId>0ae46c17:154adab15c9:305f:0</RequestId>
   </Error>
7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
   Failed to load resource: the server responded with a status of 400 (Bad Request)
8. Screenshots (if applicable)

Some guidelines: 
1. Please file Newman-related issues at https://github.com/postmanlabs/newman/issues
2. If it’s a Cloud-related issue, or you want to include personal information like your username / collection names, mail us at help@getpostman.com
3. If it’s a question (anything along the lines of “How do I … in Postman”), the answer might lie in our documentation - http://getpostman.com/docs.

**Comment by abhijitkane** [comment]
@tee33 The EMC ECS API needs its own auth header (http://www.emc.com/techpubs/ecs/ecs_api_object_control_service-1.htm#GUID-3E2A3F7A-53F1-488E-BED9-2642DEE6E20C). AWS's signature algorithm will not be accepted by ECS.
