### ISSUE TITLE
Make it easier to build JSON

### ISSUE THREAD

**Issue by rajeshrite** [a85/POSTMan-Chrome-Extension#2085]
Something like what this site does

http://www.objgen.com/json

**Comment by jimonthebarn** [comment]
I think that Json is simple enough by itself. I really dont see any value to create yet another form of abstraction. Besides if i look at the "demo" showcased at the referred link the json is already easier to read and comprehend than the "model definition". There are certainly more interesting features to implement.

Just my 5 cents though. :)

**Comment by rajeshrite** [comment]
Thanks jimonthebarn for considering my request.

PS: Postman's a great product....looking forward for it getting even more easier-to-use and useful :)
