### ISSUE TITLE
Show body first for PUT/POST requests - rather than authorization

### ISSUE THREAD

**Issue by rajeshrite** [a85/POSTMan-Chrome-Extension#2086]
For PUT and POST requests... one has to go click Body everytime to see the body...but that's the primary part of the request in most cases....

Or perhaps some kind of default setting can be provided

**Comment by chimit** [comment]
Absolutely agree! Here was my similar request:
#1501

**Comment by a85** [comment]
@aditikul We should seriously consider this. Making Body the default tab in the Mac app is possible because we can now send bodies for the GET method using the new runner.

**Comment by wikski** [comment]
+1

**Comment by troigdome** [comment]
+1

**Comment by bdone** [comment]
plus one

**Comment by tomcooke** [comment]
+1 yes please

**Comment by chimit** [comment]
Any updates on this?

**Comment by alahosky** [comment]
Defo +1, as per my comment in other issue:
https://github.com/postmanlabs/postman-app-support/issues/3389#issuecomment-336061305

**Comment by steveostlind** [comment]
+1

**Comment by believersconnect** [comment]
+1

**Comment by intraz** [comment]
+1

**Comment by embee8** [comment]
+1

Switching from the Authorization to the Body tab is super cumbersome. I can imagine that user research would reveal that the majority of users focus on the Body tab, hence, assigning the default tab might be the easiest solution. Best would be a setting to let users select the preferred tab.

**Comment by prurph** [comment]
+1

**Comment by ghost** [comment]
+1

**Comment by leandro-fernandez** [comment]
+2

**Comment by zcuric** [comment]
+1

**Comment by Guik** [comment]
+1

**Comment by TheSench** [comment]
+1

**Comment by chimit** [comment]
Have been waiting for more than 2 years already...

**Comment by mroche89** [comment]
+1

**Comment by prgx-erodri02** [comment]
+1
Definitely vote for this one. When developing APIs, the Body tab is by far the most useful one to have open

**Comment by Thota-Chaitanya** [comment]
+1

**Comment by abhijitparida** [comment]
+1 please implement

**Comment by briancmoore** [comment]
+10 I have 493 requests I need to change and I'm going crazy having to click over to body every time.

**Comment by MatiasBarboza** [comment]
+1, I'm pretty new to this but I'm definitely willing to move forward :). This feature would be really helpful for my daily job troubleshooting Web Services for consumers of the services offered by my employer. 

Cheers!

**Comment by wspencer** [comment]
+1.  Incredibly annoying.  Ever tried using your own product in a production environment?

**Comment by custompro12** [comment]
+1

**Comment by zbaysf** [comment]
+1

**Comment by dylanh724** [comment]
How's the progress **[since submitted 2 years ago]**?

**Comment by AlexPreved** [comment]
+1

**Comment by AntoniusGolly** [comment]
+1

**Comment by wspencer** [comment]
2 years, 2 months.  Any progress on this TRIVIAL change?

I'll bet someone is busy building a 'better Postman' right now, since these guys can't seem to get anything done.

**Comment by chimit** [comment]
@shamasis, @numaanashraf, @abhijitkane, @a85

**Comment by shamasis** [comment]
Yes. Truly it’s been a long time. 😊 But here’s the dilemma: we didn’t change the default behaviour since some prefer the other way too. We did think of introducing another settings for this, but refrained from making everything a settings nightmare. 

The thing that would work is the simple ability to drag and drop to reorder these tabs and match one’s workflow. This satisfies all use cases without having to add settings, but is a tad difficult to build based on the way things are wired up now. 

I’m not not sure when exactly we are picking this up but if you’ve noticed, we have recently started to prioritise all long-standing issues and I’m sure this will get picked up sooner than later.

**Comment by chimit** [comment]
@shamasis, maybe a simple "remember the last tab" is an option?

P.S. But I'm still pretty sure most of the people need a body tab much more often. It's absolutely no problem to switch to any other tab when you need.

**Comment by semiherdogan** [comment]
+1

**Comment by ed-rod** [comment]
@shamasis 
I agree with @chimit . Having custom ordering on tabs is not necessary to have this feature. All you need is an internal value for the last used tab that is updated every time the user changes the tab. All newly opened requests then show the last used tab by default. This wouldn't require any settings in configuration pages.

**Comment by marklofdahl** [comment]
+1

**Comment by Sofianio** [comment]
Now the default is "params" ...
When I see the dates on some issues I feel like they don't even listen to our feedbacks :/

**Comment by davingreen** [comment]
+1 Body as default or config to set as default

**Comment by austin-plixer** [comment]
I keep updating hoping to see this feature added..

**Comment by kostelnyy** [comment]
That config would be really helpful

**Comment by gaikaz** [comment]
+1 Remembering last used tab of the Request should be easy to implement and would definitely satisfy everyone here at least for the time being. So many people here requesting this, and this must be just a small part of users, who have github and bother leave a comment.

Please just give this issue/feature some little time. Thanks.

**Comment by linnsha** [comment]
+1

**Comment by dihmeetree** [comment]
+1

**Comment by zmts** [comment]
+1

**Comment by yehtutlwin** [comment]
+1

**Comment by Essler** [comment]
@shamasis, back on February 13 you mentioned "this will get picked up sooner than later" and I see a label was added on July 8. What's the status of this issue today, and where can we go to more closely follow its progress?

**Comment by sea-cat** [comment]
+1

**Comment by bensullivan** [comment]
+1

**Comment by slw07g** [comment]
Please make this feature request a priority. 

_Other than this inconvenience, I find the PostMan app to be quite nice._

**Comment by slw07g** [comment]
This may help ease the pain for some:

I did find that if make a PostMan account, and save my requests to the same workspace, I can view the body of all the requests in a scrollable view on the website https://web.postman.co

![image](https://user-images.githubusercontent.com/8406059/65379782-119cac00-dc9c-11e9-8212-dca26542d1dc.png)

**Comment by BriceJamin** [comment]
+1

**Comment by BriceJamin** [comment]
I want to look at a X POST request. I click on it. I'm in Params UI so I click on Body.
I want to compare with another Y POST request. I click on it. I'm in Params UI so I Click on Body. Ok i get it.
I want to come back to X. I click on it. I'm in Params UI... 

RHAAAAAAAAAAA.

**Comment by rudisills** [comment]
+1

**Comment by EmreSURK** [comment]
+1
That behavior really bothers. It makes really hard to navigate between requests. 
I m sure if the developers of Postman can realize how much problems that behavior causes it but I m about to left Postman. It is annoying.

**Comment by bensullivan** [comment]
+1

**Comment by LaurieBrownBulkhead** [comment]
+1
I can't believe this has been left for so long without any resolution. It makes using postman so frustrating and comparing the bodies of multiple requests tedious. The Params tab is almost useless to me so defaulting to it is very annoying.

**Comment by wspencer** [comment]
I suspect the postman development team has become so 'agile' they can't get anything simple done anymore.  This is a glaring usability issue.

**Comment by geez0r** [comment]
sigh... +1

**Comment by rudisills** [comment]
I just saw this (Issue 2086 belongs to this project).
@codenirvana closed the project on Jun 27, 2019. 
https://github.com/postmanlabs/postman-app-support/projects/24

@vkaegis @codenirvana Any word on whether 2086 can get added back to an active project to have a possible resolution in the future?

**Comment by cyrielle-hada** [comment]
**Two possible options for this issue.**

1. Add an option in the app settings.
2. Make Postman detect the request automatically: when Postman is opening a POST request - it should find the first tab where the parameters are defined by the user.

_Feedback reported via Product Support_

**Comment by akamarvin** [comment]
+1k , when re-opening Postman from a previous session, each time I return to one of my current key tabs, I have to re-set it to body instead of params. 
Who uses the params tab with POST anyway ? ... Nobody. 
Even when you need file upload capabilities , you use body > form-data.  
So I really don't get why the params would be the default for every request.  
Please give us the choice in settings or remember the choice on a per request basis.

**Comment by DedMorozzz** [comment]
+1. Variable only "Body". How to choose "body" as default tab?

**Comment by zmts** [comment]
+1

**Comment by wilzokch** [comment]
while this feature is not ready, we can use the following hack to achieve it
1. View > Developer > Show DevTools (Current View) / **CTRL + SHIFT + i** for window user
2. Click on "Console" Tab
3. paste following code

> setInterval(function() {document.querySelectorAll('.collection-virtualized-list-item__request').forEach(function(e){e.onclick= function() {setTimeout(function(){document.querySelector('.tab--body').click();}, 1500);};})}, 500);

**Comment by chimit** [comment]
Almost 5 years since the first time this issue was reported. Still no any progress in such a simple thing. @vkaegis please, pay attention on this.

**Comment by rudisills** [comment]
@wilzokch Thanks for sharing your workaround. Is there any way to make this code run at application start so it works each time I run the app?

**Comment by wilzokch** [comment]
@rudisills I think it is not possible to run this code automatically... 

you only need to copy this code once, 

when you re-open postman, go to console tab, you can use arrow key **Up** to get this script back

if you do not want to repeat this step, I will suggest you keep your postman open, and hibernate your PC

**Comment by ufosaga** [comment]
I suppose Postman should add a config for this since this is quite useful.

**Comment by Sofianio** [comment]
@ufosaga you're Wong ... 😂  😂

**Comment by arlemi** [comment]
When comparing two **opened** requests, switching between tabs shouldn't be reverting to the Params tab. 

![keepbody](https://user-images.githubusercontent.com/5029719/84374371-ce8dba80-abd5-11ea-8ce6-91b1030a99c9.gif)

**Comment by steven-pribilinskiy** [comment]
+1

**Comment by securitygoodie** [comment]
> while this feature is not ready, we can use the following hack to achieve it
> 
> 1. View > Developer > Show DevTools (Current View) / **CTRL + SHIFT + i** for window user
> 2. Click on "Console" Tab
> 3. paste following code
> 
> > setInterval(function() {document.querySelectorAll('.collection-virtualized-list-item__request').forEach(function(e){e.onclick= function() {setTimeout(function(){document.querySelector('.tab--body').click();}, 1500);};})}, 500);


thanks a lot!
This is much useful.
I wonder why this is not available as a feature in postman. They could add this in settings.

**Comment by igauravsehrawat** [comment]
Still not giving up the hope. It will be very a productive feature.

Probably just pinning a tab feature or something similar.

**Comment by Scrandre** [comment]
+1
Or just an option of not switching the tab when switching between collections would be useful too, so you would always stay in the tab you're analyzing right now

**Comment by kolengri** [comment]
+1

**Comment by Niush** [comment]
Postman shows Green Dot if there is content in Params or Body.

![image](https://user-images.githubusercontent.com/16359077/95419741-ef82d400-0959-11eb-877a-e7b0f9dc44b2.png)

So, there could be a feature such that, if there is Green Dot (has content) in Params keep it opened. If there is only Green Dot (content) in Body then open the Body tab by default. This could be very productive feature. Still waiting for it.

**Comment by cayzars** [comment]
It seems to work when there's nothing in the Tests tab.

> while this feature is not ready, we can use the following hack to achieve it
> 
> 1. View > Developer > Show DevTools (Current View) / **CTRL + SHIFT + i** for window user
> 2. Click on "Console" Tab
> 3. paste following code
> 
> > setInterval(function() {document.querySelectorAll('.collection-virtualized-list-item__request').forEach(function(e){e.onclick= function() {setTimeout(function(){document.querySelector('.tab--body').click();}, 1500);};})}, 500);


=> Works if there's nothing in the tests tab.

**Comment by juliocabify100** [comment]
5 years later...

**Comment by Essler** [comment]
> 
> 
> 5 years later...

I've since moved on to [Insomnia](https://insomnia.rest/) (no affiliation).

Something small like this not being addressed after all this time, especially with the reasonings the developers have given, doesn't bode well for the project.

**Comment by ouribeb930** [comment]
Is this going to be done in some point before I die?
I really good solution would be just to be able to move the body tab first.
Another solution would be to add a setting to define the selected tab ( I mean any tab we want ).
One more would be just to be able to make tabs float and dockable in some place we want.

This really makes me angry, not like upset, but really angry... hate.

Is there anyone out there with different opinion?

Have you ever thought that some times we just want to compare two f*** bodies?

Really, please fix it!!!

**Comment by Hao-Wu** [comment]
It is 12/20/2020
Waiting...

**Comment by healarconr** [comment]
This feature would be helpful.

Add a thumbs up to [the first comment of the issue](https://github.com/postmanlabs/postman-app-support/issues/2086#issue-156938781) and a comment to show that you would like to have this feature too. Hopefully it would help to rank this issue higher.

**Comment by slw07g** [comment]
I wonder if this is the better place to report feature requests:

https://support.postman.com/hc/en-us/requests/new/

**Comment by tparikka** [comment]
Also hoping for this feature.

**Comment by thilllon** [comment]
+1

**Comment by KiraElric007** [comment]
Hola!! 👋 
We have added this feature in the latest release of Postman 😃 ! Now you can pick up from where you left. The tab you were working on before closing the request will be focused the next time you reopen the request.
Upgrade to the [Postman v8.2](https://www.postman.com/downloads/).

**Comment by akamarvin** [comment]
> 
> 
> Hola!! 👋
> We have added this feature in the latest release of Postman 😃 ! Now you can pick up from where you left. The tab you were working on before closing the request will be focused the next time you reopen the request.
> Upgrade to the [Postman v8.2](https://www.postman.com/downloads/).

Months and years of this being open and what's proposed is actually not really the appropriate answer. 
your thing kind of work, but not on already opened collections after an upgrade. 
So, in order to for it to work, I need to save , remove  and re-import my collections ... 

and then, on each and every request that I will open for the first time in a collection, i still have to "imprint" my preference, hence the Body tab. .... For each and every request ... this is so sad ... did'nt you understand that was the main point ? the default behaviour ?

... it would have been MUCH MORE SIMPLE, 
- to detect that the actual body of a request is raw json and so to open that instead of that dreaded, always empty, "Params" tab.
- or to allow via a GLOBAL OPTION to select Body > Raw as the preferred way to open ANY new POST request.
And finally relegating the "Params" tab where it belong : the dark corner at the back of the classroom.

I'm a bit fed up, and that emphatic "you're not signed in, you'll stay in scratch pad" in a yellow/orange banner at startup, is kind of the last drop. We will be starting to review alternatives . The pushy "be online" attitude is ... too much.

**Comment by arlemi** [comment]
@akamarvin There are a few things in your post:

> So, in order to for it to work, I need to save , remove and re-import my collections ...

You don't need to save, remove, or re-import. Clicking any tab will save it as the "last opened" one and the next time you open the request it will default to it. 

![lastopenrequest](https://user-images.githubusercontent.com/5029719/114368225-1aeab380-9b75-11eb-90cb-080c6450225f.gif)

> and then, on each and every request that I will open for the first time in a collection, i still have to "imprint" my preference, hence the Body tab. .... For each and every request ... this is so sad ... did'nt you understand that was the main point ? the default behaviour ?

Having a default behaviour is the reason why this issue existed in the first place. When the app started there wasn't many options and the default behaviour was the Authorization tab, then the Params tab. If we default it to "Body" then what about:
- POST requests with query params?
- POST requests with pre-request/test scripts?
- POST requests with Auth? 

For each of these you'd be defaulted to the Body tab and then would have to switch. With the solution we've implemented you'll be prompted with the last thing you were working on, regardless of the request type.

> ... it would have been MUCH MORE SIMPLE,
> - to detect that the actual body of a request is raw json and so to open that instead of that dreaded, always empty, "Params" tab.
> - or to allow via a GLOBAL OPTION to select Body > Raw as the preferred way to open ANY new POST request.
And finally relegating the "Params" tab where it belong : the dark corner at the back of the classroom.

Because you're not using the Params tab doesn't mean no one else is, when implementing feature requests we try to take everyone's use-case into account. While this might be an inconvenience at the start, tell yourself that from now, every time you switch to the "body" tab for one of your request you won't have to do it again for that same request! 

Hope this helps understanding where we're coming from. 🙂 Closing the issue since this has been implemented.

**Comment by bombillazo** [comment]
This is still the best solution 😞 

>  - or to allow via a GLOBAL OPTION to select Body > Raw (or any other) as the preferred way to open a POST request (or at least any request).

It is super annoying and time-consuming editing a bunch of requests and having to move through tabs.

**Comment by ouribeb930** [comment]
+1

**Comment by Levon770** [comment]
+1

**Comment by tbettermann** [comment]
+1

**Comment by rohit-wowmedia** [comment]
+1

**Comment by arlemi** [comment]
This issue has already been closed: https://github.com/postmanlabs/postman-app-support/issues/2086#issuecomment-817630488

**Comment by Proximat** [comment]
Issue has been closed but it still hasn't been resolved?

**Comment by tbettermann** [comment]
> For each of these you'd be defaulted to the Body tab and then would have to switch. With the solution we've implemented you'll be prompted with the last thing you were working on, regardless of the request type.

This solution is not functioning properly for the 'Examples' section of a request. It would be beneficial if this solution were consistent across the entire application.

**Comment by Om-i** [comment]
[#2086 (comment)](https://github.com/postmanlabs/postman-app-support/issues/2086#issuecomment-817630488) This seems to work with regular requests, but request examples don't seem to retain the last tab selected, defaulting to the Params tab.
