### ISSUE TITLE
Can't install Postman offline from .crx file

### ISSUE THREAD

**Issue by liemqv** [a85/POSTMan-Chrome-Extension#2087]
Postman is the best REST tool, but I'm having a problem follows:
I can't install postman offline from .crx file, error message: **"Apps, extensions, and user scripts cannot be added from this website."**
1. App (Chrome app or Mac app):Chrome app
2. OS details: Windows 7

![Error](https://lh3.googleusercontent.com/YfE4VPyt_4B_oDYFhWNOzgkbxMhEFsSzqxFZhJdGQgxmei6J7e7SCbg6LDndJ1i9oyTn=s170)

**Comment by numaanashraf** [comment]
@liemqv Could you let us know where you downloaded the `.crx` from and also your Chrome version?

**Comment by liemqv** [comment]
Hi @numaanashraf ,
- I download .crx from Chrome Store: https://chrome.google.com/webstore/detail/postman/fhbjgbiflinjbdggehcddcbncdddomop, use "Get CRX" extension.
- Chrome version: 51.0.2704.79 m

Thanks!

**Comment by abhijitkane** [comment]
@liemqv Can you attach a screenshot of the link for the .crx file?
