### ISSUE TITLE
OAuth 2 token request fail

### ISSUE THREAD

**Issue by RaneofSoTN** [a85/POSTMan-Chrome-Extension#2088]
Currently my requests to use the oauth2 helper within the postman app have been broken. They were not always this way. It seems to be due to a recent upgrade of the app.

When we perform the oauth2 flow, everything works up until retrieval of the token from out endpoint. At this point, postman is listed as sending in both the basic auth header and the details in the body. Which is currently forbidden by our implementation, keeping up with the specifications. This is causing us to:
1. Not get the successful token
2. Not get an error saying that oauth2 failed because of a 401 for the above error.

Can we get something to determine where the token requests should go?
# 

Please include the following:
1. Postman Version: 4.2.1
2. App (Chrome app or Mac app): Chrome App
3. OS details: Windows 7
4. Is the Interceptor on and enabled in the app: no
5. Did you encounter this recently, or has this bug always been there: Recently <2weeks
6. Expected behaviour: Able to finish oauth2 flow
7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
8. Screenshots (if applicable)

![fiddlerpostmanissue](https://cloud.githubusercontent.com/assets/5208840/15579200/9fd14666-2331-11e6-90d8-1e82649a7c1e.png)

**Comment by neverendingqs** [comment]
@RaneofSoTN @a85 - probably should merge this with https://github.com/postmanlabs/postman-app-support/issues/1360

**Comment by harryi3t** [comment]
We are going to support an option in the App from where user can choose which authentication method should be used.

In the mean time as a workaround, you can un-check the `Request access token locally` check box

<img src= 'https://user-images.githubusercontent.com/5207331/29372418-aa89146a-82c8-11e7-9965-75dbdda990c0.png' height=500px/>

When it's checked the App makes the second request using both authentication methods
When it's unchecked our server is used which only sends the credentials in the body (as of this writing)

let me know if this solves your issue.

**Comment by miezel** [comment]
Workaround didn't do it for us. If we don't check this we get message 'Could+not+make+access+token+request'

We are using OpenAM which is very strict so access token request with client id/client secret in both auth header and request body is rejected. 

We are more than happy to use the newest version but this is blocking for us.

Hoping for a quick fix on this.

Regards,
Michel

**Comment by mehle** [comment]
Postman seems to be in violation of RFC 6749 with this, which states that multiple authentication methods must not be used.  Also, using credentials in the POST body should only be used if the client is incapable of using Basic Authentication.  Perhaps it can be exposed as an option, but right now, it's unusable for us.

**Comment by harryi3t** [comment]
@mehle this issue has been fixed. 
Now we have a dropdown menu to select where the credentials should be added.
Please update to latest postman native app.
Let me know if it’s not working for you.

**Comment by mehle** [comment]
Thanks!  I just realized that this was resolved on the native app, but it probably won't make it to the Chrome version.  Time to switch.
