### ISSUE TITLE
Save authorization type

### ISSUE THREAD

**Issue by jhalterman** [a85/POSTMan-Chrome-Extension#2090]
Somewhat related to and #1463 - it would be great if postman **did** save the authentication type. As mentioned in #1463, the headers don't necessarily need to be saved, but the type at least should. This works well when the auth values are parameters that are substituted for an environment.

**Comment by abhijitkane** [comment]
@jhalterman There's a 'Save helper data to request' option. If this is checked, clicking 'Save' will save the helper data (tokens/secrets etc). with the request in the collection.

Feel free to re-open if it doesn't work.
