### ISSUE TITLE
IndexedDB is growing uncontrolled >20GB

### ISSUE THREAD

**Issue by MattiasMM** [a85/POSTMan-Chrome-Extension#2091]
4.2.1
win / x86-32
Chrome 50.0.2661.102
Interceptor ON

I send POST request with attachments in the form-data.
As a consequence the IndexedDB grows and grows with every message I send from Postman.

The folder:
...\AppData\Local\Google\Chrome\User Data\Default\Storage\ext\fhbjgbiflinjbdggehcddcbncdddomop\def\IndexedDB\chrome-extension_fhbjgbiflinjbdggehcddcbncdddomop_0.indexeddb.blob\ currently holds over 20GB of memory.

How can I clear the IndexedDB storage?
How can I prevent it from storing sent attachments to file system?

Thanks,
![postmancapture1](https://cloud.githubusercontent.com/assets/19603819/15599545/996e9880-23ec-11e6-92d9-037d38fa3f99.JPG)

**Comment by abhijitkane** [comment]
@MattiasMM The next version of the app will not store sent files in the history requests. For now, you can clear your history - click the trashcan icon (screenshot), and select 'Clear all'.
<img width="299" alt="screen shot 2016-05-29 at 21 43 17" src="https://cloud.githubusercontent.com/assets/681190/15634640/6990dc3a-25e6-11e6-8eb1-2d43e04867cc.png">
