### ISSUE TITLE
Collection is missing

### ISSUE THREAD

**Issue by shafrir** [a85/POSTMan-Chrome-Extension#2093]
Please include the following:
1. Postman Version:
   4.2.2
   win / x86-32
   Chrome 50.0.2661.102
2. Chrome app
3. Windows 10
4. disable
5. New bug
6. collection is missing
7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):

i have a VERY important collection this morning and now i see it`s missing "Phoenix"
please help to restore it

**Comment by sobtiankit** [comment]
@shafrir Can you email help@getpostman.com with your account details?

**Comment by abhijitkane** [comment]
--Follow up via email--
