### ISSUE TITLE
4.2.1 - Send and Download creates empty/invalid files

### ISSUE THREAD

**Issue by cristianmuntianu** [a85/POSTMan-Chrome-Extension#2095]
Hello,

I have opened a new issue as a continuation of the closed issue #1905 .
We are still experiencing this problem on postman 4.2.1, and possibly even v4.2.2.
Would you kindly review this issue and check if it's actually fixed?

The bug/error occurs when downloading archived database dump files from S3 using Api calls.

I ruled out the error from our api call since i've tried countless times to reproduce the bug using cURL calls and worked perfectly.
The file is around 200 MB in size.

Have not tested/seen scenarios where a file having 1GB or more to have this issue.

The impact is quite major, since this bug affects some of our clients who cannot get their own database using Postman and we need to ask them to use cURL calls, even though those are not easy to use, especially on a Windows Operating System.

Moreover following your bug description pattern, here are all the details:
1. Postman Version: V4.2.1
2. App (Chrome app or Mac app): Mac App and Chrome App
3. OS details: Mac Os El Capitan and Windows operating system
4. Is the Interceptor on and enabled in the app: It is always On
5. Did you encounter this recently, or has this bug always been there: Seems like the bug has not been fixed.
6. Expected behaviour: File should download normally.
7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app): Did not take any.
8. Screenshots (if applicable): Did not take any, if necessary will add 

Regards,
Cristian Muntianu
Technical Support Engineer 
[Mambu Tech](http://www.mambu.com/)

**Comment by abhijitkane** [comment]
@cristianmuntianu Do smaller files like https://www.google.co.in/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png work for you?

**Comment by cristianmuntianu** [comment]
Hello @abhijitkane ,
Yes the smaller files work. I'm refering to .zip files not images.

Regards,
Chris

**Comment by a85** [comment]
@numaanashraf Was this issue fixed?
