### ISSUE TITLE
changing shortcuts

### ISSUE THREAD

**Issue by toddmcbrearty** [a85/POSTMan-Chrome-Extension#2096]
is it possible to change the shortcuts?
I would so love command+r to execute the queries. 

Please include the following:
1. Postman Version: 4.2.2
2. App (Chrome app or Mac app): mAC
3. OS details: 10.11.5
4. Is the Interceptor on and enabled in the app:
5. Did you encounter this recently, or has this bug always been there:
6. Expected behaviour:
7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
8. Screenshots (if applicable)

**Comment by abhijitkane** [comment]
@toddmcbrearty We're working on ways to make the shortcuts customizable, but we can't offer an ETA yet.

**Comment by xmollv** [comment]
> I would so love command+r to execute the queries.

I completely agree. On **macOS**, CMD+R should be the default shortcut to send requests instead of CMD+Enter.

**Comment by dagrooms52** [comment]
Would be great to turn off `ctrl + s` for quick save. We share postman collections with 30+ developers and some of them play fast and loose with saving routes - breaking the rest of us. I bet it's a force of habit for most to `ctrl + s` after editing something, so turning it off would help us out a bunch.

**Comment by plam4u** [comment]
+1 for shortcut customizations

**Comment by kilisinovic** [comment]
Is there any progress on this? I have problem where ctrl+alt+v is key combination for "@" on my keyboard and it bothers me that it changes from dual to single panel every time i try to enter email address.

**Comment by leozilla** [comment]
+1 for changing shortcuts (no need for custom ones for me at least)

**Comment by makuc** [comment]
Same as @Ludakic300 , I too have a problem with **ctrl+alt+v** (or actually **alt gr** / **right alt** equaling both, **ctrl + alt** ) being my key combination for "@" and it automatically screwing my workspace... A fix would be awesome!

*Just turning it off would be awesome, since I don't really need a shortcut for changing my work-space!*

**Comment by michaldemjancuk** [comment]
Is this issue noticed ? I have trouble with this and this ticket is opened approx. 2 yrs...

**Comment by makuc** [comment]
Still nothing.... I guess developers don't really like hearing others about their feedback and just blatantly disregard it... Disappointing indeed...

**Comment by S0und** [comment]
I call this the English syndrome. Shipping an app in EU, but you have no chance to change the app's clock from AM/PM to 24hour format. 

Same thing with ASCII. You have some fucked up characters like éáúpüóóüö, just die, we don't support UTF8.

You have to use Ctrl+Alt+V for '@' or AltGr + C for '&' ? OHh you are still alive? Just dieee, or use English keyboard layout.

**Comment by philosowaffle** [comment]
Bump.

**Comment by Grzegorzsa** [comment]
Some shootcuts conflicts with typing language specific characters so it is hard to use this app with non-English text. Right Alt + aszxcnloe should in Polish produce ąśżźćńłóę istead I have some windows opening. These shortcuts cannot be changed from menu.

**Comment by ricardoaugusto** [comment]
👍  All I want is the ability to change CMD R to _Rename_ and CMD E to _Edit_ a request...or at least insert a Menu Item, so the Shortcuts on  > System Preferences > Keyboard could map it.

**Comment by faludigabor** [comment]
Up  - for Hungarian layout too  its a pain ...

**Comment by emanuelhonorio** [comment]
my "?" is **alt gr + w** and it closes the tab in postman, so every time i try to pass a parameter in a url it closes...

**Comment by bmoyer240** [comment]
👍 +1 even a simple implementation [at first] would be awesome e.g. modifying a json file.

**Comment by makuc** [comment]
At let us be able to ***disable*** shortcuts all-together if you can't make it possible to disable only *certain* shortcuts we don't really need (like changing my workspace for no apparent reason... When I try to enter @ character).

**Comment by DedMorozzz** [comment]
+1 for customize hotkeys, or just remove hotkey from "quit"...

**Comment by greg-petersen** [comment]
+1 for this feature, would greatly speed up development workflow if we could bind our own shortcuts!

**Comment by LimmaPaulus** [comment]
I would also want to at least disable shortcuts. Currently I cannot type comma with my custom keyboard layout, which is quite painful when typing JSON.

**Comment by a85** [comment]
Shortcuts can be disabled now in Postman 7.0+. Custom bindings will be available in future versions.

**Comment by ddemydenko** [comment]
+1 customization hotkeys

**Comment by Arkemlar** [comment]
2 years for editable shortcuts feature? I think it not that hard to implement for commercial app...  :anger:   :disappointed:

**Comment by argethlam** [comment]
Hi guys,

I had same problem with sending requests and **cmd + enter**, it's not natural for me... So, after I spend some time searching for solution without any success, I decide to made changes by myself. 
So, I did it :).

Here is solution:
- from _Application_ right click on _Postman_, and click on **Show Package Contents**. 
- navigate to **Contents->Resources->app->js** directory and find file with name "**vendor-ui.js**". You will need to make a copy of this file somewhere on your HDD because you will not be able to change file on this location....
- after you made copy, open that file with some text editor (e.g. Sublime Text or some other), and search to find "**DEFAULT_SHORTCUT_CONSTANTS**". This is a list with defined shortcuts, so find one with name "**sendCurrentRequest**" inside it... Now, all you need to do is to change "**mod+enter**" => "**mod+R**" (shortcut), "**Ctrl+Enter**" => "**Ctrl+R**" (keyLabel) and also keyLabelDarwin switching enter sign with **R**.

After you saved those changes, just override original file with one containing our changes (or even better, change name of original file and keep it, maybe you will need him one day :)), restart Postman and enjoy :).

This is just workaround until Postman developers offer us possibility to setup our own shortcuts.

This works for me, now I'm happy :), I hope that will work for you also.

Regards

**Comment by Vladinho10** [comment]
{
  name: 'sendCurrentRequest',
  label: 'Send Request',
  shortcut: 'mod+r',
  keyLabel: 'Ctrl+R',
  keyLabelDarwin: 'R' },

**Comment by Vladinho10** [comment]
1. cd /Postman/app/resources/app/js
2. vim vendor-ui.js
search in your editor sendCurrentRequest. You will find this object
{
  name: 'sendCurrentRequest',
  label: 'Send Request',
  shortcut: 'mod+enter',
  keyLabel: 'Ctrl+Enter',
  keyLabelDarwin: '⌘↵' },
3. change it with this
{
  name: 'sendCurrentRequest',
  label: 'Send Request',
  shortcut: 'mod+r',
  keyLabel: 'Ctrl+R',
  keyLabelDarwin: 'R' },
4. save it and restart postman.

**Comment by makuc** [comment]
How could one do this on Windows?
1. I navigated to: `%localappdata%\Postman\app-7.0.7\resources` (the latest version installed)
2. I used: `npx asar extract app.asar app` to extract the archive.
3. Opened: `app\js\vendor-ui.js` and edited it (replacing the shortcut: `Ctrl+Alt+v` with `Ctrl+Alt+p`...for all instances as in the above example)
4. Re-packed it: npx asar pack app app.asar
5. Launch Postman anew.

Entry in the `Settings` updated, but the shortcut itself stayed the same. E.g., `Ctrl+Alt+v` still toggles the layout. What am I doing wrong? Should I also edit `electron.asar` and if so, which files inside it? Or am I missing something else entirely?

PS: My edited entry:
```
{
          name: 'toggleLayout',
          label: 'Toggle Two-Pane View',
          shortcut: 'mod+alt+p',
          keyLabel: 'Ctrl+Alt+p',
          keyLabelDarwin: '⌥⌘P',
          menuShortcut: true
}
```

**Comment by Vladinho10** [comment]
be attentive in register, 
{
          name: 'toggleLayout',
          label: 'Toggle Two-Pane View',
          shortcut: 'mod+alt+p',
          keyLabel: 'Ctrl+Alt+P' // this must upper case,
          keyLabelDarwin: '⌥⌘P',
          menuShortcut: true
}
P.S. I think keyLabelDarwin must be just 'P' not  '⌥⌘P', you can try both

**Comment by makuc** [comment]
@Vladinho10 Still doesn't work. Fixed the upper case, as well as tried both versions for `keyLabelDarwin`.

In Settings it is properly displayed as `Ctrl + Alt + P`, yet when I press this combination nothing happens. Pressing `Ctrl + Alt + V` toggles it just the same as it used to. (I'd be satisfied if I could remove only this shortcut, because this is combination for writing `@` on my keyboard, hence why I'm trying to reassign it to something else)

I also re-checked  that this combination isn't in use by something else. It isn't...

**Comment by Vladinho10** [comment]
remove menuShortcut: true in that object

**Comment by makuc** [comment]
Still the same... Nothing changes.

**Comment by RaedShari** [comment]
Kindly, Is there any update on this feature?

**Comment by boneferz** [comment]
АУ!!!! ребятки, сделайте изменение гор клавиш!

**Comment by keltik85** [comment]
Hi just landed here. Nice Feature indeed!

Any statement why the implementation is so difficult?

**Comment by nickfoster** [comment]
I was search for how to change the shortcuts in Postman so I can match the tab controls I'm used to in Visual Studio.  Pretty disappointed it can't be done :(

**Comment by gustave001** [comment]
+1 for this feature

**Comment by JonLaliberte** [comment]
Yeah, and using cmd - . for anything other than cancel is annoying.

**Comment by seth-rah** [comment]
4 years later and still open, oh boy.

Doesn't help that some of the shortcuts are none-standard and now I need to adapt to new shortcuts.

**Comment by blackerhand** [comment]
> 👍 我想要的只是将CMD R更改为_重命名_，将CMD E 更改为_编辑_请求的功能……或者至少插入菜单项，因此>“系统偏好设置”>“键盘”上的“快捷方式”可以将其映射。

me too

**Comment by classicalguss** [comment]
Wow postman. You have one of the best technological apps, and yet it can't do the thing that almost every other App does? I hope it can be done too.

**Comment by NichoFerdians** [comment]
any update?

**Comment by ghost** [comment]
(Take this comment with every single grain of salt.)
Postman is one of the most impressive and useful apps I have ever seen, especially in the web space, and yet it doesn't have editable keybindings? Honestly this issue doesn't make it any less fantastic, but it does make me think there's some serious laziness going on here. It's far from the most important feature but people, it's been YEARS -- it can't possibly be that hard to add that it's a non-starter... :frowning_face: 
Much love, Postman, but come on.

**Comment by eriegz** [comment]
Hey Postman, if you could squeeze this feature into an upcoming sprint that would be 💯. 😉

**Comment by keltik85** [comment]
Corona crisis 2020 and still no movement on this issue.

**Comment by Paras-code-007** [comment]
> * cd /Postman/app/resources/app/js
> * vim vendor-ui.js
>   search in your editor sendCurrentRequest. You will find this object
>   {
>   name: 'sendCurrentRequest',
>   label: 'Send Request',
>   shortcut: 'mod+enter',
>   keyLabel: 'Ctrl+Enter',
>   keyLabelDarwin: '⌘↵' },
> * change it with this
>   {
>   name: 'sendCurrentRequest',
>   label: 'Send Request',
>   shortcut: 'mod+r',
>   keyLabel: 'Ctrl+R',
>   keyLabelDarwin: 'R' },
> * save it and restart postman.

that does not work 
cause every time you will run postman it generate these file
I thought of this because the changed file I put there and backedup file I put there were deleted and original file was regenerated

**Comment by awachat** [comment]
Hey Team,

Our team uses PyCharm as a preferred IDE for working with code. We recently moved to PostMan as a preferred IDE for working with APIs. Our devs are used to the shortcuts on PyCharm, making it hard to use Postman API to write API definitions, review them, or discuss API design.  The most annoying part is code folding and unfolding. The shortcuts are different for PyCharm and Postman API Editor (https://github.com/ajaxorg/ace/wiki/Default-Keyboard-Shortcuts)

As an alternative, we copy the YAML in PyCharm, and go through it, and then add the comment on Postman, but it is troublesome. We want to explore if we can connect bitbucket with the postman collection, and API-reviewers would add the comment on the bitbucket.

The ability to customize the keyboard shortcuts would help us adopt postman as an API IDE quicker. 

Thanks.

**Comment by RubenMaier** [comment]
How much longer do you think it will take to include it? 5 years have passed since this article was started. Do you still think we don't need it? Or does the Postman community not care about us?

**Comment by bugoverfl0w** [comment]
> * vendor-ui.js

Great reply, thanks bro :D

I am using Ubuntu, I like this one ehheehe

**Comment by algorun77** [comment]
I'm adding my voice here. It's sad that a feature as needed as custom shortcuts is still not integrated after more than 5 years of asking. Everyone is used to it's own shortcuts, it should be available after all those years

**Comment by boan-jfm** [comment]
Maybe just have a `keybindings.json` without UI in the beginning - like Visual Studio Code: https://code.visualstudio.com/docs/getstarted/keybindings#_advanced-customization

**Comment by gbersac** [comment]
Much needed! On an azerty keyboard most shortcut just doesn't work.

**Comment by RollingHog** [comment]
Same here. `vendor-ui` doesn't work, GREPed and changed some other files without effect. `keybindings.json` or even simple explanation where to monkeypatch hotkeys would be really-really useful.

**Comment by 27shutterclicks** [comment]
+1 Would be great if there was a way to import key bindings definitions from another code editor. I've been using Brackets app lately and love their code editing hotkeys. Would be great to simply copy that over somehow.

**Comment by kha-pham-dss** [comment]
+1 for this. Toggle sidebar with Ctrl + \ is most uncommon way. It's difficult to use and slow to work with. 
Would be very helpful to let user custom shortcut. Thanks.

**Comment by seth-rah** [comment]
I stopped using postman because if they can't even prioritise the simplest of accessibility issues, then I don't feel like it's ever going to care about the needs of its users.

**Comment by hugojerez** [comment]
I know I'm reviving an old topic

I consider Postman as a professional tool, I hope I'm not wrong, but it can't be that only some actions have shortcuts and that they can't be edited

Of the few shortcuts that exist they are strange like CMD+E to rename instead of F2

<img width="180" alt="image" src="https://user-images.githubusercontent.com/5186975/203379085-20b891b6-d832-4bf3-ad98-29946c59f8e7.png">

**Comment by arlemi** [comment]
Hey everyone! 

We've added the ability to customize shortcuts in the latest version of the Postman app. Update your app and give it a go! 

![custom_shortcuts_preview](https://user-images.githubusercontent.com/5029719/220134887-ee0ac526-0524-41d5-8168-a55ee5c8f534.gif)

You can learn more about it on [the Learning Center](https://learning.postman.com/docs/getting-started/settings/#shortcuts).

**Comment by ilopmar** [comment]
This can't be true! I just want to use the same shortcuts as pretty much any other app: Firefox, Chrome, editors,... :sob: 

![image](https://user-images.githubusercontent.com/559192/220136091-8295d7a7-93be-432c-9aed-f356e37cdc6e.png)

**Comment by seth-rah** [comment]
It also appears that you've locked the remapping of some shortcuts while others are open to restricted editing.

![image](https://user-images.githubusercontent.com/2222634/220148453-62013479-970c-4e46-862f-e92b6ece70b0.png)

**Comment by seth-rah** [comment]
I can partially understand this, but at the same time the shortcuts in-app don't match the system shortcuts. 

For example on Windows F2 is rename. Why can't this be configured in Postman?

![image](https://user-images.githubusercontent.com/2222634/220149986-d8af190e-7da2-4c2b-a548-bb16e2f672fc.png)

**Comment by algorun77** [comment]
I'm very grateful that our requests has been heard but I agree with everyone, the customisation as is is very limited and does not allow us to match our system shortcuts or standardly used (like mentioned : F2 to rename, Ctrl+Page Down/Up to switch tabs, etc...).

Still, this is a first step and hope that a complete implementation will be done in the near future.

**Comment by planetabhi** [comment]
We plan to enable function keys, navigation keys, numeric keypads, and locked shortcuts in the next release, which is expected in mid-March.

**Comment by planetabhi** [comment]
> We plan to enable function keys, navigation keys, numeric keypads, and locked shortcuts in the next release, which is expected in mid-March.

We have enabled the function keys, control pad keys, and a few of the locked shortcuts in the latest release. Numeric keypad compatibility is in the pipeline for upcoming releases.

**Comment by algorun77** [comment]
> > We plan to enable function keys, navigation keys, numeric keypads, and locked shortcuts in the next release, which is expected in mid-March.
> 
> We have enabled the function keys, control pad keys, and a few of the locked shortcuts in the latest release. Numeric keypad compatibility is in the pipeline for upcoming releases.

Hello,
I can confirm that!

![image](https://user-images.githubusercontent.com/24519881/226637502-8eeed83e-6d9b-4e6b-9bb8-c7fb1812ff71.png)

That's really awesome, thank you very much 😄

**Comment by planetabhi** [comment]
> > We plan to enable function keys, navigation keys, numeric keypads, and locked shortcuts in the next release, which is expected in mid-March.
> 
> We have enabled the function keys, control pad keys, and a few of the locked shortcuts in the latest release. Numeric keypad compatibility is in the pipeline for upcoming releases.

We have also added support for numeric keypads in the latest v10.13 release.
