### ISSUE TITLE
Postman/Newman both resolve templated values of null as a string

### ISSUE THREAD

**Issue by cdanielsen** [a85/POSTMan-Chrome-Extension#2097]
**Setup**
1. Postman Version: 4.2.2
2. Chrome 50.0.2661.102
3. Windows 10 (win / x86-32)
4. Interceptor disabled
5. Bug seems to have always been there

**Steps to reproduce:** Attempt to resolve a templated value in a request with the valid JSON value of `null` via a global, environment, or data variable.  Example:

```
// Request body json
{
  “someKey": "{{someValue}}"
}

// DataFile (could be an environment or global variable as well)
[
 {
  “someValue": null
 }
]
```

**Expected behavior:** `someKey` should be resolved with the valid value of `null`

**Actual behavior:** `someKey` is resolved with the **string** "null"

**Comment by cdanielsen** [comment]
Bump?

**Comment by mstaalesen** [comment]
As said on slack. Removing the "" around {{someValue}} seems to solve it in Postman.

credit: bsn2007

**Comment by cdanielsen** [comment]
Think I was using an outdated version when I originally noticed this. Thanks!
