### ISSUE TITLE
Cannot disable hyperlinks in responses

### ISSUE THREAD

**Issue by phillip-haydon** [a85/POSTMan-Chrome-Extension#2098]
Please include the following:
1. Postman Version: 4.2.2
2. App (Chrome app or Mac app): Windows Chrome App
3. OS details: Windows 8.1
4. Is the Interceptor on and enabled in the app: No
5. Did you encounter this recently, or has this bug always been there: All the time
6. Expected behaviour: Copy paste link without it opening new tab
7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app): n/a
8. Screenshots (if applicable) n/a

Some guidelines: 
1. Please file Newman-related issues at https://github.com/postmanlabs/newman/issues
2. If it’s a Cloud-related issue, or you want to include personal information like your username / collection names, mail us at help@getpostman.com
3. If it’s a question (anything along the lines of “How do I … in Postman”), the answer might lie in our documentation - http://getpostman.com/docs.

---

When receiving a response from the server that contains a url. It's literally impossible to copy paste the link because it makes all links clickable. There is currently no setting to disable this and it causes a lot of pain trying to get 1 time urls to paste into a browser window.

**Comment by abhijitkane** [comment]
@phillip-haydon Got it. We'll soon push a fix that lets you copy the text without having it open a new tab.

**Comment by aditikul** [comment]
@phillip-haydon @abhijitkane You should be able to click and drag to select and copy the URL now. Earlier the URL got selected automatically. Let me know if this is working for you now.

**Comment by phillip-haydon** [comment]
Thanks a lot, will update tomorrow at work and give it a whirl. 

<3 Thanks for making this awesome app.

**Comment by phillip-haydon** [comment]
Whoops I forgot to reply. Yes it seems to work fine now. Thanks a lot!!!!
