### ISSUE TITLE
Syncronizing issues

### ISSUE THREAD

**Issue by mfranco84** [a85/POSTMan-Chrome-Extension#2100]
Please include the following:
1. Postman Version: 4.2.2
2. App (Chrome app or Mac app): Chrome 50.0.2661.102
3. OS details: win / x86-32 
4. Is the Interceptor on and enabled in the app: Yes
5. Did you encounter this recently, or has this bug always been there: Been There more than 3 months
6. Expected behaviour: Syncronize collection in a proper way

Hi, I belong to AristaMD team, we previously reported this issue. 
Syncronizing is leaving some requests, that were previously deleted, we must unsubscribe and subscribe again in order to get the correct collection.

**Comment by abhijitkane** [comment]
@mfranco84 Can you upgrade to the latest version (4.3.2), and then give it a shot? If it still happening, could you send us an email at help@getpostman.com with the exact steps that you're following?
