### ISSUE TITLE
Persist sort order

### ISSUE THREAD

**Issue by fmarais** [a85/POSTMan-Chrome-Extension#2102]
Please include the following:
1. Postman Version: **4.2.2**
2. App (Chrome app or Mac app): **Chrome**
3. OS details: **Linux**

Sort order is not persisting on restart of application, very annoying!

**Comment by numaanashraf** [comment]
@fmarais Could you let us know which sort order is not persisting and send us a screenshot if possible?

**Comment by fmarais** [comment]
The last selected sort order item does not persist on the 'Collections' list.
On startup of postman it seems to select the default sort item which in this case is 'Sort by name'

**Comment by sdnts** [comment]
Can you try updating to the latest version and try again? Fixes in v4.4 should solve your issue

**Comment by fmarais** [comment]
Hi there, thanks for the response

It looks like the issue still exists in v4.4.1

Some screenshots
_1st open (sorted by name a-z automatically) *_CORRECT*
[image: Inline image 1]

_1st open (selected sort by date) CORRECT_

_[image: Inline image 2]_

_2nd open after sorting by date(reverts back to 'sorted by name a-z
automatically')_
_INCORRECT, should persist previous sort order selected_

_[image: Inline image 3]_

_Hope this helps :)_

_Regards_

**Comment by sdnts** [comment]
@fmarais I can't see the images you attached, can you re-attach?

**Comment by fmarais** [comment]
Maby your mailing provider is blocking them, here they are as attachments
in a zip file :)
images.zip

**Comment by sdnts** [comment]
I've identified the error at our end, we'll push a fix for this in the next release.

**Comment by fmarais** [comment]
I can confirm that the 'persist collections sort order on restart' bug has
been fixed in v4.4.2

Nice, good work! 😄
