### ISSUE TITLE
templating value is overwritten by the value in header (template isn't saved)

### ISSUE THREAD

**Issue by jjmartin** [a85/POSTMan-Chrome-Extension#2103]
Please include the following:
1. Postman Version: 4.2.2
2. App (Chrome app or Mac app): Chrome app
3. OS details: Win 10/ x86-64  Chrome 50.0.2661.102
4. Is the Interceptor on and enabled in the app:  i think so
5. Did you encounter this recently, or has this bug always been there: probably always - just started using the templates
6. Expected behaviour:  when i put a template in a header value in my request header {{somevar}}  the template itself will be maintained.   However it gets replaced by the value of that variable and so if i later save the request - its lost its relationship with that variable.
7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
8. Screenshots (if applicable)

Before
![image](https://cloud.githubusercontent.com/assets/607183/15787879/89c38b06-2979-11e6-8626-086eeef3adb7.png)

After Send:
![image](https://cloud.githubusercontent.com/assets/607183/15787903/a2cec160-2979-11e6-9b96-2c2141d425fa.png)

**Comment by ebomcke** [comment]
Hey,
I'm experiencing the same issue, but only in the latest Postman Canary (Mac app) release. (Version 4.3.2-canary.2)

Tested with the Chrome app, the environment variables are correctly preserved (Chrome app v 4.3.2, Chrome v 51.0.2704.84, Interceptor enabled).

OS details : OSX v10.11.5 (15F34)

Etienne

**Comment by abhijitkane** [comment]
@jjmartin 
Can you upgrade to v4.3.2 of the Chrome app and check? I'm not able to reproduce this.

@ebomcke 
Reproducible on Postman Canary. We'll push a for this in the next release.

**Comment by czardoz** [comment]
@ebomcke, are you able to reproduce this in the latest version? (v4.4.2-canary.1)

**Comment by ebomcke** [comment]
@czardoz : I just tested it with v4.4.2-canary.1 and the issue is not present anymore.

**Comment by jjmartin** [comment]
i have 4.4.2 now and its still happening:

fresh load:
![image](https://cloud.githubusercontent.com/assets/607183/17024514/cff7e9e0-4f1d-11e6-81f1-ca51982e1819.png)
after i hit send:
![image](https://cloud.githubusercontent.com/assets/607183/17024542/efb6b1b2-4f1d-11e6-874b-d8698e9122c6.png)

so now if i was to save the request... the template value for {{aws_security_token}} would be gone and the temp security token that i have in my global vars that is only valid for like 10 minutes would be there.
