### ISSUE TITLE
Font is too small for my vision and this cannot be increased in other ways than hacking the code

### ISSUE THREAD

**Issue by barbu110** [a85/POSTMan-Chrome-Extension#2104]
The UI font in the application is very very small. I am having vision problems and it's always a struggle to use the application. Although I like it, I will probably have to move away if you guys don't give a hacking solution of changing the code somehow. 

The results font can be changed in settings. However the overall UI font cannot be changed in any way. What can be done for a temporary solution, at least?

**Comment by barbu110** [comment]
Great that nobody cares about accessibility here.

**Comment by aditikul** [comment]
@barbu110 I assure you that we care. We've pushed a couple of updates over the last few months that improves legibility on the app, however there are several resolutions and screen sizes that we need to take into account. We are also going to push another update very soon which will allow you to customize the view further and increase/decrease viewport as needed. If you can share screenshots of how this looks for you it will help us fix the issue faster.

**Comment by barbu110** [comment]
![image](https://cloud.githubusercontent.com/assets/7272395/17294314/ae9e3db4-57fe-11e6-8dd2-aabc290a4708.png)

This is how it looks my screen. Basically, I would increase the `font-size` (for my screen) with like `4px` at lease so it would be `15px - 18px`.

**Comment by danielmcq** [comment]
I would like to add that a fix for this would be appreciated by users who have very high resolution screens as well.
It would be nice if changing the font size worked like it already does in Chrome, where you can use `Ctrl`+`+` (`⌘`+`+`) or `Ctrl`+`-`(`⌘`+`-`) to increase or decrease.

**Comment by a85** [comment]
@danielmcq You can use this now. Check out Settings > Shortcuts to see how:

<img width="701" alt="screenshot 2016-09-10 14 04 34" src="https://cloud.githubusercontent.com/assets/653409/18413533/84ccf89c-775f-11e6-8563-ebb589590804.png">

**Comment by dfesenko** [comment]
To change the size of the font you should use `Ctrl` + `+`, but not that `+` button that is located in the area of Num Lock, but that that is located near the `Backspace` or `Enter` buttons. This button has both `+` and `=` signs on it. For me, only this button works.

**Comment by j0a0m4** [comment]
Thanks @dfesenko, I was also having the same issue.
