### ISSUE TITLE
Curl command Import

### ISSUE THREAD

**Issue by ameymahadik** [a85/POSTMan-Chrome-Extension#2105]
Hi 

I am trying to import the below curl command and then run it on postman but it gives me an error - Not Found"

Whereas when i run the same command using curl - it works fine and i receive a valid json string in return

curl https://api-sandbox.uphold.com/oauth2/token -X POST -H "Content-Type: application/x-www-form-urlencoded" -u f21abe7ec197bb5f841b53bce10dde670c4f20aa:feae50496d0d14594cc45e91f549f0a3406e6384 -d "code=0e61e945eaca1589d7de4250214330ddd2482464&grant_type=authorization_code"

Please include the following:
1. Postman Version:4.2.2
2. App (Chrome app or Mac app): Chrome 50.0.2661.102
3. OS details: Windows 7

**Comment by a85** [comment]
Seems to work fine for me. Can you check by updating to the latest version?

**Comment by ameymahadik** [comment]
Hi

Still does not work ... tried with the latest version as well

Try importing the below command

curl https://api-sandbox.uphold.com/oauth2/token -X POST -u
f21abe7ec197bb5f841b53bce10dde670c4f20aa:feae50496d0d14594cc45e91f549f0a3406e6384
-d "grant_type=client_credentials&scope=vouchers:read vouchers:write"

When i run the same using curl , i get the below json response

{"error":"unauthorized_client"}

If I try the same after importing it in postman it gives a different error

Not Found

Regards,
Amey

**Comment by abhijitkane** [comment]
@ameymahadik This is due to the server rejecting requests with the "origin" header that Chrome sends.

This request fails in curl too:

```
curl https://api-sandbox.uphold.com/oauth2/token -X POST -H 'origin: chrome-extension://fhbjgbiflinjbdggehcddcbncdddomop' -u f21abe7ec197bb5f841b53bce10dde670c4f20aa:feae50496d0d14594cc45e91f549f0a3406e6384 -d "grant_type=client_credentials&scope=vouchers:read vouchers:write"
```
