### ISSUE TITLE
Delete button not visible when clicking Existing Tokens Name

### ISSUE THREAD

**Issue by RonakThakkar** [a85/POSTMan-Chrome-Extension#2106]
Please include the following:
1. Postman Version:4.3.0
2. App (Chrome app or Mac app): Chrome app
3. OS details: Windows
4. Is the Interceptor on and enabled in the app: Don't know. But may be not.
5. Did you encounter this recently, or has this bug always been there: Yes, after release of version 4.3.0
6. Expected behaviour: Delete button for deleting Tokens was there previously.
7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
8. Screenshots (if applicable)

**Comment by numaanashraf** [comment]
@RonakThakkar We've changed the design of OAuth2 Token List a bit in 4.3.0. You can now select a token from the list to see the token details Postman received during authorisation. You can find the delete button at the top of this detailed token view.

![oauth2deletetoken](https://cloud.githubusercontent.com/assets/3295568/15812999/db71eed2-2bd8-11e6-8c4e-f7f70f17738a.jpg)

**Comment by RonakThakkar** [comment]
Here is what I see.

![postman-tokenerror](https://cloud.githubusercontent.com/assets/10152601/15813209/bdbda082-2bda-11e6-8e47-4e120ece6b0c.png)

**Comment by numaanashraf** [comment]
@RonakThakkar that looks like a bug. We'll include a fix for this in the next release.

**Comment by RonakThakkar** [comment]
I found the problem. There is a long horizontal scroll bar and then at end I get 2 buttons, Use Token and Delete. 

I think Token text is not wrapped properly. It does not look good so please fix that.

**Comment by RonakThakkar** [comment]
This is small but important to fix as we have to horizontal scroll so long for "Use Token" button to be accessible.

**Comment by efvincent** [comment]
+1 - Renders Postman unusable in my environment where we're constantly generating new bearer tokens, can't get to the "Use Token" button without obscene amount of scrolling. 
- Postman v4.3.0
- win / x86-32
- Chrome 50.0.2661.102

**Comment by sdnts** [comment]
Can you update to the latest version and check if this is fixed? We pushed a fix recently

**Comment by efvincent** [comment]
It's much better, the right hand pane is now fully visible horizontally, which means the "Delete" and "Use Token" buttons are in reach. There still seem to be layout issues, for example with a bearer token selected, the value of the `access_token` now wraps, but now is so long that it flows out the bottom of the  "Authorization" section of the request pane, behind the entire response pane, and beyond the response pane vertically. 

This doesn't effect usability, for me anyway. But it looks a bit sloppy so you may want to take a look at it. Here's a shot: 
![image](https://cloud.githubusercontent.com/assets/647610/16390245/d35ea97c-3c6f-11e6-8bbd-c21b3b9079b9.png)

**Comment by sdnts** [comment]
@efvincent We pushed changes that should fix your issue. Feel free to reopen if the issue persists :)
