### ISSUE TITLE
Feature Request - Request POJO code generation 

### ISSUE THREAD

**Issue by ed-george** [a85/POSTMan-Chrome-Extension#2107]
Postman Version: 4.2.2
App (Chrome app or Mac app): Chrome App
OS details: Mac

I believe it would be highly beneficial for the application to add POJO creation within its "Generate Code" Java section.

Many popular libraries (e.g. Retrofit, GSON) use POJOs in HTTP requests during serialization, so having Postman generate these objects from a request would therefore be quite useful.

An example of what I'd expect this feature to do can be seen using this example 
## Request (in cURL format)

```
curl -X POST -H "Content-Type: application/json" -d '{
  "Email": "email@example.com",
  "Password": "password",
  "Settings": {
    "MySetting": true
  }
}' "http://example.com/login"
```
## Generated

```
public class LoginRequest {
    private String email;
    private String password;
    private Settings settings;

   public String getEmail(){ return email; }
   public void setEmail(String email){ 
      this.email = email;
   }
   // ... more getters and setters 
}

public class Settings {
    public boolean mySetting;
    public void getMySetting(){ return mySetting; }
    public boolean setMySetting(boolean mySetting){
        this.mySetting = mySetting;
    }
}
```

**Comment by abhijitkane** [comment]
@ed-george Can you file this at https://github.com/Mashape/httpsnippet? That's the library we're using to generate code snippets.

**Comment by ed-george** [comment]
Thank you @abhijitkane - I have filed a request [here](https://github.com/Mashape/httpsnippet/issues/79)
