### ISSUE TITLE
Don't save keyboard shortcut

### ISSUE THREAD

**Issue by ryanfreeth** [a85/POSTMan-Chrome-Extension#2110]
1. Postman Version: 4.2.2
2. App (Chrome app or Mac app): Chrome App
3. OS details: Windows 8.1
4. Is the Interceptor on and enabled in the app: No (N/A)
5. Did you encounter this recently, or has this bug always been there: Just noticed. Not sure about the history of it.
6. Expected behaviour: Keyboard goodness

Hey Postman!

Is it possible to get keyboard shortcuts for the `Do you want to save?` dialog?
I would love to press `d` to not save.
Esc works for Cancel, Enter works well for Save. But I mostly want to not save.

Thank you

**Comment by mstaalesen** [comment]
Try the spacebar :)

**Comment by ryanfreeth** [comment]
Totally works.
I never noticed that Don't Save had focus before.
