### ISSUE TITLE
Postman Json parser not invalidating incorrect json

### ISSUE THREAD

**Issue by Rahul91** [a85/POSTMan-Chrome-Extension#2111]
I am using RESTful flask api and I was able to post the following payload and got the respective reply:

![screenshot from 2016-06-02 13 20 45](https://cloud.githubusercontent.com/assets/4932690/15737686/034a91fa-28c5-11e6-81cc-bbe2a9f2e222.png)

Then I tried validating json itself on http://www.jsoneditoronline.org/ , I got this error while parsing json:

![screenshot from 2016-06-02 11 54 55](https://cloud.githubusercontent.com/assets/4932690/15737705/2736590a-28c5-11e6-9cb8-423a9f2999d4.png)

Another json online parser http://jsonviewer.stack.hu/ , converted int(002) to 2 and parsed the json

I got the following error when tried parsing from python, confirming that the json is incorrect.

![screenshot from 2016-06-02 13 44 51](https://cloud.githubusercontent.com/assets/4932690/15738292/4318df00-28c8-11e6-9701-a1ae30f9c4b5.png)

Possible Issue: Postman should notify me for incorrect json.

Meta Detail:
1. Postman Version: 4.3.0
2. App (Chrome app or Mac app): Chrome
3. OS details: Linux Ubuntu 14.04
4. Is the Interceptor on and enabled in the app: False
5. Did you encounter this recently, or has this bug always been there: Yes

**Comment by chauhan130** [comment]
Wasted 3 hours thinking something is wrong with my code, considering POSTMan parses the json correctly:

http://prntscr.com/elsiem
http://prntscr.com/elsj4r

I am on Version 4.10.3.

**Comment by a85** [comment]
Closing this as this was filed for a much older version.
