### ISSUE TITLE
Postman is getting crashed with 2GB file size attachment.

### ISSUE THREAD

**Issue by dmthakrar** [a85/POSTMan-Chrome-Extension#2112]
Please include the following:
1. Postman Version: 4.3.0
2. App (Chrome app or Mac app): Chrome 50.0.2661.102
3. OS details: win / x86-32
4. Is the Interceptor on and enabled in the app:
5. Did you encounter this recently, or has this bug always been there: recently face this issue, it was working fine with old version
6. Expected behaviour: File should be attached / success fully uploaded
7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
8. Screenshots (if applicable)
   ![chrome](https://cloud.githubusercontent.com/assets/14257953/15897904/d7c8a0e6-2db3-11e6-88f7-4892c3c5f53d.png)

**Comment by abhijitkane** [comment]
Tracking at https://github.com/postmanlabs/postman-app-support/issues/1946

**Comment by shamasis** [comment]
seems like in Postman v4.5+ the app does not crash when uploading large files in form-data mode. The binary mode is still crashing though.

**Comment by khushboovdesai** [comment]
I am using v5.1.2 ; interceptor = enabled; filesize = 2.4gb . Neither form-data works nor binary. Help needed to resolve this.
TIA

**Comment by sdnts** [comment]
@khushboovdesai Are you on one of our native apps?
