### ISSUE TITLE
Collection Runner not substituting values from CSV

### ISSUE THREAD

**Issue by stefanomcghee** [a85/POSTMan-Chrome-Extension#2113]
Please include the following:

Postman Version:4.3.0
OS X / x86-64
Chrome 51.0.2704.84
1. Is the Interceptor on and enabled in the app: No
2. Did you encounter this recently, or has this bug always been there: Always there
3. Expected behaviour: GET contains data from CSV
4. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
5. Screenshots (if applicable)

Using a request formatted like this:
http://myserver/registration-rest/subscribeUser?ModelType=Student%20Seat%20based&OrganizationId={{orgid}}&LearningContextRole={{roleid}}&SubscribeType=Institutional%20Licensing&ProductId={{productid}}&UserId={{userid}}

and a CSV file formatted like this:
role,orgid,productid,userid
Student,8a9480bc28dee8910128e413607856f0,8918,ffffffff53ff6df2e4b062dee5175bf7
Student,8a9480bc28dee8910128e413607856f0,8918,ffffffff53ff6df2e4b0be88133f4544

When I use Collection Runner, it previews correctly but does not submit the substituted information. Instead I get an error from the server because it is being presented with the variables {{roleid}} and the other variables instead of the actual data in the CSV file.

What am I missing? I have a CSV file with over 5000 values I would like to provide in a file if I can get this to work.

**Comment by abhijitkane** [comment]
@stefanomcghee The CSV fole says 'role', and the URL says roleid.

Can you try running this collection: https://www.getpostman.com/collections/87d02029976ee533e360 with a simple data file:

```
name
n1
n2
```
