### ISSUE TITLE
Feature request: JSON array count

### ISSUE THREAD

**Issue by bertyhell** [a85/POSTMan-Chrome-Extension#2115]
It would be nice to show counts for arrays inside JSON replies:

eg:
Instead of:

``` json
{
  "posts": [
      {"item1": {}},
      {"item2": {}},
      {"item3": {}}
  ]
}
```

Add a counter for the arrays in the pretty printen view:

``` json
{
  "posts": [     length: 3
      {"item1": {}},
      {"item2": {}},
      {"item3": {}}
  ]
}
```

Chrome console does something similar:
![image](https://cloud.githubusercontent.com/assets/1710840/15957544/20e27b84-2ef0-11e6-8d32-fba5c282c523.png)

**Comment by dougludlow** [comment]
+1

**Comment by dougludlow** [comment]
Possible duplicate of #1678.

**Comment by sobtiankit** [comment]
We'll add this to the feature list. In the meantime, one solution for this would be to add this in your test script:

var body = JSON.parse(responseBody);
tests["Posts length is " + body.posts && body.posts.length] = true;

which will show you the array size in the tests tab.

What do you think @dougludlow @bertyhell ?

**Comment by dougludlow** [comment]
Ah, nice, @sobtiankit. I was trying to figure out a way to display this in the tests. Thanks!

**Comment by bertyhell** [comment]
@sobtiankit Works great, thx

**Comment by rchadha** [comment]
@sobtiankit awesome!! thanks

**Comment by sdnts** [comment]
Guys, closing this as #1678 looks like the same thing. We're working on making this possible. Will update everyone on that thread :)

**Comment by NicolasChaillou** [comment]
Hi, today Sobtianky made my day, since I found that all 'length' troubles, as a noob dev on this I do add a few :

var body = JSON.parse(responseBody)."WHAT YOU SEEK FOR";
// initialize
tests["Posts length is " + body.length && body.length] = true;

**Comment by kazi-rashedul-haque** [comment]
> Hi, today Sobtianky made my day, since I found that all 'length' troubles, as a noob dev on this I do add a few :
> 
> var body = JSON.parse(responseBody)."WHAT YOU SEEK FOR";
> // initialize
> tests["Posts length is " + body.length && body.length] = true;

Thank you man, this is exactly what I was looking for.

**Comment by jlroth051785** [comment]
Hello  @sobtiankit , can you help explain why the last statement tests["Posts length is " + body.length && body.length] = true; gives you the number of items in your array? I tried this with my array and it worked, but I am only getting the number 27 which is the number of objects in my array. I guess I am wondering why body.length; isn't sufficient.

Thanks,
Joe
