### ISSUE TITLE
Content is not active after open Generate code snippet pop-up

### ISSUE THREAD

**Issue by adequatica** [a85/POSTMan-Chrome-Extension#2118]
Steps:
1. In Postman builder after created request click [Generate Code];
2. Generate code snippets pop-up appears;
3. Press CMD+A – search form in background was selected, but nothing changed in pop-up.

Content area in Generate code snippet pop-up is not active after open, it cases manual click to [Copy to Clipboard] for coping cURL command.

Expected behaviour, that context of opened pop-up does not lost and can be accessed by keyboard shortcuts: click [Generate Code], press CMD+A – cURL command is selected, press CMD+C – cURL command is copied. 
1. Postman Version: 4.3.2
2. App (Chrome app or Mac app): Mac app
3. OS details: 10.11.5
4. Is the Interceptor on and enabled in the app: No
5. Did you encounter this recently, or has this bug always been there: always been and pisses off

**Comment by a85** [comment]
@numaanashraf The focus should shift to the Generate Code modal automatically.

**Comment by sdnts** [comment]
Can you update to the latest version (4.4.1) and try again? A fix went in that should solve your issue.

**Comment by adequatica** [comment]
Fixed, thanks a lot, now works as expected!
