### ISSUE TITLE
Test runner - "current run" section to small to use

### ISSUE THREAD

**Issue by danballance** [a85/POSTMan-Chrome-Extension#2119]
I think the trigger was deleting all of my previous test runs from the left-hand panel. This seemed to cause the div (I'm guessing it's a div!) under current run to become very small. So small I can't access my projects to run more tests. Please see screenshot, it should hopefully make the problem clearer.

I've tried all manner of restarts and ways I can think of to try and get the section to expand, but I just can't get to my tests. Postman is amazing - this is the first issue I have hit - but I now can't run any of my tests. Will probably try the Node module in the meantime so I can work.

Thanks in advance for all of your hard work on this project, it's one of the best out there IMHO :)
1. Postman Version: 4.3.2
2. App: Chrome app
3. OS details: Ubuntu 13.10 64bit
4. Is the Interceptor on and enabled in the app: No
5. Did you encounter this recently, or has this bug always been there: not seen the issue before
6. Expected behaviour: I can run my tests

![test-runnerissue](https://cloud.githubusercontent.com/assets/13839912/16044202/66d3e7a6-323b-11e6-966f-1ba10b079d98.png)

**Comment by numaanashraf** [comment]
@danballance Could you let us know your Chrome version too?

**Comment by danballance** [comment]
Hi, yes of course: Chrome 48.0.2564.97

**Comment by abhijitkane** [comment]
@danballance Can you upgrade to v4.3.3 and check? This should be fixed now.

(chrome://extensions, enable 'Developer Tools', 'Update extensions now')

**Comment by danballance** [comment]
Sorry for the long delay on this. I can confirm that this is now working for me. Thanks ever so much for your help!
