### ISSUE TITLE
Ability to move requests from one collection to another

### ISSUE THREAD

**Issue by snarglefarg** [a85/POSTMan-Chrome-Extension#212]
I would like the ability to move requests (one by one or in a group) to another collection.

As I built up my collection, I realized that I should have created multiple collections for better organization. Moving my existing requests to new collections would be a welcome addition.

**Comment by sGuid** [comment]
This isn't working for me either, I can only drag within collections, and not between collections.  Is this suppose to still be working, or is there already a bug for this?

Version 48.0.2564.116 (64-bit)

**Comment by jaumeavila** [comment]
+1

**Comment by ETMilord** [comment]
+1

**Comment by PBSJ** [comment]
+1

**Comment by dchien234** [comment]
+1

**Comment by arlemi** [comment]
@DangChien This is already feasible, you can drag and drop your requests to any other collection.

**Comment by green-green-avk** [comment]
+1

**Comment by kalimbra** [comment]
In linux, what I do is to go where the collections files are kept, and move the according files to the correct collections (generally I copy  / paste, then delete them later if all is ok) .

**Comment by bigunyak** [comment]
Drag and drop is not working for me on Mac in v1.28.0 :(

**Comment by sony-mathew** [comment]
Hey @bigunyak, 

Thank you for reaching out to us about the issue you're experiencing. We're here to help you resolve it as quickly as possible.

To better understand the problem, could you please provide us with some additional information? Specifically, we'd love to see:

* A screenshot of the Postman version you're using (like the one below)
* A detailed description of the error you're encountering, including any error messages or codes you've received
* If possible, a screenshot or screen recording of the error in action

This will help us investigate the issue more efficiently and provide a more accurate solution. We appreciate your help in gathering this information and look forward to resolving your issue soon!


![Screenshot 2024-09-11 at 12 45 01 PM](https://github.com/user-attachments/assets/b6efc064-e086-4761-93e5-762a7aa2a9ed)
