### ISSUE TITLE
Postman does not send any requests

### ISSUE THREAD

**Issue by NikKosse** [a85/POSTMan-Chrome-Extension#2120]
System and error info:
1. Postman Version: 4.3.2
2. App (Chrome app or Mac app): Chrome App
3. OS details: Windows 7 SP 1
4. Is the Interceptor on and enabled in the app: No and no
5. Did you encounter this recently, or has this bug always been there: recently, first started a week ago
6. Expected behaviour: send any kind of request
7. Console logs: No errors appear in the console!  Looking at the network tab when trying to send a request, nothing shows up.  It's like nothing happens at all when I click the send button.

I have tried to google for the issue and have been unable to find anyone else with the same problem, outside of this post: https://github.com/postmanlabs/postman-app-support/issues/712.  The fix for that problem did not solve my issue.

**Comment by abhijitkane** [comment]
@NikKosse Can you attach a screen recording using something like http://www.cockos.com/licecap/?

**Comment by NikKosse** [comment]
![Here ya go!](https://cloud.githubusercontent.com/assets/1736386/16083999/b2d3fb72-32dc-11e6-937a-d7d3c24a1856.gif)  As you can see, there is nothing happening in postman when I try to send a request.

**Comment by numaanashraf** [comment]
@NikKosse Could you let us know your Chrome version too?

**Comment by NikKosse** [comment]
Chrome version: 51.0.2704.84 m

**Comment by NikKosse** [comment]
Any word on a fix for this?  Or anything I can do to try and fix it myself?

**Comment by abhijitkane** [comment]
@NikKosse Can you uncheck the 'Disable Cache' box? If that doesn't help, can you attach a screenshot of your Postman settings (wrench icon in the top right)?

**Comment by NikKosse** [comment]
Unchecking the disable cache button didn't change anything.  I have attached the screenshot of the settings page, as well as a screenshot of the about page, in case there's anything there that can help you.  Thanks!

![general settings](https://cloud.githubusercontent.com/assets/1736386/16991761/5452d2ca-4e62-11e6-9571-f4fec1770e03.PNG)
![about postman](https://cloud.githubusercontent.com/assets/1736386/16991767/5795de8c-4e62-11e6-85f5-3a873c764f02.PNG)

**Comment by numaanashraf** [comment]
@NikKosse Are you still facing this issue in the current version (v4.7.2) of the Chrome App? We are not able to replicate this at our end. Also, could you check if you are facing a similar issue with our native Windows app? www.getpostman.com/apps.

Google is deprecating the Chrome App platform and we highly recommend moving to our native client. You can find more info regarding this at http://blog.getpostman.com/2016/08/23/using-the-postman-chrome-app-implications-from-the-recent-google-announcement/

**Comment by NikKosse** [comment]
I do not see the issue in the chrome app, only in the native app.
