### ISSUE TITLE
POST not working when Body is empty

### ISSUE THREAD

**Issue by kevinplaut** [a85/POSTMan-Chrome-Extension#2121]
Please include the following:
1. Postman Version: 
   4.3.2
   win / x86-64
   Chrome 51.0.2704.84
2. App (Chrome app or Mac app): 
   Chrome ver. 51.0.2704.84 m (64-bit)
3. OS details: 
   Windows 7 Professional, version 6.1 (Build 7601: Service Pack 1)
4. Is the Interceptor on and enabled in the app:
   Yes
5. Did you encounter this recently, or has this bug always been there:
   Just recently noticed, might have always been there but not sure.
6. Expected behavior:
   POST would work without needing a line item added in the Body. 
   6.2 Current behavior: 
   If the Body is empty, POST returns `<h2>Incomplete response received from application</h2>`. POST returns correct response when there is any line item in Body, including one without any values.
7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
   <
   3extensions::platformApp:17window.localStorage is not available in packaged apps. Use chrome.storage.local instead.(anonymous function) @ extensions::platformApp:17
   extensions::platformApp:17beforeunload is not available in packaged apps.(anonymous function) @ extensions::platformApp:17
   sails.io.js:142 Connected to Sync server
   >
8. Screenshots (if applicable)

Some guidelines: 
1. Please file Newman-related issues at https://github.com/postmanlabs/newman/issues
2. If it’s a Cloud-related issue, or you want to include personal information like your username / collection names, mail us at help@getpostman.com
3. If it’s a question (anything along the lines of “How do I … in Postman”), the answer might lie in our documentation - http://getpostman.com/docs.

**Comment by abhijitkane** [comment]
@kevinplaut Can you try changing the URL to http://echo.getpostman.com/post, and see if you face the same problem?

**Comment by kevinplaut** [comment]
Hi @abhijitkane, thanks for the quick reply! I'm not seeing the issue for that URL (
http://echo.getpostman.com/post). And a colleague here didn't have the
issue using a Mac on any of the URLs I'm having the issue with.

**Comment by abhijitkane** [comment]
@kevinplaut Does toggling the Interceptor off help?

With the Interceptor off, you can check the network tab (https://www.getpostman.com/docs/errors) to see the exact request payload that was sent.

**Comment by kevinplaut** [comment]
@abhijitkane That did it! I haven't been using Interceptor for too long so forgot to try
with  that off (and the Mac user had it on with no issues), but
it seems that was causing the issue on my machine. With Interceptor
off it works as expected. With Interceptor on it looks like the request
isn't being sent at all. The attached screenshot (bottom two highlighted
lines) is what Network shows when requesting with Interceptor on. 
![image](https://cloud.githubusercontent.com/assets/17710142/16060799/6c57075a-323e-11e6-86be-04eee773419e.png)

**Comment by abhijitkane** [comment]
@kevinplaut When using the Interceptor, you'll need to open the DevTools window of the Interceptor. That's where the XHR request is actually fired from.

**Comment by kevinplaut** [comment]
@abhijitkane Ah ok, please see the attached screenshot showing the request I'm getting the issue with.
![image](https://cloud.githubusercontent.com/assets/17710142/16062707/d8c2c108-3249-11e6-98c5-88946e7ba115.png)

**Comment by abhijitkane** [comment]
A `502` indicates a server error. Is there anything odd in your server logs when you make the request?

**Comment by kevinplaut** [comment]
@abhijitkane Unfortunately no, or at least that I can see.
