### ISSUE TITLE
postman getting crashed while executing collection from Runner

### ISSUE THREAD

**Issue by asifpasha29** [a85/POSTMan-Chrome-Extension#2122]
Please include the following:
1. Postman Version:4.3.2
2. App (Chrome app or Mac app):Chrome 51.0.2704.84
3. OS details:win / x86-64
4. Is the Interceptor on and enabled in the app:yes
5. Did you encounter this recently, or has this bug always been there:yes
6. Expected behaviour:no
7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
8. Screenshots (if applicable)

**Comment by abhijitkane** [comment]
@asifpasha29 Can you provide the exact steps to reproduce this problem? Is this happening with every collection you run, or just one collection?

What happens if you toggle the Interceptor off and try?

**Comment by asifpasha29** [comment]
steps to reproduce:
1. create any post request with necessary elements in xml
   2.build database query in test tab to fetch data from database
2. create one node.js database  service to fetch the database values and insert query in body which we created in post request test tab.
3. here we are getting first time previous request response and again hit same service we are getting excepted response which not previous response

**Comment by abhijitkane** [comment]
@asifpasha29 "Getting expected response which is not previous response" is not the same as the issue title.

Can you include screenshots that shows the issue you're facing?
