### ISSUE TITLE
 Garbage collection -getting invalid reponse-we need to get response as : "abc" which is expected from the current api but we are getting "xyz" which response of the previous request and we are used 

### ISSUE THREAD

**Issue by asifpasha29** [a85/POSTMan-Chrome-Extension#2123]
Hi 
Garbage collection - when we run the individual request , we are getting previous request response and hit same request once again we are getting result as expected

Postman Version:4.3.2
App (Chrome app or Mac app):Chrome 51.0.2704.84
OS details:win / x86-64
Is the Interceptor on and enabled in the app:yes
Did you encounter this recently, or has this bug always been there:yes
Expected behaviour:

we need to get response as : "abc" which is expected from the current api but we are getting "xyz" which response of the previous request and we are used 

postman.clearGlobalVariable("variable_key");

postman.clearEnvironmentVariable("variable_key");

still issue is persist this issue is random

please help me on this.

**Comment by abhijitkane** [comment]
@asifpasha29 What happens if you try with the Interceptor off?
You can also re-enable the Interceptor by going to `chrome://extensions`

**Comment by asifpasha29** [comment]
Hi ,

Even I tried both way it's coming same as I mentioned above

Thanks & regards,
Ashid

**Comment by abhijitkane** [comment]
@asifpasha29 If you're still seeing this, can you check the Network tab in the console (https://www.getpostman.com/docs/errors)? This will show the exact request/response payloads that Postman is sending/receiving.

**Comment by sdnts** [comment]
@asifpasha29 Is this still reproducible?
