### ISSUE TITLE
Test failing to pick up on error 400 

### ISSUE THREAD

**Issue by dnoakeselcom** [a85/POSTMan-Chrome-Extension#2124]
Currently using a test to make sure any failure is captured without using any text as the 400 error can have a different error text, depending on the XML sent

tests["Status code is 400"] = responseCode.code === 400;

It is failing to pick up the 400 code from the XML response;

<?xml version="1.0"?>
<!DOCTYPE cXML SYSTEM "http://xml.cxml.org/schemas/cXML/1.1.010/cXML.dtd">
<cXML version="1.1.010" payloadID="1466006354039" timestamp="2016-06-15T11:59:14-05:00" xml:lang="en-US">
    <Response>
        <Status code="400" text="failure">Reason text</Status>
    </Response>
</cXML>

**Comment by abhijitkane** [comment]
The "400" is not the response code. You'll need to use xml2Json (https://www.getpostman.com/docs/sandbox) to parse the response, and then check for the 400.

`responseCode.code` refers to the HTTP response code, which is `200` in the attached screenshot.

<img width="335" alt="screen shot 2016-06-16 at 01 58 37" src="https://cloud.githubusercontent.com/assets/681190/16096290/dfac5002-3365-11e6-8056-846a6f85e176.png">

**Comment by romanbarabash** [comment]
works for me, btw:
```
var jsonData = JSON.parse(responseBody);
tests["Status code is 400"] = jsonData.statusCode === 400;
```
where  `.statusCode` is "statusCode": 400 in json response.
