### ISSUE TITLE
OAuth1 authentication failure with POST and certain characters in post vars

### ISSUE THREAD

**Issue by webward09** [a85/POSTMan-Chrome-Extension#2125]
Hi

Recently I have found OAuth1 authentication has been failing when using Postman to make the requests.

The verification only fails when doing a POST, where the body is sent as x-www-form-urlencoded, and the post parameters contain certain characters (space, or any of @%&"$?,:) 
eg. if the Body contains:
name:Test User
email:test@test.com
Verification will fail on the server due to the space and 'at' symbol characters.

I believe this is a Postman issue as no changes have been made to the client code, and it had been working before (sometime in the last few months). I have tried using the http://echo.getpostman.com service to debug the problem but unfortunately there is no endpoint that combines oauth1 and POST. GET requests continue to work fine.

So it looks like a url encoding issue affecting OAuth1 posts only. I am using Andy Smith's [oauth-php](https://code.google.com/archive/p/oauth-php/) on the server.
1. Postman Version: 4.3.2
2. App (Chrome app or Mac app): Chrome extension
3. OS details: Windows 7 Professional 64bit
4. Is the Interceptor on and enabled in the app: installed but turned off
5. Did you encounter this recently, or has this bug always been there: Recently
6. Expected behaviour: OAuth1 verification should not change regardless of postvars content

**Comment by webward09** [comment]
Just to update on this, using the Developer tools I checked the base string coming out from Postman. For the post var value "test@test.com", the base string contains "test%252540test.com", showing that the string has been url encoded 3 times. 
However for the post var value "test'test.com", the base string contains "test%2527test.com", showing that the string has been url encoded 2 times. So there is an inconsistency there.

**Comment by webward09** [comment]
So can I please get confirmation that this is actually a bug? 

I know OAuth 1 isn't as popular as OAuth 2. But for those of us who do use OAuth1, we need it to work properly.

**Comment by abhijitkane** [comment]
@webward09 - 
`encodeURIComponent("test'test.com")` gives `test'test.com`
`encodeURIComponent("test@test.com")` gives `test%40test.com`

We tried using Twitter's OAuth1 API, and Postman seems to work fine. I've attached a screenshot of the Postman window that produced the last 3-4 tweets at https://twitter.com/____hal9000____

<img width="938" alt="screen shot 2016-06-23 at 01 50 34" src="https://cloud.githubusercontent.com/assets/681190/16282149/14da6320-38e5-11e6-9af7-e9d1ef6d3aa9.png">

The status contains special chars, and the call worked with spaces etc. too.

**Comment by webward09** [comment]
Hi abhijitkane,

Thanks for getting back to me. In your Twitter example you used form-data. The bug only appears with x-www-form-urlencoded.

I have reproduced the problem with a test Twitter account https://twitter.com/oauth1testing. In the first example, I am posting testing@testing.com as the status. In the second example, posting testing.testing.com as the status allows the post to go through.

![twitter-post-fail](https://cloud.githubusercontent.com/assets/9889506/16302291/3011bb4a-3942-11e6-971f-bcfc0ef88534.JPG)
![twitter-post-success](https://cloud.githubusercontent.com/assets/9889506/16302297/35f3b05e-3942-11e6-8c51-9ce2046f1996.JPG)

**Comment by abhijitkane** [comment]
@webward09 Thanks for reporting this. We'll push a fix in the next release.

**Comment by abhijitkane** [comment]
@webward09 This has been fixed in v4.4.2 of the app (Chrome only). Can you update (https://www.getpostman.com/docs/updating) and check?

**Comment by webward09** [comment]
Hi @abhijitkane 

Yes, I can confirm this is fixed. I tested in Postman 4.4.2 (Chrome) using our own system and also using twitter. All looks good.

Thanks for the fix.
