### ISSUE TITLE
Postman Post/Put/Delete doesn't work - 403 forbidden

### ISSUE THREAD

**Issue by jefferyyuan** [a85/POSTMan-Chrome-Extension#2126]
Thanks for building this useful tool.

Found today that Post/Put/Delete doesn't work - it returns 403 forbidden.

**This problem happens in multiple setup - mine, and 3 other coworkers.**
- Postman doesn't send out request at all. I add breakpoint in server side.

I followed http://blog.getpostman.com/2015/06/13/debugging-postman-requests/, it failed at xhr.send.

Please fix this as this will make postman totally not woking.

This is stack trace from postman:
background_page.js:447 POST ...... 403 (Forbidden)
sendXhrRequest  @   background_page.js:447
addToQueue  @   background_page.js:536
onExternalMessage   @   background_page.js:554
target.(anonymous function) @   extensions::SafeBuiltins:19
EventImpl.dispatchToListener    @   extensions::event_bindings:388
target.(anonymous function) @   extensions::SafeBuiltins:19
publicClassPrototype.(anonymous function)   @   extensions::utils:151
EventImpl.dispatch_ @   extensions::event_bindings:372
EventImpl.dispatch  @   extensions::event_bindings:394
target.(anonymous function) @   extensions::SafeBuiltins:19
publicClassPrototype.(anonymous function)   @   extensions::utils:151
messageListener @   extensions::messaging:207
target.(anonymous function) @   extensions::SafeBuiltins:19
EventImpl.dispatchToListener    @   extensions::event_bindings:388
target.(anonymous function) @   extensions::SafeBuiltins:19
publicClassPrototype.(anonymous function)   @   extensions::utils:151
EventImpl.dispatch_ @   extensions::event_bindings:372
EventImpl.dispatch  @   extensions::event_bindings:394
target.(anonymous function) @   extensions::SafeBuiltins:19
publicClassPrototype.(anonymous function)   @   extensions::utils:151
dispatchOnMessage   @   extensions::messaging:334

**Comment by abhijitkane** [comment]
@jefferyyuan 403 is the response code. It has to come from the server.

Since you're using the Interceptor to send the request, check the Network tab of the Interceptor - 
1. `chrome://extensions/` 
2. enable `Developer mode`
3. Search for Interceptor, click on Inspect background page.

I've attached a screenshot of the Interceptor successfully sending a POST request.
<img width="1136" alt="screen shot 2016-06-16 at 01 25 40" src="https://cloud.githubusercontent.com/assets/681190/16095213/485654ea-3361-11e6-8027-9086d102771c.png">

**Comment by jefferyyuan** [comment]
Thanks so much for your response. @abhijitkane 

Actually we figured out it's our fault. Recently another developer added a CORS Filter that will check Origin header. But we forgot to update our postman script to include the Origin header.

After add it, the API works now.

Thanks so much and I will close the issue.

**Comment by bhanupinninti** [comment]
How to add Origin header?? @jefferyyuan

**Comment by bhanupinninti** [comment]
We are getting 403 error all of sudden since yesterday..

![image](https://user-images.githubusercontent.com/38074414/40754408-915bbe26-64bc-11e8-8ecd-b9502bdbe67b.png)

**Comment by BernardMarieOnzo** [comment]
using sails.js, check if in your file 'config/security' if your 'csrf' is false

**Comment by saumendrabehura** [comment]
403Forbidden
28 ms
483 B
1234567

**Comment by saumendrabehura** [comment]
403Forbidden
28 ms
483 B
1234567

**Comment by ardhikarn** [comment]
with adonis, change csrf to false in config/shield.js
