### ISSUE TITLE
All postman history has disappeared!

### ISSUE THREAD

**Issue by yarandoo** [a85/POSTMan-Chrome-Extension#2127]
All the valuable postman history has disappeared! This is really annoying as lot of request were quite important and takes time re reading docs to generate the api calls.

I am not the only one affected, as other colleagues have also lost their histories as today.

1. Postman Version:  0.8.4.8
2. App (Chrome app or Mac app): Chrome extension
3. OS details: IOS
4. Is the Interceptor on and enabled in the app: ---
5. Did you encounter this recently, or has this bug always been there: Since today
6. Expected behaviour:
   Expecting to see all my postman history
7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
8. Screenshots (if applicable): Empty history list

Also a co-worker of mine faced the same issue today. Is this due to a postman update?

**Comment by abhijitkane** [comment]
@yarandoo 

Which Postman Extension do you have - https://chrome.google.com/webstore/detail/postman-rest-client-short/mkhojklkhkdaghjjfdnphfphiaiohkef/reviews?hl=en or https://chrome.google.com/webstore/detail/postman-rest-client/fdmmgilgnpjigdojojpjoooidkmcomcm?hl=en?
The first one is an unauthorized clone of Postman, and we cannot provide support for that. If you're on the second one, head to chrome://extensions, enable 'Developer Mode', and click 'Update Extensions now'. This will update you to 0.8.4.17, and you will be able to access your data.

A recent Chrome update broke v0.8.4.8. We'd pushed a patch for this some time back, but this clone app did not.
The new Postman app is available at https://chrome.google.com/webstore/detail/postman-rest-client-packa/fhbjgbiflinjbdggehcddcbncdddomop?hl=en.

**Comment by yarandoo** [comment]
@abhijitkane thanks very helpfull answer. I will switch to the authentic POSTMAN ;) do you know if I can easily migrate the history from one to the other?

**Comment by a85** [comment]
@yarandoo You can take a data dump from the legacy version and import it in the new version: http://www.getpostman.com/docs/migration
