### ISSUE TITLE
Auto completed requests are not affected by undo.

### ISSUE THREAD

**Issue by JordanAlimi** [a85/POSTMan-Chrome-Extension#2131]
Version/App Information:
1. Postman Version: **4.3.2**
2. App (Chrome app or Mac app): **Chrome app with electron**
3. OS details: **Ubuntu 15.04**
4. Is the Interceptor on and enabled in the app: **Disabled**
5. Did you encounter this recently, or has this bug always been there: **Unsure, found recently**
6. Expected behaviour: **Undo to affect auto completed requests**
7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app): **No logs for issue.**
8. Screenshots (if applicable) :

Written request:
![postman1](https://cloud.githubusercontent.com/assets/8739093/16123658/d9f03db4-33b9-11e6-8d6f-1e30929c3cf6.png)

Auto completed:
![postman2](https://cloud.githubusercontent.com/assets/8739093/16123685/f2a11e82-33b9-11e6-8633-547014f609bf.png)

Undone:
![postman3](https://cloud.githubusercontent.com/assets/8739093/16123690/f77f13aa-33b9-11e6-8f60-17e3e4c52780.png)

Steps to reproduce the problem:
1. Manually type in a request.
2. Use a suggested auto-complete.
3. Undo with ctrl-z which only reverts what you typed, not the auto-completed text.

**Comment by a85** [comment]
Verified this is still happening in 4.7

**Comment by numaanashraf** [comment]
@JordanAlimi This is fixed in v4.10.5+. Please verify and let us know.
