### ISSUE TITLE
Cannot enable/disable query parameters in Key Value Editor

### ISSUE THREAD

**Issue by ohavryl** [a85/POSTMan-Chrome-Extension#2132]
According to the documentation https://www.getpostman.com/docs/keyvalue_editor I should be able to enable/disable or comment/uncomment query parameters in Key Value Editor.

**Comment by abhijitkane** [comment]
@ohavryl This is a limitation due to the way the URL is stored. We'll soon be introducing a new underlying data format which should allow this.

Thanks for pointing out the discrepancy in the docs - we'll fix this today.
