### ISSUE TITLE
"No module named libmproxy" when trying to start pmproxy

### ISSUE THREAD

**Issue by ubuntudroid** [a85/POSTMan-Chrome-Extension#2133]
1. Postman Version: 4.3.2
2. App (Chrome app or Mac app): Packaged app
3. OS details: OSX 10.11.5, Chrome 51.0.2704.79 (actually it's vivaldi, but that shouldn't make a difference for the issue at hand)
4. Is the Interceptor on and enabled in the app: yes
5. Did you encounter this recently, or has this bug always been there: just installed the app for the first time, so can't say
6. Expected behaviour: pmproxy should start without an error
7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app): log output of pmproxy should suffice as this doesn't seam to be a Postman app problem, but rather a proxy problem

I've just installed the postman packaged app and now I'm trying to get pmproxy up and running. I followed the instructions over [here](https://www.getpostman.com/docs/capture).

I'm stuck at the `pmproxy save --tcp_connection true` call. It returns with

```
File "/usr/local/bin/pmproxy", line 7, in <module>
    from postmanproxy.main import main
  File "/usr/local/lib/python2.7/site-packages/postmanproxy/main.py", line 2, in <module>
    from postman.collection_creator_proxy import CollectionCreatorProxy
  File "/usr/local/lib/python2.7/site-packages/postmanproxy/postman/collection_creator_proxy.py", line 1, in <module>
    from libmproxy import controller, proxy
ImportError: No module named libmproxy
```

Tried to install mitmproxy, but that didn't help either.

**Comment by ubuntudroid** [comment]
Okay, this can be fixed by installing mitmproxy 0.16 as the current version 0.17 doesn't seem to incorporate libmproxy any more.

```
pip install mitmproxy==0.16
```

**Comment by ubuntudroid** [comment]
The proxy somehow starts now, but right after it has started I receive the following error.

```
File "/usr/local/bin/pmproxy", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/postmanproxy/main.py", line 91, in main
    start_creator_proxy(args)
  File "/usr/local/lib/python2.7/site-packages/postmanproxy/main.py", line 45, in start_creator_proxy
    cacert = os.path.expanduser("~/.mitmproxy/mitmproxy-ca.pem")
TypeError: __init__() got an unexpected keyword argument 'cacert'
```

**Comment by ubuntudroid** [comment]
I'm now using the proxy fork from [noodleOne](https://github.com/noodleOne/PostmanProxy) which appears to work just fine. But I didn't manage to find the proxy settings menu in the app. Returning to Charles for the time being and will check this out again in half a year.

**Comment by a85** [comment]
@ubuntudroid Looking into this. The Postman Mac app itself acts as a proxy and there is no need to use pmproxy. We are bringing that to Windows and Linux too.

**Comment by ubuntudroid** [comment]
@a85 ah, so on which port do I have to connect to proxy the data from my mobile phone through the app?

**Comment by a85** [comment]
The default is 5555. https://www.dropbox.com/s/m66sbi2t4xptpof/Screenshot%202016-06-19%2015.47.17.png?dl=0

**Comment by ubuntudroid** [comment]
So probably I'm just not clever enough to find the button to open this modal dialog. oO Where do I exactly have to click on to pull this up? Feeling really stupid now. :P

**Comment by ubuntudroid** [comment]
Argh, I had the packaged Chrome app installed, not the Mac app. Sorry for the confusion. 🐼 🌴

**Comment by ubuntudroid** [comment]
Monitoring SSL requests from e.g. an Android app isn't supported by the Mac App, is it? They are not appearing in the history.

**Comment by a85** [comment]
I'd let @abhijitkane answer that. I do think we added SSL support but not sure if it can be done through Android.

**Comment by abhijitkane** [comment]
@ubuntudroid It can support SSL to a certain extent. If the server has HSTS enabled, then the proxy will be unable to eavesdrop correctly. Are you able to browse https sites through your browser with the proxy enabled?
