### ISSUE TITLE
UI issue : URL params not fully removed from URL when deleted

### ISSUE THREAD

**Issue by niminmp** [a85/POSTMan-Chrome-Extension#2136]
Postman Version : 4.3.2
App : Chrome App
OS : Windows 7
Interceptor is ON
Encountered this issue recently when starting to use the feature.

Issue details : After typing in a URL param in 'params' key field, removing the value from key is not completely removing the param from the address field. The first letter of the param still exist.

![image](https://cloud.githubusercontent.com/assets/10994847/16159767/9624169e-3492-11e6-841b-2aa69584c025.png)

Removing the param : 

![image](https://cloud.githubusercontent.com/assets/10994847/16159793/b02273c4-3492-11e6-8ca8-6dbdcebb0d6b.png)

**Comment by abhijitkane** [comment]
@niminmp Thanks for reporting this. We'll aim to push a fix for this ASAP.

**Comment by vegetableman** [comment]
@niminmp This issue has been fixed for a while. Feel free to reopen this.
