### ISSUE TITLE
Screen change when a Picture has been dropped on 

### ISSUE THREAD

**Issue by KaMagno** [a85/POSTMan-Chrome-Extension#2137]
1. Postman Version: 4.3.2
2. App (Chrome app or Mac app): Mac app.
3. OS details: OS X 15.0.0 / x64.
4. Is the Interceptor on and enabled in the app: - 
5. Did you encounter this recently, or has this bug always been there: Recently.
6. Expected behaviour: It just should not happen.
7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app): I cannot get the logs when the issue happen
8. Screenshots (if applicable)

Get a picture and drop it on Postman screen,  the screen change to the Picture.

**Comment by abhijitkane** [comment]
@KaMagno Thanks for reporting this. This has been fixed in the latest version (4.4.2) of the app. To update - https://www.getpostman.com/docs/updating
