### ISSUE TITLE
Collection export / import roundtrip loses the description for each of the methods.

### ISSUE THREAD

**Issue by rahulj123atwork** [a85/POSTMan-Chrome-Extension#2138]
1. Postman Version: 4.3.2
2. App (Chrome app or Mac app): Chrome 51.0.2704.84
3. OS details: OS X / x86-64 - 10.11.15
4. Is the Interceptor on and enabled in the app: Yes
5. Did you encounter this recently, or has this bug always been there: Noticed it today 6/17/2016
6. Expected behaviour: Description text for each api method should not be lost in the round-trip.
7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app): Not available.
8. Screenshots (if applicable)

Steps to recreate:
1. Create a collection in which the api methods have a description.
![image](https://cloud.githubusercontent.com/assets/4239234/16163335/827491c8-348d-11e6-9838-fdcc942dfc82.png)
1. Export a Postman collection in "Collection v2" format.
   ![image](https://cloud.githubusercontent.com/assets/4239234/16163344/90023fe8-348d-11e6-99f2-a0b4c4415a7d.png)
2. Then import that .json file and create a 'copy' collection.
3. Now when I access the api methods in the 'copy' collection, I don't see the description text in Postman.

**Comment by abhijitkane** [comment]
@rahulj123atwork Thanks for reporting this. We've fixed this in our internal build, and will be pushing out a fix this week.

**Comment by abhijitkane** [comment]
@rahulj123atwork Can you confirm this fixed in v4.3.3 of the app?

**Comment by gthieme** [comment]
Yep, its fixed after an update.
