### ISSUE TITLE
Cannot manually sort requests or headers

### ISSUE THREAD

**Issue by musiKk** [a85/POSTMan-Chrome-Extension#2139]
1. Postman Version: 4.3.2
2. App (Chrome app or Mac app): Chrome 51.0.2704.103 (64-bit)
3. OS details: Ubuntu Linux 14.04
4. Is the Interceptor on and enabled in the app: No
5. Did you encounter this recently, or has this bug always been there: Always
6. Expected behaviour: Being able to sort headers and requests.
7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):

This appears the moment I initiate the drag.

```
Uncaught Error Uncaught Invariant Violation: Cannot call beginDrag while dragging. chrome-extension://fhbjgbiflinjbdggehcddcbncdddomop/js/requester.js 50048 6 Error: Cannot call beginDrag while dragging.(…)
(anonymous function) @ requester.js:242181

Uncaught Invariant Violation: Cannot call beginDrag while dragging.
invariant @ requester.js:50041
beginDrag @ requester.js:49792
(anonymous function) @ requester.js:49129
handleTopDragStart @ requester.js:208720

```

Steps to reproduce the problem:

Try to manually sort a request or header. The visual feedback provided is as expected, i.e., there is a "shadow version" of the element being dragged under the mouse cursor but dropping does nothing.

**Comment by vegetableman** [comment]
@musiKk Thank you for reporting. The issue has been fixed. Will be part of the next release.

**Comment by musiKk** [comment]
I can confirm it's working now. Thanks!
