### ISSUE TITLE
I don't see interceptor icon in Postman

### ISSUE THREAD

**Issue by Sshapo2003** [a85/POSTMan-Chrome-Extension#2140]

**Comment by Sshapo2003** [comment]
Add Interceptor to Chrome.
Enabled it.
Restarted Chrome and Postman. No Interceptor icon
http://screencast.com/t/bdpZMkGaToia

Postman version
Version 4.3.2 (4.3.2)

**Comment by abhijitkane** [comment]
@Sshapo2003 The screenshot shows the Mac app, not the Chrome app. You can get the Chrome app from https://chrome.google.com/webstore/detail/postman-rest-client-packa/fhbjgbiflinjbdggehcddcbncdddomop?hl=en.

**Comment by Tzvika-m** [comment]
@abhijitkane 
This feature doesn't exist in the mac app?
As I understand it the chrome app is deprecated, no?

**Comment by nlaffey** [comment]
@abhijitkane echoing what Tzvika-m said... I really want to use Postman but the communication around what to use and how to get interceptor working has been really confusing/frustrating for the past few years.

**Comment by Pictor13** [comment]
[Documentation for mac app v6.x](https://www.getpostman.com/docs/v6/postman/sending_api_requests/interceptor_extension) says to just install Interceptor and enable it in the app (as it used to be into Chrome App).

But no icon is present in the Mac app.

This is frustrating...
Anybody that got it work? Or is the documentation just incorrect?

**Comment by ccrisologotiqk** [comment]
I made it work, it only works with chrome app not for native/desktop app. So you have to open it thru Postman Interceptor extension from your chrome then launch the Postman. I just figured out the postman from chrome is different from desktop version.

**Comment by Pictor13** [comment]
Yes, but Chrome Apps are deprecated and will be removed. So we need a way to make Interceptor work with the native app.
Interceptor is the reason why I use Postman rather than other tools; when Chrome apps won't work anymore I will have to leave Postman too.
