### ISSUE TITLE
Add copy to clipboard functionality in "Pretty" response mode

### ISSUE THREAD

**Issue by Ajeey** [a85/POSTMan-Chrome-Extension#2141]
Allow user to copy while in the "Pretty" response mode.

App Details - 

4.3.3
OS X / x86-64
Chrome 51.0.2704.84

Screen shot - 
<img width="1065" alt="screen shot 2016-06-21 at 11 44 10 am" src="https://cloud.githubusercontent.com/assets/1799117/16219669/8c0f2106-37a5-11e6-9f60-3aac4e10b472.png">

**Comment by abhijitkane** [comment]
@Ajeey You need to select text to be able to copy it. We also have a separate copy button that lets you copy the whole response.
<img width="225" alt="screen shot 2016-06-21 at 13 23 48" src="https://cloud.githubusercontent.com/assets/681190/16222034/a1fefc9e-37b3-11e6-946e-d40a17be11fc.png">
<img width="334" alt="screen shot 2016-06-21 at 13 24 46" src="https://cloud.githubusercontent.com/assets/681190/16222050/c1401444-37b3-11e6-8d14-ec8f3e9dfb3d.png">

**Comment by Ajeey** [comment]
@abhijitkane Since it is an href, it should allow me to copy without selecting.
