### ISSUE TITLE
Postman does not send un-named body parameters on POST

### ISSUE THREAD

**Issue by kdprince** [a85/POSTMan-Chrome-Extension#2144]
1. Postman Version: 4.3.3
2. App (Chrome app or Mac app): Chrome App
3. OS details: window 7
4. Is the Interceptor on and enabled in the app: No
5. Did you encounter this recently, or has this bug always been there: Unknown
6. Expected behaviour: Un-named body parameters should be sent as part of the POST request
7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
8. Screenshots (if applicable)

1)  Set the following Headers:
Content-Type  application/x-www-form-urlencoded
2) Click on 'Body' tab
3) select the x-www-form-urlencoded parameter type
4) Create a key that is un-named and a supply the value 'dummy'
5) Click generate code and notice the screenshot has the appropriate body message of the following:
POST /fubot/events/ack HTTP/1.1
Host: localhost
Content-Type: application/x-www-form-urlencoded

=dummy

6) Launch 'Fiddler' or other capture tool to capture URL requests
7) Send the request
8) Examine the POST request and notice that the un-named Body parameter is not sent with the request.

Notes:
(Workaround) You can copy the body parameter, switch to "raw" mode and post with the un-named parameter.  
C# requires that if you have a single body post parameter that the parameter must be un-named or model binding will not work.
The behavior of postman is inconsistent.  The 'Generate Code' button clearly generates what I expect the request to be, but that request differs from what is actually sent.

Setting Content-Length had no effect one way or the other.

![image](https://cloud.githubusercontent.com/assets/20074096/16243716/3a00cb80-37be-11e6-8c0e-a8db1edb1f28.png)

![image](https://cloud.githubusercontent.com/assets/20074096/16243743/4ebabac2-37be-11e6-850e-80e5925232cb.png)

![image](https://cloud.githubusercontent.com/assets/20074096/16243779/7e848148-37be-11e6-9c7e-bd90753344ca.png)

**Comment by vegetableman** [comment]
@kdprince This has been fixed in our internal build. Will be part of the next release.

**Comment by vegetableman** [comment]
@kdprince The issue has been fixed in the recent release 4.8.3 . Closing this. Feel free to reopen if the issue still exists ^_^.
