### ISSUE TITLE
Setting empty headers

### ISSUE THREAD

**Issue by caioiglesias** [a85/POSTMan-Chrome-Extension#2145]
I intercepted an HTTP GET request with [Charles](http://www.charlesproxy.com), then I tried to recreate it on the Postman app, but it didn't work.

I found out that one of the GET headers should be empty, but I wasn't able to set it to empty on postman. On [libcurl](https://curl.haxx.se/libcurl/c/httpcustomheader.html) you just add a semi-colon to the header and it will expand to empty.

```
/* Add a header with "blank" contents to the right of the colon. Note that
   we're then using a semicolon in the string we pass to curl! */ 
chunk = curl_slist_append(chunk, "X-silly-header;");
```

I used wireshark to investigate what postman was sending out (I later found out I could have used chrome dev tools :expressionless:) and it was dropping the header instead of setting it to empty. I couldn't find a way to actually do it on Postman. I'm currently "generating code" as CURL and manually replacing the colon with a semicolon to run it on Mac OS' terminal.
1. Postman Version: Version 4.3.2 (4.3.2)
2. App (Chrome app or Mac app): Mac APP
3. OS details: OSX 10.10.5
4. Is the Interceptor on and enabled in the app: Yes
5. Did you encounter this recently, or has this bug always been there: Always
6. Expected behaviour: Send empty header instead of dropping it.
7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
8. Screenshots (if applicable)

**Comment by Joyce-Stack** [comment]
+1

**Comment by cars10** [comment]
+1

**Comment by SamvelRaja** [comment]
@madebysid - check if this issue is still there in latest native app

**Comment by sdnts** [comment]
Hey @caioiglesias @MendeleyStack @cars10 Can you guys try updating to the latest version (4.7) and verify if fixed?
Closing for now, feel free to reopen if this still persists.

**Comment by caioiglesias** [comment]
Worked for me on v.4.7.0
