### ISSUE TITLE
 The pop-up menu can not scroll up and down

### ISSUE THREAD

**Issue by pipiliang** [a85/POSTMan-Chrome-Extension#2146]
Postman Version: 4.3.2
App (Chrome app or Mac app):  Chrome app , Chrome 50.0.2661.87 m
OS details: Windows 7
Is the Interceptor on and enabled in the app:
Did you encounter this recently, or has this bug always been there: Always
Details: After typing in "xml" in 'Headers' value field, the popup menu can't scroll up and down when hit `↑` or `↓`.
![issue](https://cloud.githubusercontent.com/assets/15980794/16289323/c11319b6-3926-11e6-9753-1b4392839093.png)

**Comment by a85** [comment]
Seems to be working for me in the latest version. (4.7)
