### ISSUE TITLE
Feature Request : Create a default option in settings to export collections to V1 or V2

### ISSUE THREAD

**Issue by dhoyt** [a85/POSTMan-Chrome-Extension#2148]
Having to take an action each time to export all my collections to V2 is a pain. I would like to make my choice in settings once.

Thanks ... RJ

**Comment by abhijitkane** [comment]
@dhoyt In the next release, we'll preserve your choice. Selecting v2 once will cause v2 to be selected the next time you open the modal.

**Comment by abhijitkane** [comment]
@dhoyt This has been fixed in v4.4.2 of the app (Chrome only). Can you update (https://www.getpostman.com/docs/updating) and check?
