### ISSUE TITLE
History is not working in new version

### ISSUE THREAD

**Issue by danprado** [a85/POSTMan-Chrome-Extension#2149]
Hi.
I don't know if I'm using it wrong but, it looks like the history is not working in the new version.
Whenever I make a request it doesn't append the request to the top of the history. It just replace the top record instead. 
Is this a bug or am I missing something?
1. Postman Version: 4.4.0
2. App (Chrome app or Mac app): Chrome.
3. OS details: win / x86-32
4. Did you encounter this recently, or has this bug always been there: With the new update.
5. Expected behaviour: The history should behave like a history. Appending each request made.

**Comment by abhijitkane** [comment]
@DanPrado This is a bug that was introduced in the latest version. We've fixed this internally, and will be pushing a fix for this soon.

**Comment by danprado** [comment]
Cool! Thanks @abhijitkane ! =)

**Comment by HenrikHL** [comment]
It seems to be a problem with 4.4.1 as well:

4.4.1
win / x86-32
Chrome 51.0.2704.84

**Comment by bcardi** [comment]
Yes, i am experiencing this same issue with 4.4.1
4.4.1
win / x86-32
Chrome 51.0.2704.103

**Comment by abhijitkane** [comment]
This was reported in 4.4.0 and 4.4.1. The fix will go out in the next version.

**Comment by HenrikHL** [comment]
@abhijitkane what is the timeframe for next version? Is it within days or weeks?

This case (together with case [2153](https://github.com/postmanlabs/postman-app-support/issues/2153)) is really a show-stopper for me. It is too cumbersome to use POSTman when these things don't work :-(

**Comment by abhijitkane** [comment]
@HenrikHL At least a week. For now, you can delete your old history items to fix this.
If you have Sync enabled, signing out and signing back in will also fix this.
