### ISSUE TITLE
Feature Request: Multiple 'environments'

### ISSUE THREAD

**Issue by Storm-BE** [a85/POSTMan-Chrome-Extension#215]
First of all, thank you for this great tool!

I use it to test a WCF service. This service is running on multiple urls:
- Live server
- Testing server
- Local testing 

The environment selection menu is perfect for this. However, I also have another variable: the login. I have multiple users that can login to (any of) the webservices, with a username and password. At this moment I can only put these variables in the global environment.

It would be awesome if I could just select "Testing server", and choose "UserA" in another dropdownlist, to test UserA on the Test environment, for example.

This functionality can be achieved by adding 'environment groups', and allowing the user to select 1 environment out of each environment group.

I apologise if this idea is a bit too far-fetched, but I think it could be useful for many :)

Thanks for reading!

Storm-BE

**Comment by matanshukry** [comment]
It seems related, so I'll just continue this open (would love if anyone can reopen this).

I personally has a need for using multiple environment simultaneously. I'm guessing multiple dropdowns would be impossible (assuming you don't want to hard limit the number of multiple environments simultaneously), but a dropdown with checkboxes IMO would be nice.

My specific use case is I'm using different environments for multiple projects, where the projects work together. so I can use projectA-envA with projectB-envB, but I don't have anyway of doing that in postman.

Currently, I simply have an environment for projectA, and everything else I'm changing manually :\
