### ISSUE TITLE
Feature Request: Postman Cloud-Monitor - Send email on collection failure

### ISSUE THREAD

**Issue by brandonmarino** [a85/POSTMan-Chrome-Extension#2150]
Having the option to email a specific person if a test collection run fails in the cloud-monitor would a be great addition to the service.

**Comment by dhoyt** [comment]
That's funny ... I am getting emails from the Monitor and would like to know how to shut them off.

**Comment by brandonmarino** [comment]
Oh, its being sent to my junk folder. /facepalm.

Hey dhoyt, I'd probably just make a rule in whatever service I was using to send the spam from the monitor directly to your trash or your junk folder. Good-luck!
