### ISSUE TITLE
{{$timestamp}} global variable is not being replaced by its value

### ISSUE THREAD

**Issue by afalvella** [a85/POSTMan-Chrome-Extension#2151]
1. Postman Version: 4.4.1
2. App (Chrome app or Mac app): Chrome app
3. OS details: ubuntu linux 15.10
4. Is the Interceptor on and enabled in the app: no, it's disabled
5. Did you encounter this recently, or has this bug always been there: recently
6. Expected behaviour: the timestamp variable should be replaced to a value instead of the same string '{{$timestamp}}'
7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app): -
8. Screenshots (if applicable): -

When using the postman runner the {{$timestamp}} global variable works fine but using the monitor the variable are not being replaced, we are receiving this: 
email: 'test_{{$timestamp}}@gmail.com'
when we should be receiving something like this: 
email: 'test_1467057812@gmail.com'

**Comment by abhijitkane** [comment]
@afalvella Can you contact us at help@getpostman.com with your username and the monitor/collection for which you're seeing this?

**Comment by shamasis** [comment]
This issue should be resolved with our latest update to the monitoring system. Feel free to reopen if that is not the case.
