### ISSUE TITLE
Cannot enable interceptor.

### ISSUE THREAD

**Issue by sumanmitra** [a85/POSTMan-Chrome-Extension#2152]
1. Postman Version: 4.4.1
2. App (Chrome app or Mac app): Chrome
3. OS details: Windows 8.1
4. Is the Interceptor on and enabled in the app: No
5. Did you encounter this recently, or has this bug always been there: First time using. So not sure about previous behaviour.
6. Expected behaviour: I should able to enable interceptor.. 
   ![postman-interceptor](https://cloud.githubusercontent.com/assets/14543160/16447375/ed0cf824-3e09-11e6-8f19-f1a1dcacb3c5.jpg)
7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
8. Screenshots (if applicable) Given.

As I click to enable it, a popup is coming "Install Postman Interceptor". As I click install button , it is taking me to following url.
https://chrome.google.com/webstore/detail/postman-interceptor/aicmkgpgakddgnaphhhpliifpcfhicfo
I clicked on "Available on chrome" button. Chrome got installed. But I found it is not working after installation.

Just fyi... Chrome is not my default browser. IE is my default browser.

Thanks,
Suman

**Comment by abhijitkane** [comment]
@sumanmitra Can you open Chrome, head to `chrome://extensions`, and see if the Interceptor is listed there?

**Comment by sumanmitra** [comment]
What I see below.

```
On Wednesday, June 29, 2016 3:12 PM, Abhijit Kane <notifications@github.com> wrote:
```

 @sumanmitra Can you open Chrome, head to chrome://extensions, and see if the Interceptor is listed there?—

**Comment by abhijitkane** [comment]
@sumanmitra The screenshot wasn't uploaded correctly.

**Comment by sumanmitra** [comment]
![chromeextensions](https://cloud.githubusercontent.com/assets/14543160/16450628/ae90f66a-3e1b-11e6-9d3a-0a9224b7c56e.jpg)

**Comment by abhijitkane** [comment]
You also need to install the Interceptor. Head to https://chrome.google.com/webstore/detail/postman-interceptor/aicmkgpgakddgnaphhhpliifpcfhicfo?hl=en in chrome, and click 'Add to Chrome'

**Comment by sumanmitra** [comment]
I did it before in IE but not from Chrome itself. Its working now. Thanks,
