### ISSUE TITLE
Very slow response time when entering data in an empty field

### ISSUE THREAD

**Issue by HenrikHL** [a85/POSTMan-Chrome-Extension#2153]
1. Postman Version: **4.4.1**
2. App (Chrome app or Mac app): **Chrome**
3. OS details: **Win10**
4. Is the Interceptor on and enabled in the app: **No (not installed)**
5. Did you encounter this recently, or has this bug always been there: **recently.. I haven't been using POSTman for the last 2 months - before that it worked fine**
6. Expected behaviour:**when I click in an empty field (eg a new header field) I would expect to be able to enter data imediately. It seems like it is connecting to some external service to validate what I write or make some kind of look-ahead suggestion...?**
7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
8. Screenshots (if applicable)
   ![image](https://cloud.githubusercontent.com/assets/3489388/16447927/24d0caee-3def-11e6-99b2-d7c78e26cf1b.png)

Click on any empty field and start writing. A delay of 3-8 seconds occurs before the text entered in the field becomes visible in the field. Modifying a field that contains a lot of text works fine.
My guess is that a server is being contacted - this process is very slow. Maybe look-ahead typing has been introduced...? If so - where do I turn it off!

**Comment by HenrikHL** [comment]
Here is a [link to a video](https://www.dropbox.com/s/oboa1z1u35fq038/2016-06-29%2011.08.02.mp4?dl=0) showing the problem

**Comment by abhijitkane** [comment]
@HenrikHL This could be due to a large number of history requests. 

Can you also check the console for the value of these properties - pm.urlCache.getUrls().length and pm.history.length?

These are all the URLs that are offered as autocomplete suggestions.

**Comment by abhijitkane** [comment]
@HenrikHL Before you delete history, can you also check the console for the value of these properties - `pm.urlCache.getUrls().length` and `pm.history.length`?

These are all the URLs that are offered as autocomplete suggestions.

**Comment by aguilera51284** [comment]
+1

**Comment by mrgyf1** [comment]
+1 What can i do to fix it?

**Comment by ferasodh** [comment]
+1

**Comment by byronsanchez** [comment]
same

**Comment by numaanashraf** [comment]
@byronsanchez , @aguilera51284 @mrgyf1 Are you still facing this issue in the latest version of the app (`v4.10.7`)?

**Comment by byronsanchez** [comment]
@numaanashraf - just figured it out. For me it was because of a lot of history requests like @abhijitkane said. Cleared the history and it is back to normal. Yea, it was v4.10.7. But it's good now.

**Comment by voeurnchy** [comment]
+1
