### ISSUE TITLE
Updated Postman Cannot Override User Agent

### ISSUE THREAD

**Issue by tomrossi7** [a85/POSTMan-Chrome-Extension#2154]
Before upgrading Postman on my Mac, I had requests that worked fine with the User-Agent being set in the Headers section. After upgrading, I can no longer set the User Agent because it gives an error Restricted HTTP Headers. I can't find anywhere else within the app that I can set the User Agent?

Version/App Information:
-->
1. Postman Version:
   4.4.1 
2. App (Chrome app or Mac app):
   Mac App
3. OS details:
   OSX El Capitan
4. Is the Interceptor on and enabled in the app:
   Dont know what this is
5. Did you encounter this recently, or has this bug always been there:
   After running software update
6. Expected behaviour:
   Should be able to set the user-agent

**Comment by abhijitkane** [comment]
@tomrossi7 Did you upgrade from the Chrome app to the Mac app, or just to a newer version of the Mac app?
In any case, you can download Postman Canary via https://www.getpostman.com/app/postman-osx-canary. This includes a new runtime which lets you send all restricted headers, including User-Agent.

**Comment by tomrossi7** [comment]
Thanks @abhijitkane! I was using the Mac app, but just installed Canary and it works like a charm...
