### ISSUE TITLE
Changing theme makes contents of response body panel 2 lines tall

### ISSUE THREAD

**Issue by dangerman** [a85/POSTMan-Chrome-Extension#2156]
Found in:
Postman Version: 4.4.1, Chrome 51
Windows 10
Interceptor not enabled

**Steps to reproduce**
- Make a successful request
  - Response body panel should be populated
- Go to Settings and change Theme

**Expected**
- Response body panel looks the same as before, but with updated theme.

**Actual**
- The text within response body is only 2 lines tall, but the panel itself remains the same size.
- Can scroll through it using the mousewheel, but only 2 lines are visible at a time.
- There is no scrollbar for the body panel.
- Changing body rendering mode from the dropdown e.g. JSON/Text/XML fixes the panel.

**Comment by abhijitkane** [comment]
@dangerman Can you confirm this fixed in the latest version of the app (4.4.2)?
