### ISSUE TITLE
Response Pretty view rounding non-zero numbers to zero

### ISSUE THREAD

**Issue by tomridl** [a85/POSTMan-Chrome-Extension#2157]
If a number is less than 0.0001, it is rounded down to 0.0000 in the pretty view. For example: 

Raw:

```
{"success":true,"message":"","result":{"Bid":0.00000051,"Ask":0.00000052,"Last":0.00000051}}
```

Pretty:

``` json
{
  "success": true,
  "message": "",
  "result": {
    "Bid": 0.0000,
    "Ask": 0.0000,
    "Last": 0.0000
  }
}
```

Version/App Information:
1. Postman Version: Version 4.4.1
2. App (Chrome app or Mac app): Mac app
3. OS details: OSX 10.11.5

**Comment by a85** [comment]
@abhijitkane Still valid?
