### ISSUE TITLE
OAuth 1.0 not supported by NetSuite RESTlet 

### ISSUE THREAD

**Issue by ShawnTalbert** [a85/POSTMan-Chrome-Extension#2158]
1. Postman Version:
   4.4.1
2. App (Chrome app or Mac app):

chrome app
1. OS details:

Linux  Mint 17
1. Is the Interceptor on and enabled in the app:

Enabled: no
1. Did you encounter this recently, or has this bug always been there:

I think it's always been there
1. Expected behaviour:

Successful authentication with OAuth 1.0 to a NetSuite RESTlet
1. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):

Nothing in the console.
1. Screenshots (if applicable)

Steps to reproduce the problem:
I suspect this is specifically an issue with the signature generation, but postman nor NetSuite exposes details of the error.

If you need an actual netsuite endpoint to test against let me know and I'll go about trying to come up with one for you.

**Comment by abhijitkane** [comment]
@ShawnTalbert Sure, you can send the credentials to help@getpostman.com

**Comment by ShawnTalbert** [comment]
Still working on getting this for a 'real' account...

**Comment by abhijitkane** [comment]
@ShawnTalbert Closing this for now. Feel free to re-open if you still face the issue.

**Comment by chris-bleile** [comment]
This is a problem for us as well.  We have been asked to do this for a couple of clients so they can test our work before we go live.
