### ISSUE TITLE
tagging for collections and environments

### ISSUE THREAD

**Issue by jannemann** [a85/POSTMan-Chrome-Extension#2159]
while using the API to download collections and environments it came to my mind that it would be helpful to select a bunch of collections/environments by some tag.

i don't know what the best implementation look like, but i would consider key/value tags.

**Comment by mblandfo** [comment]
Looks like duplicate of https://github.com/postmanlabs/postman-app-support/issues/929

**Comment by jannemann** [comment]
@mblandfo I think you are right
