### ISSUE TITLE
show uid in app ui

### ISSUE THREAD

**Issue by jannemann** [a85/POSTMan-Chrome-Extension#2160]
it would be helpful to optionally see uid for collections and environments in the app

**Comment by jsooter** [comment]
I'd like to add that showing the UID in the app UI would help when working with the Postman API.  When you have two similarly named collections in an API result set it can be difficult to tell which is which. 

There is no requirement that collection names be unique. If the UID is visible in the UI, it becomes very easy to compare by UID, which is always unique.

**Comment by mzroth** [comment]
A visible location for the UIDs in the UI would help when trying to use the collections in CICD pipelines as well. That way we could directly access the collection from the API without having to search and sort each time the CICD is run. It would also help prevent breaking the pipelines if someone creates a non-unique collection name.
