### ISSUE TITLE
Postman Collection -- Cannot pull the requests up/down inside the folder

### ISSUE THREAD

**Issue by Yabko** [a85/POSTMan-Chrome-Extension#2161]
Hello there,

**Version/App Information:**
1. Postman Version: 4.4.1
2. App (Chrome app or Mac app): Chrome 51.0.2704.103
3. OS details: Win 10 / x64
4. Is the Interceptor on and enabled in the app: OFF
5. Did you encounter this recently, or has this bug always been there: It's a new bug, haven't seen it before.

**Steps to reproduce the problem:**
1. Start Postman;
2. Go to Collections;
3. Have a Collection with a Folder;
4. Add several requests to the folder;
5. Try to rearrange the requests by pulling them up or down => it's impossible, the requests cannot be rearranged.
I believe it was working a couple of days before.

![postman_rearrange_broken](https://cloud.githubusercontent.com/assets/9423162/16560827/419d2024-41fe-11e6-9145-8c7ce1ce8fe4.png)

**Comment by abhijitkane** [comment]
@Yabko Is the collection shared by someone else? If they changed the permissions to read-only, you won't be able to edit the collection or its requests.

**Comment by Yabko** [comment]
I'm the collection owner, so i'm the only one with the permissions to edit the collection.

**Comment by abhijitkane** [comment]
@Yabko Can you contact us at help@getpostman.com with your username/email?
Also, are there any errors in the console - https://www.getpostman.com/docs/errors?

**Comment by Yabko** [comment]
Sorry, but yesterday I played around with enabling/disabling sharing the Collection with the team and it fixed the problem.
So, i doubt if now my console can show anything useful.
It might be just a glitch, or might be a bug, but now I can't reproduce it either.
