### ISSUE TITLE
Postman sync is restoring already deleted requests

### ISSUE THREAD

**Issue by emmanuel-umana** [a85/POSTMan-Chrome-Extension#2162]
Version/App Information:
1. Postman Version: 4.4.1
2. App (Chrome app or Mac app): Windows 10 and Macs
3. OS details: 
4. Is the Interceptor on and enabled in the app: Off
5. Did you encounter this recently, or has this bug always been there: not always there, it seems is affecting from some months ago
6. Expected behaviour: Removed requests are not restored during Sync. Currently for some reason the requests removed by one member of the team are restored at some point, our guess is that is happening when another user when and old version of the collection opens the postman (automatic sync runs on loading)
7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
8. Screenshots: http://screencast.com/t/yFzXlqhlbm

Steps to reproduce the problem:

Not sure exactly if is happening all the time, but this is our guess.

1) Have a collection shared 5 users with a good amount of requests and folders. (that's our scenario)
2) Remove a request from one of the users postman.
3) Open postman with a different users with the old collection version.
4) At this point, the collection is sync and deleted requests are restored from the shared collection instead of removed from the old user collection.

Some guidelines: 

In the screenshot you can see 2 collections, AristaMD is the shared one and "AristaMD Copy" is the last version we exported of that one. We removed from the shared collection the folder "PILOT-781 eConsult follow up", but for some reason, the folder is there again :-(

Could you guys help us to review this issue? we are getting errors caused by having requested that were originally deleted.

Thanks!

**Comment by emmanuel-umana** [comment]
One more thing, looking at activity feed UI found this actions the user never did, probably it happened during app loading sync.

June 22 
dobando modified the request PILOT-804: Search user by Role in the collection AristaMD 10:32 AM dobando added the request PILOT-804: Search user by Role to the collection AristaMD 10:32 AM
dobando created the folder PILOT-804 eConsult Panelist Set to Saved in the collection AristaMD 10:32 AM
dobando created the folder PILOT-781 eConsult follow up in the collection AristaMD 10:32 AM
dobando added a request to the collection AristaMD 10:32 AM
dobando added the request PILOT-905: Unschedule and complete the referral to the collection AristaMD 10:32 AM

**Comment by abhijitkane** [comment]
@emmanuel-umana Are all members of the team on v4.4.1 of the app? Also, can you contact us at help@getpostman.com with your username, and the owner of the 'AristaMD' collection? This will help us trace exactly what happened to the deleted folder.

**Comment by emmanuel-umana** [comment]
Yes, all of we are using that same version, I just check with each of them.

4.4.1 / win / x86-32 / Chrome 51.0.2704.103
4.4.1 / OS X / x86-64 / Chrome 51.0.2704.103
4.4.1 / win / x86-64 / Chrome 52.0.2743.60
4.4.1 / win / x86-32 / Chrome 51.0.2704.103
4.4.1 / OS X / x86-64 / Chrome 51.0.2704.103
4.4.1 / OS X / x86-64 / Chrome 51.0.2704.103
4.4.1 / OS X / x86-64 / Chrome 51.0.2704.103
4.4.1 / win / x86-32 / Chrome 51.0.2704.103

I will send you the other info through the help email.
Thanks

**Comment by emmanuel-umana** [comment]
Hi abhijitkane,

This is the information requested about this issue:

1) All the team is using the same version, I just check with each of them.

Emmanuel Umaña: 4.4.1 / win / x86-32 / Chrome 51.0.2704.103
Elberth Quesada Porras: 4.4.1 / OS X / x86-64 / Chrome 51.0.2704.103
Darryl Kuhn: 4.4.1 / win / x86-64 / Chrome 52.0.2743.60
Karolina Muñoz: 4.4.1 / win / x86-32 / Chrome 51.0.2704.103
Jose Daniel Beita: 4.4.1 / OS X / x86-64 / Chrome 51.0.2704.103
Luis Diego Cordero: 4.4.1 / OS X / x86-64 / Chrome 51.0.2704.103
Travis Fawcett: 4.4.1 / OS X / x86-64 / Chrome 51.0.2704.103
Daniel Obando Fuentes: 4.4.1 / win / x86-32 / Chrome 51.0.2704.103

2)  My Username: emaurojas125 / eumana@growthaccelerationpartners.com
Email of the collection owner: Darryl Kuhn darryl@aristamd.com

Let me know if you need some extra information.

## Regards,

_Emmanuel Umaña, Developer_

_Phone: 506-2225-1976 http://506-2225-1976/_

_Skype: emaurojas125_

_eumana@wearegap.com eumana@wearegap.com_

www.wearegap.com http://www.growthaccelerationpartners.com/

On Tue, Jul 5, 2016 at 10:38 AM, Abhijit Kane notifications@github.com
wrote:

> @emmanuel-umana https://github.com/emmanuel-umana Are all members of
> the team on v4.4.1 of the app? Also, can you contact us at
> help@getpostman.com with your username, and the owner of the 'AristaMD'
> collection? This will help us trace exactly what happened to the deleted
> folder.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/postmanlabs/postman-app-support/issues/2162#issuecomment-230532321,
> or mute the thread
> https://github.com/notifications/unsubscribe/ABbLSANGVKJQs-CUy_mkHuuTxPoPpCxdks5qSohpgaJpZM4JEqgD
> .

## 

_Emmanuel Umaña, Developer_

_Phone: 506-2225-1976 http://506-2225-1976_

_Skype: emaurojas125_

_eumana@wearegap.com eumana@wearegap.com_

www.wearegap.com http://www.growthaccelerationpartners.com/

**Comment by a85** [comment]
@sobtiankit @abhijitkane Still valid? Can we review all sync related bugs here once and clear them off if they are invalid?

**Comment by abhijitkane** [comment]
Was converted to a Zendesk issue - hasn't recurred since.
