### ISSUE TITLE
Folders and their requests missing when exporting/importing via share link

### ISSUE THREAD

**Issue by crunchtime-ali** [a85/POSTMan-Chrome-Extension#2165]
1. Postman Version: 4.4.1
2. App (Chrome app or Mac app): Mac app
3. OS details: macOS 10.11.6
4. Is the Interceptor on and enabled in the app: Off
5. Did you encounter this recently, or has this bug always been there: don't know
6. Steps to reproduce the problem:
   - Create a collection
   - Create a folder inside this collection
   - Add one or more requests into this folder
   - Share the collection via a collection link
   - Import  the collection as a copy or on another machine
7. Expected behaviour:
   - The folder and its requests are inside the copy of the collection
8. Encountered behaviour:
   - All requests on the base level are imported but folders and their requests are missing

**Comment by abhijitkane** [comment]
@dj-hedgehog I'm not able to reproduce this. Can you try importing this link: https://www.getpostman.com/collections/ed81698d5b22ea9d772a (it should give a collection with a folder, and one request in the folder)?

If this imports correctly, can you check the console for any errors (https://www.getpostman.com/docs/errors) while exporting/importing?

**Comment by crunchtime-ali** [comment]
It worked with your Postman collection.
I tried again adding a folder (and requests) to the project I previously had trouble with but now it works.
I'm closing this issue until the problem occurs again.
