### ISSUE TITLE
Wrong encoding for parmas

### ISSUE THREAD

**Issue by vanduc1102** [a85/POSTMan-Chrome-Extension#2168]
Hi,

I really love postman,

When I want to create a request like this:

![2](https://cloud.githubusercontent.com/assets/3014017/16616131/661b047c-43a5-11e6-8411-6c3d93975026.jpg)
This is SoapUI, a heavy one.

I want to the same in Postman, And I got error:

> Caused by: java.net.URISyntaxException: Illegal character in query at index 79: https://localhost:8443/xtao-web/rest/complementary/type-none-building?searchBy={%22criteria%22:[%22field%22:%22codeEtatTypeNonImmeuble%22,%22expression%22:%22equal%22,%22value%22:%22V%22]}&orderBy={%22order%22:[%22field%22:%22name%22,%22descending%22:%22false%22]}&range={%22from%22:0,%22to%22:100}&countOnly=false
>     at java.net.URI$Parser.fail(Unknown Source)
>     at java.net.URI$Parser.checkChars(Unknown Source)
>     at java.net.URI$Parser.parseHierarchical(Unknown Source)
>     at java.net.URI$Parser.parse(Unknown Source)
>     at java.net.URI.<init>(Unknown Source)
>     at org.jboss.resteasy.specimpl.ResteasyUriBuilder.buildFromValues(ResteasyUriBuilder.java:744)
>     ... 38 more

Now I got the URL created by SoapGUI paste to PostMan, and It work

And of course, you can look at the Params. It is encoded.

![1](https://cloud.githubusercontent.com/assets/3014017/16616407/428f8558-43a7-11e6-8f4e-100d8743298e.jpg)

So I think PostMan should work with the Params not encoded

**Comment by abhijitkane** [comment]
@vanduc1102 You can select the text, right click > Encode/DecodeURIComponent to change the encoding. Postman sends what is visible in the UI.
