### ISSUE TITLE
Postman not displaying an image after a successful GET

### ISSUE THREAD

**Issue by MicrocontrollersAndMore** [a85/POSTMan-Chrome-Extension#2169]
1. Postman Version: 4.4.2
2. App (Chrome app or Mac app): Chrome App
3. OS details: Windows 7
4. Is the Interceptor on and enabled in the app: tried with and without interceptor
5. Did you encounter this recently, or has this bug always been there: always
6. Expected behaviour: should display image ??
7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app): see screenshot
8. Screenshots (if applicable)

After a get, Postman is displaying a small piece of paper icon rather than the actual image:

![untitled](https://cloud.githubusercontent.com/assets/5672876/16654981/486fdb92-4426-11e6-930d-beff91cc915f.png)

I know the image is good since I can see the localhost program serving it on my other screen.  I've tried with both a .jpg and a .png, same result.  If I choose the copy option in the postman output window and paste into Microsoft Paint, it appears blank, and if I paste into notepad I get this:

![untitled2](https://cloud.githubusercontent.com/assets/5672876/16655072/b8bdd57a-4426-11e6-8695-a198cb920f91.png)

So at least I know there is data there, and I'm getting a 200 response so it seems the GET went through.  Any ideas??

**Comment by MicrocontrollersAndMore** [comment]
Sorry, I tried again with Interceptor turned off and now the image displays successfully

**Comment by afreeland** [comment]
Thanks for posting this =)

Probably a dumb question but why does the interceptor being enabled cause this behavior...

**Comment by tdb-alcorn** [comment]
+1 I'm still seeing that Interceptor causes image previews to break. When Interceptor is off image preview works fine. This makes working with APIs difficult. Can we re-open this issue or should I make a new one?

**Comment by stevenyeo99** [comment]
hi hel me
