### ISSUE TITLE
Feature Request - Allow copy of data from environment overview when data is double clicked

### ISSUE THREAD

**Issue by NoNameProvided** [a85/POSTMan-Chrome-Extension#2170]
Double clicking on the values in the overview (the popup which appears when the eye icon is clicked on the top right corner.) of the environment variables should copy that value to the clipboard 
1. Postman Version: 4.4.2
2. App (Chrome app or Mac app): Chrome App
3. OS details: OS X El Captain 10.11.5
4. Is the Interceptor on and enabled in the app: No
5. Did you encounter this recently, or has this bug always been there: Always
6. Expected behaviour:
7. Console logs are not needed
8. Screenshots (if applicable)

![screen shot 2016-07-08 at 10 52 19 am](https://cloud.githubusercontent.com/assets/4706265/16682466/1a99eeb2-44fb-11e6-816d-2d818c96d4cf.png)

**Comment by a85** [comment]
Thanks for the suggestions. We'll have improvements to this flow soon but probably not this exact behavior. Will update the thread if we get back to this after our backlog.
