### ISSUE TITLE
curl: no percent-encoding

### ISSUE THREAD

**Issue by sergeny** [a85/POSTMan-Chrome-Extension#2171]
Related to https://github.com/postmanlabs/postman-app-support/issues/1270 

Curl export is not doing percent-encoding. I've had "(" and ") "in the URL query string, as in
"http://server?location=point (1,2)", and it should've generated "http://server?location=point+%281,2%29".

**Comment by abhijitkane** [comment]
@sergeny Only the space needs to be encoded to %20. We'll push a fix for this in the next release.

<img width="809" alt="screen shot 2016-07-13 at 13 00 31" src="https://cloud.githubusercontent.com/assets/681190/16795226/ce0335a6-48f9-11e6-8f35-b41dc3458dba.png">

**Comment by abhijitkane** [comment]
@sergeny This has been fixed in v4.4.3 of the app.
