### ISSUE TITLE
Launch a multitude of the same GET requests with different variable in for loop

### ISSUE THREAD

**Issue by tsibiski** [a85/POSTMan-Chrome-Extension#2172]
Hello,

In looking for the solution to my problem, I came across https://github.com/postmanlabs/postman-app-support/issues/697. This issue seems to address part of my needs, but I think my need takes it to a different place.

Here is what I need:

I am creating a Collection that grabs a server url and a version number from our API. Then, I build the url for a second GET using these returned values. This second GET request retrieves an asset list that will be all of the files on our server. 

For each of these returned files, I want to launch a third request that differs only in one url parameter, which is the file name. So if there are 100 files returned from the second GET request, then I will launch the third request 100 times with a new file name each time. Each of these 100 requests will be checked for the response code of 200.

Is this currently possible with Postman? If not, is there another tool that can do this?

**Comment by abhijitkane** [comment]
@tsibiski the .setNextRequest function described in #697 will solve this. In the test script of your third request, use `postman.setNextRequest("Name of third request");` to keep repeating it.
You can set an environment variable to change the URL each time the 3rd request is run. You'll also need to store an environment variable that functions as a loop counter.

Check http://blog.getpostman.com/2016/03/23/conditional-workflows-in-postman/ for more.

**Comment by tsibiski** [comment]
Thank you!

**Comment by AmrutaBirar** [comment]
@tsibiski - can you post your collection (after removing proprietary code), I have a similar challenge
- first get api returns all the physicians in a City
- second get api needs to loop through those physicians (need to test for 200 OK)

**Comment by gaptx85** [comment]
@abhijitkane I hate to ask what seems like a stupid question, but do  you have any suggestions on how to build that loop in a way that works on Newman?
