### ISSUE TITLE
Wrongly encoding URL parameters in Postman 4.4.2-canary.1 (Mac)

### ISSUE THREAD

**Issue by thirtified** [a85/POSTMan-Chrome-Extension#2174]
1. Postman Version: 4.4.2-canary.1
2. App (Chrome app or Mac app): Mac App
3. OS details: 10.11.5
4. Is the Interceptor on and enabled in the app: no
5. Did you encounter this recently, or has this bug always been there:
6. Expected behaviour: GET URL parameter values should be sent unchanged and not encoded, as described in https://www.getpostman.com/docs/requests (and done so by the non-Canary versions, as far as I can tell).
7. Console logs: –
8. Screenshots (if applicable): –

Steps to reproduce the problem:

When sending a GET request with an URL parameter containing URL-invalid characters, Postman Canary is partially encoding/converting the value when sending the request. A value "x%y" seems to be sent out as "y%2525z", for whatever reason (tested with Postman Echo).

This does not apply to the generated code bits, e.g. cURL code with the above URL parameter value works fine.

**Comment by abhijitkane** [comment]
@czardoz Can you update this ticket if fixed?

**Comment by sdnts** [comment]
@thirtified Are you still seeing this behaviour in the latest version (4.8)? Feel free to reopen if you do :)
