### ISSUE TITLE
Refused to set unsafe header "Cookie" with interceptor on

### ISSUE THREAD

**Issue by Simonowicz** [a85/POSTMan-Chrome-Extension#2175]
1. **Postman Version:** 4.4.2
2. **App (Chrome app or Mac app):** Chrome app
3. **OS details:** Ubuntu 14.04 and Windows 7
4. **Is the Interceptor on and enabled in the app:** It is installed, on in chrome and enabled in postman.
5. **Did you encounter this recently, or has this bug always been there:** Loads of topics online, none provides help, so I suppose it's been around for quite some time.
6. **Expected behaviour:** Cookie is being sent in the request.
7. **Console logs:**

> background_page.js:428 Refused to set unsafe header "Cookie"
> sendXhrRequest @ background_page.js:428
> addToQueue @ background_page.js:538
> onExternalMessage @ background_page.js:556
> target.(anonymous function) @ extensions::SafeBuiltins:19
> EventImpl.dispatchToListener @ extensions::event_bindings:388
> target.(anonymous function) @ extensions::SafeBuiltins:19
> publicClassPrototype.(anonymous function) @ extensions::utils:151
> EventImpl.dispatch_ @ extensions::event_bindings:372
> EventImpl.dispatch @ extensions::event_bindings:394
> target.(anonymous function) @ extensions::SafeBuiltins:19
> publicClassPrototype.(anonymous function) @ extensions::utils:151
> messageListener @ extensions::messaging:205
> target.(anonymous function) @ extensions::SafeBuiltins:19
> EventImpl.dispatchToListener @ extensions::event_bindings:388
> target.(anonymous function) @ extensions::SafeBuiltins:19
> publicClassPrototype.(anonymous function) @ extensions::utils:151
> EventImpl.dispatch_ @ extensions::event_bindings:372
> EventImpl.dispatch @ extensions::event_bindings:394
> target.(anonymous function) @ extensions::SafeBuiltins:19
> publicClassPrototype.(anonymous function) @ extensions::utils:151
> dispatchOnMessage @ extensions::messaging:336

**8. Screenshots (if applicable)**
![cookie log](https://cloud.githubusercontent.com/assets/4785876/16799481/503cf40c-48f1-11e6-96c4-a86fdd9f1de6.png)

I followed all the tutorials and despite interceptor being turned on both in Postman and Chrome, in Postman alone the requests that I'm trying to send that contain cookies are not sent to the server despite the error that's displayed in the console.

**Comment by abhijitkane** [comment]
Can you try to replicate the following scenario? (httpbin.org/cookies, Cookie: hello=world, Interceptor turned on). This endpoint will return cookies that have been set on the domain.

<img width="780" alt="screen shot 2016-07-13 at 16 32 23" src="https://cloud.githubusercontent.com/assets/681190/16801280/6762f4da-4917-11e6-83d7-8780798a4e4c.png">

**Comment by Simonowicz** [comment]
The endpoint works correctly for me. The problem is still being logged, but the request headers that I inspect in interceptor do contain cookie values. I'm trying to set JSESSIONID cookie in my request using PUT method and body that is multipart/form-data type.

![cookie not set](https://cloud.githubusercontent.com/assets/4785876/16801526/7e6201ec-48fb-11e6-808d-5b0aa00a4e49.png)
