### ISSUE TITLE
Feature Request: Snippets bar hideable / resizeable

### ISSUE THREAD

**Issue by baldemarch** [a85/POSTMan-Chrome-Extension#2176]
I found the snippet sidebar a bit intrusive when writing tests since I don't use them because I can't add my own, but mostly because uses spaces that I would like to have available to write my code. I couldn't find any place where I could learn how to do this, seems like you can't. So I'm respectfully requesting this feature as an improvement for the UI and devs.

**Comment by abhijitkane** [comment]
@baldemarch What version of the app are you using? The sidebar is resizable (hover over the right edge of the sidebar and drag). To hide, click the button near the top-left of the window.

**Comment by baldemarch** [comment]
I'm using version 4.4.2 on OS X 15.6.0 / x64.

I know the left sidebar is resizable and how to do it.

What I'm talking is about the Snippets bar which are on the right side of the Tests area. That Snippets sidebar cannot be hidden or resize.

<img width="249" alt="screen shot 2016-07-18 at 23 10 22" src="https://cloud.githubusercontent.com/assets/1851559/16937434/d320bfc6-4d3c-11e6-8edc-a3d56577a6b0.png">

Thanks for your help!

**Comment by abhijitkane** [comment]
@baldemarch Ah...misread the 'snippets' part. We're working on improving the UI around the snippets section - including a collapsible sidebar and custom snippets. Will keep this thread updated.

**Comment by baldemarch** [comment]
Thank you @abhijitkane

**Comment by mstaalesen** [comment]
@abhijitkane This is especially a feature-request I can get behind after the new Two-pane-view was introduced.

**Comment by mthoreso** [comment]
+1

**Comment by sdnts** [comment]
Guys, test / pre-request snippets can now be hidden starting version 4.10.2. Can you guys verify if this solves this issue?

**Comment by mstaalesen** [comment]
Confirmed :)

**Comment by mthoreso** [comment]
Booyah!  Nicely done.  On to [#882](https://github.com/postmanlabs/postman-app-support/issues/882)
