### ISSUE TITLE
Add ability to open multiple instances of Postman in multiple Windows 10 virtual desktops

### ISSUE THREAD

**Issue by nibras85** [a85/POSTMan-Chrome-Extension#2177]
I'm using Windows 10's virtual desktops feature and I'm trying to open an instance of Postman in more than one desktop. What I noticed is that if I have an instance of Postman open in one desktop, it won't open in any other desktop. I have to close the first instance first before being able to open it in any other desktop. It would be nice if I could use multiple instances of Postman in different desktops.

OS: Windows 10 64 bit
Postman version: 4.4.2
Chrome version: 51.0.2704.103

Thanks.

**Comment by a85** [comment]
@nibras85 Can you try our native apps? The Chrome apps are set to be deprecated soon and we recommend switching to the Windows native app to avoid such issues: www.getpostman.com/apps. Let me know if this issue still exists and I'll reopen the issue.

**Comment by nibras85** [comment]
@a85 I installed the native Windows version of Postman and the issue still exists.

**Comment by sdnts** [comment]
@nibras85 You should be able to achieve this by using the New Window button on the top left. It'll open a new window of Postman that you can drag on to a different desktop. 
Correct me if I misunderstood.

**Comment by nibras85** [comment]
@madebysid Yes, what you suggested works. But it would be nice if I can just have another instance of Postman by launching it normally instead of going to the first instance, then creating another one from it.

**Comment by shez1983** [comment]
I might also add that this is not working. Although New window opens. all i get is the orange/yellowish background with image of our solar system with texts 'fastening seatbelts.. etc'

**Comment by sdnts** [comment]
@shez1983 Are you using the New Window button on the app? This works for me on v4.7.1. 
It'd be helpful if you could share a screenshot of your DevTools in #585, where your issue is being tracked.

**Comment by vivirusdi** [comment]
Hi there,

Would it possible if I've different Team to share my collections with?

Since I've Team A, Team B, Team C to work with, since with current configuration when I share a collection -or- environments to Team, it would be available to all of them (by subscribing the collections) - how do I manage a specific collection -and- environment only available for a specific Team / Person? Is it possible to do using Postman? I'm using native Postman apps.

What is the use of the new window on native Postman actually? I'm able to open a new window, but it is always using the same username? 

Thanks for any helpful information.

**Comment by sdnts** [comment]
@vivirusdi Multiple windows can be used when you're working on different collections and need a separate workspace for each. It is more of an organization utility.
Currently, you can only be signed into one team at a time, so to do what you are describing, you'll have to sign out of your current team, then sign in to the new team. In that case, your issue shouldn't occur.

**Comment by jeffheaton** [comment]
also running into this issue, the 2nd postman ends up "fastening seat belts" endlessly.  Might be a good place for an error prompt if this is not a supported feature.

**Comment by sdnts** [comment]
@jeffheaton You can open up a second Postman window by using the New Window button on the top left. Opening up multiple _instances_ of the app isn't possible, since they both try to read from the same location. I'll let you guys know when we make progress :)

**Comment by antonpious** [comment]
Even with the app this problem exists. A person is not able to open two postman each with different accounts. If we login to one, it take the same login on the other and vice versa. At least it should keep the user in context.

The other feature related to this is, why can't you have a read only account which can't create any collection by itself but can subscribe to other's collections.

**Comment by SamvelRaja** [comment]
All,
The multi-instance of app is not possible from our end. we would recommend to use the new-window button to start a new app window for this use case.

Closing this now as it won't be fixed.

**Comment by themafole** [comment]
Dears, any update on this feature, please ?

I'm obliged to open one collection on the desktop client and another one using the web browser ...

**Comment by adedejiibrahim7** [comment]
It would be really nice to be able to sign into different teams on different windows.

**Comment by yarmoliq** [comment]
It would be really nice to be able to sign into different teams on different windows.

**Comment by holoyan** [comment]
Any update?
