### ISSUE TITLE
Disable param in bulk edit with shortcut

### ISSUE THREAD

**Issue by kirugan** [a85/POSTMan-Chrome-Extension#2178]
Disabling in bulk edit view is simple now, just add "#" in the line beginning. I wish there would be option to do this with shortcut (many ide use cmd + / for commenting in editor window).

**Comment by IllyaMoskvin** [comment]
Unfortunately, toggling from "Bulk Edit" to "Key-Value Edit" after disabling a param in this manner will remove it permanently. (Confirm by toggling back to "Bulk Edit" afterwards.) Perhaps that is a separate bug, but relevant.

See also #785 for what seems to be the canonical issue of toggling params, specifically the [comment](https://github.com/postmanlabs/postman-app-support/issues/785#issuecomment-131129432) by @abhijitkane re: why this isn't possible until Collections Format v2 is implemented.

**Comment by a85** [comment]
Over the long term we will be deprecating bulk edit. It's being a blocker in supporting additional features on the main editor and essentially we have to create a translation layer between a text based format and the UI behavior. Hence, not all features will be supported in the bulk editor.

**Comment by ashadnasim52** [comment]
> Over the long term we will be deprecating bulk edit. It's being a blocker in supporting additional features on the main editor and essentially we have to create a translation layer between a text based format and the UI behavior. Hence, not all features will be supported in the bulk editor.

Brother bulk editor is much more preferred by developer, just like a normal editor add some features, like we use query in row fields, but for using params we need to use bulk editor
