### ISSUE TITLE
When viewing an authorization token, content overflows its panel.

### ISSUE THREAD

**Issue by monkora** [a85/POSTMan-Chrome-Extension#2179]
1. Postman Version: 4.4.2
2. App: Mac & Chrome
3. OS details: OS X 10.11.2
4. Is the Interceptor on and enabled in the app: No
5. Did you encounter this recently, or has this bug always been there: Always
6. Expected behaviour: Should be able to resize panel or to scroll.
7. Console logs:
8. Screenshots

![screen shot 2016-07-17 at 2 02 47 pm](https://cloud.githubusercontent.com/assets/13706254/16898306/ba56ae9e-4c27-11e6-9167-91e7e4c5254e.png)
![screen shot 2016-07-17 at 1 54 17 pm](https://cloud.githubusercontent.com/assets/13706254/16898308/d015abc2-4c27-11e6-8a1f-b432c9eda56f.png)

I've encountered an issue when requesting an authorization token. If more information is received in the token than the panel is sized for then the overflow is simply hidden from view. See screenshots: I need to be able to copy the entirety ID Token to use it as a header, and double clicking the text doesn't highlight the entire block. In the Chrome App I am able to copy it because the overflow seems to flow over the top of the response panel rather than underneath, but this is still less than ideal.

Great app on the whole, makes testing my API a breeze thank you :)

**Comment by aditikul** [comment]
@monkora Thanks for reporting this we'll check why this is happening and get it fixed shortly.

**Comment by a85** [comment]
@madebysid Is this still a valid bug?

**Comment by sdnts** [comment]
For now, yes. We're working on this.

**Comment by sdnts** [comment]
@monkora Can you update to the latest version (4.8) and check if your issue is resolved?

**Comment by monkora** [comment]
@madebysid Yes it is, cheers :)
