### ISSUE TITLE
Need copy option for links in Response body

### ISSUE THREAD

**Issue by mahendranv** [a85/POSTMan-Chrome-Extension#2180]
Links in response body might be image urls, which postman can't handle. Clicking on them opens a new tab which I found totally unusable. It would be great if you provide option to copy link in right click context menu.  
1. Postman Version: 4.4.2
2. App (Chrome app or Mac app): Chrome App
3. OS details: OS X / x86-64
4. Is the Interceptor on and enabled in the app: Yes
5. Did you encounter this recently, or has this bug always been there: Always
6. Expected behaviour: Right click on links in response body should provide option for 'copy link'
7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
8. Screenshots (if applicable)

**Comment by abhijitkane** [comment]
@mahendranv In the next version, you'll be able to select the link (by dragging the cursor), and right click > copy. Selecting the link will not open the URL in a new tab.

**Comment by abhijitkane** [comment]
@mahendranv Can you confirm this working now?

**Comment by mahendranv** [comment]
I can able to select link and copy as in normal text.

Thank you.

Mahendran V.
On Jul 26, 2016 5:44 PM, "Abhijit Kane" notifications@github.com wrote:

@mahendranv https://github.com/mahendranv Can you confirm this working
now?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
https://github.com/postmanlabs/postman-app-support/issues/2180#issuecomment-235249697,
or mute the thread
