### ISSUE TITLE
Cors Issue

### ISSUE THREAD

**Issue by pearson-lucas-dev** [a85/POSTMan-Chrome-Extension#2181]
1. Postman Version: 4.4.2
2. App (Chrome app or Mac app): Mac App
3. OS details: OS X 15.5.0 / x64
4. Is the Interceptor on and enabled in the app: No
5. Did you encounter this recently, or has this bug always been there: Recently (But I hadn't downloaded the app until recently)
6. Expected behaviour: Post to work
7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
8. Screenshots (if applicable)

Call out to Zend API that is checking CORS.

Fatal error:  Uncaught Zend\Http\Header\Exception\InvalidArgumentException: Invalid header value for Origin key: &quot;Origin&quot; in /Users/<user>/Projects/api/vendor/zendframework/zendframework/library/Zend/Http/Header/Origin.php:36

Stack trace:
#0 /Users/<user>/Projects/api/vendor/zendframework/zendframework/library/Zend/Http/Headers.php(448): Zend\Http\Header\Origin::fromString('Origin: file://')

Same exact code with Chrome App of Postman works fine.  I heard about people making hacks in Zend to catch when a header of Origin: file:// is used.  From my understanding it should be file:/// the third slash indicates the root directory and then is considered a legitimate path. 

I looked for an existing bug for this but didn't see it, sorry if I missed it.

Thanks!

**Comment by abhijitkane** [comment]
@pearson-lucas-dev You can check out a fix in Zend here - https://github.com/zf-fr/zfr-cors/issues/29

Alternatively, you can download Postman Canary for Mac here - https://www.getpostman.com/app/postman-osx-canary. This will let you specify a custom `Origin` header - something like 192.168.0.1 should do.

**Comment by pearson-lucas-dev** [comment]
@abhijitkane Yeah I have been all through that, thanks.
