### ISSUE TITLE
Special Headers in native app

### ISSUE THREAD

**Issue by sftsk** [a85/POSTMan-Chrome-Extension#2182]
Like elaborated in #1667 Interceptor is not part of the native app and like mentioned in #781 Interceptor is needed for sending some headers Chrome would not allow. i.e. `Host`.

It does not seems like the native app supports them either. Could you please tell me what to do?
Trying to test something behind a load balancer and need to make sure to reach the right  vhost.

Thank you so much for this awesome tool and your help!

**Comment by abhijitkane** [comment]
@sftsk The current version of the native app overcomes restrictions for some headers (like `Cookie`).

We have a 'canary' channel, where the native app uses the Postman Runtime (http://blog.getpostman.com/2016/06/14/introducing-postman-runtime-more-power-better-control/) to send requests, and can send the `Host` header. You can download this from https://www.getpostman.com/app/postman-osx-canary

This will soon make it's way into the production Mac app.

**Comment by sftsk** [comment]
Perfect, thank you so much :) !

**Comment by gioccher** [comment]
Hi, are there any updates on this?
I'm trying to override the Host header, and Postman v6.4.4 and v6.5.0-canary01 on Windows are ignoring it.
Thanks

**Comment by mbpakalin** [comment]
@gioccher I cant override host header too, did u fixed it somehow this ?
