### ISSUE TITLE
Code generator for HTTP for multipart/form-data generate invalid code

### ISSUE THREAD

**Issue by RomanMinkin** [a85/POSTMan-Chrome-Extension#2184]
1. Postman Version: `4.4.2`
2. App (Chrome app or Mac app): `Chrome`
3. OS details: `OSX 10.10.5`
4. Is the Interceptor on and enabled in the app: `No`
5. Did you encounter this recently, or has this bug always been there: `always`
6. Expected behaviour: Boundary value for `multipart/form-data` should be generated correctly for `HTTP`
7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app): `n/a`
8. Screenshots (if applicable)

1. Create a POST request with `multipart/form-data`
2. Click **Generate Code** (for `HTTP`)

Result:

```
POST /login HTTP/1.1
Host: example.com
Cache-Control: no-cache
Postman-Token: 6932905c-5c00-5933-f973-41137becc8ee
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

----WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="email"

email@example.com
----WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="password"

123456
----WebKitFormBoundary7MA4YWxkTrZu0gW
```

But according to https://www.w3.org/TR/html401/interact/forms.html#h-17.13.4.2 the generated coe should look like: 

```
POST /login HTTP/1.1
Host: example.com
Cache-Control: no-cache
Postman-Token: 6932905c-5c00-5933-f973-41137becc8ee
Content-Type: multipart/form-data; boundary=--WebKitFormBoundary7MA4YWxkTrZu0gW

----WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="email"

email@example.com
----WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="password"

123456
----WebKitFormBoundary7MA4YWxkTrZu0gW--
```

Diff

```
5c5
< Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

---
> Content-Type: multipart/form-data; boundary=--WebKitFormBoundary7MA4YWxkTrZu0gW
15c15
< ----WebKitFormBoundary7MA4YWxkTrZu0gW

---
> ----WebKitFormBoundary7MA4YWxkTrZu0gW--
```

**Comment by abhijitkane** [comment]
@RomanMinkin Thanks, we've fixed this in our internal build. We'll push this fix in the next release.

New output:

```
POST /post HTTP/1.1
Host: echo.getpostman.com
Cache-Control: no-cache
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="key1"

A
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="key2"

B
------WebKitFormBoundary7MA4YWxkTrZu0gW--
```

**Comment by RomanMinkin** [comment]
@abhijitkane Awesome! Thanks for heads up!

**Comment by abhijitkane** [comment]
@RomanMinkin Can you confirm the fix in v4.4.3 of the app?

**Comment by RomanMinkin** [comment]
@abhijitkane Yes, fixed in `v.4.4.4`! Thanks for a quick fix!

**Comment by xxleyi** [comment]
This bug seems come back in Postman version 7.34.0, and my OS is MacOS 10.14.3 (18D42)
