### ISSUE TITLE
could not delete cookie with the browser way

### ISSUE THREAD

**Issue by shuperry** [a85/POSTMan-Chrome-Extension#2187]
1. Postman Version: 4.4.2
2. App (Chrome app or Mac app): Mac Postman App
3. OS details: os x El Captian

I write some api with node, when I visit with my chrome browser at same url, my backend app excuted `ctx.cookies.set('jwt', null)` to delete cookie, this works in chrome and the cookie is removed, but in Postman app, cookie still there.

**Comment by abhijitkane** [comment]
@shuperry Does manually deleting the cookie from the 'Manage Cookies' section work?

**Comment by shuperry** [comment]
@abhijitkane Yeah, delete domain and cookie from `Manage Cookies` works.

**Comment by odziem** [comment]
This is still the case on 4.6.1. My understanding is that Postman doesn't set cookies with an empty string value or with an expiry in the past. This breaks a common pattern used to "unset" a cookie.

**Comment by sdnts** [comment]
I believe this ties in with [this](https://github.com/postmanlabs/postman-app-support/issues/3312) issue, and as such will be accomplished together. I'm marking this as a feature request.

**Comment by codenirvana** [comment]
~Duplicate of #3312~

Originally posted at https://github.com/koajs/koa/issues/777
