### ISSUE TITLE
Testing with Postman

### ISSUE THREAD

**Issue by maphongba008** [a85/POSTMan-Chrome-Extension#2188]
I want to test my API, that 1 function has many test cases, how can I do this in Postman. Do I have to write many requests for 1 function?
Ex: I want to test login function, and I write 2 requests, 1 for correct email/password, and 1 for wrong email/password?

**Comment by PFarrell89** [comment]
That's what I do when logging in.
I create one request that uses invalid data and another with correct data

**Comment by abhijitkane** [comment]
@maphongba008 Such questions are best suited to the Postman Slack community - https://www.getpostman.com/slack-invite
