### ISSUE TITLE
Widen Environment drop-down list

### ISSUE THREAD

**Issue by nathan-alden-sr** [a85/POSTMan-Chrome-Extension#2190]
The environment drop-down list is too small horizontally. I am forced to abbreviate my environment names to accommodate this. Preferably, the drop-down list would be wide enough to accommodate lengthy names, or at the very least resize itself automatically.

This is an issue because currently, the Environment feature is useful for more than just Test and Prod. For example, my team uses environments to represent not just deployment targets but also which identity is represented by the environment's Authorization setting.

![image](https://cloud.githubusercontent.com/assets/1189759/17029988/1ef44b6e-4f33-11e6-813b-0b38c4afd729.png)

![image](https://cloud.githubusercontent.com/assets/1189759/17030006/3bba27be-4f33-11e6-8846-83a625528bb5.png)

**Comment by aditikul** [comment]
@nathan-alden Makes sense. That's a common use case. We have increased the width of the dropdown recently however totally understand that it's not enough. We'll look into this again. We're also looking at better ways to manage environments and variables in the long run. Will update this ticket.

**Comment by nathan-alden-sr** [comment]
Thanks for the quick reply. Postman is a must-have tool for my team. Keep up the great work!

**Comment by a85** [comment]
@nathan-alden The dropdown list width is now customizable. https://www.dropbox.com/s/q3kt0mlpmujdvsc/Screenshot%202016-09-05%2019.02.03.png?dl=0
