### ISSUE TITLE
Postman Echo - Streamed Response Test Fails Intermittently

### ISSUE THREAD

**Issue by jfeltis** [a85/POSTMan-Chrome-Extension#2192]
1. Postman Version: 4.4.2
2. App (Chrome app or Mac app): Both
3. OS details: OS X 10.11.6
4. Is the Interceptor on and enabled in the app: No
5. Did you encounter this recently, or has this bug always been there: Not sure
6. Expected behaviour: Tests pass
7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app): N/A
8. Screenshots (if applicable)

1. Run Postman Echo > Utilities > Streamed Response several times until the `response is sent in chunks` test fails

The issue is that the server is not returning the `Transfer-Encoding` header consistently.

**Comment by sdnts** [comment]
@jfeltis Is this still an issue? Please let me know if it is, and I'll reopen :)
