### ISSUE TITLE
User-Agent is not overriden in headers

### ISSUE THREAD

**Issue by bublik** [a85/POSTMan-Chrome-Extension#2193]
1. Postman Version:4.4.2
2. App (Chrome app or Mac app): Chrome app
3. OS details: OSX 10.9.5
4. Is the Interceptor on and enabled in the app:
5. Did you encounter this recently, or has this bug always been there: Always
6. Expected behaviour: User-Agent header will be enabled
7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
8. Screenshots (if applicable)

**Comment by abhijitkane** [comment]
@bublik This is a restriction of the Chrome platform. We have a "Postman Canary" app for OSX which lets you override all headers - https://www.getpostman.com/app/postman-osx-canary

The Chrome app will never be able to send these restricted headers.

**Comment by bublik** [comment]
thanks for reply

Voloshin Ruslan
skype: voloshin_ruslan

2016-07-25 10:51 GMT+03:00 Abhijit Kane notifications@github.com:
