### ISSUE TITLE
Bulk Edit option doesn't preserve inserted text

### ISSUE THREAD

**Issue by kubah** [a85/POSTMan-Chrome-Extension#2196]
When editing text in Headers section with Bulk Edit option, new text disappears when current section (tab) is changed to another.
1. Postman Version: 4.4.2
2. App (Chrome app or Mac app): Chrome 51.0.2704.103
3. OS details: win / x86-32 (reported in Settings -> About section). Actually it is Windows 10 64 bit.
4. Is the Interceptor on and enabled in the app: tested with both, enabled and disabled Interceptor
5. Did you encounter this recently, or has this bug always been there: Encountered recently, not sure if it has been there already.
6. Expected behaviour:
   - Insert text to Headers section with Bulk Edit
   - Change tab to another one
   - When back to Headers tab, text still should be available in text field

How to reproduce bug:
1. Create new request
2. Go to Headers section
3. Change insert text option to Bulk Edit
4. Write some text in text field
5. Change section (tab) to another
6. Back to Headers section
7. Inserted text disappears

**Comment by vegetableman** [comment]
hey @kubah, Thanks for the detailed report 👍 . The issue has been fixed in our internal build. Will update you on the release version it will be part of.

**Comment by vegetableman** [comment]
@kubah The issue has been fixed in the recent release `4.8.3` .  Closing this. Feel free to reopen if the issue still exists ^_^.
