### ISSUE TITLE
Authorization type is not preserved when closing request tab

### ISSUE THREAD

**Issue by kubah** [a85/POSTMan-Chrome-Extension#2197]
Chosen authorization type is lost (not saved) when we open another request in the same tab.
1. Postman Version: 4.4.2
2. App (Chrome app or Mac app): Chrome 51.0.2704.103
3. OS details: win / x86-32 (reported in Settings -> About section). Actually it is Windows 10 64 bit.
4. Is the Interceptor on and enabled in the app: tested with both, enabled and disabled Interceptor
5. Did you encounter this recently, or has this bug always been there: tested with both, enabled and disabled Interceptor
6. Expected behaviour:
   - Choose authorization tab
   - Choose authorization type
   - Open another request in the same tab
   - When open previous request, authorization type should be saved

How to reproduce bug:
1. Create new request
2. Go to authorization section
3. Choose one of the authorization type
4. Change request to another
5. Back to previous request
6. Chosen authorization type was not preserved

**Comment by abhijitkane** [comment]
@kubah You need to explicitly save the Auth data with the request - check the 'Save helper data to request' box, and hit 'Save'. This section often contains sensitive information, and automatically saving it could be a security issue.

**Comment by kubah** [comment]
@abhijitkane thanks for your response.
I would like to discuss 2 problems connected with this issue.
First, in my opinion this issue is more about Postman keeping last used authorization type (also for OAuth 2.0) per request, maybe without saving sensitive informations and without explicit checking 'Save helper data to request' box.
Next thing is connected with security issue. As you wrote in your comment, saving sensitive informations could be security issue. As for now every authorization type keeps data in fields even without check 'Save helper data to request' box. Maybe this could be consider as separate problem.
If I miss your point, please correct me.

**Comment by a85** [comment]
Should be fine now with the new auth implementation.
