### ISSUE TITLE
Postman not starting

### ISSUE THREAD

**Issue by laurentyhuel** [a85/POSTMan-Chrome-Extension#2198]
Version/App Information:
-->
1. Postman Version: 4.4.3
2. App (Chrome app or Mac app): Version 52.0.2743.82 (64-bit)
3. OS details: Ubuntu 14.04 LTS (64)
4. Is the Interceptor on and enabled in the app: NA
5. Did you encounter this recently, or has this bug always been there: always
6. Expected behaviour: launch app
7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app): NA
8. Screenshots (if applicable) NA

I run in command line:
/opt/google/chrome/google-chrome --profile-directory=Default --app-id=fhbjgbiflinjbdggehcddcbncdddomop
[5161:5161:0725/165238:ERROR:display_info_provider_aura.cc(31)] Not implemented reached in virtual void extensions::DisplayInfoProviderAura::UpdateDisplayUnitInfoForPlatform(const display::Display &, extensions::api::system_display::DisplayUnitInfo *)

An icon is created in dashed and it' all, application isn't launched.
I tried to remove extension and reinstall it, same behavior.

**Comment by czardoz** [comment]
I think this is a problem with your Postman window being minimized on start. I have experienced this before unfortunately. 

Does Postman show up when you alt+tab?

**Comment by laurentyhuel** [comment]
I have 2 screens plug on my PC, main is on, other is always off. Postman was launched by default on other screen. Sorry for that mistake.
