### ISSUE TITLE
Obtain and delete OAuth 2.0 token does not update Existing Tokens list

### ISSUE THREAD

**Issue by kubah** [a85/POSTMan-Chrome-Extension#2199]
With OAuth 2.0 authorization type obtain new access token and delete it does not update table with Access Tokens.
1. Postman version: 4.4.2 and 4.4.3
2. Chrome version: 51.0.2704.103
3. OS version: win / x86-32 (reported in Settings -> About section). Actually it is Windows 10 64 bit.
4. Encountered recently, not sure if it has been there already.
5. Expected behaviour: Access Token should not be present on the Existing Tokens list after being delete

How to reproduce bug:
1. Create 2 new requests
2. Choose first request tab
3. Go to authorization section
4. Choose OAuth 2.0 authorization type
5. Create at least 3 Access Tokens
6. Select last Access Token and push Use Token
7. Go to second request tab, authorization section, choose OAuth 2.0 authorization type
8. Delete last Access Token
9. On first request tab, Access Token is still on the list

Please note: after couple attempts to obtain new token and/or delete it on these two request tabs, the Existing Tokens table stops refresh itself. It is hard to duplicate such behaviour but please keep that in mind.

**Comment by numaanashraf** [comment]
Thanks for reporting this @kubah. We'll take a look and push a fix soon.

**Comment by kamalaknn** [comment]
@kubah this should be fixed the latest version of the app(`5.2.0`). Could you update your app and lets us know if you are still seeing this.

Closing this issue now. Please do let us know if it still persists.
