### ISSUE TITLE
OAuth 2.0 support

### ISSUE THREAD

**Issue by beriberikix** [a85/POSTMan-Chrome-Extension#22]
Would love to see OAuth 2.0 support on here. For a good example, see Google's [OAuth 2.0 playground](https://code.google.com/oauthplayground/). It could be as robust as that, or plain and simple.

There's already good sample code on how to [add OAuth 2.0 to a Chrome extension](http://smus.com/oauth2-chrome-extensions/).

Either way, that would finish this off as the best REST client extension out there.

**Comment by Ulriksen** [comment]
+1

**Comment by markmadlangbayan** [comment]
+1
