### ISSUE TITLE
Newman running scripts from secured server

### ISSUE THREAD

**Issue by tariqghalib** [a85/POSTMan-Chrome-Extension#2200]
Our collections are currently on a SVN. If we use Newman to run those scripts by providing the URL's, can we also perform basic authentication from Newman before connecting the svn?

Version/App Information:
1. Postman Version: 4.4.0
2. App (Chrome app or Mac app): Chrome
3. OS details: Windows 7 Professional
4. Is the Interceptor on and enabled in the app: Yes
5. Did you encounter this recently, or has this bug always been there: Since the start
6. Expected behavior: Enable providing basic authentication credentials (username/password) for a SVN to Newman before kicking off the scripts

Steps to reproduce the problem:
- Put your collections on a SVN
- Try to run postman collections through Newman providing URL's

**Comment by czardoz** [comment]
If you're talking about collection URLs, yes, you can specify basic auth in them. 

```
newman -u http://user:pass@server/path/to/collection
```
