### ISSUE TITLE
Cookies Overlap in UI

### ISSUE THREAD

**Issue by octohub** [a85/POSTMan-Chrome-Extension#2201]
1. Postman Version: 4.4.3
2. App (Chrome app or Mac app): Mac App
3. OS details: 10.11.5, OS X El Capitan
4. Is the Interceptor on and enabled in the app: No.
5. Did you encounter this recently, or has this bug always been there: It has been there for at least July 1 2016.
6. Expected behaviour: The cookies should not overlap, it makes them very difficult to read.
7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
8. Screenshots (if applicable)
   <img width="707" alt="screen shot 2016-07-26 at 4 46 26 pm" src="https://cloud.githubusercontent.com/assets/3731917/17159222/87cccae6-5350-11e6-8073-b8145e37f3d0.png">

**Comment by numaanashraf** [comment]
@octohub Thanks for reporting this. We'll roll out a fix soon.

**Comment by octohub** [comment]
👍

**Comment by SamvelRaja** [comment]
@octohub There is a whole new UI for cookie manager is available in the latest version 😄
