### ISSUE TITLE
Starting Postman with lately used tabs

### ISSUE THREAD

**Issue by kubah** [a85/POSTMan-Chrome-Extension#2204]
It would be great if Postman could remember recently used tabs and open them when starting.

**Comment by numaanashraf** [comment]
Hi @kubah, thanks for the suggestion. We'll try to accommodate this in our backlog and get back to you when we have an ETA.

**Comment by vegetableman** [comment]
@kubah The feature has been added to the latest version 4.9 ^_^. Closing this.
