### ISSUE TITLE
Cannot save request when authorization type is set

### ISSUE THREAD

**Issue by kubah** [a85/POSTMan-Chrome-Extension#2205]
Cannot save request when authorization type is set to Basic, Digest, OAuth 1.0, Hawk or AWS
1. Postman version: 4.4.3
2. OS version: win / x86-32 (reported in Settings -> About section). Actually it is Windows 10 64 bit.
3. Chrome version: 51.0.2704.103
4. Encountered recently, not sure if it has been there already.
5. Expected behavior:
   - Choose Basic, Digest, OAuth 1.0, Hawk or AWS authorization type
   - Push Save button or Ctrl-S
   - Request is saved

How to reproduce bug:
1. Create new request
2. Go to Authorization section 
3. Change authorization type to Basic, Digest, OAuth 1.0, Hawk or AWS
4. Change request content (e.g. url)
5. Push Save button or Ctrl-S
6. Request seems to be not saved

**Comment by SamvelRaja** [comment]
@kubah Thanks for bringing this to our notice, we will be looking into it.

**Comment by vegetableman** [comment]
@kubah Could you update to the latest version `4.9`. And check if you are still facing the issue?
