### ISSUE TITLE
Default Origin header content "file://" is not a valid URI

### ISSUE THREAD

**Issue by janghwan** [a85/POSTMan-Chrome-Extension#2206]
1. Postman Version: 4.4.3
2. App (Chrome app or Mac app): Mac / Chrome
3. OS details: Mac OS X yosemite
4. Is the Interceptor on and enabled in the app: on and off
5. Did you encounter this recently, or has this bug always been there: it's been there for long time i think.
6. Expected behaviour:
7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
8. Screenshots (if applicable)

Default `Origin` header of all Postman request is `file://` which is not valid URI, and it raises exception when creating `java.net.URI`.

`new URI("file://")`
throws 

```
java.net.URISyntaxException: Expected authority at index 7: file://
  at java.net.URI$Parser.fail(URI.java:2848)
  at java.net.URI$Parser.failExpecting(URI.java:2854)
  at java.net.URI$Parser.parseHierarchical(URI.java:3102)
  at java.net.URI$Parser.parse(URI.java:3053)
  at java.net.URI.<init>(URI.java:588)
  ... 32 elided
```

The workaround is sending custom `Origin` header using interceptor in chrome app, but it doesn't seem to be possible in mac app.

**Comment by abhijitkane** [comment]
@janghwan We've moved to a new request platform in our "Postman Canary" app for OSX. you can get it here - https://www.getpostman.com/app/postman-osx-canary. We'll soon push this to the production channel.

**Comment by hgschmie** [comment]
Bug still exists in standalone postman 4.10.7 on MacOS X. 

Especially annoying when using in conjunction with the "Get new Access Token" flow to request OAuth 2.0 tokens as there is no way to influence the Origin value sent to the authentication server.

The server we are using (CloudFoundry UAA) rejects these requests in its CORS filter as invalid, because `file://` is not a valid URI. It should be `file:/` (only one slash).

**Comment by numaanashraf** [comment]
@janghwan @hgschmie This issue is not reproducible in Postman v6.7. Please verify and re-open this issue if you are still facing this.
