### ISSUE TITLE
Replay Post request doesn't work if it requires session

### ISSUE THREAD

**Issue by p00j4** [a85/POSTMan-Chrome-Extension#2208]
```
 1. Postman Version:  4.4.3
 2. App (Chrome app or Mac app): MAC App
 3. OS details: MAC OSx- 10.10.5
 4. Is the Interceptor on and enabled in the app: Enabled
 5. Did you encounter this recently, or has this bug always been there: Always
 6. Expected behaviour: Should be able to replay the post calls which require session to empower test case execution on top of them
```

**Actual**
I want to write a test case for an api which requires session
for that I'm trying to replay/repeat the post call which is behind Authentication.
Using the awesome Postman Interceptor I got login & the post call both recorded in postman history but while sending it again, it brings the index page in response as if the session is not maintained 
i'm doubting it has to do something with session cookie is not being passed but I clearly see the session id passed in Headers-Cookie

**Tried debugging:**
I see a problem here : the cookie is passed via postman is under "headers" section, I don't see a separate panel for Cookies like I see it in chrome web developer tool & charles proxy

Postman has only Headers section which has Cookie as field:
<img width="326" alt="screen shot 2016-07-28 at 4 05 53 pm" src="https://cloud.githubusercontent.com/assets/6470509/17209865/fd3506b2-54dc-11e6-9e7d-0524678eb77d.png">

Developer Tools- Chrome has Cookie as separate object and in headers both places
<img width="304" alt="screen shot 2016-07-28 at 4 05 57 pm" src="https://cloud.githubusercontent.com/assets/6470509/17209870/004e04a2-54dd-11e6-89c1-812bbaa5fe69.png">
Charles also have same mechanism like developer tool
<img width="385" alt="screen shot 2016-07-28 at 4 06 02 pm" src="https://cloud.githubusercontent.com/assets/6470509/17209873/034bb0dc-54dd-11e6-8840-4b06522e158b.png">

so my session id cookie I need to see in separate Cookie object as well as in headers just like other tools in order to make it work (edited), any guide which tells how to send that? 
As per [blog](https://www.getpostman.com/docs/interceptor_cookies): it should have worked automatically 

**Is there any more settings required to achieve it?**

**Comment by p00j4** [comment]
- @abhijitkane any idea, is it something blocked by chrome app?

**Comment by vegetableman** [comment]
@p00j4 Sorry for the late reply on this. Not sure how we missed this. The session cookie would be sent regardless of the differences in the ui you observed. Could you please try using the latest version of the chrome app and check if it's reproducible?.
