### ISSUE TITLE
Can't Post

### ISSUE THREAD

**Issue by canine-afficionado** [a85/POSTMan-Chrome-Extension#2210]
Hello, I can't get Postman to successfully send a POST in the application but if I use Postman to Generate Code and run using cURL or Python it works as expected.
1. Postman Version: 4.4.3
2. App (Chrome app or Mac app): Mac
3. OS details: OS X 10.11.6
4. Is the Interceptor on and enabled in the app: No
5. Did you encounter this recently, or has this bug always been there: Always
6. Expected behaviour: JSON response
7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
   You are not a member of a team
   You are not a member of a team
   Failed to load resource: the server responded with a status of 500 (Internal Server Error)
8. Screenshots (if applicable)
   ![image](https://cloud.githubusercontent.com/assets/20718341/17239675/54477de6-55a9-11e6-864c-1252cf5bd648.png)
   ![image](https://cloud.githubusercontent.com/assets/20718341/17239706/8769402e-55a9-11e6-9bfb-1340cfea68a7.png)

Thank you for your help and a great product.

**Comment by numaanashraf** [comment]
@b3nda1ley Could you keep DevTools open, send the request and check the Network tab in DevTools for the request that was sent? It seems like Postman is sending the POST request, but there is some issue with the API/server implementation that yielded a `500 Internal Server Error`.

**Comment by canine-afficionado** [comment]
Thanks - normally I'd agree except if I generate code for cURL or Python and run it there is no issue. It only fails when sending from Postman. Here's the network tab:

![image](https://cloud.githubusercontent.com/assets/20718341/17247203/fe7dfb34-55d4-11e6-86da-133bcea6a5ab.png)

Is it something to do with that origin header?

**Comment by canine-afficionado** [comment]
This has been rectified in 4.5 thank you

**Comment by gogson** [comment]
When will the 4.5 version be available ?
