### ISSUE TITLE
Uncaught Error: Minified exception occurred; 

### ISSUE THREAD

**Issue by calmchang** [a85/POSTMan-Chrome-Extension#2211]
requester.js:1032 Uncaught Error: Minified exception occurred; use the non-minified dev environment for the full error message and additional helpful warnings.

**Comment by numaanashraf** [comment]
@calmchang Please share your App type (Chrome/Mac/Windows), App version and OS details and also any steps you took that resulted in this error.

**Comment by SamvelRaja** [comment]
Closing this as we didn't get response from user.
