### ISSUE TITLE
Postman runner stuck in the middle of execution

### ISSUE THREAD

**Issue by tariqghalib** [a85/POSTMan-Chrome-Extension#2212]
**Problem Statement:**
I have a lot of test cases and when I try to run one of the folder under a collection, postman runner pauses at a test case and stays stuck at that forever.

**Version/App Information:**
1. Postman Version: 4.4.0
2. App (Chrome app or Mac app): Chrome App
3. OS details: Windows 7 Professional
4. Is the Interceptor on and enabled in the app: Yes
5. Did you encounter this recently, or has this bug always been there: Always
6. Expected behaviour: Runner should continue executing tests till the end of the suite
7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):

**Steps to reproduce the problem:**
1. Create a collection
2. Add sub folders to the collection
3. Add tests under the folders
4. Execute one sub folder under the collection

**Comment by a85** [comment]
Issues like these should be fixed with 5.0+. I'd recommend switching to our native apps. www.getpostman.com/apps
