### ISSUE TITLE
Feature Request: Be able to create Environment Folders

### ISSUE THREAD

**Issue by baldemarch** [a85/POSTMan-Chrome-Extension#2213]
Say you start working with a large amount of environments, the list grows and need to change according to the endpoints you are working on.

It would be great to have folders to organize the environments and cycle through them faster.

Thanks!

**Comment by arctouch-douglaskazumi** [comment]
Additionally, a second combo box could be added to select environments(dev, prod, qa...) for a certain app.

**Comment by a85** [comment]
We have introduced Workspaces recently to help organize your work better. There are no plans for folders around environments for now.
