### ISSUE TITLE
Header "Content-Type" is not exported at all (collection v2) or not exported properly (collection v1).

### ISSUE THREAD

**Issue by pollenflugkalender** [a85/POSTMan-Chrome-Extension#2215]
1. Postman Version: 4.4.3
2. App (Chrome app or Mac app): Chrome app
3. OS details: Windows 7 Enterprose 64bit
4. Is the Interceptor on and enabled in the app: no
5. Did you encounter this recently, or has this bug always been there: seems to be a new bug.
6. Expected behaviour:

There seems to be a problem with the export of headers.
### 1. Collection v1:

The exported json of the header "Content-Type: application/x-www-form-urlencoded" has a space between "Content-Type" and the colon ":"

Expected behaviour:  
`Content-Type: application/x-www-form-urlencoded"`

Actual behaviour:
`Content-Type : application/x-www-form-urlencoded"`  (wrong)
### 2. Collection v2:

If I export the same collection in collection format v2 the whole Content-Type header is missing.

Example:

Expected behaviour::

```
                "header": [
                    {
                        "key": "Authorization",
                        "value": "Basic {{bearer_token}}",
                        "description": ""
                    },
                    {
                        "key": "Content-Type",
                        "value": "application/x-www-form-urlencoded",
                        "description": ""
                    }
                ],
                "body": {
                    "mode": "urlencoded",
                    "urlencoded": []
                },
                "description": ""
            },

```

Actual behaviour:

```
                "header": [
                    {
                        "key": "Authorization",
                        "value": "Basic {{bearer_token}}",
                        "description": ""
                    }
                ],
                "body": {
                    "mode": "urlencoded",
                    "urlencoded": []
                },
                "description": ""
            },
```
1. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
2. Screenshots (if applicable)

**Comment by abhijitkane** [comment]
@pollenflugkalender Can you attach a screenshot of what the headers tab of your request looks like in Postman?

**Comment by shamasis** [comment]
@czardoz cc

**Comment by pollenflugkalender** [comment]
headers tab image (Key-Value Edit):
![image](https://cloud.githubusercontent.com/assets/8361094/17860891/54079656-688f-11e6-850f-cd6b18b08327.png)

**Comment by pollenflugkalender** [comment]
header tab image (Bulk Edit):

![image](https://cloud.githubusercontent.com/assets/8361094/17861047/d55d394a-688f-11e6-8801-3cf81325504d.png)

**Comment by pollenflugkalender** [comment]
I get the same error with the brand new stand-alone Postman Windows application.

![image](https://cloud.githubusercontent.com/assets/8361094/17861272/aa39d4b6-6890-11e6-96d0-ef414958671f.png)

This means that it's not a bug of the export but an internal issue. Nevertheless the collections still work within the chrome app.

**Comment by pollenflugkalender** [comment]
I found a workaround for the problem:

If I set the  header "Content-Type" in "Headers" and the content type in "Body" to "raw" then the header is exported properly in both export formats.

**Comment by a85** [comment]
Closing as an old bug and should be fixed as part of updates to the new collection format.
