### ISSUE TITLE
4.5.0 response body color are wrong

### ISSUE THREAD

**Issue by robhicks** [a85/POSTMan-Chrome-Extension#2216]
I just upgraded and the response body is a grey background with black text. 
1. Postman Version: 4.5.0
2. App (Chrome app or Mac app): Mac
3. OS details: OSX v 10.11.6
4. Is the Interceptor on and enabled in the app:
5. Did you encounter this recently, or has this bug always been there: Recent - due to upgrading
6. Expected behaviour: see pics
7. Screenshots (if applicable)

Steps to reproduce the problem:
1. install 4.5.0
2. send a request with Accept application/json
<img width="481" alt="screen shot 2016-08-01 at 9 15 14 pm" src="https://cloud.githubusercontent.com/assets/719152/17315960/58738154-582d-11e6-9aea-7391c5defa9d.png">
<img width="281" alt="screen shot 2016-08-01 at 9 15 38 pm" src="https://cloud.githubusercontent.com/assets/719152/17315961/58761202-582d-11e6-9e78-9002abc1957b.png">

**Comment by czardoz** [comment]
@robhicks, is there a `Content-Type` header present in the response? If yes, can you share the value of the header?

**Comment by jhiemer** [comment]
@czardoz same issue over here. Using Spring Data REST endpoint, which responds with:

`Content-Type →application/hal+json;charset=UTF-8`

Layout not to good atm. :-)

**Comment by conteit** [comment]
It's not only a layout issue: also the toolbar for Pretty/Raw/Preview, ... is not displayed.

It seems that new postman no more handles application/hal+json content type.

**Comment by czardoz** [comment]
@conteit You're right, that's the bug. We're working on a fix as we speak :)

**Comment by shamasis** [comment]
Yay! I see 4.5.1 has this fixed. Can anyone else confirm? Then I'll close this.

**Comment by robhicks** [comment]
Fix in 4.5.1 confirmed.

**Comment by robhicks** [comment]
By the way, the content type that was being returned in the response used to open this issue was application/vnd.fs-idx-projecttemplate-v1+json not application/hal+json

**Comment by shamasis** [comment]
+json is detected as json now in any type. 😊 Closing the issue.
