### ISSUE TITLE
add a pause or on/off toggle button to temporarily stop sending an individual parameter with the request

### ISSUE THREAD

**Issue by rubenjleon** [a85/POSTMan-Chrome-Extension#2219]
1. Postman Version:   Version 4.5.0
2. App (Chrome app or Mac app):  Mac application
3. OS details: 10.11.6

Feature Request:
![screen shot 2016-08-02 at 8 41 07 am](https://cloud.githubusercontent.com/assets/7998624/17334987/2c3ff1ca-588d-11e6-8392-4d607c68e360.png)

In the attached image, there are two icons in the far right allowing a user to move their parameters up and down vertically for better organization and an "x" for deleting a parameter.  These are great features.  I suggest adding another button, something a like a pause button or an on an off toggle button to simply stop an individual parameter from being sent with a request.   I have to turn parameters off to test the output when required parameters are not sent. 

Currently I have to delete a parameter so it is not sent, then type it in again when I do need it.  So adding another button icon that simply prevents the parameter from being sent with the request saves a lot of time and trouble.  

Thanks!

**Comment by a85** [comment]
@shamasis is this something that can be fixed through the runtime?

**Comment by shamasis** [comment]
@a85 it's a matter of hooking it up using UI and little tweak in runtime.

**Comment by abhijitkane** [comment]
@JamesLeon This is available in Postman 5.2+.

**Comment by rubenjleon** [comment]
Awesome, Thanks!
