### ISSUE TITLE
Runnr not working

### ISSUE THREAD

**Issue by rohin** [a85/POSTMan-Chrome-Extension#2220]
1. Postman Version: 4.5.0
2. App (Chrome app or Mac app): Mac App
3. OS details: OSX 10.11.6
4. Is the Interceptor on and enabled in the app:
5. Did you encounter this recently, or has this bug always been there: Recently
6. Expected behaviour: The Test Collection should have run using runnr
7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
8. Screenshots (if applicable)

I have a postman collection which I run daily to test my APIs. It was working fine till yesterday however it has stopped working this morning. I tried to look at Postman console and even dev console but did not see any error. As soon as I hit the start button it stops saying 0 passed 0 failed. I even tried a fresh install.

**Comment by czardoz** [comment]
@rohin, can you tell us more about the collection? 1. How many requests does it have? 
2. Do you use environments with it?
3. Do you use iteration data files? If yes, do you use CSV or JSON?
4. How many iterations have you configured it for?
5. Do you see any error show up as a red alert in the runner window?
Any other details you can give will help too!

**Comment by rohin** [comment]
Let me try and answer
1. How many requests does it have?  - Collection has 3 sub-folder, sub-folder 1 has 22 requests which I am trying to execute
2. Do you use environments with it? - When I run single iteration I use environment, when I run multiple iterations I use a CSV file. I tried with and without environment.
3. Do you use iteration data files? If yes, do you use CSV or JSON? CSV when running iterations.
4. How many iterations have you configured it for? 8
5. Do you see any error show up as a red alert in the runner window? Nope. None - which is the part that bumped me. It did work yesterday though I am not sure if it was before the 4.5 update or after it. 

Are there particular log files which I can locate and share?
Any other details you can give will help too!

**Comment by czardoz** [comment]
A screenshot of your devtools console will help a lot, even if it contains no errors.

**Comment by rohin** [comment]
<img width="1135" alt="screen shot 2016-08-03 at 11 40 47 am" src="https://cloud.githubusercontent.com/assets/369916/17355584/33ceb6e6-596f-11e6-94db-6899d680b13c.png">

The screenshot should show you the setup and the dev console setup as well.

**Comment by czardoz** [comment]
Awesome, thanks! We're looking into the issue.

**Comment by rohin** [comment]
It is working for me now post the 4.5.1 update. Gr8!!
