### ISSUE TITLE
Postman unable to look up things or thing graphs since update

### ISSUE THREAD

**Issue by grace-spitzer-wong** [a85/POSTMan-Chrome-Extension#2223]
Hi

I've been using Postman to look up thing graphs and things but for an unknown reason since the recent update, I'm getting this error message and it takes a long time to send and get the error:

Could not get any response
There was an error connecting to xxx
Why this might have happened:
The server couldn't send a response: - Server is working
Ensure that the backend is working properly - all correct
Self-signed SSL certificates are being blocked: - certificates all fine
Fix this by turning off 'SSL certificate verification' in Settings > General - done
Request timeout:
Change request timeout in Settings > General - done

My colleague has no problems.

Any ideas?

Thanks

**Comment by TTN-js** [comment]
I have this issues as well (Using to test API). It looks like its only a problem on the packaged app. I tested things on the chrome extension and things seem to work fine. 

Has your colleague updated?

**Comment by mayken** [comment]
i have the same problem. v4.5.0

**Comment by TTN-js** [comment]
Probably related to issue #2217 and #2214. Looks like they are working on it.

**Comment by grace-spitzer-wong** [comment]
Wanted to test on Chrome extension but for some reason when I try to get the extension, it won't let me as I have the app installed.

**Comment by grace-spitzer-wong** [comment]
@TTN-js thanks for flagging the associated issue.

**Comment by TTN-js** [comment]
@Grace-W That's weird. Maybe uninstall the packaged app and get the chrome extension for the time being?

**Comment by a85** [comment]
Thanks for the report. We are working hard on fixing these asap.

**Comment by shamasis** [comment]
This is addressed in 4.5.1. Closing as duplicate.
