### ISSUE TITLE
Postman 4.5.1 - postman.getResponseCookie not working

### ISSUE THREAD

**Issue by DerFlash** [a85/POSTMan-Chrome-Extension#2226]
1. Postman Version: 4.5.0
2. App (Chrome app or Mac app): Mac app
3. OS details: macOS 10.11.5
4. Is the Interceptor on and enabled in the app: no
5. Did you encounter this recently, or has this bug always been there: recently (update)
6. Expected behavior: Should return the cookie
7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
8. Screenshots (if applicable)
9. Steps to reproduce the problem:

I just noted after updating to v4.5.0 that postman.getResponseCookie("myCookie") does no longer return the given cookie with this name.
I confirmed that it is available by checking the return Cookies tab and also by looking into console.log(responseCookies).

Kind regards
Björn

**Comment by shamasis** [comment]
Seems it's working. Need to know more why it's not working for you. Can you pass more details such as maybe a scaled down collection that we can import and reproduce the result.

**Comment by DerFlash** [comment]
The request are going to an enterprise internal oData service, so unfortunately sharing the collection won't help to reproduce it directly.

I'll try to give as many information as possible by going step by step through the specific requests:

The request is a POST request sending a basic auth header, Accept (application/xml,application/atom+xml), Content-Type (application/atom+xml) and an XML body.

The script/test is this:

``` javascript
var auth = request.headers["Authorization"]
postman.setGlobalVariable("AUTH", ""+auth);
tests["AUTH updated"] = true;

console.log(postman.getResponseCookie('X-SMP-APPCID'));
console.log(responseCookies);

if (responseCode.code === 201)
{
    var jsonObj = xml2Json(responseBody);
    var appCID = jsonObj["entry"]["content"]["m:properties"]["d:ApplicationConnectionId"];
    if (appCID)
    {
        postman.setGlobalVariable("X-SUP-APPCID", ""+appCID);
        tests["AppCID updated from content"] = true;
    }
    else
    {
        tests["AppCID not found"] = false;
    }

} else {
    var appCIDCookie = postman.getResponseCookie('X-SMP-APPCID');
    if (appCIDCookie)
    {
        postman.setGlobalVariable("X-SUP-APPCID", appCIDCookie.value);
        tests["AppCID updated from cookie"] = true;
    }
    else
    {
        tests["AppCID cookie not found (PostMan Interceptor not activated?)"] = false;
    }
}
```

When I first send it, I get a '201 Created', so the script can just parse the needed AppCID from the returned XML body.
On optional later request we won't get 201, so we try to get the AppCID from the cookies, which we got anyway.

This works fine on 4.4.3, but not on 4.5.0/4.5.1.

Looking at the log output of the script in 4.4.3:
<img width="1158" alt="bildschirmfoto 2016-08-09 um 11 33 01" src="https://cloud.githubusercontent.com/assets/185013/17511880/5b7eb5e6-5e25-11e6-9cbb-8c4c4936693b.png">

Looking at the same log output of the script in 4.5.1:
<img width="1156" alt="bildschirmfoto 2016-08-09 um 11 41 49" src="https://cloud.githubusercontent.com/assets/185013/17512111/924e137c-5e26-11e6-8df3-195d68da32f4.png">

I think this object format difference may be the reason why postman.getResponseCookie is not working correctly?

In both versions the cookies look fine in the cookies tab:
(although the AppCID cookies get doubled after the initial request)
<img width="1338" alt="bildschirmfoto 2016-08-09 um 11 38 48" src="https://cloud.githubusercontent.com/assets/185013/17512195/0287a270-5e27-11e6-88e0-81b7d52d496f.png">

**Comment by shamasis** [comment]
This should be resolved now. Closing. Please reopen if otherwise.

**Comment by DerFlash** [comment]
Works like a charm
