### ISSUE TITLE
Collection runner fails when a header is deactivated

### ISSUE THREAD

**Issue by jkrenge** [a85/POSTMan-Chrome-Extension#2227]
1. Postman Version: 4.5.0
2. App (Chrome app or Mac app): Mac app
3. OS details: OS X 15.6.0 / x64
4. Is the Interceptor on and enabled in the app: no
5. Did you encounter this recently, or has this bug always been there: recently
6. Expected behaviour: Collection Runner should execute tests and if something fails tell me so
7. Console logs: -
8. Screenshots (if applicable): see below
## Steps to reproduce the problem:

(1) Create a new request with a simple test case, then add a header to the request but deactivate it.

![screen shot 2016-08-04 at 12 31 11](https://cloud.githubusercontent.com/assets/625618/17398880/59d0c2dc-5a3f-11e6-9868-86bcb1f2067d.png)

(2) Run this collection with the collection runner. It won't mark any tests as failed but briefly show an error window on top of the screen.

![screen shot 2016-08-04 at 12 22 26](https://cloud.githubusercontent.com/assets/625618/17398840/23977fbc-5a3f-11e6-8d7d-39e49650325f.png)

---

This is made worse by #1963

**Comment by a85** [comment]
Thanks for the report. We are working hard on pushing a fix asap.

**Comment by shamasis** [comment]
Upgrade to 4.5.1 - it should now stop sending disabled headers. Give it a spin and drop a feedback here so that I can close the issue.

**Comment by jkrenge** [comment]
Nice. ✌🏼️

**Comment by shamasis** [comment]
We've identified and addressed additional aspects of the issue. It's going out in next release which is tentatively v4.6 on Mac, scheduled for today. Would love if anyone can confirm this once the update is received.

**Comment by jkrenge** [comment]
Works already in 4.5.1, will check 4.6 as it's updated.
