### ISSUE TITLE
import test run in collection runner with pervious test execution that exported before not run and give me error

### ISSUE THREAD

**Issue by hanyghazal** [a85/POSTMan-Chrome-Extension#2228]
1. Postman Version: 4.4.3
   1. App (Chrome app or Mac app):Chrome app
   2. OS details: windows 7
   3. Is the Interceptor on and enabled in the app: not enabled 
   4. Did you encounter this recently, or has this bug always been there: no this is first time
   5. Expected behavior:  should import any previous test run that exported in any old version because no meaning  and not make sense to make export to something not able to import it with new postman versions  
      7.actual behavior : when run a test before in previous versions then save the test run by export it after finish run then now on this postman version try to import this test runs , it give me error "can not import test run, please check the format of the file".

**Comment by GregoryPellegrin** [comment]
This problem is still active on 6.4.4

**Comment by bickelk** [comment]
Still seeing this problem on v6.5.3.
