### ISSUE TITLE
Postman  4.5.0 - Frozen and blank MainWindow after call to my API for a response body size about 16000 lines

### ISSUE THREAD

**Issue by francknouama** [a85/POSTMan-Chrome-Extension#2229]
1. Postman Version: 4.5.0
2. App (Chrome app or Mac app): Mac App
3. OS details: Mac OS Yosemite
4. Is the Interceptor on and enabled in the app: no
5. Did you encounter this recently, or has this bug always been there: It only happen since I applied the last upgrade to Postman
6. Expected behaviour: Getting the response displayed into the response panel as before
7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app): debugger also lost the connection with app dude to this issue
8. Screenshots (if applicable)
   ![postman-frozen](https://cloud.githubusercontent.com/assets/586511/17407245/8c58edd4-5a34-11e6-8d70-643087acd88d.png)
   ![error with web developer tools](https://cloud.githubusercontent.com/assets/586511/17407248/90960c7e-5a34-11e6-9c5b-c9c9002ef4e9.png)

**Comment by shamasis** [comment]
4.5.1 should fix this. Seems like JSON.parse was blocking things with large string when sent to Postman Console (a newly introduced feature to see what request and response is being sent by postman). So, we now truncated it. That seems to have solved the issue - at least in our tests.

**Comment by shamasis** [comment]
This should be resolved now. Closing. Please reopen if otherwise.

**Comment by francknouama** [comment]
Sounds good! Thanks @shamasis
