### ISSUE TITLE
Collection Ordering gets randomized on add

### ISSUE THREAD

**Issue by taer** [a85/POSTMan-Chrome-Extension#223]
I have a collection with about 20 requests in it. I ordered them, and quit for the day. The next time I use it, they're in the same order.

I then added a new requests by
1) Pick one of the requests that is close to what I want.
2) Edit the VERB(POST to PUT for example)
3) Hit Add to collection, pick the collection, and give it a new name.
4) it appears at the bottom as I expect.
5) quit chrome
The next time I launch chrome and open postman, I got the collection and find not only is the new entry randomly placed in the list, the entire list has been shuffled around. 

A workaround I found:
Add the new API call. It goes to the bottom. Prior to quitting, grab it, move it randomly, then move it back. At that point, the list seems to persist it's order.

**Comment by zeeshanejaz** [comment]
Why is this happening again? I use postman for scenario testing and order is really important.
