### ISSUE TITLE
4.5.0: Tests fail on JSON.parse(responseBody)

### ISSUE THREAD

**Issue by conteit** [a85/POSTMan-Chrome-Extension#2230]
Since I've updated Postman to version 4.5.0 I get this error on any test that tries to parse the request body (see screenshot).

![schermata 2016-08-04 alle 12 04 36](https://cloud.githubusercontent.com/assets/1316540/17430762/72f1fb0c-5af6-11e6-81df-9de8473add23.jpg)

I'm running Postman Mac App on MacOS El Captain 10.11.6. No interceptor is enabled, no evidence in logs.

The response body is a standard JSON body like:

``` json
{
  "status": "READY",
  "configFile": "file:///C:/MyApp/settings.xml",
  "maxActiveStreamCount": 1,
  "selectedStudyId": "65602129",
  "freeSpace": 443359035392,
  "lowDiskSpaceWarning": false
}
```

Content-Type is `application/json; charset=utf-8` and Server is `Microsoft-HTTPAPI/2.0`

Before updating the App everything worked smoothly.

**Comment by czardoz** [comment]
@conteit Could you post a screenshot of your DevTools? You can open it in the "View" menu of the app.

**Comment by abhijitkane** [comment]
@conteit Also, can you try changing the URL to https://gist.githubusercontent.com/abhijitkane/9d465c7fd56edf73cd5b4eede8ea1db5/raw/fedf75aef76020a2dff27eb944b51c4c2b83a4f3/gh2230.json and trying?

**Comment by conteit** [comment]
@czardoz 
![schermata 2016-08-05 alle 14 04 59](https://cloud.githubusercontent.com/assets/1316540/17436172/ad84cc80-5b15-11e6-9907-c1e0bf2deae0.jpg)

**Comment by conteit** [comment]
@abhijitkane: The URL you provided me actually works.
![schermata 2016-08-05 alle 14 09 59](https://cloud.githubusercontent.com/assets/1316540/17436294/54459766-5b16-11e6-8ebc-d65975559fad.jpg)

The environment variable is correctly set. The Content-Type in this case is `text/plain`.

**Comment by shamasis** [comment]
We released 4.5.1 with more intelligent checks for content type header. Can you give it a spin and let us know if it works?

**Comment by conteit** [comment]
Sorry for the delay.

Unfortunately it does not work.
![schermata 2016-08-07 alle 20 45 47](https://cloud.githubusercontent.com/assets/1316540/17464491/5399b0b0-5ce0-11e6-9529-eb8485c99b2b.jpg)

Still nothing in DevTools.

**Comment by abhijitkane** [comment]
@conteit Can you attach a screenshot with the Body response tab selected instead of Tests?

**Comment by conteit** [comment]
![schermata 2016-08-07 alle 21 12 57](https://cloud.githubusercontent.com/assets/1316540/17464631/cbe56fac-5ce3-11e6-8d3f-02cd81ed84a7.jpg)

**Comment by abhijitkane** [comment]
And with the raw mode selected instead of pretty? My guess would be there's some non-printing character which is failing the JSON.parse in your test script.

**Comment by conteit** [comment]
![schermata 2016-08-07 alle 21 17 16](https://cloud.githubusercontent.com/assets/1316540/17464652/60bc7c92-5ce4-11e6-87f6-46404ce7a466.jpg)

**Comment by abhijitkane** [comment]
Can you try `JSON.parse(responseBody.substring(1));`?

**Comment by conteit** [comment]
It worked! But I cannot understand why.
![schermata 2016-08-07 alle 21 24 16](https://cloud.githubusercontent.com/assets/1316540/17464690/83ece0ac-5ce5-11e6-80bf-87e1ceebe66a.jpg)

**Comment by abhijitkane** [comment]
There's a non-printing character as the first character in your response. 

This will print out the ASCII value of the first character as a test:

`tests['ASCII Code for char[0]: ' + responseBody.charCodeAt(0)] = true;`

**Comment by conteit** [comment]
There is a "zero-width no-break space" in front of the response, it's something that Microsoft framework uses as byte-order-mark (BOM) according to [this post](http://stackoverflow.com/questions/6784799/what-is-this-char-65279). I have not changed the server implementation so it is something that probably was managed in previous versions of Postman.

**Comment by conteit** [comment]
The issue is still present in v4.7.0. Are you still working on it?

**Comment by a85** [comment]
@conteit Yep. Looking into it again.

**Comment by shamasis** [comment]
@czardoz add liquid-json as a JSON replacement inside sandbox and that should address this. There wasn't anything specific we were doing except if XHR handled slant specific case. Point to note that this issue was present with XHR as well.

**Comment by a85** [comment]
@shamasis @SamvelRaja can we close this now?
