### ISSUE TITLE
Query parameters without a value assigned an explicit empty value

### ISSUE THREAD

**Issue by mlschechter** [a85/POSTMan-Chrome-Extension#2231]
1. Postman Version: 4.5.1
2. App (Chrome app or Mac app): Mac app
3. OS details: OS X 10.11.6
4. Is the Interceptor on and enabled in the app: Cannot get the interceptor to work, so I'm thinking "no"
5. Did you encounter this recently, or has this bug always been there: Was working correctly in 4.4.3, and broken in 4.5.1
6. Expected behaviour: Query parameters that do not specify a value should be sent as is, without appending an `=` to the parameter name
7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
   It should be View->Show DevTools for the Mac App; there were no console logs
8. Screenshots (if applicable)
   N/A

Execute a `GET` on the following URL from a browser and from Postman:
`http://www.webservicex.com/globalweather.asmx?WSDL`

The appended `=` will cause the request (now `http://www.webservicex.com/globalweather.asmx?WSDL=`) to fail from within Postman. This can be verified by adding the `=` to the URL in the browser and seeing that the error is the same.

This may be related to #2218

**Comment by shamasis** [comment]
Checking.

**Comment by shamasis** [comment]
Hey - this issue has been identified and is being tested as I type this. Once this, and a bunch of others get tested, we will release it. Should be sometime next week.

**Comment by czardoz** [comment]
Has been fixed with this change: https://github.com/postmanlabs/postman-collection/pull/82

The fix will be out in the next release :)

**Comment by mlschechter** [comment]
Thanks for the quick turnaround! Postman is an exceedingly useful tool for us.

**Comment by shamasis** [comment]
We've identified and addressed the issue. It's going out in next release which is tentatively v4.6 on Mac, scheduled for today. Would love if anyone can confirm this once the update is received.

**Comment by shamasis** [comment]
This should be resolved now. Closing. Please reopen if otherwise.
