### ISSUE TITLE
javascript window object is not defined in version 4.5

### ISSUE THREAD

**Issue by matart15** [a85/POSTMan-Chrome-Extension#2233]
## javascript `window` object is not defined in version 4.5

pre-request code was working on 4.4

```
window.Utils = {
   ...
}
```

after version 4.5 this code gives error 

```
reference window is not defined
```

 if i downgrade to 4.4.3 It is still working
1. Postman Version: 4.50 and 4.5.1
2. App (Chrome app or Mac app): Mac app
3. OS details: OSX 10.11.6
4. Is the Interceptor on and enabled in the app: No
5. Did you encounter this recently, or has this bug always been there: recently (after 4.5.0 update)
6. Expected behaviour: send request
7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app): Not working
8. Screenshots (if applicable)

version 4.4.3
<img width="969" alt="screen shot 2016-08-06 at 11 08 49 am" src="https://cloud.githubusercontent.com/assets/17027219/17454147/2eb7e2e0-5bc7-11e6-8585-4f797f617afd.png">

version 4.5.1
<img width="972" alt="screen shot 2016-08-06 at 11 10 38 am" src="https://cloud.githubusercontent.com/assets/17027219/17454151/37a298fa-5bc7-11e6-991d-c9cdbd1ff8e6.png">

**Comment by shamasis** [comment]
Window, DOM and jquery has been marked as deprecated since long. It has now been discontinued. 

Are you using the window object to store something that would be available through a run? If yes, use environment variables. Closing this. We may still continue the discussion to address your use.

**Comment by matart15** [comment]
Yes I am using window to store my functions through other test.
I tried enviroinment variables. But I could not make it work.

I could save environment variable like this.
![screen shot 2016-08-08 at 9 51 11 am](https://cloud.githubusercontent.com/assets/17027219/17466587/e7bc90ec-5d4d-11e6-88bf-583cf0fe402f.png)

And confirmid it on manage env
![screen shot 2016-08-08 at 9 51 47 am](https://cloud.githubusercontent.com/assets/17027219/17466591/00a80f82-5d4e-11e6-8a3d-05689733d926.png)

But in the test it says no function
![screen shot 2016-08-08 at 9 52 00 am](https://cloud.githubusercontent.com/assets/17027219/17466592/04075d7c-5d4e-11e6-90df-17262c5421b8.png)

I also tried saving object as string then called `eval` but could not access my function too.

If it is not big trouble could you provide some way to save functions in env variable or point me to the direction.

**Comment by shamasis** [comment]
With the new runtime, persisting a function through requests is not possible because data goes via IPC and it serialises all variables. We will have to code something to facilitate this. 

One question: are you using this while making requests from the builder or are you using it in collection runner? Or both?

**Comment by matart15** [comment]
I am using this for both. In 4.43 this works with collection runner too.

I declare one function in very first test. For example  

```
window.Utils = {
     schemaTest: function(tests, schema, key = null){
        if (typeof key === 'undefined' || key === null) {
            tests["schemaTest_jsonData == " + schema.title ] = tv4.validate(this.jsonData, schema);
        } else {
            var val = this.get(this.jsonData, key)
            tests["schemaTest : " + key + " == " + schema.title] = tv4.validate(val, schema);
        }
    },
    userSchema: {
      "title": "userSchema",
      "type": "object",
      "allOf": [
        modeBaselSchema,
        {
            "properties": {
                "name": { "type": "string" },
                "email": { "type": "string" },
                "followers_count": { "type": "integer" },
                "followings_count": { "type": "integer" },
            },
        "required": [ "name" ]
        },
    ],
  }
}
```

And save it to window (if possible global).

Later I have 13 or more requests that include UserModel in response. For each of them I use `Utils.schemaTest(tests, Utils.userSchema, key = "data.0.user")`
It is easier. 

I can define `schemaTest` and `userSchema` in each test. 
But problem is my schemas gets changed easily with my api gets new functionality.
So, changing code in multiple place is not safe because I am a only human and I can easily forget to change one of them. Currently I have 17 models.

So if I understand right There is no way to achieve this in v4.5 right?.

**Comment by shamasis** [comment]
You can. Simply save the code as string in an environment variable in first request and eval it in subsequent requests.

**Comment by matart15** [comment]
I will try that later. For now I stick with v4.4
Thank you.
