### ISSUE TITLE
Windows Native App - .addHours returns an error. Works fine in Chrome App

### ISSUE THREAD

**Issue by PFarrell89** [a85/POSTMan-Chrome-Extension#2235]
Forgive me, I'm not super technical:
1. **Postman Version:** win32 10.0.10586 / x64
2. **App (Chrome app or Mac app):** Desktop
3. **OS details:** Windows 10 Professional 64bit
4. **Is the Interceptor on and enabled in the app:** No
5. **Did you encounter this recently, or has this bug always been there:** Only occurs in Desktop App

**"There was an error in evaluating the test script:  TypeError departure.addHours is not a function**"

The below code returns the above error. The same code runs perfectly fine in the Chrome app:

```
var duration = new Date();
var departure = new Date();
departure.addHours(duration.getHours());
departure.addMinutes(duration.getMinutes());
```

![error](https://cloud.githubusercontent.com/assets/8641826/17483027/4bfc1086-5d7c-11e6-9f82-e6df78a91b8c.PNG)

**Comment by shamasis** [comment]
We've identified and addressed the issue and other SugarJS related ones. It's going out in next release which is tentatively v4.6 on Mac, scheduled for today. Would love if anyone can confirm this once the update is received.

**Comment by shamasis** [comment]
This should be resolved now. Closing. Please reopen if otherwise.
