### ISSUE TITLE
OAuth 2.0 dialog - cursor jumps to end on keypress in URL fields

### ISSUE THREAD

**Issue by samcook** [a85/POSTMan-Chrome-Extension#2236]
1. Postman Version: 4.4.3
2. App (Chrome app or Mac app): Chrome
3. OS details: Windows 10
4. Is the Interceptor on and enabled in the app: No
5. Did you encounter this recently, or has this bug always been there: Unsure
6. Expected behaviour: Cursor doesn't jump to end of URL text field after each keypress
7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
8. Screenshots (if applicable)

Steps to reproduce the problem:
- In the Authorization tab, set type to "OAuth 2.0" and click "Get New Access Token".
- In either "Auth URL" or "Access Token URL", attempt to edit the URL.
- The cursor jumps to the end of the text field after each keypress, which is really unhelpful if you're trying to type anywhere except the end of the string.

**Comment by numaanashraf** [comment]
@samcook Thanks for reporting this. We'll include a fix in the coming releases.

**Comment by Haegin** [comment]
I'm also seeing this problem on the Postman 4.6.2 Mac app on OS X. The bug only seems to affect the URL fields.

![postman bug](https://cloud.githubusercontent.com/assets/124099/18205769/d890fc5e-70f1-11e6-914b-7ae2b3d58607.gif)

**Comment by vegetableman** [comment]
@Haegin @samcook Thanks for reporting this :+1: . This has been finally fixed in our internal build and will be part of the next release.

**Comment by vegetableman** [comment]
The issue has been fixed on the latest version `4.7.2`. Check it out.
