### ISSUE TITLE
[FRONT BUG] Post Params Shown In The URL

### ISSUE THREAD

**Issue by benjaminaudet** [a85/POSTMan-Chrome-Extension#2237]
1. Postman Version: **4.4.3**
2. App (Chrome app or Mac app): **Chrome App**
3. OS details: **Windows 7 Pro**
4. Is the Interceptor on and enabled in the app: **No**
5. Did you encounter this recently, or has this bug always been there: **Always**
6. Expected behaviour: **When you set params in "POST" mode, the params are shown in the URL**
7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
8. Screenshots (if applicable)
   http://image.prntscr.com/image/398167b476f64a408fcb9ac173089ad0.png

**Comment by sdnts** [comment]
Hey @benjaminaudet The parameters you are trying to set are in fact URL parameters and are supposed to show up in the URL.
If you're trying to set POST body parameters, try the Body tab right below the URL bar and set them there :)

**Comment by benjaminaudet** [comment]
Hey ! Thanks you, it wasn't very clear for us.

Thanks again for the fast response
