### ISSUE TITLE
Oauth 1.0 prevents additional parameters from being added to POST

### ISSUE THREAD

**Issue by JBrace1990** [a85/POSTMan-Chrome-Extension#2239]
1. Postman Version:4.4.3 win / x86-32 Chrome 51.0.2704.103
2. App (Chrome app or Mac app): Chrome app
3. OS details: Windows 10
4. Is the Interceptor on and enabled in the app: No
5. Did you encounter this recently, or has this bug always been there: Recently, but only due to OAuth implementation
6. Expected behaviour: 
7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
8. Screenshots (if applicable)

1. Setup OAuth 1 authorization
2. Add fields to body
3. Send request using form-data
4. Additional fields will be removed and not sent to the server

Workaround:
Instead of using form-data, use x-www-form-urlencoded

**Comment by sdnts** [comment]
@JBrace1990 Are you still seeing this in the latest version (4.8)?

**Comment by shamasis** [comment]
@madebysid or anyone else, can this be reproduced?

**Comment by sdnts** [comment]
@JBrace1990 Closing this. Please feel free to reopen if you're still seeing this with the latest version (4.10.2)
