### ISSUE TITLE
PM does not send cookies if Origin is set 

### ISSUE THREAD

**Issue by c3cris** [a85/POSTMan-Chrome-Extension#2241]
1. Postman Version: 4.4.3
2. App (Chrome app or Mac app): Chrome APP
3. OS details: OSX 10.11.6
4. Is the Interceptor on and enabled in the app: On and Enabled
5. Did you encounter this recently, or has this bug always been there: Recently
6. Expected behaviour:  Cookie header should always be sent
7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app): None
8. Screenshots (if applicable)

If `Send Postman Token Header` is turned on in postman Settings:
Send a Get request with the following headers.
- User-Agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36
- Accept:text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,_/_;q=0.8
- Accept-Encoding:gzip, deflate, sdch, br
- Accept-Language:en-US,en;q=0.8
- Cookie:session={{session}} //some random cookie

**Update** I found out that if i don't send `Accept` header the `Cookie` will send. Any value added to `Accept` header will stop `Cookie` header even if i send Origin.

On the server end print the request, in my example I used php:

```
<?php 
      var_dump(getallheaders());
?>
```

Output:

```
....(other elements)
 ["Cookie"]=>
  string(106) "session=7c47r2b8aauckkks4tdehf95b0;"
...(more headers)
```

Step 2: 
Now for the same request add Origin in the header preferably a valid Origin.
Hitting the same script you will see PostMan did don't send the Cookie header.

**NOTE:** This will be inversed if If `Send Postman Token Header` is turned **Off**
Now it won't send cookies if Origin isn't provided.

**Comment by c3cris** [comment]
Can anyone confirm this? It lead to a waste of several hours until I saw that it wasn't something on our end but Postman.

**Comment by a85** [comment]
@c3cris Looking into this.
@shamasis Tied to the runtime?

**Comment by shamasis** [comment]
It's reported to be in version 4.4.3 of chrome app @a85

**Comment by a85** [comment]
Ah. Let's check for this in the new version then.

**Comment by sdnts** [comment]
@c3cris Can you try updating to the latest version (4.7) on the native app and verify if this is fixed?

**Comment by c3cris** [comment]
I haven't had time to test it. I can try it this weekend, I apologize.

**Comment by c3cris** [comment]
It's still happening in 4.8...
With Origin ( does not work, no cookie sent)
![screen shot 2016-10-17 at 4 17 51 am](https://cloud.githubusercontent.com/assets/1042198/19435718/0bd01486-9421-11e6-9cc7-ec27ccfcdc5e.png)
With out Origin:  (works)
![screen shot 2016-10-17 at 4 18 00 am](https://cloud.githubusercontent.com/assets/1042198/19435717/0bbb6432-9421-11e6-92b6-f0d56239166d.png)

@SamvelRaja
