### ISSUE TITLE
Postman not using proxy authentication from Chrome

### ISSUE THREAD

**Issue by vilu** [a85/POSTMan-Chrome-Extension#2242]
I believe this has changed with the latest Chrome update, Postman have stopped using the proxy authentication from Chrome. Before I used to do postman requests to a service like this.
1. HTTP request to service resulting in 407
2. Open Chrome do get request to same url, resulting in a proxy authentication popup which I filled in and submitted.
3. Now I can make postman requests.

This has now stopped working and I will reach the service in Chrome but in Postman I still get 407s.
1. Postman Version:
   4.4.3
   Chrome 52.0.2743.116
2. App (Chrome app or Mac app):
   Chrome App
3. OS details:
   OS X : 10.11.5 (15F34)
4. Is the Interceptor on and enabled in the app:
   No
5. Did you encounter this recently, or has this bug always been there:
   Things seem to have changed with the latest chrome updates. 
6. Expected behaviour:
   Use Chromes settings for proxy authentication
7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):

```
extensions::platformApp:17 window.localStorage is not available in packaged apps. Use chrome.storage.local instead.(anonymous function) @ extensions::platformApp:17
extensions::platformApp:17 beforeunload is not available in packaged apps.(anonymous function) @ extensions::platformApp:17
extensions::platformApp:17 unload is not available in packaged apps.(anonymous function) @ extensions::platformApp:17
requester.js:236125 GET http://{URL} 407 (Proxy Authentication Required)
```
1. Screenshots (if applicable)

**Comment by mschinca** [comment]
I ran into the same issue

**Comment by Rasumichin** [comment]
I observe the same problem on my company notebook running Windows 7.
Chrome Version 52.0.2743.82 m (64-bit)
Postman 4.7.1 (win / x86-64)

Here a screenshot from the developer tools:
![postman-proxy-problem](https://cloud.githubusercontent.com/assets/1571623/18589815/af4a6d76-7c2c-11e6-8567-f845905e582a.png)

A solution would be really appreciated.

**Comment by ashishkp** [comment]
I am also facing same issue - any solution would be highly appreciated.

**Comment by vilu** [comment]
Any updates here? I could temporarily fix it by using the Chrome interceptor, not really working anymore now.

**Comment by vegetableman** [comment]
@vilu We are looking in to it. Will get back to you.

**Comment by vegetableman** [comment]
The issue seems to be caused by security patches made for chrome 52.0.2743.82. As of now, using chrome interceptor is the only way to work around authenticated proxy woes. 
Also, I have posted my query on the relevant forums for this issue. Will keep you guys posted.

**Comment by vegetableman** [comment]
An Update:-

Got in touch with the chrome dev team, the proxy issue is a side-effect of the security fix for this bug :- https://bugs.chromium.org/p/chromium/issues/detail?id=291417

Solutions:-
- You would have to turn on the interceptor to make proxy-authenticated requests, so that it has the same request context as that of the browser.
- The native app supports proxy authentication (check gif below).

![proxy-auth-native](https://cloud.githubusercontent.com/assets/1330851/19229048/2d913782-8ee8-11e6-8b1b-56cf5c6365c7.gif)

Currently, the ui is not intuitive enough for the use-case but we will update it 😊

**Comment by dominhhai** [comment]
Not working on Chrome `54.0.2840.71` too.
Any update?

**Comment by jeffwesson** [comment]
The workaround noted in the gif above is no longer working for me on Chrome 55.0.2883.95 (64-bit)

**Comment by marceloavan** [comment]
same issue here

**Comment by jreim** [comment]
I am having the same issue with a new install of post man. I try to do a get and hit a proxy authentication issue. I could not find where to set up the proxy. I am trying the interceptor.

**Comment by johntiror** [comment]
From today I'm also facing this issue from my company network. (Chrome Version 56.0.2924.87 (64-bit)).
The proxy auth workaround it's working, but not the interceptor (that I'd prefer to use), but maybe I'm doing something wrong. I turned on the interceptor in chrome, what do I need to do inside postman?
Thanks

**Comment by vegetableman** [comment]
@johntiror You need to first authorise yourself to the proxy server through the chrome browser (a dialog for username and password would appear) and after that, the chrome app (Postman) will pass the header for subsequent requests (the interceptor needs to be turned on).

**Comment by johntiror** [comment]
Thanks very much, but I'm currently using Chrome with no issue (no dialog), maybe I need to trigger the dialog in some way?

**Comment by emaborsa** [comment]
I have to call a service which requires Basic Auth. I'm behind a proxy which does not require authentication, but get 407 Error. Chrome Version 57.0.2987.98 (64-bit). Postman Version 4.10.3 win32 10.0.14393 / x64.

**Comment by sdnts** [comment]
@emaborsa Looks like your API is returning that error. Maybe the API itself requires auth?

**Comment by emaborsa** [comment]
@madebysid Yes, the API requires Auth0. I Send the crendentials using 'Authorization' header, but the Proxy blocks the request.

**Comment by henriquedesousa** [comment]
The workdaround in https://github.com/postmanlabs/postman-app-support/issues/2242#issuecomment-252550883 is not working, for some reasons postman-app is stripping the `Proxy-Authorization` header. Why?!

**Comment by chnouman** [comment]
check proxy browser you may have any proxy browser running mine was zenmate.

**Comment by sdnts** [comment]
Guys, can you try updating to 5.2.0? Native apps now support configuring a custom proxy for all requests made through the app. You should be able to set a custom proxy by heading over to `Settings > Proxy` and get this working.

Do note that this is only possible on the [native apps](https://getpostman.com/apps), not on the Chrome app, as there is no support for this on the chrome platform.

**Comment by we2seek** [comment]
Hi everyone! I just switched to native app v5.3.2 and noticed it doesn't respects to system proxy configuration. Unfortunately, I can't setup proxy manually (and do not wont) because of my proxy use authentication. Please, provide me, where I fail? )

**Comment by ioneyed** [comment]
Utilizing the v5.3.2 it prompts me to signin. This signin prevents the ability to adjust the proxy preferences. There use to be a "take me to the app" without a signin however it only gives me the "Cancel and take me to signed in account". When debugging the issues within the Dev Tools I noticed that regardless of how many times I `clear cache` or `delete browser data` in chrome I always see the following error `407 Proxy Authentication Required (from disk cache)`. I have done restarts, reboots of the local squid proxy, hard codes into the system proxy for the authentication and nothing gets me past this screen.

MacBook Pro OSX (10.11.6)
Postman v5.3.2
Chrome: Version 62.0.3202.94 (Official Build) (64-bit)
