### ISSUE TITLE
Windows Client - postman.clearEnvironmentVariables(); does not function correctly

### ISSUE THREAD

**Issue by PFarrell89** [a85/POSTMan-Chrome-Extension#2243]
**1. Postman Version:** win32 10.0.10586 / x64
 **2. App (Chrome app or Mac app):** Windows Client
 **3. OS details:** Windows 10 Professional 64 Bit
 **4. Is the Interceptor on and enabled in the app:** No
 **5. Did you encounter this recently, or has this bug always been there:** This function works fine in the Chrome application.
 **6. Expected behaviour:** This should clear all environment variables created in that environment.

**Steps To Reproduce:**
1. Open the Windows Postman Client.
2. Run a couple of requests that use the "postman.setEnvironmentVariable("name", value);" function.
3. Run a request that contains the "postman.clearEnvironmentVariables();" function.
4.  Click the 'Eye' icon next to the Environment dropdown to view current environment variables.
5. Notice that none of the variables have been deleted.
6. Run the same steps using the Chrome application.

**Comment by shamasis** [comment]
We've identified and addressed the issue. It's going out in next release which is tentatively v4.6 on Mac, scheduled for today. Would love if anyone can confirm this once the update is received.

**Comment by shamasis** [comment]
This should be resolved now. Closing. Please reopen if otherwise.
