### ISSUE TITLE
Cancel request doesn't cancel in Postman Canary

### ISSUE THREAD

**Issue by dannyfallon** [a85/POSTMan-Chrome-Extension#2244]
1. Postman Version: 4.4.3-canary.1
2. App (Chrome app or Mac app): Mac App
3. OS details: 10.11.6
4. Is the Interceptor on and enabled in the app: No
5. Did you encounter this recently, or has this bug always been there: Recently, not sure if always
6. Expected behaviour: Cancel the request
7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
8. Screenshots (if applicable)

Keep watching after the second request succeeds (for about another 5 seconds)

![postman-please-stop](https://cloud.githubusercontent.com/assets/1104475/17551619/16d4cf4c-5ef3-11e6-80e4-86082c0fa159.gif)

I cancelled the request after ~5 seconds and then changed to another environment before sending it again. While the second request succeeded and the result is displayed it gets overwritten by the result from the first request when it comes back (in this case it's a 504 Gateway Timeout nginx error. Clicking cancel should actually cancel the request, close the connection and stop listening for a response.

**Comment by numaanashraf** [comment]
@dannyfallon Thanks for reporting this. This will be fixed in the coming release.

**Comment by numaanashraf** [comment]
@dannyfallon This is fixed in versions 4.5.1 and up.
