### ISSUE TITLE
New Request is overwritten by opening Saved Request

### ISSUE THREAD

**Issue by monkpit** [a85/POSTMan-Chrome-Extension#2245]
### Version/App Information:
1. Postman 4.4.3
2. Chrome app / Chrome 51
3. Mac OSX 10.11.6
4. Interceptor on and enabled: no
5. Bug has always been there since I've used Postman
6. Expected behavior: when I open a new request tab in Postman and make changes, these changes should persist if I click on a saved request. The saved request should open in its own tab.
### Steps to reproduce issue:
1. Open postman and open a new Request tab. Ensure your Postman session has at least 1 saved request that can be loaded later.
2. Ensure all other tabs are closed.
3. Edit the URL for the new Request, but do not hit save (maybe you need to refer to another request that you already wrote)
4. Click on a saved request (we check another request to copy/paste something or whatever)
5. _Issue_ The new Request is overwritten by the saved request in the same tab.
### Proposed solution:

As soon as a new Request tab is opened, consider it dirty (orange tab icon) if any fields are changed.

I'm aware that there are workarounds to avoid this issue by changing the way I interact with Postman. For example, if I wish to copy/paste from another request, edit the other request and do a "save as" - however I'll end up hitting "save" by reflex, and run into a similar issue. Or, more simply, I could just click "Save" every time I open a new Request editor tab - that's the simplest workaround, but that's not intuitive to me.

The workflow I describe in the steps to reproduce this issue is something my lizard brain expects to be able to do based upon my mental model of every other editor I use on a daily basis. So, I constantly revert back to this workflow and I lose my work.

**Comment by aditikul** [comment]
@monkpit Totally understand your issue. And also how critical it is to your workflow. We are aware of this and have already started looking at some solutions. Will update this thread when we push a fix for this. Thanks for reporting! Stay tuned for updates.

**Comment by monkpit** [comment]
@aditikul thanks for the quick response!

**Comment by SamvelRaja** [comment]
This has been released in our latest 5.2 version of the kindly update it to get it  😄
