### ISSUE TITLE
X-Amz-Security-Token header's global variable reference value gets replaced with the actual value when the AWS Auth is made

### ISSUE THREAD

**Issue by nwayve** [a85/POSTMan-Chrome-Extension#2246]
Version/App Information:
1. Postman Version: **4.4.3**
2. App (Chrome app or Mac app): **Chrome 52.0.2743.116**
3. OS details: **win / x86-32 (Windows 10 Pro OS Build 14393.51)**
4. Is the Interceptor on and enabled in the app: **Yes**
5. Did you encounter this recently, or has this bug always been there: **Unknown**
6. Expected behaviour: 
   When sending an AWS Auth request, when there is a header for `"X-Amz-Security-Token"` with a value that references the global variable `{{aws_security_token}}`, I expect the variable reference to not get replaced with the actual value set in that variable.

Steps to reproduce the problem:
1. Have an API Gateway in AWS with an endpoint that has its Authorization set to `AWS_IAM`
2. Create a Postman request to hit this endpoint
3. Get temporary STS credentials that have access to this endpoint.
4. Set up the Authorization Type in Postman to AWS Signature and set the AccessKey and SecretKey to access the endpoint with the ones received from getting the STS credentials.
5. Create a Global Variable called `aws_security_token` and set its value to the security token received from the STS credentials
6. Add a header to the request: `"X-Amz-Security-Token": {{aws_security_token}}`
7. Make the request
8. The request should succeed but the value for the security token header has now been replaced with the actual value.

This is somewhat inconvenient because I have to make sure I don't accidently update the request after it gets made, and when the STS credentials expire, I then have to replace the value with the global variable reference again (usually by just closing the request without saving and reopening it).
I want this to be a global variable because I have another postman request that gets the STS creds and saves the values to those global variables.

**Comment by shamasis** [comment]
This should be resolved now - mac v4.6. Closing. Please reopen if otherwise.
