### ISSUE TITLE
[Feature Request] Reusable test functions 

### ISSUE THREAD

**Issue by DaleLJefferson** [a85/POSTMan-Chrome-Extension#2247]
Every single one of my tests has the same boilerplate code at the top. 

_Status is 200, has etag header, gzip header etc._

It would be great to be able to wrap this up in a function. 

```
runCommonTests()
```

**Comment by glspdotnet** [comment]
Hi @DaleJefferson! I know this isn't ideal, but you could try saving your test code (with or without minification) as a global variable and eval()-ing it at the start of your tests. Not the cleanest way of sharing boilerplate code, to be sure, but at least you only have to change it in one place when it _does_ have to be updated!

**Comment by shermes** [comment]
Would also like to see this feature

**Comment by hkgill** [comment]
+1

**Comment by a85** [comment]
@shamasis Same issue as #882

**Comment by shamasis** [comment]
Hello everyone, how about being able to add test and prerequest scripts to a folder, which runs upon sending any request under that folder (or collection)?

**Comment by mthoreso** [comment]
@shamasis I believe the issue here (and in [Issue #882 ](https://github.com/postmanlabs/postman-app-support/issues/882)) is that a lot of people want to use Postman/Newman and also want some programmatic flexibility to create and re-use code.  The suggestion to add scripts to a folder which runs upon any request under that folder/collection is too rigid.  Not all requests in the folder may need the script.  

I don't want to use frisby.js because other QAs in my org will likely be scared of it.  I want a lot of the flexibility that frisby.js offers me to be available in Postman/Newman.  

You guys are doing awesome work by the way :)

**Comment by shamasis** [comment]
There are two things we think we should do:
1. Common scripts in folders
2. A global scripts section that can be referred from any folder or request.

These two combined should address script re use issue.

**Comment by mthoreso** [comment]
Awesome!

**Comment by smalekzadeh** [comment]
any progress on script re use?

**Comment by westphalen** [comment]
+1 Common scripts for all elements in my Collection and/or folders.

**Comment by Dkstu** [comment]
+1 Common scripts for all elements in my Collection and/or folders.

**Comment by deanmoses** [comment]
+1 Common scripts for all elements in my Collection and/or folders.

**Comment by gauravshetti** [comment]
+1 Need that badly

**Comment by barnesm999** [comment]
+1 Proper script re-usability  prevents Postman from being a full fledged testing tool.

**Comment by carl-parrish** [comment]
+1

**Comment by ShawnBuckley** [comment]
+1

**Comment by hdushan** [comment]
+1

**Comment by shinusuresh** [comment]
+1

**Comment by shubhamj-cuelogic** [comment]
I am looking for same. It will be a great feature if we have that functionality

**Comment by kkoston** [comment]
+1

**Comment by leozilla** [comment]
+1

**Comment by seekingua** [comment]
+1

**Comment by IvanVasilko** [comment]
+1

**Comment by medvednic** [comment]
+1

**Comment by jonpcunanan** [comment]
+1

**Comment by snipebin** [comment]
+1

**Comment by ameyvaert** [comment]
+1

**Comment by zedbahn** [comment]
+1

**Comment by AdrianoLRibeiro** [comment]
+1

**Comment by ssparasuram** [comment]
+1
I was duplicating more codes.Please help me to solve that duplication.

**Comment by cakirpro** [comment]
+1

**Comment by a85** [comment]
Collection level scripts (pre-request, test) scripts are available in version 5.4+. Docs to follow soon!

**Comment by yeugeneu** [comment]
+1

**Comment by matthisk** [comment]
Seems like collection level scripts can only be used to share literal values between requests. Not to share functions, is that correct?

**Comment by jonpcunanan** [comment]
I found this from another forum.  You can do a hack and set a function as a global variable like this.

postman.setGlobalVariable("commonTests", (testsInput) => { .. }

For our requests we have to request an auth token first so I'll set this commonTests function in the pre-request scripts.

Call this from your request test 

eval(globals.commonTests)();
