### ISSUE TITLE
[Feature Request] - On disk editing

### ISSUE THREAD

**Issue by DaleLJefferson** [a85/POSTMan-Chrome-Extension#2248]
Currently our workflow is import collection from Git, edit collection export collection, commit changes. 

It would be great to be able to open a file, and when you save the changes, they are saved to the file like a normal editor.

**Comment by kbatyai** [comment]
Would be great to work on collections saved to normal files... (stored in on-prem GIT)

**Comment by sdnts** [comment]
@DaleJefferson @kbatyai We're working on integrations between Postman Collections and GitHub, which will be out very soon. I'll keep you guys updated here.
That should help you out :)

**Comment by kbatyai** [comment]
@madebysid direct(-only)-GitHub or pure Git? The two is not the same.

I understand your business needs with forcing monthly-cloud-things, but in lot of cases it's not an option, contrariwise on-prem-isolated-source-control integration needed for daily work and workflows...

**Comment by philreindl** [comment]
Any progress on this?  
I'm not using github, and would love to be able to use newman as part of the build automated testing.  Current workflow is too cumbersome.

Thanks

**Comment by a85** [comment]
File based flows are not part of our immediate roadmap. I'll update this roadmap as things change. You can use the import/export feature or our Github/Gitlab integrations to switch between IDEs and Postman.

**Comment by andimueller** [comment]
It would be great if this feature request would be opened again. 
It is quite impractical to save a collection via export. We do not use Github/Gitlab. We have our own Git Repository and are not interested in saving our tests on external repositories / servers.

Thanks in advance!

**Comment by hungchu0912** [comment]
Hi, is there any update on this feature? Such a shame that a basic function cannot be supported in big product like postman
