### ISSUE TITLE
Cookie path not being set - postman 4.5.1 Mac app

### ISSUE THREAD

**Issue by nevster** [a85/POSTMan-Chrome-Extension#2249]
1. Postman Version: 4.5.1
2. App (Chrome app or Mac app): Mac app
3. OS details: 10.11.6
4. Is the Interceptor on and enabled in the app: N/A
5. Did you encounter this recently, or has this bug always been there: recently after auto update this morning
6. Expected behaviour: cookie path should be set correctly
7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
8. Screenshots (if applicable)

Steps to reproduce the problem:
Making a call that returns a cookie like this in the response headers:
Set-Cookie:"mycookiename=irrelevant; max-age=86400; path=/; Expires=Fri, 12 Aug 2016 07:25:23 GMT"

Headers tab shows above line for Set-Cookie
Cookies tab shows cookie but path is blank

Click on Manage cookies and it shows a cookie like this:
mycookiename=irrelevant; max-age=86400; path=/api/v1/simulators/authenticator; domain=localhost;

That path is the path of the rest call. We've tried setting the path to other things like /fred and still get the same results.

**Comment by shamasis** [comment]
We've identified and addressed the issue. It's going out in next release which is tentatively v4.6 on Mac, scheduled for today. Would love if anyone can confirm this once the update is received.

**Comment by shamasis** [comment]
This should be resolved now. Closing. Please reopen if otherwise.

**Comment by nevster** [comment]
I can confirm it's all working now. Thanks @shamasis!
