### ISSUE TITLE
Select "text" response format when response is text/csv

### ISSUE THREAD

**Issue by aromanet42** [a85/POSTMan-Chrome-Extension#2250]
1. Postman Version: 4.4.3
2. App (Chrome app or Mac app): Chrome App
3. OS details: Linux Mint
4. Is the Interceptor on and enabled in the app: no
5. Did you encounter this recently, or has this bug always been there: always been there
6. Expected behaviour: I would like Postman to use the "Content-Type" Response header to choose the response display format

Steps to reproduce the problem:
- build an API which returns CSV data.
- one of the CSV line contains html char. For example, my CSV returned is: 

```
    code;label;description
    3010104;<0-3 !>;this is a description
```
- call the API in Postman with Accept header set to "text/csv"
- Postman thinks that the response is HTML and tries to interpret it. It displays the following result:

```
    code;label;description
    3010104;
    <0-3 !>;this is a description
```

I have to manually change the "result display format" to "Text" to have the correct display.

**Comment by numaanashraf** [comment]
@aromanet42 Thanks for reporting this. We are looking into the issue and should have a fix out soon.

**Comment by vegetableman** [comment]
@aromanet42 Can you try updating to the latest version (4.8) and check if this is fixed?

**Comment by aromanet42** [comment]
Hello Vignesh,

This is what I see in the "about" view of my Postman app:

4.8.1
linux / x86-64
Chrome 51.0.2704.103

But it still doesn't work :/

2016-10-15 6:44 GMT+02:00 Vignesh Anand notifications@github.com:

**Comment by vegetableman** [comment]
@aromanet42 Could you verify if the issue still exists in the recent release `4.8.3` ^_^.

**Comment by vegetableman** [comment]
@aromanet42 Closing this issue. Feel free to reopen if the issue still exists ^_^.

**Comment by aromanet42** [comment]
@vegetableman Looks like it's working now, thanks!

**Comment by liam-hitchcock-dev** [comment]
Currently this issue is showing up again on postman v5.3.2: 'expected the response type to be 'text' but got 'text/csv'
Is there any chance to get this issue looked at again?
