### ISSUE TITLE
Postman sends two requests for POST request with formdata

### ISSUE THREAD

**Issue by aimfeld** [a85/POSTMan-Chrome-Extension#2251]
It seems that Postman sends two requests for the following POST request. The request sends a json file and an XML file and returns a PDF file:

```
{
    "name": "POST /assessments?action=reevaluation",
    "request": {
        "auth": {
            "type": "basic",
            "basic": {
                "username": "{{username}}",
                "password": "{{password}}",
                "saveHelperData": true,
                "showPassword": false
            }
        },
        "url": "{{baseUrl}}/assessments?action=reevaluation",
        "method": "POST",
        "header": [
            {
                "key": "Accept",
                "value": "application/vnd.tp.sdbb.ch.v1+pdf",
                "description": ""
            },
            {
                "key": "Authorization",
                "value": "REMOVED",
                "description": ""
            }
        ],
        "body": {
            "mode": "formdata",
            "formdata": [
                {
                    "key": "blackbox",
                    "value": "zsb-blackbox-2.0.json",
                    "type": "file"
                },
                {
                    "key": "assessmentConfiguration",
                    "value": "assessment-zsb.xml",
                    "type": "file"
                }
            ]
        },
        "description": ""
    },
    "response": []
}
```

Version/App Information:
1. Postman Version: 4.4.3
2. App (Chrome app or Mac app): Chrome app (Chrome 52.0.2743.116)
3. OS details: Windows 10
4. Is the Interceptor on and enabled in the app: Don't know
5. Did you encounter this recently, or has this bug always been there: Recently, bug may have existed before
6. Expected behaviour: Only one request is sent
7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
8. Screenshots (if applicable)

**Comment by numaanashraf** [comment]
Can you check whether this has been resolved in our Windows Native client? http://www.getpostman.com/apps

**Comment by aimfeld** [comment]
I have just tested with the Windows Native Client (4.6.2, win / x86-32, Chrome 52.0.2743.116). The problem did occur with the above request. I also tested another POST request without form-data, it got sent only once as expected.
