### ISSUE TITLE
Referring to Environmental Variables in test doesn't work

### ISSUE THREAD

**Issue by EpicNuts** [a85/POSTMan-Chrome-Extension#2254]
1. Postman Version: 4.4.3
2. App Chrome app or Mac app): Chrome App
3. OS details: Ubuntu 16.04
4. Is the Interceptor on and enabled in the app: off
5. Did you encounter this recently, or has this bug always been there: recently
6. Expected behaviour: I should be able to refer to a stored variable in the test case.
7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
8. Screenshots (if applicable)
   ![screenshot from 2016-08-11 11-55-47](https://cloud.githubusercontent.com/assets/3577690/17585318/530f572a-5fbb-11e6-909a-ed26f71e6720.png)
   

As you can see in the attached image, the response.namespace is defined explicitly as "default, and the test passes because the response does indeed have "default" as the value. If I change the test to say:

tests["namespace in Response"] = response.namespace == "{{namespace}}";

...the test will fail. The same goes for the DeviceName and vin. The responses are all correct, but unless they are specified explicitly in the tests, the tests fail.

**Comment by abhijitkane** [comment]
@EpicNuts You'll need to use `environment.variableName` to refer to the variable in test scripts.

```
tests["namespace in Response"] = response.namespace == environment.namespace;
```

Relevant docs are at https://www.getpostman.com/docs/sandbox

**Comment by EpicNuts** [comment]
@abhijitkane Many thanks for the fast response! Out of curiosity, has this always been the case, or was this a recent change? I could have sworn I was calling back localEnv variables in the test area before...

Anyway, thanks again :)

**Comment by abhijitkane** [comment]
Nope, this has always been this way :)

The {{variableName}} syntax is for URLs, headers, and the request body only.
