### ISSUE TITLE
Proxy-Authorization header is never sent

### ISSUE THREAD

**Issue by allapaj** [a85/POSTMan-Chrome-Extension#2255]
Hello,

The "Proxy-Authorization" header is stripped from every request I try to send. Here's my app info:

Version 4.4.3
win / x86-32
Chrome 52.0.2743.116

Here's a sample request I captured with the header missing:

```
POST http://localhost:9030/ HTTP/1.1
Host: localhost:9030
Proxy-Connection: keep-alive
Content-Length: 21
Cache-Control: no-cache
Origin: chrome-extension://fhbjgbiflinjbdggehcddcbncdddomop
Content-Type: application/json
User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36
Postman-Token: 930c80f3-e16c-b9dd-15c4-6fb133321394
Accept: */*
Accept-Encoding: gzip, deflate
Accept-Language: en-GB,en-US;q=0.8,en;q=0.6

{
    "rawr": "rar"
}
```

These are the headers I was expecting it to send:

```
Proxy-Authorization:OTP 1234
Content-Type:application/json
```

**Comment by abhijitkane** [comment]
@allapaj Proxy-Authorization is a restricted header, which the Chrome app is unable to send. We'll add a warning for this soon. We have a native Windows app (http://getpostman.com/apps) which does not have this restriction.

**Comment by allapaj** [comment]
Is this a restriction with Chrome apps? I tried using Advanced Rest Client, and it didn't seem to have the problem.

**Comment by shamasis** [comment]
@allapaj - we use native XHR in chrome app. That has restricted headers. If we use underlying chrome TCP API this can be fixed. We haven't researched full stability around that API yet. We are looking into developing something around this and we will keep you posted.

Meanwhile, please use one of our native clients.

**Comment by numaanashraf** [comment]
Closing this issue since this falls under the bigger umbrella of switching to TCP based request method inside Chrome.
