### ISSUE TITLE
OAuth 1.0 requests returning "Service temporary unavailable"

### ISSUE THREAD

**Issue by jaredhanks** [a85/POSTMan-Chrome-Extension#2257]
1. Postman Version: 4.5.1
2. App (Chrome app or Mac app): Mac app
3. OS details: OS X 10.11.6
4. Is the Interceptor on and enabled in the app: Yes
5. Did you encounter this recently, or has this bug always been there:  Recent (works in 4.4.3 Chrome App just fine).
6. Expected behavior: Return an xml response.
7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
8. Screenshots (if applicable)

When using OAuth 1.0 I'm getting an 500 error with "Service temporary unavailable" (side note: is that a typo? should "temporarily"?).  I'm hitting a Magento endpoint, in case that helps at all.

I can run the same thing from command line via cURL and get the proper response.  I can also use the Chrome app (v 4.4.3) and it works just fine.

**Comment by jaredhanks** [comment]
Just upgraded to 4.6.1 Mac app and it appears the issue has been resolved.

**Comment by abhijitkane** [comment]
@jaredhanks Great! There was a cookie-related issue which might have been causing this. Feel free to re-open if you see this behavior again.
