### ISSUE TITLE
Allow to download older postman versions.

### ISSUE THREAD

**Issue by q42jaap** [a85/POSTMan-Chrome-Extension#2260]
Didn't know where to put this, feel free to close or do whatever.

The website should have an archive page (just hide it in the footer) where we can download older postman builds. Since it's a zip file, this should be super easy. 4.6.0 being broken with cookies, just reinstall 4.5.x and there's a workaround...

**Comment by shamasis** [comment]
While that's something to look into, can you check your cookie issues are addresses? 😜

**Comment by q42jaap** [comment]
Aaah, I forgot to respond, yeah I think they're fixed now.

**Comment by shamasis** [comment]
@aditikul the thoughts on the original issue posted here?

**Comment by a85** [comment]
@shamasis Can we do this with our release server? Thinking we can have one older version as a back up.

**Comment by kunagpal** [comment]
@a85 For the record, this is currently possible.

**Comment by SonofNun15** [comment]
Having an issue with 4.10.0. At the moment it is hard to even diagnose exactly what the problem is. Would like to fallback to 4.4.2 in the meantime, at least to compare. 👍 to the idea of making older versions accessible. Can't find 4.4.2 anywhere.

**Comment by SonofNun15** [comment]
Did get a copy from a coworker who had it archived.

**Comment by a85** [comment]
@numaanashraf We should list out the previous version of the app on the website. @kunagpal Possible right?

**Comment by kunagpal** [comment]
@a85 Yes, this should be fairly easy to do.

**Comment by oofpez** [comment]
I'd love to have this option.  With the current size of my environments, & collections, Postman easily takes over 4GB of memory when I start it up (and some actions can take over a minute for the UI to respond).
It used to be more manageable in previous versions.

**Comment by a85** [comment]
@oofpez We are constantly optimizing for memory and performance.

That said, older versions will be available for download through our website soon.

**Comment by bwaterm2** [comment]
Are older versions available for download through your site yet? I am unable to find anything but the current version.

**Comment by godfrzero** [comment]
@bwaterm2 You can check the changelog page: https://www.getpostman.com/apps#changelog-mac-app

Older versions are available for the Mac, Linux & Windows apps.

**Comment by bwaterm2** [comment]
@godfrzero Not sure how I missed that the first time I looked. Thanks so much!

**Comment by alewmt** [comment]
Two resent version is not enough. I submitted an issue https://github.com/postmanlabs/postman-app-support/issues/3980 which exists in all of them.

**Comment by timbkbasic** [comment]
You mention providing older versions for download, but they still do not appear to be available. Some of us out here (i.e., myself) are stuck on older Mac OS platforms (need to test there) and are unable to run Postman. Specifically, I need a version of Postman that will run on MacOS 10.8.5. Can anyone please tell me where to get a version of Postman that is compatible with MacOS 10.8.5?

**Comment by genachka** [comment]
Due to bug https://github.com/postmanlabs/postman-app-support/issues/3963 need to revert to previous version. How can I download 5.4.0? Can't believe it's been almost 2 years since this was asked and still not easily possible if even possible?

**Comment by SamvelRaja** [comment]
@genachka you can get it here https://www.getpostman.com/apps#changelog-mac-app

**Comment by timbkbasic** [comment]
Still need version compatible with MacOS 10.8.5. Nowhere to be found...

**Comment by numaanashraf** [comment]
@timbkbasic The minimum version we support for MacOS is 10.9. We recommend using our Chrome apps if you are on MacOS 10.8

**Comment by timbkbasic** [comment]
<minor rant>Modern operating systems are designed to allow support for previous OS versions rather easily, so I am quite surprised so many developers force an operating system upgrade for their software.</minor rant>

That said, there must be a version of Postman somewhere that will run on MacOS 10.8.5. I am assuming that the version worked at that time. All I need is a download. I am not looking for any support whatsoever. Just a download.

I cannot stress enough how absurd it is for one piece of software to force me to update my operating system! If I update to 10.9, numerous applications that I rely on every day will cease to function. I know I am a dinosaur, but years ago, as developers, we had respect for OS "ecosystems" and never felt that our software should force an update of the OS. In the rare case that it did, we always provided access to older versions that were compatible with previous OS versions.

**Comment by genachka** [comment]
@SamvelRaja thank you, but looks like that supports only the current and immediate previous. They updated today to 5.5.2 so the only other one I can grab is 5.5.0 leaving 5.4.0 not downloadable. :(

**Comment by tsvx** [comment]
@genachka Just for now, it seems that you can just replace the version in the "Download" url to the desired version and that's it. 5.4.0 is not available, but I've got 5.4.1 in this way.

**Comment by karol-depka** [comment]
Hi. Did you try to manually edit the download URL? I just managed to download from https://dl.pstmn.io/download/version/5.3.0/windows64 (which I edited from https://dl.pstmn.io/download/version/6.0.9/windows64 ) . Try editing the download url for Mac etc.

I found the url here: https://www.getpostman.com/apps#changelog-mac-app .

**Comment by sshushliapin** [comment]
It seems recent versions (starting from 6.1.4) can be downloaded via [Postman Apps page](https://www.getpostman.com/apps#changelog-windows-app).

**Comment by numaanashraf** [comment]
Please note that downgrading to older versions is not recommended can lead to data loss or the app not launching or working as expected due to incompatible formats of data stored locally.

**Comment by sshushliapin** [comment]
Yep, but #4952 brings much more harm IMHO.

**Comment by MelleKoning** [comment]
After downloaded recent version 7 the app shows a popup to upgrade team, and that popup does not go away. 
The sign-out button gives a scary warning that all collections are going to be deleted??

Searching a previous download (v6.7) as recommended in the popup, leads to a page where v7 can be downloaded. 
What gives?

**Comment by guillegr123** [comment]
@MelleKoning at the bottom of the page are the links. These are for the latest v6:
* https://go.pstmn.io/dl-macos64-v6-latest
* https://go.pstmn.io/dl-win64-v6-latest
* https://go.pstmn.io/dl-win32-v6-latest
* https://go.pstmn.io/dl-linux64-v6-latest
* https://go.pstmn.io/dl-linux32-v6-latest

**Comment by dineshbhagat** [comment]
https://dl.pstmn.io/download/version/10.9.4/osx64
