### ISSUE TITLE
Custom media types for request body content

### ISSUE THREAD

**Issue by travisspencer** [a85/POSTMan-Chrome-Extension#2261]
Postman should allow users to define custom media types. In this preference, a user should be able to:
- Define the media type with a friendly name (e.g., "Foo" has a media type of `application/vnd.foo`)
- The syntax of the body content of that media type (e.g., XML, JSON, HTML, etc.) which the request editor will later use to highlight and check the code.

When making a request with such preferences defined, these custom media types should show up in the request editor when making POST/PUT/PATCH/etc. requests and the `raw` option is selected for the request body. In such cases, the user-defined media types should be be shown in the drop-down menu under `Text`. The friendly name should be shown with the media type in parenthesis. The options should be sorted alphabetically in the user's current locale using the friendly names. After selecting a custom media type, the `Content-Type` header should be added as it is today with built-in media types but with the user's custom type.

Something similar to the following mockup:

![screen shot 2016-08-14 at 5 24 49 pm](https://cloud.githubusercontent.com/assets/2499235/17664366/ca05e6c4-62f3-11e6-8c95-a55cb9b028d8.png).

The target for this should be all versions of Postman

**Comment by DannyDainton** [comment]
Hey @travisspencer 

I appreciate it's been a while since this was raised but I'm just looking over the issue tracker to see what can be closed out.

There have been many changes to the platform since this was created as a feature request - Are we ok to close this request out now?

**Comment by travisspencer** [comment]
This kinda lack of functionality has made Postman unusable for me in the work I do on OAuth and OpenID Connect. So, we invented an alternative -- oauth.tools. When I can't use that for something unrelated to those spec, I use curl and curlie. As a result, I'm no longer a Postman user and am indifferent to the state of this ticket.
