### ISSUE TITLE
 Pressing ENTER in "DO YOU WANT TO SAVE?" pop-up ALWAYS saves.

### ISSUE THREAD

**Issue by jamesyarrington** [a85/POSTMan-Chrome-Extension#2262]
Version/App Information:
1. **Postman Version:** 4.4.3
2. **App (Chrome app or Mac app):** Chrome 52.0.2743.116
3. **OS details:** Windows 10
4. **Did you encounter this recently, or has this bug always been there:** Not sure, In the past (1-2 weeks?) I've noticed that I had changes that I didn't expect were saved when I opened a previously saved request.  I've only discovered the source this morning.
5. **Expected behaviour:**  If I press ENTER in the "DO YOU WANT TO SAVE?" pop-up, The selected (Blue-outlined) option should be performed.

Steps to reproduce the problem:
1. Create a collection.
2. Create a new request, and save it in that collection.
3. Make a change to the request.
4. Close the tab with the request.
5. Press ENTER with "Don't Save" highlighted.
6. Reopen the request and see that your changes were saved.

**Comment by sdnts** [comment]
Hey @jamesyarrington, The `Enter` key is supposed to be an alias for Save and Exit. You can use the Spacebar to actually perform what is outlined.
This is the default behaviour for all native apps.

**Comment by jamesyarrington** [comment]
Thanks for the quick response - `Spacebar` does work like I was expecting `Enter` to work..

**Comment by sdnts** [comment]
Awesome!
