### ISSUE TITLE
Broken encoding of UTF-8 query params

### ISSUE THREAD

**Issue by dchuiko** [a85/POSTMan-Chrome-Extension#2263]
1. Postman version: 4.6.0
2. Mac app
3. OS version: MacOS 10.11.6
4. No
5. Recently
6. Query parameters should be url encoded. Example url params: `?search=обязательный`, expected value on server: `?search=%D0%BE%D0%B1%D1%8F%D0%B7%D0%B0%D1%82%D0%B5%D0%BB%D1%8C%D0%BD%D1%8B%D0%B9`, got: `search=>1O70B5;L=K9`

**Comment by numaanashraf** [comment]
Able to reproduce. Working on a solution.

**Comment by czardoz** [comment]
This is a downstream bug in Node: nodejs/node#8321

**Comment by jschulenklopper** [comment]
Adding a confirmation / reproduction of this bug, and a difference between the Postman Chrome app and the Postman application on Mac OSX.
The Chrome app is able to request `GET /romanization/Москва/iso_9 HTTP/1.1` correctly to a Romanization service that I'm developing on localhost -- note the Cyrillic characters for the native spelling for Moscow.
The installed OSX Postman application throws an error message "Could not get any response" for the same request: `There was an error connecting to localhost:8080/romanization/%D0%9C%D0%BE%D1%81%D0%BA%D0%B2%D0%B0/iso_9`.

The URL encoding seems to be correct though. If I directly request `localhost:8080/romanization/%D0%9C%D0%BE%D1%81%D0%BA%D0%B2%D0%B0/iso_9` via Postman, there's no problem.

**Comment by chimit** [comment]
Confirm! Something has been changed last few months. Before this request had been working without problems:

```
GET {{url}}/tags/巴黎/photos
```

Now I have to select 巴黎, right-click and choose **EncodeURIComponent** to make it work as before. The request is changed to:

```
GET {{url}}/tags/%E5%B7%B4%E9%BB%8E/photos
```

Postman 4.7.0 for macOS (standalone).

**Comment by xxldoctor** [comment]
4.7.1
win32 10.0.10586 / x64

Postman convert lowercase cyrillic letter this way:
абвгдеёжзийклмнопрстуфхцчшщъыьэюя = 012345Q6789:;<=>?@ABCDEFGHIJKLMNO
in case of uppercase letters in URLparamerter request can throw different errors:
Letter from (АБВГДЕЁЖЗИЙКЛМНОП) = Could not get any response There was an error connecting to %requesturl%
Letter from (РХ) = Error: 500 
У = request lost following urlparameters
Ц = erase oll symbols after it (may by carret return?)
other letters convert this way:
СТФЧШЩЪЫЬЭЮЯ = !\"$'()\* ,-./

**Comment by czardoz** [comment]
This was fixed and released. Do re-open the issue if you're still having problems :)

**Comment by dmz9** [comment]
@czardoz still able to reproduce this bug
version 5.5.3@win7x64

![default](https://user-images.githubusercontent.com/19429896/37000194-abaf452c-20d3-11e8-82da-c99799a49b7b.png)

**Comment by gdomo** [comment]
Still able to reproduce
Postman 6.4.4
Ubuntu 18.04.1 LTS

http://{{host}}{{port}}/api/v3/queries/абвгдеёжзийклмнопрстуфхцчшщьыъэюяАБВГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧШЩЬЫЪЭЮЯ

turns in
GET /api/v3/queries/012345Q6789:;<=>?@ABCDEFGHILKJMNO !"#$%&'(),+*-./ HTTP/1.1


![image](https://user-images.githubusercontent.com/38424025/47425485-19ee1d80-d793-11e8-90eb-2bf668378fae.png)
