### ISSUE TITLE
Postman stopped working after upgrade to 4.6.0 today

### ISSUE THREAD

**Issue by gilesheron** [a85/POSTMan-Chrome-Extension#2264]
1. Postman Version:  4.6.0
2. App (Chrome app or Mac app):  Mac app
3. OS details: 10.11.6
4. Is the Interceptor on and enabled in the app:No
5. Did you encounter this recently, or has this bug always been there: Bug seems to have appeared with upgrade to 4.6.0
6. Expected behaviour: Requests get sent
7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
   # 
   
      o
   (/) P O S T M A N
   ^
   
   Go to View -> Show Postman Console to check your script logs. 
# 

requester.js:267366 Uncaught Error Uncaught Error: Could not call remote function ''. Check that the function signature is correct. Underlying error: Cookie has domain set to a public suffix
Error: Could not call remote function ''. Check that the function signature is correct. Underlying error: Cookie has domain set to a public suffix
    at callFunction (/Applications/Postman.app/Contents/Resources/electron.asar/browser/rpc-server.js:225:11)
    at EventEmitter.<anonymous> (/Applications/Postman.app/Contents/Resources/electron.asar/browser/rpc-server.js:306:5)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:201:7)
    at WebContents.<anonymous> (/Applications/Postman.app/Contents/Resources/electron.asar/browser/api/web-contents.js:218:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:191:7) /Applications/Postman.app/Contents/Resources/electron.asar/renderer/api/remote.js 176 7 Error: Could not call remote function ''. Check that the function signature is correct. Underlying error: Cookie has domain set to a public suffix(…)(anonymous function) @ requester.js:267366
/Applications/Postman.app/Contents/Resources/electron.asar/renderer/api/remote.js:176 Uncaught Error: Could not call remote function ''. Check that the function signature is correct. Underlying error: Cookie has domain set to a public suffix
Error: Could not call remote function ''. Check that the function signature is correct. Underlying error: Cookie has domain set to a public suffix
    at callFunction (/Applications/Postman.app/Contents/Resources/electron.asar/browser/rpc-server.js:225:11)
    at EventEmitter.<anonymous> (/Applications/Postman.app/Contents/Resources/electron.asar/browser/rpc-server.js:306:5)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:201:7)
    at WebContents.<anonymous> (/Applications/Postman.app/Contents/Resources/electron.asar/browser/api/web-contents.js:218:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:191:7)
1. Screenshots (if applicable)

access anything using Postman 4.6.0 on Mac.

if I delete all the cookies then postman sends something at last but authorization to my app fails.

this was all ok before the update to 4.6.0

**Comment by sdnts** [comment]
Hey @gilesheron, we've identified the error on our end. It is indeed an issue with our cookie management (as you suspected). We'll push a fix for it in the next couple of days.

**Comment by gilesheron** [comment]
ah - great.  thanks!   Unfortunately I have a customer demo tomorrow :(

is there a way to roll back by one release?

On 15 Aug 2016, at 16:15, Siddhant Sinha <notifications@github.com<mailto:notifications@github.com>> wrote:

Hey @gilesheronhttps://github.com/gilesheron, we've identified the error on our end. It is indeed an issue with our cookie management (as you suspected). We'll push a fix for it in the next couple of days.

**Comment by sdnts** [comment]
Can you drop in a mail at help@getpostman.com? We'll get you sorted.

**Comment by sdnts** [comment]
We pushed changes that should fix your issue. Can you update to the latest version (v4.6.1) and confirm?

**Comment by gilesheron** [comment]
Will check when I get home this evening.

On 15 Aug 2016, at 18:40, Siddhant Sinha <notifications@github.com<mailto:notifications@github.com>> wrote:

We pushed changes that should fix your issue. Can you update to the latest version (v4.6.1) and confirm if it is fixed?

##

**Comment by fodurrr** [comment]
Hi,

How can I get version 4.6.1?? I have the same isssue and I cannot get the latest corrected version.

Thanks

**Comment by abhijitkane** [comment]
@fodurrr `Settings > Update`, or `Postman > Check for Updates`

**Comment by fodurrr** [comment]
@abhijitkane Sounds strange but I cannot find update options in the setting menu and in the Chrome store there is still the version 4.6.0 not the newest 4.6.1.

**Comment by gilesheron** [comment]
Looks good to me :)

On 15 Aug 2016, at 18:40, Siddhant Sinha <notifications@github.com<mailto:notifications@github.com>> wrote:

We pushed changes that should fix your issue. Can you update to the latest version (v4.6.1) and confirm if it is fixed?

**Comment by fodurrr** [comment]
@gilesheron I checked the documentation as well I cannot update inside extension and I do not have the update menu in the app settings neither, see picture.
![image](https://cloud.githubusercontent.com/assets/10008597/17682255/506b3f2c-6342-11e6-91ba-67e4c6aea2c4.png)

Why I do not have the Update menu???
Please...

**Comment by gilesheron** [comment]
it’s under the “Postman” entry as “Check for Updates”.

On 15 Aug 2016, at 23:46, fodurrr <notifications@github.com<mailto:notifications@github.com>> wrote:

@gilesheronhttps://github.com/gilesheron I checked the documentation as well I cannot update inside extension and I do not have the settings menu in the app neither, see picture.
[image]https://cloud.githubusercontent.com/assets/10008597/17682255/506b3f2c-6342-11e6-91ba-67e4c6aea2c4.png

Why I do not have the Update menu???
Please...

**Comment by fodurrr** [comment]
I do not have postman entry neither, nor check for update, nothing
![image](https://cloud.githubusercontent.com/assets/10008597/17682442/85f07670-6343-11e6-951c-5c2a725ff6d9.png)

This drives me crazy today :((

**Comment by abhijitkane** [comment]
@fodurrr Looks like you have the Chrome app, not the Mac app. Can you attach a screenshot of the DevTools Console window (https://www.getpostman.com/docs/errors)?

**Comment by gilesheron** [comment]
are you on a Mac?  If so then the Postman entry ought to be top left (next to the apple icon).

On 15 Aug 2016, at 23:54, fodurrr <notifications@github.com<mailto:notifications@github.com>> wrote:

I do not have postman entry neither, nor check for update, nothing
[image]https://cloud.githubusercontent.com/assets/10008597/17682442/85f07670-6343-11e6-951c-5c2a725ff6d9.png

This drives me crazy today :((

**Comment by fodurrr** [comment]
Yes I am on windows, bad for me :)
I will check it tomorrow again, I gtg to sleep....

**Comment by fodurrr** [comment]
Thanks guys my problem was solved, it was not even related to Postman, sorry :(
