### ISSUE TITLE
Client certificate does not load from Mac keychain

### ISSUE THREAD

**Issue by bsreera** [a85/POSTMan-Chrome-Extension#2265]
1. Postman Version: 4.6.0
2. App (Chrome app or Mac app): Mac
3. OS details: OS X 15.5.0 / x64
4. Is the Interceptor on and enabled in the app: No
5. Did you encounter this recently, or has this bug always been there: Yes
6. Expected behaviour: Pick up cert from keychain while sending requests
7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app): 
8. Screenshots (if applicable)
   Could not get any response
   There was an error connecting to ******

Why this might have happened:
The server couldn't send a response:
Ensure that the backend is working properly
Self-signed SSL certificates are being blocked:
Fix this by turning off 'SSL certificate verification' in Settings > General
Client certificates are required for this server:
Fix this by adding client certificates in Settings > Certificates
Request timeout:
Change request timeout in Settings > General

**Comment by shamasis** [comment]
Postman Mac App does not use the Chrome keychain. Please use the "Settings -> Certificates" section.

![screenshot 2016-08-16 16 04 09](https://cloud.githubusercontent.com/assets/232373/17696331/2eaa001a-63cb-11e6-8fea-d76fd2a4c78d.png)

@abhijitkane @numaanashraf - we need to better highlight this in the app.

**Comment by bsreera** [comment]
I did use it but its not really working. I am confused about the usage.

I gave hostname as https://someserver
And gave link to the certificate.

I tried multiple combinations and all different formats for key and crt, none of them worked. 

Is there a document I should be referring for this?

**Comment by sdnts** [comment]
@bsreera The `host` field in the Certificates section needs just the host, without the protocol or ports. In your case, you would type in `someserver.com` instead of appending at https:// in front of it as you are doing right now. Can you try this and let us know if the problem persists?

We'll try to improve our documentation around this.

**Comment by bsreera** [comment]
@madebysid It is still the same. I am still unable to get it working. I am using the chrome app to keep it going as of now. 

Please let me know what else I can try. The format I have tried are .jks, .pem, .cer

**Comment by shamasis** [comment]
@czardoz @numaanashraf - we seriously need to find a way to bubble OpenSSL errors and loop it with server response to generate a much more debug friendly error message. Currently, it's very difficult to figure out what's going wrong with @bsreera.

**Comment by shamasis** [comment]
@bsreera can you use latest 4.6.2 app and confirm the error you see in postman console? If you've configured the certificate properly, you should see which cert got picked up and what error was thrown.

**Comment by bsreera** [comment]
@shamasis All I get is

Could not get any response
There was an error connecting to ******

Why this might have happened:
The server couldn't send a response:
Ensure that the backend is working properly
Self-signed SSL certificates are being blocked:
Fix this by turning off 'SSL certificate verification' in Settings > General
Client certificates are required for this server:
Fix this by adding client certificates in Settings > Certificates
Request timeout:
Change request timeout in Settings > General

This is how my config looks

Host   someserver.com:someport
CRT file  /Users/someuser/client-cert.crt

**Comment by shamasis** [comment]
@bsreera can you help with two things?
1. Does your server only need the crt file or anything else beyond that?
2. What is the message you see in Postman Console regarding certificates with respect to this request.

If you want, we can chat on our slack community. https://www.getpostman.com/slack-invite

**Comment by shamasis** [comment]
@bsreera - can you please check in postman console what's the error displayed? Pressing (cmd + l) opens it.

**Comment by bsreera** [comment]
When I use .pem

Error:
write EPROTO 140735099686912:error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure:../../vendor/node/deps/openssl/openssl/ssl/s3_pkt.c:1472:SSL alert number 40 140735099686912:error:1409E0E5:SSL routines:ssl3_write_bytes:ssl handshake failure:../../vendor/node/deps/openssl/openssl/ssl/s3_pkt.c:656:

When I use .jks

Error:
error:0906D06C:PEM routines:PEM_read_bio:no start line

When I use .crt

Error:
error:0906D06C:PEM routines:PEM_read_bio:no start line

**Comment by bsreera** [comment]
Not sure how it used to work, but I would usually run the postman chrome extension

chrome-extension://fdmmgilgnpjigdojojpjoooidkmcomcm/index.html

There it would popup as ask me to select the cert. And then I would launch the chrome postman app. Not sure how the stand alone app was picking it up till 4.6.0

**Comment by shamasis** [comment]
Also there was a similar issue solved here https://github.com/postmanlabs/postman-app-support/issues/2217

**Comment by bsreera** [comment]
Based on the comments, pointing CRT and KEY to the same .pem file solved the issue.

**Comment by mike390** [comment]
after an hrs searching this fixed the problem for me too - worth writing a guide about it?

**Comment by a85** [comment]
@mike390 Yep. Documentation will be updated soon.

**Comment by knasim** [comment]
yep - i'm having the same issue and i the correct cert/key chain (i can connect using C).

'Error: write EPROTO 140735678243776:error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown:../../vendor/node/deps/openssl/openssl/ssl/s3_pkt.c:1472:SSL alert number 46 140735678243776:error:1409E0E5:SSL routines:ssl3_write_bytes:ssl handshake failure:../../vendor/node/deps/openssl/openssl/ssl/s3_pkt.c:656:'

this is really crappy software !

**Comment by w3nchao** [comment]
Yes I'm having the same issue: 
native postman app + Version 4.10.7
`Error: write EPROTO 140736277353408:error:14094412:SSL routines:ssl3_read_bytes:sslv3 alert bad certificate:../../vendor/node/deps/openssl/openssl/ssl/s3_pkt.c:1472:SSL alert number 42 140736277353408:error:1409E0E5:SSL routines:ssl3_write_bytes:ssl handshake failure:../../vendor/node/deps/openssl/openssl/ssl/s3_pkt.c:656:`
![screen shot 2017-05-23 at 5 28 55 pm](https://cloud.githubusercontent.com/assets/3597941/26381964/6f1e33ca-3fdd-11e7-92ff-9d593aebfa9b.png)

**Comment by numaanashraf** [comment]
@knasim @w3nchao This thread was originally for loading client cert from Mac keychain. Continuing this discussion on #3063

**Comment by knasim** [comment]
either way - you're product needs to do a better job of supporting openssl otherwise it will die.

**Comment by numaanashraf** [comment]
@knasim Thanks for the feedback. We'll take this into consideration as we improve our SSL support.

**Comment by w3nchao** [comment]
@numaanashraf Yes, this error happens when i load the crt and key file to Postman - Settings - Certifications. I thought loading client cert from Mac keychain was not supported in postman. Is there an update?

**Comment by knasim** [comment]
@w3nchao - did you export your certificate out to PEM ?  can you post the args you gave to openssl

**Comment by krdeepak** [comment]
I have a crt file which i imported in mac keychain. But chrome extension postman app does not show  that certificate in the select certificate prompt when hitting the api (just shows one certificate by apple - com.apple.idms.appleid.prd.68432b4c5531556751724a4d757363383770524679513d3d)

Using mac native app and adding crt file also fails with
 `(Error: write EPROTO 140735815500736:error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake )`
Is key file optional when giving crt file?

Any known solution?
