### ISSUE TITLE
Postman history/collections reverts to old state

### ISSUE THREAD

**Issue by mick6701** [a85/POSTMan-Chrome-Extension#2267]
Hello,

I have been using Postman frequently the last couple of months.  Today, I go into Postman and my history and collections have reverted to the state that existed on March 4.   So I lost 5 months of history and Collection changes.

Any clue what may have caused this?

Thanks

**Comment by abhijitkane** [comment]
@mick6701 Can you head to https://app.getpostman.com/dashboard/collections/private?expand=1 and check if all your data is there? If yes, you can sign out and sign back in.

Also, did you notice the missing collections as soon as you opened Postman, or did you perform some user action?

**Comment by mick6701** [comment]
Yes, I noticed the missing collection immediately.  

Thanks for the quick response.  My recent Collections are saved in the location https://app.getpostman.com location.  Any idea what may have caused this so I can avoid it in the future?

**Comment by abhijitkane** [comment]
@mick6701 Nope. We'll investigate and see how this might have happened. Closing this for now. Feel free to re-open if you see this again.
