### ISSUE TITLE
Microsoft Azure AD oAuth login Window fails to load while getting a new access token

### ISSUE THREAD

**Issue by cartickn** [a85/POSTMan-Chrome-Extension#2268]
1. Postman Version: 4.6.1
2. App (Chrome app or Mac app): Windows App
3. OS details: Windows 10
4. Is the Interceptor on and enabled in the app: No
5. Did you encounter this recently, or has this bug always been there: Recently, Today
6. Expected behaviour: Microsoft oAuth Login Window Appears
7. Screenshots (if applicable)
   ![image](https://cloud.githubusercontent.com/assets/2995388/17709611/b2e6cdcc-639e-11e6-88e7-b32d50425378.png)

Create an Azure AD application and enable oAuth
From the Postman windows app set-up Authorization using oAuth 2.0 and click Get New Access Token.
The expected behavior is Microsoft login window appear within the Postman window.

Instead the window shows blank page due to bunch of javascript errors.

![image](https://cloud.githubusercontent.com/assets/2995388/17709611/b2e6cdcc-639e-11e6-88e7-b32d50425378.png)

**Comment by narthollis** [comment]
I am experiencing this same issue with a different OAuth2 server.

![image](https://cloud.githubusercontent.com/assets/67732/18655475/49986420-7f28-11e6-9ee8-3960aa03ada9.png)

From what I can see, the issue appears to be that jQuery has detected that it is running in a NodeJS-like environment and is therefor not putting its self into the global scope like it would on the web.

The fix should be to launch the OAuth2 window with node injection disabled.

**Comment by SamvelRaja** [comment]
@cartickn  @narthollis  Thanks for bringing this to our notice, will keep this issues updated regarding the progress of it.

**Comment by sdnts** [comment]
Can you guys try updating to the latest version of the app (4.8) and check if this is fixed? This looks related to #2351

**Comment by narthollis** [comment]
It appears to be working for me now.
