### ISSUE TITLE
Ability to disable a request in a collection

### ISSUE THREAD

**Issue by tariqghalib** [a85/POSTMan-Chrome-Extension#2269]
**DESCRIPTION:**
Currently we do not have the ability to disable a selected request under a collection. The ability to disable a request from the list of the requests under a collection would be very useful when we try to run selected requests in the runner.

**Version/App Information:**
1. Postman Version: 4.4.2
2. App (Chrome app or Mac app): Chrome App
3. OS details: Windows 7 Professional
4. Is the Interceptor on and enabled in the app: Yes
5. Did you encounter this recently, or has this bug always been there: The feature was never available
6. Expected behaviour: Should have the ability to disable a single request from the list of requests under a collection

**Steps to reproduce the problem:**
- Create a collection
- Create multiple requests under the collection:
  1) GET Name
  2) GET UserStatus
  3) POST UserInfo
  4) GET UserStatus)
- Disable second request in case we do not want to check the status of user before posting his/her info. Then it Looks like 
  1) GET Name - Enabled (May be black or normal color)
  2) GET UserStatus - Disabled (May be greyed out)
  3) POST UserInfo - Enabled (May be black or normal color)
  4) GET UserStatus) - Enabled (May be black or normal color)
- Now run the collection from Runner and it runs only
  1) GET Name - RAN
  2) GET UserStatus - SKIPPED
  3) POST UserInfo - RAN
  4) GET UserStatus - RAN

**Some guidelines:** 
- We should add this in the menu that opens from right (...) button. So the Menu looks like:
  Edit
  Duplicate
  Delete
  Disable (or Enable in case its disabled)
- Disabled requests should still be editable
- Color change for disabled requests would help tell user if its disabled currently or not (nice to have feature)

**Comment by sdnts** [comment]
Hey @tariqghalib, I understand your requirement, and you can achieve this right now using Postman's `setNextRequest` function.
Basically, you use this function to skip over the second request in your collection by calling it in the `Tests` section of the first request and supplying the name of your third request.

You can find relevant docs [here](https://www.getpostman.com/docs/workflows) or look at an example [here](http://blog.getpostman.com/2016/03/23/conditional-workflows-in-postman/)

Feel free to reopen if I misunderstood!
