### ISSUE TITLE
Windows App Includes empty realm and oauth_token header values when Chrome app does not 

### ISSUE THREAD

**Issue by chris-deluca** [a85/POSTMan-Chrome-Extension#2272]
Postman Version: 4.6.1
App (Chrome app or Mac app): Windows 
OS details: Windows Server 2012 R2
Is the Interceptor on and enabled in the app: No
Did you encounter this recently, or has this bug always been there: Yes (just downloaded the Windows version)
Expected behaviour:
1. Windows app should behave like the Chrome app

Actual behavior: 
1. Start copies of both the Windows and Chrome App
2. Set the following
 a. The URL to an appropriate value and the operation to Get
 b. Authentication type to OAuth 1.0
 c. Consumer key to an appropriate value
 d. Consumer secret to an appropriate value
 e. Signature Method to HMAC-SHA1
 f. Timestamp to an appropriate value
 g. Nonce to an appropriate value
 h. Version 1.0
 i. Realm empty
 j. Add params to header - checked
 k. Add empty parameters to Signature - unchecked
 l. Encode OAuth Signature - unchecked
 m. Save helper data to request - checked
3. Click "Send" 

Windows App Results:

```
<TransactTsError xmlns:i="http://www.w3.org/2001/XMLSchema-instance">
      <Code>Unauthorized</Code>
      <DiagnosticData i:nil="true"/>
      <Message>Invalid signature</Message>
  </TransactTsError>

```

Chrome App Results:

```
  {
    "oauth_callback_confirmed": "true",
    "oauth_token": "djZWYnBFNXNa...<snipped data/>",
    "oauth_token_secret": "x/3w76G...<snipped data/>"
  }
```

Windows App Header:
  Authorization:OAuth realm="",oauth_consumer_key="FFFFFFFF-FFFF-FFFF-FFFF-FFFFFFFFFFFF",oauth_token="",oauth_signature_method="HMAC-SHA1",oauth_timestamp="1471479411",oauth_nonce="RTyyQ738hBh",oauth_version="1.0",oauth_signature="iTALu8svVkjY9uXCoR%2BFnJHhew8%3D"

Chrome App Header:
  Authorization:OAuth oauth_consumer_key="FFFFFFFF-FFFF-FFFF-FFFF-FFFFFFFFFFFF", oauth_signature_method="HMAC-SHA1",oauth_timestamp="1471479441",oauth_nonce="GpVuwW", oauth_version="1.0",oauth_signature="1%2B%2B4T8OtoaP0h%2B%2BOwofmZcQvmz8%3D"

Differences:
1. Realm was added to the header (empty) when it shouldn't have
2. oauth_token was added to the header (empty) when it shouldn't have

Screenshots (if applicable)
Attached - 4 shots.  2 from Chrome app and 2 from Windows app showing 100% matching data, yet Chrome app works, Windows app does not.

![chrome-details](https://cloud.githubusercontent.com/assets/21092038/17758029/bd4c3c68-64a0-11e6-9997-2b6ed1ca3c27.png)
![chrome-header](https://cloud.githubusercontent.com/assets/21092038/17758032/bd4faf2e-64a0-11e6-8893-a240790fc839.png)
![windows-details](https://cloud.githubusercontent.com/assets/21092038/17758030/bd4cdad8-64a0-11e6-9d26-b111c3043dce.png)
![windows-header](https://cloud.githubusercontent.com/assets/21092038/17758031/bd4cf748-64a0-11e6-812d-9fe062438db0.png)

**Comment by numaanashraf** [comment]
Thanks for reporting this @Chris-Deluca. We'll have a fix out for this in the next release.
