### ISSUE TITLE
Feature Request: Shared Environments should be editable by the creator and team members

### ISSUE THREAD

**Issue by respectTheCode** [a85/POSTMan-Chrome-Extension#2273]
With the new monitoring service this becomes even more important.

**Comment by a85** [comment]
@respectTheCode Agree. We are working towards this.

**Comment by Faz540** [comment]
How on earth isn't this more requested? haha 😛 
Unless this is a duplicate issue and the original has a lot more +1s.

@a85 Is there any progress on this or is this part of the roadmap at all?

Other than my community post below, the only workaround is to just delete and re-share an environment and then tell your team members to re-subscribe to the new environment.

https://community.getpostman.com/t/editing-shared-environments-environment-variables/443

**Comment by mccannt** [comment]
I would love to see this make it into a release in the near future.

**Comment by CakeEddy** [comment]
This is a feature that I've been keeping my eye out for. Please implement this ASAP.

**Comment by respectTheCode** [comment]
@a85 any progress on this? We have completely stopped using the monitoring service because it was too hard to maintain.

**Comment by a85** [comment]
@respectTheCode @CakeEddy Yep! Environment templates are going away and we'll just have environments from now on. This is being implemented through Workspaces #3205. Check out our Canary channnel. There won't be any distinction between environments that you work on and your team works on any more.

**Comment by a85** [comment]
Environments are now available in Workspaces. Complete roll-out next week. More info in our docs: https://www.getpostman.com/docs/postman/workspaces/intro_to_workspaces
