### ISSUE TITLE
Runner writes to wrong environment

### ISSUE THREAD

**Issue by austinmoore-** [a85/POSTMan-Chrome-Extension#2274]
1. Postman Version: 4.6.1
2. App (Chrome app or Mac app): Mac app
3. OS details: OS X El Capitan Version 10.11.6
4. Is the Interceptor on and enabled in the app: No
5. Did you encounter this recently, or has this bug always been there: Recently encountered
6. Expected behaviour: The Runner writes to the selected environment
7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):

```
 ================================================================
     o
   (/) P O S T M A N
   ^

   Go to View -> Show Postman Console to check your script logs. 

================================================================
🌏 sync service connectivity initiated
socket replaying queued commands
🌏 connected to sync service.
Import globals
🐶 watchdog checking connection health
Import environments
Import headerPresets
Import collections
```
1. Screenshots (if applicable) N/A

**Steps to reproduce:**
1. Have at least two environments (`env1`, `env2`) with different environment variables.
2. Select the first environment (`env1`) in the main Postman window.
3. Open the Runner, and select a different environment (`env2`).
4. Run a test in the Runner.
5. Close the Runner and look at the key-value pairs in `env1` to see that they are overwritten with the key-value pairs from `env2`.

**Comment by shamasis** [comment]
@numaanashraf cc

**Comment by numaanashraf** [comment]
@austinmoore- Thanks for reporting this. We'll include the fix in the next release.

**Comment by austinmoore-** [comment]
I just updated Postman, and saw that this issue was resolved. I ran through the steps to reproduce, and everything worked great. Thanks!
