### ISSUE TITLE
Generate Code for cURL does not encode value

### ISSUE THREAD

**Issue by LilyEssence** [a85/POSTMan-Chrome-Extension#2275]
Version/App Information:
1. Postman Version: 4.5.1
2. App (Chrome app or Mac app): Mac app
3. OS details: Version 10.11.6
4. Is the Interceptor on and enabled in the app: Not sure
5. Did you encounter this recently, or has this bug always been there: Not sure
6. Expected behaviour: Generate code for cURL should produce a working, correct cURL script, even if one of the headers contains special symbols/characters
7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app): Not sure you need these.
8. Screenshots (if applicable)

Steps to reproduce the problem:
Create new call with header that has a value with special symbols such as ",./;[,'/.!@#$%^&_(". And example of when these symbols may be used would be a password field. 
Generate code -> cURL
See that the value hasn't been encoded in the url. For example, ",./;[,'/.!@#$%^&_(" should turn into "%2C.%2F%3B%5B%2C%27%2F.!%40%23%24%25%5E%26*("

**Comment by SamvelRaja** [comment]
should we encode? that might not be useful for someone else.
- we could only escape characters that are not compatible with terminal input
- put quotes around parameters that have spaces (or space-like) characters

**Comment by sdnts** [comment]
@LilyEssence Can you generating cURL in the latest version (4.8.3) and see if it is correct?
