### ISSUE TITLE
Feature Request - Saving tabs states and data on close and open app

### ISSUE THREAD

**Issue by cristiammercado** [a85/POSTMan-Chrome-Extension#2278]
Hi people, 

It would be great if when I close the Postman app for Windows (or any version), keep the header information and the body of the tabs I'm using at the time. When you reopen the application, all the same information opens in the tabs as it was when I closed it.

Thanks a lot for this great app!

**Comment by jamest-iqmetrix** [comment]
Has anything been implemented for this yet?
I've noticed that for the last couple of weeks, I do in fact have a tab still open when I open the Chrome app (version 4.7.1).  But instead of it being a tab I was using in my previous session, it's simply always the same tab with the same information.

**Comment by numaanashraf** [comment]
@cristiammercado @jamest-iqmetrix Restoring tab states is currently in the pipeline, but we don't have an ETA yet. Currently, Postman launches with one tab pre-filled with the last sent request.

**Comment by vegetableman** [comment]
@cristiammercado @jamest-iqmetrix The latest version `4.9` supports restoring tab states. Let me know what you guys think.

**Comment by jamest-iqmetrix** [comment]
I've been meaning to get back to this, but Chrome is being finicky with updates and I don't want to lose all of my settings by uninstalling/reinstalling.
Planning on checking later this week on my personal machine.

**Comment by cristiammercado** [comment]
@vegetableman It's great! The new feature is working very well. Excellent work!

**Comment by dvkwong** [comment]
Sorry to say but I do NOT like this feature. 

I generally do a lot of adhoc queries etc which I do not want to overwrite the defaults. Also previously before if I screwed up the request I could simply click on the request again to go back to the defaults which is no longer the case any more.

Can we either get an option to disable feature or have an option to close all tabs without being prompted to save.

Thanks
