### ISSUE TITLE
Retrieve binary response from Sharepoint REST Api call similar to postman 

### ISSUE THREAD

**Issue by manishagr83** [a85/POSTMan-Chrome-Extension#2280]
I am trying to download a file from sharepoint 2013 and save as a local file before sending as attachment in a email in my JAVA application. I have tested the URL http://<host-name>/Sites/BPM/_api/web/getfilebyserverrelativeurl('Test Sharepoint.docx')/$value with postman and it works perfectly with the Send and Download option where the file received is having all the content of the word document. Need help with the following
1. How do we find the internals of what postman is doing as with the following code my word document is not showing any contents of the word
byte[] bytearray = returnStr.getBytes("UTF-8");
OutputStream stream = new FileOutputStream("C:/Manish/JDBC/Test Sharepoint.docx");  
                stream.write(bytearray);
                stream.close();
2. How do we set the file name in postman while calling the send and download option

**Comment by abhijitkane** [comment]
@manishagr83 Setting the filename isn't supported right now.
For 1., Postman simply treats the response as an Arraybuffer when you click 'Send and Download'.

You'll need to reference your Java library's docs for more on how to read the file in your application.
