### ISSUE TITLE
oauth2 in postman / newman without using the integrated support

### ISSUE THREAD

**Issue by pollenflugkalender** [a85/POSTMan-Chrome-Extension#2281]
Hi all,

We want to use postman in conjunction with newman (for CI) therefore we need to fully automate the oauth2 authentication process. But afaik this is not possible with the integrated oauth2 support. For example, you have to generate an access token by manually pressing the button "Get New Access Token". Or is it possible to do press the Postman button programatically? But how would that work within Newman?

Is there maybe a way to implement the oauth2 authentication process without using the integrated oauth2 support? Do there exist working examples I can use as a template?
I guess the main steps are to make work oauth2 are:
1. How can get the response URL with the auth code I need for the token request? 
2. How can I press a button ("accept") on a consent page? 
Can I perform these two steps within postman / Newman e.g. via javascript?

That you very much for your feedback!

-->

**Comment by snaits** [comment]
The other helpers have "Save helper data to request" checkboxes, this is missing from the OAuth2 helper. I think that would solve the problem.

**Comment by pradeepkusingh** [comment]
ignore please.

**Comment by shamasis** [comment]
I am not sure that automating the IDP's web UI is feasible at all (maybe it even defeats the whole purpose of oAuth2)! Even if you have full control, IDP UIs protect against these sort of situations using Captcha and other obfuscation.

Maybe use HMAC mode for this purpose. Perhaps, we could introduce this mode. Feature request on https://github.com/postmanlabs/postman-app-support/issues/632

@a85 - this might need to be closed.

**Comment by snaits** [comment]
@shamasis  If you are thinking about an OpenID scenario, sure, this defeats the purpose and may not be possible at all.

For just fetching a client_credentials flow type OAuth2 token though, it would be very helpful indeed.

**Comment by a85** [comment]
Closing this issue as this might not be feasible. For automated testing scenarios, APIs typically present an alternative auth scenario that would work with Postman/Newman.

**Comment by ChangeTheCode** [comment]
I think this problem is still valid. 
If you host your API in your own environment it is still possible to provide an alternative auth scenario for testing. But now you will use an Cloud Service an his provided Security mechanism you can't open all gates or you shouldn't. 

So for this scenario it would be nice to have an solution to automate the postman/newman test. or am I the wrong assumption?

**Comment by lucaNationwide** [comment]
Looking forward to a solution for this issue
