### ISSUE TITLE
Request Size Displayed

### ISSUE THREAD

**Issue by javagrnd** [a85/POSTMan-Chrome-Extension#2282]
Would it be possible to have similar feature that lists total size of request, like what one receives from '%{size_request}' in curl.  I work with s3 repositories and their ingress (inbound traffic) & egress (outbound traffic) tracks the size of traffic in bytes & includes the actual request itself (as well as the data).  This will allow for tracking as close to actual usage as possible for both request & response.

ref: Postman Support Issue located here deals with response size : postman-app-support/issues/156

1. Postman Version: 4.6.2
2. Chrome app
3. OS details: Win 7x Enterprise
4. Is the Interceptor on and enabled in the app: No
5. Did you encounter this recently, or has this bug always been there: Recently thought of it
6. Expected behaviour: Request Size: 1234567 bytes
7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app): not applicable (yet)
8. Screenshots (if applicable): not applicable (yet)

**Comment by andreujuanc** [comment]
I just ended up using firefox for this. Only issue is that the debugging window is quite bad, and does not have a scroll. But maximising it "fixes" that, so it actually works better than postman..

**Comment by anudeepmedicharla** [comment]
@a85 We could do this along with the breakup of network timings. What are your thoughts?

**Comment by Sugavanas** [comment]
This would be useful same as #156 when you are building an API that will be accessed by your own mobile apps.

**Comment by a85** [comment]
This is coming soon to the production apps.

**Comment by codenirvana** [comment]
We've added this on our Canary (`version: 7.1.0-canary01`) channel https://www.getpostman.com/canary

![Screenshot 2019-03-28 at 11 35 02 AM](https://user-images.githubusercontent.com/4865836/55134779-ca4fbb80-514f-11e9-9404-6a8ef67f6f41.png)

Will update the thread once we release this on our stable channel.

**Comment by javagrnd** [comment]
Awesome.  Thank you so much.


James Cookson

Sr QA Engineer, SDET

https://www.linkedin.com/in/jamescookson/

________________________________

**Comment by codenirvana** [comment]
This has been added in the latest Postman App (v7.0.9). 🎉
