### ISSUE TITLE
308 status code

### ISSUE THREAD

**Issue by adaksuman** [a85/POSTMan-Chrome-Extension#2283]
How can I receive 308/307 responsecode in postman?. I am able to get such code in other client like advance rest client.

postman shows "Could not get any response"

postman client version -
 4.6.2
linux / x86-64
Chrome 51.0.2704.63

1. Postman Version:
2. App (Chrome app or Mac app):
3. OS details:
4. Is the Interceptor on and enabled in the app:
5. Did you encounter this recently, or has this bug always been there:
6. Expected behaviour:
7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
8. Screenshots (if applicable)

**Comment by czardoz** [comment]
@adaksuman Can you share a small collection that reproduces the issue? If it contains sensitive information, you can email it to help@getpostman.com :)

**Comment by adaksuman** [comment]
Ok. I tried with toy node.js app. I see, problem is coming when I tried to add custom header  before sending 308.

Node app

var express = require('express');
var app = express();

app.post("/test",function(req,res){
    res.header("location","localhost:8080/path");
    res.set("foo","bar");
   res.status(308).end();
});
app.listen(8000, function() {
        console.log('Express server listening on port 8000');
});

I see an "Could not get any response" in postman while curl and advance rest client gave me correct header with statusCode.

**Comment by sdnts** [comment]
Hey @adaksuman, can you try turning off Automatic redirects in Postman's settings (Wrench icon on top-right > Settings) and try again?
Looking at your server, Postman tries to follow the redirect to `localhost:8080/path`, and since no server is running on that address, it fails to display a response.
