### ISSUE TITLE
GET Request Responds with 400 Bad Request with Var in URL

### ISSUE THREAD

**Issue by patrick-martin-shoutpoint** [a85/POSTMan-Chrome-Extension#2285]
1. Postman Version: 4.6.2
2. App (Chrome app or Mac app): Mac
3. OS details: 10.11.5
4. Is the Interceptor on and enabled in the app: No
5. Did you encounter this recently, or has this bug always been there: Since last update
6. Expected behaviour: 200 OK response
7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):

```
GET
https://api.shoutpoint.com/v1/LiveCalls/141793@4755
07:55:26.295
Error:
SSL Error: Hostname/IP doesn't match certificate's altnames: "Host: api.shoutpoint.com/v1. is not in the cert's altnames: DNS:api.shoutpoint.com, DNS:www.api.shoutpoint.com"

```
1. Screenshots (if applicable)

400 Bad Request on GET requests, when I use a variable in the URL like this: `https://{{BASE_URL}}/LiveCalls/:callId`
BASE_URL = api.shoutpoint.com/v1

```
Error:
SSL Error: Hostname/IP doesn't match certificate's altnames: "Host: api.shoutpoint.com/v1. is not in the cert's altnames: DNS:api.shoutpoint.com, DNS:www.api.shoutpoint.com"
```

However, if I remove the variable and change the URL to `https://api.shoutpoint.com/v1/LiveCalls/:callId`, the request works.

**Comment by numaanashraf** [comment]
@patrick-martin-shoutpoint Thanks for reporting this. We are looking into this and will keep you posted.

**Comment by PabloLedo97** [comment]
Buenas tardes, el problema que tengo, es que al hacer un GET  al conjunto de recursos no me sale en ese conjunto un recurso que previamente habia creado correctamente mediante un POST. Cual podria ser el fallo gracias
