### ISSUE TITLE
UI Scaling text selection offset

### ISSUE THREAD

**Issue by everydaynerd** [a85/POSTMan-Chrome-Extension#2286]
### Version/App Information:
1. Postman Version: 4.6.2
2. App: Mac app
3. OS details: El Capitain 10.11.6
4. Is the Interceptor on and enabled in the app: No
5. Did you encounter this recently, or has this bug always been there: Recently
6. Expected behaviour: Text selection should start where the cursor starts.
7. Console logs: n/a
8. Screenshots
   ![image](https://cloud.githubusercontent.com/assets/4731446/17898157/b2d98866-6924-11e6-9d30-d25b17f02615.png)
### Steps to reproduce the problem:

Scale the UI up or down.  Depending on how many +/- is the number of lines that the offset of text selection varies.  For example, in the Tests window, if scaled up three times, click on the first line of the test, and drag down.  The text selection will highlight starting three lines down, and off to the right a few characters.  Conversely, if scaled down, the highlight will start above the cursor.  If UI Scaling is normal, text selection is normal as well.

**Comment by numaanashraf** [comment]
@everydaynerd Thanks for reporting this. We'll include the fix in this week's release.

**Comment by deepal** [comment]
@numaanashraf I also have this issue with the mac app. After zooming out UI, Cursor does not appear where I click, but few lines up. UI scaling feature is almost useless due to this issue. Hope you guys will fix this soon. <3 postman.

**Comment by sdnts** [comment]
@everydaynerd @dpjayasekara Can you guys try updating to the latest version (4.7) and verify if this is fixed?
