### ISSUE TITLE
JSON/XML body "hide/unhide" control mis-aligned

### ISSUE THREAD

**Issue by gilesheron** [a85/POSTMan-Chrome-Extension#2287]
1. Postman Version:
   4.6.2
2. App (Chrome app or Mac app):
   Mac app.
3. OS details:
   10.11.6
4. Is the Interceptor on and enabled in the app:
   No
5. Did you encounter this recently, or has this bug always been there:
   Recently (saw in 4.6.1 for sure, but not before 4.6.0 I think).
6. Expected behaviour:
   Pressing the little triangle on the left by the line number adjacent to a JSON "{" or "[" (or to an XML tag where the end-tag is on another line) should "hide" that block of JSON or XML content.   Instead what I'm seeing here is that it either does nothing, or it hides another, subsequent block.
7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
   Not seeing any logs
8. Screenshots (if applicable)

Issue a postman command that returns a block of JSON or XML, then go into the returned body (in "Pretty" mode) and click on any of the triangles next to line numbers on the left hand side.  Notice which block of content (if any) is hidden.

**Comment by numaanashraf** [comment]
@gilesheron Thanks for reporting this. We have fixed this in our internal builds and will be rolling out the fix in this week's release.

**Comment by gilesheron** [comment]
you guys rock.

On 23 Aug 2016, at 19:02, Numaan Ashraf <notifications@github.com<mailto:notifications@github.com>> wrote:

@gilesheronhttps://github.com/gilesheron Thanks for reporting this. We have fixed this in our internal builds and will be rolling out the fix in this week's release.

**Comment by numaanashraf** [comment]
@gilesheron The fix for this is out on versions 4.6.3 and up. Could you verify and let us know?

**Comment by jammage** [comment]
Hello,

I can confirm this working now in Postman 4.7.0 for Windows.  More details of my app are as follows:
win / x86-32
Chrome 52.0.2743.116

Thanks for making the change!

**Comment by gilesheron** [comment]
yes - works for me :)

On 6 Sep 2016, at 11:41, Numaan Ashraf <notifications@github.com<mailto:notifications@github.com>> wrote:

@gilesheronhttps://github.com/gilesheron The fix for this is out on versions 4.6.3 and up. Could you verify and let us know?
