### ISSUE TITLE
Support for Windows Authentication

### ISSUE THREAD

**Issue by gsteinbacher** [a85/POSTMan-Chrome-Extension#2292]
We have our IIS setup to only allow Windows Authentication.  When I execute my Rest API call from a browser the request works just fine.  When I run the same request through Postman I get a 401 - Unauthrorized.  Is there a way to allow Postman to support Windows Authentication?

**Comment by RobbyDeLaet** [comment]
+1

**Comment by swisscoder** [comment]
+1 
=> as the chrome app will not live forever this becomes more important! Please build it into the Windows App.

**Comment by shamasis** [comment]
@gsteinbacher you mean NTLM auth right?

**Comment by giuliocaccin** [comment]
Is this a duplicate of #1137 ?

**Comment by chrisknoll** [comment]
Looks like we're seeing momentum, does that latest PR mean that we'll be seeing this supported in the near future?

**Comment by AlessandroLazzari1985** [comment]
+1

**Comment by muehan** [comment]
+1
there is a useful workaround here: https://stackoverflow.com/a/40544245/4383425

**Comment by harryi3t** [comment]
We are adding NTLM support in Postman 5.3
Please refer the original issue https://github.com/postmanlabs/postman-app-support/issues/1137 for updates
Marking this as duplicate and closing.
