### ISSUE TITLE
Host header is incorrectly set when using param as path segment and environment variable for host including protocol

### ISSUE THREAD

**Issue by andreassiegel** [a85/POSTMan-Chrome-Extension#2294]
Recently, I encountered an issue with the host address in an environment variable in combination with a param as path segment.

Assume the following:
- I have a environment variable for the host: `server`
- I want to send a request to an endpoint like `/endpoint/someValue`
- I want to use a param as a path segment: `/:param`, which will be set to `someValue`

Thus, the expected request URL is `http://localhost:1234/endpoint/someValue` in each case.

To construct this URL, I use to different approaches, that lead to different `Host` headers I receive in my application, which in turn results in undesired responses:

| Request | `server` environment variable | Response | `Host` header |
| --- | --- | --- | --- |
| `GET {{server}}/endpoint/someValue` | `localhost:1234` | OK | `localhost:1234` |
| `GET {{server}}/endpoint/:param` | `localhost:1234` | OK | `localhost:1234` |
| `GET http://{{server}}/endpoint/someValue` | `localhost:1234` | OK | `localhost:1234` |
| `GET http://{{server}}/endpoint/:param` | `localhost:1234` | OK | `localhost:1234` |
| `GET {{server}}/endpoint/someValue` | `http://localhost:1234` | OK | `localhost:1234` |
| `GET {{server}}/endpoint/:param` | `http://localhost:1234` | ERROR | `http://localhost:1234` |

In the last case, the protocol is not stripped off when the `Host` header is set, when I send the request via Postman.

The request URL is correctly built in all cases, and also generated `cURL` commands are fine. The only difference, that I see, is the `Host` header field.

I would expect that the protocol is stripped, even if the host is set as an environment variable, which may include the protocol.

**Version/App Information:**

Postman Version: 4.6.2
App (Chrome app or Mac app): Mac app
OS details: OS X El Capitan 10.11.6 (15G31)

**Edit:**

Most likely a duplicate of https://github.com/postmanlabs/postman-app-support/issues/2276

**Comment by numaanashraf** [comment]
@andreassiegelrfid This is a regression in v4.6.2. We are rolling out a fix for this in v4.6.3 that should drop within a day or two.

**Comment by SamvelRaja** [comment]
We released a fix for this in 4.6.3 - @andreassiegelrfid can you check and confirm? 😄

**Comment by andreassiegel** [comment]
It worked when I last tested with v4.6.3! :)
