### ISSUE TITLE
OAuth 1.0 signature invalid for URLs with path variables

### ISSUE THREAD

**Issue by worrel** [a85/POSTMan-Chrome-Extension#2295]
Version:4.6.2
OS:OS X / x86-64
Chrome 52.0.2743.116
Interceptor on & enabled

OAuth 1.0 integration:
1. Setup a call for an OAuth 1.0 API with a URL that includes a path variable (e.g. GET request for `https://api.yelp.com/v2/business/:business-id`
2. Provide value for the path variable
3. Setup required OAuth parameters
4. Either issue the request directly or "Update Request" & then execute
5. Invalid OAuth signature is produced & request is rejected

Note that replacing the ":business-id" with the value of the path variable directly results in correct behavior.  It appears the OAuth signature is generated prior to replacing the path variable, resulting in an invalid signature.

**Comment by sdnts** [comment]
Hey @worrel, thanks for reporting this, we're looking into this and will update you when a fix is out.

**Comment by sdnts** [comment]
Hey @worrel Can you try updating to the latest version (4.7) on the native app and verify if this is fixed?

**Comment by worrel** [comment]
Looks like I'm on 4.7 ![](https://www.dropbox.com/s/rn6zh22cts23c8m/Screenshot%202016-09-12%2019.04.43.png?raw=1)
The issue still occurs though.  I can take a working OAuth request for Yelp API and make it fail by switching out the `some-business-name` in `https://api.yelp.com/v2/business/some-business-name` with `:business-id` and providing `some-business-name` in the params form.

**Comment by sdnts** [comment]
Ah I was able to reproduce this. We'll get on a fix.
For the time being though, you could use environment variables in pretty much the same way.
Make a request to `https://api.yelp.com/v2/business/{{businessId}}`, setting `businessId` in an environment variable. Relevant docs are [here](https://www.getpostman.com/docs/environments)

**Comment by sdnts** [comment]
@worrel I verified this to be fixed in v4.8. Can you check and close?
