### ISSUE TITLE
Sometimes "undefined" is rendered between XML tags in Pretty view

### ISSUE THREAD

**Issue by HenrikHL** [a85/POSTMan-Chrome-Extension#2297]
1. Postman Version: 4.6.2
2. Chrome app
3. OS details: Windows 10 Pro 64bit
4. Is the Interceptor on and enabled in the app: YES
5. Did you encounter this recently, or has this bug always been there: recently
6. Expected behaviour:
   I expect POSTman to present the result in the Pretty-view without inserting extra text when showing the result of a GET request
7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
8. Screenshots (if applicable)
   ![image](https://cloud.githubusercontent.com/assets/3489388/18089222/1e8691cc-6ebf-11e6-9bd3-c079e97bb0a3.png)
   in XML view and

![image](https://cloud.githubusercontent.com/assets/3489388/18089247/3b228610-6ebf-11e6-9f50-8eefc67ce802.png)
In Raw view...

If some special character is inserted between **< /id>** and **< /TextSection>** then I would expect to see it in Raw view.

**Comment by abhijitkane** [comment]
@HenrikHL Can you paste the raw response as-is here?

**Comment by HenrikHL** [comment]
```
<TextSection><reviewId>038903011113025117</reviewId><noteId/><parentSectionId/><headingLevel>1</headingLevel><heading>Summary</heading><tag>FEEDBACK_SUMMARY</tag><headingFixed>true</headingFixed><mandatory>true</mandatory><formattingOptions>BODY_TEXT</formattingOptions><text>&lt;p>I wish to congratulate the authors for a very fine review. The authors conclude that activated protein C (APC) should not be used in sepsis with an APACHE II score of less than 25 or in pediatric patients and that there is very weak evidence supporting APC use in patients with severe sepsis and at high-risk of death.&lt;/p>
&lt;p>I believe the conclusion should be stronger than this. This drug should not be used at all. The division after a score of 25 was not preplanned, and the overall result, including all randomized patients, was not statistically significant. In such circumstances, subgroup analyses are inappropriate and dangerously misleading, as the authors also point out. I have compared the results for patients below and above 25 and got P = 0.59, confirming the lack of a difference between the effect in these two subgroups.&lt;br/>We have been fooled so often in the past into believing that various, very expensive drugs for the treatment of sepsis were effective because of their presumed beneficial effects on the coagulation processes. Sadly, the only thing that has been effective with APC was its marketing.&lt;/p>
&lt;p>Submitter agrees with default conflict of interest statement:&lt;/p>
&lt;p>I certify that I have no affiliations with or involvement in any organization or entity with a financial interest in the subject matter of my feedback&lt;/p></text><sortOrder>0</sortOrder><id>1853159927358149</id></TextSection>
```

**Comment by abhijitkane** [comment]
@HenrikHL The `&lt;/p>` needs to be escaped to `&lt;/p&gt;`. We'll push out a fix for the `undefined` issue soon, but the indentation won't work properly till the XML is escaped.

**Comment by HenrikHL** [comment]
Thank you.
I am not sure why ">" is not escaped - Jackson (fasterXML) does the escaping for me... I will look into it

**Comment by abhijitkane** [comment]
@HenrikHL Can you confirm this fixed in the latest version of the Chrome app (https://www.getpostman.com/docs/updating)?

**Comment by HenrikHL** [comment]
Thank you for fixing the problem. The "undefined" has dissapeared. The indention though is wrong - but I guess that is still because I don't properly escape the XML?
Appart from the indention it looks correct...
![image](https://cloud.githubusercontent.com/assets/3489388/18270926/d902355e-742f-11e6-907e-4ce038ea4846.png)

**Comment by abhijitkane** [comment]
Yep, the `/p>` is regarded as a closing tag. Closing this issue for now.
