### ISSUE TITLE
Digest Auth not saveable

### ISSUE THREAD

**Issue by amnesty007** [a85/POSTMan-Chrome-Extension#2298]
Version/App Information:
1. Postman Version: 4.6.3 / 4.6.2
2. App (Chrome app or Mac app): Chrome App aswell as Windows App
3. OS details: Windows 7 64 bit / Windows 10 64 bit
4. Is the Interceptor on and enabled in the app: off
5. Did you encounter this recently, or has this bug always been there: recently
6. Expected behaviour: Saving Settings

When picking Digest Authentication you cannot save your Request with Digest enabled.
The only way to save settings is to export the Collection modify the Json and reimport it.
But when you do 1 request postman recognizes changes and would like to save it again.

It should work as Basic. Saving works perfectly with Basic.

Kind Regards

**Comment by vegetableman** [comment]
@amnesty007 Looking in to this. Thanks for reporting.

**Comment by vegetableman** [comment]
@amnesty007 This has been fixed in our internal build. And will be part of the upcoming release.

**Comment by SamvelRaja** [comment]
@amnesty007 We patched up a fix in 4.8.0, kindly update the version and check the same.
