### ISSUE TITLE
collection modifications not syncing to runner

### ISSUE THREAD

**Issue by Catweasle** [a85/POSTMan-Chrome-Extension#2301]
1. Postman Version: 4.6.3
2. App (Chrome app or Mac app): desktop application (local, not syncing to cloud)
3. OS details: windows 10
4. Is the Interceptor on and enabled in the app: no
5. Did you encounter this recently, or has this bug always been there: always (newbie)
6. Expected behaviour: changes to collection are taken into account in runner

Doc says:While the window is open, you can make changes to your collections inside the main Postman window and they will be updated inside the Collection Runner as well.

But... If I change something to a request in the collection (E.g. set a global variable in the prerequest script, modify a test) and I rerun the collection in an open runner, the changes are not taken into account. I need to relaunch the runner window (and reset environment, #iterations..) to have the updated collection running.

Is it a bug or is it me?

**Comment by SamvelRaja** [comment]
@Catweasle Thanks for reporting this to us. We are working on this and will update here once this has been fixed.

**Comment by sdnts** [comment]
@Catweasle Our latest release (4.9) on the native apps features a brand new Runner that syncs collection modifications between the App and the Runner. Can you update and check if this works for you now?
