### ISSUE TITLE
Feature-request: RSA-SHA1 signature method for OAuth 1.0 Authentication helper

### ISSUE THREAD

**Issue by mykhaylo-** [a85/POSTMan-Chrome-Extension#2302]
Hi,
Currently Postman supports only HMAC-SHA1, HMAC-SHA256 and PLAINTEXT signature methods.  Need to have also RSA-SHA1 where request is signed with RSA private key. 
Are there any plans on adding this?

Thanks.

**Comment by dvishniakov** [comment]
+1 for RSA-SHA1
Support for the signature using asymmetric keys would be good. It's supported by OAuth 1.0 and it's also supported in JWT which gained a lot of popularity

**Comment by Roam-Cooper** [comment]
Almost a year and no progress on this issue?

**Comment by henzard** [comment]
+1

**Comment by andrewgl504** [comment]
+1

**Comment by shdunning** [comment]
+1

**Comment by unlikelyzero** [comment]
+1

**Comment by dvlancer** [comment]
+1

**Comment by oscarrobinson** [comment]
+1

**Comment by crsantini** [comment]
+1

**Comment by saliehendricks** [comment]
+1

**Comment by gurkanyerlikayaoglu** [comment]
+1

**Comment by c-f-allen** [comment]
+1

**Comment by willmero** [comment]
+1

**Comment by garethcollinson** [comment]
+1 - required for any xero accounting integrations

**Comment by avvensis** [comment]
+1

**Comment by Shifty-kek** [comment]
+1

**Comment by kweebtronic** [comment]
+1

**Comment by vladare** [comment]
+

**Comment by Josephliao1991** [comment]
+1

**Comment by kingwrcy** [comment]
+1,please support RSA  encrypt/decrypt/sign/verify。

**Comment by andybellenie** [comment]
+1

**Comment by yincheng0807** [comment]
+1

**Comment by cblazo** [comment]
+1

**Comment by kedu** [comment]
+1

**Comment by gregrobson** [comment]
+1
2 years and no movement on this?

**Comment by scottysseus** [comment]
A little-known product called JIRA has a REST API which only supports RSA-SHA1.

**Comment by quentin34** [comment]
Same thing here, would like to use  RSA-SHA1 for JIRA REST API.

**Comment by nitzel** [comment]
+1

**Comment by BytesDude** [comment]
+1

**Comment by MarkoHub** [comment]
+1

**Comment by gvillacarlos-deputy** [comment]
+11111

**Comment by nvhaver** [comment]
+1

**Comment by COLTELLAIT** [comment]
+1

**Comment by TheFRedFox** [comment]
+1

**Comment by ray-marr** [comment]
Need this for Xero API integration.

**Comment by lozog95** [comment]
+1

**Comment by tekNorah** [comment]
> Need this for Xero API integration.

Me too!

**Comment by morrisond91** [comment]
I was able to get around a similar scenario with this workaround, see my solution here

https://github.com/morrisond91/PostmanRsaSupport/blob/master/README.md

**Comment by visualisedata** [comment]
+1 please

**Comment by er1ck** [comment]
+1

**Comment by brucephenry** [comment]
OMG. Really. REALLY. You don't support RSA? Le Sigh...

**Comment by jackpowers** [comment]
+1

**Comment by ben-pearson** [comment]
+1

**Comment by enrikas** [comment]
+1

**Comment by tarrball** [comment]
+1  ...Jira for me too

**Comment by Veraxus** [comment]
+1 also due to JIRA. I can't believe such a fundamental auth feature has been open and unaddressed since 2016.

**Comment by paprikati** [comment]
+1 for xero

**Comment by asponda** [comment]
+1 for JIRA API

**Comment by peavers** [comment]
+1 for JIRA API

**Comment by arbtfnf** [comment]
GSoC 2020, 
I am interested to work on this feature, Can you introduce me in getting started and start contribution.
IRC channel?

**Comment by prasadrathod** [comment]
GSoC 2020,
Hi, I am interested to work on this feature. It will be great if I can get some guidance and how to join IRC channel of PostmanLabs and get started.

**Comment by vdespa** [comment]
It would be nice to this in Postman as currently there is no easy way of getting around this, apart from what @morrisond91 posted.

**Comment by vikiCoder** [comment]
We are currently working on this. We are adding RSA signature methods for OAuth1 in the upcoming release of the Postman app. I will update here when it is released.

**Comment by vikiCoder** [comment]
We've added RSA signature methods in Postman 7.27, please update or download the latest version of the app to check it out. 🙂
