### ISSUE TITLE
Can no longer import CURL

### ISSUE THREAD

**Issue by Redor** [a85/POSTMan-Chrome-Extension#2304]
1. Postman Version: 4.6.3
2. App (Chrome app or Mac app): Windows App
3. OS details: Windows 7
4. Is the Interceptor on and enabled in the app: no
5. Did you encounter this recently, or has this bug always been there: Recently
6. Expected behaviour: It should be possible to import CURL commands

Click on Import, go to the "Paste Raw Text". Add e.g. 

```
curl 'http://rmsol.de'
```

Error occurs: Error while importing Curl: Cannot read property 'convertCurlToRequest' of undefined

**Comment by vegetableman** [comment]
hey @Redor we are looking in to the issue and will have a fix out for it this week. Thanks for taking time to report it 👍 .

**Comment by grojguy** [comment]
I encountered this yesterday also.  Chrome app works.  Windows app does not.

**Comment by vegetableman** [comment]
@grojguy The issue is specific to the recent version : 4.6.3, available only for the native apps. We found the issue, a fix will be out soon this week.

**Comment by funwhilelost** [comment]
@vegetableman 👍  much appreciated.  Any workarounds in the meantime?  I just copied all the headers over for each `-H`... a bit tedious.

**Comment by grojguy** [comment]
@funwhilelost ... FYI, I am using the addon in Chromium for the time being, and it works there.  (I much prefer the native app however.)

**Comment by vinnyamp** [comment]
I'm facing the same problem, the previous version works fine, the problem is on 4.6.3.
For the time being I'll be using the Chrome version, it's still on 4.6.2 and works fine.

**Comment by SamvelRaja** [comment]
@vinnyamp @grojguy @funwhilelost @Redor  You can find the fix in our latest 4.7.0 update.
