### ISSUE TITLE
Url params has Chinese error

### ISSUE THREAD

**Issue by huijiewei** [a85/POSTMan-Chrome-Extension#2305]
1. Postman Version: 4.6.3
2. App (Chrome app or Mac app): Mac app
3. OS details: OSX 10.11.6
4. Is the Interceptor on and enabled in the app:
5. Did you encounter this recently, or has this bug always been there:
6. Expected behaviour:
7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
8. Screenshots (if applicable)

**Comment by a85** [comment]
@huijiewei Thanks for reporting this. Looking into the issue.

**Comment by SamvelRaja** [comment]
This is been fixed in the latest 4.7.2 kindly update your app and check the same.
