### ISSUE TITLE
Delay is not being added to collection run in app

### ISSUE THREAD

**Issue by Chough** [a85/POSTMan-Chrome-Extension#2306]
1. Postman Version: v4.6.3 
2. App (Chrome app or Mac app): Windows App
3. OS details: Windows 7 Enterprise x64 6.1.7601 SP1 7601
4. Is the Interceptor on and enabled in the app: No
5. Did you encounter this recently, or has this bug always been there: Recent
6. Expected behaviour: Collection runner adds delay between requests
7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
8. Screenshots (if applicable)

Steps to reproduce the problem:

From the Windows standalone app
Open collection runner
Add a delay (e.g. 500ms)
Run a collection

Note that there is no delay between requests.

I've ran the same scenario through Newman and the delay has been properly invoked.

**Comment by sdnts** [comment]
@Chough Thanks for reporting this. This has been fixed in our internal build and we'll push out a fix for this in the next release.

**Comment by vegetableman** [comment]
@Chough The bug has been fixed in the release v4.7.0. Check it out.
