### ISSUE TITLE
Script request object retains POST parameters even when method is changed to GET

### ISSUE THREAD

**Issue by mandrean** [a85/POSTMan-Chrome-Extension#2308]
1. Postman Version: 4.6.2
2. App: Chrome app
3. OS details: OS X El Capitan 10.11.5
4. Is the Interceptor on and enabled in the app: No
5. Did you encounter this recently, or has this bug always been there: For as few months at least, I think?
6. Expected behaviour: Should not send body with `GET` request
7. Screenshots:

![image](https://cloud.githubusercontent.com/assets/4631744/18170028/03487606-705d-11e6-9a89-403853c4cf8a.png)
![image](https://cloud.githubusercontent.com/assets/4631744/18169967/bb13964a-705c-11e6-91fa-96b7ca87a853.png)

Steps to reproduce the problem:

Send a `POST` request with a body. Switch to `GET` and send a new request.

Postman will imply that there is no body, since the option to see the body greyed out. But it still sends the old body from the previous `POST`! And you can't even clear the field without first switching to the `POST` method then back to `GET`.

**Comment by sdnts** [comment]
Hey @mandrean, thanks for reporting this.
The problem isn't that Postman is sending extra parameters with GET requests, it is that the `request` object is not being reset properly when you change your method from POST to GET. You can verify this by checking your Network tab in the DevTools. You'll see that the actual payload does not have those parameters in it.

As a side node, you should use just `request` to check what request is being sent (without `this`), as `this` will be deprecated soon. You can use `https://www.getpostman.com/docs/sandbox` for documentation regarding scripts in Postman.

**Comment by mandrean** [comment]
Hi @madebysid, thanks for quick response!

Anyway I can work around this issue (maybe with a Pre-Request Script?) before a stable release with a fix for this is released?

Edit: Never mind. I can just check the method and wipe `data: {}` if it's a `GET` or `DELETE`.
