### ISSUE TITLE
Windows app doesn't remember previous window state on startup.

### ISSUE THREAD

**Issue by wayne-werner** [a85/POSTMan-Chrome-Extension#2311]
1. Postman Version: v4.7.0
2. App (Chrome app or Mac app): Windows
3. OS details: Windows 10.1
4. Is the Interceptor on and enabled in the app: Don't know
5. Did you encounter this recently, or has this bug always been there: At least several weeks
6. Expected behaviour: Windows apps should restore window state on app startup to previous sessions state (window position, size, max state).

**Comment by SamvelRaja** [comment]
Hey @wayne-oscme we are facing an issue with remembering the window state in Windows version alone. We are having this in our list. And will update here once we reached the solution.

**Comment by vegetableman** [comment]
@wayne-oscme Thanks for reporting this 👍 .  The issue has been fixed in the latest version of the app. Could you verify?.

**Comment by wayne-werner** [comment]
I can indeed.  It is now working!  Thanks!

**Comment by sdnts** [comment]
Awesome! Closing this then.
