### ISSUE TITLE
Client certificates omitted in Runner

### ISSUE THREAD

**Issue by tdurden82** [a85/POSTMan-Chrome-Extension#2313]
1. Postman Version: 
   4.6.2
   1. App (Chrome app or Mac app): 
      Mac App
   2. OS details: 
      OS X El Captain 10.11.6
   3. Is the Interceptor on and enabled in the app: 
      Negative
   4. Did you encounter this recently, or has this bug always been there: 
      Recently
   5. Expected behaviour: 
      When a collection is executed via Runner, it uses the certificates just like when executed via the main Postman screen
   6. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
   7. Screenshots (if applicable)
      ![postmanconsole-runnercertnoworky](https://cloud.githubusercontent.com/assets/10553256/18288876/c15165b6-7442-11e6-8157-cd34efe3f573.png)

Steps to reproduce the problem:
1.) Run a collection that uses a certificate for authentication and observe successful execution and observe certificates included in log.
2.) Run the collection in Runner and observe and observe failed execution and lack of certificates included in log.

**Comment by sdnts** [comment]
We've fixed this in our local build, and will be rolling out a release very soon.

**Comment by SamvelRaja** [comment]
@tdurden82 We patched this up in our latest 4.8.0 release. Kindly update and test the same from your end 😄
