### ISSUE TITLE
[Feature Request] - Ability to sync collections and environments from version control (git)

### ISSUE THREAD

**Issue by tariqghalib** [a85/POSTMan-Chrome-Extension#2315]
**Feature Statement:**
If we could add the ability to sync latest collections and environments from the version control (git) that will be of great value. Currently every time I share an update with the team, they have to manually delete and upload new collections and environments. Its a tedious task to do. I do know that there is cloud service available but support for other version controls will add to postman value as a standalone tool.

**Version/App Information:**
1. Postman Version: 4.6.2
2. App (Chrome app or Mac app): Chrome
3. OS details: Windows 7 professional
4. Is the Interceptor on and enabled in the app: Yes
5. Did you encounter this recently, or has this bug always been there: Its a default behavior from the start
6. Expected behavior: Ability to sync latest collections and environments from git

**Comment by stianlagstad** [comment]
I see value in this even though we're using the cloud service. Instead of having multiple collections (one for each version of our APIs), version control and tagging would make life easier.

**Comment by sdnts** [comment]
@stianlagstad @tariqghalib This is on our roadmap. :D Will keep you updated regarding progress here.

**Comment by kbatyai** [comment]
Would be great to work on collections saved to normal files... (stored in on-prem GIT)

**Comment by jongio** [comment]
+1 Feeling the collection versioning pain atm.

**Comment by allyn-psyonix** [comment]
Our team is looking for a similar solution. We would like to be able to commit our postman tests to our git repo and include them with PRs to be code reviewed with the feature being tested. The next step would be the ability to specify a branch to run a collection from via Newman for automated build pipeline integration.

1) Commit feature changes and postman tests to new branch
2) Submit PR for review, which includes the code, unit tests, and postman tests
3) Build server builds and deploys the branch, runs unit tests, and runs postman tests **for that branch**
4) PR is approved and merged to master
5) Postman client stays in sync as branch changes. Either it monitors the local disk and updates as the files change from external git commands, or it syncs with an explicit branch on a remote git server directly (e.g. specify which branch within Postman).

We are at the point in our build process where this is one of the next big improvements we would like to make. While I really hope Postman supports this in the future, we are currently looking at alternative options given that this or related features have been requested as far back as 5 years here.

**Comment by kbatyai** [comment]
Still would be great to have and on-prem collection maintanance, instead of forcing subscription-cloud-model... or at least be honest here about you will never support this because of business goals...

**Comment by vkaegis** [comment]
Hey guys! We've made an RFC to document our ideas on version control in Postman, would love your thoughts and feedback on it:

https://community.getpostman.com/t/version-control/2715

**Comment by vkaegis** [comment]
Hey guys, you can now fork collections and merge changes back between them (as of v6.7.1). 

This provides a basic level of versioning and being able to manage changes between collections. We'll also be adding integrations to native git systems which can work with our versioning constructs, and also allow tagging of collection versions which can map with your changes to code repos. No ETA on all these just yet, but I'm gonna keep this issue open till we have all that.

Feel free to open another issue if you have specific feedback around the current implementation.

**Comment by jackw3434** [comment]
> Our team is looking for a similar solution. We would like to be able to commit our postman tests to our git repo and include them with PRs to be code reviewed with the feature being tested. The next step would be the ability to specify a branch to run a collection from via Newman for automated build pipeline integration.
> 
> 1. Commit feature changes and postman tests to new branch
> 2. Submit PR for review, which includes the code, unit tests, and postman tests
> 3. Build server builds and deploys the branch, runs unit tests, and runs postman tests **for that branch**
> 4. PR is approved and merged to master
> 5. Postman client stays in sync as branch changes. Either it monitors the local disk and updates as the files change from external git commands, or it syncs with an explicit branch on a remote git server directly (e.g. specify which branch within Postman).
> 
> We are at the point in our build process where this is one of the next big improvements we would like to make. While I really hope Postman supports this in the future, we are currently looking at alternative options given that this or related features have been requested as far back as 5 years here.

This is exactly the sort of thing i am looking for.
Have you found any alternative options for this?

**Comment by allyn-psyonix** [comment]
> We'll also be adding integrations to native git systems which can work with our versioning constructs, and also allow tagging of collection versions which can map with your changes to code repos. No ETA on all these just yet, **but I'm gonna keep this issue open till we have all that**.

(emphasis mine)

Does the closing of this ticket mean that the other mentioned features in the quote have been implemented? Just looking to clarify since it was closed without comment.

**Comment by allyn-psyonix** [comment]
> This is exactly the sort of thing i am looking for.
> Have you found any alternative options for this?

Not yet
