### ISSUE TITLE
Native App Profile Switcher (multiple profiles / multiple users)

### ISSUE THREAD

**Issue by tclift** [a85/POSTMan-Chrome-Extension#2316]
I use Postman with 3 separate Google Accounts, each with separate collections and environments (thank you!). Using the Chrome App, this is all kept separate automatically. The app is simply installed 3 times, with my email address in the app name to disambiguate (e.g. in Spotlight).

With Chrome Apps eventually going away, it would be very helpful to have a profile switcher in the native app so that I can switch between them (without having to do a full logout, which deletes profile data and requires re-authentication).

I imagine that it could just switch out the active credentials, re-initialising the app if required (i.e. it wouldn't have to be doing anything in the background, such as syncing, with the other profiles).

**Comment by a85** [comment]
@tclift Yep. This is on our roadmap but with the main intention of supporting multiple teams. Any reason you had to keep collections and environments separate?

**Comment by tclift** [comment]
@a85 just to separate work & work & play :)

**Comment by bcodermicro** [comment]
I second this ability...

**Comment by derpoho** [comment]
Is there any update on this issue?

**Comment by milan-tradecore** [comment]
Hi, is there any update on this? It'd be very helpful indeed, if I may say so myself.

edit: the concept that slack has with multiple teams would fit perfectly.

**Comment by emmanuelt88** [comment]
Any update on this? this would be quite helpful!

Thanks for the great work you do!

**Comment by OmarKan** [comment]
Any update on this ? 

It's VERY helpful to have this feature, I personally use 4 Accounts for postman, as I work with 4 different teams on 4 different projects, and each of them require a different email address.

**Comment by mlg-mario** [comment]
Any update on this?

**Comment by o15a3d4l11s2** [comment]
I believe this is now possible in the app.

From the changelog (part of it):

> 5.3.1 18 Oct, 2017
> You can now add multiple user accounts and switch between them seamlessly

**Comment by SamvelRaja** [comment]
@o15a3d4l11s2 mentioned, adding multiple user accounts and switching between them is available in our native apps v5.3.1
