### ISSUE TITLE
postmanclient: does not support non-ascii argument value in query str

### ISSUE THREAD

**Issue by boisde** [a85/POSTMan-Chrome-Extension#2317]
1. Postman Version: <code>4.7.0</code>
2. App (Chrome app or Mac app): <code>Mac app</code>
3. OS details: <code>Version 10.11.6 (15G1004)</code>
4. Is the Interceptor on and enabled in the app:<code>No</code>
5. Did you encounter this recently, or has this bug always been there: <code>always</code>
6. Expected behaviour:
   - <code>Directly input non-ascii str argument into query string as params of a request, and postman client will do the url-encode correctly for that argument and then send it to the web server.</code>
7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
8. Screenshots (if applicable)
   <img width="1088" alt="sc1" src="https://cloud.githubusercontent.com/assets/72353/18378564/54edd0e8-76a0-11e6-9f35-f5ce19bbf5d0.png">
9. Steps to reproduce the problem:
   - `just input some non-ascii argument(for example Chinese) into postman client as part of the query string will result in falsely encoded request uri sent to the server.`

**Comment by yarcowang** [comment]
Yes, I have the same error.

**Comment by linxiang-dev** [comment]
same here
Mac app version 5.1.2, does not support the Chinese url params
but chrome app works fine

**Comment by sdnts** [comment]
I believe this should be solved now. I was able to send a Unicode character to the [Postman Echo](https://postman-echo.com/get?a=😀) server successfully using Postman with the latest version (6.0.10). Please let me know if it isn't working as expected for you, and I'll reopen!
