### ISSUE TITLE
Duplicating a test case should put the new test case immediately below the original one

### ISSUE THREAD

**Issue by megadix** [a85/POSTMan-Chrome-Extension#2318]
1. Postman Version: 4.7.0
2. App (Chrome app or Mac app): Mac app
3. OS details: Mac OS X 10.11.5 El Capitan
4. Is the Interceptor on and enabled in the app: No
5. Did you encounter this recently, or has this bug always been there: Always been there
6. Expected behaviour: duplicating a test case should put the new test case immediately below the original one

Steps to reproduce the problem:
- add many test cases (ideally fill the whole screen)
- select one of the first test cases
- duplicate test case
- wrong behavior: the new test case is added as last, making it disappear from screen

Suggested behavior:
Putting the cloned test case right below the original one would make editing faster, more reliable and pleasant.

**Comment by a85** [comment]
This is fixed in the latest versions of the app.
