### ISSUE TITLE
Unable to connect to my account, after login

### ISSUE THREAD

**Issue by rvnath** [a85/POSTMan-Chrome-Extension#2319]
1. Postman Version:  4.7.0
2. App (Chrome app or Mac app):  Chrome App
3. OS details: Linux Mint (Linux / x86-64)  chrome 52.0.xxxx
4. Is the Interceptor on and enabled in the app: yes
5. Did you encounter this recently, or has this bug always been there:  Recently, when I switched to a new m/c having linux mint 18.  It was working fine on linux mint 17 Rafaela.
6. Expected behaviour:
7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
8. Screenshots (if applicable)
   screen shot attached
   ![postman-sync-fail](https://cloud.githubusercontent.com/assets/4309494/18409210/a4c3e89a-775f-11e6-8be1-127ade732640.png)

**Comment by vegetableman** [comment]
@rvnath Could you post a screenshot of the console tab?

**Comment by rvnath** [comment]
Sorry for late reply. Here is the screenshot of the console window.
![postman](https://cloud.githubusercontent.com/assets/4309494/18947205/b589ae9a-864f-11e6-8813-8b8d5bc9a059.png)

**Comment by rvnath** [comment]
Also adding the expanded view of stacktrace for websockets error.
![postman2](https://cloud.githubusercontent.com/assets/4309494/18947302/249c6c8c-8650-11e6-8f4b-b99412215b82.png)

**Comment by rvnath** [comment]
Hello Friends,  Is there an update to this problem...?
regards.

**Comment by a85** [comment]
@rvnath Please email us at help@getpostman.com for account specific issues. The support team will help you sort it out.

**Comment by murat** [comment]
Hi, is this resolved? Same issue is happening on my Linux desktop. 

OS: Linux Mint 18 Cinnamon x64
Chromium: Version 60.0.3112.113 (Developer Build)
Postman: Postman for Linux Version 5.2.0 linux 4.10.0-33-generic / x64

Console output:

```shell
sails.io.js:5 WebSocket connection to 'wss://sync-xi.getpostman.com/socket.io/?__sails_io_sdk_version=0.11.0&__sai…tform=browser&__sails_io_sdk_language=javascript&EIO=3&transport=websocket' failed: Connection closed before receiving a handshake responsews @ sails.io.js:5WS.doOpen @ sails.io.js:4Transport.open @ sails.io.js:3Socket.open @ sails.io.js:3Socket @ sails.io.js:3Socket @ sails.io.js:3Manager.open.Manager.connect @ sails.io.js:3(anonymous function) @ sails.io.js:3wrapped @ xml.js:22
sails.io.js:142 🌏 error establishing connection with sync service.
 Error: websocket error(…)
sails.io.js:142 🌏 scheduled reconnection attempt #6 after 60000ms
```

Note: What's interesting is: the chrome app is running normally. :thinking:

**Comment by sdnts** [comment]
We had to do an unscheduled maintenance on our servers. Can you try again in a couple of hours? Thanks for the patience.
