### ISSUE TITLE
long numeric values get truncated after 16 digits when extracting from JSON

### ISSUE THREAD

**Issue by mad666** [a85/POSTMan-Chrome-Extension#2320]
1. Postman Version: 4.7.0
2. App (Chrome app or Mac app): Chrome App, Chrome 53.0.2785.101
3. OS details: Windows 7 x64 Enterprise SP1
4. Is the Interceptor on and enabled in the app: tried on and off
5. Did you encounter this recently, or has this bug always been there: didn't use the feature before
6. Expected behaviour: values from JSON response get correctly written to environment
7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app): watchdog checking connection health
8. Screenshots (if applicable)

use the following code in "tests" section of a request:

`var jsonData = JSON.parse(responseBody);
postman.setEnvironmentVariable("key", jsonData.key);`

the value gets written but diffeers from value in JSPON response for the last three digits.
example:
3007107488898323462 -> 3007107488898323500

**Comment by sdnts** [comment]
Hey @mad666, this is a limitation with JavaScript itself. JS only has about 16 digits of precision, which is why you lose information. One work-around could be to use strings instead of numbers.
Closing as there's nothing we can do about this really 😛
