### ISSUE TITLE
Documentation Request: Windows Application client certificate changes require clarification

### ISSUE THREAD

**Issue by goldbergjeffrey** [a85/POSTMan-Chrome-Extension#2321]
1. Postman Version: **4.7.0 win32 10.0.10586 / x64**
   1. App (Chrome app or Mac app): **Windows App**
   2. OS details: **Windows 10**
   3. Is the Interceptor on and enabled in the app: **No**
   4. Did you encounter this recently, or has this bug always been there: **First seen on 12-September-2016**
   5. Expected behaviour: Prompt for client certificate, certificate authentication works and receive response from rest api.  A recent development with the Windows app is that it no longer connects to rest apis using certificate auth when using client certs that are self-signed, even when SSL certificate verification is turned off.  When verification is turned off, 403 errors appear.  

This appears to be due to a change in the way Postman handles client certs.  It doesn't appear to use the Windows certificate store like it used to and still does in the Chrome App.

Once I created a pem version of my cert and pointed it to the proper endpoint in settings the Windows app works again.

Steps to reproduce the problem:

Fire up Postman Windows App, try to connect to a rest endpoint that used to work using a certificate in the current user store.  It no worky.

Turn off self-signed cert verification.  Try again.  Still no worky.

Add cert to certificate settings in Postman and it worky!

**Comment by shartvig** [comment]
I have the same problem in the windows app, but even adding the PEM as Key file, doesnt make it work, are you also supplying a CRT file ? It's not very clear which kind of keyfile should be used.

I've also tried with a PKCS12 file, but none of this work.

Would be nice with some documentation on the add certificate tab.

**Comment by abhijitkane** [comment]
@shartvig We have docs on client certs here - https://www.getpostman.com/docs/postman/sending_api_requests/certificates.
