### ISSUE TITLE
generated cURL code does not encode single quotes properly

### ISSUE THREAD

**Issue by janeklb** [a85/POSTMan-Chrome-Extension#2322]
1. Postman Version: 4.7.0
2. App (Chrome app or Mac app): Chrome
3. OS details: Xubuntu 16.04
4. Is the Interceptor on and enabled in the app: No (not proactively at least..)
5. Did you encounter this recently, or has this bug always been there: Recently (First time i tried to do this)
6. Expected behaviour: That generated cURL code works in my terminal
7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app): nothing relevant in the postman dev tools log
8. Screenshots (if applicable): none

To replicate:
- Create a new request to any url (eg. http://localhost/)
- in the _Body_ tab, select _raw_ and add a stringified JSON object with a couple single quotes in one of the values. ie.
  - `{ "prop": "this is a 'value'" }`
- click on _generate code_ and select _cURL_
- you should see output like this:
  - `curl -X POST -H "Cache-Control: no-cache" -H "Postman-Token: d27cf817-b646-c9fd-cfac-ab5169b5e8da" -d '{ "prop": "this is a '"'"'value'" }' "http://localhost/"`

The issue:
- running this command in both `sh` and `bash` will leave the prompt up, as if the command input contains some un-terminated value. eg. you see a `>` after pressing enter.
- if the generated code is pasted into a new file (`postman`)..
- .. and run via bash (`bash postman`) you get: 

```
postman.sh: line 1: unexpected EOF while looking for matching `"'
postman.sh: line 2: syntax error: unexpected end of file
```
- .. and run via sh (`sh postman`) you get:

```
postman.sh: 2: postman.sh: Syntax error: Unterminated quoted string
```

**Comment by SamvelRaja** [comment]
@janeklb   Thanks for bringing this to our notice. We are looking into this issue. will let you know the status here.

**Comment by vegetableman** [comment]
@janeklb Checkout the latest update. feel free to reopen if the issue still exists ^_^.

**Comment by janeklb** [comment]
Thanks @vegetableman looks good to me :)
