### ISSUE TITLE
Chrome Request throttled (Anti-DDoS)

### ISSUE THREAD

**Issue by soundstep** [a85/POSTMan-Chrome-Extension#2323]
I've got a suite tests and one of them is testing a 500 response.
I noticed when I run it against a remote url more than a few times the request are throttled by chrome:

![screen shot 2016-09-13 at 11 49 16](https://cloud.githubusercontent.com/assets/133293/18471171/7f728a1a-79a8-11e6-89f7-2a31b23701a1.png)

![screen shot 2016-09-13 at 11 52 54](https://cloud.githubusercontent.com/assets/133293/18471200/a3e7513c-79a8-11e6-8cd1-c2d0b1fcc754.png)

More information there:
http://dev.chromium.org/throttling

Note that several iterations against a 500 status code is working well with newman or against a localhost url.

Any idea how I can run the Postman chrome app with this flag? ``--disable-extensions-http-throttling`
Or is it an option that could be inside postman itself?

Thanks  for any light on this.

**Comment by zaipie** [comment]
You can add the flag to the shortcut to Postman:
![postman throttling](https://cloud.githubusercontent.com/assets/15891409/25849060/391685f0-34bd-11e7-9d88-9c3699b56ad4.PNG)

Full link in my case will be:
```"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" --profile-directory=Default --app-id=fhbjgbiflinjbdggehcddcbncdddomop --disable-extensions-http-throttling```

Note that this doesn't seem to work when Chrome is already running.

**Comment by abhijitkane** [comment]
@soundstep There's nothing we can do from in the application to prevent this. I'd recommend switching to our native apps (https://www.getpostman.com/apps).
