### ISSUE TITLE
Could not get any response on Windows App

### ISSUE THREAD

**Issue by marekpetak** [a85/POSTMan-Chrome-Extension#2324]
Hi, Im using Postman for Windows app version 4.7.1 on Windos 8.1 64bit on company proxy (using user name and password). Default config. I do not use interceptor.

Every request ends up with an error Could not get any response and history is not recorded as well.
If I run the same request on Chrome App on the same PC, all works fine

DevTools console does not show any errors, it does not show anything at all ...

![screenshot](https://cloud.githubusercontent.com/assets/7045818/18504334/ad4c0900-7a59-11e6-9d1a-1ade5a3e142a.PNG)

**Comment by SamvelRaja** [comment]
@marekpetak Can you get me a screen shot of our **PostmanConsole** (View -> Show postman console or Cmd+Alt+C)
It will show the proxy details there.

**Comment by marekpetak** [comment]
deleted is the domain name. so it looks like is using the domain name instead of proxy IP ... is this settable somewhere or just using system default?

![screenshot](https://cloud.githubusercontent.com/assets/7045818/18504607/0f273054-7a5b-11e6-8b90-47f3456c0cce.PNG)

**Comment by SamvelRaja** [comment]
@marekpetak Postman will take up the Proxy details available in the Internet options of  your system, Can you check whether it is there properly. 

Also, let me know how you are setting the proxy, through Proxy auto configuration(PAC) or directly providing proxy details in the `Internet options -> Connections -> Lan Settings`

**Comment by marekpetak** [comment]
manualy set IP:PORT and is using my domain login/password

**Comment by SamvelRaja** [comment]
Hey @marekpetak I believe there is no way to provide username and password for proxy server in windows by directly.  Also, at present we are working on a feature to bring in all the proxy setting inside the Postman itself which will eventually have the username and password support also, I hope that will fix your problem.

**Comment by marekpetak** [comment]
No as far as I'm aware. Similiar behind proxy settings is required for GIT where I need to set .gitconfig 
proxy = domain%5Cusername:password@IP:PORT, although the solution is not perfect as plain text password is being stored in .gitconfig.

**Comment by id0Sch** [comment]
not getting a response as well (mac)
i'm getting a response when using generated curl code + chrome

**Comment by chuck-wood** [comment]
I'm using 4.10.7 and there's still no way to set a proxy in Postman. Any idea when this feature will be available? (I can't set a system-wide proxy because only certain hosts I'm trying to access require the proxy.)

**Comment by abhijitkane** [comment]
@chuck-wood Can you try updating to 5.2.0? Native apps now support custom proxy configurations (Settings > Proxy).
