### ISSUE TITLE
Body not generated in code snippet when stored in environment variable

### ISSUE THREAD

**Issue by S33G** [a85/POSTMan-Chrome-Extension#2325]
Postman Version 4.6.3 (4.6.3) Mac OS 10.11.6 (15G31)
No Interceptor

First time I've used 'Generate Code' with environment variables

I expected postman to generate my code into a file, with the header and body present.
However, in certain languages, when the body is stored in an environment variable. The body is not included as part of the code generation.

No errors in console log.

---

Screenshots / Steps to reproduce.

I have a json string as an environment variable which is in the body of my request
![screen shot 2016-09-14 at 2 09 19 pm](https://cloud.githubusercontent.com/assets/655807/18513312/efc1a5f8-7a84-11e6-9be0-339b6328dc8b.png)

If I generate a Curl request, the body is included. Great.
![screen shot 2016-09-14 at 2 09 58 pm](https://cloud.githubusercontent.com/assets/655807/18513332/fabab152-7a84-11e6-8128-813331fa0266.png)

But with PHP and lots of others, the request body is missing.
![screen shot 2016-09-14 at 2 09 36 pm](https://cloud.githubusercontent.com/assets/655807/18513318/f47be0ea-7a84-11e6-9e5c-ae8a98023303.png)

If I copy the json directly into the body (bypassing the environment variable), everything works as expected.

**Comment by S33G** [comment]
Actually, so far the only language I can get to output the body from environment variables is the default (HTTP)

**Comment by sdnts** [comment]
@charj-it The latest version (4.9) has fixes that should solve your issue. Can you update and confirm?

**Comment by S33G** [comment]
Apologies for the delayed response.
From what I can see the issue I reported has been resolved.

Keep up the good work guys! 👍
