### ISSUE TITLE
Content-Type for x-www-form-urlencoded is not set automatically

### ISSUE THREAD

**Issue by stephan-gruen** [a85/POSTMan-Chrome-Extension#2326]
1. Select Body -> raw
2. Select XML
3. Switch to Headers -> Content-Type is set to "text/xml"
4. Select Body -> x-www-form-urlencoded
5. Switch to Headers -> Content-Type is still set to "text/xml", but should be set to "application/x-www-form-urlencoded"

**Comment by SamvelRaja** [comment]
@stephan-gruen  Thanks for bringing this to our notice. This would be available in our next version.

**Comment by vegetableman** [comment]
@stephan-gruen The issue has been fixed in the latest version `4.7.2`. Check it out.
