### ISSUE TITLE
ReferenceError xmlToJson is not defined windows app

### ISSUE THREAD

**Issue by rhull007** [a85/POSTMan-Chrome-Extension#2330]
Using newest  Windows version (4.7.1 win32 6.1.7601 / x64)  of postman get following error  trying to use the below
var jsonObject = xmlToJson(responseBody);

There was an error in evaluating the test script:  ReferenceError xmlToJson is not defined

Works fine in Chrome version

1. Postman Version:
2. App (Chrome app or Mac app):
3. OS details:
4. Is the Interceptor on and enabled in the app:
5. Did you encounter this recently, or has this bug always been there:
6. Expected behaviour:
7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
8. Screenshots (if applicable)

**Comment by sdnts** [comment]
Hey @rhull007, the function xmlToJson is deprecated, so you should use xml2Json in your test script. You can find docs about the test sandbox [here](https://www.getpostman.com/docs/sandbox)

Closing this, feel free to reopen if this doesn't fix you issue

**Comment by rhull007** [comment]
Update , you can ignore this. Figured it out.
console.log(jsonObject.person.$.name);

//////////////////////

Oh ok, thanks for the info. Dang well  I'm trying  to rework my test cases and cant find any example with how to traverse the new xml tree, I keep getting undefined on attributes, so any input would be appreciated!

XML example  -- >< person name="ryan"/>
var jsonObject = xml2Json(responseBody);
console.log(JSON.stringify(jsonObject));  -->{"person":{"$":{"name":"ryan"}}}
console.log(jsonObject.person)  --> //OK
console.log(jsonObject.person.name)  -->  undefined

I dont understand how the $ fits in since it never showed in XmlToJson
Much thanks, I'm trying to get the rest of my department to use Postman,  fantastic tool!
