### ISSUE TITLE
OAuth 1.0 works for GET and POST but fails for DELETE

### ISSUE THREAD

**Issue by crunchytom** [a85/POSTMan-Chrome-Extension#2332]
1. Postman Version: 4.7
2. App (Chrome app or Mac app): Chrome app
3. OS details: OSX 10.11.12
4. Is the Interceptor on and enabled in the app: no
5. Did you encounter this recently, or has this bug always been there: N/A
6. Expected behaviour: OAuth signature match
7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
8. Screenshots (if applicable)

use OAuth 1.0 for an endpoint with the DELETE method.  fails due to signature mismatch.  same request working fine in Paw, other clients.  The string that postman is signing to generate the oauth signature should start with the method (uppercase) -- and it must be wrong?  or some other segment of the string could be missing/wrong.

btw, paw has a great feature where you can view the base signature string that is being signed, it would be super-useful to expose that somewhere in postman so we can see what string postman is signing; this would have saved me a couple hours of digging around in our perfectly-fine server-side oauth code.

**Comment by SamvelRaja** [comment]
@crunchytom  Thanks for bringing this to our notice we will keep posting the status on this issue here.

**Comment by kamalaknn** [comment]
@crunchytom you can view the OAuth 1 signature and the Header by opening the Postman console. `View -> Show Postman Console` should open up the console for you. 

Is there something that is not part of the request information in Console that you are looking for in particular?
