### ISSUE TITLE
application/jwt response opens download prompt

### ISSUE THREAD

**Issue by felixfbecker** [a85/POSTMan-Chrome-Extension#2333]
1. Postman Version: 4.7.1
2. App (Chrome app or Mac app): Windows Electron app
3. OS details: Windows 10 Pro x64
4. Is the Interceptor on and enabled in the app: no
5. Did you encounter this recently, or has this bug always been there: it was introduced in a recent update
6. Expected behaviour: Just show the response like text, don't open a download prompt
7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
8. Screenshots (if applicable)

When doing a request to an endpoint that returns a [JSON Web Token](https://jwt.io/) with the (correct, IANA-registered) Content-Type `application/jwt`, a download prompt is shown to save the response. This doesn't make much sense and makes it complicated to copy+paste the token into an Authorization header. This is only since a recent update. A JWT is just a single line of Base64-encoded JSON.

**Comment by a85** [comment]
@czardoz Is this a runtime issue?

**Comment by sdnts** [comment]
@felixfbecker We've identified this issue and a fix should be released today. Will keep you in the loop :)

**Comment by jbrunken** [comment]
Just as an FYI, this is happening for .m3u8 playlist files as well (at least on the Mac version).   They are text files but it's prompting for a download.   Content-Type is application/vnd.apple.mpegurl

**Comment by felixfbecker** [comment]
It seems to me that Postman simply opens a download prompt that is any `application/*` Content-Type, except some known ones like `application/xml`. Instead, it should rather decide based on the charset. If it is a UTF-8, ASCII or ISO-whatever charset it should be displayed in the app. If it is binary (and not something it can display like an image), it should be downloaded.

Actually, I would prefer if Postman _never_ automatically downloads a file. You can always click "Send and download" explicitely, but the default action for "Send" should be to display the response in the app, even if it is binary. The use case for downloading is much smaller than the possibility of having a text type detected falsely as something binary to download.

**Comment by shamasis** [comment]
@felixfbecker the issue is with previewing it. It will be addressed if we decide the following:
- all responses are rendered as text
- known set of responses are syntax highlighted or sent for auto preview for non test
- remaining always render as RAW text.

Thoughts?

**Comment by felixfbecker** [comment]
So basically
- "Send" never downloads
- "Send and download" always downloads
- "Raw" tab always displays text
- "Pretty" always tries to syntax highlight based on Content-Type (but can be changed with dropdown)
- "Preview" always previews like a browser would (HTML, images, svgs, audio file, PDFs, ...)

?

**Comment by shamasis** [comment]
It's actually the preview that triggers downloads! 
- you'll be surprised how many servers do not return accurate or any content type. 
- many have content that browser has no way to render it.

**Comment by felixfbecker** [comment]
Oh, of course, makes sense! Is it not possible to "suppress" _any_ download prompt by the preview?

**Comment by shamasis** [comment]
No. the preview is done by encoding the content to an iframe. And we have no control what is accepted by the iframe and what is not.

**Comment by sdnts** [comment]
@felixfbecker `application/jwt` along with more mime types should now show up as text (in 4.7.2), could you confirm?

**Comment by felixfbecker** [comment]
Fixed, thanks!
