### ISSUE TITLE
Why Postman App for chrome send requests to *.top domains?

### ISSUE THREAD

**Issue by deanilenko** [a85/POSTMan-Chrome-Extension#2334]
1. Postman Version: Postman 4.7.1
2. App (Chrome app or Mac app): Chrome app
3. OS details: Ubuntu 16.04.01
4. Is the Interceptor on and enabled in the app:
5. Did you encounter this recently, or has this bug always been there: not sure
6. Expected behaviour: don`t send any statistic
7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app): have no logs
8. Screenshots (if applicable):

hello!

I sent get request to:  http://api.nestoria.co.uk/api?country=uk&pretty=1&action=search_listings&encoding=json&listing_type=buy&page=1&place_name=leeds .

and after some period of time, my IPS system caught next:

GET /user/4x3emraycqzlpdvstig7uhj0nbw896ko/156645/page?url=http%3A%2F%2Fapi.nestoria.co.uk%2Fapi%3Fcountry%3Duk%26pretty%3D1%26action%3Dsearch_listings%26encoding%3Djson%26listing_type%3Dbuy%26page%3D1%26place_name%3Dleeds&iframe= HTTP/1.1
Host: otherwaydo.top
Connection: keep-alive
Cache-Control: no-cache
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36
Postman-Token: bc3b2e1c-3d47-a4c3-f3ef-ad167c2f677c
Accept: _/_
Accept-Encoding: gzip, deflate, sdch
Accept-Language: ru,en-US;q=0.8,en;q=0.6
Cookie: __cfduid=db930a8895fdf18f974d2ca0bcdb6a9fe1474297591

What is it?

PS send anonymous usage data disabled: http://dl2.joxi.net/drive/2016/09/19/0009/1497/611801/01/19700e0b27.jpg

**Comment by abhijitkane** [comment]
@deanilenko Can you check the Network tab of the DevTools window (https://www.getpostman.com/docs/errors)? Make sure `All` and `Preserve log` are enabled. This will log out any requests made via Postman.

You should see one entry for the request you're manually making through Postman. Is there a second entry for the `/user/4x3emraycqzlpdvstig7uhj0nbw896ko` URL too?

**Comment by deanilenko** [comment]
After i enabled debug, i tried several times, but i could not get this issue any more. i will try to do this a bit latter

**Comment by a85** [comment]
Closing for now until confirmed.
