### ISSUE TITLE
Folder with unicode character not working perfect

### ISSUE THREAD

**Issue by siczmj** [a85/POSTMan-Chrome-Extension#2337]
That was my idea I start using some unicode charater (💻, 📱) for better user experience. But it seems that this is a problem in some places. Sync working perfect, but not working the follows:
- Share collection link failed (only blink the hidden panel when click "Get Link" button)
- Online docs not show the folder name. (see attachment please).
- Import failed when using "Import From Link" (I see by interceptor not download full JSON response on network. Break at first unicode character)

> {
>     "id": "a0261fa7-7624-399d-1e9d-61b7566f4c95",
>     "name": "BET",
>     "description": "",
>     "order": [],
>     "folders": [
>         {
>             "id": "191534f8-b7cf-6ac9-c513-917e4c0a1866",
>             "name": "

Version/App Information:
1. Postman Version: 
   4.7.1
2. App (Chrome app or Mac app): 
   Chrome app
3. OS details: 
   win / x86-32
4. Is the Interceptor on and enabled in the app: 
   yes
5. Did you encounter this recently, or has this bug always been there: 
   yes
6. Expected behaviour: 
   maybe
7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
   Only when I use "Import from url". I think the problem same because the folder name contains Unicode character.
8. Screenshots (if applicable)

![folder_unicode_1](https://cloud.githubusercontent.com/assets/11421161/18707558/ef5e600c-7ff6-11e6-80d4-ba1b4fccdb42.jpg)
![folder_unicode_2](https://cloud.githubusercontent.com/assets/11421161/18707557/ef591c64-7ff6-11e6-960c-8fde5d876d4b.jpg)

**Comment by sdnts** [comment]
@siczmj Thanks for reporting this.
I was able to reproduce the unicode characters not showing in the documenter, we're working on a fix for that. 
However, I was able to import the collection properly (I made a GitHub Gist, and used that link to import by URL in the app with the interceptor on). Can you share the link you use to import your collection? If it contains private info, make a dummy collection and share that so I can replicate the issue :)

**Comment by siczmj** [comment]
Hi @madebysid,
I created a new collection for testing this issue:
https://www.getpostman.com/collections/f9e517a1d75bf4105c00
All problem occurs.

Here is a new attachment for demonstrate Share "blinking":
![collection-link_get-link_flash_only](https://cloud.githubusercontent.com/assets/11421161/18722779/5162c42a-8036-11e6-8de6-4e9f7652b681.gif)
(Yes, I can copy the postman share url because I am a really fast :D)

I used the follow characters:
http://www.fileformat.info/info/unicode/char/1f4bb/index.htm
http://www.fileformat.info/info/unicode/char/1f4f1/index.htm

Everything works after removed unicode characters.
I hope it was helpful.

**Comment by sdnts** [comment]
Ah I get it now, was able to reproduce. We'll get on a fix

**Comment by a85** [comment]
@madebysid Was this fixed?

**Comment by sdnts** [comment]
@a85 Not yet, some services still do not support Unicode completely.

**Comment by kwood-netrist** [comment]
@madebysid Just wondering if you have a timeline on Unicode support. We'd love to be able to share unicode characters in the body of POSTs in our collection.

**Comment by sdnts** [comment]
This should be working as expected now on the latest app version (6.0.10 as of now). Closing this. Please let me know if it doesn't, and I'll reopen
