### ISSUE TITLE
OAuth1 still failing in latest version (windows desktop)

### ISSUE THREAD

**Issue by Ian1971** [a85/POSTMan-Chrome-Extension#2339]
I am still unable to migrate to the windows desktop version because OAuth1 is not working correctly.
Previously it was added empty params (even if not specified). Now it seems to have a erroneous comma

e.g.
Header = OAuth ,oauth_consumer_key-...

that comma before oauth_consumer_key shouldn't be there, and isn't in the chrome version.

Thanks!

**Comment by sdnts** [comment]
@Ian1971 We have fixed this in our internal build, and we'll release a fix today. You can track the issue [here](https://github.com/postmanlabs/postman-app-support/issues/2312).

Closing as duplicate
