### ISSUE TITLE
Files not properly attaching to multipart/form-data request in v4.7.2 on Linux Mint

### ISSUE THREAD

**Issue by LeWestopher** [a85/POSTMan-Chrome-Extension#2340]
1. Postman Version: 4.7.2
2. App (Chrome app or Mac app): Chrome
3. OS details: Linux Mint 17.3
4. Is the Interceptor on and enabled in the app: I've tested with interceptor on and off.
5. Did you encounter this recently, or has this bug always been there: Recently
6. Expected behaviour: When selecting a file for a key/value type in multipart, it should attach the file to the request.
7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
8. Screenshots (if applicable)

I cannot get files to attach to a multipart form request properly using Postman v4.7.2.  The key is being added to the request, but the filename is "" and there is no file data within the form boundary.  I can confirm this by viewing the raw HTTP message or any other format that Postman converts to.  Screenshots below with Console screenshots.
1. I select the file named `helpdeskimages.zip` and attach it to the `uploadFile` key in the multipart-formdata section:
   ![pm_issue_1](https://cloud.githubusercontent.com/assets/5728795/18763522/66c373a8-80d3-11e6-82e7-9cbc3a2aeedf.png)
2. I check the raw HTTP request.  No form data included in the request.
   ![pm_issue_2](https://cloud.githubusercontent.com/assets/5728795/18763521/66ba8fcc-80d3-11e6-9ae5-d28f4cc5defd.png)

2A. An alternate view of the request, converted to a Node.js request.
![screenshot from 2016-09-22 14 51 14](https://cloud.githubusercontent.com/assets/5728795/18763702/1ceae8c8-80d4-11e6-86b9-262377ebdf2f.png)
1. Here is a SS of the console.  These errors occur on load of Postman so they may be unrelated to the issue, but included regardless with stack traces.
   ![screenshot from 2016-09-22 14 48 13](https://cloud.githubusercontent.com/assets/5728795/18763586/a9dddd9a-80d3-11e6-888b-02edad74a66b.png)

I've read somewhere that having a `Content-Type` header set can interfere with Postman building file requests, so I've double checked the there is no such header set.  

Any thoughts on this issue?

WK

**Comment by vegetableman** [comment]
@LeWestopher Thanks for reporting this 👍 .  Could you check the Network tab of the DevTools window (http://blog.getpostman.com/2015/06/13/debugging-postman-requests/) and send a screenshot?

**Comment by vegetableman** [comment]
@LeWestopher Further more, tagging this issue as something that needs investigation, as we are not able to reproduce this issue.
- Heres a screenshot of a working form-data upload. Also, you could trying uploading any file to `echo.postman.com` and check the response (as seen below under the `files` key).
  ![screen shot 2016-09-23 at 12 24 33 pm](https://cloud.githubusercontent.com/assets/1330851/18776726/db4c89b6-8188-11e6-8dd2-397238e3b4ea.png)
- Also, code generator does not support displaying file-paths due to browser restrictions.

**Comment by curtisgibby** [comment]
I'm having the same problem as @LeWestopher . Same setup: Postman 4.7.2, Chrome app, Linux Mint 17.3. My colleague on a Mac was just able to POST to the same URL that I've been trying with the same data, and his succeeds where mine fails.

**Comment by czardoz** [comment]
@curtisgibby Are you toggling the interceptor on and off between requests?

**Comment by curtisgibby** [comment]
I previously did not even have Postman Interceptor installed. Now I've installed it and turned it on, and I'm getting the same result.

**Comment by oveach** [comment]
v4.10.7 standalone version on Windows 10, same problem. Unable to upload any file.

**Comment by Otoris** [comment]
Same version, Mac OS edition. I choose a file, but it's not actually in the request. I tried choosing a file and looking at the raw request, then switch back to the key-value view and the file is gone.

**Comment by yolo2013** [comment]
Same issue. Please focus on this.

**Comment by oligriffiths** [comment]
I'm seeing exactly the same issue.

**Comment by dsithija** [comment]
This worked for me.
Go to Headers tab and remove everything (specifically Content-Type).

**Comment by LeWestopher** [comment]
@dsithija Removing the Content-Type header (or any headers for that matter) does not work, for myself at least.

**Comment by pedrolarap** [comment]
Me sucede exactamente lo mismo.

**Comment by SamvelRaja** [comment]
Are you guys facing the problem in 5.4.1 Native app?

**Comment by curtisgibby** [comment]
Looks good 👍 in the latest native app:

![screenshot from 2017-12-08 11 26 12](https://user-images.githubusercontent.com/1086964/33779535-98dcd63e-dc0a-11e7-9f9d-1c37319bb01f.png)

**Comment by nimeso** [comment]
I'm still having issues with this. if I use https://postman-echo.com/post it returns correctly but if I have a simple php file with print_r($_FILES); I get an empty array back. I'm kinda new to PHP so maybe I'm missing something simple.

**Comment by 6lick** [comment]
Having same issue on linux mint
