### ISSUE TITLE
Form-data File not refreshing content in consecutive requests after file change.

### ISSUE THREAD

**Issue by IGZfranciscoserrano** [a85/POSTMan-Chrome-Extension#2341]
1. Postman Version: 4.7.1
2. App (Chrome app or Mac app): chrome app
3. OS details:Ubuntu 16.04
4. Is the Interceptor on and enabled in the app: yes
5. Did you encounter this recently, or has this bug always been there: I think it has always been present
6. Expected behaviour: When I have a multi-part/form-data request, containing a file, file keeps selected, but the content is not being refreshed, so, if you make changes, the updated file is not being sent, it keeps sending the old version without the changes, the version with the old content you selected initially.
7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
8. Screenshots (if applicable)

**Comment by sdnts** [comment]
Hi @IGZfranciscoserrano, we do not store file paths with requests for security reasons, so I doubt this will ever be supported. You can re-upload the file for this to work.
