### ISSUE TITLE
Mac App: application/octet-stream doesn't preview

### ISSUE THREAD

**Issue by kintel** [a85/POSTMan-Chrome-Extension#2342]
1. Postman Version: 4.7.2
2. App (Chrome app or Mac app): Mac app
3. OS details: 10.10.5
4. Is the Interceptor on and enabled in the app: N/A
5. Expected behaviour: Should behave the same ways as the packaged app

Steps to reproduce the problem:
- Send the following request: `https://httpbin.org/response-headers?Content-Type=application%2Foctet-stream%3B+charset%3DUTF-8&Server=httpbin`
  -> The Mac app doesn't preview, but opens a file dialog for saving the result

Note: When doing this in the Chrome app, the application/octet-stream body is attempted previewed. Since the result is actually plain text, the preview also makes perfect sense.

Many servers provide the wrong content type in the response headers, so while you're technically correct in not previewing, it would increase usability if a preview was attempted in a similar way as the Chrome app.

Similar to #2333

**Comment by codenirvana** [comment]
This is fixed in the latest Postman app.
