### ISSUE TITLE
Unable to close Console with default keyboard shortcut

### ISSUE THREAD

**Issue by jschram** [a85/POSTMan-Chrome-Extension#2343]
**Version information**
1.  Postman Version: _4.7.2_
2.  App (Chrome app or Mac app): _Mac App_
3.  OS details: _Mac OS X 10.10.5 Yosemite_
4.  Did you encounter this recently, or has this bug always been there: _Not sure_
5.  Expected behaviour: _Should be able to close Console with Cmd + W_

**Steps to reproduce the problem**
- Open the Console with Cmd + Opt + C
- Try to close the Console with Cmd + W
- Nothing happens, have to use the mouse to close the Console

**Comment by vegetableman** [comment]
@jschram You could use `Cmd + Shift + W` to close the console window. The shortcut is not mentioned in the `Settings -> Shortcuts` dialog. We will update it. Closing this, feel free to reopen if it does not work.

**Comment by jschram** [comment]
Works as described. Thanks! 👍
