### ISSUE TITLE
Allow swapping views from Horizontal to Vertical so you can see more of the response in a scrolling window next to the request

### ISSUE THREAD

**Issue by areeves2** [a85/POSTMan-Chrome-Extension#2345]
Version/App Information:
1. Postman Version:  4.7.2 - win32 6.1.7601 / x64
2. App (Chrome app or Mac app): Windows App 
3. OS details: Windows 7 Pro
4. Is the Interceptor on and enabled in the app: No 
5. Did you encounter this recently, or has this bug always been there: Just upgraded to standlaone app from Chrome version 
6. Expected behaviour: Expected to be able to swap views would be a nice to have .

View # 1 
Request 

---

Response

View # 2 
Request | Response

**Comment by a85** [comment]
@areeves2 We are working on this. Will be out soon. :)

**Comment by a85** [comment]
Available now in 4.10+

**Comment by stiggity** [comment]
How do I switch between the two? (I happened across some key sequence and it went side by side, now I can't switch it back. This is the top hit when trying to Google how to switch back.)

**Comment by stiggity** [comment]
Okay - when you click the Settings button, the drop down menu has Settings at the top. Given the line beneath "Settings" I mistook this for a column header rather than a separately clickable entity. Click Settings there at the top of the dropdown. 

Two-pane view is used to toggle between top down and side by side.

Plus side, in sorting this out I discovered Postman has a dark theme.

**Comment by kamalaknn** [comment]
@stiggity There is also a shortcut for switching the Two Pane View - `cmd + opt + v`(if you are on macOS) or `ctrl + alt + v`.

On the latest version of the app, you can use the toggle icon on the bottom right of the app. It should look like this 

<img width="204" alt="screen shot 2017-10-06 at 11 29 36 pm" src="https://user-images.githubusercontent.com/8401064/31353082-c23e651e-ad4e-11e7-8fc7-4ba1d5e13a3a.png">

Thanks.

**Comment by singh-amandeep** [comment]
Ubuntu => ctrl + alt + v
