### ISSUE TITLE
[Feature request] Additional hotkeys 

### ISSUE THREAD

**Issue by sun-mir** [a85/POSTMan-Chrome-Extension#2346]
Would like to use these key combinations on Mac:
- `⌘ + L` get request URI (option for quick edit URL) 
- `⌘ + D` open duplicate of current request page with all data (extremely useful when creating new request for your collection or comparison of the responses for 2 similar requests)

Similar browser based commands will be very appreciated for PC and *Unix users.

**Comment by a85** [comment]
These are available now in the new native apps!
