### ISSUE TITLE
Missing requests

### ISSUE THREAD

**Issue by tofra** [a85/POSTMan-Chrome-Extension#2347]
1. Postman Version: 4.7.2
2. App (Chrome app or Mac app): Mac app
3. OS details: 10.11.6
4. Is the Interceptor on and enabled in the app: off
5. Did you encounter this recently, or has this bug always been there: discovered today
6. Expected behaviour: all requests should be shown
7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
8. Screenshots (if applicable)

Today I started postman, and wanted to run a request, when navigating to the folder, i noticed a lot of requests (14) are missing. As you can see in the screenshot, it shows I should have 51 requests. But when I open all folders and count, I only see 37. The second folder is missing the 14 requests.

I was worried that I lost the 14 request, so I did go to Settings->Data->Download. In the downloaded file, the missing requests are there.
![image](https://cloud.githubusercontent.com/assets/1746173/18808339/ad456434-825f-11e6-897c-ebd629d8cdda.png)

Any idea what it could be?

**Comment by abhijitkane** [comment]
@tofra If you have Sync enabled, can you check `https://app.getpostman.com/dashboard/collections/private?expand=1` to see if your requests show up? If yes, you can sign out and sign back in, and your data will be re-synced.

We're working on this issue, and hope to push a fix for it soon.

**Comment by tofra** [comment]
When I go to https://app.getpostman.com/dashboard/collections/private?expand=1 I see 37 requests
![image](https://cloud.githubusercontent.com/assets/1746173/18810756/5a5e0188-829e-11e6-9a1d-a3474d830a2f.png)

When I go to https://app.getpostman.com/dashboard/collections/private I see 51 requests
![image](https://cloud.githubusercontent.com/assets/1746173/18810750/39b4527a-829e-11e6-950e-5940f6929fd7.png)

Weird.. I really have no clue what's going on..

**Comment by abhijitkane** [comment]
@tofra Can you contact us at help@getpostman.com with your account username / email?
