### ISSUE TITLE
Incorrect Formatting for JSON Responses with Specific Headers

### ISSUE THREAD

**Issue by sethlopezme** [a85/POSTMan-Chrome-Extension#2348]
1. Postman Version: _4.7.2_
2. App (Chrome app or Mac app): _Mac app_
3. OS details: _Mac OS X 10.11.3_
4. Is the Interceptor on and enabled in the app: _False_
5. Did you encounter this recently, or has this bug always been there: _Discovered within the last 48 hours._
6. Expected behaviour: _All valid JSON responses with the proper content-type headers should be formatted as JSON._
7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app): _None._
8. Screenshots (if applicable): _None._

Within the last 48 hours, Postman has begun to automatically format responses with specific headers and valid JSON payloads as HTML. Previously, these responses were properly formatted as JSON. It appears that there was a very similar (if not exact) issue a couple of years ago (#563), but there wasn't a helpful resolution found in the comments as I am currently on the latest release of Postman.

**Steps to reproduce the problem:**

In my case, the issue is occurring when I receive responses with valid JSON payloads and the headers listed below. The HTTP status code doesn't appear to matter.

```
Connection →keep-alive
Date →Sun, 25 Sep 2016 06:46:55 GMT
Transfer-Encoding →chunked
cache-control →no-cache
content-encoding →gzip
content-type →application/json; charset=utf-8
vary →accept-encoding
```

These headers appear to be the default headers that are returned by [Hapi.js](http://hapijs.com/) when you reply with a normal javascript object.

An example JSON payload that this occurs with is:

``` json
{"env":"development","pid":73175,"ping":1}
```

**Comment by numaanashraf** [comment]
@sethlopezme Thanks for reporting this. We are looking into the issue and should have a fix out soon.

**Comment by vegetableman** [comment]
@sethlopezme Could you update to the latest version (4.8) of the app and verify if it's fixed?

**Comment by vegetableman** [comment]
@sethlopezme Closing this issue. Feel free to reopen this if the issue still exists ^_^
