### ISSUE TITLE
Automatically change request Content-Type header in RAW POST and PUT requests

### ISSUE THREAD

**Issue by LordotU** [a85/POSTMan-Chrome-Extension#235]
So, when I change editor mode to JSON or Text or other, request header Content-Type still is application/xml.

I can manually set correct Content-Type header, but it is not intuitive.

![Postman - Google Chrome 2013-03-01 14 50 27 ](https://f.cloud.github.com/assets/1268296/209164/e53c458e-825d-11e2-822e-ea9ffcfe48a7.png)

**Comment by giriakshay** [comment]
The resource identified by this request is only capable of generating responses with characteristics not acceptable according to the request "accept" headers

I am getting this error can you help me out please
