### ISSUE TITLE
Problem with coma separated values of GET parameters

### ISSUE THREAD

**Issue by IlianIliev** [a85/POSTMan-Chrome-Extension#2350]
1. Postman Version: 4.7.2
2. App (Chrome app or Mac app): Mac app
3. OS details: OS X 10.11.5
4. Is the Interceptor on and enabled in the app: I have no idea
5. Did you encounter this recently, or has this bug always been there: Just encountered it, works fine with the chrome app
6. Expected behaviour: 
7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
8. Screenshots (if applicable)

When passing coma separated string as value of a GET parameter to a URL they should be considered as separate parameters.

E.g. `http://example.com/?id=6,2` should lead to the server seeing two parameters e.g. `id=6` and id=2. This is working both when tried via curl and the chrome app.
However when trying the same with the Mac app the server sees this as one parameter `id="6,2"`

I can not give you a public URL as I am working on local code version but the setup is: Nginx + Gunicorn + Falcon.

**Comment by IlianIliev** [comment]
Actually looking at my webserver access logs I saw that for some reason the coma(`,`) is escaped which leads to the mentioned problem:
With Postman: `/?ids=6%2C2`
With Curl: `/?ids=6,2`

**Comment by sdnts** [comment]
@IlianIliev Thanks for letting us know, we're looking into this.

**Comment by sdnts** [comment]
@IlianIliev Can you update to the latest version (4.8) and check if your parameters are handled properly?

**Comment by Rohit-Metapercept** [comment]
> Actually looking at my webserver access logs I saw that for some reason the coma(`,`) is escaped which leads to the mentioned problem:
> With Postman: `/?ids=6%2C2`
> With Curl: `/?ids=6,2`

How did you solved this issue ? Can you suggest the way of defining it  ?
