### ISSUE TITLE
"jQuery is not defined" error when using Postman standalone app for OAuth2

### ISSUE THREAD

**Issue by alexplumb** [a85/POSTMan-Chrome-Extension#2351]
1. Postman Version: 4.7.2
2. App (Chrome app or Mac app): Mac standalone
3. OS details: OS X Yosemite 10.10.5
4. Is the Interceptor on and enabled in the app: Yes
5. Did you encounter this recently, or has this bug always been there: Only occurs since switching to standalone app
6. Expected behaviour: There shouldn't be any javascript errors when using the authorization code flow in OAuth2
7. Console log:
   ![screen shot 2016-09-26 at 11 12 38 am](https://cloud.githubusercontent.com/assets/7225271/18837437/29a19e46-83da-11e6-8b03-b9a0796cf8fb.png)

Following an email from the Postman team notifying me that Google was phasing out Chrome Apps and that Postman was offering a standalone Mac app, I happily downloaded the new one. For some reason, however, it's failing to load any javascript for my API's OAuth2 login page. The Chrome app did not have this issue. 

Triggering this is a matter of using Postman's internal OAuth2 tool. I am trying to get a new access token, and the above screenshot is what the console log shows when loading the login page for getting a new authorization code.

Let me know if there's any other information you need to help diagnose this issue. I'll be going back to the Chrome app until this is fixed. :(

**Comment by sdnts** [comment]
Hey @alexplumb, the Postman native app does not have Postman Interceptor support. Are you using the app's inbuilt proxy? This might be interfering with communication between Postman and your API.

I tried replicating this with the GitHub API, and it works fine. Could you double check to make sure your API is working properly?

**Comment by alexplumb** [comment]
Hi @madebysid 

I am not using the Proxy feature, and I can verify that this works simply by using the Chrome app instead of the standalone app.

**Comment by sdnts** [comment]
After some investigation, I've found and fixed the problem that may cause the OAuth 2.0 helper to behave like this for some APIs on the standalone app. Thanks for reporting this, we'll push out a fix for this soon :)

**Comment by SamvelRaja** [comment]
@alexplumb The fix went in our 4.8.0, can you confirm the same from your end.

**Comment by alexplumb** [comment]
That worked! Thank you so much.
