### ISSUE TITLE
Windows native app fails to install 

### ISSUE THREAD

**Issue by pmneve** [a85/POSTMan-Chrome-Extension#2352]
1. Postman Version:  4.7.2  (32 and 64 bit)
2. App (Chrome app or Mac app):  Windows native
3. OS details: Win 7 sp1
4. Is the Interceptor on and enabled in the app: no
5. Did you encounter this recently, or has this bug always been there: always
6. Expected behaviour:  Postman windows native installs.
7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):   Not applicable
8. Screenshots (if applicable)  Not applicable

Steps to reproduce the problem:
1. Run Postman-win64-4.7.2-Setup.exe
2. Click 'Run' on windows popup

**Comment by SamvelRaja** [comment]
@pmneve Thanks for bringing this to our notice. Any failure dialogue showing up while installing?

**Comment by pmneve** [comment]
@SamvelRaja:  No failure dialogue at all.  Just goes away.  :(

**Comment by SamvelRaja** [comment]
@pmneve  I doubt that it might be a permission issue. The app will try to install it in the 
`C:/Users/USERNAME/AppData/Local`

**Comment by SamvelRaja** [comment]
@pmneve Can you able to install the app?

**Comment by pmneve** [comment]
Sorry about delay responding.   No.  Just tried to install the latest version and same thing.  process appears in task manager for about 10 seconds and then disappears

**Comment by SamvelRaja** [comment]
@pmneve can try opening the installer using command line?  And let me know if that thows any errors there.. 😞

**Comment by skwirking** [comment]
Installation of 64-bit version 5.3.2 is failing for me too. I do get an error dialog, however, unlike the OP. The message is "Installation has failed: Failed to extract installer"

![image](https://user-images.githubusercontent.com/6760178/33357088-2d9b0dde-d4fb-11e7-9c7a-fc232a01234c.png)

I tried executing from the command line. The console returns immediately with no output, and a moment later the error dialog appears:

![image](https://user-images.githubusercontent.com/6760178/33357211-d8808c10-d4fb-11e7-9cf3-929041f48ae0.png)

Choosing 'run as administrator' has the same result.

A workaround that seems to function for me is to unzip the exe, then unzip the nuget package and run `lib\net45\Postman.exe`

**Comment by El-Mahbub** [comment]
I have similiar problem. And i was did what skwirking say but when i want to extract nuget package i got dialog say that file was currupted and still cant to install postman.

**Comment by gaambo** [comment]
this is still happening. @skwirking s solution works, but thats far from ideal of using postman.

**Comment by Mohammad-Tabbara** [comment]
The issue still present @skwirking solution solved it for me.

**Comment by tmsajin** [comment]
I had the same issue and got a solution for me. 
It seems mcAfee blocked something.
Please try if it work for you.
1) Right click and take properties of the exe file.
2) Click "Unblock" button , close properties box.
3) Run .exe again.

**Comment by puneethnviraat** [comment]
For windows: Right click on the .exe file select troubleshoot compatability option then follow the istrucions. 
i did the same now running fine postman.exe

**Comment by Putnam14** [comment]
This is still an issue with Postman 6.6.1, running Windows 10 64-bit. Running in compatibility mode does not fix it. @skwirking's solution does not seem to work either.

**Comment by axios94** [comment]
Check the C drive space

**Comment by CeUrquhart** [comment]
I had recently enabled  VT-X/AMD-v on my device and was getting this error I went into the bios and disabled it and tried to run the install again and it worked.

**Comment by naveed1234567** [comment]
hi i am getting this error failed to extract installed on postman

**Comment by naveed1234567** [comment]
![Screenshot_2](https://user-images.githubusercontent.com/49415120/55756493-2200f780-5a6b-11e9-8c49-aece09d782cd.png)
I am getting this error after downloading postman plz some one help me out to get rid of this error

**Comment by Carl-Bowen** [comment]
Try executing the installation file as Administrator by right-clicking the file. That resolved it for me! :).

**Comment by allenben746** [comment]
Changing the compatibility mode to Windows 7 worked for me.
