### ISSUE TITLE
"Right click > Copy" on urls in responses does not copy

### ISSUE THREAD

**Issue by jimonthebarn** [a85/POSTMan-Chrome-Extension#2353]
When I right click on a url in the pretty response view I have an option to "copy" but the url does not get copied upon clicking on it. It only works if I manually select the whole url by drag-selecting the url (which gets annoying after awhile when you frequently have to work with urls spanning multiple lines) and then issue the copy command.

I understand you are using the ACE - Editor for the text editor views but Is there something you can do to copy links without selecting the whole url upfront?

Best regards,
Ben
1. Postman Version:
   4.7.2
   win32 6.1.7601 / x64
2. OS details:
   Windows 7 Enterprise SP1

Steps to reproduce the problem:
Right click on a url in response tab and select copy

**Comment by SamvelRaja** [comment]
Thanks for bringing this to our notice. We will look into this and keep you updated 😄

**Comment by numaanashraf** [comment]
We'll take this up as part of the improvements planned in pretty rendering of JSON responses.

**Comment by davmillar** [comment]
I'm also affected by this. Ctrl+Click to open in the default browser is fine about 35% of the time, but the rest of the time I need the ability to explicitly open one-time-use links in a specific browser or Incognito tab.

**Comment by InflictedPDNK** [comment]
Affected by this too. Was about to raise a bug, but I can see it's already dated to 2016! 
Using Version 6.7.4 (6.7.4)

**Comment by a85** [comment]
As a workaround instead of copying the link, you can select the text itself and copy it.

**Comment by DaliborTakac** [comment]
> 
> 
> As a workaround instead of copying the link, you can select the text itself and copy it.

No you can't, as of 7.6.0, at least on windows 10 right clicking anything that looksl like url opens taht url in new postman tab. If you click and drag to select upon releasing mouse button same happens. I have a feeling that the prettier postman team wants to make the app the less functional its becoming.

PS. Tried also with with "raw" display, same thing :-)

**Comment by kevin-postman** [comment]
I am happy to report that this issue has been resolved in today's release of 7.17. Please update and give it a try.
