### ISSUE TITLE
Unable to hit save due to a display bug when saving a request

### ISSUE THREAD

**Issue by ctmlr** [a85/POSTMan-Chrome-Extension#2354]
1. Postman Version: 4.7.2
2. App (Chrome app or Mac app): Chrome
3. OS details: Ubuntu 14.04
4. Is the Interceptor on and enabled in the app: Yes
5. Did you encounter this recently, or has this bug always been there: Recently
6. Expected behaviour: Being able to hit the save button
7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app): N/A
8. Screenshots (if applicable)

![postman-bug](https://cloud.githubusercontent.com/assets/4529260/18888661/47554bca-84c7-11e6-9ebc-f6b00728e352.png)

When I try to save a request the modal seems to stretch all the way off the display area and I am unable to hit the save button.

My screen resolution is: 2880 x 1800 (retina display on a macbook pro).

**Comment by SamvelRaja** [comment]
Thanks for bringing this to our notice. We shall look into this and update the status here.

**Comment by sdnts** [comment]
Hey @chandwer which version of Chrome are you running Postman on?

**Comment by ctmlr** [comment]
@madebysid Chrome Version 54.0.2840.59 (64-bit)
