### ISSUE TITLE
Testing Large Numbers in Response Body

### ISSUE THREAD

**Issue by vgadolin** [a85/POSTMan-Chrome-Extension#2355]
1. Postman Version: 4.7.1
2. App (Chrome app or Mac app): Chrome Version 53.0.2785.116 m (64-bit)
3. OS details: Windows 10
4. Is the Interceptor on and enabled in the app: No
5. Did you encounter this recently, or has this bug always been there: Not sure - first time trying with large numbers in a large response.
6. Expected behaviour: Test should pass with large number as I am copying directly from response
7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app): N/A
8. Screenshots (if applicable) - see below for examples

 I am trying to use Tests to verify my response body that contains large numbers with a decimal.  When I click Send and using either Response Body: Contains string or Response body: is equal to a string, the test fails even though I have copied the number exactly from the response.  Weird part about this is that the first number which is a negative number passes the test.  I even removed the "dash" and the first test works without issue.  I even removed the quotes around the number and this did not solve the issue.

Example:  (Note:  the response is fairly large and the numbers I am looking for are somewhere in the middle of the response).  Using a test to verify text works no matter where it is located.  The issue is only with numbers.  Also it is with a new section as in below.  If I try to test for numbers at the beginning of the response, I do not have any issues.

"objectiveValues": [
    {
      "name": "expectedreturn",
      "initialValue": -4582330.770470251,
      "finalValue": 42214562.94487466,
      "delta": 46796893.71534491,
      "multiplier": 1
    },

The initialValue passes the test.  However the other tests do not pass.  Here is how I have the test that passes:

tests["Body matches string--4582330.770470251"] = responseBody.has("-4582330.770470251");

However if I try:
tests["Body matches string-42214562.94487466"] = responseBody.has("42214562.94487466"); it says FAIL and I copied it directly.

Should I be formatting things differently in order to get these tests to pass?

After doing further testing - it seems to be an issue on where the decimal is.  In other words, if I am doing a test on large number like 5.000000002132459, test passes.  However once I try the above numbers where the decimal is in the middle of the numbers, this is when the tests do not pass.  First number passes, second does not.

**Comment by SamvelRaja** [comment]
Thanks for bringing this to our notice. We will investigate this and let you know the update regarding this here.

**Comment by vgadolin** [comment]
Any update on this?

**Comment by sdnts** [comment]
@vgadolin We've identified the problem, and a fix will be out with the next release. Will keep you updated here :)

**Comment by sdnts** [comment]
@vgadolin Can you retry with the latest version (4.10.2) and verify if this is fixed?

**Comment by vgadolin** [comment]
I will test this as soon as I can.  We are in the process of finishing up our sprint.  Once that is done, I will let you know how the testing went.

**Comment by vgadolin** [comment]
Please REopen this.

This still exists.  The first line in test with large numbers running in the runner works properly, but when you get to the next line in tests where there are large number running in the runner fails.  Example. tests["Body matches string-42214562.94487466"] = responseBody.has("42214562.94487466");  - this line works fine.  However if I have a similar line like tests["Body matches string-548.1456248491579"] = responseBody.has("548.1456248491579"); it says FAIL.  The only way to get it to pass is to shorten the second line to 548.1456 or something similar.

**Comment by vgadolin** [comment]
Note:  If I run through the collection runner, this seems to work.  However when I run through newman, it does not.

**Comment by vgadolin** [comment]
I was able to test this.  This is working now.  Thanks so much for fixing.
