### ISSUE TITLE
Support system proxy exceptions in the Windows native app

### ISSUE THREAD

**Issue by ceottaki** [a85/POSTMan-Chrome-Extension#2356]
1. Postman Version: 4.7.2
2. App: Windows (native)
3. OS details: Windows 7 SP1 64-bit
4. Is the Interceptor on and enabled in the app: no
5. Did you encounter this recently, or has this bug always been there: always there
6. Expected behaviour: send requests considering the proxy set up in the system network settings including exceptions

I use Postman behind a company proxy and we make calls to both external and internal REST services. For internal servers we do not use the proxy, therefore the proxy configuration includes exceptions for these. The Postman Chrome app works just fine with these exceptions and is able to both use the proxy to connect to outside servers and not use the proxy for internal servers, but the Windows app is always using the proxy and ignores the exceptions.

Proxy exceptions are configured as such:

![image](https://cloud.githubusercontent.com/assets/1913232/18911285/25b4bf5c-8574-11e6-846e-0c29b88ccaa6.png)

Postman returns a 502 Bad Gateway status with our proxy's error message saying that the host has not been found, clearly showing that it tried to connect to it through the proxy despite the exception being there.

**Comment by SamvelRaja** [comment]
Thanks for bringing this to our notice, I will investigate further on this and get back to you in the same thread.

**Comment by ceottaki** [comment]
No problem, thanks for assigning it so quickly. Let me know if you need more information that I can provide.

**Comment by SamvelRaja** [comment]
@ceottaki  I checked the same it is working as expected in the 4.7.2 app version.
Adding the screenshot for the same. Let me know if i missed anything while testing it.
Also, we are working on a advance version of the proxy settings inside the app which would eventually solve this case also.

![screenshot 6](https://cloud.githubusercontent.com/assets/5114052/18953172/b34aadee-866a-11e6-805f-4f8b19ba66da.png)
![screenshot 7](https://cloud.githubusercontent.com/assets/5114052/18953175/b7af6a00-866a-11e6-97bc-fb7b1a39e029.png)

**Comment by ceottaki** [comment]
Hi, @SamvelRaja 

Thanks for the investigation, that is really weird. I've pretty much tested it the same way and this is what I have:

![image](https://cloud.githubusercontent.com/assets/1913232/18960391/7749e6c4-8661-11e6-9f1e-30f35ce46bb4.png)

No issues when doing the exact same from the Chrome app.

If there will be more advanced proxy settings in the native app soon, then this wouldn't be an issue, so I suppose I can wait for that.

Thanks again.

**Comment by abhijitkane** [comment]
@ceottaki The current version of the Windows app supports specifying system/global proxy configurations. Feel free to re-open if you're still seeing this.
