### ISSUE TITLE
Cannot switch between users in successive API calls (Basic Auth)

### ISSUE THREAD

**Issue by PeterDo3** [a85/POSTMan-Chrome-Extension#2357]
I am trying to check that I can read/write to site using different users.  Both users have different USERNAMES and PASSWORDS.   Previously this worked, but now I am getting an error response:
    \* HTTP Status 403 - Access to the requested resource has been denied *

What I have found, is that if I manually switch the state of Interceptor between calls, the test passes.  Without this intervention, one of the API calls fails with responseCode.code '403'.

I have checked the passwords and usernames of the site, both are correct.

Not sure what is causing it.

Version/App Information:
1. Postman Version:  4.7.2
2. App (Chrome app or Mac app):   Chrome 53.0.2785.116
3. OS details:    Windows 10 Version 1607 (OS Build 14393.187)
4. Is the Interceptor on and enabled in the app: (Yes and No)
5. Did you encounter this recently, or has this bug always been there: Recently
6. Expected behaviour: All tests should pass
7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
   They do not show anything.

Sequence 1 - Interceptor OFF
User1: Get data.   Result:  responseCode.code '403'
User2: Post data.  Result:  responseCode.code '200'

Sequence 2 - Interceptor ON
User1: Get data.   Result:  responseCode.code '200'
User2: Post data.   Result:  responseCode.code '403'

Sequence 3 - Interceptor ON/OFF (Manual Intervention)
User1: Get data.   Result:  responseCode.code '200'  (Interceptor ON) 
User2: Post data.   Result:  responseCode.code '200'  (Interceptor OFF)

**Comment by sdnts** [comment]
@PeterDo3 Can you provide more details about the type of server you're running, and if it needs browser cookies in any way to authenticate? (Which might be why using the Interceptor affects your result)

Requests in Postman are completely separate from each other, so if you're using different `Authorization` headers in both requests, they should work.

Do you have a sample collection I can replicate this with?

**Comment by sdnts** [comment]
@PeterDo3 Is this still reproducible?
