### ISSUE TITLE
Double scrolling UI is bad

### ISSUE THREAD

**Issue by rich-blockley-bg** [a85/POSTMan-Chrome-Extension#2358]
1. Postman Version: Version 4.2.2 (4.2.2)
2. App (Chrome app or Mac app): Chrome app
3. OS details: OS X 10.11.6 (15G1004)
4. Is the Interceptor on and enabled in the app: I dont think so
5. Did you encounter this recently, or has this bug always been there: always
6. Expected behaviour: Don't have the bottom of the screen scroll as well as a container inside
7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app): None
8. Screenshots (if applicable)

So in Postman one has app screen split into left (buttons to run stuff) and right side (the input and output).
In the input and output area it is split vertically: top (get, authorization, headers etc) and the bottom (json output, for example).
The bottom pane goes off the bottom of the screen, and I have to scroll the whole right side down to reveal it. THEN I have to scroll within the output text box. I don't think it is good UI to have one scrolling thing (the output box) inside of another scrolling pane (the whole right-hand side).

In my attached screenshot I've drawn two red arrows. The upper one shows that the whole right screen pane is not at the bottom - which means that I have to scroll something to view all the content. Then the other arrow shows my output content which is scrollable.

Personally I think the output should be 'docked' - that is, it just lives at the bottom and occupies whatever space it can. Then you scroll that pane only.

![image](https://cloud.githubusercontent.com/assets/19687509/18915698/ccd6a47a-8589-11e6-87ac-d05dd56b20d2.png)

**Comment by vkaegis** [comment]
Hey @rich-blockley-bg! Thanks for reporting this. We're actually working on an improved Builder interface which behaves EXACTLY as you mentioned :) You can hope to see it in one of our coming releases.

**Comment by bkubiak** [comment]
Hi @vkaegis, I'm looking forward to the updated interface, because scrolling content on Postman for Mac is really painful. Any update on the issue?

In addition to @rich-blockley-bg solution, I would suggest that the upper pane (auth/headers/body etc.) could hide after clicking on a new button (show/hide) or even when clicking on the same tab button (when clicking on "Body", the body content is revealed and next click on "Body" would hide the upper panel).

**Comment by mr-mmmmore** [comment]
+1
This is so annoying! Will it be fixed soon?

**Comment by a85** [comment]
Yes. A 3-pane vertical layout is coming in 4.9.

**Comment by a85** [comment]
Yes. A 3-pane vertical layout is coming in 4.9.

**Comment by vkaegis** [comment]
Hey @rich-blockley-bg, the 4.9 release supports a two-pane view which should fix any double-scrolling problems you have. Hoping this solves your issue!

**Comment by numaanashraf** [comment]
The new two-pane view is available in versions 4.9.0 and up. This can be enabled them via Settings > General > Two-pane view or via the keyboard shortcut (Cmd/Ctrl + Alt + V). Closing this issue.

**Comment by PhilTheAir** [comment]
It is terrible!! Is there any setting that could make the UI fixed?
