### ISSUE TITLE
Windows packaged app  4.7.2 still sending GET instead of POST.

### ISSUE THREAD

**Issue by ftrujillojr** [a85/POSTMan-Chrome-Extension#2359]
1. Postman Version:  4.7.2
2. App (Chrome app or Mac app):  Windows
3. OS details:  Windows 7
4. Is the Interceptor on and enabled in the app:  can't find Interceptor in settings.
5. Did you encounter this recently, or has this bug always been there:  Worked in Chrome app, stand alone app is failing.
6. Expected behaviour:   If I send a POST, it should send a POST.  With or without trailing slash.
7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
8. Screenshots (if applicable)

Steps to reproduce the problem:   Try any POST.  One without trailing slash.  One with.
The one with will send a POST.   The one without will send a GET.   Nice tool on Chrome.
Chrome did not want to support the apps, so I moved your Windows packaged app.   Really buggy.

![crop](https://cloud.githubusercontent.com/assets/355338/18927189/2431c52c-8578-11e6-9eeb-7e0c2efbaf4d.png)

**Comment by abhijitkane** [comment]
@ftrujillojr This is due to a server-side redirect. https://postman.zendesk.com/hc/en-us/articles/211913929-I-sent-a-POST-request-but-Postman-seems-to-be-sending-a-GET-request-

**Comment by ftrujillojr** [comment]
Same behavior.  Still broken.

**Comment by abhijitkane** [comment]
@ftrujillojr Can you provide a publicly accessible URL that you see this issue with?

**Comment by ftrujillojr** [comment]
I'm going to say go ahead and close this ticket.  I just need to get into
the 21st century.

I learned a lot from the below post.
For those who are still confused, read the 1st paragraph here =>
Redirects done by the Web server itself
http://sebastians-pamphlets.com/the-anatomy-of-http-redirects-301-302-307/

Without trailing slash, the Location is transmitted back.  The browser
redirects this as a GET, which in my case is a a RESTful index().   Now, I
understand.

nsglnxdev1:/home/ftrujillo/NetBeansProjects/StrutsWebApp [695]$ curl -ss -i
-H "Accept: application/json" -H "Content-Type: application/json" --data
'{"emailData":{"email":"ftrujillojr@gmail.com","firstName":"Francis","lastName":"Trujillo"}}'
--request "POST" http://nsglnxdev1.micron.com:8085/StrutsWebApp/emailData
HTTP/1.1 302 Found
Date: Thu, 29 Sep 2016 15:58:28 GMT
Server: Apache-Coyote/1.1
Location: http://nsglnxdev1.micron.com:8085/StrutsWebApp/emailData/
Proxy-Connection: Keep-Alive
Transfer-Encoding: chunked

With the trailing slash, I get back the "201 Created" that I was looking
for.

nsglnxdev1:/home/ftrujillo/NetBeansProjects/StrutsWebApp [700]$ curl -ss -i
-H "Accept: application/json" -H "Content-Type: application/json" --data
'{"emailData":{"email":"ftrujillojr@gmail.cm","firstName":"Francis","lastName":"Trujillo"}}'
--request POST http://nsglnxdev1.micron.com:8085/StrutsWebApp/emailData/
HTTP/1.1 201 Created
Date: Thu, 29 Sep 2016 16:02:21 GMT
Pragma: no-cache
Server: Apache-Coyote/1.1
Expires: -1
Content-Type: application/json;charset=UTF-8
Cache-control: no-cache, no-store, must-revalidate
Content-Length: 151
Proxy-Connection: Keep-Alive
Content-Style-Type: text/css
Access-Control-Allow-Origin: *
Access-Control-Allow-Headers:
Content-Type,Access-Control-Allow-Headers,Authorization,X-Requested-With,Cache-Control,Origin,Accept,X-Jersey-Tracing-Accept,X-HTTP-Method-Override
Access-Control-Allow-Methods: GET,POST,DELETE,PUT,OPTIONS,HEAD

{"data":{"email":"ftrujillojr@gmail.com
","firstName":"Francis","lastName":"Trujillo"},"method":"POST","status":201,"uri":"\/StrutsWebApp\/emailData\/"}

**Comment by a85** [comment]
Glad it's resolved @ftrujillojr
