### ISSUE TITLE
OAuth2 supporting a nonce for the auth URL

### ISSUE THREAD

**Issue by urkle** [a85/POSTMan-Chrome-Extension#2360]
1. Postman Version: 4.7.1
2. App (Chrome app or Mac app): both
3. OS details: N/A

I have an OpenID Connect SSO system setup (which OpenID connect is layered ontop of OAuth 2.0 ).  And part of that spec is that the auth URL endpoint has a nonce passed to it.   Currently Postman does not send a nonce, only a code.  Thus all attempt to get an OAuth2 toke via postman fail due to this limitation..

Extending the OAuth2 dialog to support an option "send nonce to auth URL" would nicely fulfill this requirement.    (Documentation http://openid.net/specs/openid-connect-core-1_0.html#codeExample )

**Comment by nufrifin** [comment]
A year later I tried to get a token from Okta using implicit flow and got this back in a well hidden chrome dev tools console:
`"The+'nonce'+parameter+is+required+for+authorize+requests+with+either+the+'id_token'+or+'token'+response+types.."`

**Comment by CCob** [comment]
More and more IdP's are implementing OIDC spec on top of OAuth now and I have hit the same problem.  I worked around it by adding nonce query argument to the auth URL which worked, but a tick box for this would be ideal

**Comment by rtrompier** [comment]
I agree with @CCob. For exemple, NONCE params is now mandatory with latest version of Keycloak ;)

**Comment by spahrson** [comment]
As a workaround (at least using Keycloak) it is possible to attach the `nonce`-param for the auth-url as query-param e.g. `...?nonce=asd`

**Comment by abhijeetborole** [comment]
Hey everyone! Thank you for the patience! We’ve added the ability to customise your OAuth2,0 requests with Postman v10.13.
This is available under the `Advanced` section under OAuth2.0. With these changes, you can now add params to the headers, body and URL for token and refresh requests. You can also add query params to the auth request.

You can add the `nonce` here in the `Advanced` Section to the Auth Request.

![CustomOauthLow](https://user-images.githubusercontent.com/9638586/232849656-63e0297a-7bc3-4472-8ff3-04cf2f5df95e.gif)

If you have any Audience and Resource parameters, you can move them to the new editors with the Move Audience and Resource button.

![MoveAudAndResFlow](https://user-images.githubusercontent.com/9638586/232850201-59d30590-d7c7-41c1-94c7-9a1c77f1757b.gif)


Do let us know if you have any issues.

P.S. - For refresh parameters, these will be stored with the token and any changes will only be considered when you generate a new token

Postman app v10.13 is being rolled out will be available for everyone in couple of days
