### ISSUE TITLE
Native Windows Client does not display Multipart Response

### ISSUE THREAD

**Issue by jjathman** [a85/POSTMan-Chrome-Extension#2362]
1. Postman Version: v4.7.2
2. App (Chrome app or Mac app): Native Windows App
3. OS details: Windows 7
4. Is the Interceptor on and enabled in the app: no
5. Did you encounter this recently, or has this bug always been there: after the switch to the native app
6. Expected behaviour: I'm interacting with a SOAP service which responds with a multipart message using MTOM (Content-Type →multipart/related; type="application/xop+xml"; boundary="uuid:179fc224-285a-4430-b14c-42a74b78f674"; start="root.message@cxf.apache.org"; start-info="application/soap+xml"). Previously with the Chrome version of postman I would still see the response and it would have XML highlighting. Now the Body tab is just simply blank and I can't see any way to view the response at all. I see get the correct status, time, and size values so I believe it is getting the response and processing it OK. I also see the response body in the Postman Console (not in the devtools console)
7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app): The last message displayed is: Resource interpreted as Document but transferred with MIME type multipart/related: "data:multipart/related;base64
8. Screenshots (if applicable)

**Comment by SamvelRaja** [comment]
Thanks for bringing this to our notice. We will update you the status once it is been fixed.

**Comment by sdnts** [comment]
Hey @jjathman, can you still reproduce this in the latest version (4.8)?

**Comment by jjathman** [comment]
Yep, looks like it works correctly for me now. Thank you!
