### ISSUE TITLE
POSTMAN concurrent requests

### ISSUE THREAD

**Issue by chandramohan-lakshminarayanan** [a85/POSTMan-Chrome-Extension#2364]
Hello, 

Given that now POSTMAN is also available as a standalone (not relying on Chrome anymore) , can we get to know when will the POSTMAN get the Async HTTP client feature to run concurrent requests? 

Thanks, 
Chandra

**Comment by sdnts** [comment]
@chandramohanpl We've done a redesign of the runner that takes advantage of the all new Postman Runtime and allows you to send concurrent requests. You can download the canary release for OSX [here](https://dl.pstmn.io/download/channel/canary/osx_64). 
I'd recommend you to join our Slack community [here](https://www.getpostman.com/slack-invite) so you can provide feedback before the runner moves to our stable builds :)

**Comment by charltog** [comment]
Do you have anything available for Windows?  I would be willing to test a dev build if you have one.

**Comment by sdnts** [comment]
@charltog Yes of course, you can download a Windows Canary build from: [x86](https://dl.pstmn.io/download/channel/canary/windows_32) or [x64](https://dl.pstmn.io/download/channel/canary/windows_64)

**Comment by sdnts** [comment]
@chandramohanpl @charltog The new Runner is out with our latest release (4.9) on our native apps. Concurrent runs are now possible :)
