### ISSUE TITLE
Import json v2 cause second query parameter value to be url encoded

### ISSUE THREAD

**Issue by nevostruev** [a85/POSTMan-Chrome-Extension#2365]
1. Postman Version:  4.7.2
2. App (Chrome app or Mac app): Mac App
3. OS details: OS X 10.11.6 (15G1004)
4. Is the Interceptor on and enabled in the app: No
5. Did you encounter this recently, or has this bug always been there: Not sure
6. Expected behaviour: correct import of second and next query parameters
7. Console logs: Postman Logs are empty
8. Screenshots (if applicable)

Steps:
- Create request with at least one request parameter and 2 or more query parameters
- Set query parameters values to variables `{{variableName}}`
- Export request into json v2 file
- Import json file back to postman
- Value of second parameter is url encoded

Sample json file:

``` json
{
  "variables": [],
  "info": {
    "name": "test",
    "_postman_id": "bb55e8a2-6233-618c-9b8c-184d9598f036",
    "description": "",
    "schema": "https://schema.getpostman.com/json/collection/v2.0.0/collection.json"
  },
  "item": [
    {
      "name": "Broken params",
      "request": {
        "url": {
          "raw": "http://any-host/path/:pathParam?param1Good={{param1Good}}&param2Bad={{param2Bad}}",
          "protocol": "http",
          "auth": {},
          "host": [
            "any-host"
          ],
          "path": [
            "path",
            ":pathParam"
          ],
          "query": [
            {
              "key": "param1Good",
              "value": "{{param1Good}}"
            },
            {
              "key": "param2Bad",
              "value": "{{param2Bad}}"
            }
          ],
          "variable": [
            {
              "value": "{{pathParam}}",
              "id": "pathParam"
            }
          ]
        },
        "method": "GET",
        "header": [],
        "body": {
          "mode": "raw",
          "raw": ""
        },
        "description": ""
      },
      "response": []
    }
  ]
}
```

Query params before export:

```
param1Good:{{param1Good}}
param2Bad:{{param2Bad}}
```

Query params after import:

```
param1Good:{{param1Good}}
param2Bad:%7B%7Bparam2Bad%7D%7D
```

**Comment by SamvelRaja** [comment]
Thanks for bringing this to our notice. We will update the progress regarding this here.

**Comment by vegetableman** [comment]
@nevostruev The issue has been fixed on our internal build. Will be part of the upcoming release.

**Comment by vegetableman** [comment]
@nevostruev Can you try updating to our latest version (4.8) and check if this is fixed?

**Comment by nevostruev** [comment]
Works in 4.8. Thanks for fixing.
