### ISSUE TITLE
Oauth 1.0 Helper not working on 4.7.2

### ISSUE THREAD

**Issue by gladstongarcia** [a85/POSTMan-Chrome-Extension#2367]
1. Postman Version: 4.7.2
2. App (Chrome app or Mac app): Chrome app
3. OS details: Windows 7 SP1
4. Is the Interceptor on and enabled in the app: Yes
5. Did you encounter this recently, or has this bug always been there: The second I was forced to update to 4.7.2
6. Expected behaviour: Request REST API with Oauth 1.0 and Querystring auth parameters.

1. Enter REST API address.
2. Enable Oauth 1.0 authentication Helper.
3. Uncheck all checkboxes, leave Save helper data to request marked.
4. Fill keys and token with data.
5. Click Update Request. 

It will add the parameters to the begining of the already existing URL as the first parameters. Behavior on 4.7.1 was to append the extra parameters.

If you click send, or update request again, it will add oauth parameters to querystring again, and again.

**Comment by vegetableman** [comment]
@gladstongarcia Thanks for reporting 👍 . The issue has been fixed in our internal build. Will be part of the upcoming release.

**Comment by SamvelRaja** [comment]
@gladstongarcia This has been fixed in our 4.9.0 version. Kindly check the same from your end 😄

**Comment by gladstongarcia** [comment]
Worked flawlessly. 

Guys, thanks for the support and dedication. Your tool is really great.
