### ISSUE TITLE
Cookies are not visible but sent with the request.

### ISSUE THREAD

**Issue by coding-idiot** [a85/POSTMan-Chrome-Extension#2368]
1. Postman Version: Latest chrome extension
2. App (Chrome app or Mac app): Chrome App
3. OS details: Windows 7
4. Is the Interceptor on and enabled in the app: Yes
5. Did you encounter this recently, or has this bug always been there: Always
6. Expected behaviour: As a user, I should be able to see every minute details of the request being sent and edit them. Otherwise it results in unexpected behavior.
1. Just sign in into any application
2. Send another request which requires session cookie
3. Notice the request doesn't send 403 because the cookie is sent in the subsequent request but it's not visible in the UI

**Comment by sdnts** [comment]
@coding-idiot When you say the cookie isn't visible, what do you mean?
The interceptor with the Chrome App will send your request through Chrome, so it sends any cookies you have stored in Chrome, that is what it was meant for :D
