### ISSUE TITLE
Reason phrase is not displayed (again)

### ISSUE THREAD

**Issue by ugumba** [a85/POSTMan-Chrome-Extension#2370]
I'm using Postman Windows app 4.7.2.
Postman consistently displays only the default reason phrase, never my custom phrases.
I've verified with Insomnia, which shows the reason phrase correctly.

Maybe a regression of #1918 ?

**Comment by sdnts** [comment]
@ugumba Postman has a registry of HTTP reason phrases that are the convention.
What is your use case to use custom reason phrases?

**Comment by ugumba** [comment]
Why would I need to provide a use case?  The HTTP standard supports the provisioning of a custom reason phrase, which normally overrides (or augments) the conventional phrase.  I can use it to further explain to the user or API consumer why a request did not return "200 OK" (e.g.), without resorting to the body (which may not even be sent in case of HEAD) or a response header.  It would actually be really useful from Postman itself.

Postman has correctly displayed the reason phrase before, and similar defects **have even been fixed before** (see #1918 and #1841).  Other REST/HTTP client tools do support it (e.g. Insomnia, as mentioned above).

**Comment by sdnts** [comment]
Ah okay I'll investigate and get back to you here.

**Comment by sdnts** [comment]
@ugumba Hey the latest version of the app (4.8) addresses this, and the custom reason phrase should now show up. Can you update and verify?
