### ISSUE TITLE
Chrome App Bugs when working with Oauth2.0 Tokens

### ISSUE THREAD

**Issue by davingreen** [a85/POSTMan-Chrome-Extension#2371]
1. Postman 4.7.2 for Chrome
2. Chrome app
3. Windows 10 updates installed (Sept 28, 2016)
4. No interceptor
5. Had issues before...
6. Expect to be able to manage Oauth2.0 Tokens (see details, delete)
7. Console log attached
8. Video: https://www.dropbox.com/s/na9fcoj9baru84p/2016-09-29_18-55-53.MP4?dl=0. Screenshot of broken interface: https://db.tt/3H3PlpgB

I am trying to setup some Oauth2.0 tokens to use with Podio API. I have been able to do this with a SLIM API successfully. However, after trying to create a second token, I started to get a lot of unexpected behavior from the Chrome app. It now does not show the details for tokens and clicking them breaks much of the interface. I have logged out, uninstalled the app, reinstalled, etc. I am unable to manage or modify the tokens as new Tokens do not load the Auth URL anymore.
[fhbjgbiflinjbdggehcddcbncdddomop-1475190237495.txt](https://github.com/postmanlabs/postman-app-support/files/501871/fhbjgbiflinjbdggehcddcbncdddomop-1475190237495.txt)

**Comment by sdnts** [comment]
@davingreen The video you uploaded seems to get stuck at a point, so I couldn't see what was going wrong. From your description, it looks like the second token did not appear in the sidebar and then the interface broke. Am I right?

**Comment by davingreen** [comment]
Correct. Here's another video that will hopefully show it better: https://db.tt/lTQMi7fd. It get's stuck when clicking the token. Then everything goes haywire.

**Comment by sdnts** [comment]
@davingreen The video is stuck again :P But I was able to reproduce the error with the Podio API. We'll work on a fix and have it out at the earliest

**Comment by sdnts** [comment]
@davingreen Can you try updating to the latest version (4.8) and verify if this is fixed?

**Comment by davingreen** [comment]
Appears to be working. Thanks!
