### ISSUE TITLE
re-Importing collection 

### ISSUE THREAD

**Issue by vip9** [a85/POSTMan-Chrome-Extension#2373]
1. Postman Version: 4.7.2
2. App (Chrome app or Mac app): Chrome app
3. OS details: Linux

When developing new API, you'll probably modify your api a lot (adding new routes, etc).
It would be great Postman remember import URL for collection and have ability to redownload and import (replace) old collection with one button.

**Comment by sdnts** [comment]
If you try to import a collection that already exists in the app, you should get a pop-up asking you if you want to replace the collection. Do you not get this?

Also, you can edit your collection in the app directly, by adding requests to it. You shouldn't need to import it repeatedly.

**Comment by vip9** [comment]
My app automatically exports all endpoints to json, so it would be easier just to click "refresh collection". 
Importing again or editing collection is few more steps to make (duplicating work)

**Comment by a85** [comment]
POST/PUT routes in the new Postman Cloud API (https://api.getpostman.com) will support workflows like these. It will allow POSTing to an existing collection and syncing it with everyone's Postman copy. Closing this for now.
