### ISSUE TITLE
Incorrectly parsing an URL in a response body

### ISSUE THREAD

**Issue by maurociancio** [a85/POSTMan-Chrome-Extension#2374]
1. Postman Version: 4.7.2
2. App (Chrome app or Mac app): Chrome app
3. OS details: Ubuntu 14.04 linux / x86-64
4. Is the Interceptor on and enabled in the app: nop
5. Did you encounter this recently, or has this bug always been there: I've started using the app a few days ago
6. Expected behaviour: Postman incorrectly parse an URL that has escape characters like "\"
7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
8. Screenshots (if applicable)

When you click this URL in a response body
![image](https://cloud.githubusercontent.com/assets/155789/18996291/1a0140de-8706-11e6-9925-b966ca26efe9.png)

Postman parse it wrong and include the trailing slash () in the next request:
https://stripped.url.com/..../.../.JKuMdH8xnQra9Z2V5JyatgUGwc**\**

It should not include the trailing slash because is an escape character.

**Comment by sdnts** [comment]
Is this still an issue? Please let me know if it is, and I'll reopen.
