### ISSUE TITLE
content-lenght header field is not updated when request body is updated

### ISSUE THREAD

**Issue by blikblum** [a85/POSTMan-Chrome-Extension#2375]
1. Postman Version:  4.7.2
2. App (Chrome app or Mac app): Windows app
3. OS details: Windows 10
4. Is the Interceptor on and enabled in the app: Yes
5. Did you encounter this recently, or has this bug always been there: always
6. Expected behavior:

The content-length header field should be updated when body content is changed and request is saved or sent

Steps to reproduce the problem:

Saved a POST request to a collection using the interceptor / proxy. It saves the request url, body and also header fields. Among header fields there's content-length that is set to a fixed value.

If i change the request body with a different size than previous one and save or send the request, the content-length field is not updated, leading to a mismatch between the declared content length and the actual one. This can cause problems like 408 HTTP error when content-length is bigger than actual content length.

**Comment by a85** [comment]
You should remove the Content-Length header. Postman will automatically attach one.

**Comment by blikblum** [comment]
This is what i've done to get working and now i will look at it when changing body requests. But other users can fall in same trap making its life harder and with potential to generate new support requests.

The user has to figure by itself why the request stopped work (server started to return 408). I wasted more than two hours trying to figure why i can change request body of my other requests (created manually) and not with the created with the interceptor. 

I see some options to improve usability (not mutually exclusive)
1) The interceptor by default stores content-length. Do not do it since as you pointed postman will add it on the fly
2) Show a warning when modifying body content when content-length is stored

**Comment by blikblum** [comment]
3) Document the warning
