### ISSUE TITLE
Auto encoding of URL params while running collection through newman on Linux

### ISSUE THREAD

**Issue by seekdageek** [a85/POSTMan-Chrome-Extension#2376]
1. Postman Version: 4.7.2
2. App (Chrome app or Mac app): Chrome app
3. OS details: Linux 2.6.32-642.4.2.el6.x86_64
4. Is the Interceptor on and enabled in the app: No
5. Did you encounter this recently, or has this bug always been there: I am new user of newman and facing this first time. I am not aware whether this is existing issue.
6. Expected behaviour: I am passing a URL parameter as {date} instead of {{date}} in a collection. Expected behavior is that the URL param {date} should be passed as it is. However when I am running the collection through newman, which is installed on Linux machine, the characters { and } are getting encoded.
7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app): Issue is in newman. Hence not able to collect the console logs.
8. Screenshots (if applicable)

**Comment by numaanashraf** [comment]
@seekdageek This seems like a bug. We are tracking this at https://github.com/postmanlabs/newman/issues/664.
