### ISSUE TITLE
Add Support for third party login

### ISSUE THREAD

**Issue by buddyackerman** [a85/POSTMan-Chrome-Extension#2377]
There is an issue that was posted recently about not supporting Authentication on Windows IIS servers that are configured for NT Auth.  Postman also needs to be able t handle third party auth as well.  NOw that the legacy extension is deprecated I have no way to authenticate to my Web Api.  The Web Api is a .NET based web api that has the controllers set to authenticate with and ADFS authentication redirect.  So, when accessing my app it redirects to the ADFS login page then once logged in it redirects to my app.  The extension was great because the auth cookie was shared amongst tabs in the browser session.  This is no longer the case with the Postman app.  In effect I can no longer use Postman.

**Comment by a85** [comment]
Closing this as we are tracking Interceptor support in #1667. Any missing form of authentication can be baked into Pre-request scripts or through a combination of manual steps + script based flows.
