### ISSUE TITLE
JSON Formatting of the request body

### ISSUE THREAD

**Issue by usubhash** [a85/POSTMan-Chrome-Extension#2378]
1. Postman Version: 4.7.2
2. App (Chrome app or Mac app): Mac
3. OS details: 10.11.6
4. Is the Interceptor on and enabled in the app:
5. Did you encounter this recently, or has this bug always been there:
6. Expected behaviour:
7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
8. Screenshots (if applicable)

It will be great if postman has an option with which the pasted body in the request can be JSON formatted. This is helpful to organize the request copied from different places and edit if needed.

**Comment by SamvelRaja** [comment]
@usubhash You can prettify the JSON copied into the request body very easily,  paste the JSON request body(raw),  select JSON(application/json) and press **Cmd/Ctrl + B** It would be prettified automatically.
![prettify request body](https://cloud.githubusercontent.com/assets/5114052/19104739/d71c4f8a-8afb-11e6-9109-98cb9975b898.gif)

**Comment by usubhash** [comment]
@SamvelRaja Thats awesome. Thanks for letting me know. Please let me know if this is documented.

**Comment by govindrai** [comment]
Feature request: Can you please add this feature as a shortcut in the edit menu? I wasn't able to find this anywhere. Also is this documented somewhere?

**Comment by Alonski** [comment]
I am commenting here even though a long time has passed.
This isn't documented in the Shortcuts section in Postman.

**Comment by vkaegis** [comment]
@Alonski Thanks for the reminder! We'll go one step ahead and actually add a button in the UI for this (along with documenting the shortcut of course).

**Comment by guntram** [comment]
@SamvelRaja using ctrl+B does not do anything in my postman raw json body.
But as a workaround, I can click on "code" on the right side, and there my json data will be shown prettified. I can copy it from there and paste it into the body...

**Comment by gysi** [comment]
The hidden ctrl+B Feature stopped working for me.

**Comment by hiimdoublej** [comment]
@gysi Me too

**Comment by sudoliyang** [comment]
@gysi, I have the same issue.
My environment is Postman Version 6.3.0 (6.3.0)

**Comment by numaanashraf** [comment]
@gysi @hiimdoublej @sudoliyang This is a confirmed regression in `v6.3.0`. We are working on rolling out a fix for this in the next release.

**Comment by sudoliyang** [comment]
@numaanashraf 
sounds great 👍, thank you.

**Comment by kid1412621** [comment]
> @usubhash You can prettify the JSON copied into the request body very easily, paste the JSON request body(raw), select JSON(application/json) and press **Cmd/Ctrl + B** It would be prettified automatically.
> ![prettify request body](https://cloud.githubusercontent.com/assets/5114052/19104739/d71c4f8a-8afb-11e6-9109-98cb9975b898.gif)

not work in example?

**Comment by Alonski** [comment]
@vkaegis Just another friendly reminder about this :)

**Comment by fernandops26** [comment]
> @usubhash You can prettify the JSON copied into the request body very easily, paste the JSON request body(raw), select JSON(application/json) and press **Cmd/Ctrl + B** It would be prettified automatically.
> ![prettify request body](https://cloud.githubusercontent.com/assets/5114052/19104739/d71c4f8a-8afb-11e6-9109-98cb9975b898.gif)

Good response, just a consideration, ctrl + b worked after saving the changes of my request.

**Comment by vkaegis** [comment]
@Alonski We've added Beautify as an explicit action in places like the request body (if you choose JSON) but have a better solution for exposing this as a consistent set of actions on the code editor / viewer. That is gonna take a bit longer. Thanks for the reminder though. 👍

**Comment by Alonski** [comment]
Hey @numaanashraf Was this fixed?

**Comment by numaanashraf** [comment]
@Alonski Yes. You can format via the shortcut (Cmd/Ctrl+B) or use the beautify button. 

<img width="760" alt="screenshot 2019-02-03 at 12 24 45 pm" src="https://user-images.githubusercontent.com/3295568/52173672-c4240b00-27ae-11e9-8c00-ab5107592c37.png">

**Comment by Alonski** [comment]
@numaanashraf Amazing! Thanks!

**Comment by Alonski** [comment]
@numaanashraf I think one last piece that could also help improve this is to add to the shortcuts screen a new `Editor` section that teachs the Ctrl+B shortcut.

Another option that could complement or be instead is adding a tooltip over the Beautify button.

**Comment by numaanashraf** [comment]
Thanks for the feedback @Alonski. We'll include these in an upcoming update.
