### ISSUE TITLE
Cookie expiry does not respect timezone in Mac app

### ISSUE THREAD

**Issue by akdor1154** [a85/POSTMan-Chrome-Extension#2379]
Using the Postman Mac App, cookie expiries are interpreted as if my computer was running with the current local time, but in GMT.

e.g. if I set a cookie that expires in fifteen hours, and my computer running both Postman and my Node server is running at 11:20 am in Melbourne, with OS X's timezone set to AEDT = UTC+1100.

```
POST http://localhost:8000/auth/appKey
... 
[Headers as viewed in Postman]
Set-Cookie →appAuth=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE0NzU1NDA0NDMsImV4cCI6MTQ3NTU5NDQ0M30.x-UWgWMozSFr1V1WpMQXSJLCCE7GMdVvqFvLgouS3Bs; Path=/; Expires=Tue, 04 Oct 2016 15:20:43 GMT; HttpOnly
```

Note that the above expiry is correct - the current time is 11:20 + 1100 hours, ~= 00:20 GMT, so the cookie expiry is 15 hours in the future at 15:20 GMT, as expected.

However, if I look in the Cookies that get sent with future requests and inspect this cookie, I see

```
appAuth=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE0NzU1NDA0NDMsImV4cCI6MTQ3NTU5NDQ0M30.x-UWgWMozSFr1V1WpMQXSJLCCE7GMdVvqFvLgouS3Bs; path=/; domain=localhost; HttpOnly; Expires=Tue Oct 04 2016 15:20:43 GMT+1100 (AEDT)
```

Note that the cookie has been set with the GMT time but local timezone.

If I run the Postman Chrome app (in Vivaldi, not that it should make a difference), and inspect Cookies with Vivaldi, the cookie gets set with the correct expiry:

```
Expires: 2016/10/5 02:20
```

(Vivaldi does not display a timezone, so local is implicit, and the time matches the local time that the cookie is meant to expire)

**Comment by sdnts** [comment]
@akdor1154 Thanks for reporting this. We're looking into this.

**Comment by vegetableman** [comment]
@akdor1154 Could you share the screenshot of the request and response headers on the postman console (`View -> Show Postman Console`) for the requests you are making?.

**Comment by siwatpru** [comment]
I also have this problem. I can't clear the cookie in the mac app version. (It works in the chrome app version)

Login API response header

```
Set-Cookie →AuthSession=YWRtaW5AYWRtaW4uY29tOjU3RkRGQTY1OsDcEhZBHW94xEgUFGX9yn_PokWj; path=/; httponly
```

Cookie viewed from `Manage Cookies` section.

```
AuthSession=YWRtaW5AYWRtaW4uY29tOjU3RkRGQTY1OsDcEhZBHW94xEgUFGX9yn_PokWj; path=/; domain=datana; HttpOnly; Expires=Tue Jan 19 2038 03:14:07 GMT+0700 (ICT);
```

Logout API response header

```
Set-Cookie →AuthSession=; path=/; expires=Thu, 01 Jan 1970 00:00:00 GMT; httponly
```

**Comment by vegetableman** [comment]
@siwatpru Thanks for posting the issue 👍 . We are looking in to it and will keep you posted.

**Comment by vegetableman** [comment]
@siwatpru Creating the issue you mentioned here #2404, as this is a different one.

**Comment by abhijitkane** [comment]
@siwatpru Fixed in the latest version. Feel free to re-open if you're still seeing this.
