### ISSUE TITLE
Response is always displayed as HTML but have in header content-type: json

### ISSUE THREAD

**Issue by kopljan** [a85/POSTMan-Chrome-Extension#2380]
As title say, before this version Postman will correctly display response. But starting with this version he will always display as HTML and you must manually to change, every time, to JSON. Seems that Postman does not read anymore content-type in response header.
1. Postman Version: 4.7.2
2. App (Chrome app or Mac app): Windows client
3. OS details: Windows 7 64x
4. Is the Interceptor on and enabled in the app:
5. Did you encounter this recently, or has this bug always been there: with latest update
6. Expected behaviour: like before, response should be displayed automatically as JSON
7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
8. Screenshots (if applicable)

![snip_20161004085516](https://cloud.githubusercontent.com/assets/19471834/19065219/889d08ac-8a12-11e6-9f67-62b4e28efbd8.png)
![snip_20161004091255](https://cloud.githubusercontent.com/assets/19471834/19065250/c754d1b0-8a12-11e6-976d-276db0c43384.png)

**Comment by SamvelRaja** [comment]
@kopljan  I tried replicated the same from my end and it seems to be working fine that Postman auto detecting the response format using the content-type response header. Attaching a GIF, just let me know whether i missed anything while testing it. That would be great to debug further.

> You can specify to display auto select JSON in settings -> General -> Language Detection to JSON

![responseautoselect](https://cloud.githubusercontent.com/assets/5114052/19105602/76d6eab8-8b00-11e6-85f7-4a21a38b914e.gif)

**Comment by kopljan** [comment]
Hi, do you have some email address to send you endpoint which you can use for test? 
When I switch explicitly from AUTO to JSON, it is working now, but AUTO Option does not recognize properly Content-type from Response Header.

**Comment by SamvelRaja** [comment]
@kopljan Yes, kindly send the email to **help@getpostman.com**

**Comment by sdnts** [comment]
@kopljan Can you try updating to our latest version (4.8) and check if this is fixed?

**Comment by kopljan** [comment]
Hi, just updated, checked and it is working as intended. 
Thanks.

**Comment by pluralismx** [comment]
I have a php file that returns a json with all of my dashboard data to postman but chrome is not receiving the JSON response from  it. I have an AJAX method to receive server's response which is not actually getting it from JSON.parse(hr.responseText);
