### ISSUE TITLE
Collection list the URL instead of a short name or description

### ISSUE THREAD

**Issue by slchorne** [a85/POSTMan-Chrome-Extension#2381]
1. Postman Version: 4.0.3
2. App (Chrome app or Mac app): Mac app
3. Did you encounter this recently, or has this bug always been there: always

The list of calls in a collection should show or include a column for a more verbose description.
the list of URLs isn't much help since the host_name just renders all the urls identical

![screen shot 2016-10-04 at 11 09 50 am](https://cloud.githubusercontent.com/assets/1591861/19086478/32a22a5c-8a23-11e6-80b1-2190faaa2b92.jpeg)

**Comment by sdnts** [comment]
@slchorne When you save a request to a collection, you have a field in the popover modal to specify a `Name` for the request. By default, this name is the request URL, but you can change it when saving, or even after it (by hovering over the request, clicking on the ellipsis button, and choosing `Edit`).
I'm guessing while saving the requests, you did not change the request name, hence it shows all URLs.

Closing this, feel free to reopen if I misunderstood.
