### ISSUE TITLE
Feature Request - Add Mass Import Environments to Gears Dropdown

### ISSUE THREAD

**Issue by tekrat** [a85/POSTMan-Chrome-Extension#2383]
**1. Postman Version:** 4.7.2 

**2. App Version:** Windows Desktop (Electron version not Chrome App)

**3. OS details:** Windows 7

**4. Is the Interceptor on and enabled in the app:** N/A

**5. Did you encounter this recently, or has this bug always been there:** N/A

**6. Expected behaviour:**

When I click on the gears icon for managing environments there is no mass import option.   To be consistent with new WinForms drop downs add a link to the generic 'Imports' pop up window to the gears icon.  Also to be consistent with new WinForms drop downs add new set of drop downs that work like this:
- Environments _(same function as clicking the gears icon in the top right side of the application)_
  - Manage Environments _(same function as the 'Manage Environments' option found under the gears icon)_
  - Import Environments _(same function as the 'Imports' on the form)_
  - Share Environments _(same function as the 'Share Environments' option found under the gears icon)_

**7. Console logs:**  N/A

**8. Screenshots (if applicable):** http://imgur.com/a/vJguR

**Comment by a85** [comment]
Tracking here: https://github.com/postmanlabs/postman-app-support/issues/2899. Closing this issue as a duplicate.
