### ISSUE TITLE
New Feature request for Merging Collections

### ISSUE THREAD

**Issue by PradeeshKS1** [a85/POSTMan-Chrome-Extension#2385]
Hi Team,

This is new feature request to merge multiple collections. We are a small team working on automating Rest APIs using Postman.  We are adding APIs to folders and adding to the main Collection. 
Now we are making a copying of the folder and drag and drop the folder to the collection and share to the team members. The problem is if I drag and drop the folder without making the copy , the original folder is moved to the main collection and deleted from Original collection.
And we don't want to add the APIs in main collection before testing it.
So it would be great if we have a functionality to merge the Collection we are working on with the other collection

**Comment by ansharfirman** [comment]
It's will be Awesome. Make it real, Please..

**Comment by joaogomes44033** [comment]
+1

**Comment by ghost** [comment]
Seems obvious. I had to combine them with XML manually.

**Comment by a85** [comment]
This is hitting soon on production: https://twitter.com/kamalaknn/status/1081855945649483782

**Comment by vkaegis** [comment]
Aaaand it's in production! Feel free to open another issue if you have feedback around the implementation.

**Comment by huangdenghe** [comment]
Can it work now?
