### ISSUE TITLE
Postman Windows app is automatically encoding query params.  E.g. $top => %24top

### ISSUE THREAD

**Issue by edminer** [a85/POSTMan-Chrome-Extension#2386]
1. Postman Version: 4.7.2  win32 6.1.7601 / x64
2. App (Chrome app or Mac app): windows
3. OS details: Win7
4. Is the Interceptor on and enabled in the app: no
5. Did you encounter this recently, or has this bug always been there: just started using the windows version.  Have been using the Chrome plugin up till recently
6. Expected behaviour:  I expect the Windows app to act like the Chrome plugin and not auto-encode URI Components.
7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
8. Screenshots (if applicable)

Try this URI:  https://target-device/path?$top=200
Postman Chrome plugin sends that $top query param along "as-is".  Good!
Postman Windows App auto-encodes the $, sending this param to the target:  %24top    Bad!

**Comment by numaanashraf** [comment]
@edminer Thanks for reporting this. We will be rolling out a fix in the coming releases.

**Comment by edminer** [comment]
Thanks, much appreciated.

**Comment by sdnts** [comment]
@edminer We pushed a fix for this with v4.8, can you update and confirm if this is fixed for you?

**Comment by dagrooms52** [comment]
Did not work for me, for example the request I discovered this bug with:
`id eq 3D51FF02CBACFD4A480901 and `
after being saved in Postman turns into
`id%20eq%203D51FF02CBACFD4A480901%20and%20`.

**Comment by SamvelRaja** [comment]
@dagrooms52 Can you test the same in our canary version? We had fixed this recently in our canary build.
OSX: https://dl.pstmn.io/download/channel/canary/osx_64
Windows 32-bit: https://dl.pstmn.io/download/channel/canary/windows_32
Windows 64-bit: https://dl.pstmn.io/download/channel/canary/windows_64
Linux 32-bit: https://dl.pstmn.io/download/channel/canary/linux_32
Linux 64-bit: https://dl.pstmn.io/download/channel/canary/linux_64

It is been tracked here #2538

**Comment by dagrooms52** [comment]
That works, thanks @SamvelRaja
