### ISSUE TITLE
Chrome app - SugarJS Date formating not working

### ISSUE THREAD

**Issue by icougil** [a85/POSTMan-Chrome-Extension#2388]
Version/App Information:
1. Postman Version: 4.7.2
2. App (Chrome app or Mac app): Chrome app
3. OS details: Mac OS X El Capitan 10.11.3
4. Is the Interceptor on and enabled in the app: Not enabled
5. Did you encounter this recently, or has this bug always been there:
6. Expected behaviour: It should appear the Date formatted as we want
7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
8. Screenshots (if applicable)

![image](https://cloud.githubusercontent.com/assets/2370634/19159216/f1d33118-8beb-11e6-946e-b291952d56a3.png)

Steps to reproduce the problem:
1. Create a request
2. Instantiate a Date and formatting it using [SugarJS documentation](https://sugarjs.com/docs/#/Date/format) as a _Pre-request script_

```
console.log((new Date()).format('%F')+" ---");
console.log("Date: "+new Date().format('%Y%m%d')+" <<<<");
```

The result should be the date formatted as it is required.

Best,

**Comment by vegetableman** [comment]
The app uses an older version of `Sugarjs`, specifically, `1.4.1`. You could use `new Date().format('{yyyy}{M}{dd}')` for the same result. Will keep you posted as to whether we could update the lib on the sandbox.

**Comment by sdnts** [comment]
@cougil Closing this for now, feel free to reopen if you encounter any problems.
