### ISSUE TITLE
Feature: GraphQL / edit request via Pre-Request Scripts

### ISSUE THREAD

**Issue by reggi** [a85/POSTMan-Chrome-Extension#2390]
This is a big bucket ticket for GraphQL Support.

Here's an example json request body:

```
{"query":"query thomas {\n  author\n}","variables":"{}","operationName":"thomas"}
```

The behavior I'd love is to be able to put the raw query in the body like this.

``` graphql
query thomas { 
  author
}
```

Then be able to put the variables in the `params`, which can easily be tied to env vars.

Then in Pre-Request Scripts I'd love to alter the request

``` js
var body = {
   query: request.data,
   variables: request.params,
   operationName: request.params.operationName
}
request.data = JSON.stringify(body)
```

But I learned the hard way that you can't set the request data in the Pre-request Script.

I'd also love Syntax Highlighting for GraphQL somehow!

**Comment by reggi** [comment]
What I have right now as a hack is this.

Body:

```
{{request}}
```

Pre-render Script:

``` js
let query = `
query thomas { 
  author
}
`;

let variables = {

};

postman.setEnvironmentVariable("request", JSON.stringify({query, variables, operationName: ''}));
```

**Comment by sdnts** [comment]
@reggi Thanks for all the suggestions! We're looking into this. It's being tracked on #1669. Closing this, as it is easier to keep feature requests in one place :)

**Comment by hfmm99** [comment]
Is there any plan to support template literals for formatting graphQL queries in pre-request strings, like this?

let query = gql\`
  query thomas {
    author(id: 123, active: true) {
      id
      name
    }
  }\`;

And make this looks formatted like this?

![image](https://user-images.githubusercontent.com/3942700/124804750-e1c5a380-df17-11eb-9854-d1d68bc4cb62.png)

Thanks
