### ISSUE TITLE
Cannot use environment variables in tests?

### ISSUE THREAD

**Issue by iredmail** [a85/POSTMan-Chrome-Extension#2391]
Dear support,

I defined some environment variables, e.g. `name=foo`, then try to use it in tests like this:

```
var jsonData = JSON.parse(responseBody);
console.log("{{name}}");
tests["Verify name"] = jsonData.name == "{{name}}";
```

The console logs string `{{name}}` directly, not expected value `foo`.
1. Postman Version: 4.7.2
2. App (Chrome app or Mac app): Mac app
3. OS details: macOS 10.12
4. Is the Interceptor on and enabled in the app: [not sure]
5. Did you encounter this recently, or has this bug always been there: always.
6. Expected behaviour: 
7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
8. Screenshots (if applicable) N/A

Steps to reproduce the problem:
- Define some environment variables
- Use the variable in tests.

**Comment by sdnts** [comment]
@iredmail To access environment (and global) variables in pre-request & test scripts, you need to do something like this:
`var x = postman.getEnvironmentVariable('<name>')`

The `{{<name>}}` syntax does not work in pre-request and test scripts because they are written in JavaScript, hence follows JS rules.

**Comment by iredmail** [comment]
Please mention `postman.getEnvironmentVariable()` in either of doc pages below:
- https://www.getpostman.com/docs/environments
- https://www.getpostman.com/docs/pre_request_scripts
- https://www.getpostman.com/docs/sandbox
- https://www.getpostman.com/docs/testing_examples

**Comment by sdnts** [comment]
Thanks for the pointer, we'll update our docs 👍
