### ISSUE TITLE
Add the ability to ignore/disable specific requests in a collection in the runner

### ISSUE THREAD

**Issue by andreassiegel** [a85/POSTMan-Chrome-Extension#2392]
This is a feature request for the collection runner:

It would be great if it was possible to exclude requests/test cases in the collection runner, instead of either being able to select individual requests or whole collections, e.g. by adding check boxes to the runner interface.

Background:

At the moment, we are heavily testing our API using Postman and already identified some problems with a particular endpoint. However, for several reasons the test cases for this endpoint are still part of our collection which is shared among our team members, and which is also part of our CI process. Thus, removing the test cases or moving them to another collection is not feasible in this case.

**Comment by sdnts** [comment]
@andreassiegelrfid Thanks for the suggestions!
For now, you can use `postman.setNextRequest` to skip requests in the runner. [Docs](https://www.getpostman.com/docs/workflows)

**Comment by georambo** [comment]
No update on this?  Similar scenario where just want to disable a request, until a bug is fixed.

Using setNextRequest is not intuitive and extra item to manage.

**Comment by bquack** [comment]
+1

**Comment by msilkroad** [comment]
+1

**Comment by internationalbridgeinc** [comment]
+1

**Comment by tinghf** [comment]
+1

**Comment by elleryfamilia** [comment]
+1

**Comment by edsonmedina** [comment]
+1

**Comment by dantench** [comment]
+1

**Comment by juancesarvillalba-zz** [comment]
+1

**Comment by elleryfamilia** [comment]
@madebysid Hey there, any updates on whether this issue is being prioritized for a near release? It's been out there for 10 months now.

**Comment by danceric0919** [comment]
It's a very wanted function from my side. 
postman.setNextRequest is good but not good enough. why not just let ppl disable script they don't want to execute?

**Comment by tgmuender** [comment]
+1

**Comment by Stolkmeister** [comment]
+1

**Comment by ji50180** [comment]
We have about a hundred occurances of a certain pretty expensive test in several collections, in different places. We need the collection one time per day with, and several times without this request
It would be sweet if we could start newman or the postman runner with different environments,
where only the variable "ignore_request_x" is changed to either true or false. That way we would put something like this into the prerequest-script:
```
if (postman.getEnvironmentVariable("ignore_request_x")=='true'){
   postman.skipRequest;
}
```

**Comment by AI-debug** [comment]
```+1```

**Comment by davegough** [comment]
+1

**Comment by AndriiStepura** [comment]
I'm resolve this by "empty" first GET request with test code which contains counter for iterations (# of run ), as example here js code if you want start from "Request name if not first run" all iterations except first:

> //If not first iteration, we don't need again set same variables and again create same users (as ex. admin), so we skip some test setup steps and not first iteration start from another step
```
var iterationCounter = parseInt(environment.iterationCounter);
if(isNaN(iterationCounter)){postman.setEnvironmentVariable("iterationCounter", 1)}
else{postman.setEnvironmentVariable("iterationCounter", parseInt(iterationCounter)+1);}
if (environment.iterationCounter>1){postman.setNextRequest("Request name if not first run")}
```

**Comment by tomershay** [comment]
+1

**Comment by p10tyr** [comment]
+1
Even something simple as if the folder or test starts with ! or something just ignore it

**Comment by skyboyer** [comment]
+1
there are a lot of request, each time we need to run different subset of them(say, authorization + something around checking permissions and then - different things to get different flows) - that's why setNextRequest does not help

**Comment by mslancashire** [comment]
+1

**Comment by RuniQa** [comment]
At first, I admire your work on Postman. 
At the second, +1 to this thread. setNextRequest needs to be set on preceding request. However to have full workflow control you need to check conditions before request is send.

**Comment by tomasz-sienn** [comment]
+1

**Comment by kondal99** [comment]
+1

**Comment by JoGosGitHub** [comment]
+1

**Comment by pytnik89** [comment]
+1

**Comment by efrenette11** [comment]
+1

**Comment by sharmatha** [comment]
+1

**Comment by cen1** [comment]
There should just be a simple checkbox to disable specific calls, just like you can disable HTTP headers without actually deleting them. The use cases are many. `setNextRequest` is a bit wonky.

**Comment by surfjedi** [comment]
+1

**Comment by dannylevenson** [comment]
+1

**Comment by Malavos** [comment]
how is this not a feature already! +1

**Comment by nchaluse** [comment]
+1 it should become a feature, a flag somewhere, that'd be neat, really !

**Comment by andyherd** [comment]
+1

**Comment by trialTrail** [comment]
+1
How this does not already exist is boggling. We need a simple way to toggle tests.

**Comment by richja** [comment]
+1

**Comment by mccannt** [comment]
+1
We really need to see some movement on this. Its a key function that ReadyAPI has that is missing in Postman.

**Comment by adrians99** [comment]
I second this, I have multiple environments and not all requests/tests work with them so I need to skip some requests without ending the collection request workflow.
Why setNextRequest() runs then next request and then ends the flow? if I am running a collection I don't want it to end all the requests.

I suggest 2 options:

1. setNextRequest() doesn't finish the flow while using the runner in a Collection.
2. Or create a new method like "skipRequest()" to continue with the other requests. That way I can try: if(environment.url === "http://local:8080") {skipRequest()
}

**Comment by d2huynh** [comment]
+1 on "create a new method like "skipRequest()" to continue with the other requests. That way I can try: if(environment.url === "http://local:8080") {skipRequest()
}"

**Comment by dpburgess** [comment]
+1

**Comment by fabioyy** [comment]
+1

**Comment by wonl** [comment]
1++

**Comment by grafikri** [comment]
+1

**Comment by jahanzaib-ahmed-confiz** [comment]
+1 

"create a new method like "skipRequest()" to continue with the other requests. That way I can try: if(environment.url === "http://local:8080") {skipRequest()}"

**Comment by jraff89** [comment]
+1

**Comment by berniezhao11** [comment]
+1

**Comment by elleryfamilia** [comment]
@madebysid How many +1s do we need? :)

**Comment by dmweyek** [comment]
+1

**Comment by splio-baptiste-capart** [comment]
+1 !

**Comment by anshul07** [comment]
+1

**Comment by naikparag** [comment]
+1

**Comment by joachimaumann** [comment]
+1

**Comment by marexv** [comment]
+1

**Comment by dmrickey** [comment]
+1

**Comment by javiesses** [comment]
+1

**Comment by sunborn23** [comment]
+1

**Comment by tegomass** [comment]
+1

**Comment by sivaramkjs** [comment]
+1

This option would be very useful for a wide range of use cases.

**Comment by deepthakannan** [comment]
+1

**Comment by hoya1101** [comment]
+1

**Comment by tinghf** [comment]
+1

**Comment by myspringleaf** [comment]
+1

**Comment by GarthF** [comment]
+1

**Comment by jesbinsoftworks** [comment]
Hi I want to skip a folder if it's not a certain version, what's the code for this ?

**Comment by mccannt** [comment]
@jesbinsoftworks You would want to use the Postman Workflow, so you should be able to do this 
using the `setNextRequest()` function.

More info here:
https://www.getpostman.com/docs/v6/postman/collection_runs/building_workflows

**Comment by jesbinsoftworks** [comment]
I want a script that is in  javascript and it's used for pre-request Script that will do this way as it skips a folder if it's not verion <= new version , if it's not new version sit should be skiping to a next folder.

**Comment by AndriiStepura** [comment]
@jesbinsoftworks I'm trying this at this weeks, unfortunately, it does not work for all folder, my way - is set first and last (Set here unic name of las request in your folder) requests as empty calls as example get and add for first pre request script, this is example for each iteration after first (skip second and each next), but if you use runner remember to kill iterationCounter after each run:

```
var iterationCounter = parseInt(environment.iterationCounter);
if(isNaN(iterationCounter)){postman.setEnvironmentVariable("iterationCounter", 1)}
else{postman.setEnvironmentVariable("iterationCounter", parseInt(iterationCounter)+1);}

console.log("Current iteration (" + environment.iterationCounter + ") if it more than one I want skip SOAP for redundant run same tests");
console.log();

var iterationCounter = parseInt(environment.iterationCounter);

if (environment.iterationCounter>1){
    postman.setNextRequest("Set here unic name of las request in your folder");
    postman.skipRequest;
}

if (environment.iterationCounter==11){pm.environment.unset("iterationCounter")}
```

**Comment by mccannt** [comment]
@jesbinsoftworks You can do this by doing a simple `if` statement to check the version. If its `=` the version you want, do something. 
Example:
```javascript
if ($version === X){
  // Make a call to the next request you want based on the version
  setNextRequest("Do This Call");
} else {
  // If the version is not what you want, call the next request you like
  setNextRequest("Do This Other Call");
}

**Comment by jesbinsoftworks** [comment]
I have an environment called 6.4 which  most of my tests run on and there is one folder which only support version 6.5 and up so I want to skip the folder that supports 6.5 by java-script code   using the pre request Script option in tests.

**Comment by AlbertORoura** [comment]
+1

**Comment by ghost** [comment]
+1

**Comment by mverma-va** [comment]
Why do we need to wait for 2years for a feature which is needed by so many users?

**Comment by lemonkaren** [comment]
is there any good news updated?

**Comment by lexon** [comment]
+1

**Comment by naomiwu1** [comment]
+1

**Comment by michaelvannevel** [comment]
+1

**Comment by tinghf** [comment]
if it's not going to be fixed, just close it and let people have closure at least? 
if it's going to be fixed, either just fix it already or share the plan with the community (timeline?). 

What's the point of leaving a simple request like this in open state and no plan to fix it in the future anyway?

**Comment by vkaegis** [comment]
Hey guys, quick clarification here, we do have a plan to separate out scripts into individual units that can be enabled / disabled. We do not yet have an ETA on this though. We definitely understand the gravity of this use case, but just want to make sure that our implementation around this will solve not just this problem but several others around how events are structured in the Postman runtime. Will let you all know as soon as we have more concrete plans on this.

**Comment by EstherSalinas** [comment]
+1

**Comment by library1010** [comment]
+1

**Comment by SFBorland** [comment]
Any update on this..?

**Comment by ghost** [comment]
+1

**Comment by joelfogue** [comment]
+1

Here's a temp workaround while we wait for this feature to get implemented:

Assuming the collection runs alphabetically, here's how I solved this:
Let's say you have a collection "_**collection_x**_" with 4 api calls _**A, B, C and D**_
Since the collection will get executed alphabetically, in that order: _**a,b,c,d**_ then we can do the following:

**_From B, add a setNextRequest("D") to SKIP C_**

This will not work if your collection doesn't execute in the same order always and consistently

**Comment by alaeddineG** [comment]
+1

**Comment by gauravshetti** [comment]
+1

**Comment by MSkalt** [comment]
this is basic functionality

**Comment by landonr** [comment]
+1

**Comment by jovistruck** [comment]
Argh, JMeter just allows you to disable and enable elements. This isn't difficult to do Postman!

**Comment by andreicontan** [comment]
+1 - c'mon guys, you can do it!

**Comment by vermavikrant** [comment]
+1

**Comment by jhpratt** [comment]
@vkaegis Can you clean this thread up? All of the "+1" comments are completely useless. There's GitHub's reaction feature, which has existed for years.

**Comment by shamasis** [comment]
If we do this, my idea, keeping as a note here: as part of the initiative to mutate request from pre-request script, we could think of skipping the request from pre-request. But it needs more thoughts around debugging and visibility

**Comment by xsedlak** [comment]
Hi @shamasis, if do you need some input from user side I can support you. 

I have one idea how can be implemented in the JSON. We can use some comment of Disabled request/directory but I'm not sure if it's the good solution, see 
https://stackoverflow.com/questions/244777/can-comments-be-used-in-json 

Or can be used another JSON flag for disabling request/directory.
 
The debugging will ignore the part of JSON in globally and visibility will be same like in JMeter when you disable anything. 

What do you think about the solution?

**Comment by juanrb** [comment]
any updates on this feature? I used to use jmeter and this is the feature I miss the most from it

**Comment by shamasis** [comment]
Hello everyone. Before I do an elaborate update on what are our plans around this, I thought it would be a good idea to post a link to a similar issue here where I commented roughly how we intend to solve this use case. 

https://github.com/postmanlabs/postman-app-support/issues/5707

Essentially, this should be feasible in Postman where you should be able to pick and choose what you want to run, how to run them and also define how to link/chain things visually.

We are doing some ground work to reach there and would update on this in a while.

**Comment by p00j4** [comment]
Is this feature in any near roadmap? 
In my case, it's very inconvenient to add/remove setNextRequest in many tests every-time. Having a newman flag to say ignore and a small feature for bulk selection in runner to disable/enable.

**Comment by BrambleRamble** [comment]
@p00j4 makes a good point about being able to flag tests to be skipped/disabled when running a collection in Newman too. I'd like to be able to enable/disable individual requests directly in Postman, then when running the exported collection in Newman, I'd like the disabled requests to be skipped automatically.

**Comment by saswatds** [comment]
Hello @andreassiegel and everyone we have a version of collection runner that gives you the ability to select and reorder the requests before starting the run. We have released it to our canary app version `Version 7.1.1-canary03`. You can download the canary app at https://www.getpostman.com/downloads/canary

We are still polishing the UI and optimizing the performance, but while we do that, your suggestion is most welcome. Do test this feature out give us your feedback. 

I shall keep this thread posted when we move this feature to our stable version.

![runner](https://user-images.githubusercontent.com/8796447/59599614-a2537100-911c-11e9-924e-7762daef7ad6.gif)

Thanks

**Comment by uday-nitjsr** [comment]
Great to see this feature to be added. The demo looks amazing I will download this app and let you my experience with this

**Comment by cen1** [comment]
A welcome feature but not really what I proposed in #4568, feature request was explicitely for this option to exists outside of the runner.

**Comment by saswatds** [comment]
Hi @cen1, we have duly noted your request and absolutely welcome it. Be assured that we are going to constantly iterate over this feature. For the very first iteration, we wanted to try out the selection feature inside the runner and validate that everything works as it's supposed to. And also verify that we are not breaking any well-established workflows our community has already established. 

Really appreciate your feedback. We will keep our community posted as and when we are up with new updates.

**Comment by cen1** [comment]
No problem, I'll check it out and give feedback.

**Comment by a85** [comment]
Everyone, this feature is out in production. More details to follow on our blog soon. The GIF describes this feature better than words. 

On this feature to exist outside of Postman: We have designed Newman to be used for explicitly automation scenarios and you should be using a Collection file for this. We will create generators from Collection Runner but "enabling/disabling" requests will not be part of the collection format - at least of now. There are other areas of work that we will post on this tracker soon on how to handle these scenarios.

**Comment by TaukSnarkyAgrud** [comment]
I would like to post an idea to extend the feature added for this thread. 
Select (check/uncheck) followed by shift+Select inverts the check on all tests between selection.
More explicitly: We may need to disable a long list of items and individually selecting the items is slow. Shift selection of all items(much like in file explorer) would be speedy.
Another nuance to the idea would be to allow folder selection in the runner to toggle entire folders.

**Comment by TaukSnarkyAgrud** [comment]
Another idea to share with the team:
Add pre-defined Request.method: "disabled".
Execution logic hops over any request set to disabled; to the request immediately following the request(s) listed with Request[method] = "disabled"

**Comment by ismdcf** [comment]
Is it possible to do the following like mentioned in the initial post to skip the request with the help of pre-request script like postman.skipRequest

**Comment by oxygenecore** [comment]
+1 for `postman.skipNextStep()`. We are generating collections to be run in newman, and would like this feature to be purely a feature of collections or steps, not some external runner.

**Comment by ghost** [comment]
is it possible to skip a folder inside a folder during postman runner?
