### ISSUE TITLE
Include actual results and response data in the collection runner statistics

### ISSUE THREAD

**Issue by andreassiegel** [a85/POSTMan-Chrome-Extension#2393]
This is a feature request for the collection runner test results:

Even though it's nice to have the overview of all executed tests and assertions with the green and red boxes, this doesn't provide much information on what went wrong in the test.

For instance, the statistics show that my test _Status code is 200_ failed, but I don't get any information which status code actually was returned. In this regard it would be extremely helpful to at least get the status code (or more precise: the actual result for an assertion), if not even the the full response.

The information would be available in the Postman Console, but it's almost impossible to find the corresponding entry for a particular test case there if you have a large collection that you run in several hundred iterations.

**Comment by sdnts** [comment]
@andreassiegelrfid Thanks for all the suggestions! We're working on a redesign of the runner, so we'll keep those in mind :)

**Comment by rahbari** [comment]
I came here to request this feature! It's great to have req and res body tab next to passed and failed tabs in each step summary. most of the time I need res body more than tests!

**Comment by andreassiegel** [comment]
@madebysid That's great news! I'm looking forward to the redesign. :)

**Comment by sdnts** [comment]
Hey @andreassiegelrfid @rahbari The new runner is out on our canary channel. You can download it for OSX [here](https://dl.pstmn.io/download/channel/canary/osx_64).
It adds ability to view your request & response, among other new features. Do let us know of any feedback you have / bugs you find :)

**Comment by jbauerrfid** [comment]
Is there a Canary version available for Ubuntu? I would like to get better test runner results here also.
Currently I can use the Chrome app only, and that one is updated globally by Chrome, so it would be difficult to switch to a Canary channel here.

**Comment by andreassiegel** [comment]
@madebysid The new collection runner is amazing! Thanks a lot!

And, indeed, I already found a bug: Filtering passed or failed tests doesn't always work: 

![image](https://cloud.githubusercontent.com/assets/13197892/19554901/e4595416-96ba-11e6-9053-1872cae1826b.png)

As you can see, I actually selected only the failed tests, but still see all tests. Unfortunately, I don't know how to reproduce the issue. It worked when I first used the new runner, but when I retried a collection run, it doesn't anymore. It doesn't matter if I want to see the passed or failed tests, I always get all.

**Comment by SamvelRaja** [comment]
@jbauerrfid We are working on it. Will update this post once we are ready with the build.

**Comment by SamvelRaja** [comment]
@andreassiegelrfid  Thanks for bringing this to our notice we shall look into the edge case from our end as well.

**Comment by andreassiegel** [comment]
Two more bugs:
- _Run Summary_ doesn't work
- Showing results for other iterations than the first one doesn't work

If I click on either the _Run Summary_ button or the iterations numbers on the right, nothing happens.

Some information from the Developer Tools log:

```
Uncaught TypeError: Cannot read property 'scrollTop' of undefined (runner.js:55506)
...
https://app.getsentry.com/api/82351/store/?sentry_version=7&sentry_client=r…0-canary.1%22%2C%22event_id%22%3A%227dbc216dda8a4588ab10a96597126a99%22%7D Failed to load resource: the server responded with a status of 429 (TOO MANY REQUESTS)
...
Uncaught Error Uncaught TypeError: Cannot read property 'scroll' of undefined (runner.js:37884)
Uncaught TypeError: Cannot read property 'scroll' of undefined (commons.js:4312)
```

The _429 Too Many Requests_ happens a lot, it fills most of the log I see.

**Comment by SamvelRaja** [comment]
@jbauerrfid  The Linux app is out [https://www.getpostman.com/apps](https://www.getpostman.com/apps) 😄

**Comment by sdnts** [comment]
@andreassiegelrfid Thanks for the feedback!
I've isolated and fixed the results bug (2).
Haven't been able to replicate the Run Summary one though. Does it happen every time for you?
I'd also recommend joining our Slack community [here](https://www.getpostman.com/slack-invite) for easier communication :)

**Comment by andreassiegel** [comment]
@madebysid Thanks for the response and the Slack recommendation! Just joined your community! :)

Regarding the Run Summary: Let me put it like this: I never saw it working, maybe I need to download a new version.

**Comment by sdnts** [comment]
@andreassiegel The new Runner is out with our latest release (4.9) on the native apps. You should be able to see the actual request / response data now.
Thanks for all the feedback :D
