### ISSUE TITLE
Share global variables through collections

### ISSUE THREAD

**Issue by msignataur** [a85/POSTMan-Chrome-Extension#2394]
Would be nice if we can share global variables with the collections.

A lot of people have collections that contains global variables, ej:

`{{API_URL}}/users/{{ENVIRONMENT}}/search?email={{EXAMPLE_EMAIL}}`

And when them share it, receptors dont know whats the value for these variables. I as owner i know whats the final url pressing code and viewing the code snippet.

**Comment by sdnts** [comment]
@msignataur Thanks for the suggestion! We're actually working on something very similar to this. Will keep you posted.

**Comment by tariqghalib** [comment]
@madebysid @abhijitkane @a85 Anything on this, we are in dead need of this. As we are on cloud and there is literally no way to share globals

**Comment by a85** [comment]
Collection variables are available in versions 5.5+!
