### ISSUE TITLE
Feature request: Double click to edit folder name, task name

### ISSUE THREAD

**Issue by iredmail** [a85/POSTMan-Chrome-Extension#2395]
Dear developers,

Could you please consider implementing double-click to edit folder/task name? Currently we have to click the 3-dot menu ->Edit. But double-click will be much productive and save our time.

**Comment by sdnts** [comment]
@iredmail Thanks for the suggestion! This feature is in the pipeline, and should be out relatively soon. Will keep you posted :)

**Comment by vegetableman** [comment]
@iredmail You could update to the latest version, which supports renaming as an action on the menu and right-click native context menu.
