### ISSUE TITLE
Collection Runner does not send cookies

### ISSUE THREAD

**Issue by thesec** [a85/POSTMan-Chrome-Extension#2396]
1. Postman Version: 4.7.2
2. App (Chrome app or Mac app): Mac app
3. OS details: OS sierra, 10.12
4. Is the Interceptor on and enabled in the app: n.a. w/ Mac app?!
5. Did you encounter this recently, or has this bug always been there: recently, not having used it with cookies the bug might as well always have been there ...
6. Expected behaviour: cookies are sent within Collection Runner
7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):

within Builder - 1 -

Request Headers:
cache-control:"no-cache"
User-Agent:"PostmanRuntime/2.5.2"
Accept:"_/_"
Host:"dev-counter.photonengine.com"
cookie:"... yummycookiedatainhere ..."
accept-encoding:"gzip, deflate"

within Collection Runner - 2 - 

Request Headers:
cache-control:"no-cache"
User-Agent:"PostmanRuntime/2.5.2"
Accept:"_/_"
Host:"dev-counter.photonengine.com"
accept-encoding:"gzip, deflate"

Steps to reproduce the problem:
Within Builder add a cookie, run the test, see the cookie being passed (-1-).
Open Collection Runner, run the same test, see the cookie misssing (-2-).

**Comment by sdnts** [comment]
@thesec I'm unable to reproduce this. I made a collection where the first request sets a cookie and the second one has a test to verify if the cookie is sent. I had the Postman Console (Cmd + Alt + C) opened up to check the request headers. The Cookie header was present in the Runner request too.

[Here](https://documenter.getpostman.com/view/214062/gh2396/2MrXwu) is the collection I used. You can use the Run In Postman button (top right) to import this collection to your app :)

Let me know if the collection does/doesn't work for you or if I misunderstood.

**Comment by thesec** [comment]
Thanks @madebysid - "Set Cookie" requests the cookie to be set with response.
It does not pass any cookie information which is what I am trying: "Within Builder add a cookie ...".

**Comment by sdnts** [comment]
So you mean to say you set the cookie manually in the app, right?
In that case, there can be multiple reasons the cookie wasn't sent. (Having set it as HttpOnly, having set it for one path only etc.) Could you give me some more details about your cookie and the endpoint you are trying to send this to? (please remove any sensitive information). It'll be easier to debug this then. 
It is still weird that it works in the builder, but not in the runner, but having some more context should help me get to the bottom of this :)

**Comment by thesec** [comment]
Yes, the cookie is manually set from within the Builder/Manage Cookies ...

The cookie just has  "name=value; path=/; domain=.domain.com;".
The domain is the very same in Builder and Runner, ditto the environment.

**Comment by thesec** [comment]
Let me know if I can provide additional info to identify the root cause or find a solution.

**Comment by sdnts** [comment]
@thesec I've been unable to reproduce this on the native app, even after manually setting a cookie through the builder. The cookie header is always sent.
Are you looking at the request headers through the Postman Console? 

Also, can you type in `pm.cookieManager.cookies` in your Runner DevTools (View > Show DevTools) and check if the domain you are sending the request to is a property of the returned object? Also, are you working with `localhost` as the domain?

**Comment by thesec** [comment]
mmmh :/

Am looking at the headers in the console, yes.
The domain is not localhost and is not being mapped to in a custom host entry or the like.
And the domain - being part of the environment variables - is the same in Builder and Runner.

The domain is part of pm.cookieManager.cookies.

I tried to set the domain including the subdomain, with and without a leading dot ... no success.

**Comment by sdnts** [comment]
@thesec I think I've isolated the problem, and will include a fix in the next release, which should be out soon. Will keep you updated.

**Comment by thesec** [comment]
excellentamundo, thanks ahead!

**Comment by sdnts** [comment]
@thesec Can you try updating to the latest version (4.8) and verify if this is fixed?

**Comment by thesec** [comment]
Fixed, done, awesome! Thankamundo!

**Comment by thesec** [comment]
_ups_ too slippy - had not saved the test in builder. The cookie set with the cookie manager in builder is still not passed with the test in runner.

**Comment by sdnts** [comment]
@thesec Do you have the runner open when creating your cookie? The runner does not yet communicate with the main window in real time.

**Comment by thesec** [comment]
The runner was not open when I set up the cookie.

**Comment by sdnts** [comment]
Apologies on the late reply. I'm still looking into this, we'll roll out a fix with v4.8.1

**Comment by thesec** [comment]
@madebysid no worries have found a "workaround" (added the cookies' info to the environment and to the header which makes them shareable and hence seems the correct way to do this(?!), therefore in double quotes ;))
Thanks for keeping me in the loop :]

**Comment by sdnts** [comment]
Several improvements have been made to the Runner, can you try doing this now in the latest version (4.8.3)?
