### ISSUE TITLE
Feature request: Copy headers when opening a new tab by clicking link in body

### ISSUE THREAD

**Issue by gislikonrad** [a85/POSTMan-Chrome-Extension#2397]
So one thing that's been bothering me is that when I'm working with APIs that implement HATEOAS, I have to rewrite all the headers in the new tab that gets opened when I click a link in the response body.

What I feel should happen is that 
1. You click a link in the response body
2. A new tab opens with the link (this already happens)
3. The headers from the original tab get copied to the new tab. (new feature)

The inner funtionality could check if the hostname of the request url in the first tab and the hostname of the request url of the new tab are the same, and if they're not the headers would not be copied.

**Comment by a85** [comment]
There is a setting for this: https://www.dropbox.com/s/5z6g1eyrj5ur4fk/Screenshot%202016-10-14%2017.11.23.png?dl=0

**Comment by Aidenir** [comment]
Noticed this was working before, then suddenly it stopped, and I'm guessing thats when they introduced the setting maybe? Should have been on by default if that was the expected behavior.

**Comment by a85** [comment]
@Aidenir There are multiple viewpoints on this. We put in defaults as the majority opinion. :)

**Comment by Kskohli** [comment]
@a85 , the dropbox png image is not working.
