### ISSUE TITLE
Postman not launching on MAC

### ISSUE THREAD

**Issue by heathdbrown** [a85/POSTMan-Chrome-Extension#2398]
1. Postman Version: 4.7.2
2. App (Chrome app or Mac app): Chrome App
3. OS details: OS X 10.10.5 (14F1912)
4. Is the Interceptor on and enabled in the app: not known
5. Did you encounter this recently, or has this bug always been there: Several weeks, corruption on Google Chrome browser error for corrupted profile.
6. Expected behaviour: It launches
7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
8. Screenshots (if applicable)

![screen shot 2016-10-10 at 9 55 16 am](https://cloud.githubusercontent.com/assets/618460/19240516/6136ec52-8ed0-11e6-8fc2-a2bffe8f66e3.png)

Try to attempt to open the postman application.

**Comment by sdnts** [comment]
@heathdbrown Do you see any errors in the DevTools Console?

**Comment by heathdbrown** [comment]
@madebysid what am I looking for or how do I pull up those logs?

**Comment by heathdbrown** [comment]
@madebysid 
Here is the screen scrape of the dev logs. I missed the original step 7 in the posting instructions.

Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/

```
3requester.html:1 window.localStorage is not available in packaged apps. Use chrome.storage.local instead.
requester.html:1 beforeunload is not available in packaged apps.
requester.html:1 window.localStorage is not available in packaged apps. Use chrome.storage.local instead.
tester_sandbox.html:1 unload is not available in packaged apps.
common.js:127265 Could not load DB Event {isTrusted: true, type: "error", target: IDBOpenDBRequest, currentTarget: IDBOpenDBRequest, eventPhase: 2…}bubbles: truecancelBubble: falsecancelable: truecomposed: falsecurrentTarget: nulldefaultPrevented: falseeventPhase: 0isTrusted: truepath: Array[0]returnValue: truesrcElement: IDBOpenDBRequesttarget: IDBOpenDBRequesttimeStamp: 8509.310000000001type: "error"__proto__: EventAT_TARGET: 2BLUR: 8192BUBBLING_PHASE: 3CAPTURING_PHASE: 1CHANGE: 32768CLICK: 64DBLCLICK: 128DRAGDROP: 2048FOCUS: 4096KEYDOWN: 256KEYPRESS: 1024KEYUP: 512MOUSEDOWN: 1MOUSEDRAG: 32MOUSEMOVE: 16MOUSEOUT: 8MOUSEOVER: 4MOUSEUP: 2NONE: 0SELECT: 16384bubbles: (...)get bubbles: ()cancelBubble: (...)get cancelBubble: ()set cancelBubble: ()cancelable: (...)get cancelable: ()composed: (...)get composed: ()composedPath: composedPath()constructor: Event()currentTarget: (...)get currentTarget: ()defaultPrevented: (...)get defaultPrevented: ()eventPhase: (...)get eventPhase: ()initEvent: initEvent()path: (...)get path: ()preventDefault: preventDefault()returnValue: (...)get returnValue: ()set returnValue: ()srcElement: (...)get srcElement: ()stopImmediatePropagation: stopImmediatePropagation()stopPropagation: stopPropagation()target: (...)get target: ()timeStamp: (...)get timeStamp: ()type: (...)get type: ()Symbol(Symbol.toStringTag): "Event"__proto__: Object
common.js:129743 Notification System not initialized_show @ common.js:129743error @ common.js:129782onerror @ common.js:127266
```

**Comment by sdnts** [comment]
@heathdbrown From your logs, it looks like your indexedDB is somehow corrupted. Do you have Sync enabled? If yes, can you try uninstalling and re-installing  the app? When you sign back in, all your collections should be back.

If sync is not enabled, you'll have to head to chrome://indexeddb-internals/, and search for `fhbjgbiflinjbdggehcddcbncdddomop`. If you're able to find any of the folders listed there, can you zip up that folder and send it to help@getpostman.com? We might be able to recover your data. Take a backup of the folder, and then reinstall.

**Comment by heathdbrown** [comment]
@madebysid ok I backed-up the folder with the database then removed, uninstalled, reinstalled and now postman opens.

I don't use sync, and I am ok with not restoring the data, just confused on what causes the corruption or what I can do to make sure I have some type of backup locally.

If you have any advice on those topics, I would appreciate it, if not we can close this out.

**Comment by sdnts** [comment]
@heathdbrown We've been trying to get to the bottom of this, but haven't found a reliable reproduction set. So far, it looks like a Chrome issue. Sync was created to solve problems like this. I'd recommend using it to prevent data loss in the future :)

**Comment by heathdbrown** [comment]
thanks @madebysid
