### ISSUE TITLE
Set a base path at the collection level

### ISSUE THREAD

**Issue by chriskinsman** [a85/POSTMan-Chrome-Extension#2399]
I would like to set a base path at the collection level and then have each test add path specific information to the base path.

Right now as I switch between local tests, canary test and production tests I have to change each item in the collection to have a different base path.

**Comment by sdnts** [comment]
@chriskinsman You could use environment variables to do this sort of thing.
You can have a variable called `url` in your collection requests, and have three environments for your local / canary & production tests. Docs are [here](https://www.getpostman.com/docs/test_multi_environments).

**Comment by chriskinsman** [comment]
the problem with environment variables is that when using the UI i frequently switch between environments.  Using environment variables would require me to quit and restart the UI each time I switch environments which is very disruptive.

**Comment by sdnts** [comment]
@chriskinsman You wouldn't need to restart the UI every time, you can use the environment dropdown on the top right to switch between environments. You can use the Eye icon on the top right to preview your currently active environment.

**Comment by chriskinsman** [comment]
Thanks for being patient.  I misread your reply as a shell environment variable.  This is exactly what I was looking for
