### ISSUE TITLE
Define headers at the collection level

### ISSUE THREAD

**Issue by chriskinsman** [a85/POSTMan-Chrome-Extension#2400]
I have a collection of requests that point at a specific environment.  Each environment requires a different auth header.

As I switch environments I have to change the auth header for each request.  Would be nice to change it at collection level and have it apply to all enclosed requests.

**Comment by sdnts** [comment]
@chriskinsman Are you using Postman's auth helpers to generate those headers? If yes, you could use environment variables in the parameters. That way every time you switch environments and send the request, your headers would be generated automatically.
If you're not using Postman's helpers, then you can use environment variables to store the actual generated header as an environment variable, and use that in the Headers section.

Let me know if I misunderstood

**Comment by chriskinsman** [comment]
the problem with environment variables is that when using the UI i
frequently switch between environments.  Using environment variables would
require me to quit and restart the UI each time I switch environments which
is very disruptive.

**Comment by a85** [comment]
You can now use Collection level auth, pre-request scripts, test scripts and variables to reduce duplication at a request level. I suggest trying those out. Available in versions 5.5+
