### ISSUE TITLE
cURL request differs from UI request, due to URL-encoding differences

### ISSUE THREAD

**Issue by PhilipSharman** [a85/POSTMan-Chrome-Extension#2405]
1. Postman Version:
   - Chrome: 4.7.2, OS X / x86-64, Chrome 53.0.2785.143
   - Macintosh: Version 4.7.2 (4.7.2)
   - Windows: 4.7.2, win32 6.1.7601 / x64
1. App (Chrome app or Mac app):
   - Chrome app
   - Macintosh standalone app
   - Windows standalone app
2. OS details:
   - Macintosh: OS X, 10.11.6
   - Windows: Windows 7
3. Is the Interceptor on and enabled in the app: No
4. Did you encounter this recently, or has this bug always been there: Recently.
5. Expected behaviour: The URL in the cURL code should match the URL used by the UI.

Steps to reproduce the problem:
1) Use a URL with URL-encoded spaces (e.g. http://www.example.com/some%20name).
2) Generate a GET request via the UI.
3) Compare that to the cURL code generated by clicking the "code" button.

My understanding is that the Postman application no longer automatically URL-encodes anything. (Which is fine.) But it seems that the cURL code still does.

I have found:
- The UI generates a request with the correct URL. (http://www.example.com/some%20name)
- The cURL code incorrectly encodes the "%" sign. (Resulting in: curl -X GET -H "Cache-Control: no-cache" -H "Postman-Token: 1f6d385c-8b4a-fcef-ee87-b895c8fb9139" "http://www.example.com/some%2520name")

Furthermore, there are differences in how this affects OAuth 1 authentication (when running the request via the UI):
1. In the Chrome app, authentication works okay.
2. In the standalone Mac app and the standalone Windows app, authentication fails. (There is a "signature_invalid" error.)

I'm guessing that the standalone versions of Postman are using the (incorrect) cURL version of the URL, whereas the Chrome application is using the original URL.

Thanks.

**Comment by sdnts** [comment]
@PhilipSharman Thanks for the detailed report. I was able to find the problem. It is fixed, and should be out with the next release. Will keep you updated.

**Comment by PhilipSharman** [comment]
Right on! Thanks.

**Comment by sdnts** [comment]
@PhilipSharman Can you try updating to the latest version (4.8.3) and check if this is fixed?

**Comment by PhilipSharman** [comment]
Yes, I can confirm that this is fixed in v4.8.3. Thanks!
