### ISSUE TITLE
Undefined Bearer token when saving oauth2 tokens from box.com

### ISSUE THREAD

**Issue by stridera** [a85/POSTMan-Chrome-Extension#2406]
1. Postman Version: 4.7.2
2. App (Chrome app or Mac app): Mac
3. OS details: OS X El Capitan (10.11.6)
4. Is the Interceptor on and enabled in the app: No
5. Did you encounter this recently, or has this bug always been there: First time trying
6. Expected behavior: Should obtain and use a valid oauth token
7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app): N/A
8. Screenshots (if applicable)

Attempt to connect to the Box API following instructions here:  https://docs.box.com/reference#oauth-2-overview

I'm able to enter my information and it brings up the grant window, which I accept.  It then completes and looks ok.  However, when I add the token to my headers I get: "Authorization:Bearer undefined"

**Comment by sdnts** [comment]
@stridera Do you also see `undefined` as the value of the `access_token` field in the OAuth2 details view in the UI?

![screenshot-2016-10-13-15 43 23](https://cloud.githubusercontent.com/assets/7689783/19345613/ba43e758-915c-11e6-894b-9f1df6275f3c.png)

**Comment by stridera** [comment]
I don't have any field in the token other than name.
<img width="755" alt="screen shot 2016-10-13 at 3 11 17 pm" src="https://cloud.githubusercontent.com/assets/1100365/19368906/403801a6-9157-11e6-88ce-0cd1726baa6b.png">

**Comment by sdnts** [comment]
@stridera That's weird that the response did not contain an `access_token`. Could you also upload a screenshot of your Get Access Token modal (with sensitive info redacted)? I'm trying to replicate this issue on my end. A simple OAuth2 request works for me, but maybe I'm missing something.

**Comment by stridera** [comment]
My bad.  The token url was slightly off.  You might call it a bug in the sense that it never told me of a failed call.

**Comment by sdnts** [comment]
That's interesting, we'll try to make it more obvious when a call failed.

**Comment by charles-studio** [comment]
![image](https://user-images.githubusercontent.com/15262389/32218390-b28b5c44-be65-11e7-9775-1343b9ef29fd.png)
Authorization:Bearer undefined

**Comment by pawan-mittal** [comment]
I am also facing same issue. Bearer token is un-defined for Auth 2.0

**Comment by p1111-0** [comment]
we are facing the same issue on Postman for Chrome version 5.5. Please suggest.

**Comment by marcodafonseca** [comment]
Same issue here. Not sure what I'm doing wrong.
