### ISSUE TITLE
Body is sent in the GET request when it was previously POST type of request

### ISSUE THREAD

**Issue by kiedysktos** [a85/POSTMan-Chrome-Extension#2407]
Version/App Information:
1. Postman Version: Version 4.7.2 (4.7.2)
2. App: OS X
3. OS details: OS X 10.12 - Sierra
4. Is the Interceptor on and enabled in the app: no
5. Did you encounter this recently, or has this bug always been there: recently

Reproduction steps:
1. Define a GET type of request, save it
2. Change the type to POST, add some body JSON
3. Save request
4. Switch request type back to GET
5. Save request
6. Run request by clicking "Send" - works well, no body sent.
7. Run request in Runner

**Result:** The body input in step 2 is sent! It is not visible in Postman GUI, but you can see it in the console. My tests are failing because of this. 

The body resent when you export collection to .json file and find the request.

Workaround: delete the body from the .json file, replace it with empty raw body.

**Comment by sdnts** [comment]
@kiedysktos Thanks for reporting this. We are aware of the issue and are working on this. This was actually reported earlier in #2308. Will keep you updated.

**Comment by sdnts** [comment]
@kiedysktos Can you try running your collection in the latest version (4.8.3) and check if the GET body is still being sent?
