### ISSUE TITLE
Keyboard shortcut on macOS: Close "Collection Runner" window with CMD+w

### ISSUE THREAD

**Issue by iredmail** [a85/POSTMan-Chrome-Extension#2408]
Dear developers,

On macOS, there's no keyboard shortcut to close "Collection Runner" window. I suggest use CMD+w for this, it's commonly used by many macOS applications.

**Comment by vegetableman** [comment]
@iredmail You could use `CMD + SHIFT + W` to close the window. It isn't in the shortcuts list in the settings dialog (it will show up in the upcoming release ^_^).

**Comment by iredmail** [comment]
But why CMD+SHIFT+W? CMD+W (2 keys) is easier to press, and not used by other feature.

**Comment by sdnts** [comment]
Hey @iredmail, `Cmd + W` is used in the app to close a tab. Mixing these shortcuts in the main app and the runner would lead o inconsistency :)
