### ISSUE TITLE
UX improvement/suggestion after duplicating a request

### ISSUE THREAD

**Issue by shmup** [a85/POSTMan-Chrome-Extension#2409]
Here's a common scenario for me:
1. Create and define a request within Postman. Save.
2. Duplicate it, as I want to make a similar request
3. Immeditely click the ellipsis menu next to the duplicated entry and adjust its name.
4. Then I start adjusting the Tests and Body parameters. Save.

Except.. and this is probably something I need muscle memory to develop for, I've been in the previous request window this whole time. Because duplicating doesn't put focus in the Collections menu on the left.

After a month of using Postman/newman at work, you'd think I'd have made a mental note: duplicate AND BE SURE TO CLICK the new entry in the side-pane.

I was curious if you've considered having duplicate trigger Collection menu focus, and maybe you intended it to not work that way.

**Comment by vegetableman** [comment]
@shmup Thanks for posting this issue 👍 .
@vkaegis @bhawna2109 thoughts?

**Comment by vkaegis** [comment]
Thanks for reporting this @shmup! Completely missed this, expect a fix in the coming versions!

**Comment by vegetableman** [comment]
@shmup The issue has been fixed in the recent release `4.8.3` . Closing this. Feel free to reopen if the issue still exists ^_^.
