### ISSUE TITLE
Any discussion of modifying/extending the existing context menu?

### ISSUE THREAD

**Issue by shmup** [a85/POSTMan-Chrome-Extension#2410]
Just a simple question/thought: with your own context menu you could add a Chrome-esque solution to having way too many tabs open:

![image](https://cloud.githubusercontent.com/assets/118710/19388177/3b554938-91ec-11e6-9cfe-c3fd88508c8a.png)

To extend, I suppose it could trigger in other areas pretty nicely. A right click in the Collections pane could be another implementation of the ellipses menu (edit, duplicate, delete). It's probably a nice rule of thumb to leave native context menus in any form based windows: so the general working area would probably be left alone, really any input box at all. On the other hand, extending the existing one in textareas like the Tests would allow for a quicker insertion of snippets.

I'm not sure what a clean/nice solution would be, or if any is needed at all.

Mostly though, I just wanna quickly close _all these damn tabs_. 😄 

![image](https://cloud.githubusercontent.com/assets/118710/19388341/1aadd5b4-91ed-11e6-89ce-244068002c74.png)

**Comment by numaanashraf** [comment]
@shmup We are working on context-menu actions on tabs and sidebar. We'll keep you posted on the progress. 😄

**Comment by a85** [comment]
This is coming up in 4.9

**Comment by a85** [comment]
Out now on native apps! 
<img width="471" alt="screenshot 2016-12-21 22 07 40" src="https://cloud.githubusercontent.com/assets/653409/21397469/e684a214-c7c9-11e6-8d80-d7f66d3a19cf.png">
