### ISSUE TITLE
Windows app calculates the OAuth signature differently from the Chrome application

### ISSUE THREAD

**Issue by chris-deluca** [a85/POSTMan-Chrome-Extension#2411]
1. Postman Version: 4.8.1
2. App (Chrome app or Mac app): Windows App
3. OS details: Windows Server 2012 R2
4. Is the Interceptor on and enabled in the app: No
5. Did you encounter this recently, or has this bug always been there: Always
6. Expected behavior: Signature calculation should be identical between the Windows and Chrome applications.
7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app): Attached
8. Screenshots (if applicable)

Repro Steps:
1. Submit the same OAuth request from the Windows and Chrome apps.

This might be due only to character encoding differences when data is submitted. It is unclear if the devtools app is just translating the characters differently or if the data is being submitted differently.

[Win32vsChromeAppBug.txt](https://github.com/postmanlabs/postman-app-support/files/530426/Win32vsChromeAppBug.txt)

**Comment by vegetableman** [comment]
@Chris-Deluca Thanks for posting this issue along with the attached log file 👍 . This is a tough one to reproduce. Would be great if you could send a screenshot of the request headers on the Postman Console (`View -> Postman Console`) on the native app after you send a request (with the key redacted of-course).

**Comment by chris-deluca** [comment]
![snip_20161017112458](https://cloud.githubusercontent.com/assets/21092038/19449941/6d17f17e-945c-11e6-9bd3-2ac5ab956e6e.png)
![snip_20161017112515](https://cloud.githubusercontent.com/assets/21092038/19449940/6d15c336-945c-11e6-9465-3fad75ff52c0.png)

Here are two screenshots for you.  The keys are test keys and aren't real - so no need for redacting.  If you need we can even do a "remote view" session so you can see it in action yourself or I'm happy to get any data you need.

**Comment by vegetableman** [comment]
@Chris-Deluca Remote view would be great 👍 . You could get in touch with me through the postman community on slack.

**Comment by shaworth** [comment]
I updated to 4.8.0 on mac and immediately ran into this issue.  Literally was running collections one minute, accepted the upgrade, and my collections no longer worked (on the mac).   Prior to the update both the mac and windows behaved the same.  Now I am seeing oAuth1.0 errors on all requests from the mac, the same collection works perfectly on windows.

Same behavior for both the chrome extension on mac, and the app.

**Comment by shaworth** [comment]
I attempted to create the exact same request on windows and mac, with the intent of using tcpdump to capture the resulting requests on my host.  In the process I uncovered what I believe to be a bug, which may or may not be related to this issue.

Mac chrome extension, installed in the past hour (how do I tell the version?):
- enter a URL, set method to POST.
- Select OAuth 1.0 from Authorization tab
- Enter 1234567890ABCDEF for consumer key, consumer secret, token and token secret.
- HMAC-SHA1 as the signature method
- Timestamp of 1234567890
- nonce of 123456
- Version 1.0
- Realm OAuth

Uncheck 'Add params to header', check the other three
Click 'Update Request' which updates the URL. 

Notice, that either the timestamp, or the nonce have been changed depending on which was changed the latest.

Repeat the same on windows.

Notice, that the timestamp and nonce have not been changed.

This prevents me from sending the same traffic from mac and windows which eliminates the ability to dump the packets and compare the resulting traffic empirically.

**Comment by shaworth** [comment]
Is it possible to revert to the previous version?  I need postman on my Mac.  :)

**Comment by sdnts** [comment]
@shaworth Could you drop a mail to help@getpostman.com?

**Comment by SamvelRaja** [comment]
@shaworth can you provide me the details of the version you were updated from? so that we make sure it is not a recent release regression.

**Comment by shaworth** [comment]
@SamvelRaja , I'm afraid that prior to this issue I've never needed to know the version.  Generally I accept the upgrades when prompted.  Is there a client-side log that provides upgrade information?

**Comment by SamvelRaja** [comment]
@shaworth hope you received the 4.7.2 download link from us. Can you check and let me know whether it is reproducible there?

**Comment by shaworth** [comment]
@SamvelRaja , I did not receive the download link.  I just edited my profile to make my e-mail address public, please resend link directly to my e-mail.  I will be able to test later today.  Regards.

**Comment by SamvelRaja** [comment]
@shaworth Sent you the link of the older version 😄

**Comment by SamvelRaja** [comment]
@Chris-Deluca  @shaworth We had made the changes in our authorization flow kindly check and confirm the same.

**Comment by chris-deluca** [comment]
I tested with v4.9.0 and the issue is exactly the same - no change.

**Comment by sdnts** [comment]
Is this still an issue?
