### ISSUE TITLE
Hide main menu ability in windows native application

### ISSUE THREAD

**Issue by abhdr** [a85/POSTMan-Chrome-Extension#2412]
I think Postman Windows nativie application this ablity.

**Comment by a85** [comment]
@vegetableman Can you illustrate this better here?

**Comment by vegetableman** [comment]
@abhdr Not sure if I got it right but you meant the app should be able to hide the native menubar with `File`, `Edit`, ...  on the postman windows app, right?

**Comment by abhdr** [comment]
Hi,

Definetly that one :)

**Comment by sdnts** [comment]
@abhdr Won't this violate the pattern that all native Windows app follow?

**Comment by abhdr** [comment]
I assume not; because most of the native win app has this feature  - like [visual studio code](https://github.com/Microsoft/vscode/issues/945) -

**Comment by rodrigopmatias** [comment]
Copy Insomnia hide menu.

**Comment by pf1gura** [comment]
I see this issue was closed. I just installed Postman and I don't think this ever made it into the app. Is this not going to be implemented?

cc: @SamvelRaja
