### ISSUE TITLE
Postman mac App's Developer Tool not show request correct

### ISSUE THREAD

**Issue by 016** [a85/POSTMan-Chrome-Extension#2413]
1. Postman Version: Version 4.7.0 (4.7.0)
2. App (Chrome app or Mac app):Mac App
3. OS details:Mac os 10.11
4. Is the Interceptor on and enabled in the app: no idea
5. Did you encounter this recently, or has this bug always been there: 100% repeat
6. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
   🌏 disconnected from sync service. possibly a network outage.
   sails.io.js:142 🌏 scheduled reconnection attempt #1 after 14708ms
   sails.io.js:142 🌏 reconnecting to sync service. #(1/8)
   sails.io.js:142 🌏 reconnected to sync service after being offline for 15.909seconds.
   sails.io.js:142 🌏 connected to sync service.
   sails.io.js:142 🌏 disconnected from sync service. possibly a network outage.
   sails.io.js:142 🌏 scheduled reconnection attempt #1 after 6970ms
   sails.io.js:142 🌏 reconnecting to sync service. #(1/8)
   sails.io.js:142 🌏 reconnected to sync service after being offline for 8.596seconds.
   sails.io.js:142 🌏 connected to sync service.
   requester.js:269134 🐶 watchdog checking connection health

Steps to reproduce the problem:
1. Menu Bar, View->Show DevTools
2. open Network tab, just like what we did in chrome.
3. send GET request "http://localhost/xxx/api/web/index.php/v1/system-states"
4. in Network I found two requests
4.1 Frist Request URL:data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==
Request Method:GET
Status Code:200 OK (from cache)
4.2 Second Request URL:blob:file:///eef0f00f-be4e-4aa6-ab9f-979806c1833c
Request Method:GET
Status Code:200 OK (from cache)

looks Postman send request by some strategy, I want it show direct request in Network like chrome did.

can anyone help?

thx.

**Comment by sdnts** [comment]
@016 If you're looking for the request and response details, you can open up the Postman Console (Cmd/Ctrl + Alt + C). That will show up all details you might need.

**Comment by 016** [comment]
@madebysid Jesus, I found it, thx. Can u explain a little bit why I can't see it in Network? sometime we need Timing and some stuff.

Or maybe you can direct show me how to put it back Network like Chrome inspector?

thx again.

**Comment by sdnts** [comment]
The Postman native apps are built on top of a NodeJS based runtime, which means they won't show up in the Chrome DevTools, but it'll allow us to do other things like concurrent requests, sending restricted headers, etc. You can read more about this [here](http://blog.getpostman.com/2016/08/26/the-postman-console/)
