### ISSUE TITLE
Not able to click links in the response

### ISSUE THREAD

**Issue by jtenar** [a85/POSTMan-Chrome-Extension#2414]
Hello, Ive noticed this was already reported in issue no. #1101 which is already closed but I'm facing the same issue on version:
4.8.0
win / x86-64
Chrome 53.0.2785.143

Any workarounds?

**Comment by sdnts** [comment]
@jtenar I assume you are using the Chrome app, right?
Is there a URL I can make a request to to reproduce this?

Could you try sending a GET request to `echo.getpostman.com/get` on the latest version (4.8.1) and check if the issue persists there as well? (There would be a `url` field in the response whose value should be clickable)

I think it might be related to the way we distinguish between URLs and normal text.

**Comment by jtenar** [comment]
Morning Siddhant,
This is what I get when I try to do the get request to the URL you send me:
{"args":{},"headers":{"host":"echo.getpostman.com","user-agent":"Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36","postman-token":"f748111c-43cb-fae9-fa6f-5c155434751a","accept":"_/_","accept-encoding":"gzip, deflate, sdch","accept-language":"es-ES,es;q=0.8","cookie":"sails.sid=s%3AtJLXgEEAIGuHDgh1ZOL4Zldd9BpmWYuA.LGG7JCZIg0WpIzYKzj8D50mn0TQu5sfPImdJFqFpRuQ","via":"1.1 CWS_proxy","cache-control":"no-cache"},"url":"http://echo.getpostman.com/get"}
I'm running 4.8.0.
Thanks for your follow up.
Regards,
JT

```
  From: Siddhant Sinha <notifications@github.com>
```

 To: postmanlabs/postman-app-support postman-app-support@noreply.github.com 
Cc: jtenar j_tenar@yahoo.com; Mention mention@noreply.github.com
 Sent: Monday, October 31, 2016 1:29 PM
 Subject: Re: [postmanlabs/postman-app-support] Not able to click links in the response (#2414)

@jtenar I assume you are using the Chrome app, right?
Is there a URL I can make a request to to reproduce this?Could you try sending a GET request to echo.getpostman.com/get on the latest version (4.8.1) and check if the issue persists there as well? (There would be a url field in the response whose value should be clickable)I think it might be related to the way we distinguish between URLs and normal text.—

**Comment by jtenar** [comment]
Hi Siddhant,
I've updated to 4.8.1 and still get the same issue.
No link is shown with your url, and with the links on my test page, if I click them, nothing happens...
Best regards,
JT

```
  From: Siddhant Sinha <notifications@github.com>
```

 To: postmanlabs/postman-app-support postman-app-support@noreply.github.com 
Cc: jtenar j_tenar@yahoo.com; Mention mention@noreply.github.com
 Sent: Monday, October 31, 2016 1:29 PM
 Subject: Re: [postmanlabs/postman-app-support] Not able to click links in the response (#2414)

@jtenar I assume you are using the Chrome app, right?
Is there a URL I can make a request to to reproduce this?Could you try sending a GET request to echo.getpostman.com/get on the latest version (4.8.1) and check if the issue persists there as well? (There would be a url field in the response whose value should be clickable)I think it might be related to the way we distinguish between URLs and normal text.—

**Comment by sdnts** [comment]
@jtenar I think I misunderstood you. Are you talking about links in the `Preview` section of the response? If so, these links are not supposed to work because of security concerns.

URLs in the actual response body (JSON or otherwise), are supposed to open up as a Postman request in a new tab.

**Comment by jtenar** [comment]
Ok. If it is so, you can close the support question then.
Thanks for your time and follow up...

```
  From: Siddhant Sinha <notifications@github.com>
```

 To: postmanlabs/postman-app-support postman-app-support@noreply.github.com 
Cc: jtenar j_tenar@yahoo.com; Mention mention@noreply.github.com
 Sent: Tuesday, November 1, 2016 10:16 AM
 Subject: Re: [postmanlabs/postman-app-support] Not able to click links in the response (#2414)

@jtenar I think I misunderstood you. Are you talking about links in the Preview section of the response? If so, these links are not supposed to work because of security concerns.URLs in the actual response body (JSON or otherwise), are supposed to open up as a Postman request in a new tab.—
