### ISSUE TITLE
Contents of "exec" tag are formatted to be a string on export from an array.

### ISSUE THREAD

**Issue by message2prateek** [a85/POSTMan-Chrome-Extension#2417]
Version/App Information:
1. Postman Version: 4.8
2. App (Chrome app or Mac app): Chrome App
3. OS details: Windows 8
4. Is the Interceptor on and enabled in the app: Yes
5. Did you encounter this recently, or has this bug always been there: Always been there
6. Expected behavior: When exporting a collection using the "Collection Formatter V2" I expect the Exec variable to stay as an array when the collection is imported and the exec is an array.
7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
8. Screenshots (if applicable)
   ![image](https://cloud.githubusercontent.com/assets/18386256/19460575/65c2eaf4-9539-11e6-910d-6887208e7f2a.png)
## Steps to reproduce the problem:
1. Choose to export a collection to a json file using the "Collection V2" format. 
2. Open the exported collection.json file into a text editor.
3. The test scripts which are available under the "exec" tag are formatted on a single line as a string. 
4. Change the value exec variable from a String to an array of Strings 
   i.e. 
   from 

```
"exec" : "line1\n;line2\n"
```

```
"exec" : [ "line 1",
              "line 2"
            ]
```
1. Save and import into Postman.
2. Export from Postman, the exec is reformatted to 

```
"exec" : "line1\n;line2\n"
```

This makes it very hard to diff between versions.
## Expected Output
1. The exec values should retain the formatting and be exported as an array.
## Actual Output
1. The exec values get reformatted to be a string on export.

**Comment by caliginouspierson** [comment]
I find this particularly annoying, we trialed postman as a simplier more flexible version of soapUI. 
We commit all postman collections to a VCS and rely on Pull Requests for quality, the inability to see changes because it's on one line is a real pain. 

I think the default should be scripts on multiple lines.

**Comment by sdnts** [comment]
@message2prateek @caliginouspierson That makes sense. We've changed this behaviour so that the app now exports multiline tests / pre-request scripts as an array of strings rather than a `\n` separated string. We'll be rolling out a fix in the coming releases :)

**Comment by sdnts** [comment]
Hey guys, can you guys try updating to the latest version (4.8.3) and check if the exports work the way you expect?
