### ISSUE TITLE
Could not get any response when 204: No Content returned from server

### ISSUE THREAD

**Issue by DCRichards** [a85/POSTMan-Chrome-Extension#2418]
1. Postman Version: 4.8.0 (4.8.0)
2. App (Chrome app or Mac app): Mac app
3. OS details: Mac OSX 10.11.5
4. Is the Interceptor on and enabled in the app: N/A (Mac app)
5. Did you encounter this recently, or has this bug always been there: Recent but not tried before
6. Expected behaviour: Status code should be 204 No Content and response headers displayed
7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app): No relevant info in the Dev tools, Postman Console shows `Error: Parse Error` in console, but with no further information.
8. Screenshots (if applicable)

Steps to reproduce the problem:
1. Make a request which returns a 204, in this case, I'm making a POST request.
2. `Could not get any response` displayed and the status code not shown as 204, instead just the message `There was an error connecting to <URL>`
3. Making the same request with 200, 201 etc response codes works correctly and the status code is correctly displayed. Trying the same request in cURL gives the correct response:

``` shell
< HTTP/1.1 204 No Content
< Server: nginx/1.11.3
< Date: Tue, 18 Oct 2016 09:40:40 GMT
```

**Comment by DCRichards** [comment]
Just had a thought on this actually, could it be the `Content-Type` header? It looks like I might still be sending `application/json` as that's the default for the API and the way it's set up. Is Postman trying to parse it regardless of the 204?

**Comment by sdnts** [comment]
Which API are you using? Can you try doing the same using `http://echo.getpostman.com/status/204`? This is a test service.
I'm on v4.8, and this endpoint works fine for me, even with the Content-Type header.

**Comment by DCRichards** [comment]
@madebysid That works for me fine. The API is our own private API so sadly I can't open it up for poking, I might try when the _response_ returns `Content-Type: application/json` rather than sending in the request

**Comment by sdnts** [comment]
@DCRichards Did you manage to reproduce this?

**Comment by DCRichards** [comment]
@madebysid I've not yet found an isolated test case. What I have seen is when proxying the same API call through a different server (so the 204 response is the same, but sent from my proxying server rather than the other), postman responds correctly, so it's something specific to that server. It's wordpress using the Oauth2 plugin but not sure why that's making a difference....

**Comment by sdnts** [comment]
@DCRichards This is just a thought, but do you perform a redirect in any way with your old setup? The app will, by default, try to follow these redirects. Can you try switching off automatic redirects in Settings > General and see if the problem persists?

**Comment by DCRichards** [comment]
Ah, that's a thought @madebysid, I'll give it a try and let you know! Thank you

**Comment by igorsantos07** [comment]
I'm facing the same issue, also on a private API :(

If I copy the `curl` code Postman generates, add `-i` to get headers, I get this on command-line:

```
HTTP/1.1 204 No Content:
Server: nginx
Date: Thu, 10 Nov 2016 17:52:12 GMT
Connection: keep-alive
Access-Control-Allow-Origin: https://localhost:8080
```

I was also outputting `content-type: application/json`, but removing it made no difference.

Linux Mint 18, Postman desktop 4.8.1. Nothing useful shows on the console, as with the OP.

**Comment by igorsantos07** [comment]
Actually, while testing out I removed the content-type while changed the timeout setting to a bad value.
Setting timeout to 0 (as default) and **not** sending the JSON content-type with the 204 response solved the matter for me.

I found no clear, canonical answer on [204](https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.2.5) vs. [Content-Type](https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.17), but from my humble interpretation, 204 should ideally not send a Content-Type header, as there's no content to encode neither would be (as in the case of a HEAD response):

> The 204 response MUST NOT include a message-body, and thus is always terminated by the first empty line after the header fields.
> 
> The Content-Type entity-header field indicates the media type of the entity-body sent to the recipient or, in the case of the HEAD method, the media type that would have been sent had the request been a GET.

Thus, it _feels_ that Postman is correct on trying to parse something that has a content-type. Maybe a warning should be added to that list of suggestions, stating that empty responses should not contain a content-type? Or should it be a cool guy and skip parsing if the response is empty?

**Comment by chimit** [comment]
The problem is still there. Postman has a confusing behavior on `204: No Content` server response. It doesn't show the response body and even HTTP status. It only displays an error:

```
Could not get any response
There was an error connecting to http://local.app/v1/devices/2.
Why this might have happened:
The server couldn't send a response:
Ensure that the backend is working properly
Self-signed SSL certificates are being blocked:
Fix this by turning off 'SSL certificate verification' in Settings > General
Client certificates are required for this server:
Fix this by adding client certificates in Settings > Certificates
Request timeout:
Change request timeout in Settings > General
```

Please, make Postman able to display at least HTTP response status 204 or better along with a response body.

**Comment by malvadeza** [comment]
Some problem here.
On Desktop App (Windows/Mac) it doesn't work, but as the Chrome App postman is able to show the response code (it works).

**Comment by themirror178** [comment]
Same problem here (Windows App), works on Chrome App.

**Comment by doggy8088** [comment]
When I have `Location` header in the response headers, my Windows App v5.0.2 will get the same problem.

**Comment by Whyounes** [comment]
Problem still exists in version 5.1.2

**Comment by 0xceb1d** [comment]
Still having this issue. 
Postman displays the body when changing response to something else (i.e 200)

**Comment by developer99** [comment]
I do not think it is supposed to return anything by standards.

See [https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html](https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html)

_The 204 response MUST NOT include a message-body, and thus is always terminated by the first empty line after the header fields._

Oh. duh  @igorsantos07 already said this.  :)

**Comment by developer99** [comment]
In my case, perhaps I have misinterpreted the reason to return 204.  I am using it when a query seeking records does not find any.  No records, return 204 (no content).

> The server has fulfilled the request but does not need to return an entity-body

But perhaps I DO need to return data and should return status 200 OK and return a message such as `"message":"No records found"` and/or an empty record set.  

Which would be best for the developer?  Status 204 (No content) or Status 200 (OK) with empty record set and/or message?

I do not think either breaks any rules or interpretation of status codes necessarily.

**Comment by igorsantos07** [comment]
@developer99 I suggest you to post those questions on a forum such as StackOverflow. That's off-topic, as we're discussing here an issue with Postman interpretation of 204 responses :)

> (psssst, hint: return 200 `{}` instead of a message stating there are no records. Your API should return a list of records, even when that list is empty)

**Comment by ghost** [comment]
<img width="1440" alt="screen shot 2017-10-30 at 18 00 27" src="https://user-images.githubusercontent.com/12474491/32167687-3d3a4bcc-bd9c-11e7-8f63-8f68d5c267ae.png">
I've the same issue in macOS native app and chrome app. But if the service was called from localhost everything work fine.

**Comment by nirmalgoswami** [comment]
same issue here

**Comment by ERPedersen** [comment]
I can confirm that this is happening for me and another of my colleagues as well. It happens regardless of whether the request has a body or not.

**Comment by kapitanluffy** [comment]
I am having this issue as well.

**Comment by jmauerhan** [comment]
This is a problem for me as well, if I do this request in curl, I get the correct response:
```
HTTP/1.1 204 No Content
Server: nginx
Content-Type: application/json
Connection: keep-alive
Cache-Control: no-cache, private
Date: Tue, 15 May 2018 21:43:08 GMT
```

But Postman shows me the confusing "Could not get any response" and no way to view the headers to see that I did in fact get a 204.

**Comment by omar-faruk-sust** [comment]
I am having same issue as well. anyone have any solution ?

**Comment by yanxiaodi** [comment]
I think it's not the problem of Postman. As @igorsantos07 said, we should follow the HTTP specification. Make sure there is no body in the response if it returns 204. Otherwise, ask the APIs service provider first.

**Comment by kudlohlavec** [comment]
Totally agree with @igorsantos07 and @yanxiaodi . I had the same issue, I was testing some stuff so I got some testing messages in the code and were returning 204 response with notorious "Could not get any response" message in postman.
After removal of all messages in the code and returning only empty 204 response code, everything started to work properly in postman.

**Comment by shamasis** [comment]
Hey... I took a dig at locally reproducing this. Phew! Getting a server to misbehave is really tricky. I am very comfortable with NodeJS and sadly I could not create a server that would send 204 and body.

I am sure of one thing though - can confirm that 204 without body works fine on Postman, irrespective of request method / header / whatever.

I will switch to some low-level language to make a misbehaving server. PS If anyone has anything handy to speed me up, let me know.

The test code I used (not relevant):
```
const http = require('http')
const port = 3000

const requestHandler = (request, response) => {
  console.log(request.url)
  response.writeHead(204);

  response.write('some data', function () {
    console.log('sent');
    
    response.end('Hello Node.js Server!');
    console.log('end');
  });
}

const server = http.createServer(requestHandler)

server.listen(port, (err) => {
  if (err) {
    return console.log('something bad happened', err)
  }
  console.log(`server is listening on ${port}`)
})
```

**Comment by shamasis** [comment]
@numaanashraf has pointed me out to dump HTTP raw data on TCP. Let me get back

**Comment by igorsantos07** [comment]
@shamasis glad to know at least somewhere it's hard to not follow the standards! Lol

That said, a lot of servers out there do not respect this.
I think Postman could very well interpret it better (if it's feasible) and, maybe even, show a warning like "this request shouldn't have a body, but here it goes".

It's bad because it's something, as we can see, a LOT of people stumble upon. Postman should take some extra care in those cases.

**Comment by shamasis** [comment]
@igorsantos07 - you are right on target. we should do this. After all, Postman is a debugging tool. @kamalaknn and I are looking into ways to tweak the underlying client to at least return the body.

**Comment by kaiserkiwi** [comment]
Any news on this? This seems to be still a problem.

**Comment by jmauerhan** [comment]
@shamasis if you still need help reproducing this, it's very easy in PHP, I could get you a docker container that runs the built in php server and returns this invalid response?

**Comment by shamasis** [comment]
I reproduced it. The issue seems to be related to content-length and as such was making things more confusing.

Any response with content-length greater than actual response content buffer size is stalling postman-runtime. This is irrespective of request method. This also sees to be a limitation of underlying NodeJS http body parsing. It actually may need a lot more / low-level work than initially expected.

Just to confirm the investigations @codenirvana did.

```
No Content-Length: Works
Content < Content-Length: Works, if socket.end
Content > Content-Length: Parse Error
```

**Comment by ghost** [comment]
I found a number of related issues:

- https://github.com/nodejs/node-v0.x-archive/issues/7019
- https://github.com/request/request/issues/1713
- https://stackoverflow.com/questions/34769824/what-does-this-error-mean-hpe-invalid-constant/42346053
- https://github.com/nodejs/node/issues/21000
- https://github.com/nodejs/node-v0.x-archive/issues/4863

And so on. They seem to be related to @shamasis finding. At work we couldn't process any response from Symphony, as _node_ choked on the following:

```php
$response = new JsonResponse();
$response->setStatusCode(JsonResponse::HTTP_NO_CONTENT);
return $response
```

Changing that to:

```php
$response = new Response();
$response->setStatusCode(Response::HTTP_NO_CONTENT);
return $response
```

makes the problem go away. `JsonResponse` always came back with an actual content length of 2, regardless of the `Content-Length` header being present or not. _Node_ would never parse the request. Now it's a proper empty response so it works.

Does this help?

**Comment by HeroicOvenmitt** [comment]
I had a silly issue causing this same problem for a little while. For me I was returning a 204 with 'Success' set to false. -_-

**Comment by p00j4** [comment]
I too ran into this and after hours of hitting the walls, here is what now hopefully can save someone's time:

**Background** We were using python app and one day, we added a reverse proxy in our nginx conf  proxy_pass and then started noticing the same calls started responding slower. Initially we were blindly checking the conf and postman, curl stuff and finally figured the pattern that it's only happening for 204 response codes. Since the same call if was hit using cURL, we were immediately getting the response hence we thought, it's a bug at postman level or something to do with nginx and postman together. 

### Towards finding the fix:
**1. On requesting, without nginx:** ran cURL with `-v` this time, 
found that the server sends "assume close after body" also notice the content length.
<img width="491" alt="screen shot 2019-02-04 at 8 20 24 pm" src="https://user-images.githubusercontent.com/6470509/52216987-8b268c00-28bd-11e9-9584-61d46e2c5f2e.png">

**2. On requesting using nginx's reverse proxy:** 
the reponse disn't have any instruction to close and observe th last line "connection left intact", also notice the content length.
<img width="497" alt="screen shot 2019-02-04 at 8 33 34 pm" src="https://user-images.githubusercontent.com/6470509/52216988-8bbf2280-28bd-11e9-847f-757a46e01379.png">

This difference was enough to confirm it's nginx config which needs a fix and found that ```keepalive_timeout 0;```  came as the life savior hack, i.e. after reloading nginx, now postman knows that connection is closed, there is no need to wait more for 204 case.
And more reading revealed that the **default** keepalive_timeout is 60 seconds hence postman was receiving the signal to close connection and return after a minute  (yes I had calculated the time it was taking to return from postman to report the issue to team postman, because the cURL copied from the same postman was returning immidately  🤦‍♀️) 

For reference, Nginx conf looks like this:
```
location /my_route/ {
         proxy_pass  <my_domain>:<my_port>/;
         proxy_http_version  1.1;
         keepalive_timeout 0;
   }
```
I'm still new to nginx and proxies, learned new lessons of API redirection rules against refusing to change from 204 to 200 without understanding the actual reason  😄

**Comment by eysikal** [comment]
I ran into this same issue today and it cost me a few hours thinking it was my code that was the issue. 

I encountered the issue when trying to set up Lavavel Sanctum and hitting the /sanctum/csrf-cookie route, which returns a 204 with no content and 2 cookies. 

macOS 10.15.4 running Laravel Valet.

**Comment by Niush** [comment]
@eysikal Did you find any suitable solution for this? Postman seems to just throw `Error: Parse Error: Expected HTTP/` and also ignore the cookie so user is not authenticated.

**Comment by eysikal** [comment]
@Niush No, I never did. I ended up using Chrome extension tool to test my API and that’s when I discovered that it was Postman that had the issue.

**Comment by mccannt** [comment]
@eysikal We have made some recent changes to resolve this.

What version of our application are you using currently? 
Do you see this issue with any other endpoint that returns a 204?

**Comment by Niush** [comment]
@mccannt After latest update (Windows Version 7.31.1) it is working from Build View just fine.
But, still not working in **Pre-requests Script**.
While using `sendRequest` as below:

```js
pm.sendRequest({
    url: pm.environment.get('base_web_url')+'/sanctum/csrf-cookie',
    method: 'GET',
}, function (error, response, {cookies}) {
    // THROWS ERROR: TypeError: Cannot destructure property 'cookies' of 'undefined' as it is undefined.
})
```
And console.log of response has **0 cookie and 0 header**. (Although, it does exist as it works from Build view)

I also tested with ``https://httpstat.us/204`` endpoint, and it works fine. So, it is might be with the way Laravel Sanctum returns the response.

**Comment by mccannt** [comment]
Thanks for the follow-up @Niush I agree that this does sound like an isolated issue with Laravel Sanctum as this appears to work as expected when hitting other valid endpoints that return a 204. 

Closing this issue for the time being. If this is still an issue against endpoints other than Laravel Sanctum, please feel free to reopen with details on how to replicate this.

**Comment by nmfzone** [comment]
@eysikal Now, you need to pass `Accept` header as `application/json` to avoid this issue in `Laravel Sanctum 2.9.0`.

```js
pm.sendRequest({
    url: `${pm.variables.get('host')}/sanctum/csrf-cookie`,
    method: 'GET',
    header: {
        'Accept': 'application/json'
    }
}, function (error, response, { cookies }) {
    if (!error) {
        pm.environment.set('xsrf-token', cookies.get('XSRF-TOKEN'))
    }
})
```

**Comment by rushirami** [comment]
@nmfzone Thanks for this comment it was really helpful.

**Comment by cortierdev** [comment]
I faced a similar issue in Laravel.

In my case, it turned out to be something adding extra bytes to the response. I could spot it with curl:
```
Excess found: excess = 4 url = / (zero-length body)
```

Since it was a new project, I decided to do a full reinstall, which resolved the problem. It was likely an unintended extra line or hidden character somewhere in the code—tricky to pinpoint, but a clean reinstall did the trick.

**Comment by kemmis** [comment]
10 years later and I'm still running into this. Apis that return 204 + body content makes postman throw "HTTP/2 Protocol Error:Stream closed with and error." And there's no workaround for those of us where we don't own the api we are calling.

**Comment by shamasis** [comment]
@kemmis - this could be a separate line of issue and not exactly this one.

Would you mind sharing more details in a new issue?

**Comment by shamasis** [comment]
Actually, wait. @parthverma1 feels this is likely same issue, but in a different flavour. @parthverma1 can you check and see if you can tweak anything here?

**Comment by kemmis** [comment]
@shamasis Here are additional details:

GET from Postman w/ HTTP version set to AUTO or HTTP/2:

- Error in postman console: Error: Stream closed with error code NGHTTP2_HTTP_1_1_REQUIRED
- No response data/headers shown at all

GET from Postman w/ HTTP version set to HTTP/1.x:

- Error in postman console: Error: Parse Error: Expected HTTP/, RTSP/ or ICE/
- No response data/header shown at all

CURL details of response after it downgrades to HTTP/1.1:
```
* Request completely sent off
< HTTP/1.1 204 No Content
< Cache-Control: no-cache,no-store
< Pragma: no-cache
< Content-Length: 253
< Content-Type: application/json; charset=utf-8
< Expires: -1
< ServerMetrics: {"BlockReads":0,"BlockWrites":0,"BlocksAllocated":0,"DBTime":0,"DatabaseCPUTime":3,"ECFNetworkTime":0,"ECFRequestCount":0,"ECFRequestTime":0,"GREF":152,"JournalEntries":0,"LockWait":0,"LocksFailed":0,"LocksGranted":0,"MCommands":2498,"MemoryDifference":0,"NetworkCacheMisses":0,"NetworkUpdates":0,"WorkflowEventBlockReads":0,"WorkflowEventDBTime":0,"WorkflowEventECFNetworkTime":0,"WorkflowEventECFRequestCount":0,"WorkflowEventGREF":152}
< Strict-Transport-Security: max-age=31536000; includeSubDomains
< SERVER: WebServer
< Date: Tue, 02 Jun 2026 14:01:49 GMT
<
* Excess found writing body: excess = 253, size = 0, maxdownload = 0, bytecount = 0
* shutting down connection #1
```

**Comment by shamasis** [comment]
Thanks @kemmis. Tracking here https://github.com/postmanlabs/postman-app-support/issues/14165
