### ISSUE TITLE
Add document tree viewer for XML

### ISSUE THREAD

**Issue by mfulton26** [a85/POSTMan-Chrome-Extension#2419]
Postman's document viewers -- Pretty, Raw, Preview -- are great but none of them provide a way of viewing decoded content for XML like web browsers -- Chrome, Edge, Firefox, etc. -- display the document tree which is different from "pretty printing".

Could a "Tree" viewer be added?

It would differ from the "Pretty" viewer in that, for XML for example, it would display decode XML character entity references. i.e. Instead of displaying `&amp;`, `&lt;`, etc. it would display `&`, `<`, etc.

I would love to be able to view and copy URLs and other content from the XML without having to manually decode the XML character entity references myself.

Thank you.

**Comment by a85** [comment]
Closing this as we haven't seen traction on this feature request. We are working on modularizing Postman to support plug-ins using which this feature can be built in the future.
