### ISSUE TITLE
form-data "Choose Files" button crashes Chrome and Postman

### ISSUE THREAD

**Issue by mmichalowicz** [a85/POSTMan-Chrome-Extension#2420]
1. Postman Version:
       4.8.0
2. App (Chrome app or Mac app):
       Chrome app
3. OS details:
       Windows 7 Enterprise (64 bit)
4. Is the Interceptor on and enabled in the app:
       Yes
5. Did you encounter this recently, or has this bug always been there:
       First time trying to use the form data feature with a file
6. Expected behaviour:
       Clicking on "Choose Files" for a form-data line entry of type "File" should pull up some kind of file chooser
7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
       Cannot find logs for application. This is a crash in the app when trying to create a request using form-data feature.
8. Screenshots (if applicable)
       None, can send if needed but it's a simple crash when clicking "Choose Files" button

Steps to reproduce the problem:
        Create a brand new request (+), switch to POST, select Body, select form-data, for the first key entry, choose type "File" from pulldown where you choose Text or File, "Choose Files" button appears, click on "Choose Files", crashes Chrome: "Google Chrome has stopped Working, Close Program"

**Comment by sdnts** [comment]
@mmichalowicz Does this happen only on the Postman Chrome app or for any Chrome app?
Also, are there any logs in the Postman app's console? (Instructions to enable it are [here](http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/))

A screenshot of the crash with the console open would also be helpful :)

**Comment by mmichalowicz** [comment]
Sorry for the delay... Since I am working at Vanguard, a financial institution, sharing log files tends to be scrutinized (as to be expected)...  With that being said there are no logs.  

However I did make progress asking for help from within Vanguard. Since this is a Chrome extension, it is really just a hyped up browser instance and is therefore treated as such. Vanguard security policies disallow web browsers from accessing the filesystem. Sooo, it's **not supposed to work** since it doesn't have Windows permissions to do so.  So this is not really a bug, rather an enhancement request to check for security permissions and give a meaningful error message to the user instead of crashing both PostMan and the Chrome instance that the extension was launched from.

**Comment by sdnts** [comment]
@mmichalowicz Unfortunately, there isn't a way to check this beforehand from the browser AFAIK.
You could try out our [native apps](https://getpostman.com/apps) though, which should be able to work properly.
