### ISSUE TITLE
Token in token detail should be selectable.

### ISSUE THREAD

**Issue by ejfn** [a85/POSTMan-Chrome-Extension#2421]
Version/App Information:
1. Postman Version: 4.8.0
2. App (Chrome app or Mac app): Chrome App
3. OS details: macOS and Windows
4. Is the Interceptor on and enabled in the app: Off
5. Did you encounter this recently, or has this bug always been there: Yes, recently
6. Expected behaviour: The token details should be selectable so that I can right click on the selected token and send to enviroment.
7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app): N/A
8. Screenshots (if applicable)

Steps to reproduce the problem:
1. From any request Tab, Select Authorization -> OAuth2
2. Select any existing token (get one if none)
3. In the Token details view at the right side, the token text should be selectable .

Which is not convenient, I need to select and send token to the environment, or copy/paste to somewhere else. I know I can choose "Add token to" Header or Url, but it only adds to a single request, which is useless for a batch run.

**Comment by ejfn** [comment]
And, it would be much better if you can add an "Environment" option to "Add token to".

**Comment by sdnts** [comment]
Hey @ericvan76, the OAuth2 token on the right panel is indeed selectable. Did I misunderstand your question?

![screenshot 2016-10-19 11 41 17](https://cloud.githubusercontent.com/assets/7689783/19507507/1af69dd2-95f1-11e6-9ddd-19483bddec7f.png)

**Comment by sdnts** [comment]
@ericvan76 I was able to reproduce this. It happens only the Chrome App, not the native app. Will keep you updated.

**Comment by sdnts** [comment]
@ericvan76 Can you try doing this in the latest version (4.8.3) and see if the token is selectable?

**Comment by ejfn** [comment]
Yes it's selectable now, thanks. 
But right-clicking on selected text, the context menu is different from what it was before. previously there are two options in the menu:
* Set: {current environment}
* Set: Globals

With them I can sent selected text to an environment variable via one of above options. But they're not shown any more.
