### ISSUE TITLE
[Feature request] Mark request fields as "non-dirtying"

### ISSUE THREAD

**Issue by Aidenir** [a85/POSTMan-Chrome-Extension#2422]
The problem I've been having for a while now is that I for example have a request saved for fetching an oauth access token (without the build-in helper, for many reasons), and one parameter, "code" is obviously changing everytime I request a new access-token. But since this change is irrelevant (the code will not be valid next time I open the request) I don't wan't the request to be showing as changed because I might have that one request open for several days, getting new codes all the time. When its then time to close down, I can't be sure of what in the request has actually changed.

I have no idea how this would look, but maybe a checkbox beside input fields (headers, query params, body etc) to track changes, that ofc is checked by default.

**Comment by vegetableman** [comment]
You could set the `code` as an environment variable. That way, it won't mark the request as dirty. 
Also, you could create another request in the collection that would just fetch the code and set it in the environment and then you could run your request to fetch the access token.
Checkout this post: http://blog.getpostman.com/2014/01/27/extracting-data-from-responses-and-chaining-requests/

**Comment by sdnts** [comment]
@Aidenir Closing as environment variables should solve your problem :)
Let me know if they don't.
