### ISSUE TITLE
Right click to set environment variable not working in 4.8.0

### ISSUE THREAD

**Issue by stevenmcdermott8** [a85/POSTMan-Chrome-Extension#2423]
Hi,
I'm using Postman 4.8.0 and I can not set environment variables (or global variables) from the right-click contextual menu. I do not even get the option to set a variable like it did before.

![image](https://cloud.githubusercontent.com/assets/8916704/19523886/c037479a-95d0-11e6-899c-b6d4da658c62.png)

Working on Mac OSX yosemite, recently updated chrome from 48.x to 54.x

It should also be noted, i cannot copy, paste, etc.

**Comment by donroyco** [comment]
I also encountered this issue. Right clicking in the actual data is not working, even after a reboot or reinstall. I can still use the context menu for the top right _no environment_ dropdown.

Postman App version: 4.8
Chrome version: 54
Operating System: macOS Sierra

**Comment by vegetableman** [comment]
Thanks guys for reporting it 👍 . We are looking in to it.

**Comment by donroyco** [comment]
A workaround until the fix has arrived is that you can go to the _Raw_ or _Preview_ input and then do a right click to access the context menu. That works for me.

<img width="211" alt="Raw input" src="https://cloud.githubusercontent.com/assets/1763537/19723644/80263056-9b7c-11e6-81f1-ca6aa1fb75ec.png">

**Comment by jbouzekri** [comment]
@donroyco : nice work around.

Just to everybody knows that it happens on Ubuntu 16.10 too :
4.8.0
linux / x86-64
Chrome 54.0.2840.71

**Comment by chrisjmccrum** [comment]
happening to me as well on v4.8.0

Mac OSX 10.11.6
Chrome 54.0.2840.71

**Comment by tagyoureit** [comment]
Still happening on 4.8.1.  Would love to get this fixed.  It is a key part of my workflow.

**Comment by sdnts** [comment]
@tagyoureit We'll push out a fix for this with the next release :)

**Comment by eylonmalin** [comment]
@madebysid When would be that next release with fix to this bug ?
This feature is one of the most important features of postman.

**Comment by sdnts** [comment]
We're planning on releasing a fix for this first thing next week.

**Comment by vegetableman** [comment]
The issue has been fixed in the recent release `4.8.3`. Closing this issue. Feel free to reopen if the bug still exists ^_^.

**Comment by stevenmcdermott8** [comment]
Confirmed working for me, thanks for the fix guys!

**Comment by eylonmalin** [comment]
Thanks a lot for the fix.

**Comment by Workom2016** [comment]
My Postman version is 4.8.3 but still cannot set environment variable from response header.
Please advise.

**Comment by tagyoureit** [comment]
It is working in the 'Body' section of the results again in 4.8.3.  I never tried it in previous versions from the 'Headers' tab.

**Comment by vegetableman** [comment]
@Workom2016 Due to a breaking change in the recent versions of chrome, selection on non-editable areas could no longer be supported on the chrome app. This fix allows setting environment variables only from an editable section like response body, test scripts, etc., which solves most of the use-cases reported in this issue. 

I would recommend switching to the native app which supports your use-case.

**Comment by vegetableman** [comment]
@Workom2016 The issue will be fixed in the upcoming version. Thanks for pointing it out 👍 .
