### ISSUE TITLE
Randomly test failures when running with Postman Collection Runner or Newman

### ISSUE THREAD

**Issue by Pablodotnet** [a85/POSTMan-Chrome-Extension#2425]
1. Postman Version: 4.8
2. App (Chrome app or Mac app): Mac app & Chrome app
3. OS details: El Capitan (Mac app) & Ubuntu (Chrome App)
4. Is the Interceptor on and enabled in the app: No
5. Did you encounter this recently, or has this bug always been there: Always been there
6. Expected behaviour: When I run a request in Postman, the programmed tests passes, but when running the same request with Postman Collection Runner or with Newman, some of the tests randomly fails, even if it's still passing in Postman.

Issue Explanation: 
I have my collection with some post requests and get requests with some tests, when running them with Send button individually they all worked, BUT when I get to run all the collection with Collection Runner (Opening Menu > Run > Collection Runner > Start Test) some of the tests that wasn't failing runned individually failed when running them in Collection Runner. I say that they randomly fail because if a run them again, tests that failed in previous run doesn't fail in the new one, but some that wasn't failing, fails in the new run. Running the collection with Newman have this behavior too, sometimes some tests passes and sometimes no, it's random.

**Comment by vegetableman** [comment]
@Pablodotnet It's not clear as to what exact issue you are facing. Considering, you are writing tests around requests and responses. Could you open up devtools in case of the chrome app (https://www.getpostman.com/docs/errors) and verify the request and response for the calls with the failing tests.

**Comment by andreassiegel** [comment]
@Pablodotnet Could you elaborate a bit in which way your tests are failing in the collection runner, or what kind of tests are failing?

For instance, we've experienced issues with random _500 Internal Server Error_ responses we can't explain, so that we are not sure if Postman or the API is the actual problem.

I'd really appreciate your feedback. Would be good to know we're not the only ones with randomly failing tests.

**Comment by sdnts** [comment]
@Pablodotnet Is this still happening to you?

**Comment by Pablodotnet** [comment]
Hi, sorry for taking some time to answer, I'm not having this issue anymore because I changed my SO from Linux to MacOS, I read that this issue isn't happening with Native Postman App + Newman, and it's true, all my test pass in Postman, Collection Runner and Newman.

The issue I was getting was like this:
I have my collection with some post requests and get requests with some tests, when running them with Send button individually they all worked, BUT when I get to run all the collection with Collection Runner (Opening Menu > Run > Collection Runner > Start Test) some of the tests that wasn't failing runned individually failed when running them in Collection Runner. I say that they randomly fail because if a run them again, tests that failed in previous run doesn't fail in the new one, but some that wasn't failing, fails in the new run. Running the collection with Newman have this behavior too, sometimes some tests passes and sometimes no, it's random.

It's kinda weird I know, I preferred to change to MacOS so I stop dealing with this problem.

**Comment by amritajainBeachbody** [comment]
Yes, we are experiencing similar issue.
For example: A test that asserts "firstName" in response fails via newman and works fine when run from app individually.

- node_modules/.bin/newman run tests/postman/collections/<collectionName>.postman_collection.json --folder <folderName> -e tests/postman/envs/<env>.postman_environment.json

**Comment by Pablodotnet** [comment]
Which version of Postman and Newman are you using? and which OS?

**Comment by amritajainBeachbody** [comment]
Sure,
newman version = 3.9.3
postman version = 6.0.10
OSX El Capitan

Upon further debugging found that:
The tests are failing because newman is not able to set Postman variables.

postman.setEnvironmentVariable("accessToken", jsonData.accessToken); --> works fine on app
postman.setEnvironmentVariable("accessToken", jsonData.accessToken); --> doesn't work in newman

We generate accessToken in first call and set the EnvironmentVariable and then use that value for next call.

**Comment by Pablodotnet** [comment]
Uuuhm I'm doing that in all my tests and aren't failing, this is how my tests looks like when doing that:

````
var jsonData = JSON.parse(responseBody);
if(jsonData.data !== undefined) {
    postman.setEnvironmentVariable("dataToken", jsonData.data.token);
    tests["Response returns id"]            = jsonData.data.id;
}
````

And in the next call I use it on header like this on Headers tab:
````
Key:  Authorization
Value: Bearer {{dataToken}}
````

Or if you are going to use it on the route it needs to be like this:
````
{{ApiUrl}}/users/{{userId}}
````

If you are going to use it on request's body in form-data view you should use it like this:
````
Key: name  Value: {{firstNutriologoName}}
````

If you are going to use it on body on raw json you should use it between "" like this:
````
{
 "name": "{{name}}"
}
````

That's different approaches of what I have and aren't failing.

**Comment by mattd3v** [comment]
For anyone else experiencing this, which I just did, remember to save your requests before executing them in the runner. If they work individually and not in the runner, it could be because they haven't been saved yet. A simple mistake, which can result in this particular issue.

**Comment by IDScanBrianMulhall** [comment]
this happens for me too. I run them separately and they work and together some in the collection of tests will fail.

OS Name	Microsoft Windows 10 Pro
Version	10.0.19041 Build 19041
Postman v8.3.1

I am making POST requests to an API and getting back 400 responses in the collection tests runner but 200 responses separately

**Comment by bharathirajaramasamy** [comment]
This happens to me too. Not sure how to fix this issue
OS - Mac os
Postman version - 10.0.39

**Comment by shubhbhargav** [comment]
@bharathirajaramasamy Can you please share a few more details around the issue:

- What is the error you are seeing here?
- Is the error consistently reproducible?
- What are the steps to reproduce the error?
