### ISSUE TITLE
Feature request: add vertical split mode

### ISSUE THREAD

**Issue by Nopik** [a85/POSTMan-Chrome-Extension#2426]
Currently the request/response panes are stacked vertically, with horizontal splitter. So, if I'm editing body of json request and want to scroll through response, each of those panes has limited vertical amount of screen space. And it also creates some weird and very annoying scrolling behaviour.

Moreover, on big-resolution screens (lets say FullHD+), a vast amount of space is unused, since the screen is very wide, so Postman just display white area there.

Being able to send request on the left, with response on the right will provide much more effective use of screen space + better scrolling (e.g. GraphiQL does have similar approach). If that would be coupled with easy layout switch, it would be perfect.

**Comment by vegetableman** [comment]
@Nopik The feature is being worked on ^_^.  Here's the issue where you can track it #2345. Closing this as a duplicate.

**Comment by Nopik** [comment]
Any rough estimates when it could be available? like this month, this year, this decade? :)

**Comment by vegetableman** [comment]
@Nopik we want to get it right but, yes, in a month or sooner.

**Comment by a85** [comment]
Available in 4.9.3!
