### ISSUE TITLE
request.data shows as array in Mac native app

### ISSUE THREAD

**Issue by fostec82** [a85/POSTMan-Chrome-Extension#2428]
1. Postman Version: 4.8
2. App (Chrome app or Mac app): Mac and Chrome
3. OS details: OS X 10.11.6
4. Is the Interceptor on and enabled in the app: No
5. Did you encounter this recently, or has this bug always been there: Recently
6. Expected behaviour: request.data should be object
7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app): Included
8. Screenshots (if applicable)

Do a simple HTTP Post to any URL and include the following as the pre-request script:

console.log(request.data);

Set the Body to 'x-www-form-urlencoded' with simple key/value
key: foo
value: bar

On the Mac app console you get an array with an object.  However on Chrome App you get the object as expected.

This causes issues in larger scripts use a 'for(var param in request.data)' operation.

![chromeconsole](https://cloud.githubusercontent.com/assets/21953364/19573959/4b0cbfe8-96d6-11e6-86f0-1d45172059c2.png)

![macconsole](https://cloud.githubusercontent.com/assets/21953364/19573897/0c40eeec-96d6-11e6-9269-f2eb09f97e32.png)

![keyvalue](https://cloud.githubusercontent.com/assets/21953364/19573872/f1849e14-96d5-11e6-82a7-26a25d046d15.png)

**Comment by sdnts** [comment]
Hey @chrifost, the native app's behaviour is what you should follow. The native app uses Postman Runtime ([here's](http://blog.getpostman.com/2016/06/14/introducing-postman-runtime-more-power-better-control/) why). By keeping the `request.data` as a key-value store, users would face problems when it came to multiple parameters with the same name.
Postman Runtime will make its way to the chrome app soon, so your tests could break then. I'd suggest updating them.
