### ISSUE TITLE
Would be great if the "tests['whatever'] = true;" automatically created console.log and console.error statements

### ISSUE THREAD

**Issue by sjdirect** [a85/POSTMan-Chrome-Extension#2429]
tests['some message you want to see '] = true; is used to display debug messages.

I know that this is the "correct" way to do this in postman but it really seems like a hack. The problem is that if you run several tests in the collection runner those statements are not shown in the order that they happened. This makes me have to do both console.log + console.error + test[''] to really understand what is happening. PostMan should just pipe the tests[] data directly to console.log and console.eror messages based on if the test passes or fails

**Comment by sdnts** [comment]
@sjdirect You can also do a `console.log` within the test / pre-request scripts and that output will be piped to the Chrome console as well as the Postman Console (Cmd/Ctrl + Alt + C)

**Comment by sjdirect** [comment]
I understand that but then I have to do this for every test. Doesn't it seem a little verbose?

```
tests[message] = success;
if(success){
    console.log(message);
}
else{
    console.error(message);
}
```

**Comment by sdnts** [comment]
@sjdirect It does indeed. I'm trying to understand why you'd need to do a `console.log` in the first place.
Is this something you do on a regular basis, or just temporarily (for debugging perhaps)?

**Comment by sjdirect** [comment]
When you create reusable calls/logic and use postman.setNextRequest("whatever") the ordering of collection runner output is confusing. The console.log statements are in the order they are executed. So yes it's more for debugging purposes. And it seems like such an easy thing to add.

**Comment by sdnts** [comment]
@sjdirect That's a valid use case.
We are working on a redesign of the runner that should address your problem. It is currently on our Canary channel. You can download the Canary release [here](https://dl.pstmn.io/download/channel/canary/osx_64).
I'd recommend you to join our Slack community [here](https://www.getpostman.com/slack-invite) so you can provide feedback before the runner moves to our stable builds :)

We'll also consider adding logs from tests. :)

**Comment by sjdirect** [comment]
Thanks for listening. Looking forward to future releases.

**Comment by sdnts** [comment]
@sjdirect The new Runner is out with our latest release (4.9) on our native apps and you should now be able to see the complete response along with failed tests. Can you update and see if that solves your use case? :)

Feel free to reopen if not.
