### ISSUE TITLE
response example tab

### ISSUE THREAD

**Issue by ghost** [a85/POSTMan-Chrome-Extension#2430]
hello,
is there any chance to get some "response example" tab next to authorization, body, etc. tabs? where i can define response example in formatted json? just for information what shoud i get after request sent?

**Comment by vivganes** [comment]
@Mkax  Can you please explain how you would use the response example?  Do you expect Postman to throw error when the server returns some other response?

**Comment by ghost** [comment]
@vivganes Just to view how the response should looks like if i send the request. 

for example: on Response tab i choose to define responses for 200, 404, 400
- for 200 i paste example response in json format (just example data)
- for 404 i paste different response and for 400 as well

then someone else can simply view example responses on response tab without sending any requests or if resources are not implemented yet.

**Comment by sdnts** [comment]
@Mkax You can do this partially as of now. You can save responses for requests that are part of a collection, using the `Save Response` button on the top right of the response section.

Example responses are not in our immediate roadmap as of now, though.

**Comment by bhawna2109** [comment]
hey guys, this is now supported in the new Examples feature! :tada:

Get the story - http://blog.getpostman.com/2017/05/17/mock-responses-in-postman-by-using-examples/
