### ISSUE TITLE
Windows App not working with SSL certificate

### ISSUE THREAD

**Issue by navff** [a85/POSTMan-Chrome-Extension#2432]
1. Postman Version: **4.8.0**
2. App (Chrome app or Mac app): **Windows App**
3. OS details: **Windows 10, v1607**
4. Is the Interceptor on and enabled in the app: **not enabled**
5. Did you encounter this recently, or has this bug always been there: **all times when I try get request**

Steps:
1. Trying to run GET request: https://wpay.uniteller.ru/results/?Login=2721&Password=123
2. Seen the error.

I imported certificate to root collection (from chrome, IE, end from windows wizard), but It is still not working. When I working with other servers they are working normally.

![2016-10-26 10_20_44-new issue postmanlabs_postman-app-support yandex](https://cloud.githubusercontent.com/assets/869492/19716713/e78fcbba-9b65-11e6-9d62-482cc9be5846.png)

**Comment by sdnts** [comment]
Hey @navff! Are you trying to send a certificate along with the request to your URL? If so, can you try out our native Windows App (which has support for this)? From your screenshot, I see that you are using the Chrome App, not the native one. You can download it [here](http://getpostman.com/apps).

You can then head over to Settings > Certificates and add your certificate there. It'll then be sent with your request as long as the host is the same

**Comment by abhijitkane** [comment]
@navff Feel free to re-open if you still face this issue.
