### ISSUE TITLE
Postman Sends all the cookies stored in Chrome for that domain

### ISSUE THREAD

**Issue by jitbit** [a85/POSTMan-Chrome-Extension#2435]
1. Postman Version: 4.8.0
2. App (Chrome app or Mac app): Chrome app
3. OS details: Windows 10
4. Is the Interceptor on and enabled in the app: yes
5. Did you encounter this recently, or has this bug always been there: always
6. Expected behaviour: no cookies from Chrome should be sent to domain
7. Console logs: `window.localStorage is not available in packaged apps. Use chrome.storage.local instead.
   beforeunload is not available in packaged apps.
   window.localStorage is not available in packaged apps. Use chrome.storage.local instead.
   unload is not available in packaged apps.`

**Comment by sdnts** [comment]
@jitbit That is the intended behaviour. When you have the interceptor installed and activated from the Chrome App, your request actually goes through Chrome, so all you cookies related to that domain are also sent. In fact, this is the primary use case for the Interceptor. Feel free to reopen if I misunderstood :)
