### ISSUE TITLE
Is it possible to import variables from csv or json file in Pre-requests script?

### ISSUE THREAD

**Issue by mahekmerchant** [a85/POSTMan-Chrome-Extension#2436]
e.g
var j=from CSV or json
postman.setGlobalVariable("id", "j");

**Comment by sdnts** [comment]
@mahekmerchant You can do this in the Collection Runner. [This](http://blog.getpostman.com/2014/10/28/using-csv-and-json-files-in-the-postman-collection-runner/) blog post should help you out :)

**Comment by mahekmerchant** [comment]
Actually my purpose is to import variables from csv ,set as an enviroment variable in pre-request script. I want to run this collection file using newman without passing environment file.So is it possible?Is there any library to import external csv file or json file?

**Comment by sdnts** [comment]
@mahekmerchant You can supply in a CSV file in Newman too. Check out [Newman Docs](https://github.com/postmanlabs/newman#command-line-options), specifically the `-d` option. You can then use these variables from the CSV directly in your collection.
Newman's Issue tracker is [here](https://github.com/postmanlabs/newman/issues)
