### ISSUE TITLE
Collecion Runner fails to read a property from JSON array  

### ISSUE THREAD

**Issue by camminati** [a85/POSTMan-Chrome-Extension#2438]
1. Postman Version: 4.8.1
2. App (Chrome app or Mac app): win32 10.0.14393 / x64
3. OS details: Windows 10 Version 1603
4. Is the Interceptor on and enabled in the app: no
5. Did you encounter this recently, or has this bug always been there: not sure.. maybe recently
## Expected behaviour:

I'm am trying to set an evinronment variable reading the value from the json body and use it in the url for the next call.

The body:

``` json
{
  "responseStatus": "OK",
  "responseDetails": [],
  "responseData": {
    "messagesInfo": [
      {
        "senderMessageId": 14094,
        "priority": 4,
        "url": "clients/451/messages/14094"
      }
    ]
  }
}
```

and in the test script I read it like this:

``` js
var jsonData = JSON.parse(responseBody);
tests["responseStatus OK"] = jsonData.responseStatus === "OK";
var messagesInfo = jsonData.responseData.messagesInfo;
tests["body = " + JSON.stringify(jsonData, null, `\t`)] = true;
tests["Message ID = " +messagesInfo[0].url ] = true;
postman.setEnvironmentVariable("msgId-url", messagesInfo[0].url);
```

What actually works if I run the test from the APP:

![image](https://cloud.githubusercontent.com/assets/5380553/19771532/77f3a4bc-9c63-11e6-963e-e810d9a656a6.png)

But if I use the collection runner, I fails (mostly... like 99% of the time) with:

![image](https://cloud.githubusercontent.com/assets/5380553/19771583/a49b52c6-9c63-11e6-9307-19be3dc68a9b.png)

Once in a while it works, but I can not reproduce the exact parameters.

It runs as 2nd call in a Test-Suite. The first call gets the token needed for Auth.
I use this heavily in other cases, but here is the only instance where I take the values from an array, maybe this has something to do with it.

**Comment by sdnts** [comment]
Hey @camminati, I made a little server that returns me the body you've defined, but I was unable to reproduce this.
Could you open up the Postman Console (Cmd/Ctrl + Alt + C) and start the collection run? That way, you should be able to see the actual response your server sends back. Can you make sure the response is as expected in both cases?

**Comment by camminati** [comment]
@madebysid thanks for the answer. With the console I could check the response and the time stamps and indeed, the answer was empty every time under 100 ms. I could follow it back to a problem in my server-app, the message is sent asynchronously and is not there yet.

Sorry for wasting your time. I'll close the issue. I owe you one.
