### ISSUE TITLE
PostMan crashes on startup (when connecting to postman servers)

### ISSUE THREAD

**Issue by HenrikHL** [a85/POSTMan-Chrome-Extension#2439]
1. Postman Version: 4.8.0
2. App (Chrome app or Mac app): Chrome
3. OS details: Win 10 64bit
4. Is the Interceptor on and enabled in the app:
5. Did you encounter this recently, or has this bug always been there: From today
6. Expected behaviour: Postman starting normally
7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
8. Screenshots (if applicable)

Today when starting postman it crashes upon start. It starts up - but after trying to connect it crashes. It is 1-2 weeks ago since last time I used postman - there were no problems at that time...
I have restarted my machine

**Comment by sdnts** [comment]
@HenrikHL If you have all your collections synced, could you try a reinstall of the app? Sync would make sure all your collections are intact.

**Comment by HenrikHL** [comment]
Thank you - it worked by uninstalling POSTMan and then reinstalling it.

2016-10-28 10:31 GMT+02:00 Siddhant Sinha notifications@github.com:
