### ISSUE TITLE
Couldn't transmit generated id from POST methodto the next GET method

### ISSUE THREAD

**Issue by zhangman1212** [a85/POSTMan-Chrome-Extension#2441]
Hi,

I'm not sure if this is a bug vs. something I am doing wrong.

Description:
I have POST/GET/UPDATE/DELETE methods for one resource file, I want to create a resource using POST method then get the resource by id, the 'id' is generated by POST method, it's unique, so I hope I could transmit the generated 'id' from POST method to the GET methods, I create a global variable named 'id', and write a snippets in the POST method's Test field.
1. Create a global variable: id
2. Created a POST method with snippets in the Test field:

```
tests["Body contains id"] = responseBody.has("id");
var data = JSON.parse(responseBody);
if (data.id) {
  tests["post_id found"] = true;
  postman.setGlobalVariable("id", data.id);
}
else {
  tests["post_id not found"] = false;
}
3. Send the POST method and get Response body :
```

{
  "data": {
    **"id": 910399922765895,**
    "type": "staffSubstitution",
    "accountId": 8800387990610,
    "calendarId": 884011643700923,
    "contactId": 466197263641902,
    "createdDate": "2016-10-28T22:11:42Z",
    "createdId": 8800387990489,
    "createdName": "Mandy Zhang",
    "lastModifiedDate": "2016-10-28T22:11:42Z",
    "lastModifiedId": 8800387990489,
    "lastModifiedName": "Mandy Zhang",
    "organizationId": 888409690211048,
    "recurrence": {
      "type": "ical",
      "datesApplicable": {
        "from": "2016-10-12",
        "to": "2016-10-12"
      },
      "event": {
        "end": "2016-10-13T00:00:00",
        "start": "2016-10-12T00:00:00"
      }
    },
    "resourceBundleId": 888409690211244,
    "status": "A",
    "timeZoneString": "Asia/Shanghai"
  }
}

```
4. Check the global variable
Actual result: Global id's value is "undefined"


Version/App Information:
 1. Postman Version: 4.8.1
 2. App (Chrome app or Mac app): Chrome 52.0.2743.116
 3. OS details: win / x86-32 
 4. Is the Interceptor on and enabled in the app: off
 5. Did you encounter this recently, or has this bug always been there: I met this bug always here
 6. Expected behaviour: post method generated an ID, I hope there is a way could transmit the ID to the next method, such as GET/DELETE method

Thanks,
```

**Comment by sdnts** [comment]
@zhangman1212 I noticed an error in your test script. The path to `id` field in your case is actually `data.data.id` (Since you're storing the entire response in a variable called `data`). If you change your test script to 
`postman.setGlobalVariable("id", data.data.id);`, it should work fine.
Feel free to reopen this if it doesn't :)

**Comment by zhangman1212** [comment]
Thank you very much, it works! But I have to set response variable as another name, shouldn't dup to 'data'
