### ISSUE TITLE
Disabled headers make newman fail

### ISSUE THREAD

**Issue by jmfayard** [a85/POSTMan-Chrome-Extension#2443]
Hello, I have an error that I first reported as a newman issue here https://github.com/postmanlabs/newman/issues/729 

Given the following request...
![image](https://cloud.githubusercontent.com/assets/459464/19848323/15f4045e-9f4d-11e6-9610-dd2dd3d96f2d.png)

When postman saves that request in v2 format, it does not store the information that the header is disabled

```diff
/// collectionv2.postman_collection.json
"request": {
	"url": "http://httpbin.org/headers",
	"method": "GET",
	"header": [
		{
			"key": "X-Testing-Postman-Headers",
			"value": "true",
			"description": ""
		},
		{
			"key": "//X-Disabled-Header",
			"value": "true",
-           "disabled": "true",
			"description": ""
		}
	],

```

This makes `newman run collectionv2.postman_collection.json` fails the same way than in   https://github.com/postmanlabs/postman-app-support/issues/2227 `Collection runner fails when a header is deactivated`

**Comment by sdnts** [comment]
@jmfayard Thanks for reporting this, we'll push out a fix soon :)
What version of the app are you on?

**Comment by sdnts** [comment]
@jmfayard The `disabled` key should now be correctly exported in the latest version (4.8.3). Feel free to reopen this if you face issues.
