### ISSUE TITLE
setNextRequest works globally while running collection based on CSV file

### ISSUE THREAD

**Issue by skyboyer** [a85/POSTMan-Chrome-Extension#2444]
Env: Postman 4.8.1 Chrome Extension

I have configured workflow based on [Postman docs](https://www.getpostman.com/docs/workflows):
1. log in
2. skip the rest requests in collection if there is 500 status code returned(setNextRequest(null)) - sometimes there is data issues in DB
Everything works fine.
But when I run collection for several times on CSV file with several credentials

Expected: 
setNextRequest(null) skips requests left in collection for current data row only

Actual: 
setNextRequest(null) finish execution globally

**Comment by sdnts** [comment]
@skyboyer The request that has `setNextRequest(null)`, is it inside a folder, or is it a direct child of the collection?
In the second case, it would end the execution, this is the intended behaviour.

Also, does this happen only when a CSV is used as a data source?

Let me know if I misunderstood.

**Comment by skyboyer** [comment]
@madebysid  yes, it's direct child.

Up to my mind running collection for 8 times based on CSV with 8 different rows should be the same like running collection for 8 times over 8 single-lined CSV files. Currently it does not seem working this way. Am I wrong with that understanding?  Could you please add some details?

And is there workaround with placing some request inside the folder in collection?

As for second question("only when a CSV file is used") - it seems so but I'm not completely sure. I'll check it as soon as possible.

**Comment by sdnts** [comment]
@skyboyer I think I misunderstood. `postman.setNextRequest` will end the current _iteration_. Your understanding is correct. If you have a CSV with 8 rows, and you run the collection for 8 iterations, each iteration would get one row from the CSV. `setNextRequest`'s scope would then be the current iteration.

Can you check [this](https://documenter.getpostman.com/view/214062/gh2444/2Mtt6J) collection I made?
I used a CSV that looks like this:

```
status
200
200
200
200
500
200
200
500
200
200
```

If you run the collection with 10 iterations, you'll see that the third request runs only 8 times (It is skipped when the response code is 500), which I suppose is what you are trying to achieve. 

If I misunderstood, could you create a simple collection that demonstrates your problem? :)

**Comment by skyboyer** [comment]
On your collections it's executed as expected.
Maybe my collection(tests-part of it) contains syntax error that leads to execution is stopped.
So sorry for disturbing, I'm closing this issue.
Thank you for answering.

**Comment by sdnts** [comment]
@skyboyer No problems, feel free to reopen if you manage to reproduce this :)
