### ISSUE TITLE
Postman intercepting focus from Chrome

### ISSUE THREAD

**Issue by Heneman** [a85/POSTMan-Chrome-Extension#2445]
1. Postman Version: 4.8.1
 2. App (Chrome app or Mac app): Chrome App
 3. OS details: OSX 10.11.6 (15G1004)
 4. Is the Interceptor on and enabled in the app: Yes
 5. Did you encounter this recently, or has this bug always been there: Always been there
 6. Expected behaviour: Postman intercepts focus from Chrome when Cmd-Tabbing
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app): N/A
 8. Screenshots (if applicable)

Launch Chrome, launch Postman, switch to another app, Cmd-Tab to Chrome, have Postman brought up instead

**Comment by sdnts** [comment]
@Heneman We're looking into this, will let you know here when a fix is out

**Comment by a85** [comment]
This is a Chrome platform issue. As the platform itself has been deprecated we can't do anything about it. I recommend shifting to our native apps: www.getpostman.com/apps
