### ISSUE TITLE
Environment suddenly overwrites another

### ISSUE THREAD

**Issue by stianlagstad** [a85/POSTMan-Chrome-Extension#2446]
This issue has been driving me crazy today. Let's say I have two environments: envA and envB. I switch between these two often (every minute at times). I also have several collections that I keep switching between. Then, suddenly, all variables set in envA will be present in envB, and everything that was previously in envB is gone. Completely gone. And I don't mean the values of the variables, which change based on prerequest scripts - I mean the actual keys/variables

This might have started occuring after updating my postman app yesterday, but I'm not sure. I'm not able to reproduce the bug either. Has anyone seen anything like this? Were there any changes in the recent linux app update that could have caused this?

 1. Postman Version: v4.8.1
 2. App (Chrome app or Mac app): Linux app
 3. OS details: Ubuntu 16.10
 4. Is the Interceptor on and enabled in the app: No
 5. Did you encounter this recently, or has this bug always been there: Encountered first time today
 6. Expected behaviour: An environment should only change when I go into it and add/remove environment variables.
 7. Console logs: NA
 8. Screenshots: NA

Steps to reproduce the problem: I don't know. I try to reproduce it and everything works as normal. I go back to work, and then after using postman for a while (switching between collections and environments), suddenly one environment will be overwritten by another.

**Comment by sdnts** [comment]
@stianlagstad That's weird indeed. We haven't made changes to our environments recently either. If you do manage to reproduce this, can you update this issue? I haven't been able to.

**Comment by stianlagstad** [comment]
I'll keep trying, @madebysid. Where exactly does postman store my environments locally? If I knew that then I could monitor changes in those files, so that I know exactly when it happens.

**Comment by sdnts** [comment]
@stianlagstad We don't store the environments in files anywhere, it is all stored in the app's IndexedDB, so unfortunately, there's no way for you to track this :/

**Comment by PFarrell89** [comment]
@stianlagstad @madebysid 
I don't suppose you have tests for Environment A running in the Collection Runner whilst switching to Environment B in the normal Postman Builder screen?

This happens to me if I have tests that deliberately overwrite/delete environment variables in the Collection Runner, but when I switch Environments in the Builder screen (whilst the Collection Runner is running) it's overwriting/deleting the variables for my other Environment.

**Summary:**
- Collection Runner is running tests against Environment A (tests include storing and deleting environment variables)
- Whilst the Collection Runner is running I am switching to Environment B in the normal Builder screen and the environments are stored/deleted against Environment B instead.

**Comment by stianlagstad** [comment]
This might be what is happening to me, @PFarrell89. I do find myself starting one request in environment A, then switching and starting another request in environment B before the first request with environment A has finished (with tests). I will do some testing later.

**Comment by stianlagstad** [comment]
Alright, I've managed to reproduce it. If I change environment during the execution of a request (from envA to envB), upon completion of the request envB will be gone (it will only contain what was in envA).

I keep running into this bug because I have breakpoints in my app running locally. When I launch a request with an environment to my app locally, it will stop at my breakpoints. Then, during inspection of my code, I often go to postman and run other requests with other environments. When the first request finally completes, I'm standing in another environment in postman. That environment is then lost.

I do not have any tests that update the environment variables, but I do have a prerequest script for the first request that replaces a date variable in envA.

Does this make sense?

**Comment by sdnts** [comment]
@stianlagstad I'm assuming you are running these requests in the main Postman window, not the collection runner. I made a request to `echo.getpostman.com/delay/5`, which will essentially delay the response, giving me time to switch environments. I even have a pre-request script that sets an environment variable, like you do.
However, when the response arrives, the variable is set in the correct environment (even though I switch to a separate environment), and both environments are intact. 

Can you reliably reproduce this? If so, would it be possible for you to share a simple collection that I can replicate this with? (You can reply here, or send it over to help@getpostman.com)

@PFarrell89 I saved this request in a collection and ran it in the runner (with Persist variables checked), continuously switching environments in the main window while the run was ongoing. Both environments were intact in that case too. 

I think I'm missing something here, since you guys can replicate this, but not me. In either case, a simple collection that you are seeing this with would help greatly.

**Comment by stianlagstad** [comment]
I've been able to reliably reproduce the issue that @PFarrell89 is describing. This is the setup:
- Request1: Calls `http://reqres.in/api/users?delay=10` which returns some test data after 10 seconds. This is using `envA`, which has a variable called `testThis`. There's a test script that updates the value of `testThis` after the request is done:

```
var data = JSON.parse(responseBody);
postman.setEnvironmentVariable(
    'testThis',
    data.per_page);
```
- Request2: This is a request to `http://reqres.in/api/users?delay=2` which returns some test data after 2 seconds. This is run with `envB`, which does _not_ have a variabled called `testThis`, but has the variable called `test`. There's a test script that updates the value of `test` after the request is done:

```
var data = JSON.parse(responseBody);
postman.setEnvironmentVariable(
    'test',
    data.page);
```

I do this:
- Run request1 with `envA`.
- Immediately I go to request2 (which is in another collection, if it matters) and run it with `envB`.
- Request2 finishes first, and I can see that the `test` variable in `envB` has been set to `1`. So far so good. I'm still standing in `envB` in postman.
- Then request1 finishes, and suddenly I've lost `test` in `envB`. What I see now is the variable `testThis` and its value `3`.

So the result is that I've lost `envB` entirely. I can record this happening if it's any help. Here are the two collections anyhow:
[Collection1 with request1](https://www.getpostman.com/collections/e599fbd4fedbc6e30fa9)
[Collection2 with request2](https://www.getpostman.com/collections/9db812dd0e74702fb812)

**Comment by stianlagstad** [comment]
Have you had a chance to test this, @madebysid?

**Comment by stianlagstad** [comment]
Helllo?

**Comment by sdnts** [comment]
@stianlagstad Terribly sorry about this, I'll try to replicate this tonight and will get back to you with what I find.

**Comment by sdnts** [comment]
@stianlagstad I tested this with your collection, and it seems to work as expected. When the second (shorter) request completes, the active environment is `envB`, so variable `testThis` is set there.
When the first (longer) request completes, the active environment is still `envB`, so variable `test` is set there too. While this was happening, `envA` was intact.

We've made several improvements in recent releases, can you check if this is still happening for you?

**Comment by stianlagstad** [comment]
Sorry for my late reply. I do still experience this. I'll try to reproduce it again when I'm at the office.

**Comment by numaanashraf** [comment]
@stianlagstad Have you faced this issue again recently? We had rolled out fixes for some rare cases in the environments feature that might address this issue.

**Comment by stianlagstad** [comment]
Hey @numaanashraf, thanks for checking in. I haven't had this happen for a couple of months at least so I'd say its safe to close this :)

**Comment by mailer-insights** [comment]
I'm also having this exact problem, using the current update: Version 7.2.2 (7.2.2)
