### ISSUE TITLE
Request Font Size

### ISSUE THREAD

**Issue by Izidi** [a85/POSTMan-Chrome-Extension#2448]
1. Postman Version: 4.8.1
 2. App (Chrome app or Mac app): Windows Desktop App
 3. OS details: Windows 7 64 Bit
 4. Is the Interceptor on and enabled in the app: Yes
 5. Did you encounter this recently, or has this bug always been there: Always been there
 6. Expected behaviour: To be able to increase or decrease the font size for the request the same as the response.
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app): N/A
 8. Screenshots (if applicable)
![image](https://cloud.githubusercontent.com/assets/2879895/19906195/b8c89c60-a071-11e6-8ec0-5527e8c728d4.png)

While I am able to change the font size for the Response for my requests, I am unable to change the font size for the Request, as shown in the Screenshot. This is for the Desktop App for Windows and so Ctrl + Scroll Wheel does not change the font size.

**Comment by sdnts** [comment]
@Izidi You can use Cmd/+ to increase the font size. Cmd/- will decrease it, and Cmd/0 will reset it to the default value :)
