### ISSUE TITLE
Save settings for OAuth 2.0 access tokens in the collection

### ISSUE THREAD

**Issue by seppestas** [a85/POSTMan-Chrome-Extension#2453]
Typically all the endpoints for a collection use the same type of authentication, and are capable of using the same authentication tokens.

It would be handy to save the settings for requesting OAuth 2.0 access tokens inside of the collection instead of only remembering the last used settings globally. This would make it a lot easier to get new tokens for requests in a collection, especially when you have multiple collections that use OAuth 2.0.

**Comment by czardoz** [comment]
Closing in favor of #2058
