### ISSUE TITLE
It is the first time I use postman, but I  cna't recieve any response whatever url i send.who can tell me what can i do?

### ISSUE THREAD

**Issue by mynameisaaa** [a85/POSTMan-Chrome-Extension#2455]

**Comment by mynameisaaa** [comment]
It is the first time I use postman, but I  cna't recieve any response whatever url i send.who can tell me what can i do?
![image](https://cloud.githubusercontent.com/assets/23112538/19998723/5b727092-a2a9-11e6-8d69-19e7625c8c30.png)

**Comment by mynameisaaa** [comment]
It's postman for windows,not for mac

**Comment by mynameisaaa** [comment]
Just now i reliase it the mater of https,When iI change https to http , postman response the things I needed,But Why?

**Comment by sdnts** [comment]
@mynameisaaa The protocol shouldn't matter. Could you open up the DevTools (View > Show DevTools) and check if there are any errors there for failed requests?

**Comment by mynameisaaa** [comment]
setting>general> then off the ssl ,
