### ISSUE TITLE
Markdown bug

### ISSUE THREAD

**Issue by ghost** [a85/POSTMan-Chrome-Extension#2456]
1. Postman Version:  4.8.1
 2. App (Chrome app or Mac app):  Chrome 54.0.2840.71
 3. OS details:  macOS 10.12.1
 4. Is the Interceptor on and enabled in the app:
 5. Did you encounter this recently, or has this bug always been there:
 6. Expected behaviour:
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 8. Screenshots (if applicable)

I recently noticed that codeblock syntax does not work well after updating to Sierra.
![screen shot 2016-11-04 at 5 03 37 pm](https://cloud.githubusercontent.com/assets/6554442/19999660/07dbc588-a2b7-11e6-8553-d5f8216d66d9.png)

![screen shot 2016-11-04 at 5 03 56 pm](https://cloud.githubusercontent.com/assets/6554442/19999726/5a80c59a-a2b7-11e6-8cc6-7c23e00d9ea4.png)

is this known issue?

**Comment by shamasis** [comment]
This shouldn't be a Sierra related issue. Initial testing revealed that it could be the order of the sanitisation process we apply on the markdown and subsequent HTML. @madebysid is looking into it.

**Comment by ghost** [comment]
thank you.

**Comment by sdnts** [comment]
@HyoKim We've fixed this internally, and will be rolling out a fix in the coming releases. Will keep you updated here.

**Comment by ghost** [comment]
Awesome! 👍
Thank you.

**Comment by sdnts** [comment]
@HyoKim  Our latest release (4.9) should solve this problem. Can you try updating and confirm?

**Comment by ghost** [comment]
Sorry for late reply.
It works great. Thank you so much!
