### ISSUE TITLE
Cannot load saved responses in Postman

### ISSUE THREAD

**Issue by git-sirius** [a85/POSTMan-Chrome-Extension#2459]
1. Postman Version: 4.8.1
 2. App (Chrome app or Mac app): Windows App
 3. OS details: Windows 7 Enterprise 64bit
 4. Is the Interceptor on and enabled in the app: No
 5. Did you encounter this recently, or has this bug always been there: It was working before I upgraded to this version.
 6. Expected behaviour: If I click on a saved response, it should be loaded below the request section.
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 8. Screenshots (if applicable)
![image](https://cloud.githubusercontent.com/assets/716761/20146247/1d8ceb56-a671-11e6-8c17-a80c5bd36995.png)
![image](https://cloud.githubusercontent.com/assets/716761/20146474/09b2205a-a672-11e6-8183-f9c9ab72f5f2.png)

Steps to reproduce the problem: 

1. Click a request with Saved Responses.

2. Click the downward triangle to display list of Saved Responses

3. Click one of the Saved Responses
Error: xml.js:22 Uncaught Error Uncaught TypeError: Cannot read property 'split' of undefined file:///C:/ProgramData/xxxxxx/Postman/app-4.8.1/resources/app.asar/js/requester.js 79322 25 TypeError: Cannot read property 'split' of undefined(…)

4. Click a different request with Saved Responses
Error: xml.js:22 Uncaught Error Uncaught TypeError: Cannot read property 'remove' of undefined file:///C:/ProgramData/xxxxxx/Postman/app-4.8.1/resources/app.asar/js/common.js 17411 28 TypeError: Cannot read property 'remove' of undefined(…)

5. Click Send button
Error: xml.js:22 Uncaught Error Uncaught Error: Minified exception occurred; use the non-minified dev environment for the full error message and additional helpful warnings. file:///C:/ProgramData/xxxxxx/Postman/app-4.8.1/resources/app.asar/js/common.js 1029 6 Error: Minified exception occurred; use the non-minified dev environment for the full error message and additional helpful warnings.(…)

6. Click on other Saved Requests (with or without saved requests). 
You will notice that they all now have the same box with the same Saved Responses from the request on which you clicked on one of the saved responses, even though those requests don't have saved responses or at least not those saved responses)

7. Check the PostMan Console:
You will notice that the Request is still waiting for a reponse.

And request not ever sent.

**Comment by SamvelRaja** [comment]
@git-sirius The issue has beed fixed in our internal build. This will be out tomorrow as 4.8.2 version.

**Comment by SamvelRaja** [comment]
@git-sirius The fix has been released in our 4.8.2 version. Kindly check the same from your end.

**Comment by git-sirius** [comment]
Confirming that all the reported issues in this bug have been fixed in version 4.8.3 (I haven't seen a version 4.8.2 and this bug number, 2459, showed up in the change log for 4.8.3):
- The saved responses are loading properly
- I am able to send requests and the PostMan console no longer shows "Response Headers: Loading..."
- The saved responses box from one response no longer gets copied to all other saved requests
- No more errors are seen in the DevTools

Thank you for fixing this, team PostMan!
