### ISSUE TITLE
AWS Sig4 Issue

### ISSUE THREAD

**Issue by glidenz** [a85/POSTMan-Chrome-Extension#2460]
Hi All

Trying to access an API I created on AWS which requires AWS_IAM authorisation. I've followed what I can find on the AWS and Postman docs and I am receiving an error that by all accounts appears to be fixed already according to other issues that I have read thru.

"message": "The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method.

The one thing to note that seems to be different from other peoples examples (issue 1663) is the Authorization tab on my app which doesn't appear to have session token option. It doesn't appear on the screen like other examples I have found online.

Postman - OSX 4.8.1
Chrome - 54.0.2840.71
Content Type - application/json
Using Variables - Yes

It would appear to me that the Authorisation Header is not correct and different to what AWS is expecting as the error tells me what it was expecting further down and they are different

Anyone got some tips or clues as to why the sig is not working? I am VERY confident that the access & secret key are correct.

I'm quite new to all of this FYI
Thanks

**Comment by sdnts** [comment]
@glidenz The `Session Token` field is supported in our [native apps](http://getpostman.com/apps). Could you download the native OSX / Windows / Linux app and see if adding your session token there works for you?

**Comment by glidenz** [comment]
I thought I was using native OSX app ver 4.8.1 but I will re-check

**Comment by glidenz** [comment]
OSX 4.8.3 seems to work fine

Issue solved
