### ISSUE TITLE
Static url for linux app download?

### ISSUE THREAD

**Issue by victorhaggqvist** [a85/POSTMan-Chrome-Extension#2461]
I'm trying to find a static url for the linux version, but fail to find any thing but the one for latest version (https://dl.pstmn.io/download/latest/linux?arch=64).

It would be great if there was something available similar to the osx one ie. https://s3.amazonaws.com/postman-electron-builds/mac/Postman-osx-4.8.3.zip.

**Comment by jeffska** [comment]
To elaborate, package managers that download the app and then perform integrity checks (like MD5 and checksum) are expecting to be able to download, verify, and install a specific version.  Without a version-specific URL, that becomes a problem.

**Comment by abhijitkane** [comment]
@jeffska @victorhaggqvist You can try use `https://dl.pstmn.io/download/version/:version/:platform`, where platform is one of: `win32`, `win64`, `osx`, `linux32`, or `linux64`.

The fixed URL for v4.2.9 of the 64-bit linux app is `https://dl.pstmn.io/download/version/4.2.9/linux64`.

**Comment by abhijitkane** [comment]
@jeffska @victorhaggqvist You can use https://dl.pstmn.io/download/version/:version/:platform, where platform is one of: win32, win64, osx, linux32, or linux64.

The fixed URL for v4.9.3 of the 64-bit linux app is https://dl.pstmn.io/download/version/4.9.3/linux64
