### ISSUE TITLE
Postman issue copying REST data

### ISSUE THREAD

**Issue by phoffer7874** [a85/POSTMan-Chrome-Extension#2462]
In the new version of Postman the format when we copy the JSON data from the body is not in the same format as is was (Readable), now it is in pure JSON.

Is there a way to get the readable JSON format?

**Comment by vegetableman** [comment]
@phoffer7874 Could you elaborate your issue with screenshots?. I am able to copy and retain the format of JSON from postman, when pasting it to an editor.

**Comment by phoffer7874** [comment]
Anand,

Thank you for the quick response.

Normally when I copy data from Postman in the pretty mode:

[image: Imagem inline 1]

And pasted it into Notepad it was formatted as pretty now it is formatted
as Raw:

[image: Imagem inline 2]

This functionality got lost in the last update. (Yesterday)

Please inform why this was taken away, because now it is very difficult to
analyse data in Excel.

Regards,

Petrus Hoffer

2016-11-11 6:50 GMT-02:00 Vignesh Anand notifications@github.com:

**Comment by vegetableman** [comment]
@phoffer7874 Are you using the chrome or the native app?.

**Comment by vegetableman** [comment]
@phoffer7874 Also, To confirm, were you coping directly from the app or by clicking on `Copy to Clipboard`button.

**Comment by phoffer7874** [comment]
Anand,

I tested using both the Chrome verion and the native App. I am clicking on
the copy button, because I work with big files.

Thanks in advance, and have a good weekend.

Peter

2016-11-11 11:43 GMT-02:00 Vignesh Anand notifications@github.com:

**Comment by vegetableman** [comment]
@phoffer7874 Thanks for confirming ^_^. The issue has been identified and will be fixed in the next release. 

Good weekend to you as well  ^_^.

**Comment by phoffer7874** [comment]
Anand,

When will the next release enter in production?

2016-11-11 23:51 GMT-02:00 Vignesh Anand notifications@github.com:

**Comment by vegetableman** [comment]
@phoffer7874 In the coming week. Stay tuned for updates and thank you for posting this issue 👍 .

**Comment by phoffer7874** [comment]
Anand,

Thank you very much, resolving this issue is very important for me.

Have a good week,

Peter

2016-11-12 15:42 GMT-02:00 Vignesh Anand notifications@github.com:

**Comment by phoffer7874** [comment]
Anand,

The change is still not in production, what will be the date for this
update?

Thanks in advance,

Peter

2016-11-12 20:17 GMT-02:00 Petrus Hoffer <petrus.hoffer@gmail.com>:

**Comment by vegetableman** [comment]
@phoffer7874 Sorry for the delay. It's fixed in the latest version `4.9.2`. Closing this, feel free to reopen if the issue still exists.

**Comment by pecet66** [comment]
Newest version here, still the same issue, on Windows Postman application and Chrome plugin.

**Comment by ramsrib** [comment]
Upgraded to latest version of standalone postman and started facing this issue. It was not happening in the previous version.

Details:
Postman for Chrome
Version 5.0.1
OS X / x86-64
Chrome 59.0.3071.109

**Comment by nddipiazza** [comment]
:+1: open this... it's broken as hell

**Comment by Voltir** [comment]
Copy paste on linux is broken :/ (native app)

**Comment by phoffer7874** [comment]
Vignesh,

Copy paste in the Google Chrome Application is working correctly.

Thanks,

Peter

2017-11-03 15:24 GMT-02:00 Nick Childers <notifications@github.com>:
