### ISSUE TITLE
Duplicate Postman Test to Another Collection

### ISSUE THREAD

**Issue by rollinginsanity** [a85/POSTMan-Chrome-Extension#2463]
It was suggested on Twitter that I come over here to make this suggestion.

When working with items on collections I tend to create one massive collection with all the endpoints, and then a second collection that I then tease out the actual logical functional tests for APIs.

It would be great if I if one could Duplicate a particular test to another collection, rather than a copy being made in the current collection.

Cheers! It's 4.30 on a Friday when I'm writing this, so I'm going to grab a beer.

**Comment by vegetableman** [comment]
@rollinginsanity Let's say, you have two collections `C1` and `C2`. `C2` is the duplicate collection with tests. I am guessing you want to replace a request `R1` in collection `C1` with `R1` (with tests) from `C2`. Is that right?

**Comment by rollinginsanity** [comment]
I was thinking more that I have C1 and C2, with request R1 only in C1.
Rather than copying it and ending up with "R1 copy" in C1, being able to
"copy to" C2, co that R1 is in both.

However the case you mentioned is also good, I ran in to that where I have
2 sets of requests (subfolders in a collection that I use the runner with).
I realised I'd made a mistake that affects them both and had to fix both
requests in each subfolder seperatly.

For some context I'm in the process of driving some api security testing
with postman (hence the variations of sets of requests in the runner) and
its actually working pretty well.

**Comment by vkaegis** [comment]
Hey guys, you can now fork collections and merge changes back between them (as of v6.7.1). 

What this means in this particular context is that your one massive collection can be treated as sort of a "master" collection from which you can create forks for your functional tests. Changes to the master collection can be pulled into the forks and changes to the tests in the forks can also be merged back into the master whenever required. 

Closing this issue for now, feel free to open another if you have more feedback around our implementation.
