### ISSUE TITLE
Exporting Collections leads to empty file

### ISSUE THREAD

**Issue by anikasolanka** [a85/POSTMan-Chrome-Extension#2464]
Hi,

Since yesterday the export of collections doesn't work anymore. I am able to choose export and save it, but when I check on my hard drive, the collection is of size 0 KB.

It happens with all collections I try to export.

I am not able to use our collections in our CD pipeline anymore which blocks our test and delivery.

Best regards,

Anika Solanka

Infos:
- Chrome App Version 4.8.1
- win / x86-32
- Chrome 54.0.2840.71
- Interceptor not activated
- recently encountered

**Comment by vegetableman** [comment]
@anikasolanka Since you are able to export, could you follow this steps:-
- Open up the devtools console window (https://www.getpostman.com/docs/errors).
- Export the collection.
- Share a screenshot of the console window in this github issue, so that we can debug and get back to you.

**Comment by anikasolanka** [comment]
While trying to get the console output it started working again. When I restarted for the devtools enablement, postman was updated to 4.8.3.
Maybe this fixed the issue?
Thank you for your support and quick response!
