### ISSUE TITLE
Two equal signs at the end of request loose in cURL generated code

### ISSUE THREAD

**Issue by adequatica** [a85/POSTMan-Chrome-Extension#2466]
1. Postman Version: 4.8.3
 2. App (Chrome app or Mac app): Mac
 3. OS details: 10.12
 4. Is the Interceptor on and enabled in the app: No
 5. Did you encounter this recently, or has this bug always been there: Don't know
 6. Steps to reproduce:

* Have GET request with two equal signs at the end: ``https://example.url/foo?bar=parameter==``
* Click [Code];
* In the «Generate code snippets» pop-up see (the last two equal signs lost): ``curl -X GET "https://example.url/foo?bar=parameter"``

 7. Expected behaviour: see cURL request with parameter as is in «Enter request URL» field: ``curl -X GET "https://example.url/foo?bar=parameter=="``

**Comment by prashantagarwal** [comment]
@enotramone Can you update to 5.2.0 and verify if this issue is fixed. Also I just tried your example
and `https://example.url/foo?bar=parameter==` was shown as `https://example.url/foo?bar=parameter%3D%3D` which I believe is correct.
