### ISSUE TITLE
POST data not showing on import .json file

### ISSUE THREAD

**Issue by alexrootways** [a85/POSTMan-Chrome-Extension#2467]
Hi,
I seen POST data issue when we import postman's json file.    For example i had downloaded .json file from https://github.com/CurrencyCloud/postman.  After import if i  try PHP CURL code using code generate tool of postman, then it was not showing any  POST data.   That means after import if we try to call api then it does not work because nothing as send as post data, evenif it shows post data in api fields.  In backend it does not read post data.   But now suppose if we  manually enter same field then it will works. In this case it will show all fields in code generated tools too.
![1](https://cloud.githubusercontent.com/assets/8638707/20256298/84765ffa-aa68-11e6-9ed8-3354dd040cbf.jpg)
![2](https://cloud.githubusercontent.com/assets/8638707/20256300/883486c6-aa68-11e6-9fed-1f7f1b44081f.jpg)

**Comment by alexrootways** [comment]
Just remind that i use windows based POSTMAN tool, instead of use as chrome plugin.

**Comment by a85** [comment]
This should be fixed now.
