### ISSUE TITLE
Plus signs in request URLs are automatically encoded

### ISSUE THREAD

**Issue by grayrod** [a85/POSTMan-Chrome-Extension#2468]
## Version/App Information:
 1. Postman Version: **4.8.3**
 2. App (Chrome app or Mac app): **Mac app**
 3. OS details: **macOS Sierra 10.12.1**
 4. Is the Interceptor on and enabled in the app: **no**
 5. Did you encounter this recently, or has this bug always been there: **Recently**
 6. Expected behaviour: **Plus signs (+) in request URLs would not be automatically encoded**

## Description
My requests that include a plus sign in the query string are no longer working. They are returning bad request errors.  I first noticed after updating to 4.8 and have been working around this problem since then. 

A plus sign in the query string should represent a space.  But it seems any **+** gets automatically encoded to **%2B**.  The API I'm talking to then decodes the %2B back to a +, instead of a space. If I manually change plusses to spaces then all works again in Postman.

NOTE: If I copy/paste a request URL with a plus sign directly into Terminal and use cURL, then it works.

**Example problematic request URL**
**https://example.com?filter=lastName+%3D+rodriguez**

**Example working request URL**
If I replace the plus signs with actual spaces, the request works as expected, like this:
**https://example.com?filter=lastName %3D rodriguez**

**Comment by TatyanaMartynyuk** [comment]
I have the same issue on Postman Version 4.9.1 (4.9.1)

**Comment by SamvelRaja** [comment]
@grayrod @TatyanaMartynyuk 
 The issue has been fixed in our latest canary([4.9.4-canary.1](https://dl.pstmn.io/download/latest/osx?channel=canary)) release,
can you guys switch to that version an check the same?
On additional note we are using the whatwg's [url parser algorithm](https://url.spec.whatwg.org/#parsers).

**Comment by SamvelRaja** [comment]
@grayrod @TatyanaMartynyuk Just a nudge to check whether you guys had the chance to test it in the latest canary.

**Comment by grayrod** [comment]
@SamvelRaja I tested it out in Postman Canary v4.9.4 and it looks good now . Thanks!

**Comment by TatyanaMartynyuk** [comment]
Hi!
I did not have chance to test it because I changed a job and at my new
place I do not use Postman (for now).
Anyway, thank you for fixing it!

Tatyana

**Comment by grayrod** [comment]
Looks good in the new Mac app version 4.10.0. Thanks!
