### ISSUE TITLE
Add "data" to postman collections/calls

### ISSUE THREAD

**Issue by mistersender** [a85/POSTMan-Chrome-Extension#2470]
I would like to have a feature added to postman where custom data could be saved on each call/collection/folder, much like the "edit" allows a description to be saved. I'm working on some stuff with postman/newman/cloudAPI where it would be really handy to be able to save some user-defined data with each of these for automated testing purposes & have that data also returned from the cloudAPI. For example, I may like to be able to run tests against a certain a tag. If the collections support data, I could add tags in the data and query the API to see what tests to run.

**Comment by vegetableman** [comment]
@mistersender For now, the app supports environments which allow you to maintain custom data in variables that you could use through out collections.(https://www.getpostman.com/docs/environments). As for supporting data pertaining to each request, it is part of the roadmap. Will keep you posted in this thread.

**Comment by a85** [comment]
Collections now support variables which you can use to embed data into Collections.
