### ISSUE TITLE
Pretty print is producing invalid data

### ISSUE THREAD

**Issue by AlexandraColdea** [a85/POSTMan-Chrome-Extension#2471]
Postman Version: 4.8.3
OS X 10.10.3

Steps to reproduce the problem:
Have a request that returns the following raw result:
`{  "script" : "var quote = \"<quote>\\\"<quote>\";"}`
In the pretty print view this is turned into:
`{ "script": "var quote = \"<quote>\"<quote>\";"}`
which is invalid

**Comment by sdnts** [comment]
@AlexandraColdea That looks like valid JSON. The quotes (") in the value are escaped properly using backslashes ( \ ), so it looks proper.

**Comment by AlexandraColdea** [comment]
@madebysid 
You are right, the JSON is valid, however Postman unescapes part of the data, making it illegal. 

I have the following string which contains an escaped quote: 
`var quote = "<quote>\"</quote>";`
When I serialise it and send it as a value in a JSON this turns to:
`{ "script" : "var quote = \"<quote>\\\"<quote>\";"}`
This is the value I can see in the raw view, which is correct:
<img width="401" alt="screen shot 2016-11-17 at 14 44 05" src="https://cloud.githubusercontent.com/assets/6747174/20393610/6ba27e78-acd4-11e6-9e61-c94dc46b9a4f.png">

However, the pretty print view displays this:
<img width="439" alt="screen shot 2016-11-17 at 14 43 58" src="https://cloud.githubusercontent.com/assets/6747174/20393655/8560796e-acd4-11e6-9cc3-2401134ad879.png">

You can see that the doubly escaped quote is now only escaped once. This means that if I try to POST back the result copied from the pretty print view I can't because it's no longer valid.

Does that make sense?

**Comment by prashantagarwal** [comment]
@AlexandraColdea I believe this issue is fixed in Postman app. Please verify this in latest version of Postman app. If you are still seeing this feel free to reopen the issue.
