### ISSUE TITLE
Postman IDE, while importing v1 collection, fails to read persisted Request->Body->file value in json project file.

### ISSUE THREAD

**Issue by 4everqa** [a85/POSTMan-Chrome-Extension#2472]
Background info:
 1. Postman Version: 4.8.3  win / x86-32
 2. App (Chrome app or Mac app): Chrome Version 54.0.2840.99 m
 3. OS details: Windows 7 64bit
 4. Is the Interceptor on and enabled in the app: If it is on or off do not affect issue.
 5. Did you encounter this recently, or has this bug always been there: Always
 6. Expected behaviour: Expected behaviour would be that project settings would be still present after having closed and opened the project again.
 7. Console logs: The project requests needn't be executed in order to see this behaviour.
 8. Screenshots (if applicable)
9. Repro probability: 100% , tested various times on different systems, at different occasions in time, on different versions of postman.

Steps to reproduce the problem:
0. Do not login to a repository - this step might not be needed in order to repro issue.
1. Create a postman project (or use the echo sample postman project)
2. Inside the project, on for example on a POST request method, https://echo.getpostman.com/post ,
add to the request a Body Form-Data row with a File value. Name the row for example "file". (pls see attached screenshots)
2. Browse and choose a file and select it.
3. Verify that the value is filled in, for example "Sample.xml"
4. Press the Save button for the request method changed.
5. Export the project (as collection v1) to a file on disk, Postman%20Echo.postman_collection.json.
6. Close postman 
7. Import the same project file from the file on disk.
8. Verify that the file value is still found in the GUIof the IDE.
(In build 4.8.3  win / x86-32 the file attribute it is  empty) 

Before export:
![postman_file_value_persist](https://cloud.githubusercontent.com/assets/23533139/20409061/6ca055cc-ad18-11e6-8be9-c3dd523b14aa.png)

After import:
![postman_file_value_persist_after_import](https://cloud.githubusercontent.com/assets/23533139/20409208/0f0120a8-ad19-11e6-8813-aa9cc56f3659.png)

More info:
It appears that it is the opening(reading), as opposed to closing(writing), of the project data that contains the defect. The reasoning behind this belief is that if one opens the resulting persisted json project file , the text editor shows the filename properly value "Sample.xml" contained in it. 
However, as pointed out earlier, after opening it in the IDE it is not visible.

Many thanks for fixing this issue.

**Comment by sdnts** [comment]
@4everqa Thanks for reporting this, I'm looking into this.

**Comment by sdnts** [comment]
@4everqa I noticed you are using the Chrome App. In that case, re-loading the file on import won't be possible, because Chrome (and most browsers) do not supply us the full file path when uploading. Also, they do not allow apps to read from a user's file system.

As for the native apps, this looks like a bug, and I'll get on a fix.

**Comment by 4everqa** [comment]
Many thanks for looking into this issue madebysid. /4everqa

**Comment by sdnts** [comment]
Hi @4everqa the app no longer stores file paths with a collection to address security concerns, so I doubt this will ever be possible. I'm closing this for now.
