### ISSUE TITLE
Feature request: More visibility for collection request descriptions

### ISSUE THREAD

**Issue by poisa** [a85/POSTMan-Chrome-Extension#2474]
When saving a request, there is an option to enter a description. It would be great if this description could be seen (at least the first line) right below each request in the Collections.

The reason this is useful is because -in my case- all the URLs for my collections look exactly the same but headers are different. I have 20 items in a collection and have no way of differentiating them other than the description (which is not visible). In order to find the one I want, I have to click them all one by one. 

A good place (I think) to put the description would be in the Collection list right under each URL. In my particular case only the first line of the description would suffice.

**Comment by vegetableman** [comment]
@poisa When saving a request, you could also edit the name of the request. Let me know if that helps.

**Comment by poisa** [comment]
@vegetableman Ah! I thought the name was the actual URL and that if I changed that the request would change. 
Now that I know they aren't related I'm going to go ahead and change them! 
Thanks!
