### ISSUE TITLE
Swagger.yaml not importing

### ISSUE THREAD

**Issue by dulichan** [a85/POSTMan-Chrome-Extension#2475]
1. Postman Version: 4.8.3
 2. App (Chrome app or Mac app): Mac app
 3. OS details: 10.11.5
 4. Is the Interceptor on and enabled in the app: nope
 5. Did you encounter this recently, or has this bug always been there: always
 6. Expected behaviour: Swagger YAML file to load 
 7. Console logs

Not parseable YAML: <ParseException> Malformed inline YAML string ("Get the details of the operations/activities executed by the server\). (line 33: 'description: "Get the details of the operations/activities executed by the server\')

Steps to reproduce -
Please import the attached file to postman. 

Possible cause - 
The yaml file has a line break. I have validated the yaml file using a linter and it's passing linter tests. 

summary: "Getting Activity Details"
      description: "Get the details of the operations/activities executed by the server\
        \ on the devices registered with WSO2 EMM, during a defined time period."
      operationId: "getActivities" 

[swagger.yaml.zip](https://github.com/postmanlabs/postman-app-support/files/599849/swagger.yaml.zip)

**Comment by vegetableman** [comment]
@dulichan Thanks for reporting this issue 👍 . We were able to replicate it, will get back to you.

**Comment by vegetableman** [comment]
The issue has been fixed on our internal build. Stay tuned for the next release ^_^.

**Comment by SamvelRaja** [comment]
@dulichan  This has beed fixed in our latest 4.9.0 version. Kindly check the same from your end.
