### ISSUE TITLE
Response lag in native app compared to chrome app

### ISSUE THREAD

**Issue by vegetableman** [a85/POSTMan-Chrome-Extension#2476]
1. Postman Version: 4.8.3
 2. App (Chrome app or Native app): Native
 3. OS details: Any
 4. Is the Interceptor on and enabled in the app: No
 5. Did you encounter this recently, or has this bug always been there: always
 6. Expected behaviour: Similar or nearly identical response time.
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):

Steps to reproduce the problem:
Hit `Send` on any url, notice the response displayed is ~2 second slower on the native app, regardless of the underlying platform, compared to the chrome app.

**Comment by mstaalesen** [comment]
+1

**Comment by aguilera51284** [comment]
+1

**Comment by michaeldaw** [comment]
I have also just started experiencing this as well. It's not just a lag in hitting the  "Send" button, but in typing in to the URL input box as well. The Chrome App version continues to work fine.

**Comment by katzbo** [comment]
+1. it takes ever :(.

**Comment by tapyokka** [comment]
+1

**Comment by Kars-de-Jong** [comment]
+1 for me too. Response times are less than 100 ms with the Chrome app, and > 800 ms with the native app. This starts getting especially important now that the Chrome app is about to be discontinued.

**Comment by thecodemill** [comment]
+1 I'm getting > 5000ms responses compared to the ~200ms previously!

**Comment by andreaforzani** [comment]
+1

**Comment by prsh9** [comment]
+1

**Comment by kubalunacek** [comment]
+1

**Comment by thecodemill** [comment]
FYI, I only found out yesterday that [macOS routes requests to .local domains via Multicast DNS (Bonjour)](https://support.apple.com/en-gb/HT201275) rather than standard DNS. I think Windows has a similar policy in place. It is possible to enable standard DNS lookups, but I found this was the case of my 5000ms delays, not Postman. The upgrade to desktop version just happened to coincide with me experiencing the .local lag. I presume that the Bonjour lookup is timing out after 5 seconds, then re-attempting through normal DNS. Hope this helps.

**Comment by Kars-de-Jong** [comment]
FYI, same goes for me. In my case it was a NetBIOS name lookup. If an IP number is used instead, it's fast (even faster than the Chrome app).

**Comment by wyudong** [comment]
My `etc/hosts` is like the following. Requesting `.dev` will get response much faster than `.local`. That only happen on postman native app not chrome extension. I can now switch to the native app.

```
127.0.0.1 hb.local
127.0.0.1 hb.dev
```

**Comment by thecodemill** [comment]
It's a bit of a pain to maintain, but I've started doing this in `/etc/hosts` to allow `.local` sites to load without the 5000ms Bonjour lookup:

```
127.0.0.1	mysite.local
::1		mysite.local
```

**Comment by chimit** [comment]
Very annoying problem. Interesting thing is that only the first request is slow. If hit the "Send" button again the response is quick. Sometime later everything repeats.

Local endpoint:
- Chrome App: **214 ms**
- macOS App: **5179 ms**

**Comment by vikiCoder** [comment]
We've added a tooltip in response time showing detailed timing information after the request is sent. Please update to the latest version(v7.0.9) and you will be able to see what is taking more time in request sending. Below is a screenshot just as an example of this feature.

![image](https://user-images.githubusercontent.com/16588032/56639099-7cb26a00-668d-11e9-956b-da417d65e7da.png)

**Comment by chimit** [comment]
@vikiCoder @a85 the problem still takes place for the first request:

![image](https://user-images.githubusercontent.com/839349/57748468-a569d480-770c-11e9-9a49-90ee1a13a8e3.png)

**Comment by shamasis** [comment]
@chimit - there could be various reasons for the delay between handshake to first-byte. I would need a a way to reproduce this condition locally - can you file a separate issue with as much detail as possible to reproduce this?

TLS certificates and gzip can interfere with time time to first byte and chrome app has a global cache that native app doesn’t have and that too can influence the behaviour of first request.
