### ISSUE TITLE
Not exporting Body into "CURLOPT_POSTFIELDS" when generating a PHP cURL Script

### ISSUE THREAD

**Issue by vinnyamp** [a85/POSTMan-Chrome-Extension#2478]
1. Postman Version: **4.8.3**
 2. App (Chrome app or Mac app): **Mac App**
 3. OS details: **OS X SIERRA**
 4. Is the Interceptor on and enabled in the app: **No**
 5. Did you encounter this recently, or has this bug always been there: **Recently**
 6. Expected behavior: **Get "CURLOPT_POSTFIELDS" when generating a PHP cURL script.**

I'm facing a problem on Postman when I generate a PHP cURL script. In previous versions it used to export  the Body request into the "CURLOPT_POSTFIELDS" on the generated PHP cURL Script, but now it won't export.

Screenshot:

![issuepostman](https://cloud.githubusercontent.com/assets/4457878/20459199/4bc1d900-aea0-11e6-8e85-aa4b92a2066c.png)

**Comment by sdnts** [comment]
@vinnyamp This is fixed internally and we'll be rolling out a fix for this in the coming releases. Will keep you updated.

**Comment by sdnts** [comment]
@vinnyamp The latest version (4.9) has fixes that should solve your issue. Can you update and confirm?

**Comment by thomasmoors** [comment]
The bug seems to be back. My current version is 7.9.0 for Mac OS.

**Comment by Erellariss** [comment]
Also faced this bug on windows 10.
