### ISSUE TITLE
Data File Import - Collection Runner - not working properly

### ISSUE THREAD

**Issue by nau7ic** [a85/POSTMan-Chrome-Extension#2482]
Postman Version: **4.8.3**
App (Chrome app or Mac app): **Chrome**
OS details: **Win 7 64-bit**
Is the Interceptor on and enabled in the app: **NO**

**Current behaviour**:
When I import the example CSV or JSON File the last colum (password) is missing in the preview and is not imported.

**Expected behaviour**:
When I import the example CSV or JSON File all colums are imported and in the preview screen.

![data preview](https://cloud.githubusercontent.com/assets/23634399/20484490/b61933ae-aff7-11e6-8f7f-bdd435ffa756.PNG)

**Comment by nau7ic** [comment]
I was trying to import my own files and it didnt work as expected. First i thought i had a format error in my CSV file. So i imported both example files with the same outcome. Only the first 4 colums are shown

**Comment by SamvelRaja** [comment]
@nau7ic The preview modal shows all the columns, you need to scroll horizontally to view that.
And does your data gets properly replaced in your request while running the collection?

**Comment by nau7ic** [comment]
Sry for late answer. I guess i had a chaching issue. Now everthing is working as intended. Thx you for your help.
