### ISSUE TITLE
Show Postman Console before Show DevTools - DevTools console remains blank

### ISSUE THREAD

**Issue by stormposse** [a85/POSTMan-Chrome-Extension#2483]
1. Postman Version: 4.8.3
 2. App (Chrome app or Mac app): Mac app
 3. OS details: OS X 14.5.0 / x64
 4. Is the Interceptor on and enabled in the app: no
 5. Did you encounter this recently, or has this bug always been there: since 4.8.0
 6. Expected behaviour: DevTools console shows messages from Postman regardless of Postman Console / DevTools launch order
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 8. Screenshots (if applicable)

DevTools launched AFTER postman console launched - file name is ...console.html
![DevTools launched AFTER postman console launched - file name is ...console.html](https://cloud.githubusercontent.com/assets/17124925/20522137/90349052-b0a6-11e6-9575-68296da907f2.png)

DevTools launched BEFORE postman console launched - file name is ...requester.html
![DevTools launched BEFORE postman console launched - file name is ...requester.html](https://cloud.githubusercontent.com/assets/17124925/20522304/7ec5fa94-b0a7-11e6-88ec-c58142ee6bfe.png)

1. Open postman Mac app

2. Select in sequence from Postman menu: 
    View > Show Postman Console (Postman console opens)
    View > Show DevTools (DevTools console opens)
    write a console.log("test-message"); in a script and execute
    - note no output appears in the DevTools console
    - close the Postman Console
    - note BOTH consoles are closed

3. Select in sequence from Postman menu: 
    View > Show DevTools (DevTools console opens)
    View > Show Postman Console (Postman console opens)
    write a console.log("test-message"); in a script and execute
    - output appears in the DevTools console as normal and in Postman Console as well
    - close the Postman Console
    - DevTools console remains open as expected

**Comment by vegetableman** [comment]
@stormposse I am not able to reproduce the issue. Also, regardless of the sequence, the log will be displayed on both Devtools and Postman Console. Let me know if you need any clarifications.

**Comment by vegetableman** [comment]
@stormposse Also, if you could share a screencast for the issue, the better I would be able to help you.

**Comment by stormposse** [comment]
Thanks for looking at this @vegetableman. I re-installed 4.8.3 this morning and tried again - the problem is still there. I made a QuickTime movie and here it is on screencast:
http://www.screencast.com/t/rVHlWAoiknp

Any ideas what may be going on?

**Comment by vegetableman** [comment]
@stormposse Thanks for sharing the screencast 👍 . On the second case (in the vid), You need to focus the main window (request builder), instead of the console and then, open devtools to see the logs. Devtools is different for both the windows and will open based on the focused window. 

But, I think we could make changes, so that, the logs appear for the devtools on the Postman Console window as well.

**Comment by stormposse** [comment]
Ah! Thanks @vegetableman, I get it now - yes if I focus on the main window again after opening Postman Console and then open devTools it's fine. I just expected both to refer to the same (main Postman) window. Same thing happens if you use the keyboard shortcuts - alt-cmd-c followed by alt-cmd-i.
