### ISSUE TITLE
Make saved responses more obvious

### ISSUE THREAD

**Issue by fotoflo** [a85/POSTMan-Chrome-Extension#2484]
1. Postman Version:
 2. App (Chrome app or Mac app):
 3. OS details:
 4. Is the Interceptor on and enabled in the app:
 5. Did you encounter this recently, or has this bug always been there:
 6. Expected behaviour:
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 8. Screenshots (if applicable)

**Comment by a85** [comment]
Coming up soon through the "Examples" feature.
