### ISSUE TITLE
allow editing of saved responses

### ISSUE THREAD

**Issue by fotoflo** [a85/POSTMan-Chrome-Extension#2485]
so i can show what the response SHOULD look like

**Comment by gwestwater** [comment]
Is there an ETA on this I need to scrub some data out of the sample responses we have saved

**Comment by bhawna2109** [comment]
@fotoflo @gwestwater We are working on something which will support editing/reordering etc. of saved responses in a neat manner.

There isn't any ETA on this, but will update this thread once it's out in canary.

**Comment by derekssmith** [comment]
+1

**Comment by mnannola** [comment]
+1

**Comment by juancferrer** [comment]
+1

**Comment by bhawna2109** [comment]
hey guys, we have an exciting update  - response editing is here! :tada:

Get the story - http://blog.getpostman.com/2017/05/17/mock-responses-in-postman-by-using-examples/
