### ISSUE TITLE
Escape string does not work in an html in json

### ISSUE THREAD

**Issue by aminsepahan** [a85/POSTMan-Chrome-Extension#2488]
when we want to have a html content in our Json, we should skip its string!
but the problem is that postman supports clicking on link in html or Jsons, but when you click on it, it uses the last "/" so it wouldn't work

**Comment by aminsepahan** [comment]
for example in this Json string:

http://degaresh.com/5190/%d8%af%d8%b3%d8%aa%d9%87%e2%80%8c%d8%a8%d9%86%d8%af%db%8c-%d9%86%d8%b4%d8%af%d9%87/30-%d8%af%d8%a7%d8%b3%d8%aa%d8%a7%d9%86-%da%a9%d9%88%d8%aa%d8%a7%d9%87-%d8%a2%d9%85%d9%88%d8%b2%d9%86%d8%af%d9%87-%d8%a7%d9%81%da%a9%d8%a7%d8%b1-%d8%a7%d8%ad%d8%b3%d8%a7%d8%b3%d8%a7%d8%aa-%d8%aa%d8%a7/?json=1&include=content,date,tags,categories,thumbnail&date_format=d%20M%20Y%20,%20H:i



the src of the image will not be opened when clicked on it

**Comment by sdnts** [comment]
@aminsepahan I don't think I understand is the issue that the additional `/` is being treated as teh URL?

**Comment by SamvelRaja** [comment]
Closing this for now, kindly feel free to open this when ever needed.
