### ISSUE TITLE
Multipart request with file and json data

### ISSUE THREAD

**Issue by ShilAggarwal** [a85/POSTMan-Chrome-Extension#2490]
1. Postman Version: 4.8.3
 2. App (Chrome app or Mac app): Chrome App
 3. OS details: Windows 7/64-bit
 4. Interceptor is off
 5. For multipart request, there is no provision to post send json data with the file upload. (Raw data in application/json format + file in form-data) 
 6. Expected behaviour: There should be provision to send json data type along with file upload

1. Choose a post request.
2. Set header as "Content type : multipart/form-data"
3. In the Body tab, select "form-data" and add files and json data 
4. The json data can only be text type and not application/json type 
5. Throws I/O error.

**Comment by sdnts** [comment]
@ShilAggarwal Could you try doing this on our [native apps](https://getpostman.com/apps)? The native apps are built on top of Postman Runtime, which has improved support for multipart/form-data requests.

**Comment by ShilAggarwal** [comment]
Thanks for prompt response ! But my issue is still not resolved. I need to imitate my curl request in postman (its working using curl).
The curl script is-
curl.exe -F "files[]=@!<filepath>!" -F "jobdata=@!<json_filepath>!;type=application/json" %<post_url>%

I don't have any way to send json form data in postman

**Comment by ShilAggarwal** [comment]
Hi,
Works perfect now.. sending both the files as file type only in form data :)
Thanks for the support!

**Comment by abner-xin** [comment]
@ShilAggarwal How did you resolve your issue?

**Comment by mastermunj** [comment]
@ShilAggarwal I'm also keen on knowing the solution.

@abner-xin did you find solution yet?

**Comment by ShilAggarwal** [comment]
Hi,

I was able to achieve this using the native postman app. I uploaded both
json data and file as file uploads.

Thanks
-shilpa

**Comment by mastermunj** [comment]
Okay, got it. Thank you. :)

**Comment by KeithT** [comment]
Can you provide more details how you did this please?
I am trying to do a POST with both parameters in the json formatted body and a file upload. As far as I can see Postman (x64 Windows) only supports one of the other of these. 
Under Body ->"form-data" supports a fileupload 
but Body -> Raw (with the dropdown on JSON) no file upload can be select.
So it's one or the other

**Comment by sdnts** [comment]
@KeithT If you choose `form-data` as your body type, you can change the key type using the dropdown next to it. This is only on a per-row basis, so you can send files *and* text.

**Comment by KeithT** [comment]
@madebysid Thanks for responding. Yes I saw that, but it seems to only send Text, whereas I want to sent JSON. If I try this approach I get the same 415 Unsupported Media Type response, as if I sent TEXT instead of JSON using the "raw" option (without the file for testing in this case). 

So I still don't think it's possible to send a file and JSON, or am I missing something still?

**Comment by swateek** [comment]
any solution to this?

**Comment by novalic** [comment]
I'm having the same problem. Anyone figured out a solution?

**Comment by padmakshidivate** [comment]
Hi,
May be this is little late to reply but it will be helpful to somebody stuck in between as i dont see any solution provided yet here.

Coming to the point - where we want to send JSON DATA/OBJECT and FILE as same time in single request using native POSTMAN:

step 1 : pass your json data as string in body as form-data. Where you have to put the json data in key value pair 
 step 2: Deserialize this JSON string into your object at server side where you recieve the request .
 
![image](https://user-images.githubusercontent.com/40118027/41191571-4c97fcb4-6c0f-11e8-899f-6ac730b02a2d.png)

**Comment by Ajay7Patel** [comment]
@padmakshidivate Thanks for responding. It's very helpful and worked for me.

**Comment by ntopulos** [comment]
For those who like me stumble upon this thread searching how to upload files alongside complex json data, there is actually a solution.

1. Use the `form-data` tab.
2. For the file choose the `file` format.
2. For your JSON arrays choose the `text` format and use the following structure for your keys `arrayname[keyname]`.

![](https://user-images.githubusercontent.com/11980109/34472248-60814848-ef3c-11e7-8fd8-fbbb4aba71a6.png)

Source: https://stackoverflow.com/questions/39037049/how-to-upload-a-file-and-json-data-in-postman/48054400#48054400

Related issue: #3331

**Comment by NarmadhaKumar** [comment]
how to send a array of multipart file to json, My api uploads a folder and the service has "Multipart[] files" as parameter in my rest api. Please help me with this

**Comment by dresean** [comment]
Been wrecking my brain on this one as I wan't to upload media with content entered by the user from the client in the request body in JSON form. It's currently not possible to test this with Postman [according to their documentation](https://learning.getpostman.com/docs/postman/sending_api_requests/requests/)
![Screen Shot 2019-04-17 at 6 52 30 PM](https://user-images.githubusercontent.com/20849315/56326070-95c59300-6142-11e9-87e5-27a5aaae3336.png)
Read the last line above. Such a bummer, guess I won't know if it works fully until I try it out on the front end. Ugh.

**Comment by ashwath20** [comment]
json is nothing but a String . Pass the text in json formate and Use JSON  serialise
  in other end

**Comment by dschmide** [comment]
Do I understand this correctly: 
The solution is to use multipart / formdata and use one of the values as the payload you'd normally use as the json body, combined with a (relatively irrelevant) _form key name_, which the server serializes as "the json body"?

If so, this really isnt a Postman issue, it's just smelly api design.

**Comment by raisin-shadowed1** [comment]
https://stackdev.space/questions/testing-the-rest-api-by-using-curl-to-post-json-data-json-arrays-and-image-files I was faced with the same issue and devised a fix
