### ISSUE TITLE
Feature Request, request specific ability to disable following redirects.

### ISSUE THREAD

**Issue by itsjamie** [a85/POSTMan-Chrome-Extension#2493]
It would be great to be able to disable following request redirect at the request level, perhaps via the Tests interface.

This is related to #2492, where we currently disable following all redirects to be able to grab the implicit grant token to support integration tests.

**Comment by skyboyer** [comment]
+1
especially when some requests in the same collection should follow redirects and some - just test 'Location' header

**Comment by skyboyer** [comment]
is it possible to integrate into pm object so it could be used in pre-request script?

**Comment by mjkraner** [comment]
Would love this too

**Comment by hetz** [comment]
👍 I want this feature

**Comment by basinilya** [comment]
Can't properly implement a j_security_check login: 302 means successful login and I'm not interested in following the redirect after that. 200 means bad password.

**Comment by salemgolemugoo** [comment]
Please add this feature!

**Comment by oooarthur** [comment]
Feature definitely required.

**Comment by codenirvana** [comment]
We've added support for Request Level Configurations in the latest version of the Postman App.

You can configure redirects by setting the `Automatically follow redirects` configuration.

![Screenshot 2019-11-04 at 8 56 19 AM](https://user-images.githubusercontent.com/4865836/68098165-3746e300-fee1-11e9-9317-5bab5664ec0c.png)

We'll be adding support for the folder and collection-level configurations soon!

**Comment by tsturtz** [comment]
Need this available in pre-request scripts :/

**Comment by JuanSeBestia** [comment]
I keep waiting :(  @codenirvana 

> We'll be adding support for the folder and collection-level configurations soon!
