### ISSUE TITLE
URL Encoding issue with Windows App

### ISSUE THREAD

**Issue by vamsisk** [a85/POSTMan-Chrome-Extension#2495]
1. Postman Version: v4.8.3
 2. App (Chrome app or Mac app): Windows App
 3. OS details: Windows 7
 4. Is the Interceptor on and enabled in the app: No
 5. Did you encounter this recently, or has this bug always been there: Just installed on windows
 6. Expected behaviour: URL should work without encoding issues . 
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
Couldnt parse settings to JSON. String: undefined
xml.js:22 Upgrade DB
xml.js:22  ================================================================
     o
   (/) P O S T M A N
   ^

   Go to View -> Show Postman Console to check your script logs. 

================================================================
xml.js:22 LastSynced not found...resetting to 0
xml.js:22 Since not found...resetting to 0
sails.io.js:142 🌏 sync service connectivity initiated
sails.io.js:759 socket replaying queued commands
sails.io.js:142 🌏 connected to sync service.
5xml.js:22 🐶 watchdog checking connection health
sails.io.js:142 🌏 disconnected from sync service. possibly a network outage.
sails.io.js:142 🌏 scheduled reconnection attempt #1 after 11985ms
sails.io.js:142 🌏 force disconnecting from sync service.
https://sync-xi.getpostman.com/__getcookie Failed to load resource: net::ERR_PROXY_CONNECTION_FAILED
sails.io.js:232 error requesting https://sync-xi.getpostman.com/__getcookie
sails.io.js:5 WebSocket connection to 'wss://sync-xi.getpostman.com/socket.io/?__sails_io_sdk_version=0.11.0&__sai…tform=browser&__sails_io_sdk_language=javascript&EIO=3&transport=websocket' failed: Error in connection establishment: net::ERR_PROXY_CONNECTION_FAILED
sails.io.js:142 🌏 error establishing connection with sync service.
 Error: websocket error
    at WS.Transport.onError (file:///C:/Users/xx54/AppData/Local/Postman/app-4.8.3/resources/app.asar/js/libs/sails.io.js:3:29990)
    at WebSocket.ws.onerror (file:///C:/Users/xx54/AppData/Local/Postman/app-4.8.3/resources/app.asar/js/libs/sails.io.js:4:11754)
sails.io.js:142 🌏 scheduled reconnection attempt #1 after 6628ms
sails.io.js:142 🌏 reconnecting to sync service. #(1/8)
sails.io.js:142 🌏 reconnected to sync service after being offline for 31.646seconds.
sails.io.js:142 🌏 connected to sync service.
sails.io.js:759 socket replaying queued commands
sails.io.js:142 🌏 disconnected from sync service. possibly a network outage.
sails.io.js:142 🌏 scheduled reconnection attempt #1 after 6726ms
sails.io.js:142 🌏 reconnecting to sync service. #(1/8)
sails.io.js:142 🌏 reconnected to sync service after being offline for 7.103seconds.
sails.io.js:142 🌏 connected to sync service.
8xml.js:22 🐶 watchdog checking connection health

 8. Screenshots (if applicable)

![image](https://cloud.githubusercontent.com/assets/14157831/20623904/ce06d356-b301-11e6-8eb2-55369fbfd44d.png)

**Comment by sdnts** [comment]
@vamsisk What is the value of the variable `url` in your environment / globals? Does it have any unicode characters?

**Comment by vamsisk** [comment]
@madebysid No unicode characters. It is a just a HTTP URL is like below. Just manipulated few characters in the host and path as this is confidential. 

**In URL Field:** 
{{protocol}}://{{url}}​​​/v3/api/iden

**environment variables:**

url: ppe-api-iden.com.xxxxx.org
protocol: https

**Comment by sdnts** [comment]
@vamsisk While your issue baffled me for some time, it looks like your URL has some unprintable characters, which is why you are seeing the weird percent encoding.

I'm supposing you copied the URL from somewhere, (and then I coped from GitHub) so these characters made their way into Postman. Can you try deleting the environment, creating a new one and retyping the URL variable? That should get rid of those characters, and URL resolution should work properly.

Let me know if this works for you

**Comment by vamsisk** [comment]
@madebysid 

Your observation is exactly right. Yes the URL field have some non printable characters and due to that those characters are encoded during the Resolved URL value. No issue with the data in environment variables. 

But I think we should still handle this inconsistency. Just because the same configuration is working perfectly in Postman for Chrome but not in Windows app. The configurations are initially done in postman for chrome and synced recently into windows app.

Also, if a character is non-printable I think those characters should be ignored while persisting the value in Postman data/config store.

**Comment by prashantagarwal** [comment]
@vamsisk Can you update to 5.2.0 and verify if you are still seeing this issue.
