### ISSUE TITLE
Issue with the new line encoding (%5Cn instead of %0A)

### ISSUE THREAD

**Issue by melwas** [a85/POSTMan-Chrome-Extension#2497]
Currently when using `application/x-www-form-urlencoded` Content-Type parameters with new line symbol (`\n`) are encoded as `%5Cn` (separately encoded `\` character [`%5C`] and `n` character). This can cause some hard to identify bugs on server side, where parsing the exact payload of parameters is essential (e.g. I had this issue when debugging payments gateway webhooks integration). An invalid encoding is present in both UI and all generated code snippets.

A proper encoding of `\n` symbol is `%0A`.

 1. Postman Version: 4.8.3
 2. App (Chrome app or Mac app): Mac App
 3. Is the Interceptor on and enabled in the app: Yes
 4. Did you encounter this recently, or has this bug always been there: Recently
 5. Expected behavior: New line character should be encoded as `%0A`

**Comment by SamvelRaja** [comment]
We are following a master thread #4555 to track all issues related to Url encoding. Please follow that issue for updates.
