### ISSUE TITLE
Feature request: How to read test data from local(PC)  text file in Postman sandbox?

### ISSUE THREAD

**Issue by xiaobeiying** [a85/POSTMan-Chrome-Extension#2499]
If there are some test data(.txt/.json) in the local files that I want to use within the Postman  sandbox. How can I to do?
Like FileSystemObject in Javascript.

Tks All Frist.

**Comment by sdnts** [comment]
@xiaobeiying Directy reading files in the sandbox is not possible (recommended)

You should take a look at the Collection Runner with data files. This should help: http://blog.getpostman.com/2014/10/28/using-csv-and-json-files-in-the-postman-collection-runner/

**Comment by xiaobeiying** [comment]
@madebysid  If there is only one data, that will be OK. 
But if there are many datas, and each iteration will use different data. 
How can i do that?

**Comment by vegetableman** [comment]
@xiaobeiying each iteration would be mapped to each row in the data file in case of `csv`, where as, it would be mapped to each element in an array in case of `json`.

**Comment by xiaobeiying** [comment]
@vegetableman @madebysid  Thanks all, I got it.
