### ISSUE TITLE
Oauth 2.0: state not specified during access token request

### ISSUE THREAD

**Issue by lucasvanhalst** [a85/POSTMan-Chrome-Extension#2500]
1. Postman Version:
 2. App (Chrome app or Mac app): 4.8.3
 3. OS details: linux / x86-64
 4. Is the Interceptor on and enabled in the app: no
 5. Did you encounter this recently, or has this bug always been there: 28/11/2016
 6. Expected behaviour: Postman should also send the 'state' parameter that it sent during the authorize request in the access token request.
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app): N/A
 8. Screenshots (if applicable)
![selection_071](https://cloud.githubusercontent.com/assets/6652304/20665538/5e20e192-b560-11e6-8719-c8926b9e41b6.png)

Steps to reproduce:
See screenshot. During the authorize request a random state is specified (`GET /v1/oauth/authorize?client_id=test_client_id&scope=user:name&state=5702018&redirect_uri=https%3A%2F%2Fwww.getpostman.com%2Foauth2%2Fcallback&response_type=code` but during the `POST /v1/oauth/access_token` request this state isn't specified resulting in the request being refused since the state doesn't match.

**Comment by sdnts** [comment]
@lucasvanhalst Thanks for reporting this. Could I have some more information?
When you say `state`, what do you mean? Do you mean the OAuth URL parameters? Or are the headers / body not the way you expect them?

This will help me debug this easier.

**Comment by lucasvanhalst** [comment]
I was expecting the 'state' parameter to be present in the POST parameters, just like client_id, client_secret etc. It's an optional parameter, but when it is supplied in the authorize request it should also be included in the access token request.

It's explained very well here (step 2 is where the issue is in this case) https://developer.github.com/v3/oauth/#web-application-flow

**Comment by sdnts** [comment]
Ah I get it. The OAuth2.0 helper does not have support for the `state` parameter as of now. I'll add this as a feature request though.

Did you manually add the state parameter in the authorization request in your case or was that an example? If you remove the `state` parameter, does your OAuth flow succeed?

**Comment by lucasvanhalst** [comment]
The state parameter was added by postman.

**Comment by sdnts** [comment]
@lucasvanhalst My bad, I understood your issue now. We're working on a fix for this. Will keep you updated on this thread.

**Comment by lucasvanhalst** [comment]
Thanks for that!

**Comment by sdnts** [comment]
@lucasvanhalst We added support for the `state` parameter in the latest version of the app (4.9). Can you try updating and see if your issue is resolved?

**Comment by lucasvanhalst** [comment]
Seems to be fixed, thanks!
