### ISSUE TITLE
Editors cannot publish documentation

### ISSUE THREAD

**Issue by mjgp2** [a85/POSTMan-Chrome-Extension#2501]
As an editor, I cannot publish documentation created by another user within my company, but I can publish documentation that I create. 

This is reproducible across many different collections.

Any workaround? :)

**Comment by mjgp2** [comment]
As an editor, I can also not find the public URL for the documentation as far as I can see?

**Comment by a85** [comment]
@mjgp2 We are changing the behavior here so that it follows access control rules. If you have edit permission, then you can publish this. For now you will need that person to publish. To find the public URL you can go to the "View Docs" link from the Team Library. On the top bar you will see a button that says "Published". Clicking on it will show you two links "View public URL", "Copy public URL".

**Comment by mjgp2** [comment]
Thanks for your prompt response :)

**Comment by mjgp2** [comment]
Unfortunately, there is no button there after following the instructions @a85  :(

**Comment by bityardigans** [comment]
This is actually proving to be a big reason we are hesitant to purchase pro. Seems like a pretty big oversight that we have to have the creator publish. Instructions as mentioned above do not work; button not present.

Is there an ETA on this?

**Comment by a85** [comment]
@bityardigans We missed this and will be changing the behavior pretty soon. Talking to the team.

**Comment by adamtickner** [comment]
We are running a trial now and access control rights are important for us.

Not the specific scenario above but we would like to have control over who can publish, based on roles.

**Comment by a85** [comment]
@godfrzero This is possible now I believe?

**Comment by godfrzero** [comment]
Yep. As of Feb. 23rd, anyone with `edit` permissions to the collection can publish, modify and unpublish the associated documentation.

**Comment by Fauzdar1** [comment]
I can edit the collection but can't publish it as there's no such button. Has it been moved to the pro plan completely? AFAIK, It was there last year.
