### ISSUE TITLE
Malformed encoding when requesting https://www.google.co.jp

### ISSUE THREAD

**Issue by Huachao** [a85/POSTMan-Chrome-Extension#2502]
1. Postman Version: 4.8.3
 2. App (Chrome app or Mac app): Windows App
 3. OS details: Windows 10 Build 10.0.14393
 4. Is the Interceptor on and enabled in the app: No
 5. Did you encounter this recently, or has this bug always been there: Just installed windows app
 6. Expected behaviour: 
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 8. Screenshots (if applicable)

![image](https://cloud.githubusercontent.com/assets/2796177/20691627/2572db90-b60d-11e6-8343-f990a6423940.png)

**Comment by SamvelRaja** [comment]
Thanks for bringing this to our notice. We shall keep you posted regarding this process 😄

**Comment by sdnts** [comment]
@Huachao Updating to 4.10.2 should solve this. Can you verify please?

**Comment by Huachao** [comment]
@madebysid verified, it's solved, thanks
