### ISSUE TITLE
OAuth 2.0 Callback URL should be editable

### ISSUE THREAD

**Issue by craigday** [a85/POSTMan-Chrome-Extension#2503]
The Callback URL for OAuth 2.0 Authentication is not editable and hard-coded to https://www.getpostman.com/oauth2/callback. Some APIs we use require this value to be set to specific URL, not just any URL for security reasons. Can you please make this value editable.

**Comment by sdnts** [comment]
@craigday This is specifically weird to do, allow me to explain why.

If you have your own callback URL, your server would have to be responsible to get the authorization token from the OAuth 2.0 provider, and exchanging it for the access token (while logging in to the OAuth 2.0 provider, which can be a hard-coded user I suppose). 
While these two requests are going on, the app's connection will need to be kept open and you would send the access token to the app when you receive it (after the token request). This is possible.

However, the fact that the app does all this for you is the reason the OAuth 2.0 helper exists in the first place.

In your case, if you have a server that does all this for you, you wouldn't need the OAuth 2.0 helper. I'd recommend creating a simple collection that does this (Send a request to your server with the required parameters, and let it return the access token). When your server returns an access token, save it to an environment variable and use it subsequently.

Closing this. Feel free to to reopen if I misunderstood.
