### ISSUE TITLE
[Feature Request] Add 'updated_at' attribute to collection

### ISSUE THREAD

**Issue by ronaldsalas** [a85/POSTMan-Chrome-Extension#2504]
Suggest adding a 'updated_at' (or 'exported_at') attribute to the postman collection schema so that people can know which "version" is the latest or not. I also suggest that the date value for this is updated whenever the collection is exported.

**Comment by a85** [comment]
Checking through the updated_at attribute is not the ideal way to check versions. We recommend exporting to source control or using the in-built activity feed to checking last updated results.
