### ISSUE TITLE
Pre-request Script using disabled parameters

### ISSUE THREAD

**Issue by AramilRey** [a85/POSTMan-Chrome-Extension#2506]
**Postman Version**: 4.8.3
**App**: Chrome app | Chrome 54.0.2840.100
**OS details**: linux / x86-64
**Is the Interceptor on and enabled in the app**: Yes
**Did you encounter this recently, or has this bug always been there**: Always been there

**Expected behaviour**: (List of options)
1. Disabled parameters shouldn't be on the Pre-request Script.
2. Disabled parameters shouldn't be on the request.headers / request.data Objects.
3. Every parameter should expose if its enabled or disabled.

**Steps to reproduce the problem**:
1) Create a request with some Headers or Body parameters and disable one
2) Log these values with the Pre-request Script
3) Send the request
4) Disabled parameters aren't sent, but they are available on the Pre-request Script.

In my case, this is a problem because some api validates the source of the request via making some operations to the parameters of that request to create a string, and when a parameter is used by the pre request script but not by the api, this validation fails.

**Comment by sdnts** [comment]
@AramilRey Can you try this out on our [native apps](https://getpostman.com/apps)? The native apps are built on top of Postman Runtime, which hasn't made its way to the Chrome App yet. 

You can get the current request parameters using `this.request.data`. Disabled parameters should not show up in the returned Array.
I'm unable to reproduce this there.

Feel free to reopen if I misunderstood.

You can get the current request parameters using `this.request.data`. Disabled parameters should not show up in the returned Array.
