### ISSUE TITLE
opening saved request replaces current unsaved tab

### ISSUE THREAD

**Issue by ruifortes** [a85/POSTMan-Chrome-Extension#2507]
Hello
This is a bit annoying because its common to start working on a new request and opening a saved one to copy some data.
In this case opening the saved one would replace the current unsaved one that you're working on.
If tab is dirty it shouldn't be maintained and not replaced
Thanks

**Comment by sdnts** [comment]
@ruifortes You can use the shortcut Cmd/Ctrl + Shift + Click on a saved request to open it in a new tab. That way, your current request (which isn't saved to a collection, so there's no saying if it is dirty or not) will be preserved.

Feel free to reopen if I misunderstood.

**Comment by ruifortes** [comment]
Sure...but there will be some not so clever guys like myself loosing some seconds worth of work ;-)
Nevertheless I thing the "expected" way to a bunch of us is not replacing a dirty tab.
