### ISSUE TITLE
Inconsistent ordering of test folders between Runner and Main Postman Window

### ISSUE THREAD

**Issue by PFarrell89** [a85/POSTMan-Chrome-Extension#2509]
1. Postman Version: 4.8.3 win32 10.0.10586 / x64
 2. App (Chrome app or Mac app): Windows
 3. OS details: Windows 10 64 Bit

I have a folder called '_DONE' which contains an API call to our messaging software informing the test team that a particular test collection has finished. I have one of these in every test collection folder.

This is at the bottom of the Test Collection folder as you can see in the screenshot

![image](https://cloud.githubusercontent.com/assets/8641826/20800452/7d3a7bd6-b7dd-11e6-845c-e58f1c8bd306.png)

However, in the Collection Runner the '_Done' folder is placed at the top of the list.

![image](https://cloud.githubusercontent.com/assets/8641826/20800436/737c5290-b7dd-11e6-88d3-33c6beccbc4f.png)

Minor issue, I know :)
I could just rename the folder, but thought I'd report it anyway.

**Comment by sdnts** [comment]
@PFarrell89 Thanks for reporting this, we'll fix this in an upcoming version

**Comment by sdnts** [comment]
@PFarrell89 This should now be fixed in the latest stable versions, so I'm closing this. Please reopen if you're still seeing this!
