### ISSUE TITLE
Incorrect encoding of '-' sign in Postman Runner

### ISSUE THREAD

**Issue by kkoszarski** [a85/POSTMan-Chrome-Extension#2510]
1. Postman Version: 4.8.3
 2. App (Chrome app or Mac app): Chrome 54.0.2840.99
 3. OS details: win/ x86-32

 4. Description of the problem
4.1 Create a call in the postman with PUT/POST method and place there a parameter of an email
{
	"email": "{{email}}",
	"street": "test",
	"houseNumber": "test"
}
4.2 Save call in a collection of calls 
4.3 Go to a runner and try to run this collection while provisioning csv with header email(one column not finished with comma ",") and first iteration starting from test@test-test.com 
!4.4 Run the method and observe how the "-" sign is not properly passed to the execution of the request and it fails on the backend validation. While when the request will be build by hand there is no problem. 
It is possible that application uses try to use the "-" as a delimiter however it should start to do it when column names are named.

**Comment by sdnts** [comment]
Is this still an issue? Please let me know if it is, and I'll reopen.
