### ISSUE TITLE
Ace editor: unable to right click > copy/paste text

### ISSUE THREAD

**Issue by robolivable** [a85/POSTMan-Chrome-Extension#2511]
1. Postman Version: 4.9.0
 2. App (Chrome app or Mac app): Chrome app
 3. OS details: OS X El Capitan 10.11.16
 4. Is the Interceptor on and enabled in the app: Yes
 5. Did you encounter this recently, or has this bug always been there: Noticed recently
 6. Expected behaviour: Highlight/point to text in Ace editor > right click > copy/paste
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app): N/A
 8. Screenshots (if applicable)

![screen shot 2016-12-01 at 1 17 57 pm](https://cloud.githubusercontent.com/assets/7831876/20806536/51f05856-b7c9-11e6-959c-6a79ec6f2bb7.png)

![screen shot 2016-12-01 at 1 18 56 pm](https://cloud.githubusercontent.com/assets/7831876/20806541/55f9a8d0-b7c9-11e6-9ffd-f867a5a0283b.png)

Steps are pretty clear, highlight/point to any text in any of the Ace editor fields, and right click.

Started noticing this issue on my box at work for the last few days. At first I suspected it to be an OS problem, but even after an update/a couple of restarts, the issue persists.

**Comment by robolivable** [comment]
Just now noticed that this may be an issue higher up in Chrome itself. I get the same problem on Ace's home page... This can be closed since it may be unrelated to Postman.

Edit: This is due to a bug regarding a Chrome update and Ace: https://github.com/ajaxorg/ace/issues/3127

**Comment by vegetableman** [comment]
@robolivable yep. Thanks for commenting on the ace issue thread ^_^.
