### ISSUE TITLE
Add application/vnd.api+json to Content-Type autocomplete

### ISSUE THREAD

**Issue by silverqx** [a85/POSTMan-Chrome-Extension#2512]
__application/vnd.api+json__ header value is missing in Content-Type's autocomplete dropdown list.

I think, that whole postman behavior ( syntax highlight, preview, ... ) is the same as for __application/json__ header.

**Comment by mathewdgardner** [comment]
+1

**Comment by nilskp** [comment]
It seems that Postman doesn't even understand that `application/vnd.api+json` is of type `application/json`, since formatting is listed as just `Text`.

**Comment by richardsondx-symbility** [comment]
+1

**Comment by silverqx** [comment]
I tried latest __v6.5.2__ now and __application/vnd.api+json__ header is still missing.

Here is link, which describes differences between __application/vnd.api+json__ and __application/json__ headers, in short __application/vnd.api+json__ is for jsonapi requests ( https://jsonapi.org/ ) and it has been properly registered with IANA.

https://stackoverflow.com/questions/28055526/header-value-application-vnd-apijson

**Comment by nilskp** [comment]
This ticket should address any `application/<whatever>+json` content types, as they're all JSON, and should be formatted such.

**Comment by nayema** [comment]
+1

**Comment by simonewebdesign** [comment]
+1

**Comment by bret-peterson** [comment]
+2 :)

**Comment by hvt** [comment]
Like @nilskp mentioned, here the 'official' link describing the `+json` suffix: https://tools.ietf.org/html/rfc6839#section-3.1 and the IANA registration of the content type: https://www.iana.org/assignments/media-types/application/vnd.api+json.

Would indeed be great if JSON API requests and responses would be formatted as JSON :].

**Comment by justmobilize** [comment]
Any progress on this? Is it hard to add `application/vnd.api+json` as a format that works 100% like `application/json`?

I understand it's not widely used, but this makes Postman difficult to use

**Comment by saswatds** [comment]
Hi everyone, 
Starting app version 7.7 `content-type` header in the form `application/*+json` are now automatically detected as `JSON` language. 

Do check it out. Your feedbacks are valuable to us. 

Thanks.

**Comment by bret-peterson** [comment]
> Hi everyone,
> Starting app version 7.7 `content-type` header in the form `application/*+json` are now automatically detected as `JSON` language.
> 
> Do check it out. Your feedbacks are valuable to us.
> 
> Thanks.

I upgraded to 7.7.3 (Windows) and still don't see this functionality working

**Comment by vpmv** [comment]
> I upgraded to 7.7.3 (Windows) and still don't see this functionality working

I had to run the update twice to make it work (Linux). Also, don't be tempted to reselect JSON on the body pane.

**Comment by justmobilize** [comment]
So it works, but definitely a little confusing. Since it's not in the drop down. And agree with other comments, if you then re-select `JSON` from the drop down, it overwrites the `content-type` header (which then will break API calls...)

But it is a step in the right direction!

**Comment by codenirvana** [comment]
Hey everyone 👋 
The latest version of the Postman app (v7.20.0) will no longer force add/update the `Content-Type` header on switching the raw body language.

As mentioned in https://github.com/postmanlabs/postman-app-support/issues/2512#issuecomment-533672748, `Content-Type` headers in the form `application/*+json` will be automatically be detected as JSON language.

**Comment by justmobilize** [comment]
Works great! Thanks so much

**Comment by saswatds** [comment]
Closing this issue now. Additionally we have also added `application/vnd.api+json` to the auto-complete which should out in the next release.

**Comment by JoeAlamo** [comment]
@saswatds Hey there, I'm glad this is fixed in the Postman app, however on hosted Postman docs any example request or response that uses `application/vnd.api+json` doesn't have the same formatting that `application/json` does, the formatting is completely plain.

e.g: 
![Screenshot 2020-10-23 at 10 54 40](https://user-images.githubusercontent.com/8210662/96989887-3e199c00-151e-11eb-8e60-6cf89f4c45c1.png)

Where would be the best place to raise this issue?

**Comment by Tim-K-DFW** [comment]
Any progress on this? 7 years later, there's still no way to do this, because Postman auto-generates `content-type` header which CANNOT be edited or disabled ([any more](https://community.postman.com/t/application-vnd-api-json-in-drop-down-of-body/13996)... why???), at the same time not having this option in `body` dropdown.

You guys have a fantastic tool that I truly loved for years, but it's perplexing inexplicable stuff like this that makes one switch tools. Thank you! 🙏🏽💖
