### ISSUE TITLE
Request Collection Location Subtitle

### ISSUE THREAD

**Issue by danielcooperxyz** [a85/POSTMan-Chrome-Extension#2513]
It would be quite useful when working with large postman collections, for the request header to contain or be subtitled with the location in the collection?

I maintain requests for the same API in different environments, with many requests having the same name, it's quite confusing knowing which folder the request is in when it is open.

At the moment I differentiate by changing the title, but by displaying the location in the collection might be better? A combintion of tool tip on hover and subtitle under the request title might be cleaner?
![image](https://cloud.githubusercontent.com/assets/5233036/20831006/0e184f5a-b87b-11e6-88d2-e13dd81e0f1d.png)

**Comment by a85** [comment]
That's a good idea. We'll think about this more and reply here.

**Comment by bhawna2109** [comment]
@d4nc00per The app now ([v 4.10](https://www.getpostman.com/apps)) has a tight coupling between the active tab and the request in the sidebar. Thus, the sidebar _always_  highlights the request you're working on, so this should help in identifying its parent folder/collection.

We are working on some features which will involve slight UX changes in the tab, and will definitely consider your suggestion for the same.

**Comment by danielcooperxyz** [comment]
I will check it out, thanks for the update!
