### ISSUE TITLE
"Error reading data file. Error: Could not determine format of file." when uploadin JSON or CSV file in Runner after update to 4.9.0

### ISSUE THREAD

**Issue by karinamkl** [a85/POSTMan-Chrome-Extension#2514]
1. Postman Version: 4.9.0
 2. App (Chrome app or Mac app): Windows desktop app
 3. OS details: Windows 7 Professional 
 4. Is the Interceptor on and enabled in the app: (only in Chrome app - off)
 5. Did you encounter this recently, or has this bug always been there: in v.4.7.2 when uploading JSON file was getting error that app is unable to determine format but could manually select format from dropdown 
 6. Expected behaviour: JSON file gets uploaded in Runner
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 8. Screenshots (if applicable)
https://cloud.githubusercontent.com/assets/20668526/20837822/ccc4c3d2-b873-11e6-9e0b-dbbe435aa51e.png

**Comment by numaanashraf** [comment]
Hi @karinamkl, thanks for reporting this. Could you mail a sample of the JSON you are facing issues with to help@getpostman.com? We'll help you get this sorted.

**Comment by karinamkl** [comment]
Hi @numaanashraf sent files to help@getpostman.com

**Comment by davecanderson** [comment]
I have the same issue loading a CSV. If you ignore the error the collection will run and complete the selected number of iterations however it uses the first line in the CSV for all the iterations. As a result I've not been able to test the new feature for 0 iterations using all the lines in the file; https://github.com/postmanlabs/postman-app-support/issues/1342. Selecting 0 just runs a single iteration using the data from the first line.

I've mailed my collection, data, environment and run result to help@getpostman.com.

**EDIT:** My normal installation prompted me to upgrade which I did. I've now uninstalled Postman (Windows x64) and reinstalled the Canary channel. I now get the _Data File Type_ and _Preview_  controls which were not present before. The file format error is only shown when clicking _Preview_ but the issues running the collection persits.

Testing using 0 for the iterations appears to run a single iteration. Afterwards the recent run list shows a running collection (in blue) and the details have no requests and the progress % is NaN. You can't Stop Run so you have to delete the recent run.

I'm unsure if this is related or just not a feature but inspecting the run results none of the Request information has been populated with the data used in the iteration.
![postman-run-result](https://cloud.githubusercontent.com/assets/2754325/20870506/a21c41f2-badd-11e6-95d4-95454920f382.png)

**Comment by sdnts** [comment]
@karinamkl @davecanderson We've released a fix for this, and you should be able to use your CSV files properly now. Can you update your app to the latest version (4.9.1) and verify if the fix works for you?

**Comment by karinamkl** [comment]
@numaanashraf Updated for version 4.9.1 and I'm able to attach/preview JSON and CSV files and run collection with them successfully. Also able to see array of objects from JSON in preview.

**Comment by Negatseg** [comment]
hello, I face the same challenge when I try to import my folder to post man. would you help me out on that It says 'could not determine format'.
