### ISSUE TITLE
Populate environment variables  before pre-request script

### ISSUE THREAD

**Issue by ocmyhome** [a85/POSTMan-Chrome-Extension#2516]
I need to create a hash based off of my url, and I have an environment variable set for the base url portion, {{BaseUrl}}.  In a pre-request script I call request.url, but {{BaseUrl}} isn't passing along the value I've set for it, and responds with something like:  "{{BaseUrl}}/web.api/blah/blah" and not  "https://prodendpoint/web.api/blah/blah"

Is it possible to have these environment variables be populated or accessible for pre-request scripts?  We have multiple environments, so this base url value will be different in each.  I'm not sure how to resolve this issue without this populated enviro value.

Version/App Information:
 1. Postman Version: 4.8.3
 2. App (Chrome app or Mac app): Chrome 54.0.2840.99
 3. OS details: windows 10
 4. Is the Interceptor on and enabled in the app: No
 5. Did you encounter this recently, or has this bug always been there: Just encountered this today
 6. Expected behaviour:  environment variable be populated with set value, available for use in the pre-request script.

Steps
1. Create a GET request with url:  "{{BaseUrl}}/en-us/"
2. Create an environment variable of:
  key = BaseUrl
  value = https://www.microsoft.com
3. Select this environment in Postman
4. In the pre-request script, add:
  var url = request.url;
  console.log(url);
5. Open dev tools > console, to examine the console.log output
6. Send the request
7. Note, it will output {{BaseUrl}}/en-us/

**Comment by ocmyhome** [comment]
I can work around this by simply calling:  postman.getEnvironmentVariable("variable")

Preferably, Postman be enhanced to populate these values prior to running a pre-request script

**Comment by sdnts** [comment]
@ocmyhome Pre-request scripts, as the name suggests, are run before the request is made, so variables in the URL are not resolved at that time. This is by design.
The correct way of accessing variables is indeed `postman.getEnvironmentVariable`.

**Comment by pixelwiz** [comment]
Hi, so how can I pass a value calculated in the pre-request script into the URL variable?  I tried setting key={{variabkle}} amd key={{postman.getEnvironmentVariable("variable")}} neither worked for me, it puts the actual string in the URL.  So how do I make it resolve the variable?

**Comment by ocmyhome** [comment]
Call this:  postman.setEnvironmentVariable("SomeEnviroProp", calculatedVar);

This will set the enviro prop w/ your value...

**Comment by pixelwiz** [comment]
Thanks, I figured out that part, but I could not get it to actually be used in property as variables.  I was trying to do things like {{keyvalue}}  Turns out it does actually work, but you have to enable the environments first and then add one and select it.  Then it finally worked.  Also I was able to use CryptoJS functions, which was great, but the final piece of the puzzle was to encodeURI();  Then everything worked.
