### ISSUE TITLE
GET request displayed with POST data in documenter

### ISSUE THREAD

**Issue by yentsun** [a85/POSTMan-Chrome-Extension#2518]
self-explanatory screenshot 

![selection_164](https://cloud.githubusercontent.com/assets/630971/20863518/d1ec384e-b9ff-11e6-8b44-f40c6d55b52e.png)

the post data probably duplicated from the previous endpoint description. this happens when response is *saved* for an endpoint

**Comment by sdnts** [comment]
@yentsun Thanks for reporting this. We've been planning support for custom methods in a future release, so that's why you see a body with your GET request.
For now, could you recreate the request? That'll get rid of the extra body in there.

**Comment by yentsun** [comment]
@madebysid thanks for the quick reply! This extra body actually exist in multiple requests, so recreating is not an option. I guess we can live with it for now, as body in GET is not sane anyway.

**Comment by yentsun** [comment]
BTW recreating does work, thanks @madebysid. An easy way to fix a request is to copy it and delete the original.
