### ISSUE TITLE
Add checkboxes to enable/disable parameters

### ISSUE THREAD

**Issue by maedox** [a85/POSTMan-Chrome-Extension#2519]
For headers and form data there is a checkbox per line to enable/disable it. I would like to request the same feature for URL parameters.

 1. Postman Version: 

> 4.9.0
> linux / x86-64
> Chrome 55.0.2883.75

 2. Chrome App
 3. OS details: Ubuntu 16.10

**Comment by vivek201** [comment]
Yeah, this would be really helpful.

**Comment by IllyaMoskvin** [comment]
Dupe of #785, I think.

**Comment by a85** [comment]
Closing as duplicate of #785
