### ISSUE TITLE
I'd like to request the feature for selecting multiple API requests via command click or shift click

### ISSUE THREAD

**Issue by fReinko** [a85/POSTMan-Chrome-Extension#2520]
1. Postman Version:
 2. App (Chrome app or Mac app):
 3. OS details:
 4. Is the Interceptor on and enabled in the app:
 5. Did you encounter this recently, or has this bug always been there:
 6. Expected behaviour:
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 8. Screenshots (if applicable)

**Comment by sdnts** [comment]
@fReinko You can select multiple History requests using Cmd/Ctrl + Alt + Click.
In case of requests in a collection, we're working on something along these lines. I'll keep you posted here :)

**Comment by thetreythomas** [comment]
Any updates on this? The last comment is from Dec 2016.

**Comment by MauriceS** [comment]
Any progress on this?

**Comment by DannyDainton** [comment]
This functionality is available in the latest version of the Postman platform.
