### ISSUE TITLE
"Add params to headers" does not append OAuth 1.0 values correctly -- missing a comma after "Realm" k,v

### ISSUE THREAD

**Issue by christopherwxyz** [a85/POSTMan-Chrome-Extension#2522]
1. Postman Version: Version 4.9.0 (4.9.0)
 2. App (Chrome app or Mac app): Mac app
 3. OS details: 10.12.2
 4. Is the Interceptor on and enabled in the app: No.
 5. Did you encounter this recently, or has this bug always been there: within last 4 months.
 6. Expected behavior: Postman correctly appends Realm with a `,` correctly after the first value. See screenshot below.
 8. Screenshots (if applicable)

![screen shot 2016-12-06 at 10 19 39 am](https://cloud.githubusercontent.com/assets/362387/20933742/9bbb37de-bb9e-11e6-8b3f-caf6b112a128.png)
![screen shot 2016-12-06 at 10 20 27 am](https://cloud.githubusercontent.com/assets/362387/20933748/a187567a-bb9e-11e6-9d44-19835167f755.png)

**Comment by sdnts** [comment]
@chrstphrwllc Thanks for reporting this, we're working on a fix for this, and it'll be out with the next release. I'll keep you updated here.

**Comment by SamvelRaja** [comment]
@chrstphrwllc  The fix has been added to the 4.9.2 version of the app. Kindly update and test the same 😄
