### ISSUE TITLE
console.log() returns double.

### ISSUE THREAD

**Issue by Wua4** [a85/POSTMan-Chrome-Extension#2524]
1. Postman Version: 4.91 (Latest)
 2. App (Chrome app or Mac app): Windows
 3. OS details: Windows 7x64
 4. Is the Interceptor on and enabled in the app:
 5. Did you encounter this recently, or has this bug always been there: Since update
 6. Expected behaviour: Console.log returns what was designated.
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 8. Screenshots (if applicable)

In a test script, 
console.log("Test");

In the console, this returns
Test
Test

Seems to be some repeated code, causing double to appear.

**Comment by sdnts** [comment]
@alexzxz Thanks for letting us know. We're working on a fix :)

**Comment by sdnts** [comment]
@alexzxz Can you try updating to the latest version (4.9.2) and check if this is fixed for you?
