### ISSUE TITLE
Select a Collection after a sub-collection selection in Collection runner

### ISSUE THREAD

**Issue by sgueniot** [a85/POSTMan-Chrome-Extension#2525]
Hello, this is a bug i seen in Collection runner
Version/App Information:
 1. Postman Version: 4.9.1
 2. App (Chrome app or Mac app): Mac app
 3. OS details: Max os X sierra
 4. Is the Interceptor on and enabled in the app: no
 5. Did you encounter this recently, or has this bug always been there: recently
 6. Expected behaviour: Collection should be selectable after selection of a sub Collection.
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 8. Screenshots (if applicable)

Steps to reproduce the problem:
-open Collection runner
-select a **collection** (it's working)
-select a **sub collection**
-try to select a **collection** (it's not working)

**Comment by sdnts** [comment]
@sgueniot Thanks for reporting this, we're looking into this. I'll let you know here when a fix is out.

**Comment by sdnts** [comment]
@sgueniot We released a fix for this in 4.9.2. Can you update and check if this is fixed?

**Comment by sgueniot** [comment]
hello, 
It's fixed.
thanks
