### ISSUE TITLE
Postman reporting there is a new version even though the latest version is 4.9.0

### ISSUE THREAD

**Issue by ferronrsmith** [a85/POSTMan-Chrome-Extension#2528]
Postman for linux is reporting there is a new version (4.9.1), even though the latest available version is 4.9.0

**Comment by sdnts** [comment]
@ferronrsmith There indeed is a new version (4.9.1), that has some fixes for the Runner :)

**Comment by madebysid** [comment]
Are you not able to update to 4.9.1? If so, there an issue open (#2489). It might be a permission issue, in which case, can you try doing what this comment suggests: https://github.com/postmanlabs/postman-app-support/issues/2489#issuecomment-264174117

**Comment by kunagpal** [comment]
@ferronrsmith The issue has been fixed, do go ahead and try the update :smile:
