### ISSUE TITLE
Big Bug！！！markdown editor cant type in chinese!!!!!!!

### ISSUE THREAD

**Issue by solody** [a85/POSTMan-Chrome-Extension#2530]
1. Postman Version: 4.9.0
 2. App (Chrome app or Mac app): chrome app
 3. OS details: windows10 / x86-64 Chrome 54.0.2840.99
 4. Is the Interceptor on and enabled in the app: No
 5. Did you encounter this recently, or has this bug always been there: always, and all my friends that use windows 8/10 also always get this bug.
 6. Expected behaviour: to type chinese words in postman's markdown editor.
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 8. Screenshots (if applicable)

just edit a collection or a request，input chinese words to the description field with the system type program, pinyin or wubi.

then, the words show in the input box，is not my expected.
for example:
i type "wqvb" + enter，it shou be show "你好 "，
but it show me "wqvb你好 "

**Comment by sdnts** [comment]
@solody Unfortunately, I cannot type in Chinese characters in the description, however, copying and pasting Chinese characters from elsewhere works for me. Is this only happening for you when you directly type these characters in?
If you know of a program I can use to type characters, I'd appreciate it, so I can try to reproduce this :)

**Comment by solody** [comment]
@madebysid not only me, I had tested, all windows 8/10 computer in my office, got this problem.  It's no problem when we copying n pasting Chinese characters, the problem just present when we type Chinese characters directly. All Chinese typing program I can use,  could produce this problem, for example, Windows self-contained Chinese typing programs: Pingyin拼音, Wubi五笔, Cangjie倉頡 etc. You can try it.

**Comment by SamvelRaja** [comment]
@solody 
We found the issue and fixed the same from our end, just cross check the same, attaching the gif before and after the fix.
![chinese_old](https://cloud.githubusercontent.com/assets/5114052/22689677/ffa032dc-ed57-11e6-9059-a7a54e246df7.gif)
![chinese_new](https://cloud.githubusercontent.com/assets/5114052/22689923/21c13b44-ed59-11e6-8ca6-9516f31cd0e8.gif)

**Comment by sdnts** [comment]
@solody Is this still reproducible in the latest version (4.10.2)?

**Comment by solody** [comment]
sorry for late, it's ok now in latest version, thank u very much.@madebysid

**Comment by Acris** [comment]
@SamvelRaja Hi, can you share how to fix it? Thank you.

**Comment by SamvelRaja** [comment]
@Acris  we are using the Ace editor in the app where they fixed it, detailed issue reference https://github.com/ajaxorg/ace/issues/3099

**Comment by Acris** [comment]
@SamvelRaja Thank you very much! 👍
