### ISSUE TITLE
Collection Runner Select File cannot select same file after removing data file

### ISSUE THREAD

**Issue by davecanderson** [a85/POSTMan-Chrome-Extension#2531]
1. Postman Version: 4.9.1
 2. App (Chrome app or Mac app): Windows x64
 3. OS details: Windows 10
 4. Is the Interceptor on and enabled in the app: No
 5. Did you encounter this recently, or has this bug always been there: Unsure
 6. Expected behaviour: Can select same file as previously selected

After removing a selected data file you cannot choose the same file again. You have to select another file first, remove that and then select the original.

Steps to reproduce the problem:

1. Open Collection Runner
2. Select Data File choose test.csv (file is selected)
3. Remove Data File with X
4. Select Data File choose test.csv (is not selected)
5. Select Data File choose test-alt.csv (is selected)
6. Remove Data File with X
7. Select Data File choose test.csv (is selected)

**Comment by sdnts** [comment]
@davecanderson Thanks for pointing this out. We've fixed this internally and will be rolling out a fix in the coming week. Will keep you updated here.

**Comment by sdnts** [comment]
@davecanderson We released a fix for this in our latest version (4.9.2). Can you try updating and verifying?

**Comment by davecanderson** [comment]
Yes, this issue is resolved.
