### ISSUE TITLE
Collection Runner Run Results - show iteration data for Request URL and Request Body

### ISSUE THREAD

**Issue by davecanderson** [a85/POSTMan-Chrome-Extension#2532]
I would like the feature that the Run Results will show the actual URL and data sent with the request for each iteration rather than the variable placeholders.

![run-results-request-data](https://cloud.githubusercontent.com/assets/2754325/20988941/f91285f2-bd26-11e6-9890-1e5f6863746a.png)

In the Console it can be hard to find the correct data for the requests as they have no labels.

![run-results-request-console](https://cloud.githubusercontent.com/assets/2754325/20988871/aeedbf82-bd26-11e6-9338-d5e6c8c5c7b5.png)

In the Console the expand collapse arrows adjacent to the name don't expand the same as clicking on the name.

**Comment by vkaegis** [comment]
Hey @davecanderson, thanks for pointing this out! We're working on improvements to the Runner which show both iteration and environment data as part of the run. Will let you know as soon as it's out!

**Comment by Voldacar21** [comment]
Hi @davecanderson, 
Some news about this improvement?
If not, is there another possibility to link iteration data with results?

**Comment by saswatds** [comment]
This issue has been addressed in the latest version of the app `7.18.0`. Closing this issue for now.
