### ISSUE TITLE
Missing change log for new Mac app version

### ISSUE THREAD

**Issue by amriteya** [a85/POSTMan-Chrome-Extension#2533]
Postman Version:4.9.1

I just updated to 4.9.1 Mac app version but I am unable to see the changelogs at https://www.getpostman.com/apps#changelog

The latest version displayed is: 4.8.0

Here is the screenshot:

<img width="739" alt="screen shot 2016-12-08 at 11 45 01 am" src="https://cloud.githubusercontent.com/assets/4987564/20999732/bc205a1e-bd3c-11e6-9e34-36676b4cba05.png">

**Comment by sdnts** [comment]
@amriteypandey Thanks for pointing this out. We'll update the website to reflect changelogs for all recent versions of the app.
