### ISSUE TITLE
Accessing variables in pre-request script

### ISSUE THREAD

**Issue by alan** [a85/POSTMan-Chrome-Extension#2534]
I'm trying to access the variables from the environment in the pre-request script to generate a JWT, is this possible?

I've searched the docs, issues and web for potential solutions with no luck. I've seen some information pointing that `data.variable_name` should be available. However although `data` is there, `variable_name` is undefined  on `data` (used the console to find out).

Version/App Information:
 1. Postman Version: 4.9.0
 2. Chrome app

**Comment by sdnts** [comment]
@alan In the pre-request / test scripts, you can access an environment variable using the function `postman.getEnvironmentVariable('variableName')`. [Docs](https://www.getpostman.com/docs/testing_examples)
The `data` variable is populated when you use a data file in the Collection Runner. [Docs](https://www.getpostman.com/docs/multiple_instances)

**Comment by alan** [comment]
Great!  I don't use the test so hasn't read those docs.
