### ISSUE TITLE
Test evaluation error not visible in Collection Runner

### ISSUE THREAD

**Issue by carl-ashby** [a85/POSTMan-Chrome-Extension#2535]
1. Postman Version: v4.9.1
 2. App (Chrome app or Mac app): Postman for Windows
 3. OS details: Win 10
 4. Is the Interceptor on and enabled in the app: No
 5. Did you encounter this recently, or has this bug always been there: Recent
 6. Expected behaviour: 
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 8. Screenshots (if applicable)

----
1. Open postman
2. Cause error in a test, mine was due to an empty response body.

![image](https://cloud.githubusercontent.com/assets/24458621/21016042/3020820a-bd32-11e6-8754-1ad2bbb4a638.png)

3. Open Collection Runner and run tests.
4. See error "Open DevTools for more info."
![image](https://cloud.githubusercontent.com/assets/24458621/21016112/717a7490-bd32-11e6-841f-921a2b074289.png)

5. Open Dev Tools. Nothing listed in console, couldn't find any information.

**Comment by sdnts** [comment]
@st-dev Thanks for reporting this. I'm looking into this. I'll let you know when a fix is out (hopefully some time within the next week).

**Comment by sdnts** [comment]
@st-dev Can you try updating to the latest version (4.9.2) and see if your test errors are logged properly now?

**Comment by carl-ashby** [comment]
Yes they are. Thank you.
