### ISSUE TITLE
Discrepancy between Postman-Chrome and Postman-Mac

### ISSUE THREAD

**Issue by anish83** [a85/POSTMan-Chrome-Extension#2537]
1. Postman Version: **4.9.0 for Chrome** and **4.9.1 for Mac**
 2. App (Chrome app or Mac app): **Both**
 3. OS details: **OS X EL CAPTAIN. Version 10.11.6** and **Chrome Version 43.0.2357.65 (64-bit)**
 4. Is the Interceptor on and enabled in the app: **On and enabled in Chrome** and **not enabled in Mac**
 5. Did you encounter this recently, or has this bug always been there: **We just started testing our new service**
 6. Expected behaviour: **Both Chrome and Mac versions behave in the same way.**
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app): **No errors in both console.**

 8. Screenshots (if applicable): **NA**

First of all, thank you so much for a great product!! It is saving a lot of time for our team. You guys are the best!!

My team came across an issue recently for file upload using web service that we created.

The web service is written as a plugin in Jive using J2EE, Spring, CXF.

The _**web service is working fine when using the Postman-Chrome**_. But, _**it is giving error from Jive while using the Postman-Mac**_.

When tested using the cURL command, it is working fine when using _multipart/mixed_, but throwing the same Jive error while using _multipart/form-data_.

Sample cURL command:
curl -X POST -H "Authorization: Basic YWRtaW46YWRtaW4=" -H "Content-Type: multipart/mixed" -H "Cache-Control: no-cache" -H "Postman-Token: 12fabee9-c356-a779-41bb-8e6d12eb8a29" -F "file=@UploadTest.txt" "http://localhost:8080/api/issue/attach"

So, we figured, the issue is happening as Jive has its own parser using Struts 2. And the CXF page says we have to disable the Struts 2 parser, if we use multipart/form-data.
[CXF Page](http://cxf.apache.org/docs/jax-rs-multiparts.html#JAX-RSMultiparts-NoteaboutStruts)
So, it makes sense that **the cURL command is working with _multipart/mixed_ and not with _multipart/form-data_**. (Struts parser is invoked only for form-data)

The question we have is how does the Postman-Chrome works when using multipart/form-data or any other multipart; when Postman-Mac never works for any multipart content type (form-data, mixed ... etc).
Can you please help us with this dilemma?

**_If you can send us the difference in the (POST) calls between Postman-Chrome and Postman-Mac, it will be very helpful._**

**Comment by a85** [comment]
We recommend using the Postman native apps now as the Chrome apps are deprecated.
