### ISSUE TITLE
TextEncoder isn't usable in pre-request scripts in standalone Postman

### ISSUE THREAD

**Issue by benfowler** [a85/POSTMan-Chrome-Extension#2539]
Hi, 

I have run into an issue when attempting to make use of a certain standard Javascript class from the pre-request scripts in Postman.  The following snippet works in the legacy Postman plugin that shipped with Chrome (the latest available from the App Store), but does _not_ work at all in the standalone Mac version of Postman (the Electron-hosted one).

```javascript
var content = 'jolly jumbuck';
var enc = new TextEncoder('utf-8');
var len = (enc.encode(content)).length;
```

We get the following error:

    There was an error in evaluating the Pre-request Script:  ReferenceError TextEncoder is not defined

This, interestingly, works fine on the developer console in both cases. It just fails when you go to use it in a pre-request script.

Nothing is reported on either the DevTools or Postman console.

This is being tested against 4.9.1 of the Mac app.

**Comment by sdnts** [comment]
Hey @benfowler, the standalone Postman apps are built on top of [Postman Runtime](http://blog.getpostman.com/2016/06/14/introducing-postman-runtime-more-power-better-control/), which, unlike the Chrome App, sends requests using a Node.js sandbox. As such, it does not include every Javascript class, because they simply aren't always needed.
I'll add this as a feature request. It will help if you could provide an example use case so we can make an informed decision :D

**Comment by benfowler** [comment]
Hi @madebysid !

Our particular use case, is that we need the length of the UTF-8 encoded string, in bytes, in order to compute a message authentication code (HMAC) to do a call:

```var contentLength = (new TextEncoder('utf-8').encode(content)).length;```

Without this, we come unstuck very fast when processing payloads with multibyte characters...

Unfortunately for us, the code above worked fine in the Chrome version, which is on it's way out; we've just told our users that they ought to use the Mac version of Postman, which unfortunately doesn't. 

I've tried to work around the lack of `TextEncoder` inside the Node.js-sandboxed version of Postman, without success :(

**Comment by shamasis** [comment]
Can you not use Buffer APIs instead? Storing strings as buffers should also give you some useful set of APIs.

We will soon make changes that would shim node apis in chrome and then Buffer should work indistinguishably across all platforms.

**Comment by benfowler** [comment]
Doesn't appear to work for me at all within standalone Postman (or the Chrome one, for that matter), despite working fine off the Node REPL, sadly.

I tried both `Buffer.byteLength(str, enc)` as well as constructing the Buffer and then calling methods, no joy.

**Comment by benfowler** [comment]
Workaround:

```javascript
unescape(encodeURIComponent(content)).length ;
```

**Comment by shamasis** [comment]
Postman uses a controlled version of NodeJS execution VM. Please use `Buffer.byetLength` function to achieve the same result.

For example, `Buffer.byteLength('😎');` would return `4`.

**Comment by frokev** [comment]
You could also do:
```
const encoded = new Uint8Array(Buffer.from("test 😊"));
const length = encoded.length;
```
Which is equivalent to:
```
const encoded = (new TextEncoder()).encode("test 😊");
const length = encoded.length;

```
