### ISSUE TITLE
Standalone Mac App Is Not Handing Environment Variables Correctly

### ISSUE THREAD

**Issue by PhilipSharman** [a85/POSTMan-Chrome-Extension#2540]
Version/App Information:
 1. Postman Version: 4.9.1.
 2. App (Chrome app or Mac app): Mac app
 3. OS details: OS X 10.12.1
 4. Is the Interceptor on and enabled in the app: No.
 5. Did you encounter this recently, or has this bug always been there:  I'm pretty sure this is new behaviour.  I don't think it existed in approx. version 4.7.
 6. Expected behaviour: An environment variable, such as {{consumerkey}} in the OAuth 1.0 screen should be expanded in the cURL code generated.

Steps To Reproduce
1) On the "OAuth 1.0" screen, I have {{consumerkey}} in the Consumer Key field.

![image](https://cloud.githubusercontent.com/assets/209361/21066133/2523de2a-be21-11e6-905f-ba638b455240.png)

2) In my enviroment, I have "consumerkey" set to "123456".

![image](https://cloud.githubusercontent.com/assets/209361/21066186/6bf92328-be21-11e6-8c60-0e7ec789397b.png)

3) When I click "Code" to generate cURL code, I get this:

curl -X GET -H "Content-Type: application/x-www-form-urlencoded" -H "Authorization: OAuth oauth_consumer_key=\"**%7B%7Bconsumerkey%7D%7D**\",oauth_signature_method=\"HMAC-SHA1\",oauth_timestamp=\"1481320684\",oauth_nonce=\"xm0RXczhCmp\",oauth_version=\"1.0\",oauth_signature=\"oa%2BSEHiRvas%2Fvasr4ZHfmTY5au4%3D\"" -H "Cache-Control: no-cache" -H "Postman-Token: 17952920-60d4-f85e-f583-9181bae8286a" "https://example.com/"

The consumer key has been set to:
oauth_consumer_key=\"%7B%7Bconsumerkey%7D%7D\"

4) If I use the Chrome application, the cURL code is correct:

curl -X GET -H "Content-Type: application/x-www-form-urlencoded" -H "Authorization: OAuth oauth_consumer_key=\"**123456**\",oauth_signature_method=\"HMAC-SHA1\",oauth_timestamp=\"1481320684\",oauth_nonce=\"xm0RXczhCmp\",oauth_version=\"1.0\",oauth_signature=\"Qv8A4JydbWdm5ey4%2Fpx9steVgOc%3D\"" -H "Cache-Control: no-cache" -H "Postman-Token: 3df61a2f-9a71-a4b6-ede6-659099efacd5" "https://example.com/"

Thanks,
   Philip.

**Comment by rcrooks** [comment]
I'm seeing a similar issue with OAuth 2 -- almost certain it started with 4.9.1
Oddly enough, it still works for one of our APIs, but for others, all requests made through Postman or Postman generated curl return unauthorized.

Thanks,
Robert

**Comment by dvishniakov** [comment]
I have a 4.10.3 Postman app on Mac and it looks good there
