### ISSUE TITLE
Issue with auto-generating GUIDS for _postman_id

### ISSUE THREAD

**Issue by dforney14** [a85/POSTMan-Chrome-Extension#2541]
1. Postman Version: 4.9.1
 2. App (Chrome app or Mac app):  Native Windows App
 3. OS details:  Windows 7 Enterprise
 4. Is the Interceptor on and enabled in the app: No
 5. Did you encounter this recently, or has this bug always been there:  We believe this has always been there.
 6. Expected behavior:  We are hoping to be able to merge into our Enterprise-Hosted Source-Control System without conflicts created by new _postman_id's being generated when we import/export Postman collections
 7. Screenshots (if applicable)
![image](https://cloud.githubusercontent.com/assets/24485104/21067749/8c94e1c2-be2a-11e6-82eb-2f123c205443.png)

The comparison shows that Postman seems to be auto-generating new GUIDs for "_postman_id" and other "id" fields for request/reponses ran.

We are unfortunately unable to use your Sync feature due to security systems in place at our work so we are hoping you might have a suggestion or if we may request a feature be added to Postman.  What we are looking for is a setting to be integrated to not generate these new GUIDs or save them to the export json file as these typically result in conflicts that need to be resolved.

Any help or suggestions you may have are greatly appreciated!

Thank you
<!--

**Comment by sdnts** [comment]
@dforney14 The ID field is an internal field, and as such this is the expected behaviour. I'll add this as a feature request, though :)

**Comment by dforney14** [comment]
@madebysid  Thanks for the quick response!  I appreciate the feature request.

**Comment by vwxyzjn** [comment]
Is there any progress on this by any chance? Having to commit with thousands of lines of `_postman_id` changed every time we export the collection is not fun...

**Comment by remisbaima** [comment]
same issue here. I am using postman 6.2.3

**Comment by dcorking** [comment]
an explanation of the meaning of _postman_id would help users choose an appropriate workaround

**Comment by hfmm99** [comment]
Being able to keep versions of postman cases is very important, associate the changes to tickets, or so.  Please implement this feature for not regenerating the GUIDs on every export.  Thanks.

**Comment by hfmm99** [comment]
Also, why is this closed without any response?  This issue was reported four years ago, and it hasn't been fixed yet

**Comment by arlemi** [comment]
@hfmm99 The IDs are not regenerated on every export but on every import. If you're exporting the same collection multiple times you'll always see the same IDs. 

If you'd like to keep the same IDs, look into how you can collaborate within Postman instead of outside of the app: https://learning.postman.com/docs/postman/collaboration/collaboration-intro/

We also have a feature request for ID-less export that you may be interested in following: https://github.com/postmanlabs/postman-app-support/issues/2906
