### ISSUE TITLE
"Persist variables" in Runner of Windows standalone fails

### ISSUE THREAD

**Issue by Farzadd** [a85/POSTMan-Chrome-Extension#2542]
1. Postman Version: v4.9.1
 2. App (Chrome app or Mac app): Windows Standalone
 3. OS details: Windows 10 Pro (x64)
 4. Is the Interceptor on and enabled in the app: Not installed
 5. Did you encounter this recently, or has this bug always been there: always been present
 6. Expected behaviour: As the Chrome version does, environment variables should be persisted when the option is enabled. However no changes are made to the environment. Same script and test run work as expected when using the Chrome extension.
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app): N/A
 8. Screenshots (if applicable)

1. Run the collection runner with a collection that makes changes to the environment variables
2. Ensure the "Persist Variables" option is enabled
3. Check the environment variables's values/state for changes

**Comment by SamvelRaja** [comment]
Thanks for bringing this to our notice. We shall keep you updated in this thread on the update.

**Comment by sdnts** [comment]
@Farzadd This was fixed in our latest release (4.9.2). Can you try updating and verifying?

**Comment by Farzadd** [comment]
@madebysid Just verified and it worked as expected!

That's great! Thank you very much for the quick support.
