### ISSUE TITLE
Content-Type in Body section is reset after each crash

### ISSUE THREAD

**Issue by nikolayandr** [a85/POSTMan-Chrome-Extension#2544]
1. Postman Version:4.9.0
 2. App (Chrome app or Mac app):Chrome 53.0.2785.101
 3. OS details:linux / x86-64
 4. Is the Interceptor on and enabled in the app:yes
 5. Did you encounter this recently, or has this bug always been there: recently

**Comment by sdnts** [comment]
@nikolayandr Could you provide a little more background?
What do you mean by `crash`? Do you mean the request is reset or only the Content-Type header is lost?

More info would help me debug this  easier :)

**Comment by nikolayandr** [comment]
Hello. By crash I meant that postman process finishes his work suddenly. When I relaunch postman app, header isn't lost but when I go to section "Body" after crash, the section looks like this:
![after](https://cloud.githubusercontent.com/assets/4941456/21134889/78292242-c128-11e6-8e24-5602c91f8649.png)

Before a crash this section looked like this:
![before](https://cloud.githubusercontent.com/assets/4941456/21134843/4a3dbc30-c128-11e6-819d-4d95ec27dd49.png)

I noticed that postman began to crash when I began to use placeholders in body of requests. Now almost each second request crashes postman, also this very often occurs  when I'm switching between request tabs

**Comment by nikolayandr** [comment]
Hm, I can suggest that postman is crashed when many tabs are opened. In some moment I couldn't open any tabs, postman has been always finished his work suddenly. I closed all tabs and now everything is OK

**Comment by iagomls** [comment]
Same here.
In my case, even if the app doesn't crash, the body type is not kept.

**How to reproduce:**
1. Create a request with a different body type from default (like `application/json`).
2. Close the app.
3. Open it again.
4. Notice the current request is the same you made last time the app was opened. But the custom body type (`application/json`) was replaced by `text`.

It does not apply for collections or history.

OS: macOS Sierra 10.12.2.
Chrome version: 55.0.2
Postman version: 4.9.2

**Comment by GDuparquet** [comment]
Same as iagomelanias.

Juste saved a request in a custom collection. When I close and then launch postman again, the body type is set to "text". Even if the Content-type header is still set to "application/json".

OS : Windows 10
Chrome version : 55.0.2883.87
Postman version: 4.9.2

**Comment by sdnts** [comment]
@nikolayandr @GDuparquet We've fixed this internally, and will be rolling out a fix for this in an upcoming release. Will keep you informed here.

**Comment by prashantagarwal** [comment]
@nikolayandr @GDuparquet If you are still facing this issue feel free to reopen this issue.
