### ISSUE TITLE
Postman Runner : when using parameter substitution in the url, results are not shown

### ISSUE THREAD

**Issue by waynet3** [a85/POSTMan-Chrome-Extension#2546]
1. Postman Version: 4.9.1
 2. App (Chrome app or Mac app): Windows Standalone
 3. OS details: Windows 10 Pro (x64)
 4. Is the Interceptor on and enabled in the app: Not installed
 5. Did you encounter this recently, or has this bug always been there: Recently
 6. Expected behaviour: The results should appear in the Runner
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 8. Screenshots (if applicable)

Steps to reproduce the problem:

1. Create a collection that has a request that makes use of a required parameter
    Eg. https://www.google.com/maps/search/:field
2. Run the collection in the Runner
3. The Runner does not display the request results that makes use of the required parameter, or any requests results after it.
4. The "Run Summary", "Retry" and "New" buttons stop responding.

![image](https://cloud.githubusercontent.com/assets/23221841/21136687/42c8111a-c12f-11e6-8009-fa0fae662118.png)

![image](https://cloud.githubusercontent.com/assets/23221841/21136491/86ec9ed4-c12e-11e6-85a3-493b73c2eafe.png)

**Comment by vegetableman** [comment]
@waynet3 Thanks for reporting this issue 👍 . Will keep you posted on this thread.

**Comment by sdnts** [comment]
@waynet3 Do you see any errors in the DevTools console? (Ctrl + Shift + I)

**Comment by waynet3** [comment]
@madebysid No, there are no errors in the DevTools console

**Comment by sdnts** [comment]
@waynet3 I was able to reproduce this and a fix is on it's way. I'll keep you updated.

**Comment by sdnts** [comment]
@waynet3 Can you try updating to the latest version (4.9.3) and verify if you issue is fixed?

**Comment by waynet3** [comment]
@madebysid The issue seems to be resolved, thank you.
