### ISSUE TITLE
Allow large values in inputs (more than 0.5MB)

### ISSUE THREAD

**Issue by anupshah** [a85/POSTMan-Chrome-Extension#2547]
Hello,

I am using Postman to test sending large PDFs to my API (sent as Base64 encoded text). I am using variables to store different base64 encoded PDFs to vary my testing. However, I am finding some larger PDFs (more than ~0.5 MB) are not saving as variables successfully - they get truncated at 0.5MB.

Workaround: I can create duplicates and put those large PDFs in the request body manually rather than using environment variable substitution but it makes management harder (and the text editor is understandably slow if you need to modify some other data in the request).

 1. Postman Version: 4.9.0
 2. App (Chrome app or Mac app): Chrome App
 3. OS details: Windows 10 (fully updated)
 4. Is the Interceptor on and enabled in the app: No (not applicable here - I don't think)
 5. Did you encounter this recently, or has this bug always been there: Only noticed - it may have always been here, not sure
 6. Expected behaviour: Can add very large text to a global environment variable
 7. Console logs: None (not applicable)
 8. Screenshots (if applicable): see below

See attached zip file [globals.postman_globals.zip](https://github.com/postmanlabs/postman-app-support/files/648985/globals.postman_globals.zip). It is a backup of global variables.

I have modified it manually so that the text value is the correct base64encoded text of a PDF file. If you upload it, that text gets truncated.

Similarly if you create a new global variable (may apply to local ones too) and paste the large base64 encoded text and save it, you will see it is truncated if you open it again.

This screenshot shows the last variable where the value has been scrolled to the end.
![image](https://cloud.githubusercontent.com/assets/2446665/21141522/9b957dfe-c135-11e6-8464-1aa7a88df9a7.png)

The final text ends with "kVe5C" but if it had not been truncated it would have ended with "U9GDQo="

I think it is getting truncated at half a megabyte, 512KB

If so, would like to request the limit be increased (maybe configurable if there are challenges with this) or if this cannot be done due to some technical limitation maybe detect/indicate that pasted value has been truncated perhaps?

**Comment by madebysid** [comment]
@anupshah I'll investigate this. Will keep you updated here.

**Comment by sdnts** [comment]
@anupshah The maximum length of a string inside an input field is 524288 characters, which we do not override at any point. This might be causing the truncation that you observe. I'll add this as a feature request (to increase the maximum allowed limit in text fields)

**Comment by anupshah** [comment]
@madebysid Many thanks for that. Look forward to the feature update!

**Comment by a85** [comment]
This should be fixed now in versions 5.0+

**Comment by anupshah** [comment]
Hi. Finally got round to trying it out. Works great. Many thanks!

**Comment by zio-mitch** [comment]
A good idea could be to allow to store these base64 variables in external files.
Is there a way?

**Comment by networkinss** [comment]
> A good idea could be to allow to store these base64 variables in external files.
> Is there a way?

Indeed, that would be great, for example to read OAS3 yaml files from the filesystem.
Is it possible to import them with Javascript (into environment variable) somehow ?
