### ISSUE TITLE
Origin header is present in the POST request even no Origin header was specified

### ISSUE THREAD

**Issue by polomsky** [a85/POSTMan-Chrome-Extension#2548]
1. Postman Version: 4.9.0
 2. App (Chrome app or Mac app): Chromium 53.0.2785.143
 3. OS details: Ubuntu 16.04 (64bit)
 4. Is the Interceptor on and enabled in the app: tried both
 5. Did you encounter this recently, or has this bug always been there: unknown
 6. Expected behaviour: Origin header is not present in request when is not set

Send POST request to any domain. Origin header with `chrome-extension://...` is present in the request. I am aware of that this is behaviour caused by Chrome itself, but I expect that at least Interceptor can remove that header if is not specified.

**Comment by sdnts** [comment]
@polomsky The interceptor sends your request through Chrome, so that's where the extra header is coming from.
Can you try on of our [native apps](https://getpostman.com/apps) and check if you can reproduce this there?

**Comment by polomsky** [comment]
Native app for linux does not send Origin header.
There is unexpected header `Postman-Token` but it does not break anything.

**Comment by sdnts** [comment]
@polomsky `Postman-Token` is a custom header which you can use to track requests, it shouldn't break anything.
When using the interceptor, requests are actually made though Chrome (which is the primary use case for the Interceptor, so you can use cookies from the browser etc.).

The native apps, however, make requests using a NodeJS environment, so they don't have this problem :)

Closing this, as there is little we can do about this. Let me know if I misunderstood.
