### ISSUE TITLE
[Feature] - Ability to run xmlhttprequests in the pre-request script

### ISSUE THREAD

**Issue by tariqghalib** [a85/POSTMan-Chrome-Extension#2549]
**Feature Request**
The ability to run the xmlhttprequest in the pre-request script is a gem. This actually enables us to make each test independent of each other and an easy way to grab pre-request setup (values, variables, even DB queries)

Currently if we run this we get an **error**:
There was an error in evaluating the Pre-request Script:  TypeError xmlHttp.open is not a function

**Version/App Information:**
 1. Postman Version: 4.9.1
 2. App (Chrome app or Mac app): Windows
 3. OS details: Windows 64 professional
 4. Is the Interceptor on and enabled in the app: No
 5. Did you encounter this recently, or has this bug always been there: Yes few months ago
 6. Expected behaviour: Should have the ability to run the xhr from pre-request scripts

**Steps to reproduce the problem:**
function httpGet(theUrl)
{
    var xmlHttp = new XMLHttpRequest();
    xmlHttp.open( "GET", theUrl, false ); // false for synchronous request
    xmlHttp.send( null );
    return xmlHttp.responseText;
}

var response = httpGet( postman.getEnvironmentVariable("apihost") + "/" + postman.getEnvironmentVariable("base") + "/" + postman.getEnvironmentVariable("public") + "/xyz/" + postman.getEnvironmentVariable("abc") + "/xyz/" + postman.getEnvironmentVariable("myData") );

console.log(response);

**Comment by JohnArrowwood** [comment]
+1

**Comment by vegetableman** [comment]
@tariqghalib @JohnArrowwood  Using `xmlhttprequest` on the pre-request scripts is not the recommended or supported way to go about getting data for requests. Instead, you could create a collection and chain the requests, such that the required data is fetched from a request run in an order above the current request.

Related doc : http://blog.getpostman.com/2016/03/23/conditional-workflows-in-postman/

**Comment by cadaniel** [comment]
+1

I need to support RSA-SHA512 signatures in my requests. Currently I have python scripts to generate data to be imported in the runner. This model is just getting unsupportable.

**Comment by abhijitkane** [comment]
@cadaniel @JohnArrowwood @tariqghalib Postman v5.2+ has support for async scripts. Postman will wait for all callbacks to return (or hit the global timeout limit) before executing the next request.
