### ISSUE TITLE
Display {{variable}} value in History / Display request url in app

### ISSUE THREAD

**Issue by duepayer** [a85/POSTMan-Chrome-Extension#255]
It would be great if there was an option to display the {{variable}} value in the History url field. For example, if the request was sent with {{host}}/version/item/info.json, the History section would display "http://prod.host.com/version/item/info.json". This would be helpful for debugging purposes as it is impossible to know what environment the request was set to at the time of execution without it. After reading through past issues I noticed that this was the original functionality but was changed to only display the {{variable}} in the url field - https://github.com/a85/POSTMan-Chrome-Extension/issues/73. I'm still not sure what the use case is for only seeing the variable but it would be really helpful if we had the option to view the full request url somewhere in the app.

**Comment by jimpudar** [comment]
I still don't think we have a good solution to this issue. I have a request which uses dynamic variables (e.g. `{{$randomInt}}`) and as far as I can tell there is no way for me to tell what random int got sent with a particular request by observing the history.

Furthermore, the current concept of environments have both initial and current values, suggesting that variables may have different values now than they did when the request was made.

If I click the "Code" button and view the request as cURL or Python, I can see that the dynamic variable is replaced by the _current_ version of that variable, not the value that was actually sent.

Hopefully I'm missing something here?
