### ISSUE TITLE
Postman for Windows fails to follow 307 redirect correctly

### ISSUE THREAD

**Issue by sschlesier** [a85/POSTMan-Chrome-Extension#2550]
Postman for windows 4.9.0/4.9.1 on windows 10, no interceptor

In postman for windows
Ensure automatically follow redirects is on
Attempt to GET the following URL: https://paymentdatastoretest.iqmetrix.net/ping
Result: Could not get any response....
Expected: follow the 307 and get a valid response

Accessing the same URL in the postman chrome plugin follows the redirect and returns a response as expected.

**Comment by sdnts** [comment]
@sschlesier I'm pretty sure you checked this, but is the Follow Redirects switch in your Settings (wrench icon on the top right) turned on in the native app?

**Comment by sschlesier** [comment]
Yes, follow redirects is enabled.  

Here are a couple sample fiddler captures with and without follow redirects (rename them to .saz).
[with follow redirect.zip](https://github.com/postmanlabs/postman-app-support/files/652600/with.follow.redirect.zip)
[no follow redirect.zip](https://github.com/postmanlabs/postman-app-support/files/652599/no.follow.redirect.zip)

Have you tried to repro the issue?  We have reliably reproduced this on 3 different machines on 3 different networks.  It's always broken on the windows native app, and always works on the chrome browser app.

**Comment by sdnts** [comment]
@sschlesier I was able to reproduce this with a 307 status code for some servers (not all, though). We'll fix this in an upcoming release and keep you updated here.

**Comment by adrian7** [comment]
I have the same issue on Mac.

**Comment by tariqghalib** [comment]
+1 for windows app for 302 redirects

**Comment by sschlesier** [comment]
@madebysid do you know what the cause is?  Is there something missing/extra in some responses?

**Comment by samlehman** [comment]
+1 for mac too, 4.10.7

**Comment by prashantagarwal** [comment]
Guys this is already fixed in current Postman version. If you are still seeing this feel free to reopen this issue.

**Comment by shetaksroc** [comment]
Hi Guys,
Still I am facing this issue with the latest version of postman.
