### ISSUE TITLE
Where is JavaScript API documented?

### ISSUE THREAD

**Issue by Ernesto-Maserati-CH** [a85/POSTMan-Chrome-Extension#2552]
Where can I find a full JavaScript API documentation of Postman?

I want to see which built in variables I can use, what are their functions and arguments and so on.

What I mean is a good old API documentation, not information spread across dozens of tutorials, blogs etc.
I am using Postman 4.9.1 Windows App.

**Comment by czardoz** [comment]
@Ernesto-Maserati-CH https://www.getpostman.com/docs/sandbox
