### ISSUE TITLE
Verifying if request body is equal to response body, how?

### ISSUE THREAD

**Issue by Ernesto-Maserati-CH** [a85/POSTMan-Chrome-Extension#2553]
I want to verify in the tests section that the response body is equal like the request body.

After a while I found the variables which I potentially could use for it:

responseBody === request.data

But that does not work if I use variables in the request body. The response body contains the values, so the comparison results in "not equal".

What I need is the effective request send by Postman. Is there another variable for that, since request.data does not work for my use case as I wrote above?

By the way, such a basic and useful validation, it would be very nice to have a snippet for them in Postman.

I use Postman 4.9.1, Windows App.

**Comment by vegetableman** [comment]
@Ernesto-Maserati-CH You could use `postman.getEnvironmentVariable` to get the data from variables. I think we could add the related snippet for the same on the snippets section.
Also, you could refer this doc for the api supported on the scripts :- https://www.getpostman.com/docs/sandbox.

**Comment by Ernesto-Maserati-CH** [comment]
I don't think that works vegetableman. I have no clue what you mean, really. Did you understand my problem?

As I said, the variable "request.data" returns the request template with variables like {{guid}} inside it. So if you compare that with responseBody it is not equal. I am looking for a built in variable with the effective request data (after the variables in it have been evaluated). Something like this.

**Comment by vegetableman** [comment]
@Ernesto-Maserati-CH Ah... I see. 

Variables, as of now, are not resolved for the request object on test scripts. For now, you could use something like, for instance, `postman.getEnvironmentVariable(request.data[0].value.replace(/\{\{|\}\}/g, ''))`.

It's definitely not elegant, but will get back to you with more details.

**Comment by vegetableman** [comment]
@Ernesto-Maserati-CH It's part of the roadmap. There is no ETA as of yet.

**Comment by Ernesto-Maserati-CH** [comment]
Ok, I see. Would be really nice to be able to access request data after it has been populated with the actual variable values. Thanks for working on it and providing me a workaround!

**Comment by sturlath** [comment]
When will this be available? I´m trying to post random data with {{$randomInt}} and would like to have access to the variable in the test.

`{
  "amount": {{$randomInt}},
  "currency": "ISK"
}`

And then something easy like 
`var a = postman.getEnvironmentVariable("amount");
console.log("Amount:  " + a);`

I´m going to look at what you proposed @Ernesto-Maserati-CH to try to access the request body. I hope it works. Else I would love for some alternative to doing this if you can think up anything. Am I maybe doing this backwards?

**Comment by vegetableman** [comment]
@sturlath @Ernesto-Maserati-CH You could update to the latest version and access the values directly using `request.data`. Let me know if it works.

**Comment by xiaobeiying** [comment]
@vegetableman I have a problem when using `request.data`.
`var iContent = request.data["i"]`, the script worked great in Postman Sandbox, but the same script in Postman APP, its return is `undefined`.
Why???

**Comment by xiaobeiying** [comment]
My problem have been resloved. @kunagpal Thanks.

> The issue here is that `request.data` is an object in the Chrome app, but is an array in the native app. You'll have to adjust your logic to work with arrays instead of objects.
https://postmancommunity.slack.com/archives/D37KCC05T/p1490171896263414
