### ISSUE TITLE
How can I get the input parameters inside testscripts?

### ISSUE THREAD

**Issue by mohamedmubarish-s-19801** [a85/POSTMan-Chrome-Extension#2558]
I am trying to do input validation ( whether the input and output parameter values are equal) in postman. For example, if I am sending payload as {"name":"test"} and if I am getting response as {"name" : "test"}, I need to check the key "name" in response is same as payload (i.e) test, dynamically. for that I need to get input parameters (query and payload) inside testscripts. How can i get the input parameters inside testscripts?

Thanks in Advance!

**Comment by Farzadd** [comment]
You can retrieve the request object in test scripts and parse the body (see the snippets for JSON parsing) to retrieve your variables.

The `request.data` variable is what you are looking for.

More info:
https://www.getpostman.com/docs/sandbox#requestresponse-related-properties

**Comment by vegetableman** [comment]
@Farzadd 👍  😀

**Comment by Charmee2811** [comment]
can you please help me how to retrieve response object from input file.
I am not able to do that in test scripts..

My requirement is I have to login from 10 different users and validate user Role in response for each user
