### ISSUE TITLE
Remove share link from getpostman.com

### ISSUE THREAD

**Issue by giver** [a85/POSTMan-Chrome-Extension#256]
How can I remove shared link from getpostman.com?

**Comment by freak4pc** [comment]
Is this still planned? I shared a link and would like to delete it since it contains some sensitive data...

Thanks :)

**Comment by shamasis** [comment]
IMHO, not really. It's quite difficult to allow deletion of an anonymously shared collection. Any ideas/suggestion would be cool though.

In case it is not anonymously uploaded, you can definitely update the URL with a blank collection and we are working on better management of the URL when you're logged in.

**Comment by freak4pc** [comment]
That would force me to delete my collection ... I don't see the exactly problem. A third "destructive" button on this screen should be added. "Delete URL" ... that would just destroy the file on your storage after a warning prompt. What do you think on that solution ? 

![83f582f4-11b6-4ec6-8ef4-58c74d1f8ff1](https://cloud.githubusercontent.com/assets/605076/12080050/4b242534-b257-11e5-8a4b-901901a21624.jpg)

**Comment by abhijitkane** [comment]
@freak4pc If you were signed in when you uploaded the collection, you can click your username (on the top-right corner of the Postman window) > My collections. Here, you should see an entry for this collection which you should be able to delete.

**Comment by freak4pc** [comment]
Oh cool :) That's exactly what I was looking for. 
Maybe adding this button in the aforementioned location would be an improvement?

Thank you!

**Comment by abhijitkane** [comment]
Yep..we've added this to our usability roadmap and will try to take this up soon.

**Comment by ruslansokolov** [comment]
@abhijitkane Has this been implemented? I've deleted a shared collection, but it's still accessible via the URL.

**Comment by abhijitkane** [comment]
@ruslansokolov If you were signed in when you uploaded the collection, you can click your username (on the top-right corner of the Postman window) > My collections. Here, you should see an entry for this collection which you should be able to delete.

**Comment by ruslansokolov** [comment]
Like I said, I have deleted the collection. It does not show up under My Collections. However, if I hit that URL, it still returns the JSON with collection data. It's been 4 days and it's still available.

**Comment by abhijitkane** [comment]
@ruslansokolov Can you share the collection link here or send an email to help@getpostman.com? We'll manually delete the link.

**Comment by finwe200** [comment]
I inadvertently published a link and I desperately want to delete it.  On the Browser page I click on Delete Link but nothing happens.  Any help will be greatly appreciated.

**Comment by sdnts** [comment]
@finwe200 Just go to your public collection docs and click on the top-right dropdown that says `Publish` and select `Unpublish`.

**Comment by finwe200** [comment]
Sorry, I'm not finding that drop-down.  Is this from Postman App (Chrome) or the Collections webpage (https://app.getpostman.com/dashboard/collections/links)?

**Comment by sdnts** [comment]
@finwe200 By publishing a link, I'm thinking you mean you published your collection. In that case, you can open up your app, and find the published collection in the sidebar. Then click on the little arrow next to the collection, and in the drawer that opens up, click on `View Docs`. It'll take you to the website, where you should be able to see the dropdown.

**Comment by finwe200** [comment]
Thank you very much for the prompt replies.  I did that but I only see a Publish button and not a drop-down.   Also clicking on _Delete Link_ does nothing.

## ![postmancollectionspage](https://cloud.githubusercontent.com/assets/8620210/19118646/ed92ece4-8ad1-11e6-8d7d-ffe0f86e0db9.PNG)

![collectionlinks](https://cloud.githubusercontent.com/assets/8620210/19118696/14664e74-8ad2-11e6-93f6-f2fd1d6e5927.PNG)

**Comment by sdnts** [comment]
@finwe200 In that case, your collection hasn't been published :)
I must have misunderstood then. What do you mean when you say you published your link?

**Comment by godfrzero** [comment]
@finwe200 @madebysid I'm checking this out. Looks like we broke the `Delete Link` action in the last push. I'll fix this ASAP and let you guys know 😅

**Comment by finwe200** [comment]
So I am not going mad.  I look forward to the fix.

**Comment by godfrzero** [comment]
@finwe200 The fix is live, and `Delete Link` seems to be working fine now. Let me know if you're still having trouble, and sorry this took so long.

**Comment by finwe200** [comment]
Hi Vivek,

I tested this today and it works.  Many thanks for fixing this.

Jon

**Comment by athulmurali** [comment]
Also, clicking the publish button again will redirect you to the page where you can unpublish the docs

**Comment by owaiskhalid95** [comment]
wf

**Comment by owaiskhalid95** [comment]
Hey all
i want to get my own personal access link not the one showing document.postaman is there any way for this?

**Comment by 2020-abhilash** [comment]
Is there any way to delete a public link that was shared and we do not have access to the account that it was shared from?
