### ISSUE TITLE
Attaching files in Collection Runner is not possible

### ISSUE THREAD

**Issue by stamtesteng** [a85/POSTMan-Chrome-Extension#2560]
**Environment**
Postman 4.9.0
win / x86-32
Chrome 54.0.2840.99
Windows 7

**Issue**
1. If I understand correctly, there is a limitation in Postman where you cannot define a specific path and file name for a file that you want to upload, in both options of request body 'form data' or 'binary', as it is documented here: 
https://www.getpostman.com/docs/requests 
"you would have to reattach a file if you are loading a request through the history or the collection."
Is this going to available with any workaround?

2. An alternative way to overcome the above mentioned limitation may be to allow the path and the file names to be stored in environment or global parameters. But this seems that is not supported as weel. 

Since I am trying to create a test suite as dynamic as possible.
I create some data in my test environment using the API mechanism I have to test.
Then I am trying to import some binary files in my application using the POST method.
When I am doing this process manually (meaning that in the body of the request I select the binary option and I select the file I want to post) everything is ok.
I am trying now to automate this process by using a dynamic parameter. To be more precise, I want to define the name of the binary file and the path that it is stored in the disk during runtime. And this is because the binary file is created by another Post request that is executed in a previous step of my Test Suite.
For other cases that I use raw data option in the body of the request, I have used environment parameters that I update their values in a prerequest script or inside the Test tab (script executed after the actual request).

**Comment by sdnts** [comment]
@stamtesteng 
1. This is something we don't do currently. On the Chrome App, this simply isn't possible, as Chrome does not give us the actual path of the file, just a fake one. On the native apps, we do not store file references because these are usually system specific, which causes more problems than it solves.

2. I'll add this as a feature request :)

**Comment by abhijitkane** [comment]
@stamtesteng To send files with requests while running a collection, you'll need to use Newman - http://blog.getpostman.com/2014/11/15/using-newman-to-run-collections-with-file-post-requests/. Supporting file uploads through Postman's runner isn't on our immediate roadmap.

**Comment by AndriiStepura** [comment]
Does anybody know some workarounds for this?
