### ISSUE TITLE
Postman and Newman integration issue: rawModeData in GET requests should always be emtpy

### ISSUE THREAD

**Issue by stamtesteng** [a85/POSTMan-Chrome-Extension#2561]
**Versions used**
Postman 4.9.0
win / x86-32
Chrome 54.0.2840.99
Newman 1.1.2
Windows 7

**Issue**
Consider the case that a user in Postman duplicates (or make a Save As to) a POST (or a PUT or any other method that includes a body-raw data) request.
Then user goes to the new request created (the duplicate) and make changes. If user change the method used in the request to be a method that does not include request body (e.g. GET), then the Body tab is correctly disabled from selection. User saves the request.
After this, user exports the collection.

In the collection exported, the specific request (GET) includes the body of the request of the original (POST) request (the one before the transformation of the method from POST to GET) inside the property “rawModeData” of the json file of the collection. This has the following result. 

**Run in Postman** 
In case the collection is imported in Postman and runs through Postman or Postman runner, everything runs correctly.

**Run through Newman**
In case the same collection runs through Newman, then the specific will fail due to a “SyntaxError in test-script”.

**Expected Result**
The Test Suite should run correctly in both Postman and Newman.

It seems that in this case Postman should clear the content of “rawModeData” in case is used one of the methods that have no request body :
-	Get
-	Copy
-	Head
-	Purge
-	Unlock

**Comment by sdnts** [comment]
@stamtesteng That's a great observation. The reason the request body is saved with the collection is to enable us to restore bodies when the method is changed back. However, this body is not actually sent from the Postman App.
It's weird that Newman throws a `SyntaxError in test script` though. Could you open an issue over at the [Newman Issue Tracker](https://github.com/postmanlabs/newman)? This makes it easy for us to segregate issues.

Feel free to reopen this if you face issues with the app :)

**Comment by stamtesteng** [comment]
Thank you @madebysid. As you can see I opened a ticket in newman as you proposed:
https://github.com/postmanlabs/newman/issues/821
