### ISSUE TITLE
Write to responseBody object in a test? Or a Test Console window for test output?

### ISSUE THREAD

**Issue by rich-blockley-bg** [a85/POSTMan-Chrome-Extension#2563]
Version 4.9.1 (4.9.1)
Mac app - mac version 10.11.6
No interceptor
---

Can I (I don't think I can, but I might be doing it wrong) write to the responseBody object in a Test?

A compelling reason this might be useful:

For a certain GET request in my system, I get back so much JSON data that Cmd-F does not cut it. However I could easily remove a few nodes from the in-memory response and what I want would be easily viewable. It'd not be the actual response any more, but modified in memory. This would be very useful for pruning off data that my testers don't want to have to trawl through.

Alternatively, some kind of output window from a Test would be nice. Then I can make up some JSON based on my responseBody and put it into this Test Output window. What do you think?

Rich

**Comment by SamvelRaja** [comment]
@rich-blockley-bg 
I hope our postman console will help you in viewing the partial manupulated data you have. All you need to do  the console.log(partialData) from the test Scripts.

Adding a GIF for your use case, Kindly let me know if i miss something.

http://blog.getpostman.com/2016/08/26/the-postman-console/
https://www.getpostman.com/docs/errors

![loginconsole](https://cloud.githubusercontent.com/assets/5114052/21317535/8980013e-c62b-11e6-823b-62139184933a.gif)

**Comment by worrel** [comment]
How do you actually open the console? I'm on Postman 4.9.2 Mac App, and the suggested key sequence of cmd-alt-c doesn't do anything?

**Comment by sdnts** [comment]
@worrel I'm on v4.9.3 on the native Mac App, and the Console opens up using the shortcuts for me. You can head over to the View menu on the top and select Postman Console too. If you don't see the View menu, you might be on the Chrome App (they're visually similar). You can check this by opening up Settings (wrench icon on the top right), and switching to the About tab.

**Comment by worrel** [comment]
@madebysid thanks, i downloaded the 4.9.3 zip & ran that and it works - I was indeed on the Chrome App, which has now been banished :-)
