### ISSUE TITLE
Enviroment variables don't work in Header values.

### ISSUE THREAD

**Issue by GregPK** [a85/POSTMan-Chrome-Extension#2564]
1. Postman Version: 4.9.2
 2. App (Chrome app or Mac app): Chrome 53.0.2785.143
 3. OS details: linux / x86-64
 4. Is the Interceptor on and enabled in the app: Yes
 5. Did you encounter this recently, or has this bug always been there: First time user
 6. Expected behaviour: To Use enviroment variable name in header value
 7. Console logs: [logs.txt](https://github.com/postmanlabs/postman-app-support/files/655821/logs.txt)
 8. Screenshots (if applicable)
- Recorded video of the problem [header-var-not-working.zip](https://github.com/postmanlabs/postman-app-support/files/655823/header-var-not-working.zip)

Since a variable working in the Header value is explicitly mentioned [here](http://blog.getpostman.com/2014/02/20/using-variables-inside-postman-and-collection-runner/) I assume this is a bug.

Rundown of the video:
- I have a `{{auth_token}}` var that I have set in the enviroment
- I put it into the value of the header, the request does not work
- To show that the problems doesn't lie in the value itself I then copy it from the enviroment value variable preview into the Header value field
- The request works as expected.

**Comment by sdnts** [comment]
Hey @GregPK, when you define an environment variable, you do not need to include the double curly braces in it's name like you have. You can just call it `auth_token` and use it. 
However, when using it, you include the `{{}}` to tell the app that you're referring to an environment variable.

So, in essence, you would create a new environment variable called `auth_token`, and give it a value. Then, in your `Header` tab, you would type `Authorization` as the name and `{{auth_token}}` as the value. That should work.

Feel free to reopen if it doesn't :)

**Comment by GregPK** [comment]
No idea how I missed that. Thanks!

**Comment by ZeeshanAhmadKhalil** [comment]
@madebysid  im using `{{token}}` in header but i am getting `{{token}} string` in the console instead of its value
