### ISSUE TITLE
Garbled Response (Incorrect encoding)

### ISSUE THREAD

**Issue by 1nfinite9** [a85/POSTMan-Chrome-Extension#2567]
I'm using an API that returns data in Japanese encoding (Shift-JIS). Previously, this data was automatically recognized as Shift-JIS and displayed properly but now it's showing up as garbled text.

 1. Postman Version: 4.9.2
 2. App (Chrome app or Mac app): Mac app
 3. OS details: macOS Sierra 10.12.2
 4. Is the Interceptor on and enabled in the app: No
 5. Did you encounter this recently, or has this bug always been there: since a few versions back
 6. Expected behaviour: Encoding is automatically detected and converted accordingly
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 8. Screenshots

![screen shot 2016-12-16 at 14 31 25](https://cloud.githubusercontent.com/assets/4265044/21252707/5292fd48-c39c-11e6-988f-11338f10c129.png)

**Comment by SamvelRaja** [comment]
Thanks for bringing this to our notice, we fixed this in our internal build. We shall let you know once it has been released.

Also, possible duplicated of #2502

**Comment by 1nfinite9** [comment]
Thanks for the **fast** reply. Looking forward to the next release.
