### ISSUE TITLE
No response when opening runner

### ISSUE THREAD

**Issue by fanchongcn** [a85/POSTMan-Chrome-Extension#2568]
1. Postman Version:4.9.2
 2. App (Chrome app or Mac app):Mac app
 3. OS details:mac OS 10.12.2
 4. Is the Interceptor on and enabled in the app:
 5. Did you encounter this recently, or has this bug always been there: this bug always been there
 6. Expected behaviour:I want to use runner
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):

runner.js:153251 Error: Unknown format of run(…)importRun @ runner.js:153251
runner.js:145453 Notification System not initialized_show @ runner.js:145453
runner.js:69636 Uncaught Error Uncaught TypeError: Cannot read property 'toLowerCase' of undefined file:///Applications/Postman.app/Contents/Resources/app/js/runner.js 147623 36 TypeError: Cannot read property 'toLowerCase' of undefined(…)(anonymous function) @ runner.js:69636
runner.js:147623 Uncaught TypeError: Cannot read property 'toLowerCase' of undefined
runner.js:69636 Uncaught Error Uncaught Error: Minified exception occurred; use the non-minified dev environment for the full error message and additional helpful warnings. file:///Applications/Postman.app/Contents/Resources/app/js/common.js 1029 6 Error: Minified exception occurred; use the non-minified dev environment for the full error message and additional helpful warnings.(…)(anonymous function) @ runner.js:69636
common.js:1029 Uncaught Error: Minified exception occurred; use the non-minified dev environment for the full error message and additional helpful warnings.

 8. Screenshots (if applicable)

<img width="1257" alt="qq20161216-132721 2x" src="https://cloud.githubusercontent.com/assets/1079492/21252650/7e75efa0-c393-11e6-8b38-21fd3e946891.png">

Upgrade Postman from 4.8.3 to 4.9.2

1) Open Postman

2) Click on button 'Runner' on the left-higher conner of the screen to Open Runner.

**Comment by alexgalkin** [comment]
+1
Have the same issue

**Comment by alexgalkin** [comment]
Guys, not sure how application was released with such blocker issue. It make it fully unusable. Tests cannot be run at all using new version of the app.

**Comment by sdnts** [comment]
@fanchongcn @alexgalkin This seems to happen when some test runs get corrupted. We have a fix ready, it'll be out early next week. Will keep you posted.

**Comment by alexgalkin** [comment]
@madebysid thanks for the update. Note sure what you mean by "some test runs get corrupted" - collection is executed just fine using newman. Only Postman UI has the issue with Runner.

**Comment by LouWii** [comment]
Same issue here. Hope it'll get resolved soon :)

**Comment by sdnts** [comment]
@fanchongcn @alexgalkin @LouWii Can you guys try updating to the latest version (4.9.3) and ceck if your issue is resolved?

**Comment by alexgalkin** [comment]
@madebysid it works for me now (after upgrade). Thanks.
