### ISSUE TITLE
Granular sharing

### ISSUE THREAD

**Issue by ferronrsmith** [a85/POSTMan-Chrome-Extension#2570]
Is there any plans to support granular sharing ? There are parts of my API that I would like to share with my team, but necessarily make public.

**Comment by sdnts** [comment]
@ferronrsmith When you share a collection, it gets shared with your team only. No one else can read. To make it public, you have to explicitly Publish your collection.

Do let me know if this is what you want, or if I misunderstood.

**Comment by ferronrsmith** [comment]
I think you misunderstood the question. Granular sharing/publish meaning..

If i have a collection of 

[A, B, C]

C <-- may be a private folder within my API that contains internal endpoints. When I share this, I might share it with the internal team, but when I publish I don't want customers to see it.

Currently the only way to do this is just to create to separate collections, one public-facing & internal.

**Comment by sdnts** [comment]
Ah, that's not possible right now. You'll have to create separate collection as of now. I'll add this as a feature request, though :)

**Comment by a85** [comment]
@ferronrsmith We had a discussion here and unfortunately for the time being, the abstraction that you can share right now would have to be a collection. I'd recommend splitting the collection and manage sharing settings at a collection level.
