### ISSUE TITLE
postman can't post JSON to mysql

### ISSUE THREAD

**Issue by Tskyone** [a85/POSTMan-Chrome-Extension#2571]
I follow the book named sails.jsessentials to develop REST API using sails.js. I used Postman to send JSON to a mysql database. Here are the screenshots:
![Uploading QQ截图20161218224142.png…]()
![qq 20161218224208](https://cloud.githubusercontent.com/assets/24636050/21294252/775056e8-c573-11e6-806a-b2396aa7b563.png)
In the book, the JSON data "email" and "message" should appear in the Body frame below, before "createdAt", "updatedAt" and "id", which were created by sql automatically.
Did I miss something?

**Comment by Tskyone** [comment]
![qq 20161218224142](https://cloud.githubusercontent.com/assets/24636050/21294284/43abf008-c574-11e6-8872-a983e067f618.png)

This is the first screenshot, if the previous one can not show up.

**Comment by sdnts** [comment]
@Tskyone This looks like the behaviour of your server. Can you try making a request to `https://echo.getpostman.com/post` and see if you data is POSTed correctly?
If yes, then to solve your issue, you should contact the person who wrote the server, as it probably is programmed behaviour, and we do not have control over it :)

Feel free to reopen if I misunderstood.

**Comment by Tskyone** [comment]
@madebysid Seems like It worked when posted to the site you mentioned. This is what I got when clicked Send:
![aaa](https://cloud.githubusercontent.com/assets/24636050/21375252/3ded8984-c767-11e6-99a0-80028c3f410b.png)
So it means data can be POSTed correctly and there is something wrong with the server(I made it with Sails.js)?
I will check it, thank you sir :)
