### ISSUE TITLE
Usability concern with Manage Environments 

### ISSUE THREAD

**Issue by S33G** [a85/POSTMan-Chrome-Extension#2573]
Version 4.9.2 (4.9.2)
Mac App
OS X EL Capitan 10.11.6 (15G31)

![screen shot 2016-12-19 at 9 20 09 am](https://cloud.githubusercontent.com/assets/655807/21307270/abfdbd82-c5cc-11e6-9c06-72810ab1f24d.png)

This is a fairly small thing and subjective thing, but I noticed a few members of my team struggling with this one.

In order to edit environment variables, the user is required to click the title of the environment, which feels almost like a secondary piece of functionality, whereas share is very prominent.

It would be really cool to see a edit button introduced here.

What do you guys think?

**Comment by vkaegis** [comment]
Hey @charj-it, thanks for pointing this out! Definitely make sense, we'll have a look at how any explicit edit action affects any navigation flows. Will let you know as soon as any change goes out!

**Comment by jimmic** [comment]
@charj-it totally agree with this. nice one.

**Comment by S33G** [comment]
No problem guys. I really enjoy using Postman as part of my day to day API work, so suggesting little things like this just make it that little bit better.

I'll keep my eyes out for more 👍

**Comment by giridharvc7** [comment]
This is now fixed in app version 8. 

<img width="1392" alt="Screenshot 2021-02-18 at 12 55 54 PM" src="https://user-images.githubusercontent.com/1040583/108320439-cec06a00-71e8-11eb-88b4-e029fcb4d374.png">
