### ISSUE TITLE
Having Rest api's for \ in Postman Pro to maintain Postman Collections

### ISSUE THREAD

**Issue by jvkaam** [a85/POSTMan-Chrome-Extension#2576]
It would be fun to have the ability to be able to maintain your postman collections through api's.

**Comment by sdnts** [comment]
@jvkaam Aha, you should check out our [Postman Pro API](https://api.getpostman.com/).

You could then set up collections to manage collections. 😛

**Comment by jvkaam** [comment]
I should have known. Top! Good reason tot start the Pro version.
