### ISSUE TITLE
After updating to 4.9.x: Character "+" in URL query parameter encoded as '%20' while expected '%2B'.

### ISSUE THREAD

**Issue by vgorloff** [a85/POSTMan-Chrome-Extension#2579]
1. Postman Version: 4.9.3
 2. App (Chrome app or Mac app): 4.9.3
 3. OS details: macOS 10.12.1 (16B2555)
 4. Is the Interceptor on and enabled in the app: No
 5. Did you encounter this recently, or has this bug always been there: **After updating** to 4.9.x from 4.8.x
 6. Expected behaviour: URL parameter `foo+bar-xyz@gmail.com` encoded as  `foo%2Bbar-xyz@gmail.com`
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app): None
 8. Screenshots (if applicable): None

Since updating to 4.9.x character `+` in URL query parameter encoded as `%20`.

Request: `https://example.com/api/customer/login/?email=foo+bar-xyz@gmail.com`
Generated code snippet (cURL):  
`curl --request GET --url 'https://example.com/api/customer/login/?email=foo%20bar-xyz%40gmail.com'`

Manually escaping "+" sign does not help:
Request: `https://example.com/api/customer/login/?email=foo%2Bbar-xyz@gmail.com`
Generated code snippet (cURL):   
`curl --request GET --url 'https://example.com/api/customer/login/?email=foo%252Bbar-xyz%40gmail.com'`

Thank you!

**Comment by numaanashraf** [comment]
@vgorloff Thanks for reporting. We are looking into this and will keep you posted here.

**Comment by vgorloff** [comment]
Oh. Seems it is a duplicate of #2517. And related to #2538.

**Comment by robertkuhar** [comment]
This is happening to me and its kind-of a big deal.  Is Postman incapable of dealing with URL encoded parameters?

**Comment by SamvelRaja** [comment]
@vgorloff @robertkuhar The issue has been fixed in our latest canary([4.9.4-canary.1](https://dl.pstmn.io/download/latest/osx?channel=canary)) release,
can you guys switch to that version an check the same?
On additional note we are using the whatwg's [url parser algorithm](https://url.spec.whatwg.org/#parsers).

**Comment by vgorloff** [comment]
Thank you!

canary(4.9.4-canary.1) still has an issue.
Here is GET url:

`https://www.example.com/api/customer/login/?email=test+ios-default@xyz.com&password=somePass`

Here what "Code -> Shell cURL" generates:

```
curl --request GET \
  --url 'https://www.example.com/api/customer/login/?email=test%20ios-default%40xyz.com&password=somePass' \
  --header 'cache-control: no-cache' \
  --header 'postman-token: 6f8f7edf-f8ef-d052-00ec-d7ca6eb33f9d'
```

But expected:

```
curl --request GET \
  --url 'https://www.example.com/api/customer/login/?email=test%2Bios-default%40xyz.com&password=somePass' \
  --header 'cache-control: no-cache' \
  --header 'postman-token: 6f8f7edf-f8ef-d052-00ec-d7ca6eb33f9d'
```

So, character "+" in URL query parameter still encoded as '%20' while expected '%2B'.

**Comment by vgorloff** [comment]
When i'm trying to login to my server with account which has symbol"+" in e-mail (like `test+ios-default@example.com` the server still returns me authorisation error. So, the build canary(4.9.4-canary.1) still generate example code "Code -> Shell cURL" with mistake as well as encode with mistake URL before executing network request. 

While Postman version 4.8.3 working as expected.

**Comment by SamvelRaja** [comment]
@vgorloff Thanks for your time in testing it out, will update the thread once it is fixed.

**Comment by SamvelRaja** [comment]
@vgorloff 
Let me just put up the things which are to be sorted out in this issue. 

When we generate the cUrl code (shell -> cUrl)

1. In query params '+' needs to be encoded to %2B instead of %20 - This is the expected behavior as + has a special meaning of (space) in query params which needs to encoded as %20 (space). 
[source](https://web.archive.org/web/20151218094722/http://blog.lunatech.com/2009/02/03/what-every-web-developer-must-know-about-url-encoding#Thereservedcharactersaredifferentforeachpart)

2. double encoding, that is %2B has been converted to %252B - This will be fixed in the next release.

If you need to send '+' to your server, you need to provide the encoded value  %2B, which would be decoded as '+' in your server.

Kindly let me know if i miss any.

**Comment by vgorloff** [comment]
Thank you @SamvelRaja !

>1. In query params '+' needs to be encoded to %2B instead of %20 ...

Sure. In query params "+" needs to encoded as "%20" (space).  What about "Bulk edit mode"?
Should we use "%2B" instead of "+" in "Bulk edit mode"? (see attachments)

[Example when "+" used](http://i.imgur.com/WH8LIeK.png)
[Example when "%2B" used](http://i.imgur.com/NoehKhX.png)

**Comment by SamvelRaja** [comment]
@vgorloff Thanks for the screenshot.
Yes, you need to use %2B.

Note: The issue 2 of double encoding still happens making it to %252B when you generate the shell->cURL, this will be fixed and released in the canary channel tomorrow.

**Comment by Npscholar** [comment]
@SamvelRaja Thanks for working on this @vgorloff thanks for raising this. Where can I get the canary build or is it more advisable to downgrade to the last working version (what version is that?)

**Comment by vgorloff** [comment]
@Serotonin7 Last working version 4.8.3.
Seems this version is not available for Download from official website.
By the luck I found it on one of office laptops .)

**Comment by SamvelRaja** [comment]
@vgorloff @Serotonin7 the latest 4.10.2 app has the fix for double encoding happening for %2B present in the query param.

**Comment by vgorloff** [comment]
Hello,

I checked version 4.10.2. Here is results:

- When in "Bulk Edit" mode query parameter defined as "+" (user+test@example.com).
   Then request sent as " " (user test@example.com). Expected.

- When in "Bulk Edit" mode query parameter defined as "%2B" (user%2Btest@example.com).
   Then request sent as "+" (user+test@example.com). Expected.

Thank you!

**Comment by sridi** [comment]
still have the problem with postman 10.13.5
