### ISSUE TITLE
Feature request - Predefined parameters when open new tab

### ISSUE THREAD

**Issue by kolyamba123** [a85/POSTMan-Chrome-Extension#2580]
Version/App Information:
 1. Postman Version: v4.9.3
 2. App (Chrome app or Mac app): Postman for Windows win32 6.1.7601 / x64
 3. OS details: Win 7 x64

When i open a new tab, i should always put headers, URL, arguments, etc. For example, for the header, i can set presets, but whatever to use it I should make at least 3 clicks (go to the form header, click the "Presets" and click on the right). 
It would be much easier if when you open a new tab it has been set by default headers, URL, QS, attributes, etc.

**Comment by sdnts** [comment]
@kolyamba123 New tabs are essentially ways to start afresh. They behave much like browser tabs.

If you find yourself repeating the headers etc. for every new request, you could save the request to a collection, and then duplicate it. Then you can open up the duplicated request and change only a small part. That should save you some time :)

**Comment by kolyamba123** [comment]
@madebysid I have many requests in collection, but it is much easier to tap "+" button, than find request and dublicate it. Moreover, often i do not need to save the query, so the duplication is unnecessary. As a result, I have to do a lot of extra activities. It is a pity that I could not find a response from you :/
