### ISSUE TITLE
[Feature] Use further documentation capability directly in Postman by adding comments 

### ISSUE THREAD

**Issue by Korayem** [a85/POSTMan-Chrome-Extension#2581]
Would love to see a way to add comments beside each API or attribute in a body.

Also ability to save server response as expected sample for frontend team to answer the timeless question of "what does response look like?"

This way, we can create a documentation of our APIs to be shared between our backend and frontend devs

**Comment by sdnts** [comment]
@Korayem You can have descriptions for each request inside a collection. To do this, just hover over a request, click on the three dots to the right, and select `Edit`. Then type in your description (in Markdown) in the Description field of the modal that opens up.
This should help you explain each attribute of the request body (and more, perhaps) to developers.

As for sample responses, for now, you just include a code block inside your description, but we've been working on a more elegant solution to this. I'll keep you updated here. :)

**Comment by Korayem** [comment]
Wow never noticed that before. But it needs to show up in the API details
screen too.

In addition to that, attribute level description is also important to
easily communicate, for instance, which attributes are optional. It needs
to be accessible directly where we manage body attributes, don't you think?

Keep up the amazing work. You guys are building an indispensable tool.

 Wed, Dec 21, 2016 at 10:46 AM Siddhant Sinha <notifications@github.com>
wrote:

**Comment by a85** [comment]
Available in Postman 5.0+. Parameter descriptions + request + folder + collection level descriptions with tables should let you add any form of docs. Check out api.getpostman.com for a reference.
