### ISSUE TITLE
Collection Runner ignores "ignored" form-data keys

### ISSUE THREAD

**Issue by gsirin** [a85/POSTMan-Chrome-Extension#2582]
- Postman Version 4.9.3 for Windows (win32 10.0.14393 / x64)
- Interceptor disabled

Some of my test kept failing because of the following (maybe) bug.

Steps to reproduce the problem:

1. Create a new Request, select the Body-Tab and add some form-data fields and populate the keys and values with some sample text
2. Disable one form-data row by unchecking the checkbox in the very front
3. Open the Runner and run the test
4. Open the "Request Body" Dialog by clicken on the title of the request
5. I can see the disabled form-data field due it is passed to the API :( 

Screenshot attached
![2016-12-21 14_33_26-postman](https://cloud.githubusercontent.com/assets/3208391/21391176/c126381e-c78a-11e6-8975-5198cb8b89a6.png)

Thank you! Awesome tool!

**Comment by sdnts** [comment]
@gsirin Thanks for letting us know. We're working on a fix for this. I'll let you know when it is out.

**Comment by a85** [comment]
@madebysid Is this going in 4.10.3?

**Comment by sdnts** [comment]
@a85 Yep.

**Comment by pastudan** [comment]
Just confirming this is still an issue on the latest version since it sounded like 4.10.3 was where this fix might land?

I'm still seeing the bug on:

> Postman for Mac
> Version 4.10.7
> OS X 15.6.0 / x64

![image](https://cloud.githubusercontent.com/assets/1296162/25569807/334c97b4-2dd2-11e7-9de2-b4baaf3fa851.png)

**Comment by pastudan** [comment]
@a85 any update / eta on this? thanks!

**Comment by a85** [comment]
@pastudan We are releasing 4.11 soon to fix this.

**Comment by numaanashraf** [comment]
@pastudan v4.11.0 is out now and it includes the fix for this.

**Comment by pastudan** [comment]
@numaanashraf can confirm this is fixed, thanks!
