### ISSUE TITLE
Quickly Duplicate Requests

### ISSUE THREAD

**Issue by MarkSonghurst** [a85/POSTMan-Chrome-Extension#2583]
I need to efficiently duplicate a number of core Requests between folders/collections.
To ensure a sane test environment for each of my API test cases within Postman, I must issue these Requests:
1. Login as Admin
2. Create a new user with a random email address
3. Verify that user
4. etc...

As it seems I cannot 'link' to an already defined Request from another folder or collection, I need to duplicate these core Requests between each of my test cases. 
This laboriously requires me to select the ... button on each Request, select Duplicate, drag the copy to the correct folder (or collection) and then rename it so it's not called "...copy" any more. As you can imagine, this gets very tedious, very fast!

Allow me to select one or more Requests (using GUI standard ctrl or shift) and then drag copies of them into the relevant folder/collection, where they are duplicated using the original name - only apply the "...copy" name only if they already exist at the destination with the same name.

Version/App Information:
 1. v4.9.3
 2. Linux
 3. CentOS 7

**Comment by a85** [comment]
Thanks for the request. We are working on exactly these things and we'll starting rolling out new versions of Postman across all platforms pretty soon.:)

**Comment by ghost** [comment]
+1
It would be awesome to be able to point to requests outside current directory or to their duplicates in `postman.setNextRequest()` too.

**Comment by a85** [comment]
There are "Duplicate" and "Rename" keyboard shortcuts in the sidebar that should make this super easy.

**Comment by SumithraSomu** [comment]
@a85 
Hey Abhinav,

Seems like this request was made  in 2016 and now in 2019 December I am using **Current Version: v7.12.0.** But I am not able to select multiple requests to duplicate them.  Is there any possibility for us to get such a feature. 

Thank you in advance.
Sumithra Somu.
