### ISSUE TITLE
Could not get any response in Windows, Linux, Mac App for 204, 304 HTTP response without "Body" but with "Header" (Content-Type →application/json; charset=UTF-8)

### ISSUE THREAD

**Issue by Dmytro-Komaryst** [a85/POSTMan-Chrome-Extension#2585]
Version/App Information:

 1. Postman Version: v4.9.3
 2. App (Chrome app or Mac app): Windows App
 3. OS details: Windows 8.1
 4. Is the Interceptor on and enabled in the app: Yes
 5. Did you encounter this recently, or has this bug always been there: Always
 6. Expected behavior: Windows App shouldn't fall if in the response with Header (Content-Type →application/json; charset=UTF-8)  absent the body 
 7. Console logs: http://joxi.ru/bmo0wWyHLpZW2y
 8. Screenshots (if applicable)
For Windows app: http://joxi.ru/l2ZlyNzU5bywrJ
For Chrome app: http://joxi.ru/LmG5zEOs8xN1Al , http://joxi.ru/krDjEOaikPyD2p

Bug description:
Error message "Could not get any response" in Windows App for GET and PATCH request who send in response (Status: 204 No Content or 304 Not modified) without "Body" but with "Headers" - (Content-Type →application/json; charset=UTF-8).

In my application, it is very difficult to remove this header (Content-Type →application/json; charset=UTF-8) from the GET and PATCH response.
Could you fix it on its side (You do not need to handle the response body when Status: 204 No Content or 304 Not modified and response with Header (Content-Type →application/json; charset=UTF-8), like you do in Crome App)

This bug not reproduced: 
1) for the Crome App  ( http://joxi.ru/LmG5zEOs8xN1Al , http://joxi.ru/krDjEOaikPyD2p).
2) for the 204, 304 HTTP response without body and without Header (Content-Type →application/json; charset=UTF-8) https://echo.getpostman.com/status/204

Dmitry
d.komarist@gmail.com

**Comment by Dmytro-Komaryst** [comment]
response from the network panel in the chrome app dev tools http://joxi.ru/KAxbwz0c9MVQm8

**Comment by Dmytro-Komaryst** [comment]
Hello,
I've reproduced this bug in the Node.js

My script:
var request = require("request");
require('request-debug')(request);
request.get('https://bo-qa-02.icecat.biz/restful/v2/multimedia/21021?access_key=XXXXXXXXXXXXXXXX&session_type=rest', function (error, response, body) {
  console.log(error);
  console.log(response);
  console.log(body);
});

Node.js error response:
C:\nodejs\Console2>node C:\nodejs\Console2\test\request.js
{ request:
   { debugId: 1,
     uri: 'https://bo-qa-02.icecat.biz/restful/v2/multimedia/21021?access_key=XXXXXXXXXXXXXXXX&session_type=rest',
     method: 'GET',
     headers: { host: 'bo-qa-02.icecat.biz' } } }
{ Error: Parse Error
    at Error (native)
    at TLSSocket.socketOnData (_http_client.js:363:20)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at TLSSocket.Readable.push (_stream_readable.js:134:10)
    at TLSWrap.onread (net.js:548:20) bytesParsed: 282, code: 'HPE_INVALID_CONSTANT' }
undefined
undefined

{ response:
   { debugId: 1,
     headers:
      { server: 'nginx',
        date: 'Wed, 04 Jan 2017 11:19:36 GMT',
        'content-type': 'application/json; charset=UTF-8',
        connection: 'close',
        expires: 'Thu, 19 Nov 1981 08:52:00 GMT',
        'cache-control': 'no-store, no-cache, must-revalidate, post-check=0, pre-check=0',
        pragma: 'no-cache' },
     statusCode: 204,
     body: '' } }

**Comment by sdnts** [comment]
@Dmytro-Komaryst Thanks for the detailed report & apologies on the delay. We're looking into this.

**Comment by ghost** [comment]
Same problem in Postman for Windows Version 4.9.3 win32 10.0.14393 / x64 .

**Comment by ghost** [comment]
Still not working in v4.10.3 , 204 returns a error .

**Comment by Dmytro-Komaryst** [comment]
So, I found the way how to bypass that problem.
I use "Fiddler 4" before postman, like a proxy. 
And use substitution of the SSL certificate on the "Fiddler SSL certificate" http://joxi.ru/D2P3ZDNcVox7m3
Switch-off SSL certificate verification in the Postman http://joxi.ru/5mdvE7KcyOVQA1
After that Postman works correctly http://joxi.ru/KAxbwz0cPEjPm8

Without that bypass, I get error http://joxi.ru/gmvbwqMcPEE0ma

I think that bug in postman-request.js
I sent support request few times but that error not fixed :(

**Comment by rdohms** [comment]
I seem to have the same issue, but only in newman, not in postman. My Postman monitors are also broken, no proxy in play, not sure what to do?

I get this error in DevTools:
```
Object {bytesParsed: 215, code: "HPE_INVALID_CONSTANT", name: "Error", message: "Parse Error", stack: "Error: Error: Parse Error↵    at Error (native)↵    at Socket.socketOnData (_http_client.js:361:20)↵    at emitOne (events.js:96:13)↵    at Socket.emit (events.js:188:7)↵    at readableAddChunk (_stream_readable.js:176:18)↵    at Socket.Readable.push (_stream_readable.js:134:10)↵    at TCP.onread (net.js:543:20)"}
```

**Comment by Dmytro-Komaryst** [comment]
I found the bug in my application. Fixed bug and postman start work correct.
The bug in my application consisted in that:
For 304 and 204 responses I returned not empty body (body contained one symbol (')) and with header (Content-Type →application/json; charset=UTF-8) this caused falling the Postman.

**Comment by Dmytro-Komaryst** [comment]
Try clearing body before sending the response to your application, maybe it helps you.

**Comment by rdohms** [comment]
As far as we can tell, we have no Content-Type headers and nothing in the body.

**Comment by rdohms** [comment]
```
HTTP/1.1 304 Not Modified
Date: Thu, 20 Jul 2017 10:39:05 GMT
Connection: keep-alive
Server: Apache/2.4.6 (CentOS)
ETag: "12722c70-107e-4663-9b80-077c587cf882_1"
Cache-Control: public
```

**Comment by Dmytro-Komaryst** [comment]
Try this request for checking Postman
https://postman-echo.com/status/304

**Comment by Dmytro-Komaryst** [comment]
If this request works fine it's the same problem as at me
I also thought that in response I have an empty body.
And Chrome app Postman works fine (but native Postman win app is fall)

**Comment by Dmytro-Komaryst** [comment]
Native windows Postman app and Newman works on the lib request.js Node.js
Chrome Postman app - works on another principle (for this reason it works fine)

**Comment by rdohms** [comment]
So,

- https://postman-echo.com/status/304 works fine
- our endpoint does not really show anything in the body
- i'm on a mac with the native app but i can reproduce this in runner and postman monitors.

The server we see this on runs on a new ALB structure on AWS, that is the only difference we can see.

**Comment by Dmytro-Komaryst** [comment]
So, for my case (I use Yii framework for my application) helps next hook:
if 204 or 304 then clears the headers, cookies, content, body data, stream.
Maybe it's not your case, I don't know :)

**Comment by rdohms** [comment]
@madebysid any progress on the investigation on your side?

**Comment by pontifex** [comment]
@Dmytro-Komaryst I was hit by (almost?) exactly same issue as described by you. Same as in your case, problem was on my side. When I was doing curl request with -v resulted in ```Excess found in a non pipelined read: excess = 2 url = /api/test/123 (zero-length body)``` Fixed bug on my side and Postman is able now to handle request properly. What was misleading for me, executing curl without -v resulted in fully proper response and behavior (outside Postman), request was executed, response headers seemed to be fine. Conclusion: double check your requests!

**Comment by elizabeththecountess666** [comment]
URL https://postman-echo.com/get?test=123.

**Comment by A-Sandwich** [comment]
Hit this issue as well in the Linux client. Any progress on this issue?

**Comment by numaanashraf** [comment]
This is a verified bug and we are tracking this at #2418. Closing this as duplicate.
