### ISSUE TITLE
Suggestion: Previewing markdown description

### ISSUE THREAD

**Issue by loicginoux** [a85/POSTMan-Chrome-Extension#2588]
Hi, 
I find that describing an endpoint could be improved, here are my suggestions:

- Having like github issues, a preview panel for description text. 
- having a wider textarea

At the moment, writing directly in the textarea is painful, I have to first write my text on a markdown editor to check syntax, and then copy/paste it on the postman edition popup.
It would be quicker and easier to being able directly to edit and see clearly what we are writing on the box

![screenshot 2016-12-23 10 42 39](https://cloud.githubusercontent.com/assets/824936/21451079/955b2f32-c8fc-11e6-9045-179432077d45.png)

**Comment by sdnts** [comment]
@loicginoux That's a great idea, adding this as a enhancement request :D
We're working on something very similar, so I'll let you know when this is out!

**Comment by a85** [comment]
@vkaegis @bhawna2109 We should do a prototype design. With the in-tab editors for Markdown, we can think about this.

**Comment by jooleeanh** [comment]
I believe this is solved ? @madebysid

**Comment by Cazaimi** [comment]
@loicginoux , we've exposed this feature on the Web dashboard. Simply head to the private documentation of a Collection by clicking the 'View more' button in the app. Please check the GIF below:

![Mar-20-2020 17-54-20](https://user-images.githubusercontent.com/13660453/77163376-f2a89680-6ad3-11ea-9927-d8116e2af3fc.gif)

I hope this solves your problem 🙂

**Comment by loicginoux** [comment]
Perfect thanks 👏👏
