### ISSUE TITLE
Could not get any response / Broken pipe

### ISSUE THREAD

**Issue by karthikvrao** [a85/POSTMan-Chrome-Extension#2589]
Version/App Information:

 1. Postman Version: 4.9.1/4.9.3
 2. App (Chrome app or Mac app): Mac app
 3. OS details: OS X 10.11.1
 4. Is the Interceptor on and enabled in the app: Yes but Not applicable
 5. Did you encounter this recently, or has this bug always been there: Yes, recently after the latest update.
 6. Expected behaviour: Requests should return response with body and status code.
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 8. Screenshots (if applicable)
![postman mac app](https://cloud.githubusercontent.com/assets/20852493/21461072/267da87e-c974-11e6-99df-f24ff7a9fde0.png)
![postman chrome app](https://cloud.githubusercontent.com/assets/20852493/21461074/2c0c5150-c974-11e6-85d7-f67e7b68323f.png)

Steps to reproduce the problem:
Enter any url and click on 'Send'.

Bug description:
The message saying "Could not get any response" is displayed for all requests, be it on local host or public urls like https://www.google.co.in/. It causes my local dev server to show a 'Broken pipe' message in the terminal. This issue has come up as soon as I updated the Postman app. All requests used to work perfectly fine but none work now. I have not modified any setting from the defaults. I spent hours of my productive hours trying to figure out the solution but I could not. Thankfully, I still had the Chrome app installed which still works just fine for all requests.

I can get by with the Chorme app for now but I like the Postman Mac app better. Please fix it soon.

PS: If this is not a bug, please let me know of a solution to fix this issue. I am puzzled how it is suddenly not working.

**Comment by vegetableman** [comment]
@karthikvrao Thanks for reporting this issue 👍 . Could you open the devtools on the Mac app and check if there are any errors on the console? You could refer: https://www.getpostman.com/docs/errors

**Comment by karthikvrao** [comment]
I don't see any errors. I have attached the screenshots of both Console tab and Network tab of DevTools. Let me know if you need anything else.
![postman devtools console tab](https://cloud.githubusercontent.com/assets/20852493/21465265/85b02c8e-c9c1-11e6-9ab1-d402c3657d72.png)
![postman devtools network tab](https://cloud.githubusercontent.com/assets/20852493/21465267/8a149ab2-c9c1-11e6-8a95-57944d732e75.png)

**Comment by vegetableman** [comment]
@karthikvrao Could you send a request and check if there are any errors on the devtools console after sending it?

And If there are no errors, could you open the `Postman Console` and share the screenshot of the console for the request being sent on this thread? (`View` -> `Show Postman Console` or `Cmd + Alt + C`)?

**Comment by karthikvrao** [comment]
I forgot to mention it but actually I had checked the Postman Console last time itself while was checking DevTools and found it to be blank.

**Comment by vegetableman** [comment]
@karthikvrao I guess you misunderstood. Could you keep the devtools open, while the request is being sent? and check if the are any errors on the devtools console and `Postman Console`?

**Comment by karthikvrao** [comment]
Ok, I did that and found that DevTools console had no errors but Postman Console had an error(screenshot attached).
![postman console error](https://cloud.githubusercontent.com/assets/20852493/21485263/90e7a274-cbc6-11e6-82b8-d46697bfdb20.png)

**Comment by jfneis** [comment]
Has anyone found a solution for this? My Postman just started behaving the same way. I'm not sure it's not application fault, but I have no other clue right now instead of Postman.

**Comment by sdnts** [comment]
@jfneis Is the Chrome app working fine for you too?

**Comment by jfneis** [comment]
@madebysid yeap, just fine! it was a silent bug in our API, everything is OK right now!
