### ISSUE TITLE
macOS 10.12.2 app - empty blue button

### ISSUE THREAD

**Issue by snypelife** [a85/POSTMan-Chrome-Extension#2590]
Lowest of priorities, I know. It doesn't even bother me. I just happened to notice it and not see anything in the issue tracker. Perhaps its nothing/intentional? 

1. Postman Version: **4.9.3**
2. Mac app
3. macOS **10.12.2**
4. Interceptor is **off**
5. First time I've noticed.
6. For there not to be a empty blue button/element
7. and 8.
![image](https://cloud.githubusercontent.com/assets/1965406/21464444/93f37b6a-c94a-11e6-9834-bd19d67483f7.png)

Steps to reproduce the problem:
1. Open app. That's pretty much it. It seems to occur only when you haven't actually made a request yet.

For the record, I wasn't hovering on the DOM element in DevTools, so it's not the DevTools highlighting feature. It's there before you even open DevTools.

**Comment by sdnts** [comment]
Hey @snypelife, this is supposed to be an empty state for a new tab, so this is indeed intentional :D
