### ISSUE TITLE
How to reset/restore the example Postman collections?

### ISSUE THREAD

**Issue by automatix** [a85/POSTMan-Chrome-Extension#2595]
Hello!

I created a new GET request in Postman and accidentally saved it as one of the example Postman requests (and so overwrote it). How can I restore the standard request set?

I removed Postman and installed it again, hoping, that then I would get the example collections again. But it hasn't worked. Now I cannot access the example requests at all (I only see the collections and the total number of the requests in them):

![postman-echo](https://cloud.githubusercontent.com/assets/440005/21483262/7aefccea-cb7f-11e6-9539-baa5bc76df25.png)

Context: Postman v4.9.3 on Windows 7.

**Comment by sdnts** [comment]
@automatix If you go to https://echo.getpostman.com/ and click on Run In Postman on the top-right, you should be able to re-import the sample requests

**Comment by automatix** [comment]
Perfect, thank you very much!
