### ISSUE TITLE
empty environment variables are lost

### ISSUE THREAD

**Issue by sshanks24** [a85/POSTMan-Chrome-Extension#2596]
1. Postman Version: 
4.9.3
 2. App (Chrome app or Mac app): 
Mac app
 3. OS details:
 El Capitan (10.11.6)
 4. Is the Interceptor on and enabled in the app:
 No
 5. Did you encounter this recently, or has this bug always been there:
 Recently.  Guessing this was introduced with 4.9.3?
 6. Expected behaviour:
 Empty environment variables should be allowed

Steps to reproduce the problem:

1. Create an environment variable (e.g. empty_will_be_lost)
2. Do not set a value and update
![screen shot 2016-12-27 at 3 31 03 pm](https://cloud.githubusercontent.com/assets/263324/21507807/841ee434-cc49-11e6-8dff-f6db7acd6bc1.png)
3. Send a request with the environment that references the new empty variable
4. Observe that the empty variable is no longer in the environment.
![screen shot 2016-12-27 at 3 31 40 pm](https://cloud.githubusercontent.com/assets/263324/21507818/9b36c5d8-cc49-11e6-830f-a07b9fa60d9b.png)

We use empty variables quite a bit in our environment files to build out urls.  I haven't been able to find a decent workaround to this issue.  New behavior was introduced in a recent update as we have been using empty variables for a while.

**Comment by jvkaam** [comment]
Yes we encountered the same problem.. you could enter a space as a temporary workaround if that works for you but it should be fixed..

**Comment by sshanks24** [comment]
Unfortunately, the space workaround doesn't work for our use case.  We wind up with the spaces being passed in the url like: 
````
https://%20%20some.url.com
````

**Comment by sdnts** [comment]
Guys, this might be related to https://github.com/postmanlabs/postman-app-support/issues/2598, I'll investigate and let you know.

**Comment by tmack8001** [comment]
yes this is plaguing me as well as I have a "port" environment variable switch for all of my postman api requests that under certain circumstances is set to "" meaning use the protocols default value... have a work around that works, but this should be fixed.

**Comment by surfjedi** [comment]
+1

**Comment by whippet-rider** [comment]
+1

**Comment by sdnts** [comment]
Guys, 4.10.2 includes a fix for this. Can you try updating and verifying?

**Comment by whippet-rider** [comment]
was 4.10.2 only just released? I tried the check for updates this afternoon but nothing was available. Updating now, can let you know tomorrow. Thanks...

**Comment by whippet-rider** [comment]
Looks good to me @madebysid :) Much appreciated...

**Comment by tmack8001** [comment]
Will update when I get back to my Mac. If it does as promised i would be much appreciated!

**Comment by sdnts** [comment]
Closing this. Please let me know if it doesn't and I'll reopen this :)
