### ISSUE TITLE
when i edit an api with chinese in description , it's weird

### ISSUE THREAD

**Issue by scoful** [a85/POSTMan-Chrome-Extension#2600]
1. Postman Version: 4.9.2
 2. App (Chrome app or Mac app): Chrome 55.0.2883.87
 3. OS details: win 10
 4. Is the Interceptor on and enabled in the app: no
 5. Did you encounter this recently, or has this bug always been there: yes

when i edit an api with chinese in description , it's weird.
please try it.

**Comment by sdnts** [comment]
@scoful Could you give me a little more detail on what you weird behaviour you see?

**Comment by sdnts** [comment]
@scoful We made changes to the way chinese inputs are handled. Can you try updating and check if the behaviour is as expected?

**Comment by scoful** [comment]
@madebysid it's worked ! thanks very much!
