### ISSUE TITLE
setGlobalVariable with value 0 does not work

### ISSUE THREAD

**Issue by schmitti123** [a85/POSTMan-Chrome-Extension#2603]
1. Postman Version: 4.9.3
 2. App (Chrome app or Mac app): Mac app
 3. OS details: macOS 10.10.2 (sierra)

If i try to set a global variable with value  0 (zero) it does not work.
The variable will not be created if I run the requests manually.

In the Postman-Runner it does work.

The code is like that:

`postman.setGlobalVariable("tmpVersion", 0); `

**Comment by SamvelRaja** [comment]
@schmitti123 Tracked here #2598
