### ISSUE TITLE
[Bug] - Postman Windows app cannot handle 302 redirects properly

### ISSUE THREAD

**Issue by tariqghalib** [a85/POSTMan-Chrome-Extension#2604]
**Description:**
During a sign in to a web app to retrieve the authentication Code, there are few redirects involved and postman windows app fails to preserve all query parameters during the redirects, while the postman chrome app can handle that properly.

**Version/App Information:**
 1. Postman Version: Version 4.9.3
 2. App (Chrome app or Mac app): Windows
 3. OS details: Windows Professional 64
 4. Is the Interceptor on and enabled in the app: N/A
 5. Did you encounter this recently, or has this bug always been there: Always been the case
 6. Expected behaviour: Postman app to handle 302 redirects properly by preserving the referrer location and get valid response back after all redirects
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app): 

**Steps to reproduce the problem:**
This happens when we have an api call that involves few 302 redirects in it. (Chrome app can handle it properly but native apps cant). Few steps are:
1. A GET call to get to the login page. During this call there's a resumePath thats generated. We store the resumePath as a variable.

2. A POST call to pass login credentials and resumePath along with it

3. The second call can be divided into 4 sections:
a. First a post call to login page by passing the login information and resumePath
b. A 302 redirect that passes this information back to the authentication server. This also contains a redirect URL.
c. Another 302 redirect that moves the authenticated user alongside a referrer location. This also contains few query string parameters (clurl, resumePath and a custom variable called cd) that build up the final call to retrieve the authentication code
d. A GET call to retrieve the auth Code from the redirectURI

4. I have built a nodejs app that does the above 4 steps. Now if we change the query string parameters during the 302 redirects (indirectly changing the referrer location where it needs to go after the 302) we get exactly same error that postman windows app is showing which is:
 Your login credentials could not be resolved.  Please try logging in again.

Above is happening because we do pass the right credentials but it fails to bring back the success authentication from the server after the 302 redirect.

**Comment by shevyf** [comment]
This has been an ongoing issue - according to the HTTP 1.1 RFC, the redirected requests should use the same method as the original, but Postman developers have commented that they believe it should be handled as a GET per that RFC. In fact, code 303 exists to ask for a different method, while 301 and 302 should use the same method.

```
Note: RFC 1945 and RFC 2068 specify that the client is not allowed
      to change the method on the redirected request.  However, most
      existing user agent implementations treat 302 as if it were a 303
      response, performing a GET on the Location field-value regardless
      of the original request method. The status codes 303 and 307 have
      been added for servers that wish to make unambiguously clear which
      kind of reaction is expected of the client.
```

from https://www.ietf.org/rfc/rfc2616.txt in the section on 302 codes.

**Comment by sdnts** [comment]
@shevyf We'll definitely look into this in more detail. Will keep you updated here.

**Comment by czardoz** [comment]
@shevyf We'd really like to follow the RFC. The problem however, is this: http://stackoverflow.com/questions/17605915/what-is-the-correct-behavior-expected-of-an-http-post-302-redirect-to-get

Basically, when browsers see a 302 to a `POST` request, they make a `GET` request to the URL specified in the `Location` header. A large number of Postman users expect it to behave in the same way as browsers do. In fact, with our native apps, we had to take special effort to retain this behavior. 

We could however add a setting to control this, @madebysid

**Comment by tariqghalib** [comment]
@madebysid @czardoz Any update on this guys. This currently doesnt work in the CLI runner (newman) as well. That breaks the nightly builds.

**Comment by mipsot** [comment]
I see POST -> GET redirects as single POST in Console window. It is discouragingly and hard to debugging. You can provide more information about all redirects.

I use Linux desktop client, last 4.10.7 version.

**Comment by prashantagarwal** [comment]
@tariqghalib Can you update to latest version of Postman app and verify if you are still seeing this issue.

**Comment by Thilaknath** [comment]
@prashantagarwal  I still have this issue, despite having the latest version postman.

Environment : Windows 10

A quick summary, I try to do a POST with the authentication headers and that is supposed to return me with a json response, But i don't receive any and instead being redirected to the login screen of the app. When i toggle off the Autoredirect, i get a 302 but the content is not rendered.

**Comment by azzimuth** [comment]
I'm having this issue as well. I try to call an API on http which should redirect to https but Postman just says `Could not get any response. There was an error connecting to XXX`. I see in Fiddler that the server returns 302 but somehow Postman cannot handle that. I'm running version 5.3.2.

**Comment by gmile** [comment]
We see the issue to. Unfortunately our tests fail due to this. @prashantagarwal would it be possible to have this as a configuration option?

We're using 5.6.0 canary.

**Comment by gmile** [comment]
We were able to get around the problem by "skipping" redirection, e.g. specifying https in the first place instead of http in postman requests.
