### ISSUE TITLE
Header Content-Type Field not updated when switching content type radio buttons

### ISSUE THREAD

**Issue by LuiSlacker** [a85/POSTMan-Chrome-Extension#2605]
**Version Info**

 1. Postman Version: 4.9.2
 2. App (Chrome app or Mac app): Chrome app
 3. OS details: macOS Sierra (10.12) OS X / x86-64
 4. Is the Interceptor on and enabled in the app: yes
 5. Did you encounter this recently, or has this bug always been there: always
 6. Expected behaviour: When selecting the  _x-www-form-urlencoded_ option for POST/PUT request within the body tab, a header filed _Content-Type:_  _x-www-form-urlencoded_ is added. This Header Field should be removed or updated when toggling another content-type option(radio button)

**Steps to reproduce the problem:**
* chose POST or PUT request
* change body's content type from _form-data_ to _x-www-form-urlencoded_ (clicking radio button)
* this adds a content type header of value _x-www-form-urlencoded_
* when you change the content-type back to something else (clicking radio buttons), the content-type header is neither removed nor updated, leaving it with the wrong value of _x-www-form-urlencoded_

**Comment by vegetableman** [comment]
@LuiSlacker Thanks for posting this issue 👍 . Let's keep the discussion on this thread https://github.com/postmanlabs/postman-app-support/issues/2366.
