### ISSUE TITLE
Window disappears when attempt to toggle off full screen 

### ISSUE THREAD

**Issue by zach-is-my-name** [a85/POSTMan-Chrome-Extension#2606]
1. Postman Version: 4.9.3
 2. App (Chrome app or Mac app): Guess what? Postman also has a Windows version!
 3. OS details: 14393.576
 4. Is the Interceptor on and enabled in the app:  Don't know
 5. Did you encounter this recently, or has this bug always been there: Recently
 6. Expected behavior: Ability to not be in full screen
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app): Give me a Windows instruction and I'd be glad to
 8. Screenshots (if applicable)

**Comment by sdnts** [comment]
@zach-is-my-name Are you working on the native Windows app? Could you provide a little more detail on what problem you're facing?

**Comment by wla2000** [comment]
I believe this same issue has occurred with me.  Postman fills the whole screen and I cannot resize it.  I can close with alt-f4 or File->Exit, but I cannot see the taskbar and I cannot move the application by dragging on the title bar.  
I am using the native Windows postman app,  v4.10.3 on Windows 10 (10.0.14393 Build 14393).  I have uploaded a screen shot.
![image](https://cloud.githubusercontent.com/assets/10872270/24052240/280b7468-0b0b-11e7-9358-05aa0dfcdd8f.png)
If there is any additional information you need please let me know.

**Comment by trs79** [comment]
Pressing F11 to toggle full screen fixed the issue for me

**Comment by ahmetmert** [comment]
Full screen mode is very annoying. I must have mistakenly pushed f11 key and had the same issue with wla2000. I though it was a bug or something

**Comment by ankurdengla** [comment]
@wla2000 We went through your comment and it seems you entered full screen mode on Postman app. The behaviour you reported is as expected on the Windows platform. The full-screen mode on Windows by default hides the task bar and the title bar on all apps. They can be recovered by pressing F11 to exit full-screen mode. Also, resizing the window or moving it is disabled in full-screen mode

**Comment by ankurdengla** [comment]
@zach-is-my-name The exact issue you are facing is unclear to us from your comment. Are you still facing this issue? Can you share the steps for reproducing this issue?

**Comment by numaanashraf** [comment]
With only the information that is currently in the issue, we don't have enough information to take action or verify whether this is a valid issue. I'm going to close this but don't hesitate to reach out if you are still facing this issue.
