### ISSUE TITLE
Missing WebDAV Methods

### ISSUE THREAD

**Issue by om3rcitak** [a85/POSTMan-Chrome-Extension#2607]
Missing WebDAV Methods

1. MOVE
2. MKCOL
3. PROPFIND
4. PROPATCH

details: http://www.webdav.org/specs/rfc2518.html

**Comment by sdnts** [comment]
@Om3rCitak While we really appreciate the pull request, the actual app code isn't the one you see here. This repository is meant only to be a place to organize issues.

Custom methods is on our roadmap, and we're tracking this here: https://github.com/postmanlabs/postman-app-support/issues/1710.
