### ISSUE TITLE
Send Referer using Interceptor

### ISSUE THREAD

**Issue by mattusey-zimperium** [a85/POSTMan-Chrome-Extension#2612]
1. Postman Version: 4.9.2
 2. App (Chrome app or Mac app):Chrome 55.0.2883.95
 3. OS details:OS X 10.11.6
 4. Is the Interceptor on and enabled in the app: yes
 5. Did you encounter this recently, or has this bug always been there: first time checking
 6. Expected behaviour: When using interceptor, expect Referer header to be sent out with API calls

Steps: Turn on Interceptor in Postman, navigate to page in Chrome web app, then send API from Postman.  I do see the proper cookies being sent out in the API call, but I don't see the Referer header.  If I turn off Interceptor, I get a Session Authentication error from my API, so I know Postman is sending the auth cookie.  When I turn on the dev console for Postman, I do see that Cookie, but there is no Referer header.

Am I missing a step to get Postman/Interceptor to send the restricted headers, or is this a bug?

**Comment by abhijitkane** [comment]
@mattusey-zimperium I'm able to send the Referer header through Postman once the Interceptor is enabled. Can you try with the latest versions of Postman (5.2.0) and Interceptor (0.2.23)?

**Comment by jxnu-liguobin** [comment]
Postman Interceptor 0.2.27
Postman 5.5.4
can't get Referer from request, how i can do?
I use curl -H "Referer:/realtime" that can work successfullly,but don't in postman Headers
