### ISSUE TITLE
Postman Collection Runner  Not able To save the responses for all the iteration

### ISSUE THREAD

**Issue by rest17** [a85/POSTMan-Chrome-Extension#2613]
1. Postman Version: 4.9.3 (Free)
 2. App (Chrome app or Mac app): Postman For Mac
 3. OS details: OS X 15.6.0/x64
 4. Is the Interceptor on and enabled in the app: No
 5. Did you encounter this recently, or has this bug always been there: Recently Started Using Postman and then seeing it.
 6. Expected behaviour: 

When the collection runner test result are saved , it should save the request and response for all the iteration. When running the single request response can be saved using send and download , but through collection its not possible. Is it because of free version I am using.

To reproduce . Try to run a post request from collection for 100 iteration. And Export the collection result . Check the json if is has the request and response also in it.

**Comment by sdnts** [comment]
@rest17 The app has no restrictions even if you are not a part of any team.
The requests and responses logged in the Collection Runner are meant to be logs, and as such, they are not exported to prevent security concerns.
Closing this. Feel free to reopen if I misunderstood.
