### ISSUE TITLE
Need Information regarding the concurrent request in Postman

### ISSUE THREAD

**Issue by rest17** [a85/POSTMan-Chrome-Extension#2614]
I running collection for a request with iteration count set to 50.

Are all the 50 request running parallelly or sequentially.

**Comment by sdnts** [comment]
@rest17 As of now, a run is sequential. So, when you start a run with 50 iterations, it'll run sequentially.
I'm guessing you're trying to do some sort of load testing, which isn't possible right now. This is something we're considering, but there isn't an ETA as of now.
