### ISSUE TITLE
Different response time : original server response time is different than postman rest call response time

### ISSUE THREAD

**Issue by rajcybage** [a85/POSTMan-Chrome-Extension#2615]
Version/App Information:

 1. Postman Version: 4.9.2
 2. App (Chrome app or Mac app): Chrome App Chrome 55.0.2883.87
 3. OS details: win / x86-64
 4. Is the Interceptor on and enabled in the app: yes
 5. Did you encounter this recently, or has this bug always been there: always been there
 6. Expected behaviour: same response time
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):

 8. Screenshots (if applicable)

Postman response time:568 ms, 625ms

![image](https://cloud.githubusercontent.com/assets/3119321/21739688/3774269e-d4c8-11e6-9320-483b7460f0b2.png)

![image](https://cloud.githubusercontent.com/assets/3119321/21739689/459e29a4-d4c8-11e6-9f2f-73b358995391.png)

Server original response time: 18ms, 19ms

![image](https://cloud.githubusercontent.com/assets/3119321/21739691/5e53765c-d4c8-11e6-97fe-ccb3636bb5c5.png)

![image](https://cloud.githubusercontent.com/assets/3119321/21739697/776b0308-d4c8-11e6-90f6-fa998bbbcc6e.png)

**Comment by prashantagarwal** [comment]
@rajcybage Can you update to 5.2.0 and verify if you are still seeing this issue.

**Comment by tanvayv10** [comment]
> Version/App Information:
> 
> 1. Postman Version: 4.9.2
> 2. App (Chrome app or Mac app): Chrome App Chrome 55.0.2883.87
> 3. OS details: win / x86-64
> 4. Is the Interceptor on and enabled in the app: yes
> 5. Did you encounter this recently, or has this bug always been there: always been there
> 6. Expected behaviour: same response time
> 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
> 8. Screenshots (if applicable)
> 
> Postman response time:568 ms, 625ms
> 
> ![image](https://cloud.githubusercontent.com/assets/3119321/21739688/3774269e-d4c8-11e6-9320-483b7460f0b2.png)
> 
> ![image](https://cloud.githubusercontent.com/assets/3119321/21739689/459e29a4-d4c8-11e6-9f2f-73b358995391.png)
> 
> Server original response time: 18ms, 19ms
> 
> ![image](https://cloud.githubusercontent.com/assets/3119321/21739691/5e53765c-d4c8-11e6-97fe-ccb3636bb5c5.png)
> 
> ![image](https://cloud.githubusercontent.com/assets/3119321/21739697/776b0308-d4c8-11e6-90f6-fa998bbbcc6e.png)

HI , you solved this issue ?
