### ISSUE TITLE
Trailing 0s don't show when JSON is pretty printed

### ISSUE THREAD

**Issue by sixcorners** [a85/POSTMan-Chrome-Extension#2618]
1. Postman Version:4.9.2
 2. App (Chrome app or Mac app): chrome app
 3. OS details: mac
 4. Is the Interceptor on and enabled in the app: what is that?
 5. Did you encounter this recently, or has this bug always been there: yes, idk
 6. Expected behaviour: shows the values as they are in the JSON
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 8. Screenshots (if applicable)

try to view 3.20 in the json pretty printing thing
It shows 3.2

**Comment by prashantagarwal** [comment]
@sixcorners Can you update to the latest postman version and verify if you are still seeing this issue, you still face this kindly reopen this issue.
