### ISSUE TITLE
Enviornment Var as Host is not Resolved Properly With Shared Collection

### ISSUE THREAD

**Issue by workabyte** [a85/POSTMan-Chrome-Extension#2620]
1. Postman Version:4.9.2
 2. App (Chrome app or Mac app):Chrome 55.0.2883.87
 3. OS details:win / x86-32
 4. Is the Interceptor on and enabled in the app: no
 5. Did you encounter this recently, or has this bug always been there: prob not new
 6. Expected behaviour: 
Url looking like this: GET: http://{{api.url}}/somthine/special/
with Env Values api.url == 'api.someplace.com' 
would result with: GET: http://api.someplace.com/somthine/special/

So after a little digging i believe i have found the issues here.

**To Reproduce** 
1. var name MUST
1.1 have a '.' in the name
1.2 be the 'host' value in the url
1.3 be shared or used in something else remote (like monitors or such)
2 request MUST be a GET request

I believe the cause is that when there is a '.' and the req is a GET the JSON saved for this looks like such
the original var i was using was 'api.server' and then changed to 'api-server' as a work around 
`"host": [
								"{{api",
								"server}}"
							]`
VS
`"host": [
								"{{api-server}}"
							]`

the output becomes `Error: Invalid URI "https:///%7B%7Bapi.server%7D%7D/somthine/special/"`

Workaround for me so far was to just change the '.' to a  '-' so that host would then be saved as shown above and then used properly (little painful but i learned my lesson)

**Comment by workabyte** [comment]
just curious if there is an update on this.
also wondering if my assessment was accurate?

thanks for such a great product!

ps we are a paid customer :)

**Comment by SamvelRaja** [comment]
@workabyte Thanks for contacting us. The issue has been identified and it is been fixed internally. We shall update this thread once it is released.

**Comment by vegetableman** [comment]
@workabyte Could you verify if the issue is fixed in the latest version `4.10.3`?

**Comment by workabyte** [comment]
@vegetableman, based on the JSON that was saved on export i would say this looks to be resolved. 
thank you much!
