### ISSUE TITLE
Nested environments with inherited variables

### ISSUE THREAD

**Issue by chimit** [a85/POSTMan-Chrome-Extension#2621]
Hi!

My list of environments became too big: dev, test, production URLs with a few profiles with different variables in each. So I have to name my environments like `[Project1][Dev] - user1`, `[Project2][Test] - customer2` e.t.c.

It would be much more convenient to use nested environments with inherited variables. Please, consider this proposal.

**Comment by sdnts** [comment]
@chimit We've been experimenting with a few ideas to support use cases with large amounts of data, like yours. I'll let you know here when we have something concrete :)

**Comment by rolfmadsen** [comment]
If I could select multiple environments, that would solve this usecase for me.

I could place information like:
1. API version and credentials in one environment, which I would change depending on my test scenario in different collections 
2. variables that I would use across collections in a separate environment.

I assume that wouldnt break exisiting setup for syncronization of environments to Postman serveres etc.

It would be a problem if I had duplicate variables in the selected environments however.

**Comment by vsethi13** [comment]
+1
In the spring-boot world, it has a similar feature called "profiles". The concept is the same, that you logically group your config variables in different profiles and activate as many of them while running the program.

**Comment by sudharsan81** [comment]
Awaiting for this feature very eagerly. Then I can migrate my CI tests from costly-to-maintain .Net scripts to 100% postman scripts :)

**Comment by kdp8791** [comment]
+1

**Comment by alvmunoz** [comment]
+1

**Comment by jordaaash** [comment]
+1. We have essentially the same use case as @rolfmadsen. We have access tokens for different roles, and templates other for request variables, and want to be apply to compose them together for requests.

**Comment by ymajoros** [comment]
+1. That would also help for a simple use case where you want most variables to be shared with a team, but some still have to be local. If we could select multiple environments, we could just have a shared one and a local one at the same time.

**Comment by vimception** [comment]
@rolfmadsen Paw (paw.cloud) solves this by introducing a 3th level 'Groups', so the hierarchy becomes 'Group' > 'Environment' > 'Variables'. It has nothing to do with having 'large amounts of data' @madebysid, it is a very basic use case. Suppose I have an API which issues OAuth tokens. I would like to independently select the server (development, testing, QA...), the user (admin, testuser1...) and the client (mobile app, javascript spa...), each having their own set of variables to be used in composing the request:

Server > Development > root_url = localhost:5000
User > Admin > email = ..., password = ....
Client > Mobile > scope = 'api offline_access', grant_type = 'password', ....

Flattening these into a single level explodes the number of combinations, as pointed out by @chimit.
I don't understand why this does not get higher priority.

**Comment by emersonf** [comment]
It's way too easy to get an explosion of configuration with the current setup, e.g. one environment for each combination of different end-users, clients, deployment environments, etc. 

If you want to keep the concept of "environments", let us specify an ID for each environment, e.g. `qa`, or `x_qa`. Turn the Environment dropdown into a multi-select. Turn `pm.environment.set("variable_key", "variable_value");` into either `pm.environment.set("environment_id", "variable_key", "variable_value");` or more conveniently, `pm.environment_id.set("variable_key", "variable_value")`. Update `pm.variables.get()` to read from all enabled environments. At that point, we don't need to repeat configuration and can just enable the environments we need.

The "environment" name is also misleading and is causing a fragmentation of the same concept. We're just dealing with a set of property maps. Allowing users to create an arbitrary number of maps and letting us turn them on or off for a collection, via drop down, etc. would simplify how variables work in Postman. That way there's no conceptual difference between `pm.global` and `pm.x_qa`, except for a default precedence in case of variable name conflicts.

**Comment by vishcious** [comment]
Worked around this issue temporarily by having the "common" variables in an environment file and moving the variables that change to a data file per "environment" with just one iteration... works for now.

But, yeah, supporting multiple environment files is the real solution

**Comment by unigeek** [comment]
I have the situation, which I imagine is common, where I want to substitute a set of values for various variables based on the environment that I am working with. To do this, I defined collection-specific variables like `dev.service_url`, `dev.account_id`, `dev.user_id` (and corresponding `test.service_url`, `test.account_id`, `test.user_id`) all within the Postman collection. Then I define a global variable `env` which I set to either `dev` or `test`. Doing so enables me to refer to my variables as more-or-less of a whole set by using `{{{{env}}.service_url}}`, `{{{{env}}.account_id}}` and `{{{{env}}.user_id}}`. Some of the variable validation that Postman wants to do results in calling out issues, but it does seem to work for me.

**Comment by miketonguk** [comment]
Keep Environment as is (for backward compatibility) and then create 2 more selectable 'groups' of settings that can also be applied. One to select the Product, System or Client you're interacting with and another to select the User, Identity, or Authentication you wish to use. 

The 2 new groups can be turned off by default and only added if a team requires it.

**Comment by gavinclarkeuk** [comment]
I must be missing something here. I don't understand why you wouldn't just have the generic ability to add multiple environments. Seems to me if you add 2 more variable sets then when someone has 5 different dimensions to their model they will just be asking for this feature again.

If you just made it possible to apply multiple environment files and made it very obvious what would happen in the case of duplicated keys (ideally with a warning) then it would presumably be a lot less work than adding n additional arbitrary kinds of environment file, and would be infinitely extensible too.

**Comment by jwwicks** [comment]
+1.  For inheritance. I tend to break out my collections by API which have endpoints, client credentials etc... Then depending on the project I have Develop, Test/Staging and Production environments. With inheritance you override a parent variable in the child environment. 

I do like the way Runscope handles this with a Shared Environment and then an inherited one in each bucket/test.

Backward compatibility could be maintained by simply defaulting parent to global which I assume is already the default behavior.

**Comment by TehBakker** [comment]
Wants to have an env with url and non sensible variable and another with sensible data that should not be shared

**Comment by science695** [comment]
> Wants to have an env with url and non sensible variable and another with sensible data that should not be shared

You can do that with the current normal environments. Make an environment in your Team or public workspace with the test data in it. And when you publish that, include the test data environment.

**Comment by snotmare** [comment]
+1 Our use case is similar to others. We have a url like this:
`https://{{host}}/foo/{{version}}/bar/etc`

If I could select multiple environments to use, I could select the host I want and separately select the version. That would be a lot better than having separate environments for all the different combinations.

**Comment by a85** [comment]
We support Collection variables now that gives an additional scope for defining variables that are related to requests. We don't envision supporting nested environments any time soon. It increases the complexity of maintaining those variables as well as sharing them. Other use cases should be easily supported by collection variables, environments, and globals.

**Comment by science695** [comment]
@a85: Can you explain how I could set a collection and be able to switch between DEV, QA, and PROD, and also switch between 3 different test users (API KEYS)?

You've mentioned that is is easily supported, but I can't find the right angle of attack to solve this.

Thanks!

**Comment by emersonf** [comment]
It's not easily supported. I've resorted to creating dummy requests that do nothing but set environment variables, and I "run" them to change variables, e.g. switching between dev/qa/prod, for example. And keeping actual environments for secrets. It's a garbage workaround.

@a85 this shouldn't be closed. There's a state explosion problem that's easily solved by multi-selects and collection variables don't help.

**Comment by TehBakker** [comment]
Doing the same as @emersonf , dummy requests to switch variable around

**Comment by science695** [comment]
@a85 I can understand that turning the environments into somewith with inheritance would definitely increase the complexity alot.

I think that many of these use cases could be solved without the inheritance, just the ability to activate more than 1 environment at a time.

i.e.:
Environment: DEV, TEST_USER1, API_PROTOCOL3_2

Each of these environments would have the same functionality of variables as is currently there, but the ability to activate multiple at once would let us avoid this explosion of combinations.

**Comment by cjjohansen** [comment]
I Would not go for inheritance but for a kind of composition. It exists alot of places for instance Azure Application Configuration. Where they use the concept of labels. So each configuration field can have multiple values based on a label. It looks like this:
![image](https://user-images.githubusercontent.com/465656/63998943-9ca5de80-cb02-11e9-832a-0dd25eed3778.png)

The same thing could be done for a collection where you could define a variable that could have different values for each environment.

This would definitly make my postman life easier

**Comment by sandeep609** [comment]
We are facing the same issue. We maintain different environment files corresponding to our deployment environments and each of them has around 200 variables. These variables can't be part of the "Global" variables files, as the environment files represent both pre-prod and production environments and some of the URLs (represented as variables) are different for pre-prod and prod environments. It getting challenging to replicate new variables added under one environment to all the other environments and the postman UI is not making it any easier. (For now I'm trying to copy parts of the json file to other environment files but this is very error prone.)

It would really help if there was environment composition, something like enviroment-A can be built based on "static-urls" environment and other variables defined as part of the environment-A...Not really sure why this would be challenging, this is very similar to how spring-boot does.

**Comment by kenlefeb** [comment]
> Other use cases should be easily supported by collection variables, environments, and globals.

Part of the problem with this is that updating my collection by importing an OpenAPI Specification, erases all the collection variables. Postman is not my primary OAS editor, so I have to continually update my Postman collection from an external source.  Environments are the best way to persist configuration values distinct from the collection itself.
