### ISSUE TITLE
Postman does not unzip automatically gzipped responses

### ISSUE THREAD

**Issue by Rihab** [a85/POSTMan-Chrome-Extension#2622]
I needed to gzip all the json responses in our app because of the large amount of data we have. Any browser already unzips automatically the received response into JSON. However Postman returns something like : `H4sIAAAAAAAAAM2POwvCMBSF90L/wyVzB9tmcnZxcLFuIiE0VwikD/IQpOS/20RL1cGt0vW...` 
How do I make Postman unzip this automatically ? Is this possible at all ?

NB : I run the Postman 4.9.3 App on Windows 10.

**Comment by sdnts** [comment]
@Rihab Sorry for the lack of activity here, but can you also reproduce this with `https://postman-echo.com/gzip`, or is this happening just for your server?

**Comment by Rihab** [comment]
@madebysid the problem is fixed. Sorry that I did not put any feedback here. 
I was doing the compression manually while Vert.x was also doing it for me. 
So Postman maybe found a double-gzipped response and could therefore not unzip it.
When I use only the gzip feature of Vert.x I don't have the problem anymore and Postman unzips the reponse correctly.
PS: please please mark this as solved or not applicable. Thanks :)

**Comment by sdnts** [comment]
Awesome, that's great to hear!

**Comment by drkhannah** [comment]
im getting a gzipped response from an API, how to I unzip the byte array?

**Comment by CRC-Mismatch** [comment]
@drkhannah being a byte array, are you sure it's gzipped? If it's just the value that's messed up, it could be one or more of 
1. As JSON has no concept of 'byte', if the server is returning JSON, maybe it interprets a byte array as a string when encoding to JSON?
2. Is the server sending the correct Content-Type and Content-Encoding headers?
3. If it's only the value, while other data appears fine, could the server be compressing this value manually?
4. As byte arrays shown as string don't have to be like a "normal" string, maybe just the data in it looks as random as compressed/encrypted data?
5. Is it possible that the server is returning the byte array in Base64 encoding, and then gzipping the entire response (which is getting decompressed, but you're actually reading the Base64)?

For the first 2, you'd have to change it within the server - and also it's really probable that you'll end up having the same problem with some of the available JSON encoding libraries for whichever language you're using.
For the latter 3, you'd have to try scripting something in the Tests code to treat the received value, but if it's really compressed, I'm not sure if Postman exposes any libraries that are able to treat this. For Base64, it's well documented - you could go with something like `data = CryptoJS.enc.Base64.parse(base64content);`

**Comment by swateek** [comment]
Facing a similar trouble, my express server is doing a gzip for my code. I can see it in cURL, but the same is not seen on POSTMAN. Any help @madebysid ?

**Comment by soulomoon** [comment]
@swateek  + 1

**Comment by swateek** [comment]
Actually, we need to ensure "Accept-Encoding: application/gzip" as a part of Headers. 

Postman unzips and displays it for debugging purposes. You won't get a zip file downloaded. If you really need to test it that way, have a cURL request.

**Comment by rafajrcarvalho** [comment]
> Actually, we need to ensure "Accept-Encoding: application/gzip" as a part of Headers.
> 
> Postman unzips and displays it for debugging purposes. You won't get a zip file downloaded. If you really need to test it that way, have a cURL request.

Actually, the correct header is 'Accept-Encoding: gzip'.

It works with 'application/gzip' because the server does not recognize that value and therefore assumes the default value 'identity', which means no compression.

Note that with 'Accept-Encoding: gzip', not only does it work properly, but the response size is significantly smaller, since it is actually being compressed.
