### ISSUE TITLE
Why save same every POST request

### ISSUE THREAD

**Issue by om3rcitak** [a85/POSTMan-Chrome-Extension#2623]
Hi,

Why save same every POST requests? I wanna save just 1 request (like GET method)

example : http://prntscr.com/du9bux

**Comment by sdnts** [comment]
@Om3rCitak The history, as the name suggests, is meant to be a historical timeline of all your requests. We follow the following ideology when add items to the history:
When you POST data to a service, you're actually changing something server side, so each request in essence is unique, hence they show up as different items in the history
However, a GET is usually a pure operation, which means that it will yield the same response every time (and does not change anything server side). Hence these display as a single list item

What you are looking for, I'm guessing are collections, where you can actually save a request to be accessed later. [This](https://www.getpostman.com/docs/collections) should be useful if you are just starting out.

Feel free to reopen if I misunderstood.

**Comment by om3rcitak** [comment]
@madebysid thank you :)
