### ISSUE TITLE
Make sent request available

### ISSUE THREAD

**Issue by benjamw** [a85/POSTMan-Chrome-Extension#2625]
It would be nice to have the request that was sent available to look at somewhere. Maybe along the bar that has the Body, Cookies, Headers, etc... Just add one called Request or something.

Something that has all the variables replaced with their actual values, all cookies sent, all headers sent, all actual POST data, etc. so that bugs (like missing/incorrect variables) can be more easily found.

It would also be nice just to be able to see exactly what was being sent to the server.

**Comment by sdnts** [comment]
@benjamw If you are on the native apps, you can do this by using the Postman Console (View > Postman Console). This will show you exactly what was sent to the server.
If you're on the Chrome App, though, you'll have to use the Chrome DevTools to do this. [This](http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/) guide should help. I'd recommend switching to the native app, though so you aren't affected when Google ends support for Chrome Apps later this year.

**Comment by benjamw** [comment]
I am on the native app. I'll check that out. Thank you.
