### ISSUE TITLE
Digest Authentication is not working and server nonce values are not retried automatically

### ISSUE THREAD

**Issue by krishnamohanpkm** [a85/POSTMan-Chrome-Extension#2626]
Hi,
We have been using Postman Rest Client 0.8.4.19 version and Digest Authentication perfectly works in that version.
Recently we installed Postman 4.9.2 since no support for Postman Rest client v 0.8.4.19.
In latest Postman 4.9.2, we need to manually enter Digest Authentication nonce values that server returns every time.  Ideally it should automatically retry the request with Server returned nonce value.
Can you please fix the above issue ASAP?
OR 
at least give us the Postman Rest Client 0.8.4.19 version. We are not able to download it. Looks like it was removed in webstore. The following link not working.

https://chrome.google.com/webstore/detail/postman-rest-client/fdmmgilgnpjigdojojpjoooidkmcomcm?utm_source=chrome-app-launcher-info-dialog

 1. Postman Version:4.9.2
 2. App (Chrome app or Mac app):Chrome app
 3. OS details: Windows 7 professional 64 bit
 4. Is the Interceptor on and enabled in the app: No
 5. Did you encounter this recently, or has this bug always been there: Always
 6. Expected behaviour:Digest auth server nonce value has to be used and retry the request
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 8. Screenshots (if applicable)

[log.txt](https://github.com/postmanlabs/postman-app-support/files/699936/log.txt)
![postman4 9 2](https://cloud.githubusercontent.com/assets/20651284/21864932/be2310f0-d7f8-11e6-9d8c-c8dbe1350288.JPG)
![postmanrestclient0 8 4 19](https://cloud.githubusercontent.com/assets/20651284/21864931/be14b4ec-d7f8-11e6-888f-2041c6aa3486.JPG)

**Comment by sdnts** [comment]
@krishnamohanpkm The main Postman App does not chain any requests right now, even for Digest Auth requests.
However, you can write a test script that does this for you. You can get the header nonce values using the predefined variable `postman.getResponseHeaders`, and set environment variables for these values. You can then use these variables in the next request using the `{{variableName}}`syntax. 

You can then run the two Digest Auth requests one after the other, manually, or use the Collection Runner to run them one after the other automatically.

Closing this. Feel free to reopen if I misunderstood.

**Comment by jamesajones** [comment]
I use a two step process in which I copy the values from Www-Authenticate into the Digest fields. Sorry but haven't mastered scripting yet.
