### ISSUE TITLE
Variables used in POST requests not properly being substituted by data file values in collection runner

### ISSUE THREAD

**Issue by artrespa** [a85/POSTMan-Chrome-Extension#2627]
I am trying to run a collection of requests in the collection runner that utilizes a data file in order to run tests. The bodies of each request is raw JSON using postman variables. An example of this is below:

          {
            "ContactFirstName":"{{ContactFirstName}}",
		"ContactLastName":"{{ContactLastName}}",
		"ContactPhone":"{{ContactPhone}}",
		"Priority":"{{Priority}}",
		"Description":"{{Description}}",
           }

My data files contain keys matching the variable names and have corresponding values, as shown below:

CSV: 
ContactFirstName,ContactLastName,ContactPhone,Priority,Description
Jimmy,John,123-456-7890,1-Low,This is a description.
Bob, Smith, 111-222-3333,3-High,Another description.

I have tried using both CSV and JSON for the data files. The values in the file are not properly substituting the variables in the request body. The request processes the literal string in the request body as the field value. ie. ContactFirstName = "{{ContactFirstName}}" rather than "Jimmy". This happens with every value in every request being tested, resulting in failed tests. Is there a step or detail that I am missing in the process of setting up the requests to use data files when ran in the collection runner? 

 1. Postman Version: 4.9.2
 2. App (Chrome app or Mac app): Chrome 55.0.2883.87
 3. OS details: win /x86-32
 4. Is the Interceptor on and enabled in the app: no
 5. Did you encounter this recently, or has this bug always been there: Encountered recently 
 6. Expected behaviour: The values given in the data file should properly replace the variables in the request bodies and the tests should run given those proper test values.

**Comment by sdnts** [comment]
@artrespa When you specify a variable in the request body, you do not need to surround it in double quotes. This would turn the variable into an actual string (with value "{{ContactFirstName}}"). Your request body should look like: 

```
{
        "ContactFirstName": {{ContactFirstName}},
	"ContactLastName": {{ContactLastName}},
	"ContactPhone": {{ContactPhone}},
	"Priority": {{Priority}},
	"Description": {{Description}}
}
```

**Comment by techpeace** [comment]
If I have a variable that is meant to be a string, then it needs to be enclosed in quotation marks in the environment itself or it will come out as a JSON error, as it gets embedded into the JSON body without quotation marks:

```json
{
  "userId": someUserId
}
```

If I need to use that user ID in a URL segment, then I need a version of it that isn't enclosed in quotation marks. The workaround here seems to be creating two environment variables, one including quotation marks, and one without.

**Comment by lisadu** [comment]
We're seeing this issue as well. If we run the collection with a JSON data file that includes `{"Name": "Test"}`. `{{Name}}` will render in the body as Test, but we need it to be "Test".

**Comment by amanautomation** [comment]
We are also seeing this issue. For now, I can put double quotes in my csv file but that is not a very pretty solution. And it is more painful when I have to validate the data in response json against the data available in csv file as I have to get rid of all the double quotes for the validation to work.

Request the postman team to look into it.

**Comment by dnaidionov** [comment]
I'm still seeing this issue. Running the v6.0.10

**Comment by nedeliaev** [comment]
issue is reproduced for me as well
Postman v6.0.10

**Comment by sriram474** [comment]
I am also facing the same issue with the postman version 5.5.2 chrome plugin

**Comment by techpeace** [comment]
As mentioned in #4718, you can now enclose the variables in quotes:

```json
{
  "userId": "{{userId}}"
}
```

**Comment by mrosendin** [comment]
I am experiencing an issue where, when quoting the data variable as shown above, it is no longer accessible in tests. Instead it is `null`.

E.g.,

```javascript
console.log(pm.iterationData.get("foo"))
console.log(environment["bar"])
```

Logs `null` and `bar`, respectively.

It seems the only workaround is to escape quotes in the data file like so:

```json
[
  {
    "foo": "\"value\""
  }
]
```

This makes it accessible in the tests but frustratingly, when comparing it to strings, it contains quotes!

For example:

```
tests["It matches"] = jsonData.key === pm.iterationData.get("foo");
// => value != "value"
```

To workaround the issue, chain `.replace(/"/g, "")` to remove the double quotes.

**Comment by keke9036** [comment]
"data":"{{data}}" not working for version 6.7.3 desktop,

**Comment by texaskiwi** [comment]
I'm seeing this issue in 7.0.6 desktop.   

It appears to happen when the object is nested

Without quotes
{"customerAccount":{"test": {{postcode}}  }}    ->    {"customerAccount":{"test": 77079  }}

With quotes
{"customerAccount":{"test": "{{postcode}}"  }}   ->   {"customerAccount":{"test": "{{postcode}}"  }}

Not a nested object
{"postcode":"{{postcode}}"}  ->  "postcode":"77079"

**Comment by ionapjolive** [comment]
This is a blocker for my use case. Have to be able to iterate over data variables nested in JSON body.

> 
> 
> I'm seeing this issue in 7.0.6 desktop.
> 
> It appears to happen when the object is nested
> 
> Without quotes
> {"customerAccount":{"test": {{postcode}} }} -> {"customerAccount":{"test": 77079 }}
> 
> With quotes
> {"customerAccount":{"test": "{{postcode}}" }} -> {"customerAccount":{"test": "{{postcode}}" }}
> 
> Not a nested object
> {"postcode":"{{postcode}}"} -> "postcode":"77079"

**Comment by milser** [comment]
Same problem here: 
Postman for Linux
Version 6.7.1

[ @texasquiwi](https://github.com/postmanlabs/postman-app-support/issues/2627#issuecomment-474106468)
> Without quotes
>{"customerAccount":{"test": {{postcode}} }} -> {"customerAccount":{"test": 77079 }}
>
>With quotes
>{"customerAccount":{"test": "{{postcode}}" }} -> {"customerAccount":{"test": "{{postcode}}" }}
