### ISSUE TITLE
JSON response parser shows error instead of showing raw response content

### ISSUE THREAD

**Issue by dudeofawesome** [a85/POSTMan-Chrome-Extension#2628]
1. Postman Version: 4.9.3
 2. App: Mac app
 3. OS details: macOS 10.12.2 on MacBook Pro 2016
 4. Is the Interceptor on and enabled in the app: no
 5. Did you encounter this recently, or has this bug always been there: I just experienced it
 6. Expected behaviour: Response viewer should fall back to "Raw" if JSON parser fails
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app): No errors displayed
 8. Screenshots (if applicable)
![image](https://cloud.githubusercontent.com/assets/1683595/21868717/09baed20-d809-11e6-9504-b2d177138b4e.png)
![image](https://cloud.githubusercontent.com/assets/1683595/21868722/0f1f5a26-d809-11e6-9b69-69f5df2bbe3c.png)

1. Get a response back that claims to be JSON, but isn't
1. Have response body viewer set to auto or JSON
1. Proceed to be confused

**Comment by S33G** [comment]
I've also experienced this issue, I receive it when dumping an Array or something.

`Array()`

gives me Unexpected 'A'. 

Was super confused the first time it happened.

**Comment by vegetableman** [comment]
Thanks guys for reporting this issue 👍 . 
@a85 The mode could be changed to `Text` for the editor on such cases. What do you think?

**Comment by dudeofawesome** [comment]
Yes, that would be perfect

**Comment by sdnts** [comment]
We depend on the response Content-Type header to automatically choose a parsing type for the response. Can you guys make sure the response Content-Type header is correct?
