### ISSUE TITLE
Submitting a request URL with an environment property and a path parameter always fails with error connecting message

### ISSUE THREAD

**Issue by dphillipsprosper** [a85/POSTMan-Chrome-Extension#2629]
Version/App Information:

 1. Postman Version: 4.9.3
 2. App (Chrome app or Mac app): Windows App
 3. OS details: Windows 10
 4. Is the Interceptor on and enabled in the app: No
 5. Did you encounter this recently, or has this bug always been there: I think it's been there since I switched from the Chrome app to the Windows App
 6. Expected behaviour: I expect a result to be returned. Instead, I get the following error: There was an error connecting to %7B%7Bsite.url%7D%7D/path/12345.
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app): Nothing is showing up in the logs when I click send
 8. Screenshots (if applicable)
N/A

Steps to reproduce the problem:
1. Use a request URL following the pattern {{site.url}}/path/:id where the environment variable site.url = http://my.site.com and the param :id is set to 12345

2. Click send

It should be noted, that if I replace the param :id in the request URL with the value directly, it works!

**Comment by sdnts** [comment]
@dphillipsprosper We're aware of this issue, and will release a fix for this in an upcoming version. Will keep you updated here.

**Comment by sdnts** [comment]
@dphillipsprosper 4.10.2 includes a fix for this. Can you try updating and verifying?
