### ISSUE TITLE
Postman Export/Import Changes OPTIONS Member Body setting; Runner fails to Run with OPTIONS Body Setting of form-data 

### ISSUE THREAD

**Issue by bill-morris** [a85/POSTMan-Chrome-Extension#2630]
1. Postman Version: 4.9.2
 2. App (Chrome app or Mac app): Chrome Version 55.0.2883.87 m (64-bit) App
 3. OS details: win/x86-64 (Win 7)
 4. Is the Interceptor on and enabled in the app: Yes
 5. Did you encounter this recently, or has this bug always been there: Just noticed, but only recently attempted this export/import round trip.
 6. Expected behaviour:  1) Saving a collection in postman and importing it should not change an OPTIONS member Body setting of x-www-form-urlencoded to form-data. 2) Running a collection with Runner should not fail/hang when an OPTIONS member has a Body setting of form-data. 
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
This is the console log when running a collection in RUNNER that has an OPTIONS member with body setting of form-data. Note that RUNNER hangs.
Uncaught Error Uncaught ReferenceError: ArrayBufferEncoderDecoder is not defined chrome-extension://fhbjgbiflinjbdggehcddcbncdddomop/js/common.js 109322 33 ReferenceError: ArrayBufferEncoderDecoder is not defined
    at child._sendRequest (common.js:109322)
    at common.js:107168
    at child.<anonymous> (common.js:110705)
    at child.<anonymous> (common.js:99253)
    at child.<anonymous> (common.js:101742)
    at triggerEvents (common.js:99294)
    at triggerApi (common.js:99281)
    at eventsApi (common.js:99080)
    at Object.Events.trigger (common.js:99271)
    at common.js:110742
(anonymous) @ common.js:145054
common.js:109322 Uncaught ReferenceError: ArrayBufferEncoderDecoder is not defined
    at child._sendRequest (common.js:109322)
    at common.js:107168
    at child.<anonymous> (common.js:110705)
    at child.<anonymous> (common.js:99253)
    at child.<anonymous> (common.js:101742)
    at triggerEvents (common.js:99294)
    at triggerApi (common.js:99281)
    at eventsApi (common.js:99080)
    at Object.Events.trigger (common.js:99271)
    at common.js:110742
_sendRequest @ common.js:109322
(anonymous) @ common.js:107168
(anonymous) @ common.js:110705
(anonymous) @ common.js:99253
(anonymous) @ common.js:101742
triggerEvents @ common.js:99294
triggerApi @ common.js:99281
eventsApi @ common.js:99080
Events.trigger @ common.js:99271
(anonymous) @ common.js:110742

Here is the 109322 line in common.js giving the heartache:
	          remoteRequest.body = ArrayBufferEncoderDecoder.encode(body.get("data"));

 8. Screenshots (if applicable)
postman before saving
![postman_before_save](https://cloud.githubusercontent.com/assets/25080559/21892705/b560d7fe-d89d-11e6-8559-0988172d8282.png)
postman after importing
![postman_after_import](https://cloud.githubusercontent.com/assets/25080559/21892734/cb44da02-d89d-11e6-89ac-172f068bf36c.png)
runner console log
![runner_console](https://cloud.githubusercontent.com/assets/25080559/21892749/e047548e-d89d-11e6-9e54-df0902f340b0.png)

Problem 1
1) Create a Collection having an OPTIONS member with a Body setting of x-www-form-urlencoded.
2) Export the collection. Leave the default of Collection v2 radio toggled on.
3) Delete the collection.
4) Import the collection.
5) Verify that the body setting for the OPTIONS member has been changed in the round trip to form-data.

Problem 2
1) Run a collection using Runner that has an OPTIONS member with a Body setting of form-data.  Note that this can be the collection from Problem 1.
2) Observe Runner never returns. Check console.log for error data.

Note that there is no body in our OPTIONS calls, so the Body setting should not be needed.
Note also that we workaround this issue by setting the body to RAW (tested with RAW settings Text and JSON (application/json)). The Raw setting survives the Export/Import round trip.

**Comment by numaanashraf** [comment]
Closing this issue as Chrome apps are deprecated and is in maintenance mode. Please move to Postman's Desktop Apps to get the latest features and bug fixes (https://www.getpostman.com/apps)
