### ISSUE TITLE
PHP cURL code generation bug

### ISSUE THREAD

**Issue by AykutCevik** [a85/POSTMan-Chrome-Extension#2631]
Problem:

Postmans PHP cURL code generation sets the raw input for requests directly in the `curl_setopt_array` call, which leads cURL to avoid sending raw input due to a bug in cURL.

You have to set it explicitly after setting the curl option `CURLOPT_CUSTOMREQUEST` with:
`curl_setopt($curl, CURLOPT_POSTFIELDS, "{\"foo\":\"bar\"}");`

To reproduce it, make a custom POST-request with an input json and generate its code for PHP cURL. Then execute the generated code and see, that it is not transferring the raw input.

![image](https://cloud.githubusercontent.com/assets/1965251/21935447/d5884272-d9ad-11e6-90d6-a1e76668deab.png)

Version/App Information:
 1. Postman Version: 4.9.2
 2. App (Chrome app or Mac app): 55.0.2883.95 (64-bit)
 3. OS details: Mac OSX
 4. PHP: several versions affected, 7.1 also

**Comment by VShingala** [comment]
@AykutCevik  It seems that php cURL has fixed `curl_setopts_array()`. I tried to reproduce your issue but seems to be working fine for me. And Postman generated `php-cURL` code snippet is working correctly too.

Can you confirm this?
