### ISSUE TITLE
JSON file are sent as Octet stream in Multipart POST Request

### ISSUE THREAD

**Issue by DrakaSAN** [a85/POSTMan-Chrome-Extension#2635]
1. Postman Version: 4.9.2
 2. App: Chrome app
 3. OS details: Windows 10
 4. Is the Interceptor on and enabled in the app: Yes
 5. Did you encounter this recently, or has this bug always been there: Discovered recently.
 6. Expected behaviour: When POSTing a `.json` file in a multipart request, expecting the file's mime type to be `application/json`

Currently, when doing a multipart request containing a JSON file, the mime type is sent is `application/octet-stream`, while it should be `application/json`.

**Comment by sdnts** [comment]
@D219 Can you also reproduce this with one of our [native apps](https://getpostman.com/apps)?

**Comment by DrakaSAN** [comment]
No, only on the chrome app. It was a nice news there is a native app too.

**Comment by kamilgregorczyk** [comment]
If it contains file and some other values then it should be multipart/form-data

**Comment by kamilgregorczyk** [comment]
I'm also facing the same issue, here's my request body https://www.dropbox.com/s/tnhk2n0ox57amg2/Zrzut%20ekranu%202017-09-03%2015.24.31.png?dl=0 and I have no headers set.

**Comment by sdnts** [comment]
@kamilgregorczyk If this works on the native apps, can you try those out? I'd recommend shifting anyway, since Google plans to deprecate all Chrome apps later this year.
