### ISSUE TITLE
form-data POST sends application/x-www-form-urlencoded header

### ISSUE THREAD

**Issue by scr** [a85/POSTMan-Chrome-Extension#2636]
When sending a POST with form-data selected, it seems to send the format for multipart/form-data, but application/x-www-form-urlencoded as the Content-Type

Log from akka-http server (See http://doc.akka.io/docs/akka-http/current/scala/http/routing-dsl/index.html)
```
HttpEntity.Strict(application/x-www-form-urlencoded; charset=UTF-8,------WebKitFormBoundaryHd6mYHJbBmrth7XD
Content-Disposition: form-data; name="raw_html"

<html><body>Testing</body></html>
------WebKitFormBoundaryHd6mYHJbBmrth7XD--
),HttpProtocol(HTTP/1.1))
```

 1. Postman Version:  4.9.2
 2. App (Chrome app or Mac app): Chrome app
 3. OS details: OSX Sierra 10.12.2 (16C67)
 4. Is the Interceptor on and enabled in the app: not sure
 5. Did you encounter this recently, or has this bug always been there: recently
 6. Expected behaviour:
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 8. Screenshots (if applicable)

**Comment by vegetableman** [comment]
@scr Thanks for posting this issue 👍 . This usually happens when you switch from `x-www-form-urlencoded` to `form-data` and the `Content-Type` header of the former is retained. The fix will be out in the next release.

**Comment by koreyba** [comment]
The same issue is in Windows app in 4.9.3 version. Waiting for the fix, thanks!)

**Comment by vegetableman** [comment]
@koreyba @scr The fix is not part of the current release, as there are plans to allow further customisation for the same.

**Comment by Odame** [comment]
It's been about two months since the last comment on this issue. Any fix yet?

**Comment by ManWithShotgun** [comment]
If you use **Body** with selected **form-data** and in **Headers** tab see field with `Content-Type` then just delete this field (the header auto set in request). Current Content-Type must see if press Code (right side; on line with Authorization, Headers, Body, etc).

**Comment by sdnts** [comment]
As @vegetableman said, this header is added when you switch from `x-www-form-urlencoded` back to `form-data`. We explicitly do not remove any headers since there's no way to tell is a header was added by you, the user or automatically. Deleting the header manually seems like the cleanest solution to me.

Please let me know if you guys disagree, and I'll reopen this :)
