### ISSUE TITLE
Faulty tokens in oauth2 (can't delete)

### ISSUE THREAD

**Issue by Fjandin** [a85/POSTMan-Chrome-Extension#2637]
postman version 4.9.3 (Mac App)

I somehow managed to generate some faulty tokens or something but this is what i see now

https://gyazo.com/2a0f203c97a84064a2edd0ab5b25b4bb

When i click of any of the tokens i get nothing neither can i delete them from the list.

**Comment by sdnts** [comment]
Thanks for letting us know. A fix will be out with the next release.

**Comment by cgamache** [comment]
Temporary workaround to clear all OAuth2 tokens (for the Chrome App at least): 

In chrome
visit **chrome://inspect/#extensions**
click `inspect` under Postman
find the `Application` tab
expand IndexedDB -> postman -> oauth2_access_tokens
right-click -> Clear
restart

If you know how to use IndexedDB you'll know how to be more targeted with your deletes.

HTH!

**Comment by sdnts** [comment]
@Fjandin @cgamache 4.10.2 should fix this. Can you guys try updating and verifying this?

**Comment by Fjandin** [comment]
The issue is fixed for me, i can now delete tokens 👍

**Comment by madebysid** [comment]
-
