### ISSUE TITLE
No response for GET to subdomain.localhost:8080 Error: getaddrinfo ENOTFOUND

### ISSUE THREAD

**Issue by matthewsommer** [a85/POSTMan-Chrome-Extension#2638]
I'm trying to send a simple GET request to a subdomain of localhost and I'm getting an error in the Postman console that Error: getaddrinfo ENOTFOUND but the URL is definitely available. I've tried different combinations of including the http protocol and not including it and it doesn't work. Testing the same subdomain for the public site works fine.

Version/App Information:
 1. Postman Version: 4.9.3
 2. App (Chrome app or Mac app): Mac app
 3. OS details: 10.12.2
 4. Is the Interceptor on and enabled in the app: No
 5. Did you encounter this recently, or has this bug always been there: Just discovered
 6. Expected behaviour: Page should load but is not loading
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app): "Error:
getaddrinfo ENOTFOUND subdomain.localhost subdomain.localhost:8080"
 8. Screenshots (if applicable)

Steps to reproduce the problem: Send GET to subdomain.localhost:8080, no response and console reports "Error:
getaddrinfo ENOTFOUND subdomain.localhost subdomain.localhost:8080"

**Comment by vegetableman** [comment]
@matthewsommer The issue happens when you are sending a GET request to an invalid url. you may need to configure your `hosts` file. Related link which might help you :- http://stackoverflow.com/questions/23259697/error-getaddrinfo-enotfound-in-nodejs-for-get-call

**Comment by matthewsommer** [comment]
@vegetableman, My url is absolutely valid; http://subdomain.localhost:8080 is a valid URL. Modifying the hosts file does not make sense because the hosts file is what resolves the localhost hostname to the local IP loopback address 127.0.0.1. This is most certainly a bug as there are other bugs for Postman version 4 related to not being able to resolve localhost, the difference with this bug to those tickets is that this bug is for subdomains.

**Comment by vegetableman** [comment]
@matthewsommer The url is valid but you would have to map the mentioned subdomain to the loopback address `127.0.0.1` in your hosts file (`127.0.0.1       subdomain.localhost`). Also, you could verify whether the mapping is valid by checking the output to `ping subdomain.localhost` on the terminal.

**Comment by matthewsommer** [comment]
@vegetableman the issue is the web application I'm testing utilizes wildcard subdomain *.localhost.com so I might be testing many different subdomains. I've added this to the hosts file and verified that gives me a workaround, thanks! If you aren't considering this a bug then shouldn't it be at least a feature request? No modern browser could get away with not resolving subdomain.localhost and Postman definitely shouldn't either IMO.

**Comment by matthewsommer** [comment]
@vegetableman, also wouldn't this be a fairly easy fix? Just resolve `*.localhost` to whatever IP `localhost` resolves to from the `host` file? I suppose that wouldn't work though if `*.localhost` was mapped to a different IP in the local `host` file

**Comment by vegetableman** [comment]
@matthewsommer 👍  Tagging this as a feature request. Will keep you posted on this thread.

**Comment by matthewsommer** [comment]
@vegetableman thanks brother! I love Postman and continue to sing its praises :)

**Comment by jazoom** [comment]
Have the same issue. URL works in Chrome but not in Postman.

**Comment by abhijitkane** [comment]
@jazoom @matthewsommer The Postman Chrome app doesn't do any resolving of its own - it uses Chrome's XHR API to send the request. Can you check our native apps (https://www.getpostman.com/apps) and see if those work for you? I'm able to hit *.localhost subdomains in my Postman instance.

**Comment by jazoom** [comment]
This was a long time ago but I'm pretty sure I was using the native app then. I axed the Chrome app soon after the native app was in beta.

**Comment by abhijitkane** [comment]
@jazoom The app's proxy settings (Settings > Proxy) might help. Try toggling the system proxy setting - that might be interfering with the IP lookup.

**Comment by jazoom** [comment]
I only occasionally use Postman so I might not be the best person to help you debug this issue. I don't think I even have it installed at the moment.

**Comment by joaokamun** [comment]
I'm having the same problem with macOS native app. 
Change to chrome extension app worked for me.

**Comment by sdnts** [comment]
@jazoom @joaokamun Do you use /etc/hosts somewhere? Our native apps do not support this at the moment, but we're tracking this in #2369 
Chrome app requests are made via the Chrome browser, which is why it works.

Do you think this might be happening to you as well?

**Comment by jazoom** [comment]
@madebysid I don't now but I might have at the time I first commented above.

**Comment by joaokamun** [comment]
@madebysid My `/etc/hosts` is the default, never changed but I'm using Docker.

**Comment by czyzu01** [comment]
Interesting thing we've found out in our environment, when using 6.0.10 on Windows 10 uses system proxy settings, and you've set ENV variable for  http_proxy and https_proxy, that may cause problems. Setting them to null in batch script, solved problem for us.

**Comment by chitti-cc** [comment]
@a85 @madebysid  is this issue got fixed? I am facing the same problem, let me know if there is a workaround.

**Comment by shanjee** [comment]
I have the latest version (v6.2.4) when I run the monitor I am getting the same error. 

Error: getaddrinfo ENOTFOUND xxxx.com xxx:443, but the same collection works fine in post man when i run the run, any clue ?

**Comment by listenrightmeow** [comment]
This is an active problem for developers that opt into managing local DNS management with dnsmasq. I struggled to find a solution for a couple days, read this article and modified my hosts file.

Web browsers & curl honor dnsmasq networking while Postman doesn't.

**Comment by codenirvana** [comment]
We've added support for `*.localhost` lookup in the latest version of the Postman app (v7.6.0).

**Comment by emimarz** [comment]
I am experimenting this issue right now, Error: getaddrinfo ENOTFOUND
if I get the curl  code by the application it works but inside the app all request give me that error
and I'm not using localhost, I'm using an url that is accessible via browser

**Comment by emimarz** [comment]
I download the next version and it works but I don't know why happen that

**Comment by DevJulianSalas** [comment]
I am having the same error with version Version 10.14.9 using websockets. Once I removed the subdomain it works correctly.

`Error: getaddrinfo ENOTFOUND subdomain.localhost`
