### ISSUE TITLE
Ability to switch between multiple profiles

### ISSUE THREAD

**Issue by derpoho** [a85/POSTMan-Chrome-Extension#2639]
Feature Request:

It would be nice to be able to switch between multiple profiles quickly. It's annoying to logout/login again when switching to another profile. If there was a dropdown to switch logged in profiles, it would be awesome! ;)

Keep up the nice work!

Greets Marcus

**Comment by sdnts** [comment]
Hey @derpoho! That's a valid concern. We're actually tracking this already here: #2316. I'm closing this one so we can keep things tidy :)
