### ISSUE TITLE
Chrome to Postman Workflow missing

### ISSUE THREAD

**Issue by aleemb** [a85/POSTMan-Chrome-Extension#2640]
1. Postman Version: 4.8.3
 2. App (Chrome app or Mac app): Mac app

I am not sure how I did this in the past, maybe it was integration but there is no way to copy a network request from Chrome Debugger Tools (copy as curl) and paste it into Postman and have it work.

It's nearly there but the issue is that the CURL request encodes the form data and "Hello World" becomes "Hello+World" which Postman uses verbatim without decoding the "+" to spaces and so on.

This makes it frustrating to work with Chrome + Postman.

CC @numaanashraf

**Comment by a85** [comment]
Improvements to code generation through plugins will handle this workflow. Closing this for now.
