### ISSUE TITLE
API response is not saved correctly

### ISSUE THREAD

**Issue by sinaa2000** [a85/POSTMan-Chrome-Extension#2643]
1. Postman Version: Version 4.9.3
 2. App (Chrome app or Mac app): Windows app
 3. OS details: win32 6.1.7601 / x64
 4. Is the Interceptor on and enabled in the app: No
 5. Did you encounter this recently, or has this bug always been there: Recently
 6. Expected behaviour: Saving a response from API into a environment variable
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):   2xml.js:22 true
 8. Screenshots (if applicable)

I'm calling an API via POST, I can see the output which is a number (it's just a text, no json format), when I try to save the response into an environment variable I get a "true" instead of the actual value, console log also shows true, but I see the output number generated by the API in Postman and Fiddler or any other API calling tool. Tried adding Accept: text/xml in the header and got a serialized xml in Postman output Body like this: <long xmlns="http://schemas.microsoft.com/2003/10/Serialization/">12849817</long>, but even trying to parse this or anything that I do, I still get either an empty or a true. Tried parsing the response directly, in Json and xml even parsing as an Int but all unsuccessful. So I just wanted to know if this is a bug in Postman? I'm stuck here in this part and really need some help.
I'd appreciate your response.
Thanks

**Comment by sinaa2000** [comment]
here's the log from postman console:


Request Headers:
cache-control:"no-cache"
Postman-Token:"21b81719-10f3-42ed-ac47-b04af22c07d0"
Authorization:"OAuth xxx"
User-Agent:"PostmanRuntime/3.0.9"
Accept:"*/*"
Host:"xxx.com"
accept-encoding:"gzip, deflate"
content-length:""
Response Headers:
server:"rundl"
date:"Wed, 18 Jan 2017 00:41:46 GMT"
content-type:"application/json; charset=utf-8"
content-length:"28"
connection:"keep-alive"
cache-control:"no-cache, no-store"
pragma:"no-cache"
content-encoding:"gzip"
expires:"-1"
x-compressresponsestream:"gzip"
access-control-allow-origin:"*"
strict-transport-security:"max-age=31536000; includeSubDomains"
x-content-type-options:"nosniff"
x-xss-protection:"1; mode=block"
Response Body:12850139
Request Body:
146 ms



but I get true when I log the responseBody to console.
the responseBody is a number but Postman wont get it!

**Comment by sinaa2000** [comment]
Any ideas guys?

**Comment by sdnts** [comment]
Hi @sinaa2000, that's a weird one. Are you doing `console.log(responseBody)`? You said `JSON.parse`, `xml2Json` and `parseInt` do not return the correct value? Are you parsing the variable `responseBody`? Could you share your test script with me?

I set up a little server that returns me an integer with a 200 status code, but wasn't able to replicate this. Can you switch over to the Raw tab in the response section and check what is displayed there?

**Comment by sinaa2000** [comment]
Hi @madebysid,

Thanks for your response.
Yes, I do console.log and "true" is what I get.
Getting the value directly from responseBody gets me "true" as well as parsing it either in Json or XML.
The weird thing is I get the correct expected value which in this case is a number in Postman's response as well as the console inside response.
here's my test script : 

if (tests["Preallocated rundl id obtained successfully"] = responseBody =! "" && !responseBody.has("BadRequest")) {
    var response = JSON.parse(responseBody);
    postman.setEnvironmentVariable("pre_rundl_id", responseBody);
    console.log(responseBody);
    console.log(response );
}

for example in the last run I got this number in Postman response 12862223
same in Pretty, Raw and Preview and in console in,
Response Body:12862223
Request Body:
200 ms
true

but when assigning it to an environment variable or just trying to print it out directly, I get a "true" !


Any ideas what the issue is?


Thanks

**Comment by sdnts** [comment]
@sinaa2000 I see in your test script, you're doing `responseBody =! ""` in the first line, which is assigning the value `!""` (true) to the variable responseBody, and so you get the output `true` everywhere. I'm guessing this is a typo :P

**Comment by sinaa2000** [comment]
Thats probably not the issue as its just an if condition!?
If it doesnt go in if statement it shouldnt print the console, right?
Its probably just a typo and should not affect the responseBody, right?
Im just printing the responsebody and it doesnt work.

**Comment by sdnts** [comment]
Yep it's an `if` condition, but you're doing an assign to the variable `responseBody`.

If you have something like:
```
var value = true;
var x;
if (x=true) {
    console.log('hello')
}
```

`Hello` would be printed to the console, but `x` would also be assigned the value `true`. This is JavaScript behaviour. 

In any case, you should never do an assign on the variable `responseBody`.

**Comment by sinaa2000** [comment]
Oh, right, thanks so much for the help!
