### ISSUE TITLE
Read collections and environments from file

### ISSUE THREAD

**Issue by gianisegatto** [a85/POSTMan-Chrome-Extension#2645]
Guys,

Could you add a feature that makes postman always be updated from the Collection and Environment file once these files were imported to Postman.

Example:
Lots of times we change Environment files directly from the text editor and we have to remember to remove the environment and import the file again.

I think Postman behavior could be as an IDEA.

**Comment by sdnts** [comment]
Hey @gianisegatto! We're actually tracking this feature request here: #1079 
Reading and writing to a file is a difficult problem to solve in a collaborative environment, so we're still thinking of an elegant solution.

You should follow that thread for constant updates :)

Feel free to reopen this if I misunderstood your request.
