### ISSUE TITLE
[Feature Request] Can we have tool-tip of title on hovering tab title?

### ISSUE THREAD

**Issue by mahendranv** [a85/POSTMan-Chrome-Extension#2647]
Feature Request:
It would be really helpful to see tab title/URL without clicking on it.

 1. Postman Version: 4.9.2
 2. App (Chrome app or Mac app): Chrome app
 3. OS details: Windows 10

**Comment by sdnts** [comment]
@mahendranv That's a valid concern, adding this as an usability feature :)

**Comment by a85** [comment]
This is available now.
