### ISSUE TITLE
Unexpected character repeat bug.

### ISSUE THREAD

**Issue by Edunga1** [a85/POSTMan-Chrome-Extension#2648]
1. Postman Version: 4.9.3
 2. App (Chrome app or Mac app): Mac app
 3. OS details: OSX Sierra 10.12.2
 4. Is the Interceptor on and enabled in the app: No
 5. Did you encounter this recently, or has this bug always been there: N/A
 6. Expected behaviour: N/A
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app): N/A
 8. Screenshots (if applicable)

When I write a request description in Korean, unexpected characters are repeated.

<img width="499" alt="screen shot 2017-01-20 at 3 29 21 pm" src="https://cloud.githubusercontent.com/assets/11594584/22139125/a1331a90-df27-11e6-80ac-61564fd7e0d2.png">

I just typed 14 characters ("가나다라마바사아자차카타파하"), but there are too many unexpected additional characters.

**Comment by vegetableman** [comment]
@Edunga1 Thanks for reporting this issue 👍 . We are in the midst of replacing the built-in editor with a better one. Will keep you posted in this thread.

**Comment by numaanashraf** [comment]
@Edunga1 Hi, could you verify if this is happening with our latest version? Postman v6.1.4.

**Comment by Edunga1** [comment]
@numaanashraf Sorry, I'm too late. it has been resolved on v6.1.4! thank you.
