### ISSUE TITLE
Importing v2 Collection has OverWritten Update.exe

### ISSUE THREAD

**Issue by sandwichesandtoast** [a85/POSTMan-Chrome-Extension#2649]
Version/App Information:
1. Version 4.9.3 win32 10.0.14393 / x64
2. Stand-alone Installer
3. Windows 10 Pro
4. I do not believe that "Interceptor" is available
5. Recent bug, but I've not done many imports previously
6. Expected behaviour: Import v2 collection from Desktop into available collections
7. The logs I've found show nothing interesting; is the collection import logged?

Steps to reproduce the problem:
1. Get a v2 collection sent to you by a colleague
2. Open the "Import" dialogue ion via the "Import" button next to "Runner"
3. Click to browse
4. Select the collection
5. Import
6. Mileage may vary, my "Update.exe" under "C:\Users\user\AppData\Local\Postman" was overwritten

**Comment by sdnts** [comment]
Hi @Skeksis! We do not write to the file system from anywhere in the app, so this looks very unlikely. Can you reliably reproduce this or was this a one time thing?
Also, how did you conclude that Update.exe was overwritten? Was it deleted?
