### ISSUE TITLE
Emacs version allowed

### ISSUE THREAD

**Issue by gianisegatto** [a85/POSTMan-Chrome-Extension#2650]
I'd like to know which version of emacs can I use in my javascript for pre-requests and tests?

Kind regards,
Giani Segatto

**Comment by sdnts** [comment]
@gianisegatto The test / pre-request script sections aren't based on a specific version of emacs. They're merely a text editor with JS syntax highlighting.
Feel free to reopen this if I misunderstood :)

**Comment by gianisegatto** [comment]
Hi Siddhant Sinha,

Thanks for your response. However, my doubt is about the javascript code that I can write in the pre-script.
We had tried to use Map object and the code didn't work in postman.
These are the Map reference
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map
https://tc39.github.io/ecma262/#sec-map-objects

Kind regards,
Giani Segatto

**Comment by sdnts** [comment]
Ah, JS code in the pre-request / test scripts is written in ES5. Since Maps are part of the ES6 spec, they won't work right away.

**Comment by gianisegatto** [comment]
Cool,

Thanks a lot for your fast answer.
Do you have some idea when does postman will allow ES6?

Kind regards,
Giani Segatto

**Comment by sdnts** [comment]
The Chrome app is limited by the version of Chrome you're on. So, you might now be able to use all ES6 features there.
However, on our [native apps](https://getpostman.com/apps), you can use Maps and other ES6 JS. As of v4.9.3, we use Chrome 53 in the native app, so it should support all ES6 syntax.

**Comment by gianisegatto** [comment]
Cheers mate, thanks a lot for your help
