### ISSUE TITLE
Reordering the keys in form-data loses file information

### ISSUE THREAD

**Issue by mtx62** [a85/POSTMan-Chrome-Extension#2651]
1. Postman Version: 4.9.2
 2. App (Chrome app or Mac app): Chrome
 3. OS details: OS X / x86-64
 4. Is the Interceptor on and enabled in the app: no
 5. Did you encounter this recently, or has this bug always been there: first time
 6. Expected behaviour: you can't know 
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 8. Screenshots (if applicable)

I'm sorry I can't fill all your requirements because it's a small bug,
simply when I relocate the image data of the form-data the keys change and the locations of the images relocated also (visibly) but not during sending of the request.

Best regards.

**Comment by sdnts** [comment]
@mtx62 When you say you relocate the form-data keys, do you mean you're reordering the keys or you're relocating the file on your file system?

**Comment by mtx62** [comment]
I believe reordering is the right word

**Comment by numaanashraf** [comment]
Fixed in Postman v7.0
