### ISSUE TITLE
File Post with no content

### ISSUE THREAD

**Issue by dxkite** [a85/POSTMan-Chrome-Extension#2652]
1. Postman Version: 4.9.2
 2. App (Chrome app or Mac app): Chrome
 3. OS details: Windows 10 Pro
 4. Is the Interceptor on and enabled in the app:
 5. Did you encounter this recently, or has this bug always been there:
 6. Expected behaviour: can't post  file as usual.
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 8. Screenshots (if applicable)

1. Send File First.
![image](https://cloud.githubusercontent.com/assets/7450707/22179779/6a21f93c-e098-11e6-883a-8ce62729fd5b.png)
2.  Send it again with this header:
![image](https://cloud.githubusercontent.com/assets/7450707/22179773/4253f1b2-e098-11e6-8ba3-b7d052951f3b.png)

**Comment by vegetableman** [comment]
@DXkite Could you follow the steps listed on https://www.getpostman.com/docs/errors and verify the network request being sent on the devtools. Also, you could send a POST request to `https://echo.getpostman.com/post` (which will spit out the content on the response) to check whether file upload is working.

**Comment by madebysid** [comment]
@DXkite Could you provide a little more detail as to what the issue is? Can you not POST a file at all? If so, could you try POSTing a simple file to `https://postman-echo.com/post`? This is a test service that should allow you to confirm if the problem lies with the app or with your server.

**Comment by dxkite** [comment]
The upload file module working at first,But  when  POST  again( Without choose file) ,The POST Request Only has a boundary.


Happy Chinese NewYear!  :small:

**Comment by prashantagarwal** [comment]
Can you update to the latest postman app and verify if you are still seeing this issue.
