### ISSUE TITLE
Save dialogs too long (height), buttons invisible.

### ISSUE THREAD

**Issue by gregjan** [a85/POSTMan-Chrome-Extension#2653]
1. Postman Version: 
 2. App (Chrome app or Mac app): 4.9.3 Linux AND 4.9.2 (Chrome App)
 3. OS details: Ubuntu 16.04
 4. Is the Interceptor on and enabled in the app: No
 5. Did you encounter this recently, or has this bug always been there: recently noticed
 6. Expected behaviour: I should be able to see the bottom edge of the dialog window and the buttons near the bottom. Instead the dialog is longer than the main window, with the lower edge and buttons hidden.
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 8. Screenshots (if applicable)

0. Use CTRL-plus to zoom the PostMan window to an acceptable size for your screen resolution.
1. Create a request
2. Hit "Save".
3. Dialog opens, but buttons are invisible.
2. With my normal screen settings the Save buttons are not visible and I cannot scroll or drag the window to reach them.

NOTE: I was able to "fix" the issue by using CTRL-minus to zoom the app way out. Then the bottom of the dialog is visible.

**Comment by vegetableman** [comment]
@gregjan Thanks for posting this issue 👍 . Will keep you posted on this thread.

**Comment by vegetableman** [comment]
@gregjan Could you update to the latest version `4.10.3` and check if the issue still exists?. Also, You could zoom in and out, even if the dialog is open.
