### ISSUE TITLE
Suboptimal use of space for request urls in 2 pane mode

### ISSUE THREAD

**Issue by Nopik** [a85/POSTMan-Chrome-Extension#2654]
When using Postman in 2 columns mode (request on left, response on right), the text input for URL is relatively short, whereas there is a plenty of space to the right:
![image](https://cloud.githubusercontent.com/assets/554841/22242295/1758e8e6-e223-11e6-8608-96770de7b6e2.png)

**Comment by vkaegis** [comment]
@Nopik Thanks for reporting this! We're considering an alternative where the URL bar extends for the width of the tab. Will keep you updated.

**Comment by vkaegis** [comment]
Hey @Nopik, the URL bar now extends to the full width in the two-pane view. Closing this issue, feel free to open another if you have more feedback around this!
