### ISSUE TITLE
Postman App crashing upon receiving response

### ISSUE THREAD

**Issue by mverdier** [a85/POSTMan-Chrome-Extension#2655]
1. Postman Version: 4.9.2
 2. App (Chrome app or Mac app): Chrome app, Chrome 49.0.2623.87
 3. OS details: linux / x86-64
 4. Is the Interceptor on and enabled in the app: No
 5. Did you encounter this recently, or has this bug always been there: Started happening about a week ago or so
 6. Expected behaviour: Getting an answer from my API endpoint
 7. Console logs: There's not much being logged upon crashing sadly, I can't provide anything more than basic logging information like such: http://pastebin.com/muFKFgU1

To reproduce the problem, I can just send a few request to random GET endpoints (haven't tried with POST) and surely at some point one of them will crash the app. It usually takes like 2, 3, up to a maximum of 4 successful requests to make it crash. It only seems to crash upon 200-OK responses, none of the 403-Forbidden responses seem to crash it.

**Comment by vegetableman** [comment]
@mverdier Thanks for posting this issue 👍 . The occurrence of this issue on the chrome app is quite intermittent as reported by few others and hard to reproduce. Could you verify if the issue is reproducible on the native app?.

**Comment by mverdier** [comment]
@vegetableman I just tried using the same API endpoints on the native Linux x64 app, the issue doesn't seem to be reproducible there.
