### ISSUE TITLE
Add ability to export test results to html

### ISSUE THREAD

**Issue by DanielStoica85** [a85/POSTMan-Chrome-Extension#2656]
Please add the ability to export the collection runner test results in a html page that can be easily shared and read by other team members.

**Comment by sdnts** [comment]
@DanielStoica85 If you want to get run report in an HTML format, you should also look into [Newman's HTML reports](https://github.com/postmanlabs/newman#html-reporter-options).

Newman is a command line collection runner, so it'll behave exactly the same as the native app's Collection Runner. You can give it a collection and generate an HTML report.

**Comment by DanielStoica85** [comment]
@madebysid Yes, I did not try Newman yet, I will in the near future, but I still think it would be really useful to be able to generate prettier HTML reports from the collection runner too.

**Comment by a85** [comment]
@DanielStoica85 Exporting HTML files within the app has a lot of issues. We'll be transitioning over to a plug-in based model in the near future that will let users write custom converters. For now, I'd recommend using the newman reporters or writing a custom external converter for exporting from JSON to HTML.

**Comment by GeekMustHave** [comment]
I have tried Newman and in some cases, the tests that work in Postman and show up in runner do not show up at all in Newman.  It does 3 of the 10 test and just stops displaying the test results at all.

I've tried to go back and figure out what test is causing the problem and after a few hours gave up.

**Comment by ykhodos** [comment]
+1

**Comment by Zakir99458** [comment]
Is it resolved? I mean it is an old issue and still, I am not able to generate an HTML report using Postman directly. I have to use Newman instead. 
Please let me know.
