### ISSUE TITLE
Collapse all folders in one click

### ISSUE THREAD

**Issue by nagyf** [a85/POSTMan-Chrome-Extension#2657]
This is a minor problem, but a really annoying one.
Please, add a button to be able to collapse all folders on the collections tab in one click (maybe next to the sorting button?).
I have ~30 folders right now which will increase with time, and it's really hard to find something in the list when a lot of folders are open.
Right now the only option is to collapse them one by one, but I think a "Collapse all" button would greatly enhance the UX.

**Comment by DanielStoica85** [comment]
Good idea!

**Comment by vgadolin** [comment]
I agree it is needed.  It would also be great if you could do the same in the builder on the tabs that are opened

**Comment by vegetableman** [comment]
@vgadolin You could right click on the tab name to close all tabs. 
![screen shot 2017-03-02 at 6 46 56 pm](https://cloud.githubusercontent.com/assets/1330851/23552598/c217e704-0042-11e7-8aea-fd9ae467799a.png)

**Comment by vgadolin** [comment]
ok thank you for this information and for adding this!

**Comment by josslamberti** [comment]
I'd suggest having a 'collapse all collections' button as well, collapsing both folders and collections.

**Comment by anishkny** [comment]
Workaround for anyone stumbling on this:

1. Click on filter text box (top left)
1. Enter some character (e.g. "a")
1. Delete it.
<img width="1202" alt="Screen Shot 2020-01-29 at 12 28 18 PM" src="https://user-images.githubusercontent.com/357499/73394706-f0c01500-4292-11ea-96c3-1841a9355376.png">

This collapses all folders. Checked on Postman Version 7.16.0 (7.16.0)

**Comment by giridharvc7** [comment]
Thank you for your patience, We've introduced this feature in v10.13. You can now use `Option+Click` to expand and collapse all children of an element. This work for collections and folders. 

https://user-images.githubusercontent.com/1040583/232968843-ecd9e63c-3d65-4bee-ae12-fba2dd55107e.mov


Please give this a try and let us know what you think
