### ISSUE TITLE
Update postman-docs to include sandbox library versions

### ISSUE THREAD

**Issue by cchretien** [a85/POSTMan-Chrome-Extension#2658]
1. Postman Version: Latest documentation
 2. App (Chrome app or Mac app): Latest
 3. OS details: All platforms
 4. Is the Interceptor on and enabled in the app: N/A
 5. Did you encounter this recently, or has this bug always been there: Always been around
 6. Expected behaviour: Expect to know what version of libraries Postman loads so we know what library functions are available. Links always reference the latest documentation of each library 
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 8. Screenshots (if applicable)

When looking up the postman docs to see what library support there is in the sandbox the links reference the latest documentation for each library (i.e. lodash, SugarJS). You have to dig pretty deep to understand what version of library is loaded then lookup the right version of documentation online to see what's available.

It would save a lot of time for people if the postman docs would at least list the version of package that is included in the sandbox. The user can then lookup documentation for that version.

**Comment by a85** [comment]
Updated here: https://www.getpostman.com/docs/postman/scripts/postman_sandbox_api_reference

**Comment by pgg** [comment]
In the mac app Version 5.0.0, pre-req. console.log(_.VERSION) outputs 3.10.1 and not 4.17.2 as indicated by the above api reference . . . in https://github.com/postmanlabs/postman-sandbox/blob/develop/package.json you have in dependencies "lodash": "4.17.2" but in devDependencies you have: "lodash3": "3.10.1" . . .

**Comment by czardoz** [comment]
@pgg the version in the sandbox is v3.10.1 (we cannot upgrade and break everyone's scripts) just like that.

**Comment by czardoz** [comment]
It's here (in case you're interested): https://github.com/postmanlabs/postman-sandbox/blob/711a505ff9a2f934b257f7ecd68f06229471ecc8/lib/sandbox/postman-legacy-interface.js#L6

**Comment by pgg** [comment]
@czardoz  Was not expecting you to break everyone's scripts, just pointed out that you state the sandbox is on v4 where in fact it is on v3 . . . https://www.getpostman.com/docs/postman/scripts/postman_sandbox_api_reference
