### ISSUE TITLE
Saved collection call SOAP Webservice not works in postman-app and works in postman-chrome

### ISSUE THREAD

**Issue by ghost** [a85/POSTMan-Chrome-Extension#2659]
1. Postman Version: Postman for windows: 4.9.3 , Postman chrome: 4.9.2
 2. App (Chrome app or Mac app): Windows App and Chrome App
 3. OS details: Windows 10  win32 10.0.1.4393 / x64    Chrome App: Chrome 55.0.2883.87
 4. Is the Interceptor on and enabled in the app: enabled
 5. Did you encounter this recently, or has this bug always been there:
 6. Expected behaviour:

 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 8. Screenshots (if applicable)
![2017-01-25_17h06_05](https://cloud.githubusercontent.com/assets/19286907/22298400/af013f06-e320-11e6-92f7-5009528169ba.png)
![2017-01-25_17h07_27](https://cloud.githubusercontent.com/assets/19286907/22298434/cee4388c-e320-11e6-9f37-59b1c7e87882.png)
![2017-01-25_17h08_18](https://cloud.githubusercontent.com/assets/19286907/22298473/e61a23f4-e320-11e6-9809-43a5aceec984.png)

Create collection about SOAP Webservices and execute on Chrome app  and works
Execute same on Windows APP and fails, also fails in NewMan after export collection from Chrome app.

Seems save BODY have characters doesn't works well when execute from Windows or newman.

**Comment by vegetableman** [comment]
@espiatsundiogroup Thanks for posting this issue :+1:. Could you open up the `Postman Console` and check if the the request body sent is valid. To open up the console, you could refer: https://www.getpostman.com/docs/errors

**Comment by ghost** [comment]
Hi,

I opened Postman Console from Desktop app amb Console from Chrome add on .

The body are different.

From Chorme Add on:

[cid:image001.png@01D27BAB.C8F2DFF0]



From Desktop Version:
[cid:image002.png@01D27BAB.C8F2DFF0]


I think  a problem is related with how parsing an XML body .

**Comment by vegetableman** [comment]
@espiatsundiogroup The screenshots are not visible. Could you upload them on this thread?

**Comment by ghost** [comment]
[cid:image001.png@01D27BD3.F7859B50]

[cid:image002.png@01D27BD3.F7859B50]

**Comment by vegetableman** [comment]
@espiatsundiogroup The attachments are being stripped out. You will need to manually upload them from this thread.

**Comment by ghost** [comment]
Desktop Version
![2017-01-31_10h20_50](https://cloud.githubusercontent.com/assets/19286907/22468582/18fffda0-e7c9-11e6-954b-9f646c04fab9.png)

Chrome addon version
![2017-01-31_10h20_03](https://cloud.githubusercontent.com/assets/19286907/22468586/1b53e850-e7c9-11e6-9412-843d897fc3d7.png)

**Comment by abhijitkane** [comment]
@espiatsundiogroup Are you still seeing this with v5.2.0 of the app?

**Comment by ghost** [comment]
Finally I realized about the error.
The problems comes from wrong Header, A Header Content-length.
From Chrome App this Header is ignored.
I delete this header and now works fine.
