### ISSUE TITLE
Feature request: indicate folders in "Run Results" in "Collection Runner"

### ISSUE THREAD

**Issue by TomBaxter** [a85/POSTMan-Chrome-Extension#2660]
1. Postman Version: 4.9.3
 2. App (Chrome app or Mac app): Linux
 3. OS details: Ubuntu 16.04.01
 4. Is the Interceptor on and enabled in the app: No, I think?
 5. Did you encounter this recently, or has this bug always been there: Always
 6. Expected behavior: Indication of folder when viewing "Collection Runner" "Run Results"

**Comment by sdnts** [comment]
@TomBaxter This is something that's on our roadmap. Will keep you updated here :)

**Comment by saswatds** [comment]
This feature is supported in the latest version app. Closing issue
