### ISSUE TITLE
JSON string nested in JSON response being eliminated

### ISSUE THREAD

**Issue by TheNate-zz** [a85/POSTMan-Chrome-Extension#2662]
We have a partner returning a JSON string nested **inside** a JSON object.  _Please_ don't ask me why.  All I know is that at least one older version of PostMan still showed the JSON string, and the newest one does not.  Is this a PostMan bug?  Or is this just such _crappy_ JSON from our partner that PostMan refuses to process it? 

1. Postman Version: 4.9.3
 2. App (Chrome app or Mac app): Mac app
 3. OS details: Sierra 10.12.2
 4. Is the Interceptor on and enabled in the app: No
 5. Did you encounter this recently, or has this bug always been there: Recently encountered (but upgraded from 2.x)
 6. Expected behaviour: See screenshots, below 
 7. Console logs: Nothing relevant
 8. Screenshots (if applicable)
a. - response to GET call in browser:
![screen shot 2017-01-26 at 2 53 38 pm](https://cloud.githubusercontent.com/assets/5301925/22348052/35622814-e3d8-11e6-8307-668526722a14.png)
b - response to GET call in PostMan:
![screen shot 2017-01-26 at 2 53 01 pm](https://cloud.githubusercontent.com/assets/5301925/22348064/3ddd3358-e3d8-11e6-8e23-9dd8b04763fa.png)

**Comment by sdnts** [comment]
@TheNate Can you see the actual value in the `Raw` tab in the response section?

**Comment by TheNate-zz** [comment]
No, I cannot:
![screen shot 2017-01-27 at 9 26 30 am](https://cloud.githubusercontent.com/assets/5301925/22374130/da4c6caa-e472-11e6-894a-471cad8171f4.png)

**Comment by sdnts** [comment]
@TheNate The Raw tab shows the request as received by Postman, so I'm guessing this isn't sent at all(?). Since this is a string, it shouldn't be treated any different from other strings. Can you see if a cURL request returns the expected body?

**Comment by TheNate-zz** [comment]
In the first screenshot, above, you can see the results of making the call in a web browser - the data not displayed by PostMan **is**, indeed, being returned.  Here's a sample with "Paw"...

![screen shot 2017-01-30 at 9 33 05 am](https://cloud.githubusercontent.com/assets/5301925/22426992/6ccfc4c4-e6cf-11e6-8cfe-408927c42fca.png)

**Comment by sdnts** [comment]
@TheNate We were able to replicate the issue and get to the bottom of this. 
We found that some characters in the URL weren't being encoded properly, which was causing this.
We've fixed this internally, and will be rolling out a fix for this soon. Will keep you informed here.

Meanwhile you can download the canary build here, where the fix already went in:

OSX: https://dl.pstmn.io/download/channel/canary/osx_64
Windows 32-bit: https://dl.pstmn.io/download/channel/canary/windows_32
Windows 64-bit: https://dl.pstmn.io/download/channel/canary/windows_64
Linux 32-bit: https://dl.pstmn.io/download/channel/canary/linux_32
Linux 64-bit: https://dl.pstmn.io/download/channel/canary/linux_64

**Comment by TheNate-zz** [comment]
Great, thanks!

**Comment by sdnts** [comment]
@TheNate v4.10.2 should fix this problem. Can you try to update and verify?
