### ISSUE TITLE
API oauth signature not valid

### ISSUE THREAD

**Issue by rpratsch0936** [a85/POSTMan-Chrome-Extension#2663]
Using OAuth 1.0 Authorization and I am providing a consumer key and consumer secret (no token is supposed to be required). Trying to use the Talent by Torsh API. It keeps giving me the error : API oauth signature not valid. I am not sure why this is happening.

 1. Postman Version: newest version
 2. App (Chrome app or Mac app): Chrome
 3. OS details: Windows 8.1
 4. Is the Interceptor on and enabled in the app:
 5. Did you encounter this recently, or has this bug always been there: Recenlty
 6. Expected behaviour:
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 8. Screenshots (if applicable)

![image](https://cloud.githubusercontent.com/assets/14165649/22385142/90aa117e-e49f-11e6-8336-913b33361f1d.png)

![image](https://cloud.githubusercontent.com/assets/14165649/22385168/9bf3241c-e49f-11e6-9561-4c4f08ce1923.png)

![image](https://cloud.githubusercontent.com/assets/14165649/22384981/be8b915e-e49e-11e6-9cbc-cccc96210b48.png)

**Comment by vegetableman** [comment]
@rpratsch0936 Could you select the option `x-www-form-urlencoded` on the `Body` tab, and then 
click on `Update Request`? and check if the `POST` request works.

`form-data` is not a valid conduit for oAuth parameters. This bug is fixed in the native app such that Clicking on `Update Request` will only update  `x-www-form-urlencoded` and not `form-data`.

**Comment by rpratsch0936** [comment]
Thank you for getting back to me on this. I tried using the option x-www-form-urlencoded but it sill gives me the same error message. See screenshot below. Is there anything else that I can try to solve this? I appreciate your assistance!

![image](https://cloud.githubusercontent.com/assets/14165649/22424675/8db6b7ba-e6c5-11e6-8431-12a90647c478.png)

**Comment by rpratsch0936** [comment]
Ran a few more tests and the issue got resolved. Thank you for your assistance!
