### ISSUE TITLE
LinuxApp Korean Input Method Does Not Work Correctly

### ISSUE THREAD

**Issue by daemin-hwang** [a85/POSTMan-Chrome-Extension#2665]
1. Postman Version: Version 4.9.3
 2. App (Chrome app or Mac app): Postman for Linux
 3. OS details: linux 4.4.0-53-generic / x64
 4. Is the Interceptor on and enabled in the app: -
 5. Did you encounter this recently, or has this bug always been there: always
 6. Expected behaviour: Duplicate words should not be entered / Korean input method should operate normally.
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app): -
 8. Screenshots (if applicable)

**Current problem**
![image](https://cloud.githubusercontent.com/assets/1132756/22497212/41b81582-e893-11e6-8070-64e700d78edc.png)

**Expected behaviour**
![image](https://cloud.githubusercontent.com/assets/1132756/22497233/73f94f52-e893-11e6-918f-b77ecadef446.png)

Duplicate words should not be entered / Korean input method should operate normally.

**Comment by sdnts** [comment]
@s20307 We've made some changes to the input editor that should fix your issue as well. The fix will go out with 4.10, I'll let you know here when it is out.

**Comment by sdnts** [comment]
@s20307 Can you see if this is still a problem with 4.10.2?

**Comment by ryan1st** [comment]
Though not being original author, I also have been experiencing this issue and watching this thread!
So excited with the fix!  So far, it seems the issue is gone now!  I can write Korean freely as English now. Thank you so much!  👍 💯
