### ISSUE TITLE
Mac OS - cannot PUT to AWS S3 presigned URL (works in chrome version)

### ISSUE THREAD

**Issue by maciekdragan** [a85/POSTMan-Chrome-Extension#2666]
1. Postman Version:4.9.3
 2. Mac app
 3. OS details: OS X Yosemite 10.10.5 
 4. Is the Interceptor on and enabled in the app: don't know
 5. Did you encounter this recently, or has this bug always been there: recently
 6. Expected behaviour: send PUT with presigned URL to AWS S3
-----------
1. Get presigned URL from AWS S3
2. Try to upload to the URL some data
3. You will receive
```xml
<Error>
    <Code>SignatureDoesNotMatch</Code>
    <Message>The request signature we calculated does not match the signature you provided. Check your key and signing method.</Message>
...
...
</Error>
```
The best part: It works in chrome app version !!! 
I lost nearly whole day looking for bug in my application. Mac OS version and chrome
version do not have the same engine ?

**Comment by sdnts** [comment]
@maciekdragan The native apps are built on top of [Postman Runtime](https://github.com/postmanlabs/postman-runtime). We're looking into what might be causing your problem.

**Comment by harryi3t** [comment]
@maciekdragan could you help me reproduce this issue.
I am not able to generate the pre-signed URL
I tried to follow the docs (using golang) but could not get it working.
How are you generating yours?

**Comment by shanepadgett000** [comment]
My company is experiencing the same issue. Was this ever resolved? We get a presigned URL and try to PUT an image. It works in the Chrome version but does not work in the Mac or Windows desktop versions.

**Comment by harryi3t** [comment]
@sp-tenovos We did not get any feedback on this issue. Could you let me know on how to generate this pre-signed URL so that I can reproduce this issue? If there is some documentation for this, could you also share that link?
