### ISSUE TITLE
issue when i try convert from form-data to raw (JSON)

### ISSUE THREAD

**Issue by macro-dadt** [a85/POSTMan-Chrome-Extension#2667]
i can send a request successfully by form-data, but not work when i try with raw (JSON). Any help is appreciated. it seem data can reach to server, but server can not parse from it
![screen shot 2017-02-02 at 14 15 34](https://cloud.githubusercontent.com/assets/21075652/22538008/ae7733aa-e952-11e6-850a-3bc660ffbdea.png)
![screen shot 2017-02-02 at 14 15 57](https://cloud.githubusercontent.com/assets/21075652/22538007/ae77123a-e952-11e6-9295-41e2ff3c0203.png)
![screen shot 2017-02-02 at 14 16 13](https://cloud.githubusercontent.com/assets/21075652/22538009/ae783f2a-e952-11e6-8fb0-e97a5e545df4.png)

**Comment by sdnts** [comment]
@macro-dadt Since the data reaches the server properly, I'd recommend looking at your server code to figure out why a parse is failing.

**Comment by varmalx** [comment]
is there any one able get it
