### ISSUE TITLE
When a timeout occur during a  test running , postman hangs. 

### ISSUE THREAD

**Issue by polimreis** [a85/POSTMan-Chrome-Extension#2668]
Version/App Information:

 1. Postman Version: 4.93
 2. App (Chrome app or Mac app): Mac app ( Chrome app stil in 4.9.2 version )
 3. OS details: MAC OS X EL Capitain
 4. Is the Interceptor on and enabled in the app:
 5. Did you encounter this recently, or has this bug always been there: This occur just in this version, on version 4.9.2 this doesn't happen 
 6. Expected behaviour: if will occur a timeout , postman must continue run the other tests

 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
![1486043064](https://cloud.githubusercontent.com/assets/14127521/22552119/b51741be-e93e-11e6-8731-9b04cfd419c6.png)
![1486043000](https://cloud.githubusercontent.com/assets/14127521/22552118/b4fcb984-e93e-11e6-83aa-4dba76e4fd7e.png)

 8. Screenshots (if applicable)
![1486042789](https://cloud.githubusercontent.com/assets/14127521/22552117/b4fb630e-e93e-11e6-8c5f-eae92f9d5edc.png)

Steps to reproduce the problem:

Create a collection with 3 request
The second request must have timeout error
Run the collection
during the second request, the postman hangs and doesn't run the third request.

**Comment by polimreis** [comment]
It doesn't occur in chrome version , because chrome version is on 4.9.2 , and as I told, This start happen on 4.9.3 version

**Comment by sdnts** [comment]
@polimreis Thanks for reporting this, I'm taking a look at this. Will report here when I make progress :)

**Comment by sivcan** [comment]
Hi, 
I advise you to kindly update to the [latest version](https://www.getpostman.com/apps) of the native app.
Feel free to reopen this issue if it still persists in the latest version.
