### ISSUE TITLE
Debugging from DevTools for Native App

### ISSUE THREAD

**Issue by hottes** [a85/POSTMan-Chrome-Extension#2670]
1. Postman Version: 4.9.3
 2. App (Chrome app or Mac app): Postman for Windows
 3. OS details: win32 6.1.7601 / x64
 4. Is the Interceptor on and enabled in the app: Off
 5. Did you encounter this recently, or has this bug always been there: new installation
 6. Expected behaviour: With the DevTools window open, the code execution should pause when hitting the debugger; statement in the Tests script.
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 8. Screenshots (if applicable)

I have just installed the Windows Native App. When I launch the DevTools window and run a request with the 'debugger;' command in it's Tests, the code does not pause when it gets to the debugger; command. I have the Debugging for packed apps flag enabled. Any input on how to enable debugging on the native app would be appreciated.

**Comment by numaanashraf** [comment]
Hi @hottes, pre-request and test scripts run in a special sandboxed node process in the native app, and do not support debugger statements at the moment. The recommended way right now is to use `console.log`s to print out debug information and view them on the Postman Console (Ctrl + Alt + C)

**Comment by skyboyer** [comment]
are there any news on this feature? could we use remote debugging to debug that "sandboxed node process"?
