### ISSUE TITLE
What technology is behind postman?

### ISSUE THREAD

**Issue by chrisiek** [a85/POSTMan-Chrome-Extension#2671]
Perhaps very off topic question but I must ask about it.

What technology was used to program this nice tool?

**Comment by sdnts** [comment]
@chrisiek Glad to hear you like the app!
The Postman native app is built on top Electron, with the view layer written in React. Some parts use Redux for data management, while others use good ol' Backbone :D

**Comment by 6Hat** [comment]
Good question... was amazed at the Postman UI myself and looked it up. I am an ASP.Net MVC developer (along with a few other technologies) and had somehow never heard of Electron until this post. I was absolutely amazed at what I had discovered: [Electron](https://www.youtube.com/watch?v=8YP_nOCO-4Q) 
This is everything I have been looking for as I have been researching Self Hosting ASP.Net MVC apps recently... What I have found seems hacky. It is beautiful that there is a full highly used framework for this already. And judging by the Postman application it works very well!

**Comment by gianlazz** [comment]
@6Hat I know this is a long time later since your post but I too am a .NET developer and find Electron super exciting. I've made a blog post about setting up an electron app with angular and aspnet core webapi bundled in for the backend running on kestrel.

https://lazz.tech/blog/electron-netcore-2-0-webapi-w-kestrel-server-backend-bundled/

**Comment by ayazsayyed** [comment]
its purely built on html css and good ol' Javascript :D

**Comment by ghost** [comment]
It is slow like a hell. I assumed it is Electron and then I googled it and now I am here to confirm my assumptions.

**Comment by ntodorov** [comment]
> It is slow like a hell. I assumed it is Electron and then I googled it and now I am here to confirm my assumptions.

Not sure what is slow for you? GPU situation is the only thing I saw slow with Postman. It is a sleak app.
Try using SoapUI - java written tool and compare it with Postman ...

**Comment by TepidDrink** [comment]
Being honest, Postman does seem iffy and I think it needs to work on this. 
I have a pretty good laptop, i5-6300U 2.5GHz 8GB, and as soon as I have more than 5 tabs open on Postman, the application slows right down.
I want to try Insomnia but I have too many Postman collections.

**Comment by AliAkberAakash** [comment]
Is is possible to develop a plugin for postman? Any hints on where to get started? I have no idea about web technologies.

**Comment by 6Hat** [comment]
@gianlazz You know I never did get into Electron... let alone with .Net. However this last year I've had the pleasure of picking up Blazor... which back when this was posted didn't exist yet... or at least I hadn't heard of it. I must admit I have been loving Blazor and have been wondering if you've had a chance to tinker with it yet? If so, how does is it compare with .Net Electron?

**Comment by mkbhru** [comment]
> ol'

Its not slow, just its startup time is slow which is time taken by electron to load sandboxed chromium libraries it requires to provide this much consistent ui in almost every platform.

**Comment by pc-magas** [comment]
Are there unoficial Postman apps that do not use Elentron. Sometimes Memory consumption spike and run out of memory.
