### ISSUE TITLE
Collection Runner - Need total run time of a particular collection

### ISSUE THREAD

**Issue by vgadolin** [a85/POSTMan-Chrome-Extension#2672]
1. Postman Version: 4.9.3
 2. App (Chrome app or Mac app): App (not Chrome)
 3. OS details: Windows 10
 4. Is the Interceptor on and enabled in the app: Yes
 5. Did you encounter this recently, or has this bug always been there: In Chrome version but not in Installed version
 6. Expected behaviour: In this screenshot, it shows the total run time from your docs:  https://www.getpostman.com/img/v1/docs/source/cr-3.png.  However the total run time is not displayed.
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app): N/A
 8. Screenshots (if applicable) - See above

 Run a collection in the installed version.  No total run time
![collectionrunner_totaltimenotthere](https://cloud.githubusercontent.com/assets/22482661/22570969/ab9ec774-e96b-11e6-83f8-d1ccb5c8c232.png)

**Comment by vkaegis** [comment]
@vgadolin Thanks for pointing this out! We'll be fixing this in the upcoming versions, will keep you updated.

**Comment by lostpebble** [comment]
Yep, just changed over to the installed version from Chrome and this is a sorely missed stat in the collection runner.

**Comment by nitinet** [comment]
Also not in the installed version for liinux

**Comment by mckennajones** [comment]
Any update on this?

**Comment by lostpebble** [comment]
Yea pretty bleak this isn't in yet. It may seem like a minor thing to the team - but it's actually a pretty **major** regression my eyes Seeing your entire performance run at a quick glance like that gives you lots of insight.

**Comment by mckennajones** [comment]
@lostpebble, if you export the results to JSON you can see the total run time. This is my work around. Not ideal, but it's one way to get the time.

**Comment by nathanawmk** [comment]
the total run time is in which format? seconds or miliseconds?

**Comment by mckennajones** [comment]
@nathanawmk My vote would be milliseconds.

**Comment by NikolaiTsepalov** [comment]
Any update?

**Comment by patricklambourne** [comment]
For me this is a significant missing feature. The collection runner functionality would be much more useful if it displayed a summary of the execution time for each run. I realise the number is available in the .json export but this is a clumsy workaround.

**Comment by teampurpledev** [comment]
Surprised to see this is still an issue in Postman 8.0. 

If console.time() was a supported function it would be easier to get the runtime from the UI - and not rely on the export or newman.

**Comment by NelemaniA** [comment]
I'm also missing this feature, since I am testing the status=200 in every request (pm.test("Status moet 200 zijn", function () { pm.response.to.have.status(200); });) and I am wondering if the total run time is affected by testing this in every request. So I was searching for the total runtime but could not find it (other than making an export after every run which is not a good workaround).
My collection is going to exist of probably thousands of tests, so not testing the status on every request could be a serious time saver.

**Comment by malvikach** [comment]
@NelemaniA, @all: 

We are happy to inform you that with Postman v10 you will be able to check the run duration for every run and a lot more! 

Giving you a sneak peek into how Postman version 10 would solve the problem mentioned on the thread:

<img width="1050" alt="Screenshot 2022-09-21 at 7 03 04 PM" src="https://user-images.githubusercontent.com/89449769/191517881-fea5775e-1d80-4e45-b3ca-3de9f6ed0e9a.png">


We have also introduced a 'Runs' tab for collections that will contain all your Collection Runs and some useful statistics about them!! 

<img width="1002" alt="Screenshot 2022-09-21 at 6 52 41 PM" src="https://user-images.githubusercontent.com/89449769/191515846-9aeb4f33-f002-4943-b0d8-191ae3e0da88.png">


The latest Postman v10 is not Generally Available(GA) right now, but we are giving early access to teams who might be keen on some of the features. If you are interested to give this a spin, please comment on this thread! 
[This](https://blog.postman.com/introducing-the-postman-cli-to-automate-your-api-testing/) is our blog that talks about the other Collection Run features we are offering along with the new Postman CLI. 
You can also set up some time with me to discuss further using [this](https://calendly.com/malvika-chaudhary/v10-feedback).
