### ISSUE TITLE
File upload issue when the request is loaded from history

### ISSUE THREAD

**Issue by Romanone** [a85/POSTMan-Chrome-Extension#2673]
Hello, here some information about this:
 1. Postman Version: 4.9.2
 2. App (Chrome app or Mac app): Chrome app
 3. OS details: Windows 10 x64

Steps to reproduce the problem: check video
[Little explanation on YouTube (https://youtu.be/Oc4h0YEf4PU)](https://youtu.be/Oc4h0YEf4PU)

**Comment by SamvelRaja** [comment]
@Romanone Thanks for the video 😄  We will provide you the update regarding this issue in the same thread soon.

**Comment by SamvelRaja** [comment]
Tracking in #4320
