### ISSUE TITLE
Importing a swagger.json from a Link fails.

### ISSUE THREAD

**Issue by pintux** [a85/POSTMan-Chrome-Extension#2674]
Importing the attached swagger.json generates an error, while importing the same swagger.json from file it works.

 1. Postman Version: 4.9.2
 2. App (Chrome app or Mac app): Chrome
 3. OS details: macOS Sierra 10.12.3
 4. Is the Interceptor on and enabled in the app: no, it's off.
 5. Did you encounter this recently, or has this bug always been there: 
 6. Expected behaviour: load the swagger
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 8. Screenshots (if applicable)
![postman](https://cloud.githubusercontent.com/assets/4560610/22585608/df6df182-e9f8-11e6-88d5-cc308a2d0afe.png)

1. Rename the attached file in swagger.json.
2. Serve the attached swagger.json by a web server 
3. in postman do: Import > Import from Link.

Downloading the file and "importing from link" works.

[swagger.json.txt](https://github.com/postmanlabs/postman-app-support/files/749965/swagger.json.txt)

**Comment by vegetableman** [comment]
@pintux Imported the swagger through `Import File`, `Import From Link` and by pasting Raw text on `Paste Raw Text` on the import dialog. In all the cases, the issue was not reproducible. Could you elaborate more?

**Comment by pintux** [comment]
@vegetableman Please, try importing the swagger from this URL: https://m3.vivocha.com/a/antonio/api/v2/swagger.json

Again, I'm experiencing the same error. Thanks.

**Comment by vegetableman** [comment]
Thanks for sharing the link @pintux. Will get back to you with more details.

**Comment by vegetableman** [comment]
@pintux The issue has been fixed internally. And will be part of the upcoming release ^_^.

**Comment by pintux** [comment]
@vegetableman cool! ;) Thank you.

**Comment by vegetableman** [comment]
@pintux Checkout the latest update. feel free to reopen if the issue still exists ^_^.
