### ISSUE TITLE
OAuth 2.0 Authorization does not use state parameter

### ISSUE THREAD

**Issue by kujenga** [a85/POSTMan-Chrome-Extension#2677]
1. Postman Version: 4.9.3
 2. App (Chrome app or Mac app): Mac app
 3. OS details: macOS Sierra 10.12.2 (16C67)
 4. Is the Interceptor on and enabled in the app: I don't think so?
 5. Did you encounter this recently, or has this bug always been there: I assume it has always been there
 6. Expected behaviour: The OAuth 2.0 spec specifies the availability of a "state" parameter [1] in Authorization requests. This parameter is strongly recommended for use due to security concerns [2]. The OAuth 2.0 authorization flow should make use of this parameter.
 7. Console logs: No logs are produced during this interaction

Our OAuth 2.0 server requires the presence of a "state" parameter for security reasons. Thus, we are currently unable to get an OAuth token using Postman. We would strongly prefer not to disable security requirements in order to make use of postman 😄. Thanks!

[1] https://tools.ietf.org/html/rfc6749#section-4.1.1
[2] https://tools.ietf.org/html/rfc6819#section-3.6

**Comment by vegetableman** [comment]
@kujenga Thanks for letting us know about the state parameter ^_^. Will keep you posted on this thread.

**Comment by harryi3t** [comment]
Please try out the latest version of Postman. It has the state parameter.
Please do me us know if you face any issue regarding this.


<img width="615" alt="postman" src="https://user-images.githubusercontent.com/5207331/42157641-df99dbaa-7e0b-11e8-8a6c-c64cd4c56537.png">
