### ISSUE TITLE
[Feature Request] - Ability to add pre-execution delay to individual requests

### ISSUE THREAD

**Issue by tariqghalib** [a85/POSTMan-Chrome-Extension#2679]
**Description:**
Currently we have ability to add delay to a folder, that puts a delay between each request for a complete folder for that collection run. It would be nice to have the ability to add a permanent delay to individual requests in a folder.

**Version/App Information:**

 1. Postman Version: 4.9.3
 2. App (Chrome app or Mac app): Windows app
 3. OS details: Windows professional x64
 4. Is the Interceptor on and enabled in the app: Enabled
 5. Did you encounter this recently, or has this bug always been there: Always been there
 6. Expected behaviour: Ability to add a delay to individual request

**Proposed Solution:**
FIRST
Add the delay in the popup that appears when we click the (...) for each request. Currently we have following options in the popup:
Edit
Duplicate
Delete

We could add another option:
Delay
You click it and we get to a setting where we can add a delay in ms

SECOND
Add the delay option as a tab. Currently we have following options that appears as tabs for a request:
Authorization
Headers
Body
Pre-request scripts
Tests

We could add another option
Delay

**Comment by sdnts** [comment]
@tariqghalib Just to make sure I understood this request correctly, do you mean separate delay values for each request in a collection when you run a collection?

**Comment by tariqghalib** [comment]
@madebysid Yes thats correct! I think that will be a very handy feature to make each test independent and will be helpful for runner performance by only adding delays where required. Also, will save an effort to add delay separately to individual requests (which BTW hangs postman windows client a lot, if we use JS sleep or wait)

**Comment by KumG** [comment]
+1

**Comment by O11o1** [comment]
Seconded, We have tests that involve creating a resource, a process that can take multiple minutes to complete if the systemis under heavy load. Currently, we have a GET test following it that polls for completing, but we still want to have about a minute delay on it so that we're not recklessly polling before it can possibly be done.

The ability to set a per-request delay for specific tests within a larger test folder would improve our workflow.

**Comment by rtabor** [comment]
+1

**Comment by harryi3t** [comment]
You can use either of the following solutions
### 1. Using collection runner
Set a delay while running a collection from the `Collection Runner`
![image](https://user-images.githubusercontent.com/5207331/30100932-259dffea-9308-11e7-88c7-423fff2e765d.png)


### 2. Using async flow from test scripts
Use setTimeout from pre-request script
![image](https://user-images.githubusercontent.com/5207331/30100840-cd256a06-9307-11e7-9afd-972d1e288359.png)
tip: you can even use the environment variables to control this delay in setTimeout

Please let me know if this doesn't work for you.
