### ISSUE TITLE
Environment variable converts '~' when using the Runner

### ISSUE THREAD

**Issue by blilienthal** [a85/POSTMan-Chrome-Extension#2683]
Hello Postman team!

Sometimes the `~` (tilde) in an environment variable changes to a combination of letters `\x7e`.
Seemes to me, that it occurs while syncing.

I changed it back to '~' several times, but it happens almost every second day.

 1. Postman Version: v4.9.3
 2. App (Chrome app or Mac app): Linux
 3. OS details: OpenSuse
 4. Is the Interceptor on and enabled in the app: ?
 5. Did you encounter this recently, or has this bug always been there: Since installation of native Linux app.

_EDIT: The problem appeared again and I found out, it's the hex code for `~`. Please fix that, I'm testing in an environment using mounts on my home directory, so I need the tilde_

**Comment by sdnts** [comment]
@blilienthal Thanks for reporting this. We're aware of this, and this appears to happen when you sync back environments from the Collection Runner. The fix is ready, and we'll push it out with our next release, which should be relatively soon. Will keep you informed here.

**Comment by sdnts** [comment]
@blilienthal Can you try updating to the latest version (4.10.2) and verify if this was fixed?

**Comment by blilienthal** [comment]
@madebysid Everything's working perfectly now! Thx!
