### ISSUE TITLE
[Feature Request] - Ability to add description to individual variables and parameters.

### ISSUE THREAD

**Issue by dhiva** [a85/POSTMan-Chrome-Extension#2685]
I would like to add individual description to the parameters of the request and display those description as part of the docs against each parameters. In certain scenarios the query parameters are not self explanatory and I want to add further description to explain the purpose of the parameter. The V2 JSON Schema supports description attribute for query parameters but there is no way to add these description using postman app and there is no option to add description to path variables. Could you please provide an UI functionality to add these descriptions to path variable and query parameters.

**Comment by sdnts** [comment]
@dhiva Thanks for the request! This is actually on our roadmap, I'll keep you informed if its progress here.

**Comment by sidd1004** [comment]
+1

**Comment by a85** [comment]
Available now in 5.0+
