### ISSUE TITLE
Postman Chrome App crashes and will not launch: Windows 7

### ISSUE THREAD

**Issue by dalejbrittain** [a85/POSTMan-Chrome-Extension#2686]
Postman Chrome App will not launch any more. 

I have been using the Postman Extension to chrome for over a year and recently it stopped launching.

Unfortunately, I have not been using Syncing feature so I have a few hundred calls and dozens of collections that I am hoping not to loose. 

Version/App Information:
-->
 1. Postman Version: 4.9.2
 2. Chrome App
 3. OS details: **Windows 7**
 4. Is the Interceptor on and enabled in the app: **NO**
 5. This just started happening a few days ago
 6. Expected behaviour: Postman opens
 7. Console logs (cannot get any logs because Postman never starts
 
Steps to reproduce the problem:
1. Try to launch Postman
2. Wait while it attempts to connect 
3. Postman crashes without ever opening
4. Receive dialog that says, "Postman has crashed. Click this balloon to restart the app.  (See attached)
![postman crashed](https://cloud.githubusercontent.com/assets/25623726/22747775/3833e14c-ede5-11e6-9ea8-33bc6258b1d4.png)
5. When I click the balloon, postman attempts to lauch, but it just crashes again without opening
6. The balloon is displayed again.
-->

**Comment by dalejbrittain** [comment]
After creating this ticket, I also emailed help@getpostman.com and got a the following response:

Hi Brittain,
Postman stores all its data locally in an application-specific indexedDB file. You could go to the url: chrome://indexeddb-internals, search for the text "chrome-extension://fhbjgbiflinjbdggehcddcbncdddomop" and copy the files listed out under paths for the extension, and move them back in after you've reinstalled Postman.
Let me know if any queries.
Regards,
Vignesh Anand,
Developer, Postman

**Comment by dalejbrittain** [comment]
My first thought to fix the crash problem was that I should just remove Postman and add it back. But I didn't do so because I didn't want to loose my collections. At the time I was not able to back up them up and without knowing the location where they are stored locally I was stuck.

In the above response Vignesh, shows the location, this was very helpful, because I was concerned about loosing my collections as I was not using the sync option.  

Using this information I was able to "copy" the DB file,  so I was free to remove Postman and add it back.

With a fresh copy of Postman I was able to add back the DB file, but every time that I launched Postman, it would remove the DB, so my collections were missing. I guessed that this was because the "current" log files and manifest file where not matching the DB file.

To get around this I closed Postman, then copied the DB file and renamed the log file to match the old file. After going that I was able to re-launch postman and this time the DB file was not deleted and when postman opened, all my collections were back!

So I am now back in business, thanks to the response from  Vignesh Anand.

**Comment by TiepB5518** [comment]
hi  dalejbrittain, i got the exact issue you had. i followed your instruction but i m a bit lost at where you said you renamed log file. which log file is it? there are 6 files in that chrome-extension_fhbjgbiflinjbdggehcddcbncdddomop_0.indexeddb.leveldb folders

**Comment by dalejbrittain** [comment]
I am sorry I didn't really post all the steps so I am not surprised that you are a bit lost.

Window 7 (not sure if these steps will work on any other OS)

Steps:
1) chrome://indexeddb-internals
2) Look for: chrome-extension://fhbjgbiflinjbdggehcddcbncdddomop
3) Under the "Paths:" section note the location of the "chrome-extension_fhbjgbiflinjbdggehcddcbncdddomop_0.indexeddb.leveldb" folder
4) Navigate to this location on your local system.
5) Copy this entire contents of this folder and save it to a safe location on your local system to be used later (your collections will be in DB file in this folder)
6) Remove the Postman extension from Chrome
7) Re-Add the Postman extension to Chrome
8) Launch Postman
Postman should open but it will be default settings with none of your collections
9) Close Postman
10) Navigate back to the path on location on your local machine that you noted in step 3
11) Delete the "MANIFEST" file
11) Copy the DB file and the "MANIFEST" file from your "Safe location" created in step 5
12) Paste the DB file and the "MANIFEST" file into the clean [ chrome-extension_fhbjgbiflinjbdggehcddcbncdddomop_0.indexeddb.leveldb ] folder.
13) Rename the log file in this folder to match the name of the log file in your "Safe location".

NOTE: There are a few files named "log" in this folder but only one with a .log extension which windows should identify as a type = Text Document. This is the one that you want to rename.

Most likely the name of the log file in your "Safe location" will be something like 000258.log and the one in the chrome extension folder will be 000001.log or 000002.log.  If you don't do this it seems that the "new" install of Postman does not see the collections DB file.

Hopefully this helps you out TiepB5518, good luck!

If this does work and you get your collections back I would strongly recommend creating an account for Postman and enabling the Sync function. Additionally you may consider using the App which can be downloaded directly from https://www.getpostman.com/apps

Personally,  have found the app to be a bit more response and more robust than the chrome extension. 

Either way good luck!

**Comment by TiepB5518** [comment]
hi dalejbrittain, thank you for detail instruction. really appreciated! i followed your instruction above but unfortunately that i still cannot open postman after copy the file (DB file and the "MANIFEST" and rename the .log file that match the old file i have (000224.log). not sure what else i do wrong but i tried this a few times and made sure postman can be opened after fresh reinstalled.

**Comment by dalejbrittain** [comment]
If you just paste in the DB file, does Postman open, but without your old collections?

**Comment by TiepB5518** [comment]
hi Dale, that is correct. if i just past in the DB, Postman open just fine but no old collection. and DB file got removed once i open Postman.

if i replaced new Manifest file with old file that Postman won't open, just spinning

**Comment by dalejbrittain** [comment]
Okay, try pasting in everything, except the .log file from the "old" folder
and rename the .log file to match what it was in the "old" folder.

**Comment by dalejbrittain** [comment]
when you paste in in the "Old" files choose the windows option to "overwrite/replace" existing files.

**Comment by TiepB5518** [comment]
hi Dale, 

that still does not let me open Postman

**Comment by avachnis** [comment]
hi Dale. 
I faced with the same issue on ubuntu 15.10 and applied your suggested steps (the 14 steps post) and it works for me.
Thanks!

**Comment by frozenrein01** [comment]
The SIMPLEST WORKING SOLUTION is to disable POSTMAN in your chrome's extension page.. then RUN the postman app again and it'll automatically open and be enabled in the extensions.

**Comment by Dinesh-Dewangan** [comment]
Same Problem Facing In Ubuntu 16. SomeOne help how to resolve it

**Comment by arora-abhishek** [comment]
Thanks @dalejbrittain 
Adding to dale's solution, you need to go to this folder -> /home/abhishek/.config/google-chrome/Default/Storage/ext/fhbjgbiflinjbdggehcddcbncdddomop/def/IndexedDB/
Here, you will find two more folders, one ending with blob another ending with db, choose the one ending with db.
on clicking the "chrome-extension_fhbjgbiflinjbdggehcddcbncdddomop_0.indexeddb.leveldb" you will come across approximately 6 files from which you need to copy the files ending with db and .log and also the Manifest one.
Copy these three files to another folder.
After re-installing, delete the newly created Manifest file.
Paste the manifest and db file from your saved folder to ->  chrome-extension_fhbjgbiflinjbdggehcddcbncdddomop_0.indexeddb.leveldb/
Now, rename the log file in this folder to match the name of the log file in your saved folder.
