### ISSUE TITLE
Can't import this file, no useful error message

### ISSUE THREAD

**Issue by cappslock** [a85/POSTMan-Chrome-Extension#2687]
1. Postman Version: 4.9.3
 2. App (Chrome app or Mac app): Mac
 3. OS details:
 4. Is the Interceptor on and enabled in the app:
 5. Did you encounter this recently, or has this bug always been there: recently
 6. Expected behaviour: file imports
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app): empty
 8. Screenshots (if applicable)

I am unable to import this file, either by downloading and dropping it in directly or by pulling it from the URL (http://docs.discourse.org/swagger.json).

Not getting any information out of the console unfortunately.

![screen shot 2017-02-08 at 12 24 26 pm](https://cloud.githubusercontent.com/assets/2079125/22751354/a797729c-edf9-11e6-892c-ff8891e3a16f.png)
![screen shot 2017-02-08 at 12 24 32 pm](https://cloud.githubusercontent.com/assets/2079125/22751358/a995f7bc-edf9-11e6-996c-5306163ae047.png)

Any clue why it's failing? I am not the author of the definition file, just trying to import it.

**Comment by bveenvliet** [comment]
I think the problem is with the line:

    "in": "formData",

when I remove it then it imports fine.
