### ISSUE TITLE
Native Windows App 4.9.3 Collection Runner inserts old login cookie with new one, causes 400 Bad Request and all requests stop

### ISSUE THREAD

**Issue by rzizza** [a85/POSTMan-Chrome-Extension#2688]
**Postman Version:** 4.9.3, win32 6.1.7601 / x64
 **App:** Windows Native Client
 **OS details:** Windows 7 Enterprise

I am running a Collection that includes a Login Request. 

**When I run this request in the **_Postman Window_**:**
It creates a session cookie, which I can view in the "Cookies" (found under "Save"). If I send a Log Out Request, this session cookie is removed. 
If I send a Login Request (creating sessionCookie1), and then another Login Request, another cookie, sessionCookie2 is created that overwrites sessionCookie1. Then all further requests I make use sessionCookie2. 

**When I run this request in the _Collection Runner:_**
If I already have an existing sessionCookie1, and then send a Login Request via Collection Runner, sessionCookie1 is sent in the header of the Login Request, and sessionCookie2 is created. Then the _next request that is sent fails_ because both sessionCookie1 and sessionCookie2 are sent in the header.
That request fails with "400 Bad Request", and the message "Open DevTools for more info", and Collection Runner stops running any further tests. 

If I then delete sessionCookie2 from the "Cookies" window and try to rerun in the Collection Runner, my Login Request will _still_ send sessionCookie2 in the header, and so I will still have two session cookies (sessionCookie2 and sessionCookie3 now) that will make further tests impossible. 

It also makes successful Logout impossible afterward.

**Expected Behavior:**
Collection Runner should overwrite the sessionCookie, like it does when running from the Postman Window. 

** This is not an issue in the Chrome App at all, and the same defect steps will not produce an issue. I was just hoping to use the Windows version since the Collection Runner and console in that app make debugging a lot easier.

**Steps to reproduce the problem:**

1. Before opening Collection Runner, I send a Login Request. This creates sessionCookie1. 

![image](https://cloud.githubusercontent.com/assets/10212761/22756075/ecff7d9c-ee13-11e6-9cc8-f55fd7ff8374.png)

2. Now I open the Collection Runner, and start running my Collection, which includes another Login Request. 

3. In my Collection Runner Login Request, I can see that the sessionCookie1 is sent in the Header of this new request.

![image](https://cloud.githubusercontent.com/assets/10212761/22756140/3588fda4-ee14-11e6-9d12-ba40f94c18cc.png)

4. This Collection Runner Login Request has also created a new sessionCookie2:

![image](https://cloud.githubusercontent.com/assets/10212761/22756259/7ed7adb6-ee14-11e6-8e19-f0ca5bead03e.png)

5. The next request that is sent after login will then try to send both sessionCookie1 and sessionCookie2, causing the whole Collection to fail and stop.

![image](https://cloud.githubusercontent.com/assets/10212761/22756364/e19251fe-ee14-11e6-9f4f-c2be1f5921b0.png)

6. Collection Runner gives me this message:

![image](https://cloud.githubusercontent.com/assets/10212761/22756410/0b2c3174-ee15-11e6-862a-c1656a4bc29a.png)

7. Dev Tools tells me this, which just tells me that the request wasn't successful:

![image](https://cloud.githubusercontent.com/assets/10212761/22756520/61d57daa-ee15-11e6-80fc-1e9cd99f4277.png)

Please let me know if there are any questions.

The only similar issue I found was this one, which was a Chrome App issue and has been closed: 
[#1425: an old cookie header continues to be injected even after I close postman ](https://github.com/postmanlabs/postman-app-support/issues/1425)

**Comment by sdnts** [comment]
@rzizza Thanks for letting us know. I'll take a look at this.

**Comment by Voldacar21** [comment]
Hi @madebysid, I have exactly the same issue. Some news about this?

**Comment by sivcan** [comment]
@rzizza @Voldacar21  Since the collection runner on starting the run, stores everything in memory
and cookies can't be cleared thus you've been facing this issue.

This feature request will solve this use-case
https://github.com/postmanlabs/postman-app-support/issues/3312

You can follow the same thread to receive updates.
