### ISSUE TITLE
Is there any method to export a collection from postman by using the command line tool(such as Linux bash shell script)?

### ISSUE THREAD

**Issue by xmeng1** [a85/POSTMan-Chrome-Extension#2691]
Feature enquire

Is there any method to export a collection from postman by using the command line tool(such as Linux bash shell script)?

**Comment by sdnts** [comment]
@xmeng1 Postman's app doesn't have a CLI export method, but you could take a look at [postman-collection](https://github.com/postmanlabs/postman-collection). Could you elaborate a little about what you're trying to do?

**Comment by xmeng1** [comment]
OK thank, I will check this SDK. 

According to my research on the JSON of the collection, I found that the collection JSON download by my API key (JSON-Remote) is different with the JSON export from the Packaged App (JSON-Local). 

Apart from the size of files (JSON-Remote > JSON-Local, such as my collection: 6M>1M), the value of `file` key is also different. In JSON-Remote, the value of `src` of type `file` is an object which contains the path. However, the Newman cannot parse this object. Actually, the `src` should be the string of path.

```
{"key":"data","type":"file","enabled":true,"warning":"","src":{"0":{"name":"mx1.png","path":"xxxxx/xxxx/mx1.png","lastModified":1485878813982,"lastModifiedDate":"2017-01-31T16:06:53.982Z","webkitRelativePath":"","size":223419,"type":"image/png"},"length":1}}
```

I am doing some work to convert the object of "src" to "path" automatically by Linux shell script. Meanwhile, I want to keep the JSON as small as possible. So I prepare to use the JSON-Local and copy the path value in JSON-Remote to the JSON-Local.

**Comment by sdnts** [comment]
@xmeng1 Which version of the app are you on? This used to be an issue with an older version, but we've fixed this since.
Can you try updating to the latest version of the app and retrying?

**Comment by xmeng1** [comment]
> 4.9.1
> linux 4.8.6-201.fc24.x86_64 / x64

OK, I will update to 4.9.3 and try again.

**Comment by xmeng1** [comment]
I try the new version and the result is same, I think my issue can be same with [#2331](https://github.com/postmanlabs/postman-app-support/issues/2331), the file parameter in form-data cannot save. And I will and new comment at that issue.

**Comment by sdnts** [comment]
Hey guys, we're working on a CLI tool for Postman.
The initial version will only be able to import collections, but I'm adding collection exports as a feature request for the CLI :)

**Comment by Sporky023** [comment]
Thank you @madebysid for addressing this.  I'm also interested in this feature, and my use case is that I want to include a Foreman export as json in my git repository for my app.  

I'd like to work this export into some kind of a git pre-commit hook, or at least have a command to do it so I can manually run the export before committing files.  

You mentioned that you'd add collection exports as a feature request for the CLI.  I'm looking at issues on the Newman repository at https://github.com/postmanlabs/newman/issues, but none of the issues either open or closed have the tag `feature request` and contain text "export".  

I'm not sure if you were referring to Newman as the CLI in your August 21 comment?

**Comment by metalcamp** [comment]
Any updates on this feature?

**Comment by sdnts** [comment]
Guys, there hasn't been major progress on this front yet, since all of us have been working on Workspaces. We'll get back to this soon, and will keep you updated on the progress.

**Comment by namgivu** [comment]
I'm looking for way to export Postman collection from CLI too - it's a tiring job to use mouse clicking and choosing file. Any update on this @madebysid

**Comment by StefNewton** [comment]
A CLI interface for Postman would be so helpful, please update on progress!

**Comment by billxinli** [comment]
+1 on this, would like to export a collection to git.

**Comment by Seluj78** [comment]
Agreed ! Would love a tool to automate exporting of collections too

**Comment by 0x6B386F** [comment]
+1. 
Sorry for +1 commment, but .. this is must have feature for me :-) Thank you

**Comment by zakiaziz** [comment]
Hey @madebysid it's been a few months. Don't want to be pushy, but would love an update! 😄

**Comment by Jeckerson** [comment]
+1 Our team need this feature!

IMO, by making CLI of Postman, current feature is in top list of "must have".

**Comment by pcockwell** [comment]
Currently trying to version control Postman collections in git while also differentiating environment strictly by branch in git. Current Postman Github integration only does backup to github, rather than allowing full versioning by branch/env/etc. Really need some for of CLI based exporting and importing so that we can complete the following workflow:
- Pull git repo
- Change to relevant environment based branch
- Import collection(s) into Postman
- Make changes (but DON'T SYNC TO POSTMAN API)
- Export collection(s) from Postman to local files
- Commit changes to git

@madebysid Has there been any progress at all on an export or import feature for the CLI?

**Comment by TomFaulkner** [comment]
+1 for this. Would love to be able to export and import queries programmatically to save and distribute through git.

**Comment by science695** [comment]
Would also like this. I have been exporting and checking my data into a local git server manually on a schedule. And would love to be able to automate it more frequently

**Comment by pgordon9** [comment]
Can't wait for this feature! Dev workflow will be much less error prone and require less verbal communication on check in processes.

**Comment by SeriousM** [comment]
We download the collection with an api call via curl to disc and check it
in. Straight forward and simple.

**Comment by zakiaziz** [comment]
@SeriousM  do you have a snippet of code or CLI command you can share with us?

**Comment by SeriousM** [comment]
> @SeriousM do you have a snippet of code or CLI command you can share with us?

sure! this is done with windows batch but you can easily convert it to bash.

```batch
SET target_folder=tests
SET postman_api_key=xxxxxxxx
SET postman_collection_id=xxxxxxxxx

if not exist "%target_folder%" mkdir %target_folder%

curl -X GET https://api.getpostman.com/collections/%postman_collection_id% -H "X-Api-Key: %postman_api_key%" -H "Cache-Control: no-cache" -o %target_folder%\newman_spec.json

```

The collection id can be found if you query `https://api.getpostman.com/collections/` with the api key.

**Comment by itsdarrylnorris** [comment]
Hey @SeriousM , This works great only for the export part of it. However, it will be nice to have something we can use to automatically import into the postman collection and we can see it in the UI.

From what I have read online they are using [LevelDB](http://leveldb.org/), which makes importing this collection hard (maybe impossible), unless they give us an API or CLI to be available to import it locally.

**Comment by SeriousM** [comment]
There is no api for that yet.
Our approach is to maintain all requests/tests in one account, use the
batch file to download a collection for a product and use a docker image
with postman (npm) to run the tests in isolation.
I would love to have a collection file we could open to modify and check in
without the whole "everything is online", but that's not the case (yet?).

I hope that helped you. If you have any further questions about our
workflow please contact me on Gitter.

**Comment by johnny-chiang** [comment]
+1 for this, really need this feature

**Comment by rjouhann** [comment]
Same + 1

**Comment by kytmanov** [comment]
Guys, try this app https://github.com/kytmanov/postmanBackup . Works fine for me.

**Comment by adityagoel** [comment]
+1

**Comment by science695** [comment]
Not an exact replacement, but for pro and enterprise customers, you can now integrate with your own self-hosted git server.

https://blog.getpostman.com/2019/01/11/backup-your-collections-on-a-custom-domain-in-your-git-repositories%EF%BB%BF/

For some this may be a better solution.

**Comment by a85** [comment]
We have integrations with all major repository providers as well as the Postman API along with collection specific exports and bulk exports. Closing this for now.

**Comment by gabrielef** [comment]
> > @SeriousM do you have a snippet of code or CLI command you can share with us?
> 
> sure! this is done with windows batch but you can easily convert it to bash.
> 
> ```batchfile
> SET target_folder=tests
> SET postman_api_key=xxxxxxxx
> SET postman_collection_id=xxxxxxxxx
> 
> if not exist "%target_folder%" mkdir %target_folder%
> 
> curl -X GET https://api.getpostman.com/collections/%postman_collection_id% -H "X-Api-Key: %postman_api_key%" -H "Cache-Control: no-cache" -o %target_folder%\newman_spec.json
> ```
> 
> The collection id can be found if you query `https://api.getpostman.com/collections/` with the api key.

Bash version:

```bash
#!/bin/bash

target_folder="postman"
postman_api_key="123456"
postman_collection_id="78901"

mkdir -p $target_folder

curl -X GET https://api.getpostman.com/collections/$postman_collection_id -H "X-Api-Key: $postman_api_key" -H "Cache-Control: no-cache" -o $target_folder/postman_collection.json
```

**Comment by tasdflkjweio** [comment]
+1 for this feature. Integrations are not what this ticket was asking for, so why was it closed?

**Comment by jantoebes** [comment]
I have the feeling that, correct me if i am wrong, the team of postmanlabs explicitly don't want a file/folder sync. There are several tickets created for this and for me it feels like a basic functionality (besides all these advanced integrations and syncs with github/gitlab and their own online services). @a85 why is that?

**Comment by rahulhada** [comment]
How we can sync collections with bitbucket ?

**Comment by arlemi** [comment]
@rahulhada This isn't possible at the moment. We're tracking it as a feature request in #4780

**Comment by AllanOricil** [comment]
I like the idea of a cli. Is there a place where we can vote the postman features that needs to be prioritized?

**Comment by itsdarrylnorris** [comment]
@AllanOricil , I think you are in the right place (I could be wrong). Postman pricing model kinda depends on this feature of keeping everything in sync. Adding this feature via the CLI might cause paid customers to get off their pay service and use the CLI instead.

That is just my theory base on the poorly response/support in this ticket.

**Comment by arlemi** [comment]
@AllanOricil @itsdarrylnorris Have a look at `postmanctl`, that seems to be doing what you're asking for. If you have any feedback around it, please add it to the forum post. 

https://community.postman.com/t/introducing-postmanctl-a-cli-for-interacting-with-the-postman-api/11776

**Comment by isen-ng** [comment]
> @AllanOricil , I think you are in the right place (I could be wrong). Postman pricing model kinda depends on this feature of keeping everything in sync. Adding this feature via the CLI might cause paid customers to get off their pay service and use the CLI instead.
> 
> That is just my theory base on the poorly response/support in this ticket.

My gut tells me you are right. However, it's exactly this kind of "make things difficult for you if you don't pay" strategy that makes me adamant about not paying for a service.

**Comment by schardev** [comment]
The year is 2025, and somehow Postman still doesn’t have a simple export feature via CLI.
