### ISSUE TITLE
Add support to fetch specific user required information output from large api response.

### ISSUE THREAD

**Issue by skhatei** [a85/POSTMan-Chrome-Extension#2695]
It would be better if postman can provide selective rendering of response on the app/ support to filter out the data or a set of data that a user is looking for from api response which displays a huge amount of data.
At present its not that friendly to filter the contents one by one since sometimes the data are related to each other and to verify and relate them i need to copying them in notepad and then analyse the data.
It would be great if the user can search or set some constraints such as particular name or attribute with value and the output of the response only shows the object that contains or meets the constraints specified.

**Comment by a85** [comment]
@skhatei We don't have immediate plans to support this. We are working on a plug-in architecture that should help with use cases like this eventually though. Closing this request in it's current from. Keep our eye on our public roadmap for announcements: https://trello.com/b/4N7PnHAz/postman-roadmap-for-developers
