### ISSUE TITLE
Invalid OAuth 1.0 signature with Postman 4.9.3 on Linux

### ISSUE THREAD

**Issue by xi-ao** [a85/POSTMan-Chrome-Extension#2696]
1. Postman Version: 4.9.3
 2. App (Chrome app or Mac app): Linux
 3. OS details: Archlinux x64
 4. Is the Interceptor on and enabled in the app: No
 5. Did you encounter this recently, or has this bug always been there: Only on 4.9.3

Postman 4.9.3 seems to generate an invalid OAuth 1.0 signature.
Tested with an empty GET and POST request, with just OAuth fields filled in.
Same values in the Chrome app or in version 4.9.2 work correctly.

**Comment by vegetableman** [comment]
@xi-ao Would be great if you could share the collection causing the issue?. You could drop a mail to help@getpostman.com.

**Comment by xi-ao** [comment]
Fixed with Postman 4.10.0, so I would say this bug can be closed.
