### ISSUE TITLE
Ability to mark test as "skipped"

### ISSUE THREAD

**Issue by dlopuch** [a85/POSTMan-Chrome-Extension#2698]
Test runners typically have three outcomes of a test: passed, failed, and skipped.

The "Skipped" state is typically used to mark partial/incomplete tests or tests that are currently failing but the failure shouldn't stop your CI system from marking the entire thing as failure. The key idea though is the "Skip" still shows up in your test report, so in a lot of workflows, the report line item acts as a TODO.

It would be great if postman supported "Skipped" tests in its test runner -- would allow test-driven development where you write tests for expected functionality but don't bring your CI to a halt if something is not yet ready.

Note: I don't think this is the same as #1172 -- it's not that we want the entire *request* to be skipped, it's that we want just one particular test in the test script to be skipped (and more importantly, we want a count of skips in the runner report so we know there's an active TODO).

With postman's simple test API, this could be as simple as a magic constant, eg `tests['my test thats not quite ready'] = postman.SKIP_TEST; // TODO: responseBody.something === 'value thats not yet ready'`

**Comment by edsonmedina** [comment]
+1

**Comment by a85** [comment]
@shamasis I believe this is present in 5.0+

**Comment by edsonmedina** [comment]
@a85 Care to elaborate? Do you have a link to share?

**Comment by kunagpal** [comment]
@edsonmedina @dlopuch 
```js
pm.test.skip('This is a work in progress', function () {
  pm.expect({}).to.be.empty;
});
```
