### ISSUE TITLE
Environment variables not falling back to global variable values on pre-request script 

### ISSUE THREAD

**Issue by dewdad** [a85/POSTMan-Chrome-Extension#2699]
1. Postman Version: 4.9.2
 2. App (Chrome app or Mac app): Chrome app
 3. OS details: Windows 10
 4. Is the Interceptor on and enabled in the app: Yes
 5. Did you encounter this recently, or has this bug always been there: Yes in the past few weeks
 6. Expected behaviour: getEnvironmentVariable("APPNAME") should use global value from global variable of the same name when not defined for a selected environment.

Steps to reproduce the problem:
1, Define a global variable "varname".
3. Make sure that "varname" variable is not defined in the currently used environment.
2. in a pre-script of a request use getEnvironmentVariable("varname") and evaluate. Should equal global value. Instead it is undefined.

**Comment by sdnts** [comment]
@dewdad I'm not able to reproduce this on the Chrome App.

Here's my pre-request script:
```
let varname = postman.getGlobalVariable('varname')
console.log(varname)
```

Can you open up the environment preview tooltip (the eye icon next to the environment name) and see if you can see your global variable there? Can you also make sure it isn't being overridden? (Overridden global variables are struck through)

Can you reliably reproduce this?
