### ISSUE TITLE
OAuth "Auto add parameters" not occurring when method is POST

### ISSUE THREAD

**Issue by RenegadeMeister** [a85/POSTMan-Chrome-Extension#270]
Steps to Replicate:
1) In the primary frame, select the "OAuth 1.0" tab.
2) Enter Consumer Key, Consumer Secret, and Version number. (Example version: 1.0)
3) Enable the "Auto Add Parameters" setting.
4) Provide a URL without any variables
5) Change method from GET to POST
6) Click the URL Params icon/button
7) Select content type "raw" and a payload format of "XML"
8) Enter payload information in XML format
9) Click Send

Expected result:
Between the URL and the request payload, all OAuth related URL parameters would be listed and appended to the URL.  This is expected because that is what occurs when "Auto Add Parameters" is enabled when using the GET method.

Actual result:
Between the URL and the request payload, no additional URL parameters are displayed below the URL or appended to the URL itself.

Impact:
This prevents me from using Postman for most of the request types for the REST application that I test, as most requests use a HTTP method of POST.

**Comment by mfissehaye** [comment]
How about if the API does not accept params from header; only from query params, such as is the case with WooCommerce REST API?

**Comment by sdnts** [comment]
Hey @merhawifissehaye Postman has supported sending OAuth parameters through query parameters (as well as body parameters) for a while. Could you try updating to the latest version (4.8) and check?
