### ISSUE TITLE
Load Client certificates from macOS keychain

### ISSUE THREAD

**Issue by jensraaby** [a85/POSTMan-Chrome-Extension#2700]
Since version 4.6 (IIRC) we've had to manually supply the CRT/KEY files for client SSL authentication. This previously used the MacOS keychain, which is still used in the Chrome app.

I work in an organisation that uses client certs for virtually every web API, and I like to access these through Postman. Unfortunately, the Postman desktop app has now become impractical to use because I manually have to set up every individual domain before making any requests - this is a frustratingly time consuming thing to do.

What I would propose is wildcard hostnames for the certificate hostnames.
For example, setting up a certificate for `*.mydomain.com` would provide that certificate to all subdomains of `mydomain.com`.
Similarly, `api.*.mydomain.com` would apply to `api.stage.mydomain.com` and `api.live.mydomain.com`.

Alternatively, it would be great if the OS keychain was integrated again, as that integration never caused any problems for us before.

 1. Postman Version: 4.9.3
 2. App (Chrome app or Mac app): Mac app
 3. OS details: OS X 10.9.5

**Comment by sdnts** [comment]
@jensraaby Understandable. Tagging this as a feature request :)

**Comment by kamalaknn** [comment]
@shamasis @numaanashraf this should be possible with the recent changes to Certificates in `postman-collection`. Thoughts?

**Comment by felipehummel** [comment]
Any progress on this? I'm now in the same situation as @jensraaby

**Comment by 1I1III1liL1** [comment]
Bump. The Chrome app has a reminder saying that Chrome apps are being deprecated, but this is critical functionality that I use daily.

**Comment by oresot** [comment]
+1

**Comment by codenirvana** [comment]
Certificate configurations already support wildcards in the domain, Refer: https://github.com/postmanlabs/postman-app-support/issues/5123

Updated the issue title for this feature request.

**Comment by kkalavantavanich** [comment]
Any progress on this? It's been 3 years already...

**Comment by kkalavantavanich** [comment]
Any progress on this? It's been 4 years already...

**Comment by shamasis** [comment]
> Any progress on this? It's been 4 years already...

@kkalavantavanich you mean the wildcard support or reading from keychain? Wildcard support is already present. 

The reading from keychain is not going as reliable and easy as we had originally thought. Tonnes of on-install compilation binaries from the open source projects such as keytar that we explored. 

We may not eventually support this.

**Comment by sakiv** [comment]
@shamasis `*.example.com` works, but `service*.example.com` does not.

**Comment by jviotti** [comment]
Merging this with https://github.com/postmanlabs/postman-app-support/issues/5930
