### ISSUE TITLE
Unable to open more than one tab from a particular saved call in the collection

### ISSUE THREAD

**Issue by musiKk** [a85/POSTMan-Chrome-Extension#2702]
1. Postman Version: 4.9.2
 2. App (Chrome app or Mac app): Chrome App
 3. OS details: Ubuntu Linux 16.10
 4. Is the Interceptor on and enabled in the app: does not matter
 5. Did you encounter this recently, or has this bug always been there: a few versions ago I think
 6. Expected behaviour: see below
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app): n/a
 8. Screenshots (if applicable)

When a tab has been opened from a saved request I cannot open a second tab for the same request. I think this has been introduced as a feature a while ago and it makes sense if the first request is not edited. However I sometimes change stuff in a request (and subsequently get the "modified dot" in the tab title) and want to compare that to the original saved request. But I cannot open it again because this only activates the existing (edited) tab.

To reiterate:

1. Save a request as "foo"
2. Close all tabs
3. Open "foo"
4. Make some edits but DON'T save
5. Open new tab
6. Open "foo" again

Result: The first edited "foo" is activated

Expected result: "foo" is opened a second time in the version saved in step 1.

**Comment by sdnts** [comment]
@musiKk This is the intended behaviour. However, since 4.10, we've added a new option in the request dropdown to allow you to open the request in a new tab. Can you update to the latest version (4.10.2) and see if that's what you expect?

**Comment by musiKk** [comment]
Of course I would've preferred it like I suggested but your solution works as well. :wink: Thanks!
