### ISSUE TITLE
[Bug] - When renaming a test, Copying and Pasting the name actually Copy and Pastes the Test Item

### ISSUE THREAD

**Issue by PFarrell89** [a85/POSTMan-Chrome-Extension#2705]
I'm using the Postman Chrome Application Version 4.10.0. (Ideally I'd be using the Windows Client but #2598 is still a big issue that hasn't been fixed yet - which was reported nearly 2 months ago)

**Issue:**
Copy and Pasting the name of the test item, actually copy and pastes the test item rather than the name.

**Steps to Recreate:**
Attempt to rename a test.
Select all of the text and Copy this to your clipboard (Windows: Ctrl + C)
Paste (Windows: Ctrl + V) Notice this will copy and paste the actual test, not the name.

ALSO, you are aware that you have to press Enter to confirm renaming the test?
If the user renames then clicks off the test item, the name reverts back to what it was.

ALSO you can't highlight the name of a test item, I have to press Ctrl + A to highlight all the text.
Attempting to highlight the test item's name actually attempts to drag the item.

Let me know if you require more information.

**Comment by vegetableman** [comment]
@PFarrell89 Issue #2598 has been fixed. As to the "copying the name" issue, could you elaborate more on it with a screenshot perhaps?

**Comment by PFarrell89** [comment]
I've clicked the "..." icon next to a Test Item.
Clicked Rename (The whole name is automatically highlighted)
I press Ctrl + C to copy the name
![image](https://cloud.githubusercontent.com/assets/8641826/23059485/879b95fa-f4f1-11e6-83cf-1ca5e4f66be4.png)

I then press Ctrl + V to paste the copied name into a Test Item
The Test Item is then Copied tothe bottom of the Collection.

![image](https://cloud.githubusercontent.com/assets/8641826/23059544/cc8dd312-f4f1-11e6-8662-f84ed19ad35a.png)

**Comment by vegetableman** [comment]
@PFarrell89 Thanks for sharing the screenshot 👍 . Tagging this as a bug.

**Comment by vegetableman** [comment]
@PFarrell89 You could update to latest version 4.10.3 which takes care of the issue ^_^.
