### ISSUE TITLE
Incorrect JSON pretty-printing of floating point numbers

### ISSUE THREAD

**Issue by apazzolini** [a85/POSTMan-Chrome-Extension#2708]
1. Postman Version: 4.10.0
 2. App (Chrome app or Mac app): Mac App
 3. OS details: 10.11.6
 4. Is the Interceptor on and enabled in the app: n/a
 5. Did you encounter this recently, or has this bug always been there: Recent (a couple of days)
 6. Expected behaviour: Pretty JSON printing should render floating point numbers properly

Make a request to a server that returns a floating point number in its JSON response and attempt to format the JSON in Postman.

The raw response is: 
```
{ "messagesPerSecond":393.57195301590247 }
```

The "pretty" version of this is:
```
{
  "messagesPerSecond": {
    "s": 1,
    "e": 2,
    "c": [
      3,
      9,
      3,
      5,
      7,
      1,
      9,
      5,
      3,
      0,
      1,
      5,
      9,
      0,
      2,
      4,
      7
    ]
  }
}
```

**Comment by iamareebjamal** [comment]
Issue does not exist for only floating point numbers, but also for integers

Raw Data :
```js
{ "error": false, "message": "Sent successfully!", "message_id": 5771851712033702072 }
```

Pretty Printed : 
```js
{
  "error": false,
  "message": "Sent successfully!",
  "message_id": {
    "s": 1,
    "e": 18,
    "c": [
      5,
      7,
      7,
      1,
      8,
      5,
      1,
      7,
      1,
      2,
      0,
      3,
      3,
      7,
      0,
      2,
      0,
      7,
      2
    ]
  }
}
```

**Comment by SamvelRaja** [comment]
@apazzolini @iamareebjamal Tracking it here #2703.. Will be fixed and released in sometime from now.
