### ISSUE TITLE
Exporting postman collection without permissions to directory.

### ISSUE THREAD

**Issue by mmckillion-r7** [a85/POSTMan-Chrome-Extension#2709]
1. Postman Version: Version 4.10.0
 2. App (Chrome app or Mac app): Chrome App
 3. OS details: Linux
 4. Is the Interceptor on and enabled in the app: Yes
 5. Did you encounter this recently, or has this bug always been there: Always been there, only found root cause today.
 6. Expected behaviour: Should either save or give warning.

Export a collection to a directory that does not have write access.

**Comment by vegetableman** [comment]
@mmckillion-r7 Thanks for creating this issue 👍 . Will keep you posted.

**Comment by a85** [comment]
I am not sure what we can do here other than improve error warnings. Closing this as a bug.
