### ISSUE TITLE
Pretty view not displaying integers correctly for json if length is greater than 15 digits

### ISSUE THREAD

**Issue by chuckwade** [a85/POSTMan-Chrome-Extension#2710]
1. Postman Version:  4.10.0
 2. App (Chrome app or Mac app):  Chrome App
 3. OS details:  Windows 7 
 4. Is the Interceptor on and enabled in the app:  No
 5. Did you encounter this recently, or has this bug always been there:  Not sure
 6. Expected behaviour:  display json correctly "packageId:"5431254321111111"
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 8. Screenshots (if applicable)
![Uploading Capture.PNG…]()

In response (pretty view only) 
"packageId:"5431254321111111" turns into "packageId": {
                "s": 1,
                "e": 15,
                "c": [
                  5,
                  4,
                  3,
                  1,
                  2,
                  5,
                  4,
                  3,
                  2,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1,
                  1
                ]
              }

**Comment by sdnts** [comment]
@chuckwade This was fixed in a recent patch release (4.10.2). Feel free to reopen if an update does not solve your issue :)
