### ISSUE TITLE
JSON isn't automatically detected if content-type header is text/javascript

### ISSUE THREAD

**Issue by tpnick** [a85/POSTMan-Chrome-Extension#2712]
1. Postman Version: Version 4.10.2 (4.10.2)
 2. App (Chrome app or Mac app): Mac App
 3. OS details: OS X El Capitan 10.11.6
 4. Is the Interceptor on and enabled in the app: No, is it needed for the standalone app?
 5. Did you encounter this recently, or has this bug always been there: always been there
 6. Expected behaviour: JSON should be automatically selected when the response comes through as the display parser but it gets stuck on auto only when the header text/javascript is passed, other headers work fine.
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app): 🐶 watchdog checking connection health
sails.io.js:142 🌏 disconnected from sync service. possibly a network outage.
sails.io.js:142 🌏 scheduled reconnection attempt #1 after 14654ms
xml.js:22 🐶 watchdog checking connection health
 8. Screenshots (if applicable)

**Comment by vegetableman** [comment]
@tpnick Could you elaborate on why you need the type `JSON` set for a `text/javascript` content type?
