### ISSUE TITLE
checking for updates does not finish / dl.pstmn.io certificate expired

### ISSUE THREAD

**Issue by hn3000** [a85/POSTMan-Chrome-Extension#2713]
1. Postman Version: 4.10.1
 2. App (Chrome app or Mac app): Mac app
 3. OS details: Mac OS X 10.11.6
 4. Is the Interceptor on and enabled in the app: no
 5. Did you encounter this recently, or has this bug always been there: only today
 6. Expected behaviour: Check for Update should report an available update or that none are available.
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 8. Screenshots (if applicable)

Steps to reproduce the problem:

1. Choose "Check for Updates ..." from the Apple menu
2. Watch the update checker not finishing

Additional info: when I tried to download the update manually, I got a "Certificate Expired" warning from all the browsers I tried.

This is what Firefox offered:
<img width="917" alt="screen shot 2017-02-16 at 05 07 07" src="https://cloud.githubusercontent.com/assets/133752/23007108/67b885c2-f406-11e6-82e9-b05643d30e27.png">

**Comment by SamvelRaja** [comment]
@hn3000 We are on it.. thanks for the heads up.

**Comment by SamvelRaja** [comment]
@hn3000 The issue has been fixed you can update without a problem now.
