### ISSUE TITLE
[Bug] - Pretty JSON formatting float numbers wrongly

### ISSUE THREAD

**Issue by nullco** [a85/POSTMan-Chrome-Extension#2715]
1. Postman Version: 4.10.0
 2. App (Chrome app or Mac app): Chrome app
 3. OS details: Ubuntu 16.04
 4. Is the Interceptor on and enabled in the app: Disabled
 5. Did you encounter this recently, or has this bug always been there: Recently
 6. Expected behaviour: Pretty JSON response should respect number format as it comes from the server
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 8. Screenshots (if applicable)

![bug1](https://cloud.githubusercontent.com/assets/5529078/23025347/a3a20200-f42b-11e6-92e7-1bae4b60e721.png)

the avg fields which is actually a float number is showing like:

"avg": {
          "s": 1,
          "e": 1,
          "c": [
            6,
            2,
            9,
            6,
            7,
            5,
            4,
            3,
            9,
            4,
            5,
            4,
            5,
            2,
            7,
            0,
            4
          ]
        }

![bug2](https://cloud.githubusercontent.com/assets/5529078/23025355/ac1cc26c-f42b-11e6-82ac-5a521a9df3ce.png)

In raw, it shows correctly:

"avg": 62.967543945452704

Steps to reproduce the problem:

Consume a resource that gets a JSON with a float field with many decimal points,
check the differences between pretty and raw responses

**Comment by sdnts** [comment]
@nullco We released a fix for this in 4.10.2. Can you try updating to verify that this is fixed?

**Comment by nelsjm** [comment]
@madebysid I ran into this issue on 4.10.0 and updated to 4.10.2 and it went away.
