### ISSUE TITLE
Restoring postman collection on a different machine after original machine crash

### ISSUE THREAD

**Issue by pushkard** [a85/POSTMan-Chrome-Extension#2721]
I am using the Windows Postman app and had bunch of collections saved in the app. My machine crashed and now I have a new windows machine and have access to the original data (mapped as different drive)

Is there a way to restore the collections by copying files from the old hard disk?

 1. Postman Version: 4.9.3
 2. App: Windows App
 3. OS details: Windows 10

**Comment by vegetableman** [comment]
@pushkard You could replace the folder `Postman` on the path `C:\Users\<User>\AppData\Roaming` with the one from the older machine.
Also, to avoid such issues, you could enable sync which will help you maintain and sync your collections across different machines.

**Comment by pushkard** [comment]
It worked. Thanks.

**Comment by SarathVakacharla** [comment]
For mac?

**Comment by kierans** [comment]
`~/Library/Application\ Support/Postman`
