### ISSUE TITLE
Postman always follows redirects, ignores setting Follow Redirects = off

### ISSUE THREAD

**Issue by jbauerrfid** [a85/POSTMan-Chrome-Extension#2722]
1. Postman Version:
Postman for Chrome
Version 4.10.2
linux / x86-64
Chrome 50.0.2661.86
 2. App (Chrome app or Mac app):
Chrome app
 3. OS details:
Ubuntu 16.04 LTS
 4. Is the Interceptor on and enabled in the app:
all interceptor settings are off
 5. Did you encounter this recently, or has this bug always been there:
100% reproducable
 6. Expected behaviour:
Display the 307 response in the response window

Create a service which responds to a GET with following response:
 - HTTP status: 307
 - Response header: "Location: https://www.getpostman.com" (it just needs a valid URL)

Instead of displaying this response, postman executes the redirect and displays the HTML it finds on the redirect URL. This happens even when the redirect interceptor is switched off.

It is not possible to turn this behavior off, e.g., to inspect the original response.

**Comment by vegetableman** [comment]
@jbauerrfid You need to enable the interceptor to disable redirect ^_^.

**Comment by jbauerrfid** [comment]
I am on "Automatically follow redirects" in the "General" tab. It redirects in both settings ON or OFF.
Is there an other location to configure the interceptor?

**Comment by vegetableman** [comment]
@jbauerrfid The interceptor needs to be turned on, in order to stop the redirection. You could refer this doc to enable the interceptor: https://www.getpostman.com/docs/capture.

**Comment by jbauerrfid** [comment]
I have moved to Postman for Linux which solved the problem for me.

**Comment by VincentSaelzler** [comment]
I an experiencing the same issue. Redirects are followed.

I have checked the interceptor option in Postman to orange (assuming means "on") and also have the interceptor browser extension installed.

Settings > Interceptor > Automatically follow redirects is off

Chrome: Version 59.0.3071.104 (Official Build) (64-bit)
Postman for Chrome: Version 5.0.1 win / x86-64

![extension](https://user-images.githubusercontent.com/16230737/27553828-86b42028-5a7a-11e7-81ab-a3febf3b66d9.PNG)

![interceptor](https://user-images.githubusercontent.com/16230737/27553748-38952b1c-5a7a-11e7-806c-d926ea43f310.PNG)

**Comment by arcseldon** [comment]
Same problem. Interceptor is enabled, automatically follow redirects is disabled. Doesn't work, still follows the redirects. :(

**Comment by josevavia** [comment]
I asume that this bug is still present, isnt it?

I have this problem in both chrome extension and linux app

**Comment by rgasioro** [comment]
UPDATE: please disregard this. After further investigation, I have discovered that Postman is working as expected.

**Comment by numaanashraf** [comment]
@rgasioro, Could you open the Postman Console (View > Show Postman Console) in Postman App and send us a screenshot of the request/response logs? 

Please note that in the Postman Chrome App - you'ld need to install and enable Postman Interceptor to turn off auto-follow of redirects.

**Comment by rgasioro** [comment]
@numaanashraf please close this issue, Postman is working as expected (I was misled by other clients.)

**Comment by numaanashraf** [comment]
@rgasioro Glad to know that. Could you let us know what caused the confusion? It'll be very helpful for our community and we would also be able to make these issues easy to debug in Postman.

**Comment by rgasioro** [comment]
I guess the major source of confusion were cookies. Extension rest clients kept including them, even after deleting. I used another standalone rest client to verify that Postman is not at fault, and that in turn helped me uncover user error (I have assumed that since some extensions work as expected, I am on the right path, which was not true.)

BTW, it's the standalone Postman that works as expected, extension is still redirecting (ignoring redirect setting.)

**Comment by rulatir** [comment]
If not following redirects REQUIRES enabling, configuring and learning a difficult and complicated tool like the Postman Interceptor, then I don't consider this bug fixed. It will be fixed when I will be able to disable the option in the Postman settings, and Postman will OBEY. Just like that. Without having to learn new tools.

Please reopen.
