### ISSUE TITLE
variable with local / collection visibility

### ISSUE THREAD

**Issue by sebastien-savalle** [a85/POSTMan-Chrome-Extension#2723]
Hello,

We are using global variables for chaining request of a collection. 
For example, those variables can contains a specific identifier on which we are working temporarily. Would it be possible to add a new type of variable for such purpose ?

Some interesting requirements:
- Set an expiration date on the variable.
- Limit the scope of the variable to a collection or a window.
- Clear the variables when the window is closed.

Does it make sense ?
Thanks a lot,

**Comment by sdnts** [comment]
@ellavas We're working on something similar, i.e. collection level variables. Will let you know here when we make progress!

**Comment by loraxipam** [comment]
See #1285

**Comment by orossant** [comment]
It would be nice too, to  be able to read and write global variables Inside a Collections.
When I user Inside one collection, two request, the first one modify a global env variable and the second request will read the global variable but with wrong value.

**Comment by a85** [comment]
Closing as a duplicate of #1285
