### ISSUE TITLE
Feature Request: Adding JS Fetch as an option in the generate code snippets section.

### ISSUE THREAD

**Issue by sautumn** [a85/POSTMan-Chrome-Extension#2724]
It would be great if you could add [JS fetch](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch) support in the 'generate code snippets' section of Postman.

Awesome product! 
Thanks so much!

**Comment by sdnts** [comment]
@sautumn Thanks for the suggestion! Are you trying to make a request from within another request? If so, you can also look into setNextRequest to accomplish what you want. [Docs](https://www.getpostman.com/docs/workflows), [Example](http://blog.getpostman.com/2016/03/23/conditional-workflows-in-postman/)

**Comment by gausie** [comment]
This would be really useful.

**Comment by roccomuso** [comment]
+1 thanks

**Comment by johnmerced-ks** [comment]
+1 Looking for this as well!

**Comment by drojkind** [comment]
+1 for this as well !

**Comment by VinLau** [comment]
+1, fetch is the way to go!

**Comment by karanthakral** [comment]
Any updates?

**Comment by harrisrobin** [comment]
+1

**Comment by dzoba** [comment]
Would also really like this.

**Comment by dennissterzenbach** [comment]
Any updates? 
Still are waiting to see support for Postman to generate JavaScript Fetch API compatible code...

**Comment by dfeehrer** [comment]
+1 Would still really like to see this, thanks!

**Comment by reggi** [comment]
Is there any progress on this? Is this something the open-source community can do, or does it have to be done by @postman-admin ?

**Comment by ghinks** [comment]
totally awesome idea. I have been using the request code snippet generation for ages, and was wondering when we would move on to fetch.

**Comment by brahambence** [comment]
+1 It would be a really useful addition

**Comment by jsjoeio** [comment]
+1 - our team would really love this!

**Comment by joelbqz** [comment]
Any update on this? +1

**Comment by AustinAmoruso** [comment]
Yes please

**Comment by realPrimoh** [comment]
+1 would be fantastic!

**Comment by ashishjs** [comment]
+1 YEP Please!

**Comment by MartinMuzatko** [comment]
omg. I was pretty surprised this is not there yet.

**Comment by bschoone** [comment]
+1

**Comment by ichoosetoaccept** [comment]
This would indeed be amazing.

Apparently, Paw can do this with https://github.com/bdougherty/paw-javascript-fetch-generator.

Haven't tested it though...

**Comment by vinniejames** [comment]
+1

**Comment by gbertoncelli** [comment]
+1

**Comment by apboon** [comment]
+1
(I am amaziballzed that this is still not included.. would be easy to implement..)

**Comment by DylanTackoor** [comment]
+1 :)

**Comment by oceangravity** [comment]
+1

**Comment by a85** [comment]
We are moving all code generators to a plugin based model so we can update them independently and add new ones on the fly.

**Comment by oceangravity** [comment]
Thank You @a85 great news!

**Comment by cjrutherford** [comment]
+1, would love to see this as well.

**Comment by dhondtlaurens** [comment]
+1, this would be great for documentation

**Comment by a-m-dev** [comment]
any updates yet?

**Comment by amstrad** [comment]
+1

**Comment by TimmJensen** [comment]
+1 Please add :+1:

**Comment by rigwild** [comment]
Indeed this would be so useful. I "copy as fetch" on chrome console all the time. 👍

**Comment by andy-rush-beerhawk** [comment]
ooo yes please +1

**Comment by Fluorz** [comment]
+1

**Comment by gventuri** [comment]
+1

**Comment by Leoooob** [comment]
+1 seems like it's been on the wait list for a long while

**Comment by rhartness** [comment]
Also going to suggest this.  Is it even in the works?

**Comment by krisdev** [comment]
+1
Would be bloody useful ;)

**Comment by godblesslancek** [comment]
+1 !! Thank you for the product!

**Comment by abhijitkane** [comment]
Everyone - the latest Postman Canary has support for a new set of code-generators, including JS-Fetch and Powershell.

Canary can be downloaded from https://www.getpostman.com/downloads/canary, and run be run side-by-side with your regular Postman app. You'll need to enable the `Experimental Codegen mode` option in Postman's global settings to see the new language options.

cc @krisdev @Leoooob @rhartness @godblesslancek

**Comment by lionel-rowe** [comment]
In a weird coincidence, literally yesterday I made a Postman collection → `fetch` API converter as a workaround. I guess it's of limited use now that this is in Canary, but I'll stick it here for posterity's sake:

https://codepen.io/lionel-rowe/full/zVrLvw

I suspect it's considerably less stable and featureful than even a canary release, but maybe someone might find some marginal use for it.

**Comment by steveostudios** [comment]
This literally could not come any sooner! Thank you Postman team for this! It worked flawlessly for me the first time.

**Comment by slayb3ar** [comment]
@abhijitkane Awesome to hear about the new set of code-generators. I'm having a little trouble figuring out how to enable the `Experimental Codegen mode`.

Could you walk me through how to enable this flag?

**Comment by daytonlowell** [comment]
> @abhijitkane Awesome to hear about the new set of code-generators. I'm having a little trouble figuring out how to enable the `Experimental Codegen mode`.
> 
> Could you walk me through how to enable this flag?

In Postman, go to the `Preferences > General` tab. 2nd switch down, under Request is "Experimental Codegen mode".

**Comment by nachozullo** [comment]
\+ 1 I need it
