### ISSUE TITLE
Postman fails to load large (1MB sized) 3rd party javascript lib (pdf2txt), and often (but not always) crashes after load fail.

### ISSUE THREAD

**Issue by 4everqa** [a85/POSTMan-Chrome-Extension#2725]
1. Postman Version:  4.9.2   win / x86-32    browser app, native not tested (yet)
 2. App (Chrome app or Mac app): Chrome 55.0.2883.87
 3. OS details: Windows 7 64bit,  20 GB RAM free.
 4. Is the Interceptor on and enabled in the app: no
 5. Did you encounter this recently, or has this bug always been there:  Crash always have happened  , tested on many machines.
 6. Expected behavior: 
 6.1. Successful load of the external javascript library 
 6.2 No crash in postman browser app

7. Steps to reproduce:

Request tab
GET https://github.com/hubgit/hubgit.github.com/blob/master/2011/11/pdftotext/pdf.js?raw=true

Test Script tab
// "install" Postman pdf2text lib (note: it is 1,06 MB in size)
postman.setGlobalVariable('pdf2txt', responseBody);
 ReferenceError: test is not defined
    at eval (eval at loadCustomFile (Evaluator.js:226), <anonymous>:10:1)
    at eval (eval at loadCustomFile (Evaluator.js:226), <anonymous>:11:16)
    at r.loadCustomFile (Evaluator.js:226)
    at Evaluator.js:215

8. Often, after the message ReferenceError: test (or pdf2txt) is seen, postman (browser app) crashes.

9. More info:
The 3rd party java lib is known to work fine and has been extensively used successfully standalone, in isolation, outside of postman.

10. Reference:
https://postmancommunity.slack.com/archives/general/p1485975042001201?thread_ts=1485961872.001198&cid=C0WBDGZ4P

**Comment by numaanashraf** [comment]
Not able to replicate this issue. Seems to be worked as expected. Do let us know if you are still facing this issue with the latest version of Postman.

<img width="977" alt="Screenshot 2019-03-28 at 8 32 53 AM" src="https://user-images.githubusercontent.com/3295568/55126881-5c49cb00-5134-11e9-818a-34cb42effb67.png">
