### ISSUE TITLE
Bulk Edit of Headers doesn't load until second attempt

### ISSUE THREAD

**Issue by RangerDan** [a85/POSTMan-Chrome-Extension#2726]
1. Postman Version: 4.9.2
 2. App (Chrome app or Mac app): Chrome app, Chrome 56.0.2924.87
 3. OS details: Fedora linux / x86-64
 4. Is the Interceptor on and enabled in the app: Yes
 5. Did you encounter this recently, or has this bug always been there: Recent encounter
 6. Expected behaviour: If I have the Header bulk edit selected and I move from test to test, I expect the headers to load successfully after clicking a new case.  This doesn't seem to be happening.

 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app): None that are relevant

Steps:
- Have a set of multiple tests with multiple headers each.
- Notice the header count on the 'Header' tab control properly counts the number of headers.
- Enable Bulk-edit mode for Headers.
- Delete a header and save the test.
- Click the next test.
- Notice the Header count changes but the listed headers do not.
- Click the previous test.
- Notice the header count changes back and the listed headers are correct.
- Click the next test again.
- Notice the header count is now correct, and the full header listing is available in the bulk-edit memo control.

**Comment by SamvelRaja** [comment]
Are you still facing this issue? Can you confirm the same in our 5.2.0 version of the app.
Closing this, please feel free to reopen if still happens.

**Comment by RangerDan** [comment]
Looks good to me (Linux Chrome app and Electron for good measure)
