### ISSUE TITLE
Pretty printer cant handle long decimal values in output

### ISSUE THREAD

**Issue by smileatom** [a85/POSTMan-Chrome-Extension#2728]
1. Postman Version: 4.10.0
 2. App (Chrome app or Mac app): mac
 3. OS details:  10.12.3
 4. Is the Interceptor on and enabled in the app: dunno
 5. Did you encounter this recently, or has this bug always been there: just now
 6. Expected behaviour: JSON pretty printer misinterprets lat lng as objects and spews junk
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 8. Screenshots (if applicable)

"lat":38.09980980..etc

turns into: 

"lat": {
        "s": 1,
        "e": 1,
        "c": [
          3,
          8,
          0,
          5,
          0,
          3,
          1,
          2,
          9,
          0,
          8,
          2,
          2,
          7,
          1,
          6
        ]
      }

In the pretty printer

The json is valid and looks fine in the raw or preview view.

Use a long negative or positive double value in return json and view in pretty printer

**Comment by SamvelRaja** [comment]
@rendion Hey this has been fixed in our 4.10.2 version, can you kindly update your app and check the same? Also feel free to reopen the issue if it recurs.

**Comment by smileatom** [comment]
Will do.

**Comment by smileatom** [comment]
works ty
