### ISSUE TITLE
Request rename + paste duplicates request

### ISSUE THREAD

**Issue by toneplex** [a85/POSTMan-Chrome-Extension#2731]
1. Postman Version: 4.10.2
 2. App (Chrome app or Mac app): Mac app
 3. OS details: macOS Sierra
 4. Is the Interceptor on and enabled in the app:
 5. Did you encounter this recently, or has this bug always been there: recent
 6. Expected behaviour: When renaming a request, the request should not be duplicated

**Steps to reproduce the problem:**
1. Duplicate a collection folder
1. In the new folder, click on an existing request in a collection.
1. Press ⌘+e to edit the request
1. Delete the existing request name and press ⌘+v to paste in text
1. The request will be renamed, but you will also have a duplicate request created in the collection with the name + ' copy'

**Before:**
<img width="423" alt="before" src="https://cloud.githubusercontent.com/assets/595547/23132321/d0233130-f752-11e6-83a2-fb99ec1e0a7b.png">

**After:**
<img width="423" alt="after" src="https://cloud.githubusercontent.com/assets/595547/23132320/d0219da2-f752-11e6-8c2c-7bdca6e40aa8.png">

**Comment by vegetableman** [comment]
@toneplex Thanks for posting this issue along with screenshots 👍  . Will keep you posted.

**Comment by vegetableman** [comment]
@toneplex You could update to latest version `4.10.3` which takes care of the issue ^_^.

**Comment by toneplex** [comment]
Thanks @vegetableman, that fix works great!
