### ISSUE TITLE
Feature Request: Sticky Header in Postman docs

### ISSUE THREAD

**Issue by jaskarangump** [a85/POSTMan-Chrome-Extension#2732]
It will be great to have the header stick on the top even when a user scrolls. 
This will allow to - 
- change the language from any place
- Click the 'Run in Postman' link

It is generally the pattern we have seen. It will be great if this could be implemented.

**Comment by steffenschebesta** [comment]
Agreed - this would be a lot more user friendly.   
Also should be fairly easy to implement

**Comment by vkaegis** [comment]
@jaskarangump Thanks for writing in! Just curious, do you switch languages often within the documentation? Or is it once per documentation?
