### ISSUE TITLE
[feature]workspace 

### ISSUE THREAD

**Issue by unifreak** [a85/POSTMan-Chrome-Extension#2733]
I hope that new version Postman can haave workspace feature. so I can save currently opened tabs into one workspace, next time I open a workspace, those tabs&request params are there. something like sublimt-text's workspace.

**Comment by sdnts** [comment]
@UniFreak Thanks for the suggestion! This is on our radar, will let you know here when we make progress :)

**Comment by a85** [comment]
Tracking here in #3205
