### ISSUE TITLE
Runner Removes leading 0's from .csv data

### ISSUE THREAD

**Issue by GriffinOSI** [a85/POSTMan-Chrome-Extension#2734]
Postman Runner Removes leading "0" from values in .csv spreadsheet. 

This causes tests to fail unless I create a new var, append a 0 then test against the new var.

![excelview](https://cloud.githubusercontent.com/assets/10963335/23161300/85e65eb0-f821-11e6-8bc5-20ba03414391.JPG)
![preiviewvie](https://cloud.githubusercontent.com/assets/10963335/23161310/8df5a052-f821-11e6-9988-0aab51dc7371.JPG)

Postman for Windows
Version 4.10.2
win32 10.0.14393 / x64

There is reference to a similar issue here that was closed but it does not seemed to have been resolved

https://github.com/postmanlabs/postman-app-support/issues/1917#issuecomment-200397668

**Comment by catcalling** [comment]
Hi, I also have the same problem. Can i ask when will this be fixed? :(

**Comment by catcalling** [comment]
Hi, I also encountered the same problem. Is this fixed already?  Or when will it be fixed? :(

**Comment by sdnts** [comment]
@catcalling This isn't fixed yet unfortunately, but we'll be taking a look at this.

**Comment by Pixelartist** [comment]
Having the same issue - would be nice to see it fixed.

**Comment by jacopone** [comment]
I am having the same issue - really important to fix

**Comment by lloydmoran** [comment]
Would love to see a fix for this.

**Comment by KatrinaC** [comment]
I'm also having issues with this. Any timeline for a fix?

**Comment by ashishkpathak** [comment]
This issue has been open over 2 years!! Its a very common feature required by the development community. Can this be prioritized.

**Comment by lucas937** [comment]
Is this issue still open? Very strange, this should be fixed ASAP. Im trying to work around this but its not working. what do i do?

**Comment by lloydmoran** [comment]
A workaround is to put the value in the .CSV in quotes e.g. "0000123". Not ideal for a few reasons but it worked for me.

**Comment by yaredw** [comment]
So 2+ years later...hopefully this will be prioritized soon? It's kind of a big deal...

**Comment by vikiCoder** [comment]
Hi everyone,

We convert numbers without quotes in CSV file into JavaScript Number while parsing the CSV file in the Postman App. As a result, leading zeros from the number is removed because that information can't be stored in JavaScript Number. If you want to keep numbers with leading zeros as it is, you can specify them as a string in CSV file by wrapping the number in double quotes like below:
```
index,specialNumber
1,"000001"
2,"000002"
```

However, for the users who don't want this behavior or want to have more control over parsing, we are planning to provide options related to CSV file parsing behavior in our long term roadmap. We will consider adding an option to parse specified columns as string by default. Other suggestions are always welcome regarding what options you would like to have when we add them.

**Comment by saswatds** [comment]
Closing this issue for now in favour of the options feature

**Comment by ttan70** [comment]
any update on this, I can't find a solution to fix this, all links take me back to this issue link

**Comment by thanhphuocdang** [comment]
I'm stuck on this after a thousand years.
Any better solution now?

**Comment by asharrahman-toast** [comment]
Any solution yet? Our team is running into lots of Postman Issues and this is the cherry on top.

**Comment by vikinzer** [comment]
This has not been fixed and the "We have a plan" post is 3 years old.  This is kind of ridiculous.

**Comment by VaishnaviChallaPostman** [comment]
Hey everyone 👋 
Sorry for the inconvenience caused. We understand your concern.
Our team is looking into this issue and we will provide any updates here on this thread.
Thanks for your patience :)

**Comment by mohamead** [comment]
What is the status her?

**Comment by caljayw** [comment]
Any progress here?

**Comment by rodrigo-gonzalez-LS** [comment]
I prayed and prayed

**Comment by jmarine32** [comment]
Hi -- is there an update on this issue?

**Comment by kdomagal** [comment]
same problem here.. over two years and still not fixed, this is ridiculous

**Comment by Pixelartist** [comment]
I think this is just not getting any attention - @kdomagal is talking about two years. I hit this bug in 2017. Time flies.
@VaishnaviChallaPostman If there is a "vote for this bug" or any other community option, it would be great. We obviously cannot judge the workload on the devs nor do we understand your milestones.

**Comment by malvikach** [comment]
Hi All,

We are looking at this issue and have an approach/solution in mind. If anyone is interested to give us feedback or discuss the resolution, please drop us a note here or send me an email on malvika.chaudhary@postman.com 

Thanks for your patience. 

Regards,
Malvika

**Comment by ashishkpathak** [comment]
Yes, I would like to understand the solution for this old issue. Which
version is it planned to be rolled out?

Thanks,

**Comment by malvikach** [comment]
@ashishkpathak 👋 

Thanks for responding. We are thinking to let users specify the data types of the column in the preview screen. Once we parse the file and show it in the preview, we will give an option to the user to change the data type of a column. Hence, this will allow the user to change the datatype from "Number" to "String" so that the values with preceding zeros would be retained. 

If you are up for a discussion, [here](https://calendly.com/malvika-chaudhary/v10-feedback) is my calendar, please feel free to block some time. Alternatively, feel free to provide suggestions on this thread. 

Thanks again

**Comment by Shobhitpatial01** [comment]
Hi I tried adding a [ ' ] in front of the leading zero worked for me as a workaround

**Comment by malvikach** [comment]
Hi everyone 👋 

Glad to inform you that with the latest release of Postman v 10.18, we have included a fix to this problem. 

You will now be able to let Postman know how you would like your data file columns to be parsed. We support String, Boolean, and Numbers apart from the default logic that is still available (option called "Auto-Detect"). 
When you upload a file, the file will be parsed based on the auto-detection logic that exists, however, you can change the column type of a file and select for the column to be of a given type such as "String". This will help you retain the preceding 0's in your data. The preview screen will show you how the data will be parsed once you change the type. 

Please see the below video for a walkthrough of how this works:


https://github.com/postmanlabs/postman-app-support/assets/89449769/108a4c88-aaa2-4c52-af29-7dc3e1c2eb47


You can also read more about this on our [learning center](https://learning.postman.com/docs/collections/running-collections/working-with-data-files/#data-file-format). 

Hope this helps. Thanks everyone for giving us feedback on this. 

I will be closing this ticket but please feel free to ask questions or give us feedback.  

Regards,
Malvika

**Comment by ninjeffontherun** [comment]
I am running into the opposite problem where postman is removing trailing 0s from my API call
![image](https://github.com/postmanlabs/postman-app-support/assets/41549994/59742814-7be9-4b1b-a3fa-7ac8522fd9c8)
