### ISSUE TITLE
Global Variables is not being recognised inside the JSON Body

### ISSUE THREAD

**Issue by eheinen** [a85/POSTMan-Chrome-Extension#2735]
When I just defined a Global Variable and tried to use it into my JSON Raw Body. It came as undefined. But when I change the variable to environment, it works.

Example:

{
  "name" : "Name - {{RANDOM_UUID}}"
}

 1. Postman Version: 4.10.2
 2. App (Chrome app or Mac app): Chrome 56.0.2924.87
 3. OS details: OS X / x86-64
 4. Is the Interceptor on and enabled in the app: Yes
 5. Did you encounter this recently, or has this bug always been there: Recently
 6. Expected behaviour: It should get my Global Variable value
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app): 
 8. Screenshots (if applicable)

1 - Define a global variable
2 - In your POST request set the Body raw JSON format
3 - Enter a JSON using a string + global variable. e.g.: "Name - {{variable}}"

**Comment by sdnts** [comment]
@eheinen In your case, since `{{variable}}` is inside double quotes, it is treated as a String, hence not modified. You should include `Name - ` in the global variable and then use it as such:

```
{
    "name": {{RANDOM_UUID}}
}
```

Please feel free to reopen if I misunderstood :)

**Comment by eheinen** [comment]
After I restarted the Postman it started to work as "Name - {{RANDOM_UUID}}"
