### ISSUE TITLE
"Close Window" closes all windows instead of only the current one

### ISSUE THREAD

**Issue by FM-96** [a85/POSTMan-Chrome-Extension#2738]
Version/App Information:

 1. Postman Version: v4.10.2
 2. App: Windows app
 3. OS details: Windows 10 Home
 4. Is the Interceptor on and enabled in the app: N/A
 5. Did you encounter this recently, or has this bug always been there: Unknown; I only just installed the Windows app.
 6. Expected behaviour: Only the one window closes, all others stay open.
 7. Console logs: Not possible, as the app closes.

Steps to reproduce the problem:

1. Open Postman
2. Click the "Open a new Postman Window" button
3. In the new window, either click File -> Close Window, or press Ctrl+Shift+W, or click the red X at the top right of the window.

Expected behaviour: The window closes, the other window stays open.
Actual behaviour: Both windows close.

Additional information:

The Chrome app (which is what I used until now) does not have this issue.

**Comment by vegetableman** [comment]
@FM-96 Thanks for posting this issue 👍 . Will keep you posted ^_^.

**Comment by tienle488** [comment]
yes, please!

**Comment by a85** [comment]
Seems to be fixed in the latest release.

**Comment by tienle488** [comment]
thank YOU for the fix!!
