### ISSUE TITLE
500/800 errors hang at "Fetching data..."

### ISSUE THREAD

**Issue by jpumph** [a85/POSTMan-Chrome-Extension#274]
Frequently when testing REST calls that return 500 or 800 errors, rather than returning the error code the Start button gets stuck at "Fetching data..." and it quickly times out and displays the results from the last call you made, which is misleading. The only way to tell you're looking at old results is to make sure that Fetching isn't still showing. 
![fetching](https://f.cloud.github.com/assets/3694617/468176/bc6c7750-b68d-11e2-99bf-103806f7c61a.jpg)

**Comment by johannesjo** [comment]
Still an issue for me. Postman seems unable to handle any errors.

**Comment by abhijitkane** [comment]
@johannesjo What version of Postman are you using?

**Comment by johannesjo** [comment]
Well apparently an old one. The issue does not seem to persist for the latest. Not really specific to postman, but do you know, if I have to update all chrome apps manually?

**Comment by abhijitkane** [comment]
Chrome updates apps erratically. All apps are supposed to be checked for newer versions every 4-5 days, but we have users using versions of Postman that are a few months old.

**Comment by johannesjo** [comment]
Thank you. That's interesting to know.
