### ISSUE TITLE
feature request: 'master collection' to sync changes in calls to multiple 'normal' collection

### ISSUE THREAD

**Issue by SORC3r3r** [a85/POSTMan-Chrome-Extension#2740]
It would be nice to have a kind of 'master' collections which contains a library of REST calls. This master collection would not be designated for newman tests or postman runner, it rather serves as area to modify your REST calls. 

For my application I have different test cases which need to be tested with different collections. The collections basically contain the same REST calls but differ in their order.
If something changes in my API I have to change every call seperately.
By linking the REST calls of a 'master' collection to the other 'normal' collections and then changing the 'master' REST calls, all REST calls in the 'normal' collections would be changed as well.
I thought about using the environment variables but I can´t  forsee which structural and content changes will be made in the API.

**Comment by madebysid** [comment]
@SORC3r3r That's an interesting idea. Now I don't know what your setup looks like exactly, but do environments not help in such situations?
I'm thinking out loud here, but maybe you could have an environment variable that governs the order of requests? Let me know if I misunderstood, though.

**Comment by sdnts** [comment]
@SORC3r3r That's an interesting idea. While collections are usually meant to be independent, I'm guessing you're talking about some sort of inheritance right?

**Comment by SORC3r3r** [comment]
@madebysid Yes, thats right. I think of a master/base collection which will pass on the properties of the included calls to calls in other collections which maybe are linked or directly derived from the master/base collection. It would be nice to derive the calls just like duplicating, but the derived ones properties would depend on the master/base collection calls whilst the duplicated are independent ones.

**Comment by vkaegis** [comment]
Hey guys, you can now fork collections and merge changes back between them (as of v6.7.1). 

This fits in to your exact use case as your original collection or "master" can be forked to create multiple "normal" collections, and changes to the normal ones can be merged back into the master as and when required.

Closing this issue for now, feel free to open another if you have more feedback around this implementation.
