### ISSUE TITLE
App is blank after fresh install

### ISSUE THREAD

**Issue by mcanepa** [a85/POSTMan-Chrome-Extension#2742]
1. Postman Version: 4.10.2 win64
 2. App (Chrome app or Mac app): Windows
 3. OS details: Windows 10 Home x64
 4. Is the Interceptor on and enabled in the app: Don't think so
 5. Did you encounter this recently, or has this bug always been there: Recently
 6. Expected behaviour: See the app
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
Fail To load file:///C:/Users/#1\AppData\Local\Postman\app-4.10.2\resources\app.asar\background-modules/../html/requester.html
resource: net::ERR_FILE_NOT_FOUND
 8. Screenshots (if applicable)
![postman](https://cloud.githubusercontent.com/assets/25961439/23223653/5df25e9c-f90a-11e6-80f3-9faf984a0212.png)

Download de app from https://www.getpostman.com/ and select Win x64. Then try to install.

I saw #2256, but that did't help. What can I do to get this working?

**Comment by vegetableman** [comment]
@mcanepa Could you open the app directly through the command prompt and share the screenshot or logs from there?
Path for the same: `C:\Users\<User>\AppData\Local\Postman\app.4.10.2\Postman.exe`

**Comment by mcanepa** [comment]
The same...

Can I do something else?

![postman20170301](https://cloud.githubusercontent.com/assets/25961439/23462088/3a5ac4cc-fe6b-11e6-8752-1fddb1490421.jpg)

**Comment by sdnts** [comment]
@mcanepa Something else looks off here. AFAIK, Windows uses a forward slash (`/`) to separate file paths, not a backslash(`\`). Your path seems to have a weird combination of both. Have you tried completely removing and reinstalling? (4.10.3 is the latest version as of now)

**Comment by mcanepa** [comment]
Just download 4.10.3
Still getting a blank window and the error is the same

**Comment by mcanepa** [comment]
Just download 5.0.2
Still getting a blank window and the error is the same:
Failed to load resource: net::ERR_FILE_NOT_FOUND
file:///C:/Users/#1\AppData\Local\Postman\app-5.0.2\resources\app.asar\background-modules/../html/requester.html

May be that "#1" in the path (username) has something to do with it

**Comment by mcanepa** [comment]
any progress on this?

**Comment by Tosch8** [comment]
got exactly the same issue for 5.1.3...

**Comment by Tosch8** [comment]
@mcanepa: is #1 the name of your user? I had the same problem since the new installation of Windows10. My user also had a # in the username. I changed it in the registry (from Tosch#8 to Tosch8). Now Postman is working without any problems :-) Maybe you can also try that.

**Comment by mcanepa** [comment]
@Tosch8 Yes, that's my username! I'll try your suggestion. Thanks =)

**Comment by mcanepa** [comment]
Well I had problems doing that, but I think that maybe we've found out what the problem was.

Let's hope this gets fixed soon.

**Comment by SamvelRaja** [comment]
@all We rolled out the fix for this issue in our canary channel. 
Requesting you guys to download and check the same from [here](https://www.getpostman.com/canary)
