### ISSUE TITLE
HTML entities are copied as their respective characters

### ISSUE THREAD

**Issue by matt-tingen** [a85/POSTMan-Chrome-Extension#2743]
**Version/App Information:**
 1. Postman Version: 4.10.2
 2. App (Chrome app or Mac app): Mac App
 3. OS details: macOS 10.12.3
 4. Is the Interceptor on and enabled in the app: No
 5. Did you encounter this recently, or has this bug always been there: Noticed recently, but may have been there a while
 6. Expected behavior: Copying a response with HTML entities copies the raw response.
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 8. Screenshots (if applicable)

**Steps to reproduce the problem:**
1. GET a page/endpoint whose response includes HTML entities e.g. `{"foo":"&quot;"}`
2. Click the "copy response" button
3. Paste the response somewhere

**Observed result:**
The response is copied with HTML entities rendered as their respective characters.

This is particularly troublesome for JSON where it can copy invalid JSON due to unescaped quotes. This can be seen with what is copied for the above example:
```
{
    "foo": """
}
```

Regardless of what view pane is selected, Postman seems to copy what is represented in the Preview pane. I would expect it to copy the response as displayed in the selected view or to always copy the raw response.

**Comment by vegetableman** [comment]
Thanks for posting this issue 👍 . We were able to reproduce this issue. Will keep you posted.

**Comment by vegetableman** [comment]
@matt-tingen The issue has been fixed and is part of the latest release `4.10.5`. Feel free to reopen if it still exists. ^_^
