### ISSUE TITLE
Feature Request - Need a button to close All tabs and the ability to not save/save the data

### ISSUE THREAD

**Issue by vgadolin** [a85/POSTMan-Chrome-Extension#2745]
1. Postman Version: 4.10.2
 2. App (Chrome app or Mac app): Windows
 3. OS details: Windows 10
 4. Is the Interceptor on and enabled in the app: Yes
 5. Did you encounter this recently, or has this bug always been there: Always been there
 6. Expected behaviour: Click a button that closes all tabs and the ability for a pop-up or something to save or not save the data from the tabs
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 8. Screenshots (if applicable)

I run multiple collections and sometimes in manual mode.  
-->This creates a tab for each test in my collection when I change something.
-->I would like the ability to close all of the tabs instead of having to close each one manually.  This takes a long time especially if I need to make a bunch of changes.

**Comment by vegetableman** [comment]
@vgadolin The latest version `4.10.3` supports closing all tabs. You just have to right click on the tab to see the options.
![screen shot 2017-03-02 at 6 46 56 pm](https://cloud.githubusercontent.com/assets/1330851/23508651/bacbf8ac-ff78-11e6-8c28-5fe388780e24.png)

**Comment by d-schmidt** [comment]
@vegetableman I've got no right click menu in 4.10.3. Do I have to activate it somewhere?

**Comment by mbuquet** [comment]
@d-schmidt Same here, I do not have a right click menu on 4.10.3 (Windows app). ( @vegetableman )

**Comment by vegetableman** [comment]
@d-schmidt @mbuquet Did you guys right-click on the tab?
![image](https://cloud.githubusercontent.com/assets/1330851/23698604/235e08e0-0412-11e7-8668-32929685f65b.png)

**Comment by d-schmidt** [comment]
@vegetableman Yes. The pointy finger mouse cursor does change into an arrow but the menu doesn't appear.

**Comment by vegetableman** [comment]
@d-schmidt Are you on the chrome or native app?. Could you share a screenshot of the app?.

**Comment by d-schmidt** [comment]
I'm using the chrome app. I'm starting it using a desktop link created by chrome `chrome://apps/`.

The screenshot doesn't show much:
![postman](https://cloud.githubusercontent.com/assets/3226483/23702965/d38f8aaa-03fd-11e7-9cd6-c1e6232424ee.PNG)

**Comment by vegetableman** [comment]
@d-schmidt As of now, the chrome app does not support the tab context menu.

**Comment by d-schmidt** [comment]
So there is no way to close all or at least close without save? Closing postman closed all tabs without saving a few versions ago. Could we get this back as a setting?

The popup box asking me to save is annoying. I would also be okay with "never save" option.

**Comment by vegetableman** [comment]
Closing this issue. @d-schmidt Could you create an issue related to the `never save` option, so that we could keep you posted on the same ?

**Comment by aaabramov** [comment]
I will leave this for people who are using newer versions and are trying to find `Close All Tabs` button:

<img width="1020" alt="screen shot 2017-10-10 at 13 17 40" src="https://user-images.githubusercontent.com/11317222/31381539-8776916c-adbd-11e7-8e14-2c7524b133c6.png">

**Comment by aaabramov** [comment]
How? How this could ever happen? I have unassigned @vegetableman from this ticket :D

<img width="780" alt="screen shot 2017-10-10 at 13 19 10" src="https://user-images.githubusercontent.com/11317222/31381598-b387dc98-adbd-11e7-924f-03f6fbe81973.png">
