### ISSUE TITLE
Accidentally sending of requests when editing URI

### ISSUE THREAD

**Issue by joelhellman** [a85/POSTMan-Chrome-Extension#2746]
I find it way too easy to accidentally send off a request, when all I wanted was to edit URI.

![image](https://cloud.githubusercontent.com/assets/3614135/23236001/e2e04e46-f957-11e6-870f-211f07b3782f.png)

So if I press ENTER while the URI field is in focus (because I'm editing it), my Postman sends the request right away. Unlike for example when I edit rename in either of these dialogs, where ENTER is required to save:

![image](https://cloud.githubusercontent.com/assets/3614135/23236100/3ae5c904-f958-11e6-8b09-22557546536a.png)

![image](https://cloud.githubusercontent.com/assets/3614135/23236138/50d83b8e-f958-11e6-876a-a53dd05bee4e.png)

Version/App Information:
 1. Postman Version: Postman for Chrome
 2. App (Chrome app or Mac app): Version 4.10.2 Chrome 56.0.2924.87
 3. OS details: win / x86-64
 4. Is the Interceptor on and enabled in the app: no
 5. Did you encounter this recently, or has this bug always been there: can't remember
 6. Expected behaviour: a shortcut like ctrl-ENTER to trigger request

**Comment by vegetableman** [comment]
@joelhellman Thanks for letting us know about this issue ^_^. However, this might cause issue for existing users, who are used to the edit and enter flow.

**Comment by joelhellman** [comment]
Perhaps as an option if others prefer how it works today, then? Like `[x] Use ctrl-enter instead of enter to send requests`. 

While you will get used to how it currently works, if that means first firing off a unintentional request or two, I would prefer a less 'eager' default shortcut.  When I shared my library with my colleague (who didn't use Postman) he triggered a POST request right away when he duplicated a request and changed the uri. Luckily it wasn't a DELETE...

**Comment by a85** [comment]
We'll make shortcuts customizable to solve this among other issues.
