### ISSUE TITLE
Getting the slow response

### ISSUE THREAD

**Issue by jayasimharr** [a85/POSTMan-Chrome-Extension#2747]
1. Postman Version:v4.10.2
 2. App (Chrome app or Mac app):Chrome app
 3. OS details:Windows 7 p
 4. Is the Interceptor on and enabled in the app: NO
 5. Did you encounter this recently, or has this bug always been there: from last 2 weeks 
 6. Expected behaviour: response should come very quickly
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 8. Screenshots (if applicable)

**Comment by vegetableman** [comment]
@jayasimharr Could you share a screenshot of the `Timing` tab from the network panel of the devtools?. To open up the devtools, you could refer: https://www.getpostman.com/docs/errors.
