### ISSUE TITLE
Editing duplicated environment edits the environment duplicated from too

### ISSUE THREAD

**Issue by SORC3r3r** [a85/POSTMan-Chrome-Extension#2748]
1. Postman Version: 4.10.2
 2. App (Chrome app or Mac app): Windows Download
 3. OS details: Windows NT 6.1
 4. Is the Interceptor on and enabled in the app:
 5. Did you encounter this recently, or has this bug always been there: always
 6. Expected behaviour: editing duplicated environment only changes properties of environment which is edited, not the environment duplicated from too

Steps to reproduce:
1. create a new environemnt or use existing environment with a couple of variables 
![1](https://cloud.githubusercontent.com/assets/22958825/23250654/5e6ba4be-f9aa-11e6-81d1-7d783b206bc3.PNG)
2. duplicate the environment
![2](https://cloud.githubusercontent.com/assets/22958825/23250663/66115524-f9aa-11e6-9ccb-c9296ad1c103.PNG)
3. edit the variables in the duplicated environment and update
![3](https://cloud.githubusercontent.com/assets/22958825/23250668/69d72422-f9aa-11e6-96c3-0c3d16a89689.PNG)
4. take a look into the environment duplicated from; it was edited too
![4](https://cloud.githubusercontent.com/assets/22958825/23250672/6cebfb9c-f9aa-11e6-9e85-fbf243ec0eb6.PNG)

**Comment by SORC3r3r** [comment]
It works fine with the Chrome App.

**Comment by vegetableman** [comment]
@SORC3r3r Could you reload the app and check if the changes made to the duplicate environment are persisted on the original environment?

**Comment by SORC3r3r** [comment]
@vegetableman If I create a duplicate, do changes in the duplicate, close the application and restart it - the changes are not persisted to the original.

**Comment by vegetableman** [comment]
@SORC3r3r The issue is quite intermittent. Tagging this as a bug. Will keep you posted.

**Comment by maccer83** [comment]
I get this as well in the Mac app v 4.10.7. If I duplicate a command (right-click its tab and choose "Duplicate"), and then edit the name of the duplicated tab (by clicking the pen icon and writing a new name), the original tab gets the new name as well. In my case, the name change for the old tab persists even after a close / restart of the app.

**Comment by SORC3r3r** [comment]
@maccer83 Maybe try duplicating your command then restart the application and then make the changes?
I know restarting is not an elegant solution but maybe it works for now.
