### ISSUE TITLE
Request ability to create collection nodes that do not make a request and only execute JavaScript

### ISSUE THREAD

**Issue by JohnArrowwood** [a85/POSTMan-Chrome-Extension#2749]
I use collections as a series of requests intended to complete a process.

For example: 
> connect to API server A and create a record
> connect to API server B and query for the record just created - verify that it is found

My requests are generic and reusable, so they make heavy use of environment variables.  In order to complete the example above, I insert requests that clearly communicate what is going on:

> -- server A --
> create a record
> -- server B --
> query for record - verify that it is found

The only thing that the "-- server A --" and "-- server B --" request does is execute JavaScript.

I much prefer this over hiding the logic in the requests themselves because it makes it easier to maintain and modify the scenario if there are not hidden assumptions and requirements.  I can add another request into the sequence without worrying about the environment switch not happening at the right place in the flow.

However, Postman doesn't let me ONLY execute JavaScript, so instead I have to execute a request, e.g. GET http://echo.postman.com/ - and only when it is complete can I progress to the next request.

I'm asking for the ability, in some way, to add a "request" that doesn't actually initiate any network communications.  That way I can execute arbitrary JavaScript in the middle of a collection without having to tie that Script to an unnecessary HTTP request.  

An easy way to implement that is to add a new http method that is "NO-OP", "NONE", "SKIP", or "INTERNAL" (or something) which, if selected, causes the request to actually not do anything.  That may not be the ideal solution, but I'm not coming up with anything more ideal, at the moment.

**Comment by sandeepbantode** [comment]
I am also looking forward to get this feature sooner, to solve my automation juggling.

**Comment by sadiqkhoja** [comment]
any expected released date of this?

**Comment by sdnts** [comment]
There isn't a concrete date for this, but this is part of our near-term product roadmap: https://trello.com/b/4N7PnHAz/postman-roadmap-for-developers

**Comment by a85** [comment]
Collection and folder level scripts are now available in 5.4+

**Comment by JohnArrowwood** [comment]
I'm sorry, but I don't see how my ask has been satisfied.

I want a dummy request that doesn't make a request.  If I leave the URL blank, it errors out.  So for now, I put www.example.com, but that is not fair to them, and it slows down my execution.

**Comment by JohnArrowwood** [comment]
And I can't seem to re-open the issue.
