### ISSUE TITLE
"Copy to Clipboard"-button on "Pretty" HTML breaks inline scripts

### ISSUE THREAD

**Issue by aripalo** [a85/POSTMan-Chrome-Extension#2752]
1. Postman Version:
`4.10.2`
 2. App (Chrome app or Mac app):
App
 3. OS details:
macOS Sierra `10.12.2 (16C67)`
 4. Is the Interceptor on and enabled in the app:
Off.
 5. Did you encounter this recently, or has this bug always been there:
Recently. 
 6. Expected behaviour:
  Copy the response HTML as pretty printed, but do not insert newline characters into JavaScript strings and by doing so breaking syntax on inline `<script>`-elements.
 
7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
Nothing interesting, just the default stuff:
```
================================================================
     o
   (/) P O S T M A N
   ^

   Go to View -> Show Postman Console to check your script logs. 

================================================================
sails.io.js:142 🌏 sync service connectivity initiated
sails.io.js:759 socket replaying queued commands
sails.io.js:142 🌏 connected to sync service.
3xml.js:22 🐶 watchdog checking connection health
xml.js:22 🐶 watchdog checking connection health
sails.io.js:142 🌏 disconnected from sync service. possibly a network outage.
sails.io.js:142 🌏 scheduled reconnection attempt #1 after 9695ms
```
 8. Screenshots (if applicable)
![screen shot 2017-02-24 at 14 38 21](https://cloud.githubusercontent.com/assets/679146/23304207/30f1624c-faa1-11e6-96f9-a8bfdcb8f98f.png)

 9. **Steps to reproduce the problem:**

  - `source.html`:
```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Hello</title>
</head>
<body>
  <script type="text/javascript">
    var element = 'div';
    var klass = 'bar';
    var foo = '<' + element + ' class="' + klass + '"></' + element + '>';
  </script>
</body>
</html>
```
  - Serve `source.html` on `http://localhost:<port>`

  - Request content from `http://localhost:<port>` with Postman

  - Select "Pretty"-view

  - Click "Copy to Clipboard" -button

  - Paste into file `pbpaste > pasted-from-postman.html`

  - View `pasted-from-postman.html` contents:
```html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Hello</title>
    </head>
    <body>
        <script type="text/javascript">
    var element = 'div';
    var klass = 'bar';
    var foo = '<' + element + ' class="' + klass + '">
        </' + element + '>';
    </script>
</body>
</html>
```

… notice the linebreak after `klass + '">`!

**Comment by vegetableman** [comment]
@aripalo You could switch to the Raw mode and then copy, which would give you the desired result. In case of pretty mode, the copy to clipboard applies the same formatting as the response viewer to keep the result same.
