### ISSUE TITLE
While Postman Chrome extension can GET an url,  Postman Windows app cannot

### ISSUE THREAD

**Issue by Olf42bur** [a85/POSTMan-Chrome-Extension#2754]
Hello, I'm stuck with an issue, I can't figure out what the heck could be happening in the ridiculous simple scenario :/ 

1. Postman Version: 4.10.2
 2. App (Chrome app or Mac app): Windows App
 3. OS details: Windows 10
 4. Is the Interceptor on and enabled in the app: Yes (in chrome extension)

 5. Did you encounter this recently, or has this bug always been there: Always
 6. Expected behaviour: GET the page in the windows app, as the chrome extension
 7. Console logs: **Error: connect ECONNREFUSED 138.197.228.101:443**
 8. Screenshots: https://goo.gl/KSSJVy  ![image](https://cloud.githubusercontent.com/assets/7925133/23320573/574a77b4-faa9-11e6-99e9-d58b0bd9c564.png)

Steps to reproduce the problem:
- Try to get to the website, with your browser: https://rita-latest.overture.barco.com 
  - The website works fine, https certificates are all good.
- Try to GET the same url via Postman as windows app
  - Could not get any response

**Comment by vegetableman** [comment]
@Olf42bur The issue was not reproducible with the url shared. Could you let us know if you are behind a proxy?.

**Comment by Olf42bur** [comment]
Hello @vegetableman ! Thank you for your answer.

I don't think I'm behind any proxy.

I have no clue how this can happens; But well, after the weekend, everything works good !

I'm lost about what could have happened, but we can close this ticket, for the moment :)
