### ISSUE TITLE
postman chrome and windows app API request to azure with bearer

### ISSUE THREAD

**Issue by dealharris** [a85/POSTMan-Chrome-Extension#2755]
GET request with Bearer fails

 1. Postman Version: 4.10.2
 2. App (Chrome app or Mac app): Chrome
 3. OS details: Windows 10
 4. Is the Interceptor on and enabled in the app: Yes
 5. Did you encounter this recently, or has this bug always been there: recently, only on requests made with bearer
 6. Expected behaviour: 
 7. Console logs - see below:

Blocked script execution in 'filesystem:chrome-extension://fhbjgbiflinjbdggehcddcbncdddomop/temporary/response.html' because the document's frame is sandboxed and the 'allow-scripts' permission is not set.

**Comment by dealharris** [comment]
checked in both chrome and windows app, same error

**Comment by jongio** [comment]
Which API are you trying to call?  I have some of the ARM and IoT calls working, details here: http://blog.jongallant.com/tags/postman/

**Comment by harryi3t** [comment]
@dealharris can you try this on the native app and let us know the API you are using, the error message and the console logs

**Comment by dealharris** [comment]
apologies, but this was awhile ago and not sure why my original request didnt include the API request. This had to do with the common oauth2 authorization...e.g request for Auth code with SSO login (https://login.microsoftonline.com/common/oauth2/authorize) then using Auth Code make request for Access token (https://login.microsoftonline.com/common/oauth2/token).

**Comment by ghost** [comment]
anyone able to call key vault sign successfully? (https://docs.microsoft.com/en-us/rest/api/keyvault/sign/sign) It would be better if there is an example.
