### ISSUE TITLE
When saving a request after adding Authorization options, URL becomes [object Object]

### ISSUE THREAD

**Issue by lgo** [a85/POSTMan-Chrome-Extension#2757]
1. Postman Version: 4.10.2 (4.10.2)
 2. App (Chrome app or Mac app): Mac app
 3. OS details: OS X 4.10.2 (4.10.2)
 4. Is the Interceptor on and enabled in the app: No
 5. Did you encounter this recently, or has this bug always been there: Yes, just encountered
 6. Expected behaviour:

Expect it to save the request. To reproduce this:
- Create a request, e.g. `{{base_url}}/v2/users/:user_id`
- Save it
- Change it to have Authorization Basic, e.g. user: `{{ token }}`, password: blank
- Save again
- URL becomes `[object Object]` and is unsaved.

 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
```
common.js:4312 Uncaught TypeError: url.indexOf is not a functiongetURLPathVariables @ xml.js:22
getPathVariablesValues @ xml.js:22
handleModelURLChange @ xml.js:22
triggerEvents @ common.js:60497
triggerApi @ common.js:60482
eventsApi @ common.js:60281
Events.trigger @ common.js:60472
set @ common.js:60642
process @ xml.js:22
handleSubmitForm @ xml.js:22
handleSubmitForm @ xml.js:22
handleClick @ common.js:55704
invokeGuardedCallback @ common.js:4286
executeDispatch @ common.js:4131
executeDispatchesInOrder @ common.js:4154
executeDispatchesAndRelease @ common.js:3586
executeDispatchesAndReleaseTopLevel @ common.js:3597
forEachAccumulated @ common.js:4428
processEventQueue @ common.js:3802
runEventQueueInBatch @ common.js:4457
handleTopLevel @ common.js:4473
handleTopLevelWithoutPath @ common.js:14647
handleTopLevelImpl @ common.js:14627
perform @ common.js:6617
batchedUpdates @ common.js:10641
batchedUpdates @ common.js:6125
dispatchEvent @ common.js:14758
```

 8. Screenshots (if applicable)
<img width="1113" alt="screen shot 2017-02-26 at 14 37 20" src="https://cloud.githubusercontent.com/assets/1161183/23344414/e04299a6-fc30-11e6-8bd6-57ad7844758c.png">

**Comment by kamalaknn** [comment]
Hey @xLegoz,

The fix for this issue has been rolled out as part of the 4.10.5 release.

Please let us know if this issue still exists. Closing this for now.
