### ISSUE TITLE
AltGr+2 Hotkey prevents @ symbol on German Keyboards

### ISSUE THREAD

**Issue by cawoodm** [a85/POSTMan-Chrome-Extension#2758]
On German keyboards `AltGr+2` is how you enter the `@` symbol. This seems to be blocked or otherwise assigned in Postman so that when you press the key combination the input box loses focus and no `@` key is entered. This makes it really problematic since `@` can be used in usernames for authentication or in URL parameters. Workaround is to copy the symbol to the clipboard and use `Ctrl+V` to paste it into postman.

Postman for Chrome
Version 4.10.2
win / x86-64
Chrome 54.0.2840.59

**Comment by JuanDMeGon** [comment]
Having the same issue. Confirmed on Windows 10 with a Latin keyboard.

**Comment by gimlichael** [comment]
Confirmed. Same on Danish keyboard :-(

**Comment by prashantagarwal** [comment]
Closing this, as we're tracking this here: #2707 . I'll keep that thread up-to-date
