### ISSUE TITLE
Markdown ignored on requests viewdocs

### ISSUE THREAD

**Issue by LokizFenrir** [a85/POSTMan-Chrome-Extension#2759]
**_Version/App Information:_**
Postman v4.10.2
Win 7 Professional SP1
Interceptor disabled
Always been there

**_Expected behaviour:_**
**Given** description is added in markdown to either sub collection folders or requests themselves
**then** markdown should be applied
**when** viewing the collection "ViewDocs"

**_Steps to reproduce the problem:_**
Add markdown description to any sub collection folder or request.

**Comment by vegetableman** [comment]
@LokizFenrir Could you elaborate on the issue with screenshots?. We are not able to reproduce it.

**Comment by LokizFenrir** [comment]
Seems there was a caching issue on my local machine on chrome viewdocs ended up with not decorating the markdown descriptions properly.

Can confirm is working properly.
