### ISSUE TITLE
Postman does not send any request... not working at all

### ISSUE THREAD

**Issue by yasmeenhashem** [a85/POSTMan-Chrome-Extension#2760]
1. Postman Version:
 2. App (Chrome app or Mac app):
 3. OS details:
 4. Is the Interceptor on and enabled in the app:
 5. Did you encounter this recently, or has this bug always been there:
 6. Expected behaviour:
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 8. Screenshots (if applicable)

**Comment by vegetableman** [comment]
@yasmeenhashem Could you fill in the details above? so that we could help you better ^_^.

**Comment by bramus** [comment]
I'm having the same issue. I have both Chrome (60) and Chrome Canary (62) installed (on Mac OS Sierra 10.12.6). Therefore have two installs of Postman laying around _(one linked to each version of chrome)_.

Only the one linked to Chrome Canary (62) actually does something. The one linked to Chrome (60) does nothing:
- The only allowed call is to http://localhost/. All others (somehow) yield a connection error.
- The Interceptor being installed or not does not help. 
- Resetting the chrome://flags to their defaults has no effect.

Hope this helps somehow in the investigation of this issue.

**Comment by sdnts** [comment]
@bramus Have you tried out the steps on the error screen? If both Postman versions are the same, I suspect you have some settings different that is causing this.

<img width="1201" alt="screenshot 2017-08-21 18 07 50" src="https://user-images.githubusercontent.com/7689783/29519606-ac122638-869b-11e7-95c5-4212c5c8f978.png">

**Comment by bramus** [comment]
I checked and could not immediately find any differences. Eventually switched to the standalone Mac app, which works fine.

**Comment by sdnts** [comment]
@bramus Weird. I'd recommend sticking to the native app anyway, since Google will end support for all Chrome apps this year. I'm closing this issue then :)
