### ISSUE TITLE
feature request: export sub folders 

### ISSUE THREAD

**Issue by SORC3r3r** [a85/POSTMan-Chrome-Extension#2761]
feature request:
It would be nice to directly export sub folders as a collection.
I think the only way to do this now would be to duplicate the sub folder and move it to a 1st lvl folder and then export the 1st lvl folder.

Another useful feature would be the possibility to move a 1st lvl folder to another folder - to make it a sub folder of another 1st lvl folder.

**Comment by vegetableman** [comment]
@SORC3r3r Support for nested folders (sub folder) with in a collection (1st lvl folder) is being worked on. Could you elaborate on your use-case for nested collections?

**Comment by a85** [comment]
We will be improving drag/drop capabilities + other folder capabilities. Exporting a folder will be possible through those flows.

**Comment by SORC3r3r** [comment]
I think it is still not possible to export a nested-folder as seperate collection.
And via drag/drop I am not able to drag/drop a nested-folder to the 'collection level'.
Are you planning on improving this?

**Comment by SamvelRaja** [comment]
@SORC3r3r can you provide me the info on which version of the app and the steps to reproduce the issue you are facing? This will help in tracing down the issue much closer.

**Comment by SORC3r3r** [comment]
I am using Version 5.1.3
I have nested folders in my collections which I would like to export as stand-alone collection.
For example I have a collection which contains bug tests for an api.
Every bug test is in a nested folder within the collection and may consist of multiple REST calls.
I need to run the collection in the postman runner to test all bug fixes. But I would like to export the bug-testing-nested-folder seperately to attach them to the test executions for the bugs.
Therefor I need to export the nested-folder as stand-alone collection.

**Comment by brendanborgelt** [comment]
+1 for this feature

**Comment by fsudderth** [comment]
+1

**Comment by thanhdatbkhn** [comment]
+1

**Comment by PrinceAnsong** [comment]
+1

**Comment by njuro** [comment]
+1

**Comment by prezire** [comment]
This is useful when sharing multiple request collection folders to the team. Not the entire collection, but just folders. Take for example in our case, currently we have lots of different web hooks with URLs and associated sample JSON payloads. It would be nice to probably ZIP the root folder and put it in the project management tool to be shared with.

**Comment by el-nuru** [comment]
+1

**Comment by lucas-g-simoes** [comment]
+1

**Comment by tonypaolucci** [comment]
@prezire  Agreed. In my case we work with a few 3rd party vendors to aid in development and any updates or improvements I make to the collection in their dedicated folder could be immediately exported for their use.

**Comment by neriya197** [comment]
+1

**Comment by WillFelisberto** [comment]
+1

**Comment by sambhusai** [comment]
+1, ran into this scenario where I would like to export one of my folder from a collection

**Comment by HenrrySalinasJala** [comment]
+1

**Comment by shatk** [comment]
we are using postman v8.0.6. is this feature in place ? If not strongly recommend this feature to be part of the product where we don't need to export the whole project api's to share few api's.

**Comment by sikri-eic** [comment]
> We will be improving drag/drop capabilities + other folder capabilities. Exporting a folder will be possible through those flows.

@a85, Your comment is 4 years old. Is this idea still in the backlog, or has it been abandoned.

**Comment by archongum** [comment]
Workaround: create a new collection for export purpose, then drag and drop the subfolder you wanna export to the collection, and export the collection.

**Comment by JohnT1** [comment]
+1

**Comment by voicerecordist** [comment]
+1

**Comment by j0nimost** [comment]
> We will be improving drag/drop capabilities + other folder capabilities. Exporting a folder will be possible through those flows.

it's been 5 years

**Comment by ZenwalkerD** [comment]
+1 this thread is long open. 
Its unfortunate that a simple feature from postman is not being supported. It helps alot to share specific stuffs with respective individual.

**Comment by badeavali** [comment]
+1 
Would be extremely beneficial when you have tons of requests in a single big collection separated by sub-folders

**Comment by odaiwa** [comment]
+1
would be super helpful

**Comment by qq253498229** [comment]
+1
I noticed that the issue has been closed. Has this feature been implemented now?

**Comment by myozawlatt** [comment]
As of the year 2024, I continue to require that feature.

**Comment by alexandros-catori** [comment]
Issue closed but the feature is missing
