### ISSUE TITLE
Duplicating request does not properly select it

### ISSUE THREAD

**Issue by thurt** [a85/POSTMan-Chrome-Extension#2763]
1. Postman Version: v4.10.2
 2. App (Chrome app or Mac app): mac app
 3. OS details: osx el capitan v10.11.6
 4. Is the Interceptor on and enabled in the app: no
 5. Did you encounter this recently, or has this bug always been there: recently
 6. Expected behaviour: since the duplicate request becomes highlighted after performing a duplication, i expect that the neighboring panel would be updated to show "POST get-autocomplete copy"
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app): n/a
 8. Screenshots

Given:
![screen shot 2017-02-27 at 3 45 01 pm](https://cloud.githubusercontent.com/assets/8955144/23379313/8118e56e-fd04-11e6-8173-3972ff386995.png)

Click on Duplicate for this request:
![screen shot 2017-02-27 at 3 45 12 pm](https://cloud.githubusercontent.com/assets/8955144/23379311/7c2ae46c-fd04-11e6-987d-d09ba23474df.png)

Result of click (the duplicate appears selected):
![screen shot 2017-02-27 at 3 45 22 pm](https://cloud.githubusercontent.com/assets/8955144/23379303/75cf12e6-fd04-11e6-9e8a-a2d86653b3f2.png)

However, in neighboring panel, the title is not updated to reflect the current selection (bug):
![screen shot 2017-02-27 at 3 45 30 pm](https://cloud.githubusercontent.com/assets/8955144/23379297/712e661a-fd04-11e6-859c-2b3d9fb1f155.png)

**Comment by PFarrell89** [comment]
Confirmed in Windows client

**Comment by thurt** [comment]
@PFarrell89 @madebysid fix appears to be included in v4.10.3

![screen shot 2017-03-07 at 9 16 32 am](https://cloud.githubusercontent.com/assets/8955144/23660616/fbffe2f0-0317-11e7-9139-3a3559e761b5.png)
