### ISSUE TITLE
RAML 1.0 Folder Import Bug Due to Typed Fragments

### ISSUE THREAD

**Issue by NekoKikoushi** [a85/POSTMan-Chrome-Extension#2765]
Hi guys! Thanks for such a great product! First time reporter here!

While making a collection for the company I work for as a QA Engineer (via Windows 10 64bit on Postman v4.10.2) I noticed RAML folder imports are supported (which we're using already for our API documentation). However it doesn't appear that Postman supports Typed Fragments as defined in the RAML 1.0 specification. Specifically we are using "ResourceType" typed fragments.

Every file in our raml resource folder throws a postman exception because of the very first line (which is valid per the 1.0 specification found [here](https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md#typed-fragments).
`#%RAML 1.0 ResourceType`

**Comment by MrJ0rdan** [comment]
![](https://files.slack.com/files-tmb/T025D81RC-F4B695WDQ-58de020767/pasted_image_at_2017_02_27_06_05_pm_1024.png)

**Comment by sdnts** [comment]
Hi @MrJ0rdan Thanks for letting us know! We'll look into this!

**Comment by NekoKikoushi** [comment]
Thank you we really appreciate that, keep up the great work!

**Comment by robm-sentinelda** [comment]
This is because Postman STILL does not support RAML 1.0 -- only 0.8

see https://github.com/postmanlabs/postman-app-support/issues/1906

**Comment by DannyDainton** [comment]
Closing this issue as it has now been resolved in version: 7.22.1

Please feel free to reopen with the steps to reproduce if the issue persists.
