### ISSUE TITLE
Option to remove close buttons from tabs

### ISSUE THREAD

**Issue by alan-givati** [a85/POSTMan-Chrome-Extension#2766]
The close button takes up a large amount of space on each tab, and most importantly its very easy to click on accidentally.  Please add an option to disable close buttons.  Obviously this works only if there is another mechanism to close tabs (like a keyboard shortcut or middle-click).

**Comment by sdnts** [comment]
Hi @alan-givati! Do you have tons of tabs open? The close button, currently, is visible only when you hover over a tab, but stays invisible other times, mimicking the behaviour of most modern browsers. Is this not ideal?

**Comment by alan-givati** [comment]
Hi @madebysid I prefer to middle-click to close tabs.  That way there is no chance I can accidentally close a tab when all I wanted was to select it.  At the moment its easy to accidentally close tabs, especially when there are many open.

**Comment by sdnts** [comment]
@alan-givati Ah, you should be able to middle-click to close a tab, but we'll look into making accidental tab closes rare.
