### ISSUE TITLE
Chrome extension appends GET parameters on every request when OAuth 1.0 helper is used

### ISSUE THREAD

**Issue by dvishniakov** [a85/POSTMan-Chrome-Extension#2767]
1. Postman Version: 4.10.2
 2. App (Chrome app or Mac app): Chrome affected. Mac version is not affected
 3. OS details: OS X El Capitan 10.11.6
 4. Is the Interceptor on and enabled in the app: Tried both. No difference
 5. Did you encounter this recently, or has this bug always been there: I didn't use Postman before
 6. Expected behaviour: OAuth parameters from the helper should replace themselves. Or even better to do not change the URL of the original request
 7. Console logs: nothing is printed in the console 
 8. Screenshots (if applicable)

Looks somewhat similar to https://github.com/postmanlabs/postman-app-support/issues/2367

1. In Postman Chrome extension, open default collections, "Auth:Others", "OAuth1.0 Verify Signature"
2. In "Headers" tab, uncheck "Authorization" header
3. Optional
- Verify that URL is not changed by pressing Send button several times
- In "Authorizaion" tab change Type combobox value to Hawk
- Verify that URL is not changed by pressing Send button several times
4. In "Authorizaion" tab change Type combobox value to OAuth 1.0
5. If Consumer key and secret are empty, fill them by copying values from the description of this request
6. Press Send button several times

URL before pressing Send button:
https://echo.getpostman.com/oauth1

URL after pressing Send once:
https://echo.getpostman.com/oauth1?code=xWnkliVQJURqB2x1&grant_type=authorization_code&redirect_uri=https://www.getpostman.com/oauth2/callback&client_id=abc123&client_secret=ssh-secret&oauth_consumer_key=RKCGzna7bv9YD57c&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1488316969&oauth_nonce=DDnLv7&oauth_version=1.0&oauth_signature=5VfxNfw6DkI14hpmcd3uN2yTNSw=

URL after pressing Send 3 times:
https://echo.getpostman.com/oauth1?code=xWnkliVQJURqB2x1&grant_type=authorization_code&redirect_uri=https://www.getpostman.com/oauth2/callback&client_id=abc123&client_secret=ssh-secret&oauth_consumer_key=RKCGzna7bv9YD57c&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1488317576&oauth_nonce=AGRIzp&oauth_version=1.0&oauth_signature=dwMOIFkBo8v0tgEIU4hn08WUNtA=&code=xWnkliVQJURqB2x1&grant_type=authorization_code&redirect_uri=https://www.getpostman.com/oauth2/callback&client_id=abc123&client_secret=ssh-secret&code=xWnkliVQJURqB2x1&grant_type=authorization_code&redirect_uri=https://www.getpostman.com/oauth2/callback&client_id=abc123&client_secret=ssh-secret&code=xWnkliVQJURqB2x1&grant_type=authorization_code&redirect_uri=https://www.getpostman.com/oauth2/callback&client_id=abc123&client_secret=ssh-secret

**Comment by sdnts** [comment]
@dvishniakov Can you try force updating to 4.10.3? I'm unable to reproduce this on 4.10.3

**Comment by dvishniakov** [comment]
@madebysid I was able to reproduce it:
Postman for Chrome  Version 4.10.3
OS X / x86-64
Chrome 56.0.2924.87

**Comment by sdnts** [comment]
@dvishniakov Weird, I'm still unable to reproduce this. Could you attach maybe a GIF or a screenshot?

**Comment by dvishniakov** [comment]
@madebysid sure, here are a few:
Screenshot 1: just after step 3 when Auth header is used - the URL is not changed yet
![screen shot 2017-03-20 at 11 23 45 am](https://cloud.githubusercontent.com/assets/11319948/24106969/e6fd495e-0d5f-11e7-8ec1-d87f94c035fc.png)

Screenshot 2: clicked "Send" button once after disabling usage of Auth header. URL is changed once
![screen shot 2017-03-20 at 11 24 04 am](https://cloud.githubusercontent.com/assets/11319948/24107040/1620b450-0d60-11e7-858b-c0ed4908a5a7.png)

Screenshot 3: a few more clicks on "Send" button shows that parameters are added several times:
![screen shot 2017-03-20 at 11 24 21 am](https://cloud.githubusercontent.com/assets/11319948/24107117/4ce699fa-0d60-11e7-9e04-41eed2490d2b.png)

**Comment by harryi3t** [comment]
@dvishniakov Chrome app is deprecated. Can you test this in the native apps?
You can download it from https://www.getpostman.com/apps

**Comment by dvishniakov** [comment]
@harryi3t if the Chrome app is deprecated, let's just close this bug then.
