### ISSUE TITLE
Loosing json body when opening saved response

### ISSUE THREAD

**Issue by lachaib** [a85/POSTMan-Chrome-Extension#2769]
1. Version 4.10.2
 2. Chrome app
 3. OS details: Windows 7
 4. Is the Interceptor on and enabled in the app: No
 5. Did you encounter this recently, or has this bug always been there: I got it only since my last update (previous version unknown but rather recent
 6. Expected behaviour:
When opening a saved response from a request, the body content of the request gets emptied, which is not expected.
Expectation = previous behaviour = when opening a response, the request stays untouched

Steps to reproduce the problem:

* Open a POST request with a json body, with a saved response
* Open saved response
* Check the body tab of the request, it is empty

 I could not reproduce with the echo example of postman, but I have it with my professional project that obviously can't be displayed.
Nothing shown in console.

I hope I gave you enough data to investigate.
Thanks

**Comment by sdnts** [comment]
Hi @lachaib, thanks for letting us know. I was able to reproduce this, albeit partially.
When opening a saved response, the request is also updated to reflect the loading the saved response. However, this isn't saved (the tab becomes dirty). If you close the tab without saving, and reopen the request, you'll see the body is still there.

However, I can understand how this can become confusing and annoying. We'll take this up soon :)
Will let you know when we have progress to report.

CC @bhawna2109 Maybe we could take another look at this flow as well?

**Comment by bhawna2109** [comment]
@lachaib responses are now saved in examples (which is basically a request+response pair). Thus, when you open an example, it opens in the examples editor and does NOT affect your base request.

More about this here- http://blog.getpostman.com/2017/05/17/mock-responses-in-postman-by-using-examples/

Would love to hear your feedback on this feature. Is there something we can improve upon?
