### ISSUE TITLE
Feature Request : Enable/Disable toggle for each request in the collection

### ISSUE THREAD

**Issue by JeanFrancoeur** [a85/POSTMan-Chrome-Extension#2770]
Hi!

We need a way to enable or disable any request in a collection.  This way, it will be easier to build/test our request chain.

Thank you in advance,
Jean

**Comment by sdnts** [comment]
Hi Jean, that's a valid use case. We'll be looking into this. Will keep you updated :)

**Comment by saswatds** [comment]
This feature is supported in the latest version of the app. Closing
