### ISSUE TITLE
Feature Request : Able to prepare the body inside the Pre-request Script tab

### ISSUE THREAD

**Issue by JeanFrancoeur** [a85/POSTMan-Chrome-Extension#2771]
Hi!

Actually, we need to prepare our body request inside the previous request by using a global or an environment variable.  It could be more useful to be able to prepare the body inside the Pre-request Script tab of the current request.  This way each request can be independently prepared, even in a complex workflow collection.

Thank you in advance,
Jean

**Comment by SamvelRaja** [comment]
@JeanFrancoeur you can always set the environment or global  value with the body you generated in the  pre request script which is been used in your request body. Attaching you the GIF with the use 
![env in pr script](https://cloud.githubusercontent.com/assets/5114052/23539267/257c51a6-0000-11e7-93bc-ad0c6eab6bf4.gif)
case, kindly let me know if i miss something

**Comment by JeanFrancoeur** [comment]
Hi!  You are right, my bad.  There was a JSON serialization related issue.  The received body was in JSON string, not in object format, so the modification was just ignored. Thank you for your time.
