### ISSUE TITLE
Option to disable tabs / Only a single tab

### ISSUE THREAD

**Issue by mbuquet** [a85/POSTMan-Chrome-Extension#2773]
1. Postman Version: 4.10.2
 2. App (Chrome app or Mac app): Windows App
 3. OS details: Windows 10 Pro 64-bit
 4. Is the Interceptor on and enabled in the app: No
 5. Did you encounter this recently, or has this bug always been there: For a while
 6. Expected behaviour: Opening requests (even if a change was made) shouldn't open a new tab

Hello,

I want to request an option to remove tabs altogether or disable opening a new tab when I open a new request if the current tab/request has had a change made to it.

My reasoning is that I make numerous requests where the only thing I am changing are parameters (GET/POST/PUT, etc) and the rest of the request remains the same. I do not need these changes saved and I end up having numerous tabs opened when going through different requests. I want everything I do in one single tab or just disable tabs altogether.

The problem is made worse since there does not seem to be a way to "close all tabs" (though I remember there being an option by Right clicking the tab, but that seems to have disappeared). Even with the close all tabs ability, I'd have to sit there and click "Don't save" for every tab closed. Leaving all the tabs opened seemed to have a performance impact when opening Postman (I didn't do any testing on this).

I have the option "Always open requests in new tab" disabled, but this only applies if there are no changes to the request in the current tab. 

Thanks!

**Comment by vegetableman** [comment]
@mbuquet Thanks for letting us know about this issue 👍  . `Close all tabs` is still around on the right click of tab name ^_^.  

To summarise your issue :
- Reopen tabs on startup - This could be a toggle-able setting. The performance impact of multiple tabs should be negligible, unless you have way too much request data on these tabs.
- Single tab / No Multiple tabs - This will take us some time to think through, if it's really a valid use-case though. If enough users chime in, we would consider it. 

Will keep you posted on this thread ^_^.

**Comment by jmoody** [comment]
> Single tab / No Multiple tabs - This will take us some time to think through, if it's really a valid use-case though. If enough users chime in, we would consider it.

Please allow a single tab.

**Comment by mpearson** [comment]
Completely agree. Tabs can be useful but it is extremely frustrating having to constantly close 20 tabs when I had no desire to create more than one. If I want a new tab, I'll create one myself.

**Comment by bhawna2109** [comment]
Hi guys, ability to force close all tabs is now supported in our latest version [(V 5.3.0)](https://www.getpostman.com/apps#changelog). 🎉  Clicking on the three dots next to the '+' icon brings up a dropdown with options to manage the tabs you're currently working with.

The last option in the dropdown -  'Force close all tabs' - will close all the tabs without prompting to save each time - 
![image](https://user-images.githubusercontent.com/14976346/31305502-b5e2a444-ab58-11e7-80df-e12148e13c3a.png)

**Comment by spdaley** [comment]
If I could +1 million this I would. This new tab behavior is driving me insane. Even with the force close all tabs option, I don't want multiple tabs most of the time so I find myself continuously having to click the "force close all tabs" option. I really love postman and what I can do with it but if there was one feature I could eradicate it would be this multi-tab feature (and the annoying red dot indicating I've made a change or something that I don't care about). I'm sure I'll get used to it eventually ... hopefully.

**Comment by jpvajda** [comment]
A preference to turn off Tabs would be awesome. I'd love to see this in the product.

**Comment by MKindy** [comment]
+1 from me.  Being stuck doing a bunch of manual testing due to some errors with data not being supplied properly by our client, and though I can just as easily close all tabs after each cycle, I often find myself in the zone and spaced out and ten 15-part collections later, Postman has 150 open tabs and is chugging along like cold molasses.

**Comment by WrecksKing** [comment]
👍 eagerly awaiting this feature!

**Comment by pss-miracle** [comment]
This sound exactly the feature we need in our organisation. Tab madness is killing effectiveness
Hope to see this in the upcoming releases

**Comment by a85** [comment]
Postman doesn't open a new tab anymore and switches to the existing open tab if you switch to it from the sidebar. There are no further changes planned around this.

**Comment by Bartimeus** [comment]
Hi! 
Please allow only one tab!

**Comment by PavelProkhorov** [comment]
I wanna one tab!! 
That is why I started to use Insonmia instead.

**Comment by bskiefer** [comment]
Yep, Paw has this down. Not sure why they don't act on user input...

**Comment by pdcarroll** [comment]
First, tabs in the Postman UI do not add value to the user experience. There is already a way to navigate your requests: the sidebar menu. Having an inferior UI abstraction to access requests (i.e., the tabs) is not needed.

Second, in addition to not adding any obvious value, the existence of tabs actually adds friction to the user experience. It clutters the UI and creates additional work for users, who are forced to continually close all of the tabs that they never wanted open to begin with.

I'll concede there may be users who actually find some value in the tab UI; however, like other commenters, I believe this "feature" should be opt-in, or at least support opting-out.

**Comment by ianbale** [comment]
Hmm. I have a lot of items in my collections.

Usually I'm working on a handful at a time. So to be able to open that handful as tabs and have them "in the foreground" is very convenient.

Until today I've not had any problem with tabs. Certainly not multiple tabs opening for the same endpoint. Today though - I guess I got an update - clicking an endpoint default to replacing the current tab, not opening a new one. Now that is annoying! I've not changed any setting, so this is a change of default behaviour. This needs to be a new setting, not simply change everyone's default behaviour.

**Comment by wpccolorblind** [comment]
hi @a85 -- it's 2020 and people still want an option for no tabs...

**Comment by ghost** [comment]
Is there ANY good argument not to implement such a functionnality ?
This issue should not be closed ...

**Comment by arlemi** [comment]
@michelsaumon Here are a few arguments:
- Having both a sidebar (that you can hide) and tabs is common in developer tools (see Eclipse, VSCode for example)
- We've implemented functionalities that help with the current issue (https://github.com/postmanlabs/postman-app-support/issues/2773#issuecomment-334914563, https://github.com/postmanlabs/postman-app-support/issues/2773#issuecomment-471252670)
- As much as we'd like to, we do not have infinite resources and cannot implement every feature users ask for (we currently have [1k+ feature requests](https://github.com/postmanlabs/postman-app-support/issues?q=is%3Aopen+is%3Aissue+label%3Afeature)). 

Hope that helps understanding our point of view!

**Comment by jmoody** [comment]
Since you mentioned VS Code - it has an option to disable tabs.

**Comment by pss-miracle** [comment]
@arlemi a few comments to note:
* Something being common / widespread does not equal to it being good for everyone. Even the history of mankind has a few notable examples of that.
* Implemented fixes are basically equal to symptom treating. The real need here is the ability for people to take control of the way they want to use their working environment. Just in the same way one would like to be influence their own working environment in real life, instead of being told how things should be. 

On a further note I have to say that I am very pleased with Postman as a product. At the same time I find it rather odd that in these days, where user input / feedback become gold in product development, this thread shows that in some cases this does not matter (enough). 

I really hope for the sake of the community that you will reconsider the setting as an option.
Thank you.

**Comment by arlemi** [comment]
@pss-miracle I highly agree with your first point, and that's not what I meant to reflect here. The TL;DR of my post is that we're doing as much as we can to please the community, but we unfortunately cannot implement every feature request we get. 

We appreciate every single piece of feedback we get but could do a better job at explaining how we qualify and act on it ([a la VSCode](https://github.com/microsoft/vscode/wiki/Issues-Triaging), again), that's something I'm working on. 😄

**Comment by laymanmu** [comment]
https://github.com/Kong/insomnia

**Comment by josephbleau** [comment]
> https://github.com/Kong/insomnia

Is it compatible with postman collections?

**Comment by josephbleau** [comment]
This is a much needed feature! Force close tabs is a ridiculous suggestion. Did you even read the original request?

**Comment by ChrisKruegerDev** [comment]
Is there any plan to implement this feature? Otherwise switch to Insomnia for the team would be the better option.

**Comment by vaxxis** [comment]
We are considering a postman subscription for the entire company and after initial evaluations between postman and insomnia the most "hated" behaviour in postman was "the tabs Problem".

Is there any plan to fix these UX issues or maybe a config to disable tabs entirely?

The main problem is that each time you press a request in the sidebar postman will open a new tab. Maybe a "preview" feature like the one available in VSCode would be preferable, open a tab only if changes were made, what do you think?

Thank you.

**Comment by arlemi** [comment]
Hi @vaxxis, the behaviour you're describing should be the current behaviour of the app. See the GIF below, I can single-click requests as much as I want and they'll open in a single tab, if I double-click or edit a request it will open a new tab. 

![newtabs](https://user-images.githubusercontent.com/5029719/101478437-9b3fa480-3948-11eb-8604-63c7dff3e8f8.gif)

Please let me know if you're seeing something different!

**Comment by vaxxis** [comment]
Hi @arlemi,
i'm really happy that the described behaviour was already implemented and i just missed the "Always open requests in new tab" setting :)

Thank you very much!

**Comment by ldiebold** [comment]
It would be nice if we could just "hide" the tabs section entirely.
Postman is an electron app right? Why not just have an option that sets the tabs menu to `display: none;`?

For those that want this functionality, here's what I did:
- **ctrl + shift + i** in postman to open the developer console.
- **ctrl + shift + c** to enable the selector
- select the section where all the tabs are (the one with the class **requester-tabs-wrapper**)
- add the following to element.style: `display: none;`

Unless I've read this thread wrong, I'm pretty sure this is the functionality we're all after? Am I just naive, or is this a relatively straight forward feature to implement?

Pretty sure VS Code uses a similar strategy. They still track all your tabs, but just let you hide them :smile:

**Comment by patrick-hurley** [comment]
Hi  @arlemi  - I see the same behaviour as your gif until I save changes to a request. If I then click on a different request, it opens that new request in a new tab. Is there any way to stop this from happening?

**Comment by arlemi** [comment]
@patrick-hurley Not at the moment, once you start doing some changes in a tab it'll pin it until you close it.

**Comment by alexstanhopesbg** [comment]
I totally understand that the Postman team have limited resource, but I'd like to underscore previous comments that this is not fixed.  By moving between tests and editing them, I end up with an array of tabs (dozens).  Eventually I have some with unsaved changes, some duplicates, some renamed and now in conflict.  It's a mess.  Completely happy to accept it's just me, but from what I read here, it's not.

I'd like an option to disable tabs and just use the Collection list as a 'tab', including the unsaved status.  I appreciate this is non-trivial and I also really appreciate what an amazing job the Postman dev team do.  Thank you.

**Comment by sebastian-fredriksson-bernholtz** [comment]
I've recently come back to Postman because of shared work collections after years of using Insomnia. The main reason for switching to Insomnia was for how easy it is to work with. No tabs, no manual save. Just focus on what you need to do. Like I think Postman used to be when I started using it many years ago when it was still a Chrome app.

I think the scripting/test support is a lot more user friendly than Insomnia, and while there are other things I think Insomnia does better, if it wasn't for the tabs, I would probably make Postman my default client out of convenience. 

But the tabs drive me crazy! I end up with tens of tabs, half edited and unsaved, some conflicting because they've been updated in another tab (how did I do that!). 

Came across this CLOSED issue and thought "YES! I can make Postman bearable". Looking for the solution in thread only to realise there is none. Going to see if I can get all of the work collection set up in Insomnia and move the company over until this is fixed.

**Comment by Hackmodford** [comment]
Came here looking for a way to disable tabs.

**Comment by milovac** [comment]
I found out that Insomnia has minimalistic approach and not tab problems. 
https://insomnia.rest/

**Comment by arlemi** [comment]
On Postman web (go.postman.co), there's a setting to disable tabs: 
![image](https://user-images.githubusercontent.com/5029719/211517131-5171c5b8-6031-4a1e-b276-52bfc4a9f0d3.png)

**Comment by milovac** [comment]
Not available on the desktop version :-(

**Comment by vkaegis** [comment]
@milovac Out of curiosity, is the configuration to remove tabs on the web app behaving as expected? Any behaviors you find odd there? We're currently testing this with a set of users before we look at rolling this out in the desktop app.

**Comment by milovac** [comment]
@vkaegis I did not test the web app; only using desktop.
Another area for improvement (on the desktop app) is the ability to reduce the horizontal screen size. It is beneficial when the app can be narrow; the app (as-is) has specific minimal width. That might include reducing icon sizes on the left vertical toolbar and the ability to reduce the width (more) of the vertical menu on the left. Also, make the input field and Send button more flexible in width.

**Comment by vkaegis** [comment]
@milovac Thanks for the feedback, and yes, we're currently working on removing / reducing the min width so that it can work more seamlessly in smaller form factors. 

It would be really helpful if you could try out the web app with the Remove Tabs configuration turned on, just to understand whether that behavior works for your use case. As always, any feedback is welcome.

**Comment by exec228** [comment]
The most wonderful UX for multiple tabs is that when you try to close one, you often encounter “Unsaved changes conflicting with somewhere else”.

It is just a marvellous play to distract my tired mind from work to realize what that conflict could be back 10–15 minutes ago and which version is actually needed!

Just love Postman's multitab game “Only one will survive. Who will it be?..”
————————————
Especially, I would like to greet the option “Always open requests in new tabs”.

Grand prix goes to that developer!

Because when this option is toggled OFF, Postman “NOT Always open requests in new tabs”. Only randomly, sporadically.

**Comment by exec228** [comment]
Version 10.13.0
Architecture x64
Platform win32 10.0.19045

Please, reopen!

**Comment by eirhardt** [comment]
Just tossing my hat into the fire here. Update on No Tabs option? I find all of Postman's tabs to be increasingly annoying, personally lol

**Comment by whalemare** [comment]
Please, reopen! Allow us to use only single tab

**Comment by MKindy** [comment]
Oh my god, how is this the current state of this request? Talk about delinquency. There are reasons we stopped using Postman where I work, this among them.

**Comment by orlandodiaz** [comment]
Tabs are one of the reasons postman is considered bloat. This is not a web browser. Tabs make the client slower and for most people, they're unnecessary because everything is organized on the left pane anyways
