### ISSUE TITLE
Shared team collections URL

### ISSUE THREAD

**Issue by sinaa2000** [a85/POSTMan-Chrome-Extension#2774]
Hi,

I've been using Postman for a while now and just upgraded to Pro to have the team sharing capability.
I very much like it but there's an issue that I haven't been able to find any way around it, I read through the issues here but haven't found my specific issue and a solution for it.
Since we have an app that has access to collection URLs online to run them as they get updated, I just wanted to know if there's a way to find a shared-with-team collection's URL?
I mean like when a team member shares a collection and someone else subscribes to that shared collection, is there a way to find the link directly?
I read through the Postman API Pro's documentation and I know you can find all the collections and their content but there's no option to get the URL.
So I was wondering if there's a way to find it?

I'd appreciate if you could reply.

Thanks!

 1. Postman Version:
 2. App (Chrome app or Mac app):
 3. OS details:
 4. Is the Interceptor on and enabled in the app:
 5. Did you encounter this recently, or has this bug always been there:
 6. Expected behaviour:
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 8. Screenshots (if applicable)

**Comment by sdnts** [comment]
Hi @sinaa2000, each collection has a documentation link associated with it, that can be viewed by anyone who can read the collection (in your case, shared collections with your team). You can share this link with your teammates. If you click on `View Docs` beside the `Share` button, you should be able to share this URL.
Let me know if this isn't very clear or if I misunderstood.

**Comment by a85** [comment]
API documentation here: https://docs.api.getpostman.com
