### ISSUE TITLE
Cannot change headers without deleting them first

### ISSUE THREAD

**Issue by Daszczu** [a85/POSTMan-Chrome-Extension#2775]
Hello,
When I choose Presets in Headers values aren't replaced but appended. 

Version/App Information:
 1. Postman Version: **Postman for Chrome Version 4.10.2**
 2. App (Chrome app or Mac app): **Chrome 56.0.2924.87**
 3. OS details: **win / x86-64**
 4. Is the Interceptor on and enabled in the app: **yes**
 5. Did you encounter this recently, or has this bug always been there: **always**
 6. Expected behaviour: **headers should be replaced**

Steps to reproduce the problem:
Each time I want my headers changed I have to delete them first and then select a Preset.

For example in each preset I have `Content-Type:application/json` saved so when I click a preset it doubles this entry.

**Comment by vegetableman** [comment]
@a85 The current behaviour is to merge preset values with the existing headers. Should selecting a preset, instead, replace the current headers entirely with the preset one?

**Comment by a85** [comment]
We will change the behavior of presets at a later date. Closing this now as we are backlogged heavily.
