### ISSUE TITLE
Cannot change name of saved response

### ISSUE THREAD

**Issue by Daszczu** [a85/POSTMan-Chrome-Extension#2776]
Hello,
I just want to rename my saved responses. That's all.

Version/App Information:
 1. Postman Version: **Postman for Chrome Version 4.10.2**
 2. App (Chrome app or Mac app): **Chrome 56.0.2924.87**
 3. OS details: **win / x86-64**
 4. Is the Interceptor on and enabled in the app: **yes**
 5. Did you encounter this recently, or has this bug always been there: **always**
 6. Expected behaviour: **There should be a way to rename saved responses**

Steps to reproduce the problem:
1. Save some response and provide a name
2. Delete response and save another if you only want to change the name

**Comment by vegetableman** [comment]
@Daszczu Thanks for posting this issue 👍 . The feature is part of the roadmap, will keep you posted ^_^.

**Comment by bhawna2109** [comment]
Hi @Daszczu this is now supported - http://blog.getpostman.com/2017/05/17/mock-responses-in-postman-by-using-examples/
