### ISSUE TITLE
Asynchronous Javascript in tests

### ISSUE THREAD

**Issue by KumG** [a85/POSTMan-Chrome-Extension#2777]
Hello,

I have a request that returns file (CSV) as binary string.

I'm trying to check the content of the file in my tests. The problem is that I use a FileReader that is asynchronous and works with events.

Is there any way to wait for an event before continuing ? Or a workaround ?

The code is working with the Chrome console, but I can't do a test with the result...

Thanks

`
	
	getCsv(myBlob);

	function getCsv (blob) {
			var reader = new FileReader();
			reader.onload = function () {
				console.log(reader.result);
			};
			reader.readAsText(blob);
		}
`

**Comment by sdnts** [comment]
@KumG Async JS isn't supported right now, but we're working on something similar. Will keep you updated here :)

**Comment by abhijitkane** [comment]
@KumG Postman v5.2+ has support for async scripts.
