### ISSUE TITLE
Unable to install Postman from Chrome Web Store

### ISSUE THREAD

**Issue by KINFOO** [a85/POSTMan-Chrome-Extension#2778]
1. Postman Version: __4.10.2__
 2. App: __Chrome App__
    - I try to install from __Chromium 56.0.2924.76__.
 3. OS details: Debian
    - `Linux hendrix 4.9.0-1-amd64 #1 SMP Debian 4.9.6-3 (2017-01-28) x86_64 GNU/Linux`
 4. Is the Interceptor on and enabled in the app: __No__
 5. Did you encounter this recently, or has this bug always been there: __Recently__
 6. Expected behaviour: 
    - Being able to install __Postman Chrome App__
 7. Console logs: Can't activate them as I can't run app...
 8. Screenshot

![6](https://cloud.githubusercontent.com/assets/154818/23504651/c25a669a-ff40-11e6-8bc2-851ecdcee16e.gif)

Screenshot is in French, because:

- I am French
- Chrome does not allow user [to change language](https://support.google.com/chrome/answer/173424?co=GENIE.Platform%3DDesktop&hl=en)

I can traduce everything.

Thanks for the work.
Kevin

**Comment by sdnts** [comment]
Hi Kevin!

Does this machine have permissions to install Chrome extensions? I've seen some companies that disable this. Can you confirm if this is not the case with you?
In any case, you can also try out our [native apps](https://getpostman.com/apps). Google will end support for Chrome apps soon.

**Comment by KINFOO** [comment]
@madebysid I am administrator of my machine.

**Comment by KINFOO** [comment]
Just switched to __native app__.

Thanks
