### ISSUE TITLE
Proxy not working in Linux app

### ISSUE THREAD

**Issue by marlarius** [a85/POSTMan-Chrome-Extension#2779]
The built-in proxy in the Linux app does not work. When you press Connect, nothing happens. No error message, just nothing.

Postman-linux-x64-4.10.2 on Linux Mint 17.3 on Cinnamon, 64-bit

**Comment by sdnts** [comment]
@marlarius This is a known issue, and we released a fix for this with 4.10.3. Can you try updating and confirm?

**Comment by sdnts** [comment]
Closing, as this is being tracked here too: https://github.com/postmanlabs/postman-app-support/issues/2727 :)

**Comment by marlarius** [comment]
Yes, it works!
