### ISSUE TITLE
[Feature] Request: Ability to apply conversions to param values in Key-value edit 

### ISSUE THREAD

**Issue by sandropons** [a85/POSTMan-Chrome-Extension#2781]
Hello!
I'm currently using Postman for Chrome V.4.10.3 on win 10 / x86-64.
Usually I have to enter processed strings in params or headers key-pair values.
I think it would be cool to have some string processing functions to convert string values so i can insert human-readable values and have postman convert it on sending.
In fact, i have to convert values into md5, base64, sha1 and the like before submitting the API request.

Here is an example picture worth thousand words:
![postman-feature-request](https://cloud.githubusercontent.com/assets/2334496/23546547/54337b46-0000-11e7-8b12-0cbebd6a066f.jpg)

What do you think?
Cheers,
Sandro

**Comment by sdnts** [comment]
@sandropons We do have very limited ways of doing similar things (mostly encoding and decoding), but that's also a manual process. This is an interesting idea. Tagging this as a feature request :)

**Comment by a85** [comment]
@sandropons I recommend using Postman scripts for all conversions. This way behavior is managed at one place and there is more predictability during debugging.
