### ISSUE TITLE
Requests on Postman-win64-4.10.2-Setup.exe dosn`t work

### ISSUE THREAD

**Issue by S0im** [a85/POSTMan-Chrome-Extension#2782]
1. Postman Version:Postman-win64-4.10.2-Setup.exe
 2. App (Chrome app or Mac app):
 3. OS details:win10 x64
 4. Is the Interceptor on and enabled in the app:
 5. Did you encounter this recently, or has this bug always been there:
 6. Expected behaviour:
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 8. Screenshots (if applicable)
![image](https://cloud.githubusercontent.com/assets/25290478/23577044/4ed4b0ac-00f0-11e7-8279-f47cc0772751.png)

 when use the Postman-win64-4.10.2-Setup.exe on my computer，It always say 505  HTTP Version not supported。But the requests are just exported from my chrom Potsman app。Why？

**Comment by vegetableman** [comment]
@S0im Thanks for posting this issue 👍 . It could be an url encoding issue on the native app. Could you share the url with domain name and other sensitive bits redacted?. You could also share a screenshot of the `Postman Console` for the request for us to debug. To open up the Console, you could go to `View -> Show Postman Console`.

**Comment by DSMjyp** [comment]
I have the same issue. It just says “505 HTTP Version Not Support” .But my native app is Postman-win32-4.10.3-Setup.exe. Here is the Postman Console. 
![postmanbug](https://cloud.githubusercontent.com/assets/26500207/24070389/761c4532-0bf7-11e7-9a8c-0c06e5e70720.jpg)

**Comment by S0im** [comment]
Sorry，recently I find postmannativeapp  dosn‘t support Simplified Chinese。But in the chrome app，the chrome encode the URI 。So，we can set an environment at the pre-request scripts like this ：“postman.setGlobalVariable("zhongwen", encodeURI("你好"));” ，and use the “{{zhongwen}}” in the request URI。
