### ISSUE TITLE
Cookies tab (under the send button), sometimes showing and sometimes not.

### ISSUE THREAD

**Issue by nadav96** [a85/POSTMan-Chrome-Extension#2783]
1. Postman Version: 4.10.3
 2. App (Chrome app or Mac app): Chrome app
 3. OS details: Windows 10 64 bit
 4. Is the Interceptor on and enabled in the app: true
 5. Did you encounter this recently, or has this bug always been there: recently
 6. Expected behaviour: cookies tab should always be visible, at least when cookies are set.
 8. Screenshots (if applicable)
![postman_cookie_lack](https://cloud.githubusercontent.com/assets/16354621/23579102/b0aa11ca-00ee-11e7-8742-6afecb4c1b01.jpg)

During my use with the app, I've noticed that sometimes (not sure how to reproduce), next to the code tab (under the save button , highlighted area in the screenshot), there is another tab, called cookies, which is a quick and easy way to edit/add/remove cookies of the global session, which is really helpful, but unfortunately, most of the time it's hidden.

Maybe I'm missing something, is there a reason for the tab not showing most of the time?  Is it a new feature you testing selectively? 

Thanks.

**Comment by vegetableman** [comment]
@nadav96 The chrome app doesn't have the cookie manager, only the native app does. I guess you have been switching between the two, too often 😄
