### ISSUE TITLE
Changing environments during a request that writes a variable overwrites environment

### ISSUE THREAD

**Issue by Tapppi** [a85/POSTMan-Chrome-Extension#2784]
Changing an environment from one to another during a request that writes an environment variable in its tests causes the new environment to be overwritten with the one that was in use started the request. Restarting the app, the wrong values have been persisted.

 1. Postman Version: Version 4.10.2 (4.10.2)
 2. App (Chrome app or Mac app): Native mac app
 3. OS details: macOS v10.12.3 (16D32)
 4. Is the Interceptor on and enabled in the app: -

 5. Did you encounter this recently, or has this bug always been there: Wouldn't know, but guess it has been there for a while.

 6. Expected behaviour: The environment variable should be set:
*  globally for setGlobalVariable()
* in the new or old env for setEnvironmentVariable() (don't know which ?!?)

To reproduce:
* Create two environments with some variables that differ between them but have same names
* Create a request that takes a while
* Use postman.setEnvironmentVariable() or postman.setGlobalVariable() in request tests

* Execute request with env 1 used
* Change to env 2
* After the request finishes and the tests run, env 2 has been overwritten with values from env 1

**Comment by sdnts** [comment]
Hey @Tapppi Thanks for reporting this. I was able to reproduce this. We'll get on a fix.

**Comment by sdnts** [comment]
@Tapppi  Can you try updating to 4.10.5 and check if this is still happening to you?

**Comment by Tapppi** [comment]
Seems to be fixed, thank you!
