### ISSUE TITLE
4.10.3: Proxy setting dialog not prompted on clicking interceptor icon on Windows machine

### ISSUE THREAD

**Issue by shubhangi9595** [a85/POSTMan-Chrome-Extension#2785]
1. Postman Version: 4.10.3
 2. App (Chrome app or Mac app): Chrome app on Windows
 3. OS details: Windows 10
 4. Is the Interceptor on and enabled in the app: Yes
 5. Did you encounter this recently, or has this bug always been there: Using this first time
 6. Expected behaviour: clicking interceptor icon should launch proxy setting dialog
![postman](https://cloud.githubusercontent.com/assets/26189743/23581550/e73d9e30-013b-11e7-9672-d83488611bd2.png)

 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 8. Screenshots (if applicable)  attached postman.png

![postman](https://cloud.githubusercontent.com/assets/26189743/23581573/54f7b8ca-013c-11e7-84a1-ce2eb28e7574.png)

**Comment by vegetableman** [comment]
@shubhangi9595 The proxy dialog is only available for the native app. In the chrome app, the icon is   related to interceptor which also allows for capturing requests but to do so, you need to install the postman interceptor. https://www.getpostman.com/docs/capture
