### ISSUE TITLE
Two colons in URL prevents any further requests from completing

### ISSUE THREAD

**Issue by danaugrs** [a85/POSTMan-Chrome-Extension#2787]
1. Postman Version: 4.10.3
 2. App (Chrome app or Mac app): Chrome 56.0.2924.87
 3. OS details: Windows 7 Enterprise
 4. Is the Interceptor on and enabled in the app: Yes
 5. Did you encounter this recently, or has this bug always been there: Noticed it recently.
 6. Expected behaviour: I expect a request to a bad URL (e.g. with two colons) to timeout. I expect that cancelling that bad request should close the connection and not prevent me from issuing any other requests.
7. Console logs: Nothing shows up.

Make a request to any URL containing two colons.
Example: GET www.google.com:80: (note the second colon)

This will prevent further requests to any URL from completing.

It seems like this issue happens whenever 2+ colons are present in the URL.
A chrome restart is required to restore normal functionality.

**Comment by prashantagarwal** [comment]
@danaugrs Can you update to the latest postman app and verify if this issue is still there.
