### ISSUE TITLE
Ability to post-process JSON responses

### ISSUE THREAD

**Issue by mirfilip** [a85/POSTMan-Chrome-Extension#2790]
Dealing with JSON APIs, I often want to post-process the response. Use cases can be: I'm interested only in particular fields, I want to map/filter/reduce the response etc.

There seems to be no way of directly post-processing the response in Postman. Lack of this feature often forces me to go back to CLI to do a good old `curl ... | jq '...'`.

A competitor product [paw](https://paw.cloud/extensions/) has the extension system and one of them is the [jq extension](https://paw.cloud/extensions/jq) which nails this exact use case.

There is also a [node-jq](https://www.npmjs.com/package/node-jq) wrapper for jq. Of course, you still need a `jq` binary in the system, which can be a problem. Nevertheless, this can be fixed by some message that you need it first to use this feature.

**Comment by vegetableman** [comment]
@mirfilip You could map/filter/reduce the response on the test script after parsing it using `JSON.parse(responseBody)`.  The sandbox also supports lodash. To know more about the supported api and libraries, you could checkout: https://www.getpostman.com/docs/sandbox

**Comment by mirfilip** [comment]
@vegetableman I'm aware of that, but that's not really what I asked for.

What you say is the ability to write a test (meaning, it has a boolean output - passed or not) where you can test the response. What you see on the response window cannot be changed with tests. I can map/filter/reduce in tests, but just to do some assertions.

What I wanted is the ability to mess with the response, so that you see these changed in response window. One imagined use case: let's say I call some API that returns a big collection of users, which are in turns big objects. Every user has an address (1 to 1 relation). I would like to see a userId and corresponding address. I'm not interested in other details. The response is huge and it's not viable to collapse fields manually. Normal flow with `curl` + `jq` would be to post-process the response and leave only interesting bits:
```
$ curl -X GET "http://example.org/api/users" -s | jq '.users | .[] | {id: .id, address: .address.full}'
```

I can come up with dozens of similar use cases if needed.

**Comment by a85** [comment]
@shamasis Something to consider for pm.api.

@mirfilip Thanks for the suggestion! We have a bunch of things being worked up for the runtime sandbox. @shamasis can share more thoughts.

**Comment by vastbinderj** [comment]
@a85 @shamasis 

Do you think instead of using postman, we could use newman with jq if we wanted to script tests?

Thoughts?

**Comment by qiangmao** [comment]
+1

**Comment by mtakacs** [comment]
+1

**Comment by jimmartens** [comment]
+1

**Comment by JorisInsign** [comment]
Hi,

I'm interested with this feature too, but in postman gui too.
For example, I have an API that return part of the response "stringified".
Example of response : 
```json
{
    "router": {
        "headers": {
            "cache-control": [
                "must-revalidate, no-cache, private"
            ],
            "date": [
                "Wed, 20 Jun 2018 06:19:05 GMT"
            ],
            "content-type": [
                "application/json"
            ],
            "x-ua-compatible": [
                "IE=edge"
            ],
            "content-language": [
                "fr"
            ],
            "x-content-type-options": [
                "nosniff"
            ],
            "x-frame-options": [
                "SAMEORIGIN"
            ],
            "expires": [
                "Sun, 19 Nov 1978 05:00:00 GMT"
            ],
            "vary": [
                null
            ],
            "content-id": [
                "<router>"
            ],
            "status": [
                200
            ]
        },
        "body": "{\"test\":\"foo\",\"bar\":[\"baz\"]}"
    },
    "collection#uri{0}": {
        "headers": {
            "cache-control": [
                "must-revalidate, no-cache, private"
            ],
            "date": [
                "Wed, 20 Jun 2018 06:19:06 GMT"
            ],
            "content-type": [
                "application/vnd.api+json"
            ],
            "x-ua-compatible": [
                "IE=edge"
            ],
            "content-language": [
                "fr"
            ],
            "x-content-type-options": [
                "nosniff"
            ],
            "x-frame-options": [
                "SAMEORIGIN"
            ],
            "expires": [
                "Sun, 19 Nov 1978 05:00:00 GMT"
            ],
            "vary": [
                null
            ],
            "content-id": [
                "<collection#uri{0}>"
            ],
            "status": [
                200
            ]
        },
        "body": "{\"test\":\"foo\",\"bar\":[\"baz\"]}"
    }
}
```
To preview my API, I wanted to be able to see (in the gui ;) beautified !) this response with body entry "parsed".

Thansk for your help,

**Comment by vremennyi** [comment]
+1 for this feature
Insomnia has JSONPath response filtering... but they have no header presets)

**Comment by gaia** [comment]
+1 to filter directly in the GUI

**Comment by thsaravana** [comment]
@mirfilip I recently had the same requirement, to post process the Json response. I ended up writing a test script for this. It turns out that we can write pretty much execute any JS script there. And I wrote the below:

```
var json = pm.response.json();
var noOfRecords = json.records;
console.log(noOfRecords);
```

This spits out the output in the Postman Console. Similarly you can do whatever you want with the JSON response. The amount of JS that you can execute is less, and it would be great if we could include any JS library and run that in the script.

**Comment by gaia** [comment]
That is progress but I don't see why just not leave it to JQ. Put a JQ syntax filter in there. The licensing (MIT) couldn't be easier.

**Comment by lauksas** [comment]
I use a framework which wrappers the response in a comment for "security" and I used to be able to modify the responseBody as below in order to postman show the response beautifully, but in the latest version I can't anymore, does anyone have any tips? seems that I can't modify the `responseBody` variable anymore...

`responseBody = responseBody.replace('/*-secure-','').replace('*/', '');`

**Comment by a85** [comment]
Everyone, you can now use the Visualizer https://www.getpostman.com/api-visualizer to process responses in any way that you want to. Check out templates at explore.postman.com for examples.

**Comment by GuillaumeDesforges** [comment]
Visualizer is cool, support for jq querying would still welcome
