### ISSUE TITLE
Basic Authorization "Update Request" Replaces all environment variable references in URL with values

### ISSUE THREAD

**Issue by Gleeble** [a85/POSTMan-Chrome-Extension#2793]
1. Postman Version:
Version 4.10.3
 2. App (Chrome app or Mac app):
Postman for Mac
 3. OS details:
OS X 16.4.0 / x64
 4. Is the Interceptor on and enabled in the app:
No
 5. Did you encounter this recently, or has this bug always been there:
This happened in a recent update to the application
 6. Expected behaviour:
When you click the "Update Request" button to apply authorization, environment parameters remain as their parameter replacement keys instead of being replaced in the setup as the current environment's values.
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
No logs appear
 8. Screenshots (if applicable)

Create a request using environment variables in the url, such as `http://{{server}}:{{port}}/path/to/api?q={{query}}`

Go to the Authorization sub tab and select "Basic Auth" authentication. Add in username and password information and click "Update Request". The URL has now replaced the variable references with the values that have been set in the current environment.

**Comment by Everis** [comment]
+1 on this. Same happens to me with Linux app.

**Comment by kamalaknn** [comment]
Hey @Gleeble,

Thank you for reporting the issue.
We have taken note of this, and fixed it. It will roll out as part of the next version.

Will update here once the next version is out.

**Comment by Gleeble** [comment]
Thanks!

**Comment by kamalaknn** [comment]
Hey @Gleeble @Everis ,

The latest version 4.10.5 has a fix for this behaviour and is out now. Please update your apps and try it out.

Closing this issue. Feel free to re open if you see this again. Thanks.
