### ISSUE TITLE
Export of GET request keeps POST body content leading to errors during execution

### ISSUE THREAD

**Issue by smijar** [a85/POSTMan-Chrome-Extension#2794]
1.Postman Version: Version 4.10.3
2. Standalone mac app
3. OS: Mac OS X Version: 10.12.3
4. Interceptor is turned off
5. Bug has Always been there
6. Bug:
When you create a new request, say that you marked it as a POST request and used x-www-form-urlencoded and entered some info in the BODY text box.

Now, change the type to GET request instead.  This should make the BODY section blank and the type raw

Instead, on export, the exported JSON file contains the request section as saying that the BODY is x-www-form-urlencoded, and includes the BODY information as part of the GET.

When making a HTTP request to the server, this section is included as part of the request causing the server to reject the request with a "415, unsupported media type".

Expected behavior:
It should be pretty simple to On changing a POST request to a GET, to empty out the BODY section and mark it a raw request, and also make sure that the exported content does not contain this info as well.

Thanks. A great product.

 1. Postman Version:
 2. App (Chrome app or Mac app):
 3. OS details:
 4. Is the Interceptor on and enabled in the app:
 5. Did you encounter this recently, or has this bug always been there:
 6. Expected behaviour:
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 8. Screenshots (if applicable)

**Comment by sdnts** [comment]
@smijar Thanks for reporting this. We're aware of this. We're currently working on allowing bodies for GET requests, so in a future version, you'll be able to see it at least. Closing this in favour of #2729, where this is being tracked.

**Comment by smijar** [comment]
I am not sure if the other issue has any relevance here.  Mine was mainly a pointer for the UI to clear out the body or present an option to clear it out if switching from a POST to a GET request.

The other issue condones this issue by saying that GETs should be allowed to have a BODY.
