### ISSUE TITLE
Postman/Interceptor duplicates cookies under new path

### ISSUE THREAD

**Issue by SuperScript** [a85/POSTMan-Chrome-Extension#2795]
Cookie handling in Postman is broken. It requires Interceptor and will not accept a cookie set manually without enabling interceptor. Once interceptor is enabled, cookies are sent, but then they are duplicated onto a new path.

 1. Postman Version:
Postman 4.10.3
Interceptor  0.2.20

 2. App (Chrome app or Mac app):
Chrome app
Same symptoms occur on Mac app

 3. OS details:
Mac OS 10.10.5 and other versions

 4. Is the Interceptor on and enabled in the app:
Yes and no

 5. Did you encounter this recently, or has this bug always been there:
I'm new to these tools, so unknown

 6. Expected behaviour:
I expect Postman/Interceptor to use cookies as provided and not to creatively modify them by changing the path. Instead, Postman duplicates cookies with a path derived from the request made, rather than using the path given. This is broken behavior.

If Postman let me set a cookie manually and use it, that would satisfy my need. But it suppresses use of cookies unless interceptor is enabled. Once interceptor is enabled, the cookies are used, but duplicated onto the erroneous path (e.g. / -> /api).

 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 8. Screenshots (if applicable)

**Comment by sdnts** [comment]
@SuperScript Chrome does not allow apps to set cookies directly. This is why the Interceptor comes into play, where the request is actually sent from Chrome itself. Even then, the cookie management is handled by Chrome. Unfortunately, this isn't under our control.

Have you tried on of our [native apps](https://getpostman.com/apps)? It has an inbuilt Cookie Manager that should allow you to add and edit cookies, which would fit your use.

Let me know if the native app solves your issue :)
