### ISSUE TITLE
Inaccurate messages on startup

### ISSUE THREAD

**Issue by Y-Less** [a85/POSTMan-Chrome-Extension#2798]
1. Postman Version: 4.10.2
 2. App (Chrome app or Mac app): Windows
 3. OS details: Windows 7
 4. Is the Interceptor on and enabled in the app: I didn't enable it, so it is whatever the default is.
 5. Did you encounter this recently, or has this bug always been there: Always there.
 6. Expected behaviour: Accuracy
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 8. Screenshots (if applicable)

Start the program.  It displays messages like "launching escape pods".  There are no escape pods on my computer, nor is anything launched.  I don't have a complete list of all of these pointless messages but I've never seen one I believe to be correct; the program startup should either provide accurate information on what it is doing or nothing at all.  At best this is just stupid, at worst, false advertising.  At least have an option to disable trivialities like that.

**Comment by vegetableman** [comment]
@Y-Less How you can be so sure that there are no escape pods? 😁

**Comment by Y-Less** [comment]
Because I built my own machine.

**Comment by NigelGay** [comment]
I searched for a setting to turn this off too, and found your ticket with no resolution, so came up with this solution:
1) Find where Postman gets installed to - C:\Users\<name>\AppData\Local\Postman, under here you'll see a folder app-n.n.n\resources and a file in there named app.asar.
2) You need a way to edit .asar archives, the best I found was a plugin for 7-zip here - http://www.tc4shell.com/en/7zip/asar
3) Using this, open up the app.asar archive, see the html folder and extract out the files console.html, requester.html and runner.html
4) Edit these as you desire, either strip out the li tags completely or replace them with something sensible like "Please wait"
5) Copy your modified versions back into app.asar

**Comment by igorbljahhin** [comment]
Hi @abhijitkane !

I remember there were some funny messages on Postman's startup and they are gone after some version. Where I could find them? I tried to find them in the file mentioned in comment above, but there are not there anymore.
