### ISSUE TITLE
Disable pop-up about automatic updates

### ISSUE THREAD

**Issue by Y-Less** [a85/POSTMan-Chrome-Extension#2799]
1. Postman Version: 4.10.2
 2. App (Chrome app or Mac app): Windows
 3. OS details: Windows 7
 4. Is the Interceptor on and enabled in the app: Don't know
 5. Did you encounter this recently, or has this bug always been there: Always been there - even after I first downloaded and installed the tool, the first thing it wanted me to do was update it, why was the version I downloaded fromthe website not the latest?
 6. Expected behaviour: Have a "never" option on updates.
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 8. Screenshots (if applicable)

Every time I start the program it comes up with an update dialog with only two options - "Update" and "Remind me later", no "Never" option.  I have come to the conclusion, after many years of getting burned, that automatic updates are the worst way to do updates, especially when so few people have any regard for backwards compatability.  To come to a program you have used many times before, only to find that it has randomly changed itself and broken your workflow, is totally unacceptable.  Granted, I've not used this one long enough to have developed that familiarity yet, and maybe I'm being unfair and in actual fact Postman has never had a single breaking change ever (if that's the case, I apologise); but I've seen it way too many times in way too many programs to even want to take the risk any more.  there needs to be a "never check for updates" option somewhere.

**Comment by sdnts** [comment]
@Y-Less Understandable. You can disable _automatic_ updates on the native apps by heading over to Settings (wrench icon on the top right > Settings), switching over to the `Updates` tab, and changing automatic updates to `None`, so that you never get automatically updated. There isn't a way currently to not show the popover at all, but I understand your concern and we'll look into this.
CC @a85

**Comment by jonathancrosmer** [comment]
It's even worse on Linux.  Automatic updates are not possible in Linux, so there is no way to avoid the nuisance popup on start.

**Comment by mehanoid** [comment]
Furthermore - the popup is absolutely useless if you have installed Postman from a repository (e.g. from AUR on ArchLinux)

**Comment by anodynos** [comment]
> heading over to Settings (wrench icon on the top right > Settings), switching over to the Updates tab, and changing automatic updates to None, so that you never get automatically updated.

In v5.5.3 the `automatic updates` option is missing :-(

**Comment by sdnts** [comment]
We've received feature requests for a PPA distribution of the app on Ubuntu (#2931). You can follow that for updates.

@anodynos, I think you might be on the Chrome app. Chrome handles updates there. I'd recommend shifting to the native apps since Chrome apps are deprecated.

**Comment by tzusman** [comment]
Please please do something about this.  I am constantly being prompted with an update alert about a bug fix that I'm not running into, or a feature that I don't need.  It would be nice if I could ignore all updates except for major versions (like a couple times a year type of upgrades).

**Comment by anodynos** [comment]
@madebysid I am using the latest (`Postman-linux-x64-6.0.10.tar.gz`) from https://www.getpostman.com/apps - I still can't find `Settings -> Update -> Automatic` updates option :-(

**Comment by prashantagarwal** [comment]
Hey Everyone, from Postman app v6.1.0, there will be no pop up for minor and patch updates. You can read more about it here http://blog.getpostman.com/2018/05/16/postman-6-1-linux-auto-update/

**Comment by Y-Less** [comment]
So have you disabled auto updates?

**Comment by prashantagarwal** [comment]
@Y-Less No, but we have made the user experience more subtle. No more popups, just small indicator that an update is available and ready to install.

**Comment by Y-Less** [comment]
So we can ignore then forever now?

**Comment by ghost** [comment]
This is a seriously annoying distraction. It's not enough to disable the nag screen only for minor updates. There needs to be an option that allows people to turn this off. When the tool gets in the way of the work, it becomes a problem, not a tool.

**Comment by ghost** [comment]
The obvious solution is to create nag issues in this repo until the issue is resolved.

**Comment by ZhaoKunLong** [comment]
- Totally agree with that. we should have a button to close it. or can provide an option like pop every 30 days one time.
