### ISSUE TITLE
Expand the URL bar to far right when the `two-panes` option is enabled

### ISSUE THREAD

**Issue by dannyhajj** [a85/POSTMan-Chrome-Extension#2802]
1. Postman Version: 4.10.3
 2. OS details: Ubuntu 16.10

This is UX change request to the "two-panes" beta feature. At the moment, when we enable the feature, the URL bar is only visible in the left pane, which holds the Request part.

This issue is about expanding the URL bar to far right, as with the current size, you can barely see the content of the URL bar.

The following are a couple of images of how I propose the changes to be. Basically:
 - The Status and Time of the response would move down, to the far right of the body, cookies, headers and tests tabs.
- The URL would expand to fill width of the Postman window.

Current Layout:
![postman-original](https://cloud.githubusercontent.com/assets/530409/23857343/a84c4cc8-0805-11e7-8311-80faa8ce611e.png)

Proposed Layout:
![postman-edited](https://cloud.githubusercontent.com/assets/530409/23857342/a8465264-0805-11e7-8540-acd09389d87e.png)

**Comment by numaanashraf** [comment]
Hi @dannyhajj Thanks for the suggestion. We are looking into this and tracking this at #2716.
