### ISSUE TITLE
Special characters are not encoded URL

### ISSUE THREAD

**Issue by ressabrimirakl** [a85/POSTMan-Chrome-Extension#2805]
1. Postman Version: 4.10.3
 2. App (Chrome app or Mac app): win app
 3. OS details: win / x86-32
 4. Is the Interceptor on and enabled in the app: yes
 5. Did you encounter this recently, or has this bug always been there: just recently after the last release
 6. Expected behaviour: 
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app): 
 8. Screenshots (if applicable)

call an API with the special character "|" in the URL. You will get an error 400 "Bad Request".

**Comment by sdnts** [comment]
@ressabrimirakl I tried sending a request to `httpbin.org/get?a|b=c` and was able to get the correct response. URL encoding was a big issue, but we've since fixed it to follow the WhatWG spec.

Can you also try the Chrome app and let me know if that works properly?

**Comment by RandyMeyer** [comment]
I've run into an issue with URL encoding working differently between the Windows and Mac apps. Both Windows and Mac are running the latest 4.10.7 version of Postman but the Windows one would not accept URIs with a colon ( : ) in them unless it was encoded but the Mac will accept it encoded or a literal colon character. ***Note:*** The space in the URL does not need to be encoded on either system.

e.g.
These both work on the Mac:

- `http://localhost:8090/pentaho/api/repos/:public:Global:Host:Completion Progress.prpt/reportjob`
- `http://localhost:8090/pentaho/api/repos/%3Apublic%3AGlobal%3AHost%3ACompletion Progress.prpt/reportjob`

This is the only one that works on Windows:

- `http://localhost:8090/pentaho/api/repos/%3Apublic%3AGlobal%3AHost%3ACompletion Progress.prpt/reportjob`

**Comment by ressabrimirakl** [comment]
Hi,

Thank you for your feedback.
I am working with Windows and in the previous version, i was able to send requests with the special character "|". I didn't need to encode this character. 
Now i have to send "%7C" instead the pipe.

Do you think that i can use again the previous behavior, witout having to send the encoded characters in the URL?

Best Regards,

**Comment by prashantagarwal** [comment]
@ressabrimirakl Can you please update to the latest version of Postman app and verify if you are still facing this issue.

**Comment by MatthewHartstonge** [comment]
I've just had this issue upgrading to 5.5.0 on Windows 10 x64.

For our RESTful APIs we follow Google API design spec, therefore operations that don't fit in the normal HTTP verbs use `/{resourceID}/:action`

For example, the following now fails again:
```
http://localhost:8080/v1/cats/c6621640-cde3-40c2-9e7e-db5dd89ec6f6/:feed
```

'Code' shows:
```
POST /v4/cats/c6621640-cde3-40c2-9e7e-db5dd89ec6f6/ HTTP/1.1
Host: localhost:8080
...
```

This shows up correctly via 'code' but fails:
```
http://localhost:8080/v1/cats/c6621640-cde3-40c2-9e7e-db5dd89ec6f6/::feed
```

'Code' shows:
```
POST /v4/cats/c6621640-cde3-40c2-9e7e-db5dd89ec6f6/:feed HTTP/1.1
Host: localhost:8080
```

Finally, URL Encoding the colon works:
```
http://localhost:8080/v1/cats/c6621640-cde3-40c2-9e7e-db5dd89ec6f6/%3Afeed
```

'Code' shows:
```
POST /v4/cats/c6621640-cde3-40c2-9e7e-db5dd89ec6f6/%3Afeed HTTP/1.1
Host: localhost:8080
```

**Comment by ddcatgg** [comment]
Issue still exists, when url is `http://.../:export_date.json`, and `:export_date=20220630` , the code snippet generated is correct, but the actual url sent is:

    http://.../:export_date.json

Postman for Windows
Version 9.23.3

**Comment by shubhbhargav** [comment]
This seems to be caused by a change pertaining to this issue: https://github.com/postmanlabs/postman-app-support/issues/8302

I am opening up that issue. You can follow the updates there @ddcatgg.
