### ISSUE TITLE
User defined "Content-Type" header ignored (Windows app)

### ISSUE THREAD

**Issue by Przem83** [a85/POSTMan-Chrome-Extension#2807]
The user set "Content-Type" header is being ignored when using x-www-form-urlencoded Body.

Version/App Information:
 1. Postman Version: 4.10.3
 2. App (Chrome app or Mac app): Windows app
 3. OS details: Windows 10 Pro
 4. Is the Interceptor on and enabled in the app: N/A
 5. Bug encountered after switching from Chrome app to Windows app.
 6. Expected behavior: User should be able to override the default "Content-Type" header whenever necessary  (in my case setting a specific charset is required). This worked correctly in Chrome app but fails in Windows App

Steps to reproduce the problem:
1) set request type to: POST
2) set Body to: x-www-form-urlencoded
3) add following header:     Content-Type:  application/x-www-form-urlencoded; charset=UTF-8

Following the above steps will generate a HTTP request with the default Content-Type header (application/x-www-form-urlencoded) instead the one provided by user.

**Comment by sdnts** [comment]
@Przem83 Do you have two `Content-Type` headers? If you do, can you try disabling the automatic one and trying again?
Also, are you replying on the Code Generator to determine what request will be sent? The code generator as such, does not have anything to do with the actual request. You can open up the Postman Console (Cmd+Alt+C or View > Postman Console) and resend the request to see which header is actually sent.

Let me know what you find

**Comment by Przem83** [comment]
Hi **@madebysid** ,
I've checked with the Postman Console and the Content-Type header is OK. After some try an error I've found out that what I'm experiencing is not a Header issue but rather a problem with importing collections from chrome. It seems that the request I'm using was not imported correctly by the windows app. While everything seems OK when looking at the GUI the x-www-form-urlencoded body is not being send or corrupted (Postman Console shows it as empty). What's interesting is that when I cut the body using "Bulk Edit" and then just past it back everything is working fine again. I can reproduce the issue on other PC's by simply importing the chrome dump file or the collection file to windows app. Please note that when importing the same file to chrome app everything works fine.

**Comment by Przem83** [comment]
OK - I found the root cause. There is a format inconsistency between the collections exported from chrome and the ones exported from windows app. The difference is within the body->urlencoded object. It seems that within the windows app two additional fields where added: "type": "text" and "enabled": "true" and that the windows app is unable to correctly import the x-www-form-urlencoded requests when those two fields are absent in the json file.

**Comment by prashantagarwal** [comment]
Related to #2366
