### ISSUE TITLE
Put duplicated request below the original

### ISSUE THREAD

**Issue by jphiloon** [a85/POSTMan-Chrome-Extension#2808]
Feature request
 1. Postman Version: 4.10.3
 2. App (Chrome app or Mac app): Chrome
 3. OS details: Windows 7
 4. Is the Interceptor on and enabled in the app: n/a
 5. Did you encounter this recently, or has this bug always been there:  This is std behavior when duplicating a request
 6. Expected behaviour: Desired behavior is to have the new duplicate item positioned in the list directly below the original instead of appended to the list.
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 8. Screenshots (if applicable)

**Comment by a85** [comment]
This is fixed in the latest app versions.
