### ISSUE TITLE
Feature request: File + "application/x-www-form-urlencoded"

### ISSUE THREAD

**Issue by hlubovac** [a85/POSTMan-Chrome-Extension#2810]
I think the subject is clear. File selection is present only for body+form-data ("multipart/form-data").

As a work-around, I use a simple HTML file to test what I want.

**Comment by milichev** [comment]
@hlubovac , @a85 ,
Why was it closed?
Any workaround how to post a file as an application/x-www-form-urlencoded entry in Postman?

**Comment by hlubovac** [comment]
I have no clue. I didn't have high hopes to begin with. I'm surprised it took them 2 years to dismiss this.

**Comment by codenirvana** [comment]
@milichev @hlubovac If you want to set file params like form-data but with `application/x-www-form-urlencoded` content-type, there's definitely a workaround:
![Screenshot 2020-07-20 at 8 52 32 AM](https://user-images.githubusercontent.com/4865836/87896868-289c5e00-ca67-11ea-98a4-e7633f428922.png)
