### ISSUE TITLE
Editor does not decorate parameter description text when an underscore is present

### ISSUE THREAD

**Issue by udev** [a85/POSTMan-Chrome-Extension#2812]
1. Postman Version: Version 4.10.3
 2. App (Chrome app or Mac app): Chrome 56.0.2924.87
 3. OS details: OSX Sierra 10.12.3
 4. Is the Interceptor on and enabled in the app: Yes and No
 5. Did you encounter this recently, or has this bug always been there: (I'm a new user)
 6. Expected behaviour: parameter description text should be correctly decorated
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app): ... I'm terrible. Please forgive me...
 8. Screenshots:
![image](http://i.imgur.com/TQTRVu1.png)

To reproduce the issue enter add a parameter with a description containing an underscore like below:

\> some_parameter: \`I'm a description with an underscore_text.\`
\>
\> another_parameter: \`I'm a description without an underscore.\`

**some_parameter** will be properly decorated when the underscore in **underscore_text** is removed.

**Comment by vegetableman** [comment]
@udev Thanks for posting this issue 👍 . Will keep you posted ^_^.

**Comment by soysandeep** [comment]
@udev Thanks for reporting this issue. This is not a bug in Postman app, its an issue in our underlying library and we have raised this issue to them. And we are expecting a fix. We'll keep you posted!

**Comment by pankajk07** [comment]
Fixed as part of v7.24
