### ISSUE TITLE
[Feature Request] HTML export of Collection Runner results

### ISSUE THREAD

**Issue by Vijayabaskar03** [a85/POSTMan-Chrome-Extension#2814]
An option to export results from Runner in HTML format (similar to Newman's, may be) rather than just the JSON that can only be viewed in a Runner.

**Comment by sdnts** [comment]
@a85 Maybe we could use Newman's reporters here?

**Comment by kunagpal** [comment]
@madebysid That would require offloading newman reporters into distinct modules first.

**Comment by a85** [comment]
I'd recommend writing a custom converter to use Postman's JSON exports or using newman. We don't have any plans for adding HTML generation from the Collection Runner.
