### ISSUE TITLE
the return message in builder display in Chinese but in Unicode when run in collection runner.

### ISSUE THREAD

**Issue by pierre0505** [a85/POSTMan-Chrome-Extension#2815]
1. Postman Version: Postman v4.10.3 
 2. App (Chrome app or Mac app): Native app
 3. OS details: Windows 10 home edtion(x64)
 4. Is the Interceptor on and enabled in the app: NA
 5. Did you encounter this recently, or has this bug always been there: always
 6. Expected behaviour: should return in chinese character
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 8. Screenshots (if applicable)
![postman-unicode](https://cloud.githubusercontent.com/assets/8911932/23992317/63e0dd32-0a77-11e7-8f69-88421df5dd38.jpg)

**Comment by sivcan** [comment]
@pierre0505 The latest version of the postman i.e. v6.1.4 does not have this issue anymore.

I tried the following:
![image](https://user-images.githubusercontent.com/12631777/42093550-6127a15a-7bca-11e8-92d5-891456d502ee.png)

Kindly upgrade to the latest version and let us know if the issue still persists for you.
