### ISSUE TITLE
Using dashes in JSON variable names in tests

### ISSUE THREAD

**Issue by fonix232** [a85/POSTMan-Chrome-Extension#2818]
Version/App Information:

 1. **Postman Version:** 4.10.3
 2. **App:** Chrome
 3. **OS details:** Windows 10 Insider Preview build 15058
 4. **Is the Interceptor on and enabled in the app:** No
 5. **Did you encounter this recently, or has this bug always been there:** Recently, but probably has been there for some time
 6. **Expected behaviour:** PostMan parses the result and allows access to JSON fields with dashes in their name (e.g. `port-is-open`)

Steps to reproduce the problem:

1. Write new test
2. Parse response body as JSON (`var jsonData = JSON.parse(responseBody);`)
3. Have a JSON field with a dash in its name (e.g. `port-is-open`)
4. Try to access that field for a test (`tests["Port open"] = jsonData.arguments.port-is-open;`)

Result is the Tests page throwing the following error:

There was an error evaluating the test script: **is is not defined**

It clearly picked up the content between the two dashes. If I use a name that has a single dash in it, the result is the text after the dash (so e.g. with `port-open` it will say **open is not defined**).

**Comment by prashantagarwal** [comment]
@fonix232 try using
`tests["Port open"] = jsonData.arguments['port-is-open']`.

**Comment by a85** [comment]
This is just invalid javascript.

**Comment by fonix232** [comment]
Tell that to the Transmission RPC API developers, they implemented their
RPC calls like this.

**Comment by vegetableman** [comment]
@fonix232 Did you try out the solution mentioned on https://github.com/postmanlabs/postman-app-support/issues/2818#issuecomment-287257763?

**Comment by fonix232** [comment]
I'll try it in a moment. I only checked email notifications and for some reason @prashantagarwal 's answer wasn't there.

**Comment by fonix232** [comment]
Accessing the property as an array member works. Thanks!

**Comment by bruno-unna** [comment]
@a85 Why do you say it's invalid javascript? This is supposed to be a JSON document, and it is valid according to my validators.

**Comment by sdnts** [comment]
@bruno-unna Test scripts are actually JavaScript, not JSON, so you cannot have variables with a `-`.

The request body is JSON, though.
