### ISSUE TITLE
[Feature Request] Ability for specific folders under a collection to refer the data files

### ISSUE THREAD

**Issue by saiudayakella** [a85/POSTMan-Chrome-Extension#2821]
Currently when we run a collection and set the data file, it is applicable for the entire collection. It would be good if user can chose data files for specific folders under a collection.

Scenario:
 Create a collection for an API  and different folders under this collection . Requests under each folders are grouped such that they cater a specific workflows. So in this case, few workflows may need to be validated with multiple users or diff data. So when I run a collection, I need not refer data files for all the workflows and can read from env variables as well.

**Comment by sdnts** [comment]
@saiudayakella If each folder is supposed to use independent data, isn't it better if you have just one data file with lots of keys and each folder accessing different keys?

For example, Folder 1 uses the first, second and third keys, Folder 2 uses the fourth, fifth and sixth keys etc.?

**Comment by saiudayakella** [comment]
@madebysid  Consider this scenario:
1) Folder 1 contains diff requests and should be validated by single user ( First request as "Authenticate User" and subsequent requests which valdate the workflow)
2) Folder 2 contains diff requests and should be validated by single user ( "Authenticate User" and subsequent requests which valdate the workflow)
3) Folder 3 contains diff requests and should be validated by different users ( 1 user per iteration)

If I crate a data file this way: [ {"Username": "XXXX","Password: "YYYY"}, {"Username": "XXXX","Password: "YYYY"},
: "XXXX","Password: "YYYY"}, {"Username": "XXXX","Password: "YYYY"}]

In this case when I point this data file when running the collection, each folder will be iterated 3 times. This is not expected.  How do I proceed in this regard?

**Comment by sdnts** [comment]
Yep so what I had in mind was something like:

```
[{
    "user1": "X1",
    "pass1": "Y1",
    "user2": "X2",
    "pass2": "Y1",
    "user3": "X3",
    "pass3": "Y1",
}, {
    "user1": "X1",
    "pass1": "Y1",
    "user2": "X2",
    "pass2": "Y1",
    "user3": "X3",
    "pass3": "Y1",
}]
```

Since these three users have different roles (I think), they make logical sense as well, don't you think?

**Comment by saiudayakella** [comment]
@madebysid Does this not iterate my entire collection as each element refers to one iteration? I can set this way if I have to validate all workflows(folders) with multiple users.

Point 3 which I pointed above will definitely be done by different users(roles), but if I specifiy user1, user2, user3 in the data file, I should duplicate the subsequent requests which validate the workflow. i.e. Authenticate user({{user1}} followed by subsequent requests, Authenticate user {{user2}} followed by 
Authenticate user({{user1}} followed by subsequent requests, Authenticate user {{user2}} followed by subsequent requests.

Are we not duplicating the requests here? If we simply specify the way which I said above{{Username}}, we need not duplicate requests. 

From the attached screenshot, you can see workflow1 will be validated by only admin, workflow2 can be done by any valid user( admin, non-admin). In this case, when running the collection, I need not iterate my workflow1 and iterate only workflow2 such that I get 1 user per iteration. Does it make sense?
![image](https://cloud.githubusercontent.com/assets/19469293/24131608/c6c884e8-0e43-11e7-9918-360b7ee57dfb.png)

**Comment by saiudayakella** [comment]
@madebysid Did you get a chance to look into this issue?

**Comment by saiudayakella** [comment]
@madebysid  We have many scenarios falling under this umbrella. If I individually run specific folders under a collection, I do not have any problem but when we run the entire collection(practical case), I do not want all the folders to be iterated and just specific folders. Can you discuss?

**Comment by amruta-kale** [comment]
I have the same issue. Would like to pass different data files for different tests in one collection. Also to be able to pick up specific data rows from the csv for a test. 
Was there any update on this issue?

**Comment by a85** [comment]
Loading multiple data files is not planned for anytime in the future. Postman's Collection Runner does allow you to select specific requests and folders and run them across iterations so you can use that functionality with different data files to get the same outcome. Otherwise we recommend splitting folders into different collections.
