### ISSUE TITLE
Postman hangs indefinitely on start if already debugging web app in Visual Studio

### ISSUE THREAD

**Issue by thnk2wn** [a85/POSTMan-Chrome-Extension#2823]
If I'm already debugging a web app in Visual Studio and then launch Postman, it hangs indefinitely...

 1. Postman Version: 4.10.3
 2. App (Chrome app or Mac app): Chrome app
 3. OS details: Windows 10
 4. Is the Interceptor on and enabled in the app: no
 5. Did you encounter this recently, or has this bug always been there: not sure
 6. Expected behaviour: Postman launches as normal regardless of whether VS debugging is already in process
 7. Console logs: unable to get to
 8. Screenshots (if applicable): none

Steps to reproduce the problem:
Run (start debugging) an ASP.NET Core Web API project from Visual Studio 2017 on Windows 10. Launch Postman. Postman hangs indefinitely on startup - splash screen animation never stops. Stop debugging and close Postman. Relaunch Postman and note it starts fine when Visual Studio isn't debugging.

**Comment by SamvelRaja** [comment]
@thnk2wn Can you notice any log in the console?
You can open the console through the  View -> Show devtools option.

**Comment by thnk2wn** [comment]
@SamvelRaja Are you talking about built-in browser dev tools like Chrome Developer Tools or something built-in to Postman? Either way I don't see any way to see Console output as pre-launch there's nothing to debug and during the launch you're stuck at the splash screen w/no apparent way to see Dev Tools for that loading window.

**Comment by gordingin** [comment]
I am having a non launch issue also. This is what I see.

xml.js:22 Notification System not initialized_show @ xml.js:22
xml.js:22 'FileError is deprecated and will be removed in M54, around October 2016. Please use the 'name' or 'message' attributes of the error rather than 'code'. See https://www.chromestatus.com/features/6687420359639040 for more details.
xml.js:22 Error: INVALID_STATE_ERR

**Comment by sivcan** [comment]
I advise you all to shift to the latest [Native Postman App](https://www.getpostman.com/apps)
The Chrome App is deprecated.
