### ISSUE TITLE
Postman hangs viewing >1MB responses in Pretty mode

### ISSUE THREAD

**Issue by aburkholder** [a85/POSTMan-Chrome-Extension#2825]
1. Postman Version: 4.10.3
 2. App (Chrome app or Mac app): Mac app
 3. OS details: macOS 10.12.3 (Sierra), 2.6 Ghz i7, 8 GB RAM, solid state HD with 140 GB free space
 4. Is the Interceptor on and enabled in the app: ? no idea - what is it?
 5. Did you encounter this recently, or has this bug always been there: first encountered today
 6. Expected behaviour: 
- be able to scroll through JSON responses > 1 MB in Pretty mode without hanging
 7. Console logs: nothing of value prints in the console
 8. Screenshots (if applicable) : n/a

Steps to reproduce the problem:
1. Make a request that returns a JSON payload larger than one megabyte (mine is 1.1 MB)
2. Attempt to scroll through the response in "Pretty" mode
3. After scrolling through a few 10s of KB of the response, Postman hangs. Only option is to Force Quit the app.

It is worth noting that this behavior does not occur with my 1.1 MB response when viewing the response in RAW and PREVIEW modes.

**Comment by Daszczu** [comment]
I've also encountered this behavior. Win 10, latest Postman app.
Pretty is hanging the app and I had to kill the process.

**Comment by jongunter** [comment]
Same here. I had a large JSON file I loaded in PostMan in Windows 8. UI completely locked up..couldn't use it for over a minute.

**Comment by prashantagarwal** [comment]
we are already tracking this issue here [#793](https://github.com/postmanlabs/postman-app-support/issues/793). Closing this as duplicate
