### ISSUE TITLE
Multiple Scrollbars impedes normal use case

### ISSUE THREAD

**Issue by abdulkareemgs** [a85/POSTMan-Chrome-Extension#2826]
1. Postman Version:4.10.3
 2. App:Mac App
 3. OS details:MacOS sierra 10.12.3 (16D32)
 4. Is the Interceptor on and enabled in the app:No
 5. Did you encounter this recently, or has this bug always been there:Always there
 6. Expected behaviour:there should only one scroll bar or no nested scroll bars
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 8. Screenshots 

![postman_screenshot](https://cloud.githubusercontent.com/assets/10112879/24090177/e06777be-0d63-11e7-86dd-4d2621f7c629.png)

Steps to reproduce
select post method
select body tab
select raw
put large text

now we get two scroll bars one for body
one for whole main content

**Comment by SamvelRaja** [comment]
@abdulkareemnalband How about having a two pane layout, which smoothens this workflow much.
view -> Toggle Two-pane view  (Alt+Cmd+V)

**Comment by abdulkareemgs** [comment]
@SamvelRaja sorry i didn't knew about two panes closing this issue
