### ISSUE TITLE
Collection Runner - Is there a way to automatically save run results to a central location?

### ISSUE THREAD

**Issue by dforney14** [a85/POSTMan-Chrome-Extension#2827]
Version/App Information:
 1. Postman Version: 4.10.3
 2. Native Windows App
 
Our organization has adopted Postman to run the majority of our rest service testing and we need the ability to save our run history for internal audit purposes.  Currently we can do this by manually exporting the Run Results for each collection (each time we run that collection), however this is becoming more of a hassle as our number of collections are reaching the hundreds and our number of tests the thousands.  

Is there a feature to automatically keep track of all our run history (date, time, tests, results, etc.) Instead of manually having to export it as a json file?  

Due to the nature of our business we have sensitive data in our tests and we cannot utilize the sync feature you offer.  I also took a look at some of the features of Postman Pro (specifically the Documentation feature) however this doesn't seem like it will fit our needs either.

Have you encountered any organizations that have also requested a feature similar to this, or know how they accomplish this using Postman?

Thanks for any help you can give!

**Comment by dforney14** [comment]
We have found a solution to accomplish what we were looking for.  By utilizing a combination of Newman and HP-UFT we are able to export our newman run reports and copy them to a central location utilizing some C#.  Just wanted to update this with our findings.

**Comment by malvikach** [comment]
Hi @dforney14 👋 

I know you have already shared a workaround on this. However, wanted to inform you that in Postman's version 10, we have also introduced a 'Runs' tab for collections that will contain all your Collection's Runs and useful statistics about them, you can also use this as a dashboard and filter/sort across your runs:

<img width="1002" alt="191515846-9aeb4f33-f002-4943-b0d8-191ae3e0da88" src="https://user-images.githubusercontent.com/89449769/202413263-5be7d815-48ec-4c7e-983d-7604e7bb2e09.png">

We also recently launched Postman CLI using which your test results will be published back to Postman and will also appear in the above dashboard. Read more about it [here](https://blog.postman.com/introducing-the-postman-cli-to-automate-your-api-testing/). 

I am closing the issue. Please feel free to share your thoughts or feedback anyway.

Cheers!
Malvika
