### ISSUE TITLE
Issue with custom Content-Type in Response Header

### ISSUE THREAD

**Issue by naresh7690** [a85/POSTMan-Chrome-Extension#2829]
I have created a REST Web service, from that service i sending an xml structured response as a string with response header Content-Type: application/emergencycalldata.provideinfo+xml

My browsers chrome,IE is unable to display the content. Instead it is downloaded as a file.
but same response with header Content-Type: application/xml works as expected.

Is there any possible solution to display the content in the browser when the content type is application/emergencycalldata.provideinfo+xml ?

**Comment by sdnts** [comment]
@NareshEtoile Are you on the native or the Chrome app? I am unable to reproduce this with the latest version (4.10.5 as of now) by setting up a little Node server that returns this `Content-Type`.

Can you try updating and check if you can still see this?

Feel free to reopen if still happens.
