### ISSUE TITLE
collection runner: inconsistency with variables usage in tests

### ISSUE THREAD

**Issue by skyboyer** [a85/POSTMan-Chrome-Extension#2832]
Data loaded from CSV file in collection runner can be used the same way as ordinary variables: through {{variable_name}} notation.
Except "Pre-request"  and "Tests" sections. There I have to refer data[] variable. 
At least I was unable to find data imported from CSV neither in environment[] nor globals[] variable.

So if I have tests with variables used I should change them each time I use Collection Runner.

Suggestion is to provide additional method "postman.getVariable" that would work just like {{...}} notation does:  search key in data imported from CSV or in current Environment or in global variables.

**Comment by sdnts** [comment]
@shamasis Thoughts?

**Comment by kunagpal** [comment]
@skyboyer This can be done as follows:
```js
pm.variables.get('my_var_name'); // data > environment > globals
```
