### ISSUE TITLE
"Publish gist" feature

### ISSUE THREAD

**Issue by udev** [a85/POSTMan-Chrome-Extension#2834]
I work directly with a modest base of integration partners ranging from active, full-time to development staff to part-time contractors to relatively untrained hobbyists. It would be convenient to have a "publish gist" feature like in [Charles Proxy](https://www.charlesproxy.com/) that would take complete request and response body and header information and publish that information as a gist.

Feature as seen in Charles Proxy:

![Charles' publish gist feature](http://i.imgur.com/5Fg46Ha.png)

The resultant gist:

[https://gist.github.com/udev/c5f48fe2542e48ee60d5013cb751aef1](https://gist.github.com/udev/c5f48fe2542e48ee60d5013cb751aef1)

**Comment by udev** [comment]
https://developer.github.com/v3/gists/#create-a-gist

**Comment by vegetableman** [comment]
@udev Sounds cool 👍 . Tagging this as a feature request.

**Comment by a85** [comment]
I'd recommend using collection links for this. Postman allows you to upload a collection and generate a link that you can share with others.

**Comment by udev** [comment]
@a85  The idea is not for the person developing the scripts to share them. The idea is to help those who are attempting to integrate an API (unsuccessfully) quickly and easily share request and response information without the need to copy and paste information from postman. A context menu item or a button to do the mundane work would be appreciated.

**Comment by kid1412621** [comment]
not responding in linux latest version

**Comment by psi-gh** [comment]
Error in 4.6.1
(already tried to re-enable gist with different auth key)
![Screenshot 2021-04-09 at 17 14 35](https://user-images.githubusercontent.com/1121645/114178356-1052d300-9957-11eb-9035-24944ccf35ea.png)
