### ISSUE TITLE
[Feature Request] On the right-click on a tab offer the posibility to close tabs

### ISSUE THREAD

**Issue by jcatric** [a85/POSTMan-Chrome-Extension#2835]
Hi,

It would be nice to add a feature that when you right-click on a tab, it gives an option to Close Tab, Close Other Tabs & Close All Tabs, Close unmodified

because it's annoying to have to click on each tab to close them when you have more than 10 open.

Thx.
Best Regards.
Jerome.

**Comment by vegetableman** [comment]
@jcatric If you are on the native app, you could right-click on the tab to select the former 3 options.  As for the fourth option, could you provide an example of an app/tool that provides it?.

**Comment by jcatric** [comment]
Ok my mistake i was talking about "postman for chrome"

![postmanchrome](https://cloud.githubusercontent.com/assets/5849848/24297228/5e4ef032-1078-11e7-82d0-c2179828836b.png)

(the fourth option is unnecessary, because postman native allow to close all tabs even if they have been modified)

 i will switch on postman native.
