### ISSUE TITLE
data.variables Undefined in Pre-request Scripts and Tests for Native App only

### ISSUE THREAD

**Issue by myasutake** [a85/POSTMan-Chrome-Extension#2836]
Postman Mac app v4.10.3.
OSX 10.11.6
Not using Interceptor

Postman Chrome app
OSX 10.11.6
Not using Interceptor

Fairly new to this area of Postman, so I'm not sure how far back this issue potentially goes.

When running a Collection, I'd like to reference the data variables collected from a JSON Data File. I am able to fetch these variables with the Chrome app, but not the Mac app (shows undefined).

This code snippet was attempted in both Pre-request Script and Tests:
`console.log('data var test ' + data.dataVar);`

The Chrome console shows
`data var test 12345`.
The Mac console shows
`data var test undefined`.

The Collection itself executes properly.

**Comment by SamvelRaja** [comment]
Hi @MooMan272, the predefined variable `data` is defined and gets values from the data file that you supply when you run your collection via the Runner. Do note that it is defined only in the Runner. You can read up on documentation [here](https://www.getpostman.com/docs/postman/collection_runs/working_with_data_files). Closing this. Please feel free to reopen if i misunderstood :)

**Comment by p00j4** [comment]
https://www.getpostman.com/docs/v6/postman/scripts/postman_sandbox

**Request/response related properties**

Trying to access a GET parameter but it returns `undefined` 

```
request.data["param_key"]
```
Any clues?
