### ISSUE TITLE
Multi-line text field for URL

### ISSUE THREAD

**Issue by alexandruirimiea** [a85/POSTMan-Chrome-Extension#2839]
Currently, the URL can be edited on a single line. This is especially difficult for long URLs, because I need to move the cursor whenever I need to access a hidden part of the URL.

I see there is a Key-Value edit for URL parameters, but I may ask, will a multi-line text field for the URL ever be considered for implementation?

![multilinepostmanaddresseditor](https://cloud.githubusercontent.com/assets/9987767/24279862/25db02a4-1055-11e7-83e7-9737134a01ea.PNG)

**Comment by prashantagarwal** [comment]
Hey. Thanks for pointing it out. We are planning to change this very soon in our upcoming versions.
I will keep you updated about it.

**Comment by a85** [comment]
This is available now in 4.10.5
