### ISSUE TITLE
Keep URL and request name consistent

### ISSUE THREAD

**Issue by alexandruirimiea** [a85/POSTMan-Chrome-Extension#2840]
Is there a possibility to keep the request name the same as the URL for that request?

For example, if I save a new request in a collection with URL `{{address}}/old-method`, it will automatically be saved accordingly, but when I change the URL to `{{address}}/new-method`, the request name will not change, so the request will appear as `{{address}}/old-method` in the collection, this causing confusions next time I want to look in the list for the corresponding request. So if I want to keep them consistent, I have to redundantly update the name as well.

I have searched about this but I couldn't find anything relevant to the described issue.

![inconsistentrequestname](https://cloud.githubusercontent.com/assets/9987767/24280131/081f9250-1057-11e7-890a-17cd6649ac58.PNG)

**Comment by sdnts** [comment]
@alexandruirimiea While I understand your issue, the request name is generally separate from the URL, so having a link between them is probably not a good idea. Usually, you have names like `Get User details`. This makes it easy for collection subscribers to make sense of what a request does. This is also used when the collection's documentation is shared.

When you save a request, you can change the request name in the modal that pops up. It defaults to the request name. Even after a request is saved, renaming it is possible by clicking on the little pencil icon beside the request name (right below the tabs).

Do let me know and feel free to reopen if I misunderstood :)

**Comment by alexandruirimiea** [comment]
> the request name is generally separate from the URL, so having a link between them is probably not a good idea

@madebysid indeed, I am fully aware of what you are saying. What I was trying to say is that it would be nice if there was a checkbox in options like "Keep request name as URL", that the user can check (or uncheck) if he/she wants (or doesn't want) to avoid the redundancy issue that I described above.
