### ISSUE TITLE
Collection Runner - If 1 API got failed(status not equal to 200), runner not running other APIs, any setting so that other APIs got run as well.

### ISSUE THREAD

**Issue by InfobyteTarun** [a85/POSTMan-Chrome-Extension#2841]
1. Postman Version:
 2. App (Chrome app or Mac app):
 3. OS details:
 4. Is the Interceptor on and enabled in the app:
 5. Did you encounter this recently, or has this bug always been there:
 6. Expected behaviour:
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 8. Screenshots (if applicable)

**Comment by abhijitkane** [comment]
@InfobyteTarun Not able to reproduce this. Are you still seeing this with v5.2.0 of the app?
