### ISSUE TITLE
[Feature Request] Add "Never save on close"-option

### ISSUE THREAD

**Issue by d-schmidt** [a85/POSTMan-Chrome-Extension#2842]
I want to get rid of multiple tabs of slightly changed requests without being asked to save each of them one by one.
This could be a check box in the "save?" dialog or a general setting.

In the Chrome App it is, as of now, not, not possible to close all tabs (with or without saving).
Since `4.10.3` the native app supports "close all" but I can't verify if it asks to save.

relates to #2745

**Comment by d-schmidt** [comment]
We got a "close all" in the chrome app now. good enough for me.

**Comment by mortac8** [comment]
How can I close all tabs from the Windows app?  I have 50 tabs open and it asks me to save each one in Postman 5.1.3.

**Comment by d-schmidt** [comment]
I got a [...] button next to the tabs. It has an close all option. There is still a "save?" dialog but you can click a few times on the same spot and everything is gone.

edit: the Windows App has a right click menu on the tabs, I think?

**Comment by vlaminck** [comment]
Can we please still get a "never save" option? 

I typically start from a saved request, alter it, then close it. An example of this is a saved request to fetch all items, then grab an id out of the response and put it in the url to fetch the details for that item. There would be no point saving my "list items" request with an id in it. Likewise I will change from GET to PUT/POST/DELETE which also fundamentally changes my saved request. 

I will also create a new tab and build up a request or series of requests, and then close the tab with no intention of ever saving that tab. I understand wanting a prompt to prevent accidental tab closures, but I, personally, don't want that. 

I basically want to never save anything. If I do want to save something, I explicitly hit the save button or cmd+s.

**Comment by bhawna2109** [comment]
Hey @vlaminck yes, we're looking into this. Tracking this here #3386

**Comment by vlaminck** [comment]
awesome, thanks!

**Comment by d-schmidt** [comment]
As I agree with @vlaminck. It would be nice to have still.
I would reopen this ticket if it weren't for the new #3386. The new one duplicates this.
