### ISSUE TITLE
Header auth template is not done at runtime

### ISSUE THREAD

**Issue by b4nst** [a85/POSTMan-Chrome-Extension#2844]
1. Postman Version: 4.10.3
 2. App (Chrome app or Mac app): Stand alone ubuntu
 3. OS details: Ubuntu 16.04
 4. Is the Interceptor on and enabled in the app: No
 5. Did you encounter this recently, or has this bug always been there: recently but did not try before

When:
Running a collection. 

When I set Basic auth on request header templated with environment variable comming from last requests (setted in a previous GET), the template is not applied at runtime. Actually I think that the header auth is setted at  ```Basic base64("{{login_varName}}:{{password_varName}")```, which obviously respond with a 401.

It would be useful to be able to change the auth value at runtime.

**Comment by numaanashraf** [comment]
Hi @BastienAr, we are having trouble replicating this at our end. I've shared a sample collection which fetches the authorization information from one endpoint and uses this info to generate basic auth for the next call. Do let me know if this collection works fine at your end.

https://www.getpostman.com/collections/bcc701dbde7ae6a8b8e0

**Comment by b4nst** [comment]
Yep, I somehow manage to get my stuff working (your collection works too) just by resetting my environment. The problem seems to occurs when the header was saved with values already setted in the environment. Actually I also have trouble to reproduce the behavior. I will try to replicate it, but you can close this issue since it seems to happen in really specific configuration.

I also noticed that if you save your request with valid credential (e.g. after testing it manually), when you export the collection the header with your credential will be exported (at `#/item/0/request/header/1/value`). Ain't it a security leak ? I mean if you want to put it on git or whatever, you will have to remember to remove this part.

Thanks for your investigation and your time.
