### ISSUE TITLE
postman doing preflight request and CORS header check

### ISSUE THREAD

**Issue by mrghosh** [a85/POSTMan-Chrome-Extension#2845]
I am using postman to debug [qbittorrent API](https://github.com/qbittorrent/qBittorrent/wiki/WebUI-API-Documentation). qbittorrent API doesn't send 'Access-Control-Allow-Origin' header. So, all XHR request made by postman is failing.

Previously, I used ARC(advanced rest client) extension, and It had an option to "disable" XHR. So, It worked fine according to my scenario.

Is there any way postman can be helpful in my case?

1. Postman Version:  Version 4.10.4
 2. App (Chrome app or Mac app): Chrome
 3. OS details: win / x86-64
 4. Is the Interceptor on and enabled in the app: No
 5. Did you encounter this recently, or has this bug always been there: N/A
 6. Expected behaviour: N/A
 7. Console logs:
XMLHttpRequest cannot load http://127.0.0.1:8118/version/api. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'chrome-extension://fhbjgbiflinjbdggehcddcbncdddomop' is therefore not allowed access.
 8. Screenshots (if applicable)

**Comment by numaanashraf** [comment]
@souravndp That's odd. Postman should not be doing a preflight request and CORS header check. Could you let us know your OS and exact Chrome version too? We'll look into this. In the meantime, you could try our native apps (www.getpostman.com/apps) which do not use XHR.

**Comment by mrghosh** [comment]
I didn't think about this before but now I realized chrome allows extension and apps to make XHR.

My OS is Windows 10 64 bit. Chrome Version 56.0.2924.87 (64-bit)

![capture](https://cloud.githubusercontent.com/assets/652191/24366398/a795cca0-1336-11e7-9247-4d4621bd9c84.PNG)

**Comment by numaanashraf** [comment]
Thanks for the screenshot, @souravndp. We are taking a look at this.

**Comment by numaanashraf** [comment]
Hey @souravndp, could you send us a screenshot of the Network tab with the failed request? Something like 
![screen shot 2017-03-27 at 10 53 24 pm](https://cloud.githubusercontent.com/assets/3295568/24369034/4de3e8f4-1340-11e7-9022-11eb0ebe0521.png)

**Comment by mrghosh** [comment]
![image](https://cloud.githubusercontent.com/assets/652191/24373454/11a7a2ae-134f-11e7-800b-8c55de0543f9.png)

![image](https://cloud.githubusercontent.com/assets/652191/24373509/2e9a0f78-134f-11e7-987b-20613189071c.png)

![image](https://cloud.githubusercontent.com/assets/652191/24373535/402b6f98-134f-11e7-90e7-6e3a42f98cce.png)

**Comment by prashantagarwal** [comment]
@souravndp Can you switch to Postman native apps and verify if you are still facing this issue

**Comment by profporridge** [comment]
I switched to the postman app and I am getting the CORS error

**Comment by azoz158-zz** [comment]
Any solution yet?

**Comment by PeterMen** [comment]
Any solution yet?

**Comment by PeterMen** [comment]
![image](https://user-images.githubusercontent.com/18695024/56010045-9a3e1600-5d14-11e9-888b-5ce199504fc4.png)

**Comment by geoidesic** [comment]
Is it possible to switch preflight checks on for postman?

**Comment by tkirankumar786** [comment]
> @souravndp Can you switch to Postman native apps and verify if you are still facing this issue

it working for postman native apps but how
