### ISSUE TITLE
Access token request returns the Postman app itself

### ISSUE THREAD

**Issue by LeightonFerris** [a85/POSTMan-Chrome-Extension#2846]
I'm following the Yelp Fusion API documentation and when trying to get a new access token I'm getting an error from Postman "Error getting access token from client_credentials flow: SyntaxError: Unexpected token < in JSON at position 0". After using Chrome's inspector to examine the request and its response I've found that the response appears to be the HTML for Postman itself (i.e the UI, references to JS files, CSS, etc.)

1. Postman Version: 4.10.4
2. App (Chrome app or Mac app): Chrome
3. OS details: Windows 10
4. Is the Interceptor on and enabled in the app: No
5. Did you encounter this recently, or has this bug always been there: N/A (I'm a new user)
6. Expected behaviour: Return a valid access token

To reproduce this issue:
1. Click "Get New Access Token" after setting the "type" to "OAuth 2.0".
2. Set the "Auth URL" to "https://api.yelp.com/oauth2/token"
3. Enter Client ID and Client Secret for your Yelp app.
4. Set "Grant Type" to "Client Credentials".
5. Click "Request Token"

**Comment by harryi3t** [comment]
@LS-Kai Was trying to register on yelp for so long and it was always showing

> yelp is overworked right now

Then read on a blog post that they check the IP address and throw this error on mismatch 😆 

Anyway, I confirm the bug. Yelp requires the credential in the body and we are sending it in the header.
Also, you are putting the URL in the wrong input box, it must be in the `Access Token URL` and not in the `Auth URL` See https://tools.ietf.org/html/rfc6749#section-4.4.2

> The client makes a request to the token endpoint .....

But don't worry, this was a fault on our part. In Postman 5.3 we will be removing the extra inputs which are not relevant to the selected variant of OAuth-2

Also, I have fixed the bug on the local build and tested the same with yelp API.
We will be adding an option where you can select where should the credentials go (header or body)
You can expect the fix in Postman 5.3 which will be released around 1st week, Oct

**Comment by harryi3t** [comment]
@LS-Kai Postman 5.3.0 is out. It now supports an option for configuring where the client credentials should be sent (in the body or in the header)

I have personally tested it out with Yelp and it works. Could you try it again with the latest version and let me know if this fixes the issue.
