### ISSUE TITLE
Unable to enable the inspect element feature in postman

### ISSUE THREAD

**Issue by swathisham** [a85/POSTMan-Chrome-Extension#2848]
1. Postman Version: Postman for Windows
Version 4.10.3
win32 6.1.7601 / x64
 2. App (Chrome app
 3. OS details:
 4. Is the Interceptor on and enabled in the app: Disabled
 6. Expected behaviour:
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 8. Screenshots (if applicable)

**Comment by numaanashraf** [comment]
@swathisham Please share the steps to replicate this issue.
