### ISSUE TITLE
Cookies are not included in POST requests from Chrome app

### ISSUE THREAD

**Issue by jonrimmer** [a85/POSTMan-Chrome-Extension#2850]
**NOTE: "Use the native app" is not a solution, at the native app does not support HSTS.**

 1. Postman Version: 4.10.4
 2. App (Chrome app or Mac app): Chrome App
 3. OS details: macOS Sierra 10.12.3
 4. Is the Interceptor on and enabled in the app: Yes, and yes.
 5. Did you encounter this recently, or has this bug always been there: Unsure.
 6. Expected behaviour: 

When making a POST from the Chrome app, the cookies should be sent to the server.

 7. Console logs:

```
3requester.html:1 window.localStorage is not available in packaged apps. Use chrome.storage.local instead.
requester.html:1 beforeunload is not available in packaged apps.
requester.html:1 window.localStorage is not available in packaged apps. Use chrome.storage.local instead.
tester_sandbox.html:1 unload is not available in packaged apps.
2tester_sandbox.html:1 window.localStorage is not available in packaged apps. Use chrome.storage.local instead.
```

 8. Screenshots (if applicable)
 9. Chrome version: 57.0.2987.110 (Official Build) (64-bit)

Steps to reproduce the problem:

  1. Use the Chrome app and inspector to record some POST requests with cookies.
  2. Try to run them from within Postman.
  3. The cookies are not included with the request.

**Comment by numaanashraf** [comment]
Hi @jonrimmer, Postman Chrome app relies on your browser to set the cookie correctly while sending requests via the Interceptor. Please verify that the cookie you expect in the subsequent calls have been set correctly in the browser (chrome://settings/cookies). To debug the requests send via the Interceptor, open its DevTools via chrome://inspect/#extensions -> Inspect (Postman Interceptor
chrome-extension://aicmkgpgakddgnaphhhpliifpcfhicfo/background.html) and check the Network tab.

**Comment by jonrimmer** [comment]
Hi @numaanashraf, yes, I can see the cookies in the browser settings.

Debugging the interceptor's background page networking confirms what I reported: the logged GET requests sent via Postman include the expected Cookie header, whereas POST requests sent via Postman do not include any Cookie header.

**Comment by numaanashraf** [comment]
Hi @jonrimmer, could you drop us a mail at help@getpostman.com with the cookie info? we'll take a look at why this cookie is not picked up in the POST request. Please redact the key, value and domain information from the cookie before you send us.

**Comment by anshupitlia** [comment]
why was this issue closed, is it fixed?
