### ISSUE TITLE
Too long decimals cause parse failure

### ISSUE THREAD

**Issue by smileatom** [a85/POSTMan-Chrome-Extension#2852]
1. Postman Version: v4.10.3
 2. App (Chrome app or Mac app):mac app
 3. OS details: latest OSX 
 4. Is the Interceptor on and enabled in the app: no
 5. Did you encounter this recently, or has this bug always been there: recently
 6. Expected behaviour: JSON values with ampersands in strings are returned as data
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 8. Screenshots (if applicable)

Sorry the issue wasnt the ampersand, it was too long lat longs (again)

We've seen this issue before.  

 "lat": 38.05043923206446,
    "lng": -122.5280850661197,

**Comment by smileatom** [comment]
I dont know what parser you are using but parsing these as strings and converting is safer than trying to parse as decimal.

**Comment by abhijitkane** [comment]
@rendion Fixed in the latest version. Feel free to re-open if you're still seeing this.
