### ISSUE TITLE
Hitting "Update Request" on auth tab gets rid of variables in URL

### ISSUE THREAD

**Issue by rbalik** [a85/POSTMan-Chrome-Extension#2854]
1. Postman Version: 4.10.3
 2. App (Chrome app or Mac app): Windows App
 3. OS details: Windows 10 64-bit
 4. Is the Interceptor on and enabled in the app:
 5. Did you encounter this recently, or has this bug always been there: Just switched to the window app today and started seeing it
 6. Expected behaviour: When I set a username and password and click "Update Request" the URL should not change.

1) Use a URL that uses an environment variable.
2) Type username and password in authentication tab
3) Click "Update Request" 
4) Variables in URL get replaced with their values

**Comment by vegetableman** [comment]
@rbalik Thank you for posting this issue 👍 . The issue has been fixed internally and will be part of the upcoming release.

**Comment by kamalaknn** [comment]
Hey @rbalik,

The fix for this issue has been rolled out in our latest release 4.10.5.

Closing this now. Please feel free to re open the issue if you continue to see this.
