### ISSUE TITLE
Issue in obtaining OAuth token due to duplicate credentials being sent from postman

### ISSUE THREAD

**Issue by jaskarangump** [a85/POSTMan-Chrome-Extension#2856]
1. Postman Version: Version 4.10.4
 2. App (Chrome app or Mac app): Chrome
 3. OS details: OS X / x86-64
 4. Is the Interceptor on and enabled in the app: Off
 5. Did you encounter this recently, or has this bug always been there: Recently 
 6. Expected behaviour: As per Oauth spec, the client credentials should be sent either in body or header. However currently, it is being sent in both places.
As per section 5.2 of oauth spec - https://tools.ietf.org/html/rfc6749#section-5.2
 invalid _request should be returned if 
               The request is missing a required parameter, includes an
               unsupported parameter value (other than grant type),
               repeats a parameter, includes multiple credentials,
               **utilizes more than one mechanism for authenticating the
               client**, or is otherwise malformed.

**Comment by vegetableman** [comment]
@jaskarangump The app does not set oAuth details on both the header and body at the same time. I  am guessing, the issue you are seeing is, the app does not remove the existing oAuth details from the body when switching to `Add params to header` and vice-versa ?

**Comment by harryi3t** [comment]
@jaskarangump We are fixing this bug. But for now, I can suggest you a workaround.
 Can you try __un-checking__ the `Request access token locally` <img src= 'https://user-images.githubusercontent.com/5207331/29372418-aa89146a-82c8-11e7-9965-75dbdda990c0.png' height=500px/>

When it's checked the App makes the second request using both authentication methods
When it's unchecked our server is used which only sends the credentials in the body
