### ISSUE TITLE
Swagger Docs missing specification when importing

### ISSUE THREAD

**Issue by khaosdoctor** [a85/POSTMan-Chrome-Extension#2857]
__Description__:

When I import some swagger yaml or json documentation (even swagger's own examples like the petstore), some parameters are not loaded correctly, i.e. The body parameters are fetched with the description of the object and the auth method is aways "No Auth". This might have been referenced on #843 and more specifically on #2617 

Version/App Information:
 1. Postman Version: 4.10.3
 2. App: Windows App
 3. OS details: Windows
 4. Is the Interceptor on and enabled in the app: No
 5. Did you encounter this recently, or has this bug always been there: Recently
 6. Expected behaviour: Show the correct documentation
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app): Nothing in the console
 8. Screenshots (if applicable)

Simple upload:
![](https://i.imgur.com/HKa1UCF.png)

Imported Swagger petstore full example YAML:

![](https://i.imgur.com/B6bB7Qx.png)

Going to a POST or PUT request (any request with body parameters):

![](https://i.imgur.com/B6bB7Qx.png)

Body isn't there, there's the description instead:

![](https://i.imgur.com/XeHNDfl.png)

But if we open the docs we can see the structure:

![](https://i.imgur.com/Jo0nYVk.png)

(Notice that the description is the field that is being fetched)

Also, the authorization method is none:

![](https://i.imgur.com/cov5s3j.png)

Whereas in the docs we have this:

![](https://i.imgur.com/tvriECb.png)

__Steps to reproduce the problem:__

1. Open Postman
2. Click Import
3. Import YAML or JSON
4. Check body params for POST/PUT requests, they're not there
5. Check Auth, it's not there either

**Comment by OliverRC** [comment]
I can confirm that postman is not using the body schema to populate the body tab
![image](https://cloud.githubusercontent.com/assets/1888486/24871740/f391caca-1e1a-11e7-9e59-ef5be4c2482c.png)

http://swagger.io/specification/#parameterObject

**Comment by Damaged-Organic** [comment]
Same thing here. Also, Postman can't import Swagger folder with files containing relative reference (as described [here](https://stackoverflow.com/questions/35552367/splitting-swagger-definition-across-many-files), for example).

**Comment by mattcrwi** [comment]
Same issue here. this is a huge pain for an application with about 100 endpoints.

**Comment by kostyay** [comment]
Same issue as well

**Comment by OliverRC** [comment]
No love for getting this fixed?
I'd say full, and decent support for swagger is a MUST for any rest client nowadays.

**Comment by dperconti** [comment]
Any update on this ticket?

**Comment by OliverRC** [comment]
Guys is there any update? If your code was open source I would happily try and assist fixing this.

**Comment by tomselvi** [comment]
https://insomnia.rest/ is open source and looking for someone to add swagger support if closed Postman team cannot keep up with community requirements

**Comment by jobec** [comment]
Sort of related to #4499

**Comment by ericliang** [comment]
Is there any plan for this issue/feature?  It's so important since we're using auto-generated swagger documents and favor postman for collaboration.

**Comment by makkpsss** [comment]
Getting the body as JSON Object in request body. Tried importing it for Opencart API

**Comment by abhijitkane** [comment]
Everyone - https://github.com/postmanlabs/postman-app-support/issues/2617 has been closed. The latest Postman version (7.2.1+) supports generating the request body from the Swagger 2.0 schema.
