### ISSUE TITLE
Cookies cannot be deleted by domain

### ISSUE THREAD

**Issue by ipshing** [a85/POSTMan-Chrome-Extension#2858]
Version/App Information:
 1. Postman Version: 4.10.3
 2. App (Chrome app or Mac app): Windows 10 App
 3. OS details: Windows 10
 4. Is the Interceptor on and enabled in the app: No
 5. Did you encounter this recently, or has this bug always been there: Found recently
 6. Expected behavior: When clicking on the X to remove all cookies in a domain, the cookies are actually deleted (and not just hidden from view).

Steps to reproduce the problem:
1. Click on manage cookies
2. Click the X in the title bar of a domain that contains at least one cookie.
3. Close the Manage Cookies window.
4. Click Manage Cookies again.

Result: The cookies from the deleted domain are still stored.

**Comment by ipshing** [comment]
Upon further investigation it appears that the "group" X effectively deletes one cookie at a time. They all disappear but when you open the window again, all but one have returned.

**Comment by numaanashraf** [comment]
Hi @ipshing, thanks for reporting this. We are trying to replicate this at our end and will keep you posted.

**Comment by vl4dt** [comment]
I am having a similar issue, I can see the Cookies tab next to Body with a list of all cookies but there are no buttons or any way to delete them, it's just a read only list of all cookies, which is very useful but I'd like to run some test with a fresh environment.

**Comment by SamvelRaja** [comment]
@ipshing You still facing this issue? we are unable to reproduce this from our end.
And
@vl4dt we have the option to delete the cookies for a whole domain as well, which will be visible on the right side when you hover over the domain name.

<img width="819" alt="screen shot 2017-09-06 at 5 37 40 pm" src="https://user-images.githubusercontent.com/5114052/30111180-5b2f73f6-932a-11e7-9f37-5e374c66c88e.png">

**Comment by ipshing** [comment]
I am no longer seeing this in the Windows Postman client.
