### ISSUE TITLE
How to save response of an API request to a CSV file and use that CSV as input for other API calls.

### ISSUE THREAD

**Issue by RatanShreshtha** [a85/POSTMan-Chrome-Extension#2859]
Hi

I have been using Postman for a while and I really love the tool but I am not able to understand how can I save response of an API to a CSV file, and later use the CSV file to fire some other APIs.

**Comment by rajaksanjay** [comment]
Hi Ratan , 
Did you find any solution ? I am also looking for same. I have chain of API request and want to export final result to csv

**Comment by RatanShreshtha** [comment]
Hi Sanjay,

I saved the result in the environment variable in the form of an array of objects.

Something like this:-
[{key1: val1}, {key1: val1}, ........... ]

And then I saved the environment JSON to the location, using command line option --export-environment <path> of Newman.

I hope that this is helpfull.

**Comment by rajaksanjay** [comment]
Thank you . This is helpful

**Comment by millan-QL** [comment]
To save response of an API request to a `CSV` file or a `.txt` file, **newman run** solution:

`newman run your_collection_file.json --export-environment ./output.txt`

_Here is a bit more loaded version of above command_

`newman run your_collection_file.json -e env.json -d input_data.csv --export-environment ./output.txt`

collection file: `your_collection_file.json`
Environment file: `env.json`
Input Data to your collection: `input_data.csv`
and as replied by @RatanShreshtha  the syntax to output your Environment details: 
`--export-environment ./output.txt` (ref: https://github.com/postmanlabs/newman)

**./output.xt** (will create a file named `output.txt` in present `.` directory

**Output looks like:**
```
{
  "_": {
    "postman_variable_scope": "environment",
    "postman_exported_at": "YYYY-MM-DDT06:35:17.259Z",
    "postman_exported_using": "Postman/6.2.1"
  },
  "id": "xxxxxxxx-xxxxx-xxxx-xxxx-xxxxxxxxxxxx",
  "values": [
    {
      "type": "any",
      "value": "Value of your end point/ host url",
      "key": "host"
    },
    {
      "type": "any",
      "value": "8080",
      "key": "port"
    }, 
```

☝️ will output all environment variables set during your run (refer your:  `your_collection_file.json`

_You may have to tweak it a bit or later process output file to see it in a desired shape_

**Comment by sivcan** [comment]
@millan-QL This is a great explanation! 
Also, here's a Postman app solution to write responses to file (file extensions can be changed - project tested with CSV and JSON) and it's very easy to integrate with everyday workflow. 
https://documenter.getpostman.com/view/3407886/RWgp1fB5
