### ISSUE TITLE
Large response bodies crash browser tab

### ISSUE THREAD

**Issue by andrewswan** [a85/POSTMan-Chrome-Extension#286]
I have a REST endpoint (behind the firewall, so the URL is not useful here) that I can query successfully using curl:

```
curl -H "Accept:application/json" http://my/url -o resp.txt

% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                               Dload  Upload   Total   Spent    Left  Speed
100 1657k  100 1657k    0     0   241k      0  0:00:06  0:00:06 --:--:--  376k
```

However hitting the same URL from POSTMan causes the browser tab to crash with an "aw, snap" message. I'm guessing the size of the response (1.6Mb) is the problem. Is there a known issue/limitation for response bodies of this size?

**Comment by andrewtuplin** [comment]
This is still an issue for me. I'm working with large texts files (posting data into the body of POST requests) and postman is constantly crashing.

**Comment by pbassut** [comment]
+1. Looks like this issue still exists. 
Chrome 46.0.2490.80 (64-bit)
Postman 3.1.4
Mac OSX El Capitan

**Comment by noansknv** [comment]
+1 Still an issue
Chrome 46.0.2490.86 (64)
Postman 3.1.6 
OS X 10.11.2 Beta (15C40a)

**Comment by luqmansungkar** [comment]
+1 Still an issue
Chrome 51.0.2704.106 (64-bit)
Postman 4.4.1 
Linux Mint 17.3 Rosa

**Comment by subham27** [comment]
I am fetching data from a view having more than 300 columns and 100 k rows.Although the rest service returns the list.But postman fails to display data.It displays data only if I populate 1000 records.

**Comment by bendem** [comment]
A neat fix would be a global setting to stop postman from trying to display requests larger than X.

**Comment by stianlagstad** [comment]
+1 Still an issue
Chrome 54.0.2840.59 (Official Build) (64-bit)
Postman 4.8.0
Ubuntu 16.10

The app crashes if the response is large and I look at the response with `Pretty` formatting.
