### ISSUE TITLE
Send and Download not saving correctly

### ISSUE THREAD

**Issue by rhildebrand** [a85/POSTMan-Chrome-Extension#2860]
1. Postman Version: 4.10.5
 2. App (Chrome app or Mac app): Windows app
 3. OS details: Windows 10
 4. Is the Interceptor on and enabled in the app: No
 5. Did you encounter this recently, or has this bug always been there: Recent
 6. Expected behaviour: Download valid requested file to client.

1. GET http://blog.getpostman.com/wp-content/uploads/2014/07/logo.png and choose "Send and Download"
2. Save to local machine - response.png
3. The file gets saved, but it is an invalid file. 

It is worth noting that this worked in 4.10.3 and that the regular Send functionality works - you'll see the image displayed in the Response body section.

**Comment by SamvelRaja** [comment]
@rhildebrand  Thanks for bringing this to our notice.  We are confirming the issue on the latest release. Will update the thread on the process.

**Comment by chloeharper** [comment]
I'm having the same issue.

**Comment by bizentass** [comment]
Facing this issue on the Mac app as well.

**Comment by kamalaknn** [comment]
@bizentass This bug has been affecting all our native apps. 

We have a fix ready for this. We will be releasing it as soon as possible.

**Comment by kamalaknn** [comment]
Hello everyone,

We have rolled out the fix for this in the latest version of our app. Could you update your apps to the latest version and let us know if it works?

Feel free to re open the issue if you continue to see this.

**Comment by tojagrut** [comment]
It works!

Cheers.

**Comment by rhildebrand** [comment]
Works for me at v4.10.7

Thanks!

**Comment by chloeharper** [comment]
Works for me too!
Thank you!
