### ISSUE TITLE
Feature Request: Add setting in two-pane view to display address field on full width

### ISSUE THREAD

**Issue by Kanaduchi** [a85/POSTMan-Chrome-Extension#2862]
Currently when I switch to two-pane view address input is displayed only above left pane. When we use a long query, it's very inconvenient.

It will be great to add new option to display address field on full width above both panes.

See screenshot:
![2-pane view](https://cloud.githubusercontent.com/assets/7042994/24492909/55de4254-1546-11e7-9986-dc6734e24eff.png)

**Comment by numaanashraf** [comment]
Hi @Kanaduchi Thanks for the suggestion. We are looking into this and tracking this at #2716.
