### ISSUE TITLE
Not possible to see full URL in collections

### ISSUE THREAD

**Issue by stanac** [a85/POSTMan-Chrome-Extension#2863]
Version/App Information:

 1. Postman Version: 4.10.3
 2. App (Chrome app or Mac app): Postman for Windows
 3. OS details: win32 10.0.10586 / x64
 4. Is the Interceptor on and enabled in the app: makes no difference
 5. Did you encounter this recently, or has this bug always been there: always i believe
 6. Expected behaviour: There is horizontal scroll bar on collections and history for long urls
 8. Screenshot:

![image](https://cloud.githubusercontent.com/assets/8450675/24497415/a78d54a6-153b-11e7-8041-511de4e6b810.png)

Steps to reproduce the problem: 
1. open collection with long urls

expected:
there is a horizontal scrollbar so user can scroll and differentiate long urls that start with same path segments

actual:
no horizontal scrollbar, not possible to see difference in urls without opening request

I understand that horizontal bar might not be according to your UI guidelines, but it makes the collections list unusable in some cases

**Comment by bhawna2109** [comment]
@stanac You can give your requests a name. This will help in identifying requests in the sidebar even if they have a similar URL.
