### ISSUE TITLE
Post Method returns Get Response Newman

### ISSUE THREAD

**Issue by mohamedmubarish-s-19801** [a85/POSTMan-Chrome-Extension#2866]
Hi
I tried running a post method in newman but the response i got is for get method. It works well and good in Postman. Please check and let me as soon as possible

**Comment by mohamedmubarish-s-19801** [comment]
Any Update on this.. Or Am I wrong ?..  I am using newman version 3.5.2.. please update me on the same as this is a show stopper for our progress

**Comment by a85** [comment]
Please post this here: https://github.com/postmanlabs/newman/issues
