### ISSUE TITLE
Unable to copy data from Clipboard

### ISSUE THREAD

**Issue by jangirashok** [a85/POSTMan-Chrome-Extension#2867]
Hi Guys,
It's more like a request for a new feature. I use Postman to a lot of API testing. I love this tool as it's amazingly interactive and helps me understand everything going on from client side. So, in order to do my tests I do Certificate Based/ JWT authorization. For each new request I have to create signatures; which, I hope you understand, makes it really terrible.
If there was a way we could access System Clipboard in Test Sandbox Script. It will make life so easy(at least mine), and I hope it helps others as well. I hope you guys consider this small request.
Thanks!

 1. Postman Version: 4.10.5
 2. App (Chrome app or Mac app): Chrome and Mac(both)

**Comment by vegetableman** [comment]
@jangirashok Although we don't have a dedicated JWT authorization helper, you could also compute the signature on the pre-request script and then set it as an environment variable and pass that variable to the Authorization header. For example,

``` js
var header =  btoa({'alg': 'HS256', 'typ': 'JWT'}),
    payload = btoa(<payload>), //payload to be sent
    signature = CryptoJS.SHA256((header +'.'+ payload), <secret>)

postman.setEnvironmentVariable("signature", signature);
```
Also, how does access to the system clipboard help you in your scenario?

**Comment by jangirashok** [comment]
Okay: so I have like 15 different APIs I test on my environment; and they need certificate based authorization. Each time I have to test an API; I execute a Java program which generates a CMS Sign which then I copy and paste into Authorization header.
To make it a little efficient I added toolkit to my java program and when I execute it; it will automatically copy CMS sign into clipboard. Once copied, I manually paste that signature in Authorization header. Now: I love Test Sandbox Pre-Scripting, I just feel like if we had access to System Clipboard (or may be even more accessibility to system), programming with Postman would be at a whole new level.(at least for me LOL) Thanks for your response though: Really quick :)
