### ISSUE TITLE
Large form-data post causes app to freeze

### ISSUE THREAD

**Issue by payneBrandon** [a85/POSTMan-Chrome-Extension#2869]
1. Postman Version: 4.10.5
 2. App (Chrome app or Mac app): Chrome
 3. OS details: Windows 10
 4. Is the Interceptor on and enabled in the app:
 5. Did you encounter this recently, or has this bug always been there: recently
 6. Expected behaviour:
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 8. Screenshots (if applicable)

**Comment by numaanashraf** [comment]
@payneBrandon Hey, we have made various improvements to request sending in our native apps. Are you facing the same issue with our native apps? https://www.getpostman.com/apps.

**Comment by a85** [comment]
Closing this issue as we need to define "large" better. We are tracking performance metrics internally and will publish a post soon on benchmarks and the efforts we are taking up to improve dealing with large amounts of data.
