### ISSUE TITLE
Cookie values with an equal sign (=) are not parsed correctly

### ISSUE THREAD

**Issue by valeshino** [a85/POSTMan-Chrome-Extension#2870]
1. Postman Version: 4.10.5
 2. App (Chrome app or Mac app): Mac app
 3. OS details: OS X Sierra (10.12.4)
 4. Is the Interceptor on and enabled in the app: n/a
 5. Did you encounter this recently, or has this bug always been there: Only on the newest version, updated today, and encountered the problem immediately
 6. Expected behaviour: Cookies with a value that includes an equal sign (=) should retain their entire value up to the ;
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app): n/a
 8. Screenshots (if applicable)

In the mac app, open the cookies management dialog and create a new cookie using:
`A=B=C; path=/; domain=.example.com;`

On save, it will continue, but if you re-open that newly created cookie it will look like:
`A=B; path=/; domain=.example.com;`

A similar issue occurs when set-cookie headers are sent from the http server, but instead of dropping the =C portion of the value, it just ignores the cookie completely.
`set-cookie: A=B=C; Domain=.example.com; Path=/`

There are a few existing sites / APIs that use this cookie format (like https://www.yahoo.com/) which this update breaks completely.

**Comment by ChrisCTX** [comment]
Same thing happening on the Windows native App with the latest update.

**Comment by valeshino** [comment]
Is there anywhere to get the old version of postman? This is currently blocking me from using the tool at all since I cannot use or provide login cookies for a few sites I'm testing. I couldn't find an archive of old versions anywhere on the site or throughout the github, but I could have just missed it.

**Comment by ChrisCTX** [comment]
@valeshino I'm currently using the chrome extension version with the Interceptor plugin to load up my browser's cookies into it, of course this is limted to domains where I can write my own cookies.

**Comment by marshallalsup** [comment]
Workaround on installed version of Postman, (4.10.7) is to add the cookie as a header. 
Header Key: cookie
Header Value: someKey=someValueIncludingEqualSigns

To do this on the browser plugin version of Postman you need to turn on the intercepter

**Comment by dshefchik** [comment]
I found the culprit. Located in the _cookie module:

```
_parseSingleCookieString: function _parseSingleCookieString(host, cookieString) {
	    //if this was set using the cookie manager, it might have path and domain too
	    var thisCookieParts = _.chain(cookieString).trim().split(';').filter(function (part) {
	      return !_.isEmpty(part);
	    }).value();
	    var len = thisCookieParts.length;
	    var retVal = {};
	    var i = 0;
         
	    var thisCookie = _.chain(thisCookieParts[i]).trim().split('=').value();
	    if (thisCookie.length >= 1) {
	      //Added this to allow cookie values to have '='
	      //Zendesk 1344
	      try {
	        var cName = _.trim(thisCookie[0], '\n '); //this is the part before the first =
	        var cValue = _.trim(thisCookie[1], '\n '); //part after the first =

	        retVal.url = host;
	        retVal.name = cName;
	        retVal.value = cValue;
	      } catch (e) {
	        console.log("Error setting cookie: " + e);
	      }
	    }

	    //process all the other parts
              // ...

	   return retVal;
	  }
```
Judging from this code, it's ignoring everything after the second '='. Even though that comment is saying it's not.

**Comment by MXYMIN** [comment]
Still seeing this issue on Postman (4.11.1).

**Comment by abhijitkane** [comment]
@MXYMIN Fixed in the latest version. Feel free to re-open if you're still seeing this.
