### ISSUE TITLE
the dash letter in url causes problem when used as environment variable

### ISSUE THREAD

**Issue by MehrdadMzfr** [a85/POSTMan-Chrome-Extension#2871]
1. Postman Version:  4.10.5
 2. App:Chrome app 
 3. OS details: Windows 10
 4. Is the Interceptor on and enabled in the app: NO
 5. Did you encounter this recently, or has this bug always been there: just started to use
 6. Expected behaviour:
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 8. Screenshots (if applicable)

I'm trying to use environment variable for urls. I set the environment key url to https://my-address/myresource

then when I try to use, it removes the part that contains the dash and give following error:

{{url}}/doStuff

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>Error</title>
    </head>
    <body>
        <pre>Cannot POST /myresource/doStuff</pre>
    </body>
</html>

can you please explain how to use a variable name that contains a dash letter (-)?
 e.g.  https://my-address/myresource

**Comment by vegetableman** [comment]
@MehrdadMzfr I am not able to reproduce the issue. You could verify the request being sent by checking the network tab on the devtools in the app. To enable devtools, you could refer: https://www.getpostman.com/docs/errors

**Comment by MehrdadMzfr** [comment]
verified the request and it was a mistake on my side. 

thanks for for the follow up and the nice product :)
