### ISSUE TITLE
Can add a column to describe or explain each Key-Value ?

### ISSUE THREAD

**Issue by chuoke** [a85/POSTMan-Chrome-Extension#2873]
In the first, please forgive me for my poor English.   

I developing a lot of APIs in my work, and I test and archive  them in Postman, which is  really convenient. But I usually forget what is mean of some keys. That is terrible for me as some key have multiple meanings.
I always need to check many doc to live it over again.   

So, I hope there is another column to explain the Key for each row.

I wish you can understand this issue and know what I want.  
Thanks !

**Comment by chuoke** [comment]
Yes！every cool ！This feature is finished with an excellent. 
You can close it, @a85 .
Thanks

**Comment by chuoke** [comment]
But I wonder why not one more column in doc, 
I think it is a little unreasonable that the sample value was covered with the description.

**Comment by a85** [comment]
@chuoke You are welcome. We will have more templates for docs soon. For now, the description will be visible next to the value.
