### ISSUE TITLE
Feature request: link Environment to Collections

### ISSUE THREAD

**Issue by poisa** [a85/POSTMan-Chrome-Extension#2876]
As the number of Collections and Environment grows they become unmanageable. I think it would be great that you could only use the Environments that belong to a Collection so if you are using a tab that was saved in a Collection, then you could only use its Environments. This could, of course, be an optional thing to use.

Here's my specific use case. I have a microservice that I usually deploy on different client's Amazon Web Services accounts. The current system makes it VERY easy for me to send a request to the wrong microservice.

If linking Environments and Collections is not something you might want to implement, I can offer you some suggestions:

- Have the ability to assign a particular color to Collections. When you open a tab from a collection, the tab (and even better, the whole screen background) gets painted with that color. This makes it immediately clear where you are at. Other software like SQLYog also implemented background colors to solve this same problem (I take credit for convincing them to do that :1st_place_medal: 😃  ). And it's not like you have to put a color picker or anything but maybe a palette of 10 preset pastel colors. 

![](http://i.imgur.com/5zrhqMk.png)

- Another option would be to be able to launch a whole new window with just a Collection and its assigned Environments. That way you can make sure that THIS window belongs to THIS client, and so forth You can't make a mistake. I know, this one is a little convoluted but may be a good starting point for another idea.

- Maybe you could assign colors to Environment and Collections. Even though they might be independent of each other like they are now, the user could assign them the same background color so it would be easier for users to identify them. You could even Environment colors for other purposes like red for production, yellow for staging, green for development, etc.

Hope these Ideas help...

**Comment by loraxipam** [comment]
Is this different than #2723 ?

**Comment by poisa** [comment]
@loraxipam Yes, this is different though they don't contradict each other.

**Comment by a85** [comment]
Thanks @poisa for the detailed use case. We are working on a feature called "Workspaces" to allow for better management of Collections and Environments. We don't want an explicit linking of environments and collections but workspaces will let you roughly do the same way.

**Comment by cauvery-guda-eb** [comment]
Looking forward for this change.

**Comment by a85** [comment]
Closing this and tracking the thread here #3205
