### ISSUE TITLE
How to send xml and json parameter as request in postman api tool for testing 

### ISSUE THREAD

**Issue by shrutiSS** [a85/POSTMan-Chrome-Extension#2878]
API for Login

Request
http://******/***/login.xml 

Basic Authentication is - Username and Password

Response
JSON format
{"success" = "pass", "username" = " ", "password" = " "}

------------------------------------------------------------

API for Presence

Request
http://********/***/presence.xml
JSON
{
  "presence"{
   { 
     "status" = "available",
      "messege" = "This is my status"
   }
}

Response
JSON Format
{"success" = "pass", "status" ="available"}

**Comment by abhijitkane** [comment]
@shrutiSS You can refer to relevant docs here - https://www.getpostman.com/docs/postman/sending_api_requests/requests

**Comment by vigneshpandians** [comment]
Duplicate of #4591

**Comment by vigneshpandians** [comment]
@ @abhijitkane
