### ISSUE TITLE
Intuit's  API Collection is not working in the Collection-Runner

### ISSUE THREAD

**Issue by praveenv88** [a85/POSTMan-Chrome-Extension#2880]
Hi,

Intuit's QBO collection which uses with OAuth1 tokens is not working in 'Collection Runner'. It works through the Intuit Developer API Explorer

Version/App Information:

 1. Postman Version: Version 4.10.5
 2. App (Chrome app or Mac app): Chrome App 56.0.2924.87
 3. OS details: Windows 10
 4. Is the Interceptor on and enabled in the app:Yes
 5. Did you encounter this recently, or has this bug always been there: We tried the 'collection runner' feature recently and encountered the issue.
 6. Expected behaviour: Collection should work while running it using 'Collection Runner'.
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 8. Screenshots (if applicable)

You can try the collection from here - https://developer.intuit.com/docs/0100_quickbooks_online/0400_tools/0012_postman

its happening for both Sandbox/Production Version.
Please let us know if we are missing something here.

![intuit_postman](https://cloud.githubusercontent.com/assets/26852519/24587163/2325dd32-17cf-11e7-8c81-4777e8c25157.jpg)
![intuit_postman](https://cloud.githubusercontent.com/assets/26852519/24587179/557b4678-17cf-11e7-8f7a-795a75ab520b.jpg)

**Comment by a85** [comment]
We haven't seen any specific bug reports on this. Please get in touch with Intuit's support to resolve this.
