### ISSUE TITLE
Feature Request: Collection-common Tests

### ISSUE THREAD

**Issue by mdaize** [a85/POSTMan-Chrome-Extension#2881]
Hi there,

I am finding that I am performing a lot of test copy/paste between some/most/all of my tests within a collection. This results in a large amount of maintenance required to maintain if something changes between each/all of them.

It would be great if we had the ability to have a set of "common" tests that would run on each test within a collection -- a sort of (collection) global test.

This would add a new depth to API testing including the possible enforcement of certain API specification/standards.

Imagine if we could build out a set of tests for JSONAPI or other API-standard and be able to apply them across an entire collection!

Food for thought. :)

**Comment by SamvelRaja** [comment]
@MatthewDaize Trust us, something similar is already in our list, will update the thread once it is available.

**Comment by mdaize** [comment]
That's great to hear. :)

**Comment by a85** [comment]
Collection level scripts are available in Postman 5.4+!
