### ISSUE TITLE
nested loop in Postman 

### ISSUE THREAD

**Issue by JennyIlinets** [a85/POSTMan-Chrome-Extension#2884]
Need to validate search for only customer names  who have accounts A&B
```
{
  "resourceType":"Client",
 [
   {"Name1",
     "account": [
             {
              "accountCode": "A",
               "accountCode": "B",
            }
                 ],
     {"Name2",
        
      "account": [
        {
          "accountCode": "A",
        },
            
       {"Name3",
        
      "account": [
        {
          "accountCode": "A",
          "accountCode": "B",
          "accountCode": "C",
            }
          
          ]  }
  ```

**Comment by vegetableman** [comment]
@ZheniyaS The JSON shared is invalid. Could you elaborate more on the issue?.

**Comment by JennyIlinets** [comment]
________________________________
Hi ,
Here is Json
{
"resourceType": "Customer",
  "active": true,
  "identifier": [
    {
      "use": "usual",
      "type": {
        "coding": [
          {
            "system": "systemID",
            "version": "v1",
            "code": "TAX",
            "userSelected": true,
            "display": "Tax ID number"
          }
        ]
      },
      "system": "systemID",
      "value": "value1",
      "period": {
        "start": "2015-05-01",
        "end": "2017-10-02"
      }
          }

        ],
  "name": [
    {
      "use": "official",
      "text": "Dr. BEST",
      "family":
        "Dr. BEST"
        }
  ],
  "telecom": [
    {
      "system": "phone",
      "value": "415-666-6666",
      "use": "temp",
      "rank": 1,
      "period": {
        "end": "2017-05-02",
        "start": "2014-05-01"
      }
    }

  ],
  "address": [
    {
      "use": "work",
      "type": "postal",
      "text": "California2",
      "line": [
        "125 XYZ Street1"
      ],
      "city": "San Bruno",
      "state": "CO",
      "postalCode": "60203",
      "district": "district",
      "country": "USA",
      "period": {
        "end": "2014-05-02",
        "start": "2014-05-01"
      }
        }
  ],
  "role": [
    {
      "accountholder": {


      "code": {
        "text": "is primary account holder",
        "coding": [
          {
            "system": "system02",
            "version": "v2",
            "code": "Primary"

          }
        ]
      },
      "account specialty": [
        {
          "text": "",
          "coding": [
            {
              "system": "account specialty ",
              "version": "v1",
              "code": "checkingA"

            }
          ]
        },
        {
          "text": "",
          "coding": [
            {
              "system": "account specialty ",
              "version": "v1",
              "code": "checkingB"

            }
          ]

        },
        {

      "telecom": [
        {
          "system": "email",
          "value": "best@hotmail.com",
          "use": "temp",
          "rank": 1,
          "period": {
            "end": "2014-05-02",
            "start": "2014-05-01"
          }}
        }]




 I have multiple records , so some customers have  two accounts and others just one,
 need to search only for ones that have 2 accounts and I need to do validation with Postman automation, and Iam  struggling with nested loop.
 will appreciate any help

Zheniya

**Comment by abhijitkane** [comment]
@ZheniyaS You can checkout lodash as an easy way to navigate your JSON object - https://lodash.com/. This is supported in the test sandbox as well.
