### ISSUE TITLE
Cookie not displaying

### ISSUE THREAD

**Issue by joshualawson** [a85/POSTMan-Chrome-Extension#2885]
Postman is not displaying cookies with wildcard domain in the Cookies tab, although when I get the Cookie in the test tab and log it to console it exists.

By wildcard domain cookies I mean setting the domain on the cookie to .mydomain.com (which will allow all subdomains of mydomain.com access to the cookie.

## Version/App Information:

 1. Postman Version: 4.10.5
 2. App (Chrome app or Mac app): Mac
 3. OS details: OS X El Capitan Version 10.11.6 (15G1217)
 4. Is the Interceptor on and enabled in the app: No
 5. Did you encounter this recently, or has this bug always been there: Bug was found in recent update
 6. Expected behaviour: 
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app): No errors in log

## Steps to reproduce the problem:

1.  Create a cookie with a wildcard domain e.g. .mydomain.com.au
2. Check cookies tab in response

**Comment by kamalaknn** [comment]
Hi @joshualawson,

Thanks for reporting this issue. This is a bug in the recent release. Sorry, it affected your workflow.

We have a fix ready for this. We will roll the fix as a new release in a few days.

I will update here once the next version is out.

**Comment by kamalaknn** [comment]
Hi @joshualawson 

We have rolled out a fix for this. Please update your app to the latest version.

We are closing this for now. Feel free to reopen if you continue to see this on the latest version.
