### ISSUE TITLE
Multiple environments' composition

### ISSUE THREAD

**Issue by skyboyer** [a85/POSTMan-Chrome-Extension#2889]
Case: there are several independent groups of variables that should be changed at once. Say there could be different servers(development + QA + production - different domains, different ports, different parts of URL), different auth information(admin + client + guest - login + password + some flags to change flow through .setNextRequest()).

Currently: it's possible to pick just single ENV. So for case mentioned above I have to duplicate values(say with creating admin@QA, guest@QA, admin@prod, guest@prod environments). 
It takes some time to update logically equal variables through different environments.  

Proposal: allow multiple selection for ENV dropdown. So for initial case I'd just pick "QA" and "admin" environments.

It may cause ambiguity if several envs(among selected) contain variable(s) with the same name. Maybe it'd be acceptable if user just gets notification on that "Be careful there are several variables with equal names in selected environments. It's impossible to say what value will be used". 
And user could just migrate such variables into separated environments(and pick only one from them).

**Comment by vsethi13** [comment]
+1
In the spring-boot world, it has a similar feature called "profiles". The concept is the same, that you logically group your config variables in different profiles and activate as many of them while running the program.

**Comment by skyboyer** [comment]
actually I've missed existing Feature request on this
https://github.com/postmanlabs/postman-app-support/issues/2621
Sorry for that

**Comment by alexgman** [comment]
from what i understand a collection of environments is related to a specific thing that you are testing, whether it be an API or an application or some RESTful node server.

for example, i have a Repricing API with multiple environemnts: dev, qa, prod. 

but i also have a completely unrelated application, let's say Yo Mama's Pizza Shop, which similarly has dev, qa, prod.

_yet the variables are completed unrelated between those two applications!_

is there a recommended way of structuring your environments/groupings of environments to allow for testing multiple applications ?
