### ISSUE TITLE
[Feature request]: Add 'ignore this update' option to update dialogue

### ISSUE THREAD

**Issue by domarmstrong** [a85/POSTMan-Chrome-Extension#2890]
Please add the option to ignore an update, currently the app is not available in linux package managers and updating is a real chore. Often I do not 'need' the updates and can ignore several. Currently every time I open the app it tells me there is an update, this is annoying and also means I won't notice when there are new updates because I'm used to closing it.

**Comment by numaanashraf** [comment]
Hi @domarmstrong, thanks for the suggestion. We'll take a look at this and try to include it in our roadmap.

**Comment by preethammavin** [comment]
With the current implementation, we do not show the update modal on every app launch but actually ask for restarting the app only when we have an update ready.  With respect to linux, we support auto update as compared to the previous implementation. This should have a better experience for our users.
