### ISSUE TITLE
Bulk replace option for collection import

### ISSUE THREAD

**Issue by kunagpal** [a85/POSTMan-Chrome-Extension#2892]
Originally posted by @annguyen209 in https://github.com/postmanlabs/postman-collection/issues/228.

> When I do import collections from a folder, some collections already exist and a message box displays to ask me Replace or Import as Copy. I have to click so many times repeatedly because it asks for every single collection. It is more helpful when we have an option that says "Do it for all" to apply for all actions.

**Comment by a85** [comment]
Bulk import/export is not a recommended way for collaboration. Closing this for now.
