### ISSUE TITLE
Unable to enter @ in URL text field

### ISSUE THREAD

**Issue by jefcasters** [a85/POSTMan-Chrome-Extension#2894]
1. Postman Version: 4.10.5
 2. App (Chrome app or Mac app): Postman for Chrome/ Postman for windows
 3. OS details: win / x86-32
 4. Is the Interceptor on and enabled in the app: yes
 5. Did you encounter this recently, or has this bug always been there: recently
 6. Expected behaviour: user is able to use special chracters such as "@# in the url
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 8. Screenshots (if applicable)

Steps to reproduce the problem:
1. Open Postman
2. Create new request
3. put focus in URL textfield
4. enter @ sign using Alt Gr + @

Observed behaviour:
1. Text field loses focus
2. @ sign not entered

**Comment by Topener** [comment]
You know, Chrome app is deprecated and chrome will remove them soon too. Use the dekstop application instead

**Comment by jefcasters** [comment]
Behaviour also happens on native client for windows.

**Comment by zlepper** [comment]
This is also happening in the body of custom requests for me.

**Comment by jefcasters** [comment]
Issue also occurs on the windows client.
Other special characters also have the issue
