### ISSUE TITLE
Could not get any response on Windows App

### ISSUE THREAD

**Issue by jessicaalvarezbayer** [a85/POSTMan-Chrome-Extension#2897]
Hi, Im using Postman for Windows app v4.10.5 on Windows 7 on company proxy. I do not use interceptor.
First time I have to send certificates with a request.
Every request ends up with an error Could not get any response.

![1](https://cloud.githubusercontent.com/assets/26798195/24670092/2cd61bba-1943-11e7-94a8-e14cc00fa184.PNG)

Certificates tab:

![2](https://cloud.githubusercontent.com/assets/26798195/24670099/3344f246-1943-11e7-8a2e-c70dbc648a5a.PNG)

DevTools console does show these errors:

![image](https://cloud.githubusercontent.com/assets/26798195/24668870/a560668a-193e-11e7-8b84-e31731280dcc.png)
![image](https://cloud.githubusercontent.com/assets/26798195/24668890/b277d074-193e-11e7-8c0e-cb7b7c382983.png)

Console logs:

![3](https://cloud.githubusercontent.com/assets/26798195/24670107/39d21562-1943-11e7-8b4e-8830f5f7597b.PNG)

**Comment by jessicaalvarezbayer** [comment]
Can anyone help me, please?

**Comment by jessicaalvarezbayer** [comment]
After investigating I found a proxy configuration issue

**Comment by vegetableman** [comment]
@JessiAlvarez Great to know, you resolved the issue ^_^. Could you let us know as to what was the proxy configuration issue?, you were facing, as it might help others who come across the same issue.

**Comment by morvagor** [comment]
@vegetableman I had the same problem after trying desktop Postman for Windows (have Win 10). Chrome app worked fine, but desktop had this problem. I use proxy for connecting to www, which apparently is OK with Chrome. But as target site is in the intranet, I just added exception for this site to Windows proxy configuration and desktop app started to work as well.
