### ISSUE TITLE
OAuth 2 issue on Mac Client

### ISSUE THREAD

**Issue by meswanholm** [a85/POSTMan-Chrome-Extension#2898]
When attempting to use OAuth 2 to retrieve (and use) a token on the Mac OS client (Postman for Mac
Version 4.10.5 OS X 16.4.0 / x64) the retrieval of the token fails with the error "Error getting access token from client_credentials flow. Could not send request". In the console a 403 is generated: Failed to load resource: the server responded with a status of 403 (Forbidden).

The EXACT same OAuth configuration works fine and retrieves the token with the Chrome App (Version 4.10.5 OS X / x86-64 Chrome 57.0.2987.133)

**Comment by harryi3t** [comment]
@meswanholm 
Can you try __un-checking__ the `Request access token locally` and let us know if that works for you?

<img src= 'https://user-images.githubusercontent.com/5207331/29372418-aa89146a-82c8-11e7-9965-75dbdda990c0.png' height=500px/>
