### ISSUE TITLE
Feature Request - Bulk Import / Export Environments

### ISSUE THREAD

**Issue by aroemen** [a85/POSTMan-Chrome-Extension#2899]
I have many environments for various APIs. When something shared across different environments needs to change, it would be nice to download a JSON document of all the environments in order to make those changes. Then once the changes have been made, import the document overriding the existing environments that were in the JSON document.

**Comment by a85** [comment]
@aroemen We are building a refactoring tool right within Postman.

**Comment by aroemen** [comment]
@a85 that sounds great!  Can you elaborate more on what that will all entail?

**Comment by a85** [comment]
Basically a global find/replace with section specific replacements for specific types. Things like "Replace foo with bar in header params across collections, A, B and C". Will post more things as we have the design goals laid out better. :)

**Comment by huseyin-kilic** [comment]
I am also waiting the feature of mass export for selected environments. 
Find & replace will be very useful too.

**Comment by DmytroPuzhay** [comment]
FYI Workaround would be using dump file (Settings -> Data -> Export data -> Download) which saves everything, then doing your changes, then importing it again.

P.S. Before importing it back one has to delete environments first due to bug https://github.com/postmanlabs/postman-app-support/issues/3365

**Comment by vkaegis** [comment]
@aroemen @huseyin-kilic The Find and Replace feature is now available on the native apps. You can refer to this blog post for more information: http://blog.getpostman.com/2018/11/13/find-and-replace-text-code-and-variables-in-postman/

Fine tuning your exports is not really on our immediate roadmap, so if you're satisfied with this solution, I'm gonna close this issue. Feel free to open another if you have more feedback around this.
