### ISSUE TITLE
Overriding User-Agent header

### ISSUE THREAD

**Issue by eelkeh** [a85/POSTMan-Chrome-Extension#290]
Setting the User-Agent header doesn't seem to be overriding Chromes default User-Agent header.
Using Postman  0.8.1 in Chrome 28.0.1500.20 beta.

**Comment by oleynikd** [comment]
What if I'm using standalone MAC version? Can I override `User-Agent`?
Thanks.

**Comment by gianarb** [comment]
It works on MAC version

**Comment by ishwarchandratiwari** [comment]
how can i edit req.headers['user-agent'] 
....i am using postman to test my api..where is want hit my api with modified  req.headers['user-agent']
