### ISSUE TITLE
Postman Blank screen after installing Version 4.10.5

### ISSUE THREAD

**Issue by ghost** [a85/POSTMan-Chrome-Extension#2900]
1. Postman Version: 4.1.0.5
 2. App (Chrome app or Mac app):
 3. OS details:Windows 7 ,32 bit operating system
 4. Is the Interceptor on and enabled in the app:NO
 5. Did you encounter this recently, or has this bug always been there:

**Comment by prashantagarwal** [comment]
Hi @keepfightingnevergiveup, are you using chrome app ? Is so can you let us know the chrome version. It will help us debug the issue faster.

**Comment by ghost** [comment]
Hi Prashant,

Chrome version is 57.0.2987.133.
But remember , The issue is regarding about the Desktop Postman Client.

Thanks & Regards
Hitesh kumar Sharma

**Comment by prashantagarwal** [comment]
Thanks for sharing this. Would it be possible for you to check devtool's console and check are there any errors there, even better if you could share the screenshot of it.

Thanks.

**Comment by ghost** [comment]
Hi Prashant,

Thanks for the prompt response.
Please find the snapshot below.



[image: Inline image 1]


Thanks & Regards
Hitesh Kumar Sharma

**Comment by prashantagarwal** [comment]
Hey. I think something went wrong. Unable to see the screenshot.

**Comment by ghost** [comment]
Hi Prashant,
I apologize for the delay
Please find the attached snapshot.


Thanks & Regards
Hitesh Kumar Sharma

**Comment by mousehappy** [comment]
@prashantagarwal 
I encounter the problem too， with Windows 7 and Chrome 57-64bit
After reinstall Chrome 57-32bit, the problem of blank tab is solved.

**Comment by prashantagarwal** [comment]
@mousehappy @keepfightingnevergiveup We released 4.10.7 with the fix. Can you please verify if this issue is fixed for you guys.

**Comment by terrywolf** [comment]
@prashantagarwal - I encountered the same problem and it still occurs on 4.10.7.

**Comment by prashantagarwal** [comment]
@terrywolf We are closing this issue. If you are still facing this issue please right to help@getpostman.com
