### ISSUE TITLE
INTERFACE Shortcuts doesn't work

### ISSUE THREAD

**Issue by smonbi** [a85/POSTMan-Chrome-Extension#2902]
1. Postman Version: Version 4.10.5
 2. App (Chrome app or Mac app): Postman for Windows
 3. OS details: win32 10.0.15063 / x64
 4. Is the Interceptor on and enabled in the app:
 5. Did you encounter this recently, or has this bug always been there:
 6. Expected behaviour:
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 8. Screenshots (if applicable)

 Zoom In
Ctrl + 0 --> Reset Zoom
Ctrl + Alt + 1 --> Switch To Sidebar
Ctrl + Alt + 2 --> Switch To Builder
does'nt work.

At this time the Ctrl + - --> Zoom Out works fine and I can't reset the zoom to the default size

![image](https://cloud.githubusercontent.com/assets/16024306/24704838/928c665a-1a09-11e7-8f2e-e46ec7a57592.png)
and i can't use the windows version of postman

-->

**Comment by sdnts** [comment]
@smonbi The `Switch To Sidebar`& `Switch To Builder` shortcuts do not have a visible effect on the UI, they just shift focus to the sidebar and builder to allow you to use shortcuts that make sense in that context (such as moving around the sidebar using arrow keys). Are you looking for visual feedback when you use those shortcuts?
If not, could you elaborate a little as to what doesn't work and what you expect?

**Comment by bmcminn** [comment]
These shortcuts do work, however I noticed Postman doesn't listen for certain key events on the numpad.

Numpad events:
- <kbd>ctrl</kbd>+<kbd>-</kbd> to zoom out works
- <kbd>ctrl</kbd>+<kbd>+</kbd> to zoom in doesn't work
- <kbd>ctrl</kbd>+<kbd>0</kbd> to reset zoom doesn't work

Numrow events:
- <kbd>ctrl</kbd>+<kbd>-</kbd> to zoom out works
- <kbd>ctrl</kbd>+<kbd>+</kbd> to zoom in works
- <kbd>ctrl</kbd>+<kbd>0</kbd> to reset zoom works

**Comment by oamm** [comment]
I'm using Postman 5.0.0 on windows 10 pro spanish with a cmstorm keyboard and the shortcuts for change focus to sidebar or builder doesn't work.

**Comment by malammar** [comment]
Does the focus sidebar hotkey not work anymore? I can't seem to find it on mac.

**Comment by juliannojungle** [comment]
<kbd>ctrl</kbd>+<kbd>\\</kbd> (show sidebar) doesn't work anymore as well.
Confirmed bug on #5505.

**Comment by a85** [comment]
Closing as this as Postman has deprecated Chrome apps and there is better support for shortcuts in the native apps.
