### ISSUE TITLE
Postman app not sending request to server

### ISSUE THREAD

**Issue by munir131** [a85/POSTMan-Chrome-Extension#2904]
1. Postman Version: 4.10.5
 2. App (Chrome app or Mac app): Linux App
 3. OS details: linux / x86-64 - Ubuntu 16.04 LTS
 4. Is the Interceptor on and enabled in the app: ON
 5. Did you encounter this recently, or has this bug always been there: recently
 6. Expected behaviour: Will request to server
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app): Nothing in console
 8. Screenshots (if applicable)

NOTE: In chrome tab postman working properly.
![image](https://cloud.githubusercontent.com/assets/6319375/24740626/b6d2c7c8-1abf-11e7-9f2c-467ebc6a8930.png)

**Comment by kamalaknn** [comment]
Hi @munir131 

We are trying to reproduce this. 

Could you open the app in debug mode `NODE_DEBUG=request /PATH_TO_APP/Postman` from terminal and share errors on the terminal if any?

Also could you attach a screenshot of the incomplete request on Postman Console (View -> Show Postman Console) ?

It will help us isolate the issue.

Thanks.

**Comment by munir131** [comment]
There is nothing in console. Also it's working fine if i off interceptor.

**Comment by kamalaknn** [comment]
From the screenshot you've shared I could see that you are using the chrome app. Chrome App with Interceptor seems to be working fine for us.

Could you try sending a request to `https://echo.getpostman.com/get` with the interceptor on, so we can have an idea?

**Comment by munir131** [comment]
When I was going to send request on echo.getpostman I tried to on interceptor but it's shows me
![image](https://cloud.githubusercontent.com/assets/6319375/24746710/c57b0912-1ad7-11e7-9185-45631ea73042.png)
When clicked in install button i found that i had already installed postman interceptor extension on chrome.
![image](https://cloud.githubusercontent.com/assets/6319375/24746653/89e83834-1ad7-11e7-8658-b8d3cf421379.png)
Again when i click on interceptor toogle at that time get same pop up. Now I can't on interceptor.

Sorry for late reply.

**Comment by munir131** [comment]
I reinstalled postman Chrome app and now working fine. Sorry for inconvenience.

**Comment by kamalaknn** [comment]
@munir131 Not a problem. Glad you got it solved.

**Comment by choicevine** [comment]
Excuse me please:
I also have a 404 error
when I started the app abou a week ago, the api's were responding  
But since 3 days It has not been responding 
There is 400 and 404 error 
cannot GET, 
cannot POST
how can I resolve this

**Comment by choicevine** [comment]
![cap8](https://user-images.githubusercontent.com/34416135/61493399-53da0200-a968-11e9-9b7f-7992d933bc9b.PNG)

**Comment by choicevine** [comment]
![cap7](https://user-images.githubusercontent.com/34416135/61493424-6b18ef80-a968-11e9-92be-b76477a6358f.PNG)

**Comment by choicevine** [comment]
![cap9](https://user-images.githubusercontent.com/34416135/61494052-065e9480-a96a-11e9-88f3-99f52c96b2ad.PNG)
