### ISSUE TITLE
issue | same instance through loadbalancer

### ISSUE THREAD

**Issue by mshahat** [a85/POSTMan-Chrome-Extension#2908]
Hi, 

```
Postman - Version 4.10.5 (4.10.5)
Mac app
macOS 10.12.4 (16E195)
```

I've a simple setup. 
* 2 services running on 2 AWS EC2 machines. 
* AWS ELB Classic TCP load balancer load balancing among both instances. 
If i keep on hitting the loadbalancing service, i get response from the same instance for long time ( few minutes ) 
If  I use curl for e.g. 
`curl --insecure --request GET --url https://apix-971872563.eu-west-1.elb.amazonaws.com:9233/ping`

then it works as expected and i can see round robin load balancing, receiving responses from both instances interchangeably as expected.

I can see "send no-cache header" enabled in preferences but with no effect, i tried either way. 
This is the same behaviour I get if i use Chrome browser, in this case i see request header `"Cache-control: max-age=0" `

Thanks,

**Comment by mshahat** [comment]
AWS ELB Classic has a setting for idle timeout set to 60 sec by default. This is what was causing the behaviour. curl ends the process with every request, so probably the behaviour wasn't reproduced with curl. 

closing this one.  Thanks

**Comment by numaanashraf** [comment]
@mshahat Postman sends a `Connection: keep-alive` request header to reuse tcp connections for better performance on subsequent requests. I just noticed that we don't explicitly show this in the Postman Console of our native apps or talk about this on our docs. We'll document these to make debugging connection related behaviors easier.

**Comment by mshahat** [comment]
Thanks @numaanashraf  ... Does it make sense to expose this as a flag as well ? as in can be disabled ? 

Would keep-alive have significance with layer-4 TCP load balancing ? with an idle-timeout similar to this one in AWS ELB Classic 
https://docs.aws.amazon.com/elasticloadbalancing/latest/classic/config-idle-timeout.html?icmpid=docs_elb_console

keep-alive is an application level layer-7 , isn't it ? 

Thanks,
