### ISSUE TITLE
Header Key value is not getting set in an environmental variable

### ISSUE THREAD

**Issue by dipeshoffice** [a85/POSTMan-Chrome-Extension#2909]
Hi All,

I have a requirement of getting the value from the Header request and using it in a variable in POSTMAN.

Ex: when we perform oauth 2.0, we get the Authorization token.
That authorization token we can either use at URL or at Header.
If we are using the Authorization Token at the Header, i want to get that value and automatically set it in the environment variable.

So basically i want in my code:

Auth_token= Postman.GetRequestheader("Authorization')
Postman.setEnvironmentVariable("Authorization",Auth_token).
However, i am not able to figure out how can i get my code 1 corrected.

Please help.

**Comment by tommarkallen** [comment]
You can save the authorization request header like this

auth_token=request.headers.authorization;
postman.setEnvironmentVariable("Authorization",auth_token);
