### ISSUE TITLE
Clone POST body field

### ISSUE THREAD

**Issue by alexandruirimiea** [a85/POSTMan-Chrome-Extension#2910]
It would be nice if there was an option to clone a field from POST body. This is useful for example when we have a long value that we want to modify and have two alternatives of it, enabling one of them at a time, like in the attached picture.
![duplicatefield](https://cloud.githubusercontent.com/assets/9987767/24756848/481ebb44-1ae6-11e7-958c-f0f9af332259.PNG)

**Comment by bhawna2109** [comment]
@alexandruirimiea Hitting CMD+D duplicates a row, have you tried using it for your use case?

**Comment by alexandruirimiea** [comment]
@bhawna2109 now that you said it, I've tried and it works. I expected there was a visual method though.

**Comment by bhawna2109** [comment]
@alexandruirimiea Glad it worked for you. Also, thanks for the suggestion - adding contexual icons to the editor is a part of our roadmap. Will update this thread when we have a build ready. Closing this for now.
