### ISSUE TITLE
Forward slash (/) automatically inserted into {{vars}/} while typing URLs

### ISSUE THREAD

**Issue by IllyaMoskvin** [a85/POSTMan-Chrome-Extension#2914]
1. Postman Version: **4.10.5**
 2. App (Chrome app or Mac app): **Mac app**
 3. OS details: **macOS Sierra (10.12.4)**
 4. Is the Interceptor on and enabled in the app: **No**
 5. Did you encounter this recently, or has this bug always been there: **Recently**
 6. Expected behaviour: **Let me close the variable by typing }} without inserting /**
 7. Console logs: **Nothing relevant, just sync service messages.**

 8. Screenshots:

Here's a GIF of the error. I'm not typing the `/` in `}/}`, it's being inserted automatically.

![GIF of the error](http://i.imgur.com/9msJTSc.gif)

To reproduce, perhaps try typing `{{}}` in between two `//` in the URL, not including the protocol? Not sure. This is the shortest string I've found that triggers it: `http:///foo/` to `http://{{}}/foo/`

**Comment by numaanashraf** [comment]
Hi @IllyaMoskvin, thanks for reporting. We are looking into this.

**Comment by prashantagarwal** [comment]
Hey @IllyaMoskvin this has been fixed in version 4.10.6. Please update your Postman app.

**Comment by IllyaMoskvin** [comment]
Excellent! Thanks for the quick fix! :+1:

**Comment by DerFlash** [comment]
*cry* I took this previous behavior as a feature ;-)
We have a lot of paths containing variables as optional path structure .../{{resourcePath}}/... which previously worked like a charm in resulting in a single slash .../... .
Now it's a ...//... then which failed our requests. 😢 

For sure the new behavior is absolutely ok, but I need to fix all our collections.

Is there any nice way to add the second forward slash depending on the parameter? Or do I need to include the slash into the parameter itself?
