### ISSUE TITLE
Avoid deleting param row on key clear if value is present

### ISSUE THREAD

**Issue by IllyaMoskvin** [a85/POSTMan-Chrome-Extension#2915]
1. Postman Version: **4.10.5**
 2. App (Chrome app or Mac app): **Mac app**
 3. OS details: **macOS Sierra (10.12.4)**
 4. Is the Interceptor on and enabled in the app: **No**
 5. Did you encounter this recently, or has this bug always been there: **Recently**
 6. Expected behaviour: **Do not delete param row if value is present**
 7. Console logs: **Nothing relevant, just sync service messages.**

 8. Screenshots:

When I clear the `Key` from a parameter (e.g. deleting or cutting), that whole parameter is deleted in its entirety, even if it still has a value. I think this is bad for usability: the user risks losing information that would be difficult to replace (e.g. GUID). The only way to restore that value would be to close the request form, but then the user would lose any other unsaved changes. `Undo` does not undo these deletes.

I'd suggest to either (1) include a dedicated delete button and make that the only way to delete the row (perhaps allow `Tab`-ing to that button), or (2) only delete the row if the `Value` is also empty.

Here's a GIF illustrating this problem. IMO, this shouldn't happen:

![GIF of the issue](http://i.imgur.com/ytE6qAB.gif)

**Comment by numaanashraf** [comment]
Hi @IllyaMoskvin, thanks for reporting this. We are working on few improvements to the url params section. We'll include this in those improvements too.

**Comment by sdnts** [comment]
@IllyaMoskvin This should be fixed in the latest version (5.2.0). Can you update and verify?
Let me know if this still exists, and I'll reopen

**Comment by JanneP80** [comment]
I got Postman v6.0.10 and this still occures. :(
