### ISSUE TITLE
Modifying a {{var}} (eg fixing a typo) results in the var being removed completly 

### ISSUE THREAD

**Issue by chrismcneill** [a85/POSTMan-Chrome-Extension#2916]
*Steps to reproduce*
create a variable (either local or global)
type in the variable manually - purposfully (for this reproduction) typo it
attempt to fix the typo
*Expected*: I would expect the typo to be fixable without having to re-key the complete variable
*Actual*: Deleting/changing one letter causes the whole variable to be stripped out and needing re-keyed.

![corrections-remove-param](https://cloud.githubusercontent.com/assets/15048271/24790852/d23c285a-1b6f-11e7-87ab-e36618be33ee.gif)

*Environment Details*
Postman for Chrome
Version 4.10.5
win / x86-32
Chrome 56.0.2924.87
Interceptor enabled
appears to be a new issue after recent updates

**Comment by prashantagarwal** [comment]
Hey @chrismcneill ,
Thanks for reporting this issue. This only happens when you press backspace. We are already tracking this issue here #2895 . We will be fixing this behaviour soon.
I am closing this issue and marking it as duplicate.
