### ISSUE TITLE
Feature Request: Allow Collections Items to Act Like Templates

### ISSUE THREAD

**Issue by ChubbyArse** [a85/POSTMan-Chrome-Extension#2917]
1. Postman Version: 4.10.5 (4.10.5)
 2. App: Mac App
 3. OS details: N/A
 4. Is the Interceptor on and enabled in the app: No
 5. Did you encounter this recently, or has this bug always been there: N/A
 6. Expected behaviour: N/A
 7. Console logs: N/A
 8. Screenshots: N/A

I have a suggestion for the team - the ability to use the stored items in a collection as templates. So rather than opening and editing it, you would click on it and and it would be loaded into a new tab. This could be executed like any other tab - except if you save or close it you are prompted with the save dialog that asks you to enter it’s details.

So my typical usage of POSTMAN is that I have a collection and I would find the item I need to execute, open it, edit it, execute it and close it without saving the changes. Sadly, sometimes I do save and have to re-edit it to set if back!!!

This would also help using the Basic Auth helper - as this substitutes in the parameters in the url when you click “Update Request” - which are forever gone when you save it! This way any item you open is freely editable and disposable. If you needed to edit the template - you would right click on it in the list and select “edit”.

I guess you could either set a property on a collection for all items to act as templates, or you could specify each individually and have an indicator on the item in the list (like a box around the verb or highlight the name in orange).

Happy to chat through more.

**Comment by a85** [comment]
Thanks for the suggestion. We are working separately on the authorization changing the request part.

@bhawna2109 @vkaegis this is similar to the "Ghost tabs" that we were discussing.

**Comment by ChubbyArse** [comment]
Any update on this?

**Comment by vkaegis** [comment]
@ChubbyArse Just curious, have you tried modifying permissions on the collection? If you create a collection and allow only read access to it for your team, when they open it in a tab, it functions EXACTLY the way you mentioned. 

![read only collection](https://user-images.githubusercontent.com/6038010/43200237-83d751e2-9032-11e8-8345-22058ca8038b.gif)
