### ISSUE TITLE
SSL certificate verification doesn't ignore self-signed certificates during getting OAuth2 token when it's off

### ISSUE THREAD

**Issue by zihotki** [a85/POSTMan-Chrome-Extension#2918]
1. Postman Version: v4.10.5
 2. App (Chrome app or Mac app): Windows App
 3. OS details: Windows 10 Pro
 4. Is the Interceptor on and enabled in the app: No
 5. Did you encounter this recently, or has this bug always been there: don't know
 6. Expected behaviour: When 'SSL certificate verification' is off it should ignore all certificate errors
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
"Failed to load resource: net::ERR_INSECURE_RESPONSE" 

 8. Screenshots (if applicable)
![image](https://cloud.githubusercontent.com/assets/114631/24800149/30e37e42-1b9f-11e7-946f-680cd838e488.png)

Steps to reproduce the problem:
1. Setup an OAuth authentication server with self-signed SSL certificate 
2. Pick OAuth 2 authorization 
3. Fill in the details for access token request
4. Click on "Request Token" 
Received error "Error getting access token from client_credentials flow. Could not send request" and in postman dev tools console it shows 'net::ERR_INSECURE_RESPONSE' error.
Expected - it should ignore certificate issues when verification is off.

**Comment by numaanashraf** [comment]
Hi @zihotki, thanks for reporting this. Relaxing SSL verification is not supported for OAuth 2.0 flow at the moment. We will look into including this in our roadmap soon.

**Comment by zihotki** [comment]
As for the workaround, I managed to make it working using Chrome App by navigating first to the access token url, adding the certificate to exclusion list (advanced -> proceed to .. (unsafe)), and then requesting the token. Not ideal but at least works, but the best would be to make the setting work across all features.

**Comment by rubensa** [comment]
You should **document this on docs** as I've spent more than an hour trying to guess If my server was the problem (cause I have _SSL certificate verification_ disabled on _Settings_)

**As a side note**:  There is **no log in Postman Console** (in stand alone version) about the request to the server when _Gran Type_ is _Authorization Code_ and server certificate is auto-signed (so no way to guess the problem with the certificate not been validated).  In the server side I can only see a socket connection closed by the client.

**Comment by zihotki** [comment]
Given that Chrome Apps workaround soon will stop working (Chrome Apps are obsolete, you know), there will be no solution for the problem. And this is essential for testing APIs internally/locally where self-signed certificates are used.

**Comment by rubensa** [comment]
I was talking about @numaanashraf documenting that: 

> Relaxing SSL verification is not supported for OAuth 2.0 flow at the moment.

PS:  I'm using the Native Postman App, not the Chrome App.

**Comment by andutta** [comment]
Hello, did anyone resolve the issue of bypassing security check for self signed certificates when OAuth2 URL is called for getting a token?

**Comment by zihotki** [comment]
No, the issue is still there and it doesn't look that it's going to be addressed soon :( . It's a show stopper for us and for many others.

**Comment by jeyabal-hcl** [comment]
Same issue. I am not able to use standalone postman due to this issue. means its a show stopper. 
Same API test is working like charm in chrome with the said workaround.

**Comment by chr1573r** [comment]
Experiencing the same issue

**Comment by VenkattaPidikiti** [comment]
Experiencing the same issue from 6.7.2 and 6.7.3

**Comment by numaanashraf** [comment]
This has been addressed in Postman v7.0
