### ISSUE TITLE
Body resets to html when changing tabs

### ISSUE THREAD

**Issue by bbrosius** [a85/POSTMan-Chrome-Extension#2919]
1. Postman Version: 4.10.6
 2. App (Chrome app or Mac app): Windows App
 3. OS details: Windows 10
 4. Is the Interceptor on and enabled in the app:
 5. Did you encounter this recently, or has this bug always been there: Seems to be recent as of the last version. 
 6. Expected behaviour: When changing tabs the body format selection isn't reset.
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 8. Screenshots (if applicable)

1. Make an http request that returns json. 
2. Body comes back with html formatting selected.
3. Switch formatting from html to json.
4. Switch to another request tab.
5. Return to previous tab formatting has reset from json to html.

**Comment by kamalaknn** [comment]
Hey @bbrosius 

Thanks for reporting the issue. We are looking into this. We will get back to you with a fix in the next version.

**Comment by sujayvenaik** [comment]
Hey @bbrosius 
Hi, we have addressed this issue as part of various improvements we have made to how tabs work in Postman. These changes are up available on our canary channel (https://www.getpostman.com/canary) today and would soon be available on the stable channel. Do try these out in the canary and let us know.

**Comment by sujayvenaik** [comment]
Hey @bbrosius ,
This issue has been fixed and is available on the stable channel (v6.4.x).
You can update the app to the latest version.

Thanks again for writing in and reporting this issue.

**Comment by bbrosius** [comment]
@sujayvenaik Thanks so much for getting this fixed, works much better now.
