### ISSUE TITLE
Feature Request: Show as curl command

### ISSUE THREAD

**Issue by matthewpflueger** [a85/POSTMan-Chrome-Extension#292]
On the occasion when you need to execute an http request from the command line (like when you are ssh'd into another host) it would be great if what you were just executing from POSTMan could be shown as a curl command...

**Comment by andrewjmead** [comment]
@a85 I'm using the packaged app but can't seem to find it. Where is the option located?

**Comment by andrewjmead** [comment]
Found it. Click "preview"  the select "curl" up at the top. Thanks!

**Comment by bricker** [comment]
Did this feature get removed from the Postman 3 app? I can't find it...

**Comment by a85** [comment]
@bricker You can now generate code in 15+ languages including curl by hitting the "Code" icon at the bottom right. It's just next to the red reset button.

**Comment by bricker** [comment]
@a85 I see it now, thanks!

**Comment by brian-stinar** [comment]
Yeah, I'd LOVE this. I always have to spend a bunch of time translating between my postman requests and curl.

**Comment by Ademord** [comment]
Any updates on this?

**Comment by ArashJalalian** [comment]
I would love this.

**Comment by micer** [comment]
@brian-stinar @Ademord @ArashJalalian it's in Postman already, see comments above! ;-)
