### ISSUE TITLE
Parameter inputs work extremely slow in v. 4.10.5

### ISSUE THREAD

**Issue by malabyan** [a85/POSTMan-Chrome-Extension#2920]
1. Postman Version: 4.10.5
 2. App (Chrome app or Mac app): Chrome
 3. OS details: win / x86-32
 4. Is the Interceptor on and enabled in the app: ON
 5. Did you encounter this recently, or has this bug always been there: everytime since latest update
 6. Expected behaviour: in previous version with a little bit other design of parameter-input fields input worked fine, it shouldn`t freeze
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app): -
 8. Screenshots (if applicable)
![postman-issue](https://cloud.githubusercontent.com/assets/25370022/24803636/76c22a20-1bb4-11e7-8df7-24437897d4e3.gif)

As you can see from the attached gif the new-looking fields for parameters are extremely slow - I put the cursor inside the field, type data but it always freezes for a couple of seconds which is VERY annoying. It never happened before with an older design (started a week or a couple of weeks ago).
Please can you fix it? I love Postman )

**Comment by tomex443** [comment]
+1

**Comment by a85** [comment]
This should be fixed with the latest update.

**Comment by ivanlewis** [comment]
After new UI, setting parameters it is damn slow. Using Desktop app on Windows 10. This needs to be fixed asap. Thanks

**Comment by tomex443** [comment]
I had this same problem. In Version 4.10.7 it's works fine than in previous versions.

**Comment by cph2117** [comment]
I have 4.10.7, and am having this problem as well. It makes it almost unusable...

**Comment by gregeisips** [comment]
I am on 5.0 and I have similar problems -- too slow to use this

**Comment by cph2117** [comment]
@prashantagarwal Is there an update on this? The app is unusable...

**Comment by prashantagarwal** [comment]
Hi, @cph2117 . We have released quite a few updates after 4.10.7 . Can you update it to the latest version (v5.0.2) and see if this is still happening for you. Also, can you tell how many collections/requests do you have currently.

**Comment by cph2117** [comment]
@prashantagarwal I'm on v 5.0.2 on Mac, and the issue still persists

**Comment by igoel** [comment]
same here, using:
Version 5.1.2
linux / x86-64
Chrome 56.0.2924.87

**Comment by jschram** [comment]
Same issue here; typing anything anywhere is painfully lagging

Postman 5.2.0 (standalone version)
Mac OSX 10.12.6

Checkout my timeline export from the dev tools: https://gist.github.com/jschram/41be00df5f033905185d53e979a47714

There's a lot of delays around keypress events

**Comment by jseger** [comment]
What is the status of this issue?  Are there any workarounds?

**Comment by prashantagarwal** [comment]
We have fixed this internally. We will make this available with our next release.

**Comment by prashantagarwal** [comment]
We have released the fix on our Canary app. Can someone please verify it.

**Comment by prashantagarwal** [comment]
You can download our canary apps from [here](https://www.getpostman.com/canary)

**Comment by jseger** [comment]
Yeah works good!

**Comment by prashantagarwal** [comment]
Awesome.I will close this once we release the fix on our stable channel.

**Comment by prashantagarwal** [comment]
We have release the fix with Postman v6.1.2.

**Comment by jseger** [comment]
I'm still seeing this issue in v6.7.3.

**Comment by jkrusinski** [comment]
I also still see this issue in 6.7.4, but only in the request URL field. Typing any url is extremely slow.
