### ISSUE TITLE
Overzealous autocompletion for environmental variables

### ISSUE THREAD

**Issue by mtoothman** [a85/POSTMan-Chrome-Extension#2923]
1. Postman Version: 4.10.5
 2. App (Chrome app or Mac app): Mac app
 3. OS details: macOS Sierra, 10.12.3
 4. Is the Interceptor on and enabled in the app: yes
 5. Did you encounter this recently, or has this bug always been there: unsure
 6a. Expected Autocomplete is only invoked between `{{}}`.
6b. Actual: Autocomplete is invoked everywhere.
 7. Console logs: n/a
 8. Screenshots (if applicable):

![image](https://cloud.githubusercontent.com/assets/4804034/24813159/fe048a56-1b9a-11e7-9151-8748311f7f51.png)

Steps to reproduce the problem: Create an environment variable beginning with `1` (like`12`), then type a `1` anywhere.

**Comment by prashantagarwal** [comment]
@mtoothman Thanks for bringing up this point. Actually autocompleting variables is just a starting point. We want to provide more power to this autocomplete to make it super useful for various use cases. For example imagine autocompleting test snippets. Also we are working on bunch of other stuff for test scripts and having autocomplete behave just like autocomplete in code editors helps us to solve all those use cases as well.
