### ISSUE TITLE
Request Body Do you want to add templates for reference

### ISSUE THREAD

**Issue by tonycody** [a85/POSTMan-Chrome-Extension#2927]
Do you want to add templates for reference.

If you do not support the request to add a fixed request format template, the contents of the request may have been replaced. Standard format can not remember

sample:
![qq 20170408125559](https://cloud.githubusercontent.com/assets/6773121/24825857/d6d6584a-1c5a-11e7-9b30-14ea401172f3.png)

But that description takes up too much space to fold up

Body Content JSON format should be provided

**Comment by a85** [comment]
I'd suggest using the new "Examples" feature for templates.
