### ISSUE TITLE
Share individual links to requests

### ISSUE THREAD

**Issue by tonycody** [a85/POSTMan-Chrome-Extension#2928]
![qq 20170408135410](https://cloud.githubusercontent.com/assets/6773121/24826251/f5e34834-1c63-11e7-91cb-d85bf1af1913.png)
![qq 20170408135447](https://cloud.githubusercontent.com/assets/6773121/24826252/f60e088a-1c63-11e7-88b5-c6bdbbda8291.png)
![qq 20170408135815](https://cloud.githubusercontent.com/assets/6773121/24826253/f637d5c0-1c63-11e7-9d8e-710c57c4fda1.png)

For reference only

**Comment by tonycody** [comment]
In addition, can you hide some of the information that is not commonly used?

**Comment by a85** [comment]
You can use collection links for this. The unit of sharing in Postman will remain as a collection for now.
