### ISSUE TITLE
Slow UI after updating to v4.10.6

### ISSUE THREAD

**Issue by ghost** [a85/POSTMan-Chrome-Extension#2929]
After updating to **v4.10.6** UI became slow. When clicking on Send button it takes a considerable amount of time for its text to become _Sending..._; Or when clicking inside body of a request to type a json object it takes some time(1 or 2 seconds) for cursor to appear.

 1. Postman Version: **4.10.6**
 2. App (Chrome app or Mac app): **Desktop Version**
 3. OS details: **Windows 10**
 4. Is the Interceptor on and enabled in the app: **Yes**
 5. Did you encounter this recently, or has this bug always been there: **It appeared just now, today**.
 6. Expected behaviour: When you click on the body field of a request it shouldn't take 1 second long.

Steps to reproduce the problem: **Update to the latest version**.

**Comment by concordion2k** [comment]
+1 

Same details for me: Win 10, v4.10.6

The app as a whole is unresponsive for several seconds between UI clicks, such as opening a collection, clicking a request, etc. In one use case, I counted a full 15s before the UI responded to a click.

**Comment by augustosamame** [comment]
+1
Exactly the same issue for me when upgraded to last version
It gets progressively worse as more tabs are opened, until UI is virtually unusable

Postman Version: 4.10.6
App (Chrome app or Mac app): Desktop Version
OS details: OSX El Capitan
Is the Interceptor on and enabled in the app: No
Did you encounter this recently, or has this bug always been there: It appeared just now, today right after upgrading.
Expected behaviour: When you click on the body field of a request it shouldn't take 1 second long.

**Comment by numaanashraf** [comment]
@miladamirzadeh @concordion2k @augustosamame We are looking into this.

**Comment by mikealexds** [comment]
+1 
Gets unusable pretty quickly.
Postman Version: 4.10.6
App (Chrome app or Mac app): Desktop Version
OS details: OSX El Capitan

**Comment by numaanashraf** [comment]
@miladamirzadeh @concordion2k @augustosamame @mikealexds We have identified the issue. Working on pushing a fix as soon as possible.

**Comment by ferasodh** [comment]
+1

**Comment by ghost** [comment]
@numaanashraf Thank you so much. Postman is a great tool.

**Comment by gaochengyidlmu** [comment]
+1
please make it , thank u

**Comment by numaanashraf** [comment]
@miladamirzadeh @concordion2k @augustosamame @mikealexds @ferasodh @gaochengyidlmu We are rolling out `v4.10.7` to address this issue. Do update and let us know.

**Comment by gaochengyidlmu** [comment]
just now, the version 4.10.7 has been released.
the problem resolved.
Thank you very much!

**Comment by numaanashraf** [comment]
Glad to hear that @gaochengyidlmu. Thanks again for your patience and support. Have a good week. 😃

**Comment by ghost** [comment]
@numaanashraf  Thank you so much.

**Comment by gregeisips** [comment]
I am having the same problem with v5.0 -- so slow when updating variables in the tests or pre-execution scripts in particular

**Comment by sdnts** [comment]
@gregeisips We working on some performance optimizations around variables, and we'll push out a release for this very soon. You can follow #3216 for updates.

**Comment by syamalakonapuram** [comment]
Hi,
After upgrading to version  6.1.3, MAC(OS-10.12.6), performance is too bad. Just an example: One of the API triggers an email. Before Postman shows the API response, I am able to see the email in my inbox. Every operation in Postman taking lot of time. In this version performance really screwed up.
Your help on this is much appreciated. Thank you.
