### ISSUE TITLE
HTTPS calls not connecting - iOS simulator

### ISSUE THREAD

**Issue by d3020** [a85/POSTMan-Chrome-Extension#2930]
Hi, 

This is my first post here and hoping someone can help. Would appreciate it. In a nutshell, I can't seem to get the https calls to show up in Postman. Here is what I have done. 

- Installed Postman 4.10.6 (Mac app)
- Proxy settings are on and pointing to 5555
- In my Mac OS settings I have the http and https proxy settings on and set to 127.0.0.1 and port 5555
- When I go on the iOS simulator and to any site that is http... I can see the traffic in Postman. That is good.
- But when I go to anything using https... it does not load
- I have tried going into Settings on Postman and turning the SSL certificate verification off, but it did not seem to change anything with the experience.

What am I missing? 

Thanks.

**Comment by sdnts** [comment]
@d3020 Have you set up the same proxy on HTTPS as well?
