### ISSUE TITLE
Request - Postman Debian repository (PPA)

### ISSUE THREAD

**Issue by Eli-Goldberg** [a85/POSTMan-Chrome-Extension#2931]
It would be really awesome to be able to:

sudo apt install postman

:)

**Comment by numaanashraf** [comment]
Hi @Eli-Goldberg, thanks for the suggestion. This is on our roadmap but we don't have an ETA for this just yet. 😃

**Comment by DrakaSAN** [comment]
Any update since april? Currently, updating on linux is a pain if you didn't setup a script to do it for you...

**Comment by Graham42** [comment]
Someone has already created a script to create the need .deb  file https://gist.github.com/SanderTheDragon/1331397932abaa1d6fbbf63baed5f043

**Comment by Eli-Goldberg** [comment]
@Graham42 this is awesome. Thank you !

@numaanashraf Bumping this. I think this is important, could really use this repository,
plus this would keep everyone up to date with your latest updates.
Thanks.

**Comment by repkins** [comment]
Yeah, would be nice to have ASAP especially for frequent updates.

**Comment by DanielRamosAcosta** [comment]
Also, it would be nice to have a debian package.

**Comment by ldeveikis** [comment]
Any news?

**Comment by You2s** [comment]
Please make as soon as possible the update messages that you can't remove in the settings drive me crazy

**Comment by espaciomore** [comment]
Thank you, made my day!

**Comment by ghost** [comment]
A Snap package (https://snapcraft.io, https://www.ubuntu.com/desktop/snappy) would be another solution that would cover many of the popular Linux distributions.

**Comment by shreyaskarnik** [comment]
+1 on Snap package!

**Comment by Alishankhan** [comment]
+1 on Snap package!!

**Comment by klapperkopp** [comment]
snap pls

**Comment by alaczibb** [comment]
Snap us please! :)

**Comment by alexberny** [comment]
+1 on Snap package!!!

**Comment by ilya40umov** [comment]
Yeah, it's super annoying to download every new version manually. So, any solution which would allow to auto update Postman on Linux would be very much appreciated.

**Comment by sdnts** [comment]
We will be looking into Linux app distribution very soon, I'll let you guys know here when we have an update.

**Comment by bluet** [comment]
Expecting.
Gotta use Insomnia temporarily before Postman snap package got released.

**Comment by Rndwiga** [comment]
+1 on snap package please

**Comment by emilianobonassi** [comment]
+1 on snap

**Comment by RidgeA** [comment]
Hi, what about rpm repo?

**Comment by kenshin6x** [comment]
+1 on snap or even deb/rpm package

**Comment by tristan957** [comment]
Why can't people just give an upvote to a comment instead of the +1 bs? I just want to read the actual discussion. If you have nothing to say, don't comment.

**Comment by matudelatower** [comment]
+1 on snap

**Comment by alexander-khrystych** [comment]
+1 to `apt-get` - in combination with current way of Postman distribution on Linux, these popups are getting extremely annoying. It's convenient either to click 'Update' then provide a root password and see an updated app on the screen in a few seconds, or don't update at all till some major updates. 

I don't want to go through hacking with re-installing the app to update it to get rid of destruction I get every time I have to check something that just came up to my head real quick. Making no tumbler for 'update notifications' is completely unclear to me.

**Comment by rcludwick** [comment]
+1 to snap.   It seems to be the way of the future, especially for commercial/non-libre apps.

**Comment by ghisvail** [comment]
`electron-builder` can generate a lot of [packages](https://www.electron.build/configuration/configuration) which can be published in a release channel somewhere (on GitHub or the official website).

If you guys could generate a working `.deb` from `electron-builder` then it could serve a basis for `snap` or `flatpak` to provide universal Linux support.

**Comment by kocian** [comment]
+1 on snap

**Comment by x80486** [comment]
So, folks...it's been **MORE** than a year since this was reported. Tons of people have expressed their opinions...but still, there is no answer from you.

It shouldn't take you more than a week to generate a **Flatpak** these days ‒ or even a Snap. That's all we are asking for.

**Comment by matudelatower** [comment]
New in Ubuntu Software
![615bc307-f674-4691-a386-678e6946cbcd](https://user-images.githubusercontent.com/5694115/40054147-3611fc3c-581a-11e8-9d60-df477c18c12d.jpeg)

**Comment by mshipko-lineate** [comment]
+1 for snap or apt's package

**Comment by prashantagarwal** [comment]
Hey Everyone, with Postman v6.1.0, we have released automatic updates for Linux. With the help of this your Postman app will be available to update itself whenever a new version will be released. You can read more about it here http://blog.getpostman.com/2018/05/16/postman-6-1-linux-auto-update/

**Comment by tristan957** [comment]
I don't really think this solved the problem though. The point of the task is to provide a non-tarball based solution to Linux packaging. With an actual package format, updates should be left to the package manager whenever possible. Please do not close this issue.

**Comment by mshipko-lineate** [comment]
The app suggested me to download the new version from the site. Not good.

**Comment by prashantagarwal** [comment]
@mshipko-lineate From now onwards it won't suggest you but will actually download the update http://blog.getpostman.com/2018/05/16/postman-6-1-linux-auto-update/

**Comment by prashantagarwal** [comment]
@tristan957 Can you give me a use case where our automatic updates won't help to solve the issue. The idea behind these automatic updates was to make user experience for updates seamless like other OS.

**Comment by ghisvail** [comment]
> Can you give me a use case where our automatic updates won't help to solve the issue.

Since the code for the auto-updater is not opensource, and therefore not verifiable, how can I trust future updates won't erase my `/home` or `/` folders by inadvertence?

> The idea behind these automatic updates was to make user experience for updates seamless like other OS.

Which is the responsibility of a package manager on Linux. Hence why your community is asking for `apt`, `flatpak` or `snap` solutions.

I personally tried to help kickstart a flatpak packaging effort in #4512 (which is a packaging solution I am experienced with), but this door was shut to my face with a straight closing of this issue and no follow-up on the discussion. As far as community management is concerned, I have seen better, much better.

**Comment by ghost** [comment]
Thanks for the auto-updating feature on Linux - much better!

@prashantagarwal In my opinion auto-updates are only part of the story. The opening comment wasn't to do with updates - it was just about installing the application in the first place. I'd still love to be able to do a `sudo apt-get install postman`.

**Comment by ilya40umov** [comment]
@prashantagarwal 
Here are some advantages of using snaps over a proprietary solution (with other package managers some of these points may not apply):
1. I can install / update the app directly from the terminal, without having to open a website and download it from there. As a nice benefit it makes more difficult for hackers to convince people to install fake software. (E.g. a Postman-like site sends me an email, saying that there is major update that requires me to re-download the app, and the link leads to a site where I download malware. All of this would be much harder to pull off if I had Postman installed as a snap)
2. I don't need to figure out where to put the app on my machine, after I have downloaded it.
3. With snaps I have a few previous versions kept around in case I need to rollback.
4. Snaps normally run in a sandbox
5. I won't need to create .desktop file myself

**Comment by prashantagarwal** [comment]
OK Guys, these requests seem pretty reasonable. So I have opened a new feature request, using which we will be tracking all the package requests. I think there are couple of them related to Snap, Flatpack etc, which I will link to the issue.

**Comment by mirland** [comment]
BTW: I think this issue should be reopened until the feature is done.

**Comment by tvvignesh** [comment]
+1 for the Postman Snap Package

**Comment by publicvirtualvoid** [comment]
Yes please! Why is this issue closed?

**Comment by djbrown** [comment]
Today I came across this Issue, this is what I found:

- Unofficial Snap: https://snapcraft.io/postman
  > This snap is not going to be maintained for any changes that require action beyond a rebuild. 
- Unofficial Flatpak: https://flathub.org/apps/details/com.getpostman.Postman
  > This wrapper is not verified by, affiliated with, or supported by Postman or Postdot Technologies.

**Comment by ghisvail** [comment]
Indeed, there are multiple means to install and subsequently update,
Postman on Linux today.

Unfortunately, the ones you listed are not officially endorsed by the
upstream developers, and are maintained by their respective community on a
best effort basis. Therefore, the disclaimers you quoted are accurate and
necessary.

**Comment by andydavidson** [comment]
Every application on my computer asking to maintain its own software updates and dependencies is going to leave a stinking mess. There is a reason the community has signalled a strong preference for a solution that works via the existing package manager in their linux distribution. Please adopt this method and not some trendy "I can update myself" poison.

**Comment by ghisvail** [comment]
@andydavidson I totally agree with you, though I can understand the upstream developers' perspective. Especially if they are not familiar with the Linux ecosystem and packaging solutions.

The good news are that we have got some choice (snap and flatpak) and a community of users who are willing to help maintain and update those packages. Upstream may join the maintenance effort later, when they feel more comfortable about them.

**Comment by x80486** [comment]
@andydavidson, If you use a Flatpak (or Snap), the dependencies thing is not an issue at all. Additionally, you would get the updates consistently (as long as they are published), etc.

Moreover, a PPA would be only a benefit for Debian-flavored distros.

**Comment by tiagohillebrandt** [comment]
In case anyone on this thread is interested, I've created a PPA for Postman on Launchpad: https://launchpad.net/~tiagohillebrandt/+archive/ubuntu/postman

Usage:

```
$ sudo add-apt-repository ppa:tiagohillebrandt/postman -y
$ sudo apt-get update
$ sudo apt-get install -y postman
```

**Comment by Eli-Goldberg** [comment]
@tiagohillebrandt 
Finally !!
Will this be updated frequently?
IMHO this issue can be closed

**Comment by RidgeA** [comment]
It is not a vendor's repository, so no one could guarantee continuous support of it and up-to-date versions. I'd like to see an official repository (rpm would be nice too).

**Comment by tiagohillebrandt** [comment]
@Eli-Goldberg Yes, for now I've been updating it on monthly basis. When time permits I will setup an automation to update the PPA automatically when new Postman versions are released.

**Comment by tiagohillebrandt** [comment]
@RidgeA I've created this PPA to help the community. Of course an official PPA is always welcome, but while we don't have one it can be helpful.

@numaanashraf In case you are interested, please feel free to use this source to create an official PPA: https://github.com/tiagohillebrandt/postman-ubuntu-ppa

**Comment by RidgeA** [comment]
@tiagohillebrandt 
No offense. My point just that the issue couldn't be closed.

**Comment by tiagohillebrandt** [comment]
@RidgeA None taken. Actually the issue was closed a while ago lol

Not sure if they still having plans to release that official PPA.

**Comment by RidgeA** [comment]
@tiagohillebrandt 
> Actually the issue was closed a while ago lol

Yeah, I know. It is pity ...
I'm talking more about the real issue rather than issue on github :-)

**Comment by adrianrudnik** [comment]
Just removed 19 Postman-{{timestamp}.tar.gz files and their extracted counterparts after detecting I'm still on 6.1.x. Seems like the auto-updater just downloads but fails to replace either the directory or symlink?

Please use some established mechanism for distribution.

**Comment by smamran** [comment]
https://github.com/linux-bd/ubuntu/blob/master/app/postman.md

**Comment by ghisvail** [comment]
And?

Le dim. 4 nov. 2018 à 10:15, এস এম এমরান <notifications@github.com> a
écrit :

**Comment by tnatanael** [comment]
+1

**Comment by habibix** [comment]
+1

**Comment by PedroJuan91** [comment]
hi guys!
2nd month of 2019 and getting to 3rd month,
is there any updates regarding for the official PPA or SNAP in postman..
thanks :)

**Comment by lonix1** [comment]
@PedroJuan91 No, the OP spoke of a PPA.

Not everyone uses snap, because it updates automatically without giving control to the user.

**Comment by rcludwick** [comment]
And a lot of people really like snap, because it updates automatically
without needing user intervention.

It's not like there only has to be one and exactly one packaging
solution...

**Comment by lonix1** [comment]
@rcludwick The OP was for PPA, and this issue has since been hijacked to promote snap.

However, I agree. There should be PPA and snap.

**Comment by elliottn** [comment]
would be helpful since some chromebooks can install debs

**Comment by tristan957** [comment]
The fact that this has been closed, and not repopened is laughable. The issue was closed with no reasoning, and the solution the Postman team provided is not even close to the respective package formats requested. Postman is just another company that treats Linux as a second-class citizen. I urge all of you to quit using this application. They do not care about our opinions. @tiagohillebrandt set up a PPA faster than the official team did. If it takes so little effort to do, why can't they do it? There are alternatives out there like Insomnia that are open source, and listen to what their users have to say. Use the power of choice to force the Postman team to listen to you. Unsubscribing from this issue because the +1 spam is obnoxious and the issue will never be fixed.

If the Postman team ever chooses to listen to us, then they should take note from Discord. Discord is a closed source application which allows distributions to repackage it. Solus has it in their main repo, and updates are distributed through the package manager. If Postman will not create packages for Linux that work with package managers, then they should allow distributions to repackage it.

**Comment by adrianrudnik** [comment]
Today was the day where this all breaks down to the best worst case. Just tried to open up a project and there is no "normal" way around it. Either log out and loose my stuff until "someone" updates something or invest another 30 minutes on this damn topic.

- PPA is not up-to-date (no worries, its awesome someone even made one and its not to critize its out-of-date)
- Postman itself has not done anything to help in 2 years, Linux installation is still manual and automatic updates still do not work as intended (at least for me).

![Screenshot from 2019-03-28 11-51-45](https://user-images.githubusercontent.com/681514/55152326-6f6a9400-5150-11e9-9c58-e32f0bd080b4.png)

**Comment by jflambert** [comment]
Sorry, why was this closed? I'm using this [PPA](https://launchpad.net/~tiagohillebrandt/+archive/ubuntu/postman) and it hasn't been updated since 8.12.4

How am I supposed to get the latest version on 18.04?

**Comment by jflambert** [comment]
PPA was just updated to 9.12.0 ;) thanks @tiagohillebrandt

**Comment by tiagohillebrandt** [comment]
@jflambert No problem :-)

**Comment by robinpecha** [comment]
Some version updates in PPA, pls?

**Comment by MrHaroldA** [comment]
@tiagohillebrandt , can you please look into updating Postman to the latest stable again? Tnx!

**Comment by tiagohillebrandt** [comment]
Hey guys, PPA has been updated to the latest version. Also, just a heads up I'll be dropping the Ubuntu Xenial support (official support ended on April 2021) on the next PPA update.

**Comment by MrHaroldA** [comment]
@tiagohillebrandt there's a new version again: Postman v9.25.2. Is it feasible for you to keep updating the PPA, or should we switch to a different way to keep our local Postman installations up-to-date?

**Comment by seantcanavan** [comment]
it looks like we only got a snap unfortunately so everyone who has de-snap'd their ubuntu distro is going to be stuck self-installing / self-updating

for any newcomers just go here: https://github.com/linux-bd/ubuntu/blob/master/app/postman.md

**Comment by tiagohillebrandt** [comment]
@MrHaroldA Unfortunately I had no access to a device with Ubuntu to generate and test the PPA packages for a while. Now that is resolved, and the PPA has been updated with the latest Postman version :-)

**Comment by princebillygk** [comment]
This is issue is reported in 2017 but still no action.

**Comment by someperson** [comment]
The snap has usability problems for me (tiny cursor; unfixed for at least 2 years). Any updates on this as an alternative?
