### ISSUE TITLE
Automatically save collection to file upon edit

### ISSUE THREAD

**Issue by marcioAlmada** [a85/POSTMan-Chrome-Extension#2932]
1. Postman Version: Any
 2. App (Chrome app or Mac app): Chrome
 3. OS details: Linux
 4. Is the Interceptor on and enabled in the app: Nope
 5. Did you encounter this recently, or has this bug always been there: It's a feature request
 6. Expected behaviour:

I'm using Postman + newman command line tool. Every time a collection is updated I have to export the collection file manually in order for newman to execute it. That's a little bit annoying if you're doing it ~30 times a day or more :sweat_smile:

How about being able to hit ctrl+s and have the collection persisted as a local file too? Or is there already a way to better integrate Newman and Postman locally?

Thanks!

**Comment by marcioAlmada** [comment]
@a85 was this feature rejected or closed because [duplicate]? I could not find the other issue asking for the same thing.

**Comment by a85** [comment]
Yes: https://github.com/postmanlabs/postman-app-support/issues/2248

There are a lot of duplicates in the current tracker so been cleaning them all up.

**Comment by Mkuteg** [comment]
@a85 Hello!
Do you have any updates about this issue? A lot of people really waiting for this feature.
And not for only collections, but for environment too. 
Thank you!

**Comment by shashankawasthi88** [comment]
Hi @Mkuteg, have you tried backing up the collection on GitHub, Dropbox, etc. We have a bunch of Integrations available for backing up your collections (https://learning.postman.com/docs/integrations/intro-integrations/). 
For running the latest copy of Collection via Newman, you could also use the Postman Cloud APIs. See an Interesting Blog Post that explains various options available - https://blog.postman.com/newman-run-and-test-your-collections-from-the-command-line/
