### ISSUE TITLE
Feature Request: private variable values in environment

### ISSUE THREAD

**Issue by garthk** [a85/POSTMan-Chrome-Extension#2935]
Working around #2934 requires OAUTH2 endpoint URIs, client IDs, client secrets, and the eventual `access_token` itself to be held in the environment. The environment is synchronised to Postman.

I'd much appreciate being able to choose some environment variables for which the _values_ should not be synchronise. Please do keep synchronising the keys; just replace the values with `[REDACTED]` and prompt the user of the desktop or web apps to provide their own values if they need them.

**Comment by a85** [comment]
Thanks for the feature request. This is coming through sessions. RFC here: https://community.getpostman.com/t/sessions-in-postman/1925

Tracking the request elsewhere.
