### ISSUE TITLE
Extract RESTCONF specification url parameters

### ISSUE THREAD

**Issue by vcmJonasTarnowetzki** [a85/POSTMan-Chrome-Extension#2937]
1. Postman Version: 4.10.7
 2. App: Chrome app
 3. OS details: Ubuntu 16.04.2 LTS
 4. Is the Interceptor on and enabled in the app: No
 5. Did you encounter this recently, or has this bug always been there: Always as far as I know.
 6. Expected behaviour: When testing an api that uses RESTCONF specified url parameters, these parameters are extracted by Postman into the params window for editing.
 7. Console logs: none available

The [RESTCONF specification requires url parameters](https://tools.ietf.org/html/draft-ietf-netconf-restconf-18#page-25) to be in the form of `/leaf-list=id/`.  Postman can currently correctly generate urls of this type from swagger.json files, but Postman cannot identify these parameters and display them for editing in the params section.

The following would be a valid RESTCONF url: `http://IPADDRESS/restconf/data/top-leaflist=fred/`  Postman is capable of importing a swagger.json file describing this endpoint, resulting in  `http://IPADDRESS/restconf/data/top-leaflist=:name/`

This url would be a valid RESTCONF url, but the parameter is not extracted:
![restconf-url](https://cloud.githubusercontent.com/assets/17341448/24919773/f6fa0092-1ea1-11e7-8a73-41d7817b8522.png)

Conversely, the following url is not valid RESTCONF but is valid in other specifications, and the parameter is extracted:
![restconf-url-invalid](https://cloud.githubusercontent.com/assets/17341448/24919777/fa398458-1ea1-11e7-87ec-2d78a22c16e9.png)

Is related to Issue #85.

**Comment by a85** [comment]
We have no plans to change the existing parameter format for now and the rendering of the related user interface. If we do this in the future, it'll be through a plug-in.
