### ISSUE TITLE
Unicode characters in scripts do not sync correctly

### ISSUE THREAD

**Issue by hughescr** [a85/POSTMan-Chrome-Extension#2939]
1. Postman Version: Version 4.10.7 (4.10.7)
 2. App (Chrome app or Mac app): Mac app
 3. OS details: 10.12.4
 4. Is the Interceptor on and enabled in the app: na
 5. Did you encounter this recently, or has this bug always been there: noticed recently, but probably always been there and I hadn't noticed
 6. Expected behaviour: Valid unicode characters in javascript should be correctly saved and retrieved during syncing
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app): na
 8. Screenshots (if applicable)

![screen shot 2017-04-11 at 5 22 30 pm](https://cloud.githubusercontent.com/assets/46348/24936133/8e1e983c-1edb-11e7-8352-8525e86e8107.png)
![screen shot 2017-04-11 at 5 23 42 pm](https://cloud.githubusercontent.com/assets/46348/24936163/c51c21ba-1edb-11e7-9f58-21dd6cff9fb0.png)

Steps to reproduce the problem:

a. Create a new request
b. Create a pre-request script or a test script which contains unicode characters
c. Click "Save"
d. Share and subscribe to the collection; or else call the postman API to retrieve the collection by uid
e. The script is truncated producing incorrect results, or even invalid unparseable/unexectuable javascript

**Comment by hughescr** [comment]
Note that line 2 above works fine -- escaped unicode works; only inline unicode is breaking things, whether it's in a comment or a string, or probably elsewhere too.

**Comment by kamalaknn** [comment]
We've pushed fixes in our Sync layer in the latest release. Please update to the latest version.
