### ISSUE TITLE
Highlighting text while renaming request in Sidebar drags the whole request

### ISSUE THREAD

**Issue by anton-arsentyev** [a85/POSTMan-Chrome-Extension#2940]
1. Postman Version: 4.10.7
 2. App (Chrome app or Mac app): Mac App
 3. OS details: MacOs Sierra

![screen shot 2017-04-12 at 14 57 21](https://cloud.githubusercontent.com/assets/22887126/24958805/e9a806b0-1f90-11e7-8a1b-393c6735dd61.png)

Steps:

1.  Click "Rename" in Context menu
2. Try to highlight text to edit/delete, but instead i move whole element, like in non Edit mode.

**Comment by numaanashraf** [comment]
Thanks for reporting this @anton-arsentyev. We are working on a fix and will roll it out in an upcoming release.

**Comment by numaanashraf** [comment]
This issue is fixed in Postman v7.0.9
