### ISSUE TITLE
Cannot generate collection link

### ISSUE THREAD

**Issue by wendyleecook** [a85/POSTMan-Chrome-Extension#2946]
1. Postman Version: 4.10.7
 2. App (Chrome app or Mac app): Chrome (57.0.2987.133)
 3. OS details: Windows 7 SP1
 4. Is the Interceptor on and enabled in the app: On
 5. Did you encounter this recently, or has this bug always been there: Just in the last week or so
 6. Expected behaviour: I should be able to generate a collection link
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 8. Screenshots (if applicable)

1. Show the sidebar and click the ... button for a collection then click Share
2. Click Collection Link
3. Click Get Link
4. Wait for link to be generated

**Comment by numaanashraf** [comment]
Hi @wendyleecook, thanks for reporting this. I'm not able to replicate this issue. Could you try again and let us know if this is happening again?

**Comment by vinodbudala** [comment]
Hi @numaanashraf, even for me collection link is not getting generated.

**Comment by SamvelRaja** [comment]
@wendyleecook  and @vinodbudala can you provide us few more details on this issue to help[at]getpostman.com?
Closing this here, as it needs more information needs to be shared privately.
