### ISSUE TITLE
Feature request: Preview tab with relative resources links.

### ISSUE THREAD

**Issue by justux90** [a85/POSTMan-Chrome-Extension#2948]
Hello,
when you make request to server and it's responding with HTML page all relative links to CSS/JS/etc files will be broken and will not work. Full URLs is working fine.

So `/assets/style.css` will not work while `http://example.com/assets/style.css` will work in `Preview` tab and HTML is shown correctly.

---

Also it would be great to open links from JSON response in default browser rather than in new postman tab.

**Comment by powelski** [comment]
What is the status of this issue? I believe it would be great if previewing HTML in Postman mirrored browser's behavior as much as possible. Relative URLs are a standard accepted by W3C.

**Comment by vkaegis** [comment]
@justux90 @powelski You should be able to open relative URLs from the response in tabs now. Just for clarification, Postman allows you to open relative URLs in the response in a new tab where we automatically append the base URL to it. We also now have variables with which you can reuse these values.

We don't yet have the ability to open it in a browser, but I can mark that as a feature request for a configuration if you'd like?

**Comment by justux90** [comment]
I think it would be fine to have in app viewer only

Sent from Yahoo Mail on Android 
 
  On Thu, 15 Nov 2018 at 12:10, Vineet Kumar<notifications@github.com> wrote:   
@justux90 @powelski You should be able to open relative URLs from the response in tabs now. Just for clarification, Postman allows you to open relative URLs in the response in a new tab where we automatically append the base URL to it. We also now have variables with which you can reuse these values.

We don't yet have the ability to open it in a browser, but I can mark that as a feature request for a configuration if you'd like?

**Comment by vkaegis** [comment]
@justux90 Awesome, closing this issue for now. Feel free to open another if you have more feedback around this.

**Comment by samuelgfeller** [comment]
> You should be able to open relative URLs from the response in tabs now. Just for clarification, Postman allows you to open relative URLs in the response in a new tab where we automatically append the base URL to it.

I'm not sure if I understand well @vkaegis, is there a setting that makes Postman prepend the base url to the relative resources (css) link? Because that would allow us to have a styled render in the Preview tab.

Basically I have a set of requests (with a specific body) and need to preview the styled result, is that possible with Postman, and if yes how?
