### ISSUE TITLE
[Bug] Memory leak

### ISSUE THREAD

**Issue by bluesky139** [a85/POSTMan-Chrome-Extension#2949]
1. Postman Version: 4.9.3
 2. App (Chrome app or Mac app): PC native app
 3. OS details: Windows 7 x64
 4. Did you encounter this recently, or has this bug always been there: always
 5. Screenshots
![image](https://cloud.githubusercontent.com/assets/1788897/25034469/4f8fa288-2119-11e7-8cf0-d4a3974a06d8.png)

 Open postman and send request again and again, you can see the memory always increase.
 It will not decrease even close all tabs.

**Comment by snaits** [comment]
I'm having a similar issue with Postman for Chrome on Windows 10 (x64) with version 4.10.7.

**Comment by SamvelRaja** [comment]
We are constantly working on optimizing our memory consumption in our native app. Thanks for taking  your time and providing the info on this. We shall update this thread on the progress as well.

**Comment by georgedpeterson** [comment]
Same issue here.

**Comment by wtchangdm** [comment]
I think I encountered this on macOS as well. Would like to provide information if needed.

**Comment by kamalaknn** [comment]
@bluesky139 @georgedpeterson @snaits 

We've made a lot of changes to the Postman app's data storage layers. Could you update your apps to the recent version(`6.0.10` now) and verify if this still exists?

**Comment by bluesky139** [comment]
I just test v6.0.10, it looks like no memory leak anymore, I think I can close this issue now.
