### ISSUE TITLE
SSO we have a continue button to connect to the site

### ISSUE THREAD

**Issue by plegault3397** [a85/POSTMan-Chrome-Extension#2952]
1. Postman Version: v4.10.7
 2. App (Chrome app or Mac app): chrome
 3. OS details: Windows
 4. Is the Interceptor on and enabled in the app:no
 5. Did you encounter this recently, or has this bug always been there:always
 6. Expected behaviour:
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 8. Screenshots (if applicable)
<p>You're about to login to LeanKit.</p>
<p>Please click "Continue" to be redirected to your account login page.</p>

Unable to get past this

**Comment by arpit0729** [comment]
Thanks for reporting this @plegault3397 . Could you mail us at help@getpostman.com your team-name and username.
