### ISSUE TITLE
[Feature] Default view should be 'Body' rather than 'Authorization'

### ISSUE THREAD

**Issue by daddyshortlegs** [a85/POSTMan-Chrome-Extension#2954]
When you click on a request in any collection, the default view is 'Authorization'. Most of the time, I'm really only interested in the request, so by default, would it be a better idea to make the default view 'Body'? It should save quite a few clicks.

**Comment by bdone** [comment]
+1 for this. for saved requests within a collection, it would be nice to default to the last used tab (auth, headers, body, etc.), or add a preference to let users default to their own choice.

**Comment by jormaechea** [comment]
+1.. Plus, it would be nice for this to be a setting

**Comment by bhawna2109** [comment]
Tracking a similar issue here- #2086 
Closing this as duplicate.
