### ISSUE TITLE
Request: Close all tabs in Chrome app 

### ISSUE THREAD

**Issue by strowk** [a85/POSTMan-Chrome-Extension#2956]
From https://github.com/postmanlabs/postman-app-support/issues/1263 I get that we can close all tabs now only in native app, but it would be great to have it in Chrome too. 

Since one of the last update tabs become persistent (they stays even after reboot) and now plenty of tabs could only be closed one by one - it's veeery long. I think I have hundreds of them. It would take half an hour to close them all =(

**Comment by a85** [comment]
Google has deprecated Chrome apps and unfortunately no new APIs are being published on the Chrome platform. I'd recommend moving to native apps.
