### ISSUE TITLE
ReferenceError when using tests

### ISSUE THREAD

**Issue by fdw** [a85/POSTMan-Chrome-Extension#2957]
1. Postman Version: 4.10.7
 2. App (Chrome app or Mac app): Native Linux app
 3. OS details: Ubuntu 16.04
 4. Is the Interceptor on and enabled in the app: n/a
 5. Did you encounter this recently, or has this bug always been there: since last week, at least
 6. Expected behaviour: tests run without error, as described in [http://blog.getpostman.com/2014/01/27/extracting-data-from-responses-and-chaining-requests/](http://blog.getpostman.com/2014/01/27/extracting-data-from-responses-and-chaining-requests/)
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
```ReferenceError: $ is not defined```
 8. Screenshots (if applicable)

Add a test to extract a value from a HTML form, f.e. 
```var responseHtml = $(responseBody);```

I would expect this to run and `responseHtml` to contain a version of the response. Instead, I get the error "ReferenceError: $ is not defined"

**Comment by numaanashraf** [comment]
Hi @fdw, we have deprecated and removed jQuery from the script sandbox in our native apps. We recommend you use Cheerio for extracting value from HTML response. You can find the info at http://blog.getpostman.com/2016/08/30/jquery-replaced-by-cheeriojs-in-postman-sandbox/ & https://cheerio.js.org/

**Comment by fdw** [comment]
@numaanashraf: Thank you, this solves my problem! :)

**Comment by numaanashraf** [comment]
@fdw Glad to hear that. 😃
