### ISSUE TITLE
Tab Completed text removed after sending a request

### ISSUE THREAD

**Issue by johnpurser** [a85/POSTMan-Chrome-Extension#2958]
1. Postman Version: 4.10.7
 2. App (Chrome app or Mac app): Chrome App
 3. OS details: Windows 10
 4. Is the Interceptor on and enabled in the app: No
 5. Did you encounter this recently, or has this bug always been there: I just installed it, not sure
 6. Expected behaviour: Should not remove 'tab completed' text in test after request is sent
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 8. Screenshots (if applicable)

**Comment by numaanashraf** [comment]
Hi @johnpurser could you post a screenshot showing the 'tab completed' text you are referring to?

**Comment by johnpurser** [comment]
![postman1-2017-04-20_12-31-08](https://cloud.githubusercontent.com/assets/8234611/25244630/2579a360-25c7-11e7-9a56-60a8da36403a.png)
![postman2-2017-04-20_12-31-08](https://cloud.githubusercontent.com/assets/8234611/25244629/25798f56-25c7-11e7-83c6-8a08730e1e54.png)

**Comment by johnpurser** [comment]
@numaanashraf 

Screenshot added.  Please advise.
