### ISSUE TITLE
Postman ignores the Cache-Control header

### ISSUE THREAD

**Issue by tsonev7** [a85/POSTMan-Chrome-Extension#2959]
I have web api which includes the Cache-Control header on GET

The postman response is
**Cache-Control →max-age=3600**
Content-Length →19
Content-Type →application/json; charset=utf-8
Date →Wed, 19 Apr 2017 19:12:42 GMT
Server →Microsoft-IIS/10.0
X-AspNet-Version →4.0.30319
X-Powered-By →ASP.NET
X-SourceFiles →=?UTF-8?B?RDpcdHNvbmV2XFByb2plY3RzXFdlYkFwaVRlc3QyXFdlYkFwaVRlc3QyXGFwaVx2YWx1ZXM=?=

I disabled the setting "Send no-cache header" but even when the Cache-Control header is included in the response, Postman always goes to the server when I call the method for a second time ?

**Comment by a85** [comment]
Postman can't control the response that it receives. The no-cache header is sent by Postman to your server. That's something that you have to look with your server.

**Comment by heroicefforts** [comment]
The no-cache header is great, unless you're trying to test ETag behavior.

**Comment by Moahamm** [comment]
if i want to configure that cache-control to no-cache or no-store by using postman then how will it be possible?
