### ISSUE TITLE
Simplify postman environment / global variable resolution

### ISSUE THREAD

**Issue by gitfool** [a85/POSTMan-Chrome-Extension#2960]
Variables are fundamental to scripting, so even the slightest reduction in API overhead would be much appreciated. With that in mind, I should be able to resolve a variable regardless of its scope, given the simple assumption that environment variables override global variables.

Currently I have to check both, for example using `environment[varName] || globals[varName]`, when I should be able to just use `variable[varName]`, or `postman.getVariable(varName)` (for those that prefer verbosity), where the API checks both scopes in override order.

 1. Postman Version: 4.10.7
 2. App (Chrome app or Mac app): Chrome app
 3. OS details: Windows 10 (1607)
 4. Is the Interceptor on and enabled in the app: No
 5. Did you encounter this recently, or has this bug always been there: N/A
 6. Expected behaviour: N/A
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app): N/A
 8. Screenshots (if applicable)

**Comment by skyboyer** [comment]
Note: #2832 is about slightly different thing but with the equal outcome: generic .getVariable would be more handful then separated getEnvironmentVariable/getGlobalVariable

**Comment by kunagpal** [comment]
@gitfool This can be done as follows:
```js
pm.variables.get('my_var_name'); // data > environment > globals
```
