### ISSUE TITLE
Feature request: List the versions of the javascript libraries that the sandbox has access to

### ISSUE THREAD

**Issue by mstaalesen** [a85/POSTMan-Chrome-Extension#2961]
It would be really nice to have an option to display the version of the libraries that the sandbox is using. I'm aware that I can check https://www.getpostman.com/docs/sandbox to see what libraries are available. The problem with this right now, is that it does not show which version that is in use, and it will not show when you are updating the version of a library.

My request would be to have this information available through a button or an option in menu (in the native app), or perhaps show it under Settings? It could be something as easy as showing it under About.

Something like:
Postman v4.10.7
Lodash: <version>
CryptoJS: <version>
SugarJS: <version>
[....]

**Comment by a85** [comment]
We are working on extending the sandbox to support external libraries which will give more control over the libraries being used. Closing this issue for now.
