### ISSUE TITLE
[MacApp] [Bug] : Environment variables cleared after switching tabs

### ISSUE THREAD

**Issue by anton-arsentyev** [a85/POSTMan-Chrome-Extension#2963]
1. Postman Version:  4.10.7
 2. App (Chrome app or Mac app): MacApp
 3. OS details: MacOs Sierra

Created new environment variables, didnt click "Update" button, switched tab to "Environment templates", switched back - variables disappear...

![screen shot 2017-04-20 at 14 43 35](https://cloud.githubusercontent.com/assets/22887126/25231371/f59d5bbc-25d7-11e7-8ae8-eadb337ce117.png)

**Comment by numaanashraf** [comment]
Thanks for reporting this @anton-arsentyev. We look into this and include a fix soon.

**Comment by anton-arsentyev** [comment]
@numaanashraf better fix this - https://github.com/postmanlabs/postman-app-support/issues/2545 ;) or this - https://github.com/postmanlabs/postman-app-support/issues/2895
Its much more important for me
Thanks
