### ISSUE TITLE
Feature request: Allow the URL text box height to be adjusted

### ISSUE THREAD

**Issue by staybfutrell** [a85/POSTMan-Chrome-Extension#2965]
Postman for Chrome Version: 4.10.7 win / x86-32
Windows 10 Pro x64 build 10586.873
Interceptor is disabled

It would be nice to be able to resize the URL portion of the window to be able to see the entire URL without having to click on it.

Example:
https://example.com/api/products-detailed/?s=searchexact~nm~Custom%20Stringer%20NEMA%205-20%20Plug%20to%205-15%20Duplex%20Black%2F5-15%20Duplex%20Black%2F5-15%20Duplex%20Black%2F5-15%20Duplex%20Black%2F5-15%20Duplex%20Black%2F5-15%20Duplex%20Black%20Receptacle%5C%28s%5C%29%20-%20All%20Boxes%3A%20Black%20-%20125V%2F15A%2012%2F3%20SOOW-EPDM%20-%20Plug%20to%20Box%201%20Length%3A%2013%20feet%20%2F%20Box%201%20to%20Box%202%20Length%3A%206%20feet%20%2F%20Box%202%20to%20Box%203%20Length%3A%206%20feet%20-%20Total%20Length%20of%20cord%20sections%3A%2025%20feet

While I can click Params and then Bulk Edit will allow me to see the entire query parameter value it takes a few more steps

**Comment by a85** [comment]
@staybfutrell I don't see how we could do this without breaking the UI. Closing this for now. Will pick it up when we have a re-look at the interface.
