### ISSUE TITLE
download url for a specific version is necessary !

### ISSUE THREAD

**Issue by ghost** [a85/POSTMan-Chrome-Extension#2967]
I wanna package Linux native app for postman, but I found it there is only an url avaliable - https://dl.pstmn.io/download/latest/linux64

This url always gives me the latest Linux native app, therefore I can not package it for my linux box.
You know, linux packaging system always need a version number.

**Comment by numaanashraf** [comment]
Hi @m31271n, which distro are you on? We are working on adding support for linux package managers.

**Comment by ghost** [comment]
@numaanashraf I am on Gentoo.

**Comment by ghost** [comment]
Current linuxXXXX.tar.gz is OK. Just need a version number, then we will have a package for Gentoo. ;)

**Comment by czardoz** [comment]
@m31271n, you can use this endpoint to fetch information about available versions, as well as a link to each one: https://dl.pstmn.io/changelog

**Comment by ghost** [comment]
@czardoz Thanks. That's what I want.
