### ISSUE TITLE
Feature request: Code generate support R language (RCurl package or httr pachage)

### ISSUE THREAD

**Issue by strategist922** [a85/POSTMan-Chrome-Extension#2968]
1. Postman Version: Postman v4.10.7
 2. App (Chrome app or Mac app): Windows APP
 3. OS details: Windows 7 / 10 64 Bit 

could it possible to add R Language support in code generation function?
For example, could support generate code for R Language's RCurl or httr package.

**Comment by robertocross** [comment]
I would like this feature added too.

**Comment by fljoly** [comment]
This would be nice. I've been struggling

**Comment by umeshp7** [comment]
We'll be soon adding this support. You can track the progress here: https://github.com/postmanlabs/postman-code-generators/issues/347

**Comment by DannyDainton** [comment]
Support for Rcurl and httr are now in the Postman platform

<img width="482" alt="image" src="https://user-images.githubusercontent.com/17089546/177528818-b4bbcb91-66a9-44ab-bdf2-141affbecf8d.png">
