### ISSUE TITLE
Runner data file is not loaded on retry

### ISSUE THREAD

**Issue by 70mmy** [a85/POSTMan-Chrome-Extension#2969]
When I run a collection and provide a data file, the first time running, the variables from the data file are loaded as expected, if I hit "Retry" the variables from the file are not loaded (the "data" variable is empty).

 1. Postman Version: 4.10.7
 2. App (Chrome app or Mac app): Mac app
 3. OS details: Mac os 10.12.4
 4. Is the Interceptor on and enabled in the app: -
 5. Did you encounter this recently, or has this bug always been there: just discovered
 6. Expected behaviour: 
On "Retry" the data file should be loaded again

Start a collection runner with a data file and add a console.log(data) to a test. First time the collection runs, the data variable is populated, if you hit "Retry", data is empty

**Comment by zemien** [comment]
I'm experiencing the same issue on Windows native app 4.10.7 too.

**Comment by gqy117** [comment]
The same issue on Windows native app 5.0.2

**Comment by sdnts** [comment]
We've managed to reproduce and fix this issue. A patch will be out with the next release :)

**Comment by sdnts** [comment]
Guys, this should be fixed with 5.2. Please reopen if you still see this.

**Comment by i3anaan** [comment]
Experienced this issue (twice) with a later version:

Postman for Windows
Version 7.9.0
win32 10.0.18362 / x64

Therefore I would like to request @madebysid or @70mmy to reopen this issue
