### ISSUE TITLE
how to downgrade postman to old version？

### ISSUE THREAD

**Issue by longxianlin** [a85/POSTMan-Chrome-Extension#2973]
new version
style is terrible, and form is not good.
old version, form is best.

how to downgrade postman to old version?

 1. Postman Version:
 2. App (Chrome app or Mac app):
 3. OS details:
 4. Is the Interceptor on and enabled in the app:
 5. Did you encounter this recently, or has this bug always been there:
 6. Expected behaviour:
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 8. Screenshots (if applicable)

**Comment by numaanashraf** [comment]
Hi @longxianlin, we are constantly improving the app based on feedback. Could you let us know why you do not prefer the new data editors?

**Comment by edwardmlyte** [comment]
Mildly related: being able to control the version installed in pre-built environments would be extremely useful in maintaining stability.

**Comment by sburtonctr** [comment]
Did somebody find a solution for this?  The reason I wish to downgrade to the previous version is because clearing variables doesn't work anymore in 4.1.1.0.  This worked until this morning after an upgrade.

**Making this call in the Tests tab:**

    clearPrefixFromEnv("ws_");

**JavaScript Code:**

```
clearPrefixFromScope = function(scope, prefix, clearScope) {
    _.each(_.filter(_.keys(scope), function(prop) {
        return prop.startsWith(prefix);
    }), function(prop) {
        clearScope(prop);
    })};

clearPrefixFromEnv = function(prefix) {
    clearPrefixFromScope(environment, prefix, postman.clearEnvironmentVariable);
};

clearPrefixFromGlobal = function(prefix) {
    clearPrefixFromScope(globals, prefix, postman.clearGlobalVariable);
};

anyPrefixedInScope = function(scope, prefix) {
    return _.some(_.keys(scope), function(prop) {
        return prop.startsWith(prefix);
    })};

anyPrefixedInEnv = function(prefix) {
    return anyPrefixedInScope(environment, prefix);
};

anyPrefixedInGlobal = function(prefix) {
    return anyPrefixedInScope(globals, prefix);
};
```

**Comment by numaanashraf** [comment]
@sburtonctr Thanks for reporting this. We are looking into it. In the meantime, you can downgrade to a previous version by downloading the app from `https://www.getpostman.com/apps#changelog`. Before you do this, please turn-off auto-update via Settings > Update > Automatically download updates = None.

**Comment by sburtonctr** [comment]
Thank you, that worked downgrading back to 4.10.7.  If you need anymore information from me about this issue, just let me know, willing to help.

**Comment by numaanashraf** [comment]
@sburtonctr You can also get around this problem by explicitly binding the function you pass as `clearScope`.

```
clearPrefixFromEnv = function(prefix) {
    clearPrefixFromScope(environment, prefix, postman.clearEnvironmentVariable.bind(postman));
};

clearPrefixFromGlobal = function(prefix) {
    clearPrefixFromScope(globals, prefix, postman.clearGlobalVariable.bind(postman));
};
```

/cc @shamasis

**Comment by sanccie26** [comment]
> 
> 
> Thank you, that worked downgrading back to 4.10.7. If you need anymore information from me about this issue, just let me know, willing to help.

Would like to acquire 4.10.7 - you have recommendations?  Thanks!
sanccie26@gmail,com

**Comment by AnjanaSridhar** [comment]
I'm not able import Swagger 2.0 json into Postman 7.3.4 and 7.2.2.

**Comment by Guha5277** [comment]
This library was dead? Solution never comes?

**Comment by 0verEngineer** [comment]
> Hi @longxianlin, we are constantly improving the app based on feedback. Could you let us know why you do not prefer the new data editors?

Based on feedback from your manages? Because it cannot be the users or else the app would not push vendor lock like it does.
