### ISSUE TITLE
Slack - Postman Auth Login shows a blank page

### ISSUE THREAD

**Issue by swateek** [a85/POSTMan-Chrome-Extension#2974]
1. Postman Version: **4.10.7**
 2. App (Chrome app or Mac app): **Mac app**
 3. OS details: **Sierra**
 4. Is the Interceptor on and enabled in the app: **NO**
 5. Did you encounter this recently, or has this bug always been there: **Not Sure**
 6. Expected behaviour: **Postman should show an authorization page for Slack**
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 8. Screenshots (if applicable)

Used this blog [Slack-Postman Integration](https://api.slack.com/tutorials/slack-apps-and-postman) to create the integration.

However, on pressing "Get Access Token" a blank page pops up instead of the Slack page to authorize.

Created this issue here, because am using the postman redirect URL for my authorization.

**Comment by numaanashraf** [comment]
Hi @swateek, are you entering the Auth URL correctly? We just tried the flow detailed in the tutorial and it seems to work correctly on Postman for Mac v4.10.7.

<img width="482" alt="screen shot 2017-04-25 at 3 20 32 pm" src="https://cloud.githubusercontent.com/assets/3295568/25379733/acddbb90-29cb-11e7-9218-67703e6d03db.png">
<img width="805" alt="screen shot 2017-04-25 at 3 21 31 pm" src="https://cloud.githubusercontent.com/assets/3295568/25379734/acee73c2-29cb-11e7-925d-61d4087f4277.png">
<img width="953" alt="screen shot 2017-04-25 at 3 21 58 pm" src="https://cloud.githubusercontent.com/assets/3295568/25379735/aceef5d6-29cb-11e7-9e41-03b9610279ab.png">

**Comment by swateek** [comment]
@numaanashraf I got around this issue, apparently the Scope isn't an optional parameter for Slack. Thank you!

**Comment by JulienMalige** [comment]
Don't know if it can help. My issue was that I already had install the app (and accept the permissions).
