### ISSUE TITLE
OAuth 2.0 - Support ssl certificate authentication

### ISSUE THREAD

**Issue by kunagpal** [a85/POSTMan-Chrome-Extension#2975]
Originally posted by @sivakrishnajee in https://github.com/postmanlabs/newman/issues/997

When trying to get a new access token for oAuth 2.0 - Grant type of "Authorization Code" results in the following error:

error: invalid_request
Description: proper%20client%20ssl%20certificate%20was%20not%20presented

 1. Postman Version: Version 4.10.7 - win32 6.1.7601 / x64
 2. App (Chrome app or Mac app):
 3. OS details: Windows 7
 4. Is the Interceptor on and enabled in the app:
 5. Did you encounter this recently, or has this bug always been there: happening for last 3 months
 6. Expected behaviour: Postman should generate a new access token
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 8. Screenshots (if applicable)
![](https://cloud.githubusercontent.com/assets/17912926/25292352/c12c821e-26a3-11e7-82de-6b2e1bf61502.png)

![](https://cloud.githubusercontent.com/assets/17912926/25292399/efbe09d6-26a3-11e7-8733-0ec4ccd514df.png)

Steps to reproduce the problem:

1. Start Postman native app by clicking the same from windows desktop
2. Click the "Get New Access Token"
3. Click Request Token
4. Following error is displayed:
error: invalid_request
Description: proper%20client%20ssl%20certificate%20was%20not%20presented

**Comment by sivakrishnajee** [comment]
Kunagpal, Thank you for moving the ticket into the appropriate queue.

**Comment by harryi3t** [comment]
@sivakrishnajee 
This should be fixed in Postman 5.4

This is happening because the endpoint is certificate protected.
As of now, we don't support certificate authentication for OAuth-2 flows.

Renaming the title...

**Comment by kamalaknn** [comment]
@sivakrishnajee Starting from `5.3.1` Postman would use any Client SSL certificates you've defined under `Settings -> Certificates`. Please update your apps to the latest version and give it a try.

Please note that this is only available on our Native apps. Here's the download [link](https://www.getpostman.com/apps).
