### ISSUE TITLE
Postman is not getting oAuth 2.0 - Access Token when there are 2 SSL certificates in windows certificate store

### ISSUE THREAD

**Issue by kunagpal** [a85/POSTMan-Chrome-Extension#2976]
Originally posted by @sivakrishnajee in https://github.com/postmanlabs/newman/issues/998

 1. Postman Version: Version 4.10.7
 2. App (Chrome app or Mac app): Windows
 3. OS details: win32 6.1.7601 / x64
 4. Is the Interceptor on and enabled in the app:
 5. Did you encounter this recently, or has this bug always been there: happening for last 3 months
 6. Expected behaviour: Postman should generate a new access token
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 8. Screenshots (if applicable)

![](https://cloud.githubusercontent.com/assets/17912926/25293996/3b9d7a10-26ab-11e7-9bdf-d26c5d543484.png)

![](https://cloud.githubusercontent.com/assets/17912926/25294281/77d605e6-26ac-11e7-8d7b-7b1fe31cd56f.png)

1. Make sure that there are 2 certificates attached to windows certificate store.
2. Make sure that 1 certificate is configured with Postman.
3. Start Postman native app by clicking the same from windows desktop
4. Click the "Get New Access Token"
5. Click Request Token
6. Following error is displayed:
```
    error: invalid_request
    Description: proper%20client%20ssl%20certificate%20was%20not%20presented
```
8. Now, start Internet Explorer and remove one of the certificates (not being used by postman) from the Internet Options -> content -> certificates
9. Now, repeat above steps 3-6. Postman will get the access token.

**Comment by kamalaknn** [comment]
Hi @sivakrishnajee,

We've made sure OAuth 2 token requests use the client certificates configured in Postman starting `5.3.1-canary01`. 

Here are the download links
```
madOS:
https://dl.pstmn.io/download/channel/canary/osx_64

windows:
https://dl.pstmn.io/download/channel/canary/windows_32
https://dl.pstmn.io/download/channel/canary/windows_64

linus:
https://dl.pstmn.io/download/channel/canary/linux_32
https://dl.pstmn.io/download/channel/canary/linux_64
```

could you verify this?

**Comment by kamalaknn** [comment]
This should be out in Postman `5.3.1`. I am closing this issue, feel free to reopen if you are facing difficulties.
