### ISSUE TITLE
[MacApp][Feature]: Edit enviroment variables in url is painful

### ISSUE THREAD

**Issue by moleksyuk** [a85/POSTMan-Chrome-Extension#2977]
1. Postman Version: 4.10.7 (4.10.7)
 2. App (Chrome app or Mac app): Mac app
 3. OS details: macOS Sierra 10.12.4 (16E195)
 4. Is the Interceptor on and enabled in the app: 
 5. Did you encounter this recently, or has this bug always been there: I figured out this in on of the latest releases of Postman
 6. Expected behaviour: Invalid enviroment variable should be editable like a text and not disappear at all with press `Backspace` button.

Steps to reproduce the problem:

1. Create an enviroment variable `application-url`.
2. Create a new request and set url as: `http://{{application-url}}/user/get`. (At this point `application-url` has **orange** color which means it's valid)
3. Go to environment variables and rename it to `application`.
4. Back to the created request in step 2. (At this point `application-url` has **red** color which means it isn't valid).
<img width="465" alt="screen shot 2017-04-26 at 18 28 23" src="https://cloud.githubusercontent.com/assets/793472/25442681/55b1d3c2-2aae-11e7-874b-dfbb769240cc.png">

5. Put cursor in after `-url|}}` word and press `Backspace` button to start deletion of `-url` suffix.
6. After the press of `Backspace` button Postam deletes the whole variable!!! and my url becomes as `http:///user/get`. This behavior is painful. I just wanted to delete suffix, why it's delete?
<img width="546" alt="screen shot 2017-04-26 at 18 28 31" src="https://cloud.githubusercontent.com/assets/793472/25442693/5e82d776-2aae-11e7-9d10-ee6f86e49627.png">

As a suggestion, if you rename some environment variable - just update it in all requests. It will be very helpful because I have a lot of requests and sometimes it requires to rename some variables and then I need to update each request.

**Comment by vegetableman** [comment]
@moleksyuk We are able to reproduce the issue. Will keep you posted ^_^.

**Comment by prashantagarwal** [comment]
Hi @moleksyuk , We are tracking this issue at #2895 . I am closing this issue as duplicate.
