### ISSUE TITLE
Integrating Postman with gitlab hosted in a private server. 

### ISSUE THREAD

**Issue by anurajsl** [a85/POSTMan-Chrome-Extension#2978]
I am a user who is in trial period of Postman Pro. I wanted to integrate my postman and collections with Gitlab. However I have created an access token and tried to add it in your integrate with gitlab section (https://app.getpostman.com/dashboard/integrations/gitlab/list)  in cloud app. But the issue is that I have created token in my custom hosted gitlab server ie. git.mydomain.com, but you are pointing to the gitlab.com site. Hence the token is treated as invalid. Can you please help me with integrating it with my privately hosted gitlab server

**Comment by scholary-tim** [comment]
+1

**Comment by reydi** [comment]
+1

**Comment by alexthornton** [comment]
+1

Even if this problem is not fixed, it would be very helpful if the GitLab integration documentation were updated.

**Comment by cafferata** [comment]
+1

**Comment by ratpik** [comment]
The feature to allow users to specify their custom gitlab hosted domain is part of our product roadmap. We will post an update to our [community](https://www.getpostman.com/community) channels when we release this.

**Comment by sbrendtro** [comment]
+10 Our company's CI/CD infrastructure is built on private GitLab servers, repos, build runners, etc.  Having a sync to private servers is a huge need, as we could further automate API testing using Newman as part of our build process.

**Comment by philmirez** [comment]
Will an update be posted here or should I just keep checking the community channel?

**Comment by ratpik** [comment]
We will close this issue after we roll out this feature. Until then all updates go to https://community.getpostman.com/

**Comment by jooleeanh** [comment]
+1, the gitlab integration was one of the main reason we purchased the Pro membership. Comes as a bad surprise to see it doesn't work with private GitlLab servers.

**Comment by albertoig** [comment]
Any news about this integration for private gitlab?

**Comment by ravikiran1988** [comment]
yeah we purchased pro recently and wrote a lot of integration tests, and in the end we found that the integration doesn't happen with privately hosted gitlab. Sad

**Comment by sabandemirci** [comment]
+1

**Comment by HappyZombies** [comment]
Would really appreciated if this feature was added. Much needed!

**Comment by jrantam** [comment]
+1

**Comment by daviddelannoy** [comment]
+1 waiting for this PR to get a Postman Pro licence, not really usable  for us without this feature

**Comment by molliejaeron** [comment]
+1 Gitlab integration is the reason I purchased Postman Pro. Not being able to use it with our privately hosted gitlab is killer.

**Comment by kataqatsi** [comment]
+1

**Comment by igoratencompass** [comment]
+1

**Comment by grubskim** [comment]
+1
Any reason why this feature is not on https://community.getpostman.com/?
It seems to get a lot of attention here.

**Comment by velger25** [comment]
We are just beginning to use Postman Pro and integrate it into our testing and CI/CD system and the ability of integrating with Git Lab was a big pull for us to use Postman. Adding this feature would open us to adding many more licenses as the implementation grows.

**Comment by merritta87** [comment]
+1 looking for progress report on this.

**Comment by MrMatthewDavis** [comment]
Any update here?

**Comment by sbrendtro** [comment]
I think I'm not alone in being a bit frustrated that it's been over a year and a half with no movement on this. I just posted the following feature request in the community forum, as apparently commenting here has zero effect.  I also emailed Postman corporate and tweeted at the CEO.  Hopefully someone somewhere is listening.

https://community.getpostman.com/t/gitlab-private-servers/3294

**Comment by kartikjain26** [comment]
@sbrendtro @anurajsl and others This issue is being currently worked upon. It should be available soon.

**Comment by a85** [comment]
@preethammavin This has shipped as well right?

**Comment by preethammavin** [comment]
Yes the feature has been released

**Comment by molliejaeron** [comment]
Can anyone get this to work since news came through that the feature was released? I can see the Gitlab custom domain integration set up section but keep getting an error.

> Oops! Looks like you did not enter the token associated with this custom domain. Please enter correct token and domain.

**Comment by kartikjain26** [comment]
@molliejaeron Can you confirm if you are using protocol (http/https) along with your domain url. Something like- https://example.com
And also that your personal access token has not expired.

**Comment by sbrendtro** [comment]
I had the same experience... adding the protocol fixed it.  However, I just checked my integrated GitLab repo, and no backup files are posted.  I made changes to two separate collections that are supposed to be backed up, and no changes were posted to the repo.  Followed the instructions here:  https://learning.getpostman.com/docs/postman_pro/integrations/gitlab/  Is there a way to see why it's not backing up?

**Comment by kartikjain26** [comment]
@sbrendtro  can you check if you had given api scope while creating personal access token for gitlab ? 
Like this one here-
<img width="611" alt="screen shot 2018-12-15 at 8 13 09 pm" src="https://user-images.githubusercontent.com/26088676/50044228-44c76480-00a6-11e9-996f-e55726cbe372.png">

**Comment by tibij** [comment]
I have a similar issue and I was wondering if anyone managed to see the files posted. I've successfully added the integration entry but there is nothing posted to the private Gitlab (the API scope was checked when the token was generated).

**Comment by shashankawasthi88** [comment]
Hi All - For the GitLab Integration on a custom domain, there might be a firewall issue that is blocking the Integration from running successfully. With the latest release, we are running the GitLab, GitHub, and Webhook Integration through a static IP. Once the IP is whitelisted in your network's firewall, the Integration should run as expected. Please follow the link to know about the details of the IP address - https://learning.postman.com/docs/integrations/intro-integrations/

**Comment by BoomtownSimon** [comment]
Hail Mary but here goes... I have the integration configured, repo and branches selected from the drop downs, which means Postman was able to access with my token yet all log activity fails with this ambiguous message. Opened a support ticket but apparently nobody can diagnose the problem and we're unable to use the integration. Confirmed we do not have IP based firewall rules. 

> Unknown error encountered during integration execution.

**Comment by shashankawasthi88** [comment]
@BoomtownSimon thanks for bringing this up. We have escalated this internally, the team should revert to you shortly.

**Comment by ghost** [comment]
I am using a SAML authentication for Gitlab, i created a personal access Token along with api, read_api and read_user permission and try to integrate into Postman along with custom domain(https://gitlab.domain.com), but getting a following error:
**Oops! Looks like you entered an incorrect token.**

**Comment by shashankawasthi88** [comment]
@mnomansadiq can you raise a support ticket, the team will reach out to you soon for the issue.

**Comment by ghost** [comment]
@shashankawasthi88 Can you please tell me where to create a support ticket for that?

**Comment by shashankawasthi88** [comment]
@mnomansadiq - [here](https://support.postman.com/hc/en-us/requests/new/)

**Comment by a85** [comment]
We have been working on a much better version of this request to satisfy the original intent and make Postman git-compatible. This will eventually supersede all existing Git integrations on the product. Postman workspaces that allow for pushing/pulling from the filesystem while also bringing in git-branch awareness that is useful for CI and pull request review workflows.

You can see it in action here: 

https://github.com/user-attachments/assets/7d29c5ff-ff2e-4c0f-a711-9499650cee92

Our engineers are using this internally and see huge gain in productivity in their workflow with the ability to tie collections, spec, and environment file changes tied to code commits.
