### ISSUE TITLE
Using environment variables from test window = Not working

### ISSUE THREAD

**Issue by dav1dbailey** [a85/POSTMan-Chrome-Extension#2980]
Hi,  

I have been using Postman for several months now and all okay so far, however I have a test that requires using an environment variable.  However It appears that any environment variables that are referenced from in the Tests section are ignored / do not work. I have so far been setting variables (this still works) but unable to use any variables.

I read on this site that its best to use the Pre-request Script to set a variable that will then be called from the Tests so I have tried that too however this also does not work.

Please let me know if you need to see the test or screenshot? Any help much appreciated.
Dave

Version/App Information:
-->
 1. Postman Version: 4.10.7 (win32 10.0.15063 / x64)
 2. App (Chrome app or Mac app): N/A
 3. OS details: Win 10
 4. Is the Interceptor on and enabled in the app: N/A
 5. Did you encounter this recently, or has this bug always been there: Unsure
 6. Expected behaviour: Successfully reference an environment variable from Tests Tab.
 7. Console logs 
 8. Screenshots (if applicable)

**Comment by sdnts** [comment]
Hi @dav1dbailey! How are accessing these environment variables?
In the pre-request script, you would ideally have something like: 
```
pm.setEnvironmentVariable('foo', 'bar')
```

and the test script would look like this:
```
let foo = pm.getEnvironmentVariable('foo',)
```

Also, do have an environment active? Without an active environment, this won't work. [Docs](https://www.getpostman.com/docs/environments)

**Comment by dav1dbailey** [comment]
Hi @madebysid. 

My test is using the current date and time. The pre-request script sets the currrent date and time as an env variable then the Test uses it like this:

**Pre request script:**

_postman.setEnvironmentVariable('SlotStart',function getDateTime() {
    var now     = new Date(); 
    var year    = now.getFullYear();
    var month   = now.getMonth()+1; 
    var day     = now.getDate();
    var hour    = now.getHours();
    var minute  = now.getMinutes();
    var second  = now.getSeconds(); 
    if(month.toString().length == 1) {
         month = '0'+month;
    }
    if(day.toString().length == 1) {
         day = '0'+day;
    }   
    if(hour.toString().length == 1) {
         hour = '0'+hour;
    }
    if(minute.toString().length == 1) {
         minute = '0'+minute;
    }
    if(second.toString().length == 1) {
         second = '0'+second;
    }   
    var dateTime = year+'-'+month+'-'+day+'T'+hour+':'+minute+':'+second;   
     return dateTime;
}());_

**The Test uses the 'SlotStart' variable like this:**

_for (var k = 0; k < response[i].Bookings.length; k++)
    {
        if (response[i].PestType == "Rats" 
        && response[i].ServiceType == "residential" 
        && response[i].Bookings[k].Status == "Confirmed" 
        && response[i].Bookings[k].SlotStart < "{{SlotStart}}")
        {_

This is probably not the ideal example to use as it is a bit complicated example.  So it is not just this example that does not work but it is any variable being used in the Tests that are not working.  For example if I amend the above Test =  _if (response[i].PestType == "Rats"_ to _if (response[i].PestType == "{{PestType}}"_ this too does not work.  Any variable being referred to from the Tests does not work / it is ignored.

**Comment by sdnts** [comment]
@dav1dbailey Sorry about the late response. I see your problem. Test scripts are JS, so the syntax `{{SlotStart}}` won't work here. Your test script would look like this:

```
var SlotStart = postman.getEnvironmentVariable('SlotStart')
for (var k = 0; k < response[i].Bookings.length; k++)
{
if (response[i].PestType == "Rats"
&& response[i].ServiceType == "residential"
&& response[i].Bookings[k].Status == "Confirmed"
&& response[i].Bookings[k].SlotStart < SlotStart)
{
```

Let me know if this does not work for you.

**Comment by dav1dbailey** [comment]
Thank you very much for your help.  This works :-)
