### ISSUE TITLE
Collection Runner not sending Authorization Header with GET Requests

### ISSUE THREAD

**Issue by shawnseaton** [a85/POSTMan-Chrome-Extension#2981]
1. Postman Version: 4.10.7
 2. App (Chrome app or Mac app): Mac App
 3. OS details: Mac OS Sierra 10.12.4
 4. Is the Interceptor on and enabled in the app: no
 5. Did you encounter this recently, or has this bug always been there:  recently with the latest update
 6. Expected behaviour: tests that run successfully individually should also run successfully in the collection runner.  Same tests run successfully in Chrome app.

 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):

 8. Screenshots (if applicable)
![collection_runner_and_developer_tools_-_file____applications_postman_app_contents_resources_app_html_runner_html](https://cloud.githubusercontent.com/assets/22386863/25539906/07a5fab8-2bfe-11e7-9e49-ba7293f77637.png)

![working test](https://cloud.githubusercontent.com/assets/22386863/25540140/d07f2982-2bfe-11e7-9c06-272860304a8f.png)

**Comment by goldie987** [comment]
I'm having the exact same issue!

**Comment by sdnts** [comment]
Guys, are you still seeing this? I was unable to reproduce this on the latest version (5.2.0). Please reopen if you're still seeing this.
