### ISSUE TITLE
New Dynamic Variables Request: test name references to enable application log backtrace back to postman

### ISSUE THREAD

**Issue by dlopuch** [a85/POSTMan-Chrome-Extension#2982]
The existing postman dynamic variables are {{$guid}}, {{$timestamp}}, and {{$randomInt}}.

Request adding a new ones: {{collectionName}} and {{testName}}.

Use case: 
Sometimes user's application logging might show something weird or warranting further investigation.  Being able to backtrace to originating request would be helpful. With {{collectionName}} and {{testName}}, the postman test that generated the requests can be dumped into custom headers (eg `X-Postman-Originator`), and user's application logging can capture that to backtrace to the original test suite that created the request.

Not all application incidents that warrant further investigation necessarily show up as error responses, so it's a bit more complicated than "well just look at which postman tests failed."

**Comment by shamasis** [comment]
You can achieve this by using any variable name of your choice as a value of header and then using pre-request script at a collection level to set its value. This actually allows you to set anything that you need and not be limited by what’s provided as dynamic variable. It’s also one-time inclusion in collection level script and doesn’t not need to be repeated for every item.

The dynamic variables are scoped across the app as a global and cannot be aware of collections and test.
