### ISSUE TITLE
HTTP POST Header wrong case

### ISSUE THREAD

**Issue by shuxiao9058** [a85/POSTMan-Chrome-Extension#2984]
1. Postman Version: 4.10.7
 2. App (Chrome app or Mac app): Mac app
 3. OS details: OS X 10.12.4 (16E195)
 4. Is the Interceptor on and enabled in the app: no
 5. Did you encounter this recently, or has this bug always been there: a bug always
 6. Expected behaviour: no
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 8. Screenshots (if applicable)
<img width="712" alt="image" src="https://cloud.githubusercontent.com/assets/3312525/25555861/b83118e2-2d23-11e7-94f9-04fe144f1dbd.png">

The export of postman post request's header of "Content-Type" is "content-type", can not parse with golang HTTP server.

https://tools.ietf.org/html/rfc7230#page-22

**Comment by czardoz** [comment]
@shuxiao, HTTP headers are case insensitive by default so it shouldn't matter. RFC: https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2

You can override it manually if needed :)

**Comment by shuxiao9058** [comment]
@czardoz 
as image below:
![wechatimg62](https://cloud.githubusercontent.com/assets/3312525/25557233/2d249f18-2d40-11e7-92f8-a8bb32b0777f.jpeg)

but exported curl code is: 

```
curl -X POST \
  http://httpbin.org/post \
  -H 'content-type: application/x-www-form-urlencoded' \
  -d key1=value1
```

This is a function in Golang, more info: [https://golang.org/src/net/textproto/reader.go?s=14869:14913#L552](url)

```
// CanonicalMIMEHeaderKey returns the canonical format of the
// MIME header key s. The canonicalization converts the first
// letter and any letter following a hyphen to upper case;
// the rest are converted to lowercase. For example, the
// canonical key for "accept-encoding" is "Accept-Encoding".
// MIME header keys are assumed to be ASCII only.
// If s contains a space or invalid header field bytes, it is
// returned without modifications.
func CanonicalMIMEHeaderKey(s string) string {
	// Quick check for canonical encoding.
	upper := true
	for i := 0; i < len(s); i++ {
		c := s[i]
		if !validHeaderFieldByte(c) {
			return s
		}
		if upper && 'a' <= c && c <= 'z' {
			return canonicalMIMEHeaderKey([]byte(s))
		}
		if !upper && 'A' <= c && c <= 'Z' {
			return canonicalMIMEHeaderKey([]byte(s))
		}
		upper = c == '-'
	}
	return s
}
```

**Comment by shuxiao9058** [comment]
Do you have any plan on this issue? 
@jeremys @abhijitkane @abroz

**Comment by shuxiao9058** [comment]
When did you start processing this bug?

**Comment by antidote2** [comment]
5.5.2 same issue - cannot use postman for chrome for this reason, but desktop version is 6 where it works

**Comment by abhijitkane** [comment]
@shuxiao9058 @antidote2 
Not able to reproduce this anymore. Also, in Postman 7.2.1, we've introduced bug-fixes, support for two new languages (JS-Fetch and Powershell), and the ability to configure certain aspects of the generated snippet with the 'Experimental Codegen Mode' flag enabled in Postman's global settings.
