### ISSUE TITLE
Cursor off by one or more character spaces

### ISSUE THREAD

**Issue by venkatcc** [a85/POSTMan-Chrome-Extension#2985]
1. Postman Version: 4.10.7
 2. App (Chrome app or Mac app): Postman for Windows 
 3. OS details: Windows 10 Pro
 4. Is the Interceptor on and enabled in the app:
 5. Did you encounter this recently, or has this bug always been there: Started using this only recently and I've seen it since day 1.
 6. Expected behaviour: Typed characters should be input at the cursor's position.
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 8. Screenshots (if applicable)

Steps to reproduce the problem:

1. Start a POST method for some API, and click on the "Body" tab, and choose the "raw" radio-button to compose the body of the API. 
2. Start typing some text, like say JSON key/value pairs.
3. The first few characters seem to be displayed as typed and the cursor position seems fine. But after a while, the cursor position is off by one or more character spaces. The behavior is very similar to what is described here for ATOM: https://discuss.atom.io/t/cursor-appears-to-be-displayed-one-character-to-the-right-of-its-actual-position/1452

A video showing the behavior: https://www.youtube.com/watch?v=rk5Mnl5t-S8
You'll see that when I start typing the second key/value pair, the cursor 'races' ahead from where the characters are being typed.

Note: When I tried key/value pairs of shorter lengths, I did not see this issue. Can't explain the difference in behavior.
For example, the following does not have an issue:
{"key1":"value1", "key2":"value2", "key3":"value3", "key4":"value4", "key5":"value5", "key6":"value6", "key7":"value7", "key8":"value8", "key9":"value9"}

But this does:
{"email_address":"some_email_address@example.com", "first_name":"first-name"}

**Comment by gerbal** [comment]
Seeing the same issue on Ubuntu w/ Gnome DE linux 4.13.0-36-generic / x64
Postman Version 5.5.2

**Comment by griffinwalker** [comment]
same issue on arch linux 4.15.3-2-ARCH running i3wm

**Comment by prashantagarwal** [comment]
Can you guys update to the latest Postman app (6.1.4) and see if it is happening. Thanks

**Comment by venkatcc** [comment]
I see this happening in v6.1.4 as well.

**Comment by prashantagarwal** [comment]
@venkatcc are you on Windows ?

**Comment by venkatcc** [comment]
@prashantagarwal Yes, I'm.

**Comment by freiguy1** [comment]
I'm still seeing this issue - the font being used is NOT picking up the system monospace font. The font in the editor isn't even monospace.

**Comment by venkatcc** [comment]
Issue seen in v6.2.3 as well.

**Comment by geekysrm** [comment]
Same issue on latest version
Ubuntu 18.04

**Comment by venkatcc** [comment]
The issue is still seen in v6.5.3.

Tested on Windows 10.

**Comment by surewould** [comment]
I'm seeing this in an up to date Manjaro install. 6.6.0-1 from aur/postman-bin. Previous versions had it as well.

**Comment by TCB13** [comment]
+1 on windows 10. Postman 6.7.3.

**Comment by venkatcc** [comment]
The problem exists in Postman v7.0.7 (on Windows 10) as well.

**Comment by venkatcc** [comment]
Still in v7.2.2 (on Windows 10).

**Comment by Axzc** [comment]
Solved this problem in Postman v7.6.0

**Comment by venkatcc** [comment]
@Axzc Nope, I still see this after updating to Postman v7.6.0.

**Comment by Axzc** [comment]
@venkatcc I modified the postman font, this problem is gone, on ubuntu.

**Comment by pythoneer** [comment]
Problem still exists on Version 7.8.0
linux 5.3.4-arch1-1-ARCH / x64

out of the box

@Axzc where do i change the font? I only found a setting for the font size (Settings->General->User Interface)

**Comment by yrong** [comment]
this fucking issue last for 3 years, lose patience for postman

**Comment by Axzc** [comment]
@pythoneer in /Postman/app/resources/app/js/requester.css  search .editor.ace_editor

**Comment by yrong** [comment]
@Axzc  modify to what?

```
➜  Postman-6.1.3 cat app/resources/app/js/requester.css | grep -i ".editor.ace_editor" -C 5
.editor {
  font-size: 12px;
  border: 1px solid var(--hairline-strong);
  border-radius: 3px;
  /* Search Extension Styling */ }
  .editor.ace_editor {
    font: 12px "Monaco", "Menlo", "Ubuntu Mono", "Consolas", "source-code-pro", "Cousine", monospace; }
    .editor.ace_editor .ace_gutter {
      background-color: var(--bg-secondary); }
    .editor.ace_editor .ace_content {
      background-color: var(--bg-primary); }
  .editor.empty-editor .ace_hidden-cursors {
    visibility: hidden; }
  .editor.empty-editor .ace_marker-layer .ace_active-line {
    background: transparent; }
...

```


```
➜  Postman-6.1.3 lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.3 LTS
Release:	18.04
Codename:	bionic
```

```
➜  Postman-6.1.3 fc-list |more
/usr/share/fonts/truetype/msttcorefonts/comicbd.ttf: Comic Sans MS:style=Bold,Ne
greta,tučné,fed,Fett,Έντονα,Negrita,Lihavoitu,Gras,Félkövér,Grassetto,Vet,Halvfe
t,Pogrubiony,Negrito,Полужирный,Fet,Kalın,Krepko,Lodia
/usr/share/fonts/truetype/tlwg/TlwgTypo-Bold.ttf: Tlwg Typo:style=Bold
/usr/share/fonts/truetype/dejavu/DejaVuSerif-Bold.ttf: DejaVu Serif:style=Bold
/usr/share/fonts/truetype/arphic/uming.ttc: AR PL UMing TW MBE:style=Light
/usr/share/fonts/truetype/fonts-kalapi/Kalapi.ttf: Kalapi:style=Regular
/usr/share/fonts/truetype/fonts-gujr-extra/Rekha.ttf: Rekha:style=Medium
/usr/share/fonts/truetype/tlwg/TlwgTypewriter-BoldOblique.ttf: Tlwg Typewriter:s
tyle=Bold Oblique
/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf: DejaVu Sans Mono:style=Book
/usr/share/fonts/truetype/ubuntu/UbuntuMono-RI.ttf: Ubuntu Mono:style=Italic
```

**Comment by Axzc** [comment]
@yrong change to the appropriate font
This is my setting in ubuntu18.04
.editor.ace_editor {
 font: 12px "Ubuntu Mono", "Menlo", "Monaco", "Consolas","source-code-pro", "Cousine", monospace, monospace; }

**Comment by yrong** [comment]
@Axzc  That did work and Thanks.  My previous assumption is that if any font exists in fc list should work and seems not, need to keep `Ubuntu Mono` first

**Comment by venkatcc** [comment]
Postman v7.10.0 on Windows 10 still has this issue.

**Comment by a85** [comment]
Closing this issue as we haven't been able to replicate this. Please open a new issue with replication steps if needed.

**Comment by pythoneer** [comment]
I investigated this problem a little bit deeper and it looks like that in my case the problem stems from a bug in the noto font configuration on arch i have installed on my system https://github.com/googlefonts/noto-fonts/issues/1128 also https://bugs.archlinux.org/task/64083

**Comment by yrong** [comment]
@a85  have you ever read previous discussion? how dare you say unable to replicate?  The root cause is that default font configuration is not proper in most linux releases.
```
 font: 12px "Monaco", "Menlo", "Ubuntu Mono", "Consolas", "source-code-pro", "Cousine", monospace, monospace; }

```

**Comment by venkatcc** [comment]
I can reproduce this every time. I'm on Windows 10, and earlier suggestions to mess around with default font configuration on Linux to get this working right are not applicable on Windows (since I couldn't find the equivalent configuration files or the equivalent configuration settings).

Today, I removed my 7.10.0 installation and installed 7.12.0 and I still see the issue. I've attached a video showing the problem. As I start typing the second key-value pair, you can see the cursor moving ahead, and this makes any typing impossible. If you'd like to repoduce, I suggest trying the exact length strings I'm using in the video demonstration. Shorter length key-value pairs _may_ not exhibit the problem. And other length pairs may also exhibit the problem, but I've been testing with this pair because I know this always exhibits the problem.
[CursorOff.zip](https://github.com/postmanlabs/postman-app-support/files/3909569/CursorOff.zip)

**Comment by ubuntu2204** [comment]
The  reason is postman cannot find font.so use another one,but their weight is different.I had install font Menlo-Regular.ttf and Monaco-Linux.ttf.At last It works.

**Comment by pythoneer** [comment]
looks like even the workaround from @Axzc does not work anymore in  7.20.1

**Comment by renyuntao** [comment]
Same issue on latest version
Ubuntu 18.04

**Comment by pankajk07** [comment]
This has been fixed as part of `v7.26`. Please update your app and try it out.

**Comment by pythoneer** [comment]
@pankajk07 can confirm, this fixed it for me – thank you very much to all involved!

**Comment by venkatcc** [comment]
Yes!! It indeed is fixed!! Thanks.

**Comment by Sebastian23** [comment]
It still reproduces on v9.1.1 (Windows 10)

**Comment by paramothers** [comment]
Still it is there, in chromeos, chrome browser only. 
Brave browser doesnot have this cursor problem

**Comment by gkxk** [comment]
@Sebastian23 same issue here(win10, v9.5.0)
Setting -> General -> Font-family
change from "IBMPlexMono, 'Courier New', monospace" to "'Courier New', monospace". 
this fixed the problem for me

**Comment by Sebastian23** [comment]
> 

This actually works. Thanks a lot! :)

**Comment by carsonsaldanha** [comment]
> @Sebastian23 same issue here(win10, v9.5.0) Setting -> General -> Font-family change from "IBMPlexMono, 'Courier New', monospace" to "'Courier New', monospace". this fixed the problem for me

Thank you! This worked for me on ChromeOS.
