### ISSUE TITLE
Imported Collection adds Request Body to GET requests in Collection Runner

### ISSUE THREAD

**Issue by eltonium** [a85/POSTMan-Chrome-Extension#2986]
Version/App Information:
 1. Postman Version: 4.10.7
 2. App (Chrome app or Mac app): Postman for Windows win32 10.0.14393 / x64
 3. OS details: 
 4. Is the Interceptor on and enabled in the app: Don't know.
 5. Did you encounter this recently, or has this bug always been there: Recently, New User
 6. Expected behaviour:
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 8. Screenshots (if applicable)

Steps to reproduce the problem:
Issue: Importing an exported collection adds a request body to GET requests when using Collection Runner. Does not have issue Sending in Builder.

The request body seems to be inherited from prior POST/PUT/PATCH requests (anything with a response body). Re-saving the request (for example, add an "a", and then remove the "a", and save.) fixes the issue, but subsequent GET requests in the collection will then inherit the request body.

I'm not sure how this happens because as far as I'm aware, the user is not allowed to send a request body in GET requests.

Before exporting/importing
![get before](https://cloud.githubusercontent.com/assets/5133365/25564405/af4d91e4-2d80-11e7-97ef-8360dd0f4173.png)

After importing
![get import](https://cloud.githubusercontent.com/assets/5133365/25564409/b3b185ba-2d80-11e7-9a75-f0c8ee7d5943.png)

Console
![console](https://cloud.githubusercontent.com/assets/5133365/25564455/8c7a226c-2d81-11e7-984a-5f22cb1740e2.png)

Edit: This happens when a Request with a response body is copied, the Request is changed to a GET request, and then the collection is exported. It appears that when exporting, the previous response body is not cleared.

**Comment by tschuy** [comment]
It looks like the body is getting saved in the exported JSON, but not being ignored upon import. You can see all of the requests that will attempt to send a malformed body with:

`cat tschuy_postman.json | jq '.item | .[] | select(.request.method=="GET") | select(.request.body.raw != "")'`

**Comment by tschuy** [comment]
Also, exceptions (like `JSON.parse()` throwing upon trying to parse that HTML page) should count as failures, not successes. This bug was made even more frustrating by it showing itself with a cryptic "see DevTools" (when it should be "See Postman Console") and by a lower number of tests *having run* than I expected. At the very least, I should've had some notice up top that not everything went alright.

**Comment by numaanashraf** [comment]
This is addressed in the latest version of Postman (v6.7)
