### ISSUE TITLE
Generated python.http code for PUT and DELETE requests not working

### ISSUE THREAD

**Issue by Rahul-Lends** [a85/POSTMan-Chrome-Extension#2988]
Version/App Information:
 1. Postman Version: v4.10.7 
 2. App (Chrome app or Mac app): Mac app
 3. OS details:
 4. Is the Interceptor on and enabled in the app: yes
 5. Did you encounter this recently, or has this bug always been there: recently
 6. Expected behaviour: 
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 8. Screenshots (if applicable):

<img width="1182" alt="screen shot 1" src="https://cloud.githubusercontent.com/assets/19791614/25566927/d6bc867e-2e00-11e7-8cea-8ea6c8d05fb2.png">
<img width="709" alt="screen shot 2" src="https://cloud.githubusercontent.com/assets/19791614/25566928/d6bfb556-2e00-11e7-91c6-334b6d26395d.png">
<img width="1167" alt="screen shot 3" src="https://cloud.githubusercontent.com/assets/19791614/25566929/d6c653b6-2e00-11e7-8a42-f5ac112b5de5.png">

Hello,

I’ve been trying to run some of the generated scripts on Postman in Python so that I can manipulate them and make a few updates on Jive, by using the Jive REST API.
The generated Python scripts for GET and POST requests seem to be working fine. However, the PUT and DELETE requests keep returning a similar response on IDLE, as seen in the screenshots below.

For example, if I want to delete a document on Jive, I just send the following request using the Postman app, and this works. The document is successfully deleted from Jive.

(Screenshot 1)
The Python code generated to run this request is seen below:

(Screenshot 2)
However, an attempt to run this code using a Python IDE, results in the following:

(Screenshot 3)
The document is not deleted on Jive. This sort of output is produced upon executing the generated code for any sort of PUT or DELETE request.

This is an urgent requirement for my team at the moment, and we’d be extremely gratuitous if the issue could be resolved at the earliest.
Hoping for a swift response,

Thanks and regards,

Rahul Singh

**Comment by abhijitkane** [comment]
The screenshot shows a 302 from one of the endpoints. The Python library might not be automatically following redirects.  @Rahul-Lends - can you try updating the URL of the request in Postman to the correct URL (probably the one mentioned in the third screenshot)?

The code generated mentions delete, which is obviously correct. We're looking at ways to preserve the 'redirect' setting from Postman while generating the code snippets, and will open a separate issue for that.
