### ISSUE TITLE
Feature request: data for requests when not testing against file 

### ISSUE THREAD

**Issue by garthk** [a85/POSTMan-Chrome-Extension#2989]
Postman/Mac v4.10.7:

Situation:

* API with parameters passed in the URL path
* Desire to `{{substitute}}` those when hitting Send
* No desire to put them in the environment, as they're request-specific

I can get two out of three using the pre-request script:

```
environment['varname'] = environment['varname'] || 'value';
```

I'd _prefer_ to do this, as it'd then not pollute the environment:

```
data['varname'] = data['varname'] || 'value';
```

**Comment by a85** [comment]
You can use collection variables for this now.
