### ISSUE TITLE
Modification of the separator between the host and parameters

### ISSUE THREAD

**Issue by arvalon** [a85/POSTMan-Chrome-Extension#2990]
1. Postman Version: v.4.10.7
 2. App (Chrome app or Mac app): Chrome app
 3. OS details: Windows 8

Is it possible to remove or modify the question mark separation between the host and parameters? Now automatically populated with question mark ("?"). Some servers do not accept a delimiter and return an error.
![postmap1](https://cloud.githubusercontent.com/assets/19150332/25579181/19bcd730-2e7e-11e7-9c4b-fbf9630ab637.png)

**Comment by a85** [comment]
Not right now. But you can directly edit the URL field instead of using the URL params option.
