### ISSUE TITLE
Errors occur when snapping Postman window, then unable to expand/collapse sidebar

### ISSUE THREAD

**Issue by ericmacfa** [a85/POSTMan-Chrome-Extension#2991]
1. Postman Version: **4.10.7**
 2. App (Chrome app or Mac app): **Windows native app**
 3. OS details: **Windows 10 Enterprise x64**
 4. Is the Interceptor on and enabled in the app: **No**
 5. Did you encounter this recently, or has this bug always been there: **Recently**
 6. Expected behaviour: **Ability to snap Postman window to half-width (and maximize) without impairing usability**
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
(Attempted use of ``` didn't format properly?)
**Error occurs when snapping to half-width**
```
Uncaught Error Uncaught TypeError: Cannot read property 'id' of undefined file:///C:/Users/myUsername/AppData/Local/Postman/app-4.10.7/resources/app.asar/js/requester.js 14480 53
```
**Error occurs when clicking expand/collapse sidebar button, after snapping to half width**
```
Uncaught Error Uncaught TypeError: Cannot read property 'getHostNode' of null file:///C:/Users/myUsername/AppData/Local/Postman/app-4.10.7/resources/app.asar/js/common.js 7235 29
```
**Error occurs when maximizing, after snapping to half width**
```
Uncaught Error Uncaught Invariant Violation: Minified React error #136; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=136&args[]=Button for the full message or use the non-minified dev environment for full errors and additional helpful warnings. file:///C:/Users/myUsername/AppData/Local/Postman/app-4.10.7/resources/app.asar/js/common.js 3636 16
```
 8. Screenshots (if applicable)

    1. Open Postman and maximize
    2. Snap Postman window to half-width (drag to one side of the display)
    3. Maximize Postman window

**Comment by vegetableman** [comment]
@ericmacfa Those errors are not related to the window issue. Could you check if you have `Snap` enabled?. Checkout the screenshot below for the setting to enable.

![image](https://cloud.githubusercontent.com/assets/1330851/25743950/cf5978da-31b4-11e7-8f1b-d4efa504de19.png)

**Comment by ericmacfa** [comment]
@vegetableman I do have Snap enabled, please see the below picture. I am able to Snap the window, but the errors (mentioned above) occur when I do so.
![image](https://cloud.githubusercontent.com/assets/18381801/25806206/16821b80-33c8-11e7-9bef-a67603618a13.png)

**Comment by vegetableman** [comment]
@ericmacfa We are not able to reproduce this issue. Could you share a gif of the actions with the devtools open?.

**Comment by ericmacfa** [comment]
@vegetableman Please see below gif. Since it's low quality, I also included a screenshot of what the DevTools console looked like at the end
gif:
![postmanerror](https://cloud.githubusercontent.com/assets/18381801/26008048/cc7c0c0a-3708-11e7-8459-5646dbd2a4d5.gif)
Screenshot:
![image](https://cloud.githubusercontent.com/assets/18381801/26008025/b612f1fe-3708-11e7-909f-837f02d5f797.png)
