### ISSUE TITLE
postman window position can't be reset, can become unrecoverable off-screen

### ISSUE THREAD

**Issue by k3davis** [a85/POSTMan-Chrome-Extension#2992]
1. Postman Version: 4.10.7
 2. App (Chrome app or Mac app): Windows x64
 3. OS details: Windows 10
 4. Is the Interceptor on and enabled in the app: n/a
 5. Did you encounter this recently, or has this bug always been there: unknown

The Postman window can become unrecoverable off screen in the following situation:

* Dual monitors, with the screen extended across both monitors
* Open Postman and position on secondary monitor (in my case the right one)
* Change display settings to "duplicate displays" instead of extend

Postman is now positioned off screen in a completely inaccessible way. Attempts to correct:

* Win key + left (which typically manually drags a focused window's position) - no effect

* Right-click taskbar > Cascade windows - postman isn't included in the cascade and is still untouchable

* Uninstall/Reinstall app - window position as well as numerous other settings are retained as though you never uninstalled it at all (an issue unto itself)

**Comment by AadilC** [comment]
Experiencing the same issue (Win 10 multi monitor setup)

@k3davis try focusing on the postman window by _Clicking_ the icon on the __task bar__ 
or 
<kbd>ALT</kbd> + <kbd>TAB</kbd> (<kbd>WIN</kbd> + <kbd>TAB</kbd>) to select.

Once focused hit <kbd>ALT</kbd>+ <kbd>SPACE</kbd> which brings up  small menu
Then select either __Move__ or  __Maximize__ to adjust the window position 

hope this helps :)

**Comment by vegetableman** [comment]
Thanks for letting us know about this issue. Will keep you guys posted ^_^.

**Comment by MHeironimus** [comment]
Seeing this issue on Windows 7 also.

**Comment by AugustKarlstedt** [comment]
Issue still exists.

**Comment by k3davis** [comment]
I wonder (but have not tested the theory) if this issue is shared with other Electron apps, or if it is Postman-specific.

**Comment by kristyoverton** [comment]
I'm having this issue now, in v5.0.2.

**Comment by sdnts** [comment]
For the moment, if you guys see this, you can reset the app's window settings manually. To do this, you'll need to delete the `requester.json` file from the app's data directory, this is located:

on macOS: `~/Library/Application\ Support/Postman`
on Windows: `C:\Users\Postman\AppData\Roaming\Postman`
on Linux: `~/.config/Postman`

We'll take this up soon so the manual step isn't needed.

**Comment by Rigler01** [comment]
This happened to me yesterday when i connected remotely to my work machine (which does have multiple monitors, in case that's the relevant thing). I'm using version 5.2.1 and Windows 7. 

The manual fix re the requester.json file worked (once I'd permanently deleted it from the recycle bin)  - thanks very much for this, it saved my evening...as sad as that sounds!

**Comment by k3davis** [comment]
Simply exiting Postman, renaming the file, and starting it again worked for me (on Windows). I look forward to this getting fixed because I frequently switch between 1 and 2 monitor scenarios and forget to move Postman to my primary screen before doing so.

**Comment by skbr1234** [comment]
Still experiencing this on Windows 10 x64

**Comment by thecuriousdev** [comment]
The issue got fixed in **PostmanCanary 5.6.0-canary01**

get the build from https://www.getpostman.com/canary

**Comment by cshaw33** [comment]
This issue is happening again with Postman v7.3.4.

The old manual fixes mentioned above did not work for me, but I was able to resolve by editing C:\Users\user\AppData\Roaming\Postman\window and setting all values for "isFullScreen" to false

**Comment by Moltenhead** [comment]
Same issuse after update, here is some logs executing using the console launcher :
![Capture d’écran 2019-10-02 à 09 29 56](https://user-images.githubusercontent.com/32105250/66025638-3f34f100-e4f7-11e9-9745-58bba76d94fa.png)
The last message is indefinitly repeating itself and window doesn't show.

**Comment by hannabatjargal** [comment]
> For the moment, if you guys see this, you can reset the app's window settings manually. To do this, you'll need to delete the `requester.json` file from the app's data directory, this is located:
> 
> on macOS: `~/Library/Application\ Support/Postman`
> on Windows: `C:\Users\Postman\AppData\Roaming\Postman`
> on Linux: `~/.config/Postman`
> 
> We'll take this up soon so the manual step isn't needed.

This fixed my problem. Thank you so much!

**Comment by b-hayes** [comment]
This is happening again on MacOS Catalina with Postman Version 7.12.0

**Comment by darkcorn1997** [comment]
i deleted ‘window’ on my macos instead of ‘requester.json’， it have solved

**Comment by talr1** [comment]
happened to me on windows 10 v7.14.0
deleting the file 'window' in C:\Users\[user]\AppData\Roaming\Postman  solved the issue.

**Comment by gohalien** [comment]
Opening the window file and setting isFullScreen to false (instead of true) solved the problem

**Comment by NArnott** [comment]
This is still an issue, or became one again. It's taking up the full screen (including the Taskbar) and the Alt-Space workaround doesn't work as Restore, Size and Move are all disabled.

I'm using PostMan v7.34. I am on a laptop that sometimes is on a docking station, so screen sizes change from time to time, and I'm wondering if that's what got me into this situation. But know I can't figure out how to get it back so I can move it across screens, see the taskbar again (while using it), etc.

![image](https://user-images.githubusercontent.com/198647/95881055-642c8880-0d35-11eb-941d-30f79ab4beba.png)

**Comment by NArnott** [comment]
In case anyone else gets into this mess, it looks like F11 switches between full screen mode and normal mode (rather than manual config file edits)

**Comment by SmaugWyrm** [comment]
> This issue is happening again with Postman v7.3.4.
> 
> The old manual fixes mentioned above did not work for me, but I was able to resolve by editing C:\Users\user\AppData\Roaming\Postman\window and setting all values for "isFullScreen" to false

April 2023 and this is still(again) an issue on v10.12.11 this fix correct the problem

**Comment by astanwar99** [comment]
Experiencing same issue on Arch Gnome - Postman 10.17 in single monitor setup.

This is working though: 

> Experiencing the same issue (Win 10 multi monitor setup)
> 
> @k3davis try focusing on the postman window by _Clicking_ the icon on the **task bar** or ALT + TAB (WIN + TAB) to select.
> 
> Once focused hit ALT+ SPACE which brings up small menu Then select either **Move** or **Maximize** to adjust the window position
> 
> hope this helps :)

**Comment by alraney80** [comment]
Experiencing same issue on Windows 11 - Postman 10.24 in dual monitor setup. However, using F11 to toggle between full screen mode and normal mode fixes the issue.
