### ISSUE TITLE
Remote logout one/all sessions

### ISSUE THREAD

**Issue by dialex** [a85/POSTMan-Chrome-Extension#2993]
1. Postman Version: 4.10.7
 2. App (Chrome app or Mac app): Chrome App
 3. OS details: macOS 10.12.4 / x86-64
 4. Is the Interceptor on and enabled in the app: Off
 5. Did you encounter this recently, or has this bug always been there: Always
 6. Expected behaviour: **As a user I want to remotely logout all active due to security concerns.**

Steps to reproduce the problem:

1. Login to getpostman.com
2. Go to https://app.getpostman.com/dashboard/sessions

![screen shot 2017-05-02 at 15 24 04](https://cloud.githubusercontent.com/assets/2140450/25622343/00d839ac-2f4c-11e7-9d20-a790653292e2.png)

Services like Facebook and Google have a button per session to do a remote logout. So I was hoping Postman had one too.

I have Postman installed on my Mac and my Windows VM, so 38 active sessions seem _a bit too much_. I'm concerned, I want to close them and **I just can't!** Is there any workaround?

**Comment by a85** [comment]
Did you share your username/password with anyone?

**Comment by dialex** [comment]
Yes I did, with a friend that was helping me.

**Comment by shamasis** [comment]
Try changing your password and it should clear all older sessions.

**Comment by dialex** [comment]
​Changing my password was my first try. It did not clear the older sessions.
Notice that Postman's UI says "Your sessions remain active until you have
*manually* logged out.
​

**Comment by abhijitkane** [comment]
@dialex You can delete all sessions via https://app.getpostman.com/dashboard/sessions

**Comment by dialex** [comment]
Thanks for developing that feature, now it's just a matter of clicking the link :)
<img width="727" alt="screen shot 2017-08-20 at 14 04 58" src="https://user-images.githubusercontent.com/2140450/29495136-9b7fa23c-85b0-11e7-9242-f58b18def7c7.png">

**Comment by Sofianio** [comment]
Why is it limited to only 3 active sessions now?
