### ISSUE TITLE
AWS Signature calculated before variable substitution?

### ISSUE THREAD

**Issue by davidwallen** [a85/POSTMan-Chrome-Extension#2994]
It appears a request with variables is calculating the HMAC before the variable substitution occurs resulting in errors. Example request:

{
  "logGroupName": "test",
  "logStreamName": "test-stream",
  "sequenceToken": "49567423208377365908725071670784560352875325557011675618",
  "logEvents": [
    {
      "timestamp": {{$timestamp}}, 
      "message": "{{$guid}} Logging a sample message"
    }, 
    {
      "timestamp": {{$timestamp}}, 
      "message": "{{$guid}} They come in batches"
    }, 
    {
      "timestamp": {{$timestamp}}, 
      "message": "{{$guid}} curiously you can log in the future"
    }
  ]
}

Results in:

{
  "__type": "InvalidSignatureException",
  "message": "The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.\n\nThe Canonical String for this request should have been\n'POST\n/\n\naccept:application/json\ncontent-length:549\ncontent-type:application/x-amz-json-1.1\nhost:logs.us-east-1.amazonaws.com\nx-amz-date:20170502T164743Z\nx-amz-target:Logs_20140328.PutLogEvents\n\naccept;content-length;content-type;host;x-amz-date;x-amz-target\n03b9bed50fc6df8f4c72fe53fb299b175c06290fae92c451214049c27206cc79'\n\nThe String-to-Sign should have been\n'AWS4-HMAC-SHA256\n20170502T164733Z\n20170502/us-east-1/logs/aws4_request\n81fe990e57e33ea6a6056b678c223989edbd8117ed0e9e3fab12a0471850d87f'\n"
}

(Some content obfuscated in the response)

**Comment by harryi3t** [comment]
@davidwallen Could you provide more details?
Are you on a native app or chrome app?
Also, I don't recognise this example request JSON format

I tried the same using environment variables, and it works for me
![image](https://user-images.githubusercontent.com/5207331/30857705-6a020744-a2da-11e7-9ccb-3de75e472678.png)

Are you doing something different?
