### ISSUE TITLE
Nothing for Does not contain

### ISSUE THREAD

**Issue by anudhingra** [a85/POSTMan-Chrome-Extension#2995]
1. Postman Version: 4.10.7
 2. App (Chrome app or Mac app):
 3. OS details: Mac OSx 10.12.4
 4. Is the Interceptor on and enabled in the app:
 5. Did you encounter this recently, or has this bug always been there:
 6. Expected behaviour:
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 8. Screenshots (if applicable)

Hi,
I was wondering if there is a way in Postman to pass the test on the basis of some action.
For example, I would like to mark the test Pass/Fail if I verify that a certain value IS NOT present in the JSON response. Is that possible?
On similar lines, is there a way to write a test such that the JSON response DOES NOT have a value.
I am aware of 'Contains string'. Anything available for Doesnot contain string?

Thanks for your help.

Regards,
Anuj Dhingra.

**Comment by vegetableman** [comment]
@anudhingra 
you could use  `JSON.parse(responseBody)` and then use a lodash utility function to determine if a value is present or not. Checkout https://www.getpostman.com/docs/sandbox for more info on the supported api.

**Comment by anudhingra** [comment]
How will lodash help in my case?

**Comment by abhijitkane** [comment]
@anudhingra You can refer to standard JS docs - adding an exclamation mark before the condition will negate it: `tests["Body matches string"] = !responseBody.has("string_you_want_to_search");`

**Comment by anudhingra** [comment]
Somehow it was not giving reliable results. I had to write a simple logic around it to get the expected result.I was curious if there can be a built-in function to make life easy.

On Monday, August 14, 2017, 3:47:18 PM PDT, Abhijit Kane <notifications@github.com> wrote:


@anudhingra You can refer to standard JS docs - adding an exclamation mark before the condition will negate it: tests["Body matches string"] = !responseBody.has("string_you_want_to_search");
