### ISSUE TITLE
POSTMAN is skiping the failed assestions if the last assersion passes

### ISSUE THREAD

**Issue by paarsa** [a85/POSTMan-Chrome-Extension#2996]
Welcome to the Postman Issue tracker. Any feature requests / bug reports can be posted here.
Any security-related bugs should be reported directly to security@getpostman.com

Version/App Information:

 1. Postman Version: 4.10.7
 2. App (Chrome app or Mac app): Linux app (not sure if its also happening on other OSs)
 3. OS details: Ubuntu 14.06
 4. Is the Interceptor on and enabled in the app: No
 5. Did you encounter this recently, or has this bug always been there:
 6. Expected behaviour: Explain below(steps to repoduce)
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 8. Screenshots (if applicable)

Steps to reproduce the problem:

It seems postman ignores the failures if there is 1<= passed test after the failed assertion.
i.e:
assertion A (A=true)
assertion (B=false) (must fails the test)
assertion C (C=true)

The final outcome of the postman test must be false because B failed. But postman shows the final results as Passed(because it looks at C which was true as the last line of the test) which is wrong and the test easily ignores any bug and marks the test as successfull. 

Some guidelines: 

1. Please file Newman-related issues at https://github.com/postmanlabs/newman/issues

2. If it’s a Cloud-related issue, or you want to include personal information like your username / collection names, mail us at help@getpostman.com

3. If it’s a question (anything along the lines of “How do I … in Postman”), the answer might lie in our documentation - http://getpostman.com/docs.

**Comment by sdnts** [comment]
@paarsa This should be fixed in the latest version (5.2) when you use the PM API. Here's a [gist](https://gist.github.com/madebysid/b57985b0649d3407a7aa9de1bd327990) explaining how to use this, we will update docs soon. Please reopen if this is still happening to you.
