### ISSUE TITLE
Unable to type @ character

### ISSUE THREAD

**Issue by zetisam** [a85/POSTMan-Chrome-Extension#2998]
Postman for Chrome
Version 4.10.7
win / x86-64
Chrome 58.0.3029.96

In using Windows 10, using the nl_BE locale and an azerty keyboard.
In order to type the @ character, I need to press the [alt gr] + [2 é @ ] key.

See example of keyboard layout: 
![azerty keyboard layout](https://upload.wikimedia.org/wikipedia/commons/thumb/9/93/Belgian_keyboard_layout.png/799px-Belgian_keyboard_layout.png)

It's impossible to type this character this way in Postman (it used to be possible, don't know exactly when this has changed). Since a lot of our usernames are actually e-mail addresses, this character is very important to us.

The current workaround is to copy-paste the email address,  or type use [alt]-[64] keycombo (which I can never seem to remember)

**Comment by prashantagarwal** [comment]
Closing this, as we're tracking this here: #2707 . I'll keep that thread up-to-date.

**Comment by zetisam** [comment]
Thanks for the reference. Didn't find any issues when searching for @, seems the search engine can't really handle the character.
