### ISSUE TITLE
Generated HTTP request are encoding URLs 

### ISSUE THREAD

**Issue by udev** [a85/POSTMan-Chrome-Extension#2999]
Postman for Chrome
Version 4.10.7
OS X / x86-64
Chrome 58.0.3029.96

![image](https://i.imgur.com/GnWOOgm.png)

reproduction:
- click the "Code" button to view the curl script
- observe that the ampersands and other characters have been URL encoded

expected:
- special characters are not URL encoded unless they are key/value query paramters

This behavior is new as I've used the copy to clipboard option in that window extensively and only recently encountered this issue.

**Comment by abhijitkane** [comment]
@udev 
Can you try this is Postman 7.2.1, with the 'Experimental Codegen Mode' flag enabled in Postman's global settings? We've introduced bug-fixes, support for two new languages (JS-Fetch and Powershell), and the ability to configure certain aspects of the generated snippet.

**Comment by udev** [comment]
I haven't used Postman in a while but I'll consider it. Thanks.
