### ISSUE TITLE
Saved responses are out of order when creating an API document 

### ISSUE THREAD

**Issue by jbhandari** [a85/POSTMan-Chrome-Extension#3003]
Unless I maybe missing something, it would be nice to have a scheme to order saved responses when we generate API documentation. I have tried alpha and numbered schemes to order my saved responses but to no avail. 

 1. Postman Version:
      4.10.7
 2. App (Chrome app or Mac app):
      Mac App
 3. OS details:
      Sierra
 4. Is the Interceptor on and enabled in the app:
     no
 5. Did you encounter this recently, or has this bug always been there:
     always (i think)
 6. Expected behaviour:
     Should be in order you save it or alphanumeric ordering system. But best option would be a drag and drop or arrow button system where you can order your saved responses so it shows up as intended in generated api docs. 
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):

n/a

 8. Screenshots (if applicable)

![glatsy api - version 1 2017-05-08 23-44-17](https://cloud.githubusercontent.com/assets/6493672/25834806/487b63f0-3448-11e7-9c0e-b5a786a1463e.jpg)

Save responses. Based on the order you save them, alpha ranking, or numerical ranking...the saved responses once a API doc is generated is random. 

Thank you for taking your time to read this.

**Comment by numaanashraf** [comment]
We are tracking this at #1070. Closing this as duplicate.
