### ISSUE TITLE
Feature Request: Add setting to disable close button on tab

### ISSUE THREAD

**Issue by philmagr** [a85/POSTMan-Chrome-Extension#3005]
With many tabs click target on the X can become as much as 25% of the tab size.
This makes it difficult to quickly switch between tabs because I always need to double-check that I am not clicking on the X.

Use-Case: I just closed a tab while trying to switch to it, to see if I needed to save the request on that tab or not. Pretty sure I did, but it's gone now.

TL;DR: Accidental data loss is easy right now, can we please make it hard?

**Comment by a85** [comment]
Agree with you on the accidental data loss. We are changing this behavior pretty soon. Postman will be much more conservative in assuming that the tab can be closed. Closing this feature request in it's current form though. Lots of issues elsewhere on the tracker around tab management. Will use them for updates.

**Comment by NetVicious** [comment]
I prefer to have one option to disable the X button on the tab, because I close they with CTRL+W, or with the middle-click of the mouse.
