### ISSUE TITLE
Suggestion: Add show/hide option per collection

### ISSUE THREAD

**Issue by rmondragon** [a85/POSTMan-Chrome-Extension#3008]
Hi, usually I used the filter option to bring the collections that I need. But, now that I have too many and some that don't have anything in common, the filter is useless. 

As a suggestion, you can add show & hide option to hide 1 or many collections that I don't need and only show the ones that I need.

**Comment by a85** [comment]
Thanks for the suggestion. We are working on this idea of "Workspaces' that will let you create views on the entire set of collections. This will solve this visibility problem without having to toggle settings on each collection. Closing this for now.

**Comment by xsedlak** [comment]
Hi Asthana, do you have some progress of the feature. 
We need to hide some request/folder in the collection. 
The same functionality is implemented in the JMeter via Disable for anything. 
Thank you and best regards,
Miroslav Sedlak 

BTW: I read some threads related for the topic, see
https://github.com/postmanlabs/postman-app-support/issues/2392
https://github.com/postmanlabs/postman-app-support/issues/1467
