### ISSUE TITLE
Large response with base64 content freezing postman

### ISSUE THREAD

**Issue by syxxpk** [a85/POSTMan-Chrome-Extension#3009]
Hi,

We are calling a service that returns a pdf encoded as base64.  The call itself is quick but as soon as you scroll down to the part of the response with the base64 content it freezes the UI.  I'm on version 4.10.7 of Postman.

This wasn't happening before so I'm guessing that something changed in an update.  However even with older versions of Postman the UI would be slow for a few seconds but eventually it would become responsive again.  It seemed to me like it was trying to parse the base64 content to see if it was a http link.  I say this because sometimes if I clicked on the base64 content it would open up a new Postman tab and copy the base64 content into the url field.  

Ideally there would be a settings in Postman to turn off the url parsing.  I looked at the settings but didn't see a way to do this.

Marco

**Comment by Startouf** [comment]
I also have this issue when I try to copy paste a base64 image in an environment variable to be reused in postman API calls

**Comment by chalalo1533** [comment]
I have same problem :(

**Comment by darylpeeters** [comment]
Same problem here, it seems that it would like to interpret it as a hyperlink and at that moment it becomes almost unresponsive

**Comment by JoshKeegan** [comment]
I'm having the same problem.
Is there any fix planned?

**Comment by OneCrazyRussian** [comment]
This was remedied a little in now deprecated Chrome Apps, but in "native" ones (I can't stand calling Electron apps native) it's downright unbearable for years already. Put a long base64 or JSON string without line breaks into Postman - it hangs for minutes while thrashing its own database and your disk.

Either undeprecate Chrome apps (as they had better perf than Electron) or create a proper Native app that can handle at least up to 10mb solid strings.

**Comment by numaanashraf** [comment]
@syxxpk @Startouf @chalalo1533 @darylpeeters @JoshKeegan @OneCrazyRussian We have created a master thread #4751 to track all issues related to large responses. We would be updating that thread on possible workarounds, planned improvements and releases related to large response performance.
