### ISSUE TITLE
JSON response URL with ampersand in gets incorrectly encoded to &amp; after clicking link

### ISSUE THREAD

**Issue by kevinbe71** [a85/POSTMan-Chrome-Extension#301]
For example, when the JSON response (in the "pretty" view) contains output like the following:

{
    "data": [
        {
            "id": 6,
...
        },
        {
            "id": 7,
...
        }
    ],
    "count": 7,
    "responseCode": 200,
    "links": {
        "previous": {
            "href": "http://localhost/app/api/v1/resource/?start=2&limit=2"
        },
        "next": {
            "href": "http://localhost/app/api/v1/resource/?start=6&limit=2"
        }
    }
}

clicking on the link brings up:
http://localhost/app/api/v1/resource/?start=6&amp;limit=2

Notice how the & was converted to &amp; which isn't correct.

**Comment by nuriyevn** [comment]
For some reason , I have the situation when response comes to me as 
```
<RSP request='Deposit' rc='0'>
    <RESULTS Provider='' ProviderRef='' RedirectUrl='https://example.com/p/purchase?site_id=134&amp;id=1234' Reference='1141'/>
</RSP>
```

instead of just

```
<RSP request='Deposit' rc='0'>
    <RESULTS Provider='' ProviderRef='' RedirectUrl='https://example.com/p/purchase?site_id=134&id=1234' Reference='1141'/>
</RSP>

```

So, '&'   is converted to '&amp;'   while in browser I do not see convertation.
