### ISSUE TITLE
New Window doesn't reflect Team Activity

### ISSUE THREAD

**Issue by fossterer** [a85/POSTMan-Chrome-Extension#3010]
1. Postman Version: 4.9.3
 2. App (Chrome app or Mac app): Postman for Linux
 3. OS details: linux 4.4.0-77-generic / x64
 4. Is the Interceptor on and enabled in the app: No clue
 5. Did you encounter this recently, or has this bug always been there: Recent
 6. Expected behaviour: Opening a "New Window" in Postman shouldn't be any different than opening it for the first time
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 8. Screenshots (if applicable)

Steps to reproduce the problem:
1. Use the 'New Window' button inside Postman
2. Confirm that the sync status says - 'In Sync'
3. From the new window, observe the results of these actions:

 - 'Team Library > Team Collections" does not show synced collections and
 - "Team Activity > Activity Feed" does not reflect **all** the activity in the team

**Comment by a85** [comment]
This should be fixed now with the new workspaces release in 6.0+
