### ISSUE TITLE
Unable to import collections

### ISSUE THREAD

**Issue by okjim3GH** [a85/POSTMan-Chrome-Extension#3012]
Whenever I try to import a collection via a link I get this error:
"Failed to import data: format not recognized"
The Chrome Developer Tools console window says:
"Not parseable "YAML"
Postman for Chrome
Version 4.10.7
win / x86-64
Chrome 58.0.3029.96
This is an example link that fails:
https://www.getpostman.com/collections/a0715a8730540e86b569
What I get back is not the collection file I requested but an html page generated in house:
![image](https://cloud.githubusercontent.com/assets/1092820/25917462/2054e122-3596-11e7-9a3e-3d2bf3d61ff3.png)
Is there anything I can do to avoid this? Are collections files available else where or in another format?

**Comment by czardoz** [comment]
Looks like your institution firewall needs to be configured to allow Postman collection links. You'll have to talk to your network administrator to do this, Postman cannot work around this issue :)

**Comment by okjim3GH** [comment]
I can download a .postman_collection file. I just can't work with the URLs that end without filename/extension. Is there any way to transform a link like this: https://www.getpostman.com/collections/a0715a8730540e86b569 into something that ends in .postman_collection?

**Comment by abhijitkane** [comment]
@okjim3GH You'll need to look at third party services that offer this. Postman doesn't support customized URLs for collections.
