### ISSUE TITLE
Favicon support for postman API documentation feature

### ISSUE THREAD

**Issue by ewilde** [a85/POSTMan-Chrome-Extension#3014]
On the [team edit page](https://app.getpostman.com/dashboard/teams/edit) where you can customize the domain, team logo and name.

Allow customers to specify a 'favicon' for the documentation api site

**Comment by shamasis** [comment]
Marking this as a feature request.

**Comment by a85** [comment]
Closing as a duplicate of https://github.com/postmanlabs/postman-app-support/issues/2719. Will be out in public docs soon!

**Comment by mjaverto** [comment]
@a85 is this live? I also have a pro account and am not seeing where I can upload this?
