### ISSUE TITLE
ZIP output not opens "Save as" dialog, but displays the binary content in the body

### ISSUE THREAD

**Issue by butlnor** [a85/POSTMan-Chrome-Extension#3015]
When REST method responds with "application/zip" for "Content-Type" header, Postman will display the ZIP's binary content inside the body area, without any option to save this content to a file (or I don't find such a button). 

I have tried some other REST methods that return PDF, "application/pdf", and those properly open "Save as" dialog to save the content to a file.

I would suggest for Postman to open "Save as" dialog also for ZIP, as having textual representation of a binary content is useless. Unless Postman displays the binary data as hex values in columns (like hex editors do)

**Comment by butlnor** [comment]
You marked this as a "support", although I think this is a "missing crucial functionality". 
If this is really a support, can you please tell me, where to find a "save as file" button for binary content, which is now rather displayed inline as a "corrupted text"?

**Comment by numaanashraf** [comment]
Hi @butlnor Have you tried `Send and Download`?

<img width="294" alt="screen shot 2017-06-02 at 2 56 27 pm" src="https://cloud.githubusercontent.com/assets/3295568/26719883/d4d482e6-47a3-11e7-9959-eef99b7c8dfb.png">

**Comment by butlnor** [comment]
Wow, I wasn't aware of that. Thanks.

Still, it might be good to have the similar behavior for "ZIP" as you already have for PDF, which automatically opens the "save as dialog".
