### ISSUE TITLE
Auto refresh digest headers

### ISSUE THREAD

**Issue by marawan31** [a85/POSTMan-Chrome-Extension#3017]
This is more of a feature request.

What I suggest is simply sending a request to the server and if the server returns 401 with digest we simply add the nonce and other header fields and send a new request with the username and password added.
Right now we need to send a first request then wait to receive 401 then manually update the nonce and other stuff in the authorization tab and send the request again.
 
Thanks

**Comment by harryi3t** [comment]
duplicate of https://github.com/postmanlabs/postman-app-support/issues/808

**Comment by sdnts** [comment]
Closing in favour of https://github.com/postmanlabs/postman-app-support/issues/808 :)
