### ISSUE TITLE
Collection Runner window does not display

### ISSUE THREAD

**Issue by wierzba3** [a85/POSTMan-Chrome-Extension#3018]
1. Postman Version: v4.10.7
 2. App (Chrome app or Mac app):  Windows
 3. OS details: Windows 10 Enterprise
 4. Is the Interceptor on and enabled in the app: I don't know what this is
 5. Did you encounter this recently, or has this bug always been there: Recently
 6. Expected behaviour: The test runner window should display
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 8. Screenshots (if applicable)

Steps to reproduce the problem:
1. I open collapsible details window using the ">" button on one of my collections.
2. I select "Run"
3. The window does not display. I see on my taskbar that the collection runner window exists, but when I try to open it (by clicking on it in the taskbar) it does not open.

update:

I've tried:

1. Closing the app ( and looking for any orphan processes but did not find any) and it did not help.
2. Restarting my computer and it did not help. 
3. Uninstalling and reinstalling the app, and it did not help

It was working yesterday and I cannot think of anything that could have caused this. This is probably goin got make it difficult to replicate.

**The last operation that I performed that I can recall was to drag-and-drop a request from one collection to another.**

**Comment by sdnts** [comment]
Hi @wierzba3! Did you have an external monitor connected when you last opened the Runner? We've been investigating #2992 which might be what you're seeing as well. 

Basically, if you opened the Runner on the second monitor, then close the app, disconnect the Monitor and open the Runner again, it "opens" on the new monitor, but you can't see it. Can you visit that link and make sure that is not what you're seeing as well?

**Comment by wierzba3** [comment]
The scenario you described is not my situation. I do have 2 monitors, however, I'm running a windows server 2012 VM through hyper-v hosted on a windows 10 machine. The VM is full screen mode on one monitor.

I went to the link and tried what they suggested, maximizing the collection runner window from the taskbar, and it worked . I can access the window now

**Comment by sdnts** [comment]
I'm guessing this i related to the monitor window positioning, so I'm closing this. We'll release a fix for #2992 with a coming release and I'll update that ticket. Please feel free to re-open this if that does not fix your issue as well.

**Comment by thecuriousdev** [comment]
The issue got fixed in **PostmanCanary 5.6.0-canary01**

get the build from https://www.getpostman.com/canary
