### ISSUE TITLE
response in xml or json option

### ISSUE THREAD

**Issue by niksworld22** [a85/POSTMan-Chrome-Extension#3020]
if we can have response in desired format i mean choice of getting response in like json or xml or any other format

**Comment by sdnts** [comment]
Hi @niksworld22 I don't think I understand. Are you talking about formatting the response as JSON / XML?
Can you attach a screenshot explaining what issue you're facing?

**Comment by niksworld22** [comment]
yes, actually i don't have issue but i want to suggest a option to get
response in desired format

json
xml

**Comment by sdnts** [comment]
The response format would be dictated by the server you use. You can try to format it as JSON or XML by using the dropdown right above the response section.
Please reopen if I misunderstood.
