### ISSUE TITLE
Postman Chrome app is crashing randomly

### ISSUE THREAD

**Issue by ocallm1** [a85/POSTMan-Chrome-Extension#3021]
1. Postman Version: 4.10.7
 2. App (Chrome app or Mac app): Chrome App
 3. OS details: win / x86-32
 4. Is the Interceptor on and enabled in the app: yes
 5. Did you encounter this recently, or has this bug always been there: recently
 6. Expected behaviour: not randomly crashing
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 8. Screenshots (if applicable)

**Comment by prashantagarwal** [comment]
@ocallm1 Can you switch to our Postman native apps and see if you are still facing the same issue.

**Comment by ocallm1** [comment]
thanks I've updated and haven't seen the problem again locally! It was with a tab I think that threw an error and I had maybe 50 tabs open, I think closing them all fixed it too!
