### ISSUE TITLE
Export multiple separated collections 

### ISSUE THREAD

**Issue by youyou82** [a85/POSTMan-Chrome-Extension#3022]
1. Postman Version: v4.10.7
 2. App (Chrome app or Mac app): Chrome app
 3. OS details: Windows 7 Pro
 5. Did you encounter this recently, or has this bug always been there: Always there
 6. Expected behaviour: Be able to export multiple separated collections

Description: today we can only export on single collection or a collection containing several collections but we are not able to export several separated collections. 
To do so, we need to export our collections one by one which is time consuming. 

Proposition: 
- Enhance the application by adding a new feature "Export" into the collection menu and an Export tab. 
- Short term solution: 
When clicking on one of those two features, the user will be able to select multiple separated collections and export them. The result will be as many collection as selected by the user.
- Long term solution: 
When clicking on one of those two features, the user will be able to select multiple collections (whatever there are separated or part of one collection). 
The final result could be choosen by the user (all grouped in one collection or as many collections as selected by the user)

![image](https://cloud.githubusercontent.com/assets/28593427/26003513/339b3b02-3733-11e7-93c5-21b751ae8a37.png)
![image](https://cloud.githubusercontent.com/assets/28593427/26003571/5a7102ac-3733-11e7-9c26-93fddc5ff383.png)

**Comment by a85** [comment]
Sorry but this is not on our roadmap right now. We will review bulk export/import options in the context of Workspaces.

**Comment by afayes** [comment]
I need that bulk export all collections feature too!

**Comment by cassioconti** [comment]
Since this feature is not available, my workaround for now is creating folders inside a collection. Then I keep only one collection. By the way, drag-and-drop works for moving the saved requests.

**Comment by jfavaron** [comment]
@cassioconti thanks for the tip, good call

**Comment by bt-dd** [comment]
I noticed that the ability to export by Workspace would be possible by recursively calling the Postman API. Made a quick console app to dump Collections/Environments into folders, organized by Workspace.

A little rough around the edges, but here it is for anyone wanting to check it out - https://github.com/bt-dd/Postman_WorkSpace_Downloader

**Comment by allenrcochran1** [comment]
> I noticed that the ability to export by Workspace would be possible by recursively calling the Postman API. Made a quick console app to dump Collections/Environments into folders, organized by Workspace.
> 
> A little rough around the edges, but here it is for anyone wanting to check it out - https://github.com/bt-dd/Postman_WorkSpace_Downloader

I got as far as downloading your tool, then found this in Postman:

![image](https://user-images.githubusercontent.com/43894877/48163166-8e9d7d80-e2a4-11e8-995a-63bd9de97ecc.png)

**Comment by bt-dd** [comment]
@allenrcochran1 - I ran across that option in settings as well. Issue is, it exports the data flattened. So, when you go to import elsewhere it won't organize things by workspace. All your collections/environments from various workspaces will be imported into the single workspace you are currently under the context of on new account.

If that isn't a deal breaker though, it works fine.

**Comment by allenrcochran1** [comment]
Ah, got it. Thanks for the clarification.
