### ISSUE TITLE
GUI no longer accessible on Mac

### ISSUE THREAD

**Issue by JonFranchi** [a85/POSTMan-Chrome-Extension#3023]
I'm not able to access postman any longer.  It loads, but I can never get to the GUI to use it.  I've uninstalled multiple times and rolled back to previous versions.  It is possible, though I can't be certain, that this happened after I upgraded to macOS Sierra.  

 1. Postman Version: **4.10.7, 4.10.6, 4.10.5** -- I tried uninstalling and reverting to previous versions to find a working one.
 2. App (Chrome app or Mac app): **Mac**
 3. OS details: **10.12.4 Sierra**
 4. Is the Interceptor on and enabled in the app: n/a - **cant access app any longer**
 5. Did you encounter this recently, or has this bug always been there: **Appeared a couple weeks ago.**
 6. Expected behaviour: **Being able to see the application.**
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app): **N/A, can't get into App.**
 8. Screenshots (if applicable)
**The below screenshot shows what happens when I right click the Postman logo and choose 'show all windows', then move the cursor up.  It shows as if some application is there, indicated by the blue outline as I mouse over, but clicking it simply reverts to desktop.**
![image](https://cloud.githubusercontent.com/assets/10428021/26006031/9a8c3754-3700-11e7-852d-ed82d6880bc8.png)

**Comment by JonFranchi** [comment]
I was able to resolve this for myself by looking further into the application while it was running.  I saw that it was accessing files in user/library/application_support/postman, so I deleted that folder and restarted postman.  It loaded immediately.

**Comment by vegetableman** [comment]
@JonFranchi

**Comment by vegetableman** [comment]
@JonFranchi We are not able to reproduce this issue. Do you happen to use a multi-monitor setup?.

**Comment by JonFranchi** [comment]
I do not.  I tried a few changes of desktop resolution though during my troubleshooting.

**Comment by JonFranchi** [comment]
I apologize, but my solution was to delete the entire application_support/postman folder.  In retrospect I should have tried to narrow down the specific file causing the issue so it could be further investigated.
