### ISSUE TITLE
Runner tries to validate SSL certificates even though toggled off from settings

### ISSUE THREAD

**Issue by alia-a** [a85/POSTMan-Chrome-Extension#3025]
Version/App Information:

 1. Postman Version: Version 4.10.7
 2. App (Chrome app or Mac app): Windows native (Chrome?)
 3. OS details: Windows 8
 4. Is the Interceptor on and enabled in the app: no, afaik
 5. Did you encounter this recently, or has this bug always been there: -
 6. Expected behaviour: Run a collection successfully on a HTTPS-server with self-signed SSL certificates

Steps to reproduce the problem:

1. Have a HTTPS server with self-signed SSL certificates
2. Set the certification validation off from Settings->General
3. Verify the request runs fine when run alone from Postman
4. Try to run the same request from Runner
5. Observe SSL verification error ("SSL Error: DEPTH_ZERO_SELF_SIGNED_CERT")

**Comment by sdnts** [comment]
Hi @alia-a I tried doing this, and was unable to get a response from the Runner as well. Can you try restarting the Runner after switching off SSL certificate verification?

**Comment by alia-a** [comment]
Restarting the runner (well, I restarted whole Postman) helped indeed.

**Comment by sdnts** [comment]
Ah, awesome. Looks like settings aren't being propagated across windows. I'll take a look at this.

**Comment by jayanthktn** [comment]
I am latest update. i am not able to access the API. keep on displays, ssl certificate issue. really horrible. but its not displaying in Chrome extension. only displaying in Windows application.
![postman](https://user-images.githubusercontent.com/27004220/28511463-f0071dea-706a-11e7-83a8-614eea51d4f7.PNG)

**Comment by clarkeb** [comment]
Currently having this same problem in postman v5.3.0, Windows native client.

**Comment by samuelt1** [comment]
I am having the same problem on the mac app. v5.5.0

**Comment by sivcan** [comment]
@jayanthktn @clarkeb Are you guys still facing this issue on the latest version of the postman app viz v6.1.4?

Note: If you toggle SSL in the settings then you need to close the runner window and relaunch it for the SSL settings to be applied. 

Let us know if you're still facing this.

**Comment by dderjoel** [comment]
I can confirm that until restarting the Runner, the settings are not propagated.
Postman version 6.5.2, OS: Windows 10
