### ISSUE TITLE
Activity, Click to Expand,  The page can not scroll

### ISSUE THREAD

**Issue by iugo** [a85/POSTMan-Chrome-Extension#3026]
1. Postman Version:
4.10.7

 2. App (Chrome app or Mac app):
Chrome app

 3. OS details:
macOS 10.12.4

 4. Is the Interceptor on and enabled in the app:
Yes

 5. Did you encounter this recently, or has this bug always been there:
Yes

 6. Expected behaviour:
If the content is too long, you can scroll the page.

 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 8. Screenshots (if applicable)

Steps to reproduce the problem:

1. Collection
2. Activity
3. Click to Expand
4. The page can not scroll

**Comment by sdnts** [comment]
Hi @iugo, we're aware of this, and a fix will be out with the next version. I'll let you know here 
when it is out!

**Comment by numaanashraf** [comment]
@iugo This is fixed in latest version 4.11.0.
