### ISSUE TITLE
Set folder's visibility for public documentation 

### ISSUE THREAD

**Issue by jormaechea** [a85/POSTMan-Chrome-Extension#3028]
I started publishing collections documentation from Postman, but I realized that I have in the same collection some folders with public endpoints, and some with private ones.. 

It would be nice to be able to set some folders as private, so I don't have to split my all my pub+pvt collections, and avoid managing team access permissions twice.

**Comment by a85** [comment]
Sorry but this is not on our roadmap right now. You'd have to separate them manually. Hiding folders/requests has several issues around data export and other effects. We are improving our permission models at several levels and will keep posting updates on our blog + the roadmap.
