### ISSUE TITLE
Error with AWS Signature in Postman native app in Ubuntu

### ISSUE THREAD

**Issue by canhnht** [a85/POSTMan-Chrome-Extension#3029]
I got error when trying AWS Signature in Postman native app in Ubuntu. It seems like AWS Signature issue has been resolved in #1663. I don't know what I did wrong. Hope someone can help.
Thanks in advance.

 1. Postman Version: 4.10.7
 2. App (Chrome app or Mac app): Ubuntu app
 3. OS details: Ubuntu 16.04
 4. Is the Interceptor on and enabled in the app: No
 5. Did you encounter this recently, or has this bug always been there: I just encountered this issue recently
 6. Expected behaviour: 200 OK response is returned

**Comment by canhnht** [comment]
When I try requesting from mobile app (I use Mobile Hub sample app), it works fine. I still don't know why it failed in Postman?

**Comment by canhnht** [comment]
Hi @kamalaknn , what do you think about this issue?

**Comment by kamalaknn** [comment]
Hi @canhnht 

From the screenshots it looks like the `Authorization` signature in the header was generated incorrectly, but we may need more context to find the issue.

I am tagging @czardoz here, who can help you out better.

**Comment by czardoz** [comment]
@canhnht can you ensure that there's no saved authorization header present in the request? Also, this can happen when there's a time lag between your system time and the AWS servers.

**Comment by canhnht** [comment]
I just tried again IAM authorization without Session Token and it worked fine. Maybe my system time was lag behind the AWS servers.
I think this issue can be closed. Thanks a lot for your support.
