### ISSUE TITLE
[Feature Request] Ability to modify environment variable in tooltip when hovering over a variable in input field

### ISSUE THREAD

**Issue by jonfk** [a85/POSTMan-Chrome-Extension#3030]
1. Postman Version: 4.10.7
 2. App (Chrome app or Mac app):
 3. OS details:OS X / x86-64
 8. Screenshots (if applicable)
![screen shot 2017-05-15 at 4 07 58 pm](https://cloud.githubusercontent.com/assets/1024688/26077210/4dc429aa-3989-11e7-8e24-63cf7685da08.png)

When running requests interactively through postman, We often need to modify some environment variables between requests. Currently the only way I am aware of modifying the environment variable is through the "Manage Environments" panel.

It would make that workflow more efficient if we could modify the environment variable in the tooltip that appears when hovering on a variable in the input field.

**Comment by skatikia** [comment]
@jonfk I'm 7 years late to this thread, but I come with good news! 🙌🏾

With Postman **V11.14**, we have rolled out multiple improvements to our variables interface, including **the ability to update variable values on the go**.

![edit-value](https://github.com/user-attachments/assets/45aed08c-2982-47e2-9833-d30ddf2e1e3e)

I hope you like this change as much as we do! Update your app to start working with this change and many more, and let us know what you feel ([over a call](https://calendly.com/shobhit-katikia/meet-with-shobhit) or just drop an email to [shobhit.katikia@postman.com](mailto:shobhit.katikia@postman.com)).

[Check out the Postman V11.14 release note](https://arc.net/l/quote/vtemyulc)
