### ISSUE TITLE
Postman responding super slow - chrome app and windows app 

### ISSUE THREAD

**Issue by sharduul** [a85/POSTMan-Chrome-Extension#3031]
1. Postman Version: 4.10.7
 2. App (Chrome app or Mac app): Chrome app, Windows app 32bit/64bit
 3. OS details: Windows 10
 4. Is the Interceptor on and enabled in the app: No (not installed)
 5. Did you encounter this recently, or has this bug always been there: Always there for me
 6. Expected behaviour: Should be responsive
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):

![2](https://cloud.githubusercontent.com/assets/4227876/26080173/5abaafb2-3993-11e7-9b00-23952de25016.PNG)

 8. Screenshots (if applicable)

![1](https://cloud.githubusercontent.com/assets/4227876/26079984/a9baa758-3992-11e7-946c-a991a9ea2717.PNG)

It's hung there for past 15 mins. 
Even when the app starts it hangs for couple of minutes before a request is loaded.

**Comment by SamvelRaja** [comment]
@sharduul  Thanks for bringing this to our notice, can you provide me your **Chrome version** and also the expanded log of `Could not load DB` EVENT object?
This helps us to debug much faster.

**Comment by sharduul** [comment]
I found the solution. The problem was on my end.
Due to duplicating the requests, some of my GET requests had got body from the POST requests. When I inspected the JSON, I realized those body objects had added thousand's of line per GET request. Therefore, importing such garbage data on some other machine would make the POSTMAN slow.

Thanks for the response though.

**Comment by kvnapavl** [comment]
@sharduul What method(s) did you use to test view the body in the POST request?
