### ISSUE TITLE
Create common javascript function to reference? Or include js file?

### ISSUE THREAD

**Issue by wierzba3** [a85/POSTMan-Chrome-Extension#3032]
I have a common block of code to do some parsing that I use in many postman test scripts verbatim.
Is there any way I can place this function in a central location and reference it from my tests, instead of copy + pasting over and over?
This is using the postman for windows desktop application.

**Comment by JamesMessinger** [comment]
@wierzba3 - See [this blog post](http://blog.getpostman.com/2017/07/28/api-testing-tips-from-a-postman-professional/), specifically, Tip #5, which shows how to reuse code across multiple requests

**Comment by a85** [comment]
Postman with 5.4+ now supports collection and folder level scripts which will eliminate duplication across requests. We are working on a plug-in framework that will help deal with external dependencies. Will be part of a separate initiative.
