### ISSUE TITLE
[Bug] - Environment Variables saved in Pre-request Script are listed alphabetically

### ISSUE THREAD

**Issue by Faz540** [a85/POSTMan-Chrome-Extension#3034]
Found a minor bug, but thought I'd raise it so you're aware.

I'm using the Windows Native client, 64 bit (Windows 10)

**Bug:**
Environment Variables declared under the 'Pre-Request Script' tab are shown under the Environment alphabetically, rather than the order they were declared.

**See Below Example Pre-Request Script:**
![image](https://cloud.githubusercontent.com/assets/9334128/26104227/b7c496d6-3a34-11e7-9d92-679e4ae01af8.png)

![image](https://cloud.githubusercontent.com/assets/9334128/26104243/d1faaf9a-3a34-11e7-9212-75ef968738db.png)

If I move the code from the 'Pre-Request Script' tab to the 'Tests' tab and hit Run again, then the variables are shown correctly under the Environment:
![image](https://cloud.githubusercontent.com/assets/9334128/26104355/6bfefd62-3a35-11e7-80e3-504511d0c4d7.png)

**Comment by SamvelRaja** [comment]
Thanks for bringing this to our notice. Will keep the thread updated once it is fixed from out end.

**Comment by kamalaknn** [comment]
Hi @Faz540 

The environment viewer serves the purpose of inspecting the _values_ of environment/global variables. However the order in which they are displayed is not guaranteed and should not be relied upon.

We hope that this does not affect any of your workflows as such. Feel free to let us know if there is something we are missing.
