### ISSUE TITLE
Event property "disabled" is dead feature.

### ISSUE THREAD

**Issue by urosjarc** [a85/POSTMan-Chrome-Extension#3035]
When I put [disabled property in my event](http://schema.getpostman.com/json/collection/v2.0.0/docs/index.html) they are not applied:
```
[
  { listen: 'test', script: [Object], disabled: true },
  { listen: 'prerequest', script: [Object], disabled: true }
]
```

When I import my collection and then export I can't see "disabled" on the same event that should be.
Postman should pass those events where disabled is on...

**Comment by kunagpal** [comment]
@urosjarc This is meant to be supported in the near future, but isn't right now.
