### ISSUE TITLE
Binary file request body not working in generated code

### ISSUE THREAD

**Issue by jcampbell05** [a85/POSTMan-Chrome-Extension#3036]
1. Postman Version:
4.8.1

 2. App (Chrome app or Mac app):
Mac App

 3. OS details:
OS X Sierra

 4. Is the Interceptor on and enabled in the app:
No

 5. Did you encounter this recently, or has this bug always been there:
Recently

 6. Expected behaviour:
When I do post request with raw file, the content should be in the POST BODY.

 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):

 8. Screenshots (if applicable)
Setup POST request to send raw file. Notice no file is sent

**Comment by numaanashraf** [comment]
@jcampbell05 Thanks for reporting this. Could you update to the latest version (v4.10.7) and let us know if you are still facing this issue?

**Comment by jcampbell05** [comment]
@numaanashraf cool the new one has fixed it :) but the code examples are wrong they lack the lines of code / command line arguments to send the contents of the file.

**Comment by jcampbell05** [comment]
Suddenly started happening again, not sure why.

**Comment by Otoris** [comment]
Windows 10 x64 and MacOS 10.12.5 both exhibit this behavior. Could be permission related to file uploads? However, I get this on older versions as well.

**Comment by jcampbell05** [comment]
One thing I've noticed is it doesn't seem to happen on servers and netcat running on the local machine.

**Comment by Cethy** [comment]
Still broken ...
macOS@10.11.6 + postman@6.3.0

> When I do post request with raw file, the content should be in the POST BODY.

Using "body/binary", selecting a file ; sending or code generation never uses/displays `--data-binary "@FILE_PATH"` (but multipart work correctly).

**Comment by a85** [comment]
Closing as we have changed the underlying code generation libraries.

**Comment by nobi1007** [comment]
@a85 still, when we upload a file via binary it works fine, but in the generated code it just says `payload = 'file contents here'`. Can, you please elaborate or at least provide some sample of the required contents would be appreciable. 

Also, I went through the `code_gen` library but in the code too I couldn't find any description about it. Everywhere it is just written that if a type is file then return `'file contents here'`.
