### ISSUE TITLE
POST request on postman client returns HTML instead of JSON 

### ISSUE THREAD

**Issue by jeson114** [a85/POSTMan-Chrome-Extension#3037]
1. Postman Version:4.10.7
 2. App (Chrome app or Mac app):Chrome App on Mac
 3. OS details:macOS sierra 10.12.3
 4. Is the Interceptor on and enabled in the app: don't know
 5. Did you encounter this recently, or has this bug always been there:Recently encountered
 6. Expected behaviour: should return JSON instead of HTML
 

I sent name and pass with Content-Type: application/x-www-form-urlencoded .
and the same request works in curl on the terminal , also works with another client called Advanced Rest Client

**Comment by kamalaknn** [comment]
Hi @jeson114 

We are trying to reproduce the issue. Could you try the same request on `https://postman-echo.com` and share the steps to reproduce this?

If you could attach screenshots of the app with the response you get, it will be very helpful for us. You can mask your sensitive data in it though.

Thanks!

**Comment by jeson114** [comment]
Ah .  i figured it out . There was some server config issue . Some Drupal module was being intrusive and causing some sort of redirection during preflight . It's fixed . will close this now
