### ISSUE TITLE
Is there any way I could save my Request and Response while using collection runner?

### ISSUE THREAD

**Issue by ghost** [a85/POSTMan-Chrome-Extension#3038]
Version : 4.10.7
Chrome Version : 58.0.3029.110

Is there any way I could save my Request and Response while using collection runner individually?

Thanks in Advance!!

**Comment by kamalaknn** [comment]
@Balaji1294 

I don't think there is an option now to save a request or a response from the Collection Runner runs.

Could you elaborate more on your scenario where you need to save requests/responses from the runner?

However you can still save responses into requests from the Builder. There is also a new feature in works that allows you to create example responses on your own. More details on example response [here](http://blog.getpostman.com/2017/05/17/mock-responses-in-postman-by-using-examples/).

Cheers.

**Comment by ghost** [comment]
Hi Kamal,

I wanted to store the Response for each request individually, say I run it for 50 iterations I want all the responses to be stored in a file.

Now that it is not available, I will find an alternate.

Thanks!!
