### ISSUE TITLE
Parenthesis inconsistency

### ISSUE THREAD

**Issue by kwstoikonomou** [a85/POSTMan-Chrome-Extension#3039]
1. Postman Version: 4.10.7
 2. App (Chrome app or Mac app): Windows/Chrome
 3. OS details: Windows 10
 4. Is the Interceptor on and enabled in the app: No
 5. Did you encounter this recently, or has this bug always been there: Do not know, i think the 2nd
 6. Expected behaviour: Consistency of Encoding parethensis across apps

Reproduce:
Send a requet to a url that includes parenthesis. 

The chrome app will not encode the parenthesis (i think this is preferable)
The windows app will encode parenthesis as %28, %29.

This is inconsistent and i think it should change, although in most cases it should not cause any problems. 
In order to figure this out it had to be combined with another bug (not Postman's though). 
My ASP .NET threw a hissy fit when i tried to send an OData request with encoded parenthesis and had to watch the request logs to understand that the problematic requests where being sent this way.

**Comment by ili101** [comment]
Thank you @kwstoikonomou 
I'm facing the same problem.
I tried to use Postman to send an API request and was getting a "syntax error", To see the problem I then used Postmen for windows "PROXY" option and sent the request to it, the parenthesis was encoded to %28 and %29 so the request was failing.
I then did the same thing on the Chrome version the () was not encoded and the API worked.

Please make the Windows version behave like the Chrome version so I will be able to use it.
Thank you

**Comment by takuy** [comment]
agree, this makes Postman unusable on Windows.

**Comment by p3l** [comment]
@kamalaknn tagged this issue with "needs-investigation".
Is there anything we could do to help with that?

**Comment by SamvelRaja** [comment]
We are following a master thread #4555 to track all issues related to Url encoding. Please follow that issue for updates.

**Comment by codenirvana** [comment]
This is fixed in the latest version of the Postman app (v7.20.0) by enabling the "Use next generation URL processing" setting as mentioned in #8154.
