### ISSUE TITLE
Upgrade electron version of Postman

### ISSUE THREAD

**Issue by clement-escolano** [a85/POSTMan-Chrome-Extension#3040]
1. Postman Version: 4.10.7
 2. App (Chrome app or Mac app): Mac
 3. OS details: macOS Sierra
 4. Is the Interceptor on and enabled in the app: Don't know
 5. Did you encounter this recently, or has this bug always been there: Always
 6. Expected behaviour: Postman should be able to run await / async function
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app): 
 8. Screenshots (if applicable) : https://i.imgur.com/JCOBBo8.png

I encountered the problem faced in the issue #1038 and tried a solution with promises and await / async function. It is not working however because the await / async support in chrome is recent. It is not so recent though and latest version of electron support it (1.6 and above). Is it possible to upgrade the version of electron used by Postman ? 

Thank you

**Comment by numaanashraf** [comment]
@clement-escolano Thanks for reporting this. Requests and script execution runs in a node environment in Postman native apps and async/await needs Node v7.6.0+ which is currently available only in a pre-release version of Electron (v1.7.0+). Furthermore, we aim for parity of node versions across our entire product offering for uniformity. We will take this up after async/await support lands on stable & LTS channels in Node & Electron.

**Comment by clement-escolano** [comment]
@numaanashraf Ok thank you for your answer. Looking forward to this ! 😄
