### ISSUE TITLE
Feature request: version control for collections and environments

### ISSUE THREAD

**Issue by floorn** [a85/POSTMan-Chrome-Extension#3041]
For my current project, I am using Postman for internal testing. 

Since I am working on this project with a collegue, we share collections and environments via git. If I pull a new commit from my collegue, I need to import collections manually before I can start working. 

I think it would be very useful if Postman can use version control in the future. 

Kind regards, Floor

**Comment by vegetableman** [comment]
@floorn Adding full support for version-control (Example: tagging) is part of the roadmap. For now, you could share your collections with your colleague by adding him/her to a team to keep the collections and environments in sync. Also, you could restore a particular collection to the previous state through the activity feed of a collection. 
References:
https://www.getpostman.com/docs/postman/team_library/sharing
https://www.getpostman.com/docs/postman/team_library/activity_feed_and_restoring_collections

**Comment by floorn** [comment]
@vegetableman Thank you for your response! It is nice to hear that this feature is part of the roadmap. Also thanks for the additional references. 

Kind regards, Floor

**Comment by agseco** [comment]
I'm looking forward to this feature.

IMHO it could be as simple as this: when you import a collection into Postman you can choose either to store it in the Postman App (as it works now) or just work with it right from its original location.

If you chose the latter and you have your collection file under version control, it will be constantly synched as you work with it, thus avoiding the current pain of importing/exporting the collection.

**Comment by a85** [comment]
Postman supports git based workflows through export/import of JSON or through the API. For Pro users, you can directly export to Github repos. Collection files distributed across multiple sources quickly get out of sync or have to be manually updated.

**Comment by vkaegis** [comment]
Hey guys! We've made an RFC to document our ideas on version control in Postman, would love your thoughts and feedback on it:

https://community.getpostman.com/t/version-control/2715
