### ISSUE TITLE
Do not show the old response body, if the response body of the new request is empty

### ISSUE THREAD

**Issue by AlexByte** [a85/POSTMan-Chrome-Extension#3043]
If I change the request, press Send and get 404, 204 or any other mute response body, then the body of the last answer with the nonempty body is displayed.
It's confusing

**Comment by sdnts** [comment]
@AlexByte I think you're seeing the same issue as #2950. If so, that's a bug and we'll be releasing a fix in the next version. Please feel free to reopen this if this is a separate issue.
