### ISSUE TITLE
How to use the pm object from sandbox

### ISSUE THREAD

**Issue by tariqghalib** [a85/POSTMan-Chrome-Extension#3044]
Description:
How can we use the pm.* APIs. There is no guide and using it directly results in ReferenceError: pm is not defined.

Version/App Information:
-->
 1. Postman Version: **Version 4.10.7 / win32 6.1.7601 / x64**
 2. App (Chrome app or Mac app): Windows
 3. OS details: Windows 7 Professional
 4. Is the Interceptor on and enabled in the app: Yes
 5. Did you encounter this recently, or has this bug always been there: recently
 6. Expected behaviour: Have some guides for the new sandbox features
 7. Screenshots (if applicable)
![image](https://cloud.githubusercontent.com/assets/1693324/26208788/002ae634-3bb9-11e7-96d1-7d9e1aabe9df.png)
![image](https://cloud.githubusercontent.com/assets/1693324/26208846/1a0b5fa2-3bb9-11e7-9cac-0a6d96924396.png)

**STEPS:**
I am simply trying something like this:
console.log( pm.info);
This generates an error:
There was an error in evaluating the test script:  ReferenceError: pm is not defined

**Comment by shamasis** [comment]
This has not hit production yet. If you want to try it out, let me know over Slack or email. Our slack community details are at www.getpostman.com/community

Canary build of Postman can be downloaded by following the links provided at the end of this blog post http://blog.getpostman.com/2016/11/22/postmans-new-collection-runner/
This runs parallel to main postman app and experimental/latest beta releases are put here first.
