### ISSUE TITLE
Runner Rest output result

### ISSUE THREAD

**Issue by nickost** [a85/POSTMan-Chrome-Extension#3046]
Could be very useful the possibility to see after running a collection runner the output of all Rest calls and not only the HTTP status and test result.

**Comment by sdnts** [comment]
@nickost Have you tried out the native app's Runner? It will display the output of all requests (if they aren't larger than 300kbs) if you click on the request's name.
Please feel free to reopen if I misunderstood.

**Comment by nickost** [comment]
Perfect i found this feature in the native app.
I switch from Chrome version to it.
I didn't know that in the native version there were more features.
