### ISSUE TITLE
Close all tab in one shot

### ISSUE THREAD

**Issue by nickost** [a85/POSTMan-Chrome-Extension#3047]
Could be a useful feature the possibility to close all tabs opened in one shot.

**Comment by sdnts** [comment]
@nickost On the native apps, if you right click on a tab, you should be able to close all tabs. On the Chrome apps, we cannot open context-aware right click menus, so it isn't possible there. Please feel free to reopen if I misunderstood.

**Comment by nickost** [comment]
Perfect i found this feature in the native app.
I switch from Chrome version to it.
I didn't know that in the native version there were more features.
