### ISSUE TITLE
Delete collection completely from local and cloud.

### ISSUE THREAD

**Issue by skormel** [a85/POSTMan-Chrome-Extension#3048]
I'm trying to delete completely some old collections, because nowadays they are useless.

I delete them from chrome app but there'are still on cloud (getpostman.com) and when I change from computer they resync and appear again.

How can I remove them completely from local and cloud?.

Best Regards.

**Comment by sdnts** [comment]
@skormel When you delete a collection, it should go away from the website as well and should not be synced to other apps. This looks like a bug.
Do you see any errors in the DevTools console after you try to delete the collection? Can you also make sure you are on the same account on both apps (of you have multiple accounts)?

**Comment by skormel** [comment]
After you respond me, I tried again and several collections where removed from cloud but other still apeared. Today logged from work and appeared two old collection, I deleted again and now all of the disapear from cloud.

Now everything it's alright.

I only have an account but I use it on several diferent computers and operating systems.

Best Regards.
Antonio
