### ISSUE TITLE
Typo in Snippets list "Validate with Tiny Validatore"

### ISSUE THREAD

**Issue by scholary-tim** [a85/POSTMan-Chrome-Extension#3050]
Under the 'Tests' section, the Snippets list contains a small typo under the Response Body list for JSON validation. Reads "Validate with Tiny Validatore" rather than "Validate with Tiny Validator".

Found in Postman (for Mac), 4.11.0-canary02 (4.11.0-canary02) - but may be in current version too - haven't checked.

**Comment by sdnts** [comment]
@tjdurden Ah, thanks for pointing that out, we'll get that fixed.

**Comment by sdnts** [comment]
This should now be fixed in the latest Canary and stable releases. Closing.
