### ISSUE TITLE
After changing the password, the old account can also synchronize data

### ISSUE THREAD

**Issue by cainiaoDJ** [a85/POSTMan-Chrome-Extension#3052]
1. Postman Version:
Version 4.10.7
 2. App (Chrome app or Mac app):
 mac app & windows app
 3. OS details:
 windows & mac 10.12
 4. Is the Interceptor on and enabled in the app:
 no
 5. Did you encounter this recently, or has this bug always been there:
 6. Expected behaviour:

我在mac机器上运行了postman，并且登录了账号。当我想在Windows上继续我的开发时，我忘了我的账号密码。我通过邮箱重置密码后，我发现在原先的老机器上，依然能够运行同步。我并没有用新密码继续登录。  
I run the postman on the mac machine and logged in to the account. When I want to continue my development on Windows, I forgot my account password. I reset the password through the mailbox, I found in the original old machine, still able to run synchronization. I did not use the new password to continue to log in.

 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
yes
 8. Screenshots (if applicable)
null

a. sign in account in one machine
b. use another machine, change password, sign in with new pwd. 
c. try to sync by old machine.  process sucess, it is bad. I had change my pwd!

**Comment by shamasis** [comment]
Yes. Currently we would like if you could manually log out. We would add the feature to clear all sessions next month or earlier. We are waiting for some old app versions to phase out. 

Cc @abhijitkane
