### ISSUE TITLE
Parameter is missing in the request

### ISSUE THREAD

**Issue by jvkaam** [a85/POSTMan-Chrome-Extension#3053]
Hi everyone,

I'm trying to update a collection by using the PUT method. For some reason it returns:

{"error":{"name":"paramMissingError","message":"Parameter is missing in the request.","details":{"param":"collection"}}}

Defined in ANT I execute the following CURL command:

```
<exec executable="D:\tools\curl-7.49.1-win64-mingw\bin\curl" resultproperty="resupdate">
	<arg value="--request" />
	<arg value="PUT" />
	<arg value="--url"/>
	<arg value="https://api.getpostman.com/collections/${uid}" />
	<arg value="--header"/>
	<arg value="'content-type: application/json'"/>
	<arg value="--header"/>
	<arg value="x-api-key: xxxxxxx" />	
	<arg value="--data"/>
	<arg value="@pfixednewcollection.json"/>
</exec>
```

I know the x-api-key (although scrambled here) is correct because when changing this it produces an authentication error.
Also the defined file: pfixednewcollection.json is found because when I change it to a filename that doesn't exist I get an error message also. I even replaced the content with the example provided on the Postman website.
The ${uid} has a correct value because I can see that during execution.
Can anyone point me in the right direction where to look for?

Thanks

John

**Comment by shamasis** [comment]
@jvkaam can you look into the sample request defined in docs.api.getpostman.com

Can you check whether you are boxing your collection the file in a key called `collection`?

Example:

```
{
  "collection": {
    "name": "your collection",
    "item": […]
    }
}
```

You can also refer to a sample json within the examples repository of newman.
