### ISSUE TITLE
Could not get any response

### ISSUE THREAD

**Issue by zhuyingda** [a85/POSTMan-Chrome-Extension#3054]
Whatever the url I request, it always show me `Could not get any response`.
I request my own website and check the access log in server, and I found the postman just not send any http request.
Also, I found that if I open Charles and set the `Mac OS Proxy` on, the postman app can request and get correct response.

Here is my info:
 1. Postman Version: 4.10.7
 2. App (Chrome app or Mac app): Chrome 58
 3. OS details: Mac OS X 10.12.2
 4. Is the Interceptor on and enabled in the app: dont know
 5. Did you encounter this recently, or has this bug always been there: always
 6. Expected behaviour:
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 8. Screenshots (if applicable)

**Comment by kamalaknn** [comment]
@zhuyingda Are you working on an environment that is behind a proxy?

This is most probably an issue with misconfigured System Proxy settings. Could you verify once that your macOS system proxy is configured right and try sending a request?

If you are still seeing it, could you send a screenshot of the Postman Console(`cmd + opt + c` should open it). 

Thanks!

**Comment by zhuyingda** [comment]
@kamalaknn 
I see an error log in console ：
Error: getaddrinfo ENOTFOUND socks5127.0.0.1 
So I check out my system network settings, and I found a socks proxy config.
I canceled that configuration and postman can request.
Thank you!

**Comment by kamalaknn** [comment]
@zhuyingda great!

Glad you got it figured out. Closing the issue now.
