### ISSUE TITLE
[Feature Request] Assign certificate pair to all subdomains of a host name

### ISSUE THREAD

**Issue by iainjmitchell** [a85/POSTMan-Chrome-Extension#3055]
**Request:**
It would be really useful if you could assign the certificate pair to all subdomains of a specific host.
For example, add a host of _*.monkey-api.com_ and have this certificate pair used for requests to _bob.monkey-api.com_ and _dave.monkey-api.com_.

**Comment by kamalaknn** [comment]
@iainjmitchell this looks like a duplicate of #2700 

Closing this issue. Please follow the parent thread for updates.
