### ISSUE TITLE
deletion of environment variable when attempting to set it via postman.SetEnvironmentVariable

### ISSUE THREAD

**Issue by drexler** [a85/POSTMan-Chrome-Extension#3056]
1. Postman Version: 4.10.7
 2. App (Chrome app or Mac app):
 3. OS details: Windows 8.1
 4. Is the Interceptor on and enabled in the app: No
 5. Did you encounter this recently, or has this bug always been there: Recently
 6. Expected behaviour:  Variable is left as is. 
 7. Screenshots (if applicable)

1. Import the test environment template from the attached zip file
2. Import the test collection from the attached zip file. 
3. Run Get Comment to see working version. 
4. Run Get Comment(Deletes url Variable) to reproduce issue. 
5. Go to Manage environments and notice that the url variable has been deleted after Step 4. 

[postmanbug.zip](https://github.com/postmanlabs/postman-app-support/files/1020190/postmanbug.zip)

**Comment by kamalaknn** [comment]
@drexler Hey!

I gave the collection a try. I could see that in the second request the value you are trying to set to an environment variable is `undefined`. 

So at the end of the request any value that was previously set to the same environment variable would be wiped out. If you want the value to be retained, you can try adding a check for falsy cases before setting it to your environment like `responseData["url"] && postman.setEnvironmentVariable("url", responseData["url"]);`

However, the fact that setting `undefined` to an environment variable removes it from the peek view might need some thought from the Postman App side.

**Comment by drexler** [comment]
@kamalaknn  thanks for looking into it. My expectation was the variable to remain irrespective of the value being set.

**Comment by david-poindexter** [comment]
We are having this same issue.  What is the resolution?

**Comment by anodynos** [comment]
In PostMan v6.0.10 I have the same problem - trying to set an environment variable to `undefined` cause the environment variable to be deleted. This should not be the expected behaviour for sure!
