### ISSUE TITLE
Allow Environments to be shared/owned with other team members so it available within Postman Monitoring

### ISSUE THREAD

**Issue by satwise** [a85/POSTMan-Chrome-Extension#3058]
We have multiple people writing collections that will end up in Postman Monitoring, but the Environments I've defined can't be reused or shared with another admin who should also be able to manage the Environment.

This is causing confusion and proliferation of environments, as users can't select an existing Environment to Monitor test collections, as they did not create that environment.

Please adjust permissions on environments so that specific team members can be granted read and write access​ to the environment, making it selectable when publishing a Postman Monitor.

**Comment by kamalaknn** [comment]
@edjanx thanks for sending your feedback.

I am tagging this as a feature request. @a85 your thoughts on this?

**Comment by a85** [comment]
@kamalaknn Yep. We need to make some changes in the Postman app before we can support this.
@edjanx We are working towards solving this soon. Will add to this issue once we have some updates.

**Comment by FreeWillaert** [comment]
Any news on this?
Sharing templates is a good thing, but whenever a template is updated it must be manually synched, which is a real pain...

**Comment by a85** [comment]
Environment templates are now transitioned off to environments through our new feature called Workspaces. More info here: https://www.getpostman.com/docs/postman/workspaces/intro_to_workspaces
