### ISSUE TITLE
How can we parse a URL in a pre-request script?

### ISSUE THREAD

**Issue by who** [a85/POSTMan-Chrome-Extension#3059]
I'd like to write a pre-request script that parses some information from `request.url`.

What's the best way to parse a URL from inside a pre-request script?

These do NOT work:
```
var myURL = new URL(request.url); // This does not work
var myURI = new URI(request.url); // This does not work
```

Version/App Information:
 1. Postman Version: 4.10.7
 2. App: Mac App
 3. OS details: OS X Sierra

**Comment by kamalaknn** [comment]
Hi @who 

The scripts are executed in a sandboxed environment. That's why you are not seeing some of the Javascript APIs. 

We are working on some nice improvements to the `scripts` sections in the next version that will make this 
a lot easier. cc @shamasis 

For now I am closing this since this not an issue with the Postman itself. Feel free to continue the discussion here.

**Comment by duboff** [comment]
Hi @kamalaknn I agree this is not an issue with Postman but is there a recommended solution for this?

**Comment by kamalaknn** [comment]
Hi @duboff,

You can use our [Collection SDK](https://github.com/postmanlabs/postman-collection) library to parse your URL.

```js
var sdk = require('postman-collection'),
      url = new sdk.Url(request.url),
      urlJson = url.toJSON();

console.log(urlJson);
```

You can do much more with our Collection SDK. Please refer to our documentation on all you can do - http://www.postmanlabs.com/postman-collection/

**Comment by stokito** [comment]
Here is docs http://www.postmanlabs.com/postman-collection/Url.html and example:
```js
const sdk = require('postman-collection');
const apiUrl = new sdk.Url("https://example.com:8080/dir1/dir2?param1=1&param2=2");
console.log(apiUrl.getPath()); //=> "dir1/dir2"
console.log(apiUrl.getRemote()); //=> "example.com:8080"
```
So it's API is similar but not compliant with `URL`.

But I wondered why not just simply add the `url` module that is already enabled in Node.JS 7?
https://nodejs.org/api/url.html#url_the_whatwg_url_api

Thus you can save a lot of time for users who now need to search.

**Comment by stokito** [comment]
I just found that Postman do have the [url](https://nodejs.org/api/url.html) package but we need to import it explicitly. Also for some reason the URL constructor not parses and arg so I had to use `URL.parse()` instead:

```js
let URL = require('url');
let apiUrl = URL.parse('https://user:pass@sub.example.com:8080/p/a/t/h?query=string#hash');
let apiPath = apiUrl.pathname; //=> /p/a/t/h
```

**Comment by ZachHaber** [comment]
@stokito. the url package there only brings in the [Legacy url api](https://nodejs.org/api/url.html#legacy-url-api)!

I'm not sure why they haven't let the WHATWG URL from node through the sandbox, but it definitely is frustrating that a legacy package labeled "do not use" is exposed over making it easy to use modern APIs.

**Comment by arvenil** [comment]
I wonder why this is closed if we still can't use URL API?

**Comment by LiamKarlMitchell** [comment]
Why not allow new URL?

**Comment by zomars** [comment]
I've also ended in this rabbit hole. You would think after seven years this would be already included.

**Comment by ajb-neodynamics-io** [comment]
+1
