### ISSUE TITLE
[Feature request] Ability to share collections folders

### ISSUE THREAD

**Issue by zaherg** [a85/POSTMan-Chrome-Extension#3061]
I do love to organize my Collection with sub-folders, instead of using Collections all the time.
but the problem is that you cant share a folder, you can only share the whole collection which is annoying.

I contacted the support and asked me to add this as a feature request, hope it will be also something other people may want.

thanks

**Comment by numaanashraf** [comment]
@linuxjuggler Thanks for the suggestion. We'll prioritise and add this to our roadmap if this helps or adds value to a large section of our users. You can find the current roadmap at https://trello.com/b/4N7PnHAz/postman-roadmap-for-developers.

**Comment by zaherg** [comment]
sounds good, thanks

**Comment by a85** [comment]
Sorry but this is not on our roadmap right now. The core unit of sharing in Postman will remain as collections for the near future. If this changes, we'll update on our roadmap.
