### ISSUE TITLE
unable to find example icon to create request/response example mock

### ISSUE THREAD

**Issue by jb08** [a85/POSTMan-Chrome-Extension#3065]
where is the example icon as described [here](http://blog.getpostman.com/2017/05/17/mock-responses-in-postman-by-using-examples/?utm_source=All+contacts&utm_campaign=512cc22d71-EMAIL_NEWSLETTER_2017_05_22&utm_medium=email&utm_term=0_bba0cca85f-512cc22d71-13460919)?

![screen shot 2017-05-23 at 3 13 06 pm](https://cloud.githubusercontent.com/assets/8146460/26374379/c7c0ac78-3fca-11e7-8f4a-3dba26650384.png)

 1. Postman Version: v4.10.7
 2. App (Chrome app or Mac app): Mac app
 3. OS details: El Capitan
 4. Is the Interceptor on and enabled in the app: ?
 5. Did you encounter this recently, or has this bug always been there: ?
 6. Expected behaviour: see example icon
 8. Screenshots (if applicable)

**Comment by sdnts** [comment]
Hi @jb08! The examples flow has not made it to our production channel yet. You can download our Canary version if you want to take it for a spin: 
[OSX](https://dl.pstmn.io/download/channel/canary/osx_64)
Windows [x86](https://dl.pstmn.io/download/channel/canary/windows_32) [x64](https://dl.pstmn.io/download/channel/canary/windows_64)
Linux: [x86](https://dl.pstmn.io/download/channel/canary/linux_32) [x64](https://dl.pstmn.io/download/channel/canary/linux_64)

All your data should be synced in from the production app if you use Sync :)
