### ISSUE TITLE
EncodeURIComponent and DecodeURIComponent in right mouse menu do not work

### ISSUE THREAD

**Issue by tgourley01** [a85/POSTMan-Chrome-Extension#3066]
EncodeURIComponent and DecodeURIComponent in right mouse menu do not work.

 1. Postman Version: **4.10.7**
 2. App (Chrome app or Mac app): **chrome app, Chrome Version 58.0.3029.110 (64-bit)**
 3. OS details: **windows 10 pro**
 4. Is the Interceptor on and enabled in the app: **on or off seems to make no difference**
 5. Did you encounter this recently, or has this bug always been there: **I'm new to postman, can't say how long...**
 6. Expected behaviour: **Expected the selected text or field to encode/decode using RMB option (which it seems to in the desktop application)**
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 8. Screenshots (if applicable)

Add a query parameter to a POST request. Select some URLEncoding sensitive text like "{}" and select EncodeUriComponent, nothing happens. I expect it to be URLEncoded to "%7B%7D" (like in the desktop app)

**Comment by numaanashraf** [comment]
@tgourley01 Thanks for reporting this. Could you let us know your exact Chrome version?

**Comment by tgourley01** [comment]
Added chrome version to initial report, thx!

**Comment by nuriyevn** [comment]
I have  the  same  issue

**Comment by prashantagarwal** [comment]
@tgourley01 @nuriyevn We have fixed this issue in 5.3.0 release. Can you guys please update your chrome app and verify.

**Comment by restot** [comment]
I have this issue 

MacOS 13.1
MacBook Air m1

Version 10.11.1
UI Version: 10.11.1-ui-230222-1424
Desktop Platform Version: 10.11.1 (10.11.1)

@prashantagarwal What else I've could provide to help with the resolution of this issue?
