### ISSUE TITLE
Base 64 encoded Cookie Problems with "=" at the end

### ISSUE THREAD

**Issue by dvinell** [a85/POSTMan-Chrome-Extension#3069]
1. Postman Version: 4.10.7
 2. App (Chrome app or Mac app): 
 3. OS details: Windows 10
 4. Is the Interceptor on and enabled in the app:
 5. Did you encounter this recently, or has this bug always been there: Always
 6. Expected behaviour: Cookie handling works correctly

If I try to add a Base 64 encoded cookie with a "=" at the end and save it, then the trailing "=" is truncated, and my call fails.

So I start by pasting in as a new cookie for domain "aa.com":

SMSESSION=ptf2EN1LhLD-- stuff deleted from here to save space --sutNG0+2L8=; path=/; domain=.aa.com; Expires=Sun Jan 10 2038 23:14:07 GMT+0000 (GMT Standard Time); 

Then I save it, and what is saved is as follows:
Note that the last "=" before the path has been removed.

SMSESSION=ptf2EN1LhLD-- stuff deleted from here to save space --sutNG0+2L8; path=/; domain=.aa.com; Expires=Sun Jan 10 2038 23:14:07 GMT+0000 (GMT Standard Time);

**Comment by kamalaknn** [comment]
@dvinell Thanks for reporting the issue. We will look into this.

**Comment by sdnts** [comment]
@dvinell Can you update to 5.1.2 and check if this is fixed now?
