### ISSUE TITLE
the following parameters are missing : oauth_callback

### ISSUE THREAD

**Issue by devyanikul** [a85/POSTMan-Chrome-Extension#3071]
I am trying to generate token for outh1. After filling all authorization field, I get an error of missing parameters oauth_callback. how to add this parameter as i have already tried adding manually but doesn't work. Thank you

 1. Postman Version:
 2. App (Chrome app or Mac app):
 3. OS details:
 4. Is the Interceptor on and enabled in the app:
 5. Did you encounter this recently, or has this bug always been there:
 6. Expected behaviour:
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 8. Screenshots (if applicable)

**Comment by a85** [comment]
Please follow issue guidelines and do not cram everything in the issue title. Closed until this is fixed.
