### ISSUE TITLE
Every api call will fail after making api call to an undefined port

### ISSUE THREAD

**Issue by tvpsh2020-zz** [a85/POSTMan-Chrome-Extension#3072]
1. Postman Version: 
- 4.10.7
 2. App (Chrome app or Mac app): 
- Chrome app
 3. OS details: 
- Windows 10 Pro x64 (ver 1703, build 15063.296)
 4. Is the Interceptor on and enabled in the app: 
- enabled
 5. Did you encounter this recently, or has this bug always been there: 
- always occur
 6. Expected behaviour:
- Complete my request
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):

Nothing special but I can describe this scenario : 
I'm sure my server is fine and the api also doing well, we assume the api address is 10.100.125.30:8000, then I make an api call to a undefine port like 10.100.125.30:44567, Postman will hang in there and always shows "Loading...", then I click the "Cancel Request", thereafter every normal api call will hang in there and shows "Loading..." too.

It can be resolve after I restart Chrome. 

 8. Screenshots (if applicable)

**Comment by numaanashraf** [comment]
@tvpsh2020 Thanks for reporting. This is a known issue in Postman Interceptor. We are working on rolling out a fix for this soon.

**Comment by abhijitkane** [comment]
@tvpsh2020 Can you confirm this fixed in the latest versions of Postman (5.2.0) and the Interceptor (0.2.23)? Feel free to reopen if not.

**Comment by tvpsh2020-zz** [comment]
Yes, now it is behave normally, thanks for help :)
