### ISSUE TITLE
Parse html from response body

### ISSUE THREAD

**Issue by MatteoPiovanelli** [a85/POSTMan-Chrome-Extension#3073]
Hello.

I used to do, in tests:
```
var myHtml = document.create("html");
myHtml.innerHtml = responseBody;
```

I updated postman to run stuff with newman and now those same tests return an error like "document is undefined" even when running them in postman.

Is thee a conventional way to parse an html response?

I will be able to provide more detail tomorrow when I am back in the office

**Comment by kamalaknn** [comment]
HI @MatteoPiovanelli-Laser 

Postman executes all your scripts in a sandboxed environment. That is why you are not able to access `document` from within the scripts.

You can use the [cheerio](https://cheerio.js.org/) library for your html related parsing.

This should work 

```
var $ = cheerio(responseBody)
```
Hope this helps.

Closing this because this is not an issue with the Postman App itself. Feel free to continue discussion though.

**Comment by MatteoPiovanelli** [comment]
Thank you. I'll try that when I am back on my machine.

**Comment by MatteoPiovanelli** [comment]
@kamalaknn just commenting to say I tried cheerio and it works perfectly. Thanks again for your reply.

**Comment by kamalaknn** [comment]
@MatteoPiovanelli-Laser you're welcome 😄 

Glad that it solved your issue.

**Comment by joelcolucci** [comment]
@kamalaknn

**UPDATE START**
I re-installed Postman and cheerio is now working as expected
**UPDATE END**
 
When adding`html = cheerio(responseBody);` to the Tests section the following error is displayed `There was an error in evaluating the test script: cheerio is not defined`.

I don't see any reports of this bug/error in usage. I can put together an issue report if needed. If I'm forgetting something just let me know :)

**App**
Postman for Chrome
Version 5.2.1
OS X / x86-64
Chrome 61.0.3163.100

**System**
macOS Sierra 10.12.6

**Comment by kamalaknn** [comment]
@joelcolucci `cheerio` and other libraries are not included in our `Chrome` apps. 

You can download our native apps from https://www.getpostman.com/apps. Here's our [blog](http://blog.getpostman.com/2017/03/14/going-native/) on why you should consider our Native apps over our Chrome app

**Comment by joelcolucci** [comment]
@kamalaknn thank you for reply.

I had thought I had the native Mac app installed all along. I suppose my "re-install" was the first install. 😐

Regardless thanks again :)
