### ISSUE TITLE
When the protocol is omitted from the link, Postman only uses GET

### ISSUE THREAD

**Issue by Dougley** [a85/POSTMan-Chrome-Extension#3075]
1. Postman Version: v4.10.7
 2. App (Chrome app or Mac app): Win64
 3. OS details: Windows 10 Creators Update x64
 4. Is the Interceptor on and enabled in the app: No
 5. Did you encounter this recently, or has this bug always been there: Recently
 6. Expected behaviour: Postman adheres to the option set in the drop-down menu
 7. Console logs: http://i.imgur.com/8I09XvH.png
 8. Screenshots (if applicable)

<img width="528" alt="postman_2017-05-25_20-07-28" src="https://cloud.githubusercontent.com/assets/9768134/26468119/95a0850c-4195-11e7-9797-f96017f7fe9e.png">

Steps to reproduce the problem:
1. Create a [requestb.in](https://requestb.in), or something similar.
2. Enter the link into Postman, but strip the `https://` from the URL.
3. Set the method to anything but GET in the dropdown.
4. Send request.

**Comment by sdnts** [comment]
Hi @SteamingMutt!
When you make a request without the protocol, it is assumed to be `http`
We did some investigating here, and it looks like RequestBin redirects all requests to `http` to `https`.
When this happens, the method is reset to GET and the request body is stripped off, which is standard behaviour. You can verify this by turning off `Automatically Follow Redirects` in the app (under the `General` tab of `Settings`). With this setting off, you'll get a 301 status code, and the Location header pointing to the `https` URL.

There isn't much we can do here unfortunately, so I'm closing this :)
