### ISSUE TITLE
How to branch to request based on conditional statement without making a request first.

### ISSUE THREAD

**Issue by wierzba3** [a85/POSTMan-Chrome-Extension#3076]
Hi,

My scenario is that my suite of tests is ran against a web service and I want to refactor it to be able to run against multiple environments.

The first request in the collection is to obtain an authentication token.

My problem is that, for this first request to obtain a token, I want to execute different requests based on a configurable environment variable.

So, say I've set the environment variable "my_environment" to value DEV.

I want the tests to read the value of the environment variable (which is DEV in this scenario), and execute the "DEV Token Request" and completely ignore/skip the "PROD Token request.

I can't see a way to do this without having to create some dummy request and then branch to the appropriate request in the post-execution script. If this is the only way, what is the cleanest/easiest dummy request I can make?

**Comment by kamalaknn** [comment]
Hey @wierzba3 

Postman has a `setNextRequest` function in the scripts that can help you with this. You can modify the following script to suit your needs.

```js
var my_environment = postman.getEnvironmentVariable('env');

if (my_environment === 'DEV') {
  postman.setNextRequest('DEV Token request'); // name of your request goes here
} else {
  postman.setNextRequest('PROD Token request'); // name of your request goes here
}
```

Hope this helps. Closing the issue since it is not an issue with the Postman App itself. Feel free to continue discussion here.
