### ISSUE TITLE
Team Cloud Documenter - issues with HTTP protocol in sample code blocks

### ISSUE THREAD

**Issue by SMSMichael** [a85/POSTMan-Chrome-Extension#3079]
1. Postman Version: 4.10.7
 2. App (Chrome app or Mac app): Windows/Chrome App
 3. OS details: Win10 64
 4. Is the Interceptor on and enabled in the app: N/A
 5. Did you encounter this recently, or has this bug always been there: Only just started using Team Cloud Documenter
 6. Expected behaviour: Sample code generated by the team cloud documenter should either use the http protocol prefix (http/https) included in the environment variable (if one is used) or should not add additional slashes to the URL when the protocol is hard coded into the path
```
// Environment Variables Example
// {{baseURL}} = https://api.example.com
{{baseURL}}api/some/endpoint // -> https://api.example.com/api/some/endpoint
// Current Behavior:
{{baseURL}}api/some/endpoint // -> http://https://api.example.com/api/some/endpoint

// Hard Coded Example
// {{baseURL}} = api.example.com
https://{{baseURL}}api/some/endpoint // -> https://api.example.com/api/some/endpoint
// Current Behavior:
https://{{baseURL}}api/some/endpoint // -> https:///api.example.com/api/some/endpoint
```
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app): N/A - Team Cloud Documenter
 8. Screenshots (if applicable)
![image](https://cloud.githubusercontent.com/assets/8366819/26503703/cb392230-420f-11e7-9fe6-428b62c09485.png)

1. Create a new postman collection
2. Create a new environment that includes:
 - `{{baseURL}}` - includes PROTOCOL + DOMAIN (e.g. https://app.example.com)
 - `{{domain}}` - includes only DOMAIN (e.g. app.example.com)
3. Create 2 endpoints in the collection
 - One that uses the `{{baseURL}}` variable
 - One that uses the "https" + `{{domain}}` variable
4. Share the environment you created as a public template
5. Publish the collection via the team cloud documenter

Results: 
* The version using the full `{{baseURL}}` appends "http:///" to the path (which it shouldn't)
* The version using a hardcoded "https" + `{{domain}}` includes an extra slash in the URL: e.g. "https:///api..."

**Comment by godfrzero** [comment]
@SMSMichael Thanks for bringing this up. We're aware of this issue and a fix should be out within a few days. 👍

**Comment by thirdjm** [comment]
Is this allready fixed as it still seems to be an issue ?

**Comment by godfrzero** [comment]
@thirdjm We're already pushed out a fix for the additional slash that shows up. 

There's still an issue which causes multiple protocols to show up if the original URL starts with an environment variable, where the protocol will repeat. We're still figuring out a fix for that.

**Comment by thirdjm** [comment]
@godfrzero when separating the two variables as protocol and endpoint my code has http:// instead of my variable https://. In my opinion https:// is more important then http:// so if you replace it out of the box, pls then do it with https://

thanks.

**Comment by zodeus** [comment]
Any movement on this? Seems like a fairly straightforward fix. The issue doesn't appear in the postman app. Just the publish hosted docs

**Comment by godfrzero** [comment]
@zodeus Fixes for the additional slash, and the duplicate protocol, have already been pushed out. Are you still running into this issue?

**Comment by zodeus** [comment]
It's fixed in the App, but in the hosted version (cloud?) It's still broken
![image](https://user-images.githubusercontent.com/238219/31253666-8c2c2cc6-a9da-11e7-9346-b92de44e78c0.png)

**Comment by godfrzero** [comment]
@zodeus In your case, this seems to be happening because the environment variable value has a leading space.

**Comment by zodeus** [comment]
You are correct, thanks and sorry for that.
