### ISSUE TITLE
Feature request : Testing response body values to a g- variable value

### ISSUE THREAD

**Issue by Muralinie** [a85/POSTMan-Chrome-Extension#3080]
1. Postman Version:Version 4.10.7
 2. App (Chrome app or Mac app): Windows app
 3. OS details: MS Windows 7 enterprise 

I want to avoid the verifiable response values to be hard coded in the tests, rather pick the response values from the global variables to verify the response body . Is this possible in postman to reduce manipulation of scripts for change in test data results .

Example: My current script says : 
tests["Document returned with id_num "]= data.docList[i].Datamap.id_num === '1030939177'

I do not want the test value "1030939177" to be hardcoded in the script, but be verified through a variable . if this feature is available in POSTMAN? . This feature would be useful in creating  reusable scripts without changing the test scripts for each change of test data .

**Comment by sdnts** [comment]
Hi @Muralinie You can use global variables to do this kind of thing.
[Docs](https://www.getpostman.com/docs/postman/environments_and_globals/manage_globals)

You'll need to set up a global variable and access this variable in your script using `postman.getGlobalVariable('<name>')`

**Comment by sdnts** [comment]
Closing this. Please feel free to reopen if I misunderstood :)

**Comment by Muralinie** [comment]
I think you have misunderstood :) . I am not wanting to set a global variable . As per the scripts I have shared I want to verify the value in the tests picking the value from global variable ,

**Comment by sdnts** [comment]
Yep, so once you set a global variable called `expectedValue` to `1030939177`, your test script would look like: 
`tests["Document returned with id_num "]= data.docList[i].Datamap.id_num === postman.getGlobalVariable('expectedValue')`

Note that I'm getting the global variable value using `getGlobalVariable`

**Comment by Muralinie** [comment]
thanks madebysid. That solved my question . Since this method is not present in the snippets I couldn't get this method . :+1:
