### ISSUE TITLE
Issue with doing get of environment variable if variable name starts with an integer.

### ISSUE THREAD

**Issue by vishnupathak** [a85/POSTMan-Chrome-Extension#3081]
1. Postman Version:
 2. App (Chrome app or Mac app):
 3. OS details:
 4. Is the Interceptor on and enabled in the app:
 5. Did you encounter this recently, or has this bug always been there:
 6. Expected behaviour:
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 8. Screenshots (if applicable)

**Comment by sdnts** [comment]
Hi @vishnupathak Could you share your test script here?
Also, for future searchability, please give the issue an appropriate title and describe the issue in the description instead of the title.

**Comment by vishnupathak** [comment]
sorry, will take care of heading so that people may search easily.
Details:
 if (i=="A")
{ var STA_R_ID = environment.R_ID1; 
  postman.setEnvironmentVariable("STA_R_ID", STA_R_ID);  
  
   var STA_Quantity = environment.1Quantity1;
  postman.setEnvironmentVariable("STA_Quantity", STA_Quantity);  
} 
else
{ var STA_R_ID = environment.R_ID2; 
  postman.setEnvironmentVariable("STA_R_ID", STA_R_ID);  
  
   var STA_Quantity = environment.2Quantity1;
  postman.setEnvironmentVariable("STA_Quantity", STA_Quantity);  
}

Here script is working fine for getting and setting variables R_ID1/R_ID1  using STA_R_ID but not for 1Quantity1/2Quantity1 using STA_Quantity

**Comment by sdnts** [comment]
@vishnupathak The correct way to get an environment is by using `postman.getEnvironmentVariable('<variableName>')`. This will return the value of the variable.

Since Postman scripts are still JS, variables starting with a number are not allowed, which is why you're seeing this error. Let me know if using `getEnvironmentVariable` fixed your issue.

**Comment by vishnupathak** [comment]
no luck, i tried here are the results:

if my syntax is:  var STA_Quantity= postman.getEnvironmentVariable('1Quantity1')

error: "ReferenceError: getEnvironmentVariable is not defined"

if my syntax is: var STA_Quantity= postman.getEnvironmentVariable(1Quantity1)

error: unexpected 1

if my syntax is:  var STA_Quantity= postman.getEnvironmentVariable("1Quantity1")

No error but next step of setEnvironmentVariable won't set any value.

If the only way to solve it is by redefining my variables please confirm.

**Comment by sdnts** [comment]
The first and last statements are both correct, there isn't a difference between `'` & `"`. I think you might have a space between `postman.` and `getEnvironmentVariable`. (The error also suggests something similar).

I'm unable to reproduce the error you described in the third statement.

My test script looks like this:

```
let x = postman.getEnvironmentVariable('1yay1')
console.log(x)
postman.setEnvironmentVariable('1yay1', 'something else')
let y = postman.getEnvironmentVariable('1yay1')
console.log(y)
```

**Comment by vishnupathak** [comment]
Hey Sid, No I haven't left any space, probably what you mentioned in your first comment is the reason, i.e. my variable name starts with an integer instead of alphabet "1Quantity1", will try to correct the naming convention and retry.

**Comment by sdnts** [comment]
@vishnupathak Were you able to get this to work?
