### ISSUE TITLE
Postman native app doesn't work with System Proxy

### ISSUE THREAD

**Issue by boekhold** [a85/POSTMan-Chrome-Extension#3084]
1. Postman Version: 4.10.7
 2. App (Chrome app or Mac app): Native
 3. OS details: Windows 10

My organization uses Forcepoint TRITON AP-ENDPOINT Web Diagnostics (formerly Websense), which forces a System Proxy to be set (even though btw I can access outside websites without going through a proxy server....).

With Postman Native App, I'm trying to access a REST API that's hosted in AWS. This fails with the following message in the console:

![image](https://cloud.githubusercontent.com/assets/3764084/26570073/885c4f10-451f-11e7-8e70-1d9244cb3213.png)

Seems like the proxy authentication doesn't work properly?

A) Is there a way to disable Postman from using a Proxy Server completely?
B) Can I do something to fix the proxy authentication error?

**Comment by sdnts** [comment]
Hi @boekhol, Postman will use the system proxy. Can you try giving a wildcard entry to blacklist your API in your system's proxy settings?

**Comment by boekhold** [comment]
Hi,

Unfortunately I have no control over proxy settings. They are controlled by some group policy or this silly Websense/Forcepoint thing. Proxy settings look like:

![image](https://cloud.githubusercontent.com/assets/3764084/26575331/d28d64fa-4535-11e7-9847-a397a8aa80a4.png)

Actual Proxy PAC URL obfuscated, but it's something belonging to Websense/Forcepoint.

If I try one of the REST endpoints that just a simple GET request with pathinfo/queryparams, and I run it from Chrome, with the same system proxy settings, it works. Looking at the DevConsole, I see:

- General
   - Request URL: my HTTPS URL
   - Remote Address: xxx.xxx.xxx.xxx:8081, which I assume is an HTTPS proxy
- Request Headers
    - Host: IP address and port of my target

![image](https://cloud.githubusercontent.com/assets/3764084/26576188/00556bc8-4539-11e7-8024-5f9cf1028f9b.png)

**Comment by sdnts** [comment]
Can you check if the PAC script is actually returning a protocol with the proxy URL? We suspect it isn't. When there isn't a protocol, Postman will default to an HTTP proxy, whereas you need an HTTPS proxy, which is why this must be failing.
We're also looking into this in more detail

**Comment by boekhold** [comment]
Doesn't look like the PAC script returns a protocol:

![image](https://cloud.githubusercontent.com/assets/3764084/26580229/478710e6-4548-11e7-882d-b6149cd40e78.png)

I obfuscated the actual IP addresses, but there's no http:// or https:// or ftp:// in front of them.

**Comment by sdnts** [comment]
Would it be possible for you to try and change this to return the protocol and see if things work correctly? We'll look into how this can be made clearer in the app.

**Comment by boekhold** [comment]
Unfortunately I do not have the access to change the PAC script, or even change the System Proxy to load a local copy :(

**Comment by ismaelhamed** [comment]
@madebysid Can you guys just give us the option to set up the proxy manually, like most apps?

**Comment by sdnts** [comment]
@ismaelhamed Ah indeed, we've done exactly that. The custom proxy is out on our Canary channel right now. You'll find it under Settings > Proxy
This will make its way into our stable channels with the next release.

Here are download links for Canary:
[OSX](https://dl.pstmn.io/download/channel/canary/osx_64)
[Windows 32-bit](https://dl.pstmn.io/download/channel/canary/windows_32)
[Windows 64-bit](https://dl.pstmn.io/download/channel/canary/windows_64)
[Linux 32-bit](https://dl.pstmn.io/download/channel/canary/linux_32)
[Linux 64-bit](https://dl.pstmn.io/download/channel/canary/linux_64)

**Comment by tkrolbm** [comment]
@madebysid thank you for this update. I had exactly the same problem as original poster and manually setting proxy details allows me to use postman properly.

**Comment by cacti77** [comment]
@madebysid How do you specify the username and password details in the Global Proxy Configuration for the Canary build? I'm using Windows 64-bit but it only lets me enter a server name and port. My HTTPS_PROXY and HTTP_PROXY environment variables have formats like this:

`HTTPS_PROXY=http://<user_id>:<password>@<proxy_server>:<proxy_port>/`

**Comment by cacti77** [comment]
Somebody showed me a workaround that works in Windows: create a .bat file that unsets the environment variables you may have. i.e.,:
```
set HTTP_PROXY=
set HTTPS_PROXY=
start Postman.exe
```
Put this bat file in the same directory as Postman (C:\Users\<Your_Windows_Username>\AppData\Local\Postman\app-5.1.3 in my case) and run it. Then my requests worked fine:). This is using the regular Postman build v5.1.3 and I didn't change any of the default settings in the app itself. I guess Windows users who don't set a global HTTP_PROXY or HTTPS_PROXY environment variable won't need this.

Admittedly this was for accessing URLs inside the corporation's firewall.

**Comment by johighley** [comment]
Using canary version v5.2.0-canary01.  I normally go through a corporate proxy, which works ok (settings get sync'd).  However, I need to make a request to a local server and can't use the proxy.  Turning off the proxies in settings is still trying to use the proxy though, per the console showing the error returned by the proxy.  Creating the .bat file as cacti77 is a work around.  There needs to be two levels of proxy settings: the app in general for syncing, etc. and per-request settings to override the app level.

**Comment by cacti77** [comment]
One thing I haven't tried is to set NO_PROXY inside the Windows .bat file for accessing endpoints inside the company rather than unsetting HTTP_PROXY and HTTPS_PROXY.

**Comment by johighley** [comment]
From what I can tell, clearing the proxy variables in the .bat doesn't break the app's outside requests for syncing and update checks. It seems to be using the system proxy settings for app requests and the environment variables for the user defined requests.

**Comment by harryi3t** [comment]
In the latest version of Postman 5.2.0, we have added additional settings to manage proxy settings
![image](https://user-images.githubusercontent.com/5207331/29882136-c65ccb12-8dc9-11e7-99de-516cdbe2529e.png)

System Proxy is the one set at the OS level
Global Proxy is what you can set for all the requests made by Postman app

Just turn off both the proxies and it should work.
Let me know if you still face the issue.

**Comment by cacti77** [comment]
@harryi3t No, sorry - 5.2.0 doesn't work for me on Windows 7. Even with both proxies turned off I can't access services inside the corporate firewall. (Admittedly my HTTP_PROXY, HTTPS_PROXY and NO_PROXY environment variables are still set but Postman shouldn't be affected by them if I've turned both System and Global Proxy off in the settings, should it?) I've gone back to using my .bat file.

**Comment by harryi3t** [comment]
@cacti77 for windows app please follow the thread https://github.com/postmanlabs/postman-app-support/issues/2253

And as I mentioned in that thread, can you also try replacing localhost to 127.0.0.1
also please share the logs from Postman Console.

**Comment by win5do** [comment]
macos 10.14
postman native app v6.5.2 

still has bug. 
I can access google.com in chrome after enable the vpn(socks5, pac).
but  enable the Use System Proxy setting in postman, can't get google.com. 
Manual set global proxy configuration in postman can work, this is not pure.

![image](https://user-images.githubusercontent.com/22112659/48750484-41fd6d80-ecba-11e8-93b6-e2b6836f7ad1.png)

**Comment by lesscodetxm** [comment]
I'm seeing the same issue with 7.20.1. If Postman is configured to use the system proxy I can't connect to one of our services (I can connect outside of Postman - eg Chrome). The system proxy is configured via a Symantec PAC file. I have to plug the IP address given by the PAC script into the Postman Global proxy settings in order for it to work.

**Comment by lesscodetxm** [comment]
I stand corrected - I thought I was running 7.20.1 after I updated from within Postman, but after I restarted the Proxy tab looks different and I can no longer connect to the problem service no matter what Proxy settings I have, it seems. The service continues to work fine in the browser and from other scripts and apps.

**Comment by kamalaknn** [comment]
@lesscodetxm Can you share more information to help us debug this? 

1. The version of Postman you are using right now
2. Screenshot of the Proxy tab in settings
3. Information on the proxy you are using. Do you have a different configuration for proxy for the services you are using?
4. Can you share the errors you are getting for the requests by opening `View -> Show Postman Console`?

**Comment by lesscodetxm** [comment]
@kamalaknn 
I had uninstalled Postman and tried to reinstall, and ended up in the situation described here: https://github.com/postmanlabs/postman-app-support/issues/6723

After uninstalling, wiping the Postman folder from my AppData and reinstalling, I'm able to run again (7.20.1) and the Proxy tab looks like it did before I updated (two sections, one for Global Proxy and one for System Proxy).

I am now able to call my service from Postman by turning off both proxy configurations.
If I turn on either proxy (or both), the console says:

```
GET https://redacted
Error: read ECONNRESET
Warning: This request did not get sent completely and might not have all the required system headers
Proxy
authenticate: false
host: "10.220.0.42"
id: "95d684f9-42d9-448f-99df-fc7941c642e9"
match: {…}
port: 8080
tunnel: false
Request Headers
client_id: fdd3e921231c4d0799041bb3d0ff5b7d
client_secret: 990081aDD3464329A35B70997B1Da9FD
```

**Comment by TungstenX** [comment]
I'm having proxy issues. It used to have two sections. One I could manually specify a proxy and/or use the system one. Now I only have the system one, that doesn't work.
Postman for Windows
Version **7.22.1**
win32 10.0.15063 / x64

![Capture83](https://user-images.githubusercontent.com/13778824/79336352-e0c7e100-7f23-11ea-90e1-5328513a1835.PNG)

**Comment by ankurdengla** [comment]
Hey @TungstenX !

Earlier the proxy settings were only for sending requests. We have moved that to a section titled `Proxy configuration for sending requests` in the `Proxy` settings. You can still apply the system settings for sending requests and also specify a custom proxy. You just need to -

* Check the `Use System Proxy` checkbox if you need to use the system proxy for sending requests under the `Proxy configurations for sending requests`
* Check the `Add a custom proxy configuration` checkbox and specify settings under the same section if you need to specify a custom configuration.

![image](https://user-images.githubusercontent.com/26045713/79336802-f9df8a80-7f41-11ea-841b-8c68137ebb41.png)

**Comment by TungstenX** [comment]
Hi @ankurdengla 
Thank you for the quick response.
The UX is bad. When unticked, one cannot see the tick box. Clicking on the "Use the system proxy" text doesn't toggle the check box.

**Comment by ankurdengla** [comment]
Hey @TungstenX !
We are sorry that you are having such an experience with the app. You should be able to toggle the setting by clicking on the checkbox for `Use system proxy` .
Clicking on the text to toggle is not something we have added at the moment. But thanks for the feedback. We are constantly looking into improving the UX for the app.
