### ISSUE TITLE
Loading indicator icon is not symmetrical

### ISSUE THREAD

**Issue by cypressious** [a85/POSTMan-Chrome-Extension#3085]
1. Postman Version: v4.10.7
 2. App (Chrome app or Mac app): Windows App
 3. OS details: Windows 10
 4. Is the Interceptor on and enabled in the app: no
 5. Did you encounter this recently, or has this bug always been there: not sure
 6. Expected behaviour: The sun should be proply centered 
 8. Screenshots (if applicable)

![grafik](https://cloud.githubusercontent.com/assets/1191816/26582006/845665a2-453f-11e7-9bbc-751dce11589d.png)

**Comment by sdnts** [comment]
@cypressious Whoa nice eye there! We'll get this fixed!

**Comment by sdnts** [comment]
@cypressious We fixed this in 5.2 :D
