### ISSUE TITLE
Full resizable Request or a Resizable Response window

### ISSUE THREAD

**Issue by loraxipam** [a85/POSTMan-Chrome-Extension#3088]
When creating a POST body I have no need at all to see the Response window. In fact, the resizable Request window only allows me to fill my whole screen with a completely empty Response window. But I can't make a full screen Request window. :-(

-- Expected behaviour
Request body window could go beyond half screen OR the Response body window could be "minimized".

-- Current behaviour
Request window size goes from 9 to 35 lines (of 14 pt font).

![emptiness](https://cloud.githubusercontent.com/assets/17756560/26646775/ec2c9842-460a-11e7-819e-c0965ba3a635.PNG)

**Comment by a85** [comment]
You can try going to View > Toggle two-pane view to get a full column request/response window.

**Comment by loraxipam** [comment]
Yes, that helps a lot but I still have a quarter of my screen black where my request is being edited.

**Comment by a85** [comment]
Marked this as a feature. We are working on making the Postman app modular and eventually each component will be resizable, minimizable etc.

**Comment by Hack-Make-Mustache** [comment]
Hey ... it's 2 years later and it's still the same :(
Working with Postman in Vertical makes this pretty painful.

**Comment by coditva** [comment]
Hey @loraxipam and @CuriousSecGuy,

We've improved the Request and Response editing/viewing experience to allow you to hide away a section when you don't need it, exactly how you described.

Please update the app (`7.28.0` or later) and resize the Request or Response panes to any size you prefer! 🎉 

![Screen Recording 2020-08-25 at 13 07 01](https://user-images.githubusercontent.com/8445768/91146116-1485f500-e6d4-11ea-9c60-ef1673d167f5.gif)

**Bonus tip:** With version `7.30.0` you can also quickly resize the panes by scrolling over them while pressing the `Alt` key (`option` key on MacOS).

**Comment by loraxipam** [comment]
:1st_place_medal: 

Y'all rock, amigos!
