### ISSUE TITLE
Memory leak in latest version?

### ISSUE THREAD

**Issue by Ravendarksky** [a85/POSTMan-Chrome-Extension#3090]
When I use the latest update of postman for more than about 40 mintues it starts to EAT my memory until it becomes unresponsive and I ahve to close it. I can then reopen it and contine on. This has happened to me three times tonight... I'm simply hitting single endpoints GET, PUT, POST and DELETE. None of them are returning much data. I do have some tests assigning a few enviroment variables but nothing exciting.

 1. Postman Version: v4.11.0
 2. App (Chrome app or Mac app): Windows native app (electron?)
 3. OS details: Windows 10 64 bit
 4. Is the Interceptor on and enabled in the app: No, disabled
 5. Did you encounter this recently, or has this bug always been there: Recently
 6. Expected behaviour: I would not expect my memory to keep growing when I'm not even using the runner.
 7. Console logs : N/A
 8. Screenshots: http://imgur.com/a/9O2zS

1. Use postman for about an hour, making lots of requests and touching a few envrioment variables (all single strings)... nothing magical.

**Comment by Ravendarksky** [comment]
May be a duplicate of: https://github.com/postmanlabs/postman-app-support/issues/2949 Sorry

**Comment by SamvelRaja** [comment]
We are start tracking them in #2949
