### ISSUE TITLE
Create a Converter Mechanism

### ISSUE THREAD

**Issue by nhalstead** [a85/POSTMan-Chrome-Extension#3091]
1. Add a feature to Convert/Export a JSON Array, Something easy to work with when taking something from a program, etc.
2. Add the ability to Export to CURL to run in Linux, etc.
3. Add a feature to Accept CURL patterns to take in and process to make a new Request Type.

**Comment by nhalstead** [comment]
This is in relation to Windows PostMon 4.11.0.

**Comment by nhalstead** [comment]
This is in relation to Windows Postman 4.11.0.

**Comment by SamvelRaja** [comment]
**1. Add a feature to Convert/Export a JSON Array, Something easy to work with when taking something from a program, etc.** 
Can you explain me bit more on how you want to export the data? currently you can currently create a collections out of the requests and export them as postman_collection format. 
https://www.getpostman.com/docs/collections

**2. Add the ability to Export to CURL to run in Linux, etc**
https://www.getpostman.com/docs/creating_curl

**3.Add a feature to Accept CURL patterns to take in and process to make a new Request Type.**
https://www.getpostman.com/docs/importing_curl

Hope this finds useful.
