### ISSUE TITLE
Auto-Complete Usability / Changing Variable

### ISSUE THREAD

**Issue by StoicNZ** [a85/POSTMan-Chrome-Extension#3092]
1. Postman Version: 4.10.7
 2. App (Chrome app or Mac app): Native Windows (<-- might want to update that example template on GitHub)
 3. OS details: Windows x64
 4. Is the Interceptor on and enabled in the app: No
 5. Did you encounter this recently, or has this bug always been there: Noticed recently
 6. Expected behaviour: Let me delete parts of a variable name without deleting the whole thing.. I'd rather not have auto-complete at all when this happens.
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app): N/A
 8. Screenshots (if applicable)

![4](https://cloud.githubusercontent.com/assets/5607534/26664041/1c9f7b62-46d2-11e7-85ad-0481a6939888.gif)

Assign two environment variables, use them in your request, try to change one without deleting the entire variable name at once. (In my image above, I try to change "https" to "http" to call http://google.com instead of https://google.com)

**Comment by prashantagarwal** [comment]
@StoicNZ Thanks for reporting this. We have released a new version 4.11.0 with the fix for this. Please verify if this is fixed for you un that version.

**Comment by StoicNZ** [comment]
@prashantagarwal I'm on the canary02 version of 4.11.0 and it's fixed..

How did you do that? *shifty eyes*

Fixed.. You damn wizard.

**Comment by prashantagarwal** [comment]
😄
