### ISSUE TITLE
Default Variable Value

### ISSUE THREAD

**Issue by StoicNZ** [a85/POSTMan-Chrome-Extension#3094]
I'm using Postman collections as part of my CI deployment process because I love Postman and I will force it on everyone I know until they love it, too.

Now, hiring a good technical tester is hard and we tend to get landed with a lot of people who don't understand a lot of new tech, or it takes them a little bit to get used to.

I'd like to add default variable values in the notation if none is applied in the current environment. A good syntax I can suggest which is also used in the Java Spring framework would be:

{{variableName:variableDefaultValue}}

This would be useful for those who don't already have all the environment variables they need, or would like some example of what values go where when the variable name isn't sufficient enough.

Those new to your API or your Postman collection might be missing a value, or some values just don't need to be set 99% of the time but we still like to parametrize our collections when possible so we can just update our build parameters or CI process without touching the code.

That's enough words for today. Thanks all.

**Comment by numaanashraf** [comment]
Thanks for the suggestion @StoicNZ. We are working on improvements to variables at the moment and we'll keep this use case in mind.

/cc @bhawna2109

**Comment by a85** [comment]
I believe you can now use Collection variables for this now and overwrite these values with environment variables.

**Comment by Bharwcb** [comment]
@a85 is the ability to set default environment variable values a feature now?  Is there documentation on this?

**Comment by a85** [comment]
Yep. You can set an initial value now for all kinds of variables now.

**Comment by Bharwcb** [comment]
Thanks @a85 , where can I find documentation or instructions on how to do this?

**Comment by vkaegis** [comment]
@Bharwcb Here's some reference material for setting session values for variables: https://www.getpostman.com/docs/v6/postman/environments_and_globals/sessions

You can also go through this blog post which best explains differences in how these variables values work: http://blog.getpostman.com/2018/08/09/sessions-faq/

Closing this issue, feel free to open another if you have more feedback around this.

**Comment by emersonf** [comment]
I was about to request the exact same feature, syntax and all.

Imagine a request that POSTs a JSON body with 10 properties and their values.

```json
{
  "prop1": 24,
  "prop2": "hi",
  "propA": {
      "prop3": "foo...",
      "prop4": 24,
      "prop5": "hi",
   },
  "propB": {
      "prop6": false,
      "prop7": false,
      "prop8": true
   },
  "prop9": -8,
  "prop10": "bye"
}
```

If that request is manually triggered using _Send_, odds are the JSON contains 10 literal values. Now imagine you decide to trigger that request 100 times from the collection runner, and want to set those 10 values from a CSV file using data variables. Right now, that would require creating 10 environment or collection variables, setting their values, and overriding them with data variables. But those 10 new variables create a lot of noise and maintenance overhead and don't really provide any benefit. (If you think that's not so bad, assume 30 requests and 5 variables each and imagine dealing with 150 variables.) One-off variables that people don't have any intention of changing run counter to the spirit of environment or collection variables.

If we could change those 10 values from literals to variables with defaults, e.g.  from `24` to `{{count:24}}`, in the POST body, I could easily reuse the same request between the collection runner and a manually triggered request. If no variable is found, 24 is sent. If I provide a data variable called `count`, it's value would be sent.  Without ever declaring an environment or collection variable.

**Comment by oxygenecore** [comment]
I would also want to have default values for local variables (appearing in one step, for example) without having to expose this variable to the whole collection.
