### ISSUE TITLE
Remove Snippet for "Reason phrase has string"

### ISSUE THREAD

**Issue by StoicNZ** [a85/POSTMan-Chrome-Extension#3096]
1. Postman Version: 4.11.0-canary02
 2. App (Chrome app or Mac app): Windows Native
 3. OS details: Win x64

The "created" string should be capitalised since most websites return it that way, but I'd consider removing this snippet altogether to do away with people implementing reason-phrase when HTTP/2 has done away with it altogether. (And I'll pretend SPDY doesn't exist since they want to allow anything for the status.)

For example load up this HTTP/1.1 website in Chrome and look at your Network tab - see under General > Headers > Status Code it says "200 OK"?
https://www.w3.org/Protocols/HTTP/Performance/microscape/

Now open up Google and do the same - you should only see the Status Code. HTTP/2 is here! Woo!

Don't remove the functionality, but I'd definitely suggest removing the snippet altogether given the wave of new RESTful API developers and testers who rely on Postman and build it into their tools without knowledge of the HTTP spec itself.

![image](https://cloud.githubusercontent.com/assets/5607534/26669378/fb05096c-46f0-11e7-8ba6-dd1a27bf11db.png)

**Expected**
```
//yo dawg, i herd u leik HTTP/1.1, but what about HTTP/2? think about the future! or don't, and make everyone mad in a few years.
```

**Actual**
```
pm.test('expect status to have a specific reason', function () {
	pm.response.to.have.status('created');
});
```

**Comment by prashantagarwal** [comment]
@StoicNZ thanks for the feedback. The new snippets are still under rigorous testing and that's why we have not released them to the production app yet. We will keep a note of this.

**Comment by shamasis** [comment]
The reason phrase capitalisation has been fixed to match RFC https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.2.2 .

It now looks like
```javascript
pm.test("Status code name has string", function () {
    pm.response.to.have.status("Created");
});
```

Meanwhile, we would work towards improving auto-complete and other such in-editor feature to better improve the experience.
