### ISSUE TITLE
Postman app doesn't handle login with google account if 2 factor authentication is enabled

### ISSUE THREAD

**Issue by amahlaka** [a85/POSTMan-Chrome-Extension#3098]
1. Postman Version: 4.11
 2. App (Chrome app or Mac app): Chrome
 3. OS details: Windows 10 Pro
 4. Is the Interceptor on and enabled in the app: Yes
 5. Did you encounter this recently, or has this bug always been there: Unknown
 6. Expected behaviour: Log in with google account 
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app): TBD
 8. Screenshots (if applicable)

Steps to reproduce the problem:
Click> Sign in with Google
Enter google account email and password
Click Login in
Expected result: if account has 2fa enabled, wait for user to complete the challenge ( code, securite key etc) and log in after that
What Happens: The 2 Factor authentication window opens and immediately closes, causing the login to fail, resulting in error on top of the window: Failed to login

**Comment by numaanashraf** [comment]
@amahlaka Thanks for reporting. We are looking into this.

**Comment by curtiscook** [comment]
I'm running into this on mac chrome as well. Postman throws a "could not login" error and prematurely closes the 2FA window

**Comment by ai7** [comment]
Running into this issue too. Postman prematurely closes the 2FA window.

**Comment by kissgyorgy** [comment]
On Linux it says "You can only use your Security Keys with Google Chrome."

**Comment by thecuriousdev** [comment]
Hey All, Can you try updating your app to the latest version (6.1.2+), And please let us know if you are still facing this issue.

**Comment by kissgyorgy** [comment]
Same for me with 6.1.3 "You can only use your Security Keys with Google Chrome"

**Comment by calebmathis** [comment]
MacOS High Sierra
Postman 6.1.3
"You can only use your Security Keys with Google Chrome"
"Try Another Way", clicks, security key is the only option!?!

**Comment by calebmathis** [comment]
OK, my bad. Just needed to add another 2-factor method (like my phone) through my google account settings first. Then I can use it :)

**Comment by SamvelRaja** [comment]
Duplicate of #3697
