### ISSUE TITLE
Export v2 collection results in empty collection json file

### ISSUE THREAD

**Issue by bquack** [a85/POSTMan-Chrome-Extension#3099]
1. Postman Version: 4.11.0
 2. App (Chrome app or Mac app): Chrome app
 3. OS details: Windows 10
 4. Is the Interceptor on and enabled in the app: No
 5. Did you encounter this recently, or has this bug always been there: Once updating to 4.11.0 from 4.7.10
 6. Expected behaviour: Export a v2 collection 
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 8. Screenshots (if applicable)

1. Open Postman
2. Delete all collections from the collection pane
3. Import a collection (any previously v2 collection you might have)
4. Export that collection
5. The json file ends up being 1kb with an empty item array. So NONE of the folders/tests/etc... are exported to the json file. This is all I end up with:

{
	"variables": [],
	"info": {
		"name": "My-Collection-v1.0",
		"_postman_id": "d09373da-a00c-9728-b3db-bb5932c49afa",
		"description": "",
		"schema": "https://schema.getpostman.com/json/collection/v2.0.0/collection.json"
	},
	"item": []
}

I have confirmed this issue with 2 other machines running Postman v4.11.0. I tested this on v4.10.7 prior to upgrading to v4.11.0 and did not have any issues.

This is a critical blocker as you cannot export your collections from Postman.

**Comment by numaanashraf** [comment]
@bquack Thanks for reporting. We are looking into this issue and will keep you posted.

**Comment by numaanashraf** [comment]
@bquack Would it be possible to send a sample collection to help@getpostman.com? It'll help us a lot in debugging this.

**Comment by bquack** [comment]
@numaanashraf I just emailed a collection to you. Also, for anyone else looking at this ticket:

I tried a few things and one thing that seems strange is if I import this collection, then rename any one of the folders, then export it exports fine. I then diffed the export to the original that I imported and the only differences were the folder name change and the info._postman_id.

I get the feeling that something else is going on here that is not related to how the collection json is formed. I tried some other things like deleting the Postman IndexedDB in Chrome and modifying the info._postman_id directly in the original json prior to importing, but that doesn't fix the issue.

**Comment by numaanashraf** [comment]
@bquack Thanks for sending the collection file. We identified the root cause and have fixed this in an internal build. We'll roll this out in the upcoming release.

**Comment by bquack** [comment]
@numaanashraf  Thank you so much for tackling this so quickly. May I ask what was the cause? Also, do you have a date for the next release?

**Comment by bquack** [comment]
I was able to verify this is now fixed. Tested in version 5.0.0

Thanks for the quick turnaround!

**Comment by hoogenbj** [comment]
Hi, this bug should be reopened. It happens on Linux (64-bit) in version 5.1.3!
Look at this empty collection I exported:
{
	"variables": [],
	"info": {
		"name": "Product Summary",
		"_postman_id": "af41194f-9ee7-544c-6300-de9279cbab10",
		"schema": "https://schema.getpostman.com/json/collection/v2.0.0/collection.json"
	},
	"item": []
}

**Comment by Moegamad** [comment]
I agree, this bug has resurfaced, i am having same issue on Windows 10 postman version 5.1.3 as well.
Empty collection exported:
{
	"variables": [],
	"info": {
		"name": "DATA",
		"_postman_id": "961996fb-d18c-16c8-dab9-5adff4513593",
		"description": "",
		"schema": "https://schema.getpostman.com/json/collection/v2.0.0/collection.json"
	},
	"item": []
}

**Comment by sdnts** [comment]
We're looking into this. At first glance, it looks like older collections are misbehaving, collections created recently do not have this problem. Thanks for bring this to our notice.

**Comment by Moegamad** [comment]
@madebysid great, thanks! hope it gets sorted soon

**Comment by jehof** [comment]
I have a similar problem. Exporting to CollectionV2 format results in an empty collection, while exporting to CollectionV1 format works. I´m on 5.2.0 on Win10

**Comment by moquist** [comment]
I've got the same issue. I'm importing a WADL file and then trying to export it, and a v2 export is empty (as shown above, by Moegamad) unless I modify it somehow, first. Renaming the collection seems sufficient to provoke an actual v2 export. I've tested with several versions, but I'm currently using Postman-linux-x64-5.3.2.

**Comment by kalmas** [comment]
@moquist's collection rename collection workaround worked for me. Version 5.3.2 for win64.

**Comment by nick-randal** [comment]
Still Broken in 5.5.0 but the workaround is still valid.

**Comment by Sneha174** [comment]
This issue still exists for me and the renaming workaround is not working. Exporting results in empty collection for v1, v2 as well as v2.1. I'm running postman windows app v6.1.2.

**Comment by snspinn** [comment]
I have a similar issue. All test in my collection but the last are omitted from the collection.
This is a new collection. I have tried exporting in v2.1, v2 and v1 in that order and they all seem to have same issue.
This only cropped up recently and I have managed to export collection successfully before this only last week..

**Comment by numaanashraf** [comment]
@goldfishalpha could you let us know which Postman app version you are using?

**Comment by snspinn** [comment]
@numaanashraf Thanks for the reply.
I'm using v6.2.3 .

**Comment by numaanashraf** [comment]
@goldfishalpha Could you share screenshots showing the issue? We are having trouble replicating this at our end.

**Comment by numaanashraf** [comment]
@goldfishalpha Also, please open the app's devtools via (View > Show DevTools (Current View)) and send us a screenshot of any errors there after trying to export.

**Comment by snspinn** [comment]
@numaanashraf,
I sent those screen shots on to  help@getpostman.com

I forgot to mention my original problem before I came upon this one: The
urls were not being included in the collection either.
I started by manually adding these fields AFTER exporting the collection.

Attached are warnings I get when exporting my collection (1 warning each
time I do).
I have also included a screenshot of my postman runner when I try to run
the collection.

I do not see any error in the DevTools. However, I am fairly new to Postman
so may definitely have missed something.

Many Thanks

**Comment by snspinn** [comment]
So looks like I made a major oversight.
I had not saved changes to each request (tab) in the collection before I exported them or ran them!
I had hit the save button several times before without realizing the save would only take effect on the current request tab I had selected/highlighted and not all of them.

This seems like a strange setup in the GUI as I had closed postman (without closing individual tabs) and restarted my machine without being prompted to save any work I had done. (Granted, I did not lose progress as all work was still there on restart)
It also seems strange to me to be able to export a collection that excludes recent changes. I'm sure there is a good reason for this though. Maybe a "save all changes and export" alongside the current "export" option maybe useful?

I am posting this in case anyone makes the same mistakes as me though it is entirely likely this will not be the case.

**Comment by numaanashraf** [comment]
@goldfishalpha Glad to know this is resolved. We agree that unsaved edits not being exported or used in collection runs can be a source of confusion and are part of the learning curve of. We'll get better at this with better documentation and communication within the app.

/cc @vkaegis

**Comment by nephisha** [comment]
When exporting a collection as v2.1 -- The resulting collection.json file doesn't have the body for any POST request. It is seen as "body": {
					"mode": "raw",
					"raw": ""
				}

But the actual POST request in the Postman app has a Json Body defined.

**Comment by snspinn** [comment]
@nephista in case you are making the same mistake as me; are all changes made to EACH POST request saved?
 If the request tab has a red/orange dot on it, the changes have not been saved

**Comment by kamalaknn** [comment]
@nephisha 

Are you on the `6.2.4-canary01`?

We are aware of an issue where raw body is not exported in the collection. We are pushing a fix for this on the canary channel soon. 

**PostmanCanary 6.2.4-canary01 is the only version that is affected by this. The current production channel does not have issues with raw body on exports**

**Comment by kamalaknn** [comment]
Hey @nephisha 

This is fixed and released as `6.2.4-canary02`

**Comment by mahmudbodurov** [comment]
Hi. this app drive me crazy. up to date postman and new created collection all parameters right but export collection gives me
```
				{
					"name": "Get invoice status",
					"request": {
						"method": "GET",
						"header": [],
						"url": null
					},
					"response": []
				},
```
no urls no header no any parameters.

**Comment by yuranich** [comment]
> Hi. this app drive me crazy. up to date postman and new created collection all parameters right but export collection gives me
> 
> ```
> 				{
> 					"name": "Get invoice status",
> 					"request": {
> 						"method": "GET",
> 						"header": [],
> 						"url": null
> 					},
> 					"response": []
> 				},
> ```
> 
> no urls no header no any parameters.

@Mahmud989 it is not obvious, but to see a proper result on export you just need to save every request inside a collection.
Initially I thought they are saved automatically but turned out they are not.
