### ISSUE TITLE
Mac App throws uncaught exception if opened while updating

### ISSUE THREAD

**Issue by jb08** [a85/POSTMan-Chrome-Extension#3100]
Received this message after opening App for first time; after I closed, and then re-opened, it worked fine.

![screen shot 2017-06-01 at 11 19 20 am](https://cloud.githubusercontent.com/assets/8146460/26690755/1fe3ea18-46c0-11e7-8867-77f830a074e7.png)

 1. Postman Version: 4.11.0 (4.11.0)
 2. App (Chrome app or Mac app): Mac
 3. OS details: El Capitan

**Comment by numaanashraf** [comment]
@jb08 Thanks for reporting. Do you remember doing any extra steps the first time? Maybe opening the app from Downloads and then moving it to Applications?

**Comment by jb08** [comment]
I was upgrading from previous version. I was expecting it to open on its own, it was being slow so I clicked on postman app to open it, received that error. forced close, then reopened and it worked fine and said updated successfully.

**Comment by numaanashraf** [comment]
@jb08 Ah. Got it. It seems you opened the app while it was in the middle of updating itself, which might sometimes take a bit longer depending on CPU and hard disk load. We'll look into how we can detect this and show a helpful message.
