### ISSUE TITLE
Feature request: Add RSA-SHA1 to the OAuth 1 dropdown

### ISSUE THREAD

**Issue by mp3killa** [a85/POSTMan-Chrome-Extension#3101]
1. Postman Version: 4.11.0
 2. App (Chrome app or Mac app): Chrome App
 3. OS details: Windows 10 x64
 4. Is the Interceptor on and enabled in the app: N/A
 5. Did you encounter this recently, or has this bug always been there: always
 6. Expected behaviour: Please add RSA-SHA1 to the dropdown for OAuth1.0 or at least allow edits to be made directly to the URL without the changes getting overwritten on "Send"

**Comment by prashantagarwal** [comment]
Thanks for reporting this. We will keep you updated on any progress on thisl

**Comment by jachin84** [comment]
+1

**Comment by kamalaknn** [comment]
duplicate of https://github.com/postmanlabs/postman-app-support/issues/2302
