### ISSUE TITLE
Support To Download Postman Pro Published HTML Documentation

### ISSUE THREAD

**Issue by ypolishetty** [a85/POSTMan-Chrome-Extension#3102]
Team,

Could you please add support to download Postman Published HTML documentation?

I know that I could publish Postman Documentation including on my Custom Domain and also generate HTML with docman (https://github.com/davidevernizzi/docman) . But we'd still want to request if a future support for download of the actual postman pro published docs is possible.

**Comment by a85** [comment]
Sorry but this is not on our roadmap.

**Comment by ypolishetty** [comment]
Fine, Thanks.
