### ISSUE TITLE
AWS default credentials

### ISSUE THREAD

**Issue by DraakUSA** [a85/POSTMan-Chrome-Extension#3103]
1. Postman Version: 4.11.0
 2. App (Chrome app or Mac app): Windows App
 3. OS details: Windows 10
 4. Is the Interceptor on and enabled in the app: ??
 5. Did you encounter this recently, or has this bug always been there: Always been there (from what I can tell)
 6. Expected behaviour: Ability to read credentials file
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 8. Screenshots (if applicable)

AccessKey, SecretKey, and Session Token, are regenerated once an hour.  Would like the ability to read aws credentials file to retrive these values.  I have several profiles that are auto updated during this regenerating.  I would like the ability to supply a profile name, and have postman automatically grab the correct information so I don't need to constantly cut and paste this.  If this is doable via a pre-request script please point me to where I can find it.

**Comment by kamalaknn** [comment]
Hey @DraakUSA 

Thank you for your feedback. 

We are working on adding a bunch of improvements to authentication flows from Postman. We'll see how we can fit this in our long term roadmap.

Marking this as a feature request for now.

Thanks

**Comment by DraakUSA** [comment]
Even if it's the ability to read an INI file and set the environment variables via the pre-request script would be useful to do this.

**Comment by harryi3t** [comment]
@DraakUSA Reading file from test scripts is not supported in Postman.
But, you can always use Runner + data file for this.

create a file data.csv having all the values
```
AccessKey,SecretKey,Session Token
xxxxxxxxx,xxxxxxxxx,xxxxxxxxxxxxx
```

open runner and click on `select file`, pick the file created above
![image](https://user-images.githubusercontent.com/5207331/30581072-80e810dc-9d3c-11e7-92c8-5a58b1c765f4.png)

Verify the details are correct by clicking on `preview`
![image](https://user-images.githubusercontent.com/5207331/30581096-8f7e0052-9d3c-11e7-912f-a66a352fbd4c.png)

Now when you run the collection, it will pick these values

Let me know if you face some issues.

**Comment by harryi3t** [comment]
Also, can you let me know how these values are updating?

**Comment by nagarajatantry** [comment]
@harryi3t I am in similar situation.  Temporary tokens are generated  automatically and my .aws/credentials file get updated.  If postman can read the values from this file location by default based on profile. it would save a bunch of time.

**Comment by DraakUSA** [comment]
We have an inhouse script that keeps a user's .aws/credentials file up to date with new tokens before they expire.  These tokens expire for business security, and are retrieved via SAML tokens.  The reason is that the aws client uses the AWS_PROFILE environment variable or the specified --profile on the command line to get the correct tokens from the .aws/config and/or .aws/credentials file to get tokens.

A sample profile  in the credentials file looks like:

```
[profile-name]
aws_access_key_id=<AccessKey>
aws_secret_access_key=<SecretKey>
aws_session_token=<Session Token>
region=us-east-1
output=json
<other keys and values>

[next-profile]
  :

```
It would be nice if we could enter a profile name when we have AWS Authentication selected and have Postman automatically look up the needed values from the config and/or credentials file.  The credentials file has priority over the config file.

Ref: https://docs.aws.amazon.com/cli/latest/userguide/cli-config-files.html

**Comment by nagarajatantry** [comment]
@DraakUSA @harryi3t  I have come up with a workaround using `Pre-request Scripts`.  
- Use below Code snippet in Pre-Request Scripts tab
```
pm.sendRequest("http://localhost:8888/aws_keys/<profile name>", (err, res) => { 

    var data = JSON.parse(res.text());
    pm.environment.set("access_key", data['aws_access_key_id'])
    pm.environment.set("secret_key", data['aws_secret_access_key'])
    pm.environment.set("session_token", data['aws_session_token'])
});
```
- In the Authorization section, set Access Key, Secret Key and Session Token with   `{{acess_key}}` ,  `{{secret_key}}` and  `{{session_token}}`
- `http://localhost:8888/aws_keys/<profile name>` is a simple rest api I developed which responds with the keys for a given Profile. Using AWS SDK internally to pick the keys from credentials file.  Response from API will be like
```
{
    "aws_access_key_id": "foo",
    "aws_secret_access_key": "bar",
    "aws_session_token": "temp"
}
```
Note: In my bash script, I start this api and keep it running by default all the time.

**Comment by shamasis** [comment]
I don't think we would build reading external password files directly. It has huge security implications and various API CLI vendors have their own storage locations and it would be very difficult to keep pace with it.

However, knowing that we are working towards a plugin-based approach to various parts of Postman, this may be implemented as a plugin in future.

**Comment by a85** [comment]
Closing as a security risk. Our plug-in system will solve for this in the future.

**Comment by kibiz0r** [comment]
@a85: Does the plug-in system solve this now?

Edit: Like others here, I'm trying to streamline development in an environment where the credentials reset hourly.

For any future readers: You could add some more security around @tannaga's recommendation by encrypting the response with a public key and keep the private key in your Postman collection so you don't accidentally serve creds to anyone who asks.

**Comment by rcollette** [comment]
I want to import from API Gateway but it does not provide a way to specify session token.   It would be great if this would support typical AWS credential resolution mechanisms (credential file, environment variables, etc.).  If Postman is using the AWS SDK, then credential discovery should be rather simple.
