### ISSUE TITLE
HttpOnly cookie not being set after deleting it manually (v4.11.0 Native OSX)

### ISSUE THREAD

**Issue by miqmago** [a85/POSTMan-Chrome-Extension#3104]
1. Postman Version: 4.11.0
 2. App (Chrome app or Mac app): Mac app
 3. OS details: 10.11.6
 4. Is the Interceptor on and enabled in the app: N/A
 5. Did you encounter this recently, or has this bug always been there: related https://github.com/postmanlabs/postman-app-support/issues/2258
 6. Expected behaviour: Cookie should be set and visible in Manage Cookies
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
```

POST

POST
http://macmiquel.local:3000/api/v1/user/login
06:12:20.756
Request Headers:
cache-control:"no-cache"
Content-Type:"application/x-www-form-urlencoded"
User-Agent:"PostmanRuntime/6.1.6"
Accept:"*/*"
Host:"macmiquel.local:3000"
accept-encoding:"gzip, deflate"
content-length:50
Response Headers:
x-powered-by:"Express"
set-cookie:"connect.sid=s%3A3UGQIJofM6QLOxdQtQRWJtsDi2c8TATE.8nzKdnugh6FJvJN3FuBaH4FvAuLPH5Cib6lL1eLjiTs; Path=/; Expires=Fri, 02 Jun 2017 04:27:20 GMT; HttpOnly"
access-control-allow-origin:
undefined
access-control-allow-credentials:"true"
content-type:"application/json; charset=utf-8"
content-length:"412"
etag:"W/"19c-1YUYQFVMkyDlauuVeGA8AQ""
vary:"Accept-Encoding"
date:"Fri, 02 Jun 2017 04:12:20 GMT"
connection:"keep-alive"
```

Steps to reproduce the problem:

1. Open Cookie dialog and remove any session cookies for the domain
2. Make a request to a site that returns session and httponly cookie
3. The session cookie will not be set, but any other cookies will

If the session cookie was already present (previous versions were doing fine), the cookie is changed, once you drop it from cookies it will never be saved again.

Also another weird thing is that in response pane Headers, I can see the two cookies (connect.sid and lang), only lang (not httponly) is being set, but in console logs I can't see lang set-cookie header.

![captura de pantalla 2017-06-02 a les 6 12 58](https://cloud.githubusercontent.com/assets/1849488/26710504/980a196e-475a-11e7-9af7-58a8cc0c6d74.png)

![captura de pantalla 2017-06-02 a les 6 13 04](https://cloud.githubusercontent.com/assets/1849488/26710299/360e76b6-4759-11e7-8c6c-3bb7176d0d9b.png)

**Comment by miqmago** [comment]
Also noted that when I try to set it manually it does only work when domain is specified:

1. Open cookie dialog
2. Add Cookie
3. Paste `connect.sid=s%3A3UGQIJofM6QLOxdQtQRWJtsDi2c8TATE.8nzKdnugh6FJvJN3FuBaH4FvAuLPH5Cib6lL1eLjiTs; Path=/; Expires=Fri, 02 Jun 2017 06:27:20 GMT; HttpOnly`
4. Save. At this point, the name of the cookie will not be changed, remaining to Cookie_4
5. Close cookie dialog
6. Reopen cookie dialog and cookie will not be there

Another case:

1. Open cookie dialog
2. Add cookie
3. Paste `connect.sid=s%3A3UGQIJofM6QLOxdQtQRWJtsDi2c8TATE.8nzKdnugh6FJvJN3FuBaH4FvAuLPH5Cib6lL1eLjiTs; path=/; domain=.macmiquel.local; HttpOnly; Expires=Fri Jun 02 2017 06:27:20 GMT+0200 (CEST);`
4. Save. At this point, the name of the cookie will be saved
5. Close cookie dialog
6. Reopen cookie dialog and magically cookie is there

**Comment by prashantagarwal** [comment]
@miqmago Thanks for reporting this.

**Comment by kamalaknn** [comment]
Hey @miqmago,

We are seeing some issues where cookies with a small `Max-Age` or a shorter `Expires` is not being persisted.

From the data you've provided I could see that your `Expires` is short for the cookie. Also I could see that you are using a local server. Could you increase the `Expires` in the `set-cookie` header on your local server to a day and check if it works?

We will roll out a fix for this soon.

Thanks.

**Comment by miqmago** [comment]
Seems a problem of timezone:

This works:

```
maxAge: 2 * 3600 * 1000 + 2000

connect.sid=s%3AuxNcwO25qzO6JhGtxL4Z-svw5wCRsle-.QsjyuZaxrCxm77LQUzsgMK7ECQU3gFZhTLsT0dH8d04; Path=/; Expires=Fri, 02 Jun 2017 09:07:44 GMT; HttpOnly

Local computer hour: 9:07
```

This does not:

```
maxAge: 2 * 3600 * 1000 + 1000

connect.sid=s%3AjM-jteVdFZ6_6xP3PSqcXFXluac-Q3Ml.r3YxGOYlFHIkNJ1OL3ST5kZSfI1wVOIvz7sYEe1PUdQ; Path=/; Expires=Fri, 02 Jun 2017 09:17:39 GMT; HttpOnly

Local computer time: 09:17
```

This 1000ms I suppose it's not working because of postman computing time.

**Comment by kamalaknn** [comment]
@miqmago Ah!

This is because the timezone of the cookie was being converted to your timezone. That is why you were not seeing the cookie stored, because it would have already expired.

We have fixed this internally and will roll it out to production soon. 

I will update this thread once the fix is out in production.

**Comment by sdnts** [comment]
@miqmago This should be fixed in 5.1.2. Can you update and confirm?

**Comment by prashantagarwal** [comment]
@miqmago This is fixed in the latest Postman version. Feel free to reopen this issue if you still see it.

**Comment by AlmogCohen** [comment]
@prashantagarwal I'm experiencing the exact same issue on OSX with version 6.1.3 :(

1. Cookies where present in the Cookie Manager
2. I've deleted the JSESSIONID manually
3. Now it is not being set again even with the Set-Cookie header
4. Also, adding the cookie manually doesn't work.

What would you recommend doing? reopening an issue?

**Comment by stirp** [comment]
@AlmogCohen same here except that adding cookie manually worked for me.
I'm wondering if there is a way to add cookies from Tests. I can get HttpOnly cookies from postman.getResponseCookie($cookieName).

**Comment by Fixbruenix** [comment]
Same problem occurs on Windows with version 6.1.3.

**Comment by kkukshtel** [comment]
Is this still open? I'm having the same issue on Windows and OS X - getting a proper Set-Cookie header returned but nothing sticking in Postman or appearing in the Cookie tab.
