### ISSUE TITLE
[Feature Request] - Functionality to generate a Postman Pro URL through the Postman Client

### ISSUE THREAD

**Issue by Faz540** [a85/POSTMan-Chrome-Extension#3108]
Postman Pro works great, however I think obtaining the URIs from the Collection/Environment Endpoints can be improved.

If there are other ways to obtain the desired URI please let me know in case I'm missing something.

It would be cool if there was a 'Postman Pro' button.

- Clicking this opens a popup/menu etc. .
- The User manually enters their active Postman Pro API Key,
- Select a Test Collection from a dropdown list (similar to how the Collection Runner works)
- Select an Environment from a dropdown list (Again, similar to how the Collection Runner works)
- Then, the user clicks a 'Generate' button and the full URL is generated so the user can copy this.

**Example:**
newman run https://api.getpostman.com/collections/{{testCollectionURI}}?apikey={{postmanProAPIKey}} --environment https://api.getpostman.com/environments/{{environmentURI}}?apikey={{postmanProAPIKey}}

**Comment by numaanashraf** [comment]
Thanks for the suggestion @Faz540. We'll keep this use-case in mind while we improve Postman Pro.

**Comment by davidespihernandez** [comment]
Closing this as it's been more than 5 years since the issue was created. Postman has evolved a lot since then, and I think this probably makes no sense currently.

**Comment by DannyDainton** [comment]
With the introduction of the Postman CLI and the ability to run Collections in a CI/CD pipeline, the original feature request/use case has evolved slightly, as the product has in that time.

The platform now auto-generates those run commands and pipeline configs, while also giving you the option to create a new API Key at the same time.

![image](https://user-images.githubusercontent.com/17089546/211583023-b8efa4b2-31d9-4fb9-863f-82a95901e5a3.png)
