### ISSUE TITLE
[Feature Request] Ability to close all tabs inside of postman app simultaneously or similar functionality like Chrome browser to close tabs

### ISSUE THREAD

**Issue by mpurwar** [a85/POSTMan-Chrome-Extension#3109]
1. Postman Version: 4.11.0
 2. App (Chrome app or Mac app): Chrome
 3. OS details: Windows 10
 4. Is the Interceptor on and enabled in the app: No
 5. Did you encounter this recently, or has this bug always been there: 
 6. Expected behaviour: Ability to close multiple tabs simultaneously.
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 8. Screenshots (if applicable)

**Comment by numaanashraf** [comment]
Thanks for the suggestion @muditpurwar. We'll look into this as we work on improving the tabs functionality.

**Comment by a85** [comment]
Close all tabs is available in native apps in 5.0+. This feature won't make it to the Chrome app unfortunately in the near future.

**Comment by prmichaelsen** [comment]
Ok. So this feature has been implemented. Now how do I use it?

**Comment by deepakpathania-zz** [comment]
@prmichaelsen Simply click on the ellipsis in the tab section in the builder for the dropdown to appear and then select 'Close All Tabs'. Image attached for reference. 

![selection_010](https://user-images.githubusercontent.com/15071438/31831321-a175eda8-b5e0-11e7-8673-1f251c5ac3d0.png)

**Comment by prmichaelsen** [comment]
Thank you!

**Comment by cegprakash** [comment]
When we have more than 50 tabs open, the 3 dots button is not visible. And as there is no scrollbar, it is very hard to make it visible again. I had to close each tab at the end manually (also had to respond to the alert box for each tab) until the 3 dots menu is visible.

Shall we reopen this please..

**Comment by bhargavkaranam** [comment]
Hi @cegprakash,
This issue has been addressed in the latest version of the Postman app. Along with this, there are a bunch of other improvements that have been made to the way tabs work in Postman. Please update your app to the latest version.
