### ISSUE TITLE
Login Sync : Missing Raw Body

### ISSUE THREAD

**Issue by sburtonctr** [a85/POSTMan-Chrome-Extension#3110]
Version/App Information:

 1. Postman Version:  4.10.7 
 2. App Windows
 3. OS details: Windows 10
 4. Is the Interceptor on and enabled in the app: None
 5. Don't know how long this has been an issue
 6. Expected behaviour:  Data should re-sync

**ISSUE:**
1.  Logout Postman Pro Account  (All data will be wiped from the windows postman app)
2.  Login Postman Pro Account (All data is restored).
3.  Most of my post test are missing its raw body.  Seems to be in only a few folders that this is happening.  But every test in that folder is missing its data.

4.  To Fix it I have to delete everything and reload from my exported file that I generated by using settings/data

If you want my exported file, I am happen to provide it if you need it.

**Comment by numaanashraf** [comment]
Thanks for the report @sburtonctr. We are looking into this.

**Comment by SamvelRaja** [comment]
Can you try updating to our latest 5.2.0 version of the app which has lots of improvements around our sync layer? closing this, for now, feel free to reopen this if you still face this issue.

**Comment by mariogalic** [comment]
I have lost bodies for all POST requests after syncing with Postman 6.0.10. I did not perform an export prior to the sync. Any chance this can be recovered?
