### ISSUE TITLE
Duplicate parameters added to URL using Collection Runner

### ISSUE THREAD

**Issue by codetotest** [a85/POSTMan-Chrome-Extension#3111]
1. Postman Version:  4.11.0 (4.11.0)
 2. App (Chrome app or Mac app): Mac App
 3. OS details: Osx
 4. Is the Interceptor on and enabled in the app: No
 5. Did you encounter this recently, or has this bug always been there: Yes (may be bug introduced)
 6. Expected behaviour:  should not add anything extra otherthan what is configured
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 8. Screenshots (if applicable)

**https://domain.com/v1/Login?email=email@domain.com&pwd=password/?email@domain.com&pwd=password**

**Comment by codetotest** [comment]
It works fine when request send from editor...itself

**Comment by numaanashraf** [comment]
@codetotest Thanks for reporting. We are looking into this.

**Comment by sdnts** [comment]
Hi @codetotest Is this happening from the authorization helpers? Can you provide me a way to reproduce this?

**Comment by codetotest** [comment]
@madebysid - below the steps to repro:

1. Create new Collection .
2. Create new request - change it to type post and enter URL...
3. Add a header value (in my I needed - not sure if that'll make any difference..)
4. Save the request to the collection.
5. Now export the collection using V2

following object is what I noticed in Json file ,which is causing the issue ..
```
{
    "name": "login",
    "request": {
        "url": {
            "raw": "{{url}}/v1/Login?email=username@domain.com&pwd=P@ssword",
            "auth": {
                "user": "{{url}}/v1/Login?email=sc-apm-all@persona.com&pwd=P",
                "password": ""
            },
            "host": [
                "@ssword"
            ],
            "path": [
                ""
            ],
            "query": [
                {
                    "key": "email",
                    "value": "username@domain.com",
                    "equals": true,
                    "description": ""
                },
                {
                    "key": "pwd",
                    "value": "P@ssword",
                    "equals": true,
                    "description": ""
                }
            ],
            "variable": []
        },
        "method": "POST",
        "header": [
            {
                "key": "Referer",
                "value": "/app/",
                "description": ""
            }
        ],
        "body": {},
        "description": ""
    },
    "response": []
}
```


Hope this is helpful and let me know if there is anything else I can help with..

**Comment by GabrielGM** [comment]
I have the same problem with the recent versions of Postman, when I import and export again (**Collection v2**), it duplicates my parameters.

Running **Windows 10** app.
Postman **v4.11.1**

**First export:**

`
...
"variable": [
{
	"value": "{{catalogId}}",
	"id": "id",
	"description": ""
}
]
...
`

**Import and export again without modification:**
`
"variable": [
								{
									"value": "{{catalogId}}",
									"id": "id",
									"description": ""
								},
								{
									"value": "{{catalogId}}",
									"id": "id"
								}
							]
`

Note: In the UI, it always displays correctly.
![image](https://cloud.githubusercontent.com/assets/8442923/26831465/6364dd5a-4a9a-11e7-8091-e197d3e90879.png)

**Comment by codetotest** [comment]
Duplicate issue reported and fixed --  https://github.com/postmanlabs/postman-app-support/issues/3141 

@madebysid @kamalaknn  -- fyi
