### ISSUE TITLE
Problem with setting environment variable using the runner in native app v4.11.0 

### ISSUE THREAD

**Issue by bahar-p** [a85/POSTMan-Chrome-Extension#3112]
1. Postman Version: v4.11.0
 2. App (Chrome app or Mac app): Native App
 3. OS details: Windows 7
 4. Is the Interceptor on and enabled in the app: disable
 5. Did you encounter this recently, or has this bug always been there: Just recent when I updated to v4.11.0 on the native app. Didn't have problem with it before
 6. Expected behaviour: When "postman.setEnvironmentVariable" is executed in the script using the runner, the current Environment file used in the call should be updated with defined Env variable and its value. 
 7. Console logs:

**Test - Pre-script code:**
`
if (data["Username"] !== undefined && data["Password"] !== undefined) {
   postman.setEnvironmentVariable("WS_USERNAME", data["Username"]);
   postman.setEnvironmentVariable("WS_PASSWORD", data["Password"]);

   console.log(`Setting credentials to ${data["Username"]} and ${data["Password"]}`);
   console.log(`Reading environment variable: 
                      environment["WS_USERNAME"]: ${environment["WS_USERNAME"]} -- 
                      environment["WS_USERNAME"]:  ${environment["WS_USERNAME"]}` );
}
`

**Sample output Logs:**
`Setting credentials to  test1 and  test1`
`Reading environment variable: environment["WS_USERNAME"]:  test1 -- environment["WS_USERNAME"]:  test1`
`Setting credentials to  test2 and  test2`
`Reading environment variable: environment["WS_USERNAME"]:  test2 -- environment["WS_USERNAME"]:  test2`

**Note:**
As can be seen from debug logs, although `environment["var"]` contains the value, after the test is executed, the environment file is not updated and does not contain the new variable. Seems like as issue with `postman.setEnvironmentVariable` call

 8. Screenshots (if applicable)
NA

**Comment by sdnts** [comment]
Hi @bahar-p When you say the environment file is not updated, do you mean the environment value in the main app isn't updated? If so, did you have the `Persist Variables` checkbox ticked when starting the run?

**Comment by bahar-p** [comment]
@madebysid Good point! It was unchecked mistakenly. I normally have it checked by default and missed the fact that it had gotten unchecked...Thanks for pointing that out. I will close the issue :)
