### ISSUE TITLE
Will you add a feature to 'copy curl command'?

### ISSUE THREAD

**Issue by maicss** [a85/POSTMan-Chrome-Extension#3113]
When right click on a request, shows a option `copy curl command`.

Thanks.

**Comment by numaanashraf** [comment]
@maicss Thanks for the suggestion. 😃

**Comment by maicss** [comment]
Thank you very much!!!!

**Comment by a85** [comment]
@maicss You can use the "Code" option now to generate code in curl as well as other commands. There are no plans immediately to add to the context menu in Postman.

**Comment by maicss** [comment]
How to use `code` command in chrome extensions?

**Comment by maicss** [comment]
```
GET /users/4 HTTP/1.1
Host: 127.0.0.1:9100
Cache-Control: no-cache
Postman-Token: 27371f8c-7800-fd8f-dfc6-5cbec0db0ce5
```
You means this?

Compare to write a curl command directly, which prefers easier?

Forget about it......
