### ISSUE TITLE
4.11.0-canary02: Collection Runner Not Detecting Tests

### ISSUE THREAD

**Issue by StoicNZ** [a85/POSTMan-Chrome-Extension#3114]
1. Postman Version: 4.11.0-canary02
 2. App (Chrome app or Mac app): Native Windows
 3. OS details: Windows x64
 4. Is the Interceptor on and enabled in the app: No
 5. Did you encounter this recently, or has this bug always been there: Recently
 6. Expected behaviour: Produce runner results
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 8. Screenshots (if applicable)

(Might be just the new library definition)

Created Get with Tests to Fail
![image](https://cloud.githubusercontent.com/assets/5607534/26777366/42ee090e-4a20-11e7-9bc0-c8aa701e6242.png)

Runner
![image](https://cloud.githubusercontent.com/assets/5607534/26777414/79571d64-4a20-11e7-9f52-561f5f57f6fd.png)

**Comment by sdnts** [comment]
Hi @StoicNZ I was able to reproduce this. Let me check what's causing this. 🤔
 In the mean time, you can use the normal `tests` objet to write tests. That should work as expected.

**Comment by sdnts** [comment]
This should now be fixed in the current canary and stable releases. Closing. Please reopen if you're still seeing this.
