### ISSUE TITLE
Why on earth it add x-www-form-urlencoded header and do NOT REMOVE IT when click form-data!

### ISSUE THREAD

**Issue by dexcell** [a85/POSTMan-Chrome-Extension#3118]
WHY! WHY

Wasting hours try to find out what caused it. I thought my app doesnt work as expected.

 1. Postman Version:
 2. App (Chrome app or Mac app):
 3. OS details:
 4. Is the Interceptor on and enabled in the app:
 5. Did you encounter this recently, or has this bug always been there:
 6. Expected behaviour:
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 8. Screenshots (if applicable)

**Comment by SamvelRaja** [comment]
Tracking in #2366
