### ISSUE TITLE
Linux app 4.11.1 tarball throws errors when unpacked

### ISSUE THREAD

**Issue by danielcarr** [a85/POSTMan-Chrome-Extension#3119]
Version/App Information
------
 1. Postman Version: 4.11.1
 2. App (Chrome app or Mac app): Linux app
 3. OS details: OpenSUSE LEAP 42.2 (GNU/Linux Kernel 4.4.62-18.6 x86_64)
 4. Is the Interceptor on and enabled in the app: Not that I know of
 5. Did you encounter this recently, or has this bug always been there: It seems to be new in the latest version, I didn't encounter it when I upgraded to version 4.11.0 yesterday
 6. Expected behaviour: Unpacking the downloaded archive with `tar xzf ` should just work without ugly side effects
 7. Console logs : N/A
 8. Screenshots (if applicable): N/A
----

Steps to reproduce
------
1. Download the archive from https://dl.pstmn.io/download/latest/linux64
2. On the command line (assuming you're in the directory to which the archive was downloaded), run `tar xzf Postman-linux-x64-4.11.1.tar.gz` (or whatever the file has been called).
3. It should just work silently, creating a directory called `Postman`.
4. Although it does create the `Postman` directory, instead of working silently, it prints the following lines 32 times (ie 96 lines in all) 
```
tar: Ignoring unknown extended header keyword 'SCHILY.dev'
tar: Ignoring unknown extended header keyword 'SCHILY.ino'
tar: Ignoring unknown extended header keyword 'SCHILY.nlink'
```

While it technically works, it makes the upgrade process less pleasant, and it could potentially have a negative impact on more automated integrations of the upgrade process.

[Apparently](https://superuser.com/questions/318809/linux-os-x-tar-incompatibility-tarballs-created-on-os-x-give-errors-when-unt) this happens when a tarball is created with BSD tar and unpacked with GNU tar.

**Comment by sdnts** [comment]
Hi @danielcarr! Thanks for letting us know. We'll definitely look into this :)

**Comment by danielcarr** [comment]
Thanks @madebysid, I appreciate the quick response.

**Comment by kamalaknn** [comment]
Hi @danielcarr,

Thanks for sharing your feedback. This is something we might have missed if not for your feedback. 

We have made sure the packaging for linux is done in the right environments now. The next release and all future releases should not have this warnings.

Thanks, have a nice day.

**Comment by kamalaknn** [comment]
Hey @danielcarr 

We've fixed this in the latest version of the app. Could you check the `5.0.0` release and see if you still get the warnings?

Thanks.

**Comment by danielcarr** [comment]
Thanks @kamalaknn, I can confirm that it's working as expected (no warnings) in version 5.0.0

**Comment by danielcarr** [comment]
Thanks @kamalaknn, I can confirm that it's working as expected (no warnings) in version 5.0.0
