### ISSUE TITLE
JSON schema validation always returns true

### ISSUE THREAD

**Issue by edsonmedina** [a85/POSTMan-Chrome-Extension#3122]
1. Postman Version: browser app
 2. App (Chrome app or Mac app): chrome app
 3. OS details: Ubuntu 16.04

Steps to reproduce the problem:

Use the following test:
```
var jsonData = {}; // this is empty, so it should fail

var schema = {
 "data": {
    "type": "object",
    "properties": {
        "main": {
            "type": "object"
        }
    },
    "required": ["main", "zzz"]
 }
};

tests["Response is valid"] = tv4.validate(jsonData, schema);
```
Given `jsonData` is declared as empty, the schema validation should fail, but when I execute the test I get a green (success). Same thing happens independently of the content of `jsonData`.

**Comment by numaanashraf** [comment]
@edsonmedina Hi, I'm looking into this now.

**Comment by numaanashraf** [comment]
@edsonmedina That doesn't look like a valid schema. If you wanna validate `jsonData.main` and `jsonData.zzz`, the below schema should work.

```
var schema = {
    "type": "object",
    "properties": {
        "main": {
            "type": "object"
        }
    },
    "required": ["main", "zzz"]
};
```

**Comment by edsonmedina** [comment]
@numaanashraf I actually wanted to validate `jsonData.data.main`. 

So I tried:
```
var schema = {
    "type": "object",
    "properties": {
        "data": {
            "type": "object",
            "properties": {
                "main": {
                    "type": "object"
                }
            },
            "required": ["main", "zzz"]
        }
    }
};
```

But the result is still the same.

**Comment by edsonmedina** [comment]
Actually, I take that back. It did work.

Thank you very much.

**Comment by sanamvarma** [comment]
Hi,
I am facing a similar issue:
my response schema is

const  resSchema =
{ 
    "$schema": "http://json-schema.org/draft-04/schema#",
"required": ["T1","T2"] ,
"properties": 
{ 
    "topicId": { "type": "integer" }, 
    "topicNamesssss": { "type": "string" }, 
    "topicNote": { "type": "string" }, 
    "grade": { "type": "integer", }, 
   } 
  
};

My response is :
{
           "topicId": "1",
        "topicName": "2",
        "topicNote": "Area: Concept & informal units",
   
}

pm.expect(tv4.validate(response1, resSchema)).to.be.true; is always returning true.
I validated the same in a JSONvalidator and that correctly shows me the discrepancies between the schema and response. PFA screenshot for it.
![schema validation](https://user-images.githubusercontent.com/33303833/32709607-b8959274-c885-11e7-8fd2-694594403cf7.png)

Please let me know if any more details are needed.
Any help/suggestion would be appreciated.

**Comment by itLead797** [comment]
I'm running into the same issue tv4.validate is always returning true. 
Postman App: v5.5.0

**The test:**
if(responseCode.code === 200) {
    tests["Status code is " + responseCode.code] = responseCode.code === 200;
    var jsonData =  JSON.parse(responseBody);
    const schema = {
        "required": ["val1", "val2", "val3"],
        "properties": {
            "val1": { "type": "string" },
            "val2": { "type": "string" },
            "val3": { "type": "string" }
        }
    };
    try {
        tests["expected schema returned"] = tv4.validate(jsonData, schema);
        console.log("Validation errors: ", tv4.error);
    }
    catch(err) {
        tests["FAIL: Expected data not found"] = 'true' === 'false';
    }
} else {
    tests["Status code is " + responseCode.code] = responseCode.code === 200;
}

**The Response:**
[
    {
        "val1": null,
        "val2": null,
        "val3": null,
    }
]

**The Test Result:**
PASS expected schema returned
