### ISSUE TITLE
Variables within variables

### ISSUE THREAD

**Issue by hertzigger** [a85/POSTMan-Chrome-Extension#3123]
1. Postman Version: 4.11.0
 2. App (Chrome app or Mac app): Chrome
 3. OS details: Windows 10
 4. Is the Interceptor on and enabled in the app: no
 5. Did you encounter this recently, or has this bug always been there: Feature Request
 6. Expected behaviour: None
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 8. Screenshots (if applicable)

I would like to be able to include variables within other variables including dynamic ones. Please see my screen shot. 
![image](https://user-images.githubusercontent.com/4991108/26839081-e1f176b2-4ad9-11e7-82e7-56f76706bc45.png)

This would be even more powerful with extra dynamic variables like random names or such

**Comment by numaanashraf** [comment]
Hi @hertzigger, dynamic variable names are supported at the moment. However, we've disabled variable autocomplete in environment add/edit dialogs due to performance issues. We are working on enabling this back again.

**Comment by abhijitkane** [comment]
@hertzigger Feel free to re-open if nested variables aren't working for you.
