### ISSUE TITLE
Postman for Chrome (Linux) crashes at random moments

### ISSUE THREAD

**Issue by bpaczkowski** [a85/POSTMan-Chrome-Extension#3124]
1. Postman Version: 4.11.1
 2. App (Chrome app or Mac app): Chrome 58.0.3029.110 (64-bit)
 3. OS details: Linux
 4. Is the Interceptor on and enabled in the app: no
 5. Did you encounter this recently, or has this bug always been there: It's the second time I encountered this.
 6. Expected behaviour: Not to crash the application?
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app): Can't provide any, the app just outright crashes.
 8. Screenshots (if applicable)

Don't know the specific steps to reproduce. It seems to crash at random moments, sometimes instantly after I start the app, sometimes after I click a button or try to send a request. Previously I fixed it by removing all Postman data from my profile, I'm not going to do that now so I can help diagnose this issue, since this is not the first time this has happened.

Is there a way to check what crashes the application? Does Chrome keep any logs?

**Comment by numaanashraf** [comment]
@bpaczkowski Thanks for writing in. This is a known issue where Chrome on Linux aggressively closes packaged apps during spikes in resource usage. We are working on reducing the resource usage. In the meantime, we recommend you try out our Linux native app which shouldn't have any unforeseen crashes. You can get it at https://www.getpostman.com/apps.

**Comment by bpaczkowski** [comment]
Thanks! Didn't know there was a native Linux app.

**Comment by sworisbreathing** [comment]
I've just encountered this issue as well and can did some playing around with it. In my case I had a lot of open request tabs in Postman. If I clicked on another request in a postman collection, instead of opening the request up, Postman would crash. It happend 3 or 4 times in succession. I closed a few of the open tabs and it started working again, so I guess that kind of supports @numaanashraf's comment about Chrome killing it due to resource usage.

**Comment by covolution** [comment]
Hi, I am using the Native app on Linux and get random crashes so switching to that won't fix it.  Is there any sort of log file or crash reporting?  I just send basic json calls and it crashes at random.

**Comment by covolution** [comment]
Any ideas on how to find the problem?  It is crashing far to often to be usable.  I really like Postman but think I will have to change to something else unless I can get it to stop crashing when I need it.

**Comment by numaanashraf** [comment]
Hi @covolution, could you share more information with us? Like average size of the JSON responses, number of open tabs, environments and scripts in the requests. Also, have you noticed any particular action that triggers the crash, like sending a request, updating environments etc?

**Comment by covolution** [comment]
Unfortunately, I haven't found a pattern. That's why I was asking if there's a log file.  I have a basic collection that calls the ElasticSearch Api.  When I click "Send", the UI says "loading" and it crashes completely.

**Comment by Atulg23** [comment]
Every time i called request then crashing. I updated also but can't work. I like postman for testing. but i am finding another option

**Comment by vmarcinko** [comment]
Same thing here... Sometimes it crashed during first request, and sometimes it last just few requests. Native and chrome extension, regardless. Linux Mint BTW.

**Comment by numaanashraf** [comment]
Postman Chrome Apps are deprecated. Please use Postman for Linux (www.getpostman.com/downloads) and let us know if you are still facing this issue.
