### ISSUE TITLE
Version 4.11.1 Pre-request Script returns different request.data for GET request

### ISSUE THREAD

**Issue by msb333-msb333** [a85/POSTMan-Chrome-Extension#3125]
1. Postman Version: 4.11.1
 2. App (Chrome app or Mac app):  Chrome App
 3. OS details: Windows 7
 4. Is the Interceptor on and enabled in the app:
 5. Did you encounter this recently, or has this bug always been there:  Recent
 6. Expected behaviour:  Expected no data like 4.10.7
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 8. Screenshots (if applicable)

We do AWS Signatures using Pre-request Scripts.

Using version Postman 4.10.7:
Modify the Postman Echo, Auth: Digest, DigestAuth Request  to add a simple Pre-request script (URL:  GET https://postman-echo.com/digetst-auth):

console.log("payload=" + request.data);
console.log("hash=" + CryptoJS.SHA256(request.data));

It prints the following in the Console (this is expected):
payload=undefined
hash=e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855

Now use Postman Version 4.11.1 with the exact same setup.

It prints the following in the Console (this is unexpected):
payload=[object Object]
hash=4ea5c508a6566e76240543f8feb06fd457777be39549c4016436afda65d2330e

Further, when you capture the request in TCPDUMP on the HTTP server, the request body has the following (odd that a GET request would have any request body).

{"meta":{}}

**Comment by numaanashraf** [comment]
@msb333-msb333 Thanks for reporting. We are looking into this.

**Comment by sivcan** [comment]
Hi,
I suggest you to kindly use the native app of Postman since Chrome App is deprecated. -https://www.getpostman.com/apps

If the issue persists in the native apps, then feel free to reopen it.
