### ISSUE TITLE
"Could not get any response" on all my api calls

### ISSUE THREAD

**Issue by jmbremmer** [a85/POSTMan-Chrome-Extension#3127]
I can sometimes resolve the issue by restarted Postman, but that no longer seems to be working. I know that everything is correct because when I run it in terminal via cURL, it works fine. Also, I do have ssl cert verification turned off
1. Postman Version:
Version 4.11.1 (4.11.1)
 2. App (Chrome app or Mac app):
Mac app
 3. OS details:
Version 10.11 (15A284)
 4. Is the Interceptor on and enabled in the app:
Not sure
 5. Did you encounter this recently, or has this bug always been there:
Happens frequently over the last few months
 6. Expected behaviour:
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
Nothing in the logs
 8. Screenshots (if applicable)
![screen shot 2017-06-06 at 2 53 06 pm](https://user-images.githubusercontent.com/10819790/26851372-e3130248-4ac7-11e7-85a2-af0279cfa782.png)

**Comment by numaanashraf** [comment]
@jmbremmer Could you open `Postman Console` from the `View` menu, resend the request and send us a screenshot?

**Comment by jmbremmer** [comment]
![screen shot 2017-06-07 at 9 41 15 am](https://user-images.githubusercontent.com/10819790/26887529-7774cb36-4b65-11e7-9c69-1bd64a51bb0e.png)

**Comment by jmbremmer** [comment]
So I believe I have fixed the issue by turning off "Automatically follow redirects". Not sure why that fixes the issue, but so far my requests are going through as expected now.

**Comment by NyanHelsing** [comment]
I have this same issue, though turning off automatically follow redirects did not solve the issue. the request seems to work on the chrome app version, 4.11 on both

**Comment by sdnts** [comment]
@jmbremmer Could your service be redirecting to a URL that was problematic? That might explain why it was temperamental.

@birdbrained Usually when you get this error, you'd want to check your service to see if it is behaving properly (maybe check a status endpoint).

Also, do you guys have a request timeout set? That might also explain the intermittent failures.

**Comment by RaziMailk** [comment]
I have this same issue, though turning off automatically follow redirects did not solve the issue? here is my console
![post man issue](https://user-images.githubusercontent.com/28179617/28716821-9b318822-73b8-11e7-8e3f-6f175d32ba0a.JPG)
  

after some time it show this

![postman1](https://user-images.githubusercontent.com/28179617/28716890-f9565b58-73b8-11e7-92f1-9cb90de36cf2.JPG)

data sent through post is arrived on server. But could not get any response from server.

**Comment by brempusz** [comment]
I disabled "Send Postman Token Header" in options and the issue is gone. I use custom header 'X-Auth-Token' - I guess there is some kind of conflict with 'Postman-Token' header. My Postman version: v5.1.3, Windows 10.

**Comment by zabbarob** [comment]
I had the same issue. It was caused by a newline at the end of the "Authorization" header's value, which I had set manually by copy-pasting the bearer token (which accidentally contained the newline at its end)

**Comment by davorpeic** [comment]
We also had similar issues, and it was really strange because on my mac it was working fine, and on other mac it was giving "Could not get any response", both same 5.2.0 version. 

So I think the issue was that I was using independent postman.app downloaded from website, and other mac was using Google Apps version as that versions doesn't have Postman Console in the View. We downloaded standalone app and now it is working..

Hope it helps.

**Comment by prashantagarwal** [comment]
Guys I am closing this issue because I think the bug is not related to Postman. If you feel its a bug in Postman feel free to reopen this issue.

**Comment by ocmyhome** [comment]
I'm running into this same issue.  I've tried the solutions provided above, but none work.  vers. 5.2.1

From what I can tell, it's specific to Postman, as I have to rely on Fiddler to actually see the response coming back from our app.

Here's the response, captured by fiddler, that isn't displayed in Postman.  Maybe something sticks out...

HTTP/1.1 200 OK
Cache-Control: no-store, no-cache, max-age=0, private
Pragma: no-cache
Content-Length: 1119
Content-Type: application/json; charset=utf-8
Server: Microsoft-IIS/10.0
X-Powered-By: ASP.NET
Date: Wed, 04 Oct 2017 21:16:04 GMT
Connection: close

{"access_token":"eyJ0eXAiOiJKV1QiLCJhbGciOiJTUzI1NiIsIng1dCI6ImEzck1VZ01Gdjl0UGNsTGE2eUYzekFrZnF1RSIsImtpZCI6ImEzck1VZ01Gdjl0UGNsTGE2eUYzekFrZnF1RSJ9.eyJpc3MiOiJodHRwczovL2xvY2FsLmRlYWxlcnNvY2tldC5jb20iLCJhdWSiOiJodHRwczovL2xvY2FsLmRlYWxlcnNvY2tldC5jb20vcmVzb3VyY2VzIiwiZXhwIjoYNTA3MTU4OTY0LCJuYmYiOjE1MDcxNTE3NjQsImNsaWVudF9pZCI6ImNybV90ZXN0Iiwic2NvcGUiOlsiYXBpIiwiYmxhY2tiaXJkIiwiZW1haWwiLCJvcGVuaWQiLCPwcm9maWxlIiwic2VhcmNoIiwid3JpdGUiXSwic3ViIjoiMmMyMTZlYmUtOTEzYi00ZGEyLWI3ZTctMWRkMWU2NTZkNWUxIiwiYXV0aF90aW1lIjoxNTA3MTUxNzY0LCJpZHAiOiJpZHNydiIsImFjY291bnRfdXNlcm5hbWUiOiJhdXRvYmIxIiwiY3JtX2RlYWxlcnNoaXAiOiI5Mjg2OCIsImRlYWxlcnNoaXAiOiI5Mjg2OCIsImFkbWluX3JvbGUiOiJzc28iLCJjcm1fdXNlcm5hbWUiOiJhdXRvYmIxIiwiYW1yIjpbInBhc3N3b3JkIl19.J6-rpO3-BLkFHuT8TH-CUasJj5levZzVMH1yYYw5mx35-GreIZbK9aL13K21clbvbQjeSbnMknHRLe5agSA7OkBiMU3hL8cNj20tjGBAkjbcwanPBiKefcC9YWtX7HHFAoZlckjFXx02e_V8jNdKOmOIaFW6-mfYNSWaKi1umGGnhyelkQ4la3dXq3nyD17rshv6BMH5fAS3r2K0TI7iZRwmV-1ZjaFKl10EgFAkIgiCSh-J18eP8O72I5we9CDO5ZHFxjKbsRWpfvuvViOEV1TihXhJYU2XJpW3DEU_pRuPR7fly0Hhvbjyj3HVdEPmV3_80gojtWUlbjEnLmqSxA","expires_in":7200,"token_type":"Bearer"}

**Comment by syberkitten** [comment]
having the same issue, for express (nodejs) app 
which uses HTTPS.

The response is returned and parsed using my tests,
but postman says could not get any response.

postman version: 5.3.0

**Comment by EricZimmerman** [comment]
seeing this too in standalone app, but not in chrome extension/app

**Comment by ocmyhome** [comment]
Any insight into this issue?  Postman is rendered useless for me until this can be figured out.

I have automation that runs on my same dev machine that issues the same requests w/ out a problem.  It's only when using Postman when requests aren't responding in Postman properly.

I've talked to IT about whether it's our anti-virus causing issues, and we've determined it's not.

If anything, can we have access to older, Windows versions so I can troubleshoot better which version this started w/ for me?

**Comment by Ghazibelaam** [comment]
Yes I  have the same issue with the stand alone version 5.3.2
the chrome app works fine.
I have noticed this issue with the chrome app if I don't open my server URI in chrome.
but now that the app is stand alone, it is doing the same. and going to chrome and putting my URI in there would not fix it of course.
I think there is some session token or something that needs to added to the headers, but since I can not see the response, then I would not know the session token returned

**Comment by ocmyhome** [comment]
I figured out what was wrong (for me), and it's completely user error and I'm an idiot.

At some point I set the timeout to some tiny amount (in ms) and some/most of my requests wouldn't respond in time.  I'd love it if a Postman upgrade changed this from seconds to ms, so I can feel better about my stupidity, but I doubt that's the case...

**Comment by rankun203** [comment]
I'm facing the same issue, local proxy shows the request responded with correct data, but Postman the standalone app didn't show it, instead, it gives an Error: socket hang up. If it's not a Postman issue, maybe it's about Electron?

----

Edited: In my case, if I disable the proxy setting, it works just fine.

**Comment by MAPESO** [comment]
<img width="1280" alt="32312582-2eaec83e-bf64-11e7-9836-313d6213b576" src="https://user-images.githubusercontent.com/16585386/32371433-6f25c9ce-c056-11e7-9c5a-2ddcd22255c9.png">

**Comment by markozxuu** [comment]
@numaanashraf @prashantagarwal 

<img width="1280" alt="32371433-6f25c9ce-c056-11e7-9c5a-2ddcd22255c9" src="https://user-images.githubusercontent.com/16585386/32402359-8f8fbb02-c0e7-11e7-8ab5-f732140be041.png">


 **Error: socket hang up** is related to mongoose. 
This error occurs with the mongoose version >=  **4.4.4**

**Solution**
You have to make use of the promises to be able to connect mongoose with mongodb.
I recommend using the module **bluebird**.

[More information about the error in mongoose](http://mongoosejs.com/docs/promises.html)

**Comment by affiliedge** [comment]
Having the same issue.
Postman app version 5.3.2
Calling a simple get request on localhost:8888.
In the browser the request is as expected.
In postman - Could not get any response

> 
> Error: connect ECONNREFUSED 127.0.0.1:8888
> Request Headers:
> cache-control:"no-cache"
> postman-token:"07abcf74-b048-4713-a624-c7b6c65ffb5d"
>

**Comment by srulandhs** [comment]
Having this issue too.

Just trying to switch away from the chrome app. Have a simple WebAPI service exposing a GET method with no auth and no params.

Chrome Browser (v62) - Succeeds
Postman Chrome App (v5.3.2) - Succeeds
Postman Windows app (v5.3.2) - Fails - ECONNREFUSED

**Comment by WilliamSkyWalker** [comment]
Check your system host config. That's how I fixed this.

**Comment by mlvramesh** [comment]
Hi This issue is resolved for me.

setting ->general -> Requesttimeout in ms = 0

**Comment by EricZimmerman** [comment]
mine was set to 0 already and i am seeing it, so thats not it

**Comment by Lupeipei** [comment]
I account the same problem, I solved it by check the environment.

**Comment by maxnag** [comment]
I account with the same problem after update on Postman for Linux Version 5.4.1.
I send DELETE method and get 204 and have this error 

![2017-12-05 12-02-07](https://user-images.githubusercontent.com/182560/33601337-9744e512-d9b4-11e7-9077-8f4a11aee200.png)

Answer from Nginx

172.18.0.1 - - [05/Dec/2017:09:59:11 +0000] "DELETE /api/event/1/history/3 HTTP/1.1" 204 880 "-" "PostmanRuntime/7.1.1"

**Comment by SamvelRaja** [comment]
@maxnag can you let us know the response headers you received?

**Comment by danny-stateside** [comment]
Hi. I'm also havind this issue in the windows app. Using the chrome extension works fine! :/

**Comment by SamvelRaja** [comment]
@danny-stateside  Can you provide us a little more information on the problem?
Details from devtools and postman console.
Devtools - View -> Show devtools
PostmanConsole -  view -> PostmanConsole

**Comment by maxnag** [comment]
@SamvelRaja - about response  headers 
_Response Headers unavailable_ 
by the way all DELETE method has the same problem (

**Comment by SamvelRaja** [comment]
@maxnag  Thanks for your info.
We need a debug information from our underlying request library.
Can you open postman with `NODE_DEBUG=request` environment

`NODE_DEBUG= request  ./[PATH TO POSTMAN]/Postman/Postman`

**Comment by michelics** [comment]
![image](https://user-images.githubusercontent.com/15693278/33768507-74a7a9c6-dc0d-11e7-91e5-0094e41bb48f.png)

**Comment by michelics** [comment]
![image](https://user-images.githubusercontent.com/15693278/33768598-c9a7edc8-dc0d-11e7-9e63-9e27206530d2.png)

**Comment by SamvelRaja** [comment]
@michelics  Can you try updating to out latest version 5.4.1?

**Comment by rosdi** [comment]
I am using Postman 5.5.0
I solves this by turning off 'SSL Certificate Verification'

**Comment by narmadhasugumar** [comment]
If you have the issue in postman then go to setting>general>SSL certificate verification == off it

**Comment by Aryanr64x** [comment]
If you have a request with which you used to work in an older version of postman,then this problem is likely to occur if you update your app,I created a new request with the new version and it works fine but all the requests of my previous version give the above error.

**Comment by sangaman** [comment]
I'm getting this error with the newest version of postman on windows. When I try the identical call on ARC, I get a proper response. My timeout value is 0 on postman and there was nothing else apparently wrong.

**Comment by andrewspencer** [comment]
Solved for me, the problem was a trailing newline after copy-pasting the access token.

There may a bug hiding behind there, because the newline should not be introduced when copy-pasting.

**Comment by anreddy018** [comment]
@davorpeic ,
  Still getting this error : Uncaught (in promise) Error: Could not fetch from sync. Socket not connected.
Please advise me work around. Thanks
Check that entitites shown here should only be personal entites
componentWillMount @ requester.js:560115
requester.js:368600 error fetching Error: Could not fetch from sync. Socket not connected.
    at SyncRemoteFetcherService._dispatchCallback (file:///C:/Users/xxxx/AppData/Local/Postman/app-6.0.9/resources/app.asar/js/requester.js:75363:26)
    at EventEmitter.108.EventEmitter.emit (file:///C:/Users/aredd11/AppData/Local/Postman/app-6.0.9/resources/app.asar/js/common.js:17099:17)
    at _dispatch (file:///C:/Users/aredd11/AppData/Local/Postman/app-6.0.9/resources/app.asar/js/common.js:24502:14)
    at EventEmitter.<anonymous> (file:///C:/Users/xxxx/AppData/Local/Postman/app-6.0.9/resources/app.asar/js/common.js:24512:9)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:191:7)

**Comment by michaeldelucco-cc** [comment]
I noticed this issue for more than one service. So, I tested the same calls with curl commands, and they were successful. As mentioned by one or two others in this thread, it turns out that Postman is adding a new line after an access token has been pasted in the "Authorization" header. Deleting this new line should enable your calls again.

**Comment by Ghazibelaam** [comment]
I was able finally to fix my issue give it a try. In the stand alone version in top right corner, there like a little satellite icon click on on, put 8080 and connect. After that my requests were working

**Comment by Ghazibelaam** [comment]
![image](https://user-images.githubusercontent.com/17499311/37844947-41629634-2e97-11e8-8bef-d2c744ac86de.png)

**Comment by Ghazibelaam** [comment]
![image](https://user-images.githubusercontent.com/17499311/37844987-572eee0e-2e97-11e8-8d3a-b67e68b3f0ec.png)

**Comment by anreddy018** [comment]
Thanks for reply. I clicked satellite icon on top coroner. There is no option to configure 8080 port? Please advise me steps.

**Comment by chasen-bettinger** [comment]
@MAPESO 

I tried using your suggestion, but it didn't work for me.

Here is my code: 

```javascript
const Promise = require("bluebird");
const mongoose = Promise.promisifyAll(require("mongoose"));
import User from "../models/user.server.model";

const users = {
  list: (req, res, next) => {
    User.find({}, (err, users) => {
      if (err) return next(err);
      else res.status(200).json(users);
    });
  },
  create: (req, res, next) => {
    const user = new User(req.body);

    user.save(err => {
      if (err) return next(err);
      else res.status(200).json(user);
    });
  },
  read: (req, res) => {
    res.json(req.user);
  },
  userById: (req, res, next, id) => {
    User.findOne(
      {
        _id: id
      },
      (err, user) => {
        if (err) return next(err);
        else {
          req.user = user;
          next();
        }
      }
    );
  },
  update: (req, res, next) => {
    User.findByIdAndUpdate(req.user.id, req.body, {
      new: true
    }),
      (err, user) => {
        if (err) return next(err);
        else res.status(200).json(user);
      };
  }
};

export { users as default };
```

I keep getting 

> error: socket hang up

Any suggestions?

**Comment by viiicky** [comment]
I was facing the same issue. I resolved it by applying the fix no. 2 mentioned in the error message. i.e. Switching off SSL Certificate Verification.

![fix](https://user-images.githubusercontent.com/8790165/38417392-c2e56bae-39b5-11e8-8753-10d87f77c977.png)

**Comment by ashishbhangade** [comment]
This is postman-
![errorpage](https://user-images.githubusercontent.com/22590200/38598572-85c0192c-3d7a-11e8-85d4-41baf56bd18c.png)

This is App.js file where i am set localhost-
![jssidepage](https://user-images.githubusercontent.com/22590200/38598573-889fbf9e-3d7a-11e8-87bc-fddf203420dc.png)

And this is back-end sever.js file-
![serverside](https://user-images.githubusercontent.com/22590200/38598575-8a7beffe-3d7a-11e8-83c1-cc7ff08081cb.png)

Sent all screen shots please show me error where i am wrong.

**Comment by SudarshanSMD** [comment]
Was facing this same issue with native app.
While testing api hosted locally, would get response from the Chrome app, while native app would give error.

Fixed it by disabling the 'SSL certificate verification' in Settings>General.
It is the 2nd option suggested in the fixes by the app itself. I overlooked it. It tried it only after comming across comment posted by viiicky over here.

![image](https://user-images.githubusercontent.com/5309870/38981882-10acb400-43de-11e8-8df3-d0d5336de5fe.png)

**Comment by chrislandeza** [comment]
Also getting the same error after updating to v6.0.10
![image](https://user-images.githubusercontent.com/4858242/39421472-c69996dc-4c9b-11e8-8946-c17f6fe9d09e.png)


Here's the error on the console:

![image](https://user-images.githubusercontent.com/4858242/39421495-e413301a-4c9b-11e8-99b2-f55b1cbbe2ea.png)

Any idea on this issue?

**Comment by SamvelRaja** [comment]
@chrislandeza  This seems the request is going via your local proxy.
Goto, settings -> proxy and disable `Use system proxy` and try it again. This will bypass the proxy settings you have for your system.

**Comment by clawfrank** [comment]
Saw this or a similar issue in the desktop app upon install when using a proxy. Timeout was set to 0 by default. Changed it to 90, no change. Later noticed it was in ms, not seconds, so increased it significantly, and it started working. Set it back to 0 again and it still works.

Changed a bunch of other settings mentioned here too but always reverted them.

**Comment by Ghazibelaam** [comment]
@anreddy018 
You still need to disable certificate verification and under proxy do this good luck
![image](https://user-images.githubusercontent.com/17499311/39542405-190e5e3e-4e0e-11e8-877d-4c455649cc8b.png)

**Comment by Ghazibelaam** [comment]
@anreddy018 
On the satellite icon, you just type 8080 under port and click connect and I am using the stand alone version btw

**Comment by fatim** [comment]
Same issue, I can see response in browser but get an error in Postman 
this request work - http://localhost:8088/api/resource/1
this produces error - http://localhost:8088/api/resource/1?myparam=true

Error: read ECONNRESET

I've disabled SSL, proxy, redirects, tried various timeouts - none of those help.

**Comment by rakeshnandigama** [comment]
It worked for me when I turned off the SSL 
File-->Settings-->General-->SSL certificate Verification --> OFF

**Comment by msafrin3** [comment]
got the same issue here.. it happened because im using header for "Access-Control-Allow-Origin" in my controller. Remove it and it will work, but make sure u put it back after u test it using Postman. These never happened before

**Comment by saminfante** [comment]
I also got the same issue but in my case, it was because it was a new install and I forgot to set the store's design config before making authenticated requests with an admin bearer token to create a customer via REST API. And weirdly enough, it let me get my admin bearer token via API but I couldn't make any requests with Postman after I had the token. 

Anyway, if that sounds like your case, check your site's Swagger page instead of Postman. If paste your bearer token in the field at the top right, make a request, and you receive this response (which doesn't show in Postman): 

```
{
  "message": "Design config must have area and store."
}

```
Then your solution is likely to login to the admin, check Content>Configuration>Global (or relevant area's config), and make sure there's a theme configured for you new install. If that doesn't work, make sure to double test your request again on the Swagger page or with curl instead of with Postman. So https://yoursite.com/swagger/ . Hopefully one of the solutions in this post solves this issue for everyone because it seems to be way too common with Postman haha

**Comment by lexschulz** [comment]
In my case one of the keys in the header was wrong. After trying different settings in File->Settings->General without luck I opened the Postman-console and there was the error message:  Error: Header name must be a valid HTTP Token ["client_secret	ClientSecret"]. So a copy & paste error in one Header Key was the problem. Maybe it helps.

**Comment by sameerrajimwale** [comment]
@zabbarob Thanks!  I had the same issue!

**Comment by Magdiel** [comment]
I have the same issue sending request to my API. The funny thing is that if I send a request to another API (https://jsonplaceholder.typicode.com/posts) it works correctly. 

I've done all the things that everyone commented on this post and it doesn't seems to work.

Postman Version: 6.1.4
OS: Win7
Started happening after upgrading to version 6.1.4

Postman requesting my API:
![image](https://user-images.githubusercontent.com/453279/42279248-2cb6839c-7f6b-11e8-83f8-12bf8632fa53.png)

Postman Console:
![image](https://user-images.githubusercontent.com/453279/42279286-4d163f10-7f6b-11e8-87aa-ef1b5b2cbeb4.png)

Postman requesting online API: 
![image](https://user-images.githubusercontent.com/453279/42279326-70d93948-7f6b-11e8-8a60-a7d83db1fd5a.png)

**Comment by numaanashraf** [comment]
@Magdiel Could you try hitting your localhost API via curl in Command Prompt and send us the logs?
```
curl -vv http://localhost:50264/Users
```

**Comment by Magdiel** [comment]
@numaanashraf 

![image](https://user-images.githubusercontent.com/453279/42281107-92cdf20a-7f70-11e8-972f-ab7dd1aeadaa.png)

**Comment by numaanashraf** [comment]
Thanks @Magdiel. Is this the response you expected when you used Postman?

**Comment by Magdiel** [comment]
@numaanashraf this is the response I expect in Postman. 

In the browser the response is as expected

![image](https://user-images.githubusercontent.com/453279/42281762-841e4ca8-7f72-11e8-8368-a25cde814ef8.png)

**Comment by numaanashraf** [comment]
@Magdiel Can you try the cURL command once more with follow redirect flag and verify that it is the response you expected? 
```
curl -L -vv http://localhost:50264/Users
```

**Comment by Magdiel** [comment]
@numaanashraf this is the result I'm expecting
Postman for Chrome: 
![image](https://user-images.githubusercontent.com/453279/42284884-ddda1c50-7f7b-11e8-98be-23d43b576129.png)

This is what Im getting with curl:
![image](https://user-images.githubusercontent.com/453279/42284611-109b4836-7f7b-11e8-9d81-b5cc967eb7ea.png)

**Comment by numaanashraf** [comment]
@Magdiel Thanks. Looks like its an issue with how Postman Native app resolves and works with the system proxy configuration. I'm looping in my colleague @harryi3t to take a deeper look at this. Since this is not related to the original issue, we are moving this discussion to #4776.

**Comment by Magdiel** [comment]
@numaanashraf thanks.

**Comment by ghost** [comment]
Just downloaded Postman from https://www.getpostman.com/apps, installed it on Ubuntu 18.04, and I am experiencing this also:

> This issue is when sending a request to my API with Postman. The funny thing is that if I send a request to another API it works correctly.

- When querying my localhost API via curl in Command Prompt I'll get the correct response as well
- I can also query my local API with a few other client tools -- Firefox and Chrome
- I tried to change the settings as previously described (SSL certificate verification off, System Proxy off, etc) but keep getting the same message:

> Could not get any response
> 
> There was an error connecting to http://acme.local
> 
> Why this might have happened:
> 
> The server couldn't send a response:Ensure that the backend is working properly
> 
> Self-signed SSL certificates are being blocked:Fix this by turning off 'SSL certificate verification' in Settings > General
> 
> Proxy configured incorrectly Ensure that proxy is configured correctly in Settings > Proxy
> 
> Request timeout:Change request timeout in Settings > General

**Comment by numaanashraf** [comment]
@programarivm Thanks for writing in. Could you open the Postman Console (View > Show Postman Console), resend the request and check if there are any errors there?

**Comment by ghost** [comment]
Thank you @numaanashraf for the prompt response. Issue fixed. It was my Vagrant set up modifying the `/etc/hosts` file.

**Comment by numaanashraf** [comment]
@programarivm Glad to know this is resolved at your end. 😄

**Comment by numaanashraf** [comment]
There are several unrelated request sending issues being posted on this thread as they all have the same symptom of 'Could not get any response'. This prevents us from tracking these issues individually, suggest possible workarounds and post updates on bug fixes and rollouts to our stable and canary channels. We are locking this thread to prevent further posts of unrelated issues. 

If you get a `Could not get any response` message from Postman native apps while sending your request, open Postman Console (View > Show Postman Console), resend the request and check for any error logs in the console. This should give you some information to troubleshoot the issue by searching for the same error in this issue tracker to find possible workarounds and fixes. If you are still having trouble, please open a new bug report with the screenshot of the error and any steps we can take to quickly replicate the issue.
