### ISSUE TITLE
"Overwrite request" confirmation dialog incorrectly displays when saving a request with a new header selected from a preset

### ISSUE THREAD

**Issue by qmcree** [a85/POSTMan-Chrome-Extension#3129]
1. Postman Version: 4.11.1
 2. App (Chrome app or Mac app): Mac app
 3. OS details:  macOS 10.12.3
 4. Is the Interceptor on and enabled in the app: N/A
 5. Did you encounter this recently, or has this bug always been there: Recently
 6. Expected behaviour: Should not ask for confirmation to overwrite the request. 
 7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):  None
 8. Screenshots (if applicable)

1. Open an existing request.
2. Click request's headers tab.
3. Add a new header by choosing from a preset.
4. Save the request. 
5. Notice the incorrectly displayed confirmation dialog saying "This request has been modified in another open tab." and asking to overwrite it.

**Comment by numaanashraf** [comment]
@qmcree Thanks for reporting. We are looking into this.

**Comment by muralidharbg** [comment]
same issue can be seen in version 5.0.0 as well

**Comment by qmcree** [comment]
I haven't experienced this bug in a week or two. I've been able to save requests with a new header selected from a preset without encountering the unexpected overwrite dialog.

**Comment by sdnts** [comment]
@qmcree That's great to hear!
@muralidharbg Does 5.0.2 also show you the same error?

**Comment by muralidharbg** [comment]
@madebysid I'm not experiencing this error in 5.0.2
