### ISSUE TITLE
Linux app freezing periodically!

### ISSUE THREAD

**Issue by dimmg** [a85/POSTMan-Chrome-Extension#3134]
## App Details:
```
Postman for Chrome 
Version 4.11.1
linux / x86-64 (Ubuntu 16.04)
Chrome 59.0.3071.86

Interceptor: off / not installed
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there: this bug always been there 
 2. Expected behaviour: should respond to commands instantly 
 3. Console logs - unavailable as there is no console

Sometimes the app just is freezing completely and it becomes almost totally unresponsive.
Clearing the history, closing all tabs, reinstalling and restarting application do not help.

After some time, the app is working normally and then again starts to lag.

**Comment by numaanashraf** [comment]
@dimmg Thanks for reporting. This is a known issue and we are working on rolling out the fixes soon.

**Comment by numaanashraf** [comment]
@dimmg Are you still facing this issue in the latest version of Postman (v6.1.4)?

**Comment by dimmg** [comment]
Seems like this got fixed, as lately everything has been running smoothly.
I think the ticket can be closed now.

Thanks!

**Comment by numaanashraf** [comment]
@dimmg Glad to know that. Closing this issue.
