### ISSUE TITLE
Importing cURL Command through Raw Text fail to correctly parse HTTP verb

### ISSUE THREAD

**Issue by qkdreyer** [a85/POSTMan-Chrome-Extension#3135]
## App Details:

```
Postman for Mac
Version 4.11.1
OS X 16.4.0 / x64
```

## Issue Report:

 1. Did you encounter this recently, or has this bug always been there:

No idea.

 2. Expected behaviour:

While importing a cURL command through raw text, it should handle a -X argument without space, as cURL does.

 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):

None.

 4. Screenshots (if applicable)

![image](https://user-images.githubusercontent.com/717869/26881728-943d15f6-4b98-11e7-8216-196948537740.png)

Try to import a cURL raw text command with -X argument not spaced to an HTTP Verb
It doesn't correctly parse the HTTP Verb.

**Comment by numaanashraf** [comment]
@qkdreyer Thanks for reporting. We'll look into this.

**Comment by dsatgithub55** [comment]
Any update on this issue please ?? @numaanashraf

**Comment by abhijitkane** [comment]
@dsatgithub55 @qkdreyer This should be fixed in Postman 7.2.2. Feel free to add a comment if you see any other issues around this.

Closing for now.
