### ISSUE TITLE
upload file in collection runner

### ISSUE THREAD

**Issue by zhangmoon** [a85/POSTMan-Chrome-Extension#3137]
hi, does postman support upload file in collection runner.
I run upload file in collection runner, the file does not upload.

**Comment by kamalaknn** [comment]
Hi @zhangmoon 

At the moment Collection Runner does not support uploading files. That is because saved requests can be shared with others in the team, or be synced to an app on a different machine, and the file path would be invalid for then. 

Could you explain your use case so we see if there are any other ways to achieve this?

**Comment by bigbigmike** [comment]
I also had this dilemma and ended up installing Newman to run my collection with a file upload and I was successful.  It would be a good feature to be able to provide a way to do this in collection runner.

**Comment by nagabhiru** [comment]
Our web application requires us to upload a zip file and then run a job through REST APIs.
I have created a collection that does this but I can run it only through Newman.
I understand that collections can be shared and the file path would be different across machines.
Currently Collection Runner has option to select data file (json/text/csv) 
If you can enable option to manually select any file to be uploaded in the Collection Runner that would be great.
Teams will then select the appropriate file from their machines in the Collection Runner GUI before running.

One workaround is that currently Postman searches for the file to be uploaded in:
"C\Users\'username'\appdata\Local\Postman\app-x.x.x\"
If you copy the file to that location you can successfully upload it from Collection Runner

**Comment by kamalaknn** [comment]
@shamasis @numaanashraf what are your thoughts on this?

**Comment by amerryma** [comment]
Yes I would like to see if we could do this as well. Assuming each team member has the file in the same spot it should work.

**Comment by dipakbachhav** [comment]
I am using postman collection runner to upload images. I have already created environment and able to use collection runner for other api but while uploading image I am failed. Is postman collection runner supports image upload operation and can i run multiple iteration for image upload?Can you please help me?

**Comment by abhijitkane** [comment]
To send files with requests while running a collection, you'll need to use Newman - http://blog.getpostman.com/2014/11/15/using-newman-to-run-collections-with-file-post-requests/. Supporting file uploads through Postman's runner isn't on our immediate roadmap.

**Comment by tazmaniax** [comment]
+1 to add support for uploading files specified as file paths in the runner data

**Comment by santakd** [comment]
+1 to add support for uploading files specified as file paths in the runner data. This will really help.

**Comment by AlbertORoura** [comment]
+1 same here! That will awesome :)

**Comment by funkydunc** [comment]
+1 same here.

I would like to be able to store a different relative file path per request:

I'm using Postman / Newman to test a CSV Import API. Each tests uses a different file which tests a different error case.
- e.g. Request 1 uploads: 'data/0_all_fields_good.csv'
- Request 2 uploads: 'data/1_col_1_empty.csv', and so on for many test cases

I can export the collection to json, and add the 'src' attribute in a test editor and this works in Newman as documented here:

http://blog.getpostman.com/2017/09/21/run-collections-with-file-uploads-using-newman/

But, if I reopen the collection in postman to write more tests, it removes the 'src' attributes.

It would be great to have this fixed. Thanks!

**Comment by sebcaps** [comment]
In addition this workaround can hardly be set up in a continuous integration environment...
It would be a great thing to handle this. 
My 2 cent's : 
- add an option to newman (postman ?) to configure a folder path where ressource are stored
- in  test script just use filename
- during execution add path variable to filename.

**Comment by grafikri** [comment]
+1

**Comment by bizzard4** [comment]
+1

**Comment by mlb5000** [comment]
This is a real hinderance during development of test collections. Even if you populate the `src` portion of a File field in a multipart request directly in the `postman_collection.json`, if you then import it into the Postman application, make changes to **other** requests/add new ones, and then export the collection to a file again (i.e. to save it before sending it up to CI to be executed, or to run newman locally), the `src` value is lost and set to `null`.

The main client should at least retain the modified file src value, and only overwrite it when/if that actual request is modified (if then). I get not being able to refer to a specific file in the Postman collection runner since it's literally an embedded Chrome browser and browsers (rightly) don't let you do that sort of thing, but the workflow between building in Postman and running in newman is completely disrupted by losing file src paths during the import/export process.

And I'm definitely not about to develop my test collections directly in JSON...

**Comment by JordanStopford** [comment]
As above - this is making it a pain to write tests as we are having to put the "src" fields back in manually every time after a fresh export.

i.e. +1

**Comment by xargsyan** [comment]
+1 to implement it.
This is confusing, since tests ("Run Collection") fail on file uploads.
And is really important bug, since it makes the whole "Collection Runner" feature unusable if there is a file upload.

@abhijitkane, @madebysid  the issue is "closed" yet has the "feature" tag.
Does it mean that the issue is "closed" and won't be done? or will be done in the next versions?

We are (all) looking forward for your (positive) response. Thanks.

**Comment by jscul** [comment]
I don't often comment on threads like this but this feature is a must have for API testing... if every time we download Postman and sync our data we have to re-upload all of our images collaboration becomes a nightmare and makes Postman unusable for multipart/form testing.

**Comment by danabeled** [comment]
This is my first comment on github ever, this feature is a no-brainer add in my opinion. It's the single thing making my team doubt if it's viable for our CI test process.

**Comment by sahanakrishnaiyer** [comment]
+1 to have this feature implemented

**Comment by andreacab** [comment]
+1 here too, we would like to use postman as our api testing tool, but this is currently stopping us.

**Comment by irshu355** [comment]
+1

**Comment by DeadcatDev** [comment]
+1 again... really, i need this badly :D

**Comment by lhu-smartling** [comment]
+1 Would be really helpful

**Comment by nirradi** [comment]
+1 First time user of postman collection runner, first thing I tried and it doesn't work :(

**Comment by saswatds** [comment]
Hi everyone postman does support file in collection runner from app version 7.1.0
More on how it works has been described in the comments
https://github.com/postmanlabs/postman-app-support/issues/4320#issuecomment-490749103

In case of a situation where file-reference were not selected on the system you are running the collection,  you can check your postman console and find PPERM error in which case you will need to allow insecure file read from your settings. 
If you still find that file uploads are not working feel free to create a new issue

**Comment by jscul** [comment]
@saswatds _"If you want to access the file in some other computer, simply keep another copy of the file with the same name in the same directory path in the other computer, preferably in the working directory."_ This still seems like a headache... what's being asked for in this thread (IMO) is the ability to have files be stored by Postman (on a server) so when I update a request with a new image other people can simply sync and the image is automatically downloaded for them to use. I get that this creates some overhead on your part but it's pretty annoying constantly having to sync up 2 different things: the Postman application and the image directory. It'd be nice if we could just sync the application.

**Comment by saswatds** [comment]
Hi @jscul, we hear you. 
The working-directory abstraction built inside that app was one of the first steps towards providing such a service. 
We are actively looking at this and I am sure we will have something to share soon. I can't guarantee an ETA but rest assure that it's on our radar.

**Comment by Ranchman42** [comment]
Please add this +1!!!

**Comment by harshitgupta** [comment]
It's 2020. come on guys!!!

**Comment by ashokpant** [comment]
Guys, everybody around the globe needs this. Even I got a call from Mars! 
Please add this feature :)

**Comment by chill-cod3r** [comment]
+1 to needing it. Seems like the filepath could be set by an environment variable and call it a day.

**Comment by benydc** [comment]
+1 needing this!

**Comment by arlemi** [comment]
That issue is closed, please refer to[ that feature request (#5147)](https://github.com/postmanlabs/postman-app-support/issues/5147) and add a 👍 on the first message if this is something you'd like to see!
