### ISSUE TITLE
Json schema validation issue - "Required" keyword does not seem to work

### ISSUE THREAD

**Issue by API-Guru** [a85/POSTMan-Chrome-Extension#3138]
## App Details:
Postman for Windows
Version 4.10.7
win32 6.1.7601 / x64

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there: Recently noticed
 2. Expected behaviour: There should be strict schema validation 

1. Store schema in schema variable
```
'{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "definitions": {},
    "id": "http://example.com/example.json",
    "properties": {
        "ApiVersion": {
            "type": "string"
        },
        "CorrelationId": {
            "type": "string"
        },
        "InternalVersion": {
            "type": "string"
        },
        "Result": {
            "properties": {
                "$type": {
                    "type": "string"
                },
                "Chains": {
                    "items": {
                        "properties": {
                            "Code": {
                                "type": "string"
                            },
                            "ID": {
                                "type": "integer"
                            },
                            "Name": {
                                "type": "string"
                            }
                        },
                        "type": "object"
                    },
                    "type": "array",
                    "required": ["Code","ID","Name"]
                    
                }
            },
            "type": "object",
            "required": ["$type","Chains"]
        }
    },
    "type": "object"
};'
```
2. Create a variable to store the response body
Sample reponse body 
```
`{
  "ApiVersion": "1.0",
  "InternalVersion": "1.0.0.0",
  "CorrelationId": "ffffff",
  "Messages": [
    {
      "Code": "2031",
      "MessageText": "No Record found"
    }
  ]
}`
```

3. Use tiny validator for schema validation 
4. The above validations results Pass. However if you notice in Data, there is a mandatory array "Chains" which must be returned to pass the schema, but even when the response contains no such array, the test result is Pass.

The schema is generated using website - https://www.jsonschema.net/#/editor

**Comment by kamalaknn** [comment]
Hi @API-Guru 

This does not appear to be a bug with the Postman itself, but a difference in behaviour with tiny validator. 

Could you open an issue on their [issue tracker](https://github.com/geraintluff/tv4) ?

I am closing this issue here. Feel free to reopen if you find this to be an issue particular to Postman.
