### ISSUE TITLE
"Preview" content persists when subsequent requests returns empty body responses.

### ISSUE THREAD

**Issue by davidmpeace** [a85/POSTMan-Chrome-Extension#3140]
## App Details:

```
Postman for Mac
Version 4.10.7
macOS Sierra 10.12.3 / x64
```

## Issue Report:
1. This issue is present on the "Preview" tab, of the response Body section. 
2. When a web request returns no (empty) response, the previous request data is still visible until you click "Pretty" or "Raw".

## Steps to reproduce
 1. Submit any web request that returns data.
 2. Click on the "Preview" tab
 3. Submit the same web request, but ensure the request returns no data this time (empty).
 4. The "Preview" tab retains it's previous content.  You can click on "Pretty" or "Raw" to reset this.
 5. Expected behavior: "Preview" tab should be empty, since the response was empty.

**Comment by numaanashraf** [comment]
@davidmpeace This was a known issue and we have addressed this in `v4.11.0`. Could you update to the latest version `4.11.1` and verify?

**Comment by davidmpeace** [comment]
Thank you @numaanashraf - all is good.  Sorry for the dup.
