### ISSUE TITLE
Publish Docs behind a Password

### ISSUE THREAD

**Issue by nalum** [a85/POSTMan-Chrome-Extension#3142]
I'd like to request the ability to publish documentation behind a password.

I have requirements for documentation that is not public and would like to use the postman service but currently cannot.

**Comment by kamalaknn** [comment]
Hi @Nalum 

Thank you for your feedback. This is something we do not support yet. 

I am tagging this as a feature request. @a85 can clarify on the roadmap.

**Comment by a85** [comment]
Sorry but this is not on our roadmap. For shared documentation, you can invite documentation users to your time.

**Comment by nalum** [comment]
Is there a user type that is limited to viewing the documentation?

I think either or all of these options would be good to have as a feature of postman:

* Permissions that allow a user to only view documentation
* Permissions that allow a user to only view a subset of documentation
* Documentation that is password protected

The permissions might be the better option over the password protection.

**Comment by krismeister** [comment]
@a85 I'm not certain its fair to close both this and #3188 without providing another venue for customer feedback.

There is a difference in our organization between api consumers and api developers. Our developers do need to work closely within the postman tools, consumers only need access to the docs. Literally they won't benefit from the other postman suite except the documentation.

As this is not a planned feature, we'll need to export the api definitions and use another tool to 
generate the docs to host behind a protected space.

**Comment by musamamasood** [comment]
@krismeister I am facing similar issue, please share other tool to generate docs.

**Comment by krismeister** [comment]
@musamamasood We've not solved this. One we're considering is [slate](https://github.com/lord/slate) which looks pretty easy to impliment.

You pretty much make [markdown documents of the api](https://github.com/lord/slate/blob/master/source/index.html.md) and it outputs this: https://lord.github.io/slate/#introduction

I'd really like a 100% postman solution however, but we need the password protection.

**Comment by musamamasood** [comment]
Thanks, It required much effort but quite an impressive tool as well.

**Comment by piersmacdonald** [comment]
We need this feature as well before we fully migrate away from readme.io

**Comment by mountainhound** [comment]
We also need this feature. We heavily use Postman and having it for docs would be amazing because it would save us a lot of time. But without some sort of security on the documentation only we cannot use the feature.  A public link is not suitable to my company needs, if we could have a password or just allow certain users to view documentation only that would suffice.

**Comment by tonestrike** [comment]
Us too!

**Comment by irmingard** [comment]
Is it on your road map now? Without this feature, we will be migrating to a Postman alternative within the next year.

**Comment by cmarfil** [comment]
Same here, we need to protect the documentation, in many cases as an explicit requirement of the client.

**Comment by mehdichati** [comment]
+1 for me too

**Comment by jkewley** [comment]
Consider that some of your customers are consultants who develop APIs and integrations based on APIs for clients and who would like to provide a well documented, usable Postman collection as a deliverable. Being able to secure access to published docs would be a huge win for those consultants, and could easily provide justification for PM Pro and Enterprise investments.

**Comment by acornforth** [comment]
My concern with postman automatically publishing docs to a 'Private' area is that it's not really private...

It might be obscured pretty well with long UUID-like hex string in the uri, but anyone with that link can see the documentation, and though the risk is small, they could conceivably be stumbled upon by a malicious bot or scraper....

i give my +1 not just to a password protection option for this, but also to some of the other suggestions here for a more fine-grained permissions system.

As I have been merrily developing away with postman, i did not realise for a long time that my client_id client_secret, username and password, were all being displayed in plain-text on a publicly accessible link!

Yes, I know it's better to use variables for that, but typically i don't bother setting up an environment until a bit later on in the process, it's not usually the first thing i will do if i just want to check a couple of endpoints.

The worst thing about this is i did not even know it was happening, silently in the background everytime i press save.... I think there should be some much more obvious warnings about the risks here..

for now i cannot recommend the use of Postman without a long list of caveats and qualifiers....

**Comment by gpredl** [comment]
nothing new until now?

**Comment by shelbaz** [comment]
Any updates? We have a need for it

**Comment by arlemi** [comment]
We have a new feature request around this here: #6681.

In the meantime another option is to export your documentation using a third-party tool like [Postmanerator ](https://github.com/aubm/postmanerator) and host it on your own password-protected website.
