### ISSUE TITLE
request.data returning as [object Object]

### ISSUE THREAD

**Issue by jlewis-13** [a85/POSTMan-Chrome-Extension#3143]
## App Details:
```
Postman for Mac
Version 4.11.0
OS X 16.4.0 / x64
```

## Issue Report:
this issue started recently.  the scripts used to work.  

Expected behaviour:
this script should return as null. 
postman.setEnvironmentVariable("body", request.data);

Screenshots (if applicable)
request.data returning as [object Object]
![image](https://user-images.githubusercontent.com/22100584/26980847-58d6acc4-4d01-11e7-85cb-82acc23aa66d.png)

pre request script uses request.data to capture the body of the request.  
this script used to return as NULL for all GET api calls. 
postman.setEnvironmentVariable("body", request.data);

Steps to reproduce the problem

Run get api with environment variable of 'body' and look at captured value. 
postman.setEnvironmentVariable("body", request.data);

**Comment by codetotest** [comment]
@jlewis-13 try ---  postman.setEnvironmentVariable("body", JSON.stringify(request.data));

**Comment by sdnts** [comment]
@jlewis-13 Objects, when stringified (to display in the environment preview list), show up as `[object Object]`. As @codetotest suggested, doing a JSON.stringify before setting the variable and a JSON.parse before usage should solve your issue.
I'm closing this, please feel free to reopen if this is still a problem for you

**Comment by jlewis-13** [comment]
Hi - this is not returning as empty.  It comes back as {}.  Any other ideas?

postman.setEnvironmentVariable("body", JSON.stringify(request.data));
![image](https://user-images.githubusercontent.com/22100584/27035298-cc7e1852-4f4e-11e7-995f-bbab8dc53cdb.png)

**Comment by codetotest** [comment]
hey @jlewis-13 , looks like body is empty.

Tips for debug:
If you using native app - Open Postman console and fireup request.
you can see the request data both header and body.   Hope this is helpful!

Cheers!

**Comment by jlewis-13** [comment]
@codetotest the console shows the request body of the GET request is null.  Postman still shows either [object Object] or {} as the environment variable value.

**Comment by tsokac2** [comment]
Here is my example and it works:

const response = pm.response.json();
const IBAN = response.accounts[0].identification.iban;
pm.collectionVariables.set("IBAN", JSON.stringify(IBAN));
console.log(IBAN);


// Variables: IBAN "SK4075000000007777777777"

Response Source:

{
    "creationDateTime": "2019-03-11T10:30:44+01:00",
    "accounts": [
        {
            "identification": {
                "iban": "SK4075000000007777777777"
            },
            "name": "TPP COMPANY 2 S.R.O.",
            "productName": "ČSOB Podnikateľské konto",
            "type": "CACC",
            "baseCurrency": "EUR",
            "servicer": {
                "financialInstitutionIdentification": "CEKOSKBX"
            },
            "consent": [
                "AISP",
                "PISP",
                "PIISP"
            ]
        },
        {
            "identification": {
                "iban": "SK8175000000002222222222"
            },
            "name": "TPP COMPANY 2 S.R.O.",
            "productName": "ČSOB Podnikateľské konto",
            "type": "CACC",
            "baseCurrency": "EUR",
            "servicer": {
                "financialInstitutionIdentification": "CEKOSKBX"
            },
            "consent": [
                "AISP",
                "PISP",
                "PIISP"
            ]
        }
    ]
}
