### ISSUE TITLE
Examples are shared between original and saved as request

### ISSUE THREAD

**Issue by MiguelTVMS** [a85/POSTMan-Chrome-Extension#3145]
## App Details:
```
Postman for Windows
Version 5.0.0
win32 10.0.15063 / x64
```

## Issue Report:
When a delete the examples from a request a just created from other request using 'save as' the examples from the original request are deleted either.

Steps:
1. Create a request.
2. Add some examples.
3. Go to save as option on the save button of the request.
4. Delete the examples from the new request.
5. Save the request.
6. All the examples on both requests are gone.

**Comment by prashantagarwal** [comment]
@jmtvms Thanks for reporting this issue. We will look into this and keep you updated on this thread.

**Comment by kamalaknn** [comment]
@MiguelTVMS This should be fixed in the latest release of Postman(6.0.10 at the time of writing). Could you update your app to the latest version and verify this?
