### ISSUE TITLE
Feature request: edit environment templates

### ISSUE THREAD

**Issue by Eli-Goldberg** [a85/POSTMan-Chrome-Extension#3147]
## App Details:
```
Postman for Linux
Version 5.0.0
linux 4.8.0-54-generic / x64
```
Hi, my entire team asks for this:

Please add the ability to edit Environment templates directly,
instead of deleting them, cleaning up the existing environment (hiding vars..), creating a new template with the same name, etc..

**Comment by numaanashraf** [comment]
@Eli-Goldberg Thanks for the suggestion. We'll update here when this lands on our roadmap. You can find the current roadmap at https://trello.com/b/4N7PnHAz/postman-roadmap-for-developers.

**Comment by a85** [comment]
Environment templates are now transitioned off to environments through our new feature called Workspaces. More info here: https://www.getpostman.com/docs/postman/workspaces/intro_to_workspaces
