### ISSUE TITLE
Postman collection runner does not run collection to its end when newman does

### ISSUE THREAD

**Issue by krogold** [a85/POSTMan-Chrome-Extension#3149]
## App Details:
Postman for Windows
Version 5.0.0
win32 10.0.14393 / x64

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:
I'm a newcomer, I've never seen this before
 2. Expected behaviour:
I expected the same number of tests to be run with postman and newman
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
no log available (no running error)
 4. Screenshots (if applicable)
irrelevant

Hello, 
I'm currently developing a test collection that I want to run with newman.
When my collection is ready, I run it with Postman runner. I have 55 requests, and the result is 99 passed and 5 failed (these failures are known and under control)

When I run it with newman, I end up with:
55 requests, with 1 failed 
55 test scripts, with 2 failed
141 assertions, with 13 failed

Failures are of no concern so far, what is annoying is that Postman does not run all the tests and stops before the end as newman runs the entire collection.
Moreover, I couldn't find how to export Postman results in something else than JSON (no option at export)

Is there a particular limitation with Postman ? it seems to me that it can handle much more test cases

Alexandre

**Comment by numaanashraf** [comment]
@krogold Thanks for writing in. Postman doesn't have any limitations that might cause this. Would it be to possible to share a sample collection we can use to replicate?

**Comment by krogold** [comment]
Hello, thank you for your quick response,

I can't join a zip containing my collection, Something went wrong (?) is there another way to send you the sample ?

By the way I noticed Something, the Postman run stopped on a particular failure (return 415 - unknown), in a test that is still not mature, could it be the reason ?
Is it possible to skip some tests when launching a collection (without removing them from the collection) when we know that they will fail (when they are not mature or if the tested API is still under development) ?

thank you


Alexandre

**Comment by krogold** [comment]
Actually I tried to run my collection folder by folder, the error really happens on the step I described before. The particular case is that it is a POST request that fails. Most of the requests I use are PUT and GET.
A previous POST request succeeded though ...

**Comment by numaanashraf** [comment]
@krogold So the runner stops when it hits a POST request that returns 415? You could mail us the collection file to help@getpostman.com and cite this GitHub issue number on the subject. Also, could you open the Postman Console (View menu > Show Postman Console), rerun this folder, and send us a screenshot of this request's log?

**Comment by krogold** [comment]
I did run with console and I have additional information (though I counldn't read it in the console from the developer Tools ?):
Domovea set child group relationship: JSONError: Unexpected token '<' at 1:1 <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/ ^
Usually, this kind of message prevents from executing the test case.

It seems to be a server issue, here is the HTML body returned from the request:
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <title>Http Error</title>
        <link rel="stylesheet" type="text/css" href="/system/http/default.css" />
    </head>
    <body>
        <div id="banner">
		415
		
            <p>Unsupported Media Type</p>
        </div>
        <div id="adv">
            <span>Generated by</span>
            <a href='http://www.prosyst.com'>ProSyst HTTP Server</a>
        </div>
    </body>
</html>

besides I send the collection and environment by mail, as well as the screenshot.

Thank you very much for your help

Alexandre

**Comment by sdnts** [comment]
Hi @krogold Are you doing a `JSON.parse` in the test script of this response? I'm guessing yes, since the error suggests that.
I suspect this is why it is failing (since JSON.parse fails to parse the HTML response body, and throws an error). The reason it works in Newman is probably because of some config difference between the two. (I say this since the underlying request running code in the native app and Newman is the same).
Is your environment being correctly updated in the app? I don't think this has anything to do with the 415 response code, just the HTML response body. 

Can you check your collection to see what might be causing the 415 response?

**Comment by krogold** [comment]
Yes, I actually do and I realize that I already encountered this error: when I set a request body 'raw' and I don't modify the format (Text by default) it provokes this kind of errors. This was the case here.
If I modify the format to JSON, the error provoked is just linked to my request and is no longer blocking. The runner can play the collection to its end.

Many thanks for your help.

Alexandre

**Comment by sdnts** [comment]
@krogold Awesome, that's great to hear!

**Comment by sinahosseini76** [comment]
hi
