### ISSUE TITLE
[Feature Request] - Give the user the ability to open/not open SENT requests in a new tab 

### ISSUE THREAD

**Issue by Faz540** [a85/POSTMan-Chrome-Extension#3150]
Windows App
Windows 10 64 Bit

I've noticed since v5.0.0 that all sent requests now open in a new tab, this allows the user to view their response from previous requests.

There's currently a setting called "Always open requests in new tab" and if this is true - This creates a new tab for every request that's OPENED in Postman.

Ideally, I'd like a similar setting which creates a new tab for every request that is SENT in Postman.

This will leave Postman with lots of open/unused tabs.

**Comment by numaanashraf** [comment]
@Faz540 Thanks for the suggestion. We'll look into this.

**Comment by Faz540** [comment]
Another UX suggestion would be similar to how Sublime Text handles opening files.

Single click opens the file in the same tab, replacing the current tab (assuming no changes have been made to the tab the user was working on)

Double click always opens the file in a new tab.

I think adopting that approach would be more efficient than the suggestion I previously mentioned.
Thanks :)

**Comment by a85** [comment]
We are pausing more changes in the tab system for now. We have seen the current system be flexible enough. We'll continue looking at changes and re-open this issue if needed. Thanks for submitting @Faz540
