### ISSUE TITLE
[Bug] - Since Update 4.11.0 tests fail in the Runner when compared to Postman (see example)

### ISSUE THREAD

**Issue by Faz540** [a85/POSTMan-Chrome-Extension#3153]
**Windows App
Windows 10 64 Bit**

In Postman, I'm saving a boolean as an environment variable (postman saves this a string)
In the next endpoint my test contains the following line of code

```
var response = JSON.parse(responseBody);    
if(environment.isRestricted == "false") {
        tests["Is Restricted = FALSE"] = response.isRestricted === false;
    } else {
        tests["Is Restricted = TRUE"] = response.isRestricted === true;
    }
```

This works perfectly in Postman, but when running this in the Runner, it fails.
This should definitely pass, as the value returned is always false (boolean)

I was positive I've seen this test working recently so I tried using the previous versions of Postman and found the test works fine in Windows App 4.10.7.
As soon as you update to 4.11.0, this will fail in the runner.

**Version 4.10.7:**
![image](https://user-images.githubusercontent.com/9334128/27039785-ea2e9b82-4f86-11e7-91e0-8936334ebac5.png)

**Version 5.0.0:**
![image](https://user-images.githubusercontent.com/9334128/27039897-46d9e472-4f87-11e7-86ac-d7b8d55c80e7.png)

![image](https://user-images.githubusercontent.com/9334128/27039944-70f54116-4f87-11e7-9b30-611861fe2be2.png)

Feel free to rename this bug title as it's a pretty generic bug title :)

**Comment by numaanashraf** [comment]
@Faz540 Thanks for reporting. We are looking into this.

**Comment by sdnts** [comment]
@Faz540 Are you still seeing this?
Is this related to #3428 by any chance?

**Comment by Faz540** [comment]
@madebysid I'm unable to confirm that as this test collection has now been deleted and the enpoint was re-built since this was reported.

It seems that this is the same issue I reported #3428.
Would it be worth running my scenario against Version 4.10.7? :)

**Comment by sdnts** [comment]
@Faz540 Cool, I'm closing this issue then. There's no need to downgrade to 4.10.7, I'm fairly certain this is the same as #3428

**Comment by Faz540** [comment]
I agree. Thanks
