### ISSUE TITLE
Runner:Get Method doesnt read variables from csv.

### ISSUE THREAD

**Issue by Chandana87** [a85/POSTMan-Chrome-Extension#3155]
Hi,

I am not sure whether this feature was ever there.
Just want to understand if I can pass the params value in csv file instead of URL in GET method.
I am trying but its not reading it.
I have already set the environment and whenever I am passing the params through URL, the GET method
is working absolutely fine. But when I try to run it through Collection Runner it does read the csv datafile what I have added, I am sure as I can see the values in json log but the params are still undefined and not reading those values
**Steps to reproduce**

1. URL containing the parameter in the following format.
https://xyz.com?{{abc}}&{{def}}&{{ghi}}
2. through collections runner the datafile has been uploaded
3.When I click on start test I can see in the log the param id's have not taken values from csv file.

**Comment by numaanashraf** [comment]
Hi @Chandana87, could you share a sample collection and csv? It'll help us replicate and debug this faster.

**Comment by Chandana87** [comment]
Hi @numaanashraf please find attached
[Desktop.zip](https://github.com/postmanlabs/postman-app-support/files/1071957/Desktop.zip)

**Comment by Chandana87** [comment]
Hi @numaanashraf  my apologies, I realized there is some issue with the rest service itself as the similar file worked in another service. Hence I am closing this issue.

Thank You.
