### ISSUE TITLE
Timezone token not replaced in pre-request script

### ISSUE THREAD

**Issue by LucaBlackDragon** [a85/POSTMan-Chrome-Extension#3159]
## App Details:
```
Postman for Windows
Version 5.0.0
win32 10.0.14393 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:
    Just happens recently.
 2. Expected behaviour:
     The {Z} placeholder should be replaced with the timezone (e.g. "+02:00") as per [SugarJs Docs](https://sugarjs.com/dates/#/Formatting) when used in a Pre-request Script, but it is left untouched.
 3. Console logs:
    ```
    POST
    localhost:8080
    09:45:33.195
    Request Headers:
    cache-control:"no-cache"
    Postman-Token:"619e1013-2b1e-4c76-a2c8-3dbd55da1337"
    Content-Type:"application/json"
    User-Agent:"PostmanRuntime/6.1.6"
    Accept:"*/*"
    Host:"localhost:8080"
    cookie:"ASP.NET_SessionId=03actfbqvmfnxf45wvsymulz"
    accept-encoding:"gzip, deflate"
    content-length:37
    Response Headers:
    date:"Wed, 14 Jun 2017 07:45:33 GMT"
    connection:"keep-alive"
    transfer-encoding:"chunked"
    Response Body:
    Request Body:"{ "date": "2017-06-14T09:45:32{Z}" }"
    ```

 4. Steps to reproduce the problem
      - Create a sample JSON POST request
      - Set this Pre-request Script:
        ```js
        postman.setGlobalVariable("SampleDate", new Date().format('{yyyy}-{MM}-{dd}T{HH}:{mm}:{ss}{Z}'));
        // SampleDate should be 2017-06-14T09:45:32+02:00
        ```
      - Set this JSON request body:
        ```json
        { "date": "{{SampleDate}}" }
        ```
      - Send the request and check the Request Body in the Console.
        The {Z} placeholder will not have been replaced (e.g. `2017-06-14T09:45:32{Z}`, see Console log above)

 5. Tips
      - it sort of works by using a smallcaps placeholder (e.g. `{z}` instead of `{Z}`): with that, I get this Request Body: `Request Body:"{ "date": "2017-06-14T09:58:26+2" }"`
	  - it is not a SugarJs related issue. The same code (`new Date().format('{yyyy}-{MM}-{dd}T{HH}:{mm}:{ss}{Z}')`) works as expected outside Postman (e.g. you can try to run it in the dev console on their website).

**Comment by SamvelRaja** [comment]
@LucaBlackDragon  we are looking into this issue, we shall let you know the progress here.

**Comment by kunagpal** [comment]
@LucaBlackDragon It is highly likely that this discrepancy is due to a difference in Sugar.js versions across the documentation for Sugar and within Postman. Additionally, Sugar.js is deprecated and will be replaced by momentjs (https://github.com/moment/moment) soon, so we'd advise against depending on Sugar entirely. Feel free to get back to us if you're facing other issues 😄

**Comment by LucaBlackDragon** [comment]
OK thanks!

**Comment by LucaBlackDragon** [comment]
@kunagpal By the way I think you should update your [Sandbox docs](https://www.getpostman.com/docs/postman/scripts/postman_sandbox) and mark SugarJS as deprecated, like you already did for BackboneJS.

**Comment by kunagpal** [comment]
@LucaBlackDragon The deprecation notice for Sugar.js has been added here: https://www.getpostman.com/docs/postman/scripts/postman_sandbox#commonly-used-libraries-and-utilities
