### ISSUE TITLE
Hello,my postman stucks, and have to install new one, where i can find my collections? I use win 10

### ISSUE THREAD

**Issue by rvainio** [a85/POSTMan-Chrome-Extension#3160]
## App Details:

```
Postman for Mac
Version 4.11.0
OS X 16.4.0 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:
 2. Expected behaviour:
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 4. Screenshots (if applicable)

**Comment by rvainio** [comment]
MyPostman stucks on sending and can't use it,  after restart my pc , and start Postman again, I can see it in taskbar but can't  use it, it doesn't open,  I install new one and it works,  now I want to find my  old collections, so in which directory in my win10 pc I can find those?

**Comment by SamvelRaja** [comment]
@rvainio The new app version you installed should automatically loads the old app data into it. 
Can you help me in reproducing the issue?  

Anyhow, the app data will be stored in C:\\Users\[USER]\AppData\Roaming\Postman  which won't be in the readable format.

**Comment by rvainio** [comment]
Hi, thx for fast comment, i don't know how to reproduce, Postman just stuck, I check the folders but can't find my JSON files from there, maybe unreadable format. :(

**Comment by SamvelRaja** [comment]
@rvainio Did you signed into your postman account? if so don't worry your collections will be synced with us. Can you send mail to help[at]getpostman.com to help in retrieving it.

**Comment by rvainio** [comment]
not sure, don't remember , I install my Postman 2.5.2017, but maybe just install it without signed in . 
anyway I will sent email so you can check

**Comment by SamvelRaja** [comment]
@rvainio Yeah sure goahead. If you had the account we shall help with that.
