### ISSUE TITLE
Not sending pasted fields in form-data or x-www-form-urlencoded

### ISSUE THREAD

**Issue by pauloallex24** [a85/POSTMan-Chrome-Extension#3162]
## App Details:
```
Postman for Mac
Version 5.0.0
OS X 15.6.0 / x64
```

## Issue Report:
1. When I add a key and a value to x-www-form-urlencoded it doesn't send throw POST or PUT to the server.
2. If I move the key, it continues not sending.
3. It happen if I past the content in `Key-value Edit`.
4. If I enter `Bulk Edit` and go back to `Key-value Edit` it sometimes send. And sometimes I need to edit in the `Bulk Edit` before go back `Key-value Edit` in order to send the field.
5. I can confirm that it happens in `x-www-form-urlencoded` and `form-data`and not in URL `Params`.
6. It happened at least with POST and PUT requests.
7. I've notices this in this version and in previous update.
8. If I copy and past from and to `Bulk Edit` it doesn't happen.

Tell me what can I do to give you more data about this bug.

## How to reproduce:
1. Copy one or more fields with the selection tool in `Key-value Edit` from one endpoint and past it in another.
2. The field(s) will not be sent unless I edit the fields in `Bulk Edit`mode.
Note: It will happen in `form-data` and `x-www-form-urlencoded` but not in URL `Params`.

(updated)

**Comment by SamvelRaja** [comment]
@pauloallex24  Thanks for bringing this to our notice, we shall check the same and let you know the details in the same thread.

**Comment by pauloallex24** [comment]
Just happened when I past a copy of all fields of another endpoint, copied and pasted in `Key-value Edit` mode. Changed between `Bulk Edit` and go back to `Key-value Edit`and still not working. Just worked when I went to `Bulk Edit`, added one paragraph and went back to `Key-value Edit`.
I was in a PUT request this time.

**Comment by pauloallex24** [comment]
Just been able to reproduce the bug. Will now edit the first post.

**Comment by prashantagarwal** [comment]
@pauloallex24 This is now fixed in the newer releases of Postman. Can you please update your app. Feel free to reopen if you are still seeing this issue.
