### ISSUE TITLE
Cannot get first set-cookie entry.

### ISSUE THREAD

**Issue by klubi** [a85/POSTMan-Chrome-Extension#3163]
## App Details:
```
Postman for Mac
Version 5.0.0 (5.0.0)
OS X 10.12.5 (16F73)
```

## Issue Report:
 1. Make a request to any service that returns two *Set-Cookie* entries. (In my case It's JSESSIONID and AWSELB)
 2. Cookie manager recognizes both of them properly.
 3. In tests there is no way to get first *Set-Cookie* entry using `postman.getResponseHeader("Set-Cookie");`
 4. Both cookies are present in Postman main window, but in Postman Console Window only second one is listed.

**Comment by kamalaknn** [comment]
Hey @klubi 

Ideally `postman.getResponseHeader('Set-Cookie)` should have returned an array of all the `Set-Cookie` headers, you have multiple headers.

We'll look into this.

Thanks for the report.

**Comment by klubi** [comment]
Hi @kunagpal, @kamalaknn 
I managed to find a workaround for this.
`postman.getResponseCookie('JSESSIONID').value`

But few minutes later I found the opposite situation, it turns out I cannot place multiple `Set-Cookie` headers, looks like only the last one is being sent.

**Comment by kunagpal** [comment]
@klubi As the name suggests, `postman.getResponseCookie` is meant to return one cookie. However, You can use `pm.cookies.all()` to obtain an array of cookie objects.

**Comment by klubi** [comment]
Thanks @kunagpal

Is there a documentation page where all `postman...` commands are listed so I can try to look for the one I need on my own, instead of opening stack over question or github issue?

**Comment by kunagpal** [comment]
https://www.getpostman.com/docs/postman/scripts/postman_sandbox
