### ISSUE TITLE
Desktop app command line arguments

### ISSUE THREAD

**Issue by phcs93** [a85/POSTMan-Chrome-Extension#3165]
## App Details
```
Postman for Windows
Version 5.0.0
Windows 10 / x64
```
## Question
I'm using postman to debug my ASP.NET WebAPI on Visual Studio.

I've configured VS to "browse with" postman when running a WebAPI. It launches the app properly but, it would be amazing if I could set up the starting URL/Method/Headers/etc through the command line.

My question is, are there any command line arguments for the desktop app?

**Comment by kamalaknn** [comment]
Hey @phcs93 

This is interesting.

I am tagging this as a feature request. @a85 can clarify on the roadmap for this.

Thanks.

**Comment by VitaliyKurokhtin** [comment]
It would be even more useful if this scenario is supported via link from browser. That way it will be a lot easier to integration into any web app that allows user to build random HTTP requests, like Postman itself, or provides access to any API that is updated frequent enough to make it infeasible to upload every time.

**Comment by a85** [comment]
We will open an app level API for these workflows but there are no plans currently for command line arguments.
