### ISSUE TITLE
Duplicate interfaces open using shortcut to open Postman console 

### ISSUE THREAD

**Issue by codetotest** [a85/POSTMan-Chrome-Extension#3169]
## App Details:

```
Postman for Mac
Version 4.11.0
OS X 16.4.0 / x64
```

Postman Version -- 5.0.0

## Issue Report:

on Mac try ⌥⌘C this would open two postman console windows.

Expected : only one.

**Comment by kamalaknn** [comment]
Hey @codetotest 

That doesn't seem right. We'll look into this and see what we can do. 

Thanks.

**Comment by a85** [comment]
Seems to be fixed now.
