### ISSUE TITLE
Test Runner : URL Value Is incomplete/malformed

### ISSUE THREAD

**Issue by jordan1k** [a85/POSTMan-Chrome-Extension#3170]
## App Details:

```
Postman for Windows
Version 5.0.0
win32 10.0.10586 / x64
```
After the most recent update there seems to be some issues around Test Runner URL construction/usage. Previously there was no issue and all tests would pass as expected.
Attached are two test run outputs: One being from the Native App and one from the Chrome Extension.
The Chrome Extension seems function as expected.
Both test runs originate from the same collection file.

Examining the "url" values for the test "name" of "Sponsors for a bill 1" in the two attached outputs highlight the difference in the URL values. The URL in the Native App seems to be incomplete. There are further examples contained in the files ( most seem to center around a pattern of "...&$expand=<nested data structure>([commands])" ).

[LDSAPIFROMNATIVEAPP.txt](https://github.com/postmanlabs/postman-app-support/files/1078609/LDSAPIFROMNATIVEAPP.txt)
[LDS APIFROMEXTENSION.txt](https://github.com/postmanlabs/postman-app-support/files/1078611/LDS.APIFROMEXTENSION.txt)

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there: Recent, with newest updated
 2. Expected behaviour:
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 4. Screenshots (if applicable)

**Comment by SamvelRaja** [comment]
Thanks for bringing this to our notice we shall look into it and update the progress here.
