### ISSUE TITLE
Long collections/monitor runs time out - please increase 5 minute limit

### ISSUE THREAD

**Issue by dwertheimer** [a85/POSTMan-Chrome-Extension#3171]
I have a collection that crawls my API and tests each of the URLs within, looking for 404s, via setNextRequest(). It always times out before completion when run as a monitor or from Newman. 

`Error: callback timed out`

Support told me:

> Our monitors have a built-in limit of 5 minutes to run, to prevent abuse and accidental overcharges (like ones caused by infinite loops). You can read about this and other information in our Monitor FAQs section of our docs. At the moment we don't have plans to extend or remove the limit, but we'd love for you to send it in as a "new issue" to our GitHub. This lets it get a wider audience, so we can see how many of our users are interested in this changing.

I understand/appreciate that, but since I am paying by the request, you should be happy for me to keep the servers firing off requests if I do so with my eyes open.  Please either add a checkbox in "monitors" to remove time limits (with any warnings, disclaimers and price tags you want), or allow me to change that time limit to my discretion.

FWIW, I can't do this locally in Newman either, because Newman runs out of memory and dies after about 500 requests. Still, I would prefer to have it run as a monitor so that I can have it run once a day and just report the results.

**Comment by SamvelRaja** [comment]
Thanks for bringing this to our notice we shall look into this and update the progress here.

**Comment by rgangal** [comment]
any update on this ? I am running into same issue where my tests needs to wait for 10 mins.

**Comment by SimeonPetkovAtlaSense** [comment]
We have the same problem with our API acceptance tests that need to wait for some data to get synced before they check the data.

**Comment by amnoman** [comment]
I'm facing the same problem. My collection need much more time because to send next request I've to wait for certain update. Need a solution asap!

**Comment by NeilHarper** [comment]
We have a background process that runs on our server on a regular 5 minute period to process some of the data that was uploaded via our API. My tests require me to wait for 5 minutes after I do an upload to make sure that the processing is complete. This means that my monitor fails on the first test (and I have quite a few tests in the suite :-( ). I would really appreciate a solution to this.

**Comment by pablo-lago** [comment]
+1

**Comment by etspaceman** [comment]
+1

**Comment by smurugesh1686** [comment]
+1

**Comment by ionapjolive** [comment]
+1

**Comment by MartinIvison** [comment]
+1

**Comment by jayanthktn** [comment]
+1

**Comment by shivamconan** [comment]
+1

**Comment by edwinboy0312** [comment]
+1 . is there any update on this ?

**Comment by loctb** [comment]
+1 please help us about this issue

**Comment by edwinboy0312** [comment]
i hope you guys have already ready out ' --timeout-request 25000 ' if not give it a shot.

**Comment by JeffLoo-ong** [comment]
+1

**Comment by ArnauNaval** [comment]
+1

**Comment by alibaghernejad** [comment]
It's happened for me too.
Postman monitoring generate repeating error that say "Error: callback timed out"

**Comment by damircuca** [comment]
Love the product - but agree with everyone else 5 minutes doesn't make much sense. Now I have to copy / paste postman collections x 50 times - just to get around this issue.

**Comment by Lucifer90** [comment]
+1

**Comment by alaulkar** [comment]
Just received Monitoring Blocks Price Update email. Would love to but won't be able to scale it as long as callback timeout limitations are in place. 
Any kind of update on this would be greatly appreciated.
Thanks!

**Comment by rtabor** [comment]
+1

**Comment by rmdaggett** [comment]
+1

**Comment by MatthewOBoyle** [comment]
+1

**Comment by leompeters** [comment]
+1

**Comment by Satak** [comment]
We have the same issue. Hitting the 5 minute mark because we have long running tests. Please increase this to 10 minutes.

**Comment by kgjelsten** [comment]
+1

**Comment by davidteofilovic** [comment]
+1

**Comment by sulmanbashir** [comment]
+1

**Comment by jon-robinson** [comment]
+1

**Comment by malyalal** [comment]
Is there a fix or workaround for this problem? It's been 2 years and still I 'm facing the same issue with my collection monitor. Please advice.

**Comment by John2496** [comment]
+1

**Comment by jg8481fp** [comment]
+1

**Comment by j-fbriere** [comment]
+1

**Comment by giu87** [comment]
+1

**Comment by kvarela** [comment]
+1

**Comment by AndrewYoungQA** [comment]
+1

**Comment by Budanovvv** [comment]
+1

**Comment by colbsmcdolbs** [comment]
+1

**Comment by astoykovych** [comment]
+1 
Do we have at least any workaround on this problem?

**Comment by VicKetchup** [comment]
An idea I mentioned to Postman team member back in November, posting it here for some feedback and maybe a nudge to get this resolved:
"If this issue is being delayed due to running costs, can I suggest allowing users to go over 5 minute limit if they desire, but every 5 minutes will be charged as a monitor run. So for example, our monitor complets in 6 minutes > we get charged as for 2 monitor runs, as in this way it will be up to us to optimise performance but avoid the issues due to this set limit."

**Comment by Davi-DeGanne** [comment]
I found this in the Monitors FAQ, and it's amazing how antithetical this statement is:

> Will Monitors impact my API performance?
You have full control over the behavior of your monitors. Not only can you determine which of your API endpoints are called, you can also determine how many and how often they are called. In addition, Postman restricts each monitor’s total run time to 5 minutes, to limit the number of requests it can perform.

We have "full control" yet are limited to 5 minutes...? What if I want to wait 10 seconds between each request, to make absolute sure that the tests aren't impacting our API's responsiveness for customers? Then I'm limited to under 30 requests? Or what, I'm forced to do shenanigans like split my 300 request collection into 10 other collections, and daisy-chain them all with the Postman API? That's insane.

I understand that this was probably an attempt to prevent collections from running in a loop or something, clogging up your servers and potentially incurring undesired costs for the customer. But as a customer that knows what the hell he's doing, and is never going to cause problems like that, I find it rather suffocating that I'm forced to leave these monster-sized training wheels on.

If you really must have a time-based hard-cap, at least let us go into the settings and extend/remove it. Other cloud-based computing services approach it this way, and seem to do just fine.

**Comment by alekscp** [comment]
+1

**Comment by godfrzero** [comment]
Hey folks, we're actively working on this issue and we plan to extend the 5-minute limit to 10 minutes before early next week. We'll work on extending it further in additional releases after that. There's no change necessary from your end at this time, monitors which are currently timing out due to the 5 minute limit will automatically extend their run times.

**Comment by godfrzero** [comment]
The timeout for all monitors have been extended to 10 minutes now. We're working on additional timeout extensions and, if necessary, configuration options. I'll post additional updates here as they become available. 👋

**Comment by godfrzero** [comment]
The timeout for monitors have now been extended to 15 minutes for folks on any of the paid plans — free plans are still subject to the 10-minute limit. I'm closing this ticket for now since the original intent has been addressed. If the 15-minute timeout still feels restrictive, please let us know and I'd be happy to learn more about your use case.

Cheers!
