### ISSUE TITLE
Only 1 response header per key is parsed to JSON

### ISSUE THREAD

**Issue by justlauzadis** [a85/POSTMan-Chrome-Extension#3172]
## App Details:

```
Postman for Windows
Version 5.0.0
win32 10.0.15063 / x64
```

## Issue Report:
Response headers containing several set-cookie headers are parsed to JSON object having only one set-cookie value instead of an array of all values.

![image](https://user-images.githubusercontent.com/29478115/27219067-f642715a-5288-11e7-9816-211dc9909351.png)

**Comment by kamalaknn** [comment]
Hey @justlauzadis 

Thanks for reporting this. This should not have been the case here. All headers should be listed.

We'll look into this.

**Comment by jerrfi** [comment]
I'm having this same problem where multiple "Link" header items are returned but tests only find the last Link header processed even though both Links appear in the Postman response Header.

Postman Console also shows only the last Link header rather than all headers named "Link".

**Comment by justlauzadis** [comment]
Could this help?:

When I attempt to call `postman.__execution.response` I receive an `Error: Invalid Chai property: _postman_propertyIsList`

**Comment by justlauzadis** [comment]
Workaround:
`var resHeaders = postman.__execution.response.headers;`
`var auth = resHeaders.filter(function(header){`
  `return (header.value.includes('Authorization='))`
`})[0].value;`

**Comment by a85** [comment]
@kamalaknn Is this fixed?

**Comment by jerrfi** [comment]
This problem still exists for our usage.

The response header for a single API call includes line like these: (in this order)

Link →<http://server/endpoint?...&page=3>;REL=next
Link →<http://server/endpoint?...&page=3>;REL=previous

The Test to validate the response includes:

var linkIndexNext = postman.getResponseHeader("Link").toString().indexOf("REL=next");
tests["Link Header contains REL=next"] = linkIndexNext > -1;

var linkIndexPrevious = postman.getResponseHeader("Link").toString().indexOf("REL=previous");
tests["Link Header contains REL=previous"] = linkIndexPrevious > -1;

The Test Results should mark both of these assertions as a PASS.  But beginning with version 5.0.0 Postman began incorrectly reporting:

FAIL Link Header contains REL=next | AssertionError: expected false to be truthy
PASS Link Header contains REL=previous

The Tests Results seem to only correctly validate the last occurrence of "REL=*" found in the header.

Reversing the tests order doesn't make a difference;  The Tests Results only validates the last occurrence of "REL=*" found in the header.  The other occurrence ("REL=next") is always incorrectly marked as a FAIL.

These tests successfully worked as expected prior to version 5.0.0.

**Comment by kamalaknn** [comment]
The original issue posted here where headers with multiple keys were not listed in the response sections is fixed. Please update to the latest version.

@jerrfi For your case, you can use the `pm.response.has('Key', 'Value')` if you have control over the exact value you are trying to match. Otherwise, use `pm.response.toJSON()` to get a complete list of all headers and you can test for the key you are looking for.
