### ISSUE TITLE
Multi-line parameters - newlines converted to ampersand

### ISSUE THREAD

**Issue by freshehr** [a85/POSTMan-Chrome-Extension#3176]
## App Details:

```
Postman for Mac
Version 5.0.0
OS X 16.6.0 / x64
```

## Issue Report:
This issue arose after the new multi-line edit feature was introduced.

The API I work with makes use of a SQL/XPATH like string called AQL passed via a GET parameter This is normally formatted with newlines for readability e.g.

```
aql:select 
  a/uid/value as uid,
  a/composer as author
  from EHR e
```
Prior to the multi-line edit feature, it was easy to paste this string in directly and Postman would correctly encode it. Now it appears that the newlines are interpreted as ampersands.

```GET /rest/v1/query?aql=select&amp;a/uid/value as uid,&amp;a/composer as author&amp;from EHR e HTTP/1.1
```
Can I confirm if if this expected behaviour, or of there are any workarounds/ settings that I can use to revert to previous behaviour?

More of an annoyance than a bug, especially since Postman is otherwise such a fantastic tool but it worked great for me before and not so good now.

**Comment by sdnts** [comment]
Hi @freshehr, I was unable to see this. I pasted the params you provided and the new lines weren't converted into ampersands. Did I miss a step?
