### ISSUE TITLE
Postman app: how to use custom DNS resolver (Linux)

### ISSUE THREAD

**Issue by Blasterdick** [a85/POSTMan-Chrome-Extension#3177]
```
Postman for Chrome
Version 5.0.1
linux / x86-64
Chrome 59.0.3071.86
```
How can I use local `dnsmasq` on `127.0.0.1` to resolve hosts in Postman with it? 

Thanks in advance for any kind of help.

**Comment by czardoz** [comment]
@Blasterdick Postman uses the system DNS resolver, so you'll have to set it in your network options.

**Comment by Blasterdick** [comment]
@czardoz I've set up `dnsmasq`, added `nameserver 127.0.0.1` to the first line of `/etc/resolv.conf` file, so `nslookup mydomain.com` gives an expected result, and Google Chrome uses local resolver as well.

But requests from the Postman app goes to a real IP. 

> Postman uses the system DNS resolver

So, it seems like it's not. Maybe, I can somehow debug it? 

Thanks in advance.

**Comment by Blasterdick** [comment]
False alarm, thank you, @czardoz, after restarting Postman everything works as expected.
