### ISSUE TITLE
[Feature Request] - Ability to Access Collection and Request (Edit) Information In Pre-request and Tests Logic

### ISSUE THREAD

**Issue by labossieresr** [a85/POSTMan-Chrome-Extension#3179]
## Feature Request
I don't see a way to access via script within the Pre-request or Tests tabs the Name and Description information of the Collection or the Description of a given test I am on. For example, I may have a collection named "Collection 1" with a Description of "This is my first collection". Something similar can exist for each API test created within the collection. Well, I'd like to access that information programmatically so I could do things like make note of where I am  (i.e. debugging/logging/test step 'T' in collection 'C'). I do see that I can get the test name via pm.info.requestName but not the Description.

**Comment by sdnts** [comment]
Hi @labossieresr, thanks for the feature request! You can get the request name using `request.name`, or `pm.info.requestName` (But I see you've figured that out already).
We'll look into adding more collection meta to the `pm.info` object!

**Comment by labossieresr** [comment]
Thank you madebysid!  Unfortunately, I just discovered that pm.info is only accessible directly in Postman. When running a collection via Newman a reference error is generated (pm is not defined). So using request.name is the way to go for my needs as it is supported within Postman and Newman. The additional meta I am looking to get, both the description for the request as well as name and description of the collection, would be desired from within Postman and Newman via the same syntax. Also, are you able to point me to a good source that describes the request object so I can see what else besides .name is available?

**Comment by abhijitkane** [comment]
@labossieresr The latest versions of Newman should support the same API that Postman does. The complete docs are at https://www.getpostman.com/docs/postman/scripts/postman_sandbox_api_reference and https://www.getpostman.com/docs/postman/scripts/postman_sandbox.
