### ISSUE TITLE
Changing Value of Global Variable Removes it From Existence

### ISSUE THREAD

**Issue by junkert** [a85/POSTMan-Chrome-Extension#3182]
## App Details:

```
Postman for Mac
Version 5.0.0
OS X 16.6.0 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:
```
I am new as of Postman 5.0.0. This happens every time the Set method is called.
``` 
2. Expected behaviour:
```
- When changing a global variable's value to nothing the variable should stay and not be removed.
Currently changing the variable's value to an invalid value will make the variable disappear from
global scope. The variable should stay and an error in the console / UI should indicate that the user
is trying to do something that is invalid.
```
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-
postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
```
 
```
 4. Screenshots (if applicable)
```
See below
```

Steps to reproduce the problem

1. Create a global variable (auth_token in our example)
[https://ibb.co/noXVyQ](https://ibb.co/noXVyQ)
2. Create a fake JSON-API endpoint that returns the variable "auth_token".
[https://ibb.co/ex5Tk5](https://ibb.co/ex5Tk5)
3. Notice that we do not define data until after it has already been used. This is invalid and should throw an error. Data is not defined until after its use.
[http://ibb.co/g8v0yQ](http://ibb.co/g8v0yQ)
4. Now look in globals and notice variable is now gone! 😢 
[Sad Panda](https://ibb.co/n74cdQ)

**Comment by prashantagarwal** [comment]
@junkert Thanks for reporting this. Try renaming you variable **data** to something else. Actually **data** is a postman variable which Postman expose when you run this request in Runner. So while running this in **Request Builder** data is an empty object and hence data.auth_token resolves to undefined.

**Comment by junkert** [comment]
Thanks @prashantagarwal. We have moved over to newman for our testing and have fixed the error in our javascript. Thanks for getting back to us quickly.
