### ISSUE TITLE
When I set number to a global variable or environment variable ,it is not setting exact value but rather decremented by 1.

### ISSUE THREAD

**Issue by acharVignesh** [a85/POSTMan-Chrome-Extension#3183]
## App Details:

```
Postman for Linux
Version 5.0.1
Ubuntu 16.04.2 LTS
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:
I have not tried with the older version, so not sure whether this bug always been there.
 2. Expected behaviour:
I'm trying to set some id's from the response to the global variable for request chaining. The id number set to the global variable is decrement by 1. Expecting correct value should be set.Please check the screenshot below.
Here orderId=11983534162602985
what is set is=11983534162602984

![postmanissue](https://user-images.githubusercontent.com/12829702/27320710-075feaba-55b5-11e7-9bbe-8d33bf568fb8.png)

 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
NA
 4. Screenshots (if applicable)
Please check the screenshot above.

**Comment by prashantagarwal** [comment]
@acharVignesh Thanks for reporting this. I am not able to reproduce this though. Is this happening for all the variables which you are setting or for this specific case ?

**Comment by acharVignesh** [comment]
@prashantagarwal  I'm facing it for the variable with numbers(numbers with many digits). Other values are set properly. One hint I could give is that it would be parsing issue because if I take the raw response from postman try to format it in any other web based JSON parser, I could see that fields having value being decremented. Attaching the raw response snippet from the postman. Try to parse/beautify it.
[Snippet.txt](https://github.com/postmanlabs/postman-app-support/files/1087848/Snippet.txt)

**Comment by acharVignesh** [comment]
@prashantagarwal did you get any clue?

**Comment by sdnts** [comment]
@acharVignesh I think this has to do with the large numbers, since JS can only handle numbers up to 16 digits in precision. Can you try converting the number to a string and try again? I'm guessing you'll use it your URLs, so it shouldn't affect other requests.
