### ISSUE TITLE
Condition on Request

### ISSUE THREAD

**Issue by waytoharish** [a85/POSTMan-Chrome-Extension#3184]
Hi Team,
I am looking to put test condition on Request like request contain 'Name'.I want to execute my test case only if  my request have name otherwsie i dont want to send request.How can i control the same in POST Man Test

## App Details:

```
Postman for Mac
Version 4.11.0
OS X 16.4.0 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:
 2. Expected behaviour:
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 4. Screenshots (if applicable)

**Comment by prashantagarwal** [comment]
Hi @waytoharish do you want to use this in Runner ?

**Comment by waytoharish** [comment]
Yes.I am trying to run with POST Man Runner

**Comment by a85** [comment]
You can use setNextRequest and the scripting sandbox to achieve this. Check out our docs: www.getpostman.com/docs
