### ISSUE TITLE
Save environment variable from json output in postman function

### ISSUE THREAD

**Issue by decode007** [a85/POSTMan-Chrome-Extension#3185]
I have output data like:

`{
"dbflash:db-files": {
    "db-file": [
        {
            "usageStatus": "Backup",
            "dbFileName": "DB_1710013320170619041443",
        },
        {
            "usageStatus": "Current",
            "dbFileName": "DB_1710013320170619111647",
        }
    ]
}
}`
For which i need to set environment variable for backupDbFile and currentDbFile

I have written iterator for that, but because of key "dbflash:db-files" and "db-file" it is showing me syntax error.

`var jsonData = JSON.parse(responseBody);
jsonData.dbflash:dbfiles.db-file.forEach(function(entry) { 
if (entry.usageStatus === 'Current') {
    postman.setEnvironmentVariable("currentDb", JSON.stringify(entry.dbFileName));   
}
if (entry.usageStatus === 'Backup') {
    postman.setEnvironmentVariable("backupDb", JSON.stringify(entry.dbFileName));   
}
});`
Tried using quotes also but that too is not working

`jsonData.'dbflash:dbfiles'.'db-file'.forEach(function(entry)`

**Comment by prashantagarwal** [comment]
@decode007 try using **square bracket notation** `jsonData["dbflash:db-file"]` rather than **dot notation**.
Dot notation gives syntax error when you try to access invalid JSON keys.

**Comment by decode007** [comment]
jsonData["dbflash:dbfiles"]["db-file"].forEach(function(entry) 

With this was also i am seeing error "cannot read property 'db-file' of undefined

**Comment by prashantagarwal** [comment]
@decode007 can you please check your property names once.
Shouldn't it be `jsonData["dbflash:db-files"]["db-file"].forEach(function(entry)`
