### ISSUE TITLE
Replace All on import

### ISSUE THREAD

**Issue by brigand** [a85/POSTMan-Chrome-Extension#3187]
## App Details:

```
Postman for Mac
Version 5.0.0
OS X 16.6.0 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there: Always
 2. Expected behaviour: When reimporting I'd like to replace all in one click, instead of multiple modals.
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app): N/A
 4. Screenshots (if applicable) N/A

Click import, drag/drop postman json files onto the import modal. Click replace. Wait half a second. Click replace again, etc.

Our workflow is that we check postman json files into git (out of my hands to change), and I regularly need to reimport all of the files edited by the backend team.

Thanks!

**Comment by vkaegis** [comment]
Hey @brigand! Thanks for bringing this to our attention, this could definitely be improved. We'll let you know as soon as a fix is out for this.

**Comment by a85** [comment]
No plans for additional work on this. We recommend using Workspaces for sharing and collaboration.
