### ISSUE TITLE
Postman Native Client Font Size

### ISSUE THREAD

**Issue by ChadEpstein** [a85/POSTMan-Chrome-Extension#3190]
I'm using the native Windows client and the font size is smaller than the Chrome App and harder to read.  Can we please get a way to resize the font size of the UI (not just the request and response text) e.g. collection names, request URL etc?

**Comment by kamalaknn** [comment]
@C-4 Sorry about that.

We'll see if we can change the default font sizes. 

In the mean time you can try increasing the zoom level of the app with `ctrl +`. 

Thanks.

**Comment by rsabirov** [comment]
I agree, font sizes too small.
