### ISSUE TITLE
Save endpoint response as an enviroment

### ISSUE THREAD

**Issue by hertzigger** [a85/POSTMan-Chrome-Extension#3191]
This is a feature request not a bug.

Hi, I'm using the new environments a lot (great work btw), I'm using them so much that I've created an endpoint in my application that generates a test user and responds with an environment. I copy the response and save it, then import it as a new environment in postman. Its a slight niggle but i'd like the option to save my response as a new environment directly in postman. This would cut out a few steps for me.

It's not a big issue but very nice :)

**Comment by kamalaknn** [comment]
Hey @hertzigger 

Thank you for your feedback. 

I am tagging this as a feature request.

We'll have a look at this. @shamasis @a85 your thoughts on this?

Thanks.

**Comment by czardoz** [comment]
Well, the best way to go about this, is to use the Postman Pro API (api.getpostman.com) to import the environment.

**Comment by a85** [comment]
@hertzigger This is tricky as we want to keep collections and environments decoupled. As @czardoz says, using the Postman Pro API might be a better solutions.
