### ISSUE TITLE
Headers with `\n` in their Value are silently stripped

### ISSUE THREAD

**Issue by adskdouglaz** [a85/POSTMan-Chrome-Extension#3195]
Postman silently drops Headers with values containing `\n`.

## App Details:

```
Postman for Chrome
Version 5.0.1
win / x86-64
Chrome 60.0.3112.32
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:
    Recently; but I'm new to Postman
 2. Expected behaviour:
    Postman strips or errors when pasting Header Values containing `\n`
 3. Console logs:
    N/A
 4. Screenshots (if applicable)
    N/A

### Reproduction
  1. Put a string with a `\n` on your clipboard
  2. Create a new (GET) Request Header with any Key
  3. Paste the clipboard into the Value field
  4. Send the request

**Comment by SamvelRaja** [comment]
Thanks for bringing this to our notice, we shall update the progress in same thread.

**Comment by SamvelRaja** [comment]
According to this [RFC](https://tools.ietf.org/html/rfc822#section-3.1) HTTP Headers should not have CRLF
Hence closing the issue.
