### ISSUE TITLE
Is it possible to refer to postman call name within the tests body

### ISSUE THREAD

**Issue by mailtogj** [a85/POSTMan-Chrome-Extension#3196]
## App Details:
Postman for Chrome
Version 5.0.1
win / x86-64
Chrome 58.0.3029.110

In my collection, I have various requests within folders.
e.g. Collection>CollectionFolder1>Request1, Request2 ...

Is it possible to get a reference of the request names within the tests so that I could write something like:

try {
    ...
} catch (e) { 
     tests[`Test failed with exception ${e} for call request ${SOME_VARIABLE_THAT_STORES_REQUEST_NAME}`] = false 
}

**Comment by SamvelRaja** [comment]
@mailtogj `request.name` is the one you are looking for.
```javascript
var e = 'message';
tests[`Test failed with exception ${e} for call request ${request.name}`] = false;
```
