### ISSUE TITLE
Skip First Request

### ISSUE THREAD

**Issue by sadiqkhoja** [a85/POSTMan-Chrome-Extension#3197]
I want to skip first request based on a condition.

Context:
First request is a token request and I run collection 100 times so I want to execute first request only for first iteration or if token is expired. setNextRequest in pre-request script can't be use in this case as it sets next request in pipeline and current request is execute in any case.

Alternative solution: 
I can add a dummy request to www.example.com but that would be useless network call, I tried data:html;,abc but this is appending http to request and failing

## App Details:
Postman for Windows
Version 5.0.0
win32 10.0.10586 / x64

**Comment by sdnts** [comment]
@sadiqkhoja Hmm, as of now, there isn't a standard way of doing what you want, unless you add a dummy request. (Maybe try `localhost`?). We're working on collection script support in the app, which I believe should solve your issue as well.
I'm closing this in favour of: https://github.com/postmanlabs/postman-app-support/issues/2749

Please reopen if you think I misunderstood and these two aren't the same :)

**Comment by sadiqkhoja** [comment]
Thank @madebysid, collection script would solve my problem as well. One related question, is there any way to skip current request based on a condition in pre-request script? If I put setNextRequest(null) in pre-request even then current request is executed, is it desire behavior? [Documentation](https://www.getpostman.com/docs/postman/collection_runs/building_workflows) says something else:

> setNextRequest() is always executed at the end of the current script. This means that if you put setNextRequest() in a pre-request script, the current request will never be sent.

**Comment by sdnts** [comment]
Indeed, this is desired behaviour. I'll update the docs to reflect this as well. Thanks for pointing this out.
