### ISSUE TITLE
New JSON Validator Needed

### ISSUE THREAD

**Issue by jon49** [a85/POSTMan-Chrome-Extension#3199]
Since it doesn't appear that `tv4` is being actively maintained I think this issue needs to stop being punted down the road. Not only is `tv4` not maintained, but neither is it standard compliant with the `JSON Schema` standards.

As you can see there hasn't been any work done of on the source code for 2 years - <https://github.com/geraintluff/tv4>.

If you look at the issues you can see that they are not responded to by the original author:
<https://github.com/geraintluff/tv4/issues>

I think Postman owes it to its users to investigate and use a standards compliant library that is actively maintained.

A wrapper around the new library can be used so that the old `tv4` API can still work properly while still displaying the new API of whatever library Postman chooses to use.

Here are previous issues on the subject:

**Open**
#2788

**Closed** 
#3173
#3138
#2574

Thanks in advance!

**Comment by sdnts** [comment]
@jon49 We will definitely look into this. As you said, we'll need to add a new library in order to keep previous tv4 scripts working.
@shamasis @kunagpal Can we look into this for `postman-runtime`?

**Comment by tlemons** [comment]
Hi - thanks for being so receptive about looking into this.  Being unable to perform JSON response validation is a big 'hole' for us right now. I'd like my team to focus on Postman for our testing, but we'll need to look for alternates for the JSON response validation soon.  Could you share your timeline for adding functional JSON validation?  Thanks!

**Comment by sdnts** [comment]
Hey! Our public roadmap is available here: https://trello.com/b/4N7PnHAz/postman-roadmap-for-developers so you can watch that.

**Comment by tlemons** [comment]
Thanks for this pointer; I'll follow this from now on.  So, it appears that addressing JSON validation is not even a planning-level card, so this issue won't be addressed in the foreseeable future; is that correct?  Thanks.

**Comment by sdnts** [comment]
Indeed, but since this is a new issue, we'll look into this in detail and update the roadmap accordingly :)

**Comment by tlemons** [comment]
Ah.  thanks.

**Comment by jvkaam** [comment]
To motivate an upvoting I would suggest that having a full CI and CD environment in which you generate Postman collections you definitely want to validate it against its own schema.

**Comment by tlemons** [comment]
I would like to motivate upvoting of this feature, but don't know how to accomplish what jvkaam suggested. That said, is this feature being considered for a future release?  Thanks!

**Comment by imranismail** [comment]
Any update on this?

**Comment by shamasis** [comment]
Thinking of adding Ajv -> https://www.npmjs.com/package/ajv - does that sound good?

**Comment by kamalaknn** [comment]
We've added `ajv` library to the sandbox scripts. This should be available in Postman native apps starting from 6.7.1.

**Comment by king4sam** [comment]
Did anyone use ajv successfully on postman native app v6.7.1? ( on MacOS )
I followed instructions [here](https://learning.getpostman.com/docs/postman/scripts/postman_sandbox_api_reference) to  require ajv in test script, but I got error as below

```
var Ajv = require('ajv');
var ajv = new Ajv();  // ReferenceError: console is not defined
```

Is there somebody met the same issue or I require ajv in the wrong way?

**Comment by codenirvana** [comment]
@king4sam You can refer the example given [here](https://learning.getpostman.com/docs/postman/scripts/test_examples/).

You either have to use `{logger: console}` option or `{logger: false}` to avoid the ReferenceError.

Example:
```javascript
var Ajv = require('ajv'),
    ajv = new Ajv({logger: console}),
    schema = {
        "properties": {
            "alpha": {
                "type": "boolean"
            }
        }
    };

pm.test('Schema is valid', function() {
    pm.expect(ajv.validate(schema, {alpha: true})).to.be.true;
    pm.expect(ajv.validate(schema, {alpha: 123})).to.be.false;
});
```

This is because `console` is not directly available(inside sandbox) to Ajv and when `logger` option is missing, Ajv will [assign console](https://github.com/epoberezkin/ajv/blob/v6.7.0/lib/ajv.js#L488) by default and throws ReferenceError.

**Comment by king4sam** [comment]
@codenirvana thank you!
