### ISSUE TITLE
Sync'd changes made on Laptop are not visible when logging into same account on Desktop.

### ISSUE THREAD

**Issue by serkand** [a85/POSTMan-Chrome-Extension#3200]
## App Details:
Postman for Windows
Version 5.0.0
win32 10.0.15063 / x64

## Issue Report:
I have been using Postman for windows on my Desktop for a while now and recently, I installed v5.0.0 on my laptop in order to continue to work on my collections from home. Both are Windows 10 machines and have the same version of Postman for Windows installed.

Last night, I made changes to my collection on my laptop and ensured that I was IN SYNC. Today, I log into my desktop and my latest changes are not there. I have tried "signing out and deleting local data" on my desktop and then signing back in. I still don't get the changes that I can see on my laptop.

I force sync'd my changes on the laptop, exited the app and repeated the sign out and sign in process on the desktop but still can't see the latest code change. Also tried the manual re-sync on the desktop, but the button doesn't seem to do anything, so I disabled Sync, restarted the App (without signing out) and then enabled the sync. After the sync process finished, I checked for the expected changes but no such luck!

I am using the same account on both machines and expected that changes made on either machine that are sync'd should be visible on both.

Is there are underlying issue with cloud sync? 
OR
Is there a way to clear local data/cache (maybe) on my desktop that could force down the changes from the cloud??
I found these directories:
C:\Users\<username>\AppData\Roaming\Postman\Cache
C:\Users\<username>\AppData\Roaming\Postman\GPUCache
Clearing the data files in these directories didn't help either.

**Comment by sdnts** [comment]
@serkand Sync changes are usually propagated very quickly. Are *both* clients in the state of `In Sync`? Also, can you see your changes over at https://app.getpostman.com/dashboard/collections/private?expand=1?

In either case, can you check DevTools of both clients to see if you find any errors there?

**Comment by serkand** [comment]
Yes, both clients are in a state of `In Sync`

No it doesn't appear. My collection is a Team collection, not sure if is that why ?

When I do a GET https://api.getpostman.com/collections/ _**< mycollectionguid >**_ on either machine, I don't see my changes. They only appear on my Laptop and this is confirmed when I do and export from there.

On both machines, DevTools -> Console shows:

 ================================================================
     o
   (/) P O S T M A N
   ^

   Go to View -> Show Postman Console to check your script logs. 

================================================================
Since not found...resetting to 0
🌏 sync service connectivity initiated
socket replaying queued commands
🌏 connected to sync service.
🐶 watchdog checking connection health

**Comment by SamvelRaja** [comment]
@serkand Can you provide us the detail on what kind of changes you made in the collection exactly. 
Also, https://api.getpostman.com/collections/ < mycollectionguid > has the updated information in it?
if so, kindly check the `pm.user.id` in both machines are same.

**Comment by serkand** [comment]
I just tried a change to a request in a private collection from my laptop and it was sync'd correctly on the desktop.

I then made a small change in the request that was causing the problem (team collection) on the laptop and it sync'd correctly the desktop 

I suppose the change on the laptop forced the sync?

In any case, its all working now, so we can close this.

**Comment by serkand** [comment]
@SamvelRaja just a side note, how do I check the pm.user.id ?

**Comment by SamvelRaja** [comment]
@serkand  you need to check in the devetools. 
View -> Show devtools 
There you need to check it.
