### ISSUE TITLE
In Postman app - Test fails if the string data is in CSV file while same test passed by newman

### ISSUE THREAD

**Issue by shubhamj-cuelogic** [a85/POSTMan-Chrome-Extension#3201]
I am facing a issue where my value is present in CSV. Now when I am running my test from collection runner then my testcase is showing failed. If I am using .trim() function then same testcase passed from collection Runner.

This issue is not present in newman. If I am running the same collection with newman then my testcase is passing without any trim function. 

Additionally I have observed that sometime if I am extracting data from CSV and if it is a integer then I need to typecast it. It will be fine if that happen in every case but it happens with few function like "responseCode.code" while working fine without typecast if I am assert any value. Pardon me if I am missing something in this case.

Value which I am taking from CSV is -

Key - ClientName3
value - Client Scenario 1

## App Details:

```
Postman for Windows
Window 10 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:
 2. Expected behaviour:
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 4. Screenshots (if applicable)

**Comment by sdnts** [comment]
Hi @shubhamj-cuelogic, can you attach the test script you're using so I can see where the `.trim` function is being used? Can you also tell me what the test is doing?

**Comment by shubhamj-cuelogic** [comment]
@madebysid - I have added the portion where I am getting error. Please Let me know if you need anything else from my side.

Testcase Pass -

tests["assert array Active array client 2 name values "+jsonData.Data.Active[1].ClientName] = jsonData.Data.Active[1].ClientName === "Client Scenario 1";

Testcase Fails -

tests["assert array Active array client 2 name values by csv ="+jsonData.Data.Active[1].ClientName] = jsonData.Data.Active[1].ClientName === data.ClientName3

Testcase Pass -

tests["assert array Active array client 2 name values by csv ="+jsonData.Data.Active[1].ClientName] = jsonData.Data.Active[1].ClientName === data.ClientName3.trim();

Value which I am taking from CSV is -

Key - ClientName3
value - Client Scenario 1

**Comment by shubhamj-cuelogic** [comment]
Hey @madebysid .. Any update on same?

**Comment by shubhamj-cuelogic** [comment]
I have uploaded my file on below link :
https://ufile.io/v62tw

The file will be deleted in 30 days so please download as soon as possible
@madebysid

**Comment by sdnts** [comment]
Hi @shubhamj-cuelogic, I see there's an extra character (`\r`) at the end of your file. If you preview the file from the Runner, you'll see it too.
If you open the CSV and remove the extra line from the end (`\r` translates to a new line ), everything should work. When you do an explicit `.trim()`, this will remove the `/r`, which is why it works.

Can you try this and let me know?
