### ISSUE TITLE
Request tabs disappear after Postman restart in the Linux version

### ISSUE THREAD

**Issue by bpaczkowski** [a85/POSTMan-Chrome-Extension#3202]
## App Details:

```
Postman for Linux
Version 5.0.0
linux 4.11.6-1-ARCH / x64
```

## Issue Report:
Restarting the application removes all the opened tabs. This is not the case in the Chrome Extension version, where after closing Postman and opening it again it kept all previously opened tabs.

**Comment by kamalaknn** [comment]
Hey @bpaczkowski 

Thanks for reporting this. We'll look into this.

Are you signed in or signed out when you close the app?

**Comment by bpaczkowski** [comment]
I'm signed out on both the Chrome and standalone versions.

**Comment by SamvelRaja** [comment]
Can you check the behaviour in our latest 5.2 version of the app and confirm that the issue still persist?
closing this now, feel free to reopen it if you face it again.

**Comment by bpaczkowski** [comment]
Yes, it does persist in 5.2 as well. I can't reopen the issue if someone else closed it.

**Comment by JordanTribley** [comment]
I would like to report the same in version 5.3.2 of the Linux native application (Ubuntu). BUT it only happens when clicking the "X" on the application title bar to close the program. Using "File->Quit", "Ctrl+Q", or even when the application closes unexpectedly, the tab state is preserved when the application is re-opened.

**Comment by Goltergaul** [comment]
i can confirm the same behavior that @JordanTribley reported for version 5.5.0 on linux ubuntu

**Comment by prashantagarwal** [comment]
@Goltergaul This is the expected behaviour here. Closing specifically on X means you want to discard these tabs.

**Comment by Goltergaul** [comment]
@bpaczkowski that makes no sense from my point of view. Why should it be different from ctrl+Q and File->quit? Moreover this does not happen on windows, and worked properly in older versions of postman (at least the chrome version)

And it doesn't even warn you that your work will be lost.

**Comment by kamalaknn** [comment]
@Goltergaul In the latest version of the Postman desktop app(6.0.10 now) we preserve all the open tabs in your last window. Quitting the app through `Ctrl + Q` or clicking on the `X` button should save the state your app and restore it back when you open it again. Can you update your app to the latest version and give this a try?

**Comment by Goltergaul** [comment]
@kamalaknn yes I can confirm that this now works in 6.0.10. Many thanks! :)

**Comment by kamalaknn** [comment]
@Goltergaul Glad to know you found it useful 😄
