### ISSUE TITLE
decode gzipped response

### ISSUE THREAD

**Issue by drkhannah** [a85/POSTMan-Chrome-Extension#3203]
I'm making a post to an api that returns a gzipped response

the response is json but is a byte array

how do i decode this byte array in postman so i can see the unzipped json response?

here is a snapshot of the response

{
  "d": [
    31,
    139,
    8,
    0,
    0,
    9,
    110,
    136,
    0,
    255,
    236,
    125,
    11,
    143,
    219,
...

**Comment by kamalaknn** [comment]
Hey @drkhannah 

Could you share a sample Url where you are seeing this?
