### ISSUE TITLE
Postman uses Chrome Icon in Windows 10 Start Tiles

### ISSUE THREAD

**Issue by Armesh** [a85/POSTMan-Chrome-Extension#3204]
## App Details:
Postman for Chrome
Version 5.0.1
win / x86-64
Chrome 58.0.3029.110
```
Postman Chrome, Windows 10

```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:
 Always Been there
 4. Screenshots (if applicable)
![issue](https://user-images.githubusercontent.com/4216475/27513449-a0ebb2fe-5998-11e7-8edd-8cd124a3bfc5.jpg)

When I pin my Postman to my Start button tiles, it appears as Chrome Icon instead of Postman Icon. It makes things very confusing.

**Comment by a85** [comment]
The Chrome app platform is unfortunately deprecated and we won't see any updates on those APIs. I recommend shifting to native apps.
