### ISSUE TITLE
[Features] Workspaces

### ISSUE THREAD

**Issue by a85** [a85/POSTMan-Chrome-Extension#3205]
Creating this issue to put together all issues that are about associating collections with environments.

https://github.com/postmanlabs/postman-app-support/issues/213
https://github.com/postmanlabs/postman-app-support/issues/1513
https://github.com/postmanlabs/postman-app-support/issues/1453

**Comment by NicholasParian** [comment]
@a85 This would be an awesome feature.  Do you have an update on this?

For us, each customer has their own configurable API setting.  And thus, our list of collections and environments have become unmanageable.   If possible we, would like to have each customer have their own workspace so we can better organize their specific documentation, requests, and environment variables.  Also, a nice to have would be able to run the runner on each defined workspace/collection/environment for regression testing

That way, we can create public documentation for each customer and maintain collections for us to regression test with and actually be able to organize by customer

_Workspace: Customer A_
            --> **Collections**
                 ----> Documentation
                          ------> Example A
                          ------> Example A
                          ------> Example A
                 ----> Resource 1 - Requests
                           ------> Request A (sets environment variables for Customer A->Resource 2->Request A)
                           ------> Request B  (sets environment variables for Customer A -> Resource 2->Request B)
                 ----> Resource 2 - Requests
                           ------> Request A (sets environment variables for Customer A->Resource 3->Request A)
                           ------> Request B (sets environment variables for Customer A -> Resource 3->Request B)
                 ----> Resource 3 - Requests
                           ------> Request A
                           ------> Request B
                 ----> Regression Test
                           ------> Request A
                           ------> Request B
                           ------> Request N
            --> **Environments**
                 ----> Documentation
                          ------> Documentation Environment Variables 
                 ----> Test
                           ------> Test Environment Variables 
                 ----> Staging 
                           ------> Staging Environment Variables 
                 ----> Production
                         ------>  Production Environment Variables

**Comment by sdnts** [comment]
@NicholasParian We've been planning this!
You can follow our (product roadmap](https://trello.com/b/4N7PnHAz/postman-roadmap-for-developers) for consistent updates :)

**Comment by AlbertoP64** [comment]
@a85 @madebysid, no flames but, to explicitly advertise on each closed merged issue, about the Trello moving affair, would have been a great idea IMHO 😉 
I've done it on #213

**Comment by 4F2E4A2E** [comment]
How to export a collection in order to use with newman? It seams not possible to export any collection at the moment, only via settings -> export (dump / backup) => not the same as collection export
![image](https://user-images.githubusercontent.com/64590/32365154-08d51166-c079-11e7-82f0-ba0eaf0e5180.png)

**Comment by cauvery-guda-eb** [comment]
Is there any rough ETA for this feature. Looking forward to it. 

Thank you.

**Comment by loraxipam** [comment]
Great work on this, guys! This is fantastic.

**Comment by a85** [comment]
Workspaces are available now. More info on our docs: https://www.getpostman.com/docs/postman/workspaces/intro_to_workspaces

**Comment by Ciki** [comment]
link is broken, this one works https://www.getpostman.com/docs/v6/postman/workspaces/intro_to_workspaces

**Comment by Ciki** [comment]
note that there are also broken links within the post (without the `v6` part)

**Comment by AlbertoP64** [comment]
⁣Many thanks Postman team for progressing and finally processing this issue, I'll be back when I test the new feature to give a feedback, eventually!! :-) love your work guys :hugs:

Inviato da TypeApp ​

Il giorno 11:29 01/mar/2018, alle ore 11:29, Ciki <notifications@github.com> ha scritto:

**Comment by miraclebg** [comment]
How about setting a default environment in the public documentation?

**Comment by godfrzero** [comment]
@miraclebg You can select an environment while publishing a collection. This environment will then be available publicly, and it'll be selected by default when the public documentation is viewed.
