### ISSUE TITLE
FATAL ERROR: Postman will crash if there is to much tabs

### ISSUE THREAD

**Issue by urosjarc** [a85/POSTMan-Chrome-Extension#3207]
Postman crash if I wanted to open tab if there is to much tabs already opened. Can some1 confirm my statement if its true.

**Comment by kamalaknn** [comment]
Hey @urosjarc 

We are working on some performance improvements for multiple tabs open.

Are you using the Postman Chrome app or the Native apps? (Check [How can I tell if I’m on the Postman Chrome app or Postman native app?](http://blog.getpostman.com/2017/03/14/going-native/))

Thanks

**Comment by urosjarc** [comment]
I'm using chrome app on linux.

**Comment by prashantagarwal** [comment]
Can you update to the latest native postman app and verify if you are still seeing this issue.

**Comment by urosjarc** [comment]
Postman app is still crashing...
