### ISSUE TITLE
After Canceling 'Close All Tabs' Later Single Tab Closing Attempts To Close All Tabs

### ISSUE THREAD

**Issue by NekoKikoushi** [a85/POSTMan-Chrome-Extension#3209]
## Preface
I did try to search for this issue first so I'm relatively positive this is actually a new bug.
I did not try on anything other than Windows but it seems likely this may propagate to all platforms.

## App Details:
```
Postman for Windows
Version 5.0.0
win32 10.0.15063 / x64
```

## Issue Report:
 1. Encountered recently, but this was the first time I've ever canceled a "close all tabs" action
 2. Expected behaviour: after I cancel close all tabs, and then try to close a single tab, only that single tab would be closed by postman (the underlying 'is_close_all_tabs_action' boolean-or whatever it is named-need be flipped back to false when cancel is clicked, or at least that's what it looks like is not happening).
 3. Console logs N/A
 4. Screenshots N/A

## Steps To Reproduce
1. Open a few requests and make changes so the has-changes icon appears on the tab.
2. Right click a tab and choose "close all"
3. Close a tab or two but before they are all closed click the cancel option on one of the edited requests
4. Now try to close a single tab.
5. Observe that Postman still attempts to close all tabs.

**Comment by sdnts** [comment]
Hi @MrJ0rdan, thanks for reporting this. I was able to reproduce this, and we'll include a fix for this with the next release.

**Comment by sdnts** [comment]
Hey @MrJ0rdan, are you still seeing this on 5.1.2?

**Comment by NekoKikoushi** [comment]
Looks fixed to me! Thank you kindly!

**Comment by kamalaknn** [comment]
Great! I am closing this issue then.
