### ISSUE TITLE
[Bug] - Since Update 4.11.0 the user is unable to increment environment variables

### ISSUE THREAD

**Issue by Faz540** [a85/POSTMan-Chrome-Extension#3210]
#3153 and #3150 
Due to the above issues I'm using version 4.10.7 (Windows App)
However, I noticed on any version after 4.10.7, the below test will not function correctly.

```
tests["Status code is 200"] = responseCode.code === 200;

// Test Results:
var test_results = Object.values(tests);
for(var i = 0; i < test_results.length; i++) {
    if(test_results[i] === true) { environment.passed ++; }
    else { environment.failed ++; }
}
```

**In short, what should happen is:**

- It runs the Status Code === 200 test.

- It then loops through the 'tests' array and if any of them are true, increment the 'passed' environment variable (which is initialized in the pre-request) by 1 and do the same if tests fail for the 'failed' environment variable.

- I use this to send me a message on slack upon test completion to say "{{failed}} tests have failed"

This works as expected on version 4.10.7 but updating to any of the later versions causes the 'passed' and 'failed'environment variables to stay at zero.

**Comment by sdnts** [comment]
Hi @Faz540, directly updating the environment using `environment.failed++` isn't recommended. Can you do this using `postman.setEnvironmentVariable` & `postman.setEnvironmentVariable` too see if that works as expected? I'm closing this, but please reopen if you can reproduce this with these getters and setters as well :)

**Comment by Faz540** [comment]
Yep, I've re-written the code to the below:

```
// Test Results:
var test_results = Object.values(tests);
for(var i = 0; i < test_results.length; i++) {
    if(test_results[i] === true) { 
        passed = parseInt(postman.getEnvironmentVariable("passed"));
        postman.setEnvironmentVariable("passed", passed + 1); 
    }
    else {
        failed = parseInt(postman.getEnvironmentVariable("failed"));
        postman.setEnvironmentVariable("failed", failed + 1);
    }
}
```

**Comment by sdnts** [comment]
Yep, this should work. Additionally, might I also suggest you add a fallback to zero when you initialize the pass counter:
`passed = parseInt(postman.getEnvironmentVariable("passed")); || 0` to make sure it works even when these variables are not defined at all.

**Comment by Faz540** [comment]
Is that still required even if I declare them in the pre-request script?
I set these values to zero at the start of the test run

```
postman.setEnvironmentVariable("passed", 0);
postman.setEnvironmentVariable("failed", 0);
```

**Comment by sdnts** [comment]
Ah no, then the defaults are redundant
