### ISSUE TITLE
PLS help to add a function using to hide/show 【Description】in body columns 

### ISSUE THREAD

**Issue by xtet2008** [a85/POSTMan-Chrome-Extension#3211]
## App Details:

```
Postman for Mac
Version 4.11.0
OS X 16.4.0 / x64
```

## Issue Report:
I cannot input/change the key name in the request body frame when I change the "Two-pane view" on .  Cause the window which show "Text/File" will be prompt in the top when the mouse move on column "Key". So that I cannot change the key column unless I cancel the "Two-pane view" function.

So could we add a option using to show/hidden the column in SETTINGS -> General frame named "Show key description in the body"

I don't know how to catch the screen as attach upload here. if need it pls let's me know in the first time, my email address is  xtet2008@126.com.  Thank guys.

**Comment by sdnts** [comment]
Hey @xtet2008, if you click on the three dots next to the `Bulk Edit` button and choose not to show the Description column. This will stick for the current tab.
We're looking into providing settings for hiding / showing the column on a global basis. We'll keep you updated on this thread.

**Comment by xtet2008** [comment]
Hey Sir.

Thanks for your reply and care. I already know how to hide the Description as the same way as you sent to me.
Cause isn't save my action that means I need to hide the column first every time If I want to edit/add the key name in body request frame. 
So, I think if it can be save user's habit that you  providing a settings for hiding/showing the column on a global basic, then it will be more perfect.

B.regards & TKS again.

**Comment by sdnts** [comment]
Indeed, we'll include a way to hide this in a more global fashion in the next release :)

**Comment by xtet2008** [comment]
I'm looking forward to that very much.  I'm a web services developer need to use it debug the API every times.

**Comment by prashantagarwal** [comment]
@xtet2008 This is fixed in latest Postman version. If you hide a column, it will not show up by default on subsequent tabs. I am closing this issue. If you still face any problem, feel free to reopen the issue.

**Comment by xtet2008** [comment]
Thanks Sir.
