### ISSUE TITLE
Feature Request: OAuth2 Helper should allow user to specify whether to include ID & Secret in Basic Auth or in request body

### ISSUE THREAD

**Issue by rogerdc** [a85/POSTMan-Chrome-Extension#3214]
## App Details:

```
Postman for Windows
Version 5.0.0
win32 10.0.14393 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there: Unsure, have never tried this before.
 2. Expected behaviour: Allow user to specify whether to include client_id and client_secret in either Basic Auth header or in request body
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
common.js:157233 POST https://login.microsoftonline.com/[redacted]/oauth2/token 401 (Unauthorized)send @ common.js:157233ajax @ common.js:156714startAuthorization @ xml.js:22triggerEvents @ common.js:144946triggerApi @ common.js:144933eventsApi @ common.js:144732Events.trigger @ common.js:144923processOAuth2RequestToken @ xml.js:22handleRequestToken @ xml.js:22handleClick @ common.js:140193invokeGuardedCallback @ common.js:5376executeDispatch @ common.js:5205executeDispatchesInOrder @ common.js:5228executeDispatchesAndRelease @ common.js:4622executeDispatchesAndReleaseTopLevel @ common.js:4633forEachAccumulated @ common.js:5517processEventQueue @ common.js:4836runEventQueueInBatch @ common.js:11711handleTopLevel @ common.js:11722handleTopLevelImpl @ common.js:17109perform @ common.js:7433batchedUpdates @ common.js:17027batchedUpdates @ common.js:6595dispatchEvent @ common.js:17184
 4. Screenshots (if applicable)
![image](https://user-images.githubusercontent.com/4684857/27599462-73e85068-5b2e-11e7-8915-c13102043ef7.png)
![image](https://user-images.githubusercontent.com/4684857/27599538-adf798ea-5b2e-11e7-9a05-c0a1ab8014cc.png)
![image](https://user-images.githubusercontent.com/4684857/27599671-22537ae2-5b2f-11e7-9920-003d52c4df86.png)
![image](https://user-images.githubusercontent.com/4684857/27599701-3768f7e0-5b2f-11e7-9144-3c146bfdeeba.png)

Attempt to obtain an OAuth2 token from a provider that apparently does not support putting the credentials in the Authorization header.

It would be nice if the user could specify whether to put the credentials in the Authorization header or in the body.

**Comment by prashantagarwal** [comment]
@rogerdc Thanks for this suggestion. We are working on improving Auth workflow in Postman. We will consider this suggestion while improving it.

**Comment by ScrappyXII** [comment]
I have seen the same issue where some servers will throw an error if client_id is included in the request body. While the spec does say client_id MAY be included, some servers are more strict about this than others.

**Comment by vikiCoder** [comment]
I am not sure when it was added, but the current version of Postman native app (v7.3.4) has an option to specify whether to include client_id and client_secret in either Basic Auth header or in request body. Below is a screenshot of the same:

<img width="619" alt="Screenshot 2019-07-29 at 3 16 19 PM" src="https://user-images.githubusercontent.com/16588032/62039120-af33ac00-b214-11e9-8b38-408e1209a995.png">
