### ISSUE TITLE
Lost Collections and Environments after upgrade to 5.0.0

### ISSUE THREAD

**Issue by misha-kotov** [a85/POSTMan-Chrome-Extension#3215]
## App Details:

```
Postman for Mac
Version 5.0.0
OS X 15.6.0 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there: 
Encountered after upgrading to 5.0.0 (I do not have an account). 
 2. Expected behaviour:
After upgrade, my collections and environments are preserved. 
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 4. Screenshots (if applicable)

1. Create some collections and environments on 4.x.x without signing in. 
2. Upgrade to 5.0.0

**Comment by prashantagarwal** [comment]
@misha-kotov Thanks for reporting this. We will investigate and try to reproduce this issue on our end.

**Comment by misha-kotov** [comment]
@prashantagarwal Is there a place I can look for the lost collections locally? Where are they stored on a Mac?

**Comment by prashantagarwal** [comment]
@misha-kotov Was this issue resolved for you. You can drop a mail to help@getpostman.com if you are still facing any issue.
