### ISSUE TITLE
Enhancement: Slack integration: Allow properties of existing integrations to be viewed & edited

### ISSUE THREAD

**Issue by niranjv** [a85/POSTMan-Chrome-Extension#3219]
In the Slack integration page (e.g., https://<mysubdomain>.postman.co/dashboard/integrations/slack/list):

* Allow properties of existing integration to be viewed
* Allow properties of existing integration to be edited. Currently, must delete and re-create integration with desired properties.

**Comment by ankitjaggi** [comment]
This is something we are planning to release soon.

**Comment by shashankawasthi88** [comment]
@niranjv This functionality is now available in the latest release.

As a creator of the integration, you should now be able to: -

- View and edit the info of configured integration (slack/ any other).

To view and edit the configured integrations: -

- Within your workspace, from the web dashboard go to Browse > Integrations - To list all the Integrations of the workspace

- Click on the Integration you want to view/ edit (say slack). Go to the **Added Integrations** tab.

- Click on the edit option against the Integration to edit/ view the information related to integration configuration.

You can also view the **Integration run logs** by clicking on the Integration name on the **Added Integrations** listing page.

Please see below the screenshots for the same.
<img width="1440" alt="Screenshot 2020-09-29 at 2 36 08 PM" src="https://user-images.githubusercontent.com/71059054/94539114-73560580-0262-11eb-87c9-3b8bb9fbe7f4.png">
<img width="1440" alt="Screenshot 2020-09-29 at 2 39 39 PM" src="https://user-images.githubusercontent.com/71059054/94539149-7c46d700-0262-11eb-9b65-4372b8a350ea.png">
<img width="1440" alt="Screenshot 2020-09-29 at 2 42 52 PM" src="https://user-images.githubusercontent.com/71059054/94539173-81a42180-0262-11eb-92ab-b28efcfbb867.png">
