### ISSUE TITLE
Zoom In using shortcut key is not working

### ISSUE THREAD

**Issue by mrshyam** [a85/POSTMan-Chrome-Extension#3221]
hello sir
*Zoom In* using shortcut key is not working...

**Comment by sdnts** [comment]
Hey @mrshyam I'm able to zoom in using `Cmd+` or `Ctrl+` on v5.0.1. Which version of the app are you on?
Are there specific steps I need to take to reproduce this?

**Comment by mrshyam** [comment]
Working with keyboard  Ctrl- and not working with numeric keyboard.

**Comment by clytemnestra** [comment]
Same issue here.

**Comment by mayurtikundi12** [comment]
same issue here as well
using ubuntu os

**Comment by larsm6** [comment]
I just encountered the same problem. It actually seems to be related to a wrong implementation of the "+"-key binding. I'm using a german keyboard and had to find the position of the "+" sign of an engl keyboard (ctrl + shift + 0). That did the magic ;)
