### ISSUE TITLE
Close a Postman window will close all other Postman Window on Desktop App

### ISSUE THREAD

**Issue by Vietntse02406** [a85/POSTMan-Chrome-Extension#3222]
**App Details:**
Postman for Windows
Version 5.0.0
win32 6.3.9600 / x64

**Issue Report:**
 1. Not sure. I always used the Chrome app, just changed to Desktop app for about a month
 2. Hit "Close" on a Postman window only close that window, not all Postman windows
 3. None
 4. None

**Step to reproduce:**
1. Open Postman Desktop app
2. Open a new Postman Window (Ctrl N)
3. Hit close on either window
4. Both window close

Same with 3 or many windows.
Only happen with Desktop app, the Chrome App works fine

**Comment by prashantagarwal** [comment]
@Vietntse02406 Thanks for reporting this. We were able to reproduce this only on Windows. We will look into this and release a fix for the same.

**Comment by prashantagarwal** [comment]
@Vietntse02406 This is fixed in latest version of Postman. Thanks
