### ISSUE TITLE
Mock-Api: Adding cache-control to headers don't work

### ISSUE THREAD

**Issue by Muddz** [a85/POSTMan-Chrome-Extension#3223]
## App Details:
```
Postman for Windows
Postman v5.0.0
Windows 10
```

## Issue Report:

I'm trying to add a `Cache-Control: max-age: 600` to my header's `GET` request in my mock api like in this [screenshot](http://i.imgur.com/oO2bFAS.png)

but I never get a response header that actually have any `cache-control` in the header.

This is the header I get returned after I press *SEND* in Postman

> Access-Control-Allow-Credentials →
> Access-Control-Allow-Headers →
> Access-Control-Allow-Methods →
> Access-Control-Allow-Origin →
> Access-Control-Expose-Headers →
> Connection →keep-alive
> Content-Encoding →gzip
> Content-Type →text/html; charset=utf-8
> Date →Wed, 28 Jun 2017 13:31:28 GMT
> ETag →W/"c65-KUKZJmecuSjDxceIjksyQg"
> Server →nginx/1.10.2
> Vary →Accept-Encoding
> X-RateLimit-Limit →60
> X-RateLimit-Remaining →59
> X-RateLimit-Reset →1498656748
> transfer-encoding →chunked

**Comment by prashantagarwal** [comment]
@Muddz Thanks for reporting this. We are already working on a fix for this which will be out in next couple of weeks. I will keep you updated about it.

**Comment by ghost** [comment]
+1

**Comment by prashantagarwal** [comment]
@Muddz Can you check if this is still happening for you. If so feel free to reopen this issue.
