### ISSUE TITLE
App crashing freguently

### ISSUE THREAD

**Issue by shibinaec** [a85/POSTMan-Chrome-Extension#3226]
My app
Postman for Chrome
Version 5.0.1
win / x86-32
Chrome 58.0.3029.110
Crashes frequently.. i have cleared history requests still  no change .

**Comment by sdnts** [comment]
@shibinaec We are continuously working to make sure the app is stable. We recently release 5.0.2 which has some performance improvements. Can you try updating and check if the performance is better?

**Comment by sdnts** [comment]
Closing this in favour of #3105

**Comment by shibinaec** [comment]
Thank you for your support sir,
I have removed the extension and downloaded the postman  app,now I'm able
to work with it, no problem at all.
Thank you so much for your support.
