### ISSUE TITLE
Postman native app in Windows - Certificate issue

### ISSUE THREAD

**Issue by skumarcse** [a85/POSTMan-Chrome-Extension#3228]
## App Details:
Postman helps you develop APIs faster
Postman for Windows
Version 5.0.2
win32 6.1.7601 / x64

## Issue Report:
Could not get any response
There was an error connecting to https://api.examples.com/account/BalanceInquiry.
Why this might have happened:
The server couldn't send a response:
Ensure that the backend is working properly
Self-signed SSL certificates are being blocked:
Fix this by turning off 'SSL certificate verification' in Settings > General
Client certificates are required for this server:
Fix this by adding client certificates in Settings > Certificates
Request timeout:
Change request timeout in Settings > General

**Steps to reproduce the problem**
 1. downloaded postman native app for windows x64.
 2. Settings --> Certificates tab --> Add Certificate
 3. Added .CRT, .KEY and PassPharse
 4. Accessed the API, got above error.

Same Certificate tried with Mac Postman Native App, it is perfectly working. Just this certificate problem with Postman Windows Native App.

**Comment by numaanashraf** [comment]
@skumarcse Thanks for reporting this. Could you open the Postman Console (View > Show Postman Console) on the windows app, retry the request and send us a screenshot of the logs in the console?

**Comment by skumarcse** [comment]
Here is the console log. Note: this is accessed through corporate network.
POST
https://api.examples.com/account/BalanceInquiry.
07:45:46.145
Error: tunneling socket could not be established, statusCode=407
Client Certificate:
keyPath:"C:\Postman\postman-cert\grp-client.prod.local.key"
pemPath:"C:\Postman\postman-cert\grp-client.prod.local.crt"
Proxy:
proxy:"http://10.xxx.xx.xx:8080"
tunnel:true
Request Headers:
cache-control:"no-cache"
Content-Type:"application/json"

**Comment by kamalaknn** [comment]
Hey @skumarcse,

From the console logs, it looks like the request could not go through the proxy. Could you make sure your proxy settings are configured the right way on your windows machine?

**Comment by abhijitkane** [comment]
@skumarcse Fixed in the latest version. Feel free to re-open if you're still seeing this.

**Comment by chisumo2016** [comment]
![image](https://user-images.githubusercontent.com/9254656/36280018-e87abc8a-1290-11e8-97b6-021237aae72f.png)

**Comment by GodelMachine** [comment]
@kamalaknn Hi Kamal, I am facing the same problem as @chisumo2016 above. When the SSL verification is turned ON, I get @chisumo2016 screen. But when the SSL verification is disabled, I get this - 

![postman github](https://user-images.githubusercontent.com/17872895/40601431-cd4beede-6272-11e8-81bc-daa1f648e539.PNG)

I am doing this on Windows.
Kindly advise. Thanks.
