### ISSUE TITLE
Raml import not working in postman 5.0.2

### ISSUE THREAD

**Issue by suttermichael** [a85/POSTMan-Chrome-Extension#3233]
After the update of postman to the 5.x release the import of our Raml files aren't working any more. The import was working in the 4.* releases. In case I import a file manually I get an error message. Please see attached screenshot. 
We're using raml 0.8

## App Details:
Postman for Chrome
Version 5.0.1
win / x86-64
Chrome 58.0.3029.110
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:
Recently after the update to 5.*
 2. Expected behaviour:
The import should be successful 
![ramlimport](https://user-images.githubusercontent.com/22204033/27822828-543f4d10-60a7-11e7-867f-a261a38d35fe.png)

 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 4. Screenshots (if applicable)

<!--
Steps to reproduce the problem
-->

**Comment by suttermichael** [comment]
![ramlimport](https://user-images.githubusercontent.com/22204033/27822904-9298895a-60a7-11e7-9550-464ecdced28e.png)

**Comment by sdnts** [comment]
Hi @suttermichael, do you have external references in your RAML spec? If so, those aren't supported yet. I'll make sure we get the error text more descriptive.

**Comment by suttermichael** [comment]
Hi @madebysid do you mean files which include via 
!include
in our RAML file? 
We have such includes and they had been working in postman 4.x

**Comment by abhijitkane** [comment]
@suttermichael Apologies for the delay on this. Is this something you're still seeing in Postman 7.2+? If yes, attaching a link to a RAML doc that's failing will help debug this.

**Comment by suttermichael** [comment]
@abhijitkane sorry, not using RAML anymore. Therefore I can't retest...

**Comment by DannyDainton** [comment]
Hey @abhijitkane,

I took a look at this some more to see if I could get more information about the issue.

Using this example in the section from the [raml-org](https://github.com/raml-org/raml-spec) GH repo:

https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md/#the-root-of-the-document

```raml
#%RAML 1.0
title: GitHub API
version: v3
baseUri: https://api.github.com
mediaType:  application/json
securitySchemes:
  oauth_2_0: !include securitySchemes/oauth_2_0.raml
types:
  Gist:  !include types/gist.raml
  Gists: !include types/gists.raml
resourceTypes:
  collection: !include types/collection.raml
traits:
securedBy: [ oauth_2_0 ]
/search:
  /code:
    type: collection
    get:
```

Added this as a `Raw Text Import` on version 7.2.2 - It failed to import and showed the followed message:

<img width="320" alt="Screenshot 2019-07-01 at 13 59 37" src="https://user-images.githubusercontent.com/17089546/60438489-b01ef100-9c08-11e9-9203-998d5fa5a9ff.png">

From the learning centre, it states that we do support version 1.0 - https://learning.getpostman.com/docs/postman/collections/data_formats/#importing-raml

The message text on the `Import` feature doesn't specify which version we support but we do show `RAML 0.8`on the schema dropdown, in the new `APIs` feature. 

I took this from the `0.8` RAML documentation and went through the steps again. 

https://github.com/raml-org/raml-spec/blob/master/versions/raml-08/raml-08.md#named-parameters-with-multiple-types

```raml
#%RAML 0.8
title: Amazon simple storage API
version: 1
baseUri: https://{destinationBucket}.s3.amazonaws.com
/:
  post:
    description: The POST operation adds an object to a specified bucket using HTML forms.
    body:
      application/x-www-form-urlencoded:
        formParameters:
          AWSAccessKeyId:
            description: The AWS Access Key ID of the owner of the bucket who grants an Anonymous user access for a request that satisfies the set of constraints in the Policy.
            type: string
          acl:
            description: Specifies an Amazon S3 access control list. If an invalid access control list is specified, an error is generated.
            type: string
          file:
            - type: string
              description: Text content. The text content must be the last field in the form.
            - type: file
              description: File to upload. The file must be the last field in the form.
```

This did import this into the application and create a Collection and Environment file but the information in the different sections seem to be missing.

<img width="1676" alt="Screenshot 2019-07-01 at 14 11 51" src="https://user-images.githubusercontent.com/17089546/60439178-3e47a700-9c0a-11e9-83a1-7cc3d85b325e.png">

This was tested against the MacOS version of the app on version 7.2.2.

**Comment by abhijitkane** [comment]
Closing this issue for now. RAML 1.0 support is being worked on, and we have no reproducible issues on RAML 0.8
