### ISSUE TITLE
[Feature] Search bar for global/environment variables

### ISSUE THREAD

**Issue by msignataur** [a85/POSTMan-Chrome-Extension#3235]
Would be nice if you can add a search bar in preview list of environment/global variables.
I have a lot of variables and it’s very embarrassing to find the value that I want to use.

**Comment by sdnts** [comment]
@msignataur Thanks for this feature request!
You might also be interested in #2016

**Comment by anudeepmedicharla** [comment]
Tracking this issue here: https://github.com/postmanlabs/postman-app-support/issues/3561
