### ISSUE TITLE
Multiple custom domains for docs publish

### ISSUE THREAD

**Issue by thix1606** [a85/POSTMan-Chrome-Extension#3236]
Please, add multiple custom domains for docs.
Nowadays I can only publish docs using a single domain.
My team has multiple different products. It'd be great to share each on a specific domain.

Thanks!

**Comment by prashantagarwal** [comment]
@thix1606 Thanks for reaching out to us. Can you drop a mail at help@getposman.com . Our support team will help you out with this.

**Comment by iMacTia** [comment]
@prashantagarwal may I ask you what does that mean exactly?
Is it possible to have multiple custom domains? Is it something that can be achieved only through the support?

**Comment by prashantagarwal** [comment]
@iMacTia  Yes you can set multiple custom domains (max 5) from your postman dashboard.

**Comment by iMacTia** [comment]
That's cool! Thanks @prashantagarwal, last time I used Postman Cloud (I think before the "PRO" rebranding) you could have only 1. Nice to know you can have up to 5 now.
