### ISSUE TITLE
Comment few calls from running in collection runner

### ISSUE THREAD

**Issue by decode007** [a85/POSTMan-Chrome-Extension#3237]
I my collection, one of my request is getting failed because complete data is not fetched.
Although that call individually is running fine.
Was that because of some timeout. In that case can we increase the default timeout?

Also, for the time being, can i skip that call from running in collection.
Like commenting that specific call

**Comment by prashantagarwal** [comment]
@decode007 Thanks for the suggestion. We are already tracking a similar issue #2392 . For now, you can use `postman.setNextRequest` to skip requests in the runner. [Docs](https://www.getpostman.com/docs/workflows)
