### ISSUE TITLE
Malformed headers show server as being down, rather than bad request

### ISSUE THREAD

**Issue by wmonk** [a85/POSTMan-Chrome-Extension#3238]
## App Details:

```
Postman for Mac
Version 5.0.2
OS X 16.4.0 / x64
```

## Issue Report:
1. Did you encounter this recently, or has this bug always been there:
Encountered today, latest version - 5.0.2
2. Expected behaviour:
Instead of seeing:
![image](https://user-images.githubusercontent.com/175278/27857553-0c92b0c4-616a-11e7-9878-cf0a1163d283.png)
I should see a warning that the request was malformed.

3. Console logs:
This was logged to the console - which isn't particularly useful if you don't know where to look. Also doesn't match up with the error shown in the main screen. You can see a `" "` at the end of the string, which is actually a newline character.
<img width="952" alt="screen shot 2017-07-05 at 10 10 16" src="https://user-images.githubusercontent.com/175278/27857639-637eeede-616a-11e7-9684-34aa309118fc.png">

## Steps to reproduce the problem
1. Open "Manage Environments"
2. Use key value edit
3. Paste into the value field, a string with a newline character (or by the look of it any invalid character)
4. Use that variable in a request header
5. See "Server error" screen *not* a warning about a malformed request

**Comment by prashantagarwal** [comment]
@wmonk Thanks for reporting this. We will investigate this and try to reproduce it on our end. We will keep you updated.

**Comment by prashantagarwal** [comment]
Related to #4485
