### ISSUE TITLE
Support OAuth2 Authentication with parameters in body per RFC6749

### ISSUE THREAD

**Issue by solvingj** [a85/POSTMan-Chrome-Extension#3239]
## App Details:
```
Postman for Windows
Version 5.0.2
win32 10.0.15063 / x64
```

## Issue Report:
Here is the link to the relevant section of the RFC for OAuth2:
https://tools.ietf.org/html/rfc6749#section-2.3.1

Here is the relevant excerpt:

> The authorization server MUST support the HTTP Basic
>    authentication scheme for authenticating clients that were issued a
>    client password.
> 
>    For example (with extra line breaks for display purposes only):
> 
>      Authorization: Basic czZCaGRSa3F0Mzo3RmpmcDBaQnIxS3REUmJuZlZkbUl3
> 
>    Alternatively, the authorization server MAY support including the
>    client credentials in the request-body using the following
>    parameters:
> 
>    client_id
>          REQUIRED.  The client identifier issued to the client during
>          the registration process described by Section 2.2.
> 
>    client_secret
>          REQUIRED.  The client secret.  The client MAY omit the
>          parameter if the client secret is an empty string.

Since OAuth2 dialog was introduced in Postman, it has sent the parameters as header values.  There is no option to toggle to the alternative mechanism which is to send the parameters as part of the message body.  

## Background
I happen to believe that this section of the RFC is poorly worded, and therefor open to misinterpretation.  Any sentence using the keyword "MUST" in the context of a one-of-many requirement should include a reference to all possible options that satisfy the requirement in that sentence using commas or a colon followed by a bulleted list. In this case, the sentence featuring the keyword "MUST" defines one of the available options then terminates with a period, and is then followed by an example.  Only after the example is an alternative method defined in a subsequent sentence. This kind of discontinuity in RFC's is likely to lead to the interpretation that the first option is the only way to satisfy the "MUST" requirement. 

## Use Case
The Microsoft Azure's REST API authentication system has implemented the alternative mechanism, which requires the parameters in the body when requesting tokens.

Reference:  https://stackoverflow.com/questions/40641616/postman-client-credentials-flow-with-azure-ad-protected-ressource/40891500#40891500

Microsoft Azure AD is now a prominent identity provider.  All of Microsoft's cloud services depend on it, but many other cloud applications integrate with it as their IDP.   

## Conclusion
Both fully supporting the RFC and supporting a prominent cloud provider in Microsoft Azure seem to be compelling reasons to add the option requested.  Feedback and questions welcome.

**Comment by kunagpal** [comment]
@solvingJ Thanks for pointing this out, a clean fix would be to make the inbuilt OAuth2 helper configurable, so as to specify sending the auth parameters via headers or the request body (as is the case here).

**Comment by solvingj** [comment]
Yes that is exactly what I had in mind. A dropdown that defaults to headers would be the simplest experience.

**Comment by kunagpal** [comment]
@solvingj This is now supported in v5.3.0 of the app, do go ahead and check it out 😄

**Comment by kamalaknn** [comment]
We've added more fixes to the OAuth 2.0 flows in Postman `5.3.1`. That should fix a lot of rough edges. 

Please do update your apps and test it out. 

Note: The new updates are only available on our Native apps. [Download Link](https://www.getpostman.com/apps)

**Comment by yagurlova2** [comment]
> ## App Details:
> ```
> Postman for Windows
> Version 5.0.2
> win32 10.0.15063 / x64
> ```
> 
> ## Issue Report:
