### ISSUE TITLE
Run results doesn't expand the line as per the text in the tests

### ISSUE THREAD

**Issue by kharod** [a85/POSTMan-Chrome-Extension#3240]
When running tests from Postman Collection runner, in the Run Results  the text is overlapping with the text displayed in the next test and so on. This happens when I try to print the response body as part of the test, so it is more readable at first look to see whats wrong with it.

But Run Results where the tests are displayed, the text in the postman doesn’t expand with it and it ends up in this messy output which no one can understand. Have a look at the screen for reference.

It should expand to display the text being printed in there without being overlapped with other tests.

![2017-07-06 10_55_54-collection runner](https://user-images.githubusercontent.com/22200272/27893145-3e22fd28-6247-11e7-91c9-47f7c9a01b41.png)

**Comment by kamalaknn** [comment]
Hey @kharod, 

Thanks for reporting this. We'll look into this. We'll update the thread once this is fixed.

**Comment by sdnts** [comment]
Also, on a side note, you can view the body of the request without actually printing it out by clicking on the request name, which will open a tooltip where info about the request is displayed.

**Comment by kharod** [comment]
Thanks Guys.

**Comment by sivcan** [comment]
This has been fixed in the latest version of the Postman App (6.4)
You can now hover over long test names to see the tooltip with the complete name.
