### ISSUE TITLE
Request with 303 redirect response is never ending when Automatically follow redirects is off

### ISSUE THREAD

**Issue by blagoyborisov** [a85/POSTMan-Chrome-Extension#3242]
## App Details:

```
Postman for Chrome
Version 5.0.2
win / x86-32
Chrome 54.0.2840.87
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there: I have been experiencing the problem since at least version 5.0.1 of Postman.
 2. Expected behaviour: A response with status 303 is displayed
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):

window.localStorage is not available in packaged apps. Use chrome.storage.local instead.
beforeunload is not available in packaged apps.
window.localStorage is not available in packaged apps. Use chrome.storage.local instead.
unload is not available in packaged apps.
🌏 sync service connectivity initiated
socket replaying queued commands
🌏 connected to sync service.
🐶 watchdog checking connection health

When a GET request returns 303 redirect Postman just keeps displaying `Loading...` without displaying the redirect response. I am using Postman Interceptor and `Automatically follow redirects` is off. Some time ago it was working fine displaying the correct 303 response and not following the redirect.

Thank you!

**Comment by SamvelRaja** [comment]
@blagoyborisov  Thanks for bringing this to us. We shall update the progress in the same thread.

**Comment by abhijitkane** [comment]
@blagoyborisov We've updated the Interceptor to 0.2.23. Can you force an update?

Here’s what you need to do in Chrome:
```
In the address bar, type chrome://extensions.
At the top of the page, check and enable Developer Mode.
Click the Update extensions now button beneath Developer Mode.
```

**Comment by blagoyborisov** [comment]
The issue is resolved.

Thank you!
