### ISSUE TITLE
New Feature: description for expected response fields

### ISSUE THREAD

**Issue by cacothi** [a85/POSTMan-Chrome-Extension#3244]
## App Details:
Postman for Chrome
Version 5.0.2
win / x86-64
Chrome 59.0.3071.115

## Issue Report:
Hi Guys,

I would like to suggest a new feature for the documentation. 

It would be possible to have a documentation with regards to the expected response? (description for expected response fields)

We have a scenario which we would use Postman Documentation for our in-house APIs, and our team would need to have more details about the end-point response.

At the moment we can add a description, type, method and also the parameters descriptions, however I couldn't find a way to write a documentation with the response expectation. It would also nice to match with the test, like, the response is expect an array of items which would have some specific properties, and then **would be nice to have a description for each property within the response**.

**Comment by sdnts** [comment]
Hi @cacothi, you can use Example Responses for this kid of thing. [Docs](https://www.getpostman.com/docs/postman/collections/examples)

Example responses show up in the Documentation, so this should work for you :)

I'm closing this, but please reopen if you feel Examples do not serve your use case!

**Comment by averyby** [comment]
> Hi @cacothi, you can use Example Responses for this kid of thing. [Docs](https://www.getpostman.com/docs/postman/collections/examples)
> 
> Example responses show up in the Documentation, so this should work for you :)
> 
> I'm closing this, but please reopen if you feel Examples do not serve your use case!

Glad to find that the example response is editable.
