### ISSUE TITLE
[Feature] Improve mock servers.

### ISSUE THREAD

**Issue by bicanc** [a85/POSTMan-Chrome-Extension#3246]
I used your mock server and i like it, it is super easy to use, thank you for the product.
I want to use mock servers but i stuck somewhere.

For example;
1- There is a list service with pagination but Params are ignored by mock servers. I wish to create multiple mock examples; `?page=1`, `?page=2` or `?type=x` `?type=y&page=3` etc., and their custom responses in examples section, then when i request to mock server with these params, i want that specific responses.

2- and post method need this improvement too. For ex, I have save endpoint; 'saveItem'.
POST '/save' endpoint and I created multiple example request bodies;

A case: 
`{ responseWith: balance, type='pencil' } //returns with Balance body you defined in example 1 custom response`

B case: 
`{ responseWith: itemName, type='keyCode' } //returns with Balance body you defined in example 2 custom response .......`

'A' returning json could be completely different from 'B', but uses the same endpoint, with different request params and request bodies. 

So one endpoint can have multiple 200 responses with custom params and request body. (also can have multiple 400 errors too)

If you improve your mock servers to work this way, this would be awesome.

**Comment by sdnts** [comment]
Hi @bicanc, thanks for these suggestions! We'll look into these.

**Comment by ratpik** [comment]
@bicanc - We have introduced two new optional headers `x-mock-response-name` and `x-mock-response-id` either of which can be specified while calling a mock to specify the exact response you want by name or by the uid of the saved example respectively. This lets you custom match arbitrary responses to your mock request.

Eg. For your POST query above if you have examples that differ only in the body of the response saved with name as **Case A** and **Case B**, you can pass the `x-mock-response-name` header with value **Case A** to retrieve the response saved under **Case A**.

In case you plan to have multiple saved examples in your collection with the same name, then it is better to get the saved example by passing the example uid. Currently you can get the example response uid by using the [Postman Cloud API fetch a collection endpoint](https://docs.api.getpostman.com/#647806d5-492a-eded-1df6-6529b5dc685c) and searching for your example response in it. The uid has the syntax `<user_id>-<response_id>`.
