### ISSUE TITLE
Error with {{Domain}} env variable and query string params

### ISSUE THREAD

**Issue by chemitaxis** [a85/POSTMan-Chrome-Extension#3247]
## App Details:
```
Postman for Mac
Version 5.0.2 (5.0.2)
macOS Sierra 10.12.4 (16E195)
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there: **recently**
 2. Expected behaviour: 
**Make the get request correctly**
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
No logs needed
 4. Screenshots (if applicable)

![screen shot 2017-07-07 at 12 00 49](https://user-images.githubusercontent.com/1420409/27954411-1c4672a6-6310-11e7-8451-7c9891cee872.png)

Steps:

1.- Create a Env Variable, for example **Domain**, and add a value for this variable, for example **http://localhost:9000/**
2.- Create a method GET like this:  **{{Domain}}api/mystuff**
3.- Add a query string param

The console log show the request without the query string param:

![screen shot 2017-07-07 at 12 01 11](https://user-images.githubusercontent.com/1420409/27954415-2206aabc-6310-11e7-8e74-2fe48627c245.png)

Thanks

**Comment by sdnts** [comment]
Hi @chemitaxis, I'm unable to reproduce this.

From your screenshots, it looks like you're looking at two different requests. Do note that the Postman Console will only capture requests and display them when it is open.

Can you keep the console open and resend the request to see if it displays correctly?

Also, is it possible to check your server logs to check if the query parameters are actually sent?

**Comment by chemitaxis** [comment]
Hi, here you have the screen shot updated. You have 4. The "fail" is using the {{Domain}} environment variable, and the "ok" is using the host url directly.

If I replace the environment variable {{Domain}} with http://localhost:9000 it works fine. I have attached a screen shot too.

Thanks!!
![console_fail](https://user-images.githubusercontent.com/1420409/27955517-7eec03b2-6315-11e7-8925-10d4eaab8775.png)
![console_ok](https://user-images.githubusercontent.com/1420409/27955518-7eee8d9e-6315-11e7-83d9-bfd29d8723e4.png)
![postman_fail](https://user-images.githubusercontent.com/1420409/27955519-7eef77ae-6315-11e7-9e06-e899a0bb0f4d.png)
![postman_ok](https://user-images.githubusercontent.com/1420409/27955520-7ef2307a-6315-11e7-855f-13d6af57d8e3.png)

**Comment by chemitaxis** [comment]
Hi @madebysid did you see my screenshot? Thanks

**Comment by prashantagarwal** [comment]
Can you update to the latest postman app and verify if you are still seeing this issue.

**Comment by glaucomorais** [comment]
Here, with the Postman version 7.7.0, I was having the same problem. The request only was sent when I set the "current value" of the Global Variable.
Therefore, if the "current value" is not set, the "inital value" is ignored (at least, in the case of Global).

It is intentional or the "current value" only fallback to "initial value" in Environments/Local variables (not in Globals)?
