### ISSUE TITLE
When generating documentation the Parameters are not listed.

### ISSUE THREAD

**Issue by instecjason** [a85/POSTMan-Chrome-Extension#3249]
When generating documentation, I have an API call with 2 parameters.  I have set up examples to show how they are used but the parameter list and description of those parameters do not show up in the final documentation.  Headers DO show up... but the parameters and their descriptions do not.

From PostMan:
![image](https://user-images.githubusercontent.com/22374873/27974313-16d1db86-6323-11e7-832a-f7b9c846bfbc.png)

From Generated Docs:

![image](https://user-images.githubusercontent.com/22374873/27974336-3090e512-6323-11e7-89d3-b2e811637840.png)

**Comment by ferronrsmith** [comment]
Think this is what you're looking for https://www.getpostman.com/docs/postman/api_documentation/environments_and_environment_templates

You need to select an environment templates so the properties can be evaluated

**Comment by instecjason** [comment]
Hey Ferron,
  It is not what I am looking for.

I am talking about Parameters.  They pop up when you click the Param button.  I included screenshots to show what I am talking about.  The Headers are output in the documentation with their descriptions but the parameters are not.



Jason A. Pamplin, PhD
─ Striving for Clarity
m. 770-355-9814

**Comment by sdnts** [comment]
@instecjason We're building this out as we speak. I'm adding this as a feature request!

**Comment by instecjason** [comment]
That’s great to hear.  It seems since I can put in a description and that your documentation says it works that it was already there.

What expectation should I have on when this will be available?  Also, will you notify me when it is done?

Jason A. Pamplin, PhD
─ Striving for Clarity
m. 770-355-9814

**Comment by a85** [comment]
These area available now in the latest version of the documenter!

**Comment by MiGlez90** [comment]
Hello there, I know this issue is closed but I have recently had the same problem.  The params for my endpoint are not displayed properly.  Please, could you help me out? 
![screen shot 2018-12-12 at 1 01 53 pm](https://user-images.githubusercontent.com/15187254/49892273-33642b00-fe0e-11e8-8d19-b2a741a40f97.png)

**Comment by godfrzero** [comment]
@MiGlez90 What parameters are you expecting to be displayed? Also, are you seeing this problem in the private or public documentation?
