### ISSUE TITLE
Allow sharing a collection with part of a team

### ISSUE THREAD

**Issue by ferronrsmith** [a85/POSTMan-Chrome-Extension#3250]
~Is it possible to share a collection with members of the team and not the whole team ?~

**FEATURE REQUEST** : Add the ability to share a collection with individual members of the team vs all the team.

**Comment by sdnts** [comment]
@ferronrsmith Thanks for the request.
For now, you should be able to use the Run In Postman button to do this. Granted it won't be updated as the Team Library is, but it's a start till we get on this.

**Comment by a85** [comment]
Closing here. Will be tracking features like these through #3205
