### ISSUE TITLE
Combaining 2 Json Variable 

### ISSUE THREAD

**Issue by nenro** [a85/POSTMan-Chrome-Extension#3253]
HI All,

is there a way to combine 2 Json  environment variables ? 
for example 
Variable 1 : GenreIDs [28,18,14]
Variable 2 : [{"id":28,"name":"Action"},{"id":18,"name":"Adventure"},{"id":14,"name":"Animation"},{"id":35,"name":"Comedy"},{"id":80,"name":"Crime"}]

i need to create a new variable which based on the first 1 IDs, search for the Key and return the values. so in that case it should be : Action,Adventure,Animation

thansk 
ronen

**Comment by sdnts** [comment]
Hi @nenro, Lodash is included in the test sandbox, so you should be able to do:

```
var var1 = [28,18,14];
var var2 = [
{"id":28,"name":"Action"},
{"id":18,"name":"Adventure"},
{"id":14,"name":"Animation"},
{"id":35,"name":"Comedy"},
{"id":80,"name":"Crime"}
];

var var3 = _.filter(var2, function (item) { return _.includes(var1, item.id) })
// or if want just the names
var var3 = _.chain(var2)
                 .filter(function (item) { return _.includes(var1, item.id) })
                 .map('name')
                 .value()
```

Please feel free to reopen if I misunderstood.
