### ISSUE TITLE
Pre-request-Script own Snippets

### ISSUE THREAD

**Issue by ferronrsmith** [a85/POSTMan-Chrome-Extension#3254]
Should be able to save pre-request and tests scripts as snippets so that they can be used in other request.

~~pre-request/tests scripts should be executed in a true sandbox. Currently set/clearGlobalVariable modifies global which isn't really "sandboxed". Modifications made inside the sandbox shouldn't affect global state.~~

I see why you did it this way, but a true sandboxed approach would av made for interesting things.

**Comment by sdnts** [comment]
Hi @ferronrsmith, this has been on our radar for quite some time now, and we're actively working to make this possible in an elegant fashion.
I'm closing this in favour of #675 (Custom snippets) and also #2749 (Collection level scripts), but please reopen if I misunderstood :)
