### ISSUE TITLE
mac client problem - Could not get any response- exported curl works fine

### ISSUE THREAD

**Issue by daugustus** [a85/POSTMan-Chrome-Extension#3255]
## App Details:
```
Postman for Mac
Version 5.0.2
OS X 15.6.0 / x64
```
## Issue Report:
Using basic auth - converted to an Auth header by Postman - Postman responds with "Could not get any response", console is empty. If I convert the request to cUrl and run the request, cUrl responds with the expected result. 

The dev-tools console was empty (I have never used the console before so it could be my error in using the dev tool).

The linux client works perfectly using the same collection.  Also, the chrome plugin- on the same Mac where Postman is installed - works fine.

Obviously, I cannot share the credentials with you but if you have other ideas or need more information, I will be glad to help if I can.

Thanks,
Dave

**Comment by kamalaknn** [comment]
Hey @daugustus,

Could you open Postman Console (`View -> Show Postman Console`) and then send the request with the console open, and share the logs? You can remove the authentication part in the logs though.

**Comment by daugustus** [comment]
The log entries are below. They show a simple timeout but this seems unlikely as it happens immediately. 
```
GET
https://example.com/applications?output=JSON
Error: ETIMEDOUT
Request Headers:
Authorization:"Basic BOGUS123=="

**Comment by prashantagarwal** [comment]
@daugustus Can you please update the Postman app to latest version and verify if you are still facing this issue. Thanks

**Comment by mohitkanwar** [comment]
Hi,
I am facing the same issue in 5.5.2 (latese version as of 19 Jun 2018)

**Comment by preethammavin** [comment]
@mohitkanwar try using the native apps(6.1) as we have deprecated chrome apps, and let us know if the issue persists.

**Comment by MatthieuPeyrot** [comment]
The same issue I get ETIMEDOUT to every single request even in POST GET PUT.
My versions of the client on mac is 6.1.4

**Comment by dhcmega** [comment]
Same for me, all api calls giving ETIMEDOUT. Thanks.

EDIT: solved by changing timeout from 12 (?) to 100000

**Comment by numaanashraf** [comment]
There are several unrelated request sending issues being posted on this thread as they all have the same symptom of 'Could not get any response'. This prevents us from tracking these issues individually, suggest possible workarounds and post updates on bug fixes and releases to our stable and canary channels. We are locking this thread to prevent further posts of unrelated issues.

If you get a "Could not get any response" message from Postman native apps while sending your request, open Postman Console (View > Show Postman Console), resend the request and check for any error logs in the console. This should give you some information to troubleshoot the issue by searching for the same error in this issue tracker to find possible workarounds and fixes. If you are still having trouble, please open a new bug report with the screenshot of the error and any steps we can take to quickly replicate the issue.
