### ISSUE TITLE
Ability to share collections across teams

### ISSUE THREAD

**Issue by olivoil** [a85/POSTMan-Chrome-Extension#3256]
Would it be possible to have several "teams" in a cloud account?

I work on several projects, each with different team members, and can't share a collection from one project to team members from another project.

**Comment by kamalaknn** [comment]
Hey @olivoil 

Thanks for your feedback.

I am tagging this as a feature request. @a85 can clarify on the roadmap for this.

**Comment by a85** [comment]
Inter-team collaboration will be possible through #3205 but they are far away in the roadmap right now. You'll have to export/import manually.
