### ISSUE TITLE
No method when pressing "ENTER"

### ISSUE THREAD

**Issue by mfrtrifork** [a85/POSTMan-Chrome-Extension#3257]
## App Details:

```
Postman for Mac
Version 5.0.2
OS X 10.12.5 / x64
```

## Issue Report:
When choosing the method to the left of the URL input field the user is allowed to press "enter/return" to select no method. Would be nice if the first element/"GET" would be selected when pressing enter in the dropdown.

When pressing enter in version 5.0.2 there is no method and the "cURL" for the request is invalid since it has no method.
I would expect it to select "GET" as method but please let me know if this is expected behaviour.

Let me know if you have any questions or need help to reproduce.

Thanks for a great application though 🥇

**Comment by kamalaknn** [comment]
Hey @mfrtrifork 

Thanks for sending your feedback. I was able to replicate this too. Ideally, one request method should always be selected.

I'll look into this.

**Comment by a85** [comment]
@kamalaknn Is this fixed now?

**Comment by mfrtrifork** [comment]
@a85 Yes, I can confirm that it was fixed 👍

**Comment by a85** [comment]
Awesome!
