### ISSUE TITLE
[Usability Suggestion] One more dropdown for environments

### ISSUE THREAD

**Issue by alvmunoz** [a85/POSTMan-Chrome-Extension#3258]
## App Details:
```
Postman for Windows
Version 5.0.2
win32 6.1.7601 / x64
```
All the people in my team agreed that it would be very useful to have an additional Dropdown for Environments in Postman.

We would use one dropdown to choose the environment and the other to choose the user credentials you want to use for that environment.... At the moment we have to edit it everytime and it is exhausting.
However I believe there can be additional user cases a part of using it for credentials.

![maxthonsnap20170711113446](https://user-images.githubusercontent.com/17126683/28062125-40dfe65e-662d-11e7-8eac-60823965686b.png)

thanks,

**Comment by bhawna2109** [comment]
Thanks for the suggestion @alvmunoz 
However, I'm afraid I do not understand your use case entirely. You can currently store different credentials in different environments and switch between them. Does this not help?

**Comment by alvmunoz** [comment]
Hi @bhawna2109  , can you advise how to do it? 

At the moment, we have all the users in the enviroments with a different "Key" name, and then we have to rename the key everytime we wnat to use a different user. Or we have to copy/paste the user in the user variable everytime we want to change the user. That's very tedious. 

We prefer to have a prefix set of user credentials and we can change from one user to another user by just selecting in the dropdown, rather than having to: 
1) open the enviroments, 
2) copy the user from somewhere, 
3) replace the value of the key, 
4) save...

**Comment by bhawna2109** [comment]
@alvmunoz Got it - environments are meant to support this very use case :)

I would suggest having different environments for different users in this case. For example, if I have 3 users, I would create 3 environments, namely User1, User2 and User3.
Each of these environments would share the same set of keys (user credentials), but with different values for each user.

You can use these keys in your requests and their values will change when you change the environment from the dropdown. A step by step guide for working with environments is here - https://www.getpostman.com/docs/postman/environments_and_globals/manage_environments

Let me know if this isn't something you're looking for.

**Comment by alvmunoz** [comment]
At the moment we are using the Enviroments dropdown to choose the "enviroment" where we send the requests (that is, PRODUCTION, SIS, DEVELOPMENT, LOCAL, etc. ).   

The only option is to have an enviromemnt for user. So we would increase the number of enviroments * number of users credentials.... Which is not easy to manage....

**Comment by bhawna2109** [comment]
@alvmunoz Yep, I understand the need. We're tracking a similar issue here #2621 
Improving the UX around Environments is a part of our roadmap, and we'll definitely look into this. Thanks for bringing this up - will update this thread once we have something concrete.

**Comment by alvmunoz** [comment]
Yes, that's exactly what I want! nested enviroments!
> So I have to name my environments like [Project1][Dev] - user1, [Project2][Test] - customer2 e.t.c.

You can close this issue and I will track the progress in that one.

Thanks :)

**Comment by bhawna2109** [comment]
That would be good @alvmunoz 
Closing this as duplicate.
