### ISSUE TITLE
Wait for next call

### ISSUE THREAD

**Issue by decode007** [a85/POSTMan-Chrome-Extension#3260]
Hi, I am using POSTMAN for one restconf operations.
One of my request is for link bring-up. In which after successful post call. It takes around 5 min for link to come up.
That why my get request fails, when i run as a collection.
I can not set interval on the complete collection as it is for one call only.

I tried with setTimeout, set interval also in test tab. But that too is not working.

`function dummy () {
}
setTimeout(dummy, 10000);
console.log("wating for some time")'

log says :

> setTimeout is not available inside sandbox and has no side-effect.

**Comment by prashantagarwal** [comment]
Hey @decode007 .  Currently there is no straight forward way to do this from Postman., but in upcoming releases we are bringing some new improvements which should make all this possible very easily. In the meantime you can refer #1038 for some work arounds.
