### ISSUE TITLE
[Feature Request] - Highlight the differences in the 'Resolve Sync Conflicts' window

### ISSUE THREAD

**Issue by Faz540** [a85/POSTMan-Chrome-Extension#3261]
Lately I've been seeing the 'Resolve Sync Conflicts' popup in Postman between what's been synced to the server and what the local value is.

Ideally, the difference between the local and server values should be highlighted to make it obvious to the user what changes they're committing to.

This is pain if the app crashes and it's asking the user lots of conflicts.
Feel free to ask if you need more info about this request.

**Comment by prashantagarwal** [comment]
@Faz540 Thanks for suggesting this. Point duly noted. 👍

**Comment by Heydiddly** [comment]
These suggestions have probably already occurred to you, but it would also be great to have wider/resizable text areas for the local/remote sections, and have each request be collapsible.

**Comment by ankit-m** [comment]
Released to production.
