### ISSUE TITLE
Global Variables not saving

### ISSUE THREAD

**Issue by ryancap-ual** [a85/POSTMan-Chrome-Extension#3263]
## App Details:
Postman for Windows
Version 5.0.2
win32 6.1.7601 / x64

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there: New Issue
 2. Expected behavior: When I create a new global variable key/value so that I can do what is in the video https://www.youtube.com/watch?v=DTOS_dFeXvM&t=552s. It does not save the variable definition. 

1) Make new global variable key/value. 
2) Save it
3) Click out of that window.
4) Run API
Global variable definition not saved even if it is static.

**Comment by sdnts** [comment]
Hi @ryancap-ual, I'm not able to reproduce this.
When you say you click out of the window, are you referring to the Globals window? If so, you have to explicitly press Save at the bottom to save your globals. This additional steps makes sure no accidental saves take place.

If this does not work, can you share the script you're using to set the variable?

**Comment by tobeliketree** [comment]
I am having the same problem.  I am using the following code in the tests window to attempt to capture the organization id from the json response and then set it as environmental variable. 

`var jsonData = JSON.parse(responseBody);
postman.setEnvironmentVariable("organization_id", jasonData.data.org.id);`

The response body is as follows and I am expecting  'O00006zZL5oD.wxw' to be set as an environmental variable.  This is not happening when I look at quick view or edit the actual environment template.  

`{
    "status": "ok",
    "data": {
        "org": [
            {
                "member": "t",
                "id": "O00006zZL5oD.wxw",
                "name": "Treebris"
            },
            {
                "member": "t",
                "id": "O0000AoXP1xI.fPs",
                "name": "PS Test Agency"
            }
        ]
    }
}`

I also tried to use the same code to set a global variable and that was not working either.

**Comment by tobeliketree** [comment]
I have some additional information to add to my post above.   The problem seems to be happening with any new attempt to set global or environmental variables.  I have long running / existing endpoints that use the exact same code block (different key values I'm looking for of course) and those work perfectly.  It's any new attempt at using this code block that seems to be a problem.   
Interestingly when I console.log the key I'm looking for it returns **null**. 

`https://www.photoshelter.com/psapi/v3/avatar/query?api_key=Q0CyJliGlFA&fields=*&user_id=U0000iXlMoqKC5T8`

```
var jsonData = JSON.parse(responseBody);
postman.setEnvironmentVariable("avatar_id", jsonData.data.Avatar.avatar_id);

console.log(jsonData.data.Avatar.avatar_id)
```

[Here is a screenshot with console open and console.log showing null when value is there.](http:/www.stockimages.me/postman.png)

**Comment by tobeliketree** [comment]
@madebysid  Can you take a look at my update documented above?  I still cannot save any variables.  All I get are null values -  this same code worked before but doesn't any longer in newest version of the app for mac.

**Comment by sdnts** [comment]
Hi @tobeliketree, from your screenshot, it looks like `Avatar` is an array. In this case, the correct selector would be `jsonData.data.Avatar[0].avatar_id`. I'm guessing this is why your variables were not being saved. Can you try this and let me know what happens?

**Comment by mardann** [comment]
I have encountered same issue:
I'm using a static global variable in place of a header value needed across all services in a collection.

## Reproduction:
1) set global variable via  "Manage Environment" window `access_token:xxxx`, save

2) place variable in request header:
`Content-Type:application/json
Mobile-App:1
Access-Token:{{access_token}}`

3) run request - everything fine:
`Content-Type:application/json
Mobile-App:1
Access-Token:xxxx`

4) edit same variable `access_token:yyyy`, click save

5) preview that variable HAS changed - with mouse-over and by clicking the "eye" icon - variable is set to `yyyy`

6) run services again - **VARIABLE CHANGED BACK TO OLD VALUE**!
`Content-Type:application/json
Mobile-App:1
Access-Token:xxxx`

## Environment:

Postman for Chrome
Version 5.1.2
win / x86-64
Chrome 59.0.3071.115

**Comment by prashantagarwal** [comment]
@mardann Can you do couple of things here.
- Update your app to the latest postman version.
- Check that you are not setting the same variable using pre-request or test scripts.

**Comment by sujayvenaik** [comment]
Hey @mardann 

I checked this on my end and this seems to work fine.

Please try it once with the latest app and also make sure that you are not changing the variables again in the pre-request or test scripts.

**Comment by numaanashraf** [comment]
@ryancap-ual @mardann @tobeliketree We had made various core changes to the internals of the app to prevent these issues. I was not able to replicate this on the latest version of Postman (v6.1.4). Please verify and reopen if this is still happening at your end with the latest version.

**Comment by Elsin-S** [comment]
Adding a Solution here, Close all the postman windows and try again.
