### ISSUE TITLE
Import Folder of Collections Not Working

### ISSUE THREAD

**Issue by ejerlun** [a85/POSTMan-Chrome-Extension#3264]
## App Details:
Postman for Chrome
Version 5.0.2
win / x86-64
Chrome 59.0.3071.115

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there: Recent
 2. Expected behaviour: Import > Import Folder > Drag and Drop | Select Folder then collections in the selected folders imported.
 3. Console logs:
common.js:128041 Uncaught (in promise) TypeError: Cannot read property 'FileReader' of undefined
    at child.importFolder (common.js:128041)
    at xml.js:22
    at <anonymous>
importFolder @ common.js:128041
(anonymous) @ xml.js:22

**Comment by sdnts** [comment]
Hi @ejerlun, thanks for reporting this. I was able to reproduce this. We will get this fixed as soon as possible.

**Comment by a85** [comment]
@madebysid Is this fixed?

**Comment by JhonatanGarcia92** [comment]
@madebysid is this fixed?

**Comment by a85** [comment]
Chrome apps are deprecated. Please move to the native app for bug fixes and better support.
