### ISSUE TITLE
Import Folder doesn't work from v5

### ISSUE THREAD

**Issue by kunagpal** [a85/POSTMan-Chrome-Extension#3267]
Originally posted by @gauravshetti in https://github.com/postmanlabs/newman/issues/1126

> From v5 onwards, importing folders containing collections, enviornment and global variables doesn't seem to work anymore.

## App Details:

```
Version 5.0.0
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:
 2. Expected behaviour:
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 4. Screenshots (if applicable)

**Comment by gauravshetti** [comment]
Yes, the behaviour was consistent or as expected (import from folders) in v4.5. However in latest 2 versions (v5.0, v5.0.2) I am not able to import collections or environments using import Folder functionality.

Here is the error thrown on Postman DevTools
```
xml.js:22 Uncaught (in promise) TypeError: Cannot read property 'FileReader' of undefined(…)
importFolder @ xml.js:22
(anonymous function) @ xml.js:22
```

**Comment by kunagpal** [comment]
Duplicate of #3264

My bad, I didn't see that one earlier.
