### ISSUE TITLE
Prettify/Beautify JSON and XML in Request Body

### ISSUE THREAD

**Issue by qarasha** [a85/POSTMan-Chrome-Extension#3270]
# Prettify/Beautify/Minify in Request Body
It would be cool to have a Prettify/Beautify and eventually Minify feature for request body. 
For us that are extensively using Postman, we do loose some amount of time on prettifying/beautifying JSON/XML in request bodies (especially when collected and pasted directly to postman). 

## App Details:

```
Postman for Mac
Version 5.0.2 (5.0.2)
OS X 10.11.6 / x64
```

**Comment by sdnts** [comment]
@qarasha You can beautify the raw body by selecting everything and using the shortcut `Cmd+B`. Is this what you were looking for?
Please feel free to reopen if not!
