### ISSUE TITLE
Accept-Language is sent but I not specified it.

### ISSUE THREAD

**Issue by Arkemlar** [a85/POSTMan-Chrome-Extension#3271]
## App Details:

```
Postman for Chrome
Version 5.0.2
linux / x86-64
Chrome 59.0.3071.86
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there: just got it, worked fine before
 2. Expected behaviour: do not send Accept-Language
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 4. Screenshots (if applicable)
![image](https://user-images.githubusercontent.com/19671202/28178286-95aa41fe-6806-11e7-89a9-a002b4e3c39a.png)

To reproduce: I opened chrome app, then run API method which I used before without any problems.
Postman shows following cURL code:
```
curl -X GET \
  http://my-local-url \
  -H 'cache-control: no-cache' \
  -H 'content-type: application/json' \
  -H 'postman-token: some-token' \
  -H 'vf-api-token: some-token'
```
My backend app shows me request info in debugger and I seen that request contains following header:
`accept-language "ru-RU,ru;q=0.8,en-US;q=0.6,en;q=0.4"`
I used curl command above in console and proved that there is no such a header in request in my backend side, then I checked XHR request using chrome debugger and found that this header is sent:
![image](https://user-images.githubusercontent.com/19671202/28178615-c9297bc0-6807-11e7-8c47-9b8950be3961.png)

**Comment by sdnts** [comment]
Hey @Arkemlar, are you using the Interceptor to send your requests?

Also, as an alternative, can you try this out on our [native apps](https://getpostman.com/apps)?

**Comment by Arkemlar** [comment]
@madebysid I use smetimes, but during this tests it was disabled. In native app everything is ok, the header is not sent when not specified.

**Comment by sdnts** [comment]
Ah, as I suspected. When you send out XHR requests from Chrome, it auto-attaches this header.
I'd suggest shifting to the native apps anyway, since Chrome apps will deprecated by Google this year.
I'm closing this since the native apps behave as expected. Please reopen if you feel otherwise :)

**Comment by Arkemlar** [comment]
@madebysid the strange thing is that this issue appeared recently, so it might be something with browser upgrade. But nvm, I will use native app then.
