### ISSUE TITLE
code generate - node.js request  - fs.createReadStream quotes  

### ISSUE THREAD

**Issue by m67hoff** [a85/POSTMan-Chrome-Extension#3273]
the  code generate  for a multipart/form-data POST  for  node.js request 
has a quoted  fs.createReadStream()  call - so it will not read the file!  
(instead it sends  the sting "fs.createReadStream(...)" ) 

#### 5.0.2 code sample:

```javascript
var fs = require("fs");
var request = require("request");

var options = { method: 'POST',
  url: 'http://localhost:1880/read',
  headers: { 'content-type': 'multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW' },
  formData: 
   { '': 
      { value: 'fs.createReadStream("img.jpg")',
        options: { filename: 'img.jpg', contentType: null } } } };

request(options, function (error, response, body) {
  if (error) throw new Error(error);

  console.log(body);
});
```

#### should be :

```javascript
var fs = require("fs");
var request = require("request");

var options = { method: 'POST',
  url: 'http://localhost:1880/read',
  headers: { 'content-type': 'multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW' },
  formData: 
   { '': 
      { value: fs.createReadStream("img.jpg"),
        options: { filename: 'img.jpg', contentType: null } } } };

request(options, function (error, response, body) {
  if (error) throw new Error(error);

  console.log(body);
});
```

**Comment by sdnts** [comment]
@m67hoff Thanks for pointing this out! We'll get this fixed.

**Comment by abhijitkane** [comment]
Can you try this is Postman 7.2.1, with the 'Experimental Codegen Mode' flag enabled in Postman's global settings? We've introduced bug-fixes, support for two new languages (JS-Fetch and Powershell), and the ability to configure certain aspects of the generated snippet.

I'm unable to reproduce this particular issue in the latest version (experimental mode).
