### ISSUE TITLE
Body in post is deleted when it is being work on simultaneously

### ISSUE THREAD

**Issue by ycho46** [a85/POSTMan-Chrome-Extension#3276]
## App Details:

```
Postman for Windows
Version 5.0.2
win32 6.1.7601 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there: Been working around this for a while
 2. Expected behaviour: Body to be in sync
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 4. Screenshots (if applicable)

1. Create a post requset
2. Add body
3. Keep it open and let someone else edit the post.

**Comment by kamalaknn** [comment]
Hey, @ycho46 ideally it should warn you with a message `This request has been modified in another open tab.`. Did the request body change without a confirmation dialog?

Could you share more info on what/how you changed the request body, that is causing you to lose your work? (screenshots or screen capture would be super helpful).

**Comment by ycho46** [comment]
Hi @kamalaknn, so the message "This request has been modified in another open tab." appears when we are about to close the tab and somebody else worked on it. Our problem is that when we open a random post, sometimes the Body of the post would be missing. We initially thought this was a sync issue that when people are simultaneously working on the same post the sync would get messed up and body would be deleted. To avoid this our team was trying not to work on the same post at once. However, the deletion of the body still occurred. Another thing is that the data is available online (Web browser), so when we save the collection using the API key, the body is present. It is that the body is missing locally (Postman App) for the whole team.

**Comment by TheAllThing** [comment]
Related to this issue, I've seen where a team member has content in the body that is not in sync with what's in the web view. We were able to sync the first issue by making a small change on the desktop client's body and it pushed all changes from client up to the web.  

Conversely, we have also seen where the web view content is _empty_, but the body on the local desktop app has the content we expect to be present. Clicking the sync button does not push to the web, so teammates do not get the updates made locally.

**Comment by kamalaknn** [comment]
@TheAllThing @ycho46 

We've pushed some major improvements to our Sync and Data layers in the latest stable release. Could you update your app to the latest version? Please let us know if this issue still exists
