### ISSUE TITLE
Delete other user's environment templates

### ISSUE THREAD

**Issue by alvmunoz** [a85/POSTMan-Chrome-Extension#3277]
## App Details:
```
Postman for Windows
Version 5.0.2
win32 6.1.7601 / x64
```

Hi,
We have in our postman a number of environments that were shared by people that are no longer in the Company. Despite of being admin, there is no way to delete them. 

At least admins should have the rights to delete any environment template.

**Comment by kamalaknn** [comment]
Hey @alvmunoz 

Could you email your `Team` id and the `Environment templates` you want to remove to `help@getpostman.com`?

We'll take a look at it.

**Comment by sdnts** [comment]
I'm closing this in favour of #3274, as this will be taken up with that feature request. Please reopen if you feel otherwise.
