### ISSUE TITLE
Shortcut for cycling through tabs 

### ISSUE THREAD

**Issue by javiber** [a85/POSTMan-Chrome-Extension#3280]
It would be nice if we could use `ctrl+PgUp` / `ctrl+pgDown` to cycle through tabs the same way as it works in Chrome.
IMHO all tabs-related shortcuts should be the [same as in Chrome](https://support.google.com/chrome/answer/157179?hl=en)

**Comment by sdnts** [comment]
@javiber Cycling through tabs is possible using `Cmd+Shift+]` & `Cmd+Shift+[`.
Is this what you were looking for?

Please reopen if not :)

**Comment by javiber** [comment]
Hey @madebysid, Thanks for the quick response,

First of all, I use Ubuntu so for me it's `Ctrl+Shift+]` & `Ctrl+Shift+[` and although your right, that *does* works on Postman but the problem is that for Linux and Windows, Chrome uses `Ctrl+Tab`/`Ctrl+Shift+Tab` or `Ctrl+PgDown`/`Ctrl+PgUp` (check this [link](https://support.google.com/chrome/answer/157179?hl=en)). So it would be great for Windows and Linux users to just use the same Chrome shortcuts that we've already wired in our brains.

**Comment by patrick-boatner** [comment]
+1 for making them the same as Chrome (any most other web browsers) via `Ctrl-Tab`. I'm a big fan of keyboard shortcuts, but I can't bring myself to learn a non-standard tab switch shortcut.

**Comment by nlwillia** [comment]
This is still an issue for Windows users.  @madebysid can it be reopened, or would you rather someone request it again?

**Comment by sdnts** [comment]
Hey @nlwillia, I'm not involved with this repo anymore, so I'd suggest opening a new one so the right people take a look at it!
