### ISSUE TITLE
Get Collection URL is not working 

### ISSUE THREAD

**Issue by tatyanaprokopenko** [a85/POSTMan-Chrome-Extension#3287]
Application info:
Postman for Mac
Version 5.0.2
OS X 15.6.0 / x64

I tried to get collection URL 
collection->Share collection->Collection Link->Get link->No url appears->Fetch link-> error "Something went wrong while generating a shareable link for your collection. Try again after sometime."

**Comment by prashantagarwal** [comment]
@tatyanaprokopenko Hey, I am unable to reproduce this. This error generally occurs when you are offline (not connected to internet). Can you once please verify your network connection status.

**Comment by tatyanaprokopenko** [comment]
Just checked my network connection, seems like it is fine
<img width="1323" alt="screen shot 2017-07-19 at 13 32 37" src="https://user-images.githubusercontent.com/16290695/28364943-e40983da-6c86-11e7-8d10-a0988292313c.png">

**Comment by prashantagarwal** [comment]
Hmm, Ok can you open devtools and check network panel to see what happens when you click on Get Link.

**Comment by tatyanaprokopenko** [comment]
![screen shot 2017-07-19 at 13 48 23](https://user-images.githubusercontent.com/16290695/28365466-023cd92c-6c89-11e7-931f-f87fdec515c8.png)

**Comment by prashantagarwal** [comment]
Okay just one last thing, what's the response you are getting for this request ?

**Comment by tatyanaprokopenko** [comment]
Only for events I have response
{"RecordId":"5fInY8GQ+HjpfQ9EzZulhsj1f0HTxZsYSGU5vINoaXzRFyEPlYc3DfCsipb1q/PFbZveet4go1Xe2Tl9/4XPt13sLxmRnxTYRqLnDyVJUImN/QLhLCzhHs/yU6vD01RVqaOfIqUuRfH6IQNh/Ufs+tYyM5z91PzUhK1p6kR15qRL3z0EwqN2aL195kqCwCqPoJeP6F5o455YmrhMQlpf/C1+8LeSXwmd"}

![screen shot 2017-07-19 at 14 01 38](https://user-images.githubusercontent.com/16290695/28365931-d279b672-6c8a-11e7-8635-b8491981246d.png)

**Comment by prashantagarwal** [comment]
No, I mean I can see your collections request failing in the above screenshot. I want to see are you getting 400 for some reason or any other status. So can you open the response of that collections request (the one which is red in above screenshot) and see what status/error the API is returning.

**Comment by tatyanaprokopenko** [comment]
It says 
(failed) net::err_connection_reset
![screen shot 2017-07-19 at 14 15 02](https://user-images.githubusercontent.com/16290695/28366367-adf8d59c-6c8c-11e7-8fad-59b5862727bd.png)

**Comment by prashantagarwal** [comment]
Hmm, So this means that this request is not going to network because of some network connection issue. Any chance that you are behind a network proxy ? Also have you recently started facing this issue or was it there before ?

**Comment by tatyanaprokopenko** [comment]
I will check with my DevOps team and let you know.
Thank you for help

And I have one more problem, in the morning I sent message in Postman help desk but still don'e have answer. Maybe you can help me 
"Hello postman team,

My account is tatyana.prokopenko (tatyana.prokopenko@gmail.com) and yesterday I accidentally updated all my new collections with old data. How it happened:
I have several postman applications and yesterday I opened one that I didn’t for about 3 months and in the morning I opened application with my new data in collection, but all my new collection now has old data
Could you please revert all that happened after 18.07 (18:00 Amsterdam time)

Looking forward your answer,
Tatyana"
