### ISSUE TITLE
Fuzzing option in postman

### ISSUE THREAD

**Issue by javixeneize** [a85/POSTMan-Chrome-Extension#3289]
Hi

This is not an issue at all, its just a question. I would like to know if i could create some type of loop in postman

I want to do a loop where i read every line from this text file and i inject that value to a field in the body and check the assertion

For example, i have a text file with several payloads (every line is a payload). Lets say:

' or 1=1; --
<script>alert("1")</script>
injection2
injection3
etc

I have a body with 4 fields. a, b, c, d

I have an assertion (test) that the response has to be different to code==200

What i want to do a loop where i map to the field b the content of the line of the text file and validate the response against the expected result

Is that possible?

Thanks

**Comment by virusdefender** [comment]
You need Burp Suite

**Comment by prashantagarwal** [comment]
Hey @javixeneize you can post this question in our slack community. Someone will definitely help you out there.
