### ISSUE TITLE
Add variable substitution in URL

### ISSUE THREAD

**Issue by cappslock** [a85/POSTMan-Chrome-Extension#329]
It would be nice to do variable substitution in the request URL.

For example if the request URL is:

```
{{host}}/things
```

And there is a variable:

```
host = http://api.com/api/v1.0
```

request would resolve to:

```
http://api.com/api/v1.0/things
```

**Comment by Abhinay12** [comment]
i just wanted to use access_token  as a variable...........................

**Comment by prusswan** [comment]
`{{host}}/some_path?some_param={{value}}`   value is not substituted

This problem comes and goes

**Comment by abhijitkane** [comment]
@prusswan Can you mention the Postman version you're on?

**Comment by prusswan** [comment]
Version 3.2.20 (packaged) OS: win
Architecture: x86-32
Native client architecture: x86-64

**Comment by mashariqk** [comment]
Not sure if this will help but I had a similar requirement to get the complete request in the Pre-request Script. I have created a gist for the same https://gist.github.com/mashariqk/62fdf2a0d6497b88ab62428021196aec

**Comment by peterkrieg** [comment]
`{{urlPrefix}/users` doesn't substitute either - any updates on this?

**Comment by mashariqk** [comment]
@peterkrieg You should get the url first by calling 
`var url = returnParsedUrl();`
And then do any manipulations in the Pre-Request Script. Let me know if that worked for you

**Comment by peterkrieg** [comment]
@mashariqk   actually my problem was just that the variable `initial value` was set but not the `current value`.  I thought current value would default to initial if not filled in but I guess I was wrong.  Thanks for the help though!

**Comment by mashariqk** [comment]
Cool!
