### ISSUE TITLE
Custom SSL CA support in Postman Desktop apps

### ISSUE THREAD

**Issue by Comradin** [a85/POSTMan-Chrome-Extension#3290]
## App Details:
Postman for Windows
Version 5.1.0
win32 6.1.7601 / x64

## Issue Report:
 1. We could verify this with 5.0.0/5.0.2/5.1.0
 2. Accessing an encrypted website with a certificate issued by company CA
 3. The console shows the following error: Error: SSL Error: UNABLE_TO_GET_ISSUER_CERT_LOCALLY

I try to access an internal ssl protected URL with the latest postman client for windows. Just updated this morning to 5.1.0. The company uses its own certification authority and the root certificate is installed on all windows clients via ActiveDirectory/GPO mechanisms.

The different browsers installed on my computer can access and verify the certificate. Tested with Firefox and Chrome.

I checked the certificate store using the mmc (Microsoft Management Console) with the certificate snap-in and the CA's root certificate is in the trusted root ca folder for my user and the computer. (I am not sure about the correct naming, I have a german windows installation). 

But for the Postman client I have to deactivate the ssl certificate verfication in Settings -> General.

**Comment by prashantagarwal** [comment]
@Comradin Thanks for reporting this. We are investigating this issue.

**Comment by sridevicherukuri** [comment]
Are there any updates on this issue?

**Comment by responsible-adult** [comment]
I am hitting this exact problem also.

**Comment by Comradin** [comment]
Just tried with the latest 5.2 release and the error still exists

**Comment by Comradin** [comment]
Just a note, our colleagues with Windows 10 machines have the same issue. Sadly it is not Windows 7 only :slightly_smiling_face:

**Comment by slilie** [comment]
I am having this issue as well, I tried installing the root cert from mmc into Postman but my request continues to fail with "UNABLE_TO_GET_ISSUER_CERT_LOCALLY".

**Comment by numaanashraf** [comment]
@Comradin @etzlers1 @robert-mendoza @sridevicherukuri Custom CA is not supported in Postman Desktop apps yet. This is on our roadmap but we don't have an ETA at the moment. We'll post updates here when we start working on this.

**Comment by OliverRC** [comment]
I'd definitely add my vote to have this implemented. Working in a corporate environment it is common to have a local CA for development environments. 

It is interesting to note that the Chrome extension works because it reuses the Chrome certificates. It would be a great addition to allow the Desktop app to do the same.

**Comment by jobec** [comment]
Same here. It also feels very wrong having to disable this globally if a single server has an internally signed certificate.

Lots of other tools allow to specify this in some sort of config file:
- pip (for installing python packages)
- git
- vagrant
- Pycharm

**Comment by ruariobrien** [comment]
I would like to see the ability to point postman to a CA bundle, will this be a future enhancement?

**Comment by them0ntem** [comment]
Hey, Any update on this issues?

**Comment by gartmeier** [comment]
Sadly not a Windows only issue. Experiencing the same issue with macOS as well

**Comment by gthieme** [comment]
I believe I'm hitting this same issue, but with a different error message. The error I get is:
Error: SSL Error: UNABLE_TO_VERIFY_LEAF_SIGNATURE

The keychain of the cert for the host I'm hitting uses a custom intermediate issuing ca and a custom root ca. Could that be the cause of the different error message?

**Comment by science695** [comment]
I can confirm this is happening on ubuntu 18.04 as well

**Comment by bjnoelucanr** [comment]
This would be very helpful as we use self-signed certs for internal only servers. It's hard to use Postman as a true testing platform without this...

**Comment by ghost** [comment]
I can confirm this needs to be implemented ASAP. I got the root CA in the OS trust store but Postman sadly thinks the OS trust store is not needed, so it's very hard to use Postman to test internal servers with self-signed certificates.

**Comment by josh-cain** [comment]
+1.  System trust store configured correctly, but Postman will not recognize environment trust store, or allow me to customize the one it's using.  Bad form.

**Comment by science695** [comment]
Even if there was some "hack" way to let us add the root CA to postman manually, it would be a great help.

Where does Postman keep its root CAs?

**Comment by derKrischan** [comment]
+1. Another upvote for this issue. We need a possibility to configure the CA or a truststore. Disabling SSL at all is bad style.

**Comment by gjd6640** [comment]
I have this same issue and concern. Disabling SSL shouldn't be necessary. Also, it sours new-to-Postman users on the experience by presenting a hurdle to getting it working when they're first introduced to the product.

**Comment by rest17** [comment]
Have same issue.There should be support to add selfsigned truststore to have mutal authetication.

**Comment by bond-** [comment]
+1 on Postman for Mac

**Comment by SteelPhase** [comment]
it's probably time for an update here. this is still an issue in v6.2.5

**Comment by Fonger** [comment]
If you can't resolve this issue, you shouldn't deprecate Chrome app.

I guess this issue can't be easily fixed because Electron apps are bundled with node.js which uses built-in certificates.

**Comment by TimJin** [comment]
+1 on mac

**Comment by TimJin** [comment]
One way to workaround:
Self-signed SSL certificates are being blocked:
Fix this by turning off 'SSL certificate verification' in Settings > General

**Comment by SteelPhase** [comment]
Seems Electron is the blocker. Node has support for added additional ca certs with the NODE_EXTRA_CA_CERTS environment variable. Also while disabling SSL certificate verification is an option, it's definitely not the correct way to solve certificate issues

**Comment by tbennett6421** [comment]
I would like to see custom ca's supported as well

**Comment by feyyazesat** [comment]
I'm not sure do I'm hitting to exactly same problem here, but when I setup Postman proxy, I cannot proxy SSL urls and I hit to postman provided SSL certificate with end date 2015.
![screen shot 2018-08-31 at 12 00 10](https://user-images.githubusercontent.com/1338800/44906602-a93bff00-ad15-11e8-909f-0002f11d562f.png)
![screen shot 2018-08-31 at 12 00 19](https://user-images.githubusercontent.com/1338800/44906603-a93bff00-ad15-11e8-8a2c-1e18b449f580.png)

**Comment by science695** [comment]
@feyyazesat This issue is about adding your own Certificate Authority.

Your issue would seem to be related to Postman Proxy, or the site you are reaching having an expired Certificate. I would recommend you make a new issue.

**Comment by tbennett6421** [comment]
@numaanashraf Can we get an update? I don't see this on the project roadmap on your team's trello board #3152

**Comment by numaanashraf** [comment]
@tbennett6421 We don't have an ETA on this yet. We'll share an update as soon this lands on our near term roadmap. Thanks for the patience.

**Comment by MetalJacx** [comment]
Any update on this. Though with SSL certification verification off works for most api. I have now run into an issue where the API will not accept non ssl cert verification. My cert is accepted as trusted root on my system but postman refuses to leverage or see this cert.

**Comment by xalimar** [comment]
This is basic SSL validation, this needs to be added to your roadmap.  Please don't contribute to users thinking it is OK to disable certificate validation.

**Comment by nolimitdev** [comment]
It is first time I installed Postman but Im wondered that Postman does not use system certificate store and does not enable adding own CA certificate. Disabling SSL verification is not acceptable solution.

**Comment by slm0n87** [comment]
+1 on Postman for Linux

**Comment by Zer07even** [comment]
We need this +1 Postman for Linux

**Comment by codenirvana** [comment]
We've added this on our Canary (`version: 7.1.0-canary01`) channel https://www.getpostman.com/canary

![Screenshot 2019-03-28 at 12 04 57 PM](https://user-images.githubusercontent.com/4865836/55135458-bd33cc00-5151-11e9-9088-39d8545fd5e7.png)

When set, the well known "root" CAs will be extended with the extra certificates in the file. The files should consist of one or more trusted certificates in PEM format.
Will update the thread once we release this on our stable channel.

**Comment by xalimar** [comment]
> We've added this on our Canary (`version: 7.1.0-canary01`) channel > When set, the well known "root" CAs will be extended with the extra certificates in the file. The files should consist of one or more trusted certificates in PEM format.
> Will update the thread once we release this on our stable channel.

Fantastic! I can work with this, although consider supporting PEM file or directory (and reading all CA PEM certs in a directory).  Supporting a directory means I can specify /etc/ssl/certs which has all of the trusted CA certs (stock + custom).

**Comment by shamasis** [comment]
> Fantastic! I can work with this, although consider supporting PEM file or directory (and reading all CA PEM certs in a directory). Supporting a directory means I can specify /etc/ssl/certs which has all of the trusted CA certs (stock + custom).

@xalimar -That's a very good suggestion! It would have real bad performance hit if we support this. Imagine reading all certs on every request + verify if they are valid + concat them (yeah, NodeJS doesn't support any other way), etc etc. Reading once and not re-reading isn't good either.

**Comment by codenirvana** [comment]
We've added support for this in the latest Postman App (v7.0.9) 🎉

**Note:** The single CA file should consist of one or more trusted certificates in PEM format, this means you can append as many CA certificates as you want to the single file.

**Comment by Daniel15** [comment]
Thank you @codenirvana! 

One small suggestion: Could the "There was an error connecting to [...]" error message mention this feature? Currently it just suggests turning off SSL cert validation.

**Comment by U31664** [comment]
unable to get local issuer certificate

Any update with this? 

You are up to date! Postman v7.16.1 is the latest version.

**Comment by neilpalima** [comment]
I am experiencing this issue. A subdomain uses a wild card ssl. It can be accessed on chrome and stating the certificate is valid. Disabling ssl cert validation makes it accessible but I think this is just a work around.

**Comment by vizzyks** [comment]
I am using Canary 7.26.3 and was expecting that this time postman runs with "SSL certificate verification" ON after I added the certificate(.PEM) to it. But it did not. 
Looks like Postman is still not able to verify the Private certificate, whereas Chrome is able to. 
From the discussion above it appears that this issue was taken care in Canary, is it otherwise?

**Comment by jadell** [comment]
Is there a reason certs need to be added to Postman specifically? Why doesn't Postman use the OS certificate store?

**Comment by epritchardcw** [comment]
Couple years later and it still doesn't make any sense that postman can't use the local trusted certificate store.
