### ISSUE TITLE
Slash is Missing when Importing Collection with Base URL as Parameter

### ISSUE THREAD

**Issue by AmrEldib** [a85/POSTMan-Chrome-Extension#3292]
## App Details:
```
Postman for Chrome
Version 5.0.2
win / x86-64
Chrome 59.0.3071.115
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:
__I've encountered this bug recently.__
 2. Expected behaviour:
__I expect URLs to have double slashes after protocol when importing a collection. Ex: http:// and not http:/__
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
__N/A__
 4. Screenshots (if applicable)
![image](https://user-images.githubusercontent.com/769272/28431570-9d03c3d4-6d39-11e7-8cbb-0cdff9737243.png)
![image](https://user-images.githubusercontent.com/769272/28431592-ac38b148-6d39-11e7-9155-8cf54d4031ab.png)

## Steps to reproduce the problem
1. Create a request where the base URL (server name) is a parameter using `:server`. 
2. Save this request to a collection.
3. Export collection
4. Delete collection from postman
5. Import collection
6. Each request that has the base URL as a parameter will now have the URL be: `http:/:server/` instead of `http://:server/`  

## Notes
- Any other request that includes a parameter that isn't the base URL will work fine. See the request titled "With server name" in the attached collection.
- I inspected the exported collection and found that the export is fine, the problem seems to be in the import.
- Here's a collection for testing with two requests: one with a server name and one without a server name. Note: the file was renamed to .txt to allow for uploading.
[Simple Collection.postman_collection.json.txt](https://github.com/postmanlabs/postman-app-support/files/1163270/Simple.Collection.postman_collection.json.txt)

**Comment by kamalaknn** [comment]
Hey @AmrEldib 

Thank you for reporting this. We have tracked the issue to [`postman-collection-transformer`](https://github.com/postmanlabs/postman-collection-transformer). We will work on a fix for this.

Also, the path variable syntax `:variable` is deprecated in favor of the newer syntax `{{variable}}`. In the meantime, you can switch to the newer syntax and continue working while we fix this.

**Comment by kunagpal** [comment]
@AmrEldib Did the suggested fix work for you?
