### ISSUE TITLE
Console logs print headers which has already been disabled in the case.

### ISSUE THREAD

**Issue by S0im** [a85/POSTMan-Chrome-Extension#3293]
## App Details:
Postman for Windows
Version 5.1.0
win32 6.1.7601 / x64

## Issue Report:
Console logs print headers which has already been disabled in the case. See this，I disabled the "bug",and it still appeared in the log,  but in fact postman didn`t sent the "bug".

![console bug](https://user-images.githubusercontent.com/25290478/28452135-c15cbdb8-6e23-11e7-955a-52858563529e.jpg)

1.disabled a header in the case。
2.open the console log
3.send a request 
4.observe the headers in the console

**Comment by prashantagarwal** [comment]
@S0im Thanks for reporting this. I was able to reproduce this. We will get this fixed soon.

**Comment by kunagpal** [comment]
@S0im This should have been fixed in the 5.2.0 release, feel free to reopen if your issue persists. Thanks! 😄
