### ISSUE TITLE
Postman code not generating swift code for post request

### ISSUE THREAD

**Issue by mugrufis** [a85/POSTMan-Chrome-Extension#3294]
I am doing a post request using postman to get the code snipet.Doing a post request with Body->raw->JSON(application/json) and passing as body empty brackets [] everything is working, I get a response from server and I can also generate a Swift snipet to use for my project.Doing the same as above, but instead of empty brackets passing a JSON inside, the postman request gets again a response from the server and everything works OK, aside from the fact that there is no code snippet for Swift. All other supported languages have their snipet, but Swift does not.When swift is preselected from previous call the dialog box is empty, and when selecting another language and going back to swift, the swift dialog box shows the snipet from the other language.Here is a copy of my passed-in JSON:
```
[
   {
    "quantity" : null,
    "id" : 3,
    "articleLocation" : {
      "article" : {
        "articleGroup" : null,
        "version" : 1,
        "state" : 0,
      },
      "id" : "SDGHKP2343244",
      "location" : "aaesdf",
      "stock" : "16.0"
    },
    "date" : null,
    "version" : 0,
    "user" : null
  },
  {
    "quantity" : null,
    "id" : 4,
    "articleLocation" : {
      "article" : {
        "articleGroup" : null,
        "version" : 1,
        "state" : 0,
      },
      "id" : "SDGSDF2343244",
      "location" : "sdgsdf",
      "stock" : "12.0"
    },
    "date" : null,
    "version" : 0,
    "user" : null
  }
]
```

**Comment by prashantagarwal** [comment]
@mugrufis Thanks for reporting this. We are investigating this issue.

**Comment by abhijitkane** [comment]
@mugrufis Unable to reproduce this on Postman 7.x. If you're still seeing this, feel free to add a comment detailing exact steps to reproduce the issue (with screenshots, preferably).
