### ISSUE TITLE
[Chrome] Deactivated environment variable seen valid in scripts

### ISSUE THREAD

**Issue by rfonrouge** [a85/POSTMan-Chrome-Extension#3295]
## App Details:
Postman for Chrome
Version 5.0.2
win / x86-64
Chrome 59.0.3071.115

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:
No idea, just started working with scripts.

 2. Expected behaviour:
When getting a deactivated environment variables (unchecked in Manage Environments window) with getEnvironmentVariable() or getGlobalVariable(), the value should be undefined. It is considered undefined in other places it is used (request url, body, etc.)

Note that I have not been able to found a method to get the actiavion status to bypass the issue. Anyway, it would not be convenient to check the value AND status everytime you get a environment/global variable.

## How to reproduce:
- Duplicate any request (for instance Request Methods/Get Request) and set the following test script:
```
var globalVar = postman.getGlobalVariable("test-global-var");
tests["test-global-var is defined"] = (globalVar);
```
- Create a "test-global-var" global variable with value "test"

First run to check the global variable is defined
- Run the test.
=> The test "test-global-var is defined" is Green

Second run to show the global variable is defined even when deactivated
- In the Environment Management window, deactivate/uncheck the "test-global-var" variable 
- Run the test.
=> The test "test-global-var is defined" is green, but should be red (since we have just deactivated the variable)

You could make more complicated tests to ensure the deactivated variable is not taken into account in the request body...

**Comment by sdnts** [comment]
Hi @rfonrouge, I was able to reproduce this on the Chrome app, we'll get this fixed.

However, this does not appear to be happening on the [native apps](https://getpostman.com/apps). can you try this out there? I'd recommend using the native apps anyway since Google will deprecate Chrome apps soon :)

**Comment by rfonrouge** [comment]
I've just installed the windows native app and it works fine. Thanks @madebysid :)
