### ISSUE TITLE
Sort by HTTP Method type

### ISSUE THREAD

**Issue by Ezilkannan** [a85/POSTMan-Chrome-Extension#3296]
It would be nice to have a "sort by request method type" option in the desktop app.

## App Details:
```
Postman for Mac
Version 5.1.1
OS X 16.6.0 / x64
```

**Comment by sdnts** [comment]
Hi @Ezilkannan, are you referring to requests within collections? If so, this would be weird to have, since requests inside collections have a defined order, so just sorting by method will mess with that.

Or are you looking for this in the history sidebar?

**Comment by Ezilkannan** [comment]
Hi @madebysid, I did refer to the requests within collections. It has a sort by name and sort by date option. I felt that a sort by request method would also be helpful. Or does the sort work only on the collections as a whole and not for requests within the collection?

**Comment by sdnts** [comment]
Ah indeed, the sort that you are referring to applies only to collections as a whole, not the contents, since the order of content is important.

**Comment by Ezilkannan** [comment]
I guessed so. Thanks for the clarification.
