### ISSUE TITLE
Unusual activity in postman history

### ISSUE THREAD

**Issue by jdsans** [a85/POSTMan-Chrome-Extension#3299]
Not sure but i'm seeing some get requests in my postman which i have no idea how they were made. I never made those requests and don't know the nature or purpose of requests but i'm seeing it in the postman. There's also request headers attached to those get requests. How and why?

![postman](https://user-images.githubusercontent.com/180413/28502511-ca8c9152-6fc1-11e7-945f-6db73c4302b9.jpg)

**Comment by sdnts** [comment]
@jdsans Can you open your Postman [sessions dashboard](https://app.getpostman.com/dashboard/sessions) and check if you have any sessions you do not recognise? I think you might be logged into some other app, which is where the history requests are made.

If you have sync enabled, I'd recommend checking if all collections are intact [here](https://app.getpostman.com/dashboard/collections/private?expand=1). If they are, just revoke all sessions and log in to the app again.
If you do not use Sync, just backup all your collections by heading over to Settings > Data > Export, then revoke all sessions.

If you still see unrecognised history items even after a session revoke, please let me know here and drop an email to help@getpostman.com

**Comment by jdsans** [comment]
@madebysid Thanks for your reply. I looked at my sessions history yesterday and have already revoked all my sessions. I use postman only on my PC, so i didn't see any active session in the sessions history besides the one i had opened. The strange thing is on the 18th i might have been working on my project and i see those localhost requests being made which are the only one's i ever made through postman but the bunch of other history requests seem vague. 

Although not sure i did that on the 18th but i remember installing intercepter around that time, not sure if that's something to do with those requests?

**Comment by sdnts** [comment]
Installing the interceptor wouldn't have anything to do with it, since the Interceptor doesn't log you in in any way. If you do not see any other sessions any more, no more weird history should appear anymore.

I wonder, were you experimenting with the Proxy? If you were, maybe those requests were captured?

**Comment by jdsans** [comment]
Nope don't use proxy. I'm always on direct connection. I'll keep any eye for any further such activity

**Comment by sdnts** [comment]
Awesome, I'm closing this, but please reopen if you see this again.
