### ISSUE TITLE
Postman Update 5.1.2 Failing

### ISSUE THREAD

**Issue by jlsinnott** [a85/POSTMan-Chrome-Extension#3301]
## App Details:

```
Postman for Mac
Version 5.0.2
OS X 16.6.0 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there?
Recently. I am trying to update my Postman app to 5.1.2
 2. Expected behavior: That the app will update
 
4. Screenshots (if applicable)
<img width="500" alt="screen shot 2017-07-24 at 11 32 52 am" src="https://user-images.githubusercontent.com/19391060/28531142-e89e3590-7063-11e7-9753-066353b0a3b2.png">

**Comment by sdnts** [comment]
Hey can you make sure that your Postman App is in the /Applications directory? We've seen this error get resolved after the app moves to /Applications.

**Comment by jlsinnott** [comment]
Moved it and the update was successful. Thanks for the quick reply!
