### ISSUE TITLE
Its very hard to recognize on which tab I am currently if there are multiple tabs opened.

### ISSUE THREAD

**Issue by ravibhagat** [a85/POSTMan-Chrome-Extension#3303]
Its very hard to recognize on which tab I am currently if there are multiple tabs opened.

**Comment by ravibhagat** [comment]
![image](https://user-images.githubusercontent.com/17745162/28536327-7f27968c-7064-11e7-842d-479e95296705.png)

**Comment by ravibhagat** [comment]
Please see above tabs, its really difficult to know which is current tab. please do some coloring to entire tab which is opened as of now.

**Comment by kamalaknn** [comment]
Hey @ravibhagat 

I can understand this could be painful for you while working with many tabs open.

I'm looping in our design team to this thread. We'll look into how we can improve this behavior.

**Comment by numaanashraf** [comment]
In the latest version of Postman, we highlight the active tab with an orange accent. Hope this helps with this issue.

![screen shot 2018-09-17 at 12 38 31 pm](https://user-images.githubusercontent.com/3295568/45609704-a6137380-ba76-11e8-8bd7-4032ffb433bb.png)

**Comment by ravibhagat** [comment]
Thanks Team, appreciate your efforts.
