### ISSUE TITLE
Same url is getting returned in the newman report though we see different urls in the newman while executing Postman collection for many iterations(15)

### ISSUE THREAD

**Issue by sravanisatharla** [a85/POSTMan-Chrome-Extension#3309]
Team,

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:
This was encountered recently, Same url is getting returned in the newman report though we see different urls in the newman while executing Postman collection for many iterations(15).
 2. Expected behaviour:
It should take different input data from input sheet and hit different urls

**Comment by sdnts** [comment]
Hi @sravanisatharla, the [Newman](https://github.com/postmanlabs/newman/issues) repository would be the correct place to create this issue :)
