### ISSUE TITLE
Json script error in different API's while running postman collection in newman  

### ISSUE THREAD

**Issue by sravanisatharla** [a85/POSTMan-Chrome-Extension#3310]
Issue:
Json script error in different API's while running postman collection in newman  

Steps to Reproduce:
1. Created a collection with different input data in the input json
2. Run the collection with input json in newman
newman run Collection_name.postman_collection.json -n 15 -d Input_P_S.json -e PD.postman_environment.json -r html,cli

3. Getting Json script error while running it for different API's though there's no error on the script.
i.e., when running the collection say api1 failed and api2 passed with json script error first time and when we run the collcetion again api1 is getting passed and api2 is failed.

So everytime its failing different API's though theres no error.

**Comment by sdnts** [comment]
Hi @sravanisatharla, can you create an issue over at the [Newman](https://github.com/postmanlabs/newman/issues) repository? This will make sure the correct people address your issue :)

As a side note though, a JSON script error usually means you're doing some sort of JSON.parse on a variable that isn't a string. If you're parsing the response body, can you make sure the body is what you expect?
