### ISSUE TITLE
Delete cookies programmatically

### ISSUE THREAD

**Issue by rj93** [a85/POSTMan-Chrome-Extension#3312]
I'm looking for a way to clear cookies between each test, I know I am able to do this via the GUI but I want to do it automatically in the pre-request scripts. I tried `document.setCookie = ...`, but `document` isn't defined. 

My current work around is to set the cookies into global variables, and use these variables in the header values, which allows me to set the values to empty strings at the beginning of each test.

**Comment by sdnts** [comment]
Hi @rj93, sorry about the delay here. This isn't possible right now, but we've been actively looking into this. I'm tagging this as a feature request, and will let you know here when it is out :)

**Comment by krogold** [comment]
Hi, I'm trying to find a workaround in order to neutralize a cookie returned by the server. 
Is there a way to get the cookie object ? 
currently, if I use pm.cookies, I get an array that contains the cookie, I can even erase it with pm.cookies.clear() but it doesn't erase the cookie (though pm.cookies array is empty). 

I wonder how to get the object (pm.cookies[0] does not work) so I could modify its expiry date, for instance.

thank you

Alexandre

**Comment by krogold** [comment]
I found a way to get the cookie object, however the "expires" property is not available  :(
I used pm.cookies.idx(0)
is it possible to make it available and writeable ?

well, anyway it is useless, as modifying a propertie through pm.cookies methods is not reflected in postman (ie. I changed the cookie name, I can see it changed when I log pm.cookies but when I open the "Manage Cookies" window in postman, there is no change reflected ...

**Comment by kamalaknn** [comment]
@krogold the `pm.cookies` now allows you read and set cookies. We will be extending it to add more functionality to cookies.

**Comment by krogold** [comment]
Ok, but does it concerns every cookie (send and received ?) because when I use it to modify a received cookie, I can see the change in pm.cookies but when I enter the cookie management window (on the right hand side of postman windows app) I don't see any update in the concerned cookie ?

**Comment by Cehnee** [comment]
Hi, is there any update on this issue, or others like this (https://github.com/postmanlabs/postman-app-support/issues/1228, I'm looking at you)? As it happens, we had no other option but to turn away from using Postman for anything automated in our company, this is a make-or-break feature for us.

**Comment by elistemann** [comment]
@kamalaknn the issue described by @krogold still exists, at least in the native OSX app. It seems that the [CookieList](http://www.postmanlabs.com/postman-collection/CookieList.html) is not linked to the cookies in the CookieManager. For example if i have a request which sets a cookie "xy" i can successfully run this test:
```
tests["received cookie"] = pm.cookies.has("xy") === true
pm.cookies.clear()
tests["removed cookie"] = pm.cookies.has("xy") === false
```
But when i look into the CookieManager it's still there. Also pm.cookies.add or pm.cookies.append doesn't seem to have any effect, neither in the CookieManager nor when i do
```
pm.cookies.add({"test.cookie": "test"})
console.log(pm.cookies.toObject())
```
It contains the cookie set by the request, but not the added cookie.
Maybe i'm just using it wrong. Could you paste an example how to add / edit a cookie?

**Comment by EricThieme** [comment]
@elistemann same problem with windows version 5.4.1 I tried out your tests. They worked, but the cookies remained as I could see in the reaction of my backend in the following test.

**Comment by nicolattuso** [comment]
@kamalaknn I have the same problem, I can't automate things properly while this feature is missing. I am using version 5.5.0 on Linux.

**Comment by Iliev88** [comment]
+1

**Comment by marvader** [comment]
+1

**Comment by gctommy** [comment]
:heavy_plus_sign: 💯

**Comment by Aidenir** [comment]
+1 for this as well. I get that cookies were an issue when postman was built as a chrome extension, but now I can't see why everything regarding cookies is such a PITA.

**Comment by cyrfer** [comment]
+1 to be able to remove cookies with something like a pre-request script, or a setting to ignore them for a specific domain.

**Comment by tomheisner** [comment]
+1

**Comment by fedelibar** [comment]
+1

**Comment by Mefffiu** [comment]
+1

**Comment by isaru66** [comment]
+1

**Comment by JulienBarlet** [comment]
+1

**Comment by slaout** [comment]
+1

**Comment by clavergne** [comment]
+1

**Comment by bmdatl** [comment]
+1

**Comment by markusfoss** [comment]
+1

**Comment by pmartella** [comment]
+1

**Comment by GuillaumeTroyon** [comment]
+1

**Comment by dar88rm** [comment]
+2

**Comment by aiannello** [comment]
+1

**Comment by enzod-lgtm** [comment]
+1

**Comment by Tyson1986** [comment]
+1

**Comment by Dnowakdn** [comment]
+1

**Comment by grandcamel** [comment]
+1

**Comment by LordJohn42** [comment]
Add this feature, please.

**Comment by kknd113** [comment]
+1

**Comment by kudinov-fedor** [comment]
+1

**Comment by mali-eg** [comment]
+1

**Comment by AnthonyCC** [comment]
+1

**Comment by richja** [comment]
+1

**Comment by superheri** [comment]
+1 This is very needed in my case...

**Comment by benreyle** [comment]
+1

**Comment by rishulmatta** [comment]
+1

**Comment by AlexPanchenko** [comment]
+1

**Comment by SiriusED** [comment]
+1

**Comment by ncpre** [comment]
+1

**Comment by regisbsb** [comment]
+1 💯

**Comment by TarasMelnyk** [comment]
+1

**Comment by ravikanth39** [comment]
+1

**Comment by oussama2507** [comment]
+1

**Comment by five-star-reveiws** [comment]
+1

**Comment by diegolealco** [comment]
+100

**Comment by arifioreac** [comment]
+1

**Comment by simonhardingforgerock** [comment]
+1

**Comment by nakanu18** [comment]
+1

**Comment by rgasioro** [comment]
+10
I am surprised that this is not possible now (programmatically clearing Cookie Manager's cookies.)
This is such an important feature for automated tests.

**Comment by liushilive** [comment]
+1
这是一个很重要的功能。

**Comment by LeoLiangJin** [comment]
+1,    My situation is that I need to login in different circumstances, but they  doesn't help set-cookies when response. It causes I need to set cookies by myself. It really helps if modification on pm.cookies reflects on cookie manager.

**Comment by whowantsahero** [comment]
+1, this feature would be extremely helpful for my company's automated tests.

**Comment by ratelgogo** [comment]
+1

**Comment by arnabitsme** [comment]
a

**Comment by yabols** [comment]
+100

**Comment by HarryF514** [comment]
+1
+1
+1

**Comment by Doogiemuc** [comment]
+1   please implement this.  I'd also need it.

**Comment by florimon** [comment]
+1 Please implement this! Not having this hinders automation of a postman collection.

**Comment by paolocarrasco** [comment]
+1

**Comment by rgasioro** [comment]
Still in need of this feature... any update from the dev team?
Several users have already mentioned it, this is hindering test automation since a) there are situations where you don't want to send cookie, especially when re-running tests, b) old, expired cookies cause problems

**Comment by nidkil** [comment]
Any chance this will be added soon?

**Comment by Nyjaski** [comment]
+1

**Comment by abhijitparida** [comment]
+1 please implement

**Comment by pabx06** [comment]
+10

**Comment by eduandrade** [comment]
+1

**Comment by rgasioro** [comment]
Is anyone from the development team reading this? No matter how many +1 we add, there's no response.

**Comment by abhijitparida** [comment]
Keep +1ing 😆

**Comment by regisbsb** [comment]
@kunagpal

**Comment by kunagpal** [comment]
Hey folks! We're currently in the midst of tracking/organizing all such runtime feature requests to better understand and prioritize changes. A better view of the same can be seen from our GitHub project board here: https://github.com/postmanlabs/postman-app-support/projects/32#card-13099109. In the meantime, feel free to express interest in the feature request of your choice by leaving a 👍against the opening statement in this thread. This helps us understand what our users want most. (Do avoid +1 comments, as they merely contribute to noise 😞).

**Comment by regisbsb** [comment]
@kunagpal having said that all the other proposals don't look as simple as a this request and gather much less attention from the public. This one also tracks back a year plus ago.

**Comment by rgasioro** [comment]
Thanks for the reply and ditto to what @regisbsb wrote.

**Comment by andreyvolodko1996** [comment]
+1

**Comment by andreyvolodko1996** [comment]
this issue was created more than a year ago. 
and there are a lot of problems because of this issue. 
why developers do nothing... I just cannot understand.

**Comment by rgasioro** [comment]
I agree, this is the ONLY thing that prevents me from fully automating my tests. Real pain and inconvenience.

**Comment by andreyvolodko1996** [comment]
yea. I wrote to postman support a lot of times, but it's still not resolved.

**Comment by andreyvolodko1996** [comment]
hi there

can you tell me, how do you get your cookies that are sent to the cookie
manager and prevents you to automate tests?

**Comment by kopach** [comment]
Hi there. Until this issue is still not fixed, @rj93, could you please explain in more details your workaround, please?

**Comment by rgasioro** [comment]
In my case, I have to go to Cookie Manager and manually delete all cookies before each set of tests or after long period of inactivity.

**Comment by kopach** [comment]
Thanks @rgasioro, this way I know. But this is a manual way. As far as I understood from @rj93's response - there is some automated workaround by using global variables and headers.

**Comment by andreyvolodko1996** [comment]
Hi again
in my case, I have to send GET request to obtain
request_verification_token, after that I need to send POST request to
obtain my access_token (cookie is equal to access token in my case) (I past
my username, password and  request_verification_token in the request body).
and when I perform all this actions, cookies fall into cookie manager. but
I have several roles in my website, and I need to use several credentials.

ok, so. I have found two to ways to solve this problem.
First: 1. In Settings you need to switch off Automatically follow redirects.
[image: image.png]
2. Then you need to write your requests in Tests section so that the main
request doesn't work. It's confusing) but look at the screenshot
3. Further you can add the value of cookie to the global/environment
variable and use it wherever you want and cookie don't fall into cookie
manager
[image: 2018-11-29_17h33_23.jpg]
and with the help of this method you just need to perform, for example 3
requests for every role, and use this credentials all day.


and the Second way is to just to use newman for testing and further
jenkins, cause it's more convenient to use.

И еще вопрос, может ты русский?)

**Comment by andreyvolodko1996** [comment]
Hi again
in my case, I have to send GET request to obtain
request_verification_token, after that I need to send POST request to
obtain my access_token (cookie is equal to access token in my case) (I past
my username, password and  request_verification_token in the request body).
and when I perform all this actions, cookies fall into cookie manager. but
I have several roles in my website, and I need to use several credentials.

ok, so. I have found two to ways to solve this problem.
First: 1. In Settings you need to switch off Automatically follow redirects.
[image: image.png]
2. Then you need to write your requests in Tests section so that the main
request doesn't work. It's confusing) but look at the screenshot
3. Further you can add the value of cookie to the global/environment
variable and use it wherever you want and cookie don't fall into cookie
manager
[image: 2018-11-29_17h33_23.jpg]
and with the help of this method you just need to perform, for example 3
requests for every role, and use this credentials all day.


and the Second way is to just to use newman for testing and further
jenkins, cause it's more convenient to use.

**Comment by rgasioro** [comment]
My problem is that we use dynamic cookie names, so I never know what the name will be.

**Comment by kopach** [comment]
Hi @andreyvolodko1996. Unfortunately screenshots you've added doesn't show up, so it's not really clear what is your first workaround. Could you edit your comment and update screenshots? And as for second workaround - [newman](https://www.npmjs.com/package/newman) also stores cookies between requests within same collection, so not sure how does it work for you.

**Comment by andreyvolodko1996** [comment]
if requests in the contractions locates in separate folders, Newman doesn't
store cookie.

**Comment by kopach** [comment]
Unfortunately it doesn't work for me in this way. Anyway, could you, please, describe your step 2 from first workaround, please?
>2. Then you need to write your requests in Tests section so that the main
request doesn't work. It's confusing) but look at the screenshot

Could you share, please, some code example you put in Tests section? And what do yo put as url for main request?

**Comment by kopach** [comment]
Thank you @andreyvolodko1996 a lot. I finally managed to execute multiple requests at once without cookies sharing. The workaround with separate folders works for me now. As it appeared the key thing for this workaround to work - was to put cookies sensitive requests in separate **root** folders inside collection. What I was doing wrong at first - was separating request in sub-folders inside another nested folder. So, now I can execute multiple requests correctly from newman as well as from postman's Collection Runner.

**Comment by andreyvolodko1996** [comment]
that sounds great)
should still I explain you my step 2 from first workaround or that's enough
for you to run your collections in postman?

**Comment by kopach** [comment]
For me this is totally enough, at least for now :). Thanks once again 👍

**Comment by andreyvolodko1996** [comment]
cool

can you tell me, you use Jenkins either on the localhost or on the server?

**Comment by kopach** [comment]
I don't use newman on jenkins, there is no need for this in my case yet. I do run my postman collection locally for now.

**Comment by andreyvolodko1996** [comment]
oh, got it. I was thinking you use jenkins, but as I understood, you just
run your collections in cmd with the help of newman

**Comment by germyjen** [comment]
I need to be able to clear an auth cookie between tests, is there a way to do that without manual intervention? The cookies seem to persist even between folders and I'm at a loss.

**Comment by andreyvolodko1996** [comment]
Yes, with the help of Newman, but it is not so good way if we are talking
about cookie.
Tell me please the whole way you get your cookie? Where do you take it?

**Comment by andimueller** [comment]
**+1**

**Comment by jerret-halter** [comment]
+1

**Comment by Hesamedin** [comment]
+1

In addition to that, I would like to set Environment programatically, too. Please look at my question in stackoverflow if the feature is already there. Thanks.

https://stackoverflow.com/q/53766614/513413

**Comment by donsting** [comment]
The single folder workaround works for me using newman if I set the cookie to a environment var... however, my reporting does not give an overall picture.  I really wish this would get fixed.

**Comment by ejerskov** [comment]
+1

**Comment by kthulsidoss** [comment]
+1

**Comment by WendallHersh** [comment]
following

**Comment by jshanman** [comment]
following.

Need to be able to 
1. override sent cookies in pre-request after all hard coded headers are set, variables replaced, and cookie manager cookies added.
2. set or clear all cookie values (including ones just added via Set-Cookie response from the server) in post-request test that affects the cookie manager cookies for subsequent requests/tests in different requests to the same domain.

**Comment by darukavishnikov** [comment]
+1 to this problem. 
Thanks in advance

**Comment by jamesvillarrubia** [comment]
+1

**Comment by diehardcoder007** [comment]
Hi All

I am still not able to identify the solution for clearing the cookie between two subsequent run of a collection via NewMan.
Can anyone help me with the solution if available

Thanks

**Comment by kthulsidoss** [comment]
@diahardcoder007 could u try this top of the test script
const cookies = pm.response.headers.all().filter(headerObj => headerObj.key === 'Set-Cookie').map(headerObj => headerObj.value);
pm.environment.set('cookies', cookies.join(';'));

**Comment by aisen0921** [comment]
> 
> @diahardcoder007 could u try this top of the test script
> const cookies = pm.response.headers.all().filter(headerObj => headerObj.key === 'Set-Cookie').map(headerObj => headerObj.value);
> pm.environment.set('cookies', cookies.join(';'));

@kthulsidoss 
It's still not working.

**Comment by freerider7777** [comment]
What the... Such simple issue exists for 2 years...

**Comment by brettsamann** [comment]
It's also a problem for me that I can't programmatically control what happens in the cookie manager, or at the very least disable the "Set-Cookie" functionality. I know we have pm.cookies.get() and pm.cookies.clear() but as stated before the "clear" doesn't actually clear the cookies from the cookie manager. I have no idea why there's a .get and not a .set function - almost every function with a .get has a .set.

**Comment by codenirvana** [comment]
Hello everyone.
It took us a while but, we are currently adding support for programmatic access of cookies. 🎉 
You would be able to programmatically manipulated cookies for the whitelisted domains (configurable).

Will post about the finalized API and its availability in our canary and stable channel soon!

**Comment by arnaudlacour** [comment]
Awesome that you're addressing this!
Don't take this as an indication of impatience but can you give us a feel for when you expect it to drop?

**Comment by codenirvana** [comment]
We've added this on our Canary (`v7.3.5-canary04`) channel https://www.getpostman.com/canary

We are currently working on documenting this feature and the sandbox APIs.
Meanwhile, here's the brief to get started with this on Canary:

### Whitelisting Domains
First, you need to whitelist the domains for which you want programmatic access to be enabled. Add domains under the new "Whitelist Domains" settings (bottom left of the existing cookie manager).

<img width="977" alt="1" src="https://user-images.githubusercontent.com/4865836/62236253-5a4a8e00-b3ec-11e9-9065-e46f49a226c0.png">
<img width="715" alt="2" src="https://user-images.githubusercontent.com/4865836/62236284-66cee680-b3ec-11e9-9321-97a19ece1223.png">

> **Pro Tip:** To whitelist a domain and all its subdomains, use `*.domain.com`

### Sandbox APIs
We added support for `set`, `get`, `getAll`, `unset`, and, `clear` methods on cookies for the given URL. All these methods are accessible using the new **CookieJar** pm API.

**Accessing the CookieJar**
```js
const jar = pm.cookies.jar();
```

> **Note:** All the CookieJar methods are asynchronous.
It throws access denied error for non-whitelisted domains cookie access.

**CookieJar.set**
There are three ways to set a cookie.
```js
const jar = pm.cookies.jar();

// using cookie name and value
jar.set('http://example.com', 'token', '123456', function (error, cookie) {
  // error - <Error>
  // cookie - <PostmanCookie>
  // PostmanCookie: https://www.postmanlabs.com/postman-collection/Cookie.html
});

// using set-cookie string
jar.set('http://example.com', 'token=123456; Path=/; HttpOnly;', function (error, cookie) {
  // error - <Error>
  // cookie - <PostmanCookie>
});

// using PostmanCookie or its compatible object
jar.set(pm.request.url, { name: 'token', value: '123456', httpOnly: true }, function (error, cookie) {
  // error - <Error>
  // cookie - <PostmanCookie>
});
```

**CookieJar.get**
Get the cookie value with the given name.
```js
const jar = pm.cookies.jar();

jar.get('http://example.com', 'token', function (error, value) {
  // error - <Error>
  // value - <String>
});
```

**CookieJar.getAll**
Get all the cookies for the given URL.
```js
const jar = pm.cookies.jar();

jar.getAll('http://example.com', function (error, cookies) {
  // error - <Error>
  // cookies - <PostmanCookieList>
  // PostmanCookieList: https://www.postmanlabs.com/postman-collection/CookieList.html
});
```

**CookieJar.unset**
Remove single cookie with the given name.
```js
const jar = pm.cookies.jar();

jar.unset(pm.request.url, 'token', function (error) {
  // error - <Error>
});
```

**CookieJar.clear**
Remove all the cookies for the given URL.
```js
const jar = pm.cookies.jar();

jar.clear(pm.request.url, function (error) {
  // error - <Error>
});
```

> **Pro Tip:** Use `pm.request.url` for current request URL

Everyone, please try it out and share the feedback.
Will update the thread once we release this on our stable channel.

**Comment by bagrip** [comment]
I am still seeing that same JSESSIONID is being used

**Comment by andreyvolodko1996** [comment]
When the request returns access_token, this access_token is sent to the
Cookie manager, and these new methods are not able to get/set/clear/unset
this access_token. This is the problem. Unfortunately, the problem with
cookie manager is not resolved(

**Comment by andreyvolodko1996** [comment]
maybe it;s connected with the fact, that some websites are using two types
of cookies.
One for the registration and after that the user receives second cookie
(access_token) using first cookie.

**Comment by JohnArrowwood** [comment]
There was a note about this being implemented in 7.3.5-canary.  I'm running 7.5.0 stable.  I still can't delete cookies.  Has this feature been release to stable yet?

**Comment by FBO-Testing** [comment]
I tested the deletion of cookies in V7.6.0 canary05 and it works very well.
when can the function be available in a stable version?

**Comment by andreyvolodko1996** [comment]
it still doesn't work if there are two cookies for one domain. It just
deletes one cookie and leaves another. Maybe it's only in my case.

>

**Comment by codenirvana** [comment]
We've added support for programmatic cookie access in the latest version of the Postman app (v7.6.0). Refer https://github.com/postmanlabs/postman-app-support/issues/3312#issuecomment-516965288 for more details.

**Comment by codenirvana** [comment]
> it still doesn't work if there are two cookies for one domain.

@andreyvolodko1996 can you file a separate issue for this?

> when can the function be available in a stable version?

@FBO-Testing @JohnArrowwood Shipped in v7.6.0. 🎉

**Comment by andreyvolodko1996** [comment]
Where should I file this issue ?

**Comment by FBO-Testing** [comment]
Thanks for the info @codenirvana , that sounds promising ;-)

**Comment by MackeyG** [comment]
Solved my issue when working with AWS cognito to obtain multiple oauth tokens

**Comment by bagrip** [comment]
@codenirvana This is working fine in Postman and Newman and having issues with Nodejs, throwing below error

**jar.clear is not a function                                                                                                                                                  at test-script**

**Comment by dktsni** [comment]
Hi @codenirvana !

Thx for the addition of the `pm.cookies.jar()` API, it helps a lot ! 🎉 

I have a second question regarding this, is there any way to add the whitelist element through a script or an environment file ? The purpose here is to delete the cookies in our tests when they're launched _via_ newman, but we need to whitelist automatically the URLs.

dktsni

**Comment by codenirvana** [comment]
Hey @dktsni, there's no need to whitelist hostname in Newman and Monitoring for programmatic cookie access because unlike the Postman app they don't have a shared cookie store.

**Comment by dktsni** [comment]
I just upgraded our newman version to 4.5.5, and it works now, guess that we use a version which doesn't include your fix.
Thanks !

**Comment by swasthik8** [comment]
I have a scenario where i need to clear cookies after a Request, but when i run the Collection, Cookie gets stored and following Requests will fail as it expects loggedIn=false. ( because of the cookies stored)

i used this script , still not able to resolve . can someone help me here





const jar = pm.cookies.jar();
jar.getAll(pm.request.url, function (error, cookies) {
  // error - <Error>
  // cookies - <PostmanCookieList>

});

jar.clear(pm.request.url, function (error) {
  // error - <Error>
});

**Comment by vikiCoder** [comment]
@swasthik8 Make sure that you have whitelisted the domain of request URL (`pm.request.url`) as suggested in this comment: https://github.com/postmanlabs/postman-app-support/issues/3312#issuecomment-516965288

> First, you need to whitelist the domains for which you want programmatic access to be enabled. Add domains under the new "Whitelist Domains" settings (bottom left of the existing cookie manager).

**Comment by swasthik8** [comment]
@vikiCoder i did whitelisted the request url, sill its storing the cookies and following calls fail.
i tries in newman aswell, still same . not able to proceed , can someone help

![Screenshot 2020-09-27 at 3 26 55 PM](https://user-images.githubusercontent.com/51586332/94362037-29d8af80-00d6-11eb-85d1-ef244b4d929c.png).

@codenirvana 

![Screenshot 2020-09-27 at 3 32 45 PM](https://user-images.githubusercontent.com/51586332/94362121-c00cd580-00d6-11eb-9c7d-65136266a7ac.png)

in the above newman ss, loggedIn was supposed to be false but due to the cookies strored from the previous calls. request is failing

**Comment by ulayera** [comment]
This only works if the url has no variables, as they are being interpolated just before the request is sent.

Here if anyone gets to this issue just as me, let's say url is `https://{{myVar}}/someUri`
```
const jar = pm.cookies.jar();
pm.request.url.host = [pm.environment.get("myVar")];
jar.clear(pm.request.url, (error) => {
    if (error)
        console.error(error);
});
```

**Comment by rufreakde** [comment]
Tried to use @ulayera sugestion but it did not seem to work in my scenario:
url: `{{myVar}}/test/discovery?entityID={{myVar}}`

```
const jar = pm.cookies.jar();
pm.request.url.host = [pm.environment.get("myVar")];
jar.clear(pm.request.url, (error) => {
    if (error)
        console.error(error);
});
```
In the end I constructed the url myself with string template literals.

pm.request.url was somehow always empty `""`

**Comment by elburro1887** [comment]
I also can't get it to work. I have whitelisted the domain  the cookiejar outputs the cookies of the domain correctly, but i cannot delete them.

**Comment by emreeay** [comment]
Hitting the same issue as @elburro1887 and @swasthik8 . I noticed that, if the cookie has "httpOnly" or "secure" header, you can't delete them via script. `jar.clear` clears all the cookies except these httpOnly and secure ones. 

I think this is a bug. If this is intended, there should be a setting in Postman to activate or disable it, I guess.

**Comment by in-op** [comment]
I'm also hitting the same issue as @swasthik8. I can run my tests individually just fine, with the pre-request script (either in each test individually, or in the collection as a whole) working as intended. When I run the collection as a whole it persists the cookies.

**Comment by alsgeek** [comment]
There is a new option in postman settings where in we can disable cookie jar that in turn disables cookies like jsessionid from getting loaded while running a request call (Post/Get/PUT). 
![image](https://user-images.githubusercontent.com/32621481/148445024-1c989aa0-f8d3-4627-a26d-0a32fd239468.png)
This option is available for for each request call. the  other way to add this is:

"protocolProfileBehavior": {
				"disableCookies": true
			},
Adding this to your collection.json would disbale the cookies such as JSESSIONID, etc.

**Comment by rufreakde** [comment]
> There is a new option in postman settings where in we can disable cookie jar that in turn disables cookies like jsessionid from getting loaded while running a request call (Post/Get/PUT). ![image](https://user-images.githubusercontent.com/32621481/148445024-1c989aa0-f8d3-4627-a26d-0a32fd239468.png) This option is available for for each request call. the other way to add this is:
> 
> "protocolProfileBehavior": { "disableCookies": true }, Adding this to your collection.json would disbale the cookies such as JSESSIONID, etc.

As a note here this option is really not that useful since this issue appears mostly on execution of a complete collection. And there you often need to execute specific requests in an order and reuse cookies. It can help for single requests but if you need a flow this is not very helpful.

A similar option on collection level:
Clear Cookies on Collection Run - True 

Would be much simpler.

**Comment by ttimt96** [comment]
Any solution to clearing HttpOnly Secure cookie after request?

**Comment by m3dbedb** [comment]
@alsgeek, where to add 

> "protocolProfileBehavior": {
> "disableCookies": true
> },
 to collection.json?
