### ISSUE TITLE
Scrollbars are very small

### ISSUE THREAD

**Issue by rsabirov** [a85/POSTMan-Chrome-Extension#3313]
## App Details:

```
Postman for Windows
Version 5.1.2
win32 10.0.15063 / x64
```

## Issue Report:
Scrollbars are very small. They are hard to hit by mouse. Especially on wide screens.

**Comment by sdnts** [comment]
Hi @rsabirov, we use default browser scrollbars everywhere. Can you try zooming in (Cmd+)? This will widen the scrollbars as well.

I'm closing this, but please reopen if you feel zooming in doesn't help.
