### ISSUE TITLE
download content is "undefined"

### ISSUE THREAD

**Issue by lhomme-a** [a85/POSTMan-Chrome-Extension#3314]
## Issue Description:
When i execute a request with a response contening a pdf file a message box ask me for a location for response.pdf
I select a repository and click Save.
The file is created but its content is only the word "undefined".

## App Details:

```
Postman for Chrome
Version 5.0.2
win / x86-64
Chrome 59.0.3071.115
```

**Comment by sdnts** [comment]
@lhomme-a I was able to save a PDF returned from a server with the correct contents. Can you make sure the PDF being sent from your server is correct?

**Comment by lhomme-a** [comment]
Hi

Here is a sample i can use to reproduce the issue.
For me the content of response.pdf is always undefined.
Therefore the body.length is 113897


De : Siddhant Sinha [mailto:notifications@github.com]
Envoyé : mercredi 26 juillet 2017 14:24
À : postmanlabs/postman-app-support
Cc : LHOMME Alain; Mention
Objet : Re: [postmanlabs/postman-app-support] download content is "undefined" (#3314)


@lhomme-a<https://github.com/lhomme-a> I was able to save a PDF returned from a server with the correct contents. Can you make sure the PDF being sent from your server is correct?

**Comment by MaximTovstashev** [comment]
Have the same issue. The pdf is definitely correct, as it can be saved by any other client.
Maybe it matters that the request uses POST method

**Comment by fuzzypantlets** [comment]
I am seeing the same issue. It is a POST that returns a pdf attachment:
content-disposition →attachment; filename="appId.pdf"
content-type →application/pdf
content-length →17042

It works in curl.

Version 5.1.3
win / x86-64
Chrome 60.0.3112.101

**Comment by sdnts** [comment]
Do you guys have any public endpoints I can try this with?

**Comment by fuzzypantlets** [comment]
I just tried a GET with the first pdf google showed me and it behaved the same:
GET http://www.rms.nsw.gov.au/documents/roads/licence/guide-to-driving-test.pdf

Pops up a save dialog with response.pdf which contains the word "undefined"

**Comment by sdnts** [comment]
@fuzzypantlets This confuses me even more, this downloaded fine for me. What version of the app are you on? Can you try a force update of all your Chrome extensions? Can you also try out our native apps and see if it is resolved there?

**Comment by lhomme-a** [comment]
The problem persists for me after a force update of Chrome extension. I cannot try with the native app because i am behind an authenticated proxy and i have the #2242 issue.

My version is  : 

Postman for Chrome
Version 5.1.3
win / x86-64
Chrome 60.0.3112.90

I use also  : Postman Interceptor 0.2.23

And  i repeat, i am behind an authenticated proxy. Maybe it matters.

**Comment by sdnts** [comment]
@lhomme-a On the latest native apps, you should be able to use the System proxy for calls by switching on the Global Proxy in `Settings > Global Proxy` and setting a system proxy. Can you try this out?

**Comment by lhomme-a** [comment]
With the native application, i need to manually add a *Proxy-Authorization* header to the request then the response.pdf is correct.
So the issue is only for the chrome extension.

**Comment by red15** [comment]
I've also encountered this, I did notice the `reponseBody` does contain the actual PDF data. (ChromeExtension)

Can also confirm exact same request works in "native" application.

**Comment by prashantagarwal** [comment]
I am closing this as Postman native app is behaving correctly. Also as we are deprecating chrome apps, we recommend everyone to move to our native apps.
