### ISSUE TITLE
Variable exported with "id" are duplicated.

### ISSUE THREAD

**Issue by sebastien-savalle** [a85/POSTMan-Chrome-Extension#3317]
When a collection (created with a previous version of postman) is exported, variables are export in an array. Each element is stored with at least an "id" and a "value". In that case, each variable is stored twice in the array.
```
"variable": [
   {
      "value": "",
      "id": "anId"
   },
   {
      "value": "",
      "id": "anId"
   }
]
```
With recent collection, the "id" is replaced by a "key". In that case, there is no duplicates.
```
"variable": [
   {
      "value": "",
      "key": "anId"
   }
]
```
## App Details:
```
Postman for Windows
Version 5.1.1
win32 10.0.15063 / x64
```

**Comment by sdnts** [comment]
Hi @ellavas! Thanks for reporting this. Can you tell me approximately which version of the app the faulty collection was created from? If I understood correctly, collections created from 5.1.2 and up do not misbehave, right?

**Comment by sebastien-savalle** [comment]
Hi, sorry but I have no idea of the version. Collection was created first in 2016.
And the previous export was in May. Collections were successfully exported.

**Comment by numaanashraf** [comment]
@ellavas This was an issue in an earlier version and we had fixed it in a later version. I had verified that the variable data is exported correctly in the latest version Postman v6.1.4.
