### ISSUE TITLE
Collapsible JSON

### ISSUE THREAD

**Issue by fabb** [a85/POSTMan-Chrome-Extension#332]
Would be awesome if POSTman also had collapsible JSON like the Advanced Rest Client Chrome extension.

**Comment by Ciwan1859** [comment]
Is this feature implemented yet? I am using Version 2.0.19 (packaged), I get a large JSON object (has complex nested lists). I'd like to collapse all. Is there a way I can do that?

**Comment by digitalmaster** [comment]
+1

**Comment by p-mcgowan** [comment]
in case anyone else ends up here as I did - #1257 has shortcuts for fold/unfold all: 
Alt-0 (Win) / Command-Option-0 (Mac) for 'fold all', and Alt-Shift-0 (Win) / Command-Option-Shift-0 (Mac)
