### ISSUE TITLE
pre-request script. request.data is not updating variables if it's passed to a function

### ISSUE THREAD

**Issue by manuelbcd** [a85/POSTMan-Chrome-Extension#3322]
## App Details:

```
Postman for Chrome
Version 5.1.2
win / x86-64
Chrome 59.0.3071.115
```
Using pre-request script to try to send a payload based hash into a header.
The behaviour is really confusing me.

// The value will contain the request data WITHOUT parsing the variables
var a = btoa(request.data);

// The value will contain the request data perfectly parsed (final payload).
var a request.data;

Due to this behaviour I cannot use the request.data to calculate any hash to be placed into a header.
Is this a bug or may I use another function?

Thanks in advance

**Comment by sdnts** [comment]
Hi @manuelbcd! Thanks for reporting this. Since `request.data` is an object, you cannot do a `btoa` on it directly. This will actually try to convert the object into a string (which will be `[object Object]`), which will always yield the wrong hash. You should do: `btoa(JSON.stringify(request.data))` to make sure the object is stringified correctly.

You can verify all of this by doing a little test like so:

```
let value = request.data,
    stringifiedValue = JSON.stringify(request.data),
    hash1 = btoa(value),
    hash2 = btoa(stringifiedValue);
    
console.log('Value: ', value, '|| Hash: ', hash1, '|| Decoded: ', atob(hash1));
console.log('Value: ', stringifiedValue, '|| Hash: ', hash2, '|| Decoded: ', atob(hash2));
```

This isn't a problem with the app as such, but just JS behaviour. If you can confirm that using `JSON.stringify` solves your problem, I will go ahead and close this :)

**Comment by ghost** [comment]
Is this the same issue as what i seem to be getting on another post?:

_

> "Evaluator.js:235 TypeError: Cannot read property 'length' of undefined" 
> 
> Postman for Chrome
> Version 5.1.2
> win / x86-64
> Chrome 59.0.3071.115

> at eval (eval at loadCustomFile (Evaluator.js:231), <anonymous>:11:24)
> at eval (eval at loadCustomFile (Evaluator.js:231), <anonymous>:134:16)
> at r.loadCustomFile (Evaluator.js:231)
> at Evaluator.js:220

_

**Comment by manuelbcd** [comment]
@madebysid  Thanks for your answer but this is exactly the problem... stringify throws the same result.

ie.  var v = btoa(JSON.stringify(request.data));
output of "v" (after base64decode) -->  whatever: {{whatevervar}}, whatever2: {{whatevervar2}}

but  if I do:  var v = request.data;
output of "v" -->  whatever: "value1", whatever2: "value2"

If I use stringify only the result is ok
but  if I do:  var v = JSON.stringify(request.data);
output of "v" --> whatever: "value1", whatever2: "value2"

So btoa are not giving me the parsed value, only the "template". It does not matter if I stringify first. 

Any other idea?  Thanks in advance

**Comment by manuelbcd** [comment]
@madebysid  Actually I have done it by replacing the vars wildcards by myself, following the info from this issue  https://github.com/postmanlabs/postman-app-support/issues/1541

```
var strdata = request.data.replace(/{{(\w*)}}/g,function(str,key) {return environment[key]});
postman.setGlobalVariable("nti", btoa(strdata));

```
So finally it's working.
But I'm still wondering why it's so strange the behaviour when passing the request.data directly to btoa or hashing functions.

**Comment by sdnts** [comment]
@manuelbcd Sorry about the delay. Currently, the request data that you get using `request.data` does not auto-resolve variables, which is why you need to do a manual replace. I'm treating this as a feature request though, and will keep you updated on the progress!

**Comment by Misiu** [comment]
@madebysid any update on this?
I'm using variable in URL, so I must manually replace variable with it value.

**Comment by aggieben** [comment]
I used this in my pre-request script:

```js
function replaceVariables(templateString) {
    let tokens = _.uniq(templateString.match(/{{\w*}}/g))
    
    _.forEach(tokens, t => {
       let variable = t.replace(/[{}]/g, '') 
       let value = environment[variable] || globals[variable]
       templateString = templateString.replace(new RegExp(t,'g'), value)
    });
    
    return templateString
}
```

You can use this on any part of the request that uses environment variables.

**Comment by silentbrown** [comment]
I also tripped over this. Solution from @aggieben works well - maybe include this in postman-collection sdk>

**Comment by harryi3t** [comment]
@manuelbcd Request is not resolved in the pre-request script since the variables could be further modified there.
But you can use the `postman-collection` library within the scripts to resolve the request yourself.
Here's a sample script
```js
let sdk = require('postman-collection'),
    newRequest = new sdk.Request(pm.request.toJSON()),
    resolvedRequest = newRequest.toObjectResolved(null, [pm.variables.toObject()], { ignoreOwnVariables: true });
    
// prints the resolved request to console. Please check DevTools to see the structure
console.log({ resolvedRequest })
```

Does this solve your use case? If yes, then I can close out this issue :)

**Comment by shijialee** [comment]
> I used this in my pre-request script:
> 
> ```js
> function replaceVariables(templateString) {
>     let tokens = _.uniq(templateString.match(/{{\w*}}/g))
>     
>     _.forEach(tokens, t => {
>        let variable = t.replace(/[{}]/g, '') 
>        let value = environment[variable] || globals[variable]
>        templateString = templateString.replace(new RegExp(t,'g'), value)
>     });
>     
>     return templateString
> }
> ```
> 
> You can use this on any part of the request that uses environment variables.

`let value = environment[variable] || globals[variable]` 

can be changed to `let value = pm.variables.get(variable)`  which resolves variable defined in different scope automatically. 

see https://learning.postman.com/docs/writing-scripts/script-references/postman-sandbox-api-reference/#the-pm-object
