### ISSUE TITLE
Saved Examples in Postman Collection are not accurately matched for retrieval

### ISSUE THREAD

**Issue by enayetullah** [a85/POSTMan-Chrome-Extension#3323]
## App Details:
Postman for Linux
Version 5.1.2
linux 4.10.0-27-generic / x64

## Issue Report: Mocking Backend Services Using Postman
Since the beginning the saved Examples in Postman Collection are not accurately matched for retrieval:
Save Example with userid of 10:
GET https://xyz-api.com/api/prod/v2.01/users/**10**/reservations/227967/
with a saved example response body.

Using Postman API, to call the above mocked endpoint:
GET https://{{mockId}}.mock.pstmn.io/api/prod/v2.01/users/**10**/reservations/227967/
It will return the saved response. However, a modified version of this request:

GET https://{{mockId}}.mock.pstmn.io/api/prod/v2.01/users/**20**/reservations/227967/

will also return the above same response example. 

With 20 in /user/**20**/reservations, the postman should return nothing. As there is no example saved for this url.

**Comment by ratpik** [comment]
If an exact match is not found for a saved example request, then fuzzy matching is triggered which looks at similar urls in your saved examples. So the **10** in your URL is matched with **20** since both are numbers. If you expect mock to not do a fuzzy match in this case, pass something that is not a number like **AA** instead of **20**.

**Comment by enayetullah** [comment]
@ratpik That is not what I want. I want to save two examples, one with a URL as "GET https://{{mockId}}.mock.pstmn.io/api/prod/v2.01/users/**10**/reservations/227967/" and one with "GET https://{{mockId}}.mock.pstmn.io/api/prod/v2.01/users/**20**/reservations/227967/"

When I call "GET https://{{mockId}}.mock.pstmn.io/api/prod/v2.01/users/**20**/reservations/227967", it will just return the response saved for first URL (with **10**).

**Comment by ratpik** [comment]
@Rashid-007 - If you have two URLs saved like that, a call to mock the URL with **20** should be returning the URL with **20** (and **10** should return the one with **10**). The fuzzy matching happens only when you have one example saved with URL **10** and you are calling mock with a URL where the **10** is replaced by **20**. 

Can you verify that you have **two different saved examples** for **10** and **20** with **different response bodies**?

**Comment by enayetullah** [comment]
@ratpik For **20**, save response is small json Array with 3 elements. When I call using postman API, it return the example response save under **10** (The long one).
![image](https://user-images.githubusercontent.com/4485140/28815533-f92ecb06-76a1-11e7-953b-51cb2eb81425.png)
![image](https://user-images.githubusercontent.com/4485140/28815611-3a33fce8-76a2-11e7-92ef-e828091b2c48.png)
![image](https://user-images.githubusercontent.com/4485140/28815675-6d2c9b00-76a2-11e7-8831-3aa3dfd902e8.png)
![image](https://user-images.githubusercontent.com/4485140/28815814-e8a24636-76a2-11e7-88b0-3e7a4f5cd8bd.png)

**Comment by ratpik** [comment]
@Rashid-007 - This bug has been fixed. You requests should match as you expect them to match.
