### ISSUE TITLE
Can't log in to postman via Google id

### ISSUE THREAD

**Issue by dtsob75** [a85/POSTMan-Chrome-Extension#3327]
When I try to log on to postman, I use the login via google. In the last few days, I installed postman on a server I am trying to test and when I click the Sign In with Google button, the google login page flashes on for a few seconds and then reverts to the general Sign in page.  I only get this problem on the new server I am trying to use.  I need to be able to share the api calls to this server.

## App Details:
Postman for Chrome
Version 5.1.2
win / x86-64
Chrome 59.0.3071.115
```
Postman for Mac
Version 4.11.0
OS X 16.4.0 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there: Recently
 2. Expected behaviour:
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 4. Screenshots (if applicable)

Click the Postman icon
Click Login button 
Click Sign in with Google button

**Comment by sdnts** [comment]
Hi @dtsob75 Are you still seeing this? I'm able to sign in using Google on 5.1.2.

**Comment by dtsob75** [comment]
Yes, just tried it again.  Not sure if it makes any difference, but the box I am attempting to logon from is Windows server 2012 r2

**Comment by sdnts** [comment]
@dtsob75 When you say you get redirected to the general sign in page, do you mean the Google sign in page or the getpostman.com sign in page?

We did push some fixes for this yesterday, but if you still cannot log in, I'd recommend resetting your password via `https://app.getpostman.com/forgot-password` and trying a normal login.

**Comment by sdnts** [comment]
@dtsob75 Are you still seeing this?

**Comment by dtsob75** [comment]
Yes, I am.  I just tested it again.  I get to the postman log on page, click the Sign I with Google button.  For a fraction of a second, the google logon popups up, but then goes back to the postman logon.

 

 

Thanks,

 

Joel Zinn

**Comment by sdnts** [comment]
@dtsob75 Does the Google login screen close or does the new window redirect to Postman's login page? Do you have any cookies set?

**Comment by felipecalvo** [comment]
@madebysid I'm having the same problem on two different computers. The Google login screen flashes for a fraction of a second (took me a while to get that screenshot right), then it closes and I'm back to the Postman app login screen. It doesn't redirect anywhere.

![1](https://user-images.githubusercontent.com/11304439/30030778-37056268-9165-11e7-8fce-b31a239553c3.png)
![2](https://user-images.githubusercontent.com/11304439/30030779-370ab984-9165-11e7-8e5a-cb072f134c6e.png)

**Comment by msmpeteclark** [comment]
I'm having a very similar issue. I click the "Sign In with Google" button, a window pops up and lets me put in my google details, which then authenticate. The window disappears but I am still left on the standard login page.

**Comment by timothyholmes** [comment]
I am experiencing this issue on the desktop client for macOS, on a fresh copy of the app. I am able to log in to the the chrome extension.

**Comment by SamvelRaja** [comment]
@timothyholmes can u provide me a screencast of the issue you are facing? helps us to trace it down much easier.
Can you open the app using the command line?
`open <LOCATION_OF_THE_APP>/Contents/MacOs/Postman`
and try to log in, this gives us the additional details we need. Kindly send the screenshot to help[at]getpostman.com by hiding the sensitive data.

**Comment by mybyte** [comment]
Having the same issue. After successful validation of the credentials, the App just takes me back to the log-in screen. Nothing interesting to screenshot/capture. The highlighted line is interesting though. Maybe the login mechanism is not the issue, but the UI rendering...

IOVARendererID property not found 
**_/Library/Caches/com.apple.xbs/Sources/AppleGVA/AppleGVA-9.1.12/Sources/Slices/Driver/AVD_loader.cpp: failed to get a service for display 8_** 
Starting Browser login with URL:
Cleared all storageData for clean session: login_enterprise
LoginWindow redirected to Url = <url here>
LoginWindow redirected to Url = <url here>
LoginWindow navigated to Url = <url here>
LoginWindow navigated to Url =  <url here>
LoginWindow redirected to Url =  <url here>
LoginWindow redirected to Url =  <url here>
Send success back to renderer: 
 https://erisedstraehruoytubecafruoytonwohsi.chromiumapp.org/oauth2?user_id=[...]

**Comment by JavOLeeN** [comment]
FYI
https://github.com/electron/electron/issues/7466

**Comment by btrdurfee** [comment]
I am having this issue as well with MacOS version 5.3.1. After authenticating, it takes you back to the login screen.

**Comment by jbrz** [comment]
This happens to me in 5.3.1 on OSX - not sure if relevant, but I'm using 2FA for Google.

**Comment by StevenGall** [comment]
@btrdurfee @jbrz It seems to be fixed in 5.3.2. I would suggest downloading the update if you haven't already. 👍

**Comment by hoose145** [comment]
not sure that it is fixed in 5.3.2.

i try to login and it just gives me a blank screen and doesn't do anything else.

**Comment by nian88** [comment]
i have the same problem

**Comment by eraac** [comment]
Fresh app, just unzip (no move to Application directory)

- MacOS 10.13
- Postman app 5.3.2
- MFA on Google

Just after login with Google, window is close and give me postman login page again

**Comment by abhijitkane** [comment]
@nian88 @Eraac @hoose145 Can you head to View>Show DevTools and repeat the process? Any errors you see in the console might be helpful.

**Comment by msmpeteclark** [comment]
@abhijitkane I have just tried logging in with the console open, no errors are included in the console output.

**Comment by eraac** [comment]
@abhijitkane Developer Tools Console and Postman Console are absolutely empty 😢

**Comment by SamvelRaja** [comment]
@Eraac Can you remove ~/Library/Applications \Support/Postman directory and try again. 
If the problem persists, can you send us a screencast/video to help[at]getpostman[dot]com

**Comment by eraac** [comment]
@SamvelRaja directory removed, it's work correctly now ! (and the login interface has changed) ❤️

**Comment by raesteyn** [comment]
On windows, removing the contents of C:\Users\[USER]\AppData\Roaming\Postman seems to have resolved the issue.

I purged my cache, which broke the desktop apps login. I am guessing the solution would be the same regardless of how we arrived at the problem though.

**Comment by marcelomelodf** [comment]
Deleting %APPDATA%\Roaming\Postman also worked for me.

**Comment by rbochz28** [comment]
Removing the directory does fix the issue, but it will also unfortunately wipe out your work space.

**Comment by ojblass** [comment]
anybody facing this issue should look at the 'Start In' folder for the Postman shortcut.  I corrected it and was able to retain my workspace.  The updater didn't correctly fix it.

**Comment by eylvisaker** [comment]
Thanks @ojblass - that fix worked for me.
