### ISSUE TITLE
Postman: Unable to authenticate using access token

### ISSUE THREAD

**Issue by skyfloyd** [a85/POSTMan-Chrome-Extension#3328]
Recently I decide use Postman but I can't create mocks because of this error "Unable to authenticate using access token." 
![error](https://user-images.githubusercontent.com/9090865/28794623-e66090a4-7647-11e7-9f21-9b125c375d22.png)

Any idea how can I solve this problem?

I am just trying to make this sample https://www.getpostman.com/docs/postman/mock_servers/mocking_with_examples

**Comment by sdnts** [comment]
Hi @skyfloyd, thanks for reporting this, we're looking into this. I'll let you know when we've made a fix on our end so you can retry.

**Comment by abhijitkane** [comment]
@skyfloyd Fixed in the latest version. Feel free to re-open if you're still seeing this.

**Comment by porfila** [comment]
Just not working with an access token containing a "+"
