### ISSUE TITLE
Postman encodes '+' as %20 in request endpoint

### ISSUE THREAD

**Issue by ghost** [a85/POSTMan-Chrome-Extension#3329]
## App Details:

```
Postman for Mac
Version 5.1.2 (5.1.2)
macOS Sierra 10.12.6 (16G29) / x64
```

## Issue Report:
 1. I'm submitting email address 'test+1@test.com' to Java REST service via parameter.
 2. Postman encodes this as '&email=test%201%40test.com'.
 3. The %20 is being interpreted as space in email and breaks the service (note space inside email address: there is a problem with the email address :test 1@test.com\njava.lang.Thread).
 4. When I submit email with correct encoding it goes through: '&email=test%2B1%40test.com'.

Steps to reproduce the problem:
 1. Create a call with parameter for email address and use + sign in email address.
 2. Submit the call and see cURL. Plus sign will be encoded as %20 (space).

**Comment by matbos** [comment]
I can confirm this issue also exists in the Postman for Chrome on Windows.

> Postman for Chrome
Version 5.1.3
win / x86-64
Chrome 60.0.3112.101

**Comment by makimb2** [comment]
Also, similar to this if you pass a parameter that has a "#" in it, postman won't read it and will delete it and any trailing characters.   

so for example if you have a endpoint:    https://domain/info/username=testName&password=testrun#this

"#this"  will be deleted and not read once you click send

Thanks

**Comment by jakublang** [comment]
I have somilar problem with "!". I am using delta query and when I try send delta token https://example.com/api/MyEntitySet?!deltatoken='123' the endpoint receive https://example.com/api/MyEntitySet?%21deltatoken='123'.

**Comment by SamvelRaja** [comment]
We are following a master thread #4555 to track all issues related to Url encoding. Please follow that issue for updates.
