### ISSUE TITLE
Can't import collections

### ISSUE THREAD

**Issue by thechrisproject** [a85/POSTMan-Chrome-Extension#333]
Behavior: Any attempt to import a collection via file or URL fail. I have tried opening the file by clicking "Choose Files". After choosing a JSON file that I exported, the input element still says "No file chosen". Dragging a file onto that button also does nothing. Dragging a file into the "drop files here" area does nothing. If I enter a collection URL (url is to a resource that is only accessible from the network I'm on) and then hit "import", nothing happens.

I have tested this on Macs and Windows 7 machines, same behavior.

Backstory: My small development team uses POSTMan to test our rest services. I was trying to create a repository of collections for us all to use so I exported mine with the intention of importing so I could create screenshots and instructions. Now I can't even get my collections back.

![postman](https://f.cloud.github.com/assets/482304/856594/2256c052-f540-11e2-800e-36e084a43230.jpg)

**Comment by brandonmerritt** [comment]
FWIW: Was having problems importing from the Postman Chrome Plugin to the Standalone app. Just importing the .txt file didn't work (didn't know about the json trick). Once I cut out all the data within the collections object and pasted them directly into the standalone app everything imported fine.

**Comment by abhijitkane** [comment]
@brandonmerritt You mean copy the contents of the txt file, and pasting them into the Import window in the standalone app?

Could you mail the txt file in question to help@getpostman.com? You can edit out any sensitive URLs/headers. Importing the text file should be equivalent to pasting its contents.

**Comment by johnwpratt** [comment]
I've tried the old version of postman and now the new one, tried importing, tried pasting and tried changing the file extension and so far nothing has allowed me to import a postman collection file which I have been assured works, Any suggestions?

In the old version I would get no response when I tried uploading.
In the new version I get "Failed to Import: Format not recognized"

The name of the file I am trying to import ends in .postman_collection

**Comment by a85** [comment]
@johnwpratt Is the collection file exported from Postman or generated somewhere else? We run into issues when JSON data is different from the one that Postman recognizes.

**Comment by johnwpratt** [comment]
Thanks for getting back to me. I figured out what it was. The collection was hosted on a chat and when I downloaded it, it added a thnk wrapper. When I pasted it without that wrapper it imported fine.
