### ISSUE TITLE
I am unable to drag or resize the Postman app

### ISSUE THREAD

**Issue by MarkAllan007** [a85/POSTMan-Chrome-Extension#3330]
Postman for Windows
Version 5.1.2
win32 10.0.15063 / x64

I am unable to drag or resize the Postman app. For example, I want to split the screen with two apps, each app taking up half the screen.

1. Does Postman contain controls that allow it to be dragged from the menu bar?
2. Does Postman contain controls that allow the user to resize it from the menu bar, sides or corners?

I cannot drag or resize Postman, but I don't know if these are bugs? Your UX designers may have designed Postman to take the entire screen. You may not want to allow users to drag Postman from one screen to another. You may not want users to resize Postman. 

Thank you,
Mark

**Comment by sdnts** [comment]
Hi @MarkAllan007, the app is resizable and draggable.
You should be able to drag the app by the title bar. Resizing is also possible by dragging any corder of the app.

AFAIK, on Windows, if any app is maximized, it is not resizable. You might need to `Restore` using the three window controls.

I'm closing this, but please reopen if you cannot resize even after restoring the app window.

**Comment by MarkAllan007** [comment]
Madebysid,

"the app is resizable and draggable."
My take away - I should be able to drag and resize the Postman app.

When I open Postman, it expands and takes up the entire screen. 
1. I cannot drag Postman, because it’s title/main menu bar does not respond to dragging.
2. The title/main menu bar does not contain window controls for resizing.
3. The task bar popup menu does not contain options for changing size, it cannot open in a minimized form.
4. See attached image below.

"You might need to Restore using the three window controls."
How? With what window controls? 

My take away, if I cannot drag the Postman app, if it has no controls to resize the app, then the app has bugs.

Thank you,
Mark

Company: Postdot Technologies
Accounting: MSEAI
Assessment: LARAWS, LCTAJS

**Comment by MarkAllan007** [comment]
![postman tool screenshot](https://user-images.githubusercontent.com/4197055/28842424-4d1198d6-76c3-11e7-84ad-b928f5dde341.jpg)

**Comment by MarkAllan007** [comment]
Notice that there are no window controls for changing the windows size.

**Comment by Faz540** [comment]
Press F11 to toggle Full Screen mode off/on.

**Comment by HiVisAxolotyl** [comment]
why did sdnts even answer if he had no idea.  F11 is the answer, and completely not obvious. Apps dont normally open at full screen with only F11 to get to the resize control . Crap design from postman.
