### ISSUE TITLE
How to send application/json data along with file in postman multipart/form-data post request?

### ISSUE THREAD

**Issue by gampasandeep** [a85/POSTMan-Chrome-Extension#3331]
Postman for Windows 10
 x64
```

**Comment by sdnts** [comment]
@gampasandeep Can you elaborate?
If you want to send over a file, you should be able to change the dropdown value next to the `key` column from `Text`to `File`.

**Comment by gampasandeep** [comment]
![capture](https://user-images.githubusercontent.com/29592177/28858454-4081e3fe-776e-11e7-8b73-3da8ad7b08f6.PNG)

In the screenshot along with that file i need to send the below data.Is it possible??
{
"field1":"",
"field2":"",
"field3":""
	
}

**Comment by sdnts** [comment]
Sure. Just adding these field below your file field, as separate rows should work fine.

**Comment by gampasandeep** [comment]
Yeah Thank you.
It is working fine.But can i send all the fields as single object???

**Comment by urn046** [comment]
![err](https://user-images.githubusercontent.com/32358258/30960511-d8b53af8-a460-11e7-9317-3ae5d80228c9.PNG)


I am facing problem while sending POST request that contains xml file and json data.
It is showing bad request format
how should i resove it?

**Comment by gampasandeep** [comment]
@urn046  the json object that you are trying to send is not a valid format.

Try giving your json object key as key parameter and value as value parameter in the form-data.

**Comment by Huiziryuu** [comment]
@madebysid  I'm using Jersey REST in servlet. Since the request sent from PostMan doesn't contain content type for JSON form data parameter, Jersey read it as String rather than a JSON object.
The request content from post man is:
`Cache-Control: no-cache
Postman-Token: 5241a928-78e9-2b70-637a-96a68775c85b
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="jsondata"

{"responseFormat":"json"}
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="payload_data"; filename="test.pdf"
Content-Type: application/pdf


------WebKitFormBoundary7MA4YWxkTrZu0gW--`

**Comment by janpridal** [comment]
Same for me. I need to upload a file and json as multipart as it is nicely summarized in the answer here: https://stackoverflow.com/questions/27609569/file-upload-along-with-other-object-in-jersey-restful-web-service
Unfortunately it is not possible to set the content-type for each part in Postman though it is allowed by specification as one can see from samples therein: https://www.w3.org/Protocols/rfc1341/7_2_Multipart.html

**Comment by lpj145** [comment]
If Somebody needed [Solution link by me](https://stackoverflow.com/a/48054400/6923849)

Add field name as array.
![image](https://user-images.githubusercontent.com/11980109/34472248-60814848-ef3c-11e7-8fd8-fbbb4aba71a6.png)

**Comment by sify21** [comment]
The json part of the body should also be set as "File" rather then "Text", and put your json data in a json file for example "a.json". 
Just find out that this method doesn't work on windows, but works fine on linux.  
  
**NOTE:** _This is an old workaround which I accidentally found out when postman didn't have this feature, and now it has been officially supported, check out  #1104_

**Comment by amberream** [comment]
Confirmed it works on Linux, but not on Windows.  Would be great to get it working on Windows...

**Comment by savithaAjitraj** [comment]
Hi is multipart supported now on postman?

**Comment by swateek** [comment]
@sify21 it doesn't help. Any other thought?

The code in my case looks for req.body, if I want to send through POSTMAN am unable to achieve that along with file from form-data.

**Comment by matthiasbe** [comment]
Hi,
It appears to work fine for me on Windows 10, using @sify21 method.
I added two files : one containing my image, the other is a JSON file containing the json data I want to send along.

![image](https://user-images.githubusercontent.com/9254232/41856079-79f56b06-7894-11e8-87ce-c67b49f6158d.png)

The corresponding Spring endpoint looks like this : 
```java
@RequestMapping(value = "/completetask", method = RequestMethod.PUT, consumes = {"multipart/form-data"})
public Intervention completeTask(@RequestPart("action") InterventionAction action, @RequestPart("resources") MultipartFile[])
```

**Comment by amberream** [comment]
I am using the (new?) ARC chrome app instead of PostMan to get around this issue.  It works fine on Windows with ARC!

**Comment by prashantagarwal** [comment]
Hey, guys we are tracking this feature here #1104

**Comment by vlott** [comment]
Thanks, sify21. The workaround of attaching the JSON as a file with a .json extension works on MacOS also.

**Comment by prmdsngh** [comment]
I resolved it by sending json in the form of string and use objectMapper class to map JSON string  to the object.

**Comment by ghost** [comment]
Did anyone get the question? The OP wanted to send the data as JSON body as the application is designed to accept JSON post body(again not as a key JSON file). Or if that is already possible, it's not clear in any of the answers. Probably someone from postman team should take responsibility and give a clear answer and a link to the documentation.

**Comment by dejf-js** [comment]
Seems that Postman is not able to send JSON body together with a multipart attached file.

**Comment by GuilhermeMorais** [comment]
I could send JSON files with Postman, in Windows 10:
   1 - I save as JSON extension (Like @sify21)
   2 - But I put it on the path "c:\fileName.json" Then it worked! 

I hope it helps others.

**Comment by GarryLowther** [comment]
I can create a POST which sends a file I pick into my API if I run it as a "Send", but when I run this as part of other steps in the collection runner, it does not find the file and it errors. What am I missing?

**Comment by GarryLowther** [comment]
Oh, just found this: https://community.getpostman.com/t/collection-runner-with-file-uploads/1234
Perhaps uploading files using the Postman collection runner is still not possible?

**Comment by dresean** [comment]
So I've just found out that this is actually impossible for now at least. [look at the documentation here](https://learning.getpostman.com/docs/postman/sending_api_requests/requests/) 
![Screen Shot 2019-04-17 at 6 52 30 PM](https://user-images.githubusercontent.com/20849315/56325946-349dbf80-6142-11e9-8a46-3e59613c3b1b.png)
Read the last line above.

**Comment by evereux** [comment]
The question is regarding sending files with a Content-Type "application/json" including the file (which is not JSON). Many people seem to missing this.

**Comment by ZhilunLiu** [comment]
> Hi,
> It appears to work fine for me on Windows 10, using @sify21 method.
> I added two files : one containing my image, the other is a JSON file containing the json data I want to send along.
> 
> ![image](https://user-images.githubusercontent.com/9254232/41856079-79f56b06-7894-11e8-87ce-c67b49f6158d.png)
> 
> The corresponding Spring endpoint looks like this :
> 
> ```java
> @RequestMapping(value = "/completetask", method = RequestMethod.PUT, consumes = {"multipart/form-data"})
> public Intervention completeTask(@RequestPart("action") InterventionAction action, @RequestPart("resources") MultipartFile[])
> ```

Yes, I'm using this method and it's works fine, Noted that I change my code using @RequestPart annotation instead of RequestParam

**Comment by kasradzenika** [comment]
this thread:
![Heckoverflow](https://i.redd.it/2k1ut81gpcl01.png)

**Comment by nirmal1997** [comment]
> Hi is multipart supported now on postman?

yes its suported

**Comment by nirmal1997** [comment]
how to get the url by uploading an image in multipart form data.But make sure that use parser.add_argument(images,loc*******)

    def post(self):  
            data = parser.parse_args()
            print(data)
            image = data['image'] 
            print(image)
            # imagew= request.files['file']
            # print(image)

            # print(UPLOAD_FOLDER)
            UPLOAD_FOLDER= path
            image.save(os.path.join(UPLOAD_FOLDER, image.filename)) 
            img = image_url + str(image.filename)
            return {
                        'data': img,
                        'statusCode': 1
                    }
will anyone help me to solve this

**Comment by Jigsawk** [comment]
> ![capture](https://user-images.githubusercontent.com/29592177/28858454-4081e3fe-776e-11e7-8b73-3da8ad7b08f6.PNG)
> 
> In the screenshot along with that file i need to send the below data.Is it possible??
> {
> "field1":"",
> "field2":"",
> "field3":""
> 
> }

this way can solve my problem

**Comment by Srivahni** [comment]
> > ![capture](https://user-images.githubusercontent.com/29592177/28858454-4081e3fe-776e-11e7-8b73-3da8ad7b08f6.PNG)
> > In the screenshot along with that file i need to send the below data.Is it possible??
> > {
> > "field1":"",
> > "field2":"",
> > "field3":""
> > }
> 
> this way can solve my problem

Yes, it is possible. you can give your json body in the "value" field with a key. I've found the "Bulk Edit" option (next to the ... dots) easy to paste/edit json data.

<img width="712" alt="Capture" src="https://user-images.githubusercontent.com/15986239/75084292-1a580f00-54d4-11ea-935f-706cad5b1d8a.PNG">

**Comment by ahsanfarooq3423** [comment]
The way to send mulitpart data which containts a file with the json data is the following, we need to set the content-type of the key fields to '**application/json**' in the postman body tab like the following:

![image](https://user-images.githubusercontent.com/31133118/77055825-6030c600-69f3-11ea-953b-80bd123b8d8a.png)

**Comment by Abdelilah00** [comment]
**try this** 
![image](https://user-images.githubusercontent.com/32691012/84044121-0ced6480-a99f-11ea-82b3-44aabc80265f.png)

**and my _DTO_ look like** 
![image](https://user-images.githubusercontent.com/32691012/84044288-44f4a780-a99f-11ea-8337-81eb5e3ec8b7.png)

**Comment by suneelsharma1612** [comment]
> Hi,
> It appears to work fine for me on Windows 10, using @sify21 method.
> I added two files : one containing my image, the other is a JSON file containing the json data I want to send along.
> 
> ![image](https://user-images.githubusercontent.com/9254232/41856079-79f56b06-7894-11e8-87ce-c67b49f6158d.png)
> 
> The corresponding Spring endpoint looks like this :
> 
> ```java
> @RequestMapping(value = "/completetask", method = RequestMethod.PUT, consumes = {"multipart/form-data"})
> public Intervention completeTask(@RequestPart("action") InterventionAction action, @RequestPart("resources") MultipartFile[])
> ```

can you please explain to me, I have to upload three different doc file with three browse button, using spring boot

**Comment by aartigiri-hub** [comment]
> > Hi,
> > It appears to work fine for me on Windows 10, using @sify21 method.
> > I added two files : one containing my image, the other is a JSON file containing the json data I want to send along.
> > ![image](https://user-images.githubusercontent.com/9254232/41856079-79f56b06-7894-11e8-87ce-c67b49f6158d.png)
> > The corresponding Spring endpoint looks like this :
> > ```java
> > @RequestMapping(value = "/completetask", method = RequestMethod.PUT, consumes = {"multipart/form-data"})
> > public Intervention completeTask(@RequestPart("action") InterventionAction action, @RequestPart("resources") MultipartFile[])
> > ```
> 
> Yes, I'm using this method and it's works fine, Noted that I change my code using @RequestPart annotation instead of RequestParam

**Comment by bhuvnesh1405** [comment]
> The json part of the body should also be set as "File" rather then "Text", and put your json data in a json file for example "a.json".
> Just find out that this method doesn't work on windows, but works fine on linux.
> 
> **NOTE:** _This is an old workaround which I accidentally found out when postman didn't have this feature, and now it has been officially supported, check out #1104_

Thanks for the idea, got it working on JMeter too. Many thanks!

**Comment by Captain-JackSparrow65** [comment]
> The way to send mulitpart data which containts a file with the json data is the following, we need to set the content-type of the key fields to '**application/json**' in the postman body tab like the following:
> 
> ![image](https://user-images.githubusercontent.com/31133118/77055825-6030c600-69f3-11ea-953b-80bd123b8d8a.png)

No it's not working for me I'm using Linus os problem is when I send hain data along with image file using req.body it send back the server error which I hade set in the code

**Comment by arlemi** [comment]
@Captain-JackSparrow65 Please open a topic on the [community forum](https://community.getpostman.com/) and walk us through what you're experiencing so we can help (providing screenshots, videos, logs will help).

**Comment by mjkatgithub** [comment]
> @urn046 the json object that you are trying to send is not a valid format.
> 
> Try giving your json object key as key parameter and value as value parameter in the form-data.

but what if the value is a nested json object

**Comment by bestcomp-dev** [comment]
This works fine
https://stackoverflow.com/a/52748531/2989257

**Comment by PDS42** [comment]
> > @urn046 the json object that you are trying to send is not a valid format.
> > Try giving your json object key as key parameter and value as value parameter in the form-data.
> 
> but what if the value is a nested json object

For nested objects, you need to use the following syntax (there could be other solutions, but this one works for sure):

![Screenshot from 2022-01-24 15-24-10](https://user-images.githubusercontent.com/11089426/150800691-5b1aee53-d633-4b29-bfb3-8e354e94598c.png)
