### ISSUE TITLE
OAuth2 `state` variable - insufficient entropy

### ISSUE THREAD

**Issue by dowlingw** [a85/POSTMan-Chrome-Extension#3332]
## App Details
```
Postman for Mac
Version 5.1.2 (5.1.2)
macOS Sierra 10.12.6 (16G29)
```

## Feature Request
Some Authorization servers will reject client `state` values that do not appear to have high enough entropy. For example, ORYs Hydra product rejects `state` values less than 8 characters long.

In the case of Hydra, it is doing so to ensure application clients are not vulnerable to specific threats, see the following:
https://tools.ietf.org/html/rfc6819#section-4.4.1.8

The values generated by Postman are seven characters in length.

I understand that the limit imposed by Hydra is arbitrary (I think seven digits should be sufficient in Postmans use case), however it would be nice if this was a configurable option in the Postman application.

**Comment by sdnts** [comment]
Hi @dowlingw, thanks for letting me know. I'm adding this as a feature request.
If not configurable, we should at least be able to increase the state value size!

**Comment by vikiCoder** [comment]
We no longer auto-generate the `state` variable in OAuth2 according to the latest version of Postman native app (v7.3.4). You can specify whatever value you want as the state in the provided field shown in below screenshot:

<img width="621" alt="Screenshot 2019-07-30 at 2 05 04 PM" src="https://user-images.githubusercontent.com/16588032/62113916-27f93d80-b2d3-11e9-8326-3779d94bcab3.png">

You can also use variables like `{{$timestamp}}` and `{{$randomInt}}` in the state field to randomize its value.
