### ISSUE TITLE
Request body deleted if that body type is not selected when app is closed

### ISSUE THREAD

**Issue by thePurpleMonkey** [a85/POSTMan-Chrome-Extension#3334]
## App Details:

```
Postman for Windows
Version 5.1.2
win32 10.0.15063 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there: Always been there, but I only started using Postman recently.
 2. Expected behaviour: Request body of all formats are saved.
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 4. Screenshots (if applicable)

### Steps to reproduce the problem

1. Open/Create a post request, and go to body tab.
    a. Choose x-www-form-urlencoded. Enter data.
    b. Choose raw. Enter data.
    c. Save.
2. Close Postman. Open Postman.
3. The only request body data that remains after opening is whatever was left open when Postman was closed. If raw was selected, then x-www-form-urlencoded is empty. If x-www-form-urlencoded was selected, then raw is empty.

**Comment by sdnts** [comment]
@thePurpleMonkey Thanks for reporting this, I was able to replicate. We'll get on a fix

**Comment by prashantagarwal** [comment]
@thePurpleMonkey There can only be one request body associated with a request. We just keep track of all the changes that you make in memory. Once you quit the app we don't save all of that.
