### ISSUE TITLE
Display of Example Responses In Documentation Is Inconsistent

### ISSUE THREAD

**Issue by staticvoidmaine** [a85/POSTMan-Chrome-Extension#3335]
## App Details:
```
Postman for Linux
Version 5.1.2
linux 4.11.9-1-ARCH / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there: Recently/Always
 2. Expected behaviour: Example responses are displayed in a consistent way. Either display them in a scrollable element, or an expandable element, but not either at (what seems like) random.
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 4. Screenshots (if applicable)

## Steps to Reproduce
1. Create collection to document etc.
2. Configure requests
3. Add examples (I added 3 to each request)
4. Publish documentation
5. See that some example responses are click-expandable
6. See that some example responses are scrollable
7. See that each example within each collection may (what seems unpredictably so far) be one or the other.

**Comment by staticvoidmaine** [comment]
Bonus points for inconsistent/random ordering of examples with no way to set the order (to my knowledge)

**Comment by sdnts** [comment]
@rylancates I'm looking into this. Ideally, examples are shown as is, but if they're too long, they're truncated and you can view them by expanding.

As for the example reordering, this is on our roadmap, and will be part of an upcoming release. I'll let you know here when it is out. Currently, they're ordered by the time they were created.

**Comment by staticvoidmaine** [comment]
To supply my experience, I have seen all example responses contained within a 200px tall box where the width is responsive to window width. The only difference is, like I mentioned, whether the box is click-expnadable or scrollable.

**Comment by seabamirum** [comment]
I have 4 examples in Postman but when published to documentation only the first and last in the list are appearing.

**Comment by SleeplessByte** [comment]
Having the same issue as @seabamirum . Some of the responses simply don't show at all; some of them show correctly.

**Comment by godfrzero** [comment]
@seabamirum @SleeplessByte Does this issue persist? Usually, examples not showing up at all means that the collection hasn't finished syncing completely.

@rylancates The order of the examples rendering the documentation match the order in the app (or, they do now). Whether or not the example is expandable/scrollable depends on the length of the content.

**Comment by SleeplessByte** [comment]
@godfrzero It seems like a syncing issue. Another example that I've deleted is stil showing up. I restarted the windows app, I pressed the "force sync" in case of sync issues button. None of those things five you feedback. I think it would be helpful to see if it synced or not, or what the last sync was, so I could at least check that timestamp.

**Comment by godfrzero** [comment]
We're tracking a few sync-related fixes internally which will be coming out in the next release. In the meantime, could you let me know if you're using the latest version of the app? (6.1.4)

I'll also make a note to focus on communicating sync errors with more clarity.

**Comment by SleeplessByte** [comment]
@godfrzero updated yesterday to whatever the latest was yesterday 👍

**Comment by godfrzero** [comment]
Okay. I'll keep this thread updated with any sync related fixes we release. In the meantime, using 'Force Sync' should resolve the issue whenever it pops up.

**Comment by preethammavin** [comment]
The issues around this have been fixed, closing the issue for now. Do feel free to reopen the thread if the issue persists.
