### ISSUE TITLE
Unable to drag or resize the Postman app

### ISSUE THREAD

**Issue by MarkAllan007** [a85/POSTMan-Chrome-Extension#3336]
Postman for Windows
Version 5.1.2
win32 10.0.15063 / x64

Related to issue: 3330
Status: Reopened

Madebysid,

"the app is resizable and draggable."
My take away - I should be able to drag and resize the Postman app.

When I open Postman, it expands and takes up the entire screen.
1. I cannot drag Postman, because it’s title/main menu bar does not respond to dragging.
2. The title/main menu bar does not contain window controls for resizing.
3. The task bar popup menu does not contain options for changing size, it cannot open in a minimized form.

"You might need to Restore using the three window controls."
How? With what window controls?

My take away - if I cannot drag the Postman app, and if it has no controls for resizing, then the app has some bugs that should be fixed. 

Thank you,
Mark

Internal tracking
Company: Postdot Technologies
Accounting: MSEAI
Assessment: LARAWS, LCTAJS

![postman tool screenshot](https://user-images.githubusercontent.com/4197055/28846265-5ebcef92-76d0-11e7-9983-69cf252e3610.jpg)

**Comment by Faz540** [comment]
Apologies if I'm incorrect, but it seems, judging by the screenshot, that your Postman app is in Full Screen mode.
Press F11 to exit Full Screen mode and you should be able to resize, move the window. (It seems Postman remembers if it was in Full Screen mode when you exit the program)

**Comment by sdnts** [comment]
@MarkAllan007 Did you try what @Faz540 suggested? This is what I was saying as well. Looks like your app is in full screen mode and is stuck there. F11 should fix this.

**Comment by MarkAllan007** [comment]
Hi Faz540 & Madebysid,
Yes, I found the control to toggle/turn the drag and resize controls on/off for Postman.
Thank you so much! 
Mark

Internal tracking 
Company: Postdot Technologies
Accounting: CSRI 
Assessment: HARAWS, HCTAJS

![view - toggle full screen mode](https://user-images.githubusercontent.com/4197055/28878343-9e1e0d12-7764-11e7-9889-e04d3ab50a1d.jpg)

**Comment by ddsurf** [comment]
is actually a issue, can not resize mouse over to get two way arrow, Regardless of full screen or normal screen. Been stuck in swagger due to it.

**Comment by JohnBorelliApproved** [comment]
@Faz540,

Dear God!  Thank you!  This has been such a pain and all I needed was F11!
