### ISSUE TITLE
Allow the OAUTH2 dialog to project values into the environment

### ISSUE THREAD

**Issue by gareth-a-jones** [a85/POSTMan-Chrome-Extension#3338]
Having used the oauth2 dialog to get a new token, I don't want to take further manual steps to inject the output into my environment.  Rather, I want to set up the dialog to push the access and refresh tokens retrieved into named environment variables.
 See #3337  for the necessary precursor issue for OAUTH2 state management to make this useful.

**Comment by sdnts** [comment]
@garethj-msft This sounds like a good idea, and a useful thing to have. I'm marking this as a feature request!

**Comment by gareth-a-jones** [comment]
Seems like it and its compatriot should have the auth label too?

**Comment by a85** [comment]
@garethj-msft Added the Auth label. Thanks for the suggestion!

**Comment by vikiCoder** [comment]
Closing this as a duplicate of the following issue:
https://github.com/postmanlabs/postman-app-support/issues/1507
