### ISSUE TITLE
numbers as names in environment variables

### ISSUE THREAD

**Issue by lilling** [a85/POSTMan-Chrome-Extension#3340]
## App Details:
Postman for Chrome
Version 5.1.2
win / x86-64
Chrome 59.0.3071.115

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there: encounter this recently
 2. Expected behaviour: to be able to save enviornment variables as numbers
 3. Console logs : None
 4. Screenshots: 
![image](https://user-images.githubusercontent.com/11631465/28887358-8feeaa6a-77c5-11e7-9848-273ffc201a3c.png)

## steps:
- call environment variable a number like 143 in the screen shot or all kind of number you want.
- try to call it

**Comment by sdnts** [comment]
@lilling I was able to replicate this on our Chrome apps, but not our [native apps](https://getpostman.com/apps). I'd recommend switching to the native apps anyway since Chrome apps will be deprecated by Google later this year.

Please reopen if I misunderstood.

**Comment by lilling** [comment]
![image](https://user-images.githubusercontent.com/11631465/28919416-0ae2a484-7856-11e7-9538-1c03c0f501e6.png)
isnt it native app?
