### ISSUE TITLE
Support OAuth 2.0 with Resource Owner Password Credentials

### ISSUE THREAD

**Issue by kimkha** [a85/POSTMan-Chrome-Extension#3341]
Please support OAuth 2.0 option with grant_type = "password", which describe as "Resource Owner Password Credentials" in https://tools.ietf.org/html/rfc6749

**Comment by sdnts** [comment]
Hi @kimkha This looks like a duplicate of #1446, so I'm closing this. 
We've planned to re-look at all auth helpers in the near future, so we'll take this up then. You can keep an eye on our [roadmap](https://trello.com/b/4N7PnHAz/postman-roadmap-for-developers)
