### ISSUE TITLE
Delay when scrolling on large sized entries of response data

### ISSUE THREAD

**Issue by bunyaminsg** [a85/POSTMan-Chrome-Extension#3342]
## App Details:

```
Postman for Chrome
Version 5.1.2
linux / x86-64
Chrome 59.0.3071.109
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there: noticed recently
 2. Expected behaviour: Usual behaviour
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app): none
 4. Screenshots (if applicable): not applicable

I have a message API that responds with json structures. The `attachment` part of this json contains base64 encoded files that's size may be in megabytes. When I scrolling over this response, a delay occurs only when scrolling over the `attachment` entry. There isn't any performance issue when the attachment is not in screen or collapsed. So I deal with this problem by scrolling to that field with patience and then collapsing it :) 

My suggestion is that if responded json has an entry that is larger than x bytes, it may comes collapsed initially.

**Comment by prashantagarwal** [comment]
Thanks for the suggestion @bunyaminsg . We will surely look into improving this.

**Comment by numaanashraf** [comment]
@bunyaminsg We have created a master thread #4751 to track all issues related to large responses. We would be updating that thread on possible workarounds, planned improvements and releases related to large response performance.
