### ISSUE TITLE
Error on POST request: "JavaScript is required. This web browser does not support JavaScript..."

### ISSUE THREAD

**Issue by qualityworld** [a85/POSTMan-Chrome-Extension#3344]
## App Details:
Postman for Mac
Version 5.1.2
OS X 16.7.0 / x64

Also tested on:

Postman for Windows (Both in Parallels on Mac and a Desktop PC with same Windows version)
Version 5.1.2
win32 10.0.15063 / x64

And I get the same problem on all systems.

## Issue Report:
I'm new to Postman and my first try-out ever is causing problems...
I keep getting a "This webbrowser does not support JavaScript..." error whenever I send the Post request, and I should get a Token returned.
I've searched the community and other resources as well as google and cannot find a solution to my problem, so I hope you can point me in the right direction.

Attached is screenshots from Postman and the Console

Thanks for your help.
<img width="1315" alt="postman console" src="https://user-images.githubusercontent.com/2625540/28916859-de4ad246-7843-11e7-9fa5-68693d27c87b.png">
![postman2-blurred](https://user-images.githubusercontent.com/2625540/28916857-de44e688-7843-11e7-9702-6b3cd7144f9c.png)
[postman error.txt](https://github.com/postmanlabs/postman-app-support/files/1196780/postman.error.txt)
![postman1](https://user-images.githubusercontent.com/2625540/28916858-de45b37e-7843-11e7-854e-bf69687137c1.gif)

**Comment by prashantagarwal** [comment]
@qualityworld We don't allow Javascript to run in preview mode in Postman for security reasons. And so when you are using javascript to hide this text, it is not running.

**Comment by qualityworld** [comment]
Hi again - thanks for the answer, but I'm not sure if my question was unclear or if I simply dont understand the answer ?!
I use postman to send the attached request - and I should then simply get a response containing a JSON Web Token and thats it, no javascript or anything else.
BUT what I get when using Pretty/Raw or Preview is a html-respons with a Javascrip error text inside... that is my problem.

Hope I'm more clear this time or that you maybe have time to expand on your answer if I simply dont understand it... anyway, thanks for your help!
Cheers,
David
 
![postman-post2](https://user-images.githubusercontent.com/2625540/29062656-caae0982-7c22-11e7-9c9a-e763d7821281.png)

![postman-response-post2](https://user-images.githubusercontent.com/2625540/29062765-4fc17dc0-7c23-11e7-8ee1-9db23326bcb6.png)

**Comment by prashantagarwal** [comment]
@qualityworld I think this might not be related to Postman. I believe this is coming from the server.  Do you have access to this server so that you can debug this.

**Comment by qualityworld** [comment]
Great - thanks for pointing me in this direction, I will contact the API developer and ask if they can debug the request from their end!

**Comment by avinash0** [comment]
I am also facing similar problem. API response is coming through browser but not working in postman. Postman return with some html <noscript>Please enable JavaScript to view the page content.</noscript>

@prashantagarwal  If we belive this response is comming from server - in this case we debug this. If we hit api through browser then we are getting the logs at server side but postman request is not reaching upto server. Request is preflight failed. 

What will be the possible errors? Please help. Thanks!

**Comment by LeopoldLerch** [comment]
same here

This is a adfs-request to a local server, eg in connection with sharepoint. The redirect after successful authentication there is done via javascript on that page. so, when javascript is not working, there will be no redirect and the error message is shown. 

This problem is occurring if one sends the request directly via post,  or if you try to do the authorization via eg "Get new Access Token" in the authorization menu. 

And of course, this is coming from the server. But the server is from MS and that is the wanted behaviour. 
So Postman will have to be able to deal with that.

**Comment by doctorgucci** [comment]
@LeopoldLerch I have the same problem. Did you manage to find a solution to this?

**Comment by sandipfadadu** [comment]
Same problem i`m facing.
"This site requires Javascript to work, please enable Javascript in your browser or use a browser with Javascript support"

**Comment by mtcherni95** [comment]
I have a problem with GET, meaning on some website it works and in others it does not. however the problematic website works on chrome. 
With the problmatic website I get error 503 on postman, while, again, it works on postman

**Comment by truestbyheart** [comment]
i have the same problem

i recently developed a simple api with php and while testing it locally it seemed to work fine but when i uploaded it to a server, when i use my browser it works fine but when i use postmen and my other app it returns an error like so
![screenshot 1](https://user-images.githubusercontent.com/37019531/50216771-bb5ead80-0397-11e9-9338-c542afd46c81.png)
![screenshot 2](https://user-images.githubusercontent.com/37019531/50216772-bbf74400-0397-11e9-8e1c-491cc06e49da.png)

**Comment by sbkrish** [comment]
This problem exist, if you were disabled JavaScript manually in your browser. Otherwise the issue arise from your server side when you are using a free hosting services like InfinityFree.  So kindly check with your server whether they provide an enabling feature for JavaScript or not. 

Some of them allow Javascript _only for web browser and not for API, bot and cURL services_. For this, you need to upgrade from free service to premium or else migrate your website to some other free hosting services like 000webhost. 

Hope this help.

**Comment by janmyszkier** [comment]
I have encountered this issue today and only on OSX version. Trying to post on Shopify API.
Work fine with most recetn postman on Linux, but on OSX, we're getting HTML page with information about javascript being disabled. Same collection imported to both Postman instances, only OSX version results with javascript not being enabled.

**Comment by programwindow** [comment]
I am able to resolve this issue.   Issue was in the redirect url that i had defined in the 'registered App on Azure portal". 

Aftrer changing redirect url to it to "https://:localhost"  ,   I did not get the javascript  error again.

Note 
- My app is for "desktop and mobile client applications"
- My app is Not for Web Apps

**Comment by nhutkhtn** [comment]
> 
> 
> i have the same problem
> 
> i recently developed a simple api with php and while testing it locally it seemed to work fine but when i uploaded it to a server, when i use my browser it works fine but when i use postmen and my other app it returns an error like so
> ![screenshot 1](https://user-images.githubusercontent.com/37019531/50216771-bb5ead80-0397-11e9-9338-c542afd46c81.png)
> ![screenshot 2](https://user-images.githubusercontent.com/37019531/50216772-bbf74400-0397-11e9-8e1c-491cc06e49da.png)

Hi @truestbyheart, 
you have been solved this case. I have a similar case and can you share your experience.? Thanks

**Comment by YurySemakov28** [comment]
I deleted old cookies and copied them from a browser where it works
thanks to this guide https://www.youtube.com/watch?v=WcRHYRaqAnk

**Comment by Utility84** [comment]
> [@LeopoldLerch](https://github.com/LeopoldLerch) I have the same problem. Did you manage to find a solution to this?





https://botspatronizing.github.io/observers/
