### ISSUE TITLE
data stored in server?

### ISSUE THREAD

**Issue by javixeneize** [a85/POSTMan-Chrome-Extension#3345]
Hi

One question about postman usage. The requests that you send are purely stored in your local computer, or is there any information that is synchronised and stored in postman servers?

I mean... will any of my test data, endpoints etc... go to any form of postman infrastructure?

Thanks

**Comment by prashantagarwal** [comment]
@javixeneize If you are not using Sync (Sync is off), then no information related to your api, collections etc goes to Postman servers.
