### ISSUE TITLE
Param descriptions not shown in web view

### ISSUE THREAD

**Issue by mjgp2** [a85/POSTMan-Chrome-Extension#3346]
The param descriptions that our devs add to endpoints are not visible in the web view.

Can you please add the params table to the web view?

Thanks!

**Comment by prashantagarwal** [comment]
@mjgp2 Are you referring to API Documentation. If so then you will be happy to know that we are working on a version of Public API Documentation which we are planning to release shortly. This will start showing your param descriptions.

**Comment by mjgp2** [comment]
Yes the web view of the documentation which can optionally be made public.

Thanks for the update, let me know when it's GA!

**Comment by a85** [comment]
Param descriptions are shown in the documenter now.

**Comment by mjgp2** [comment]
Thanks!

**Comment by StephenOTT** [comment]
Is there a way to show disabled query params?

It seems that query params only show in the docs if they are "checked" / turned on.  If there are many optional query params that are documented, it makes the docs and postman file very messy to work with.

The goal here is to have the params shown in the docs, even when the param if "unchecked"/disabled.

**Comment by StephenOTT** [comment]
example: 
![screen shot 2018-05-04 at 3 23 55 pm](https://user-images.githubusercontent.com/1994838/39648089-4c25e3e4-4faf-11e8-8c76-866b9117e69d.png)

Where all those params are optional and we just want to show the available options and not dirty the CURL

**Comment by phcoliveira** [comment]
https://github.com/postmanlabs/postman-docs/issues/1470
