### ISSUE TITLE
Cannot send "api_key" as a custom header

### ISSUE THREAD

**Issue by phpguru** [a85/POSTMan-Chrome-Extension#3348]
## App Details:

```
Postman for Mac
Version 5.1.3 (5.1.3)
OS X 10.12.6 / x64
```

## Issue Report:
I cannot send "api_key" as a custom header.

I can send "api-key" (hyphen instead of underscore) or "x-api-key" or "foo", but for some reason, not "api_key". It makes no sense and took me awhile to debug.

**Comment by prashantagarwal** [comment]
@phpguru Hmm this seems odd. Are you not receiving this header on your server ? As far as I know some servers do drop headers with underscores silently. For example Apache 2.4 onwards do this to prevent cross-site-scripting attacks via header injection.

**Comment by phpguru** [comment]
I'm using nginx with PHP-FPM.

We noticed "x-api-key" was a "default" available header in postman and switched our code to expect that instead.

**Comment by prashantagarwal** [comment]
Yeah, nginx drops headers with underscores, unless you have enabled them in the config.
http://nginx.org/en/docs/http/ngx_http_core_module.html#underscores_in_headers 

I am closing this issue since this is not related to Postman app.
