### ISSUE TITLE
Postman Params - Seeing double

### ISSUE THREAD

**Issue by jeff-r-skillrev** [a85/POSTMan-Chrome-Extension#3350]
## App Details:

```
Postman for Windows
Version 5.1.3
win32 10.0.14393 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:
This bug has been present for a few versions. At least for all 5.x versions.
 2. Expected behaviour:
I expect to see one row for dealing with key/value pairs on Params. Instead, I see two tables.

 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
There are none.
 4. Screenshots (if applicable)
![image](https://user-images.githubusercontent.com/11765949/28986978-500cc904-7937-11e7-9653-389e9bafb553.png)

Repro problem:
Start a new request tab in Postman.
Use the URL "https://swapi.co/api/people"
Click the "Params" button
Notice that there are two tables with columns "Key", "Value", and "Description". Not sure which one to use...so I put my key/value pair in the first one.

This bug results in no problematic behavior (the request still works, and passes in collection runner). It's just confusing to have 2 tables. It also causes problems when exporting to Newman (will file a separate bug for that).

**Comment by ghost** [comment]
Just an observation. I see two tables as well when I have both path params and query params. The top table seems to be for path params, and the bottom table for query params. It threw me at first, but I've gotten used to it.

**Comment by jeff-r-skillrev** [comment]
Thanks for explaining that. I at least know why they're both there now, which helps usability.

**Comment by numaanashraf** [comment]
Headers to differentiate these have been added in Postman v7.0
