### ISSUE TITLE
Feature Request: Smarter request body

### ISSUE THREAD

**Issue by matt-usurp** [a85/POSTMan-Chrome-Extension#3351]
I have this use case where an endpoint that we maintain has a bunch of optional fields, and removing these to test the endpoint is getting tedious. A way to make this less painful would be the ability to accept a different input format that doesn't affect the `mime-type`.

For example, `YAML` has comment support and it would be much easier to comment out each line so I can test the endpoint with different payloads faster. Obviously, this means that we need a drop down (or it could be smart) to support an "input type". 

**Alternatively** the ability to add many request bodies to a request and select one to send would also work. Potentially with the ability to name them too. That way I can have a few different test cases within the same endpoint.

**Note** that I am aware that I can handle this by making loads of endpoints with the different request bodies, but this is more of a cheat/hack. From a documentation point of view, this would be invaluable information too. I should also note that I am not really testing these endpoints, it's just easier to get the point across with this context.

**Comment by ratpik** [comment]
Have you checked out the new **Examples** feature in Postman? - http://blog.getpostman.com/2017/05/17/mock-responses-in-postman-by-using-examples/

**Comment by matt-usurp** [comment]
@ratpik Thanks, I didn't see this feature get released so that's cool. I will admit that this will help the use case and maybe makes my example moot, but I would like to still keep this open for input type feature.

**Comment by a85** [comment]
@matt-usurp Thank you for filing this. We have some improvements through detailed schema support that I have posted about in other threads (https://github.com/postmanlabs/postman-app-support/issues/3117#issuecomment-488125080) that should help with this and similar issues.
