### ISSUE TITLE
[Bug] [Mac] : $timestamp unresolved variable

### ISSUE THREAD

**Issue by anton-arsentyev** [a85/POSTMan-Chrome-Extension#3354]
## App Details:

```
Postman for Mac
Version 5.1.3
OS X 10.12.5 / x64
```

## Issue Report:

Shows its unresolved, but actually runtime its resolved:
 
![screen shot 2017-08-07 at 17 59 59](https://user-images.githubusercontent.com/22887126/29035281-406dc136-7b9b-11e7-91df-681660067228.png)

Mb add some description in tooltips for system variables ?

**Comment by prashantagarwal** [comment]
@anton-arsentyev Thanks for bringing this up. We realised it already and have fixed it internally. This should be available in upcoming releases.

**Comment by anton-arsentyev** [comment]
@prashantagarwal perfect!, thanks

**Comment by prashantagarwal** [comment]
@anton-arsentyev This is now fixed in latest version of Postman app (5.2.0) .
