### ISSUE TITLE
Unexpected behavior reordering items in folders

### ISSUE THREAD

**Issue by ghost** [a85/POSTMan-Chrome-Extension#3355]
## App Details:

```
Postman for Mac
Version 5.1.2 and 5.1.3
macOS 10.12.6
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:
Recently since subfolders within collections introduced.
 2. Expected behaviour:
Expect to be able to drag items within a folder to reorder. Sometimes, this will fail, and when it fails, a request item may be duplicated or deleted.
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
Not sure, but I think this error in the console is associated with the bug:
common.js:5401 Uncaught TypeError: Cannot read property 'ownerDocument' of null
 4. Screenshots (if applicable)

Steps to reproduce:
1. Create a collection.
2. Create a subfolder in the collection.
3. Create several items in the subfolder.
4. Drag the second item above the first item with the intent of making the second item the first item in the list.

Observed results:
1. When the reorder fails, the items will not change order.
2. If there are NO items in the main collection that are not in the subfolder, the item that you dragged to reorder is duplicated in the main collection outside of the subfolder.
3. If there ARE items in the main collection that are outside of the subfolder, the very last item is DELETED. 
4. This seems to happen with newly created subfolders. If you quit and restart the application, items in existing subfolders seem to behave as expected.

**Comment by prashantagarwal** [comment]
@watchwithjames Thanks for reporting this. We will investigate and try to reproduce this issue reliably. I will keep you updated about this here.

**Comment by tangochris** [comment]
I have this issue constantly. I can rarely, if ever, re-order items in a folder. Here is a screencast to demonstrate: https://www.screencast.com/t/c8hJ8dTdi. Quitting and restarting does not help. Is there a workaround?

`Postman 5.1.3 for Mac OSX 10.12.5`

**Comment by a5ync** [comment]
Same here. I can re-order only the root-level items.

@intranetchris @prashantagarwal I think I've found a workaround, at least it works on Windows. Try to duplicate the directory (using three dots menu of directory).
The new clone will allow you to re-order items.

`Windows 10 Pro, Postman 5.1.3`

**Comment by ghost** [comment]
I just saw that there's another issue that contains some comments similar to my experience in this ticket.

https://github.com/postmanlabs/postman-app-support/issues/3349

**Comment by SamvelRaja** [comment]
Hey @watchwithjames  @intranetchris @a5ync ,
We pushed out *Canary app(5.2.0-canary02)* with fixes for reordering problem you all facing, can you help in testing the same from your end?

Just download and install the app according to your os.
*NOTE:*  Backup the data in current app using Settings -> Data -> Export  for additional security.

https://dl.pstmn.io/download/channel/canary/osx_64
https://dl.pstmn.io/download/channel/canary/windows_32
https://dl.pstmn.io/download/channel/canary/windows_64
https://dl.pstmn.io/download/channel/canary/linux_32
https://dl.pstmn.io/download/channel/canary/linux_64

**Comment by SamvelRaja** [comment]
Closing in favor of #3291
