### ISSUE TITLE
AWS response redirect resign

### ISSUE THREAD

**Issue by DraakUSA** [a85/POSTMan-Chrome-Extension#3356]
## App Details:

```
Postman for Windows
Version 5.1.3
win32 10.0.14393 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:
Just encountered
 2. Expected behaviour:
Redirect without signing redirected location
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
None
 4. Screenshots (if applicable)

Set up AWS API Gateway needing signed request to return S3 PreSignedUrl with redirect (HTTP StatusCode 302) to retrieve document.  Currently Postman re-signs the URL.  This is incorrect, URL is already signed and should just be retrieved as is without signing.

**Comment by SamvelRaja** [comment]
Thanks for bringing this to our notice, we shall let you know the progress in the same thread.

**Comment by arlemi** [comment]
This was added in Postman 7.27, please update or [download the latest version of the app](https://www.postman.com/downloads/). 🙂
