### ISSUE TITLE
Oauth token request uses multiple client id authentication

### ISSUE THREAD

**Issue by mcfedr** [a85/POSTMan-Chrome-Extension#3357]
The request from Postman to Access Token URL (eg /api/oauth2/token) after getting a code includes both Basic auth and post values for client_id and client_secret

The Oauth2 RFC specifically states in [Section 2.3](https://tools.ietf.org/html/rfc6749#section-2.3) "The client MUST NOT use more than one authentication method in each request."

The server that I am using throws an error saying the client tried to use multiple forms of authentication.

**Comment by prashantagarwal** [comment]
@mcfedr We are making some improvements around Authentication flows. We will investigate it and release a fix in upcoming releases.

**Comment by harryi3t** [comment]
@mcfedr I have reproduced and confirmed the issue.
Our server is indeed setting the Basic auth header and setting the values in the body as well.

Unfortunately, we can't remove support for one of these from the server side, coz it may cause other customer's server to break (which may support only one of these.)

We are thinking (not finalized yet) to solve this issue from front-end, giving the user the ability to choose what type of authentication the server should use (maybe a check-box/dropdown to choose the authentication method.)

**Comment by mcfedr** [comment]
Choosing would make most sense. Like I said, my server is rejecting the
request because it uses both.

**Comment by harryi3t** [comment]
@mcfedr Can you try __un-checking__ the `Request access token locally` <img src= 'https://user-images.githubusercontent.com/5207331/29372418-aa89146a-82c8-11e7-9965-75dbdda990c0.png' height=500px/>

When it's checked the App makes the second request using both authentication methods
When it's unchecked our server is used which only sends the credentials in the body

**Comment by harryi3t** [comment]
@mcfedr Did the above-mentioned step work for you?

**Comment by mcfedr** [comment]
It worked, the client params were only in the body of the request.

But, the first time I did it, the server rejected the request, because it wasn't from the local network, and responded with 403 status code, and a message, and postman said everything was ok, and the error message is the stored token

![Stored token](https://i.imgur.com/LjpRdIe.png)

**Comment by harryi3t** [comment]
@mcfedr Glad it worked!
About the issue in App about not able to differentiate error vs token, 
I think displaying an error alert would give the user some idea of what went wrong. 

I will take this in our internal issue tracking system.
Closing this now. Please re-open if you face some more issues around this.
