### ISSUE TITLE
Raw body editor JSON comment

### ISSUE THREAD

**Issue by horacehylee** [a85/POSTMan-Chrome-Extension#3358]
It would be great if request raw body editor can support comment, for easier testing

**Comment by prashantagarwal** [comment]
@horacehylee You can add comments to raw body. Can you explain a bit more about the use case you are trying to achieve.

**Comment by horacehylee** [comment]
@prashantagarwal Yes, we can add comments to raw body. But it shows red error highlight for JSON.
![postman_json](https://user-images.githubusercontent.com/16369356/29103305-6d6cf97a-7cf1-11e7-8ddc-b1e9f3f47cda.png)

Can we have a similar syntax highlight as in Javascript.
![postman_json_2](https://user-images.githubusercontent.com/16369356/29103363-c4631c8c-7cf1-11e7-827e-3ef15eadd2e5.png)

**Comment by abhijitkane** [comment]
@horacehylee The JSON schema (http://www.json.org/) does not support comments. Postman supports disabling parameters for form-data / urlencoded types, but cannot do so for JSON - the entire body is treated as the request payload.

**Comment by davmrv** [comment]
@abhijitkane yeah, but this is a testing tool, not a JSON validator, commenting out JSON could be a great tool for testing APIs, because is a pain to send many information using the form-data / urlencoded tool

**Comment by M00nk1d** [comment]
@abhijitkane I completely agree with @Bl4ckf4ll It would be a greate feature to allow comments in JSON editor.

**Comment by thirtified** [comment]
Still open as https://github.com/postmanlabs/postman-app-support/issues/3117.

**Comment by markus-ethur** [comment]
Agree totaly, we should have some kind of comments

**Comment by adriannasui** [comment]
@markuspxpx @thirtified @M00nk1d @Bl4ckf4ll @horacehylee 
I can add comments in JSON raw editor. And they work as expected. Call goes through ignoring the commented-out lines
![image](https://user-images.githubusercontent.com/8627433/40293567-2e79cd78-5cda-11e8-83cd-3e5c329d95f1.png)
Maybe I am missing something here? Is this not what is needed?

**Comment by armyofda12mnkeys** [comment]
I agree, would be great to allow comments (even if you had to 'opt into' this feature [via a checkbox in the Request Area] on the specific Request that would be fine).

Sometimes I want comments to describe that param, 
or to suggest alternate values to copy/paste to test,
or maybe quickly comment out a param or a group of params when testing our web services.

**Comment by ykh** [comment]
I need this one also :+1:

**Comment by NaveenThiyagarajan** [comment]
+1 It would be great if we have this feature.

**Comment by Ben-Mark** [comment]
+1 A must feature

**Comment by lord5et** [comment]
+1 Would be great to have this feature

**Comment by YuliaLoyko** [comment]
+1 looking for it as well

**Comment by kid1412621** [comment]
+10086

**Comment by arthurlauck** [comment]
Must implement

**Comment by z3ugma** [comment]
+1

**Comment by FeChagas** [comment]
+1

**Comment by pbindy** [comment]
+1

**Comment by chunkai-meng** [comment]
+1

**Comment by julienloizelet** [comment]
+1

**Comment by Nicolai6120** [comment]
You can trim all comments before sending JSON data, you just provide the handy way to present addditional information for new API users, who will use this method. Like some kind of specification. It can be separated field, but showed on screen at the same time with JSON data. Yeah, we have a @comments@ link at the right top corner, but it is absolutely not convinient!

Look what we have in swagger:
![image](https://user-images.githubusercontent.com/6821061/52125974-19d9a580-263f-11e9-910f-e6b48fc262fb.png)

**Comment by Matreshqa** [comment]
+1

**Comment by carlnoval** [comment]
+1

**Comment by spooks7er** [comment]
+1

**Comment by lalit-lintel** [comment]
+1

**Comment by Jakems777** [comment]
+1

**Comment by gmiahiang** [comment]
+1

**Comment by anrito** [comment]
+1

**Comment by ofesenko** [comment]
+1

**Comment by vloctb** [comment]
+1 for this feature

**Comment by jonyzp** [comment]
+1 now it's mandatory

**Comment by ramesh2014** [comment]
+1 for this feature.

**Comment by jeremyml** [comment]
+1 It would be nice

**Comment by myaming** [comment]
+1

**Comment by OpitiCalvin** [comment]
+1 this feature is needed

**Comment by Alfian5229** [comment]
+1 for this feature

**Comment by bilal68** [comment]
+1 for this feature

**Comment by paulmwatson** [comment]
+1 for this feature

**Comment by cbrownfieldpp** [comment]
Please do this. +1

**Comment by TuringZhu** [comment]
+1

**Comment by ViettelGroup-hungnd67** [comment]
+1 although the request is opened from Aug 8, 2017 and today is July 4 2019

**Comment by Frost-on-Web** [comment]
Well... +1 =/

**Comment by Messhias** [comment]
+1

**Comment by facundoperezh** [comment]
+1

**Comment by sqiubgl** [comment]
+1!!!

**Comment by Klaym3n** [comment]
+1! That would be great feature!

**Comment by edisonX-sudo** [comment]
@a85 it will be horrible 4 documenting the http Api using json without this feature. +1 for this feature

**Comment by miguel719** [comment]
+1

**Comment by sriharshagangadhar** [comment]
Not yet implemented! Please some one look into this

**Comment by ZoharHedri** [comment]
+1

**Comment by huytx0909** [comment]
+1

**Comment by leoliew** [comment]
+1

**Comment by rishabhprakash** [comment]
+1 for this feature

**Comment by n8kolenberg** [comment]
+1 for this feature

**Comment by shkrwnd** [comment]
+1 for this feature.
Well you can show the editor request as well as actual request that will be sent.
It is also good if we are testing multiple key value pairs in patch request having more than 50 fields.
Because of this lacking feature , I have to save request to another editor and copy paste it to postman for testing each subsequent request.
Really this feature will save my time and others too.

**Comment by touficSl** [comment]
+1 for this feature

**Comment by sezini** [comment]
+1 for this feature

**Comment by stonedem0** [comment]
+++

**Comment by Aex12** [comment]
I also need this feature.

**Comment by M-Yankov** [comment]
~I do not know how much `+1` is required this to be implemented. Is this planned to be implemented in the next year ?~

Hm... after a little testing this is working no matter that the editor shows red icon for error. 
V 7.7.3, Windows 10 x64

**Comment by abdvel** [comment]
+1

**Comment by micongjie** [comment]
+1 for this feature

**Comment by einnor** [comment]
+1

**Comment by yunji7** [comment]
+1

**Comment by ddcatgg** [comment]
+1

Or you can keep the raw mode, but add a table editing mode like `form-data` to json to generate json, which can also achieve the ability to add comments to json.

**Comment by mrdulin** [comment]
+1, for macOS, shortcut should be <kbd>command</kbd> + `/`

**Comment by fabriziospurio** [comment]
+1

**Comment by NastassiaZ** [comment]
actually it would be great feature which will make our work more productive. +1 to it

**Comment by senthazalravi** [comment]
Badly want the commenting in the body request itself, I need to mark some of the tests with different body requests and I have no way to communicate to the other testers. Kindly consider.

**Comment by jemyto** [comment]
+1

**Comment by holger82** [comment]
+1

Soo Neides Feature. Swagger is the wenig Place for nen General comments and putting it in a separate place  outside postman is another media break.

**Comment by bhalash** [comment]
+1 for this!

**Comment by nalliot** [comment]
+1 It would be a very nice feature to document the requests!

**Comment by agrofcsik** [comment]
+1 (here we are in 2020, roughly 3 years after this thread was created, 72 comments later) and this still doesn't exist. Pretty please with sugar on top?

**Comment by bearcatharish** [comment]
+1

**Comment by softmantk** [comment]
+1

**Comment by ghost** [comment]
Would be really helpful.

**Comment by yankip** [comment]
+1

**Comment by tradahmed** [comment]
that will be much better 
and Also for searching we need a tool like VS searching entire solution or open document.

**Comment by rahmatputrawiranata** [comment]
+1 yeah it will be much better

**Comment by Aisahamzah** [comment]
+1 would be very helpful

**Comment by avaitonis** [comment]
+1 This would be great feature. We are sharing Postman request and json payloads are huge. Now comments are saved in Excel, but because of number of fields this is difficult to manage.

**Comment by RamNow** [comment]
+1 this feature would be very helpful

**Comment by RomainLapeyre** [comment]
+1

**Comment by NathanThiya** [comment]
+++++

**Comment by emiliogarza** [comment]
+1 I would love to see this feature, is there a reason this can't be done? As stated above, this is a testing tool and not a JSON validation tool, this can help me to leave some optional params for testing in a single request, instead of multiple requests in a collection that are similar.

**Comment by imokweb** [comment]
+1 We're going for the record 🏆

**Comment by Elixor** [comment]
+1 **I would really appreciate to see some way how to comment multiple lines by keyboard shortcut.**

**Comment by Mont4** [comment]
+1

**Comment by shsong** [comment]
+1

**Comment by pankajk07** [comment]
We heard you guys. We are working on this and will be available in one of our upcoming releases. Thanks for the feedback

**Comment by pankajk07** [comment]
Just to set clear expectations regarding the previous [comment](https://github.com/postmanlabs/postman-app-support/issues/3358#issuecomment-628375224), we will only be fixing the syntax highlighting part wherein adding the comment in the JSON body will not show error in the editor.

**Comment by Pacheco95** [comment]
+1

**Comment by cto-pripeljisi** [comment]
+1

**Comment by trta2352** [comment]
+1

**Comment by SanhDoan** [comment]
+1

**Comment by BlackHades** [comment]
+1

**Comment by karunais13** [comment]
+1 this feature would be very helpful

**Comment by kevinohara80** [comment]
+1

**Comment by edwardchew97** [comment]
+1

**Comment by nvseerx** [comment]
This is very helpful to add as a feature for people trying to learn new APIs that have various body structures for the requests, comments would make this much easier! ++++++++++++

**Comment by smashah** [comment]
This issue really hit me like a brick wall when developing with Postman. Very disheartening. I wouldn't mind contributing to a bounty for this to get implemented ASAP. It's been more than 3 years!!!!!!

**Comment by mat-ale** [comment]
+1

**Comment by Elixor** [comment]
I wonder using shortcut : ctrl + k, c - is possible to comment multiple lines (same as in VS). But how can I uncomment them again? :-P Shortcut: ctrl + k, u - will uncomment but it also set all to uppercase :) any ideas? Thanks!

**Comment by cheneyweb** [comment]
+1

**Comment by filmico** [comment]
As @Elixor has pointed out, Ctrl + k + U is uncommenting but also uppercasing the selections. Fixing this will help many people!! Cheers

**Comment by silverjohnes** [comment]
+100

**Comment by AkariMarisa** [comment]
I'm using this script as my pre-request script to remove comments in raw json data, and it's kinda works.
```
var rawData = pm.request.body.raw
var strippedData = rawData.replace(/\\"|"(?:\\"|[^"])*"|(\/\/.*|\/\*[\s\S]*?\*\/)/g, (m, g) => g ? "" : m)
console.info(strippedData)
pm.request.body.raw = strippedData
```

**Comment by paulmwatson** [comment]
That's an interest idea @AkariMarisa, using tooling rather than changing the JSON "standard". Thanks for it.

**Comment by silverjohnes** [comment]
> I'm using this script as my pre-request script to remove comments in raw json data, and it's kinda works.

Could you be so king to show me how you mark comments?

**Comment by AkariMarisa** [comment]
@silverjohnes 
![2021-04-20_08-48](https://user-images.githubusercontent.com/13818070/115320867-3d07b580-a1b5-11eb-863d-539cf976f534.png)
![2021-04-20_08-51](https://user-images.githubusercontent.com/13818070/115321072-abe50e80-a1b5-11eb-9c8a-e6e19be636d4.png)
![2021-04-20_08-50](https://user-images.githubusercontent.com/13818070/115320949-67f20980-a1b5-11eb-83fd-028658929fd3.png)
I use folder as a container to manage APIs, so I can add a 'root' pre-request script to rid off the comments.
I only test raw json data, and it's works for me. Maybe someday someone can improve this method.
ps. Please ignore the Chinese that on the pictures.

**Comment by julienloizelet** [comment]
> I'm using this script as my pre-request script to remove comments in raw json data, and it's kinda works.
> 
> ```
> var rawData = pm.request.body.raw
> var strippedData = rawData.replace(/\\"|"(?:\\"|[^"])*"|(\/\/.*|\/\*[\s\S]*?\*\/)/g, (m, g) => g ? "" : m)
> console.info(strippedData)
> pm.request.body.raw = strippedData
> ```

I tried this but it failed (unfortunately): the logged data is ok but it seems that the body sent remains unchanged.
Maybe I'm doing something wrong but I found an issue related to this : https://github.com/postmanlabs/postman-app-support/issues/4808
When I read this issue, I understand that changing the body request in a pre-request script is not possible. @AkariMarisa : what is your secret ?

**Comment by AkariMarisa** [comment]
@julienloizelet You're right, my method doesn't change the JSON. I thought it worked because my testing server can reformat JSON data, and forgot this. I'm trying to figure out why postman's pre-request script cannot update body.

**Comment by codenirvana** [comment]
Hello everyone 👋

To temporarily unblock this, **Postman v8.3.0** added support for programmatically mutating the request body.
So, the workaround suggested by @AkariMarisa will work now. 🎉 

The following `pre-request` script will remove comments from the raw mode body.
```js
// Strip JSON Comments
if (pm.request.body.mode === 'raw') {
    const rawData = pm.request.body.toString();
    const strippedData = rawData.replace(/\\"|"(?:\\"|[^"])*"|(\/\/.*|\/\*[\s\S]*?\*\/)/g, (m, g) => g ? "" : m)

    pm.request.body.raw = strippedData;
}
```

Also, we'll soon add native support for this in the app.

**Comment by ilya-git** [comment]
The code above changes Content-Type to `text/plain`, if you API does not accept that one can add something like this:

```js
pm.request.headers.add({key: 'Content-Type', value: 'application/json'});
```

to fix it. There is probably a simpler way but I did not figure it out.

**Comment by gooza** [comment]
To uncomment the lines i use find "//" and replace in selection. It is anoying but better than comment out line by line.

**Comment by LuckyTil** [comment]
JSON text.
Ctrl-K, Ctrl-U uncomments current line OK, when block is not selected.
When block is selected, Ctrl-K, Ctrl-U uncomments block and UPCASES it.
Fix, please.

**Comment by rr-justin-hanselman** [comment]
+1 to this feature.  For complicated legacy systems, I have the hardest time helping my QAs and new developers understand all the permutations of a payload.

Bloating the pre-request scripts would only further add confusion.

**Comment by asoltesz** [comment]
+1 to this feature, badly needed.

In Postman, there is no good feature to document the request, so everybody would like to do it in the body.

The Documentation panel is mostly useless. Is is very hard to notice / read anything you put in there because it displays a lot of other contents which is not about documenting the request. 

The Comments panel can only be used with Workspaces (which is a non-starter for us).

**Comment by mayureshs** [comment]
+1 to this feature. Please fix the uppercasing issue.

**Comment by Kyreikal** [comment]
+1 to this.

The form data ui would be perfect for this. Add a new _raw-json_ tab and just have it spit out the raw json on selected variables rather than form data. Everything you need is there, type, description, key and value. Only thing that would need work is nested fields.

You can document and optionally select variables with a click.

**Comment by emiliogarza** [comment]
Why refuse a feature that clearly many people want? @Kyreikal has a good solution here ^

**Comment by AceOubahaTLI** [comment]
+1 please fix uppercasing, it makes the uncomment feature more or less unusable

**Comment by seanc** [comment]
+1 for this feature

**Comment by PeterRygeMCB** [comment]
+1

**Comment by Geet2312** [comment]
+1

**Comment by Martin-Suska** [comment]
> JSON text. Ctrl-K, Ctrl-U uncomments current line OK, when block is not selected. When block is selected, Ctrl-K, Ctrl-U uncomments block and UPCASES it. Fix, please.

I'm using `CTRL + /` to comment/uncomment, works fine in Postman 10.10.8

**Comment by ashuvyaspm45** [comment]
Hello everyone 👋
Thank you for your patience for this feature. We have added the comment support in raw json body editor in latest release (**Postman v10.13**). Please check this out and give us the feedback.

**Comment by SamehSaeed** [comment]
The issue has returned "Postman v11.2.0" when using Ctrl+k+u to un-comment while selecting the text, the text transforming to uppercase after une-commented
