### ISSUE TITLE
I have 5 to 6 collections about 100 requests and my postman always crashes.

### ISSUE THREAD

**Issue by jagadeesh666** [a85/POSTMan-Chrome-Extension#3359]
## App Details:

```
Postman for Mac
Version 4.11.0
OS X 16.4.0 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:
 2. Expected behaviour:
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 4. Screenshots (if applicable)

**Comment by prashantagarwal** [comment]
@jagadeesh666 Can you update your app to 5.1.3 and check if this is still happening. We made a lot of performance and stability fixes after 4.11.0
