### ISSUE TITLE
Runner should not stop when an error arrises

### ISSUE THREAD

**Issue by chrisron95** [a85/POSTMan-Chrome-Extension#3360]
## App Details:
```
Postman for Windows
Version 5.1.3
win32 10.0.14393 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:
always there
 2. Expected behaviour:
The runner should keep going through tests even when a simple error arrises.
3. Actual behavior:
If we make a call that results in an html error page (normal html page, starts with <!DOCTYPE html>), the runner just stops dead in it's tracks and logs in the devtools "unexpected token". It's very frustrating when I have a run that's been going for a while and an error comes up that stops the runner before it's finished and I have to start over. This error should not stop the runner. I could understand it logging the error, stating that there was an error, and then skipping that call, but the runner should not stop. I have logic in my runner tests that deal with this error, however it's useless since the runner itself won't let it continue.

This also happens if it's searching for (in my case) "_id" and it's not there. This rarely stops it, but every once in a while it does.

![image](https://user-images.githubusercontent.com/16259311/29090159-a686fb98-7c4c-11e7-8944-d25a386311c1.png)

**Comment by chrisron95** [comment]
This is also not strictly this computer. This happens on all computers I've tried on, including Mac.

**Comment by SORC3r3r** [comment]
Same here.
I edited the tests so they would not quit the runner:

```
if (responseBody.has("<!DOCTYPE html>") === true){
    test["..."] = true === true;
}
if (responseBody.has("_id") === true){
    test["..."] = true === true;
}
```

**Comment by prashantagarwal** [comment]
@chrisron95 Yeah this makes sense. We will try to enhance runner with this suggestion. I will keep you updated here about this.

**Comment by mirsoo** [comment]
To edit the tests catching this Postman incorrect behaviour is not the right approach!
Postman should not fail on getting 500 errors.
I can react on 500 error and quit test by myself if i want (with postman.setNextRequest(null))
I'm using Version 6.3.0 and it still failing on 500 error

**Comment by 21anujashah** [comment]
Is there any option to resolve this issue? Can we add relevant scripts in "Tests" section to handle these type of errors? In my single collection, I have 400+ requests. It stops after 35 requests, sometimes after 40 requests.

**Comment by nttlorand** [comment]
Any news about this issue? It was created in 2017 and several years have passed already. If this is not going to be fixed ever due to the "Low" priority then maybe a professional could give us a pertinent solution. Thanks!

**Comment by m3dbedb** [comment]
I would add my 5 cents for option "halt on errors".

**Comment by half-eaten-apple** [comment]
Much needed feature in 2021 !
When i run the collection using Newman CLI, then only i am able to run all the API's even if some of them fails.
Postman should have this feature to treat failed test cases as Soft Assertions and keep the collection execution running.

**Comment by Rabadash8820** [comment]
@giridharvc7 If you're going to close #10391 as a duplicate of this one, then could you please provide an update here? These early exits during long collection runs are quite frustrating, and this issue is now over 4 years old...

**Comment by xaviergm** [comment]
Any updates on this issue?

**Comment by Freakishmahesh** [comment]
Awaiting for the resolution. Much needed feature.!

**Comment by wnagelx** [comment]
Any updates on this issue?

**Comment by LTRichHouse** [comment]
Awaiting resolution. Much needed feature!

**Comment by dcstamps** [comment]
I see this will likely never be fixed since it's been outstanding for 5 years.  I can't imagine having issues that impacts our customers for 5 years and just ignoring their countless pleas for a fix.  Bad business.

**Comment by malvikach** [comment]
@dcstamps Apologies for your experience and for not getting back on this thread sooner! I can definitely see how an error might force you to restart the run and you might end up losing time over it. 

We have taken note of this feature request! I will update this thread as soon as we have some news on this. 

If you would like to talk to me 1:1 about the above issue or any other similar issues you are facing- here is a [link](https://calendly.com/malvika-chaudhary/v10-feedback) to my calendar that you can use to schedule time with me.

**Comment by lucianamerege** [comment]
> @dcstamps Apologies for your experience and for not getting back on this thread sooner! I can definitely see how an error might force you to restart the run and you might end up losing time over it.
> 
> We have taken note of this feature request! I will update this thread as soon as we have some news on this.
> 
> If you would like to talk to me 1:1 about the above issue or any other similar issues you are facing- here is a [link](https://calendly.com/malvika-chaudhary/v10-feedback) to my calendar that you can use to schedule time with me.

Any updates?

**Comment by mirsoo** [comment]
Hi Postman SupportI have experienced that Postman has implemented test run limitation from version 10Because of that I will not use Postman in the feature any more.Sorry but that was very destructive decision and you will lose a lot of customers.It's so sad.I will close this issue soonBest regards Mirsad Am 21.03.23, 18:48 schrieb Luciana ***@***.***>:

   
   
   @dcstamps Apologies for your experience and for not getting back on this thread sooner! I can definitely see how an error might force you to restart the run and you might end up losing time over it. 
   We have taken note of this feature request! I will update this thread as soon as we have some news on this. 
   If you would like to talk to me 1:1 about the above issue or any other similar issues you are facing- here is a link to my calendar that you can use to schedule time with me. 
   
  Any updates?

**Comment by Rabadash8820** [comment]
> I will close this issue soon

@mirsoo You can't do that if you're not a maintainer or the Issue author.

**Comment by malvikach** [comment]
Hi All,

I have provided some updates regarding this issue [here](https://github.com/postmanlabs/postman-app-support/issues/3845#issuecomment-1479079618)

Please do take a look and add your thoughts.  

@mirsoo Could you drop us a note at help@postman.com regarding the limits. Our goal is to enable your workflows as seamlessly as possible. If you wish to discuss this instead, please use [this calendly link](https://calendly.com/malvika-chaudhary/v10-feedback) to schedule some time with me.

Regards,
Malvika

**Comment by mirsoo** [comment]
Hi Malvikathat's great.Hopefully Postman will implement this feature soon!I will set an appointment regarding run limitations with you.Best regards MirsadAm 22.03.23, 10:25 schrieb Malvika Chaudhary ***@***.***>:

   
  Hi All, 
  I have provided some updates regarding this issue here 
  Please take a look and add your thoughts. 
  @mirsoo Could you drop us a note at ***@***.*** regarding the limits. Our goal is to enable your workflows as seamlessly as possible. If you wish to discuss this instead, please use this calendly link to schedule some time with me. 
  Regards, Malvika

**Comment by malvikach** [comment]
Hi All,

Glad to inform everyone that this improvement has been released in the latest Postman release (version 10.13). You can now customize the Collection Runner to continue to run if an error occurs.

![ezgif com-video-to-gif (2) (1)](https://user-images.githubusercontent.com/89449769/232977794-f287054f-b88a-416a-a26b-a46c4d102581.gif)

The setting will be checked by default i.e. by default Runner will stop the execution in case of an error. If you wish to continue runner to execute, you can uncheck this setting and Postman will remember it throughout your session for all subsequent runs unless you change it.

Hope this helps your workflows. Once again, thanks a lot for sharing your feedback on this.

Please note: The Postman version update is being rolled out, you will get it in the next 1-2 days if you haven't already.

Cheers,
Malvika

**Comment by dcstamps** [comment]
This is great news, thank you so much!

**Comment by xaviergm** [comment]
Awesome! Thank you very much @malvikach !

**Comment by LTRichHouse** [comment]
Wonderful - thanks @malvikach . Just used it. Remembers my turning it off too -yay! ☺️
