### ISSUE TITLE
Pre-request Script: Wrong MD5 encoding when using dynamic variables $timestamp & $randomInt

### ISSUE THREAD

**Issue by dareaze** [a85/POSTMan-Chrome-Extension#3362]
## App Details:

```
Postman for Windows
Version 5.1.3
win32 10.0.10586 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:
Notice the error after testing new API request using pre-test script dynamic variables $timestamp and $randomInt. The response success IF define key=fixed variable.
 2. Expected behaviour:
Response message success
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 4. Screenshots (if applicable)
![image](https://user-images.githubusercontent.com/23372437/29104436-fe4034ac-7cf7-11e7-943f-5aafd39b8afb.png)

![image](https://user-images.githubusercontent.com/23372437/29104481-5f9d0d9c-7cf8-11e7-913c-5d9c004f1895.png)

**Comment by prashantagarwal** [comment]
@dareaze We don't support dynamic variables inside Pre-request script and test script.
https://www.getpostman.com/docs/postman/environments_and_globals/variables

If you want you can use vanilla javascript to mimic the $timestamp
