### ISSUE TITLE
Concurrent Environments with precedence

### ISSUE THREAD

**Issue by LouVaiano** [a85/POSTMan-Chrome-Extension#3363]
## App Details:
```
Postman for Chrome
Version 5.1.3
win / x86-64
Chrome 60.0.3112.90
```

## Feature Request:
Environments allow a set of pre-configured values to be defined. When shared they allow others to access these values. However sometimes I would like to override one or more of these values with locally personalised values. For example a shared Environment might define a key with a generic email address, noreply@mydomain.com. However when I use that key locally I want my personal email address, me@mydomain.com.

A possible implementation is to prioritise Environment files such that keys in a higher priority Environment file override that in a lower priority Environment file. I could then configure a general, and possibly shared shared, Environment file to have lower priority than my personal Environment file.

I would be happy with support for only two levels of Environment files.

Regards,
Lou

**Comment by prashantagarwal** [comment]
@LouVaiano Yeah that makes sense. So we do prioritise Environment variables over Global variables as of now, it is just that you cannot share Global variables.

**Comment by LouVaiano** [comment]
Thanks for getting back to me.

Just so I am clear, does that mean my request is on the roadmap or so I
make do with the Globals, which doesn't meet my objectives?

Regards,
Lou

Lou Vaiano
LTX Pty Ltd
PH: 0422 660 798
EM: lou.vaiano@ltx.com.au

**Comment by prashantagarwal** [comment]
@LouVaiano We will discuss it internally and see if this use case can be solved by making Global variables shareable, so that you can share global variable **noreply@domain.com** and then in your environment variable override this with **me@domain.com**

**Comment by LouVaiano** [comment]
Excellent, thanks.


Lou

Lou Vaiano
LTX Pty Ltd
PH: 0422 660 798
EM: lou.vaiano@ltx.com.au

**Comment by sankalp0o** [comment]
Hi @LouVaiano, 
Just wanted to check in if you are able to use workspaces to solve your particular use case. Globals now belong to a workspace and are shareable with the team (along with the workspace). There are also variables at a collection level. This should allow you to define a precedence level.

In addition to this, we're also working on a concept called sessions which allow you to define local values for variables. Read about it at https://community.getpostman.com/t/sessions-in-postman/1925 and feel free to drop in comments.

**Comment by vkaegis** [comment]
Hey @LouVaiano, you should be able to override initialised values of variables with "current" values now. Closing this issue, feel free to open another if you have more feedback around this.
