### ISSUE TITLE
Export v2 collection results in empty collection json file - regression

### ISSUE THREAD

**Issue by hoogenbj** [a85/POSTMan-Chrome-Extension#3364]
## App Details:
Postman for Linux
Version 5.1.3
linux 3.16.0-38-generic / x64

## Issue Report:
 1. This started happening recently
 2. Expected behaviour: export a collection that contains everything
 3. Instead an empty collection gets exported:
{
	"variables": [],
	"info": {
		"name": "Product Summary",
		"_postman_id": "af41194f-9ee7-544c-6300-de9279cbab10",
		"schema": "https://schema.getpostman.com/json/collection/v2.0.0/collection.json"
	},
	"item": []
}

**Comment by sdnts** [comment]
Hi @hoogenbj, I was unable to reproduce this. Is this still happening for you?

**Comment by hoogenbj** [comment]
It happens to collections that I've created with older versions of 
Postman. New collections are fine. It is a big nuisance to recreate such 
old collections but at least it works then. So I guess this can be closed.

**Comment by sdnts** [comment]
@hoogenbj That shouldn't be needed. Do you remember approximately when you created these problematic collections? This will help me narrow down what Postman version you were on so I'll be able to replicate the problem.

**Comment by hoogenbj** [comment]
Sorry, I cannot remember...

**Comment by sdnts** [comment]
@hoogenbj Do you use Sync? If yes, can you also try logging out of the app, and then logging in? This will fetch all your collections again, just in case collections are somehow corrupted. You should then be able to export correctly.
Without Sync, your app is the only source of the collections, so this won't work.
