### ISSUE TITLE
Active or Default Environment state is missing

### ISSUE THREAD

**Issue by dgofman** [a85/POSTMan-Chrome-Extension#3366]
After importing a project I would like to replace "Environment Drop-down" by last selected Environment in the dump file. 

We have two solutions:
1) Add a new property value on top level
{
	"version": 1,
        **"activeEnvironment": "NewEnvironment",**
	"collections": [
...
2) Adding flag in the array of environments
        "environments": [
		{
			"name": "OldEnvironment",
			"values": [
...
			]
		},
		{
			"name": "NewEnvironment",
			**"selected": true,**
			"values": [
...
			]
		}
	],

Thanks,
David

**Comment by prashantagarwal** [comment]
@dgofman That's a good suggestion. We will try to fit this in our roadmap. I will keep you updated about this here.

**Comment by a85** [comment]
I don't think this is going to make it to the app. Importing from a data dump and changing state is not an expected behavior.
