### ISSUE TITLE
Postman should not round 64-bit integer ids

### ISSUE THREAD

**Issue by joelpresence** [a85/POSTMan-Chrome-Extension#3368]
## App Details:

```
Postman for Mac
Version 5.1.3 (5.1.3)
macOS 10.12.6
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:
Recently
 2. Expected behaviour:
A 64-bit integer id returned in a JSON body should be preserved exactly and not truncated.  Javascript is rounding it by storing it as float64 which truncates the mantissa to 53 bits.
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 4. Screenshots (if applicable)

Return a HTTP response to PAW including 64-bit integers >= 2^53.

Our large team is considering moving from PAW (Mac only) to Postman.  We're willing to pay for Postman pro, but it's not OK that Postman (via Javascript) truncates integers larger than 2^53.  These are ids, so they need to be perfectly precise.  It's too much of a burden for us to start also returning "id_str" or doing some custom JSON rendering, so if this can't be fixed, we're just going to buy more units of PAW for Mac rather than pay for Postman.  And I **do** like Postman.  :-). Help me out here please!

I guess I would expect PAW to allow me to do something like:

```
var jsonData = JSON.parse(responseBody);
postman.setEnvironmentVariable("user_currency_grant_result_id", jsonData.Grants[0].UserCurrencyGrantResultId);

// Postman should NOT round jsonData.Grants[0].UserCurrencyGrantResultId - it is an int64, preserve its full precision please!
```

I guess I'm imagining something like:

```
var jsonData = JSON.parse(responseBody);
postman.setEnvironmentVariable("user_currency_grant_result_id", postmanGetInt64(jsonData.Grants[0], "UserCurrencyGrantResultId"));
```

You (Postman) would write the function `postmanGetInt64(obj, key)` that would return the int64 with full precision.

Or is there some way to import a javascript library to do this or some other way to access the raw JSON before it has been parsed from a dictionary into an object?

**Comment by joelpresence** [comment]
Bump.  Any updates @a85 ?  Thanks!

**Comment by prashantagarwal** [comment]
@joelpresence We are already tracking this in #2736 . I am closing this as duplicate issue.
