### ISSUE TITLE
[UI Improvement] - When successfully sharing an environment, the fields are cleared and no successful message is displayed.

### ISSUE THREAD

**Issue by Faz540** [a85/POSTMan-Chrome-Extension#3370]
Windows App. 64 Bit, Windows 10.

Open 'Manage Environments' and the popup appears.
Click 'Share' on any environment.
Notice the fields have been cleared and no success message is displayed to the User.
When this first occurred, I thought that the sharing was unsuccessful.

**Before:**
![image](https://user-images.githubusercontent.com/9334128/29269938-18ba340c-80ec-11e7-8939-91d6c4caef2a.png)

**After clicking Share:**
![image](https://user-images.githubusercontent.com/9334128/29269941-26c1378a-80ec-11e7-8496-9f1bef44ff96.png)

**Comment by prashantagarwal** [comment]
@Faz540 Thanks for pointing this out. We will get this fixed in upcoming releases.

**Comment by a85** [comment]
Environment templates are now transitioned off to environments through our new feature called Workspaces. More info here: https://www.getpostman.com/docs/postman/workspaces/intro_to_workspaces
