### ISSUE TITLE
"Manage Environments" modal should have a filter

### ISSUE THREAD

**Issue by curtisgibby** [a85/POSTMan-Chrome-Extension#3371]
## App Details:
```
Postman for Linux
Version 5.0.0
linux 3.19.0-32-generic / x64
```
In the "Manage Environments" window, when you have a lot of environments, it would be nice to have an input box to quickly filter down to the specific environment you're looking for, rather than scrolling through a long list.

**Comment by prashantagarwal** [comment]
@curtisgibby Thanks for this suggestion. We will try to get this included in future releases.

**Comment by tienle488** [comment]
Yes, please!  Thank you.

**Comment by curtisgibby** [comment]
Here it is, three years later, and I'm still scrolling through several hundred environments. :cry:

**Comment by giridharvc7** [comment]
This is fixed in our latest update. Please update the app to 8.x or you can use the Web version of postman! Let us know what you think!
