### ISSUE TITLE
multiline json,  Add new "JSON  Graphql"  in dropdown in Body section , like graphiql

### ISSUE THREAD

**Issue by webmobiles** [a85/POSTMan-Chrome-Extension#3375]
When I send the graphql query string, I must to do it in just one line, 

{"query":"query{allQuotes{text}}"}

it's possible to add a new 'json graphql' , so i can type the query in multilines like graphiql, in type like this:

```
{"query":"

query {
  allQuotes {
    text
  }
}

"}
```

**Comment by prashantagarwal** [comment]
@webmobiles We are already tracking this in #1669 . Supporting Graphq is there in our [roadmap](https://trello.com/b/4N7PnHAz/postman-roadmap-for-developers).
