### ISSUE TITLE
Runner doesn't run all folders

### ISSUE THREAD

**Issue by abirstolov** [a85/POSTMan-Chrome-Extension#3380]
## App Details:
```
Postman for Chrome
Version 5.1.3
win / x86-64
Chrome 60.0.3112.90
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there: recently
 2. Expected behaviour: run tests in all sub foldfolders

To Reproduce:
- Select a collection with sub-folders
- Run with the _Runner_
Results:
a folder has been skipped, ran other 2 folders
Expected: 
run all folders

**Comment by sdnts** [comment]
@abirstolov Are you seeing this for all collections or some specific collections? If you use Sync, can you make sure all your changes are on your [Postman Dashboard](https://app.getpostman.com/dashboard/collections/private) are intact, then log out of the app and login again? This should fetch all collections again, in case some collections are corrupted.

We'll be releasing a new version next week (5.2), that should fix most of these collection integrity issues. Can you let me know if you still see this after 5.2 goes out?

**Comment by prashantagarwal** [comment]
@abirstolov We were unable to reproduce this on our end. If you are still facing this issue, feel free to reopen this.

**Comment by abirstolov** [comment]
I got version 5.2 and it still happens.
I'm getting different calls run from different folders
in one it runs 1 out of 15
in another 1 out of 8
and in another 4 out of 4
and in another one also 4 out of 4

What information can I send you to duplicate it?
