### ISSUE TITLE
Allow body for GET requests.

### ISSUE THREAD

**Issue by JoshMcCullough** [a85/POSTMan-Chrome-Extension#3381]
## App Details:
```
Postman for Chrome
Version 5.1.3
win / x86-64
Chrome 60.0.3112.90
```

## Issue Report:
GET requests should allow a body since it is allowed in the HTTP spec. When preparing a GET request in Postman, the "Body" tab is disabled and a body cannot be entered.

**Comment by prashantagarwal** [comment]
@JoshMcCullough We are already tracking this issue here #2729. I am closing this as duplicate
