### ISSUE TITLE
Unicode characters in URLs are not percent encoded

### ISSUE THREAD

**Issue by IlianIliev** [a85/POSTMan-Chrome-Extension#3382]
## App Details:

```
Version 5.1.3 (5.1.3)
macOS Sierra
Version 10.12.6
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:
I have a local app running. When I try the following address `http://localhost/ägg` I can see that the request comes unchanged. 
If I do the same request in Chrome I see the `ä` character percent encoded.
I have found it recently and I am not sure if it has been the same before.

 2. Expected behaviour:
Unicode characters in URLs should be automatically percent encoded the same way as in your browser.

 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):

GET file:///Users/ilian/Downloads/Postman.app/Contents/Resources/app/html/mode-auto.js net::ERR_FILE_NOT_FOUND

 4. Screenshots (if applicable)

**Comment by prashantagarwal** [comment]
@IlianIliev Thanks for reporting this. We will investigate this issue and release a fix in upcoming Postman releases

**Comment by yeegr** [comment]
I second this issue. A simple get statement with UTF-8 characters in Chrome returns the correct document, but fails in Postman. I console.log(request.url), Chrome sends a correctly escaped string whereas Postman does not.

**Comment by reem-codes** [comment]
Has this been fixed yet? my postman desktop app shows the same issue

**Comment by bluppfisk** [comment]
Issue still present in Postman 6.1.4 today ):

**Comment by SamvelRaja** [comment]
We are following a master thread #4555 to track all issues related to Url encoding. Please follow that issue for updates.

**Comment by codenirvana** [comment]
This is fixed in the latest version of the Postman app (v7.20.0) by enabling the "Use next generation URL processing" setting as mentioned in #8154.
