### ISSUE TITLE
401 Unauthorized response prevents sign-in window

### ISSUE THREAD

**Issue by markkimsal** [a85/POSTMan-Chrome-Extension#3384]
When requesting an OAuth2.0 authorization page, if the server responds with 401 and a login form Postman will not open the window and allow the opportunity to login.

**Comment by abhijitkane** [comment]
@markkimsal Can you mention what version/platform of the app you're seeing this with (Chrome app or the native app)? If you're using the Chrome app, you can try switching to the native version (https://www.getpostman.com/apps) - we have greater control over the OAuth2 flows there.

Is there a publicly-accessible URL we can try to reproduce this with?

**Comment by markkimsal** [comment]
It only happens with the Chrome plugin.  I don't have a public endpoint at the moment.

**Comment by harryi3t** [comment]
@markkimsal When the server responds with 401, which auth is it protected by (basic/digest/NTLM)?

**Comment by markkimsal** [comment]
@harryi3t It doesn't seem like there's a chrome plugin anymore.  The desktop app doesn't open browser windows at all, so this issue doesn't apply.  It was irrespective of the presence or value of any WWW-Authenticate header.

**Comment by markkimsal** [comment]
@harryi3t I just tested the desktop app and it works fine.  If there is no more chrome plugin then this issue no longer applies.
