### ISSUE TITLE
Postman Echo - Delete Cookies Tests have wrong descriptions

### ISSUE THREAD

**Issue by Yardglass** [a85/POSTMan-Chrome-Extension#3387]
## Issue Report:

1. Download Postman Echo JSON from here: https://www.getpostman.com/view-collection/cb422f2f53444914b07f
2. Import the JSON
3. Go to Cookies->Delete Cookies and look at the tests

Expected: 

tests["Body does not contain cookie foo1"] = !('foo1' in responseJSON.cookies);
tests["Body does not contain cookie foo2"] = !('foo2' in responseJSON.cookies);

Actual:

tests["Body contains cookie foo2"] = !('foo2' in responseJSON.cookies);
tests["Body does not contain cookie foo2"] = !('foo1' in responseJSON.cookies);

As you can see the descriptions don't match what is being tested for (and when they both pass it says that it does and doesn't contain foo2).

-->

**Comment by prashantagarwal** [comment]
@Yardglass Hey, I am not sure what is wrong here.

<img width="609" alt="screen shot 2017-08-15 at 12 31 13 pm" src="https://user-images.githubusercontent.com/3762808/29305319-bdcf2532-81b5-11e7-96b2-34d5ef7a8772.png">

**Comment by Yardglass** [comment]
@prashantagarwal thanks for the quick look at this - the delete method is removing both foo1 and foo2, (https://echo.getpostman.com/cookies/delete?foo1&foo2) but the tests aren't showing that at all. The above tests you are showing do not match what I am seeing though, but are also wrong if your method is the same?

It's deleting both cookies in my version which I downloaded from here: https://www.getpostman.com/view-collection/cb422f2f53444914b07f

**Comment by Yardglass** [comment]
@prashantagarwal 
If I get the Postman Echo collection this way:

1. Go to https://docs.postman-echo.com/ 
2. Click [>Run in Postman]

I get different tests which fail. The Delete Cookies URL still contains params to delete foo1 & foo2 (https://postman-echo.com/cookies/delete?foo1&foo2).

The (failing) tests from the above location are:

    tests["Body contains cookie foo1"] = 'foo1' in body.cookies;
    tests["Body contains cookie foo2"] = 'foo2' in body.cookies;

As you can see it's checking for these cookies to exist which is wrong. They should be:

    tests["Body does not contain cookie foo1"] = !('foo1' in responseJSON.cookies);
    tests["Body does not contain cookie foo2"] = !('foo2' in responseJSON.cookies);

Here's a screenshot:

![image](https://user-images.githubusercontent.com/1118977/29344229-f5e7ea7c-8268-11e7-974f-8745c469218b.png)

Cheers,

Yardglass

**Comment by kamalaknn** [comment]
@Yardglass Ah yes, the tests should have been the other way. We'll take a look at it. Thanks for letting us know.

**Comment by Yardglass** [comment]
Thanks @kamalaknn, happy to help.

**Comment by kamalaknn** [comment]
@Yardglass Thank you for bringing this to our notice.

We have updated the `Postman Echo` collection now. New imports will have the correct tests and test descriptions. Closing this issue now.

Cheers!
