### ISSUE TITLE
Feature Request: Reinstate Postman Interceptor applying cookies automatically (Xdebug)

### ISSUE THREAD

**Issue by voycey** [a85/POSTMan-Chrome-Extension#3392]
I use Postman along with Xdebug in PHPStorm and have done for at least a year now, however following recent updates Postman interceptor doesn't seem to be working to send the Xdebug cookies so my debugger can latch on to the request from Postman.

I can manually start the debugger and then enter the cookie value into the new Cookie Manager functionality but as XDebug generates a new cookie for each start of the debugger this adds significant time to the debugging workflow!

Previously with the Postman Interceptor Chrome app and the toggle for the interceptor in Postman, everything worked seamlessly, once a debugging session was started from within PHPStorm any request sent through postman would be automatically picked up.

**Comment by prashantagarwal** [comment]
@voycey Thanks for reporting this. We will investigate this issue and get back to you.

**Comment by RDeluxe** [comment]
I thought I did something wrong ! Good to know it's not me ...

This is a fundamental feature for me, to be able to debug correctly PHP server side code. Thanks !

**Comment by numaanashraf** [comment]
@RDeluxe @voycey Are you still facing this issue?

**Comment by geoffrothman** [comment]
@numaanashraf yes I am experiencing this as well!

**Comment by voycey** [comment]
Yes now it is a manual process but it works:

Start Xdebug from your IDE - you will get a URL that looks something like this:

http://localhost/XDEBUG_SESSION=78342

You can create a cookie in the Cookies section of Postman to have it use this cookie (Check what your cookie value is and replace there).

![image](https://user-images.githubusercontent.com/1065098/45130192-f7944680-b1ca-11e8-9dc8-75b2f20d8d97.png)

The previous functionality was much better as it was automated and meant that you didnt need to do this edit for each launch of the debugger

**Comment by abhijitkane** [comment]
@numaanashraf This is the native-app <-> interceptor issue, right?

**Comment by abhijitkane** [comment]
@voycey The new native apps support integration with the interceptor to sync cookies. Check https://community.getpostman.com/t/interceptor-integration-for-postman-native-apps/5290 for more.

Closing this issue for now. Feel free to comment if you're unable to get the cookie syncing to work.
