### ISSUE TITLE
Postman doesn't know to compare NULLs from Response Body and CSV file

### ISSUE THREAD

**Issue by dmladek** [a85/POSTMan-Chrome-Extension#3393]
## App Details:
```
Postman for Windows
Version 5.1.3
win32 10.0.14393 / x64
```

## Issue Report:
1. My test tries to compare extracted value of an element from the JSON response body.
The value of interest can be **null**. I'm using CSV file to store there expected results, so
I can compare data in responses with expected date prepared in CSV file.

## Steps to reproduce the problem
I've attached my CSV file.
[PostMan-EPIC-SF-VALIDATION.csv.txt](https://github.com/postmanlabs/postman-app-support/files/1227122/PostMan-EPIC-SF-VALIDATION.csv.txt)

**The code snippet of my test is following**
```
// a wee functional test to validate the Response summary status of the response
var response_summary_status = JSON.parse(responseBody).Response_Summary_Status__c;
tests["Validate that the Response summary status is No response"] = response_summary_status === data.response_summary_status;

// a wee functional test to validate the Processing summary status of the response
var processing_summary_status = JSON.parse(responseBody).Processing_Summary_Status__c;
tests["Is the Processing summary status completed?"] = processing_summary_status === data.processing_summary_status;

console.log("|-"+response_summary_status+"-|");
console.log("|"+data.unit_status+"|");
console.log("|-"+processing_summary_status+"-|");
console.log("|"+data.processing_summary_status+"|");
```

**The snippets of response body**
```
{
    "attributes": {
        "type": "Response__c",
        "url": "/services/data/v40.0/sobjects/Response__c/a0JP0000004jnS9MAI"
    },
    "Id": "a0JP0000004jnS9MAI",
    "OwnerId": "005P0000001HrOAIA0",
    "IsDeleted": false,
    "Name": "R0001192285",
    "RecordTypeId": "012o0000000tHPEAA2",
    "CreatedDate": "2017-03-07T01:17:12.000+0000",
    "CreatedById": "005P0000001HrOAIA0",
    "LastModifiedDate": "2017-08-15T04:53:49.000+0000",
    "LastModifiedById": "005P0000001XsyMIAS",
    "SystemModstamp": "2017-08-15T10:30:23.000+0000",
    "LastActivityDate": null,
    "LastViewedDate": "2017-08-16T02:27:21.000+0000",
    "LastReferencedDate": "2017-08-16T02:27:21.000+0000",
    "Collection_Instance__c": "a03P0000004VCiAIAW",
    "Created_From_Response_Id__c": null,
    "Response_Summary_Status__c": "No Response",
    "Processing_Summary_Status__c": null,
    "Mailable__c": "Y",
    "CO_6__c": null,
    "X75_Indicator__c": false
}
```

**Console log**
```
GET
https://xxxxxxx.cs4.my.yyy.com/services/data/v40.0/sobjects/Response__c/a0JP0000004jnSHMAY	04:15:23.568
|-No Response-|				04:15:24.385
|Refused|				04:15:24.393
|-null-|				04:15:24.406
|null|					04:15:24.410
```
It is obvious from the console output that both "processing_summary_status" from response body and CSV file are same. Both are printed as 'null', but the postman fails to evaluate that expression to true.

Also it's attached as two screenshots
![postmanbug](https://user-images.githubusercontent.com/30220272/29349038-b1a7a580-82ab-11e7-8d7a-4441882ed031.PNG)
![postmanconsole](https://user-images.githubusercontent.com/30220272/29349039-b1b88c24-82ab-11e7-9551-3c6ab0359af8.png)

**Comment by prashantagarwal** [comment]
@dmladek Thanks for reporting this issue. We will investigate and update you about this issue.

**Comment by abhijitkane** [comment]
@dmladek `null` from your CSV file is treated as a string. `null` in a JSON response is treated as the JS null object. You'll need to add special handling for `"null"`.

**Comment by dmladek** [comment]
Thank you for the update. Will try that.
Cheers,
-d
