### ISSUE TITLE
Feature Request: API Documentation : Request with Params-List

### ISSUE THREAD

**Issue by Telaran** [a85/POSTMan-Chrome-Extension#3395]
Hello together, maybe it's a possible duplicate on [#3346](https://github.com/postmanlabs/postman-app-support/issues/3346) but I'd like to clarify my feature request.

### Story 
We have some requests (like search/filter) which can have several params and many of them are optional.
![paramsdocs_ex001](https://user-images.githubusercontent.com/2278266/29356291-11a26458-8274-11e7-9eaa-36041591e146.png)

### Requirement
In some cases it's good enough if some of our frontend developer would have access to the "API Documentation" and in that view a "good" params view is missing. 
Sure we could (thanks to the markdown feature) add all these in the description of the request but that would be double work and high risk of mistakes.

### Current
Currently everything about params are missing.
![paramsdocs_ex002](https://user-images.githubusercontent.com/2278266/29356445-9ddb59f2-8274-11e7-91e6-524e7d1a61fc.png)

### Possible approach
It should contain something like a Table or List (maybe collapsible).
![paramsdocs_ex003](https://user-images.githubusercontent.com/2278266/29360210-231c5ffa-8282-11e7-950b-6e35a10ddcdb.png) _(Not styled Table Example, not collapsible)_

**Comment by prashantagarwal** [comment]
@Telaran . Yes we will support query parameters in new version of documentation and it is going to be released very soon. Right now we don't support optional query parameters but you can very easily solve your use case by describing them as optional in description. But yeah they have to be enabled in your request.

**Comment by prashantagarwal** [comment]
@Telaran I am closing this as duplicate in favour of #3346

**Comment by Telaran** [comment]
@prashantagarwal 
Thanks for your feedback. Looking forward for the upcoming release

**Comment by tufangxu** [comment]
Hi, Can we change the query condition to "OR" instead of "&" among keys

**Comment by phcoliveira** [comment]
https://github.com/postmanlabs/postman-docs/issues/1470
