### ISSUE TITLE
Bug - Cannot reorder calls in collection v5.1.3

### ISSUE THREAD

**Issue by ataylor12** [a85/POSTMan-Chrome-Extension#3396]
## App Details:
```
Postman for Mac
Version 5.1.3 (5.1.3)
--------------------
macOS Sierra
Version 10.12.6
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:
Encountered only since update to 5.1.3
 2. Expected behaviour:
Should be able to reorder calls by dragging a call above/below other calls or into other folders in the side panel.
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
`
Requests not found in order_reorder    xml.js:22 
    RootLevelRequests @ xml.js:22
    reorderRequestInCollection @ xml.js:22
    handleDragDrop @ xml.js:22
    drop @ xml.js:22
    drop @ xml.js:22
    (anonymous function) @ xml.js:22
    drop @ xml.js:22
    (anonymous function) @ xml.js:22
    handleTopDrop @ xml.js:22
    wrapped @ xml.js:22
`
4. Screenshots (if applicable)
N/A

1. Open collection with multiple calls
2. Select call and drag above a different call
3. Calls will go back to original order

**Comment by SamvelRaja** [comment]
Thanks for bringing this to our notice, we are actively looking into this issue. We shall update the same thread asap.

**Comment by SamvelRaja** [comment]
@ataylor12 We pushed out *Canary app(5.2.0-canary02)* with fixes for reordering problem you are facing, can you help in testing the same from your end?

Just download and install the app according to your os.
*NOTE:*  Backup the data in current app using Settings -> Data -> Export  for additional security.

https://dl.pstmn.io/download/channel/canary/osx_64

**Comment by SamvelRaja** [comment]
Closing in favor of #3291
