### ISSUE TITLE
Not printing logs on the console

### ISSUE THREAD

**Issue by zagirhmm** [a85/POSTMan-Chrome-Extension#3397]
## App Details:

```
Postman for Mac
Version 4.11.0
OS X 16.4.0 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:
 2. Expected behaviour:
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 4. Screenshots (if applicable)

**Comment by kamalaknn** [comment]
Hey @zagirhmm 

We would need more information to help you out here. Please let us know when and how this happens.

Also, you are on an older version of the app. Please update your app to the latest version and check if you are still seeing this. If you are having troubles updating your app, try downloading the latest version from https://www.getpostman.com/apps

I'm closing this for now. Please reopen this issue if it still exists in the latest version of the app.

**Comment by zagirhmm** [comment]
Hi - am able to see the logs now, thanks 

Zagir

**Comment by kamalaknn** [comment]
Great!
