### ISSUE TITLE
Need to press Ctrl+Z many times to undo changes in the url box

### ISSUE THREAD

**Issue by mlambley** [a85/POSTMan-Chrome-Extension#3398]
## App Details:
```
Postman for Chrome
Version 5.1.3
win / x86-64
Chrome 60.0.3112.90
```

## Issue Report:
When I change text in the URL box, and then press Ctrl+Z to undo the changes, it takes 2-3 presses before the undo operation happens.

For example:
![postman url](https://user-images.githubusercontent.com/17264636/29396817-b4a94010-835d-11e7-8dc4-690612606e8a.png)

If I were to change "46" to "46393" and then Ctrl+Z to undo the changes back to "46", I need to press Ctrl+Z 8 times for this to happen.

**Comment by prashantagarwal** [comment]
@mlambley Thanks for reporting this we are already tracking this issue #3315 . I am closing this as duplicate issue.
