### ISSUE TITLE
Feature Request: Support Request Body for GET Requests

### ISSUE THREAD

**Issue by andreassiegel** [a85/POSTMan-Chrome-Extension#3399]
I know that GET requests usually don't have (and probably shouldn't have) a request body.

However, the [RFC 2616 Hypertext Transfer Protocol -- HTTP/1.1](https://tools.ietf.org/html/rfc2616) doesn't explicitly state that GET requests must not have a body, but section [9.3 GET](https://tools.ietf.org/html/rfc2616#section-9.3) only refers to the request URI or message headers.

Roy T. Fielding clarified this in a [REST Architecture discussion group](https://groups.yahoo.com/neo/groups/rest-discuss/conversations/messages/9962):

> In other words, any HTTP request message is allowed to contain
a message body, and thus must parse messages with that in mind.
Server semantics for GET, however, are restricted such that a body,
if any, has no semantic meaning to the request. The requirements
on parsing are separate from the requirements on method semantics.
>
> So, yes, you can send a body with GET, and no, it is never useful
to do so.

[Elasticsearch](https://www.elastic.co/guide/en/elasticsearch/reference/current/index.html)'s REST API is an example of a certainly well-known API that breaks with the principle, e.g. the [Multi Get Document API](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-multi-get.html) requires a GET request with a request body:
```
GET _mget
{
    "docs" : [
        {
            "_index" : "test",
            "_type" : "type",
            "_id" : "1"
        },
        {
            "_index" : "test",
            "_type" : "type",
            "_id" : "2"
        }
    ]
}
```

It would really be nice if this API could also be used with Postman, because, personally, I consider, e.g., `curl` a bit cumbersome in some cases.

An option to still indicate that GET requests usually should not have a body is displaying a warning, for instance.

Also see the [corresponding thread in the Postman Slack](https://postmancommunity.slack.com/archives/C0WBDGZ4P/p1502953347000045) community.

**Comment by prashantagarwal** [comment]
@andreassiegel We are already tracking this issue here #2729. I am closing this as duplicate

**Comment by andreassiegel** [comment]
@prashantagarwal Thank you! Sorry for missing the existing feature request.
