### ISSUE TITLE
nginx proxy_pass `Unable to authenticate using access token` error

### ISSUE THREAD

**Issue by candyan** [a85/POSTMan-Chrome-Extension#3400]
## App Details:

```
Postman for Mac
Version 4.11.0
OS X 16.4.0 / x64
```
proxy_pass to mock api server and proxy_set_header x-api-key

and then return 

```
{
    error: {
        name: "invalidCredentialsError",
        message: "Unable to authenticate using access token."
    }
}
```

**Comment by kamalaknn** [comment]
Hey @candyan 

Could you share more details about what you are seeing?

Is this something that is not working on the Postman app or the Mock APIs? Also, could you clarify what you mean by mock APIs, are you referring to Postman Mocks or your own mocks?
