### ISSUE TITLE
[Bug] - Deleted environments that were shared are still shown under the Manage Environments > Environment Templates window

### ISSUE THREAD

**Issue by Faz540** [a85/POSTMan-Chrome-Extension#3401]
**Postman Windows App using Windows 10 x64.**

**Steps To Reproduce:**
Create and Share an environment with your team
Wait for sync
Click the 'Team Library' link at the top of the page
Click 'Environment Templates' tab.
Delete shared Environment from the Team Library
Wait for sync
Open the 'Manage Environments' window
Delete environment that was previously shared from the 'Manage Environments' window
Wait for sync
Open the 'Manage Environments' window
Notice that the deleted environment (that was previously shared) is still shown.

**See Below Screenshot:**
I unshared and deleted all the 'LEGACY' environments before and they're still being shown under the Manage Environments > Environment Templates window.

![image](https://user-images.githubusercontent.com/9334128/29407246-b2087410-833b-11e7-8839-0435634ed4b4.png)

I've confirmed that these environments are no longer returned using the Postman Pro endpoint, which is what I expected:
https://api.getpostman.com/environments

**Comment by Faz540** [comment]
I managed to get around this issue by using the postman pro api endpoint DELETE /environments/{{environment_uid}}

It seems we can also edit shared environments by using the PUT /environments/{{environment_uid}}
I know this is feature that a lot of Postman Users want expressed in the UI, it was only by chance that I found this endpoint and realised this was possible (before hand I was deleting the old shared environment, make the desired changes to the environment and then re-share the environment)

**Comment by SamvelRaja** [comment]
This issue should have been solved by our 6.x update. Kindly update to our latest 6.1.4 app.
