### ISSUE TITLE
New version of postman forces response download instead of displaying result inline

### ISSUE THREAD

**Issue by ArunKSY** [a85/POSTMan-Chrome-Extension#3402]
Image is not showing inline in updated postman version.It is asking to download the file.

![barcode_image_capture_sdf](https://user-images.githubusercontent.com/31095804/29407373-d46852ca-8361-11e7-853f-108ab90c5be9.PNG)

**Comment by kamalaknn** [comment]
Hey @ArunKSY 

Inline images seem to be working fine (try requesting `http.cat/200`). Could you share more details on where you are seeing this?

Could you share more details on the version of the App you are seeing this and if you are on the Chrome app or the Native app. A screenshot of `Settings -> About` would help.
