### ISSUE TITLE
Import of variable values does not work

### ISSUE THREAD

**Issue by TheCodeDestroyer** [a85/POSTMan-Chrome-Extension#3403]
## App Details:
```
Postman for Chrome
Version 5.1.3
OS X / x86-64
Chrome 60.0.3112.90
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there: Not sure, beacause I havent played with variables before
 2. Expected behaviour: If variable has value X the imported value in params table should be X as well not empty string
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 4. Screenshots (if applicable)

[HERE](http://imgur.com/p0trKJ8)

Import [this](https://gist.github.com/TheCodeDestroyer/80c74650ca6f2a82c9fad14b34bdfdb2) json and check Params value `what` should have value `posts`, but it has an empty string

**Comment by kamalaknn** [comment]
@TheCodeDestroyer Thank you for sending in your feedback. 

We have fixed this internally and will roll it out as part of the next release. We will update this thread once the fix goes to production.

Also, we are deprecating the `:variable` syntax in favor of environment `{{variable}}` syntax. We will get this fixed, but moving out of `:variable` usages will help you for long term.

Chears!

**Comment by TheCodeDestroyer** [comment]
Could you provide an example of how will a request look like with env variable syntax?

**Comment by kamalaknn** [comment]
Hey @TheCodeDestroyer here's a more extensive documentation on using variables with requests in Postman - https://www.getpostman.com/docs/postman/environments_and_globals/variables.

Have a nice day!

**Comment by TheCodeDestroyer** [comment]
@kamalaknn So if I understand this correctly local variables will be replaced by env variables?
If that is the case then if I have 200 request saved with env variables instead of local ones then my env setups needs to have a huge collection of variables, or did I not understand this correctly?

**Comment by kamalaknn** [comment]
@TheCodeDestroyer do you have individual variables for each request in the collection? Could you share how you are using variables in requests? We are working on introducing variables at collection/folder level. We'll keep this in mind.

**Comment by TheCodeDestroyer** [comment]
@kamalaknn Sadly I can't legally show you the examples I'm working with,
but just imagine you are working on a huge project with 100+ entities in db and all of those are exposed through the API.
Examples:

* `/api/v2/entity1/:entity1Id/[sub entity]/[sub entity id]?someQueryStringWithVariables'
* `/api/v2/entity2/:entity2Id/[sub entity]/[sub entity id]?someQueryStringWithVariables'
* `/api/v2/entity3/:entity3Id/[sub entity]/[sub entity id]?someQueryStringWithVariables'
* `/api/v2/entity4/:entity4Id/[sub entity]/[sub entity id]?someQueryStringWithVariables'
* etc.

Having from `entity1Id` to `entity100Id` all stored in env variables seems a bit of an overkill.
Personally I don't care if you leave `:entity1Id` or if you change to `{{entity1Id}}` as long as the behavior is the same as with query string variables as in being defined locally for each request and available in `Params` section.

**Comment by sdnts** [comment]
@TheCodeDestroyer Can you try updating to 5.2 and check if you still see this issue?

**Comment by TheCodeDestroyer** [comment]
@madebysid It works now, thank you!
