### ISSUE TITLE
Request - Improved GUI

### ISSUE THREAD

**Issue by JebediahSpringfield** [a85/POSTMan-Chrome-Extension#3404]
Hi guys,

   You have an interesting tool but one thing that bothers me is the lack of very basic functionality in the Collections GUI.

   Would it be possible to make the copy and paste of requests between collections straightforward?

   For example, I created a collection to verify 40 cases and later found out that there was already another collection related to the same tests. In order to add my 40 cases to the existing collection, I have to go through the painful process of moving the requests One By One. 

   I don't know the history of this app, but It really surprises me that such functionality is absent from the tool. Being able to do multiple selections (with ctrl, shift), copy, move and the likes is something developers take for granted ever since what? Windows 95?

Thank you.

**Comment by kamalaknn** [comment]
@JebediahSpringfield 

Thanks for sending in your feedback. This has been a pain point for long. This is on our roadmap, but we can't arrive at a deadline for release yet.

We are tracking this in #803. Please follow the main thread for updates.

**Comment by JebediahSpringfield** [comment]
That's good to hear. Thank you for the feedback Kamalakannan.
Cheers

      De : Kamalakannan <notifications@github.com>
 À : postmanlabs/postman-app-support <postman-app-support@noreply.github.com> 
Cc : JebediahSpringfield <andre2999@yahoo.com>; Mention <mention@noreply.github.com>
 Envoyé le : Jeudi 17 août 2017 12h12
 Objet : Re: [postmanlabs/postman-app-support] Request - Improved GUI (#3404)
   
@JebediahSpringfieldThanks for sending in your feedback. This has been a pain point for long. This is on our roadmap, but we can't arrive at a deadline for release yet.We are tracking this in #803. Please follow the main thread for updates.—
