### ISSUE TITLE
Postman 5.1.3 keeps crashing on Ubuntu 17 when using Environments

### ISSUE THREAD

**Issue by alexeyOnGitHub** [a85/POSTMan-Chrome-Extension#3405]
## App Details:
```
Postman for Chrome
Version 5.1.3
linux / x86-64
Chrome 54.0.2840.59
```

 1. Did you encounter this recently, or has this bug always been there:

this started happening very often once I started using "environments" (awesome feature, btw! just discovered it and it is super helpful - no more need in keeping tons of mostly-duplicate requests)

when it crashes, "chrome://inspect/#apps" page becomes empty, "postman" disappears from there. no logs.
not sure how provide more useful info...

this is a pretty consistent issue. happens randomly (once for every ~3 actions I take)   with various actions - sometimes when I click "Send" for a request or even with I click "delete request".   

this never happened until I started using "environments"

when this happens on "Delete request from Postman" action, I can see (After manual Postman restart) that the request was in fact deleted. but it lead Postman to crash.

**Comment by alexeyOnGitHub** [comment]
![image](https://user-images.githubusercontent.com/239741/29429608-25f20cc4-8346-11e7-8631-429943c0d09d.png)

**Comment by alexeyOnGitHub** [comment]
side note - clicking on this "balloon" does not restart it

**Comment by kamalaknn** [comment]
Hey @alexeyOnGitHub 

This could be because of memory issues related Chrome apps. Could you try out out native apps, you can download them from https://www.getpostman.com/apps.

Please let us know if you are still seeing them on the native apps.

**Comment by alexeyOnGitHub** [comment]
thank you, I will export all collections and environments and try them with Ubuntu native app on Monday. (side note - would be nice to be able to export all collections and envs at once).

**Comment by alexeyOnGitHub** [comment]
no problems with native Postman app on Ubuntu 17 64bit.

**Comment by jahrichie** [comment]
Ubuntu 16.04.2 LTS native app crashes on every request.  Tried clearing history completely still crashes.  Any advice?

**Comment by wojcikcp** [comment]
@jahrichie Same situation. I think my 500's are so bad that they crashes postman :dancer:

**Comment by rajanverma-me** [comment]
ubuntu 16.04 LTS. native app keeps crashing. not even opening

**Comment by amritms** [comment]
ubuntu 16.04 LTS. native app crashes system, need to restart everytime I hit wrong endpoint.

**Comment by brandon-clair** [comment]
I'm also experiencing these crashes on the native Postman 5.1.3. I'm running it on Linux Mint 18.2 Cinnamon 64-bit:
```
$ uname -a
4.11.0-14-generic #20~16.04.1-Ubuntu SMP Wed Aug 9 09:06:22 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```
The trigger for the crash has been inconsistent.

**Comment by artischocke** [comment]
I'm experiencing this issue as well, even without using Environments as the title suggests (Ubuntu 16.10)

```
Postman for Chrome
Version 5.4.0
linux / x86-64
Chrome 59.0.3071.109
```

The number of "tabs" open does seem to influence how quickly the app crashes.

**Comment by TaylanT** [comment]
same here

**Comment by jumpingstone** [comment]
same here, crash every time on ubuntu LTS 16.04

**Comment by vayu-technology** [comment]
Still crashing here too; Ubuntu LTS 16.05 latest build.  Unusable.

**Comment by ragsnas** [comment]
Same here with native app on Ubuntu 16.04.4 LTS
Crashes randomly and not only on requests.

**Comment by kamalaknn** [comment]
Can you try updating to the latest *Native App* for Postman and verify this?

**Comment by hernanlaborde** [comment]
I experiment the crash in ubuntu 17. I use the nativefile from  https://www.getpostman.com/apps

**Comment by ragsnas** [comment]
@kamalaknn I thought i had the native app (does not run in chrome but stand alone). But now i have the native app and it does work fine. Thanks!

**Comment by MarcoCaballero** [comment]
Hiya! as @artischocke said:

> The amount of open "tabs" seems to influence how quickly the application fails.

I can add to this, the number of **'unsaved' tabs increases the probability**

Could be high memory usage issue?

Tested on VirtualBox: 

```
$ uname -a 
Linux osboxes 4.13.0-37-generic #42~16.04.1-Ubuntu SMP Wed Mar 7 16:03:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

```
Postman for Chrome
Version 5.5.2
linux / x86-64
Chrome 64.0.3282.186
```

Cheers!

**Comment by brandon-clair** [comment]
I'm using the Postman for Linux x64 Native App, now. The problem doesn't exist there.

**Comment by hmachefe** [comment]
Oh yes it does. Ubuntu needs to be rebooted, and Postman to be restarted again (from scratch)

**Comment by anasalsalah** [comment]
I've tried both the native app and the Chrome app on Linux Ubutnu 16.04 (64-bit). Just 1-3 clicks anywhere and then it crashes. This started happening after adding just a few API requests.

**Comment by gfernandez-me** [comment]
ubuntu 18. native app crashes system, need to restart everytime I hit wrong endpoint.
