### ISSUE TITLE
Feature Request: Search and Replace URLs in API Requests

### ISSUE THREAD

**Issue by idevtech** [a85/POSTMan-Chrome-Extension#3406]
Postman for Windows
Version 5.1.3
win32 10.0.15063 / x64

When a collection is duplicated it would be useful to be able to search and replace the URLs for the API requests. For example, I have ~50 requests in a collection and when it is duplicated manually replacing the domain portion of each URL is time consuming.

**Comment by bhawna2109** [comment]
Thanks for explaining your use case @idevtech. This is actually on our roadmap :) Stay tuned for updates on this!

**Comment by a85** [comment]
Closing as a duplicate of https://github.com/postmanlabs/postman-app-support/issues/1429
