### ISSUE TITLE
auto unset content-type while changing body type

### ISSUE THREAD

**Issue by attmore** [a85/POSTMan-Chrome-Extension#3408]
when change post body type from  'x-www-form-urlencoded' to ‘form-data’ ,headers is still set content-type = application/x-www-form-urlencoded

![image](https://user-images.githubusercontent.com/1621318/29442013-c0a6e5f8-8401-11e7-92ee-fc9d602c32df.png)
then
![image](https://user-images.githubusercontent.com/1621318/29442037-d5bfcedc-8401-11e7-8138-6242b84d80f1.png)
header is still application/x-www-form-urlencoded 
![image](https://user-images.githubusercontent.com/1621318/29442037-d5bfcedc-8401-11e7-8138-6242b84d80f1.png)

**Comment by kamalaknn** [comment]
Hey @attmore 

Thanks for your feedback. I am tagging this as a feature request.

@numaanashraf what do you think about this?

**Comment by a85** [comment]
This works as expected now.
