### ISSUE TITLE
copy past issue of body date between 'form-data' and 'x-www-form-urlencoded'

### ISSUE THREAD

**Issue by nongfumemequan** [a85/POSTMan-Chrome-Extension#3409]
## App Details:

```
Postman for Windows
Version 5.1.3
win32 10.0.14393 / x64
```

## Issue Report:
 copy body date form 'form-data' to 'x-www-form-urlencoded', it show success but actually it did not
open request code and find the body data is empty(see attach)
![form-data](https://user-images.githubusercontent.com/16768592/29442931-4979d11a-8407-11e7-95b1-3161d3420ccd.png)
![x-www-urlencoded](https://user-images.githubusercontent.com/16768592/29442939-51ddfade-8407-11e7-894c-dbc227f05140.png)
![request code](https://user-images.githubusercontent.com/16768592/29442945-5ad1e498-8407-11e7-811c-dd4f720488d9.png)

**Comment by kamalaknn** [comment]
@nongfumemequan Thanks for reporting this. We are able to reproduce this. We are looking into this.

**Comment by prashantagarwal** [comment]
@nongfumemequan we are already tracking this #3162. I am closing this as duplicate.
