### ISSUE TITLE
Node api working in browser but preflight failed in postman

### ISSUE THREAD

**Issue by avinash0** [a85/POSTMan-Chrome-Extension#3410]
When calling API https://mywebsite.com/api/register through browser and it returns correct response from server as `{ "error": false, "message": "Hello World" }`
If we hit the same request from postman then it returns with some html content as <noscript>Please enable JavaScript to view the page content.</noscript>
Below is node side code:

    var express = require("express");

    var app = express();

    var bodyParser = require("body-parser");

    var router = express.Router();

    var fs = require('fs');
    var https = require('https');
    
    var cors = require('cors');
    
    app.use(cors());
    
    app.use(bodyParser.json({limit: '50mb'}));
    
    app.use(bodyParser.urlencoded({ limit: '50mb', "extended": false }));
    
    var privateKey  = fs.readFileSync('key.pem');
    var certificate = fs.readFileSync('cert.pem');
    var passphrase = 'testphrase';
    var credentials = {key: privateKey, cert: certificate, passphrase:passphrase};
    
    router.get("/", function (req, res) {
    
        res.json({ "error": false, "message": "Hello World" });
    
    });
    app.use('/api', router);
    var server = https.createServer(credentials, app).listen(8080);

The api working through the browser but not with postman. What will be the possible errors? 
Please help. Thanks!

**Comment by kamalaknn** [comment]
Hey @avinash0 

Could you share a screenshot of the response you see? Also, any logs on `Postman Console` `View -> Show Postman Console` (only available on native apps) would help.

**Comment by avinash0** [comment]
![postman response](https://user-images.githubusercontent.com/6986217/29457510-19f6810a-8438-11e7-9059-420fc255de7a.png)

this is response and no logs found

**Comment by kamalaknn** [comment]
@avinash0 from you node code, I could see you are adding certificates to the server. Does your endpoint require a client side certificate?

**Comment by avinash0** [comment]
@kamalaknn Client side certificate not required. Only SSL certificate at server side.

**Comment by avinash0** [comment]
Any idea why this error coming through postman

**Comment by numaanashraf** [comment]
@avinash0 Could you verify the implementation of your `api/register` route?. Seems like it's a HTML endpoint that needs a browser to render the page and then redirect via JavaScript, which would explain why it works in the browser. Postman doesn't do JavaScript execution inside your HTML response.
