### ISSUE TITLE
Google OAuth2 returns 404

### ISSUE THREAD

**Issue by rossjha** [a85/POSTMan-Chrome-Extension#3411]
## App Details:
```
Postman for Mac
Version 5.1.3 (5.1.3)
macOS 10.12.6 (16G29)
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:

  I haven't successfully used Authorization > OAuth2
 
2. Expected behaviour:

  Receive Google access token, but returns HTML (404) instead.

**Details**
```
Auth URL: https://accounts.google.com/o/oauth2/auth
Access Token URL: https://accounts.google.com/o/oauth2/v4/token
Client ID: {set}
Client Secret: {set}
Scope: email
Grant Type: Authorization Code
```

The *Authorized redirect URIs* in console.developers.google.com is set to: 

```
https://www.getpostman.com/oauth2/callback
```

**Response**
```
en%3E%3Cmeta%20charset=utf-8%3E%3Cmeta%20name=viewport%20content=%22initial-scale=1,%20minimum-scale=1,%20width=device-width%22%3E%3Ctitle%3EError%20404%20(Not%20Found)!!1%3C/title%3E%3Cstyle%3E*{margin:0;padding:0}html,code{font:15px/22px%20arial,sans-serif}html{background:
```

Any help would be appreciated.

**Comment by sdnts** [comment]
Hi @rossjha, can you check if the Access token URL is correct? Looks like Google sends back a 404 when it is hit, which is why you get this.
Closing as this doesn't look related to Postman. Please reopen if I misunderstood.

**Comment by rossjha** [comment]
Thanks yeah was trying different URL's.  Looks like i have the same issue as #2811

**Comment by uprg** [comment]
I am having the same problem but in my python script . postman runs nicely
