### ISSUE TITLE
Request: Option to generate cURL without line breaks

### ISSUE THREAD

**Issue by who** [a85/POSTMan-Chrome-Extension#3412]
## App Details:
```
Postman for Mac
Version 5.1.3
OS X 16.6.0 / x64
```
## Issue Report:
In older versions of Postman, when generating a cURL command from a request, a one-line cURL would be generated. I really miss this, as one-liner cURL commands are preferred in my workflow.

## Feature request:
Please add a new generator entitled "cURL (one liner)" or "cURL (no newlines)". This new generator would not use \ newline statements. The existing cURL generator that that does use newline statements should remain so.

**Comment by sdnts** [comment]
@who I understand how this might be useful. Adding this as a feature request.
In the mean time, the multiline cURL should work too :)

**Comment by shreys7** [comment]
Hey @who Can you try this is Postman 7.2.1, with the 'Experimental Codegen Mode' flag enabled in Postman's global settings? We've introduced bug-fixes, support for two new languages (JS-Fetch and Powershell), and the ability to configure certain aspects of the generated snippet.

For this particular use-case, there's a separate curl-level 'MultiLine Curl Request' setting, which you can control once you've selected cURL in the language selector. Turning it off would generate the single line cURL command, solving your use case :)
