### ISSUE TITLE
Bad POST keys when using form-data Body with Postman Chrome app

### ISSUE THREAD

**Issue by jrounsav** [a85/POSTMan-Chrome-Extension#3413]
I'm developing an API and using Postman to test my POST endpoints and have started receiving errors.
My reporting shows that Postman is sending the following API key in the body:

```------WebKitFormBoundaryIrfhUo5Iwf8Wix3n\r\nContent-Disposition:_form-data;_name,```

This when happens my POST Body is set to form-data but I can mitigate it by using x-www-form-urlencoded.

## App Details:
```
Postman for Chrome
Version 5.1.3
OS X / x86-64
Chrome 60.0.3112.90
```

## Issue Report:
 1. First time seeing this
 2. The app should only send the defined key/val pairs through

**Comment by jrounsav** [comment]
Console Logs

```window.localStorage is not available in packaged apps. Use chrome.storage.local instead.
requester.html:1 beforeunload is not available in packaged apps.
requester.html:1 window.localStorage is not available in packaged apps. Use chrome.storage.local instead.
tester_sandbox.html:1 unload is not available in packaged apps.
2tester_sandbox.html:1 window.localStorage is not available in packaged apps. Use chrome.storage.local instead.
sails.io.js:142 🌏 sync service connectivity initiated
sails.io.js:759 socket replaying queued commands
sails.io.js:142 🌏 connected to sync service.```

**Comment by kamalaknn** [comment]
@jrounsav Could you try out our Native apps and see if it still happens? You can download our native apps at https://www.getpostman.com/apps.
