### ISSUE TITLE
Postman is duplicating requests in collection after it is shared in Team Library

### ISSUE THREAD

**Issue by correajd** [a85/POSTMan-Chrome-Extension#3415]
## App Details:

```
Postman for Mac
Version 5.1.3 (5.1.3)
macOS Sierra Version 10.12.6 (16G29)
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:
    Postman Pro has recently started acting irregularly. When I posted collection, it created a copy of the last request. 
 2. Expected behaviour:
    The expected behaviour is that it maintains the state of what it was when I click the "Share" button.
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 4. Screenshots (if applicable)

**Comment by sdnts** [comment]
Hi @correajd This should not be happening. The app should maintain the state of the collection when sharing.
I wasn't able to reproduce this though. Is this happening only for a single collection or all collections you create? Does signing out, then signing in help?

**Comment by andrew-jones** [comment]
I just had this problem too, spent 30mins cleaning up duplicates in a public postman doc.  Version 6.2.5 of Postman.
