### ISSUE TITLE
All Requests time out

### ISSUE THREAD

**Issue by cpttripzz** [a85/POSTMan-Chrome-Extension#3416]
## App Details:
Postman for Linux
Version 5.1.2 and 5.1.3
linux 4.10.0-30-generic / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there: Recent
 2. Expected: Requests succeed.
 3. Result: requests time out.

- Tried logging in, get blank tab
- All requests end with error connecting.
- Tried signing out and re-adding data after exporting collections
- tried deleting ~/.config/Postman and doing a simple get to localhost with no env vars...
- tried downgrading / upgrading versions.
- even http://foaas.com/off/Tom/Everyone?shoutcloud fails
- workaround: chrome extension still works after I sign in, but the native app is completely broken

- i want a refund!    :P

**Comment by sdnts** [comment]
Hi @cpttripzz Do you have an app level timeout set by any chance? You can check this by heading over to Settings(Ctrl+,) > General tab. There's a field there for Request timeout. Setting it to zero should solve this issue. Please reopen if it doesn't!

**Comment by cpttripzz** [comment]
No timeout was set. Still broken.

**Comment by sdnts** [comment]
This is very weird. Are you using any sort of proxies in your environment?

**Comment by abhijitkane** [comment]
@cpttripzz Can you check https://www.getpostman.com/docs/postman/sending_api_requests/debugging_and_logs for the actual request/response?
In case your server needs client-side certs, these can be set at https://www.getpostman.com/docs/postman/sending_api_requests/certificates.

Feel free to re-open if you still see this with all other endpoints too.
