### ISSUE TITLE
Postman Crashing Annoying issue

### ISSUE THREAD

**Issue by zohaib055** [a85/POSTMan-Chrome-Extension#3419]
Postman is crashing  whenever i click from history not sure why but this is so much annoying please fix these issues

Version 5.1.3
linux / x86-64
Chrome 58.0.3029.110

**Comment by sdnts** [comment]
@zohaib055 Is this happening for any request from the history sidebar or only a specific item?
Can you also try this on our native apps and see if the problem persists? You can download native apps [here](https://getpostman.com/apps)
