### ISSUE TITLE
Collect runner feature request : Create file (csv/json/excel/etc.) based on response

### ISSUE THREAD

**Issue by francoisneron** [a85/POSTMan-Chrome-Extension#3421]
I want to be able to generate a file from my collection runner in a appropriate format.

For example, I want to use send thousands of requests to an endpoint and be able to log any failed requests in a file in my own format (using the response, or error codes provided by the 3rd party).

**Comment by sdnts** [comment]
@francoisneron Have you taken a look at Newman [reporters](https://github.com/postmanlabs/newman#configuring-reporters)?

**Comment by francoisneron** [comment]
Thanks for the quick reply, @madebysid .

I'm looking for something like this. Is that achievable with Reporters?

This is like the existing "get from file".
`postman.setEnvironmentVariable("ENVIRONMENT_VARIABLE_X", data.fieldheader);`

I want more like a "push to file". (take in consideration x iteration, new variable to be set, pick up the file and add a new header to the CSV/JSON). That can be done on Pre-Request script or Tests tab.
`postman.addData("ENVIRONMENT_VARIABLE_X", newfieldheader );`
`postman.addData("value to push", "header to add or if already existing");`

**Comment by sdnts** [comment]
@francoisneron Sure. The reporter Docs should help here. We do not allow users to write to files form pre-request / test scripts because of security reasons, unfortunately.
You can join our [Slack community](https://www.getpostman.com/slack-invite) to ask any questions you have :)
