### ISSUE TITLE
Sync Issue in request body for a member with read-only permission to a collection.

### ISSUE THREAD

**Issue by vaibhav-plackal** [a85/POSTMan-Chrome-Extension#3422]
## App Details:

```
Postman for Mac
Version 5.1.3 (5.1.3)
```

## Issue Report:

Request body data is not synced for new team member with read-only access.

#### Steps to reproduce the issue
1. A new team member was added and I allowed her 'read-access'. However, some of the APIs that got synced were missing the request body.
2. When I changed the data (body part) on my end and synced back, the requests on their installation got updated and the data appeared. 

**NOTE**: Team members have the same version of Postman on the same OS (version 5.1.3 / macOS Sierra)

**Comment by sdnts** [comment]
@vaibhav-plackal We're working on many improvements to Sync flows, and they should be out with the next release. Can you let us know if these issues persist after 5.2 hits production?

**Comment by vaibhav-plackal** [comment]
Sure. I can. When is 5.2 coming out?

**Comment by sdnts** [comment]
@vaibhav-plackal We're aiming for some time this week.
