### ISSUE TITLE
Postman crashes when clicking send if too many requests are open

### ISSUE THREAD

**Issue by smacktoid** [a85/POSTMan-Chrome-Extension#3424]
## App Details:
```
Postman for Chrome
Version 5.1.3
linux / x86-64
Chrome 49.0.2623.87
```

## Issue Report:
 This bug seems to have been present for at least a year, and it has never stopped occurring for me.

**Expected behaviour:**
I should be able to open new tabs without the app crashing. It's even acceptable for the app to enforce a maximum limit, but it should never crash.

**Steps to reproduce:**
Once I get to around 20 open tabs, clicking Send on a request tab crashes the entire Postman app.

This happens constantly for me, on two separate machines (one Windows, one Linux). Our API uses a lot of hypermedia controls, so we are often selecting links from within response bodies to open new tabs as we navigate the API. 

This means that we end up with lots of tabs being open, which leads to this bug occurring.

**Comment by sdnts** [comment]
@scottmmmm 20 tabs shouldn't be doing this. we'll take a look at this.

**Comment by smacktoid** [comment]
I've attached a video showing this occurring. Note how I open several requests by following links, and then the video shows the mouse stuttering across the screen after I click "Send" the last time. At this point Postman has crashed (the video looks funny because the screen recorder was configured to record Postman, so it didn't handle the crash very well)

[postman-bugs.mp4.zip](https://github.com/postmanlabs/postman-app-support/files/1251297/postman-bugs.mp4.zip)

**Comment by prashantagarwal** [comment]
@scottmmmm Can you try this on our native Postman app

**Comment by smacktoid** [comment]
I can't see the issue when navigating through my API using the native client. Good job!

**Comment by prashantagarwal** [comment]
Awesome. I am closing this issue for now but please let us know if you face this issue again
