### ISSUE TITLE
Inconsistent behaviour when clicking links within response body

### ISSUE THREAD

**Issue by smacktoid** [a85/POSTMan-Chrome-Extension#3425]
## App Details:
```
Postman for Chrome
Version 5.1.3
linux / x86-64
Chrome 49.0.2623.87
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:

Issue seems to have started occurring recently.

 2. Expected behaviour:

Clicking on a link in a response body should behave consistently. In the past it always resulted in a new open tab. Now it seems to sometimes open a new tab, or sometimes replace the URL on the current tab.

**Comment by sdnts** [comment]
@scottmmmm I tried replicating this, but the link always opens in a new tab for me, which leads me to believe I might be doing something wrong. Can you provide steps I can follow?

**Comment by smacktoid** [comment]
After testing a bit more it looks like the new tab is always opened, but it is inconsistently setting the focus. Sometimes the current tab remains open, and sometimes focus switches to the other, new tab.

In terms of further steps to reproduce, I'll try my best.

The response I'm looking at is as follows:
```
{
    "@context": "http://localhost:8580/case-service/context.jsonld",
    "@id": "http://localhost:8580/case-service/verint/case-definitions/Case_SingleStageCasewithOnEntryTask",
    "@type": [
        "vce:CaseDefinition"
    ],
    "vce:caseDefinitionId": "Case_SingleStageCasewithOnEntryTask",
    "vce:createCase": "http://localhost:8580/case-service/verint/cases?caseDefinitionId=Case_SingleStageCasewithOnEntryTask",
    "vce:name": "SingleStageCasewithOnEntryTask"
}
```

The response headers are :
```
Content-Length →423
Content-Type →application/ld+json;charset=UTF-8
Date →Tue, 22 Aug 2017 12:12:07 GMT
ETag →"0ffe5fe80f86f44adcd3625488568c030"
Server →Apache-Coyote/1.1
X-Application-Context →case-service
```

To reproduce the problem I am clicking on the vce:createCase property within the response body. This opens that URL in a new tab, but whether the new tab is opened or not appears to be random.

**Comment by smacktoid** [comment]
I've attached a video of this happening. 

At the 15 second mark in the video, I click a link in the response body. At that point another tab opens, but focus stays on the current window. You can see that I have to switch to the other window manually.

Throughout the rest of the recording I'm able to click on links and automatically switch to other tabs, highlighting the inconsistent nature of this bug.

[postman-bugs.mp4.zip](https://github.com/postmanlabs/postman-app-support/files/1251308/postman-bugs.mp4.zip)

**Comment by sdnts** [comment]
@scottmmmm I can indeed see the problem, and I probably cannot reproduce it because it is not consistently happening. I'll look into this. Thanks for reporting!

**Comment by culli** [comment]
One way to work around this would be to add a preference to make urls not be clickable in results.  Also it might be nice to make them open in the default system browser instead of in postman.  https://github.com/postmanlabs/postman-app-support/issues/2030

**Comment by smacktoid** [comment]
Whilst that would be one way to resolve the issue it's not the ideal solution when you're developing an API with hypermedia links in the body.

Developers of such APIs (like me!) would prefer the links to be clickable within Postman, so that they can design a nice, easily navigable URL structure. The current behaviour (opening a new tab) is fine, as long as the application behaves consistently once the tab is open.

**Comment by smacktoid** [comment]
Why was this closed, has it been fixed?

**Comment by prashantagarwal** [comment]
@scottmmmm This seems to be fixed in our Postman native apps.

**Comment by smacktoid** [comment]
Excellent!
