### ISSUE TITLE
Postman inconsistent behaviour with cURL request

### ISSUE THREAD

**Issue by krogold** [a85/POSTMan-Chrome-Extension#3429]
## App Details:
Postman for Windows
Version 5.1.3
win32 10.0.15063 / x64

## Issue Report:
1. Seen today, repeated on each try

2. Expected to be rejected as "not authentified" error 401

3. irrelevant

4. irrelevant

Description:
I have the following API downloaded in JSON from Swagger Editor:
PUT http://10.37.64.243/m2m/fim/items/fim:device:manager/operations/getAllDeviceTypes?exclude={{exclude}}
with exclude being an environment variable set as : href,metadata,name,arguments

Nominal use requires basic authentication, in this case it works and I get a JSON body with expected result.

If no authentication is provided: 
- in Swagger Editor : nominal behaviour, request is rejected with error code 401
- in Postman : WRONG behaviour, I end up with status code 200 and a response body identical to the one that I get when authenticated
- If I generate the cURL code snippet from Postman and launch it out of Postman: nominal behaviour, I get the same error as the one I get in Swagger Editor (the one expected)

Why do Postman behave differently from the cURL request ??
I probably do something wrong, but I can't figure out what

Thanks for any help

Alexandre

**Comment by krogold** [comment]
Actually, if I sign out then sign in it works as expected, but dynamically it doesn't.
If I activate basic authentication, then deactivate it setting 'No Auth' and removing the corresponding header, the problem appears again.
How can we reset the context without signing out/signing in ?

thank you

Alexandre

**Comment by sdnts** [comment]
Hi @krogold, when you remove the Basic Auth, do you still see the autorization header with the request? When you remove the auth helper, but your authorization header is already generated, Postman will not automatically remove the header. This might explain why you get a 200 without any authentication.

**Comment by krogold** [comment]
Thank you for replying
That's what I do, I noticed that and then I remove the authentication header but it seems to be still activated somehow.
Is there a way to delete a header programmatically (so I could do it in a pre-request script) ?

**Comment by krogold** [comment]
I tried the Postman Echo collection in order to see how it behaves and it works properly, whatever the order of the tests. Maybe it is linked to the fact that it concerns GET requests as mine is a PUT request ?

**Comment by sdnts** [comment]
The request method shouldn't matter, as the Authorization logic is independent. If you do not see the header in the UI, then the header shouldn't be present. Can you check your server logs to see if your server still receives the header? If your server uses cookies, do you think they might be interfering?

**Comment by krogold** [comment]
Indeed I have a cookie in my response ... 
It appears in the cookies part. I'll try to delete it

**Comment by krogold** [comment]
That's it ! 
There are features about cookies, will they allow me to delete the cookie before launching my request ?

**Comment by sdnts** [comment]
Manipulating cookies from the scripts is something that isn't supported yet, but we've been looking into it. We're tracking this here: #3312

**Comment by krogold** [comment]
Thank you

**Comment by charly37** [comment]
I wish I saw this post 2 days ago...
