### ISSUE TITLE
postman not launching

### ISSUE THREAD

**Issue by VikhyatChandra** [a85/POSTMan-Chrome-Extension#3430]
Hi i've installed postman using https://blog.bluematador.com/posts/postman-how-to-install-on-ubuntu-1604/?utm_source=hootsuite&utm_medium=twitter&utm_campaign= , Also i do see the icon in the gui although it fails to start

**Comment by sdnts** [comment]
Hi @monkmahadeva Do you mean the app gets stuck on the loading screen or do you not see the UI at all?

**Comment by monkmahadeva** [comment]
Hi i've installed postman using https://blog.bluematador.com/posts/postman-how-to-install-on-ubuntu-1604/?utm_source=hootsuite&utm_medium=twitter&utm_campaign= , Also i do see the icon in the gui although it fails to start

**Comment by VikhyatChandra** [comment]
when i click on the ui icon. it loads but never opens

**Comment by AndrewCarterUK** [comment]
I'm not sure if this is what I'm experiencing.

I've downloaded the Linux binaries, running "./Postman" exits without an error message.

Debian Stretch (fresh install).

**Comment by sdnts** [comment]
@monkmahadeva If it's stuck on the loading screen, can you open up the DevTools and check if there's any errors there?

@AndrewCarterUK We currently support only Debian 8 unfortunately.
[OS Support](https://github.com/electron/electron/blob/master/docs/tutorial/supported-platforms.md). We'll look into this.
