### ISSUE TITLE
Unable to display Postman app UI.

### ISSUE THREAD

**Issue by Tb0** [a85/POSTMan-Chrome-Extension#3431]
## App Details:

```
Postman for Mac
Version 5.1.3 (5.1.3)
Sierra 10.12.6
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there: Postman was working without any issue before this.
 2. Expected behaviour: Postman UI should be displayed as usual.
 3. No logs sorry.
 4. 
![screenshot](https://user-images.githubusercontent.com/772107/29615143-0cbc7548-880d-11e7-9ae7-04f2f7a98dd5.jpg)

## Steps to reproduce the problem:

Open Postman app.
You can see the icon into the dock.
You can see its menu on the top bar. Even the history items are displayed within the menu.
Right clicking on the postman dock icon and trying to display only postman doesn't work, even when clicking within the blue circle. (see screenshot)

I tried to uninstall. Reinstall. Didn't work.
Tried to install older version. Didn't work.

I'm stuck :-(

**Comment by sdnts** [comment]
@Tb0 Huh, looks like the app is stuck on some other screen. Can you head over to `~/Library/Application\ Support/Postman` and delete the `requester.json` file? This will reset the window settings for the app and it should show up again. Let me know if this works for you :)

**Comment by Tb0** [comment]
@madebysid That worked ! Thank you !!
