### ISSUE TITLE
Postman Echo - Utilities / Date and Time tests are wrong for 'Between Timestamps'

### ISSUE THREAD

**Issue by Yardglass** [a85/POSTMan-Chrome-Extension#3433]
## App Details:
Postman for Windows
Version 5.1.3
win32 10.0.15063 / x64

## Issue Report:
1. Go to https://docs.postman-echo.com/
2. Click [>Run in Postman]
3. Open the Utilities / Date and Time folder
4. Select 'Between Timestamps' tests

## Expected tests:

var **between** = JSON.parse(responseBody).**between**;

tests["Status code is 200"] = responseCode.code === 200;
tests["Comparsion was correct"] = **between** === false;

## Actual tests (looks like they've been copy-pasted from the 'after' tests):

    var= after = JSON.parse(responseBody).after;

    tests["Status code is 200"] = responseCode.code === 200;
    tests["Comparsion was correct"] = after === false;

![image](https://user-images.githubusercontent.com/1118977/29623488-26f2ef40-8859-11e7-9c33-d2c1be5da525.png)

**Comment by sdnts** [comment]
@Yardglass Thanks for letting us know, we'll get this collection fixed :)

**Comment by Yardglass** [comment]
Thanks, Just a heads-up that the **"Comparison was correct"** should probably be **"Date wasn't between passed values"** or similar.

**Comment by mccannt** [comment]
Closing this issue as it has now been resolved.
Please feel free to reopen with the steps to reproduce if the issue persists.
