### ISSUE TITLE
Cannot get Postman to Send Configured Client Certificate

### ISSUE THREAD

**Issue by lisagrady** [a85/POSTMan-Chrome-Extension#3434]
I'm using:
Postman for Windows
Version 5.1.3
win32 10.0.15063 / x64

I'm trying to get postman to send the configured client certificate to my target web server/host. 
I've added the client certificate from Settings -> Certificates
![image](https://user-images.githubusercontent.com/31289490/29632543-283fdf5e-87f8-11e7-84cb-d8d0fda7b1ae.png)

To test if the certificate is being sent, I launched the Postman console (ctrl+alt+c) and issued a GET request to https://echo.getpostman.com/get from Postman. When I expand the GET request in the Postman console it doesn't show the certificate being sent. Am I overlooking some obvious configuration? I'm new to Postman, so any advice is much appreciated!

GET
https://echo.getpostman.com/get
11:36:48.571
Request Headers:
cache-control:"no-cache"
Postman-Token:"3c3f4917-495c-4928-ae4c-9b3fa51cb902"
User-Agent:"PostmanRuntime/6.2.5"
Accept:"*/*"
accept-encoding:"gzip, deflate"
referer:"https://echo.getpostman.com/get"
Response Headers:
access-control-allow-credentials:""
access-control-allow-headers:""
access-control-allow-methods:""
access-control-allow-origin:""
access-control-expose-headers:""
content-encoding:"gzip"
content-type:"application/json; charset=utf-8"
date:"Wed, 23 Aug 2017 18:36:48 GMT"
etag:"W/"15e-fGDZW+FjhuzF3hmCi9JJqg""
server:"nginx/1.10.2"
set-cookie:"sails.sid=s%3A-XfVygvjl-wkILo4XXJF7gxVkkyoacs0.l7%2BAEAcAFhT%2BN7TgiJGxn7EhqON5JfU3UHxIMzPo2WM; Path=/; HttpOnly"
vary:"Accept-Encoding"
content-length:"238"
connection:"keep-alive"
Response Body:
args:
headers:
url:"https://postman-echo.com/get"

**Comment by sdnts** [comment]
Hi @lisagrady I suspect this has to do with the port number you've entered. Since you explicitly entered a port number when adding the certificate, the pattern match must be failing. If you send a request to `https://echo.getpostman.com:443/get`, the certificate should be attached correctly.

This shouldn't be needed in my opinion, so this looks like a bug. @kamalaknn Thoughts?

**Comment by lisagrady** [comment]
Thanks @madebysid!
I appreciate the help!  I tried passing the port in the request and I still don't see the certificate sent in the request.
![image](https://user-images.githubusercontent.com/31289490/29675007-b1115910-88a8-11e7-90eb-6c24c0c058ca.png)

Is it normal in the response I see the following URL?
"https://postman-echo.com/get"

**Comment by kamalaknn** [comment]
@madebysid you right. The port option in the proxy config has caused the request URL to not match.

The port option is not needed in the config. However, if it is specified the URL should also explicitly match the port. If we assume port in the URL and try to match it, it might fail if the config does not have the port.

This could be a tricky thing to decide. I think the thumb rule for the config could be to stick with the way requests URLs are used.

**Comment by lisagrady** [comment]
Ok, I was able to get it working by not specifying the port in the client certificate settings:
![image](https://user-images.githubusercontent.com/31289490/29675421-f7f2c480-88a9-11e7-912b-bdbf9ec8f43e.png)

Postman query and results through postman console:

![image](https://user-images.githubusercontent.com/31289490/29675462-142bceda-88aa-11e7-8f0f-d77f2ba871af.png)

Thanks again for the assistance!

**Comment by kamalaknn** [comment]
@lisagrady Great! 

I'm closing this issue for now. At the moment I don't think the port should be auto detected. Feel free to continue the discussion here.

**Comment by wangeugene** [comment]
Hey! noob here. Could you tell me where did you get the .key file, and . crt file for importing certificate into 
postman? I really want to know, thanks

**Comment by lisagrady** [comment]
@sail456852 - I haven't tested this in a while, but last time I tested I just created a self-signed certificate which you can do using something like keytool (https://docs.oracle.com/javase/1.5.0/docs/tooldocs/solaris/keytool.html). 

Otherwise, you can request a "real" certificate from a Certificate Authority.

Then, I converted the pfx into a separate key file. I used the steps from this URL as guidance for that:
https://www.markbrilman.nl/2011/08/howto-convert-a-pfx-to-a-seperate-key-crt-file/

Below are my sample commands:
C:\OpenSSL-Win64\bin>openssl pkcs12 -in jappleseed.pfx -nocerts -out jappleseed.key
Enter Import Password:
MAC verified OK
Enter PEM pass phrase:
Verifying - Enter PEM pass phrase:

C:\OpenSSL-Win64\bin>openssl pkcs12 -in jappleseed.pfx -clcerts -nokeys -out jappleseed.crt
Enter Import Password:
MAC verified OK

C:\OpenSSL-Win64\bin>openssl rsa -in jappleseed.key -out jappleseed-decrypted.key
Enter pass phrase for jappleseed.key:
writing RSA key

Finally, I was able to use the "decrypted.key" and the ".crt" files in the Postman client like you can see in my screen shots in the previous posts in this thread.

I hope this helps!
Lisa

**Comment by felickz** [comment]
On windows... Make sure the CRT is in PEM(ASCII) format and not binary.   Further, make sure if you generate the file on a linux machine that you convert to Windows line endings.

Error seen was: Error: error:0906D06C:PEM routines:PEM_read_bio:no start line

(similar error also seen when trying to use a PFX file in the CER upload field - Postman not validating file extensions there so watch for mistakes)

**Comment by Nagendra1DSY** [comment]
> @sail456852 - I haven't tested this in a while, but last time I tested I just created a self-signed certificate which you can do using something like keytool (https://docs.oracle.com/javase/1.5.0/docs/tooldocs/solaris/keytool.html).
> 
> Otherwise, you can request a "real" certificate from a Certificate Authority.
> 
> Then, I converted the pfx into a separate key file. I used the steps from this URL as guidance for that:
> https://www.markbrilman.nl/2011/08/howto-convert-a-pfx-to-a-seperate-key-crt-file/
> 
> Below are my sample commands:
> C:\OpenSSL-Win64\bin>openssl pkcs12 -in jappleseed.pfx -nocerts -out jappleseed.key
> Enter Import Password:
> MAC verified OK
> Enter PEM pass phrase:
> Verifying - Enter PEM pass phrase:
> 
> C:\OpenSSL-Win64\bin>openssl pkcs12 -in jappleseed.pfx -clcerts -nokeys -out jappleseed.crt
> Enter Import Password:
> MAC verified OK
> 
> C:\OpenSSL-Win64\bin>openssl rsa -in jappleseed.key -out jappleseed-decrypted.key
> Enter pass phrase for jappleseed.key:
> writing RSA key
> 
> Finally, I was able to use the "decrypted.key" and the ".crt" files in the Postman client like you can see in my screen shots in the previous posts in this thread.
> 
> I hope this helps!
> Lisa

Thanks a mil Lisa, this really helps.

**Comment by ma198307** [comment]
Hi, 
1) Testing client auth only pfx file with passphrase works
I have tested this scenarion with a selfsigned certificate in .pfx format(public, private key with passphrase) and that authenticate fine on  api1 through postman. api1 has this self signed cert on the hosted server.

2) Testing client auth using just  crt file option( .crt/.pem extension ASCII file format) fails
When I test api2 with a public client cert  with .cer or .pem extension (signed by DigiCert SHA2 Secure Server CA), the api trace logs shows the peer did not send any certificate in the request, while in postman console, it shows certificate is sent in the request. 
I am wondering if  anyone else noticed similar issue while verifying client auth with just  .crt file. 

Also does .crt file require passphrase option while configuring or is it optional?
My understanding is that client public key can be read with or without passphrase on the server as long as server has right CA.

3) I think most of the client would only share public key/certificate and not the private key or .pfx, it's good that postman supports all 3 modes , really helpful for the developer and testers.

**Comment by githubsheng** [comment]
@ma198307 

I had the exact same issue when working with just the crt file. Postman log shows that it sends the certificate but in fact, the server logs clearly shows that postman did not send the certificate. It confused me for a while.

When I use curl and its `clientCertificate` option to send just the crt file, everything works ok and the server responds correctly though. So it looks like a postman bug

**Comment by ericthomas1** [comment]
Does anyone know *how* Postman sends client certs across the wire as part of a request? 

**I'm in the dark on:**
- how its sent (hidden headers, body, etc.)
- how its encoded (ascii, utf8, etc.)
- etc. 

I need this info so I can convert/decode/compare certs in the app logic. 
Thank you
