### ISSUE TITLE
Collection Runner doesn't preserve selected collection across runs

### ISSUE THREAD

**Issue by mtoothman** [a85/POSTMan-Chrome-Extension#3435]
## App Details:
```
Postman for Mac
Version 5.1.3
OS X 16.7.0 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there: recently noticed but could have always been there
 2. Expected behaviour: Selected environment remains selected on subsequent runs executed with Collection Runner
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app): n/a
 4. Screenshots (if applicable)

Select an environment and collection (anything will do)
![image](https://user-images.githubusercontent.com/4804034/29633642-f9b4bd9a-8814-11e7-8469-d130fda06c57.png)

Run the collection.
Hit New
![image](https://user-images.githubusercontent.com/4804034/29633685-12968e60-8815-11e7-9139-563ce7fedb01.png)

Expected: previously selected environment is selected
Actual: whatever environment that was selected when Collection Runner started is selected

**Comment by sdnts** [comment]
Hi @mtoothman, if I understand correctly, the previous environment is selected, but the collection isn't right? I was able to reproduce this on my end. Please let me know if I misunderstood.

**Comment by sivcan** [comment]
@mtoothman The latest version of the [Postman App v6.1.4](https://www.getpostman.com/apps) fixes the issues regarding the selection.

Kindly update to the same.
Thanks.
