### ISSUE TITLE
beforeRequest support in Collections

### ISSUE THREAD

**Issue by Azuka** [a85/POSTMan-Chrome-Extension#3436]
## App Details:

```
Postman for Mac
Version 5.1.3
OS X 16.7.0 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:
 2. Expected behaviour:
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 4. Screenshots (if applicable)

This isn't a bug, but I couldn't find anything related in the docs.

I'm writing an integration test suite, and part of the requirements for a request is generating a signature using a hash of both the request parameters and the url. However, the url and several data parameters rely on environment variables, so the value of `request` in a pre-request script looks like this in the console:

```json
{
  "data": {
    "a": "{{varName}}"
  },
  "headers": {},
  "id":"77a53855-f09d-e9dd-fcb6-e2a3aa750aa5",
  "method":"GET",
  "name":"Health Check",
  "url":"{{apiUrl}}/v1/health",
}
``` 

I noticed `beforeRequest` is exposed for newman (where it'll eventually be run), but is there a hook to add that to the prerequest script for a single request in a collection, or to get the full request after environment/global variable substitution? Or even a helper method to perform environment variable substitution on an object or string?

**Comment by Azuka** [comment]
Looks related to #3322. I'll close after I verify the suggestions there work.

**Comment by sdnts** [comment]
@Azuka Indeed, this is the same issue as #3322. I've marked that as a feature request. In my opinion, a function that resolves variables would be useful.
I'm closing this in favour of #3322, please reopen if you feel otherwise!
