### ISSUE TITLE
Export v2 collection results in empty collection json file

### ISSUE THREAD

**Issue by Moegamad** [a85/POSTMan-Chrome-Extension#3439]
## App Details:

```
Postman for Windows
Version 5.1.3
win32 10.0.15063 / x64
```

## Issue Report:
Open Postman
Export V2 collection
The json file ends up with an empty item array.  nothing is exported to the json file. This is the content of the file:
{
"variables": [],
"info": {
"name": "DATA",
"_postman_id": "961996fb-d18c-16c8-dab9-5adff4513593",
"description": "",
"schema": "https://schema.getpostman.com/json/collection/v2.0.0/collection.json"
},
"item": []
}

**Comment by sdnts** [comment]
@Moegamad I've reopened #3099, which is where this was originally reported. Closing this as duplicate.
