### ISSUE TITLE
Feels a little slow

### ISSUE THREAD

**Issue by ssp0xd7** [a85/POSTMan-Chrome-Extension#3440]
## App Details:

```
Postman for Mac
Version 4.11.0
OS X 16.4.0 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:
 2. Expected behaviour:
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 4. Screenshots (if applicable)

**Comment by sdnts** [comment]
@ssp0xd7 We made several improvements to performance in recent releases. Can you try updating your app all the way to 5.1.3 and see if things feel better?

**Comment by ssp0xd7** [comment]
I've tried Version 5.3.0,it feels better,thx~
