### ISSUE TITLE
GUI: POST, SEND and SAVE buttons overlapped

### ISSUE THREAD

**Issue by mroche89** [a85/POSTMan-Chrome-Extension#3442]
## App Details:
Postman for Chrome
Version 5.1.3
win / x86-64
Chrome 60.0.3112.101

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:
I have noticed it for a couple months now. Can't say for sure whether it was there before and I ignored it or if it's new behaviour

 2. Expected behaviour:
Address bar should not disappear and UI components should not overlap

 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
Right clicking doesn't reveal any options so I'm not sure how to open console in the app. If logs would help, please advise.

 4. Screenshots (if applicable)
![postmanbugreport](https://user-images.githubusercontent.com/3477933/29696351-ae31e1cc-898b-11e7-9241-ff3e93808ebf.gif)

This is rereporting issue 2186.

The behaviour is not always consistent. In the gif example, I am not able to choose which tab gets the erroneous positioning. When it does happen to a particular tab however, that tab will continue to produce this behaviour every time the window is resized.

In my example in the gif, it only occurs on the 5th tab but that's not always the case. It occurs when resizing the window. It will not affect the active tab, only one off screen. If the tab with the bad position becomes the active tab prior to a resize, the correct positioning is restored. This is the only way that I can get around the issue at the moment.

**Comment by sdnts** [comment]
@Trestal Thanks for reporting this! I'll take a look at this.

**Comment by prashantagarwal** [comment]
@Trestal This is fixed in latest Postman apps
