### ISSUE TITLE
Need to be able to Sign In with multiple Accounts for PRO

### ISSUE THREAD

**Issue by mdridley** [a85/POSTMan-Chrome-Extension#3445]
Our company does a lot of consulting and thus works with multiple companies that were using or have been introduced to Postman. However it is very difficult to associate and use multiple Pro teams with different organizations right now. It would be handy if it was closer to iTunesConnect where I could choose the company/team and view/create syncs from there.

**Comment by sdnts** [comment]
@mdridley Thanks for the feature request! This is actually planned for release very shortly. We're working on this as we speak. I'll let you know here when this is out.

**Comment by a85** [comment]
This is available now in the latest versions of the app.
