### ISSUE TITLE
Conditional logic in test to skip rest of iteration's API calls, move on to next iteration

### ISSUE THREAD

**Issue by Bharwcb** [a85/POSTMan-Chrome-Extension#3446]
## App Details:
```
Postman for Mac
Version 4.11.0
OS X 16.4.0 / x64
```

## Issue Report:
 1. This issue has existed previously.  I assume it is user error and I just do not yet know how to do what I need ;)
 2. For simplicity sake, I have two API calls in a collection runner.  I import a CSV with just one column with a header called Body.  I have 4 iterations of a Body data that I will use as the actual body in the 1st API call's request (using {{Body}}, this works), then make some other trivial 2nd API call just to demonstrate this issue.  S

FYI in my first API call is just requesting an accessing token.  I want to set up conditional logic to either continue the test script, or move on to the next iteration.  This is because that would mean the data is bad for that iteration, and I want to move on.

Test script for my 1st API call (requesting the access token):
```
if (responseCode.code !== 200){  
    console.log("1st API call unsuccessful.");
    // Expecting to use postman.setNextRequest(null); to skip the 2nd API call in this iteration, and just move on to the next iteration.
    postman.setNextRequest(null);
} else {
    console.log("1st API call successful: Access token created");
    // handle response
}
```

Test script for my 2nd API call:
```
if (responseCode.code !== 200){  
    console.log("2nd API call unsuccessful.");
} else {
    console.log("2nd API call successful.");
}
```

For this situation, I intentionally made my data bad for the 2nd of 4 iterations.  I would expect it to skip to the next iteration once encountering the error code other than 200, which it does, but then it skips that second API call for all subsequent iterations (iteration 3 & 4). 

 3.Console.log:

```
1st API call successful: Access token created
2nd API call successful.

common.js:121056 POST (url) 400 (Bad Request)
1st API call unsuccessful.

1st API call successful: Access token created

1st API call successful: Access token created
```

So, what's happening here:

- First iteration: runs both calls.
- Second iteration: fails first call, so skip 2nd API call (as expected, I want this)
- Third iteration: only runs first call (I want BOTH API calls to run).
- Forth iteration: only runs first call (I want BOTH API calls to run).

**Comment by sdnts** [comment]
Hi @Bharwcb! Thanks for taking the time to explain the issue in detail!

I made a simple collection to imitate what you're trying to do [here](https://documenter.getpostman.com/view/214062/gh3446/6nBvAjc).

It has 3 requests, and it is supposed to skip over the 3rd request in the second iteration. I use `postman.setNextRequest(null)` to skip over the third request, and my condition is the current iteration number. Although this does not use any data files, it should, in essence be the same as your collection, correct?

Here's what my run looks like (which is what you expect as well, right?)
![screenshot 2017-08-28 14 31 58](https://user-images.githubusercontent.com/7689783/29767027-80106b68-8bfe-11e7-8bf4-78a0a47423ec.png)

Can you import this collection and see if this works correctly on your app (I'm on 5.1.3, I'd recommend updating before checking)? If it does, can you check the conditions you have in your scripts to see if there are problems there?

Do let me know if the collection isn't like yours, so I can update it and try to replicate again. :)

**Comment by Bharwcb** [comment]
Hi @madebysid thanks for your reply!

I may have discovered what the issue was.. I did not realize you have to explicitly tell the request in its test to proceed to the next API call, if you are using postman.setNextRequest(null) at all.

So an example of the solution was:
```
if (responseCode.code === 200) {
    setNextRequest('Next API Call');  // I didn't realize I needed this
} else {
    setNextRequest(null);
}
```

Is this accurate?

I also had a separate but related question of where all of the attributes like responseCode.code, responseBody, etc. are documented.

Thanks!

**Comment by sdnts** [comment]
@Bharwcb By default, the next request in order will be run, even if you omit `postman.setNextRequest`. You can see this in the collection I shared.

Docs for the test API are [here](https://www.getpostman.com/docs/postman/scripts/postman_sandbox_api_reference)

**Comment by gigamac** [comment]
your link 
https://documenter.getpostman.com/view/214062/gh3446/6nBvAjc returns a 404
