### ISSUE TITLE
Add proxy configuration for using Postman's cloud features

### ISSUE THREAD

**Issue by StormRider01** [a85/POSTMan-Chrome-Extension#3450]
Postman for windows appears to not use the "Use System Proxy" setting for App level traffic, specifically for Sync traffic (and specifically to NOT use the system default proxy).

We have a ZScaler in our environment, pushed as an Automatic configuration script. (chrome settings -> open proxy settings -> Lan Settings). When the proxy is used, both Chrome Postman and Windows Postman are unable to sync. Disabling the proxy and restarting the apps allows both to Sync.

As far as I can see, it's very similar to this issue:  #3001 

ZScaler is returning a 307 if specific auth cookies are not present, and Postman doesn't pop a window to allow authentication.

## App Details:
Postman for Windows
Version 5.1.3
win32 10.0.15063 / x64

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there: 
Unknown, new user in this environment.

 2. Expected behaviour:
Postman should sync

 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
No console activity
 4. Screenshots (if applicable)

**Comment by sdnts** [comment]
@StormRider01 I'm not familiar with ZScale, but the reason we cannot use proxies for Sync is because there is no support for websockets. Correct me if I'm wrong, but I think there's little we can do here.

**Comment by StormRider01** [comment]
@madebysid I'm seeing the exact opposite behavior- with a system proxy specified, Sync hangs on Connecting. When I disable the system proxy and restart Postman, it almost immediately hits In Sync status. This is with "Global Proxy Configuration" and  "Use System Proxy" off.

I also pulled down Version 5.2.0 win32 10.0.15063 / x64 today, same behavior.

For my environment, simply using the Use System Proxy = off for the App communications would be sufficient, as traffic isn't _Required_ to use the proxy.

**Comment by sdnts** [comment]
@StormRider01 We do not use the proxy set within the app for Sync traffic and specifically. That uses your system proxy, as you've noticed.
So what's happening is, your system proxy is used for communicating with Sync even if the `Use global proxy` switch is turned OFF, so Sync gets stuck on `Connecting`. I'm treating this as a feature request!

**Comment by ankurdengla** [comment]
Hey @StormRider01  !

We’ve released authentication support for proxy servers in the latest canary version (v7.18.0-canary02) of the app. The app will use the system proxy settings by default and show a window to enter credentials if the proxy server requires authentication. Please give it a try and share any feedback that you might have with us.

The canary app can be downloaded from here - https://www.postman.com/downloads/canary.

**Note that the request sending feature will still rely on the proxy settings available in Settings.**

**Comment by ankurdengla** [comment]
Hey @StormRider01 !

Proxy authentication support has been released as part of Postman v7.21.0.
