### ISSUE TITLE
Postman Sandbox API reference

### ISSUE THREAD

**Issue by 1jcruz** [a85/POSTMan-Chrome-Extension#3451]
## App Details:

```
Postman for Windows
Version 5.1.3
win32 6.1.7601 / x64
```

My apologies if this is very basic. I'm new to Postman. In the documentation, there is a section on Postman Sandbox API reference (https://www.getpostman.com/docs/postman/scripts/postman_sandbox_api_reference). It states that a number of NodeJS modules are available. I need to use the url module, and I see that it is not available. (Note: I need it to calculate a header value in a pre-request script). Is there an alternative way of loading it?

**Comment by sdnts** [comment]
Hi @1jcruz, all node modules are not included in the sandbox as of yet.
Out of curiosity, how are you going to calculate the header? Maybe there's an easier way to do that using currently included modules.

**Comment by 1jcruz** [comment]
Hi @madebysid, I'm trying to call the Canvas Data API. It uses an authentication method that requires me to create an encoded hash signature based on 8 string elements, 2 of which come from the API URL. The JavaScript they recommend to use is:

`var crypto = require('crypto')`
`var url = require('url') `
`var HMAC_ALG = 'sha256'  `
`var apiAuth = module.exports = {  `
`  buildMessage: function(secret, timestamp, uri) {  `
`    var urlInfo = url.parse(uri, false);  `
`    var query = urlInfo.query ? urlInfo.query.split('&').sort().join('&') : '';  `
`    var parts = [ 'GET', urlInfo.host, '', '', urlInfo.pathname, query, timestamp, secret ]  `
`    return parts.join('\n')  `
`  },  `
`  buildHmacSig: function(secret, timestamp, reqOpts) {  `
`    var message = apiAuth.buildMessage(secret, timestamp, reqOpts)  `
`    var hmac = crypto.createHmac(HMAC_ALG, new Buffer(secret))  `
`    hmac.update(message)  `
`    return hmac.digest('base64')  `
`  }  `
`} `

(Note: full details at https://community.canvaslms.com/docs/DOC-6623, if you want to read them)

I realized that I couldn't load the crypto or url modules into Postman as written, and that's when I dived into the documentation. I switched to using Postman's crypto-js module, but that's as far as I got. Am I correct in assuming that if a version of the url module is not available, then I will have to write my own code to perform the URL string parsing, splitting, sorting, and joining?

**Comment by sdnts** [comment]
@1jcruz You should be able to `require('url')` starting with 5.2.0 🎉
Also, instead of `require('crypto')`, you can use CryptoJS, which is included in the sandbox. Do let me know if this works for you :)

**Comment by aggieben** [comment]
I'm trying to do `require('url')` and getting back an empty object (`{}`).  Here's my script:

```
const url = require('url')
console.debug(url)
```

The console shows this:
![image](https://user-images.githubusercontent.com/1321/38900172-1970ab48-4260-11e8-9684-a468dc5d8461.png)

I'm on Postman 6.0.10
