### ISSUE TITLE
Replace Environment Variable with real value when publishing docs

### ISSUE THREAD

**Issue by elzii** [a85/POSTMan-Chrome-Extension#3453]
I would love to be able to replace variables with their real values when publishing docs. Consider the following scenario when using variables in the request URL:

## Environments

**Environment A - (Dev)**

`api_host` - `dev.example.com`

**Environment B - (Production)**

`api_host` - `www.example.com`

## Example Request

```
GET http://{{api_host}}/users
```

We use variables in the paths for a ton of calls. Being able to swap a token, or test/dev/prod servers is a huge win for efficiency without having to rewrite all the request URLs.

Having them be replaced with the actual values would be far more useful to the consumer of the docs rather than the variable.

**Comment by sdnts** [comment]
Hi @elzii, before publishing docs, if you specify an environment to associate it with, the variables in that environment template will be used to populate values in the collection.

<img width="1866" alt="screenshot 2017-08-29 16 02 07" src="https://user-images.githubusercontent.com/7689783/29816853-6d441d60-8cd3-11e7-98e6-84d463cc8155.png">

**Comment by elzii** [comment]
Sweet! I was hoping it was user error :P Thanks.
