### ISSUE TITLE
Can't add description right after we reopen Postman 

### ISSUE THREAD

**Issue by florinciubotariu** [a85/POSTMan-Chrome-Extension#3454]
## App Details:
Postman for Chrome
Version 5.1.3
win / x86-64
Chrome 60.0.3112.113

## Issue Report:
1. Create a request without a description and save it in a collection.
2. Make sure the tab with that request is opened.
3. Close Postman and open it again.
4. There is no way to add the description of the request. In order to be able to add a description, we must change to another request (another tab) and come back.

**Comment by sdnts** [comment]
@florinciubotariu Oh wow thanks for reporting this, I was able to reproduce this. We'll get this fixed.

**Comment by a85** [comment]
@madebysid Is this fixed?

**Comment by sujayvenaik** [comment]
Hey,
@florinciubotariu 

Can you update the app to the latest version and try this ?
I tried but could not re produce on the latest version of the app.

You can download the app from https://www.getpostman.com/apps

**Comment by florinciubotariu** [comment]
Hello @sujayvenaik
I can confirm this does not reproduce anymore.
