### ISSUE TITLE
Download/export dialog is hidden behind Postman

### ISSUE THREAD

**Issue by mstaalesen** [a85/POSTMan-Chrome-Extension#3456]
In Postman 5.1.3, if I want to save or export a collection or environment, the save dialog is hidden behind Postman.

Linux Native App.
Ubuntu 14.04

**Comment by sdnts** [comment]
@mstaalesen Does it always open behind the Postman window? I tried this on an Ubuntu VM but was unable to replicate.

**Comment by mstaalesen** [comment]
Try the following:

1) Start Postman
2) Try to export a collection
-> Dialog appears correct

3) Move Postman from Screen 1 to Screen 2
4) Try to export a colletion
-> Dialog appears behind Postman

**Comment by dannyhajj** [comment]
This may be an issue with Unity though. It used to happen to me with different applications as well. For example, when trying to open the file dialog to upload files in Firefox.

**Comment by mstaalesen** [comment]
That may be true! I'll close this issue since it seems to be hard for you to reproduce.
