### ISSUE TITLE
[Bug] - Opening the console using shortcut Key in Postman causes it to open twice

### ISSUE THREAD

**Issue by Faz540** [a85/POSTMan-Chrome-Extension#3457]
**Postman Windows App,
Windows 10 x64 Bit.**

I'm not sure if this occurs on the Mac/Linux apps too.

Using the shortcut key to open the Postman Console (CTRL + ALT + C) sometimes causes two instances of the console to open.

I've confirmed this happening on other people's machines in our office.

I can re-create this 100% of the time, but it seems to happen when you open the console for the first time when opening Postman.

I've never seen this issue occur when opening the console via the "View > Show Postman Console" menu item.

This issue isn't a new bug as I can remember this happening when I first started using the Windows app for Postman, I just assumed this was occurring due to my keyboard. But like I said, I've confirmed this issue with several other people using the Windows app.

**Comment by sdnts** [comment]
@Faz540 Weird, I was able to reproduce this. Thanks for reporting this!

**Comment by djbf** [comment]
I just tested this on Mac/5.2.0 and it doesn't seem to be an issue there.

**Comment by vegetableman** [comment]
@madebysid the issue was reproducible on version `5.0.2` on Mac. Does not seem to the case for the latest version `5.2.0` on Mac. Not sure of other platforms.

**Comment by Faz540** [comment]
Just reproduced this on version 5.2.0 on Windows.

To be fair, this is the first time I've encountered it this week.

**Comment by Faz540** [comment]
Just reproduced on version 5.2.1 on Windows

**Comment by a85** [comment]
Can't seem to reproduce this in 5.5

**Comment by Faz540** [comment]
@a85  Yep, unable to reproduce this in Windows 5.5.0. :)
