### ISSUE TITLE
[Feature Request] Basic Auth with Password Only

### ISSUE THREAD

**Issue by tomoguisuru** [a85/POSTMan-Chrome-Extension#3458]
## Settings
```
Postman for Mac
Version 5.1.3
OS X 10.12.6 / x64
```

## Details
I'm currently using the Reflect.io API to pull information about our linked data. Their API what I'd consider an edge case of BasicAuth and only uses a password. (no user) Currently in Postman, you have to have both the username and password in order for it to automatically generate the Base64 encode string. 

## Feature Request
Allow for the BasicAuth info to be saved without a username by either having a checkbox or a confirmation dialog indicating that the `username` is not present and may cause issues

## Requirements
BasicAuth encoding should allow for the following string to be encoded, `:<password>`

Example:
`:MySuperAwesomePassowrd` -> `Ok15U3VwZXJBd2Vzb21lUGFzc3dvcmQ=`

**Comment by sdnts** [comment]
@tomoguisuru We're working on improving auth flows in the native apps, we'll keep this in mind. Thanks for the request!
In the mean time though, you should be able to use CryptoJS (included in the sandbox) in combination with environments to do this!

**Comment by harryi3t** [comment]
Since the [basic auth RFC](https://tools.ietf.org/html/rfc7617#section-2) does not say anything about the username and password being required/optional, it's safe to leave it to the server implementing it

That said, we will be updating our logic to make the username & password optional 🎉 
Will keep this thread posted about the updates.

**Comment by harryi3t** [comment]
Hi, Brandon

Postman 5.3.0 is out with the fix. Now you can omit the username field and it should just work fine.
 Please re-open if the fix is not working for you. I will be more than happy to assist you.

Thanks
