### ISSUE TITLE
Runner generates request URL using unmarked key value.

### ISSUE THREAD

**Issue by susumuf** [a85/POSTMan-Chrome-Extension#3459]
## App Details:

```
Postman for Windows
Version 5.20.0
Windows 10 v1703 build 15063.483 / x64
```

## Issue Report:
100% reproducable.
 I faced a problem /w runner which is generating request URL using unmarked key value.

here's steps as below screen shot
define URL
![definedurl](https://user-images.githubusercontent.com/13374698/29852657-4b869150-8d76-11e7-9b50-de766ed72aa6.jpg)
runner generated URL
![generatedurl2](https://user-images.githubusercontent.com/13374698/30016999-68b8aa04-9192-11e7-908d-956c6dc4a4b7.jpg)

hope this gonna be fixed or a way escape. I don't wanna chage my definition each testing /w runner.

**Comment by sdnts** [comment]
@sumf Thanks for reporting this, we'll get this fixed with the next version.

**Comment by sivcan** [comment]
@sumf The latest version of the [Postman Native App (v.6.1.4)](getpostman.com/apps) doesn't have this issue.
Just make sure that your requests are saved before running them in the runner.

The keys that were marked as disabled (unchecked) are the one's that won't appear as params in the request when running the request.
