### ISSUE TITLE
DCR:Breaking the 1MB barrier – Postman console

### ISSUE THREAD

**Issue by susumuf** [a85/POSTMan-Chrome-Extension#3461]
## App Details:

```
Postman for Mac
Version 5.20.0
Windows 10 v1703 build 15063.483 / x64
```

## Issue Report:
Not a issue, just DCR(Design Change Request)

To dig a response body, json/xml array data is increase in the size potentially.
so I would request Max size is 10MB minimum or larger than.
![1mb](https://user-images.githubusercontent.com/13374698/29859783-a9f9da08-8d9e-11e7-97a8-981a8fd0aed5.jpg)
not sure best size.

**Comment by susumuf** [comment]
Ooops, not for Mac, I used for Windows native client.

**Comment by sdnts** [comment]
@sumf This was done because of performance issues. I'm marking this as a feature request!

**Comment by ritwijsinha** [comment]
@susumuf 

We broke the 1 MB barrier in Postman Console! 🎉 

Update to Postman v7.13 to use this.

Cheers!
