### ISSUE TITLE
Documenter | Styles for request types in headers not applied consistently

### ISSUE THREAD

**Issue by djbf** [a85/POSTMan-Chrome-Extension#3464]
## App Details:

```
Postman for Mac
Version 5.2.0
OS X 16.7.0 / x64
```

## Issue Report:
When viewing generated docs, the CSS styles from importer.css aren't consistently (mostly not, in my case) applied across requests type headings. 
```
.GET {
  color: #3eb63e; }
.POST {
  color: #f5a623; }
.PATCH {
  color: #666666; }
.PUT {
  color: #4a90e2; }
.DELETE {
  color: #ed4b48; }
```

Some sample headings:
![happy-colors](https://user-images.githubusercontent.com/694161/29888621-6f814a32-8d76-11e7-9f87-d9c5b07294ed.png)
![image](https://user-images.githubusercontent.com/694161/29888693-a58ccfa2-8d76-11e7-8a63-03773426a0d8.png)

**Comment by sdnts** [comment]
Hi @djbf! Is this happening for specific endpoints? Could you let me know steps you followed to do this? That'll help us get this fixed as soon as possible :)

**Comment by djbf** [comment]
I copied one of the unstyled calls to a new collection, sanitized it, and am attaching the exported json here in case it yields anything helpful. 

One thing worth noting, though, is that the Postman Echo and Postman BDD collections I've imported do not seem affected by this issue when viewing their documentation. I haven't had much luck reproducing this with newly created calls and was way too deep in to my collection before I realized the display issue in my collection docs.

I'm not using any special characters in the description fields or anything seemingly oddball. I did create this collection under a previous Postman version, so it could just be a past issue. Maybe I'll use this holiday weekend to reconstruct my collection manually as copying and pasting seems to preserve the styling error.
[3463.zip](https://github.com/postmanlabs/postman-app-support/files/1271639/3463.zip)

**Comment by godfrzero** [comment]
@djbf I've pushed out a new version with a fix for this, can you take a look and let me know if it's working as expected now?

**Comment by djbf** [comment]
Much improved! Thanks, Vivek!  All the request types are colored consistently now. The only lingering issue I'm seeing now is that they aren't all uppercase.  In the page code, interestingly, it seems like the GET, PUT, etc. are natively uppercase rather than being made that way by a text-transform property.

![image](https://user-images.githubusercontent.com/694161/30183352-f2863240-93ce-11e7-9e9f-1691409a1036.png)

**Comment by godfrzero** [comment]
Yep, I've queued that up for the next release which should be out around this time next week. I'll update this thread when it's out.

In the meantime, if you want to fix the formatting issue before that, duplicating the request should fix it. The problematic requests were created using an older version of the app which messed up the casing.

**Comment by djbf** [comment]
Thank for that tip and thanks for your work!
