### ISSUE TITLE
Postman Echo POST won't echo the HTTP headers of the request.

### ISSUE THREAD

**Issue by jmunozz** [a85/POSTMan-Chrome-Extension#3465]
## App Details:
Chrome App
```
Postman for Mac
Version 4.11.0
OS X 16.4.0 / x64
```

## Issue Report:
1. I just encounter this issue this issue recently as I'm start using the mock API along with postman echo.
2. * I'm using the postman-echo API. I'm working on the POST https://postman-echo.com/post endpoint. 
    * The doc says `This endpoint echoes the HTTP headers, request parameters, the contents of the request body and the complete URI requested.`But when I try to add any header to the request. I won't find any of my headers in the response. 
4. 
![capture d ecran 2017-08-30 a 15 27 41](https://user-images.githubusercontent.com/16085772/29891099-ee74d338-8d97-11e7-92f2-8c2ee997950f.png)
![capture d ecran 2017-08-30 a 15 28 00](https://user-images.githubusercontent.com/16085772/29891107-f301dbe4-8d97-11e7-82ac-ac3fa9b22bc7.png)

**Comment by kunagpal** [comment]
Hey @jmunozz, the `Headers` tab is for headers belonging to the current response. Here, the response is the actual response returned from Postman Echo. In order to see the request details,  you'd have to click on the `Body` tab (which is to the left of `Headers`).

**Comment by jmunozz** [comment]
**I see... the headers are echoed in the body of the request. Thanks, it makes sense.**

Problem is I use this response for mocking an API endpoint. 
And the browser won't allow any response with invalid `access-control-allow-origin` header (in this case header is sent but empty).
How could I force this header to be `*` in the Postman-echo response ?

**Comment by kunagpal** [comment]
There's no way to force this from a requester's perspective consistently across all Echo endpoints, but the returned value can be changed.
