### ISSUE TITLE
Add a Save All menu/hotkey option

### ISSUE THREAD

**Issue by idevtech** [a85/POSTMan-Chrome-Extension#3466]
## App Details:
```
Postman for Windows
Version 5.2.0
win32 10.0.15063 / x64
```

## Issue Report:
Often I have multiple request tabs open and have edited them. Is there a Save All menu option or hotkey? I've searched the app and docs but have been unable to find information about this operation. It's cumbersome to go to each tab individually and click Save. Sometimes I have up to 20 tabs w/ changes.

**Comment by sdnts** [comment]
Hi @idevtech! There isn't a button like this. but we've been looking into tab issues lately and I'll consider this a feature request :)

**Comment by theampersand** [comment]
Better yet: auto-save!

**Comment by darioseidl** [comment]
Yes, please! The only workaround right now seems to be using "Close All" in the tab bar and then hitting Enter a dozen times.

**Comment by aaronshaver** [comment]
This is badly needed.

**Comment by dbodow** [comment]
Lack of this (and even better would be auto-save, or version controlling) makes Postman a very unreliable tool. I either triple save everything just to be sure, or realize that one of the changes I made to a monitored test hasn't stuck around the next day.

Even better than save-all/autosave would be some sort of git-like version controlling where I can see what changes I've made, stage & commit them, and roll forward and back across changes over time. That's how everyone manages code tests these days, and it's a glaringly missing part of Postman.

**Comment by dht** [comment]
I would like to have a save on send. Same same by different. Whenever I send a request, for me, it means it is valid and good and can be saved. That is why I would very much appreciate a **Save on send**. 

I agree with prior posters that having multiple tabs with an orange dot and remembering which ones need saving 15 minutes after modification is not the optimal UX experience. 

Most code editors support auto save as default by now (VScode has a parameters to enable it) and I see postman as a code editor as firing HTTP requests is part of the development cycle.

**Comment by Caltor** [comment]
@dht Totally agree, this issue alone is pretty much forcing me to use Insomnia instead.

**Comment by stedwick** [comment]
Auto save and save all, please!

**Comment by a85** [comment]
Improvements to tab management are in our Canary build right now. Postman now will store unsaved changes in buffers which means we don't have to prompt to ask people to save. The next bit here is to have an option for Auto Save. We have a version control system in place already (being able to rollback for example) - forking and merging will be available soon.

**Comment by ricardf-cmp** [comment]
Any forecast when this feature will make it live? We're a team of 9 QA's using this app (Pro accounts) and just discovered this nice "easter egg" from Postman. If not solved soon we might very well migrate to some other tool that doesn't force us to save all modifications manually, one at a time...

**Comment by petereps** [comment]
Also would love this feature. Just lost an entire day of work due to not realizing the "Sync across devices" doesnt actually save anything else.

**Comment by dineshviswanath** [comment]
I am not sure what is going wrong in postman team. I see request for "Autosave" from 2015 in other place. Yet, postman is not fixing it. Could someone from postman team possibly answer this question "Why we dont have autoSave of request after being persistently requested from community?" 🙏

**Comment by fh32000** [comment]
**Auto save , save all and Close&Save All , please!**

**Comment by vfragola** [comment]
This is badly needed.  Any thoughts on when this feature request will be completed?

**Comment by maxim-danilov** [comment]
I imported 120 curl queries to Postman. Postman doesn't have 'save all' button. 
So I did **360 mouse clicks** to save all the open tabs (of course I used an xdotool macro for automating).
Please improve usability by adding 'save all' button.

**Comment by friend0** [comment]
This is RIDICULOUS. Making multiple edits across requests is super common, and I can't be sure the requests I'm building are the same ones my product team is using unless I go through every single request and save. This will be the reason I abandon this tool and cancel our team account. FIX THIS NOW

**Comment by rlundy** [comment]
> Improvements to tab management are in our Canary build right now. Postman now will store unsaved changes in buffers which means we don't have to prompt to ask people to save. The next bit here is to have an option for Auto Save. We have a version control system in place already (being able to rollback for example) - forking and merging will be available soon.

All this sounds lovely, but it brings to mind that saying about letting the Perfect be the enemy of the Good.  Autosave might not be perfect, but it's a lot better than what we have now: Either losing work, or UI annoyance by being asked for every tab if we want to save it.  (Also, that update was from a _year_ ago.)

How about a quick autosave option that we can use _now_ instead of some kind of convoluted built-in source control that we can only use in a hypothetical future?

**Comment by achavate** [comment]
this is very painful. Please provide save all options. Autosave would be wonderful

**Comment by smart-niggs** [comment]
Any progress/feedback with the auto save feature, I might consider checking out other tools.

**Comment by mensoh** [comment]
I enjoy using Postman quite a bit, but like the others here the amount of time spent on double checking if my changes across 25 open tabs have been saved is becoming really quite painful 😢 
Is there any reason this hasn't happened yet?

**Comment by stokescomp** [comment]
And if there is an auto save. Lets have an option to turn auto saving off encase I am making changes that I don't want to save. And when I am ready to save I will use save all menu or shortcut.

**Comment by katlimruiz** [comment]
autosave and saveall +1

**Comment by mbaric** [comment]
autosave and saveall :1st_place_medal: 
Come on that can't be that hard to implement, if you need help in this few of us am sure can help out but this is like totally needed.
@madebysid

**Comment by mmeloni** [comment]
autosave and saveall +1

**Comment by cinphon** [comment]
autosave and saveall +1

**Comment by lostindark** [comment]
I don't know how many times I modified a lot of requests but forget to save them before I close those tabs. Only find out when tests failed.

Need the following features:
1. Warning there are not saved modifications when: close tabs, run test collections.
2. Offer an option to save all.
3. Auto save!
4. The modified status dot should show up in collections too (not only on tab).

**Comment by jbevarts** [comment]
If anything, saveall.  How was this not considered in v1?

**Comment by bu4ak** [comment]
Autosave and Save All **+1**

**Comment by Camineet** [comment]
omg

**Comment by jimpudar** [comment]
Still no autosave in 2020? Amazing!

**Comment by SergeyShidlovsky** [comment]
A lot of development teams in Ukraine are ROLFing  across absence of the "Autosave" Feature

**Comment by rlundy** [comment]
Hey, look, in just three short weeks this issue is going to have its 3rd birthday.  What a great birthday present it would be to implement this feature!  🎂 🎉

**Comment by pbrink231** [comment]
Would love to have this feature.  I always end up with ton of unsaved tabs.  Auto save or atleast a close and save all button

**Comment by aktur** [comment]
+1 for this option. I've asked for this on a webinar and was directed to this thread. It shouldn't be too hard to get it done in the next sprint? Listen your customers, please ;)

**Comment by SergeyShidlovsky** [comment]
> +1 for this option. I've asked for this on a webinar and was directed to this thread. It shouldn't be too hard to get it done in the next sprint? Listen your customers, please ;)

They have directed you to this thread and what did they ask from your side to do in this thread?

**Comment by aktur** [comment]
Observe it for news

> > +1 for this option. I've asked for this on a webinar and was directed to this thread. It shouldn't be too hard to get it done in the next sprint? Listen your customers, please ;)
> 
> They have directed you to this thread and what did they ask from your side to do in this thread?

Observe it for news.

**Comment by vfragola** [comment]
> > +1 for this option. I've asked for this on a webinar and was directed to this thread. It shouldn't be too hard to get it done in the next sprint? Listen your customers, please ;)
> 
> They have directed you to this thread and what did they ask from your side to do in this thread?
Stare at it and hope it happens via osmosis.

**Comment by countzero** [comment]
+1 for this option.

**Comment by JanDoggen** [comment]
Agree with a lot of earlier posters - this feature should have been in the interface yesterday! The environment becomes a mess with tons of open tabs, many with unsaved data. I have lost data this way.
In addition to the 'save' features, the tabs should also have the ability to autoclose, i.e. only one remains open:
As soon as more tabs are open than fit in the current view, it is much easier to open a request from the collections than trying to remember and find an open tab.

**Comment by bababuuui** [comment]
+1

**Comment by GXelha** [comment]
+1 
I don't understand what's the thinking behind not having the ability to save all tabs at once, it's really cumbersome to go one tab at a time.

**Comment by Samgrocock** [comment]
+1

**Comment by jbevarts** [comment]
Are you an engineer?  Have you ever built a project and wanted to test it? Have you ever lost data from working on several APIs at the same time because you didn't save each one individually?  Do you ever want to gut postman from your workflow when you realize save all isn't an option?  Do postman engineers use postman to test?  

Yes.

**Comment by mmeloni** [comment]
This thread gathers all the war wounded

**Comment by jkennaly** [comment]
for(var i=0;i<tabs.length;i++) {
 tabs[i].save();
}
Maybe something like that?

**Comment by jamesholland-uk** [comment]
Another war-wounded engineer, who lost a few hours of API work. Pleeeeeeeeeeeeease can there be something (auto-save is my number one preference, but save-all would be second choice if quicker/easier to implement) to save the pain of re-doing API work? Many thanks :-)

**Comment by silverboots** [comment]
+1

**Comment by andres-loyola** [comment]
+1

**Comment by edemen** [comment]
+1

**Comment by anjasnewbie** [comment]
please add this feature, we need it badly

**Comment by diegojuan2104** [comment]
+1

**Comment by oyamo** [comment]
4 Year Anniversary for this feature request

**Comment by Juraj-Masiar** [comment]
Maybe someone here would like to contribute a patch for this? :)
I can imagine the implementation would be pretty simple, something like:
```ts
const tabs = await browser.tabs.query({});
await Promise.all(tabs.map(t => storageAPI.saveTab(t)));
```

**Comment by beshoo** [comment]
+1

**Comment by boredhero** [comment]
+1 and also an autosave option i could enable to just save things whenever i change them would be great.

**Comment by sujayvenaik** [comment]
@boredhero and everyone in this GH thread.

Hey,
We have started rolling out autosave in beta.
Ref: https://github.com/postmanlabs/postman-app-support/issues/8195#issuecomment-1549587681

-----------------------------------------------------------------------------------------------------------
Hi, 

We are rolling out beta version of Autosave in [Postman v10.14](https://www.postman.com/downloads/) . To try out the feature:
1. Fill out the [Google form](https://docs.google.com/forms/d/e/1FAIpQLSdkaNemRWs_og-s6aq7YTHR090tSjJH_AshthFs3IYnvrkA-w/viewform) with details.
2. We will enroll you into the beta program.
3. You will soon receive an email with details on how to get started.

We look forward to you trying out the feature and sharing your [feedback with us](https://github.com/postmanlabs/postman-app-support/issues/12016).

_Originally posted by @sujayvenaik in https://github.com/postmanlabs/postman-app-support/issues/8195#issuecomment-1549587681_

**Comment by giridharvc7** [comment]
We've now enabled this for all accounts as an Opt-in feature.
You can turn on application wide autosave from Settings -> General -> Application -> Autosave


We'd love to know what you think about this, feel free to post your feedback in this thread, or [here](https://github.com/postmanlabs/postman-app-support/issues/12016)
<img width="1512" alt="image" src="https://github.com/postmanlabs/postman-app-support/assets/1040583/1f477c69-f0c4-4e89-8cc2-3b971c8a98dc">

**Comment by bu4ak** [comment]
Legendary day!

**Comment by yossarian123** [comment]
Tears of joy..

**Comment by mohrazzak** [comment]
IDK why I did new search for this feature and gratefully it is added

**Comment by Rakeshpro9040** [comment]
Awesome :) !!!
