### ISSUE TITLE
Feature request: Pre-populating Collection value when saving a request

### ISSUE THREAD

**Issue by poisa** [a85/POSTMan-Chrome-Extension#3467]
Let's say you are working on an endpoint and save it to a collection. It would be a great time saver if the next time you try to save an endpoint into a collection, the collection would be pre-selected. 
When you have a few dozen collections, scrolling or even searching the collections slows down the process quite a bit.

**Comment by SamvelRaja** [comment]
Thanks for bringing this to our notice, we shall analyze and provide a better solution without breaking current use case.

**Comment by a85** [comment]
This is available in the latest versions of Postman.
