### ISSUE TITLE
Does not respect hosts file

### ISSUE THREAD

**Issue by okonomiyaki3000** [a85/POSTMan-Chrome-Extension#3468]
## App Details:

```
Postman for Windows
Version 5.2.0
win32 6.1.7601 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there: Always (since become standalone app)
 2. Expected behaviour: Hosts in the hosts file should resolve to the proper ip address
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 4. Screenshots (if applicable)

Try this. Send a request to a hostname listed in the hosts file. See? It doesn't go to the correct address. Probably gets 'unresolved hostname' or something like that. 

Please fix this soon. I have to use Insomnia until then.

**Comment by sdnts** [comment]
Hi @okonomiyaki3000 thanks for reporting this! We're tracking this in #2369, so I'm closing this one :)
