### ISSUE TITLE
PostMan doesn't recognize url include ( &

### ISSUE THREAD

**Issue by peter-wangxu** [a85/POSTMan-Chrome-Extension#3469]
## App Details:

```
Postman for Windows
Version  v5.2.0 
Windows 10
```

## Issue Report:

I had  URL links like `http://10.32.253.69:8080/redfish/v1/StorageSystems/Members('4FDB0851-EE73-C655-0D13-A2A7F8A4F7AA')` in http response. I need to navigate to the url by clicking in the response while only `http://10.32.253.69:8080/redfish/v1/StorageSystems/Members(` was recognized as a valid URL.

except behavior:
url contains characters like `)` `(` or `$` should be recognized as part of the URL, so that user can navigate to the correct url via the http response.

**Comment by sdnts** [comment]
@peter-wangxu Thanks for the feature request! We will look into this.
If, however, your server returns a URL encoded version of the URL in the response, it should be picked up correctly.

**Comment by peter-wangxu** [comment]
We are not encoding the url in the http response due to other limitations in our backend.

Can you please escalate this and make it available in a future release?

Thanks
Peter

**Comment by peter-wangxu** [comment]
Any update on this issue?

**Comment by shamasis** [comment]
This seems to be addressed now.
Try making call to `https://httpbin.org/anything/redfish/v1/StorageSystems/Members('4FDB0851-EE73-C655-0D13-A2A7F8A4F7AA')` and on response, click the URL displayed in response viewer. It should correctly open.
