### ISSUE TITLE
[Feature request] Advanced debugging in console

### ISSUE THREAD

**Issue by milancheck** [a85/POSTMan-Chrome-Extension#3473]
I'm sure I'm not the only one who craves for following features:
1. Log specifically just the output into console, that I defined in sandbox (not all requests in Runner)
2. Using colors in cosole
3. Colorize the particular requests as it is displayed in Collection sidebar
4. Ability to turn on and off these features...

EDIT:
5. I believe that console.**log**/**warn**/**info** should make some difference in the end. But, that's not the case unfortunately. http://blog.getpostman.com/2016/08/26/the-postman-console/

**Comment by sdnts** [comment]
Hi @MilanD93! Thanks for the request! We are looking at making improvements in this regard. Do you have anything specific you'd like to be able to see?

**Comment by milancheck** [comment]
@madebysid I accidentaly created the issue before I was actually able to describe it as a whole. Please refer to my edited posting. Thanks

**Comment by ykhodos** [comment]
+1

**Comment by thetreythomas** [comment]
+1 - Would love to be able to add color to the console.

**Comment by ritwijsinha** [comment]
Hello, @MilanD93.

The new Postman Console supports `console.log`, `console.info`, `console.warn`, and `console.error` which are visibly distinguishable. 

Here, check it out!
![image](https://user-images.githubusercontent.com/19693841/68193614-54f77380-ffd9-11e9-8a5c-860c30730ce5.png)

To use this, please update to Postman v7.10!

Cheers 🎉
