### ISSUE TITLE
Properties for Collections

### ISSUE THREAD

**Issue by dgofman** [a85/POSTMan-Chrome-Extension#3474]
Currently Postman supporting only Global and Environment Variables.
I will suggest to add supports TestCase Variable as well.
When I am adding a Folder and under folder creating collections I need specify properties shareable between all collections under the folder (TestSuite)
Another folder may contains the same names but with different values.
Please check SOAPUI/Ready!API. This tool supporting Global/Project (Environment)/ TestSuite / TestCase + TestStep property definitions.

Thanks,
David

**Comment by sdnts** [comment]
This is actually already under planning: #1285
I'm closing this in favour of #1285, we'll let you know when we make progress!
You can also follow our [product roadmap](https://trello.com/b/4N7PnHAz/postman-roadmap-for-developers)
