### ISSUE TITLE
Add the ability to exclude specific requests from documentation

### ISSUE THREAD

**Issue by bunchjesse** [a85/POSTMan-Chrome-Extension#3476]
I use Postman to test a bunch of degenerate cases in my API (validation, etc) and it would be great if I could exclude those requests in my documentation.

Either excluding specific requests or an opt-in for requests I want to publish would be awesome!

**Comment by sdnts** [comment]
@bunchjesse Thanks for the feature request! We will look into this.

**Comment by a85** [comment]
I don't think we will do this feature as part of our current roadmap. We recommend using separate collections right now. We are working on tools to help with similar requests across collections (find and replace, refactor) etc.
