### ISSUE TITLE
Environment template UI/UX problem and suggestion

### ISSUE THREAD

**Issue by elijah-hawk** [a85/POSTMan-Chrome-Extension#3479]
Postman for Mac
Version 5.2.0
OSX 10.12.3 / x64

## Issue Report:
UI/UX issue with Adding shared Environment templates

## Expected behaviour:
* Click Add
* Receive Checkmark UI
* Checkmark UI sustains to notify the user that the template has been added immediately and upon revisiting the template section

## Actual behaviour:
* Click Add
* Receive Checkmark UI
* Add button re-appears

## Suggestion based off interaction with support:
Considering templates are snapshots and would need to be periodically updated when collaborating, I believe it would be good to sustain the Checkmark UI but add a Refresh button so that the template can be refreshed/updated

**Comment by sdnts** [comment]
Hi @elijah-hawk, If I understand correctly, you're referring to this UI, correct?
![screenshot 2017-09-04 17 40 05](https://user-images.githubusercontent.com/7689783/30025866-1a0ad00c-9198-11e7-85b2-9999c0398908.png)

This additional step is for you to make sure that no sensitive values are shared with your team. Environments often contain credentials that you would not want to share.

However, I understand where this is coming from. Currently, environment templates are not synced in real time. When this happens, this step can be removed for sure :)

**Comment by elijah-hawk** [comment]
Actually, this:

![sharedenvtemplates](https://user-images.githubusercontent.com/20306765/30069241-119c07ce-9215-11e7-9118-4d4da50beeb2.png)

If you click on "Add" you'll see what I mean based off my suggestions when I opened this up.

**Comment by a85** [comment]
Environment templates are now transitioned off to environments through our new feature called Workspaces. More info here: https://www.getpostman.com/docs/postman/workspaces/intro_to_workspaces
