### ISSUE TITLE
Feature Request: JSON pretty pretting & wrapping also for input (not just output)

### ISSUE THREAD

**Issue by vorburger** [a85/POSTMan-Chrome-Extension#348]
You seem to offer JSON pretty pretting & wrapping for the response (Body / Pretty / JSON) below.

It would be very useful when typing up the input (raw / JSON) on top about to be sent as well!

As far as I'm concerned this could be always on & automatic (continuously, or on Send or Save). If other users don't like it always on, you could have an explicit action / icon for it.

**Comment by catalinux** [comment]
Yes, but still does not beautifies  the request

**Comment by tch3141** [comment]
For my purposes just being able to get rid of the horizontal scroll bar in the input and having plain ugly wrapping would be an improvement.

I don't exactly care if it's pretty, but it seems impossible to take screen shots and see complete requests with long lines in them right now, even if they should fit. I'm doing this for educational purposes, and have to manually go chunk up the long lines.

**Comment by trollfred** [comment]
+1 would be useful

**Comment by abhijitkane** [comment]
@catalinux @kittee Cmd/Ctrl+B should beautify the request body json if the type is set to JSON

**Comment by trollfred** [comment]
@abhijitkane thank you, it helps a lot!

**Comment by a85** [comment]
@abhijitkane Is this documented in the shortcuts screen inside Settings?

**Comment by seangarner** [comment]
Doesn't seem to work on the new linux beta desktop app (4.8.3).

**Comment by sdnts** [comment]
@seangarner I'm unable to reproduce this on 4.8.3. 
To be sure, you're using Cmd+B in the raw body view right? And is the raw body type set to JSON? Do note that beautification will only work if the JSON is valid.

**Comment by seangarner** [comment]
@madebysid I can't reproduce now either.  I'm pretty sure the json was valid because I would have been sending it to an api that'd parse it.

**Comment by sdnts** [comment]
@seangarner Ah, possible. In any case, it wasn't documented earlier, I've done it now. It should appear in the shortcuts list inside the app in the next release :)

**Comment by rickythefox** [comment]
@madebysid Shortcut is still not listed under Settings / Shortcuts it seems.

**Comment by mikodigital** [comment]
thanks cool stuff

**Comment by timmyz** [comment]
@abhijitkane great secret weapon!!!

**Comment by simplenetworks** [comment]
Does not work in  6.2.5 - osx.

Worked in previous versions

**Comment by mangatinanda** [comment]
Pretty useful feature, Not working in Version 6.4.2. Please fix.

**Comment by numaanashraf** [comment]
@mangatinanda This should be addressed in 6.4.4. Do update and let us know.
