### ISSUE TITLE
setNextRequest isn't working inside a for loop.

### ISSUE THREAD

**Issue by swateek** [a85/POSTMan-Chrome-Extension#3481]
I fetch a certain set of data from the collection, and store the unique ids in a global variable. 

I need to loop over the ids and execute another request. That is not working.

Request 1 - Test Script contains

```
for(var i=0; i<allData.length; i++){
    postman.setEnvironmentVariable('action_item', allData[i]['_id']);
    postman.setNextRequest('Remove From DB');
}
```

Request 2 - Remove From DB is a simple delete request.

Is there anything I am missing?

## App Details:

```
Postman for Mac
Version 5.2.0
OS X 16.4.0 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:
 2. Expected behaviour:
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 4. Screenshots (if applicable)

**Comment by swateek** [comment]
Ah, I should have done the loop logic in the second request too. Sorry.

**Comment by sdnts** [comment]
@swateek Hey! Looking at your code, it looks like you're trying to call the `Remove from DB` call for every item individually, right? `setNextRequest` will only make sure the request you set runs after the current one has finished. This does not behave like functions in programming languages, as in, the control will not return to the for loop

There are two ways to do this correctly:
1a. GET all your data, and store the count in an Environment variable. If `count > 0`, setNextRequest to `Remove from DB`.
1b. In the test section of `Remove from DB`, get the environment variable, decrement. If it is still > 0, setNextRequest to itself, else setNextRequest to `null`. This will make sure there are no infinite loops.

2. Use `pm.sendRequest` in the test script in a loop.

If I misunderstood, ignore this :)

**Comment by swateek** [comment]
Thanks for this @madebysid I am stuck in yet another problem.

**Pre-Request Script**

```
var allData = postman.getEnvironmentVariable("allData");
allData = allData.split(",");

if(allData.length > 1){
    var action_itm = allData[0];
    postman.setEnvironmentVariable('action_itm', action_itm);
    var index = allData.indexOf(action_itm);
    allData = allData.splice(index, 1); // remove first element
    pm.environment.set('allData', allData.toString());   
}else{
   pm.environment.unset("allData");
   pm.environment.unset("action_itm");
   postman.setNextRequest(null);
}
```

**Test**

pm.setNextRequest("Remove from DB");

Well, the splice() which should remove only the first element here isn't working correct. It's removing the next element instead. This is quite strange, but I don't know how else to debug apart from console.
