### ISSUE TITLE
Collection Runner window doesn't show up

### ISSUE THREAD

**Issue by edouardpagnier** [a85/POSTMan-Chrome-Extension#3483]
## App Details:
```
Postman for Windows
Version 5.2.0
win32 6.1.7601 / x64
```

## Issue Report:
 1. I have this problem for a month.
 2. Expected behaviour: The Collection Runner window should show up when click on Run
 3. Actual behaviour: The Collection Runner window doesn't show up even if it appear in taskbar
![2017-09-04 17_36_56-postman](https://user-images.githubusercontent.com/1946370/30032932-9be85b3a-9198-11e7-87b9-74ec6898912c.png)
![2017-09-04 17_40_53-](https://user-images.githubusercontent.com/1946370/30032933-9beb8544-9198-11e7-8089-9a6328f30260.png)

Steps:
1. Open Postman for Windows app
2. Click on Runner at top left (or Run for a specific collection)

Uninstall / reinstall did not solve the problem.

**Comment by sdnts** [comment]
@edouardpagnier Have you tried out the temporary solution I mentioned [here](https://github.com/postmanlabs/postman-app-support/issues/2833#issuecomment-324857159)? I'm closing this in favour of #2833, please let me know if that does not work for you, I'll reopen this.

**Comment by edouardpagnier** [comment]
@madebysid, yes that worked, thanks a lot !
Sorry for the duplicate issue...
