### ISSUE TITLE
Duplicating a folder does not copy the request Body

### ISSUE THREAD

**Issue by poisa** [a85/POSTMan-Chrome-Extension#3484]
## App Details:
```
Postman for Mac
Version 5.2.0
OS X 16.7.0 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:
Recently.

 2. Expected behaviour:
When clicking the three horizontal dots icon next to a folder and choosing "Duplicate", the newly duplicated requests have an empty body. I expect them to contain the same body as the original requests.

**Comment by sdnts** [comment]
@poisa We've seen this happen with raw bodies. These are present, but do not show up. Restarting the app should fix this. Regardless, this is a bug that we'll fix in an upcoming version. Thanks for reporting!

**Comment by cyeagerkarmak** [comment]
If it is any help, it seems like the missing Body is only an issue when duplicating a folder. If I duplicate an individual test, or if I duplicate an entire collection, the Body is not lost.

**Comment by cyeagerkarmak** [comment]
Moving a folder also causes the Body of tests within the folder to be lost.

**Comment by SamvelRaja** [comment]
@poisa  @cyeagerkarmak We released the fix with our canary build 5.3.0-canary01, kindly confirm the fix from your end.

Just download and install the app according to your os.
NOTE: Backup the data in current app using Settings -> Data -> Export for *additional security*.

https://dl.pstmn.io/download/channel/canary/osx_64
https://dl.pstmn.io/download/channel/canary/windows_32
https://dl.pstmn.io/download/channel/canary/windows_64
https://dl.pstmn.io/download/channel/canary/linux_32
https://dl.pstmn.io/download/channel/canary/linux_64

**Comment by poisa** [comment]
I can confirm that this is solved in the linked canary release.

**Comment by anglisc** [comment]
**Also Confirmed Fixed:**

**Issue** : _Duplicating a folder does not copy the request Body #3484_
**Verified on Version :** _v5.3.0-canary01_
**Issue Description :** _When duplicating folders, raw request body data of the requests within that folder is not being duplicated. Leaving the request body empty in the duplicated request in the duplicated folder._

**Comment by abhijitkane** [comment]
Thanks @poisa @anglisc

**Comment by miralpopat** [comment]
thanks it works

**Comment by ValeSauer** [comment]
Thanks for fixing this. Canary works fine.

**Comment by SamvelRaja** [comment]
All, we patched up the fix in 5.2.1 version of the app. Kindly update and confirm from your end 😄
