### ISSUE TITLE
Feature request - Automated "Send and Download" Function

### ISSUE THREAD

**Issue by Pawana93** [a85/POSTMan-Chrome-Extension#3489]
In the last few weeks I had to make an endurance test for a photo application and there I run an issue. I wrote the tests to be automated, but to watch the taken photos (to see if the anonymisation worked) I always had to press "Send and Download" manually. 

So: If I have to run ... let's say 100 tests, it is very time consuming to make every photo by clicking the requests manualy. So I wanted to ask: Could you please make it possible to run collections in the runner and then save it to the hard drive? Like the "Save and Download" Button?

That would be pretty nice and helpful.

**Comment by sdnts** [comment]
@Pawana93 Thanks for the request! We'll look into this :)

**Comment by RobPostman** [comment]
We have another request for this from another user.

**Comment by prashantagarwal** [comment]
@RobPostman @Pawana93  I can suggest you a workaround. You can create a local node server and expose a POST endpoint from that. Then you can start sending your API response to this POST request and on the server side just write this received response to a file. This is a blog post which will help you in doing that. Also we recently included pm.sendRequest which will help you in sending a request from postman scripts.

**Comment by kavithasub** [comment]
Hi, Seems that both issues #3594 and #3489 pointing each other, but no solution updated for the requirement. 
For my scenario, it is need to download an attachment from the response using newman run, just like 'Send and Download' in postman.
**Do you guys have any update on this requirement apart from above workaround? may be in latest release?**

**Comment by davadora** [comment]
FWIW, my organization would be interested in this feature being added as well.  Adding the workaround isn't really feasible for us given our testing infrastructure.  A very attractive integration to a cutting edge visual validation tool would be the outcome of our testing efforts if this feature could be added.
D.Harrison
Cardconnect

**Comment by bharatramawat28** [comment]
Is there any way to automate or setting send and download permanent for some requests for chaining?

How is send and download working or is there any other way to do send and download automatically?

**Comment by jiuli** [comment]
how to use java Implementation sendAndDownload function?
