### ISSUE TITLE
When closing tabs I am being offered to save or not to dave but I don't know which tab it is offering me to save

### ISSUE THREAD

**Issue by gregarrayent** [a85/POSTMan-Chrome-Extension#3490]
## App Details:

```
Postman for Windows
Version 5.2.0
win32 10.0.15063 / x64

```

## Issue Report:
 1. Issue has always been there
 2. Expected behavior:
If the UI could show me at least the name of the tab (API) that I am closing and being offered to help it would be great
An option to "skip" i.e. not close the tab and not save it either (for further inspection) could be also very useful
An option to close all tabs that are saved/not modified should also be considered
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 4. Screenshots (if applicable)

1. Work with many tabs
2. Modify some of the tabs
3. Select "close all tabs" or "close other"

**Comment by sdnts** [comment]
Hi @gregarrayent, I'm assuming you're running into this when closing multiple tabs, right? We've been looking into tab management, will take this into account :)

**Comment by sujayvenaik** [comment]
Hey @gregarrayent 
We had an internal discussion on this issue and have thought of adding the TabTitle on the Modal to give more context.

This will be available in our next release.
Will update this thread once this goes out to canary and production app.
