### ISSUE TITLE
Enhancement request: As a postman end user I want to copy a request from collection to collection in an easy, intuitive manner

### ISSUE THREAD

**Issue by gregarrayent** [a85/POSTMan-Chrome-Extension#3491]
## App Details:

```
Postman for Windows
Version 5.2.0
win32 10.0.15063 / x64

```

## Issue Report:
 1. Problem has always been there
 2. I can select a request in Collection A and "copy" it and then go to Collection B and "paste it" into collection B
 3. Currently I can only "duplicate" a request which creates the request with an appended "copy" name inside the same Collection. I then need to drag and drop it to Collection B (very inconvenient when working with filtered requests) and then rename it to remove the dumb "copy" at the end of the name

**Comment by sdnts** [comment]
Hi @gregarrayent, you should be able to copy & paste a request using the keyboard shortcuts `Cmd+C` & `Cmd+V`. Please reopen if I misunderstood :)

**Comment by gregarrayent** [comment]
@madebysid -- you are correct -- it has either been added recently or I'm a moron -- you chose :-)

**Comment by sdnts** [comment]
@gregarrayent Haha it was added recently, and it isn't really documented anywhere yet, so it's definitely not your fault :D
