### ISSUE TITLE
Support multiple randomInt per request

### ISSUE THREAD

**Issue by arnaldop** [a85/POSTMan-Chrome-Extension#3495]
Currently, multiple {{$randomInt}} variables result in the same integer being used multiple times.

Please add support for multiple random integers to be added to the same request.

Also helpful, add support for random integers to be referenced later, such as {{$randomInt:0}} would refer to the 1st random integer used in this request. This can be useful for places where the data needs to be random, but needs to have a certain amount of internal data integrity.

**Comment by sdnts** [comment]
@arnaldop Thanks for the feature request! I can definitely see value in this. We will look into this.

**Comment by shamasis** [comment]
This is exactly how this works now! See attached screenshot. What am I missing?
<img width="850" alt="Screenshot 2019-06-21 at 15 47 43" src="https://user-images.githubusercontent.com/232373/59916192-2028bc80-943c-11e9-9345-cbafac191cfd.png">

Well, it could be that we fixed this (intentionally or as a side effect of fixing some other issue) and forgot to update this issue?

**Comment by shamasis** [comment]
Regarding: 

> Also helpful, add support for random integers to be referenced later, such as {{$randomInt:0}} would refer to the 1st random integer used in this request. This can be useful for places where the data needs to be random, but needs to have a certain amount of internal data integrity.

The best way to do that is using variables and scripts. Use `{{$myRandomNumber}}` in request and set its value with collection scripts and a lot of other stuff we added in the last few years. Closing. :-)
