### ISSUE TITLE
Code generation for cURL omits parameters for imported requests

### ISSUE THREAD

**Issue by Dil-nlaycock** [a85/POSTMan-Chrome-Extension#3496]
## App Details:

```
Postman for Windows
Version 5.2.0
win32 10.0.10586 / ia32
```

## Issue Report:
This issue seems similar to previously fixed bug 2883
If I craft a request within Postman, then generating a cURL command from that request seems to work fine. However, if I export the collections and then import it into postman on another machine, then the generated cURL is missing some or all of the parameters.
These parameters are present when I select HTTP for code generation.
e.g HTTP looks like this:-

```
POST /connect/token HTTP/1.1
Host: myserver.mydomain.com
Content-Type: application/x-www-form-urlencoded

client_id=myclientid&client_secret=myclientsecret&grant_type=mygranttype&token=mytoken&scope=myscope
```
compared to cURL which looks like this:-

```
curl -X POST \
  http://myserver.mydomain.com/connect/token \
  -H 'content-type: application/x-www-form-urlencoded'
```

It has dropped all of the parameters in this case. Sometimes just one of the parameters will be present, but the rest are lost.

 1. Did you encounter this recently, or has this bug always been there: encountered the issue in 4.11 (the first version I used) and issue remains after upgrading to 5.2
 2. Expected behaviour: all parameters should appear in the generated cURL command
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 4. Screenshots (if applicable)

**Comment by abhijitkane** [comment]
@harryi3t Can we get more clarity on where exactly the bug is? Is there a difference in the request object when the collection is exported+imported? Or is the curl codegen giving a different result for the same request object in two different apps?

**Comment by abhijitkane** [comment]
@Dil-nlaycock I'm not able to reproduce this on the latest version of the app. Apologies for the inordinate delay here, but could you check if you're still seeing this?

**Comment by harryi3t** [comment]
@Dil-nlaycock If you are still seeing this on the latest version of Postman (7.0.6), could you share a sample exported collection where this issue is reproducible?
