### ISSUE TITLE
Although I am logged in I cannot sync

### ISSUE THREAD

**Issue by Bella1977** [a85/POSTMan-Chrome-Extension#3497]
Postman for Windows
Version 5.2.0
win32 6.1.7601 /x64

## Issue Report:
 1. Since this morning I can login but I cannot sync. It does not connect and re-tries after a certain time or stays Offline. Sync is not deactivated. 
2. Collection is accessible via the postman online, but cannot be synched.

**Comment by sdnts** [comment]
Hi @Bella1977, we had to undertake some unscheduled maintenance on our servers, which is why you're seeing this. You can rest assured though, all work that you do will be automatically synced when our servers come back online (which should be a couple of hours).

You can track status [here](https://status.getpostman.com)

**Comment by Bella1977** [comment]
Thank you...I really hope it is coming back soon..The link does not work for me (Unable to connect) As I did log out yesterday and now I do not have access to my collection. Is there another way of accessing. I noticed that not all my collections have an individual link. So I assume this is something I have to invoke in postman before. I am looking at https://app.getpostman.com/dashboard/collections/private
Thank you.

**Comment by jamieps** [comment]
It's http://status.getpostman.com - it's not being served over HTTPS.

**Comment by sdnts** [comment]
@Bella1977 @jamieps Can you guys try now? Sync is up now

**Comment by jamieps** [comment]
@madebysid Thanks, it was slow to initially sync but it is working now.

**Comment by ralfieri** [comment]
I just lost hours of work closing Postman not realizing it was still syncing after 10 minutes. I'm NOT a happy camper. Why wouldn't my local store be protected?

**Comment by KatjaLeu** [comment]
I have pretty much the same problem here - i.e. our whole team cannot connect with postman 5.4.1, it just loops as soon as we click on "Connect/Synch" - what is the problem??

**Comment by numaanashraf** [comment]
@KatjaLeu That's odd. Could you drop us a mail at `help@getpostman.com`? We'll help you get this sorted.

**Comment by KatjaLeu** [comment]
Hello

The problem was configurative – I had to change some proxy configs, it works now

Have a nice day
