### ISSUE TITLE
Problem with Chai assertions

### ISSUE THREAD

**Issue by krogold** [a85/POSTMan-Chrome-Extension#3500]
## App Details:
Postman for Windows
Version 5.2.0
win32 10.0.15063 / x64

## Issue Report:
 1. Seen today, sytematic
 2. I expect having my assertion result in the Tests tab, PASS or FAIL
 3. No relevant console log
 4. No relevant screenshot

Description:

Hi, I encounter a weird problem with postman test function
I used to do tests like this: 
`    tests["Status code is 200"] = responseCode.code === 200;`
I needed to customize a bit so I upgraded it like this:
```
    test_name = "[ "+ request.name + " ] - ";
    tests[test_name + "Status code is 200"] = responseCode.code === 200;
```

This worked fine.

I discovered recently that embedded snippet "Status code: Code is 200" would show like this:
```
    pm.test("Status code is 200", function () {
        pm.response.to.have.status(200);
    });
```

Which is very nice, especially as some users have no developping background, so I tried it and decided to use it for my tests.

Then I went back to my original problem that required customization, so I did
```
    pm.test(test_name + "Status code is 200", function () {
        pm.response.to.have.status(200);
    });
```

**This does not work, but it raises no error: the test just does not appear at all in the Tests tab !**
previousely I had Tests (3/3) with 3 tests with PASS, now I have Tests (2/2) (At least I would expect Tests (2/3) with one failed test or an error)    

It could be my syntax, so I tried differently:
```
    test_assert = test_name + "Status code is 200" 
    
    pm.test(test_assert, function () {
        pm.response.to.have.status(200);
    });
```
This doesn't work either.

to make sure nothing's wrong with my syntax I tried :
```
    pm.test("[ Get all configuration - nominal ] - Status code is 200", function () {
        pm.response.to.have.status(200);
    }); 
```  
**Which fails. Is there a number of characters limitation ???** 
For checking purpose I tried 
`pm.test("[ Get all configuration - nominal ] - abcdefghijklmnopqrstuvwxyz0123456789", function () {`

**Which works** => it is not a number of characters limitation, so I tried setting my own string, character by character.
It works up to 
```
    pm.test("[ Get all configuration - nominal ] - Status code is 20", function () {
        pm.response.to.have.status(200);
    });
```
I end up with Tests (3/3)
    
**If I add the last "0" it doesn't work any longer ????? Tests (2/2)**

I even tried :
```
pm.test("[ Get all configuration - nominal ] - Status code is 20 that's all", function () {
    pm.response.to.have.status(200);
});
```

**And it WORKS  :(**
The Tests tab indicates Tests (3/3) and I have my indication: 
PASS [ Get all configuration - nominal ] - Status code is 20 that's all

Am I entreing the Twilight Zone, somehow ?
    
I really would like to understand, if someone can help ...

**Comment by krogold** [comment]
I tried some more tests:
- to check if the problem is to end with a digit:
```
pm.test("[ Get all configuration - nominal ] - Status code is 20 that's all0", function () {
    pm.response.to.have.status(200);
});
```
=> it works
- to check if it is linked to the position of code 200 (I removed the final "l" of "nominal"):
```
pm.test("[ Get all configuration - nomina ] - Status code is 200", function () {
    pm.response.to.have.status(200);
});
```
=> it fails
- from this observation I tried inserting one or more blank spaces before "200":
```
pm.test("[ Get all configuration - nominal ] - Status code is   200", function () {
    pm.response.to.have.status(200);
});
```
=> it works
**whatever the number of preceding spaces** before "200", the display in Tests tab is the following:
PASS [ Get all configuration - nominal ] - Status code is 200
**with just one space between** "is" and "200"

I think I found the very one (and tricky) bug of the Tests tab. 
**It's a real and annoying issue as, in a production cycle, it may be unnoticed**

**Comment by sdnts** [comment]
@krogold Thanks for the detailed report! This is definitely weird, I'll investigate and get back to you!

**Comment by codenirvana** [comment]
@krogold I am not able to reproduce this issue, can you check if this issue still persists with the latest Postman App.

**Comment by codenirvana** [comment]
@krogold Works fine on Postman App v6.6.1.

<img width="876" alt="problem with chai assertions - 3500" src="https://user-images.githubusercontent.com/4865836/50447703-1158c580-0943-11e9-99c8-116917669241.png">

Feel free to reopen if you're still facing this issue.
