### ISSUE TITLE
Collection changelog isn't helpful for tracking new examples

### ISSUE THREAD

**Issue by vibin** [a85/POSTMan-Chrome-Extension#3502]
Hi, is there way to easily track the most recently added/updated examples for requests in a collection? 

In the activity feed, I see "User created a response {response_name} added in the {collection_name} collection.", but it's super unhelpful as it doesn't tell which request the response belongs to.

**Comment by SamvelRaja** [comment]
@vibinr  thanks for bringing this to our notice, we shall keep you posted on the progress.

**Comment by poisa** [comment]
Let me add to this that having a diff with what the API had before and what it has now would be absolutely wonderful.

**Comment by rchupick** [comment]
echoing Poisa above -- it seems the documentation under 'breaking the event down' shows diffs but i'm not seeing how to access them: https://www.getpostman.com/docs/v6/postman/team_library/activity_feed_and_restoring_collections

@SamvelRaja  is this still available?

**Comment by poisa** [comment]
@rchupick I can't talk about the current version but I think with the previous one, the diff could only be seen online (if you logged in to the actual Postman webpage) and Postman (the app) only showed the brief change set.

**Comment by vkaegis** [comment]
Thanks for all the feedback around this guys! 

@rchupick @poisa Yes, the diffs are available in the Postman app. That said only changes to the request definition (headers, url etc) are tracked right now. We're working on expanding this, and improving the idea and representation of revisions / changelogs, so stay tuned for more updates around this.

**Comment by kartikjain26** [comment]
@vibin could you verify if this is still the case ? We have revamped our Collection Changelog UI and you should be able to see saved example responses in the Changelog
