### ISSUE TITLE
Could not get any response

### ISSUE THREAD

**Issue by namrata18s** [a85/POSTMan-Chrome-Extension#3503]
I am getting this following error on postman ,My server is also running

Could not get any response
There was an error connecting to https://localhost:3000/product.
Why this might have happened:
The server couldn't send a response:
Ensure that the backend is working properly
Self-signed SSL certificates are being blocked:
Fix this by turning off 'SSL certificate verification' in Settings > General
Client certificates are required for this server:
Fix this by adding client certificates in Settings > Certificates
Proxy configured incorrectly
Ensure that proxy is configured correctly in Settings > Proxy
Request timeout:
Change request timeout in Settings > General

Previously  all requsts were running properly PUT,GET,POST,but now its not going correctly

## App Details:

```
Postman for Mac
Version 4.11.0
OS X 16.4.0 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:
 2. Expected behaviour:
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 4. Screenshots (if applicable)

**Comment by vaibhav-plackal** [comment]
Same Problem here. Exact same. Except that my version is:

**Version 5.2.0 (5.2.0) on macOS 10.12.6**

It does not wait for me to debug the application. Why is it that with every release, something which was previously working gets screwed up. How ironic, that the company which allows others test their products doesn't test theirs? 😕

**Comment by SamvelRaja** [comment]
@namrata18s  @vaibhav-plackal  can you guys kindly provide further details on the issue?

Can you guys check what was the response in Postman console?

Open Postman console by View  -> Show Postman Console before sending the request and check the result after sending it.

and send us the screenshot of it? this would help us in debugging much faster and resolve the issue.

**Comment by Thrilok3** [comment]
i got the same issue
(https://user-images.githubusercontent.com/32164325/30693224-3b1eadf2-9eec-11e7-93fb-2e50d8940a6b.png)  that is the referenced screen shot,please give me the solution

**Comment by prashantagarwal** [comment]
@Thrilok3 Can you provide me some details. 
 - What request you are trying to hit (GET, POST etc).
 - Is it to a local server or any other service.

**Comment by Thrilok3** [comment]
post method, it is in server machine

**Comment by prashantagarwal** [comment]
@namrata18s @vaibhav-plackal @Thrilok3 Can you guys also do one favour. The request for which you are not getting any response, can you generate a curl code using Postman code snippet generator and try sending this request from terminal. Let me know if you see any error.

**Comment by Thrilok3** [comment]
(https://user-images.githubusercontent.com/32164325/30694202-a1aeead8-9ef0-11e7-85bf-d5c1fab842dc.png)   in local host is working fine that is the error i got

**Comment by prashantagarwal** [comment]
@Thrilok3 ok did you tried it with curl also ? You can generate by using Code generator on the right side.

**Comment by Thrilok3** [comment]
i tried in my site and postman only not tried in curl.

**Comment by prashantagarwal** [comment]
Ok Thrilok I am guessing this might not be related to Postman. So I am guessing when you are sending this post request some error is happening on the server, which is not handled by the server. As a result of which the server is not returning any response. Also in the first screenshot that you posted I can see error ECONNRESET which is generally caused by the same issue. If you could try sending out this request with curl we can confirm this behaviour.

**Comment by Thrilok3** [comment]
on that request we request the google analytics api also,please give me the
solution for that.

thanks,
Thrilok.

**Comment by prashantagarwal** [comment]
@Thrilok3 I am sorry but I will not be able to help if the issue is not in Postman.

**Comment by PyExplorer** [comment]
Hi, I've encountered the same situation for native app and the reason was in the external proxy (Settings-> Proxy->Global Proxy Configuration  had been turned on)

**Comment by HakamFostok** [comment]
In my case just make a get request which you are sure that it will succeed, (for example request http://www.google.com)
and then try again, it could solve the problem

**Comment by tim-view** [comment]
I had this issue when there was a trailing white space on a header value. The postman console showed me the error and removing that solved my issue.

**Comment by DipendraPoudel** [comment]
I had the same issue. The error was I set the the request timeout to some other values and later i brought it to 0  it worked for me.Thanks

**Comment by tayclark** [comment]
@DipendraPoudel - Have been trying to solve this for months. Thank you!

**Comment by alihamidreza** [comment]
Could not get any response
There was an error connecting to http://localhost:8000/api/v1/courses/s.
Why this might have happened:
The server couldn't send a response:
Ensure that the backend is working properly
Self-signed SSL certificates are being blocked:
Fix this by turning off 'SSL certificate verification' in Settings > General
Proxy configured incorrectly
Ensure that proxy is configured correctly in Settings > Proxy
Request timeout:
Change request timeout in Settings > General

**Comment by numaanashraf** [comment]
@alihamidreza Could you open Postman Console (View -> Show Postman Console), resend the request and check if there are any errors shown there?

**Comment by williamnsambu** [comment]
I am getting the same error below is my Postman Console screenshot. Any help?
![postmanerror](https://user-images.githubusercontent.com/17203487/42830582-75c9a208-89b1-11e8-9754-c5bd8db34879.png)

**Comment by williamnsambu** [comment]
I used http as opposed to https and now I get a different error.
![image](https://user-images.githubusercontent.com/17203487/42830838-3a942a4a-89b2-11e8-9ddd-ef74498fed11.png)

**Comment by williamnsambu** [comment]
I solved both error by setting the SSL certificate verification to "OFF." You do that by Clicking on File>Settings.
![image](https://user-images.githubusercontent.com/17203487/42831075-f95bdfc2-89b2-11e8-9b06-afb1f51fd57d.png)

**Comment by manoadamro** [comment]
I have the same problem, just says "Could not get any response" yet both my browser and curl have no problems. Tried the solutions above, but they did not help

**Comment by numaanashraf** [comment]
@manoadamro Could you open the Postman Console (View > Show Postman Console), resend the request and let us know if there are any errors there?

**Comment by Gmarn** [comment]
Hi,
I am in a similar case since 2 days, I could not resolved it. I recently download the new version of postman but the error is still there.

Here an error:
![image](https://user-images.githubusercontent.com/20647745/43472602-39485a5e-94c4-11e8-8d94-35852f1c43a9.png)

Here an other one:
![image](https://user-images.githubusercontent.com/20647745/43472700-84d41954-94c4-11e8-8763-9ff6ec0ab0d7.png)

(I tried all solution proposed in this discussion...)

**Comment by carodrigues** [comment]
Hi guys,

I the same issue when i execute "{{endpoint}}/api/sequences/"

Could not get any response
There was an error connecting to %7B%7Bendpoint%7D%7D/api/sequences/.
Why this might have happened:
The server couldn't send a response:
Ensure that the backend is working properly
Self-signed SSL certificates are being blocked:
Fix this by turning off 'SSL certificate verification' in Settings > General
Proxy configured incorrectly
Ensure that proxy is configured correctly in Settings > Proxy
Request timeout:
Change request timeout in Settings > General

But it works if i pust the path "https://localhost:44323/api/sequences"


The "endpoint" is an env variable with "https://localhost:44323".

How can i fix this?

**Comment by numaanashraf** [comment]
There are several unrelated request sending issues being posted on this thread as they all have the same symptom of 'Could not get any response'. This prevents us from tracking these issues individually, suggest possible workarounds and post updates on bug fixes and releases to our stable and canary channels. We are locking this thread to prevent further posts of unrelated issues.

If you get a "Could not get any response" message from Postman native apps while sending your request, open Postman Console (View > Show Postman Console), resend the request and check for any error logs in the console. This should give you some information to troubleshoot the issue by searching for the same error in this issue tracker to find possible workarounds and fixes. If you are still having trouble, please open a new bug report with the screenshot of the error and any steps we can take to quickly replicate the issue.
