### ISSUE TITLE
[Command]+R should resend request

### ISSUE THREAD

**Issue by adeleusiere** [a85/POSTMan-Chrome-Extension#3505]
## App Details:
```
Postman for Mac
Version 5.2.0 (5.2.0)
macOS Sierra 10.12.6 (16G29)
```

## Issue Report:
It would be very natural to have [Command]+R resending request from the active tab.

**Comment by prashantagarwal** [comment]
@adeleusiere Thanks for the suggestion, Actually we already have `Cmd + ENTER` as a shortcut to send the request. I don't think we will have another shortcut for the same action.

**Comment by gkssjovi** [comment]
Also want CMD + R, with CMD + Enter, you must put the hand on mouse twice.
