### ISSUE TITLE
Ctrl+Z (Undo) is very slow

### ISSUE THREAD

**Issue by mazgagan** [a85/POSTMan-Chrome-Extension#3506]
## App Details:
Postman for Chrome
Version 5.2.0
OS X / x86-64
Chrome 60.0.3112.113

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:
       From past month or so
 2. Expected behaviour: No slowness
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 4. Screenshots (if applicable)

**Comment by sdnts** [comment]
@mazgagan Can you elaborate a little? Where are you doing the `Cmd+Z`?

**Comment by tiagomsmagalhaes** [comment]
@madebysid I also found this issue on Windows. For example, when inserting an url. if I wan't to go back, i have to do ctrl+z twice

**Comment by ntonyho** [comment]
Yup
You have to do it twice
Super annoying

**Comment by miralpopat** [comment]
agree its very slow

**Comment by wtchangdm** [comment]
Can confirm on macOS 10.12/10.13, no matter I edit in URL or request body.

**Comment by miralpopat** [comment]
I dont have i tried on Windows only

**Comment by Mardoxx** [comment]
@madebysid Each action require three executions of undo. This is across the whole application. Edit -> Undo shortcut is also broken.

**Comment by mikehenken** [comment]
+1

**Comment by cawoodm** [comment]
+1 Windows 10

**Comment by kalevish** [comment]
Same issue undo is very slow.... but redo doesn't work at all. 
Mac 10.12.6
Postman Mac version 5.3.2 
How to reproduce: 
1. type any character in Postman request URL field.  
2. Undo - Hit cml+d twice to undo the character   (This is annoying but some how managed it)
3. Redo - cmd+shift+z to redo ... nothing :(

**Comment by Faz540** [comment]
Still present in Windows version 5.4.0

**Comment by jkewley** [comment]
Would love to see this fixed as well.

**Comment by mrpronerd** [comment]
On Mac OS 10.13.2 this now takes three undo attempts to get it to undo one step.

**Comment by jobec** [comment]
Even worse: if you edit the URL by typing, every typed character requires pressing `ctrl+z` 3 times to undo a single character.

**Comment by Rhymen** [comment]
+1 Windows 10
Undo in body is working fine, but if you edit the URL, you have to press CTRL+Z mutiple times and its very laggy. The menu-item Edit/Undo doesn't seem to work at all.

**Comment by jimmijohansson1** [comment]
Can confirm this happens on windows 10 on the desktop application. Very annoying bug, would love to see it fixed.

**Comment by kalevish** [comment]
Undo is insanely slow on in address bar "Enter request URL". Takes three ctrl+z to undo it. 
Redo doesn't work at all for address bar. 

But undo/redo does work all other fields like collection name, description, request body. 

Please do something about it. This is very annoying bug.

**Comment by prashantagarwal** [comment]
Hey everyone. We have fixed this internally and soon we will make it available on our canary channel. I will keep you updated when we will make it available in production apps.
Thanks

**Comment by prashantagarwal** [comment]
We have released the fix on our Canary app. Can someone please verify it.

**Comment by prashantagarwal** [comment]
You can download our canary apps from [here](https://www.getpostman.com/canary)

**Comment by ntonyho** [comment]
Just curious, what is the cause of this bug?

**Comment by bdollard** [comment]
I have observed this bug in version 6.0.10 on Linux.
I can confirm that the CanaryBuild fixes this issue. It also appears to fix #3849

**Comment by gcphost** [comment]
Undo takes 2 attempts at ctrl+z for it to work in the URL for me.

Redo works nowhere. 
 
macOS Sierra 10.12.6
Postman 6.0.10

**Comment by prashantagarwal** [comment]
@gcphost We have release the fix on our canary app. It will soon be made available to everyone.

**Comment by prashantagarwal** [comment]
We have release the fix with Postman v6.1.2
