### ISSUE TITLE
variables become url-encoded

### ISSUE THREAD

**Issue by machinshin** [a85/POSTMan-Chrome-Extension#3507]
## App Details:

```
Postman for Mac
Version 5.2.0 (5.2.0)
OSX 10.10.5 (14F2511)
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there: Yes

 2. Expected behavior: {{host}}
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 4. Screenshots (if applicable)
https://www.dropbox.com/s/mqdvrtj6y1zjtfz/Screenshot%202017-09-09%2019.58.51.png?dl=0

handlebar variables become url-encoded, and the only way to fix them in the app or the documentation is to retype the url. 

two examples from the generated documentation

```javascript
var options = {
  "method": "POST",
  "hostname": [
    "{{host%0A}}"
  ],
  "path": [
    "ext",
    "v1",
    "create-user"
  ],
  "headers": {
    "x-my-access-token": "{{api-pass",
    "content-type": "application/json"
  }
};
```

var options = {
  "method": "POST",
  "hostname": [
    "{{host%0A}}"
  ],
  "path": [
    "ext",
    "v1",
    "create-user"
  ],
  "headers": {
    "x-my-access-token": "{{api-pass",
    "content-type": "application/json"
  }
};

**Comment by sdnts** [comment]
Hi @machinshin Can you tell me what steps you followed to make it so? I'm unable to reproduce.

Also worth noting is the fact that you can select an environment in your documentation page to populate variables from that environment.
