### ISSUE TITLE
Data of Body (method POST) has been reset after save example

### ISSUE THREAD

**Issue by giangnd2508** [a85/POSTMan-Chrome-Extension#3508]
## App Details:
Postman for Chrome
Version 5.2.0
win / x86-64
Chrome 60.0.3112.113

## Issue Report:
 1. I found it when I try to update Document (this is the first time I use this feature).
 2. Expected behaviour: 
Just update the information which has changed, not other infor.

Steps to reproduce the problem:
1. Fill the infor: url, data param of body.
2. Add new example: Request example, Response example.
3. Back to API 
---> data param of body has gone.

Please check it, I have to spend too much time to fix this documents.

**Comment by sdnts** [comment]
Hi @giangnd2508 I was able to replicate this on my end. Ideally, this should not happen. We will get this fixed as soon as possible. Thanks for reporting!

**Comment by giangnd2508** [comment]
Thanks and hope that this feature will be fixed on the next release.

**Comment by ZedoAditi** [comment]
Hi siddhant,
My issue is similar to the mentioned above. 
When I try to drag a subfolder from the collection folder to another collection folder, the json from the body section becomes blank from all the requests(POST/PUT).

Please check.
Thanks.

**Comment by ZedoAditi** [comment]
Postman for Windows
Version 5.2.0
win32 10.0.15063 / x64
