### ISSUE TITLE
{{$timestamp}} dynamic variable doesn't work in saved examples

### ISSUE THREAD

**Issue by selch** [a85/POSTMan-Chrome-Extension#3509]
## App Details:

```
Postman for Windows
Version 5.2.0
win32 10.0.10586 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there: Always been there
 2. Expected behavior: The {{$timestamp}} variable would display current timestamp when used in an example
 3. Reproduce: Replace a timestamp in a saved example with {{$timestamp}} dynamic variable. When the example is returned you'll just see "{{$timestamp}}" instead of a real timestamp for today.

**Comment by numaanashraf** [comment]
@selch Thanks for reporting this. We are tracking this issue internally and will let you know of any updates.

**Comment by kamalaknn** [comment]
@selch could you give more context as to when you expect the variables to be resolved? Are you using this example as part of a mock response?

**Comment by PilotConway** [comment]
We are using a mock and we definitely would like the timestamp to be resolved when returning the example from a mock request. Some of our mock responses need to have date/times within a certain range of `now()` and constantly having to go in and set timestamps gets annoying after a while. 

Really we'd like to be able to dynamically have variable resolution for everything in the examples when using the mock server. Then we could do uuid's as well.

**Comment by ratpik** [comment]
@PilotConway @selch - Postman Mock servers now support dynamic variable resolution for `{{$timestamp}}` and several other variables. The entire set of variables are listed in this issue #971
