### ISSUE TITLE
Collection Runner Hangs when starting

### ISSUE THREAD

**Issue by andrewwburns** [a85/POSTMan-Chrome-Extension#3510]
## App Details:
Postman for Windows
Version 5.2.0
win32 10.0.10240 / x64

## Issue Report:
1. After latest update, when loading the Collection Runner, it gets stuck showing electrons orbiting. 
2. Expected behaviour is that it should finish loading and allow collections to be run.

To reproduce:
- Open Postman (this works fine)
- Click Runner
- Collection Runner opens, but then gets stuck showing orbiting electons. The electrons do orbit; it's not completely hung.

**Comment by SamvelRaja** [comment]
@andrewwburns  that's odd, can you provide us the log from the dev tools of runner window.

Once you opened up the runner, focus on the runner windows and click view ->Show dev tools

This would help us in identifying what's going wrong.
