### ISSUE TITLE
User-Agent setting not working when Interceptor is off

### ISSUE THREAD

**Issue by xin-zhang** [a85/POSTMan-Chrome-Extension#3512]
## App Details:

```
Postman for Chrome
Version 5.2.0
win / x86-64
Chrome 60.0.3112.113
```

## Issue Report:
`User-Agent` header setting doesn't work. Default Chrome User-Agent is used instead.

If turned Interceptor on, the issue goes away.

## Steps to reproduce the problem

1. Set up a request according the following curl command
```
curl -X GET \
  http://example.com/ \
  -H 'user-agent: MyUserAgent'
```

2. Set up chrome proxy to go through 127.0.0.1:8888, and set up Fiddler to monitor traffic

3. Send the request. Fiddler catches the following traffic (**Buggy here: default UserAgent is used**)
```
GET http://example.come/ HTTP/1.1
Host: example.come
Proxy-Connection: keep-alive
Cache-Control: no-cache
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36
Postman-Token: 20c73ad3-c61e-bc61-3488-834ef6821500
Accept: */*
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.8,ja;q=0.6
```

4. Enable Interceptor and send the request again. Fiddler catches the following traffic (**Issue gone: customized UserAgent is used correctly**)
```
GET http://example.come/ HTTP/1.1
Host: example.come
Proxy-Connection: keep-alive
Cache-Control: no-cache
X-Postman-Interceptor-Id: e32d7af4-e254-1cc4-f11c-e71c506022ee
User-Agent: MyUserAgent
Postman-Token: d2968c5c-4220-40ce-06fa-853bb3f9be25
Accept: */*
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.8,ja;q=0.6
```

**Comment by abhijitkane** [comment]
@xin-zhang This is expected behavior. Chrome's XHR API doesn't allow certain headers to be set.

You'll need to enable the Interceptor, or use our native apps (http://getpostman.com/apps).

**Comment by xin-zhang** [comment]
Hmm... You should definitely write it somewhere in a document or an FAQ page, or if you can remind people in Postman when they try to set User-Agent it would be really nice.

I tried [Advanced Rest Client](https://www.google.co.jp/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0ahUKEwiGotCH6Z_WAhUMhbwKHf46DQEQFggoMAA&url=https%3A%2F%2Fchrome.google.com%2Fwebstore%2Fdetail%2Fadvanced-rest-client%2Fhgmloofddffdnphfgcellkdfbfbjeloo&usg=AFQjCNEo489FdO7M0eVz4c9u475vROBbXQ), which doesn't have this weird behavior.

Could you tell me why enabling Interceptor solves this? If a part of Interceptor can solve this problem, why don't you just embed that part of Interceptor into Postman in the first place?

Thanks
