### ISSUE TITLE
Not active header is blocking rest of active headers

### ISSUE THREAD

**Issue by emcence** [a85/POSTMan-Chrome-Extension#3514]
If having more than one header and uncheck one of them, rest headers in the list are not taken in consideration when request is send

**Comment by numaanashraf** [comment]
@emcence Thanks for reporting this. We are not able to replicate this at our end. Could you let us know your app version and a sample request?

**Comment by emcence** [comment]
Version 5.2.0 (5.2.0)
PUT/POST request which has headers Accept, Content-Type, Authorization
(which is inactive, unchecked but exist) another random header which is
also checked as Content-Type.

**Comment by emcence** [comment]
Additional info, even if there is no inactive header, added header is not
taken in consideration.

**Comment by emcence** [comment]
Find out that header was depended from another one, so if both are used
than having expected outcome. Described behavior above is not a postman
issue.

**Comment by prashantagarwal** [comment]
@emcence Is this a bug in Postman app ?

**Comment by emcence** [comment]
No. Not a bug.

On Fri, Sep 22, 2017 at 10:33 AM, Prashant Agrawal <notifications@github.com

**Comment by prashantagarwal** [comment]
Oh cool. Closing this issue.
