### ISSUE TITLE
Runner Test Script problem: ReferenceError | blob is not defined

### ISSUE THREAD

**Issue by mpergament** [a85/POSTMan-Chrome-Extension#3516]
## App Details:

```
Postman for Mac
Version 4.11.0
OS X 16.4.0 / x64
```

![image](https://user-images.githubusercontent.com/13856387/30328505-d423beb2-97cf-11e7-864e-18250dcfd108.png)

After executing it I see following error in Console:
ReferenceError | blob is not defined

Imho the problem is due to the dash in config-blob as same script works just fine on all objects which do not have dash:
var response = JSON.parse(responseBody),
    objuuid = [];

response.config-blob.forEach(function (obj) {
    if (obj.fq_name[2].has("SRX4100")) {
        objuuid.push(obj.uuid);
    }
});

**Comment by mpergament** [comment]
Solved it

**Comment by PetrKnedlik** [comment]
How have you solved it? @mpergament

**Comment by pawelkaliniakit** [comment]
I am using Postman v6.7.3 and I am still having this issue:
"ReferenceError: XYZ is not defined"
:(
