### ISSUE TITLE
Postman doesn't add cookies to localhost domain.

### ISSUE THREAD

**Issue by janzenz** [a85/POSTMan-Chrome-Extension#3518]
Postman for Mac
Version 5.2.0
OS X 10.12.6

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:
     > I'm not sure I just found about it today.
 2. Expected behaviour:
     > Should be able to add cookies on specific domain.
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
     > No error
 4. Screenshots (if applicable)
     
<img width="733" alt="screen shot 2017-09-13 at 10 47 49 am" src="https://user-images.githubusercontent.com/1410147/30351754-0e0dc824-9871-11e7-9209-488082545304.png">

Click Cookies > Add `localhost:8080` > Then try `Add Cookie` it doesn't show the text box to fill in.

**Comment by numaanashraf** [comment]
Hi @janzenz, thanks for reporting this. We were able to replicate this issue at our end and will be working on getting a fix out in the coming releases.

**Comment by sophiekruijt** [comment]
Is there any workaround for this issue? I'm trying to send a request locally and need to add a cookie to the request.

**Comment by sirjoe** [comment]
Same question as @stefankruijt . @numaanashraf could you please advise when the next release is scheduled to be out?

**Comment by brianlovin** [comment]
+1 here, will follow along with this issue to hopefully add cookies to localhost requests :)

**Comment by andreas-bergstrom** [comment]
This does seem to be fixed in the current mac version. I also had this issue previously but using the latest version I can set cookies for localhost, at least if it is a domain (i.e. app.localhost which is then pointed to localhost using the hosts file).

**Comment by dbrezack** [comment]
Can confirm this is occurring on win x64 5.3.2 (current as of today) on windows.

**Comment by adamlc** [comment]
I can confirm this is this still isn't working on macOS v5.4.1 using localhost or 127.0.0.1 with a port.

Edit:
It seems to be any domain with a non standard port doesn't work, e.g. ```google.com:8080``` doesn't work either :(

**Comment by mxdi9i7** [comment]
+1, still not fixed as of today.

**Comment by dannash918** [comment]
For those looking for a workaround I was able to add cookies using just localhost (no port). Thanks to @adamlc for recognising it was a port issue.

![image](https://user-images.githubusercontent.com/20009111/33817272-c6b8dbea-de92-11e7-9412-241ebdbe9dd3.png)

**Comment by smartman** [comment]
Issue is still persisting

**Comment by stamminator** [comment]
157 days later, issue still taking place. Running v5.5.3 on Windows.

**Comment by shabinGravitum** [comment]
Issue still exists in latest Windows version as of today

**Comment by beheist** [comment]
Still exists in Version 6.0.9 (6.0.9) for Mac. Fix greatly appreciated.

**Comment by Parth** [comment]
Still exists in Windows 6.0.10

**Comment by NorkhairiMisdi** [comment]
Still exists on Ubuntu. Looking forward to a fix soon.

**Comment by MaeseppTarvo** [comment]
Still an issue with the 6.0.10 for MacOS

**Comment by shahkunalj** [comment]
The same issue exists with v6.0.10 for Win

**Comment by philicomus** [comment]
Please fix this. Being able to send cookies on localhost development servers is a very common use case for developers!

**Comment by vincentracine** [comment]
Still an issue v6.0.10 MacOS 10.12.6

**Comment by camleng** [comment]
@philicomus Have you tried just using localhost (with no port)? It's working for me as of today.

**Comment by jakesylvestre** [comment]
@camleng when I use localhost the cookies don't save.

**Comment by jakesylvestre** [comment]
Try this: https://github.com/postmanlabs/postman-app-support/issues/1700#issuecomment-181227107 

But for me I get an error connecting (it works when I remove `Cookie: _`) so it's something at the proxy level

**Comment by jakesylvestre** [comment]
Update: adding `Cookie:` works for localhost. Sucks that you can't use the `Cookies` interface, but this is helpful for now.

**Comment by harryi3t** [comment]
As per the RFC http://tools.ietf.org/html/rfc6265, the port number is not considered while persisting/using a cookie
Also, I checked the behaviour with browsers. When I set up a server running on `localhost:3333` and set a cookie, the browser saves it with domain `localhost`. Postman also does the same thing.

Also, from the UI if you just type the `domain` instead of `domain://post` it works and which is expected behaviour.

**Comment by carlYumana** [comment]
+1 on 6.2.3 on Ubuntu Linux 18.04

The thing is when you try to add a Cookie when you don't have any cookie on that domain. When you have almost one you can add whatever you want.

Thanks in advance.

**Comment by seantcanavan** [comment]
I couldn't get cookies to load for 127.0.0.1 but I could get them to load for localhost.

Postman 6.4.3 Ubuntu 18.04.1

**Comment by mshauny** [comment]
This issue is still there on postman v6.5.2 (which is the latest) on windows. omit the port number in localhost, so instead of localhost:5000, you just specify localhost. Which kind of makes sense for postman not to work. Thanks to @adamlc  for recognizing that. 

Thanks to @harryi3t  for clarifying, this is the expected behavior

**Comment by harryi3t** [comment]
@mshauny That is not a workaround, that's how it's is supposed to be used. Please see the [comment](https://github.com/postmanlabs/postman-app-support/issues/3518#issuecomment-401298505) for more details.

**Comment by mshauny** [comment]
@harryi3t  correct, I did recognize that after checking the RFC, hence I said it made sense for postman not work. Apologies, wrong choice of words and thank you for clarifying that.

**Comment by martin-bidroom** [comment]
Still present, even in Postman 6.7.3

**Comment by milesflo** [comment]
~~Issue present in Postman for linux~~

**Comment by seantcanavan** [comment]
@milesflo I am not having this issue on either Linux or Mac. Are you using ports as part of your localhost URL?

**Comment by milesflo** [comment]
@seantcanavan Update: I figured it out.

Turns out it was a non-issue / user error :)

I was confused by how adding a new cookie would default `Cookie_#`, and whenever I added _additional_ data to the key/value string, it would not save...

As it turns out, each Cookie added by the modal should only represent a **single value**. I was under the impression that by clicking [+], what I was doing was adding an entire preset to be sent to the target API.

In actuality, each cookie should be added independently, and `Cookie_#` value should be _replaced_ by what you are wanting to add. (In my case it was a `jwt` cookie)

**Comment by colinmcintyre** [comment]
Still an issue. My API request will set the cookie correctly. However when attempting a request to the API which requires the cookie, it is not being attached

**Comment by seantcanavan** [comment]
@colinmcintyre are you using ports as part of your localhost definition? I don't think this is a bug so much as a usability issue with the UI and setting it up.

**Comment by colinmcintyre** [comment]
Hi. Yes I am using a port in the url (localhost:4600/api/) when requesting, however the cookie is stored only as localhost without any port. I interesting thing is it works sometimes.. 

Please if you know a work around or the correct way of using the app let me know.

**Comment by colinmcintyre** [comment]
Ok. I have found the cause. Postman currently does not support cookies set with Prefix **secure: true**.

[https://learning.getpostman.com/docs/postman/sending_api_requests/cookies/](https://learning.getpostman.com/docs/postman/sending_api_requests/cookies/)
_Bottom of the page_

As soon as I removed that flag when in the api, the cookie is being sent.

**Comment by TheDirigible** [comment]
This issue still exists.  To be clear, this is a UI issue.  When you click "Add Cookie", nothing happens.  This only happens if the user has entered a protocol before the domain name, ie "http://".  Postman should reject that if it's invalid.  It shouldn't present a non-working button.

**Comment by seantcanavan** [comment]
I think there might be an issue with adding a port as well after localhost although I'm not sure why.

**Comment by dz902** [comment]
I agree with @TheDirigible. This is indeed a UX issue anyway. I search and found this issue 3 months ago, and now I have to search it again to remember what I learnt last time. With a proper warning or error this could've been easy.

**Comment by Roemerb** [comment]
Issue is still not fixed. v7.22.1 on Ubuntu.

**Comment by andrei115** [comment]
There is a workaround by using the domain localhost instead of localhost:port provided by @dannash918 which is working fine

**Comment by jBernz** [comment]
This workaround does not work for me. Any value I set for a cookie on localhost is not saved when I click save. This must be a bug.

**Comment by IgPugliese** [comment]
i could replicate the original bug

**Comment by aksswami** [comment]
Issue still there on MAC Version 7.29.0 (7.29.0).

**Comment by ICeZer0** [comment]
It is not working with Interceptor

**Comment by fernandokbs** [comment]
I solved using the domain without http

**Comment by Brenndoerfer** [comment]
Specifying a protocol (https/http) or port prevented me from being able to add cookies.

Simply use `localhost` as the domain (without https or a port)

**Comment by paciorek-lukasz** [comment]
Still not working on Windows

**Comment by apedeveloper** [comment]
Just fix this already

**Comment by Rick-van-Dam** [comment]
Any cookie I add is not saved

**Comment by JosephCanete** [comment]
Problem still persist :/

**Comment by billdotdev** [comment]
I used the intercepter to capture cookies and add domain `localhost` without the port

**Comment by Dmdv** [comment]
The issue still persist on Mac OS BigSur

**Comment by coltonyoung** [comment]
The issue still persists on Windows v9.1.3

**Comment by mortezaadi** [comment]
Same issue on Mac Monterey

**Comment by shakhzodrasulov** [comment]
Same issue on Windows 10, Postman v9.7.1 in the latest version by today

**Comment by lukasbahr** [comment]
Still exists on MacOS 12.1, Postman v9.6.2.

**Comment by DannyDainton** [comment]
Hey folks,

I'm just trying to get more of an understanding here, I have no context about this issue. As it was opened in 2017 against version 5.2.0 - The Postman platform has moved on from that point, with multiple changes in all areas of the product.  

It was closed in 2018 with the following comment:

> As per the RFC http://tools.ietf.org/html/rfc6265, the port number is not considered while persisting/using a cookie
Also, I checked the behaviour with browsers. When I set up a server running on localhost:3333 and set a cookie, the browser saves it with domain localhost. Postman also does the same thing.

> Also, from the UI if you just type the domain instead of domain://post it works and which is expected behaviour.

I can see that several users on the thread have mentioned it still being present in a different version but I haven't seen any updated steps to reproduce the problem using the latest version. 

Could someone create a comment with all these specific details including images or a recording of the behaviour, to allow us to see what is currently happening on your Postman instance? 

@shakhzodrasulov / @lukasbahr / @TheDirigible could you help out here?

**Comment by jde-chil** [comment]
the problem still persists with the port
one workaround is to set the cookies as variables and store them. In the "tests" section of the request setting the cookies.
```
// cookies are set with a 'Set-Cookie' response header, the format is 
// key=cookie-value; param1=value1;param2=value2 ...
// we need to store cookie-value
let cookies = ['csrftoken', 'sessionid'];
for (let h of pm.response.headers.all()) {
    if (h.key === 'Set-Cookie') {
        for (let c of cookies) {
            if (h.value.includes(c)) {
                postman.setEnvironmentVariable(c, h.value.split(';')[0].replace(`${c}=`, ''));
            }
        }
    }
}
```
it will set environnement variables with the name of the cookies
then to set the cookies in a request, go to "headers" and set a header Cookie with value `cookie1={{env_var1}};cookie2={{env_var2}}`
with precedent code key: `Cookie` value: `csrftoken={{csrftoken}};sessionid={{sessionid}}`

<img width="795" alt="Screenshot 2022-02-21 at 16 08 51" src="https://user-images.githubusercontent.com/16058184/154981692-07b2470e-8f12-4632-8d03-29eeaf23d1b8.png">

**Comment by TheDirigible** [comment]
Follow the original steps to reproduce.  This isn't rocket science.

**Comment by jessonyo** [comment]
I'm having the same issue on postman v9.15.2. The workaround I got was using 127.0.0.1 instead of localhost and it sets the cookie correctly according to the set cookie header. The problem is, it still doesn't automatically add Cookie to my requests headers so I still need to use a workaround using environment variables.

**Comment by muldon** [comment]
still not fixed for mac too.. using postman 9.29.3

**Comment by shaunjacobsen** [comment]
This is still not fixed.

**Comment by shubhbhargav** [comment]
Hey everyone, first of all, thanks for highlighting this.

As of now, we are unable to reproduce this issue at our end. Adding a few details from the previous comments at the time we fixed the issue in order to clarify the behaviour under certain scenarios:

- Cookies are set on the domain level. Port number is not considered for that (as per the RFC: https://www.rfc-editor.org/rfc/rfc6265). In essence, when calling an endpoint with a port number (like `localhost:3000/foo`), the cookie will be set on `localhost`.
- Setting the cookie with / without protocol works in Postman Desktop version 9.31.21. Sharing a screen recording (with the protocol case) here: https://www.loom.com/share/cecba744de2742458a70aeba2e28b2c9
- Cookie is sent in the subsequent requests with the same domain (as shown in the above recording). This can be verified either by looking at the auto-generated headers in the headers tab or via console.

In order to help us debug this better, can you please file a new Github ticket detailing the steps taken? We are closing this thread for the future readers to discover this context.
