### ISSUE TITLE
Transfer history to new computer

### ISSUE THREAD

**Issue by garrettd714** [a85/POSTMan-Chrome-Extension#352]
Work got me a new computer. I don't have my (long) history in collections. Is there a way to transfer my history to my new computer?

**Comment by akgupta0304** [comment]
Best way which I used, Create a login on postman and whenever You do login on another computer login with the same account, You will get all the data.

Otherwise, Export the data into Json format from setting->data. And the same json can be used for import.

**Comment by garrettd714** [comment]
@akgupta0304 **5 years ago**, postman didn't have centralized accounts. Export, I don't believe gives you history either but, thanks for digging around the 'net.
