### ISSUE TITLE
Cannot sign in into Postman APP

### ISSUE THREAD

**Issue by krogold** [a85/POSTMan-Chrome-Extension#3520]
Postman for Windows
Version 5.2.0
win32 10.0.15063 / x64

## Issue Report:
 1. systematic from today

 2. Expected behaviour:
Use postman echo for tests
Sign-in in my postman app and recover my current work

 3. no console log - just a "something went wrong message"

4.
I tried to use postman echo services => timeout
I tried to sync => not sync (no message, just still trying)
I tried to sign-out/sign-in => can no longer sign in
I tried to change my password => ok to sign on-line, not in the app
I tried to use postman echo services without signing-in => timeout
I tried looking for updates but it checks continuousely (stuck)

What can I do to get back to my signed-up app ? please help

**Comment by numaanashraf** [comment]
Hi @krogold, could you send us a screenshot of the Console and Network tabs in the apps DevTools? (View > Show DevTools).

**Comment by krogold** [comment]
Yes, here they are

![image](https://user-images.githubusercontent.com/29147722/30367976-142e41f8-9870-11e7-8c63-b2248d23acce.png)

and 

![image](https://user-images.githubusercontent.com/29147722/30367992-1e59f82a-9870-11e7-8ad7-b1daa562c125.png)

tell me if you need further screenshots

thank you

**Comment by krogold** [comment]
sorry, I screwed up the network one, here it is:
![image](https://user-images.githubusercontent.com/29147722/30368087-641e9ac8-9870-11e7-9c8f-c5a6135a2a35.png)

**Comment by krogold** [comment]
Strange ... I can sign in online. I think I'm up to date with the version, there must be something with my network connection ...

**Comment by krogold** [comment]
Can I do a wireshark capture ? which ip should I seek ?

**Comment by krogold** [comment]
Hi, I tried logging on someone else's computer and it worked. His version is 4.10.7 though ...
I guess it may not be linked to postman but more linked to my network connection. 
However, I don't have any problem to access to internet. did you manage to find something out of the printscreens ? 
Would it be worth reinstalling the APP ? 
will I lose my collections  ?

**Comment by krogold** [comment]
I'm definitely not an expert in Windows. Restarting my machine was not enough, I had to restart my ethernet card. Now I can sign-in and use postman-echo for tests (thank you Michel !).
I just hope that syncing will give me back my collections ! 
Thanks for your time.
Alexandre
