### ISSUE TITLE
proxy tab is not displayed in setting and  interceptor is also installed in postman.

### ISSUE THREAD

**Issue by pardeepmillipixels** [a85/POSTMan-Chrome-Extension#3521]
![proxy](https://user-images.githubusercontent.com/31564222/30366814-f9912fd0-9889-11e7-8869-e7678fd94021.png)

## App Details:

```
Postman for Mac
Version 4.11.0
OS X 16.4.0 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:
 2. Expected behaviour:
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 4. Screenshots (if applicable)

**Comment by numaanashraf** [comment]
@pardeepmillipixels Custom Proxy is available only on our Desktop apps and are not currently available in Postman Chrome Apps. You can download the Desktop app for your OS from www.getpostman.com/apps.
