### ISSUE TITLE
Swagger import does not populate hostname correctly when path starts with mixture of string literal and variable e.g. "/v{version}"

### ISSUE THREAD

**Issue by PerthCharern** [a85/POSTMan-Chrome-Extension#3522]
## App Details:
```
Postman for Windows
Version 5.2.0
win32 10.0.15063 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there: Not sure. Most likely has always been there.
 2. Expected behaviour: Hostname should be populated correctly.

## Repro Step:

- Get a swagger v2 file. The pet store should work http://petstore.swagger.io/v2/swagger.json

- Change the first path from `/pet` to `/pet{aaaaa}`. 

- Import into postman.

- Note that the call generated for APIs with path `/pet{aaaaa}` will NOT have the hostname populated.

**Comment by prashantagarwal** [comment]
@PerthCharern Can you clarify what output you are expecting here. Also can you try this by using `/pet{{aaaaa}}` instead of `/pet{aaaaa}`.

**Comment by PerthCharern** [comment]
The Postman host name is not populated correctly:

If the path is simply `/pet`, you will get `http://petstore.swagger.io/v2/pet` in the host name box.

But when the path is `/pet{aaa}`, you will get `pet:aaa`. The expected hostname should be `http://petstore.swagger.io/v2/pet:aaa`.

Using `/pet{{aaa}}` gives this hostname: `pet:/:aaa`, which is still incorrect. Even if this gives out the correct hostname, it's still a bug since Postman should be able to parse the Swagger document without requiring this specific change.

**Comment by PerthCharern** [comment]
Just to clarify why `http://petstore.swagger.io/v2/pet:aaa` is the expected hostname. This is how you guys currently parse path parameter: `/pet/{petId}` gets parsed into `http://petstore.swagger.io/v2/pet/:petId`. (Use the host and base path in the doc, and then append the path, and replace `{variable}` by `:variable`). 

When path is `/pet{aaa}`, the path itself gets translated to `pet:aaa` but is not prefixed with the host and base path for some reason.

Note, however, that when I change the path to `/pet/pet{aaa}`, you guys can parse this properly to `http://petstore.swagger.io/v2/pet/pet:aaa`. 

It looks like the problem is isolated to the case of the path beginning with string literal and variable only. If mixtures of string literal and variable appear elsewhere in the path, those ones are handled fine.

**Comment by Unders0n** [comment]
faced similar problem. Is there any updates for that?

**Comment by abhijitkane** [comment]
@Unders0n @PerthCharern This should be addressed in the latest version of the Postman app.

However, the `{{baseUrl}}/pet:aaaa` is still problematic, because there's no way to provide the value of the `aaaa` variable. If the path variable is part of a URL segment (`/pet{aaa}`), we'll need to translate this as an environment variable instead of a path variable (`/pet{{aaa}}` instead of `/pet:aaa`).

Keeping this issue open for now.

**Comment by DannyDainton** [comment]
Hey @abhijitkane 

Is this comment still valid or are we now in a position to close this issue?

**Comment by chughmayank** [comment]
@PerthCharern  - This issue is resolved now. Try out the latest version of Postman! Feel free to reach out if you face any issues!
Cheers!
