### ISSUE TITLE
Feature Request: Multiple Concurrent Send Requests

### ISSUE THREAD

**Issue by Stephen3443** [a85/POSTMan-Chrome-Extension#3523]
It would be extremely useful if you could select multiple saved requests in the left pane and send them at the same time concurrently. It would mean we could simulate real world situations where we have users accessing features at the same time and causing concurrency issues.

**Comment by numaanashraf** [comment]
@Stephen3443 Thanks for the suggestion. We'll take this into consideration as we plan our roadmap. You can find our current roadmap here - https://trello.com/b/4N7PnHAz/postman-roadmap-for-developers

**Comment by shamasis** [comment]
Just an update ... you can now do this as part of the collection runner. It’s still serial though.

**Comment by malvikach** [comment]
Closing this, as this is being tracked here: https://github.com/postmanlabs/postman-app-support/issues/493

Please feel free to provide further feedback to us on the linked issue. I will keep the issue updated with news on this.
