### ISSUE TITLE
Get New Access Token results in HTTP 404 after login - Auth0

### ISSUE THREAD

**Issue by walterpinson** [a85/POSTMan-Chrome-Extension#3524]
## App Details:
```
Postman for Mac
Version 5.2.0
OS X 10.12.6 (macOS Sierra)
```

## Issue Report:
When attempting to get a new **OAuth 2.0** access token via the *Get New Access Token* button, the process ends in an HTTP 404 error.

 1. Did you encounter this recently, or has this bug always been there:

I've successfully used this feature quite some time ago on a different project.  But most recently, this is the only behavior that I'm seeing on my current project.

 2. Expected behaviour:

My expectation is that after I was prompted for my authentication credentials and then supplied them, that a token would be acquired and I could use it to call the API that I'm trying to test.

 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):

There is absolutely nothing in the Dev Tools on the Console log related to attempts to obtain an access token.

 4. Screenshots (if applicable)

![image](https://user-images.githubusercontent.com/1972521/30412204-d1f8c3b6-98e3-11e7-8752-95efa687afbc.png)

### Steps to Reproduce

1. Choose Authorization tab - underneath request
1. Select OAuth 2.0 from the Type drop-down
1. Click the Get New Access Token button
1. Verify that `https://www.getpostman.com/oauth2/callback` is configured as a valid callback URL at my Authorization Service (Auth0).
1. Complete the Get New Access Token dialogue box
    1. Choose  **Authorization Code** as my Grant Type
    1. Leave "Request access token locally" unselected.
1. Click the Request Token button
1. When presented with Auth0 login screen, complete the sign-in flow

At that point, I am presented with the 404 Screen, above.

**Comment by numaanashraf** [comment]
@walterpinson Thats odd. I just tried the steps you had provided and I was able to get a new token from Auth0. Could you try again and let us know if you are still facing this issue?

**Comment by walterpinson** [comment]
Thanks for such a quick response, @numaanashraf.  The fact that this works for you provides more data to my troubleshooting efforts.  Could you please confirm for me that the 404 screen that I included above is a Postman screen and not an Auth0 screen?

**Comment by walterpinson** [comment]
I repeated the steps with the same result.  Clearly, the configuration for the authorization URL is correct because I am redirected to the Authorization Service and am allowed to login.  The request is either failing at one of the callback URLs or the Access Token URL.  Since the console and dev tools aren't picking up the network traffic for this request, I'm flying blind.

**Comment by numaanashraf** [comment]
@walterpinson Are you still facing this issue with our latest version v6.1.4?

**Comment by numaanashraf** [comment]
@walterpinson We are closing this issue as we are not able to replicate this at our end and the use case seems to work as expected when we follow the steps provided. Feel free to re-open if you are still facing this issue.
