### ISSUE TITLE
Remember Collection between Saves

### ISSUE THREAD

**Issue by cawoodm** [a85/POSTMan-Chrome-Extension#3526]
Every time one saves a request, postman forces you to select a collection.

Even if you "Save As" an existing request from Collection A you have to re-select Collection A (the scrolling selection is actually pretty hard to use - oversensitive to mouse scrolling).

It would be much better if the last collection was remembered. The user can select another one but the last chosen collection is offered by default.

**Comment by prashantagarwal** [comment]
@cawoodm we are already tracking this issue here #3467 . I am closing this as duplicate issue.
