### ISSUE TITLE
Close All Tabs: No to all option

### ISSUE THREAD

**Issue by cawoodm** [a85/POSTMan-Chrome-Extension#3527]
When one selects close all tabs and there are 20+ tabs open you have to say "Don't" save 20 times. Should be a "No to all" option.

![ss](https://user-images.githubusercontent.com/498834/30427302-91b637ea-994f-11e7-9ca2-08d96e553a4a.png)

**Comment by prashantagarwal** [comment]
@cawoodm We are already tracking this issue here #2195 . I am closing this as duplicate issue.
