### ISSUE TITLE
Activity Feed shouldn't track non-shared collections

### ISSUE THREAD

**Issue by poisa** [a85/POSTMan-Chrome-Extension#3528]
## App Details:
```
Postman for Mac
Version 5.2.0
OS X 16.7.0 / x64
```

I don't think the team activity feed should show things you do outside shared collections. In my workflow I usually do all sorts of tests and I don't want team members to have to see them. Think of it as using git; every time you hit the save button on the endpoint, you are making a commit. Whatever you do outside a shared collection should not be commited.

Currently if you are in a team, there is no way to hide actions from the team so the feed is very polluted with different tests from everyone and it is impossible to find the activity that matters (like someone adding/removing and actual production endpoint)

**Comment by a85** [comment]
I don't think it does. The activity feed only shows activity for the shared collections.

**Comment by poisa** [comment]
I'm going to close this issue because with the latest version this is not happening anymore.
