### ISSUE TITLE
Empty/null values in CSV-Files are resolved to variable name

### ISSUE THREAD

**Issue by si-net** [a85/POSTMan-Chrome-Extension#3529]
## App Details:

```
Postman for Linux
Version 5.2.0
linux 4.10.0-33-generic / x64
```

## Issue Report:
 1. Recent problem
 2. Context: Collection Runner, Submitting raw Json Bodies with the use of Data-variables.
 3. When a csv files contains empty values these will not resolve to an empty value in the request body. But instead the name of the data-variable will be placed in the request.

## Steps to reproduce the problem

Have csv-file that contains an empty value:
Iteration | id | name  |
1            |      | simon |

Have Request Json Body with the variable names of the csv-file:
{
"ID" : "{{id}}",
"customer_name" : "{{name}}"
}

This will resolve the request to:
{
"ID" : "{{id}}",
"customer_name" : "simon"

But the ID-field should resolve to an empty value, so that you can check your API´s behaviour in case of null/empty values. 
"ID" : "",
"customer_name" : "simon"

<!--

**Comment by si-net** [comment]
Problem was resolved. To produce empty strings one has to input: "" into the csvfile via a texteditor

**Comment by mjkraner** [comment]
What if you don't want an empty string?  you want it to be null

**Comment by shahjd01** [comment]
Is there any solution for handling null value? I am passing null in csv file, but it is treated as string!

**Comment by Lilly2016** [comment]
I'm also experiencing this issue. Is there a solution now?

**Comment by mrehal13** [comment]
Did we got any workaround to pass null in csv? Currently null in csv file it is treated as string i.e. "null"
