### ISSUE TITLE
Collection Runner Statistics Page Should Show Environment

### ISSUE THREAD

**Issue by kbuzby** [a85/POSTMan-Chrome-Extension#3530]
## App Details:

```
Postman for Chrome
Version 5.2.0
win / x86-64
Chrome 60.0.3112.113
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there: Encountered Today
 2. Expected behaviour: It would be nice to at the very least see the environment name the collection ran against when a run is selected in the statistics view.

In Collection Runner:
You can see part of the environment the collection ran against in the "Previous Runs" panel, but not the full name. When selecting the run to view the details in the statistics window the environment name isn't shown anywhere. 

Additionally, it would be even nicer to be able to see what the variables used for a run were, but the name would be good enough to start.

**Comment by a85** [comment]
A bit confused: the name is visible in the collection runner in the top bar.

**Comment by kbuzby** [comment]
I've been using the Windows native app recently and everything is showing there now, and have an easy to way to log the requests / responses to see the variables used. I don't remember what the chrome app looked life off the top of my head, and I know that's been discontinued in favor of the native apps recently. I'll close the issue. Thanks!
