### ISSUE TITLE
Request send hang when run with tests

### ISSUE THREAD

**Issue by luqmansungkar** [a85/POSTMan-Chrome-Extension#3531]
## App Details:
```
Postman for Linux
Version 5.2.0
linux 4.10.0-33-generic / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there: **`just recently`**
 2. Expected behaviour: **`Request sent, test run, the response showed, test result showed`** 
 3. Console logs:
```
xml.js:22 There was a fatal error when sending the request!
```
```json
{
"message" : "URI malformed",
"name" : "URIError",
"stack" : "URIError: URI malformed
    at Function.ensureEncoded (evalmachine.<anonymous>:9815:582)
    at Cookie.update (evalmachine.<anonymous>:9698:841)
    at new Cookie (evalmachine.<anonymous>:9698:353)
    at PropertyList.add (evalmachine.<anonymous>:9728:1914)
    at u (evalmachine.<anonymous>:11443:428)
    at Function.Ui (evalmachine.<anonymous>:11443:35994)
    at PropertyList.populate (evalmachine.<anonymous>:9728:3025)
    at new PropertyList (evalmachine.<anonymous>:9728:736)
    at new Execution (evalmachine.<anonymous>:71:450)
    at Object.<anonymous> (evalmachine.<anonymous>:68:1080)"
}
```
## Steps to reproduce the problem:
* Create usual request, write anything in tests tab (even a simple console log or anything from the snippet)
* Click send
* Stuck at sending
* Cancel request, remove everything from test
* Click send
* Request done normally and response showed normally

### Update
This just happen on a cluster of my endpoints. Request run normally before with test, just happen suddenly this morning. Nothing seems unusual, and request run normally outside postman or when run in postman without tests

**Comment by numaanashraf** [comment]
@luqmansungkar Thanks for reporting this. This seems to be a URI parsing error. Could you share a sample request to replicate this issue at our end? It'll help us a lot in triaging this issue.

**Comment by luqmansungkar** [comment]
Sample request:

```
GET /flip-server/big_api/v2/general/balance HTTP/1.1
Host: localhost
Authorization: Basic SkRKNUpERXpKRmRLVms1V1R6SktaRlZ0TVdFd05DODRZbTV2Tm5WV2JITnNOa0pCVmtrM1JVZEZVSFZLVms5VmIzRkRhMFU1Um5WcllqTlA6
Cache-Control: no-cache
Postman-Token: a83c5afe-3df2-b362-3ee4-2aa2e777fa0e
```

Sample tests script:
```javascript
try{
    tests["Response code is 200"] = responseCode.code === 200;
    
    var jsonData = JSON.parse(responseBody);
    
    pm.test("Response time is less than 200ms", function () {
        pm.expect(pm.response.responseTime).to.be.below(200);
    });
    
    tests["balance is integer more than -1"] = jsonData.balance > -1;
}catch(err){
    tests["exception: "+err] = false;
}
```

Expected response:
```json
{
    "balance": 13678053
}
```

Is that enough?

**Comment by kamalaknn** [comment]
@luqmansungkar we're not able to reproduce this with any of our API endpoints. It appears to be working for both JSON and non JSON responses. 

Could you share a sample of actual response you received that broke the request?

**Comment by luqmansungkar** [comment]
Yes, I also confused because the same endpoint with the same code, failed in my dev machine, but worked in the prod environment. It worked before in my dev machine.

What I share before is the actual response from my dev machine. Here's another example of the same endpoint
```json
{
    "balance": 2947483647
}
```

If try the request while opening the Postman Console, it showed these:
* Request Headers
```
cache-control:"no-cache"
postman-token:"8d9b645d-2443-4db2-93c4-d83d2c003e96"
authorization:"Basic SkRKNUpERXpKRmRLVms1V1R6SktaRlZ0TVdFd05DODRZbTV2Tm5WV2JITnNOa0pCVmtrM1JVZEZVSFZLVms5VmIzRkRhMFU1Um5WcllqTlA6"
content-type:"application/x-www-form-urlencoded"
user-agent:"PostmanRuntime/6.3.2"
accept:"*/*"
host:"localhost"
cookie:"_bigCSRF=1fbf43a61c66d3164cbfcae0dea1ac465aced2acdacef005a793dab37e218239a%3A2%3A%7Bi%3A0%3Bs%3A8%3A%22_bigCSRF%22%3Bi%3A1%3Bs%3A32%3A%22%F6%F0%02%D4L%97n%E4%FE%190L%D1%B5BS%92%A1G%95%90%0E%A1%0E%DC%AC%9B6%D9%60%A7%03%22%3B%7D; _bigSessionId=bpdiu2n0vn9kua0iuk77u19mg0"
accept-encoding:"gzip, deflate"
```
* Response Headers
```
date:"Tue, 19 Sep 2017 07:48:04 GMT"
server:"Apache/2.4.18 (Ubuntu)"
content-length:"22"
keep-alive:"timeout=5, max=100"
connection:"Keep-Alive"
content-type:"application/json; charset=UTF-8"
```
* Response Body
```
balance:2947483647
```

Those all showed while the request on the Postman main window still stuck.

**Comment by labbati** [comment]
Exact same issue here, I can add a few things to what @luqmansungkar wrote. I even tried to reproduce with public APIs like wikipedia and similar but I cannot reproduce.

```
Postman for Linux
Version 5.2.1
Linux my_laptop_name 4.10.0-35-generic #39-Ubuntu SMP Wed Sep 13 07:46:59 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

A few more observation that can help:
1. The problem is not related to the specific test code @luqmansungkar posted. It can be replicated even if you just write `// some comment` in the test with no other code at all.
2. It could be something at a lower level than the http layer, as the same setup (docker containers + api code) in local HAS the problem mentioned in this issue, while on the remote dev server HAS NOT.

Here are the curl relevant dump for the REMOTE request that WORKS
```
*   Trying xxx.xxx.xxx.xxx...
* TCP_NODELAY set
* Connected to api.devel.my_domain.com (xxx.xxx.xxx.xxx) port 80 (#0)
> POST /api/v1/user/login HTTP/1.1
> Host: api.devel.my_domain.com
> User-Agent: curl/7.52.1
> Accept: */*
> cache-control: no-cache
> content-type: application/x-www-form-urlencoded
> Content-Length: 81
> 
* upload completely sent off: 81 out of 81 bytes
< HTTP/1.1 200 OK
< Date: Wed, 04 Oct 2017 16:19:25 GMT
< Server: Apache
< X-Powered-By: PHP/7.1.5
< Cache-Control: no-cache
< Vary: Accept-Encoding
< Content-Length: 3999
< Connection: close
< Content-Type: application/json
```
While here the curl relevant dump for the LOCAL request that DOESN'T WORK
```
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to api.local.my_domain.com (127.0.0.1) port 80 (#0)
> POST /api/v1/user/login HTTP/1.1
> Host: api.local.my_domain.com
> User-Agent: curl/7.52.1
> Accept: */*
> cache-control: no-cache
> content-type: application/x-www-form-urlencoded
> Content-Length: 81
> 
* upload completely sent off: 81 out of 81 bytes
< HTTP/1.1 200 OK
< Date: Wed, 04 Oct 2017 16:18:31 GMT
< Server: Apache
< X-Powered-By: PHP/7.1.5
< Cache-Control: no-cache
< Vary: Accept-Encoding
< Content-Length: 3999
< Connection: close
< Content-Type: application/json
```

**Comment by yurii-github** [comment]
almost same here on Debian with standalone app
Postman for Linux
Version 5.3.2
linux 4.9.0-4-amd64 / x64

bugged just an hour ago

in console output IS good. Remove anything from "Tests" and no more "loading..." stuff

how to reset it? It's app breaking thing

p.s.
probably it is because
I was using xDebug and clicked POST again while STILL debugging previous session

p.p.s.
After running on newly extracted distro of Postman issue did not show!
AND this issue also disappeared on old distro!

that's how I "fixed" it for now, but I would appreciate to know location of that magic "blocker file"

regards

**Comment by yurii-github** [comment]
happened again. diff distro copy did not help
removing tests help

it's app breaking bug

**Comment by labbati** [comment]
In my case I noticed that this issue was caused by a cookie including binary data. Removing that cookie everything was fine (even with tests). Unfortunately I am not able to provide neither that cookie value, nor to reproduce with different cookies.

**Comment by yurii-github** [comment]
labbati 
thanks! I got some random _crf cookie, after removing it all is fine now
I guess that's the true issue

p.s. on 1st encounter I also cleared cookie, but it didn't help that time. maybe cache or something

**Comment by luqmansungkar** [comment]
Wow, thanks @labbati ! That solved the problem!

**Comment by yasiralijaved** [comment]
I also got the same issue. Resolved it after removing the _crf and _crf-backend cookies.
