### ISSUE TITLE
Social Login

### ISSUE THREAD

**Issue by cacothi** [a85/POSTMan-Chrome-Extension#3532]
## App Details:
```
Postman for Chrome
Version 5.2.0
win / x86-64
Chrome 61.0.3163.91
```

## New Feature:
Hi guys,

I was wondering if would be nice to have on the pre-request the possibility to trigger some social logins and on the callback set an global variable with the credentials to run the end-points.

As Facebook login doesn't change often, for example, would be even nicer if the users could input their facebook app ID and scope and the postman handles the request.

;)

**Comment by sdnts** [comment]
@cacothi Have you taken a look at `pm.sendRequest`? You can send requests from within pre-request & test scripts using this. [Here](https://gist.github.com/madebysid/b57985b0649d3407a7aa9de1bd327990) are some examples. 

I'm closing this, but please feel free to reopen if you face problems :)
