### ISSUE TITLE
Feature request: Edit variables directly in popup window

### ISSUE THREAD

**Issue by poisa** [a85/POSTMan-Chrome-Extension#3533]
When you hover over a variable a small popup window appears with the variable's value. It would be great if you could edit it right from that window instead of having to go through the menues to do so.

**Comment by bhawna2109** [comment]
@poisa Thanks for the feature request. This is actually on our roadmap and we're tracking this issue here- https://github.com/postmanlabs/postman-app-support/issues/763 We'll update the thread once we have this feature out. 

Closing this one as duplicate.
