### ISSUE TITLE
Sync issue - ordering of requests is not being synced

### ISSUE THREAD

**Issue by scenage** [a85/POSTMan-Chrome-Extension#3535]
## App Details:
Postman for Windows
Version 5.2.0
win32 10.0.15063 / x64

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there: **Recently**
 2. Expected behaviour: Creating requests in postman and then shifting the ordering is not being reflected in the postman pro call. This is happening for multiple requests.

This is the ordering of the requests in my postman application:
![image](https://user-images.githubusercontent.com/8476191/30531497-12180e00-9c92-11e7-9ae0-450b58df089b.png)

This is the ordering in the console logs from the collection call:
![image](https://user-images.githubusercontent.com/8476191/30575629-8aefa122-9d45-11e7-8536-37678d0cdd4b.png)

1. Create two requests
2. Move the last one to the first position. Notice the sync does not run.
 Note that duplicating and renaming requests causes the same problem.

**Comment by scenage** [comment]
The ordering matters when we are running newman through powershell.

**Comment by sdnts** [comment]
@scenage We've made several improvements here, can you update your app to the latest version (5.3.1 as of right now), and check if you're still seeing this? Please reopen if you do :)

**Comment by irmingard** [comment]
Still happening in v5.5.0, can you please reopen the issue?
