### ISSUE TITLE
post mac client connecting always

### ISSUE THREAD

**Issue by candyan** [a85/POSTMan-Chrome-Extension#3536]
<img width="1281" alt="2017-09-18 3 36 20" src="https://user-images.githubusercontent.com/1287252/30532735-79463016-9c88-11e7-86a1-150c20a114c1.png">

<img width="1425" alt="2017-09-18 3 45 22" src="https://user-images.githubusercontent.com/1287252/30532741-809f36be-9c88-11e7-9d1f-d62ffaefc98e.png">

## App Details:

```
Postman for Mac
Version 5.2.0
macOS Sierra 10.12.5 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:
 2. Expected behaviour:
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 4. Screenshots (if applicable)

**Comment by numaanashraf** [comment]
@candyan We had a momentary network outage, which should be resolved now. Could you check and let us know if you are still facing this issue?

**Comment by candyan** [comment]
resolved for me now! thx @numaanashraf
