### ISSUE TITLE
Capture input values and store it into variables

### ISSUE THREAD

**Issue by RakeshMadhavan** [a85/POSTMan-Chrome-Extension#3538]
Hello,

Is there a way to capture the values I pass as input and store it into variables? For example, I pass a value name=abc as the input. The response gives me values similar to abc but not exactly abc. The name I pass is dynamic and will be different for different requests. So, I need to save these input values somewhere. Is there a way to do it?

Regards
Rakesh

**Comment by numaanashraf** [comment]
@RakeshMadhavan I'm afraid I don't understand your use-case. Could you please give a detailed explanation?
