### ISSUE TITLE
We can post a data and a file, for data I need to use a raw and JSON and for file I have to use Binary data, so I am achieveing this now by making 2 API calls. Can I do it with one API call? can I use raw->JSON and somehow make sure that attachment is also uploaded? 

### ISSUE THREAD

**Issue by NeerajAduri** [a85/POSTMan-Chrome-Extension#3541]
## App Details:

```
Postman for Mac
Version 4.11.0
OS X 16.4.0 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:
 2. Expected behaviour:
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 4. Screenshots (if applicable)

**Comment by numaanashraf** [comment]
Hi @NrjAr, this is not supported in the UI yet. We are tracking this issue at #1104. I'm closing this as a duplicate.

**Comment by NeerajAduri** [comment]
Yeah please! I will follow 1104 then, thanks for the response.
