### ISSUE TITLE
Modify Generated Save File

### ISSUE THREAD

**Issue by IcarusCodes** [a85/POSTMan-Chrome-Extension#3543]
Hello, 

I would like to choose what gets saved in the exported file(the one you get from Runner > Statistics > save external file). I am going over an API and I require 83332 iterations. 1000 iterations generate 500k lines in the external file, and i cannot manipulate it due to its size.(~200mb)

Is there a way I could choose what gets saved in the generated file? I would only require the response bodies for each iteration clumped up in a json.

I could not find any information regarding this online, a response is much appreciated(or suggestions for this)

Thanks in advance!

**Comment by IcarusCodes** [comment]
Running all 80k requests would estimately generate 42 millions of lines, which would be roughly 12GB, was bored and did some math since this is a showstopper for me till I sort out how to customize the save file.

**Comment by prashantagarwal** [comment]
@IcarusCodes We don't have this currently. But I can tell you a very simple work around which you can modify according to your use case. You can create a local node server and expose a POST endpoint from that. Then you can start sending your API response to this POST request and on the server side just write this received response to a file. This is a [blog post](http://blog.getpostman.com/2017/09/01/write-to-your-local-file-system-using-a-postman-collection/) which will help you in doing that. Also we recently included [pm.sendRequest](https://gist.github.com/madebysid/b57985b0649d3407a7aa9de1bd327990) which will help you in sending a request from postman scripts.
