### ISSUE TITLE
Make a configurable option in Settings like "Create separate tab on each call" with default = "false"

### ISSUE THREAD

**Issue by chelovekdotcom** [a85/POSTMan-Chrome-Extension#3544]
## App Details:

```
Postman for Chrome
Version 5.1.3
win / x86-64
Chrome 60.0.3112.101
```

## Issue Report:
Working with PostMan I make about 20-50 REST calls every day.
At the end of the day I find out that I have opened >30 tabs. I need to close them one by one because the 'Close all tabs' menu item confirms at each tab. 
That's why I propose to make a configurable option in Settings like "Create separate tab on each call" with default value = "false".
So user could decide to create new tab for each call or rewrite values in current tab.

Thanks,
Ivan

**Comment by prashantagarwal** [comment]
@chelovekdotcom I don't think we will have support this. But that being said we do understand the pain of closing tabs one by one and getting that confirm box. In upcoming release we are fixing this to force close all tabs. I hope that will help in your workflow.
