### ISSUE TITLE
No SSL/certificate tab/fields to be found anywhere in 5.2.0

### ISSUE THREAD

**Issue by nilskp** [a85/POSTMan-Chrome-Extension#3545]
## App Details:

```
Postman for Chrome
Version 5.2.0
win / x86-64
Chrome 60.0.3112.113
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there: Just started using Postman, the Windows download.
 2. Expected behaviour: Per the documentation, and screenshots seen, I'm expecting to find either/both an SSL setting in the General tab, or a Certificates tab. Neither are present.
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 4. Screenshots (if applicable) 
![image](https://user-images.githubusercontent.com/74843/30711939-ea3f4ad4-9ecf-11e7-9c4f-7bc91c9767f8.png)

**Comment by prashantagarwal** [comment]
@nilskp Those tabs are there in our native postman apps. I am guessing that you are using chrome app.
