### ISSUE TITLE
postman with oauth2 and nodejs response

### ISSUE THREAD

**Issue by wizardnet972** [a85/POSTMan-Chrome-Extension#3548]
Hello. I'm building auth2server with nodejs. and I need some help to understand what Response should I return to postman..
I have route: 
```
router.get('/authorise', (req, res, next) => {
 res.status(200).send('test');
});
```

When I click on "Request token" button (in postman) new window is popup, with the test (from the route) as content.
What I missing here what I need to do to Postman that give him access_token?

I want to skip the login screen for now.

I'm not sure what data I need to send (status code so on)..
please please help me.

I also try: 
```
router.get('/authorise', (req, res, next) => {
   res.writeHead(302,
        { Location: 'https://www.getpostman.com/oauth2/callback' }
    );
    res.end();
});
``` 
but Not work.

**Comment by prashantagarwal** [comment]
@wizardnet972 I am sorry but we use this repo to only keep a track of bugs and feature requests. I think a better place for your query would be our slack community or stackoverflow.
