### ISSUE TITLE
Can't write tildes (~) on the URL input on Windows app.

### ISSUE THREAD

**Issue by javiergarval** [a85/POSTMan-Chrome-Extension#3550]
## App Details:
```
Postman for Windows
Version 5.2.0
win32 10.0.15063 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:
Encountered recently.
 2. Expected behaviour:
Writing tildes in the URL input.
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 4. Screenshots (if applicable)
![Imgur](https://i.imgur.com/6bpHapz.png)

## Steps:
When writing a tilde (~) into the URL input box, a dash (-) appears instead of a tilde. But appears correctly in the tab's text.

**Comment by numaanashraf** [comment]
@javiergarval Thanks for reporting this.

**Comment by SamvelRaja** [comment]
@javiergarval  This issue is not available in the latest version of Postman app. I recommend you to update to our latest 6.1.4 version.
![screenshot 4](https://user-images.githubusercontent.com/5114052/42078163-1721f8ca-7b99-11e8-89a9-19ceab57c923.png)
