### ISSUE TITLE
Chrome opens without pinned tabs

### ISSUE THREAD

**Issue by gregsdennis** [a85/POSTMan-Chrome-Extension#3552]
## App Details:

```
Postman for Chrome
Version 5.2.0
OS X / x86-64
Chrome 60.0.3112.113
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:
    I'm not sure when the behavior was introduced, but I've only noticed it recently.

 2. Expected behaviour:
    Chrome should open with my pinned tabs.

 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):

		requester.html:1 window.localStorage is not available in packaged apps. Use chrome.storage.local instead.
		requester.html:1 window.localStorage is not available in packaged apps. Use chrome.storage.local instead.
		requester.html:1 window.localStorage is not available in packaged apps. Use chrome.storage.local instead.
		requester.html:1 beforeunload is not available in packaged apps.
		requester.html:1 window.localStorage is not available in packaged apps. Use chrome.storage.local instead.
		tester_sandbox.html:1 unload is not available in packaged apps.
		tester_sandbox.html:1 window.localStorage is not available in packaged apps. Use chrome.storage.local instead.
		tester_sandbox.html:1 window.localStorage is not available in packaged apps. Use chrome.storage.local instead.
		sails.io.js:142 🌏 sync service connectivity initiated
		sails.io.js:759 socket replaying queued commands
		sails.io.js:142 🌏 connected to sync service.

 4. Screenshots (if applicable)

I like to keep several tabs pinned in Chrome.  But when I start Postman without Chrome already open, it opens a new Chrome window without my tabs.  I then have to go into my history and reopen the closed window (e.g. "4 tabs").

Not sure if this is a Postman or Chrome issue, but I figured I'd start here since Postman is launching Chrome.

**Comment by gregsdennis** [comment]
For completeness, I've logged an [issue with Chrome](https://bugs.chromium.org/p/chromium/issues/detail?id=768582) as well

**Comment by numaanashraf** [comment]
@gregsdennis This is a Chrome issue. Postman Chrome app is launched by Chrome and this is outside the control of Postman. Thanks for filing this issue with Chrome.

**Comment by gregsdennis** [comment]
@numaanashraf I posted here because Postman launches Chrome and didn't know if that was part of the issue.  Thanks though.
