### ISSUE TITLE
Duplicate attribute is not being displayed in the Pretty format of Response Body 

### ISSUE THREAD

**Issue by kavithaj110** [a85/POSTMan-Chrome-Extension#3553]
## App Details:

```
Version 5.2.0
OS X / x86-64
Chrome 60.0.3112.113
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:
I'm not sure when the behavior was introduced, but I've only noticed it recently.
 2. Expected behaviour:
Postman Should display the same response body in the Pretty format that is displayed in the Raw.

 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 4. Screenshots (if applicable)
our POST API call was returning malformed JSON response body (Duplicate attribute in the body) but in the Pretty Response it is always showing the valid Response body (with only one attribute)
but in the Raw format it is showing correct response body.

1.use the POST request which returns duplicate/ Invalid JSON response. 
2.check the Response body in Pretty format (JSON) and then Raw.

**Comment by numaanashraf** [comment]
Hi @kavithaj110, Pretty mode expects a valid JSON and does preliminary validation and sanitisation before showing a pretty-fied output, hence it will auto drop any duplicate keys. We'll take your suggestion into consideration when we roll out improvements to the Pretty response feature.

**Comment by plusonedev** [comment]
I just ran into this issue.  It has hidden a bug in our app for months.

**Comment by kamalaknn** [comment]
Hey @kavithaj110 @plusonedev 

This should be fixed on the latest version of the Postman desktop app.
<img width="1114" alt="Screenshot 2020-05-11 at 9 17 54 PM" src="https://user-images.githubusercontent.com/8401064/81581902-fe765200-93cc-11ea-9df6-2460eef92f56.png">
