### ISSUE TITLE
password could not found

### ISSUE THREAD

**Issue by licatherine** [a85/POSTMan-Chrome-Extension#3554]
## App Details:

```
Postman for Mac
Version 4.11.0
OS X 16.4.0 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:
 2. Expected behaviour:
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 4. Screenshots (if applicable)

**Comment by SamvelRaja** [comment]
@licatherine  can you provide me more details on the issue you are facing?

**Comment by licatherine** [comment]
1. When i type my username and password, it reminded me wrong password, but actually it is right.
2. When i click forgot password,  there is no space to reset the password.
Details please see below pictures:

![fo](https://user-images.githubusercontent.com/10595747/30843940-ed85c4c8-a2be-11e7-9bd5-e2c654494161.png)
![re](https://user-images.githubusercontent.com/10595747/30843942-f31cd408-a2be-11e7-9486-f0bd450d75c9.png)

**Comment by licatherine** [comment]
@SamvelRaja I have added the details, please review it.
Could you give me a solution?

Thanks

**Comment by SamvelRaja** [comment]
@licatherine clicking **Trouble signing** in will take you to the forgot password flow.
We are facing a small glitch in the handover from app to web login, we are looking into it right now.

**Comment by licatherine** [comment]
I tried as you mentioned. there is no response when clicking Trouble signing

**Comment by SamvelRaja** [comment]
@licatherine You can directly go to [Trouble Signing in](https://identity.getpostman.com/trouble-signing-in) page.

**Comment by licatherine** [comment]
directly go to this page could not resolve the password.

**Comment by abhijitkane** [comment]
@licatherine Can you contact us at help@getpostman.com with from your registered email address?
