### ISSUE TITLE
Please add Github Enterprise option to the Github Integration

### ISSUE THREAD

**Issue by alkemann** [a85/POSTMan-Chrome-Extension#3555]
Just tried out the GitHub integration and is a very nice way to sync collections down to a repository for the purpose of newman running acceptance tests, but much of my company's code lives in a GitHub Enterprise (hosted elsewhere than GitHub.com).

Hopefully adding the option to the GitHub integration (thanks for the great option already there, the detail of branch is particularly nice "extra" option) should hopefully not be too much work, but would be providing great value.

PS. The sort of companies that has their own GitHub enterprise is the same sort of company that has need for many pro accounts wink wink :)

**Comment by ratpik** [comment]
@alkemann - Would you happen to know if your enterprise github account is hosted in way that makes it publicly accessible on the internet (like github.com)? Or is the enterprise github endpoint behind some kind of a corporate firewall?

**Comment by alkemann** [comment]
Hey. No it is not behind a firewall, but it is behind an identity authentication  (Okta). Presumably you use the APIs, so you need a token?

**Comment by ratpik** [comment]
Thanks for providing that information! The custom identity provider should ideally not affect this integration. We do have this feature on our roadmap. We post regular updates to our [community](https://www.getpostman.com/community) channels and will have one for this too once we roll it out.

**Comment by emilva** [comment]
👍

**Comment by occasl** [comment]
This would be great to have and we're using Okta too. Any movement on this feature?

**Comment by larryfinkelstein** [comment]
This is one of the constraints preventing us from fully adopting postman.

**Comment by chickez** [comment]
Hi, any updates on this? Would be great to have it

**Comment by kartikjain26** [comment]
@alkemann @chickez @larryfinkelstein - Integration for Github enterprise feature where it is hosted elsewhere is being currently worked upon. It should be available soon.

**Comment by jamie-lloyd** [comment]
Is there a rough ETA for supporting github enterprise integration? I just bought a pro license today, assuming it would work.

**Comment by kartikjain26** [comment]
@jamie-lloyd Hey, Github enterprise integration will be available soon. Its in beta. Is your custom domain intranet ?

**Comment by BAMSDK** [comment]
If by "custom domain intranet" you mean a self hosted enterprise version of GitHub than yes

**Comment by jamie-lloyd** [comment]
If by "custom domain intranet" you mean a self hosted enterprise version of GitHub then yes

**Comment by a85** [comment]
I believe this is available now @preethammavin?

**Comment by preethammavin** [comment]
This has been added as part of Integrations.

**Comment by alkemann** [comment]
🍾

**Comment by TwentyKnots** [comment]
@preethammavin is this GitHub Integration feature available for Pro users? Or do you have to be a Postman Enterprise user to use the GitHub Enterprise Integration?

Thanks!

**Comment by kartikjain26** [comment]
@klpeltie It is available for Postman Pro users.
