### ISSUE TITLE
Environment  variable deleted instead of throwing undefined variable error when by mistake tried to assign with wrong data variable name

### ISSUE THREAD

**Issue by amnoman** [a85/POSTMan-Chrome-Extension#3557]
## App Details:

Postman helps you develop APIs faster
Postman for Windows
Version 5.2.0
win32 10.0.15063 / x64

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there: previously it was replacing the 
 environment variable name with the undefined data variable name but now its deleting the variable from the environment.
 2. Expected behaviour: Suppose to throw an error undefined variable
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 4. Screenshots (if applicable)

1. check the value of environment variable "Iteration"
2. Run the collection from the Runner
3. Find the environment variable again.
4. check the console as well, you will see an inconsistency for environment.set and console.log

[Practice.zip](https://github.com/postmanlabs/postman-app-support/files/1333910/Practice.zip)

**Comment by numaanashraf** [comment]
@amnoman Thanks for reporting. We are looking into this.

**Comment by harryi3t** [comment]
@amnoman I was able to reproduce this issue and we are working on the fix.
I will update the thread once the fix is released.

**Comment by harryi3t** [comment]
@amnoman We have released a fix for this on our canary apps. 
Can you please verify it?
You can get the canary app from https://www.getpostman.com/canary

**Comment by harryi3t** [comment]
@amnoman  This is fixed in the latest version of Postman 6.2.3
