### ISSUE TITLE
SSL Certificate Verification setting has been removed from Mac app 5.2.1

### ISSUE THREAD

**Issue by ebrooks-anaplan** [a85/POSTMan-Chrome-Extension#3558]
## App Details:

```
Postman for Mac
Version 5.2.0
OS X 15.6.0 / x64
```

## Issue Report:
My Postman version updated from 5.2.0 to 5.2.1 this morning and now I can no longer send requests to https endpoints that use a private cert.  I get a connection failure with the error that the certificate chain is invalid.  When I went to Settings to disable the "SSL certificate verification" setting, I discovered that it was no longer there.  After downloading 5.2.0 again and turning off this setting, I'm once again able send requests to my API's.  Please put this setting back!

**Comment by j-damsgaard** [comment]
Hi has the same issue, no certificate tab in my settings window..
<img width="717" alt="screen shot 2017-09-26 at 23 56 09" src="https://user-images.githubusercontent.com/32313423/30886490-760127cc-a317-11e7-887f-77e91405692a.png">

**Comment by j-damsgaard** [comment]
Or it seem's to bee a related issue...

**Comment by sdnts** [comment]
Hey guys, looks like you're on the Chrome apps. Certificate support is only available on our [native apps](https://getpostman.com/apps)

@j-damsgaard As your about screen says, you're on the Chrome app
@ebrooks-anaplan Did you open the Chrome app by accident? Visually they look similar. Heading over to Settings > About should confirm this.

**Comment by ebrooks-anaplan** [comment]
@madebysid I'm using the same shortcut in the dock that I've always used for the native app, but after the upgrade I'm now seeing Postman for Chrome in the settings tab.  I downloaded the latest native app and now the setting is back.  Perhaps the bug is with the automatic updater pulling the wrong update file and installing Postman for Chrome instead of Postman for Mac?

**Comment by sdnts** [comment]
Huh, that seems unlikely, since Chrome app updates are handled by Chrome, while native app updates are handled by our own service.
This is super weird since you say you used the same shortcut. Using macOS's Spotlight can make this happen, but the dock shortcut shouldn't. I'll see why this might be happening.
