### ISSUE TITLE
Runner - "=" added in the GET request to variable value

### ISSUE THREAD

**Issue by dnesterov** [a85/POSTMan-Chrome-Extension#3559]
App Details:

Postman for Windows
Version 5.2.0
win32 6.1.7601 / x64

## Issue Report:
 1. Not sure if this was there as I'm new to the postman, however, this definatelly looks like an issue
 2. Expected behavior:
"=" shouldn't be added to GET request on its own when running the "Runner" 
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):

Steps to reproduce the problem:
1. Set up an Enviroment
2. Set a Global variables
3. Create a collection with more than one request with the Global variables
4. Verify that all requests are successfully passing if run manually
5. Open "Runner"
6. Select your Environment and click "Run"
7. Observe the failed test
Expected Result:
1. All requests should run successfully (as they running successfully manually)
2. It should be no additional symbols or characters be added into request URL if running via "Runner"
Actual Result:
1. Request failed
2. "=" is added to the request URL

![image](https://user-images.githubusercontent.com/14010489/30898025-de11236a-a31e-11e7-8656-3ea32444cd76.png)
![image](https://user-images.githubusercontent.com/14010489/30898093-177f6706-a31f-11e7-87b2-136222d8f462.png)

**Comment by numaanashraf** [comment]
@dnesterov Hey. Thanks for reporting. This is a known issue that was originally reported and tracked at #3181. Closing this as duplicate.
