### ISSUE TITLE
Standard JSON editor uses 4 space indentation where beautifier (Cmd+B) uses 2 space indentation. The two should be consistent.

### ISSUE THREAD

**Issue by ravshansbox** [a85/POSTMan-Chrome-Extension#3562]

**Comment by numaanashraf** [comment]
@ravshansbox Thanks for reporting this. We'll roll out a fix for this in the coming releases.

**Comment by ravshansbox** [comment]
thank you for support 👍

**Comment by govindrai** [comment]
In addition to this, could you also add the shortcut into the `Edit` menu?

**Comment by SamvelRaja** [comment]
This has been fixed in our latest 6.1.4 app. 
And yes we will add this to our shortcut menu 👍

**Comment by SamvelRaja** [comment]
Closing in reference to #2378

**Comment by cosbor11** [comment]
no, I have no way of setting the beautifier to only use 2 spaces instead of 4. 2 spaces is preferable when working with ElasticSearch queries
