### ISSUE TITLE
Buffering considered Harmful

### ISSUE THREAD

**Issue by Pacerier** [a85/POSTMan-Chrome-Extension#3564]
Why would Postman even buffer? How can it be disabled?

**Comment by numaanashraf** [comment]
@Pacerier I'm afraid I don't understand this issue. Please elaborate.

**Comment by Pacerier** [comment]
Eg re https://stackoverflow.com/a/9728519/632951
See: postman shows no output before script end.

**Comment by Pacerier** [comment]
Bug is fixed?

**Comment by JHubi1** [comment]
I'm not sure if the original issuer was having the same problem, but there doesn't seem to be a way of disabling the client side buffering, like [curl's `-N`-flag](https://curl.se/docs/manpage.html#:~:text=%2D%2Dhttp2.-,%2DN%2C%20%2D%2Dno%2Dbuffer,-Disable%20the%20buffering). This is quite hindering when working with [JSON streaming](https://en.wikipedia.org/wiki/JSON_streaming) using [JSONL](https://jsonlines.org/), for example.
