### ISSUE TITLE
Cannot edit cookies with same name under the same domain but has different path

### ISSUE THREAD

**Issue by kenvifire** [a85/POSTMan-Chrome-Extension#3565]
## App Details:
Version 5.2.0 (5.2.0)
```
Postman for Mac
Version 4.11.0
OS X 16.4.0 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there
     Recently
 2. Expected behaviour:
     Should be able to edit cookies with same name under the same domain but has different path, only can see one of them.

**Comment by numaanashraf** [comment]
@kenvifire Thanks for reporting this.

**Comment by numaanashraf** [comment]
This issue is fixed in Postman v7.0.8

**Comment by kenvifire** [comment]
@numaanashraf Thanks for fixing this! Great job!
