### ISSUE TITLE
Support proxy authentication

### ISSUE THREAD

**Issue by sengopal** [a85/POSTMan-Chrome-Extension#3566]
## App Details:
Postman for Mac
Version 5.2.1
OS X Sierra / x64

## Issue Report

1. Setting up system Proxy usage was always a problem with Postman. However, with the new System Proxy setting (Toggle to use the system proxy), the hope was the proxy from the system configuration can be made to function.
2. However, the system proxy has an authentication (Basic base64(username:password)) which needs to be first provided to authorize against the proxy server.
3. Only after that the actual API can be invoked.
4. This is well explained in the stackoverflow post [here](https://stackoverflow.com/questions/10023636/http-spec-proxy-authorization-and-authorization-headers)
5. Unfortunately, there seems to be no way to perform such a call or i am unable to figure out the means to set this pre-call up.
6. I have scoured through the Postman docs, but could not find any indicator of how to make this work.
7. This is not a problem for the chrome extension as the authentication from the browser is shared via the Interceptor.

**Comment by msanecki** [comment]
@harryi3t  In which version/when are you going to provide this feature?

**Comment by harryi3t** [comment]
@msanecki I am afraid this is not on our immediate roadmap.
There is a workaround though, you can set an environment variable for using proxy
```
HTTP_PROXY=http://USERNAME:PASSWORD@IP_ADDRESS:PORT
HTTPS_PROXY=http://USERNAME:PASSWORD@IP_ADDRESS:PORT
```
Some imp points
 - If using localhost, make sure to use actual IP instead since localhost is converted to ipv6 `::1` which might not work for your local proxy server
 - If you don't want other applications to be affected then create a script file (depending on the OS) and set the environment variables only for Postman process
  Eg. for mac
  ```
   HTTP_PROXY=http://USERNAME:PASSWORD@IP_ADDRESS:PORT /path/to/Postman
   ```

The moment we have this on our roadmap I will update this thread :)

**Comment by yakup38** [comment]
@harryi3t 
Your work around doesn't work behind our corporate Proxy on Win 7.
I have set system env variable but still doesn't work on native app.

What am i misssing ?

**Comment by harryi3t** [comment]
For windows please try creating a `.bat` file
```bat
set HTTP_PROXY=http://USER:PASS@host:port
start Postman.exe
```
Save this file and put it in the postman installation directory.
For windows, it should be `C:\Users\Postman\AppData\Local\Postman\app-5.3.2` for the latest version.

When you open this file, the set environment variable will only apply to the Postman process.
I have tested this on win 10. Let me know if you have any issues with win 7.

**Comment by yakup38** [comment]
Hi,
thank you for your kind suggestion.
In my case i have a NTLM auth proxy i guess since it doesn't work with your suggestion.
However, the working workaround was using CNTLM local proxy from sourceforge.net.

Now, my main problem is the WSSE Authorization which just works fine out of the box on SOAPUI but unfortunately couldn't make it work on Postman till now.

I guess some scripting should probably do it on the Pre-Request tab but couldn't find the solution yet.

Thanks !

**Comment by isaru66** [comment]
I have run into this issue after upgraded from chrome app. Hope postman team will make this work out of the box soon.

For me, i have use CTNLM(http://cntlm.sourceforge.net) proxy as a work arround and it works very well.

**Comment by ChristianKoessel** [comment]
I have the same issue:
Behind a corporate proxy with mandatory authentication (Basic/NTLM) the native app isn't working:
`Error: tunneling socket could not be established, statusCode=407`
The suggested workaround (using HTTP_PROXY environment variable with user and password) works with many other applications but not with Postman.

There simply has to be a way to configure username and password for authenticating proxies!

**Comment by simgar** [comment]
The environment variables/batch file doesn't work for me, either

**Comment by pawelpluta** [comment]
Any plans to fix it? This issue is actually a blocker in migration from Chrome App, because application is unusable in most corporate worlds.

**Comment by clodio** [comment]
+1 : i can not use postman without this feature

**Comment by jocafi** [comment]
+1: All big corporation are waiting for the Postman with proxy authentication. At this moment, I am using the old Postman on the company that uses the proxy in the browser.

**Comment by riaadh** [comment]
+1 i think this should be priorisaed since most of us work in corporate company that have out of the box a proxy.
Thans

**Comment by kpodkalicki** [comment]
+1 it is a must-have

**Comment by pcostarg** [comment]
This is a must have for testing purposes on many corporate proxies.

**Comment by JulienVan** [comment]
\+ 1 , definitely a must-have, when will you deliver it ?

**Comment by Neurozone** [comment]
+1, please support it

**Comment by Christophe93** [comment]
+1, please support it

**Comment by bhanupinninti** [comment]
+1 when can we get this to use

**Comment by hedgeh0k** [comment]
+1 also faced this problem on the corporate network after migration from the Chrome application

**Comment by furick1** [comment]
+1

**Comment by furick1** [comment]
Using latest native postman on windows (v6.1.4) and mac, pass proxy basic auth by doing the following.

1) Enter your proxy auth uname/pwd in the authorization section and click preview request which should copy the base64 version of the login to a header var.
2) Copy that base64 value into a new header key called "Proxy-Authorization"
3) Go back into authorization and either clear the values or change to uname/pwd that your end point may require.
4) Ensure the proxy is set in the Postman settings minus the auth which doesn't stick or set it in the system proxy info

**Comment by anserzhang** [comment]
407 code still.
+1, Please support it.

**Comment by anserzhang** [comment]
Just found a workaround for Mac, using CNTLM, then set proxy server in Postman to 127.0.0.1:3128 (CNTML default listen port)

**Comment by Jpsy** [comment]
The workaround of @anserzhang works under Windows 10 too. The CNTLM project is a bit aged, but I could easily install and configure it on Win10. It also solves the same problem for any other local tools that are not able to do NTLM authentication against a proxy.

**Comment by Nickedynick** [comment]
To expand on @furick1 's answer, I ended upcopying this base64 value into an environment variable and writing a short [pre-request script](https://go.pstmn.io/docs-prerequest-scripts) to copy this into the headers for a given collection/folder:

    var proxyAuth = pm.environment.get("Proxy-Authorization");
    pm.variables.set("Proxy-Authorization", proxyAuth);

Doing it this way, you only need to replace the base64 string in one place each time your password expires.

**Comment by ronesp86** [comment]
+1 
please add support this \o/
include credential fields in [Settings] > [Proxy] > User and Pass
OR
just add field to put value in [Edit Collection] > [Authorization] > [TYPE] > Proxy-Authorization

**Comment by EdwinOtten** [comment]
+1 please support this
Chrome webapps are being deprecated but I still can't move to the native client, because it lacks this feature. It's very much needed for devs in corporate environments.

**Comment by iguana007** [comment]
+1

**Comment by Tzaphkiel** [comment]
+1 
I also have the issue.
env vars do not solve it.
It was working with the chrome app...

**Comment by nagelm** [comment]
+1

**Comment by fontanon** [comment]
+1

**Comment by SaamiSolutions** [comment]
Work around provided by @furick1 works on v6.3.0 on win 10

**Comment by guilhermelabigalini** [comment]
+1

**Comment by iguana007** [comment]
Confirmed @furick1 guide works on Win10 :)

**Comment by akw123** [comment]
+1

**Comment by nac0n** [comment]
+1 Same problem here... Since i can't add my username and password for the proxy in the native-app i see no way to go over from the webapp.
I tried to do @furick1 's suggestion as a workaround but it didn't work using v6.5.2. So i'm just testing my API using chrome or the (now deprecated) webapp...

**Comment by LA** [comment]
+1 RIP

**Comment by Jpsy** [comment]
Remember that there is a workaround using CNTLM local proxy. We use it all the time with Postman and it works well.

**Comment by sengopal** [comment]
@nac0n I add a  "Proxy-Authentication" .  header for every request with Basic authentication which works for mac app

**Comment by nac0n** [comment]
It appears i did something wrong to work during my first try with the "Proxy-authentication" suggestion as now it's working perfectly fine.

@furick1 's example did work.

**Comment by sai-github** [comment]
[Postman help center](https://support.getpostman.com/hc/en-us/articles/360008893713-How-do-I-configure-Postman-to-work-through-a-proxy-)

These steps on windows worked for me.
Create a `.bat` file with following and run it. Disable global proxy and system proxy in postman application
```
set HTTP_PROXY=''
set HTTPS_PROXY=''
set http_proxy='http://username:password@proxy_server:port'
set https_proxy='http://username:password@proxy_server:port'
start C:\path\to\Postman.exe 
```

**Comment by jscavalcante** [comment]
> Using latest native postman on windows (v6.1.4) and mac, pass proxy basic auth by doing the following.
> 
> 1. Enter your proxy auth uname/pwd in the authorization section and click preview request which should copy the base64 version of the login to a header var.
> 2. Copy that base64 value into a new header key called "Proxy-Authorization"
> 3. Go back into authorization and either clear the values or change to uname/pwd that your end point may require.
> 4. Ensure the proxy is set in the Postman settings minus the auth which doesn't stick or set it in the system proxy info

Its Working for me. THX...

**Comment by nagelm** [comment]
Yes @furick1 's example does work but I have to manually configure for each request. I can abstract the b64 token to an environment variable but there does not seem to be a way to add a new header automatically with each request.

**Comment by nac0n** [comment]
> Yes furick1 's example does work but I have to manually configure for each request. I can abstract the b64 token to an environment variable but there does not seem to be a way to add a new header automatically with each request.

@nagelm One way is to put all requests in a folder which holds the authorization header. Then with each new request just use the "Inherit auth from parent" type for authorization. This isn't a real fix but could ease the workflow for now.

**Comment by nagelm** [comment]
I am already using "inherit auth from parent" for the app auth but I hadn't thought to try it with another folder layer above for the proxy auth. Not sure if it will be possible if you are already using inheritance for app auth but thanks for the tip, I'll give it a go!

**Comment by codenirvana** [comment]
We've added this on our Canary (`version: 7.1.0-canary01`) channel https://www.getpostman.com/canary

<img width="727" alt="Screenshot 2019-03-29 at 2 52 37 AM" src="https://user-images.githubusercontent.com/4865836/55193698-bcd91680-51cd-11e9-8e37-4f51e1d5a1c7.png">

**Note:**
Currently, only Basic Auth is supported.
For NTLM we are tracking it here:  #3692 (Please leave 👍 there). 

As far as I know, mostly these three Authentication methods are used: `Basic`, `Digest`, and `NTLM`.
Let me know If I am missing anything here. 😅

Please try it out in the Canary version and let us know if you face any issue.
Will update the thread once we release this on our stable channel.

**Comment by mungojam** [comment]
Kerberos support please, or is that covered by digest?

**Comment by nagelm** [comment]
Working well for me on the Canary build. Only suggestion is to mask the password field like elsewhere in the app.

**Comment by codenirvana** [comment]
@nagelm Thanks for the feedback. We already made this change for our stable release.

<img width="698" alt="Screenshot 2019-04-04 at 6 52 41 PM" src="https://user-images.githubusercontent.com/4865836/55605788-b92c2d80-5793-11e9-927d-152a695fc60d.png">

**Comment by codenirvana** [comment]
Added support for proxy authentication in Postman v7.0.9 🚀

As mentioned in https://github.com/postmanlabs/postman-app-support/issues/3566#issuecomment-477780835 currently only Basic Auth is supported and support for NTLM is tracked here: #3692.
