### ISSUE TITLE
Export variable values during runtime to external file

### ISSUE THREAD

**Issue by agrawalankit29** [a85/POSTMan-Chrome-Extension#3567]
E.g. https://www.getpostman.com/docs/postman/collection_runs/working_with_data_files (https://www.getpostman.com/docs/postman/collection_runs/working_with_data_files) this link talks about fetching values from an external file, similarly how can I store a specific variable value to an external file while running our collections.
## App Details:

```
Postman for Mac
Version 4.11.0
OS X 16.4.0 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:
 2. Expected behaviour:
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 4. Screenshots (if applicable)

**Comment by numaanashraf** [comment]
@agrawalankit29 Thanks for writing in. This is not supported at the moment. Could you explain why you'ld want to export data to file while running the collection? It'll help us a lot in understanding your use-case and suggest any possible workarounds.

**Comment by agrawalankit29** [comment]
Hi Numaan,
Thanks a lot writing back and taking the effort to understand my
requirements. I really appreciate this.

The reason I want to export data while running the collection is that I am
working on a embedded system front end of which is based on REST APIs. Now
we have created collections of postman requests which are serving us as a
automated test script, so when I am sending requests there are few values
generated from the system which I need to capture. I want to export these
values to a external file preferably excel so that I can use this value
later or compare them as test results.

Hope I was able to give you some clarity and apologies for writing back so
late

Thank you

On 28-Sep-2017 12:51 PM, "Numaan Ashraf" <notifications@github.com> wrote:

@agrawalankit29 <https://github.com/agrawalankit29> Thanks for writing in.
This is not supported at the moment. Could you explain why you'ld want to
export data to file while running the collection? It'll help us a lot in
understanding your use-case and suggest any possible workarounds.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/postmanlabs/postman-app-support/issues/3567#issuecomment-332750684>,
or mute the thread

**Comment by a85** [comment]
I'd recommend checking this article out for exporting values/data: http://blog.getpostman.com/2017/09/01/write-to-your-local-file-system-using-a-postman-collection/
