### ISSUE TITLE
Plugin doesn't keep order of received elements. How to fix?

### ISSUE THREAD

**Issue by wzup** [a85/POSTMan-Chrome-Extension#3568]
Looks like the plugin breaks order of received elements.

I request a set of items from some API url. Items are ordered by date. So their PRIMARY `id` order doesn't have any order which is the right behavior. But Postman breaks correct date order and sorts items by `id`. Which is wrong.

This is order of items received from API. Ordered by date, not `id`:
```
[
    {id: 100, date: '2017'},
    {id: 1, date: '2016'},
    {id: 50, date: '2015'},
]
```

Then I iterate items to make an object by `id`. And date order MUST be retained:
```
let oItems = {}
items.forEach(row => {
    oItems[row.id] = row;
});
```

So I expect this result, which correct result:
```
{
    100: {id: 100, date: '2017'},
    1: {id: 1, date: '2016'},
    50: {id: 50, date: '2015'},
}
```

But Postman breaks it, and returns this instead, ordered by `id` which is wrong. 
Why? How to forbid Postman to interfere and sort items arbitrarily?
```
{
    1: {id: 1, date: '2016'},
    50: {id: 50, date: '2015'},
    100: {id: 100, date: '2017'},
}
```

**Comment by prashantagarwal** [comment]
@wzup. You are converting an array of object into a hash map like data structure. Hash maps will not guarantee the order and in most of the scenarios sort automatically.  So I don't think there is anything that Postman app can do here. But just out of curiosity why do you want to have some order in an object, if you want so why not let them be in array itself.

**Comment by wzup** [comment]
> why do you want to have some order in an object

I can access data directly by some key. With an array of objects I can't. I need to iterate an array to find an object I need. Not very productive.

> Hash maps will not guarantee the order

Not exactly.  Objects keep order how you populate them.
But generally I agree. I already googled the issue and have learned it. It's ES issue, not Postman's.
