### ISSUE TITLE
[Feature Request] Allow integration with a self-hosted GitLab installation

### ISSUE THREAD

**Issue by dannyhajj** [a85/POSTMan-Chrome-Extension#3569]
I was trying to use the GitLab integration, but it currently doesn't allow us to input a URL, so I assume it only allows integration with gitlab.com.

Is it possible to add a feature which allows us to integrate with a self-hosted GitlLab installation?

**Comment by prashantagarwal** [comment]
@dannyhajj we are already tracking this here #2978 . Closing this as duplicate.
