### ISSUE TITLE
It would be preferable to allo partial publications of collections

### ISSUE THREAD

**Issue by workabyte** [a85/POSTMan-Chrome-Extension#3571]
this feature requests is based on 2 collections we currently maintain for a single API.
one collection is focused on testing overall functionality and the other if for creteing a public place for documentation.

ALL calls in the public collection exists in the test collection and then have to be maintained individually.
the test collection has additional calls that are used to validate a handful of other items and are continually evolving.

ideally we could merge these together and not publish the extra calls so that we would not have to maintain the calls that represent the core functionality in multiple locations.

i could be taking the wrong approach to this, if there is a better way to solve for this please let me know.   

one of many examples here,
![image](https://user-images.githubusercontent.com/2341949/30978938-139c52c6-a44a-11e7-9768-01f3306ecbd8.png)

![image](https://user-images.githubusercontent.com/2341949/30978957-1f2ed8e8-a44a-11e7-9e10-737c9b210a8d.png)

**Comment by a85** [comment]
I don't think this is going to be on our roadmap any time soon as we intend a collection to be a source of truth. We suggest creating multiple collections/multiple documents and linking them together.
