### ISSUE TITLE
Response body not displaying correctly when Response Content Type is application/json and response body is a number

### ISSUE THREAD

**Issue by bobderrico** [a85/POSTMan-Chrome-Extension#3572]
## App Details:

```
Postman for Mac
Version 5.2.0 (5.2.0)
OSX Sierra Version 10.12.6
```

I am running into an issue testing an endpoint that sets a response header `Content-Type` as `application/json`, but the response body is just a single number (in this case... `1`). My understanding of JSON is that a JSON literal on its own is considered valid JSON. For example, `JSON.parse(1)` works without any issues (tested this in Chrome, Safari, Firefox, and IE).

In this specific case, the response body postman displays for the value of `1` is `��srjava.lang.Integer⠤���8Ivaluexrjava.lang.Number������xp`.

I would expect the response body displayed to be `1`. When I make the request using cURL, or using the `fetch()` api in the browser, I get the expected response body of 1.

 As an experiment, since I do have control over the API, I set the `Content-Type` header as `text/plain`, and in this case, I see the expected response body of `1` in Postman. However, this is not a preferred solution, as our API development team has chosen to use `application/json` for these types of response, and our other systems and browsers have no issues with handling this type of request.

**Comment by prashantagarwal** [comment]
@bobderrico Thanks for reporting. Can you do me a favour and provide a screenshot of the Postman console after you send this request. Follow these steps.
- Open Postman console (View -> Show postman console)
- Send this request
- See that the received response is displayed in the Postman console.
- Take the screenshot of the received response in Postman console.

**Comment by bobderrico** [comment]
Attached is the screenshot. Thank you!
<img width="963" alt="screen shot 2017-10-02 at 3 20 09 pm" src="https://user-images.githubusercontent.com/22890947/31095058-67ebfc44-a785-11e7-99a4-27a1e54f0746.png">

**Comment by prashantagarwal** [comment]
@bobderrico This looks weird. As far as I know we don't do any sort of manipulations on the received response. Also response is displaying some error related to Java whereas Postman uses Javascript. I will assume your server is built using Java so this could be possible that you are receiving this response from server itself.

**Comment by bobderrico** [comment]
That is correct that this is a Java server, however the request returns the expected result of `1` with `curl` and Javascript's `fetch()` API.

I am beginning to think that this is actually an underlying issue with NodeJS. We are exploring several avenues for testing, including using NodeJS and the Chakram testing library, and I see the same result there as on Postman. I haven't had a chance to do any digging, but I suspect this may be an issue with NodeJS's http module.
