### ISSUE TITLE
pm.globals.set(key, value) does not work if `value` is a CryptoJS object

### ISSUE THREAD

**Issue by joristirado** [a85/POSTMan-Chrome-Extension#3575]
## App Details:

```
Postman for Windows
Version 5.2.1
win32 10.0.15063 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:
First time using the `pm.globals.set()` method as of today, before I was using `postman.setGlobalVariable()` which works as expected, so I can't say

 2. Expected behaviour:
`pm.globals.set('md5', CryptoJS.MD5('string'))` should set the global variable `md5` to the MD5 hash of `string`, instead it sets it to `[object Object]`

 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
n/a

 4. Screenshots (if applicable)
n/a

## Steps to reproduce
1. In the pre-request script, generate a md5 hash using the `CryptoJS.MD5()` method:
```javascript
var hash = CryptoJS.MD5('string');
```
2. Now set a global variable using the `pm.globals.set()` method:
```javascript
pm.globals.set('md5', hash);
```
3. Run your request and check the value of your global variable `md5`. With this example, it should be `b45cffe084dd3d20d928bee85e7b0f21` and instead is `[object Object]`

## Notes
This scenario works perfectly fine when using `postman.setGlobalVariable(key, value)` method.

**Comment by numaanashraf** [comment]
Thanks for reporting this @azefiel. We're looking into this discrepancy.

**Comment by kamalaknn** [comment]
@azefiel There are two parts to this issue. 

First the `postman. setGlobalVariable` was doing an implicit string conversion before setting to a global variable. That is why you were seeing it as a string always. The `pm.globals.set` tries to retain the type of the value.

However, Postman does not support viewing/editing values as objects yet, although the scripts support it. That is why you are seeing a mismatch. We are working on allowing viewing/editing values as objects in environments.

If you want to continue with the previous behavior you can use `pm.globals.set('md5', hash.toString());`

**Comment by prashantagarwal** [comment]
Related to #3463
