### ISSUE TITLE
2-panel view in beta needs more work. 

### ISSUE THREAD

**Issue by nutharsh** [a85/POSTMan-Chrome-Extension#3577]
url holder should not be merged with request panel. it has to be separated from both request and response panel.

**Comment by nutharsh** [comment]
[snapshot url](https://github.com/nutharsh/uploads/blob/master/postman-2-panel-view.png)

**Comment by prashantagarwal** [comment]
@nutharsh Thanks for suggesting this. We are already tracking this here. #2716 . Closing it as duplicate.

**Comment by nutharsh** [comment]
Thanks for looking into this.
