### ISSUE TITLE
Code genetared for swift 4 doesn't work

### ISSUE THREAD

**Issue by randalb1991** [a85/POSTMan-Chrome-Extension#3579]
## App Details:

```
Postman for Mac
Version 5.2.1
OS X / x86-64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:
 2. Expected behaviour: The code generated  should to work for swift4
 4. Screenshots (if applicable)

**Comment by numaanashraf** [comment]
Thanks for reporting this @randalb1991

**Comment by daniel-lahoz** [comment]
Postman for Mac
Versión 5.3.2
OS X / x86-64

I don't Know what happend here, in previous versions the code works and also was more elegant solution.

**Comment by abhijitkane** [comment]
@randalb1991 @daniel-lahoz Can you try this is Postman 7.2.1, with the 'Experimental Codegen Mode' flag enabled in Postman's global settings? We've introduced bug-fixes, support for two new languages (JS-Fetch and Powershell), and the ability to configure certain aspects of the generated snippet.
