### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by gregsdennis** [a85/POSTMan-Chrome-Extension#3581]
## App Details:

```
Postman for Windows
Version 5.2.1
win32 10.0.15063 / x64
```

## Feature:
I'd like to reorient the request body and response in a vertical split so that the panes are side-by-side rather than one on top of the other.

With the horizontal split, there is a lot of wasted real estate to the right side of the application.  A vertical split would utilize this space.  It would also show more of the response without having to scroll.

**Comment by numaanashraf** [comment]
@gregsdennis This is already supported. Head to Settings > General and toggle Two-pane view under User Interface.

**Comment by gregsdennis** [comment]
I see that is the functionality I was looking for.  However, it seems that "Two-pane view" may be a poor name for this feature given that the default orientation also has two panes.

**Comment by numaanashraf** [comment]
@gregsdennis Thanks for the suggestion. 😃
