### ISSUE TITLE
How to default to XML for all requests and responses? Cannot change to XML view? Etc?

### ISSUE THREAD

**Issue by mkamoski** [a85/POSTMan-Chrome-Extension#3583]
Dear TabbedPostman Extension --
Please.
I am using the latest TabbedPostman extension on the latest Chrome on Windows 7.
Cannot change to XML view.
Cannot default responses to XML.
Clicked button for XML and JSON still appears.
Sent header as content-type = application/xml but no luck.
I need to send and receive XML for all testing.
Is there a trick?
Please advise.
Thanks.
-- Mark Kamoski

**Comment by numaanashraf** [comment]
@mkamoski Postman tabbed extension has been deprecated for over 2 years and we no longer maintain or provide support for it. Please use our Desktop apps - https://www.getpostman.com/apps
