### ISSUE TITLE
Support for zero width joiners in emojis

### ISSUE THREAD

**Issue by j27lee** [a85/POSTMan-Chrome-Extension#3584]
So far postman has been an amazing tool and has worked incredibly well for me. I'm currently working with emojis and ran into an issue today around Zero Width Joiners. Some emojis are combinations of other emojis with a zero width joiner in between them. Browsers take the 2 emojis and combine them for the user.

The API response through postman shows the emojis with the zero width joiner in between:

If something is stored as: 👨🏿‍🚀💆🏽👨🏿‍🚀👨‍🚀
The response in postman is this:  "👨🏿\u200d🚀💆🏽👨🏿\u200d🚀👨\u200d🚀",

In a web browser, they render correctly.

Any plans on supporting zero width joiners in the future?

## App Details:
```
Postman for Mac
Version 5.2.0 (5.2.0)
OS X 10.12.6 (16G29) / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:  First time I've noticed it.
 2. Expected behaviour: Render the combined emojis as one instead of 2 emojis with a zero width joiner in between them
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 4. Screenshots (if applicable)

<img width="453" alt="screen shot 2017-10-02 at 1 20 40 pm" src="https://user-images.githubusercontent.com/333929/31095399-f67bf960-a775-11e7-9c37-d354c6904da1.png">

Steps to reproduce the problem:
1) Have an API service return this: 👨🏿‍🚀💆🏽👨🏿‍🚀👨‍🚀
2) Postman shows this: "👨🏿\u200d🚀💆🏽👨🏿\u200d🚀👨\u200d🚀",

**Comment by numaanashraf** [comment]
Thanks for the suggestion @j27lee

**Comment by DannyDainton** [comment]
Hey @j27lee 

This looks to be fixed in the latest Canary version.

<img width="704" alt="Screenshot 2019-06-28 at 11 53 24" src="https://user-images.githubusercontent.com/17089546/60337605-641b4480-999b-11e9-9497-4e9d94348e74.png">

https://www.getpostman.com/downloads/canary

**Comment by preethammavin** [comment]
~~Closing the issue for now, as it is not reproducible. Feel free to reopen it, if it is not so.~~

This is fixed in the latest version of the Postman app (v7.3)
