### ISSUE TITLE
The maximum length for the response text is too small.

### ISSUE THREAD

**Issue by waltmoorhouse** [a85/POSTMan-Chrome-Extension#3589]
## App Details:
```
Postman for Mac
Version 5.2.1 (5.2.1)
OS X 10.12.6 (16G29) / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there: recently encountered, but might have always been there.
 2. Expected behaviour: Allow me to save an Example of my API output even when it is large.
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app): Response too large. The response body for "Large Example" cannot be synced. The maximum length for the response text is 100000 characters

## Steps to reproduce the problem:
Hit an API that returns a large (over 100000 characters) response.
Click Save Response.
Click Save Example.
The error will appear on the top of the screen in a popup.

**Comment by numaanashraf** [comment]
Thanks for the feedback @waltmoorhouse.

**Comment by a85** [comment]
@sobtiankit Can we increase these limits now?

**Comment by walkiri** [comment]
I keep seeing this few times per day even after deleting example.

**Comment by waltmoorhouse** [comment]
We're holding off on purchase until this is resolved, as it makes it impossible to use for documenting our API or mocking, because the responses we need are very large.  Please fix asap and let us know when done so we can contact sales.

**Comment by sobtiankit** [comment]
@waltmoorhouse we're going to increase this limit in 5.4 version of the app. Just curious, what is a typical large response size for you?

**Comment by steveblackmon** [comment]
i would like to see a higher limit as well.  some of our endpoints returns several megs of json uncompressed.  perhaps if the response is past a certain size, the example response could be saved as a blob such that it can be only be previewed in the client (or in the published docs) with an additional click and server request by the viewer?

**Comment by waltmoorhouse** [comment]
That's great news @sobtiankit !  The one I was trying to save when I got this error is 360k characters, but it is English only, we also have some calls that include French, so I ran one of those and it is over 600k characters, so I think if the max size were 1,000,000 it would accommodate our largest current outputs.

**Comment by gjnk** [comment]
We have responses as big as 1,500,000 characters, so I suggest setting a limit to 5,000,000, just to make sure.

**Comment by ruariobrien** [comment]
Hi, I am testing an api endpoint in development that returns uncompressed 6.3 MB of json data. Postman hangs with "loading" in its GUI interface on the api call. Console shows "Responses larger than 1MB are not shown" , I had to run the api call again through mitmproxy to confirm the api response was actually returning the expected json data. I think it it a bug for the GUI to hang saying "Loading...". I advocate for allowing a setting under preferences to allow the ability to increase response api buffers for json data.  Thanks.

**Comment by a85** [comment]
This response should be much higher now. @shamasis Can you confirm and close?

**Comment by codenirvana** [comment]
We've made significant improvements recently to handle large responses and this has been fixed in the latest version of the Postman app.
