### ISSUE TITLE
Digest authentication example doesn't work with apache 2.4.25

### ISSUE THREAD

**Issue by utezduyar** [a85/POSTMan-Chrome-Extension#3590]
## App Details:

```
Postman for Mac
Version 5.2.0 (5.2.0)
10.12.6 (16G29)
```

## Issue Report:

Digest authentication example coming with postman doesn't work with apache 2.4.25. Successful apache authentication requires $opaque field to be passed on the request too and the only way to make apache echo this value is to actually make a digest authentication attempt. 

Following is the console for successful authentication:

> GET
> http://192.168.0.31/axis-cgi/disks/list.cgi?diskid=all
> 08:09:19.974
> Request Headers:
> cache-control:"no-cache"
> postman-token:"3d1941fc-a387-4055-97d7-701ee8a512af"
> authorization:"Digest username="root", realm="a@a.com", nonce="", uri="/axis-cgi/disks/list.cgi?diskid=all", response="27fd9263d4f4d5a9f8226d1fa9a90247", opaque="""
> user-agent:"PostmanRuntime/6.3.2"
> accept:"*/*"
> host:"192.168.0.31"
> accept-encoding:"gzip, deflate"
> Response Headers:
> date:"Sat, 06 May 2017 04:21:39 GMT"
> server:"Apache/2.4.25 (Unix) OpenSSL/1.0.2k"
> www-authenticate:"Digest realm="AXIS_ACCC8E186218", nonce="S/2mV9NOBQA=007c5a4908a18707ddf1a85ba14a53ced249b203", algorithm=MD5, opaque="13", stale=true, qop="auth""
> content-length:"381"
> keep-alive:"timeout=5, max=100"
> connection:"Keep-Alive"
> content-type:"text/html; charset=iso-8859-1"
> Response Body:
> 401
> 10 ms
> GET
> http://192.168.0.31/axis-cgi/disks/list.cgi?diskid=all
> 08:09:20.046
> Request Headers:
> cache-control:"no-cache"
> postman-token:"2561441a-a190-49b1-8538-c2f6127c1d76"
> authorization:"Digest username="root", realm="AXIS_ACCC8E186218", nonce="S/2mV9NOBQA=007c5a4908a18707ddf1a85ba14a53ced249b203", uri="/axis-cgi/disks/list.cgi?diskid=all", response="4f2276678c2e76c17686e301bf684018", opaque="13""
> user-agent:"PostmanRuntime/6.3.2"
> accept:"*/*"
> host:"192.168.0.31"
> accept-encoding:"gzip, deflate"
> Response Headers:
> content-type:"text/xml"
> Response Body:
> 
> 
>

**Comment by numaanashraf** [comment]
@umuttl Thanks for reporting this. We are working on a lot of improvements to the Auth feature at the moment.

**Comment by harryi3t** [comment]
@umuttl I am happy to inform you that [this issue](https://github.com/postmanlabs/postman-runtime/pull/411/files#diff-0363496618ed0af9394c70423f7ee91eR174) is already fixed in [runtime](https://github.com/postmanlabs/postman-runtime).

This will be released with Postman 5.3 in the next couple of days.

**Comment by utezduyar** [comment]
Thanks!

**Comment by utezduyar** [comment]
@harryi3t What does new postman mean for me? Currently I make 2 DigestAuth requests and the first one has only bogus data. I assign the global variables on the first one with following code. Does new runtime mean that I don't have to do this?

> var authenticateHeader = postman.getResponseHeader('WWW-Authenticate'),
>     realmStart = authenticateHeader.indexOf('"',authenticateHeader.indexOf("realm")) + 1 ,
>     realmEnd = authenticateHeader.indexOf('"',realmStart),
>     realm = authenticateHeader.slice(realmStart,realmEnd),
>     nonceStart = authenticateHeader.indexOf('"',authenticateHeader.indexOf("nonce")) + 1,
>     nonceEnd = authenticateHeader.indexOf('"',nonceStart),
>     nonce = authenticateHeader.slice(nonceStart,nonceEnd);
>     opaqueStart = authenticateHeader.indexOf('"',authenticateHeader.indexOf("opaque")) + 1,
>     opaqueEnd = authenticateHeader.indexOf('"',opaqueStart),
>     opaque = authenticateHeader.slice(opaqueStart,opaqueEnd);

**Comment by harryi3t** [comment]
@umuttl In the new version of Postman that is coming out in the next few days, Postman will do the populating of `nonce`, `realm`, `opaque`, etc for you if left empty.

In the new version, you can remove the global variables for the `nonce`, `realm` and `opaque`,  and can also remove the extraction and retry logic.

**Comment by harryi3t** [comment]
@umuttl Postman 5.3.0 is out. Could you try it again with this updated version?

**Comment by utezduyar** [comment]
I tried it, things are much better. Thanks.
