### ISSUE TITLE
Change Split view design

### ISSUE THREAD

**Issue by ram3shyadav** [a85/POSTMan-Chrome-Extension#3591]
## App Details:

```
Postman for Chrome
Version 5.2.1
win / x86-64
Chrome 61.0.3163.100
```

## Feedback:
 Please update the split view design for the chrome like below

![untitled](https://user-images.githubusercontent.com/4143650/31213851-2d9cdc00-a9c6-11e7-9862-4c0a8bb053e9.jpg)

**Comment by numaanashraf** [comment]
Thanks for the feedback. We are tracking this request at #2716. Closing this as duplicate.
