### ISSUE TITLE
Schema Validation Passes even if Difference in Property Name in an Object

### ISSUE THREAD

**Issue by guptarajatkn** [a85/POSTMan-Chrome-Extension#3593]
## App Details:

```
Postman for Linux
Version 4.11.0
UBUNTU 16.04
```

## Issue Report:
The schema validation is passing always. Even when you have a different property inside the schema than your data object. (or vice versa) the postman test passes always. 
Ideally Schema validation must capture the difference in the properties in data vs schema in test.

 var data = {
    "id": 17,
    "logoURL": "http://abcdefgh.org/logotest",
    "name": "abcd efgh",
    "websiteURL": "www.abcdefgh.com",
    "emailId": "abcdefgh@company.com",
    "creationDate": "2017-10-05T09:15:33.083Z"
};

var schema = {
    "type": "object",
    "properties": {
        "id": { "type": "integer" },
        "logoURL": { "type": "string" },
        "name": { "type": "string" },
        "websiteURL": { "type": "string" },
        "emailId": { "type": "string" },
        "creationTime": { "type": "string" }
    }
};

tests["Testing response schema"] = tv4.validate(data, schema);

is a PASS always ( even with difference in "creationDate" vs "creationTime" )

**Comment by prashantagarwal** [comment]
@guptarajatkn To strictly match the properties defined in your schema you can use a combination of
`required` and by setting `additionalProperties ` to false.

something like this

```
var schema = {
    "type": "object",
  	"additionalProperties": false,
  	"required": ["id","logoURL","name", "websiteURL","emailId", "creationTime"],
    "properties": {
        "id": {
            "type": "integer"
        },
        "logoURL": {
            "type": "string"
        },
        "name": {
            "type": "string"
        },
        "websiteURL": {
            "type": "string"
        },
        "emailId": {
            "type": "string"
        },
        "creationTime": {
            "type": "string"
        }
    }
};
```

**Comment by guptarajatkn** [comment]
Thanks a lot. I was missing something surely ;) can this be added to POSTMAN Tests Documentation as well would be helpful to many out there.
