### ISSUE TITLE
Add file download ability to runner

### ISSUE THREAD

**Issue by chrisron95** [a85/POSTMan-Chrome-Extension#3594]
## App Details:
```
Postman for Mac
Version 5.2.1
OS X 17.2.0 / x64
```

## Feature Request:
I think a great feature that would be very helpful for me and my team along with a lot of other people I’m sure would be to be able to download files from the runner. For example, our company generates reports. Now, I have a runner set up that will do what it has to do and generate a report, then it gets the report in our three formats: HTML, JSON, and PDF. When using the runner, the HTML and (sometimes, depending on the length) the JSON are returned in the response body, however the PDF just says the test passed and that’s it. If I use that same call in postman, not in the runner, it will pop up with a dialog box to download the PDF file. I’d like to be able to set something up in the tests section where I could specify what I want to name it and where I want it to save.

I know for me it would be an extremely helpful feature, because we have to generate a lot of reports to test all of our products and test cases, however right now only half of that is automated. It will generate the reports, but then I have to manually go in and download each report, rename them, then put them in the google drive folder. It’s not that big of a deal and having the runner has significantly cut down the time this process takes, but it would be nice to be able to completely automate it so it’s not so tedious, since we have to run this pretty often.

**Comment by chrisron95** [comment]
Similar to this feature request #3489

**Comment by prashantagarwal** [comment]
@chrisron95 I can suggest you a workaround. You can create a local node server and expose a POST endpoint from that. Then you can start sending your API response to this POST request and on the server side just write this received response to a file. This is a [blog post](http://blog.getpostman.com/2017/09/01/write-to-your-local-file-system-using-a-postman-collection/) which will help you in doing that. Also we recently included [pm.sendRequest](https://gist.github.com/madebysid/b57985b0649d3407a7aa9de1bd327990) which will help you in sending a request from postman scripts.
