### ISSUE TITLE
Saving Example Requests Is Slow

### ISSUE THREAD

**Issue by staticvoidmaine** [a85/POSTMan-Chrome-Extension#3595]
## App Details:

```
Postman for Linux
Version 5.2.1
linux 4.12.13-1-MANJARO / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there: Recently
 2. Expected behaviour: Reasonably quick/responsive UI
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 4. Screenshots (if applicable)

I'm not sure if this is specific to my account as I have a fair amount of request examples saved (possibly a few hundred), when running a request and clicking `Save Response` is starting to slow to a crawl. It's creeping up into the 10-30 second range before the save screen appears. I'm just bringing the performance issue I'm experiencing to your attention.

In the case I just experienced, I have a collection with published documentation with a fair amount of markup and about 20 requests with ~3 examples per request.

1. Have a request in a collection with published documentation that you would like to add examples to
2. Run a request
3. Click `Save Response`
4. Possibly experience a wait of 5-30+ seconds for the save response screen to appear

**Comment by prashantagarwal** [comment]
@rylancates This should be fixed in Postman version 5.3.2. Feel free to reopen the issue if you are still facing this issue.
