### ISSUE TITLE
Hard coded shortcuts conflicting with my (possibly many) keyboard layouts

### ISSUE THREAD

**Issue by drake1979** [a85/POSTMan-Chrome-Extension#3596]
Hard coded shortcuts are very annoying when using hungarian layout for example.
To type the @ sign you have to press Ctrl+Alt+V which is a Postman shortcut toggling the split view.
To type the & sign you have to press Ctrl+Alt+C which opens the console...

Nice feature to have shortcuts, but without the ability to disable them, or customize them this feature is a drawback for many of us.

**Comment by prashantagarwal** [comment]
@drake1979 Thanks for the suggestion. This is there on our roadmap but I don't have exact timeline for this. We will keep you updated about this.

**Comment by somadeaki** [comment]
A simple "disable hotkeys" switch would suffice. The app is basically unusable on non-English keyboard layouts.

**Comment by TommyZG** [comment]
+1 on this issue in the name of a 100 million South&East Europeans...

**Comment by somadeaki** [comment]
It's a real shame that this simple issue still hasn't been addressed. I am unable to use postman any longer.

**Comment by jsobeslav** [comment]
I support this feature: in order to write `&`, or `@` characters I have to open notepad, write it there, and copy the character to Postman. It's anoying.

Simple off switch is all we need.

**Comment by drake1979** [comment]
Created this issue a year ago.
Since than Postman updated itself many times.
Disabling all (but Toggle) hotkeys would be a trivial development.
Please, send us the source and we, or any of us will add (remove) this feature.

**Comment by drake1979** [comment]
> @drake1979 Thanks for the suggestion. This is there on our roadmap but I don't have exact timeline for this. We will keep you updated about this.

1 year have passed. Still no idea when this 2h development will be scheduled for release?
Postman was a very good tool, but instead of refining it You choose to stuff with all the bells & whistles most users do not need in most of their time. This screams for modularity...
But anyway, just put an if before keyboard event handlers please.

**Comment by numaanashraf** [comment]
This is related to #2707 and we are tracking progress and posting updates there. Closing this as duplicate.
