### ISSUE TITLE
I want to get the last href response from the response log

### ISSUE THREAD

**Issue by Architmantry** [a85/POSTMan-Chrome-Extension#3598]
I want to get the value for " "href": "https://fu"," from the response which is at the bottom of the response

 {
    "ImportActivityId": 300100112643991,
    "Name": "RevDemo",
    "Description": null,
    "ObjectCode": "Account",
    "AttachmentObjectCode": null,
    "DecimalSeparator": ".",
    "DateFormat": "ORA_ZCA_US_FORMAT",
    "ImportMode": "CREATE_RECORD",
    "TimestampFormat": "ORA_ZCA_US_FORMAT",
    "FileEncoding": "ORA_ZCA_UTF8_ENCODING",
    "Delimiter": "COMMA_DELIMITER",
    "NotificationEmail": null,
    "ImportMapping": null,
    "Schedule": "ONE_TIME_IMMEDIATE",
    "ScheduleTime": null,
    "Activate": "YES",
    "CreatedBy": "MHoope",
    "CreationDate": "2017-10-05T10:52:43+00:00",
    "LastUpdateDate": "2017-10-05T10:52:43.184+00:00",
    "LastUpdatedBy": "MHoope",
    "LastUpdateLogin": "5AB6A4D96AC04085E053470BF20AF403",
    "HighVolume": "NO",
    "DataFiles": [
        {
            "FileName": null,
            "Title": null,
            "Size": null,
            "Description": "User provided input data file",
            "InputFileContentId": "UCMFA00007278",
            "StartTime": null,
            "EndTime": null,
            "EstimatedCompletionTime": null,
            "Status": "ORA_MKT_QUEUED",
            "ReadFromFile": null,
            "LoadedSuccessfully": null,
            "SuccessReportContentId": null,
            "ErrorsReported": null,
            "Warnings": null,
            "ErrorReportContentId": null,
            "ExceptionReportContentId": null,
            "CreatedBy": "MHoope",
            "CreationDate": "2017-10-05T10:52:43.204+00:00",
            "LastUpdateDate": "2017-10-05T10:52:43.240+00:00",
            "LastUpdateLogin": "5AB6A4D96AC04085E053470BF20AF403",
            "LastUpdatedBy": "MHoope",
            "links": [
                {
                    "rel": "self",
                    "href": "https://fu",
                    "name": "DataFiles",
                    "kind": "item",
                    "properties": {
                        "changeIndicator": "ACED0005737200136A6176612E7574696C2E41727261794C6973747881D21D99C7619D03000149000473697A65787000000001770400000001737200116A6176612E6C616E672E496E746567657212E2A0A4F781873802000149000576616C7565787200106A6176612E6C616E672E4E756D62657286AC951D0B94E08B02000078700000000278"
                    }
                },
                {
                    "rel": "canonical",
                    "href": "https://fu",
                    "name": "DataFiles",
                    "kind": "item"
                },
                {
                    "rel": "parent",
                    "href": "https://f",
                    "name": "importActivities",
                    "kind": "item"
                },
                {
                    "rel": "lov",
                    "href": "https://f",
                    "name": "DataFilesStatusVA",
                    "kind": "collection"
                }
            ]
        }
    ],
    "links": [
        {
            "rel": "self",
            "href": "https://f",
            "name": "importActivities",
            "kind": "item",
            "properties": {
                "changeIndicator": "ACED0005737200136A6176612E7574696C2E41727261794C6973747881D21D99C7619D03000149000473697A65787000000001770400000001737200116A6176612E6C616E672E496E746567657212E2A0A4F781873802000149000576616C7565787200106A6176612E6C616E672E4E756D62657286AC951D0B94E08B02000078700000000378"
            }
        },
        {
            "rel": "canonical",
            "href": "https://f",
            "name": "importActivities",
            "kind": "item"
        },
        {
            "rel": "lov",
            "href": "https://f",
            "name": "ImportDelimiterLOV",
            "kind": "collection"
        },
        {
            "rel": "lov",
            "href": "https://fu",
            "name": "ImportAttachmentObjectsLOV",
            "kind": "collection"
        },
        {
            "rel": "lov",
            "href": "https://fu",
            "name": "ImportModeLOV",
            "kind": "collection"
        },
        {
            "rel": "lov",
            "href": "https://f",
            "name": "ImportFileEncodingLOV",
            "kind": "collection"
        },
        {
            "rel": "lov",
            "href": "https://f",
            "name": "ImportScheduleModeLOV",
            "kind": "collection"
        },
        {
            "rel": "lov",
            "href": "https://f",
            "name": "ImportMappingsLOV",
            "kind": "collection"
        },
        {
            "rel": "lov",
            "href": "https://f",
            "name": "ImportDecimalSeparatorLOV",
            "kind": "collection"
        },
        {
            "rel": "lov",
            "href": "https://fu",
            "name": "YESNOLOV",
            "kind": "collection"
        },
        {
            "rel": "lov",
            "href": "https://f",
            "name": "ImportTimeStampLOV",
            "kind": "collection"
        },
        {
            "rel": "lov",
            "href": "https://f",
            "name": "ImportDataFormatLOV",
            "kind": "collection"
        },
        {
            "rel": "lov",
            "href": "https://f",
            "name": "ImportObjectsLOV",
            "kind": "collection"
        },
        {
            "rel": "child",
            "href": "https://fu",
            "name": "DataFiles",
            "kind": "collection"
        }
    ]
}

**Comment by prashantagarwal** [comment]
@Architmantry I don't this this is an issue related to Postman. We use this Github repo to keep track of bugs and features. I think stackoverflow would be a better place for this question.
