### ISSUE TITLE
Enable suggestions for environment variables in url

### ISSUE THREAD

**Issue by tvvignesh** [a85/POSTMan-Chrome-Extension#3600]
## App Details:
```
Postman for Chrome
Version 5.2.1
linux / x86-64
Chrome 61.0.3163.100
```

## Feature Request:
When I type in the name of an environment variable in Headers, I get suggestions to add but if I try the same in the URL bar, the suggestions do not come up but the environment variable works. 

Would be a nice addition to provide suggestions in URL bar as well.

Great work by your team by the way with Postman and I am loving every minute of development with it. Cheers!

**Comment by bhawna2109** [comment]
@tvvignesh This is supported in the app - you need to type an open curly bracket to bring up the autocomplete in the URL bar.
![image](https://user-images.githubusercontent.com/14976346/31327543-a1d35444-aced-11e7-9c8c-eae91640f748.png)

**Comment by tvvignesh** [comment]
@bhawna2109 Oh! I dont know if this was newly implemented. My app updated and now, I am able to see this working. Will close this. Thanks :+1:
