### ISSUE TITLE
UI Enhancement:  Collapsible Sections

### ISSUE THREAD

**Issue by ivanbell2012** [a85/POSTMan-Chrome-Extension#3601]
## App Details:
```
Postman for Windows
Version 5.3.0
win32 10.0.14393 / x64
```
Could you please add an option to collapse the sections in the right section of the UI?  In order to maximize my results view, I used to choose "Authorization" tab in the 2nd vertical section (this yielded the most real estate in the results view).  With the current version (just updated today), it seems all of those tabs are now a fixed height and reduce my results visibility.

If you added a collapsible div to each section, it would allow me/us to view more of the results without having to scroll.

Thanks in advance.

**Comment by kamalaknn** [comment]
Hi @ivanbell2012

Thanks for your suggestion. We have tried our best to bring a lot of new enhancements to the Authorization tab and hence the difference in the new version. We'll try to optimize the view for response viewing.

For now, you can use our `Two Pane` view to split the request section into two and bring your response to your right. 

You can use the `cmd + opt + v`(if you are on macOS) or `ctrl + alt + v` shortcut or clicking on the following icon on the bottom right of the App to bring up the two-pane layout.

<img width="204" alt="screen shot 2017-10-06 at 11 29 36 pm" src="https://user-images.githubusercontent.com/8401064/31291857-d672ae30-aaee-11e7-9f1b-c3056b0ef0c5.png">

Hope this helps.

Thanks,

**Comment by arlemi** [comment]
Hey! 

We've pushed changes to the layout of the app in [Postman Canary](https://www.postman.com/downloads/canary/) which allow to collapse different section of the app as you please. Please try it out and let us know what you think either here or [on our community forum](https://community.postman.com/t/new-layout-in-postman-canary/13450). 

Here's a quick preview: 
![canary-sliding](https://user-images.githubusercontent.com/5029719/84889240-77ce2800-b090-11ea-9fd5-7a0bb38a094e.gif)

**Comment by coditva** [comment]
This is now available in Postman 7.28.0 as well 🎉
