### ISSUE TITLE
Suggestions create environment for parameters while body is json

### ISSUE THREAD

**Issue by wang6771264** [a85/POSTMan-Chrome-Extension#3607]
While request body is json or form, use environment varaible manage parameters!

{
  "orderId": 3240541, 
  "token": ${test_token}$, 
  "appCode": 101
}
instead of 
{
  "orderId": 3240541, 
  "token": "74972cb24c217c5fddf2b6eea0fb5e11", 
  "appCode": 101
}

Sorry, my English is bad, maybe you can't understand mine.

**Comment by prashantagarwal** [comment]
@wang6771264 If I understand this correctly, you want variable suggestion in raw body like we have in form-data or url. 
Or you just want to use variables inside raw body.
