### ISSUE TITLE
Convert it into a desktop app

### ISSUE THREAD

**Issue by tusharmath** [a85/POSTMan-Chrome-Extension#361]
Why don't we use [node-webkit](https://github.com/rogerwang/node-webkit) or [app.js](http://appjs.com/) for building up a user interface? 

It will look and feel much better and people who don't want to use chrome can also use it.

**Comment by a85** [comment]
We would be putting out a native version using Electron soon. Email us at help@getpostman.com to try it out.

**Comment by drywolf** [comment]
I am also looking for a native solution to be able to store postman files / workspaces in my local git repositories more easily.

Any news on the native electron version ? :smile: :+1:

**Comment by numaanashraf** [comment]
@drywolf We do have a native Electron app for Mac. You can find the download link [here](http://www.getpostman.com/apps).

**Comment by drywolf** [comment]
Thanks for the quick response ... I'm developing on Windows 10 though, do you have plans to release electron versions for Windows/Linux as well ?

**Comment by numaanashraf** [comment]
@drywolf Yep! They are in the works. 😃  Unfortunately we don't have an ETA for them yet.

**Comment by drywolf** [comment]
@numaanashraf Very cool, I'm looking forward to it :+1:

**Comment by drywolf** [comment]
Just for reference ... the Postman native app is now available for Linux:
http://blog.getpostman.com/2017/03/14/going-native/ :smile: 👍 

Any news on a Windows release ?

**Comment by czardoz** [comment]
@drywolf Windows has been available for a few months now, grab it here: https://www.getpostman.com/apps

**Comment by drywolf** [comment]
😏 Ow, I did overlook the big link in the header, just saw the options below for Chrome/Mac/Linux.
Nice, I'm looking forward to try it out over the weekend.

Thanks @czardoz 

UX-PS: maybe a more vibrant color for the download button in the header would make it more recognizable, I just visited the page in a hurry when I posted the above comment and I seriously overlooked it ☺️
