### ISSUE TITLE
Trello road map is very vague

### ISSUE THREAD

**Issue by Billy-** [a85/POSTMan-Chrome-Extension#3610]
Some extra information and notes on the cards in your Trello road map board would be very much appreciated. Just a short description perhaps and a link to somewhere to track in more detail (e.g GitHub Issue) the discussion and/or progress would be ideal.

Kind regards,
Bill

**Comment by prashantagarwal** [comment]
@Billy Thanks for pointing this out. We will get this updated soon. I am closing this issue as this is not a feature or bug related to postman app.
