### ISSUE TITLE
When I press on "Environment quick look" button, the application hangs

### ISSUE THREAD

**Issue by sdauwalder** [a85/POSTMan-Chrome-Extension#3612]
## App Details:

```
Postman for Windows
Version 5.3.0
win32 6.1.7601 / x64
```

## Issue Report:
When I press on "Environment quick look" button (the eye) the application hangs (consuming full CPU). I tried to reinstall, with no exit. Also happens in Canary version.
 1. Did you encounter this recently, or has this bug always been there: It appeared to me a few versions ago
 2. Expected behaviour: No hanging!
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app): Nothing shows up on DevTools
 4. Screenshots (if applicable)

**Comment by prashantagarwal** [comment]
@sdauwalder Thanks for reporting this. Just to debug this better, Can you let me know how many variables do you have in your Global variables and in the active Environment. Also can provide me a.
screenshot of devtools when you see this error.

**Comment by sdauwalder** [comment]
Thanks for answering. I have found the causing problem. I tried to look at the global variables, and it was impossible, everything was hanging. The issue was that I was saving a 2MB json in a global variable. That made it impossible to view the global variables. When I deleted it, everything worked fine again. 
So it is not actually an error, but maybe a improvement could be to show only partial info of big variables so that the viewer doesn't hang.

**Comment by prashantagarwal** [comment]
@sdauwalder Good to hear you were able to debug it. Actually the idea behind quick look was to provide users a way to see their actual variable values, but yeah we never made it to handle MB's of data. We are working on some improvements for Environment quick look, we will surely take into consideration there.
