### ISSUE TITLE
Leading whitespace in variable value isn't preserved when saving from bulk edit

### ISSUE THREAD

**Issue by kbuzby** [a85/POSTMan-Chrome-Extension#3613]
## App Details:

```
Postman for Chrome
Version 5.3.0
win / x86-64
Chrome 61.0.3163.100
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there: Encountered today and reproducible.
 2. Expected behaviour: If whitespace is entered in the value of the key-value pair in bulk-edit mode, it should be preserved.
 4. Screenshots (if applicable)
Existing environment variables:
![image](https://user-images.githubusercontent.com/2800467/31357745-a0be6d80-ad08-11e7-8461-d9a1e421d1fa.png)

Enter bulk-edit mode:
![image](https://user-images.githubusercontent.com/2800467/31357760-b4decb84-ad08-11e7-931c-ede699010c33.png)

Add another key with whitespace:
![image](https://user-images.githubusercontent.com/2800467/31357794-c9c8e7b4-ad08-11e7-8e7e-ef65e79a4057.png)

Go back to key-value edit mode and whitespace before BOTH values is removed:
![image](https://user-images.githubusercontent.com/2800467/31357820-e47661a4-ad08-11e7-8ee7-6b3aadcd5ca1.png)

This also happens when saving directly from bulk edit mode.

This makes copying key-value pairs in during bulk edit unusable if I want to preserve whitespace.

**Comment by prashantagarwal** [comment]
@kbuzby Thanks for reporting this. We will get this fixed in upcoming releases.

**Comment by prashantagarwal** [comment]
@kbuzby Do you have a specific use case for which you want this whitespace

**Comment by kbuzby** [comment]
Yes, the whitespace is part of the values for the variables for the application im testing. If I don't save the whitespace in the variable then I'll have to add it to the request body before the variable

Also, not only is it something I have a use case for, but the fact that I can save whitespace in the key-value edit mode, but not the bulk edit mode I think is the real problem. It'd be better if it was at least consistent.

**Comment by prashantagarwal** [comment]
@kbuzby This is fixed in our latest Postman app release.
