### ISSUE TITLE
JS in pre-request script does not work well

### ISSUE THREAD

**Issue by S0im** [a85/POSTMan-Chrome-Extension#3615]
Postman for Chrome
Version 5.3.0
win / x86-64
Chrome 61.0.3163.100

## Issue Report:

Creat a pre-request script like this: 
 `    var date = new Date();
    var month = date.getMonth() + 1;
    var strDate = date.getDate();
    if ( month <= 9) {
        month = "0" + month;
    }
    if (strDate <= 9) {
        strDate = "0" + strDate;
    }
    var var1 = "string" + date.getFullYear() + month + strDate;
    var var2 =  date.getFullYear() + month + strDate;
    postman.setEnvironmentVariable("VAR1",var1);
    postman.setEnvironmentVariable("VAR2",var2);`
Then use the 'VAR1' and 'VAR2' in the request,like this
![var](https://user-images.githubusercontent.com/25290478/31367940-1aa5e7e6-adad-11e7-920e-9f832489539f.jpg)
Send the request ,and check  'VAR1' and 'VAR2' 
![var2](https://user-images.githubusercontent.com/25290478/31367972-4c36ee9a-adad-11e7-9b2c-40c9b93cb0ff.jpg)
See the difference? The 'VRA2' does not work as I hoped, then I realise  it can also used like this ：
`var var2 =‘’ + date.getFullYear() + month + strDate;`
![tim 20171010112651](https://user-images.githubusercontent.com/25290478/31368063-f2e4a502-adad-11e7-8583-2299e3da56ad.jpg)

Please tell me whether this is a postman bug,or the  javascript'. 
Thank U.

**Comment by harryi3t** [comment]
@S0im This is just how javascript works.
You can try this in a node console
![image](https://user-images.githubusercontent.com/5207331/31375344-d75f120c-adbe-11e7-80a3-966f5eda4c6c.png)
