### ISSUE TITLE
When close the newopened postman window , all postman windows are gone...

### ISSUE THREAD

**Issue by S0im** [a85/POSTMan-Chrome-Extension#3617]
## App Details:

```
Postman for Windows
Version 5.3.0
win32 6.1.7601 / x64
```

## Issue Report:
Open a postman window from the OPEN NEW butten on the left top beside the Runner butten, then just close the new postman window, all your postman windows are gone......
![tim 20171010181015](https://user-images.githubusercontent.com/25290478/31381207-7316d78a-ade6-11e7-912f-70cf595726cd.jpg)

**Comment by prashantagarwal** [comment]
@S0im Thanks for reporting this issue. We are already tracking a similar issue #3222 .
