### ISSUE TITLE
DAV, cardDAV, calDAV request methods

### ISSUE THREAD

**Issue by sapiens-sapide** [a85/POSTMan-Chrome-Extension#3618]
## App Details:

```
Postman for Mac
Version 4.11.0
OS X 16.4.0 / x64
```

## Feature request:
I'm working on a cardDAV server implementation and I must be able to use DAV related verbs as the request methods : 
```
- REPORT
- MKCOL
- PROPATCH
- MOVE
```

**Comment by prashantagarwal** [comment]
@sapiens-sapide We are already tracking a similar issue #166 . Closing this as duplicate.
