### ISSUE TITLE
"Send as Basic Auth header" Client Authentication option should NOT include "client_id" in the POST body

### ISSUE THREAD

**Issue by neverendingqs** [a85/POSTMan-Chrome-Extension#3619]
## App Details:

```
Postman for Windows
Version 5.3.0
win32 10.0.14393 / x64
```

## Issue Report:
1. Did you encounter this recently, or has this bug always been there:
    - I encountered this recently.

2. Expected behaviour:
    - When `POST`ing to `Access Token URL`, if `Client Authentication` is set to `Send as Basic Auth header`, the `client_id` should **not** be included in the `POST` body.

3. Console logs:
    - **Form Data**
grant_type:authorization_code
code:auth-code.fboMj_ric3bxPn_U32DAzgXnKzcIsz4L2dnSXvJ-2vg
state:f23594b7-7fb1-42eb-abb9-852614dad4d6
**client_id:ec50b582-088b-478d-ba3d-3cbe325faa85**
redirect_uri:https%3A%2F%2Flocalhost%3A3001%2Fcallback

4. Screenshots (if applicable)
    - ![image](https://user-images.githubusercontent.com/8854618/31400357-48737cb4-adbd-11e7-805a-6b5041728aa8.png)

**Comment by neverendingqs** [comment]
Closing for now - looks like I missed the following and need to think on this:

>    A client MAY use the "client_id" request parameter to identify itself
>    when sending requests to the token endpoint.  In the
>    "authorization_code" "grant_type" request to the token endpoint, an
>    unauthenticated client MUST send its "client_id" to prevent itself
>    from inadvertently accepting a code intended for a client with a
>    different "client_id".  This protects the client from substitution of
>    the authentication code.  (It provides no additional security for the
>    protected resource.)
> ~https://tools.ietf.org/html/rfc6749#section-3.2.1

**Comment by kamalaknn** [comment]
@neverendingqs this part of the RFC is why we've included `client_id` in all token requests. However, we've seen some providers rejecting the token request authenticates using Basic auth header and sends `client_id` in the body, although the RFC allows it.
