### ISSUE TITLE
No longer finds session cookies since moving to a separate window

### ISSUE THREAD

**Issue by robvdl** [a85/POSTMan-Chrome-Extension#362]
I used to use Postman 0.8.x for our web app and really loved it.  We use a Django web app with TastyPie API and use session authentication (using a cookie coming from Django), so when logged into the Django web app you are also authenticated for the API.

Postman 0.8.x used to work fine as it picked up the session cookie when logged into our Django web app.

I decided to upgrade to Postman 0.9.x today and sadly can no longer use Postman now, as it can no longer authenticate our API as Postman can no longer find the session cookie from Django.

Postman now runs in a window rather than browser tab and it can no longer see the session cookie when I log into my site, so I am no longer able to use it.

Can we please add the ability to do session authentication again, either that, or add the ability to run it in a browser tab again as before.. so that the session cookie can be found.

**Comment by dlucian** [comment]
Not working. Turned on Interceptor, found the request in Postman's History. Replayed it. Got '401 Unauthorized back'. Have been going at it for 2 hours now. Good bye Postman.

**Comment by rohanBagchi** [comment]
It works. Just ensure that you have added the interceptor & the app to the correct chrome account. As in, I have two accounts: one for work & one for personal. I added the interceptor in personal and tried to use postman installed for work. You can check by going to chrome webstore from your browser window and searching for `Postman`. If it says `Added to chrome`, it means, you have it in your currently logged in account/profile. 
Now try looking to [Interceptor](https://chrome.google.com/webstore/detail/postman-interceptor/aicmkgpgakddgnaphhhpliifpcfhicfo).  Follow same procedure.
Turn on interceptor in your browser.
Open postman, and you should see a `Interceptor` button up top like this 
<img width="130" alt="screen shot 2017-03-08 at 4 08 18 pm" src="https://cloud.githubusercontent.com/assets/5557094/23700666/7f31adb4-0419-11e7-8418-c9a3648d2b25.png">
Switch it on and try to access protected URL after having logged in from browser.
It should work.

**Comment by eblanshey** [comment]
If I have multiple chrome profiles open, for example work and personal, and interceptor is installed on both, how does Postman decide which window's cookies to use?
