### ISSUE TITLE
Exporting a collection cleans body.file.src

### ISSUE THREAD

**Issue by TomONeill** [a85/POSTMan-Chrome-Extension#3621]
## App Details:
```
Postman for Windows
Version 5.3.0
win32 10.0.15063 / x64
```

## Issue
When having a file selected in the Body tab using binary data, this is what the exported Collection contains regarding the file:
```
"request": {
	"method": "PUT",
	"header": [],
	"body": {
		"mode": "file",
		"file": {
			"src": ""
              	}
	},
	"url": "anyurl"
}
```
Notice that request.body.file.src is empty. I read that this is normal (since it's not supported by Postman), but manually entering a file location like `"src": "./some.png"` works to be ran using _newman_.
However, when importing the file and then exporting it again, Postman clears the src part again, so I have to fill it in manually every time.

## Suggested solution
A quick solution would be to totally ignore `src`'s value, which would be acceptable at the moment.

A more complete solution would be to extract the location from the in Postman selected file and place it in the exported JSON. When importing the JSON, Postman could also look for the file using that location.

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:
To me it's always been this way.
 2. Expected behaviour:
See suggested solution.
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
Not important for this issue.
 4. Screenshots (if applicable)
Not applicable.

**Comment by TomONeill** [comment]
Any updates on this @kunagpal ?

**Comment by kunagpal** [comment]
Related to #3641

**Comment by harryi3t** [comment]
This is being tracked here https://github.com/postmanlabs/postman-app-support/issues/4320
