### ISSUE TITLE
Execution time display improvements

### ISSUE THREAD

**Issue by transome** [a85/POSTMan-Chrome-Extension#3624]
It would be nice to be able to see a running execution time during a call, instead of just waiting to see after the call finishes. It would also be nice to be able to display it in a more human readable format (aka minutes) and be able to copy the execution time.

**Comment by prashantagarwal** [comment]
@transome Thanks for the suggestion. Just out of curiosity what use you are trying to achieve. Generally response time for requests are in seconds. Also any particular reason you want to see running execution time here.

**Comment by transome** [comment]
For me the times are in milliseconds. I often start a long running api call, but forget to keep track of when I started it, and it would be useful to see how long it has gone for already in case it has gone for longer than expected, or just to have an idea of how long it has left to go. I often have to share execution times with other team members, and currently when I have to do this, I have to manually type in the displayed time in milliseconds (since I can't copy it), and then convert it to minutes.

**Comment by prashantagarwal** [comment]
@transome I think a better solution would be to add a test case for this scenario in user rest script.
Something like this 
```
var moment = require('moment');

pm.test("Response time is less than 200ms", function () {
    pm.expect(pm.response.responseTime).to.be.below(200);
});
```
So now you can very easily keep a check on your response times. Also you can use Moment.js in your test scripts, so you can convert this time into whichever format you like and log it in Postman console (from where it should be very easy to copy).
