### ISSUE TITLE
Collections Pane improvements

### ISSUE THREAD

**Issue by transome** [a85/POSTMan-Chrome-Extension#3625]
It would be nice to have a collapse all button, and be able to have more than one level of hierarchy.

**Comment by prashantagarwal** [comment]
@transome Are referring to the sidebar ?

**Comment by transome** [comment]
Yes, the collections pane on the left side.

**Comment by mbuquet** [comment]
I agree, I would love to have a "Collapse all collections/folders" button. I have a lot of collections and each with a lot of folders.

**Comment by prashantagarwal** [comment]
@transome @mbuquet Cool, thanks for the suggestion.

**Comment by a85** [comment]
Closing as a duplicate of https://github.com/postmanlabs/postman-app-support/issues/2657

**Comment by DataTeamITInternal** [comment]
The issue remains:

No way to Collapse "FOLDERS" in the collections pane.

You closed as duplicate however that ticket solved "TABS" not "FOLDERS"

Thanks
