### ISSUE TITLE
Console displays request body as "=undefined" string when viewed in "Raw" view

### ISSUE THREAD

**Issue by serkand** [a85/POSTMan-Chrome-Extension#3626]
## App Details:
Postman for Windows
Version 5.3.0
win32 10.0.15063 / x64

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:
Recently
 2. Expected behaviour:
Request Body is displayed correcly in raw view
3. Screenshots (if applicable)
![consolerawview](https://user-images.githubusercontent.com/22509908/31473940-5403cd4a-af43-11e7-9096-61db03e2b20b.jpg)

Steps:
1. Open the Postman Console
2. Send a Post http request with a body that is of RAW (JSON) format.
3. View the request in the Postman Console, first in "Pretty" view and then in "Raw" view.
4. Note the request body shows a string containing "=undefined=undefined=undefined=undefined=undefined=undefined......" etc

**Comment by sdnts** [comment]
@serkand Thanks for reporting this! I was able to reproduce this with a raw POST body, we'll get a fix out with an upcoming release, planned sometime next week.

**Comment by prashantagarwal** [comment]
@serkand This is fixed in 5.3.2. Please update your app and feel free to reopen the issue if you are still seeing this.
