### ISSUE TITLE
Easier to create collections for CRUD requests 

### ISSUE THREAD

**Issue by stsrki** [a85/POSTMan-Chrome-Extension#3628]
It would be great of there is an option to create collection based on the predefined template.
Right now I have collections for my APIs that have requests for create/get/getAll/update/delete. Every collection is defined for different model (Employees, Departments. Cities, ...) and almost all of them have the same structure. The problem is that when I need to add new collection for my model i need to duplicate it and then manually change every URL, every test case and parameters. I am already using environment variables and they help but not enough.

What I propose is something that will behave like "snippets" in programming languages where I define keywords that will be replaced with my own value. That way I can create "template collection" that will have parts of URL, param, tests and other things replaced with my own name.

**Comment by prashantagarwal** [comment]
@stsrki Thanks for suggesting this feature.

**Comment by a85** [comment]
We will support this using more extensive schema languages. More detail in other issues that we are tracking here.
