### ISSUE TITLE
Bulk Reordering

### ISSUE THREAD

**Issue by Nuluvius** [a85/POSTMan-Chrome-Extension#3629]
## App Details:
```
Postman for Windows
Version 5.3.0
win32 10.0.15063 / x64
```

## Issue Report:
I can't seemt to find a way to reorder a number of requests beyond drag & drop. This causes significant inconvenience if there's lots of similar requests.

For example, when recording a user's workflow through a site and then wanting to replay this later: If one saves the requests to a collection and then replays this it will play the requests in the wrong order.

Sorting chronologically or even a simple select a number of requests and reverse the order would be nice.

**Comment by prashantagarwal** [comment]
@Nuluvius Thanks for suggesting this feature.

**Comment by giridharvc7** [comment]
Closing this ticket as this feature is now available in Postman. You can read more about it [here](https://blog.postman.com/introducing-sidebar-bulk-actions/)
