### ISSUE TITLE
Issues with version 5.2.1  - Request payload keep changing to the previously saved request after saving the response.

### ISSUE THREAD

**Issue by malyalal** [a85/POSTMan-Chrome-Extension#3630]
Once a request is sent and the response is saved, the request is not available to resend again. 
Then clicking back on the request will remove the saved request payload
## App Details:

```
Postman for Chrome
Version 5.2.1
OS X / x86-64
Chrome 61.0.3163.100
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there: **In this version of postman.**
 2. Expected behaviour: **Option to "Resend" the request without clicking back button after saving the response.**

## Steps to reproduce the problem
1. Create a Post request with a request body then click send
2. Click to save the response
3. Try to resend the request by changing any value in the request body.
-->

**Comment by prashantagarwal** [comment]
@malyalal Currently we don't allow to send the saved Examples. This behaviour might change in future.

**Comment by malyalal** [comment]
@prashantagarwal, you got me wrong!! I am not trying to send the saved example but trying to resend the same original request once again after saving the response

**Comment by piyushkantm** [comment]
Any Update on this?

It would be nice to save request also while saving examples as it makes more sense

**Comment by RaffaeleSgarro** [comment]
So how do we do it in Postman?
