### ISSUE TITLE
Feature Request: Enable Send and Download in Runner

### ISSUE THREAD

**Issue by andymcf** [a85/POSTMan-Chrome-Extension#3633]
## App Details:
Mac Version 5.3.0 (5.3.0)

## Feature Request

I'd like to be able to use the Send and Download option from within Runner

**Comment by prashantagarwal** [comment]
@andymcf Thanks for suggesting this feature. Any particular use case you are trying to achieve through this feature ?

**Comment by andymcf** [comment]
I wanted to be able to save the response from the runner

**Comment by a85** [comment]
You can copy/paste the response from the body. We'll have more features around this announced when we do a new version of the runner.

**Comment by dnet5** [comment]
Hi @a85 it kinda solves the problem, but only if you test few requests...

**Comment by toucedam** [comment]
I would love to have this feature. I need to attach the evidence of the runner at Jira and I need to log more  than 300 requests. Is there a way I can do that?
