### ISSUE TITLE
Content-Type always set to text/html.

### ISSUE THREAD

**Issue by cpironmo** [a85/POSTMan-Chrome-Extension#3636]
Postman for Mac
Version 5.3.0
OS X 17.0.0 / x64

## Issue Report:
 1. I believe I've only begun to encounter this since I installed a recent update.
 2. When I set a header Key: Content-Type Value: application/json I expect to see this in the results Header section after sending my POST request. However it always remains as Content-Type: text/html; charset=utf-8. This prevents my node API using the bodyParser nom package from receiving/interpreting the req.body object at it only recognises it as undefined.

To reproduce simply attempt to send a POST request to an endpoint setting a header Key Content-Type Value application/json, and add a validated json object into the raw section of the body tab. Then send the request.

In the results check the Headers and not the Content-Type isn't application/json but is text/html charset=utf-8.

**Comment by prashantagarwal** [comment]
@cpironmo I just tried this and I am correctly getting the application/json in the response header
<img width="1120" alt="screen shot 2017-10-16 at 10 52 31 pm" src="https://user-images.githubusercontent.com/3762808/31625780-f4e4140c-b2c4-11e7-9715-d250e82955ec.png">

Just to get back response content-type as application/json you should send a valid json in response or specifically set response header as application/json from your server.

> This prevents my node API using the bodyParser npm package from receiving/interpreting the req.body object at it only recognises it as undefined.

To debug it  better can you paste a screenshot of the request that you are making.

**Comment by CharlesIrvineKC** [comment]
@prashantagarwal, I am having this same problem. I am returning JSON from my mock. What do you mean by "specifically set response header as application/json from your server"?

**Comment by deepakpathania-zz** [comment]
@ChuckIrvine For mocks, you need to explicitly set the response header as `application/json`. What I mean by that is, than in your example that you're saving, you'll have to specify the response header in the headers tab of the example response. Here's how it looks in the app. 

![screen shot 2018-08-21 at 6 19 04 pm](https://user-images.githubusercontent.com/15071438/44402290-f1695d80-a56e-11e8-8a4d-69b65a41c5e6.png)

**Comment by CharlesIrvineKC** [comment]
Very cool, Deepak. I had the setting on top but not the one on the bottom. Things are working correctly now! Thanks for the quick and excellent response. 

By the way, the last time I used Postman was a couple of years ago. You guys have improved it immensely!

Thanks again for your help.

Chuck

**Comment by kokkonda-abhilash** [comment]
Thanks for the solution @deepakpathania I've faced the same issue and your solution helped me resolve the issue 👍
