### ISSUE TITLE
Postman callback url not in authentication helper

### ISSUE THREAD

**Issue by ronaldsalas** [a85/POSTMan-Chrome-Extension#3637]
## App Details:

```
Postman for Mac
Version 5.3.0
OS X / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there: No

Before version 5.3.0, the Postman callback url can be found and can be copied when trying to get a OAuth2 access token thru the authorization helper. But I can't find it now. Can we find it somewhere else in Postman? The callback url field is blank when I open it. 

When trying to setup the integration with other apps, often it is needed to enter the callback url first before getting the Client ID and Client Secret.  And it would be convenient to be able to copy the Postman url from Postman itself. 

Or maybe I am missing something?

**Comment by kamalaknn** [comment]
Hi @ronaldsalas,

In the `5.3` version of Postman we've removed the restriction on callback URLs, i.e. you can enter any value in the callback URL input. This is because not every user has control over changing the callback URLs the can register with the identity providers.

So you can use any URL in the callback URL input, as long as it matches with the one you have registered with the identity provider. In fact, Postman does not actually wait for the response from the callback URL, so it can be a non-existent URL like `http://localhost/` in order to make sure your access tokens are safe.

Hope this clarifies. 
Thanks

**Comment by ronaldsalas** [comment]
Thanks @kamalaknn I understand why you need to remove the restriction. But does that mean we can't use the old Postman callback url anymore? Which is (after some googling.....) https://www.getpostman.com/oauth2/callback. 

Or that, we have to take note of this url on our own as we won't find this url displayed in the app anymore? And if we do want to use it, we have to enter it on the field? (I can save it as a environment variable, I know, but still it means it's on-us now to make sure you have that url saved somewhere). 

Sorry, just trying to understand the extent of the change. Because before, when I needed to get the Postman callback url before, I just open Postman, go to the authentication helper and copy it from there. Now, I have to search for it in the internet or make a note on a Post-It on what the url is... or make sure that I have a callback_url variable in my environment with the right url.

**Comment by kamalaknn** [comment]
I understand your thoughts. Usually, you should be able to get the callback URL from your the identity provider settings where you've registered your OAuth 2 application(where you would find your client id and client secret).

Like this for GitHub.
<img width="577" alt="screen shot 2017-10-16 at 11 35 48 pm" src="https://user-images.githubusercontent.com/8401064/31627621-7ff00ea6-b2cb-11e7-9bb2-8a3bac747975.png">

If you feel the need to keep a note of the callback URL you can put it on your environment or global and use it in the form for getting a new OAuth 2.0 token.

Now that Postman allows you to enter any callback URL, I would suggest you use something you can keep in mind like `https://localhost/`.

**Comment by ronaldsalas** [comment]
ok, thanks @kamalaknn
