### ISSUE TITLE
Sort order in docs does not match sort order in application

### ISSUE THREAD

**Issue by GuyPaddock** [a85/POSTMan-Chrome-Extension#3643]
## App Details:

```
Postman for Chrome
Version 5.3.0
win / x86-64
Chrome 61.0.3163.100
```

## Issue Report:
This is the first time I've encountered this issue.

### Steps to Reproduce the Problem
1. Create a collection.
2. Add some requests to the collection.
3. Clone some of the requests in the collection and give the clones new names.
4. Drag and drop some of the clones to the top of the list of requests.
5. Re-arrange a few of the other requests.
6. Export documentation.
7. Compare the order that that requests appear in the collection to the order they appear in the docs.

### Expected Results
The requests are ordered the same in the application as they are in the documentation.

### Actual Results
The requests are not in the same order in the documentation as they are in the application:
#### Application
![image](https://user-images.githubusercontent.com/2631799/31635150-ce35cb42-b293-11e7-806b-d268cb71c6f3.png)
#### Documentation
![image](https://user-images.githubusercontent.com/2631799/31635216-0242e9ec-b294-11e7-8b4b-c20972f8c14e.png)

**Comment by GuyPaddock** [comment]
As a workaround, this works:
1. Re-order requests in the order you want them in the docs.
2. Export the collection to JSON.
3. Delete the collection inside Postman.
4. Import the collection from the exported JSON file.
5. Generate docs.

I'm guessing that the order requests appear in docs is based on some internal "insertion order" / "creation order" that Postman is tracking for the items. When a collection is exported to JSON, the order of the requests in the JSON follows the order that the requests appear on-screen. So, if my theory is correct, when you delete a collection and re-import it, you're forcing the "insertion order" to match the sort order because the file you're importing adds the requests in the order you sorted them before export.

**Comment by prashantagarwal** [comment]
@GuyPaddock Thanks for reporting this. We are looking into this issue.

**Comment by a85** [comment]
@GuyPaddock Are you still seeing the issue? We had pushed an update to fix this.

**Comment by harryi3t** [comment]
@GuyPaddock This appears to be fixed so I am closing this issue. If not, feel free re-open the issue.
