### ISSUE TITLE
Numbers in .csv are not send correct when  use Runner

### ISSUE THREAD

**Issue by S0im** [a85/POSTMan-Chrome-Extension#3644]
## App Details:
```
Postman for Chrome
Version 5.3.0
win / x86-64
Chrome 61.0.3163.100
&
Postman for Windows
Version 5.3.0
win32 6.1.7601 / x64
```

## Issue Report:
Numbers in .csv are not send correct when I use runner . Here is the numbers in my .csv:

num1,num2,num3
1,1,1
10,10,10
01,01,01
02,02,02

This is  the preview in the runner of Postman for Chrome:
![1](https://user-images.githubusercontent.com/25290478/31650642-ec72986c-b34a-11e7-8217-2de152e0f6ba.jpg)
And here is the preview in the runner of Postman for Windows:
![2](https://user-images.githubusercontent.com/25290478/31650863-e514c38c-b34b-11e7-9e82-b43d535a755d.jpg)

**The "01"s and "02"s have been changed !** 

And maybe I have the same  issue with this guy, #3576

**Comment by prashantagarwal** [comment]
@S0im Thanks for reporting this. We are already tracking a similar issue #2734 . I am closing this as duplicate issue.
