### ISSUE TITLE
Auth1.0 - Add authorization to Request Header

### ISSUE THREAD

**Issue by qarinaflavia** [a85/POSTMan-Chrome-Extension#3647]
I used for my request OAuth1.0 and I would add the authorization to the header. After I updated to the new version (5.3.0) my requests don't work anymore. I get error: Invalid login attempt. I want to specify that my requests were working correctly before. The only change was to update the Postman.

What could cause this?

**Comment by kamalaknn** [comment]
@qarinaflavia could you make sure the `Timestamp` and `Nonce` fields are empty in your `Authorization` tab?

If left empty Postman will fill in auto-generated values for the fields. I am guessing there are stale values in those fields that are used for authorization.

If removing those fields do not help please share a screenshot of you Authorization tab and the Postman Console(`View -> Show Postman Console`) for the failed request so we can take a look.

**Comment by Viacheslav-Romanov** [comment]
The same thing. Return an update button!

**Comment by kamalaknn** [comment]
@Viacheslav-Romanov the older versions of the app would add `Timestamp` and `Nonce` every time you did `Update Request`. In the new version, Postman would use whatever the values you've entered. It will generate values internally if the fields are left empty.

Removing the fields should make the send work. If you have any particular use for the `Update Request` we'd love to hear.

**Comment by qarinaflavia** [comment]
Thank you for suggestion. I had to clear Timestamp and Nonce and it worked.

**Comment by Viacheslav-Romanov** [comment]
Are you gonna to explain it everyone who uses a new version?
