### ISSUE TITLE
postman vs pm - is postman getting deprecated?

### ISSUE THREAD

**Issue by vdespa** [a85/POSTMan-Chrome-Extension#3648]
There are now **two ways to work with variables**, for example: `postman.getEnvironmentVariable("foo") ` and `pm.environment.get("foo")`. **Same goes for `tests`**, old style vs `pm.test`.

I have recently noticed that the snippets panel has changed and uses the pm version to work with variables / tests. 

I am a bit confused, because the documentation is out-of-sync with the actual product. Is the old style getting deprecated or something?

**Comment by kamalaknn** [comment]
Hi @vdespa, 

The `pm.*` API is new and we are adding new features to it. We are slowly moving our documentation to the new API, and the first step is the update to snippets in the Postman App.

There are a few features on `postman.*` for which no alternative exist on `pm.*` like `postman.setNextRequest`. We'll put out a notice for `postman.*` deprecation once `pm.*` is feature complete.

That being said, if you are not relying on functions like `postman.setNextRequest` it is advisable to move to the `pm.*` now.

Thanks!

**Comment by mattdeluco** [comment]
Is the updated documentation available for perusal?

**Comment by shamasis** [comment]
The [docs](https://www.getpostman.com/docs/v6/postman/scripts/postman_sandbox) would remove `postman.*` right after postman-runtime 8.0 release which implements a variant of `postman.setNextRequest`.

cc @loopDelicious
