### ISSUE TITLE
Increase size / Ability to resize URL Parameter Values

### ISSUE THREAD

**Issue by karthicraghupathi** [a85/POSTMan-Chrome-Extension#365]
Greetings!

Great job so far. This is more of a feature request than a bug.

It would be great if you can increase the size of the URL parameter values or at least provide the ability to re-size them. As you can see from the screenshot below, there is a lot of room left and it can be put to use.

![postman](https://f.cloud.github.com/assets/1508545/1150511/0126ed46-1eec-11e3-902c-f1d9396a717c.png)

**Comment by a85** [comment]
Coming up in version 3.0 in a couple of weeks!

**Comment by krumax** [comment]
bam ... great!
