### ISSUE TITLE
UI controls/editors do not regain focus along with main window after upgrade to 5.3.1

### ISSUE THREAD

**Issue by tsantzi** [a85/POSTMan-Chrome-Extension#3651]
## App Details:

```
Postman for Linux
Version 5.3.1
linux 4.9.0-3-amd64 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:
Issue appeared after upgrading to 5.3.1
 2. Expected behaviour:
When the main window looses focus, and then regains it (e.g. with ALT-TAB), the last-focused widget in the window should be focused.

Steps to reproduce the problem:

1. Use/focus any control in Postman main window, e.g. the body editor
2. ALT-TAB to another application
3. ALT-TAB back to Postman: control does not have focus (so e.g. can't use CTRL-ENTER without clicking on the editor again)

**Comment by SamvelRaja** [comment]
Thanks for bringing this to our notice, we shall look into and update the status here.

**Comment by mattboothman** [comment]
This is also an issue on Windows 10: Postman v5.3.1

**Comment by sdnts** [comment]
Hi @tsantzi @mattboothman We released 5.3.2 which has a fix for this, can you try updating and confirming it works correctly now?

**Comment by tsantzi** [comment]
Hi @madebysid I can confirm that 5.3.2 fixes this bug in Linux, many thanks!

**Comment by mattboothman** [comment]
Hey, thanks for the speedy response. I can confirm this is now fixed on Linux for 5.3.2. I will check Windows later.
