### ISSUE TITLE
Using .not causes other tests to fail. 

### ISSUE THREAD

**Issue by EricWafford** [a85/POSTMan-Chrome-Extension#3652]
## App Details:

```
Postman for Mac
Version 5.3.0
OS X 10.13.0 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there: **Recently**
 2. Expected behaviour: using .not.be in test sandbox should not cause issues with other tests elsewhere.
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app): Nothing Found.
 4. Screenshots (if applicable)
![screen shot 2017-10-18 at 10 30 50 am](https://user-images.githubusercontent.com/19695455/31727602-a1c938fc-b3ef-11e7-968f-46f2bad67e49.png)

**Steps to reproduce the problem**

Using a simple call to the echo service, and a test example taken directly from https://www.getpostman.com/docs/postman/scripts/postman_sandbox_api_reference

When using .not.be in a test, subsequent tests fail, even though they should not. It seems to spill over the "not" aspect into other tests, as seen in the assertion error expecting it to "not" be 200.

**Comment by prashantagarwal** [comment]
@EricWafford closing this as duplicate. We are already tracking it here #3592
