### ISSUE TITLE
Please change the font 

### ISSUE THREAD

**Issue by xutl** [a85/POSTMan-Chrome-Extension#3653]
Please change the font under the Windows version, in the non-English display, very small, or even see, such as Chinese。

**Comment by deepakpathania-zz** [comment]
Hey @xutl 
While I am not sure whether you can change the font itself but you can definitely change the font size in the settings modal if it seems too small to you. Find below a picture for your reference. 

![selection_008](https://user-images.githubusercontent.com/15071438/31760882-c60551c6-b4d3-11e7-8c8c-9c85a4dbb56d.png)

More on this here : https://www.getpostman.com/docs/postman/launching_postman/settings

**Comment by xutl** [comment]
@deepakpathania You said that the solution can not solve the problem.

![111](https://user-images.githubusercontent.com/20939388/31803476-84ef250a-b586-11e7-98dd-a3f54247f4ab.png)

**Comment by deepakpathania-zz** [comment]
@xutl Not sure what you mean by that. I simply meant that I was not sure about updating the font itself but the font size can be easily updated through the settings modal if you wish so.

**Comment by xutl** [comment]
@deepakpathania Setup mode can not update the font in the tab, and the default font for the software is not friendly to Chinese.

**Comment by prashantagarwal** [comment]
@xutl You can use `Cmd + '+'` to Zoom in. This will help you to see the small font better.

**Comment by xutl** [comment]
![111](https://user-images.githubusercontent.com/20939388/31939427-ef05e71c-b8ec-11e7-913c-4a04da97484c.png)



@prashantagarwal The method will enlarge the font as a whole。You can compare Chome version and App version。

**Comment by xutl** [comment]
![111](https://user-images.githubusercontent.com/20939388/31939435-f649daec-b8ec-11e7-90e8-366957092737.png)

**Comment by prashantagarwal** [comment]
@xutl I am still not sure what you are expecting here. I can see your windows version in zoomed out, which can be increased using the method I mentioned above.

**Comment by DoveAz** [comment]
I have same problem 
![image](https://user-images.githubusercontent.com/15158280/32093454-ea269b26-bb2e-11e7-985f-eea12f3562ec.png)
color too light ,  we need a option to change font

**Comment by DoveAz** [comment]
see  active tab 

![image](https://user-images.githubusercontent.com/15158280/32093822-5c858d34-bb30-11e7-8a5f-5011a86f8a43.png)

word in the active tab not clear

if add font-size in css 

![image](https://user-images.githubusercontent.com/15158280/32093847-6e49627a-bb30-11e7-884a-630a167c385d.png)

we need  options to change tabs  fong-size  and change font , default font display is bad ..... microsoft is good

**Comment by HudsonAfonso** [comment]
+1
"we need options to change tabs fong-size and change font, default font display is bad"

**Comment by virmundi** [comment]
To chime in, I think you need to globalize the font settings. I upgraded to Ubuntu Bionic Beaver. Now the menu bar is wonky. I tried to see which font was used in the Dev Tools, but I think that setting is outside the scope of that tool.
![postmanfontrenderingissue](https://user-images.githubusercontent.com/1041487/40123223-b85a2fd2-58f3-11e8-820b-272ccb843955.png)

**Comment by amleaver** [comment]
+1, I've also just upgraded to Ubuntu 18.04 and have the same issue. Changing the "Editor Font Size" has no impact on the fonts used in the toolbar menu.

![image](https://user-images.githubusercontent.com/535721/40299476-46937fcc-5cde-11e8-899b-03ce0ed6cab9.png)

**Comment by prashantagarwal** [comment]
@amleaver Can you share your current Postman app version

**Comment by amleaver** [comment]
@prashantagarwal that was on 6.0.10 however I upgraded to 6.1.2 this morning and can confirm that the issue I reported 2 days ago has been fixed and fonts are now readable. Thanks for reminding me to try updating!

**Comment by virmundi** [comment]
Same for me. Fonts look great now.

**Comment by vkaegis** [comment]
Great to hear! Let us know if you find any other issues around this. Going forward, we want to make much of the UI as customizable as possible, giving you greater flexibility around individual font sizes. No ETA on this just yet, but stay tuned!

**Comment by seyoatda** [comment]
3 years passed, still can't find any UI font settings. The UI is ugly. I should admit that the abilities of Postman is good enough, but many user couldn't bear the ugly UI. Is adding some UI customization settings so hard? I don't think you care about the user experience.
