### ISSUE TITLE
Hope that environment variables can be associated with collections

### ISSUE THREAD

**Issue by xutl** [a85/POSTMan-Chrome-Extension#3654]
I hope that the environment variable can be associated with the set, so that you can set a custom environment variable for each collection, in the development environment, pre-environment, and online environment can easily switch a unified URL constant

**Comment by xutl** [comment]
It is possible to set an environment that belongs only to the collection

**Comment by deepakpathania-zz** [comment]
Duplicate of #2876. 
Follow #3205 for the roadmap. 
Read about managing environments here https://www.getpostman.com/docs/postman/environments_and_globals/manage_environments

**Comment by cauvery-guda-eb** [comment]
Looking forward for this change, badly need this.

**Comment by prashantagarwal** [comment]
Closing this as duplicate of #2876
