### ISSUE TITLE
Error while sending request: Failed to execute isetRequestHeader on IXMLHttpRequest: 'User-Agent:' is not a valid HTTP header field name. 

### ISSUE THREAD

**Issue by apoorv-yadav** [a85/POSTMan-Chrome-Extension#3658]
Hi, 

I have been working on Tickspot API (https://github.com/tick/tick-api/blob/master/sections/roles.md) and recently I have started facing an issue regarding headers which says :  **Failed to execute isetRequestHeader on IXMLHttpRequest: 'User-Agent:' is not a valid HTTP header field name.**

BUT when I used cURL, it worked fine with no issues. So, pls help and suggest a solution and cause of issue in postman.

## App Details:
Postman for Chrome
Version 5.3.1
win / x86-64
Chrome 62.0.3202.62
```


## Issue Report:
 1. I started facing this issue a few days back
 2. Expected behaviour: No error should have come
 3. Screenshot
![postman issue](https://user-images.githubusercontent.com/32958271/31822268-d6319170-b5c5-11e7-9c41-e42c6a0ceb5f.png)

**Comment by prashantagarwal** [comment]
@apoorv-yadav I can see there is a `:` in User-Agent header. Also I would recommend you to move to native app rather than using Chrome App.

**Comment by apoorv-yadav** [comment]
@prashantagarwal when I remove the **:** chrome app gives error.

But when I tried in postman's native app then it worked. THANKS MAN FOR YOUR HELP!!
