### ISSUE TITLE
Postman support SOCKS proxy

### ISSUE THREAD

**Issue by fostec82** [a85/POSTMan-Chrome-Extension#3659]
## App Details:

```
Postman for Mac
Version 5.3.1
OS X 10.12.6 / x64
```

Trying to route Postman native app through a SOCKS proxy setup via ssh.  For example:

~$ ssh -D 33333 user@myserver.com

Leveraging simple curl commands works as expected

~$ curl --proxy socks5h://localhost:33333 "http://url-to-call-on-myserver.com"

However (I think as expected) the SOCKS proxy/tunnel does not work in Postman Native app.

![screen shot 2017-10-20 at 9 26 20 am](https://user-images.githubusercontent.com/21953364/31823041-bedc31f8-b578-11e7-9e1d-01b28261b3ff.png)

The PostMan system level proxy setting works, but do not need to route all my machines traffic through the SOCKS proxy.

Is there a way to fix this or is there a roadmap item to consider adding this support?

**Comment by prashantagarwal** [comment]
@chrifost We are already tracking this issue #1321  . I am closing this as duplicate.
