### ISSUE TITLE
Open postman on tab instead of window

### ISSUE THREAD

**Issue by ianpogi5** [a85/POSTMan-Chrome-Extension#366]
Developers already have a lot of windows to switch to. Postman just added another one. Previous versions open on on tab and it was great. 

Maybe a extension option to open in tab or window would be better.

**Comment by Drachenfels** [comment]
@jtremback Postman Rest Client is still in chrome web store (at least for Ubuntu 14.04 and Chrome 41), so there is no problem with installing and using it.

**Comment by blabno** [comment]
+1 for postman in tab

**Comment by chorsnell** [comment]
+1 in a tab, really not sure why its forcing its own window, terrible UX decision in an otherwise fantastic add on

**Comment by shkm** [comment]
+1 in tab. Terminal -> alt+tab -> chrome -> refresh -> dammit, it's postman again.

**Comment by a85** [comment]
@shkm We have been combing issues on Google Code and fix for this should be coming soon from Google. They had to refactor the entire windowing system for Mac.

**Comment by shkm** [comment]
Awesome to hear, @a85. Thanks :-).

**Comment by pleerock** [comment]
+1 for tab

**Comment by marcellodesales** [comment]
:+1: Tabs!

**Comment by matejvelikonja** [comment]
:+1:

**Comment by zsf3** [comment]
+1 for tabs.

**Comment by tucq88** [comment]
+1 for Tab. It's more perfect if there's an option for deciding Tab or Window.

**Comment by mbiersdo** [comment]
+1 for Tab

**Comment by ababeel** [comment]
+1 for Tab

**Comment by besir** [comment]
+1 for tab

**Comment by fizerkhan** [comment]
+1 for tab

**Comment by a85** [comment]
This is not coming any time soon folks. Please use the Mac app: www.getpostman.com/apps. Other native versions coming soon.

**Comment by lpil** [comment]
:+1:

**Comment by Malet** [comment]
:+1:

**Comment by paivaric** [comment]
+1

**Comment by kpfgmaur** [comment]
+1

**Comment by helloeve** [comment]
+1 for tab

**Comment by ricardo-rossi** [comment]
+1

**Comment by itailulu** [comment]
+1

**Comment by jvosantos** [comment]
+1

**Comment by skozz** [comment]
+1

**Comment by stevenhornung** [comment]
+1

**Comment by ssonibj** [comment]
+1

**Comment by ghost** [comment]
The only thing i cannot understand is why it's blocked to not open as a separate application just like other extensions:

![screen](https://cloud.githubusercontent.com/assets/13694007/14618194/aa035e96-05b1-11e6-9e20-3a39fd0d00f4.png)

As you can see there is no chrome windows, feedly has icon group in menu on it's own. Postman, instead, opens as one of chrome windows (under it's icon group in menu). It's very annoying.

Anyway, opening postman as a separate window should be still an option, even it's get back to open as tab by default.

Not everybody is tied by any legacy cookie based authentication for api - and in case of token based authentication separate window is absolutely the best.

**Comment by teaboxshiv** [comment]
+2

**Comment by rivierasolutions** [comment]
+3 So annoying

**Comment by a85** [comment]
Postman is available as a Mac app at www.getpostman.com/apps. A Windows app is going to be out pretty soon. Linux is in the works too. We can't put Postman in a tab because of restrictions of the Chrome platform.
