### ISSUE TITLE
Connect firebase with authentication

### ISSUE THREAD

**Issue by cicerocruz** [a85/POSTMan-Chrome-Extension#3660]
I'm trying to connect to Firebase with Bearer authentication, I'm not understanding how to do it ...

Rule in Firebase:
{
   "rules": {
     ".read": true,
     "users": {
       "$ uid": {
         ".write": "$ uid === auth.uid"
       }
     }
   }
}

**Comment by prashantagarwal** [comment]
@cicerocruz We use this repo to track issues and features related to Postman app. I think you might get better help in our slack community or StackOverflow.
