### ISSUE TITLE
Feature Request: Private documentation

### ISSUE THREAD

**Issue by mattcanty** [a85/POSTMan-Chrome-Extension#3663]
We use Postman across our development teams, however I fear that documentation may accidentally be published. At this time it would mean that the our documentation would be public.

We'd like a way of allowing developers to click "publish" safe in the knowledge that it will only be available to the team.

**Comment by prashantagarwal** [comment]
@mattcanty Thanks for suggesting this feature.

**Comment by vkaegis** [comment]
@mattcanty Thanks for writing in! Private documentation within the team is available through the "View in Web" button in the desktop app, and by clicking on a collection name in the web app. If a collection has been shared in a team workspace, everyone in the team can automatically access it's documentation this way. Does this solve your use case?  

Public documentation is meant specifically for public consumption.

**Comment by sankalp0o** [comment]
Hi @mattcanty, like @vkaegis mentioned, 'Publish' is only for making the documentation available for public consumption. Your team would be allowed to view the documentation for any shared collection without needing to 'Publish'. I'm closing this for now, let me know if this does not cover your feature request.

**Comment by scriptsure** [comment]
@a85 is there any progress having a single user name and password or bearer token that could be used to secure the docs? We are a commercial healthcare (i.e. HIPPA) company and do not want to share docs with everyone.

**Comment by karthiks3000** [comment]
I created a tool that generates an html documentation from a postman collection. I then host the html on a private network just for our internal users. Hope this helps

https://github.com/karthiks3000/postman-doc-gen
