### ISSUE TITLE
Ctrl+Shift+N should do not open a new collection runner window

### ISSUE THREAD

**Issue by midrissi** [a85/POSTMan-Chrome-Extension#3665]
## App Details:

```
Postman for Windows
Version 5.3.1
win32 6.1.7601 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:

**Encountered recently**

 2. Expected behaviour:

**Ctrl+Shift+N should open a new postman window**

 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):

**No Logs**

 4. Screenshots (if applicable)

**No screenshots**

1. Press **Ctrl+Shift+N**
2. The collection runner is opened instead of a postman window.

**Comment by deepakpathania-zz** [comment]
Hey @midrissi , that is intentional. You might want to do **Ctrl+N** for a new Postman window. Refer to the shortcuts tab in the settings modal for more information. Image attached for reference. 

![selection_011](https://user-images.githubusercontent.com/15071438/31953100-f18908da-b8ff-11e7-893b-a83d07c8470e.png)

More on this here. https://www.getpostman.com/docs/postman/launching_postman/navigating_postman

**Comment by midrissi** [comment]
Hey @deepakpathania . As you can see in the attached image that you have sent, Ctrl+Shift+N should  open a new postman window. But it opens the collection runner instead! :( 

The same shortcut is shown in the main view:

![postman](https://user-images.githubusercontent.com/3237344/31954198-36c39fca-b8e5-11e7-85e2-446213a4cd97.PNG)

Thanks.

**Comment by deepakpathania-zz** [comment]
@midrissi Totally missed that, you're right. Also, **Ctrl+SHift+R** doesn't seem to open the runner window either. 
@kunagpal Please have a look.

**Comment by sdnts** [comment]
@midrissi Hey, just chiming in to let you know that I've verified this is indeed a bug on Windows (only on Windows I see), we'll get this fixed as soon as possible.

**Comment by deepakpathania-zz** [comment]
@madebysid I was able to replicate this on the Linux app as well.

**Comment by sdnts** [comment]
@midrissi @deepakpathania We released 5.3.2 which has a fix for these issues on Windows and Linux, can you update and confirm it is fixed?

**Comment by deepakpathania-zz** [comment]
@madebysid Fixed in the Linux app.

**Comment by midrissi** [comment]
@madebysid Fixed in windows too :+1: 

![bitmoji](https://render.bitstrips.com/v2/cpanel/7834193-282480426_5-s1-v1.png?transparent=1&palette=1&width=246)
