### ISSUE TITLE
Postman sending GET over POST when query string is present

### ISSUE THREAD

**Issue by williamokano** [a85/POSTMan-Chrome-Extension#3666]
## App Details:

```
Postman for Chrome
Version 5.3.1
linux / x86-64
Chrome 61.0.3163.100
```

## Issue Report:
Everytime I choose POST method but I do have some query string parameter, it send GET as method instead of POST, even with POST selected.

**Comment by prashantagarwal** [comment]
@williamokano I was unable to reproduce this. Could you provide a screenshot of Network tab inside chrome devtools when you make this request. Folllow these steps.
- Open Chrome Devtools in your Postman app.
- Select Network tab.
- Make your POST request
- See that the request shows up in your Network tab.
- Click on the request to see details and take the screenshot of it.

**Comment by prashantagarwal** [comment]
@williamokano Also if it is possible for you, could you switch to our native apps and try running your request there.
