### ISSUE TITLE
Feature Request: Add ability to define required/optional fields/headers and field types

### ISSUE THREAD

**Issue by govindrai** [a85/POSTMan-Chrome-Extension#3668]
Postman Documenter is a lifesaver. However, when trying to create complete documentation, something that will be very helpful is having the ability to define which fields/headers are required or optional and the type of field that will be required. I know this can be specified in the description, but it is not ideal. :)

Here are the columns I am proposing for headers:
KEY | VALUE | DESCRIPTION | OPTIONAL

Here are the columns I am proposing for request bodies:
KEY | VALUE | TYPE | DESCRIPTION | OPTIONAL

Here's a screenshot of an API documentation I found was easy to navigate and might be good for inspiration: 
<img width="922" alt="screen shot 2017-10-24 at 3 04 09 pm" src="https://user-images.githubusercontent.com/13859249/31971449-c005b8f0-b8d0-11e7-96a5-04fedb0abcbf.png">

**Comment by prashantagarwal** [comment]
@govindrai We have reopened #3117 . I am closing this one so that we can easily track this feature. This will be automatically linked to #3117 which will make sure your inputs are considered when we work on this feature.
Again, Thanks for suggesting this feature.

**Comment by ParthivSavani** [comment]
@govindrai Nice!. How to add this in my existing API collection? @a85

**Comment by shashankawasthi88** [comment]
Hi All,

We are happy to announce the launch of [Types in Collections](https://community.postman.com/t/the-postman-drop-design-sync-and-manage-apis-without-the-switching-tax/78684#p-129904-create-error-free-api-experiences-with-type-validation-3) for all users. This will give you the ability to define required/optional fields/headers and field types.

Please reach out to us if you have any feedback!
