### ISSUE TITLE
[Feature Request] Rename variable reference within a collection

### ISSUE THREAD

**Issue by drahnieR** [a85/POSTMan-Chrome-Extension#3669]
## App Details:

```
Postman for Chrome
Version 5.3.1
win / x86-64
Chrome 61.0.3163.100
```

## Issue Report:
So consider I got an API collection from App1 and another collection from APP2. Both collections uses client_id, client_secret for oauth.
But I'm actually working at a bigger scope which coordinate both apps. I don't really want to duplicate a lot of common variables into 2 environments, and switch back and forth.
So instead of creating 2 environment for each of them, I might want to rename all variable reference within one of the collection and make them peacefully in one environment.

Any idea?

**Comment by prashantagarwal** [comment]
@drahnieR If I got your question right, your referring something like Find & Replace. We are actively working on this feature and as a result of which we already have `Find` functionality out in our native apps. In coming releases we will introduce `Replace` as well, using which you can replace all instances of the searched string with a single click. But yeah, again, this only available in our native apps.

Then for now what you can do is easily find all the request which uses that variable and change that variable manually. 

Also as a workaround what you can do is export this collection, open the exported file in an editor, do find and replace using that editor and then import back this file in postman.

**Comment by drahnieR** [comment]
@prashantagarwal Thanks for the quick response. That really sounds good to me.
I've already worked around it the same way you mentioned ;)
cheers

**Comment by prashantagarwal** [comment]
@drahnieR Great !!

**Comment by jjsty1e** [comment]
Hi @prashantagarwal , how's this going now?

**Comment by ptrkstr** [comment]
@prashantagarwal would really love this future, hope it's still in development!

**Comment by feeeper** [comment]
> @prashantagarwal would really love this future, hope it's still in development!

It's already done as I can see. You can open `Find and Replace` panel with `Ctrl+Shift+F` (on Windows).
