### ISSUE TITLE
Ability to export environments

### ISSUE THREAD

**Issue by chinmay185** [a85/POSTMan-Chrome-Extension#367]
Just as we export collections and can import them on another system, it would be good to export environments so that they can be imported on other systems. Without this feature I currently have to recreate all the environment variables on other machine manually.

**Comment by curtisgibby** [comment]
+1 for uploading to getpostman.com

**Comment by intraz** [comment]
+1 for uploading to getpostman.com

**Comment by bowofolaf** [comment]
+1 for sharing variables!

**Comment by bowofolaf** [comment]
But before that can we have an export all/some feature and the ability to import multiple environments from one file?

**Comment by abhijitkane** [comment]
@bowofolaf You can download all your data (collections+environments+globals) and import in another app.`Settings>Data>Download/Import`.

**Comment by rhpatel99** [comment]
+1 For for uploading to getpostman.com

**Comment by vpavliuk-diosoft** [comment]
Hi all, i have next question:
If i want run posman collection from newman with environments. When i run just one file newman cant see url (http://prntscr.com/bkk49t)
 How i can do that? 
I have try export Backup.postman_dump.json and run in to newman, but no action (http://prntscr.com/bkk49t)
