### ISSUE TITLE
Problem with pm instance

### ISSUE THREAD

**Issue by ibnbd** [a85/POSTMan-Chrome-Extension#3670]
I am using most recent standalone version of Postman. I have some Pre-Request-Script.

```
pm.globals.set
pm.sendRequest
```

Which works perfectly on my MacBook every times I try. But on my windows computer sometimes it's working sometimes giving this error : `There was an error in evaluating the Pre-request Script: pm is not defined`.

I doubt Postman sometimes fails to load all dependencies, is there any other explanation for this?

Thank You

**Comment by prashantagarwal** [comment]
@ibnbd By any chance are you using chrome app on your Windows computer. `pm` is only available for our native apps.

**Comment by ibnbd** [comment]
@prashantagarwal no I am using 64bit windows standalone version. Version 5.3.1, which I downloaded again yesterday. It worked after installation, now saying pm is not defined.

**Comment by prashantagarwal** [comment]
@ibnbd Can you provide me the screenshot of the whole app when the error occurs.

**Comment by ibnbd** [comment]
@prashantagarwal 

This is a successful call : https://imgur.com/ITGXiCZ

This is error : https://imgur.com/WmUCn56

**Comment by ibnbd** [comment]
@prashantagarwal
I have the standalone version, which I downloaded from : 
https://dl.pstmn.io/download/latest/win64

**Comment by prashantagarwal** [comment]
@ibnbd Definitely the error one is the Chrome app. By any chance do you have both native and chrome app on your Windows. If you are using some utility (like Spotlight Search in mac) that might be unable do differentiate.

**Comment by prashantagarwal** [comment]
@ibnbd Open your chrome browser and type `chrome://apps/`
If you see postman, remove it from there.

**Comment by ibnbd** [comment]
@prashantagarwal I don't have Chrome app version of Postman. Only standalone version.

**Comment by ibnbd** [comment]
@prashantagarwal  thanks, my MacBook didn't had Chrome app but windows computer did.

**Comment by prashantagarwal** [comment]
Cool, closing this issue now.

**Comment by junaidaion** [comment]
thanks @prashantagarwal .

Open your chrome browser and type chrome://apps/

it worked for me
