### ISSUE TITLE
Postman crashes since last Chromium update

### ISSUE THREAD

**Issue by mrbinr** [a85/POSTMan-Chrome-Extension#3671]
## App Details:
```
Chromium Version 62.0.3202.62 (Build officiel) Built on Ubuntu ,
running on Ubuntu 16.04 (64 bits)
Postman Version : 5.3.1
```

## Issue Report:
Since this morning, after having  updated Chromium as usual when system asks to do it, when i launch Postman, splash screen is displayed, after few seconds it close and then notification appears «Postman has crashes, click on notification to start again».

**Comment by mrbinr** [comment]
Here is logs from syslog : 

> Oct 25 09:43:29 ME dbus[903]: [system] Activating via systemd:
    service name='org.bluez' unit='dbus-org.bluez.service'
Oct 25 09:43:29 ME dbus[903]: [system] Activation via systemd failed
    for unit 'dbus-org.bluez.service': Unit dbus-org.bluez.service not found.
Oct 25 09:43:29 ME chrome-fhbjgbiflinjbdggehcddcbncdddomop-Default.desktop[12169]:
    ATTENTION: default value of option force_s3tc_enable overridden by environment.
Oct 25 09:43:29 ME chrome-fhbjgbiflinjbdggehcddcbncdddomop-Default.desktop[12169]:
    [12169:12169:1025/094329.942372:ERROR:display_info_provider_aura.cc(31)]
    Not implemented reached in virtual void extensions::DisplayInfoProviderAura::
    UpdateDisplayUnitInfoForPlatform(const display::Display &,
    extensions::api::system_display::DisplayUnitInfo *)
Oct 25 09:43:36 ME chrome-fhbjgbiflinjbdggehcddcbncdddomop-Default.desktop[12169]: #
Oct 25 09:43:36 ME chrome-fhbjgbiflinjbdggehcddcbncdddomop-Default.desktop[12169]: # Fatal process OOM in heap setup
Oct 25 09:43:36 ME chrome-fhbjgbiflinjbdggehcddcbncdddomop-Default.desktop[12169]: #
Oct 25 09:43:36 ME kernel: [ 4559.324670] traps: DedicatedWorker[12446] 
    trap invalid opcode ip:555f4e3fc7df sp:7f04857f6f78 error:0 
    in chromium-browser[555f49f1b000+8012000]

**Comment by mrbinr** [comment]
Standalone Postman works, but Chrome extension not.

**Comment by deepakpathania-zz** [comment]
Hey @mrbinr, Chromium has actually indicated they will be fully deprecating chrome apps in the second half of 2017, therefore, I highly recommend using the native Linux app for your usage.[ Here](https://blog.chromium.org/2016/08/from-chrome-apps-to-web.html) is the article for your reference.

**Comment by mrbinr** [comment]
@deepakpathania thanks for your answer, and it's what i've done... i've removed Chromium app and installed native linux app to be able to continue my job :)
