### ISSUE TITLE
How to extract data from the postman results of response, and extract the data output to the file Note: the result of response is XML format

### ISSUE THREAD

**Issue by chenlei354** [a85/POSTMan-Chrome-Extension#3672]
How to extract data from the postman results of response, and extract the data output to the file
Note: the result of response is XML format

**Comment by prashantagarwal** [comment]
@chenlei354 you get request response as `responseBody` in `Test scripts`. Now what you can do is create a local server and expose a `POST` endpoint and then, using [pm.sendRequest](https://gist.github.com/madebysid/b57985b0649d3407a7aa9de1bd327990) call this POST endpoint with the `responseBody` as data. Also this is one [blog post](http://blog.getpostman.com/2017/09/01/write-to-your-local-file-system-using-a-postman-collection/) for some inspiration.
