### ISSUE TITLE
Collection browser in runner window scrolls up when you open a collection

### ISSUE THREAD

**Issue by chrisron95** [a85/POSTMan-Chrome-Extension#3673]
## App Details:
```
Postman for Mac
Version 5.3.1
OS X 17.2.0 / x64
```

## Issue Report:
_Please note, this is a very minute issue. It's not overly important, just a bit annoying._
 1. Did you encounter this recently, or has this bug always been there:
This started sometime within the last few updates, not sure exactly when but it was fairly recent.
 2. Expected behaviour:
When using the collection browser in the runner window, as you go into a collection, it should be scrolled all the way to the top. However, it usually scrolls down just past the first item in the collection.
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 4. Screenshots (if applicable)
![screen shot 2017-10-25 at 11 56 53 am](https://user-images.githubusercontent.com/16259311/32008948-a0a45416-b97b-11e7-9d95-a585d9278e97.png)
This is where it automatically scrolls to anytime I click on a collection.

Open a new runner window and start navigating through collections. You should notice that every time you go into a collection, it's not scrolled to the very top.

**Comment by sdnts** [comment]
@chrisron95 I was able to replicate this. The scroll position is persisted when you go through collections, we'll push out a fix for this with the next release. Thanks for reporting!

**Comment by a85** [comment]
Seems to be fixed in the latest release.
