### ISSUE TITLE
UI Imporvement for dual-pane layout

### ISSUE THREAD

**Issue by wkuckro** [a85/POSTMan-Chrome-Extension#3674]
## App Details:
```
Postman for Mac
Version 5.3.1 (5.3.1)
OS X 10.12.6 (16G29)
```

## Issue Report:
Improvement: I'd like the UI elements here to be lined up together when viewing side-by-side. You can see there are two different layout styles specifically for the `JSON` dropdown

![image](https://user-images.githubusercontent.com/16108658/32016668-22d63090-b98a-11e7-94f1-5e5c198f1901.png)

**Comment by sdnts** [comment]
Hi @wkuckro! Are you talking about the `JSON (application/json)` dropdown on the left?

**Comment by wkuckro** [comment]
Either or. Basically, these elements don't line up Consequently a request body and response body that are identical in terms of length are offset and that is visually disruptive

**Comment by vkaegis** [comment]
@wkuckro It's been a while but we've been working on some major changes to the infrastructure of how tabs are represented. Expect to see some visual improvements around this in the coming versions!

**Comment by coditva** [comment]
The layout has been improved in the latest Postman app 7.28.0 🎉 

![image](https://user-images.githubusercontent.com/8445768/88019533-a6d03180-cb47-11ea-930c-5a4ffabab3cb.png)
