### ISSUE TITLE
While running test cases from CSV file, can I tell postman to skip certain cases?

### ISSUE THREAD

**Issue by maissom-abbasi-confiz** [a85/POSTMan-Chrome-Extension#3675]
## App Details:

```
Postman for Mac
Version 4.11.0
OS X 16.4.0 / x64
```

## Question: While running test cases from CSV file, can I tell postman to skip certain cases?

So I have a bundle of test cases maintained in a CSV file format. Is there a way to tell postman runner to skip a test case based on a particular field in the CSV file. For example If I want to add a column "Execute" and it has associated values "Yes/Skip" for al the test cases and in my pre-request script, I do something like:

If(data.execute != "Yes"){

pm.setNextRequest();
}

Did anyone encounter a similar situation and worked it out? Many thanks!

Best,

**Comment by sdnts** [comment]
@maissom-abbasi-confiz Do you use the new `pm` API to write your tests? If so, what you can do is  add a conditional assert inside your `pm.test` block.
Even if you use the `tests` object, you should still be able to populate a test key conditionally.

So it would look something like:

```
pm.test('test name', function () {
    pm.response.to.have.body("response_body_string");
    if (!data.skip) {
        pm.expect(pm.response.responseTime).to.be.below(200);
    }
})
```

or

```
tests['always runs'] = true
if (!data.skip) {
    tests['runs sometimes'] = false
}
```

Please feel free to reopen if I misunderstood :)

**Comment by maissom-abbasi-confiz** [comment]
Hi @madebysid ,

I did not quite understand the solution.

Let me try to walkthrough by my scenario.

I have a CSV file with 16 rows of test data permutation against a single API call. I intend to add another column (say "execute" that has values "Yes/Skip". Can I control the execution of running the suit by adding a check in pre-request script that just altogether skips the iteration if the "data.execute" is set to "Skip". (Note data is that pm object for the input csv/json file we provide in the Runner screen).

p.s. I read on some other thread that "setNextRequest("request_name") basically does not skip the current iteration (Makes sense, as it is already inside that iteration execution). It basically allows to jump to a particular request. Since I have only one request, which is tested for different test cases, it won't be a solution for me. Basically I am trying to skip an iteration.

Hope it clarifies. Many thanks!
