### ISSUE TITLE
Postman Nonce 

### ISSUE THREAD

**Issue by Elektra-2** [a85/POSTMan-Chrome-Extension#3678]
Hello,

The API I am using the consume service using Postman only accepts nonce in numbers. 
Is it possible to change this on the settings as postman only creates nonce in numbers and letters? 

thanks,

**Comment by kamalaknn** [comment]
@Elektra1 Could you share the Authentication Type you are using? 

In general, Postman has an option for you enter your values for any of the fields that you want to override. So you should be able to enter any `nonce` in the advanced section and it should just work. Could you check that?
