### ISSUE TITLE
Blank window after duplicate username error

### ISSUE THREAD

**Issue by glenwinters** [a85/POSTMan-Chrome-Extension#3679]
## App Details:

```
Postman for Windows
Version 5.3.2
win32 10.0.15063 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there: I saw this on first install of Postman.
 2. Expected behaviour: I'm not sure what it's supposed to do, but perhaps it should prompt for a new username since the one I gave was taken.
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 4. Screenshots (if applicable)

I briefly saw an error message about the username already existing and then the whole window went blank except for the menu.

![image](https://user-images.githubusercontent.com/435066/32059327-a1e6c822-ba20-11e7-86c5-0650762f2a76.png)

1. Start app for the first time after install
2. Login with Google
3. After being prompted to enter a username for the account, type in an account name that happens to already exist.

**Comment by prashantagarwal** [comment]
@glenwinters Thanks for reporting this.

**Comment by thecuriousdev** [comment]
@glenwinters, Can you update the postman app to the latest version (6.1.2+), and please let us know if you are still facing the issue.

**Comment by glenwinters** [comment]
@thecuriousdev No issues after the update.

**Comment by thecuriousdev** [comment]
@glenwinters Perfect! I'll close the issue for now, feel free to reopen if you face any issues.
