### ISSUE TITLE
AWS Authorization header for uploading binary file calculated incorrectly

### ISSUE THREAD

**Issue by d-shenoy** [a85/POSTMan-Chrome-Extension#3680]
## App Details:

```
Postman for Mac
Version 5.3.2 (5.3.2)
OS X 10.12.6 (Sierra)
```

## Issue Report:
 
 <?xml version="1.0" encoding="UTF-8"?>
<Error>
    <Code>XAmzContentSHA256Mismatch</Code>
    <Message>The provided 'x-amz-content-sha256' header does not match what was computed.</Message>
    <ClientComputedContentSHA256>e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855</ClientComputedContentSHA256>
    <S3ComputedContentSHA256>1c0847b15dc11be65c0003b5d56592c6664a00341d0c3bb0583f3df1a3842f68</S3ComputedContentSHA256>
    <RequestId>F141EF1C2F292B67</RequestId>
    <HostId>k9oySDdjJBPS94pYEEUiYkibfk2v9VpHzoHw08ULPH+U3GwyFyDY1IoAm9PJ7BCHc5R7265KWCE=</HostId>
</Error>

Method: PUT
Body: binary - image(png)
=================
Region: us-east-1
Service: s3
================

**Comment by prashantagarwal** [comment]
@d-shenoy Thanks for reporting this.

**Comment by harryi3t** [comment]
@d-shenoy We have already received this bug report here https://github.com/postmanlabs/postman-app-support/issues/3232

You can upvote that issue, and subscribe to it for updates :)
