### ISSUE TITLE
Console errors in documentation on custom domain

### ISSUE THREAD

**Issue by hongaar** [a85/POSTMan-Chrome-Extension#3681]
## App Details:
```
n/a
```

## Issue Report:
On a custom documentation domain, I get a bunch of these errors in the console:

```
Refused to load the font 'data:font/woff;base64,...' because it violates the following Content Security Policy directive: "font-src https: 'self' *.getpostman.com fonts.gstatic.com fonts.googleapis.com".
```

and

```
button.js:1 Refused to apply inline style because it violates the following Content Security Policy directive: "style-src https: 'self' *.getpostman.com *.pstmn.io fonts.gstatic.com fonts.googleapis.com". Either the 'unsafe-inline' keyword, a hash ('sha256-...'), or a nonce ('nonce-...') is required to enable inline execution.
```

**Comment by godfrzero** [comment]
This isn't a bug, per-se. The first set of CSP errors will show up if you have extensions running which inject any kind of code into the page. We can't turn off CSP, so there's really nothing we can do here.

It should be noted that these errors don't get in the way of any functionality.

**Comment by hongaar** [comment]
@godfrzero this has nothing to do with running extensions injecting code; you're setting a CSP policy in your response headers and that policy is being violated by your own scripts.

1. the documentation page (button.js) is trying to run this code:

```
injectCriticalStyles: function(L) {
   M.document.getElementById(L) || document.body.insertAdjacentHTML("afterbegin", i.criticalCss)
},
```

2. the server which generates the document sends along this header:

```
content-security-policy: default-src https: 'self' *.getpostman.com; font-src https: 'self' *.getpostman.com fonts.gstatic.com fonts.googleapis.com; frame-ancestors 'none'; img-src * data:; script-src https: 'self' 'unsafe-inline' *.getpostman.com *.pstmn.io www.google-analytics.com www.googletagmanager.com; style-src https: 'self' *.getpostman.com *.pstmn.io fonts.gstatic.com fonts.googleapis.com;
```

These two are not compatible.

I understand this doesn't affect functionality, but it's still a (minor) bug as your code tries to accomplish something and now this will never be achieved since it's not executed by the browser.

The first error seems to be gone now btw.

**Comment by godfrzero** [comment]
@hongaar That particular part of the script is blocked by CSP _by design_. It's coming from an independent module, namely the Postman Run Button, and the injection of the critical CSS should actually be blocked in this particular case.

As for the font loading, that could be cause by any number of external sources. My guess was an extension, but again, that was a guess.

**Comment by hongaar** [comment]
That explains it then. I'm sure there could be some debate whether violating CSP by design is a good idea, but I'll leave that up to you. ;)
