### ISSUE TITLE
Postman Proxy HTTPS certificate errors

### ISSUE THREAD

**Issue by ygeelen-tb** [a85/POSTMan-Chrome-Extension#3682]
I'm experiencing the exact same issue as this guy:
https://stackoverflow.com/questions/41078313/using-postman-as-proxy-for-android-phone-certificate-error
I’m also trying to record HTTP requests done on my Android tablet.
Do you have any idea why I’m getting certificate errors? I tried disabling SSL verification in the Postman settings also.

**Comment by jeubank12** [comment]
I have similar issue, I am watching this bug: [3631](https://github.com/postmanlabs/postman-app-support/issues/3631)

**Comment by gabrielmcv** [comment]
The apps for Chrome: Postman and Interceptor worked like a charm, now, with the native, the main function was lost.

**Comment by chughmayank** [comment]
Hey @ygeelen-tb ! Could you please confirm if you are still facing this issue?

**Comment by ygeelen-tb** [comment]
@chughmayank I no longer have that proxy setup, it's been too long sorry.. :-D

**Comment by chughmayank** [comment]
@ygeelen-tb It looks to be fixed and I am marking this issue as Closed. However, please feel free to Reopen the ticket if you face the same issue :)
