### ISSUE TITLE
Error: The request body must contain the following parameter: 'client_secret or client_assertion'.  

### ISSUE THREAD

**Issue by JurgenPostelmans** [a85/POSTMan-Chrome-Extension#3685]
Hi,

I'm trying to get an access token using Azure AD for the Microsoft Power BI REST Service or Dynamics 365. When I fill in the details about the Token Request and execute it, I get the following response in the console:

The request body must contain the following parameter: 'client_secret or client_assertion'.
 Trace ID: d04b3b58-8deb-42da-9869-d70bfdab2a00
 Correlation ID: 73e48134-84b0-4983-9f89-17ed170cf50b
 Timestamp: 2017-10-27 10:35:53Z

If i have a look at the raw request in the console I can see that parameters like redirect_uri, grant_type, client_id are present but not the client_secret? 

POST /common/oauth2/token
content-type: application/x-www-form-urlencoded
authorization: Basic MDUzMTk5MTEtYjczMy00M2ExLWFjYjAtMWQ2MzVkZTE1OTI3OnFuOEZTbkhkaUlaaUd6YWxXaWU3TmVMbk5WbTJUR0dXUlRjTUxEQXdMc3lFPQ==
user-agent: PostmanRuntime/6.4.1
accept: */*
host: login.microsoftonline.com
accept-encoding: gzip, deflate
content-length: 716
grant_type=authorization_codecode=AQABAAIAAABHh4kmS_aKT5XrjzxRAtHztxSNsyDPFQ9knffdH44Y4b9LI4ci-Tf4bKn-D8AcVLSGpXtfxph3-YqnK-kwUsSSpEooH_fFO7C0oZZK324q9hpFt1LF-_ShqsuzF1q2iBZxZKKNnFt7JSXtH7PQt3AkP_jW7-B6d5annOZJ0opxJayDyqfHPI8vZBItqKTnnkX2-DPZ54VgZENVFTaLV5SvzrvWUj-69oK-bYxB3uTQI1Q311w0InESDLj1yUXyyIvmifhx_ALD6LApDKqwtLgLn2d-k4Y0InxS1-qI5tuOp_b-etn3dquL0TnStqVB2qEOM3c4SCVJIVS0Fnzp9pjklEh7BGiZS8Ke_I52QImpf9fWjc7ilr3-0J-QJJRruNYy4mV8I2hr-IXmS_6epP4qqU-x4UQzxX49d8Cbck6hrZFIr8e3F_UstDZQbaLFxlVixII-Bct5_sBamTWcGZn_UeuIMgDCpU8sGmlxSxzhvMk98uzPQ2sDGWeoq5G5YW998Yok9X5hIuYI4sNO68SRdl4uc02akKtVsV7GxS_3hCAAredirect_uri=https://www.getpostman.com/oauth2/callbackclient_id=05319911-b733-43a1-acb0-1d635de15927

**Comment by JurgenPostelmans** [comment]
And one more thing I noticed is that when I make exactly (!) the same token request using on old Postman V5.2 running on windows, it works without any issues!

**Comment by JurgenPostelmans** [comment]
Upgraded my Windows Postman client app, and now it showing the same behavior. So it is still an issue...

**Comment by oumiller21** [comment]
Same issue here

**Comment by kamalaknn** [comment]
@JurgenPostelmans Azure AD Token request expects `client_secret` to be in the request body. The default is to send them as `Basic Authorizorization Header`. 

**Switching the `Client Authentication` to `Send client credentials in body` should fix it.** 

In versions older than 5.3 Postman would send the credentials in request body, that wasn't ideal for all users. So we've changed this behavior to give more control to the user. The new defaults work for most of the providers. This explains why this used to work in 5.2 and not in 5.3.

I'm closing this issue, feel free to leave a comment if it doesn't work, I'll take a look.
