### ISSUE TITLE
Saving two examples in one tab after each other

### ISSUE THREAD

**Issue by sepehrr** [a85/POSTMan-Chrome-Extension#3689]
## App Details:

Postman for Mac
Version 5.3.2 (5.3.2)
OS X 

## Issue Report:
I make a request and click on "save response" and save it as an example with the title I want. that's fine.  now I change the request and click send and then I try to save new response as new example, but I can't change the example title to what I want, it's not editable, it's read only. 

PS. If I close tab and select request from my collection to open it in new tab I can save new response with my desired title.

**Comment by prashantagarwal** [comment]
@sepehrr That's odd. We were unable to reproduce this at our end. We will investigate more.
