### ISSUE TITLE
pm.response.to.not.be causes later assertions to work backwards.

### ISSUE THREAD

**Issue by lippsm** [a85/POSTMan-Chrome-Extension#3690]
## App Details:
Postman for Windows
Version 5.3.2
win32 10.0.15063 / x64

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there: I'm new to the program, so I'm not sure if this has been existing behavior. The code I was using, however, was found in an example in the 'Test Scripts' section of the getpostman website. I took out a lot of the fluff from the code to illustrate the problem.
 2. Expected behaviour: 
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 4. Screenshots (if applicable)

Steps to reproduce the problem:
1. Create a Get request for postman-echo.com/get
2. Add the following code for Tests:

```js
// example using response assertions
pm.test("Response should not be error", function(){
    pm.response.to.not.be.error;
});

// example using pm.response.to.be
pm.test("Response must be valid", function(){
    pm.response.to.be.ok;
});

// why does this pass? this shouldn't pass...
pm.test("Body is correct", function(){
    pm.response.to.have.body("egads");
});
```

3. Click Send.
**First test passes, as expected. Second test fails, though it shouldn't. Third test passes, but it should fail.**

**Comment by prashantagarwal** [comment]
@lippsm Can you try this out with the latest Postman v6.1.2
Thanks

**Comment by lippsm** [comment]
I tried it with the latest version and it appears to be working as expected now.

**Comment by prashantagarwal** [comment]
Awesome.

**Comment by GrzegorzPi** [comment]
I can not confirm  for:

Version 6.1.2
win32 10.0.16299 / x64

Tests from above:
1) pass - ok
2) fali - wrong
3) pass - wrong


And my example also fail:

```
// should pass
pm.test("Body is correct before", function(){
    pm.response.to.have.jsonBody('pagination');
});

// should pass
pm.test("Response should not be error", function(){
    pm.response.to.not.be.error;
    
});
//should pass
pm.test("Body is correct after", function(){
    pm.response.to.have.jsonBody('pagination');
});
```

first and third tests are the same, but only first pass

**Comment by egccir** [comment]
I've had intermittent issues with this in v6.1.3.  But for me it seems to be related to whether the returned results are syntactically-correct JSON or not.  That doesn't make much sense, but there it is.

**Comment by anna-seredinskaya** [comment]
The issue is back... Exact same reproduction steps as described by the original author of this issue.
Postman version: v6.7.0-canary01
OS version: Windows10 Home Edition version 1803, x64

**Comment by abhijitkane** [comment]
This is being tracked at https://github.com/postmanlabs/postman-app-support/issues/3592
