### ISSUE TITLE
Improved Folder Handling

### ISSUE THREAD

**Issue by cawoodm** [a85/POSTMan-Chrome-Extension#3693]
Like many other people I am responsible for multiple systems with multiple environments. Say you have 3 systems and each has DEV, TEST, PROD you have 9 systems and I manage these via folders currently (maybe there's a better way and I'd be glad to hear it).

The problem with folders is that when you search it searches across all folders and expands all of them. This is a pain when you have the same term (e.g. a noun) in every folder. You end up continuously collapsing folders every time you search.
![image](https://user-images.githubusercontent.com/498834/32159321-54de5934-bd4d-11e7-93d3-d22f7a52277a.png)

So I would suggest:
1) Would be nice to search in a folder OR
2) Would be nice to no automatically expand folders when searching but keep them as the user has them. Collapsed folders can show how many results they contain in their subtitle.
3) Perhaps there could be a cooler way of swapping environments (similar to the "All, Me, Team" tabs above)
4) As a developer it's common to focus only on one system and wish to hide the others for a while. Maybe folders can be "pinned" or "muted" somehow like layers in Photoshop

**Comment by prashantagarwal** [comment]
@cawoodm Thanks for the suggestion. I think your use case could be better handled by using [Environment variables](https://www.getpostman.com/docs/postman/environments_and_globals/manage_environments).

So you can move all your environment dependent things (urls, tokens etc) to specific environments and then use variables. This will save you from the trouble of maintaining separate requests.

**Comment by cawoodm** [comment]
Yep, that does indeed work well. Still not convinced the search should expand everything though.

**Comment by prashantagarwal** [comment]
@cawoodm Yes, that's a good suggestion. Also we introduced `Find` feature in our native apps. You can try that as well to search inside you request, collections, etc.

**Comment by prashantagarwal** [comment]
@cawoodm Yes in that ticket Examples are referred as saved responses.
