### ISSUE TITLE
Equals sign dropped from request in postman collection runner

### ISSUE THREAD

**Issue by agaitaud** [a85/POSTMan-Chrome-Extension#3698]
## App Details:

```
Postman for Windows
Version 5.3.2
win32 6.3.9600 / x64
```

## Issue Report:
 1. Issue with Collection runner in Postman for Windows application, where character = is dropped from certain requests. I never had this issue with Postman Chrome extension, and only ran into it when when switching to Postman for Windows. Equals sign is dropped when either at the end of a request, or when surrounded by non-url encoded special characters (spaces, 
 2. Expected behavior: I expect the entire content of a saved request to be executed when using collection runner. Special characters should not need to be url encoded unless the target rest api needs it.
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 4. Screenshots (if applicable) !([equals sign being dropped] https://user-images.githubusercontent.com/33237723/32199558-44cd87c6-bd8a-11e7-8050-96ba91fd2061.jpg)

**Comment by prashantagarwal** [comment]
@agaitaud We were unable to reproduce this on our end. We will try to investigate it more and keep you updated here.

**Comment by agaitaud** [comment]
Thank you for the update. If I can assist in some way let me know. I was able to work around the problem by adding an ampersand to the end of the request as though I would be passing in another query string parameter to the api.

**Comment by prashantagarwal** [comment]
@agaitaud It would be helpful if you could share the url for which you were facing this issue. I tried with Postman echo collection, but was unable to reproduce this issue.

**Comment by agaitaud** [comment]
Even if I sent you the url, you wouldn't be able to call the services that I use to test postman unfortunately. They are secured, and I would not be able to grant access.

**Comment by prashantagarwal** [comment]
@agaitaud That's fine. I just want to see the url structure so that I am not missing anything.

**Comment by agaitaud** [comment]
Ok here you go:
{{url}}/ishop/v4.0/vehicle/qualifiers/v2.0?m1VehicleId=eWVhcj0yMDA3Jm1ha2U9RG9kZ2UmbW9kZWw9Q2FiKyUyNitDaGFzc2lzJnN1Ym1vZGVsPVIzNTAwK0hEJmVuZ2luZT02LjcmZnVlbFR5cGU9RGllc2VsJmVuZ2luZUNvZGU9RVRKJmJvZHlTdHlsZT1QaWNrdXAmZHJpdmVUeXBlPTRXRCZ0cmFuc2ZlckNhc2VUeXBlPVBhcnQrVGltZSZ0cmFuc21pc3Npb25Db250cm9sVHlwZT1BdXRvbWF0aWM=

**Comment by sivcan** [comment]
@agaitaud Hey, I tried reproducing this issue on the latest version of the [Postman App v6.1.4](https://getpostman.com/apps) but I can confirm that it's not dropping the equal symbol anymore.

![image](https://user-images.githubusercontent.com/12631777/42092442-946a2cb2-7bc6-11e8-87f6-4d2eed0eb5f1.png)
Ignore the `postman-echo` url. 

Could you try upgrading to the latest app and check if it's still happening for you?
If the issue does persist, can you write to help@getpostman.com along with the collection exported through which we can reproduce this issue on our end?

Thanks
