### ISSUE TITLE
Feature Request: Inline Console (Similar to Browser Console)

### ISSUE THREAD

**Issue by deepal** [a85/POSTMan-Chrome-Extension#3700]
Hey guys, 

Is there a possibility of making the postman console inline as a panel at the bottom of the page (similar to dev tools in chrome) other than a separate console window? I badly need the console, but it's really painful when it opens up in a new window.

Thanks.

**Comment by prashantagarwal** [comment]
@dpjayasekara Thanks for the suggestion. And yes it is there in our roadmap. We will have this soon

**Comment by vvs11** [comment]
@deepal Please check out Postman v7.28 and let us know your feedback
