### ISSUE TITLE
Closing second Postman window exits application

### ISSUE THREAD

**Issue by gavinclarkeuk** [a85/POSTMan-Chrome-Extension#3702]
## App Details:

```
Postman for Windows
Version 5.3.2
win32 6.1.7601 / x64
```

## Issue Report:
If I open a second postman window (File->New Postman Window), and then close again it using either the X in the top right, or by using File->Close Window it closes the entire application. I'd expect it to just close the window I selected and leave the original window open, especially given Exit and Close Window are separate menu items.

Just started noticing this, but may have been there for a while.

**Comment by deepakpathania-zz** [comment]
Hey @gavinclarkeuk, As per the discussion on #3222, this was a windows specific issue. I would recommend updating to the latest version, 5.3.2, to see if this persists and then report again.

**Comment by gavinclarkeuk** [comment]
Somehow copied and pasted incorrect version info above, am using latest 5.3.2 on windows and issue persists but I see #3222 is still open, so will close this as a dupe
