### ISSUE TITLE
Follow Authorization header when redirecting to a different host

### ISSUE THREAD

**Issue by joe-mojo** [a85/POSTMan-Chrome-Extension#3703]
## App Details:

```
Postman for Mac
Version 5.3.2
OS X 16.7.0 / x64
```

## Issue Report:
Postman Mac doesn't re-send headers on redirect as Postman Chrome did.

1) Create a collection in Postman Chrome
2) Create a GET with Basic auth. The endpoint must redirect on another IP
3) launch the request

Expected : like in Postman Chrome, Postman Mac should follow 302 and retry the request on the new location with same header (including auth) and get a 200 response
Actual: Postman Mac follow 302 without header, leading to a 403 response

**Comment by prashantagarwal** [comment]
@joe-mojo Thanks for reporting this.

**Comment by thomdabeast** [comment]
Still having this issue.

**Comment by shamasis** [comment]
Note to self: 

Interesting read regarding 302 in RFC 1945

https://tools.ietf.org/html/rfc1945
```
   302 Moved Temporarily

   The requested resource resides temporarily under a different URL.
   Since the redirection may be altered on occasion, the client should
   continue to use the Request-URI for future requests.

   The URL must be given by the Location field in the response. Unless
   it was a HEAD request, the Entity-Body of the response should
   contain a short note with a hyperlink to the new URI(s).

   If the 302 status code is received in response to a request using
   the POST method, the user agent must not automatically redirect the
   request unless it can be confirmed by the user, since this might
   change the conditions under which the request was issued.

       Note: When automatically redirecting a POST request after
       receiving a 302 status code, some existing user agents will
       erroneously change it into a GET request.
```

**Comment by shamasis** [comment]
More notes from HTTP 1.1 specs

https://tools.ietf.org/html/rfc2616#section-10.3.2
```
Note: RFC 1945 and RFC 2068 specify that the client is not allowed
      to change the method on the redirected request.  However, most
      existing user agent implementations treat 302 as if it were a 303
      response, performing a GET on the Location field-value regardless
      of the original request method. The status codes 303 and 307 have
      been added for servers that wish to make unambiguously clear which
      kind of reaction is expected of the client.
```

Where on earth do they specify what headers are allowed to forward?

**Comment by martin5211** [comment]
Can we set followAuthorizationHeader variable in postman-request to true by default or add an option in Settings Headers to enable it or disable it? It's annoying to lose the authorization headers when the redirect happens to a different domain name.

**Comment by codenirvana** [comment]
@martin5211 we are currently adding support for request configurations which will allow you to configure request sending flows like this (retain `authorization` header when a redirect happens to a different hostname.).

Will post about its availability in our canary and stable channel soon!

**Comment by codenirvana** [comment]
We've added support for Request Level Configurations in the latest version of the Postman App (v7.7.2).

You can turn `Follow Authorization header` configuration ON to retain authorization header when a redirect happens to a different hostname.

<img width="1029" alt="Screenshot 2019-09-17 at 12 14 39 PM" src="https://user-images.githubusercontent.com/4865836/65017657-eb49da00-d944-11e9-9c29-5b80b5e64b9f.png">

We'll be adding support for the folder and collection-level configurations soon!

**Comment by tonypaolucci** [comment]
Are there plans to make this a global setting and not per request? We have a system that is now redirected based on what region of the world made the call. The tests we use to exercise the system must be updated to account for this.

**Comment by craigers521** [comment]
> Are there plans to make this a global setting and not per request? We have a system that is now redirected based on what region of the world made the call. The tests we use to exercise the system must be updated to account for this.

Checking in... 2024 and still not finding away to enable this for an entire collection or globally.

**Comment by lukelongcn** [comment]
> We've added support for Request Level Configurations in the latest version of the Postman App (v7.7.2).
> 
> You can turn `Follow Authorization header` configuration ON to retain authorization header when a redirect happens to a different hostname.
> 
> <img alt="Screenshot 2019-09-17 at 12 14 39 PM" width="1029" src="https://user-images.githubusercontent.com/4865836/65017657-eb49da00-d944-11e9-9c29-5b80b5e64b9f.png">
> 
> We'll be adding support for the folder and collection-level configurations soon!

It's work.
