### ISSUE TITLE
dosen't work postman on mac

### ISSUE THREAD

**Issue by neoty** [a85/POSTMan-Chrome-Extension#3704]
## App Details:

```
Postman for Mac
Version 4.11.0
OS X 16.4.0 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:
 2. Expected behaviour:
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 4. Screenshots (if applicable)

**Comment by josluimg** [comment]
Postman osx 5.3.2

macOS Sierra 10.12

Postman can not open
<img width="1190" alt="captura de pantalla 2017-11-09 a las 20 23 39" src="https://user-images.githubusercontent.com/3416114/32625192-e76a5046-c58b-11e7-9e43-2254ffcf6c9c.png">
