### ISSUE TITLE
Wrong position on second screen every time Postman opens

### ISSUE THREAD

**Issue by leolozes** [a85/POSTMan-Chrome-Extension#3705]
Two screens setup, one laptop with HiDPI (3200x1800) and a 1080p external screen. 
Usually I always opened Postman on the second screen. 
Since the last two-three versions, Postman always open in a weird size / position on the second screen.

## App Details:
Postman for Windows
Version 5.3.2
win32 10.0.16299 / x64

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there: happens since the last two / three versions
 2. Expected behaviour: usually Postman opened with the same dimensions / position as when it was last closed.
 3. Screenshots (position of Postman when it opens on the second screen):
![image](https://user-images.githubusercontent.com/11133817/32232713-f545c28e-be58-11e7-97f7-08cc512e51c3.png)

**Comment by prashantagarwal** [comment]
@LeoLozes Thanks for reporting this. We will investigate this issue.

**Comment by thecuriousdev** [comment]
Hey @LeoLozes, Can you update your Postman app to the latest version and verify this once again?

**Comment by leolozes** [comment]
@thecuriousdev it looks like it's working fine, I'll let you know if there's a strange behaviour :)

**Comment by thecuriousdev** [comment]
@LeoLozes happy to hear that :) I am closing this issue for now, but feel free to reopen this if you are facing any issues.
