### ISSUE TITLE
Repeated GET-params disappear

### ISSUE THREAD

**Issue by gukoff** [a85/POSTMan-Chrome-Extension#3708]
## App Details:
```
Postman for Mac
Version 5.3.2
OS X 16.7.0 / x64
```

How to reproduce:
1. Put in the URL `http://google.com?a=1&a=2&a=3`
2. Uncheck any of the repeated params
<img width="765" alt="2017-11-01 16 39 08" src="https://user-images.githubusercontent.com/5655837/32273187-3bc64ee8-bf23-11e7-9323-3fbcd278793c.png">
3. Unchecked params disappear instead of getting disabled
<img width="763" alt="2017-11-01 16 40 19" src="https://user-images.githubusercontent.com/5655837/32273223-632bed58-bf23-11e7-953f-dc7330044817.png">

**Comment by prashantagarwal** [comment]
@gukoff Thanks for reporting this we were able to reproduce this issue.

**Comment by a85** [comment]
Closing as duplicate of #3311. Tracking progress there.
