### ISSUE TITLE
Postman Desktop (Windows) does not work (proxy?)

### ISSUE THREAD

**Issue by Fuerte1** [a85/POSTMan-Chrome-Extension#3709]
## App Details:

```
Postman for Windows
Version 5.3.2
win32 10.0.14393 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:
First time I used Desktop version, and it has never worked.
 2. Expected behaviour:
It should connect to server.
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 4. Screenshots (if applicable)

I go to local .NET SOAP service:
http://localhost:56862/Service.asmx
Everything works in Chrome Postman, but Desktop Postman can't connect:

Could not get any response
There was an error connecting to http://localhost:56862/Service.asmx.
Why this might have happened:
The server couldn't send a response:
Ensure that the backend is working properly
Self-signed SSL certificates are being blocked:
Fix this by turning off 'SSL certificate verification' in Settings > General
Proxy configured incorrectly
Ensure that proxy is configured correctly in Settings > Proxy
Request timeout:
Change request timeout in Settings > General

I have tried all proxy configuration combinations.
We are using automatic proxy configuration script:
http://proxy:8083/

**Comment by Fuerte1** [comment]
Postman console shows this:

Error: Invalid protocol: proxy:

**Comment by mbrasier** [comment]
Postman doesnt seem to support NTLM proxies in the desktop app - this is a major limitation as it makes it unusable in corporate environments. Not sure why they decided to discontinue the chrome app without making sure this works.

See also https://github.com/postmanlabs/postman-app-support/issues/3692

**Comment by Jummartinezro** [comment]
Same issue over my corporate network, even if I properly configured the proxy Postman for Chrome works as expected but new Postman doesn't

**Comment by harryi3t** [comment]
@Fuerte1 @Jummartinezro  Does your proxy needs authentication?
If yes, then I am afraid this is not yet supported. There is a separate thread https://github.com/postmanlabs/postman-app-support/issues/3566

**Comment by mbrasier** [comment]
@harryi3t It isn't as simple as proxies requiring authentication its about NTLM as an authentication mechanism for proxies. This is absolutely a requirement for any use of postman in a corporate environment. It is supported in chrome, but not in the desktop app, making the desktop app unusable.

**Comment by Fuerte1** [comment]
I think that the proxy does not need authentication. Or the authentication is automatic using certificate etc.
I googled this NTLM authentication, and probably it is that.
https://www.cisco.com/c/en/us/support/docs/security/web-security-appliance/117931-technote-ntml.html

**Comment by harryi3t** [comment]
@Fuerte1 As I was expecting, your proxy requires authentication.

In Postman Chrome, Chrome is providing a lot of functionalities out of the box including transparently authorizing the proxy. And among other things, this is one the functionality that we need to add to the native apps and we are working on it.

This is not exclusive to windows native app and I mentioned earlier, there is a separate thread https://github.com/postmanlabs/postman-app-support/issues/3566

Closing this issue. Please follow the other thread for updates about the proxy authentication feature.

### Update
The above-mentioned issue is about adding support for authentication for a proxy. There is [another issue](https://github.com/postmanlabs/postman-app-support/issues/3692) which is specific to adding support for `NTLM` authentication for a proxy.
You might want to follow this issue instead.
