### ISSUE TITLE
Large files upload via postman crashes postman 

### ISSUE THREAD

**Issue by surajpasuparthy** [a85/POSTMan-Chrome-Extension#3711]
## App Details:

```
Postman for Mac
Version 4.11.0
OS X 16.4.0 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:
 2. Expected behaviour:
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 4. Screenshots (if applicable)

**Comment by prashantagarwal** [comment]
@surajpasuparthy Thanks for reporting this. Can you let us know steps to reproduce this issue. Thanks

**Comment by sivcan** [comment]
I suggest you to update to the latest version of the app and let us know if the issue still persists.
