### ISSUE TITLE
This is a duplicate header and will be overridden by the Authorization header generated by Postman.

### ISSUE THREAD

**Issue by Saibobba** [a85/POSTMan-Chrome-Extension#3716]
This is happening after the latest update of postman. Is there any way I can turn it off. This duplicate header is affecting my responses to API calls.

Repro Steps
1. Select oauth 2 authorization.
2. Get the Bearer Token
3. Use the token and click send for valid API call.
4. See the Headers section ----> It has 2 headers. One that's generated and other is duplicate which is dynamically generated.
I do not want the duplicate to be generated automatically.

It says 'This is a duplicate header and will be overridden by the Authorization header generated by Postman.' but is not being overridden.

Please advice 

Postman for Windows
Version 5.3.2

**Comment by sdnts** [comment]
Hi @Saibobba, when you have an authorization set, Postman will automatically generate an Authorization header for you. If you do not want this, you can select No Auth from the Authorization tab. This will not add the extra Authorization header that you're seeing. 

Ideally, you shouldn't need the manual step of adding the auth header to your request. Is there a reason you want to do it on your own instead of letting the app handle it?

**Comment by kamalaknn** [comment]
@Saibobba Are you adding an `Authorization` header manually or could you check if one was accidentally saved with the request? If that is the case removing this header will solve the issue.

If you don't find either, please check if any of your scripts add the `Authorization` header. If you don't find any of these and still seeing two headers generated by Postman, that would be something we would like to investigate.

**Comment by Saibobba** [comment]
@kamalaknn  @madebysid  Im sorry... this has caused due to saving a header with requests.
Once I deleted the old header and saved the requests, it's doing fine.

Thanks again

**Comment by GregTurner** [comment]
I got burned strange behaviour.  This feels like a bug, if the Headers->Key is edited from `Authorization` to another name it should re-evaluate if the header should be overridden.  Minor bug IMO.

**Comment by carlosezam** [comment]
> Hi @Saibobba, when you have an authorization set, Postman will automatically generate an Authorization header for you. If you do not want this, you can select No Auth from the Authorization tab. This will not add the extra Authorization header that you're seeing.
> 
> Ideally, you shouldn't need the manual step of adding the auth header to your request. Is there a reason you want to do it on your own instead of letting the app handle it?

for a specific jwt in just one request

**Comment by swport** [comment]
@madebysid Duplicate headers added in a request should be able to override headers generated by Postman, including Authorization header.
