### ISSUE TITLE
Feature Request: Ability to monitor the disk space in postman

### ISSUE THREAD

**Issue by nithyamuth** [a85/POSTMan-Chrome-Extension#3718]
Writing log entries into our system consumes the disk space. Hence until the disk space is emptied, the processes that need to be run are put in queue.

So wanted to know if we have any integrations with postman that would help resolve this issue by monitoring the disk space.

**Comment by sdnts** [comment]
Hi @nithyamuth, there isn't a Postman integration for what you're mentioning. However, this seems like a feature that is out of scope of Postman, so I'm closing this. Please reopen if I misunderstood :)

**Comment by nithyamuth** [comment]
Hi, I understand that there isn't an integration n Postman at the moment. I got an email from Rob Anderson from postman team asking me to submit a feature request which might be considered at a later point of time.
