### ISSUE TITLE
[Bug] Command-Return stops sending requests after changing tabs, or sending requests

### ISSUE THREAD

**Issue by acceptableEngineering** [a85/POSTMan-Chrome-Extension#3720]
## App Details:

```
Postman for Mac
Version 5.3.2
OS X 16.7.0 / x64
```

## Issue Report:
 _1. Did you encounter this recently, or has this bug always been there?_
I believe this began with version 5.3.2

 _2. Expected behaviour:_
Shortcut keys function persistently while using the app

**Steps to reproduce the problem**
 1. Click into the request pane and press `Command-Return`. Observe the request is sent as expected. Now use shortcut combo `Shift-Command-[` or `Shift-Command-]` to switch tabs and press `Command-Return` again. A request is not sent until the user refocusses the mouse into the one of the panes.
 2. Click into the response pane and press `Command-Return`. Observe the request is sent as expected. Press `Command-Return` again. A request is not sent until the user refocusses the mouse into one of the panes.

**Comment by sdnts** [comment]
@markmutti Thanks for reporting this, I was able to replicate this. We will get on a fix.

**Comment by jkleckner** [comment]
Still bug in Version 5.5.0.

**Comment by prashantagarwal** [comment]
@jkleckner Can you try this on our latest version of App

**Comment by jkleckner** [comment]
This seems to work in version 6.1.4.

**Comment by prashantagarwal** [comment]
Cool, Thanks for confirming this.
