### ISSUE TITLE
trouble in sign-in with google tap method

### ISSUE THREAD

**Issue by ram-rana-16** [a85/POSTMan-Chrome-Extension#3722]
```
Postman for Mac
Version 5.3.2 (5.3.2)
MacOS High Sierra 10.13 / x64
```

## Issue Report:
 1. Not able to sign-in with google tap (on mobile) method, although in mobile side its sign-in approved

Steps to reproduce the problem
* Open desktop application, and try sign-in with google account

**Comment by abhijitkane** [comment]
@rb16 What's the exact issue you're facing? Is there any error message you're seeing? A screenshot of Postman and the DevTools window (https://www.getpostman.com/docs/postman/sending_api_requests/debugging_and_logs) would help.

**Comment by ram-rana-16** [comment]
I have enabled my 2 factor authentication google account using google mobile prompt (https://support.google.com/accounts/answer/6361026?co=GENIE.Platform%3DAndroid&hl=en), I validated my self from mobile side but postman app not logging in.

Now It worked 😄 when i tried multiple times, but earlier (first time after installation) it wasn't working.
