### ISSUE TITLE
Can not import the the request body in examples

### ISSUE THREAD

**Issue by JasonMing** [a85/POSTMan-Chrome-Extension#3723]
## App Details:

```
Postman for Mac
Version 5.3.2
OS X 17.0.0 / x64
```

## Issue Report:
 1. I export a whole collection via v2 format
 2. Then import into my Postman for Mac
 3. Everything is ok except the request body in the examples
 4. The exported collection is in attachment [foo.postman_collection](https://github.com/postmanlabs/postman-app-support/files/1440255/foo.postman_collection.txt) (By some reasons, I've already hidden the request data with `...hidden...`)

**Comment by SamvelRaja** [comment]
Thanks for bringing this to our notice, we were able to reproduce the issue from our end. We shall update the progress here.

**Comment by prashantagarwal** [comment]
@JasonMing This is fixed in 5.4.0+ versions of Postman. Feel free to reopen this issue if you are still seeing this.
