### ISSUE TITLE
Option Oauth 2  ‘Request Access Token Locally’ missing in 5.3.2

### ISSUE THREAD

**Issue by PavelKa** [a85/POSTMan-Chrome-Extension#3724]
Documentation : https://www.getpostman.com/docs/postman/sending_api_requests/authorization
mentions:
If your OAuth2 provider is not publicly accessible (hosted locally or on your intranet), make sure the ‘Request Access Token Locally’ option is enabled.
But this option is missing in 5.3.2:
![image](https://user-images.githubusercontent.com/1038522/32366351-0c714c2c-c07e-11e7-9476-e6634e043606.png)

Postman for Windows
Version 5.3.2
win32 6.1.7601 / x64

**Comment by SamvelRaja** [comment]
@PavelKa  Yes, we deliberately removed it and makes fetching the token locally as default. 
Are you facing any kind of problem making this as default? If so, kindly let us know.
We shall update the documentation as we speak 😄

**Comment by SamvelRaja** [comment]
https://github.com/postmanlabs/postman-docs/pull/164  Fixes this.
