### ISSUE TITLE
Feature request: small improvements to the Environment Quick Look pop up

### ISSUE THREAD

**Issue by josslamberti** [a85/POSTMan-Chrome-Extension#3725]
## App Details:
Postman for Windows
Version 5.3.2
win32 10.0.16299 / x64

## Feature Request:
When I click on Environment Quick Look (the eye icon), I would benefit from 2 improvements:
1 - Only show the first line of data for long pieces of data (as when editing values). In my case I have a base64 PNG to scroll through and since today it needs to be much bigger because of a minimum size rule!
2 - Keep the environment name and Edit button out of the scrolling area so I can click on Edit without having to scroll back up. It wouldn't be a problem if the view was always scrolled back up automatically when reopening it (note: the fact that it doesn't scroll back up automatically when reopening it is a good thing on its own).

**Comment by SamvelRaja** [comment]
Thanks for your valuable feedback. We will forward your input to our UI/UX team 😄

**Comment by giridharvc7** [comment]
Environments are now available as a new tab/window in Postman version 8, both on the app and the web. Please let us know if you still face these problems. Closing this issue for now
