### ISSUE TITLE
Token window does not close when pressing Use token

### ISSUE THREAD

**Issue by reager** [a85/POSTMan-Chrome-Extension#3727]
## App Details:

```
Postman for Windows
Version 5.3.2
win32 10.0.15063 / x64
```

## Issue Report:
 1. When the window with the token appear after pressing Get new access token -> Request token it does not close after pressing "Use token". Pressing the X to close the window requires 8 clicks, and the modal window gets more transparent for each click before finally it closes.
 2. Expected behaviour:
The window closes when clicks "Use token" or on the first click of X
 4. Screenshots (if applicable)

I have managed to retrieve the token
![image](https://user-images.githubusercontent.com/668343/32376322-c8ef6c78-c0a4-11e7-9902-f72820a125b7.png)

Pressing "Use token" does nothing for closing the window.

First click on
![image](https://user-images.githubusercontent.com/668343/32376379-eefe208a-c0a4-11e7-88a4-dd28ba0aa2d2.png)

Secondclick on
![image](https://user-images.githubusercontent.com/668343/32376387-f69eb3ea-c0a4-11e7-87ba-8596a48856c7.png)

Third click on
![image](https://user-images.githubusercontent.com/668343/32376402-fe3b60da-c0a4-11e7-87b5-4d6a93b4fc56.png)

Fourth click on
![image](https://user-images.githubusercontent.com/668343/32376411-070c0430-c0a5-11e7-95d7-16396b87adcd.png)

Fifth click on
![image](https://user-images.githubusercontent.com/668343/32376420-0f04e562-c0a5-11e7-93dd-408d8cfef034.png)

Sixth click on
![image](https://user-images.githubusercontent.com/668343/32376435-16b79e62-c0a5-11e7-88c4-82fca76f4b8d.png)

Seventh click on
![image](https://user-images.githubusercontent.com/668343/32376459-208396f8-c0a5-11e7-8d35-e88e7dfed6b0.png)

Eight click on X will finally close the window.

**Comment by SamvelRaja** [comment]
@reager you are seeing any kind of error in the dev console while doing this.
You can open the console by View -> Show Devtools

**Comment by reager** [comment]
Dont know if its related, but this is what show up in the dev tools

![image](https://user-images.githubusercontent.com/668343/32443321-e19e3dce-c2fe-11e7-802c-298acc0fec14.png)

**Comment by gLes** [comment]
I can also reproduce the issue. It happens when I use the **Get New Access Token** dialog and the **Manage Tokens** dialog is shown immediately after. It's as if multiple instances are shown of the same dialog. The overlay behind the dialog is more and more transparent after every click on the close button of the dialog, until the dialog finally disappears.

Same error is visible in the console:
![image](https://user-images.githubusercontent.com/544320/32603602-9be0d1f4-c54a-11e7-8f4b-e4f84aef4f3f.png)

**Comment by krmr** [comment]
I am also experiencing this issue. Just now I finally noticed that this only happens if more than one tab is open. Actually the dialog has to be closed once per open tab.

**Comment by SamvelRaja** [comment]
Thanks for the great info! Confirming that this is the case :) Will patch it up in next release 👍

**Comment by kamalaknn** [comment]
This has been fixed in the latest version of Postman. 

I'm closing this issue, please report to us if this issue still exists.

Thanks
