### ISSUE TITLE
Need to be able to control when updates to shared collections occur

### ISSUE THREAD

**Issue by CoolDadTx** [a85/POSTMan-Chrome-Extension#3729]
When using a shared collection the only options you have are view and edit. When edit is enabled then any user who makes a change to the collection in Postman will automatically update the shared collection. This isn't desirable in most cases because each dev may create or change their own collection in Postman. Right now those changes would be pushed to the shared collection. The only workaround (to avoid accidental changes) is to either not enable editing for the team or have a process (that could be violated) to create a copy of the collection.

A gating system is needed to allow a dev to use a shared collection and only update the shared version if/when they decided to. Something akin to a check in or update system would be ideal. 

## App Details:
Postman helps you develop APIs faster
Postman for Windows
Version 5.3.2
win32 10.0.15063 / x64

**Comment by deepakpathania-zz** [comment]
Hey @CoolDadTx, interesting point, I would like to suggest a walk around which might be useful to you.
So in cases like these, try considering shared collections as a version-controlled entity and rather than editing the commonly shared collection directly, maintain a local copy( say by exporting the collection and importing with a patch name, there might be a better way for this), edit that and once you feel comfortable with the changes you have made, push them to the shared collection. The patch names can also help you keep track of the changes made over time. 
Not sure if this satisfies your use case, but might help someone facing a similar issue. You can read more about exporting and managing collections [here](https://www.getpostman.com/docs/postman/collections/sharing_collections).

**Comment by CoolDadTx** [comment]
Thanks for your feedback. I mentioned the basics of what you describe in my original post but as I mentioned, it really isn't scalable or reliable. Perhaps short term but nothing permanent. Here's the scenarios I can think of.

Scenario 1
User logs into Postman which automatically pulls down the shared collections. User wants to look at a particular request so they open it and make a request. They close the tab and Postman offers to save. Because we're trained to save instinctively, we save. The shared collection has been updated.

Scenario 2
User does not log into Postman. To get the collections they have to import like you would if you weren't on a team. This defeats the purpose of having a team and limits the usefulness in private collections. An alternative where you log in, get the shared collections and log out also isn't a useful scenario.

Scenario 3
User copies each shared collection (a variant of your patch approach). When the user goes back into Postman they have no way of knowing whether their copied version is up to date or not so they have to delete the old copy, and copy the existing shared collection again. If a user actually has a change they want to make then they have to copy the change(s) back to the shared collection manually.

Scenario 4
The patch variant you mentioned. Sounds reasonable up front (and I admit that versioning is reasonable) but as you make updates to a collection the # of shared collections become uncontrollable. We have many different collections and having multiple versions of each one would be unrealistic. At a minimum you'd have to have some sort of cap on variants (old, previous and current; perhaps). But there is nothing to prevent someone from changing any of them. Again, it boils down to being a good citizen.

I think Postman needs better management of shared collections. None of the solutions that could be done today are reliable enough to entrust to a dev team to get right (especially a young dev team).

**Comment by deepakpathania-zz** [comment]
>  When the user goes back into Postman they have no way of knowing whether their copied version is up to date or not so they have to delete the old copy, and copy the existing shared collection again.

I totally agree with this and can imagine this being problematic in maintaining large no of collections. 

For the first scenario though, simply trying a particular request of a collection wouldn't affect the shared collection in general. You can also try playing around with permissions a little bit( view and edit) to switch between the two if you want only experienced devs to have the edit access (to counter the young dev team point). 

I believe something like updating your local copy of the collection with the latest shared one(like an upstream pull to get up to date) is a viable option.

**Comment by sankalp0o** [comment]
@CoolDadTx We're working on features related to tagging and merging collections as a first step towards better collaboration on collection. While this is not exactly what you're asking for, I do believe that this will help with the approach @deepakpathania suggested. You would not have to keep different copies indefinitely, you'd be able to merge them when you think you're ready with changes. This would work even if the original collection was modified in the mean time and you'd be able to resolve conflicts easily.

**Comment by vkaegis** [comment]
Hey guys! We've made an RFC to document our ideas on version control in Postman, would love your thoughts and feedback on it:

https://community.getpostman.com/t/version-control/2715

**Comment by vkaegis** [comment]
Hey guys, you can now fork collections and merge changes back between them (as of v6.7.1). 

This gives you a lot more granularity on what changes you want to merge back into a collection which multiple people are working collaboratively on. We'll be building further improvements on this, such as a review process for merge requests, and once we have role-based access control in place (coming soon), you'll be able to control who can review these requests as well. 

Closing this issue for now, feel free to open another if you have more feedback around this implementation.
