### ISSUE TITLE
Could not import a exported collection JSON file. Fix included.

### ISSUE THREAD

**Issue by skrelo** [a85/POSTMan-Chrome-Extension#373]
I ran into an issue in importing a collection. I exported a collection at one location, then tried to import it into another. Both versions of POSTman were identical, and there was no HTML wrapper in the JSON file.

Chrome version: 29.0.1547.76

The error message was referring to line 500 in requester.js. Could not get length of undefined. 
the 'collection' object variable being passed to 'importCollectionData' is actually a parent object of a 'collections' array, thus there is no 'requests' member in 'collection'.

In the 'importCollections' method, before it passes a 'collection' object to 'pm.collections.importCollectionData', it needs to traverse through the 'collection.collections' array, to get the individual collection first, before the import process.
Here is my modified version of that function, this fix worked for me, not saying it will for everyone, or if this is even a bug, I just know that importing did not work for me, and this is what i did to fix it:

requester.js:532

``` javascript
importCollections:function (files) {
        // Loop through the FileList
        for (var i = 0, f; f = files[i]; i++) {
            var reader = new FileReader();

            // Closure to capture the file information.
            reader.onload = (function (theFile) {
                return function (e) {
                    // Render thumbnail.
                    var data = e.currentTarget.result;
                    var collection = JSON.parse(data);
                    collection.id = guid();

                    // Need to traverse through the collection.collections array
                    for (var t in collection.collections) {
                        pm.collections.importCollectionData(collection.collections[t]);
                    }
                };
            })(f);

            // Read in the image file as a data URL.
            reader.readAsText(f);
        }
    },
```

**Comment by mmmattos** [comment]
Importing a newly exported collection fails (nothing actually got imported) but without any errors. 
The pop-up says:
 "It worked!

The collection has been added"
 But the collections list remains unchanged.
Any clues?
Thks.

**Comment by abhijitkane** [comment]
@mmmattos Can you mail the collection file in question to help@getpostman.com?
You can edit out the URLs/header values/other sensitive info.

**Comment by GregoryPellegrin** [comment]
This problem is still active on 6.4.4

**Comment by javedmshah** [comment]
and still active on v7.14.0
