### ISSUE TITLE
Encoding of URL query string is incorrect

### ISSUE THREAD

**Issue by sndwow** [a85/POSTMan-Chrome-Extension#3734]
## App Details:
```
Postman for Windows
Version 5.3.2
win32 6.1.7601 / x64
```

## Issue Report:

For example url : http://abc?plate_no=粤123456
Using fiddler will display：http://abc?plate_no=�123445

**Comment by SamvelRaja** [comment]
Thanks for bringing this to our notice, we shall look at the issue and update the progress in the same thread again.

**Comment by scplay** [comment]
same issue here, when chinese parameters in GET, the uri encode does not work corretly. My service return 400 bad request

**Comment by abhijitkane** [comment]
Related to https://github.com/postmanlabs/postman-app-support/issues/3688

**Comment by shamasis** [comment]
Closing as very very close duplicate of https://github.com/postmanlabs/postman-app-support/issues/4555
