### ISSUE TITLE
Feature Request: Need to be able to manage large number of collections

### ISSUE THREAD

**Issue by CoolDadTx** [a85/POSTMan-Chrome-Extension#3735]
As the number of collections a team has grows, the existing dashboard becomes unusable. Right now it seems to simply list them in the order they were added. A team should be able to better organize them. 

1) At a minimum provide sorting options such as newest to oldest or alphabetical.
2) Provide the ability to group collections together (i.e. Public, Private, Obsolete, Preview, Test).
3) It would be nice if this grouping construct boiled down to the app as well. Additionally the app shouldn't load collections unless I actually try to open them. If I were to have a 100 collections in my team but only 1 wanted to work on then I don't want to wait for the other 99.
4) Perhaps the ability when opening Postman to be alerted to what new collections are available (or have been updated) and allow me to decide to download the updates.

## App Details:
Postman helps you develop APIs faster
Postman for Windows
Version 5.3.2
win32 10.0.15063 / x64

**Comment by a85** [comment]
Thanks! This is exactly what we are working on with the idea of #3205. More news soon!

**Comment by SamvelRaja** [comment]
Closing this in reference with #3205
