### ISSUE TITLE
Feature request : Postman should modify response content.

### ISSUE THREAD

**Issue by selfboot** [a85/POSTMan-Chrome-Extension#3736]
Now we can only use pre-request and tests script:

![](https://s3.amazonaws.com/postman-static-getpostman-com/postman-docs/59184189.png)

But sometimes the response is encrypted, and it's better if we can use js to decrypt it and then display it.  So can postman add a **pre-response** process, and allow us modify the response content?

**Comment by SamvelRaja** [comment]
I can understand your concern. You can very well console.log the decrypted response in the test script which will eventually show up in our postmanConsole (View -> Show postman console).

**Comment by alanwei43** [comment]
> I can understand your concern. You can very well console.log the decrypted response in the test script which will eventually show up in our postmanConsole (View -> Show postman console).

I can get response data in the test script, like `pm.response.json()`, but how to modify the response data?

**Comment by mlick** [comment]
@alanwei43   Did you find a way?
