### ISSUE TITLE
Drag and dropping inside collection folder exhibits erratic behavior

### ISSUE THREAD

**Issue by AndySoHotRightNow** [a85/POSTMan-Chrome-Extension#3737]
When I try to click, hold and move (i.e. drag and drop) a request within a collection folder it gets moved to a completely different place.

To give you a concrete example:

![screen shot 2017-11-06 at 3 52 06 pm](https://user-images.githubusercontent.com/17130123/32430568-d54ed9d2-c30a-11e7-8ba5-25232f26e531.png)

This is me trying to move `public/admins/login` request one position upwards (i.e. above the `manager/admins` request), when I let go, it gets sent to a completely different folder for no reason at all (in this case it was the `guests` folder).

This happens with other requests (although not all of them) and regardless of how many positions I try to move them up or down.

## App Details:
Postman for Mac
Version 5.3.2
OS X 16.7.0 / x64

**Comment by SamvelRaja** [comment]
@AndySoHotRightNow  Thanks for bringing this to our notice. Can you send us an email to help[at]getpostman[dot]com from your registered email id?

**Comment by AndySoHotRightNow** [comment]
Just a follow up.

Today I was having the same problem, however, at some point this window popped out:

![screen shot 2017-11-07 at 5 40 33 pm](https://user-images.githubusercontent.com/17130123/32486931-138dfb50-c3e3-11e7-9d5d-8880b8cb71e7.png)

After clicking on `Resync` the erratic behavior disappeared.

**Comment by GrzegorzPi** [comment]
I have a similar behaviour but only with interact between 2 collections.

My collection example:

1. collection

- subfolder

-- req11

-- req12

-- req13

-- req14

2. collection
- subfolder

-- req21

-- req22

-- req23

-- req24

In some drag and drop event it don't work correct:

**Scenario1:**
1) drag req21
2) drop on line after req14
3) req21 drops actualy between req13 and req14
Expected:
req21 drops after req14, on the end of collection

**Scenario2:**
1) drag req21
2) drop on line between req11 and req12
3) req21 drops actualy before req11 on beginning of the collection
Expected:
req21 drops between req11 and req12

**Settings:**
Postman for Windows
Version 5.5.0
win32 10.0.16299 / x64

**Comment by AndySoHotRightNow** [comment]
Although not a permanent solution, this behaviour vanished once I restarted Postman, could you confirm if the same happens to you?

**Comment by GrzegorzPi** [comment]
I have been looking a bit more into this.

I suddenly saw 2 type of dropping requests:
- drop on upper drop line
- drop on lower drop line

2 drop lines are so close, so I didn't see this until now (screen):

![postman](https://user-images.githubusercontent.com/35603973/35333532-5abb5036-010f-11e8-96c7-b11deafe2dad.png)

Behaviour:
1) drag in the same collection - dropping request on lower or upper line works the same and correct.

2) drag between collection
 - dropping request on lowel line drops correctly
 - dropping request on upper line drops request one position to high - not correctly - case i've been describe abow.

 - over first request in list there is only lower drop line - so every drop here works fine

- under last request in list there is only upper drop line - so every drop here works badly 

3) @AndySoHotRightNow  no, restart doesn't help for me.

**Comment by AbdelrahmanHafez** [comment]
Same thing happens to me, whenever I try to move a folder from one place to another in the same folder, it gets moved to either inside a sibling folder, or move to a higher level of folders.

Sometimes when I move a folder, other folders disappear, the drag and drop features inside the collections need a lot of work.

**Comment by sivcan** [comment]
Hi all, 
The [latest version](https://www.getpostman.com/apps) of the app includes major upgrades in the drag-and-drop feature.
I advise you all to update to the same.
Let us know if you're still experiencing this issue.
