### ISSUE TITLE
Can't Publish Documentation for a Collection

### ISSUE THREAD

**Issue by staticvoidmaine** [a85/POSTMan-Chrome-Extension#3738]
## App Details:

```
Postman for Linux
Version 5.3.2
linux 4.12.14-1-MANJARO / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there: Yes
 2. Expected behaviour: I am able to publish documentation for a collection
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):

```
dashboard:44 [Violation] Avoid using document.write().
(anonymous) @ dashboard:44
(anonymous) @ dashboard:44
main.js:1 Our embeddable contains third-party, open source software and/or libraries. To view them and their license terms, go to http://goto.zendesk.com/embeddable-legal-notices
raven.js:51 

  |>    Now connected to Sails.
\___/   For help, see: http://bit.ly/1DmTvgK
        (using sails.io.js node SDK @v1.1.12)



raven.js:51 {response: "<!DOCTYPE html>↵<html lang="en">↵  <head>↵    <met…a-var-url-prefix=""></script>↵↵  </body>↵</html>↵", error: undefined, statusCode: 500}
a.(anonymous function) @ raven.js:51
(anonymous) @ domain.js:77
r @ runtime.js:65
(anonymous) @ runtime.js:299
e.(anonymous function) @ runtime.js:117
m @ proc.js:280
n @ proc.js:378
(anonymous) @ proc.js:441
Promise rejected (async)
E @ proc.js:440
S @ proc.js:507
b @ proc.js:425
m @ proc.js:306
n @ proc.js:378
(anonymous) @ proc.js:489
r @ scheduler.js:19
s @ scheduler.js:60
a @ scheduler.js:33
(anonymous) @ channel.js:185
t @ channel.js:26
(anonymous) @ middleware.js:67
(anonymous) @ bindActionCreators.js:3
value @ CollectionPublish.js:24
e.notifyAll @ CallbackQueue.js:76
close @ ReactReconcileTransaction.js:80
closeAll @ Transaction.js:206
perform @ Transaction.js:153
perform @ Transaction.js:140
perform @ ReactUpdates.js:89
S @ ReactUpdates.js:172
closeAll @ Transaction.js:206
perform @ Transaction.js:153
batchedUpdates @ ReactDefaultBatchingStrategy.js:62
o @ ReactUpdates.js:97
dispatchEvent @ ReactEventListener.js:147
d @ raven.js:386
```

 4. Screenshots (if applicable): N/A

Replicated in both the postman app for linux as well as the browser.
1. For a given collection, click "Publish"
2. Be brought into default browser (chrome in my case) as logged in user (me).
3. Sit at a spinner indefinitely.
4. Open developer tools which reveals an error message
5. Begin filing a github issue with postman-app-support
6. Fill in App Details
7. Specify this issue was encountered recently
8. Specify expected behavior
9. Provide console.log information
10. Note that a screenshot is not applicable
11. RangeError: Maximum call stack size exceeded.

**Comment by godfrzero** [comment]
@rylancates Could you shoot us an email at help@getpostman.com with the ID of the collection you were trying to publish, and the email associated with your postman account?

**Comment by staticvoidmaine** [comment]
You bet
