### ISSUE TITLE
"src" and "value" attributes from the "form-data" gets removed after exporting the collection using the postman 5.3.2

### ISSUE THREAD

**Issue by dtopcuog** [a85/POSTMan-Chrome-Extension#3740]
```
"src" and "value" attributes from the "form-data" gets removed after exporting the collection using the postman 5.3.2. 
```
## App Details:

```
Postman for Linux
Version 5.3.2
linux 3.10.0-327.55.2.el7.x86_64 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:
 `Recently.`
 2. Expected behavior:
 `src and value should not be removed from the collection if already existed`
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
`N/A`
 4. Screenshots (if applicable)
![formdata](https://user-images.githubusercontent.com/33434754/32465955-4bdba5c8-c313-11e7-906b-578a79253a54.PNG)

```
Have a collection that has already body which is set to "form-data" 
     Make sure form-data has some key:value pairs. (see screenshot)
     Make sure one of the key's type value is set to "file" already
Modify the collection and export it (using 5.3.2)   
     After exporting the collection, you will notice that the "src" and "value" pairs are removed. 
```

**Comment by SamvelRaja** [comment]
@dtopcuog we are removing the src in form-data for security concerns.
But, the idea of having it as an environment variable, we shall look at as a feature and try to analyze the possibilities around it.

**Comment by cchretien** [comment]
I'm also seeing this issue. We specifically create our collections to work with newman and it is painful if we have to manually update every time we export.

https://github.com/postmanlabs/newman#file-uploads

**Comment by treefitty** [comment]
Hi @SamvelRaja, I was just wondering if you could voice these concerns (just so we can empathise) as it's quite an frustrating problem; actually my case might be different..

FWIW I have an issue where I export the collection on my Linux (Ubuntu 16.04) desktop, save to git and then import that onto my Mac. Once I export it again it has removed all the references to "files" and I have to manually revert those hunks in order to keep my tests running. EDIT: If I just keep working on my Mac or Linux (not swapping between) I can export over the top with no issues.

As I say that could be redundant, I just want to make sure there is some technical difference between the OPs issue and mine... Cheers!

**Comment by mikhail-amurov** [comment]
I confirm this issue as well for v.5.3.2. Exporting "src" and "value" attributes from the "form-data" works fine in older version v.5.1.3.

**Comment by Huffers** [comment]
This has come up as a key issue at several retrospectives where I work.

We want automated tests of our API (which involves file uploads), so we use Newman to run the tests on build machines and Postman to edit and run them locally. Every time we export a collection it loses all the file uploads and we have to carefully commit only the changes we intended. And every few days someone accidentally commits one of these changes, breaking the build, and we lose time investigating and fixing it.

**Comment by majstorki88** [comment]
+1 for this issue.

**Comment by pschumacher** [comment]
+1

**Comment by ChadTaljaardt** [comment]
+1

**Comment by harryi3t** [comment]
This is being tracked here https://github.com/postmanlabs/postman-app-support/issues/4320
