### ISSUE TITLE
Postman no selected files caused bad request

### ISSUE THREAD

**Issue by ym13349140** [a85/POSTMan-Chrome-Extension#3742]
## App Details:
```
Postman for windows
Version 5.3.2
win32 10.0.15063 / x64
```

## Issue Report:
I use Python-Flask on my server end.I want to use postman POST form-data to test my API.I have to upload an image to the server,when I manually select an image,the server request.files['cover'] can get the file and return the correct response,but when there is no selected file,then I get a 400 bad request response.when I check the server end,I find that python request.files['cover'] could even not get the key "cover" and return a bad request.

Here's my request and response:
![image](https://user-images.githubusercontent.com/17507937/32474394-4f324238-c3a7-11e7-925f-6995616b4dbc.png)

I wonder that if there is no selected files then the request will even not send the key to server?
Hope for a reply.

**Comment by shamasis** [comment]
Essentially, we currently drop the entire file row, if no file has been selected once or reading file failed.

So, a good behaviour would be:

1. Send the file "key" / name, irrespective of whether a file was selected or reading errors out (and give a warning in console logs). 
2. To ignore the key as well as value, we should respect the disabled checkbox. This is done.

Regarding point one, affected subset, if we do the change, might be a very low in numbers. Need to evaluate impact on existing collection runs if we do this change.

cc @codenirvana @kamalaknn @numaanashraf

**Comment by codenirvana** [comment]
Blocked on: https://github.com/form-data/form-data/issues/412

**Comment by abhijitkane** [comment]
@codenirvana Will the `.prototype` workaround suggested on https://github.com/form-data/form-data/issues/412 not work?

**Comment by arlemi** [comment]
This was fixed in 7.16.0, please let us know if you're facing the same issue.
