### ISSUE TITLE
Test are not running On Native App whereas It is working as expected in chrome extension 

### ISSUE THREAD

**Issue by nikhileshshah** [a85/POSTMan-Chrome-Extension#3743]
Today, I installed Postman Native app and tried to execute my existing automation script which was developed on  Postman chrome extension and strange part is my script is working fine with chrome extension and it is failing with Native App

## App Details:
Postman Native App:
Postman v5.3.2 is the latest version

```
Postman for Windows
Version 5.3.2

```

## Issue Report:
I have been using Postman client browser extension from last 8 months, Since i started getting notification that chrome app will be deprecated soon so I moved to Native App. Where I am facing below mentioned issue.

Issue:
With native app I found my test cases were not getting executed and I am getting error as "**"Message": "Unable to verify integrated windows authentication."**". whereas my collection is working as expected on chrome extension.

As my API's are using Integrated Windows Authentication , we dont have to pass Token/Authorization is Header.

**Chrome Extension Details:**
Postman for Chrome
Version 5.3.2
win / x86-64
Chrome 55.0.2883.87

Kindly help

**Comment by nikhileshshah** [comment]
@postman-admin : Can someone help me on this Please.

**Comment by harryi3t** [comment]
@nikhileshshah I have few questions
 1. Are your APIs protected by windows auth
 2. Is there a proxy involved which requires windows auth
 3. which windows auth is it? (NTLM/Kerberos/Negotiate)

We already support NTLM auth for API requests. 
So if the answers to above questions are in order **YES, NO, NTLM** then you can just update all the requests with the new NTLM auth that is supported by the native apps.

The reason this is not required for the Postman Chrome extension/plugin is that in that case chrome as a browser is providing some functionalities out of the box including but not limited to Authentication.

**Comment by nikhileshshah** [comment]
Yes, our API's using integrated windows authentication (IWA). I tried passing NTML but getting same error

**Comment by harryi3t** [comment]
@nikhileshshah 
Can you share the logs from postman console?
-  Open Postman Console
-  Clear if any logs are present
- Send *one* request having NTLM auth to your end point
Q1. How many logs do you see in the postman console?
Q2. Please share the entire logs here (of *every* request from console)

**Comment by nikhileshshah** [comment]
Sorry, I am unable to open PostmanClient (Native App) console, I have added console.log( ) function in test tab and executed test, after execution when i right click on window it is not showing me any option to inspect.

Could you please help me to get postman Native App console log, Please

**Comment by nikhileshshah** [comment]
Hello,

I enabled NTLM and passed my windows credentials but still its failing. So I captured logs for the same.

`Error running scripts: ReferenceError | m is not defined Objectmessage: "m is not defined"name: "ReferenceError"type: "Error"__proto__: Object
exception @ xml.js:22
invokeCallbackSafely @ xml.js:22
(anonymous) @ xml.js:22
emitMany @ events.js:127
emit @ events.js:201`

Note: Same request is working on postman browser extension.

Thank You

**Comment by harryi3t** [comment]
@nikhileshshah The logs are not related to NTLM at all. This error is happening coz you are trying to log a variable `m` which is not defined.

Please remove the `console.log` and then send the request.
I want to see the logs of the request being sent.
See the sample screenshots

### Normally 3 requests are sent for NTLM authentication
![image](https://user-images.githubusercontent.com/5207331/32659426-b9b4ccbc-c644-11e7-8288-094f2f7e4277.png)

### Request 1 logs expanded (repeat this for the rest of the requests)
![image](https://user-images.githubusercontent.com/5207331/32659465-ec15ac9e-c644-11e7-93c2-8466c8c803fd.png)

**Comment by nikhileshshah** [comment]
Hello,

If i remove console.log(), Logs are not getting printed in Developer tool.

Thank You

**Comment by harryi3t** [comment]
@nikhileshshah No, not developer console, please check postman console.
See my screenshots above.
To open it click on main menu `View` -> `Show postman console`

**Comment by nikhileshshah** [comment]
hello @harryi3t,

Thank you, please find attached screenshot. I did not see any authenticate tag under request/response. I passed NTML request with username and password.
 
![postman client console log](https://user-images.githubusercontent.com/6782463/32731860-eca8bb42-c8b0-11e7-9fe7-53ceaf1ff7ac.png)

**Comment by harryi3t** [comment]
@nikhileshshah Thanks for the input.
I noticed that the required header `www-authenticate` was not sent by the server.
Using this header server tells the user what authentication is expected. See my screenshot above for reference.

Also, here's the official reference for NTLM 
https://msdn.microsoft.com/en-us/library/cc237540.aspx
In this they mention

> The first time the client requests the document, no Authorization header is sent; so the server responds with the following.
>   
>  S: HTTP/1.1 401 Unauthorized
>  S: **WWW-Authenticate: NTLM**

**Comment by nikhileshshah** [comment]
@harryi3t : Thank You.
So, Developer has to handle this right?

**Comment by harryi3t** [comment]
@nikhileshshah yes, the developer who wrote the logic for the auth server should take care of this.

**Comment by nikhileshshah** [comment]
Thank You @harryi3t ,
