### ISSUE TITLE
Runner should always keep the response body logged

### ISSUE THREAD

**Issue by chrisron95** [a85/POSTMan-Chrome-Extension#3744]
## App Details:

```
Postman for Mac
Version 5.3.2
OS X 17.2.0 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:
Been there as long as I can remember
 2. Expected behaviour:
When a test fails in the runner, or the runner is stopped entirely, it should keep the response body logged. However, more often than not it just says either "response body unavailable" or "Data unavailable" (see screenshot)
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
Error running tests for Consumer Institution List: TypeError: Cannot read property 'length' of undefined
onEndTest @ runner.js:221765
 4. Screenshots (if applicable)
![screen shot 2017-11-02 at 10 21 49 am](https://user-images.githubusercontent.com/16259311/32500356-2cc0a324-c3a3-11e7-82b9-ff637d5443ec.png)
(Please note, all other calls have the body stored, it's only when there's an error that it says this very unhelpful message)

I'm not sure how this could be reproduced, this just happens to me every time the runner stops itself and says "Open DevTools for more info" (which is extremely annoying might I add, it shouldn't blatantly stop the runner because it couldn't get the length of undefined, but that's another issue I have already written up.)

Once this issue pops up, I have no way of finding out what went wrong without going back and doing every single call of the large runner collection manually until I get to where I can see what happened, and often times it's something that would be very easy to keep logged, like a one line error message that is returned.

Fixing this issue would be a major help to me for debugging. This happens way too often for me to ignore it.

**Comment by cen1** [comment]
This happens whenever a JS error is thrown in the test script and should probably be fixed. Until then, writing JS tests in a way to never cause errors is the workaround.

**Comment by sivcan** [comment]
Hi @chrisron95 - This has been fixed in the [Latest version of the app](https://www.getpostman.com/apps) 
Closing this.
