### ISSUE TITLE
Need "Workspaces" to group collections

### ISSUE THREAD

**Issue by idevtech** [a85/POSTMan-Chrome-Extension#3745]
As I use Postman for multiple projects and clients I'm finding a single list of collections limiting. What would be useful is a higher level grouping mechanism like a "workspace" or "project" which would contain collections. This organization could be achieved by using a collection as the parent and then creating folders to group requests. However, this limits capabilities like mocking a collection which can't be done on a folder basis. Slack has a workspace implementation that achieves this functionality for reference.

**Comment by sdnts** [comment]
Hey @idevtech! Thanks for the feature request! Workspaces are actually a requested feature and are on our [roadmap](https://trello.com/b/4N7PnHAz/postman-roadmap-for-developers).
We're tracking it at #3205. We'll update that thread when we make progress!
