### ISSUE TITLE
Windows Native App not showing all cookies

### ISSUE THREAD

**Issue by jdfurlan** [a85/POSTMan-Chrome-Extension#3748]
I've used the chrome app for several months now, and I would use interceptor in chrome to handle the auth cookie that our web app requires for authenticated requests. Now that I've switched to the native app on windows, I don't see any way of doing that. When I look in the cookie store, it doesn't show all the cookies that are actually in the browser. Without the auth cookie, we can't test our APIs.

Postman for Windows
Version 5.3.2
win32 10.0.14393 / x64

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:
Never encountered this issue with the chrome app - have always seen on the Windows app

 2. Expected behaviour:
Before I would use Interceptor to handle the auth cookie - the new native app doesn't give that option unless I'm just not seeing it.

 4. Screenshots (if applicable)
![image](https://user-images.githubusercontent.com/11356304/32526165-c220ffe8-c3dc-11e7-8b82-96dcb49cd786.png)

**Comment by sdnts** [comment]
@jdfurlan The cookie store in the app is independent of your browser's cookie store. If you want to use your browser's cookies, you'll have to add them here.
Alternatively, if you use an endpoint to set cookies, you can just hit that endpoint from the app and the cookies will be created automatically.

**Comment by jdfurlan** [comment]
Ya so that's what I've been doing as a working solution - but this means that every time I authenticate with our app, I need to go into Chrome cookies, literally copy the cookie name and cookie data out, and paste it into a new cookie in the Postman cookie store. I understand this is a limitation of the native app, but it makes it essentially useless for testing any web app that requires an authentication cookie for any endpoints. At this time I'll be moving back to the native Chrome app. Would be really nice to no longer see the deprecation message there since it actually has more functionality than the desktop app.
