### ISSUE TITLE
New distribution format for Linux - Flatpak

### ISSUE THREAD

**Issue by baszczewski** [a85/POSTMan-Chrome-Extension#3749]
```
Postman for Linux
Version 5.X
```

## Issue Report:
1. Postman at the moment is available on Linux in archive with binary file. 
2. It's not convenient way to install it. User have to manually create shortucts etc. 
3. It's not also to secure, because any security bug inside your's software can affect userspace. 
4. There is solution in new, multiplatform package distribution for Linux: Flatpak.
5. It's easy to use, but most important part for my is security. Flatpak applications are sandboxed from rest of the system;

More information: http://flatpak.org/

**Comment by sdnts** [comment]
Hi @baszczewski Thanks for the request! We will look into this and let you know here when we make progress :)

**Comment by suciptoid** [comment]
Hi, 
I've create simple script to pack Postman using AppImage.
https://github.com/showcheap/postman-appimage

More info about AppImage : https://appimage.org/

**Comment by ziggy42** [comment]
News on this?

**Comment by SamvelRaja** [comment]
We are working on the auto-update for the linux app. Kindly, subscribe to #2931 where we are actively tracking the issue.

**Comment by baszczewski** [comment]
@SamvelRaja 
Excuse me but this is not solution. Idea behind Flatpak is not to provide only easy updates or setup process, but also to separate app from other critical system components (run app in own sandbox). 
Repositories are nice, but in my opinion only for open source code / maybe system base. They are a far away from perfect to share closed apps like yours. 
Other question is, do you have resources to provide packages not only for Debian but also other important distributions which have other package format? 
I would like propose to use Flatpack because it's easy to prepare (a lot easier than Debian package in my opinion), Flatpack have great integration with software center apps, and provide modern security trends.   

Please reconsider distribution format and reopen this issue.

**Comment by ghisvail** [comment]
I second @baszczewski. Flatpak support and auto-updates are orthogonal concerns. Please re-open.

**Comment by Amunak** [comment]
Thirded. Postman is nice, but installing and updating it is a pain, and there needs to be a way to isolate it and install it properly, with tools already available for Linux. Auto-updaters are a huge no-no; unless you want to open source your project and provide proper packages in various distros' repositories, Flatpak is the way to go.

**Comment by baszczewski** [comment]
For all interested people, Flatpak package is ready:
https://flathub.org/apps/details/com.getpostman.Postman
https://github.com/flathub/com.getpostman.Postman

**Comment by ghisvail** [comment]
A word of caution: this `flatpak` is not officially endorsed by upstream Postman, and will be purely community maintained (same as Slack or Skype is currently). I have already put that disclaimer explicitly in the app's description but I'd rather repeat it here.

Testing, feedback and PR's for the `flatpak` packaging are warmly welcome.

**Comment by marek-binkowski-sim** [comment]
Another word of caution: I had Postman installed via flatpak and I wasn't able to connect with Chrome via Interceptor. Spent a lot of time trying all possibilities. Finally I uninstalled it from flatpack and installed it by direct download. Interceptor connected immediately!

Additionally, I couldn't make use of the update feature of Postman when installed via flatpak. It could be me, the error was caused by lack of write permissions, so maybe it is resolvable if somebody knows where to find the files...

**Comment by Amunak** [comment]
Generally apps managed by flatpak can only be updated through flatpak, for consistency. So that's actually a good thing: code of an app should not be writable by that same (or any other, really) app. That's what package managers are for.

The other thing seems like a bug; might be necessary to grant some extra permissions.


________________________________

**Comment by ghisvail** [comment]
Le sam. 22 août 2020 à 14:36, Jiří Barouš <notifications@github.com> a
écrit :

> Generally apps managed by flatpak can only be updated through flatpak, for
> consistency. So that's actually a good thing: code of an app should not be
> writable by that same (or any other, really) app. That's what package
> managers are for.
>

Indeed.

The other thing seems like a bug; might be necessary to grant some extra
> permissions.
>

Feel free to file a bug for it in the Flathub Postman repo.

________________________________
