### ISSUE TITLE
How to reflect correct value in in the test result?

### ISSUE THREAD

**Issue by xsisec** [a85/POSTMan-Chrome-Extension#3750]
Hello everyone,

If my test success I get in the result label "amount" and "name",
instead I would like to have  "Kalle and "1 110,00" presented.

Could someone help me I been tried to log correct the value I am trying to fetch but I don't really succeeded, 

```
var pass = true;
var fail = false;

var body = {
        "name": "Kalle",
        "amount": "1 110,00"
        };
 
 for (var i in body)
        {
            
        result = responseBody.has(body[i]);
        if (result)
            tests[i + " body value is present"] = pass;
            
        
        else
            tests[i + " body value is not present"] = fail;
            //console.log([i]);

        }

```

Could someone help me ?

Thank you in advance

Regards

Elmnas

**Comment by deepakpathania-zz** [comment]
Hey @elmnas If I understand your question correctly, you would like to access the properties in your body object. In your for loop, after you check whether your responseBody has the body object, simply store the `body[i]` in another variable to access them. So something like this.
```javascript
 for (var i in body) { 
    result = responseBody.has(body[i]);
    if (result) {
       var bodyProp = body[i];
       console.log(i + " : " + bodyProp);
   }
}
```
This will give you 
```
name : Kalle
amount : 1 110,00
```

**Comment by xsisec** [comment]
This is definitely more what I looking for now is it just the last part left to assign the BodyProp included in the result so it says Amount: + (BodyProp).

Thank you

**Comment by xsisec** [comment]
I solved it by:

```
var pass = true;
var fail = false;

var body = {
        "name": "Addition",
        "amount": "1 110,00"
        };
 
 for (var i in body)
        {
            
        result = responseBody.has(body[i]);
        var bodyProp =body[i];
        if (result)
            
            
            tests["result is: "+ i +"=" +  bodyProp] = pass;
            
        
        else
            tests[i + " body value is not present"] = fail;
            //console.log([i]);

        };
        
```

**Comment by deepakpathania-zz** [comment]
@elmnas Glad, I could help. 
@prashantagarwal This can be closed.
