### ISSUE TITLE
Change Postman URL for multiple request

### ISSUE THREAD

**Issue by ranujn** [a85/POSTMan-Chrome-Extension#3754]
Hi ,

Can we change URL for multiple request in one go. IS there any feature in postman for this.

I have 300 request for that I need to change end points.

Thanks in Advance

**Comment by prashantagarwal** [comment]
@ranujn We are actively working on this and this will be an addition to our current feature `Find Elements`. For now as a workaround you can export the collection, make your changes using some IDE and then upload the collection file back.

**Comment by ranujn** [comment]
Thanks for the update. Can you please let me know which IDE I can use?

**Comment by augustinfla** [comment]
@prashantagarwal, hi, Do you have a date for this feature?

**Comment by prashikbansod** [comment]
> Thanks for the update. Can you please let me know which IDE I can use?

I tried to use notepad++ to replace all the URL's in the collection, but its replacing all at desired location but not working.
