### ISSUE TITLE
Multi-language suggestion 

### ISSUE THREAD

**Issue by misaya** [a85/POSTMan-Chrome-Extension#3755]
If support the language packages, we will get better feelings

**Comment by prashantagarwal** [comment]
@yemadu Thanks for the suggestion.

**Comment by hjkl950217** [comment]
Also hope to support zh-cn

**Comment by arlemi** [comment]
Closing this since it is a duplicate of #3126.

Please add your input on which language you'd like to see added in the other issue so it's easier for us to track. :)
