### ISSUE TITLE
empty array while sending raw json

### ISSUE THREAD

**Issue by maan6050** [a85/POSTMan-Chrome-Extension#3756]
i am trying to send json data in raw. but getting empty array. i have attached the screenshot please review and provide back feedback about what i might be doing incorrect.

Regards

## App Details:

```
Postman for Mac
Version 4.11.0
OS X 16.4.0 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:
 2. Expected behaviour:
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 4. Screenshots (if applicable)

**Comment by maan6050** [comment]
![issuejb](https://user-images.githubusercontent.com/22326605/32591396-e97d8804-c544-11e7-81e2-49bb4410be54.png)

**Comment by maan6050** [comment]
- actually i am using postman after a long time. so i can i encountered it very recently. 
- I expect the array values in the array.
- i have attached the screenshot already

-

**Comment by prashantagarwal** [comment]
@maan6050 This looks something that your server returned and not the Postman itself. Can you do couple of things.
- Update to latest Postman app (5.3.2).
- Add screenshots of Postman Console after sending the request

**Comment by ghost** [comment]
> @maan6050 This looks like something that your server returned and not the Postman itself. Can you do a couple of things?
> 
> * Update to latest Postman app (5.3.2).
> * Add screenshots of Postman Console after sending the request

I was having the same issue looks like I just misspelled the array in my API.
