### ISSUE TITLE
Https Requests Problem

### ISSUE THREAD

**Issue by notarmara** [a85/POSTMan-Chrome-Extension#3757]
## App Details:
```
Postman for Windows
Version 5.3.2
win32 6.1.7601 / x64
```

## Issue Report:
![image](https://user-images.githubusercontent.com/12168345/32597150-159854be-c536-11e7-8563-a3db73407ce7.png)

I have this problem on https requests both for localhost and for any internal net backend.
I have tried different settings configurations: 

Disabling all on general section:
![image](https://user-images.githubusercontent.com/12168345/32597302-877aab9a-c536-11e7-9129-d5fe76dd6186.png)

Enabling and disabling proxy:
![image](https://user-images.githubusercontent.com/12168345/32597345-ab891170-c536-11e7-9ada-e94fd8a71170.png)

Setting and removing HTTP_PROXY and HTTPS_PROXY env var

Setting and removing certificate:

![image](https://user-images.githubusercontent.com/12168345/32597436-ff90a166-c536-11e7-8fc0-fa1dbb6ab8e7.png)

But I have always the same problem.
this is the console output:
![image](https://user-images.githubusercontent.com/12168345/32597489-2dd6c406-c537-11e7-9c2f-cc533a3ef3c1.png)

With the Chrome app all works well.

Please help me.

**Comment by sdnts** [comment]
@notarmara Can you also try enabling the System proxy (if you use one) to check if that helps? A little more information about the server itself would help us debug this.

**Comment by notarmara** [comment]
@madebysid I have already done this in one of my past attempts. 

I have tried both this solution:

![image](https://user-images.githubusercontent.com/12168345/32789299-c3e23228-c95b-11e7-9628-fb7ad6be4fe9.png)
and this:

![image](https://user-images.githubusercontent.com/12168345/32789347-e35a354c-c95b-11e7-980a-fa83610b2d08.png)

but nothing.

if it can help, this is the output of the console:

this for the first case:

![image](https://user-images.githubusercontent.com/12168345/32789433-1f6e5f36-c95c-11e7-954a-fac1801770ae.png)

this for the second:

![image](https://user-images.githubusercontent.com/12168345/32789491-4454f33c-c95c-11e7-99e7-bd6216f520d7.png)

However the access occurs inside the network, so the proxy should not be needed.

the application server I'm using is wildfly 9.0.2 Final version and

![image](https://user-images.githubusercontent.com/12168345/32789803-019c8f18-c95d-11e7-96c8-3bbcdc2ae597.png)

![image](https://user-images.githubusercontent.com/12168345/32790165-ffe18bfa-c95d-11e7-8b66-af68d9352c00.png)

**Comment by notarmara** [comment]
I finally found the problem and solved it. It's needed to set NO_PROXY environment variable:

set NO_PROXY=localhost,127.0.0.*

adding all hosts of the internal network. 
Please share this information on your guide in order to avoid the same issue for other people.
