### ISSUE TITLE
Logo has disappeared on Windows

### ISSUE THREAD

**Issue by ChrisAllisonMalta** [a85/POSTMan-Chrome-Extension#3762]
## App Details:

```
Postman for Windows
Version 5.3.2
win32 10.0.15063 / x64
```

## Issue Report:
I'm not sure which updated version this happened in but its been there for a while, basically the Postman logo isnt on my taskbar (or whatever its called in Windows10!) Its there on my mac and it for sure used to be. 

![image](https://user-images.githubusercontent.com/11945453/32615321-c631e752-c56f-11e7-93e8-bad77a2319ee.png)

To the right of the VS Code logo is Postman

**Comment by sdnts** [comment]
@ChrisAllisonMalta Thanks for reporting this. Do you use Sync? If yes, can you make sure all your collections are intact (and synced) and try re-installing the app to see if the logo reappears?
I want to verify if this was caused during an update or not.

Please don't try re-installing if you do not use Sync, as this will lead to all your collections and environments to be removed. You'll need to manually take a backup if you want to attempt this.

**Comment by ChrisAllisonMalta** [comment]
Hi @madebysid I just tried uninstalling it and reinstalling it, the logo hasn't appeared again unfortunately

**Comment by sivcan** [comment]
Hi @ChrisAllisonMalta  - Kindly update to the [latest version](https://www.getpostman.com/apps) of the app and let us know if the issue still persists for you.
Feel free to reopen it if it does.

**Comment by ChrisAllisonMalta** [comment]
Hi 
I can confirm that the issue remains on v6.0.10 but on the canary build v6.1.0-canary01 it works ok
I am using windows version 10.0.16299 build 16299

Thanks

**Comment by sdnts** [comment]
Awesome, the canary version should land on our stable channel soon, which will fix this issue for you :)

**Comment by SamvelRaja** [comment]
@ChrisAllisonMalta This had been fixed in our recent 6.1.4 version of the app. Kindly update the app 😄
