### ISSUE TITLE
Postman cloud is saving a request with a folder id that doesn't exist

### ISSUE THREAD

**Issue by correajd** [a85/POSTMan-Chrome-Extension#3763]
## App Details:

```
N/A
```

<!--
Some guidelines: 

1. Please file Newman-related issues at https://github.com/postmanlabs/newman/issues
We have been building a node.js app that ingests collection data from the www.getpostman.com/collections api where we piece together selected folders in our own dynamic collection. We noticed that one of the requests has a folder id of a non-existent folder which is making this process more difficult. 
https://www.getpostman.com/collections/1c9b50cd2ff4cc4493b0
Folder:
{
  name: "C15340 (cancel refund)",
  description: "",
  collectionId: "42334a49-f3b6-28cb-b11a-6edf5cbbb29a",
order: [
    "3a0fb98d-b2e4-0251-a379-18bcf6b51c68",
    "2c86c4f7-0814-d4ee-9d8b-330b556701d3",
    "c6edae14-604c-3ea9-4424-e7a65ae215a5",
    "f121f11d-ed90-ed08-14a4-bcf8a398252c",
    "c985758b-ef12-ba9d-60d4-b2435dead8ab",
    "53e68ed3-e0da-42a3-c7a8-472a61013650",
    "a64ea263-ff09-a223-cbed-03954534f63b"
    ],
  owner: "797723",
  folders_order: [ ],
  id: "57624e7c-f5af-d7dd-4972-28e610275cb1"
}
Request:
{
id: "a64ea263-ff09-a223-cbed-03954534f63b",
headers: "Content-Type: application/json ",
headerData: [
{
key: "Content-Type",
value: "application/json",
description: "",
enabled: true
}
],
url: "https://svc-api-int-1.{{env}}.squaretrade.com:10020/api/warranty/{{rpid}}/basic",
folder: "ebfe43be-f776-fe01-ec18-de6d4f9ef4f0",<<Where did this come from?!
queryParams: [ ], 
preRequestScript: null,
pathVariables: [ ],
pathVariableData: [ ],
method: "GET",
data: [ ],
dataMode: "raw",
tests: "eval(globals.utils); if(responseCode.code === 200){ let { subscription, recurringPaymentDefinition} = JSON.parse(responseBody); tests['subscription table cancelled'] = subscription.status === 'Cancelled'; tests['RPD table cancelled'] = recurringPaymentDefinition.status === 'Cancelled'; if(tests['subscription table cancelled'] && tests['RPD table cancelled']){ postman.setGlobalVariable('warrantyStatus', subscription.status); } } else { tests[`response code is 200 instead of ${responseCode.code}`] = false; postman.setNextRequest(globals.runId ? 'Report Result' : null); } addTestResults(this.request.name, tests);",
currentHelper: "normal",
helperAttributes: [ ],
time: 1506545429880,
name: "GET Warranty Objects",
description: "",
collectionId: "42334a49-f3b6-28cb-b11a-6edf5cbbb29a",
responses: [ ],
rawModeData: "{ "firstName": "TARGET", "lastName": "User", "source": "TARGET_MOBILE", "merchantID": "subscrip_tgrt11212016", "resaleProductID": "RD-SP1499RN3A", "email": "email@email.com", "type": "AMEX", "currencyCode": "USD", "testAddress": { "address1": "142 Main Street", "address2": "", "city": "Orlando", "stateCode": "FL", "countryCode": "US", "zipPostalCode": "32123" } }"
}

**Comment by sdnts** [comment]
Hi @correajd, What were you doing when you encountered this? Did you see a Sync issue modal that made you aware of this error?

**Comment by correajd** [comment]
I was analyzing the json response from the getpostman.com/guid link. I noticed that one of the requests stored a folder id that didn't exist in the collection.

**Comment by SamvelRaja** [comment]
@correajd  Post 6.x version of the app we had fixed a lot data inconsistency issue. 
Kindly try generating the collection link from it 😄
