### ISSUE TITLE
Postman POST method Header Key and custom value will send ISO-8859-1 or UTF-8 

### ISSUE THREAD

**Issue by krishreddy82** [a85/POSTMan-Chrome-Extension#3767]
## App Details:

```
Postman for Mac
Version 4.11.0
OS X 16.4.0 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:
 2. Expected behaviour:
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 4. Screenshots (if applicable)

**Comment by sdnts** [comment]
@krishreddy82 Can you provide a little more info about this? Steps to reproduce would definitely help us debug this.

**Comment by krishreddy82** [comment]
we got the required info. Headers can accept only ISO-8829-1 not UTF. its required the RFC2047 implementation. 

Thanks for reply.
