### ISSUE TITLE
Feature request: Request body support for JS expressions

### ISSUE THREAD

**Issue by leonardschneider** [a85/POSTMan-Chrome-Extension#3768]
It would be great if the request body could support JS expressions, so we could do things like:
```
{
  "number": `1 +2`,
  "string": `"hello"`,
  "null": `null`,
  "array": `[1, 2, 3]`,
  "ignoredOptional": `undefined`,
  "randomIntBetween0And1000": `Math.floor(Math.random() * 1000)`,
  "globalVariableDerivation": `pm.globals.get("count") + 3`
}
```
If the result of the evaluation is undefined, then the whole field is ignored.

**Comment by sdnts** [comment]
@leonardschneider Thanks for the request! We will try to look into supporting more ES6 JS features. I'll let you know here when we make progress.

**Comment by codenirvana** [comment]
@leonardschneider I understood your use case, this can be achieved using the [variables](https://learning.getpostman.com/docs/postman/environments_and_globals/variables/).

I feel we misunderstood this feature request initially as JS expressions can't be evaluated directly in the request body.

**Comment by shamasis** [comment]
This use-case can now be achieved using editable requests from pre-request scripts programmatically. Albeit this specific need to edit "body" is not yet supported. But is in the roadmap in short to mid term. 

The same is being tracked at: https://github.com/postmanlabs/postman-app-support/issues/4808
