### ISSUE TITLE
Windows application crashes searching a large response 

### ISSUE THREAD

**Issue by gm90043** [a85/POSTMan-Chrome-Extension#3769]
## App Details:

```
Postman for Windows
Version 5.3.2
win32 10.0.14393 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there: Occurs more often recently.
 2. Expected behaviour: Search functionality should be responsive.

If a response returns a large set of data (600k+ lines) attempting to search that data causes a huge memory spike and crashes the application. This occurs as soon as the search icon is clicked.

**Comment by sdnts** [comment]
@gm90043 Thanks for reporting this, we will look into this. We're always looking to improve performance, so this would be one place we will focus on.

**Comment by numaanashraf** [comment]
@gm90043 We have created a master thread #4751 to track all issues related to large responses. We would be updating that thread on possible workarounds, planned improvements and releases related to large response performance.
