### ISSUE TITLE
Anchors in published documentation don't scroll to the anchored service

### ISSUE THREAD

**Issue by 5p3c7r3** [a85/POSTMan-Chrome-Extension#3770]
## Issue Report:
 1. Did you encounter this recently, or has this bug always been there: I just encountered this issue, I'm not sure if it has been there before or for how long.
 2. Expected behaviour: The browser should scroll to the service that matches the anchor tag in the URL

## Steps to reproduce
* Navigate to published documentation for a collection
* Scroll down to a folder and expand it
* Click on one of the services and notice that the URL anchor changes
* Copy that new URL and open it in a new tab
* Notice that the browser doesn't scroll down to the anchored service

This is an important feature of the documentation because without it I can't share links to services with my team.

**Comment by godfrzero** [comment]
This is something we've noticed breaking in Chrome 61+, and we're working on a fix for it. I'll update here once we've pushed it out. If you notice it breaking in any other browsers/devices, please let us know.

**Comment by 5p3c7r3** [comment]
Sounds good thank you!

**Comment by YoniWitz** [comment]
I'm still experiencing the same bug, is it only me?

**Comment by godfrzero** [comment]
@jonath23 This shouldn't be happening anymore, are you still seeing this problem?
