### ISSUE TITLE
Feature Request: Option to privatly host documentation

### ISSUE THREAD

**Issue by dantenchghx** [a85/POSTMan-Chrome-Extension#3773]
The formatting of the postman documentation and the ease in which it is created is fantastic. 

Unfortunately, our API is not available for public consumption and is for the use of other internal systems created by the company that rely on the data we store.

As such, we wouldn't want to publicly host any API documentation via postman on the web for all to see, we'd love to see that as part of postman pro or enterprise, the ability to specify our own domain to host this documentation, or alternatively, for postman to create a folder, containing all the code to generate the documentation which can be placed directly within our code base.

**Comment by deepakpathania-zz** [comment]
Duplicate of #3663.

**Comment by a85** [comment]
@dantenchghx You don't need to expose anything publicly. The default view for documentation is private and URLs are accessible only to your team members.

**Comment by dantenchghx** [comment]
@deepakpathania I don't think it's a duplicate, we're not worried about accidental publication - as it's quite obvious I think if it is published or not.

@a85 I understand that, unfortunately not everyone who works in my company uses postman. The company has a lot of employees, all working on different systems, however many of these different systems use our API - as such we are required to keep documentation of our API but these cannot be publicly available at this time. We ideally want the ability to publish API documentation with postman to a private server, rather than hosting it with yourselves. I think it's a matter of preference and I believe having the choice to either host the documentation publicly with postman, or enter details of where to privately host your API documentation is a valid request and a potential selling point of a pro or enterprise licence. Ultimately the documentation aspect is a powerful tool, and it would be a shame for it not to be made full use of for those who cannot publicly host their documentation, but still need to have it somewhere for internal use.

**Comment by a85** [comment]
Sorry but we won't have this on the immediate roadmap. Documentation is not a static HTML/CSS page that we can publish. There are several other systems that will complement docs as part of the full SaaS offering for Pro/Enterprise (annotations, versioning, real-time collaboration etc.). We'll re-open this thread if plans change. I'd recommend using an external library for converting and hosting docs privately if needed.

**Comment by thomasazdon** [comment]
My pains are similar to the above - but moreso from a consolidated set of solutions.  We use AHA for our roadmap - which gives us a good tickets site.  We use Confluence for our documentation that is more - how to etc. Prometheus for system statuses, and postman for API documentation in 3 flavors (user stories, end point by end point models, and how to's.  A client of ours now has 4 login id's and passwords to interact with us. Our client portal and application login, the postman documentation, the Aha website, and the confluence page.  This is not really a tenable situation - it's horrible client service (from us to our clients).  What we desire is the ability to embed the postman documentation in our website so users login to our website and then arrive at the postman documentation.  1 login to rule them all.

**Comment by timmeade** [comment]
Agreed Concur with @thomasazdon almost same situation here.

**Comment by scriptsure** [comment]
@a85 is there any progress having a single user name and password or bearer token that could be used to secure the docs? We are a commercial healthcare (i.e. HIPPA) company and do not want to share docs with everyone.

**Comment by makkaba** [comment]
same demand here.

**Comment by LukeXF** [comment]
Any update on this?

**Comment by rikeppb** [comment]
> My pains are similar to the above - but moreso from a consolidated set of solutions. We use AHA for our roadmap - which gives us a good tickets site. We use Confluence for our documentation that is more - how to etc. Prometheus for system statuses, and postman for API documentation in 3 flavors (user stories, end point by end point models, and how to's. A client of ours now has 4 login id's and passwords to interact with us. Our client portal and application login, the postman documentation, the Aha website, and the confluence page. This is not really a tenable situation - it's horrible client service (from us to our clients). What we desire is the ability to embed the postman documentation in our website so users login to our website and then arrive at the postman documentation. 1 login to rule them all.

Hey there!
How do you share the Postman documentation with your clients, is it by inviting them to a Postman Team and sharing there?
