### ISSUE TITLE
Runner doesn't run the collection and returns error "request url is empty".

### ISSUE THREAD

**Issue by viraxslot** [a85/POSTMan-Chrome-Extension#3774]
Hi guys,

## App Details:
```
Postman v5.3.2 desktop app.
Win 10 Pro, build 1709
```
Steps to reproduce problem:
**1. Add new collection "TestCollection"**
**2. Add new GET-request with variables**
http://{{host}}/api/flight?orig={{orig}}&dest={{dest}}&dep={{depDate}}&ret=&adt={{adtCount}}&chd={{chdCount}}&inf={{infCount}}

The result link is: http://somehost/api/flight?orig=XXX&dest=XXX&dep=20171115&ret=&adt=1&chd=0&inf=0
Without any dots in domain name.

**3. Add headers:**
Content-Type: application/json
X-Application-Type: WebApp
**4. Add environment with variables** 
**5. Click "Send"** Everything is ok.
**6. Go to Collection Runner**
Select the same environment, select collection, run.

**Expected:** response is returned.
**Actually:** error "Error: runtime:extenstions~request: request url is empty" in Postman console.
**In DevTools:**
[postman_error.txt](https://github.com/postmanlabs/postman-app-support/files/1461849/postman_error.txt)

Please tell me where I was wrong.
Many thanks.

**Comment by alphabetek** [comment]
I guess you are missing a step before 6, click button "Save".

**Comment by viraxslot** [comment]
@alphabetek there is no "save" button at all.

**Comment by alphabetek** [comment]
Normally there is a button "Save":
![image](https://user-images.githubusercontent.com/5899023/32718450-757b7184-c85d-11e7-8d19-4f47c1ddd485.png)

**Comment by viraxslot** [comment]
@alphabetek omg, sorry and thanks. Strange UI logic for me.

**Comment by d4hines** [comment]
This got me too. The part that tripped me up was everything else was working: sending the request, the collection, the mock server, but not the runner. So glad I found this thread, because I was stumped!

**Comment by alvagenesis** [comment]
Same here! I have to hit the save button for every request in the collection before i was able to run it.

**Comment by dsreenivas** [comment]
Solution for :Runner doesn't run the collection and returns error "request url is empty".
Before going to Collection runner, save the individual request and go to Collection runner and run it, it will work.
It work's for me, when i did the same.

**Comment by nurikabe** [comment]
Interface would be a lot more clear if the save state was somehow reflected:  Color of the save button, a "last saved" timestamp, etc.

**Comment by Daemon42** [comment]
Wasted quite a lot of time before I found this topic.   This is definitely very confusing, because when you click on the request under the collection, it shows all the latest changes, even if it's not saved.   I even closed Postman and reopened it and these apparently unsaved requests were still there.  I just couldn't figure out why the Runner wouldn't run them.    
Agree that change in state of the Save button would be nice, or a little * next to the unsaved requests under the collection itself.

**Comment by saifalfalah** [comment]
Same thing happened to me too. I forgot pressing save and created the monitor.

**Comment by aravindUnleashed** [comment]
I don't understand the use of Save logic here. The collection is always there when you close and open PostMan.

**Comment by chrisgel15** [comment]
It got me too as well :(

**Comment by monica017** [comment]
Wasted tons of time before finding this.

**Comment by ThornBirdlx** [comment]
终于解决了，这个操作很让人郁闷

**Comment by 18549** [comment]
The UI is quite obtuse in this area.

Why should whether a request is saved even have any impact on whether it can be run in the collection runner? If the request can be run using its current state in the main window it makes no sense whatsoever that it cannot be run in the collection runner.

'Save' means 'will this object's state be persisted if I close the application'. Not 'does this thing exist in all aspects of this application or only some of them (with no way of knowing which)'.

And the Save button itself on the main window is totally inconspicuous and provides no feedback as to whether the request is saved or not.

**Comment by ericprud** [comment]
Is there an issue to improve the UI wrt the user not knowing to do an apparently superfluous save? I took a timed screenshot to capture the error and duckduckgo'd it immediately, so I only lost about 5 mins, but this appears to cumulatively cost many thousands of user hours.

**Comment by sumanasindhu** [comment]
Thanks for the post

**Comment by MichaelBrooks-Version1** [comment]
Same here. After over 30 years in this industry it never ceases to amaze me how bad some user interfaces can be. Thanks.

**Comment by emremrah** [comment]
Why there is an option as selecting data file if it's gonna use the saved request anyway?

**Comment by gillallifam** [comment]
I request the implementation of auto save.

**Comment by pteki5** [comment]
Thanks, saved.

**Comment by xar3f** [comment]
this article and solution save me in 2021.

**Comment by atish53481** [comment]
It work for me 
Save the Collection and also make sure that you are following the proper Collection pattern 
![image](https://user-images.githubusercontent.com/48210584/157736463-3f261e75-ac52-4348-92c6-9e3deaf42496.png)

**Comment by ra-hul** [comment]
> I guess you are missing a step before 6, click button "Save".

thank you. it saves meee. thanks a lot

**Comment by agrawalsmart7** [comment]
Just use, CTRL+S

**Comment by Wangxin09** [comment]
感谢🙏，还真的没有保存的原因。
![image](https://github.com/user-attachments/assets/8c69e540-833c-499f-881b-9cc4d48cf5d8)
