### ISSUE TITLE
Encoding of URL paths is incorrect

### ISSUE THREAD

**Issue by armpogart** [a85/POSTMan-Chrome-Extension#3778]
## App Details:

```
Postman for Windows
Version 5.3.2
win32 10.0.16299 / x64
```

## Issue Report:
 1. I use the request that is working in chrome app, but in native app I get `incorrect symbols in header` response from the API server, it's something with request encoding, I have russian characters in request endpoint name and it is working ok in chrome app. Request is something like `http://endpoint:port/odata/standard.odata/Catalog_Пользователи?$format=json`
 2. Expected behaviour: correct response
 3. In Dev Tools console I see one error - `Failed to load resource: net::ERR_FILE_NOT_FOUND - mode-auto.js`

**Comment by armpogart** [comment]
Maybe something related to https://github.com/postmanlabs/postman-app-support/issues/2263

**Comment by armpogart** [comment]
Also if I encode url manually and use the encoded string there - everything is working.

**Comment by sdnts** [comment]
@armpogart Thanks for reporting this, we will investigate this. @kamalaknn This looks related to runtime. Related: #3734, #3765

**Comment by armpogart** [comment]
Any progress on this one?

**Comment by shamasis** [comment]
Note: We need more details, perhaps a scaled down collection and/or endpoint to reproduce this.

**Comment by armpogart** [comment]
@shamasis I guess any endpoint with `Cyrillic` letters in url. In my case it was [1C](https://1c-dn.com/1c_enterprise/what_is_1c_enterprise/) platform with it's odata endpoints. Unfortunately the endpoint I was working with is private and I don't have any public one at this moment.

**Comment by gdomo** [comment]
Postman 6.4.4
Ubuntu 18.04.1 LTS

 `абвгдеёжзийклмнопрстуфхцчшщьыъэюяАБВГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧШЩЬЫЪЭЮЯ`

turns in
`012345Q6789:;<=>?@ABCDEFGHILKJMNO����������������� !"#$%&'(),+*-./`

Example:
![image](https://user-images.githubusercontent.com/38424025/47425582-70f3f280-d793-11e8-9302-a39699a9a2f3.png)

**Comment by shamasis** [comment]
Closing it as a duplicate in master issue: https://github.com/postmanlabs/postman-app-support/issues/4555

**Comment by shamasis** [comment]
Closing it as a duplicate in master issue: https://github.com/postmanlabs/postman-app-support/issues/4555

**Comment by codenirvana** [comment]
This is fixed in the latest version of the Postman app (v7.20.0) by enabling the "Use next generation URL processing" setting as mentioned in #8154.
