### ISSUE TITLE
Getting undefined on running tests using data object

### ISSUE THREAD

**Issue by azharmohammedk** [a85/POSTMan-Chrome-Extension#3782]
## App Details:
Postman helps you develop APIs faster
Postman for Windows
Version 5.3.2
win32 6.1.7601 / x64
```

## Issue Report:
 1. Here is my test that I am running under 'test' section in postman
pm.test("Check data function", function(){
    console.log('Input sent in this case is '+ data.query_string);
});
 2. Expected behaviour: 
I have entered "query_string" as "test" in my testdata json file and expect 'Input sent in this case is test' to be printed inside the postman console. This is my testdata json file

[{
    "query_string": "test"

}]

 3. Console logs 
But I get --> Input inside the test is undefined

**Comment by SamvelRaja** [comment]
@azharmohammedk  I tried the same scenario from my end, it is working as expected. 
can you provide us a screencast of the exact problem you are facing, would be easy for us to debug.
Also, attaching the way I tried out from my end.

![testing data](https://user-images.githubusercontent.com/5114052/32830379-f85165be-ca1a-11e7-8e79-37038c913e3c.gif)

**Comment by azharmohammedk** [comment]
Thanks. It was a user error. I will close this.
