### ISSUE TITLE
Cursor misaligned

### ISSUE THREAD

**Issue by bramhaag** [a85/POSTMan-Chrome-Extension#3783]
## App Details:
```
Postman for Linux
Version 5.3.2
linux 4.13.11-1-ARCH / x64
```

## Issue Report:
Cursor is misaligned when typing in the Body > Raw textbox, this happens in the normal view and Two-Pane view. See this gif for more information: https://owo.whats-th.is/1c62ff.gif

Increasing/decreasing postman's font size does not appear to affect the offset of the cursor

**Comment by sdnts** [comment]
Hey @bramhaag, did you, by any chance, change the typeface that is used in these editors? We use a monospace typeface by default, and the offset is based on that.

**Comment by bramhaag** [comment]
I haven't changed fonts for postman specifically. [These](https://owo.whats-th.is/daf699.png) are the fonts selected in the gnome tweak tool.

**Comment by stephenhillier** [comment]
I'm also getting the same problem. Same distro (arch). I installed postman-bin from AUR.

It seems that the cursor is aligned based on monospace character spacing but the actual characters are a non-monospaced font.

Is there a way to change the font or make sure I have the one I need?

**Comment by ChristofferKarlsson** [comment]
Did anyone of you find out why this is happening?
I'm also on Arch and I am experiencing the same problems. Have tried both `postman` and `postman-bin` from the AUR.

```
Postman Linux 6.0.10
Linux 4.15.13-1-ARCH
```

**Comment by fracalo** [comment]
I experienced the same problem and the issue was caused by postman not finding a correct monospace font.   
To check if your `monospace` font is correctly aliased on arch  control what  `fc-match monospace` is referencing,   
if it points to some non-monospace font that is the  reason you get a misaligned textarea in the UI.

To fix this you'll need to modify `etc/fonts/local.conf`.
as an example this is mine:
```
<?xml version="1.0"?>
<!DOCTYPE fontconfig SYSTEM "fonts.dtd">
<fontconfig>
    <match target="pattern">
        <test qual="any" name="family"><string>serif</string></test>
        <edit name="family" mode="assign" binding="same"><string>Noto Serif</string></edit>
    </match>
    <match target="pattern">
        <test qual="any" name="family"><string>sans-serif</string></test>
        <edit name="family" mode="assign" binding="same"><string>Noto Sans</string></edit>
    </match>
    <match target="pattern">
        <test qual="any" name="family"><string>monospace</string></test>
        <edit name="family" mode="assign" binding="same"><string>Noto Mono</string></edit>
    </match>
</fontconfig>

```

**Comment by prashantagarwal** [comment]
Related to #2985
