### ISSUE TITLE
Desktop icon is created without user permission

### ISSUE THREAD

**Issue by cherepets** [a85/POSTMan-Chrome-Extension#3788]
## App Details:
```
Postman for Windows
Version 5.3.2
win32 10.0.16299 / x64
```

## Issue Report:
After the installation Postman creates desktop icon without any question/permission.
Even if you manually delete it, it will reappear after the next update.

**Comment by sdnts** [comment]
@cherepets Thanks for reporting this. We have been looking to have a more customizable installer in the future, will take this into consideration. You can follow #3019 for updates :)
