### ISSUE TITLE
Postman is not responsive with large requests

### ISSUE THREAD

**Issue by joe94** [a85/POSTMan-Chrome-Extension#3790]
## App Details:

```
Postman for Mac
Version 5.3.2
OS X 10.12.6 / x64
```

## Issue Report:
 1. I recently found this issue.
 2. I expect the app to stay responsive no matter how many requests I have sent through it and no matter what kind the requests were.

## Steps to reproduce the problem

1. Simply generate a couple of requests with URLs of length > 60k characters
2. Now try to use the app as you normally would. 
3. You will notice that almost everything in the app UI is slower.

## Note
I understand the assumption might have been that URLs are relatively short strings. That said, if optimizations cannot be made against large requests (maybe because they have to be brought in from disk), at the very least rules should exist to prevent these slow down the app (i.e. like not keeping these long requests in history for too long).

**Comment by SamvelRaja** [comment]
we are already tracking this issue here #793. Closing this as duplicate
