### ISSUE TITLE
Need to export Request Body in JSON Report through Collection Runner

### ISSUE THREAD

**Issue by ranujn** [a85/POSTMan-Chrome-Extension#3791]
I want to export Request and Response Body in the JSON Report through Collection Runner.
To export Response Body I written below statement
                 tests["Response:"] = responseBody;
But I am not able to export Request in same way. Can you someone please let me know how I can export Request Body in the Report.

Thanks in Advance.

**Comment by kunagpal** [comment]
@ranujn You can do this as explained below:
```js
tests["Response:"] = pm.response.text();
tests["Request:"] = JSON.stringify(pm.request);
```

**Comment by ranujn** [comment]
@kunagpal Thanks for your reply.

I am very new to JSON. I dont know what pm var represent to. Can you please let me know how I can define pm var.

**Comment by kunagpal** [comment]
@ranujn You don't have to define the `pm` variable, it is inbuilt within the Sandbox, like `tests`.

**Comment by ranujn** [comment]
@kunagpal Its giving me attached error 
![image](https://user-images.githubusercontent.com/33507161/32875517-7e5b59ea-caec-11e7-8c82-816475057ad9.png)

**Comment by kunagpal** [comment]
@ranujn It looks like you're on the Chrome app, or an older version of the Native app. Could you update to v5.3.2 and confirm if this issue persists? Thanks!

**Comment by ranujn** [comment]
@kunagpal Thanks for quick response.

I was using Chrome app. Its working in Native app. but through this statements, Request and Response both are not exported in the report.
Its coming like this
"tests": {
				"Status code is 201 Success with valid details": true,
				"Response:": true,
				"Request:": true
	    }

I want exact body which I am passing and Response that I am getting.

**Comment by ranujn** [comment]
@kunagpal  Is there any way to get request and response body in the Report. I used statement provided by you but its showing only status of test case pass and failed, not the actual request and response.

Thanks in Advance.

**Comment by a85** [comment]
@ranujn Not at the moment.

**Comment by atul-shl** [comment]
is there any plan to export response body in report in near future? It will be a great if this feature is incorporated

**Comment by cnidus** [comment]
Also hitting this myself. Would really like to capture ResponsBody in runner results.

**Comment by sneh208** [comment]
Is there a quick way where I can pull only failed requests (request body) in json or any document?
