### ISSUE TITLE
Can't order Test in Folders, Adding a test to a folder puts the file in Random Folder

### ISSUE THREAD

**Issue by ugenlik** [a85/POSTMan-Chrome-Extension#3792]
## App Details:

```
Postman for Mac
Version 5.3.2 (5.3.2)
OS X 10.12.6 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there: always there
 2. Expected behaviour:Should able to re-order tests suits and folders 
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
![screen shot 2017-11-13 at 6 04 42 pm](https://user-images.githubusercontent.com/1995917/32754012-29f7a710-c89d-11e7-8596-4087eb53c9ef.png)
 4. Screenshots (if applicable)
![postmanbug](https://user-images.githubusercontent.com/1995917/32754015-2ec84ca4-c89d-11e7-9b8b-c9b8ce1b0ce9.gif)

**Comment by SamvelRaja** [comment]
Tracking in #3614
