### ISSUE TITLE
Add better documentation on how to migrate Interceptor workflows to Native Postman 

### ISSUE THREAD

**Issue by mliq** [a85/POSTMan-Chrome-Extension#3793]
Since you now are hoping for us to move away from the Chrome app, you should really provide better documentation on how to migrate our workflows to the Native app. Interceptor plugin was very easy, proxy not as much (I have spent 10 minutes and have not got it working, fortunately I can just stick with Chrome Postman for now).

Currently your docs show a use case of capturing iphone requests, which I do not need, and a link to an outdated and unmaintained Apple support page which also is not particularly helpful.

My use case is to capture my chrome activity in Postman on the same Mac, and I use it very frequently. (Mainly, to get all the headers needed for a request into Postman).

Also, I foresee issues with using the system proxy rather than only Chrome from an overflow of data from other running apps, but we will see about that. Perhaps add details on how to filter these out in your instructions please.

Thank you!

**Comment by SamvelRaja** [comment]
@mliq I can understand your concerns and I will put forward your points to the team when we have this on our roadmap. And keep you posted on the status as well.

**Comment by brianquintin** [comment]
I currently use Interceptor to authenticate a session in chrome, allowing me to use Postman without even having to touch any cookies--the Postman chrome app automatically uses the browser session passed by Interceptor. If there is a way to enable this flow in the Native app, I'd love to see it documented.

**Comment by sivaprabug** [comment]
I am struggling with same issue, How can i handle the session in Native App. Before i am using simply install interceptor extension and postman extension.

when ever i launched the session **_just turn on interceptor_** icon the session all cookies capture in postman app.

but now **really difficult to handle**, we don't know how capture sessions

**Comment by ottens** [comment]
I would love to see better documentation on this as well. In my normal workflow I log in to a website via Chrome and then after that use Postman to test API request for an already authenticated session without having to worry about authentication, replicating that functionality in Postman would be awesome. One way would be to add a basic browser to Postman, not sure if that would be an option.

**Comment by benoitcerrina** [comment]
For the same reason mentioned above I have not been able to use the native app.  The app I am working on requires an authenticated session and I can test webservice calls easily with the chrome app, I haven't found how to do it with the native app

**Comment by nlaffey** [comment]
I've also been frustrated by communication around the how to use the interceptor feature with the Native App. The documentation makes it seem like this is possible but I haven't been successful.

**Comment by geoffrothman** [comment]
@vkaegis I can't get the chrome interceptor plugin to work with Postman on the Mac either. I followed the instructions, removed port 5555 in the native app and chose History but nothing shows up. any ideas? How else would I troubleshoot API requests in my chrome browser??

**Comment by Pictor13** [comment]
The "capturing + editing request + execute new request" was also my main use cases (actually the capturing feature is the only reason why I chose Postman over other tools); now it seems to not be possible anymore.

The proxy feels broken. Accessing it via http/https returns a generic error message (*"Something went wrong. And we are reporting a custom error message"*). The native app reports "Proxy Connected" successfully.
But nothing is captured.... except for urls relative to **localhost**.

**Comment by tithisharma98** [comment]
> Since you now are hoping for us to move away from the Chrome app, you should really provide better documentation on how to migrate our workflows to the Native app. Interceptor plugin was very easy, proxy not as much (I have spent 10 minutes and have not got it working, fortunately I can just stick with Chrome Postman for now).
> 
> Currently your docs show a use case of capturing iphone requests, which I do not need, and a link to an outdated and unmaintained Apple support page which also is not particularly helpful.
> 
> My use case is to capture my chrome activity in Postman on the same Mac, and I use it very frequently. (Mainly, to get all the headers needed for a request into Postman).
> 
> Also, I foresee issues with using the system proxy rather than only Chrome from an overflow of data from other running apps, but we will see about that. Perhaps add details on how to filter these out in your instructions please.
> 
> Thank you!

Hi @mliq @Pictor13 @geoffrothman , 

We are doing some interventions around how can we make the interceptor more accessible and understandable in our native application. Would you be interested to get on a quick 35 mins call to help us understand the uses cases better? :) 

Do let us know!

**Comment by shashankawasthi88** [comment]
Hi, @mliq @Pictor13 @geoffrothman do let us know your experience with the latest version of the app. If the interceptor/ proxy is accessible and easy to understand or not.

**Comment by shashankawasthi88** [comment]
The documentation is updated to clearly mention the steps required to enable proxy and interceptor. Closing this for now. Feel free to reopen if you see a gap in the documentation.
