### ISSUE TITLE
 Hope to add Chinese version

### ISSUE THREAD

**Issue by ghost** [a85/POSTMan-Chrome-Extension#3794]
Hope to add Chinese version.
## App Details:

```
Postman for Mac
Version 4.11.0
OS X 16.4.0 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:
 2. Expected behaviour:
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 4. Screenshots (if applicable)

**Comment by SamvelRaja** [comment]
Tracking in #3755
