### ISSUE TITLE
Allow linux support for the embed button

### ISSUE THREAD

**Issue by nkaraolis** [a85/POSTMan-Chrome-Extension#3798]
## App Details:

```
Postman for Linux
Version 5.3.2
linux 4.10.0-38-generic / x64
```
## Feature request:
Hello I have just used the share and embed button feature to allow postman tests to be run on a github readme file. It picks up the markdown correctly and is able to find the collection as expected.

However, it doesn't pick up the linux version I have installed. Would it be possible to extend the embed button to allow linux support?

**Comment by SamvelRaja** [comment]
@nkaraolis Yeah, the support needs to be provided from the electron framework we use for our native apps, where they are currently developing the feature, I shall update the same thread when we adopt the version in our app.

**Comment by mautematico** [comment]
I'm facing this same issue.

Can't postman collections be downloaded and then imported, or something?

**Comment by vkaegis** [comment]
Hey guys, this is now available. You can refer to this blog post for more details: http://blog.getpostman.com/2018/10/16/run-in-postman-is-now-available-for-linux/

Feel free to open another issue if you have more feedback around this.
