### ISSUE TITLE
Xdebug

### ISSUE THREAD

**Issue by LimeBlast** [a85/POSTMan-Chrome-Extension#380]
I'm interested in using POSTman with XDebug, but can't seem to figure out how to make it work.

My current set-up (via a browser) involves using PHPStorm's bookmarklette (http://www.jetbrains.com/phpstorm/marklets/) to start the xdebug session - maybe something like this can be baked into POSTman?

Cheers.

**Comment by goalain** [comment]
I solved it:
1) connect to the server in another tab and activate xdebug (the bug icon in the url line)
2) in the postman tab, click the Headers button
3) add a Header (on the left side), type: Cookie
4) add a Value (on the right side, type: XDEBUG_SESSION=netbeans-xdebug

![screenshot from 2015-01-15 17 58 40](https://cloud.githubusercontent.com/assets/6030621/5761079/a5f6e4f6-9ce1-11e4-829c-dd67e76dbd61.jpg)


Maybe it can work wihout bringing up the debugger in another tab, by using
XDEBUG_SESSION_START=netbeans-xdebug
but i didn't tested it.

Also, if you use another debugger than netbeans, you will have to figure out yourself what to put on the right side of the "=". I figured it out with wireshark (a sniffer) to see what's in there.

**Comment by mohitagrawaltruelancer** [comment]
@goalain Thanks i worked

**Comment by tripflex** [comment]
POSTMAN is now showing exclamation when using "Cookie" header type and says to use Interceptor .... is this really the case, you have disabled setting the Cookie header value to force people to use interceptor???

**Comment by abhijitkane** [comment]
@tripflex No. The new Postman app cannot set the cookie header. The XHR API explicitly forbids this (https://developer.mozilla.org/en-US/docs/Glossary/Forbidden_header_name). We have to make use of the Interceptor to send cookies.

**Comment by tripflex** [comment]
Ahhh, **I apologize for my ignorance and appreciate your very quick response.**  

Is there any way to prevent existing cookies in Chrome from being automatically used in POSTMAN requests?  My problem is i'm trying to set my XDEBUG cookie but everytime I do it pulls in the WordPress cookies, which throws an error because REST API does not support OAuth and Cookie authentication at the same time.

Thanks!

**Comment by abhijitkane** [comment]
With the Interceptor on, you can manage cookies from chrome://settings/cookies
