### ISSUE TITLE
[Feature Request] - Allow Users to move the Response Body window to a different screen/monitor

### ISSUE THREAD

**Issue by Faz540** [a85/POSTMan-Chrome-Extension#3800]
I know there's a "two pane" selector in the app settings so we can see the Body and Response Body either side, however, **I'd like the ability to detach the Response Body and move that to a different screen/monitor.**

This way, the request body gets a full screen to itself and so does the Response Body 😄 
This means I won't have to deal with the response body window getting in the way whilst writing/modifying the request body and having to deal with multiple scroll bars.

When dealing with a large Tests section and a large Response Body, each one has a scroll bar and ontop of that there is a scroll bar for the app 😱 

Sorry if this has already been raised but I couldn't find it.

**Comment by SamvelRaja** [comment]
Since #3513 covers the same feature, closing this in favor of it.
