### ISSUE TITLE
Enable autocompletion for Postman Sandbox API

### ISSUE THREAD

**Issue by Faz540** [a85/POSTMan-Chrome-Extension#3801]
Hi,
I'm liking the new "pm" syntax and I'm sure it's still a work in progress at the minute, but here's a little suggestion to make writing tests quicker.
Just a suggestion, can we change "environment" to "env" to make tests cleaner.
Instead of calling
```
 pm.environment.get("name");
```
We could call:
```
pm.env.get("name");
```

**Comment by sdnts** [comment]
@Faz540 Thanks for the feature request! In the mean time, you can also use pm.variables (which will look for the variable in the environment as well as global) if that looks neater.
@shamasis Thoughts?

**Comment by pratiks** [comment]
I would propose auto-complete over abbreviating the word.  While I also wish it was env over environment, there is cost associated with updating my scripts to reflect pm.env. 

Auto-completion on the other hand would provide writing tests faster overall, not only for the environment module.

**Comment by kamalaknn** [comment]
Hey @Faz540 @pratiks 

We are tracking improvements for autocompleting sandbox API in #3919.
