### ISSUE TITLE
Runner is now crashing every time I run it

### ISSUE THREAD

**Issue by ZuechB** [a85/POSTMan-Chrome-Extension#3802]
## App Details:
Postman for Windows
Version 5.3.2
win32 10.0.16299 / x64

When I run runner it gets about half way down and then just crashes, I can select a batch at a time and run each batch fine, but that defeats the purposes of being able to test all my apis in one shot.  Let me know if I can help in anyway

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there: This just started happening recently
 2. Expected behaviour: runner should complete as normal

Steps to reproduce the problem
**Run Runner with a ton of post and get requests in each folder**

**Comment by SamvelRaja** [comment]
@ZuechB are you seeing any kind of error on the console before the crash?
View -> ShowDevTools for opening the dev console.
