### ISSUE TITLE
Mismatch between api data returned in browser vs Postman Desktop App

### ISSUE THREAD

**Issue by zac11** [a85/POSTMan-Chrome-Extension#3804]
## App Details:

```
Postman for Windows 
Version 5.3.2
Windows 1o/ x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there: 
Encountered this issue today itself.
 2. Expected behaviour:
When hitting an API endpoint that has special characters like % in the url, the output returned should be same between Chrome browser and Postman. 

Chrome browser returns a JSON when the endpoint is hit, while Postman returned the data in `text/csv`. 

 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app): None
 4. Screenshots (if applicable)
Can add if asked.

Just hit the API end point in Postman and Chrome separately. 

Additional Information : The backend API is a Ruby on Rails API, which calls a SOLR service which returns data in `text/csv` if specified in parameters. However, this is not specified in the parameter or the url in any way

The url is something like http://basepath.com/path1/something/row_num=1&param_1=%5FIndustry%2Fparam_2=%2F%Something&sort=asc

If I add an explicit `format=json` in the url like this

http://basepath.com/path1/something/row_num=1&param_1=%5FIndustry%2Fparam_2=%2F%Something&format=json&sort=asc

then Postman returns a JSON output.

Why is this happening and how can I overcome this. Searching on SO returned solutions to switch the language detection to JSON from Settings, but it doesn't help

**Comment by SamvelRaja** [comment]
@zac11 
Postman sses the content-type header sent by the server to display the response in JSON / XML / HTML / Text format.

You can very well open our postman console (view - Show postman console) to check the network call we made to the server.

Also, regarding %, can you provide me bit more insight on what was the expected and the actual behavior?

**Comment by zac11** [comment]
@SamvelRaja Thanks for looking into it.

I will surely take a look at the console tomorrow in office.

Regarding the output , I would expect both chrome and POSTMAN to return json formatted output. 
The % is in the URL  params itself.

**Comment by zac11** [comment]
So, I had a look at the console for Postman and the request doesn't tell much either

![2017-11-16_1218_1](https://user-images.githubusercontent.com/8002297/32877726-ee7544d0-cac8-11e7-9ae5-f114594183be.png)


The response headers are

![2017-11-16_1221_1](https://user-images.githubusercontent.com/8002297/32877747-0396e17a-cac9-11e7-92a1-9b7552a39394.png)

You see the response has content type `text/csv`, while if I hit the same url without changing any single thing in Chrome, it returns a json response

![2017-11-16_1225_2](https://user-images.githubusercontent.com/8002297/32877825-56c7f97e-cac9-11e7-89f5-52736ff50416.png)


What could explain this mismatch??

**Comment by zac11** [comment]
any updates on this one @SamvelRaja ?

**Comment by SamvelRaja** [comment]
@zac11 Can you check the request headers you are receiving from postman vs the chrome browser. 
And regarding the display of response, as I mentioned above the response format is based on the response header we receive. 

Closing this, as this is not seems to issue from Postman.

**Comment by pabloleone** [comment]
I'm facing the same issue. Seems that postman is using Chrome cookies and it depends the session you have opened the response you'll get from postman. Chrom is not using the session when requesting from a different domain and that's why you get different responses. I'm in hell trying to see how to prevent this to happen.

**Comment by tctrautman** [comment]
Hi @pabloleone 👋 !  Did you ever figure this out / do you happen to remember how you resolved this?
