### ISSUE TITLE
Receiving intermittent Error running scripts: JSONERROR | Unexpected token '<' at ...

### ISSUE THREAD

**Issue by ryanhinton** [a85/POSTMan-Chrome-Extension#3806]
Hello,

I am receiving intermittent errors randomly on the Runner and my Newman execution.  Sometimes it runs perfectly and more often I receive the error mentioned in the subject line.  When I run the test individually, most of the time it works fine, but on a blue moon it will give the error, but if I try again it then works without changing anything.  I know the scripts work, so I cannot understand the problem with the this intermittent error.

## App Details:
Postman helps you develop APIs faster
Postman for Windows
Version 5.3.2
win32 6.3.9600 / x64
Website
Twitter
Licences
Changelog
Documentation
Report an issue
```
Postman for Mac
Version 4.11.0
OS X 16.4.0 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:
Started happening in the past month
 2. Expected behaviour:
No errors
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 4. Screenshots (if applicable)

![image](https://user-images.githubusercontent.com/11085554/32810238-1d2f2fe6-c968-11e7-8c4f-2e9359b1db79.png)

**Comment by SamvelRaja** [comment]
The error shows like, you are doing JSON.parse(response) on an HTML response.

**Comment by ryanhinton** [comment]
Thank you for your response.  You just guided me into realizing that the problem is indeed a code problem and it is related to an update of a framework I am using.  Have a good day!
