### ISSUE TITLE
double evaluations (in desktop client only)

### ISSUE THREAD

**Issue by mnimer** [a85/POSTMan-Chrome-Extension#3808]
## App Details:
```
Postman for Mac
Version 5.3.2
OS X 17.2.0 / x64
```
compared with
```
Postman for Chrome
Version 5.3.2
OS X / x86-64
Chrome 61.0.3163.100
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:
This has been around for awhile. It breaks in the desktop client and works in the old chrome app

 2. Expected behavior:
Variables should only be evaluated once per request

If I try to use {{$guid}} more then once it is re-evaluated every time, but only in the desktop app. This makes it impossible to put the same id into two places. 

This is also true if I try to set a variable in a pre-request script and use it twice, both times it is reevaluated.

I can understand that the $guid variable is re-evaluated every time. I don't like it but I get it if it has to be. However, the pre-request script should only be evaluated once so I can get a value to use more than once.

On Desktop Client: 
post to: https://postman-echo.com/post

Pre-Request Script:
postman.setGlobalVariable("newUuid", "{{$guid}}");

JSON Body: 
{
	"field1":"{{$guid}}",
	"field2":"{{$guid}}",
	"field3":"{{newUuid}}",
	"field4":"{{newUuid}}"
} 

Desktop Results, notice how all 4 UUID's are different
"data": "{\n\t\
"field1\":\"0fa08a71-897e-4a61-b5f6-fe67533916ef\",\n\t\
"field2\":\"310442eb-bdbf-40ff-8802-7c623dff3890\",\n\t\
"field3\":\"b62acdf7-e431-43a7-baf5-88d03722e0e3\",\n\t\
"field4\":\"23d74265-1631-4f7f-9a4c-d9ea18e7bf17\"\n}",

Chrome App Results, notice how all 4 UUID's are the same
"data": "{\n\t\
"field1\":\"c96f6525-73d1-4537-99af-9ea1fde07a78\",\n\t\
"field2\":\"c96f6525-73d1-4537-99af-9ea1fde07a78\",\n\t\
"field3\":\"c96f6525-73d1-4537-99af-9ea1fde07a78\",\n\t\
"field4\":\"c96f6525-73d1-4537-99af-9ea1fde07a78\"\n}",

**Comment by kamalaknn** [comment]
@mnimer Postman now generates a new UUID for each usage of `$guid`. It's been this way since the introduction of our native apps, changing it now might break things.

You can still achieve the same effect with `{{myUuid}}` in body, and the following in your pre-request script
```
var uuid = require('uuid');

// generate `uuid` once and put it on a variable
// this is the exact uuid you would get with a `$guid`
pm.globals.set('myUuid', uuid.v4());
```

Hope this helps, closing this issue for now. Feel free to continue the discussion here.

**Comment by mnimer** [comment]
requiring and using uuid.v4() is a simple enough. Thanks!
