### ISSUE TITLE
Verification of Module, sub module response body(Partially and completely)

### ISSUE THREAD

**Issue by amitavmishra** [a85/POSTMan-Chrome-Extension#3809]
## App Details:

```
Postman for Windows
Version 5.3.2
Win 7
```

## Issue Report:
The Response which I am getting is 
{
    "recordCount": 5,
    "items": [
        {
            "id": 1,
            "name": "30 "
        },
        {
            "id": 2,
            "name": "17 "
        },
        {
            "id": 3,
            "name": "66"
        },
        {
            "id": 4,
            "name": "14 "
        },
        {
            "id": 5,
            "name": "24"
        }
    ]
}

I am trying to test the value of the id.
I have written the below code.

var jsonData = JSON.parse(responseBody);
tests["Record  should have : " ] = jsonData.recordCount ===5;
tests["Items: "] = jsonData.items.id ===1;

The First Test case RecordCount is Passed, but the id is failing. 

How to test or verify the view Model and sub models.

**Comment by SamvelRaja** [comment]
I can see that items is an array, so the below code will work for you.

```
var jsonData = JSON.parse(responseBody);
tests["Record should have : " ] = jsonData.recordCount ===5;
tests["Items: "] = jsonData.items[0].id ===1;
```

**Comment by amitavmishra** [comment]
Thanks! that worked.
