### ISSUE TITLE
Feature Request: Act as system proxy on startup

### ISSUE THREAD

**Issue by dinolupo** [a85/POSTMan-Chrome-Extension#3810]
The "act as system proxy on startup" option will be a nice addition. 
If selected, the app should automatically attach to WinINET/IE (like Fiddler). Previously this was achieved with the Chrome Interceptor Plugin, now with client app does not work anymore.

Thanks.

**Comment by SamvelRaja** [comment]
@dinolupo if your requirement is for getting the requests to postman (history/collection) automatically, then we have the solution already in it. https://www.getpostman.com/docs/postman/sending_api_requests/capturing_http_requests

Kindly let us know if this solves your use case?

**Comment by dinolupo** [comment]
Hi, 
to use that option I need to configure the proxy in the applications. 
While, what I was suggesting, is that the application should automatically configure itself as a "System Proxy" to capture the traffic of all applications automatically (without configuring any proxy). Fiddler has also the ability to select an application (using the mouse) and capture only the traffic from that application.
Thanks.
