### ISSUE TITLE
Setting API method type (POST, GET) dynamically inside pre-request

### ISSUE THREAD

**Issue by maissom-abbasi-confiz** [a85/POSTMan-Chrome-Extension#3812]
## App Details:

```
Postman for Mac
Version 4.11.0
OS X 16.4.0 / x64
```

I wanted to know if there is a way to dynamically set API method type (such as POST, GET etc.) within pre-request script. I have a project where I have developed a generic postman framework that can test any API call with given parameters and expected response (xml/json etc.). This works well for POST call (which is currently the scope).

Is there a way where I can set the API method type to say "GET" in the pre-request part?

Any workaround / guideline shall be really appreciated. Thanks.

**Comment by prashantagarwal** [comment]
@maissom-abbasi-confiz There is no straight forward way to do this.
Either you can use newman (our CLI tool) to do the as it allows setting you method as a variable. Also you can try to leverage `pm.sendRequest()` I am not sure whether this will work for you but these are the only two things that come to my mind for achieving this.

**Comment by maissom-abbasi-confiz** [comment]
@prashantagarwal 

Thanks for following up. Can you please give an example using newman. I am familiar with newman and use it to run our postman scripts through command line.
