### ISSUE TITLE
Error Parsing Json response

### ISSUE THREAD

**Issue by magdazacharska** [a85/POSTMan-Chrome-Extension#3814]
Postman for Windows
Version 5.3.2
win32 6.1.7601 / x64

I'm getting Parse Error when response is in JSON format.    Here is the output of the  Postman Console:

![image](https://user-images.githubusercontent.com/25852404/32856933-3d378746-ca14-11e7-80f1-aba2ae723fef.png)

 Postman for Chrome behaves as expected and returns:
![image](https://user-images.githubusercontent.com/25852404/32857090-c6089920-ca14-11e7-8da8-66a97b4733ab.png)

**Comment by prashantagarwal** [comment]
@magdazacharska Thanks for reporting this. So you don't see any response on the native app ?

**Comment by magdazacharska** [comment]
The request posts the data but the postman for windows doesn't display the response.   If I send a consecutive request to the service to GET  the data for the user from POST request, it will display correctly.
![image](https://user-images.githubusercontent.com/25852404/32896803-01b7bea4-cab2-11e7-81e7-7d70a6f047d0.png)

If I don't provide the required headers for the POST request and the response from the service is text not json then postman for windows handles it correctly:
![image](https://user-images.githubusercontent.com/25852404/32896501-29f2bd70-cab1-11e7-8d8f-77a0e32686f8.png)

So it seems the problem is with processing JSON response for the POST request.

**Comment by prashantagarwal** [comment]
@magdazacharska Are you still facing the issue can you debug if your issue is related to #3858

**Comment by magdazacharska** [comment]
No, I don't experience this problem anymore.  I upgraded Postman multiple time since I reported the issue.  I'm currently on Version 6.1.4 .

**Comment by prashantagarwal** [comment]
Cool, closing this issue then. Let me know if you face this again in future.
