### ISSUE TITLE
Editing Request JSON causes JSONDecodeError on Backend

### ISSUE THREAD

**Issue by invertium** [a85/POSTMan-Chrome-Extension#3815]
I recorded a webhook request from stripe with postman, resending the request works fine, but when I change a value in the JSON in the Body->Raw Tab, my backend throws a JSONDecodeError. Copy and Pasting the code to python requests (via the "code" dialog) works fine though.

**Comment by prashantagarwal** [comment]
@JulianSchneider Can you tell me what JSON exactly are you trying to send when you get this error.
