### ISSUE TITLE
[Bug] Do not encode query charcters that don't need encoding

### ISSUE THREAD

**Issue by oliverjanik** [a85/POSTMan-Chrome-Extension#3816]
## App Details:
Postman for Windows
Version 5.3.2
win32 10.0.15063 / x64

## Issue Report:
Just upgraded from Chrome extension to Desktop version. Chrome version had this working well.

Send like this:
```
http://example.com/api?limit(10,0)
```

Postman actually sends this:
```
http://example.com/api?limit%2810,0%29
```

Relevant RFC spec: https://tools.ietf.org/html/rfc3986#section-3.4

Funny enough I just reported a similar issue against insomnia.: https://github.com/getinsomnia/insomnia/issues/604

**Comment by prashantagarwal** [comment]
@oliverjanik I am unable ton reproduce this. Can you provide some screenshot of Postman console.

**Comment by oliverjanik** [comment]
Here's a screen cap from a sniffer:
![image](https://user-images.githubusercontent.com/2280140/32891942-9c7c5280-cb28-11e7-92f2-3c8b4a2af789.png)

**Comment by EmirGluhbegovic** [comment]
Hey,

I am experiencing the same issue making the following get request:
localhost:3114/api/users?filter(name, test)
It encodes the parans and the coma. How can I disable this from happening?

 "GET /api/users?filter=%28name,test%29 HTTP/1.1" 500 174 "-" "PostmanRuntime/6.4.1"

**Comment by jhr** [comment]
On the other hand, characters that actually need encoding are left as is, like `=`.
`GET /foo?q=(a=b)` is encoded to `GET /foo?q=%28a=%29`. I would expect it to be `GET /foo?q=(a%3db)`.

**Comment by oliverjanik** [comment]
@jhr why? based on RFC spec `=` is a `sub-delim` which is allowed in query string.

**Comment by jhr** [comment]
I didn't read the RFC, to be honest. Referring to [Wikipedia](https://en.wikipedia.org/wiki/Percent-encoding#Percent-encoding_reserved_characters) instead, all characters with special meaning shall be encoded. The `=` sign has a special meaning since it separates name from value in GET parameters. If the value itself contains an `=` sign, it only makes sense to encode it, in my opinion.

**Comment by oliverjanik** [comment]
@jhr that is woefully ignorant position. What you refer to as keys and values, is a part of the HTML specification that defines how forms construct query string for method="GET". URL spec above knows nothing about key and value pairs.

If you choose not to read the spec, please do not suggest anything as it's interpretations much like yours that are causing harm in the first place. Unfortunately the standard is kind of complicated and your Wikipedia article is a gross over simplification. 

Postman is a dev tool. Magic behind the scenes and whimsical encoding are unacceptable. I want a scalpel not a butter knife.

**Comment by jhr** [comment]
@oliverjanik Well, how about supporting that "HTML specification" then? I am more than aware that URLs do not have keys or values in that sense. But thanks for the blunt reminder.

Postman supports, via its UI, to put in Key, Value, and Description as GET params. It, therefore, does this exact distinction between keys and values. Within such value, an `=` sign should be encoded in order to work as expected. If the UI didn't support keys and values, I wouldn't have asked for it but instead properly encoded the whole string manually in the first place. It's just misleading in my opinion.

**Comment by gabeluci** [comment]
So is this going to be looked at? I just ran into this today.

But I agree with oliverjank: let's ignore the '=' sign "issue" (whether it is an issue or not) since that's not in the scope of the original purpose of this issue.

**Comment by smokedlinq** [comment]
This also affects queries where we are trying to pass in the query "fields=values(Status)" and it's encoding the parens and it should not be.

**Comment by SamvelRaja** [comment]
We are following a master thread #4555 to track all issues related to Url encoding. Please follow that issue for updates.

**Comment by vikiCoder** [comment]
Hi everyone, this is fixed in the latest [Postman Canary](https://www.postman.com/downloads/canary) release (version 7.20.0-canary03). We don't automatically encode `()` anymore according to WHATWG URL standards. You can see more details about the fix at #8154

**Comment by codenirvana** [comment]
This is fixed in the latest version of the Postman app (v7.20.0) by enabling the "Use next generation URL processing" setting as mentioned in #8154.

Feel free to leave your feedback at #8154 or reopen this thread if the issue persists.

**Comment by Peter83** [comment]
I enabeld the "Use next generation URL processing" but "&" chars inside environment param, are still encoded as %26.

**Comment by Peter83** [comment]
> This is fixed in the latest version of the Postman app (v7.20.0) by enabling the "Use next generation URL processing" setting as mentioned in #8154.
> 
> Feel free to leave your feedback at #8154 or reopen this thread if the issue persists.

I enabeld the "Use next generation URL processing" but "&" chars inside environment param, are still encoded as %26.
