### ISSUE TITLE
Allow access to collections when offline & authentication has failed

### ISSUE THREAD

**Issue by edwardgalligan** [a85/POSTMan-Chrome-Extension#3819]
Bug  #1634 seems to have been requesting this feature in 2015, but it was closed after resolving a (related, but distinct) bug in the app, and it seems - as far as I can tell - the feature was never pursued further.

Are there any plans to make Postman fully work offline? As it stands, in order to use Postman offline  (according to the fix in  #1634) I'd have to get online somehow, connect to Postman servers, sign in to my account, and then disconnect again after the app is signed in. This isn't really viable at times when I don't actually have an internet connection.

**Comment by sdnts** [comment]
@lucideer The app does not require you to sign in to be able to use it. You should be able to skip sign in and start sending requests. Is this not working for you?

**Comment by edwardgalligan** [comment]
Hey @madebysid, thanks for replying so quickly, and sorry if I misunderstood how this should work. Yes, the app was not working earlier today when I was out-of-office and offline.

Earlier it was presenting the sign-in screen. There was no option to skip - the closest thing was a small grey link at the bottom saying something like "Take me to a signed in account" or some similar, quite cryptic text. The link did nothing.

I've retried it now (disabling my internet connection). The behaviour is quite different (and a bit inconsistent):

- if I try signing out and restarting the app, it shows me as signed in, but there is no session data (seemingly the local data is deleted but the signout never finalises without an active internet connection)
- if I go online, then sign out, close the app, go offline and re-open it, it takes me straight to the app with no sign-in prompt at all
- if I click the "Sign in" button top-right while offline, I get the sign-in prompt with the same grey link mentioned above but the link now has different text that before: it now says "Take me straight to app", and everything works fine.

It looks like this is working fine for me, so I guess this bug can be closed, but there are definitely other bugs/issues in there somewhere.

It's possible this was a migration bug from a previous version upgrade as I have not used Postman in a short while. Also, if it's of any relevance, my account currently shows two sessions (though I've only ever had one), one of which is labelled "Older Login".

**Comment by sdnts** [comment]
This looks odd. We will look into this.

**Comment by edwardgalligan** [comment]
Update on this bug - unfortunately I don't have much data, as it's difficult to reproduce reliably. It seems to only affect me when I'm not in a good position to debug (i.e. have no internet access and haven't pre-planned having debugging tools at the ready).

The best I can offer is a description and screenshot:

![screen shot 2018-02-01 at 14 56 56](https://user-images.githubusercontent.com/170268/35685161-d4149f3a-0760-11e8-9df7-a616e3dbdbba.png)

The above screen is what I was presented with when I:

- opened Postman while offline
- had been signed into my Postman account the last time I had used Postman (with an internet connection)

Clicking the *"Cancel and take me to signed in account"* link at the bottom brought up a loading screen, which brought me back to this screen. Over and over. I was completely unable to use Postman.

Having regained internet now, Postman works fine. I tried closing it, disconnecting, re-opening and it works fine. **CNR**. So this appears to be a Heisenbug; one that completely cripples the app at the least convenient times.

**Comment by JamesMGreene** [comment]
:100:

This would be extremely useful to anyone testing a locally hosted service, especially if they travel and are occasionally without WiFi/LTE (e.g. on airplanes or in random unfamiliar environments). I know it's happened to me before when I was on a plane... I was surprised but failed to add an issue for it.

**Comment by sdnts** [comment]
Ah, I understand now. The app tries to re-authenticate you every 15 days to make sure your account is not being misused. I'm adding this as a feature request.
Just to make sure I understand correctly, you guys would want the app to allow you to work with your collections even after this re-authentication attempt has failed (with the premise, however, that your collections will not be synced since you're offline), correct?

**Comment by edwardgalligan** [comment]
> *Just to make sure I understand correctly, you guys would want the app to allow you to work with your collections even after this re-authentication attempt has failed (with the premise, however, that your collections will not be synced since you're offline), correct?*

I would like the app to always work offline. I'm not sure how syncing while offline would ever be expected?

> *The app tries to re-authenticate you every 15 days to make sure your account is not being misused.*

I'm extremely unclear on what the abuse vector is here? How/why does this measure work??

**Comment by martypitt** [comment]
+1 I've had this issue several times when travelling on trains that don't have wifi.

**Comment by edwardgalligan** [comment]
Can I ask if there's any intent to fix this bug? Not looking for a timeline or intending to pressure development, but simply a brief update of intent would be helpful.

According to @madebysid's description of the issue, it seems there is some logic that artificially cripples the app if it doesn't phone home every 15 days. This means that users must anticipate every instance of working without internet access if they don't use Postman constantly on a daily/weekly basis (I tend to use it for local API testing in short concentrated bursts every month or two).

If I understand @madebysid's description the existence of this limitation seems more of a conscious policy decision by Postmanlabs rather than an accidental bug, so I'm just curious if this is going to change?

**Comment by gsolak** [comment]
+1. This happened to me yesterday.

Can we please transition this from a "feature" to a critical bug? This also happened to me when I was offline. The entire application might as well be fully bricked because it is useless.

I don't use Postman on a daily basis. So the 15 days since last authentication is not thought very well. I might have not logged into postman for 3+ weeks. And then I'll be traveling and end up working on some backlog items. And during those times I rely on Postman to do some old school request w/ mocked data.

**Comment by preethammavin** [comment]
Hey, we check for authentication because of security of the users data. But we are visiting this as an improvement to the workflow of the user, will update the thread once we have tackled it.

**Comment by donotnoot** [comment]
Hello!

I'm experiencing the same thing. I usually develop on my desktop at home, and travel very often, and take my laptop to do some work while away.

What I find is that everytime I start postman to do some debugging while on the go (bus, plane, train, whatever) without internet access, I can't use postman at all. I wouldn't mind being signed out for security reasons every 15 days or whatever, but being completely locked out of postman is a major annoyance. Once, I was stuck in a plane for _8 hours without postman and it was really boring_ :(

I think the best solution would be to be able to use postman without being signed in at all? Obviously, without the synced data such as collections, call histories, etc., and then once you get back online, sign in again.

This would be very much appreciated at least by me. What I've been resorting to for the past few months is to just tether my phone for a few seconds to allow postman to sign in, but there are situations where this is not possible, which is annoying... and have to use curl or chrome/ff devtools to make calls which is really unpleasant.

I have offline docs for most of the stuff I use, my local environment doesn't need internet access for most stuff, and it would be great if this tool didn't either, would make developing offline much, much easier!

Regards.

**Comment by SomeProgrammerGuy** [comment]
Yes I have this issue. Ive installed it offline on an intranet and it simply doesnt work Im assuming because its trying to connect to the internet. I do wish people writing software would get out of this silly notion that everybody is connected to the public internet. (Or that we want the software that we use to be without asking us first).

**Comment by JamzTheMan** [comment]
gah, so work firewall now blocks www.getpostman.com and such so I can no longer use this beautiful app to test internal restful web services :(

Any update on letting us use this offline? I don't really need/want online sync anyways...

**Comment by JamzTheMan** [comment]
odd, ok, after restarting a couple times I guess I finally got it to sign off and it now seems to work (I just lost my saved requests but I can deal)

**Comment by a85** [comment]
We don't see a technically feasible way in our current architecture of handling this as of now. Postman does work as much as it can in an offline mode and when the internet connection is back - it reconnects. We already have a ton of complexity in dealing with this synchronization that checking for additional states is not possible. If Postman is going to be used definitely in a non-publicly accessible system, then I recommend not signing in at all.

**Comment by 54754N4** [comment]
First of all, i'm sorry for commenting on a closed thread.

> 
> 
> Hey, we check for authentication because of security of the users data. But we are visiting this as an improvement to the workflow of the user, will update the thread once we have tackled it.

Hmm i'm not sure how forcing an authentication every 15 days would validate the security of someone's requests/data.. Security is always layered, and if someone is able to open postman on any of my devices, then it's perfectly safe to assume that my security had already been breached at many prior levels already. 
Ultimately, I think fixing those would be more appropriate than making postman do some periodic forced authentication for little gain in security in exchange for more problems in usability =/ 

Is there any feature that would allow us to mark a collection safe for offline-use ? That way these marked collections could be stored locally and also be accessible even on non-authenticated postman clients

Edit: the only way i figured out to do the same thing is to
- right click a collection and share it using a public link
- swap to scratch pad and import collection using generated link
But having to do that for many collections seems painful just to make them accessible offline

**Comment by nilskp** [comment]
Postman has definitely gotten worse lately in this regard. I work on a VPN with only intranet access (no public internet) and used to be able to start Postman. Now it won't even start if not connected to the internet.

**Comment by wesley-adv** [comment]
Well I'm really late to this and I see this is closed but... just want to say goodbye Postman, it was good while it lasted....

I really liked it and used to to structure an API by using the Collection feature. But it started to annoy me that I was required to have an account for using something I used mainly locally and only by me (I used Collection just to document it for myself or anyone that might succeed me, no one else was working with me on it then no reason to share with anyone).

I kept postponing the warning and kept using it locally, I had no reason to make an account at all and then I refused to do so. But finally, today I got hit by an update (despite having auto updates disabled) that locked me out of the Collections feature, preventing me to do anything about it without making an account. That's plain stupid and I still don't see a reason for forcing using an account (then requiring me to use it always online).

Thankfully I could find a backup file among the app data files so I didn't lose what I worked on. But I'm going to really look into alternatives and try to forget this app exists.

P.S. Sure it has an "offline" mode but all what it allows me to do are requests and save an history of them? There are hundred other ways to do that (browsers and IDEs extensions) then Postman ended being just "another one", it lost its differential to me.

**Comment by nico-abram** [comment]
> We don't see a technically feasible way in our current architecture of handling this as of now. Postman does work as much as it can in an offline mode and when the internet connection is back - it reconnects. We already have a ton of complexity in dealing with this synchronization that checking for additional states is not possible. If Postman is going to be used definitely in a non-publicly accessible system, then I recommend not signing in at all.

@a85 I'm a bit confused by this recommendation to not sign in at all to work offline, since it seems we can no longer import locally stored export files of collections without signing in (https://github.com/postmanlabs/postman-app-support/issues/12145)
