### ISSUE TITLE
Cookies with same name but different path

### ISSUE THREAD

**Issue by farkass** [a85/POSTMan-Chrome-Extension#3824]
## App Details:
Postman for Windows
Version 5.3.2
win32 6.3.9600 / x64

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:
This is the first version I use so it was always there
 2. Expected behaviour:
Use Cookie with same name twice for different path and domain.
 4. Screenshots (if applicable)

On my VM there apps using JSESSIONID cookies.
One has a JSESSIONID for path /core
second one has JSESSIONID for path /equipments.

Trying to do API call to /core on one tab. So copied the cookie JSESSIONID from Chrome.
It is working as using the correct cookie.
On second tab trying to call API for /equipments. Tried to add here a new cookie with same name and new value for path /equipments. But instead of creating a second cookie, the previous one updated with new id value and the path.  
When tested API here it is succeded as using the correct cookie.
But when switched back to previous tab and tried the /core API call again, it is failed.

Thanks!

**Comment by numaanashraf** [comment]
@farkass Thanks for reporting this. Are you using the `Manage Cookies` feature to set the cookie for each path? Or setting the cookie via request header manually? Could you verify whether your second request is overwriting the cookie needed for the first request via the set-cookie response header.

I've attached screenshots below for the use case I tried.

Request to /get sends foo2 and foo1 cookie
<img width="614" alt="screen shot 2017-11-23 at 3 27 09 pm" src="https://user-images.githubusercontent.com/3295568/33167380-5eb0336e-d063-11e7-806e-2d74d6a71e9e.png">
<img width="617" alt="screen shot 2017-11-23 at 3 27 30 pm" src="https://user-images.githubusercontent.com/3295568/33167978-4e0d7a7e-d065-11e7-993a-f11ecce403c4.png">

Request to /post sends foo3 and foo1 cookie
<img width="645" alt="screen shot 2017-11-23 at 3 26 58 pm" src="https://user-images.githubusercontent.com/3295568/33168006-5ee851d4-d065-11e7-952e-e3899ba79fbe.png">
<img width="617" alt="screen shot 2017-11-23 at 3 27 25 pm" src="https://user-images.githubusercontent.com/3295568/33168020-6ad9f6b4-d065-11e7-9957-f38c901e8923.png">

If I set a cookie header in /get, the custom cookie value is also sent in addition to foo1 and foo2
<img width="601" alt="screen shot 2017-11-23 at 3 29 11 pm" src="https://user-images.githubusercontent.com/3295568/33168042-8639f526-d065-11e7-9872-92ab5836cdb7.png">

**Comment by farkass** [comment]
Hi @numaanashraf
Sorry, just read notification mail you have closed this. Somehow not received earlier mail about your comment.

I am setting manually the cookies.

I am using the same name JSESSIONID for different path
as foo3:
JSESSIONID=d9033c35; path=/core...
and 
as foo2:
JSESSIONID=fdd97d5c4ee0; path=/equipments...

I have two separate services using the the same called cookie with different id and different path.
Thanks!

**Comment by numaanashraf** [comment]
This is a verified bug and we are looking into tweaking the `Manage Cookie` section to support this.

**Comment by harryi3t** [comment]
@farkass  We have released a fix for this on our canary apps. 
Can you please verify it?
You can get the canary app from https://www.getpostman.com/canary

**Comment by farkass** [comment]
Hi @harryi3t,
Just tested the canary's windows x64 version and it works fine!
Thanks!
