### ISSUE TITLE
BUG Can't copy response from "pretty" view 

### ISSUE THREAD

**Issue by dragonalvaro** [a85/POSTMan-Chrome-Extension#3826]
When I try to copy some response from the panel (pretty tab), it doesn't copy to the clipboard. I have to switch to Raw view and copy from there. Neither CTRL+C or Right Button -> Copy works from pretty view

## App Details:

```
Postman for Linux
Version 5.3.2
linux 4.10.0-38-generic / x64
```

## Issue Report:
Since I moved from chrome app version, to standalone version, I'm having this issue.

http://imgur.com/yg2jK7Ll.png

## Reproduce:
Make a request, try to copy any text from the response pretty tab

**Comment by deepakpathania-zz** [comment]
Duplicate #3691.
