### ISSUE TITLE
how can i edit req.headers['user-agent'] ....i am using postman to test my api..where is want hit my api with modified req.headers['user-agent']

### ISSUE THREAD

**Issue by ishwarchandratiwari** [a85/POSTMan-Chrome-Extension#3827]
how can i edit req.headers['user-agent']
....i am using postman to test my api..where is want hit my api with modified req.headers['user-agent']

**Comment by ishwarchandratiwari** [comment]
how can i edit req.headers['user-agent']
....i am using postman to test my api..where is want hit my api with modified req.headers['user-agent']

**Comment by prashantagarwal** [comment]
@ishwardeveloper You can set User-Agent Header in Postman app.

**Comment by ishwardeveloper** [comment]
how?

**Comment by ishwarchandratiwari** [comment]
HOW?

**Comment by a85** [comment]
Read the docs: www.getpostman.com/docs

**Comment by rm-fixeads** [comment]
@ishwardeveloper 
![screen shot 2018-03-16 at 12 13 45](https://user-images.githubusercontent.com/20791352/37520074-8cd7a94e-2913-11e8-9d64-fa1af8cfdb86.png)

**Comment by ishwarchandratiwari** [comment]
thanx

**Comment by caseyprovost** [comment]
I am seeing that Postman appears to now override this value. I have `User-Agent` set, but all my requests are coming through as:

```
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36
```

**Comment by numaanashraf** [comment]
@caseyprovost Looks like you might be using Postman for Chrome. User-Agent overrides are supported in Postman's Desktop apps (https://www.getpostman.com/downloads/)

Screenshot taken from Postman for Mac v7.0.7
<img width="965" alt="Screenshot 2019-04-17 at 2 38 14 PM" src="https://user-images.githubusercontent.com/3295568/56322819-e3300900-611e-11e9-8af2-9d0d8cc6d1f1.png">

**Comment by ThanhNg** [comment]
> @ishwardeveloper You can set User-Agent Header in Postman app.

Stupid and lazy answer!

**Comment by 255-255-255** [comment]
> > @ishwardeveloper You can set User-Agent Header in Postman app.
> 
> Stupid and lazy answer!

It's not as if finding the header tab is difficult. It's right there - if you don't understand how to set headers, then maybe read the documentation, as was suggested?

**Comment by caseyprovost** [comment]
Maintainer, you might want to lock comments here...getting pretty heated. Let’s all be nice to each other here :) Sometimes there are disconnects, it doesn’t mean anyone is being malicious or lazy.

As a contributor to the issue (see comment above), I can tell you I override the value in the Mac app as suggested. However that does not appear to work. I am more than happy to provide shots of my client and the output.

**Comment by saswatds** [comment]
Hey @caseyprovost 
<img width="903" alt="Screenshot 2019-10-05 at 9 02 42 AM" src="https://user-images.githubusercontent.com/8796447/66249323-16a73400-e74f-11e9-892a-f4ed8a947a85.png">
This postman app version `v7.8.0` The user-agent seems to getting modified 😕 just right

**Comment by caseyprovost** [comment]
I was on 6 when having the issue.

**Comment by alvamanu** [comment]
No regulation here? @ThanhNg 's comment is rude and disrespectful. This is not reddit or youtube. Let's show some respect for each other.
