### ISSUE TITLE
Newman Report - Multiple sets of same request is shown for multiple iteration even though the pass/fail count is already included in the first request

### ISSUE THREAD

**Issue by azharmohammedk** [a85/POSTMan-Chrome-Extension#3828]
Newman Report - Multiple sets of same request is shown for multiple iteration even though the pass/fail count is already included in the first request

## App Details:
Postman for Windows
Version 5.3.2
win32 6.1.7601 / x64
Website
Twitter
Licences
Changelog
Documentation
Report an issue
[Newman Report Issue.docx](https://github.com/postmanlabs/postman-app-support/files/1485032/Newman.Report.Issue.docx)

[Newman Report Issue.docx](https://github.com/postmanlabs/postman-app-support/files/1485031/Newman.Report.Issue.docx)

## Issue Report:
1. I have 1 collection with 1 request having 2 tests which I am running for 2 iterations. 
2. I am using data from data file (CSV) which has two iterative data
3. When I run this using postman collection runner, I see 4 tests in total with all 4 passed which is correct
4. When I run the same using newman report, I see 2 requests and each having 2 tests but the count is incremented for each iteration showing a wrong picture that totally 8 tests have been run. Attaching detailed snapshot. 

Please fix the issue.

**Comment by prashantagarwal** [comment]
@azharmohammedk You can report Newman issues in its own repo. It will help us in keeping better track of these issues.
