### ISSUE TITLE
Postman macOS app update not working if working under account without administration rights

### ISSUE THREAD

**Issue by evgeny-sureev** [a85/POSTMan-Chrome-Extension#3829]
## App Details:

```
Postman for Mac
Version 5.2.0
OS X 17.2.0 / x64
```

## Issue Report:
 1. Bug always been there. If update is available, file successfully downloaded, but after restart version stays the same, and prompt for updating shows again.
 2. Expected behaviour: if update is available, it should be installed.

Steps to reproduce:
 1. Install Postman app under user account without admin rights.
 2. Try to update app.
 3. Check version after restart.

**Comment by prashantagarwal** [comment]
@evgeny-sureev Known issue. We can write to file system if you don't provide the app write access.

**Comment by evgeny-sureev** [comment]
Why you can't make it like in all other apps? Ask administrator password upon update. I have dozens of apps and only Postman unable to update.
