### ISSUE TITLE
[feature] Include Response Body in Runner export results output

### ISSUE THREAD

**Issue by yonisade** [a85/POSTMan-Chrome-Extension#3830]
## App Details:
Postman for Windows
Version 5.3.2
win32 10.0.15063 / x64

## Issue Report:
We can see the Request output in the Collection Runner Results window under each iteration by clicking on the [collection name]->"Response Body", but it will be much more useful to see it also as part of the JSON **results export file** under key "responseCode".

Currently, we can only see this output under "responseCode":

"detail": "Standard response for successful HTTP requests. The actual response will depend on the request method used. In a GET request, the response will contain an entity corresponding to the requested resource. In a POST request the response will contain an entity describing or containing the result of the action."

**Comment by prashantagarwal** [comment]
@yonisade  we are already tracking it here #3633 . Closing it as duplicate.
