### ISSUE TITLE
Collections that work in Postman 5.2.1 is broken since 5.3.0 up to latest

### ISSUE THREAD

**Issue by hoogenbj** [a85/POSTMan-Chrome-Extension#3831]
## App Details:
Postman for Linux
Version 5.3.2
linux 3.16.0-38-generic / x64```

## Issue Report:
1. This issue appeared with 5.3.0 and is still there
2. Expected behaviour is that after I upgrade, my collections should still work. For the one collection, the console logs are empty (screenshot 1 attached). For one of the other collections, there are some output in the console logs (screenshot 2 attached). Nothing works. Only remedy is to go back to v.5.2.1.
 1. Did you encounter this recently, or has this bug always been there:
 2. Expected behaviour:
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 4. Screenshots (if applicable)

![screenshot 1 from 2017-11-20 08 19 24](https://user-images.githubusercontent.com/4488721/33004930-1af9465e-cdcc-11e7-89bd-5112a9193e5b.png)
![screenshot 2 from 2017-11-20 08 17 33](https://user-images.githubusercontent.com/4488721/33004931-1b331582-cdcc-11e7-9d30-1438bc647920.png)

**Comment by prashantagarwal** [comment]
@hoogenbj Thanks for reporting this issue. Just couple of questions. Does your request include Authorization. Also do you get any error response

**Comment by hoogenbj** [comment]
Yes, it includes basic auth. For the one collection, but not the other. As you can see in the middle of each screenshot, I get no response. The request just hangs.

**Comment by bofrede** [comment]
I have the same problem: All versions after 5.2.1 are broken.
Requests doesn't seem to be sent. No output on the Postman console.
It doesn't matter if the requests are from an existing collection or whether it has authentication or not. Even new GET requests fails.
Latest test:
Postman 5.4.1 on Linux 4.10.0-40-generic / x64
Rolling back to 5.2.1 is all we can do for now. :-(

Is there any investigation I can do, to identify the cause?

**Comment by kamalaknn** [comment]
@bofrede 

This should not happen. Can you give us more details on the following points so we can look deeper?

1. Could you share a screenshot or the exported collection json we can use to reproduce this?
2. Are you seeing this for all requests? Could you try sending the request to `https://postman-echo.com/get`? You should see a json response.
3. Is your network connection on a Proxy? Could you verify if the settings are correct in your system and `Settings -> Proxy` in Postman?

Any other info on DevTools or Postman Console will help us find the issue.

**Comment by bofrede** [comment]
Proxy is off.
All requests fail on 5.4.1, including `GET https://postman-echo.com/get`

I saved the `GET https://postman-echo.com/get` request using version 5.2.1, where it worked.
On version 5.4.1, the Postman Console is empty.
I did however find an error message in the Developer Tools Console:
```
Failed to load resource: net::ERR_FILE_NOT_FOUND
requester.js:87178 There was a fatal error when sending the request! Objectmessage: "Unable to resolve variables. Require a List type property for variable auto resolution."name: "Error"stack: "Error: Unable to resolve variables. Require a List type property for variable auto resolution.
    at PostmanItem.toObjectResolved (/opt/Postman/resources/app/node_modules/postman-runtime/node_modules/postman-collection/lib/collection/property.js:163:19)
    at resolveVariables (/opt/Postman/resources/app/node_modules/postman-runtime/lib/runner/extensions/request.command.js:36:57)
    at PostmanCollectionRun.request (/opt/Postman/resources/app/node_modules/postman-runtime/lib/runner/extensions/request.command.js:76:13)
    at Instruction.execute (/opt/Postman/resources/app/node_modules/postman-runtime/lib/runner/instruction.js:156:29)
    at PostmanCollectionRun._process (/opt/Postman/resources/app/node_modules/postman-runtime/lib/runner/run.js:165:21)
    at PostmanCollectionRun.<anonymous> (/opt/Postman/resources/app/node_modules/postman-runtime/lib/runner/run.js:166:76)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)"__proto__: Object__defineGetter__: __defineGetter__()__defineSetter__: __defineSetter__()__lookupGetter__: __lookupGetter__()__lookupSetter__: __lookupSetter__()constructor: Object()hasOwnProperty: hasOwnProperty()isPrototypeOf: isPrototypeOf()propertyIsEnumerable: propertyIsEnumerable()toLocaleString: toLocaleString()arguments: nullcaller: nulllength: 0name: "toLocaleString"__proto__: ()[[FunctionLocation]]: <unknown>toString: toString()arguments: nullcaller: nulllength: 0name: "toString"__proto__: ()valueOf: valueOf()get __proto__: __proto__()set __proto__: __proto__()
done @ requester.js:87178
```

**Comment by kamalaknn** [comment]
Hi @bofrede 

This could be an issue with upgrade.

Could you explain your update workflow? Could you try removing your installation directory and reinstalling the Postman App?

**Comment by bofrede** [comment]
# Yes - success!
I miss a self-update feature in Postman, so I made a simple bash script:
```
#!/usr/bin/env bash
# From: https://blog.bluematador.com/posts/postman-how-to-install-on-ubuntu-1604/
wget https://dl.pstmn.io/download/latest/linux64 -O ~/Downloads/postman.tar.gz
sudo tar -xzf ~/Downloads/postman.tar.gz -C /opt
rm ~/Downloads/postman.tar.gz
# sudo ln -s /opt/Postman/Postman /usr/bin/postman
```
As you can tell, the old folder was never deleted.
The last line, which is commented, is only necessary on the initial install.

I have just renamed the old Postman program folder inside `/opt`, installed the new version again.

## It works now
Comparing the old and new folders, I have a lot of files and folders in the old program folder, not present in the new working folder.
`/opt/Postman/resources/app/background-modules`
`/opt/Postman/resources/app/node_modules/JSONStream`
`/opt/Postman/resources/app/node_modules/acorn`
`/opt/Postman/resources/app/node_modules/array-filter`
`/opt/Postman/resources/app/node_modules/array-map`
Just to name a few.

Thank you, so much, for your prompt replies.

**Comment by kamalaknn** [comment]
@bofrede Great!

We'll look into "Updating Linux App" docs and make sure this is communicated properly.

**Comment by gustawdaniel** [comment]
@bofrede - your tutorial should be pasted in official page

> https://www.getpostman.com/apps

For example next too buttons below `Postman for Linux` described as `command line method`.
