### ISSUE TITLE
Runner - "Error: Each row must have an equal number of columns" with valid CSV file

### ISSUE THREAD

**Issue by wabiloo** [a85/POSTMan-Chrome-Extension#3832]
## App Details:
```
Postman for Mac
Version 5.3.2
OS X 15.6.0 / x64
```

I've been trying to run a folder with a CSV file, which is generated automatically from my energy supplier's website. That CSV file opens fine in Excel, and looks fine when opened with a text editor.

Yet, when I try to use it as my data file in Runner, I get the following error message:
"Error reading data file: Error: Each row must have an equal number of columns."

I attach the file in question.

[MonthlyData-101025198_MM1.txt](https://github.com/postmanlabs/postman-app-support/files/1487027/MonthlyData-101025198_MM1.txt)

**Comment by prashantagarwal** [comment]
@wabiloo Thanks for reporting this we will look into this issue.

**Comment by stevegoulet** [comment]
Any update? Or is there a workaround?

**Comment by stevegoulet** [comment]
I found a workaround -- create your CSV in Windows Excel and export from there, it will then work on Postman/Mac.

**Comment by akashpatel2891** [comment]
@stevegoulet  Workaround suggested by you helped. Thanks.

**Comment by daveherrington** [comment]
Yes, this workaround (saving CSV format using Excel on Windows) works.

Even better, Excel for Mac 2011 offers the Save As format "Windows Comma Separated (.csv)".

Saving the file using this Windows Comma Separated (.csv) format did also work with Postman, which is a lot easier than borrowing a Windows computer from the accounting department.

-Dave
