### ISSUE TITLE
Cannot use certificates stored in OneDrive

### ISSUE THREAD

**Issue by tgskiman** [a85/POSTMan-Chrome-Extension#3834]
## App Details:

```
Postman for Windows
Version 5.3.2
win32 10.0.16299 / x64
```

## Issue Report:
Just had the need to use client certificates and was attempting to use a cert stored in "OneDrive" under the path ```c:\[user]\OneDrive\``` and received the following error in the console: ```certificate load error: einval: invalid argument, fstat```.

If I attempt to use the same files in another location (like "My Documents") certs/client auth works as expected.

Windows Version 10.0.16299.64, OneDrive version 2017 (Build 17.3.7117.1109)

I believe this may have to do with the version of electron as per [Microsoft/vscode#27285](https://github.com/Microsoft/vscode/issues/27285) it may be fixed by updating Electron to [electron/electron#10377](https://github.com/electron/electron/pull/10377)

Thanks!

**Comment by prashantagarwal** [comment]
@tgskiman Looks like you might have `File on Demand` settings enabled Try disabling from OneDrive settings.

There was some underlying issue with node, which was recently fixed. Once we move to latest electron version, this should work out of the box by the time, you can try disabling `File on Demand`

**Comment by prashantagarwal** [comment]
Pull Request in https://github.com/electron/electron/pull/10377

**Comment by SamvelRaja** [comment]
We had upgraded the electron version to include the fix. Kindly update to 6.1.4 version of the app.

**Comment by BrandonDusseau** [comment]
I hate to reopen very old issues, but I'm currently experiencing this issue on 6.7.2. I am unable to disable the "Files on Demand" option as it's enforced by group policy.

For now I'm working around the issue by moving the certs out of OneDrive, but it's not ideal as my organization has migrated all of active directory to OneDrive so these files are now only local to my machine. _Personally,_ I don't care that much about the workaround, but I figured I'd comment for awareness anyway.
