### ISSUE TITLE
"Could not get any response" when new line is in header value

### ISSUE THREAD

**Issue by gavenkoa** [a85/POSTMan-Chrome-Extension#3835]
I get `Could not get any response` from some time and I found the reason for that error here:

https://github.com/postmanlabs/postman-app-support/issues/3127#issuecomment-330030920

> I had the same issue. It was caused by a newline at the end of the "Authorization" header's value, which I had set manually by copy-pasting the bearer token (which accidentally contained the newline at its end)

What is surprising that exported `curl` command works great but Postman fail without any hint why.

I put authentication token to variable with trailing new line from copy/paste.

**Postman should warn about dangerous symbol in headers before sending request.**

**Comment by prashantagarwal** [comment]
@gavenkoa Thanks for pointing this out. We will look into this and get it fixed in upcoming releases.

**Comment by JohannesRudolph** [comment]
+1 it's a constance nuisance (even if you know how to workaround/fix it)

**Comment by skyboyer** [comment]
The same is observed once I put trailing space into header name. Say "Cookie :<cookie value>" leads to the same.

**Comment by skyboyer** [comment]
I see here 2 different issues: 
1. it's impossible to notice if values has trailing whitespaces(for Key-Value view - per each row; for Bulk Edit view - for last row)
2. Error during parsing request data(say trailing space(s) in Header Name) is not provided with detailed information(say "SyntaxException while parsing <HeaderName>" would be much more informative)

**Comment by ChristianWilkie** [comment]
I encountered this same issue, after removing the newline characters my request worked. Annoying :frowning_face:

**Comment by jordanboston** [comment]
I could not find a way around `n\t` being added with Postman JSON.  It just throws errors we can't get past in our function.  For the time being, I had to switch to using Insomnia which worked fine with the same data.

I'll watch for a fix or try to see if there is a resolution at a later point.  Thanks

**Comment by saswatds** [comment]
Hi @gavenkoa, In the latest version of *Postman App 7.10.0* we now actively warn users when there are invalid/non-safe characters and symbols in both key and values. This implementation follows the official RFC https://tools.ietf.org/html/rfc7230#section-3.2 for deciding the safety of characters. 
![Screenshot 2019-11-05 at 1 38 46 PM](https://user-images.githubusercontent.com/8796447/68189663-d64b0800-ffd1-11e9-8058-635eb2bb0d1d.png)
![Screenshot 2019-11-05 at 1 39 21 PM](https://user-images.githubusercontent.com/8796447/68189664-d6e39e80-ffd1-11e9-8752-c821f9dea709.png)

I will be closing this issue now. Feel free to re-open if this does not work for you.

**Comment by skyboyer** [comment]
@saswatds but how about spaces in value? it's valid character but it's still hard to notice.

**Comment by gavenkoa** [comment]
@skyboyer Yes and when I select text with triple click modern browser copies last space too.

So this kind of error is very probable.

**Comment by saswatds** [comment]
@skyboyer @gavenkoa as the specs state that whitespace is valid characters in the value, so adding warnings for such was not appropriate. 
But having said that we have already added **whitespace aware text representation** in the new console, we will be adding it to the rest of the builder pretty soon.

The above warnings help ensure that sending requests does not fail which results in the `Could not get any response` exception page.

**Comment by shamasis** [comment]
Just to sum up here. Postman now highlights leading and trailing whitespace characters + marks the invalid ones. Read more: https://blog.postman.com/2020/03/26/how-postman-increases-the-visibility-of-invalid-whitespaces-and-newlines-in-your-api-requests/
