### ISSUE TITLE
Keyboard shortcut for submitting request doesn't always work

### ISSUE THREAD

**Issue by chrisron95** [a85/POSTMan-Chrome-Extension#3836]
## App Details:

```
Postman for Mac
Version 5.3.2
OS X 17.3.0 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:
As long as I have been using the app
 2. Expected behaviour:
This is a weird one. When using keyboard shortcuts to scroll go through the tabs and submit the requests by using (on mac) command+} go to the next tab then command+enter to submit request, it should always submit the request. However, that only works if you started out by clicking on a call in the navigation pane first.

You can reproduce this by opening several tabs. When several tabs have been opened, click on the call for the first tab in the navigation pane. You should be easily able to (without using your mouse at all) scroll through the tabs and submit each call with the keyboard shortcuts.

Now without closing those tabs, go back to the first tab by clicking the tab itself. Then try scrolling through and submitting the requests again. You'll see that it'll scroll through, but it won't submit any requests unless you use the mouse to click on the call in the navigation pane.

Very strange issue that's not overly important, but I do this all the time so it can get annoying.

**Comment by kamalaknn** [comment]
Hey @chrisron95, thanks for reporting the issue. We'll investigate this and get back to you.

**Comment by sujayvenaik** [comment]
Hey @chrisron95 
This is fixed in the latest version.

Get the latest release from https://www.getpostman.com/apps
