### ISSUE TITLE
Installing Windows Postman over the Chrome App version results in "lost" configuration.

### ISSUE THREAD

**Issue by dcfsc** [a85/POSTMan-Chrome-Extension#3838]
## App Details:

```
Version 5.3.2
win32 6.1.7601 / x64
```

## Issue Report:

I had several hundred APIs configured but had not been able to sync for a long time due to our company adopting a zscaler proxy and not being able to sync.

I had Postman installed as the old Chrome app, and then installed the new one to improve proxy usage. That is when I lost all my stuff. Completely empty. I could have restored a backup if I had one. :)

When I closed the new app, and reopened using another of the 4 Postman shortcuts I have lying around, the old app came up and all my old APIs. I exported a backup.

It seems the data for each version is stored separately. Good thing...

So my problem was not really that the Postman installer overwrote or lost my APIs, but that the new installer does not warn about the old app. 

So, during Postman installation:

1. Detect that Chrome App Version was installed
2. Warn the user
3. Migrate the old collections to the new app, after a confirmation. 
4. Encourage me to uninstall the Chrome app version to remove the confusing shortcuts and prevent problems going forward. For safety, maybe not right away, but at startup while the control valves 
 to antimatter are opened, check to see if the user removed the old one, and prompt them to do so.

**Comment by kamalaknn** [comment]
@dcfsc That's a great idea. We'll investigate if and how we can do this. 

I am marking this as a feature request. We'll keep this thread updated. Thanks again.

**Comment by a85** [comment]
I doubt that Chrome has those APIs available for detecting Chrome app availability. :/

**Comment by laghutaarora** [comment]
I downloaded the windows app and i lost the old API collections(chrome app)
is there any way to restore the old collection?

**Comment by a85** [comment]
Closing this as we have 2 modes available for moving across the Chrome app - data dumps and syncing. We won't be doing a tight coupling between the Chrome app and the native app as the Chrome app platform is deprecated and we have frozen the codebase.
