### ISSUE TITLE
Referer header is not sent when set in Postman UI

### ISSUE THREAD

**Issue by snappieT** [a85/POSTMan-Chrome-Extension#384]
Create a new GET request, click on Headers, and add a Referer header. Send the request.

Expected: header is sent
Actual: header is not sent. This is confirmed through developer tools in Chrome and through a simple PHP script that echos the headers back

![screen shot 2013-10-02 at 11 52 47](https://f.cloud.github.com/assets/1431274/1252725/9f1b1646-2b51-11e3-8b30-1e9d53af457e.png)

**Comment by jayasuryajeyakodi** [comment]
You can enable postman interceptor that will allow you to change the referer header
