### ISSUE TITLE
cookie test - help

### ISSUE THREAD

**Issue by pburgr** [a85/POSTMan-Chrome-Extension#3840]
I have 2 different requests, one returns a cookie, the other one does not
how can I test, if a cookie was returned?
Can anyone share a piece of script?

I tried google something up, but it`s not working as I expected.

tests["no cookies"] = responseCookies[0] !== null

this test will pass in both of my requests

thanks for any advice

**Comment by deepakpathania-zz** [comment]
Hey, have you tried something like `postman.getResponseCookie("CookieName").value != null` ?

**Comment by pburgr** [comment]
it returns an error: Cannot read property ´value´ of null in both my requests

**Comment by pburgr** [comment]
without the .value
tests ["cookies"] = postman.getResponseCookie("CookieName") != null;
will fail in both requests

**Comment by pburgr** [comment]
I tried:
tests ["Cookies"] = ResponseCookie =! null

it works fine, but in the "cookie" request only
in the request without cookie is it:
![obrazek](https://user-images.githubusercontent.com/32922341/33078940-80ff5be2-ced4-11e7-92e8-337aca370909.png)

wrong test or a bug?

**Comment by pburgr** [comment]
what the hack?

tests ["Cookies"] = ResponseCookie = "null"
vs
tests ["Cookies"] = ResponseCookie = null

![issue_3840](https://user-images.githubusercontent.com/32922341/33079916-1344e8b2-ced7-11e7-8cdb-ae499fd99c0c.jpg)

**Comment by pburgr** [comment]
tests ["Cookies"] = ResponseCookie = "null"
&
tests ["Cookies"] = ResponseCookie = null

are sufficient for me, closing issue.
