### ISSUE TITLE
[Bug] - Unticking a query parameter that is not the last one will remove the key/value from the list of parameters rather than untick it.

### ISSUE THREAD

**Issue by Faz540** [a85/POSTMan-Chrome-Extension#3841]
Postman Windows v5.3.2

Issue 1:

![image](https://user-images.githubusercontent.com/9334128/33068646-ddb4a1b0-cea9-11e7-954a-df2b90023157.png)

Given the above, if I wanted to send the request without the last query parameter I can untick it.
This works fine.
However, if I wanted to send the request without sending any other parameter by unticking them, this will delete the key/value from the request instead of simply unticking it and temporarily removing it from the URL path.

Let me know if you need more info.

Issue 2:
![image](https://user-images.githubusercontent.com/9334128/33069090-45477766-ceab-11e7-81dc-04a40331f6c6.png)

Given the above, if I want to add another SKU query parameter, this will get added below the last ticked SKU query parameter (which is expected I guess) but it will also delete the first unticked SKU query parameter

![image](https://user-images.githubusercontent.com/9334128/33069159-8103514e-ceab-11e7-8c7e-1cb8fe4e5cdc.png)

Notice the 3rd to bottom query parameter has been replaced.

**Comment by kamalaknn** [comment]
@Faz540 Thanks for reporting this issue. 

After testing it out, I could see that the issues you are seeing happen when you have duplicate keys. We'll take a deeper look and fix this soon.

**Comment by alexandruirimiea** [comment]
I have the same issue.

**Comment by JayShallcrass** [comment]
I have also been able to recreate this issue

**Comment by sujayvenaik** [comment]
https://github.com/postmanlabs/postman-app-support/issues/4513

Hey @alexandruirimiea @JayShallcrass 

We have fixed this internally and will be out soon.
Please refer to the thread mentioned above for further updates.
