### ISSUE TITLE
Could not get any response ERROR

### ISSUE THREAD

**Issue by antonioribeiro** [a85/POSTMan-Chrome-Extension#3846]
## App Details:
```
Postman for Mac
Version 5.3.2
OS X 17.0.0 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:
I just installed the macOS app

3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 4. Screenshots (if applicable)

![image](https://user-images.githubusercontent.com/3182864/33079305-6f6ed06e-cebc-11e7-936f-ce4ba2b13a18.png)

I just created a tab, pasted the URL and sent the POST request with some data.

Works fine on Chrome extension.

**Comment by kamalaknn** [comment]
@antonioribeiro I think the error in the developer tools does not look related to the request. Could you check your settings if you have a timeout configured? Could you send a screenshot of the console item expanded so we can take a closer look?

**Comment by antonioribeiro** [comment]
@kamalaknn, I'm not in that workstation now, but I had just installed the app, so settings were all in their defaults.

**Comment by mattbrasieratos** [comment]
This is likely a proxy issue - the chrome app is using chrome's proxy settings. The desktop version doesn't use the chrome proxy settings, tries to go directly to the site and fails.

**Comment by ashleycoker** [comment]
Postman osx app does not work at all for me for this error.  Chrome app works fine.

**Comment by antonioribeiro** [comment]
@mattbrasieratos it was indeed a proxy issue, thanks and sorry for not closing this before.

**Comment by Jeeva-Rathinam** [comment]
@antonioribeiro Did you solve your issue?
