### ISSUE TITLE
Documentation: Links between articles missing /docs on mobile

### ISSUE THREAD

**Issue by Stevoisiak** [a85/POSTMan-Chrome-Extension#3848]
## App Details:
```
Safari for iOS
iOS 11.1.1
```

## Issue Report:
Issue: When viewing documentation on mobile, the links at the bottom of a page for navigating between articles are broken. (Missing /docs)

Expected behaviour: The link at the bottom of the page should bring me to the next article.

## Steps to reproduce the problem

1. On safari for iOS, open https://www.getpostman.com/docs/postman/launching_postman/installation_and_updates
2. Scroll to the bottom of the article and click “Sending the first request”
3. Link goes to 404 error for https://www.getpostman.com/postman/launching_postman/sending_the_first_request

**Comment by kamalaknn** [comment]
Hi @Stevoisiak 

Thanks for reporting the issue. We'll take a look at this and get back to you soon.

**Comment by sivcan** [comment]
I can confirm that this issue no longer exists in Safari on iOS.
Closing it.
