### ISSUE TITLE
Copy/Cut to clipboard does not work from context menu in body

### ISSUE THREAD

**Issue by buteomont** [a85/POSTMan-Chrome-Extension#3849]
## App Details:

```
Postman for Linux
Version 5.3.2
linux 4.4.0-101-generic / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there: New
 2. Expected behaviour: Copy/Cut to clipboard
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app): No logs
 4. Screenshots (if applicable)

In request body, highlight some text. Right click, select copy or cut. It does not happen.

**Comment by kamalaknn** [comment]
Hi @buteomont we are having trouble reproducing this. Could you share more information on this? 

1. Are you selecting a section of a value, or an entire row? (could you share a screenshot with the selection)
2. Are you using the `Key-Value edit` more or the `Bulk-Edit mode`?

**Comment by buteomont** [comment]
Sorry, should have mentioned it was raw body. Selecting a word, a few characters, a whole line, doesn't matter.  I should mention that CTL-C and CTL-X work properly in this scenario.  Screenshot:
![screenshot from 2017-11-22 06 10 32](https://user-images.githubusercontent.com/1907543/33127071-91e4a372-cf4c-11e7-9138-c424dbbf306f.png)

**Comment by dougmcmillan** [comment]
This issue seems to be same as https://github.com/postmanlabs/postman-app-support/issues/3691 and https://github.com/postmanlabs/postman-app-support/issues/4108

**Comment by dkuku** [comment]
On linux I can't copy from pretty formatted response but from raw response it's goes without problems.
Maybe this will be a hint to help for you solve this.

**Comment by prashantagarwal** [comment]
Tracking in #4759
