### ISSUE TITLE
Easier data entry for tabularized request bodies

### ISSUE THREAD

**Issue by prmichaelsen** [a85/POSTMan-Chrome-Extension#3850]
## App Details:

```
Postman for Chrome
Version 5.3.2
win / x86-64
Chrome 62.0.3202.94
```
## Feature request
More excel-like data entry for entering request body information in tabularized views such as: `form-data`, `x-www-url-form-encoded`.
 * hitting enter should return user to the next row of the column that was first edited in this row
 * hitting shift-enter should enter a new line in this cell (common behavior in modern apps)
 * hitting tab should move to the next column of this row
 * option to hide description field (as it is mostly in the way)
 * pre-existing data in a cell should be easier to overwrite
   * excel does this by defaulting to overwriting the cell on keypress and using F2 to edit existing data

Thank you for your consideration.
Regards,
Patrick

**Comment by numaanashraf** [comment]
All these are supported in the current table view.
