### ISSUE TITLE
Cant use Google App Password

### ISSUE THREAD

**Issue by Isanderthul** [a85/POSTMan-Chrome-Extension#3852]
I am unable to sign into my google account using an app password. I am not prepared to give out my account password.

**Comment by numaanashraf** [comment]
@Isanderthul Thanks for reporting this. We do not support app passwords at the moment. I've passed this along to the team and we'll keep you posted on any updates here.

**Comment by matthew-a-thomas** [comment]
Add me to the list of people reluctant to hand out my Google account credentials. Please keep us up-to-date on progress incorporating App passwords

**Comment by a85** [comment]
We don't have any changes around this planned for now or the near future.

**Comment by matthew-a-thomas** [comment]
On the one hand this doesn't seem like an overly complex thing to implement. On the other hand I must admit I've never dealt with Google auth so maybe there's some hidden complexity. On the other hand isn't it just OAUTH?

On the one hand it seems like a bad idea to require people's root credentials. On the other hand we should all be using two-factor auth to begin with. On the other hand you guys have no way of requiring two factor auth so what will you do when there's a breach of wherever those credentials are stored for all the poor souls who don't have two-factor auth?

To mention nothing about the uneasy feeling many of us get when we type such an important password into the prompt of an application of which we have no idea how that password will be used or stored.

> people's root credentials

I do mean _root_ credentials. My Google account is the gateway into nearly every single electronic identity of mine. With merely read access to my gmail you could easily get _active full_ access to: bank accounts, investment accounts, other email accounts, GitHub, StackOverflow, to say nothing about all the hooks into my wife's electronic identities. I keep most of my emails so you would also get a _ton_ of personal information.

I don't think I'm alone in this.

@a85 Could you explain a little more about _why_ this won't be implemented? Is it just the case that the software team doesn't feel this is important enough?
