### ISSUE TITLE
Exporting Collection v2.1 format does not work with variables

### ISSUE THREAD

**Issue by malenze** [a85/POSTMan-Chrome-Extension#3854]
## App Details:

```
Postman for Mac
Version 5.3.2 (5.3.2)
OS X 10.12.6 / x64
```

## Issue Report:
1. Did you encounter this recently, or has this bug always been there: (always)

Exporting collections where environment variables are used in URLs are not working, e. g.:
```
GET {{base_url}}/as/authorization.oauth2?response_type={{response_type}}&client_id={{client_id}}&redirect_uri={{redirect_uri}}&state={{state}}&nonce={{nonce}}&scope={{scope}}&display=touch&country={{country}}&locale={{language}}

GET {{base_url}}/static/auth/mobile-login/pp/{{country}}/{{language}}.html?resume={{resume}}
```
runs fine in Postman App, after export/import this becomes:
```
GET https://preview-login.porsche.com/as/authorization.oauth2?response_type={{response_type}}&client_id={{client_id}}&redirect_uri={{redirect_uri}}&state={{state}}&nonce={{nonce}}&acr_values={{acr_values}}&scope={{scope}}
Enter request URL
```

Exporting Collections where variables are used in x-www-form-urlencoded POST requests are not exported as variables but as values
```
username {{username}}
```
becomes
```
username mike.springer
```
if this is the value, that is currently set in environment variable username.

 2. Expected behaviour:
Variables are preserved on export/import regardless of their position within the request, header, body...

**Comment by numaanashraf** [comment]
@malenze Thanks for writing in. I'm having trouble replicating this issue. Can you mail a sample exported collection to help@getpostman.com? Thanks.

**Comment by malenze** [comment]
Sorry, Layer 8 problem.
I did the export, when several Builder tabs were still open and not finally saved. So the intermediate last saved status was exported. When I save all Builder tabs before the export, everything is fine.

Thus please close the bug report as "Fixed".
Sorry for the effort and time you spent in vain.
Nice evening. Thanks for the support!
