### ISSUE TITLE
Not able to define  setPrevious request under Prescript tab. Are we supporting this anytime sooner ?

### ISSUE THREAD

**Issue by kumarvastav** [a85/POSTMan-Chrome-Extension#3855]
## App Details:

```
Postman for Mac
Version 4.11.0
OS X 16.4.0 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:
 2. Expected behaviour:
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 4. Screenshots (if applicable)

**Comment by numaanashraf** [comment]
@kumarvastav Thanks for writing in. I'm having trouble understanding your issue. Could you elaborate on the issue with sample scripts?
