### ISSUE TITLE
Saving a request somewhere else with Ctrl+Shift+S doesn't handle saved responses correctly

### ISSUE THREAD

**Issue by dannyhajj** [a85/POSTMan-Chrome-Extension#3856]
When we try to "Save As" a request in order to save it somewhere else, the Examples in that request aren't handled correctly.

## Steps to reproduce:
- Open any request.
- Make sure it has at least one saved response.
  I suggest creating a new one for testing. As this response will be lost and cannot be recovered.
- Use <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>S</kbd> (Or <kbd>Cmd</kbd>+<kbd>Shift</kbd>+<kbd>S</kbd> on Mac)
- Save the request under a new name (It doesn't have to be in the same collection, you can save it anywhere)
 At this point:
    - The title of the tab will show that you have the new request currently open.
    - The Examples drop down will show the same examples that exist on the main request

## Current Behavior:
There are 2 ways to view the current behavior. And both are reproducible.

1. First method
    - Delete any of the examples that currently exists from the drop-down.
    - Open the old/main request.
    - The example that was removed from the new request, is also removed from the old request.

2. Second
    - Close and reopen the tab of the new request.
    - Examples in the drop-down will correctly show 0 items.

## Expected behavior
Copy examples from the old request to the new request. Or another alternative is to not copy examples at all and let the drop-down be empty.

## App Details:

```
Postman for Linux
Version 5.3.2
linux 4.13.0-17-generic / x64
```
I am able to reproduce it on Postman for Mac as well.

**Comment by numaanashraf** [comment]
@dannyhajj Thanks for reporting. We were able to replicate this issue and will be fixing this in the coming releases.

**Comment by numaanashraf** [comment]
This is related to #2893 and we are tracking updates and progress there. Closing this as duplicate.
