### ISSUE TITLE
Parse Error when receiving responses with a smaller Content-Length

### ISSUE THREAD

**Issue by lushc** [a85/POSTMan-Chrome-Extension#3858]
## App Details:
```
Postman for Mac
Version 5.3.2
OS X 16.7.0 / x64
```

## Issue Report:
Due to a bug in my own application, a JSON response included erroneous content after the payload. At first I didn't notice because the Content-Length header was being set to the payload's size, so the browser & Chrome app rendered the response as expected. Here's an example response:

```
HTTP/1.1 400 Bad Request
Date: Thu, 23 Nov 2017 16:36:53 GMT
Server: Apache/2.x (Unix) LibreSSL/2.x PHP/5.x
Cache-Control: no-store, private
Pragma: no-cache
X-Debug-Token: 00dd35
X-Debug-Token-Link: http://xxxxxxxx/_profiler/00dd35
Content-Length: 99
Connection: close
Content-Type: application/json

{"error":"invalid_request","error_description":"Invalid grant_type parameter or parameter missing"}<!DOCTYPE html>
<html>
    <head>
```

The native app's console displays the following, alongside a "Could not get any response, error connecting to" message:

![image](https://user-images.githubusercontent.com/3176079/33183993-50cd5812-d072-11e7-852b-d1c4741b7805.png)

Similar to #3814, the response is parsed correctly in the Chrome app:

![image](https://user-images.githubusercontent.com/3176079/33183086-5d5f7866-d06e-11e7-9490-7e4bc264c2e4.png)

When removing the Content-Length header, the expected (although syntactically incorrect) response is displayed:

![image](https://user-images.githubusercontent.com/3176079/33183775-2552ea86-d071-11e7-9848-ec5c1bf7db30.png)

So it seems that if the Content-Length header is set to a value less than the actual body length, the Chrome app (and browsers) truncates the content while the native app throws the parse error. I should note that Content-Length values greater than the response body's length doesn't cause a parse error.

So I suppose the crux of the issue is the differing behaviour between the Chrome and native apps when dealing with an incorrect Content-Length header. Now to fix my bug... 😄

**Comment by numaanashraf** [comment]
@lushc Thanks for letting us know. Chrome apps use Chrome's networking layer to send requests, which is a lot more forgiving with malformed responses. The native app is more strict in terms of spec compliance and there are no plans to relax this at the moment, as that would be a slippery slope to stand on as an API development tool. 😅 Anyway, we are always working on improving debug information for cases like these though and we'll keep this use case in mind. 😃

**Comment by tristanleboss** [comment]
Could be a cool idea to let user know there is a problem with the content-lengh like "Response body length is different than the one indicated in the Content-lenght header; this may lead to problem."
