### ISSUE TITLE
Does time shown in postman client inclusive of reading response and processing it ?

### ISSUE THREAD

**Issue by vignesh675** [a85/POSTMan-Chrome-Extension#3859]
## App Details:

```
Postman for Mac
Version 4.11.0
OS X 16.4.0 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:
 2. Expected behaviour:
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 4. Screenshots (if applicable)

1) Execute a rest call
2) Observe the time shown

Few questions on this

Is the time shown inclusive of reading the response from stream and showing it to user or just the time when the response is returned from server?

Is there any setting in postman to get the complete end to end time that is the response time and the time postman takes to read the response from stream and display  ?

**Comment by kamalaknn** [comment]
Hi @vignesh675 

The response time you see is the time from sending the request over the network and receiving the end of the response. This does not include the time Postman uses to process or display the response.

At the moment there is no option to compute the total time(response time + time Postman takes to show the response).

Could you explain your use case for this? Usually users optimize for the response time.

**Comment by cs94njw** [comment]
Just had this same issue.  I appreciate and understand the response from @kamalaknn , but it's weird - you're not sure whether to trust the time or not.
With the subtlety of "localhost/127.0.0.1" still not working in an obvious way, I find myself questioning whether it's a bug or a true representation.
