### ISSUE TITLE
Not able to do POST and PUT through postman after our QA environment changed

### ISSUE THREAD

**Issue by nishant-malodkar-globant** [a85/POSTMan-Chrome-Extension#3860]
Steps:

1. Load the rest URL to postman
2. Apply headers in terms of auth. and content-type
3. Set body as json body.
4. Hit the request.

Expected behaviour:
The request should get post and successful response should be received.

Actual result:
"Could not get any response" whereas for same request I am able to run GET method without changing an inch in the URL.

Note: Apologies for the request URL. its confidential

**Comment by sdnts** [comment]
Hi @nishant-malodkar-globant, do you use an internal proxy for your requests? If so, have you set it up in the Proxy section of settings?
Can you give me a little more info about your environment? Nothing specific, just an overview of what it looks like, that'll help us get to a solution faster.
