### ISSUE TITLE
Params within URL (not query string) are not resolved

### ISSUE THREAD

**Issue by evanmiller67** [a85/POSTMan-Chrome-Extension#3861]
## App Details:

```
Postman for Mac
Version 5.3.2
OS X 17.2.0 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:
Just noticed this after switching from Chrome app to the desktop client
 2. Expected behaviour:
When using parameters inside the URI, they should resolve anywhere, not just in the query string.
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
```
GET
https://:host/get?test=123
Error: Invalid URI "https:///:host/get?test=123"
Request Headers:
cache-control:"no-cache"
postman-token:"453879e8-4fc0-4f6b-b814-4dc152043fc5"
```
 4. Screenshots (if applicable)
<img width="980" alt="screen shot 2017-11-24 at 11 20 50 am" src="https://user-images.githubusercontent.com/178019/33218218-b6f01a34-d109-11e7-83bb-20e9779e47c7.png">

Steps to repro:
- Replace part of the URL with a parameter (e.g. https://postman-echo.com/get => https://:host/get).
- Fill in the parameter with the desired host
- Click Send
- Failure

**Comment by sdnts** [comment]
@evanmiller67 Can you try out environment or global variables for this?

**Comment by evanmiller67** [comment]
@madebysid That works. However, for my use case, not a great solution. I have 2000+ hosts.

**Comment by evanmiller67** [comment]
To provide clarity, this is something that exists in the chrome extension.

After switching from the extension to the native client and importing my collections, they are not working.

**Comment by dlwhitehurst** [comment]
Per RFC-1738, the slash is used within the URI as a hierarchical separator and the slash is used to separate resources that are "relative" to the resource left of the resource after the slash. I've currently been using Postman for testing a private corporate API and my test uses query parameters like so e.g. http://someserver:8357/parent/child?name=Bob and it doesn't work. I added a slash e.g. http://someserver:8357/parent/child/?name=Bob and it does work now. We cannot assume that Postman is in error. We have to assume that the service implementation is in error. Per section 3.3 HTTP of RFC-1738 the URL with query parameters is like so "http://host:port/path?searchpart". I wouldn't blame your error on Postman. The implementation behind the URL you are sending would be at fault.

**Comment by evanmiller67** [comment]
Based on your comment, the URL listed in the steps to reproduce would be incorrect (i.e. https://postman-echo.com/get).

This problem has nothing to do with the resource in question, but trying to replace the host/port portion of the URI with the parameter listed.

**Comment by kamalaknn** [comment]
Hi,

I would suggest using the new `{{variable}}` syntax in these cases. The newer syntax has better support for these cases and has better features.

All you would have to do is convert `http://:host/` to `http://{{host}}/`.
