### ISSUE TITLE
Data editor within header preset modal doesn't have autocomplete enabled

### ISSUE THREAD

**Issue by AdaptableTester** [a85/POSTMan-Chrome-Extension#3862]
__Steps to reproduce the problem__ (Desktop v5.3.2)
1. Go to 'manage header presets' dialog.. there is a placeholder message  "_Quickly add groups of header key/value pairs to the request. Start typing the name of the preset name and it'll show up in the dropdown list._"
2. But when I give a 'header preset name' and start typing in the 'Key' and 'Value' fields, the __dropdown list does NOT show up automatically__ 

PS: ahh another observation.. sorry to be pedantic about the message text.... "Start typing the **name** of the **preset name**" does it sound right ?

**Comment by sdnts** [comment]
Hey @skumar45, I'm able to see the header preset in the Header section when I type in the header preset value. Where are you typing when looking for the preset?

<img width="1033" alt="screenshot 2017-11-27 18 06 30" src="https://user-images.githubusercontent.com/7689783/33266990-b831f61a-d39d-11e7-8e7a-fb7dd9c43827.png">

Also, the message is wonky for sure, I'll look into this.

**Comment by AdaptableTester** [comment]
@madebysid It's not from the main section (the screenshot you've attached) mate. The issue is  from the 'MANAGE HEADER PRESETS' dialog box ... 'Add header preset'.

Click on 'Preset's from the RHS of your screenshot. Manage 'header presets' dialog appears... Then you see the message text .. click 'Add' and that's where it is.
![image](https://user-images.githubusercontent.com/922566/33324622-0e7c0592-d448-11e7-9a70-ed9644757689.png)

**Comment by AdaptableTester** [comment]
Any luck yet ?

**Comment by prashantagarwal** [comment]
@skumar45 This is fixed in our latest version of Postman app.
