### ISSUE TITLE
Make postman available as a desktop app on ubuntu :)

### ISSUE THREAD

**Issue by PurpleBabar** [a85/POSTMan-Chrome-Extension#3863]
Hi guys, i love postman, but since it's an appimage now, it's not automatically available as a desktop app in ubuntu. In order to do so, ubuntu just needs a .desktop app, so i made a gist :)

https://gist.github.com/PurpleBabar/567fbe8f43ed6a171af72cb488da147c

Anyway, just wanted to post it here so people can find the solution if they search it :)

**Comment by j-blandford** [comment]
Very useful, definitely needs a .deb installer (maybe allowing for auto-updates, too?) Would make this program even greater

**Comment by sdnts** [comment]
@PurpleBabar Thanks for this! We will look into this for sure :)

**Comment by a85** [comment]
We are available as a Linux app. We are tracking requests for installers elsewhere.
