### ISSUE TITLE
Postman's internal login endpoint returns 500 internal server error

### ISSUE THREAD

**Issue by j-blandford** [a85/POSTMan-Chrome-Extension#3864]
Hello
It seems that the login feature of Postman is currently non-functional, and I cannot access the app at all! 
Some debugging in Chrome gives me the following request when trying to login on the website:

Request URL:https://identity.getpostman.com/login
Request Method:POST
Status Code:500 Internal Server Error
Remote Address:52.73.37.51:443
Referrer Policy:no-referrer-when-downgrade

**Comment by markashton** [comment]
Also getting a 500 when trying to log in. Is there a way to use this offline, because getting a 500 and not being able to use the app has highlighted a risk with relying on this tool. Hopefully just a temporary blip.

**Comment by j-blandford** [comment]
@markashton  I had some success getting the app to open by unplugging my ethernet cable before logging in, and then reinserting it midway. It's a hack, but I am able to use the program again. 

If you click "Sign out" when the dialog box appears, when it asks to delete local data, you can press "Cancel" and it keeps your logged in data whilst being signed out. I think that's a bug but it works in our favour in this instance

I agree, I hope this is a temporary blip because this tool is very important for me and it really shouldn't force you to login to use the app (i.e. an offline mode)

**Comment by SamvelRaja** [comment]
@prasoc @markashton we are facing a small internal downtime, things will be normal soon.

**Comment by markashton** [comment]
Thanks @SamvelRaja - things seem to be working now.

**Comment by shahzadamunawer** [comment]
internal server error showing again and again

**Comment by zsong** [comment]
Same error today. Pure garbage
