### ISSUE TITLE
can't sign in, gave me 'Something went wrong. Please try again later.'

### ISSUE THREAD

**Issue by unifreak** [a85/POSTMan-Chrome-Extension#3866]
## App Details:
```
Window 64
Post man native app
(Can't find the version anywhere)
```

## Issue Report:
Today, postman suddenly told me that my sign in session is expired, and prompt me the login page. I typed in my login info, hit the sign in button, and after awhile, it gave me `Something went wrong. Please try again later.`. I tried again and again, still can't login. also, the `https://getpostman.com/` url is not accessable, too.

## Update
I also tried sign in with Google account, but the opened window is blank. I can visit Google site fine.

I tried restart my computer, reinstall postman and restart my network interface. All have no effect on this problem. Also I tried use Chrome extension back, but the extension didn't work also, when I hit `Send`, it just hanging there in `loading` status.

**Comment by sdnts** [comment]
@UniFreak Can you try again now?

**Comment by unifreak** [comment]
@madebysid I just tried again. same result. Is there additional thing I can provide to you for debug?

**Comment by sdnts** [comment]
@UniFreak Do you see any errors in the Console?
Since you say you cannot send any requests, it sounds like the app is unable to talk to the internet. Do you use a proxy or something?

Can you also drop in an email to help@getpostman.com from the email you use to log in?

**Comment by unifreak** [comment]
@madebysid after I click `Sign In`, there is only two network request. one is `https://app.getpostman.com/api/signin` with my authentication payload, and it got stalled. Another is `https://analytics.getpostman.com/events`, and this one got a fine response.

Here what's in my console:
![image](https://user-images.githubusercontent.com/7945546/33319623-54029f40-d47a-11e7-98c8-776af70f4cfd.png)

I have send a email to help@getpostman.com with my login email address.

**Comment by unifreak** [comment]
@madebysid I let my colleague tried to sign in his account, he is in Mac, and never has registered one account. He tried sign in with google, and works fine. We are in the same network, and I don't have a vpn connected.

**Comment by unifreak** [comment]
I have to fallback to earlier version to continue my API development. 5.3.2 force me to sign in.

**Comment by unifreak** [comment]
Today I tried to download the latest version of Postman(5.3.2), now I can sign in. I guess there was something wrong with your auth service earlier?

**Comment by sdnts** [comment]
@UniFreak We did for a little while, glad it's resolved now :)
