### ISSUE TITLE
setEnvironmentVariable Test Causes Environment Variable to Delete

### ISSUE THREAD

**Issue by johnmeredith** [a85/POSTMan-Chrome-Extension#3868]
## App Details:
Postman for Windows
Version 5.3.2
win32 10.0.14393 / x64

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there: Recent
 2. Expected behaviour: pass parsed variable into environment variable
 3. Console logs
```
GET /snomedct/search
cache-control: no-cache
postman-token: cdfdcd0d-2adf-4b86-af00-703547f23d75
user-agent: PostmanRuntime/6.4.1
accept: */*
host: msdata.org.uk:8080
accept-encoding: gzip, deflate
HTTP/1.1 200
status: 200
date: Tue, 28 Nov 2017 13:01:48 GMT
content-type: application/json
vary: Accept-Encoding, User-Agent
content-encoding: gzip
content-length: 165
server: Jetty(9.3.z-SNAPSHOT)
{"data":[{"term":"Latex","conceptId":111088007,"preferredTerm":"Latex"},{"term":"Latex protein","conceptId":255774009,"preferredTerm":"Latex protein"},{"term":"Latex specific IgE","conceptId":388365001,"preferredTerm":"Latex specific immunoglobulin E"},{"term":"Latex specific immunoglobulin E","conceptId":388365001,"preferredTerm":"Latex specific immunoglobulin E"}],"total":4}
```

Steps to reproduce the problem
1. I have set an environmnet variable 'sct-id'
2. I add the following test:
```
var jsonData = JSON.parse(responseBody);
postman.setEnvironmentVariable("sct-id", jsonData.conceptId);
```
3. I send the request, and the response comes back OK. However the enironment variable is not passed, and the variable then dissapears from the Environment.

I suspect that there are two things happening here:
1. I am not scripting the test correctly.
2. This error is then triggering the bug described elsewhere ;-)

**Comment by johnmeredith** [comment]
OK - solved it - array syntax but anotehr exampel of the variable delete bug.

```
var jsonData = JSON.parse(responseBody);   
postman.setEnvironmentVariable("sct-id", jsonData.data[0].conceptId);
```

**Comment by sdnts** [comment]
@johnmeredith Can you make sure the value of the variable does not evaluate to `undefined`?

**Comment by harryi3t** [comment]
Hi @johnmeredith,
I was able to reproduce this issue and we are working on a fix for this.
Also, I found that the same was reported earlier here https://github.com/postmanlabs/postman-app-support/issues/3557. I am closing this issue and will be posting further updates on the original issue
