### ISSUE TITLE
407 Errors over Proxy with Authentication

### ISSUE THREAD

**Issue by chrisrymer** [a85/POSTMan-Chrome-Extension#3869]
## App Details:
Postman helps you develop APIs faster
Postman for Mac
Version 5.3.2
OS X 15.6.0 / x64

I have just switched to the Desktop app and was setting up some oauth endpoints. I was constantly getting 'Could not get any response'.

![image](https://user-images.githubusercontent.com/1926784/33329385-54ad39d0-d454-11e7-9449-dfd2ba56d6a5.png)

With the resultant error:
`Error: tunneling socket could not be established, statusCode=407
Proxy:
host:"PROXY"
port:8080
match:"http+https://*/*"
Request Headers:
cache-control:"no-cache"
postman-token:"xxxxx-xxxxx-xxxxx-xxxxx-xxxxx"
content-type:"application/json"
Request Body:"{"grant_type": "password", "email": "xxxxxxxxxxx@xxxxxxxxxx.com", "password": "xxxxxxxxxxxxxxxxxxxx"}"`

This appeard to be related to authentication over our corporate proxy. If I copy the setup as curl it works perfectly fine.

Is there any workaround to fix this, as of now I will have to take it off the network to do these requests. Strangely a GET for a google.co.uk has no problems but I think that is likely to be down to our proxy rules.

**Comment by prashantagarwal** [comment]
@chrisrymer Did you try using Proxy settings inside app.

**Comment by chrisrymer** [comment]
I did, I tried a couple of the know tips to get it working. It’s doesnt seem to be able to use the proxy via the OS but didn’t seem to work when I specifically put in usr:pass.

If I output the command as curl it worked fine in terminal. I’ll try again on Monday and update

**Comment by harryi3t** [comment]
Support for auth in proxy is not there yet.
There is a feature request for this here https://github.com/postmanlabs/postman-app-support/issues/3566
Please upvote and/or subscribe to the original issue for updates.
