### ISSUE TITLE
Enhancement request: Increase size limit of example

### ISSUE THREAD

**Issue by gjnk** [a85/POSTMan-Chrome-Extension#3873]
Increase example size limit from 100,000 characters to 5,000,000 characters.
I frequently see JSON responses over 1MB in size, so this would be a useful enhancement.

**Comment by sdnts** [comment]
@gjnk We've been looking to increase this limit as pointed out in [this](https://github.com/postmanlabs/postman-app-support/issues/3589#issuecomment-339801253) issue. Closing this one.
