### ISSUE TITLE
Importing a collection does not find form-data parameter files.

### ISSUE THREAD

**Issue by pschumacher** [a85/POSTMan-Chrome-Extension#3875]
Importing a collection does not find form-data parameter files.

Steps to Reproduce:
1. Create a collection which contains a request that has a form-data parameter of type file.
2. Export the collection into the same folder, where the file exists 
3. Check the exported json file
-> src of the file is exported fine
4. Import the folder which contains the previously exported collection and file

Actual Results:
form-data parameter of type file is empty

Expected Results:
at least a folder import can find files, which are located inside the choosen folder.

**Comment by sdnts** [comment]
@pschumacher We currently do not store file references when you save collections for portability and security reasons. We're tracking this as a feature request in #3740
