### ISSUE TITLE
POSTMAN Native App v5.3.2 sends GET instead of PUT

### ISSUE THREAD

**Issue by cdeckelm** [a85/POSTMan-Chrome-Extension#3876]
I switched to the POSTMAN Native App v5.3.2.

When trying to send a PUT request to my application with a JSON Body (Content-Type: application/json) / RAW, I'll receive a GET Request in my logfile.

Tn the meantime, the exact same request being sent from the old Chrome app will be correct.

**Comment by sdnts** [comment]
Hey @cdeckelm, is the endpoint you're trying to hit public? If not, is there a public endpoint that behaves this way?
If it's private and you'd rather not share it here, you can email us at help@getpostman.com so we can investigate. Thanks :)
