### ISSUE TITLE
Please reauthenticate and try again

### ISSUE THREAD

**Issue by spottedmahn** [a85/POSTMan-Chrome-Extension#3880]
## App Details:
```
Postman for Windows
Version 5.3.2
win32 10.0.16299 / x64
```

## Issue Report:

I'm trying to get an `access token` [from within postman against Azure AD B2C](https://stackoverflow.com/questions/47275079/request-access-token-in-postman-for-azure-ad-b2c/47275299) and I'm receiving the following error:

>AADB2C90085: The service has encountered an internal error. Please reauthenticate and try again.
 Correlation ID: bee2c5c1-2c04-4687-bdb7-d3d20f71ec7e
 Timestamp: 2017-11-29 23:46:19Z

The trouble is, I'm not getting the login screen again from B2C that I received the first time.

**Comment by sdnts** [comment]
@spottedmahn Are there any cookies set by that domain? Can you try clearing them and see if you get the logic screen again?

**Comment by Tvde1** [comment]
How did you fix this?? Production is down :sob:
