### ISSUE TITLE
Postman opens in the background after using multiple monitor

### ISSUE THREAD

**Issue by eyemouth** [a85/POSTMan-Chrome-Extension#3881]
![screen](https://user-images.githubusercontent.com/25559357/33411910-3d0fb878-d5c3-11e7-99c6-e64816ce88f0.png)

## App Details:

```
Postman for Windows
Version 5.3.2
win32 6.1.7601 / x64
```

## Issue Report:
It was working fine before, but now if I want to start it, after I click starting icon,  I can just see the icon in the taskbar without any starting page. I have tried to reinstall several times and results are the same. The Chrome version is working fine in my computer.

**Comment by SamvelRaja** [comment]
@eyemouth  Can you try removing C:\Users\[USER]\AppData\Roaming\Postman\requester.json
ruuner.json and console.json

**Comment by eyemouth** [comment]
@SamvelRaja Sorry for replying late. I have fixed it by maximizing it using taskmgr. It seems postman is working well in the background for I can see it in the taskmgr. Thank you for your reply.

**Comment by mguoth** [comment]
I had the same problem (I use 3 monitors). I have solved it by turning off 2 side monitors and have kept on just the primary one. After the Postman window reappeared, I have turned on these 2 monitors back again. Now the postman works normally. As it is a clear bug, shouldn't be this one reopened?
