### ISSUE TITLE
Tab "Authorization" does not work

### ISSUE THREAD

**Issue by roukmoute** [a85/POSTMan-Chrome-Extension#3883]
## App Details:
```
Postman helps you develop APIs faster
Postman for Linux
Version 5.3.2
linux 4.4.0-98-generic / x64
```

## Issue Report:
 1. Always been there
 2. Expected behaviour:
Send a request
 3. Console logs: Nothing visible
 4. Screenshots are in the report

Currently I have a problem with "Authentication" tab and only on Linux.
When I use Basic Auth for example and I send a request:
![image](https://user-images.githubusercontent.com/2140469/33429332-af959332-d5cc-11e7-8e89-8f968002567d.png)
But nothing appends, it stay on the same screen indefinitely:
![image](https://user-images.githubusercontent.com/2140469/33428682-15d0e384-d5ca-11e7-9ca6-315c8c0e273e.png)

If I write manually the header without "Authorization", it works:
![image](https://user-images.githubusercontent.com/2140469/33429279-7bed5ace-d5cc-11e7-81c5-48a611f7f5a4.png)
![image](https://user-images.githubusercontent.com/2140469/33428753-6ad0e03c-d5ca-11e7-9739-6c531f2be1ac.png)

When I tried "Preview Request" on "Authorization" tab, it generate the same things:
![image](https://user-images.githubusercontent.com/2140469/33428995-57531cae-d5cb-11e7-8f19-820c412b9e27.png)

On Postman Console, the request does not send with "Authorization" tab but manually yes.

I've tried with and without variable, it changes nothing.

**Comment by kamalaknn** [comment]
Coul you open the `DevTools`(View -> Show DevTools) and check if there are any errors?

**Comment by roukmoute** [comment]
I forgotten to specify this but in my issue but nothing happens.
![image](https://user-images.githubusercontent.com/2140469/33487181-af83dfee-d6ac-11e7-989e-02dda332dfaf.png)

**Comment by kamalaknn** [comment]
@roukmoute 

From your screenshot I could see that you have a custom `Authorization` header defined. Please remove any headers and Postman will automatically attach `Authorization` headers.

Please update your app to the latest version and let us know if you face any issues.
