### ISSUE TITLE
Postman opens in the background after using multiple monitor

### ISSUE THREAD

**Issue by midasdy** [a85/POSTMan-Chrome-Extension#3886]
Hi,

I have been using Postman without any issues until I plugged my Windows 10 Surface Book to USB with dual monitor. I can see the instance in the task bar but not able to bring the app to the 'top'.

I have tried and uninstalling and reinstalling v5.3.2 and removing the Chrome extensions without resolution.

Has anyone encountered this and have resolved the issue?

Regards,
Midas

**Comment by SamvelRaja** [comment]
Tracking it here @midasdy #3881
