### ISSUE TITLE
version 5.4.0 posts incorrect payloads when edited 

### ISSUE THREAD

**Issue by danledgard** [a85/POSTMan-Chrome-Extension#3890]
## App Details:
```
Postman for Mac
Version 5.4.0
OS X 16.7.0 / x64
```

## Issue Report:

Following the update to 5.4.0 opening a request created previously to update and editing the raw payload does not send the expected data

* Open an existing POST or PUT request that was created prior to the 5.4.0 version and edit the raw payload
* Send the request
* The requests sent will contain the payload of the request BEFORE the editing

Opening an existing POST/PUT request and amending the payload should result in the new payload being sent

Note that amending the url or payload, saving the request and closing the tab seems to resolve the issue. Opening up the tab and amending the payload does then result in the new payload being sent.

**Comment by oofpez** [comment]
I was just coming here to report this, I'm experiencing this as well.

**Comment by kamalaknn** [comment]
Hey, 

We are trying to reproduce this. We suspect that this might have something to do with your current state of data. 

Could you export the data in your app (Settings -> Data -> Export data) and send to help@getpostman.com? If you have sensitive information in your data you can export the particular collection and remove the sensitive data before sending it to us.

**Comment by danledgard** [comment]
Unfortunately I cannot export all the data as there is far too much sensitive pieces in there, redacting it all would change all the collections, environments etc.

However I have been able to reproduce this using the Postman Echo collection.
* open the Request Methods POST request
* edit the body to add more lines
* open the Postman console and send the request
* looking at the body of the request in the console shows the new lines are missing

I have attached the Postman Echo collection export
[Postman Echo.postman_collection.json.txt](https://github.com/postmanlabs/postman-app-support/files/1522392/Postman.Echo.postman_collection.json.txt)

**Comment by kamalaknn** [comment]
@danledgard Thanks for reporting the issue. We've identified the issue and will be fixing it in the next release. 

In the meantime, you can switch to `5.3.2` from the Changelog section here - https://www.getpostman.com/apps

**Comment by aruckoj** [comment]
I also can reproduce the same issue on 5.4.0 and 5.4.1-canary01.
The issue remains when duplicating an original response.
Can also reproduce with freshly imported collections (via ["Run in Postman"](https://app.getpostman.com/run-collection/57aa74ccb45fb269ac54#?env%5BPandaDoc%20API%20Reference%5D=W3sidHlwZSI6InRleHQiLCJlbmFibGVkIjp0cnVlLCJrZXkiOiJjbGllbnRfaWQiLCJ2YWx1ZSI6IiJ9LHsidHlwZSI6InRleHQiLCJlbmFibGVkIjp0cnVlLCJrZXkiOiJjbGllbnRfc2VjcmV0IiwidmFsdWUiOiIifSx7InR5cGUiOiJ0ZXh0IiwiZW5hYmxlZCI6dHJ1ZSwia2V5IjoicmVkaXJlY3RfdXJpIiwidmFsdWUiOiJodHRwczovL3d3dy5nZXRwb3N0bWFuLmNvbS9vYXV0aDIvY2FsbGJhY2sifSx7InR5cGUiOiJ0ZXh0IiwiZW5hYmxlZCI6dHJ1ZSwia2V5IjoiYWNjZXNzX3Rva2VuIiwidmFsdWUiOiIifSx7InR5cGUiOiJ0ZXh0IiwiZW5hYmxlZCI6dHJ1ZSwia2V5IjoicmVmcmVzaF90b2tlbiIsInZhbHVlIjoiIn0seyJ0eXBlIjoidGV4dCIsImVuYWJsZWQiOnRydWUsImtleSI6InRlbXBsYXRlX2lkIiwidmFsdWUiOiIifSx7InR5cGUiOiJ0ZXh0IiwiZW5hYmxlZCI6dHJ1ZSwia2V5Ijoic2Vzc2lvbl9pZCIsInZhbHVlIjoiIn1d) button).

**Comment by SamvelRaja** [comment]
@danledgard The fix for this issue is pushed in our latest canary 5.4.1-canary02. Kindly, check the same from your end. https://www.getpostman.com/canary

**Comment by aruckoj** [comment]
Everything became normal for me on 5.4.1-canary02.
Thanks for the fix!

**Comment by danledgard** [comment]
@SamvelRaja I can confirm that 5.4.1-canary02 is working as expected

Thanks for the rapid resolution on this

**Comment by SamvelRaja** [comment]
Thanks all for the patience :) 
I would recommend everyone to stay in Canary channel if you guys need the features ahead 😄

**Comment by SamvelRaja** [comment]
This patch has been included in our latest 5.4.1 version 😄
