### ISSUE TITLE
Double quotes in curl examples

### ISSUE THREAD

**Issue by demystifier** [a85/POSTMan-Chrome-Extension#3894]
Greetings
This is a feature request: 

I would like to suggest curl client examples be generated with double quotes instead of single quote. That way api doc authors could use environment variables in the header/body examples and users can set those environment variables and easily get a working example by copy/paste them from postman. This eliminates the need to manually modify postman examples to correct things like  auth_tokens. 

Also for improved readability I would like to suggest replacing "--request" with "-X"  

Thanks

**Comment by kamalaknn** [comment]
Hi, 

Postman uses the [httpsnippet](https://github.com/Kong/httpsnippet) library for generating code examples. Could you bring this up with the authors of the parent project?
