### ISSUE TITLE
Duplicate authorization header not matching expected advertised behavior.

### ISSUE THREAD

**Issue by trev** [a85/POSTMan-Chrome-Extension#3895]
## App Details:

```
Postman for Mac
Version 5.3.2
OS X 17.2.0 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:
> Recently
 2. Expected behaviour:
> The manual authorization header should be overridden as per the messaging: **This is a duplicate header and will be overridden by the Authorization header generated by Postman.**
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
> N/A
 4. Screenshots (if applicable)

In the following gif, the Postman injected authorization header access token is valid but the manual one is invalid. According to the messaging, you'd expect the manually added authorization header to be ignored but this is not the case:

![postman_bug](https://user-images.githubusercontent.com/260079/33531797-5a7f659a-d8e6-11e7-942c-a169c8effade.gif)

P.S You really need the ability to refresh access tokens within your OAuth2 helper.

**Comment by kamalaknn** [comment]
Hi @trev,

Thanks for reporting this issue. We can confirm this behaviour. We'll roll out a fix for this in the release.

About the refresh token flows, we do have plans to enhance the current OAuth 2.0 implementation.

**Comment by kamalaknn** [comment]
@trev This should be fixed in the latest release. Could you update your app and check if it works?

**Comment by AkshataNH** [comment]
I am seeing the same issue in my Postman and I have version 6.4.4, and I guess this is the latest version.

**Comment by kamalaknn** [comment]
Hi @AkshataNH, I just tried this flow again. I could see that user specified header is overridden by the Authorization helper added by Postman, which is the expected behavior as explained by the messaging.

Are you not seeing this work as expected? Could you give a screen recording or a collection that would reproduce this issue?

**Comment by AkshataNH** [comment]
Thats fine you can resolve this issue
