### ISSUE TITLE
[Bug] - All tests are marked as passed in the 'Test Results' tab when tests have failed

### ISSUE THREAD

**Issue by Faz540** [a85/POSTMan-Chrome-Extension#3896]
**Postman Version: 5.4.0 Windows**

Given I have a request that returns the below response:
```
[
	{
 		"name": "Paul",
     	"age": 28
  	},
  	{
  		"name": "David",
  		"age": 30
	}
]
```

The below test will/should fail:
```
var response = JSON.parse(responseBody); 
tests["Length of Array is 0"] = response.length === 0;
```
All tests are marked as passing in the 'Test Results' tab.
However when looking at the tests this is actually failing.

![image](https://user-images.githubusercontent.com/9334128/33547673-c0dad554-d8dc-11e7-81d9-d16e471ba863.png)

I've tried writing this the "old" and "new" way and both give the same issue.
```
var response = JSON.parse(responseBody); 
pm.test("Length of Array is 0", function() {
    pm.expect(response.length).to.equal(0);
});
```
![image](https://user-images.githubusercontent.com/9334128/33548044-cf407bca-d8dd-11e7-8b45-92c48a13eb48.png)

**Comment by SamvelRaja** [comment]
Tacking in here #3888
