### ISSUE TITLE
Nodejs code generated via Postman

### ISSUE THREAD

**Issue by sumit1317** [a85/POSTMan-Chrome-Extension#3898]
Hi,
An api call from postman is working perfectly fine, but when I take the code from postman and run it as part of nodejs, it is giving me an error. Code generated by postman is -
var options = { method: 'POST',
url: 'https://uat.nlis.mla.com.au/soap/upload.aspx',
headers:
{ 'postman-token': '52cdfc42-4f0f-fd7c-0e94-3301a3c0e520',
'cache-control': 'no-cache',
'content-type': 'multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW' },
formData:
{ '':
{ value: fs.createReadStream(__dirname + 'nlisMovement.xml'),
options: { filename: 'nlisMovement.xml', contentType: null } } } };
request(options, function (error, response, body) {
if (error) throw new Error(error);
console.log(body);
resolve(body);
});

Attachment file named nlisMovement.xml is -

<SOAP-ENV:Envelope
xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/"
xmlns:nlis="http://www.nlis.com.au/soap/ver2.0/nlis-soap.xsd">
SOAP-ENV:Header
nlis:originator-grp
nlis:userxxxxxx</nlis:user>
nlis:passwordxxxxxxx</nlis:password>
nlis:emailxxxxxx@xxxxxx.com</nlis:email>
</nlis:originator-grp>
nlis:create-date20171201</nlis:create-date>
nlis:create-time135203</nlis:create-time>
</SOAP-ENV:Header>
SOAP-ENV:Body
nlis:P2PTransfer
nlis:transaction-nameMy P2P Transfer</nlis:transaction-name>
nlis:transfer-date20171201</nlis:transfer-date>
nlis:buyer-pic3MRDG099</nlis:buyer-pic>
nlis:free-text2004 Weaners</nlis:free-text>
nlis:nvd-grp
nlis:event-time13:30:00</nlis:event-time>
nlis:nvd-serial-no1009675</nlis:nvd-serial-no>
nlis:pic3WERT546</nlis:pic> nlis:tag-list-grp
nlis:rfid982 123525464162</nlis:rfid>nlis:rfid940 110000856447</nlis:rfid></nlis:tag-list-grp>
</nlis:nvd-grp>
</nlis:P2PTransfer>
</SOAP-ENV:Body>
</SOAP-ENV:Envelope>

I am receiving following error from server.
<SOAP-ENV:Envelope xmlns:SOAP-ENV='http://schemas.xmlsoap.org/soap/envelope/'>SOAP-ENV:BodySOAP-ENV:FaultSOAP-ENV:ClientContent-Type should be set to text/xml</SOAP-ENV:Fault></SOAP-ENV:Body></SOAP-ENV:Envelope>

I have tried setting text/xml inside both header and formData respective locations, but no success. Any guidance and pointers will be highly appreciated.

**Comment by sdnts** [comment]
@sumit1317 Maybe there's an issue with your backend service? It is very difficult for us to debug without information about your server.
Closing as this is not related to Postman. Please reopen if you feel otherwise :)

**Comment by sumit1317** [comment]
It is related to Postman, because API call from Postman is working perfectly fine ( hence no issue in server ) , but the NodeJS code generated from Postman is not working fine.


Regards,
Sumit Singh Chadha

**Comment by sumit1317** [comment]
If anyone can help on this ?
