### ISSUE TITLE
Postman native app is not working

### ISSUE THREAD

**Issue by malyalal** [a85/POSTMan-Chrome-Extension#3899]
## App Details:
My team is using Postman pro paid version. Since the Postman's chrome add-on is deprecated, we are trying to using the native app. However that never opens, if it opens after several attempts, cache clear etc, it is not synced correctly with the latest changes.
This is lagging our work progress. 
I see messages like "opening valves... moving sattelites into position etc.." The wait time to open the app is quite annoying at the moment
Postman for Mac
Version 4.11.0
OS X 16.4.0 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:
 2. Expected behaviour:
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 4. Screenshots (if applicable)

<!--
Steps to reproduce the problem
-->


<!--
Some guidelines: 

1. Please file Newman-related issues at https://github.com/postmanlabs/newman/issues

2. If it’s a Cloud-related issue, or you want to include personal information like your username / collection names, mail us at help@getpostman.com

3. If it’s a question (anything along the lines of “How do I … in Postman”), the answer might lie in our documentation - http://getpostman.com/docs.
-->

**Comment by a85** [comment]
Seems like you are on an outdated copy. Can you get a new version from www.getpostman.com
