### ISSUE TITLE
[Bug] - Using the Copy shortcut command needs to be performed twice in order for it actually store the value in clipboard

### ISSUE THREAD

**Issue by Faz540** [a85/POSTMan-Chrome-Extension#3904]
**Version: Windows 5.4.1**

This bug must have been raised before but I couldn't find it in the issue backlog, so I'm raising just incase it hasn't been raised :)

**Issue:**
Users are unable to copy items to clipboard using the CTRL+C shortcut command  from the "environment quick look" window. In order to copy items to the clipboard they have to perform the copy command twice.

This issue has been mentioned by everyone in our office that has used Postman and found it very annoying.

**Steps To Replicate:**

1. Select an environment from the dropdown list and confirm that there are environment variables present.
2. Click the "eye" icon to open the Environment Quick Look window
3. Highlight a environment variable value
4. Press the shortcut command to copy the value (CTRL+C)
5. Open a text editor and attempt to paste the value into it.
6. Notice the value was not pasted.
7. Go back to Postman and highlight the environment variable value again.
8. This time press the Copy shortcut command twice.
9. Go back to the text editor and paste.
10. Notice the value has now been successfully pasted.

Unable to confirm the same occurs for the Mac app.

**Comment by NuSkooler** [comment]
This is happening to me as well -- in what appears to be any field in the application.

Elementary OS Loki x86_64 (Ubuntu 16.04)

**Comment by SamvelRaja** [comment]
Thanks for bringing this to our notice. We will patch this up in one of our releases.

**Comment by y3g0r** [comment]
This is happening to me as well in standalone app (5.5.0) since chrome app was deprecated.
Ubuntu 16.04.3 LTS 64-bit and gnome desktop environment (ubuntu-gnome-desktop 0.58.3). 
Thanks to this issue now I know that I can workaround this problem by repeating Ctrl-C twice.

Nor Ctrl-C neither right-mouse-click, copy, don't work for me not only in environment quick look window but everywhere in UI

**Comment by prashantagarwal** [comment]
Can you guys update to Postman v 6.1.3 and see if it is still happening for you.

**Comment by vahids** [comment]
Version 6.1.3 (6.1.3) still has this issue. on Mac with Command + C

**Comment by prashantagarwal** [comment]
Tracking in #4759
