### ISSUE TITLE
Blank page when trying sign in via google

### ISSUE THREAD

**Issue by akaradzha** [a85/POSTMan-Chrome-Extension#3905]
## App Details:

```
Postman for Linux
Version 5.3.2
linux 4.4.0-101-generic / x64
```

## Issue Report:
getting blank page when trying to sign in with google account

console output:
Starting Browser login with URL: https://www.getpostman.com/client-login-appid?id=undefined&app_id=erisedstraehruoytubecafruoytonwohsi&version=5.3.2&channel=prod&type=app_native&platform=linux&os=linux 4.4.0-101-generic&architecture=x64
Cleared all storageData for clean session: login_enterprise
![screenshot from 2017-12-05 11-41-55](https://user-images.githubusercontent.com/19554649/33600265-6887eff6-d9b1-11e7-8fb1-b34f02d45ed2.png)

**Comment by prashantagarwal** [comment]
@akaradzha Thanks for reporting this. Would it be possible for you to provide a screenshot of console inside devtools.

**Comment by akaradzha** [comment]
its a native app,  also i'm using system proxy
http_proxy , https_proxy

system: ubuntu 16.04 lts

**Comment by magmasystems** [comment]
I also experienced this problem yesterday on a Macbook. We also use the system proxy and are behind a firewall.

**Comment by ebonnet** [comment]
I also experienced the same problem from Ubuntu 16.04 OS. 
The workaround is to use postman from google chrome application but I would prefer to use native postman client application.
Don't know if this following log can help:
`(postman:1933): LIBDBUSMENU-GLIB-WARNING **: About to Show called on an item wihtout submenus.  We're ignoring it.
`

**Comment by sivcan** [comment]
Hi all, 
Kindly download the latest version - [Postman 6](https://www.getpostman.com/apps) 
If the issue still persists, feel free to reopen this issue and then we'll take a look at it.
