### ISSUE TITLE
Move the OAuth2 "Use token" button to a better location

### ISSUE THREAD

**Issue by butlnor** [a85/POSTMan-Chrome-Extension#3906]
## App Details:
```
Postman for Windows
Version 5.3.2
win32 6.1.7601 / x64
```

The button for "Use token" is hidden well below the token data. This is completely unintuitive and a bad UX. Can it be moved to a more obvious and visible location?

This is how it looks in my case, I need to scroll to get to the button:

![token](https://user-images.githubusercontent.com/11555256/33602069-80c9df50-d9ae-11e7-820d-57861747a931.png)

Also, the token management is worse in 5.3.2 that it was before. It was a simply accessible list before, while now I need to select "Manage tokens" in a dropdown to get to the list. At least two clicks more. Bad design.

In my case, tokens expire after 10 minutes, so I need to request another one very often, so I get a lot of expired tokens. Can there be a button to remove ALL the old tokens at once? 

I guess you focused only on the case, when one token is valid for an indefinite time, so it can be reused all the time.

**Comment by butlnor** [comment]
Also, if I open the OAuth login dialog in a browser, it can remember the username/password. But when the same login dialog is opened inside Postman via "Get new access token", it cannot remember them, so I need to enter them every 10 minutes. Can something be done about this?

**Comment by prashantagarwal** [comment]
@butlnor Thanks for suggesting this. We will definitely take a look at this. I will keep you updated about this.

**Comment by vikiCoder** [comment]
Hi @butlnor,

We have moved the `Use Token` button to the top of the modal. Please update to the latest version of Postman app(v7.23.0) to check it out.

![image](https://user-images.githubusercontent.com/16588032/80679607-d5a3b200-8ada-11ea-836d-ba310e363271.png)
