### ISSUE TITLE
Display status codes for examples in documentation

### ISSUE THREAD

**Issue by cascer1** [a85/POSTMan-Chrome-Extension#3908]
## App Details:

```
Postman for Windows
Version 5.4.1
win32 10.0.15063 / x64
```

## Issue Report:
When I define examples for my requests in postman, I can set a status code when creating a response. However, this status code isn't visible in the online documentation (`documenter.getpostman.com/...`). This makes it more difficult for people implementing my API to know which status codes they can expect, and what the response bodies with such a status code might look like.

It would be great if generated documentation included status codes, and perhaps a little description of the examples.

**Comment by prashantagarwal** [comment]
@cascer1 We are already tracking this in #3417 . I am closing this as duplicate.
