### ISSUE TITLE
Remember OAuth2 username and password

### ISSUE THREAD

**Issue by butlnor** [a85/POSTMan-Chrome-Extension#3909]
## App Details:
```
Postman for Windows
Version 5.3.2
win32 6.1.7601 / x64
```

If I open the OAuth2 login dialog in a browser, it can remember the username/password. But when the same login dialog is opened inside Postman via "Get new access token", it cannot remember them, so I need to enter them every time. Can something be done about this?

**Comment by prashantagarwal** [comment]
@butlnor Thanks for reporting this. I am not sure we would want to do that for security reasons. The browser is able to do it because you might have enabled autocomplete fields in your browser settings (to which Postman has no access).
