### ISSUE TITLE
Postman sometimes doesn't send POST data

### ISSUE THREAD

**Issue by hskrasek** [a85/POSTMan-Chrome-Extension#391]
While testing the API Routing of my Laravel 4 application, I noticed that one of my routes was not receiving the POST data.

I first approached the Laravel community, which suggested I try using cURL from the command line to see if the Route is still messing up, which to my surprise it actually worked.

So here I am, letting you know that sometimes Postman wont send the POST data/POST request to the server. I wish I had more information like a debug output or something, but I couldn't find anything useful to provide.

Let me know if you need anymore information.

**Comment by kugyousha** [comment]
Same problem, which is strange because it was working yesterday

**Comment by abhijitkane** [comment]
@tomazahlin @kugyousha Can you attach a screenshot of your Postman screen (with the headers section expanded) when you're trying to send the request?

Also, could you follow the steps at http://blog.getpostman.com/index.php/2014/01/27/enabling-chrome-developer-tools-inside-postman/ and check if there are any errors in the console after you hit 'Send'?

**Comment by tomazahlin** [comment]
Hi, it works for me now.  think it was a Chrome issue.

**Comment by deadlydragon00** [comment]
what port does postman used?

**Comment by pwm** [comment]
Same here. Suddenly (at least it seems like) it stopped sending POST data for an endpoint I'm currently testing.

**Comment by abhijitkane** [comment]
@ghost Postman uses Chrome's XHR object to make requests. The TCP port that's used to make requests is not known to Postman - Chrome will choose this randomly while making a request. The server port that the request is made to will be 80 if none is specified.

@pwm What version of Postman are you using? (Settings > About)
If the Interceptor is not enabled, you can check the exact request payload in the Network tab of the DevTools window - http://blog.getpostman.com/2015/06/13/debugging-postman-requests/

**Comment by pwm** [comment]
@abhijitkane My issue was this #102

**Comment by noc2spam** [comment]
Same problem

```
POST /xxxxx/api/web/v1/doctor/schedule HTTP/1.1
Host: 192.168.0.105
Cache-Control: no-cache
Postman-Token: 8dfbd6fc-6f57-dc87-caa3-e0b543859ef8
Content-Type: application/x-www-form-urlencoded
```

I get 
        {
          "name": "Method Not Allowed",
          "message": "Method Not Allowed. This url can only handle the following request methods: POST.",
          "code": 0,
          "status": 405,
          "type": "yii\web\MethodNotAllowedHttpException"
        }

It was working even yesterday and all of a sudden, it does not work anymore.

```
    POSTMAN details:
    Version 3.1.6 (packaged)
    OS: win
    Architecture: x86-32
    Native client architecture: x86-64 
```

**Comment by abhijitkane** [comment]
@noc2spam Are you sure that a redirect is not happening? If the URL you enter is redirecting to something else, the second request will be a GET. To check this, enable the Interceptor and set "Automatically follow redirects" to No in the Postman settings dialog.

**Comment by noc2spam** [comment]
@abhijitkane No just double checked, there's no redirect happening.  The same method works when I use another REST client/ older version of Postman (Server returns 200 OK.).

**Comment by abhijitkane** [comment]
@noc2spam Can you follow the steps at http://blog.getpostman.com/2015/06/13/debugging-postman-requests/ to enable DevTools and open the Network section?

When it's open, check the 'Preserve log' checkbox and send the request. You should see the exact request and response payload.

**Comment by zmorris** [comment]
Confirmed, I just experienced this with two Postman tabs with identical urls and multipart/form options with the same file selected.  One tab worked repeatedly and the other did not, and I have two coworkers as witnesses.

Reselecting the same file from the find file dialog did not fix it.  But selecting a different file and then selecting the original file DID fix it.

I believe a clue to the issue is the generated -F "filekey=@[object Object]" curl command which did not work when I pasted it in the console (because it's supposed to be the name of the file), so Postman is most likely looking up the file through its own OS call or from cache and this is the step that's failing.  The actual call to the server completes but contains no multipart form body.  Also there was a superfluous -F option in the curl command which shouldn't have been there, because I had the other text form part unchecked.  So this portion of the Postman code needs to be reexamined.

I'm using Laravel 5 within Vagrant and it's possible the my tinkering with routes or dd() responses may have somehow upset Postman's cache, but I doubt it.  Here's a typical dd(Input::file()) output from the working tab:

array:1 [
  "filekey" => UploadedFile {#30
    -test: false
    -originalName: "mymovie.mp4"
    -mimeType: "video/mp4"
    -size: 191484
    -error: 0
  }
]

And from the failing tab:

[]

It's unlikely I'll be able to replicate this in the future because it's a rare bug, so hopefully this is a thorough enough report to squash it.  Thanks for the great work on Postman.. now if there was only a find command.. :-)

Postman 4.3.1
Chrome 51.0.2704.84
Mac OS X 10.11.4 (15E65)

**Comment by rommelatienza** [comment]
unable to see my fileName even
 though i already attach it.

----WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="data"; filename=""
Content-Type: 

![image](https://cloud.githubusercontent.com/assets/12545654/16575325/f149e744-42b9-11e6-9910-afe89f77604e.png)

**Comment by abhijitkane** [comment]
@rommelatienza Your screenshot shows the response headers. The server doesn't need to include the filename. The filename is included in the request body.
![screen shot 2016-07-05 at 12 55 28](https://cloud.githubusercontent.com/assets/681190/16576912/cdcb832c-42af-11e6-8787-9c2a7ee3f0b7.png)

**Comment by Arkitecht** [comment]
I am seeing this happening - but in the opposite manner. I have a POST request that succeeds in Postman, but fails via cURL cli and PHP curl with a 405 Method Not Allowed. I made the request with no data - just hitting the URL.

**Comment by redbeandev** [comment]
i am getting [object object] in Generate Code PHPcurl.Can anybody suggest on how to get the filename instead

**Comment by jasonlav** [comment]
I'm getting this issue as well. I have a POST request, but the server is receiving a GET request.

**Comment by noc2spam** [comment]
Okay as for my problem, it was a redirect indeed!! Please make sure that there isn't a redirect in your case @jasonlav. It is sometimes very tough to figure that out.

**Comment by andyslater99** [comment]
Hello, I also appear to be having this issue on OSX (10.12.2) + Postman (4.10.3) + Laravel (5.4), the app always receives the request as a GET? Any solutions?

Andy

**Comment by charanpreetKaur** [comment]
I am sending request to postman, that is supposed to download a pdf report. But postman is picking up the old jasper file inspite of it been updated in java code. how do i fix it?

**Comment by jcnitkkr** [comment]
I'm getting this issue as well. I have a POST request, but the server is receiving a GET request.

**Comment by westphalen** [comment]
This has happened sporadically to me several times in the past, and continues to do so now in your native clients. In my most recent scenario, changing the method from PUT to POST made the body data reach the server. Also switching to x-www-form-urlencoded data seems to work. But really frustrating that I think I'm looking at a problem with my code, and really it's just the data not reaching the server.

**Comment by sridhar576** [comment]
This has happened sporadically to me several times in the past, and continues to do so now in your native clients. In my most recent scenario, changing the method from PUT to POST made the body data reach the server. Also switching to x-www-form-urlencoded data seems to work. But really frustrating that I think I'm looking at a problem with my code, and really it's just the data not reaching the server.



by following above steps  i am getting the 200 status, but how ever in the body i get  **Bad Request**
 <div class="login_cta_container normaltext">
                                        <div id="login_cta_text" class="cta_message_text 1">
                                                Sorry, but we’re having trouble signing you in.
                                                    
                                            <p>We received a bad request.</p>
                                            <p></p>
                                        </div>
                                    </div>
                                                   <tr style="display: none">
                                            <td>HTTP Error Code: 400</td>

**Comment by kyleturner** [comment]
Still experiencing this issue on the native Mac client. Agree very frustrating, how can we help?

**Comment by zlanich** [comment]
I'm also experiencing the no POST Body data issue on OSX with the latest Postman. No fix?

**Comment by greatbob6** [comment]
I ran into this problem with the latest native Windows client, with a request that I imported from the Chrome web app.  The request was doing a POST with x-www-form-urlencoded and I found that switching to form-data made it work, so I tried removing all of my body variables in 'x-www-form-urlencoding' and readding them one by one and now it seems to be working with that encoding as well.

**Comment by Logarathamic** [comment]
![image](https://user-images.githubusercontent.com/36884784/36725360-19772f54-1bdc-11e8-80c3-e7bd97c8d85a.png)

**Comment by dileephell** [comment]
I'm getting the sameissue as well. I have a problem with POST request, but the server is receiving a GET request.

**Comment by numaanashraf** [comment]
@dileephell This can happen if Postman received a redirect from the API. But default, Postman would follow the redirect and in the process change the POST to GET, to keep the behavior at par with browsers and other user-agents.

https://tools.ietf.org/html/rfc2616#page-62
>However, most existing user agent implementations treat 302 as if it were a 303 response, performing a GET on the Location field-value regardless of the original request method.

**Comment by Ajmal0197** [comment]
Pass data in Body as x-www-form-urlencoded that is located below url...
