### ISSUE TITLE
[Bug] CSV Runner not working for subfolders

### ISSUE THREAD

**Issue by poniat** [a85/POSTMan-Chrome-Extension#3912]
**Version:**
Windows desktop v5.4.1

Today I have updated Postman to newest version. I have used runner for my collection, and it was fine.
After that I have used runner and selected **CSV file**.
Postman detected how many rows I have in CSV, but when I run it - it does nothing.

I have tried with 20 rows, 200 rows and 3k rows - each time I have 0 pass and 0 fails. Request are not send to my backend service.

**Comment by SamvelRaja** [comment]
@poniat I tried reproducing the issue you are facing, but it seems working for me.
Attaching a gif to ensure that this is the use case i need to check
![runnercsv](https://user-images.githubusercontent.com/5114052/33655708-d8ed6cc4-da99-11e7-9811-d68c93f9608a.gif)

**Comment by poniat** [comment]
@SamvelRaja I assume you have same version as me.. only difference is that you are using Mac and I use Windows version.

This is what I experience:

![csv_seeder](https://user-images.githubusercontent.com/2472934/33656431-532e8c9e-da76-11e7-91df-201658013e7c.gif)

**Comment by SamvelRaja** [comment]
@poniat You have sync enabled?
If so check the collections in the your dashboard and relogin in the app.
Seems like the data is corrupted internally.
If is not enabled, just move the nested folder to the top level and run it, it should work.
Meanwhile we first patch this up in our next canary release.

It is recommended to take the backup of data, if the sync is not enabled. 
Settings -> Data -> Download

**Comment by poniat** [comment]
@SamvelRaja I don't sync scripts. Everything I have is my local copy.

But when I moved my subfolder to top and execute runner - then it's working fine.

Thx for helping me. For now I will use this walkaround.

**Comment by sivcan** [comment]
@poniat I can confirm that CSV along with running subfolders are working perfectly fine on the latest version of the postman app. (i.e. v6.1.4 as of now)

If the issue still persists for you, let us know.
