### ISSUE TITLE
Allow reordering of examples

### ISSUE THREAD

**Issue by cascer1** [a85/POSTMan-Chrome-Extension#3913]
## App Details:

```
Postman for Windows
Version 5.4.1
win32 10.0.15063 / x64
```

## Issue Report:
Currently, request examples cannot be re-ordered. I like to order my examples by status code. 
Because of this, my examples might become out of order when I add a new one that doesn't have the highest status code.

I would like to be able to change the order in which examples appear.

**Comment by sdnts** [comment]
Hi @cascer1, you're right in noticing that examples do not have an order right now. We'll be working on this soon. You can follow #1070 for updates.
Closing this as duplicate :)

**Comment by nam-vu-360f-com** [comment]
Have we got it possible in 2020 please?

**Comment by namgivu** [comment]
https://github.com/postmanlabs/postman-app-support/issues/1070
Can we have it possible today 2020?

**Comment by namgivu** [comment]
Currently by now, I export the collection, edit the exported json file to reorder the example response, then import them back. Quite a verbose and tiring process indeed.

**Comment by E-Thang** [comment]
I've just been messing with this, It doesn't seem like it's working even as @namgivu suggested. I can import from JSON in the order I want, and it looks good in the Windows application. However, when I publish the document some of the examples are in random order. I even tried incrementally importing examples, first I imported with only a single expected response, then imported with the same expected response and one error response, and so on. It still ended up in random order.
