### ISSUE TITLE
Examples don't properly sync to online documentation

### ISSUE THREAD

**Issue by cascer1** [a85/POSTMan-Chrome-Extension#3917]
## App Details:

```
Postman for Windows
Version 5.4.1
win32 10.0.15063 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:  
I have always encountered this issue
 2. Expected behaviour:  
When removing or modifying examples, these changes should be correctly synced across devices and to online documentation

1. Create request with several examples
2. Sync to postman cloud
3. Modify some examples, and remove some others
4. Duplicate the request
5. Do some more modifications
6. Duplicate examples appear in online documentation, with other examples missing

**Comment by sdnts** [comment]
@cascer1 Does the icon on the top right say `IN SYNC`?
Can you also try doing a force sync? You can do this by clicking on that icon. It should momentarily turn blue, then back to orange.

Let me know if either of these things help.

**Comment by cascer1** [comment]
@madebysid Unfortunately syncing (either waiting for the automatic sync, or manually syncing by pressing the button) does not resolve the issue. The weird part is that these duplicated and incorrectly removed examples do not display as such inside postman itself, everything in postman looks the way it should.

It seems to happen only when I duplicate a request that already has some examples, and then modify the duplicated request. However, sometimes removing an example in the duplicated request also removes the example from the original request.

**Comment by dncosta** [comment]
Yeah... unfortunately this is not a new thing. Their syncing is not trust worthy yet.
It's easiest way is duplicating the whole collection and publishing the new one.

**Comment by sivcan** [comment]
Hi all,
I suggest you all to kindly update to the new version of the [Postman App](https://www.getpostman.com/apps) 

If the issue still persists, then feel free to reopen this issue.

**Comment by seitbekir** [comment]
I got this issue again. And also some extend on it.

So, I've created the docs yesterday and it was keeping in sync. But today after I've added new folder it just not updated. And after force sync also. Then I've tried to rename existing one and I've got same -- no sync. On examples, urls, etc...

Beyond that, if there was some body record and you removing it (set body "none") it just keep the last body record.

The issue is still there.

**Comment by sivcan** [comment]
@seitbekir Since you're having this issue with more things other than just examples, can you create a new separate issue?
Also, can you please add your app version, OS details etc. to it so that it'll help us triage this issue faster?

Thanks

**Comment by FelixButzbach** [comment]
I just experienced the same problem. I deleted all of the examples for one request and added new ones (without the mock server api key) but the old example requests are still appearing with the x-api-key header.
The new examples are there, too, but after the old examples.
Do you need any other information for debugging this?

Update: Nevermind, my bad. I deleted the wrong examples apparently from a wrong place. After dublicating and finding the same examples again in the documentation I found a (different?) place that had all my examples and I was able to delete them and after some seconds they disappeared from the documentation.
