### ISSUE TITLE
Updater displays unhelpful error for self-signed HTTPS certificates

### ISSUE THREAD

**Issue by Stevoisiak** [a85/POSTMan-Chrome-Extension#3918]
## App Details:
```
Postman for Windows
Version 5.3.2
win32 6.1.7601 / ia32
```

## Issue Report:

If an error occurs when attempting to download a Postman update with *File -> Settings -> Update*, Postman will display a [vague and non-specific error message](https://user-images.githubusercontent.com/1330770/33669679-22428234-da71-11e7-89ae-144d50417142.png).

> **Something went wrong. Please check your connection and try restarting the app.**

I suspect my specific download issue is due to using Postman on a corporate network which intercepts HTTPS traffic, (SSL Certificates are self-signed). SSL interception is a [fairly common practice](https://security.stackexchange.com/q/107542/141087) when on corporate networks.

To help users diagnose download errors, I would expect to see a more descriptive message. For example:

> **The connection to `https://dl.pstmn.io/` is not secure, as the SSL certificate could not be verified.**

## Steps to reproduce the problem

1. Connect to a corporate network which uses self-signed SSL certificates.
2. Check for updates with *File -> Settings -> Update*.
3. After viewing the update change-log, select *Update* to begin downloading the update
4. Wait a few seconds for "Downloading Update" to fail.

**Comment by thecuriousdev** [comment]
@Stevoisiak thanks for reporting this issue. We'll look into this and try to display this error in an informative way. We'll keep you posted here.

**Comment by SamvelRaja** [comment]
@stevoisiak  We had updated our updater to provide proper bubbling up of errors from the background. You can update the app to our latest 6.1.4 to avail it.
https://www.getpostman.com/docs/v6/postman/launching_postman/installation_and_updates#updating-postman
