### ISSUE TITLE
Copy as cURL for GET requests also contains body from previous non-GET request.

### ISSUE THREAD

**Issue by tanwangzugata** [a85/POSTMan-Chrome-Extension#3920]
## App Details:
```
Postman for Mac
Version 5.3.2
OS X 16.7.0 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:
Just started using Postman
 2. Expected behaviour:
Request body is not copied when copying as curl

1. Make a POST request with Postman (include a raw body in the request)
2. Change to a GET method - the "Body" tab is disabled but still contains the body i used for POST
3. Copy as curl - the POST body is still there but I am copy-as-curl-ing a GET request (and I cannot edit away the body from postman if my HTTP verb is set to GET

**Comment by tonyzheng121** [comment]
This is a big bug.

when a send a GET request, then change to send POST resquest, but it still send a GET request.

**Comment by thecuriousdev** [comment]
@tanwangzugata thanks reporting this issue, We are able to re-produce this issue, and will get it fixed soon.

**Comment by sujayvenaik** [comment]
Hey @tanwangzugata @tonyzheng1990 
We have released a fix for this and is up on Postman Canary.
Can you verify this once ?

You can get the canary app from : https://www.getpostman.com/canary

**Comment by sujayvenaik** [comment]
@tanwangzugata @tonyzheng1990 
Its already fixed.

Closing this issue for now, reopen if you face any other issues related to this.

You can get the postman app from : https://www.getpostman.com/apps
