### ISSUE TITLE
Create packages for Linux-based OS

### ISSUE THREAD

**Issue by zamazan4ik** [a85/POSTMan-Chrome-Extension#3921]
Hello,
I use Postman on Linux-based OS (now it's Fedora 27). And on Linux i must download tarball from Postman's site, extract it and run Postman executable. 

For Linux-users native way is using package managers. 

Can you create packages for the most widely-used Linux-based OS (Debian, RHEL, Ubuntu, Fedora, etc.)? There are only two major package type: .deb and .rpm.

Also you can choose way with Snap, Flatpak or AppImage.

**Comment by thecuriousdev** [comment]
@ZaMaZaN4iK thanks for this feature request, we are tracking this in #2931
