### ISSUE TITLE
Duplicated request loses body after saving example

### ISSUE THREAD

**Issue by jfneis** [a85/POSTMan-Chrome-Extension#3924]
## App Details:
Postman for Linux
Version 5.3.2
linux 4.4.0-59-generic / x64

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there: found it this week after working with several SOAP XML requests/responses.
 2. Expected behaviour: after saving the first example, the request body should remain the same as the one that originated the request.
 3. Console logs: doesn't apply
 4. Screenshots (if applicable)

Steps to reproduce the problem:

1. Create a new POST http://www.google.com/ request and save "abcd" to its body (raw);
2. Duplicate the request, change its body to "1234", send it, save it and save the response as an example;
3. Save the example. When you return to the request, it will be with body abcd instead of expected 1234.

**Comment by thecuriousdev** [comment]
@jfneis thanks for reporting this issue, We'll look into it, and will keep you posted here.

**Comment by sivcan** [comment]
Hi @jfneis - I tried to reproduce this issue on the latest version of [Postman](https://www.getpostman.com/apps) but couldn't

I suggest you to update to the latest version and try again.
If the issue still persists then feel free to reopen it.
