### ISSUE TITLE
Restrive iteration status using : postman.__execution.tests

### ISSUE THREAD

**Issue by RuggeriLuca** [a85/POSTMan-Chrome-Extension#3925]
Hi , 
using the previews version of Postman i was able to run the below command in the tests phase , so i was able to retrieve all tests that was run for the iteration 

    var verification = JSON.stringify(postman.__execution.tests);. 

Now with the new version the above command return Null string . 

My scope is to retrieve the status of the iteration to understated if there are failed test or not 

How i can do it now ?

Luca

**Comment by SamvelRaja** [comment]
@LRuggeriPostman 
You can very well use the tests object.
console.log(JSON.stringify(tests));
But, anyway, the async tests won't be available in that.
Can you provide us the use case for the that?
![tests](https://user-images.githubusercontent.com/5114052/33764330-015f00c2-dc3a-11e7-9cd3-ac37c183f2fa.gif)
