### ISSUE TITLE
Need help with JSON nested response

### ISSUE THREAD

**Issue by mighty98** [a85/POSTMan-Chrome-Extension#3928]
Guys, can someone please help with below.
My JSON response has a structure like below. I need to store all location ids for user 2 here in a variable in postman. How do i do it

[
    {
        "email": "mit@mit.com",
        "firstname": "mit",
        "lastname": "mit",
        "id": 3979,
        "location": [
            {
                "id": 1,
                "location_name": "Chennai",
             }
        ],
    },
    {
        "email": "xxx@xxx.com",
        "firstname": "nutan",
        "lastname": "user",
        "id": 509,
        "location": [
            {
                "id": 1,
                "location_name": "Chennai",
               
            },
            {
                "id": 2,
                "location_name": "Bangalore",
              
            },
            {
                "id": 3,
                "location_name": "Hyderabad",
                
            },
            {
                "id": 27,
                "location_name": "Delhi",
               
            }
        ],
       
    },

**Comment by thecuriousdev** [comment]
You can make use of test scripts in Postman App, https://www.getpostman.com/docs/postman/scripts/test_scripts

And save the data into an environment variable

This might be helpful,
https://www.getpostman.com/docs/postman/scripts/postman_sandbox

**Comment by mighty98** [comment]
Thanks @thecuriousdev. However these didnt help me with the speicific query :(

**Comment by a85** [comment]
Please direct coding questions to stackoverflow.com or community.getpostman.com
