### ISSUE TITLE
Variables within a variable in the environment scope

### ISSUE THREAD

**Issue by BrianKilby** [a85/POSTMan-Chrome-Extension#3929]
We use to be able to declare a global/environment variable that referenced other variables such as the below.  With the latest Postman release v5.4.1, this no longer works.  Is this lost of functionality by design or in error?  We used this technique to reduce/eliminate duplication.  As of v5.4.1, we've had to hard-code those values in 2 places.  Not ideal.

Example environment file:
{
  "id": "9414a5a6-13d5-a9d2-5de9-4e02af0a41aa",
  "name": "localhost-QATrunk-151365",
  "values": [
    {
      "key": "core-header-authorization",
      "value": "SRT-INTERNAL {{core-companyLifeSuiteCode}};{{core-class}};{{core-companyId}};{{core-userLifeSuiteId}}",
      "type": "text",
      "enabled": true,
      "warning": ""
    },
    {
      "key": "core-companyLifeSuiteCode",
      "value": "151365",
      "type": "text",
      "enabled": true,
      "warning": ""
    },
    {
      "key": "core-class",
      "value": "test",
      "type": "text",
      "enabled": true,
      "warning": ""
    },
    {
      "key": "core-companyId",
      "value": "151365",
      "type": "text",
      "enabled": true,
      "warning": ""
    },
    {
      "key": "core-userLifeSuiteId",
      "value": "996655",
      "type": "text",
      "enabled": true,
      "warning": ""
    }
  ],
  "timestamp": 1481225425639,
  "_postman_variable_scope": "environment",
  "_postman_exported_at": "2016-12-08T19:30:47.720Z",
  "_postman_exported_using": "Postman/4.9.0"
}

**Comment by kamalaknn** [comment]
Hi @BrianKilby ,

We are trying to reproduce this. I imported this environment and used it with a request. I am able to see the variable being resolved.

![out](https://user-images.githubusercontent.com/8401064/33764473-82bb8546-dc3a-11e7-87ae-3668f944984f.gif)

Could you provide more information to help us debug this?

**Comment by BrianKilby** [comment]
Try with an aync call such as :

// Load live schemas for comparison
    pm.sendRequest({
        "url": pm.environment.get("core-protocol") + "://" + pm.environment.get("core-domain") + "/jobBoardsApi/v1.0/jobBoards/schema",
        "method": 'GET',
        "header": {
            "Accept-Language": pm.environment.get("core-header-accept-language"),
            "Authorization": pm.environment.get("core-header-authorization")
        }
    }, function (err, response) {
        pm.environment.set("Job_Boards_Live_Schema", response.text());
    });

// Basic test
    tests["Setup completed successfully."] = responseCode.code === 200;

**Comment by kamalaknn** [comment]
@BrianKilby I get your point now. 

If you're using the `pm.environment.get`, it now returns the value and not resolved nested value..

At the moment there is no alternative to this. You'll have to construct the variable in the script. We'll see if we can expose an API to resolve variables to use in the scripts.

**Comment by stramel** [comment]
I don't understand why this is closed...

This is unexpected behavior especially when the variables function differently in the rest of the app.

**Comment by hiugocosta** [comment]
> I don't understand why this is closed...
> 
> This is unexpected behavior especially when the variables function differently in the rest of the app.

Agree. Why was this closed? @kamalaknn when did this bug became a feature?

**Comment by jankuzniak** [comment]
I stumbled on this issue when trying to understand what I did wrong; as a new user I agree wholeheartedly - not resolving variables for pre-request script is confusing. In my case, I'm using a variable in the URL and trying to access the URL in the pre-request script using pm.request.url.toString(); An API to resolve variables in the scripts would indeed solve my case - is there a ticket for this?

**Comment by codenirvana** [comment]
@jankuzniak Refer https://github.com/postmanlabs/postman-app-support/issues/6078#issuecomment-473022186

**Comment by jankuzniak** [comment]
@codenirvana thanks for the walkaround! Still voting for the official support 👍
