### ISSUE TITLE
Suggestion: Request Body > Form-data to json

### ISSUE THREAD

**Issue by surajds** [a85/POSTMan-Chrome-Extension#3932]
I believe it will be very useful if we can get any simple functionality to convert the form data (key value list) to json data right in place.

**Comment by SamvelRaja** [comment]
Thanks for providing the feature request. We shall put this to our UX team to get with a better solution.

**Comment by vkaegis** [comment]
@surajds Thanks for suggesting this! No ETA on this just yet, but we'll keep you updated.

**Comment by a85** [comment]
There are no deterministic ways to compare form-data to JSON as they are different formats. There might be 3rd-party tools available to do this and we recommend using those.
