### ISSUE TITLE
Unable to get value of Environment variables  

### ISSUE THREAD

**Issue by Arunkeshavareddy** [a85/POSTMan-Chrome-Extension#3935]
After updating Postman to  5.4.1, Pre-request and Tests Scripts are unable to get the value of Environment variable.

**Comment by anasnajaa** [comment]
@Arunkeshavareddy Did you manage to fix this issue?
I'm having the same problem in Postman v5.5.0, desktop version.

Edit:
I managed to find a temporary fix by replacing "/" in variable names with another character ("_" in this case). Environment variables used to work previously with forward slashes.

**Comment by Arunkeshavareddy** [comment]
Hello Anas Najaa,
Your solution is not working on mine. Thanks for the advice.

**Comment by sdnts** [comment]
@Arunkeshavareddy @anasnajaa How are you guys getting the environment variables in your test scripts?

**Comment by Arunkeshavareddy** [comment]
Hello Siddhant Sinha,
Both Pre-request and Test Scripts are unable to get values of Environment
variables after updating postman to 5.4.1 & 5.5.0

**Comment by sdnts** [comment]
@Arunkeshavareddy What I meant was, can you share the part of your test / pre-request script where you get the variables?
