### ISSUE TITLE
Issue with request to Virtual Machine

### ISSUE THREAD

**Issue by MikeBergstrom** [a85/POSTMan-Chrome-Extension#3936]
## App Details:

```
Postman for Windows
Version 5.4.1
win32 6.1.7601 / x64
```

## Issue Report:
 1. Recent Issue
 2. Expected behaviour: API response from virtual machine hosted app
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app): 
Request Headers:
cache-control:"no-cache"
user-agent:"PostmanRuntime/7.1.1"
accept:"*/*"
host:"192.168.99.100:8600"
accept-encoding:"gzip, deflate"
Response Headers:
content-type:"text/html; charset=us-ascii"
server:"Microsoft-HTTPAPI/2.0"
date:"Fri, 08 Dec 2017 18:06:40 GMT"
connection:"close"
content-length:"315"
 4. Screenshots (if applicable)

Requests made to application hosted on virtual machine running on my computer are returning a 404 from the Microsoft -HTTPAPI/2.0 service. The error logs for the Http.sys service show that the service is trying to access the site at the localhost IP address (127.0.0.1) and not the IP address requested.

**Comment by a85** [comment]
I'd recommend testing against postman-echo.com to verify. Closing this as we haven't seen any other issues related to sending of requests being a problem.
