### ISSUE TITLE
Content-Type in consistent Mac App to Chrome App

### ISSUE THREAD

**Issue by ghost** [a85/POSTMan-Chrome-Extension#3937]
When I make an attempt to upload a file, in some instances form-data in the body of the call is all that I need to use. In others it seems as though I have to specifically declare multipart/data content-type in the header otherwise something is overriding the formdata and I get an, "415: Unsupported media type error."

* Other uploads work to other endpoints. Other users (Chrome Browser Client), are able to have success with the same file.
* They are all zip files containing the same structure.
* On different configurations (Chrome Browser Client) we have success.

This is what I am experiencing:
https://stackoverflow.com/questions/22557088/unsupported-media-type-when-puting-to-apigility-with-postman

## App Details:

```
Postman for Mac
Version 5.4.1
OS X 10.13.2 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:
Unknown, have not tested these endpoints in the Mac App before.

 2. Expected behaviour:
Postman Content-Type detection is consistent.

 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):

 4. Screenshots (if applicable)

Unknown, one application (Mac) app does not pass/detect the mutipart form data correctly and I have to manually define the Content-Type in the header.

**Comment by numaanashraf** [comment]
@fxmohammed Are you still facing this issue? We are having trouble replicating this issue at our end, so any sample data you can provide will be helpful.

**Comment by ghost** [comment]
Unable to replicate this issue at the moment. Will make an addendum to this ticket if I am able to again.

**Comment by shamasis** [comment]
Note: we could begin by adding extensive tests with as many combinations we can think of and see if that reveals this issue. cc @codenirvana

**Comment by shamasis** [comment]
I'm assuming that the natural evolution of code over the years have fixed this issue. :-p Closing this. If otherwise, please comment.
