### ISSUE TITLE
stray apostrophe in Team Library message

### ISSUE THREAD

**Issue by ahaberbosch** [a85/POSTMan-Chrome-Extension#3938]
## App Details:

```
Postman for Windows
Version 5.4.1
win32 10.0.15063 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there: Recently
 2. Expected behaviour: "The Team Library and its collaboration tools..."
http://theoatmeal.com/comics/apostrophe

Open Team Library without it being enabled.
"The Team Library and it's collaboration tools..."

**Comment by SamvelRaja** [comment]
Thanks for bringing this to our notice 👍

**Comment by prashantagarwal** [comment]
@ahaberbosch We got this fixed in 5.5.0 release. Thanks for reporting this.
