### ISSUE TITLE
How to setEnvironmentVariable for data from array

### ISSUE THREAD

**Issue by AlexanderTunick** [a85/POSTMan-Chrome-Extension#3940]
Hi. I have this piece of code where i wanna setEnvironmentVariable out of  "id": 1856
I made this:
var Jdata = JSON.parse(responseBody);
postman.setEnvironmentVariable("delete_geo", Jdata.data.data.data.id);

but it doesn't work (value is undefined), could you give me an advice? 
next i gonna pass it to delete request in row {{api_base_url}}target/geo/{{delete_geo}}
{
    "data": {
        "segmentCriteriaId": 11536,
        "data": {
            "targetingId": 2,
            "isAll": false,
            "data": [
                {
                    "city": 2597,
                    "county": null,
                    "state": null,
                    "locationName": "Lostant, La Salle County, IL",
                    "id": 1856,
                    "include": true,
                    "coordinates": {

**Comment by jasperloos** [comment]
Hi Alex, can you try if this is working? 

var Jdata = JSON.parse(responseBody);
postman.setEnvironmentVariable("delete_geo", Jdata.data.data.data[0].id);

**Comment by AlexanderTunick** [comment]
Hi jasperloos, thanks! It works, I made a mistake and could not figure out, but problem turned out to be little nonsense
