### ISSUE TITLE
Postman doesn't bypass proxy for localhost if HTTP_PROXY is set

### ISSUE THREAD

**Issue by abargstaedt** [a85/POSTMan-Chrome-Extension#3942]
## App Details:

```
Postman for Windows
Version 5.5.0
win32 6.1.7601 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:
Our environment has changed recently. So not sure it always behaved like this.
 2. Expected behaviour:
When you issue a request to localhost respectively 127.0.0.1 it should bypass the web proxy. Postman seems to do so until you set the environment variables HTTP_PROXY and HTTPS_PROXY in Windows. By then it always uses these proxy settings even if you turn off system proxy in the options and even for localhost.
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
GET /api/values
cache-control: no-cache
postman-token: ad71f52c-5670-4188-bcf9-8388f1e7d609
user-agent: PostmanRuntime/7.1.1
accept: */*
host: localhost:55355
accept-encoding: gzip, deflate
HTTP/1.1 403
status: 403
content-type: text/html
server: Zscaler/6.0
cache-control: no-cache
content-length: 14402

403

 4. Screenshots (if applicable)

**Comment by abargstaedt** [comment]
I wrote a command line script that works well as a work-around and this way it also confirms that the environment variables are the cause.

<pre>SET HTTP_PROXY=
SET HTTPS_PROXY=
START %LOCALAPPDATA%\Postman\Update.exe --processStart "Postman.exe"</pre>

**Comment by kzettlmeier** [comment]
+1 I can confirm that this is happening on my machine as well.  Using the above work around for now.

**Comment by paulyk1983** [comment]
+1 Same here

**Comment by nrobert** [comment]
Hi all,

Got the same here.
As I cannot remove the HTTP_PROXY and HTTPS_PROXY environment variables for other use, I used another workaround which is solving my problem: set"NO_PROXY" environment variable:

SET NO_PROXY=localhost,127.0.0.1

Then it's working!

**Comment by Jummartinezro** [comment]
Same issue for me
Solved with @nrobert method :)
But it has to be solved on Postman directly

**Comment by Tataraovoleti** [comment]
Having same issue even though i turned off both settings

![image](https://user-images.githubusercontent.com/4704085/38745442-2e71f3f4-3f62-11e8-9f8e-52c1a2581589.png)

**Comment by oauger** [comment]
Thanks @nrobert 💌 You saved my day.

**Comment by holgerl** [comment]
The @abargstaedt trick worked for me! Thanks! 

On my machine, I was not able to remove the `http_proxy` environment variable, and this made it impossible to use Postman on localhost. This behaviour is a real pain

**Comment by MrSleazy** [comment]
@Tataraovoleti Note that if you set the PROXY configs mentioned above as environment variables, you must tell Postman to use those configs at least 😄
![image](https://user-images.githubusercontent.com/4512611/44116165-c2c052a4-9fdd-11e8-981b-c96a3c8901f8.png)

**Comment by magomedov** [comment]
The issue is still here. @abargstaedt thanks for the tip - worked for me!

**Comment by B-Dunbar-Personal** [comment]
The issue is still there,

**Comment by chucklu** [comment]
Encounter the same problem, and make it work with @nrobert 's solution

**Comment by serak** [comment]
I have the same problem, whenever i want to use Postman i have to remove the HTTP_PROXY env't variables. and postman should identify localhost and loopback ip to be bypassed

**Comment by pedrolauro** [comment]
Same here. Tried all solutions above, manipulating system's configurations, setting NO_PROXY var. Nothing worked.

**Comment by chucklu** [comment]
@pedrolauro  What's your configuration for no_proxy?

**Comment by bpeake** [comment]
My issue was a Windows environment variable set for HTTP_PROXY

**Comment by pedrolauro** [comment]
@chucklu no_proxy="localhost"

**Comment by chucklu** [comment]
@pedrolauro  My no_proxy is configured like this , there is no double quotes
```cmd
C:\WINDOWS\system32>set no_proxy
NO_PROXY=localhost,127.0.0.1
```

**Comment by pedrolauro** [comment]
@chucklu I'm on Ubuntu here. Doesn't know if makes any difference to use the quotes or not. Will try it later and then I reply here again.

**Comment by kpkar** [comment]
I had my NO_PROXY set to localhost and 127.0.0.1. But I realized I used ; instead of , in the configuration i.e. NO_PROXY=localhost;127.0.0.1 instead of NO_PROXY=localhost,127.0.0.1.
I feel so dumb right now :)

**Comment by LeonardAB** [comment]
The situation is a bit different but related.

I am behind corporate proxy AND using CNTLM. Before` v7.0.9` I had this problem as well albeit using CNTLM. The workaround is to set the postman proxy as `127.0.0.1` but **set the port** not to the CNTLM port (`3128`) but **to which we want to connect** (`80` if it is not specified). Of course the drawback of this method is that whenever I need to access other ports, I had to change this.

After `v.7.0.9` it seems the problem had disappeared. Now I am able to use `3128` as the proxy port inside postman setting. (then everything else is taken care by CNTLM.)

related SO: https://stackoverflow.com/questions/49130558/postman-cant-reach-localhost

**Comment by coxymla** [comment]
An option in Postman to ignore the HTTP_PROXY (and HTTPS_PROXY?) environment variables would be appreciated, in addition to the existing options to ignore the system proxy and to manually specify a custom proxy. In my case, the environment variables are set so Python can download packages, but when I use Postman I'm always (so far at least) wanting to query internal APIs and don't want to go through any corporate proxies.

**Comment by iqmeta** [comment]
> An option in Postman to ignore the HTTP_PROXY (and HTTPS_PROXY?) environment variables would be appreciated, in addition to the existing options to ignore the system proxy and to manually specify a custom proxy. In my case, the environment variables are set so Python can download packages, but when I use Postman I'm always (so far at least) wanting to query internal APIs and don't want to go through any corporate proxies.

Possible solution more manual settings without using environment vars? like: 

![image](https://user-images.githubusercontent.com/7533842/62520596-2f1dcf80-b82e-11e9-99cb-1aef919a7689.png)

**Comment by rob10e** [comment]
> I had my NO_PROXY set to localhost and 127.0.0.1. But I realized I used ; instead of , in the configuration i.e. NO_PROXY=localhost;127.0.0.1 instead of NO_PROXY=localhost,127.0.0.1.
> I feel so dumb right now :)

I did this as well. Thank you for pointing this out.

**Comment by joaoalber** [comment]
> Hi all,
> 
> Got the same here.
> As I cannot remove the HTTP_PROXY and HTTPS_PROXY environment variables for other use, I used another workaround which is solving my problem: set"NO_PROXY" environment variable:
> 
> SET NO_PROXY=localhost,127.0.0.1
> 
> Then it's working!

Thanks my brother, u saved my day!

**Comment by codenirvana** [comment]
Hey everyone 👋 
We've made some improvements in the latest version of the Postman app (`v7.9.0`) to fix issues around proxy configuration.

We understood the problem discussed in this issue thread and also noticed that few users (knowingly or unknowingly) rely upon the proxy configuration using the`HTTP_PROXY`, `HTTPS_PROXY`, and `NO_PROXY` environment variables.

So, we added a new setting under the system proxy configuration to opt-in or opt-out of proxy configuration through these environment variables.

![Screenshot 2019-10-16 at 1 23 23 PM](https://user-images.githubusercontent.com/4865836/66899227-3de7e600-f018-11e9-9141-af794b984a21.png)

We also added support for bypassing global proxy settings on a per-host basis for those who were relying upon `NO_PROXY` to bypass proxy for localhost (or any other hostname).

![Screenshot 2019-10-16 at 12 39 18 PM](https://user-images.githubusercontent.com/4865836/66899771-24936980-f019-11e9-97d8-c0fd66ff9322.png)

**Comment by angshumanshome** [comment]
> Hey everyone 👋
> We've made some improvements in the latest version of the Postman app (`v7.9.0`) to fix issues around proxy configuration.
> 
> We understood the problem discussed in this issue thread and also noticed that few users (knowingly or unknowingly) rely upon the proxy configuration using the`HTTP_PROXY`, `HTTPS_PROXY`, and `NO_PROXY` environment variables.
> 
> So, we added a new setting under the system proxy configuration to opt-in or opt-out of proxy configuration through these environment variables.
> 
> ![Screenshot 2019-10-16 at 1 23 23 PM](https://user-images.githubusercontent.com/4865836/66899227-3de7e600-f018-11e9-9141-af794b984a21.png)
> 
> We also added support for bypassing global proxy settings on a per-host basis for those who were relying upon `NO_PROXY` to bypass proxy for localhost (or any other hostname).
> 
> ![Screenshot 2019-10-16 at 12 39 18 PM](https://user-images.githubusercontent.com/4865836/66899771-24936980-f019-11e9-97d8-c0fd66ff9322.png)

Thanks. Can you please guide how can I set proxy_bypass along with HTTPS_Proxy from commandline?

**Comment by gopalsingh462** [comment]
I am using postman 7.34.0. My problem is it is giving a response to my home computer but not in office computer. Office computer does not use the proxy at all. 503 error on office computer when requesting remote internet server with POST request and multipart files. On the server-side it shows that it received request and a response was given but before the server responds the postman gives up with 503 with header via->proxy
Timeout is set to 0 in postman.
![postman_error](https://user-images.githubusercontent.com/11767554/98441737-3f55e600-2126-11eb-892d-7ca199cf2927.JPG)

**Comment by bettercallavi** [comment]
i am getting error "Request on loopback from external IP" ,nothing is working for me .

**Comment by angshumanshome** [comment]
You may have to set proxy
Will see when I feel good

What are you testing?
