### ISSUE TITLE
Error Message: Unexpected token ) when I Run folder via Runner and no error when do it manually

### ISSUE THREAD

**Issue by AlexanderTunick** [a85/POSTMan-Chrome-Extension#3947]
Hi everyone!
I have some issue and need some help.

In Collection, I have a folder named "Segments"
I configured 'tests' with Environment variables for requests to be successively executed.
**When I do it manually from 1 request to the last in a folder - everything is ok without any problem.** 

But when I running the same folder via Postman Runner, 
the second request unexpectedly give me **400 Bad Request**
after that accordingly, to not propper second request, the third request is 404 Not Found
and then is showing up this Error

> Something is wrong with your Pre-request scripts. Please fix them in the editor first. Message: Unexpected token )

If you need some info to know more, just write, thanks!

**Comment by sdnts** [comment]
Hi @Alextunchii, would it be possible to share your pre-request script here?
Is your script using some sort of data that makes it so that a part of your code only runs in the Runner (things like this include using the `iteration`, or `data` variables, or a mismatching environment). Your script should clear this out, so I can assist better :)

**Comment by AlexanderTunick** [comment]
Hi @madebysid, thanks for your response. I guess i resolved this issue. The reason might be in that, I wanted to use "pre-script" in this folder, but I couldn't, because I wanted to tie json file to test but I failed trying do that and then deleted "pre-script" from one request where I needed it. But how I understand it, postman still has seen pieces of code in pre script and outputted this error during running. Now it's ok, I run this folder even this iteration and it words fine. Thanks.
