### ISSUE TITLE
Question/Support: Database reset after PUT/POST API request

### ISSUE THREAD

**Issue by dsenta00** [a85/POSTMan-Chrome-Extension#3948]
Hello,

I have started to use your tool recently. Everything works great, but I was wondering what is the best way trigger command (or something else) in order to reset database again to the initial state. 

In other words, the test will return 201 JSON response on the first call, but on the second API call will return 409 (Conflict) as expected. How to avoid that?

Thanks in advance,
Regards,
Duje

**Comment by sdnts** [comment]
Hi @dsenta00, this is something that your server would have to provide. Since Postman does not directly talk to your database, there isn't a way to do this from the app, I'm afraid.
If your server provides a `/reset` endpoint, you can hit that to reset the state of your database.

**Comment by dsenta00** [comment]
That is what I thought also. Thanks for a quick answer!

Regards,
Duje
