### ISSUE TITLE
Discrepancy between collection and published documentation

### ISSUE THREAD

**Issue by LSTANCZYK** [a85/POSTMan-Chrome-Extension#3949]
## App Details:
```
Postman for Windows
Version 5.5.0
win32 10.0.15063 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:
Recently
 2. Expected behaviour:
Collection structure (folders and requests) should match between application and the generated documentation. 
 3. Console logs

================================================================
sails.io.js:142 🌏 sync service connectivity initiated
sails.io.js:759 socket replaying queued commands
2sails.io.js:142 🌏 connected to sync service.
sails.io.js:759 socket replaying queued commands
sails.io.js:142 🌏 disconnected from sync service. possibly a network outage.
sails.io.js:142 🌏 scheduled reconnection attempt #1 after 11893ms
sails.io.js:142 🌏 reconnecting to sync service. #(1/8)
sails.io.js:142 🌏 reconnected to sync service after being offline for 12.199seconds.
sails.io.js:142 🌏 connected to sync service.
sails.io.js:142 🌏 disconnected from sync service. possibly a network outage.
sails.io.js:142 🌏 scheduled reconnection attempt #1 after 8589ms
sails.io.js:142 🌏 reconnecting to sync service. #(1/8)
sails.io.js:142 🌏 reconnected to sync service after being offline for 8.907seconds.
sails.io.js:759 socket replaying queued commands
sails.io.js:142 🌏 connected to sync service.
mode-auto.js Failed to load resource: net::ERR_FILE_NOT_FOUND
sails.io.js:142 🌏 disconnected from sync service. possibly a network outage.
sails.io.js:142 🌏 scheduled reconnection attempt #1 after 9628ms
sails.io.js:142 🌏 reconnecting to sync service. #(1/8)
sails.io.js:142 🌏 reconnected to sync service after being offline for 10.373seconds.
sails.io.js:759 socket replaying queued commands
sails.io.js:142 🌏 connected to sync service.

 4. Screenshots (if applicable)
![image](https://user-images.githubusercontent.com/2145721/33842954-4aed879c-de59-11e7-9185-00e52e3b96b3.png)

Steps to reproduce the problem
I was unable to reproduce the issue, however you can observe it by going to [this link](https://documenter.getpostman.com/view/925441/ax-pos-api-specification/77o1zqo#2eadc00e-14dc-3a4c-10eb-5d7471dd4631)

**Comment by LSTANCZYK** [comment]
I was able to find a workaround for this - by moving API 6 Request in Postman Win app to another folder and then dragging it back to the one where it belongs.

**Comment by sdnts** [comment]
Hi @LSTANCZYK, this usually happens when the app goes out of sync with our Sync servers. When you reorder your requests, it forces a sync, and the order is fixed. Logging out + Logging in should have the same effect. As a side note, what you see in the documentation is always the state of the server.

Have you been able to reliably reproduce this? We're working on improvements that should fix this and a bunch of other sync issues soon. I'm closing this, but please let me know if you manage to reproduce (I'll reopen), it would help us get to the bottom of the problem faster :)

**Comment by santhub** [comment]
Any updates on this issue? Please let me know in which release it will get fixed, if not any ETA
