### ISSUE TITLE
Send button hidden at reasonable window widths

### ISSUE THREAD

**Issue by provmarkayers** [a85/POSTMan-Chrome-Extension#3951]
## App Details:

```
Postman for Mac
Version 5.5.0
OS X 16.7.0 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there: Dunno
 2. Expected behaviour: Send button should always be visible, even when postman isn't taking up 75% of my screen width
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 4. Screenshots (if applicable)
![screen shot 2017-12-11 at 3 26 21 pm](https://user-images.githubusercontent.com/33462894/33859271-f3c56a32-de87-11e7-8500-1411c0005117.png)

Just resize the window to be less wide

**Comment by sdnts** [comment]
Hi @provmarkayers, we ensure the Send button is visible as much as possible for reasons you mentioned. How wide is the Postman window right now? You can open up the DevTools by heading over to the `View Menu > Show DevTools`, and then resizing the window even slightly should show up window dimensions on the top right.

**Comment by provmarkayers** [comment]
Okay, I figured out some more details. When the window is scrolled to the top, the app behaves as expected down to about 900px width, which is acceptable. The issue happens when the window is wider than that when scrolled up to the top, and then the user scrolls down (visually detaching the send/url bar), and then resizes the window to be less wide. On my 2560px wide screen, the send button can be completely covered at a window width of 2350px. The issue can be resolved by simply scrolling to the top, but it's not an intuitive solution.

**Comment by sivcan** [comment]
The [latest version](https://www.getpostman.com/apps) of the app has fixes for the zooming part.
Kindly update to the same.
If you're still experiencing this issue then feel free to reopen it.
