### ISSUE TITLE
Please Add Proxy Setting

### ISSUE THREAD

**Issue by gronel** [a85/POSTMan-Chrome-Extension#3954]
good day Dev,

 I cant continue to used your desktop platform because our connection here is using proxy connection, please see attach file capture.png for your reference visual studio code use same technology as you used Electron build. they check if your connection is used proxy then proxy authentication dialog well appear.

[Capture.png](https://p3.zdusercontent.com/attachment/555292/qfpTYOvJoeqbhnmz5s8AuEjix?token=eyJhbGciOiJkaXIiLCJlbmMiOiJBMTI4Q0JDLUhTMjU2In0..yVjooyWMd3EdUW5iZIy_uQ._-xSglSPxaQcSXCJZPkmfEYbQNrYKl9ovxcU08AfzcXAJj0vBqO1U-4Gv1q_OGb4PaSjNfaseQFFrG2ufQZWgsxCHOHxsSDXHbzlUb-Z2wghajzEk8ZErO16kYcnElWdiejG73g2UdlXkIf6lWGAl9OtQ0HU6OtxYHKleq72E0f_f1RdzcfJfGz7MJIZm78dy8dWaWldCCfIiwcT7oFhEJMof3ol0k_jxERRRLV97dyeIbPYrYBTqDdvGzD5PBE4gzwN1JoiL8ELWtNcvJHTqw.Kfwz0VAWURfwp8e7h5xNIw)

[Error](https://p3.zdusercontent.com/attachment/555292/DFv2M8Jfw0oRkwUrpDcuAhxUa?token=eyJhbGciOiJkaXIiLCJlbmMiOiJBMTI4Q0JDLUhTMjU2In0..qAML08-HIBPREgaxux2k1Q.eT86MMkUqYbbH58PO5lUfqVLYni5hnGvpG0jrulBaImsKc_jcI9C4QakP8KeJMHCeB0BtFmwBEu9n0rpwpxt7D4lIaTt_LjvbeMh8bD5dXAjk1ZXF2Wd5_0EAVndI4HrMilESAoQ-cpkrvW7toIxyWjSAPJfksJ14xREHbodcemIJNh_WIhh6t0lCIU4VA3JataeAVwP1wi1W807Syv-exUQbWn2rwOq-853p8k464VE_Rj_g7-iDockr4S_DVqdpLhCbKBFEEn8-o7zRqa2uw.X4HX67I__bKLFOkyDq_8DA)

**Comment by sdnts** [comment]
Hi @gronel, Postman already supports proxies for requests. If you head over to Settings (`Cmd+,`), you should be able to switch to the `Proxy` tab and set up a proxy there.

**Comment by sdnts** [comment]
It just occurred to me, do you want to use the proxy for signing in to the app, or for sending requests?
