### ISSUE TITLE
Markdown syntax interpreted differently on app than on generated documentation

### ISSUE THREAD

**Issue by jooleeanh** [a85/POSTMan-Chrome-Extension#3955]
## App Details:

```
Postman for Mac
Version 5.5.0 (5.5.0)
OS X 10.12.6
```

## Issue Report:
__1. Did you encounter this recently, or has this bug always been there:__  
Not sure.
__2. Expected behaviour:__  
The preview of a markdown text in a request's description should be the same than standard markdown editors.
__3. Console logs__  
None
__4. Screenshots (if applicable)__  
None

### Steps to reproduce the problem

The following text:

```
@Versions
| Key                        | Type            |
| -------------------------- | --------------- |
| statuses                   | Int             |
```

Because there is no line between @Versions and the beginning of the table, and there aren't any spaces after @Versions, the table should not appear and the raw text should appear inline after @Versions.  
However, the Postman app shows the table properly (it shouldn't), and when the documentation is generated, the table isn't properly shown.

**Comment by sdnts** [comment]
Hi @jooleeanh, thanks for pointing this out, I believe the app should respect Markdown guidelines more strictly, I'll look into this.

**Comment by jooleeanh** [comment]
Here are some screenshots to help:

__4. Screenshots (if applicable)__  

Markdown editing:  
![image](https://user-images.githubusercontent.com/9873597/34040303-5cc70d66-e193-11e7-9725-259b1eca4a7c.png)

Markdown preview in-app:  
![image](https://user-images.githubusercontent.com/9873597/34040290-4f4472dc-e193-11e7-8cbd-414e18720f9e.png)

Generated documentation :  
![image](https://user-images.githubusercontent.com/9873597/34040322-73d9d72c-e193-11e7-950d-d106ddc8aa61.png)

**Comment by bscarlavai** [comment]
I'm seeing this issue as well
```
Postman for Mac
Version 5.5.2
OS X 17.3.0 / x64
```

**Comment by stantond** [comment]
I'm seeing this as well

```
Postman for Mac
Version 6.0.10
OS X 10.13.4
```

In Postman app

```
|Aspect|Definition|
|---|---|
|URI Parameters|None|
|Body Parameters|<pre><code>{<br>    Username: string<br>    Password: string<br>}</code></pre>|
```

Shows as

![screen shot 2018-05-08 at 17 14 52](https://user-images.githubusercontent.com/3207366/39769294-aba30db0-52e3-11e8-8eed-fbc2fa8572ef.png)

But in the generated documentation it's

![screen shot 2018-05-08 at 17 18 16](https://user-images.githubusercontent.com/3207366/39769347-dcb19aac-52e3-11e8-8d8c-4ae049a77af9.png)

This is one of the blockers for us moving our docs to Postman and going Pro

**Comment by harryi3t** [comment]
@jooleeanh Thank you for bringing this in our notice. We have identified the issue and are working on to make the experience the same across our products.

**Comment by numaanashraf** [comment]
@jooleeanh We've pushed a fix to unify the markdown rendering within Postman app and our generated documentation in Postman v7.0.8. Do let us know if you are still facing any inconsistency. Closing this issue for now.
