### ISSUE TITLE
There is no pre-request script's tab when i create a folder.

### ISSUE THREAD

**Issue by IOsonoTAN** [a85/POSTMan-Chrome-Extension#3958]
## App Details:
```
Postman for Mac
Version 5.3.2
OS X 10.12.5 / x64
```

## Issue Report:
1. I tried to create a new folder of collection.
2. I want insert a pre-request script but there is no tabs.

<img width="483" alt="screen shot 2560-12-13 at 14 40 13" src="https://user-images.githubusercontent.com/3783531/33927338-74f2664a-e014-11e7-865f-35ccebff16d3.png">

And i try to update Postman but it show me message "Something went wrong. Please check your connection and try restarting the app."

**Comment by SamvelRaja** [comment]
Can you try https://github.com/postmanlabs/postman-app-support/issues/2489#issuecomment-313596858 specified in this comment?
