### ISSUE TITLE
Postman getting irresponsive on a simple GET request

### ISSUE THREAD

**Issue by isurugiu** [a85/POSTMan-Chrome-Extension#3959]
## App Details:

```
Version 5.3.2 (5.3.2)
macOS Sierra
10.12.6
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there: I just ran into this
 2. Expected behaviour: produce output in the debug window and run the tests
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 4. Screenshots (if applicable)

1. Set a simple get request to: https://www.w3schools.com/cert/cert_bootstrap.asp
2. Create a test having the following code:

var responseHTML = cheerio(responseBody)
console.log(responseHTML.find('sidenav').contents());

3. Click Send

Notice how the application gets stuck shortly.

**Comment by pdougla002** [comment]
I will second this. My colleague did not update his Postman (his is 5.4.0 win/x86-64) and it plays as expected. My updated version (Version 5.5.0 win32 10.0.15063 / x64) no longer performs. Here is a sample response: 
_Could not get any response
There was an error connecting to http://x1.x1.x1.xx6/gohere/v1/resources?fields=results(resourceId,lastUpdatedTime,properties/userData).
Why this might have happened:
The server couldn't send a response:
Ensure that the backend is working properly
Self-signed SSL certificates are being blocked:
Fix this by turning off 'SSL certificate verification' in Settings > General
Proxy configured incorrectly
Ensure that proxy is configured correctly in Settings > Proxy
Request timeout:
Change request timeout in Settings > General_

**Comment by numaanashraf** [comment]
@isurugiu Thanks for reporting this. We were able to replicate this issue and are looking into this.

**Comment by numaanashraf** [comment]
@isurugiu Seems like the app hangs at the console.log step in the test script. Could you verify this by removing the console.log?

**Comment by numaanashraf** [comment]
@pdougla002 Created #3963 to track your issue.

**Comment by isurugiu** [comment]
@numaanashraf I can confirm the app hangs at the console.log which was actually my purpose. I wanted to take a look at that output.

**Comment by pdougla002** [comment]
Thank you, folks! Not clear if you’d like me to try any of this. Let me
know if so
Peter

**Comment by pdougla002** [comment]
I re-tested and please see my console output below. I hand-pasted the jwt
twice and notice it seems to have an extra space at the end of it. This was
not there in my clipboard. Identical GET worked with Fiddler. Thanks!

Filter Messages
Clear

Love working on Postman? Work with us to make Postman better!
https://go.pstmn.io/postman-jobs
GET
http://10.21.1.206/mwe/v1/resources?fields=results(resourceId,lastUpdatedTime,properties/userData,properties/readerId,properties/antennaId)
01:10:10.336
Pretty
Raw
Error: The header content contains invalid characters

   -
      -
      Request Headers:
         - authorization:"Bearer
         eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYWRtaW4iLCJpYXQiOjE1MTMyNzg5MDIsImV4cCI6MTUxMzMyMjEwMiwiaXNzIjoiTVdFLUF1dGgifQ.73eX7u8JFqHPGkv1z7I-9xVNT9BNhwZsVtY-y6A2hzE
         "
         - cache-control:"no-cache"
         - postman-token:"7a1f5b13-e271-4f52-a2e9-df3b10dca7b5"

**Comment by pdougla002** [comment]
Sorry that is pretty useless and now I’m on vacation through 12/18. I’ll
keeep track and try again next week if still needed.
I wondered if the token has a concat white space if that matters

**Comment by AvivSimDS** [comment]
Tested it today again:
With standalone postman 5.5.0 windows app it fails with this error message:
------------------------------------------------------------------------------------------------------
Could not get any response
There was an error connecting to https://cosigndemo.arx.com:8081/sapiws/CreateSign.
Why this might have happened:
The server couldn't send a response:
Ensure that the backend is working properly
Self-signed SSL certificates are being blocked:
Fix this by turning off 'SSL certificate verification' in Settings > General
Proxy configured incorrectly
Ensure that proxy is configured correctly in Settings > Proxy
Request timeout:
Change request timeout in Settings > General
--------------------------------------------------------------------------------------------

With postman addon for chrome 5.5.4 it works perfectly

**Comment by pdougla002** [comment]
Hi folks,
I ditched the Windows version 5.5.0 x64 referenced in this email chain and
am running fine on the Mac version of your app. I'll keep an eye out on
this, but for now can proceed with our API testing etc.
PD

**Comment by sivcan** [comment]
Hi all,
Kindly update to the latest version of the [Postman App](https://www.getpostman.com/apps) 
If the issue still persists, feel free to revert back with further information and we'll reopen it.

**Comment by rishabhmalhotra** [comment]
I am on version 6.0.10 on macOS and the issue has re-appeared.

**Comment by ookiisan** [comment]
Hi! I'm on macOS HighSierra 10.13.6 with Postman 6.4.4 and the issue still persist.

**Comment by numaanashraf** [comment]
@ookiisan Could you provide more information? Is this happening for all requests?

**Comment by ookiisan** [comment]
@numaanashraf not all requests. I was trying to execute this simple snippet
<code>
var r = cheerio(responseBody);
console.log(r);
</code>

**Comment by jimnist** [comment]
this is happening for me.
whenever i do something with cheerio, then try to `console.log()` a result, it hangs. 
os x 10.14 with version 6.5.2
