### ISSUE TITLE
Feature Request: drop down to select domain in address bar

### ISSUE THREAD

**Issue by yaghouti** [a85/POSTMan-Chrome-Extension#3964]
There are many cases that I must publish and test APIs on several servers, so I need to either change the domain of request in address bar or create different requests.
Creating different requests with the same data and keeping them synchronized takes time, so it would be more user friendly if you separate the domain from the rest of address, so we can select the domain using a drop down button.
Thanks

**Comment by prashantagarwal** [comment]
@yaghouti If I understand your use case correctly. You just want to test the same endpoint on different servers. For example. `https://server1.com/get` and `server2.com/get`. If so then what you can do essentially is save your api url as  {{serverUrl}}/get. And save `serverUrl` in your environment. Then you can create different environments with different value for `serverUrl` and then just switch the environment from the dropdown.

**Comment by yaghouti** [comment]
Exactly what I was looking for, even better. Thank you so much.
