### ISSUE TITLE
postman don't resolve environment variables

### ISSUE THREAD

**Issue by qinshiheng** [a85/POSTMan-Chrome-Extension#3966]
I use environment variables which works fine in previous versions. After upgrading to v5.5.0, when sending requests, postman use plain url address instead of resolving it. 
For example, I have an environment variable {{host:port}} which refers to 127.0.0.1:8080, and my url address is http://{{host:port}}/path/to/myapp. In older versions postman will visit http://127.0.0.1:8080/path/to/myapp, and works fine. However in v5.5.0, postman visits http://%7B%7Bhost:port%7D%7D/path/to/myapp.
It is weird that when mouse hovers variable {{host:port}}, it will show the environment infos, but when it comes to send requests, it just use {{host:port}} as a part of the url.

![35tjy q4qt33uroci i6_bh](https://user-images.githubusercontent.com/14308117/33984045-39e28cb4-e0f1-11e7-92c6-73605495e1bf.png)

## App Details:

```
Postman for Windows
Version 5.5.0
win32 6.1.7601 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:
 2. Expected behaviour:
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 4. Screenshots (if applicable)

**Comment by prashantagarwal** [comment]
@qinshiheng Can you try removing `:` from the variable name

**Comment by kalemdzievski** [comment]
Have the same issue in Postman for Linux v6.2.4. Tried to remove ":" but didn't work.
Please reopen the issue.
