### ISSUE TITLE
Is there some changed on Request between Postman for windows and Postman for Chrome App?

### ISSUE THREAD

**Issue by OStoneO** [a85/POSTMan-Chrome-Extension#3968]
## App Details:

```
Postman for Windows
Version 5.5.0
Windows 10(1709/16299.64) / x64
```

## Issue Report:
 1. I used same Url/Header/Body but get two different results。
     Is there some changed on Postman for windows or maybe my settings is wrong(I used default settings)?
 2. Screenshots like
     Chrome App Ver:
     ![Chrome App](https://raw.githubusercontent.com/OStoneO/GitHubStorage/master/Picture/postman1.png)
     Postman for windows Ver:
     ![Postman for windows](https://raw.githubusercontent.com/OStoneO/GitHubStorage/master/Picture/postman2.png)
     Headers:
     ![Headers](https://raw.githubusercontent.com/OStoneO/GitHubStorage/master/Picture/postman3.png)

ps:When I swap two of formats(x-www-form-urlencoded → form-data), the results ware swapped.

**Comment by OStoneO** [comment]
Sorry for my English  _(:з)∠)_

**Comment by prashantagarwal** [comment]
@OStoneO Is it possible for you to debug what is causing your server to crash.

**Comment by OStoneO** [comment]
If status is 500，I can't get params in java.

Used SpringMVC

**Comment by pc-tvaishnav** [comment]
x-www-form-urlencoded request doesn't work on mac native client 5.5.0 - it works on chrome app.

**Comment by loosleef** [comment]
x-www-form-urlencoded request also seems to be broken on windows native client 6.0.10.   'Broken' meaning the request body is not sent (that is, a blank body) in the HTTP call if you watch through a proxy/Fiddler.   

A workaround is to switch request body to `raw` and set the Content-Type header through the Headers tab.

**Comment by a85** [comment]
These should be fixed in our latest versions. The Chrome app is deprecated and bug fixes are in the native app.
