### ISSUE TITLE
Linux update is frustrating experience

### ISSUE THREAD

**Issue by glenpike** [a85/POSTMan-Chrome-Extension#3971]
Postman native update for Mac happens seamlessly - click update and the app will get on with it, you can even tell it to update in the background.  This is lovely.

On Ubuntu, however, it is a different story.  You have to download a tgz, unpack this to a folder on your computer (then remember to re-run the command as root) and run the binary from there.  There's no icon, you have to try to roll this yourself, which is frustrating.

I appreciate that there are so many different packaging systems, but as the software is a pre-built binary, it may be possible to use something like EPM - http://michaelrsweet.github.io/epm/ - to generate packages for various systems (the software is in maintenance mode now, so I don't know if there is a more modern alternative).

**Comment by numaanashraf** [comment]
Thanks for the feedback @glenpike. We are exploring few options to make Postman for Linux easier to install and update. 🙂

**Comment by harryi3t** [comment]
We have added support for auto-updates on Linux. This will be available in the next release 🎉 
If you want to try it out, it already released on canary https://www.getpostman.com/canary

**Comment by prashantagarwal** [comment]
Released with Postman 6.1.2
