### ISSUE TITLE
Error for windows native client

### ISSUE THREAD

**Issue by SyedAmeeruddin** [a85/POSTMan-Chrome-Extension#3972]
## App Details:

```
Postman for Mac
Version 4.11.0
OS X 16.4.0 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:
 2. Expected behaviour:
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 4. Screenshots (if applicable)
![screenshot 1](https://user-images.githubusercontent.com/33616209/34030685-0cee01e0-e194-11e7-89ad-6a7ebda7c61e.png)

**Comment by SyedAmeeruddin** [comment]
For every request this is the response. Please rectify it.I installed recently and it has default configuration.

**Comment by numaanashraf** [comment]
@SyedAmeeruddin Thanks for writing in. Seems like you are trying to send a request to `localhost` over `http`. Please verify that you have a server running that is listening to port `80` on your `localhost`.

**Comment by SyedAmeeruddin** [comment]
Thanks for swift reply.It is by default  as you said in the first place.Kindly suggest me other possibilities.

**Comment by numaanashraf** [comment]
@SyedAmeeruddin Yup. Could you try the steps detailed here
1. Open the Console via (Menu -> View -> Show Postman Console)
2. Send the request
3. Expand the log line for this request in the console
4. Share screenshot of this log in the console. (redact any sensitive information in the logs 🙂 )

**Comment by SyedAmeeruddin** [comment]
![screenshot 3](https://user-images.githubusercontent.com/33616209/34037001-1e603a9c-e1ad-11e7-8c11-faf7b80f393c.png)

**Comment by numaanashraf** [comment]
@SyedAmeeruddin Looks like the server is not responding in time and the request has timed out. Is the same GET request working via cURL or Chrome? Also please verify the request timeout settings in the app (Settings > General > Request > Request timeout in ms) -> should be `0` by default.

**Comment by SyedAmeeruddin** [comment]
The problem is solved now after changing timeout to 0 but i cant comprehend that previously when it is  0 i got the same error.later  i changed  it to 1 for testing.now when i changed to zero it is responding.. By the way before doing this i installed two chrome extensions and i got positive results.Please explain me the exact reason for the error?
![restclients](https://user-images.githubusercontent.com/33616209/34044496-34929dd2-e1cb-11e7-8d39-248da1f7def7.PNG)

**Comment by numaanashraf** [comment]
@SyedAmeeruddin Glad to hear the issue is resolved at your end. We are looking into why the default timeout setting was not being honored initially.

**Comment by SyedAmeeruddin** [comment]
I am so grateful for your support and cordiality.I wonder why default timeout should be zero!?.
