### ISSUE TITLE
Postman duplicating request parameters - in specific cases

### ISSUE THREAD

**Issue by FreeWillaert** [a85/POSTMan-Chrome-Extension#3973]
## App Details:

```
Postman for Mac
Version 5.5.0
OS X 16.7.0 / x64
```

## Issue Report:

I have this issue with 5.5, not only in collection runner (which happened before but I never really looked into it), but now also in the builder.

Steps to reproduce the problem:

Create a collection, then create a request in that collection:
GET {{tmp-uri}}/test?uri=https://example.com
with tmp-uri:http://localhost:3000

The easiest way to reproduce this is if nothing is listening on http://localhost:3000, then you get:
There was an error connecting to http://localhost:3000/test?uri=https://example.com?uri=https://example.com.

It seems to be a rather specific issue:
When I replace the colon in the uri parameter by %3A, it works fine.
If I replace the host varaiable by a literal, it works fine.
If I copy the request to a new tab, outside of a collection, it works fine.
If I generate code rather than executing the request, it looks fine.

**Comment by harryi3t** [comment]
@FreeWillaert Thanks for reporting the issue. I am happy to confirm that this is a known bug and the fix is already in progress. You can expect it to be fixed in the next version :)

**Comment by massukio** [comment]
Same issue in my end, I have a parameter with http:// prefix which causes the request duplicating the parameters. 

and I found a easy workaround is that replace "http://" with "http%3A%2F%2F" which can work perfectly for now. Looking forward to next release :)

**Comment by numaanashraf** [comment]
This issue is fixed and verified in Postman v6.1.4.
