### ISSUE TITLE
Pasting a line in Headers or Body (form-data/url-encoded) unfocuses from request zone (prevents easy use of save shortcut)

### ISSUE THREAD

**Issue by jooleeanh** [a85/POSTMan-Chrome-Extension#3974]
## App Details:

```
Postman for Mac
Version 5.5.0 (5.5.0)
OS X 10.12.6
```

## Issue Report:
 1. Encountered recently (may have been here from the start)
 2. Expected behavior:
    1. Copy 1 or more lines of headers/params from a request
    2. Paste it in the headers/params of another request
    3. Use save shortcut 'cmd-s' -> should save

Steps to reproduce the problem

   1. Copy 1 or more lines of headers/params(form-data/url-encoded) from a request 
   2. Paste it in the headers/params(form-data/url-encoded) of another request
   3. Use save shortcut 'cmd-s': doesn't save

**Comment by sdnts** [comment]
@jooleeanh Thanks for reporting this, I wasn't able to see this.
I copied a parameter from the data editor in Headers and pasted it into the data editor of another request in another tab, and Cmd+S was working as expected. Could you possibly attach a GIF or something so I can try and reproduce exactly the way you are? Thanks.
