### ISSUE TITLE
404 error preventing Sync (stuck in offline mode)

### ISSUE THREAD

**Issue by LaughlinJames** [a85/POSTMan-Chrome-Extension#3978]
## App Details:

```
Postman for Mac
OS X 10.11.6
Version 4.0.5 (4.0.5)
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:

- Just noticed

 2. Expected behaviour:

- I should be able to click the "offline" icon and sync with my online account

 3. Console logs:

- Failed to load resource: the server responded with a status of 404 (Not Found)

 4. Screenshots (if applicable)
- 
![screen shot 2017-12-15 at 11 24 56 am](https://user-images.githubusercontent.com/118043/34053047-af7dd520-e18a-11e7-9b44-63b3bca74096.png)

**Comment by sdnts** [comment]
@LaughlinJames Are you still seeing this?

**Comment by sivcan** [comment]
Closing this.
If the issue still persists, feel free to reopen it.
