### ISSUE TITLE
Postman native for Linux does not connect (for sync) through proxy

### ISSUE THREAD

**Issue by felipeaf** [a85/POSTMan-Chrome-Extension#3979]
Hello! 
My Postman Native for Linux is unable to connect to cloud through authenticated corporate proxy at all. Even the browsers are working with system proxy configuration.

The proxy is authenticated. I've had the same results configuring though Ubuntu GUI or though environment variables (HTTP_PROXY, HTTPS_PROXY, like http://user:pass@ip:port/ where user, pass, ip and port are the correct values for me, working in Windows and browser). 

My browsers are working, but they always ask for password (even when the password is in HTTP_PROXY variable).

The button in settings for use system proxy is ON.

I can even sign up or sign in, by google or directly. I ask for network manager and had a partial unblock to direct connections and i could connect without proxy, but, since i cannot continue with no proxy, i cannot sync since, it shows always like offline.

## App Details:
Postman for Linux
Version 5.5.0
linux 4.13.0-19-generic / x64 

Ubuntu 17.10

## Issue Report:

 1. Did you encounter this recently, or has this bug always been there:
I had installed Linux just this week in my work machine, and i am with this issue since i did this. I have windows installed here yet, and in windows works, besides the proxy configuration is the same.

 2. Expected behaviour:
Works though proxy when proxy is configured. When configured through Ubuntu Configuration GUI, it should ask by authentication, like browsers do, but if HTTP_PROXY has an username and password, i guess it should just works.

 3. Console logs 

In developer tools console, i have the following error:

```
Failed to load resource: the server responded with a status of 407 (Proxy Authentication Required)
https://dl.pstmn.io/changelog?channel=stable&platform=linux&to=5.5.0 Failed to load resource: net::ERR_TUNNEL_CONNECTION_FAILED
requester.html:1 Uncaught (in promise) TypeError: Failed to fetch
https://app.getpostman.com/api/app_broadcasts?user_id=0&access_token=&count=10&app_version=5.5.0&app_platform=electron Failed to load resource: the server responded with a status of 407 (Proxy Authentication Required)
https://app.getpostman.com/api/app_broadcasts?user_id=0&access_token=&count=10&app_version=5.5.0&app_platform=electron Failed to load resource: net::ERR_TUNNEL_CONNECTION_FAILED
requester.html:1 Uncaught (in promise) TypeError: Failed to fetch
https://dl.pstmn.io/update/status?channel=stable&currentVersion=5.5.0&arch=64&platform=linux Failed to load resource: the server responded with a status of 407 (Proxy Authentication Required)
https://dl.pstmn.io/update/status?channel=stable&currentVersion=5.5.0&arch=64&platform=linux Failed to load resource: net::ERR_TUNNEL_CONNECTION_FAILED
requester.html:1 Uncaught (in promise) TypeError: Failed to fetch
requester.js:242093 You tried to return focus to null but it is not in the DOM anymore
exports.returnFocus @ requester.js:242093
https://app.getpostman.com/api/signin Failed to load resource: the server responded with a status of 407 (Proxy Authentication Required)
https://app.getpostman.com/api/signin Failed to load resource: net::ERR_TUNNEL_CONNECTION_FAILED
requester.html:1 Uncaught (in promise) TypeError: Failed to fetch
https://analytics.getpostman.com/events Failed to load resource: the server responded with a status of 407 (Proxy Authentication Required)
https://analytics.getpostman.com/events Failed to load resource: net::ERR_TUNNEL_CONNECTION_FAILED
requester.html:1 Uncaught (in promise) TypeError: Failed to fetch
```

previously had login:

```
https://app.getpostman.com/api/users/1687963/app_bootstrap?user_id=1687963&…c03c63feaf1a03948c02b5b1dede6278034e&app_version=5.5.0&app_target=electron 
Failed to load resource: the server responded with a status of 407 (Proxy Authentication Required)
https://app.getpostman.com/api/users/1687963/app_bootstrap?user_id=1687963&…c03c63feaf1a03948c02b5b1dede6278034e&app_version=5.5.0&app_target=electron Failed to load resource: net::ERR_TUNNEL_CONNECTION_FAILED
https://dl.pstmn.io/changelog?channel=stable&platform=linux&to=5.5.0 Failed to load resource: the server responded with a status of 407 (Proxy Authentication Required)
https://dl.pstmn.io/changelog?channel=stable&platform=linux&to=5.5.0 Failed to load resource: net::ERR_TUNNEL_CONNECTION_FAILED
requester.html:1 Uncaught (in promise) TypeError: Failed to fetch
requester.html:1 Uncaught (in promise) TypeError: Failed to fetch
https://app.getpostman.com/api/app_broadcasts?user_id=1687963&access_token=…a03948c02b5b1dede6278034e&count=10&app_version=5.5.0&app_platform=electron Failed to load resource: the server responded with a status of 407 (Proxy Authentication Required)
https://app.getpostman.com/api/app_broadcasts?user_id=1687963&access_token=…a03948c02b5b1dede6278034e&count=10&app_version=5.5.0&app_platform=electron Failed to load resource: net::ERR_TUNNEL_CONNECTION_FAILED
requester.html:1 Uncaught (in promise) TypeError: Failed to fetch
https://dl.pstmn.io/update/status?channel=stable&currentVersion=5.5.0&arch=64&platform=linux Failed to load resource: the server responded with a status of 407 (Proxy Authentication Required)
https://dl.pstmn.io/update/status?channel=stable&currentVersion=5.5.0&arch=64&platform=linux Failed to load resource: net::ERR_TUNNEL_CONNECTION_FAILED
requester.html:1 Uncaught (in promise) TypeError: Failed to fetch
```

**Comment by sdnts** [comment]
Hi @felipeaf, thanks for reporting this. This is a known issue since most corporate proxies do not allow WebSocket communication, which is how our Sync service currently works.
Please reopen this if your proxy does allow websockets, but it still doesn't work. I'm closing this for now :)

**Comment by felipeaf** [comment]
Hi @madebysid! I can assure you that our corporate proxy supports WebSocket Communication and this is a OS specific bug.

I have dual boot in this computer. In Windows, with the same proxy configuration, Postman works fine. Most time i can only use proxy (other connections to internet are blocked), and postman  sync always works on windows.

The same machine, the same proxy server, works in windows but not in Linux.

**Comment by iamavieira** [comment]
Hey @felipeaf !

I ran into the same problem within native application.

What I thought was if the internet connection in the browser is working, maybe the deprecated google extension of postman might too.

So it does! try it out and let me know.
