### ISSUE TITLE
Packaged app: OAuth 1.0 signature method fields have to be a select box.

### ISSUE THREAD

**Issue by eerien** [a85/POSTMan-Chrome-Extension#398]
In OAuth 1.0, the signature method candidates are only HMAC-SHA1, RSA-SHA1, PLAINTEXT.

It's good to me if the fields filled as HMAC-SHA1, the popular signature method.
POSTMan packaged app is not filled the field as HMAC-SHA1, differ from ordinary POSTMan extension.

It better if the fields to be a select box with the three available methods.

**Comment by firoz942** [comment]
HMAC-SHA1 is same as RSA-SHA1?, bcoz i want to hit API of MasterCard in which it supports only OAUTH with RSA-SHA1 signature method, im facing this issue form last 3 days, can you help me..
