### ISSUE TITLE
Unable to resolve variable in Pre-request Script 

### ISSUE THREAD

**Issue by alewmt** [a85/POSTMan-Chrome-Extension#3980]
Variable is not resolved in pre-request script

## App Details:
```
Postman for Windows
Version 5.4.1, 5.5.0
win32 10.0.15063 / x64
```

## Issue Report:
 1. This issue appears when I updated postman to the latest version. Version 5.4.1 has the same problem.

![image](https://user-images.githubusercontent.com/9164890/34065218-dde4eb3e-e210-11e7-856b-d246aa918071.png)

**Comment by harryi3t** [comment]
@alewmt  variable resolution is not supported for request sent through `pm.sendRequest`
For more information check this thread https://github.com/postmanlabs/postman-app-support/issues/3929
