### ISSUE TITLE
How verify empty array

### ISSUE THREAD

**Issue by Kathy87** [a85/POSTMan-Chrome-Extension#3981]
I have response json as below:
{
    "data": [],
    "included": [],
    "meta": {
        "totalRows": 0
    }
}
I want to verify array data is empty. How can i verify it?
I try $.[?(@.data.length()>0)].id but error is "There is no marching node for JsonPath: $.[?(@.data.length()>0)].id'"

Please help. Thanks
Kathy

**Comment by deepakpathania-zz** [comment]
Hey @Kathy87, if I understand the issue correctly, you're simply trying to verify that an array in your response body is empty using a test script. If that is indeed the case, then you can do this by using the `pm.*` API like this: 
```javascript
pm.test("Data array is empty", function () {
    var jsonData = pm.response.json();
    pm.expect(jsonData.data.length).to.eql(0);
});
```
You might have to modify the content of `pm.expect` if your returned data is wrapped around something else, so for example if your data is something like
```json
{
    "content": {
        "data": [],
        "included": [],
        "meta": {
            "totalRows": 0
        }
    }
}
```
you'd have to change it to `pm.expect(jsonData.content.data.length).to.eql(0);`. 
I hope this helps. Feel free to reach out in case you have any additional querries.

**Comment by sdnts** [comment]
Closing this. Please feel free to reopen if the above suggestion does not work for you :)

**Comment by harryblam** [comment]
For visibility for future onlookers, I've used the updated syntax below to verify empty arrays (which I got from the [test examples here](https://learning.postman.com/docs/postman/scripts/test-examples/)). I think this reads a bit nicer!

`pm.expect(content.arrayData).to.be.an('array').that.is.not.empty;`

**Comment by abeward** [comment]
> For visibility for future onlookers, I've used the updated syntax below to verify empty arrays (which I got from the [test examples here](https://learning.postman.com/docs/postman/scripts/test-examples/)). I think this reads a bit nicer!
> 
> `pm.expect(content.arrayData).to.be.an('array').that.is.not.empty;`

Thank you. This worked for me.

Adding that the sample response for this example might look something like this:
```
{
    arrayData: [1,2,3]
}
```

Adding that .length checks on an assertion has never worked for me since about 2020. It often returns a success when it should fail and no error messages. I sure hope people are testing their tests.
