### ISSUE TITLE
Collection variable not present in autocomplete

### ISSUE THREAD

**Issue by rameshsubramanian87** [a85/POSTMan-Chrome-Extension#3982]
## App Details:

```
Postman for Mac
Version 5.5.0
OS X 10.12.6 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:
 Yes, but this is my first attempt at using the collection variable feature

 2. Expected behavior:
The collection variable is accessible in the collection to use.

 3. Console logs 
NA

 4. Screenshots (if applicable)
I declared a collection variable & clicked update.
![postman_collection_ variable_2017-12-15 22-53-18](https://user-images.githubusercontent.com/27235944/34068151-da3be4a8-e1eb-11e7-8b49-e3b9c6d75bd8.png)

but when I try to use the variable it isn't available in the list of available variables.
![postman_variable_notfound_2017-12-15 22-55-14](https://user-images.githubusercontent.com/27235944/34068186-0895a12c-e1ec-11e7-92c9-46fa46e9e0d5.png)

**Comment by rameshsubramanian87** [comment]
On further review, it looks like more of a UI issue as it shows the variable as unresolvable in the collection, but I can use the variable.

**Comment by prashantagarwal** [comment]
@rameshsubramanian87 Yes, we will soon be making these variables available in autocomplete.

**Comment by prashantagarwal** [comment]
@rameshsubramanian87 Collection variables are now available in autocomplete and are also highlighted. Thanks
