### ISSUE TITLE
Collection level basic authorization not working

### ISSUE THREAD

**Issue by rameshsubramanian87** [a85/POSTMan-Chrome-Extension#3983]
## App Details:

```
Postman for Mac
Version 5.5.0
OS X 10.12.6 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:
Yes, but this is my first attempt at using the collection level authorization.

 2. Expected behavior:
The basic auth defined on a collection level works in the collection.

 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
N/A

 4. Screenshots (if applicable)
N/A

Step to reproduce the issue:

1. Create a new collection.
2. Create a collection level basic authorization
3. Create a request to send with auth type as 'Inherit auth from parent'.
4. send the request, but the request fails due to authorization error.

**Comment by a85** [comment]
Seems to be working fine. Can you test this with postman-echo.com?

**Comment by rameshsubramanian87** [comment]
@a85 looks like this is working. I stored the credentials in variables & there seems to have been a typo. I am closing the ticket.

Thanks for taking a look!
