### ISSUE TITLE
Postman Collections Gone or disorganized

### ISSUE THREAD

**Issue by i-bartolome** [a85/POSTMan-Chrome-Extension#3984]
## App Details:

Postman for Windows
Version 5.5.0
win32 10.0.10586 / x64

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there: I just restarted my PC and most of my collections were gone, or disorganized.
 2. Expected behaviour: I want to get my collections back

How could I get my collections back?

**Comment by sdnts** [comment]
Hi @i-bartolome, I'm sorry to hear that you're having problems.
Do you use Sync? If yes, all your collections should be intact. Can you head over to your dashboard `https://app.getpostman.com/library/collections` and check if you see your collections there? If yes, signing out + in should bring all collections back.

If you do not use Sync, all your collections remain local to your machine. Did you or any program alter the directory where Postman stores it's data?
