### ISSUE TITLE
how to see request headers after making a get/post call?

### ISSUE THREAD

**Issue by cyth319** [a85/POSTMan-Chrome-Extension#3986]
postman only shows response headers after making a request. but i also want to see request headers? is there a way for it? I did what this [SF](https://stackoverflow.com/questions/33793629/postman-how-to-see-request-with-headers-and-body-data-with-variables-substitut) question is sayin, however no magic "response headers" section appeared in Builder

i know this place is not for questions but please help.

**Comment by sdnts** [comment]
Hi @cyth319, the headers you add to the Headers section in the request are the ones that are sent. You can also open up the Postman Console (Cmd/Ctrl + Alt + C) if you're on the native apps too see these. 
Please reopen if this does not work for you :)

**Comment by cyth319** [comment]
@madebysid opening up the console worked for me, thanks. however i think we should be able to see request headers in the builder. For example in this case, i did not write any Headers but console showed me   that postman sent  8 request headers. one of them was "referrer" which was the cause of my problem
