### ISSUE TITLE
Duplicating and moving requests causes postman to hang indefinitely

### ISSUE THREAD

**Issue by chrisron95** [a85/POSTMan-Chrome-Extension#3987]
## App Details:

```
Postman for Mac
Version 5.5.0
OS X 10.13.3 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:
It has gotten more and more prevalent over the past few months 
 2. Expected behaviour:
Duplicating and/or moving requests should, you know, work as you would expect with no problems.

Duplicating and/or moving calls, especially (but not exclusively) when between collections, causes sync conflicts right away. I duplicated, moved, and renamed 11 calls from one collection to another, and postman has been frozen for the past hour and a half at least. It randomly pops up with sync conflicts, but the app is still frozen so I can't click resolve, but the box just disappears after a little while anyway. The entire time it is syncing, but my processes on my Mac says Postman is using anywhere between 200% and 400% of my processes, and _*a lot*_ of my RAM. I have tried quitting and reopening the app, and it just made things worse: all of a sudden certain calls disappeared, and I can't even do anything about this until it finishes. I wish I could say this is the first time it's happening, but this happens any time I try to duplicate/move calls.

This is a similar (but not identical) issue to #3776, #3914, and #3504 (which I have commented on)

**Comment by chrisron95** [comment]
Also a side note, it took 3 hours to unfreeze, and the calls I mentioned before are gone and won't recover. I even tried recovering all the way back to Friday. Nothing. I click the recover button and it flashes to "recovering" briefly then just goes back to saying "recover" and does absolutely nothing. Now I have to rewrite all of the tests and everything that I wrote for them, because I can't seem to get it back.

**Comment by sdnts** [comment]
Hi @chrisron95, do you see any errors in the DevTools console when this happens? Also, does this happen for all collections you have? How many collections / folders / requests do you have?

We're also working on a bunch of improvements for the underlying layer responsible for working with collections, which I suppose should solve this issue. This is aimed to hit production with v5.6 (next release)

**Comment by vdcardenas** [comment]
Hi, I have the same problem with a Postman collection that has more than 500 requests. Importing it, copying folders and working and copy with it is directly impossible.

Attached collection without corporate data.

[Drakkar.Transfers.Quote.postman_collection.zip](https://github.com/postmanlabs/postman-app-support/files/1710586/Drakkar.Transfers.Quote.postman_collection.zip)

**Comment by kamalaknn** [comment]
Hi @chrisron95 @vdcardenas 

We've been working on some major improvements to our internal data storage layers in the app. Could you update your app to the latest version (6.0.9 or higher) and verify this?

**Comment by chrisron95** [comment]
Since updating to 6.0.9 the problem seems to be resolved

**Comment by kamalaknn** [comment]
Thanks @chrisron95 

Glad to hear that!
