### ISSUE TITLE
text gets truncated at # in value string

### ISSUE THREAD

**Issue by ghost** [a85/POSTMan-Chrome-Extension#3988]
```
Postman for Mac
Version 5.5.0 (5.5.0)
macOS 10.13.2 (17C88)
```

## Issue Report:
I want to send a GET with following param
query=ASK WHERE {<https://id.milieuinfo.be/imjv/observatie/6808/em/8/obs/9/2011#id> ?p ?v.}

However this text gets truncated at the # in the url.

**Comment by sdnts** [comment]
Hi @PaulZH, could you provide a GIF or something? I'm unable to correctly understand what you're trying to do. Thanks!

**Comment by ghost** [comment]
<img width="1646" alt="screen shot 2017-12-20 at 15 31 58" src="https://user-images.githubusercontent.com/437781/34211935-f792f05c-e59a-11e7-9031-ae2c0130d632.png">

I need to input a # in the url (the key in the database (triple store)). However I cannot get past it. What comes at that position is thrown away.

**Comment by sivcan** [comment]
Hi @PaulZH - I can confirm that this is a bug. 
We'll look into it further.

**Comment by codenirvana** [comment]
Hi @PaulZH, `#` has a special meaning in clients but not to the server, so the server strips it off and ignores it.

To solve this just replace `#` with its encoded value `%23`. In your case, something like `query=ASK WHERE {https://id.milieuinfo.be/imjv/observatie/6808/em/8/obs/9/2011%23id ?p ?v.}`

I tried to send `#` as-is in cUrl and other browsers and I had to replace it with `%23` even in those places to get it working.

**Comment by shamasis** [comment]
I also observed that the data editor does some magic ;-) of stripping `#` from the query param editor and trim it to URL. Maybe we could assist setting some encoding there - but that might be tricky as pre-encoded inputs will get tripped off. However, the intelligent encoding module that @SamvelRaja worked on can handle that situation as well.
