### ISSUE TITLE
Electron app automatically adds "=" to the end of URL, Chrome app does not

### ISSUE THREAD

**Issue by wywywywy** [a85/POSTMan-Chrome-Extension#3991]
Hi all,

Basically I am trying to interface with a 3rd party CGI API, and the URL endpoint looks like this -

http://localhost:9999/cgi-bin/api?service

Notice that the query string is non-standard.

It all works fine in the Chrome app.

But in the Electron app, it automatically adds a "=" to the end of the URL, making it http://localhost:9999/cgi-bin/api?service=

And the CGI API refuses to process it because as far as it's concerned, "service=" is not the same as "service".

It does not show the "=" in the GUI anywhere at all.  I only found out when looking at the IIS log.

So is there any way to disable this please?

Thanks.

**Comment by harryi3t** [comment]
@wywywywy Thank for reporting this bug.
This is a known bug and the fix is already in progress.
You can expect this to work in the next version :)

**Comment by wywywywy** [comment]
Thanks for the update.

Any ETA? :D

**Comment by numaanashraf** [comment]
This issue is fixed and verified in Postman v.6.1.4
