### ISSUE TITLE
can't login, again 

### ISSUE THREAD

**Issue by unifreak** [a85/POSTMan-Chrome-Extension#3993]
see #3866 . I don't know how to reopen an issue, so have to open a new one.

**Comment by unifreak** [comment]
Please let me know if your auth service is back running normally. for now I'll just to revert back to older version which can let me access my collection without signing in.

**Comment by a85** [comment]
Please email help@getpostman.com with your credentials and we'll help out.

**Comment by unifreak** [comment]
@a85 sent. I'm wondering why I'm encountering this problem. Seems you guys know the cause.

**Comment by birbird** [comment]
have this issue too.

requester.js:68011 POST https://app.getpostman.com/api/signin net::ERR_INSECURE_RESPONSE
request @ requester.js:68011
signInUser @ requester.js:188694
handleSignInSubmit @ requester.js:422636
handleSelectItem @ requester.js:9363
callback @ requester.js:11051
_fireCallback @ requester.js:133727
Mousetrap.self._handleKey @ requester.js:133788
Mousetrap.handleKey @ requester.js:134105
_handleKeyEvent @ requester.js:133848
wrapped @ requester.js:271985
requester.js:68011 POST https://analytics.getpostman.com/events net::ERR_INSECURE_RESPONSE
request @ requester.js:68011
sendRequest @ requester.js:188516
sendPayloads @ requester.js:188500
(anonymous) @ requester.js:188247
requester.js:67998 Uncaught (in promise) Object {error: TypeError: Failed to fetch, status: 0}
(anonymous) @ requester.js:67998

All https request fail
