### ISSUE TITLE
UTF-8 characters not being displayed correctly in the response status message

### ISSUE THREAD

**Issue by mohammad6006** [a85/POSTMan-Chrome-Extension#3995]
## App Details:

```
Postman for Windows
Version  v5.5.0
Windows 10 x32
```

## Issue Report:

status message not support utf-8 and I cant copy message to encode it
![image](https://user-images.githubusercontent.com/553379/34198937-434beca2-e581-11e7-95d2-8692649e7440.png)

**Comment by sivcan** [comment]
@mohammad6006 - Can you tell me how you're producing that custom status message? 
The steps that we can follow to reproduce this error.

**Comment by mohammad6006** [comment]
@sivcan I user Laravel and return response like this
```
            return (new Response)->setStatusCode(465, $errorString);
```

**Comment by appurva21** [comment]
@mohammad6006 We are not able to reproduce this issue in v7.0.7 If you are still facing this issue in the latest version, please leave a comment here with exact steps to reproduce the issue.

**Comment by mohammad6006** [comment]
@appurva21 

my code in Laravel Controller:

![image](https://user-images.githubusercontent.com/553379/55720547-5d250b80-5a16-11e9-9483-51e3a37ad88e.png)

`
return (new Response)->setStatusCode(465, 'English Türkçe العربية فارسی');
`

and response in v7.0.7

![image](https://user-images.githubusercontent.com/553379/55720631-88a7f600-5a16-11e9-8c25-97ff5d90c64c.png)

I can copy the message text now

but I think header status message doesn't support UTF-8 languages

**Comment by coditva** [comment]
This is reproducible:
![image](https://user-images.githubusercontent.com/8445768/76861514-b92d1c80-6882-11ea-964d-e54c9fb7fcad.png)

The actual status line sent (observed from wireshark):
```
[HTTP/1.1 204 English T\303\274rk\303\247e \330\247\331\204\330\271\330\261\330\250\331\212\330\251 \331\201\330\247\330\261\330\263\333\214\r\n]
```
