### ISSUE TITLE
Self-signed certificate breaks OAuth2 authorization in standalone Postman app

### ISSUE THREAD

**Issue by ghost** [a85/POSTMan-Chrome-Extension#3996]
## App Details:

```
Postman for Linux
Version 5.5.0
linux 4.9.0-4-amd64 / x64
```

## Issue Report:

We use self-signed certificates for development purpose. These certificates break the OAuth2 authorization in the standalone Postman app: Requesting a new OAuth2 token opens a new window, but the window is empty. Disabling SSL certificate verification (Settings > General) or adding an client certificate (Settings > Certificates) does not affect OAuth2 authorization. The legacy Postman Chrome Extension works fine as it allows to add an exception for the self-signed certificate.

We would expect that the standalone Postman app respects the certificate settings (SSL certificate verification and client certificates) also for the OAuth2 authorization.

**Comment by sivcan** [comment]
@hodjo - Thanks for reporting this. We'll look into this.

**Comment by lucamaf** [comment]
same here

**Comment by andutta** [comment]
Facing the same issue, any resolution ?

**Comment by zihotki** [comment]
Duplicate of [https://github.com/postmanlabs/postman-app-support/issues/2918](https://github.com/postmanlabs/postman-app-support/issues/2918 )

**Comment by sivcan** [comment]
Closing duplicate issue.
