### ISSUE TITLE
Change behavior of escape key-press in Collection Edit pop-up

### ISSUE THREAD

**Issue by jooleeanh** [a85/POSTMan-Chrome-Extension#3998]
## App Details:
```
Postman for Mac
Version 5.5.0
OS X 10.12.6 
```

#### Change behavior of `escape` key-press in Collection Edit pop-up

I keep and edit a lot of code in my collection pre-request and test scripts since that's the only way of creating functions available in the whole collection (ref #882: [Reusing pre-request scripts across requests in a collection](https://github.com/postmanlabs/postman-app-support/issues/882#issuecomment-278759032)).

Since the editor in this pop-up is often suggesting environment and global variables, I often press escape with the intent of canceling the auto-completion. However, escape just closes the pop-up without prompting. All the code edits are gone !

I think that the behavior should be:
```
if (there is an auto-complete suggestion) {
  `escape` should dismiss it;
} else if (there are changes in any of the tabs) {
  `escape` should prompt to save, discard, or cancel (keep pop-up open);
} else {
  `escape` should close without prompt;
}
```

**Comment by a85** [comment]
Thanks for the feedback @jooleeanh. Collection and folder editing is moving out of a modal and coming into tabs pretty soon. This way they would abide by the dirty/non-dirty tab rules and code edits will remain.

**Comment by tobiashochguertel** [comment]
Is there some news about the ESC Button?

**Comment by vkaegis** [comment]
@jooleeanh @tobiashochguertel This should be fixed now, closing this issue. We've disabled the Esc shortcut to dismiss. As @a85 mentioned, workflows around authoring / editing collections and folders will become much cleaner once they're in tabs. Feel free to open another issue if you have more feedback around this.
