### ISSUE TITLE
401 Unauthorized when sending OAuth1 request - cannot disable url-encoding of OAuth Signature in headers

### ISSUE THREAD

**Issue by zcramos** [a85/POSTMan-Chrome-Extension#3999]
## App Details:

```
Postman for Mac
Version 5.5.0
OS X 17.3.0 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there: Recently, I think this UI change was in 5.5.0 but I'm not certain.
 2. Expected behaviour: Application should allow me to toggle URL-Encoding of the OAuth Signature
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 4. Screenshots (if applicable)

In the Postman for Chrome app, there are several options when you select OAuth1 security, including a toggle for "Encode OAuth Signature".
![Encode OAuth Signature](https://i.imgur.com/5ccPjjY.png "Encode OAuth Signature")

In the latest version of the desktop app, those options have been replaced with a drop down which only allows the user to select whether the authorization data should go in the url or in the headers. 
![Drop Downs](https://i.imgur.com/EwYbxgZ.png "Drop Downs")

The service I am consuming evidently only supports authentication with the oauth data not encoded and in the header. I consistently receive the following message with any other OAuth1 configuration: 
```
401 - You Are Not Authorised
Reason: Invalid signature for signature method HMAC-SHA1
```

Honestly I'm not entirely sure why they have this issue, but I spent almost 2 hours banging my head on my desk this morning before I decided to try the Chrome App, and thank goodness it hasn't been updated to match the desktop version.

**Comment by sdnts** [comment]
@zcramos Thanks for reporting this. @kamalaknn @harryi3t Can you guys look into this please?

**Comment by TuomasKiviaho** [comment]
Can this be related. After the update I'm getting sometimes `oauth_token="true"` as authentication or then the Preview Request doesn't produce Authentication header at all. This is somehow OAuth1 related because the other authentication methods do respond in to the button.

**Comment by pintoko** [comment]
i also got this issue, i got invalid signature when i empty access token and token secret.

but when i fill the access token and token secret, postman generate the signature correctly

my postman version is
Postman for Mac
Version 6.0.10
OS X 15.2.0 / x64

could you help me?

**Comment by menpablo** [comment]
Same Issue here.

**Comment by cfretty** [comment]
We have run into this issue as well
Postman for windows v6.1.3

Now that Chrome app is being deprecated, this is going to be a big issue for my team.

**Comment by bryannliu** [comment]
I have the same issue Version 6.1.3 (6.1.3)  MacOS Sierra 10.12.6 (16G1408).

**Comment by Sergeyp52** [comment]
Same issue here with Version 6.1.4 on Win10 Ent.

Sending the request will cause the Authorization header to appear but in the following manner:
`OAuth oauth_consumer_key="true",oauth_token="true",oauth_signature_method="HMAC-SHA1"...`

The end result will be 401 Unauthorized although the same request works great on the Chrome extension.

Choosing "Inherit" and manually filling out the authorization will also work.

As far as I'm aware nothing special happened between the time it worked and the time it stopped working.

**Comment by orgabor** [comment]
same issue here with 6.2.5  win10 x64

**Comment by max-schulkin** [comment]
same issue with postman version 6.4.2 on macOS High Sierra 10.13.6

**Comment by SemyenSoldatenko** [comment]
* `https://....my-host.../path?a=a-b` - Works
* `https://....my-host.../path?a=a+b` - Invalid signature
* `https://....my-host.../path?a=a%2Bb` - Invalid signature

Postman Version 7.20.0 (7.20.0)
macOS Catalina Version 10.15.3 (19D76)

**Comment by vikiCoder** [comment]
Hi everyone,

We have added an option to enable/disable URL encoding of Authorization header in OAuth1 (See the screenshot below). This option is available when `Request Headers` is selected in `Add authorization data` field. 

It is out in the latest [Postman canary (v7.21.0-canary01)](https://www.postman.com/downloads/canary). Soon, it will be out in the next release of the Postman app (v7.21).

![image](https://user-images.githubusercontent.com/16588032/76386044-5bcc3380-6389-11ea-9c0f-a4f8a777c73a.png)

**Comment by vikiCoder** [comment]
The changes mentioned in my [previous comment](https://github.com/postmanlabs/postman-app-support/issues/3999#issuecomment-597455150) are out in the latest version of the Postman app (v7.21.0).
