### ISSUE TITLE
Environment Variables only store unix style line endings

### ISSUE THREAD

**Issue by kbuzby** [a85/POSTMan-Chrome-Extension#4000]
## App Details:

```
Postman for Windows
Version 5.5.0
win32 10.0.15063 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there: Recently
 2. Expected behaviour: Allow raw strings in environment variables.

When trying to enter a multi-line value for an environment variable the line endings are unix style (only \n). However, in the scenario we are testing the response from our API is giving windows style (\r\n), so we're not able to directly compare the response and a stored environment variable.

We're also not able to store raw white space characters in the environment variable values because the backslashes are escaped.

For now we are able to work around by stripping carriage returns from the response we are validating.

This issue seems similar to #3613 and it seems like it would be a useful feature to be able to indicate that you would like raw text to be stored and not encoded / processed in any way.

**Comment by sdnts** [comment]
@kbuzby Thanks for reporting this :) We're working on a better way to allow users to handle data like this in the app, which should make it explicit what is actually being stored in the environment variables. We will look into this then.

**Comment by prashantagarwal** [comment]
Related to #4179
