### ISSUE TITLE
[Bug] Postman doesn't forward the right method when  receiving a 301

### ISSUE THREAD

**Issue by n-dragon** [a85/POSTMan-Chrome-Extension#4001]
## App Details:
```
Postman for Windows
Version 5.1.3
win32 10.0.15063 / x64
```

## Issue Report:
 0. we encountered this issue recently but seems to have always been here

1. create a  request http endpoint A to return 301 with a location X in the header
example from putsrequest.com 
```
response.status=301;
response.headers['Location'] ='endpoint B';
```
2. create another http endpoint  B with location header X set to the value you put above in the header
3. request endpoint A with a POST request
3.1 Postman automatically processes the 301 and forward to the new endpoint defined in Location header
4. request endpoint B receives a GET request instead of a POST 

## Example with putsrequest:

endpoint A :  [here](http://putsreq.com/l7M124kd1gk5o2FkL4zP/inspect)
endpoint B :  [here](http://putsreq.com/J2QhX0kdLXB8h3e44Sof/inspect)

**Comment by thecuriousdev** [comment]
@NicolasDragon thanks for reporting this issue! we'll look into this, meanwhile can you try updating the postman app, and see whether the issue is still occurring for you?

**Comment by n-dragon** [comment]
still occuring with :
```
Postman for Windows
Version 5.5.0
win32 10.0.14393 / x64
```

**Comment by sdnts** [comment]
@NicolasDragon Currently, when a 301 redirect happens, method is changed to a GET (and the request body is stripped). Although the RFC does not enforce this, we emulate browsers, that do this. We will look into this soon.

**Comment by n-dragon** [comment]
ok nice!
just for info, I saw that in the rfc 2616
```
 If the 301 status code is received in response to a request other
   than GET or HEAD, the user agent MUST NOT automatically redirect the
   request unless it can be confirmed by the user, since this might
   change the conditions under which the request was issued.

      Note: When automatically redirecting a POST request after
      receiving a 301 status code, some existing HTTP/1.0 user agents
      will erroneously change it into a GET request.
```

I don't understand when you say 'we emulate browsers'

**Comment by dadvir** [comment]
Can we reopen this? i don't understand why you strip the body and change the method in this scenario? I'm using the Mac app btw.

**Comment by athe0i** [comment]
MacOS, Postman  v6.2.3, after 302 redirects method resets to GET.

**Comment by dadvir** [comment]
Probably happens on all platforms, it’s a bug in design. 
I suggest to (at least) show a warning.

**Comment by shamasis** [comment]
Yes. @dadvir you are right on target. This is the behaviour implemented wrongly by most clients (browsers) since the beginning of time. :-( Owing to the primary nature of API used via browsers from when we started, this design (or bug in design) had to be retained.

Showing 3xx information and such warnings would be great and maybe even options to ignore these by introducing settings.

Note: runtime needs to bubble 3xx information as they happen

**Comment by fractalix** [comment]
Is there any update regarding this issue? I tested Postman 7.0.9 on linux. I have tested with chrome and firefox on win,lin and mac and they keep the method (POST) on the redirection, so Postman should do it also.

**Comment by dellagustin** [comment]
Me and a colleague lost today at least, together, 4 hours of work because of this issue.
In special, when looking at the "Postman Console" 
Please add some means to make it transparent to the user that the method was changed when following the redirect.

**Comment by xzhiwei** [comment]
version 7.3.4 also have this problem ,  can return 301 body to user.
Please do something to user , let them know reason.

**Comment by codenirvana** [comment]
Hello everyone 👋
It took us a while but, we are currently adding support for request configurations which will allow you to configure request sending flows like this (following the original HTTP method on redirect).

Will post about its availability in our canary and stable channel soon!

**Comment by dholde** [comment]
> Me and a colleague lost today at least, together, 4 hours of work because of this issue.
> In special, when looking at the "Postman Console"
> Please add some means to make it transparent to the user that the method was changed when following the redirect.

Same here

**Comment by codenirvana** [comment]
As mentioned in https://github.com/postmanlabs/postman-app-support/issues/4001#issuecomment-515807857, We've added support for Request Level Configurations in the latest version of the Postman App (v7.7.2).

You can turn `Follow original HTTP Method` configuration ON to redirect with the original HTTP method.

<img width="943" alt="Screenshot 2019-09-17 at 12 48 23 PM" src="https://user-images.githubusercontent.com/4865836/65019870-b12f0700-d949-11e9-9694-0cff74bd485d.png">

We'll be adding support for the folder and collection-level configurations soon!

**Comment by amonyaos** [comment]
@codenirvana   POST body lost

![image](https://user-images.githubusercontent.com/12334944/68229040-72582c00-0031-11ea-8165-74bbb3376166.png)
Postman v7.10.0



POST /tsk1r2/oauth/token HTTP/1.1
Content-Type: application/x-www-form-urlencoded
User-Agent: PostmanRuntime/7.19.0
Accept: */*
Cache-Control: no-cache
Postman-Token: 5b1fdf27-d50c-4d6b-82f3-92479724acf9
Host: test1.mdomain.com
Accept-Encoding: gzip, deflate
Content-Length: 146
Connection: keep-alive

grant_type=client_credentials&scope=all&client_id=mengyao&client_secret=7B792ECB0D527AE9C51946CF62D18B94&redirect_uri=&email=mengyao%40mdomain.com


HTTP/1.1 302 Moved Temporarily
Date: Tue, 05 Nov 2019 16:54:37 GMT
Content-Type: text/html
Content-Length: 154
Connection: keep-alive
Location: http://test2.mdomain.com/tsk/oauth/token

<html>
<head><title>302 Found</title></head>
<body bgcolor="white">
<center><h1>302 Found</h1></center>
<hr><center>nginx</center>
</body>
</html>





POST /tsk/oauth/token HTTP/1.1
User-Agent: PostmanRuntime/7.19.0
Accept: */*
Cache-Control: no-cache
Postman-Token: 5b1fdf27-d50c-4d6b-82f3-92479724acf9
Accept-Encoding: gzip, deflate
Referer: http://test1.mdomain.com/tsk1r2/oauth/token
Host: test2.mdomain.com
Content-Length: 0
Connection: keep-alive




HTTP/1.1 200 OK
Date: Tue, 05 Nov 2019 16:54:37 GMT
Content-Type: application/json; charset=utf-8
Content-Length: 163
Connection: keep-alive

{
  "status": {
    "errno": 400,
    "code": "invalid_request",
    "message": "Invalid request: header & content must be application/x-www-form-urlencoded"
  }
}

**Comment by nikprix** [comment]
I have just bumped into this with Postman Version 7.13.0 on Windows.
Enabling 'Follow original HTTP Method' fixed it for me :)
