### ISSUE TITLE
Collection runner don't executes few requests

### ISSUE THREAD

**Issue by tanguc** [a85/POSTMan-Chrome-Extension#4004]
Version 5.5.0 (5.5.0)

Postman for Mac
OS X 10.13.2 (17C88)

## Issue Report:

 1. Did you encounter this recently, or has this bug always been there:
Recent - My actual collection is composed of 80 requests, however during the collection runner few requests of my initial collection are not ran. It's always the same kind of requests that are not ran during the runner, however usually it's the same type of request where issues coming from : PUT requests. I've already tried to duplicate collection and to run over again but neither works.

 2. Expected behaviour:
All requests from collection should be executed during the collection runner.

**Comment by sdnts** [comment]
Hi @tanguc can you confirm for me that there aren't any `setNextRequest`s in your collection? This usually causes the jumps that you're seeing.
If the same requests are skipped every time, it also points to an error like this.

**Comment by tanguc** [comment]
Hi @madebysid yes you're right, I've completely missed this point, thanks !
