### ISSUE TITLE
Portable version requirement

### ISSUE THREAD

**Issue by sfragrance** [a85/POSTMan-Chrome-Extension#4006]
In some professional environments there is no possibilities to install software using the standard "setup.exe", due to policy restrictions.
And, many people **HATE** installation.
When are'you going to propose a portable Postman ?

**Comment by prashantagarwal** [comment]
@gragrance Thanks for suggesting this.

**Comment by ripfire44** [comment]
+1
I was looking for this also.

**Comment by kmteam** [comment]
+1 
We're also very interested on portable version of Postman!

**Comment by Zymlex** [comment]
+1

**Comment by snowmen233** [comment]
+1
Though there are already several 3rd-party portable Postman REST Client, we would trust the official version the most :)

**Comment by comanche** [comment]
+1

**Comment by safepost** [comment]
+1 of course

**Comment by jjloneman** [comment]
Many enterprise people will support this feature. Because it installs to `%APPDATA%`, my company's enterprise policy restricts anyone from running any "unauthorized" executables from anything outside of `C:\Program Files`. Either a portable installer or an installer that allows selecting the destination directory is needed. Otherwise, I'm going to have to use the Chrome app until then.

![image](https://user-images.githubusercontent.com/16791848/35828640-ed7c0ed6-0a85-11e8-816b-8a3290fb884c.png)

**Comment by sourcecodemage** [comment]
+1 for this feature!

**Comment by krishnoid** [comment]
+1 yes, please.  Postman has been a make-or-spend-forever in a couple instances for me.

**Comment by KumarAlisetty** [comment]
+1 for this feature!

**Comment by crazy-max** [comment]
Have you tried this alternative : https://portapps.github.io/app/postman-portable/ ?

**Comment by jghaanstra** [comment]
Thanx @crazy-max , seems to work perfectly.

**Comment by a85** [comment]
We are continuously exploring multiple ways to package and make it easier to install Postman. We will have more updates on our blog.

**Comment by duckimann** [comment]
The program still doesn't have an official portable version at this time and as you guess, we still have to use that "installer"

**Comment by arlemi** [comment]
We've announced Postman for the Web a couple of weeks ago, it is for now in Beta and some API calls may still require to install a local agent, but we're working towards a cloud agent which should remove the need to install anything locally.
More info here: https://blog.postman.com/announcing-postman-for-the-web-now-in-open-beta/
