### ISSUE TITLE
Auth token not sent with request (Linux)

### ISSUE THREAD

**Issue by Alvyre** [a85/POSTMan-Chrome-Extension#4008]
## App Details:

```
Postman for Linux
Version 5.5.0
linux 4.4.103-36-default / x64
```

## Context

Hello !

After several mails with the support, they told me to add a new issue to the Github repository, so here I am :).
About the issue, on Linux (openSUSE leap) I downloaded Postman to try and test about an API. This API is using oAuth 2.0 authorization token, I can get successfully the token but when I try to use it with my request, it's not working (I can't "preview request" and the header is not set when I send it).

After some mails, I also tried these solutions : 
- https://github.com/postmanlabs/postman-app-support/issues/3616
- https://github.com/postmanlabs/postman-app-support/issues/3608

But none of these worked unfornunately.

Thanks in advance.

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:
**This issue has always been here.**
 2. Expected behaviour:
**Add the Auth token to header of the request.**
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
**see screenshots.**
 4. Screenshots (if applicable)
![screenshot_20171222_104611](https://user-images.githubusercontent.com/10566948/34378477-4f3f2612-eaf6-11e7-9bac-d44bedce48cc.png)
![screenshot_20171222_104638](https://user-images.githubusercontent.com/10566948/34378478-4f58815c-eaf6-11e7-84be-c0a0c0ef092c.png)
![screenshot_20171222_104704](https://user-images.githubusercontent.com/10566948/34378479-4f708360-eaf6-11e7-8685-b8ea06b1abd7.png)
![screenshot_20171227_110953](https://user-images.githubusercontent.com/10566948/34378545-9599491c-eaf6-11e7-9f45-7c01f99b2936.png)

## Steps to reproduce the problem:

- Create a new route on a API with oAuth (Any verb).
- Get new acces token with oAuth method with password credentials grant type. (success)
- Try to "preview the request" or to send the request.
- Not working : request didn't have any auth header and can't preview request.

**Comment by kamalaknn** [comment]
@Arctic76 Hi,

I'm guessing the token response for your OAuth provider does not have an `access_token` field. Postman tries to use `access_token`(as per the specifications) for Authorization. It is possible that some providers return the token in other names like `id_token` etc. 

You can verify this by opening the token in `Manage Tokens`. If that is the case you can manually copy the token and paste it in the input box for Access Token.

We'll take a look if we can disable the `Use Token` button if the token is not in a compliant format.

**Comment by Alvyre** [comment]
@kamalaknn Hi,

I checked and in the manage tokens section, the "Access Token" Field is filled.
Moreover, the API is using a oAuth library which uses 'access_token' field.

![access_token](https://user-images.githubusercontent.com/10566948/34406411-259703f2-ebb9-11e7-97f5-4fcb0d6af7f8.png)

Best,

Romain

**Comment by kamalaknn** [comment]
@Arctic76 I can see that in the token response the `token_type` is `string`. If you are using a general OAuth implementation it should be `bearer`. 

Although the spec allows specifying any token type, it is up to the consumer to interpret the type. Postman only understands the widely used `bearer` token type, which it does by adding a `Bearer` Authorization header.

We could add this as a warning for unrecognized `token_types`. I'm keeping a note of this.

**Comment by Alvyre** [comment]
@kamalaknn This was the problem thank you, I will check if this modification may impact other things in the API.

Thanks for your help !
