### ISSUE TITLE
After installing postan, Click on postman icon is opening google chrome page but not the actual postman

### ISSUE THREAD

**Issue by DeeNarsi** [a85/POSTMan-Chrome-Extension#4013]
## App Details:

```
Postman for Windows7

```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:
 2. Expected behaviour:
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 4. Screenshots (if applicable)

**Comment by prashantagarwal** [comment]
@DeeNarsi Can you please add a screenshot, which google chrome page gets open when you click on the icon.

**Comment by DeeNarsi** [comment]
I’ve re installed and it worked
