### ISSUE TITLE
White screen after a few seconds of opening the app

### ISSUE THREAD

**Issue by JuanZamudioGBM** [a85/POSTMan-Chrome-Extension#4014]
## App Details:
```
Postman for Windows
Version 5.5.0
win32 10.0.15063 / x64
```

## Issue Report:
Steps to reproduce
- Open the app
- Wait for it to load
- Two minutes later the screen turns white 
---

 1. Did you encounter this recently, or has this bug always been there:
This has been happening for about 2-3 weeks
 2. Expected behaviour:
Continue to use the app
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
If I click View -> Reload, and wait for the app to load again, and then open Dev Tools after the 2 minutes I get this error 
![postman](https://user-images.githubusercontent.com/28072896/34504745-113df376-efe6-11e7-8744-b74bcc913559.JPG)

 4. Screenshots (if applicable)
![postman2](https://user-images.githubusercontent.com/28072896/34504776-4c31af86-efe6-11e7-89fc-8135aac9aa86.JPG)

**Comment by prashantagarwal** [comment]
@JuanZamudioGBM Does this happen when you send the request or when the app is idle.

**Comment by JuanZamudioGBM** [comment]
@prashantagarwal  when the app is idle

**Comment by JuanZamudioGBM** [comment]
any updates on this? do you need more info?

**Comment by sivcan** [comment]
Kindly update to the latest version of the app - [Postman 6](https://www.getpostman.com/apps)
