### ISSUE TITLE
Postman tabs not restored and console not exiting with main app

### ISSUE THREAD

**Issue by aksbenz** [a85/POSTMan-Chrome-Extension#4015]
Since version 5.5.0, when we close the main Postman App window, the console does not exit.
This causes 2 issues:
1. Postman main app does not open again until we close the console window
2. (more severe) After closing console, and re-launching Postman, all the previous tabs are lost, even the ones which were not saved.

![postmanissuetabsnotrestored](https://user-images.githubusercontent.com/12194851/34508396-e3685402-f092-11e7-8cde-b74d0cc0b92e.jpg)

## App Details:
```
Postman for Windows
Version 5.5.0
win32 6.1.7601 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there
Since 5.5.0
 2. Expected behaviour: 
On closing main app, console should also close and on re-opening postman, previous tabs should be restored.

 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
NA
 4. Screenshots (if applicable)
Attached.

Steps:
1. Open postman windows app
2. Open console window
3. Open few requests
4. Close the main app
5. Close the console window
6. Re-open postman

**Comment by prashantagarwal** [comment]
@aksbenz Thanks for reporting this issue. We will look into it and keep you updated.

**Comment by SamvelRaja** [comment]
@aksbenz The issue of losing the tabs had been fixed in our 6.1 version of the app. 

We will keep you posted on closing the console when all postman windows closes issue.

**Comment by vkaegis** [comment]
@aksbenz Regarding your first issue around closing the console on closing the main window, these actions are usually handled by the OS and we wouldn't want to interfere with this. For example, in Windows, you can right click on the Postman application icon in the taskbar and select Close All to close all Postman windows.

We are also looking into improving window management within Postman and allowing users to lock windows into panes within the main Builder window. Stay tuned for more updates on this!
