### ISSUE TITLE
Feature request: Ability to receive updated OAuth credentials from onprem service

### ISSUE THREAD

**Issue by yenoomluap** [a85/POSTMan-Chrome-Extension#4020]
I would like to be able to connect to postman and update OAuth tokens for our connections. Postman would accept and update the authorization code saved in the environment specified.  This automation would save time from having to manually using postman to get a refresh token for our APIs.

**Comment by prashantagarwal** [comment]
@pc-mooney I think you should be able to do this by fetching OAUTH tokens in your pre-request script using` pm.sendRequest` and setting the fetched tokens to your environment variable. 
This [gist](https://gist.github.com/madebysid/b57985b0649d3407a7aa9de1bd327990) has some pm.sendRequest examples which you can use for reference.
