### ISSUE TITLE
Request working in curl but not in postman

### ISSUE THREAD

**Issue by astraydog** [a85/POSTMan-Chrome-Extension#4022]
I copied the request  from GENERATE CODE SNIPPETS of CURL,it is working in curl.
`curl -X POST \
  http://xxx.xxx.xxx.xxx:9911 \
  -H 'Cache-Control: no-cache' \
  -H 'Postman-Token: f9b03f77-1f22-b90a-dcb4-12b67db281d3' \
  -d 'data={"dspid":"xxxx" , "timestamp":1488787766, "sign":"xxxxx", "code":110}'`
![curl](https://user-images.githubusercontent.com/2909868/34557045-e96ca880-f173-11e7-8e27-fdd4c0136dbd.jpg)

but when I press  Send button in postman,the request is not working.

![postman-ui](https://user-images.githubusercontent.com/2909868/34557047-ebf05a7a-f173-11e7-8b38-e24ba238edcf.jpg)

**Comment by SamvelRaja** [comment]
@astraydog  The error message shows that request has been sent to the server from postman and the server responded with the Error.
Also, can you check the request sent out of postman using postman console (View -> Show Postman Console)

**Comment by astraydog** [comment]
@SamvelRaja the request in postman console is below

![postmanconsole](https://user-images.githubusercontent.com/2909868/34592312-0c80c358-f1fe-11e7-88b5-54626082d50a.jpg)

I can not find the difference between curl code and postman tool...

**Comment by SamvelRaja** [comment]
@astraydog  The dev log shows postman is sending the request properly to the server.
You check your server logs to verify the same for the difference in the data received.

**Comment by astraydog** [comment]
it's not convenient for us to check the sever log....
![image](https://user-images.githubusercontent.com/2909868/34604364-71ffb93e-f242-11e7-8b5c-d872f5b06e34.png)
