### ISSUE TITLE
Feature Request: Reference another request by name

### ISSUE THREAD

**Issue by cool-george** [a85/POSTMan-Chrome-Extension#4024]
## App Details:

```
Postman for Mac
Version 4.11.0
OS X 16.4.0 / x64
```

## Issue Report:
Please add a feature that allows references to be made from request (x) to request (y) in the scripts. pm.setRequest(); uses a URL and postman.setNextRequest(); uses the name but has to be used in conjunction with the Collection Runner, which doesn't do what I need it to do. Perhaps, using something like this: pm.getRequest("Request_Name (y)");

**Comment by kamalaknn** [comment]
Thanks, @cool-george

I'm marking this as a feature request. We'll share updates on the status here.

**Comment by avinashkandukuri** [comment]
Thanks for your updates on this issue @harryi3t

**Comment by shamasis** [comment]
Note: This would be part of the initiative of making collection-level data available within Postman Sandbox in the long term. This has no ETA in short to mid term and needs to be decided where in long term this gets scheduled

**Comment by arlemi** [comment]
Hey 👋 I've gathered all feedback from here and other issues into a single one, we will keep the discussion going there, closing this issue. 

➡️  https://github.com/postmanlabs/postman-app-support/issues/4193#issuecomment-626699439
