### ISSUE TITLE
No API Found to Create Users

### ISSUE THREAD

**Issue by GKandekar** [a85/POSTMan-Chrome-Extension#4025]
I am trying to Integrate Postman with Sailpoint IIQ to provision user in Postman Team. Their is no API to create user. No Use if we have to create user manually for each employee and Active them Manually.

**Comment by numaanashraf** [comment]
@GKandekar Thanks for writing in. Are you trying to setup Sailpoint IIQ as an identity provider for your Postman Team? Please write to us at `help@getpostman.com` and we'll be happy to walk you through setting up this integration.
