### ISSUE TITLE
Is it possible to put a environment variable from 1st request and put it in the responseBody of the 2nd request?

### ISSUE THREAD

**Issue by SnorreFossland** [a85/POSTMan-Chrome-Extension#4026]
## App Details:

Postman for Windows
Version 5.5.0
win32 10.0.15063 / x64

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:  
Recently
 2. Expected behaviour:
The Body of 2nd request should contain the json data from the environment variable "Json_response"
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 4. Screenshots (if applicable)

1st request:
**GET     localhost:8080/data/simple.xml**

this returns an responseBody with the xml-file content.
The xml2Json works fine and I get the Json data correct in the console.log:

v**ar jsonObject = xml2Json(responseBody);
console.log(jsonObject)**

I also get the json data set to an environment variable:

**var strjsonObject = JSON.stringify(jsonObject);
pm.environment.set("Json_response", strjsonObject);**

2nd request:
**Get or Post: localhost:8080/<arguments to get the "Json_response" in responseBody>**

How du I specify the 2nd request or is it possible to do all in one request?

**Comment by numaanashraf** [comment]
@SnorreFossland, You can use the value from the environment variable directly in the URL of the second request - `localhost:8080/{{Json_response}}`;

**Comment by SnorreFossland** [comment]
Thanks, Im not able to change the Content-Type  from text/html to application/json.
The Body content is like this:


HMTL tags.... Error 
        <pre>Cannot GET /%7B%22metis%22:%7B%22$%22:%7 ................... json data sting
HTML tags

I set the Headers to:
 Content-Type:application/json
Accept:application/json
but still got only HML response.
