### ISSUE TITLE
Manage Environments UI bug

### ISSUE THREAD

**Issue by tvvignesh** [a85/POSTMan-Chrome-Extension#4027]
## App Details:
```
Postman for Linux
Version 5.5.0
linux 4.14.0-041400-generic / x64
```

## Issue Report:
Environments displayed in one view but not in another. There are 2 ways now to manage environments (one via new in the top left portion and another via cog icon->manage environments at right portion)

Both show different data for same thing. Image attached below

**WHEN CLICKING NEW->Environment**
![p2](https://user-images.githubusercontent.com/1165845/34598408-8f134642-f212-11e7-83f3-cdc1225262fd.png)

**WHEN CLICKING Cog icon->Manage environments**
![p1](https://user-images.githubusercontent.com/1165845/34598409-8f3db9c2-f212-11e7-986c-60eaa19bf908.png)

**Comment by numaanashraf** [comment]
@tvvignesh Thanks for writing in. Could you clarify the issue? The first one is a screen to create a new environment and the second screen is a list of environments you currently have that you might want to manage.

**Comment by tvvignesh** [comment]
@numaanashraf : OOPS! Sorry.. I got it wrong. Its working fine. I got a bit confused since New->Environment gave a differnt screen and Cog->Manage Environment gave a different screen. But when I clicked cancel, it brought me back to the list.
