### ISSUE TITLE
PUT methods does not upload the file.

### ISSUE THREAD

**Issue by neilghosh** [a85/POSTMan-Chrome-Extension#4029]
## App Details:

```
Postman for Mac
Version 5.5.0 (5.5.0)
OS X 10.13.2 / x64
```

## Issue Report:
 1. This bug always been there:
 2. Expected behaviour:
      When you select a file tp be uploaded as part of PUT request it does not confider the file. Also the code generated does not have --upload-file parameter.

1.Select the method as PUT and browse the file from file system.
2.Send the request and observe the request does not upload the file selected
3.Also verify the code it does not have the e.g. cURL, it does not have the --upload-file argument 

It would be simply 

curl -X PUT 'http://example.com/endpoint' 

but it should be 

curl -X PUT 'http://example.com/endpoint' --upload-file filePath

**Comment by numaanashraf** [comment]
@neilghosh Thanks for writing in. Are you trying to send the file as a form data or as a binary payload in the request?

**Comment by neilghosh** [comment]
It's binary form upload.

On 5 Jan 2018 6:08 pm, "Numaan Ashraf" <notifications@github.com> wrote:

@neilghosh <https://github.com/neilghosh> Thanks for writing in. Are you
trying to send the file as a form data or as a binary payload in the
request?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/postmanlabs/postman-app-support/issues/4029#issuecomment-355545430>,
or mute the thread

**Comment by numaanashraf** [comment]
@neilghosh We are unable to replicate the binary file issue. Seems to be working as expected in Postman 6.1.4.

<img width="867" alt="screen shot 2018-06-29 at 5 41 41 pm" src="https://user-images.githubusercontent.com/3295568/42091637-bfc33a46-7bc3-11e8-90b5-0cb3a38584bc.png">

**Comment by numaanashraf** [comment]
We were able to replicate the code generation issue with binary files and form data files. We are tracking the issue at #2875.

**Comment by bnymn** [comment]
Hi @numaanashraf ,

Would you please use the following configurations?

### With POST (Working)
![screenshot from 2019-01-14 20-30-31](https://user-images.githubusercontent.com/3506402/51145553-4ddd5a00-183b-11e9-81ff-f415112eaff8.png)

### With PUT (Not Working)
![screenshot from 2019-01-14 20-31-07](https://user-images.githubusercontent.com/3506402/51145588-6cdbec00-183b-11e9-8ad1-93fa9817d476.png)

**Comment by kamleshwebtech** [comment]
Upload file with other form fields by using form-data is still not working in Postman. Kindly suggest.

**Comment by iz-ben** [comment]
I have the same problem. The PATCH/PUT option doesn't work in combination with the 'form-data' option, therefore I am unable to send files to the server

**Comment by dem13** [comment]
Same to me. I can upload file using POST method, but PUT method doesn't work.

**Comment by FVBernardino** [comment]
Check this
1- Headers:
    - Content-type: multipart/form-data
2- Body:
    - Add key (file) and change type field for file. This show select file for upload;
    - Add key (_method) with value: PUT

The route send must be POST.

**Comment by davileichs** [comment]
Still the PUT is not working with form-data. Besides the workaround works, it would be good to use normal PUT/PATCH methods.
