### ISSUE TITLE
"Manage Access Token" close button after getting new access token not working as intended

### ISSUE THREAD

**Issue by snaits** [a85/POSTMan-Chrome-Extension#4032]
## App Details:

```
Postman for Windows
Version 5.5.0
win32 10.0.16299 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there: Always been here
 2. Expected behaviour: Click close button, "Manage token" closes
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 4. Screenshots (if applicable)

In the Authentication tab, when I use OAuth 2.0 and "Get new access token" , after a successful request is returned, I am looking at the "Manage Access Tokens" window.

When I want to close it, I click the X in the top right corner... and I have to click the same number of times as the tabs I currently have open. And I usually have 10-15 tabs depending on the project I'm working on.

Would be super if this could be changed to close after just one click! 👍

**Comment by thecuriousdev** [comment]
@snaits thanks for reporting this issue, we'll look into this.

**Comment by prashantagarwal** [comment]
@snaits This is fixed in our latest version of Postman apps.
