### ISSUE TITLE
(GET method) request.data empty 

### ISSUE THREAD

**Issue by GioLogist** [a85/POSTMan-Chrome-Extension#4034]
## App Details:

```
Postman for Mac
Version 5.5.0 (5.5.0)
OS X 10.13.2 
```

Encountered recently.

Expected behavior: 
**request.data includes params from URL**

Actual behavior:
**request.data is empty**

**Comment by thecuriousdev** [comment]
@GioLogist thanks for reporting this issue, please provide more details to debug this issue.

**Comment by GioLogist** [comment]
Sorry about that, I was speaking in regards to test scripts. 

`request.data` returns empty when using the `GET` method

**Comment by GioLogist** [comment]
Sure.

`request.data` returns empty when using the `GET` method in test scripts. I would expect it to show `params`. However, it returns empty.

Here's an example:
![screenshot 2018-01-08 04 01 17](https://user-images.githubusercontent.com/4120754/34669868-a979893e-f428-11e7-9e95-5c4190b9c9ea.png)

**Comment by thecuriousdev** [comment]
the `request.data` is represents the request body, since GET doesn't have a request body its returns empty. I think you are looking for `request.url`

**Comment by GioLogist** [comment]
Right, just figured maybe it'd be a good idea to parse params from URL when using GET. However, I don't mind parsing them myself via URL if need be 👍🏻
