### ISSUE TITLE
Postman app history disappears in VDI

### ISSUE THREAD

**Issue by TatianaDenel** [a85/POSTMan-Chrome-Extension#4035]
Postman app installed at Windows 7, running through VDI.
My problem is, that any time Image update all users lost there history at postman.
Where is postman app locates it's settings and history in the image? How can we protect it from deleting?
## App Details:

```
Postman for Win
Version 4.11.0
OS X 16.4.0 / x64
```

**Comment by thecuriousdev** [comment]
@TatianaDenel thanks for reporting this issue, we'll look into this and get back to you soon.

**Comment by sivcan** [comment]
Hi @TatianaDenel 
As I can see you're using the old version of the postman app, I advise you to update to the latest version - It includes new features and performance improvements.

Also, I advise you to use sync (By signing up in the Postman App) - which will sync your data and you wouldn't be losing any data whenever the applications local data is deleted.
Once you login, you'll get your data synced from the server back to you.

You can do the following steps to retrieve the location of the application data.

We'll be using the [electron API](https://electronjs.org/docs/api/app)

Steps: 
1. Launch the Postman App 
2. Launch the Developer Tools (View > Developer > Show Dev Tools) 
3. In the '**Console**' type the following  : `var app = require('electron').remote.app;`
4. Then type `app.getPath('appData');`

This will give you the path as to where the data is stored on the machine. 

Hope this helps.
