### ISSUE TITLE
HTTP Status code 204

### ISSUE THREAD

**Issue by eyJhb** [a85/POSTMan-Chrome-Extension#4036]
## App Details:
```
Postman for Linux
Version 5.5.0
linux 4.4.0-104-generic / x64
```

## Issue Report:
When the API/webservice sends a 204 (no-content), that Postman app will say it failed to get a response from the server..

It should just display nothing, with the HTTP Statuscode 204.

**Comment by thecuriousdev** [comment]
@eyJhb thanks for reporting this issue, I tried from my side but not able to re produce the issue, can you please provide more details (screenshot, URL if its publicly available)?

**Comment by eyJhb** [comment]
@thecuriousdev I've made the request with postman standalone client, and then again in python - printing out the status_code, to show that it  gets something.

Images here - https://imgur.com/a/hsFNu

The headers that python gets in return are

`{'Content-Type': 'application/json', 'Cache-Control': 'no-cache, private', 'Date': 'Wed, 10 Jan 2018 14:01:42 GMT', 'Server': 'nginx/1.13.3', 'Connection': 'keep-alive'}`

**Comment by cwm22** [comment]
What was the final determination regarding this?  I believe I am running into this same issue.  I can see the response perfectly fine in fiddler.
