### ISSUE TITLE
Postman error while reaching endpoints with self signed certs

### ISSUE THREAD

**Issue by yogeshdengle** [a85/POSTMan-Chrome-Extension#4038]
## App Details:
```
Postman for Windows
Version 5.5.0
win32 10.0.14393 / x64
```

## Issue Report:
When calling an API with a self signed cert even with the the Settings-> General -> SSL Certificate Verification turned off, the SSL handshake fails.
The error message is:

**Error: write EPROTO 101057795:error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure:c:\projects\electron\vendor\node\deps\openssl\openssl\ssl\s23_clnt.c:769:**

The error message is also a bit weird as I don't have the c:\projects\electron folder on my system.
When hitting https://google.com the same installation works fine.

TLDR; The SSL verification flag seems to be broken for me.

##Steps to Reproduce:
a. Set the SSL Verification to off.
b. HIt any https API using a self signed cert.

What has been tried:
a. Re-installing 
b. I pointed to the same service just hosted on ec2 with a valid DN and that works.
c. Deleted data from AppData/Local and AppData/Roaming and re-installled Postman.

See screen shot:
![image](https://user-images.githubusercontent.com/3128121/34663144-423a7078-f47b-11e7-81d2-bf3256d58e1d.png)

**Comment by thecuriousdev** [comment]
@yogeshdengle thanks for reporting this issue, can you please provide a screenshot of settings->certificates

**Comment by yogeshdengle** [comment]
There are no client side certs configured.

![image](https://user-images.githubusercontent.com/3128121/34670988-934a92f4-f49e-11e7-94f9-abd76c6a165c.png)

**Comment by EricPSU** [comment]
I'm having the same issue in v5.5.0 for Linux.  I'm attempting to use a self-signed certificate to make my API call.  With the `SSL Certificate Verification` setting `ON`, I get an error `SSL Error: SELF_SIGNED_CERT_IN_CHAIN`.  When I turn the `SSL Certificate Verification` setting `OFF`, it doesn't send my certificate with the API call.  

Shouldn't the `SSL Certification Verification` setting should just control the verification of the certificate before the call is made and still send the certificate with the call?

**Comment by vmurin** [comment]
We have the same problem (same error message) but with normal (not self-signed) certificates from Amazon API Gateway. The actual problem is not the fact of self-signing but the SSL Version!
Postman tries to make connection with SSLv3 and it is considered as insecure  and therefore refused by Amazon Gateway.
It could be also the reason in other cases not only for Amazon.
Postman for Chrome (v.5.4.0) does not have this problem and works well.

**Comment by yogeshdengle** [comment]
@thecuriousdev can you take off the waiting-for-response label so that someone can take a look at this? I have provided the required screen shot and a few other folks have also commented that they do see this issue.

**Comment by EricPSU** [comment]
If it helps, I posted this on another thread  (#3963), but it is also applicable to this thread.

I'm using self signed certs, which means I need to turn off `SSL certificate verification` in Settings > General.  Attached screenshot shows the first GET was with the setting ON, and it returns an SSL error which is expected.  Second GET is with it OFF, it does not attempt to send the certificates with the request.  It appears that the `SSL certification verification` setting just disables send the cert on the Linux build.   The setting works correctly on Windows.


![postman_ssl](https://user-images.githubusercontent.com/25805189/35400502-f1c09f08-01c4-11e8-9d7f-32d51e036053.png)

**Comment by yogeshdengle** [comment]
@EricPSU I have the SSL verification to off.
I have verified what @vmurin has stated, on the application side, I had the server configured to use TLS for https, I turned that off and that caused post to work correctly. So it definitely is a problem of postman using sslv3 instead of TLS as required by my app.

**Comment by EricPSU** [comment]
@yogeshdengle You are correct.  I just tried swapping SSL3 for TLS and it appears to be a TLS issue.  Postman does not support TLS 1.0+ and is set to use SSL3.0-.

@thecuriousdev we've confirmed the issue, can you switch the status of this ticket?

**Comment by yogeshdengle** [comment]
@thecuriousdev why closed? This is an issue with Postman not using TLS

**Comment by EricPSU** [comment]
@thecuriousdev is this issue being merged into a different bug?  Has it been fixed for the next release?

**Comment by slaman75** [comment]
Has this issue been fixed?

TLS is the expected standard.  Enabling SSL3 on our servers creates an unnecessary vulnerability.

Please escalate

**Comment by remisbaima** [comment]
I have the same issue

**Comment by maryoomi** [comment]
Thanks @EricPSU. It worked for me by setting SSL certificate verification to off.

**Comment by mancave** [comment]
A lote of calls made last week with the same collections. But now without changing the collection I get the errors  "self signed certificate in certificate chain". But to enable or disable the "SSL certificate verification" we get the message "self signed certificate in certificate chain".

Current version: Postman for Windows, Version 6.7.2, win32 10.0.17134 / x64

**Comment by numaanashraf** [comment]
@mancave Are you referring to OAuth2 flow with self-signed certificates? https://github.com/postmanlabs/postman-app-support/issues/5819#issuecomment-457625628

**Comment by mancave** [comment]
Yes I have the same problems

**Comment by numaanashraf** [comment]
@mancave Thanks for confirming. Please follow #5819 for updates on this issue.

**Comment by mgthet** [comment]
![image](https://user-images.githubusercontent.com/15937741/65012368-17f9f380-d93d-11e9-9dc1-f219adf5e06c.png)
Please help me this error when I calling to self-sign certificate API.
