### ISSUE TITLE
Lost all collections

### ISSUE THREAD

**Issue by Calamitous** [a85/POSTMan-Chrome-Extension#4040]
## App Details:
```
Postman for Linux
Version 5.5.0
linux 4.4.0-104-generic / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:
I experienced this today.

 2. Expected behaviour:
Collections would not vanish.

 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
```
requester.js:242093 You tried to return focus to null but it is not in the DOM anymore
exports.returnFocus @ requester.js:242093
```
 4. Screenshots (if applicable)
N/A

I've just lost a great deal of work to this bug which, looking through the many closed issues, is a known thing.  I don't know what else to add except to express my immense frustration about this tool.

**Comment by kamalaknn** [comment]
Hi,

Sorry that you've lost your data. Postman stores all its data in the `~/.config/Postman` for Linux. Could you verify if you have data in it?

Anyways, if you had signed in, signing in again should bring back all the data.

If none of these work, could tell us if you saw the sign in screen that led to your data loss?

**Comment by Calamitous** [comment]
There are a number of files in ~/.config/Postman:

```
❯❯❯ ls
Cache      File System  IndexedDB      Partitions  Cookies-journal  QuotaManager          requester.json  SingletonCookie  SS
databases  GPUCache     Local Storage  Cookies     Preferences      QuotaManager-journal  settings.json   SingletonLock
```

I'm not sure where in here the collections would be stored.

I was not signed in.  I did not see a sign in screen; I opened it like I usually do (from the command-line), there was an introductory/welcome screen, but no data behind it.

**Comment by malyalal** [comment]
As suggested by @kamalaknn I signed back in still, I don't see missing collections there.

**Comment by a85** [comment]
Please email us at help@getpostman.com with your account details and the support team might be able to help you out.
