### ISSUE TITLE
Can't find postman collections which I have not used for few months.

### ISSUE THREAD

**Issue by malyalal** [a85/POSTMan-Chrome-Extension#4042]
I am a postman pro user. I lost all old postman collections, how can I restore them? 
it is nearly same as issue #4040 

## App Details:

Postman for Mac
Version 5.5.0
OS X 17.3.0 / x64

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:
yes, since i started using postman downloaded app.
 2. Expected behaviour:
Restored all collections I created.
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 4. Screenshots (if applicable)
NA

**Comment by kamalaknn** [comment]
I've left a comment on #4040, could you try loggin in again?

I'm closing this as a duplicate. Please follow the parent issue for update.
