### ISSUE TITLE
Last Postman version. Can't execute POST request

### ISSUE THREAD

**Issue by AlexanderTunick** [a85/POSTMan-Chrome-Extension#4043]
Having just simple POST request, after installing the newest Postman version
And now having the same data i do it successfully in "old" postman and can't in the new one

`There was an error in evaluating the test script:  JSONError: Unexpected token '<' at 1:1 <!DOCTYPE html> ^`

I will give more info if you need

**Comment by SamvelRaja** [comment]
Can you try switching to preview mode in the response view?
The server giving a HTML response, which postman trying to do JSON.parse

**Comment by szaza** [comment]
Hi,
I observed the same issue, the POST request worked for me with the version 5.4, however it doesn't work with the current one:

Postman for Windows
Version 5.5.0
win32 10.0.15063 / x64

I figured out it works if I specify the protocol in the URL like: https://domain.example.
With the old version it works well without specifying the protocol.

Right now if I put simply domain.example in the URL it gives me the following error:
{
    "message": "error.methodNotSupported",
    "description": "Request method 'GET' not supported",
    "fieldErrors": null
}

Could you please check it?

**Comment by AlexanderTunick** [comment]
@SamvelRaja, thanks for the response, preview mode says: 
_

> Sorry, the page you are looking for could not be found.

_
so none useful information
@szaza, thanks, but originally I always specify protocol, therefore it's ok,
and here as well:
`http://34.234.5.97/api/v1/` I use it in variable `{{api_base_url}}`

**Comment by Alextunchii** [comment]
Really hate this Postman version with these bugs which in addition to this nobody consider 
Chrome Postman: everything ok
New Postman, 400 bad requests or other problems with the same request migrated via synchronization

**Comment by jackvial** [comment]
Had the same problem. Was posting to http instead of https.

**Comment by sjjpo2002** [comment]
Same issue here. I use Postman for Chrome Version 5.5.2 to send a POST request it works. Same request on the latest Postman for Windows Version 6.1.3 doesn't work. Content type is "application/x-www-form-urlencoded".

**Comment by j1014330** [comment]
Did anyone find a solution to this issue?

**Comment by VonTalavang** [comment]
I just stop using it, going back to soapUI.

**Comment by numaanashraf** [comment]
@VonTalavang Please verify that your server is not sending a redirect for your POST request. More details at https://github.com/postmanlabs/postman-app-support/issues/450#issuecomment-435352122

**Comment by AlexanderTunick** [comment]
I had to completely delete a few request from the collection and write brand new exactly the same request and it works, since opening this report I’ve never encountered it again and enjoyably using Postman, which is despite some bugs is the coolest tool for work with http request so far.

**Comment by VonTalavang** [comment]
> @VonTalavang Please verify that your server is not sending a redirect for your POST request. More details at [#450 (comment)](https://github.com/postmanlabs/postman-app-support/issues/450#issuecomment-435352122)

I did it. I think you guys shouldnt marked as resolved.
Today I runned postman again, no changes. Magically post works.
I turned of my laptop then on again. Postman did the "get -> post" bug again.
Both times no changes.

**Comment by moiniqbal205** [comment]
Just found this thread - this is probably a bit too obvious a solution, but did you guys try keeping the terminal/command prompt open by running `php artisan serve`? Post requests should work while having this running.
