### ISSUE TITLE
Add Collection Authorization type "Headers"

### ISSUE THREAD

**Issue by javabrett** [a85/POSTMan-Chrome-Extension#4044]
## App Details:
```
Postman for Mac
Version 5.5.0 (5.5.0)
```

## Issue Report:

This is an enhancement request to add a new Authorization type to the existing types available for a Collection: the new type might be called _Headers_ or _Custom Headers_.

The idea being that you can add an arbitrary set of Header name/value pairs to be used as authorization tokens and added to each request.

Sometimes when you are developing you just need to add a set of headers (here for the purposes of authorization) to each request.  The required header names might not conform to existing authorization standards.

Perhaps the downside of this enhancement is that by allowing any HTTP Header whatsoever, this functionality goes beyond that required for authorization, and could be used for example to add any set of custom headers to all requests in a collection.  In this way it duplicates requests such as #1947 and #2692.  But based on the current UI and features, the Authorization tab seems a reasonable place to expose this sort of feature.

**Comment by dlgoodchild** [comment]
+1 (just as in #1947)

Seriously, this app _really_ needs ability to set common headers and properties for all requests.

**Comment by SamvelRaja** [comment]
I don't think we will add this feature as new authorization header, but we get your concern of having common headers for all the requests in a collection. We shall look in that way and solve the usability.

**Comment by dlgoodchild** [comment]
This is great news to hear that common headers may finally arrive. My usage of Postman has been in slow decline, because of that one major missing feature...it really is quite vital for large systems.

**Comment by GraemeAllanBryce** [comment]
working with AWS Cognito authorisation this is needed.  It is not resolved by only having AWS Sig4

+1

**Comment by Iliev88** [comment]
+1

**Comment by sobkowicz** [comment]
+1

**Comment by mathewrg** [comment]
+1
Thanks for all the good work you guys are doing. Having this feature will increase the usability very much. Thanks..

**Comment by arenaq** [comment]
+1

**Comment by xavier-b** [comment]
+1

**Comment by degraaf** [comment]
+1

**Comment by e2canoe** [comment]
We really need this. I just added authorization to my project and was shocked to discover that I now need to manually add my test token variable to all my requests' headers.

**Comment by Iliev88** [comment]
@e2canoe You can save headers in **Presets**

![image](https://user-images.githubusercontent.com/25150497/36060415-f3bc7810-0e51-11e8-83a7-c129734c9c1c.png)

**Comment by devonparsons** [comment]
@Iliev88 Useful, but header presets are not shared with your team, and editing them after the fact does not edit the requests already using them.

**Comment by darron1217** [comment]
I've always been dreamed of this feature as collection config!

Just like the image below
![image](https://user-images.githubusercontent.com/8064923/36296106-ee0b3744-132e-11e8-9b5b-e2ac878d5f72.png)

I hope this feature to be added soon!

**Comment by prashantbissa** [comment]
+1

**Comment by ma-schmidt-de** [comment]
+1 @darron1217 
The use case of having a default header like "origin=XX" or "apikey=XX" is super common. We definitely need a central place to define headers for Collections and Folders.

**Comment by Gosherm** [comment]
+1

**Comment by amouchinski** [comment]
Please add support for default headers per folder or collection as suggested by darron1217.

**Comment by LucasSteinwalker** [comment]
+1 on this request. Unfortunately a lot of API implementations don't use a standard authentication token. I just pulled in a Swagger import of 500+ requests on a new project I'm working on and unfortunately will need to add the authorization header to every request, which is a major pain.

Don't mean to seem ungrateful though. Postman is the best!

**Comment by dolmen** [comment]
Please:
- use [GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)
- use the [Subscribe button](https://help.github.com/articles/subscribing-to-and-unsubscribing-from-notifications/)
- delete your uselesss "+1"
- don't add "+1" that spam the 21 users already subscribed

**Comment by jcavalieri** [comment]
👍

**Comment by NathanNorman** [comment]
I solved this problem for my own personal situation by utilizing [jq](https://stedolan.github.io/jq/). 

1. Export postman collection to JSON. (I used Collection v2.1)
2. Add the header "x-realm: admin" to all request headers.
`jq 'walk(if (type == "object" and has("header")) then .header |= (. + [{"key":"x-realm", "value":"admin"}] | unique) else . end )' collection.json > modified.json`
3. Delete original collection and import the modified collection.

By using the `unique` function in jq this only adds the header if it is not already there. 
This same technique could be used to add any header key/value. 

I am certainly not a jq expert so any suggestions on improvements to this technique are welcome.

I should also mention that the `walk` function is not in the current jq release. If you would like to utilize it, see [this issue](https://github.com/stedolan/jq/issues/963).

**Comment by vpArth** [comment]
Any progress on this?

It's not too difficult to implement, but too important for users.  
Too much apis use custom header authorization. 
Several of them changed to custom header authentication from BasicAuth(after I create a collection in Postman).  
Should be **a way to map this API change** into Postman.  
These API changes are reason differs that issue from #1947 

Minimal is simple authorization method: "Custom Header" with two fields: name and value. Value can have variable substitutions for convenience.

Example:  

  Header: "X-Api-Auth"
  Value: "Token {{api_token}}"

Much better is to implement "Custom Headers" as a collection of key/value pairs, as proposed in this issue.

Also, this feature covers almost any other authorization method automatically.  
One that is a reason to implement it! =)

**Comment by AndrewGene** [comment]
My login endpoint returns an object like 

`{
    "email": "...",
    "firstName": "...",
    "lastName": "...",
    "token": "4e3463c2-9476-4e9a-9ed2-45347ea02275",
    "userId": "2094"
}`

**Token** is the key used in every other request's **Authorization** header.  It is short-lived (couple of hours).

So I made a "Test" in postman that reads and stores the token value into a global variable
`let jsonData = pm.response.json();
let token = jsonData.token;
pm.globals.set("token", token);`

Every other request is set up to have an **Authorization** header with the value...

`{{token}}`

I simply need to make sure I call the **Login** endpoint before I start working on the other routes.

**Comment by bobjackman** [comment]
@AndrewGene I do basically this very same thing. It works, but the problem with it is that you have to ensure that every other call you make remembers to include this custom value. There's no way to "import" this value as a header on the collection itself.

**Comment by AndrewGene** [comment]
Yes but the other issue mentioned above will address the custom header per collection problem. Postman said they will be releasing that “soon”. 

Andrew Gene Goodwin

**Comment by Nicolai6120** [comment]
Postman support soooooo slow.... Implement one simple feature is not so hard, really?

**Comment by shamasis** [comment]
We are working on programmatic way to inject headers from pre-request scripts. You can add one in collection script and that would add the same in all outgoing requests!

Also, we are modifying the Bearer auth to have modified header key name. If your bearer token auth system has special header key, then that would be possible. Would update the issue when this is released.

PS: Also considering adding an "Api Key" type auth since it seems there is no standard to provide api key. We should be able to select header name and a value there.

**Comment by AndrewGene** [comment]
Thank you so much for the feedback @shamasis.  Postman has become integral to our workflow.  Keep up the great work.

**Comment by talbronfer** [comment]
Any updates on when this feature will reach production?

**Comment by shamasis** [comment]
@talbronfer both the solutions mentioned at https://github.com/postmanlabs/postman-app-support/issues/4044#issuecomment-463200228 is now out in production. I think in latest v7.1 app. Waiting for some feedback to double check if they are working fine. 

Can you try them out and let us know? (1) api key auth type and (2) ability to manipulate request headers from script.

**Comment by wabiloo** [comment]
@shamasis - any documentation on how to achieve 2)?

**Comment by ma-schmidt-de** [comment]
@wabiloo This should help you: 
https://community.getpostman.com/t/setting-headers-for-entire-collection-folder/708

**Comment by codenirvana** [comment]
@wabiloo To mutate request headers via `pre-request` scripts:

```js
// Add new header
pm.request.headers.add({
    key: 'Authorization',
    value: 'api-key'
});

// Add or update an existing header
pm.request.headers.upsert({
    key: 'Authorization',
    value: 'new-api-key'
});

// remove header
pm.request.headers.remove('Authorization')
```

Refer: https://github.com/postmanlabs/postman-app-support/issues/1947#issuecomment-477775232

Also, as mentioned in https://github.com/postmanlabs/postman-app-support/issues/4044#issuecomment-463200228 the latest version of the Postman app adds support for new API Key auth:

<img width="808" alt="Screenshot 2019-06-05 at 12 48 43 PM" src="https://user-images.githubusercontent.com/4865836/58937529-4689ff00-8790-11e9-869d-7d5c85720b78.png">

**Comment by bobjackman** [comment]
This is excellent! Thank you! This will be a huge improvement for my workflow.

I've got requests working using this new feature, however, it looks like the headers added during the pre-request script are NOT added to the export/code dialog (see screenshots) this means I can't copy/paste the request into a terminal if needed (unless I go dig up the header names and values and add them to the curl command manually every time):

![image](https://user-images.githubusercontent.com/1231996/59373442-89068b00-8cfe-11e9-9ed9-452c3256b75a.png)
![image](https://user-images.githubusercontent.com/1231996/59373500-ab000d80-8cfe-11e9-9d1c-173e08a7ce23.png)
![image](https://user-images.githubusercontent.com/1231996/59373685-092cf080-8cff-11e9-91c0-d5fa19ac9eb1.png)

**Comment by codenirvana** [comment]
@KOGI We are tracking this feature request here: #6349

**Comment by wabiloo** [comment]
Thanks for this massive improvement!
The collection-level headers created through pre-request scripts also don't appear in the "Temporary Headers" panel on individual requests. Would be great if they could appear there as well!

**Comment by kevcam4891** [comment]
Any update on being able to customize the "Bearer" string? AWS Cognito doesn't want Bearer in the Authorization header, just the token. I simply need a way to remove this text, please!

**Comment by kepikoi** [comment]
What about supporting multiple API keys in the header?
The `pre-request` script solution is not applicable when generating collections from an imported oas3 (due to https://github.com/postmanlabs/openapi-to-postman/issues/158)
