### ISSUE TITLE
Issue on the Authorize token request

### ISSUE THREAD

**Issue by abhishekbhalani** [a85/POSTMan-Chrome-Extension#4046]
## Password not sending with POST request:

```
Postman for Windows
Version 5.5.0
win32 6.3.9600 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there: Yes
 2. Expected behaviour: Password must be send along with request. 
3. Screenshots (if applicable)
http://prntscr.com/hyg0h6
http://prntscr.com/hyg0ow

**Comment by SamvelRaja** [comment]
If I am not wrong, the password property in the data is not showing in the code generated?
In that case, it is properly showing for me. 
Kindly check and let me know if I missed any flow.
![code-gen](https://user-images.githubusercontent.com/5114052/34774365-0fa1b08e-f635-11e7-9185-2434b56d8648.gif)
