### ISSUE TITLE
How to store list of values in environment variable and use them for next request?

### ISSUE THREAD

**Issue by tanpnguyen139** [a85/POSTMan-Chrome-Extension#4047]
Dear all,

Please help me on this case: below is my 1st request response, you can see that in "content" object has many "policyNum" and "policyNumEncrypt".  I am trying to store policyNumEncrypt value to variable and use them on next request but still don't have any solution for this. Please help me solution to how to store in environment and use this environment for next request? I have tried code below but it thrown an error about cannot read property 'lenghth' of undefined. Thanks a lot for your help
```
var data = JSON.parse(responseBody);
var len=data.content.length;
var envvar_akeyvalue=[]; 
var j=0; 
for (var i=0; i<len; i++)
  { 
  envvar_akeyvalue[j]=data.content[i].policyNumEncrypt; j=j+1; 
  } 
postman. setEnvironmentVariable("policyNumEncrypt", envvar_akeyvalue); 

```
`{
  "status" : "SUCCESS",
  "oErrorResult" : null,
  "clientNum" : "290338803",
  "formDataJson" : {"content":[{"mainStt":null,"policyNum":"70703570","mainProduct":"Phú - Tích Luỹ Định Kỳ","mainProductPreffix":"PHÚ","mainProductSuffix":"TÍCH LUỸ ĐỊNH KỲ","customerBuyName":null,"mobileNo":null,"email":null,"address":null,"mainPeopleInsurrancedName":"BY^~B PK++B K^'","statuspolicy":"HĐ đang hiệu lực","forceDate":"16/05/2003","deadlinepolicyDate":"15 năm","certificateDate":null,"timesPayFee":null,"periodCostFee":null,"periodTimeFee":null,"periodCostFeeNextDate":"16/05/2017","amountMoneyMain":5.0E7,"amountMoneyMainNo":null,"expiredpolicyDate":null,"peopleInsurranceds":null,"beneficiaries":null,"agencyServepolicys":null,"transactionHistories":null,"premiumAmount":3257200,"mainAmount":null,"loan":7500000,"policyOwner":"30122691","allowPayment":false,"amountJson":null,"productCode":null,"accumulatedInsurance":0.0,"currentPayback":0.0,"despathNum":"95059058","policyNumEncrypt":"uM0fvF65bGXxrI/WHhKzJwPaDQjKZPDV"},{"mainStt":null,"policyNum":"71695547","mainProduct":"Phú - TL Định Kỳ Gia Tăng","mainProductPreffix":"PHÚ","mainProductSuffix":"TL ĐỊNH KỲ GIA TĂNG","customerBuyName":null,"mobileNo":null,"email":null,"address":null,"mainPeopleInsurrancedName":"BY^~B PK++B K^'","statuspolicy":"HĐ đang hiệu lực","forceDate":"06/09/2006","deadlinepolicyDate":"12 năm","certificateDate":null,"timesPayFee":null,"periodCostFee":null,"periodTimeFee":null,"periodCostFeeNextDate":"06/09/2017","amountMoneyMain":1.1E7,"amountMoneyMainNo":null,"expiredpolicyDate":null,"peopleInsurranceds":null,"beneficiaries":null,"agencyServepolicys":null,"transactionHistories":null,"premiumAmount":1497300,"mainAmount":null,"loan":0,"policyOwner":"30122691","allowPayment":false,"amountJson":null,"productCode":null,"accumulatedInsurance":0.0,"currentPayback":0.0,"despathNum":" ","policyNumEncrypt":"nIpPBlh3/HZTrq/sL6Fzk2ICXzVPTkGw"},{"mainStt":null,"policyNum":"71883531","mainProduct":"Phú - An Gia Thành Tài","mainProductPreffix":"PHÚ","mainProductSuffix":"AN GIA THÀNH TÀI","customerBuyName":null,"mobileNo":null,"email":null,"address":null,"mainPeopleInsurrancedName":"BY^~B PK++B K^'","statuspolicy":"HĐ đang hiệu lực","forceDate":"16/09/2007","deadlinepolicyDate":"14 năm","certificateDate":null,"timesPayFee":null,"periodCostFee":null,"periodTimeFee":null,"periodCostFeeNextDate":"16/09/2017","amountMoneyMain":1.0E8,"amountMoneyMainNo":null,"expiredpolicyDate":null,"peopleInsurranceds":null,"beneficiaries":null,"agencyServepolicys":null,"transactionHistories":null,"premiumAmount":12677000,"mainAmount":null,"loan":0,"policyOwner":"30122691","allowPayment":false,"amountJson":null,"productCode":null,"accumulatedInsurance":0.0,"currentPayback":0.0,"despathNum":" ","policyNumEncrypt":"TL+aadfutyrXbCadnCC/tBACMjINRT5A"},{"mainStt":null,"policyNum":"72814030","mainProduct":"Phú-An Lộc","mainProductPreffix":"PHÚ","mainProductSuffix":"AN LỘC","customerBuyName":null,"mobileNo":null,"email":null,"address":null,"mainPeopleInsurrancedName":"M~ BK T^'B","statuspolicy":"HĐ đang hiệu lực","forceDate":"04/10/2012","deadlinepolicyDate":"29 năm","certificateDate":null,"timesPayFee":null,"periodCostFee":null,"periodTimeFee":null,"periodCostFeeNextDate":"04/10/2017","amountMoneyMain":1.0E8,"amountMoneyMainNo":null,"expiredpolicyDate":null,"peopleInsurranceds":null,"beneficiaries":null,"agencyServepolicys":null,"transactionHistories":null,"premiumAmount":12056000,"mainAmount":null,"loan":6389700,"policyOwner":"30122691","allowPayment":false,"amountJson":null,"productCode":null,"accumulatedInsurance":0.0,"currentPayback":0.0,"despathNum":" ","policyNumEncrypt":"bAIdrp66oU0ghIZ5xVyRfxHZkE/tk/VF"},{"mainStt":null,"policyNum":"72817828","mainProduct":"Phú-An Lộc","mainProductPreffix":"PHÚ","mainProductSuffix":"AN LỘC","customerBuyName":null,"mobileNo":null,"email":null,"address":null,"mainPeopleInsurrancedName":"M~ BK T^'B","statuspolicy":"HĐ đang hiệu lực","forceDate":"15/10/2012","deadlinepolicyDate":"29 năm","certificateDate":null,"timesPayFee":null,"periodCostFee":null,"periodTimeFee":null,"periodCostFeeNextDate":"15/10/2017","amountMoneyMain":1.0E8,"amountMoneyMainNo":null,"expiredpolicyDate":null,"peopleInsurranceds":null,"beneficiaries":null,"agencyServepolicys":null,"transactionHistories":null,"premiumAmount":11216000,"mainAmount":null,"loan":5944500,"policyOwner":"30122691","allowPayment":false,"amountJson":null,"productCode":null,"accumulatedInsurance":0.0,"currentPayback":0.0,"despathNum":" ","policyNumEncrypt":"r3e1eUppCHrIVgswtgHKVRzwG7sUroYo"},{"mainStt":null,"policyNum":"73351810","mainProduct":"Phú-An Lộc","mainProductPreffix":"PHÚ","mainProductSuffix":"AN LỘC","customerBuyName":null,"mobileNo":null,"email":null,"address":null,"mainPeopleInsurrancedName":"BY^~B PK++B K^'","statuspolicy":"HĐ đang hiệu lực","forceDate":"08/06/2015","deadlinepolicyDate":"26 năm","certificateDate":null,"timesPayFee":null,"periodCostFee":null,"periodTimeFee":null,"periodCostFeeNextDate":"08/06/2017","amountMoneyMain":1.2E9,"amountMoneyMainNo":null,"expiredpolicyDate":null,"peopleInsurranceds":null,"beneficiaries":null,"agencyServepolicys":null,"transactionHistories":null,"premiumAmount":167900000,"mainAmount":null,"loan":null,"policyOwner":"30122691","allowPayment":false,"amountJson":null,"productCode":null,"accumulatedInsurance":0.0,"currentPayback":0.0,"despathNum":" ","policyNumEncrypt":"cifzO98WK69rhoFN5QTru6TlPFYvT8xZ"},{"mainStt":null,"policyNum":"73748039","mainProduct":"Phú-Bảo Gia Thịnh Vượng","mainProductPreffix":"PHÚ","mainProductSuffix":"BẢO GIA THỊNH VƯỢNG","customerBuyName":null,"mobileNo":null,"email":null,"address":null,"mainPeopleInsurrancedName":"M~ BOY^B PK++BO","statuspolicy":"Hủy","forceDate":"28/11/2016","deadlinepolicyDate":"61 năm","certificateDate":null,"timesPayFee":null,"periodCostFee":null,"periodTimeFee":null,"periodCostFeeNextDate":"28/11/2016","amountMoneyMain":6.0E8,"amountMoneyMainNo":null,"expiredpolicyDate":null,"peopleInsurranceds":null,"beneficiaries":null,"agencyServepolicys":null,"transactionHistories":null,"premiumAmount":30000000,"mainAmount":null,"loan":null,"policyOwner":"30122691","allowPayment":false,"amountJson":null,"productCode":null,"accumulatedInsurance":0.0,"currentPayback":0.0,"despathNum":" ","policyNumEncrypt":"pmn5F27uwDHdmE1u0oXRntflXM5rlQh3"},{"mainStt":null,"policyNum":"73784162","mainProduct":"Phú-Bảo Gia Thịnh Vượng","mainProductPreffix":"PHÚ","mainProductSuffix":"BẢO GIA THỊNH VƯỢNG","customerBuyName":null,"mobileNo":null,"email":null,"address":null,"mainPeopleInsurrancedName":"M~ BOY^B PK++BO","statuspolicy":"HĐ đang hiệu lực","forceDate":"28/12/2016","deadlinepolicyDate":"61 năm","certificateDate":null,"timesPayFee":null,"periodCostFee":null,"periodTimeFee":null,"periodCostFeeNextDate":"28/12/2017","amountMoneyMain":6.0E8,"amountMoneyMainNo":null,"expiredpolicyDate":null,"peopleInsurranceds":null,"beneficiaries":null,"agencyServepolicys":null,"transactionHistories":null,"premiumAmount":30000000,"mainAmount":null,"loan":null,"policyOwner":"30122691","allowPayment":false,"amountJson":null,"productCode":null,"accumulatedInsurance":0.0,"currentPayback":0.0,"despathNum":" ","policyNumEncrypt":"o2riSlbzuUms7R8vUXsutxeDfGVYabtz"}],"totalPage":1,"pageSize":8,"pageCurrentView":1,"itemViews":[1],"maxItemViews":5}
}`

**Comment by SamvelRaja** [comment]
@phuctan139  This blog has the step by step procedure for storing and using an environment variable across requests.
http://blog.getpostman.com/2014/01/27/extracting-data-from-responses-and-chaining-requests/

And in your problem, `var len=data.content.length;` should be replaced with `var len=data.formDataJson.content.length;`

**Comment by tanpnguyen139** [comment]
@SamvelRaja 

THanks for your reply, it worked now, now I will has an array variable policyNumEncrypt, so how can I set it on next request since it is an array?

Here is my body for request 

`{
 "principle": "290338803",
 "formDataJson": {
   "policyNum" : "{{policyNumEncrypt}}"
   }
}`
