### ISSUE TITLE
Postman does not remember open tabs

### ISSUE THREAD

**Issue by Goltergaul** [a85/POSTMan-Chrome-Extension#4048]
## App Details:
```
Postman for Linux
Version 5.5.0
linux 4.11.11-041111-generic / x64
```

## Issue Report:
 1. This issue has been here since i switched from the browser extension to the native app
 2. Expected behaviour: When i have open tabs, close Postman and reopen Postman then the tabs should be restored. Instead all are gone.
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app): Upon starting postman i can see the following error in the console:
```
================================================================
     o
   (/) P O S T M A N
   ^

   Go to View -> Show Postman Console to check your script logs. 

================================================================
requester.js:278308 NOTE: Adding request 4a82fa39-be80-d98e-5dcf-7faebdda3609 to force fetch
requester.js:253228 Error sanitizing order for collection:  TypeError: Cannot read property 'push' of undefined
    at child.addRemoteRequestsToFetch (requester.js:278311)
    at child.sanitizeOrder (requester.js:253224)
    at requester.js:253022
    at child._processRequests (requester.js:253128)
    at requester.js:253002
    at IDBRequest.cursorRequest.onsuccess (requester.js:283868)
sanitizeOrder @ requester.js:253228
(anonymous) @ requester.js:253022
_processRequests @ requester.js:253128
(anonymous) @ requester.js:253002
cursorRequest.onsuccess @ requester.js:283868
sails.io.js:142 🌏 sync service connectivity initiated
sails.io.js:759 socket replaying queued commands
sails.io.js:142 🌏 connected to sync service.
```

Steps to reproduce the problem:
When i have open tabs, close Postman and reopen Postman then the tabs should be restored. Instead all are gone.

**Comment by SamvelRaja** [comment]
Thanks for bringing this to our notice, we are tracking this here :) https://github.com/postmanlabs/postman-app-support/issues/3202
