### ISSUE TITLE
[Feature Request] Make environment dropdown wider

### ISSUE THREAD

**Issue by mattdeluco** [a85/POSTMan-Chrome-Extension#4050]
Right now the environment selection dropdown box is around 40 characters wide.  I've got a lot of environments with a lot of detail in their names often exceeding the width of the dropdown.

It would be nice if the dropdown could be wider to accommodate longer names **or** if a tooltip would pop up displaying the full name.

The box displaying the current environment is even more narrow - around 30 chars.  It would be nice to have the tooltip feature there, too.

I'm using the Postman app v. 5.5.0 on macOS.

**Comment by callmeaatrey** [comment]
@mattdeluco You can try dragging the line that is there to the left of the environments dropdown to resize it if you want to view more details. Please feel free to re-open it if I misunderstood.

**Comment by mattdeluco** [comment]
Hah, amazing.

I checked to see if I could drag something wider, but was looking in all the wrong places.

Thanks!
