### ISSUE TITLE
import collections programatically into Postman app.

### ISSUE THREAD

**Issue by brpaz** [a85/POSTMan-Chrome-Extension#4053]
Hello.
Is there any way to import collections to programatically to the Postman App? I would like to create a script, that will fetch a couple of Postman collections from multiple sources and automatically import them to Postman App without the user having to import one by one. 

After some investigation I discovered everything is stored on the local storage.  I tried to open ithe "file__0.localstorage" using Sqllite browser and I can see some json contents but it  the data is saved as a BLOB and I dont really know how can edit it and even if it would work.

Any ideas?

Thank you.

**Comment by sivcan** [comment]
Hi @brpaz , we've been thinking about implementing a postman CLI with functionality aiming at a similar objective.
I'm adding this as a feature request and will keep you updated.

**Comment by sivcan** [comment]
There was a similar feature request raised here [#2691](https://github.com/postmanlabs/postman-app-support/issues/2691) 

You can follow the same. 
Closing this issue.
