### ISSUE TITLE
Import swagger.json cannot negotiate WWW-Authenticate: Basic

### ISSUE THREAD

**Issue by javabrett** [a85/POSTMan-Chrome-Extension#4054]
## App Details:
```
Postman for Mac
Version 5.5.0 (5.5.0)
```

## Issue Report:
Postman Import (e.g. of `http://someserver/swagger.json`) cannot negotiate a 401 `WWW-Authenticate: Basic` response from a remote server.  Ideally Postman would either allow pre-authentication, or on a Basic auth challenge launch a web-browser style Basic auth dialog, then continue with the authentication header in-place.

As a secondary bug (and perhaps fixable independently, if-so can split-out a new issue): Postman currently responds with:

> Failed to import data: Error response received from URL. Check the console for more.

... however nothing is logged to the Postman Console.  You need to sniff the traffic to see the 401. 

## Workaround
Fetch `swagger.json` using a web browser and basic auth, then use Import -> Paste Raw Text.

**Comment by sivcan** [comment]
If I understand correctly, you're trying to import a swagger file behind an authentication barrier. 
If so, postman doesn't support this yet.

Link import was designed to import unauthenticated links, this doesn't look like a feature we'll be supporting.
