### ISSUE TITLE
Generate response data similar to what we get in Postman in Newman

### ISSUE THREAD

**Issue by akki1997** [a85/POSTMan-Chrome-Extension#4055]
I have to run 3 post requests with image uploads. Hence use newman instead of postman. The requests are working fine. But the JSON file exported does not have the response data as fetched in Postman. I have to use newman as I want to run a large number of iterations with image uploads and Postman does not support it. 

Tried using -O but it didnt work.
I require the output in the following format

{
    "images": {
        "regions": [
            {
                "boxes": [
                    [
                        470.06292724609375,
                        138.97164916992188,
                        873.6117553710938,
                        667.187255859375
                    ]
                ],
                "class": "front_profile"
            }
        ]
    }
}

## App Details:

```
Postman for Windows

```

**Comment by sivcan** [comment]
Hi @akki1997 , this is an issue for Newman. 
Kindly report the same on the Newman Repo : [Newman Issues](https://github.com/postmanlabs/newman/issues)

Closing the issue here.
