### ISSUE TITLE
Variables used in POST requests not properly being substituted by data file values in collection runner

### ISSUE THREAD

**Issue by vamsi9993** [a85/POSTMan-Chrome-Extension#4056]
Hi,

I am trying to run a collection of requests in the collection runner that utilizes a data file in order to run tests. The bodies of each request is raw JSON using postman variables. An example of this is below:

{
   "uniqueId": {{uniqueId}},
   "clientReference": {
        "leadId": {{leadId}},
        "transactionId": {{transactionId}}
      }
}

My data files contain keys matching the variable names and have corresponding values, as shown below:
JSON:
{
   "uniqueId": "123456",
   "clientReference": {
        "leadId": "abc",
        "transactionId": "def123"
      }
}

 The values in the file are not properly substituting the variables in the request body. This happens with values which are only level 2 JSON objects (in this case, "leadId" and "transactionId")

After running the collection runner, the request body in iterations looks like below:

{
   "uniqueId": 123456,
   "clientReference": {
        "leadId": {{leadId}},
        "transactionId": {{transactionId}}
      }
}

Do I need to change my raw JSON to make it work? Please help !!!

I am using postman v5.5.0 for windows.

**Comment by sdnts** [comment]
Hey @vamsi9993, nested properties in the CSV aren't supported yet. Can you try moving the `transactionId` property to the root level and try again?
Also, the JSON file is an array of objects. I assume the JSON you gave me was a typo, but your JSON file would have to look like this to work:
```
[{
"uniqueId": "123456",
"leadId": "abc",
"transactionId": "def123"
}]
```

**Comment by vamsi9993** [comment]
Hey @madebysid , Yeah the JSON file was a typo, sorry for that.
If I keep the "transactionId" in root level, it works. Unfortunately, I can't change this as we will get this data from an upstream application in bulk. 

Is there any other solution/apps you would suggest to get this done?

**Comment by sdnts** [comment]
@vamsi9993 Maybe you could have a script that flattens the object you get from your upstream app?
