### ISSUE TITLE
How do I reuse my code when writing tests?

### ISSUE THREAD

**Issue by jmfayard** [a85/POSTMan-Chrome-Extension#4058]
## App Details:

```
Postman for Mac
Version 5.5.0
OS X 17.2.0 / x64
```

## Issue Report:

I have been using postman tests extensively, and came up with a set of little helper functions that fits perfectly my particular workflow. 

What has been annoying is that I found no better way than to copy/paste them in each and every request, which becomes very quickly annoying when you have to synchronize them. 

So today I was pretty excited to discover that Postman lets me now write code at the collection or the folder level.

https://www.getpostman.com/docs/postman/scripts/intro_to_scripts#execution-order-of-scripts

alas if I define a function at the folder or collection level, the function is not exported

![image](https://user-images.githubusercontent.com/459464/34844262-30a5b834-f711-11e7-9997-b67333d60192.png)

![image](https://user-images.githubusercontent.com/459464/34844269-38179efc-f711-11e7-9006-6140b1c89aa8.png)

Should I stick with copy/pasting for code reuse?

**Comment by kunagpal** [comment]
@jmfayard At the moment, context is not shared across collection/folder/request scripts, so you'll have to proceed with the above workaround for now. This would be a useful addition though, so I'm marking this as a feature request.

**Comment by mccannt** [comment]
+1 For better support for Code Reuse. 
This is currently a sticking point for many of our QE's at my company. A better approach here would definitely help adoption for developers and SDET's

**Comment by vkaegis** [comment]
@jmfayard @mccannt  Thanks for reporting this! Reusability of scripts is on our mid term roadmap. No ETA on this just yet, but we'll keep you updated. We'd also love to hear more about how you use scripts in your work, this would be of immense help in crafting a flexible solution. You can either write to us, or schedule a call at https://calendly.com/vineetk/userconvo.

**Comment by shamasis** [comment]
Now we have scripts at folder and collection level.

You can also set local variables using `pm.variables.set` in any of the scripts in run and it will be available through the run and only during the run. Functions cannot be set as variables. 

So, as a hack, you can write your function as string in a variable in collection script and eval them everywhere. The benefit from previous step is that it is defined in a script within your collection and is completely local. Over time, we would look into exportable modules.

See this sample collection: https://documenter.getpostman.com/view/33232/RWaNPmBa

**Comment by nidkil** [comment]
@shamasis I'm sorry, but I cannot see any example in the provided link how to use variables and eval to reuse code. Can you please point it out?

**Comment by sivcan** [comment]
@nidkil Hey, on opening the documentation just click on 'Run In Postman' 
![image](https://user-images.githubusercontent.com/12631777/47200059-11ac7180-d392-11e8-9bba-295492132d69.png)
 and then the collection should get imported in the postman app.
Then you'll be able to see the pre-request scripts as written by @shamasis in the app.

Like so:
![image](https://user-images.githubusercontent.com/12631777/47200025-f5a8d000-d391-11e8-9a1a-65f638f4efe2.png)

**Comment by nidkil** [comment]
Cool thx. Just to double check: Is this a temporary hack until the functionality is implemented properly?

**Comment by bkosborne** [comment]
Yes maybe this issue should be re-opened so first class support for such a feature could be implemented?

**Comment by BrambleRamble** [comment]
I second @bkosborne's comment. The workaround above is better than nothing, but it leaves a lot to be desired.

To give more detail, our particular situation involves making requests to a variety of different endpoints. There are different expectations about how long requests to different endpoints should take, and often requests to several endpoints belong in a folder together - so, adding a folder-level test isn't flexible enough.
In this situation, I'd like to build up a little toolset of tests that I often use (e.g. 'Searching cereals responds in under 1000ms', 'Getting a specific cereal's details responds in under 2000ms'), then pick and choose which ones to include on my individual requests.

**Comment by vbisrikkanth** [comment]
+1 This something that we would like to have as well.

**Comment by kunalfirstblood** [comment]
This feature will make life easy

**Comment by prusswan** [comment]
This will make the Visualize API with custom templates more useful. It does not make sense to duplicate the same template across tests since the templates have to be updated too at some point.

**Comment by NicholasSimons** [comment]
This is something I would like to have as well!!! :) :bird:

**Comment by dancerjohn** [comment]
Count me in as wanting this as well

**Comment by poddubitskya** [comment]
Come on guys, for a powerful tool like Postman this must've been done like yesterday

**Comment by aliciam** [comment]
We would also love to be able to set up a library of shared tests that can be called on when running tests over a collection. I'd prefer to organise my requests by endpoint, rather than set of tests that they need to run, and I know about the eval workaround but find it kinda icky tbh. 

Does anyone know if there is a feature request on any of the projects for this (I did a cursory look but couldn't find any)? and if not, which projects should this be in (or across)?

**Comment by ArchanaDontula** [comment]
Yes much needed feature
