### ISSUE TITLE
Postman works in GUI just fine. Does not from clipboard in my application (python)

### ISSUE THREAD

**Issue by jacree** [a85/POSTMan-Chrome-Extension#4059]
## App Details:

```
Postman for Chrome
Version 5.4.0
linux / x86-64
Chrome 63.0.3239.84
```

## Issue Report:
I'm trying to run the Postman App using the clipboard Python output from the body tab and I assumed I could do this in my own scripts. However only the Postman Gui works and having confirmed this. I get a return code of 200 or 202 something similar and I see my app executing. When I copy the clipboard and include, the endpoint app complains that it has received a gzip file (2.0-customer.csv below) or the files in the wrong format but I still get a return code of 202. The clipboard looks like the following:

import requests

url = "http://api-integration.vsm2m.net/import/upload/automatic/"

querystring = {"force":"true"}

payload = "------WebKitFormBoundary7MA4YWxkTrZu0gW\r\nContent-Disposition: form-data; name=\"user\"\r\n\r\nTest Operator\r\n------WebKitFormBoundary7MA4YWxkTrZu0gW\r\nContent-Disposition: form-data; name=\"password\"\r\n\r\nPassw0rd\r\n------WebKitFormBoundary7MA4YWxkTrZu0gW\r\nContent-Disposition: form-data; name=\"customers\"\r\n\r\n/home/harleyj700/apk2-sandbox/apk2-testing/2.0-customers.csv\r\n------WebKitFormBoundary7MA4YWxkTrZu0gW\r\nContent-Disposition: form-data; name=\"vending_machines\"\r\n\r\n/home/harleyj700/apk2-sandbox/apk2-testing/2.0-machines.csv\r\n------WebKitFormBoundary7MA4YWxkTrZu0gW\r\nContent-Disposition: form-data; name=\"products\"\r\n\r\n/home/harleyj700/apk2-sandbox/apk2-testing/2.0-products.csv\r\n------WebKitFormBoundary7MA4YWxkTrZu0gW\r\nContent-Disposition: form-data; name=\"inventory\"\r\n\r\n/home/harleyj700/apk2-sandbox/apk2-testing/2.0-inventory.csv\r\n------WebKitFormBoundary7MA4YWxkTrZu0gW\r\nContent-Disposition: form-data; name=\"force\"\r\n\r\ntrue\r\n------WebKitFormBoundary7MA4YWxkTrZu0gW--"
headers = {
    'content-type': "multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW",
    'cache-control': "no-cache",
    'postman-token': "f6f2d689-5694-82b1-3e91-983fe18d12fd"
    }

response = requests.request("POST", url, data=payload, headers=headers, params=querystring)

print(response.text)

If I run the code above in the postman GUI, everything is fine. Its only when its run inside my application, the endpoint application complains the files are in the wrong format, ie gzip file or something to that nature and I still get a code 202 back when I see the response.text. I'm running this inside a robot application which is basically a python function for the test suite I am putting together. The endpoint URL takes these 4 files as seen above in the body and goes to a SQL server, populates the table and then we sync it to the device over cellular. I don't have alot of visibility on that end unfortunately. I didnt see anything in the help that specifically addressed my issue hence the help request.

**Comment by sdnts** [comment]
Hi @jacree, if I understand correctly, the code generated by the app isn't working the way you expect, but the app itself sends the request correctly, right?
Currently, we use an external library to generate these, but we're working on a better way for you guys to contribute (using plugins) so that issues like this don't occur. I'll let you know here when such an option is available.

Unfortunately, until then, I can only recommend checking the `requests` module docs to see if the code we're generating is malformed. :(
