### ISSUE TITLE
raw Variables inside the body of a PSOT request are not being evaluated 

### ISSUE THREAD

**Issue by zmb5000** [a85/POSTMan-Chrome-Extension#4061]
## App Details:

```
Postman for Mac
Version 4.11.0
OS X 16.4.0 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:
 2. Expected behaviour:
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 4. Screenshots (if applicable)

I have a post request that requires my variables to be dynamically updated for the body of my POST request. The body is set to raw, and the variables are set to the environment. The variables are not being evaluated unless they are inside "", which is fine for 8/10ths of the variables, but 2/10ths are integers, and the variables are showing up in red once they are set with the delimiters ( {{var}} ). Is this still an ongoing bug?

**Comment by thecuriousdev** [comment]
@zmb5000 thanks for reporting this issue, You are using an older version of Postman app, Can you try updating the Postman app and check whether this issue is still occurring?

**Comment by zmb5000** [comment]
I'm using the current version of the local app. It's not evaluating the
variables for numbers and boolean values currently. If I use a string, it's
fine, but with other variable types, it still occurs.  I've sent pictures
to show you my current issue. I hope they are helpful in discovering the
issue.

**Comment by acemrek** [comment]
+1

**Comment by jackieta1** [comment]
I'm having trouble with it evaluating ANY variables inside Body (raw, JSON). I'm having to just hardcode for now. Strings don't work for me either. I'm running Mac version, 6.0.10

**Comment by thecuriousdev** [comment]
I tried it from my side and its working fine (see the screenshot). Try updating to the latest version (6.1.3+), and let me know still its occuring for you.
<img width="737" alt="screen shot 2018-05-31 at 3 41 24 pm" src="https://user-images.githubusercontent.com/22293666/40776700-22653704-64e9-11e8-9b22-239cc3734124.png">

**Comment by thecuriousdev** [comment]
Closing this issue for now, Feel free to reopen this issue if you are facing this issue in our latest version.

**Comment by hortom** [comment]
Hi,
With the latest 7.0.4 on mac, I see this issue. I try to use a global variable in a POST request body.
```
{
  "user": {
    "token": "{{accessToken}}"
  }
}
```

It doesn't work, regardless that I have a global variable `accessToken`. When I log with pre-script `console.log(request.data);` then it contains only the `{{accessToken}}` string and not the value of it.
Did I miss something?

**Comment by kaiyuan01** [comment]
This issue still exists in newest version 7.18.1. PLease fix it

**Comment by kaiyuan01** [comment]
Please re-open it as 7.18.1 still has this issue.

**Comment by kaiyuan01** [comment]
> I'm having trouble with it evaluating ANY variables inside Body (raw, JSON). I'm having to just hardcode for now. Strings don't work for me either. I'm running Mac version, 6.0.10

Same issue now.

**Comment by jeff812** [comment]
> Closing this issue for now, Feel free to reopen this issue if you are facing this issue in our latest version.

Seeing similar behavior within the latest version, Postman v7.21.1

Unable to use my integer variables that are being set via pre-request within the request body.
