### ISSUE TITLE
Collection with NULL name stops Team synchronizations

### ISSUE THREAD

**Issue by ShemrickFlannigan** [a85/POSTMan-Chrome-Extension#4062]
Postman for Windows
Version 5.5

Expected behavior:
App does not permit Collections with NULL names

Current behavior:
App permits Collections with NULL names. NULL name Collections prevent Team Collections and Environments from synchronizing, as well as individual Collections from being created or saved.

Steps to Replicate:
1. Confirm that the Team Collections & Environment are syndicating
2. Create a new Collection with a NULL name
3. Confirm that the Team Collections & Environment no longer syndicate

**Comment by thecuriousdev** [comment]
Hey @ShemrickFlannigan thanks for reporting this issue, Can you please provide steps to reproduce this problem?

**Comment by ShemrickFlannigan** [comment]
Yes, those Steps to replicate the issue have been added to the issue

**Comment by kamalaknn** [comment]
Hi @ShemrickFlannigan 

We've pushed fixes for this issue in our latest version. Please update to the latest version.
