### ISSUE TITLE
[BUG] Postman App (Win10) shows "Could not get any response" when the return code is large than 999

### ISSUE THREAD

**Issue by SitiSchu** [a85/POSTMan-Chrome-Extension#4063]
## App Details:
```
Postman for Windows
Version 5.5.0
win32 10.0.16299 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:
Has always been there
 2. Expected behaviour:
It should normally display the returned data
 3. Console logs
Postman console just shows `Error: Parse Error` for the Request.
 4. Screenshots (if applicable)
![image](https://user-images.githubusercontent.com/18517178/34899574-13b32ef2-f7fa-11e7-8027-969beeba5190.png)

## Steps to reproduce
Make a webserver respond a HTTP status code that is above 999.

It is not a Issue related to the server since the PyCharm REST API client returns the data just fine.

**Comment by numaanashraf** [comment]
@SitiSchu Thanks for bringing this to our notice. HTTP Status codes, as per the spec should be three digits - (https://www.w3.org/Protocols/rfc2616/rfc2616-sec6.html#sec6.1.1). So anything above 999 will be treated as invalid HTTP message and will lead to a parse error. At the moment, we have no plans to support status code behavior outside of the HTTP spec.
