### ISSUE TITLE
Postman 5.5 crashes my Windows 10 (Blue Screen of Death)

### ISSUE THREAD

**Issue by escoffie** [a85/POSTMan-Chrome-Extension#4065]
## App Details:

```
Postman for Windows
Version 5.5.0
win32 10.0.16299 / x64
```

## Issue Report:
 1. Earlier this week, my Windows 10 suddenly started to crash (BSOD) every now and then just after I give focus to Postman (already running).
 2. Expected behaviour: Windows should not crash when using Postman.
 3. Console logs not available.
 4. Screenshots:

![2018-01-10 09 08 12](https://user-images.githubusercontent.com/3408273/34909209-04376a3e-f862-11e7-93d4-7e335f7fc6ad.jpg)

In case is relevant, I have an Asus N56D with the following specifications:
Processor: AMD A8-5550M APU with Radeon Graphics 2.10 GHz
RAM: 8 Gb
Windows 10 Home 64 bits
OS Version: 10.0.16299 compilation 16299

I was using Postman for Chrome, but due to the end of life of this product, I switched to the Windows app about three weeks ago. I was working just fine for two weeks, and then my Windows started to crash when Postman app was maximized. 

I'm using Docker to run some containers under a Linux Virtual Machine. The containers are a mysql v 8.0, a php-fpm 7.1 and an Nginx Alpine, and I'm using those to run a RESTFul API I'm developing with Laravel.

The database design is very straightforward, two tables with a one to one relationship with 25 records each (nothing fancy). If I perform the requests using another client, for example, RESTClient for Firefox, I can work flawlessly (but no other client is as good as Postman).

If I run Postman, and start switching from application to aplication, for example, Postman to VS Code, then to Google Chrome or Firefox, back to Postman, etcetera, most of times it works just fine. But every now and then, suddenly, and only when switching back to Postman, my Windows crashes with a Blue Screen Of Death. I restart the machine, run my containers, open all my applications for my development environment, and when less expected, only when switching back to Postman, Windows crashes again.

I experienced this at least 10 times in the last week. Yesterday, 3 times un 2 hours. It happens more often after I run a migration refresh and seed ($ php artisan migrate:refresh --seed), but not always.

The BSOD messages vary between PAGE_FAULT_IN_NNPAGED_AREA, SYSTEM_THREAD_EXCEPTION_NOT_HANDLED and MEMORY_MANAGEMENT.

My Windows have been pretty stable before this week, and the last time I saw a BSOD was about 6 months ago. I insist, it only happens when I click on the Postman icon on the taskbar, one of about ten or twenty times.

Any help or advice will be very appreciated.

**Comment by thecuriousdev** [comment]
Hey @escoffie thanks for reporting this issue, Can you share your system's resource usage details, especially Postman's resource consumption?

**Comment by dayeggpi** [comment]
exactly the same issue here.
pretty stable system, no BSOD at all since beginning.
It only started once I installed Postman (software, not Chrome plugin).

Random crashes BSOD, even when I dont run Postman.

Variable BSOD reasons:
IRQL NOT LESS OR EQUAL
VIDEO SCHEDULER INTERNAL ERROR
KERNEL SECURITY CHECK FAILURE
SYSTEM THREAD EXCEPTION NOT HANDLED (Apsx64.sys)
MEMORY MANAGEMENT
SYSTEM SERVICE EXCEPTION
DRIVER IRQL NOT LESS OR EQUAL (igdkmd64.sys)

Happens randomly without particular behavior (browsing web mainly)

Windows 10 x64, on a laptop X1 Carbon up to date.
Can't really say about Postman consumption since it happens when I am not running it, but only started since I installed it.

**Comment by escoffie** [comment]
Hi @thecuriousdev,

Sorry it took me so long. As you can see, memory consumption seems to be very high. I just opened, with four tabs, but I didn't actually did any request. The first snapshot is from one minute after open Postman and the second one, after about five minutes. I didn't did nothing, just let it there.

Thanks for investigate this issue. 

![image](https://user-images.githubusercontent.com/3408273/35200796-b568a566-fed9-11e7-8346-5fa3bf11c729.png)

![image](https://user-images.githubusercontent.com/3408273/35200808-d8ffbce4-fed9-11e7-93c5-8852be3c20cc.png)

**Comment by escoffie** [comment]
I switched back to Chrome version and everything was fine again. Then I needed access to pm object to store some values in env variables, so I had to use the stand alone version again, and sadly after a couple hours, again giving focus to Postman (maximize it) causes a Blue Screen Of Death.

**Comment by sivcan** [comment]
@escoffie @hycday - Kindly update your native apps to the  [latest version](https://www.getpostman.com/apps) which addresses the high CPU usage issue. 
If you are still facing the issue in the latest version, feel free to reopen this issue.

**Comment by escoffie** [comment]
Hello @sivcan,

Sorry to reopen this topic, but I'm still geting BSOD in my system every time I use Postman stand alone app. Less often, but still getting those, and only if I have Postman running.

I've even changed my HDD for a SSD, wich made my system fast as never before, but still getting the same problem. 

A brief recall: It is an AMD A8 processor, with 8Gb of RAM, and an ATI Radeon HD 8750M with 2 GB. Now I have an SSD running my OS, a Windows 10 Home 64-bit. I'm using Docker and virtual box to run a few containers. And obvioulsy, the latest Postman version.

With the Postman's Chrome app I can work without any problem.

Nothing too fancy, I guess. What could that be?

Thanks in advance.

**Comment by cambiph** [comment]
I have the same problem. What info can I provide you with?

**Comment by bohogirl** [comment]
i still have this problem with the latest version,,
probably it only happen among AMD hardware?
i run it in AMD A8 4500M and R5 1600 both crash every few minus of usage,,
now iam going back to chrome postman,, everything works just fine

**Comment by sivcan** [comment]
@iswaraP @cambiph - Can you guys head over to this URL and try the solution provided here: 

1. https://www.getpostman.com/docs/v6/postman/launching_postman/installation_and_updates
2. Scroll down to **Troubleshooting Postman Updates** 

The latest version of Postman App as of now is **v.6.1.3**

**Comment by cambiph** [comment]
@sivcan seems to work for me, no BSOD so far ...
Thanks for the update.

**Comment by escoffie** [comment]
@sivcan Thanks for the update! I'm able to work with the app now without BSOD so far.

**Comment by 7azem-mos3ad** [comment]
@sivcan i am having this issue now what should i do to solve it

**Comment by flyingduck92** [comment]
I have the same issue please tell me how to solves this issue
