### ISSUE TITLE
Support custom auth headers for a folder

### ISSUE THREAD

**Issue by leon** [a85/POSTMan-Chrome-Extension#4066]
I'm trying to consume an api which doesn't use use a standard way of authentication, 
It instead relies on you sending two custom headers.

Access-Token: somesha1 
Client-Secret: somesha1

It would be great if you could add another option for the authentication letting you add arbitrary headers as a mean to authenticate.

This way I could add the headers to a folder and all requests in that folder would add the headers.
<img width="796" alt="screen shot 2018-01-09 at 15 58 56" src="https://user-images.githubusercontent.com/13211/34950287-fd7b711a-fa12-11e7-9493-fbb0224600e0.png">

**Comment by vdespa** [comment]
You could use variables in your request headers and set them properly in your pre-request script.

**Comment by numaanashraf** [comment]
@leon Thanks for the suggestion. This seems to be a highly requested feature and we are exploring ways to handle this use case.

For the mean time, you can use the workaround recommended by @vdespa. It does involve manually adding the header in your requests and then setting the value via folder pre-request scripts.

I'm closing this issue as a duplicate (#4044) for now.

**Comment by Chealer** [comment]
Thank you for this request
This was solved by the addition of an "API Key" type.
