### ISSUE TITLE
Curly braces variable in the pre-request script

### ISSUE THREAD

**Issue by luismospinam** [a85/POSTMan-Chrome-Extension#4067]
In previous versions of postman I was able to use an environment variable using the curly braces "{{variableName}}" in the pre-request script. in the new 5.5.0 version this won't work.

For instance, I define a "baseUrl" variable as an environment variable, I'm able to use that in the main URL script within curly braces ("{{baseUrl}}/events") and it works great, but if i try to use the pre-request script to make another request with pm.sendReques and use the same variable with curly braces it won't work.

Here it's the pre-request script I'm using:

`pm.sendRequest({
      url:  "{{baseUrl}}/events", 
      method: 'POST',
      header: [
        'Accept:application/json',
      ],
      body: {
          mode: 'raw',
         raw: JSON.stringify({});
});`

When i open the console i see that it is doing the request to '{{baseUrl}}/events' and not using the value of the 'baseUrl' variable, it should look something like this: 'localhost:8080/events'

**Comment by vdespa** [comment]
You should use the pm.* API for that.

For example

`var url = pm.variables.get('baseUrl') + "/events"`

and

`pm.sendRequest({ url: url, .....`

**Comment by numaanashraf** [comment]
@luismospinam Thanks for writing in. Curly braces syntax was never planned for the `pm.sendRequest` API and the initial support for the same was unintended. We have dropped support for it now and we recommend using `pm.*` API to use variables in your scripts as explained by @vdespa.
