### ISSUE TITLE
Exception Response is not Displayed by Postman

### ISSUE THREAD

**Issue by joshidp** [a85/POSTMan-Chrome-Extension#4068]
Hi,

Thanks for this wonderful tool.

When I send a request to ASP.NET WebAPI and get an exception I don't see any HTTP response in Postman like 500 error. I only see below message.

![image](https://user-images.githubusercontent.com/7415276/34970920-4c8b034e-fa9d-11e7-8c00-ec47b0d88a58.png)

Please let me know how to see raw HTTP response.

Thanks again.

**Comment by sivcan** [comment]
@joshidp - You can use the postman console. 
Inside Postman go to View > Postman Console.
Now send the request and you can see it inside the console.
Click on the drop down and now It'll show you the RAW in there. 

<img width="1615" alt="screen shot 2018-01-17 at 4 40 20 pm" src="https://user-images.githubusercontent.com/12631777/35039862-27cbcd14-fba5-11e7-9776-0ca83da082ca.png">


Hope this helps.

**Comment by vinsree** [comment]
Hi Team,

How to handle 'Request errors out' error in postman and continue running with the test script. Here collection stops and do not continue running remaining scripts
**Error: ESOCKETTIMEDOUT**

**Comment by vinsree** [comment]
Screen shot below:
![image](https://user-images.githubusercontent.com/23260753/60566687-fca23200-9daa-11e9-9657-6d2835bde50f.png)
