### ISSUE TITLE
when Duplicating a folder, the new folder contains duplicates of the requests

### ISSUE THREAD

**Issue by mtatrung** [a85/POSTMan-Chrome-Extension#4071]
## App Details:

```
Postman for Windows
Version 5.5.0
win32 10.0.16299 / x64
```

## Issue Report:
 1. Recently
 2. Expected behavior: 
Happens only on a shared collection, with at least one subscriber
When duplicating a folder (FolderA) , that contains:
CollectionA> FolderA > Red1, Req2, the newly created folder contains duplicates of the requests: CollectionA> FolderA copy > Red1, Req2, **Req1**, **Req2**
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 4. Screenshots (if applicable)
![image](https://user-images.githubusercontent.com/13434413/35015366-127e2600-fae2-11e7-90d4-49aa53a20150.png)

1. Create a Shared Collection for edit (**Collection A**), Folder (**FolderA**), and 2 requests underneath(**Req1**, **Req2**)
2. Have a person subscribe to the collection
3. Duplicate **FolderA**
Result: **FolderA copy** is created, but contains 4 requests instead of 2

**Comment by numaanashraf** [comment]
@mtatrung Thanks for reporting this. We are working on few improvements to our sync and collaboration features that should solve this issue. Thanks for your patience.

**Comment by cbarrerah-sogeti** [comment]
It's also happening with collections not shared:
![image](https://user-images.githubusercontent.com/24520879/36832104-7daa0d76-1d2a-11e8-9789-a1f7a792fb08.png)

![image](https://user-images.githubusercontent.com/24520879/36832113-88fdf46c-1d2a-11e8-9122-4dbeeba60693.png)
Adding small Gif for better example, first duplicating a collection -> Works as expected. Second duplicate the folder inside the same collection -> Duplicates appear.
![giftest](https://user-images.githubusercontent.com/24520879/36832626-851346b6-1d2c-11e8-961e-a9ee9f95bed8.gif)

**Comment by prashantagarwal** [comment]
@cbarrerah-sogeti Can you try this on the latest version of Postman App. We have quite a few improvements there.

**Comment by cbarrerah-sogeti** [comment]
It works now! thank you :)
