### ISSUE TITLE
Params within URL (not query string) are not written on a published doc

### ISSUE THREAD

**Issue by grrseguin** [a85/POSTMan-Chrome-Extension#4073]
## App Details:

```
Postman for Mac
Version 5.5.0 (5.5.0)
OS X 10.11.6 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:
Just noticed this after check [my publish Postman doc](https://documenter.getpostman.com/view/718322/hl2-panorama-api/7TGkEcB#7c0737f6-ae7e-ffc4-fce3-c402f59a6b59)

 2. Expected behaviour:
When writting parameters inside the URI like `:parameter`, it should be showed in the publish Postam doc on `//documenter.getpostman.com`.

 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
No relation with the Postman application.

 4. Screenshots (if applicable)
<img width="866" alt="documenter-postman-parameters" src="https://user-images.githubusercontent.com/5268254/35045595-a1814370-fb94-11e7-94bd-b8c7432862df.png">

**Comment by numaanashraf** [comment]
@grrseguin Thanks for reporting this. We are looking into this issue. /cc @godfrzero

**Comment by godfrzero** [comment]
@grrseguin Are you still seeing this issue?

**Comment by grrseguin** [comment]
yep!, why?

**Comment by godfrzero** [comment]
We had pushed out a fix for this. I'll check again.

**Comment by godfrzero** [comment]
This is what I see in your published documentation now:

![capture](https://user-images.githubusercontent.com/2700229/42612027-9887ca76-85b6-11e8-9741-1c827c061342.PNG)

Is this not what you expected?

**Comment by grrseguin** [comment]
It works on our postman doc too :+1:
(see. https://documenter.getpostman.com/view/718322/hl2-panorama-api/7TGkEcB#7c0737f6-ae7e-ffc4-fce3-c402f59a6b59)

Thanks!
