### ISSUE TITLE
Import from swagger using folders to group requests by tags

### ISSUE THREAD

**Issue by julianohsf** [a85/POSTMan-Chrome-Extension#4075]
## App Details:
```
Postman for Linux
Version 5.5.0
linux 4.10.0-38-generic / x64
```

## Issue Report:
I have so many requests in my API Docs using Swagger v2 JSON. 99% of them, starts with /api. When I imported it into Postman, all my requests started with /api was placed in a unique folder named api. It will so great if Postman had group my requests following the _paths.{path}.{httpMethod}.tags_ API Docs JSON property.

**Comment by numaanashraf** [comment]
@julianohsf Thanks for the suggestion. We are looking into this. 😄

**Comment by matthewsommer** [comment]
Hi, I was Googling how to import swagger paths into Postman folders and came across this feature request. Still being considered? Would be great to have!

**Comment by alxtr1bal** [comment]
Yes please, would be very interesting to have this.

**Comment by marcioamr** [comment]
This is an important feature when you share your postman with your documentantion

**Comment by dthompsonza** [comment]
I tried importing swagger.json into Postman for the first time today, and the first thing I found was that it was hard to find the requests I needed - everything is in the api folder...

Any idea when/if this feature will get done?

![image](https://user-images.githubusercontent.com/769513/47841470-67d1d980-ddc2-11e8-8760-8011113533c7.png)

Thank you

**Comment by clabnet** [comment]
Also me, same issue.

**Comment by adropofilm** [comment]
Any update?

**Comment by Trojaner** [comment]
All of my APIs were prefixed with /v1 and hence Postman grouped all of them in the "v1" folder.
The solution for me was to properly set baseUrl in the swagger.json.

**Comment by ghost** [comment]
Is there a way to do this yet?

**Comment by fionaom** [comment]
Any update on this?

**Comment by CowChris** [comment]
+1

I don't want to maintain a postman collection and a swagger config in order to achieve good house keeping.

**Comment by arlemi** [comment]
@CowChris As of Postman 7.25 you can use `tags` to organise your collections when importing an OpenAPI spec:

![import using tags for folders](https://aws1.discourse-cdn.com/business6/uploads/getpostman/original/2X/9/96b35b184c46985cd0b9a341db3b14a82ae83be9.gif)

Is that what you're looking for?

**Comment by CowChris** [comment]
> @CowChris As of Postman 7.25 you can use `tags` to organise your collections when importing an OpenAPI spec:
> 
> ![import using tags for folders](https://camo.githubusercontent.com/b214917ca1697f6715fb032f29d27c72e706c757/68747470733a2f2f617773312e646973636f757273652d63646e2e636f6d2f627573696e657373362f75706c6f6164732f676574706f73746d616e2f6f726967696e616c2f32582f392f393662333562313834633436393835636430623961333431646233623134613832616538336265392e676966)
> 
> Is that what you're looking for?

🤯  appears I was living in the past on version 6. Upgraded to 7, thanks!

And thanks for taking the time to make that visual.

**Comment by arlemi** [comment]
@CowChris You're in for a treat if you're just moving now from v6 to v7, a lot has happened since! I'll close this issue for now, feel free to open a new issue here or [on the community forum](https://community.postman.com/) if you have more questions. 😄
