### ISSUE TITLE
Postman for Windows fails to follow 307 with 'Automatically follow redirects on'

### ISSUE THREAD

**Issue by whippet-rider** [a85/POSTMan-Chrome-Extension#4077]
Postman for Windows (on Windows 7)
Version 5.5.0
win32 6.1.7601 / x64 

We are POSTing a file to an end point that has a temporary redirect present and it times out in Postman. Going through old testing logs it was working fine at the end of Nov 2017, can't say what version we were using of Postman at the time.

Fiddler shows that the 307 is returned with the new Location but Postman doesn't seem to pick it up.

**Comment by numaanashraf** [comment]
@paul3291 Thanks for reporting this. We are looking into this issue.

**Comment by whippet-rider** [comment]
:thumbsup:

**Comment by harryi3t** [comment]
@paul3291 
Can you try this test endpoint and share a screenshot of the output that you see?
Make a **POST** request to https://00353ed9-79ce-4edc-a4c9-284a4118d23e.mock.pstmn.io/redirect

Also, what type of data are you posting? (form-data, x-www-form-urlencoded, raw or binary)

**Comment by whippet-rider** [comment]
Hi @harryi3t ,
we are posting an image via form-data within postman.

no output from postman.
![image](https://user-images.githubusercontent.com/2818069/35200643-3672b4a8-ff66-11e7-84ad-0a28131f18d3.png)

Fiddler shows this..
![image](https://user-images.githubusercontent.com/2818069/35200655-60536cb8-ff66-11e7-9abd-3702bc0e2f3d.png)

Hope that helps.

Regards Paul

**Comment by harryi3t** [comment]
@paul3291 Thanks for the input. 
I could reproduce this. This is happening for only `form-data` body type.

Marking this as a bug. Will update this thread about the fixes.

**Comment by whippet-rider** [comment]
Thanks @harryi3t

**Comment by abhijitkane** [comment]
@harryi3t Is this scheduled with the next app release?

**Comment by harryi3t** [comment]
@abhijitkane @paul3291 This has been fixed in the latest version of the Postman v6.7.1
