### ISSUE TITLE
Async and Await linting errors for valid code

### ISSUE THREAD

**Issue by tarunlalwani** [a85/POSTMan-Chrome-Extension#4080]
## App Details:

```
Postman for Mac
Version 5.5.0
OS X 10.13.2 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:
Just tested, may have been there always

 2. Expected behaviour:
No linting errors for valid code
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
Not needed

 4. Screenshots (if applicable)
<img width="560" alt="capturfiles-20180119_125249" src="https://user-images.githubusercontent.com/5294143/35139131-c37c814a-fd17-11e7-83d6-c2164b00dc17.png">

Enter the below code in pre-request script

```javascript
        this.getJSON = async url => {
            if (url in cache) {
                return JSON.parse(cache[url]);
            }

            let res = await this.get(url);
            cache[url] = res.text();
            return res.json();
        };
```

**Comment by thecuriousdev** [comment]
@tarunlalwani thanks for reporting this issue, we'll look into this issue and keep you posted here.

**Comment by sivcan** [comment]
Hi @tarunlalwani - You can follow this thread https://github.com/postmanlabs/postman-app-support/issues/4131 for updates regarding support for async await.

Closing this issue.
