### ISSUE TITLE
Postman test script nested for loop persisting variable value

### ISSUE THREAD

**Issue by htmtester** [a85/POSTMan-Chrome-Extension#4081]
## App Details:
Postman for Windows
Version 5.5.0
win32 10.0.15063 / x64

## Issue Report:
I am facing an issue with nested for loops in my test script. My code is like this:

  for (var index = 0; index <= VAR1; index++) {
        //statements
        for (var index2 = 0; index2 <= VAR2; index2++)
        {
                //statements
         }
}

my issue is that the first loop executes correctly but on the inside loop the value of index2 is persisting and not changing to zero before execution
I have tried all I could (while loop, add a function not to nest the loops, delete the variable, declare before the block, assign value before and after the loop) but nothing changes, the value does not get back to zero not executing the loops as expected... any help please?

thanks in advance

**Comment by GrzegorzPi** [comment]
I can not confirm:

```
var max1 = 5;
var max2 = 6;
for (var index = 0; index <= max1; index++) {
//statements
console.log("new row" + index);

for (var index2 = 0; index2 <= max2; index2++)
{
    console.log(index2 + ", ");
//statements
}
}
```
works fine for me

Postman for Windows
Version 5.5.0
win32 10.0.16299 / x64

**Comment by sivcan** [comment]
@htmtester - Can you share the steps to reproduce this issue ?
Share the script maybe.

<img width="787" alt="screen shot 2018-01-19 at 10 09 46 pm" src="https://user-images.githubusercontent.com/12631777/35161208-863aac00-fd65-11e7-9a06-f0b0f5383cc1.png">

I wrote this script which is similar to yours and it works fine.

**Comment by htmtester** [comment]
Actually I missed a point when giving you guys the code to reproduce. When you use tests[index2 +'X'] = ANYVAR > 0 ; the issue happens. you must use the index of the for loop in the tests statement. can you take another look @sivcan ? thanks

**Comment by sivcan** [comment]
@htmtester I am unable to understand what you're trying to convey.
Can you share a code snippet of the script ?

I am not sure what you're trying to achieve. 

```
for(var i = 0; i < 10; i++) { 
   // code snippet 
}
```
Something like this^

**Comment by htmtester** [comment]
it would be something like this @sivcan 

for (var index = 0; index <= 10; index++) 
{
     tests[index + 'is the value of index'] = 3 == 2;
     for (var index2 = 0; index2 <= 20; index2++)
     {
           tests[index2 + 'is the value of index2'] = 3 == 2;
     }
}

I know these tests are supposed to fail. My point is that when using the value of the control variable of the for loop in a tests statement my scenario can be reproduced.

**Comment by sivcan** [comment]
@htmtester I am assuming that 'tests' is an object that you're checking.
And you're trying to generate a key using index + 'some character'
eg: `tests['1X'] or tests['2X']`

Is that so ?

Can you share the complete script that you've written ?
Exactly as you are using ?

Feel free to redact any information. 
It'll be easier for me to understand it and then I'll try to solve your problem.

**Comment by htmtester** [comment]
from postman documentation:

_Older style of writing Postman tests
The older style of writing Postman tests relies on setting values for the special tests object. You can set a descriptive key for an element in the object and then say if it’s true or false. For example, tests["Body contains user_id"] = responsebody.has("user_id"); will check whether the response body contains the user_id string._

I had to do a workaround in my code creating functions not to nest the for loops. But were you able to reproduce the issue?

My first approach using the index values on the tests object was to see if the loop was working as expected going through my JSON object.

**Comment by htmtester** [comment]
@sivcan if you can´t reproduce the issue even with my last code nevermind don´t wanna waste your time

**Comment by sivcan** [comment]
@htmtester -  It's okay man, the postman team is always here to provide support. 😄  

I'm looking into it. 
I'll get back to you in a bit.

You can  use the new method also to test your requests.

**Comment by sivcan** [comment]
@htmtester - What you're doing is that you're overwriting the key value pair of the 'tests' object.
Let's take this example : 

```
for(let index = 0; index < 2; index++) {
    tests[index + 'X'] = 3 == 2;
    for(let index2 = 0; index2 < 3; index2++) {
        tests[index2 + 'X'] = 3 == 2;
    }
}

console.log(tests);
``` 

This is the output : 
<img width="144" alt="screen shot 2018-01-23 at 1 13 42 am" src="https://user-images.githubusercontent.com/12631777/35240830-b38c3a30-ffda-11e7-80ad-82e46290b500.png">

If I change the inner index key now to this :
```
for(let index = 0; index < 2; index++) {
    tests[index + 'X'] = 3 == 2;
    for(let index2 = 0; index2 < 3; index2++) {
        tests[index2 + 'Y'] = 3 == 2;
    }
}

console.log(tests);
```

The following will be the output : 
<img width="175" alt="screen shot 2018-01-23 at 1 15 14 am" src="https://user-images.githubusercontent.com/12631777/35240934-f36cc8ea-ffda-11e7-97d5-9817efba4efa.png">

Now you'll ask me that the 'Y' values are not correct.
That's because again, the inner loop is overwriting the key-value pair of the object.

What you can simply do if you don't have a **unique id** for every test is generate a random one.
For the sake of simplicity I'll generate a random key using **Math.random()**

Now the code becomes this :
```
function generateRandomKey () {
    return Math.floor(Math.random() * 100);
}

let randomKey = generateRandomKey();

for (let index = 0; index < 2; index++)
{
      tests[index + ' X ' + randomKey] = 3 == 2;
      for (let index2 = 0; index2 < 4; index2++)
        {
            tests[index2 + ' Y ' + randomKey] = 3 == 2;
            randomKey = generateRandomKey();
        }
}

console.log(tests);
console.log(Object.keys(tests).length); // Checking the number of keys.
```

The following is the output : 
<img width="175" alt="screen shot 2018-01-23 at 1 24 34 am" src="https://user-images.githubusercontent.com/12631777/35241363-3f0fa8f2-ffdc-11e7-9d6e-281e71f4a16d.png">

**10** shows that my loops ran 4*2 times + 2 times. 

I hope this was what you were having an issue with. 

Let me know if you need any further assistance.

**Comment by GrzegorzPi** [comment]
You can just simply put both of index into test name for guarantee uniqe test name:

```
for(let index = 0; index < 2; index++) {
    tests[index + 'X, '] = 3 == 2;
    for(let index2 = 0; index2 < 3; index2++) {
        tests[index + 'X, ' + index2 + 'Y'] = 3 == 2;
    }
}
console.log(tests);
```

**Comment by htmtester** [comment]
thanks a lot

**Comment by sivcan** [comment]
@htmtester - No problem! 😄
