### ISSUE TITLE
How to pass the array value inside body of post request

### ISSUE THREAD

**Issue by pysurendra** [a85/POSTMan-Chrome-Extension#4082]
Hi Team, 

I have created a global array 
count = ["1","2","3"]
I am trying to pass the array inside body as following,
{
	"Data": [{
                     "count:" "{{count[0]}}"
                     },
                     {
                     "count:" "{{count[1]}}"
                     },
                     {
                     "count:" "{{count[2]}}"
                     }
            ]
}
                     
But I am getting error, May i know how to pass the array inside the body of request
```
Postman for Mac
Version 5.5.0 (5.5.0)
OS X 16.4.0 / x64
```

**Comment by GrzegorzPi** [comment]
You can save only string in global variable.

When you load something from global, it is string. You have to parse it do array in pre-request Script.
Save the whole data for body in variable.
Load whole body from variable.

parsing example:
count = ["1","2","3"]
```
var  count =JSON.parse(pm.globals.get("count"))
console.log(count[0]+"string");
```
console: "1string"

or

count = [1,2,3]
```
var  count =JSON.parse(pm.globals.get("count"))
console.log(count[0]+43);
```
console: "44"

**Comment by pysurendra** [comment]
Thanks for the reply, But how can I apply this to the body of the request which I mentioned above with my question

**Comment by sivcan** [comment]
Hi @pysurendra 

_Edit_
Solved in https://github.com/postmanlabs/postman-app-support/issues/4082#issuecomment-486072669

**Comment by amodmahajan2016** [comment]
@sivcan I think we can set body attributes directly from pre request script. 
pm.request.body["Data"] = countArr; // Adding the property to body.
Only read access we have in pre request script.

**Comment by donhathuy** [comment]
@sivcan I don't think this solution works for me.
It looks like pm.request.body can't set body data in Pre-Request script.

**Comment by sivcan** [comment]
@amodmahajan2016 @donhathuy Yeah, my bad. You guys are right, there's only read-access.
The way to send the array in the body would be this:

We'll have to make use of variables, I am using local variables but you can use any variable type. 

1. Your script should build the array and then stringify it and set it in a variable
```javascript
let count = ["1","2","3","4","5"],
    countArr = [];

for(let i = 0; i < count.length; i++) {
    countArr.push({ count : `${count[i]}` });
}

pm.variables.set('countArr', JSON.stringify(countArr)); // Adding the property to a variable which we will reference in the request body
```

2. Your request body should have the `{{countArr}}` without any quotes like so:
![image](https://user-images.githubusercontent.com/12631777/56634224-cfd0f080-667e-11e9-8e30-e9690556a9e8.png)

3. Fire it away!

**Comment by ghost** [comment]
There is a very simple way to do that and send an array throw postman:

By just passing the array like that.

![image](https://user-images.githubusercontent.com/49284931/100210414-3f6a2a00-2f0b-11eb-8d66-519e21f3bc6b.png)
