### ISSUE TITLE
I'm trying to import a file into Postman and receiving 'Failed to Import: Format not Reognized.

### ISSUE THREAD

**Issue by toddbeckum** [a85/POSTMan-Chrome-Extension#4084]
## App Details:

```
Postman for Chrome
Version 5.4.0
win / x86-64
Chrome 63.0.3239.132
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:
 2. Expected behaviour:
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 4. Screenshots (if applicable)

**Comment by toddbeckum** [comment]
When trying to import a json file from source control I received the message Failed to import data; format not recognized.
I was able to import a .json file similar to this 2 days prior.

**Comment by thecuriousdev** [comment]
@toddbeckum thanks for reporting this, It can be an issue with the JSON file that you are trying to import. Can you share a sample file here so that we can debug this issue

**Comment by thecuriousdev** [comment]
@toddbeckum since there is no response from your side, I assume that the issue got resolved. Please let me know if still occurs for you. Closing the issue for now.

**Comment by kaushik597** [comment]
{
	"variables": [],
	"info": {
		"name": "Multiple Iterations",
		"description": "",
		
	},
	"item": [
		{
			"name": "Request 1",
			"event": [
				{
					"listen": "test",
					"script": {
						"type": "text/javascript",
						"exec": [
							"if (iteration%2 === 0) {",
							"    tests[\"Status code is 401\"] = responseCode.code === 401;",
							"}",
							"else {",
							"    tests[\"Status code is 200\"] = responseCode.code === 200;   ",
							"}"
						]
					}
				}
			],
			"request": {
				"url": "http://localhost:8080/api/books/",
				"method": "GET",
				"header": [],
				"body": {},
				"description": ""
			},
			"response": []
		},
		{
			"name": "Request 2",
			"event": [
				{
					"listen": "test",
					"script": {
						"type": "text/javascript",
						"exec": [
							"tests[\"Status code is 200\"] = responseCode.code === 200;"
						]
					}
				}
			],
			"request": {
				"url": "http://localhost:8080/api/books/",
				"method": "POST",
				"header": [],
				"body": {
				    "title":"test"
				},
				"description": ""
			},
			"response": []
		},
		{
			"name": "Request 3",
			"event": [
				{
					"listen": "test",
					"script": {
						"type": "text/javascript",
						"exec": [
							"tests[\"Status code is 200\"] = responseCode.code === 200;"
						]
					}
				}
			],
			"request": {
				"url": "http://localhost:8080/api/books/",
				"method": "DELETE",
				"header": [],
				"body": {},
				"description": ""
			},
			"response": []
		}
	]
}



same issue as mentioned above
