### ISSUE TITLE
Unable to login to Postman - URGENT

### ISSUE THREAD

**Issue by serkand** [a85/POSTMan-Chrome-Extension#4086]
## App Details:
Postman for Windows
Version 5.5.0
win32 10.0.16299 / x64

## Issue Report:
Unable to login via the the window app or via the web (https://identity.getpostman.com/login).

In the Windows app, we don't get passed the sign in prompt. In the web, we get the "something went wrong" message. This is from Chrome developer tools console: 

login Failed to load resource: the server responded with a status of 500 (Internal Server Error)
login:320 
POST https://identity.getpostman.com/login 500 (Internal Server Error)
(anonymous) @ login:320

This is happening for everyone on my team, so its not user specific.

1) Login to Postman via Windows app or via the web

**Comment by kunagpal** [comment]
Hey @serkand, we're aware of the issue and are working to get things back to normal. 😄 
Live updates are available here: [status.getpostman.com](http://status.getpostman.com)

**Comment by kunagpal** [comment]
@serkand Things have now come back to normal. Feel free to revert if you're facing issues.
