### ISSUE TITLE
Ability to set collection based context url

### ISSUE THREAD

**Issue by tvvignesh** [a85/POSTMan-Chrome-Extension#4087]
This is inspired a bit from WSO2 API Manager. It will be nice if we could set a base url for a collection/folder (optional) and all the APIs within will have that as the Base URL without having the need to include the host environment variable to the url. 

All we would be needing to add is the relative path.

This is how WSO2 handles it.
![swapping-api-version-and-context-in-url](https://user-images.githubusercontent.com/1165845/35244221-762333fa-ffe5-11e7-8b0e-23e372e18b93.png)

**Comment by forresthopkinsa** [comment]
it looks like even 'WSO2' requires referencing a variable, just the same as you would in Postman

**Comment by tvvignesh** [comment]
@forresthopkinsa Nope. It does not require referencing a variable once set. It does it automatically (image below). Here, the Base URL is already made available once configured and we just have to enter relative paths.

![contextapi](https://user-images.githubusercontent.com/1165845/35290890-9ff7144c-0091-11e8-9249-6790f99b33f9.png)

**Comment by forresthopkinsa** [comment]
Okay, I see. Does this pose any advantages other than not having to type in the variable in the URL field?

**Comment by tvvignesh** [comment]
@forresthopkinsa Nothing specific. Just saves time of having to type in base url everywhere and managing it. Rather, all we have to do is specify a context url per collection and then just specify relative url for the rest. Easier to manage as well. Not a blocker or anything. Just a suggestion.

**Comment by prashantagarwal** [comment]
@tvvignesh Thanks for the suggestion. I think having url as variables open avenues for quite advanced use cases. I don't think we would be supporting this in any near future. Thanks again for bringing this up.
