### ISSUE TITLE
Ability to TAG items

### ISSUE THREAD

**Issue by tvvignesh** [a85/POSTMan-Chrome-Extension#4088]
What if you could add the ability to TAG collections, folders and APIs? It will help in organizing them and searching them. Having tags will avoid the need for having so many folders within a collection and will also help in filtering.

The tags can be added by the user and synced with the server.

**Comment by sdnts** [comment]
@tvvignesh Thanks for the feature request! We're actually working on a concept of workspaces which should behave the way you want. You would be able to organize collections/environments etc. by placing them in workspaces. This will be out on our Canary channel very soon.

You can download our Canary builds here:
OSX: https://dl.pstmn.io/download/channel/canary/osx_64
Windows 32-bit: https://dl.pstmn.io/download/channel/canary/windows_32
Windows 64-bit: https://dl.pstmn.io/download/channel/canary/windows_64
Linux 32-bit: https://dl.pstmn.io/download/channel/canary/linux_32
Linux 64-bit: https://dl.pstmn.io/download/channel/canary/linux_64

I'm closing this issue in favor of #3205, but please feel free to reopen if the Canary does not solve your use case.
