### ISSUE TITLE
API Network within postman

### ISSUE THREAD

**Issue by tvvignesh** [a85/POSTMan-Chrome-Extension#4089]
You guys have done a great job of adding [API Network](https://www.getpostman.com/api-network/).

Would be nice if API Network is browsable from within postman client rather than having to go to the website. You could add another tab to browse the network and run it within postman.

Also, would be nice if you could add a search bar in the website for API Network.

**Comment by prashantagarwal** [comment]
@tvvignesh We have already included API Network in Postman app itself. If you are on native app the click on `New` button on top left corner
<img width="1275" alt="screen shot 2018-01-23 at 2 06 20 pm" src="https://user-images.githubusercontent.com/3762808/35265645-b8045860-0046-11e8-9341-88a39d95f9c1.png">
