### ISSUE TITLE
Syncing takes a long time

### ISSUE THREAD

**Issue by bcodermicro** [a85/POSTMan-Chrome-Extension#4090]
## App Details:

```
Postman for Mac
Version 5.5.0 (5.5.0)
10.12.6
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there: REcently
 2. Expected behaviour: Sync Should Hapen in a few seconds but sync is taking forever...in the old chrome app version it syncs almost instantaneously.
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app): 
 4. Screenshots (if applicable)

**Comment by MarKco** [comment]
Hello,
I'm experiencing the same issue here as well, on both windows and mac :-/ Is something happening to the servers?

**Comment by MarKco** [comment]
I apparently solved the issue by logging out on both devices and cleaning data. I guess this was a data sync issue on the single machine.

I hope this helps!

**Comment by bcodermicro** [comment]
It appears just to be to an account using GLogin and not one which just logs on locally to their service....interesting

**Comment by granak** [comment]
Same issue here, using GLogin... still Syncing (postman opened all night), nothing was synchronized yet.

**Comment by bcodermicro** [comment]
Hopefully this will be dealt with....ver frustrating. I can go back to 5.4 chrome app but want to be on 5.5 all around.

**Comment by granak** [comment]
This got resolved for me in 5.5.2

**Comment by sdnts** [comment]
@bostonmacosx @granak @MarKco Are you guys still seeing this with the latest version?
We've been working on making the Sync layer a lot more stable recently. The upcoming version should have these changes, so that should solve most of these issues. I'll let you know here when the next version is out.

**Comment by kamalaknn** [comment]
Hi, 

We've pushed the fixes to our stable channel. Please update to the latest version. Let us know if the issue still exists.

**Comment by wizzed** [comment]
Writing this from v6.0.10, the syncing is causing problems for me, I'm not able to publish my collections properly because of the syncing issue.

**Comment by satnam-sandhu** [comment]
Using v6 worked fine at first but then taking forever to sync.

**Comment by arunb2255** [comment]
Hi , I am still facing this issue Version 6.7.4

**Comment by kamalaknn** [comment]
We've pushed some major improvements to syncing in Postman v7. Could you update your app to v7 and give it a try?

**Comment by arunb2255** [comment]
Hi I have updated it , but still it is taking time

**Comment by imadarif** [comment]
post take time to sync..

**Comment by ALTELMA** [comment]
2020, still facing with this problem . . .

**Comment by sattes-faction** [comment]
I'm also having this issue. The sync spinner is rotating forever. Already signed out and in again and restartet the system. Had no effect - and the syncing slows the app down so it's completely unusable.

**Comment by pkurczyna** [comment]
We do face it as well. Any plans for fixing that?

**Comment by arif2009** [comment]
2022, still facing with this problem . . .

**Comment by fadighattas100** [comment]
syncing not working properly, taking forever and it's finish and not sync everything !!!! and you can't do anything !!!
