### ISSUE TITLE
Postman not decompressing Brotli response

### ISSUE THREAD

**Issue by forresthopkinsa** [a85/POSTMan-Chrome-Extension#4091]
## App Details:
```
Postman for Windows
Version 5.5.0
win32 10.0.15063 / x64
```

## Issue Report:
 1. I've only now encountered this problem; it worked (and works) on the Chrome app version
 2. Expected behaviour: Postman decodes the `br` encoding just the same as `gzip`
 3. Console logs:

```
POST /api/graphqlbatch/
origin: https://www.facebook.com
user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36
content-type: application/x-www-form-urlencoded
accept: */*
accept-encoding: br
accept-language: en-US,en;q=0.9
cookie: ---
cache-control: no-cache
postman-token: 065d1ac1-6068-45ca-aea1-9fc10ec07329
host: www.facebook.com
content-length: 765

<body>

HTTP/1.1 200
status: 200
content-security-policy: ---
x-frame-options: DENY
x-xss-protection: 0
access-control-allow-credentials: true
access-control-allow-origin: https://www.facebook.com
access-control-expose-headers: X-FB-Debug, X-Loader-Length
expect-ct: max-age=10, report-uri="http://reports.fb.com/expectct/"
pragma: no-cache
vary: Origin,Accept-Encoding
access-control-allow-methods: OPTIONS
strict-transport-security: max-age=15552000; preload
content-type: application/json; charset=utf-8
x-content-type-options: nosniff
expires: Sat, 01 Jan 2000 00:00:00 GMT
cache-control: private, no-cache, no-store, must-revalidate
content-encoding: br
x-fb-debug: ---
date: Tue, 23 Jan 2018 04:48:51 GMT
connection: close
```

 4. Screenshot

![image](https://user-images.githubusercontent.com/4433153/35258754-d129d1f4-ffbe-11e7-99ff-1ccc4b818605.png)

For context, I'm spoofing a Facebook Messenger request.

If I set the `accept-encoding` header to `gzip` or `deflate`, it works fine. Additionally, the same request works perfectly from the Chrome app.

**Comment by lloiacono** [comment]
Same for me using the OSX app Version 5.5.2 (5.5.2)

**Comment by prashantagarwal** [comment]
@forresthopkinsa Thanks for suggesting this. We use a [third party module](https://www.npmjs.com/package/request) to make requests from native apps. I am afraid it doesn't support brotli yet. I will keep this issue open until we come up with some solution for this.

**Comment by twurm** [comment]
@prashantagarwal any thoughts on a work around?  It's been six months, and the upstream issue is still open without any updates.

**Comment by forresthopkinsa** [comment]
Recent updates on request/request#2866 reflect that Node will be shipping native Brotli support in their next release.

**Comment by blackbyte-pl** [comment]
Any update on that? request seems to support it now, but postman still not.

**Comment by TheBox193** [comment]
+1

**Comment by kframnes** [comment]
Version 7.12.0 ... same issue.

**Comment by billwurles** [comment]
It's been nearly two years since this issue was opened, and it still hasn't been fixed?

**Comment by arlemi** [comment]
This was fixed in the app from 7.16.0, please update and let us know if you're still having problems!

**Comment by den50000** [comment]
Still not working. I got Postman Console error "Error: [ReadHuffmanCode] invalid num_codes or space". If I turn off brotli compression it working properly.

**Comment by coditva** [comment]
Hey @den50000, sorry to hear that. Do you have any public URL I can try to reproduce this issue?

**Comment by yamin8000** [comment]
I think this issue should be fixed and reopened, I'm using postman 8.7.0, when response is compressed in brotli, data is loaded correctly but size of data is equal to uncompressed data even though Accept-Encoding is set to gzip, deflate, br by default and in response headers Content-Encoding is equal to br. I tried same request using browser and in browser it's compressed and has lower size/content-length.

**Comment by davy-137** [comment]
I have also encountered the same issue, Accept Encoding request headers contain "br" but then even API returns error as "Error: Decompression failed". Please help me in this...

**Comment by mrurb** [comment]
Can br please be removed from the default "Accept-Encoding" header until Postman supports brotli! Or add an option to disable brotli?
![image](https://github.com/user-attachments/assets/41f1df6c-9dc1-4939-bcdb-a2ac6fdbc10a)

This is quite frustrating to have to do workarounds just to change to gzip or other supported format.
