### ISSUE TITLE
[FEATURE PROPOSAL] Local sync in choosen folder (VCS integration)

### ISSUE THREAD

**Issue by Nindouja** [a85/POSTMan-Chrome-Extension#4093]
I want to put my postman collection and a sample environement in my version control system. I know postman sharing is cool and do a lot but if one API endpoint change any of its parameters from release A to B and I checkout from one to another, I need to do some more action before I can get my test working in postman. Postman is no aware of different version of local sources.

What i propose is that users can choose the output path to the local sync files (per file configuration with the ability to keep the default one for some). Or maybe duplicate the local synced files to the desired directory. This way, when I develop new feature I update my postman. **Postman automatically export the new collection to my project directory**. I commit everything. And when I checkout master again, postman is automatically resyncing it self to the local files.

This aproach may have some problem integrating with actual sync; like the cloud version continuously updated. But I think integrating postman in VCS would be an amazing thing !!

**Comment by sdnts** [comment]
Hi @BancarelValentin, if you're on the Pro plan, you can take a look at our GitHub integration. If I understand correctly, that would solve your issue. You can also restore collections to a previous state from within the app if you're on Pro.

If you're not on Pro, you can export a collection from the app at any time and commit those to a VCS. This is a manual process.

I'm closing this for now as VCS syncing is already supported. Please let me know if I misunderstood.

**Comment by Nindouja** [comment]
I tried the GitLab integration as I'm an user of GitLab in my company. But we are running a private instance of GitLab which doesn't seems to be integrated. So bad :/
