### ISSUE TITLE
Syncing does not work behind corporate proxy (via websocket)

### ISSUE THREAD

**Issue by olada** [a85/POSTMan-Chrome-Extension#4098]
## App Details:

```
Postman for Windows
Version 5.5.0
win32 10.0.14393 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there: 

According to other issues, it had been fixed in the past; however, I can observe that the bug still exists in the latest version.

 2. Expected behaviour:

After logging into the account, the application should sync with your account. However, no such connection can be established which seems to come from the corporate proxy. When you add the target location of the websocket, a different error log output can be seen because the name resolving will not work anymore. (see screenshots)

 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):

Following Screenshots of the console are of relevance:
Following log is created when starting Postman behind a corporate proxy.
![websocket_normal_error](https://user-images.githubusercontent.com/4869683/35332258-b359c4e8-010a-11e8-8c93-b59874ed53a9.png)

When adding wss://sync-xi.getpostman.com to the list of exceptions, following log can be seen:
![websocket_after_exception_in_proxy](https://user-images.githubusercontent.com/4869683/35332454-4a92e0b0-010b-11e8-945c-77cf8d419ed7.png)

**Comment by sdnts** [comment]
Hi @olada, this is a known issue. Our Sync layer is built on top of WebSockets, and some corporate proxies do not allow WebSocket connections. Does your proxy/firewall allow this?
If not, I'm afraid there's little we can do.

I'm closing this for now, but please let me know if WebSockets are allowed and Sync still does not work :)

**Comment by olada** [comment]
Hi @madebysid,

in previous versions (where Postman was still a Chrome App, Syncing has definitely worked).
However, in the deprecated Chrome App version, it also does not work anymore.

So if the actual sync mechanism has not changed (and worked via websockets previously), the corporate proxy / firewall should not be the issue here (unless their policy changed of course)

For what it's worth, here is the version info of the Chrome App which I have tried where it does not work as well:

Postman for Chrome
Version 5.5.1
win / x86-64
Chrome 63.0.3239.132.

**Comment by AuldinSolutions** [comment]
I am having the same issue at my work.  But I assert there is something you can do... change the sync mechanism to use a more universally accepted protocol that is not blocked by corporate proxies such a HTTP.

**Comment by etgauthier** [comment]
This is so bad that Postman doesn't provide an HTTP base alternative and forces the websocket thing. I have been stuck using the deprecated Chrome app for ages because of this.
