### ISSUE TITLE
Can't handle big response

### ISSUE THREAD

**Issue by rawaludin** [a85/POSTMan-Chrome-Extension#4099]
My API have this response https://gist.github.com/rawaludin/1c0c988b155a6de56fc7d096804a8f50

I could get the response on curl on terminal and insomnia app. But postman give me error.

<img width="1278" alt="screen shot 2018-01-24 at 10 08 02 pm" src="https://user-images.githubusercontent.com/1274849/35339396-13e91abe-0153-11e8-915d-1956a96dec26.png">

**Comment by Rob-DeRosia** [comment]
Your response isn't that large. Have you tried the steps listed under the **Why this might have happend** section? My guess is that you will need to disable the SSL setting.

**Comment by numaanashraf** [comment]
@rawaludin Can you open the Postman Console (Menubar > View > Show Postman Console), resend the request and verify if you have any errors there?

**Comment by rawaludin** [comment]
@numaanashraf that one help me. It show `Error: The header content contains invalid characters`

You might want to suggest user to show this console when error happened. Thanks!
