### ISSUE TITLE
New feature: syntax highlighting for json/xml response body contents

### ISSUE THREAD

**Issue by sergionalin** [a85/POSTMan-Chrome-Extension#41]
One can easily live without that, but it would be nice :)
If you deem this interesting, consider using something like prettify.js (http://code.google.com/p/google-code-prettify/).

**Comment by yanicakj** [comment]
@a85 Syntax highlighting was always working then all of the sudden it stopped... could there be any specific reason why JSON responses are no longer being highlighted? (macos native Postman)
