### ISSUE TITLE
Bulk Edit loses Descriptions 

### ISSUE THREAD

**Issue by Cloud-RF** [a85/POSTMan-Chrome-Extension#4102]
## App Details:
```
Postman for Linux
Version 5.5.0
linux 3.16.0-38-generic / x64
```

## Issue Report:
When switching methods from 'form-data' to 'x-www-form-urlencoded', the bulk edit tool allows copy-pasting of rows of data. It doesn't carry over the description column so all my description fields are gone now and must be re-written, row by row.

**Comment by sdnts** [comment]
@Cloud-RF, While I cannot promise a release date yet, we've been working on some improvements to the data editor in the app, and will take this use case into consideration.

**Comment by numaanashraf** [comment]
Bulk edit option is deprecated and are being removed since v6.2 and we are working on enabling bulk edit based workflows on the main editor itself. We are tracking this change at #4898.
