### ISSUE TITLE
Bug with OAuth 2 authorization.

### ISSUE THREAD

**Issue by TomRed97** [a85/POSTMan-Chrome-Extension#4104]
## App Details:

```
Postman for Windows
Version 5.5.2
win32 10.0.10586 / x64
```

In the previous version when you choose Authorization -> OAuth 2.0 -> click get new access token -> use token, it appears in your url 
After last update when you click get new access token then when you click use token , you have to click it several times and then it doesn't appear in url. It sounds like several windows are created but not destroyed.

**Comment by callmeaatrey** [comment]
@TomRed97 I'm sorry you had to witness this issue. But, good thing is that we already accounted for this fix in the upcoming release. Feel free to open the issue again if it still persists after that.

**Comment by TomRed97** [comment]
Thank you.
