### ISSUE TITLE
Incorrect folder order on sync

### ISSUE THREAD

**Issue by sdauwalder** [a85/POSTMan-Chrome-Extension#4109]
## App Details:

```
Postman for Windows
Version 5.5.2
Win7 x64
```

## Issue Report:
2 synced accounts have different order of the folder of a collection

**Comment by sdnts** [comment]
HI @sdauwalder, we've been working on making the Syncing process a lot more stable. These improvements will land with the next version very soon, so can you check then if issues like this reappear? I'll let you know here when the next version goes out.

**Comment by prashantagarwal** [comment]
@sdauwalder Please update you app to the latest version. If you still see this issue, feel free to reopen this.
