### ISSUE TITLE
Latest online docs layout has broken some features

### ISSUE THREAD

**Issue by ghost** [a85/POSTMan-Chrome-Extension#4110]
This is an issue with the latest online documentation.

I've written all of my documentation to allow users to link back to key pieces of information such as the authentication process for each request by clicking on a link in the explanation of that request.

This was based on the documentation that postman itself had for it's own api's;
https://docs.api.getpostman.com/?_ga=2.234138839.812167779.1516899458-219127695.1499260595

The different sections under 'introduction' are now gone and I can no longer link to those sections from other areas of my documentation.

**Comment by godfrzero** [comment]
Could you shoot an email to help@getpostman.com if you haven't already, with a link to your documentation? I'm not seeing the same problem on other docs we're hosting, so this might be something specific to your collection. I'll know for sure once I take a closer look.

**Comment by ghost** [comment]
Apologies @godfrzero, it's actually only the  documentation i.e. when you log in to your account and view the docs from there.
It's not an issue on the public docs, the style there hasn't changed.

This only changed in the last week or so.
I'll email on links and screenshots anyway.

**Comment by godfrzero** [comment]
Ah, okay. I'm guessing you're using the `======` header syntax in your markdown description rather than the `#`. This is a known bug in how we're parsing the markdown and we'll be pushing out a fix for it in the next day or two.

In the meantime, if this is critical, using the `#` syntax should fix your links. I'll post here once we've pushed out the fix.

**Comment by ghost** [comment]
I'm using the h1 tags e.g. `<h1>Authentication</h1>` which used to to add an id to the <h1 tags that it rendered.
When I manually inject the id into the HTML it works.
It used to also output a list under the introduction and above the endpoints which it no longer does.
The list had a class of "toc". It seemed to just pick up all of my `<h1>` tags.

**Comment by godfrzero** [comment]
Right, the fix we're pushing out should take care of this too. 👍

**Comment by ghost** [comment]
Great. Thank you.

**Comment by godfrzero** [comment]
We've pushed out a version which should fix this issue, could you take a look and confirm? Cheers.

**Comment by ghost** [comment]
Issue resolved. Thank you.
