### ISSUE TITLE
Folders Pre-Request Scripts blank in dark theme

### ISSUE THREAD

**Issue by joeyciechanowicz** [a85/POSTMan-Chrome-Extension#4112]
## App Details:
```
Postman for Mac
Version 5.5.0
OS X 16.7.0 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there: Not present on the default theme, and not present on a collections pre-request scripts. Only a folders.
 2. Expected behaviour: You can see your pre-request scripts for a folder
 3. Console logs: n/a
 4. Screenshots (if applicable):
Before:
![image](https://user-images.githubusercontent.com/1148637/35448487-5840924a-02b2-11e8-9853-327a0c799d31.png)

After clicking:
![image](https://user-images.githubusercontent.com/1148637/35448508-65e537d4-02b2-11e8-87c2-9709bb16f679.png)

The scripts are actually present and do run, however when opening up the edit box on a folders pre-request script they are the same color as the background. Clicking anywhere highlights them

**Comment by sdnts** [comment]
Hi @joeyciechanowicz, thanks for reporting this. I was able to reproduce this. This isn't related to the theme you are in, I can see this on the light theme as well.

I'll get this fixed in an upcoming version.

**Comment by prashantagarwal** [comment]
@joeyciechanowicz This issue is fixed in latest version of Postman app
