### ISSUE TITLE
Postman converts Request Headers to lower case when running test scripts

### ISSUE THREAD

**Issue by vinogradoff** [a85/POSTMan-Chrome-Extension#4113]
## App Details:

```
Postman for Windows
Version 5.5.2
win32 6.3.9600 / x64
```

## Issue Report:
1. Send any GET request with Header "Content-Type: abc"
2. Write tests

```
tests["unchanged headers"]= request.headers["Content-Type"] == "abc";
tests["changed to lower case headers"]= request.headers["content-type"] == "abc";
```
-> Results:
FAIL
PASS

Expected: don't change headers, so:
PASS
FAIL

**Comment by prashantagarwal** [comment]
@vinogradoff Thanks for reporting this.

**Comment by harryi3t** [comment]
@vinogradoff The globally available `request`object (along with other objects) is deprecated. Please use the [pm API](https://www.getpostman.com/docs/postman/scripts/postman_sandbox_api_reference).
There's a method `get` on pm.request.headers which takes case-insensitive header name
```js
pm.request.headers.get('Content-Type') === pm.request.headers.get('content-type')
```

But if you want to check for the case also, you can convert the headers to JSON and then search for the key.
```
```

**Comment by harryi3t** [comment]
@vinogradoff The globally available `request`object (along with other objects) is deprecated. 

Please use the [pm API](https://www.getpostman.com/docs/postman/scripts/postman_sandbox_api_reference) instead.
There's a method `get` on `pm.request.headers` which takes case-insensitive header name
```js
pm.request.headers.get('Content-Type') === pm.request.headers.get('content-type')
```

But if you want to check for the case also, you can convert the headers to JSON and then search for the key.
```js
_.find(pm.request.headers.toJSON(), {key: 'content-type'}) // null
_.find(pm.request.headers.toJSON(), {key: 'Content-Type'}) // {key, value, description}
```

Now your test case can be
```js
let headers = pm.request.headers.toJSON(),
    unChangedHeader = _.find(headers, {key: 'Content-Type'}),
    changedHeader = _.find(headers, {key: 'content-type'});

tests["unchanged headers"]= unChangedHeader && unChangedHeader.value === "abc";
tests["changed to lower case headers"]= (changedHeader && changedHeader.value) === "abc";
```

There's another way to achieve this. You can convert the headers to an object [while passing extra argument for case-sensitivity](http://www.postmanlabs.com/postman-collection/PropertyList.html#toObject).
```js
let headers = pm.request.headers.toObject(null, true); // 2nd argument for case-sensitive
tests["unchanged headers"]= headers["Content-Type"] == "abc";
tests["changed to lower case headers"]= headers["content-type"] == "abc";
```
