### ISSUE TITLE
Add ability to change indentation size in settings

### ISSUE THREAD

**Issue by andreypolyak** [a85/POSTMan-Chrome-Extension#4117]
## App Details:
```
Postman for Windows
Version 5.5.2
win32 6.1.7601 / x64
```

## Issue Report:
Postman by default use 4 spaces for auto indentation (Ctrl+B). I cannot find any place in settings where it can be reduced to two spaces. Can it be added to settings?

![image](https://user-images.githubusercontent.com/7446762/35470229-6214a83e-0356-11e8-883a-64b0f3a1096e.png)

Thanks,
Andrey

**Comment by prashantagarwal** [comment]
@andreypolyak Thanks for suggesting this.

**Comment by andriisivak** [comment]
please, add the ability to change indentation size and tabs / spaces

**Comment by matt-usurp** [comment]
Bump, this feature would be really handy. Currently the 4 space indentation is not ideal for users who are working on laptops (or use small window sizes) when working with data structures with more than 3-4 levels.

This feature would be ideal for the Beautify functionality mentioned above and also the response rendering in the `pretty` panel.

**Comment by sagar-gavhane** [comment]
+1

**Comment by sagar-gavhane** [comment]
+1

**Comment by mrdulin** [comment]
+1

**Comment by Enchiridion** [comment]
+1

**Comment by luisdaglez** [comment]
+1

**Comment by stevenaw** [comment]
Possible duplicate of https://github.com/postmanlabs/postman-app-support/issues/2905 ?

**Comment by diego-f-alcantara-z** [comment]
+1

**Comment by mrdulin** [comment]
+1 

P.S. Add simple code IntelliSense and autocompletion, it will be great!

**Comment by marklofdahl** [comment]
+1

**Comment by chadwtaylor** [comment]
+1

**Comment by justclint** [comment]
+1

**Comment by rudisills** [comment]
+1

**Comment by krass1251** [comment]
+1

**Comment by breart** [comment]
Any ETA on this feature? It's been more than a year since it was created.

**Comment by AuthorProxy** [comment]
Any updates on this future? We waiting for this so long..

**Comment by brewmanz** [comment]
How hard can it be to add File - Settings - General - Tab size ?

**Comment by gstokkink-bex** [comment]
+1

**Comment by trystero11** [comment]
+1 from me, too.

**Comment by marekmajerski** [comment]
:+1:

**Comment by aleksandraban** [comment]
👍

**Comment by botond-rostas** [comment]
👍

**Comment by ArmandoAssuncao** [comment]
+1

**Comment by vsachini** [comment]
+1

**Comment by balbesina** [comment]
+1

**Comment by pankajk07** [comment]
@andreypolyak With the new release (`v7.31`), we have added few settings to customize the editor, including the ability to change the indentation size. Please try it out. We would love to hear your feedback.

**Comment by moberemk** [comment]
@pankajk07 FYI, I just changed indentation to two space; it seems it seems like it works as expected in the `body` pane when you hit beautify immediately when you change the settings but it doesn't seem to take effect in the response pane's `Pretty` view until after you reload the app. Doesn't seem to be a major issue, likely just some bad caching, but something to note--feature works great otherwise!

**Comment by andreypolyak** [comment]
@pankajk07 I set indentation count to 2:
![image](https://user-images.githubusercontent.com/7446762/92107789-07ad8380-edef-11ea-8823-288fd6af0428.png)
But for some reason when I try to beautify XML I get 4 spaces.
Before beautifying:
![image](https://user-images.githubusercontent.com/7446762/92107901-2f9ce700-edef-11ea-9a80-1435a4de3916.png)
After:
![image](https://user-images.githubusercontent.com/7446762/92107919-37f52200-edef-11ea-8122-f5236f89c7f6.png)

**Comment by pankajk07** [comment]
@andreypolyak Thanks for reporting this issue. We were able to reproduce it and tracking this internally. Also tracked in here https://github.com/postmanlabs/postman-app-support/issues/9024
