### ISSUE TITLE
API to export config data for backups 

### ISSUE THREAD

**Issue by connorsadlervelo** [a85/POSTMan-Chrome-Extension#4123]
## App Details:

```
Postman for Mac
Version 5.5.0
OS X 16.7.0 / x64
```

## Issue Report:
Is there a way or please could you create a way to allow me to export Postman config settings by running a script or making an API call?
I would like to backup my project files myself by copying files on my file system.
I do not wish to use online services as the data may be sensitive.
I raised this with support and they suggested "regularly exporting app data via "Settings">"Data">"Download" as that will give you a single file you can reimport at any time"
I would like to automate this please
I used soapUI in the past and you can just copy the project .xml file to backup your work.
Thanks

**Comment by sdnts** [comment]
Hi @connorsadlervelo, we do have a web API for this, but as you do not wish to use Sync, this will obviously not work.

I believe what you want is very similar to #2691, so I'd recommend you follow that thread for updates! Basically, a CLI tool to allow you to interact with the app is something we're working on. When it does go out, you should be able to write a script then.

Please let me know if I misunderstood, and I'll reopen this :)

**Comment by connorsadlervelo** [comment]
@madebysid Yep a CLI would be great - thanks for linking it
