### ISSUE TITLE
Sync/Duplicate random new endpoints / changes not saved

### ISSUE THREAD

**Issue by sharq88** [a85/POSTMan-Chrome-Extension#4125]
Hi.

Not sure why this happening, but this is very annoying... Just duplicated a folder and since then the app behaves very weird! Done this before, but never had any issue... now things randomly disappear and new endpoints created out of the wild! 

## App Details:
Postman for Mac
Version 5.5.2 (5.5.2)
OS X 10.12.6

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there: Only today first time
 2. Expected behaviour: To work correctly
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app): 
 4. Screenshots (if applicable)
![image](https://user-images.githubusercontent.com/2893497/35521388-7de5cf9a-0511-11e8-9b15-740d088f185c.png)

Steps to reproduce the problem: No specific way to reproduce it, as it does things randomly. I suspect it's related to duplication and syncing. Eg: It added/duplicated 25 new endpoints while I was browsing in chrome...

**Comment by rorysmorris** [comment]
Can confirm this is happening on a fresh install of Postman for me too.

**Comment by sharq88** [comment]
More accurate way of reproduction: duplicate a non-empty folder in a shared collection (team lib)
Duplication is quite important functionality if you have an existing codebase. Is there any way to get looked at this? 

@numaanashraf - Sorry for pinging you directly. Found your comment in regards of downgrading the app. I'm thinking on it as I have not seen this problem before.

**Comment by sharq88** [comment]
Tried to downgrade the app to 5 different versions down to 5.0.2 all versions produces the same problem as described above - which makes me think the problem is with the sync, not the app itself.

**Comment by iamcam** [comment]
My STR:
1. Subscribe to a team library
2. Select a folder containing requests
3. Duplicate the folder
4. Observe the new folder has all the containing requests duplicated (ie, two of each request).
5. Ask teammates if they see what you see.
6. Observe some will see empty requests. others may see what you see.

One work-around is to unsubscribe and re-subscribe to the library to get the data/syncing sorted out.

**Comment by sdnts** [comment]
@sharq88 @rorysmorris @iamcam, Sorry for the delay here. We've made major improvements to the way the app syncs with our servers on our Canary channel. Issues like these should be solved ideally.

Can you guys please try to reproduce this on the Canary build and check if you still see this? Let me know if you do.

Canary builds:

[OSX](https://dl.pstmn.io/download/channel/canary/osx_64)
[Windows x86](https://dl.pstmn.io/download/channel/canary/windows_32)
[Windows x64](https://dl.pstmn.io/download/channel/canary/windows_64)
[Linux x86](https://dl.pstmn.io/download/channel/canary/linux_32)
[Linux x64](https://dl.pstmn.io/download/channel/canary/linux_64)

**Comment by kamalaknn** [comment]
We've pushed some major improvements to the data layer and sync layer. This issue should be fixed npw. Please update to the latest version and let us know if it still exists.
