### ISSUE TITLE
Feature request: Globally assignable GET parameters

### ISSUE THREAD

**Issue by poisa** [a85/POSTMan-Chrome-Extension#4126]
Take pagination and search for example. In my case, 99% of my API endpoints contain the same pagination and search options (which are of course optional). It would be great if I could define these in a global place and then assign these parameters to any requests that I like.

This would save me from having to copy/paste these GET parameters in all my other -hundredths- of endpoints and will also allow me to mass update their documentation (when I change the global parameter description it would update all the endpoints that use it)

**Comment by sdnts** [comment]
Hi @poisa, have you taken a look at environment variables? You can define an environment variable with your common search options and use this everywhere. Now when you update this environment variable, all requests will automatically use the new values. Moreover, when viewing documentation, you can select this environment to resolve all requests in the documentation using the environment variable's value.

Here are some docs to get you started:
https://www.getpostman.com/docs/postman/environments_and_globals/variables
https://www.getpostman.com/docs/postman/environments_and_globals/manage_environments

I'm closing this, but please let me know if I misunderstood, and I'll reopen

**Comment by poisa** [comment]
Hi @madebysid. I am aware of environments an variables (and use them extensibly). They don't cover this particular scenario though, or at least I don't think they do.

Take this simplified example:

![screen shot 2018-02-20 at 1 20 32 pm](https://user-images.githubusercontent.com/348248/36444396-e75341b6-1640-11e8-860d-5a949468cd6e.png)

As you can see, `sortDir`, and `sorField` are **unchecked**. This tells our devs that both fields are optional. We have other optional fields which I've removed from this request. Also, these two fields can apply to almost all of our endpoints. They are optional every time they appear. In this case, their values don't matter; I filled them here so that you could get an idea of what they are).

We have to go through **all** of our endpoints adding these fields. It would be great if we could have a global place where we could say "these are the global get params" and in each endpoint choose which global params we would like to add. In this way, we type the params just ONCE (globally) and then in each endpoint just check the params we want to include from the global space without having to type them. 

In our case, we had an API update that changed one of these parameters and we had to go one by one on each endpoint, changing the same parameter over and over again. A global option would make changes like these a mater of seconds.
