### ISSUE TITLE
Duplicate doesn't work, no cookies

### ISSUE THREAD

**Issue by joeyhub** [a85/POSTMan-Chrome-Extension#4129]
In Chrome Canary, duplicate only creates a new entry in the same collection with the name plus copy appended. Saving it fixes this, however the save button always appears grayed out (giving the impression it's non-operative) and as though it does nothing.

Cookies also aren't showing at all.

**Comment by sdnts** [comment]
@joeyhub Can you try this on the native apps? Chrome apps have been deprecated following Google's announcement and are no longer actively maintained.

On that note, cookies on the Chrome app will not show up in the app itself, they will be in the Chrome browser. The native app fixes this as well, by providing you a cookie manager inside the app.
