### ISSUE TITLE
Env/Global variables are interpreted differently between Runner and 'manual' requests 

### ISSUE THREAD

**Issue by dennisslavid** [a85/POSTMan-Chrome-Extension#4130]
When using environment or global variables with int values, these seem to be interpreted differently depending on whether you manually send the request or use runner to go over them.

eg. environment variable with:
key = iterator
value = 1

- When triggered manually this is interpreted as string value "1"
- When using Runner this is interpreted as int value 1

## App Details:
Postman for Windows
Version 5.5.2
win32 10.0.15063 / x64

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:
Only noticed recently, could have always been there
 2. Expected behaviour:
Same interpretation of variable value in both ways of triggering a request

**Comment by allyn-psyonix** [comment]
I came here to report a similar issue. Global variables set with numbers are being converted to strings. I am seeing this behavior when running collections via Newman.

e.g.
> postman.setGlobalVariable("myval", 42);
> postman.getGlobalVariable("myval") === 42; // false
> postman.getGlobalVariable("myval") === "42"; // true

**Comment by sdnts** [comment]
Hi @dennisslavid, Unfortunately, the app does not support variable types yet, all variables are stored as strings. We're looking to support this soon.
That being said, it should not behave differently in the Runner and the builder. I was unable to reproduce this. Can you give me the script you are running?

@allyn-psyonix I think this addresses your issue as well. Are you also seeing different behavior in the Runner and the builder or is it consistently being converted to strings for you?

**Comment by allyn-psyonix** [comment]
I am seeing consistent behavior, global variables are being returned as string in all cases for me. Support for other types including complex types would be great.

**Comment by sdnts** [comment]
@allyn-psyonix Ah, so you're seeing the same issue then. I'll update you guys here when we support custom variable types.

**Comment by dennisslavid** [comment]
It's a bit difficult to upload the script as it is across mutliple requests, but what i do is:

- Initiate an 'iterator' environment variable:

`pm.environment.set("iterator", 1);`

- use this iterator to loop through a POST (mutation) request for x-times:

```
var i = pm.environment.get("iterator");

if(i < 15) {
    postman.setNextRequest("This request");
    i++;
}

pm.environment.set("iterator", i);
```
- also use this iterator for a switch statement in the pre-request script (to change the variables in the input):

```
var i = pm.environment.get("iterator");
var parameter1;
var parameter2;

switch(i) {
    case "1":
    case 1:
        parameter1 = "";
        parameter1 = "";
        break;
    case "2":
    case 2
...
```
It's in this switch statement that the difference between manual and runner become visible. For now I catch this by 'doubling up' my cases :)

Hopefully this helps.

**Comment by prashantagarwal** [comment]
Related to #3463  This is related to variable types in Postman.
