### ISSUE TITLE
Dragging and dropping saved REST calls in Collections rarely works on Linux

### ISSUE THREAD

**Issue by Tanz0rz** [a85/POSTMan-Chrome-Extension#4132]
## App Details:

```
Postman for Linux
Version 5.5.2
linux 3.10.0-327.el7.x86_64 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:
This bug has been around for as long as I can remember (~6 months)
 2. Expected behaviour:
Dragging a saved call to a new position in my collection should work
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 4. Screenshots (if applicable)

Try to reorganize an item in a collection on the left side of the UI. Often it just doesn't work. Sometimes it does, but I have about a 20% success rate.

**Comment by numaanashraf** [comment]
@TannerMoore That's odd. We are looking into this.

**Comment by prashantagarwal** [comment]
@TannerMoore This bug seems to be fixed in latest Postman app versions. Feel free to reopen this issue if this occurs again.

**Comment by Tanz0rz** [comment]
It hasn't happened to me in a while. I also found out that restarting Postman fixed it. If it shows up again, I will take some time to see if I can get some solid reproduction steps. Thanks for looking into this for me.
