### ISSUE TITLE
From my Json output, i have a date field as "created": "2016-09-30T10:42:54.778Z", how can i set the filter to only return created after  2018

### ISSUE THREAD

**Issue by priyavj** [a85/POSTMan-Chrome-Extension#4138]
## App Details:

```
Postman for Mac
Version 4.11.0
OS X 16.4.0 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:
 2. Expected behaviour:
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 4. Screenshots (if applicable)

**Comment by sdnts** [comment]
Hi @priyavj, although I think this should be handled by your server, you can use `lodash`, which is included in the pre-request / test sandbox to filter out dates you want. I'm closing this for now, but please let me know if I misunderstood, and I'll reopen.
