### ISSUE TITLE
Postman still use proxy even if disabled

### ISSUE THREAD

**Issue by TheNemus** [a85/POSTMan-Chrome-Extension#4139]
## App Details:
Postman for Linux
Version 5.5.2
linux 4.4.0-112-generic / x64

## Issue Report:
 1. I encountered this issue with 5.4.0, 5.5.0, 5.5.2
 2. Disabling the "global" and "use system" proxy settings from postman (and disabling the OS proxy too), should force Postman to make a direct call to host
 3. 
`GET
http://localhost:3000/api/events
05:05:59.557
Pretty
Raw
Error: connect EINVAL 10.0.8.242:800
Request Headers:
cache-control:"no-cache"
postman-token:"4b56227f-a3db-40c6-bea3-027f7e2ab98b"`
10.0.8.242:800 is my proxy url

#Steps to reproduce
1. Disable any proxy setting from both OS and postman (you should try this with a machine that was previously connected to some proxied network).
2. Change network (I usually disconnect ethernet and use USB tethering from phone)
3. Try to make a call to localhost

**Comment by ChrisYarland-Price** [comment]
+1 I have the same issue what is even more annoying is that the api i am trying to call is on the no proxy list and yet this is ignored

**Comment by harryi3t** [comment]
Duplicate of https://github.com/postmanlabs/postman-app-support/issues/3942

**Comment by tinonetic** [comment]
I'm experiencing this issue with POstman v8.11.0
