### ISSUE TITLE
Sort requests in collection

### ISSUE THREAD

**Issue by lmvco** [a85/POSTMan-Chrome-Extension#414]
Hi,

Anyone know which is the criteria to Postman sort requests inside a category? There's any option to drag&drop requests in order to set a custom order?

Thanks

**Comment by borbamartin** [comment]
This does not work with the Mac App :(
Using the latest version (4.1.1) on OsX 10.11.4

Upcoming fix anytime soon @a85 ?

**Comment by sryze** [comment]
Reordering manually seems to work fine on the machine where you originally do it, but the order appears to be not synced between different installations. It would be nice to have it sync as well.

**Comment by abhijitkane** [comment]
@sryze Can you check the order at https://app.getpostman.com/dashboard/collections/private?expand=1? If it's not the same, try signing out and signing back in to your app.

**Comment by borbamartin** [comment]
Seems fixed in the latest update. Thanks!

**Comment by mwshubham** [comment]
is there any support to sort by title or time in addition to drag and drop support

**Comment by kineticz** [comment]
It's a bit tedious to sort requests by drag-and-drop. Why not let users sort by date/name or other criteria by just one click?

**Comment by luis-ferro-se** [comment]
This is now broken. Before last update, a manual order of requests would stick. Now it's ordering requests inside folders in alphabetical order... Why would anyone want that?
