### ISSUE TITLE
OAuth 2.0 Authorization header not being added by Postman

### ISSUE THREAD

**Issue by jdinardo30** [a85/POSTMan-Chrome-Extension#4140]
Postman is not adding an Authorization header to my requests when using the built in generator.  I've seen this issue before (issue number below) and it was supposedly fixed, however I am seeing it now in the latest version.  I've tried uninstalling, re-installing, creating new requests, etc. but the header is not being added.

## App Details:
Postman for Windows
Version 5.5.2
win32 6.1.7601 / ia32

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:
- I am seeing the exact same issue (#3608) in the latest version of Postman  

 2. Expected behaviour:
- Authorization header is added by Postman
 3. Console logs

- See screenshots

 4. Screenshots
- Notice there is no access token being added in the first request (the one that is supposed to be added by Postman) so I added one myself just to test and it shows up.  I even get the warning message that says this header will be overridden by the Authorization header generated by postman.
![image](https://user-images.githubusercontent.com/31749300/35697671-e64ea59a-0758-11e8-9e92-2e350465c998.png)

- Another interesting thing to note is that when I click on preview request, I get a "Could not update authorization data." error even though I was able to successfully get the Access Token and authenticate via my OAuth login page.
![image](https://user-images.githubusercontent.com/31749300/35697764-267672ce-0759-11e8-9492-b5f13b6e4a5d.png)

## Steps to reproduce:
1. Click on the "Authorization" Tab for a given request
2. Select "OAuth 2.0" from the "Type" drop-down
3. Select "Request Headers" from the "Add authorization data to" drop-down
4. Click "Get New Access Token"
5. Fill in data
![image](https://user-images.githubusercontent.com/31749300/35698057-0030a138-075a-11e8-9308-1cfaea90d1d0.png)
6. Click "Request Token"
7.  Login to the applications Oauth login page to get the access token/code
8.  Verify a token was created
![image](https://user-images.githubusercontent.com/31749300/35698130-38e8ed28-075a-11e8-89c8-9ffd6aa8e2b6.png)
9. Click "Use Token"
10. Click "Preview Request" (gives me the error mentioned above) or try to send the request (which sends a request without the Authorization header added).

**Comment by jdinardo30** [comment]
Anyone?? I can't be the only one with this issue.

**Comment by unff** [comment]
Same issue here.  Fiddler shows that no Authorization header is being sent in the request.  Generating the token is fine, but it never gets passed into the request headers.  I also get the same "Could not update authorization data." when previewing the request.

Adding the "Authorization: Bearer [accessToken]" header manually works.

**Comment by sdnts** [comment]
Hi @jdinardo30 @unff Can you guys check your DevTools to see if you get any errors in there?

On Postman < v6.0, you can open DevTools by heading over to `View Menu > Show DevTools`
On Postman > v6.0, you can open DevTools by clicking on `View Menu > Developer > Show DevTool (Current View)`

**Comment by jdinardo30** [comment]
Hi @madebysid 

The only thing I am seeing is when I click "Use Token" with DevTools open, a warning is displayed stating "You tried to return focus to null but it is not in the DOM anymore".  It's also worth noting that I have to click "Use Token" twice in order for the Manage Access Tokens window to close, which results in a second warning message:
![image](https://user-images.githubusercontent.com/31749300/36735519-69e02ece-1ba4-11e8-8b0a-65184a9756d4.png)

I also clicked on "Preview Request" which generates the "Could not update authorization data" message I mentioned, but it did not display anything in the DevTools console:
![image](https://user-images.githubusercontent.com/31749300/36735663-ad1751f4-1ba4-11e8-84b1-04bb35cf7ebe.png)

**Comment by unff** [comment]
Sorry for the delay.  My Dev Tools show the following errors:

![sshot0359](https://user-images.githubusercontent.com/7915543/37427697-8d46a1f6-27a0-11e8-8c1b-765a070444eb.png)

**Comment by kamalaknn** [comment]
Hey, 

Sorry for the delayed response. 

From the details @jdinardo30 has attached I could see that the token type is `BearerToken`. According to the OAuth 2.0 specification token [type section](https://tools.ietf.org/html/rfc6749#section-7.1) any token type is supported, provided the client understands it. 

Postman currently only understands `bearer` token. So it doesn't recognize `BearerToken` and doesn't add it to the headers.

In the latest version `6.0.x` we've added a UI improvement that gives this information right in the `Manage Tokens` dialog. This will prevent similar confusions where `Use Token` is allowed but doesn't work as expected.

The workaround for this is to manually copy the token and input it in the `Access Token` input box. Although the best practice is to stick to the commonly recognized token type `bearer/Bearer`, we understand that there are some endpoints you cannot control.

I'm closing this issue. Feel free to continue the discussion.

**Comment by leotohill** [comment]
@kamalaknn , I'm at v7, I see what you describe regarding "bearertoken" vs "bearer", but your workaround isn't working for me.  I clipboard the value and paste it into the access token input box, even though that box already shows the correct value, so I don't see why this would make a difference.  And it doesn't, as Postman still does not generate an auth header for the request that follows. 

Preview Request reports "Request headers were successfully updated with authorization data for preview."

**Comment by rmm5t** [comment]
I'm seeing the same problem. Actually, I'm seeing intermittent problems with this. Earlier today, manually pasting the access-token into the field worked. Now, it no longer does. Manually pasting the access-token does not send the `Authorization` header anymore.

Some Background: We're hitting an Apigee-fronted server that incorrectly returns a `BearerToken` token type instead of a `Bearer` token type even though the Apigee server expects an `Authorization` header prefixed with `Bearer` on subsequent requests.


I originally experienced this problem initially with v6.7.4.  I just upgraded to v7.3.4, and the problem still exists.

**Comment by jdinardo30** [comment]
@rmm5t Yup we are using Apigee as well, so we have no control on what is being returned (“BearerToken” vs “Bearer”). The only work around I came up with was to have a middle man service to intercept the response from Apigee back to postman, transforming the response to replace “BearerToken” with “Bearer”. Works well but obviously isn’t ideal.

**Comment by rmm5t** [comment]
It'd be nice if the copy-n-paste workaround was at least a consistent solution. Better yet would be to allow usage of a token even if the incorrect token-type is returned.

The limiting factor could instead be that the `Authorization` header will always pass a `Bearer` prefix regardless of the token-type returned during the token handshake.

**Comment by rmm5t** [comment]
Alternatively, it'd be nice if Postman treated `BearerToken` and `Bearer` as equivalent token-type responses, just because Apigee is so prevalent.
