### ISSUE TITLE
How I can configre the destination Directory

### ISSUE THREAD

**Issue by Kirchmayer** [a85/POSTMan-Chrome-Extension#4141]
We will install Postman on lots of PC´s with different user.

So we will install Postman on Windows in the Directory C:\Program Files (x86) but we can´t configure this.

How can we made it ?

**Comment by Anton-V-K** [comment]
Same as #3019

**Comment by sdnts** [comment]
@Kirchmayer As @Anton-V-K said, we've been looking into MSI packages for Windows app distribution. When that comes in, you should be able to select a destination for app data. I'm closing this as duplicate of #3019, please follow that thread for updates :)

**Comment by number005** [comment]
Why is this closed? I can still not decide where to install to?
