### ISSUE TITLE
Allow customization of font families

### ISSUE THREAD

**Issue by mibeon** [a85/POSTMan-Chrome-Extension#4142]
Hello everyone.

I want to change the font family inside of response window, body window (everywhere monospace font is used) to another one as Monaco at Mac (macOS).

Has someone any hook, break or hack for changing font family in this app??? 
It seems like postman developers are not able to give us this shabby customization option.

I don't like Monaco font and want to set it to another one.
In year 2018 a.c. there must be a possibility to customize apps like we need.

Peace

**Comment by sdnts** [comment]
@Mibeon I'm adding this as a feature request for now. Thanks for the suggestion!

**Comment by jitendra-1217** [comment]
Please have this. 🙏

**Comment by anudeepmedicharla** [comment]
Hey @Mibeon, thank you for the suggestion! We are indeed looking at offering a few UI customizations inside the app. While I cannot give an ETA, customization is definitely on our roadmap. 

Please stay tuned for updates regarding this in future. Thank you. :)

**Comment by GregoryPellegrin** [comment]
we really need this guys, add a Monospaced font please

**Comment by chrisdeso** [comment]
Bump – we'd love to see the ability to change font size and colors as well.

[filed by postman]

**Comment by andreyoshev** [comment]
So?)

**Comment by GregoryPellegrin** [comment]
come on guys, we need this feature :)

**Comment by gitaumoses4** [comment]
Yes please. We really need this feature.

**Comment by ziishaned** [comment]
Any news on this one?

**Comment by wherevn** [comment]
Hi all. Any news on this one?

**Comment by mibeon** [comment]
Hey guys, it's about more than a year over.
Postman is electron based. Adding another font family should be not a big thing...

What is actually your problem?

**Comment by FelipeCortez** [comment]
If you really want to change the font family for the editors you can do so by changing line 1139 in `Postman/app/resources/app/js/(runner|requester|console).css`.

**Comment by abrhambas01** [comment]
@FelipeCortez , where can you find it< I didn't see anything

**Comment by abrhambas01** [comment]
@FelipeCortez 
![image](https://user-images.githubusercontent.com/12043306/56865339-86c2c880-69ff-11e9-9768-2e29ba371653.png)

Hello mate, which should I choose between the two app - ???

**Comment by molinan2** [comment]
> If you really want to change the font family for the editors you can do so by changing line 1139 in `Postman/app/resources/app/js/(runner|requester|console).css`.

Thanks for this, @FelipeCortez! It worked for me. The location in my Mac was: `/Applications/Postman.app/Contents/Resources/app/js/` for `runner.css`, `requester.css` and `console.css`. I modified all of them. Maybe updating the app will cause this to reset, but it's an easy trick to repeat.

Just searched for "Monaco" and deleted it from the line you said:

```css
.editor.ace_editor {
    font: 12px "Menlo", "Ubuntu Mono", "Consolas", "source-code-pro", "Cousine", monospace, monospace;
}
```

The main reason I don't like "Monaco" is because of the `a` character being so close to the `o`.

**Comment by donhmorris** [comment]
This would be really helpful. The fonts are pretty small on a Mac laptop. Makes it hard to see the interface for those of us who started our careers programming Apple pascal on the Apple II. 😀

**Comment by sergeyklay** [comment]
The fonts are pretty small not only on a Mac laptop. The same on my Ubuntu laptop and Debian PC. Looks like maintainers are Windows users :man_shrugging:

**Comment by owenblacker** [comment]
~It would definitely be useful to be able to change the font size in the body window. My eyesight ain't what it used to was…~ 👴🏼

~I'm on Windows and I can't see a CSS file in the application directory to mess with, unfortunately.~

**ETA:** Just noticed there's literally a field called _Editor Font Size (px)_. I was just expecting to see one with `font-face` as well as `font-size` 🙄

**Comment by kosalamoon** [comment]
> > If you really want to change the font family for the editors you can do so by changing line 1139 in `Postman/app/resources/app/js/(runner|requester|console).css`.
> 
> Thanks for this, @FelipeCortez! It worked for me. The location in my Mac was: `/Applications/Postman.app/Contents/Resources/app/js/` for `runner.css`, `requester.css` and `console.css`. I modified all of them. Maybe updating the app will cause this to reset, but it's an easy trick to repeat.
> 
> Just searched for "Monaco" and deleted it from the line you said:
> 
> ```css
> .editor.ace_editor {
>     font: 12px "Menlo", "Ubuntu Mono", "Consolas", "source-code-pro", "Cousine", monospace, monospace;
> }
> ```
> 
> The main reason I don't like "Monaco" is because of the `a` character being so close to the `o`.

thanks... this worked for me

**Comment by ZooDoo4U** [comment]
Is there a similar solution for windows?  Searching for runner.css or requester.css, couldn't find them on the machine anywhere.  Any suggestions on changing the font family on windows?

**Comment by paulodetarsofm** [comment]
> Is there a similar solution for windows? Searching for runner.css or requester.css, couldn't find them on the machine anywhere. Any suggestions on changing the font family on windows?

@ZooDoo4U, follow the instructions here: https://www.codepicky.com/hacking-electron-restyle-skype/

**Comment by ZooDoo4U** [comment]
Awesome thanks a lot.   The instructions given at codepicky.com worked great, only thing for postman to get in the browser's devtools as suggested didn't need to press the magical {CTRL}+{SHIFT}+{ALT}+D,   just needed to use the menu postman View::Developer.  After that we all should know what to do.   I'm wondering, but not sure expanding the asar as this does and renaming the release version, if postman doesn't enable the debug view automagically...   

Anyway this is perfect!  Thanks for the tip

**Comment by marcolopezpe** [comment]
Hi, thanks for the tip in windows!
Add info. I modify the file CommonLazyChunk.js line 2155 "var DEFAULT_WINDOWS_FONT_FAMILY = 'JetBrains Mono, \'Courier New\', monospace';" in my case, I put "JetBrain Mono, this for windows.


> Awesome thanks a lot. The instructions given at codepicky.com worked great, only thing for postman to get in the browser's devtools as suggested didn't need to press the magical {CTRL}+{SHIFT}+{ALT}+D, just needed to use the menu postman View::Developer. After that we all should know what to do. I'm wondering, but not sure expanding the asar as this does and renaming the release version, if postman doesn't enable the debug view automagically...
> 
> Anyway this is perfect! Thanks for the tip

**Comment by pankajk07** [comment]
@Mibeon  With the new release (`v7.31`), we have added few settings to customize the editor, including the ability to change the font family. Please try it out and do give your feedback.

**Comment by mibeon** [comment]
@pankajk07 Well done guys, well done!
