### ISSUE TITLE
UI Feature Request: Collapsing 'Authorization' Section

### ISSUE THREAD

**Issue by karakanb** [a85/POSTMan-Chrome-Extension#4145]
## App Details:

```
Postman for Mac
Version 5.5.2
OS X 17.4.0 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there: Not a bug, has always been there, a UI and UX issue.
 2. Expected behaviour: I believe that the `Authorization | Headers | Body | Pre-request Scripts | Tests` pane should be collapsible. Have been using Postman for months, and never needed the section, hence it covers 25% of my screen height for no value. I believe the section should be collapsible, just like `Params` button on the URL bar. Currently, I need to scroll down to see my response, which makes it hard to navigate for most of the time.
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
```
requester.js:471725  ================================================================
     o
   (/) P O S T M A N
   ^

   Go to View -> Show Postman Console to check your script logs. 

================================================================
sails.io.js:142 🌏 sync service connectivity initiated
sails.io.js:759 socket replaying queued commands
sails.io.js:142 🌏 connected to sync service.
mode-auto.js Failed to load resource: net::ERR_FILE_NOT_FOUND
requester.js:87057 Error running scripts: JSONError | Unexpected token '<' at 1:1
<pre>Array
^ Object
exception @ requester.js:87057
requester.js:87057 Error running scripts: JSONError | Unexpected token '<' at 1:1
<pre>Array
^ Object
exception @ requester.js:87057
sails.io.js:142 🌏 disconnected from sync service. possibly a network outage.
sails.io.js:142 🌏 scheduled reconnection attempt #1 after 13724ms
requester.js:87057 Error running scripts: JSONError | Unexpected token '<' at 1:1
<!DOCTYPE html><!--
^ Object
exception @ requester.js:87057
sails.io.js:142 🌏 reconnecting to sync service. #(1/8)
sails.io.js:142 🌏 reconnected to sync service after being offline for 14.348seconds.
sails.io.js:142 🌏 connected to sync service.
sails.io.js:142 🌏 disconnected from sync service. possibly a network outage.
sails.io.js:142 🌏 scheduled reconnection attempt #1 after 5670ms
sails.io.js:142 🌏 reconnecting to sync service. #(1/8)
sails.io.js:142 🌏 reconnected to sync service after being offline for 8.914seconds.
sails.io.js:142 🌏 connected to sync service.
sails.io.js:142 🌏 disconnected from sync service. possibly a network outage.
sails.io.js:142 🌏 scheduled reconnection attempt #1 after 10534ms
sails.io.js:142 🌏 reconnecting to sync service. #(1/8)
sails.io.js:142 🌏 reconnected to sync service after being offline for 11.199seconds.
sails.io.js:142 🌏 connected to sync service.
sails.io.js:142 🌏 disconnected from sync service. possibly a network outage.
sails.io.js:142 🌏 scheduled reconnection attempt #1 after 5733ms
sails.io.js:142 🌏 reconnecting to sync service. #(1/8)
sails.io.js:142 🌏 reconnected to sync service after being offline for 6.397seconds.
sails.io.js:142 🌏 connected to sync service.
sails.io.js:142 🌏 disconnected from sync service. possibly a network outage.
sails.io.js:142 🌏 scheduled reconnection attempt #1 after 8542ms
sails.io.js:142 🌏 reconnecting to sync service. #(1/8)
sails.io.js:142 🌏 reconnected to sync service after being offline for 10.999seconds.
sails.io.js:142 🌏 connected to sync service.
```
 4. Screenshots (if applicable)
<img width="1131" alt="screen shot 2018-02-03 at 13 29 00" src="https://user-images.githubusercontent.com/16530606/35766288-793a0f64-08e6-11e8-95bd-2323cb4ae423.png">

**Comment by JamesMGreene** [comment]
That would be really nice.  Similarly, I would love if the response section was also collapsible... less commonly but still occasionally desirable in my experience.

**Comment by brenthale** [comment]
I vote for this as well.

Regarding the "Response Section" that James talked about.  I can see how it would be nice to make it collapsible.  My big problem with that section is how I end up with multiple scroll bars.  I search for a string and often the word is in the response section but below the area currently showing on my screen.  It forces me to go to the outer scroll bar to scroll down to see the entire "response section".   Very un-user-friendly.

**Comment by a85** [comment]
You can use the 2-pane layout that shows the response to the right of the request. The button is on the bottom right in the status bar.

**Comment by karakanb** [comment]
The 2-pane layout is useful in some cases; however, it is a tradeoff between the width and height of the response section. Making some parts of the UI collapsible avoids this tradeoff and improves the overall experience. Until it is implemented, we will be using the 2-pane layout.

**Comment by sdnts** [comment]
Hi @karakanb @JamesMGreene @brenthale, I've seen a similar feature request over at #3985, I'm closing this as a duplicate, please follow that thread for updates, thanks :)
