### ISSUE TITLE
Is it possible to detect whether I doing collection run or a single endpoint request?

### ISSUE THREAD

**Issue by rawaludin** [a85/POSTMan-Chrome-Extension#4146]
My use case is, I want to skip some cleanup script on collection script if I run a single request, not a collection run.

Is it possible? Thanks.

**Comment by sdnts** [comment]
Hi @rawaludin, while I wouldn't recommend this, you can use the variable `iterations`, which is only defined when running a collection run.

Ideally, the logic you're using results in tests that depend on each other, which isn't maintainable or debuggable in the long run. I'd recommend keeping each request self-contained, in the sense that each one cleans up after itself. You wouldn't need a way to distinguish between collection runs and single request executions then.
If you have cleanup to do after ALL requests have completed, you can place this script in a separate request and keep it at the end of your collection. This way, it will run after all requests have completed.
