### ISSUE TITLE
WSS-Password Type for a SOAP API Request

### ISSUE THREAD

**Issue by idknox** [a85/POSTMan-Chrome-Extension#4149]
## App Details:
```
Postman for Mac
Version 5.5.2
OS X 16.7.0 / x64
```

## Issue Report:
Is is possible to customize this property for a SOAP API request? I could find 0 information in Google on how you can set WSS-Password Type to `PasswordText`.

Thanks!

**Comment by prashantagarwal** [comment]
@idknox I think we don't support this out of the box. But please feel free to ask this in the Postman community, someone might be able to give you some workaround this problem. https://community.getpostman.com
