### ISSUE TITLE
Code generator for NodeJS with Request misinterpret repetitive parameters in query strings

### ISSUE THREAD

**Issue by psech** [a85/POSTMan-Chrome-Extension#4150]
## App Details:
```
Postman for Mac
Version 5.5.2
OS X 10.13.2 / x64 High Sierra
```

## Issue Report:
Not sure about the previous version, just found it
 
### Actual behaviour:
I am querying the following url: https://app.launchdarkly.com/api/v2/flags/DataRoom?env=Staging&env=UAT
Please notice env parameter in query string is duplicated

The code generator produces the following:

```
method: 'GET',
url: 'https://app.launchdarkly.com/api/v2/flags/DataRoom',
qs: { env: [ 'Staging', 'UAT' ] },
headers: {...}
}
```

Following qs documentation (https://www.npmjs.com/package/request)

> "useQuerystring - if true, use querystring to stringify and parse querystrings, otherwise use qs (default: false). Set this option to true if you need arrays to be serialized as foo=bar&foo=baz instead of the default foo[0]=bar&foo[1]=baz."

as the env parameter is duplicated, we need to use querystring to stringify. So code generator should return following:

```
method: 'GET',
url: 'https://app.launchdarkly.com/api/v2/flags/DataRoom',
qs: { env: [ 'Staging', 'UAT' ] },
**useQuerystring: true,**
headers: {..}
```

**Comment by sdnts** [comment]
@psech Thanks for reporting this. It looks like an issue with the library we use to generate code snippets. We'll look into this.

**Comment by abhijitkane** [comment]
@psech Can you try this is Postman 7.2+, with the 'Experimental Codegen Mode' flag enabled in Postman's global settings? We've introduced bug-fixes, support for two new languages (JS-Fetch and Powershell), and the ability to configure certain aspects of the generated snippet.

This particular issue is fixed - 
```
var request = require('request');
var fs = require('fs')
var options = {
  'method': 'GET',
  'url': 'https://app.launchdarkly.com/api/v2/flags/DataRoom?env=Staging&env=UAT',
  'headers': {
  }
}
request(options, function (error, response) { 
  if (error) throw new Error(error);
  console.log(response.body);
});
```

**Comment by psech** [comment]
@abhijitkane I confirm, the issue has been resolved. Thank you for getting back to me.

I wonder why do I need `var fs = require("fs");` and why there are no query string parameters?
Whatsoever, it works and anyone can add qs by themselves.
