### ISSUE TITLE
Feature Request: Add auto format for JSON content

### ISSUE THREAD

**Issue by fabianerni** [a85/POSTMan-Chrome-Extension#4154]
## App Details:
```
Postman for Windows
Version 5.5.2
win32 10.0.16299 / x64
```
**Feature**
Add format option for JSON request body

**Problem**
Because JSON is by definition just one string, it's difficult the read or edit larger JSON body content in the request. The JSON content type helps with the code highlighting, but it's still a one line string.

**Request**
Add an option to format JSON content with new lines and indents, just as code editors do. A button "Auto-Indent JSON" would be great. Internally, postman could remove all formatting before submitting the request, to prevent any problems.

**Comment by JamesMGreene** [comment]
:+1:

I am frequently using an editor or jsonlint.com to format my request messages before pasting them into Postman.  It would definitely be nice to have an option to format it right in Postman.

**Comment by sivcan** [comment]
Hi @fabianerni @JamesMGreene this feature is already there in postman.
Press 'Cmd + B' (Mac) and 'Ctrl + B' (Windows) and it'll auto-indent JSON for you. 
![indent](https://user-images.githubusercontent.com/12631777/38023385-c8cf7446-329f-11e8-87da-cc1a4f6890f5.gif)

**Comment by fabianerni** [comment]
Ctrl+B only works in the Pre-req. and Test tabs, but not in the Body tab

**Comment by sivcan** [comment]
@fabianerni Are you on the latest version of the native app v6.0.10 (as of writing this comment) ?
![autoindent](https://user-images.githubusercontent.com/12631777/38025072-aa115fec-32a4-11e8-939f-d00b43e2ae7e.gif)

Auto-Indent In the Body^

**Comment by lwiecek** [comment]
I'm using Postman `Version 7.1.0 (7.1.0)` and automatic formatting doesn't work here.
I looked at available shortcuts and Cmd + B isn't listed under `Postman -> Preferences -> Shortcuts`.

**Comment by sujayvenaik** [comment]
Hey @lwiecek 
For the data types, postman supports beautifying, a `Beautify` button comes on the right end.
Also, cmb+b is not documented but essentially has the same functionality that the Beautify button will do.
![image](https://user-images.githubusercontent.com/11532114/58010043-41308180-7b0d-11e9-8a1d-489fd609fff4.png)

**Comment by lwiecek** [comment]
Hi @sujayvenaik 
Yup, it works there (sorry I haven't checked that earlier)

My issue is that I'm not able to use Cmd + B in collection's request example.

<img width="923" alt="Screenshot 2019-05-20 at 11 27 06" src="https://user-images.githubusercontent.com/3070150/58011290-3a484580-7af2-11e9-8cb3-ca87c4a9267b.png">
