### ISSUE TITLE
Capture proxy doesn't keep request authentication certificate

### ISSUE THREAD

**Issue by pawelalikowski** [a85/POSTMan-Chrome-Extension#4155]
## App Details:

```
Postman for Windows
Version 5.5.2
Microsoft Windows 10 Enterprise
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:
 2. Expected behaviour:
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 4. Screenshots (if applicable)

**Comment by sivcan** [comment]
Hi @pawelalikowski - Kindly provide the steps to reproduce this issue and also I suggest you to update to the latest version of the app i.e. (6.0.10 as of writing this comment) and let us know if this issue persists for you and we'll reopen this ticket.

Closing this.
