### ISSUE TITLE
Bad request for negative testing with Post verb always results in a time out.

### ISSUE THREAD

**Issue by nithyamuth** [a85/POSTMan-Chrome-Extension#4158]
![image](https://user-images.githubusercontent.com/33329496/35945282-460c043e-0c25-11e8-80bd-1928ac9d307a.png)

All other requests work with the postman. 
When the request is run in a collection, due to the timeout issue the whole collection stops abruptly with connection error.

**Comment by numaanashraf** [comment]
Hi @nithyamuth, please share your app/os version and the request you are trying to send. Is Postman sending the request to your server? Could you open the Postman Console (View > Show Postman Console) and let us know if you find any logs/errors there?

**Comment by nithyamuth** [comment]
the version that I use is the latest.

Postman for Windows
Version 5.5.3
win32 10.0.14393 / x64

 POST: http://httpstat.us/get/custname?start_timestamp={{starttime}}&end_timestamp={{endtime}}&param={{paramid}}

{{requestbody}}

In the console, since it times out..it reads Error: read ECONNRESET

Postman sends the request to our server and retrieves the response.
However for the same request in a different testing app, I get the desired error message as response.

**Comment by nithyamuth** [comment]
Timeout occurs when it hits a single endpoint. we are internally doing some investigation to isolate the root cause in postman. Will provide more details on this issue as soon as we have more details.

**Comment by sivcan** [comment]
Closing this.
If the issue still persists then kindly give us the details for us to investigate further into it and then we'll reopen it.
