### ISSUE TITLE
Empty test in collection download (using the API) not visible in user interface

### ISSUE THREAD

**Issue by bartdkmediahuis** [a85/POSTMan-Chrome-Extension#4159]
## App Details:

```
Postman for Mac
Version 5.5.2 (5.5.2)
macOS - 10.12.6
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:
- Bug was encountered only recently

 2. Expected behaviour:
- Our TeamCity server will download the collection, using the Postman API 
- Strange thing is that the collection file contains an element without a name, that is not visible in the User Interface. Ofcourse newman will fail to execute this test, but I'm unable to remove the call from our collection, since it's not visible. 
Seems like a bug ?
Is there any way I can remove the test ? (by chaning the raw collection JSON)
 4. Screenshots (if applicable)
![image](https://user-images.githubusercontent.com/10774633/35960050-6f4db102-0ca8-11e8-94ce-6d642048d835.png)

I don't know how to reproduce the problem (as in; no idea how the empty test got in our collection !?)

**Comment by sivcan** [comment]
Hi @bartdkmediahuis - I suggest you to kindly update to the [latest version of the app](https://www.getpostman.com/apps) and check the same.

 Let us know if the issue still persists for you, I'll reopen this ticket and we'll investigate further into this.
