### ISSUE TITLE
Design for "Resolve sync conflicts" UI

### ISSUE THREAD

**Issue by ionutincau** [a85/POSTMan-Chrome-Extension#4161]
In the Resolve sync conflicts UI is a lot of whit space for item type, item id, property name, and the values I care about (server value and local value) are on the right are on right side in small columns.

Please make this screen bigger, maybe with a side by side view of changes (like git diff), and maybe item type, id on top like a title not a column.

Also thanks :) Postman is awesome!

**Comment by sdnts** [comment]
@ionutincau Thanks for the suggestion! We will look into this :)

**Comment by ankit-m** [comment]
Closing this in favour of #3261
