### ISSUE TITLE
Delete request sends Content-length empty string when no body provided

### ISSUE THREAD

**Issue by alevito** [a85/POSTMan-Chrome-Extension#4162]
## App Details:

```
Postman for Linux
Version 5.5.0
linux 4.14.16-300.fc27.x86_64 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there: *recently*
 2. Expected behaviour: *delete request sends content-length header with empty string*
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 4. Screenshots (if applicable)

Create a DELETE request without a body and a without content-length header.
Open the Postman Console and send the request.
The request contains a Content-length with an empty value.

**Comment by thecuriousdev** [comment]
@alevito thanks for reporting this, we'll keep you posted here.

**Comment by codenirvana** [comment]
This is fixed in the latest version of the Postman App (v7.7.2).
