### ISSUE TITLE
Postman can't connect

### ISSUE THREAD

**Issue by ilicmarko** [a85/POSTMan-Chrome-Extension#4163]
## App Details:
```
Postman for Windows
Version 5.5.2
win32 10.0.16299 / x64
```

## Issue Report:
I can't get postman to go online for half of the day, tried turning of my Nod firewall still notning. 

What is really strange it works sometimes and after few hours it stops and I can't get it to go online. I tried login in and out, shuting the app on and off.

![error log](https://i.imgur.com/Kw22YIE.png)

**Comment by eloyucu** [comment]
Hi!!!
I am very rookie with postman, but I think you are using the chrome extension... have you tried the desktop app??

64 bits -  [download link](https://app.getpostman.com/app/download/win64?_ga=2.82694356.359033834.1518115388-1626027866.1509619528)
32 bits - [download link](https://app.getpostman.com/app/download/win32?_ga=2.182991972.359033834.1518115388-1626027866.1509619528)

**Comment by ilicmarko** [comment]
@eloyucu as you can see from the app info (**Postman for Windows**) I am not 😢

**Comment by ilicmarko** [comment]
Now its online and syncing, its random.

**Comment by sdnts** [comment]
@ilicmarko @eloyucu We've made several improvements to Sync recently. We are slowly rolling a new version out, so you guys should get it in a couple of days or so. Issues like these should be solved there.
If you want to verify, you can download our [Canary](https://getpostman.com/canary) version to check if you still see this.

I'm closing this for the time being, but if you still see erratic behavior on Canary as well, please let me know, and I'll reopen.
