### ISSUE TITLE
Feature: Ability to explicitly specify scope when referencing variables

### ISSUE THREAD

**Issue by andi-livn** [a85/POSTMan-Chrome-Extension#4164]
## App Details:

```
Postman for Windows
Version 5.5.2
win32 10.0.16299 / x64
```

## Issue Report:
From all I can find in the docs, stackoverflow & co, it is currently not possible to explicitly reference a variable value, as it has been defined on a specific scope, if the variable has been overwritten, i.e. set with the same name/key on another scope of higher priority. It would in some cases be useful to be able to explicitly use the value of a global variable instead of the value of an environment or collection scope variable.

A thinkable solution could be to reserve the prefixes _global._, _collection._ and _environment._, e.g. _global.foo_.
Of course this might cause problematic for users, that use dot notation in their variable keys (does anyone do that?).
Seeing as there are already several reserved variable names starting with $, such as _$guid_ or _$timestamp_, maybe the anotation could be used, that is less likely to interfer with anyone's existing collection of variables, e.g. _$global.foo_ or _$global>foo_

**Comment by harryi3t** [comment]
@andi-livn If you have a variable `foo` defined in both globals and in some environment, you can get them separately using `pm.globals` and `pm.environment` respectively

```js
pm.globals.get('foo')
pm.environment.get('foo');
```

**Comment by harryi3t** [comment]
@andi-livn Feel free to re-open the issue if this does not solve your use-case.

**Comment by andi-livn** [comment]
Thanks Harry. Just for anyone else wondering about this, in order to use this detour with a placeholder, for instance in a request URL parameter, you need to use the _Pre-request Script_.

e.g.: `GET http://localhost/api/dothemambo?cmd={{pm.globals.get("overriddenVariable")}}` does not appear to work.

But you can use a separate variable as placeholder:

`GET http://localhost/api/dothemambo?cmd={{setByScript}}`

...and then use a _Pre-request Script_ to set the value of `setByScript` to the actual correct value:

`pm.variables.set("setByScript", pm.globals.get("overriddenVariable"));`

Please correct me if I'm wrong, and there is a easier, more direct way.

**Comment by harryi3t** [comment]
@andi-livn Thanks for sharing :) and yes that is the correct way of doing it.
Just to make it more solid, I made a small diagram.

![image](https://user-images.githubusercontent.com/5207331/36134209-40582814-10a9-11e8-812e-57e14e2f1f64.png)

Becuase of the lowest preference, a global variable gets overwritten by an environment variable with the same name. Your solution sets the same variable using `pm.variables.set` which puts it in the temporary variables which are of highest preference.

**Comment by andi-livn** [comment]
Thanks for the visuals. Makes it very clear and would make a great addition to the docs.
