### ISSUE TITLE
"Force Close Tab" key combination overlays on certain keyboard layouts

### ISSUE THREAD

**Issue by brnor** [a85/POSTMan-Chrome-Extension#4165]
Postman for Windows
Version 5.5.2
win32 6.1.7601 / x64

The shortcut for the Force close tab works by pressing CTRL + ALT + W, but the shortcut also triggers by pressing AltGr + W since Windows treats AltGr as Ctrl+Alt. This behaviour cannot be changed in Windows and requires third-party software to change which I cannot set up in my work environment.
Due to my keyboard layout, AltGr + W is required for use since it provides the ' | ' character, so this is quite unpleasant to work with (especially when writing ' || ' in scripts which force-closes 2 tabs).
Could this shortcut possibly be moved to another key combination that does not overlay with certain frequently used characters like in this case?

The keyboard layout in question is [Croatian](https://en.wikipedia.org/wiki/QWERTZ#South_Slavic_Latin) but I've noticed that several more layouts have the ' | ' character on the same combination.

**Comment by thecuriousdev** [comment]
Hey @brnor thanks for reporting this, we'll keep you posted in https://github.com/postmanlabs/postman-app-support/issues/2707.
