### ISSUE TITLE
Postman app window not opening even though the program is running

### ISSUE THREAD

**Issue by ajalgaonkar** [a85/POSTMan-Chrome-Extension#4167]
## App Details:

```
Postman for Windows
Latest version
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:
I was able to run postman without issues, but after a few days of use it just wont open and maximize 
 2. Expected behaviour:
App should open
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 4. Screenshots (if applicable)
![image](https://user-images.githubusercontent.com/1766989/36059212-5218039e-0de8-11e8-8757-7f1d643e9d33.png)
![image](https://user-images.githubusercontent.com/1766989/36059219-7e24fb5e-0de8-11e8-9bc6-868bfb7a77e6.png)

**Comment by thecuriousdev** [comment]
@ajalgaonkar thanks for reporting this bug, Please help me with the following,
1. App version?
2. Do you have a multi-monitor setup?

**Comment by ajalgaonkar** [comment]
Hey @thecuriousdev I found the issue.
Repro:
1. I remoted into my Laptop from my desktop which has multi monitor set up.
2. Ran the application and then ended the session.
3. Once I opened my Laptop by itself and tried to open the application on my single screen it probably still kept its context thinking there is another monitor (apart from the primary screen of the laptop).

I solved the issue by clicking WindowsKey with side arrow to place the app in one side of my current screen after which i was able to see and use the application.
Also this consistently repros on my machine (as currently every start up is not on my primary screen for some reason).

Here is the details about the app:
![image](https://user-images.githubusercontent.com/1766989/36330623-43932a88-131f-11e8-92dd-edda2550e65a.png)

**Comment by thecuriousdev** [comment]
@ajalgaonkar thanks for your patience. The issue got fixed in Postman 6, you will get the update very soon. Please let me know if the issue is still not resolved after the update.

**Comment by yan-khonski-ca** [comment]
Hey, not fixed!
2018 06 05 - I updated Postman - Windows 7, x64, I have two monitors. The Postman does not work. Please, fix.

**Comment by thecuriousdev** [comment]
Hey @yan-khonski-ca, can you provide some more details about the issue you are facing?

**Comment by iselenium4** [comment]
6/6/2018 -- The app no longer shows up for me as well (went as far as re-installing and unplugging my 2nd monitor to try and combat the problem).  Re-installed version win64-5.3.2 and the problem persisted.  App appears to be running in windows, shows up in the task manager, and has a small hover window on the windows taskbar, but does not have a physical screen to interact with.
![image](https://user-images.githubusercontent.com/40005144/41062303-164ee1e8-699b-11e8-94ce-737342342dfb.png)
![image](https://user-images.githubusercontent.com/40005144/41062315-1ae0b6dc-699b-11e8-8a3b-0c373f77bcb9.png)

**Comment by thecuriousdev** [comment]
@iselenium4 what's the app version? if its an older version (5.x.x) try to update to the latest version of postman.

**Comment by iselenium4** [comment]
I had 5.3.2, but installing version 6.1.3 caused the same problem.

**Comment by thecuriousdev** [comment]
@iselenium4 can you try pressing windows key + arrows key?

**Comment by gauravgenius** [comment]
@thecuriousdev Facing same issue, 
I've installed "Postman-win64-6.1.4-Setup", experiencing exactly same behavior, which @ajalgaonkar mentioned earlier, quoting 
> Hey
> 
>  @thecuriousdev I found the issue.
> Repro:
> 
> I remoted into my Laptop from my desktop which has multi monitor set up.
> Ran the application and then ended the session.
> Once I opened my Laptop by itself and tried to open the application on my single screen it probably still kept its context thinking there is another monitor (apart from the primary screen of the laptop).
> I solved the issue by clicking WindowsKey with side arrow to place the app in one side of my current screen after which i was able to see and use the application.
> Also this consistently repros on my machine (as currently every start up is not on my primary screen for some reason).

**Comment by bpringe** [comment]
I am experiencing this issue as well. Sometimes the app loads the UI, other times it just stays on the loading screen (I've left it for several minutes). I see multiple postman threads running, but no UI. I have to force stop the postman processes, and try again. It usually works after force stopping processes once. But as far as when it happens initially, I don't think it happens every time I try to load it but maybe about 50% of them time. I'm on Windows 10, dual monitors (one turned vertically, not sure if this matters), Postman v6.4.4.
![image](https://user-images.githubusercontent.com/12722744/47241062-f5b7c880-d3af-11e8-972a-99479f257ab9.png)

**Comment by movAX13h** [comment]
Still nothing. I start the program, the window stays blank and the mouse cursor indicates that it is loading something. But it never finishes.  (win8)

**Comment by chayanbansal9195** [comment]
same for me

**Comment by towndwarf** [comment]
(hash)metoo. :)
I mean, postman stalled in some infinite loop. Cannot use.

**Comment by swamy526** [comment]
I am also facing same issue

**Comment by shuyih** [comment]
hi, this is happening right now with version 6.7.4 on windows 10 x64, what is the solution?

**Comment by EhsanHadid** [comment]
i have the same problem
i handle that so simple in win 10
press Shift + Right click on icon
select Maximize

**Comment by ghost** [comment]
im having this problem right now, on mac

**Comment by hamesjan** [comment]
Postman app is not opening on Mac as well

**Comment by vigneshrajvvr** [comment]
I too had this issue. In my case, i accidentally installed 0.X version. So uninstalled it and installed 7.32. Now, it's working fine.

**Comment by PierreMaraisZA** [comment]
Having problem right now on win 10, laptop monitor and hdmi side screen, postman 0.2.3

**Comment by he-dev** [comment]
I've just insatlled the _Postman Agent-win64-0.2.4_ and none of the above suggestions help. I use two monitors. Do you know other workarounds? I also tried the `POSTMAN_DISABLE_GPU` trick but it didn't work.

**Comment by S-Fahmy** [comment]
I 'm facing the same problem, I just installed Postman Agent-win64-0.2.4-Setup first time ever and it only shows up in the icon tray and in task manager but no GUI appears, that's so freaking lame.
I have my laptop connected to a monitor but I tried unplugging the monitor and the same problem occurs.

Update: I downloaded and installed Postman-win64-7.36.0-Setup instead and it seems to be working as expected now.

**Comment by saswatds** [comment]
Hi, @he-dev @sfskysf Sorry for all the confusion. 
Clarifying for people who might end up on this thread because of this. The  **Postman Agent** and **Postman App** are two different products.
The Postman Agent is a simple companion application to the [Postman Web](https://blog.postman.com/announcing-postman-for-the-web-now-in-open-beta/) experience and does not contain any user experience. It's a small daemon like application used by your browser to send requests. [Read More](https://blog.postman.com/introducing-the-postman-agent-send-api-requests-from-your-browser-without-limits/)

On the other hand, the Postman App is the full standalone desktop application that you can install and contains the GUI, which you can [Download Here](https://www.postman.com/downloads/). 

Meanwhile, I have gone ahead and raised this issue internally to the concerned teams to improve the user experience and reduce confusion.
