### ISSUE TITLE
Postman form-data not works

### ISSUE THREAD

**Issue by tahmid-hasan** [a85/POSTMan-Chrome-Extension#4168]
I'm facing some problem when using postman. When I'll try to send raw data in JSON(application/json) format, it get success.

![image](https://user-images.githubusercontent.com/34867248/36067185-6186362a-0ee2-11e8-8f27-1b7254007eee.png)

But when I'll try to send form data it returns some error.

![image](https://user-images.githubusercontent.com/34867248/36067193-99b4a7a2-0ee2-11e8-8aff-e7dee86b44fa.png)

And here is the code for my post route

#Product.js

```
router.post('/', (req, res, next) => {
    const product = new Product({
        _id: new mongoose.Types.ObjectId(),
        name: req.body.name,
        price: req.body.price
    });
    product.save().then(result => {
        console.log(result);
        res.status(201).json({
            message: 'Created product successfully',
            createdProduct: {
                name: result.name,
                price: result.price,
                _id: result._id,
                request: {
                    type: 'GET',
                    url: `http://localhost:3000/products/${result._id}`
                }
            }
        });
    }).catch(err => {
        console.log(err);
        res.status(500).json({
            error: err
        });
    });
});
```

#Product.model.js

```
import mongoose from 'mongoose';

const productSchema = mongoose.Schema({
    _id: mongoose.Schema.Types.ObjectId,
    name: {type: String, required: true},
    price: {type: Number, required: true}
});

module.exports = mongoose.model('Product', productSchema);
```

I can't find what is the problem.

**Comment by thecuriousdev** [comment]
@tahmid-hasan Actually Postman is sending the data but I don't think you'll get `form-data` in `req.body` directly. Which request body parser are you using?

In case of https://www.npmjs.com/package/body-parser (which is very common). It does not handle multipart bodies, due to their complex and typically large nature.

**Comment by thecuriousdev** [comment]
@tahmid-hasan since there is no response from your side, I assume that this issue got resolved. Please let me know if you are still facing troubles. closing the issue for now.

**Comment by armengrigoryan84** [comment]
@tahmid-hasan  the question was form-data body parser it is different  with "x-www-form-urlencoded" in case if you don't know, your answer will not solve the issue

**Comment by Ladvace** [comment]
I still have this error

**Comment by Ladvace** [comment]
with raw it works but with form-data no, I'm trying to send a file that's why I need form-data

**Comment by arlemi** [comment]
@Ladvace Sounds like an issue on the server-side rather than with Postman. I'd recommend asking the question on community.postman.com. 🙂

**Comment by zaryab444** [comment]
xggxfgxfgxfgxf

**Comment by KaiRogers** [comment]
@tahmid-hasan I have the same exact issue, were you able to resolve it? @thecuriousdev if using body-parser is the issue, which I am using as well. What would you recommend instead to handle multipart bodies?

**Comment by nimeth02** [comment]
> @tahmid-hasan I have the same exact issue, were you able to resolve it? @thecuriousdev if using body-parser is the issue, which I am using as well. What would you recommend instead to handle multipart bodies?

if you solved this..please tell me im in troubble

**Comment by KaiRogers** [comment]
@nimeth02 Its been a minute so this topic is not fresh in my mind, but I want to say I used [`multer`](https://www.npmjs.com/package/multer) which is a node.js middleware for handling multipart/form-data

**Comment by chirag0110** [comment]
Yes, Agree with @KaiRogers. You have to use any nodeJs middleware to handle multipart/form-data. You can use [Multer](https://www.npmjs.com/package/multer) or [Express Fileupload](https://github.com/richardgirges/express-fileupload) for that. [Body parser](https://github.com/expressjs/body-parser) is only handle **raw** data and **x-www-form-urlencoded** data.

I have the same issue, installed express-fileupload and then added this line to server.js

`app.use(fileUpload());
`

Everything is working fine now.

**Comment by felixdusengimana** [comment]
> Yes, Agree with @KaiRogers. You have to use any nodeJs middleware to handle multipart/form-data. You can use [Multer](https://www.npmjs.com/package/multer) or [Express Fileupload](https://github.com/richardgirges/express-fileupload) for that. [Body parser](https://github.com/expressjs/body-parser) is only handle **raw** data and **x-www-form-urlencoded** data.
> 
> I have the same issue, installed express-fileupload and then added this line to server.js
> 
> `app.use(fileUpload()); `
> 
> Everything is working fine now.

This really saved my day. 
thanks @chirag0110

**Comment by felixdusengimana** [comment]
> Yes, Agree with @KaiRogers. You have to use any nodeJs middleware to handle multipart/form-data. You can use [Multer](https://www.npmjs.com/package/multer) or [Express Fileupload](https://github.com/richardgirges/express-fileupload) for that. [Body parser](https://github.com/expressjs/body-parser) is only handle **raw** data and **x-www-form-urlencoded** data.
> 
> I have the same issue, installed express-fileupload and then added this line to server.js
> 
> `app.use(fileUpload()); `
> 
> Everything is working fine now.

This really saved my day. 
thanks @chirag0110

**Comment by truong264vu** [comment]
use multer! i'm fixed this err;

/ in 

> main.js

const multer = require('multer');
const upload = multer();
dotenv.config();
//connect DB
mongoose.set("strictQuery", false);
mongoose.connect((process.env.MONGODB_URL), () => {
    console.log('connected to MongooseDB');
})
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({extended: true}));
app.use(upload.array());

**Comment by agengpangestu** [comment]
> use multer! i'm fixed this err;
> 
> / in
> 
> > main.js
> 
> const multer = require('multer'); 
> const upload = multer(); 
> dotenv.config(); 
> //connect DB 
> mongoose.set("strictQuery", false); 
> mongoose.connect((process.env.MONGODB_URL), () => { 
> console.log('connected to MongooseDB'); 
> }) 
> app.use(bodyParser.json()); 
> app.use(bodyParser.urlencoded({extended: true})); 
> app.use(upload.array());

this work for me, thanks

**Comment by royboylab** [comment]
after adding these 2 lines , the issue was solved

```
const upload = multer();
app.use(upload.array("image"));
```

"image" is the fieldname for the file
