### ISSUE TITLE
Enhance Text Area for writing tests in postman

### ISSUE THREAD

**Issue by cyberhck** [a85/POSTMan-Chrome-Extension#4170]
## App Details:

```
Postman helps you develop APIs faster
Postman for Linux
Version 5.5.2
linux 4.13.0-32-generic / x64
```
### Feature Request
Right now writing the tests for API part is a simple textarea, it's a time consuming process, and honestly, it doesn't help much.

We must improve this a bit, at least a little bit. First, it's using JavaScript and postman's all objects are known anyway, so a little bit of autocomplete would be nice. If not, just add typescript compiler support which will help us.

What I'm thinking of now is to make that text area a rich text area, then add autocomplete based on what context it is. At least for texting, when user types `pm2.` we could do some autocomplete there so we can save some time. (or enable a way to open that in my IDE, where I can configure it myself)

**Comment by thecuriousdev** [comment]
@cyberhck thanks for suggesting this, we will keep you posted in  https://github.com/postmanlabs/postman-app-support/issues/3919
