### ISSUE TITLE
Unable to right click + paste in postman request url bar

### ISSUE THREAD

**Issue by govindrai** [a85/POSTMan-Chrome-Extension#4174]
Version 5.5.2 (5.5.2)
OSX El Capitan 10.11.6 (15G1217)

Context Menu doesn't showup when right-clicking. Therefore there is no option to paste.

**Comment by preethammavin** [comment]
Hey thanks for reporting the issue, we will be fixing it in our future releases.

**Comment by prashantagarwal** [comment]
@govindrai This is fixed in our latest version of Postman app.
