### ISSUE TITLE
Feature Request - create request in folder

### ISSUE THREAD

**Issue by ben-eichler-abcs** [a85/POSTMan-Chrome-Extension#4177]
## App Details:
Postman for Windows
Version 5.5.2
win32 10.0.16299 / x64

**Scenario**
I am starting to create a collection of requests that will cover our codebase. I've scaffolded my requests into folders, I have about 3 levels of depth, with some folders containing 20+ subfolders. My requests mostly sit in the deepest level, and I want to be able to save them there quickly.

**Problem**
Each of the ways of creating a request is funnelled through the Save Request dialog, which only permits viewing 3 folders at a time. Look at how teeny tiny the scrollbar is in the folder selection UI element...

![image](https://user-images.githubusercontent.com/31116939/36122232-7fbcfa08-10ad-11e8-99c5-b70bc637712d.png)

While the search is great, I've already got the folder tree expanded in the navigation pane...

**Suggested Improvement**
 The ideal way for me to create a request would be to right-click on a folder and have an Add Request option. This could still launch the Save Request dialog, and pre-populate the folder the request will be saved to with the folder I right-clicked on.

EDIT: A workaround is to duplicate the request in folder, but that's not the best solution...

**Comment by sivcan** [comment]
Hi @ben-eichler-abcs - Thanks for this suggestion. 
I'll be putting it up as a feature request.

**Comment by sivcan** [comment]
@ben-eichler-abcs We've added this in our latest release. (**v6.2.3** as of now)
It's available in the sidebar for collection and folders and in the collection browser.

Eg: 
_Sidebar_
![image](https://user-images.githubusercontent.com/12631777/43703643-03b7704e-997b-11e8-8661-29c2e85e8e27.png)

_Collection Browser_
![image](https://user-images.githubusercontent.com/12631777/43703741-646d7348-997b-11e8-846e-cff4e9fe315e.png)

_Also right-click support (context menu)_
![image](https://user-images.githubusercontent.com/12631777/43703651-0e552e92-997b-11e8-9f05-d1362de11f7e.png)
