### ISSUE TITLE
Error: ESOCKETTIMEOUT

### ISSUE THREAD

**Issue by Kisong75** [a85/POSTMan-Chrome-Extension#4178]
## App Details:

```
Postman for Windows
Version 5.5.2
win32 10.0.16299 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there: Always happen
 2. Expected behaviour: Postman show receive json response
 3. Console logs 4. Screenshots (if applicable)
![image](https://user-images.githubusercontent.com/28249715/36140100-61119ae2-10e3-11e8-9f52-63cac4f210f6.png)

**Comment by Kisong75** [comment]
Any progress? uninstall-reinstall, updates programs are not working.

**Comment by prashantagarwal** [comment]
@Kisong75 Can you update to the latest Postman App. Let me know if issue still persists.

**Comment by Kisong75** [comment]
Current version is v6.0.10 and this bug is still happening.
