### ISSUE TITLE
Feature Request: Hostname selection

### ISSUE THREAD

**Issue by bisoldi** [a85/POSTMan-Chrome-Extension#4180]
At the moment, while developing, I test my API's by starting up the Spring application locally in Eclipse and hitting the API's with Postman.  Then when I deploy, I test the deployed API's using Postman.  This requires 2 different requests created in Postman, I typically differentiate by putting "(local)" or "(live)" in the request name.

It would be awesome if either the hostname were separated from the path so that multiple hostnames could be put into the request (and you choose one to send the request) or simply allow multiple URL's to be saved (and again, you choose one).  The former sounds like a much better idea than the latter...

I don't know if this can be done via scripting in Postman, I simply use the UI to save and run the API requests.

**Comment by anthony-cole** [comment]
I was about to request the same thing, when I scanned down and saw this!!! This will be a huge improvement to user productivity.

There should be a way to select the host name which is separate from the requests some how.
I should be able to keep testing with a selected QA host, but choose and send different requests which will all go to that host rather than keeping multiple sets of saved requests.

Perhaps in the address bar for one mode you allow the user to "hardcode" a host name, or in an alternative "dynamic host" mode only the request path can be specified with the host coming from another drop down box of configured hosts.

**Comment by sivcan** [comment]
@bisoldi - Pardon me if I got you wrong.
As per my understanding, you're using two different url's for the requests.
The end points for your API's are obviously the same.
Just the host-url changes from local to live.

Have you tried using variables in postman ?
You can save a url as a variable in postman (maybe an environment variable or a global one).

My suggestion would be that you create two environments for your requests:
1. Local
2. Live 

Next you can add a variable to the request.
**{{baseUrl}}/your/api/endpoints**

Now you can simply switch your environments and your requests will simply hit the correct endpoints with the host-url's being resolved.

On how to use the variables you can refer this documentation : https://www.getpostman.com/docs/postman/environments_and_globals/variables

If you want more help regarding using the variables then I'd be glad to assist you.

If I didn't get you right then please let me know and I'll try to help you correctly.

**Comment by bisoldi** [comment]
@sivcan I had not, but I just tried it and it works perfectly.  I then had the thought that this wouldn't really work if I were working on multiple projects, each project had its own local and live URL and then figured out that Postman allows you to chain the variables, so I can set the Environment variable {{baseUrl}} -> {{live}} || {{local}} and then define {{live}} and {{local}} in the folder variables!!

Very awesome.

Only other suggestion is, it looks like it will be very easy to forget which environment you've got set.  Maybe a way to have the environment change some basic UI stuff, like background color or something that makes it pretty obvious?

Thanks for the tip!

**Comment by bisoldi** [comment]
@sivcan Funny thing...It seemed to be working with the chained variables (i.e. I set the environment variable {{baseUrl}} -> {{local}} and then a folder variable {{local}} -> localhost and then put {{baseUrl}} in the URL) and it worked.  I then decided to try moving {{local}} -> localhost from a folder variable to a global variable and changed some other names to be reflective of the project...And now, it doesn't work.  It doesn't even work putting it back as a folder variable.  I get the following as my response:

```Could not get any response
There was an error connecting to http://%7B%7local%7D%7D:8787/api/v1/.....```

Is this supposed to work?  Or maybe there was just something cached before and that's why it worked?  Or maybe I'm just losing it....

Thanks.

**Comment by sivcan** [comment]
@bisoldi That should just work out of the box. Just make sure to not put the curly brackets in the name of any variable. For reference please see my screenshot below
![image](https://user-images.githubusercontent.com/12631777/36296936-d407a774-1315-11e8-8ad1-79d04ff92072.png)

**Comment by bisoldi** [comment]
That worked!  Not sure what I was thinking....Thank you!

**Comment by sivcan** [comment]
@bisoldi - No problem :D
