### ISSUE TITLE
How to avoid duplicate code. 

### ISSUE THREAD

**Issue by AmyB123** [a85/POSTMan-Chrome-Extension#4182]
I have around 100 scenarios which need to be tested with different set of JsonFile, but the result we get can be verified with one single function, at present using Postman I have to copy the same code 100 times and then execute that with different array values. 

Is there a way to avoid this such that we write one function and call that and use the code by giving the array values in the individual TestScript(like parametrized function in Java)

Any Quick help will be highly appreciated  .

```
Postman for Mac
Version 4.11.0
OS X 16.4.0 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:
 2. Expected behaviour:
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 4. Screenshots (if applicable)

**Comment by Chris-Yarland-Price** [comment]
have you tried using the test area in teh folder or collection these are run for every request in the folder or collection and for somethings work much better if you have multiple requests with the same expected results

**Comment by kamalaknn** [comment]
@AmyB123 

You can try out out collection/folder level scripts to organize your scripts. You can find the documentation [here](http://blog.getpostman.com/2017/12/13/keep-it-dry-with-collection-and-folder-elements/).

I'm closing this issue. You can find more examples/answers on our community page - https://community.getpostman.com/
