### ISSUE TITLE
Feature request: Toggle folders in collections active/inactive

### ISSUE THREAD

**Issue by aprixon01112017** [a85/POSTMan-Chrome-Extension#4187]
So one can easily test selectively certain requests.

**Comment by kamalaknn** [comment]
@aprixon01112017 Thanks for your feedback.

I am marking this as a feature request.

Though it is not possible to toggle off folders, you can still selectively run folders in the collection runner. You can also use the `setNextRequest` to control your execution to skip folders. [Read More](https://www.getpostman.com/docs/postman/collection_runs/building_workflows).

**Comment by malvikach** [comment]
Closing this ticket, as we are tracking this as a feature request [here](https://github.com/postmanlabs/postman-app-support/issues/10676)
