### ISSUE TITLE
Code completion in JavaScript editor

### ISSUE THREAD

**Issue by jawn** [a85/POSTMan-Chrome-Extension#4188]
## App Details:
```
Postman for Windows
Version 5.5.2
win32 10.0.16299 / x64
```

## Question

As a postman user writing Chai style tests in javascript, I wish to see code completion to speed up writing tests.

Is this possible or on the roadmap?

Alternatively, can you use an external editor (VS Code, Atom...) to achieve this?

**Comment by kamalaknn** [comment]
@jawn 

Thanks for your feedback. I'm marking this as a feature request.

Unfortunately there is no way edit the requests in an external editor now.

**Comment by cbarrerah-sogeti** [comment]
I'd really like that too :)

**Comment by DannyDainton** [comment]
Code completion has been added to the editor.

<img width="979" alt="image" src="https://user-images.githubusercontent.com/17089546/176871602-4ee22229-dfeb-44fa-b21c-e6b6855ac119.png">
