### ISSUE TITLE
Overriding with *No Auth* doesn't always work

### ISSUE THREAD

**Issue by hongaar** [a85/POSTMan-Chrome-Extension#4191]
## App Details:

```
Postman for Windows
Version 5.5.2
win32 10.0.16299 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:
**Just recently encountered this problem, but may have always been there...**

 2. Expected behaviour:
**When creating a new collection and specifying a default authorisation mechanism, I expect requests in that collection to not use that authorisation mechanism when an individual request uses _No Auth_ (instead of _Inherit auth from parent_).** 

 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
**n/a**

 4. Screenshots (if applicable)
**n/a**

## Details

Seems to only happen
- When importing a collection from the *Run in Postman* button on our Postman documentation site
- When running a collection with *newman* (v3.9.3, loading from `https://www.getpostman.com/collections/[id]`)

When manually exporting/importing the collection in the Postman app, everything works fine.

**Comment by sivcan** [comment]
Hi @hongaar, we'll try to reproduce this issue and get back to you.

**Comment by sivcan** [comment]
@hongaar - Can you update to the [Latest version - Postman 6](https://www.getpostman.com/apps) and let us know if the issue still persists for you?
Feel free to reopen this if it does.

**Comment by hongaar** [comment]
Hi @sivcan, I'll look into this again and update this issue if I still encounter the same problem.
