### ISSUE TITLE
Postman with TLS1.2 

### ISSUE THREAD

**Issue by vbikash** [a85/POSTMan-Chrome-Extension#4192]
Have anyone used POSTMAN with TLS1.2 ? We are moving away from SOAP UI to POSTMAN to test our webservice. I am able to get response with http. After  enabling SSL, added crt, key and paraphase i am getting error.  I am able to invoke the same wsdl through the browser. Our application only accepts TLS1.2 and not sslv3 .

getting error
here was an error running your collection: write EPROTO 101057795:error:14094412:SSL routines:ssl3_read_bytes:sslv3 alert bad certificate:c:\projects\electron\vendor\node\deps\openssl\openssl\ssl\s3_pkt.c:1487:SSL alert number 42 101057795:error:1409E0E5:SSL routines:ssl3_write_bytes:ssl handshake failure:c:\projects\electron\vendor\node\deps\openssl\openssl\ssl\s3_pkt.c:656:

**Comment by vbikash** [comment]
solved

**Comment by ronikrajan** [comment]
I get this same error  using Postman 6.0.10. How was it solved? Is there a patch? Where can I see description of how this issue was solved?
