### ISSUE TITLE
file get corrupted after uploading from post man

### ISSUE THREAD

**Issue by karthiag93** [a85/POSTMan-Chrome-Extension#4195]
image file getting corrupted after sending from post man to local drive using java in Springs...
please help me out from this problem,
code:
public void upload(MultipartFile imageFile)
{
File fe = new File("/home/new/imageFile.png");
FileOutputStream outputStream = new FileOutputStream(fe);
outputStream.write(imageFile.getBytes());
outputStream.close();
}

**Comment by harryi3t** [comment]
Are you able to upload the image from some HTML page?

**Comment by karthiag93** [comment]
No..  The problem is with the filter which I put in ma code, namely logger
filters
