### ISSUE TITLE
NTLM authentication does not work in conjunction with 302 redirect

### ISSUE THREAD

**Issue by foresterr** [a85/POSTMan-Chrome-Extension#4196]
## App Details:

```
Postman for Windows
Version 5.5.3
win32 10.0.15063 / x64
```

## Issue Report:
I'm trying to connect with NTLM authorization to an API which initially responds with 302: Authorize at this location redirect. It seems that after receiving www-authenticate:"NTLM" from the redirect location, Postman tries to send the NTLM authorization header to the original URL instead of the redirected one.

**Comment by harryi3t** [comment]
@foresterr Can you test this flow in a browser. Is that handled properly?

**Comment by harryi3t** [comment]
@foresterr Confirmed the issue. Marking this as a feature request.

**Comment by jd-carroll** [comment]
What more investigation needs to be performed? This would be an incredibly useful feature within our infrastructure and more than willing to help with any implementation.

Was this working within the Chrome App version of Postman?

**Comment by coditva** [comment]
@foresterr @jd-carroll This behaviour can be used in the Postman App by enabling the option `Follow Authorization Header` in the `Settings` tab in the Request Builder.

![image](https://user-images.githubusercontent.com/8445768/69322952-cf77f280-0c6b-11ea-83c7-5661955c8f79.png)

Note: You would need to have `Automatically follow redirects` setting to be `on` too.
Do let me know if you face any issues. :)
