### ISSUE TITLE
Web alternative to "pm"?

### ISSUE THREAD

**Issue by allyn-psyonix** [a85/POSTMan-Chrome-Extension#4200]
We write our tests in the standalone client but they are executed by our automated build process via a web interface. I found out the hard way that "pm" is only supported in the standalone client when the tests started failing only during the automated build process.

Is there an alternative test form that works with both the standalone client and web interface?

**Comment by vdespa** [comment]
Which web interface are you referring to? Postman Monitors?

**Comment by harryi3t** [comment]
Same question as posted by @vdespa.

If you were referring to Postman Monitor then could you let us know which method in pm API is not working for you on Postman Monitors and working in the native app

If you were referring to Postman Chrome App then please be advised that the Postman Chrome App is now deprecated and we are not adding new features to it

**Comment by allyn-psyonix** [comment]
Just touched base with the dev who did the build pipeline integration and it sounds like it's not a web interface we are using for that, it's the Newman CLI. The "pm" object itself does not appear to be available when our tests are run via Newman. The "tv4" object also doesn't appear to be available for schema validation. Older tests that work are using the old API, appending tests to the "tests" array.

The error when trying to reference "pm" is "ReferenceError  pm is not defined"
e.g. > var data = pm.response.json();

The error when trying to reference tv4 is "TypeError  Cannot read property '$ref' of undefined"
e.g. > tv4.validate(instance, schema);

**Comment by harryi3t** [comment]
@allyn-psyonix Closing this ticket here. Please open a separate issue on here https://github.com/postmanlabs/newman/issues

I would have opened an issue on your behalf but for that more information is required (like Newman version, usage type (CLI/library), etc)

Also, put a minimal example which fails in Newman so that it's easy to reproduce.

**Comment by allyn-psyonix** [comment]
Thanks, opened issue in the proper place. Linking for reference: https://github.com/postmanlabs/newman/issues/1438
