### ISSUE TITLE
[question & feature request]  Being able to change the order of Examples

### ISSUE THREAD

**Issue by ghost** [a85/POSTMan-Chrome-Extension#4201]
Hi, is there any way to change the order of example? I am making a documentation now
(well, I would like to change the order like drug and drop)
![image](https://user-images.githubusercontent.com/13827579/36294831-75fafb50-1337-11e8-9f5b-5f42c8463093.png)

thanks in advance!

**Comment by harryi3t** [comment]
@takuyaokamoto11 Duplicate of https://github.com/postmanlabs/postman-app-support/issues/1070
This is not supported yet. Please subscribe to the original issue for updates
