### ISSUE TITLE
URL Parameter disappears when unchecked

### ISSUE THREAD

**Issue by hallem** [a85/POSTMan-Chrome-Extension#4204]
## App Details:

```
Postman for Windows
Version 5.5.3
win32 6.3.9600 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there: Within the last couple of months. Just starting to be really bothersome.
 2. Expected behaviour: There are URL params defined and when editing them, if you have duplicates for different test cases, when you uncheck one and check the other, one disappears. I'd expect that not to happen.
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app): Can't export them from the windows app.
 4. Screenshots (if applicable)
![image](https://user-images.githubusercontent.com/1198158/36324806-7a8bb862-130a-11e8-9e4b-cce97f8ec195.png)
![image](https://user-images.githubusercontent.com/1198158/36324821-84b728ee-130a-11e8-885a-06fc15457e41.png)
![image](https://user-images.githubusercontent.com/1198158/36324826-8d68e5d6-130a-11e8-95ea-33991a06c905.png)

**Comment by harryi3t** [comment]
@hallem Thanks for reporting this bug. I was able to reproduce this.
Will fix and keep you posted on the status here.

**Comment by harryi3t** [comment]
@prashantagarwal 
![issue](https://user-images.githubusercontent.com/5207331/36338693-c20b4712-13db-11e8-828c-806aaa15dc86.gif)

**Comment by sujayvenaik** [comment]
https://github.com/postmanlabs/postman-app-support/issues/4513

Hey, this is a duplicate issue already present.
Can you follow the thread above mentioned for follow ups.
