### ISSUE TITLE
Feature Request: Dynamic Values

### ISSUE THREAD

**Issue by Marko298** [a85/POSTMan-Chrome-Extension#4207]
Support for dynamic values and plugins for them like Paw has

**Comment by sdnts** [comment]
Hi @Marko298, what exactly do you mean by dynamic values? Are you talking about [dynamic variables](https://www.getpostman.com/docs/postman/environments_and_globals/variables#dynamic-variables)?

**Comment by Marko298** [comment]
Yup, I mean dynamic variable that can be used in requests and can be
extended using js

**Comment by sdnts** [comment]
@Marko298 Unless I totally misunderstood what you're saying, environments & global variables would behave the way you want, have you taken a look at those?

**Comment by sivcan** [comment]
Closing this issue.
If you need further assistance regarding the same, feel free to reach out to us.
