### ISSUE TITLE
Sync issue re-sync causes complete loss of collection

### ISSUE THREAD

**Issue by mattboothman** [a85/POSTMan-Chrome-Extension#4208]
## App Details:
Postman for Windows
Version 5.5.3
win32 10.0.16299 / x64

## Issue Report:

When duplicating folders in a collection containing requests sometimes postman throws a 'wobbly' and shows the sync issue dialog which I usually check issues and click re-sync on and continue. On this occasion after clicking re-sync all folders and requests that were contained within my collection have vanished.

Not only that but every request and folder from every collection has vanished.

## Steps to reproduce the problem

Intermittently!!!!
1. Duplicate a folder within a collection containing requests of various types
2. Edit requests in the new duplicated folder
3. Save
4. Sync issue dialog appears
5. Click re-sync
6. Work vanishes!

**Comment by sdnts** [comment]
Hi @mattboothman, before you start duplicating the folders, does the Sync icon on the top right say `In Sync`?
Also, can you try this on our Canary channel? We've pushed major updates to the Sync flow so issues like this should not happen. If it still does happen, please let me know here so we can investigate further.

You can download our Canary builds here:
Windows [x86](https://dl.pstmn.io/download/channel/canary/windows_32) or [x64](https://dl.pstmn.io/download/channel/canary/windows_64)

**Comment by mattboothman** [comment]
Unfortunately I didn't notice about the sync icon. In retrospect I'd hope the app wouldn't let me make changes that may confuse it if sync is in progress?

Sorry, all the work is lost now, unless you can let me know how to get it back (is cloud stored, no)? I'll be working with Postman in offline mode permanently, now. Can't afford another incident like last night. No more sync issues or duplication problems for me.

Thanks

Matt

**Comment by mattboothman** [comment]
It'd be awesome if the app would make like a really loud, startling noise, additionally un-mute my speakers, increasing volume to 11 and make the screen flash like a really bright red colour with the words "DANGER" in like a garish yellow. An electrical current could be triggered that instantly repels my hand from the trackpad would be a bonus.

That way I'd see that Postman is syncing and think - Hmm, best not do that thing that'd make it angry enough to delete all my work again.

**Comment by claireriley** [comment]
Hi @mattboothman - I'm sorry to hear this happened to you and would like to help where I can. I've emailed you via help@getpostman.com with more information.

**Comment by kamalaknn** [comment]
@mattboothman 

We've pushed our recent changes to the stable channel. Could you update your app to the latest version and check if the issues still exist?

**Comment by mattboothman** [comment]
In all honesty, I dearn’t do anything to upset it now. It’s fine, at the moment, with sync disabled. Kinda feel like turning Sync back on might just make the world end.
