### ISSUE TITLE
Lost all data and not able to re-sync

### ISSUE THREAD

**Issue by tarunlalwani** [a85/POSTMan-Chrome-Extension#4211]
## App Details:

```
Postman for Mac
Version 5.5.3
OS X 10.13.3
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there: recently
 2. Expected behaviour:
Colelctions are loaded
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):

Getting an error and not able to sync the collections

Uncaught TypeError: Cannot convert undefined or null to object
    at requester.js:253323
    at arrayEach (common.js:1440)
    at Function.forEach (common.js:9929)
    at child._processRequests (requester.js:253321)
    at requester.js:253266
    at IDBRequest.cursorRequest.onsuccess (requester.js:284177)

 4. Screenshots (if applicable)

**Comment by sdnts** [comment]
Hi @tarunlalwani, I'm guessing the Sync icon on the top right is stuck on `Syncing`, right?

Can you head over to your [Collections Dashboard](https://app.getpostman.com/dashboard/collections/private) and check if your private and team collections are up to date? If they are, signing out + signing back in should solve your issue.

We've also made major improvements to the way the app syncs your data. Can you also download our Canary app and see if this happens there as well? [Mac Canary](https://dl.pstmn.io/download/channel/canary/osx_64)

**Comment by tarunlalwani** [comment]
@madebysid , I am not able to Sync after logout, delete data and re-login. I think something has got synced up to the data and that is creating error in re-sync. I will try the canary build now and report back

**Comment by tarunlalwani** [comment]
@madebysid , Able to Sync in the canary build but not in 5.5.3

**Comment by sdnts** [comment]
@tarunlalwani Ah awesome, we'll be rolling out a stable build in the coming week, so this should be solved then. Thanks for reporting!

**Comment by kamalaknn** [comment]
Hi @tarunlalwani,

We've rolled the fix in our stable channel. Please update your app to the latest version.

**Comment by tarunlalwani** [comment]
Works fine now, thanks for the update
