### ISSUE TITLE
Not able to Intercept from genymotion app using Interceptor

### ISSUE THREAD

**Issue by sanjogpandasp** [a85/POSTMan-Chrome-Extension#4212]
## App Details:

```
Postman for Mac
Version 5.5.3
OS X 17.3.0 / x64
```

## Issue Report:
I have setup postman interceptor from the postman mac app. My android app is running on genymotion. I have setup to the instruction as [here](http://blog.getpostman.com/2016/06/26/using-postman-proxy-to-capture-and-inspect-api-calls-from-ios-or-android-devices/) .

I am not able to intercept the request from the app. But I am able to intercept from the web browser after accepting the certificate popup. 

I suspect that I have to export postman's certificate and install in my genymotion device as postman is acting like a proxy for the app traffic. 
But I could not find how to do it.

 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 4. Screenshots attached below. 
<img width="475" alt="screen shot 2018-02-19 at 2 30 35 pm" src="https://user-images.githubusercontent.com/5404943/36369711-4eacb370-1582-11e8-95ad-f71219c300f8.png">
<img width="468" alt="app" src="https://user-images.githubusercontent.com/5404943/36369712-4ee77f78-1582-11e8-9a1d-68aa6d439cbc.png">

**Comment by numaanashraf** [comment]
@sanjogpandasp Thanks for reporting this. We do not fully support https requests at the moment via the Postman Proxy. We are working on various improvements to this feature at the moment and will keep you posted.

**Comment by sanjogpandasp** [comment]
Thanks for the update.

**Comment by DannyDainton** [comment]
The proxy now supports HTTPS Endpoints:

https://blog.postman.com/postmans-proxy-now-fully-supports-https-endpoints/
