### ISSUE TITLE
Not able to send client secret with Postman's Authorize section using Oauth2. 

### ISSUE THREAD

**Issue by suhaboncukcu** [a85/POSTMan-Chrome-Extension#4213]
## App Details:

```
Postman for Mac
Version 5.5.3 (5.5.3)
OS X 10.13.2  / x64
```

## Details

I'm using Postman app's Authorize section to authorize and get access token from my api using Oauth2 server. 

When I try to validate my client, I've realized that Postman doesn't send "Client Secret" to my server at all. I also tried to reproduce this with a requestb.in call but I can't see my client secret delivered whereas I can retrieve my client id without a problem.

**Comment by numaanashraf** [comment]
@suhaboncukcu Thanks for reporting. We are looking into this and will get back to you if we need more information to triage this issue.

**Comment by harryi3t** [comment]
@suhaboncukcu Are you trying `Client-Authentication` in header or body?
As per the [RFC](https://tools.ietf.org/html/rfc6749#section-2.3.1)
If sent in header, then it will sent as base64 encoded value of `clientId:clientSecret`
If sent in body, then client_Id and client_secret are sent separately

I suspect your authorization server only supports credentials being passed in body. Please try changing the dropdown  value to `Send client-credentials in body`

![image](https://user-images.githubusercontent.com/5207331/36412304-9e90104a-163f-11e8-9a43-cb67ee8ab5bc.png)

**Comment by suhaboncukcu** [comment]
@harryi3t I've already tried that. But no chance. I am also, able to get client id. Just not the client secret. I am not able to get the client secret from Requestb.in neither btw.

**Comment by harryi3t** [comment]
@suhaboncukcu Please share the following screenshots to help us debug this
1. The `Get New Access Token` Modal
![postman](https://user-images.githubusercontent.com/5207331/36429439-b6c9cce4-1678-11e8-8d58-c0e9d97d3eb9.png)

2. The request headers/body sent out. Open postman console before sending the request
![postman_console_and_postman](https://user-images.githubusercontent.com/5207331/36429670-51759228-1679-11e8-9402-8f0f99e3cf6d.png)

Please blur out sensitive data (clientId, clientSecret, etc)

**Comment by suhaboncukcu** [comment]
_(Do not mind the sensitive data, they are changed and not actually sensitive)_
Thanks @harryi3t for your response. Indeed, I am able to see the client secret sent within request body when I choose it as below:

![bodyrequest](https://user-images.githubusercontent.com/2428828/36469805-8be34e20-16f9-11e8-9276-21ce41f78a97.png)
![bodyrequestload](https://user-images.githubusercontent.com/2428828/36469806-8bff3fa4-16f9-11e8-982d-422d49a7b99f.png)

**However, I don't see the client secret when I request as below:** 
![headerrequesty](https://user-images.githubusercontent.com/2428828/36469857-c4114662-16f9-11e8-8113-ee5b4df001f8.png)
![headerrequestload](https://user-images.githubusercontent.com/2428828/36469860-c7b16f7c-16f9-11e8-8282-a72e94a4a38b.png)



I am building my own Oauth2 server and I want to support client authentication when it's sent through headers. It is most probably my lack of knowledge in the matter but I can't seem to find `clientId:clientSecret`  anywhere.   Shouldn't I able to see this value somewhere in the request load?

**Comment by harryi3t** [comment]
@suhaboncukcu As mentioned in my first comment, 
 
> If sent in header, then it will sent as base64 encoded value of clientId:clientSecret
> If sent in body, then client_Id and client_secret are sent separately

base64 of `1:1` is `MTox` which is being sent in the headers
```
authorization: Basic MTox
```

Please refer the RFC for more details https://tools.ietf.org/html/rfc6749#section-2.3.1
