### ISSUE TITLE
Not Using Correct Environment Variable when Duplicate Keys Exist

### ISSUE THREAD

**Issue by Bauerna** [a85/POSTMan-Chrome-Extension#4214]
## App Details:
```
Postman for Mac
Version 6.0.2
OS X 16.7.0 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:
This issue started after updating from 5.X to 6.0.2 (I believe it was 5.5 but I don't know for sure)
 2. Expected behaviour:
When two keys with the same value exist in the environmental variables, it will warn the user of duplicate keys, but if one of they keys are not checked then the value that IS checked will be used and the error will go away. On the newest update, when I enable 1 of the duplicate keys, the "code" section shows the correct value being used, but the actual request uses the other value not currently enabled within the environment variables. See the screenshot below for more detail.
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
Console logs are empty when sending the request.
 4. Screenshots (if applicable)
<img width="971" alt="screen shot 2018-02-19 at 10 24 40 am" src="https://user-images.githubusercontent.com/17187736/36387650-2415c2e6-155f-11e8-92a3-4b50aa8539b5.png">

1. Create request with variable in it
2. Create two entries for the variable in your "Environment Variables"
3. Ensure only one of the environment variables are checked
4. The "Code" will show the checked variable in the request, the response will show the unchecked variable being used in the request - Note: The code shows the correct value, the actual request is using an incorrect value. (See screenshots below)
<img width="445" alt="screen shot 2018-02-19 at 10 25 27 am" src="https://user-images.githubusercontent.com/17187736/36387688-3f423a86-155f-11e8-9866-3a893337146f.png">
<img width="463" alt="screen shot 2018-02-19 at 10 25 13 am" src="https://user-images.githubusercontent.com/17187736/36387689-3f4df4f2-155f-11e8-9d46-452ccd8d65fa.png">

**Comment by Bauerna** [comment]
Note:

The request works properly when the duplicate environment variable does not exist, even though only one of the environment variables is checked when there are two variables.

**Comment by harryi3t** [comment]
@Bauerna Thanks for reporting this bug. We are fixing it.
You can expect the fix in the next patch release in next couple of days
