### ISSUE TITLE
json2Xml conversion

### ISSUE THREAD

**Issue by satishchilu** [a85/POSTMan-Chrome-Extension#4215]
## App Details:
```
Postman for Mac
Version 5.5.2 (5.5.2)
Mac OSSierra OS X 10.12.6 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there: New
 2. Expected behaviour: 
      
     Is there a way to convert json to xml in postman? I am writing a collection suite which calls a get API, alter the response and post again, the post API accept only XML request. I couldn't find anyway to convert my json string to xml, please suggest.

     Tried json2xml node module, added and ran collection using newman but found below error message.

**Json2XML conversion code snippet:**

var segXml = json2xml(segment);
            console.log(segXml);

**Error Logs:**

#  failure                     detail

 1.  ReferenceError              json2xml is not defined
                                 at assertion:0 in test-script
                                 inside "getSegments"

 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 4. Screenshots (if applicable)

**Comment by numaanashraf** [comment]
Hi @satishchilu, we do not have a library to help you with json to xml conversion within the Postman scripts. All the available libraries are documented [here](https://www.getpostman.com/docs/v6/postman/scripts/postman_sandbox_api_reference). I'm treating this as a feature request - could you explain your use case?

**Comment by satishchilu** [comment]
Thanks for reply. I have a service which accepts only xml payload. For one of the automation script we are calling multiple services, one service response [comes in Json] we use as input to another service which accepts only xml payload. I feel when we have xml to json conv we should also have reverse.

**Comment by a85** [comment]
This will have to be done on a case-by-case basis. Postman's JS sandbox can help with the conversion.
