### ISSUE TITLE
Ampersand doesn't render properly on navigational side in documentation

### ISSUE THREAD

**Issue by aedelbro** [a85/POSTMan-Chrome-Extension#4216]
## App Details:

```
Postman for Mac
Version 5.5.3
OS X 17.4.0 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there: There since I started using it
 2. Expected behaviour: ampersand shows as & and not `&amp;`
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app): NA
 4. Screenshots (if applicable): https://user-images.githubusercontent.com/36162221/36397713-de53f7fe-1591-11e8-9e48-3213d6cc4b28.png

Have an ampersand in an H1 (# Header name & things) in the description of the collection

**Comment by numaanashraf** [comment]
@aj-edelbrock-bolstra Thanks for reporting this. Could you provide a screenshot for the same? It'll help us triage this issue faster.

**Comment by aedelbro** [comment]
I have the link to the screenshot in the "Screenshots" section. If it's borked, I can upload to imgur.

**Comment by godfrzero** [comment]
This should be fixed now, can you let me know if it's still happening?

**Comment by aedelbro** [comment]
It does appear to be fixed. Thanks.
