### ISSUE TITLE
Postman "Download Collection" file adds body to HEAD requests

### ISSUE THREAD

**Issue by billworkricoh** [a85/POSTMan-Chrome-Extension#4219]
## App Details:

```
Postman for Windows
Version 5.5.3
win32 10.0.10240 / x64
```

## Issue Report:
Download Collection file HEAD requests contain body value.
![image](https://user-images.githubusercontent.com/36681889/36455854-501d4fa2-165f-11e8-946b-c20085de6188.png)

1. Create collection.
2. Add POST request that contains body data.
3. Add HEAD request.
4. Download Collection.
5. Run collection using Newman.
6. Notice error message, "HTTP HEAD requests MUST NOT include a request body."
7. Examine collection file.
8. Notice HEAD request contains body that is the same as the POST request.

**Comment by numaanashraf** [comment]
This is resolved in the latest version of Postman (v6.5.3)
