### ISSUE TITLE
Stopping a collection run with multiple iterations

### ISSUE THREAD

**Issue by aprixon01112017** [a85/POSTMan-Chrome-Extension#4225]
Hi

I want to stop a collection run with let's say 50 iterations on a certain error. How do I do that?

**Comment by sivcan** [comment]
@aprixon01112017 - Right now the only way to stop a run is using the 'Stop Run' button inside the runner.
I'll mark this as a feature request and we'll take a look into it.

**Comment by saswatds** [comment]
Hi @aprixon01112017 you can stop the run by using `postman.setNextRequest(null)`
More on this you can find here https://learning.getpostman.com/docs/postman/collection_runs/building_workflows/

Closing this issue now
