### ISSUE TITLE
Postman does not run on Ubuntu 17.10

### ISSUE THREAD

**Issue by risingfish** [a85/POSTMan-Chrome-Extension#4226]
## App Details:
Downloaded the latest from 
```
Postman for Linux
Version Latest as of 2018/2/21
Ubuntu 17.10 x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:
     Only shows up on newer Debian/Unbuntu systems.
 2. Expected behaviour:
     Postman executable should run
 3. Console logs 
     Trying to run the downloaded Postman executable produces:
    `./Postman: error while loading shared libraries: libnode.so: cannot open shared object file: No such file or directory`

To reproduce:
1. In a VM, or on bare metal, install a fresh instance of Ubuntu 17.10 x64.
2. Install node (via apt). The current version of node in the Ubuntu repo is 6.11.2.
3. Download the x64 binary for Postman stand alone application.
4. Run the binary and you will see the output above.

While the version of node in the Ubuntu rep is old, that doesn't seem to be the cause of the issue. Google searches quickly turn up that this is most likely related to changes in Ubuntu security setup. More specifically this seems seems to be related to:
https://stackoverflow.com/questions/9843178/linux-capabilities-setcap-seems-to-disable-ld-library-path

It seems to be a new and fairly common issue, Postman is not the first app I have had this exact same issue with. I hope it's as easy as changing the build params.

**Comment by harryi3t** [comment]
Postman is built on Electron and electron does not play well with the latest versions of Ubuntu
From https://github.com/electron/electron/issues/4583

> Electron relies on the ability to search for dynamically libraries under the binary's directory, while calling setcap would disable this ability for security reasons. For some people in the original issue, they don't actually need this ability and are able to work around this.

> This is, unfortunately, a limitation of Linux:
> http://stackoverflow.com/questions/9843178/linux-capabilities-setcap-seems-to-disable-ld-library-path

**Comment by morozovsk** [comment]
If postman is built on Electron and now it is not working.
What I can use instead Postman?
