### ISSUE TITLE
Can't escape pipe in table in documentation

### ISSUE THREAD

**Issue by aedelbro** [a85/POSTMan-Chrome-Extension#4227]
## App Details:

```
Postman for Mac
Version 5.5.3
OS X 17.4.0 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there: There since I started using it
 2. Expected behaviour: That if you put a `\|` in a table, the pipe won't create a new column, and it should be displayed as `|`. Or if a `|` is in a code block in a table, then it doesn't split the code block into two columns.
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app): NA
 4. Screenshots (if applicable)
These first 2 are if a `|` is just in a code block. First image is the markdown in the description of a collection, second image is the resulting output on the webview.
![in codeblock markdown](https://user-images.githubusercontent.com/36162221/36496757-4d26ffd4-1707-11e8-89a4-22ee80aeff3a.png)
![in code block ouput](https://user-images.githubusercontent.com/36162221/36496819-79eb9f98-1707-11e8-8b01-daa21bb0dcec.png)
These two are if you attempt to escape it. Same order as above.
![escaped in codeblock markdown](https://user-images.githubusercontent.com/36162221/36496800-6d7750ae-1707-11e8-9e77-8f5fc0e9abfe.png)
![escaped in codeblock ouput](https://user-images.githubusercontent.com/36162221/36496859-99b6a200-1707-11e8-9ca8-ebb33db97c85.png)

In the description of a collection, create a table (such as ones in the screenshots). In an entry, put in a codeblock `sometext | othertext`.  It will break the codeblock and assume you're creating a new column. Even escaping it like `sometext \| othertext` will still split the entry.

**Comment by harryi3t** [comment]
This is the limitation of the markdown renderer that we are using  https://github.com/jonschlinkert/remarkable
Related issue https://github.com/jonschlinkert/remarkable/issues/56 (closed)

Also, note that this is not even supported by Github Markdown
```
# This code is rendered below by Github Markdown

| Col-1     | Col-2 | Col-3 |
|-----------|-------|-------|
|a=0/|/|1   |    b  |  c    |
```
### Output
| Col-1     | Col-2  | Col-3 |
|---------|-------|-------|
|a=0/|/|1  |    b      |    c      |

You can use the HTML encoded value as listed on https://www.w3.org/MarkUp/html-spec/html-spec_13.html
```
# This code is rendered below by Github Markdown

| Col-1     | Col-2 | Col-3 |
|-----------|-------|-------|
|a=0&#124; &#124;1   |    b  |  c    |
```
### Output
| Col-1     | Col-2  | Col-3 |
|---------|-------|-------|
|a=0&#124; &#124;1  |    b      |    c      |

I know this reduces the readability but it the only workaround available as of now.

**Comment by aedelbro** [comment]
Thanks for the response. However, because I'm looking to put this in a code block, it auto-escapes it, preventing transformation of  the `&#124;` into a `|`, so I'm left with something like this: 
![so I'm left with something like this](https://user-images.githubusercontent.com/36162221/36543225-22594ac8-17b1-11e8-8484-bff3e86f6608.png)
Is there a workaround for this workaround in which you can disable a code block's "auto escape"?

**Comment by harryi3t** [comment]
> **workaround for this workaround**  

😆 

Sure, Use this `<code>...</code>`
```js
|                   Col-1                   | Col-2 | Col-3 |
|-------------------------------------------|-------|-------|
|<code>total = bt: 5 &#124;&#124; 6</code>  |    b  |  c    |
```


![postman](https://user-images.githubusercontent.com/5207331/36602229-874e9136-18dd-11e8-8674-96304cfb6270.png)

### How it renders in Postman

![postman](https://user-images.githubusercontent.com/5207331/36602259-97f0d526-18dd-11e8-898f-03a8a275985f.png)

I hope this helps :)

**Comment by aedelbro** [comment]
Thanks! That did the trick. Hopefully the markdown engine will support escaping pipes in the future (and we won't have to have nested workarounds).
