### ISSUE TITLE
Chai "assert" API available in tests?

### ISSUE THREAD

**Issue by allyn-psyonix** [a85/POSTMan-Chrome-Extension#4228]
The test examples reference Chai's "expect" API. Is Chai's "assert" API available? `pm.expect` works but `pm.assert` is not found. I never really liked the whole "let's try to make code sentence-readable" trend and prefer assert-style APIs.

## App Details:
```
Postman for Windows
Version 5.5.3
win32 10.0.16299 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there: only recently tried
 2. Expected behaviour:
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 4. Screenshots (if applicable)

1) Create a postman test and try anything like the following:
> pm.assert.isTrue(true);

**Comment by kunagpal** [comment]
@allyn-psyonix While the [Chai assert](http://chaijs.com/api/assert/) extension is not available at this time, the [inbuilt Node assert library](https://nodejs.org/docs/v6.13.0/api/assert.html) is indeed available. You can use this as follows:
```js
var assert = require('assert');

// do cool stuff with assert here!
```

**Comment by allyn-psyonix** [comment]
Ah, thank you! I did not think of trying that. I'll give that a shot.
