### ISSUE TITLE
Would like to have a paret or master page that provides links and navigation to our collections

### ISSUE THREAD

**Issue by kevinlbatchelor** [a85/POSTMan-Chrome-Extension#4231]
We have several post man documented API, each represents a collection of micro services deployed on AWS. My objective is to have the creation and deployment and hosting all completely completed via CICD so when we update a service with its accompanied documentation, documentation gets release to production as soon as the service hits our master branch.  We have this mostly worked out except a one major obstacles. 

There is no way for me to give out a single URL that is an index of all of our collection, that is hosted on the postman pro site (I do not want to create, manage and host my own site, I'd rather pay postman)

**Comment by a85** [comment]
Hey Kevin! If you are talking about internal APIs then this is exactly what we have been working on. Check out more info on our website at www.getpostman.com/workspaces. Workspaces bring together multiple collections in one place - it is up to you to set the context for a workspace so things can be pretty flexible.

We don't have public workspaces yet but that is on the roadmap.

**Comment by a85** [comment]
Workspaces are out now! https://www.getpostman.com/docs/postman/workspaces/intro_to_workspaces
