### ISSUE TITLE
(Is this possible?) How do I automate to copy the response body in a tab and paste in immediate next tab

### ISSUE THREAD

**Issue by ShekharReddy4** [a85/POSTMan-Chrome-Extension#4233]
Is it possible to automate to copy the response in current and paste in immediate next tab

**Comment by sivcan** [comment]
@ShekharReddy4 - I am afraid you cannot do that in the app.
However, I can help you with a small workaround.

You can store the response of a request to a global / environment.
Put the following script in the `Tests` for the request in the current tab.
```
pm.globals.set('response', JSON.stringify(pm.response));
```

Now in the next tab's **Pre-request** or **Tests** script you can use the response like so
```
let prevResp = JSON.parse(pm.globals.get('response'));
console.log(prevResp);
```

Then use it however you want to. :) 

Remember to clear the global / environment variable after you're done using the responses.

If you need any further help, let me know.
Closing this issue.
