### ISSUE TITLE
Postman working for one request while it doesnt work for other requests

### ISSUE THREAD

**Issue by vilvaathibanpb** [a85/POSTMan-Chrome-Extension#4234]
## App Details:

```
Postman for Mac
Version 4.11.0
OS X 16.4.0 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:
      Recently
 2. Expected behaviour:
      APIs should give response
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 4. Screenshots (if applicable)

**Comment by sivcan** [comment]
@vilvaathibanpb - Kindly update Postman to the latest version.
If there are any steps to reproduce it then provide the same and I'll reopen this issue.
Otherwise, it works well.
