### ISSUE TITLE
Url parameters not encoded and sent twice

### ISSUE THREAD

**Issue by grexe** [a85/POSTMan-Chrome-Extension#4235]
## App Details:
```
Postman for Linux
Version 5.5.3
linux 4.13.0-32-generic / x64
```

## Issue Report:
Url parameters (in my case containing "http://", didn't try others) are not URL encoded when being sent, which triggers a bug in Postman, so they are sent twice (for multiple parameters, all parameters will be sent twice)
They are encoded only when sent via variables.

E.g.:
GET endpoint, Url Parameter: `schemaUri=http://ontologies.semanticarts.com/o/gistTop`

will result in sending:
`GET /api/method?schemaUri=http://ontologies.semanticarts.com/o/gistTop?uri=http://ontologies.semanticarts.com/o/gistTop`

But when entering the encoded parameter directly, it works:
`?schemaUri=http%3A%2F%2Fontologies.semanticarts.com/o/gistTop`

**Comment by grexe** [comment]
seems the hash sign '#' used as anchors but also for classifiers in an ontology is not encoded at all, even when used in a variable.

**Comment by SamvelRaja** [comment]
@grexe  I can see that the request is sent only once in Postman Console.
![capture](https://user-images.githubusercontent.com/5114052/42151198-cf78c27a-7df9-11e8-8d3f-b0f77efdd8de.PNG)
For encoding issue, requesting you to subscribe to #4555

**Comment by grexe** [comment]
ok can confirm, seems to have been fixed in the meantime.
