### ISSUE TITLE
Markdown header id attributes

### ISSUE THREAD

**Issue by nfearnley** [a85/POSTMan-Chrome-Extension#4240]
id attributes are only generated for h1 tags. h2, h3, h4, ... tags do not get id attributes. If I attempt to manually set an id or name attribute, it gets cleared when viewed in the documenter.

Here is the markdown I've tried:
# TEST1HASID
#### TEST4NOID
<h1>TESTH1HASID</h1>
<h2>TESTH2NOID</h2>
<h3>TESTH3NOID</h3>
<h4>TESTH4NOID</h4>
TESTU1HASID
======
TESTU2NOID
------
<div id="DOESNTWORKID">TESTDIV</div>
<a name="DOESNTWORKNAME"></a>

If I add this to my collection description, and view my documentation https://documenter.getpostman.com/collection/view/:collectionid I see the results described above.

**Comment by nfearnley** [comment]
You can actually see how the markdown reacts with github's markdown interpreter. The div and a tags work fine, but no id tags are automatically added.

**Comment by sdnts** [comment]
@nfearnley You're right, we currently generate IDs for h1 tags only. I'm adding this as a feature request.

Out of curiosity though, why would you want to use different heading styles? Is it a matter of formatting?

**Comment by nfearnley** [comment]
I'm using it for subsections in the collection description. I want to be
able to link between them.

**Comment by godfrzero** [comment]
Heading IDs are automatically generated for all heading tags in the public documentation now (h1 - h6).
