### ISSUE TITLE
post method bugged

### ISSUE THREAD

**Issue by Ali-CFD-Alex** [a85/POSTMan-Chrome-Extension#4241]
## App Details:

```
Postman for Windows
Version 6.0.7
OS  windows 10 / x64
```

## Issue Report:
Today i updated postman after update when i chose POST method and try to upload file using form-data at first time its work. But next time try to post file it post nothing ! i have to reopen postman every time...

**Comment by harryi3t** [comment]
@Ali-CFD-Alex I have confirmed the bug to be in 6.0.7
We are working on a fix.
For now, reopening the request should work (instead of reopening Postman)

**Comment by glenpike** [comment]
Workaround - you can select a different file (which might not help) and POST.

**Comment by Ali-CFD-Alex** [comment]
@harryi3t  Removing file field and create new one works too.

**Comment by Ali-CFD-Alex** [comment]
@glenpike Its not work for me. I have some ways like removing file field than create new one , reopening request and some else

**Comment by harryi3t** [comment]
@Ali-CFD-Alex @glenpike 
We have fixed this internally and this fix will be available in the next release.
Thank you for your continued support :)

**Comment by prashantagarwal** [comment]
@Ali-CFD-Alex This is fixed in latest Postman version. Thanks

**Comment by karthiksml** [comment]
We are seeing the same issue now with the latest release 6.2.5 - Windows. Could someone help us here?
