### ISSUE TITLE
Environment variables substitution doesn't work well for query parameters in URL

### ISSUE THREAD

**Issue by cateyes99** [a85/POSTMan-Chrome-Extension#4242]
## App Details:

```
Postman helps you develop APIs faster
Postman for Windows
Version 5.5.3
win32 10.0.14393 / x64
```

## Issue Report:
The substitution of environment variables for query parameters in URL doesn't work well. For example, I have three environment variables, `{{api-version}}`, `{{ampersand}}`, `{{&}}`.

When the values of all the three are empty string then
```
?{{api-version}}              => ?=           [but should be just ?]
?{{api-version}}{{&}}         => ?{{=&}}=     [but should be just ?]
?{{api-version}}{{ampersand}} => ?=           [but should be just ?]
```
Above, if i have `?{{api-version}}{{&}}`, after substitution, it becomes `?{{=&}}=`, but , it should be `?` here.
If i have `?{{api-version}}{{ampersand}}`, after substitution, it becomes `?=`, but , it should be `?` here.

When the value of `{{api-version}}` is `api-version=v1`, `{{ampersand}}` is `&`, and `{{&}}` is `&` then
```
?{{api-version}}              => ?api-version=v1=           [but should be ?api-version=v1]
?{{api-version}}{{&}}         => ?api-version=v1{{=&}}=     [but should be ?api-version=v1&]
?{{api-version}}{{ampersand}} => ?api-version=v1&=          [but should be ?api-version=v1&]
```
If i have `?{{api-version}}{{&}}`, after substitution, it becomes `?api-version=v1{{=&}}=`, but , it should be `?api-version=v1&` here.
If i have `?{{api-version}}{{ampersand}}`, after substitution, it becomes `?api-version=v1&=`, but , it should be `?api-version=v1&` here.

Though the requests sent out by Postman has the wrong substitution, but when clicking the `Code` button under the `Save` button, the popped out `GENERATE CODE SNIPPETS` generates correct HTTP request! So Postman has used different logics to do substitution for `GENERATE CODE SNIPPETS` and the **actual** HTTP request to be sent out! Weird eh. That's why it took me a while to figure out the actual request sent out by Postman has wrong substitution.

But the way, I also tried the **Chrome Postman Extension 5.5.2** on Windows 10. It did work correctly.

**Comment by sdnts** [comment]
@cateyes99 I believe this is the same issue as #3181. Can you also try this on the [Canary build](https://www.getpostman.com/canary) and check if you still see this?

As for the code generation, you're right. We use a third-party [library](https://www.npmjs.com/package/request-snippet-generator) to generate code. The actual request sending flow is handled separately by [postman-runtime](https://github.com/postmanlabs/postman-runtime)

I'm closing this for now, but please let me know if the Canary build does not solve your issue, and I'll reopen :)

**Comment by cateyes99** [comment]
I've tried Canary build version 6.0.8. It fixed the extra `=` appended in query parameters after substitution. But in my report, there is another bug which hasn't been fixed yet. It's when setting up an environment variable called `{{&}}`. Postman Canary **doesn't** not treat it as environment variable at all and no substitution takes place, even the UI **does** recognise it as environment variable.

For example, if the value of `{{api-version}}` is `api-version=v1`, `{{&}}` is `&` and `{{aaa}}` is `aaa=111` given `?{{api-version}}{{&}}{{aaa}}`, Postman Canary sends `?api-version=v1{{&}}aaa=111`, while it should really be `?api-version=v1&aaa=111`.

Or if we let the value of `{{api-version}}` be `v1`, `{{&}}` be `---` and `{{aaa}}` be `111`, given `?{{api-version}}{{&}}{{aaa}}`, the correctly substitution is `?v1---111` , but Postman Canary sends `?v1{{&}}111`.

So #3181 does not cover this issue. I think this one should be re-opened. Note, as I mentioned previously, the `Chrome Postman Extension 5.5.2` works all **fine**!

By the way, if we save such a Http request in collection, and open the saved JSON file, we can see what's wrong in the saved collection JSON file as well. See `"key": "{{api-version}}{{",` and `"key": "}}policySystemOfRecord",` below:
```
"url": {
  "raw": "{{http}}{{host}}{{port}}{{api}}/search/claims?{{api-version}}{{&}}policySystemOfRecord=DATARICH",
  "host": [
    "{{http}}{{host}}{{port}}{{api}}"
  ],
  "path": [
    "search",
    "claims"
  ],
  "query": [
    {
      "key": "{{api-version}}{{",
      "value": "",
      "equals": false
    },
    {
      "key": "}}policySystemOfRecord",
      "value": "DATARICH",
      "equals": true
    }
  ]
}
```

**Comment by cateyes99** [comment]
@madebysid Please see my above comment
