### ISSUE TITLE
How to delete a workspace?

### ISSUE THREAD

**Issue by chimit** [a85/POSTMan-Chrome-Extension#4243]
## App Details:
```
Postman for Mac
Version 6.0.7
OS X 17.4.0 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there: Recently
 2. Expected behaviour: Ability to delete a workspace
 
I can't delete a workspace. I click a "Manage" button, the Postman dashboard is opened in the browser, but I don't see anything about Workspaces there.

**Comment by sivcan** [comment]
Hi @chimit -  You can simply delete a workspace in the app itself.

1). Switch to the 'Browse' view (down-right corner)

<img width="590" alt="screen shot 2018-02-26 at 2 09 47 pm" src="https://user-images.githubusercontent.com/12631777/36660647-ee9d7b40-1afe-11e8-85b0-0606657552bf.png">

2). Then click on '∙∙∙' and delete the workspace that you want to delete.

<img width="769" alt="screen shot 2018-02-26 at 2 10 58 pm" src="https://user-images.githubusercontent.com/12631777/36660681-0df34b6e-1aff-11e8-8475-91e06ed1654f.png">
