### ISSUE TITLE
Authorization information is not shown in published API docs

### ISSUE THREAD

**Issue by galbarm** [a85/POSTMan-Chrome-Extension#4244]
When publishing a collection to create a public api docs, the generated page does not include any information about authorization.
Tested with Bearer Token.
Currently the only way to present information about authorization is to manually add it as header and not use the Authorization feature.

**Comment by sdnts** [comment]
@galbarm Currently, we do not parse any authorization info when rendering the documentation. I'm adding this as a feature request (to show the authorization selected, not the values, obviously).

**Comment by linaspasv** [comment]
@madebysid is there any ETA for this feature?

**Comment by godfrzero** [comment]
No ETA yet, but we're actively working on this feature. I'll post here when I have new updates.

**Comment by steffenschebesta** [comment]
Will this also work with "inherit auth from parent"? https://github.com/postmanlabs/postman-app-support/issues/4912
Any updates on ETA? Currently, docs are basically useless without the auth information...

**Comment by sankalp0o** [comment]
@galbarm @steffenschebesta @linaspasv What kind of auth info are you looking to include in your documentation exactly?

**Comment by steffenschebesta** [comment]
@sankalp0o Basic and Bearer

**Comment by olelis** [comment]
Same problem here. 

For example, if API requires authorization (bearer), you can easily configure it on per-folder/per-project level.
However, this is information is not included on the published documentation (you can add it manually via text, of course).

But worse is that it is not included in the example calls.

**Comment by steffenschebesta** [comment]
@sankalp0o @madebysid @godfrzero any updates on this issue?

**Comment by azarezade** [comment]
Me too, waiting for the feature to be added!

**Comment by benfletcher** [comment]
@madebysid Are there any other aspects of requests that aren't parsed for the docs? 

We're trying to comprehensively document our API for customers and I can't find any information on what gets included in docs and what's excluded or silently ignored.

If it's going to take a while to resolve this issue, a flag in the UI indicating "private" or "hidden" on items that get dropped in the docs would be helpful. Or just a list of them.

**Comment by sdnts** [comment]
@godfrzero Perhaps you'd be able to better address @benfletcher's question :D

**Comment by serhiisol** [comment]
Could you guys take a look at the issue? Crucial piece of information is hidden from generated docs.

**Comment by benfletcher** [comment]
FWIW, [@godfrzero says](https://github.com/postmanlabs/postman-app-support/issues/4912#issuecomment-411006777) that #4912 will also resolve this issue. That issue is currently in the Now column while this one is in Later.

Either way, it's exciting that this issue seems to be getting prioritized. Thank you, it will really help us clean up some annoying duplication!

**Comment by ranchanarajasekaran** [comment]
We have fixed this issue. Please feel free to reopen the ticket to report feedback on the same.
