### ISSUE TITLE
Blank page when trying to use Azure AD Connect v1.0 endpoint for OAuth2

### ISSUE THREAD

**Issue by ngrigoriev** [a85/POSTMan-Chrome-Extension#4246]
I am trying to configure the "Get new access token" feature in Postman to work with Azure AD Connect - to call MS Graph APIs with OAuth2 access token.

After going through the authentication process I get the blank window. The parameters are definitely correct, I am using them to build my own authorization request.

I suspect that it may be because of the pop-up (real pop-up) that is used by AD FS in the final phase of the authentication flow.

## App Details:
```
Postman for Mac
Version 6.0.7
OS X 16.7.0 / x64
```

## Issue Report:
 1. I have observed it for last couple of releases
 2. Expected behaviour: new OAuth2 token is obtained by Postman
 3. Console logs: nothing logged 

I believe there is a couple of similar issues reported but none of them seem to be matching exactly the problem I experience.

Configure "Get new access token" as follows:

Grant type: Authorization Code
Callback URL: (whichever you use, my test one is like http://localhost/dummycallback.html)
Auth URL: https://login.windows.net/common/oauth2/authorize
Access Token URL: https://login.windows.net/common/oauth2/token
Client ID: <Azure app client ID>
Client Secret: <Azure app client secret>
Scope: https://graph.microsoft.com
State: any value
Client Authentication: (irrelevant) Send as Basic Auth header

I use "work/school account" (not MS personal one) and our organization uses AD FS. Specifically, it prompts for the credentials again using with a pop-up.

**Comment by ghost** [comment]
Hi Nikolai,
Can you please verify that the authorisation URL called through Postman for authorisation works on a normal browser? You can do this by performing the following steps:

1. Navigate to the app location on your machine.
2. Right click on the icon ---> Show package contents ---> Contents ---> MacOS
3. Right click on Postman executable and open with terminal.
4. Doing this will launch the Postman app as well.
5. Perform the authorisation process. Once you click the Request Token button there will be a URL that is logged in the terminal. (For example, Opening auth login window https://foo.com/auth/.).
6. Open this link in a browser (incognito mode) and verify whether the auth process goes through successfully.

Kindly let us know about the result.

**Comment by harryi3t** [comment]
@ngrigoriev I tried the same flow in the browser and it is redirecting back to the login windows again and again.
![ezgif com-optimize](https://user-images.githubusercontent.com/5207331/36778928-3b5cc83c-1c94-11e8-9d77-9d625d48c185.gif)

**Comment by ngrigoriev** [comment]
@harryi3t This is NOT work/school account for sure. Hotmail.com would be a personal account. Plus, I am not sure what parameters are you using for oauth2 endpoint.

**Comment by ngrigoriev** [comment]
This is with Postman

![giphy](https://user-images.githubusercontent.com/2364632/36793223-d86209e6-1c6a-11e8-9844-9b34329358fb.gif)

This is what is logged on the console (client ID and username masked):

``Opening auth login window https://login.windows.net/common/oauth2/authorize?response_type=code&state=state0334345341115433540928&client_id=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx&scope=https%3A%2F%2Fgraph.microsoft.com%20openid&redirect_uri=http%3A%2F%2Flocalhost%2Fepoxy%2Fcallback.html
Received redirect on auth login window https://login.microsoftonline.com/common/oauth2/authorize?response_type=code&state=state0334345341115433540928&client_id=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx&scope=https%3A%2F%2Fgraph.microsoft.com%20openid&redirect_uri=http%3A%2F%2Flocalhost%2Fepoxy%2Fcallback.html
URL did not match the registered callbackURL, so skipping
Received redirect on auth login window https://login.microsoftonline.com/common/oauth2/authorize?response_type=code&state=state0334345341115433540928&client_id=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx&scope=https%3A%2F%2Fgraph.microsoft.com%20openid&redirect_uri=http%3A%2F%2Flocalhost%2Fepoxy%2Fcallback.html
URL did not match the registered callbackURL, so skipping
Received redirect on auth login window https://login.microsoftonline.com/common/oauth2/authorize?response_type=code&state=state0334345341115433540928&client_id=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx&scope=https%3A%2F%2Fgraph.microsoft.com%20openid&redirect_uri=http%3A%2F%2Flocalhost%2Fepoxy%2Fcallback.html
URL did not match the registered callbackURL, so skipping
Received redirect on auth login window file:///Users/nik/Desktop/Trader%20Workstation%20968
Uncaught errors TypeError: Cannot read property 'join' of undefined
    at handleUrlChange (/Applications/Postman.app/Contents/Resources/app/services/OAuth2WindowManager.js:73:27)
    at WebContents.<anonymous> (/Applications/Postman.app/Contents/Resources/app/services/OAuth2WindowManager.js:126:7)
    at emitTwo (events.js:111:20)
    at WebContents.emit (events.js:191:7)
Opening auth login window https://login.windows.net/common/oauth2/authorize?response_type=code&state=state0334345341115433540928&client_id=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx&scope=https%3A%2F%2Fgraph.microsoft.com%20openid&redirect_uri=http%3A%2F%2Flocalhost%2Fepoxy%2Fcallback.html
Received redirect on auth login window https://login.microsoftonline.com/common/oauth2/authorize?response_type=code&state=state0334345341115433540928&client_id=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx&scope=https%3A%2F%2Fgraph.microsoft.com%20openid&redirect_uri=http%3A%2F%2Flocalhost%2Fepoxy%2Fcallback.html
URL did not match the registered callbackURL, so skipping
Received redirect on auth login window https://login.microsoftonline.com/common/oauth2/authorize?response_type=code&state=state0334345341115433540928&client_id=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx&scope=https%3A%2F%2Fgraph.microsoft.com%20openid&redirect_uri=http%3A%2F%2Flocalhost%2Fepoxy%2Fcallback.html
URL did not match the registered callbackURL, so skipping
Received redirect on auth login window https://login.microsoftonline.com/common/oauth2/authorize?response_type=code&state=state0334345341115433540928&client_id=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx&scope=https%3A%2F%2Fgraph.microsoft.com%20openid&redirect_uri=http%3A%2F%2Flocalhost%2Fepoxy%2Fcallback.html
URL did not match the registered callbackURL, so skipping
Received redirect on auth login window https://login.microsoftonline.com/common/oauth2/authorize?response_type=code&state=state0334345341115433540928&client_id=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx&scope=https%3A%2F%2Fgraph.microsoft.com%20openid&redirect_uri=http%3A%2F%2Flocalhost%2Fepoxy%2Fcallback.html
URL did not match the registered callbackURL, so skipping
Received redirect on auth login window https://login.microsoftonline.com/common/oauth2/authorize?response_type=code&state=state0334345341115433540928&client_id=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx&scope=https%3A%2F%2Fgraph.microsoft.com%20openid&redirect_uri=http%3A%2F%2Flocalhost%2Fepoxy%2Fcallback.html
URL did not match the registered callbackURL, so skipping
Received redirect on auth login window https://azadfs.newforma.com/adfs/ls/?client-request-id=8a68c7f1-21de-4bdf-939a-5ffd03689b84&wa=wsignin1.0&wtrealm=urn%3afederation%3aMicrosoftOnline&wctx=LoginOptions%3D3%26estsredirect%3d2%26estsrequest%3drQIIAdNiNtQztFKxMEkxsDBKStS1SEpK0TWxABKWxqaJuiYGpiZ.......-sDAuYgW6tojT9IKl9EH_9WL6ynyKPAynWPUj831D_CPCC6Mys_1dQwICPT29nbNC9LOTM51ccqL00_wjM93TSpw9jYtCbS2sDCewMX5gY9jFqQJyI9CJOfnJiTkZ-cUl-qkF-RWV-kBeTlJicrZeRkluzi0uESMDQwtdAyNdIwsFQxMrIxMrY8MoAA2&cbcxt=&username=username%40newforma.com&mkt=&lc=
URL did not match the registered callbackURL, so skipping
Received redirect on auth login window https://azadfs.newforma.com/adfs/ls/wia?client-request-id=8a68c7f1-21de-4bdf-939a-5ffd03689b84&wa=wsignin1.0&wtrealm=urn%3afederation%3aMicrosoftOnline&wctx=LoginOptions%3D3%26estsredirect%3d2%26estsrequest%3drQIIAdNiNtQztFKxMEkxsDBKStS1SEpK0TWxABKWxqaJuiYGpiZp5kmWScnJaUVCXAIfj2d03VO87z15Vvxf5ozZLTsYGS8wMr5gZLzFxO_vWFqSYQQi8osyq1JnMUsXlySWpBoYG5sYm5gamxgaGpqaGBubmhhYGllsYmZLzs_Nzc87xayUUVJSUGylr59elFiQoZebmVyUX5yfVqIHVKCQX5Cal5lyg5nxEbN4XnpRZjrQ7NQyh7zU8rT8otxEkJoLLIyvWHgMWK04OLgEeCTYFBh-sDAuYgW6tojT9IKl9EH_9WL6ynyKPAynWPUj831D_CPCC6Mys_1dQwICPT29nbNC9LOTM51ccqL00_wjM93TSpw9jYtCbS2sDCewMX5gY9jFqQJyI9CJOfnJiTkZ-cUl-qkF-RWV-kBeTlJicrZeRkluzi0uESMDQwtdAyNdIwsFQxMrIxMrY8MoAA2&cbcxt=&username=username%40newforma.com&mkt=&lc=
URL did not match the registered callbackURL, so skipping
Received redirect on auth login window https://azadfs.newforma.com/adfs/ls/wia?client-request-id=8a68c7f1-21de-4bdf-939a-5ffd03689b84&wa=wsignin1.0&wtrealm=urn%3afederation%3aMicrosoftOnline&wctx=LoginOptions%3D3%26estsredirect%3d2%26estsrequest%3drQIIAdNiNtQztFKxMEkxsDBKStS1SEpK0TW........VqIHVKCQX5Cal5lyg5nxEbN4XnpRZjrQ7NQyh7zU8rT8otxEkJoLLIyvWHgMWK04OLgEeCTYFBh-sDAuYgW6tojT9IKl9EH_9WL6ynyKPAynWPUj831D_CPCC6Mys_1dQwICPT29nbNC9LOTM51ccqL00_wjM93TSpw9jYtCbS2sDCewMX5gY9jFqQJyI9CJOfnJiTkZ-cUl-qkF-RWV-kBeTlJicrZeRkluzi0uESMDQwtdAyNdIwsFQxMrIxMrY8MoAA2&cbcxt=&username=username%40newforma.com&mkt=&lc=
URL did not match the registered callbackURL, so skipping``

**Comment by ngrigoriev** [comment]
And this is the test with the browser using copy-pasted URL from Postman console output (https://login.windows.net/common/oauth2/authorize?response_type=code&state=state0334345341115433540928&client_id=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx&scope=https%3A%2F%2Fgraph.microsoft.com%20openid&redirect_uri=http%3A%2F%2Flocalhost%2Fepoxy%2Fcallback.html)


![ezgif com-video-to-gif](https://user-images.githubusercontent.com/2364632/36793969-f3334dd2-1c6c-11e8-9f09-b64ca864498a.gif)

**Comment by ngrigoriev** [comment]
I believe the problem is related to the authentication pop-up, which is quite typical for AD FS.

**Comment by harryi3t** [comment]
@ngrigoriev Sorry, I did not see the last part which says

> I use "work/school account" (not MS personal one) and our organization uses AD FS. Specifically, it prompts for the credentials again using with a pop-up.

Also, in the second gif, I don't see the pop-up. Is it because you were already logged-in?

I will check if I can create a work account to test this flow.

**Comment by ngrigoriev** [comment]
@harryi3t 

There is pop-up there displayed after ~30s. This is Firefox private window, not cookies etc, like Chrome's Incognito mode. Probably you saw my comment with the previous GIF. I posted it and then realized that the GIF tool I used limited the duration of the GIF to 15s, so I had to convert again and update the comment.

**Comment by harryi3t** [comment]
@ngrigoriev Yeah the GIF was cached.

Now that I have seen the complete gif, the root cause is the presence of another auth (Basic/Digest/NTLM) in the Oauth2 flow.

The popup that you see is actually a prompt rendered by browser when it sees a particular header in the response header (`www-authenticate →xxxx xxxxx`)

Since there was no HTML and just a response header, you see a blank screen.

This can be easily reproduced. Just put `http://httpbin.org/basic-auth/user/passwd` in the auth URL and click on `Request Token`. This will open a white screen
Opening the same URL in the browser will prompt for username & password.

Right now I am not sure if this is a limitation in electron browser window itself.
Once I confirm where the bug/limitation is, will update the thread.

Thank you for your patience and valuable input :)

**Comment by harryi3t** [comment]
Relevant issue on electron https://github.com/electron/electron/issues/1362 
They added support for only basic auth, digest & NTLM (your case) is still not supported :( 

I have added a comment on that issue, once they add support for it or if they post a workaround we will look into this issue.
