### ISSUE TITLE
Multipart only sends file once

### ISSUE THREAD

**Issue by ztrange** [a85/POSTMan-Chrome-Extension#4247]
I updated to 5.5.3 but started having an issue with multipart. 

I have an endpoint that looks like this:
```
POST /images/ HTTP/1.1
Host: localhost:3000
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1YThhMTYzMWM2N2I5YjMwNmRhOWI3YjQiLCJ1c2VyVHlwZSI6IkVkaXRvciIsImlhdCI6MTUxOTY5MTk5OCwiZXhwIjoxNTE5Njk0OTk4LCJpc3MiOiJteC5lbGVjdG9yYWxpYSJ9.JewFQSF-trWs1UJCZAMiEfcF_VlKi6xDGr-fJdOpsB8
Cache-Control: no-cache
Postman-Token: c36c0368-552e-4a90-84bc-1edce0f894ae

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename=""
Content-Type: 


------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="body"

{"pic": {"focus": {"width": 100,"height": 100,"left": 0,"top": 0}},"slug": "harry-potter","name": "Harry Potter","bio": "The boy who lived"}
------WebKitFormBoundary7MA4YWxkTrZu0gW--
```

With the latest version, I was able to select the file to be uploaded and then run the request ONCE. If I tried it again, it never sent the file again. Even if I disabled the param in body or re-selected the file, it was never sent again. I'm now back to 5.5.2. Thought you'd like to know.

I can no longer see the about info for 5.5.3 but here is for 5.5.2

Postman for Linux
Version 5.5.2
linux 4.13.0-36-generic / x64

**Comment by SamvelRaja** [comment]
@ztrange 

Can you update to our latest canary version https://www.getpostman.com/canary and confirm that the issue still exists.

**Comment by jimji1005** [comment]
problem doesn't exist in canary build

**Comment by ztrange** [comment]
That's right. Problem doesn't exist in canary

**Comment by SamvelRaja** [comment]
@ztrange  @jimji1005  Thanks for confirming the fix. We will be rolling out the fix in our stable version soon.
Also, I would recommend staying in the canary channel to get immediate updates on upcoming features 😄
