### ISSUE TITLE
Unable to Join a Team Workspace

### ISSUE THREAD

**Issue by tredmon** [a85/POSTMan-Chrome-Extension#4250]
## App Details:
```
Postman for Mac
Version 6.0.7 (6.0.7)
Mac OSX High Sierra 10.13.3 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:
Updated to v6 of Postman today, and haven't been able to join a Team Workspace.
 2. Expected behaviour:
Clicking "Join" on a Team Workspace should resolve with either a successful join or give an indication about why joining is not available.
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
```
Sync Request: /v2/workspace/join/20d8ea55-86f6-4f0d-8906-8652924b38a2
shared.js:113315 Sync Request: Object {method: "put", url: "/v2/workspace/join/20d8ea55-86f6-4f0d-8906-8652924b38a2", headers: Object, data: Object}
shared.js:113316 Sync Response: Object {model_id: "20d8ea55-86f6-4f0d-8906-8652924b38a2", meta: Object, data: Object, revision: 3295516853, jwr: Object}
shared.js:113665 Sync Incoming: workspace:update
shared.js:113669 Object {model_id: "20d8ea55-86f6-4f0d-8906-8652924b38a2", meta: Object, data: Object, revision: 3295516853, type: "workspace"…}
shared.js:332222 no changesets to add to sync client
shared.js:330273 sync client process worker started [Object]
shared.js:331140 syncClient.getAllChangesets [] null
shared.js:113311 Sync Request: /v2/workspace/20d8ea55-86f6-4f0d-8906-8652924b38a2?populate=dependencies.collections&populate=dependencies.environments&populate=members
shared.js:113315 Sync Request: Object {method: "get", url: "/v2/workspace/20d8ea55-86f6-4f0d-8906-8652924b38a2…pulate=dependencies.environments&populate=members", headers: Object, data: Object}
shared.js:113316 Sync Response: Object {model_id: "20d8ea55-86f6-4f0d-8906-8652924b38a2", meta: Object, data: Object, jwr: Object}
```
 4. Screenshots (if applicable)
<img width="881" alt="screen shot 2018-02-27 at 11 02 54 am" src="https://user-images.githubusercontent.com/10743942/36746019-79ab1350-1bae-11e8-92c4-acabbe194e67.png">

**Comment by prashantagarwal** [comment]
@tredmon Did it got stuck in joining ?

**Comment by tredmon** [comment]
Correct. Sometimes after switching workspaces and trying again it says `Joining` for a short time before reverting back to `Join`, and a subsequent attempt will hang on `Joining`.

**Comment by tredmon** [comment]
Just updated postman to new version `6.0.9` and joining worked flawlessly. Thanks for the efforts in this regard.
