### ISSUE TITLE
Requests lost on a collection

### ISSUE THREAD

**Issue by eloyucu** [a85/POSTMan-Chrome-Extension#4252]
Hi everyone.

I am the owner of a collection shared with my team, yesterday I could see all the folders and request. Today, alll the folders have disappeared, I only can see the only one request that wasn`t inside any folder.
I was talking with a member of the team and he can see everything in the collection.

What should I do to recover my request??

**Comment by sdnts** [comment]
Hi @eloyucu, if it is the same collection your colleague sees the requests in, can you head over to your [web dashboard](https://app.getpostman.com), find the collection and check if the collection is intact there? If it is, a sign out + sign in from the app should fix your issue.

If it isn't, can you drop an email to help@getpostman.com?

**Comment by eloyucu** [comment]
Hi @madebysid 

Yes, the collection is intact. And thanks it has worked.

Thank you very much.
