### ISSUE TITLE
Code snippet generator doesn't substitute local variables

### ISSUE THREAD

**Issue by aaronadamsCA** [a85/POSTMan-Chrome-Extension#4255]
## App Details:
Postman for Windows
Version 6.0.7
win32 10.0.16299 / x64

## Issue Report:
Similar to #4176, the code snippet generator does not perform variable substitution on local variables -
 specifically, variables set in pre-request scripts using `pm.variables.set()`.

If my request body looks like this:

```
{
  "timestamp": "{{myTimestamp}}"
}
```

And my pre-request script (mine is on the collection folder) looks like this:

```
pm.variables.set("myTimestamp", moment().format());
```

The code snippet generator, in cURL format, looks like this:

```
curl -X POST \
  'https://api.com' \
  -d '{
  "timestamp": "{{myTimestamp}}"
}'
```

I would expect `{{myTimestamp}}` to be replaced with the timestamp.

I'm unsure of the full impact of running pre-request scripts to populate local variables just to generate code snippets. But without doing so, you can't effectively use the code snippet generator if you use local variables at all. You end up having to perform manual variable substitution, which is painful.

The workaround is to revert to using (abusing?) environment variables to store values set by pre-request scripts. But given that the local scope presumably exists for good reason, it seems it should be supported by the code snippet generator.

**Comment by harryi3t** [comment]
@aaronadamsTO pre-request script (and test script) only runs when a request is actually sent.
Code snippet generator is just converting the current request to a language-specific snippet. It does not run the scripts before the conversion process.

Even if we do run the script behind the scene, update any variables and then generate the snippet, it will be not same as running that script before sending the request.

**Comment by aaronadamsCA** [comment]
I figured you'd say this, and I do understand it's probably working as intended so far. I just think you'll want to think harder about intent, specifically about how local variables impact common workflows. If using local variables means you can't quickly copy a working cURL request, then they might not be a well-conceived feature.

For now I'll just stop using local variables and revert to using environment variables. It sucks to use/abuse them this way, but local variables just don't seem to be a useful feature yet.

**Comment by arikw** [comment]
I agree with @aaronadamsTO - there should be a quick way to hydrate the variables

**Comment by ghost** [comment]
I just ran into this issue as well (Its why I joined).  I understand the issue, but its frustrating as we built a lot of our tests to user pre-request variables to make quick changes to large requests.  Not having the ability to move those variables into a curl statement is going to be painful

But, if we figured out that if we  make the variables globals (with very specific names to avoid crossover) then it works
