### ISSUE TITLE
Feature Request - Bulk Request Creation

### ISSUE THREAD

**Issue by dmscheck** [a85/POSTMan-Chrome-Extension#4256]
## App Details:
```
Postman for Windows
Version 6.0.7
win32 6.1.7601 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:
Always been there
 2. Expected behaviour:
In the use case where you're starting a collection from scratch, it would be really useful to have a way to add many requests at the same time.  At the minimum, I want to be able to provide a list of request names and have the generic blank requests created.  Being able to select the HTTP method for each would be a plus, but wouldn't be completely necessary.  This would really help in setting up requests for a new API.

 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
N/A

 4. Screenshots (if applicable)
N/A

**Comment by thecuriousdev** [comment]
@dmscheck thanks for suggesting this. I'll mark this as a feature request.

**Comment by sankalp0o** [comment]
Thanks for the suggestion @dmscheck. We are looking into adding quicker options for creating new requests inside a collection. Meanwhile you can use the "New" button in the app header to create a API Documentation. This would let you create a new collection with a list of requests with methods, url etc.
