### ISSUE TITLE
Feature Request - Edit Name When Duplicating

### ISSUE THREAD

**Issue by dmscheck** [a85/POSTMan-Chrome-Extension#4257]
## App Details:
```
Postman for Windows
Version 6.0.7
win32 6.1.7601 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:
Always been there
 2. Expected behaviour:
When you duplicate a request, it currently just appends "COPY" to the existing request name.  It would save a step if the user could edit the name at the time of duplication to save the steps of selecting the request and editing there.

 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
N/A

 4. Screenshots (if applicable)
N/A

**Comment by thecuriousdev** [comment]
@dmscheck thanks for suggesting this, I'm marking this as an enhancement, We'll look into this in the future.

**Comment by a85** [comment]
We recommend using inline editing to change the name. Adding a prompt everytime prevents from faster duplication.
