### ISSUE TITLE
Unable to export Globals

### ISSUE THREAD

**Issue by patrickgardella** [a85/POSTMan-Chrome-Extension#4258]
## App Details:

```
Postman for Windows
Version 6.0.7
Windows 7 x64
```

I updated to Postman v6.0.7 today, and I am now unable to export Globals as JSON. The "Download as JSON" button doesn't do anything. 

I've saved them previously, so I'm not sure if I'm doing something wrong (it's clicking a button right?), or if the app has problems.

I've opened an internal ticket with Postman, but am posting it here as well to document the issue publicly. 

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:
 2. Expected behaviour:
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 4. Screenshots (if applicable)

**Comment by kamalaknn** [comment]
Hi @patrickgardella 

Thanks for reporting the issue. We'll roll out a fix for this soon.

We will also push the fix to the canary channel before it is rolled out to the stable channel. We'll keep this thread updated.

Thanks.

**Comment by prashantagarwal** [comment]
Hi @patrickgardella . This seems to be fixed in our latest Postman app. Can you please update your app. Thanks

**Comment by patrickgardella** [comment]
Correct. It does. Thank you, @prashantagarwal

**Comment by musamamasood** [comment]
Thanks, It's working after upgrade.
