### ISSUE TITLE
Server multi-part response with zip file has issue

### ISSUE THREAD

**Issue by kamalakannanr** [a85/POSTMan-Chrome-Extension#4265]
## App Details:

```
Postman for Chrome
Version 5.5.2
win / x86-64
Chrome 63.0.3239.132
```

## Issue Report:
I am posting REST request, and expect a multipart response from the server. One part is the json body and the other a zipfile. I expect to download this zip file. So I used "Send and Download" option and I get the save dialog and able to save the file. I have the following headers in response
_content-disposition →attachment; filename="Config.zip"
content-type →multipart/mixed;boundary=Boundary_30_118693949_1520000515308_

There are 2 issues here
1. Postman does not recognize the file as zip file, and saves it as "response" (without any file extension, so unknown file type). But as you can see above in the header the server provides the file name.
2. The other part (json body) is not displayed in the response body area of postman. When I use the "Send" option though, I get both the body parts. Pasting the response

_--Boundary_31_142886285_1520000774318
Content-Type: application/json

{"config":[{"entityName":"com.example.po","instances":["uuid1","uuid2"]},{"entityName":"com.example.rmca","instances":null},{"entityName":"com.partyMgmt.customercharspec","instances":null}]}
--Boundary_31_142886285_1520000774318
Content-Type: application/octet-stream_
{ And the binary octet stream}

Is there a way to get both the parts when I use "Send and Download" option?

**Comment by sivcan** [comment]
Hi @kamalakannanr - The Chrome application has been deprecated.
Kindly download the [latest Postman native application](https://www.getpostman.com/apps) and test out this issue.
If it persists in the native app also, let us know and we'll reopen it and look into it further.

Closing this.
