### ISSUE TITLE
Postman runner issue

### ISSUE THREAD

**Issue by chandanacheerla** [a85/POSTMan-Chrome-Extension#4266]
postman for windows 
Version 6.0.8
OS x64
```

## Issue Report:
 when i try to use runner to run my collection of API'S, i couldnt see differentiation between failure and passed one..everything showing green in color and also results 0 passed 0 failed.

Kindly assist on the same

**Comment by sivcan** [comment]
@chandanacheerla - This is to inform you that the passed and failed count are for the test cases that are there inside each of the requests. 
If you're facing any other issue then let me know.
