### ISSUE TITLE
postman-could not get any response

### ISSUE THREAD

**Issue by zhanpengli** [a85/POSTMan-Chrome-Extension#4269]
when i post data to my server but doesn't work, can u help me,thanks
![image](https://user-images.githubusercontent.com/32571006/36929989-a35e548c-1ed3-11e8-925e-dc7564c47d5c.png)

**Comment by zhanpengli** [comment]
But another server's program can send a request.

**Comment by preethammavin** [comment]
Hey, can you give us an idea about the request you are trying to send. If it contains sensitive information please do mask it.

**Comment by SamvelRaja** [comment]
@zhanpengli  I would recommend you to open Postman Console(View -> Postman Console) which gives you more insight into the request sent from Postman.

**Comment by numaanashraf** [comment]
@zhanpengli Closing due to insufficient information. Please provide logs from Postman Console (View -> Postman Console) if you are still facing this issue.
