### ISSUE TITLE
Respond to a bug. Version number: 6.0.8 Platform: Win 64

### ISSUE THREAD

**Issue by YuJinLei** [a85/POSTMan-Chrome-Extension#4271]
When creating a request, the body-> Form-data key type is file and the value is one. The request was sent again after a successful delivery, and the file could not be successfully sent to the server, that is, the request parameter was empty, but the value on the interface showed that the file was selected.

**Comment by harryi3t** [comment]
@YuJinLei Thanks for reporting this bug. We are looking into this.
WIll update the thread once I confirm this bug.

**Comment by harryi3t** [comment]
@YuJinLei This is fixed in the latest version of Postman.
