### ISSUE TITLE
Missing sorting control for collections in the Postman 6.0.7-9 Win

### ISSUE THREAD

**Issue by serg1409** [a85/POSTMan-Chrome-Extension#4272]
## App Details: 
Postman for Win
Version 6.0.9
OS Win 7 x64

## Issue Report:
 1. It was a useful sorting control for sidebar collections (by name or by date) in the Postman 5 (Build mode).
2. It's missing in 6.0.7-9

![postman5-collections-sort](https://user-images.githubusercontent.com/34937953/37084381-07579794-21fb-11e8-85b9-281dcac9f69a.PNG)

**Comment by SamvelRaja** [comment]
@serg1409 Thanks for raising your concern to us. We will update this thread once it is done from our end.

**Comment by SamvelRaja** [comment]
Tracking it in https://github.com/postmanlabs/postman-app-support/issues/4253

**Comment by ghost** [comment]
A year later in 7.0.4 and still not fixed.

**Comment by nilselde** [comment]
It would be nice to be able to sort by multiple criteria, like Name and then Type, or Type then Name:

```
GET req1
PUT req1
GET req2
PUT req2
```
or
```
GET req1
GET req2
PUT req1
PUT req2
```

**Comment by ghost** [comment]
I would be happy with the rumored button returned that sorts collections by name

**Comment by Petercopter** [comment]
This feature is still missing, even though it appears to be in the documentation?
https://learning.getpostman.com/docs/postman/collections/managing_collections/#reorder-collections

![](https://s3.amazonaws.com/postman-static-getpostman-com/postman-docs/WS-reorder-collections-sidebar.png)

**Comment by ghost** [comment]
Sad that this has been open since March 3, 2018 and no one has added the icon back in.

**Comment by sebAtos** [comment]
This feature is really important for us. Do you know why it's still missing in 7.2.2 ?

**Comment by ghost** [comment]
As well as sorting collections, would be nice to also control the sort of requests INSIDE each collection

**Comment by vladox** [comment]
Version 7.8.0, still missing:

![image](https://user-images.githubusercontent.com/2648461/66643685-8883ef80-ec1f-11e9-9736-67d5a8647bb4.png)

**Comment by Roscoe93** [comment]
Version 7.14.0,still missing

**Comment by baaa** [comment]
why is this closed?

**Comment by serg1409** [comment]
See the discussion continuation at [https://github.com/postmanlabs/postman-app-support/issues/4253](url)

**Comment by HenrikHolmIT** [comment]
v7.22.1 and still no sorting of Collections.

This really seems like a low hanging fruit!

**Comment by JasinYip** [comment]
![image](https://user-images.githubusercontent.com/7105264/80565229-90bc4480-8a22-11ea-9ecb-934ecb20f7a7.png)

v7.23.0 Still no sorting of collections...

**Comment by ghost** [comment]
Hello, I would also like this very basic feature.

**Comment by petr-hybler** [comment]
same here 8.9.0 ... still missing :( what a shame

**Comment by HenrikHolmIT** [comment]
I not even using v8 anymore. Downgraded to v7.
v8 is not a good version. Hope they fix all usability problems by v9.

Oh this feature isn't in v7 but I'm tons more productive with v7 than with v8.

**Comment by petr-hybler** [comment]
> I not even using v8 anymore. Downgraded to v7.
> v8 is not a good version. Hope they fix all usability problems by v9.
> 
> Oh this feature isn't in v7 but I'm tons more productive with v7 than with v8.

what bothers u in v8?

**Comment by HenrikHolmIT** [comment]
> > I not even using v8 anymore. Downgraded to v7.
> > v8 is not a good version. Hope they fix all usability problems by v9.
> > Oh this feature isn't in v7 but I'm tons more productive with v7 than with v8.
> 
> what bothers u in v8?

Many things. One is the fact that response examples have been added as child nodes to requests and clicking a request expands the request node. You can collapse it again but every click will expand it.
The UI for running tests totally changed. There is zero overview with the new UI.
The list is very long and I'd happily go to v8 and compile a list but I fear nothing will happen. The Expand/Collapse seems like such a minor fix to make (Do not expand on request click. Only expand when clicking on the > icon) but it didn't get fix for like 3 updates when I was using v8.

So to meet my deadlines and not be bogged down I downgraded to v7.

Oh by the way can you remove the Please update to v8 UI dialog that pops up every time v7 is opened? That's really annoying too. Dont need to see it that often. Only show it like once a week or only once per v8 updates.

Edit: I see you have no reference with Postman dev team. Read the 'you' part as 'Postman dev team'
