### ISSUE TITLE
I'm very expected add a operation of drag and drop collection

### ISSUE THREAD

**Issue by DullCat-c** [a85/POSTMan-Chrome-Extension#4275]
Postman support a operation of drag and drop collection is only in the same level at present,but in most cases , i need drag between different levels . So , i hope Postman can add this operation.

**Comment by harryi3t** [comment]
@DullCat-c Did you mean dragging folder or request?

**Comment by DullCat-c** [comment]
folder,i want to move the first level folder to another  first level folder , but i discover that can not.

**Comment by harryi3t** [comment]
@DullCat-c That is already supported. Which version are you using?
![mar-05-2018 14-20-31](https://user-images.githubusercontent.com/5207331/36965763-94c43672-2080-11e8-9ac3-a1470873f6ce.gif)

**Comment by DullCat-c** [comment]
@harryi3t 
no, that is move  of the second level,but i want to move the first level 
i think this is the first level  : 
![image](https://user-images.githubusercontent.com/29897806/37012017-8645ff38-212d-11e8-81bf-142b84e33428.png)

**Comment by harryi3t** [comment]
@DullCat-c That is not a folder but a collection and collection can't be moved in another collection. For that use folders.

Please see https://www.getpostman.com/docs/v6/postman/collections/creating_collections to know more about what collections/folders/requests are and how to use them.
