### ISSUE TITLE
Not working : Import result json generated after newman execution from command line back to postman collection runner

### ISSUE THREAD

**Issue by munnamathew** [a85/POSTMan-Chrome-Extension#4276]
While trying to import a result json after execution from command line using newman, the post collection runner is always is returning the error - "The run you are trying to import already exists".

Result analysis of tests is pretty difficult, since the results cannot be imported back to collection runner.

## App Details:

Postman Windows App
OS - Windows 10

## Issue Report:
Steps to reproduce the problem.

1. Run any test from commandline using newman, generating a report in json format,
2. Import the result json back to postman collection runner using import test run feature.

Screen shot for the same is attached below: 

![importresultjson](https://user-images.githubusercontent.com/25816031/36965603-2871126a-2080-11e8-92a5-e83d0ca744c1.png)

**Comment by munnamathew** [comment]
![importresultjson](https://user-images.githubusercontent.com/25816031/36965544-f62b2c00-207f-11e8-9aa9-93cdd32f7b65.png)

**Comment by sivcan** [comment]
Hi @munnamathew - I'll try to reproduce this issue and will notify you once confirmed.
Thank you for reporting this.

**Comment by munnamathew** [comment]
Hi @sivcan  - Thanks for looking to the issue. Do you have any update on this query?

**Comment by sivcan** [comment]
@munnamathew - The report generated by newman cannot be imported inside the collection runner.
Anyway, the error that you've reported is weird.
Are you on the latest version of the app ?
If not can you update to the latest version and try again ?

Were you ever able to import this before in the collection runner ?

You can download the latest version here - [Download Postman](https://www.getpostman.com/apps)

**Comment by sivcan** [comment]
@munnamathew - I was able to produce that error now.
We'll fix that error message.

**Comment by harryi3t** [comment]
@kunagpal Is there a way we can import the result of running a collection from Newman into Postman?

**Comment by munnamathew** [comment]
Hi all,

Is there any chance you could add this as a new feature if not already available?
Result analysis of test execution through newman is pretty difficult, since the results cannot be imported back to collection runner.

**Comment by sivcan** [comment]
Hi @munnamathew - I'll mark that as a feature request.

**Comment by munnamathew** [comment]
@sivcan  . Thanks a lot for accepting the feature request.

**Comment by vghung81** [comment]
Any others way that just generate the html report with failed test cases only?I have to run over 1000 test request and it's taking a lot of times to review each test failed

**Comment by dgmyers** [comment]
Has there been any update on this, either as a bug or feature request?

The Documentation page [command_line_integration_with_newman](https://learning.getpostman.com/docs/postman/collection_runs/command_line_integration_with_newman/) states that "The results of all tests and requests can be exported into a file and later imported into Postman for further analysis. Use the JSON reporter and a file name to save the runner output into a file."

Is this document incorrect?

**Comment by tarunKongsberg** [comment]
Is there any update on it because I am facing the same issue.

**Comment by tarunChaudharyQA** [comment]
Is there any update on this issue because I am facing the same problem?

**Comment by wmedali** [comment]
@dgmyers Yes the documentation is incorrect
the Bug is still open and the feature is broken apparently !

**Comment by tarunChaudharyQA** [comment]
@wmedali  Any timeline for the fix to be available?

**Comment by chuchuva** [comment]
Please make it easier to examine resulting JSON file. I look at this code and have no idea what it means:

```
          "stream": {
            "type": "Buffer",
            "data": [
              60,
              63,
              120,
              109,
              108,
              32,
              118,
              101,
              114,
              115,
```

**Comment by malvikach** [comment]
Reviving this old thread and taking this opportunity to inform you about new **Postman CLI**

Postman CLI is the new command line companion for Postman using which you can run your collections and your results will automatically be posted and made available on Postman. The UI will show your results in a format similar to how we show for the collection runner. 

Giving you a sneak peak into this for results of a Collection Run available in Postman::
<img width="1051" alt="Screenshot 2022-09-21 at 7 49 14 PM" src="https://user-images.githubusercontent.com/89449769/191534146-7afbe3ef-53f7-46b2-80ad-3888bc1fb37c.png">

We have also introduced a 'Runs' tab for collections that will contain all your Collection Runs and some useful statistics about them!!

<img width="1004" alt="runs" src="https://user-images.githubusercontent.com/89449769/191534511-41345cd1-dc22-446b-b905-fe06f2b8676b.png">

[This](https://blog.postman.com/introducing-the-postman-cli-to-automate-your-api-testing/) is our blog that talks about the other Collection Run features we are offering along with the new Postman CLI.
You can also set up some time with me to discuss further using [this](https://calendly.com/malvika-chaudhary/v10-feedback).





Learn more about using Postman CLI on our [Learning Center](https://learning.postman.com/docs/postman-cli/postman-cli-overview/).
