### ISSUE TITLE
Many shortcuts does not work

### ISSUE THREAD

**Issue by roukmoute** [a85/POSTMan-Chrome-Extension#4278]
## App Details:
```
Postman for Linux
Version 5.5.2
Linux Roukmoute 4.4.0-112-generic #135-Ubuntu SMP Fri Jan 19 11:48:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
i3wm
```

## Issue Report:
 1. This bug always been there
 2. Use shortcuts

Many shortcut are described here: http://blog.getpostman.com/2017/05/03/speeding-up-workflows-with-keyboard-shortcuts/
This is really cool!

But unfortunately on my desktop, `top-level navigation shortcuts` don't work.
It does… nothing.

Next for the most of the time, I use `Ctrl+l`, but on the `Preview` windows, it does not work.
There is another way to not work, it is when we are in `Pretty` windows, send request with `Ctrl+Enter`, after that, the focus has disappear, so `Ctrl+l` doesn't work anymore.

**Comment by vkaegis** [comment]
@roukmoute Could you verify if this issue still persists? Regarding the top level navigation shortcuts, we've been working on a simpler way of navigating the interface, so we've temporarily disabled these. The shortcuts shown in the Settings modal are the ones we support at the moment. We're also working on making shortcuts customizable.

Closing this for now, feel free to open another issue if you have more feedback.
