### ISSUE TITLE
Autofocus on the url input when open a new tab

### ISSUE THREAD

**Issue by NicolasGeraud** [a85/POSTMan-Chrome-Extension#4282]
## App Details:

```
Postman for Mac
Version 6.0.8 (6.0.8)
macOS 10.13.3
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:
Always been there
 2. Expected behaviour:
after hitting Cmd+T to open a new tab, I expect the focus be in the url input

**Comment by harryi3t** [comment]
@NicolasGeraud Thanks for opening this issue. This should be fixed in the next release.

**Comment by abhijitkane** [comment]
@harryi3t Can you update the status for the fix?

**Comment by numaanashraf** [comment]
This is now available in Postman v8.7.0 and above.
