### ISSUE TITLE
Different Error reaction In Postman when using conditions or try/catch

### ISSUE THREAD

**Issue by AlexanderTunick** [a85/POSTMan-Chrome-Extension#4283]
Mac 10.12.16
Postman for Chrome Version 5.5.2 OS X / x86-64 Chrome 64.0.3282.140

Hello.
Now successfully running my newman API test in TeamCity CI, but want to a bit upgrade it by adding console.log In Postman collection before uploading it to CI to start with newman. 
When errors occur I want to immediately see what the reason of the error in TeamCity build log.

What I do:
1. POST request (Create admin)
2. PATCH request (change first name)
3. DELETE admin request

And I added this one to check (DELETE request):
var jsonData = JSON.parse(responseBody);
```
 if(responseCode.code === 400 || responseCode.code === 500 || responseCode.code === 403)
 {
     console.log('====================');
     console.log(jsonData); 
   return;
}
```
And in Postman '**Test Results**' i see:

> There was an error in evaluating the test script: There was an error during JSON.parse()
> : Unexpected end of JSON input

Despite that fact that request passed successfully

But when i use try/catch construction, everything is ok:
```
var jsonData; 
try {
    jsonData = JSON.parse(responseBody);
} catch (err) {
    console.log(err);
}
```

What is going wrong? 

**In full body my whole test looks like:**

var jsonData = JSON.parse(responseBody);
```
if(responseCode.code === 400 || responseCode.code === 500 || responseCode.code === 403)
{
    console.log('====================');
    console.log(jsonData); 
    return;
}
tests["Status code is 204"] = responseCode.code === 204;
```

**Comment by harryi3t** [comment]
@Alextunchii 

> There was an error in evaluating the test script: There was an error during JSON.parse()
: Unexpected end of JSON input

This tells me that the response is not JSON. Is it not?

What is the output when you put a try catch
```js
var jsonData; 
try {
    jsonData = JSON.parse(responseBody);
} catch (err) {
    console.log(err); // This must be logging the error on console
}
```

**Comment by AlexanderTunick** [comment]
@harryi3t thanks for quick response.
Yeah, I guess you're right, because there just 204 No Content response, I missed this moment out

but with try/catch I have this:
```
{ type: 'Error', name: 'JSONError', message: 'No da
  │ ta, empty input at 1:1\n\n^' }
```

So I think it is right Postman reaction?

**Comment by harryi3t** [comment]
@Alextunchii 

> So I think it is right Postman reaction?
Yes

To fix this either use try/catch if you are not sure of the response type or remove parsing the response for this request where you know there won't be a response body
