### ISSUE TITLE
File upload form field does not detect chosen file if you reselect the same file

### ISSUE THREAD

**Issue by funkydunc** [a85/POSTMan-Chrome-Extension#4284]
## App Details:

```
Postman for Windows
Version 6.0.7
win32 6.1.7601 / x64
```

## Issue Report:
 1. I just noticed this issue:
 2. Expected behaviour: if the file field shows that I still have a file selected, then it should post the file.
 3. Console logs - none sorry
 4. Screenshots - see below

1. Make a request with a 'file' field. It succeeds.
https://gyazo.com/93f774779cc59bf21a556852944e409c

2. It is showing that the file is still selected. Repeat the request. It fails.
https://gyazo.com/9817273dd8832d41fc685373d148f31b

3. Click the 'choose file' button to reselect the file and send the request. It fails.
https://gyazo.com/556b73e9c50de23f11952f79affebbd8
https://gyazo.com/24bc9b804196605403509d7ac564dd13

4. By moving the position of the 'file field' it shown that no file is selected. Now reselect it and send the request. It succeeds.
https://gyazo.com/5e271c9477f28309e8456b8abf1971bf
https://gyazo.com/f1640748fcf77d6439e5b03eb00b3bd8

So every time you post, you must reselect the file. However this does not work unless you move the position of the file field causing it to be 'reset'. It can then be successfully re-selected.

For the 'failed' requests (403) above. Here is the data from our server log, showing that no file was posted.
2018-03-06 11:53:32,165 | WARNING | core_instances.views | /licence/ |  | No uploaded files found. Check that you posted with enctype="multipart/form-data"
2018-03-06 11:53:32,165 | WARNING | core_instances.views | /licence/ |  | Invalid Licence File. Reading data from licence file failed.
2018-03-06 11:53:32,165 | WARNING | core_instances.views | /licence/ |  | 'NoneType' object has no attribute 'read'

Thank you

**Comment by ChadTaljaardt** [comment]
I'm also receiving this issue.

Solved by the same method as suggested by op.

**Comment by harryi3t** [comment]
@funkydunc @ChadTaljaardt This was fixed in 6.0.8
Can you update to the latest version and try this out?

**Comment by ChadTaljaardt** [comment]
I will give it a shot :+1:

**Comment by ChadTaljaardt** [comment]
This has been fixed.

@funkydunc please close.

**Comment by harryi3t** [comment]
@ChadTaljaardt Thanks for confirming.
@funkydunc I am closing this. Feel free to re-open if it didn't work out for you.
