### ISSUE TITLE
How to replace complete JSON body - with env variable or otherwise?

### ISSUE THREAD

**Issue by aprixon01112017** [a85/POSTMan-Chrome-Extension#4285]
I know that substitution works for a body

{
"key" : "{{value}}"
}

But I want to replace the complete body

{{value}}

Is that possible? If so how?

**Comment by GrzegorzPi** [comment]
If I understand you correct:

Yes, you can put whole body from variable, just simply place:

{{body}}
variable in body.

Of courese first, you have to build your json object and place it in env variable {{body}} as a string. You can do it in Pre-request script page.

Or place whole body to env variable {{body}}, like this: 
{"key" : "myValue"}

**Comment by aprixon01112017** [comment]
Thanks!

**Comment by harryi3t** [comment]
@aprixon01112017 Closing this since the question was answered. Thanks @GrzegorzPi
