### ISSUE TITLE
First use of ".not." in assertion change behaviour of all following assertions to negative

### ISSUE THREAD

**Issue by GrzegorzPi** [a85/POSTMan-Chrome-Extension#4286]
## App Details:
Postman for Windows
Version 6.0.8
win32 10.0.16299 / x64

## Issue Report:
1. send (with status 200) request with json body response, for instance:
```
{
    "item_list",
    "pagination": {
        "pages": 1
    }
}
```

2. in test page put code contain assertion: "pm.response.to.not.be.error;" for instance:
```
 pm.test('has pagination', function () {
    pm.response.to.have.jsonBody('pagination');
    pm.response.to.have.jsonBody('pagination.pages');
});

pm.test('wired behaviour: to.not.be.error', function () {
    pm.response.to.have.jsonBody('pagination.pages');
    pm.response.to.not.be.error;
    pm.response.to.have.jsonBody('pagination');
});

pm.test('has pagination after to.not.be.error', function () {
    pm.response.to.have.jsonBody('pagination');
});
```

3. result is corrupted, assertion after to.not.be.error start to fail with reason: 
`response to not contain`
but we never use assertion to.not.have.jsonBody

## Screen:
![postman](https://user-images.githubusercontent.com/35603973/37036575-5ca68260-2150-11e8-8575-5aa1f7e94692.png)

**Comment by harryi3t** [comment]
Closing this in favor of https://github.com/postmanlabs/postman-app-support/issues/3690
Please subscribe to the original issue for updates
