### ISSUE TITLE
Iteration Data not used again when clicking Retry in Collection Runner

### ISSUE THREAD

**Issue by MLG-ANolan** [a85/POSTMan-Chrome-Extension#4287]
## App Details:
```
Postman for Mac
Version 6.0.9
OS X 16.7.0 / x64
```
## Issue Report:
 1. Did you encounter this recently, or has this bug always been there: **Recent**
 2. Expected behaviour: Same Iteration data is usable again when clicking Retry.

## Reproduce
1. Open collection runner
2. Select a data file (mine was json to set up POST data).
3. `Console.log(pm.iterationData.toObject());` in pre-request script.
4. Run the collection
5. Click the Retry button
6. See that iteration data is empty

**Comment by harryi3t** [comment]
@MLG-ANolan Thanks for reporting this issue. 
We are working on this and will keep you posted on the status.

**Comment by sivcan** [comment]
We'll be tracking all the issues related to data file path in here: https://github.com/postmanlabs/postman-app-support/issues/4320

**Comment by rosemary16** [comment]
Just wanted to report the same problem.

**Comment by m3dbedb** [comment]
I would like to clarify the issue. I have 'data' folder with two data files called 

    fizusers.json
    uzers.json

1. I execute collection in runner with users.json data file applied
2. I press 'retry' in runner and it retries collection execution with first (by name) file (fizusers.json) from folder with data files.
Issue confirmed with postman 7.9.0 for windows 7 64 bits

**Comment by liamthing** [comment]
Any update on this? I'm still getting this issue.

**Comment by mig-1** [comment]
Same for me but I'm using CSV file. 
If click "retry" button, data get from Enviripment variables - not from a file, like it was at first try.

**Comment by nickm8** [comment]
Using version 7.16.0 this has been fixed in the runner.
It now uses the same datafile when using the retry button.

The only issue I see is that it shows the Environment Name as "No Environment" after a retry.
This doesn't actually impact the environment variables used for the run.

It might be better to track that in a different ticket as this is now resolved.

**Comment by saswatds** [comment]
@nickm8 thanks for the verification update. I am closing this issue as the retry is fixed.
