### ISSUE TITLE
Add or modify retry button to rerun only failing tests

### ISSUE THREAD

**Issue by dbkaynor** [a85/POSTMan-Chrome-Extension#4288]
Add or modify retry button to rerun only failing tests

I have a collection that has about 200 individual tests and when only one or two fail it would be handy to be able to just rerun the failing one(s).

**Comment by harryi3t** [comment]
@dbkaynor  Thanks for reaching out to us. I have marked this as a feature request. Will keep you posted on the status.

**Comment by alyvicto** [comment]
Is there any way to reopen this or has it been resolved already?

**Comment by malvikach** [comment]
@alyvicto This issue is open. Please feel free to add your thoughts. We are tracking this as a feature request.

**Comment by malvikach** [comment]
We are tracking this [here](https://github.com/postmanlabs/postman-app-support/issues/9735)
