### ISSUE TITLE
When we generate report by newman and pass data via csv , report repeats first value for variable via csv(HTML report)

### ISSUE THREAD

**Issue by shanzee** [a85/POSTMan-Chrome-Extension#4289]
Postman for Windows
Version 6.0.8
win32 10.0.10586 / x64
![newman-cli](https://user-images.githubusercontent.com/17459346/37058161-a134a77c-21af-11e8-8722-27b1a3900d85.png)
![html-rep](https://user-images.githubusercontent.com/17459346/37058162-a162fd3e-21af-11e8-9f39-877f3a013e88.png)

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:
 2. Expected behaviour:
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 4. Screenshots (if applicable)

**Comment by harryi3t** [comment]
@shamasis Can you open this issue here http://github.com/postmanlabs/newman?
Also please provide more information about what is the expected behaviour and what issue are you facing.
