### ISSUE TITLE
Postman 6.0.9 not starting (takes at least minutes) on Windows 10 after update from 5

### ISSUE THREAD

**Issue by aprixon01112017** [a85/POSTMan-Chrome-Extension#4292]
The splash window "Configuring your workspaces" is displayed and nothing more happens for at least 5 minutes.

**Comment by SamvelRaja** [comment]
Can you share us logs from view -> developer -> show dev tools (shared) to help[at]getpostman[dot]com

**Comment by aprixon01112017** [comment]
the 6.0.9 canary2 starts successfully.

**Comment by aprixon01112017** [comment]
Ho do I access them in the file system? The app does not start so I cannot access them via the GUI

**Comment by SamvelRaja** [comment]
The menus will be accessible on the top, Just focus on the app.
you need to select the view menu from it.
Kindly let me know if that is not available.

If possible, can you provide me a screencast?

**Comment by aprixon01112017** [comment]
![postman](https://user-images.githubusercontent.com/33280703/37085804-48c222c6-21f6-11e8-83d3-e45699fb95ff.png)

**Comment by aprixon01112017** [comment]
The main window is not opening and therefore no menu is available

**Comment by SamvelRaja** [comment]
@aprixon01112017  This seems really odd. 
Can you try opening the app from cmd and send the logs from there?
```
a. Quit the app completely.
b. Go to cmd 
c. C:\Users[USER]\AppData\Local\Postman\app-6.0.9\Postman.exe
```

**Comment by aprixon01112017** [comment]
same

**Comment by SamvelRaja** [comment]
@aprixon01112017  Do you see any logs in cmd? I want the logs from there.

**Comment by aprixon01112017** [comment]
"ORM initialization successful"

**Comment by SamvelRaja** [comment]
@aprixon01112017  
Thanks for the information. 
Can you check your task manager for the number of postman process running?

We are actively looking into the problem you are facing.

Until that, to unblock you quickly.
If you are already signed in user
1. Can you go to getpostman.com and if you find all the data are synced. It is safe to remove the app data and re-install it.
  i. You need to delete the data from, `C:\[USER]\AppData\Roaming\Postman`
  ii. Go to control panel and uninstall the application and re-install the same by downloading the latest from https://getpostman.com/apps
2. If you are not a signed in user, you can go back to the previous version without deleting the data.
you can download the 5.5.3 version from 
https://dl.pstmn.io/download/version/5.5.3/windows_32
https://dl.pstmn.io/download/version/5.5.3/windows_64

**Comment by aprixon01112017** [comment]
When started from console:
4 processes.

**Comment by aprixon01112017** [comment]
Deleting the  AppData/Roaming/Postman folder did it. Thanks

**Comment by SamvelRaja** [comment]
Closing this for now.
And people who reach here, additional note **deleting** *AppData/Roaming/Postman* will **delete all your postman data completely.** 
So using that is not the recommendable way, we will try to get the app working without going through this flow.

**Comment by antoniovassell** [comment]
Where is Postman data on ubuntu?

**Comment by mderis** [comment]
**SOLVED:** I just removed app from `AppData/Roaming/Postman` and reinstalled the last version and I still had the problem. But my problem solved by installing an old version (5.3.2) and updating it from inside the application.

**Comment by mfarhat437** [comment]
hey...where can i find this directory  AppData/Roaming/Postman ??

**Comment by mderis** [comment]
> hey...where can i find this directory AppData/Roaming/Postman ??

What is your OS?

**Comment by rmorrise** [comment]
I encountered this freeze issue today after being prompted to sign in again. The first time the prompt came up, I cancelled/ignored the sign-in. When I tried to start Postman again, it hung like this until I used End Task on all running Postman instances. HTH you find the problem.

**Comment by preethammavin** [comment]
@rmorrise we have made large amount of performance fixes since after the issue was reported. Can you confirm the version on which you working on.

Also please note:
**Note:**: Please re-authenticate your account when the sign-in prompt appears, as this ensures two things 
1) Your data is always synced and backed up for you to retrieve at any point in time across any device
2) Also ensures that you are the one who can access your data and keep your account safe


It would be hard for us to ensure that the data will be backed up if you do not authenticate the account.
