### ISSUE TITLE
Postman Pro trial has finished...no longer needed, cannot run my monitors since trial expiration!

### ISSUE THREAD

**Issue by datandreporting** [a85/POSTMan-Chrome-Extension#4294]
![monitor](https://user-images.githubusercontent.com/37142454/37088548-a19ed4d0-21f5-11e8-8b50-417c11707b62.JPG)
![no monitors available](https://user-images.githubusercontent.com/37142454/37088553-a61ada36-21f5-11e8-9ca4-b1c108351ae4.JPG)

## App Details:

Postman for Windows
Version 6.0.9
win32 6.1.7601 / x64
```

## Issue Report:
 1. Username is data&reporting, I use one monitor serving 5 calls daily, went on Postman Pro week trial to check the upgraded functionality, which I didn't need presently so has expired, however, the monitor does not work and I cannot even view it since expiration a couple of days ago
 2. Expected behaviour: Monitor was working fine before

Please can this be looked at...

**Comment by sdnts** [comment]
@datandreporting Can you head over to you [usage](https://app/getpostman.com/usage) page and make sure you haven't crossed limits?
