### ISSUE TITLE
Postman getResponseCookie is null while the cookie does exist

### ISSUE THREAD

**Issue by LiamDobbelaere** [a85/POSTMan-Chrome-Extension#4295]
## App Details:

```
Postman for Windows
Version 6.0.9
win32 10.0.16299 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there: recently, but it could've always been there, haven't been using Postman for testing until now
 2. Expected behaviour: getResponseCookie shouldn't return null
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
```
POST 3000/v2/login
content-type: application/x-www-form-urlencoded
cache-control: no-cache
postman-token: 21704ff7-c539-4e04-91c1-cc342baa7b3e
user-agent: PostmanRuntime/7.1.1
accept: */*
host: api.kweetet.dev:3000
cookie: language=nl-be; connect.sid=s%3AF7mq67R6DcXd7ucbbUOVfU_z96meLJSa.qq9hFfcnD8wqCN1j6uz%2F2wr84RNfnKAvw5sqd2%2FJ5vk
accept-encoding: gzip, deflate
content-length: 52
schoolCode=1001group=1classNumber=1childCode=1111
HTTP/1.1 200
status: 200
x-powered-by: Express
access-control-allow-origin: *
access-control-allow-methods: GET, POST, PUT, DELETE, OPTIONS
access-control-allow-headers: Content-Type, Accept, Authorization, X-Requested-With
access-control-allow-credentials: true
set-cookie: language=nl-be; path=/; expires=Thu, 07 Mar 2019 12:02:19 GMT; httponly,access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEwLCJpYXQiOjE1MjA0MjQxMzksImV4cCI6MTUyMDUxMDUzOX0.HaMImSASyXd6PCiG8PNCTcNLO_k4NlTeipozxqHzEyI; Path=/; HttpOnly; Secure
content-type: application/json; charset=utf-8
content-length: 159
etag: W/"9f-3Go/b+4u4krKTXJ47cQ/3Q"
date: Wed, 07 Mar 2018 12:02:19 GMT
connection: keep-alive
{"access_token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEwLCJpYXQiOjE1MjA0MjQxMzksImV4cCI6MTUyMDUxMDUzOX0.HaMImSASyXd6PCiG8PNCTcNLO_k4NlTeipozxqHzEyI"}

console.log(postman.getResponseCookie('access_token')) -> null
```
 4. Screenshots (if applicable)
![Screenshot](https://i.imgur.com/ytYdfFW.png)

I don't know how to reproduce the problem, the only difference I've seen was that it worked in an application that had a header Set-Cookie instead of set-cookie, but it could also be something else.

Here's a comparison of the set-cookie parts from both applications, works is the one that has the cookie in getResponseCookie:

```
Broken:
set-cookie: language=nl-be; path=/; expires=Thu, 07 Mar 2019 12:14:41 GMT; httponly,
access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEwLCJpYXQiOjE1MjA0MjQ4ODEsImV4cCI6MTUyMDUxMTI4MX0.AsgnXjja-43bsmaAzpHLLylbbWZ2Lwe3Q-gA9_rfe9E; Path=/; HttpOnly; Secure

Works:
set-cookie: access_token=s%3AnsTdIXwx7FKy4YUYAgqg7otDPjy8vaB76Apo9iimfi7CamXlVHZwK88JjNGFIbRG.fAnBBp6DEpd%2FUhBKqvpbEz5PzL%2BwnARCOnDX7r%2BeIpk; Max-Age=300; Path=/; 
Expires=Wed, 07 Mar 2018 12:38:15 GMT,connect.sid=s%3AkxtX7LSqiAETaIAJsFjBs7TLUCAv-0Vs.vzICygkmfyYyjdk2Gvruuxr6HJfaMqrnGpgYo2SfcHk; Path=/; HttpOnly
content-type: application/json; charset=utf-8
```

**Comment by thecuriousdev** [comment]
Hey, @TomDobbelaere thanks for reporting this issue. I tried from my end and its working fine, can you help me to reproduce this issue?

**Comment by LiamDobbelaere** [comment]
I will provide you with a possible way to reproduce this issue tonight.

**Comment by sivcan** [comment]
Closing this issue.
If the issue still persists, feel free to reopen it.

**Comment by shuiwuxing** [comment]
解决吗

**Comment by LiamDobbelaere** [comment]
I'm sorry I never got back to you. Unfortunately it's been a long time and I haven't worked on this particular part anymore, so you can leave the issue closed.

**Comment by shawn98ag** [comment]
I have encountered a similar problem. I am trying to log into two different APIs:
```
https://{my_host}:7443/api/public/session
https://{my_host}:8443/wsg/api/public/session
```
See these documentations for reference:
http://docs.ruckuswireless.com/vscg-carrier/vszh-public-api-reference-guide-3-2.html
http://docs.ruckuswireless.com/smartzone/3.6/vsze-public-api-reference-guide-3-6.html

They both return a cookie with the same name but different paths:
```
“JSESSIONID={JSESSIONID}; Path=/; Secure”
“JSESSIONID={JSESSIONID}; Path=/wsg; Secure”
```

I have a postman test that is supposed to read that cookie and save it to an environment variable for use in future calls to the API:
```
var cookie = postman.getResponseCookie("JSESSIONID").value;
pm.environment.set("COOKIE", cookie);
```

I started off hitting the first API that returned the cookie with Path=/ and the test worked well. It retrieved the cookie value and put it into the header of the next call.

Then I switched and started hitting the second API. It returned a cookie with Path=/wsg. I now had two different cookies with the same name but different values:
![image](https://user-images.githubusercontent.com/12926860/57886356-a07f5080-77f2-11e9-8046-84e4c696d314.png)

Problem #1: The postman test is only reading the value of the cookie from the first api (Path=/). I tried to figure out how to force it to pick up the one from the second api (Path=/wsg) but no luck. So I decided just to delete the first cookie:
![image](https://user-images.githubusercontent.com/12926860/57886890-db35b880-77f3-11e9-8bc9-41db01b5a63a.png)

Problem #2: Now the postman test is returning `null` for the cookie.

![image](https://user-images.githubusercontent.com/12926860/57887065-41bad680-77f4-11e9-82ca-6b2e1a75c335.png)
Windows 7 64bit

**Comment by dhubbard-ag** [comment]
I'm on v8.3.0 and I get similar behaviour.  From checking console for responses I believe `postman.getResponseCookie` is looking at stored values from previous request/response rather than the last response.  This aligns with the points @shawn98ag makes when deleting the stored cookie.

To actually get the cookie from the response I got the following working

```
function getCookie(name) {

    var cookie = ''

    let response = pm.response
    let headers = response.headers
    let members = headers['members']

    var vals = Object.values(members);

    for (let i=0; i < vals.length; i++) {

        let v = vals[i]

        if (v.key === 'Set-Cookie' && v.value.startsWith(name)) {
            var cp = v.value.split(';')
            if (cp.length > 0) {
                var cpp = cp[0].split('="')
                if (cpp.length === 2) {
                    cookie = cpp[1].replace('\"', '')
                }
            }
        }
    }
    return cookie
}

var ctoken = getCookie('XSRF-TOKEN')

pm.environment.set('userToken', ctoken);

```

A bit hacky I know, but worked for me
