### ISSUE TITLE
Postman Desktop Oauth Fails when Consumer Key contains Exclamation Point

### ISSUE THREAD

**Issue by jamesfrankman** [a85/POSTMan-Chrome-Extension#4300]
## App Details:
```
Postman for Windows
Version 5.5.0
win32 6.1.7601 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there: 
It has always been in the Desktop version, works fine in the Chrome version of Postman.
 2. Expected behaviour:
When setting a consumer key in OAuth that contains an exclamation point the authorization header should not url escape the exclamation point.  For instance, given a consumer key of:
 
foo!bar

The authorization header's consumer key should be:
OAuth oauth_consumer_key="foo!bar",........

 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app): None

 4. Screenshots (if applicable)
![win32postmanoauthsetting](https://user-images.githubusercontent.com/20843139/37119560-c92f855a-2225-11e8-943e-758575ea6098.PNG)
![chomepostmanoauthauthorizationheader](https://user-images.githubusercontent.com/20843139/37119561-c942fa68-2225-11e8-80a9-a01a17bef2dd.PNG)
![chomepostmanoauthsetting](https://user-images.githubusercontent.com/20843139/37119562-c951d268-2225-11e8-8f4b-183a46edc573.PNG)
![win32postmanoauthauthorizationheader](https://user-images.githubusercontent.com/20843139/37119563-c9607d2c-2225-11e8-838d-368108cb822d.PNG)

Steps to reproduce the problem
1. Create Post Request to some REST endpoint where the provided OAuth consumer key contains an exclamation point.
2. Set Authorization Type to OAuth 1.0
3. Enter consumer key that contains an exclamation point. i.e. foo!bar
4. Click Preview Request button
5. Check Authorization header and look for consumer_key. The key will be set to 'oauth_consumer_key="foo%21bar"' rather than 'oauth_consumer_key="foo!bar"' which will result in failed authentication with the rest endpoint.

**Comment by thecuriousdev** [comment]
@jamesfrankman thanks for reporting this. This is reproducible, We'll look into this.

**Comment by jamesfrankman** [comment]
Postman Chrome is deprecated, but I cannot switch to the Desktop version until this defect is fixed. Can you please provide an ETA on when this will be addressed?

**Comment by ssubashchandran** [comment]
Any updates on this? When i tried to integrate with Salesforce, the access token has an exclamation mark (!) as part of it and the api request was failing continuously with session expired error message. Then i tried with curl and it was working fine.

**Sample Token:**

Bearer  00D1U00000141bg!AQwAQNow006fK4GJ6y7C41ISyjEQ9DtGUcSpsta0kxscimFxXnbl9EjLjDGgEfcDxbhj5x1RFaFGn8fT0mSbLUsgo8.eN9Zd

**Comment by vikiCoder** [comment]
Hi everyone,

We have added an option to enable/disable URL encoding of Authorization header in OAuth1 (See the screenshot below). This option is available when `Request Headers` is selected in `Add authorization data` field. Turning this option off should solve the problem mentioned in the thread. Please let us know if it doesn't solve your problem.

It is out in the latest [Postman canary (v7.21.0-canary01)](https://www.postman.com/downloads/canary). Soon, it will be out in the next release of the Postman app (v7.21).

![image](https://user-images.githubusercontent.com/16588032/76386044-5bcc3380-6389-11ea-9c0f-a4f8a777c73a.png)

**Comment by vikiCoder** [comment]
The changes mentioned in my [previous comment](https://github.com/postmanlabs/postman-app-support/issues/4300#issuecomment-597457804) are out in the latest version of the Postman app (v7.21.0).
