### ISSUE TITLE
Proxy Formatting Issue

### ISSUE THREAD

**Issue by IeuanWalker** [a85/POSTMan-Chrome-Extension#4301]
## App Details:
Postman for Windows
Version 5.3.2
win32 10.0.15063 / x64

## Issue Report:
I need to add a proxy to the app but every time I try and add it, it's only saving the base URL. 
For example, our proxy uses the credentials in the URL like this - 'http://username:password@domain.gov.uk:8080'

But the app only saves 'domain.gov.uk:8080', causing 407 proxy authentication required.

It looks like this issue is due to Postman being an Electron app, meaning it's built on Chrome. Chrome, for security reasons, recognizes that as a deprecated format and strips it out ([info on that here](https://developer.mozilla.org/en-US/docs/Web/HTTP/Authentication)).

I'm hoping that there could be a workaround for this before the Chome App disappears

**Comment by thecuriousdev** [comment]
Hey, @IeuanWalker thanks for reporting this issue. We'll look into this and will keep you posted here.

**Comment by anishtimila** [comment]
I have same issue in Postman v6.0.10. Any update on the fixes @thecuriousdev

**Comment by IeuanWalker** [comment]
Close no longer an issue
