### ISSUE TITLE
Recent runs history not visible anymore in Collection runner

### ISSUE THREAD

**Issue by sanvipy** [a85/POSTMan-Chrome-Extension#4302]
## App Details:

```
Postman for Windows
Version 6.0.9
win32 6.1.7601 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there: With the current version
 2. Expected behaviour:Recent runs displayed
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
![image](https://user-images.githubusercontent.com/18203625/37198836-9d0e0bf4-23ba-11e8-9458-9567504ac116.png)

 4. Screenshots (if applicable)
![image](https://user-images.githubusercontent.com/18203625/37146074-b591ff04-22fd-11e8-9f63-b1b9cb23c5f8.png)

**Comment by thecuriousdev** [comment]
@sanvipy thanks for reporting this issue, we'll look into this and keep you posted here.

**Comment by sivcan** [comment]
Hi @sanvipy - When did this occur ?
You're running the runs and they're not showing up at all ?
or is that after the upgrade from probably 5.x to 6.x, the recent runs are not being displayed ?

Can you share the console log with me ?
Steps:
1. Launch the Runner 
2. Click on View > Developer > **Show DevTools (Current View)**

Thanks

**Comment by chrisron95** [comment]
This has been happening to me as well since the new update. Every time I quit postman, the recent runs list clears out. I'm using postman on MacOS.

These are my console logs when I open the runner.

```
runner.js:266042 Initializing the global config
runner.js:328755 Initializing settings
runner.js:266326 Booting waterline models
runner.js:266392 
Object
 "Successful ORM initialization"
runner.js:344471 
OperationalError
runner.html:1 Uncaught (in promise) 
OperationalError
__stackCleaned__
:
true
adapterMethodName
:
"find"
cause
:
Error: Malformed error from adapter: Should always be an Error instance, but instead, got: ``` [UnknownError: Maximum IPC message size exceeded.] ``` at file:///Applications/Postman.app/Contents/Resources/app/js/runner.js:29660:20
isOperational
:
true
message
:
"Malformed error from adapter: Should always be an Error instance, but instead, got:↵```↵[UnknownError: Maximum IPC message size exceeded.]↵```"
modelIdentity
:
"collectionrun"
name
:
"AdapterError"
raw
:
DexieError
stack
:
"AdapterError: Malformed error from adapter: Should always be an Error instance, but instead, got:↵```↵[UnknownError: Maximum IPC message size exceeded.]↵```↵    at file:///Applications/Postman.app/Contents/Resources/app/js/runner.js:29660:20↵From previous event:↵    at Deferred.toPromise (file:///Applications/Postman.app/Contents/Resources/app/js/runner.js:272245:19)↵    at Deferred.then (file:///Applications/Postman.app/Contents/Resources/app/js/runner.js:272106:22)"
__proto__
:
Error
```

**Comment by sivcan** [comment]
@chrisron95 - I'll look into this issue and get back to you.

**Comment by sivcan** [comment]
@chrisron95 @sanvipy - Can you tell us whether you're running multiple collections with a big number of iterations or just any collection run won't show up no matter the number of requests or  iteration count ?

We have discovered an issue with the underlying indexedDB that chrome uses which is throwing this error and are we'll be needing some feedback regarding this to help us triage this issue faster.

**Comment by sanvipy** [comment]
@sivcan Number of iteration or size of collections doesnt seems to have any impact. The history get cleared as soon as the runner is closed and reopened!

**Comment by sivcan** [comment]
@sanvipy - Apologies for the delayed reply.
We're still looking into this and will get back to you with further updates.

**Comment by sivcan** [comment]
@sanvipy - Can you test the [latest canary build](https://www.getpostman.com/canary) ?
Does it solve the issue for you?

**Comment by sanvipy** [comment]
This issue is solved now. Thank you @sivcan
