### ISSUE TITLE
Display list of workspaces that have selected collection

### ISSUE THREAD

**Issue by andreypolyak** [a85/POSTMan-Chrome-Extension#4304]
## App Details:

```
Postman for Windows
Version 6.0.9
win32 6.1.7601 / x64
```

## Issue Report:

At the moment I believe there is no way to identify which workspaces have selected collection. Can it be added somewhere? For example in modal windows that are opened when you select "Edit" or "Share" in context menu.

Example use-cases:
1. I see collection in workspace and realize that it shouldn't be there. I want to remove it from this workspace but if it's the only workspace for this collection it would be deleted.
2. I have similar named collection in personal and team workspace. I need to know if some specific collection is shared with the team or not.

**Comment by preethammavin** [comment]
Hi @andreypolyak , thanks for the feedback. We are looking into how we can improve the discoverability of the collections, adding this as a feature request.

**Comment by anudeepmedicharla** [comment]
Hi @andreypolyak, thank you for your suggestions. Our new update solves your issue by listing the workspaces that a collection is shared in. You can view this by going to "Manage Permissions" under any shared collection.

Closing this issue.
