### ISSUE TITLE
Collections with big responses cannot be updated using Postman API

### ISSUE THREAD

**Issue by andreypolyak** [a85/POSTMan-Chrome-Extension#4309]
## App Details:
```
Postman for Windows
Version 6.0.9
win32 6.1.7601 / x64
```

## Issue Report:

I have collections that have a lot different examples. And each example (response) can be as big as several MB XML file.

Unfortunately I cannot update such collections using Postman API because I get "Bad Request" response. My tests showed that I can update collection that has one response with 1 024 000 characters but cannot update if response has 1 152 000 characters. I also cannot update collection with two responses each containing 1 024 000 characters so looks like there is global limit for collection size in Postman update collection API.

**Comment by prashantagarwal** [comment]
@andreypolyak Thanks for reporting this. We will look into this issue.

**Comment by sobitankit** [comment]
@andreypolyak This has been fixed at our end. Can you try it again?

**Comment by ankitjaggi** [comment]
@andreypolyak This has been fixed. Can you try it again?

**Comment by andreypolyak** [comment]
@ankitjaggi It's now working as expected. Thank you!

**Comment by sivcan** [comment]
Closing this issue since it's resolved.
