### ISSUE TITLE
[Postman 6.0.9] My Collections are not sorted in the "SAVE Request" window

### ISSUE THREAD

**Issue by yishayn** [a85/POSTMan-Chrome-Extension#4314]
## App Details:

```
Postman for Windows
Version 6.0.9
win32 10.0.16299 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:
 2. Expected behaviour:
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 4. Screenshots (if applicable)

when saving a new request in the Save request window,
my collections are no longer sorted as they are on the main collection window:

![image](https://user-images.githubusercontent.com/27424400/37209836-45e7895a-23af-11e8-8b33-b4bda0dc0ba6.png)

![image](https://user-images.githubusercontent.com/27424400/37209635-9f3330a0-23ae-11e8-84e7-b0fbb81f1047.png)

**Comment by sivcan** [comment]
Hi @yishayn - Thanks you for reporting this and apologies for the inconvenience caused.
This has been fixed on our end and you can expect the same to be reflected in the upcoming release.
I'll update this thread once it's out.

**Comment by sivcan** [comment]
Hi @yishayn - The new update has been released (6.0.10) and it has the fix for the same.
Closing this issue.
