### ISSUE TITLE
Path Variable descriptions are not rendered in Documentation

### ISSUE THREAD

**Issue by Dzeinz** [a85/POSTMan-Chrome-Extension#4316]
## App Details:
Postman for Mac
Version 5.4.1
OS X 16.7.0 / x64

## Issue Report:
When using path variables (ex.  :orderNumber  ) in the URL field, params populates: Key field, a value field, and a description.

The issue exists in the Documentation.
- If the 'Value' field is left blank, the documentation fills in the URL field with absolutely no indication of the existence of the Key field requirement.
- The Description field is never rendered (even through forced workarounds)

Example:
>>  URL in application:  http://my.api.com/orders/:orderNumber 
![screen shot 2018-03-09 at 2 17 50 pm](https://user-images.githubusercontent.com/29408719/37227994-b74c9dac-23a4-11e8-9581-18ee88b041ca.png)

 >> URL in documentation: http://my.api.com/orders/
![screenshot2](https://user-images.githubusercontent.com/29408719/37228249-97fff3f8-23a5-11e8-9926-95ab113aa839.png)

^^ :orderNumber is not indicated in any manner

My current workaround for this has been to fill in the value with a placeholder before publishing my Documentation ( example:  dummy value \<orderNumber> results in URL of my.api.com/order/\<orderNumber> in the documentation ).
![screenshot3](https://user-images.githubusercontent.com/29408719/37228303-c4fb9678-23a5-11e8-9445-b932e376c5f0.png)
This workaround still does not publish any "Description" of the parameter, leaving my API consumers with little detail of the field origins.

The behavior I'd expect to see (in the documentation) based on the configurations above:
![screenshot4](https://user-images.githubusercontent.com/29408719/37228629-e298bac0-23a6-11e8-8def-d25cb2b24eb2.png)

**Comment by prashantagarwal** [comment]
@Dzeinz Thanks for suggesting this. We will look into this and keep you updated.

**Comment by Dzeinz** [comment]
I wouldn’t label this as solely an enhancement.  I personally view it as a defect if your software asks you to provide the Description for path variables but then does not provide it back in the documentation.

**Comment by liran-co** [comment]
This is extremely frustrating and renders the current documentation useless. I've spent hours trying to figure out why this is the behavior. I agree with with @Dzeinz, this is a serious defect.

**Comment by godfrzero** [comment]
Path variables have been available in documentation since late March.

@liran-co If it's still not showing up for you, I'll need more details. If it's a public doc please share the link or if it's a private doc, screenshots of both the app and documentation will do. If it's something you can't share publicly, you can open a ticket via our help center and I'll get it sorted asap.

**Comment by phcoliveira** [comment]
It appears to be showing, now, but it is not rendered by Markdown. It is simply text.

**Comment by preethammavin** [comment]
The issue has been fixed, do feel free to reopen the issue if it still persists.

**Comment by duboff** [comment]
Markdown still not being rendered on public API pages for Path Variables

**Comment by godfrzero** [comment]
Verified that path variable descriptions are not interpreted as markdown, but other descriptions are: body, query params, headers. Reopening.

**Comment by godfrzero** [comment]
This has now been fixed. Path variable descriptions in public docs are rendered and interpreted as markdown.
