### ISSUE TITLE
duplicate request item, click on item, not open it on window tab

### ISSUE THREAD

**Issue by yangxikun** [a85/POSTMan-Chrome-Extension#4319]
## App Details:

```
Postman for Mac
Version 6.0.7
macOS 10.13.3
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:

> always

 2. Expected behaviour:

> open duplicate request item on window tab

 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 4. Screenshots (if applicable)

￼
![1520742531930](https://user-images.githubusercontent.com/3364160/37249732-dd19d7f0-2527-11e8-8f28-de95d5b46624.jpg)

**Comment by prashantagarwal** [comment]
@yangxikun This has been fixed in our latest release 6.0.9. Thanks
