### ISSUE TITLE
Access is denied after updating to 6.0.9 version

### ISSUE THREAD

**Issue by hitesh17** [a85/POSTMan-Chrome-Extension#4322]
## App Details:
Postman helps you develop APIs faster
Postman for Windows
Version 6.0.9
win32 6.1.7601 / x64
```
Postman for Mac
Version 4.11.0
OS X 16.4.0 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there: recently
 2. Expected behaviour: 201K
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 4. Screenshots (if applicable)

**Comment by sivcan** [comment]
@hitesh17 Can you elaborate more on what access has been denied to you ?
Kindly share the console logs too - View > Developer > Show Dev Tools (Shared)
and 
View > Developer > Show Dev Tools (Current View)
