### ISSUE TITLE
Post Man :Error: Could not fetch from sync. Socket not connected.

### ISSUE THREAD

**Issue by anreddy018** [a85/POSTMan-Chrome-Extension#4323]
## App Details:

```
Postman for Windows
Version 6.0.9
64bit
```

## Issue Report:
 1. caught (in promise) Error: Could not fetch from sync. Socket not connected.
    at SyncRemoteFetcherService._dispatchCallback (file:///C:/Users/xxxx/AppData/Local/Postman/app-6.0.9/resources/app.asar/js/requester.js:75363:26)
    at EventEmitter.108.EventEmitter.emit (

**Comment by anreddy018** [comment]
caught (in promise) Error: Could not fetch from sync. Socket not connected.
    at SyncRemoteFetcherService._dispatchCallback

**Comment by sbrandwoo** [comment]
I'm also seeing this on version 6.0.9 for x64 Linux. I see "Connecting" permanently in the top bar and my data never appears.

**Comment by sivcan** [comment]
@anreddy018 @sbrandwoo - Thanks for reporting this, we'll look into this issue.
A quick fix might be to logout of the app and login again.

**Comment by sbrandwoo** [comment]
I believe the Sync servers were down. 6.0.9 didn't cope with this well and threw an error in the console. I clearly my local data and downgraded to 5.1.3 and could see the sync moving between Connecting, Syncing over and over.

This morning it looks like sync has recovered and working as expected.

**Comment by anreddy018** [comment]
Thank you ☺   Still same error.  Might be chrome security policies also preventing the  rest request and response.

**Comment by anreddy018** [comment]
i Seeing this error : Could not fetch from sync. Socket not connected. Could U please advise any workaround.

**Comment by kamalaknn** [comment]
@anreddy018 

The error indicates that we were not able to establish a connection with Sync. We were facing some performance issues on our servers. Things should be back to normal now. Could you confirm this?

**Comment by anreddy018** [comment]
Still Same issue. Socket not connected and its not I n sync. Please advise me the workaround. Thanks

**Comment by SeedyROM** [comment]
Getting this same error on Ubuntu 16.04 using the latest download from the main website. Only happens during the collection runner.

Only seems to be during post requests.

```
caught (in promise) Error: Could not fetch from sync. Socket not connected.
    at SyncRemoteFetcherService._dispatchCallback (runner.js:74599)
    at EventEmitter.108.EventEmitter.emit (common.js:17099)
    at _dispatch (common.js:24502)
    at EventEmitter.<anonymous> (common.js:24512)
    at emitTwo (events.js:106)
    at EventEmitter.emit (events.js:191)
```

**Comment by kylewill0725** [comment]
I seem to be having the same error as well on Windows 10. I have reinstalled v6.0.10 and it still won't connect. 

>From DevTools(Current View)
>
> error fetching Error: Could not fetch from sync. Socket not connected.
    at SyncRemoteFetcherService._dispatchCallback (requester.js:75398:26)
    at EventEmitter.108.EventEmitter.emit (common.js:17099:17)
    at _dispatch (common.js:24502:14)
    at EventEmitter.<anonymous> (common.js:24512:9)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:191:7)

Update: Tried again the next morning and it successfully synced. I'm on a laptop and it may have restarted over night.
