### ISSUE TITLE
§ character in variables is removed when creating an access token

### ISSUE THREAD

**Issue by etienneq** [a85/POSTMan-Chrome-Extension#4329]
## App Details:
Postman for Linux
Version 6.0.9
linux 4.4.0-101-generic / x64

## Issue Report:
I'm new to Postman and encountered this problem.

I tried to get a new access token (OAuth 2). I stored the client secret in an environment variable. The secret containts a § character. Client authentication is set to 'Send as Basic Auth header'. Authentication fails. When I decode the base64 encoded header I see that the § is missing in the secret.

Expected: username:abc§def
Actual:  username:abcdef

When I use a variable containing a § as URL parameter or in other situations that character is not removed.

**Comment by harryi3t** [comment]
@etienneq 
This is a known bug. There's already an issue open for this here https://github.com/postmanlabs/postman-app-support/issues/4070

Closing this in favor of the above mentioned issue. Please subscribe to that thread for updates.
