### ISSUE TITLE
Downgrade postman to 5.5.3

### ISSUE THREAD

**Issue by keyjm** [a85/POSTMan-Chrome-Extension#4331]
## App Details:

```
Postman for Mac
Version 4.11.0
OS X 16.4.0 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:
 2. Expected behaviour:
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 4. Screenshots (if applicable)

Having issues since I upgraded to latest version with workspaces(most likely because rest of the team is still on old version). How do I go back to 5.5.3?  There is no way to download old version from here -->https://www.getpostman.com/apps

**Comment by kdelsol-incomm** [comment]
The old version can be downloaded from here

https://dl.pstmn.io/download/version/5.5.3/windows64

https://dl.pstmn.io/download/version/5.5.3/osx64

**Comment by keyjm** [comment]
Thank you. That worked

**Comment by SamvelRaja** [comment]
@keyjm We always recommend people to be in the latest version of the app to ensure data integrity and up to date on the feature. 
Can you kindly share us the reason for going back a to 5.5.3 version? This will help us in understanding your concerns about our major release.

**Comment by dannoso** [comment]
I had to downgrade as the new version just installed on mac os doesn't launch

**Comment by SamvelRaja** [comment]
@dannoso can you elaborate a bit on your issue. We highly not recommend people to use a lower version.

**Comment by dejunqi2008** [comment]
Also, could not use  Postman interceptor in the new version, and it could not work without it.

**Comment by numaanashraf** [comment]
@dejunqi2008 Postman Interceptor works only with our deprecated Chrome apps at the moment. Could you elaborate on the issue you are facing?

**Comment by svitch** [comment]
@SamvelRaja 5.5.3 just works!
After I installed latest 6.3 - app screen is white on launch (win8.1, Corei7 with Intel® HD Graphics)

**Comment by jengwood** [comment]
@numaanashraf POST and PUT requests are coming through as a GET in the new version

**Comment by wxb2dyj** [comment]
@jengwood  the most version 7.1.1 also has this problem, so I have to downgrade to use old version.

**Comment by codenirvana** [comment]
@wxb2dyj That might be because of 301/302 redirect where the original request method is not retained on redirects.
Please confirm if that is the issue. If so, we are tracking that here: #4001

**Comment by nhhockeyplayer** [comment]
awesome thanks friend
