### ISSUE TITLE
How to use regular expression in postman script

### ISSUE THREAD

**Issue by talktoudhai** [a85/POSTMan-Chrome-Extension#4334]
Hi,

I would like to know how to use regex in Postman to validate the value format in JSON response. 

e.g.:
"PhoneNumber" : "800-800-800"

**Comment by sivcan** [comment]
@talktoudhai  Issues on this repo are supposed to be about any bug reports or feature requests.
For questions about how to use the product itself please check our [Discourse community](https://community.getpostman.com/) or [Stackoverflow](https://stackoverflow.com/questions/tagged/postman).

**Comment by mlbd-tanzeeb** [comment]
@talktoudhai please check. I think, it will work
pm.expect(jsonData.PhoneNumber).to.match (/^\d{3}-\d{3}-\d{3}$/);
