### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by poojakhatri** [a85/POSTMan-Chrome-Extension#4336]
When I send data through row data its is working fine but same time I am using form-data its shows error.

**Comment by sivcan** [comment]
Hi @poojakhatri - Kindly elaborate more on this.
Provide us the steps and if possible then the sample data to reproduce this error.

Also, check that you're using the latest version of the Postman App [Postman 6](https://www.getpostman.com/apps)

Let us know if you're still facing the issue after updating to the latest version.
