### ISSUE TITLE
Search should not search in folder name

### ISSUE THREAD

**Issue by cawoodm** [a85/POSTMan-Chrome-Extension#4337]
Currently when one searches requests it seems to look in the folder name as well. This can be downright annoying when the folder name contains the word you are searching for.

So, if you have a folder called "Elastic Search" and you search for the word "search" it returns all collections in the folder even if they do not contain the word "search".

![image](https://user-images.githubusercontent.com/498834/37401303-e9b6b96c-2787-11e8-9c8c-e96529011b84.png)

**Comment by preethammavin** [comment]
Hey @cawoodm thanks for the feedback, we will look into how to make this experience better

In the meantime you can use Find in the App (CMD + Shift + F) which lets you search and filter for specific entity
