### ISSUE TITLE
Failed to import collection because of duplicated request guid

### ISSUE THREAD

**Issue by Toumassa** [a85/POSTMan-Chrome-Extension#4338]
## App Details:
```
Postman for Windows
Version 6.0.9
win32 6.1.7601 / x64
```

## Issue Report/:
Hello

Today I tried to import a collection of request/tests that I exported 7 monts ago with an older version of Postman (collection v1).
I ended with a simple error saying 'Failed to import collection ***'. Nothing else.

After investigating a little I figured out that the problem is duplicated request guid ("8191d8ab-fb6d-13b2-6be3-a2abe562ddc3") in the ordered list of requests of the folder

```json
{
	"name": "[scenario2] Override dates behaviour",
	"description": "",
	"collectionId": "83f928b5-098e-6528-520d-f79443af1886",
	"order": [
		"400b802d-1e0a-0be6-59bd-0fa7b5538f76",
		"25e1e745-7586-d687-a7b5-9fb83a2d772a",
		"ecded490-1949-0859-f6fb-af77eafe5933",
		"91f682c9-7e82-eb97-a661-c1eae68d544f",
		"8191d8ab-fb6d-13b2-6be3-a2abe562ddc3",
		"8191d8ab-fb6d-13b2-6be3-a2abe562ddc3",
		"13a83d14-a8f1-d591-f555-503edb4a0eb0",
		"40a7a8b9-093e-59be-fc53-2da52b0bff27",
		"997e2812-3163-baef-4bc7-f1224b2853f6",
		"68c0df66-81ad-4c7b-631a-65554ec2e7a0"
	],
	"owner": "720672",
	"folders_order": [],
	"id": "3f7a4af6-3937-9bbf-b2a4-9a212a453cb2"
},
```
However I never edited this file manually, always exported with the current version of Postman. 
So I am suggesting to be more permissive in this case or simply ignore duplicates as it could affect others.

Thanks

**Comment by sivcan** [comment]
Hi @Toumassa - That's strange.
I guess you've already manually deleted that duplicate ID and been able to import the collection.

If you're still experiencing this issue then feel free to reopen this issue.
