### ISSUE TITLE
Hightlight newline characters in headers for debugging

### ISSUE THREAD

**Issue by vzhufk** [a85/POSTMan-Chrome-Extension#4339]
## App Details:
```
Postman for Linux
Version 6.0.9
Ubuntu 17.10 Budgie
```

So. Recently I had a problem with Desktop Postman. I find out if you somehow paste New Line character(Enter) in headers postman refuses to send any request.

## Code
```
POST  HTTP/1.1
Host: google.com
Content-Type: application/json

Cache-Control: no-cache
Postman-Token: 2c6589c8-481a-4e4c-8467-88f79ae7ef9e

```

Steps to reproduce:
Just copy New Line Char and paste it into Headers values and try to Send request.

**Comment by kamalaknn** [comment]
Hi @vzhufk,

I'm not sure about the implications of a header name having a newline character. Not sure if there's much Postman can do.

Postman could highlight newlines, trailing whitespaces differently so it helps you with debugging.

**Comment by ritwijsinha** [comment]
Hey @vzhufk 

We've introduced the feature for visualizing whitespaces and highlighting invalid characters.

To use this, please update to Postman 7.21.0 😄

For more info, go through this: https://learning.postman.com/docs/postman/sending-api-requests/requests/#troubleshooting-your-requests

Cheers! 🎉
