### ISSUE TITLE
How to fetch the value from a nested JSON response in Postman Test Script?

### ISSUE THREAD

**Issue by ujjalroy1985** [a85/POSTMan-Chrome-Extension#4343]
{
"inventory": [
{
"siteName": "Default",
"uuid": "89dae40e-9702-4bb3-9d3d-ea4bdc33ea5d",
"devices": [
{
"cards": [
{
"uuid": "3404c0e3-3eb7-47fb-a62e-e261374999c1",
"name": "10GBE-1STR",
"ports": [
{
"uuid": "623ddb79-7155-4199-814c-0c76ffefc70a",
"name": "PORT",
"position": 1,
"alias": null
}
],
"position": 6,
"cards": []
},
{
"uuid": "06f19746-8104-40d0-ac96-b0c3bcdf6daf",
"name": "10GBE-1STR",
"ports": [
{
"uuid": "886b477e-a07d-4ffb-a84f-f3ac59b9c091",
"name": "PORT",
"position": 1,
"alias": null
}
],
"position": 5,
"cards": []
},
{
"uuid": "24a8f01d-8258-4f57-8168-4d68d5fe5fd9",
"name": "UVRX-4S",
"ports": [
{
"uuid": "a2c06c6f-5a59-47d7-9f2d-b699bd1a7ed8",
"name": "PORT",
"position": 2,
"alias": null
},
{
"uuid": "8571e9bd-5ee7-4f20-8ffd-b6c37840ba17",
"name": "PORT",
"position": 1,
"alias": null
},
{
"uuid": "5b4442ff-6b49-454b-8b82-daa3d0eb2845",
"name": "PORT",
"position": 4,
"alias": null
},
{
"uuid": "e49efac0-1770-4c6f-bee1-48dd06c6b3ec",
"name": "PORT",
"position": 3,
"alias": null
}
],
"position": 2,
"cards": []
},
{
"uuid": "27b0dc00-02bf-430f-b91b-cc1e8c721743",
"name": "1GBE-2STR",
"ports": [
{
"uuid": "7fd79b71-a7f6-44dc-bf9f-59933e54fd58",
"name": "PORT",
"position": 2,
"alias": null
},
{
"uuid": "f578fd3c-9f7b-4a9e-8c4e-d283dcef9fce",
"name": "PORT",
"position": 1,
"alias": null
}
],
"position": 1,
"cards": []
},
{
"uuid": "2e23b828-2dca-45b0-b674-41253229beda",
"name": "1GBE-2S",
"ports": [
{
"uuid": "bdf3ffd9-d476-440d-9181-dc1aa0bfe749",
"name": "PORT",
"position": 2,
"alias": null
},
{
"uuid": "d8cc8506-8333-4c9e-a39f-bcb61c5d2f93",
"name": "PORT",
"position": 1,
"alias": null
}
],
"position": 4,
"cards": []
}
],
"supervisors": [
{
"uuid": "050a2fe8-e67b-4f40-a0e2-8fff05146924",
"name": "CBS(N)",
"position": 7
}
],
"ports": [],
"numberOfRouteTemplates": 0,
"uuid": "31eb17c0-ea53-4b6f-a3c0-4e3d86b962dc",
"name": "CBS(N)",
"modelName": "SCHIVALELLO",
"rackPosition": null,
"numberOfAlarms": null,
"unManaged": false,
"rackUnits": null,
"pingEnabled": true,
"assignedRackUuid": "89dae40e-9702-4bb3-9d3d-ea4bdc33ea5d",
"brandName": "CISCO",
"ipAddress": null,
"isReachable": true
}
],
"longitude": null,
"lattitude": null
}
]
}

From this response how can i capture the value of uuid= 623ddb79-7155-4199-814c-0c76ffefc70a under test script in postman?

**Comment by harryi3t** [comment]
@ujjalroy1985 Issues on this repo are supposed to be about any bug reports or feature requests.
For questions about how to use the product itself please check our [Discourse community](https://community.getpostman.com/) or [stackoverflow](https://stackoverflow.com/questions/tagged/postman)
