### ISSUE TITLE
form-data : doesn't work but raw work when i setup application/json

### ISSUE THREAD

**Issue by Lakrimou** [a85/POSTMan-Chrome-Extension#4344]
i'm trying to test an endpoint ressource 
when i put data using form-data i get this message:

`{
    "code": 400,
    "message": "Invalid json message received"
}`

when i use raw and setting JSON(application/json) it's wok fine for me !

**Comment by kamalaknn** [comment]
Hey @Lakrimou 

We'll need some more information to identify why this isn't working for you. From the error message, it looks like the API server is always expecting a JSON body. 

I'm closing this as this isn't a bug with the Postman App itself. You'll find our [community forum](https://community.getpostman.com/) more helpful for discussion and debugging.
