### ISSUE TITLE
Grammar error

### ISSUE THREAD

**Issue by qa-bob** [a85/POSTMan-Chrome-Extension#4346]
![error message grammar](https://user-images.githubusercontent.com/3505937/37474121-d6923172-282c-11e8-91a4-f9c09bc14efc.jpg)

## App Details:

```
Postman for Windows
Version 6.0.9
win32 10.0.15063 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there: the First time I have seen this.
 2. Expected behavior:  Good grammar in error messages.
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app): NA
 4. Screenshots (if applicable)

**Comment by sivcan** [comment]
Hi @qa-bob - Thanks for reporting this.
We've fixed this typo on our end and the same will be reflected in the upcoming release.

Closing this issue.
