### ISSUE TITLE
Feature Request: Have local variables that are global to all workspaces

### ISSUE THREAD

**Issue by bit-cmdr** [a85/POSTMan-Chrome-Extension#4347]
## App Details:
```
Postman for Mac
Version 6.0.9 (6.0.9)
macOS 10.13.3 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there: New request due to changes in v6
 2. Expected behaviour: Previously global variables were global to everything, but not shared with anyone. Now global variables are shared and associated with a specific workspace.

There are certain situations where you may want to store sensitive information such as keys, passwords, etc. that can be accessed by any workspace, but are not shared or stored anywhere beyond the local machine. Previously this was accomplished with global variables. I understand why the functionality was changed, but I think there is a need for having a set of variables that are truly globally accessible by all workspaces and not shared. Having globals pinned to a workspace is kind of a misnomer now, as they aren't really global, just a higher level of scope within the workspace. Postman support recommended that I open a new feature request for this. Postman Support ID #17861

**Comment by sdnts** [comment]
Hey @bit-cmdr! Have you taken a look at [collection variables](https://www.getpostman.com/docs/v6/postman/environments_and_globals/variables)? If you set up variables here, they will follow your collection, wherever it goes (whichever workspace it belongs to).

This still won't address the issue of not being shared, though, so I'm adding this as a feature request.
You can use unshared environments too to do this kind of thing.

Maybe we should take a look at the flow.

**Comment by davidschwab** [comment]
I'd like to see a "super global" type approach implemented where these globals span all workspaces. Using collection variables will not work as the same variable is duplicated in every collection. I want a single place (source of truth) to update my variables that span across all my workspaces.

**Comment by a85** [comment]
There are no plans for super global variables right now. Every variable scope introduces an additional level of coupling. We discourage global coupling as it's not a good practice.
