### ISSUE TITLE
Failing assertions with multiple-word reason phrases

### ISSUE THREAD

**Issue by charliebillen** [a85/POSTMan-Chrome-Extension#4348]
## App Details:

```
Postman for Windows
Version 6.0.9
win32 10.0.14393 / x64
```

## Issue Report:
We've recently started using some of the `pm.response.to.be.*` assertions described in the [Sandbox API reference](https://www.getpostman.com/docs/v6/postman/scripts/postman_sandbox_api_reference) and have noticed a problem with those that assert against reason phrases that contain multiple words, such as 'BAD REQUEST' and 'NOT FOUND'.

The assertions are not taking the spacing into account, i.e. comparing 'BADREQUEST' to 'BAD REQUEST'.

![image](https://user-images.githubusercontent.com/5968632/37509267-90791206-28ee-11e8-900b-9af276a0fc5e.png)

I can see some [assertions](https://github.com/postmanlabs/chai-postman/blob/71ebf1acf7e869b5a26aee95259b83a5f1c9017c/lib/index.js#L132-L133) in the `chai-postman` library that appear to be upper-casing the the assertion names and comparing them to the reason phrase, but I'm not sure if that is used internally to Postman when running tests.

### Reproduction steps:
1. Set up a request to an endpoint that returns `404 NOT FOUND`, e.g `https://httpbin.org/status/404`.
2. Create a test that asserts `pm.response.to.be.notFound`.

**Comment by sivcan** [comment]
Hi @charliebillen - Thanks for reporting this. We'll look into it and get back to you.
However, you can use the status code check in the mean time.

```
pm.test("Status code is 404", function () {
    pm.response.to.have.status(404);
});
```

**Comment by charliebillen** [comment]
No problem.  Thanks, @sivcan

**Comment by kunagpal** [comment]
@charliebillen Thanks again, this bug is being fixed here: https://github.com/postmanlabs/chai-postman/pull/88

We'll update this thread when the fix is available in the app 😄

**Comment by kunagpal** [comment]
@charliebillen This has been fixed and is generally available, could you try it out in the latest stable version of the app?

**Comment by charliebillen** [comment]
@kunagpal I can confirm it works as expected.  Thank you.
