### ISSUE TITLE
Postman Crashes at random on ubuntu Linux

### ISSUE THREAD

**Issue by seunzone** [a85/POSTMan-Chrome-Extension#4351]
My Postman crashes at Random.
my fix: Install Postman using terminal:
See details here:
https://blog.bluematador.com/posts/postman-how-to-install-on-ubuntu-1604/

Always run postman from the terminal like so 
![screenshot from 2018-03-16 22-33-50](https://user-images.githubusercontent.com/22764463/37545722-466c477e-296a-11e8-9837-4ae9a9bdb26c.png)

You should not experience any crashing

**Comment by sivcan** [comment]
Hi @seunzone are you on the latest version of the postman app i.e. Postman 6.0.9 (as of now) ?
If not then can you download the latest version and let us know if you're still experiencing this issue ?

**Comment by seunzone** [comment]
Fixed, thanks. So sorry for the late response
