### ISSUE TITLE
Nesting `` `` in links no longer creates a hyperlink.

### ISSUE THREAD

**Issue by JeromeLefebvre** [a85/POSTMan-Chrome-Extension#4356]
## App Details:
```
Postman for Windows
Version 5.5.0
win32 10.0.14393 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:
Recently. I used to nest `` `` inside of the names of URLs, for example: [``google``](https://google.com) and click on the word google would open the google page. It no longer behaves this way.
 2. Expected behaviour:
This syntax should create a link 
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 4. Screenshots (if applicable)

Can't click on the bottom link.
![image](https://user-images.githubusercontent.com/4224967/37635587-cc284110-2c3f-11e8-830a-7744b2e7c3bb.png)

The markdown code
![image](https://user-images.githubusercontent.com/4224967/37635595-d807788e-2c3f-11e8-9ff5-fda1fa8c9c8f.png)

**Comment by sdnts** [comment]
Hi @JeromeLefebvre, I just tried this on the latest version of the app (v6.0.10), and this seems to be working. Of course, following the link from the app itself isn't possible right now, but if you open the collection's documentation in a web browser, the link should work. You can open a collection's documentation by clicking on the `View in web` button right above the panel you attached a screenshot of.

I'm closing this issue for now, but please let me know if this doesn't work for you, and I'll reopen!
