### ISSUE TITLE
Collection runner not updating the environment variables which are set in tests

### ISSUE THREAD

**Issue by kishorebattula** [a85/POSTMan-Chrome-Extension#4357]
## App Details:

```
Postman for Mac
Version 6.0.10
OS X 17.4.0 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:
After last to last update.
 2. Expected behaviour:
Environment variables should be updated
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 4. Screenshots (if applicable)

**Comment by sivcan** [comment]
Hi @kishorebattula - Can you please check if you've check marked the 'Persist Variables' option before running the run and also that you've set the correct environment for the run to work upon and also update.

You can refer to the following video (It shows using a data file but the process is the same - you can just skip attaching the  data file)
Discourse - [Discourse discussion about this issue](https://community.getpostman.com/t/running-specified-requests-in-runner-from-array/1204)
Video : [Runner - Persisting variables](https://www.youtube.com/watch?v=NuQD2Xmg3x8&feature=youtu.be)

If you're still facing the issue then kindly provide the steps to reproduce this issue and I'll reopen it.
