### ISSUE TITLE
[Linux] Stuck on splash screen

### ISSUE THREAD

**Issue by stianlagstad** [a85/POSTMan-Chrome-Extension#4359]
Hi!

After downloading the latest linux version (Postman-linux-x64-6.0.10.tar.gz), extracting in to my desktop and attempting to start the `Postman` file all I get is this message:
```
➜  Postman Postman
Shared window not present!
```

Anything I can do to look further into why this is happening? Tried googling the message but found nothing of interest. I'm using the i3 window manager, but I don't think that should matter as the previous version I had worked just fine.

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there: Just encountered it after installing the latest version. The previous version I had worked fine (don't know exactly which version that was, but it wasn't very old).
 2. Expected behaviour: Postman should open as usual. This does not happen.
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app): N/A
 4. Screenshots (if applicable): N/A

**Comment by SamvelRaja** [comment]
@stianlagstad 
1. can you provide us the OS distribution, This will help us in narrowing down the problem.
2. And, also I want you to ensure 
    i. **Quit** all the postman process running before you start the new version.
    ii. Double check, You **replaced** all the old version files with the latest version ones.

**Comment by stianlagstad** [comment]
Sorry about that! Here:
```
➜  cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.3 LTS"
```

I replaced the old version on my first try, but got that error message. I then deleted the folder, downloaded the new version again and unpacked that. Same result. I made sure that the old process was gone by doing `killall postman`.

**Comment by rokkie** [comment]
Had the same issue. I 'fixed' it by removing `$HOME/.config/Postman` which is not particularly elegant, but at least is starts again. Also running ubuntu 1604.

**Comment by lriverd** [comment]
ty @rokkie 
That works for me too!

**Comment by Qu4tro** [comment]
Had the same issue. No postman process was running.

$ uname -r 
4.15.9-1-ARCH

Fixed it by @rokkie suggestion. Thanks. 

EDIT: There are a few solutions below. Do try them out before deleting your Postman config!

**Comment by stianlagstad** [comment]
Will deleting that folder remove my stored collections, environments ++?

**Comment by sivcan** [comment]
Hi @stianlagstad - It'd be great if you could help us triage this issue by sharing some logs rather than clearing the local data of the Postman App so that we make the fix for everybody in the future than taking up a workaround for it.

Note: If you're not signed into the app and your data has not been synced then clearing the data of the app will lead to permanent loss of your data.

To help us debug this issue,
can you launch the app from the terminal (By changing directory to the extracted folder and running ./Postman to execute the app when inside the directory).
Kindly share the logs from the terminal. 

Thank you for your help and we regret the inconvenience caused to you.

**Comment by stianlagstad** [comment]
Hey @sivcan! I already did that in the first post although it probably wasn't clear:
```
➜  ./Postman
Shared window not present!
```
And that's the only output.

**Comment by sivcan** [comment]
Hi @stianlagstad  - Can you try to access postman without using i3 window manager ?

@Qu4tro, @rokkie and @sensey66 - Are you guys also using i3 window manager ?

**Comment by stianlagstad** [comment]
@sivcan I'll try that this weekend and report back.

**Comment by rokkie** [comment]
@sivcan I don't know, how do I check this?

**Comment by Qu4tro** [comment]
@sivcan.
Yes. I was using i3 and I got the same message as @stianlagstad 

@rokkie 
` wmctrl -m | head -1 `

**Comment by rokkie** [comment]
@sivcan I'm using Compiz

**Comment by emxjay** [comment]
I'm getting the same issue under Windows 7 (Postman **v6.0.10**).

Excerpt from `SquirrelSetup.log`:

```
2018-03-30 14:41:29> Program: Starting Squirrel Updater: --processStart Postman.exe
2018-03-30 14:41:29> Program: Want to launch 'C:\Users\XXX\AppData\Local\Postman\app-6.0.10\Postman.exe'
2018-03-30 14:41:29> Program: About to launch: 'C:\Users\XXX\AppData\Local\Postman\app-6.0.10\Postman.exe': 
```

Thanks.

**Comment by stianlagstad** [comment]
@sivcan Sorry, I was not able to try this as I had to format my computer. But the postman app worked when I installed it on a new system. (i.e. no shared window error)

**Comment by romaincarlino** [comment]
Hello, I have exactly the same problem.
I am on windows 10 and the postman window doesn't open when I start it. I have an issue "Shared window not present" on my terminal.
It was working perfectly for one month and stop to work without any visible argument.
I tried to delete everything from Postman (Appdata/Local and Appdata/Roaming, $HOME/.config) and download it again but nothing changed.

Do you have any ideas to help me please?

**Comment by ClementParis016** [comment]
I encountered the same issue on the same OS & release as the OP, but after executing `killall Postman` everything went back on track, so there may be different origins to this problem.

**Comment by karanpathak** [comment]
Thanks @rokkie 
That works for too!
Easiest fix

**Comment by carlosabs** [comment]
Same problem here. Using Ubuntu with openbox.

**Comment by jormaechea** [comment]
Updated today and it's broken again.
Last time I fixed it by removing config files.

Any update on this issue?
I'll wait a couple days before removing it again.

```
$ uname -a
Linux xxxxxxx 4.13.0-43-generic #48~16.04.1-Ubuntu SMP Thu May 17 12:56:46 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

**More info**
If i run `sudo su` and then run `postman` it works just fine. So it's definitely something about per user configs.

**UPDATE**
I started playing with config files. Moved the following files and tried to launch postman without luck:
```
~/.config/Postman/window
~/.config/Postman/Preferences
~/.config/Postman/SingletonCookie
~/.config/Postman/SingletonLock
```
Then moved them back into place and postman started normally. Don't know why, but it's working now, logged in and with all my settings.

**Comment by jawikufi** [comment]
I just 
`$ rm -rf ~/.config/Postman/SingletonCookie`
`$ rm -rf ~/.config/Postman/SingletonLock` 
and it is working again.

**Comment by moroine** [comment]
On my side I did

```
$ rm -rf ~/.config/Postman/SingletonCookie
$ rm -rf ~/.config/Postman/SingletonLock
$ sudo chown $USER:$USER -R ~/.config/Postman
```

**Comment by JacquesLeRoux** [comment]
Thanks @rokkie
That works for me too!

**Comment by Gerrit-K** [comment]
For others looking: please don't mindlessly delete files or directories! Try the solution from @ClementParis016 first, i.e. check if there are still Postman processes pending (potentially from another user?). Stopping them might already solve the problem without the risk of losing any data.

**Comment by yurii-github** [comment]
i didn't use postman too often, but got this problem too.
what i've noticed that it creates copy of itself on each run

![image](https://user-images.githubusercontent.com/1162656/49067823-c5c0d800-f22d-11e8-8800-986930595034.png)

as i remember i've ignored link App and run postamn directry from ./app/Postman
Anyway, I also had to 

1. redownload new version
1. rename ./config/Postman dir
1. run it and stop
1. then replace ./config/Postman/IndexedDB with old data

that's how i fixed for myself

regards

p.s.
maybe it was already fixed in new version, let's see

**Comment by vonboth** [comment]
This is still unsolved.

I'm running Ubuntu 18.04.

Deleting the complete .config/Postman folder cannot be an accepted solution for this problem as one will loose all data.

Is there a solution in sight? It is quite a pain **** to do this for every update.

**Comment by yurii-github** [comment]
your data is in  ./config/Postman/IndexedDB
after ./config/Postman is recreated just replace  ./config/Postman/IndexedDB with old data

p.s.
ofcourse backup whole  ./config/Postman folder if something goes really bad

**Comment by flhaz** [comment]
I was getting this error, I tried to delete the .config/Postman folder after saving IndexedDB
Same error
I downloaded the last version with no more .config/Postman or .config/PostmanCanary folder.
I am now getting 

> 1546858085747 main info ["Booting PostmanCanary 6.7.0-canary06, linux-4.4.0-141-generic on x64"]
> 1546858085748 main info ["EventBus\\x7einitialize - Success"]
> 1546858085751 main info ["UpdateHandler\\x7einit - Success"]
> 1546858085752 main info ["RuntimeExecutionService\\x7einitialized: Success"]
> 1546858085760 main info ["ProtocolHandler\\x7einit - Success with status: false]"]
> 1546858085785 main info ["Qitting app"]
> 1546858085788 main error ["WindowManager\\x7egetSharedWindow: Shared window is not available"]

This is not working.

**Comment by SamvelRaja** [comment]
@flhaz  Could you try killing all running Postman process and retry?

**Comment by flhaz** [comment]
`ps aux | grep postman` returns no result

**Comment by adglow-dbarredo** [comment]
@flhaz same error here... running it as a superuser it works: sudo ./Postman... but I haven't figured out why yet

**Comment by abhik137** [comment]
Same problem, Ubuntu 18.04. Found this error on starting from terminal
```
1553104449312 pluginHost warn ["PluginInstallationService-installFromLocal Caught an error",{"errno":-18,"code":"EXDEV","syscall":"rename","path":"/tmp/postman.openApi","dest":"/home/ubuntu/.config/Postman/plugins/postman.openApi/0.0.9","name":"Error","message":"EXDEV: cross-device link not permitted, rename '/tmp/postman.openApi' -> '/home/ubuntu/.config/Postman/plugins/postman.openApi/0.0.9'","stack":"Error: EXDEV: cross-device link not permitted, rename '/tmp/postman.openApi' -> '/home/ubuntu/.config/Postman/plugins/postman.openApi/0.0.9'"},{"pluginId":"postman.openApi","version":"0.0.9","status":"failed","error":{}}]
```
I guess it would be better to just move the files instead of trying to rename them as `/home` and `/tmp` can be on different partitions

**Comment by harryi3t** [comment]
There seem to be two issues:
- Postman not starting and is stuck on the splash screen. Deleting the user data directory (~/.config/Postman) lets you open the App
 - Postman not starting with no UI since there is already a process running in the background. Killing that process lets you open the App

The second issue does not seem related to this and we have created a separate ticket which is being tracked here https://github.com/postmanlabs/postman-app-support/issues/8205

For the first issue (which is the original issue reported by the OP) can the affected users share the logs from `~/.config/Postman/logs` at help@getpostman.com while including the issue ID (4359) in the subject line? This would really help us narrow down the bug.

**Comment by shahidcodes** [comment]
This worked for
`kill $(ps aux | grep 'postman' | awk '{print $2}')`

**Comment by DannyDainton** [comment]
Is this still an issue that people are facing on the latest version?

**Comment by DannyDainton** [comment]
Going to close this issue due to inactivity - If anyone is still facing an issue we can open this back up again.
