### ISSUE TITLE
Collection runner times out consistently when using data variables from a CSV file

### ISSUE THREAD

**Issue by nicholmikey** [a85/POSTMan-Chrome-Extension#4362]
The collection runner consistently throws a "Script execution timed out" error when trying to use variables from a CSV file. 

Here is a sample of the request. This is the valid JSON https://pastebin.com/RD0SZ3Ua 

## App Details:
```
Version 6.0.10
win32 6.1.7601 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there: For the past week of attempts it does not work. I have tried it in the past with smaller JSON bodies and it worked. 
 2. Expected behavior: I expect it to insert the 'test' variable and run the POST as expected. 
 3. Console logs: https://pastebin.com/g38bNdeE 

1. Create a CSV with a variable 'test' 
2. Try to POST the JSON body https://pastebin.com/RD0SZ3Ua 
3. Collection runner throws error. 

If I add the variable 'test' to my environment variables it works. If I just enter a value it works. As soon as I try to use a CSV it does not work. I am trying to update the currency rates in this JSON body with a CSV file, but I find trying to update any field causes the same issue. I have tested this on multiple computers including a mac.

**Comment by callmeaatrey** [comment]
@nicholmikey thanks for letting us know. We'll look into this and let you know.

**Comment by nicholmikey** [comment]
Thank you @callmeaatrey , if you need any additional info I am happy to provide it. I have had success in the past with using CSV files with the runner but there is just something unique about the shape of this json request that is breaking it.

**Comment by nicholmikey** [comment]
I'm embarrassed to report it was an issue in our pre-request script. Our script tries to swap in environment variables and when a variable was not found it would hang postman. I'm closing this ticket.
