### ISSUE TITLE
Allow auto-update to skip to latest version.

### ISSUE THREAD

**Issue by glenpike** [a85/POSTMan-Chrome-Extension#4363]
```
Postman for Mac
Version 6.0.8 to Version 6.0.10
OS X 15.6.0 / x64
```

## Issue Report:
When the system updates in the background, it appears to get the next version rather than the latest.  As a nice-to-have, can we make it jump to the latest version instead?
The use-case/reason for this is because I had manually installed 6.0.8 due to bugs in 6.0.9 and had disabled auto-update until 6.0.10 was released with the fixes.

**Comment by numaanashraf** [comment]
Closing this as we now always update to the latest version.
