### ISSUE TITLE
Access to Read for non Team members

### ISSUE THREAD

**Issue by arzanardi** [a85/POSTMan-Chrome-Extension#4365]
Hello, 

It would be interesting if external users, who did not necessarily need to have Postman accounts, could access the documentation in a restricted way (such as a login screen with email and password or some token)

**Comment by AtomicSteve** [comment]
I would also like to see this feature implemented. Our use case as a digital agency is that we have a large number of collections and monitoring calls that mean all our users need a Pro account to be able to share them and keep our documentation in one place. 

But we also have a large number of external collaborators that need read-only access to the documentation. The only current way I can see to share and keep them informed is to publish the documentation to anyone who has the URL or pay for a Pro account for each external collaborator; Neither of which is suitable.

Our ideal would be to allow us to add free users with read-only access to a Pro team. Or for us to be able to specify a list of Free postman accounts that can view it when we publish documentation.

**Comment by zachheine** [comment]
I would also appreciate this just for our internal users to be able to hit [docs.ourdomain.com](#) and get the latest published version while logged in.

**Comment by bpdev97** [comment]
This would be a really useful feature.

**Comment by clarkritchie** [comment]
👍 Agreed.  Having the docs public is blocking us from using Postman for documentation.

**Comment by amlwwalker** [comment]
Yeah I asked about this too. You _can_ have this if you are willing to pay enterprise by setting the permissions on a collection here 
![image](https://user-images.githubusercontent.com/2920180/94812141-3cacf600-03ee-11eb-91af-86221dd53fad.png)

So yeah, it would be basically great if we could have a non-public URL to the documentation that was read only - like the public documentation, just.... not public for non enterprise users

I'm not asking to have free enterprise features, its just about read only documentation. That would be great

**Comment by Raja-Simha** [comment]
Duplicate of #6681
