### ISSUE TITLE
Request hangs at sending

### ISSUE THREAD

**Issue by jacobmetrick** [a85/POSTMan-Chrome-Extension#4366]
## App Details:

```
Postman for Linux
Version 6.0.10
linux 4.15.9-1-ARCH / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there: Just recently
 2. Expected behaviour: A request is sent
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app): None available, as the request is never sent
 4. Screenshots (if applicable): See https://github.com/postmanlabs/postman-app-support/issues/2559 for similar issues.

I just send things and it doesn't work. Other similar bugs have suggested uninstalling, deleting the .config directory and reinstalling, but that has made no difference. I've also tried 5.x versions but I see the same issue.

**Comment by callmeaatrey** [comment]
@jacobmetrick this is really unwonted. Can you help me understand this better by giving steps on how to reproduce this?

**Comment by jacobmetrick** [comment]
Was able to fix by deleting my AUR directory postman-bin and re-cloning, then reinstalling.
