### ISSUE TITLE
I POST a request to a url with postman and the result was; {     "message": "The Response content must be a string or object implementing __toString(), \"boolean\" given.",     "status_code": 500 }.   But I did no see any changes on the url destination using Chrome as my browser

### ISSUE THREAD

**Issue by Peternomous** [a85/POSTMan-Chrome-Extension#4369]
## App Details:

```
Postman for Mac
Version 4.11.0
OS X 16.4.0 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:
 2. Expected behaviour:
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 4. Screenshots (if applicable)

**Comment by sivcan** [comment]
@Peternomous - Can you provide the steps to reproduce this issue ? 
Also, I suggest you to kindly update to the [latest version of the app](https://www.getpostman.com/apps) and try it.

Thanks.
