### ISSUE TITLE
How to convert below request payload of file upload into postman 

### ISSUE THREAD

**Issue by Manish082007** [a85/POSTMan-Chrome-Extension#4372]
Windows 10 X64, 

I am uploading pdf file using postman.

![image](https://user-images.githubusercontent.com/30290047/37817966-8ddc1cc2-2e9e-11e8-95b2-0fcb0cd5fb59.png)

I have tried with below parameter but its not working

![image](https://user-images.githubusercontent.com/30290047/37818032-c929183e-2e9e-11e8-9e3a-4fd0a4714f51.png)

**Comment by sivcan** [comment]
@Manish082007 - If you've found a way to solve it / any resource that you've come across then it'll be awesome if you could share the solution also.

It'll help those who'll be coming in later and are struggling to figure out this problem.

Thanks for contributing!

**Comment by Manish082007** [comment]
I found the solution

Look in request payload always key is "name" variable so which is "0", so there are 2 keys with 0 value, one contains the file which application/pdf & another key is json data. so if you have multiple document upload next 2 key names are "1". describe this solution in below screen shot. 


![image](https://user-images.githubusercontent.com/30290047/37917734-d5e4c91a-313c-11e8-8283-c6451c2bde20.png)

Thank you
