### ISSUE TITLE
pre-request script - request.url contains variable name instead of variable value

### ISSUE THREAD

**Issue by Misiu** [a85/POSTMan-Chrome-Extension#4373]
## App Details:

```
Postman for Windows
Version 6.0.10
win32 10.0.16299 / x64
```

## Issue Report:
 1. I have environment variable that holds base URL of my endpoint:
![snap 2018-03-23 at 09 44 39](https://user-images.githubusercontent.com/1741838/37819807-0f3ebab0-2e7f-11e8-90ef-26c64554b7c8.png)
 2. I'm using that variable as part of my url:
![snap 2018-03-23 at 09 46 52](https://user-images.githubusercontent.com/1741838/37819891-50171686-2e7f-11e8-91be-fc79f685c1f7.png)
 3. Inside my pre-request script I'm using `request.url` variable, but instead of giving me full url (`http://localhost:63564/test/secure_get`) I get this: `{{url}}/test/secure_get`

This is my test script that shows that bug:

```
function getAuthHeader(requestUrl) {

    requestUrl = requestUrl.toLowerCase();
    
    console.log("URL: "+requestUrl);
    return "test";
}

postman.setEnvironmentVariable('hmacAuthHeader', getAuthHeader(request.url));
```

I think that when accessing request.* inside pre-request scripts url should be already `calculated`.

**Comment by sivcan** [comment]
Hi @Misiu - The urls are not resolved inside the test scripts.
You've to use pm.environment.get / pm.globals.get to use the values inside the test scripts. 
Maybe use string interpolation or concatenation.

There's a similar feature request for variables being resolved inside the test script thus I am closing this one.
This is a similar issue : https://github.com/postmanlabs/postman-app-support/issues/3322

**Comment by Misiu** [comment]
@sivcan thank for such quick reply.
I've upvoted that issue.

**Comment by sivcan** [comment]
@Misiu - Cool
