### ISSUE TITLE
[Postman 6.0.10] [Debian] Postman is not starting stuck in an infinite loop preparing workspaces

### ISSUE THREAD

**Issue by VictorRos** [a85/POSTMan-Chrome-Extension#4374]
I encountered this issue after upgrading Postman 5.5 to the latest (6.0.10)

Infinite loop while trying to initialize workspace with the following message:
**"Preparing your workspaces ... This might take a few minutes"**

![postman_preparing_workspaces_infinite_loop](https://user-images.githubusercontent.com/6940422/37825253-7221fed4-2e8f-11e8-987a-c343d63a461e.png)

It's related to #4292.

I couldn't find a workaround like *AppData* on Windows to temporary solve this situation.
So I stay to Postman 5.5 until a solution is found.

**Comment by harryi3t** [comment]
@VictorRos 
Could you try opening the app from command-line and share the logs here? That would help us debug this and fix the issue.

```bash
# Just open a terminal and type the path to the latest version of postman (6.0.10)
$ /path/to/postman
```

Also, you asked
> I couldn't find a workaround like AppData on Windows to temporary

On linux the user data is in `~/.config/postman`. You can move/rename this directory to fix the issue. But before that please share the logs :)

**Comment by VictorRos** [comment]
It's working when I try opening the app with **Postman** or **Postman &** in command-line.
Logs:
```
$ Postman
ORM initialization successful
App events bus { name: 'booted', namespace: 'shared' }
App events bus { name: 'booted', namespace: 'requester' }
```

But when I do **Postman & exit** to close the terminal after starting Postman then I encounter the infinite loop.

I was searching the user data in `~/.cache`.
Thank you by the way ;)

**Comment by wjohnson000** [comment]
I ran into this same issue on Windows-10.  When I attempt to start `Postman` via a short-cut, sometimes it succeeds and sometimes it fails.  So I created an alias in my `cygwin` instance to start it via the command-line, and it works consistently (so far).  At least I have a solution.

**Comment by tomershay** [comment]
Happens on Mac OS as well. Happened after upgrading to the latest version.

**Comment by dannylittle** [comment]
This is also happening to me on a Windows Server 2012 R2. The shortcut's target is "_C:\Users\user\AppData\Local\Postman\Update.exe --processStart "Postman.exe_". After changing directory into the app-6.0.10 and executing postman.exe, here is the output and Postman starts correctly, 
ORM initialization successful
App events bus { name: 'booted', namespace: 'shared' }
App events bus { name: 'booted', namespace: 'requester' }

**Comment by Beera819** [comment]
Hi, after upgrading to latest release 6.1.2

I see the GET calls being stuck with no response...

![image](https://user-images.githubusercontent.com/39547835/40406650-2819f84e-5e7f-11e8-86f1-da2fb73119c6.png)

On few GET calls, I see error messages as below;

![ssl error](https://user-images.githubusercontent.com/39547835/40406707-6629810e-5e7f-11e8-9f26-0e68b68f2839.PNG)

**Comment by harryi3t** [comment]
@Beera819 Make sure you don't have an invalid proxy enabled (settings -> proxy)

**Comment by rex3du** [comment]
Happens on me with Version 6.1.2 and Mac OS High Sierra 10.13.4. It stuck on the loading view saying "Preparing your workspaces... this might take a few minutes. "

**Comment by Beera819** [comment]
@harryi3t  I never keyed in any proxy settings from the day I started using Post man. I use System Proxy

![image](https://user-images.githubusercontent.com/39547835/40412175-34cfdb56-5e90-11e8-9da6-e7ce23d88619.png)

**Comment by harryi3t** [comment]
@Beera819 Does your system proxy requires authentication, coz that is not supported yet and can cause issues.

**Comment by nissim-kurle** [comment]
Happened with me on 6.1.2 this is the log when i try to open it on command line . I do not want to delete the app data since a lot of work is not saved. Is there a workaround ? Tried downloading 6.1.3, but does not work as well. 
ORM initialization successful
App events bus { name: 'booted', namespace: 'shared' }
App events bus { data: {}, name: 'booted', namespace: 'requester' }
I am on Ubuntu 16.04 . 
Thanks , 
Nissim

**Comment by SparK-Cruz** [comment]
[meta]
@Beera819 Avoid posting an unrelated issue in other, very specific, issue like this. You can always open a new one

**Comment by JohnTJohnston** [comment]
This started happening on both of my Windows 10 PCs today.  Running Postman-win64-6.1.3.  Reinstalling failed.  And Uninstalling is also failing.  Please help.

[install-fail.txt](https://github.com/postmanlabs/postman-app-support/files/2102570/install-fail.txt)

**Comment by julian-martinez-del-campo** [comment]
Happening to me as well. On archlinux using postman v6.1.2 and 6.1.3. Reinstalling and/or removing .config/Postman does nothing.

Running from cli shows: ORM initialization successful

After eliminating the cache I am postman is able to show the login screen, but if I login or click the link to continue without logging in it brings me to the "Preparing workspace, this may take a few minutes" dialog, where it stays and doesn't do anything.

**Comment by trev-dev** [comment]
@julian-martinez-del-campo I had the exact same problem. I suspect it may have had something to do with the recent electron update on arch (maybe). What fixed this problem for me was removing the postman package and replacing it with postman-bin. I'm up and running.

**Comment by julian-martinez-del-campo** [comment]
@trev-dev Thanks! That seemed to have fixed it. I too suspected electron, I saw all the processes just sitting there not doing much after the last update.

**Comment by JohnTJohnston** [comment]
Just tried reinstall again.  Worked this time.  No idea why.

**Comment by zacacollier** [comment]
for other Arch users that find their way to this issue - the solution @trev-dev describes worked for me as well

remove the original Postman package
```
sudo pacman -R postman
```

then install [postman-bin](https://aur.archlinux.org/packages/postman-bin/) from the AUR

you might also have to kill any lingering Postman processes before it'll work - `ps -ax | grep postman` should point you in the right direction

**Comment by vkarumuri-phunware** [comment]
Steps that solved my issue: 

1. Delete Postman using Option 2 (directly from hard disk) https://macuninstallguides.com/remove-postman-2-1-3-on-mac.html
2. Reinstall the app 
3. Open the app. -> This time It prompted to login again.

**Comment by egorzot** [comment]
Check user rights for this folders:

- /opt/Postman

- /home/user/.config/Postman

I updated postman with root that's why I have to change owners rights for this folders for current user and it solves the issue:

`sudo chown -R user:user /opt/Postman /home/user/.config/Postman`

**Comment by DISKONEKTeD** [comment]
I'm getting the same issue on MacOS after update

I deleted the app (as in just trashed it and deleted from the trash, but not the actual setting files in the library as I wanted to keep my collections). I then re-downloaded and reinstalled and that fixed it

You don't need to delete the library files, as suggested in the post above me refering to mac.

This allows you to keep your collections (i don't actually have a postman account or w/e, so i don't login)

**Comment by MisinformedDNA** [comment]
@harryi3t Can we reopen this? This is clearly still an issue.

Here are my logs. It was failing via the UI, but succeeded at the command line (on Win10).

[SquirrelSetup.log](https://github.com/postmanlabs/postman-app-support/files/2435860/SquirrelSetup.log)

**Comment by MisinformedDNA** [comment]
I ran into the issue again today. I dare say that I found [a better alternative](https://github.com/Huachao/vscode-restclient/blob/master/README.md).

**Comment by farisfawaaz** [comment]
i deleted /home/user/.config/Postman folder on ubuntu 18.04.1 and it started working for me and since it synced all my collections i didn't have to worry about them. hope this helps.

**Comment by MisinformedDNA** [comment]
I believe my workaround worked until Postman was updated again. So I would have to perform the workaround each time Postman was upgraded. Sigh.

**Comment by lanka-senanayaka** [comment]
> Check user rights for this folders:
> 
> * /opt/Postman
> * /home/user/.config/Postman
> 
> I updated postman with root that's why I have to change owners rights for this folders for current user and it solves the issue:
> 
> `sudo chown -R user:user /opt/Postman /home/user/.config/Postman`
@egorzot 
Solution worked like a charm, Thanks

**Comment by taqvi** [comment]
Hi, I solved this by just Deleting all Cookies. Same happens whether it is Postman or Insomnia. In Postman cookies are at top right corner below Send button and in Insomnia Cookies are in top left tab after Environment drop down. With this solution I'm up and running.

**Comment by danielmmf** [comment]
rm ~/.config/Postman/Singleton*
