### ISSUE TITLE
When selecting a large file for upload postman screen goes black

### ISSUE THREAD

**Issue by vladah** [a85/POSTMan-Chrome-Extension#4375]
## App Details:
Postman for Windows
Version 6.0.10
win32 10.0.10586 / x64

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there: Just started using postman. No previous history
 2. Expected behaviour: Selection of the file for upload should be ok.
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 4. Screenshots (if applicable)

![capture-selecting-file-for-upload](https://user-images.githubusercontent.com/14980954/37831692-d9b76e8e-2e7c-11e8-92b2-1e75d6c0c988.PNG)

![capture-postman-screen-black-after-selecting-file](https://user-images.githubusercontent.com/14980954/37831703-e41eea64-2e7c-11e8-857b-f416895a7ab8.PNG)

I see this issue with this particular file of ~3G. Other files of ~1.5G seem to upload correctly.

To reproduce a problem:

1) Choose form-data in the Body of the request.

![capture-form-data](https://user-images.githubusercontent.com/14980954/37833141-eedeb228-2e80-11e8-9813-64b2491b853e.PNG)

2) select file. In my case the size of the file is ~3G.

**Comment by vladah** [comment]
The same issue appears in postman on Linux with the same file.

Postman for Linux
Version 6.0.10
linux 4.4.0-87-generic / x64

**Comment by sivcan** [comment]
Hi @vladah - Thanks for reporting this. We'll look into this further and get back to you.

**Comment by prashantagarwal** [comment]
@vladah Can your try this on latest Postman app (6.1.4)

**Comment by vladah** [comment]
@prashantagarwal 

Hi Prashant,

I've repeated the test with Postman app 6.1.4 and again got the black sreen.
![capture-postman-version](https://user-images.githubusercontent.com/14980954/42231254-0c5c578c-7eb9-11e8-93dd-198dc86c2e88.PNG)

![capture-postman-selecting-file-for-upload](https://user-images.githubusercontent.com/14980954/42231255-0fffba46-7eb9-11e8-8395-e3d585da8340.PNG)

![capture-postman-black-screen](https://user-images.githubusercontent.com/14980954/42231258-1290fb44-7eb9-11e8-8526-b4494a6c762b.PNG)

**Comment by prashantagarwal** [comment]
@vladah  So is it going black just by selecting the file or when you actually send the request ?

**Comment by prashantagarwal** [comment]
@vladah If you are still facing this issue can you update here.

**Comment by yoransabern** [comment]
I am also having this issue in v6.2.4, only with big files, a 1GB file still works, but files of 3GB give the black screen when selecting the file, the same thing happens when executing a request where i'm downloading a big file.

**Comment by prashantagarwal** [comment]
@yoransabern Can you provide details about your operating system.

**Comment by yoransabern** [comment]
Windows 10 Home 64 bit

**Comment by ika-microsoft** [comment]
Also having the same issue.

**Comment by staypuppy** [comment]
Same issue - Win 10 Enterprise x64 Version 1709

**Comment by vladah** [comment]
@prashantagarwal  It's when I select the file that I see the black screen. I tried this again with v6.2.5 and Windows 10 Version 1709

![capture-select-file](https://user-images.githubusercontent.com/14980954/44677600-5f48d580-aa04-11e8-8591-ff811f8fed91.PNG)
![capture-select-file2](https://user-images.githubusercontent.com/14980954/44677607-6243c600-aa04-11e8-9025-d4917d707303.PNG)
![capture-select-black-screen](https://user-images.githubusercontent.com/14980954/44677610-64a62000-aa04-11e8-8ecc-e19a58373cd4.PNG)

**Comment by prashantagarwal** [comment]
@vladah I did some digging on this issue and it seems to be an issue specific to Windows. I will update this thread once I find some workaround/solution to this issue.

**Comment by henderbj** [comment]
Hi,
I got same problem with Postman on Ubuntu 16 x86_64.
The black screen is after selecting a big file (2.6GB on my case) for upload. After the black screen, the Postman menu works, and some menu commands works, like "New Postman Window", but some others don't work, like "New Tab".

**Comment by therealalbundy** [comment]
So what's the verdict on this one folks? 
For me it occurs when I paste large JSON blob (>100MB) into body tab for a POST request. 
Postman window goes black, but drop down menus are available, though non-functional.
Windows 10, Postman 6.5.2.

**Comment by jzabroski** [comment]
I believe I have narrowed the problem down to Immutable.Js Facebook library used in the [electron-react-boilerplate-site](https://github.com/amilajack/electron-react-boilerplate-site) for efficiently (hahaha LOLOL) determining whether the a sub-tree needs to be re-rendered or not based on whether an update is an actual update or not.  This is just a hunch since I don't have access to Postman code but web developers are sort of predictable in how they code things.

**Comment by lhyla** [comment]
Having same problem.

Collection ~10k requests and exported JSON~600k of lines (160mb)
After clicking 'import' postman screen goes black, and after some seconds Postman is turning off.

Windows 10 x64
Postman Desktop 6.7.2

**Comment by grg-akshay** [comment]
@vladah We tried reproducing the issue and we were not able to reproduce the issue.
Can you please update to latest version of postman app v7.
After updating if the issue still exists, can you please provide screenshot of devtools (View -> Developer -> Show Devtools(current view))
Can you please provide logs (View -> Developer -> View logs in Explorer)

**Comment by arnitkun** [comment]
Hi!

I tried to reproduce the issue. The steps I have taken:

1.  Create a bunch of dummy files (binary and text) of sizes **1MB, 100MB, 1GB, 2GB, 4GB.** 
2.  Sent the files to a local _dummy server_ I made, by attaching them in form of form data-type and binary type body to my post requests. 
3.  The above two steps have been tried on Windows 10 Home x64 and macOs 10.
4.  The postman _app version_ was 7.2.2

The server was receiving all the posted files and even when my server was not able to handle the large files in the post requests, the app behaved normally and successfully sent the files.  I would like to add that the dummy files contained some random data, but that should not be an issue.

Would it be possible for someone who is facing this issue to provide with the exact steps that lead to reproducing this problem?

**Comment by yoransabern** [comment]
I no longer have this issue in 7.2.2, but i also have a new computer with windows 10 pro.

**Comment by shamasis** [comment]
@yoransabern congrats on your new computer :-P ... and thanks for letting us know that this isn't happening anymore. We did a lot of underlying improvements to address this bit-by-bit. The latest app should have everything that sets the right expectation.

**Comment by kkrakovych** [comment]
FYI - I reproduced the mentioned black screen on macOS 10.14.6 with Postman Version 7.5.0.

Post request received ~70Mb Excel file. First time I was not able to get the file because of limitation: 'Response size too large'. After I selected 'Sent and Download'. Than selecting place and file name, meantime (after about 10-20 seconds) the Postman screen became black.

Please let me know if you need additional details to reproduce the issue.

Update: Even more, I have increased file size limit to 100 Mb, I successfully performed post request but when I was saving the file - Postman application became black.

**Comment by kwoyna** [comment]
I am having the same exact problem for Mac Version 10.14.6 Postman Version 7.14.0

Trying to post 147.7 MB xml file.  I pasted the contents into the message window.  The screen went to black.  Now whenever I restart Postman, the screen shows for a few seconds and then goes black.  Only option seems to be to uninstall Postman and the re-install it.

This issue was reported March 2018.  Is there an ETA for a fix?

**Comment by ghost** [comment]
Same problem on windows 10 with postman win64-7.14.0
Saving a 34.42 MB JSON response locks the app with a black screen, relaunching the app only is necessaryin my case, reinstalling does not solve the problem.
My config :
![setup](https://user-images.githubusercontent.com/50437233/71453347-2c684a80-27ce-11ea-87cf-91340a1f1fa6.png)
No output in the dev tools javascript console after pressing the save response button ...
I can copy/paste the response in VS Code and save it into a file from there ...

**Comment by StacySiz** [comment]
same problem with latest postman version and mac os

**Comment by mccannt** [comment]
We have been making continuous improvements to the performance of the application recently. 
Are larger files still an issue for everyone? If so, what size?

We would like to gauge if the improvements are having the intended impact.

**Comment by yoransabern** [comment]
I no longer have this issue, just tried with a 3.5GB file and the app did not go black. Version 7.31.1 windows 10 64 bit

**Comment by mccannt** [comment]
Great, thanks for the follow-up. 
I am going to close out this issue for the time being. If this is still an issue for anyone on the most recent version, please feel free to reopen with additional details.

**Comment by ptiyer** [comment]
Can anyone let know, for which version of POSTMan the large file upload issue still exists? and for which version onwards it is resolved?

**Comment by jzabroski** [comment]
@ptiyer This is a 2 year old question. Maybe mention what version you are on and whether you tried the latest version. You're bothering people about something that hasn't been discussed in 2 years without any added context - it's bad net etiquette.
