### ISSUE TITLE
App Settings override?

### ISSUE THREAD

**Issue by savage4pro** [a85/POSTMan-Chrome-Extension#4376]
## App Details:
```
Postman for Windows
Version 6.0.10
win32 10.0.16299 / x64
```

Is it possible to override some application settings (for example, request timeout, follow redirects, proxy settings, etc.) for different workspaces, environments, collections or specific requests?

Although I do not have TOO many collections, but they are still _slightly_ different and inconvenient each time to switch checkboxes and set limits when changing the current task.

**Comment by sivcan** [comment]
Hi @savage4pro - There are no settings override as of now in the app for different workspace.
However, I'll mark this as a feature request.

**Comment by a85** [comment]
These are available through request level settings now.
