### ISSUE TITLE
[BUG] Value return undefined

### ISSUE THREAD

**Issue by Jasonseah** [a85/POSTMan-Chrome-Extension#4380]
## App Details:

```
Postman for Mac
Version 4.11.0
OS X 16.4.0 / x64
```

## Issue Report:

Hi guys I encounter a very weird bug this afternoon
![image](https://user-images.githubusercontent.com/7570733/37874499-d47f76a4-3062-11e8-9dd1-61d8dbfc8e30.png)

The screenshoot above I have 2 set of fields but the 1st set return value as undefined 

![image](https://user-images.githubusercontent.com/7570733/37874508-06d5f3ee-3063-11e8-84d2-644b587e1525.png)

What information you guys would need ? I am happy to provide any information for this issue

Additional 
![image](https://user-images.githubusercontent.com/7570733/37874574-0bd88c20-3064-11e8-90c9-badc8c402453.png)

**Comment by preethammavin** [comment]
@Jasonseah can you update to the latest version of Postman app and check if it still persists.

**Comment by Jasonseah** [comment]
Using Version 6.0.10 (6.0.10) still facing the same issue.

But I guess it should be fine, cause I can solve it by open another new tab with the same input and url.

**Comment by numaanashraf** [comment]
@Jasonseah This issue does not seem to be reproducible on the latest version of the app (v6.7.2). Please re-open if you are still facing this on the latest version.
