### ISSUE TITLE
The subsequent running requests always get the input value of the prior request, which causes test case failed.

### ISSUE THREAD

**Issue by hungdao-pyco** [a85/POSTMan-Chrome-Extension#4383]
## App Details:

```
Postman for Mac
```

## Issue Report:
 1. This bug is frequently happened.
 2. Expected behaviour:
- The subsequent requests should not get the value of prior request to run.
 3. Console logs:

 **Precondition:**
- There are 2 GET requests having the same endpoint, but different input data. 
- Explanation: the GET request "CheckEmailExisted" is used to check the input email existed on the system or not. If not return error code - 200, if yes returns 400.
- Data: 
   + Existed email "existed@yopmail.com"  => create request "checkEmail-Existed"
   + Non-existing email: "abc@gmail.com" => create request "checkEmail-NonExisting"

- Testcase tab for each or requests:

> pm.environment.set("email", "existed@yopmail.com");
> 
> var jsonData = pm.response.json();
> pm.test("environment to be production", function () { 
>     pm.expect(jsonData.message).to.equal("Email was registered"); 
> });

---
```
`pm.environment.set("email", "abc@yopmail.com");

var jsonData = pm.response.json();
pm.test("environment to be production", function () { 
    pm.expect(jsonData.message).to.equal("Email is invalid"); 
});
```

**Steps:**
Step1: Running one of 2 request name above, in my case: "checkEmail-Existed" first.
=> Console log
`GET
<url>api/v1/users/checkEmailExisted?email=existed@yopmail.com
04:18:25.679

GET /api/v1/users/checkEmailExisted

accept: application/json
cache-control: no-cache

user-agent: PostmanRuntime/7.1.1
host: <url>
accept-encoding: gzip, deflate
HTTP/1.1 400
status: 400
date: Mon, 26 Mar 2018 09:18:26 GMT
x-content-type-options: nosniff
x-xss-protection: 1; mode=block
cache-control: no-cache, no-store, max-age=0, must-revalidate
pragma: no-cache
expires: 0
x-frame-options: DENY
x-application-context: application:development:8080
content-type: application/json;charset=UTF-8
content-length: 55
accept-ranges: none
connection: close

{"message":"Email was existed","error":"E001"}`

Step 2: Running the rest and the test case is failed, and the console log shows:
GET
<url>api/v1/users/checkEmailExisted?email=**existed@yopmail.com** <<< NOT **abc@gmail.com**

**Work-around**: have to run the request "checkEmail-NonExisting" again to make it pass.

Please share your ideas in this case.
Thank you so much.

**Comment by kamalaknn** [comment]
Hi @hungdao-pyco 

I do not have a complete picture of what you're trying to do. I'm guessing you have two requests with `api/v1/users/checkEmailExisted?email={{email}}` and you set the environment variable in your scripts with `pm.environment.set("email", "abc@yopmail.com");`.

The point to note here is that requests are sent before the test script is executed. Which means that if you set an environment variable in test script it will not take any effect as the request has already been sent.

Could you confirm that you are setting the variable in your pre-request script?

If you are indeed setting the variable in your pre-request script and you are still seeing requests sent with outdated values, please provide a sample collection that helps us reproduce this issue.

**Comment by hungdao-pyco** [comment]
Thanks @kamalaknn ,

 It's solved as your think.

**Comment by kamalaknn** [comment]
Great @hungdao-pyco 

I'm closing this issue then. Happy building!
