### ISSUE TITLE
Base64 wrong data with cyrillic chars

### ISSUE THREAD

**Issue by akavato** [a85/POSTMan-Chrome-Extension#4384]
## App Details:

```
Postman for Windows
Version 6.0.10
win32 6.1.7601 / x64
```

## Issue Report:
 1. Constant problem
 2. Basic auth encodes wrong data, if login contains cyrillic chars

**Comment by harryi3t** [comment]
Duplicate of https://github.com/postmanlabs/postman-app-support/issues/4070
