### ISSUE TITLE
Post Binary Image Encoding Error

### ISSUE THREAD

**Issue by loretoparisi** [a85/POSTMan-Chrome-Extension#4385]
Hi,
I'm using the `binary` option to post an image from my local disk. I'm trying to emulate the same as

```
curl -s -X POST -F "image=@data/my_image.jpg" http://localhost:3000/api/image.post
```

For some reason (I guess encoding) the request fails, since the server does not get right image encoding (or size?).

By defaults when using this option I have a `application/x-www-form-urlencoded` as `Content-Type` header.

Other attempts:

- Using the `form-data` option and setting a `file` Key as `File` type;
- Using the `Content-Type` as `multipart/form-data`.

**Comment by JoGosGitHub** [comment]
Hi,

I see the same issue.
When using multipart my debug shows that Postman leaves the content transfer encoding empty.
But it should be set to binary.

**Comment by loretoparisi** [comment]
Hi, at the end it worked with this setup:

<img width="1136" alt="schermata_2018-04-25_alle_16_40_43" src="https://user-images.githubusercontent.com/163333/39253294-d72c37cc-48a7-11e8-8833-6fdfebeb0730.png">

and

<img width="1151" alt="schermata_2018-04-25_alle_16_40_55" src="https://user-images.githubusercontent.com/163333/39253329-e3bd5066-48a7-11e8-8a22-1d07a3b4c564.png">
