### ISSUE TITLE
Postman native app collection lost after update version

### ISSUE THREAD

**Issue by sujitkn** [a85/POSTMan-Chrome-Extension#4387]
I have been using postman since long time and did lot of experiments before buy the lincene and quite happy with so far, few days back I started using native app by importing all collection from existing chrom extension and keep on add and modify to the script in native app but unfortunately all modified script are not sync. Over the weekend my native app got upgrade and I lost all my collection.

Can you please help to restored all collection of is there a way? Waiting for your reply.

Window 
Postman v6.0.10

**Comment by hyxppz** [comment]
Me too. Somebody Help please.

windows 
v6.0.10  to v6.1.3

**Comment by fquirin** [comment]
For me it is the other way round. 6.1.3. (Windows 8.1) was buggy so I've downgraded to 6.0.10 ... and now all my collections are gone :-( :-( :-(

Edit:
For what it's worth I have a file called 'chrome-devtools_devtools_0.localstorage' in the folder '[user]\AppData\Roaming\Postman\Local Storage' that has a date right before the downgrade and a new one called 'file__0.localstorage'. But the old one is not big enough to hold my data I guess and since it is called 'devtools' its probably just some console log or something.

**Comment by ivdelchev** [comment]
Same here, that is a disaster

**Comment by kaijuking** [comment]
This happened to me today after "upgrading" the native app from 6.0.10 to 6.1.3! All my collections and environment variables are gone now! Anyway of getting them back?!
Two lessons learned: 1) always back up your collections and environment variables and 2) never update Postman again

**Comment by ivdelchev** [comment]
I lost hundreds of saved queries but at least discovered a better alternative - https://insomnia.rest/ (seems to be mac only).

**Comment by a85** [comment]
We test upgrade paths extensively to make sure there is no data loss. Please email us at help@getpostman.com so we can look at recovery options.

**Comment by laixun** [comment]
This happened to me after upgrade postman native app from 5.5.0 to 6.1.3, all my collections and environment configs are gone!

Windows
native app 5.5.0 to 6.1.3

**Comment by SamvelRaja** [comment]
@laixun  I would recommend you to follow the instruction from [here](https://community.getpostman.com/t/upgraded-to-6-0-7/1097
).

**Comment by preethammavin** [comment]
Hi,
If you still have the issue please follow the link pointed to by @SamvelRaja and write to us at help@getpostman.com. 

I am closing this issue for now, but do feel free to open it if the issue still persists.
