### ISSUE TITLE
Mac native app stuck with unknown code

### ISSUE THREAD

**Issue by Mihai1706** [a85/POSTMan-Chrome-Extension#4389]
## App Details:

```
Postman for Mac
Version 6.0.10
macOS 10.13.3 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there: Has happened twice in the last two months
 2. Expected behaviour: Sending an HTTP request uses body and header specified in request by user.

Use mac native app normally changing between different request collections.
All of a sudden using a well known request (that is known to run successfully) is not successful. 
This is because the client is now sending some other request than the one specified by the user.

Restarting request, mac native app, mac, or clearing cache and cookies do not resolve the issue.
Only solution is to completely delete mac app, trash ~/Library/Postman folder redownload client, reinstall and resync.

I can certify that the request is right because by pressing "code" and copying the cURL version into a Terminal, the request works!

At this point I am loosing confidence in Postman being a tool of choice and confidence. This needs to work 100% of the time, otherwise we loose a lot of time debugging why our API is not working.. when really it's the tool that is not working!!!

**Comment by preethammavin** [comment]
@Mihai1706 that is weird, this should not happen. Do update to the latest version of the app, we work on continuously improving our product. 

If the issue occurs again, do send any error logs as that would help us to identify the core of the issue.

**Comment by kamalaknn** [comment]
Hey @Mihai1706 

We would need a bit more information to help fix the problem here. At this point, the issue does not have any specific information for us to reproduce and fix this.

I'm closing this issue now. If you're still seeing this on the latest version of Postman, feel free to reopen with more information to help us reproduce this.

Thanks
