### ISSUE TITLE
Navigation bar goes missing

### ISSUE THREAD

**Issue by andersoyvind** [a85/POSTMan-Chrome-Extension#4390]
## App Details:

```
Postman for Linux
Version 6.0.10
linux 4.15.12-1-ARCH / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:
I started using Postman recently, experienced it three times in a week.
 2. Expected behaviour
The bar    Authorization | Headers | Body | Pre-request Script | Tests
should be available all the time.
3. Actual behaviour
The bar mentioned in 2 go missing, and I don't find a way to get it back, except creating a new "job". See attachment below.
 4. Screenshot
![screenshot from 2018-03-27 09-08-55](https://user-images.githubusercontent.com/2064897/37951981-9b7631bc-319e-11e8-9986-99ca439389ff.png)

1. I create a get request, adding Oauth2 token to the header. 
2. I leave postman open between work days. 
3. The next day or the other, the bar goes missing. I do not know at what action/state it vanishes, though.

Workaround
As a workaround, I open a new tab, fetching a new token.

P.S.
In some way, this could be more a user error than a bug, I was thinking of posting this as a question instead, like "How do I get my bar back?", but in case it is a bug...

**Comment by a85** [comment]
I think the page has just scrolled down?

**Comment by andersoyvind** [comment]
No way! 
"P.S. In some way, this could be more a user error than a bug..." - HAHAHA!

Long live subtle scrollbars. Thanks!
