### ISSUE TITLE
Authorization (get new access token) helper - can't set resource field, Azure AD returns the wrong token audience

### ISSUE THREAD

**Issue by dominicusmento** [a85/POSTMan-Chrome-Extension#4391]
## App Details:

```
Postman for Windows
Version 6.0.10
win32 10.0.16299 / x64
```

## Issue Report:
 1. bug has always been there
 2. Expected behavior: availability to set the optional resource field in authorization helper -> oauth2 -> client credentials form, currently the field is not available
 3. Console logs: no console log needed, actually everything works as expected, only the auth endpoint gives the token with wrong audience because we can't define the resource parameter
 4. Screenshots (if applicable)
![Image of problem](https://p14.zdusercontent.com/attachment/555292/ArOZ3BUqmQoWdWaOmddRWrqU3?token=eyJhbGciOiJkaXIiLCJlbmMiOiJBMTI4Q0JDLUhTMjU2In0..xObpvQ_cTqrMDT0o4gUHqw.v5es8m49GIL44UV8azOqmiwFfngL7sn48LvvdOVM5dVaH2C9dfzd-RUxjYGw_yaZwrfRjwZnzGFr0SN9Xsvl6br6yEOQYHTrM9LXbkB3IGWFg8xoh7NIMrCN7bbt0MODiuo3T6NVF5yCvd_GQz-a1IE0e70bx8eixNTXxjJmYE9Chsphj7AOH6y6f5DzXUGTTs1MYbUgcIwg5P8UYi88wKNc-auN9qe7iajXzi_54SgWYqdAQBa2JkjOdX61aCqw6KvEsMLXNKJ31UoU00NIfA7cKRAKSJyc_FyJVKcLcDE.UbvapQDgxeYVP0Ygub4DrA)

## To reproduce:
When using Azure AD and trying to use for example Microsoft Partner Center SDK, you have to obtain the oauth2 token with client credentials grant type, but there is a problem because you can't set the resource parameter so the Azure AD gives you a valid token with audience (aud) parameter set to: "00000002-0000-0000-c000-000000000000" instead of the real resource which I need. Creating the authorization token request manually in postman and only adding the resource parameter on top of the initial request, gives me the valid and working token (with aud set to my resource parameter - https://graph.windows.net in my specific case) which I can then use in my other requests.

**Comment by kamalaknn** [comment]
Hi @tomidix 

Thanks for your feedback. I'm marking this as a feature request. We'll take a look at this when we revisit OAuth 2.

**Comment by mparker** [comment]
+1 for this feature
https://docs.microsoft.com/en-us/azure/active-directory/develop/v1-oauth2-client-creds-grant-flow#request-an-access-token
This is the auth scheme for MS Azure (which is based on AAD). Adding an Azure-specific auth type should be as simple as adding "resource" as a parameter name (or alternatively, allowing user-defined parameter names to be added to the existing "OAuth 2.0" UI). Granted, MS could add support for 'scope' instead of 'resource', but I know better than to ask them for that.

**Comment by ghost** [comment]
+1
Whould be very good for making Azure API request easier to generate!

**Comment by jkewley** [comment]
Have you tried using `https://login.microsoftonline.com/[tenant_id]/oauth2/token?resource=[application_id]` for the token url?

**Comment by ghost** [comment]
> 
> 
> Have you tried using `https://login.microsoftonline.com/[tenant_id]/oauth2/token?resource=[application_id]` for the token url?

Just tried. You obtain a token, but when using it this is the respone:

`{
    "error": {
        "code": "InvalidAuthenticationTokenAudience",
        "message": "The access token has been obtained for wrong audience or resource '00000002-0000-0000-c000-000000000000'. It should exactly match with one of the allowed audiences 'https://management.core.windows.net/','https://management.core.windows.net','https://management.azure.com/','https://management.azure.com'."
    }
}`

Tried both 
https://login.microsoftonline.com/[tenant_id]/oauth2/token?resource=https%3A%2F%2Fmanagement.azure.com%2F

and
https://login.microsoftonline.com/[tenant_id]/oauth2/token?resource=https://management.azure.com/

**Comment by LR4Discovery** [comment]
I just started experimenting with postman and services secured by Azure AD. I am running into exactly the same issue described above. I assume it is still not fixed. Anyone can suggest next best way to test secured services with Postman ? Thank you

**Comment by jkewley** [comment]
We took this approach. It uses a pre-request script in the collection to deliver the same thing:
https://lnx.azurewebsites.net/postman-pre-request-script-for-azure-rest-api-client-credential-grant/

**Comment by LR4Discovery** [comment]
Thank you @jkewley. I am trying to implement the solution and running into some pre-script issues. Anyway you know how i can troubleshoot the script itself. Also for this line - {key: "resource", value: "https://management.azure.com/"}, i assume i need to replace the URL value with ApplicationId of the resource from Azure AD. Am I correct on that ?

**Comment by LR4Discovery** [comment]
@jkewley, i found a postman console. i am trying to use that to examine errors. Anything else/better i can use ?

**Comment by jkewley** [comment]
It depends what you're trying to access. If you want a token for a specific resource in Azure, you would use the app uri for the registered app. If you want to access Azure ARM APIs you'd use https://management.azure.com/. Note that the App Uri is a url and you want that instead of the App ID which is a guid. Both are found on the settings>properties screen of the app registration blade

The token request says "I'm using this auth method (grant_type) with this user (client_id) and this password (client_secret) to request a token which will let me talk to this service (resource)". 

The error message in this thread indicates that the original request targeted the wrong service (resource) and the security layer in front of that service denied access based on the contents of a valid token.

Use jwt.io to validate the token response when you get it working and look at the aud value to see if it matches the app identifier of the resource you're trying to access.

**Comment by LR4Discovery** [comment]
@jkewley For resource, i am using the URL value in the App ID URI field. This value is generated for me by Azure AD during registration process. i can verify the token through jwt.io to confirm that the same value is stored in 'aud' and still getting 'The audience is invalid'. Anything you can think of to check for ?

**Comment by will-beta** [comment]
+1
Also wondering why the Microsoft use the `resource` instead of the standard field `scope` in OAuth2.

**Comment by ashfondu** [comment]
Had the same exact issue and was able to resolve using the following settings - essentially the resource needs to be in the body instead of as a parameter. see image for details.

![image](https://user-images.githubusercontent.com/34550337/58584632-8fc7d500-820b-11e9-9c15-1f4848c34d88.png)

**Comment by Ballzer0** [comment]
+1 this would still be an awesome feature!

**Comment by zaha** [comment]
+1 from me too, would be really useful for working with azure!

**Comment by DaveC-PCL** [comment]
+1 please implement this soon.  I was struggling with this thinking I was doing something wrong, then I found this post and am relieved that is we are not able to set the resource value.  For the time being I can setup a separate request setup as ashfondu mentioned.

**Comment by chrisdreams13** [comment]
+1 Any chance to get it for x-mas???

**Comment by fbacker** [comment]
+1

**Comment by kamesh95** [comment]
+1 Following

**Comment by dominicusmento** [comment]
C'mon people this is opened more than two years and it is about one field.. We have to use some stupid workarounds...

**Comment by nemo-chevalier** [comment]
Just tried and found nothing changed in OAuth 2.0 authorization:
![image](https://user-images.githubusercontent.com/24557606/81652031-b7886b00-9465-11ea-8d15-9ae41b46aaa6.png)

Now I can only apply the workaround mentioned by @ashfondu and manually copy the AAD token for other requests...please consider add custom properties like "resource"...

**Comment by iyerusad** [comment]
Spent too many years(!) thinking I was doing something wrong here, finally spent some time to debug the postman produced token and realized same issue (scope parameter =/= resource)

Workaround from @jkewley 
--
> https://lnx.azurewebsites.net/postman-pre-request-script-for-azure-rest-api-client-credential-grant/

Folder level Auth:
---
**Auth:** None/No Auth
**Pre-Request Script:**
```js
var client_id = "" // or use: pm.environment.get("client_id");
var client_secret = "" // or use: pm.environment.get("client_secret");
var tenant = "" // or use: pm.environment.get("tenant")
var resource = "" // or use: pm.environment.get("resource")

pm.sendRequest({
    url: 'https://login.microsoftonline.com/' + tenant + '/oauth2/token',
    method: 'POST',
    header: {
        'Content-Type': 'multipart/form-data',
          },
      body: {
          mode: 'formdata',
          formdata: [
            {key: "client_id", value: client_id},
            {key: "client_secret", value: client_secret},
            {key: "resource", value: resource},
            {key: "grant_type", value: "client_credentials"},
            
        ]
      }
},  function(err, response) {
  const jsonResponse = response.json();
  pm.request.headers.add(`Authorization: Bearer ${jsonResponse.access_token}`);
  // or use pm.environment.set("access_token", jsonResponse.access_token);
});
```
Scripting ref: https://learning.postman.com/docs/postman/scripts/postman-sandbox-api-reference/

Requests within the folder can then use Auth setting of "Inherit auth from parent" (default).

**Comment by sikemullivan** [comment]
> Have you tried using `https://login.microsoftonline.com/[tenant_id]/oauth2/token?resource=[application_id]` for the token url?

That worked for me. Thanks!

**Comment by jongio** [comment]
FYI.  I have a blog and walkthrough updated for 2021.

Azure REST APIs with Postman
https://aka.ms/azurerestblog
https://aka.ms/azurerestvideo



I believe the problem is in the code that calls the /token endpoint.  As the client_id and client_secret are not included in the body of the request:

This shows what is sent in the body, even though I have client_id and client_secret set in the OAuth Postman interface

![image](https://user-images.githubusercontent.com/2163001/107891475-bfcd7500-6ed3-11eb-85d4-6126f8f561af.png)

**Comment by dsotrean** [comment]
Had the same issue recently. I had to generate the token with the parameters: grant_type, client_id, client_secret, scope, resource.
When I excluded <resource> parameter, it generated a default value for resource: 00000002-0000-0000-c000-000000000000
By setting the <resource> to "https://management.azure.com/", the generated token was valid to be used in other API calls.
![2021_04_01_21_24_49_Postman](https://user-images.githubusercontent.com/68228355/113344456-63ae9b00-9331-11eb-973e-fa1963e0240e.png)

**Comment by giridharvc7** [comment]
We've added an option to specify audience and resource. You can give this a try by updating postman to the latest version or by using the web app . Let us know what you think! 
![image](https://user-images.githubusercontent.com/1040583/122542670-9753b400-d048-11eb-975c-7cc7554086d2.png)

**Comment by schindld** [comment]
> We've added an option to specify audience and **resource**. You can give this a try by updating postman to the latest version or by using the web app . 

@giridharvc7 Did the resource field get removed in a recent release? I'm using the latest, and don't see it anywhere. And now I can't get a valid access token from ADFS.

![image](https://user-images.githubusercontent.com/1659632/137343419-f6583679-71c5-47cc-8ace-5c47415a7c6a.png)

![image](https://user-images.githubusercontent.com/1659632/137343543-c8a0979d-d181-4af5-95de-f7310c3adad3.png)

*** Edit ***
I see that the Resource field disappears when using the Grant Type = Password Credentials.
Can this issue  be re-opened?

**Comment by glaszczkowski-unicef** [comment]
Resource field does not exist when grant type is "Password credentials"
