### ISSUE TITLE
Requests occasionally reorder within a folder when duplicating a request

### ISSUE THREAD

**Issue by mr-newell** [a85/POSTMan-Chrome-Extension#4393]
## App Details:

```
Postman for Mac
Version 6.0.10
OS X 17.3.0 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:
**New as of 6.0.10**
 2. Expected behaviour:
**Requests never reorder themselves**

Unfortunately, I haven't found a way to reliably reproduce the issue, but it's happened to me twice today. Both times, my folder looked like this:
- POST
- DELETE
- POST
- DELETE

After duplicating the first request, they looked like this:
- POST
- POST
- DELETE
- DELETE

**Comment by kamalaknn** [comment]
@mr-newell We had some issues that could lead to request order getting changed after restarting the app. We've pushed the fix to our Sync servers. 

Could you log out and log in once and check if you continue to face the issue?

**Comment by mr-newell** [comment]
I've done what you requested; I'll close this by the end of the week if I notice it has stopped.

**Comment by kamalaknn** [comment]
I'm closing this issue as this has been fixed. Feel free to reopen the issue if you're facing similar issues again.
