### ISSUE TITLE
How do I send request as a prerequesits for particular request in postmen

### ISSUE THREAD

**Issue by Nuwangik** [a85/POSTMan-Chrome-Extension#4395]
I want send request as a prerequesits for perticular request. Eg:- Lets say I want to test Post Login end point. In order to do that I need to register user which did from different API call.. So for one request how can I script? How do I do this?

**Comment by sivcan** [comment]
Hi @Nuwangik - This repository is being maintained only for feature requests and bug reports.
Kindly post your query on the [Postman Community](http://community.getpostman.com/) 

Posting this will not only engage more people in solving your problem but will also help more people who're looking for a similar solution.

Thanks for contributing!

**Comment by Nuwangik** [comment]
Thanks  @sivcan . I'll address this on Postmen Community.

**Comment by sivcan** [comment]
@Nuwangik Postman* 😅
