### ISSUE TITLE
POST Request not sent if there is key named "constructor" in form-data

### ISSUE THREAD

**Issue by ahmad-511** [a85/POSTMan-Chrome-Extension#4397]
## App Details:
```
Postman for Windows
Version 6.0.10
win32 10.0.16299 / x64
```

## Issue Report:
1. I just noticed this today
2. I must be able to send POST request that has a form-data key named "constructor"
3. Nothing in the console is logged

Steps to reproduce the problem
1. Create a new POST request using whatever URL
2. Select form-data option
3. Add a new body key/value and set key name as "constructor" without quotes and assign any value to it
4. Click send

Notes
1. The request never made it to the server
2. I opened Postman console and there is no request logged there
3. After request time is out Post man shows "Could not get any response" in the result section
4. However, using x-www-form-urlencoded instead it works

**Comment by kamalaknn** [comment]
Thanks for reporting this. We will work on a fix and update the thread here.

**Comment by kunagpal** [comment]
Hey @ahmad-511, thanks again for reporting this. A fix for this bug is being worked on here: https://github.com/postmanlabs/postman-runtime/pull/553. We'll update this thread when it becomes generally available in the Postman app. 😄

**Comment by ahmad-511** [comment]
Great 👍

**Comment by kunagpal** [comment]
@ahmad-511 This has been fixed and is generally available, could you try it out in the latest stable release of the app?

**Comment by ahmad-511** [comment]
Working as a charm

Well done
