### ISSUE TITLE
Saved requests (in collection) not loading response but unsaved requests do

### ISSUE THREAD

**Issue by SchizoAA** [a85/POSTMan-Chrome-Extension#4399]
## App Details:

```
Postman for Windows
Version 6.0.10
win32 10.0.10586 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there: Recently
 2. Expected behaviour: Saved and unsaved requests/tests should run in the same amount of time and display response information and body correctly in Postman UI.
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 4. Screenshots (if applicable)
UNSAVED Request result:
![postmanbug_unsaved](https://user-images.githubusercontent.com/10621569/38052936-e8b95976-328f-11e8-9623-af782cbb2697.png)

SAVED Request result:
![postmanbug_saved](https://user-images.githubusercontent.com/10621569/38052939-eb82705c-328f-11e8-9351-1d0154e901d7.png)

To reproduce: 
1. Start with an unsaved (not in a collection) request that generates a large json response with minimal tests. ~ 5MB. Open the Console to view the logs when you run.
2. Run the request and note the time it takes for the response body to populate. Note that the response body and all info are displayed properly in the Response section on the request.
3. Save the request to a collection.
4. Run the same request again now that it is saved. Time the response.
5. Note that the console shows the request and response info. It does not show the response data, as it is over 1MB. Also note that the response section of the request is still showing 'Loading...' even though it appears that the response has been received.

**Comment by kamalaknn** [comment]
Hi @SchizoAA 

Could you open you DevTools (View -> Developer -> Show DevTools (Current VIew)) and send us the error logs if any?

**Comment by numaanashraf** [comment]
@SchizoAA We have made various improvements to our response rendering flow that should prevent issues like this. Please update to the latest version and re-open if you are still facing this issue.
