### ISSUE TITLE
I am using Postman to monitor a collection but each time, I am getting this error in the Console Error: getaddrinfo ENOTFOUND

### ISSUE THREAD

**Issue by sagarsidana** [a85/POSTMan-Chrome-Extension#4400]
## App Details:

```
Postman for Mac
Version 4.11.0
OS X 16.4.0 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:
 2. Expected behaviour:
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 4. Screenshots (if applicable)

**Comment by sagarsidana** [comment]
I am using Postman to monitor a collection and each time the monitor runs and throws an error message in the console: Error: getaddrinfo ENOTFOUND

**Comment by kamalaknn** [comment]
Hey @sagarsidana 

A `getaddrinfo ENOTFOUND` usually means a DNS error. Could you check your Proxy configuration?

I can notice that you are on a really old version of Postman. Could you download the latest Postman app from the website - https://www.getpostman.com/apps?

I'm closing this as this is not a bug with the Postman App itself.

Feel free to visit our [community discussion forum](https://community.getpostman.com/) for more help.

**Comment by suntoshakula** [comment]
may be if this link could help.
https://github.com/postmanlabs/postman-app-support/issues/6001#issuecomment-1155377029

**Comment by Sbrjt** [comment]
I was trying to fetch a URL hosted on Railway. It worked in the browser, but Postman returned: `Error: getaddrinfo ENOTFOUND`

Testing via terminal with ping produced the same DNS error. 

So I [changed](https://developers.cloudflare.com/1.1.1.1/setup/windows/) my DNS server and postman started working.
