### ISSUE TITLE
testing date value in postman

### ISSUE THREAD

**Issue by astrowalker2013** [a85/POSTMan-Chrome-Extension#4402]
I try to compare 2 dates in postman and give the status are 

 my date i want  to compare are : 2018-03-14T09:51:42.000Z"

need to converte the date in unix time how to do that.

Thanks in advence

**Comment by sivcan** [comment]
Hi @astrowalker2013 - This [answer on Stackoverflow](stackoverflow.com/questions/48314782/how-to-compare-a-string-to-a-date-in-postman-test/48315230#48315230) will help you.

Note: This repository is being maintained only for feature requests and bug reports.
For any further queries related to postman kindly visit the [Postman Community](https://community.getpostman.com/latest)

Thanks

**Comment by astrowalker2013** [comment]
Ok 
thanks a lot how ever 
the link are in 404 error

**Comment by abhijitkane** [comment]
@astrowalker2013 Updated the link - thanks!

**Comment by astrowalker2013** [comment]
i find the solution about .

i used the methode parse of Date https://www.w3schools.com/jsref/jsref_parse.asp
to convert the string time in unix time to calculate the value

**Comment by sivcan** [comment]
@astrowalker2013 - Yes, correct.
Not sure why the Stackoverflow link was giving a 404.

https://stackoverflow.com/questions/48314782/how-to-compare-a-string-to-a-date-in-postman-test/48315230#48315230
