### ISSUE TITLE
Can't use the mouse to select part of a request name

### ISSUE THREAD

**Issue by mr-newell** [a85/POSTMan-Chrome-Extension#4403]
## App Details:

```
Postman for Mac
Version 6.0.10
OS X 17.3.0 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:
**Always been there**
 2. Expected behaviour:
**The mouse can be used to select part of a request name**

On any request, right-click → 'Rename' → Attempt to select a specific part of the text. Instead of the text being selected, the request is dragged, oftentimes leading to the frustrating experience of accidentally moving a request into some unknown folder.

**Comment by harryi3t** [comment]
@mr-newell Thanks for reporting this to us. We will update the thread once the fix is out.

**Comment by prashantagarwal** [comment]
Duplicate of #2940
