### ISSUE TITLE
Failing to run native app on ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by saurabhgupta1233** [a85/POSTMan-Chrome-Extension#4406]
Failing to run the native app on Ubuntu 16.04 LTS - 
Fails on the loading screen

## App Details: (Copied from chrome app as not able to run the native app)
Postman for Chrome 
Version 5.5.2
linux / x86-64
Chrome 62.0.3202.94

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there: Recently (never tried the native app before)
 2. Expected behavior: Able to open app
 3. Console logs : 
Right now I am getting an error when running from the command line using ./Postamn command -
Shared window not present!
 4. Screenshots (if applicable) Was able to reproduce this issue multiple time previously right now I am getting a new error.

**Comment by harryi3t** [comment]
This issue is already being tracked here https://github.com/postmanlabs/postman-app-support/issues/4359
Please subscribe/upvote the original issue for the updates.
