### ISSUE TITLE
Enhancement Request: Allow Response Bodies to Return More than 1000 Rows

### ISSUE THREAD

**Issue by harrisonkrat** [a85/POSTMan-Chrome-Extension#4408]
## App Details:

```
Postman for Mac
Version 6.0.10 (6.0.10)
macOS X Sierra 10.12.6 (16G1114)
```

## Issue Report:
 1. I have encountered this bug for the last several months in a GET request.
 2. Expected behaviour: I can return the full response body from my API endpoint, or I can change a setting to allow my responses to have more records. If such a setting existed, I can find how to change it in your docs.
 3. Neither the app nor the console log returns any kind of error or indication that a max response body size has been reached. However I am expecting >5000 records from my API (since I can verify this via our native product UI). When I query my API endpoint for a response body in either CSV or JSON format, Postman caps the response body at 1000 records.

Make any GET request where you know the response body should return more than 1000 records. The Postman app response and console log response body only show 1000 records. There is no indication the response body has been capped or truncated. There is no UI setting indicating this. There is no discussion of a max response body size in the online docs.

It appears [this issue](https://github.com/postmanlabs/postman-app-support/issues/3589) may have been solved with an increase in the character size of a JSON response to 5,000,000 characters. My response body of 1000 rows does have 4,592,353 characters including spaces. However I'd prefer to be able to pull my full response body, or have some way of knowing the response has been capped, and change the setting, so I can accept the performance ramifications myself.

**Comment by harryi3t** [comment]
@harrisonkrat I have marked this as a feature request.

**Comment by a85** [comment]
We are making some fundamental improvements to Postman's response rendering including using the Monaco editor for better memory optimization and rendering speeds. You can try out these updates in the Canary channel here: https://www.getpostman.com/downloads/canary

<img width="1790" alt="Screenshot 2019-06-12 12 19 53" src="https://user-images.githubusercontent.com/653409/59379813-72ffc700-8d0c-11e9-9da4-5c9ce0492dc4.png">

You can test it out with an API that we have created on the Postman Echo service. Examples here: https://documenter.getpostman.com/view/55577/S1ZudWWm?version=latest

**Comment by codenirvana** [comment]
As mentioned in https://github.com/postmanlabs/postman-app-support/issues/4408#issuecomment-501420609, we've made significant improvements to handle large responses and this has been fixed in the latest version of the Postman app.
