### ISSUE TITLE
Can't see all test results in collection runner

### ISSUE THREAD

**Issue by ghost** [a85/POSTMan-Chrome-Extension#4410]
Hi,
I am seeing something weird in Postman. I have some post requests that should return in the response body an array of documents. And I have some tests for these documents. In total there are 15 tests per document. 

These are my tests:
```js
var apiResponse = JSON.parse(responseBody);

pm.test("Status code is 200", function () {
    pm.response.to.have.status(200);
});

for(var doc in apiResponse) {
    pm.test(`Document ${apiResponse[doc].clientOrderId.value} doesn't have an error`, _ => {
        pm.expect(apiResponse[doc].errorCode).to.eql(null);    
    });
    for(var key in apiResponse[doc]) {
        if (typeof apiResponse[doc][key] === 'object' && apiResponse[doc][key] !== null){
            pm.test(`Document property ${key} doesn't have an error`, _ => {
                pm.expect(apiResponse[doc][key].errorCode).to.eql(null);    
            });
        }
    }
}
```

I run the requests in the collection runner and I see the full test results for the first document in the response array. But for subsequent documents I only see the test result for this test pm.test(`Document ${apiResponse[doc].clientOrderId.value} doesn't have an error`)

At the top of the collection runner window I see the correct number of tests that have passed and failed. Also I can see the failed asserts in the developer tools but not in the main window of the collection runner. 

Does postman only display a limited amount of tests per request? If not is this a bug? Is there something i can do to see all tests in the main collection runner window?

Postman for Windows
Version 6.0.10
win32 10.0.16299 / x64

**Comment by harryi3t** [comment]
@dani-oprean Can you share a collection to reproduce this? I tried this using hardcoded data and all the tests runs fine.
Check this sample collection that I used for testing
[![Run in Postman](https://run.pstmn.io/button.svg)](https://app.getpostman.com/run-collection/39a18f08de45474e2144)

**Comment by ghost** [comment]
@harryi3t I attached a collection for testing. Variables were not replaced as I can't share that information.  

But, as I said before the problem is not that the tests don't run. They do. But not ALL results are displayed in the collection runner window. The same happens when I run this collection in newman in the HTML report. The cli report is complete. All test results are there. Not the html report. 

The collection runner window and the html report from newman don't display results for ALL tests. That is the problem.

[temp.postman_collection.json.zip](https://github.com/postmanlabs/postman-app-support/files/1880172/temp.postman_collection.json.zip)

**Comment by harryi3t** [comment]
@dani-oprean I cannot use the collection the you shared since it does not have a valid end-point (coz of variables)
But if you run the collection I have shared with hard-coded data, you will see that all test results are displayed
<img width="542" alt="image" src="https://user-images.githubusercontent.com/5207331/38377211-08225e78-3918-11e8-9e30-2c89e00f5586.png">
