### ISSUE TITLE
In Postman saving response XML using Test script. 

### ISSUE THREAD

**Issue by pjson235** [a85/POSTMan-Chrome-Extension#4411]
I started using Postman from last couple of days and I got struck with the below issue.

I have a GET request XML with parameters (no request body) which I have parameterrized and able to send the request with multiple data sets using csv file (using collection runner). But I need to save the responses for each and every request using script (Test, not manually). The response is in XML format and I need to save the XML to local drive. Is there any way in Postman that we can achieve this? Appreciate your directions/suggestions.

**Comment by harryi3t** [comment]
@pjson235 Unfortunately, as of now this is not supported in Postman. 
But as a workaround you can write a simple node server which when called writes/appends the request body to a file, and the from the test script call that endpoint.

**Comment by harryi3t** [comment]
@pjson235 I found a good blog post regarding this
http://blog.getpostman.com/2017/09/01/write-to-your-local-file-system-using-a-postman-collection/
