### ISSUE TITLE
Ability to alter request headers in pre-request script?

### ISSUE THREAD

**Issue by BlacKCaT27** [a85/POSTMan-Chrome-Extension#4413]
## App Details:

```
Postman for Windows
Version 6.0.9
win32 10.0.16299 / x64
```

I'm trying to configure a Collection for testing an endpoint which (mostly) supports OAuth 2.0. Thus far, I've successfully obtained tokens via their API through the Authorization tools for Collections in PM.

Unfortunately, the endpoint in question (which I have no control over), doesn't properly support the Authorization header. Instead, they've opted to expect the token value as the value of their own custom-defined header, say something like "myapitoken". 

Thus far, I don't see any way in Postman to change the name of the header to which the access token is applied, nor do I see any way to obtain the token as a variable.

I tried altering the request in the Pre-request scripts, but as I've since learned from the documentation, the request object is read-only. Using pm.request.addHeader() does, in fact, let me add a header to the request (at least the copy of the object logged with `console.log(pm.request)`, but the value doesn't persist and the header is completely ignored when the actual request is generated and sent.

Is there any way to manage this other than manually hard-coding tokens to this custom header key in every request to this API?

Thanks

**Comment by harryi3t** [comment]
@BlacKCaT27 

> Is there any way to manage this other than manually hard-coding tokens to this custom header key in every request to this API?

Yes! Use [variables](https://www.getpostman.com/docs/v6/postman/environments_and_globals/variables)

You can use a variable for the header key and another variable for the value
![image](https://user-images.githubusercontent.com/5207331/38365606-90a4e89c-38fa-11e8-90d2-78a2eaa1361b.png)

If this header key is coming from some other request, then you can simply set this variable in the test script of that request.
```js
pm.variables.set('key', pm.response.json().someValue);
```

I have made a sample collection to demonstrate this
[![Run in Postman](https://run.pstmn.io/button.svg)](https://app.getpostman.com/run-collection/3d7544311a536e356f3b)

Let me know if you need more help.

**Comment by BlacKCaT27** [comment]
This doesn't directly answer my question though. I know how to use variables in all the various fields; the problem is, in my case, I'm trying to access the token provided through the authentication system in Postman. From what I can tell, no token variable is exported for use such as how you're suggesting. The closest I could come would be to use the authentication system to obtain a token, then copy it into a variable within that environment for use on the requests. I suppose that works, but it's still more manual than I'd prefer, since I've have to go back in and update the variable value whenever the token expired. 

If there is some reserved variable name that the authentication token is stored in that I can use, that would be perfect. Does something like that exist?

**Comment by harryi3t** [comment]
@BlacKCaT27 My bad, didn't fully understand the context.
Since Postman has to be spec compliant, the header key is hard-coded to be `Authoriazation`.
But using `pm api` you can access the current auth parameters.

Try this workaround

![image](https://user-images.githubusercontent.com/5207331/38370396-a4bb60b0-3907-11e8-9636-1af7987e701d.png)
![image](https://user-images.githubusercontent.com/5207331/38370426-b76a9eec-3907-11e8-814a-878bf39407e9.png)
![postman](https://user-images.githubusercontent.com/5207331/38370512-e4a81d58-3907-11e8-8893-db0a0153704d.png)

Complete collection here
[![Run in Postman](https://run.pstmn.io/button.svg)](https://app.getpostman.com/run-collection/3d7544311a536e356f3b)

Hope this helps

**Comment by BlacKCaT27** [comment]
Perfect! Exactly what I needed, thanks!

**Comment by BlacKCaT27** [comment]
One final thing: 

It appears this solution only works on a per-request basis. I'm not able to access the auth token using the Authorization and Pre-request Scripts pages of an Environment. It would be great to have this option exposed at that level.

**Comment by harryi3t** [comment]
@BlacKCaT27 There's already an open feature request for this here https://github.com/postmanlabs/postman-app-support/issues/4396

**Comment by andini28** [comment]
![untitlednn](https://user-images.githubusercontent.com/42520676/44313471-be6e7f00-a433-11e8-9fd4-eb7ebf6d6e06.png)
how to set access Token in the Authorization field in the header key with test script on postman
![untitled](https://user-images.githubusercontent.com/42520676/44313502-23c27000-a434-11e8-80ca-a187cccf5883.png)

**Comment by harryi3t** [comment]
@andini28 You can use a variable in the authorization field
![postman 2018-08-20 14-07-20](https://user-images.githubusercontent.com/5207331/44329559-6317ad80-a482-11e8-8273-e38a48b23d41.png)

And then set the value for that variable in the pre-request script
```js
pm.variables.set('token', 'YOUR-VALUE-HERE')
```

**Comment by jayarjo** [comment]
But what if one wants to add multiple headers (exact number is not known beforehand)?

**Comment by Lambeaux** [comment]
Indeed ☝️ when you have hundreds of requests across multiple collections, and you need to toggle N headers based on the context (for instance, CSRF protection) there seems to be no good solution short of exporting everything, programmatically modifying the JSON, and re-importing. Definitely not ideal. 

You simply cannot preempt all the variables that you might need ahead of time.
