### ISSUE TITLE
Can't send data with the use of POST request from Java to Laravel

### ISSUE THREAD

**Issue by Florence2016** [a85/POSTMan-Chrome-Extension#4417]
URL url = new URL("http://....../api/......./log");
        Map<String, Object> params = new LinkedHashMap<>();
        params.put("accessid", "asasasasas");
        params.put("uid", "sasasasa");
        params.put("uname", "asasaa");
        params.put("agent", "sasasasasaddd");
        params.put("query", "adewewewe");
        StringBuilder postData = new StringBuilder();
        for (Map.Entry<String, Object> param : params.entrySet()) {
            if (postData.length() != 0) postData.append('&');
            postData.append(URLEncoder.encode(param.getKey(), "UTF-8"));
            postData.append('=');
            postData.append(URLEncoder.encode(String.valueOf(param.getValue()), "UTF-8"));
        }
        byte[] postDataBytes = postData.toString().getBytes("UTF-8");
        HttpURLConnection conn = (HttpURLConnection) url.openConnection();
        conn.setRequestMethod("POST");
        //conn.setRequestProperty("Content-Type", "application/x-www-form-urlencoded");
        conn.setRequestProperty("Content-Length", String.valueOf(postDataBytes.length));
        conn.setDoOutput(true);
        conn.getOutputStream().write(postDataBytes);

        System.out.println("\nSending request to URL : " + url);
        System.out.println("Response Code : " + conn.getResponseCode());
        System.out.println("Response Message : " + conn.getResponseMessage());
        Reader in = new BufferedReader(new InputStreamReader(conn.getInputStream(), "UTF-8"));
        StringBuilder data = new StringBuilder();
        for (int c; (c = in.read()) >= 0; ) {
            data.append((char) c);
        }
        String intentData = data.toString();
        System.out.println(intentData);

    }

**Comment by sivcan** [comment]
Is this an issue regarding Postman app ? 
This repo is only being maintained to report a bug / feature requests for the Postman app.
If you've any how-to questions then kindly check out our [Community](community.getpostman.com/latest) 

If the issue is regarding the postman app then kindly provide the app details (Settings > About) 
and also the steps to reproduce this.

I'll reopen this issue if it exists.
