### ISSUE TITLE
Unable to send a string in header to a URL

### ISSUE THREAD

**Issue by blueelvis** [a85/POSTMan-Chrome-Extension#4422]
## App Details:
```
Postman for Windows
Version 6.0.10
win32 10.0.16299 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there: Not sure
 2. Expected behaviour: It should send the request to the API Route
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app): 
```
POST /personatorservice/transactQuery/person
content-type: application/json
appkey: ⅛⅜⅝⅞
userkey: ⅛⅜⅝⅞
cache-control: no-cache
postman-token: dbf72c33-37f8-430e-af69-6fc3dd0e9299
{"persons" :[{"FirstName":"⅛⅜⅝⅞","LastName":"⅛⅜⅝⅞","Zip":"⅛⅜⅝⅞","Originator":["⅛⅜⅝⅞","⅛⅜⅝⅞"]}]}
```
 4. Screenshots (if applicable)
![image](https://user-images.githubusercontent.com/6985763/38420708-57fe9056-39c2-11e8-8d50-1eb67a0bc4c0.png)

**Comment by SamvelRaja** [comment]
@blueelvis  I could see that you have invalid characters in headers. Additionally,
 I would recommend you to open Postman console (View -> Show Postman Console ) before sending the request.
![capture](https://user-images.githubusercontent.com/5114052/42149149-aa185e70-7df2-11e8-8ff7-399b5f65293a.PNG)

**Comment by numaanashraf** [comment]
Thanks for reporting this. We are tracking this at a similar issue #4485.
