### ISSUE TITLE
App converts arabic to random strings after a while

### ISSUE THREAD

**Issue by AbdelrahmanHafez** [a85/POSTMan-Chrome-Extension#4427]
## App Details:
```
Postman for Windows
Version 6.0.10
win32 10.0.16299 / x64
```

So, I've been using postman for a while now, and one problem that I noticed a couple of months ago was that the collection couldn't keep Arabic strings as is, for some reason it gets converted to a random string instead.
It stays as Arabic for a couple of days (weeks?), then this happens.

![screenshot_605](https://user-images.githubusercontent.com/19984935/38468493-0e70f286-3b47-11e8-8bee-6ac01250ab2c.jpg)

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there: It's been always there
 2. Expected behaviour: To keep the Arabic string as it is.

I'd be more than happy to provide any information needed to find a solution to this issue.

**Comment by harryi3t** [comment]
@AbdelrahmanHafez  I tried with a sample server that sends Arabic text. Postman was able to render it correctly
<img width="622" alt="image" src="https://user-images.githubusercontent.com/5207331/42092471-b6cf3022-7bc6-11e8-9b16-c23e6bd870d9.png">

Also, when you say

> It stays as Arabic for a couple of days (weeks?)

I find this very unlikely to be a bug on Postman. Whatever the server sends we show that. If it works for days/weeks and then does not, maybe the server is not sending the right data.


Sample code for testing
```js
const express = require('express')
const app = express()
const port = '3333'


app.get('/', (req, res) => res.send('Hello World!'))
app.get('/arabic', (req, res) => res.send({
  language: 'arabic',
  text: 'هذا نموذج نص. من فضلك لا تأخذ الأمر على محمل الجد'
}))

app.listen(port, () => console.log(`Example app listening on port ${port}!`))
```

**Comment by AbdelrahmanHafez** [comment]
I think there's a misunderstanding.

This is not a rendering issue, when a server sends a response to postman, the response is rendered correctly.

The issue is that the HTTP request's JSON body, when I save it on the postman's collection, the body (which is saved on the postman's servers, I suppose) changes Arabic to these random strings.

**Comment by harryi3t** [comment]
@AbdelrahmanHafez I am sorry for misunderstanding the issue.
Here's what I tried to reproduce the issue.
1. Save a request with arabic contents in the body and let it sync with Postman server
2. Sign-out. This will delete all data from the local system
3. Sign-in back. This will pull the data from Postman servers.

After these steps, I am still able to see the characters properly. Let me know if I missed something.

**Comment by AbdelrahmanHafez** [comment]
You did not.

This alone doesn't reproduce the issue, it usually happened a couple of weeks after saving, I just checked the collection and I found things that I saved months ago haven't changed, so I guess it's fixed. Will comment here if it reoccurs.

**Comment by harryi3t** [comment]
For any user landing on this page in future, around 6 months back we migrated our database to use Unicode characters.
For any new collection/request, this should not happen anymore.
