### ISSUE TITLE
Possibility to JSON Response validation based on a CSV data

### ISSUE THREAD

**Issue by rakeshk1987** [a85/POSTMan-Chrome-Extension#4428]
I have a REST service which will give a JSON response as below

{
"id": 1,
"first_name": "George",
"last_name": "Bluth",
"avatar": "Test1"
},

{
"id": 2,
"first_name": "Janet",
"last_name": "Weaver",
"avatar": "Test2"
},

{
"id": 3,
"first_name": "Emma",
"last_name": "Wong",
"avatar": "Test3"
}

I want to compare these response against a SQL/Oracle DB to check the data is coming correctly (Data from the DB is extracted to a CSV file that is the base lined data)

My questions: 
 - Is there any way to export the response body into a CSV format as an automated way? - so that i can compare both CSVs 
 - Any way to read the data cell by cell from the CSV file to go through each JSON array in the Response body for the validation
 - Please suggest a proper way to do this if the above points cannot be done. 

Thanks in Advance.

**Comment by kamalaknn** [comment]
Hi @rakeshk1987 

We keep the GitHub issue tracker for bug reports and feature requests for Postman. You will be able to find help in our [community forum](https://community.getpostman.com/) for questions related to using the Postman app.

Thanks for understanding.
