### ISSUE TITLE
HTTP OPTIONS request with automatic follow-up GET request only shows one request in Postman

### ISSUE THREAD

**Issue by desdoades** [a85/POSTMan-Chrome-Extension#4431]
Postman for Windows
Version 6.0.10
win32 10.0.16299 / x64

When using the HTTP OPTIONS request method in Postman it automatically executes the GET when the OPTIONS was successful. However the GET is not recorded in the history and I can nowhere see that it was executed.

 1. Did you encounter this recently, or has this bug always been there:
-Unsure, this is the first version of Postman I am using
 2. Expected behaviour:
-The history should show two queries

**Comment by harryi3t** [comment]
@desdoades I tested with a proxy in between and it showed only 1 request.
<img width="596" alt="image" src="https://user-images.githubusercontent.com/5207331/42092192-9cf32cfe-7bc5-11e8-9ca3-afc3721efb76.png">

I think there might be a redirection on the `OPTION` endpoint. Can you verify this by __turning off__ the 
`automatically follow redirects` setting
<img width="359" alt="postman" src="https://user-images.githubusercontent.com/5207331/42093996-ea7ef01a-7bcb-11e8-8ac6-c3db8880b2a4.png">

After turning it off what is the status code that you get? Can you share a screenshot of that?

**Comment by desdoades** [comment]
Currently I use:
Postman for Windows
Version 6.1.4
win32 10.0.17134 / x64

To set the context: I have a server which runs on ASP.Net Core 2.1 Kestrel with CORS enabled and a sample controller method which has both attributes, [HttpGet] and [HttpOptions]. The contoller method is supposed to return a sample pdf.

I query this server in two ways:

1. via a website which runs on another domain, therefore has to use CORS via an HTTP OPTIONS. In this case always two HTTP requests are sent, first OPTIONS which answers with 204 then a followup GET which answers with 200 delivering the pdf.

2. via Postman with a HTTP OPTIONS request. Contrary to what I said in my opening post, my server only gets this single OPTIONS request. Depending on the headers I send with the request two things happen:
    a) with no headers the HTTP OPTIONS returns with 200 and the pdf file in it
    b) when mimicing the headers in the browser ("Origin" and "Access-Control-Request-Method" are essential) then the answer is 204 with no pdf file in it.
The behaviour in a) and b) has to be caused by ASP.Net Core.

Whats worth mentioning though is that the Postman setting "Automatically follow redirects" seems not to change anything about this behaviour, meaning with Postman I never get the pdf file in an automatic followup HTTP GET request.

**Comment by numaanashraf** [comment]
`OPTIONS` is not supposed to be redirected to `GET` as per HTTP spec. In browsers, when you request a cross-origin GET endpoint, the browser would do an implicit OPTIONS pre-flight request as detailed here (https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS), before doing the `GET` call. Postman doesn't enforce CORS and by design doesn't do pre-flight requests.
