### ISSUE TITLE
postman app not work when sign in with google account

### ISSUE THREAD

**Issue by yali2015** [a85/POSTMan-Chrome-Extension#4432]
Hi，
 App Details:

Postman for Mac
Version 6.0.10
OS X 10.12.6

postman app can not work when I sign in with google account, the screenshot as follows:
![image](https://user-images.githubusercontent.com/15867526/38533035-ff2a0e7a-3ca9-11e8-9342-279280cb8c06.png)

**Comment by sdnts** [comment]
Hi @yali2015, Is this still happening? We had some issues with services yesterday, this should be working now. Please let me know if you're still unable to sign in, and I'll reopen.

**Comment by yali2015** [comment]
Hi @madebysid I have try it again, but it's still not work like above screenshot.

**Comment by yali2015** [comment]
@madebysid HI can you resolve it as soon as possible?

**Comment by preethammavin** [comment]
@yali2015 can you check if it's still happening, if yes do write to us at help@getpostman.com to sort this out.

**Comment by yali2015** [comment]
@preethammavin I have try it just now. It can work when I sign in with google account finally.
Thanks!

**Comment by abigailrose** [comment]
I have this same issue the first trying to associate my Google account with Postman. It leaves me on a dead screen as shown above. However, if I exit that window, return to the app, and try to "Log in with Google", it verifies successfully.

**Comment by numaanashraf** [comment]
@abigailrose @yali2015 Are you still facing this issue with the latest version of Postman (v6.1.4)?

**Comment by SamvelRaja** [comment]
Closing this as this is fixed from our end. Feel free to re-open it if you face it again.
