### ISSUE TITLE
When Bulk Edit was clicked, Description didn't follow Key and Value. （Postman v6.0.10）

### ISSUE THREAD

**Issue by zhangbin1991** [a85/POSTMan-Chrome-Extension#4433]
## App Details:
Postman for Win7
Version Postman v6.0.10
Windows7 ultimate 64 bit
```

## Issue Report:
 1. When Bulk Edit was clicked, Description didn't follow Key and Value.

**Comment by sdnts** [comment]
Hi @zhangbin1991, Descriptions are currently not supported in Bulk Edit mode, as it is meant to be a quick way to work with your key-value pairs. When you switch back to the Key-value editor, descriptions should be restored. Do let me know if restoration is not working, or if I misunderstood your request, and I'll reopen this :)
