### ISSUE TITLE
Unable to set body type to application/json-patch+json

### ISSUE THREAD

**Issue by DevTard** [a85/POSTMan-Chrome-Extension#4434]
Please add the ability to set the body type to `application/json-patch+json` or allow us to set a custom value

This is required by a number of Microsoft's api's 

Thanks

**Comment by sdnts** [comment]
@FLM96, You should be able to do this by selecting `Raw` as the body type and sending over a custom `Content-Type` header with value `application/json-patch+json` in the request headers. Do let me know if this does not work, and I'll reopen :)
