### ISSUE TITLE
Avro Support

### ISSUE THREAD

**Issue by aeropogi** [a85/POSTMan-Chrome-Extension#4435]
## App Details:

Postman for Windows
Version 6.0.10
win32 10.0.16299 / x64

## Issue Report:

I'm using the Kafka-Rest-Proxy from Confluent in order to test our Kafka streams with Postman.  For input data that is text or json, this has been simple to do.  For input data that is AVRO, this has not been possible.  I found an article in the postman documentation (https://community.getpostman.com/t/unable-to-use-external-js-library/311/7) about how to include external javascript libraries.  I followed the same pattern of browserify, capturing the code as a global variable and then 'eval' of the variable in my script for npm avsc (https://www.npmjs.com/package/avsc) to allow me to encode my message in avro format.  I also captured the json defined avro schema as an environment variable.  Here are the lines of code I'm using in my pre-request script before encountering the error.

var avro = eval(pm.globals.get("avsc"));
var type = avro.Type.forSchema(pm.globals.get("schemaTT"));

I've also tried two variants of the second line with the same results;
var type = avro.Type.forSchema(JSON.stringify(pm.globals.get("schemaTT")));
var type = avro.Type.forSchema(JSON.parse(pm.globals.get("schemaTT")));

The error message I'm receiving is;

TypeError: Cannot read property 'forSchema' of undefined

I've verified that the Type.forSchema routine is defined in the avsc global variable.

Support for avro native within postman is ideal, but a cleaner way to use external js libraries is also very desirable.

**Comment by sdnts** [comment]
Hi @aeropogi, I agree that an `eval` isn't an ideal way to include a library, we will look into this.
However, the error you're getting looks like a JS error, so there must be some invalid access somewhere in your script. I bet you've done this already, but does a `console.log(avro.Type)` right before the access log `undefined`?

If not, can you also check if the error happens during the `eval`? I'm guessing an internal constructor or something might be doing it. Let me know what you find!

**Comment by aeropogi** [comment]
Siddhant,

I had not done the console.log, so I tried that and it came back as null.  I then put a catch block around the eval to see if there were errors happening during the eval, but there was no return.  Not sure if I did the catch block properly, so here is how I did it.

try {
    var avro = eval(pm.globals.get("avsc"));
} catch (e) {
    console.log(e.message);
}

Going to look at browserify functions to see if setting flags will make a difference.  My current package was created inside the avsc npm directory with;

browserify index.js > main.js

Michael Mayo
Senior Systems Engineer
PMAT Inc.
(c) 303-598-2152

**Comment by far-blue** [comment]
As someone else working with Avro payloads in http requests and responses it would be great to see support for them :)

**Comment by aeropogi** [comment]
My team actually found a solution, so I will post it and close this issue.

Add the Key "Content-Type" with the value "application/vnd.kafka.avro.v2+json" to the header

In the Pre-request Script:

var payload = {<json>}

var message = {
        "value_schema_id": <number from kafka registry>,
        "records": [
            {
                "value": payload
            }
        ]
    };
pm.environment.set("streamMessage", JSON.stringify(message));

In the Body: 
{{streamMessage}}

I've been testing successfully with this for a couple of months now.

**Comment by aeropogi** [comment]
To clarify, since the formatting changed a little when I submitted the comment.  The payload value is json.  The value_schema_id comes from the kafka registry.

**Comment by far-blue** [comment]
Well, that works with Kafka because Kafka supports json format message payloads. But it doesn't work with generic Avro payloads.

**Comment by SanGoku95** [comment]
Any updates on support for generic Avro?
