### ISSUE TITLE
lodash already declared

### ISSUE THREAD

**Issue by mattdeluco** [a85/POSTMan-Chrome-Extension#4436]
I have a pre-request script as follows:

```
const _ = required('lodash');
...
```

When running my request I get the following error:

`There was an error in evaluating the Pre-request Script:  SyntaxError: Identifier '_' has already been declared`

The problem is that the implicitly declared '_' is for lodash 3.10.1 (I think) while using require brings in a later version - one which has a few more features that I need and that I see in the latest lodash docs.

I think that libraries should either not be implicitly imported at all, or if they are, they should be the same version as would be available when explicitly imported.

Why are there conflicting versions of libraries?

**Comment by sdnts** [comment]
Hi @mattdeluco, this is intended. While lodash 4 is the latest version of the library, breaking changes were introduced with v4. To avoid Postman scripts breaking, we still ship v3 by default, but give you the option to `require` v4, if you need.

As for your error, you can resolve it by simply renaming your variable from `_` to something else.

I'm closing this, I hope this was helpful! If not, do let me know, and I'll reopen.

**Comment by AniketBanik** [comment]
Hi @madebysid and @mattdeluco , 
Can you please help me? I am also facing the same problem while using lodash. My lodash version is 4.17.21.
My codes are : `const _ = require("lodash");` and `product = _.extend(product,fields);`

Error showing : **const { update } = require("lodash");  SyntaxError: Identifier 'update' has already been declared**
I also tried by changing my variable name _ . But, it's not working. Please help me.
