### ISSUE TITLE
Copy pasted fields from params to body not sent.

### ISSUE THREAD

**Issue by EgorZotov** [a85/POSTMan-Chrome-Extension#4438]
## App Details:

```
Postman for Windows
Version 6.0.10
win32 10.0.16299 / x64
```

## Issue Report:
 1. Copy/pasted params with a select tool are not sent in the body. Never tried this before.
 2. Copy/paste fields from params fields. Get the full body on request send. 
 3. Screenshots : 
### These fields were not sent in the body, because they were copy/pasted from params. The test added manualy was sent fine.
![image](https://user-images.githubusercontent.com/23280344/38586945-7211b194-3d28-11e8-84da-4d9acb502661.png)

Write some params, put it in x-www-urlencoded body by selecting with mouse and ctrl-x/ctrl-v pasting. Send request and check the body.

**Comment by sdnts** [comment]
Hi @EgorZotov, I was unable to reproduce this. Can you record a screencast of you doing this or something? That would help me get to the bottom of this faster. Thanks!

**Comment by EgorZotov** [comment]
Hi, @madebysid 
Here is the video of reproducing steps. I got simple endpoint that returns the body of a request.
https://youtu.be/Wun4e4yJhbk
It can be copy/paste or cut/paste it doesn't matter.

**Comment by sujayvenaik** [comment]
Hey @EgorZotov 

I tried this on the latest v6.4.2 app, and this seems to work fine.
Could you try updating to the new app and see if you are still facing this issue. ?

**Comment by numaanashraf** [comment]
@EgorZotov We are not able to replicate this at our end. Please re-open if you are still facing this issue.
