### ISSUE TITLE
No support for WSSE authorization type

### ISSUE THREAD

**Issue by safaiyeh** [a85/POSTMan-Chrome-Extension#4439]
Reopening for Visibility:

> Postman Version: 4.10.2
> App (Chrome app or Mac app): Chrome App
> OS details: x86-64
> Is the Interceptor on and enabled in the app: Yes
> Did you encounter this recently, or has this bug always been there: Feature not present in postman at all.
> Expected behaviour:
> Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
> Screenshots (if applicable)
> My automated API testing involves working with APIs which use an authorization method called WSSE.
> The authentication happens using below parameters:
> 
> X-WSSE: UsernameToken Username="", PasswordDigest=" ", Nonce=" ", Created=" "
> 
> I didnt find a way in Postman that can help me do this.
> Any help is greatly appreciated.
> Thanks.

https://github.com/postmanlabs/postman-app-support/issues/2762

**Comment by sdnts** [comment]
Hi @JSafaiyeh, we track all features, no matter how old, and are adding new functionality as fast as we can! I'm closing this, since this is a duplicate, please follow that thread for updates, thanks!
