### ISSUE TITLE
Feature Request - Non sync'd variables/env variables.

### ISSUE THREAD

**Issue by scott-davidjones** [a85/POSTMan-Chrome-Extension#4442]
## App Details:
```
Postman for Windows
Version 6.0.10
win32 10.0.16299 / x64
```
Hi,

I currently work as part of a large team at a clients premesis. My Client has control of the Team workspace which I am apart of and I dont wish to have a local/personal copy of their collections. 

We are experiencing an issue with multiple developers running messages against a development environment and thus updating various environment variables (unique id's, statuses etc). This then causes an overlap whereby one developer 1 thinkgs he is requesting data for data set X but developer 2 changes the env variable to use data set Y causing dev 1 to retrieve data for data set Y.

This then causes a lot of head scratching and double checks of code to find out it was a postman env change that caused the "issue"

It would be benefical to be able to have a local environment that does not get sync with the team workspace. This could be a setting on the environment setup that asks if the user wants to sync the environment (checkbox?)

**Comment by JakePenzo** [comment]
Having the same issue.
There should be a Local set of variables that each user can refer to, for example the "auth token", should be stored in the local set, otherwise dev1 is going to override the token of every other dev working on the same collection with the same env.

**Comment by scott-davidjones** [comment]
believe this feature is the same as this new feature request: 
https://github.com/postmanlabs/postman-app-support/issues/4449

details in the new feature request superceed this request.
