### ISSUE TITLE
Repeated sync conflict

### ISSUE THREAD

**Issue by TheNilesh** [a85/POSTMan-Chrome-Extension#4443]
Unknown sync conflict continues to re-appear. Choosing either of Local Value or Server Value doesnt helps.

## App Details:

```
Postman for Windows
Version 6.0.10
win32 6.3.9600 / x64
```

## Issue Report:
 1. Encounter this recently since the last update. Since February 2018 (approx).
 2. Expected behaviour: No repeated sync conflict errors.
 3. Console logs ?
 4. Screenshots
![image](https://user-images.githubusercontent.com/5434666/38661532-d37f2a70-3e4e-11e8-8a81-a08727ec4e2f.png)

Don't know how to reproduce. It started after the update. Username: TheNilesh

**Comment by ghost** [comment]
Hi Nilesh,
This issue has been reported earlier. #4360 
We'll be pushing the fix out on our Canary channel.
Closing this issue.
