### ISSUE TITLE
URLEncode plus sign in query parameters

### ISSUE THREAD

**Issue by DanielPetatCes** [a85/POSTMan-Chrome-Extension#4444]
## App Details:
```
Postman for Windows
Version 6.0.10
win32 10.0.16299 / x64
```

## Issue Report:
I use the "Params" view to enter some query parameters for a GET request.
In my case, I need to send an timestamp in ISO format, which includes a + sign.
So I enter the value ```2018-04-12T10:28:47.4453505+02:00```

But as in 
https://en.wikipedia.org/wiki/Query_string#URL_encoding
my server side thinks, the + sign means a whitespace. So I get an Exception while deserializing this string.

Is it possible, to differentiate between a desired + sign and an encoded whitespace?
Or do I just have to be careful and replace the + sign by %2B myself?

**Comment by P1llus** [comment]
+1

**Comment by vanbukin** [comment]
+1

**Comment by SamvelRaja** [comment]
We are following a master thread #4555 to track all issues related to Url encoding. Please follow that issue for updates.
