### ISSUE TITLE
Difference in behaviour with postman collection runner and newman

### ISSUE THREAD

**Issue by saripr** [a85/POSTMan-Chrome-Extension#4445]
When I run tests from collection runner some tests fails and those pass in newman 3.9.1

## App Details:
Version 6.0.10
newman 3.9.1

Postman for Ubuntu
Version 6.0.10
ubuntu 16.04 LTS
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:always
 2. Expected behavior: Same behavior in collection runner and newman
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
{}
expected:"The key does not exist on the server"
message:"expected undefined to equal 'The key does not exist on the server'"
name:"AssertionError"
showDiff:true
stack:"AssertionError: expected undefined to equal 'The key does not exist on the server' at Runnable.it [as fn] (eval at exec (evalmachine.<anonymous>:11236:2548), <anonymous>:62:79) at Runnable.run (eval at <anonymous> (eval at exec (evalmachine.<anonymous>:11236:2548)), <anonymous>:9:12640) at PostmanBDD.it (eval at <anonymous> (eval at exec (evalmachine.<anonymous>:11236:2548)), <anonymous>:9:7296) at Runnable.eval [as fn] (eval at exec (evalmachine.<anonymous>:11236:2548), <anonymous>:61:5) at Runnable.run (eval at <anonymous> (eval at exec (evalmachine.<anonymous>:11236:2548)), <anonymous>:9:12640) at PostmanBDD.describe (eval at <anonymous> (eval at exec (evalmachine.<anonymous>:11236:2548)), <anonymous>:9:7030) at Object.eval (eval at exec (evalmachine.<anonymous>:11236:2548), <anonymous>:45:1) at Uniscope.exec (evalmachine.<anonymous>:11236:2583) at module.exports (evalmachine.<anonymous>:62:538) at Object.<anonymous> (evalmachine.<anonymous>:65:1694)"


Steps to reproduce:
Description: Tests have the below line:
 expect(jsonData[environment.decodedNonExistAdSlot][globals.error]).to.equal(globals.keyNotExistsMessage);
where it compares the JSON value returned from API to a string.
1.Run the above tests from collection runner and get the error message as in console log in issue report point 3
2.Run the same tests from newman and observe that it passes

**Comment by sivcan** [comment]
Hi @saripr - Are you sure that the globals that you're using in newman also exist in the app ?
Can you check that ? 
![image](https://user-images.githubusercontent.com/12631777/38725213-3f0a8f0c-3f24-11e8-9eeb-c77c43490efc.png)

Did you export the globals from newman and imported them into to the app ?

**Comment by saripr** [comment]
I have the variables in both app and newman. I have checked it with console log and this is the behaviour:
For this expect(jsonData[environment.decodedNonExistAdSlot][globals.error]).to.equal(globals.keyNotExistsMessage); statement in the code
1. If I check with the string directly like below in console log of postman as below, it displays the correct value:
console.log(jsonData[environment.decodedNonExistAdSlot]["error"]); 
and if I do like  console.log(jsonData[environment.decodedNonExistAdSlot][globals.error]); it displays null.
2.In newman if I run expect(jsonData[environment.decodedNonExistAdSlot][globals.error]).to.equal(globals.keyNotExistsMessage);  it works as expected. But if I run 
expect(jsonData[environment.decodedNonExistAdSlot]["error"]).to.equal(globals.keyNotExistsMessage);" it throws  error as in the issue report above.

This clarifies the difference in behaviour between postman and newman

**Comment by sivcan** [comment]
@saripr - If I got you correctly..

I prepared this request that does a similar thing and you can see in the console log that it works fine.
![image](https://user-images.githubusercontent.com/12631777/38732132-c8b9b1fe-3f3a-11e8-93b8-5d74fa11f12a.png)

Console log after running that request: 
![image](https://user-images.githubusercontent.com/12631777/38732153-d7ec92c2-3f3a-11e8-92fa-c8dd2b50ca5a.png)

There's no issue if I am accessing object properties using a string or globals. 
However, the null is coming as an output when an undefined variable is being used to access the property.

If I am still wrong can you send the collection and globals to [help@getpostman.com](help@getpostman.com) ?
Feel free to retract any sensitive information. :)

**Comment by saripr** [comment]
attaching my screenshots for more clarity:

![selection_082](https://user-images.githubusercontent.com/10835735/38810132-1c5f63ec-4186-11e8-82e1-92ccdc94aba0.jpg)
![selection_083](https://user-images.githubusercontent.com/10835735/38810136-1e462ff6-4186-11e8-886a-6a705f3b8da9.jpg)
