### ISSUE TITLE
New collections not syncing to team workspace without closing and re-opening the app

### ISSUE THREAD

**Issue by HollowayT** [a85/POSTMan-Chrome-Extension#4447]
## App Details:

```
Postman for Mac
Version 6.0.10
OS X 16.7.0 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there: Recently encountered
 2. Expected behaviour: When creating a new collection it should be immediately synced for all on the team workspace to see. Adding, editing and deleting requests of an existing collection are all instantly synced, but not when creating a new collection.
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app): No logs
 4. Screenshots (if applicable): No screenshots

1. Two users join the same team workspace.
2. One of the users creates a new collection in the team workspace.
3.  The other user will not see the collection. Pressing the sync button does not work. Closing and re-opening the app is the only way for the collection to sync.

**Comment by kamalaknn** [comment]
Hey @HollowayT 

I tried to reproduce this, but couldn't.

We've made a couple of fixes to handle concurrent events applied on the view, see [here](https://github.com/postmanlabs/postman-app-support/issues/4794). This fix will be pushed to the stable channel soon.

I'm closing this as a duplicate. Feel free to reopen if this is unrelated. Any more info to reproduce this would be helpful.
