### ISSUE TITLE
Got error when I try to press the "Run in postman"

### ISSUE THREAD

**Issue by BillWilson** [a85/POSTMan-Chrome-Extension#4448]
## App Details:
```
Postman for Mac
Version 6.0.10
OS X 17.5.0 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there: 
It's still exist.
 2. Expected behaviour:
Easily share my postman doc with it and open the app
 3. Console logs:
Check the screenshots
 4. Screenshots (if applicable)
![](https://i.imgur.com/Vsq68m7.png)

I got the console error when I have some non-ascii character in my document.

**Comment by dhineshwiz** [comment]
Thanks for reporting the issue, we will look into it

**Comment by preethammavin** [comment]
@BillWilson can you check with the latest version of the app? Also can you provide the link of the documentation if its public?

**Comment by BillWilson** [comment]
Thanks, @preethammavin and others who work on fixing it.
 I have checked the documentation page and it works as I expect.

My document contains some material which is not able to share the link here.
So I have some other public document which also has non-ascii character:
https://documenter.getpostman.com/view/2883359/RWTmvJZ7
https://documenter.getpostman.com/view/4857742/RznFqJmS
https://documenter.getpostman.com/view/507227/api-20/77mZM2n

**Comment by preethammavin** [comment]
@BillWilson thanks for letting us know, closing the issue.
