### ISSUE TITLE
Feature Request - Better and easier Variables

### ISSUE THREAD

**Issue by JakePenzo** [a85/POSTMan-Chrome-Extension#4449]
I agree with @vdespa, documentation is confusing and current variables are a limit when you share the collection with a team.

**Current situation:**
In the current version - from my understanding - we have 3 available scopes on where we can store variables:

- global
- collection
- environment

Scopes follow the hierarchy specified in the documentation:

- global
- collection
- environment
- local
- data

We can access the variables from the "variables tooltip" when we edit the URL for example and that's great.
From the "Tests" tab we can access variables like:

```
- pm.globals.get()
- pm.environment.get()
```

and `pm.variables.get()` I would consider it a special function because it retrieves the "highest" variable within in scopes hierarchy.
(Correct me if I'm wrong?!)

We can set variables only like:

```
- pm.globals.set()
- pm.environment.set()
```

**The problem:**
Global and Environment scopes are shared with the Team.
If I have a Test script that capture the token, after a login request for example and set that token to an environmental variable.. this variable is shared.
Means that if I have two devs working on the same collection Dev1 is going to login and override Dev2 token and vice versa.

**Possible situation:**
I think the current hierarchy works great.
But we should have 4 different scopes:

- global
- collection
- environment
- local

Variables are accessible like:

```
- pm.globals.get()
- pm.collection.get()
- pm.environment.get()
- pm.local.get()
```

And of course we can **set** variables in the same way.

```
- pm.globals.set()
- pm.collection.sett()
- pm.environment.set()
- pm.local.set()
```

**Only Global / collection / environment are shared with the Team, 
Local - obviously - stay local.

On doing this, Dev1 will not override Dev2 local variables, and everyone can keep working happily!**

The Variables Quick Look would look like:
![screen shot 2018-04-13 at 12 59 53 pm](https://user-images.githubusercontent.com/1734654/38715655-94297236-3f1b-11e8-8039-242884734195.png)

This make super easy to visualise the hierarchy and see which scope is overriding which variable.
Same as when we work on CSS with the Chrome Inspect Element.
Also much easier to edit the variables, at the moment is really annoying when you have to edit Collection variables.

pm.variables.get() will become super handy and straight forward to use as it will return the first variable "non crossed" from the top of the list.

Hope that make sense!

**Comment by dhineshwiz** [comment]
Hey @JacopoKenzo This is a great feature, Thanks for your suggestion, I'll be putting it up as a feature request.

**Comment by scott-davidjones** [comment]
closed my feature request (https://github.com/postmanlabs/postman-app-support/issues/4442) in favor of this one

**Comment by sankalp0o** [comment]
Hi @JacopoKenzo and @autumndev ,
We are currently working on a feature which would let developers work (locally) with different values of a single variable. We're taking a holistic look at how variables work inside postman and hopefully this would solve a bunch of issues including yours.

**Comment by suihanki** [comment]
~~@sankalp0o is there anything currently on the roadmap related to this? or still in early/design phases?~~

nm I see the [RFC](https://community.getpostman.com/t/sessions-in-postman/1925) around sessions!

**Comment by m3dbedb** [comment]
Does local variable, defined in pre-request or test script (var a;) is the same as collection variable accessed via pm.variables.a?

**Comment by vkaegis** [comment]
@JacopoKenzo Hey, as of 6.4, you can now set current values for all your shared variables. These values are local to your session and don't affect other users working with the same variable. 

Closing this issue for now, feel free to open another if you have more feedback around this.

**Comment by deven-s** [comment]
awaiting for this feature, any updates?
