### ISSUE TITLE
Not able to convert SOAP WSDL API XML Response to Postman REST JSON Response by giving wt=json at end of the endpoint

### ISSUE THREAD

**Issue by Tenkasi-Subramanian** [a85/POSTMan-Chrome-Extension#4452]
## App Details:
Postman for Win64
Version 6.0.10
```
## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:
I guess always.
 2. Expected behaviour:
SOAP WSDL API XML Response should be converted to Postman REST JSON Response
<!--
Steps to reproduce the problem:
1. Endpoint Used in POST method:
http://www.holidaywebservice.com/HolidayService_v2/HolidayService2.asmx,abstract**&wt=json**
2. Provide below SOAP WSDL envelope in body
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:hs="http://www.holidaywebservice.com/HolidayService_v2/">
 <soapenv:Body>
     <hs:GetHolidaysForMonth>
        <hs:year>2018</hs:year>
        <hs:countryCode>UnitedStates</hs:countryCode>
        <hs:month>11</hs:month>
     </hs:GetHolidaysForMonth>
 </soapenv:Body>
</soapenv:Envelope>
3. Send the Request.

Note:
Below endpoint is for XML to JSON Response converter and that is working fine.
http://api.plos.org/search?q=title:"Drosophila" AND body:"RNA"&fl=id,abstract&wt=json

Original Endpoint URL which provide XML response as default:
http://api.plos.org/search?q=title:"Drosophila" AND body:"RNA"&fl=id,abstract
-->

**Comment by Tenkasi-Subramanian** [comment]
![image](https://user-images.githubusercontent.com/38352845/38812536-25e847fc-41aa-11e8-864f-da8b5b7ee7c9.png)

**Comment by Tenkasi-Subramanian** [comment]
See the above image. &wt=json at the end of the endpoint converted XML Response to JSON response. I want same type of conversion for post response also which is given in Issue section.

**Comment by kamalaknn** [comment]
@Tenkasi-Subramanian By looking at the information given, I am guessing the server is returning the response in `xml` format.

To confirm this you can open the `Postman Console` (View -> Show Postman Console) and select `raw` view in response to see the raw response from the server.

If the server does return in `xml` format Postman as a client cannot and should not convert the response body.

I'm closing this issue for this reason. Please let me know if I had missed anything here.
