### ISSUE TITLE
 Postman (v6.0.10) Runner > Run Summary > all calls after 54th marked as failed

### ISSUE THREAD

**Issue by AndriiStepura** [a85/POSTMan-Chrome-Extension#4453]
## App Details:
v6.0.10 Win 10

## Issue Report:
 1. In Runner > Run Summary report - all calls after 54th marked as failed
![runnersummaryfailedred](https://user-images.githubusercontent.com/30338636/38737785-96e7e4b6-3f30-11e8-89a6-71f511156515.png)

**Comment by AndriiStepura** [comment]
P.s.: not reproduced with Postman v6.1.0-canary02

**Comment by sdnts** [comment]
@AndriiStepura, this is super weird, however, I'm glad it is fixed on the Canary channel.
Were the Summary and Results page differing? Or were both pages wrong? You might want to check your scripts to see if something was up there. 
I'm closing this for now though, since this seems to be fixed!

**Comment by AndriiStepura** [comment]
@madebysid just in "Summary" (as described in the title and steps for reproducing ;) ), at Run Results all are green.
