### ISSUE TITLE
Raspberry Pi support

### ISSUE THREAD

**Issue by BenjaminEHowe** [a85/POSTMan-Chrome-Extension#4454]
It would be great if Postman could support the Raspberry Pi. It's a pretty capable little device for desktop computing. Over [19 million units](https://www.raspberrypi.org/blog/raspberry-pi-3-model-bplus-sale-now-35/) have been sold, making it the [third best-selling computer of all time](https://www.techradar.com/news/the-raspberry-pi-is-now-the-third-best-selling-computer-of-all-time).

I appreciate that compiling for a whole new architecture is non-trivial, but...

**Comment by sdnts** [comment]
Hi @BenjaminEHowe! It's super interesting that you're trying to run Postman on a Pi. We use Electron to package our native apps, which does not support arm64 yet, which the Pi uses (correct me if I'm wrong).
If, however, you want to run collections on the Pi, I'd recommend installing Node on it, and taking a look at [Newman](https://github.com/postmanlabs/newman), which is a command line collection runner. If you use Sync, you can just punch in the collection URL and every time you run the `newman` command, it'll fetch the latest collection from our Sync servers, so you wouldn't have to worry about collection updates and stuff. Let me know if this is helpful :)

**Comment by BenjaminEHowe** [comment]
At the moment most Raspberry Pi operating systems use the `armv7l` architecture. There are a few 64-bit operating systems (e.g. [SUSE](https://www.suse.com/products/arm/raspberry-pi/)) but at the moment [there are no plans for the "official" operating system (Raspbian) to use 64-bit instructions](https://www.raspberrypi.org/blog/eben-q-a-1/) as this would break backwards-compatibility.

A quick Google [suggests you can use `--armv7l`](https://github.com/electron-userland/electron-builder/issues/831) to build for this architecture, but I've got very limited experience with Electron so I'm not sure.

**Comment by fifn2** [comment]
I'm also interested in getting this to work on the rPi

**Comment by diaakasem** [comment]
It will be great if you can provide an ARM version ... I use my Raspberry PI 4 on the go,, when I dont need to carry the laptop ... and Postman is an important app in for my work ... 

Thank you for the crazy good app.

**Comment by jpop32** [comment]
Electron now has arm64 support: https://www.electronjs.org/blog/electron-11-0 so it would seem possible to build a linux/arm64 version.

**Comment by arnaldoperez** [comment]
Still I don't see a Postman build for raspberry pi. I'm currently coding in Vscode on my raspberry pi with ubuntu, and with no problem..... so electron shuld be pretty stable in arm by now! Should this issue be reopened??

**Comment by BenjaminEHowe** [comment]
I think #5816 is the place to track arm64 support.

In terms of Raspberry Pi support, [it's been possible to run electron applications on a Raspberry Pi since at least November 2015](https://www.hackster.io/10674/electron-on-raspberry-pi-c8bce1), so I think it's a simple case of not wanting to support the additional architecture.

**Comment by mollthecoder** [comment]
arm64 is great for 64-bit Raspberry Pi OS and all, but I use 32-bit and I'd like to see support for armv7l

**Comment by BenjaminEHowe** [comment]
I don't see why they'd want to add support for an architecture which is likely on a downward trajectory. I'd suggest you strongly consider the 64-bit builds of Raspberry Pi OS. [The team at Postman report that they are actively working on Linux arm64 support](https://github.com/postmanlabs/postman-app-support/issues/5816#issuecomment-1139977279).
