### ISSUE TITLE
collection is not displayed

### ISSUE THREAD

**Issue by kmelodi** [a85/POSTMan-Chrome-Extension#4456]
## App Details:

```
Postman for Win
Version 6.0.10
OS Windows 10 x64
```

## Issue Report:
 1. After adding the collection using the url, the collection is not displayed

**Comment by sdnts** [comment]
Hi @kmelodi, can you provide some more steps to reproduce this? Maybe a screencast or something? If this is happening for only one collection, can you share the collection here? If it contains private info, please redact it, or email it to help@getpostman.com.

**Comment by kmelodi** [comment]
This problem is only for version 6 above Windows and for all my collections.
I tested the collection for Postman-Chrome and versions below 6 and had no problems.

**Comment by thecuriousdev** [comment]
@kmelodi Please provide the steps to reproduce this issue. We'll look into this.
