### ISSUE TITLE
I am not able to send form-data through POST in windows 10.

### ISSUE THREAD

**Issue by sumchat** [a85/POSTMan-Chrome-Extension#4457]
I am using windows 10. I cannot use POST.

POST /api/sellers/558/products HTTP/1.1
Host: localhost:8000
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
Cache-Control: no-cache
Postman-Token: 81886c5f-8a83-d79d-c676-ec348fdb5345

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="name"

Almond1
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="description"

nuts 
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="quantity"

4
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="Picture1.png"
Content-Type: image/png

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="address"

3372 galleon
------WebKitFormBoundary7MA4YWxkTrZu0gW--

**Comment by harryi3t** [comment]
@sumchat Could you share a screenshot of the app as well as of the Dev Tools

**Comment by sumchat** [comment]
I was facing the problem in the  Chrome app. But when I downloaded the windows app it worked fine. Seems like it is a problem only in the Chrome app.
