### ISSUE TITLE
Postman APP "Could not get any response" from localhost

### ISSUE THREAD

**Issue by levinor** [a85/POSTMan-Chrome-Extension#4459]
## App Details:
Postman for Windows
Version 6.0.10
win32 10.0.14393 / x64

## Issue Report:

Hi,

I'm new using Postman. I tried to debug a web site using the Postman APP, in Chrome the web loads perfectly but in Postman APP I allways get "Could not get any response". I tried to use 

http://localhost:53230/Default.aspx
http://127.0.0.1:53230/Default.aspx
http://[::1]:53230/Default.aspx

With the same result.

I just tried the Chrome extension version of Postman and it works like a charm.

My machine is under a Proxy, but I tried configuring it both "Use system configuration" and entering the configuration by hand, all failed. But even if I deactivate all Postman proxy configuration it tries to reach localhost through the proxy.

 3. Console logs 

http://localhost:53230/
Error: connect ETIMEDOUT {Proxy IP}:8080
Request Headers:
cache-control:"no-cache"
postman-token:"84d4e1a7-f9de-4ef3-9496-d64c78537061"

http://127.0.0.1:53230/
Error: connect ETIMEDOUT {Proxy IP}:8080
Request Headers:
cache-control:"no-cache"
postman-token:"74cd7595-e1d7-46f8-9bbe-67037d69c5b0"

http://[::1]:53230/
Error: connect ETIMEDOUT {Proxy IP}:8080
Request Headers:
cache-control:"no-cache"
postman-token:"16fb9c06-1e53-4ef2-9737-848fefd58cbd"

Thanks for your help

**Comment by hafeefshaik** [comment]
@levinor even I am facing the same issue. Thanks for reporting.

**Comment by harryi3t** [comment]
@levinor @hafeefshaik 
It's a known issue https://github.com/postmanlabs/postman-app-support/issues/4045, https://github.com/postmanlabs/postman-app-support/issues/3942
Postman will take the proxy settings from some environment variables (http_proxy, HTTPS_PROXY, etc) even if they are turned off from the UI

For now, the workaround is to open the Postman app with these variables unset. For this simply create a bat file with the following content and open the app with the bat file. Also turn off both the `global proxy` and `system proxy`

```bat
set HTTP_PROXY=
set http_proxy=
set HTTPS_PROXY=
set https_proxy=
START %LOCALAPPDATA%\Postman\Update.exe --processStart "Postman.exe"
```

**Comment by numaanashraf** [comment]
If you get a "Could not get any response" message from Postman native apps while sending your request, open Postman Console (View > Show Postman Console), resend the request and check for any error logs in the console. This should give you some information to troubleshoot the issue by searching for the same error in this issue tracker to find possible workarounds and fixes. If you are still having trouble, please open a new bug report with the screenshot of the error and any steps we can take to quickly replicate the issue.
