### ISSUE TITLE
Editing duplicated tab title affects all duplicated tabs

### ISSUE THREAD

**Issue by oleksii-lukin** [a85/POSTMan-Chrome-Extension#4463]
## App Details:
```
Postman for Mac
Version 6.0.10
OS X 17.4.0 / x64
```

## Issue Report:
I only started using Postman so not sure if this worked like this before or not

Reproduce steps:
1. Duplicate tab.
2. Rename new tab.
3. Tab from which you duplicated new tab is also renamed.

Expected behavior
1. Duplicate tab.
2. Rename new tab.
3. Only new tab should be renamed, old tab should keep it's old name

https://imgur.com/a/t9ukb https://imgur.com/a/4JlU3

**Comment by kamalaknn** [comment]
Hi @llamerr 

This seems to be an inconsistent behavior. When the same request is edited in two tabs the changes are not propogated to other tabs. But this name update seems to update other tabs as well.

We are working on improving the overall experience with tabs. We will revisist this soon.

Thanks.

**Comment by k-dahl** [comment]
This bug is making it hard to keep things organized, any update on fixing it?

**Comment by sujayvenaik** [comment]
Hey, @blitzd 

We have started working on refactoring the whole experience around tabs.
I'll keep this thread updated as soon as we make a release.

**Comment by sujayvenaik** [comment]
Hey @blitzd 
This is the desired behavior how it should go about.

In the next release, we will include inline messaging in order to communicate this better to the users.

**Comment by k-dahl** [comment]
@sujayvenaik sorry, but can you confirm that what you said equates to this bug being fixed in the next release? Because it sort of sounds like you're saying the tabs share the names and that you're going to instead update inline messaging to indicate this, and that really doesn't make any sense to me or my team.

**Comment by vkaegis** [comment]
Hey @blitzd! Thanks for pointing this out. The behavior is as intended. Duplicating a tab doesn't duplicate the request, but creates another instance which points to the same request. The request name and description are shared between the two tabs since they both point to the same request. What we will be doing in the next version is making this behavior more apparent.

That said, it seems like your intent of duplicating the tab is to get the contents of the tab in an empty slate, and not to point to the same request. If this is correct, I'd love to hear more about your use case and we can open a separate feature request.

**Comment by k-dahl** [comment]
@vkaegis my scenario was more duplicating the tab as a starting point for a variation on the request, like say a POST with valid data vs invalid... but we'd need to differentiate these variations by name. Maybe there's a better way to do this with Postman that I'm just unaware of right now. I don't know of any scenario where we'd want to duplicate a tab/request and not be able to identify it by what differentiates it from the other tab (i.e., rename it).

**Comment by vkaegis** [comment]
@blitzd Understood. Duplicating a tab actually works differently from duplicating a request. Where duplicating a tab just creates another instance pointing to the same request, duplicating a request actually creates a new request with the same contents as the previous request. So in your use case, you might be better served by duplicating the request in the sidebar than by duplicating the tab. 

Another construct you can explore on the topic of creating variations of the same request are [Examples](https://www.getpostman.com/docs/v6/postman/collections/examples). Creating examples for variations of requests also shows the same in the auto-generated documentation. Examples also allows for the ability to mock responses. Let me know if this solves your immediate problem.

We'll be working on some improvements to make this difference evident in the interface. Thanks again for taking the time to reply, it helps a lot!

**Comment by DM-MorganKohler** [comment]
Hi I just came to this thread and it seems as if there is no good way to duplicate a request currently. I tried duplicating a tab and that pointed to the same tab. I tried duplicating a collection and this pointed to the same collection. And I also tried duplicating a request as suggested here. The request was completely blank, basically, like I was starting over from scratch. Is this really the desired behavior of all of this duplication? I can't think of a use case where I would want multiple tabs pointing to the same instance. Furthermore, is the only way to actually copy content through the use of templates?

**Comment by sujayvenaik** [comment]
@DM-MorganKohler 
Hey, if you duplicate a request/collection from the sidebar it is a new instance of a request/collection that is created, so if you open the request from the duplicated collection that should not point to the original request.

This is not the intended behaviour that when you duplicate a request from sidebar it is completely blank. Can you confirm that you duplicated the request from the sidebar? And the contents which you expect in the duplicated request were saved?
Also can you share the logs from View -> Developer -> View logs from finder. And also View -> Developer -> DevTools (Current View).

**Comment by DM-MorganKohler** [comment]
@sujayvenaik
Thank you for the quick response, the issue was with me not saving the request before attempting to duplicate it. I appreciate your help in resolving this.

**Comment by vnktsh** [comment]
@sujayvenaik To make ease this confusion, we can have two options "`Duplicate`" and "`Copy to New`" from the right click menu on tabs. The current procedure i.e. if you "Duplicate" from the tab menu you're duplicating the instance and if you "Duplicate" from the side-bar, you're duplicating the request, is not intuitive and confusing.

**Comment by abser** [comment]
It is working from left sidebar only! At least it saved my life!

Thanks!

**Comment by sonuame** [comment]
Yea, pointing to the same request instead of creating a clean slate makes things little weird for me. So many times I ended up modifying my old working request. Sidebar saved me...

**Comment by vmachacek** [comment]
Why you would ever for love of god want to duplicate tab but not the request (resulting it's pointing to the same instance of request) What I'm expecting is to create copy of the tab with copy of the request. This looks like sloppy UX to me

**Comment by sonuame** [comment]
@vmachacek Let me explain this to you. Lets say there is a request A with 5+ custom headers, api url with 2/3rd of part same and sometimes same request body with minimal changes. 

I know common headers can be set for once on the parent folder but trust me i have been into cases where endpoints of same server differs with the header values too.

Now, right clicking on the left side bar and select "Duplicate request" serves y purpose perfectly. But it would be great to have the very same behavior on tab right click too. 

because lets face it... 2 tabs with  exact request body and params is a bad UX in itself. I have been working with postman from past 5yrs.. not once I saw the benefit of this. whereas duplicating the requests via side bar is part of life everyday.

**Comment by pkozuchowski** [comment]
This still happens in v7.12.0 and is extremely aggravating. Worst UX ever!

**Comment by charlesritchea** [comment]
tone deaf

**Comment by alaurenau** [comment]
This "duplicate" functionality of tabs looks completely useless and confusing. I wonder what are the use cases of shallow copy of a tab? Why would someone need it?

**Comment by arlemi** [comment]
This issue is closed, any UX improvement regarding this will be posted in #7867.

**Comment by sonuame** [comment]
> This "duplicate" functionality of tabs looks completely useless and confusing. I wonder what are the use cases of shallow copy of a tab? Why would someone need it?

lets say there are 4 environment variables including headers and some params
headers cannot be inherited from the parent collection unless you create presets and that too you have to everytime manually do "add presets"

there are 150 APIs total belongs to the project i am working on. 
what would you do??

**Comment by atrophes** [comment]
This still happen in the latest version v7.34.0, and i can't find the "Copy to new" option on right click menu

**Comment by worlebird** [comment]
You say this is desired behavior - this is NOT desired behavior. This behavior is useless, confusing, and nonsensical. Plus, the desired behavior (namely, duplicating all of the contents of an existing tab into a brand new tab unconnected to the original) doesn't seem to be supported in anyway that I can find.

**Comment by worlebird** [comment]
RE-OPEN THIS ISSUE. This is not fixed, so it should not be closed.

**Comment by sonuame** [comment]
This should be reopened

**Comment by arlemi** [comment]
You can duplicate a request, collection, or folder in the sidebar: 
![image](https://user-images.githubusercontent.com/5029719/107623198-e0d26380-6c50-11eb-927c-23448c4a243d.png)

Improvements to the UX will be posted in  #7867.

**Comment by linkinChitown** [comment]
Nah this needs to be reopened. It's incredibly unintuitive for a duplicate tab to be renaming the original one. Frustrating

**Comment by sonuame** [comment]
Please Reopen this one

**Comment by arioul89** [comment]
+1

**Comment by jasiu001** [comment]
+1

**Comment by JSalazarSoftware** [comment]
Completely unintuitive. This needs to change.

**Comment by CedricSogetrel** [comment]
+1
The current feature is confusing and useless.
The users need to create a **new** tab with the same parameters to quickly test some variations in their request without having to save them in collection or altering existent ones
