### ISSUE TITLE
Code snippet for cURL uses incorrect Content-Type when form data includes a file

### ISSUE THREAD

**Issue by narehart** [a85/POSTMan-Chrome-Extension#4465]
## App Details:
```
Postman for Mac
Version 5.5.3
OS X 17.5.0 / x64
```

## Issue Report:
**Recent**  
This is recent to me

**Expected behaviour**  
Generating cURL code from a request that includes a file in the form data should use the content header type `multipart/form-data` but instead uses `multipart/x-www-form-urlencoded`.

**Screenshots**
<img width="578" alt="screenshot 2018-04-17 12 52 15" src="https://user-images.githubusercontent.com/1486419/38893115-3b974974-423e-11e8-8df6-5a6b366a2b42.png">
<img width="739" alt="screenshot 2018-04-17 12 52 24" src="https://user-images.githubusercontent.com/1486419/38893120-40662240-423e-11e8-9b04-77cd3897968d.png">

1. Create a POST request with the content type set to form-data
2. Add a field with a file as the value
3. Click Code > cURL

**Comment by shreys7** [comment]
Hey @narehart I was not able to reproduce your issue on Postman 7.x .Only the header multipart/form-data is being added. Can you update the app and verify whether you still face the problem ? If yes,  feel free to add a comment detailing exact steps to reproduce the issue (with screenshots, preferably).
<img width="661" alt="Screenshot 2019-04-21 at 7 04 10 PM" src="https://user-images.githubusercontent.com/20665864/56470847-b3f40180-6468-11e9-8aed-3afb2622189f.png">
<img width="721" alt="Screenshot 2019-04-21 at 7 04 44 PM" src="https://user-images.githubusercontent.com/20665864/56470848-b48c9800-6468-11e9-9bb1-6b9cbae844e1.png">
