### ISSUE TITLE
A few NEEDED features for Pro

### ISSUE THREAD

**Issue by TylerAHolden** [a85/POSTMan-Chrome-Extension#4466]
## Feature requests:
+ ~~Move folders and requests around - currently you can only duplicate in the current folder or delete.~~
EDIT: I guess I found a bug because I resized my window and then it allowed me to drag and drop the folders. Thank goodness this is a feature!
+ Tag team members on requests. Imagine a particular API call is broken... It'd be nice to tag a team member so he/she can take a look at it and fix it. 
+ Labeling Routes. Custom colored labels such as [broken] or [fixed] or [build] etc.
+ Comments on requests for only team members to see.  Example "id field is coming back null. Please fix"

## App Details:
```
Postman for Mac
Version 6.0.10
OS X 17.4.0 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:
+ No
 2. Expected behaviour:
+ N/A
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
+ N/A
 4. Screenshots (if applicable)
+ N/A

**Comment by sivcan** [comment]
@NG-tylerholden - Hey, thanks for suggesting this.
I'll mark this as a feature request.

**Comment by sankalp0o** [comment]
Hi @NG-tylerholden,
We actually are planning a feature for adding comments/annotations to specific places in a collections. This should solve most of your use cases.

**Comment by a85** [comment]
@NG-tylerholden Comments are now available in our Canary release and shipping to production soon. You can tag team members as well. You can get the Canary version here: https://www.getpostman.com/downloads/canary

**Comment by a85** [comment]
@sankalp0o Can we break down this into multiple issues. Closing this as the ability to tag people and add comments is already there.
