### ISSUE TITLE
Setting menu layout close after check for update

### ISSUE THREAD

**Issue by ghost** [a85/POSTMan-Chrome-Extension#4467]
Hello
Setting menu layout closed when I check for update and there is no any update, When I close update pop up layout then also setting layout close.

**Step to reproduce**
File->Setting->Update (check for update).

**Expected Result:**
If there is no update then setting layout should not close.

**Comment by harryi3t** [comment]
@mayankvadiya Can you provide us more information about your platform, postman version and some relevant screenshots?

**Comment by ghost** [comment]
@harryi3t My platform is window10, My postman version is v6.0.10

**Comment by a85** [comment]
Can't seem to replicate this. Closing this for now.
