### ISSUE TITLE
New requests saved to collection don't appear if collection is being viewed by filter search

### ISSUE THREAD

**Issue by HollowayT** [a85/POSTMan-Chrome-Extension#4469]
## App Details:

```
Postman for Mac
Version 6.0.10
OS X 16.7.0 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there: Recently encountered
 2. Expected behaviour:  When a collection is selected by using the filter search to find it and a new request is saved to it, the request should immediately appear in the collection. The newly saved request won't appear in the collection until the filter is cleared and the collection is searched for again. This appears to be an issue only when the collection was selected via filter search. The new request appears when a collection is selected without using the filter search.
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app): No Logs
 4. Screenshots (if applicable)

1. Use the filter search to find any collection and select it
2. Create a new request and save it to the collection. 
3. The new request will not appear in the collection without clearing the filter search box and re-searching for the collection. 

A co-worker of mine using Version 5.5.2 on OS X 16.7.0 / x64 does not have this issue

**Comment by prashantagarwal** [comment]
@HollowayT We have fixed this internally. We will make it available with the next release.

**Comment by HollowayT** [comment]
@prashantagarwal Thanks for the quick response! Do you have an idea when the next release will be?

**Comment by prashantagarwal** [comment]
Most probably by the end of this month. Also we have already released this fix on our [canary app](https://www.getpostman.com/canary) , incase you want to check it out.
