### ISSUE TITLE
Multiple Client Certificate Same Port but different URL pattern

### ISSUE THREAD

**Issue by sskmail14** [a85/POSTMan-Chrome-Extension#4470]
## App Details:

```
Postman for Windows
Version 6.0.10
win32 6.1.7600 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there: this bug always been there
 2. Expected behaviour: Should support multiple client certificate with same port but different URL pattern

**Comment by sdnts** [comment]
Hi @sskmail14, This is the same as #4033, right? Please let me know if it isn't, and I'll reopen

**Comment by sskmail14** [comment]
oh ya the same one am looking for. Thanks :)
