### ISSUE TITLE
Set Request Parameter value

### ISSUE THREAD

**Issue by mrudul03** [a85/POSTMan-Chrome-Extension#4473]
## App Details:

```
Postman for Mac
Version 6.0.10 (6.0.10)
OS X 10.13.4 / x64
```

## Feature Request:
 Is it possible to set a POST request parameter with a custom value in pre-request script. For example - I want to set a request parameter with random number.

**Comment by dhineshwiz** [comment]
Hey @mrudul03, yes it is possible, create and set a environmental variable in pre-request script and use the same in request parameter. 

<img width="675" alt="screen shot 2018-04-19 at 5 22 16 pm" src="https://user-images.githubusercontent.com/10631268/38990001-4d104598-43f6-11e8-9723-71ec3111fc46.png">

For more information please refer [postman docs](https://www.getpostman.com/docs/v6/postman/environments_and_globals/variables)

**Comment by mrudul03** [comment]
Yes, I tried that. It works perfectly fine. Thanks a lot.
