### ISSUE TITLE
View Redirect request in Console

### ISSUE THREAD

**Issue by datha2703** [a85/POSTMan-Chrome-Extension#4474]
I am using Postman to submit request. Server responds with 

HTTP/1.0 302 Found
Location: https://services.****.com/di/***/ed36317f-8d77-4d62-9926-f9700bee9b6c
Server: ****
Connection: Keep-Alive
Content-Length: 0

Postman follows this redirect. I wish to see this new request in Postman console.

**Comment by sdnts** [comment]
Hi @datha2703, there's a switch called `Automatically follow redirects` in the Settings screen (Cmd/Ctrl+,), which you can disable to see the intermediate request.

<img width="740" alt="screenshot 2018-04-19 17 11 27" src="https://user-images.githubusercontent.com/7689783/38989534-d4b097fc-43f4-11e8-974c-1a171a560652.png">

I do see the value in showing intermediate requests in the Console directly though, so I'm going to add this as a feature request :)

**Comment by Gordiievskyi** [comment]
> Hi @datha2703, there's a switch called `Automatically follow redirects` in the Settings screen (Cmd/Ctrl+,), which you can disable to see the intermediate request.
> 
> <img alt="screenshot 2018-04-19 17 11 27" width="740" src="https://user-images.githubusercontent.com/7689783/38989534-d4b097fc-43f4-11e8-974c-1a171a560652.png">
> 
> I do see the value in showing intermediate requests in the Console directly though, so I'm going to add this as a feature request :)
Hi Siddhant,

I didn't get your comment. Question originally is about option to see the whole chain of redirects that happens. 
Automatically follow redirects: Prevent requests that return a 300-series response from being automatically redirected. 
If I am not mistaken,Automatically follow redirect setting is about stop of redirect chain  and not about display them or not.

**Comment by anzhurov** [comment]
Hello, @Gordiievskyi. Have you found the answer for your question??? I am interested in too

**Comment by ritwijsinha** [comment]
Hello @datha2703, @anzhurov and @Gordiievskyi.

This feature has been added in the new Postman Console. Please update to Postman v7.10 for this!

![image](https://user-images.githubusercontent.com/19693841/68192831-f978b600-ffd7-11e9-81c9-539378385796.png)

Cheers! 🎉
