### ISSUE TITLE
changing value of a local variable impacts value of environment variable (JSON)

### ISSUE THREAD

**Issue by NicoVerdonk** [a85/POSTMan-Chrome-Extension#4475]
## App Details:
Postman for Windows
Version 6.0.10
win32 10.0.16299 / x64

## Issue Report:
I'm wondering if I ran into a bug in Postman, or if this is by design.

I have a case in which I have 2 requests:
In request 1, I capture the full responsebody.
In request 2 (put) I need to provide the captured responsebody of request 1 as requestbody for request 2 but with a minimal change in certain booleans of the JSON body.

In additional requests (put) I do the same thing as in request 2. So again start from the captured responsebody of request 1 (without wanting to rerun request 1).

Therefore I used the following approach:

Request 1 - Test script:
`pm.environment.set("Filter-get_responsebody", pm.response.json());`

Request 2 - Pre-request script:
`var res_body = pm.environment.get("Filter-get_responsebody");`

`console.log(pm.environment.get("Filter-get_responsebody"));`
`//==>returns the full json response as captured in request 1 ==> OK`

`res_body.Filters[2].List[0].Checked = true;`
`console.log(pm.environment.get("Filter-get_responsebody"));`
`//==>returns the full json response but already with the updated boolean done in the var res_body ==> NOK`

`res_body.Filters[2].IsChanged=true;`
`console.log(pm.environment.get("Filter-get_responsebody"));`
`//==>returns the full json response but already updated by the 2 changes on var res_body==> NOK`

`pm.environment.set("ProductList-Put-SelectFirstFuelType-RequestBody",JSON.stringify(res_body));`

So in the pre-request script of request 2 my original environment variable (Filter-get_responsebody) gets an updated value although I am not directly altering its value. Instead on the first line I stored the environment variable value into a local script variable (res_body). Doing so allows me to reuse the original response body of request 1 in other requests.

So my question is: how come the environment variable gets an updated value while I am not directly altering it. Is this a bug in the postman scripting engine? I have setup a dummy test in which I had 2 request with the same approach, but instead of having a JSON object, I just used a string value to set and update in the environment variable. In that case, values are not overwritten. However, when updating the JSON (as in above described example), it overwrites the value directly in the environment variable.

**Comment by harryi3t** [comment]
@NicoVerdonk That's not a bug, it's by design. For your use case, you need to clone the output first before mutating it.
