### ISSUE TITLE
Cursor mismatch in text editor

### ISSUE THREAD

**Issue by numaanashraf** [a85/POSTMan-Chrome-Extension#4477]
originally reported via tweet - https://twitter.com/desidalek/status/987252394324086784

**Comment by parth115** [comment]
Postman : 6.0.10-1
Kernel : 4.14.34-1
i3wm : 4.15.0.1

Running on Manjaro Linux, postman installed from aur https://aur.archlinux.org/packages/postman/

Infinality patched fontconfig https://aur.archlinux.org/packages/fontconfig-infinality-ultimate

**Comment by prashantagarwal** [comment]
Duplicate of #2985
