### ISSUE TITLE
OpenAPI examples not showing up in application

### ISSUE THREAD

**Issue by daraul** [a85/POSTMan-Chrome-Extension#4479]
## App Details:

```
Postman for Linux
Version 6.0.10
linux 4.4.0-119-generic / x64
```

## Issue Report:
When importing a swagger file into Postman, my response examples aren't displayed in the application. 
 1. Did you encounter this recently, or has this bug always been there: encountered today, not sure if it's always been here
 2. Expected behaviour: response examples should show up as examples for the collection item
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 4. Screenshots (if applicable)
Request body example defined:
![image](https://user-images.githubusercontent.com/2440975/39085736-186b9fc6-4555-11e8-85fa-a8f7c26854ba.png)

Example added to response: 
![image](https://user-images.githubusercontent.com/2440975/39085712-b512959c-4554-11e8-8e19-0304d7f7dc93.png)

Imported as RAW text to postman (note, no examples on the top right):
![image](https://user-images.githubusercontent.com/2440975/39085724-fa20c780-4554-11e8-82a3-8a95882945ac.png)

If I'm doing this wrong, please let me know. I want to use postman to mock my backend while testing my frontends, but having to re-add existing examples every time I add new endpoints to my spec seems silly.

**Comment by abhijitkane** [comment]
@daraul We have example support for OpenAPI3 specs - you can import those if possible. We'll be updating the Swagger 1.2 importers too.
