### ISSUE TITLE
# Symbol cannot be entered in Key-Value Edit and Bulk Edit Method.

### ISSUE THREAD

**Issue by VinayJeurkar** [a85/POSTMan-Chrome-Extension#4481]
## App Details:

```
Postman for Windows
Version 6.0.10
win32 6.1.7601 / x64
```

## Current Behavior:

![image](https://user-images.githubusercontent.com/37448118/39109520-eb089524-46ea-11e8-8377-935702ca7ec9.png)

## Expected behavior:

"#2" value for the parameter "product_name_query" should appear in Key-Value Edit box.

### Steps to reproduce the problem
1. Create Post request and add any parameter.
2.  Try to type in the value "#2" for any parameter.

**Comment by sujayvenaik** [comment]
Hey @VinayJeurkar 

We are able to reproduce this at our end.
We are doing a complete refactoring around the tabs and its behavior that includes the request editing section as well.

Ill keep this thread updated as soon as we make a release.

**Comment by sujayvenaik** [comment]
https://github.com/postmanlabs/postman-app-support/issues/3208

Hey, @VinayJeurkar 
We have another thread which contains this same issue.
We will update that thread on the progress. Kindly refer to that.

Closing this for now.
