### ISSUE TITLE
Test negation leaks between tests in the same request

### ISSUE THREAD

**Issue by alexgmin** [a85/POSTMan-Chrome-Extension#4482]
## App Details:
```
Postman for Linux
Version 6.0.10
linux 4.4.0-119-generic / x64
```

## Issue Report:
![image](https://user-images.githubusercontent.com/8340441/39121535-39f3c80a-46f2-11e8-81ba-5f662537479d.png)

![image](https://user-images.githubusercontent.com/8340441/39121414-da708530-46f1-11e8-9e80-02517722dd28.png)

**Expected behavior:**
Test 1 and 3 pass. Test 2 fails.

**Actual behavior:**
Test 1 passes. Test 2 and 3 fail.

## Steps to reproduce the problem
```javascript
pm.test("Response is JSON", function () {
    console.log('Test1')
    console.log(pm.response.to.be)
    pm.response.to.be.json;
});

pm.test("Response is not JSON", function () {
    console.log('Test2')
    console.log(pm.response.to.not.be)
    pm.response.to.not.be.json;
});

pm.test("Response is JSON", function () {
    console.log('Test3')
    console.log(pm.response.to.be)
    pm.response.to.be.json;
});
```

**Comment by debjeetsarkar** [comment]
Hey @Alexgmin, thanks for pointing this out. This is a known bug and we are working towards resolving it.

**Comment by numaanashraf** [comment]
Related to #3592.
