### ISSUE TITLE
Clicking search icon should put focus in search box

### ISSUE THREAD

**Issue by jfren484** [a85/POSTMan-Chrome-Extension#4484]
## App Details:

```
Postman for Windows
Version 6.0.10
win32 6.1.7601 / x64
```

**Expected Behavior:**
When I click the Search Icon, the search box should appear and **focus should be given to the text box** so that I can immediately start typing what I'm searching for.

**Actual Behavior:**
When I click the Search Icon, the search box appears, but to enter anything into it, I have to click the text box before I start typing. You don't know how many times I've clicked the icon and started typing away only to realize my keystrokes are falling into the abyss. ;)

**Comment by prashantagarwal** [comment]
@jfren484 Are you referring to the icon in the status bar or in the sidebar.

**Comment by jfren484** [comment]
I'm referring to the search icon just above the large text box that holds
the response (there's also a Copy icon and, when a response is present, a
Save Response button).

[image: image.png]

**Comment by prashantagarwal** [comment]
@jfren484 If it is possible for you, can you try this on our canary app and check if it is still happening for you. You can download canary from https://www.getpostman.com/canary

**Comment by jfren484** [comment]
Sure, I'll try it out.

**Comment by jfren484** [comment]
It DOES work the way I would expect (and desire) in the canary app. Does
that mean it will be in an upcoming release?

**Comment by prashantagarwal** [comment]
Yes it will be there in next release. Thanks for verifying the fix.

**Comment by prashantagarwal** [comment]
@jfren484 We have released this with Postman v6.1.0
