### ISSUE TITLE
the bug of "add receive email of monitor "

### ISSUE THREAD

**Issue by water4168** [a85/POSTMan-Chrome-Extension#4486]
## App Details:

```
Postman for Window
 v6.0.10 
windows 10 / x64
```
## Issue Report:
1.sep up a monitor, select the "Receive email notifications for run failures and errors" and cancel and select again! you can see it auto creasing the nums of emailaddress
2.Screenshots (if applicable)
![image](https://user-images.githubusercontent.com/26303684/39169314-f4a8a774-47c9-11e8-889e-6ddd99acd039.png)

**Comment by prashantagarwal** [comment]
@walterliang This is fixed in Postman v6.1.0
