### ISSUE TITLE
Panel layout width requires scrolling to see entire page

### ISSUE THREAD

**Issue by md97212** [a85/POSTMan-Chrome-Extension#4487]
## App Details:

```
Postman for Mac
Version 6.0.10 (6.0.10)
OS X 16.4.0 / x64
```

I need to scroll left->right to see the entire Postman panel, ex I don't see any of the buttons that are aligned on the right margin unless I scroll to the right. Increasing the panel size doesn't help and zooming in or out doesn't help

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:
found in latest version
 2. Expected behaviour:
see the entire page without scrolling left or right
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):

 4. Screenshots (if applicable)
![screen shot 2018-04-24 at 3 57 29 pm](https://user-images.githubusercontent.com/1189243/39218210-5f9723a4-47d8-11e8-872a-2b0453fa7e63.png)
![screen shot 2018-04-24 at 3 59 00 pm](https://user-images.githubusercontent.com/1189243/39218230-72f619f0-47d8-11e8-8dd6-d4bd2b72ef85.png)

Open Postman, look at the page extents

**Comment by prashantagarwal** [comment]
@md97212 Did it happen only once for you or did the app opened in this state only. Is it possible for you to provide steps to reproduce this issue.

**Comment by chunkai-meng** [comment]
I have the same problem
