### ISSUE TITLE
[Packaged App] Response "Preview" tab cuts long responses

### ISSUE THREAD

**Issue by albertboada** [a85/POSTMan-Chrome-Extension#449]
When Response body is long enough, "Preview" tab won't let you scroll till the end of it. Not even when "Toggle size" is enabled!

![screen shot 2013-12-14 at 5 10 15 pm](https://f.cloud.github.com/assets/1840284/1748738/3e10d8b4-64da-11e3-9506-666a349a829a.png)

(There's a lot more text than that on the response, that is nowhere near the last line of it).

(MacOS 10.8)

**Comment by jlem** [comment]
I still have this issue, except my preview tab is only about 150px tall on OSX Mavericks - it's incredibly frustrating.

**Comment by a85** [comment]
@jlem This was fixed a long time ago. Can you link to an HTML page that is causing the issue? Also, which version are you on?
