### ISSUE TITLE
Postman taking lot of time to sync local data

### ISSUE THREAD

**Issue by shubsaini09** [a85/POSTMan-Chrome-Extension#4491]
## App Details:

```
Postman for Mac
Version 6.0.10
Windows x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there: Noticed recently
 2. Expected behaviour: Sync fast

Create a collection.
Export it as link, put it in browser and save the data somewhere.
Write a test case, save it and then again export it as link, put it in browser and save the data.
When both the data is compared, it is same whereas it should not. 

 

Postman app is taking a lot of time to sync with its own server. I see "Connecting" sign always.

**Comment by a85** [comment]
Closing as we are tracking performance issues in other threads. Sync performance is a constant work in progress.
