### ISSUE TITLE
Oauth 2 - Azure active directory - Missing 'resourceId'

### ISSUE THREAD

**Issue by sumadhuram456** [a85/POSTMan-Chrome-Extension#4496]
Hi,

As per the oauth2 azure active directory - client credentials authentication, it is necessary to pass an azure app URI in the 'resourceId' parameter in the https request. But the current oauth2 - client credentials authentication of postman do not have 'resourceId' parameter (Only 'scope' exist). So can you please enhance oauth2 - client credentials authentication to use azure active directory by adding this parameter.

Thanks in-advance.

**Comment by harryi3t** [comment]
@sumadhuram456 There is already an open feature request for this here https://github.com/postmanlabs/postman-app-support/issues/4391

Closing this in favour of the other ticket
