### ISSUE TITLE
importing swagger file doesn't import request parameter descriptions

### ISSUE THREAD

**Issue by jobec** [a85/POSTMan-Chrome-Extension#4499]
## App Details:
```
Postman for Windows
Version 6.0.10
win32 10.0.14393 / x64
```

## Issue Report:
 1. **Did you encounter this recently, or has this bug always been there:** Recently
 2. **Expected behaviour:** When importing a swagger file, the description of a query parameter is filled with the description from the swagger file.
 4. **Screenshots**

The example petstore swagger file has descriptions for it's parameters.:
![image](https://user-images.githubusercontent.com/16192496/39296547-800c725a-4941-11e8-8338-cb28354a1054.png)

After importing into postman, the description is empty.:
![image](https://user-images.githubusercontent.com/16192496/39296634-b49ba1e4-4941-11e8-86fa-afbcfca3e85c.png)

**Comment by sdnts** [comment]
Hi @jobec, thanks for reporting this. We are in the process of changing our importers and will take this up as part of that. Will let you know here when it is fixed :)

**Comment by jobec** [comment]
Great to hear 🎉 

You might want to look at #2857 also then as it's sort of related (but for POST body params)

**Comment by JerryChaox** [comment]
Is there any update for this problem?

**Comment by diegoernestofarias** [comment]
Hi, @a85 @abhijitkane @numaanashraf
Is there any update for this problem?
Automatically populate the parameters descriptions is a really useful feature!

**Comment by abhijitkane** [comment]
Everyone - The latest Postman version (7.2.1+) supports generating the request body from the Swagger 2.0 schema.
