### ISSUE TITLE
POST being sent as GET

### ISSUE THREAD

**Issue by obihill** [a85/POSTMan-Chrome-Extension#450]
I'm using your plugin to do a POST request. But it's send GET instead of POST.

It didn't do this before and I'm not sure why it's doing it now. I can't seem to find a version number of I would have sent it along.

Kindly advise.

**Comment by jdubjdub** [comment]
:+1: on the https redirect

**Comment by thornycrackers** [comment]
@Cryszon You just saved my day with that comment. Symfony's htaccess file was responsible for changing my posts to gets.

**Comment by DamirWallener** [comment]
I use 'http://requestb.in/' to validate requests sent by dashboard.py. It is definitely sending POST.
<img width="1061" alt="screen shot 2015-07-26 at 7 19 03 pm" src="https://cloud.githubusercontent.com/assets/12688219/8897494/64e678e2-33cb-11e5-9dd5-e39b02b8904d.png">

**Comment by assembledadam** [comment]
Had the exact same issue with http -> https!

**Comment by Bazarovay** [comment]
Well, it seems it happens whenever the url is changed. So if you make a post request to http://hostname through postman and the url changes to http://www.hostname, the post data will still be lost.

**Comment by SamiUrias** [comment]
I solved the problem writting "https://" before the url

**Comment by sdnts** [comment]
@SamiUrias In your case, it looks like `http` -> `https` redirects were set up. When redirecting, Postman will strip the POST body and forward the request as a GET to emulate browsers

**Comment by SamiUrias** [comment]
Thanks for your contribution @madebysid it is appreciated

**Comment by anshulgupta0411** [comment]
@rogierborst for me it was the other way round. It worked with trailing slash. Thanks for the input

**Comment by fgilio** [comment]
Omg, thank you guys for this. I was going crazy.

Just for the record:
I was using `https://domain.dev/endpoint/` and changed it to `https://domain.dev/endpoint`
So, I just removed the trailing `/`.

**Comment by iversa** [comment]
This is becoming funny. I had add the / at the end of the URL and then the POST started working again.

**Comment by ghost** [comment]
Same here! Started working after adding / at the end.

**Comment by jsonxr** [comment]
If you turn off "Automatically follow redirects" in the preferences, you will avoid all manner of this confusion inducing behavior.

**Comment by skys215** [comment]
In my case, it didn't send `X-Requested-With: XMLHttpRequest` in header, caused the framework thought that the request was come from a browser, instead of from an API. And the POST request was redirected to the HTML page rather then returning a JSON.
BTW, I'm using Laravel framework.

**Comment by azeredogab** [comment]
@rogierborst thanks for answer! Remove slash at the end of URL worked for me!

**POST**
```
http://api.domain.com/api/products/
```
to
```
http://api.domain.com/api/products
```

**Comment by Allakazan** [comment]
I had to add the slash in the end to POST work properly. LOL

**Comment by Deele** [comment]
This bug is still existing today in `app-6.1.4`. Why is this issue closed?

**Comment by MallikaKhullar** [comment]
It was indeed a redirect issue. Thanks guys for this thread, I was losing my mind.

**Comment by botjaeger** [comment]
hey, issue still persist.

testing route without trailing slashes, using http only

**Comment by novalic** [comment]
Using version 6.0.10  (i know it's not updated) I face the same issue when trying to send a DELETE request to a Django app. Testing it a bit, I found out that what it sends is a GET request.
**I solved this by adding a trailing slash.**

**Comment by numaanashraf** [comment]
Postman automatically changes POST to GET when it follows redirects. We do this to stay compliant with vendors and browsers. You can prevent the auto-follow of redirects by turning off "Automatically follow redirects" in Settings > General.
