### ISSUE TITLE
storing the column value(s) from CSV to an array in pre request script

### ISSUE THREAD

**Issue by swatthinan** [a85/POSTMan-Chrome-Extension#4500]
Hello,
I was trying to retrieve multiple values from a column in a CSV file to an array in postman.
I was able to do the same using JSON using JSON.parse. But not the same with CSV.
Is there a way I can achieve this?
Thanks,

**Comment by sdnts** [comment]
Hi @swatthinan, you should be able to get CSV data using the predefined variable `data` in pre-request scripts. Can you give that a shot and let me know if that works for you?

**Comment by swatthinan** [comment]
Hi @madebysid , thank you for response.
I did try with data and it is working fine to fetch a single value in an iteration
eg: var dcampusName = data.CampusName;
I am looking to fetch multiple data in a column of an excel to an array in my postman script so that i can loop in the data in the same session without running the collection on iteration basis.
Hoping to hear from you.

**Comment by harryi3t** [comment]
@swatthinan  You can use `csv-parse/lib/sync` as mentioned in this [doc page](https://www.getpostman.com/docs/v6/postman/scripts/postman_sandbox_api_reference)

![developer_tools__file____applications_postmanbeta_app_contents_resources_app_html_requester_html_and_postman](https://user-images.githubusercontent.com/5207331/39417041-2bf27120-4c6f-11e8-90e9-405c95254234.png)

**Comment by alexszarko** [comment]
Hi can you then use these variables to iterate a request?  Ie parsing the variables into a request, using them to assert in the response?
