### ISSUE TITLE
When exporting collection, GET requests should be stripped from any body in resulting json

### ISSUE THREAD

**Issue by zbstof** [a85/POSTMan-Chrome-Extension#4502]
## App Details:
```
Postman for Mac
Version 6.0.10
MacOS High Sierra 10.13.4  / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there: always
 2. Steps to reproduce:
- Create empty collection
- Add post request to collection, add body
- Export collection, inspect json - it contains body, as expected 
- Change request from POST to GET - body is disabled and not sent, save request
- Export collection, inspect json - request still contains body
3. Expected result:
When exporting GET request as part of collection, it shouldn't contain any body content

This bug causes some confusion, as version-control our collections in git, and sometime we produce new requests by copy-pasting existing ones

**Comment by sivcan** [comment]
@zbstof - Thanks for reporting this. We'll look into this issue and get back to you.

**Comment by Madsim** [comment]
I just encountered this myself. Because my POST request contains files as part of a form-data body and I duplicated it for my other requests, all my tests were failing in newman.

**Comment by numaanashraf** [comment]
@zbstof Body will no longer be exported if you select 'none' under Body tab.
