### ISSUE TITLE
Remove from workspace leads to lost of collection

### ISSUE THREAD

**Issue by simasch** [a85/POSTMan-Chrome-Extension#4503]
## App Details:

```
Postman for Windows
Version 6.0.10
win32 10.0.16299 / x64
```

## Issue Report:
I removed a collection from a workspace because I thought that I already added this collection to another workspace. But I was wrong.
Now when I try to open this collection i get:

> We can't seem to find this collection in any workspace
> This collection might have been removed by another user in your team.
> 

How do I recover this collection?

**Comment by sivcan** [comment]
@simasch - If you've removed this collection from the workspace - how exactly are you trying to open it? 
Is the collection still showing in the sidebar? 

Also, can you write to us at [help@getpostman.com](mailto:help@getpostman.com) with your query.
Thanks.

**Comment by simasch** [comment]
I can see the collection on this page: https://web.postman.co/me/collections
But when I click it then I get the error message.

Btw. it's weird that the action "Remove from Workspace" deletes the collection without warning that it will delete it.

Additionally I'm not happy some of the action I can do from the client app and some only on the web page. This is a terrible mix.

**Comment by sivcan** [comment]
@simasch - I guess you won't be able to see the collection after refreshing the page right?
Indeed it got removed from the workspace but not deleted.

You can head over to https://web.postman.co/me/collections and you'll find all collections that you've made. 
You can put the removed collection to a workspace by clicking 'Share'.

**Comment by preethammavin** [comment]
@simasch You can recover your collection by going to the All collection View in the dashboard, once you locate your collection the share it to the relevant Workspace.

Hope this helps.
Thanks

**Comment by xiaomingliu2** [comment]
I left a team workspace, resulting in the loss of a collection I Shared earlier. I could not see it anywhere. Is there any chance to restore it?

**Comment by sankalp0o** [comment]
@xiaomingliu2 if you left the team workspace, you can rejoin it and share the collection to a personal workspace.
If you left the team, your collection would still be with the team and the only way to access it is to ask them to add you back or export and send it to you.
