### ISSUE TITLE
 How to run docker for newman with environment and global json

### ISSUE THREAD

**Issue by saripr** [a85/POSTMan-Chrome-Extension#4504]
Running newman docker with json throws could not find the file even though the file exists in the path and the path is correct
App Details:

Version 6.0.10
newman 3.9.2

Postman for Ubuntu
Version 6.0.10
ubuntu 16.04 LTS

Issue Report:
Did you encounter this recently, or has this bug always been there:yes
Expected behaviour:Tests should run 
Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
Screenshots (if applicable)

Steps to reproduce the problem:
Tried adding docker for newman with below commands:

1.Pulling the image:docker pull postman/newman_ubuntu1404
2.docker run --name=“newman” -v /tests/apitest.json:/tmp/newman -t postman/newman_ubuntu1404 run “https://www.getpostman.com/collections/collectionId” --environment = ~/envt/staging.json --globals = ~/data/globals.json and it throws below error even tough the given path is right and json file is present in the path:

<p><b>unable to read data from file “~/environments/staging.json”
ENOENT: no such file or directory, open ‘~/environments/staging.json’ </b></p>

So how do I run docker for newman with environment and globals JSON

**Comment by sivcan** [comment]
@saripr - We maintain this repo for bugs or feature requests in the postman app.
For newman related issues you can visit the newman repo.

I have raised this issue here: https://github.com/postmanlabs/newman/issues/1514
