### ISSUE TITLE
Search Feature in title bar does not stop searching when anything is typed

### ISSUE THREAD

**Issue by kamransethi** [a85/POSTMan-Chrome-Extension#4505]
The search feature in the status bar never returns. Just keep searching indefinitely.
No search results are returned.

## App Details:
Version 6.0.10
win32 6.1.7601 / x64

## Issue Report:
1. Did you encounter this recently, or has this bug always been there: **Just noticed it. It used to work in previous versions.**
2. Expected behaviour: **Search used to work in a previous version. It should work as it says so in the online documentation.**
3. Console logs: **No new logs were created after the search was initiated.**
4. Screenshots (if applicable) **N/A**

## Steps to reproduce:
1.Open the search panel from the status bar
2.Search for postman or donald.
3,Notice that search keeps processing and never returns with any results

**Comment by ghost** [comment]
Hi @kamransethi 
Thanks for reporting the issue. The fix for the bug will be out in the next release. Stay tuned !

Cheers.
