### ISSUE TITLE
Plus sign not encoded, or encoded as space in get requests(v6.0.10)

### ISSUE THREAD

**Issue by P1llus** [a85/POSTMan-Chrome-Extension#4507]
## App Details:

```
Postman for Windows
Version 6.0.10
win32 10.0.16299 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:
Encountered it recently
 2. Expected behavior: 
Should be encoded as %2B, but is encoded as space instead
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-
 4. Screenshots (if applicable)

I saw this really old issue about this, but that was related to an much older version: https://github.com/postmanlabs/postman-app-support/issues/2579

Is there a version i can roll back to, to fix this? I already have several hundred tests created in the new collection, so would be hard to roll back..

**Comment by DanielPetatCes** [comment]
I reported this issue too:  #4444

**Comment by P1llus** [comment]
Oh i was sure i looked for it, must have missed it. Weird it never gets any comment, one would think it is a more serious issue..

Though for me, the GET request also supports POST in most functions so i can use that, and we should use POST anyway, but i can see this becoming an issue down the line.. And it was fixed in older versions

**Comment by SamvelRaja** [comment]
We are following a master thread #4555 to track all issues related to Url encoding. Please follow that issue for updates.
