### ISSUE TITLE
For Huge data request, I want to have my input in the form of external JSON file and indeed to re-place the entire body per iteration.

### ISSUE THREAD

**Issue by pchandrakanth** [a85/POSTMan-Chrome-Extension#4508]
## App Details:

```
Postman for Win7 /x64

```

## Issue Report:
 1. For Huge data request, I want to have my input in the form of external JSON file and indeed to re-place the entire body per iteration.
 2. Expected behavior: body of request, should able to replace by my variable when I run from Collections
 3. Screenshots : attached

## Steps to reproduce
1. My Json file in Collection runner as input data :
[{
"rename": {"AssetId": 5496,"NewName": "API-CK9-2st"},
"addfolderto": {"FolderId": 5456,"FolderName": "API-CK1"}
}]
2. And in My Pre-Request Script:

var envRename = pm.iterationData.get("rename");
pm.environment.set("rename", {{envRename }});

3. And in My Body, I'm trying to use directly the env. variable to replace body like :
{{rename}}

4. Then after running the script, my request body is replaced as:

Request Body:"[object Object]"
instead of my input json .

Please help me to resolve this, for Huge data request, I want to have my input in the form of external JSON file and indeed to re-place the entire body per iteration.

## Screenshot : 
![image](https://user-images.githubusercontent.com/29628017/39426446-84c91ce4-4c9d-11e8-85f1-126232c35bf7.png)

**Comment by shamasis** [comment]
We missed replying to this. I'm so sorry for that. But it looks like a quick fix. All we needed to do was `JSON.stringify` the variable before setting it. I just tried this and it works.

Similar to:
```
var envRename = pm.iterationData.get("rename");
pm.environment.set("rename", JSON.stringify(envRename));
```

Closing this. Down the line, we intend to support type-system on the variables. Then this stringification would also not be needed.
