### ISSUE TITLE
Bug: Menu elements render badly

### ISSUE THREAD

**Issue by DomHudson** [a85/POSTMan-Chrome-Extension#4510]
## App Details:
```
Postman for Linux
Version 6.0.10
linux 4.15.0-20-generic / x64
```

```
Ubuntu 18.04 LTS
```

## Issue Report:
Menu items with the new postman linux app appear rendered badly. I am unable to confirm if this occurred in older versions as I was previously using the chrome extension on Ubuntu 16.04 LTS. Happy to try old postman versions though, if it helps.

![screenshot from 2018-04-30 15-00-12](https://user-images.githubusercontent.com/10864294/39431062-7b2dcb28-4c87-11e8-906b-41954068b880.png)

![screenshot from 2018-04-30 15-02-38](https://user-images.githubusercontent.com/10864294/39431086-8e16e1e8-4c87-11e8-8901-22070c13eea6.png)

**Comment by rajamalw** [comment]
I am seeing the same issue in Kubuntu 18.04

**Comment by rajamalw** [comment]
Same issue in Gitkraken. Is this a Electron issue?

**Comment by rajamalw** [comment]
Seems to be rendering fine after the latest update.

**Comment by prashantagarwal** [comment]
@rajamalw Could be electron's issue. We have updated the electron version in Postman v6.1.0, which could have fixed this. Closing for now if all seems fine.

**Comment by DomHudson** [comment]
Yep thanks looks good now.
