### ISSUE TITLE
Request Description Doesn't Scroll When Viewing in Tab

### ISSUE THREAD

**Issue by gpattersonm** [a85/POSTMan-Chrome-Extension#4511]
## App Details:

```
Postman for Windows
Version 6.0.10
win32 10.0.17134 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there: I just noticed this issue.
 2. Expected behaviour: When looking at the request description from an open request tab, the description should scroll as necessary.

To reproduce, add a description to a request that is multi-lined such that it would require scrolling to get to the bottom of the description.

![image 25](https://user-images.githubusercontent.com/38870103/39453944-c08c4a4c-4c95-11e8-8320-98ee7190b7e2.png)

**Comment by prashantagarwal** [comment]
@gpattersonm Thanks for reporting this. We will get this fixed as soon as possible.

**Comment by prashantagarwal** [comment]
@gpattersonm For some reason I am unable to reproduce this. I can see scrollbar which can scroll the entire tab.

**Comment by gpattersonm** [comment]
Hello,

I was able to reproduce this just now. It seems that this is only an issue when in Two Pane view. As soon as I toggle to Single Pane View (Ctrl+Alt+V) I am able to see the scrollbar. I hope this helps.

**Comment by a85** [comment]
@gpattersonm Could replicate it: 

<img width="1792" alt="screenshot 2018-06-28 11 36 42" src="https://user-images.githubusercontent.com/653409/42053868-99a90950-7ac7-11e8-98be-925a03643ce4.png">

**Comment by sujayvenaik** [comment]
Hey @gpattersonm ,
This issue has been fixed and is available on the stable channel (v6.4.x).
You can update the app to the latest version.

Thanks again for writing in and reporting this issue.
