### ISSUE TITLE
Canonical download URL for all Linux releases

### ISSUE THREAD

**Issue by ghisvail** [a85/POSTMan-Chrome-Extension#4512]
I would be keen on providing a Flatpak packaging for Postman on Linux. To do so, I'd need to know the canonical URI where each new version of Postman is stored so that the build process can fetch the tarball in a reproducible manner.

I believe `https://dl.pstmn.io/download/channel/stable/linux_64` is a redirect to the latest tarball, right?

**Comment by dhineshwiz** [comment]
Hey @ghisvail thanks for feature request, however we are not doing this feature in near future.

**Comment by ghisvail** [comment]
> however we are not doing this feature in near future.

Sorry to insist, but how is that difficult to provide a direct path to where the tarball is hosted? I don't understand.

**Comment by ghisvail** [comment]
@prashantagarwal Could this be reconsidered please? All I need is a stable path to where the versioned tarball releases are stored. The rest of the packaging can be automated by `flatpak` easily.

**Comment by prashantagarwal** [comment]
@ghisvail we will definitely consider this. I have already linked this issue to the one we are planning to actively track. I don't have a timeline yet but I will anyways keep you updated about its progress.

**Comment by enguerran-popup** [comment]
@ghisvail I think you can use https://dl.pstmn.io/download/latest/linux64 or https://dl.pstmn.io/download/channel/stable/linux_64
I got a valid tarball with `curl https://dl.pstmn.io/download/latest/linux64 > postman-latest.tar.gz` so I think it would work with flatpack too.

**Comment by ghisvail** [comment]
@enguerran-popup, on my end `wget https://dl.pstmn.io/download/channel/stable/linux_64/Postman-linux-x64-6.1.3.tar.gz` yields a 404. I need a download URI to the **versioned** tarball.

**Comment by enguerran-popup** [comment]
@ghisvail Oh I see. I don't know how the Flatpak builder works but can't you use the url directly without adding the file name and get the file name by another mean? (https://dl.pstmn.io/download/latest/linux64 or https://dl.pstmn.io/download/channel/stable/linux_64)
Because you can get the versioned tarball name from the headers : `curl -X HEAD -i https://dl.pstmn.io/download/latest/linux64`
```
Warning: Setting custom HTTP method to HEAD with -X/--request may not work the 
Warning: way you want. Consider using -I/--head instead.
HTTP/1.1 200 OK
Content-Type: application/gzip
Content-Length: 64099775
Connection: keep-alive
Server: nginx
Date: Fri, 25 May 2018 15:56:16 GMT
Cache-Control: max-age=604800, s-maxage=604800
Content-Disposition: attachment; filename=Postman-linux-x64-6.1.3.tar.gz
Age: 322669
X-Cache: Hit from cloudfront
Via: 1.1 c4f265640b77f7a5516a99d1f2145456.cloudfront.net (CloudFront)
X-Amz-Cf-Id: P_P1S_gvSHTt59FEOt8PXyjuMrrsD9xLFyiJl_8T575PfgNlLXRVag==
```

**Edit :**
If it can help, you can download the file and get the correct filename automatically by doing : `curl -O -J -L https://dl.pstmn.io/download/latest/linux64` (curl 7.21.2 or newer) or `wget --content-disposition https://dl.pstmn.io/download/latest/linux64`

To get the filename only without having to download the file, you can use sed : `curl -sIkL https://dl.pstmn.io/download/latest/linux64 | sed -r '/filename=/!d;s/.*filename=(.*)$/\1/'`

**Comment by ghisvail** [comment]
@enguerran-popup Thanks for your assistance with this. I am gonna try what you suggested.

Do you happen to know whether there are builds provided for other architectures than `ia32` (linux_32) and `x64` (linux_64)?

**Comment by enguerran-popup** [comment]
@ghisvail I'm investigating if there's a way to get available versions or architectures. I didn't found anything atm but I found something else and it can be useful: you can specify a version by using this endpoint : `https://dl.pstmn.io/download/version/<version>/linux64`.
For instance `curl -O -J -L https://dl.pstmn.io/download/version/5.5.0/linux64` will download `Postman-linux-x64-5.5.0.tar.gz`

**Comment by ghisvail** [comment]
@enguerran-popup Looks like these are the only architectures. That's fine.

Are you guys already using a specific `appId` in your electon builds (similar to [here](https://github.com/jgraph/drawio-desktop/blob/461804cedff2c027aeb7cbe0882bc7fc684c6dea/electron-builder.json#L2)). If not, are you guys happy with `com.getpostman.Postman`?

**Comment by ghisvail** [comment]
Could you guys also let me know the path to an appropriate icon file for the application. It looks like none is provided in the release tarball. Thanks.

**Comment by enguerran-popup** [comment]
@ghisvail `/Postman/app/resources/app/assets/icon.png` :wink:

**Comment by ghisvail** [comment]
Yeah I messed up my find pattern, indeed:
```sh
>>> find Postman-linux-x64-6.1.3/ -name "icon.*"
Postman-linux-x64-6.1.3/Postman/app/resources/app/assets/icon.png
```

**Comment by ghisvail** [comment]
No .desktop file though?

**Comment by ghisvail** [comment]
It worked out in the end. Thanks for your help.
