### ISSUE TITLE
Duplicate parameter keys disappear when unchecked

### ISSUE THREAD

**Issue by Celadora** [a85/POSTMan-Chrome-Extension#4513]
When a parameter key is used more than once, and one is unchecked, the uncheckedone disappears. It would be more useful for it to be unchecked and remain, since if the client wanted to remove the parameter entirely they would use the remove button on the far right.

## App Details:
```
Postman for Windows
Version 6.0.10
win32 6.1.7601 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there: Encountered recently.
 2. Expected behaviour: I expect the parameter to not disappear when unchecked, only when removed.
 
##  Steps to Reproduce:
1. Enter the parameter key: "a", give it a value of "foo".
2. Enter the parameter key: "a" again, and give it a value of "1".
3. Make sure both are selected (meaning both are "checked").
4. Uncheck the first "a" parameter.

 At this point the first "a" parameter will disappear.

It would be preferable for the parameter to remain if the client has not chosen to remove the parameter (but has instead merely unchecked it).

**Comment by dhineshwiz** [comment]
Hey @Celadora, thanks for reporting the issues, We will get this fixed as soon as possible.

**Comment by sujayvenaik** [comment]
Hey @Celadora 
We have fixed this internally, and will be updated in canary and production app soon.

I'll keep this thread updated as soon as we release.

**Comment by sujayvenaik** [comment]
@Celadora 
Hi, we have addressed this issue as part of various improvements we have made to how tabs work in Postman. These changes are up available on our canary channel (https://www.getpostman.com/canary) today and would soon be available on the stable channel. Do try these out in the canary and let us know.

**Comment by sujayvenaik** [comment]
Hey @Celadora 
This issue has been fixed and is available on the stable channel (v6.4.x).
You can update the app to the latest version.

Thanks again for writing in and reporting this issue.
