### ISSUE TITLE
Postman Linux app installation error on Ubuntu 18 ( missing libgconf-2-4 package)

### ISSUE THREAD

**Issue by brunodles** [a85/POSTMan-Chrome-Extension#4514]
## App Details:

```
Postman for Linux
Version 6.0.10
Ubuntu 17.10 / x64
```
### uname -a
```
Linux inspiron 4.13.0-38-generic #43-Ubuntu SMP Wed Mar 14 15:20:44 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:
I'm migrating to native app
 2. Expected behaviour:
Simply open the Postman
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
```
./Postman error while loading shared libraries: libgconf-2.so.4: cannot open shared object file: No such file or directory
```
 4. Screenshots (if applicable)
Not applicable.

### How to reproduce the problem

1. Download tar
1. Extract it
1. Move to `postman` folder
1. Run `./Postman`

### Extra

When I try to run the postman I get this error
```
./Postman error while loading shared libraries: libgconf-2.so.4: cannot open shared object file: No such file or directory
```

Any of these pages contains the list of dependencies to run it.
* https://www.getpostman.com/docs/v6/postman/launching_postman/installation_and_updates
* https://blog.bluematador.com/posts/postman-how-to-install-on-ubuntu-1604/
* https://www.getpostman.com/apps

## How to solve
Just need to install `libgconf-2-4`
```
sudo apt-get install libgconf-2-4
```

### Sources
https://github.com/electron/electron/issues/1518

## Thanks
This is just a small report, thanks for the app.
You're great!

**Comment by dhineshwiz** [comment]
Hey thanks for reporting and workarounds, We will look into it

**Comment by barotashish** [comment]
Yesterday I do installation of Postman on my Ubuntu Linux 17.10 

-- 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=17.10
DISTRIB_CODENAME=artful
DISTRIB_DESCRIPTION="Ubuntu 17.10"
NAME="Ubuntu"
VERSION="17.10 (Artful Aardvark)"

-- uname -a
Linux ashish-barot 4.13.0-39-generic #44-Ubuntu SMP Thu Apr 5 14:25:01 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

-- Postman Version 
v1.6.16

**Comment by seantcanavan** [comment]
This is also an issue on Ubuntu 18.04. Just did a fresh install of 18.04 and was installing Postman.

`sudo apt-get install libgconf-2-4` fixed the issue.

**Comment by SamvelRaja** [comment]
@brunodles @barotashish  Recommending you guys to install `libgconf-2-4` as @seantcanavan  suggested.

**Comment by SamvelRaja** [comment]
Related to https://github.com/electron/electron/issues/1518

**Comment by SamvelRaja** [comment]
Closing this in ref to https://github.com/electron/electron/issues/1518#issuecomment-97708181

**Comment by joaoe** [comment]
The documentation is incorrect

https://www.getpostman.com/docs/v6/postman/launching_postman/installation_and_updates

It says `libconfig-2-4`. There is no such thing.

**Comment by BeatriceThalo** [comment]
installing from the software center instead of the tar works on ubuntu 18

**Comment by dwiyatci** [comment]
In my case (Ubuntu 18.10), in addition to `sudo apt install libgconf-2-4`, I need to do:

`sudo apt install libgtk2.0-0` 

in order to fix "error while loading shared libraries: libgtk-x11-2.0.so.0: cannot open shared object file: No such file or directory" error. :upside_down_face:

**Comment by Justin-Maxwell** [comment]
Just for search indexing:

Chromebook / Chrome-OS (v73) Crostini Linux 
`sudo apt install libgconf-2-4` fixes.

**Comment by saeidamini** [comment]
Arch base Linux installs `gconf` package solved the problem.
`sudo pacman -S gconf`

**Comment by ehtishamqureshi2013** [comment]
└─# sudo apt install libgconf-2-4
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package libgconf-2-4
