### ISSUE TITLE
OAuth 2.0 access tokens and environment variables substitution problem

### ISSUE THREAD

**Issue by davidthompson** [a85/POSTMan-Chrome-Extension#4516]
## App Details:
```
Postman for Windows
Version 6.0.10
win32 10.0.16299 / x64
```
## Issue Report:
When requesting a new OAuth 2.0 access tokens and using environment variables I am encountering an issue with using variables in the token name. If I enter the variable in the field, as per the below screenshot

![image](https://user-images.githubusercontent.com/1193010/39520780-c8f1ad66-4e03-11e8-9ee6-e16aef69c369.png)

When the token is retrieved and then displayed in the list of available tokens, the value of the variable isnt being used instead the variable name is, as shown below.

![image](https://user-images.githubusercontent.com/1193010/39520806-e033a0ec-4e03-11e8-90fe-1c6a23f9484a.png)

I don't appear to have any issues with using the environment variables in any other part of the token request.

The environment variables are setup as the following screenshot
![image](https://user-images.githubusercontent.com/1193010/39521006-a05c6b24-4e04-11e8-8a5a-59a4affab935.png)

**Comment by dhineshwiz** [comment]
Hey @davidthompson, Currently we are not supporting variables in token name, I think highlighting of variables in token name create confusion. I will add that as bug, and we will fix it soon.

**Comment by ChangeTheCode** [comment]
Is there any way to create this call via a "normal" postman request? So there is no user interaction needed. An Example is to automate the postman collection via newman. 

Would be very nice if there is anyone with an idea

**Comment by prashantagarwal** [comment]
@ChangeTheCode You can try using it pm.sendRequest in pre-request scripts.
