### ISSUE TITLE
Use regex or Any value in URL path for Mock server

### ISSUE THREAD

**Issue by ricardorlg** [a85/POSTMan-Chrome-Extension#4517]
## App Details:

```
Postman for Windows
Version 6.0.10
win32 10.0.15063 / x64
```

## Issue Report:
Hi, Is possible to use in mockserver regular expresions to matching algorithm?, I mean, I have a request that adds a random integer to the end of the path, I don't have acces to that number, what I want is to create a mock server in postman that use as example a request that has a regex at the end, so when my app sends the request to the mock server this can handle it.

**Comment by dhineshwiz** [comment]
Hey @ricardorlg , currently its not possible to do dynamic response from the mockserver

**Comment by ratpik** [comment]
@ricardorlg - It is possible to satisfy your use case. Regex handling for certain use-cases is implicitly built into the request matching algorithm. So if you have a saved example with a path like `/api/user/1` and your request url at the time of testing happens to be `/api/user/345`, then that will match with `/api/user/1`. This behavior also extends to scenarios where the ids are detected to be uuid/guid.

We are working on improving mock servers to give our users more control over how requests are matched.
