### ISSUE TITLE
Setting global variables does not work without an account

### ISSUE THREAD

**Issue by vdespa** [a85/POSTMan-Chrome-Extension#4518]
It seems that setting global variables does no longer work if you are not logged in.

```
pm.globals.set("foo", "bar");
```

## App Details:
```
Postman for Mac
Version 6.0.10 (6.0.10)
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there: recently, probably since the introduction of workspaces
 2. Expected behavior: globals should be saved

**Comment by prashantagarwal** [comment]
@vdespa We will investigate this and keep you updated about the progress.

**Comment by sivcan** [comment]
@vdespa - Thanks for reporting this.
We've fixed this issue internally and will update this thread once the fix is out.

**Comment by vdespa** [comment]
Great, thank you for the quick reply.

**Comment by sivcan** [comment]
@vdespa This has been fixed in the latest release i.e **v6.1.2**
Kindly update to the same.
