### ISSUE TITLE
Runner 400 Bad Request when posting CSV data file

### ISSUE THREAD

**Issue by v1g0rous** [a85/POSTMan-Chrome-Extension#4519]
Postman for Windows
Version  v6.0.10
Windows 10 / x64

Hello! I'm experimenting with uploading CSV data file using API.
I'd like to use Postman to post articles containing basic html tags (e.g urls) and line breaks. Here I faced some difficulties... 
My body request looks like this:
![request body](https://user-images.githubusercontent.com/30531467/39547187-75043e4c-4e5f-11e8-9553-d77bd873a2bc.PNG)
It works great if my CSV file looks like this one:
`{ "title": "How can I refill my account?", "description" : "test article", "type" : 1, "status": 2}`

But if I have some URLs inside or line breaks it shows 400 Bad request and says "Request body has invalid json format".

And by the way - it looks pretty well in "Preview", but still doesn't work:
E.g. I'd like to post something like this:
![postman csv preview](https://user-images.githubusercontent.com/30531467/39547368-0d44e72e-4e60-11e8-8e86-43494586390a.PNG)
`"title","description","type","status"
"How can I refill my account?","You can choose your preferred method of replenishing your account <a href=""https://blablabla.org/fx/paymean_list?simple_payment=off""> in your account </a>
(https://blablabla.org/fx/paymean_list?simple_payment=off). At the moment the following methods are available:

Bank transfer
Bank card

If you use the mobile application, switch to the Purse tab and then select ""Refill account"". Next, you need to choose a convenient method of payment for you.","1","2"`

Could you kindly give me a hint? I've tried to change text encoding or use JSON data file, but without success.

**Comment by prashantagarwal** [comment]
@Toradora270291 Thanks for reporting this. We will investigate this and keep you updated about the same.

**Comment by numaanashraf** [comment]
@Toradora270291 Postman does text replacement of the final raw string while replacing the variables. It looks like url and new-lines in the CSV can lead to the final JSON being invalid in your use case. The current recommendation is to make sure that you are passing in the correct encoded values in the CSV so that the final request payload is valid.
