### ISSUE TITLE
Copy as CURL

### ISSUE THREAD

**Issue by juliomenendez** [a85/POSTMan-Chrome-Extension#452]
Would be great of the request could be copied to the clipboard or shown in an input as the full CURL command line. Something like Chrome DevTools does.

**Comment by vool** [comment]
+1

**Comment by rbwendt** [comment]
You can just open the network tab in your chrome console and use copy as curl there. The network tab logs postman requests.

**Comment by fsamir** [comment]
@rbwendt how to you open chrome web tools in the Postman plugin? It doesn't let me open it in the standalone post man plugin window.

**Comment by drew-smithies** [comment]
Currently in the packaged app, you can click the "</>" icon. There you can choose to generate a code snippet in different languages.

**Comment by aarontharris** [comment]
@benchwarmer awesome!

**Comment by mickhan** [comment]
@benchwarmer  cool!

**Comment by mmmattos** [comment]
Thks, @benchwarmer !
That was exactly what I needed.

**Comment by thn929** [comment]
> Oh you can also enable the dev console as explained here: http://blog.getpostman.com/index.php/2014/01/27/enabling-chrome-developer-tools-inside-postman/

Is this `</>` icon still working in Postman 7.35.0? I see the icon there, but it doesn't seem to do anything for me.
![image](https://user-images.githubusercontent.com/2157687/101525026-5b7cbb00-3950-11eb-96bd-cb2c7205877c.png)

**Comment by drew-smithies** [comment]
@thn929 Now it's just a text link that says "code" below the Save button. No need to open the dev console.

![image](https://user-images.githubusercontent.com/5829521/103948130-e3e0ae00-50fe-11eb-9e64-765cfd756f9a.png)

**Comment by SHI-ZP** [comment]
Hi @drew-smithies,

Sometimes, a certain API relies on another API's output, which leads to a situation that a single postman request contains several HTTP requests.

As an independent tester, the dev mates want me to provide the raw cURLs of all the HTTP requests letting them reproduce the failure in their handy local environments. 

So I am wondering that is there a built-in method to get all the cURLs of the whole Postman Request from the postman UI or even newman?

Thanks for the help.
