### ISSUE TITLE
Feature Request: Ability to Execute Examples in Postman

### ISSUE THREAD

**Issue by govindrai** [a85/POSTMan-Chrome-Extension#4526]
Currently, we can save different examples of a req/res for each postman request. Quite often, depending on my task, I want to be able to actually run those examples. Currently, every time I have to test a request which is an example, I have to go into the example, copy and paste the request body, into a new window, and test it. 

I know I can easily create 4 requests different requests for the four 4 different examples, but imo that is a huge setback to what this examples feature could be. Even more, these four different examples only differ in the body that I send over, so it doesn't really make sense to create separate requests. 

So here's my request: What would be really neat if request examples could be runnable, and they could appear in the left sidebar categorized under request which is linked to those examples.

Here's a super ugly mock:
<img width="1792" alt="screen shot 2018-05-04 at 1 05 12 pm" src="https://user-images.githubusercontent.com/13859249/39650514-3d8a309a-4f9d-11e8-901a-6464bae6d34f.png">

**Comment by numaanashraf** [comment]
Thanks for the suggestion @govindrai

**Comment by numaanashraf** [comment]
Duplicate of #3694
