### ISSUE TITLE
Export CSV and show prompt Save As...

### ISSUE THREAD

**Issue by QuangMuop** [a85/POSTMan-Chrome-Extension#4530]
Hi Postman friends, I have an issue when export CSV that it automatically save CSV to my code project folder, but not show the prompt "Save As" as expect. the code like this:

```
response.setContentType("text/csv");
response.setHeader("Content-Disposition","attachment; filename=Download.csv");
```

When I export PDF, the showing of "Save As" prompt is ok with: `response.setContentType("application/pdf");`

How could Postman export CSV and show prompt "Save As"? 
Thank you so much!

**Comment by dhineshwiz** [comment]
Hey @QuangMuop , I could able to see save prompt on exporting csv file, 
<img width="826" alt="screen shot 2018-05-07 at 6 09 34 pm" src="https://user-images.githubusercontent.com/10631268/39702350-23faff88-5222-11e8-83af-5dfd46977520.png">

I have created the mock server with above headers,
<img width="908" alt="screen shot 2018-05-07 at 6 10 36 pm" src="https://user-images.githubusercontent.com/10631268/39702380-4022ed92-5222-11e8-91af-20fc2dfc9505.png">

The download response as file click send and download on postman-app, for details please refer this docs,
https://www.getpostman.com/docs/v5/postman/sending_api_requests/responses?q=&idx=blog&p=0&is_v=2
