### ISSUE TITLE
Cannot find module 'csv' error while csv is used.

### ISSUE THREAD

**Issue by swatthinan** [a85/POSTMan-Chrome-Extension#4532]
Hi,
When i tried to run the below code, i am getting "Cannot find module 'csv' " or " ReferenceError: csv is not defined" 
```js
var parse = require('csv-parse/lib/sync');
var obj = csv();
function MyCSV(abc, xyz, lmn) {
    this.FieldOne = abc;
    this.FieldTwo = xyz;
    this.FieldThree = lmn;
}
var MyData = [];
obj.from.path('C:/Newfolder/Test.csv').to.array(function(data){
    for(var index =0; index < data.length; index++){
        MyData.push(new MyCSV(data[index][0], data[index][1], data[index][2]));
    }
    console.log(MyData);
})
```
Could someone please help me with this?

Regards,
Swathi

**Comment by kunagpal** [comment]
@swatthinan I've updated your code snippet to make it easier to read. As for the ReferenceError, this is an actual issue with your snippet, as `csv` isn't defined before being used. You can directly use the `parse` instance defined on the first line, as follows: `parse('CSV content', options);`, where options is an object of options.

For more details, you'd want to take a look at  http://csv.adaltas.com/parse/#sync-api for sample usage. Also, the second half of your snippet uses a file reference to `C:/Newfolder/Test.csv`. Reading from files is not supported within the Sandbox for the reasons of security. You'll have to fetch this file from a URL, and then pass the raw CSV response to the parser.

**Comment by swatthinan** [comment]
Thanks @kunagpal! I shall try again with all the points you have mentioned. 
I am sure it will be helpful.
