### ISSUE TITLE
[Windows] Postman crash on send and download

### ISSUE THREAD

**Issue by romaromaniv** [a85/POSTMan-Chrome-Extension#4535]
Please read through the [guidelines](https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues) before creating a new issue.

**Describe the bug**
Postman application crashes.

It looks like 
![image](https://user-images.githubusercontent.com/28062488/39702893-f037660e-520e-11e8-99f7-9510f5f930ce.png)

**To Reproduce**
1. Select postman test which expects to receive pdf file (about 4 Mb size) and click 'Send and Download'
2. BitDefender security tool should be runned
3. Wait while api working and see crash (probably after receiving callback from api)

EventViewer shows me only this

Faulting application name: Postman.exe, version: 1.6.16.0, time stamp: 0x5a667119
Faulting module name: KERNELBASE.dll, version: 10.0.16299.371, time stamp: 0x6369e29f
Exception code: 0xe0000008
Fault offset: 0x0000000000014008
Faulting process id: 0x2404
Faulting application start time: 0x01d3d17487761d71
Faulting application path: C:\Users\Roman\AppData\Local\Postman\app-6.0.10\Postman.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: be862598-5051-4d47-90a2-e339dac6c719
Faulting package full name: 
Faulting package-relative application ID:

***
This is native app,
OS:
![image](https://user-images.githubusercontent.com/28062488/39703176-db9265ea-520f-11e8-91b8-44a8d051ca2f.png)

What I can provide yet for issue investigation?

**Comment by dhineshwiz** [comment]
Hey @romaromaniv  thanks for reporting, we will look into it

**Comment by romaromaniv** [comment]
Just next event viewer piece of information.

In this case postman just dissapeared(

***
Faulting application name: Postman.exe, version: 1.6.16.0, time stamp: 0x5a667119
Faulting module name: KERNELBASE.dll, version: 10.0.17134.1, time stamp: 0x701ca188
Exception code: 0xe0000008
Fault offset: 0x000000000003f218
Faulting process id: 0x8f8
Faulting application start time: 0x01d3e857d111a6e7
Faulting application path: C:\Users\Roman\AppData\Local\Postman\app-6.0.10\Postman.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 10a91a9b-0170-445a-bdbe-b9e2d2e072cf
Faulting package full name: 
Faulting package-relative application ID:

**Comment by SamvelRaja** [comment]
@romaromaniv  any memory usage spike before the crash? 
I would recommend you to open the app through `cmd` from 'c:\users\[USER]\AppData\Local\Postman\app-6.1.4\Postman.exe' this will show the internal logs from it.

**Comment by SamvelRaja** [comment]
@romaromaniv  You had a chance to look at this to find the logs for us?

**Comment by romaromaniv** [comment]
Hi SamvelRaja,

as for today I may say, that issue is obsolete.

I'm using download file per request functionality very often and after one of update (postman or windows) everything works fine. I did not do any spike.  Will use internal logs next time for similar issues, thank you for hint!

Regards,
Roman

**Comment by SamvelRaja** [comment]
Thanks @romaromaniv for getting back to us. Closing this issue for now. Feel free re-open the issue when you face again.

**Comment by romaromaniv** [comment]
Thanks a lot!
