### ISSUE TITLE
Exec tests on captured calls

### ISSUE THREAD

**Issue by andreipaz** [a85/POSTMan-Chrome-Extension#4538]
Hi guys,

First of all, Postman rocks! 

I'm currently working on building and consuming an API at work, and I'm trying to develop some workflow of API Testing with Postman, but I'm not certain if what I'm imagining is possible. I've really searched about, but I really did not find an exactly answer -- if it's possible or not. 

I'd like to intercept the requests that my application make to my api enpoints (previously added in my postman), but I also want to run the defined tests when the intercepted route matches with an endpoint in my collection. 

I know that there's more than one way to intecept the api calls with postman, but there's some way to exec tests on it?

**Comment by kamalaknn** [comment]
Hi @andreipaz 

If you want to run tests on API you can take a look at our hosted service for [monitoring](https://www.getpostman.com/tools#api-monitoring) or the [free CLI tool](https://www.getpostman.com/docs/v6/postman/collection_runs/command_line_integration_with_newman)

You can also visit our [community forum](https://community.getpostman.com/) for more help.

I'm closing this as this is not an issue with the Postman App itself. Feel free to use the community forum any further discussions.
