### ISSUE TITLE
upgraded account and not able to edit old monitor

### ISSUE THREAD

**Issue by bj97301** [a85/POSTMan-Chrome-Extension#4539]
Please read through the [guidelines](https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues) before creating a new issue.

**Describe the bug**
I upgraded my account and can no longer access my old monitors but still get error alerts via email for them.  

**To Reproduce**
1. Upgrade your account using a trial code thingy
2. Kill your api 
3. Wait for monitor(s) to run
4. Get an email with a link
5. Click the link

**Expected behavior**
Able to go to the monitor's page

**Actual behavior**
Shows an error saying: We can't seem to find this monitor in any workspace

**Screenshots**
![screen shot 2018-05-08 at tuesday may 8 2018 3 22 pm](https://user-images.githubusercontent.com/1450431/39786067-a222bdea-52d3-11e8-8c3e-03e611c85035.png)

**App information (please complete the following information):**
chrome web page
web site
osx latest version: 10.13.4 (17E202)

**Comment by godfrzero** [comment]
This is a bug we're actively working on fixing, I'll post an update here once we've pushed a fix for this.

**Comment by abhijitkane** [comment]
@godfrzero Any updates on this?

**Comment by godfrzero** [comment]
Closing as this shouldn't be happening anymore.
