### ISSUE TITLE
@set account is not displaying error message like username already exist

### ISSUE THREAD

**Issue by Akumzy** [a85/POSTMan-Chrome-Extension#4540]
Trying to create a new username but the username is taken already but no feedback apart from ajax response through devTool network

**Screenshots**
![screenshot from 2018-05-09 08-29-37](https://user-images.githubusercontent.com/25849232/39801699-fb3ee4d6-5363-11e8-8e19-4615129c6b31.png)

**App information:**
 - App Type [Native App]
 - Postman Version [6.0.1]
 - OS: Ubuntu 17.10]

**Comment by thecuriousdev** [comment]
@Akumzy thanks for reporting this issue, This issue is no longer there in our latest version (6.1+) of Postman app.
