### ISSUE TITLE
"New Request" in a collection

### ISSUE THREAD

**Issue by AntoniusGolly** [a85/POSTMan-Chrome-Extension#4541]
I love working with Postman and I use collections extensively. However, one thing annoys me. If I want to add a request to an existing collection I have to do it via  New -> Request -> (in Modal) select collection. 
This selection is a three-lined list, very hard to browse through with my many existing collections. I know I can use a search there. But there would be a way easier way to do this. Why not have an entry in the context menu of each collection named "create request"? The context menu is very long an contains a lot of useful links. This one (add request) is missing.
![unbenannt](https://user-images.githubusercontent.com/3856505/39806121-5a3b660c-5379-11e8-925f-a40e0bf68792.png)

**Comment by kamalaknn** [comment]
hi @AntoniusGolly 

Thanks for your feedback. I'm marking this as a feature request. We'll consider this in our upcoming releases.

**Comment by sivcan** [comment]
Hey @AntoniusGolly,
We've released this on our canary channel.
You can download the canary build here: https://www.getpostman.com/canary and test it out.

Thanks!
