### ISSUE TITLE
Requests in Postman Console include disabled headers

### ISSUE THREAD

**Issue by mikem** [a85/POSTMan-Chrome-Extension#4542]
## Summary

In the Postman Console, request headers are listed even if they are not checked in the UI.

## Steps To Reproduce

1. Open the Postman Console
2. Open a GET request, make sure it has a request header in it
3. Make the request, then view it in the Postman Console and note that the request header is present
4. Disable the header by removing the check in the check box in front of the request header
5. Repeat the request
6. View the second request in the Postman Console

**Expected behavior:** the second request in the console does not display the disabled header.

**Actual behavior:** the second request in the console **does** display the disabled header.

## Screenshots

Here is a request with the header sent (check box ticked). On the right, in the Postman Console, you can see the header is present. Note that the header also appears in the response body.

<img width="1440" alt="request-with-header" src="https://user-images.githubusercontent.com/62569/39819461-176a426e-53d6-11e8-8467-e8e48f1631bc.png">

Here is a request with the header not sent (check box not ticked). On the right, in the Postman Console, you can still see the header. Note, that the header does not appear to actually be sent; it's missing from the response body.

<img width="1440" alt="request-without-header" src="https://user-images.githubusercontent.com/62569/39819478-2129d7d8-53d6-11e8-8948-6236a982e2bc.png">

## App information

 - App Type: Native App
 - Postman Version: 6.0.10
 - OS: macOS High Sierra 10.13.4

**Comment by dhineshwiz** [comment]
Hey @mikem thanks for reporting, I could able to reproduce it. There is already opened issue for this issue https://github.com/postmanlabs/postman-app-support/issues/3302

**Comment by mikem** [comment]
Thanks @dhineshwiz, I subscribed to that one and will follow its progress.
