### ISSUE TITLE
Not able to reorder the last tab

### ISSUE THREAD

**Issue by alvarolorentedev** [a85/POSTMan-Chrome-Extension#4544]
**Describe the bug**
Not able to reorder the last tab drag and dropping it in a different order.

**To Reproduce**
1.  Open multiple tabs
2. swap some of them not the last one
3. try to move the last tab
4. last tab will not move

**Expected behavior**
Be able to reorder the last tab same as the rest

**App information (please complete the following information):**
 - App Type Native App
 - Postman Version 6.0.10
 - OS: macOS High Sierra 10.13.2

**Comment by dhineshwiz** [comment]
Hey @kanekotic , just tried swapping the last tab, it was working fine. I couldn't reproduce this case.
I think you are trying move a tab to last, which is not possible. Instead drag the last tab to desired position

**Comment by alvarolorentedev** [comment]
yep, you are right...sorry on the steps to reproduce the error 😞 . fast question, why is this not possible?
