### ISSUE TITLE
Import of team collection to My Workspace deletes Team collection

### ISSUE THREAD

**Issue by jgroom33** [a85/POSTMan-Chrome-Extension#4545]
**Describe the bug**
The Team collection is deleted.

**To Reproduce**
1. Create Team collection
2. Generate `Run in Postman` button
3. Navigate to My Workspace
4. Click `Run in Postman` button
5. Choose to 'replace' collection
6. Notice Collection from Team is missing

**Expected behavior**
Import into My Workspace should not provide option to overwrite.  It should be imported as 'Copy' automatically.

**App information (please complete the following information):**
 - Native
 - Postman Version 6.0.1
 - OS: macOS High Sierra 10.13.2

**Comment by prashantagarwal** [comment]
@jgroom33 Thanks for reporting this. We will get this fixed in one of the future releases. I will keep you updated about it.

**Comment by jgroom33** [comment]
It appears that the Collection name is used as a uuid across workspaces.  imo, if there is to be a shared uuid across workspaces, it should be the collection id.  But ideally, a workspace should be able to have duplicated names and id's across workspaces.

**Comment by thecuriousdev** [comment]
@jgroom33 we fixed this issue in the latest version of Postman Canary. Please verify it once from your end.

Closing this issue for now, feel free to reopen this if you are facing the same issue.
