### ISSUE TITLE
Run monitor API throw parentMissingError error

### ISSUE THREAD

**Issue by bitzip** [a85/POSTMan-Chrome-Extension#4548]
I followed the [API document](https://docs.api.getpostman.com/#5b277ca0-7114-e04e-f1f5-246fbbd6d973) to run a monitor, it throw a weird error saying parentMissingError. And I google `parentMissingError` nothing related was found ☹️.

## Screenshots
![image](https://user-images.githubusercontent.com/4319332/39909773-cd2f0f20-5526-11e8-912a-26dbb21b93c9.png)

**Comment by ankit-m** [comment]
Hey @kelly-apollo,

Can you please email us at help@getpostman.com with the `monitor_uid`?

**Comment by bitzip** [comment]
@ankit-m Sent already. Please check.

**Comment by abhijitkane** [comment]
Closed due to inactivity on the support ticket
