### ISSUE TITLE
International characters in URL path not encoded correctly with PUT requests

### ISSUE THREAD

**Issue by jesperhoy** [a85/POSTMan-Chrome-Extension#4549]
For example issuing a PUT request to http://example.com/æøå.html

The 3 danish characters in URL sent to the server are encoded in some unknown format - two bytes per character (perhaps UTF-16 ?) by Postman.

If you open the same URL in a browser, the 3 danish characters are correctly UTF-8 encoded and then percent-escaped, so that the server sees:
http://example.com/%C3%A6%C3%B8%C3%A5.html 

The correct encoding is described here: https://www.w3.org/International/articles/idn-and-iri/

This happens on Windows 10 with "Postman for Windows" version 6,0,10,

**Comment by prashantagarwal** [comment]
@jesperhoy Can you try sending this request http://postman-echo.com/get?url=http://example.com/æøå.html. This is working correctly for me and the url is being encoded as http://example.com/%C3%A6%C3%B8%C3%A5.html

Is there some screenshot that you can attach. Thanks

**Comment by jesperhoy** [comment]
Getting an empty response (0 bytes) - see attached screen shot.
Perhaps that echo function doesn't work with PUT ?

![image](https://user-images.githubusercontent.com/12099212/39983149-f0b89b5a-5756-11e8-9eb1-ee618658d2b8.png)

Tried setting up a simple console program to catch the raw request bytes:
![image](https://user-images.githubusercontent.com/12099212/39983829-4dbb02aa-5759-11e8-94c5-7aa0d959d1df.png)

Actually the problems appears to be the same with GET:
![image](https://user-images.githubusercontent.com/12099212/39983898-9b4d1eae-5759-11e8-9fff-a0cd6cd6c0bc.png)

As you can see, the URL is not encoded at all.

**Comment by harryi3t** [comment]
@jesperhoy You are getting 404 coz the endpoint is invalid. Either use `http://postman-echo.com/get` with request type `GET` or use `http://postman-echo.com/put` with request type `PUT`
Here's a screenshot showing the response using correct endpoint

![postman](https://user-images.githubusercontent.com/5207331/40534471-c31d7564-6023-11e8-9634-4086133e8e32.png)

**Comment by jesperhoy** [comment]
This issue is about the actual raw bytes sent out by the Postman app. When the request bytes are captured (as shown in my earlier post) it clearly shows that international characters are NOT percent-encoded.

Please don't dismiss this because that echo function tells you something else - that is NOT what actually happens - at least not here.

**Comment by prashantagarwal** [comment]
@jesperhoy We are tracking all these encoding decoding issues in #4555 . I will keep you updated about this anyways.

**Comment by shamasis** [comment]
@jesperhoy we have made progress in this front. More details at https://github.com/postmanlabs/postman-app-support/issues/8154

**Comment by shamasis** [comment]
@jesperhoy just tested with new URL processor on Canary. The URL `https://httpbin.org/anything/æøå.html` now gets sent as `https://httpbin.org/anything/%C3%A6%C3%B8%C3%A5.html`

**Comment by codenirvana** [comment]
This is fixed in the latest version of the Postman app (v7.20.0) by enabling the "Use next generation URL processing" setting as mentioned in #8154.
