### ISSUE TITLE
POST with form-data with file option appears to send empty body on 1st request

### ISSUE THREAD

**Issue by stevemcmillen** [a85/POSTMan-Chrome-Extension#455]
I have an API saved that is configured with binary type by default.  When I post a file using the binary option it works fine.  But if I change it to form-data and try to upload a single file, The amount of data that was specified in the POST request is different from what is actually sent.  Only 44 bytes of data are sent.  The request fails because our server is told that it should be getting a different size (the size of the file plus data I think).  I can then submit the request a 2nd time and the actual file I referred to is sent.  The file that I ad set is cleared out in the form.  I can then set the file again and submit a 2nd time and it sends the full file but also get the invalid size error from our server.  

I tried making sure to change some values to see if it was just some sort of "on change" value not getting set in the UI but this did not help.  It still submits only 44 bytes until the 2nd time I press Send.

Note: In both cases above, there is a Content-Type header set explicitly in the list of headers.

If I take out the Content-Type header, the 1st request goes with only 44 bytes of data and fails same way - server expected a different size than was sent.  The 2nd request gets the full file sent and works but since I've already uploaded 44 bytes from 1st request the request fails - I think this send set of tests is invalid since our server is likely assuming application/octet-stream.

Note: I have another API defined that is pre-defined for form-data.  That works just fine.  So I think the issue is just when you choose the "form-data' button in the POST request.

Let me know if you need more details.

This is not a high priority bug for us.  Just a minor annoyance.

**Comment by safani** [comment]
Still getting this bug today.  Has it been pushed to the WebStore yet?  When uploading a file and also sending a body on POST sometimes the body is not sent at all.

**Comment by itsjavi** [comment]
I am also having **still** this issue, but the problem was that I was sending manually the header "Content-Type : multipart/form-data". I removed it and not it works

**Comment by abhijitkane** [comment]
@mjolnic Do you have the Interceptor on?

**Comment by itsjavi** [comment]
@abhijitkane yes, but the problem was to have the Content-Type header manually set.

**Comment by SauloCosta10** [comment]
I am still having this issue. And yes, I have Interceptor on. The weird thing is that it started happening all of a sudden. I didn't have this problem until today. Edit: Fixed with the update from October 6th, 2015. Thank you
