### ISSUE TITLE
Postman Crashes when trying to download files around 10Mb

### ISSUE THREAD

**Issue by TomFS** [a85/POSTMan-Chrome-Extension#4551]
Please read through the [guidelines](https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues) before creating a new issue.

**Describe the bug**
Using GET to return a chunk of data (around 10Mb) when sending the request, Postman becomes unresponsive, in some cases crashing the computer entirely. 

**To Reproduce**
1. Send GET request that will return a large file of misc. data
2. Wait
3. Postman will become unresponsive and file will not be shown (unsure whether it will be downloaded)

**Expected behavior**
The response and data should be shown as raw text in the Response box for the query.

**App information (please complete the following information):**
 - App Type - Proprietary server
 - Postman Version 6.0.10
 - OS: Windows 10 Pro

**Comment by numaanashraf** [comment]
@TomFS Thanks for reporting this. There are known performance issues with handling large files and responses in Postman. We are tracking them at https://github.com/postmanlabs/postman-app-support/issues/1946. Closing this as duplicate.

**Comment by benwinding** [comment]
Also encountering this issue

**Comment by qijia00** [comment]
@numaanashraf, performance issues are tracked in #1946, but I don't see any actions are taken...

**Comment by JoshuaPHolden** [comment]
Also seeing this issue.
