### ISSUE TITLE
Read-Only Variables for Teams

### ISSUE THREAD

**Issue by staticvoidmaine** [a85/POSTMan-Chrome-Extension#4553]
**Is your feature request related to a problem? Please describe.**
We're using Postman as a team. We use both environment and global variables pretty heavily. We try to share as many variables as possible to make operation as smooth and consistent as possible. Sometimes, somebody accidentally overwrites a shared variable and interrupts the operation of others. This problem tends to cause problems that aren't immediately or obviously attributed to a variable change such as authentication failure etc. Finally, while we all are aware that this can happen, it still tends to happen despite our best efforts to avoid it.

**Describe the solution you'd like**
I would love to be able to mark important variables as read-only so it is not possible to change their value by accident.

**Describe alternatives you've considered**
Something that would reduce the number of times we experience this issue would be to offer "local" variables that aren't shared with anybody but can be pointed to by environment and/or global variables. This could possibly cut down on the number of times we experience the unwanted change of team-wide variables, but doesn't fully solve the root of the problem.

**Additional context**
N/A

**Comment by numaanashraf** [comment]
Thanks for the suggestion @rylancates. We are working on a set of changes and improvements that we hope would help with this use case. We'ld keep you posted on any updates here. Stay tuned. 😄

**Comment by a85** [comment]
Variables in Postman have initial values and current values. In a collaborative context, users can set initial values that will be shared but current values are local to everyone's instance of Postman. @rylancates Let me know if this solves your use case. Closing this for now.
