### ISSUE TITLE
postman 5.3 vs postman 6.0 workspace

### ISSUE THREAD

**Issue by shisapian** [a85/POSTMan-Chrome-Extension#4554]
**Describe the bug**
In 5.3v you can clearly distinguish between your own workspace and team workspace in postman UI. 
Whereas in 6.0, the collections appear to be everywhere and there is no color change. It's becoming difficult to distinguish and human error prone. I want to see the workspaces only with projects published by me along with my development projects. ( I should see the projects in  team workspaces only if I have added them to my workspace ).

**To Reproduce**
Different people in a team published 10 projects in team workspace. When I go to My workspace it shows me all of then even if I have not added them to my workspace or did an export/import.

**Expected behavior**
"My workspace" should show only projects published by me or the shared project added.

**Screenshots**

5.3 my workspace

<img width="1051" alt="screen shot 2018-05-11 at 4 42 04 pm" src="https://user-images.githubusercontent.com/20493575/39951063-452eebc6-553b-11e8-9efb-1565b2e0b5fa.png">

6.0 my workspace

<img width="1270" alt="screen shot 2018-05-11 at 4 41 27 pm" src="https://user-images.githubusercontent.com/20493575/39951072-547eadfa-553b-11e8-8c7c-6a34d80aef68.png">

And also please update your API document. Create environment with multiple values.

<img width="1433" alt="screen shot 2018-05-11 at 11 19 31 pm" src="https://user-images.githubusercontent.com/20493575/39954344-b2ec6af8-5572-11e8-8f11-4bba586d598f.png">

**App information (please complete the following information):**
 - App Type [ Native App]
 - Postman Version [e.g. 6.0.1]
 - OS: [e.g. macOS High Sierra 10.13.4]

**Comment by prashantagarwal** [comment]
@shisapian We are fixing this in the upcoming release. Also we have already released this fix on our Canary app. Can you please download the Canary app and verify if this fixes the issue for you. You can download the Canary app from https://www.getpostman.com/canary

**Comment by shisapian** [comment]
In PostmanCanary, for team workspace, I do not see all workspaces by default. There is a build/ browse in the bottom pane. Once I browse, I am seeing all shared workspaces. I am not sure if that's the expected behavior. 

Do you have a release guide for each version to refer the new features?

**Comment by prashantagarwal** [comment]
@shisapian My workspace shows any collection that you subscribe or own prior to workspaces (v6.1)
Ideally you should create your own personal or team workspaces to organise them better.
