### ISSUE TITLE
POSTMAN has not properly working has been crashed

### ISSUE THREAD

**Issue by VivekDabhi** [a85/POSTMan-Chrome-Extension#4560]
Please read through the [guidelines](https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues) before creating a new issue.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**App information (please complete the following information):**
 - App Type [e.g. Chrome App, Native App]
 - Postman Version [e.g. 6.0.1]
 - OS: [e.g. macOS High Sierra 10.13.2]

**Additional context**

**Comment by VivekDabhi** [comment]
hello good morning,

I have to try to launch postman in my ubuntu 17.10 system but get an error every time,

Try to launch Postman,
Wait while it attempts to connect,
Postman crashes without ever opening,
Receive dialog that says, "Postman has crashed. Click this balloon to restart the app. (See attached),
When I click the balloon, postman attempts to launch, but it just crashes again without opening,
The balloon is displayed again.

please give me answer ASAP how to properly work in my system, I have to try too many more method in installing postman

**Comment by numaanashraf** [comment]
@VivekDabhi Please try out Linux desktop app (https://www.getpostman.com/apps). Postman Chrome Apps are deprecated.
