### ISSUE TITLE
Postman won't start

### ISSUE THREAD

**Issue by shufflebump** [a85/POSTMan-Chrome-Extension#4562]
**Describe the bug**
The Postman app won't start on my laptop. When I try to open it, it gets stuck on the loading screen where the three dots orbit the larger dot. I tried reinstalling it several times. A coworker tried emptying cache files and deleting temp files. It worked last week, but I asked another coworker for a "large data set" and that made Postman stop working. (I'm a quasi intern at a large corporation. The data set was f*** huge.) I had to stop the whole program. Someone tried running it in command prompt, and this is the error message it gave:

ORM initialization successful
App events bus { name: ‘booted’, namespace: ‘shared’ }
App events bus { data:
{ adapterMethodName: ‘find’,
cause:
{ adapterMethodName: ‘find’,
modelIdentity: ‘workspacesession’,
name: ‘AdapterError’,
raw: [Object] },
isOperational: true,
modelIdentity: ‘workspacesession’,
raw:
{ _e: {},
inner: {},
message: ‘Maximum IPC message size exceeded.’,
name: ‘UnknownError’ } },
name: ‘booted’,
namespace: ‘requester’ }

**To Reproduce**
Try to open Postman.

**Expected behavior**
I expected Postman to open.

**App information (please complete the following information):**
 - Native App
 - Postman Version 6.0.10
 - OS: Windows 10

**Additional context**
RIP

**Comment by nissim-kurle** [comment]
Same issues. Event log .
App events bus { name: 'booted', namespace: 'shared' }
App events bus { data: {}, name: 'booted', namespace: 'requester' }

**Comment by WurstCommander** [comment]
![image](https://user-images.githubusercontent.com/5268576/41482232-3c8742d8-70d5-11e8-8e3b-7f8f9c38309e.png)

Same here, Windows 7 64bit, updates postman today. The planet's orbits are shown forever and nothing happens. I have to kill postman.exe and restart it several times. Do you need any logs etc?

**Comment by WurstCommander** [comment]
Any news on this? can't use Postman anymore.

**Comment by SamvelRaja** [comment]
@shufflebump  could you try installing the latest version 6.14 and verify that the issue still persists.

**Comment by shufflebump** [comment]
No. I took my laptop in to the IT desk and they had to reset my profile on
the laptop to fix it. I don't need to use that data set again any time
soon, so I won't be messing with it.

**Comment by SamvelRaja** [comment]
@shufflebump  Thanks for getting back and confirming. Closing this issue for now.
@WurstCommander  Your issue seems to deviate from this, I request you to follow https://github.com/postmanlabs/postman-app-support/issues/4594#issuecomment-391601621

**Comment by gufrancisco** [comment]
I'm using the 6.3 version and the same bug has occurred.
App events bus { data: {}, name: 'booted', namespace: 'requester' }
and don't open the software.
![selecao_015](https://user-images.githubusercontent.com/25965126/45590504-f623f600-b90f-11e8-9b02-6ebb7bf06c09.png)
My so is ubuntu 16.04
