### ISSUE TITLE
Check if the response is NOT EMPTY

### ISSUE THREAD

**Issue by samreenadil** [a85/POSTMan-Chrome-Extension#4563]
Hi Everyone,

Below are the tests that I have written to check if the response body is not empty.
tests["Body is NOT empty"] = (responseBody!==null);
tests["JSON ARRAY is NOT EMPTY"] = (responseBody.length >=0);
[] is the response I get in the body, when sending the requests with above tests - it shows PASS however in body I just get [] as the response. 
![image](https://user-images.githubusercontent.com/38338777/40145046-69a4aa12-592e-11e8-905a-2137656550d2.png)

![image](https://user-images.githubusercontent.com/38338777/40145067-7ba1b28c-592e-11e8-995c-6212e91494da.png)

**Comment by numaanashraf** [comment]
`responseBody` is a raw string of the response body. If you want to check if JSON array returned in the response if not empty, you can use the following script.

```
let parsedResponseBody = JSON.parse(responseBody);
tests['JSON array is not empty'] = (parsedResponseBody.length > 0);
```

**Comment by nagarc1** [comment]
Its not working. AssertionError: expected false to be truthy 

let parsedResponseBody = JSON.parse(responseBody);
tests['JSON array is not empty'] = (parsedResponseBody.length > 0);

**Comment by kpalczewski** [comment]
pm.response.responseSize > 0
