### ISSUE TITLE
Postman-Echo concatenates the content of all files of a POST request

### ISSUE THREAD

**Issue by mkammermann** [a85/POSTMan-Chrome-Extension#4564]
Note: this is a bug of the web-service postman-echo.com

If I send a POST request to https://postman-echo.com/post with a form-data body that contains multiple files, then the JSON response shows in "files" all the sent files, but the shown base64 content is the same for all files, namely the concatenation of the content of all files.

Please see the attached screenshot, where I sent 2 files that contain "abc" and "ABC" respectively. The JSON response shows the 2 files, but the base64 content of both files is "YWJjQUJD", which is when decoded using https://www.base64decode.org/ "abcABC".

![postman post mutlipart files](https://user-images.githubusercontent.com/31221611/40146248-19ce8850-5965-11e8-8c2f-80f783b170ba.png)

**Comment by numaanashraf** [comment]
Thanks for reporting this @mkammermann. We are looking in it.

**Comment by kunagpal** [comment]
@mkammermann This has been fixed. Could you re-try and confirm that it works? Thanks again! 😄

**Comment by mkammermann** [comment]
Hi Kunal, 

thank you very much for fixing this bug. 
I executed my test-program now, and it works as expected. 

Sincerely 
Matthias Kammermann 


Von: "Kunal Nagpal" <notifications@github.com> 
An: "postmanlabs/postman-app-support" <postman-app-support@noreply.github.com> 
CC: "Dipl. Ing. Matthias Kammermann" <matthias.kammermann@sphinx.at>, "Mention" <mention@noreply.github.com> 
Gesendet: Donnerstag, 17. Mai 2018 21:39:42 
Betreff: Re: [postmanlabs/postman-app-support] Postman-Echo concatenates the content of all files of a POST request (#4564) 



Closed [ https://github.com/postmanlabs/postman-app-support/issues/4564 | #4564 ] .
