### ISSUE TITLE
Differences between UI Export and API Get Collection

### ISSUE THREAD

**Issue by timatanu** [a85/POSTMan-Chrome-Extension#4565]
I'm seeing different output from when I use the Collections API vs what is saved to file when is use the Export option from within Postman. In particular the API has extra tags.

I'm invoking the API as follows. curl --request GET --url 'https://api.getpostman.com/collections/2952158-d7d0fa07-7775-c5b7-606c-6b6425685bbb' --header 'x-api-key: xxxx7c93393344bab7fff1b72599xxxx' | jq . > APC02.txt

The attached screenshot shows the API content in the lefthand pane and the exported content in the righthand one.

<img width="1237" alt="collectionsapivsexportfrompostman" src="https://user-images.githubusercontent.com/39357224/40153598-db09d73c-59cd-11e8-996d-570366b85d02.png">

**Comment by numaanashraf** [comment]
@timatanu Thanks for reporting this. We are looking into it.

**Comment by numaanashraf** [comment]
@timatanu This is intended. During file export, we remove the internal _postman_ids of all the entities in the collection. While you are using the Postman API, we preserve all the internal ids so that you can identify and continue to work with individual entities via the Postman API.
