### ISSUE TITLE
Unable to use the GET and Sync function in postman software on Corporate Network.

### ISSUE THREAD

**Issue by lkumar001** [a85/POSTMan-Chrome-Extension#4566]
Dear Sir/Madam
Kindly assist as our clients use postman, but the GET and Sync options does not work. We are accessing postman on a corporate network. Support documentation advised to enable the proxy settings, which gives authentication failure on GET and cannot connect to server when clicking sync. We also allowed the recommended amazon us east ip ranges on the firewall, but are still unable to use the GET and Sync functions. May you kindly advise what the Firewall and/or proxy requirements (Ip ranges/port/urls) are for postman to work on a corporate network. 
You previously queried if Websocket connections are blocked on our end. Websocket connections are allowed on our end.
Thank you

**Comment by lkumar001** [comment]
Does postman site use akamaitechnologies.com sites as well. We have a very restricted rulebase and akamaitechnologies.com is blocked as well as cloudfront. Please advise on this and provide us with the ip ranges, ports and or host that will require access.
Thank you

**Comment by lkumar001** [comment]
Dear Sir/Madam
Kindly advise if there is any feedback regarding this request. Thank you

**Comment by lkumar001** [comment]
Dear Sir/Madam
Kindly advise if there is any feedback regarding this request. Thank you

**Comment by a85** [comment]
Please email help@getpostman.com with your account details for connectivity issues.
