### ISSUE TITLE
Run whole subfolder or selection within the builder view using sidebar

### ISSUE THREAD

**Issue by cen1** [a85/POSTMan-Chrome-Extension#4568]
**A clear and concise description of what the problem is.**
A lot of times I have a subfolder with **prep calls** such as auth and some other stuff that sets global variables which are then used across further integration tests.

Manually running these calls one by one is tedious, especially if I am switching environments and they need to be re-run or if I need to rerun due to changes on the backend.

**Describe the solution you'd like**
Scenario 1: Right click on subfolder->Run all requests.

Scenario 2: select requests (select+shift or ctrl+select) and run selected requests.

**Describe alternatives you've considered**
Using the Runner (Scenario 1).

**Comment by numaanashraf** [comment]
@cen1 Have you tried running the folder via the Collection Runner? https://www.getpostman.com/docs/v6/api_testing_and_collection_runner/running_collections

**Comment by cen1** [comment]
Yes, I know about the runner and persisting the variables but it seems inconvenient. It's a seperate window which I need to have set up, then I need another runner window when running automated tests etc. I also have to switch environments in main and runner window, it's not synchronous.

I'd expand my idea even further, instead of running whole folder, to run a **selection** of requests, eg: select+shift or ctrl+select to highlight the wanted requests, then run them with single action.

**Comment by numaanashraf** [comment]
Thanks for the feature suggestion @cen1.

**Comment by vkaegis** [comment]
#4705

**Comment by saswatds** [comment]
Duplicate of #6360 #2392

Closing this issue to track the feature at a single place

**Comment by shamasis** [comment]
@cen1 - I’ve tweaked the title of the issue to better reflect the use case and reopened the issue.

**Comment by giridharvc7** [comment]
You can now drag drop a subfolder into the collection runner, let us know if this solves your problem @cen1
