### ISSUE TITLE
i am trying to Auotmate API via Postman and I need to reuse an excel file while running the second iteration. How do I do it ?

### ISSUE THREAD

**Issue by dasre21** [a85/POSTMan-Chrome-Extension#4569]
Is it possible to store the excel file in Postman so that I can use it again ?
not sure if it is bug or feature request

**Comment by vkaegis** [comment]
Hey @dasre21, thanks for writing in. You can supply a CSV file to the Postman collection runner to use values from the file in the run. Export your excel file as CSV to use it with your collection. You can refer to our documentation for a better idea on how to do this: https://www.getpostman.com/docs/v6/postman/collection_runs/working_with_data_files
