### ISSUE TITLE
Super local variables

### ISSUE THREAD

**Issue by justmobilize** [a85/POSTMan-Chrome-Extension#4570]
**Is your feature request related to a problem? Please describe.**
I've used Postman for a handful of different projects, as well as used Postman collections from other companies. One issue I've always had is handling variables. Most API's have some sort of `GET` by ID and in Postman the URLs for the request are either `https://api.somplace.com/thing/1` or `https://api.somplace.com/thing/{{thingId}}`. Which means I either need to change the URL or variable. When this is someone else's API it's not that big of a deal because I'm not going to save the changes. But when it's mine, and I'm both altering the request and testing on real data, it can be a pain to remember if the changes are real or fake.

**Describe the solution you'd like**
What I feel would be great is to have per tab variables. Right up there in the header next to `test` where I can set `thingId` in a super local scope that doesn't save if I close the tab, or mark it as changed.

**Describe alternatives you've considered**
Currently my team clones a main global environment and we save a bunch of variables like `sampleThingId`. It works, but it isn't ideal

Thanks,
-Justin

**Comment by sankalp0o** [comment]
Hi @justmobilize,
Thanks for the suggestion! We're working on introducing semi-permanent variables that would belong to a local session in Postman. I think this would solve your particular use case. Will let you know when we have more to show. Till then, maybe you can try using a different workspace when you're testing. Workspaces maintain their own set of global variables.

**Comment by justmobilize** [comment]
@sankalp0o that sounds great. Looking forward to hearing more! I do use different workspace / environments as I go. But as a new startup we're changing things constantly and it's still a bit complicated.

**Comment by a85** [comment]
Folks. Check out the RFC on sessions here: https://community.getpostman.com/t/sessions-in-postman/1925

**Comment by prashantagarwal** [comment]
@justmobilize variable sessions are now available on Postman app.
