### ISSUE TITLE
Not Getting Response in Pretty View Json Only

### ISSUE THREAD

**Issue by yashpal-123** [a85/POSTMan-Chrome-Extension#4571]
Hello,I am Using Paypal Rest Sdk For Creating Web-Service In Php.But My Faced Problem Is that I can't Convert Response in Json Form means not seen in json pretty view but that i can see in html view.I am using chrome version of postman.
![screenshot from 2018-05-18 11-36-41](https://user-images.githubusercontent.com/39398176/40218730-1191090c-5a90-11e8-8ef6-1860f0dfd0c8.png)
![screenshot from 2018-05-18 11-36-59](https://user-images.githubusercontent.com/39398176/40218738-18675b50-5a90-11e8-9d69-642a0089466c.png)
Can Anybody Help Me to Solve My Issue?

**Comment by vkaegis** [comment]
Hey @yashpal-123, thanks for writing in. The Postman Chrome apps have been deprecated, we'd advise you to update to the latest native app here: https://www.getpostman.com/apps

That said, your specific problem seems to arise from the fact that the response you're trying to view is in an incorrect JSON format. Ensure your response is formatted correctly to view it in the Pretty view.
