### ISSUE TITLE
Postman sending TCP Keepalives non-stop

### ISSUE THREAD

**Issue by Dynotrex** [a85/POSTMan-Chrome-Extension#4574]

**Comment by harryi3t** [comment]
@Dynotrex I tried using a proxy and sending a request with the `Connection:keep-alive` header.
The proxy showed only one request. What am I missing? How to reproduce this? Screenshots/Video would really help.

**Comment by tbennett6421** [comment]
Not sure if I should create a new issue or not, but I'm having this issue as well.

**Comment by WadeWare** [comment]
Dunno why this is closed when it's still an issue. Postman is unusable to me in this state as it creates too much overhead and unnecessary traffic for just testing. Not to mention by keeping the connection alive, a new connection is never initiated, so no handshaking never occurs again (TLS in my case). Hard to troubleshoot a handshake issue if the only way to create a new connection is to close Postman, reopen, etc.

**Comment by numaanashraf** [comment]
@WadeWare Could you try sending a `Connection: close` request header in your request? That should trigger a connection close after the request completes.

**Comment by WadeWare** [comment]
Adding a Connection: close req header does indeed trigger the close and keep-alive cease. I am kinda on the fence about this though. Meaning, the presence of the header is not a bad thing, but having to 'know' to add the header is quite different. Meaning, an option setting that says something like: 'Close connection after send' would in effect add the header in the message. 

In one sense I don't want postman modding headers from lets say a proxy capture (copy/paste/test), but in another, I may not remember to always add a connection: close when testing my own services/apis

Regardless, thanks!
