### ISSUE TITLE
Copy response is undefined("Copied to clipboard")

### ISSUE THREAD

**Issue by jesseckwon** [a85/POSTMan-Chrome-Extension#4575]
I use "Copied to clipboard"
but when I paste it's return "undefined"

Postman v6.1.2
OS: Windows10 Pro

**Comment by sivcan** [comment]
@jesseckwon Thanks for reporting this. I was able to reproduce this in the 'Pretty Mode'. 
The other views do not have this issue. We'll look into fixing this.

**Comment by robertkuhar** [comment]
I can confirm this affects Postman Version 6.1.2 (6.1.2) on OS X 10.13.4

Don't you guys have testing around this?  This seems really fundamental.

**Comment by sivcan** [comment]
@jesseckwon @robertkuhar We've released a fix for this on our canary channel.
Can you try it out and check if it solves the issue for you?

https://www.getpostman.com/canary

Canary builds run alongside the main postman app, they won't affect your settings/data.

**Comment by jesseckwon** [comment]
Now, I can use it.
Thank you.

Postman v6.1.3
OS: Windows10 Pro
