### ISSUE TITLE
Auto update fails while clicking on "Update" button. on Ubuntu Linux 18.04

### ISSUE THREAD

**Issue by barotashish** [a85/POSTMan-Chrome-Extension#4577]
**Auto update fails while clicking on "Update" button. on Ubuntu Linux 18.04** 

**To Reproduce**
1. Go to the Installation directory of Postman. e.g., ashish@ashish-barot:~/testing/Postman-linux/Postman
2. Execute Postman binary with following command :- 
    ./Postman 
3.  Once Postman GUI start, click on "Help" menu in header. And click on - "Check for Update"
4. It will open new window ( I am attaching the screen shot for the same ) 
5. Now when I click on "Update" button, it redirects me on following URL :- 
     https://www.getpostman.com/docs/v6/updating#linux 
6. when this URL loads, I am getting - 404 Page. ( I am attaching screen shot for the same ) 

**Expected behavior**
After clicking on Update button, it should update the Postman Software. 

**Screenshots**
Attaching following screen shots :- 

![screenshot from 2018-05-21 15-15-23](https://user-images.githubusercontent.com/21197417/40301855-f8a9e8f0-5d0a-11e8-88a4-ca6cf3807f0b.png)
![screenshot from 2018-05-21 15-15-02](https://user-images.githubusercontent.com/21197417/40301860-fdbf79d6-5d0a-11e8-95d8-180dbbeca875.png)

**App information (please complete the following information):**
 - App Type - Ubuntu Linux Desktop App
 - Postman Version - 6.16
 - OS: Ubuntu Linux - 18.04,  ( Linux ashish-barot 4.15.0-20-generic #21-Ubuntu SMP Tue Apr 24 06:16:15 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux )

**Comment by harryi3t** [comment]
@barotashish Thanks for reporting this.
Auto update is support from 6.1.x version. When you click on update button on an older version, it usually takes to a page from where you can download the app manually.

There is a redirection involved which is broken and we are fixing it.
For now, you can directly download the latest version which supports auto-updating from https://www.getpostman.com/apps

**Comment by barotashish** [comment]
@harryi3t  Thank you very much for updating. 

Right now I am able to use current version, and my testing is going on. 

will wait once this auto update will get fix. I will test it also.

**Comment by sivcan** [comment]
@barotashish The auto update feature is built inside the 6.1.2 version.
What's broken is the redirection to download the app from the postman's website.

**The current version that you've got won't be able to auto-update**.
You'll have to manually download the new version from https://www.getpostman.com/apps

After this, whatever next versions that come out after 6.1.2 will be automatically updated to by the app.
