### ISSUE TITLE
Postman startup very slow, 1+ minute

### ISSUE THREAD

**Issue by thoward333** [a85/POSTMan-Chrome-Extension#4578]
**Describe the bug**
I upgraded to latest 6.1.2 this morning. On startup of Postman, the window opens but is empty for ~1 minute. My cursor icon turns to busy but other than that, no indication of progress. Perhaps related: The splash logo on startup is solid black.

**To Reproduce**
1. Start Postman

**Expected behavior**
Application startup in a few seconds

**Screenshots**
![image](https://user-images.githubusercontent.com/4550812/40307621-44f10cbe-5cd1-11e8-86ca-3826d74a2183.png)

**App information (please complete the following information):**
 - Native app
 - Postman Version 6.1.2
 - Windows 7

**Additional context**
N/A

**Comment by thoward333** [comment]
I downgraded to 6.0.10 and it's working fine for me.

**Comment by prashantagarwal** [comment]
@thoward333 Can you help me chalk out some details so that we can debug this.
1) Do you have a Postman account using which you are logged in to the app.
2) Do you have multiple accounts attached to the app.
3) What is you system's hardware configuration.

Thanks in advance.

**Comment by thoward333** [comment]
@prashantagarwal 
1. My postman username is thoward333
2. No
3. 64-bit Intel i7, 16GB RAM - let me know if you need more detail

**Comment by prashantagarwal** [comment]
@thoward333 Thanks. Do you also have some GPU installed as well, Like nvidia or someother.

**Comment by thoward333** [comment]
@prashantagarwal AMD (ATI) FirePro M4000 (FireGL V) Mobility Pro Graphics

**Comment by carloshml** [comment]
I have the same issue.

**Comment by sbervinov** [comment]
I have the same issue

**Comment by MG-CDS** [comment]
Same issue here, and downgrading fixed it.

**Comment by jkonert** [comment]
same experience with 6.1.0-canary06 and 6.1.2  (win64). Downgrade to 6.0.10 works.

**Comment by cesardl** [comment]
I have the same problem right now with Postman 6.1.2 64 bits on Windows 8.1. I saw that 3 windows process launched on postman startup and mouse cursor show an loader as if to my machine is making a job on background and the app never starts.

**Comment by harryi3t** [comment]
@thoward333 @carloshml @sbervinov @MG-CDS @jkonert @cesardl 
This might be an issue with the GPU.
Can you try opening the app with `--disable-gpu` flag
```bash
cd C:\Users\YOUR_USERNAME_HERE\AppData\Local\Postman\app-6.1.2
Postman.exe --disable-gpu
```

If this works, it confirms that the issue is with the GPU.
For this, we have added a workaround in our latest canary build. You just need to add an environment variable `POSTMAN_DISABLE_GPU=true`
Detailed steps can be found here https://github.com/postmanlabs/postman-app-support/issues/4594#issuecomment-391601621

**Comment by MG-CDS** [comment]
I noticed that v6.1.3 has been released. Does this update fix the issue described here?

**Comment by harryi3t** [comment]
In 6.1.3 we added a workaround to disable the GPU. 
If after following steps as mentioned here https://github.com/postmanlabs/postman-app-support/issues/4594#issuecomment-391601621 does not solve the problem then it's not related to GPU and is a separate issue.
Can someone confirm if this works?

**Comment by SallyRobinson** [comment]
I have this issue since I upgraded to 6.1.3

**Comment by MG-CDS** [comment]
Upgrading to v6.1.3 and following the instructions in the link that @harryi3t provided has resolved this issue for me. 

Thank you @harryi3t !!!

**Comment by seven-huang** [comment]
i met this issue at postman-osx-6.2.4

**Comment by jawn** [comment]
Thanks for providing this workaround. 
However, many users may be affected and not everybody will find this page. 

The impression you get as a user is this: the software is slow or buggy (even though the GPU is the cause).

So the question is, does it make sense to enable GPU by default given these effects?

**Comment by nergalex** [comment]
Same issue with 6.2.5, it's OK now with this workaround posted on issue #4594, thank you harryi3t

**Comment by cuzzlor** [comment]
Thank you @harryi3t !!

**Comment by SteveIves** [comment]
I have this problem in 6.7.2!!! And the --disable-gpu setting DOES WORK!!! It's on a Windows 2012 R2 server VM, there IS NO GPU!!!

**Comment by TastyMantou** [comment]
This issue still happen every time Postman got updated (v.7.2.1). It's super annoying to have to go to cmd and type Postman.exe --disable-gpu.

**Comment by harryi3t** [comment]
@TastyMantou @thoward333 @SteveIves @cuzzlor @nergalex @jawn @seven-huang @MG-CDS 

We were able to trace the root cause of this to a combination of OS version + GPU hardware + Driver versions that did not work well with Electron/Chrome (which is internally used by Postman).

We have updated the Electron version on our canary channel which you can get from 
https://www.getpostman.com/downloads/canary 

Please let us know if this fixes the issue.

**Comment by jakesylvestre** [comment]
I'm still having this issue in 7.2.2 on Mac

**Comment by harryi3t** [comment]
@jakesyl Can you try the canary build (7.3.4-canary03) which you can download from https://www.getpostman.com/downloads/canary?

**Comment by jakesylvestre** [comment]
trying it out now @harryi3t

**Comment by harryi3t** [comment]
@jakesyl Also, the same is available now on our stable channel (Postman 7.3.4) as well.

**Comment by cirofeitosa** [comment]
Same issue here, using version 7.9.0 on Mac

**Comment by kwhat** [comment]
Eh, fix didnt work just looping when trying to sign in with google.

**Comment by Edceballos** [comment]
I've been having this issue for months and  so far nothing had worked, it takes up to 2 minutes for postman to start, once starts I can't switch on my tabs nor the collections for another minute, it is absolutely frustrating 👎

**Comment by Edceballos** [comment]
One new issue, I can't RENAME the tabs as it is not allowing it, I was able to just name or rename at the top, now I must do SAVE AS, and doing so it is soooo LAGGGYYYYYYY is there any other app like this to sue instead?
BTW: In case you decide to ask what hardware I use it, well let me just tell you This happens on all of my 3 Workstations, all Windows 11, Two systems are  Intel i9-10900K Nvida 2080 and 3070 64Gs 4k  RAM, RYZEN 3900X 12X24 core, 32Gs 3600 Gskill RAM all 3 systems with Samsung EVOs 3500bs, so NO, my systems aren't slow nor outdate pal..

**Comment by PaulSinnema** [comment]
Same here, Starting Postman takes very long. Still no solution?

**Comment by DenMayski** [comment]
Ok, i just disabled Hardware Acceleration, and it's work faster. Left menu - Help - Disable Hardware Acceleration. I hope it's help to you. Sorry for my English.
