### ISSUE TITLE
Resolve collection variables the same way as environment variables

### ISSUE THREAD

**Issue by ghost** [a85/POSTMan-Chrome-Extension#4579]
When environment variable is used in request URI or header params, then it gets automatically resolved and its value can be read when hovering the mouse over the variable or in the Code window.

It would be great to have collection variables (the ones entered on the Variables tab when editing collection) to be resolved the same way

**Comment by prashantagarwal** [comment]
@zhak What is your Postman app version

**Comment by ghost** [comment]
@prashantagarwal I just updated to 6.1.2. Attaching a screenshot of a variable not resolved in Code Snippet window
<img width="738" alt="postman" src="https://user-images.githubusercontent.com/1532960/40314260-a657a644-5d20-11e8-9a8d-e65060cd90ab.png">

**Comment by prashantagarwal** [comment]
Oh @zhak Actually we are tracking this here #4176 . We have also fixed this internally, will soon  be out on canary. Closing this as duplicate.
