### ISSUE TITLE
Xml file that is send as multipart, is sent with application/xml personal Content-Type header. While text/xml is required. Is there any workaround for such situation 

### ISSUE THREAD

**Issue by 7artur7** [a85/POSTMan-Chrome-Extension#4580]
I've already inspected this ticket https://github.com/postmanlabs/postman-app-support/issues/1104 and as i see Postman desn't have a feature to assign personal `Content-Type` to files, but i don't need to send multiple files with different `Content-Type` i need to send a single file but with `text/xml` not with `application/xml` (that is set by Postman by default) is there a way to do so?

**Comment by 7artur7** [comment]
There is a crutch solution of overriding `Content-Type` to `multipart/form-data; boundary=SomeBoundary` and paste request as plain text with `boundary`, correct `Content-Type: text/xml` and xml content. In such case it of course works, but isn't there more elegant solution for a single file?

**Comment by 7artur7** [comment]
Hey @harryi3t, @dhineshwiz  did you have time to investigate this?

**Comment by dhineshwiz** [comment]
Hey @7artur7 , for sending single file with custom content type, you can override the default content-type in the headers tab after selecting the file

<img width="949" alt="screen shot 2018-05-31 at 4 49 11 pm" src="https://user-images.githubusercontent.com/10631268/40779786-d6ef606e-64f3-11e8-9a63-789edc1aee57.png">

<img width="937" alt="screen shot 2018-05-31 at 4 48 37 pm" src="https://user-images.githubusercontent.com/10631268/40779791-dd6b3a9e-64f3-11e8-9460-ce64a0661ae7.png">

Let me know if you need more information

**Comment by angelinux69** [comment]
<?xml version="1.0" encoding="UTF-8" standalone="no"?><FLUXSalesReportMessage xmlns:clm63155CommunicationChannelCode="urn:un:unece:uncefact:codelist:standard:UNECE:CommunicationMeansTypeCode:D16A" xmlns:qdt="urn:un:unece:uncefact:data:Standard:QualifiedDataType:20" xmlns:ram="urn:un:unece:uncefact:data:standard:ReusableAggregateBusinessInformationEntity:20" xmlns:rsm="urn:un:unece:uncefact:data:standard:FLUXSalesReportMessage:3" xmlns:udt="urn:un:unece:uncefact:data:standard:UnqualifiedDataType:20" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:un:unece:uncefact:data:standard:FLUXSalesReportMessage:3 FLUXSalesReportMessage_3p1.xsd"><FLUXReportDocument><ram:ID SchemeID="UIDD">854d743c-48a2-484f-9ed7-61840c173c5d</ram:ID><ram:CreationDateTime><udt:DateTime>2019-10-25T04:08:40Z</udt:DateTime></ram:CreationDateTime><ram:PurposeCode listID="FLUX_GP_PURPOSE">9</ram:PurposeCode><ram:Purpose>Sales Note</ram:Purpose><ram:OwnerFLUXParty><ram:ID schemeID="FLUX_GP_PARTY">ITA</ram:ID></ram:OwnerFLUXParty></FLUXReportDocument><SalesReport><ram:ItemTypeCode listID="FLUX_SALE_TYPE">SN</ram:ItemTypeCode><ram:IncludedSalesDocument><ram:ID schemeID="EU_SALES_ID">ITA-SN-2019-481557</ram:ID><ram:CurrencyCode listID="TERRITORY_CURR">EUR</ram:CurrencyCode><ram:SpecifiedSalesBatch><ram:SpecifiedAAPProduct><ram:SpeciesCode listID="FAO_SPECIES">SWO</ram:SpeciesCode><ram:WeightMeasure unitCode="KGM"/><ram:UsageCode listID="PROD_USAGE">HCN</ram:UsageCode><ram:AppliedAAPProcess><ram:TypeCode listID="FISH_FRESHNESS">E</ram:TypeCode><ram:TypeCode listID="FISH_PRESERVATION">FRE</ram:TypeCode><ram:TypeCode listID="FISH_PRESENTATION">WHL</ram:TypeCode></ram:AppliedAAPProcess><ram:TotalSalesPrice><ram:ChargeAmount>42.5</ram:ChargeAmount></ram:TotalSalesPrice><ram:SpecifiedSizeDistribution><ram:CategoryCode listID="FISH_SIZE_CATEGORY">1</ram:CategoryCode><ram:ClassCode listID="FISH_SIZE_CLASS">LSC</ram:ClassCode></ram:SpecifiedSizeDistribution><ram:OriginFluxLocation><ram:TypeCode listID="FLUSH_LOCATION_TYPE">AREA</ram:TypeCode><ram:ID schemeID="FAO_AREA">37.1</ram:ID></ram:OriginFluxLocation></ram:SpecifiedAAPProduct><ram:SpecifiedAAPProduct><ram:SpeciesCode listID="FAO_SPECIES">AAR</ram:SpeciesCode><ram:WeightMeasure unitCode="KGM"/><ram:UsageCode listID="PROD_USAGE">IND</ram:UsageCode><ram:AppliedAAPProcess><ram:TypeCode listID="FISH_FRESHNESS">E</ram:TypeCode><ram:TypeCode listID="FISH_PRESERVATION">ALI</ram:TypeCode><ram:TypeCode listID="FISH_PRESENTATION">CLA</ram:TypeCode></ram:AppliedAAPProcess><ram:TotalSalesPrice><ram:ChargeAmount>300</ram:ChargeAmount></ram:TotalSalesPrice><ram:SpecifiedSizeDistribution><ram:CategoryCode listID="FISH_SIZE_CATEGORY">1</ram:CategoryCode><ram:ClassCode listID="FISH_SIZE_CLASS">LSC</ram:ClassCode></ram:SpecifiedSizeDistribution><ram:OriginFluxLocation><ram:TypeCode listID="FLUSH_LOCATION_TYPE">AREA</ram:TypeCode><ram:ID schemeID="FAO_AREA">27</ram:ID></ram:OriginFluxLocation></ram:SpecifiedAAPProduct></ram:SpecifiedSalesBatch><ram:SpecifiedSalesEvent><ram:OccuranceDateTime><ram:dateTime>2019-10-19</ram:dateTime></ram:OccuranceDateTime></ram:SpecifiedSalesEvent><ram:SpecifiedFishingActivity><ram:TypeCode>LAN</ram:TypeCode><ram:RelatedFluxLocation><ram:TypeCode listID="FLUX_LOCATION_TYPE">LOCATION</ram:TypeCode><ram:CountryID schemaID="TERRITORY">ITA</ram:CountryID><ram:ID schemaID="LOCATION">ITPIA</ram:ID></ram:RelatedFluxLocation><ram:SpecifiedDelimitedPeriod><ram:StartDateTime><ram:DateTyme>2019-10-19</ram:DateTyme></ram:StartDateTime></ram:SpecifiedDelimitedPeriod><ram:SpecifiedFishingTrip><ram:ID schemaID="EU_TRIP_ID"/><ram:ID schemaID="CFR">ITA000017792</ram:ID><ram:Name>CRISTOFALO I</ram:Name></ram:SpecifiedFishingTrip><ram:RelatedVesselTransportMeans><ram:RegistrationVesselCountry><ram:ID schemaID="TERRITORY">ITA</ram:ID></ram:RegistrationVesselCountry><ram:SpecifiedContactPerson><ram:RoleCode listID="FLUX_CONTACT_ROLE">MASTER</ram:RoleCode><ram:SpecifiedContactParty><ram:GivenName/><ram:MiddleName/><ram:FamilyName/></ram:SpecifiedContactParty></ram:SpecifiedContactPerson></ram:RelatedVesselTransportMeans></ram:SpecifiedFishingActivity><ram:SpecifiedFLUXLocation><ram:TypeCode schemaID="FLUX_LOCATION_TYPE">LOCATION</ram:TypeCode><ram:CountryID schemaID="TERRITORY">ITA</ram:CountryID><ram:ID schemaID="LOCATION">ITPIO</ram:ID></ram:SpecifiedFLUXLocation><ram:SpecifiedSaleParty><ram:ID schemaID="MS"/><ram:Name>ARCHINI LEONARDO</ram:Name><ram:RoleCode listID="FLUX_SALES_PARTY_ROLE">SENDER</ram:RoleCode></ram:SpecifiedSaleParty><ram:SpecifiedSaleParty><ram:ID schemaID="VAT">RCHLRD76R04H501F</ram:ID><ram:Name>ARCHINI LEONARDO</ram:Name><ram:RoleCode listID="FLUX_SALES_PARTY_ROLE">BUYER</ram:RoleCode></ram:SpecifiedSaleParty><ram:SpecifiedSaleParty><ram:Name>MEGNA GIUSEPPE</ram:Name><ram:RoleCode listID="FLUX_SALES_PARTY_ROLE">SELLER</ram:RoleCode></ram:SpecifiedSaleParty></ram:IncludedSalesDocument></SalesReport></FLUXSalesReportMessage>
