### ISSUE TITLE
Postman becomes unresponsive

### ISSUE THREAD

**Issue by aliaga-d** [a85/POSTMan-Chrome-Extension#4582]
Running on Windows 10. 
I can not see what version of postman I am running, (since it is unresponsive)

The problem is Postman has become very unresponsive. It does not respond to mouse clicks. I can see the menu. There are a lot of open tabs, but when I tried "force close all tabs", nothing happens. 

I would be very grateful if someone can tell me how to deal with this problem## Issue Report:

**Comment by harryi3t** [comment]
@aliaga-d Can you try the latest version from https://www.getpostman.com/apps
Let me know if that does not help.
