### ISSUE TITLE
Non-empty indicator circle is unvisible

### ISSUE THREAD

**Issue by BorysFursov** [a85/POSTMan-Chrome-Extension#4583]
Postman for Windows
Version 6.1.2
win32 10.0.16299 / x64
 
When Editing collection's pre-request and test scripts in previous versions we had that blue circle showing that script is now empty ( like this, but now it is green)  
![image](https://user-images.githubusercontent.com/37802805/40355548-5ee54f38-5dbf-11e8-8d00-58a4a5f925cc.png)
But after update I it doesn't work in collection edit in both (dark and white) themes here is my example:
![image](https://user-images.githubusercontent.com/37802805/40355689-c728753e-5dbf-11e8-88cb-5dbf565a2534.png)

**Comment by prashantagarwal** [comment]
@BorysFursov We have fixed this internally. Will release the fix in next app release

**Comment by sivcan** [comment]
@BorysFursov  We have a released a fix for this issue on our canary channel.
https://www.getpostman.com/canary

Canary builds can run alongside the main Postman app and won't affect your settings/data.
