### ISSUE TITLE
Collections lost after accidentally log off my account that wasn't in sync in months

### ISSUE THREAD

**Issue by lin-ma** [a85/POSTMan-Chrome-Extension#4584]
**Detailed problem**
There were a few time where I lost my collections by accident. Today's one is very frustrated!!
For the recent couple of months, I have been using standalone postman login with my postman account, unfortunately, today I accidentally logged off postman and when I logged back in, all the collections disappeared !!  and I haven't done backup, and what's more is that I realized sync has stopped working for quite sometime because of our company security policy changed. 

I googled and logged to my account (using the link https://web.postman.co/me/collections) but only able to get the collections that were saved more than **6 months** ago.

Is there a way to find the local file to have these collections recovered? 
Your help will be very critical!

**Describe the solution you'd like**
1. A way for recover the collections that wasn't sync properly or was accidentally removed by any possible seasons. e.g. extension remove, app uninstalled, or sync stopped working. etc.
2. A way for auto backup
3. When log off postman account make sure the code is checking if sync is not working, if not working, make a backup at local instead of removing local collection. 

**Describe alternatives you've considered**
1. I googled and logged to my account (using the link https://web.postman.co/me/collections) but only able to get the collections that were saved more than 6 months ago.
2. googled and tried to look for local DB file ( C:\Users\mal\AppData\Local\Google\Chrome\User Data\Default\IndexedDB)  but could not find the detailed answer.

**Additional context**
lin.ma.likes.postman@gmail.com is my postman account.
Appreciated if I can get my collections back as it has been a couple of weeks work.

**Comment by sivcan** [comment]
@lin-ma Kindly write to [help@getpostman](mailto:help@getpostman.com) for support regarding this.
Also, you can head over to the dashboard - https://web.postman.co/ and login and you'll find your collections and other data that were synced.

We maintain this repo for bug reports and feature requests only.
So I'll be closing this issue.
