### ISSUE TITLE
Large responses cause a crash or hang

### ISSUE THREAD

**Issue by GeoKnR** [a85/POSTMan-Chrome-Extension#4585]
## App Details:
```
Postman for Mac/Windows
Version 6.1.2 (6.1.2)
OS X 10.13.4 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there: Encountered recently, smaller files seem to work correctly.
 2. Expected behaviour: When the file is downloaded, i should get a file save dialog. Note that if i just do Send (not Send and Download), i get the same behavior.
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app): Console logs are displayed in the images.
 4. Screenshots (if applicable)
Mac - just hangs, never gets past the Loading... response
![screen shot 2018-05-22 at 7 29 36 am](https://user-images.githubusercontent.com/15911365/40365512-f584005c-5d91-11e8-8b5b-0542d8cc1193.png)

Windows - stops working dialog
![screen shot 2018-05-22 at 6 03 01 am](https://user-images.githubusercontent.com/15911365/40365407-b7176f2a-5d91-11e8-96dd-6d7506ff5a86.png)

This particular file is 1.27GB.  This same code works when generating smaller files.  I haven't narrowed down the point at which it stops working.

**Comment by GeoKnR** [comment]
One more thing, on the Mac version, I am able to cancel the request.  So it is not completely stuck, just never finishes getting the file.

**Comment by Beera819** [comment]
Hi, after upgrading to latest release 6.1.2

I see the GET calls being stuck with no response...

![image](https://user-images.githubusercontent.com/39547835/40406947-4b938d84-5e80-11e8-9506-a8f03a65799e.png)

And sometimes crashing with Postman has stopped working error

**Comment by vkaegis** [comment]
@GeoKnR @Beera819 Thanks for reporting this! We're aware of performance issues around large requests and are working on some improvements. We'll let you know as soon as we have an ETA on this,

**Comment by numaanashraf** [comment]
@GeoKnR @Beera819 We have created a master thread #4751 to track all issues related to large responses. Please follow that issue for updates.
