### ISSUE TITLE
Postman no longer keeps zoom the same

### ISSUE THREAD

**Issue by chrisron95** [a85/POSTMan-Chrome-Extension#4586]
Please read through the [guidelines](https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues) before creating a new issue.

**Describe the bug**
Postman has always been way too zoomed in for me, but from day one it always stayed at the zoom level that I set it at. But now ever since I updated to 6.1.2 yesterday, the zoom doesn't stay set when I restart the app. Every time I restart it now it's back to the default zoom level.

**To Reproduce**
1. Start the app
2. Set zoom level to something different than the default level
3. restart the app
4. zoom is back to default

**Expected behavior**
Zoom should stay at same level even if restarted.

**Screenshots**
Default (zoomed in)
![screen shot 2018-05-22 at 9 37 53 am](https://user-images.githubusercontent.com/16259311/40366126-60d20860-5da4-11e8-88fd-ec5de0f95627.png)

Zoomed out
![screen shot 2018-05-22 at 9 38 17 am](https://user-images.githubusercontent.com/16259311/40366149-705ae784-5da4-11e8-8797-a7755d23078b.png)

**App information (please complete the following information):**
Postman for Mac
Version 6.1.2
OS X 17.4.0 / x64

**Additional context**
I did notice that it seems to still be storing the zoom level, because when I restart it and try to zoom back out again, pressing the button one time takes me one level past where I set it before restarting. So say it zooms 10% at a time and default is 100%, I set it to 70%. Then I restart it, it's back to 100%, but pressing the zoom out button takes me down to 60% zoom. So it seems like it's storing it, it's just being ignored on startup.

**Comment by prashantagarwal** [comment]
@chrisron95 Thanks for reporting this and the context that you provided helped us in pin pointing this bug. We have fixed this internally and will soon make it available in upcoming release.

**Comment by oliverm2112** [comment]
Seems fixed in 6.1.3

**Comment by chrisron95** [comment]
Agreed, updated to 6.1.3 and it appears to be fixed. Thanks!

**Comment by prashantagarwal** [comment]
Thanks guys for verifying this. Closing it.

**Comment by perhan** [comment]
This problem is happening again to me on Mac app for quite some time now and also in Version 6.2.3. Just out of the blue Postman change zoom and can't even detect cursor position properly.

**Comment by numaanashraf** [comment]
@perhan I am not able to replicate this issue. Could you send us a screenshot or a recording of the issue? I'ld help us triage the issue faster.

**Comment by callistino** [comment]
@perhan I had the same issue and it had to do with enabling smart zoom on the magic mouse. I disabled it and it went back to the right zoom level. This wasn't an issue before though.

**Comment by petru-motrescu** [comment]
Hey 👋

Just downloaded Postman on my new MacBook with Apple silicon and I can reproduce this issue.

Postman installed from **Postman v9.19.3 for macOS (arm64).zip**
macOS Monterey version 12.4

**Comment by jainsamyak** [comment]
> Postman installed from **Postman v9.19.3 for macOS (arm64).zip**

Same behaviour, using Postman Version 9.23.3 on Mac OS Monterey 12.4
Zoom level is always reset to the same upon restart.
Really annoying, kindly provide a fix.

**Comment by numaanashraf** [comment]
@jainsamyak Thanks for reporting this. I was able to replicate this and have reopened this.

**Comment by diptarag** [comment]
Update: This issue has been fixed and is available in 9.25.2. Please let us know if you're still facing issues.
