### ISSUE TITLE
Syncing not connecting; "websocket not connected".

### ISSUE THREAD

**Issue by CianLMcCormack** [a85/POSTMan-Chrome-Extension#4587]
Hi!
when i click to sync across devices (and start working "online") no sync occurs.
I expect to be synced successfully. My end goal is to set up a monitor on a collection I've created, but I need to be online to achieve this.

 - Native App
 - Postman Version 6.0.10

Dev tools output the following at first log in attempt:
Could not find on CollectionStore. Missing or invalid parameter.
find @ requester.js:41889
requester.js:560264 Check that entitites shown here should only be personal entites
componentWillMount @ requester.js:560264
requester.js:368809 error fetching Error: Could not fetch from sync. Socket not connected.
    at SyncRemoteFetcherService._dispatchCallback (file:///C:/Users/mccoian/AppData/Local/Postman/app-6.0.10/resources/app.asar/js/requester.js:75398:26)
    at EventEmitter.108.EventEmitter.emit (file:///C:/Users/mccoian/AppData/Local/Postman/app-6.0.10/resources/app.asar/js/common.js:17099:17)
    at _dispatch (file:///C:/Users/mccoian/AppData/Local/Postman/app-6.0.10/resources/app.asar/js/common.js:24502:14)
    at EventEmitter.<anonymous> (file:///C:/Users/mccoian/AppData/Local/Postman/app-6.0.10/resources/app.asar/js/common.js:24512:9)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:191:7)
2requester.js:41889 Could not find on CollectionStore. Missing or invalid parameter.
find @ requester.js:41889
requester.js:155489 Invalid lifecycle state switch for workspace undefined & state deleting
setLifecycle @ requester.js:155489
requester.js:118790 Object
requester.js:545927 Error in login Object
(anonymous) @ requester.js:545927
requester.js:155489 Invalid lifecycle state switch for workspace undefined & state deleting
setLifecycle @ requester.js:155489
requester.js:141163 Successfully received bootstrap data Object
requester.js:238086 Publishing offline changes to sync client Array[0]
requester.js:41890 Could not perform update on UserListStore. id is missing in definition.
update @ requester.js:41890
requester.js:41889 Could not find on CollectionStore. Missing or invalid parameter.
find @ requester.js:41889
requester.js:410163 You tried to return focus to null but it is not in the DOM anymore
exports.returnFocus @ requester.js:410163
requester.js:141361 Error in fetching collection activity feed
requester.js:101423 Save aborted
requester.js:205578 Collection export failed
(anonymous) @ requester.js:205578
saveAndOpenFile @ requester.js:101424
(anonymous) @ requester.js:296962
(anonymous) @ requester.js:205577
convert @ requester.js:224139
convert @ requester.js:223934
convert @ requester.js:223756
(anonymous) @ requester.js:205570
requester.js:41889 Could not find on CollectionStore. Missing or invalid parameter.

I've seen this error posted about a few times already, but no mention of a definite resolution. I have tried logging out and in & resetting my VM, and my system proxy does allow websocket connections as tested here https://websocket.org/echo.html .

thanks in advance
Cian

**Comment by kamalaknn** [comment]
Hi @CianLMcCormack 

The error logs that you are seeing are warnings from unrelated flows. These are non critical to any workflow. We'll clean them up in upcoming releases.

Our Sync and connectivity are handled in a shared process common to all windows. Could you send logs for that process (View -> Developer -> Show DevTools(Shared)) so we can take a closer look at whats happening?

**Comment by CianLMcCormack** [comment]
hi @kamalaknn 
sorry it's taken me a while to get back to you, i haven't had any time to give to this since i raised the initial problem... workplace pressures and all that! below are logs from the shared devTools

sails.io.js:142 🌏 error establishing connection with sync service.
 Error: websocket error
    at WS.Transport.onError (sails.io.js:3)
    at WebSocket.ws.onerror (sails.io.js:4)
sails.io.js:142 🌏 scheduled reconnection attempt #1 after 14775ms
sails.io.js:142 🌏 reconnecting to sync service. #(1/1)
sails.io.js:5 WebSocket connection to 'wss://sync-xi.getpostman.com/socket.io/?__sails_io_sdk_version=0.11.0&__sai…tform=browser&__sails_io_sdk_language=javascript&EIO=3&transport=websocket' failed: Error during WebSocket handshake: Unexpected response code: 200
ws @ sails.io.js:5
WS.doOpen @ sails.io.js:4
Transport.open @ sails.io.js:3
Socket.open @ sails.io.js:3
Socket @ sails.io.js:3
Socket @ sails.io.js:3
Manager.open.Manager.connect @ sails.io.js:3
(anonymous) @ sails.io.js:3
wrapped @ vendor-shared.js:242015
sails.io.js:142 🌏 error establishing connection with sync service.
 Error: websocket error
    at WS.Transport.onError (sails.io.js:3)
    at WebSocket.ws.onerror (sails.io.js:4)
sails.io.js:142 🌏 failed to reconnect to sync service after 1 attempts.

**Comment by Ocsidot** [comment]
I have the same issue.
Here is a screenshot of the logs

![image](https://user-images.githubusercontent.com/6094145/42637289-141b963e-85eb-11e8-8a6c-1e3a614ee5e5.png)

please do something, this issue is really a blocking point for my team

**Comment by numaanashraf** [comment]
Thank you for your issue! With only the details that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if this issue is still happening for you.
