### ISSUE TITLE
Allow users to maintain different window themes at once in the Postman app

### ISSUE THREAD

**Issue by dbodow** [a85/POSTMan-Chrome-Extension#4590]
**Is your feature request related to a problem? Please describe.**
I often need to manage different Postman windows (e.g. one for production and one for development when checking for regressions). I would like to be able to easily visually differentiate between environments, which currently involves checking both the workspace and the environment name. I've frequently wasted time by running requests in the wrong environment.

**Describe the solution you'd like**
I would like to be able to set a profile that would use a different theme for each window (additional themes or the ability to use custom themes would make this even better, but I could get by with only light/dark for now). Even better, I would love to be able to have fully featured profiles and window sets (similar to iTerm2/Terminator) that I could set up once and use to manage multiple environments easily thereafter. Managing themes as profiles would be a good first step in this direction.

**Describe alternatives you've considered**
I sometimes put Postman windows in separate virtual workspaces to allow me to infer the environment by the context the window is in. However, this is insufficient for side-by-side requests.

**Additional context**
Check out iTerm2's profiles for inspiration. Modern editors also have easy to manage profiles that might give some inspiration for how this could be edited (e.g. Atom; VSCode; Sublime)

**Comment by vkaegis** [comment]
@dbodow Thanks for the feedback! Definitely understand the need for better visual differentiation between your work environments. We'll be taking this up as a feature request in the coming builds.

**Comment by chris-torruella** [comment]
Hi @dbodow, with our latest update in Postman V11, we've rolled out various app themes but more importantly to your use case, workspace color customization options. These additions could help differentiate between different workspaces. Give them a try and let us know if this was helpful!
