### ISSUE TITLE
Postman stalling/freezing on open on fresh Windows Install

### ISSUE THREAD

**Issue by EoghanH** [a85/POSTMan-Chrome-Extension#4597]
OS: Windows 10, Fresh install

**Describe the bug**
Following installation, Postman will freeze on launch.

**To Reproduce**
1. Download any up-to-date version of Postman 6.0.10 (x86 OR x64)
2. Install at any privilege level (Admin or Standard)
3. Postman installs, then opens 4 processes, and freezes on the loading screen, without any actual graphics (i.e: 'moving satellites into position' loading messages) loaded in - just a beige window. Can only be closed with "End Task"
4. Wiped out %appdata%/roaming/postman folder and completed full reinstall - no difference.

**Screenshots**
![postman-stall](https://user-images.githubusercontent.com/436600/40482212-eaa16b32-5f4b-11e8-91f9-86d70fa1ce28.png)

**App information (please complete the following information):**
 - App Type : Native App
 - Postman Version : 6.0.10, test on 6.0.9 with same issue.
 - OS: Windows 10 x64, Fresh Install

**Comment by sivcan** [comment]
Your issue looks similar to https://github.com/postmanlabs/postman-app-support/issues/4594#issuecomment-391601621

Can you check try the solution provided by @harryi3t with the latest canary build?
You can download the canary build from here: https://getpostman.com/canary

**Comment by EoghanH** [comment]
Hey Sivcan,

Perfect - the canary build is running without issue for me. Many thanks.
