### ISSUE TITLE
Extensive integration test

### ISSUE THREAD

**Issue by samreenadil** [a85/POSTMan-Chrome-Extension#4600]
Hi Postman people,

First of all Thanks a bunch for developing this amazing tool, We have Postman PRO in our organization and the requirement I have is to automate all manual integration tests for a web based application.

I have basic knowledge about postman however I have doubts as what tests to write to validate the front end things. 
Example: testing the authenticate API which is a POST request - provided parameters to postman and tested: 
1. valid token should be generated. - login successful.
2. status code =200
3. response time etc.

However I also want to validate with successful login - I see dashboard component, start a project, PDF downloads etc (note these are front end components and have API's attached to them )
Start a project has POST API request.

Also if this is not possible can Postman test that when Authenticate API is called all other API's for start a project, PDF version etc etc comes into play.

You can reach out to me on samreen@promantusinc.com.

Thank you,
Samreen

**Comment by prashantagarwal** [comment]
@samreenadil I thing our postman community would help you out better in this. https://community.getpostman.com/
