### ISSUE TITLE
Header Value to Sent to Server

### ISSUE THREAD

**Issue by cmm268** [a85/POSTMan-Chrome-Extension#4606]
Please read through the [guidelines](https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues) before creating a new issue.

**Describe the bug**
After updating to 6.3.1, an updated header value is no longer sent to the server on a subsequent request.

**To Reproduce**
1. Set method to GET and x-csrf-token value to Fetch
2. Click on Submit
3. Switch method to POST, copy the returned x-csrf-token header value into the Headers value and submit the POST
4. Server returns x-csrf-token value is required, and the submitted value shows blank.

I went back and checked in the deprecated browser extension and this still works

**Expected behavior**
The updated x-csrf-token header value should be sent along with the json payload for the OData update via POST
[odatascreenshots.pdf](https://github.com/postmanlabs/postman-app-support/files/2044824/odatascreenshots.pdf)

**Screenshots**

**App information (please complete the following information):**
 - App Type [e.g. Chrome App, Native App]
 - Postman Version [e.g. 6.0.1]
 - OS: [e.g. macOS High Sierra 10.13.2]

**Additional context**

**Comment by vierasse** [comment]
This might be related:
Post-Requests with previously obtained csrf-token worked fine with 6.0.10, after upgrade to 6.1.3. error "crsf token validation failed" occurred. After returning to 6.0.10, the same requests again show no error.

**Comment by harryi3t** [comment]
@vierasse  @cmm268 
Can you change the endpoint to `https://postman-echo.com/post` (Request Type `Post`) and then send the request again. Please share the output in a screenshot.
If this is a bug, then the server should not return the value.
When I tried this, it worked perfectly
![postman](https://user-images.githubusercontent.com/5207331/40653485-f2b93e1a-6358-11e8-9ca1-56c4ba7c378a.png)

**Comment by cmm268** [comment]
When I try using the postman-echo link, I do see the header returned.  
![image](https://user-images.githubusercontent.com/39697876/40662048-43107832-6323-11e8-9dc8-791e38209c9f.png)

How can I revert back to an older version of Postman?

**Comment by vierasse** [comment]
You can still download the 6.0.10 version, install it over the 6.1.3, worked for me.

**Comment by harryi3t** [comment]
@cmm268 @vierasse 
If the echo server is returning the header value then it means the data was sent from the client.
Are you sure it's working with Postman 6.0.10 with the exact same environment (authorization, variables, url, proxy, etc)?
You can also use a proxy tool to intercept the request and see the exact data being sent out.
If this is actually a bug in Postman I will be more than happy to fix it. But, first I need to reproduce this. Is this server publicly accessible? If not, would it be possible for you to share a limited access to this endpoint?

**Comment by vierasse** [comment]
@harryi3t , I have prepared a small collection with GET and POST service to reproduce the issue. Would not like to post it publicly, how can I send it to you as a pm?

**Comment by harryi3t** [comment]
@vierasse Thank you for taking time to do this 👍 . You can send this to me at harendra[at]getpostman.com

**Comment by vierasse** [comment]
@harryi3t done, hope you can replicate it.

**Comment by harryi3t** [comment]
@vierasse I could replicate the issue.
But, when I analysed the requests sent from 6.0.10 and 6.1.3, both are sending the query params.
The issue is with the secure cookies not being sent. This issue is already being tacked here https://github.com/postmanlabs/postman-app-support/issues/4581#issuecomment-393182451

The fix for this is already pushed to the canary build (you can get the canary build from https://www.getpostman.com/canary)
This will be available in next version of Postman (6.2.0)

Closing this issue, in favour of https://github.com/postmanlabs/postman-app-support/issues/4581#issuecomment-393182451
