### ISSUE TITLE
Disabled Variables Reported as Duplicate Keys in Bulk Edit Mode

### ISSUE THREAD

**Issue by CorwinNewall** [a85/POSTMan-Chrome-Extension#4607]
**Description**
When multiple variables are specified with the same keys, the Bulk Edit window still reports 'Duplicate Keys' even if all but one is disabled.

**To Reproduce**
1. Click [\+ New] > Collection
2. Click on Variables tab
3. Add a key-value of test 1234
4. Add another key-value of test 1234
5. Observe "Duplicate Key" warning
6. Disable one of the duplicate keys
7. Warning disappears.
8. Click 'Bulk Edit'
9. "Duplicate Keys" warning reappears.

**Expected behavior**
"Duplicate Keys" warning should only appear when two or more _uncommented_ keys are the same, in Bulk-Edit mode.

**Screenshots**
Correct:
![image](https://user-images.githubusercontent.com/25069619/40631191-4e4c8028-632e-11e8-972e-f9702e9fc45d.png)
Correct:
![image](https://user-images.githubusercontent.com/25069619/40631186-424756ea-632e-11e8-88d0-0b68c32b5174.png)
Incorrect:
![image](https://user-images.githubusercontent.com/25069619/40631182-3643fefc-632e-11e8-927a-6c1d30fefc18.png)

**App information**
Postman for Windows
Version 6.1.3
win32 10.0.17134 / x64

**Comment by CorwinNewall** [comment]
Could you please explain why this is pending close?
A false positive "Duplicate Keys" when bulk editing keys means _actual_ duplicate keys are lost in the noise.
I've verified this also happens in the latest version of Canary.

**Comment by sujayvenaik** [comment]
@CorwinNewall 
Hey, this issue is fixed now and will be soon available.
Its available on the Canary platform and you can get that build from 
https://www.getpostman.com/canary
