### ISSUE TITLE
formdata saved in collection cloud is not consistent for 2 upload requests and no src in one of them

### ISSUE THREAD

**Issue by xiaweixing** [a85/POSTMan-Chrome-Extension#4609]
**Describe the bug**
formdata saved in collection cloud is not consistent for 2 upload requests and no src in one of them

**To Reproduce**
1. Edit one of my upload request (call it A) in my team collection
2. choose test.html as file to upload
3. Save collection into cloud
4. Do the same for another request (call it B) in my team collection, choose test.jpg as file to upload

**Expected behavior**
After getCollection API call, "src" should be in the response for both requests.

**Actual result**
In the response:
for A, it shows src
but for B, it does not

**Screenshots**
request A:
![post html body](https://user-images.githubusercontent.com/19727572/40643004-0b7dea3c-6362-11e8-929b-04baee4b6e03.png)
![post html](https://user-images.githubusercontent.com/19727572/40643005-0bae5e42-6362-11e8-834f-b761dfd8bd0f.png)

request B:
![post jpg body](https://user-images.githubusercontent.com/19727572/40643006-0bddffa8-6362-11e8-8ff3-4b753712f494.png)
![post jpg](https://user-images.githubusercontent.com/19727572/40643008-0c0f1af2-6362-11e8-9e60-b91020d1160e.png)

**App information (please complete the following information):**
 - App Type [Native App]
 - Postman Version [e.g. 6.1.3]
 - OS: [Win10]

**Additional context**

**Comment by harryi3t** [comment]
@xiaweixing File path is not stored within the request for security reasons

**Comment by harryi3t** [comment]
This is being tracked here now https://github.com/postmanlabs/postman-app-support/issues/4320

**Comment by xiaweixing** [comment]
@harryi3t the problem I raised is not about file path, it's about **src**, in requestA, it has "src", but in requestB, it doesn't have "src", why??
