### ISSUE TITLE
RestSharp code generation adds undefined parameter

### ISSUE THREAD

**Issue by blueneosky** [a85/POSTMan-Chrome-Extension#4610]
The generated code for RestSharp (C#) is wrong on a specific line. I get a 500 error on the REST server. After checking the documentation of RestSharp, this error come from the generated code.

**To Reproduce**
1. Create a PUT request with a body ('{}' is enough) as application/json content type
2. Click on 'Code'
3. Select "C# (RestSharp)" form combo
4. The line beginning with `request.AddParameter(` contains `"undefined"` as first parameter.

**Expected behavior**
The documentation of RestSharp specify that the first parameter must be the content type instead of `"undefined"` (see https://github.com/restsharp/RestSharp/wiki/ParameterTypes-for-RestRequest#requestbody section)

**App information (please complete the following information):**
 - Native App
 - Postman Version 6.1.3
 - OS: Windows 10

**Comment by abhijitkane** [comment]
@blueneosky In Postman 7.2.1, we've introduced bug-fixes, support for two new languages (JS-Fetch and Powershell), and the ability to configure certain aspects of the generated snippet with the 'Experimental Codegen Mode' flag enabled in Postman's global settings.

This particular issue has been fixed, and can be seen with the 'Experimental Codegen mode' flag set.
