### ISSUE TITLE
Cannot launch postman native app if Postman console is open.

### ISSUE THREAD

**Issue by seldin** [a85/POSTMan-Chrome-Extension#4613]
**Description**
If a postman console session is open you cannot launch the postman app. 

**To Reproduce**
1. Launch Postman native app.
2. Open Postman Console.
3. Close Postman native app
4. Do not close postman console.
5. Try to launch Postman native app while postman console session is still open.

**Expected behavior**
App should launch regardless if console is open or not. When closing the app it does not ask to close the console hence opening and closing them should be independent or connected in both closing and opening.

**App information:**
 - App Type = Native app
 - Postman Version 6.1.3
 - Windows 10 16299.371

**Comment by kamalaknn** [comment]
Hi @seldin 

Thanks for reporting this. I was able to reproduce this. We'll take a look this.

**Comment by numaanashraf** [comment]
This issue has been fixed in Postman v7.0.9
