### ISSUE TITLE
Cannot choose 'POST' or 'GET'

### ISSUE THREAD

**Issue by luckyzeno** [a85/POSTMan-Chrome-Extension#4618]
My computer is win10 and postman's version is 6.1.3. The method dropbox can not show all options.
<img width="427" alt="_20180530120515" src="https://user-images.githubusercontent.com/4628573/40698471-c6c5fe84-6401-11e8-97c0-abed45449275.png">

**Comment by kamalaknn** [comment]
Hi @Luckycn 

Do you have zoom level enabled? If yes you could reset the zoom level using shortcut `ctrl + 0`. That should make sure the drop down is within the visible area.

We'll work on making sure that dropdown is always on the visible area.

**Comment by sberserker** [comment]
Have the same issue after updating to 6.1.3. Have to zoom out to make drop down fall down. When reset zoom level back with ctrl+0 it goes up like on  the start screenshot.

**Comment by prashantagarwal** [comment]
Related to #4748
