### ISSUE TITLE
Prevent closure of modals which contain unsaved changes

### ISSUE THREAD

**Issue by Bopper1892** [a85/POSTMan-Chrome-Extension#4619]
The postman app allows the input of data into modal screens, e.g. environment data. It is incredibly frustrating to enter a significant amount of data only for this to be lost when accidentally clicking on the space outside the modal, rather than using the Update button.

I'd like a prompt to warn the user that there are unsaved changes and give the option to either continue or cancel the closure of the modal screen.

**Comment by kamalaknn** [comment]
Hi @Bopper1982 

We are looking into ways we can improve the experience around editing and saving entities. I'll mark this as a feature request. 

We consider this when we revisit the environment editing flows.

**Comment by vkaegis** [comment]
Hey @Bopper1892, thanks for writing in. While we work on usability improvements to the authoring flows around environments, we've disabled clicking outside to dismiss a modal. You'll need to explicitly click on the "Close" icon, the "Cancel" or "Update" buttons to dismiss the modal. Closing this issue for now.
