### ISSUE TITLE
Can't create new folder / Can't save new request

### ISSUE THREAD

**Issue by maitmansour** [a85/POSTMan-Chrome-Extension#4620]
**Bug Description**
After updating to the 6.1.3 version i can't now create folders Or save a new request !

**To Reproduce**
1. Start Postman
2. Try to create a new folder or new request !

**Expected behavior**
creating new folder / new request (as expected !)

**Screenshots**
Nothing is showing, just when i click, i got nothing, and the window don't respond !

**App information (please complete the following information):**
 - Native Application
 - Postman Version [e.g. 6.1.3]
 - OS: Windows 10

**Comment by kamalaknn** [comment]
Hi @maitmansour 

Can you give us more details to help triage this issue?

1. Have you logged in with sync enabled?
2. Are you creating folders on a shared collection?
3. Do you see any errors in the devtools(View -> Developer -> Show DevTools(Current VIew))?
4. What is the state when you click the save button?

**Comment by maitmansour** [comment]
Hi @kamalaknn,
Of course, this is some details : 

1. Have you logged in with sync enabled?
Yes, i'm connected with my google account
2. Are you creating folders on a shared collection?
Yes
3. Do you see any errors in the devtools(View -> Developer -> Show DevTools(Current VIew))?
i didn't check before
4. What is the state when you click the save button?
nothing happening

👍  Please note that i singed out, and then signin it, this solve the problem for me.
I think a new  re-authentification is needed after updating.

Thank you for your help !

**Comment by harryi3t** [comment]
@maitmansour Were you the owner of the collection in which you were trying to add folder/request?

**Comment by maitmansour** [comment]
@harryi3t  yes, i'm the owner, like a said now it's working fine, after a new re-authentication.

**Comment by adrian-kurzeja** [comment]
I have the same problem!
Everything was working untill:
I tried to mock server... it requested me to login so i logged with my google account... after login i can' save and create tabs.... please repair ;/

**Comment by MiguelBonachea** [comment]
Have similar problem after updating to latest Postman, I had to log in again and I can see all of my old collections. However I am unable to create new collections or save to old ones. I am also getting errors about invalid workspace in devtools... Please fix soon!

**Comment by MiguelBonachea** [comment]
Just noticed this issue is closed... can someone please post solution or patch?

**Comment by numaanashraf** [comment]
@millennial-web Could you post a screenshot of the error in devtools?

**Comment by MiguelBonachea** [comment]
![error-devtools-postaman](https://user-images.githubusercontent.com/25937317/52192551-40026f80-2810-11e9-9073-d5b587b4bc21.png)
