### ISSUE TITLE
Request URL encoding '&' to '&amp;' causing response errors

### ISSUE THREAD

**Issue by c-warnick** [a85/POSTMan-Chrome-Extension#4625]
## App Details:

```
Postman for Mac
Version 6.1.3
OS X 17.5.0 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there: Encountered recently.
 2. Expected behaviour: Request should be sent without encoding '&' to `'&amp;'` or at least have the option to disable.

Click the 'code' button below save. Copy url and paste in text editor. Notice parameters are separated by `&amp;` not &

**Comment by SamvelRaja** [comment]
@c-warnick  Thanks for bringing this to our notice.

As far as I researched, the [HTTP/1.1](https://tools.ietf.org/html/rfc2616#section-3.2) standard, which uses  [URL scheme]( https://tools.ietf.org/html/rfc1630) standard specifies `&` is a `safe` character that need not to be encoded.   We will keep this in track and will update the thread once it is fixed from our end.

**Comment by abhijitkane** [comment]
@c-warnick 
Can you try this is Postman 7.2.1, with the 'Experimental Codegen Mode' flag enabled in Postman's global settings? We've introduced bug-fixes, support for two new languages (JS-Fetch and Powershell), and the ability to configure certain aspects of the generated snippet.
