### ISSUE TITLE
Load balancer sessions no longer sticky after upgrading to Postman 6.1.3

### ISSUE THREAD

**Issue by funketyme** [a85/POSTMan-Chrome-Extension#4626]
**UPDATE: I have downgraded to 6.0.10 and the functionality is working again.  Something changed with the upgrade to 6.1.3.  The issue is also no longer present when using canary build 6.2-1.**

**ISSUE**
Postman requests that hit load balancer endpoints no longer retain sticky sessions after upgrading to Version 6.1.3, win32 10.0.17134 / x64.

**STEPS TO REPRODUCE**
- Configure a URL to hit that resides behind a load balancer with sticky sessions spread over two or more servers.
- Configure a header to be returned that shows the actual servername of the machine serving the request.
- Repeatedly hit the load balanced domain endpoint in Postman and observe the respondingServer switch between all servers in the pool.
- Repeat the same test, only this time hit the URL in a web browser with dev tools open and observe the respondingServer the same for each successive request.

**EXPECTED BEHAVIOR**
The respondingServer should be the same on all Postman requests made from the same session, similar to the way the web browser functions.

**APP INFO**
 - Native Windows app
 - Version 6.1.3, win32 10.0.17134 / x64
 - Windows 10, current with Windows Update patches

**CONTEXT**
I first noticed this happening after I opened Postman for the first time after upgrading to 6.1.3 earlier today (and seeing the little notification rectangle at the top of the app).  I am not aware of any local load balancer changes made by our IT department, but I have a ticket submitted with them just to be sure.  This was working on the previous version of Postman yesterday.

Additionally this is not an issue when hitting a non load balanced endpoint.  If I hit machines in the load balanced pool directly there is no issue with the session.

**Comment by funketyme** [comment]
I have just downloaded Canary build Version 6.2.0-canary01 win32 10.0.17134 / x64 and the issue is no longer present, I have only been able to reproduce the issue in 6.1.3.

**Comment by SamvelRaja** [comment]
@funketyme  we are having an issue in setting up the cookies for secure end points in our latest release. Could you confirm that is the cause for the issue you are facing.
We fixed the same in our canary version, that's why it is working there.
Might be related to https://github.com/postmanlabs/postman-app-support/issues/4581

**Comment by funketyme** [comment]
Yes, that is it!  Thank you.  All of our cookies are secure, and required for our load balancer config.  This is definitely a duplicate of #4581.
