### ISSUE TITLE
Icon on macOS is not the same size as every other apps

### ISSUE THREAD

**Issue by ThibaultVlacich** [a85/POSTMan-Chrome-Extension#4628]
**Describe the bug**
The macOS app icon is bigger than other app icons, and is most likely not respecting Apple's Guidelines.

**To Reproduce**
N/A

**Expected behavior**
Icon is respecting macOS design guidelines.

**Screenshots**
![](https://i.imgur.com/0wcBUA0.png)

**App information (please complete the following information):**
 - App Type: Native macOS app
 - Postman Version: 6.1.3
 - OS: macOS 10.13.4

**Comment by thecuriousdev** [comment]
@ThibaultVlacich thanks for reporting this, We'll have a look into this.

**Comment by gee-forr** [comment]
It's finally fixed in 6.2.1. Thanks @thecuriousdev. I'm irrationally happy about this :)
