### ISSUE TITLE
Postman is not syncing

### ISSUE THREAD

**Issue by ogryzek** [a85/POSTMan-Chrome-Extension#4629]
**Description**
Similar to [4401](https://github.com/postmanlabs/postman-app-support/issues/4401), Postman is not syncing. I updated to 6.1.3 this morning, and then noticed the issue.

![Imgur](https://i.imgur.com/ibMwyaZ.png)

![Imgur](https://i.imgur.com/anvfeeY.png)

Also, having some issues when trying to view [workspaces](https://web.postman.co/workspaces) through the browser.  

![Imgur](https://i.imgur.com/NaNwPpd.png)

**Comment by TheAllThing** [comment]
My entire team is experiencing this same behavior.

**Comment by godfrzero** [comment]
Our provider (AWS) is experiencing issues, and we'll be back up as soon as they are. Keep an eye on our Twitter feed for updates: https://twitter.com/postmanclient

**Comment by SamvelRaja** [comment]
@ogryzek  @TheAllThing  Please feel free to re-open this issue if still persist.

**Comment by egpotter** [comment]
It is not syncing for me right now... Only shows connecting, and the console shows:
error fetching Error: Could not fetch from sync. Socket not connected.

**Comment by Ocsidot** [comment]
Still not working on windows

**Comment by ogryzek** [comment]
It was resolved, but does appear to be happening again. Not sure if new issue or re-open is better. I don't see anything mentioned on https://twitter.com/postmanclient as @godfrzero said to monitor above.
