### ISSUE TITLE
Cannot add headers with pm.request.headers.add

### ISSUE THREAD

**Issue by Ocsidot** [a85/POSTMan-Chrome-Extension#4631]
Please read through the [guidelines](https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues) before creating a new issue.

**Describe the bug**
In a pre-request script, if I add a new header value using pm.request.headers.add, it seems to be added but I cannot see it in the sent request.

**To Reproduce**
1. On pre-request script type
![image](https://user-images.githubusercontent.com/6094145/40827826-1deec794-657f-11e8-8d85-a6e199be2b0e.png)

2. Here is the result in console

![image](https://user-images.githubusercontent.com/6094145/40827982-a1f77dec-657f-11e8-9b12-a3290b670833.png)

3. In pre-request, it seems that the header is correctly added. But in the actual request, I can't see my new header

**Expected behavior**
See added header in request

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version: 6.1.3
 - OS: win32 6.1.7601 / x64

**Additional context**
I don't really if it's any issue or not. But for me if you give a 'add' method in your API it should really add the element

Thanks for your help
Regards

**Comment by kunagpal** [comment]
@Ocsidot This is expected behaviour, as changes made to `pm.request` are not propagated to the actual request sent. I'm marking this as a feature request 😄

**Comment by Ocsidot** [comment]
@kunagpal Thank you for your quick answer :)

It seems also to me that it should be a feature.
I hope this will be implemented soon :+1: 

Thanks

**Comment by pritesh-patil** [comment]
+1

**Comment by kunagpal** [comment]
@pritesh-patil Please leave a 👍 on my first comment instead of posting +1 comments, keeps the thread clean 😄

**Comment by bradleyszabo** [comment]
The Sandbox documentation definitely had me searching for this as a bug, not a feature request.

I think the presence of the following two request objects in the sandbox leads to this confusion:

- **request**

  From https://www.getpostman.com/docs/v6/postman/scripts/postman_sandbox:
  > request {object}: Postman makes the request object available to you while writing scripts. This object is read-only. Changing properties of this object will have no effect. Note: Variables will NOT be resolved in the request object.

- **pm.request** 

  From https://www.getpostman.com/docs/v6/postman/scripts/postman_sandbox_api_reference:
  > The request object inside pm is a representation of the request for which this script is being run. **For a pre-request script, this is the request that is about to be sent** and when in a test script, this is the representation of the request that was sent.

I took the latter documentation to imply that the **pm.request** should be mutable in a pre-request script and those changes applied to the outbound request, whereas the other request object is not, as clearly documented. I also did not see anything in the [Pre-Request Scripts](https://www.getpostman.com/docs/v6/postman/scripts/pre_request_scripts) or any other documentation to indicate the pm.request is also a read-only copy. I may have missed something though.

I was hoping based on the **pm.*** Sandbox API [Request](http://www.postmanlabs.com/postman-collection/Request.html) object that I could programmatically set or remove headers and query parameters in a pre-request script without having to use environment variables for the test. This would be a very powerful capability (and much cleaner) for automation and data driven testing. I was dismayed to find that this is not actually a feature.

This ticket is now a feature request specifically for request headers, but the same capability is desired for query parameters too. 

e.g.
pm.request.addQueryParams("paramKey1=paramValue1");
pm.request.addQueryParams({ key:"paramKey2", value:"paramValue2"});

where leveraging the Request API in a pre-request script ideally modifies the actual request object used.

Should I open a separate issue for the query parameters? It seems like a more holistic issue is needed for the pm.request object to become mutable according to its complete API in pre-request scripts and used for the actual request. Perhaps this ticket can cover all? 

These changes will be incredibly useful for data driven scripting.

**Comment by sunilsamantra** [comment]
@a85 Awesome feature to have in terms of usability and automation perspective.Thanks for working on this. Any tentative timeline for this to be rolled out? Waiting to use this feature for my project.

**Comment by alexanderkraemer** [comment]
Is there any update on the status of this feature request?

**Comment by Broutard** [comment]
+1 
I have to modify the host used in all requests because I have imported my api from swagger and the host is not set.

**Comment by dchBrandify** [comment]
Is this feature implemented?

**Comment by natemcintyre** [comment]
Huge +1 for getting this implemented. Would be fantastic to be able to set a header for all my requests rather than having to remember to set them each time I create a new request in a collection.

**Comment by Lambeaux** [comment]
+1

**Comment by igorveremsky** [comment]
+1

**Comment by manukoshe** [comment]
+1

**Comment by manukoshe** [comment]
this is actually a bug as noted by bradszabo

**Comment by corygross** [comment]
+1

**Comment by bradwbradw** [comment]
If it helps, i was able to get something similar working: 

In the pre-request script, set a global variable / environment variable

```
postman.setEnvironmentVariable("temp", "abc_value")
```

 then just interpolate it in the Params / Headers section of the Request Editor by setting the value to `{{temp}}`.

**Comment by huixisheng** [comment]
+1

**Comment by louislewatcn** [comment]
> 
> 
> The Sandbox documentation definitely had me searching for this as a bug, not a feature request.
> 
> I think the presence of the following two request objects in the sandbox leads to this confusion:
> 
>     * **request**
>       From https://www.getpostman.com/docs/v6/postman/scripts/postman_sandbox:
>       > request {object}: Postman makes the request object available to you while writing scripts. This object is read-only. Changing properties of this object will have no effect. Note: Variables will NOT be resolved in the request object.
> 
>     * **pm.request**
>       From https://www.getpostman.com/docs/v6/postman/scripts/postman_sandbox_api_reference:
>       > The request object inside pm is a representation of the request for which this script is being run. **For a pre-request script, this is the request that is about to be sent** and when in a test script, this is the representation of the request that was sent.
> 
> 
> I took the latter documentation to imply that the **pm.request** should be mutable in a pre-request script and those changes applied to the outbound request, whereas the other request object is not, as clearly documented. I also did not see anything in the [Pre-Request Scripts](https://www.getpostman.com/docs/v6/postman/scripts/pre_request_scripts) or any other documentation to indicate the pm.request is also a read-only copy. I may have missed something though.
> 
> I was hoping based on the **pm.*** Sandbox API [Request](http://www.postmanlabs.com/postman-collection/Request.html) object that I could programmatically set or remove headers and query parameters in a pre-request script without having to use environment variables for the test. This would be a very powerful capability (and much cleaner) for automation and data driven testing. I was dismayed to find that this is not actually a feature.
> 
> This ticket is now a feature request specifically for request headers, but the same capability is desired for query parameters too.
> 
> e.g.
> pm.request.addQueryParams("paramKey1=paramValue1");
> pm.request.addQueryParams({ key:"paramKey2", value:"paramValue2"});
> 
> where leveraging the Request API in a pre-request script ideally modifies the actual request object used.
> 
> Should I open a separate issue for the query parameters? It seems like a more holistic issue is needed for the pm.request object to become mutable according to its complete API in pre-request scripts and used for the actual request. Perhaps this ticket can cover all?
> 
> These changes will be incredibly useful for data driven scripting.

That above is exactly what I want to say.

I would like to write a universal postman collection to test all kinds of get request.
I hope to set the host, params, headers method all as variables,which will make a template so that i can run different api tests with differet params and heads.
The key point is : different api have different params keys or header keys and aslo different amount.
e.g.
I have one api  host/get1?param1=a&param2=b
         another:   host/get2?token=xxx&location=sss%country=us

I hope in prescript the headers and params can be set by the method **addHeaders  addQueryParams**
but they are not working :

I set in the **pre-request script**: 
`pm.request.addQueryParams("param1=a&param2=b")`

but when i run in **tests**:
`console.log(pm.request.url.getQueryString())`
it displays an empty string

Now I have to choose to use python script to achive data-driven tests: only one script is needed.
All left to do is just config: urls.methods, paramters,and headers as json object to run test

I wish to see it achived in postman because it has a nice report and a pretty ui which is not a easy work for QAE.

**Comment by akmozo** [comment]
I think that [header presets] (https://learning.getpostman.com/docs/postman/sending_api_requests/requests/#header-presets) can be the solution to add headers to requests.

**Comment by fortinj1354** [comment]
Header presets are definitely not a suitable replacement for being able to dynamically add headers to a request. All that feature does is make it easier to add the "header with a variable value" to the request but it does nothing to solve the issue of not wanting to manually add the header and variable in the first place.

**Comment by gustavoq-infocorp** [comment]
this issue has more than a year opened, some news about when will be planned ? or some workaround ?

**Comment by akmozo** [comment]
@fortinj1354 
`... add the "header with a variable value" to the request ` was my goal when I found this issue, and for me header presets were a suitable solution for that. 
Also, I think that many of postman users may have the same goal and will find this post, that's why I said "that header presets can be a solution to add headers to requests" and not a solution for the OP's issue .. voilà !

**Comment by shamasis** [comment]
We started our work on this.
https://github.com/postmanlabs/postman-runtime/pull/735

Only URL, header and request url can be modified

**Comment by mendelk** [comment]
@shamasis How long until this makes it into main app or Canary?

**Comment by czd890** [comment]
I hope to release this change as soon as possible. Now I can use "oauth2, add auth data to request url, accesstoken: '=1&my custom parameters'" to work around.

**Comment by ihipop** [comment]
How long until to makes it release?

**Comment by klemens-u** [comment]
I'd like to use this feature! +1

**Comment by richarddevers** [comment]
me too +1

**Comment by codenirvana** [comment]
We've added support for this on our Canary (`version: 7.1.0-canary01`) channel https://www.getpostman.com/canary

Following will work in `pre-request` scripts:
```javascript
// Add new header
pm.request.headers.add({
    key: 'Accept-Encoding',
    value: 'gzip'
});

// Add or update an existing header
pm.request.headers.upsert({
    key: 'Connection',
    value: 'close'
});

// remove header
pm.request.headers.remove('User-Agent')
```

Will update the thread once we release this on our stable channel.

**Comment by markusrt** [comment]
@codenirvana Thanks a lot. This was just in time for me as I needed this feature right now.

I used it for the "Host" header in order to test our deployment before switching the DNS.
Adding this as a pre-request script to the collection worked as expected!

**Comment by JessePerry** [comment]
Why can't this be used to update the Authorization header if using the special Authorization helper tab?
We have a good use case for this, there is some special logic to be done with our tokens, after a user has finished interactive login with OAuth2. Essentially we re-sign the token, and this is working with a pre-request script to make a new token, but I can't replace the existing Authorization header or edit it. 
Why can't I replace the existing Authorization header like this:
```
    pm.request.headers.upsert({
    key: 'Authorization',
    value: 'Bearer ' + newToken
});
```
Thanks

**Comment by CaiJingLong** [comment]
> We've added support for this on our Canary (`version: 7.1.0-canary01`) channel https://www.getpostman.com/canary
> 
> Following will work in `pre-request` scripts:
> 
> ```js
> // Add new header
> pm.request.headers.add({
>     key: 'Accept-Encoding',
>     value: 'gzip'
> });
> 
> // Add or update an existing header
> pm.request.headers.upsert({
>     key: 'Connection',
>     value: 'close'
> });
> 
> // remove header
> pm.request.headers.remove('User-Agent')
> ```
> 
> Will update the thread once we release this on our stable channel.

It's finally come true. Thanks for job.

**Comment by richarddevers** [comment]
Macos here, it works like a charm, thanks a lot guys. Awesome works

**Comment by codenirvana** [comment]
This has been added in the latest Postman App (v7.0.9). 🎉
Refer https://github.com/postmanlabs/postman-app-support/issues/4631#issuecomment-477766260 for more detail.

**Comment by ghost** [comment]
@codenirvana  this usage should add into document, make it easy to read and help us out.

**Comment by Ricardonacif** [comment]
But that doesn't solve the need for documenting the API with a default header for all requests :(

**Comment by victornaito** [comment]
> tially we re

Is there some response about it ?
