### ISSUE TITLE
Feature Request: Sync collection from local file

### ISSUE THREAD

**Issue by Ocsidot** [a85/POSTMan-Chrome-Extension#4633]
I'm always frustrated when I have to export my collection to update my saved collection and it's the same case if my collection is updated and I get a new version through Git and I need to re-import it.

Could it be possible to keep the collection in Postman synchronized with the local file as it's done on many editor?

**Comment by angamardhana** [comment]
So badly needed.  I have at least 20 to 30 Collections now. Every time I change something in any of them I have to export it, find the right directory to save, then save it, and then code commit to Git. Its a royal pain. Automaticallly writing the collection to local dir would save so much trouble. 
A much needed feature.

**Comment by a85** [comment]
We currently and for the near future don't have plans for this. Syncing to Git can be achieved through the in-build Postman integration or through the Postman API as a workaround.

**Comment by gerardbosch** [comment]
Hello @a85 , what do you mean by "in-build Postman"?
I support this feature request as well.
