### ISSUE TITLE
Postman logo disappears from Ubuntu launcher after new update v6.1.3

### ISSUE THREAD

**Issue by palakpatel07** [a85/POSTMan-Chrome-Extension#4637]
## App Details:

```
Postman for Mac
Version 4.11.0
OS X 16.4.0 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:
 2. Expected behaviour:
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 4. Screenshots (if applicable)

**Comment by thecuriousdev** [comment]
@palakpatel07 thanks for reporting this issue. We'll look into this. 

And please provide a screenshot of this.

**Comment by palakpatel07** [comment]
@thecuriousdev Thanks for reply.
i have attached screenshot of missing icon.
![screenshot_of_lost_icon](https://user-images.githubusercontent.com/33681609/40919123-348a4434-6826-11e8-9ff8-2dc62a644548.png)

**Comment by Ludim** [comment]
I updated icon path in file ~/.local/share/applications/postman.desktop to:
`Icon=/opt/Postman/app/resources/app/assets/icon.png`

First I removed file, then created again with:
```
[Desktop Entry]
Encoding=UTF-8
Name=Postman
Exec=postman
Icon=/opt/Postman/app/resources/app/assets/icon.png
Terminal=false
Type=Application
Categories=Development;
```
It worked for me.

Reference: https://gist.github.com/invinciblycool/ecc1c6e32b581b68932ac7452f4c911c

**Comment by palakpatel07** [comment]
@Ludim Thanks for reply.
It's works for me. Great :)

**Comment by SamvelRaja** [comment]
In order to support Linux auto update, we changed our directory structure which cascaded this effect. 
I would recommend to replace `Icon=/PATH_TO_POSTMAN/Postman/app/resources/app/assets/icon.png` with `Icon=/PATH_TO_POSTMAN/Postman/resources/app/assets/icon.png` in the desktop file as @Ludim  suggested.

**Comment by matpag** [comment]
The same it's happening on Windows 10 with version 6.1.4

![image](https://user-images.githubusercontent.com/4432213/42509484-5205a3c2-844c-11e8-96be-5d867e31e47c.png)

**Comment by numaanashraf** [comment]
This issue has been addressed in Postman 6.7+.

**Comment by kshitijpatil** [comment]
I see this issue in v7.10.0 (snap)

**Comment by thameemk** [comment]
> I see this issue in v7.10.0 (snap)

Got same error while installed using snap.
After that, I have cleared the broken packages and icons installed previously without using snap.
Its worked for me
