### ISSUE TITLE
Postman App not working

### ISSUE THREAD

**Issue by harishrajora** [a85/POSTMan-Chrome-Extension#4638]
Please read through the [guidelines](https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues) before creating a new issue.

**Describe the bug**
My app starts, opens the window but nothing opens after that. It has been like this since the latest update of 25 may.
![screenshot 115](https://user-images.githubusercontent.com/8916887/40889039-9083784a-677d-11e8-93d2-08ec85bc804e.png)

I am on Windows 64 bit.

**Comment by chrisdeso** [comment]
@harishrajora – Are you on version `6.1.3`? 

This may be related to a known issue where Postman doesn’t launch with certain GPUs. A workaround for this issue involves disabling your GPU, and detailed instructions on how to do that can be found via the link below.

- https://github.com/postmanlabs/postman-app-support/issues/4594

**Comment by harishrajora** [comment]
I found another getaway with opening the app with intel graphics processor. It works fine.

**Comment by thecuriousdev** [comment]
Closing this ticket. Tracking this issue in https://github.com/postmanlabs/postman-app-support/issues/4594
