### ISSUE TITLE
Save Example should preserve response status code

### ISSUE THREAD

**Issue by massenz** [a85/POSTMan-Chrome-Extension#4640]
**Describe the bug**
The Save Example feature saves the response body and headers; however, the `Status` is always pre-filled with `200 OK`.

**To Reproduce**
1. Execute a request against server which returns a non-200 code (e.g., 201 or 404)
2. Click on 'Save Example'
3. Scroll down to 'EXAMPLE RESPONSE'
4. See `Status` field pre-filled to `200 OK`

(note this behavior is also exhibited by the now-deprecated `Save Response`).

**Expected behavior**
While the field is editable, so one can edit it after the fact, it is surprising (indeed, I initially filed a bug against myself) to see a 200 when a different code is expected: I would have expected the Status Code to be copied from the actual Response, just like the Headers and Body.

**Screenshots**

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version: 6.1.3
 - OS: Ubuntu 18.04

**Additional context**
Postman autogenerated Documentation is awesome!

**Comment by SamvelRaja** [comment]
@massenz  Thanks for bringing this to us. We will push the fix also keep posted on the status here.

**Comment by sujayvenaik** [comment]
@massenz 
Hi, we have addressed this issue as part of various improvements we have made to how tabs work in Postman. These changes are up available on our canary channel (https://www.getpostman.com/canary) today and would soon be available on the stable channel. Do try these out in the canary and let us know.

**Comment by sujayvenaik** [comment]
Hey @massenz 
This issue has been fixed and is available on the stable channel (v6.4.x).
You can update the app to the latest version.

Thanks again for writing in and reporting this issue.
