### ISSUE TITLE
Neither Stable nor Canary work on Windows Server 2012 R2

### ISSUE THREAD

**Issue by Sojaner** [a85/POSTMan-Chrome-Extension#4641]
Please read through the [guidelines](https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues) before creating a new issue.

**Describe the bug**
As soon as the installation is done, the app's screen stays either black or light orange (or white it is) and the cursor constantly turn into arrow+sandwatch for a glitch and back to arrow again.
The UI never appears.

**To Reproduce**
1. Download version 6.1.3 x64/Latest Canary build on Windows Server 2012 R2 x64
2. Install
3. Run

**Expected behavior**
Can see the UI and interact correctly.

**Screenshots**
![capture](https://user-images.githubusercontent.com/1634835/40905838-644c77f6-67df-11e8-83be-1161b3a45eee.PNG)

**App information (please complete the following information):**
 - Postman Version 6.1.3 x64
 - OS: Windows Server 2012 R2 x64

**Comment by thecuriousdev** [comment]
Hey @Sojaner, thanks for reporting this issue. You found this issue after the 6.1.3 update or its been there always? 

This may be related to a known issue where Postman doesn’t launch with certain GPUs. A workaround for this issue involves disabling your GPU, and detailed instructions on how to do that can be found via the link below.

https://github.com/postmanlabs/postman-app-support/issues/4594

**Comment by Sojaner** [comment]
It appeared after the 6.1.3 update @thecuriousdev. I had been using the Postman for a long time.
And it's right when I'm in a super tight deadline for releasing a web api project. :(

**Comment by thecuriousdev** [comment]
@Sojaner I am very sorry about that :( , Have you tried the work around mentioned in https://github.com/postmanlabs/postman-app-support/issues/4594?

**Comment by Sojaner** [comment]
Thanks for the workaround @thecuriousdev. Seems to be working again. Wish I had it 2 days ago. :)

**Comment by thecuriousdev** [comment]
@Sojaner good to hear that :), I am closing this ticket, we'll track the progress of this issue in https://github.com/postmanlabs/postman-app-support/issues/4594
