### ISSUE TITLE
Postman native app for linux is not syncing

### ISSUE THREAD

**Issue by egpotter** [a85/POSTMan-Chrome-Extension#4644]
The bug is similar to #4629, #4323 and  #4401. I can update my linux native app and now the sync stopped working. It only shows connecting, but nothing ever gets updated. Already tried logging out and logging in again,  disabling/enabling my wifi, and even restarted my pc. Nothing solved the issue

I have a native app running on Fedora 27 64-bit. Gnome version is 3.26.2.

My username is e.gischkow.potter

Postman console shows this:
![image](https://user-images.githubusercontent.com/4072069/40958851-0e0dc18a-689b-11e8-9cd6-fa7b3b2d23f5.png)

**Comment by egpotter** [comment]
Postman console shows this:
![image](https://user-images.githubusercontent.com/4072069/40929552-67196124-6825-11e8-94bf-110db00ef3dc.png)

**Comment by egpotter** [comment]
Sync is still not working properly for me. Any comments?

**Comment by egpotter** [comment]
So, to anyone seeing this afterward, the sny started working again. I actually did nothing and keeps using the same app, and 22 days later it worked. I really have no idea why. I tried login of/logging in again multiple times, reinstalling the app. The only real solution was to wait 22 days.

**Comment by awestley** [comment]
I "fixed" this by **entirely** uninstalling and reinstalling Postman.

**Comment by SamvelRaja** [comment]
@egpotter  @awestley We pushed a fixed for improving the stability of networking in our 6.1.4. Closing this for now.

**Comment by tigran-m-dev** [comment]
I also have same problem, but I am using windows 10 and have the latest application 6.1.4

**Comment by thecuriousdev** [comment]
@developer-devPHP are you getting any error in the console? can you share it here

**Comment by tigran-m-dev** [comment]
![2018-07-04_2119](https://user-images.githubusercontent.com/3036510/42312755-2e656bbc-8052-11e8-9d82-bb7c55baff0d.png)
![2018-07-04_2120](https://user-images.githubusercontent.com/3036510/42312756-2e898f74-8052-11e8-8982-4e4e30150481.png)
Firs image from Postman Devtools (current view) (2018-07-04_2119)
Secon image from Devtools (shared) (2018-07-04_2120)

**Comment by tigran-m-dev** [comment]
@SamvelRaja  Do I need to create different issue or you will reopen this one?

@thecuriousdev  Screenshots was added (I mentioned you, in case of you don’t seen it yet)

**Comment by thecuriousdev** [comment]
thanks for the information, can you check the state of the sync icon?
![screen shot 2018-07-06 at 12 19 07 pm](https://user-images.githubusercontent.com/22293666/42363960-1ddbc47e-8117-11e8-993f-c8194a9d217c.png)

**Comment by tigran-m-dev** [comment]
@thecuriousdev sync icon is blue and when I am clicking on it it shows message “Connecting”

**Comment by tigran-m-dev** [comment]
@thecuriousdev 
Adding and image
![2018-07-09_2042](https://user-images.githubusercontent.com/3036510/42463965-c1880f4e-83b8-11e8-9507-b324609e6d25.png)

Do you have any thoughts?
