### ISSUE TITLE
Support for PFX / P12 certificate format

### ISSUE THREAD

**Issue by MikeCook9994** [a85/POSTMan-Chrome-Extension#4647]
Explicit duplicate of [#2494](https://github.com/postmanlabs/postman-app-support/issues/2494) for visibility.

The last time there was any input on this issue at all was over a year and a half ago. It's been commented on many times and we've asked for status updates and we've gotten nothing. I don't want to clutter your bug page with obvious duplicates, but I also would love this feature request to actually get looked at even more.

**Comment by vkaegis** [comment]
@MikeCook9994 Thanks for writing in! I understand the importance of this feature request, but creating a duplicate makes it harder for us to manage them. :( 

As for an update, this is not under active development just yet. We are quite thorough in going through any Github issues around features under active development, so I wouldn't worry about #2494 getting overlooked. Closing this for now.
