### ISSUE TITLE
Scroll not working on Collections panel

### ISSUE THREAD

**Issue by ionutincau** [a85/POSTMan-Chrome-Extension#4649]
version Postman v6.1.3

**Comment by sivcan** [comment]
@ionutincau Could you provide a gif / a video as to where you're facing this issue and how can we reproduce this ?

**Comment by oaxoh** [comment]
Previous version:
![1](https://user-images.githubusercontent.com/15733702/41083814-718832b6-6a32-11e8-9cc7-b7a7f11020e7.gif)
Postman v6.1.3:
![2](https://user-images.githubusercontent.com/15733702/41083830-7e1a2462-6a32-11e8-804a-ee4c954f0de7.gif)

**Comment by sivcan** [comment]
@edonelezovic Thank you for reporting this. 
Apologies for the inconvenience caused, I was able to reproduce it and we'll look into fixing this soon.
I'll update this thread once the fix is out.

**Comment by prashantagarwal** [comment]
Related to #4748
