### ISSUE TITLE
Set-Cookie is not working

### ISSUE THREAD

**Issue by Spelieye** [a85/POSTMan-Chrome-Extension#4653]
Please read through the [guidelines](https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues) before creating a new issue.

**Describe the bug**
Set-cookie is not setting or saving cookies when a HTTP request is made. 

**To Reproduce**
1. Make a POST query
2. Click Send then Headers. The Set-Cookie shows a new cookie to be set/saved
3. Click on Cookies 
4. No new cookie is created or saved

**Expected behavior**
When the Set-Cookie header function is called it should save and update the cookies for the curretn working session.  

**Screenshots**
Cookie being set:
![screen shot 2018-06-05 at 6 22 12 pm](https://user-images.githubusercontent.com/36861919/41010606-6582a5fa-68ed-11e8-84c3-e6dc18437afe.png)
However the cookie is not saved or updated
![screen shot 2018-06-05 at 6 22 30 pm](https://user-images.githubusercontent.com/36861919/41010612-6e0eca14-68ed-11e8-81a9-845352fb1b10.png)

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version: 6.1.3
 - OS: macOS High Sierra 10.13.4

**Comment by terrencewei** [comment]
Duplicate with https://github.com/postmanlabs/postman-app-support/issues/4581, and their guys still working on it.

**Comment by harryi3t** [comment]
Yes, the fix is already available in our [canary build](https://www.getpostman.com/canary) and will be available in our next production release (6.2.0).
