### ISSUE TITLE
Saved http request does not show all http verbs

### ISSUE THREAD

**Issue by sumadhuram456** [a85/POSTMan-Chrome-Extension#4654]
Hi,

I saved a http request into a folder in a collection. when I opened the request again, all http verb actions are not available for the saved request.

![2018-06-06_1053](https://user-images.githubusercontent.com/25096417/41018630-5eb1a916-6978-11e8-8b15-b4c947e232a5.png)

**Comment by dhineshwiz** [comment]
Hey @sumadhuram456, we have fixed this UI issue. can you please update to latest version of postman and check.

**Comment by sumadhuram456** [comment]
Hi, I am already using latest version 6.1.3 and i have this issue

**Comment by Maco03** [comment]
I'm having the exact same issue.

Postman for Windows
Version 6.1.3
win32 10.0.14393 / x64

![image](https://user-images.githubusercontent.com/1147006/41403554-6f4411e4-6fc5-11e8-90be-7736e2dfa37c.png)

**Comment by prashantagarwal** [comment]
Guys we have fixed this internally, fix will most probably be released next week.

**Comment by sumadhuram456** [comment]
Hi, I have updated to latest version 6.1.4. Still this issue exist.

**Comment by prashantagarwal** [comment]
This is fixed in our latest Postman app.
