### ISSUE TITLE
Inconsistency in history of API requests

### ISSUE THREAD

**Issue by shubsaini09** [a85/POSTMan-Chrome-Extension#4655]
**Describe the bug**
History disappears automatically. As seen in the below image i don't see daily history of my requests. Some random date's history is preserved by postman. Is it a expected behavior? What is the maximum period of time one can see their history?  

**Expected behavior**
History report for daily should be visible. 

**Screenshots**
![image](https://user-images.githubusercontent.com/12813253/41030040-ffffca38-699a-11e8-97e7-049d1af8be24.png)

**App information (please complete the following information):**
 - Native App
 - Postman Version 6.1.3
 - Windows 7 64bit

**Comment by numaanashraf** [comment]
@shubsaini09 This issue has been fixed in the latest version of Postman Desktop app (v7.3). Please update and let us know if you are still facing this issue.
