### ISSUE TITLE
Postman 6.1.3 (32 and 64bit) Will Not Start

### ISSUE THREAD

**Issue by atom0s** [a85/POSTMan-Chrome-Extension#4657]
Please read through the [guidelines](https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues) before creating a new issue.

**Describe the bug**
After upgrading to the latest Postman (6.1.3) for Windows, the application will not start. Instead, it just constantly keeps trying to create new Postman.exe processes over and over non-stop.

**To Reproduce**
1. Download latest Windows version.
2. Install latest version.
3. Attempt to run Postman.

**Expected behavior**
I expect the program to work / load.

**Screenshots**
N/A

**App information (please complete the following information):**
 - App Type [e.g. Chrome App, Native App] - Native App
 - Postman Version [e.g. 6.0.1] - Postman 6.1.3 (32/64bit happens on both)
 - OS: [e.g. macOS High Sierra 10.13.2] Windows 8.1 Pro

**Additional context**
N/A

**Comment by thecuriousdev** [comment]
Hey @atom0s, thanks for reporting this

This may be related to a known issue where Postman doesn’t launch with certain GPUs. A workaround for this issue involves disabling your GPU, and detailed instructions on how to do that can be found via the link below.

https://github.com/postmanlabs/postman-app-support/issues/4594

**Comment by atom0s** [comment]
Thanks @thecuriousdev that did fix the issue for me.

This seems more like an OS issue than a GPU one I think. I'll leave more details on that ticket though.

**Comment by dsnkostic** [comment]
+1 For this issue.
As soon as I updated Postman to the newest version 6.1.3. on Windows 8.1, it just won't start. All what I see is empty Postman window with only a border. No menus, no nothing, and mouse icon is constantly switching between 'loading' and 'normal'.

**Comment by prashantagarwal** [comment]
@dsnkostic please refer #4594 for the workaround.

**Comment by usernameistai** [comment]
version 6.2.3 same issue as dsnkostic

**Comment by hardy-devnix** [comment]
For version 6.2.3 and windows 8.1 professional version , I am facing same issue as dsnkostic

**Comment by HelgeSverre** [comment]
Same for version 6.3.0 on Windows 8.1, GPU: Nvidia NVS 510.

"POSTMAN_DISABLE_GPU=true" workaround works

**Comment by nhhockeyplayer** [comment]
this product refuses to install or do anything

**Comment by KenanHArik** [comment]
> Same for version 6.3.0 on Windows 8.1, GPU: Nvidia NVS 510.
> 
> "POSTMAN_DISABLE_GPU=true" workaround works

this worked for windows 7 for me. To clarify these settings need to be changed in the environment variables.

**Comment by naveed1234567** [comment]
![Screenshot_2](https://user-images.githubusercontent.com/49415120/56096646-6aedfb80-5f04-11e9-8373-75c978cb2bc1.png)
After downloading Postman I am getting this error plz help me out
