### ISSUE TITLE
GET request with Body

### ISSUE THREAD

**Issue by ironmanMA** [a85/POSTMan-Chrome-Extension#4661]
there are some APIs that are designed to take JSON body as param.
Eg: Elastic search APIs.

right now i use a python util for this.
Postman could support this?

**Comment by dhineshwiz** [comment]
Hey @ironmanMA  thanks for the suggestion, will add it as feature request

**Comment by harryi3t** [comment]
@ironmanMA Seems this feature request is being tracked here https://github.com/postmanlabs/postman-app-support/issues/2729
Closing this in favour of the original issue.
