### ISSUE TITLE
Code, cURL fails to expand the environment substitutions

### ISSUE THREAD

**Issue by robertkuhar** [a85/POSTMan-Chrome-Extension#4662]
**Describe the bug**
Code, cURL fails to account for environment expansions.  This greatly reduces the utility of this feature as I have to go re-edit the result rather than just "Copy to Clipboard" and run in a shell.  Yuk.

**To Reproduce**
1. Select a request with a {{something}} environment substitution
2. Select an environment in the drop down
3. Send the request
4. Click on "Code" and select CURL from the drop-down

**Expected behavior**
Expected to see a wholly formed cURL command

**Actual behavior**
curl command does not show substitutions from the environment.

**Screenshots**
<img width="673" alt="screen shot 2018-06-07 at 9 24 28 am" src="https://user-images.githubusercontent.com/190304/41113156-c1421da0-6a35-11e8-9768-c8e733216730.png">

**App information (please complete the following information):**
 - Postman Version 6.1.3 (6.1.3)
 - OS: macOS High Sierra 10.13.5

**Comment by thecuriousdev** [comment]
Hey @robertkuhar thanks for reporting this issue, I couldn't re-produce this issue from my end (Postman 6.1.14, macOS High Sierra). Is the variable getting resolved in places otherthan code generator?

**Comment by thecuriousdev** [comment]
@robertkuhar I am assuming your problem is fixed. Closing this for now, feel free to reopen this if you are facing any trouble.
