### ISSUE TITLE
Silently Removes Multiple Slashes After Base URL

### ISSUE THREAD

**Issue by jamesgoodhouse** [a85/POSTMan-Chrome-Extension#4663]
**Describe the bug**
Multiple slashes after the base URL are being silently removed by Postman.

**To Reproduce**
1. Start a local webserver
2. Use Postman to make a GET request to `http://localhost///route`
3. Observe in the webserver logs that the request came in as `/route`
4. From the CLI, run `curl http://localhost///route`
5. Observe in the webserver logs that the request came in as `///route`

**Expected behavior**
I expect postman to send requests exactly as I intended, slashes and all.

**Screenshots**
<img width="885" alt="screen shot 2018-06-07 at 12 01 12 pm" src="https://user-images.githubusercontent.com/4684194/41120491-88219914-6a4a-11e8-947a-f14b88dd1711.png">

**App information (please complete the following information):**
 - macOS Sierra 10.12.6 (16G1314)
 - Postman 6.0.10 (native)

**Additional context**
This problem was unearthed when a website we were successfully hitting with an accidentally formatted URL that included double slashes was updated and no longer routing the double slashes the same way as before. In debugging this, we used Postman and were unable to reproduce the error. Only after deciding to try cURL and successfully reproducing the error did we realize that Postman was silently stripping the extra slashes, causes real headaches for us.

**Comment by kamalaknn** [comment]
This issue has been fixed in our library `postman-collection` we use for parsing URLs. We'll push this fix out on the stable channel soon.

**Comment by daniel-white** [comment]
@kamalaknn any eta?

**Comment by kamalaknn** [comment]
This has been released on `postman-collection` as `3.2.0`. We'll update the library in the Postman app and release it in the upcoming releases.

**Comment by harryi3t** [comment]
@jamesgoodhouse 
This is fixed in the latest version of Postman 6.3.0 🎉 
![multiple-slashes](https://user-images.githubusercontent.com/5207331/45155332-4906fa80-b1f8-11e8-9deb-1d46799d2205.png)

**Comment by DerFlash** [comment]
*cry* I took this previous behavior as a feature ;-)
We have a lot of paths containing variables as optional path structure .../{{resourcePath}}/... which previously worked like a charm in resulting in a single slash .../... .
Now it's a ...//... then which failed our requests. 😢

For sure the new behavior is absolutely ok, but I need to fix all our collections.

Is there any nice way to add the second forward slash depending on the parameter? Or do I need to include the slash into the parameter itself?

**Comment by kamalaknn** [comment]
Hi @DerFlash 

I understand that this could be painful to fix. Right now you might have to set the path with slashes in your variable.

Have you tried out the global find feature? You can easily find for something across all your collections with this. Try `cmd/ctrl + shift + F` or the Search icon in the bottom bar.

 
<img width="1284" alt="image" src="https://user-images.githubusercontent.com/8401064/45486005-30a65b00-b777-11e8-8a97-ee09138ba4a7.png">

**Comment by DerFlash** [comment]
Hey @kamalaknn 

thanks for the perfect hint. 74 results, but at least I got them all ;-)
