### ISSUE TITLE
Can't leave or delete my own team workspace

### ISSUE THREAD

**Issue by bean5** [a85/POSTMan-Chrome-Extension#4665]
Please read through the [guidelines](https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues) before creating a new issue.

**Describe the bug**
When I try to delete via the app, it doesn't let me click on "Delete". On the website, I click delete, and it says "You are not permitted to perform the action."

If I try to leave, it says I am not allowed to remove all members of the workspace.

**To Reproduce**
1. Create a new account
2. Create some collections and environments
3. Create a new workspace making sure to import some collections and environments
4. Try to leave/delete the workspace (note: I had to join the workspace I had just created before I had the option to try to leave.

**Expected behavior**
I should be able to delete a team/workspace that I created at will, even if I am the last member of the team.

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version: 6.1.3
 - OS: Ubuntu 16.04

**Additional context**
Because I cannot delete nor leave, my account is going to run into issues unless I upgrade, which is not what I want at this time.

**Comment by sivcan** [comment]
@bean5 The 'Team Workspace' and 'My Workspace' created by default in the app cannot be deleted.
These are special workspaces which will stay in the app.
You can remove all the members of your team from that workspace (at least 1 member should be there).

This is an intended behavior.

**Comment by spimentel3** [comment]
So I made a team thing because I thought it would be fun to see what it enabled me to do. Surpassed 50 requests, and my project got archived and I was told to upgrade. Well I ended up being the only one using the workspace, can I disband the team thing and get my collection back?

**Comment by sivcan** [comment]
@spimentel3 You can follow the answer here https://community.getpostman.com/t/archived-collection/2679

**Comment by spimentel3** [comment]
Oh thank you so much!!!
________________________________

**Comment by fendis0709** [comment]
@sivcan Thanks man... I was accidentally shared my collection to my team. After several days, my collection that I was shared become archived.

**Comment by henk9** [comment]
> @spimentel3 You can follow the answer here https://community.getpostman.com/t/archived-collection/2679

Direct link explaining how to become a single user again - https://community.postman.com/t/archived-collection/2679/6.

**Comment by vanilla-thunder** [comment]
you guys need to simplify and unify your interface a bit.
Call things as they are, and do not use those stupid "stars" and "satellites" placeholders. I suddenly had this "star" *whatever* that looked like a team, but i named my team differently and whenever you click on "manage team" you suddenly get redirected to the website and all of a sudden this "star" thing is not a team anymore, but a teams workspace. (why then forcing people to use this useless app if you still need to use website?) But after deleting my team, this thing was still there. holy molly...

totally wasted my time on this overhyped tool.

**Comment by akshay-kulkarni-03** [comment]
@vanilla-thunder could you please share a video/image about the issue you are facing?
