### ISSUE TITLE
Upgrading to Postman 6.1.3 has broken my app

### ISSUE THREAD

**Issue by failpunk** [a85/POSTMan-Chrome-Extension#4666]
**Describe the bug**
I used the Postman in-app update to upgrade to V6.1.3 and now my Postman Mac application will not start. It hangs at the splash screen indefinitely.

**To Reproduce**
1. Opened Postman
2. Went though app auto-update process
3. Upgraded to 6.1.3
4. App will not load

**Expected behavior**
The application should work.

**Screenshots**
The following error shows in the dev tools console.

``` javascript
vendor-shared.js:85036 Error in the app boot sequence Error: Could not find default workspace while booting session
    at Object.then.then.defaultWorkspace (requester.js:12671)
    at <anonymous>

console.error @ vendor-shared.js:85036
vendor-shared.js:52146 Could not find on WorkspaceStore. Missing or invalid parameter.
find @ vendor-shared.js:52146
vendor-shared.js:85036 TypeError: Cannot read property 'getShortcuts' of undefined
    at Requester.render (/Applications/Postman.app/Contents/Resources/app/js/RequesterInit.js:3502)
    at h (vendor-ui.js:7539)
    at beginWork (vendor-ui.js:7542)
    at d (vendor-ui.js:7570)
    at f (vendor-ui.js:7570)
    at g (vendor-ui.js:7571)
    at m (vendor-ui.js:7578)
    at w (vendor-ui.js:7577)
    at z (vendor-ui.js:7576)
    at u (vendor-ui.js:7574)
    at Object.enqueueSetState (vendor-ui.js:7517)
    at LoadableComponent.webpackJsonp.734.A.setState (vendor-ui.js:7392)
    at update (requester.js:15915)
    at requester.js:15925
    at <anonymous>

console.error @ vendor-shared.js:85036
vendor-shared.js:85036 WorkspaceSession not found in DB
```

**App information (please complete the following information):**
 - Mac App
 - Postman Version 6.1.3
 - OS: macOS High Sierra 10.13.4

**Comment by failpunk** [comment]
PostmanCanary Version 6.2.0-canary02 (6.2.0-canary02) seems to work fine.

**Comment by thecuriousdev** [comment]
@failpunk thanks for reporting this issue. We made a fix for this and its available in canary..

**Comment by MarcosEich** [comment]
Hey guys, version 6.4.4 here and still getting this issue.

**Comment by E1337Kat** [comment]
ya, I also am having a similar issue when trying to run through my companies Oauth2 strategy. I can log-in then make the call to `/oauth/authorize`, and everything is fine. But when I make the POST to `/oauth/token` with all correct info, the authentication fails and the devTools console shows like 2 warnings for this issue.

I can provide more details and even a login to use to test self if needed.

**Comment by cNoveron** [comment]
Hey guys it's may 2020, I'm having the same problem with v6.7.6. What's the deal, seriously? Why is this issue closed???

**Comment by arlemi** [comment]
@carlosescom The latest version of the app is 7.25.0. v6.7.6 is ~a year old, I would recommend updating it. 
If you're a team user, you can find detailed information about how to migrate from v6 to v7 in the Learning Center: https://learning.postman.com/docs/administration/migrating-to-v7/

**Comment by cNoveron** [comment]
> @carlosescom The latest version of the app is 7.25.0. v6.7.6 is ~a year old, I would recommend updating it.
> If you're a team user, you can find detailed information about how to migrate from v6 to v7 in the Learning Center: https://learning.postman.com/docs/administration/migrating-to-v7/

@arlemi 
Nowhere in the dashboard can I see such a thing as "Migrate my team to v7".

Also, there is nothing along the lines of "Check for Updates." in Settings > Update. All I see is:
>You're up to date!
>
>You’re on v6.7.6. Snap will automatically update Postman whenever a new version is released.
>
>Having trouble with updates?

**Comment by cNoveron** [comment]
For anyone still having this ungodly issue by 2025 or beyond: just remove and reinstall using snap, like this
```
snap remove postman
snap install postman
```
