### ISSUE TITLE
Can't see diff in Activity tab

### ISSUE THREAD

**Issue by ytang-legion** [a85/POSTMan-Chrome-Extension#4668]
**Describe the bug**
see title when two team members in a team sharing a Collection and one of them try to make a change. The other team member should be able to see Activity plus the diff. But I can't see the diff

**To Reproduce**
1. Go to postman Version 6.1.3 (6.1.3). Pick an existing collection
2. type any change like adding a console logging in pre or test tab
3. Open another postman app Version 6.2.0-canary02 (6.2.0-canary02) 
4. Can see the changes but no diff
![image](https://user-images.githubusercontent.com/32074776/41132143-31cd51d2-6a74-11e8-8f82-9e02779a1026.png)

**Expected behavior**
See above. I am with Vineet Kumar @ POST|CON when I saw this issue

**Screenshots**
See above

**App information (please complete the following information):**
 - see Abvoe

**Additional context**
To get Postman to be adopted by my engineering team, we need to be able to see each other's diff

**Comment by thecuriousdev** [comment]
@ytang-legion thanks for reporting this issue, I'll look into this.

**Comment by thecuriousdev** [comment]
Hey @ytang-legion, We made a fix for this and its available in the latest Postman Canary. We are making more improvements in activity feed, stay tuned!

![screen shot 2018-07-17 at 1 41 28 pm](https://user-images.githubusercontent.com/22293666/42804630-2bbf61fa-89c7-11e8-8962-5528bbdac9b8.png)

**Comment by thecuriousdev** [comment]
@ytang-legion you can download the Canary build from https://www.getpostman.com/canary

**Comment by ytang-legion** [comment]
Cool! Can't wait to consume it. Thanks!
Yanming
