### ISSUE TITLE
Export file does not properly update the request raw url

### ISSUE THREAD

**Issue by vdespa** [a85/POSTMan-Chrome-Extension#4669]
**Describe the bug**
It seems that once a collection is imported and has duplicate query parameters, removing them will not fix the export.

**To Reproduce**
1. Import this file (remove txt extension): 
[BUG.postman_collection.json.txt](https://github.com/postmanlabs/postman-app-support/files/2085520/BUG.postman_collection.json.txt)

2. Notice that is has duplicate query parameters.

![screen shot 2018-06-08 at 06 27 21](https://user-images.githubusercontent.com/1197635/41173725-3b0a39c4-6b58-11e8-923b-a542b23c63cd.png)

3. Remove all duplicate parameters, save and export.

> key:{{trelloKey}}
> token:{{trelloToken}}
> name:{{boardName}}
> defaultLists:false
> boardStars:mine
> cardscards:none
> prefs_background_url:https://images.unsplash.com/photo-1525707662507-835b59f8ebfd?key={{trelloKey}}
> token:{{trelloToken}}

4. Check the exported JSON or re-import the newly exported collection. The duplicate params are back.

**Expected behavior**
Upon saving and exporting, the problem should correct itself and export what is shown by the GUI.

**App information (please complete the following information):**
 - App Type defaultLists
 - Postman Version 6.1.3
 - OS: macOS High Sierra

**Additional context**

**Comment by thecuriousdev** [comment]
@vdespa thanks for reporting this issue. I am able to reproduce this from my end, will look into this.

**Comment by thecuriousdev** [comment]
@vdespa this is fixed. Will be available in Postman 6.2.0 or higher.
