### ISSUE TITLE
When selecting text in a modal, releasing cursor outside of modal closes modal and doesn't save changes

### ISSUE THREAD

**Issue by GYatesIII** [a85/POSTMan-Chrome-Extension#4670]
**Describe the bug**

**To Reproduce**
1. Edit anything that opens a modal with a large text area, like a collection
2. Select text in the text area and while holding down the mouse drag the cursor outside of the modal
3. Release the mouse and note how the modal closes without any confirmation prompt

**Expected behavior**
Ideally the text should be selected and the modal should remain open or at least the app should warn the user they are about to lose unsaved changes and provide an opportunity to cancel.

**Screenshots**
See video here.
https://cl.ly/0f0L1N1f3227

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version: 6.1.3
 - OS: macOS High Sierra 10.13.4

**Comment by thecuriousdev** [comment]
@GYatesIII thanks for reporting this issue. I am able to re-produce this issue, We'll look into this.

**Comment by jpmckearin** [comment]
The modal is being dismissed on `mouseup` instead of `mousedown` as one would expect.

**Comment by prashantagarwal** [comment]
@GYatesIII This bug is fixed in latest version of Postman app.
