### ISSUE TITLE
Mac app crash when trying to save any new request

### ISSUE THREAD

**Issue by josemoreG** [a85/POSTMan-Chrome-Extension#4672]
Upgraded to Postman 1.6.3, mac app will crash whenever I try to save any new request.
Also tried Canary Release 2.0, same behavior.
Any way to debug or get native app log?

**To Reproduce**
1. Have an existent call, click "save as".
2. Edit any info and click "Save"
3. App will crash with "Something went wrong" (no info in the debug console)

**App information (please complete the following information):**
 - Native Mac App
 - Postman Version 1.6.3
 - OS: Mac Sierra 10.13.4

**Additional context**
- Never seen a crash in Postman ever before. 
- Interceptor is not enabled.
- Already tried to logout / login. Also tried to uninstall & install. Finally, tried with Canary release (same error).

**Comment by josemoreG** [comment]
I've tested downgrading to 6.0.10.
This is what I'm seeing there:
- Button "Save" is disabled when selecting one specific collection.
- Save works when selecting some specific collections.
- It's possible to save in some other collection and then move to the collection that's disabled.

Smells like something corrupted or limitation in the collection. Any ideas why the button "Save" is disabled?
Couldn't find any similar issue nor useful information in the documentation.

**Comment by thecuriousdev** [comment]
@josemoreG thanks for reporting this issue, can you help us with some screenshots?

**Comment by josemoreG** [comment]
Sure, below is what I see in 6.0.10 (button Save disabled): 
![image](https://user-images.githubusercontent.com/36407317/41228124-840b33be-6d77-11e8-8d6f-e091066d6a7e.png)

**Comment by thecuriousdev** [comment]
@josemoreG please update to our latest release (6.1.3+), and verify the same.

**Comment by josemoreG** [comment]
Ok, issue seems to be fixed after I re-upgraded to 6.1.3 again (3rd time).
