### ISSUE TITLE
NOt able to update multiple records through Postman collection

### ISSUE THREAD

**Issue by priyasuman** [a85/POSTMan-Chrome-Extension#4673]
Please read through the [guidelines](https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues) before creating a new issue.

**Getting 404 bad request when using Postman collection with data driven approach**
I am trying to update 3 records through datadriven approach using Postman collection using PUT request .

**To Reproduce**
1. Go to 'Collection Runner'
2. Click on 'Runner'
3. Scroll down to 'set the environment,iterations and select the csv data file'
4. 

**Expected behavior**
Records are not updating as expected.

**Screenshots**

**App information (please complete the following information):**
 - Postman [e.g. Chrome App, Native App]
 - Postman Version [e.g. 6.1.3]
 - OS: Windows10
[PUT method in JIRA.txt](https://github.com/postmanlabs/postman-app-support/files/2090037/PUT.method.in.JIRA.txt)

**Additional context**
![collection](https://user-images.githubusercontent.com/33960958/41233217-5d4bd9a2-6da6-11e8-9c68-a69c6733850d.png)

**Comment by sivcan** [comment]
@priyasuman 

A couple of questions:
1. What version of the app are you using? Is it the native app or the chrome app?
2. What records exactly are not being updated? The environment / global variables?
3. What should be noticed in the screenshot that's not being reflected and how it should've actually been as expected?

**Comment by priyasuman** [comment]
What version of the app are you using? Is it the native app or the chrome app?
Native Postman app 6.1.3
What records exactly are not being updated? The environment / global variables?
global variables like test case status
What should be noticed in the screenshot that's not being reflected and how it should've actually been as expected?
Actually if u refer my text file ,am trying update the test case status for three test case id but when i use postman collection and run it ,it gives me 400 BAD request.
Not able to upload the csv file.
Please have a look at my text file.
METHOD:PUT

This is the URI :http://vserver121/SpiraTest/Services/v5_0/RestService.svc/projects/27/test-cases

Request Body 
{
    "ArtifactTypeId": 2,
    "ConcurrencyDate": "/Date(1525415853343+0530)/",
    "CustomProperties": [
        {
            "BooleanValue": null,
            "DateTimeValue": null,
            "DecimalValue": null,
            "Definition": {
                "ArtifactTypeId": 2,
                "CustomList": null,
                "CustomPropertyFieldName": "Custom_01",
                "CustomPropertyId": 66,
                "CustomPropertyTypeId": 6,
                "CustomPropertyTypeName": "List",
                "IsDeleted": false,
                "Name": "Sprint Number",
                "Options": [
                    {
                        "CustomPropertyOptionId": 1,
                        "Value": "Y"
                    }
                ],
                "ProjectId": 27,
                "PropertyNumber": 1,
                "SystemDataType": "System.Int32"
            },
            "IntegerListValue": null,
            "IntegerValue": null,
            "PropertyNumber": 1,
            "StringValue": null
        }
    ],
    "IsAttachments": false,
    "ProjectId": 27,
    "ActualDuration": null,
    "AuthorId": 108,
    "AuthorName": "Vikram Chinnappa",
    "AutomationAttachmentId": null,
    "AutomationEngineId": null,
    "ComponentIds": [],
    "CreationDate": "/Date(1525415853343+0530)/",
    "Description": "Description",
    "EstimatedDuration": null,
    "ExecutionDate": null,
    "ExecutionStatusId": 3,
    "ExecutionStatusName":"{{ExecutionStatusName}}",
    "IsSuspect": false,
    "IsTestSteps": false,
    "LastUpdateDate": "/Date(1525415853343+0530)/",
    "Name": "Sharyu_Test_API",
    "OwnerId": null,
    "OwnerName": null,
    "ProjectName": "Training",
    "TestCaseFolderId": null,
    "TestCaseId":"{{TestCaseId}}",
    "TestCasePriorityId": null,
    "TestCasePriorityName": null,
    "TestCaseStatusId": 1,
    "TestCaseStatusName": "Draft",
    "TestCaseTypeId": 3,
    "TestCaseTypeName": "Functional",
    "TestSteps": []
}

**Comment by sivcan** [comment]
@priyasuman If I got you clearly, then you're trying to update global variables but those are not being reflected because your requests are failing?

If it's simply not updating the globals then probably you have the 'Persist variables' option turned off before running the request.
Kindly check that.

Also, since you mentioned that 'Not able to upload the CSV file'  would that be the reason why your requests are failing?
Since you're using the iteration data from it?

Can you share the CSV file with me as a zip (Feel free to retract any sensitive information)?
Also, can you describe what is failing? Does any error show up when you're trying to upload the CSV?

**Comment by numaanashraf** [comment]
Closing this issue as this doesn't seem to be related to a defect or a feature request in Postman. We recommend reaching out to the wider Postman community (http://community.getpostman.com/) for further help with using Postman to fulfill your specific use case.
