### ISSUE TITLE
Runner window takes long time to load

### ISSUE THREAD

**Issue by chrisron95** [a85/POSTMan-Chrome-Extension#4674]
Please read through the [guidelines](https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues) before creating a new issue.

**Describe the bug**
Since the last update, the runner window takes an exceptionally long time to load. When I open the window (regardless of whether it opens when I start the whole Postman app or if I just open a new runner window) it takes a good 10-15 minutes for the window to load. Until then it's either just a grey window, or it'll show the collections but doesn't show history and I can't click on anything until it fully loads with history. I checked the DevTools, but it doesn't show anything out of the ordinary, just shows what's being initialized. Also important to note, the regular Postman window works perfectly fine while I'm waiting for the runner window to load.

**To Reproduce**
Simply open a runner window.

**Expected behavior**
It should load up right away as it always has

**Screenshots**

It will look like this for a long time however nothing is clickable until the history and everything fully loads.
![screen shot 2018-06-11 at 9 49 20 am](https://user-images.githubusercontent.com/16259311/41235507-f4366c00-6d5c-11e8-8973-702085aa28f6.png)

DevTools:
![screen shot 2018-06-11 at 9 48 55 am](https://user-images.githubusercontent.com/16259311/41235425-cb1002b4-6d5c-11e8-912e-3e98bd19f02e.png)

**App information (please complete the following information):**
Postman for Mac
Version 6.1.3
OS X 17.4.0 / x64

**Additional context**
I do have several large collections that may be causing it to take longer to load, however I have had these same collections for a long time now and the runner window never took this long to load until the most recent update about a week or two ago.

**Comment by sivcan** [comment]
@chrisron95 Hey, thanks for reporting this issue.
In order to triage this issue quickly can you tell me if you have got an exceptionally big run history?
Do you experience any kind of lag while using the runner after it loads?

In the meantime, I'll try to reproduce this issue on my end.

**Comment by chrisron95** [comment]
@sivcan Yes, I do have a large amount of runs in the history. Granted, not much is stored in the history because even the most recent run doesn't seem to store any responses or anything anymore, but that's a story for another issue. Once it loads, everything runs perfectly fine.

**Comment by sivcan** [comment]
@chrisron95 Will look into it and get back to you.

**Comment by saswatds** [comment]
Hi everyone, in the latest `canary` version of app `7.9.0-canary01` we have made some performance improvements in the Collection Runner. It should now load much faster and with proper loading state. Do check it out and share you thoughts. 

You can download the `canary` app from https://www.getpostman.com/downloads/canary

Thanks

**Comment by saswatds** [comment]
The updates are now available in the production app. We will be closing this issue now.
