### ISSUE TITLE
Postman not saving variable correctly. 

### ISSUE THREAD

**Issue by jproano** [a85/POSTMan-Chrome-Extension#4675]
## App Details:

```
Postman for Mac
Version 6.1.3 (6.1.3)
OS X 10.13.5
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there: Recent Discovery
 2. Expected behavior: Response body of a test response from a server:

[{"id":660903245316620790,"name":"Wayland Corporation"},{"id":660903245316620757,"name":"Client Demo Org"},{"id":780128,"name":"TEST123 LLC"}]

When this gets processed in the console logs (in pretty mode) and in saving variables the two large ID's are getting shifted to 660903245316620800 ; the smaller ID is processed correctly. There seems to be some sort of bug with the handling of the larger numbers. 

This also results in the setting of incorrect variables in the postman environment when using a function like pm.environment.set("OrgID", JSON.stringify(list.id)); when iterating through the list. 

 4. Screenshots (if applicable)
<img width="404" alt="screen shot 2018-06-11 at 10 24 30 pm" src="https://user-images.githubusercontent.com/30084571/41270073-57bf9030-6dc6-11e8-96b0-05c7bd4997e8.png">
<img width="446" alt="screen shot 2018-06-11 at 10 24 43 pm" src="https://user-images.githubusercontent.com/30084571/41270077-5b18a97e-6dc6-11e8-8fd9-79d2933ae30d.png">
<img width="602" alt="screen shot 2018-06-11 at 10 27 19 pm" src="https://user-images.githubusercontent.com/30084571/41270125-b19165e8-6dc6-11e8-8f5e-d5172c1296a4.png">
<img width="304" alt="screen shot 2018-06-11 at 10 24 53 pm" src="https://user-images.githubusercontent.com/30084571/41270131-ba8f6cbc-6dc6-11e8-8936-12f4b1fcf491.png">

**Comment by thecuriousdev** [comment]
@jproano thanks for reporting this issue, I am able to re-produce this issue. We'll look into this.

**Comment by harryi3t** [comment]
@jproano Postman is built on javascript. And in javascript, all numbers are encoded as double precision floating point numbers, following the international [IEEE 754](https://en.wikipedia.org/wiki/IEEE_754) standard
The largest number that can be represented accurately is `2^53-1`. After this, the not all numbers can be represented.

You can try this yourself in a node shell
![image](https://user-images.githubusercontent.com/5207331/41275744-88091cce-6e3f-11e8-97b1-b7ac3fcae8a0.png)
