### ISSUE TITLE
The Edit Windows will close when selecting some text by dragging

### ISSUE THREAD

**Issue by alibaghernejad** [a85/POSTMan-Chrome-Extension#4676]
**Describe the bug**
When you want to select some text in edit folder or edit collection windows by dragging the text, if you put mouse pointer out of the edit window, that window will be close.

**To Reproduce**
1. Go to the collection and expand it
2. Click Right, on a folder and select "Edit"
3. Go to 'Description' tab for example (it work for 'Tests' and 'Pre-request scripts' )
4. Try to select a part of the text by dragging and mouse your mouse cursor out of the window box.
4. See error (The current window will be closed)

**Expected behavior**
The expected behavior that should be happened is that the window stays alive. (Unless it is by design!)

**Screenshots**
![postmancapture](https://user-images.githubusercontent.com/10639835/41273158-8b754c5a-6e2d-11e8-9e4d-88c8c93ef75f.gif)

**App information (please complete the following information):**
 - App Type [Native App]
 - Postman Version [6.1.3]
 - OS: [Windows 10 pro]

**Additional context**
---

**Comment by thecuriousdev** [comment]
@AliBaghernejad thanks for reporting this issue. We'll keep you posted in https://github.com/postmanlabs/postman-app-support/issues/4670
