### ISSUE TITLE
401 Handover not found

### ISSUE THREAD

**Issue by DylanC** [a85/POSTMan-Chrome-Extension#4678]
**Describe the bug**
Cannot view in web with a Collection. 

**To Reproduce**
1. Go to Collection
2. Click on View in web
3. Go to web browser
4. See 401 page with message Handover not found

**Expected behavior**
Should see docs in the web browser like before

**Screenshots**
![pm_bug](https://user-images.githubusercontent.com/4488048/41286257-ab3d5380-6e36-11e8-804b-cc7d3a5bb2f4.png)

**App information (please complete the following information):**
 - App Type Native App
 - Postman Version 6.1.3
 - OS: Windows 10

**Additional context**
Nothing more to add.

**Comment by thecuriousdev** [comment]
@DylanC thanks for reporting this issue, can you verify what's the sync status at that time? 

check the color of this icon,

<img width="367" alt="screen shot 2018-06-12 at 4 48 22 pm" src="https://user-images.githubusercontent.com/22293666/41287541-a9406b2e-6e60-11e8-8d83-175bb0d0f5a1.png">

**Comment by DylanC** [comment]
@thecuriousdev - Mine is blue currently.

**Comment by thecuriousdev** [comment]
@DylanC are you able to make requests and receive responses using postman app at this point?  also can you goto requester window and open DevTools and send me a screenshot of the network tab (Menu > View > Developer > Show Dev Tools Current View) and for shared as well (Menu > View > Developer > Show Dev Tools Shared)

**Comment by DylanC** [comment]
@thecuriousdev - The requests seem to be failing:
![cl_chrome](https://user-images.githubusercontent.com/4488048/41293432-25e8176c-6e4d-11e8-907c-cf3dbc7918e1.png)

Well I don't see any network requests happen.

**Comment by thecuriousdev** [comment]
@DylanC try restart the app once, it'll do the trick. This is a known issue in the app, let us know if you are able to re-produce the issue even after app restart.

**Comment by samvirkar144** [comment]
Hi,
I'm getting same issue before restart my machine. I  shut down the pc and now i'm getting ***we can't seem to find this page*** bug while try to see my collection in web (view in web) from local postman.
[windows 7 , postman 6.1.3 , Chrome app/ browser]
![postman_viewinweb_error](https://user-images.githubusercontent.com/33752583/41392295-7bec9d42-6fbd-11e8-91fa-7c6926eb69eb.png)

Thanks
S

**Comment by thecuriousdev** [comment]
@DylanC this issue if fixed in Postman 6.1.4, please update to the latest version.

Closing this issue for now, but feel free to reopen this if you are facing any further issues.

**Comment by DylanC** [comment]
@thecuriousdev - Seems to be working in 6.1.4 but I will let you know if this issue happens again.

**Comment by thecuriousdev** [comment]
@DylanC happy to hear that :) thanks!
