### ISSUE TITLE
App doesnt start on windows 8.1 x64

### ISSUE THREAD

**Issue by wiedikerli** [a85/POSTMan-Chrome-Extension#4679]
I get a blank white screen when I try to open the app (see screenshot).
![image](https://user-images.githubusercontent.com/2211563/41287756-07fac2a8-6e44-11e8-923f-14085ced7a7c.png)

**What I did:**
- I tried to update via the app, then the error occurd.
- I tried to reinstall the app via the website downloads.
- I deleted all files from postman in the AppData.
- I'm not able to open the console.

**What I'm using:**
 - Native App
 - Postman Version [e.g. 6.1.3]
 - OS: Windows 8.1 x64

Where is the cache from the app?

**Comment by sivcan** [comment]
@ninjaonsafari  - Considering you're on the latest version (The latest version of Postman App as of now is v.6.1.3) if not then download from https://www.getpostman.com/apps

Can you head over to this URL and try the solution provided here:
1. https://www.getpostman.com/docs/v6/postman/launching_postman/installation_and_updates
2. Scroll down to **Troubleshooting Postman Updates**

**Comment by wiedikerli** [comment]
Nice! With the gpu disabled it works.

Thanks for your fast response!

**Comment by manendra-impactqa** [comment]
After disbable POSTMAN_DISABLE_GPU = true; its working. Thanks

**Comment by shawnzxx** [comment]
Great solution, I encountered the same issue which was using Windows 8, change POSTMAN_DISABLE_GPU = true settings saved my life.

**Comment by AugustoNeves** [comment]
Awesome!!

**Comment by lazarporter** [comment]
Thank you, this worked like a charm!

**Comment by sudheerkaushik** [comment]
For those who don't understand what these guys are talking about, here is the link : https://github.com/postmanlabs/postman-app-support/issues/4594


for steps to resolve with screenshots.

**Comment by treetechnox** [comment]
it's working even for the last version 6.7.3, thank you

**Comment by j2rojasr** [comment]
If for some reason you do not have permission to add variables to the system, try using Git Bash in the terminal:

`setx POSTMAN_DISABLE_GPU "true"`

![image](https://user-images.githubusercontent.com/6734861/56237957-e958b380-6052-11e9-8a77-8697a832f3f9.png)

**Comment by ghost** [comment]
it works, thanks

**Comment by polaris018** [comment]
Thanks alot. good works!

**Comment by Kotsuha** [comment]
Thanks a lot!
