### ISSUE TITLE
After saving the request that had a body and changing it to GET, the body is still in the "Code" snippet

### ISSUE THREAD

**Issue by theholiday** [a85/POSTMan-Chrome-Extension#4680]
Please read through the [guidelines](https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues) before creating a new issue.

**Describe the bug**
Have a request with a body.

**To Reproduce**
1. Select the request with the body.
2. Save it as another request and change the method to GET via "Save As".
3. Navigate to the "Code" screen and observe the request snippet in any format (cURL for example)

**Expected behavior**
3. There's no body from the previous request.

**App information (please complete the following information):**
 - Native App
 - 6.0.10
 - Ubuntu 16.04

**NOTE**
So the problem is that I can't edit the body of a GET request on the UI, but since the request was copied it's in the "Code" snippet.

**Comment by harryi3t** [comment]
@theholiday  I was able to reproduce this. We are looking into this

**Comment by theholiday** [comment]
Glad to hear it, thanks.

**Comment by djdmbrwsk** [comment]
@harryi3t note you don't have to save for this bug to occur

**Comment by sujayvenaik** [comment]
Duplicate issue for 
https://github.com/postmanlabs/postman-app-support/issues/3920
