### ISSUE TITLE
Postman-win64-6.1.3-Setup.exe fails on Windows 7 64-bit machine

### ISSUE THREAD

**Issue by markwest1** [a85/POSTMan-Chrome-Extension#4681]
**Describe the bug**
Installing postman 6.1.3 on 64-bit Windows 7 fails.

**To Reproduce**
1. Go to 'https://www.getpostman.com/apps'
2. Click on 'Postman for Windows (64-bit)' to download installer.
3. Run installer.
4. See error.

**Expected behavior**
Installation succeeds.

**Screenshots**
![2018-06-11 13_28_57-error](https://user-images.githubusercontent.com/8137897/41300852-5876bfce-6e2c-11e8-95b6-0b9a9771f841.png)

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version: 6.3.1
 - OS: Windows 7, 64-bit

**Additional context**
Tried:
(1) rebooting machine
(2) click `Unblock` on installer details `.exe` file
(3) uninstalling/reinstalling
(4) Selecting `Run this program as administrator`.

**Comment by harryi3t** [comment]
@markwest1 Thanks for reporting the bug. We are looking into it.

**Comment by SamvelRaja** [comment]
@markwest1 Could you try opening the app manually through `cmd` from `c:\users\[USER]\AppData\Local\app-6.1.3\Postman.exe`

**Comment by SamvelRaja** [comment]
Closing this for now. Feel free to re-open this if you still face this issue.
