### ISSUE TITLE
Black boxes on install, strange errors in Squirrel log

### ISSUE THREAD

**Issue by gearskullguy** [a85/POSTMan-Chrome-Extension#4683]
Please read through the [guidelines](https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues) before creating a new issue.

**Describe the bug**
I just downloaded and installed Postman - https://app.getpostman.com/app/download/win64?_ga=2.231025439.1046642363.1528850467-1230455851.1528850467 - however during install, boxes popped up that just contained black, one of them forced itself on top of everything else, and the only way I get it to finish was to close the box after getting a "not responding" cancel box... it then opened Postman as if everything was fine, but also opened a SquirrelSetup.log file, which contained a bunch of strange errors.

**Screenshots**
![image](https://user-images.githubusercontent.com/32692076/41324367-607065dc-6e71-11e8-8af9-7c556fe0c944.png)

I would paste/attach the Squirrel log, but I haven't gone through it all to see if it contains potentially sensitive info about my system. There was some concerning errors however... the program seems to want modify my TaskBar .lnk buttons; here's an example:

2018-06-12 18:42:01> ApplyReleasesImpl: Starting fixPinnedExecutables
2018-06-12 18:42:01> ApplyReleasesImpl: Examining Pin: Snipping Tool.lnk
2018-06-12 18:42:01> ApplyReleasesImpl: File 'C:\Users\Dave\AppData\Roaming\Microsoft\Internet Explorer\Quick Launch\User Pinned\TaskBar\Snipping Tool.lnk' could not be converted into a valid ShellLink: System.IO.FileNotFoundException: The system cannot find the file specified. (Exception from HRESULT: 0x80070002)
   at Squirrel.Shell.ShellLink.IShellLinkW.Resolve(IntPtr hWnd, UInt32 fFlags)
   at Squirrel.Shell.ShellLink.Open(String linkFile, IntPtr hWnd, EShellLinkResolveFlags resolveFlags, UInt16 timeOut)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<fixPinnedExecutables>b__11_0(FileInfo file)

Of course I need to know what's going on with the black boxes and if Postman actually installed properly, but why is it related to this Squirrel app and why is that trying to modify my TaskBar buttons?! 

**To Reproduce**
1. What I described above

**Expected behavior**
Install Postman no problem.

**App information (please complete the following information):**
 - App Type: Chrome Version 67.0.3396.79 (Official Build) (64-bit)
 - Postman Version: Latest for Windows - it won't open now for me to check, got another black box - 
![image](https://user-images.githubusercontent.com/32692076/41324601-975dc87c-6e72-11e8-89bc-7ca96429ddbc.png)
UPDATE: OK it finally opened and the version is 6.1.3
 - OS: Windows 7 Pro 64-bit

**Additional context**
I've had this same issue with other apps such as Slack and HandBrake.

**Comment by chrisdeso** [comment]
@davelogear This looks similar to [issue #4594](https://github.com/postmanlabs/postman-app-support/issues/4594). 

Does launching the app via the command prompt with the GPU disabled flag `--disable-gpu` yield any results?

**Comment by harryi3t** [comment]
@davelogear As suggested by @chrisdeso, can you try the steps as mentioned here https://github.com/postmanlabs/postman-app-support/issues/4594#issuecomment-391601621

**Comment by gearskullguy** [comment]
It just eventually appeared normal after like 6 minutes... the program is installed so there's no need for me to try to install it again.

I'm just reporting it here because it happened over multiple attempts, and the exact same thing happened with other programs, and I think they all use Electron, so maybe something in Postman is triggering something with Electron.
