### ISSUE TITLE
Could not get any response error running from behind the proxy

### ISSUE THREAD

**Issue by bhanupinninti** [a85/POSTMan-Chrome-Extension#4684]
Hi Team,

We are using native postman 6.1.3 (latest). We encountered "Could not get any response" error while doing a post request to our API.

Newman Version- Postman 61.3
OS details - Windows 7 prof
Are you using Newman as a library, or via the CLI?  Yes, with newman CLI also facing "tunneling socket could not be established, statusCode=403" error.

Did you encounter this recently, or has this bug always been there: Recently
Expected behaviour: Should post and get a response
Screenshots -attached including postman console

![image](https://user-images.githubusercontent.com/38074414/41329171-6224814e-6f0f-11e8-81d1-ba039adb3756.png)

![image](https://user-images.githubusercontent.com/38074414/41329190-775b6fa0-6f0f-11e8-8550-1966c811f4f0.png)

**Comment by bhanupinninti** [comment]
adding @kunagpal

**Comment by harryi3t** [comment]
@bhanupinninti I suspect that the proxy requires authentication because as of now Postman does not support proxy authentication. There's already a feature request here https://github.com/postmanlabs/postman-app-support/issues/3566. Please subscribe/upvote the issue.

**Comment by bhanupinninti** [comment]
Is there anyway i can send credentials for authenticcation?

**Comment by harryi3t** [comment]
@bhanupinninti It's not supported as of now. You can subscribe to the original issue for updates.
