### ISSUE TITLE
Passing incorrect integer value to API

### ISSUE THREAD

**Issue by kumardeepak32** [a85/POSTMan-Chrome-Extension#4686]
I found one strange issue in postman. In below request amount is integer field.

`{   "merchantId": 49,
  "amount": 020
}`

When I pass Amount 020 instead of 20. In API controller I received amount 16. When I pass 0100 I receive 64.

If I pass in double quotes like "020" or "0100". Then I get 20 and 100.

Can you please check this

**Comment by sivcan** [comment]
@kumardeepak32 

A couple of questions: 
1. What version of the app are you using? Is it the native app or the chrome app?
2. Can you provide the steps to reproduce this issue? (screenshots / gif would be helpful)
3. What API Controller are you referring to?

**Comment by harryi3t** [comment]
@kumardeepak32 

Prefixing a number with 0 makes it interpreted as an octal number

For more information refer https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Numbers_and_dates

> Octal number syntax uses a leading zero.

**Comment by kumardeepak32** [comment]
thanks
