### ISSUE TITLE
POSTMAN does not support TLS v1.0+

### ISSUE THREAD

**Issue by slaman75** [a85/POSTMan-Chrome-Extension#4689]
POSTMAN sends all calls via SSL3.  If your serve disables all protocols other than TLS v1.2, POSTMAN does not work.

In 2014, SSL 3.0 was found to be vulnerable to the POODLE attack that affects all block ciphers in SSL; RC4, the only non-block cipher supported by SSL 3.0, is also feasibly broken as used in SSL 3.0.

This is an URGENT bug, that has been known since January 8, 2018 (https://github.com/postmanlabs/postman-app-support/issues/4038) but inexplicably was closed.

It is a security vulnerability that may be leading us to stop using POSTMAN altogether.

**Comment by prashantagarwal** [comment]
Closing it as duplicate for #4677
