### ISSUE TITLE
Need a button to format source code (indentation, spacing etc) 

### ISSUE THREAD

**Issue by angamardhana** [a85/POSTMan-Chrome-Extension#4691]
Right now the code can get pretty hard to read after coding for awhile as the indentation and spacing can be all over the map. 

So I have to periodically cut and paste the code into something like this site http://jsbeautifier.org/ , then reformat my code there and then copy and past back into Postman.

Otherwise the code gets unreadable pretty fast.

**Comment by prashantagarwal** [comment]
@angamardhana You can use `cmd + b` (or `Ctrl +b`) to pretty format.

**Comment by angamardhana** [comment]
[image: stallone.jpeg]

- j
