### ISSUE TITLE
Post - form-data - Key fields that are disabled still show up in the code preview

### ISSUE THREAD

**Issue by BrianKilby** [a85/POSTMan-Chrome-Extension#4692]
When using "Postman v6.1.3" (latest version), we've noticed that Post - form-data - Key fields that are disabled (unchecked) still show up in the code preview.  We need to be able to disable (manually or programatically) and see the resulting post payload as it will be sent to the endpoint.

![unchecked key fields still in preview](https://user-images.githubusercontent.com/31317573/41385708-5c3b1b76-6f4b-11e8-995b-c4c5ad488a35.png)

**Comment by prashantagarwal** [comment]
@BrianKilby Thanks for reporting this. We will fix this in our upcoming releases.

**Comment by numaanashraf** [comment]
This has been resolved and is verified on Postman v6.6
