### ISSUE TITLE
we cant seem to find this page bug in postman view in web

### ISSUE THREAD

**Issue by samvirkar144** [a85/POSTMan-Chrome-Extension#4694]
Please read through the [guidelines](https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues) before creating a new issue.

**Describe the bug**
I'm unable to see collection in web , Sometimes getting 401 error or we can't seem to find this page.
**To Reproduce**
1. Go to 'Postman Collection'
2. Click on 'View in web'

**Expected behavior**

**Screenshots**
![postman_viewinweb_error](https://user-images.githubusercontent.com/33752583/41391582-1f71a8d6-6fb9-11e8-9e07-65f45dae1db5.png)

**App information (please complete the following information):**
 - App Type [e.g. Chrome App ,Chrome browser]
 - Postman Version [e.g. 6.1.3]
 - OS: [e.g. windows 7]

**Additional context**

**Comment by thecuriousdev** [comment]
@samvirkar144 thanks for reporting this issue, what was the status of sync during that time? 

check the following icon,
![image](https://user-images.githubusercontent.com/22293666/41394570-0f2ce684-6fc8-11e8-8e8d-c68e18b711a0.png)

is it happening for all the collections?

**Comment by samvirkar144** [comment]
Hi,
Icon Color is blue ...
yes , this happening for all collections.
After updating the postman i'm facing the above issue.
Old collection working fine which are created before updating postman. 
Thank you @thecuriousdev 
Thanks,
S

**Comment by thecuriousdev** [comment]
Can you help me with few more details,
Are you able to send requests?
Are you seeing any content in browse view? (toggle build/browser button in the footer section).
Is everything working fine after restarting the app?

**Comment by samvirkar144** [comment]
Hi,
Following are postman console logs:
Now i'm getting **401 Handover not found** bug
![postman_error_logs](https://user-images.githubusercontent.com/33752583/41400975-399936f2-6fdc-11e8-936f-87b777493f3b.png)

Thanks,
S

**Comment by samvirkar144** [comment]
Hi,
Postman Locally working fine , whenever i tried to to see my collection view in web that time i'm getting above errors (401 or we cant seem found this page),
![postman_browser](https://user-images.githubusercontent.com/33752583/41401731-350b7670-6fde-11e8-8df6-5faf5a5cf6bc.png)

Thanks
S

**Comment by thecuriousdev** [comment]
@samvirkar144 we made a fix for this, and its available in the latest version of Postman (6.1.4+). Please verify it once from your end.

Closing this ticket for now but feel free to reopen this if you find any further issues.
