### ISSUE TITLE
Selected enviorment on startup does not populate variables

### ISSUE THREAD

**Issue by ivok** [a85/POSTMan-Chrome-Extension#4696]
Selected environment on startup does not populate variables in saved request. Ypu have to select env again to countinue work...

**To Reproduce**
1. Create environment space. Add variables.
2. Use variable in reuqest (I set url as variable for the environemnt)
3. Save to collection
4. Close Postman and start it again
5. From collection, select saved request. The environemnt is set to last used, as it must be, but the variables are not populated with values keeped in environment settings.
6. You have to unselet and select again the environment to use it properly.

**Expected behavior**
When Postman is started the last selected environment should populate the variables in request.

**App information (please complete the following information):**
 - Native App
 - Postman Version  6.1.3
 - OS: Xubuntu 16.4

**Comment by sivcan** [comment]
@ivok Thanks for reporting this issue.
I was able to reproduce this. 
We'll look into this issue and update the thread once the fix is out.

**Comment by prashantagarwal** [comment]
@ivok We have fixed this internally. We will make this fix available in next release.

**Comment by prashantagarwal** [comment]
Related to #4618

**Comment by sivcan** [comment]
Hey @ivok,
We've released a fix for this on our canary channel.
Can you download it and try it out if it fixes the issue for you?
Download here: https://www.getpostman.com/canary

Thanks!

**Comment by ivok** [comment]
Yes I confirm that it works. I installed the update and the bug is gone :) 

Unfortunately, when I updated the application, it did not run, untill I deleted the user folder. As I sow and other users had this issue also.
