### ISSUE TITLE
Not able to upload zip file using postman

### ISSUE THREAD

**Issue by kunalwattamwar** [a85/POSTMan-Chrome-Extension#4697]
**Describe the bug**
When uploading a zip file through postman to some server, getting below error.

"message": "Unexpected Content-Type header: multipart/form-data; boundary=----WebKitFormBoundary7VBAv5FK8tYmjZoJ"

Please find below preview
> POST /****/0.8/bulk?version=v1 HTTP/1.1
Host: *********
X-TenantID: ********
Accept: application/json
Cache-Control: no-cache

----WebKitFormBoundaryE19zNvXGzXaLvS5C
Content-Disposition: form-data; name="File"; filename="xyz.zip"
Content-Type: application/x-zip-compressed

----WebKitFormBoundaryE19zNvXGzXaLvS5C

**Expected behavior**
File should get uploaded

**Screenshots**
![image](https://user-images.githubusercontent.com/35274301/41400556-148d3256-6fdb-11e8-99b9-2abe035b2149.png)

**Additional context**

**Comment by theholiday** [comment]
What version of postman is that ? Seems super old.

**Comment by kunalwattamwar** [comment]
@theholiday Its the Tabbed Postman - REST Client & version is: 0.8.4.19

**Comment by theholiday** [comment]
This is the repository for this application only https://www.getpostman.com/.

**Comment by kunalwattamwar** [comment]
@theholiday I have installed Postman from your link & now i am able to upload.

I selected "binary" option which was not available in above screenshot.

Thanks.

**Comment by theholiday** [comment]
Glad to help!
