### ISSUE TITLE
Add a picto when a collection is monitored

### ISSUE THREAD

**Issue by Pducou** [a85/POSTMan-Chrome-Extension#4698]
**Is your feature request related to a problem? Please describe.**
Is it possible to add a new picto when a collection is monitored ? 
I saw that you add this picto when a collection is shared, it will be wonderful to have an other one if the collection is monitored 

**Describe the solution you'd like**
Have a picto like when a collection is shared
![image](https://user-images.githubusercontent.com/40263584/41403512-580d3c94-6fc5-11e8-841f-bf54af647bab.png)

**Comment by prashantagarwal** [comment]
@Pducou That's an interesting suggestion. I will forward this to our design team for consideration.

**Comment by DannyDainton** [comment]
Several UI changes through the different versions highlighting which Collections have monitors and a link back from the Monitor to the Collection via the right sidebar.

<img width="1087" alt="image" src="https://user-images.githubusercontent.com/17089546/176893860-c534c545-c7cd-4262-9cd4-cf9a3eb7723e.png">

<img width="1074" alt="image" src="https://user-images.githubusercontent.com/17089546/176893916-8e974804-e648-4722-b4f7-a7c9b62ac0dc.png">

There are also visual health indicators added for the Monitors in the left sidebar

<img width="745" alt="image" src="https://user-images.githubusercontent.com/17089546/176894000-ee533161-355c-4058-87d2-2e08deeb7b6b.png">
