### ISSUE TITLE
Native app fails to initialise, stuck on loading screen

### ISSUE THREAD

**Issue by mkarajohn** [a85/POSTMan-Chrome-Extension#4699]
**Describe the bug**
The app fails to initialise correctly, leaving me stuck in the loading screen

**To Reproduce**
Launch the app

**Expected behavior**
I would expect the app to load normally.

**Screenshots**
![screen shot 2018-06-14 at 15 14 54](https://user-images.githubusercontent.com/3789226/41411752-91b45aec-6fe6-11e8-8e5f-e7b9b58c89f6.png)

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version: 6.1.3
 - OS: macOS High Sierra 10.13.3

**Additional context**
The app was working fine up until a couple of days ago. Suddenly after a machine restart I am having this issue. I have tried reinstalling to no avail.

**Comment by rvdgeest** [comment]
I have the same issue.
App type: Native App
Postman Version 6.1.3
OS: Windows7

![image](https://user-images.githubusercontent.com/40421783/41644370-20f8bd02-746e-11e8-8b8c-afafdc5ee889.png)

**Comment by SamvelRaja** [comment]
Duplicate #4701  @mkarajohn  Requesting you to subscribe to the issue.
