### ISSUE TITLE
Update Mock matching algorithm to match on Accept header

### ISSUE THREAD

**Issue by jameshd** [a85/POSTMan-Chrome-Extension#4700]
Please read through the [guidelines](https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues) before creating a new issue.

**Is your feature request related to a problem? Please describe.**
I was making a Mock server recently and wondered if it was possible to return a different response based on the Content-type the client was passing. e.g. Accept: application/json return a JSON response. Accept: application/xml return the XML response. 

**Describe the solution you'd like**
I would like to be able to pass an accept header and have that taken into account when matching to a mock response to send. 

**Describe alternatives you've considered**
I have worked around the issue for now by naming my responses 404-json or 404-xml and using the `x-mock-response-name` header in the request.  Feels hacky, but it's essentially the same behaviour. 

I'd just like to add, I think Postman is amazing. I learn something new everytime I use it!

**Comment by numaanashraf** [comment]
Thanks for the suggestion @jameshd. I've passed along the feedback to the right folks.

**Comment by frendcarlo** [comment]
I also want to have this feature, for my requirements, I have different token defined in header as custom, different token returns different response.

**Comment by vvs11** [comment]
You can do header matching in mock servers. It should solve your issue.
Could you go through this thread and see if it solves your problem?
https://community.getpostman.com/t/mocked-responses-where-the-url-is-identical/7953
Let us know if you need any more info

**Comment by jameshd** [comment]
@vvs11 has answered this now.
