### ISSUE TITLE
Native app fails to initialise, stuck on loading screen

### ISSUE THREAD

**Issue by SparK-Cruz** [a85/POSTMan-Chrome-Extension#4701]
Splash screen shows "Preparing your workspaces... This might take a few minutes."
I left the computer on yesterday and came back to see the same splash screen still going.

When running from terminal this is the output:
![terminal](https://user-images.githubusercontent.com/1179000/41416798-100b94d4-6fc2-11e8-9f40-ebb97200af9a.png)

I've tried `rm -rf ~/.config/Postman` but nothing changed.

![still loading](https://user-images.githubusercontent.com/1179000/41416890-4f6a29a6-6fc2-11e8-8a58-ba417c576ee7.png)

Native App
6.1.3
Antergos Arch 238

**Comment by trogdor259** [comment]
They fixed this in canary build. if you use that it'll work. Next update should fix you.  See also https://github.com/postmanlabs/postman-app-support/issues/4666

**Comment by mkarajohn** [comment]
Can you open the dev tools and check if you get the same error message in the console as the one shown [here](https://github.com/postmanlabs/postman-app-support/issues/4699) ?

EDIT: Just noticed about #4666. Disregard me.

**Comment by Eli-Goldberg** [comment]
Same here.. Can't use the new postman version at all

**Comment by SamvelRaja** [comment]
@SparK-Cruz  @Eli-Goldberg  Can you try checking for any postman process running? If so, kill them all and restart the app.

**Comment by Eli-Goldberg** [comment]
@SamvelRaja 
rm -rf ~/.config/Postman and killing all open Postman processes did the trick.
Thanks guys

**Comment by SamvelRaja** [comment]
⚠️ @Eli-Goldberg  I would suggest not to do the `rm -rf ~/.config/Postman`  this will delete all your existing data. 
Kindly try only killing postman process alone if it happens again.

**Comment by rulatir** [comment]
But rm -rf ~/.config/Postman will also delete my entire collection of painstakingly crafted requests, right? Is there a way to salvage those?

**Comment by SparK-Cruz** [comment]
I did kill -9 it, as it's the only way to try again.
Deleting the configuration folder didn't change a thing.
I'll wait for the next release, using firefox restclient extension for now (which sucks by the way).

**Comment by trogdor259** [comment]
Just use [PostmanCanary](https://www.getpostman.com/canary), I've been using it since the issue started with no problems at all. No need to delete any settings or anything.

**Comment by SamvelRaja** [comment]
@SparK-Cruz  is it possible to provide your system details. Also, I recommend you to follow the thread [here](https://github.com/postmanlabs/postman-app-support/issues/4359)

**Comment by SparK-Cruz** [comment]
@SamvelRaja Last version fixed it. Thanks.

**Comment by devstc** [comment]
Installing the Canary version got me working again.  I clicked the link that @trogdor259 provided above.  Below are some of the errors I was getting. 

I'm a new user, installed (v6.1.4) for the first time about 5 days ago, and everything was working fine.  Then started having problems for apparently no reason.  I believe an auto-update had been attempted and is when the problems started for me. Following are some of the errors I was seeing:
- The main error that I first started seeing: "Could not get any response.  Why this might have happened: ..."
Other errors as I attempted to troubleshoot:
- "VersionError The requested version (10) is less than the existing version (30)"
- "Could not find on WorkspaceStore. Missing or invalid parameter"... and then reference to a 'vendor-ui.js' file, I think it was
- I was getting stuck on the 'spinning planets' load screen too.

Like I said though, installing Canary version fixed it.

**Comment by mkarajohn** [comment]
I am sorry for resurrecting this issue, but I was away for 9 months, and now that I am back at development, and needed Postman again, I still have this issue in the latest 7.0.6.  Still getting 

```
Error in the app boot sequence Error: Could not find default workspace while booting session
    at Object.then.then.defaultWorkspace (requester.js:5298)
    at <anonymous>
```

I have deleted my Postman config as well, what else can I try? 

UPDATE: Well, deleting everything Postman related from my ~/Library and reinstalling seemed to do the trick
