### ISSUE TITLE
During encoding final dollar-sign removed and not replaced

### ISSUE THREAD

**Issue by Scheevel** [a85/POSTMan-Chrome-Extension#4702]
Hi.  I have an oData query-string I'm using on a SharePoint REST API
query-string looks like this...
`?$select=Person/Title&$expand=Person&$filter=Person/Title eq 'John Doe'`
This query-string works fine in my code however when executed in Postman the filter was not being applied and all results were being returned, unfiltered.
To investigate in Postman I clicked "Code"->"JavaScript"->"jQuery Ajax" and noticed the encoded filter looked like this...
`?%24select=Person%2FTitle&%24expand=Person&filter=Person%2FTitle%20eq%20'John%20Doe'`
Here the dollar-sign in "Person&filter" has been removed and not replaced with '%24'.
Adding the '%24' to the "jQuery Ajax" example code and executing code in a debug window returned the correctly filtered result.
Thank you for investigating ... this is such a helpful product for testing

**Comment by sivcan** [comment]
@Scheevel 

Can you tell us the following?
1. Are you using the native app/chrome app? What's the version? 
2. The latest version of the native app as of now is v6.1.3, if you're not on the latest version then can you update to the same?

Also,
I tried to reproduce this but couldn't.
Here's what I see: 
![image](https://user-images.githubusercontent.com/12631777/41596188-22f143fe-73e7-11e8-8329-a4269e4f0598.png)

Also typing in the name 'Jhon Doe' gives the following code snippet:
![image](https://user-images.githubusercontent.com/12631777/41596243-4adeb0d6-73e7-11e8-8b86-b5f154d3b4a9.png)

**Comment by Scheevel** [comment]
Thanks for your response.  I am using the following version.  I will update this week and see if the issue is resolved with the most recent version. 
Postman for Chrome
Version 5.5.3
win / x86-64
Chrome 67.0.3396.87

**Comment by sivcan** [comment]
@Scheevel The Postman Chrome app has been deprecated.

I highly recommend using the [Native App](https://www.getpostman.com/apps) 
Kindly download the same and update this issue ticket if you're facing it in the native app or not. 
Thanks.

**Comment by SamvelRaja** [comment]
We are not fixing this in our deprecated chrome app due to constraints over the request sending. We any how handled this in our native app. Kindly switch to it 😄
