### ISSUE TITLE
Basic Auth doesn't stick

### ISSUE THREAD

**Issue by JacobAMason** [a85/POSTMan-Chrome-Extension#4704]
# Caused by #4581 and fixed in 6.1.4

When I issue a Post to Login with Basic Auth using [vSphere's Automation REST Resources](https://code.vmware.com/web/sdk/67/vsphere-automation-rest), I can't issue any more requests without seeing an unauthenticated error. I don't believe this is an issue with this Postman collection since it worked fine in 6.0.10, but it could be that the vSphere collection depended upon incorrect behavior.

**To Reproduce**
Using 6.1.3:
1. Authenticate using Basic Auth
2. Issue another request which expects you to have been authenticated
3. Get Auth error

**Expected behavior**
Expected Basic Auth to stick and to allow following requests to be authenticated.

**App information (please complete the following information):**
 - Native App
 - Postman Version 6.1.3
 - OS: macOS Sierra 10.12.6

**Additional context**
This collection is using `Inherit auth from parent` for all requests that aren't the "Login" request, and authorization helper in the collection is `No Auth`. I'll raise this issue with VMware, but wanted to note this here in case this problem has been experienced outside this collection.

**Comment by harryi3t** [comment]
@JacobAMason Would it be possible to share a collection with us that can reproduce the issue?
Also, if you would like to mail us instead of posting publicly, you can send it to help@getpostman.com.
Please add github issue number in the subject.

**Comment by JacobAMason** [comment]
https://raw.githubusercontent.com/vmware/vsphere-automation-sdk-rest/master/samples/postman/vSphere-Automation-Rest-API-Resources.postman.json

from 

https://code.vmware.com/samples/2562/vsphere-automation-rest-api-postman-resources-and-samples

**Comment by harryi3t** [comment]
@JacobAMason 
After taking a look at the collection I found that the basic auth is present only in one request.
Other requests do not have this auth. You need to add the same auth to whichever request you want to use. Alternatively, you can change the collection level auth to use the basic auth. All request can just inherit the auth definition from the parent collection

![postman](https://user-images.githubusercontent.com/5207331/41649299-ecd974f0-7498-11e8-9c29-b011532bbb35.png)
This request's auth is inherited from the parent collection


![postman](https://user-images.githubusercontent.com/5207331/41649352-02e29074-7499-11e8-9cef-cac137229a06.png)
But, the collection does not have any auth, so the request would fail

**Comment by JacobAMason** [comment]
Is there a reason this collection worked in 6.0.10?

**Comment by harryi3t** [comment]
No, it should not work in 6.0.10 too.
If you can share a minimal collection with 1 request that works with 6.0.10 and not with the latest version, it will help us to validate and fix the issue.

**Comment by JacobAMason** [comment]
That'll be a bit difficult without having something backing the API. I don't suppose you happen to have a spare vSphere cluster sitting around?

**Comment by harryi3t** [comment]
@JacobAMason I have a hunch that this could be coz of cookies. In Postman 6.1.3 there was an issue with saving secure cookies. I am guessing that making the login request was also persisting a secure cookie and using this cookie other end-points were working.
This has been fixed in 6.1.4. Can you kindly try this out in 6.1.4 and let me know if this has been fixed?

**Comment by JacobAMason** [comment]
That appears to have been the issue. Everything seems to be working fine in 6.1.4. Thanks!!
