### ISSUE TITLE
Ability to Run Request Without Persisting the Tab

### ISSUE THREAD

**Issue by dapperdandev** [a85/POSTMan-Chrome-Extension#4705]
Please read through the [guidelines](https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues) before creating a new issue.

**Is your feature request related to a problem? Please describe.**
Every time that I select a tab and run it without editing the request, it opens a tab and persists that tab. Oftentimes, I'm just running a login request. This gets pretty messy when running requests between roles.

**Describe the solution you'd like**
Please implement a way for users to run a request without opening a tab. Alternatively, implement a way to open the request in preview mode an only persist if the request is edited or the tab is double-clicked

**Describe alternatives you've considered**
Currently, I use the ellipsis to close all tabs at the end of a session.

**Additional context**
Suggestion: Add an option to the menu that's displayed when you right-click a request to "Run". Also provide a shortcut. The main obstacle I see at the moment is handling the response. It could potentially just show the status code next to the request name, e.g., **POST /api/token  200**

**Comment by a85** [comment]
Hmm. We already have this. If you don't interact with the request or change it in any way, Postman will open a new request in the same tab.

**Comment by dapperdandev** [comment]
@a85: My mistake. I rushed on writing this issue. I updated the request.

Basically, I just don't want to have to close a tab every time I run a login request :)

**Comment by vkaegis** [comment]
@djbreen7 Thanks for the feedback! We'll be tracking this feature request in a similar issue #4568. Closing this for now. Stay tuned for updates!

**Comment by dapperdandev** [comment]
👍  @vkaegis
