### ISSUE TITLE
Explicit 443 is not the same as implicit 443 when using client certificates

### ISSUE THREAD

**Issue by abatishchev** [a85/POSTMan-Chrome-Extension#4707]
**Describe the bug:**

Port is treated literally when client certificate is chosen from settings

**To Reproduce**

1. Go to Settings -> Certificates
2. Add certificate for example.com:443 (specify 443 explicitly)
3. Call https://example.com/ (no 443)
4. Observe error 401 Unauthorized
5. Call https://example.com:443/
5. Observe no error

**Expected behavior**

If port 443 was specified in settings then it's treated the same way if it was omitted.

**App information (please complete the following information):**
 - App Type: Native
 - Postman Version: 6.1.3 win32 10.0.17134 / x64
 - OS: Windows 10 x64 April Update

**Comment by numaanashraf** [comment]
@abatishchev This is a verified bug. We are working on fixing this.

**Comment by qcastel** [comment]
++1 on this one. We are using this feature for Open Banking, in the financial sector, and this bug is really affecting the user experience for our all community: We decided to use postman as a way of documenting/exploring the Open Banking standard, we really like to see this issue fixed soon.

**Comment by pwcremin** [comment]
+1

**Comment by benjefferies** [comment]
Any updates on the fix @numaanashraf?

**Comment by codenirvana** [comment]
We've released a fix for this on our Canary (`version: 7.1.0-canary01`) channel https://www.getpostman.com/canary

@abatishchev @qcastel @benjefferies Please try it out in the Canary version and let us know if you continue to face the issue.
Will update the thread once we release the fix on our stable channel.

**Comment by codenirvana** [comment]
This has been fixed in the latest Postman app.
