### ISSUE TITLE
Postman forgets cookies when sending requests manually

### ISSUE THREAD

**Issue by sebastian-hans-swm** [a85/POSTMan-Chrome-Extension#4708]
## App Details:

```
Postman for Windows
Version 6.1.3
win32 6.1.7601 / x64
```

## Issue Report:
Since version 6.1.3, Postman for Windows does not remember cookies set in responses to manual requests.

Use case: I am testing an application that uses CSRF tokens to protect form submits. When running my collection from the runner, all works as expected and I can see the session cookie left in Postman's cookie store after the run has finished.

When sending the requests manually one after the other, the second request is rejected because the session cookie is missing from the request (and thus validation of the CSRF token fails). Clicking on "Cookies" shows that the session cookie has not been saved in Postman's cookie store.

In version 6.0.10, cookies are saved in this case, and I can click through the requests manually without problems.

**Comment by sebastian-hans-swm** [comment]
Could be related to #4581. My cookies are secure cookies, too.

**Comment by harryi3t** [comment]
@sebastian-hans-swm yes this is duplicate of https://github.com/postmanlabs/postman-app-support/issues/4581
The fix is available in our [canary build](https://www.getpostman.com/canary).
In production, it will be available as part of 6.2.0 release.
