### ISSUE TITLE
"Persist Cookies" option in Collection Runner

### ISSUE THREAD

**Issue by sebastian-hans-swm** [a85/POSTMan-Chrome-Extension#4709]
**Is your feature request related to a problem? Please describe.**
I am testing an application which uses cookies for various purposes and need a clean cookie store for each test. At the moment, cookies set during a collection run always persist and are used in the next run and for manual requests. In order to run a collection multiple times I have to
1. change focus to the main window,
2. click on "Cookies",
3. click the X for each domain,
4. close the cookie manager (because it does not refresh when cookies are recreated during the next run),
5. change focus back to the runner window.

The whole process requires way too much mouse action to be used frequently. For me, it is painful enough to make me want to ditch Postman, which is a really useful tool otherwise.

**Describe the solution you'd like**
I would like to have a "Persist Cookies" option in the collection runner window like the "Persist Variables" option that is already there. If "Persist Cookies" is selected, cookies will persist after the run like they do now; if "Persist Cookies" is not selected, cookies will be cleared after the run.

**Describe alternatives you've considered**
* Deleting cookies programmatically in the pre-request script, as suggested in #3312, would help in certain scenarios, but not in others (because it would also apply when clicking through the requests manually).
* A single-click method (or hotkey) to clear the cookie store would make the manual process less painful, but I would still prefer not to have to do it at all.

**Comment by RuggeriLuca** [comment]
+1 it will helpfull

**Comment by eqj** [comment]
+1 100% of our Postman problems are "did you clear the cookies first?", we don't even want to keep them

**Comment by vikiCoder** [comment]
Hello,

We have added the following options in collection runner to provide more control over cookies while running a collection:
- Run collection without using stored cookies
- Save cookies after collection run

These options are available in [Postman App version 7.1.0 or later](https://www.getpostman.com/downloads/). Below is a screenshot showing off these options in runner window.

Screenshot:

<img width="1440" alt="Screenshot 2019-06-12 at 3 46 18 PM" src="https://user-images.githubusercontent.com/16588032/59343432-7fdee380-8d29-11e9-97e6-a48f865f8be3.png">

**Comment by sebastian-hans-swm** [comment]
Thanks! This is really helpful. 😄

**Comment by ConstantineSF** [comment]
Hello! and what about monitor? does it handle run without cookies? my code that runs without problem in collection runner falls, I think it is because of cookies. Am I right, that code that use cookies will not work in your monitor section, because it handels different, configuration is distincs from what I can set in collection runner, seems nice feature, but it didn't works. with the same code that work in postman. So sad, can some one help?
