### ISSUE TITLE
I may be the only one that needs this, but copy working from the response pane would be nice.

### ISSUE THREAD

**Issue by aking1012** [a85/POSTMan-Chrome-Extension#4714]
Consider the use case where you have an authenticator, and you're testing something for which you need an auth token.  Copy from the response pane being broken means you have to type everything and are subject to typos to paste it in to a curl whatever url or post body.  
  
I frequently open a mousepad window to type the auth token, because copy from the response pane doesn't work and hand type a many character alphanumeric auth token.

**Comment by preethammavin** [comment]
Hey @aking1012 , can you let me know which version of the App you are on. This seems to be working fine on our 6.1.3 version of the App, do update to the latest version and check if that fixes your issue.

**Comment by aking1012** [comment]
I'm one patch behind, but on the linux side.  I'll update and see if it fixes.
