### ISSUE TITLE
Sync icon no longer shows anything other than color

### ISSUE THREAD

**Issue by chrisron95** [a85/POSTMan-Chrome-Extension#4715]
Please read through the [guidelines](https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues) before creating a new issue.

**Describe the bug**
Not a major issue by any means, but the sync icon no longer shows what's going on. It simply changes between orange and blue. It used to show "Syncing" either next to it or when it was highlighted (can't remember the exact placement) but sometimes when postman's going slow I check that to see if it's syncing or not and don't always remember which color means syncing.

**To Reproduce**
Not much to reproduce, just look at the syncing symbol and try to figure out whether it's syncing or not. If you know which color means what, then fantastic. But if you don't know if orange or blue means syncing then you'll be confused

**Expected behavior**
It should show somewhere in text (or something more descriptive than simply color) whether it's syncing or up to date.

**Screenshots**

**App information (please complete the following information):**
Postman for Mac
Version 6.1.3
OS X 17.4.0 / x64

**Comment by sivcan** [comment]
@chrisron95 Surely, we'll add some other indication.

Just to help you out for now:
Orange Icon - The app is in sync with the server
Blue Icon - The app is syncing the data currently

**Comment by venriq** [comment]
I'm using Postman `v6.1.3`, and the syncing process hasn't been working for a few days. I tried everything:

- clicking on the sync button (it's always blue)
- logout and login again
- restarting the app
- reinstalling the app

But the sync never happens. Am I missing something?

**Comment by sivcan** [comment]
@venriq Can you mail us the logs to help@getpostman.com ?

Both of the following:
1. View > Developer > Show DevTools (Current View)
2. View > Developer > Show DevTools (Shared View)

**Comment by venriq** [comment]
Hi @sivcan 
After re-login one more time, the syncing feature worked again for a few minutes (the sync icon was orange), then it went blue and I had to restart the app to be able to sync back.
I sent the email with the Current and Shared View logs.

**Comment by sivcan** [comment]
Hey @venriq, we released a canary build which aims to fix this issue.
Can you try it out and let us know whether it fixes the issue for you?

Download it here: https://www.getpostman.com/canary

**Comment by sivcan** [comment]
@chrisron95 Hey, we've updated the app with a fix around this. (v6.4+)
The sync icon now shows an animation when it's syncing and stays orange once it has finished syncing.

![sync icon - animate - ease-out](https://user-images.githubusercontent.com/12631777/47280718-656ac500-d5f5-11e8-9675-ff31f15fd221.gif)

**Comment by sivcan** [comment]
@chrisron95 We've updated the app with a fix around this.
The sync icon now shows an animation when it's syncing and turns orange once it's done syncing.

![sync icon - animate - ease-out](https://user-images.githubusercontent.com/12631777/47280806-c5fa0200-d5f5-11e8-80f3-2d03a9eefa48.gif)

**Comment by sivcan** [comment]
Hey @chrisron95, we've updated the app with a fix around this. (v6.4+)
The sync icon now shows an animation when it's syncing and turns orange once it's done syncing.

![sync icon - animate - ease-out](https://user-images.githubusercontent.com/12631777/47280806-c5fa0200-d5f5-11e8-80f3-2d03a9eefa48.gif)

**Comment by sivcan** [comment]
@chrisron95 We've updated the app with a fix around this.
The sync icon now shows an animation when it's syncing and turns orange once it's done syncing.

![sync icon - animate - ease-out](https://user-images.githubusercontent.com/12631777/47280806-c5fa0200-d5f5-11e8-80f3-2d03a9eefa48.gif)

**Comment by ttrasn** [comment]
For everyone who comes here, I had this issue and when I changed my VPN connection, it fixed
