### ISSUE TITLE
Postman documentation examples don't show response headers 

### ISSUE THREAD

**Issue by jdavey1996** [a85/POSTMan-Chrome-Extension#4716]
Postman documentation examples show only the response body. Not any response headers. This is useless for requests which return header data and status codes, but no response body.

**Comment by godfrzero** [comment]
@jdavey1996 The response headers are displayed as a part of the generated snippet, so for example if you're using a cURL snippet it should show up as the `--header`.

Are you not seeing the headers in the snippet?

**Comment by vkaegis** [comment]
@jdavey1996 Thanks for writing in! Documentation generated in Postman shows the response headers as part of the "Example Response" section on the right column, under the `--header` part. Could you check and let us know if this is not working for you? Screenshots would be of great help!

**Comment by jdavey1996** [comment]
They are 'request' headers, not 'response' headers

**Comment by godfrzero** [comment]
Ah, crap. You're right, my bad. I'll see what I can do to get these added. @vkaegis

**Comment by steffenschebesta** [comment]
@godfrzero 
Third open issue concerning the missing auth header in the documentation (other two are https://github.com/postmanlabs/postman-app-support/issues/4244 and https://github.com/postmanlabs/postman-app-support/issues/4912)

**Comment by godfrzero** [comment]
@steffenschebesta This issue is unrelated. You're referring to auth headers in the request. This issue is about response headers.

**Comment by virenpawar** [comment]
I came across this issue today because I was facing same. But here's no update since Aug 2018.

**Comment by godfrzero** [comment]
Example response headers are visible in both the public & private documentation now:

<img width="894" alt="Screenshot 2020-05-30 at 3 21 42 PM" src="https://user-images.githubusercontent.com/2700229/83325341-46302100-a289-11ea-9c08-3670aef54282.png">
