### ISSUE TITLE
Postman back to freezing while duplicating large collections

### ISSUE THREAD

**Issue by chrisron95** [a85/POSTMan-Chrome-Extension#4719]
Please read through the [guidelines](https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues) before creating a new issue.

**Describe the bug**
When duplicating large collections (say, 125 requests-ish), postman completely halts for a significant amount of time while it syncs. This was an issue a while ago but was fixed months ago. However, it seems to be back. I've been noticing it over the past few weeks. Strangely, the UI doesn't look frozen, you can still hover over things and they'll highlight as normal and you can click through your currently open tabs, however trying to open a call that isn't already open will select the call from the navigator on the left, but no tab will open. You also can't save anything at all while this is going on.

From what I've observed, each time it has about the same thing happening: sync will stay on orange for a few minutes, switch to grey for about a minute, maybe a bit less, then will switch to orange for a significant amount of time (can be up to about 20 minutes) during which time I'm stuck at a complete standstill at work because I can't do anything until it finishes. Occasionally during the sync, it will pop up saying there was some kind of error syncing and to force the sync from the settings menu (which is greyed out) but completes sync later on successfully without forcing it, however this doesn't happen each time. Also, for whatever reason, whenever it finally finishes, if I have a runner window open, it will go completely black and I have to reopen it.

**To Reproduce**
Just duplicate a large collection of around 125 requests or more and watch the behavior

**Expected behavior**

**Screenshots**

**App information (please complete the following information):**
Postman for Mac
Version 6.1.3
OS X 17.4.0 / x64

**Additional context**
I've checked the developer console, but nothing is in there outside of the ordinary.

**Comment by chrisron95** [comment]
#3987 is the original issue

**Comment by DannyDainton** [comment]
Hey @chrisron95,

Are you still seeing this issue in the latest version of the native app?

**Comment by mccannt** [comment]
Closing out this issue. 
If you are still experiencing this problem, please feel free to reach out or reopen.
