### ISSUE TITLE
Test Javascript not updated when changed 

### ISSUE THREAD

**Issue by andjarnic** [a85/POSTMan-Chrome-Extension#472]
Not sure how to describe this completely.. basically in the Jetpacks add-on, I wrote a simple test script:

var jsonObject = xmltojson(responseBody);
var token = jsonObject.SomeName.Another["_attrName"];
postman.setEnvironmentVariable("key",token);

When I run my request, the first time this ran, the variable was set.. it worked. I partied for a bit because of how cool this is! Then I decided I didn't like the variable name "key", so I changed it to:

var jsonObject = xmltojson(responseBody);
var token = jsonObject.SomeName.Another["_attrName"];
postman.setEnvironmentVariable("authToken",token);

I ran it again, but oddly, the old variable name, "key" was still there, and it was updated to the new response value. The new variable name wasn't there. I then tried deleting the variable name from the environment, ran the request again, and now nothing shows up.

The main issue though is I can't lock down exactly what is going on. It seems like the javascript change I made was not "reread" and applied on subsequent requests. That would explain why on a subsequent run it updated the old variable name. But when I deleted the variable from the environment, and nothing showed up at all.. that had me questioning what is the problem.

I'll keep on trying to reproduce this more systematically to try to narrow it down, just thought I'd post this in case others are having a similar issue and/or it's a known issue.

**Comment by prdonahue** [comment]
I have this exact same issue. I set a variable and it gets set, then I run a test which returns a different value to be set and intermittently Postman will decide to update the variable, other times it'll be like "yeahh, sure .. I updated it" and you go and check and in fact the old value is still there.

By check I mean using in another test as well as clicking the environment drop-down at the top of the screen, clicking Manage Environments, and scrolling to your variable. Usually a restart a Postman works, but other times I feel like I have to delete the variable and it's value manually. Very frustrating when debugging services!

**Comment by abhijitkane** [comment]
@a85 This might be due to an error with the CodeMirror editor. Will look at it in more detail.

**Comment by BurnTurn** [comment]
Yeah it appears you guys are using CodeMirror v2.38(!) which is literally thousands of commits behind master. Why not upgrade to at least the latest v3 if not v4? The abstracted fixes are here: http://codemirror.net/doc/releases.html. I pulled the commit history from GitHub and it's massive (2,867 commits): https://github.com/codemirror/CodeMirror/compare/c8dbbd8...master.

![screen shot 2015-01-09 at 9 55 33 pm](https://cloud.githubusercontent.com/assets/9373218/5690614/9cff2520-984a-11e4-92bc-05b997fe2674.png)


At least in the meantime is there a way to explicitly remove the variable before setting a new one?

i.e., some sort of postman.deleteEnvironmentVariable("myVal");

before the 

postman.setEnvironmentVariable("myVal", responseBody);

Note that responseBody is not JSON, just a simple string, so no need to parse it.

**Comment by a85** [comment]
@BurnTurn We just got caught up with other stuff here. :) We are testing out Ace too. Any thoughts on that?

**Comment by prdonahue** [comment]
**EDIT**: Sorry, was signed in with a client's account. Reposted under my name.

Yeah it appears you guys are using CodeMirror v2.38(!) which is literally thousands of commits behind master. Why not upgrade to at least the latest v3 if not v4? The abstracted fixes are here: http://codemirror.net/doc/releases.html. I pulled the commit history from GitHub and it's massive (2,867 commits): https://github.com/codemirror/CodeMirror/compare/c8dbbd8...master.

![screen shot 2015-01-09 at 9 55 33 pm](https://cloud.githubusercontent.com/assets/9373218/5690614/9cff2520-984a-11e4-92bc-05b997fe2674.png)


At least in the meantime is there a way to explicitly remove the variable before setting a new one?

i.e., some sort of postman.deleteEnvironmentVariable("myVal");

before the 

postman.setEnvironmentVariable("myVal", responseBody);

Note that responseBody is not JSON, just a simple string, so no need to parse it.

**Comment by a85** [comment]
@prdonahue Pushing an update with the Ace editor today. It's much faster and should solve a lot of issues that CodeMirror has.
