### ISSUE TITLE
Sync reconnecting frequently

### ISSUE THREAD

**Issue by lovek323** [a85/POSTMan-Chrome-Extension#4720]
Please read through the [guidelines](https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues) before creating a new issue.

**Describe the bug**
I'm getting the "You seem to be offline" and then the "Trying to reconnect" messages frequently, then I'm given the "Resolve Sync Conflicts" window, which I resolve and then click "Resync" but the changes are not appearing on the server.

I'm getting this error in the console, which seems related:

```
error fetching Error: Could not fetch from sync. Socket not connected.
    at SyncRemoteFetcherService._dispatchCallback (vendor-shared.js:66433)
    at EventEmitter.emit (vendor-shared.js:52502)
    at _dispatch (vendor-shared.js:71365)
    at EventEmitter.<anonymous> (vendor-shared.js:71375)
    at emitTwo (events.js:125)
    at EventEmitter.emit (events.js:213)
8vendor-shared.js:52146 Could not find on CollectionStore. Missing or invalid parameter.
find @ vendor-shared.js:52146
```

**To Reproduce**
This happens when I open the app.

**Expected behavior**
The changes are synced to the server and the app stays online all the time.

**Screenshots**

Console:

![image](https://user-images.githubusercontent.com/265084/41636283-a8a61952-748c-11e8-83f6-26ffabcd1fc2.png)

**App information (please complete the following information):**
 - App Type Native App
 - Postman Version [e.g. 6.0.1]
 - OS: macOS Mojave 10.14 Beta (18A314h)

**Additional context**
N/A

**Comment by lovek323** [comment]
Update: I managed to get sync working again by signing out (and losing my local changes) and signing back in.

**Comment by gabriel-bronfman** [comment]
This issue has regressed

**Comment by preethammavin** [comment]
@gabriel-bronfman can you share the error logs, so that we can inspect the issue.

**Comment by sugoireed** [comment]
I signed out and then signed in again and it was able to sync.

Try and see if that helps.

**Comment by numaanashraf** [comment]
We have made some improvements to our sync service that should help with the intermittent connection issues. Please re-open this issue with the error logs if you are still facing this.
