### ISSUE TITLE
APIs not getting saved in history.

### ISSUE THREAD

**Issue by ltnilaysahu** [a85/POSTMan-Chrome-Extension#4722]
Cant find the apis in the history before a certain time.

**Comment by sivcan** [comment]
@ltnilaysahu Yes, there's a limit after which the history is removed.
This is an intended behavior.

**Comment by ltnilaysahu** [comment]
what is the limit?? And is there any reason behind this intended behavior?

**Comment by ltnilaysahu** [comment]
????
