### ISSUE TITLE
Collection name renaming is not synchronised with web

### ISSUE THREAD

**Issue by gabokr** [a85/POSTMan-Chrome-Extension#4723]
Please read through the [guidelines](https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues) before creating a new issue.

**Describe the bug**
I created a collection in postman for Mac. I changed the name later, but the old name is shown in the web view. The collection however gets synchronised. I can see new requests, even the description that I changed was reflected in the web, but it still shows the old name of the collection.

**To Reproduce**

**Expected behavior**

**Screenshots**

**App information (please complete the following information):**
 - App Type => Native App
 - Postman Version => 6.1.3
 - OS: => macOS X 17.5.0 / x64

**Additional context**

**Comment by numaanashraf** [comment]
@gabokr thanks for reporting. We are looking into this. In the meantime, could you verify whether you are repeatedly seeing this issue by renaming the collection once more?

**Comment by gabokr** [comment]
yes, I tried to rename several times but it stayed the same.
What happened just like 2 days ago was, that when my colleague renamed the
same collection, then the change got visible in the web and also in my
local Postman on Mac.

**Comment by numaanashraf** [comment]
@gabokr Could you check if your Postman app has trouble connecting to our services? The Sync indicator on top-right should be orange.

<img width="62" alt="screen shot 2018-07-02 at 4 16 32 pm" src="https://user-images.githubusercontent.com/3295568/42160013-5e5cbec4-7e13-11e8-8dc3-e0270e47dd5a.png">

**Comment by gabokr** [comment]
sure, that is OK and some other elements, like individual request were
synchronised correctly. Only the collection name wasn't.

**Comment by dennisslavid** [comment]
Just encountered a similar issue: renamed a collection yesterday, today the old name reappeared. (Together with another issue, but I will start a new issue for that. Could be related though...)

**Comment by kamalaknn** [comment]
Hey @dennisslavid @gabokr 

Can you update to the latest version and verify if you are still seeing these issues?

If yes, can you extract the logs from `View -> Developer -> View logs in Finder` and forward them to `help@getpostman.com`. Please add `GitHub: 4723` as the subject.

Thanks

**Comment by gabokr** [comment]
Hi guys,

I just tried to rename one collection with Postman v6.7.4, worked as
expected.

Best,
Gabriel

**Comment by numaanashraf** [comment]
Thanks @gabokr. Do let us know if you face this issue again. Closing this ticket for now.
