### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by jaguevara1978** [a85/POSTMan-Chrome-Extension#4724]
Hello, congratulations!...POSTMAN is great!!!

We just realized that it would be nice to have COMMENTS for each environmental variable. We use a lot of variables and it would be nice to have that feature. Just adding a field with a "Description/Comment" about the variable would do the job.

Regards

**Comment by sivcan** [comment]
@jaguevara1978 Hi, this is a duplicate of https://github.com/postmanlabs/postman-app-support/issues/4030
Kindly follow that thread for any updates regarding the requested feature.
