### ISSUE TITLE
UI Issue : 1. Not able to see all the options provided to choose request type. 2. Not able to see save button to save request.

### ISSUE THREAD

**Issue by neerajdwiv** [a85/POSTMan-Chrome-Extension#4725]
## App Details:
Postman for Windows
Version 6.1.3
win32 10.0.14393 / x64

## Issue Report:
 1. These issues are always been there. 
A). Not able to choose different request options provided with drop down list. They are not visible to me and there is no scrollbar provided to scroll up/down to see all options as well no way provided to choose these options using up/down arrow keys.
B). Can not able to save any request to any folder or collection since Save button is in somewhere outside the scree and not able to see that to click. No Scroll bar provided for this case too as well as no way provided to reach to Save button using tab.

 2. Expected behavior: 
A). All the option should be visible to the user to select from for request options. Scroll bar should be provided if there is less screen height available. There must be a way provided to choose other options using up/down arrow keys + Enter key.
B). Dialog height should be adjusted in a way that user can reach to the Save button. Otherwise provide scrollbar in case there is not enough screen height available. There must be a way of accessing Save button by using tab and enter key.
 
 3. 
 4. Screenshots (if applicable)
![image](https://user-images.githubusercontent.com/13641031/41758634-a9b2f668-7607-11e8-93eb-4fb2f82d4986.png)
![1](https://user-images.githubusercontent.com/13641031/41758639-ae987680-7607-11e8-8fb4-0f6b4bfe4361.PNG)

Repro Steps: This issue can be reproduced in a monitor with limited height. I am using a monitor of limited height and I am working in an Amazon Work Space. This might help to reproduce this issue.

**Comment by sivcan** [comment]
@neerajdwiv Thanks for reporting this.

For issue: 
A). We've released a canary build with the fix. You can take a look at this thread https://github.com/postmanlabs/postman-app-support/issues/4712

B). We've fixed this internally and will update this thread when the fix is out.

**Comment by prashantagarwal** [comment]
@neerajdwiv This is fixed in our latest Postman app.
