### ISSUE TITLE
AssertionError - Displaying the response body after using .response.text()).to.include cause issues

### ISSUE THREAD

**Issue by Kriz1881** [a85/POSTMan-Chrome-Extension#4728]
## App Details:
Postman for Windows
Version 6.1.3
win32 6.1.7601 / x64

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there: Recently
 2. Expected behavior: Postman is not printing all of the response when using pm.expect(pm.response.text()).to.include assertions. In the native app one failure can take all the available space in the response test results. Also when the collection is executed in Jenkins, there can be logs like "expected '{ 1000 lines of some response }' to include 'success'
 3. Console logs): N/A
 4. Screenshots (if applicable)
![image](https://user-images.githubusercontent.com/18331073/41776519-b8ea586e-7630-11e8-8d2b-ff51f8227a4a.png)

**Comment by sivcan** [comment]
@Kriz1881 We'll look into this and get back to you.

**Comment by DannyDainton** [comment]
Closing due to age and inactivity - If you're facing an issue in the latest version of the platform, we can look at reopening this again.
