### ISSUE TITLE
Post method got struck in status 403 forbidden 

### ISSUE THREAD

**Issue by Gnatarajamani** [a85/POSTMan-Chrome-Extension#4731]
Please read through the [guidelines](https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues) before creating a new issue.

**Describe the bug**

Post method got struck in status 403 forbidden 
![image](https://user-images.githubusercontent.com/40566715/41847956-80e9585a-7899-11e8-9aa2-6421b9a33501.png)

**Comment by sivcan** [comment]
@Gnatarajamani 
We need the following information from you:
Provide us with the info regarding what postman app you're using?
Also, the steps to reproduce this issue on our end.

**Comment by numaanashraf** [comment]
@Gnatarajamani This seems to be related to your specific API and server implementation. Postman seems to have received a 403 response from the server. You can access the raw request and response for this call via the Postman Console (Menu > View > Show Postman Console).

**Comment by hishamshoukathali** [comment]
Getting 403 error while trying to access a endpoint hosted in google cloud but the same can be access via browser

**Comment by ashokbhusal** [comment]
Request Headers
Content-Type: application/json
Authorization: Basic YWRtaW4yMTpsb3lhbHR5MjE=
User-Agent: PostmanRuntime/7.26.10
Accept: */*
Postman-Token: 26c56d65-c68a-4dee-b0c9-49beb5c64b93
Host: localhost:8080
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
Content-Length: 176
Cookie: JSESSIONID=9EB630BF00169EEF0896D1C589A1EFE6
Request Body
Response Headers
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache
Expires: 0
X-Frame-Options: DENY
Content-Type: application/json
Transfer-Encoding: chunked
Date: Mon, 05 Apr 2021 20:58:32 GMT
Response Body

**Comment by oprog** [comment]
@numaanashraf @sivcan 

Version 10.23.1
UI Version: 10.23.1-ui-240213-0705
Desktop Platform Version: 10.23.0 (10.23.0)
OS: MacOS 14.2.1 (23C71) Apple M1 Pro

This is what I'm experiencing about 403:

I open Postman, make a get request to my localhost:5000 API server. The server is not started yet, for some reason my laptop returns a 403. Fine. Then I start the server. If I invoke the API via browser or curl in the shell everything is working fine. Postman keeps giving me the 403 when I relaunch the previous failed request. 
To fix the issue I have to restart postman. Not a big deal but that's a bit annoying.
The _Help > Clear cache and reload_ does not fix the issue. 



Thanks
