### ISSUE TITLE
Add Java and C# to supported languages in documentation feature

### ISSUE THREAD

**Issue by molpe** [a85/POSTMan-Chrome-Extension#4733]
Having some extra languages in documentation feature would make our APIs easier to use and integrate. So enabling extra-languages would be great, specially since some of them are already present for generating code snippets in desktop app, like Java or C#.

Thanks and keep the good work.

**Comment by sivcan** [comment]
@molpe Thanks for the suggestion.
I'll mark this as a feature request.

**Comment by gdfSheldon** [comment]
Curious if there was any progress on c# documention.

**Comment by mexner** [comment]
I'm also interested in this feature.

**Comment by HarisVugdalic** [comment]
Lots of interest for C# and JAVA for our documentation. @sivcan It would also be nice if I could choose which languages I'd like to display.

**Comment by austin-plixer** [comment]
> It would also be nice if I could choose which languages I'd like to display.

That deserves its own feature request.  +1

**Comment by Aeroverra** [comment]
Agreed, Im looking for Java and C# and honestly those are the only languages I care to display.

**Comment by Raja-Simha** [comment]
Glad to inform you guys that private documentation can now generate code snippets for many more languages, including C# and Java, with options to configure generated code. We are going to release similar functionality for public documentation as well within a week. Happy to discuss any feedback from you guys.

**Comment by mail2vrajesh** [comment]
+1 for java. if you are providing code snippets for popular languages, I feel java should come first. when will this feature be available.?

**Comment by Cazaimi** [comment]
@molpe, We've added support for `C#` and `Java` in the private documentation along with 21 other language frameworks. You can head over to http://web.postman.co/ to check them out!

We're currently working on adding support for these frameworks to Public Documentation.

**Comment by Aeroverra** [comment]
@czardoz I assume the week eta @Raja-Simha gave was just a bit pre-mature? When this is added could you guys also allow a toggle of the ones we would like to display?

**Comment by Cazaimi** [comment]
@Aeroverra , if I'm not mistaken, you want that the final public documentation displays only the set of languages that you want to display? If so, I'd request you to add a feature request for the same and tag @Raja-Simha . Thanks.
