### ISSUE TITLE
Mac desktop app does not associate me with a team even though web UI does

### ISSUE THREAD

**Issue by dbodow** [a85/POSTMan-Chrome-Extension#4736]
**Describe the bug**
In the Mac desktop app, I get a "You don't have a team!" alert when trying to inspect my team / look at a team workspace. However, I clearly am associated with a team when using the web UI.

My colleague also reproduced this bug by restarting Postman on his machine and we're both locked out of team workspaces on our desktop apps.

**To Reproduce**
(After restarting the desktop app)
1. As a team member, open "My Workspace"
2. Try to open any "Team Workspace" or click on the "Team" button in the top right corner
3. See "You don't have a team!" message
4. Login via the web portal
5. Everything works just fine

**Expected behavior**
I should be able to access my team workspaces from the Postman desktop app

**Screenshots**
Desktop App:
<img width="994" alt="screen shot 2018-06-26 at 5 43 57 pm" src="https://user-images.githubusercontent.com/4065355/41946790-046caa40-7969-11e8-8519-56ae1c7f0d02.png">

Web App:
![screen shot 2018-06-26 at 5 55 40 pm](https://user-images.githubusercontent.com/4065355/41947313-aaaeb608-796b-11e8-9bac-7978acc30f45.png)

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version: 6.1.3
 - OS: macOS High Sierra 10.13.4

**Additional context**
- Tried reinstalling the desktop app already
- I only have one Postman account; still double checked that it's the same login information for each environment just in case

**Comment by SamvelRaja** [comment]
@dbodow Could you send few details from your app to help[at]getpostman[dot]com from your registered email address.
Run the following script in View -> Developer -> Show DevTools(Current View) 

```
(() => { pm.models.user.find().then((d)=> { console.log(JSON.stringify(d)) })})()
```

**Comment by dbodow** [comment]
Looks like the issue was that our subscription just ended; my colleague renewed and the issue seems to be resolved.

I'm not quite sure what the UI looks like from an account admin perspective, but you really should consider making the issue clearer to users with delinquent accounts. In the screenshot above, the 'You do not have a team!' message is really inaccurate. I would expect to see a message along the lines of "Contact your account administrator to renew your subscription!" or something that indicates the issue is with billing.

Additionally, my colleague who renewed the subscription can't recall seeing a warning email (maybe it went to the wrong gmail folder; who knows...). But an in-app warning should be given as well -- we use Postman daily, and he would have been able to catch the issue earlier if a warning had been rendered in-app.

**Comment by vkaegis** [comment]
@dbodow Thanks for catching this! Looks like we missed adding a few states for delinquent teams. We'll be rolling out a fix for this in the coming versions. Stay tuned!

**Comment by numaanashraf** [comment]
We have started showing a banner warning for delinquent teams
