### ISSUE TITLE
Azure database to Postman connection

### ISSUE THREAD

**Issue by radauto** [a85/POSTMan-Chrome-Extension#4740]
Hello Team , Is there a way we can connect to Azure cosmos DB from postman and get data ?
Any documentation / links will be helpful.

**Comment by numaanashraf** [comment]
Thanks for writing in. There seems to be resources available where folks have tried this out. I'ld recommend this specific one - https://azure.microsoft.com/en-in/resources/videos/using-rest-with-documentdb/. However, the best place for help on specific APIs are on the API providers forums or on the Postman Community - https://community.getpostman.com/

Related links:
https://stackoverflow.com/questions/44459489/azure-cosmos-db-callin-api-in-postman-syntax
https://docs.microsoft.com/en-us/rest/api/cosmos-db/restful-interactions-with-cosmosdb-resources
https://docs.microsoft.com/en-us/rest/api/cosmos-db/querying-cosmosdb-resources-using-the-rest-api
