### ISSUE TITLE
Failed to import a collection in postman

### ISSUE THREAD

**Issue by dhanotra** [a85/POSTMan-Chrome-Extension#4741]
Getting an error on importing a collection "Failed to import collection <***>"
Even though that collection is not exist in my postman workspace, I still get the below message 
then I click either Replace/ Import as Copy and then error shows on top.
A collection <***> already exists.
What would you like to do?

**To Reproduce**
1. Go to 'Import'
2. provide a link
3. click on Import
4. See this and click on Replace
A collection *** already exists.
What would you like to do?

**Comment by numaanashraf** [comment]
Thanks for reporting this @dhanotra. We are looking into this.

**Comment by thecuriousdev** [comment]
@dhanotra we fixed this issue. And its available in our latest version of canary.
