### ISSUE TITLE
Client Secret is not part of oAuth2 Implicit Grant Type

### ISSUE THREAD

**Issue by mlambley** [a85/POSTMan-Chrome-Extension#4742]
**Describe the bug**
When entering details for an implicit grant type in OAuth 2.0, the system asks for client secret. However, client secret is not part of the implicit grant type.

**To Reproduce**
1. With a request selected, click on Authorization
2. Select Type: OAuth 2.0
3. Click Get New Access Token
4. Select Grant Type: Implicit
5. See that the system asks for Client Secret

**Expected behavior**
This input field should not appear, since client secret is not used in the implicit grant type. It is confusing the third-party developers who use our API, as they are asking us what they should be putting in this field.

**Screenshots**
![image](https://user-images.githubusercontent.com/17264636/42013634-8eebfd3c-7ae1-11e8-873c-6979317e6114.png)

**App information (please complete the following information):**
 - Native App
 - Version 6.1.4 win32 10.0.17134 / x64
 - Windows 10

**Comment by sivcan** [comment]
@mlambley Thanks for reporting this. We'll update this thread once a fix is out.

**Comment by harryi3t** [comment]
@mlambley We have released a fix for this on our canary apps. 
Can you please verify it?
You can get the canary app from https://www.getpostman.com/canary

**Comment by mlambley** [comment]
I'm not sure to be honest. My `Postman OAuth 2.0` window is doing the thing where it opens but just sits there blank. It's happened before. I'll keep trying.

**Comment by mlambley** [comment]
Is there any way to debug that window? To see what it's doing? The Postman Console doesn't show any messages.

**Comment by harryi3t** [comment]
@mlambley You can open the app from command-line. It should show the logs about what's happening.
All the redirections will be logged.
I will also recommend testing the flow in a browser, (use the first URL that you see in the logs).
There is a known issue around handling native prompts. If while testing in a browser you see a native prompt, then it won't work in Postman.

**Comment by harryi3t** [comment]
@mlambley This is fixed in the latest version of Postman 6.2.3
