### ISSUE TITLE
Prettify JSON in request body

### ISSUE THREAD

**Issue by pkgajulapalli** [a85/POSTMan-Chrome-Extension#4743]
It would be good if prettifying JSON (or xml, html) data in request body.

**Comment by numaanashraf** [comment]
@pkgajulapalli Thanks for reaching out. There is an undocumented keyboard shortcut (Cmd+B for Mac or Ctrl+B for Windows/Linux) to do this while you are focused on the Request Body Editor. We are working on adding a prominent UI option to do this.

**Comment by pkgajulapalli** [comment]
@numaanashraf Thanks for the quick reply.
