### ISSUE TITLE
UI: Only one scrollbar

### ISSUE THREAD

**Issue by Montago** [a85/POSTMan-Chrome-Extension#4744]
When the response from an API is very long, it's very annoying to have 2 scrollbars.

please just let the response window expand the whole UI in such a way that the main scrollbar also works for the response window !

Scroll-windows inside scroll-windows is a UI no-go !

**Comment by numaanashraf** [comment]
Thanks for the suggestion @Montago. I've forwarded the feedback to the right folks.

**Comment by vkaegis** [comment]
@Montago Thanks for the feedback! We're working on some improvements to the tab structure which will allow users to treat contents in the tab as panes. So your request area and response area will then become it's own individual panes with it's own scroll bar.

While I realize that this is quite the opposite of what you're suggesting, we're hoping that this along with the ability to collapse individual panes and fix them in your UI will you to customize your UI according to your preferences. So for example, you could collapse the request pane and work only with the response pane which will have a single scroll bar!

Stay tuned for updates. We'd also love to hear your thoughts on this solution in detail so let me know if you'd like to schedule a call with us.

**Comment by a85** [comment]
Using the 2-pane layout should help keep only one scrollbar in the interface. Closing this for now.

**Comment by brpeterman** [comment]
That's not a solution. The two-pane layout (1) is not the default view, so the default UX is still broken and (2) makes very poor use of screen space.

Below is a pair of screenshots showing the same request in the default view and and the two-pane view. The two-pane view is borderline unusable in this situation.

* Default view: https://i.imgur.com/b6AEJfe.png
* Two-pane view: https://i.imgur.com/7mg20oP.png

I can, of course, make the window wider and it gets better the wider I make it, but I really don't need an entire column of my screen for parameters.

**Comment by Montago** [comment]
How hard can it be to just let the result expand into infinity ???

it's only a matter of settings !!
