### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by bah-sa** [a85/POSTMan-Chrome-Extension#4745]
Postman v.6.1.3, 6.1.4

After a long manual test run, memory usage is significantly increased and the response time of the user interface is noticeably increased.

**Comment by SamvelRaja** [comment]
@bah-sa could you help us by providing more information?
_Long manual test,_  
   Do you have more tabs opened during the process?

_memory usage is significantly increased and the response time of the user interface is noticeably increased._
   Could you provide us the information on the memory usage it holds when you feel the lag in response time? A screenshot of memory usage monitor would be useful.

**Comment by bah-sa** [comment]
Hello!Yes, about a hundred requests sent and as many tabs was opened when UI starts to lag. Closing all tabs decrease memory usage but not completely, and after a short number of requests UI starts to lag again.Screenshots in attachment. Sincerely,S.A.Bakhmutov  28.06.2018, 12:10, "SamvelRaja" <notifications@github.com>:@bah-sa could you help us by providing more information?Long manual test,Do you have more tabs opened during the process?memory usage is significantly increased and the response time of the user interface is noticeably increased.Could you provide us the information on the memory usage it holds when you feel the lag in response time? A screenshot of memory usage monitor would be useful.—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by SamvelRaja** [comment]
@bah-sa  Thanks for your feedback, we understand your concern, we shall look at this issue and will keep posted in this thread on the progress.

**Comment by prashantagarwal** [comment]
@bah-sa Can you update to the latest Postman app and see if it is still happening. Also I think since you have so many requests open app memory consumption might be high.
