### ISSUE TITLE
Dropdown for request type breaks at lower application heights.

### ISSUE THREAD

**Issue by JordanAlimi** [a85/POSTMan-Chrome-Extension#4748]
When postman has a height that is too small, the drop down for the request type will open upwards instead of downwards. This blocks a user from selecting their desired request type on smaller resolution screens.

**To Reproduce**
1. Open native app.
2. Reduce app's height.
3. Click on drop down for request type.
4. See that the drop down goes upwards and doesn't show all the content.

**Expected behavior**
Postman should open the drop down for the request type downwards at lower heights or have a solution for showing the drop down's content when opened upwards.

**Screenshots**

Dropdown at proper height:
![proper](https://user-images.githubusercontent.com/8739093/42060003-5a6246ea-7af3-11e8-9965-4423743d5024.png)

Dropdown at inproper height:
![bug](https://user-images.githubusercontent.com/8739093/42060021-6bcc8ef4-7af3-11e8-8ff0-ef3abd1876bb.png)

**App information:**
 - App Type: Native App
 - Postman Version: 6.1.3
 - OS: Ubuntu 16.04

**Comment by prashantagarwal** [comment]
@JordanAlimi We have fixed this and released it on our canary apps for now. It will soon be available for the Postman app itself in next release. You can download canary apps from https://www.getpostman.com/canary

**Comment by JordanAlimi** [comment]
Thanks for the quick response and sorry for the duplicate. Ill close the issue.
