### ISSUE TITLE
Horizontal scroll bar only visible when vertical scroll is at bottom

### ISSUE THREAD

**Issue by andjarnic** [a85/POSTMan-Chrome-Extension#475]
Often times responses return with lots of XML that extends the width of the window. To scroll horizontal I have to vertically scroll to the bottom.. scroll horizontal, then scroll back up to see the top area of the response. We should be able to have a horizontal scroll bar visible at all times and not need to scroll to the bottom of the response to scroll left or right.

**Comment by sidiinia** [comment]
Hey, I am on postman version 7.5.0, but it seems I am still having this issue, is there any setting that I missed? Thanks!
