### ISSUE TITLE
Collections are lost after upgrade to 6.1.4

### ISSUE THREAD

**Issue by puffluna** [a85/POSTMan-Chrome-Extension#4750]
I installed the new version Native App Version (6.1.4) of Postman and all of my collections were there and running.  Then I rebooted my machine and all of my collections are gone.

I'd like some help finding them.

Thank you.

**Comment by sujayvenaik** [comment]
Hey @puffluna,
Did you migrate from a chrome version of the app to the native app.

Also, was your data synced ?
Can you help us with more details so we can look into it further.

**Comment by puffluna** [comment]
Hi.  I had the chrome app and version 4.10.3 of native app installed.   My company asked me to upgrade to 6.4.1.  I did that and lost my collections.

I don't think my data was synced since I'm not familiar with that.  I did sign in prior to losing the collections.

Thanks for any help!!



Sent from my Verizon, Samsung Galaxy smartphone


-------- Original message --------

**Comment by sujayvenaik** [comment]
Hey @puffluna 

What best you can do is, do a bulk export of data from the chrome app. 
And you can re-import in the postman native app.
This will help you get the data and the collections back.

Step 1: Launch your chrome app
Step 2: Go to Settings
Step 3: Data Tab
Step 4: Export Data -> Download

Step 5: Launch the Postman Native App
Step 6: Press on Import on top Left
Step 7: Choose file and import.

You should ideally get all your data and collections back.

Do let me know if you face any other issues.

**Comment by puffluna** [comment]
I'm sorry.  I forgot to mention that I deleted the chrome app.  It also had old versions of the collections anyway.   Is there anything else I can try?



Sent from my Verizon, Samsung Galaxy smartphone


-------- Original message --------

**Comment by sujayvenaik** [comment]
@puffluna 

Try installing the chrome app again if you can get the data.

If not, and you use the Chrome app, head to `chrome://indexeddb-internals/` and search for `fhbjgbiflinjbdggehcddcbncdddomop`. You should see two folders listed - you can create a zip file with the contents of those folders, and email them to help@getpostman.com. We should be able to recover your data.

Do let me know if you need any help.

**Comment by puffluna** [comment]
The chrome app is no longer available.  I don't want the collections that were saved in that app.  Is there a way to recover what I had saved in the native app?



Sent from my Verizon, Samsung Galaxy smartphone


-------- Original message --------

**Comment by puffluna** [comment]
I installed the chrome app and no collections



Sent from my Verizon, Samsung Galaxy smartphone


-------- Original message --------

**Comment by sujayvenaik** [comment]
@puffluna 
If you would have enabled syncing you would surely get your collections back once you login back with the same account you used earlier.

Can you login back with the same account (logout and login again if already login), and check in the native app.
Also please let us know the color of the syncing icon present on the top bar. (Image attached)
<img width="79" alt="screen shot 2018-06-30 at 1 48 23 am" src="https://user-images.githubusercontent.com/11532114/42113096-c366c99e-7c07-11e8-98c9-293fd61c2919.png">

**Comment by sujayvenaik** [comment]
Hey @puffluna 
Closing this for now, if you have any other issue you can get back again.
