### ISSUE TITLE
Ability to save form-data when i want to attach file fails

### ISSUE THREAD

**Issue by Madhini-QA-compeat** [a85/POSTMan-Chrome-Extension#4754]
**Describe the bug**
Ability to save form-data when i want to attach file fails Post attaching file to form-data the saved file is not visible

**To Reproduce**
1. I created a POST
2. in Body i choose form-data
3. Attached a file
4. Saved the POST
5. When i reopened the file was missing

**Expected behavior**
the saved file should be there in form-data

**App information (please complete the following information):**
 - App Type [Native]
 - Postman Version [Postman v6.1.4]
 - OS: [Windows 10 Pro]

**Comment by SamvelRaja** [comment]
Tracking this extensively in #4320
