### ISSUE TITLE
Folder level code is hidden until text box is clicked

### ISSUE THREAD

**Issue by Aporrasniche** [a85/POSTMan-Chrome-Extension#4755]
**Describe the bug**
Folder level code is not displayed until the text box is clicked

**To Reproduce**
1. Inside a `Test Collection` create a folder to contain any tests within the collection
2. Edit the new (or already existing) folder and add any code to run at the folder level such as:
```
pm.test('Status code is 200', function () {
    pm.response.to.have.status(200);
});
```
3. Click `Update`
4. Select the above folder and edit again
5. Select Tests 

**Expected behavior**
The code written is displayed

**Observed behavior**
The code written is not displayed until the text box containing it is clicked 

**Screenshots**
![postman bug](https://user-images.githubusercontent.com/36635306/42113439-451e6798-7bb9-11e8-8f5a-7684c465b2b2.gif)

**App information (please complete the following information):**
 - App Type: `Postman App`
 - Postman Version `6.1.3`
 - OS: `Windows 10`

**Additional context**
This code doesn't need to be recently written for the observed behavior to occur, it will occur every time a user edits and attempts to inspect code within the folder

**Comment by bhargavkaranam** [comment]
This has been fixed in the latest version of Postman 6.2.3.
