### ISSUE TITLE
OAuth 2.0 access token dropdown cut off

### ISSUE THREAD

**Issue by i906** [a85/POSTMan-Chrome-Extension#4757]
**Describe the bug**
Unable to scroll the available token list when there are a lot of saved tokens.

**To Reproduce**
1. Go to Auth Tab and select OAuth 2.0
2. Create a lot of OAuth 2.0 access tokens
3. Click on available tokens dropdown
4. Attempt to scroll to select other access tokens
5. Notice scroll not responding

**Expected behavior**
I should be able to scroll to the desired token in the dropdown list.

**Screenshots**
![screen shot 2018-07-02 at 12 09 34 pm](https://user-images.githubusercontent.com/866735/42144977-d6768f0c-7df0-11e8-9763-4eba81eea123.png)

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version: 6.1.4
 - OS: macOS High Sierra 10.13.5

**Comment by prashantagarwal** [comment]
Related to #4748 
We have fixed this and released it on our canary apps for now. It will soon be available for the Postman app itself in next release. You can download canary apps from https://www.getpostman.com/canary
