### ISSUE TITLE
Issues related to script/code editing and syntax highlighting.

### ISSUE THREAD

**Issue by prashantagarwal** [a85/POSTMan-Chrome-Extension#4758]
**Describe the bug**
All issues related to code editing, syntax highlighting etc will be tracked in this issue. We want to get a holistic view about all these kind of similar issue and fix them.

**Comment by prashantagarwal** [comment]
Affects #4965

**Comment by prashantagarwal** [comment]
Affects #4967

**Comment by prashantagarwal** [comment]
Affects #4313

**Comment by kamalaknn** [comment]
I am closing this issue. We will be tracking the issues and fixes at an individual report level.
