### ISSUE TITLE
Issues related to Cut / Copy / Paste inside Postman app

### ISSUE THREAD

**Issue by prashantagarwal** [a85/POSTMan-Chrome-Extension#4759]

**Comment by vahids** [comment]
Seems like It's fixed on Version 6.1.4 (6.1.4) 
macOS 10.12.6 (16G1212)

**Comment by ravisanwal** [comment]
This is absolutely not fixed

**Comment by vahids** [comment]
Maybe It's randomize bug. I left postman for this bug. I switched to mitmproxy that is far better for my usage.
