### ISSUE TITLE
Change Proxy settings while testing.

### ISSUE THREAD

**Issue by IlyaDhtvzGhbltn** [a85/POSTMan-Chrome-Extension#4760]
Not possible to reset proxy settings while testing. Example I need to change or clear proxy host/port without stopping the test - for now this is impossible. This feature would be very useful.

**Comment by numaanashraf** [comment]
Thanks for the feedback and feature request @IlyaDhtvzGhbltn.

**Comment by IlyaDhtvzGhbltn** [comment]
@numaanashraf also, will be more useful change `pm.sendRequest` method and add `Proxy` as one of parameter.

**Comment by codenirvana** [comment]
Closing as we are tracking this feature request here: #5394
