### ISSUE TITLE
Lack of "permission denied" warning when uploading a file for binary request

### ISSUE THREAD

**Issue by babacode** [a85/POSTMan-Chrome-Extension#4761]
**Describe the bug**
The Postman does not warn user when the binary file selected by a user cannot be accessed by Postman.

**To Reproduce**
1. Create POST request
2. Go to 'Body' and select 'Binary' option
2. Click on 'Choose Files' and select file from location not accessible to Postman (in my case OneDrive folder)
3. Click on 'Send'
4. See response from the endpoint stating that no binary file is received

**Expected behavior**
Postman should warn the user that the binary file cannot be accessed.

**Screenshots**
![inked4c980274_li](https://user-images.githubusercontent.com/12748235/42161123-936f760a-7df1-11e8-8d6c-f38d04534dc2.jpg)

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version: 6.1.4
 - OS: Windows 10 10.0.16299 Build 16299

**Comment by numaanashraf** [comment]
@babacode Thanks for reporting this.

**Comment by harryi3t** [comment]
@babacode 
This is fixed in the latest version of Postman 6.3.0 🎉 
![postman-unreadable-file](https://user-images.githubusercontent.com/5207331/45155513-e3ffd480-b1f8-11e8-9ef4-e94d78d343ae.png)
