### ISSUE TITLE
Feature Request: CMD+Shift+T to reopen last closed tab

### ISSUE THREAD

**Issue by govindrai** [a85/POSTMan-Chrome-Extension#4763]
I always end up wanting to get back to a tab I just closed. Just like in the Chrome browser where CMD+Shift+T reopens the last closed tab, it would be really helpful if Postman App behaved similarly. 

Obviously, this doesn't make or break anything, but it would be super useful for your users, imo.

**Comment by vkaegis** [comment]
@govindrai This makes a lot of sense. Adding it as a feature request to the short term roadmap. Thanks for the feedback!

**Comment by dupiesdupreez** [comment]
+1

**Comment by sujayvenaik** [comment]
This is out with Postman(v6.6.1)
