### ISSUE TITLE
Broken Json will be shown as valid in "pretty" view mode

### ISSUE THREAD

**Issue by emanuelthedude** [a85/POSTMan-Chrome-Extension#4765]
There is an endpoint that returns invalid Json like this
```json
[{"id": "1","logoUrl": "someUrl1","linkUrl": "someUrl2"}]{"Error": "No Partners Found" }
```
But in the "pretty" view it looks like the Json is valid like below. The invalid "error"-part is cuttet out
```json
[
    {
        "id": "1",
        "logoUrl": "https://www.general-anzeiger-bonn.de/incoming/ecsImgSplashScreen_Flaeche_frei_720x720px-656723121327277465.jpg-article3883234.html/BINARY/original/ecsImgSplashScreen_Flaeche_frei_720x720px-656723121327277465.jpg?ts=1529585547000",
        "linkUrl": "http://www.general-anzeiger-bonn.de/verlag/anzeigen/"
    }
]
```

**To Reproduce**
Steps to reproduce the behaviour:
1. Do a GET on https://www.general-anzeiger-bonn.de/newsapp/getpartner?type=section&section=sport
The endpoint is secured by a basic auth. Please contact me for the password as I don't want to paste it here.
2. Click on 'Send'
3. Wait for the response and compare the response in the view mode 'Pretty' (valid Json) and 'Raw' (invalid Json)

**Expected behavior**
The view mode 'Pretty' should show 'Syntax error' if the json is not valid.

**Screenshots**
![pretty](https://user-images.githubusercontent.com/8446311/42210228-e7bc0812-7eb0-11e8-8848-38c43f63adbc.png)
![raw](https://user-images.githubusercontent.com/8446311/42210230-e7e661ac-7eb0-11e8-86dd-d8d96bdc9213.png)

**App information:**
 - Native App for Mac
 - Postman Version 6.1.4
- Mac Book Pro 13" (Early 2015)
 - OS: macOS High Sierra 10.13.5

**Comment by prashantagarwal** [comment]
Related to #3635

**Comment by prashantagarwal** [comment]
Tracking in #4758

**Comment by kamalaknn** [comment]
Hey @emanuelthedude 

Quick update, this issue is fixed now. In the newer versions of Postman, we take care to ensure that no data is removed from the actual response in any of the response vies.
