### ISSUE TITLE
Issue with Postman chrome extension

### ISSUE THREAD

**Issue by daksh9711** [a85/POSTMan-Chrome-Extension#4766]
I am running the postman in chrome app. When I was using it  was showing the same error but as i have read that pm will not work for postman chrome extension but here i am using postman then still it is not working.

**Comment by sivcan** [comment]
@daksh9711 
The chrome app doesn't support `pm.test` / `postman.test` 

What you can use is this **_tests_** format which iss supported in the chrome app:
`tests["Response time is less than 200ms"] = responseTime < 200;`

However, the support for Chrome app has been deprecated and it's recommended that you switch to the native app - [Download Postman - Native](https://www.getpostman.com/apps)
If there's a reason behind you not switching to the native app then please let us know the issue you're facing.

Thanks!
