### ISSUE TITLE
Requests hit 403 Forbidden error for a collection which uses x-signature header and request body variables

### ISSUE THREAD

**Issue by markdrury** [a85/POSTMan-Chrome-Extension#4767]
I have a straightforward collection with one request which hits a reverse geocode endpoint and uses the following Postman features:

- A CSV data input file with five fields
- A pre-request script which uses SST1-HMAC-SHA256 to create an x-signature header
- A number of trivial tests which check status code, POST success, etc.
- A request header which includes the generated x-signature plus Content-Type of application/json
- A request body which uses the input data in the following way:
    {
    "zoneId": {{zoneId}},
    "zoneName": "{{zoneName}}",
    "incidentId": {{incidentId}},
    "sourceIncidentId": "{{zoneId}}-{{incidentId}}",
    "latitude": {{latitude}},
    "longitude": {{longitude}}
    }

When I run the collection, with or without specifying an environment, I see 403 Forbidden responses for every request, even though the request URL, header and body all look correct in the run results -- the x-signature in the header and the request body both look good, per the following screenshot:

![403_request_response](https://user-images.githubusercontent.com/378248/42250394-6d52aa56-7ee5-11e8-94d3-af9701000317.png)

I have tried adding the pre-release script and tests to both the collection and the request but it matters not -- the same errors are seen.  I run with 'No Auth' set in both the collection and the request, as well, and have tried 'inherit auth from parent" in the request, to no avail.

Importantly, if I hardcode valid values in the request body (in place of the variables seen above) the request then works -- I receive a 200 response and all other simple tests pass.  I'm not at all certain why request body variable interpolation may be causing this 403 error, if that is, indeed, what's happening.  I added all variables to the collection specification, tried to surface them in the pre-release script, along with a number of other silly tries and still see the 403.  My expectation is that I'm using variables correctly in my collection/request and the requests should work the same way they do when I hardcode values in the request body.

I'm using the Postman native app, v6.1.3, on a 15" MacBook Pro running MacOS v10.13.5.  A fairly close search of Postman issues on GitHub as well as on Google turned up little related to what I'm seeing, but I could have missed something obvious.

**Comment by markdrury** [comment]
I suppose the salient question here is whether the pre-release script creates the x-signature before variable interpolation happens via data in the data file?  That may explain why the request is rejected, of course.

**Comment by kamalaknn** [comment]
Hi @markdrury 

You are right, the request is not resolved with environments in the `prerequest` scripts. That is because you can update your variables in the `prerequest` scripts, and that update should reflect in your request.

This following snippet allows you to get a snapshot of a resolved request
```js
var postmanSDK = require('postman-collection'),
    resolvedRequest = pm.request.toObjectResolved(null, [pm.variables], {ignoreOwnVariables: true})
    resolvedSDKRequest = new postmanSDK.Request(resolvedRequest);
// resolvedSDKRequest has all variables resolved
```

This is a bit ugly, we'll see if we can expose a nicer way to get a resolved snapshot of the request in scripts.
