### ISSUE TITLE
Mock Server not returning image file correctly

### ISSUE THREAD

**Issue by robertoibarra** [a85/POSTMan-Chrome-Extension#4768]
## App Details:
```
Postman for Mac
Version 6.1.3
OS X 10.11.6/ x64
```

## Issue Report:
I execute my API endpoint from Postman directly that results in an image file being downloaded, this works OK, as expected. Then I create an "example" in Postman with this image file response and it seems to be created and synced ok.

However, when I see the example again in Postman or using my API through the Mock Server, it downloads the file with like a wrong binary encoding or something, the mock server doesn't return the exact same thing that my server sent. It looks like a bug.

Here's a video of what I did:
https://screencast.com/t/i0PGa2InwzIh

I am attaching the output of from the mockserver:
curl --request POST -F 'token_key=12345' -F 'customer_id=3' 'https://4a893e39-b750-4c06-b260-113f65203916.mock.pstmn.io/api/folder/download-documents?folder_id=1670&file_id=14347'

This is the returned file, the binary encoding is like incorrect, it should be a JPG.
[it_should_be_a_jpg.txt](https://github.com/postmanlabs/postman-app-support/files/2161467/it_should_be_a_jpg.txt)

**Comment by numaanashraf** [comment]
Thanks for reporting this @robertoibarra.

**Comment by sujayvenaik** [comment]
Hey @robertoibarra 

Currently, the mock server is not capable of handling media type responses and hence can only handle textual responses.

We have tried to communicate this better to the users by adding a warning when trying to add examples with media type responses which is out on our canary channel (https://www.getpostman.com/canary) and will soon be available on the production release.

**Comment by sujayvenaik** [comment]
Hey @robertoibarra 
This has been addressed and is available on the stable channel (v6.4.x).
Now one cannot save example with media type responses.
You can update the app to the latest version.

Thanks again for writing in and reporting this issue.
