### ISSUE TITLE
Import CURL via "Paste Raw Text" doesn't work for some CURLs

### ISSUE THREAD

**Issue by Yevhenii-me** [a85/POSTMan-Chrome-Extension#4770]
**Describe the bug**
Import CURL via "Paste Raw Text" doesn't work for some CURLs.

**To Reproduce**
1. Click on "Import"
2. Click on "Paste Raw Text"
3. Put any CURL from example to input form.
4. Click on "Import"

CURL examples: https://gist.github.com/Yevhenii-me/b8335d083198f8cae877b75278e2c42a

**Actual results:**
I see error: "Error while importing Curl: TypeError: Invalid format for cURL."

**Expected behavior**
I can parse this CURLs in other services like this: https://curl.trillworks.com/
Maybe, it's not an "exemplary" example, but in fact we have this CURLs.
So, in one side we can use this import for small projects (in which we can do it manually)
In other side we can't use import CURL for big projects (where we CAN'T import logs manually, because it has a lot of parameters)

**Screenshots**
https://goo.gl/g8EV95

**App information:**
Postman for Windows
Version 6.1.4
win32 10.0.17134 / x64

**Comment by numaanashraf** [comment]
@Yevhenii-me Thanks for reporting this.

**Comment by gs-nkumar** [comment]
there is issue with angular 4 post call in my case. `\n` is appending.when copy as curl
![postman](https://user-images.githubusercontent.com/17634822/42269204-2835a048-7f9b-11e8-8f25-e53f3f1087fd.jpg)

**Comment by enginaar** [comment]
`curl -I https://www.google.com/`

also fails with the same error.

Edit: Turns out -I is not a supported option, here is all supported options in case someone else needs it. https://learning.getpostman.com/docs/postman/collections/data_formats/#importing-curl

**Comment by abhijitkane** [comment]
@enginaar @Yevhenii-me All reported issues around extra options are fixed in the latest Postman version (7.2.1).

@gs-nkumar If you're having trouble importing curl snippets in Postman v7.2.1, could you include the original curl snippet here?

Closing this for now.

**Comment by Yevhenii-me** [comment]
OMG! Thanks, guys! I'll check it right now.

**Comment by mlwanw2020** [comment]
c:\curl\bin\curl.exe -H "Content-Type: application/json; charset=UTF-8" -H "Authorization: UsersJwt %Token%" "Cookie: ServerID=1028" -k -L -X GET "https://baylor-b4.bioraft.com/jsonapi/node/chemical_container?include=field_chemical_type,og_audience,field_chemical_space,field_chemical_manufacturer" -d "&filter[lab1][condition][path]=og_audience.title&filter[lab1][condition][value]=Wood Lab&filter[lab1][condition][memberOf]=lab-group&filter[lab2][condition][path]=og_audience.title&filter[lab2][condition][value]=Romo Lab&filter[lab2][condition][memberOf]=lab-group&filter[lab3][condition][path]=og_audience.title&filter[lab3][condition][value]=Romero Lab&filter[lab3][condition][memberOf]=lab-group&filter[lab-group][group][conjunction]=OR&filter[created-before][condition][path]=created&filter[created-before][condition][value]=%Now%&filter[created-before][condition][operator]=<=&filter[created-after][condition][path]=created&filter[created-after][condition][value]=%Midnight%&filter[created-after][condition][operator]=>=" >chemtracker_export-%y%"-"%m%"-"%d%.json

**Comment by mlwanw2020** [comment]
I am having problems with this curl command for a drupal API.  This is the get request with the curl switches  what am i doing wrong guys

c:\curl\bin\curl.exe -H "Content-Type: application/json; charset=UTF-8" -H "Authorization: UsersJwt %Token%" "Cookie: ServerID=1028" -k -L -X GET "https://baylor-b4.bioraft.com/jsonapi/node/chemical_container?include=field_chemical_type,og_audience,field_chemical_space,field_chemical_manufacturer" -d "&filter[lab1][condition][path]=og_audience.title&filter[lab1][condition][value]=Wood Lab&filter[lab1][condition][memberOf]=lab-group&filter[lab2][condition][path]=og_audience.title&filter[lab2][condition][value]=Romo Lab&filter[lab2][condition][memberOf]=lab-group&filter[lab3][condition][path]=og_audience.title&filter[lab3][condition][value]=Romero Lab&filter[lab3][condition][memberOf]=lab-group&filter[lab-group][group][conjunction]=OR&filter[created-before][condition][path]=created&filter[created-before][condition][value]=%Now%&filter[created-before][condition][operator]=<=&filter[created-after][condition][path]=created&filter[created-after][condition][value]=%Midnight%&filter[created-after][condition][operator]=>=" >chemtracker_export-%y%"-"%m%"-"%d%.json

**Comment by jarrettyeo** [comment]
I got this error while testing a curl request copied from Chrome. I checked the curl options against the [acceptable options](https://github.com/postmanlabs/curl-to-postman) and found out that my curl request contained an illegal `--connected` tail. After removing it and making sure no other unsupported options were included in my request, I could successfully import my curl request into Postman.
