### ISSUE TITLE
Postman app doesn't work with system proxy env variables without valid protocol

### ISSUE THREAD

**Issue by numaanashraf** [a85/POSTMan-Chrome-Extension#4776]
Originally reported at https://github.com/postmanlabs/postman-app-support/issues/3127#issuecomment-402477560 by @Magdiel.

**Comment by harryi3t** [comment]
Hi @Magdiel, 
I noticed in the screenshot (that you posted on the other thread) that you have an environment variable `http_proxy='s460proxy:8080'`. Could you try chaning that variable to `http_proxy='http://s460proxy:8080'`

~If you don't want to change this variable permanently, you can open the app with a temporary set variable from command line~

Update:
Sorry, I didn't noticed that you were on windows. On windows you need to update the env variables using UI. Let me know if you need help regarding this.

**Comment by Magdiel** [comment]
Hi @harryi3t , 

It doesn't work either. Got the same response that I got with curl -L -vv 

![image](https://user-images.githubusercontent.com/453279/42286021-71254176-7f7f-11e8-923b-6d36fdaf5cd3.png)

**Comment by harryi3t** [comment]
@Magdiel 
 1. How did you modify the env var `http_proxy`? My previous comment didn't apply since you are on windows.
 2. Does your proxy requires any authentication?

**Comment by Magdiel** [comment]
@harryi3t 

1. How did you modify the env var http_proxy? My previous comment didn't apply since you are on windows. 

> I use Rapid Environment Editor to modify my EV's.

2. Does your proxy requires any authentication?

> No

**Comment by codenirvana** [comment]
@Magdiel `Invalid Protocol` error is because of missing `http` protocol in `http_proxy` environment variable.

Are you facing the same issue even after setting it to `http://s460proxy:8080`?

**Comment by shamasis** [comment]
@Magdiel ... do let us know ... if adding http works, then we will simply document this. Would not like to change this cross-platform default behaviour of our underlying codebase.
