### ISSUE TITLE
Scrolling of documentation section in collection when used build mode

### ISSUE THREAD

**Issue by ghost** [a85/POSTMan-Chrome-Extension#4778]
**To Reproduce**
See the screenshot. Add more text to the documentation section.

**Expected behavior**
Scrolling through a large amount of text in documentation section when "Build mode" is used

**Screenshots**
![peek 2018-07-05 00-53](https://user-images.githubusercontent.com/12297432/42294973-7ccd39ec-7fee-11e8-95fb-d47a60e34216.gif)

**App information:**
 - App Type Electron Version 1.8.4
 - Postman Version 6.1.4
 - OS: Arch Linux

**Additional information**
https://aur.archlinux.org/packages/postman/

**Comment by prashantagarwal** [comment]
@viczem Can you update the Postman app to the latest version an verify if this is fixed for you.

**Comment by ghost** [comment]
Thanks, it fixed
