### ISSUE TITLE
Ability to sync postman collections with Atlassians Bitbucket

### ISSUE THREAD

**Issue by musanas** [a85/POSTMan-Chrome-Extension#4780]
Hi,
I know we have Postman-Github real time sync/backup integration available. 
A similar integration with Atlassians Bitbucket would help me because Bitbucket is what we use in our company

Thanks & Warm Regards
Musaffir

**Comment by rozling** [comment]
I'd like to add a +1 to this; Bitbucket is so integrated into our workflow that this integration would be extremely useful.

**Comment by tjohnson4** [comment]
+1. Being able to include postman collection configuration under the version control of our choice with the project source is required for us to adopt this tool across our engineering organization

**Comment by amiebrown** [comment]
+1.  I am very impressed with the direction of Postman and it's compelling features that are beginning to surpass those of SwaggerHub.  However, it's a big mistake for the Product Leaders of Postman to dismiss the value of an integration with bitbucket.  It feels like a bold move for Postman to build in version control as a first class feature in Postman.  It creates a silo'd pipeline independent of all of the other code that developers author.  There's significant value in the API docs and the code backing those APIs to move cohesively through a version control pipeline.  It's a reason that we'll continue to leverage authoring through SwaggerHub versus authoring in Postman.  SwaggerHub offers a rich integration with Bitbucket.

**Comment by paulyk1983** [comment]
+1

**Comment by karlOS123testing** [comment]
+1

**Comment by luiz-leite-dev** [comment]
+1

**Comment by Jlopezjlx** [comment]
This feature will be very helpful. +1

**Comment by eaboyle57** [comment]
+1

**Comment by thedev** [comment]
+1

**Comment by hynespm** [comment]
+1

**Comment by bc-lparsons** [comment]
+1

**Comment by weickmanna** [comment]
+1

**Comment by AbsolutePS** [comment]
+1

**Comment by shashankawasthi88** [comment]
Hi @musanas and others, the Integration to backup your Postman collection to Atlassian Bitbucket is now available in Postman. To configure the Bitbucket Integration go to Home > Integrations > Browse All Integrations > Bitbucket tile. Fill out the configuration form to setup the Integration. Follow the link https://learning.postman.com/docs/integrations/available-integrations/bitbucket/ to find more details about the Integration.
