### ISSUE TITLE
I'm unable to create a Mock in Postman

### ISSUE THREAD

**Issue by jayakanth459** [a85/POSTMan-Chrome-Extension#4781]
I'm unable to create a Mock in Postman, Initially i thought it's my n/w issue. I tried in different networks. yet still I'm unable to create a mock

**Comment by prashantagarwal** [comment]
@jayakanth459 What is your app version

**Comment by jayakanth459** [comment]
Postman for Windows
Version 6.1.4
win32 6.1.7601 / x64

**Comment by prashantagarwal** [comment]
@jayakanth459 Can you add some screenshots ?

**Comment by jayakanth459** [comment]
At "3. Next Steps" section, it'll always browse and at the end it'll show the attached screenshot
![issue](https://user-images.githubusercontent.com/8513982/42455637-70196386-83b0-11e8-814b-c02d8e4126c1.png)

.

**Comment by jayakanth459** [comment]
Do you've any update on this? Would you like me to record and share it? please let me know.

**Comment by prashantagarwal** [comment]
Hey @jayakanth459 Can you try this out on canary and check if you are still able to reproduce this. You can download canary from https://www.getpostman.com/canary

**Comment by jayakanth459** [comment]
Thanks. It worked for me now. What was the issue. Is this something different version?

**Comment by prashantagarwal** [comment]
Cool, good to know. I am not entirely sure but we fixed a lot of edge cases around mock, monitor and documentation creation. Also we have started releasing this on our stable Postman app in stages so soon this fix should be available there as well.

**Comment by jayakanth459** [comment]
Ok, I really appreciate your assistance. It helped us to choose postman for our automation testing with this suggestion. Thanks a lot for your time.

**Comment by prashantagarwal** [comment]
Thanks @jayakanth459 and stay tuned for whole new plethora of features in our future releases.
