### ISSUE TITLE
Better distinction between "Send and Download" and "Save"

### ISSUE THREAD

**Issue by franksands** [a85/POSTMan-Chrome-Extension#4782]
One common task in postman is to save the response as a file. However, not only **Send and download** is hidden in the **Send** button, the **Save** button does not do what one initially expects, which is to save the response to a file, since **Save** in most applications means save to a file in the computer the application is running.
I would like to request that the **Send and Download** button should be replace the **Save** button and functionality related to examples should be moved to the "Examples" drop down.

**Comment by sankalp0o** [comment]
Thanks for the input @franksands. While it might not be possible to move the 'Save response' as it serves a different function that a lot of users might be used to, we will look at bringing out the 'Download' functionality somewhere where you expect it to be.

**Comment by sujayvenaik** [comment]
Hey @franksands 

We have introduced a new Download button in the response section as part of various improvements we have made to how tabs work in Postman. These changes are up available on our canary channel (https://www.getpostman.com/canary) today and would soon be available on the stable channel. Do try these out in the canary and let us know.

**Comment by vkaegis** [comment]
Hey @franksands, closing this for now. Feel free to open another issue if you feel this does not suit your requirement.
