### ISSUE TITLE
"Error reading data file. Error: Could not determine format of file." when uploading JSON file in Runner

### ISSUE THREAD

**Issue by m3dbedb** [a85/POSTMan-Chrome-Extension#4784]
1. Postman Version: 6.1.4
2. App Windows x86 desktop app
3. File system NTFS
4. File format windows formattes ANSI txt
5. Did you encounter this recently, or has this bug always been there: It is my first installation, when uploading JSON file was getting error that app is unable to determine format but could manually select format from dropdown
6. Expected behaviour: JSON file gets uploaded in Runner

**Comment by m3dbedb** [comment]
Example file
[users2.txt](https://github.com/postmanlabs/postman-app-support/files/2166961/users2.txt)

**Comment by numaanashraf** [comment]
@m3dbedb Thanks for writing in. We are tracking this issue at #4591. Closing this as duplicate.
