### ISSUE TITLE
Move collections from a workspace to another (not "add to workspace" (copy) --> delete)

### ISSUE THREAD

**Issue by PetrusKiendys** [a85/POSTMan-Chrome-Extension#4785]
**Is your feature request related to a problem? Please describe.**
I want to be able to move collections and environments from one workspace to another, not simply add existing stuff (copying) to another, and then go through the old workspace and remove stuff from there.

**Describe the solution you'd like**
A "move" functionality for collections and environments

**Comment by numaanashraf** [comment]
@PetrusKiendys Thanks for the feature suggestion.

**Comment by vkaegis** [comment]
@PetrusKiendys We think alike! This was actually one of the first suggestions that came up internally once Workspaces were released. We definitely have this on our roadmap. No ETA on this just yet, but we'll keep you updated! :)

**Comment by Doogiemuc** [comment]
There is a workaround.  Tested with Postman v6.1.4  
Export your collection. Switch workspace. (Re-)import saved .postman_collection.json   Postman will even ask you if you want to copy the collection (into the new workspace) or if you want to overwrite it (meaning move it to the new workspace)

**Comment by moskytos** [comment]
Or delete needed collections from workspace A > sync > go to [trash](https://web.postman.co/me/trash?) > and restore collections to workspace B.
Hopefully, trash feature is enabled by default.

**Comment by kartech11** [comment]
agree, would love to have this feature

**Comment by jaykhimani** [comment]
Want it (now).

**Comment by danyalaytekin** [comment]
This would be very helpful.

**Comment by ttotal** [comment]
> Or delete needed collections from workspace A > sync > go to [trash](https://web.postman.co/me/trash?) > and restore collections to workspace B.
> Hopefully, trash feature is enabled by default.

it works!!!!!

**Comment by cesardka** [comment]
> There is a workaround. Tested with Postman v6.1.4
> Export your collection. Switch workspace. (Re-)import saved .postman_collection.json Postman will even ask you if you want to copy the collection (into the new workspace) or if you want to overwrite it (meaning move it to the new workspace)

Thank you for this quick and easy workaround!

**Comment by anrhodes** [comment]
Please add a Move function Postman
Even quicker than the above workarounds is to;

1. Share the Collection in WS1
2. Go to WS2 and Duplicate the shared collection
3. Still in WS2 Delete the original shared collection (this is now removed from WS1)
4. Rename the duplicate collection if desired

**Comment by justindonnaruma** [comment]
You can also use the "Fork" option:
* Create a fork in the workspace you want
* Delete the original

**Comment by jcrawfor74** [comment]
> 
> 
> Please add a Move function Postman
> Even quicker than the above workarounds is to;
> 
>     1. Share the Collection in WS1
> 
>     2. Go to WS2 and Duplicate the shared collection
> 
>     3. Still in WS2 Delete the original shared collection (this is now removed from WS1)
> 
>     4. Rename the duplicate collection if desired

Thanks to your suggestion.. I have come up with an even simpler way in two steps:

1. In WS1 share "collection A" to WS2
2. Still in WS1, right-click on "Collection A" and choose Remove form workspace.

This only removes it from WS1 and leaves it in WS2. 

Note: the environments do not come accross so you will have to export and import to hook them back  up to your new Workspace

**Comment by vkadam** [comment]
From PostMan web ui (not the app), either select add collection to workspace or environment to workspace, then select source workspace, collection and/or environment import. nJoy :)

**Comment by edesdan** [comment]
Looking forward to this feature!

**Comment by chrisyorkston** [comment]
Would love to have this feature.

**Comment by afitzgerald** [comment]
The current behavior is terrible...

I added an existing collection to a new workspace, deleted it from the original....what? it's magically deleted from both, yeah for the trash.

I finished moving a bunch of collections into a central workspace, deleted the other workspaces (without the above delete of the collection), perfect......that is until I notice the Environments didn't come along.......AND there appears no "Trash" for those...or for the Workspaces.  Guess I am shit out luck.  You need to make moving this stuff around more seamless.

**Comment by sankalp0o** [comment]
Thanks for the feedback everyone! I agree while "moving" a collection/environment is possible, it takes too many steps. We'll work on a better experience, possibly by introducing a "Move" action like everyone suggested.

Stan tuned, I'll update when we have made progress on this.

**Comment by thefoodiecoder** [comment]
We are waiting for this feature desperately. We have too many collections now, one per product group and we are working on moving them to different workspaces to declutter. This has become a tedious work for now. 

Also, moving environments should be seamless too. It will help us reorganizing which actually happens often in new companies.

**Comment by blakegearin** [comment]
Needing this feature as well. Any updates? @numaanashraf

**Comment by sankalp0o** [comment]
@blakebuthod We have this planned in our short-mid term roadmap. Please stay tuned, I'll update soon.

**Comment by PrashantKhpkr** [comment]
Sharing the collection works! And that is good enough for the moment.. however, import feature should be re-looked and rectified.

**Comment by sankalp0o** [comment]
Hi everyone, 

Based on your feedback we've made some changes in the latest Postman release. In the new version, while Sharing a collection you can choose to remove it from the current workspace. This is the same thing as "Move".

Do check it out and let us know if this makes your workflow easier or not! We'd also love any other feedback on the "Share" flow.

**Comment by paul-uz** [comment]
@sankalp0o since when does remove = move?

That's a terrible name.

Why can't you just implement a simple "move" feature?
