### ISSUE TITLE
Monitoring notifications are not clickable inside the app

### ISSUE THREAD

**Issue by a85** [a85/POSTMan-Chrome-Extension#4786]
Please read through the [guidelines](https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues) before creating a new issue.

**Describe the bug**
Saw a monitor failure but clicking on the links in the notification did not take me to the monitor page

**To Reproduce**
1. Go to the notifications dropdown when there is a new notification
2. Click on any link in the notification

**Expected behavior**
Nothing happens

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version: 6.1.4
 - OS: macOS

**Comment by sivcan** [comment]
This has been fixed in the latest version of the Postman App (v6.2).
