### ISSUE TITLE
Feature Request: Linking to a request (or other parts) for a better workflow

### ISSUE THREAD

**Issue by shamasis** [a85/POSTMan-Chrome-Extension#4788]
Kai pointed out a possible new feature (or some variants of it) to better collaborate within his team. Quoting him:

> Dear Shamasis: Postman feedback: I find it annoying that when I am talking about an API, I am not sure how to link to it and refer to it. 
> 
> Current workflow is, if we find a bug in an API, put it in the bugs folder and label it after the bug number. That's the only sane way to find the api request (And response). i.e. check in postman, in the bugs folders ,for bug 123's request

Maybe we could provide permalink on various places in app and dashboard to deep link them. Coupled with commenting and annotation it can be a slick workflow.

**Comment by a85** [comment]
Closing as this will be covered by the eventual move to the web.
