### ISSUE TITLE
Hitting Resync in the Settings>Sync section reliably produces a conflict window

### ISSUE THREAD

**Issue by abhijitkane** [a85/POSTMan-Chrome-Extension#4789]
**Describe the bug**
Hitting Resync in the Settings>Sync section reliably produces a conflict window. The conflicts are mostly for the "type" and "description" properties of environments/globals, but some are also for the exact same folder description.

**To Reproduce**
1. Go to Settings>Sync
2. Click 'Resync'

**Expected behavior**
Conflicts should only show up for data that actually differs, not for every env/global pair I have

**Screenshots**
Attached

**App information (please complete the following information):**
 - Native App
 - v6.1.4 (OSX)

<img width="732" alt="screen shot 2018-07-06 at 11 32 12" src="https://user-images.githubusercontent.com/681190/42362310-40bb496c-8110-11e8-93dd-709ddd945d29.png">

**Comment by a85** [comment]
Closing as issue as this is filed for a much older version.
