### ISSUE TITLE
I have the admin and billing roles, but I'm not able to remove other users from the team

### ISSUE THREAD

**Issue by abhijitkane** [a85/POSTMan-Chrome-Extension#4790]
**Describe the bug**
On the team management page, when attempting to remove a user from the team, I get a spinner that never goes away. The console shows a 'you are not part of this team' error in the WebSockets tab. I only have the admin and billing roles. My colleague, who has the admin, billing, and user roles, does not face this problem.

**To Reproduce**
1. Go to your team's 'manage team' page

**Expected behavior**
I should be able to remove users, since I'm the admin

**Screenshots**
An infinitely long spinner on the screen

**App information (please complete the following information):**
- Happens across browsers on the web dashboard

**Comment by D1rtyD** [comment]
I am still having this issue with removing a user from my team.  Do you know when this will be fixed yet?

**Comment by chrisdeso** [comment]
@D1rtyD Would you reach out to help@getpostman.com with all of the relevant information so that we can get this sorted for you?

**Comment by JChinoz** [comment]
Having this same issue. Unable to remove existing user

**Comment by preethammavin** [comment]
It has been fixed now, can you verify it works now? 

Closing the issue for now, feel free to open it if it persists.
