### ISSUE TITLE
[Monitor test failure] - "Anomalous test failure" error

### ISSUE THREAD

**Issue by loctb** [a85/POSTMan-Chrome-Extension#4793]
**Describe the bug**
While monitor is running, we got this error: Anomalous test failure.
In this case, we saw that postman will retry to call the APIs, but the biggest problem is we has the duplicate result in our server side.

**To Reproduce**
1. Make monitor with Folder's test
2. Monitor it
3. Wait until error happen

**Expected behavior**
If there is any problem, retry is OK, but Postman still can call our APIs, and result in our server side got duplicate.
Our expect: 
1. If error, postman need to alert that there is an error (in case can retry, it's better)

**Screenshots**
![image](https://user-images.githubusercontent.com/37455381/42434702-528a94f2-837e-11e8-88e4-dfcaf992d259.png)
![image](https://user-images.githubusercontent.com/37455381/42434720-6181ce9e-837e-11e8-9d67-00c3875d29d3.png)

**App information (please complete the following information):**
 - Postman Version 6.1.4 (6.1.4)
 - OS: macOS High Sierra 10.13.5 (17F77)

**Additional context**
- Account used to test: developer@uiza.io

**Comment by godfrzero** [comment]
@loctb If a monitor run fails after running successfully for a while, it's re-run internally to make sure that the failure wasn't due to any networking or infrastructure issues. This is the expected behavior. It looks like your monitor succeeded on the next run.

**Comment by loctb** [comment]
The main problem here is the "Anomalous test failure". We don't know why and when this happen.
After this error, monitor run twice, and the result will be incorrect at our server side.

**Comment by godfrzero** [comment]
Right, so in this case, "Anomalous test failure" means that a test which was passing in the past suddenly failed and we can't be sure that it's a legitimate failure (and not due to ephemeral network issues). In this case, the run is re-attempted. If it fails again, then this is reported as a failure and additional runs are not attempted until the next scheduled time.

Ideally, your requests and functions should be idempotent, so this isn't a problem.

**Comment by loctb** [comment]
Thanks @godfrzero , i will close this and recheck our side. Big thanks for support.
