### ISSUE TITLE
Ctrl+tab to shift between tabs

### ISSUE THREAD

**Issue by anudeepmedicharla** [a85/POSTMan-Chrome-Extension#4795]
I would like to shift between tabs by typing Ctrl+tab, the same way I do in chrome.

**Comment by sujayvenaik** [comment]
@anudeepmedicharla 
This shortcut is available on our windows and linux platform for switching between the tabs. 
Only in mac you shift using Ctrl + Shift + [.

**Comment by anudeepmedicharla** [comment]
@sujayvenaik Can we have the same shortcut in mac too?

**Comment by arunsathiya** [comment]
This is a great suggestion! On Mac though, I am currently using Cmd+1/2/n, as mentioned here https://blog.getpostman.com/2017/05/03/speeding-up-workflows-with-keyboard-shortcuts/

**Comment by rahulgolwalkar-one** [comment]
Can you please add support for Ctrl + Tab and Ctrl + Shift + Tab 
So that the behavior is in sync with that of Chrome or any other application in general

**Comment by dschmide** [comment]
Please add the option to switch back and forth between two tabs using CRTL + Tab. Most browsers already support this.

Tab A -> Tab B -> Tab A (instead of going through C, D, E F tabs which are also open.) I really dislike using CRTL + Shift + Tab. CRTL + Tab reflects the normal Alt + Tab more closely this way.

**Comment by l3ender** [comment]
This would be great. For the longest time I didn't know there were shortcuts for switching between tabs, because I figured that if ctrl+tab wasn't supported, nothing else would be either.

Ctrl+tab / ctrl+shift+tab is standard and it would be great for Postman to add support.

**Comment by harshit-j** [comment]
It would be great to have this shortcut. I constantly try switching tabs using Ctrl+TAB but it is not supported.

**Comment by simlf** [comment]
Hello, yeah this would definetely be a very good shortcut to have, to be able to cycle through the last used tabs with just Ctrl + Tab instead of Ctrl + Shift + Tab (like in Firefox), could you please implement that feature ?

**Comment by 2shrestha22** [comment]
It should be nice to have a setting to change the behavior of ctrl+tab.

**Comment by p1zz4br0etch3n** [comment]
Please also vote for my feature request: https://github.com/postmanlabs/postman-app-support/issues/10784

**Comment by saurabhjayant** [comment]
Hey, @anudeepmedicharla. Thanks for all the great feedback! We've been playing around with an idea that might help alleviate some of the issues that you mentioned with the tabbed experience in Postman. In the web app, you can now go to your Settings page and toggle a no-tab state, which completely removes tabs from Postman. This will allow you to use Postman with browser tabs like any other browser-based application and not have a lot of conflicts when it comes to shortcuts and browser functionality. As a part of this, we've also enabled Open in New Tab actions on most navigational items, so while by default, all pages open in the same tab, you can always explicitly open new tabs when you want to see things side by side. It'd be great if you could try this out and let us know how this works for your use case.

P.S. We're also exploring improvements for the desktop application but will use this to validate some approaches before we go ahead and do that.

**Comment by anudeepmedicharla** [comment]
Awesome! I'll try it out and share the feedback @saurabhjayant :)

**Comment by chris-torruella** [comment]
Hi folks, we released recently the Custom Keyboard Shortcuts feature that should allow you to move through tabs with your favourite keyboard combination, ctrl+tab in this case.
Let me know how did that go!
https://blog.postman.com/postman-customizable-keyboard-shortcuts/
