### ISSUE TITLE
Authorization tab takes up too much of the page

### ISSUE THREAD

**Issue by Postman-Gabriel** [a85/POSTMan-Chrome-Extension#4797]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated by how much space the authorization tab takes up on screen, reducing the space I can use to view other parts of the Postman App

**Describe the solution you'd like**
Add the ability to dynamically change the size of the tab by clicking and dragging.

**Describe alternatives you've considered**
Permanently change the size of the tab

**Comment by gkiely** [comment]
Thanks @gabriel-bronfman-postman 👍 

Here's a screenshot for reference:
![image](https://user-images.githubusercontent.com/1948935/42482477-04fe01b2-842b-11e8-9f8f-d4179a1055c2.png)

**Comment by a85** [comment]
We recommend using the 2-pane layout for now. A longer term solution for this issue is going to be the ability to reorder the tab configuration in the request. @vkaegis
