### ISSUE TITLE
Monitor summary E-mail is not properly linked to the monitor details page

### ISSUE THREAD

**Issue by anudeepmedicharla** [a85/POSTMan-Chrome-Extension#4798]
In the Monitor summary emails that I get, the footer says "Head on over to the Monitors dashboard to view details". But the "view details" is not linked to the monitor's detail page, rather, I was taken to the main dashboard. I guess this is a bug.

Steps to reproduce the behaviour:
1. Click on the "view details" link in the monitor summary email.

**Expected behaviour**
To take me to the monitor's detail page or to the all monitors browse mode.

**Screenshots**
![screen shot 2018-07-10 at 11 54 53 am](https://user-images.githubusercontent.com/16399370/42493945-6b48fb82-843c-11e8-843b-aa6e67bf3d8e.png)

**Comment by preethammavin** [comment]
@godfrzero can we update the monitor summary mails to link to the monitor usage page?

**Comment by godfrzero** [comment]
This has been fixed in the latest release, the link now points to the monitor usage page.
