### ISSUE TITLE
App and Web are not in Sync.

### ISSUE THREAD

**Issue by sumit0k** [a85/POSTMan-Chrome-Extension#4799]
**Describe the bug**
App is showing orange icon, but still App and Web data are not in sync, Environment data is not updated and requests are shown outside of folder in Web. App has latest data and I have done resolve conflicts multiple times but still data is not up.

**To Reproduce**
Not sure on steps on how to reproduce, I didn't do anything new just regular add and edit requests in a collection and moving around in folder.

**Expected behavior**
App and Web data should be in sync

**Screenshots**
Developer Console logs
<img width="912" alt="screen shot 2018-07-10 at 4 55 12 pm" src="https://user-images.githubusercontent.com/7878332/42507984-a0bd610e-8464-11e8-9294-75467a2edfa9.png">

**App information (please complete the following information):**
 - App Type Native App
 - Postman Version 6.1.4
 - OS: macOS High Sierra 10.13.5

**Additional context**
Previously it was stuck with blue icon, which got resolved after disconnecting and reconnecting in offline mode via Developer Shell

**Comment by sumit0k** [comment]
On clicking manual resync from Preferences in menu, I am getting following logs and both app and web are still not in sync.

Note: I am getting popup for resolving conflicts.

<img width="912" alt="screen shot 2018-07-11 at 7 21 35 pm" src="https://user-images.githubusercontent.com/7878332/42576382-d50f17a0-853f-11e8-8c30-31ad106cf156.png">

**Comment by stixaw** [comment]
I can sync through the web on my Win Server 2016 but the app keeps saying enable syncing and just sitting there.  I can run gets etc through it but can't sync

**Comment by dantench** [comment]
I've been having a similar issue where the APP and the Web server appear to be out of sync, in some cases by quite a significant space of time, this all despite having an orange sync icon and everything looking as though it's alright. When doing a sync in my app (v6.2.3 - pro license), I get a different error in dev tools to the OP, which I've attached. I'm on Windows 10.

![image](https://user-images.githubusercontent.com/29710317/43642739-b001a610-9720-11e8-9a83-bda6080e8f8f.png)

Line 51898 is: if (!key) {console.warn(`Could not find on ${this.constructor.name}. Missing or invalid parameter.`);return;}return this.members.get(key);}filter(criteria) {return _.filter(this.values, criteria);}update(definition) {if (!definition) {console.warn(`Could not perform update on ${this.constructor.name}. Missing arguments.`);return;}let primaryKey = this.primaryKey,primaryKeyValue = definition[primaryKey],itemToUpdate;if (!primaryKeyValue) {// @todo: should throw?

![image](https://user-images.githubusercontent.com/29710317/43642834-fb9ea33e-9720-11e8-9f0f-248fd5f5ddac.png)

**Comment by sumit0k** [comment]
I am on latest version 6.2.4 and similar error is happening for my another workspace.

**Comment by kamalaknn** [comment]
Hey @sumitkumar1209 @dantench 

We made some improvements to the syncing flows in Postman v7. Can you upgrade to latest version of Postman above v7 and let us know if you are still seeing any issues?

**Comment by preethammavin** [comment]
Closing the issue for now, feel free to reopen it if it isn't resolved
