### ISSUE TITLE
Freak duplication of requests

### ISSUE THREAD

**Issue by dennisslavid** [a85/POSTMan-Chrome-Extension#4800]
**Description**
Requests are automatically duplicated from time to time. Happens very randomly.

**To Reproduce**
Unfortunately haven't found a way to willingly reproduce the problem.

**Screenshots**

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version: 6.1.4
 - OS: Windows 10

**Additional context**
Today it occurred at exactly the same time as another issue where the name of a collection was changed day A and automatically changed back to the old name day B. Feels like a sync issue.

**Comment by numaanashraf** [comment]
@dennisslavid Thanks for reporting this. This seems like a tricky one to reproduce at our end, could you mail us at help@getpostman.com with your account details and the collection/request names where you noticed this issue? We'll check for any anomalies at our end.

**Comment by cedx** [comment]
Same issue here. No idea how that happens (like @dennisslavid , this happens randomly).
More annoying : if I delete one of the duplicated request, on the next app start, the two requests are deleted!

I use two instances of the Postman app : a Windows one at my work, a Linux one at my home. It seems that this issue occurs when I create a request on one of the two apps, and the sync is triggered on the other app.

App type: the native app.
Postman version: 6.4.4
OS: Windows 10 and Ubuntu 18.04.1.

**Comment by sujayvenaik** [comment]
Hey @dennisslavid @cedx 
Can you update to the latest app (v7.x) and try if this is still happening?

**Comment by dennisslavid** [comment]
Hey @sujayvenaik 
I have updated on my primary device already, which is still running windows 10. My secondary device has recently changed OS and is now running Ubuntu 18.04. Unfortunately it seems the update isn't available through snap yet though and I do prefer to wait for the update there over using a tarball to install the latest.

Meanwhile, with the Linux machine on 6.x and Windows machine on 7.x, sync doesn't seem to work between the two machines. This isn't a problem for me, but I can't test if the issue still occurs at this time.

If you ping me as soon as the latest version is available through snap, I'll make sure to update, do some testing and return here with my findings.

**Comment by numaanashraf** [comment]
@dennisslavid Please follow the instructions at https://learning.getpostman.com/docs/postman_pro/managing_postman_pro/migrating_to_v7/#updating-app-to-postman-v7-after-migration to update your snap to Postman v7.0.

**Comment by sujayvenaik** [comment]
Hey @dennisslavid 
Closing this issue for now. Let us know if you face this issue again and feel free to reopen this thread. We will take a look.
