### ISSUE TITLE
Postman Canary-6.1.3 fails to install on Windows x64

### ISSUE THREAD

**Issue by Postman-Gabriel** [a85/POSTMan-Chrome-Extension#4801]
After running the installer, it briefly shows an installing gif, after which is crashes and fails to install. Running as admin doesn't seem to fix.

**To Reproduce**
1. Go to getpostman.com
2. Download versions 6.1.3-Canary
3. Open Installer
4. Unable to install

**Expected behavior**
Expected the installer to properly install the application

**Screenshots**
Console logs:
INFO : 2018/07/06 09:10:47.560144 main.go:80: --------
INFO : 2018/07/06 09:10:47.581088 main.go:81: Starting Postman...
INFO : 2018/07/06 09:10:47.581088 main.go:82: Current path: C:\Users\User\Desktop\da installare\postman-portable-win64-6.1.3-4
INFO : 2018/07/06 09:10:47.581088 main.go:87: Lookup app folder in: C:\Users\User\Desktop\da installare\postman-portable-win64-6.1.3-4\app
INFO : 2018/07/06 09:10:47.581088 main.go:91: Electron app folder found: app-6.1.3
INFO : 2018/07/06 09:10:47.581088 main.go:158: Process: C:\Users\User\Desktop\da installare\postman-portable-win64-6.1.3-4\app\app-6.1.3\Postman.exe
INFO : 2018/07/06 09:10:47.582141 main.go:159: Args:  
INFO : 2018/07/06 09:10:47.582141 main.go:160: Working dir: C:\Users\User\Desktop\da installare\postman-portable-win64-6.1.3-4\app\app-6.1.3
INFO : 2018/07/06 09:10:47.582141 main.go:161: Data path: C:\Users\User\Desktop\da installare\postman-portable-win64-6.1.3-4\data
INFO : 2018/07/06 09:10:47.582141 main.go:163: Launch Postman...
INFO : 2018/07/06 09:10:47.582141 main.go:170: Exec C:\Users\User\Desktop\da installare\postman-portable-win64-6.1.3-4\app\app-6.1.3\Postman.exe  

**App information (please complete the following information):**
 - App Type: Native
 - Postman Version: Canary -> 6.1.3
 - OS: Windows x64

**Additional context**
Tried with Postman Portable as well, still no luck.

**Comment by Master0rochi** [comment]
I tried to do this, and I couldn't install it. Even tried with the Canary version and was exactly the same.

**Comment by numaanashraf** [comment]
This seems related to https://portapps.io/app/postman-portable/, which is an unofficial and unsupported package. Closing this.
