### ISSUE TITLE
Response body is taller than the space allocated for it

### ISSUE THREAD

**Issue by brpeterman** [a85/POSTMan-Chrome-Extension#4803]
**Describe the bug**

The response body section of a request always overflows the space allocated for it, resulting in double scrollbars in the app. Based on #1642, this appears to be unintended. The issue I see is identical to the one recorded in that issue.

The result of this behavior is that I have to use two different scrollbars to get to the bottom of my response body.

This does not happen in two-pane view.

**To Reproduce**

1. Send a request that is long enough to create a scrollbar in the response body text area.

**Expected behavior**

There is one scrollbar for the response body, and there is no scrollbar for the request tab itself.

**Screenshots**

* (from #1642) https://i.gyazo.com/4a2dd65f6450e355939e88c184b4e01a.mp4
* (produced just now) https://gfycat.com/RegularCreepyKomododragon

**App information (please complete the following information):**
 - App Type: Native app
 - Postman Version: 6.1.4
 - OS: macOS Sierra 10.12.6

**Comment by numaanashraf** [comment]
@brpeterman Thanks for reporting this. We are tracking this suggestion at a similar issue that got reported earlier - #4744. Closing this.
