### ISSUE TITLE
URL highlighting causes the URL text to glitch out, unviewable

### ISSUE THREAD

**Issue by Postman-Gabriel** [a85/POSTMan-Chrome-Extension#4804]
Please read through the [guidelines](https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues) before creating a new issue.

**Describe the bug**
When highlighting the request URL in Mac OSX Mojave (Beta), the URL becomes unreadable and turns an odd color

**To Reproduce**
1. Download Postman on your Mojave OSX machine
2. Create a new request
3. Highlight URL of request

**Expected behavior**
Expected to see URL in the highlight

**Screenshots**
![postman-mojave-bug](https://user-images.githubusercontent.com/40899145/42652682-fe35b4ee-85c7-11e8-8fe5-45358591c34e.png)

**App information (please complete the following information):**
 - App Type Native App
 - Postman Version 6.1.4
 - OS: Mac OS X Mojave

**Comment by abhididdigi** [comment]
I verified this, and this happens if you select your "highlight color" in System Preferences -> General to purple, I think.

**Comment by abhididdigi** [comment]
Folks - I upgraded to beta 2 of Mojave, and this is now fixed. Please close the issue.
