### ISSUE TITLE
Entire Standalone App is blank

### ISSUE THREAD

**Issue by Postman-Gabriel** [a85/POSTMan-Chrome-Extension#4805]
Please read through the [guidelines](https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues) before creating a new issue.

**Describe the bug**
Every window, from console to the main Postman window, is blank and unusable.

**To Reproduce**
1. Install 6.1.4 on a Windows 8.1 x64 machine
2. See the entire application blank

**Expected behavior**
Expected an actual app, not just a blank GUI

**Screenshots**
![image](https://user-images.githubusercontent.com/40899145/42541140-176e8760-8456-11e8-837e-e3e026313af3.png)
![image](https://user-images.githubusercontent.com/40899145/42541148-1d9f4e12-8456-11e8-996e-75482e64f1e6.png)

**App information (please complete the following information):**
 - App Type: Native (Chrome app works fine on the system)
 - Postman Version 6.1.4
 - OS: Windows 8.1 x64

**Comment by SamvelRaja** [comment]
Related to #4594 
Kindly follow the workaround in the comment https://github.com/postmanlabs/postman-app-support/issues/4594#issuecomment-391601621
