### ISSUE TITLE
SSL certificate verification issues for Corp Internal CA certs?

### ISSUE THREAD

**Issue by sudhagarc** [a85/POSTMan-Chrome-Extension#4806]
**Describe the bug**
When issuing an API request to a SSL/TLS enabled endpoint with "SSL Certificate Verification" turned on in Postman preferences results in:

```
Could not get any response
There was an error connecting to https://<MASKED>
```

When SSL Certificate Verification is turned off, then it works fine. However, the same endpoint from same machine via. Chrome browser and curl command line works fine. In other words, Chrome reports the web site as "SECURE" and Curl gives proper response without "-k" option.

The endpoint is signed by Corporate Intermediate CA and the certificates are loaded onto my machine (client) where I'm invoking Postman, browser and/or curl commands.

Why this might have happened:

**To Reproduce**
1. Go to 'Postman -> Preferences -> General -> Request -> Turn on "SSL certificate verification"'
2. Create a simple "GET" Request to endpoint and Click on "Send"
3. On the bottom pane, "Could not get any response" and the standard error blob is noticed

I verified that endpoint does get the request, so there is no response timeout.

**Expected behavior**
Request to go through successfully and get a response, not give an error.

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version: 6.1.4
 - OS: macOS High Sierra 10.13.5

**Additional context**
I click on the "Code" on Postman and copy the cURL script and execute on command line and it works fine.

```
$ curl -X GET \
→   https://<MASKED> \
→   -H 'Authorization: Bearer <MASKED>' \
→   -H 'Cache-Control: no-cache' \
→   -H 'Content-Type: application/json'
<RESPONSE-RECEIVED-MASKED>
$
```

**Comment by sudhagarc** [comment]
Hmm! This one seem to be related to https://github.com/postmanlabs/postman-app-support/issues/3152.

**Comment by numaanashraf** [comment]
Yes @sudhagarc - this seems related to #3152. Postman doesn't support custom intermediate CA at the moment and hence we can't verify these SSL certs. The quick workaround till we support this is to keep the SSL verification turned off in the Settings. I'm closing this issue as a duplicate. Please follow #3152 for updates.

**Comment by shona-code** [comment]
Error: connect ETIMEDOUT 104.27.134.11:443
in console kindly help

**Comment by shona-code** [comment]
Could not get any response
There was an error connecting to https://reqres.in/api/users.
Why this might have happened:
The server couldn't send a response:
Ensure that the backend is working properly
Self-signed SSL certificates are being blocked:
Fix this by turning off 'SSL certificate verification' in Settings > General
Proxy configured incorrectly
Ensure that proxy is configured correctly in Settings > Proxy
Request timeout:
Change request timeout in Settings > General
I did everything but no solution for this
