### ISSUE TITLE
Change response data in test script

### ISSUE THREAD

**Issue by coder-free** [a85/POSTMan-Chrome-Extension#4809]
I want decrypt the response data.
For example,
response data from server is:
![image](https://user-images.githubusercontent.com/2630290/42556897-a187b9b6-851f-11e8-8bd7-b423651e9787.png)
and test script set to this:
![image](https://user-images.githubusercontent.com/2630290/42557051-007cf26a-8520-11e8-8ac3-5af81bac617c.png)
and logged the "decryptedData" value is decrypted. But the showing response data is not decrypt.

**Comment by numaanashraf** [comment]
@zfavourite99 Thanks for the feature suggestion.

**Comment by codenirvana** [comment]
@zfavourite99 You can achieve this by using the new **Visualizers** feature added in the lastest Postman app v7.7.

Example:
```js
pm.visualizer.set(`
<div id="response"/>

<script src="https://cdnjs.cloudflare.com/ajax/libs/crypto-js/3.1.9-1/crypto-js.min.js"></script>

<script>
pm.getData((err, data) => {
    var ciphertext = data.response.data;
    var bytes  = CryptoJS.AES.decrypt(ciphertext.toString(), 'secret-key');
    var plaintext = bytes.toString(CryptoJS.enc.Utf8);
    
    var output = JSON.stringify({ ciphertext, plaintext }, null, 2).replace(/\\n/g, '<br>');

    document.getElementById("response").innerHTML = output;
});
</script>

`, {
    response: pm.response.json()
});
```

<img width="1031" alt="Screenshot 2019-09-17 at 6 01 36 PM" src="https://user-images.githubusercontent.com/4865836/65041828-3845a480-d975-11e9-88d6-955bc9db7931.png">

Learn more about visualizers: https://learning.getpostman.com/docs/postman/sending_api_requests/visualizer/

Let me know if that fixes your issue!

**Comment by coder-free** [comment]
@codenirvana  
`pm.visualizer.set();` worked fine on "request" test script, but not work on "collection" test script.
