### ISSUE TITLE
Tests- JSON.parse(responseBody) extracted value doesn't correspond with the value in the response body

### ISSUE THREAD

**Issue by hdjhuang** [a85/POSTMan-Chrome-Extension#4810]
Hello, I have 2 APIs. API1 get uri's value(i.e: test1234567890), id's value(i.e: test1234567890),requestNumber's value(i.e: 1892),requestedItemName's value(i.e: AAA- test00001), status's value(i.e: Submitted) from API1's response body, 
API2 will use those from API1's response body.
I can get value for "href","state","start-date", but I can not get value which I mentioned aboved: uri's value(i.e: test1234567890), id's value(i.e: test1234567890),requestNumber's value(i.e: 1892),requestedItemName's value(i.e: AAA- test00001), status's value(i.e: Submitted)

Postman Version:  v6.1.4 
OS details: Win 7 / x64

sampleResponse Body:
{
    "href": "https://localhost:8081",
    "relations": {
        "link": [
            {
                "href": "https://localhost:8081",
                "rel": "up"
            },
            {
                "href": "https://localhost:8081",
                "rel": "remove"
            },
            {
                "href": "https://localhost:8081",
                "rel": "logs"
            },
            {
                "href": "https://localhost:8081/",
                "rel": "state"
            }
        ]
    },
    "id": "123456",
    "state": "completed",
    "start-date": 1531279570286,
    "end-date": 1531279571998,
    "started-by": "test",
    "name": "test",
    "input-parameters": [
        {
            "value": {
                "string": {
                    "value": "test/item/671890ce-fce6-4407-bf4d-e60faeb0843c/test"
                }
            },
            "type": "string",
            "name": "uri",
            "scope": "local"
        },
        {
            "value": {
                "string": {
                    "value": "{\"jsonrpc\": \"2.0\", \"method\": \"startRequest\", \"params\": [{}, \"c3f20aa7-e0b7-491f-8c68-96e2d37a0000\"]}"
                }
            },
            "type": "string",
            "name": "payload",
            "scope": "local"
        }
    ],
    "output-parameters": [
        {
            "value": {
                "string": {
                    "value": "{\"jsonrpc\":\"2.0\",\"result\":{\"uri\":\"test/request/test1234567890\",\"id\":\"test1234567890\",\"requestNumber\":\"1892\",\"requestedItemName\":\"AAA- test00001\",\"status\":\"Submitted\"}}"
                }
            },
            "type": "string",
            "name": "output",
            "scope": "local"
        }
    ]
}

Test scripts:
tests["responseBody has uri"] =responseBody.has("uri");
var uri =responseBody.has("uri");
console.log("-----------jsonData.id="+jsonData.id);
console.log("-----------jsonData.name="+jsonData.name);
console.log("-----------jsonData.value="+jsonData.value);
console.log("-----------jsonData.relations="+jsonData.relations);
console.log("-----------jsonData.input-parameters="+jsonData.output-parameters);

Postman console log:
-----------responseBody uri=undefined
-----------jsonData.id=8a076d1663d998380164884089b01bba
-----------jsonData.name=RPC Dispatcher
-----------jsonData.value=undefined
-----------jsonData.relations=[object Object]
ReferenceError | parameters is not defined

I want to get uri's value(i.e: test1234567890), id's value(i.e: test1234567890),requestNumber's value(i.e: 1892),requestedItemName's value(i.e: AAA- test00001), status's value(i.e: Submitted).
Could you please help me resolve the issue? Thank you very much!

**Comment by numaanashraf** [comment]
@hdjhuang Looks like your script has an invalid JavaScript. you can access the values you need via the following script.

```
var outputParameters = jsonData["output-parameters"];
// get more information you need from outputParameters
```

Please note that we do not support debugging support for JavaScript here. The best place to reach out for help is via Postman's user community (https://community.getpostman.com)

**Comment by hdjhuang** [comment]
@numaanashraf . Thanks for your quick response. I also tried to search from Internet but can not find solution.
I tried to use:
var outputParameters = jsonData["output-parameters"];
and got outputParameters is an object, how can I get the values I expected? Could you please give me a  sample? For example: how to get uri's value(i.e: test1234567890)? 
Thanks for your great support!

**Comment by numaanashraf** [comment]
@hdjhuang you could try
```
var uri = outputParameters[0].value.string.value.result.uri;
```

But it looks like `outputParameters[0].value.string.value` is a stringified JSON value. If that is the case, you need to parse that again.

```
var outputValue = outputParameters[0].value.string.value;
var parsedValue = JSON.parse(outputValue);
var uri = parsedValue.result.uri;
```

**Comment by hdjhuang** [comment]
@numaanashraf  It works perfectly. 
 Thanks for your great support!
