### ISSUE TITLE
Why is Postman only opening an ipv6 based proxy for capturing feature?

### ISSUE THREAD

**Issue by ayushkamadji** [a85/POSTMan-Chrome-Extension#4811]
**Describe the bug**
Postman's capturing feature opens a proxy for requesting clients to redirect to. The menu/modal dialog that sets this up does not mention an IP version, only port and target. I expected Postman to open an IPv4 tcp port but it instead opens and IPv6 one (with the correct port number). There is no option to set IP version mode for the capturing proxy in the UI. This behavior is rather unexpected. Or is it supposed to create both but failed on IPv4 mode? 

I made sure the ports I assigned were unused so that shouldn't be the source of the problem.

**To Reproduce**
1. Open Postman native app
2. Click satellite button
3. Set port xxxx and arbitrary target
4. Go to shell and type `sudo netstat -ltpn|grep Postman`
5. Will get only tcp6 ports
6. Try setting your system or browser network connection to use the proxy port with ipv4 loopback (127.0.0.1) address and it will fail.
7. You can still use the ipv6 loopback address (::1)

**Expected behavior**
Open an ipv4 tcp port or option to do so or some configuration that allows

**App information (please complete the following information):**
 - Native app
 - Version: 6.1.3
 -  OS: Linux [***] 4.10.0-38-generic #42~16.04.1-Ubuntu SMP Tue Oct 10 16:32:20 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by DannyDainton** [comment]
Hey @numaanashraf 

Is this still a valid issue or could we close this?

**Comment by iamchughmayank** [comment]
@ayushkamadji  - In case ipv6 is available, Postman will use it and start the proxy server at "::", however, if it is not available, the proxy server will be started at "0.0.0.0".

I hope this answers your query. Please feel free to reopen the ticket if find any issue in this.

**Comment by chughmayank** [comment]
@ayushkamadji  - In case ipv6 is available, Postman will use it and start the proxy server at "::", however, if it is not available, the proxy server will be started at "0.0.0.0".

I hope this answers your query. Please feel free to reopen the ticket if find any issue in this.

**Comment by flexchar** [comment]
@chughmayank @DannyDainton 

Hi, I'm trying to listen on IPv4 even though my Ubuntu workstation supports IPv6. My client fails to connect using IPv4. Does it mean that we're forced to IPv6 if that's supported?

I mean I'm running latest Ubuntu 22.10 but there's no IPv6 support from my router/ISP. So it's only the Postman that thinks this way...
