### ISSUE TITLE
The 'Import Test Run' button text goes out of bounds when the window width is reduced

### ISSUE THREAD

**Issue by abhijitkane** [a85/POSTMan-Chrome-Extension#4812]
**Describe the bug**
The button text doesn't wrap properly

**To Reproduce**
1. Open the Runner
2. Reduce window width

**Expected behavior**
Text wraps correctly, or the button min-width is set correctly

<img width="339" alt="screen shot 2018-07-11 at 20 27 58" src="https://user-images.githubusercontent.com/681190/42580902-34fcc028-8549-11e8-98d5-0aa8f791caad.png">

**Comment by sivcan** [comment]
This has been fixed in the latest version of the Postman App (6.4)
