### ISSUE TITLE
Exported collection is not valid for Postman API

### ISSUE THREAD

**Issue by loopDelicious** [a85/POSTMan-Chrome-Extension#4813]
**Describe the bug**
Exporting a collection that has a saved response with no headers results in a collection JSON that is not valid for use with Postman API.

**To Reproduce**
1. Create a mock using the +New button.
1. Export the resulting collection (v2.1) from the Postman app
1. The collection’s response headers is `null` when no response headers. 
![screen shot 2018-07-11 at 1 07 37 pm](https://user-images.githubusercontent.com/17693714/42597188-cfc7ebec-850c-11e8-939b-b6bfe0ff9fea.png)
1. This breaks when updating a collection using the Postman API to `PUT` the collection.
1. If I change the `null` to `[]`, the `PUT` is successful.

**Expected behavior**
Collection's response headers should be `[]` instead of `null` when no headers.

**App information:**
 - Native app
 - Postman Version 6.1.4
 - OS X 16.5.0 / x64

**Comment by thecuriousdev** [comment]
Hey @loopDelicious, I tried from my end its working fine. Can you share the collection with me?

**Comment by loopDelicious** [comment]
@thecuriousdev this is the exported collection with the response's headers showing `null`.
[Example_for_GitHub.postman_collection.json.zip](https://github.com/postmanlabs/postman-app-support/files/2211037/Example_for_GitHub.postman_collection.json.zip)

**Comment by kunagpal** [comment]
@loopDelicious This has now been fixed.

**Comment by deepakpathania-zz** [comment]
@kunagpal The schema needs to be updated in the backend service as well for this issue to be resolved for the end user, sending a PR with the updated schema to the concerned service and reopening it for now.

**Comment by deepakpathania-zz** [comment]
This has now been fixed.
