### ISSUE TITLE
App Icon disappears 

### ISSUE THREAD

**Issue by Postman-Gabriel** [a85/POSTMan-Chrome-Extension#4814]
**Describe the bug**
When looking at the Postman app, the logo for the shortcut disappears. It becomes the standard white page. 

**To Reproduce**
1. Have a Windows x64 machines
2. Download Postman 6.1.4
3. See Error

**Expected behavior**
Expected a logo to show

**Screenshots**

**App information (please complete the following information):**
 - App Type Native: App
 - Postman Version: 6.1.4
 - OS: Windows 10 x64

**Comment by Postman-Gabriel** [comment]
The issue also is present on Ubuntu 18.04

**Comment by SamvelRaja** [comment]
@gabriel-bronfman-postman for Ubuntu can you check this fix https://github.com/postmanlabs/postman-app-support/issues/4637#issuecomment-401349097
?

And for the Windows, does it happened after upgrading to 6.1.4? Can you provide your OS config?

**Comment by Postman-Gabriel** [comment]
@SamvelRaja I believe that he is on Windows 10 x64 and only encountered the error once he upgraded. From my experience, it seems that we have an influx of such tickets recently on this issue.

**Comment by SamvelRaja** [comment]
Thanks @gabriel-bronfman-postman  It is very hard to reproduce this. I will update the thread on the progress soon.

**Comment by chrsmrtn-** [comment]
I have this issue too. Let me know if you need info from my environment, Win 10 64bit

**Comment by SamvelRaja** [comment]
@chrsmrtn- thanks for jumping in and trying to help. Is this issue happening always or only on certain time. 
Also, if it happened from a particular time means is it possible to provide information on this?

**Comment by Tadimsky** [comment]
I see the same thing - this is the icon on the Taskbar. 
![image](https://user-images.githubusercontent.com/1149244/43618900-f0685678-967f-11e8-92d0-19b3b23d9ea8.png)


It happens all the time and shows up in the Start Menu as well

![image](https://user-images.githubusercontent.com/1149244/43618914-0aa64b80-9680-11e8-8d90-25d3a7967534.png)

**Comment by Tadimsky** [comment]
When I tried to manually change the icon I got this error:

![image](https://user-images.githubusercontent.com/1149244/43618935-269b338c-9680-11e8-9bdf-deeea0094149.png)

Verision 6.0.10 does not exist on my machine anymore. 
![image](https://user-images.githubusercontent.com/1149244/43618957-47f92016-9680-11e8-9301-adb0345c6a98.png)

So maybe the shortcut isn't being updated after update?

**Comment by SamvelRaja** [comment]
@Tadimsky  Thanks, this helped in finding the issue. I will update the thread once it gets fixed.

**Comment by datacreed** [comment]
Same here,  I recreated a shortcut from the app executable for now, seemingly in early July 2018, which appears when this thread was created, but it works.  Icon is paper-white.

**Comment by jamestown27** [comment]
This has also recently been happening to me on Windows 10 64bit and I've found a few temporary workarounds for this until it gets fixed. I can confirm that this issue seems to happen every time there is a Postman update.

One workaround is to right click the Postman icon on the taskbar (when its running) and click "Pin to taskbar", right after you do this right click the icon again and click "Unpin from taskbar" - this normally makes the icon appear correctly. For me as soon as I click "Pin to taskbar" it makes the icon turn white again (even if it is currently showing up) so I can reproduce this at any time.

Another workaround is to try to right click the Postman icon from the desktop and change the "Start in:" path to be the location of the latest Postman update - ie: C:\Users\UserDirHere\AppData\Local\Postman\app-6.2.4 . Then select the "Change Icon..." and select C:\Users\UserDirHere\AppData\Local\Postman\app-6.2.4\Postman.exe.

**Comment by joebri** [comment]
Am also getting this issue after latest (6.2.4) update. The above suggestion for a fix (by jamestown27) had worked for a previous update but... not this time. I get an error saying the folder is not valid, even though I've cut-&-pasted it from windows explorer. (This is on Windows 7 Enterprise). 

Edit: My workaround was to create a shortcut directly to the 6.2.4 exe location!

**Comment by SamvelRaja** [comment]
This has been patched up in the latest 6.2.5. Requesting everyone to update 😄

**Comment by matpag** [comment]
It's working now on Windows, thank you 👍

**Comment by bluppfisk** [comment]
Those looking how to fix this on Ubuntu, please check https://github.com/postmanlabs/postman-app-support/issues/4637

**Comment by jkbhu85** [comment]
App Icon not available in version 7.3.6 on windows 10 x64 1803.

**Comment by jkbhu85** [comment]
Resolved the issue using this link [https://github.com/postmanlabs/postman-app-support/issues/3107](https://github.com/postmanlabs/postman-app-support/issues/3107)

**Comment by gmattie** [comment]
This issue appeared for me on v7.5.0 on Windows 10 64-bit.

This fix detailed in **[this post](https://github.com/postmanlabs/postman-app-support/issues/3107#issuecomment-407789469)** solved the issue.

**Comment by JSmythSSG** [comment]
Same issue for me on  v7.6.0 too

**Comment by westmeadwestmead** [comment]
I got the same issue with v7.6
Update to v7.7.2 fixed the issue.

**Comment by ahmad-elkomey** [comment]
I'm using v7.36.0 on Ubuntu 18.04.2 LTS. Same issue. Postman is working with no icon at all. 
![Screenshot from 2020-12-02 17-30-28](https://user-images.githubusercontent.com/7439727/100893577-2ee62080-34c4-11eb-8db1-509ba385c63e.png)
