### ISSUE TITLE
Feature: Import from restlet client (DHC)

### ISSUE THREAD

**Issue by shivan** [a85/POSTMan-Chrome-Extension#4816]
**Is your feature request related to a problem? Please describe.**
Currently it is not possible to import a restlet export into postman. So all requests have to be recreated in postman.

**Describe the solution you'd like**
Possibility to import a restlet export.

**Describe alternatives you've considered**
manually recreate the requests

**Comment by numaanashraf** [comment]
@shivan We have rudimentary support for DHC exports. Could you give us a sample DHC file that you tried importing?

**Comment by shivan** [comment]
Hi @numaanashraf ,

that's the error I get:
![image](https://user-images.githubusercontent.com/1827692/42682147-045ace5a-868a-11e8-9375-fb545d225213.png)

I attached the simple example
[test.zip](https://github.com/postmanlabs/postman-app-support/files/2191955/test.zip)

Generated via export in Restlet Version: 2.18.0

Import tried in Postman latest version (whatever this is, because there is no "Help" -- "About" which shows version).
I tried by clicking import and then drag'n'drop the .json file.

**Comment by a85** [comment]
We are moving this functionality out into plug-ins and we will track importer related issues separately. Closing this issue for now.

**Comment by czim** [comment]
I had this, but only when I tried to export *everything* at once. Exporting individual projects separately works -- the separate exports import successfully. So if anyone runs into this one, this may help as a work-around until it is fixed.

Edit: there are some Projects for which it still fails in this way though, I just noticed. No idea what sets them apart...
