### ISSUE TITLE
Postman console won't open sometimes

### ISSUE THREAD

**Issue by loopDelicious** [a85/POSTMan-Chrome-Extension#4817]
**Describe the bug**
Sometimes the Postman console window will not open.

**To Reproduce**
1. Click on the Postman console icon in the bottom left footer
2. or Use the keyboard shortcut (⌥⌘C) on Mac
3. or Select from the Menu > View > Show Postman console

**Expected behavior**
Expect a new window to open and show the console, but nothing happens

**App information:**
 - Native app
 - Postman Version 6.1.4
 - OS X 16.5.0 / x64

**Additional context**
Occurs intermittently, at least 1x/week. Rebooting the Postman app fixes the problem.

**Comment by prashantagarwal** [comment]
@loopDelicious There was some UI bug on the icon which we fixed. Shortcuts might not work in the case when you are using some app like spectacle whose shortcuts conflict with app. If you see this not working as expected in future please let me know.

**Comment by Nmirontsev** [comment]
@prashantagarwal , I see this issue now on my Catalina Mac. I can't open console for the last at all. Not even once.

**Comment by ritwijsinha** [comment]
@Nmirontsev

How are you trying to open Postman Console? Like @prashantagarwal mentioned, if you have apps like Spectacle which have conflicting shortcuts (⌘⌥C) then you won't be able to open Postman Console with the shortcut.

**Comment by seba-i** [comment]
Me too - last 2 days when I open console (click on taskbar icon) it just sits there spinning. Just restarted Postman and now console shows "Something went wrong" message (no details).
Using latest Mac.
[EDIT] updated to v7.24 (from v7.19.1) and now working as expected.

**Comment by Shawanga** [comment]
Having the same issue today on macOS Monterey 12.5 intel.

**Comment by Shawanga** [comment]
Please update the download version on the site.  Newly installed from the side (https://www.postman.com/downloads/) had the same error on macOS Monterey 12.5. Needed to update it to fix it and works now.
