### ISSUE TITLE
Team workspace - Activity feed - To display the changes made in the activity feed rather than just showing it was edited

### ISSUE THREAD

**Issue by vaishrachan** [a85/POSTMan-Chrome-Extension#4819]
PostMan Pro - Trial version - If a team member makes a change to a test script in one of the shared collection, the others in the team can only see that the request in the collection was edited from the activity feed.

It would be great, if we could have a way to display which lines were edited/added or removed from the test script to better understand the changes made by different people in the team.

**Comment by SamvelRaja** [comment]
@vaishrachan  It is available already for the Postman pro/enterprise plan users
https://www.getpostman.com/docs/v6/postman/team_library/activity_feed_and_restoring_collections#breaking-the-event-down

**Comment by vaishrachan** [comment]
@SamvelRaja I did read that, but I still do not get the diff view. I subscribed to a trial version of PostMan Pro plan to experience the diff features of Pro. Is it because I am using the trial version, I dont see it?

**Comment by thecuriousdev** [comment]
@vaishrachan I was able to reproduce this issue. We made a fix for this and its available in the latest Postman Canary release.

**Comment by vaishrachan** [comment]
Thank you @thecuriousdev

**Comment by thecuriousdev** [comment]
@vaishrachan you can download our Canary build from https://www.getpostman.com/canary
