### ISSUE TITLE
Support client certificate authentication

### ISSUE THREAD

**Issue by jgongo** [a85/POSTMan-Chrome-Extension#482]
I recently had to connect to a web service using SSL and authentication using a client certificate. It seems that Postman doesn't support client certificate authentication (does it?). Could you please add support for this?

In the meantime I'm using SoapUI... please, please, please, rescue me from this hell!

**Comment by zhiyingjin** [comment]
I have a similar issue, but I am using Windows. Do you know how I can make it work? Thanks!

**Comment by sdnts** [comment]
@zhiyingjin I'm assuming you're using the Chrome app. I'd recommend switching to our native Windows app, it has support for client certificates, and this issue should not appear.

In case you're using the Chrome App, a quick Google search returns [this](https://blogs.technet.microsoft.com/sbs/2008/05/08/installing-a-self-signed-certificate-as-a-trusted-root-ca-in-windows-vista/), and should help.

**Comment by zhiyingjin** [comment]
@madebysid yeah, I tried snap-in it works for all other browsers including firefox and chrome, but not for Postman. Not sure what I am missing.

**Comment by zhiyingjin** [comment]
@madebysid yes, I am using Chrome App.

**Comment by coreyog** [comment]
I'm pretty sure this should be reopened.

I've added certs in every way I can imagine and postman simply doesn't work with them.

I've added PEM certs, DER certs, PFX files, and PEM cert/key in the same file and all I get is `400 The SSL certificate error` from Nginx. I know the certs are set up properly because Fiddler can point to the exact same files (DER+key or PEM+key, doesn't matter) and works just fine.

I'm using the dedicated app, Win10 x64, version 4.9.3 and have worked on just trying to get my Hello World of a request working for 3 hours and I'm convinced postman is incapable of client certificate authentication.

**Comment by a85** [comment]
@coreyog We are looking into this. We have a big release planned around authentication options.

**Comment by MALATHI02** [comment]
I'm using MAC, Postman 4.10, SSL is turned off , uploaded the self signed certs and private key under certificates. When I make https request, I get error "Could not get any response
There was an error connecting to https://127.0.0.1:8000/api/. Checked postman console displays "Error:
socket hang up" . What could be the issue. Appreciate your help!

**Comment by rstengel** [comment]
Are there any news regarding client certs? I have the native Windows app, Win10 x64, Postman v5.0.0 .
Tomcat: "Error trying to obtain a certificate from the client".

**Comment by axel-cerrilla** [comment]
I left this comment, just in case it could help someone
I installed postman app Win10 x64, version 5.0.2. 
**SSL is turned off**, I added individual files for client certificate and private key in PEM format and postman was able to do ssl client certificate authentication.

_These are headers/trailers for my key pair files_
-----BEGIN ENCRYPTED PRIVATE KEY-----
MI......
-----END ENCRYPTED PRIVATE KEY-----

-----BEGIN CERTIFICATE-----
MI....
-----END CERTIFICATE-----

_Postman's configuration_
![image](https://user-images.githubusercontent.com/25236333/27976467-3e8e49f8-632c-11e7-8eb9-3093fb0943af.png)

**Comment by usfalami** [comment]
I can't find Certificates Tab !!

**Comment by sowsan** [comment]
same here cant find the certificate tab, using 5.1.3 version win/x86-64 , chome 60.0.3112.90

**Comment by kustuntas** [comment]
I had the same issue. Fixed it by downloading the latest version of Postman.

**Comment by sdnts** [comment]
Guys, the certificates tab is available ONLY on the native apps, you can download them [here](https://getpostman.com/apps)

**Comment by neman** [comment]
How can I use desktop Postman when client certificate is on smart card? I can not point to a crt or pfx file, since private key will never leave smart card. What are the options for this?

**Comment by jrainey47** [comment]
Any plans for Smart Card Support?

**Comment by dk020130** [comment]
The "curl" command supports to set below 3 files:

> curl --tlsv1.2 --**cacert** root-CA.crt --**cert** certificate.pem.crt --**key** private.pem.key...

But in postman, we are only able to set "CRT" and "KEY" file without the "**cacert**".
How can I set cacert in postman?

**Comment by itsvikasgupta** [comment]
@dk020130 , did you figure out how to use cacert in postman? We have our own private CA and generate both server and client certs using our CA.
