### ISSUE TITLE
Wrong generated cURL request when request has multiple parameters with same name

### ISSUE THREAD

**Issue by ericdallo** [a85/POSTMan-Chrome-Extension#4825]
**Describe the bug**
The generated `curl` request is wrong when using multiple query parameters of same name.

**To Reproduce**
1. Make a request with multiple parameters but different values. 
Example: 
```curl
/list?codes=1&codes=2&codes=3`
```
2. Click on `Code`
3. Choose `cURL` 
4. The generated curl request is using the parameters separated by comma. Example: `/list?codes=1,2,3`

**Screenshots**
![screen shot 2018-07-13 at 4 36 40 pm](https://user-images.githubusercontent.com/7820865/42710619-116e5ad6-86bb-11e8-9bcc-9c7516481c59.png)
![screen shot 2018-07-13 at 4 37 18 pm](https://user-images.githubusercontent.com/7820865/42710626-15bb9f36-86bb-11e8-85d2-5ec8dda28570.png)

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version: 5.5.2 (5.5.2)
 - OS: macOS Sierra 10.12.4

**Comment by sujayvenaik** [comment]
Hey @ericdallo 
I could reproduce this issue.

Will keep this thread updated as soon as we fix this.

**Comment by abhijitkane** [comment]
@ericdallo 
Can you try this is Postman 7.2.1, with the 'Experimental Codegen Mode' flag enabled in Postman's global settings? We've introduced bug-fixes, support for two new languages (JS-Fetch and Powershell), and the ability to configure certain aspects of the generated snippet.
