### ISSUE TITLE
Support round-trip editing of file upload requests with variable path information

### ISSUE THREAD

**Issue by chefhoobajoob** [a85/POSTMan-Chrome-Extension#4826]
**Is your feature request related to a problem? Please describe.**
We have test cases that perform multiple file uploads where the path to the files is system dependent and can't be known at design time. The tests are maintained in a Postman collection, then exported and executed using newman. Even if the paths were known at design time, round-trip editing destroys path information in the collection. 

**Describe the solution you'd like**
We'd like a way to support POST requests where the file paths can come from Postman variables, and this path information does not get destroyed on collection import.

**Describe alternatives you've considered**
We looked at this workaround: http://blog.getpostman.com/2017/09/21/run-collections-with-file-uploads-using-newman/

...but it doesn't work for round-trip editing. Once you've edited the 'src' property for the file upload in an exported JSON file, you can't subsequently import that edited file, make changes, then export again, because the editor drops the 'src' property settings on the final export, forcing you to go back to all your upload requests and change them again.

**Comment by SamvelRaja** [comment]
We are tracking extensively on this in #4320

**Comment by chefhoobajoob** [comment]
@SamvelRaja: whoops - missed that. Thanks!
