### ISSUE TITLE
Cannot select post or get option in new tab

### ISSUE THREAD

**Issue by karthikraja34** [a85/POSTMan-Chrome-Extension#4827]
After clicking new tab in postman i cannot select **post** request from the dropdown box.The dropdown box is opening upwards and options (get,post) gets hidden under title bar.And at this point i have no way of selecting post .I tried scrolling over dropdown box but i doesn't get scrolled.

**Expected behavior**
The dropdown box should expand downwards not upwards.

**Screenshots**
![image](https://user-images.githubusercontent.com/20502926/42721613-5145464c-875b-11e8-8d95-89374de2509a.png)

**App information**
 - App Type [Native App]
 - Postman Version [v6.1.4]
 - OS: [Windows 10 version 1803 build 17134.165 ]

**Comment by sujayvenaik** [comment]
Hey @karthikraja34 
We have fixed this and released this in our canary app. You can get this here: https://www.getpostman.com/canary

This will soon be udpated on the postman app in the next build
