### ISSUE TITLE
Postman is always starting windowed.

### ISSUE THREAD

**Issue by IvoFritsch** [a85/POSTMan-Chrome-Extension#4828]
Don't know if this is a bug or just an lack of functionality.
In Windows 10, Postman always start as an window with almost the same width and height as the screen, even if I maximize, after restart it starts windowed again.

**To Reproduce**
1. Start Postman
2. Maximize window
3. Restart postman

**Comment by SamvelRaja** [comment]
@IvoFritsch  Thanks for bringing this to our notice, we shall look for the solution and get back to you on this thread on details.

**Comment by numaanashraf** [comment]
Fixed in Postman v7.0.8
