### ISSUE TITLE
how to import request json and replace dynamic variable at runtime before POST?

### ISSUE THREAD

**Issue by nileshy112** [a85/POSTMan-Chrome-Extension#4829]
Instead of copy and paste the JSON in body of the request, I would like to read it from JSON file (external source) and then replace all dynamic variables from JSON file.
 e.g. Below is my JSON file which I want to read it from my hard disk and replace all variables with valid values before sending it.
 {
 "firstName": "{{firstName}}",
 "lastName": "{{lastName}}",
 "age": {{age}},
 "correlationIds": [
 {
 "id": "{{id}}",
 "source": "{{source}}"
 },
 {
 "id": "{{id2}}",
 "source": "{{source2}}"
 }
 ]
 }

**Comment by nileshy112** [comment]
Does anybody have approach/suggestions??

**Comment by SamvelRaja** [comment]
At present we don't have the option of reading `variables` from a data file in the request builder.
But, our runner will help you in achieving the same. [Docs](https://www.getpostman.com/docs/v6/postman/collection_runs/working_with_data_files)

Feel free to re-open this issue, if you have specific use case other than this.
