### ISSUE TITLE
Have an option to not record repeated requests in Postman history

### ISSUE THREAD

**Issue by Hermholtz** [a85/POSTMan-Chrome-Extension#4830]
Hi! Quite often I'm sending multiple requests to an URL one after another, which means clicking "Send" several times. There are various reasons for that - sometimes just to see quickly an average response times (during development, long before proper perf testing takes place), sometimes to see errors popping up from time to time (before starting proper debugging). All these repeated requests get stored in history tab which clutters it. When you want to go back, you need to scroll a lot.

Having an equivalent of bash `HISTCONTROL=ERASEDUPS` behavior would be helpful, which means comparing request to previously stored ones and only moving exact same request to the top of history list, not storing another copy of it. It needs to match on URL first (to quickly filter out majority of queries), and if match is found, a deep comparison of headers and body to differentiate between variations of the same request.

Thanks.

**Comment by SamvelRaja** [comment]
Have you tried using our [collections](https://www.getpostman.com/docs/v6/postman/collections/creating_collections#saving-a-request-to-a-collection) feature?  Which helps you to organize requests.

[Runner](https://www.getpostman.com/docs/v6/postman/collection_runs/starting_a_collection_run) - Run the requests in the collection whenever you want to and assert using our [tests](https://www.getpostman.com/docs/v6/postman/scripts/test_scripts) and pre-request script features.

[Monitoring](https://www.getpostman.com/docs/v6/postman/monitors/intro_monitors) - Runs your collection with tests at a specified time and provide you the insights of response time and test results.

Additionally, you can check our command line collection runner [Newman](https://www.getpostman.com/docs/v6/postman/collection_runs/command_line_integration_with_newman)
Which you can integrate into your ci server to test your API.


Feel free to re-open the issue if you need a specific use case to solve apart from these 😄
