### ISSUE TITLE
Long Environment names not fully displayed in drop down menu.

### ISSUE THREAD

**Issue by Cazaimi** [a85/POSTMan-Chrome-Extension#4831]
**Long Environment names**
The Environment name is not fully displayed in the app, when choosing between environments in the drop down menu, if the environment name is longer than a certain number of characters. This makes choosing the correct environment difficult, as there can be environments that have names, which differ on the last 5 characters.  

The drop down menu: 

![image](https://user-images.githubusercontent.com/13660453/42756991-00da1fbc-891c-11e8-904c-96d0fe635c88.png)

GIF of the problem:

![longenvname](https://user-images.githubusercontent.com/13660453/42757023-17df9502-891c-11e8-84f9-fd7e731076c5.gif)

**Suggested Solutions**

- Display the full name of the environment when the mouse hovers over the environment in the drop down menu

- Dynamically resize the drop down menu according to the length required to display the longest environment name

**Alternatives**
One can surely use the Environment chooser pop-up box, but this is not ideal.

**Comment by sujayvenaik** [comment]
![kapture 2018-07-17 at 11 32 25](https://user-images.githubusercontent.com/11532114/42799355-310e45ca-89b5-11e8-9a4a-6c8bbfe1555f.gif)

@Cazaimi You can refer this.
