### ISSUE TITLE
Adding a search bar/index/text-search in the workspace chooser

### ISSUE THREAD

**Issue by Cazaimi** [a85/POSTMan-Chrome-Extension#4832]
**For teams who have >=30 workspaces**
For users in large teams who have a lot many workspaces, choosing the workspace that a user may want to work in becomes more difficult if the team has an >=30 workspaces. The current flow includes clicking on the workspace chooser, and choosing the workspace among those displayed in the drop down menu:

![image](https://user-images.githubusercontent.com/13660453/42757986-8ad55a26-891f-11e8-8c73-92ba82769152.png)

Scrolling through a lot many workspaces:

![manyworkspaces](https://user-images.githubusercontent.com/13660453/42758081-d9c14410-891f-11e8-852a-a305882c0a44.gif)

Over here, the names of the workspaces consist of just 2 letters, which is why it is easier to scroll through them and spot the workspace you'd like to work with. However, with more workspaces and longer names, it would be desirable to have a better way of choosing the workspace. 

**Suggestions**
Three possible solutions are:

1.  Add a search bar on top of the workspace names:

![screen shot 2018-07-16 at 5 41 29 pm](https://user-images.githubusercontent.com/13660453/42758452-344354d6-8921-11e8-8118-fc54803f3103.png)

2. The workspace names are already sorted alphabetically. However, increasing the size of the workspace chooser drop-down and adding the workspace names under Bolded and Emphasised Letter headings, as below:

![screen shot 2018-07-16 at 5 58 21 pm](https://user-images.githubusercontent.com/13660453/42759661-64bdc566-8925-11e8-8955-c37c2df8b997.png)

3. Adding a keyboard shortcut that opens a global search which works as a [selection-based search system](https://en.wikipedia.org/wiki/Selection-based_search).

**Note: The solutions below are sensible if the number of workspaces lie roughly between 30 and 100, as in the case of former, the problem is already described and in the case of the latter, the screen size may not be able to display all the workspaces cleanly, even after scroll capability.**

**Comment by sujayvenaik** [comment]
@Cazaimi 
Marking this as a feature request.

Will evaluate this internally and update this thread.

**Comment by sankalp0o** [comment]
The workspace switcher now allows filtering of workspaces very similar to what you suggested. Let us know if this does not satisfy your use cases @Cazaimi!
