### ISSUE TITLE
Trying to save/edit/make a global variable fails

### ISSUE THREAD

**Issue by Postman-Gabriel** [a85/POSTMan-Chrome-Extension#4835]
**Describe the bug**
Trying to click on the little eye in the top right corner to manage the global variables pushes the user to the environment tab. This tab will give a small error when trying to create a global variable, insisting the user has to choose an environment.

**To Reproduce**
1. Click on the gear for modifying environments
2. Click on globals tab
3. See error

**Expected behavior**
Expected to be able to save/modify/create globals from the tab

**Screenshots**

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version: 6.1.4
 - OS: Mac osX 10.12.6

**Comment by harryi3t** [comment]
@gabriel-bronfman-postman Can you share a screenshot of the error that you see?

**Comment by abhijitkane** [comment]
Closed due to inactivity
