### ISSUE TITLE
Formatting in the +New modal

### ISSUE THREAD

**Issue by loopDelicious** [a85/POSTMan-Chrome-Extension#4836]
**Describe the bug**
Formatting in the +New modal under Templates and API Network tabs

**To Reproduce**
1. Logos in API Network are squished
![screen shot 2018-07-16 at 3 17 27 pm](https://user-images.githubusercontent.com/17693714/42786581-a75b9af2-890b-11e8-8d94-daebe02ac00a.png)
1. Markdown is not rendering (or description includes markdown)
![screen shot 2018-07-16 at 3 17 38 pm](https://user-images.githubusercontent.com/17693714/42786557-96be2322-890b-11e8-9a79-5b958e78463d.png)

**App information (please complete the following information):**
 - Native app
 - Postman Version 6.1.4
 - OS X 16.5.0 / x64

**Comment by skywalker212** [comment]
+1
Facing the same issue
how can I contribute to this issue/is it possible?
![screenshot from 2018-07-18 22-12-54](https://user-images.githubusercontent.com/16351685/42895494-bc9f5368-8ad7-11e8-87de-4570e270c0d5.png)

**App information:**
 - App Type : Native App
 - Postman Version : 6.0.1
 - OS: Ubuntu 18.04 LTS

**Comment by numaanashraf** [comment]
Fixed in Postman v6.6
