### ISSUE TITLE
Two presses of CTRL+Z (or any other "cancel" shortcut) required for any cancel

### ISSUE THREAD

**Issue by cambierr** [a85/POSTMan-Chrome-Extension#4839]
**Describe the bug**
When we want to cancel an edit in postman like the request url for instance, two presses of `CTRL+Z` (the cancel shortcut on `azerty` keyboards. Not sure about `qwerty`) are required for any rollback.

**To Reproduce**
1. Create a new request
2. Write something in the url field
3. Try to remove the last character you added by pressing `CTRL+Z`
4. You have to press a second time to see the change

**Expected behavior**
The last change should be rolled back on first press of `CTRL+Z`

**Screenshots**
N/A

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version: 6.1.4
 - OS: Ubuntu 18.04 (tested on 17.10 and 17.04 too)

**Additional context**
N/A

**Comment by harryi3t** [comment]
Hey @cambierr,
I just tried this on the latest version of Postman (6.1.4) and it works as expected.
Please see my attached screenshot.

![undo-command-postman](https://user-images.githubusercontent.com/5207331/42806708-ad2d9e6e-89cc-11e8-8956-e9cd8457a1e4.gif)

Can you double check that version is indeed 6.1.4 and share a gif showing the bug?

**Comment by cambierr** [comment]
After completely removing Postman than re-installing the 6.1.4 version, it worked... not sure about what caused this but probably some update issue at some point.

Anyway, thank you for quick reply and sorry about that
