### ISSUE TITLE
Dragging a duplicate key inside environments modal is dragging 2 rows with it.

### ISSUE THREAD

**Issue by anudeepmedicharla** [a85/POSTMan-Chrome-Extension#4840]
**Describe the bug**
When I drag a duplicate key inside 'manage environments' modal, the interaction is such that I am dragging 2 rows (they key and the below row). 

**To Reproduce**
1. Create a duplication key
2. Try dragging the key.

**Expected behavior**
Only that key should be moving up and down.

**Comment by numaanashraf** [comment]
Fixed in Postman v7.1.0
