### ISSUE TITLE
POST request status 400 "name is required" but name is present in the request

### ISSUE THREAD

**Issue by mlovell82** [a85/POSTMan-Chrome-Extension#4841]
When I try to make a POST request I am getting a status 400 Bad Request with the message "name is required", but name is the 4th element of "payload".  What might be causing this error.  I have included a screen shot from postman.  

Here is the code for the post method:

app.post('/api/projects', (req, res) => {
    const { error } = validateCourse(req.body);
    if (error) return res.status(400).send(error.details[0].message);

    console.log(req.body.payload.name);
    const course = {
        payload: req.body.payload,
        timestamp: req.body.timestamp,
        type: req.body.type
    };
    
    projects.push(course);
    res.send(projects);
});

I am using:
Postman for Windows
Version 6.1.4
Windows 10

[screenshotpostman.docx](https://github.com/postmanlabs/postman-app-support/files/2201571/screenshotpostman.docx)

Thank you

**Comment by SamvelRaja** [comment]
@mlovell82 I can see that the data is sent to the server from my end.
You can also try sending the data to `http://postman-echo.com/post` endpoint. If the data is not received in the server end please feel free to re-open the issue. I am closing this as this is not the issue on Postman 😄 

> I would recommend you to log `req.body` before passing to `validateCourse` function.
