### ISSUE TITLE
Access cookies and other details when requests are sent using pm.sendRequest within scripts

### ISSUE THREAD

**Issue by LoZeno** [a85/POSTMan-Chrome-Extension#4842]
## App Details:

```
Postman for Windows
Version 6.1.4
win32 10.0.14393 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:
I've only noticed it recently, I don't know if it's been there forever
 2. Expected behaviour:
In a pre-request script, I would expect to be able to use pm.sendRequest and access all the parts of the response, including cookies, in order to (for example) retrieve anti forgery keys from cookies before using those values in a POST request.

Steps to reproduce the problem:

create a pre-request script which sends a GET request to a page that contains a cookie, and try to retrieve the cookie's value, e.g.:
```
pm.sendRequest({
            url: getRequestUrl,
            method: 'GET'
        }, function(error, response){
            if (error) {
                console.log(error);
            } else {
              
                var cookieToken = response.cookies.get("__cookieId");
                pm.environment.set("securityToken", cookieToken);   
            }
        });
```

**Comment by numaanashraf** [comment]
Thanks for reporting this @LoZeno

**Comment by rocifier** [comment]
I requested this feature in support ticket 16748 in the postman help center on May 05 2018. I don't know whether the feature was ever implemented, as support did not respond effectively to my description.  your description is better so I have created a follow-up support ticket and linked it to this issue.

**Comment by vdespa** [comment]
@a85  It is really a pity that such things do not get addressed or are not properly implemented and documented. It really limits what you can do with pre-request scripts and makes power users look into different solutions. 

The only workaround I could find is to extract the Set-Cookie header:

`const cookieHeader = response.headers.get('Set-Cookie');`

but after this, you kind of have to do the parsing on your own.

Also, make sure your request sending the cookies does not include any redirects. If it does, you need to disable redirects in Postman. It seems that you cannot configure sendRequest to disable redirects.

**Comment by SamD** [comment]
> @a85 It is really a pity that such things do not get addressed or are not properly implemented and documented. It really limits what you can do with pre-request scripts and makes power users look into different solutions.

I just started with the scripting capabilities and I was stumped by this, I spent half a day trying different approaches only to discover that the cookies are oddly available in the **tests** but not the **pre-request**. I'm not certain the reasoning behind this, I had thought at first it might have something to do with pm.sendRequest but the exact same script I would run in pre that didn't work would work fine in tests. The problem being that I need to run it before not after the main request

**Comment by rocifier** [comment]
Agreed. I decided not to use postman for my solution in the end, and coded a small node.js script to do my automation instead. That way I had full control over the requests and passing the cookies around, including passing them through a 302 redirect like web browsers do (and postman does not).

**Comment by pomeh** [comment]
+1

I also need this feature !

For information, I just created a ticket related to `pm.sendRequest` and cookie storage (#5753).

**Comment by codenirvana** [comment]
One thing to note here is that during pre-request script, it is not yet fully known what exactly the URL of the request is going to be. Based on that there are issues in regards to attaching cookies to requests.

- Cookies, when attached to a request, is closer to the request domain and path. As such, during pre-request script, it is not possible to filter the relevant cookies and colocate them with the request.
- The alternate solution to this is making the entire cookie store available within scripts. That, again, would require APIs to extract relevant cookies and would also transmit huge irrelevant-for-most-use-cases data in and out of scripting environment.

Until there is a new idea, the direct access of "set-cookie" header seems to be a viable workaround.

> The idea that we are presently drafting is opening up something like `pm.cookies.get` within all scripts. It would be an asynchronous function that makes a round-trip to the out-of-sandbox cookie data store and returns data for a particular reference domain.
>
> PS: We also need to discuss the security implications of the same.

**Comment by rocifier** [comment]
> One thing to note here is that during pre-request script, it is not yet fully known what exactly the URL of the request is going to be. Based on that there are issues in regards to attaching cookies to requests.
> 
> * Cookies, when attached to a request, is closer to the request domain and path. As such, during pre-request script, it is not possible to filter the relevant cookies and colocate them with the request.
> * The alternate solution to this is making the entire cookie store available within scripts. That, again, would require APIs to extract relevant cookies and would also transmit huge irrelevant-for-most-use-cases data in and out of scripting environment.
> 
> Until there is a new idea, the direct access of "set-cookie" header seems to be a viable workaround.

I'm worried you may not be properly understanding the most common use-case for this. I tried to restate it below:
1) set up a regular api request at Uri A
2) in the pre-request script for this request, do a side request to Uri B in order to get a new security token with the intent of using that token in the subsequent request to Uri A
3) attach the result of the token request, in this case a cookie, to the Uri A request
4) pre-request script is complete and Uri A can now make its request using the cookie with the token in it

**Comment by shamasis** [comment]
@rocifier - yep, you are right. we misinterpreted the issue because there is another actual issue with similar intent. I've changed the issue title for better tracking. Let me know if this sounds accurate.

**Comment by codenirvana** [comment]
We've added support for this in the latest Postman App (v7.1.0) 🎉

To access `pm.sendRequest` cookies:
```javascript
pm.sendRequest("https://postman-echo.com/get", function (err, response, {cookies}) {
    console.log(cookies.all());
    console.log(cookies.one('token'));
});
```

The third argument in `pm.sendRequest` callback is an object which currently has a single property `cookies` of type [CookieList](https://www.postmanlabs.com/postman-collection/CookieList.html). We are planning to add more low-level request information in this object soon.

**Comment by caot** [comment]
The only solution worked!

> 
> 
> We've added support for this in the latest Postman App (v7.1.0) tada
> 
> To access `pm.sendRequest` cookies:
> 
> ```js
> pm.sendRequest("https://postman-echo.com/get", function (err, response, {cookies}) {
>     console.log(cookies.all());
>     console.log(cookies.one('token'));
> });
> ```
> 
> The third argument in `pm.sendRequest` callback is an object which currently has a single property `cookies` of type [CookieList](https://www.postmanlabs.com/postman-collection/CookieList.html). We are planning to add more low-level request information in this object soon.

**Comment by vschoener** [comment]
I needed this! Thank you! I was trying to parse Set-Cookie with the PostmanCookie object... Is this documented somewhere? Didn't find any information

**Comment by Warlock-9000** [comment]
> The only solution worked!
> 
> > We've added support for this in the latest Postman App (v7.1.0) tada
> > To access `pm.sendRequest` cookies:
> > ```js
> > pm.sendRequest("https://postman-echo.com/get", function (err, response, {cookies}) {
> >     console.log(cookies.all());
> >     console.log(cookies.one('token'));
> > });
> > ```
> > 
> > 
> > The third argument in `pm.sendRequest` callback is an object which currently has a single property `cookies` of type [CookieList](https://www.postmanlabs.com/postman-collection/CookieList.html). We are planning to add more low-level request information in this object soon.

Please tell me how you set cookies in pre-request.

**Comment by vdespa** [comment]
@Warlock-9000 Cookies are just a header, so you can set a header with the cookies you wish to send.

**Comment by ntbosscher** [comment]
This doesn't seem to be working in the latest Postman App

Version 10.19.5
UI Version: 10.19.5-ui-231016-0826
Desktop Platform Version: 10.19.0 (10.19.0)

> There was an error in evaluating the Pre-request Script:Error: Cannot destructure property 'cookies' of 'undefined' as it is undefined.

```
pm.sendRequest({
    url: '...',
    method: 'GET'
}, function(error, response, {cookies}) {
    if (!error) {
        pm.environment.set('xsrf-cookie', cookies.get('XSRF-TOKEN'));
    }
});
```

This happens when there's an issue with the request (error is set). Perhaps the usage examples should follow this format:

```
pm.sendRequest({
    url: '...',
    method: 'GET'
}, function(error, response, extra) {
    if (!error && extra) {
        const {cookies} = extra;
        pm.environment.set('xsrf-cookie', cookies.get('XSRF-TOKEN'));
    }
});
```
