### ISSUE TITLE
Search and replace does not work properly

### ISSUE THREAD

**Issue by vdespa** [a85/POSTMan-Chrome-Extension#4843]
**Describe the bug**
The soon to be introduced functionality does not seem to work as expected.

**To Reproduce**
0. You need a collection that has some tests
1. Open the search function, select the collection
2. Search for jsonData
3. Select all the entries inside a request
4. Replace with response
5. Nothing happens (the color of the tab turns orange, but the code does not get replaced).

**Expected behavior**
Code should be updated, but it does not get updated.

**Screenshots**
<img width="829" alt="screen shot 2018-07-18 at 07 19 44" src="https://user-images.githubusercontent.com/1197635/42861396-19cca036-8a5b-11e8-87d6-fa4072416835.png">
<img width="595" alt="screen shot 2018-07-18 at 07 20 07" src="https://user-images.githubusercontent.com/1197635/42861397-19ea5f18-8a5b-11e8-8dae-6d2f104cda6e.png">

**App information (please complete the following information):**
 - Native App
 - Postman v6.2.0-canary04
 - OS: macOS

**Additional context**

**Comment by vkaegis** [comment]
@vdespa Thanks for the feedback! Looks like our Find and Replace feature isn't playing pretty with the way we handle dirty tabs. We're working on a bunch of improvements around tabs and how they convey state, and we'll be sure to fix this behavior in the coming versions. No ETA on this just yet, but stay tuned!

**Comment by a85** [comment]
@vkaegis This should just replace the text right? Why is this an issue with tabs?

**Comment by vkaegis** [comment]
@a85 What Replace does not yet do is update instances of the request that were already open as tabs. So these tabs show as dirty, since the underlying request has changed. We do not yet have a way to update the request open in a tab if (for example) it has not been edited, or is in a busy state.

**Comment by a85** [comment]
I think that's a default expectation. We should keep this feature in Canary until then. @vdespa Thank you for reporting.

**Comment by a85** [comment]
This should be fixed in the latest version of the app!
