### ISSUE TITLE
c# winform call postman api but value is null

### ISSUE THREAD

**Issue by Pailin-Kotchakorn** [a85/POSTMan-Chrome-Extension#4844]
I call api for send text file to web page for get some link pdf but when i execute my response get null. When response null it make this line (JObject oKeepResponeExecute = JObject.Parse(response.Content);) to be error. I don't understand why response is null?

My code

public void CallAPI(string strTaxID, string strBranchID, string strAPIKey, string strUserCode, string strAccessKey, string strServiceCode, string strPathTxtContent)
{
            FileInfo file = new FileInfo(strPathTxtContent);

            try
            {
                var client = new RestClient("My URL"); //Secrete
                var request = new RestRequest(Method.POST);
                request.AddHeader("Postman-Token", "8fe5e73a-cdea-4647-82b7-9c33a2762fd6");
                request.AddHeader("Cache-Control", "no-cache");
                request.AddHeader("Content-Type", "application/x-www-form-urlencoded");
                request.AddHeader("content-type", "multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW");
                request.AddParameter("multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW", "------WebKitFormBoundary7MA4YWxkTrZu0gW\r\nContent-Disposition: form-data; name=\"SellerTaxId\"\r\n\r\n" + strTaxID + "\r\n------WebKitFormBoundary7MA4YWxkTrZu0gW\r\nContent-Disposition: form-data; name=\"SellerBranchId\"\r\n\r\n" + strBranchID + "\r\n------WebKitFormBoundary7MA4YWxkTrZu0gW\r\nContent-Disposition: form-data; name=\"APIKey\"\r\n\r\n" + strAPIKey + "\r\n------WebKitFormBoundary7MA4YWxkTrZu0gW\r\nContent-Disposition: form-data; name=\"UserCode\"\r\n\r\n" + strUserCode + "\r\n------WebKitFormBoundary7MA4YWxkTrZu0gW\r\nContent-Disposition: form-data; name=\"AccessKey\"\r\n\r\n" + strAccessKey + "\r\n------WebKitFormBoundary7MA4YWxkTrZu0gW\r\nContent-Disposition: form-data; name=\"ServiceCode\"\r\n\r\n" + strServiceCode + "\r\n------WebKitFormBoundary7MA4YWxkTrZu0gW\r\nContent-Disposition: form-data; name=\"TextContent\"; filename=\"" + file + "\"\r\nContent-Type: text/plain\r\n\r\n\r\n------WebKitFormBoundary7MA4YWxkTrZu0gW--", ParameterType.RequestBody);
                request.AddFile("file", strPathTxtContent);
                IRestResponse response = client.Execute(request);

                JObject oKeepResponeExecute = JObject.Parse(response.Content);
                string strMessageExecute = oKeepResponeExecute["status"].ToString();
                MessageBox.Show(strMessageExecute);
            }
            catch(Exception ex)
            {
                MessageBox.Show(ex.ToString());
            }
        }

picture 1 Respone Value
![value](https://user-images.githubusercontent.com/41358788/42864812-e138b430-8a91-11e8-8064-bd3e0e89ddcd.PNG)
 picture 2 Error
![error](https://user-images.githubusercontent.com/41358788/42864822-e9807dda-8a91-11e8-90f4-24448e1c2dea.PNG)

**Comment by numaanashraf** [comment]
@Pailin-Kotchakorn I'm afraid I don't understand the issue you are facing. Are you sending a request with Postman and not receiving the expected request at the server end?

**Comment by abhijitkane** [comment]
Closed due to inactivity
