### ISSUE TITLE
Calling Request with in Collection Using RequestName Reference.

### ISSUE THREAD

**Issue by AnkitKabra20** [a85/POSTMan-Chrome-Extension#4845]
Is there a way through which I could call an existing request (Already created request within a collection/folders) into a new request as a pre-request or post request. Please provide the suitable recommendation to avoid maintenance.

Current Approach(workaround), I am copying the Request#1 which I need to execute first and place it before the next request Request#2. In this case, if Request#1 changes I need to make the changes in all the places in a collection where I copied Request#1.

Another Approach is copying the Request#1 parameter from the source Request#1 and place it in the Request#2 (pre-request Script using pm.sendrequest ) fall back of this approach is similar to earlier approach with an addition. I cannot call more than 1 Requests in pre-request test script If I am making the call for more that one then I cannot control the order of operations.

**Comment by ascendantofrain** [comment]
I second this request 100%.  My application is a complex authentication protocol and cookie storage so being able to call a saved "Authentication" request in a pre-request script would prove extremely valuable.

**Comment by j-ulrich** [comment]
A simple way to achieve this would probably be to give access to the current collection (or even all collections by something like `pm.getCollection('Collection 1')`).
Then one can dig out the request using the [collection API](https://www.postmanlabs.com/postman-collection/Collection.html).

**Comment by pomeh** [comment]
This issue looks similar to #882 and #4193. Maybe you'll find some solutions in those threads (and maybe this one could be closed ?).

**Comment by tatemz** [comment]
This feature request and others like it have been requested since 2015. I think it's time to move it out of the `Later` column 😉

**Comment by Moshikol** [comment]
+1

**Comment by IanKemp** [comment]
> This feature request and others like it have been requested since 2015. I think it's time to move it out of the `Later` column 😉

`Later` = "never going to be worked on" apparently.

**Comment by arlemi** [comment]
Hey 👋 I've gathered all feedback from here and other issues into a single one, we will keep the discussion going there, closing this issue. 

➡️  https://github.com/postmanlabs/postman-app-support/issues/4193#issuecomment-626699439
