### ISSUE TITLE
only let the user log errors to console

### ISSUE THREAD

**Issue by stephanos** [a85/POSTMan-Chrome-Extension#4846]
Please read through the [guidelines](https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues) before creating a new issue.

**Is your feature request related to a problem? Please describe.**

Yes. We want to use Postman Monitors to run a collection's tests for verifying whether our API works end-to-end. We added a somewhat sophisticated retry mechanism to retry if things don't work the first time.

BUT when there is a connection issue like a timeout, Postman logs that error to the console. Postman Monitors picks that up and declares the entire request as failed (see screenshot), even though all tests  _eventually_ passed ("0 failed tests").

Because of this, we can't send notifications to Slack since there would be way too many false-positives. Same with other integrations.

**Describe the solution you'd like**

I'd like Postman to _not_ log any errors itself. This way the user is in full control of whether something is an _actual_ error or just a transient one.

**Describe alternatives you've considered**

An alternative would be for Postman Monitors to _not_ consider a test run failed if there if any error has been logged.

**Additional context**

![pasted_image_2018-07-18__11_54_am](https://user-images.githubusercontent.com/159852/42893302-f39dde12-8a81-11e8-825a-d2384391fec8.png)

By the way, a workaround - which I think works - is to overwrite `console.error` with `console.warn`.

**Comment by abhijitkane** [comment]
@codenirvana

**Comment by godfrzero** [comment]
Invoking `console.error` no longer incorrectly marks the run as a failure.
