### ISSUE TITLE
Setting to show request description by default

### ISSUE THREAD

**Issue by MarkLeMerise** [a85/POSTMan-Chrome-Extension#4847]
**Is your feature request related to a problem? Please describe.**
The problem is primarily a UX and team communication thing. I try to write detailed API descriptions, but since they are collapsed by default, our team usually forgets (even if I tell them) and this might cause a gap in knowledge that would be filled by reading the description.

**Describe the solution you'd like**
When I open the preferences, there is an option to always show a request description. I think this could be disabled by default to maintain the current behavior.

**Describe alternatives you've considered**
#1351 describes a workaround that remembers if you opened the description but I do not see this working in Postman 6.1.4.

**Additional context**
![GIF of the #1351 issue still happening](https://user-images.githubusercontent.com/573634/42898106-3320c794-8a90-11e8-8762-9ee478125102.gif)

**Comment by vkaegis** [comment]
@MarkLeMerise Thanks for writing in! Amusingly, we've faced this problem ourselves. 😅 We're working on a bunch of improvements on tabs and how the different sections are arranged within it. This makes a lot of sense, and we'll be sure to include an option to do this soon. No ETA just yet, but stay tuned for updates!

**Comment by MarkLeMerise** [comment]
That sounds good. Thanks for putting out a quality product!

**Comment by coreyhickson** [comment]
Hey! Just wondering if this was worked on :)? My team would love to use a feature like this as we often forget about descriptions

**Comment by DannyDainton** [comment]
Since this issue was reported, the UI of the platform has changed. The entity(requests/folders/collections/etc) descriptions are now located on the right sidebar and not under the request name.

<img width="2631" alt="image" src="https://user-images.githubusercontent.com/17089546/177316284-62c20a85-8fd6-4f47-b05d-92b5f7b75bf9.png">
