### ISSUE TITLE
JSON formatter for raw JSON requests

### ISSUE THREAD

**Issue by mtpultz** [a85/POSTMan-Chrome-Extension#4848]
**Describe the solution you'd like**
It would be great if the raw JSON body automatically (or via button) formatted the JSON so changes could be made quickly to test endpoints that take large JSON objects

**Describe alternatives you've considered**
JSON stringify request data in console, copy it to VSCode, change file type to JSON, format JSON, and copy-paste into Postman

**Comment by bdavidhicks** [comment]
@mtpultz I have had a similar issue and some googling led me to #2378 which says you can use Ctrl+B to format the JSON body. I think that there may be a button added to do this task as well.

**Comment by mtpultz** [comment]
Hi @bdavidhicks in my raw JSON request `Ctrl + B` doesn't work

**Comment by vkaegis** [comment]
@mtpultz This is a confirmed regression in v6.3.0. We are working on rolling out a fix for this in the next release.

**Comment by kamalaknn** [comment]
We've fixed this in the latest version of Postman. Please update to the latest app and let us know if the issue still exists.

**Comment by mtpultz** [comment]
Works great!  Just copied in the raw JSON and hit Beautify.
