### ISSUE TITLE
Mouse scroll zones drawing incorrectly w/ HiDPI scaling

### ISSUE THREAD

**Issue by Kirlac** [a85/POSTMan-Chrome-Extension#4849]
**Describe the bug**
When the Win10 postman app is open on a secondary display the mouse zones are not in the correct place. This looks like an issue with HiDPI scaling - ~~scrolling works as expected on the primary monitor (3840x2160, 250% scale), but when the window is moved to the secondary display (1280x1024, 100% scale)~~ the zones render smaller and off position
EDIT: It is also doing this on the primary display, the zones are just in a different position

**To Reproduce**
1. Open the postman application on a monitor with dpi/scaling
2. Attempt to scroll any of the panes using the mouse wheel - the zone the mouse needs to be in for the scroll to register is off size/position

**Expected behavior**
Scroll zones should match the pane they are scrolling ~~(as is the functionality on the primary display)~~
EDIT: Primary display is also off - added an extra screenshot to show

**Screenshots**
The solid boxes are the zones which allow scrolling, the outlines are the panes they scroll (color coded)

From primary display (3840x2160, 250% scale):
![postman-scroll-zones1](https://user-images.githubusercontent.com/5118726/42923418-b4f7f354-8b68-11e8-8b45-7de8037fdc76.png)
From secondary display (1280x1024, 100% scale):
![postman-scroll-zones](https://user-images.githubusercontent.com/5118726/42916341-154548a4-8b48-11e8-8d1c-be31dfc8a071.png)

**App information:**
Postman for Windows
Version 6.1.4
win32 10.0.17134 / x64

**Additional context**
Windows 10 Pro x64 - 1803 (OS Build 17134.165)
Dell XPS 15 9550 - 4K Touch screen display w/ 2 secondary 1280x1024 monitors attached in "Extend" mode

**Comment by numaanashraf** [comment]
Thanks for reporting this @Kirlac.

**Comment by timhay68** [comment]
I can confirm this issue is present in Postman for Windows v6.2.3, win32 10.0.17134 / x64

Lenovo Yoga 720 with two secondary monitors in extend mode.
Windows 10 Pro x64 - 1803 (OS Build 17134.165)
Lenovo screen set to primary:
   Scale and Layout = 300% (Recommended)
   Resolution = 3840x2160 (Recommended)
   Orientation = landscape
Secondary 1 and Secondary 2:
   Scale and Layout = 100% (Recommended)
   Resolution = 1920x1080 (Recommended)
   Orientation = landscape

Many thanks to Kirlac for the report with screenshots!

**Comment by ghost** [comment]
I can confirm it still happening today in Postman for Windows Version 6.6.1 win32 10.0.17134 / x64
Dell XPS 15
Windows 10 Pro x64 - 1803 (OS Build 17134.472) 4K Touch screen display w/ 2 secondary 1280x1024 monitors attached in "Extend" mode
**I use only the secondary monitors.

**Comment by mrperson2015** [comment]
I can confirm this as well. The main monitor on the laptop seems to function as you would expect. When moved to an external monitor I see the same wonkyness that the original issue outlines.

Postman: You are up to date! Postman v6.7.3 is the latest version.
Surface Book 2
Windows 10 x64 Enterprise 1803 (OS build 17134.523) 
laptop screen 3000 x 2000 touch screen @ 200% scale
(2) 1920 x 1080 monitors @ 100% scale
**I use all monitors

**Comment by DavidLindsey0118** [comment]
Encountering the same problem in 6.7.4, Windows 64-bit. Scrolling of my results body window only works when the mouse is in the indicated green hotboxes.

I am on an HP Omen X laptop using Windows 10 Pro.  Graphics card is a NVIDIA GeForce GTX 1080.  Native display resolution is 3840x2160 (4k) but secondary monitor resolution is 1920x1080 (1080p)

**Comment by DumbThingsiMade** [comment]
I am having the same issue with v7.0.6, which is currently the latest version. 

HP EliteBook 840 G1, WIndows 10 Pro 64 Bit, i5 4300U CPU 1,90GHz (4 CPUs) ~2.5GHz 8GB RAM

Here's my dxdiag file attached.



[DxDiag.txt](https://github.com/postmanlabs/postman-app-support/files/2992491/DxDiag.txt)

**Comment by rodrigotolledo** [comment]
I'm also facing scrolling issues when using Postman in an external monitor.

Tried on two different external monitors with different resolutions (and scrolling doesn't work on both):
- BENQ Monitor - Resolution: 2560 x 1440
- BENQ Monitor - Resolution: 1920 x 1080

Scrolling works fine on my DELL Laptop (15"):
- Resolution: 3840 x 2160

Postman Version 7.0.9
win32 10.0.17763 / x64

**Comment by Blond11516** [comment]
I'm also facing similar issues with Postman 7.1.0 on Windows 10 Pro.

Scrolling boxes are out of place, but the problem only hapens when I drag the app window from one screen to the other. Basically, whichever screen the app was opened on works fine, but as soon as I drag the window to the other screen I start having problems.

I've attached my DxDiag file.

[DxDiag.txt](https://github.com/postmanlabs/postman-app-support/files/3187802/DxDiag.txt)

**Comment by twothe** [comment]
I am using Postman 7.1.1 on Windows 10, external Monitor (which is not scaled) and I have the same issue. However my main monitor is scaled, so it looks to me like Postman is getting the scaling information from the wrong monitor.

**Comment by leolozes** [comment]
Same here with a Dell XPS 13 4K display and with a 1080p Dell Monitor attached to it. 
Latest build of Windows 10, Postman 7.2.2. The scroll works if I do it in a corner (original size) as described on the issue.

**Comment by harryi3t** [comment]
Hi, 

We've pushed an update on our early access canary. It has updated the underlying platform (Electron v7) on which Postman is built. Do try it out and let us know

You can get the canary app from https://www.getpostman.com/downloads/canary

**Comment by twitharshil** [comment]
Hi Everyone,
Could you try out our early access Canary build? https://www.postman.com/downloads/canary/. We are testing some improvements that should address this particular issue. You can install and use the Canary build side by side with the stable app.

**Comment by numaanashraf** [comment]
This issue should be addressed in v7.26.0 and above.
