### ISSUE TITLE
Unable to use editor after sending request

### ISSUE THREAD

**Issue by chrisdeso** [a85/POSTMan-Chrome-Extension#4850]
**Describe the bug**
The editor – `Tests / Pre-Request / Body` – is "blocked" after sending a request.

**To Reproduce**
1. Send a request using the keyboard shortcut `Ctrl + Enter`
2. Attempt to edit the Body / Tests / Pre-Request sections

**Expected behavior**
The text fields should be editable.

**App information (please complete the following information):**
 - App Type: Native
 - Postman Version: `6.1.4`
 - OS: Windows 10

**Comment by prashantagarwal** [comment]
@chrisdeso Can you add a screen recording for this. I am unable to reproduce this with the given steps.

**Comment by jperucello** [comment]
@prashantagarwal , I was able to do the video:
https://drive.google.com/file/d/1wV5b3_lt45ZMU8sIFrwa5JuUdoIizFC1/view?usp=sharing

So I send multiple requests that I trigger through Ctrl+Enter, and when I have the tab already opened, after the request is sent, I click and try to type on the box but the focus is kept on the response block.
After I change tabs then my focus change and I can again type inside tests tab.

**Comment by prashantagarwal** [comment]
@jperucello It shows restricted access.

**Comment by jperucello** [comment]
@prashantagarwal sorry, updated.

**Comment by chrisdeso** [comment]
@prashantagarwal – Here you go :)

- https://drive.google.com/file/d/1bGQfsr6aC3EP7l4h4hwiDn5LGrp5wA_X/view?usp=sharing

**Comment by sujayvenaik** [comment]
Hey @jperucello @chrisdeso 

Can you update to the latest app v6.4.2 and check once.
I am unable to reproduce this.

**Comment by chrisdeso** [comment]
Closing as we haven't seen much action here :).
