### ISSUE TITLE
Generated cURL behaves differently to Postman client

### ISSUE THREAD

**Issue by danielvaughan** [a85/POSTMan-Chrome-Extension#4851]
**Describe the bug**
POST request is successful in Postman client but fails when using the generated cURL is run as header is empty.

**To Reproduce**
I have a POST request in Postman that produces the following cURL:
```
curl -X POST \
  https://2nmjnvya3d.execute-api.us-east-1.amazonaws.com/dev/validate \
  -H 'Cache-Control: no-cache' \
  -H 'Content-Type: application/json' \
  -H 'Postman-Token: 5ee62e47-c7b4-4e64-9f21-422b29cbeb6f' \
  -H 'describedBy: https://schema.humancellatlas.org/type/biomaterial/5.1.0/specimen_from_organism' \
  -d '{}'
```
When I run in Postman I get back the expected result:
```
{
    "valid": false,
    "message": "The document is not valid",
    "errors": [
        "describedBy is required",
        "schema_type is required",
        "biomaterial_core is required",
        "organ is required"
    ]
}
```
However, when I run the cURL at the command line I get back:
```
{"message":"Schema URL cannot be empty"}
```
This is because the describedBy header is seen as empty when it reaches the server when using cURL. When using Postman the value is there

**Expected behavior**
I would expect the same behaviour when using cURL on the command line as when executing in Postman

**Screenshots**

**App information (please complete the following information):**
 - App Type Native App
 - Postman Version 6.1.4
 - OS: macOS High Sierra 10.13.5

**Comment by danielvaughan** [comment]
This may be an AWS API Gateway rather than Postman. If a request comes from postman the case of the header name is preserved. If the generated cURL is used the header name becomes lower case. However ,the behaviour is different between a request from the app and a request for the generated cURL.

**Comment by a85** [comment]
The curl export has been one of our biggest pain points. Ironic considering that Postman was built in some way to avoid using curl. :(

**Comment by danielvaughan** [comment]
Could it be that cURL uses http/2 and postman doesn't? I read somewhere that HTTP/2 converts headers to lower case

**Comment by abhijitkane** [comment]
@danielvaughan Sorry for the delay here, but that might be it. We've confirmed neither curl nor Postman change the headers' case while making HTTP1.1 requests. Can you try adding a `--http1.1` option to your curl command and check if that works?

**Comment by shreys7** [comment]
@danielvaughan  
curl documentation states that
-v, --verbose
              Makes  curl  verbose  during the operation. Useful for debugging and seeing what's going on "under the hood". A line starting with '>' means "header data" sent by curl, '<' means "header data" received by curl that is hidden in normal cases, and a line starting with '*' means additional info provided by curl.

I used this flag and it was seen that the header case was preserved in HTTP/1.1 as well as HTTP/2

**Comment by Leigh-M** [comment]
Hi @abhijitkane adding --http1.1 to my cURL request generated by Postman fixed the issue for me
