### ISSUE TITLE
highlight tabs 

### ISSUE THREAD

**Issue by VLbrezee** [a85/POSTMan-Chrome-Extension#4853]
**Is your feature request related to a problem? Please describe.**
When I open a lot of tabs then active tab looking not expressive, so I have the difficulty to find it by eyes.

**Describe the solution you'd like**
My proposition is next - make active tab more bright, or orange point for active tab will change  on point with green color

**Additional context**
![2018-07-19 17-43-56](https://user-images.githubusercontent.com/17157463/42950028-ce0b2498-8b7b-11e8-8df7-80aadad621f5.png)

**Comment by numaanashraf** [comment]
Thanks for the feedback @VLbrezee. @vkaegis, what are your thoughts on this?

**Comment by vkaegis** [comment]
@VLbrezee Thanks for writing in! This seems like a pretty useful accessibility improvement. Just curious, would something like this help in differentiating the active tab?

![screenshot 2018-07-20 16 38 02](https://user-images.githubusercontent.com/6038010/42999473-86c8fa40-8c3b-11e8-909a-976dbee47122.png)

**Comment by VLbrezee** [comment]
@vkaegis Yes  you understood me absolutely correct. At Last  time I have worked a lot of time with Postman, it's great application, and I have a lot of opened tab, so I had problem to find quickly active tab.
So I think If developers highlight active tab more expressiveness, or make green color for point in tab , it would be great improvements ! :)

**Comment by vkaegis** [comment]
@VLbrezee Yep, definitely makes sense. :) We'll be pushing out a fix for this in the coming versions. Stay tuned!

**Comment by prashantagarwal** [comment]
@VLbrezee We added this in our latest Postman app release.
