### ISSUE TITLE
Capture and log inbound Mock Server requests, display them in Postman Console

### ISSUE THREAD

**Issue by krigi** [a85/POSTMan-Chrome-Extension#4854]
I would like to be able to see logs for every call to our Mock Servers. It would be useful to be able to see the raw inbound requests in the Postman Console... headers, body, etc.

Context: my developers often send bad requests to our mock servers, but I don't have visibility to their requests. Thus I am unable to troubleshoot where they went wrong (e.g. missed bracket, improper naming of keys, etc).

**Comment by SamvelRaja** [comment]
Thanks for raising over here. We are marking this as a feature and will update the thread on how we intend to solve this.

**Comment by sankalp0o** [comment]
Thanks for the suggestions @krigi. This is not in our immediate roadmap but this sounds like something that'll be useful for a lot of people using mock servers. Probably something to think about when we're building reporting for mock servers @a85 .

**Comment by assislucas** [comment]
Hi Postman team, did this feature request ever get picked up?

**Comment by digaomatias** [comment]
Just adding to this. It would be helpful to actually run our integration testings, because then we could match mock-server data in our asserts. 
Lets say we are testing ApiA, and it hits ApiB and ApiC. We don't care how ApiB and ApiC works. We could create mock-server for ApiB and ApiC and do our tests against ApiA, which would hit the mock-servers. Then, after the test against ApiA is ran, it calls the mock-servers to check whether the calls happened with the expected parameters. Asserting that would pass or fail the test accordingly.

**Comment by keyuls** [comment]
Please provide the functionality to access the request data sent to the mock server. so it is possible to implement scenario like this :

https://community.getpostman.com/t/saving-request-data-sent-to-mock-server/9577

**Comment by fippu82** [comment]
Can't believe postman can't do this. I would see it as most important feature of a mock server.

**Comment by vvs11** [comment]
Hi everyone, We have released Mock Call Logs which is now up on Dashboard and can be navigated through Postman v7.20+. You can now view all the requests that are made to your Mock Server. 
You have to navigate to Mock server listing in the app or dashboard and click on the mock server name. You'll see the logs.  Below is a screenshot for Mock Call Logs:

![image](https://user-images.githubusercontent.com/4140290/77855248-cba53f80-720c-11ea-8448-92f0469cc7c9.png)

Here are some links that will help you in understanding the feature.

https://learning.postman.com/docs/postman/mock-servers/setting-up-mock/#viewing-mock-calls
https://blog.postman.com/2020/03/11/introducing-postman-mock-call-logs/

Please check it out and let us know your feedback.
