### ISSUE TITLE
Postman Code Snippet Issue - JSON body to Python Payload

### ISSUE THREAD

**Issue by Msaini323** [a85/POSTMan-Chrome-Extension#4855]
**Describe the bug**
This is an issue with the Code Snippet Creator, when doing a JSON Body, the Python Payload snippet does not format correctly.

**To Reproduce**
Create any method that requires a JSON Body. Then check out how the code snippet for Python looks and you will see the issue.

Json Body:
![image](https://user-images.githubusercontent.com/27297658/42958503-4d8ecb74-8b4b-11e8-8615-c665b73b0c4f.png)

**Expected behavior**
The Python payload should be translated properly from the JSON.

**Screenshots**
Screen shots shown above of the issue.

**App information (please complete the following information):**
 - App Type [Native App]
 - Postman Version [e.g. 6.1.4]
 - OS: [Windows 10 PRO]

**Comment by abhijitkane** [comment]
@Msaini323 Can you elaborate on this? The Python code I see for both `http.client` and `Requests` is
`payload = "{\n\t\"k1\": \"v1\",\n\t\"k2\": \"v2\"\n}"`

Are you talking about the `json` parameter (as illustrated in https://stackoverflow.com/questions/9733638/post-json-using-python-requests)?
