### ISSUE TITLE
In the Upgrade to Pro page on the web dashboard, the 'Pay' button doesn't do anything

### ISSUE THREAD

**Issue by abhijitkane** [a85/POSTMan-Chrome-Extension#4856]
If I have 3 users on my team (my Pro trial expired), and try to upgrade to Pro with 2 users, the Pay button doesn't do anything. The console shows an error in the WebSocket tab saying I need to remove users, but there's no UI feedback.

**Comment by ankit-m** [comment]
A fix for this has been deployed.
