### ISSUE TITLE
Better use of space: Ability to collapse top panel

### ISSUE THREAD

**Issue by poisa** [a85/POSTMan-Chrome-Extension#4857]
Below the URL line there are a bunch of tabs:

    Authorization    Headers    Body    Pre-request Script    Tests

In my use case 99% of the time I can set these and forget about them. I'm interested in the response data but I still have to waste screen real estate with these tabs.

It would be great if these could be collapsed just like you can collapse the collections pane.

PS: Related to #4797

**Comment by numaanashraf** [comment]
Thanks for the feedback @poisa. We are aware of this and are working on few improvements that should help you with this issue. Since this is related to #4797, I'm closing this and will be using #4797 to post updates and track discussions on this issue.
