### ISSUE TITLE
Slack integration monitor names not populating

### ISSUE THREAD

**Issue by claireriley** [a85/POSTMan-Chrome-Extension#4858]
**Describe the bug**
User experiencing issue in web dashboard where monitor names are not being populated when looking at the configured Slack integration (send monitor run results to slack).

**To Reproduce**
1. Go to [web dashboard](https://app.getpostman.com/)
2. Go to any workspace
3. Click on Integrations
4. Click on Slack
5. Navigate to existing configuration

(I was unable to replicate the behavior described by the user)

**Expected behavior**
Monitor names should be displayed properly so that users can pick which ones to delete from the integration and which to keep - user had misbehaving monitor and could not single out which one it was.

**Screenshots**
<img width="853" alt="configured_integrations" src="https://user-images.githubusercontent.com/21180383/42975030-e545ca30-8b6e-11e8-8295-32ec9acd0a23.png">

**App information (please complete the following information):**
 -  Latest Chrome on Mac OS (67.0.3396.99)

**Comment by godfrzero** [comment]
This was happening due to an outage of the monitoring API, which meant that the monitor names were unavailable at this time. Instead of blocking the entire page, we show the information that's available.
