### ISSUE TITLE
Invalid sync status when the app's session expires

### ISSUE THREAD

**Issue by abhijitkane** [a85/POSTMan-Chrome-Extension#4859]
**Describe the bug**
Invalid sync status when the session expires

**To Reproduce**
1. Sign in to app
2. Close app
3. Reset password - this will expire sessions
4. Restart app
5. In the modal that shows up, click Sign Out
6. In the collections-will-be-deleted modal, click 'Cancel'
7. All my data stays editable -> potential security issue, and the sync status stays 'connecting' even though there's no WS connection

**Expected behavior**
Clicking cancel in the 2nd modal prevents any edits from being made till I sign in.

**App information (please complete the following information):**
 - OSX Native app 6.1.4

**Comment by numaanashraf** [comment]
Fixed in Postman v7.0
