### ISSUE TITLE
Epoch date in Postman

### ISSUE THREAD

**Issue by baalaZolo** [a85/POSTMan-Chrome-Extension#4863]
I would like to get the current system date in Epoch format. Can you please help me with this ?

**Comment by anshuljain03** [comment]
@baalaZolo You can use ``` Date.now() ``` to get the current timestamp in milliseconds.

**Comment by baalaZolo** [comment]
@anshuljain03 thanks for your reply. Is it any ways we can get start time of the current day? Ex Saturday, July 21, 2018 12:00:00 AM GMT+05:30 - 1532111400

**Comment by anshuljain03** [comment]
@baalaZolo The following snippet will give you the start time of the day. 
 ```
 var timestamp = new Date();
 var dt = Date.UTC(timestamp.getFullYear(), timestamp.getMonth(), timestamp.getDate());
 var date = new Date(dt).toUTCString();
 ```

**Comment by kamalaknn** [comment]
Hey @baalaZolo 

I'm closing this as this not an issue with Postman as such. Please use our community forum - https://community.getpostman.com/ for more help and discussions.
