### ISSUE TITLE
Header key corrupted when duplicating query

### ISSUE THREAD

**Issue by andig** [a85/POSTMan-Chrome-Extension#4864]
Please read through the [guidelines](https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues) before creating a new issue.

**Describe the bug**
When duplicating a query, the header key gets changed from `x-api-token` to `x-api-key`

**To Reproduce**
  1. Go to 'Collections'
  1. Select a request with `x-api-token` header defined:

      <img width="472" alt="screen shot 2018-07-23 at 09 22 25" src="https://user-images.githubusercontent.com/184815/43062724-0b156cfa-8e5a-11e8-8776-2db0267fd18f.png">

  2. Click on 'Cmd-D' to duplicate a request that has a request header defined
  3. Execute duplicated request and look at the developer console
  4. See error: request suddenly has the `x-api-key` header instead of `x-api-token`

          x-api-key:"WYgpzPIlMcFk..."

      <img width="464" alt="screen shot 2018-07-23 at 09 23 00" src="https://user-images.githubusercontent.com/184815/43062752-1feaffd2-8e5a-11e8-98ce-58c12d8296a5.png">

**Expected behavior**
Keep header key names as defined

**Screenshots**

**App information (please complete the following information):**
 - App Type Native App
 - Postman Version 6.1.3
 - OS: macOS High Sierra 10.13.2

**Comment by andig** [comment]
There is actually a second bug. When the URI contains a variable, that is replaced by the variable's value upon duplicating:

    {{url}}/surveys/{{survey}}

becomes

    {{url}}/surveys/kndvhregoerjglkjern

**Comment by kamalaknn** [comment]
Hey @andig 

I just followed your steps and could not see any change to the request on duplicating.

Can you verify if the request is updated in the UI on duplicating? Or is the request changing on sending it?

It would be great if you could provide a screen capture reproducing this. You can use https://getkap.co/ to capture your screen.

**Comment by andig** [comment]
> Can you verify if the request is updated in the UI on duplicating?

Directly on ~~updating~~ duplicating. I've noticed that I had a lot of open, unsafed tabs.

Apparently what happened was that- when selecting request from the collection- the app would show/open an unsaved tab that had `x-api-token` while the saved version was still `x-api-key`. When duplicating it would then use the saved version, not the selected tab.

Explainable but confusing? Since I have the workaround now please feel free to close if you think this is too minor a point.
