### ISSUE TITLE
Postman Not Honoring Proxy Settings

### ISSUE THREAD

**Issue by bpeake** [a85/POSTMan-Chrome-Extension#4868]
**Describe the bug**
Postman is attempting to send traffic through my system proxy, even though the use system proxy option is disabled. Sending an API call to localhost is resulting in the call being sent to the proxy. This is resulting in a workflow stoppage since I am unable to debug my APIs as I develop them. 

This is a new issue and just started occurring after upgrade to Windows 10 1703 from 1607. Not sure if it's related to that or a postman application update.

**To Reproduce**
1. Configure a system proxy in Internet Explorer.
2. Launch Postman
3. Confirm that Use System Proxy is off
4. Submit request to localhost
5. API call is sent to the proxy server.

**Expected behavior**
If Use System Proxy is not configured, the API call should go directly to the server or IP Address specified in the URL instead of submitting the request to the proxy.

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version: 6.1.4
 - OS: Windows 10 1703

**Comment by numaanashraf** [comment]
@bpeake Thanks for reporting this

**Comment by harryi3t** [comment]
@bpeake This is being tracked here https://github.com/postmanlabs/postman-app-support/issues/3942
Thanks again for reporting, please do subscribe the original issue for updates
