### ISSUE TITLE
Variables are not resolved dynamically

### ISSUE THREAD

**Issue by anudeepmedicharla** [a85/POSTMan-Chrome-Extension#4870]
When you try using a collection variable in an unsaved request, the variable doesn't get resolved, which is expected. Now, when you save the request in the same tab, the variable still gets shown as unresolved. When you send the request, the value is replaced though. I feel this behavior should be dynamic from a UI perspective.

Screenshot:
The variable is {{test}} and the value is "initial".

![screen shot 2018-07-24 at 13 01 51 pm](https://user-images.githubusercontent.com/16399370/43123658-847f0612-8f42-11e8-9c82-ca4a3e39eee8.png)

**Comment by prashantagarwal** [comment]
@anudeepmedicharla we will be fixing this along with tabs

**Comment by sujayvenaik** [comment]
This issue has been fixed and is available on the stable channel (v6.4.x).
You can update the app to the latest version.

Thanks again for writing in and reporting this issue.
