### ISSUE TITLE
Code snippets should allow to interpolate vairables

### ISSUE THREAD

**Issue by andig** [a85/POSTMan-Chrome-Extension#4871]
Please read through the [guidelines](https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues) before creating a new issue.

**Is your feature request related to a problem? Please describe.**
I need to export requests to curl for sharing with application support. Using code snippets leads to exported request containing variable names (`{{foo}}`)

**Describe the solution you'd like**
Instead I'd like to be able to substitute variable names for their values, maybe optionally, when generating code snipps (checkbox?).

**Describe alternatives you've considered**
Manual workaround :(

**Additional context**
This shows the problem:

    ❯ curl -X GET \
    'http://{{url}}/mailinglists/{{mailinglist}}/contacts' \
    -H 'Cache-Control: no-cache' \
    -H 'Postman-Token: 37a64443-...' \
    -H 'x-api-token: {{token}}'
    curl: (3) [globbing] nested brace in column 9

Using the dev console for `exporting` a request is error-prone and high manual effort.

**Comment by ctruzzi** [comment]
This seems like a defect, it was working in prior versions as it has broken all my snippets.

**Comment by abhijitkane** [comment]
@andig @ctruzzi Apologies for the delay here - this should be fixed in the latest Postman version.
