### ISSUE TITLE
Postman doesn't remember the search term when I go back in API network

### ISSUE THREAD

**Issue by anudeepmedicharla** [a85/POSTMan-Chrome-Extension#4873]
Steps to reproduce:
1. Go to API network
2. Enter a search term. For eg., 'Paypal'.
3. Click on the collection that appears. 
4. Go back.
5. The search term disappears inside the search field.

![screen shot 2018-07-24 at 15 48 31 pm](https://user-images.githubusercontent.com/16399370/43132397-44035d6a-8f59-11e8-8baf-b1fc08e7b75e.png)

**Comment by bhargavkaranam** [comment]
This has been fixed in the latest release 6.3.0.
