### ISSUE TITLE
Check the size of the Request in postman app

### ISSUE THREAD

**Issue by JayathmaChathurangani** [a85/POSTMan-Chrome-Extension#4875]
How to check the size of the request in postman app? 

When the response is given it mention about the size of the response (body and header separately) which is perfect. Likewise now I want to check the size of the request. Is it possible? If yes, how to do it?

I am using postman app v6.

**Comment by anudeepmedicharla** [comment]
Thanks for the suggestion @JayathmaChathurangani. We're already tracking this feature here:
https://github.com/postmanlabs/postman-app-support/issues/2282

Closing this issue as a duplicate.

**Comment by JayathmaChathurangani** [comment]
+1

**Comment by elchappo** [comment]
+1
