### ISSUE TITLE
Cookie Modal removal issue on postman (Prod and Canary)

### ISSUE THREAD

**Issue by alternativ** [a85/POSTMan-Chrome-Extension#4876]
**Bug**
When using the cookie manager modal one is able to delete cookies, in previous versions of Postman (6.1.x) it was possible to list all the cookies for a domain and delete them in one go. If I perform this action now and go back to the cookie manager all cookies are still there.

**Reproduce paths**

Requirement: Have cookies present in Postman library
1. In the interface click on cookies to manage cookies
2. In the bar that lists the domain for the bundled cookies press the X-button
3. Cookies dissapear
4. In the interface click on cookies to manage cookies
5. Cookies are present

**Expected behavior**
Actually delete the cookies from the filesystem.

Workaround is to delete the cookies one by one as shown in below video, however that is pretty time consuming.

**Movie attached**

[postman_cookies.mp4.zip](https://github.com/postmanlabs/postman-app-support/files/2224180/postman_cookies.mp4.zip)

**App information:**
 - Native App
 - Postman Canary 6.2.1-canary02 / Postman 6.1.4
 - Mac OS High Sierra 10.13.6

**Additional context**
Debugging: I removed all instances of Postman (Canary and prod build, removed /Users/alternativ/Library/Application Support/PostmanCanary and /Users/alternativ/Library/Application Support/Postman). Tried running with one single instance (Prod/Canary) however the issue is still present.

**Comment by harryi3t** [comment]
@alternativ Thanks for reporting the issue. I have reproduced the same on my end.
This should be fixed with the next update
