### ISSUE TITLE
Detection of pre-existing duplicate collection shall be limited to the workspace in which it is being imported

### ISSUE THREAD

**Issue by priyalviroja** [a85/POSTMan-Chrome-Extension#4877]
**Bug**

While importing a collection in a personal workspace, the app looks for any existing duplicate collection in all workspaces.

**Steps to reproduce the behavior:**
1. Go to 'Team Workspace'
2. Export any 'Collection' created/shared by another team member.
3. Go to "Personal Workspace'
4. Try Import the collection exported in step 2.

**Expected behavior**

On Import, app shall only look for any existing duplicate collection in the same workspace.

**Screenshot**

<img width="1413" alt="screen shot 2018-07-24 at 3 18 29 pm" src="https://user-images.githubusercontent.com/5723665/43153484-0c30c108-8f8f-11e8-8b9f-cce36a27b959.png">

**App information (please complete the following information):**
 - App Type [Native App]
 - Postman Version [Version 6.1.4 (6.1.4)]
 - OS: [macOS High Sierra 10.13.4]

**Comment by thecuriousdev** [comment]
@priyalviroja this is fixed, now we only check for conflicts in the current workspace scope. Available in Postman 6.2.0 or higher.
