### ISSUE TITLE
An original collection gets deleted from the App after importing the duplicate collection

### ISSUE THREAD

**Issue by priyalviroja** [a85/POSTMan-Chrome-Extension#4878]
**Bug**

A collection gets deleted from the Team Workspace after exporting and re-importing the same collection in the Personal Workspace.

**Steps to reproduce the behavior:**

1. Go to 'Team Workspace'
2. Export any 'Collection' created/shared by other team member.
3. Go to "Personal Workspace'
4. Try Import the collection exported in step (2)
5. "Replace"
6. Go to "Team Workspace", the collection which was exported and then re-imported would be missing!

**Expected behavior**

A pre-existing collection shouldn't get deleted from the App. 

**Screenshot**

<img width="1413" alt="screen shot 2018-07-24 at 3 18 29 pm" src="https://user-images.githubusercontent.com/5723665/43153484-0c30c108-8f8f-11e8-8b9f-cce36a27b959.png">

**App information (please complete the following information):**

 - App Type [Native App]
 - Postman Version [Version 6.1.4 (6.1.4)]
 - OS: [macOS High Sierra 10.13.4]

**Note**

- Collection only gets deleted from Postman App and not from Pro Dashboard.
- Sync gets stuck after performing the above steps.
- Restarting and Force-Sync the app is not helping here.

**Comment by thecuriousdev** [comment]
@priyalviroja this is fixed. Available in Postman 6.2.0 or higher.
