### ISSUE TITLE
No way to go back from the 'Trouble signing in' section in the app

### ISSUE THREAD

**Issue by abhijitkane** [a85/POSTMan-Chrome-Extension#4879]
**Describe the bug**
There's no way to go back from the 'Trouble signing in' section in the app if I accidentally click on it. I can only close the window, go back to the app, and then click 'Add new account' again.

**To Reproduce**
1. In the app's signin screen, click 'Trouble signing in'

**Expected behavior**
A back link that takes me back to the signin page

<img width="618" alt="screen shot 2018-07-24 at 23 26 57" src="https://user-images.githubusercontent.com/681190/43157036-6a99c5fa-8f99-11e8-9db1-9dcee444e63e.png">

**App information (please complete the following information):**
 - Postman 6.2.1 OSX

**Comment by sankalp0o** [comment]
@abhijitkane Are you talking about a back link or are you talking about the "Cancel and take me to signed in account"?

**Comment by abhijitkane** [comment]
@sankalp0o The former. If I know my password but accidentally clicked on the forgot pwd link.

**Comment by preethammavin** [comment]
The issue has been solved, with a return to sign in page CTA added
