### ISSUE TITLE
Unresolved variable tooltips show a red 'E' icon

### ISSUE THREAD

**Issue by abhijitkane** [a85/POSTMan-Chrome-Extension#4880]
**Describe the bug**
In the URL input, hovering over an undefined variable shows the 'E' icon, even though I have no environment selected.

**To Reproduce**
1. Unselect any environment
2. Enter `{{url}}` in the URL input

**Expected behavior**
A `?` icon, perhaps

**Screenshots**
<img width="262" alt="screen shot 2018-07-24 at 23 47 36" src="https://user-images.githubusercontent.com/681190/43157919-f88c1eec-8f9b-11e8-9818-c91da5440f04.png">

**App information (please complete the following information):**
Postman OSX 6.2.1

**Comment by vkaegis** [comment]
@prashantagarwal Can we use a red "!" for unresolved variables?
We should probably change the color for the Environment scope from red to something else.

**Comment by prashantagarwal** [comment]
This is fixed in Postman 6.2.4.
