### ISSUE TITLE
Postman using too much virtual memory in macOs High Sierra 

### ISSUE THREAD

**Issue by Krgopal** [a85/POSTMan-Chrome-Extension#4881]
Please read through the [guidelines](https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues) before creating a new issue.

**Describe the bug**
Postman is using too much virtual memory in macOS High Sierra (version: 10.13.6). It uses 20 GB of Virtual Memory for the postman. Is it the issue with the collection? I have checked the backup file for the postman,  it is of size approx 200 KB. 

**To Reproduce**

**Expected behavior**
Virtual memory of 20 Gb is much higher for apps like postman. it should not be more than 1 GB. it is consuming more virtual memory than Jvm.

**Screenshots**
![postman_virtual_memory_bug](https://user-images.githubusercontent.com/31614501/43164670-5e61adc8-8faf-11e8-93c1-46780fac3f75.png)

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version: 6.2.1
 - OS: macOS High Sierra 10.13.6

**Additional context**

**Comment by mccannt** [comment]
@Krgopal We have pushed some recent performance upgrades since this issue was logged. 
Can you try this with the most recent version of the application and let us know if this is still impacting you?

**Comment by kamalaknn** [comment]
@Krgopal We have pushed some performance improvements that help if you are working with large responses or large number of history in your workspace. Do try the latest version of Postman and let us know if you are still facing issues.
