### ISSUE TITLE
App screen doesn't show correctly

### ISSUE THREAD

**Issue by fakhrulhilal** [a85/POSTMan-Chrome-Extension#4882]
**Describe the bug**
Postman doesn't show correct screen at first load

**To Reproduce**
Just open postman

**Expected behavior**
Postman screen displayed

**Screenshots**
![postman](https://user-images.githubusercontent.com/1755735/43178714-e7ed12dc-8ff8-11e8-8c97-eed1b1eab8f8.jpg)

**App information (please complete the following information):**
 - Native app
 - Postman Version 6.1.4 64bit version
 - OS: Windows 7 Enterprise SP1

**Additional context**
This is intermittent error. Sometimes it loads the screen after minutes, sometimes it doesn't. But this time, it just freezes. I can't use postman at all at the moment. Reinstalling postman didn't solve the issue. I did cleared `%AppData%\Postman` and `%LocalAppData%\Postman` before installing.

**Comment by SamvelRaja** [comment]
@fakhrulhilal  Possibly fix for this https://github.com/postmanlabs/postman-app-support/issues/4594#issuecomment-391601621

**Comment by fakhrulhilal** [comment]
Just tried it today, suddenly, it works now. I don't know exactly what's causing the bug.

**Comment by SamvelRaja** [comment]
Closing this for now :) Feel free to reopen this if issue appears again.
