### ISSUE TITLE
Postman wont open - error: "Could not find default workspace"

### ISSUE THREAD

**Issue by blowsie** [a85/POSTMan-Chrome-Extension#4883]
**Describe the bug**
Post man wont load, shows spinner
![image](https://user-images.githubusercontent.com/308572/43197322-bd778bea-9002-11e8-82a8-6558532b70f6.png)

**To Reproduce**
1. Uninstall Postman
2. Delete Postman folder in user/AppData/Local
3. Install Postman-win64-6.1.4-Setup
4. Open Shurctut generated by installer found on desktop

**Expected behavior**
App to open

**Screenshots**

**App information (please complete the following information):**
 - App Type Native App
 - Postman Version [Postman-win64-6.1.4]
 - OS: [Win10]

**Additional context**
Errors found in the debugging console;
```
vendor-shared.js:85036 Error booting session Error: Could not find default workspace while booting session
    at Object.then.then.defaultWorkspace (requester.js:12671)
    at <anonymous>
```

```
vendor-shared.js:85036 TypeError: Cannot read property 'getShortcuts' of undefined
    at Requester.render (/C:/Users/xyz/AppData/Local/Postman/app-6.1.4/resources/app.asar/js/RequesterInit.js:3502)
    at h (vendor-ui.js:7536)
    at beginWork (vendor-ui.js:7539)
    at d (vendor-ui.js:7567)
    at f (vendor-ui.js:7567)
    at g (vendor-ui.js:7568)
    at m (vendor-ui.js:7575)
    at w (vendor-ui.js:7574)
    at z (vendor-ui.js:7573)
    at u (vendor-ui.js:7571)
    at Object.enqueueSetState (vendor-ui.js:7514)
    at LoadableComponent.webpackJsonp.734.A.setState (vendor-ui.js:7389)
    at update (requester.js:15915)
    at requester.js:15925
    at <anonymous>
````

```
vendor-shared.js:85036 WorkspaceSession not found in DB
```

![image](https://user-images.githubusercontent.com/308572/43197524-56be8f06-9003-11e8-8c77-c9a426df2399.png)

**Comment by Goufalite** [comment]
Look if the shortcut on the desktop points to the 6.1.4 version. But even launching the real exe (C:\Users\XXX\AppData\Local\Postman\app-6.1.4) the getShortcuts problem is still here

**Comment by steelerc** [comment]
I am seeing the same issue.  I have downloaded the latest Canary, and it seems to work, whereas the 6.1.4 version does not.  There are two problems I'm seeing with the Canary though: 1) it doesnt seem to recognize the POSTMAN_DISABLE_GPU = true environment variable; and 2) it doesnt seem to see my history or collections from the real current postman.
![capture](https://user-images.githubusercontent.com/3587947/43267723-bfcee31a-90bc-11e8-96be-804995d3e063.JPG)

**Comment by steelerc** [comment]
Ignore #2 above I copied a bunch of directories from my PostMan into my Canary directory and have what is needed!

**Comment by SamvelRaja** [comment]
@blowsie  @Goufalite  Could you open the app via cmd `C:\users\[USER]\AppData\Postman\app-6.1.4\Postman.exe` Which gives more logs on whats going wrong behind the scene.

Also. 
@steelerc  We won't recommend moving the files into app data will work. If you are already a logged in user then your data would be available in our servers which you can log in back and get it.

I also recommend you to open the app via cmd to view the problem going on behind the scene.

**Comment by Goufalite** [comment]
Very interesting !! Here's the console output for 6.1.4
```
App events bus { name: 'booted', namespace: 'shared' }
App events bus { data:
   { adapterMethodName: 'find',
     cause:
      { adapterMethodName: 'find',
        modelIdentity: 'workspacesession',
        name: 'AdapterError',
        raw: [Object] },
     isOperational: true,
     modelIdentity: 'workspacesession',
     raw:
      { _e: {},
        inner: [Object],
        message: 'VersionError The requested version (10) is less than the exist
ing version (30).',
        name: 'OpenFailedError' } },
  name: 'booted',
  namespace: 'requester' }
```
FYI, I installed the canary version since it fixes the problem

**Comment by SamvelRaja** [comment]
@Goufalite  Have you opened the 6.2.1 and went back to 6.1.4? We pushed 6.2.1 to part of the users. 
And going back from the version is not possible. Since we made a change in the underlying indexeddb version.

**Comment by Goufalite** [comment]
Here's the cinematic : 

- I opened 6.1.3 => worked and update available shown
- Postman done some things and showed the workspace
- I closed Postman
- I opened 6.1.4 => stuck on loading screen
At this point I didn't want to clear data because I thought it would loose my work, but I didn't knew it was automatically synced
- I downloaded and lauched canary => worked

I succeeded in retrieving my data using my account when I switched to canary.

**Comment by blowsie** [comment]
@SamvelRaja  as requested

```
C:\Users\xxx\AppData\Local\Postman\app-6.1.4>
ORM initialization successful
App events bus { name: 'booted', namespace: 'shared' }
App events bus { data: {}, name: 'booted', namespace: 'requester' }
```

**Comment by steelerc** [comment]
My screen print above was from the cmd version of the program with the developer window open to see what errors are occurring.

**Comment by kamalaknn** [comment]
This issue has not been seen in the recent versions of Postman. I'm closing this issue now. Please let us know if you are seeing this issue again.
