### ISSUE TITLE
[GET] How to get a request params as str[]

### ISSUE THREAD

**Issue by syan624** [a85/POSTMan-Chrome-Extension#4884]
Here my question:
![image](https://user-images.githubusercontent.com/41688238/43204162-c41fd09c-9052-11e8-82fe-36eeaad4e574.png)

I want to split params by "&",then sort by ASCII

**Comment by sivcan** [comment]
@syan624 
You can filter out the variables like so:
```javascript
// Function to get variables from a URL string
let getUrlParams = (str) => {
        let params = [],
    	parts = str.replace(/[?&]+([^=&]+)=([^&]*)/gi, function(m, key, value) {
                params.push({ [key]: value });
            });
        return params;
    },

    exampleUrl = '{{url}}?gameids={{gameid}}&terminal=3&source=1&sign=7xyztokenetc',

    params = getUrlParams(exampleUrl); // Replace exampleUrl with request.url

console.log(params);
```
Output of the above code: 
```javascript
[
  {
    "gameids": "{{gameid}}"
  },
  {
    "terminal": "3"
  },
  {
    "source": "1"
  },
  {
    "sign": "7fsfsfsf"
  }
]
```

To sort them: 
```javascript
let sortedParams = params.sort((x, y) => /* write your comparison logic here */);
```
Read more about sorting an array of objects in javascript here:
https://stackoverflow.com/questions/1129216/sort-array-of-objects-by-string-property-value-in-javascript

Hope this helps :) 
Also, you can reach out to the postman community https://community.getpostman.com/latest
for how-to queries and more related information.

We maintain this repository to keep a track of feature request and bug fixes thus closing this issue.
