### ISSUE TITLE
Environmental Variables issue

### ISSUE THREAD

**Issue by makrada** [a85/POSTMan-Chrome-Extension#4885]
**Describe the bug**
A user creates two environmental variables where the second one includes the "_" symbol. 

For instance, var1 and var1_2. In whichever API call the var1_2 is passed as an argument, it seems postman ignores the "_" in the request and instead passes the value of var1 to the call, hence the API response is not valid value. In my case is not valid token.

**To Reproduce**
1. Create two environmental variables as provided in the description above
2. Create two GET call each of the using these variables
3. The call with the variable with "_" should fail

**App information (please complete the following information):**
 - App Type [Native app
 - Postman for Linux / Version 6.1.4 / linux 4.15.0-24-generic / x64

**Comment by harryi3t** [comment]
@makrada Thanks for reporting the issue.
I tried reproducing this on my end but was unable to do so.
For me, the variable `var1_2` was being used even though `var1` was defined. Please see the attached screenshot
![postman](https://user-images.githubusercontent.com/5207331/43312196-2dd2fc5a-91aa-11e8-88d2-5f3eac60e425.png)

Am I missing something? If you are able to reproduce this, could you send us a screenshot?

**Comment by makrada** [comment]
Hi @harryi3t 

I tried to replicate it but it doesn't seem the behavior to be consistent(there were times that the bug wasn't happening). I am trying to understand under what circumstances this occurs. Once I have a consistent scenario if this keeps happening I will revert to you with more details.

No need to have this issue open, I will open a new one if needed in the future.

Thank you for your time.

**Comment by harryi3t** [comment]
@makrada 
I am closing this issue then. 
Feel free to re-open the issue if this happens in future.
