### ISSUE TITLE
Not able to fire requests from US (East)

### ISSUE THREAD

**Issue by aambekar91** [a85/POSTMan-Chrome-Extension#4886]
Hi Team,

I have setup a monitor to run every morning on a collection. The monitor tests the requests from US (East) and US (West) region. I was able to see the requests from US (West) being run within a minute without any issue, however, I do not see any requests being made from the US (East) region. Can you please let me know if I'm missing something? I tried to change the monitor to test requests going out only from US (East) and the 'Request Split' tab on the Monitor Performance page just says 'X run starting' but there is no request sent. Request Timeout and delay between requests both are at default setting.

**Comment by godfrzero** [comment]
The US East region has the most load, so monitors in that region tend to take a bit longer to execute. I'm guessing that you monitor did *eventually* end up sending the request, but correct me if I'm wrong.

**Comment by aambekar91** [comment]
Hi Vivek,

The monitor did not send requests yesterday but when I tried it again this morning, it seemed to work fine. Thank you for your support. You may close this issue.
