### ISSUE TITLE
Sign In on Support Help Desk not working on Firefox

### ISSUE THREAD

**Issue by numaanashraf** [a85/POSTMan-Chrome-Extension#4890]
**Describe the bug**
Sign In button on top right in help center (https://support.getpostman.com/hc/en-us/) not working on Firefox (v62 / MacOS). Works on Chrome.

**Screenshots**
<img width="1030" alt="screen shot 2018-07-26 at 1 14 42 pm" src="https://user-images.githubusercontent.com/3295568/43248642-21cdba8c-90d6-11e8-952d-7182436642c7.png">

**Comment by preethammavin** [comment]
@numaanashraf it seems to have been fixed now.
