### ISSUE TITLE
{{$randomString}}, {{$randomGuid}} & extending {{$randomInt}}- dynamic variable feature request 

### ISSUE THREAD

**Issue by zoso200** [a85/POSTMan-Chrome-Extension#4891]
Hi,

Finding $randomInt very useful. 

Would it be possible to add additional dynamic variables such as:

{{$randomIntLarge}} - 50 characters instead of 4 

{{$randomGuid}} - creates a random 32 character GUID in standard format eg 11111111-1111-1111-111111111111

{{$randomString}} - creates a random string

**Comment by tnatanael** [comment]
+1

**Comment by tnatanael** [comment]
Sugestion {{$random:{type}:{size}}}
Examples:
    {{$random:int:8}} - To generate 8 digit long random number
    {{$random:str:5}} - To generate 5 digit long random string

**Comment by Ma11hewThomas** [comment]
+1

**Comment by divinebovine** [comment]
If you want a random guid, you should be able to use `{{$guid}}`.

**Comment by jeremylima** [comment]
+1

**Comment by ghost** [comment]
+1
currently using {{$randomInt}} is giving me only 3 digit random number. How do i extend it to a 10 digit number?

**Comment by IlanPearlman** [comment]
> Sugestion {{$random:{type}:{size}}}
> Examples:
> {{$random:int:8}} - To generate 8 digit long random number
> {{$random:str:5}} - To generate 5 digit long random string

This would be an excellent extension of the tool

**Comment by Marusyk** [comment]
any news?

**Comment by zoso200** [comment]
Response from Postman Dev on this would be great. It's the one thing that'd holding back my testing using this tool at the moment.

**Comment by stoneric7** [comment]
In the meantime you could do {{$randomInt}}{{$randomInt}}, that would generate 2 numbers between 0-1000. I use this for emails. Obviously not as good as {{$random:int:8}}

**Comment by mukeshknoldus** [comment]
Any update on this as i need this feature in my testing

**Comment by DannyDainton** [comment]
As a workaround and something that has been part of the app for many versions - You could use the `_.random()` function of [Lodash](https://lodash.com/docs/4.17.11#random) to generate a random `int`.

For example:

Use `_.random(10000000, 99999999)` to get an 8 digit number or change the values to get a different range. This could be easily added to an `environment` or `global` variable, to use within your requests.

Not the feature you want to see but something that does the same thing and is there ready for you to use.

**Comment by JokerTheFourth** [comment]
+1

**Comment by Empkh** [comment]
+1

**Comment by abezhinaru** [comment]
+1

**Comment by sebastienvermeille** [comment]
+1

**Comment by ElisePatrikainen** [comment]
+1

**Comment by michiel-schoofs** [comment]
+1

**Comment by codenirvana** [comment]
A large list of dynamic variables is added in the latest version of the Postman app.

Refer: https://github.com/postmanlabs/postman-app-support/issues/971#issuecomment-532167955

For custom length random int and strings. I suggest setting a local variable in the pre-request script as mentioned above https://github.com/postmanlabs/postman-app-support/issues/4891#issuecomment-474870063

**Comment by bellaj** [comment]
a workaround would be :
"{{$randomAlphaNumeric}}{{$randomAlphaNumeric}}{{$randomAlphaNumeric}}{{$randomAlphaNumeric}}"
