### ISSUE TITLE
Deleting a request with backspace shows an error

### ISSUE THREAD

**Issue by ankit-m** [a85/POSTMan-Chrome-Extension#4892]
Please read through the [guidelines](https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues) before creating a new issue.

**Describe the bug**
In a team workspace, on a collection for which I have edit permission, using backspace to delete a request shows an error saying you do not have permissions to delete the collection. Using the context menu to delete requests works fine.

**To Reproduce**
1. Join a team workspace
2. Open a collection which you have edit access to
3. Try to delete a request from the sidebar using `backspace`

**Expected behavior**
Delete the request.

**Screenshots**
![image](https://user-images.githubusercontent.com/9019878/43258811-bb015842-90f1-11e8-97e2-824ccd71658c.png)

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version: 6.2.1
 - OS: macOS High Sierra 10.13.5

**Comment by harryi3t** [comment]
@ankit-m This is fixed on our [canary build](https://www.getpostman.com/canary) and will be available on the production build in the next release.

**Comment by harryi3t** [comment]
This is fixed in the latest version of Postman 6.2.3
