### ISSUE TITLE
The tooltip for system generated headers blocks the header-value

### ISSUE THREAD

**Issue by harryi3t** [a85/POSTMan-Chrome-Extension#4894]
**Describe the bug**
The tooltip for system generated headers blocks the header-value

**Expected behavior**
The tooltip should not block the value

**Screenshots**
![postman](https://user-images.githubusercontent.com/5207331/43263439-e4f015f8-9100-11e8-80f6-59e4f9c3ae70.png)

**Comment by numaanashraf** [comment]
Fixed in Postman v7.0
