### ISSUE TITLE
Security leak of Authorization bearer token in saved examples

### ISSUE THREAD

**Issue by cortopy** [a85/POSTMan-Chrome-Extension#4895]
**Describe the bug**
If I publish a collection with examples in the endpoint, the Authorization header is included in full with the Example data.

**To Reproduce**
1. Create a collection with one request that requires Authorization with Bearer token
2. Make the request and save the response as an example
3. Publish docs with "No Environment" associated to it
4. Open the link in a new browser
5. Click on "Run in Postman"
6. If there is no Chrome app installed, I can see the full collection data in the browser. Upon inspection, I can see that my saved example is for everybody to see in:

```
- responses[n].request.headers
- responses[n].request.headerData
```

**Expected behavior**
Not to leak Authorization values! 

In the app, it says that Authorization headers are temporary and won't be saved (even when you hover on the Authorization header in the example). However, this doesn't seem to be the case.

**App information (please complete the following information):**
 - App Type Native App
 - Postman Version 6.1.4
 - OS: Linux Manjaro

**Comment by vkaegis** [comment]
@cortopy We couldn't replicate this on our end. If you've used the Authorization Helper for Bearer Token provided in the Authorization tab of the request, a header should be added to your request. This particular header is never saved with the request or example. However, if you add an authorization header manually in the Headers tab, we treat it as a normal header and it will be saved with the request. The Run in Postman collection data never shows the Authorization header added by the helper.

**Comment by cortopy** [comment]
@vkaegis I used the Authorization Helper. In my case the header wasn't showing in the runner itself or the saved requests. However, in the file itself (as I got it from the browser) the examples do have the Authorization headers with the resolved values

**Comment by harryi3t** [comment]
@cortopy We were unable to reproduce this. Will it be possible for you to create and [share](https://www.getpostman.com/docs/v6/postman/collections/sharing_collections) a dummy collection which can reproduce this issue along with the published collection's URL? It would really help in reproducing and fixing the issue. Also if possible you can screen record the whole process

Here's a screen recording where I tried to reproduce this but was unable to do so
https://drive.google.com/file/d/1ppV4lTRy_hK91FvrmNw5_CYdE7uzc9vW/view

**Comment by cortopy** [comment]
I can see it has been fixed, as running it again and I can't find the leak any more. Closing
