### ISSUE TITLE
Postman doesn't open - DB version is missing

### ISSUE THREAD

**Issue by tlair123** [a85/POSTMan-Chrome-Extension#4897]
**Describe the bug**
Postman updated itself from 6.1.4 to 6.2.1 native app.  Now the screen opens, but the 3 dots circle endlessly.  I ran it from the command line and I got the attached error.  the heart of is is that "UpgradeError Dexie specification of currently installed DB version is missing"

[Postman Dexie error.docx](https://github.com/postmanlabs/postman-app-support/files/2232606/Postman.Dexie.error.docx)

**To Reproduce**
1. Launch from icon.
2. Watch
3. See error
4. open cmd
5. Launch postman.exe from app-6.2.1
6. See error in CMD

**Expected behavior**
I expect postman to open normally.

**Screenshots**
please see attached

**App information (please complete the following information):**
 - App Type [Native App]
 - Postman Version [e.g. 6.2.1]
 - OS: [Windows 10]

**Additional context**

**Comment by kamalaknn** [comment]
Hey @tlair123 

I'm trying to reproduce this, but couldn't. I will need some more information to debug this.

1. Can you give us the logs from `View -> Developer -> Show DevTools (Shared)` and `Right Click -> Save As`? This would export all the logs for starting up. **Please redact any user related information**.
2. Can you execute the following script and send the logs for that?
```
(function () { console.log('Update status', localStorage.getItem('dbInitContext')); var request = indexedDB.open('postman-app'); request.onerror = (e) => { console.error('Error while opening DB', e); }; request.onsuccess = () => { console.log('DB version', request.result.version); }; })();
```
This script logs the status of data storage setup step we do as part of the App startup. This would help me to identify where the root cause of this is.

**Comment by nicolasdalsass** [comment]
Hi !  I got the exact same problem, so I'll allow myself to answer : 

1.

﻿

> vendor-shared.js:76653 Initializing the global config
> vendor-shared.js:83400 Initializing settings
> shared.js:13537 Skipping migrations. No migrations to apply.
> vendor-shared.js:76713 Booting waterline models
> vendor-shared.js:144542 db name postman-app
> vendor-shared.js:83465 Error while seeding data. 
> OperationalError
> adapterMethodName
> :
> "count"
> cause
> :
> Error: Malformed error from adapter: Should always be an Error instance, but instead, got: ``` [OpenFailedError: UpgradeError Dexie specification of currently installed DB version is missing] ``` at file:///home/nico/Downloads/Postman/app/resources/app/js/vendor-shared.js:193364:5 at file:///home/nico/Downloads/Postman/app/resources/app/js/vendor-shared.js:193516:9 at replenish (file:///home/nico/Downloads/Postman/app/resources/app/js/vendor-shared.js:88798:17) at file:///home/nico/Downloads/Postman/app/resources/app/js/vendor-shared.js:88802:9 at eachOfLimit (file:///home/nico/Downloads/Postman/app/resources/app/js/vendor-shared.js:105061:36) at mapValuesLimit (file:///home/nico/Downloads/Postman/app/resources/app/js/vendor-shared.js:193515:31) at file:///home/nico/Downloads/Postman/app/resources/app/js/vendor-shared.js:76613:16 at seedDatabase (file:///home/nico/Downloads/Postman/app/resources/app/js/vendor-shared.js:193355:58) at file:///home/nico/Downloads/Postman/app/resources/app/js/vendor-shared.js:144569:76 at file:///home/nico/Downloads/Postman/app/resources/app/js/vendor-shared.js:145511:14 at file:///home/nico/Downloads/Postman/app/resources/app/js/vendor-shared.js:145301:14 at file:///home/nico/Downloads/Postman/app/resources/app/js/vendor-shared.js:63343:25 at iteratorCallback (file:///home/nico/Downloads/Postman/app/resources/app/js/vendor-shared.js:63388:17) at file:///home/nico/Downloads/Postman/app/resources/app/js/vendor-shared.js:63238:20 at file:///home/nico/Downloads/Postman/app/resources/app/js/vendor-shared.js:43242:16 at iteratorCallback (file:///home/nico/Downloads/Postman/app/resources/app/js/vendor-shared.js:43819:13)
> isOperational
> :
> true
> modelIdentity
> :
> "user"
> raw
> :
> DexieError
> message
> :
> "Malformed error from adapter: Should always be an Error instance, but instead, got:↵```↵[OpenFailedError: UpgradeError Dexie specification of currently installed DB version is missing]↵```"
> name
> :
> "AdapterError"
> stack
> :
> "AdapterError: Malformed error from adapter: Should always be an Error instance, but instead, got:↵```↵[OpenFailedError: UpgradeError Dexie specification of currently installed DB version is missing]↵```↵    at file:///home/nico/Downloads/Postman/app/resources/app/js/vendor-shared.js:193364:5↵From previous event:↵    at Deferred.toPromise (file:///home/nico/Downloads/Postman/app/resources/app/js/vendor-shared.js:150197:19)↵    at Deferred.then (file:///home/nico/Downloads/Postman/app/resources/app/js/vendor-shared.js:150056:22)↵    at file:///home/nico/Downloads/Postman/app/resources/app/js/vendor-shared.js:193365:5↵    at file:///home/nico/Downloads/Postman/app/resources/app/js/vendor-shared.js:193516:9↵    at replenish (file:///home/nico/Downloads/Postman/app/resources/app/js/vendor-shared.js:88798:17)↵    at file:///home/nico/Downloads/Postman/app/resources/app/js/vendor-shared.js:88802:9↵    at eachOfLimit (file:///home/nico/Downloads/Postman/app/resources/app/js/vendor-shared.js:105061:36)↵    at mapValuesLimit (file:///home/nico/Downloads/Postman/app/resources/app/js/vendor-shared.js:193515:31)↵    at file:///home/nico/Downloads/Postman/app/resources/app/js/vendor-shared.js:76613:16↵    at seedDatabase (file:///home/nico/Downloads/Postman/app/resources/app/js/vendor-shared.js:193355:58)↵    at file:///home/nico/Downloads/Postman/app/resources/app/js/vendor-shared.js:144569:76↵    at file:///home/nico/Downloads/Postman/app/resources/app/js/vendor-shared.js:145511:14↵    at file:///home/nico/Downloads/Postman/app/resources/app/js/vendor-shared.js:145301:14↵    at file:///home/nico/Downloads/Postman/app/resources/app/js/vendor-shared.js:63343:25↵    at iteratorCallback (file:///home/nico/Downloads/Postman/app/resources/app/js/vendor-shared.js:63388:17)↵    at file:///home/nico/Downloads/Postman/app/resources/app/js/vendor-shared.js:63238:20↵    at file:///home/nico/Downloads/Postman/app/resources/app/js/vendor-shared.js:43242:16↵    at iteratorCallback (file:///home/nico/Downloads/Postman/app/resources/app/js/vendor-shared.js:43819:13)↵    at file:///home/nico/Downloads/Postman/app/resources/app/js/vendor-shared.js:43727:16↵    at file:///home/nico/Downloads/Postman/app/resources/app/js/vendor-shared.js:192237:18"
> __stackCleaned__
> :
> true
> __proto__
> :
> Error
> vendor-shared.js:83465 Error while seeding data. 
> OperationalError
> adapterMethodName
> :
> "count"
> cause
> :
> Error: Malformed error from adapter: Should always be an Error instance, but instead, got: ``` [OpenFailedError: UpgradeError Dexie specification of currently installed DB version is missing] ``` at file:///home/nico/Downloads/Postman/app/resources/app/js/vendor-shared.js:193364:5 at file:///home/nico/Downloads/Postman/app/resources/app/js/vendor-shared.js:193516:9 at replenish (file:///home/nico/Downloads/Postman/app/resources/app/js/vendor-shared.js:88798:17) at file:///home/nico/Downloads/Postman/app/resources/app/js/vendor-shared.js:88802:9 at eachOfLimit (file:///home/nico/Downloads/Postman/app/resources/app/js/vendor-shared.js:105061:36) at mapValuesLimit (file:///home/nico/Downloads/Postman/app/resources/app/js/vendor-shared.js:193515:31) at file:///home/nico/Downloads/Postman/app/resources/app/js/vendor-shared.js:76613:16 at seedDatabase (file:///home/nico/Downloads/Postman/app/resources/app/js/vendor-shared.js:193355:58) at file:///home/nico/Downloads/Postman/app/resources/app/js/vendor-shared.js:144569:76 at file:///home/nico/Downloads/Postman/app/resources/app/js/vendor-shared.js:145511:14 at file:///home/nico/Downloads/Postman/app/resources/app/js/vendor-shared.js:145301:14 at file:///home/nico/Downloads/Postman/app/resources/app/js/vendor-shared.js:63343:25 at iteratorCallback (file:///home/nico/Downloads/Postman/app/resources/app/js/vendor-shared.js:63388:17) at file:///home/nico/Downloads/Postman/app/resources/app/js/vendor-shared.js:63238:20 at file:///home/nico/Downloads/Postman/app/resources/app/js/vendor-shared.js:43242:16 at iteratorCallback (file:///home/nico/Downloads/Postman/app/resources/app/js/vendor-shared.js:43819:13)
> isOperational
> :
> true
> modelIdentity
> :
> "globals"
> raw
> :
> DexieError
> message
> :
> "Malformed error from adapter: Should always be an Error instance, but instead, got:↵```↵[OpenFailedError: UpgradeError Dexie specification of currently installed DB version is missing]↵```"
> name
> :
> "AdapterError"
> stack
> :
> "AdapterError: Malformed error from adapter: Should always be an Error instance, but instead, got:↵```↵[OpenFailedError: UpgradeError Dexie specification of currently installed DB version is missing]↵```↵    at file:///home/nico/Downloads/Postman/app/resources/app/js/vendor-shared.js:193364:5↵From previous event:↵    at Deferred.toPromise (file:///home/nico/Downloads/Postman/app/resources/app/js/vendor-shared.js:150197:19)↵    at Deferred.then (file:///home/nico/Downloads/Postman/app/resources/app/js/vendor-shared.js:150056:22)↵    at file:///home/nico/Downloads/Postman/app/resources/app/js/vendor-shared.js:193365:5↵    at file:///home/nico/Downloads/Postman/app/resources/app/js/vendor-shared.js:193516:9↵    at replenish (file:///home/nico/Downloads/Postman/app/resources/app/js/vendor-shared.js:88798:17)↵    at file:///home/nico/Downloads/Postman/app/resources/app/js/vendor-shared.js:88802:9↵    at eachOfLimit (file:///home/nico/Downloads/Postman/app/resources/app/js/vendor-shared.js:105061:36)↵    at mapValuesLimit (file:///home/nico/Downloads/Postman/app/resources/app/js/vendor-shared.js:193515:31)↵    at file:///home/nico/Downloads/Postman/app/resources/app/js/vendor-shared.js:76613:16↵    at seedDatabase (file:///home/nico/Downloads/Postman/app/resources/app/js/vendor-shared.js:193355:58)↵    at file:///home/nico/Downloads/Postman/app/resources/app/js/vendor-shared.js:144569:76↵    at file:///home/nico/Downloads/Postman/app/resources/app/js/vendor-shared.js:145511:14↵    at file:///home/nico/Downloads/Postman/app/resources/app/js/vendor-shared.js:145301:14↵    at file:///home/nico/Downloads/Postman/app/resources/app/js/vendor-shared.js:63343:25↵    at iteratorCallback (file:///home/nico/Downloads/Postman/app/resources/app/js/vendor-shared.js:63388:17)↵    at file:///home/nico/Downloads/Postman/app/resources/app/js/vendor-shared.js:63238:20↵    at file:///home/nico/Downloads/Postman/app/resources/app/js/vendor-shared.js:43242:16↵    at iteratorCallback (file:///home/nico/Downloads/Postman/app/resources/app/js/vendor-shared.js:43819:13)↵    at file:///home/nico/Downloads/Postman/app/resources/app/js/vendor-shared.js:43727:16↵    at file:///home/nico/Downloads/Postman/app/resources/app/js/vendor-shared.js:192237:18"
> __stackCleaned__
> :
> true
> __proto__
> :
> Error
> vendor-shared.js:83465 Error while seeding data. 
> OperationalError
> adapterMethodName
> :
> "count"
> cause
> :
> Error: Malformed error from adapter: Should always be an Error instance, but instead, got: ``` [OpenFailedError: UpgradeError Dexie specification of currently installed DB version is missing] ``` at file:///home/nico/Downloads/Postman/app/resources/app/js/vendor-shared.js:193364:5 at file:///home/nico/Downloads/Postman/app/resources/app/js/vendor-shared.js:193516:9 at replenish (file:///home/nico/Downloads/Postman/app/resources/app/js/vendor-shared.js:88798:17) at file:///home/nico/Downloads/Postman/app/resources/app/js/vendor-shared.js:88802:9 at eachOfLimit (file:///home/nico/Downloads/Postman/app/resources/app/js/vendor-shared.js:105061:36) at mapValuesLimit (file:///home/nico/Downloads/Postman/app/resources/app/js/vendor-shared.js:193515:31) at file:///home/nico/Downloads/Postman/app/resources/app/js/vendor-shared.js:76613:16 at seedDatabase (file:///home/nico/Downloads/Postman/app/resources/app/js/vendor-shared.js:193355:58) at file:///home/nico/Downloads/Postman/app/resources/app/js/vendor-shared.js:144569:76 at file:///home/nico/Downloads/Postman/app/resources/app/js/vendor-shared.js:145511:14 at file:///home/nico/Downloads/Postman/app/resources/app/js/vendor-shared.js:145301:14 at file:///home/nico/Downloads/Postman/app/resources/app/js/vendor-shared.js:63343:25 at iteratorCallback (file:///home/nico/Downloads/Postman/app/resources/app/js/vendor-shared.js:63388:17) at file:///home/nico/Downloads/Postman/app/resources/app/js/vendor-shared.js:63238:20 at file:///home/nico/Downloads/Postman/app/resources/app/js/vendor-shared.js:43242:16 at iteratorCallback (file:///home/nico/Downloads/Postman/app/resources/app/js/vendor-shared.js:43819:13)
> isOperational
> :
> true
> modelIdentity
> :
> "workspace"
> raw
> :
> DexieError
> message
> :
> "Malformed error from adapter: Should always be an Error instance, but instead, got:↵```↵[OpenFailedError: UpgradeError Dexie specification of currently installed DB version is missing]↵```"
> name
> :
> "AdapterError"
> stack
> :
> "AdapterError: Malformed error from adapter: Should always be an Error instance, but instead, got:↵```↵[OpenFailedError: UpgradeError Dexie specification of currently installed DB version is missing]↵```↵    at file:///home/nico/Downloads/Postman/app/resources/app/js/vendor-shared.js:193364:5↵From previous event:↵    at Deferred.toPromise (file:///home/nico/Downloads/Postman/app/resources/app/js/vendor-shared.js:150197:19)↵    at Deferred.then (file:///home/nico/Downloads/Postman/app/resources/app/js/vendor-shared.js:150056:22)↵    at file:///home/nico/Downloads/Postman/app/resources/app/js/vendor-shared.js:193365:5↵    at file:///home/nico/Downloads/Postman/app/resources/app/js/vendor-shared.js:193516:9↵    at replenish (file:///home/nico/Downloads/Postman/app/resources/app/js/vendor-shared.js:88798:17)↵    at file:///home/nico/Downloads/Postman/app/resources/app/js/vendor-shared.js:88802:9↵    at eachOfLimit (file:///home/nico/Downloads/Postman/app/resources/app/js/vendor-shared.js:105061:36)↵    at mapValuesLimit (file:///home/nico/Downloads/Postman/app/resources/app/js/vendor-shared.js:193515:31)↵    at file:///home/nico/Downloads/Postman/app/resources/app/js/vendor-shared.js:76613:16↵    at seedDatabase (file:///home/nico/Downloads/Postman/app/resources/app/js/vendor-shared.js:193355:58)↵    at file:///home/nico/Downloads/Postman/app/resources/app/js/vendor-shared.js:144569:76↵    at file:///home/nico/Downloads/Postman/app/resources/app/js/vendor-shared.js:145511:14↵    at file:///home/nico/Downloads/Postman/app/resources/app/js/vendor-shared.js:145301:14↵    at file:///home/nico/Downloads/Postman/app/resources/app/js/vendor-shared.js:63343:25↵    at iteratorCallback (file:///home/nico/Downloads/Postman/app/resources/app/js/vendor-shared.js:63388:17)↵    at file:///home/nico/Downloads/Postman/app/resources/app/js/vendor-shared.js:63238:20↵    at file:///home/nico/Downloads/Postman/app/resources/app/js/vendor-shared.js:43242:16↵    at iteratorCallback (file:///home/nico/Downloads/Postman/app/resources/app/js/vendor-shared.js:43819:13)↵    at file:///home/nico/Downloads/Postman/app/resources/app/js/vendor-shared.js:43727:16↵    at file:///home/nico/Downloads/Postman/app/resources/app/js/vendor-shared.js:192237:18"
> __stackCleaned__
> :
> true
> __proto__
> :
> Error
> vendor-shared.js:144570 
> Object
>  "Successful ORM initialization"
> shared.js:1220 Migration bailed out due to: EXCEEDED_ATTEMPT
> shared.html:1 Uncaught (in promise) 
> OperationalError
> adapterMethodName
> :
> "find"
> cause
> :
> Error: Malformed error from adapter: Should always be an Error instance, but instead, got: ``` [OpenFailedError: UpgradeError Dexie specification of currently installed DB version is missing] ``` at file:///home/nico/Downloads/Postman/app/resources/app/js/vendor-shared.js:39852:20 at <anonymous>
> isOperational
> :
> true
> modelIdentity
> :
> "syncclient"
> raw
> :
> DexieError
> message
> :
> "Malformed error from adapter: Should always be an Error instance, but instead, got:↵```↵[OpenFailedError: UpgradeError Dexie specification of currently installed DB version is missing]↵```"
> name
> :
> "AdapterError"
> stack
> :
> "AdapterError: Malformed error from adapter: Should always be an Error instance, but instead, got:↵```↵[OpenFailedError: UpgradeError Dexie specification of currently installed DB version is missing]↵```↵    at file:///home/nico/Downloads/Postman/app/resources/app/js/vendor-shared.js:39852:20↵    at <anonymous>↵From previous event:↵    at Deferred.toPromise (file:///home/nico/Downloads/Postman/app/resources/app/js/vendor-shared.js:150197:19)↵    at Deferred.then (file:///home/nico/Downloads/Postman/app/resources/app/js/vendor-shared.js:150056:22)"
> __stackCleaned__
> :
> true
> __proto__
> :
> Error
> shared.html:1 Uncaught (in promise) 
> OperationalError
> adapterMethodName
> :
> "find"
> cause
> :
> Error: Malformed error from adapter: Should always be an Error instance, but instead, got: ``` [OpenFailedError: UpgradeError Dexie specification of currently installed DB version is missing] ``` at file:///home/nico/Downloads/Postman/app/resources/app/js/vendor-shared.js:39852:20 at <anonymous>
> isOperational
> :
> true
> modelIdentity
> :
> "user"
> raw
> :
> DexieError
> message
> :
> "Malformed error from adapter: Should always be an Error instance, but instead, got:↵```↵[OpenFailedError: UpgradeError Dexie specification of currently installed DB version is missing]↵```"
> name
> :
> "AdapterError"
> stack
> :
> "AdapterError: Malformed error from adapter: Should always be an Error instance, but instead, got:↵```↵[OpenFailedError: UpgradeError Dexie specification of currently installed DB version is missing]↵```↵    at file:///home/nico/Downloads/Postman/app/resources/app/js/vendor-shared.js:39852:20↵    at <anonymous>↵From previous event:↵    at Deferred.toPromise (file:///home/nico/Downloads/Postman/app/resources/app/js/vendor-shared.js:150197:19)↵    at Deferred.then (file:///home/nico/Downloads/Postman/app/resources/app/js/vendor-shared.js:150056:22)"
> __stackCleaned__
> :
> true
> __proto__
> :
> Error
> vendor-shared.js:224944 Error in fetching user information 
> OperationalError
> vendor-shared.js:228023 Error in fetching user information 
> OperationalError
> vendor-shared.js:121365 Unhandled rejection: AbortError: Transaction aborted
>     at IDBTransaction.<anonymous> (file:///home/nico/Downloads/Postman/app/resources/app/js/vendor-shared.js:122871:47)
>     at IDBTransaction.<anonymous> (file:///home/nico/Downloads/Postman/app/resources/app/js/vendor-shared.js:121153:23)
> shared.html:1 Uncaught (in promise) 
> OperationalError
> adapterMethodName
> :
> "find"
> cause
> :
> Error: Malformed error from adapter: Should always be an Error instance, but instead, got: ``` [OpenFailedError: UpgradeError Dexie specification of currently installed DB version is missing] ``` at file:///home/nico/Downloads/Postman/app/resources/app/js/vendor-shared.js:39852:20 at <anonymous>
> isOperational
> :
> true
> modelIdentity
> :
> "user"
> raw
> :
> DexieError
> message
> :
> "Malformed error from adapter: Should always be an Error instance, but instead, got:↵```↵[OpenFailedError: UpgradeError Dexie specification of currently installed DB version is missing]↵```"
> name
> :
> "AdapterError"
> stack
> :
> "AdapterError: Malformed error from adapter: Should always be an Error instance, but instead, got:↵```↵[OpenFailedError: UpgradeError Dexie specification of currently installed DB version is missing]↵```↵    at file:///home/nico/Downloads/Postman/app/resources/app/js/vendor-shared.js:39852:20↵    at <anonymous>↵From previous event:↵    at Deferred.toPromise (file:///home/nico/Downloads/Postman/app/resources/app/js/vendor-shared.js:150197:19)↵    at Deferred.then (file:///home/nico/Downloads/Postman/app/resources/app/js/vendor-shared.js:150056:22)"
> __stackCleaned__
> :
> true
> __proto__
> :
> Error
> shared.html:1 Uncaught (in promise) 
> OperationalError
> adapterMethodName
> :
> "find"
> cause
> :
> Error: Malformed error from adapter: Should always be an Error instance, but instead, got: ``` [OpenFailedError: UpgradeError Dexie specification of currently installed DB version is missing] ``` at file:///home/nico/Downloads/Postman/app/resources/app/js/vendor-shared.js:39852:20 at <anonymous>
> isOperational
> :
> true
> modelIdentity
> :
> "user"
> raw
> :
> DexieError
> message
> :
> "Malformed error from adapter: Should always be an Error instance, but instead, got:↵```↵[OpenFailedError: UpgradeError Dexie specification of currently installed DB version is missing]↵```"
> name
> :
> "AdapterError"
> stack
> :
> "AdapterError: Malformed error from adapter: Should always be an Error instance, but instead, got:↵```↵[OpenFailedError: UpgradeError Dexie specification of currently installed DB version is missing]↵```↵    at file:///home/nico/Downloads/Postman/app/resources/app/js/vendor-shared.js:39852:20↵    at <anonymous>↵From previous event:↵    at Deferred.toPromise (file:///home/nico/Downloads/Postman/app/resources/app/js/vendor-shared.js:150197:19)↵    at Deferred.then (file:///home/nico/Downloads/Postman/app/resources/app/js/vendor-shared.js:150056:22)"
> __stackCleaned__
> :
> true
> __proto__
> :
> Error

In image (non searchable, but readable), form : 
![image](https://user-images.githubusercontent.com/1837582/43404802-aca89ce0-9418-11e8-9c10-ab4958677745.png)

2.

Ran the command : 

(function () { console.log('Update status', localStorage.getItem('dbInitContext')); var request = indexedDB.open('postman-app'); request.onerror = (e) => { console.error('Error while opening DB', e); }; request.onsuccess = () => { console.log('DB version', request.result.version); }; })();

{"0000_initial":"finished","0001_add_archived_resources_table":"finished","0002_add_variable_sessions_table":"finished"}

undefined

DB version 10

In image form : 
![image](https://user-images.githubusercontent.com/1837582/43404911-e734ace6-9418-11e8-844b-45fecde0e12d.png)

Additional notes : 
- rollback to a previous postman version doesn't fix the problem
- happened with version 6.2.2 update, on ubuntu

**Comment by tlair123** [comment]
Thanks!

Tom Lair
Senior Business Systems Analyst, Buyer Management
708-492-7918

Insurance Auto Auctions  IAAI.COM
Two Westbrook Corporate Center, Suite 500
Westchester, IL 60154

**Comment by kamalaknn** [comment]
Hye @tlair123 

From the logs it looks like you are trying to open an older version of Postman after opening the latest version(6.2.2). The internal storage structures have changed in the latest version making it incompatible with the previous versions. 

This could have happened because you tried to open a previous version or the update process temporarily opened the current version before completing the update. 

Please try removing your current installation and downloading the latest version from - https://www.getpostman.com/apps

**Comment by kamalaknn** [comment]
Hey @tlair123 

From the logs I could see that the update process from `6.2.1` to `6.2.2` hasn't completed fully but is marked as complete leaving it in an inconsistent state.

I'm investigating this issue. Can you give me some more information here?

1. Are you signed in?
2. Do you have multiple signed in accounts in this app?

As a workaround, can you run the following script in your devtools and restart the app?
```js
(function () { localStorage.setItem('dbInitContext', null); })()
```

This would force the update process to reinitialize your app again. If you face any issues please send the logs with errors.

Thanks.

**Comment by nicolasdalsass** [comment]
Hi !

Just to mention a workaround : I deleted my local data (on ubuntu, I rm'ed `~/.config/Postman` ), relaunched, and it resynced everything from the cloud and working fine now !

**Comment by mailtoshrb** [comment]
Hi @kamalaknn, 

When I Run your Script and I still see the same issue 

See Issue:
https://github.com/postmanlabs/postman-app-support/issues/5079

**Comment by deiberchacon** [comment]
Hi,

I have the same issue since 6.1.x versions. For me, it looks like this:

![postmanissue](https://user-images.githubusercontent.com/27818529/44540030-ede6eb00-a6c2-11e8-8115-e217ae29522a.gif)

**App information:**

- Native App
- Postman Version: 6.2.5
- OS: Windows 8.1 x64

**Comment by numaanashraf** [comment]
@deiberdev Could you try the workaround detailed [here](https://www.getpostman.com/docs/v6/postman/launching_postman/installation_and_updates#troubleshooting-postman-updates)?

**Comment by deiberchacon** [comment]
@numaanashraf that removes the black squares on window resizing, but Postman doesn't start.

DevTools console shows this error:

![console_error_postman](https://user-images.githubusercontent.com/27818529/44541325-d4e03900-a6c6-11e8-985f-cec9987aec49.png)

**Comment by deiberchacon** [comment]
@numaanashraf  I deleted all the Postman local cache and installed the latest version (6.2.5), and the app starts and works well. The issue is only when updating from an old version (like 6.0.10).

This solution is described [here](https://support.getpostman.com/hc/en-us/articles/115005901149-My-Postman-app-won-t-start).

**Comment by mailtoshrb** [comment]
@deiberdev Thanks, Its Worked

**Comment by Xtremrules** [comment]
@deiberdev This method did not work for me.

**Comment by kamalaknn** [comment]
@Xtremrules The issues that you are facing might not be the same as the original issue here. Could you attach the logs that you see so we can investigate?

**Comment by Xtremrules** [comment]
@kamalaknn This is the error I see from the Developer window.
```
Initializing the global config
vendor-shared.js:83475 Initializing settings
vendor-shared.js:76788 Booting waterline models
vendor-shared.js:144334 db name postman-app
vendor-shared.js:83540 Error while seeding data. OperationalError
console.error @ vendor-shared.js:83540
vendor-shared.js:83540 Error while seeding data. OperationalError
console.error @ vendor-shared.js:83540
vendor-shared.js:83540 Error while seeding data. OperationalError
console.error @ vendor-shared.js:83540
vendor-shared.js:144362 Object "Successful ORM initialization"
vendor-shared.js:121152 Unhandled rejection: AbortError: Transaction aborted
    at IDBTransaction.<anonymous> (file:///C:/Users/GAWSB/AppData/Local/Postman/app-6.2.4/resources/app.asar/js/vendor-shared.js:122658:47)
    at IDBTransaction.<anonymous> (file:///C:/Users/GAWSB/AppData/Local/Postman/app-6.2.4/resources/app.asar/js/vendor-shared.js:120940:23)
globalError @ vendor-shared.js:121152
vendor-shared.js:83540 Error booting session OperationalError
console.error @ vendor-shared.js:83540
vendor-shared.js:83540 Error in the app boot sequence OperationalError
console.error @ vendor-shared.js:83540
vendor-shared.js:225206 Error in fetching user information OperationalError
vendor-shared.js:228285 Error in fetching user information OperationalError
```
and this is the error, If the app is started with `CMD` in Windows
```
ORM initialization successful
App events bus { name: 'booted', namespace: 'shared' }
App events bus { data:
   { adapterMethodName: 'find',
     cause:
      { adapterMethodName: 'find',
        modelIdentity: 'workspacesession',
        name: 'AdapterError',
        raw: [Object] },
     isOperational: true,
     modelIdentity: 'workspacesession',
     raw:
      { _e: {},
        _stack: 'OpenFailedError: UpgradeError Dexie specification of currently installed DB version is missing\n    at Transaction.create (file:///C:/Users/GAWSB/AppData/Local/Postman/app-6.2.4/resources/app.asar/js/vendor-shared.js:122645:31)\n    at tempTransaction (file:///C:/Users/GAWSB/AppData/Local/Postman/app-6.2.4/resources/app.asar/js/vendor-shared.js:121601:23)\n    at Table.getTransaction (file:///C:/Users/GAWSB/AppData/Local/Postman/app-6.2.4/resources/app.asar/js/vendor-shared.js:122097:17)\n    at Table.getIDBObjectStore (file:///C:/Users/GAWSB/AppData/Local/Postman/app-6.2.4/resources/app.asar/js/vendor-shared.js:122106:25)\n    at Collection._read (file:///C:/Users/GAWSB/AppData/Local/Postman/app-6.2.4/resources/app.asar/js/vendor-shared.js:123244:31)\n    at Collection.each (file:///C:/Users/GAWSB/AppData/Local/Postman/app-6.2.4/resources/app.asar/js/vendor-shared.js:123275:29)\n    at Object.find (file:///C:/Users/GAWSB/AppData/Local/Postman/app-6.2.4/resources/app.asar/js/vendor-shared.js:184466:10)\n    at _getPopulatedRecords (file:///C:/Users/GAWSB/AppData/Local/Postman/app-6.2.4/resources/app.asar/js/vendor-shared.js:111297:21)\n    at helpFind (file:///C:/Users/GAWSB/AppData/Local/Postman/app-6.2.4/resources/app.asar/js/vendor-shared.js:111734:6)\n    at _afterPotentiallyRunningBeforeLC (file:///C:/Users/GAWSB/AppData/Local/Postman/app-6.2.4/resources/app.asar/js/vendor-shared.js:149357:9)\n    at _maybeRunBeforeLC (file:///C:/Users/GAWSB/AppData/Local/Postman/app-6.2.4/resources/app.asar/js/vendor-shared.js:149331:16)\n    at Deferred._.extend._WLModel [as _handleExec] (file:///C:/Users/GAWSB/AppData/Local/Postman/app-6.2.4/resources/app.asar/js/vendor-shared.js:149333:9)\n    at Deferred.exec (file:///C:/Users/GAWSB/AppData/Local/Postman/app-6.2.4/resources/app.asar/js/vendor-shared.js:149703:10)\n    at promisified (file:///C:/Users/GAWSB/AppData/Local/Postman/app-6.2.4/resources/app.asar/js/vendor-shared.js:154507:16)\n    at Deferred.toPromise (file:///C:/Users/GAWSB/AppData/Local/Postman/app-6.2.4/resources/app.asar/js/vendor-shared.js:149989:19)\n    at Deferred.then (file:///C:/Users/GAWSB/AppData/Local/Postman/app-6.2.4/resources/app.asar/js/vendor-shared.js:149848:22)',
        inner: [Object],
        message: 'UpgradeError Dexie specification of currently installed DB version is missing',
        name: 'OpenFailedError' } },
  name: 'booted',
  namespace: 'requester' }
```

I have uninstalled and Reinstalled numerous times, It still didn't solve the problem

**Comment by Xtremrules** [comment]
Hi, @kamalaknn I have been able to resolve the Issue.
I deleted All Folders associated with **Postman** in `<Username>\AppData\Local` and `<Username>\AppData\Roaming`

**Comment by dirgagautama** [comment]
I have the same black screen's issue with @deiberdev but the solution is not working for me. Installing native apps for the first time, previously using chrome app.

Turn out the problem is Postman doesn't work with my GPU. Here is [the workaround solution](https://github.com/postmanlabs/postman-app-support/issues/4594#issuecomment-391601621). Working fine after change the shortcut to `C:\Users\<user>\AppData\Local\Postman\app-6.3.0\Postman.exe --disable-gpu`

Native app version : 6.3.0
OS : windows 8 x64

> @numaanashraf I deleted all the Postman local cache and installed the latest version (6.2.5), and the app starts and works well. The issue is only when updating from an old version (like 6.0.10).
> 
> This solution is described [here](https://support.getpostman.com/hc/en-us/articles/115005901149-My-Postman-app-won-t-start).

**Comment by tangrsgithub** [comment]
> Hi, @kamalaknn I have been able to resolve the Issue.
> I deleted All Folders associated with **Postman** in `<Username>\AppData\Local` and `<Username>\AppData\Roaming`

I solved the problem with this method.

**Comment by ayberkanilatsiz** [comment]
For OSX i clear postman cache and fixed.

Cache path: ~/Library/Application Support/Postman

**Comment by goldstar2154** [comment]
same problem after upgrading from 6.0.10 to 6.3.0. Ubuntu 16.04.05.
Fix: **delete folder /home/user_name/.config/Postman**

**Comment by kamalaknn** [comment]
Hi everyone,

Since this issue was reported, we have pushed several fixes to improve the stability of data migrations during updates. The recent updates shipped as part of Postman 7.1 released in May.

I'm closing this issue since due to inactivity.

**Comment by real-ashwin** [comment]
Had this issue today.  rm -rf ~/Library/Application\ Support/Postman fixed it.

**Comment by limoneren** [comment]
> Had this issue today. rm -rf ~/Library/Application\ Support/Postman fixed it.

Had the same issue today and uninstalling/installing didn't work, but this worked.

**Comment by leeringrose** [comment]
The same issue is here today! @kamalaknn Could you please provide the correct link to downloading the latest app so that you can be sure it's full functionality?

**Comment by numaanashraf** [comment]
@leeringrose The latest app version are available from https://www.postman.com/downloads/

**Comment by leeringrose** [comment]
@numaanashraf 
Many thanks for responding here. I tried from that page, but when I ran the installation file, the error message kept coming out.
I tried removing local cache files for the Postman, but it didn't help me at all.
