### ISSUE TITLE
Importing Collection loses unicode most Emojis

### ISSUE THREAD

**Issue by scottanthonymorin** [a85/POSTMan-Chrome-Extension#4899]
**Describe the bug**
Emojis not  exported/imported consistently across instances of "Run in Postman"

**To Reproduce**
1. Go to https://docs.smooch.io/guide/postman-collection/ 
2. Click on 'Run in Postman'
3. Open the collection in the App
4. Go to **Message Types** folder
5. Find the `POST` for "Text Message with Emojis"
6. Look at the body of the call
7. Notice that the emojis are not rendered at all. This "😍😍😍" is replace with "????????????".

I could accept that emojis are simply not supported, and move on, but if you head to the generated doc and 

1. https://documenter.getpostman.com/view/4667898/RWM6zDGd#64fa009b-a0b2-49dd-86bf-6bbfb75c75f5
2. Notice that the emojis are in the code of the API call, as expected.
3. Click on "Run in Postman" from this page.
4. Open the collection in the App
5. Locate the same API call mentioned above and notice that the emojis render as expected.

**Expected behavior**
That emojis either work across the board, or not at all.

**Screenshots**
#### When importing via "Run in Postman" in Postman docs
![postman](https://user-images.githubusercontent.com/38017293/43275722-92fdeee4-90d0-11e8-866c-6ca8bfa0e2c2.png)

#### When importing via "Run in Postman" in our docs
_Button generated via "share collection" modal_
![postman](https://user-images.githubusercontent.com/38017293/43275734-9e8cd81a-90d0-11e8-9703-38c739c16e39.png)

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version: 6.1.4
 - OS: macOS High Sierra 10.13.6

**Additional context**
We will be removing all emojis from the collection soon to not confuse potential users.

**Comment by thecuriousdev** [comment]
@scottanthonymorin thanks for reporting this issue, I am able to re-produce this.
The emojis are getting replaced with `????` when I try to import the collection with the generated `Run in Postman` button.
But its working fine if I try to import from the documentation https://documenter.getpostman.com/view/4667898/RWM6zDGd (By clicking the Run in Postman button in the documentation page)

We'll look into this and will keep you posted here.

**Comment by scottanthonymorin** [comment]
Thank you!

**Comment by scottanthonymorin** [comment]
@abhijitkane Any news here?

**Comment by harryi3t** [comment]
@scottanthonymorin This seems to be fixed. I imported the collection from https://docs.smooch.io/guide/postman-collection/ and I could see the emojis.

In case this is still not fixed please let us know.
