### ISSUE TITLE
cURL code export doesn't escape brackets in the URL

### ISSUE THREAD

**Issue by dnsbty** [a85/POSTMan-Chrome-Extension#4901]
**Describe the bug**
When exporting a request to cURL in the "Generate Code Snippets" modal, if the URL has brackets in it, the request will fail.

**To Reproduce**
1. Create a new request with the URL:`http://mydomain.com/index?page[number]=1&page[size]=10`
2. Click on the `Code` button to pop up the `Generate Code Snippets` modal
3. Choose cURL from the dropdown
4. You should get code that looks like:
```sh
curl -X GET \
  'http://mydomain.com/index?page[number]=1&page[size]=10' \
  -H 'Cache-Control: no-cache' \
  -H 'Postman-Token: 545c938e-e6e9-48de-8a71-839cd1b25a3a'
```
which upon running returns
```
curl: (3) [globbing] bad range in column 32
```

**Expected behavior**
A `\` should be put before every bracket in the URL to escape it. The above code should look like:
```sh
curl -X GET \
  'http://mydomain.com/index?page\[number\]=1&page\[size\]=10' \
  -H 'Cache-Control: no-cache' \
  -H 'Postman-Token: 545c938e-e6e9-48de-8a71-839cd1b25a3a'
```
which will give the 301 response as expected.

**Screenshots**
N/A

**App information (please complete the following information):**
 - App Type **Native App**
 - Postman Version **6.2.1**
 - OS: **macOS High Sierra 10.13.5**

**Additional context**
If Postman was open source I would have happily sent a PR 😞 Either way, thanks for providing us with such a great product!

**Comment by bvisin** [comment]
Any idea when this will be fixed?

**Comment by abhijitkane** [comment]
@bvisin @dnsbty 
Can you try this is Postman 7.2.1, with the 'Experimental Codegen Mode' flag enabled in Postman's global settings? We've introduced bug-fixes, support for two new languages (JS-Fetch and Powershell), and the ability to configure certain aspects of the generated snippet.

For this particular issue, the generated snippet is `curl -X GET "http://mydomain.com/index?page%5Bnumber%5D=1&page%5Bsize%5D=10"`.

**Comment by dnsbty** [comment]
Thanks and sorry for being slow to respond. That seems to work perfectly!
