### ISSUE TITLE
APIMATIC integrations not showing

### ISSUE THREAD

**Issue by ash007-postman** [a85/POSTMan-Chrome-Extension#4902]
![capture2](https://user-images.githubusercontent.com/41741228/43303907-810d9b48-918f-11e8-9aa5-3ab20de41003.PNG)
![image](https://user-images.githubusercontent.com/41741228/43303950-a9257fec-918f-11e8-8f5d-0ff650e64f2e.png)

 Made two integrations using Apimatic to push a collection to Github but cant see the integrations I just created in the workspace.When I try to recreate the integration I get an error that the integration already exists. Attached are the screenshots for the errors.

**Comment by ankit-m** [comment]
We have pushed a fixed for this in the latest version.
