### ISSUE TITLE
Right click "Set: <Environment>" --> "<variable>" doesn't set the value in Postman 6.2.1

### ISSUE THREAD

**Issue by wjans** [a85/POSTMan-Chrome-Extension#4903]
**Describe the bug**
When right clicking to set variable from your currently selected environment, the value is not set anymore in Postman 6.2.1.

**To Reproduce**
1. Do a simple request
2. Right click on any value in the reponse and choose "Set: \<Environment\>" --> "\<variable\>"
3. Check your environment variables afterwards and it will still contain your previous value

**Expected behavior**
The new value should have been set

**Screenshots**
![image](https://user-images.githubusercontent.com/765045/43306279-e93b2b14-917a-11e8-8e3b-23594c96896f.png)

**App information (please complete the following information):**
 - Native App
 - Postman Version 6.2.1
 - OS: macOS Sierra 10.12.6

**Additional context**
It does work when editing the environment directly.

**Comment by bhargavkaranam** [comment]
Hi @wjans,
Thank you for reporting this. We've fixed this in our canary app. You can download it from https://getpostman.com/canary

**Comment by harryi3t** [comment]
@wjans This is fixed on our canary build which you can download from https://www.getpostman.com/canary
This should be available on the production build in the next release.

**Comment by wjans** [comment]
Thanks @bhargavkaranam / @harryi3t , just tested it in the canary build and it works just fine.
