### ISSUE TITLE
Issue with Re-ordering response in Pretty-view

### ISSUE THREAD

**Issue by ash007-postman** [a85/POSTMan-Chrome-Extension#4904]
<img width="415" alt="screen shot 2018-06-21 at 11 02 23 1" src="https://user-images.githubusercontent.com/41741228/43306381-89ecad04-9198-11e8-9cbb-10b4fbce1ecd.png">
<img width="429" alt="screen shot 2018-06-21 at 11 02 28 1" src="https://user-images.githubusercontent.com/41741228/43306382-8a17be36-9198-11e8-923c-d9910a5512f3.png">

I'm on Mac OS X 12.12.6 and the version of Postman is 6.1.3. 

When I use the app to get a response the Pretty-view will automatically re-order the contents in the order of the key. Example:

Raw: { 3: {data}, 1: {data}, 2: {data} }

Pretty: { 1: {data}, 2: {data}, 3: {data} }

**Comment by MareoRaft** [comment]
Hi, I contacted support and they recommended I put my comments in this Issue...

In Postman.app (6.6.1) on macOS (10.14.1), when viewing a JSON object (to send in the body or a received one), I would like to have the ability to sort the keys alphabetically (currently, this does *not* occur). This would allow me to find what I'm looking for more easily, and to group related things together (assuming I have a good naming convention for my keys).

## Potential Caveats to sorting keys

Do any languages guarantee the preservation of JSON key order? I should think that they do not. Then changing the key order around should not be an issue. This is the only real issue I can see here: the situation where a user copies and pastes the received JSON into another location and then uses it in another capacity.

## Suggested solutions

  * When *sending* JSON in the body, there is a "Beautify" button.  There could also be a "Sort keys" button next to it.  Alternatively, there could be configuration in the settings where the user can enable/disable key-sorting onBeautify.

  * When *receiving* JSON in response, there could similarly be a sort keys button or configuration to make the "Pretty" option always sort the keys.

All of the solutions I have suggested allow the keys to be sorted or unsorted.  I think it's important that any user can get the behavior that suits their own needs.  So it can be a win-win.

**Comment by coditva** [comment]
Hi! This issue is fixed. Please update to the latest Postman app (version `7.20.0`).

![image](https://user-images.githubusercontent.com/8445768/76518167-a67ea600-6484-11ea-9257-1f7a0ba0b4c1.png)
