### ISSUE TITLE
Monitor not able to replace environment variable before sending request

### ISSUE THREAD

**Issue by aambekar91** [a85/POSTMan-Chrome-Extension#4907]
I added a new environment variable {{api_version}} and its value is shown as below:

![screen shot 2018-07-27 at 8 44 31 am](https://user-images.githubusercontent.com/39306378/43324290-629f0f04-9179-11e8-927c-cfabc73a8551.png)

This value gets replaced at run-time when I use the "Runner" to run all requests. However, the "Monitor" is not able to replace the same variable which results in bad request-

![screen shot 2018-07-27 at 8 47 09 am](https://user-images.githubusercontent.com/39306378/43324451-c08a179e-9179-11e8-8a71-7a08435e8930.png)

Postman for Mac
Version 6.1.4
OS X 17.7.0 / x64

**Comment by harryi3t** [comment]
Hi @aambekar91,
Can you make sure the monitor was created with the same environment as the one which is selected in the App?
To check this, go the monitor page and click on `...` and then click on 
<img src="https://user-images.githubusercontent.com/5207331/43353168-e014829a-924e-11e8-8d29-20976c14e62b.png" height="200px"/>


![image](https://user-images.githubusercontent.com/5207331/43353164-d85353c4-924e-11e8-8675-fd1552eaacad.png)

Make sure the `Environment` dropdown has the correct environment selected.

**Comment by aambekar91** [comment]
Hi @harryi3t,

Yes, I've made sure that the right environment is selected. I also made sure that the variable not getting substituted (api_version) is declared in that environment.

**Comment by aambekar91** [comment]
Hi @harryi3t,

It seems that the monitor has picked up the changes for the variable and is now working as expected. You may close this issue. Thank you.
