### ISSUE TITLE
The 'Clear All' button in History doesn't explicitly say that all history (not just the filtered, visible results) will be deleted

### ISSUE THREAD

**Issue by abhijitkane** [a85/POSTMan-Chrome-Extension#4910]
If you're looking at a filtered history in the app, the 'Clear All' link could be interpreted to mean 'delete all the history items that are currently visible. The modal window (attached) 
<img width="494" alt="screen shot 2018-07-28 at 09 32 48" src="https://user-images.githubusercontent.com/681190/43352923-8b0b1cfa-9249-11e8-9601-a3dcc10c4987.png">
isn't too clear either. But proceeding with this action deletes all history items in the workspace.

Postman should either explicitly say "not just filtered requests" in the warning, or only delete the ones that are visible.

**Comment by DannyDainton** [comment]
The copy has changed for this in the latest version to include the warning that it will delete all the history in the Workspace.

<img width="623" alt="image" src="https://user-images.githubusercontent.com/17089546/161565287-9bd3ff71-e91f-4d6b-b061-656bd815320f.png">
