### ISSUE TITLE
Dark screen during use

### ISSUE THREAD

**Issue by DmitrySkibitsky** [a85/POSTMan-Chrome-Extension#4914]
**Describe the bug**
After opening the application and some time of work, a dark screen appears. Some patterns are not found

**Screenshots**
![deepinscreenshot_select-area_20180729194918](https://user-images.githubusercontent.com/20288556/43368653-4a01ab22-9369-11e8-9e7d-35332dcdfc06.png)

**App information (please complete the following information):**
 - App Type Chrome App
 - Postman Version 6.2.2-1
 - OS: Linux 4.16.13-2-ARCH #1 SMP PREEMPT Fri Jun 1 18:46:11 UTC 2018 x86_64 GNU/Linux

**Additional context**
video
https://drive.google.com/open?id=1uHc-WJ6PSfLvzGhVqfESjHpFZ1YAW93m

Maybe it's something to do with the poor equipment?

**Comment by SamvelRaja** [comment]
Possible solution https://github.com/postmanlabs/postman-app-support/issues/4594#issuecomment-391601621

Feel free to reopen the issue if this doesn't solve it.

**Comment by DmitrySkibitsky** [comment]
@SamvelRaja 
```bash
[Desktop Entry]
Name=Postman
Comment=Build, test, and document your APIs faster
Exec=/usr/bin/postman --disable-gpu %U
Terminal=false
Type=Application
Icon=postman
Categories=Development;Utility;
X-Deepin-CreatedBy=com.deepin.dde.daemon.Launcher
X-Deepin-AppID=postman
```

Unfortunately it didn't help me.
