### ISSUE TITLE
Long collection names deform selector in 'Add to workspace' modal

### ISSUE THREAD

**Issue by godfrzero** [a85/POSTMan-Chrome-Extension#4917]
**Describe the bug**
The input checkbox in the 'Add to workspace' modal deforms into a rectangle if the collection name is too long.

**To Reproduce**
1. Open the Postman app
2. Select any workspace, switch to the Build view
3. Create a new collection with a really long name, For example: `A collection with a really long name really long name really long name really long name really long name really long name really long name really long name really long name really long name really long name really long name really long name`
4. Switch to another workspace, move to the Browse view
5. Click the `Add to workspace` button in the top-right corner
6. In the modal which opens, scroll until you see the collection with a really long name
7. Note how the input checkbox is now an input checkrectangle

**Expected behavior**
The input checkbox should not deform, no matter what.

**Screenshots**
<img width="517" alt="screen shot 2018-07-30 at 12 31 15 pm" src="https://user-images.githubusercontent.com/2700229/43382166-8f383f5e-93f4-11e8-84b4-7c916ab1de4d.png">

**App information (please complete the following information):**
 - Native Mac App
 - 6.2.3-beta01
 - OS: macOS High Sierra 10.13.6

**Comment by harryi3t** [comment]
@godfrzero Works in the latest version of Postman 6.5.2
