### ISSUE TITLE
Unable to import a collection

### ISSUE THREAD

**Issue by NizMech** [a85/POSTMan-Chrome-Extension#4918]
Importing files via the IMPORT-function fails

**To Reproduce**
1. Click the import button
2. Select the data file (file .json)
3. Open file
4. Error

**Expected behavior**
The file should be imported.

**App information (please complete the following information):**
 - App Type :Chrome App
 - Postman-win64-6.1.4
 - Windows 7

![1](https://user-images.githubusercontent.com/41567545/43384180-c17d4bda-93cc-11e8-80c5-a32eb153dc81.png)

**Comment by NizMech** [comment]
It's working now!

**Comment by thecuriousdev** [comment]
@NizMech happy to hear that :) but any idea why its failed initialy?

**Comment by NizMech** [comment]
@thecuriousdev : I just deleted all the collections and environments I had in my workspace and retried to import .. And it worked.
