### ISSUE TITLE
Postman App Performance Lag

### ISSUE THREAD

**Issue by ash007-postman** [a85/POSTMan-Chrome-Extension#4919]
I'm using the desktop native app on a Windows 10 machine. I've closed all tabs within the collection and rebooted my machine. I'm authoring in form-data fields specifically in the Body section of a POST request of the collection and noticing a very long lag (~10-20 seconds) from keystroke to the character appearing in the text box. My requests are at 176 in that one collection so I understand I may be pushing the tool to the limits. However, please advise best practices to improve the performance of the tool on our end. Is there a way we should say author outside and can import it in? All of my content is written, I'm just pulling it in from another source via a combination of bulk edit and copy/paste.

**Comment by vjamwec13579** [comment]
I have the "new" desktop Windows app, I have installed it / uninstalled it and it runs poorly.  My laptop is a 4 core CPU with 16 GB of RAM running Windows 10 Enterprise.  

It takes several minutes for it to respond to a mouse click.  When it does finally respond, it takes ages to search.  The interceptor feature was removed.  This is a horrible experience that I would not wish on my worst enemy. When does a company decide to remove critical functionality?  Is it so you can make $$$ from support cases?  I really wish you added to the Chrome version rather than deprecating it.  You seem to be moving backward in time, apps are going away from the desktop, not to the desktop.

**Comment by lifewingmate** [comment]
I'm a paying client (Postman Pro) and the one who reported the original lag issue. I'm running Windows 10 Enterprise on a laptop with a Core i7 processor and 16 GB of RAM, 64-bit OS.

**Comment by a85** [comment]
We are making some fundamental improvements to Postman's response rendering including using the Monaco editor for better memory optimization and rendering speeds. You can try out these updates in the Canary channel here: https://www.getpostman.com/downloads/canary

<img width="1790" alt="Screenshot 2019-06-12 12 19 53" src="https://user-images.githubusercontent.com/653409/59379813-72ffc700-8d0c-11e9-9da4-5c9ce0492dc4.png">

You can test it out with an API that we have created on the Postman Echo service. Examples here: https://documenter.getpostman.com/view/55577/S1ZudWWm?version=latest

**Comment by rhzs** [comment]
It's 2020, I think it is the same. I used postman extensively. Insomnia is still better experience when switching tabs. I am sorry but, you can feel it too. IMHO.

**Comment by nbon12** [comment]
Still lagging on windows, as high as a 1.5 second delay after typing things for things to appear in the URL bar.

Switching tabs takes about 2 seconds after clicking the button to the other tab.
Switching to a different request from the side-pane takes about 2 seconds.
Maybe it's a windows defender thing?

**Comment by mccannt** [comment]
We have made some performance improvements in the past few months. 
Can anyone having issues please try the most recent version of the application and let us know if they are still seeing an issue?

**Comment by n3nikita** [comment]
Windows 10. Core i7 and 16GB of RAM. 
Postman lags so much. 

![image](https://user-images.githubusercontent.com/22433209/104261125-24388700-5485-11eb-8e55-d8fe7fa40ff2.png)

Postman Canary seems to be less laggy

**Comment by lucasdietrich** [comment]
I had a similar issue with a not so big postman file (1 collection with 30 requests) on Windows 10, the IDE was irregularly laggy when travelling through the app.

Changing the "Performance options" settings to "best performances" solved the problems for me. I did not spend time to identify which option caused the lags (maybe text smoothing, idk).

![image](https://user-images.githubusercontent.com/42321393/112506533-2759c880-8d8e-11eb-9ad8-b16f0fedc956.png)

That could be a idea.

PS: today it's laggy again on my side, this was apparently not the reason on my side.

**Comment by jviotti** [comment]
Merging this ticket with https://github.com/postmanlabs/postman-app-support/issues/8761
