### ISSUE TITLE
Cannot save request - user not part of workspace

### ISSUE THREAD

**Issue by dbalthassat** [a85/POSTMan-Chrome-Extension#4920]
**Describe the bug**
After having create or update a request, I can not save it.

**To Reproduce**
1. Open the window to create a new request or to update an existing one.
2. Change something in the window (the request URL for example).
3. Click on 'Save' (or Ctrl+S).
4. If it is a new request, the 'Save request' window opens. Then select a collection and click on 'Save to <collection name>'.

**Expected behavior**
The request must be saved or updated in the collection. 
It is not, and the developer console shows this message: "Error in pipeline for creating request Error: permissionsHandler: User '4433837' is not part of workspace '29ba1c6f-43ab-4e23-8a6c-27c39a57a069'"

**Comment by kamalaknn** [comment]
Hi @dbalthassat 

1. Can you give me more info on what led to this flow?
2. Are you logged in at this moment?
3. Can you try logging out and logging back in?

**Comment by inestyne** [comment]
Same thing, CTRL+S no longer working, logged in, and i can't log out now without deleting local data which means i'm very badly stuck

**Comment by a85** [comment]
Too generic an issue to investigate further. Closing this as we have made changes in 7.0 through the role based access control system.
