### ISSUE TITLE
Skipping requests in pre-script and reporting skipped tests

### ISSUE THREAD

**Issue by jrsiegs** [a85/POSTMan-Chrome-Extension#4922]
There have been many requests for there to be an option to skip a request by putting something in the pre-request scripts. If this does get implemented, it would be very helpful to have a graphic next to the "passed" and "failed" graphics in the test runner that shows how many tests were skipped. It would also be great to have this detail in Newman in the chart that is shown after every run.

## App Details:
```
Postman for Windows
Version 6.2.2
win32 10.0.16299 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there: This has not been implemented yet
 2. Expected behaviour: Report how many tests were skipped in the runner.

**Comment by chrisdeso** [comment]
Friendly bump 😄

**Comment by jrumbinas** [comment]
Please note there are multiple use cases:

1. **Quarantined and ignored tests**. This would prevent item (request or folder with all it's scripts) from being executed while still allowing it to rest within the collection. Postman Collection v2.1 doesn't have any fields to support that. Any of the following fields on _Item_ and _Folder_ types would work: enabled, disabled, ignored, etc.

2. **Conditional runtime request execution**. This would help a lot with the complex configurations and workflows. E.g. execute request if specific environment varaible value is set. Conditional execution would address _postman.setNextRequest_ limitations, i.e. the need to know the following request name (which is very error prone when the time comes to re-order requests).

**Comment by WendallHersh** [comment]
Another Friendly bump as this is a feature that would help significantly when implementing for APIs. 

I currently import ALL calls from swagger and then I add tests as a I can. A pm.test.skip() or something would be nice to have in the  pre-request in order to skip the tests that have not been touched yet by testing. I know I could use a separate collection for not completed tests but it becomes a pain moving and creating new folders in the new collection. Maintenance is a big issue.

**Comment by shamasis** [comment]
`pm.test.skip()` is available in sandbox. https://github.com/postmanlabs/postman-app-support/issues/2698 @WendallHersh

**Comment by shamasis** [comment]
There is an argument that assertions should not be manipulatable from outside. Hence, the combination of ideas in this thread: https://community.getpostman.com/t/bypass-or-skip-tests-for-a-request/2704/3 coupled with the new feature to be selectively able to run parts of collections in runner should solve this. Closing.
