### ISSUE TITLE
Can no longer set environment variables by right clicking on highlighted text

### ISSUE THREAD

**Issue by wreddin** [a85/POSTMan-Chrome-Extension#4923]
With v6.2.2, I am no longer able to set variables by using the Right Click + Set:  option.  This now results in the initial value being cleared and the current value remains unchanged.

Here are my environment values before SET
![environment values before set](https://user-images.githubusercontent.com/25037380/43414096-caa7978c-93ff-11e8-9fd2-7f0e7c460e8f.PNG)

Right click > SET
![set environment value](https://user-images.githubusercontent.com/25037380/43414127-e0f917cc-93ff-11e8-83ff-dda705bea502.PNG)

Here are my values after SET.
![environment values after set](https://user-images.githubusercontent.com/25037380/43414165-fd347602-93ff-11e8-81b2-89996e02e88c.PNG)

**Comment by prashantagarwal** [comment]
@wreddin We have released the fix for this on our canary app and will soon be releasing it on our stable apps. By the time you can download canary from https://www.getpostman.com/canary

**Comment by wreddin** [comment]
I've tried it on the canary build and I have confirmed that it correctly sets the Current Value.  Thanks!
