### ISSUE TITLE
Set:Environment variable in dropdown doesn't work on 6.2.1-6.2.2

### ISSUE THREAD

**Issue by Postman-Gabriel** [a85/POSTMan-Chrome-Extension#4924]
**Describe the bug**
When right clicking on values in the response body of a request, and trying to use the drop-down menu to set the value of the variable, it doesn't populate properly.

REGRESSION: Works on 6.1.4, not after 6.2 update

**To Reproduce**
1. Find a request body with an environment
2. Highlight some data
3. Right-click to try and set the variable with dropdown

**Expected behavior**
Expected to populate a variable with a value

**Screenshots**
<img width="951" alt="screen shot 2018-07-30 at 11 34 22 am" src="https://user-images.githubusercontent.com/40899145/43416274-b1927d1a-93ec-11e8-8cc4-8f507dd324f8.png">
<img width="694" alt="screen shot 2018-07-30 at 11 35 17 am" src="https://user-images.githubusercontent.com/40899145/43416298-bcdbe4f4-93ec-11e8-9975-c040a2120773.png">

**App information (please complete the following information):**
 - App Type Native app
 - Postman Version  6.2.1-6.2.2
 - OS: Mac

**Comment by bhargavkaranam** [comment]
This has been fixed in the canary release. You can download it from https://getpostman.com/canary
Incase, there's still an issue, please use the thread of issue #4903
