### ISSUE TITLE
Long strings are altered in environment when saved

### ISSUE THREAD

**Issue by Postman-Gabriel** [a85/POSTMan-Chrome-Extension#4926]
**Describe the bug**
Strings that are of a certain length are saved as a certain subset of the string, plus a "...". This seems to be a visual thing that mistakenly gets saved to the environment instead of the actual value of the string.

**To Reproduce**
1. Create a long string
2. Attempt to save it
3. See error

**Expected behavior**
Expected to be able to use the entire string, as saved, instead of as concatenated

**Screenshots**
![](https://postman.zendesk.com/attachments/token/B0tFFePEDTOlgTvcdqH4GIxm0/?name=Screen+Shot+2018-07-26+at+8.28.29+PM.png)

**App information (please complete the following information):**
 - App Type: Native app
 - Postman Version: 6.2.1
 - OS: Mac OsX

**Comment by iftachk** [comment]
👍

**Comment by harryi3t** [comment]
@iftachk This is fixed in the latest version of Postman 6.2.3
