### ISSUE TITLE
Error View On Windows 8.1 64 Bit

### ISSUE THREAD

**Issue by jpaulus30** [a85/POSTMan-Chrome-Extension#4927]
## App Details:

```
Postman for Windows 8.1
Version 6.2.2
winx64
```

## Issue Report:
 1. I cannot view GUI postman after update postman 6.2.2
 2. See the atachment for detail
![image](https://user-images.githubusercontent.com/26064592/43438355-0d2afab4-94b8-11e8-9fa6-e715f9487aa8.png)

**Comment by SamvelRaja** [comment]
Possible solution https://github.com/postmanlabs/postman-app-support/issues/4594#issuecomment-391601621

Feel free to reopen this if this doesn't solve.
