### ISSUE TITLE
Can't get Postman installed on my desktop

### ISSUE THREAD

**Issue by nsangeet18** [a85/POSTMan-Chrome-Extension#4928]
Postman app 6.2.2 will not open when installed.
Windows 8.1 Pro 64-bit

**To Reproduce**
1. Download and run the installer.
2. Postman is installed but app doesnt open.
3. Crash dump was seen in C:\Users\<User>\AppData\Local\CrashDumps

**Expected behavior**
Postman app is installed and could launch it sucessfully.

**Screenshots**
![image](https://user-images.githubusercontent.com/39327125/43443077-35bf184a-94e3-11e8-9bc4-39d9dae0edcb.png)
[Postman.exe.7492.txt](https://github.com/postmanlabs/postman-app-support/files/2244106/Postman.exe.7492.txt)(Changed dmp to txt for upload)
![image](https://user-images.githubusercontent.com/39327125/43443128-556c2dcc-94e3-11e8-928a-737112b319fb.png)

Note: Please make previous versions available for download.

**Comment by SamvelRaja** [comment]
@nsangeet18 Could you provide me more insights on this issue?
Was you not able to open the app at all? If it is showing a crash warning, could you share a screenshot of it.

**Comment by nsangeet18** [comment]
I ran the installer and the postman GUI is blank showing me the process wheel.The second snapshot is the one which shows gui blank. There was no crash warning. Could you chk the dmp attached to see if you have any useful info.

**Comment by SamvelRaja** [comment]
@nsangeet18  Seems like a GPU issue we are facing.
Can you try the workaround provided in https://github.com/postmanlabs/postman-app-support/issues/4594#issuecomment-391601621


Feel free to re-open this issue, if this doesn't solve.

**Comment by nsangeet18** [comment]
Yes Im currently running Postman 6.2.2 with GPU mode disabled and it worked fine for me.
Hope there is going to be a future fix available soon.
Thanks!
