### ISSUE TITLE
Labels for workspaces

### ISSUE THREAD

**Issue by ankit-m** [a85/POSTMan-Chrome-Extension#4929]
**Is your feature request related to a problem? Please describe.**
Currently, I can distinguish my workspaces based on `team` and `personal`. Within these categories it becomes difficult to distinguish between workspaces (name being the only differentiator).

**Describe the solution you'd like**
Labels will allow for better organization and visibility of workspaces. In future, searching by labels can also be supported.

**Describe alternatives you've considered**
Using markers in the workspace name - `[PROJECT-A]`, `#wip`, etc.

**Comment by akshay-kulkarni-03** [comment]
You can now tag workspaces, collections and other entities for easier navigation & discoverability. To learn about it more checkout this blogpost: https://blog.postman.com/introducing-tags-the-new-way-to-navigate-in-postman/
