### ISSUE TITLE
Postman Window blanc with Windows 10 Pro 64Bit (only works with Win 8 compatibility settings) 

### ISSUE THREAD

**Issue by michaelmpschubert** [a85/POSTMan-Chrome-Extension#4930]
When I start Postman-win64-6.2.2 (after allready installed) on Windows 10 Pro 64 Bit (Build Version 17134.165), Intel HD Graphics 3000, the Postman Pogramm Window ist completely empty.
The only way to see the Postman GUI is to start the App with Windows 8 compatibility mode under Windows 10. Thats not sufficient, especially for new or unexperienced user!
Thanks for your investigations.

**To Reproduce**

**Expected behavior**

**Screenshots**

**App information (please complete the following information):**
 - App Type [e.g. Chrome App, Native App]
 - Postman Version [e.g. 6.0.1]
 - OS: [e.g. macOS High Sierra 10.13.2]

**Additional context**

**Comment by SamvelRaja** [comment]
Possible solution https://github.com/postmanlabs/postman-app-support/issues/4594#issuecomment-391601621

Feel free to reopen this if it is not fixed still.
