### ISSUE TITLE
Allow monitors to use current value in sessions for private monitors

### ISSUE THREAD

**Issue by deepakpathania-zz** [a85/POSTMan-Chrome-Extension#4933]
Consider the following scenario:
- I have a collection and environment shared in multiple workspaces.
- I do not want to share my credentials in the team workspace, so I only populate the current value in my environment leaving initial value blank so that the in the team workspace, only keys are shared and people can generate their own values based on that. (Sessions work great for this.)
- Now I want to monitor the original collection in my workspace, note that this is not a team monitor and I want to run it only for myself. 

In this scenario, my monitor still picks values from the initial value in the environment which is left blank as described above. If I populate the initial values, they would be shared in the team workspaces as well. 

Ideally, there should be an option to persist the session values for monitor run as well since it is there in the collection runner, I would expect the behavior to be consistent in both.

**Comment by sankalp0o** [comment]
@deepakpathania Current value aren't synced and therefore can't be used by monitors. I feel it'll be best to use separate environment for this. Workarounds for using the same environment for two completely different use cases wouldn't make sense. I'm closing the issue but feel free to comment if you have any thoughts on this.
