### ISSUE TITLE
204 status code is reported as "error"

### ISSUE THREAD

**Issue by 0x6B386F** [a85/POSTMan-Chrome-Extension#4936]
Please read through the [guidelines](https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues) before creating a new issue.

**Describe the bug**
204 status code is reported as "error"

**To Reproduce**
1. Click to "Send" button with request to API which returns status code 204.. 

**Expected behavior**
Show headers, status code, etc. Not error,

**App information (please complete the following information):**
 - Postman for Linux 
 - Version 6.1.4
 - linux 4.9.0-7-amd64 / x64

**Comment by 0x6B386F** [comment]
Sorry, seems to be duplicate of #2418 :(

**Comment by prashantagarwal** [comment]
Closing as duplicate.
