### ISSUE TITLE
Postman does not open, even reinstalling.

### ISSUE THREAD

**Issue by andersonmendesdev** [a85/POSTMan-Chrome-Extension#4939]
**Describe the bug**
The postman only opens normally the first time after the installation. I thought it was windows 8.1, so I reinstalled windows and the problem persists. I tried as native x64 / 86 versions.

**To Reproduce**
1. Go to open app.
Result : Fail
1. Go to open shell.
Result: Fail

**Expected behavior**

**Screenshots**
[Image problem](https://uploaddeimagens.com.br/imagens/postaman-jpg)
[Image problem 2](https://uploaddeimagens.com.br/imagens/image-jpg-7fe08513-7fa5-4028-a6ec-bd003983b0e7)

**App information (please complete the following information):**
 - App Type : Native App
 - Postman Version:  6.2.2 x64/86
 - OS: Windowns 8.1 pro x64

**Additional context**
I executed with local account and administrator, in both it does not open.

**Comment by SamvelRaja** [comment]
Seems like a GPU issue, workaround https://github.com/postmanlabs/postman-app-support/issues/4594#issuecomment-391601621

Feel free to reopen this if it is not fixing it.
