### ISSUE TITLE
Duplicating an example doesn't lead back to the request 

### ISSUE THREAD

**Issue by sivcan** [a85/POSTMan-Chrome-Extension#4941]
**Describe the bug**
On duplicating an example tab, the button to lead back to the request doesn't work.

**To Reproduce**
1. Add an example for a request
2. Right-click the tab and duplicate it
![image](https://user-images.githubusercontent.com/12631777/43507145-ea53d42a-9589-11e8-8bfe-00f2494f9e7e.png)
3. In the duplicated tab press the button (with the request name on it) to go back to the request editor
![image](https://user-images.githubusercontent.com/12631777/43507168-fb96099c-9589-11e8-84a9-df87a5aaa366.png)
It doesn't lead back to the request. 

**Expected behavior**
After duplicating the example tab and on clicking back, it should go back to the original request

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version: 6.2.1
 - OS: macOS High Sierra 10.13.4

**Comment by sujayvenaik** [comment]
This issue has been fixed and is available on the stable channel (v6.4.x).
You can update the app to the latest version.

Thanks again for writing in and reporting this issue.
