### ISSUE TITLE
Certificate Domain Validation

### ISSUE THREAD

**Issue by thyn** [a85/POSTMan-Chrome-Extension#4942]
**Describe the bug**

Situation. I have server with certificate for domain A. If I make request with Domain B I have certificate error. That's what I need. If I make Request again - I don't have error.

**To Reproduce**
1. Create Get Request to server https://google.com
2. Set host header vasya.com (or any)
3. Click Send 
   We have validation error
4. Click Send again - we don't have error

**Expected behavior**

We always have error

**App information (please complete the following information):**
 - App Type  Native App
 - Postman Version 6.2.2
 - OS: Windows Server 2016

**Comment by numaanashraf** [comment]
@thyn Thanks for reporting. We are able to replicate this issue at our end and are working towards fixing this.

**Comment by codenirvana** [comment]
@thyn This is fixed in the latest version of the Postman App.
