### ISSUE TITLE
Select multiple requests And change their URI

### ISSUE THREAD

**Issue by maitmansour** [a85/POSTMan-Chrome-Extension#4943]
**Is your feature request related to a problem? Please describe.**
I always want to Select multiple requests (Not possible right now) and change their URI

**Describe the solution you'd like**
1- I want to select multiple Requests
2- I'd like to change their URI (for example from 127.0.0.1 to another URI)

**Additional context**
Sometimes i need to duplicate multiple requests so i can test them in an other server, but i have to change the one by one

**Comment by vkaegis** [comment]
@maitmansour Thanks for writing in! This has been a long requested feature and is definitely on our cards. No ETA just yet, but stay tuned for updates!

**Comment by a85** [comment]
This should be possible with the Find and Replace feature: https://learning.getpostman.com/docs/postman/find_replace/
