### ISSUE TITLE
Postman 6.1.x fails to launch on Ubuntu 16.04

### ISSUE THREAD

**Issue by wernerm** [a85/POSTMan-Chrome-Extension#4944]
**Describe the bug**

Postman 6.1.x fails to launch on Ubuntu 16.04. 

The following error is thrown: 

> Postman: error while loading shared libraries: libnode.so: cannot open shared object file: No such file or directory

A previous Postman build (6.0.10) works just fine, so I guess something changed in the build process or version of Electron. 

**To Reproduce**

1. Launch Postman 6.1.x on Ubuntu

**Expected behavior**

Postman should launch

**App information (please complete the following information):**
 - Native App
 - Version: 6.1.3, 6.1.4
 - OS: Ubuntu 16.04

**Comment by numaanashraf** [comment]
@wernerm This is a known issue and we are tracking the upstream Electron issue https://github.com/electron/electron/issues/4583

**Comment by numaanashraf** [comment]
@wernerm This is resolved in the latest version of Postman. If you are on Linux, we recommend using our Snap package - https://snapcraft.io/postman
