### ISSUE TITLE
When exporting to cURL, escaping double quotes "" in headers is wrong

### ISSUE THREAD

**Issue by chriscoomber** [a85/POSTMan-Chrome-Extension#4945]
**Describe the bug**
See title

**To Reproduce**
Suppose my Postman request has a header:

```
Foo: "bar"
```

If I convert this to cURL I get:

```
curl -X GET \
  'http://hostname/path/to/resource' \
  -H 'Foo: \"bar\"'
```

This is incorrect, as the header is enclosed in single quotes, so the `\` before each `"` are spurious.

**Expected behavior**
```
curl -X GET \
  'http://hostname/path/to/resource' \
  -H 'Foo: "bar"'
```

or

```
curl -X GET \
  'http://hostname/path/to/resource' \
  -H "Foo: \"bar\""
```

**App information (please complete the following information):**
 - App Type: Windows client
 - Postman Version v6.2.2
 - OS: Windows

**Comment by abhijitkane** [comment]
@chriscoomber Not able to reproduce this in v7.x of Postman.

Also, in Postman 7.2.1, we've introduced bug-fixes, support for two new languages (JS-Fetch and Powershell), and the ability to configure certain aspects of the generated snippet. This can be enabled with the 'Experimental Codegen Mode' flag enabled in Postman's global settings. In the new cURL snippet, the headers are enclosed in double quotes: `-H "h1: \"bar\""`
