### ISSUE TITLE
Right click in response window to set environment value does not set variable

### ISSUE THREAD

**Issue by paulsperanza** [a85/POSTMan-Chrome-Extension#4947]
Please read through the [guidelines](https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues) before creating a new issue.

**Describe the bug**
I can usually select text and right click in the response window to set an environment variable. This has stopped working.

**To Reproduce**
1. Run a API call
2. Select text from response
3. Right click and when menu appears click "Set environment_Name environment _variable"

**Expected behavior**
The environment variable in the environment is set with highlighted text

**Actual behavior**
The environment variable in the environment is not set with highlighted text

**App information (please complete the following information):**
 - App Type Native App
 - Postman Version 6.2.2
 - OS: Windows 10 Pro 10.0.16299

**Comment by bhargavkaranam** [comment]
Hi @paulsperanza,
This has been fixed in the canary release. You can download it from https://getpostman.com/canary

**Comment by bbuchan10** [comment]
I am also seeing this. do you have an ETA on production release?

**Comment by harryi3t** [comment]
@paulsperanza @bbuchan10 This is fixed in the latest version of Postman 6.2.3
