### ISSUE TITLE
Personal workspaces Team section in workspace dropdown while app is syncing

### ISSUE THREAD

**Issue by ankit-m** [a85/POSTMan-Chrome-Extension#4948]
**Describe the bug**
After sign-in, while the app is syncing, all my **personal** and **joined** team workspaces show up in the *Team* tab of the workspace selector in `Workspaces you can join` section.

**To Reproduce**
1. Create team and personal workspaces
2. Wait for app to be in sync
3. Sign out
4. Sign in
5. Observe workspaces dropdown

**Expected behaviour**
Workspaces should show up in the correct sections even while syncing.

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version: 6.2.3
 - OS: macOS High Sierra 10.13.5

**Comment by kamalaknn** [comment]
This is fixed in Postman v7
