### ISSUE TITLE
Lost collections and history??

### ISSUE THREAD

**Issue by eappell** [a85/POSTMan-Chrome-Extension#495]
I've been using Postman for a few weeks, and had saved several collections, and purchased the jetpack.  I had both the packaged app and the inline extension installed.  I went to remove the extension, but accidentally removed the packaged app (it wasn't called 'packaged app' in my list of apps).  When I realized I had removed the packaged app, I removed the extension, without first re-installing the packaged app.  Once I did re-install it, I started it up and have no collections or history.  My name appears on the top of the window, so I'm logged in, but there are no collections available to download.  Where would those be??  Is there a file I can import?  It would be very frustrating to have to re-create all of the collections I had, so I'm desperately hoping there's a way to recover that data...  BTW, I haven't yet restarted Chrome since re-installing Postman, if that helps at all...?

**Comment by mkmoisen** [comment]
Sorry to kick a dead horse, but this has happened to me twice in the last 3 months.

**Comment by sandy-adi** [comment]
Just happened to me today :(

**Comment by sdnts** [comment]
If you have Sync enabled, can you head over to https://app.getpostman.com/dashboard/collections/private?expand=1 and check if your collections are intact? If so, logging out and logging back in should restore all your collections.

**Comment by vishnuawasthi** [comment]
I lost my all collections today.

**Comment by TomBaxter** [comment]
Didn't lose exactly, but sync hopelessly mangled the collection I've been working on all day. :(

**Comment by markSbrandt** [comment]
weird thing i noticed i'm on a mac ... when i used spotlight search and opened postman my history was gone ... when I opened via chrome > apps > postman the history was there ... whooo!

**Comment by sdnts** [comment]
@TomBaxter Can you email us at help@getpostman.com?
@markSbrandt If you have both the Chrome & Mac app, maybe you weren't signed in on the Mac App?

**Comment by MrMichaelFournier** [comment]
Hi same thing here. I manage to recover the file chrome-extension_fdmmgilgnpjigdojojpjoooidkmcomcm_0.indexeddb.leveldb
and all folders inside it.
How do I restore from such files ?

**Comment by sdnts** [comment]
@Michaos The file you have, is for the Postman Interceptor extension, not the Chrome App. The Chrome App's ID is `fhbjgbiflinjbdggehcddcbncdddomop`
Do you use Sync? If so, you should be able to log in again and all your collections should be restored.
If not, all data is stored locally on the Chrome app, but we aren't sure what causes Chrome to clear this data sometimes. I'd recommend switching to our native apps, to make sure your workflow isn't affected when Google drops support for Chrome Apps later this year.

**Comment by MrMichaelFournier** [comment]
Oh sorry I didn't pay atention to the exact file name. The file I have is named
**chrome-extension_fhbjgbiflinjbdggehcddcbncdddomop_0.indexeddb.leveldb**
I didn't used sync I will now but you think I can restore my collections with that file ?

**Comment by sdnts** [comment]
Have you tried the solution described [here](https://github.com/postmanlabs/postman-app-support/issues/569#issuecomment-75217738) for OSX or [this](https://github.com/postmanlabs/postman-app-support/issues/569#issuecomment-96316072) for Windows?

**Comment by MrMichaelFournier** [comment]
Sadly, I don't have any backup of this file.

**Comment by adammendoza** [comment]
I just lost about 300 items in my collection. :(

**Comment by sdnts** [comment]
@adammendoza If you have Sync enabled, can you email us at help@getpostman.com?
Without Sync, all your collections are stored locally, so unfortunately, there isn't anything we can do :(

**Comment by natty4GitHub** [comment]
#PIB Lost all rest call customized request. To my surprise, i lost the installation of postman altogether after security updates and restart. I've no clue.

**Comment by kpmani81** [comment]
@madebysid my chrome got recently upgraded and my "postman rest client" got deleted automatically. i had lot of collections how to recover that now? there is no option in old postman rest client to sign in and save. where it will be stored locally in my machine

**Comment by HeadlyvonNoggin** [comment]
@madebysid Am I correct that Postman Interceptor only works with the Postman Chrome App and not with the native apps? This is concerning as my tests don't work without the capability to store cookie information, and using Interceptor is the only thing I've found to work.

**Comment by sdnts** [comment]
@HeadlyvonNoggin Currently, yes. However, we understand this limitation and are working towards a way to make Interceptor work with the native apps. You can follow #3874 for updates.

**Comment by sunfeng90** [comment]
I lost my data today!

**Comment by NTPLThavarajan** [comment]
well i lost my whole history, on a crucial day, and that too available in the postman app only,
i have all the history, when i log in i lost all my history
