### ISSUE TITLE
Unable to move out of 'Continue where you left off' modal

### ISSUE THREAD

**Issue by anudeepmedicharla** [a85/POSTMan-Chrome-Extension#4950]
When I select 'continue where you left off' (bulb) icon, I get a modal. The modal doesn't get dismissed when I click outside of it. The escape key works though.

1. Click on the bulb icon

Expected behavior:
The modal should get dismissed when I click outside the modal.

**Screenshots**
![screen shot 2018-08-02 at 14 57 31 pm](https://user-images.githubusercontent.com/16399370/43575571-c500acda-9664-11e8-9912-fe1e469472cc.png)

**App information**
 - Native App
 - Version 6.2.3
 - macOS High Sierra 10.13.6

**Comment by numaanashraf** [comment]
@anudeepmedicharla We removed auto-close on click outside behavior for all modals. We'll add an explicit close button to this modal.

**Comment by anudeepmedicharla** [comment]
Yeah, makes sense. 👍🏼

**Comment by bhargavkaranam** [comment]
This has been fixed in the latest version of the app 6.2.5.
