### ISSUE TITLE
Seems Not to Expire Domain Cookie

### ISSUE THREAD

**Issue by ash007-postman** [a85/POSTMan-Chrome-Extension#4951]
macOS 10.13.6 (17G65) 
Native app: Version 6.1.4 (6.1.4)

1) create and call an API that sets a cookie for a the domain (e.g., ".yourdomain.test"), path of "/", and some future expiration date. Note in the Manage Cookies that it shows up. 
2) create and call an API that sets the same cookie (with no content/value) with a prior date of expiration. Observe that it shows the Set Cookie in the response, but the cookie still shows in the Manage Cookies UI.

The same calls, from within a browser app environment work as expected, i.e., the cookie is correctly expired/removed.

**To test on Postman**

To test in Postman, just do GET/POST/DELETE to domainCookieTest.example.test:3000/domain-cookie.

You can use the instructions there to compare to browser behavior. I used Chrome, latest Canary.

Steps: 
1. Use POST to set the cookie. Observe it is actually there in the cookies in Postman (and in the response). 
2. Use GET to echo is back (not strictly necessary, of course). 
3. Use DELETE to clear it. 
4. Use GET to see that it is not there any longer. Also, inspect Postman using the Cookies link.

Expected: 
The domain cookie should not be echoed, and it should not be listed in the Cookies dialog.

Actual: 
It keeps it and still echos it, and it is still there in the dialog.

**Comment by ambroselittle** [comment]
Thanks, @ash007-postman. 

Feel free to use my repro here: 
https://github.com/ambroselittle/simple-server 

Also, this happens on the Win10 client as well.

**Comment by harryi3t** [comment]
@ash007-postman @ambroselittle 
This seems to be working in the latest version of Postman (7.0.7)
Can you try it again?

![cookies-expiry-low-res](https://user-images.githubusercontent.com/5207331/55470168-bced7200-5624-11e9-8620-1177bdb001bc.gif)

**Comment by ambroselittle** [comment]
Still there in 7.0.7. It may be related to subdomains. Not sure. Try yours using domainCookieTest.example.test. 

![postman-domain-cookie-bug](https://user-images.githubusercontent.com/2660021/55492975-25792680-5606-11e9-83bd-21cabd67aef2.gif)

**Comment by numaanashraf** [comment]
This issue is fixed in Postman v7.0.8
