### ISSUE TITLE
Export to JSON v2.1 rewrites all _postman_id values, which makes diffing very impractical

### ISSUE THREAD

**Issue by BrambleRamble** [a85/POSTMan-Chrome-Extension#4952]
Using Postman 6.2.3, when I export a collection to JSON, all the _postman_id fields are regenerated.
When versioning the JSON file, this dominates the diff and makes it impossible to see the actual changes that were made.
On smaller collections it is an inconvenience but on larger files it is debilitating.

**To Reproduce**
1. Open Postman
2. Create collection with a folder and a request in it
3. Export the collection to JSON v2.1
4. Import the collection from JSON
5. Export the collection again, with a different name
6. Compare the two exported files and observe that most (if not all) of the _postman_id fields have been overwritten.

**Expected behavior**
The _postman_id fields should change as little as possible to facilitate versioning. From past experience, they used to only change when the associated folder/request was changed.

**App information:**
 - App Type: Native App]
 - Postman Version: 6.2.3
 - OS: Windows 10

**Comment by BrambleRamble** [comment]
I have uninstalled 6.2.3 and reinstalled 6.1.4 to try to work around this problem.
Unfortunately I haven't been able to stop it auto-updating to 6.2.3.
If anyone could advise how to do this as a temporary workaround, that would be hugely appreciated please.

Edit: It looks like I have managed to prevent automatic updates by deleting Updates.exe and app-6.2.3 from the AppData/Local/Postman folder. I'm running Postman.exe directly from the app-6.1.4 folder. If there's a better workaround that can be shared more easily with my team then that would still be very useful. Possibly the difficulty in blocking updates is a separate bug or feature request?

**Comment by numaanashraf** [comment]
@Al54321 This is a confirmed regression. We are working on releasing a fix this week.

**Comment by BrambleRamble** [comment]
@numaanashraf That's great, thank you for letting me know :-)

**Comment by numaanashraf** [comment]
We've released v6.2.4 which includes the fix for this issue. Please update and let us know if this issue is resolved at your end.

Incident Report: https://status.getpostman.com/incidents/84xjf585mkf5

**Comment by BrambleRamble** [comment]
Yes, I've tried using 6.2.4 this afternoon and this issue isn't causing me problems any more :-)
(Detail: I've tried a straight import/export with no additional changes, and I've also tried making extra changes to my collection before exporting, just to be sure. Both look good now.)

Thanks again for all you help!

**Comment by kendaop** [comment]
Hi, this issue is appearing again on v7.24.0. Can this issue be re-opened? 

I have a versioned Postman collection which is used by multiple team members. When I import the collection and then export it again without making any changes, all of the test IDs are changed, making it difficult to review the changes. 

Thank you.

**Comment by arlemi** [comment]
@kendaop The IDs are being updated upon importing the collection (any import = a new entity for Postman). More context around that here https://github.com/postmanlabs/postman-app-support/issues/4802#issuecomment-619438442

We're tracking ID-less export here: https://github.com/postmanlabs/postman-app-support/issues/2906
