### ISSUE TITLE
Duplicate "My Workspace" with limited functionality

### ISSUE THREAD

**Issue by nikitasius** [a85/POSTMan-Chrome-Extension#4954]
Well, here are strange bug

Application workspaces
![image](https://user-images.githubusercontent.com/3670331/43612780-9a4528d8-96ad-11e8-9c23-312b125fe28d.png)

Website workspaces:
![image](https://user-images.githubusercontent.com/3670331/43612829-c14b430e-96ad-11e8-80e5-6e1fc2e8676f.png)

1st in UI:
![image](https://user-images.githubusercontent.com/3670331/43612841-ccc43a24-96ad-11e8-8819-f0466d030378.png)
 But have a collection. Cannot call endpoints from it. Wireshark show no traffic!

2nd in UI:
![image](https://user-images.githubusercontent.com/3670331/43612888-f4d908aa-96ad-11e8-98f4-c5142255b7bd.png)
Same collection and requests working fine.

When i want to delete 1st i have:
![image](https://user-images.githubusercontent.com/3670331/43613045-61e32c78-96ae-11e8-9bdf-dcc79536b479.png)

WTF is happened? All was fine till i decided to make an account and connect it.

**App information (please complete the following information):**
 - postman app
 - Postman v6.2.3
 - OS: 4.9.0-0.bpo.5-amd64 #1 SMP Debian 4.9.65-3+deb9u2~bpo8+1 (2017-01-05) x86_64 GNU/Linux

**Comment by kamalaknn** [comment]
Hey @nikitasius 

We do a series of steps right after you login, to move your data to your account. We remove the existing data only after we've moved all the data is moved to your account. Normally that should be done to completion in just a few seconds after you login, and you wouldn't notice anything.

It seems that in your case this process has ended midway and existing data is not removed. I suspect that this process could have been interrupted. Can you recollect seeing any errors while signing in or restarting the app while it was still logging in?

We're looking into ways to recover from process failures like these in the medium term roadmap.

**Comment by nikitasius** [comment]
### i disconnected and connected and your tool wiped all local data, so have no more dublicates in a workspace.
___
But:
![image](https://user-images.githubusercontent.com/3670331/43639600-06026daa-971d-11e8-967a-1428a87b38b4.png)
Why it removes all?

Like i'm working offline. And i have stored data. Then i give ma laptop to someone to work fast locally with postman.
Guy disconnect, use laptop as a local to perform some tests and if i need to continue my work all what i need is to run to find an internet hotstop and connect, cause when it's no network, there are this and all job is gone:
![image](https://user-images.githubusercontent.com/3670331/43639742-877767f0-971d-11e8-95c6-60ea37d8f7c1.png)

Or i must always keep a backup for all my job what breakes git diffs like here #4952 .

Why there are no option: `log off but please do not delete current data damn`?

**Comment by sankalp0o** [comment]
Closing this issue in favor of #4862 , looks like the same issue of duplicate "My Workspace" created during sign up.
