### ISSUE TITLE
Can I set a variable, with it's scope set to the current execution scope?

### ISSUE THREAD

**Issue by kchanna** [a85/POSTMan-Chrome-Extension#4955]
## App Details:

```
Postman for Mac
Version 4.11.0
OS X 16.4.0 / x64
```

My requirement is this:
I have a request, in which I have to set a value (in the HTTP header) before sending the request.
There can be multiple values that can be set.
So I set an environment variable for this. And in the headers - I use this variable like {{my-variable}}
After web server sends back a reply - I have to validate that the response has the value set in the {{my-variable}}.
This works fine for a single run.

Imagine if I'm using the 4 to 5 "Runner" windows to execute 100 such transactions in each window.
Because it's an environment variable, the different instances of the runners are overwriting each others {{my-variable}} and some of the tests fail.

My question is: Is there anyway to set a variable in the current execution context?

If not, can I set a request header directly in the pre-req script.
That way I won't be using the environment variable.

**Comment by sivcan** [comment]
@kchanna Firstly, I highly recommend that you update your app to the latest version of Postman.
You can download it here: [Download Latest Postman](https://getpostman.com/apps)

Also, just a side note that the variables that are being inside a run are not persisted until and unless the run **finishes**.

Before starting the run you can turn off the 'Persist variables' / 'Keep Variable Values' (_as of v6.2+_) in the runner. 

![image](https://user-images.githubusercontent.com/12631777/43636021-887ae904-972e-11e8-924b-140f3ee6785f.png)


Once that is done, your variables won't be persisted after each run finishes and you can run multiple runs in parallel.
Thus, variables are modified and remain in the current execution context only.

Hope this helps!

**Comment by sivcan** [comment]
Closing this issue.

If the above-mentioned solution doesn't work for your use case, let me know and I'll reopen this issue ticket.
