### ISSUE TITLE
postman extension doesn't show full http post request body. Cut ~5000 characters each time.

### ISSUE THREAD

**Issue by bamdan** [a85/POSTMan-Chrome-Extension#4956]
## App Details:

Postman Chrome Extension

## Issue Report:
 1. Recently encountered but could have always been there
 2. Expected behaviour: While using postman interceptor to track requests from a webpage I've noticed http post requests don't show all of the body of the request in the chrome extension app history. I'd expect the dev tools view of the post body to match the postman view of the post data. Postman only shows a subset and gets cut consistently around 5000 characters.

 3. Console logs 

`<div class="ace_content" style="margin-top: -180px; width: 1055px; height: 1260px; margin-left: 0px;"><div class="ace_layer ace_print-margin-layer"><div class="ace_print-margin" style="left: 580.1px; visibility: hidden;"></div></div><div class="ace_layer ace_marker-layer"><div class="ace_active-line" style="height:16px;top:432px;left:0;right:0;"></div></div><div class="ace_layer ace_text-layer" style="padding: 0px 4px;"><div class="ace_line_group" style="height:480px"><div class="ace_line" style="height:16px"><span class="ace_paren ace_lparen">[{</span><span class="ace_variable">"tag"</span>:<span class="ace_string">"br_name"</span>,<span class="ace_variable">"detail"</span>:<span class="ace_string">"chrome"</span>,<span class="ace_variable">"container"</span>:<span class="ace_constant ace_numeric">0</span>,<span class="ace_variable">"id"</span>:<span class="ace_string">"1011533210284113"</span>,<span class="ace_variable">"cid"</span>:<span class="ace_string">"1011533210284113"</span>,<span class="ace_variable">"qid"</span>:<span class="ace_string">""</span>,<span class="ace_variable">"sid"</span>:<span class="ace_string">"1011533210284113"</span>,<span class="ace_variable">"step"</span>:<span class="ace_constant ace_numeric">0</span></div><div class="ace_line" style="height:16px">&nbsp;&nbsp;&nbsp;&nbsp;,<span class="ace_variable">"timestamp"</span>:<span class="ace_constant ace_numeric">1533290102122</span><span class="ace_paren ace_rparen">}</span>,<span class="ace_paren ace_lparen">{</span><span class="ace_variable">"tag"</span>:<span class="ace_string">"br_version"</span>,<span class="ace_variable">"detail"</span>:<span class="ace_string">"66.0.3334."</span>,<span class="ace_variable">"container"</span>:<span class="ace_constant ace_numeric">0</span>,<span class="ace_variable">"id"</span>:<span class="ace_string">"1011533210284113"</span>,<span class="ace_variable">"cid"</span>:<span class="ace_string">"1011533210284113"</span>,<span class="ace_variable">"qid"</span>:<span class="ace_string">""</span></div><div class="ace_line" style="height:16px">&nbsp;&nbsp;&nbsp;&nbsp;,<span class="ace_variable">"sid"</span>:<span class="ace_string">"1011533210284113"</span>,<span class="ace_variable">"step"</span>:<span class="ace_constant ace_numeric">0</span>,<span class="ace_variable">"timestamp"</span>:<span class="ace_constant ace_numeric">1533290102122</span><span class="ace_paren ace_rparen">}</span>,<span class="ace_paren ace_lparen">{</span><span class="ace_variable">"tag"</span>:<span class="ace_string">"br_major"</span>,<span class="ace_variable">"detail"</span>:<span class="ace_string">"66"</span>,<span class="ace_variable">"container"</span>:<span class="ace_constant ace_numeric">0</span>,<span class="ace_variable">"id"</span>:<span class="ace_string">"1011533210284113"</span>,<span class="ace_variable">"cid"</span></div><div class="ace_line" style="height:16px">&nbsp;&nbsp;&nbsp;&nbsp;:<span class="ace_string">"1011533210284113"</span>,<span class="ace_variable">"qid"</span>:<span class="ace_string">""</span>,<span class="ace_variable">"sid"</span>:<span class="ace_string">"1011533210284113"</span>,<span class="ace_variable">"step"</span>:<span class="ace_constant ace_numeric">0</span>,<span class="ace_variable">"timestamp"</span>:<span class="ace_constant ace_numeric">1533290102122</span><span class="ace_paren ace_rparen">}</span>,<span class="ace_paren ace_lparen">{</span><span class="ace_variable">"tag"</span>:<span class="ace_string">"en_name"</span>,<span class="ace_variable">"detail"</span>:<span class="ace_string">"webkit"</span>,<span class="ace_variable">"container"</span>:<span class="ace_constant ace_numeric">0</span></div><div class="ace_line" style="height:16px">&nbsp;&nbsp;&nbsp;&nbsp;,<span class="ace_variable">"id"</span>:<span class="ace_string">"1011533210284113"</span>,<span class="ace_variable">"cid"</span>:<span class="ace_string">"1011533210284113"</span>,<span class="ace_variable">"qid"</span>:<span class="ace_string">""</span>,<span class="ace_variable">"sid"</span>:<span class="ace_string">"1011533210284113"</span>,<span class="ace_variable">"step"</span>:<span class="ace_constant ace_numeric">0</span>,<span class="ace_variable">"timestamp"</span>:<span class="ace_constant ace_numeric">1533290102122</span><span class="ace_paren ace_rparen">}</span>,<span class="ace_paren ace_lparen">{</span><span class="ace_variable">"tag"</span>:<span class="ace_string">"en_version"</span></div><div class="ace_line" style="height:16px">&nbsp;&nbsp;&nbsp;&nbsp;,<span class="ace_variable">"detail"</span>:<span class="ace_string">"537.36"</span>,<span class="ace_variable">"container"</span>:<span class="ace_constant ace_numeric">0</span>,<span class="ace_variable">"id"</span>:<span class="ace_string">"1011533210284113"</span>,<span class="ace_variable">"cid"</span>:<span class="ace_string">"1011533210284113"</span>,<span class="ace_variable">"qid"</span>:<span class="ace_string">""</span>,<span class="ace_variable">"sid"</span>:<span class="ace_string">"1011533210284113"</span>,<span class="ace_variable">"step"</span>:<span class="ace_constant ace_numeric">0</span>,<span class="ace_variable">"timestamp"</span></div><div class="ace_line" style="height:16px">&nbsp;&nbsp;&nbsp;&nbsp;:<span class="ace_constant ace_numeric">1533290102122</span><span class="ace_paren ace_rparen">}</span>,<span class="ace_paren ace_lparen">{</span><span class="ace_variable">"tag"</span>:<span class="ace_string">"os_name"</span>,<span class="ace_variable">"detail"</span>:<span class="ace_string">"mac%20os%20x"</span>,<span class="ace_variable">"container"</span>:<span class="ace_constant ace_numeric">0</span>,<span class="ace_variable">"id"</span>:<span class="ace_string">"1011533210284113"</span>,<span class="ace_variable">"cid"</span>:<span class="ace_string">"1011533210284113"</span>,<span class="ace_variable">"qid"</span>:<span class="ace_string">""</span>,<span class="ace_variable">"sid"</span></div><div class="ace_line" style="height:16px">&nbsp;&nbsp;&nbsp;&nbsp;:<span class="ace_string">"1011533210284113"</span>,<span class="ace_variable">"step"</span>:<span class="ace_constant ace_numeric">0</span>,<span class="ace_variable">"timestamp"</span>:<span class="ace_constant ace_numeric">1533290102122</span><span class="ace_paren ace_rparen">}</span>,<span class="ace_paren ace_lparen">{</span><span class="ace_variable">"tag"</span>:<span class="ace_string">"os_version"</span>,<span class="ace_variable">"detail"</span>:<span class="ace_string">"10.13.2"</span>,<span class="ace_variable">"container"</span>:<span class="ace_constant ace_numeric">0</span>,<span class="ace_variable">"id"</span>:<span class="ace_string">"1011533210284113"</span>,<span class="ace_variable">"cid"</span></div><div class="ace_line" style="height:16px">&nbsp;&nbsp;&nbsp;&nbsp;:<span class="ace_string">"1011533210284113"</span>,<span class="ace_variable">"qid"</span>:<span class="ace_string">""</span>,<span class="ace_variable">"sid"</span>:<span class="ace_string">"1011533210284113"</span>,<span class="ace_variable">"step"</span>:<span class="ace_constant ace_numeric">0</span>,<span class="ace_variable">"timestamp"</span>:<span class="ace_constant ace_numeric">1533290102122</span><span class="ace_paren ace_rparen">}</span>,<span class="ace_paren ace_lparen">{</span><span class="ace_variable">"tag"</span>:<span class="ace_string">"dv_vendor"</span>,<span class="ace_variable">"detail"</span>:<span class="ace_string">""</span>,<span class="ace_variable">"container"</span>:<span class="ace_constant ace_numeric">0</span>,<span class="ace_variable">"id"</span></div><div class="ace_line" style="height:16px">&nbsp;&nbsp;&nbsp;&nbsp;:<span class="ace_string">"1011533210284113"</span>,<span class="ace_variable">"cid"</span>:<span class="ace_string">"1011533210284113"</span>,<span class="ace_variable">"qid"</span>:<span class="ace_string">""</span>,<span class="ace_variable">"sid"</span>:<span class="ace_string">"1011533210284113"</span>,<span class="ace_variable">"step"</span>:<span class="ace_constant ace_numeric">0</span>,<span class="ace_variable">"timestamp"</span>:<span class="ace_constant ace_numeric">1533290102122</span><span class="ace_paren ace_rparen">}</span>,<span class="ace_paren ace_lparen">{</span><span class="ace_variable">"tag"</span>:<span class="ace_string">"dv_model"</span>,<span class="ace_variable">"detail"</span></div><div class="ace_line" style="height:16px">&nbsp;&nbsp;&nbsp;&nbsp;:<span class="ace_string">""</span>,<span class="ace_variable">"container"</span>:<span class="ace_constant ace_numeric">0</span>,<span class="ace_variable">"id"</span>:<span class="ace_string">"1011533210284113"</span>,<span class="ace_variable">"cid"</span>:<span class="ace_string">"1011533210284113"</span>,<span class="ace_variable">"qid"</span>:<span class="ace_string">""</span>,<span class="ace_variable">"sid"</span>:<span class="ace_string">"1011533210284113"</span>,<span class="ace_variable">"step"</span>:<span class="ace_constant ace_numeric">0</span>,<span class="ace_variable">"timestamp"</span>:<span class="ace_constant ace_numeric">1533290102122</span><span class="ace_paren ace_rparen">}</span></div><div class="ace_line" style="height:16px">&nbsp;&nbsp;&nbsp;&nbsp;,<span class="ace_paren ace_lparen">{</span><span class="ace_variable">"tag"</span>:<span class="ace_string">"dv_type"</span>,<span class="ace_variable">"detail"</span>:<span class="ace_string">"tablet"</span>,<span class="ace_variable">"container"</span>:<span class="ace_constant ace_numeric">0</span>,<span class="ace_variable">"id"</span>:<span class="ace_string">"1011533210284113"</span>,<span class="ace_variable">"cid"</span>:<span class="ace_string">"1011533210284113"</span>,<span class="ace_variable">"qid"</span>:<span class="ace_string">""</span>,<span class="ace_variable">"sid"</span>:<span class="ace_string">"1011533210284113"</span>,<span class="ace_variable">"step"</span>:<span class="ace_constant ace_numeric">0</span></div><div class="ace_line" style="height:16px">&nbsp;&nbsp;&nbsp;&nbsp;,<span class="ace_variable">"timestamp"</span>:<span class="ace_constant ace_numeric">1533290102122</span><span class="ace_paren ace_rparen">}</span>,<span class="ace_paren ace_lparen">{</span><span class="ace_variable">"tag"</span>:<span class="ace_string">"dv_touch"</span>,<span class="ace_variable">"detail"</span>:<span class="ace_string">""</span>,<span class="ace_variable">"container"</span>:<span class="ace_constant ace_numeric">0</span>,<span class="ace_variable">"id"</span>:<span class="ace_string">"1011533210284113"</span>,<span class="ace_variable">"cid"</span>:<span class="ace_string">"1011533210284113"</span>,<span class="ace_variable">"qid"</span>:<span class="ace_string">""</span>,<span class="ace_variable">"sid"</span></div><div class="ace_line" style="height:16px">&nbsp;&nbsp;&nbsp;&nbsp;:<span class="ace_string">"1011533210284113"</span>,<span class="ace_variable">"step"</span>:<span class="ace_constant ace_numeric">0</span>,<span class="ace_variable">"timestamp"</span>:<span class="ace_constant ace_numeric">1533290102122</span><span class="ace_paren ace_rparen">}</span>,<span class="ace_paren ace_lparen">{</span><span class="ace_variable">"tag"</span>:<span class="ace_string">"JsLoadTime"</span>,<span class="ace_variable">"detail"</span>:<span class="ace_string">"2.721"</span>,<span class="ace_variable">"container"</span>:<span class="ace_constant ace_numeric">0</span>,<span class="ace_variable">"id"</span>:<span class="ace_string">"1011533210284113"</span>,<span class="ace_variable">"cid"</span></div><div class="ace_line" style="height:16px">&nbsp;&nbsp;&nbsp;&nbsp;:<span class="ace_string">"1011533210284113"</span>,<span class="ace_variable">"qid"</span>:<span class="ace_string">""</span>,<span class="ace_variable">"sid"</span>:<span class="ace_string">"1011533210284113"</span>,<span class="ace_variable">"step"</span>:<span class="ace_constant ace_numeric">0</span>,<span class="ace_variable">"timestamp"</span>:<span class="ace_constant ace_numeric">1533290102122</span><span class="ace_paren ace_rparen">}</span>,<span class="ace_paren ace_lparen">{</span><span class="ace_variable">"tag"</span>:<span class="ace_string">"RunTime"</span>,<span class="ace_variable">"detail"</span>:<span class="ace_string">"1.972"</span>,<span class="ace_variable">"container"</span>:<span class="ace_constant ace_numeric">0</span></div><div class="ace_line" style="height:16px">&nbsp;&nbsp;&nbsp;&nbsp;,<span class="ace_variable">"id"</span>:<span class="ace_string">"1011533210284113"</span>,<span class="ace_variable">"cid"</span>:<span class="ace_string">"1011533210284113"</span>,<span class="ace_variable">"qid"</span>:<span class="ace_string">""</span>,<span class="ace_variable">"sid"</span>:<span class="ace_string">"1011533210284113"</span>,<span class="ace_variable">"step"</span>:<span class="ace_constant ace_numeric">0</span>,<span class="ace_variable">"timestamp"</span>:<span class="ace_constant ace_numeric">1533290102123</span><span class="ace_paren ace_rparen">}</span>,<span class="ace_paren ace_lparen">{</span><span class="ace_variable">"tag"</span>:<span class="ace_string">"curr"</span></div><div class="ace_line" style="height:16px">&nbsp;&nbsp;&nbsp;&nbsp;,<span class="ace_variable">"detail"</span>:<span class="ace_string">"EUR"</span>,<span class="ace_variable">"container"</span>:<span class="ace_constant ace_numeric">0</span>,<span class="ace_variable">"id"</span>:<span class="ace_string">"1011533210284113"</span>,<span class="ace_variable">"cid"</span>:<span class="ace_string">"1011533210284113"</span>,<span class="ace_variable">"qid"</span>:<span class="ace_string">""</span>,<span class="ace_variable">"sid"</span>:<span class="ace_string">"1011533210284113"</span>,<span class="ace_variable">"step"</span>:<span class="ace_constant ace_numeric">0</span>,<span class="ace_variable">"timestamp"</span></div><div class="ace_line" style="height:16px">&nbsp;&nbsp;&nbsp;&nbsp;:<span class="ace_constant ace_numeric">1533290102123</span><span class="ace_paren ace_rparen">}</span>,<span class="ace_paren ace_lparen">{</span><span class="ace_variable">"tag"</span>:<span class="ace_string">"lang"</span>,<span class="ace_variable">"detail"</span>:<span class="ace_string">"en"</span>,<span class="ace_variable">"container"</span>:<span class="ace_constant ace_numeric">0</span>,<span class="ace_variable">"id"</span>:<span class="ace_string">"1011533210284113"</span>,<span class="ace_variable">"cid"</span>:<span class="ace_string">"1011533210284113"</span>,<span class="ace_variable">"qid"</span>:<span class="ace_string">""</span>,<span class="ace_variable">"sid"</span>:<span class="ace_string">"1011533210284113"</span></div><div class="ace_line" style="height:16px">&nbsp;&nbsp;&nbsp;&nbsp;,<span class="ace_variable">"step"</span>:<span class="ace_constant ace_numeric">0</span>,<span class="ace_variable">"timestamp"</span>:<span class="ace_constant ace_numeric">1533290102123</span><span class="ace_paren ace_rparen">}</span>,<span class="ace_paren ace_lparen">{</span><span class="ace_variable">"tag"</span>:<span class="ace_string">"PRESTEP"</span>,<span class="ace_variable">"detail"</span>:<span class="ace_string">"searchcars"</span>,<span class="ace_variable">"container"</span>:<span class="ace_constant ace_numeric">0</span>,<span class="ace_variable">"id"</span>:<span class="ace_string">"1011533210284113"</span>,<span class="ace_variable">"cid"</span>:<span class="ace_string">"1011533210284113"</span></div><div class="ace_line" style="height:16px">&nbsp;&nbsp;&nbsp;&nbsp;,<span class="ace_variable">"qid"</span>:<span class="ace_string">""</span>,<span class="ace_variable">"sid"</span>:<span class="ace_string">"1011533210284113"</span>,<span class="ace_variable">"step"</span>:<span class="ace_constant ace_numeric">1</span>,<span class="ace_variable">"timestamp"</span>:<span class="ace_constant ace_numeric">1533290102123</span><span class="ace_paren ace_rparen">}</span>,<span class="ace_paren ace_lparen">{</span><span class="ace_variable">"tag"</span>:<span class="ace_string">"searchcars"</span>,<span class="ace_variable">"detail"</span>:<span class="ace_string">"0.011"</span>,<span class="ace_variable">"container"</span>:<span class="ace_constant ace_numeric">0</span>,<span class="ace_variable">"id"</span></div><div class="ace_line" style="height:16px">&nbsp;&nbsp;&nbsp;&nbsp;:<span class="ace_string">"1011533210284113"</span>,<span class="ace_variable">"cid"</span>:<span class="ace_string">"1011533210284113"</span>,<span class="ace_variable">"qid"</span>:<span class="ace_string">""</span>,<span class="ace_variable">"sid"</span>:<span class="ace_string">"1011533210284113"</span>,<span class="ace_variable">"step"</span>:<span class="ace_constant ace_numeric">1</span>,<span class="ace_variable">"timestamp"</span>:<span class="ace_constant ace_numeric">1533290102123</span><span class="ace_paren ace_rparen">}</span>,<span class="ace_paren ace_lparen">{</span><span class="ace_variable">"tag"</span>:<span class="ace_string">"STEP"</span>,<span class="ace_variable">"detail"</span></div><div class="ace_line" style="height:16px">&nbsp;&nbsp;&nbsp;&nbsp;:<span class="ace_string">"searchcars"</span>,<span class="ace_variable">"container"</span>:<span class="ace_constant ace_numeric">0</span>,<span class="ace_variable">"id"</span>:<span class="ace_string">"1011533210284113"</span>,<span class="ace_variable">"cid"</span>:<span class="ace_string">"1011533210284113"</span>,<span class="ace_variable">"qid"</span>:<span class="ace_string">""</span>,<span class="ace_variable">"sid"</span>:<span class="ace_string">"1011533210284113"</span>,<span class="ace_variable">"step"</span>:<span class="ace_constant ace_numeric">1</span>,<span class="ace_variable">"timestamp"</span></div><div class="ace_line" style="height:16px">&nbsp;&nbsp;&nbsp;&nbsp;:<span class="ace_constant ace_numeric">1533290102123</span><span class="ace_paren ace_rparen">}</span>,<span class="ace_paren ace_lparen">{</span><span class="ace_variable">"tag"</span>:<span class="ace_string">"step1"</span>,<span class="ace_variable">"detail"</span>:<span class="ace_string">"1"</span>,<span class="ace_variable">"container"</span>:<span class="ace_constant ace_numeric">0</span>,<span class="ace_variable">"id"</span>:<span class="ace_string">"1011533210284113"</span>,<span class="ace_variable">"cid"</span>:<span class="ace_string">"1011533210284113"</span>,<span class="ace_variable">"qid"</span>:<span class="ace_string">""</span>,<span class="ace_variable">"sid"</span>:<span class="ace_string">"1011533210284113"</span></div><div class="ace_line" style="height:16px">&nbsp;&nbsp;&nbsp;&nbsp;,<span class="ace_variable">"step"</span>:<span class="ace_constant ace_numeric">1</span>,<span class="ace_variable">"timestamp"</span>:<span class="ace_constant ace_numeric">1533290102123</span><span class="ace_paren ace_rparen">}</span>,<span class="ace_paren ace_lparen">{</span><span class="ace_variable">"tag"</span>:<span class="ace_string">"entry_step"</span>,<span class="ace_variable">"detail"</span>:<span class="ace_string">"searchcars"</span>,<span class="ace_variable">"container"</span>:<span class="ace_constant ace_numeric">0</span>,<span class="ace_variable">"id"</span>:<span class="ace_string">"1011533210284113"</span>,<span class="ace_variable">"cid"</span>:<span class="ace_string">"1011533210284113"</span></div><div class="ace_line" style="height:16px">&nbsp;&nbsp;&nbsp;&nbsp;,<span class="ace_variable">"qid"</span>:<span class="ace_string">""</span>,<span class="ace_variable">"sid"</span>:<span class="ace_string">"1011533210284113"</span>,<span class="ace_variable">"step"</span>:<span class="ace_constant ace_numeric">1</span>,<span class="ace_variable">"timestamp"</span>:<span class="ace_constant ace_numeric">1533290102123</span><span class="ace_paren ace_rparen">}</span>,<span class="ace_paren ace_lparen">{</span><span class="ace_variable">"tag"</span>:<span class="ace_string">"v_dropoffD"</span>,<span class="ace_variable">"detail"</span>:<span class="ace_string">""</span>,<span class="ace_variable">"container"</span>:<span class="ace_constant ace_numeric">0</span>,<span class="ace_variable">"id"</span>:<span class="ace_string">"1011533210284113"</span></div><div class="ace_line" style="height:16px">&nbsp;&nbsp;&nbsp;&nbsp;,<span class="ace_variable">"cid"</span>:<span class="ace_string">"1011533210284113"</span>,<span class="ace_variable">"qid"</span>:<span class="ace_string">""</span>,<span class="ace_variable">"sid"</span>:<span class="ace_string">"1011533210284113"</span>,<span class="ace_variable">"step"</span>:<span class="ace_constant ace_numeric">1</span>,<span class="ace_variable">"timestamp"</span>:<span class="ace_constant ace_numeric">1533290102123</span><span class="ace_paren ace_rparen">}</span>,<span class="ace_paren ace_lparen">{</span><span class="ace_variable">"tag"</span>:<span class="ace_string">"v_pickupDa"</span>,<span class="ace_variable">"detail"</span>:<span class="ace_string">""</span>,<span class="ace_variable">"container"</span>:<span class="ace_constant ace_numeric">0</span></div><div class="ace_line" style="height:16px">&nbsp;&nbsp;&nbsp;&nbsp;,<span class="ace_variable">"id"</span>:<span class="ace_string">"1011533210284113"</span>,<span class="ace_variable">"cid"</span>:<span class="ace_string">"1011533210284113"</span>,<span class="ace_variable">"qid"</span>:<span class="ace_string">""</span>,<span class="ace_variable">"sid"</span>:<span class="ace_string">"1011533210284113"</span>,<span class="ace_variable">"step"</span>:<span class="ace_constant ace_numeric">1</span>,<span class="ace_variable">"timestamp"</span>:<span class="ace_constant ace_numeric">1533290102123</span><span class="ace_paren ace_rparen">}</span>,<span class="ace_paren ace_lparen">{</span><span class="ace_variable">"tag"</span>:<span class="ace_string">"age_edit"</span></div><div class="ace_line" style="height:16px">&nbsp;&nbsp;&nbsp;&nbsp;,<span class="ace_variable">"detail"</span>:<span class="ace_string">"display"</span>,<span class="ace_variable">"container"</span>:<span class="ace_constant ace_numeric">0</span>,<span class="ace_variable">"id"</span>:<span class="ace_string">"1011533210284113"</span>,<span class="ace_variable">"cid"</span>:<span class="ace_string">"1011533210284113"</span>,<span class="ace_variable">"qid"</span>:<span class="ace_string">""</span>,<span class="ace_variable">"sid"</span>:<span class="ace_string">"1011533210284113"</span>,<span class="ace_variable">"step"</span>:<span class="ace_constant ace_numeric">1</span>,<span class="ace_variable">"timestamp"</span></div><div class="ace_line" style="height:16px">&nbsp;&nbsp;&nbsp;&nbsp;:<span class="ace_constant ace_numeric">1533290102123</span><span class="ace_paren ace_rparen">}</span>,<span class="ace_paren ace_lparen">{</span><span class="ace_variable">"tag"</span>:<span class="ace_string">"e_age"</span>,<span class="ace_variable">"detail"</span>:<span class="ace_string">""</span>,<span class="ace_variable">"container"</span>:<span class="ace_constant ace_numeric">0</span>,<span class="ace_variable">"id"</span>:<span class="ace_string">"1011533210284113"</span>,<span class="ace_variable">"cid"</span>:<span class="ace_string">"1011533210284113"</span>,<span class="ace_variable">"qid"</span>:<span class="ace_string">""</span>,<span class="ace_variable">"sid"</span>:<span class="ace_string">"1011533210284113"</span></div><div class="ace_line" style="height:16px">&nbsp;&nbsp;&nbsp;&nbsp;,<span class="ace_variable">"step"</span>:<span class="ace_constant ace_numeric">1</span>,<span class="ace_variable">"timestamp"</span>:<span class="ace_constant ace_numeric">1533290102123</span><span class="ace_paren ace_rparen">}</span>,<span class="ace_paren ace_lparen">{</span><span class="ace_variable">"tag"</span>:<span class="ace_string">"ChatAvail"</span>,<span class="ace_variable">"detail"</span>:<span class="ace_string">"on"</span>,<span class="ace_variable">"container"</span>:<span class="ace_constant ace_numeric">0</span>,<span class="ace_variable">"id"</span>:<span class="ace_string">"1011533210284113"</span>,<span class="ace_variable">"cid"</span>:</div></div></div><div class="ace_layer ace_marker-layer"></div><div class="ace_layer ace_cursor-layer ace_hidden-cursors"><div class="ace_cursor" style="left: 515.289px; top: 432px; width: 7.20125px; height: 16px;"></div></div></div>`
 4. Screenshots (if applicable)

**Comment by bamdan** [comment]
I think it is related to the fact that the chrome->dev tools->network->Headers->Request Payload->view source there is an option to "show more" This corresponds to the cut off inside the app.

**Comment by abhijitkane** [comment]
@bamdan I'm not able to reproduce this in the Chrome or the Native app integration (I was able to capture a request with a 35000-character body). Are you still seeing this?

**Comment by abhijitkane** [comment]
@bamdan I'm not able to reproduce this in the Chrome or the Native app integration (I was able to capture a request with a 35000-character body). Are you still seeing this? If yes, a screen recording would help.
