### ISSUE TITLE
Postman native app for linux can not login

### ISSUE THREAD

**Issue by cyq7on** [a85/POSTMan-Chrome-Extension#4957]
I can't login using postman native app.

![screenshot](https://wx3.sinaimg.cn/mw1024/8b58ae51ly1ftws3o50phj20es0hajrw.jpg)
**App information :**
 - Native App
 - Postman-linux-x64-6.2.2
 - Ubuntu 16.04LTS x64

**Comment by numaanashraf** [comment]
@cyq7on This seems to be due to an intermittent issue with our authentication services. Let us know if you are still facing this issue.

**Comment by cyq7on** [comment]
Yeah,It's OK now,thanks!

**Comment by ogunsakin01** [comment]
Hi, I am facing the same issue. "We're having difficulties connecting to our authentication service. Try again after some time". 
The error has been up for days now

**Comment by archroid** [comment]
I have this problem , too and i really need it to be fixed. WHAT SHOULD I DO?
