### ISSUE TITLE
In-app "Learn More" link redirect broken

### ISSUE THREAD

**Issue by chrisdeso** [a85/POSTMan-Chrome-Extension#4959]
**Describe the bug**
The invite button's `Learn More` redirect throws a `404` – [https://go.pstmn.io/docs-invite-to-workspace](https://go.pstmn.io/docs-invite-to-workspace)

**To Reproduce**
1. Update to `6.2.0+`
2. Click on the `Invite` button
3. Click on the `Learn More` button
4. Watch redirect `404` in browser

**Expected behavior**
The `Learn More` link should point to the appropriate documentation

**Screenshots**
![image](https://user-images.githubusercontent.com/4734306/43657602-2be826f2-970b-11e8-847b-fe011e75b1a1.png)
![image](https://user-images.githubusercontent.com/4734306/43657617-340f4f18-970b-11e8-80b6-2a8f746d50bf.png)

**App information (please complete the following information):**
 - Native app
 - Postman Version `6.2.3`
 - OS: Mac OS High Sierra and win32-x64

**Comment by sivcan** [comment]
Also, the learn more link in the toast for collaboration limit is broken
![image](https://user-images.githubusercontent.com/12631777/43669281-7dd4d11a-979f-11e8-8187-6d7c1ed2d14b.png)

Leads to a 404

**Comment by a85** [comment]
This link can be changed through the redirection service right?
