### ISSUE TITLE
Sign in once and my workspace belongs to Postman?

### ISSUE THREAD

**Issue by JebediahSpringfield** [a85/POSTMan-Chrome-Extension#4960]
## App Details:

```
Postman for Windows
Version 6.2.3
win32 6.3.9600 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:
Can't tell
 2. Expected behaviour:
My workspace shouldn't be wiped out.
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 4. Screenshots (if applicable)

Start Postman
Add some collections to "My Workspace"
Sign in
Sign out
My Workspace is not accessible locally anymore with my collections deleted.
My local settings were reset (GUI Theme, proxy settings, everything).

The behavior is, once you log in you have to be connected all the time.
I hope this is a bug, if it is like this by design, you guys are going in the wrong direction.

**Comment by numaanashraf** [comment]
@JebediahSpringfield We back up all your data including workspaces, collections, environments etc to Postman when you create an account with us and any new workspaces or collections you create are realtime synced to your Postman account.

When you sign out of a Postman app we remove all locally stored data, mainly for security. We do not support signing out while maintaining your data yet, but we'ld love to understand your workflow if you would like to keep your local data while signing out.
