### ISSUE TITLE
Dynamically set Billing Cycle Toggle for additions/renewals

### ISSUE THREAD

**Issue by chrisdeso** [a85/POSTMan-Chrome-Extension#4961]
**Describe the bug**
When adding a user to a current billing cycle on a monthly plan, the `Billing Cycle` toggle is always set to `Annual` which may lead to unwanted billing cycle changes.

**To Reproduce**
1. Go to monthly team's [billing page](https://app.getpostman.com/pay/billing)
2. Click on `Add User Slots`
3. See that `Annual` is selected

**Expected behavior**
The billing cycle toggle should reflect the team's current plan

**Screenshots**
![image](https://user-images.githubusercontent.com/4734306/43664181-dcaf3e8e-9720-11e8-8cb6-38b0351ab76b.png)

**Comment by ankit-m** [comment]
A fix for this has been deployed and it should not auto switch to annual anymore.
