### ISSUE TITLE
Unable to publish documentation through the Chrome app

### ISSUE THREAD

**Issue by abhijitkane** [a85/POSTMan-Chrome-Extension#4964]
**Describe the bug**
I'm unable to publish documentation for a collection via the Chrome app

**To Reproduce**
1. Sign up via the Chrome app as a free user
2. Create a collection
3. Click Publish Docs from the collection's context menu
4. The web dashboard will show a screen asking you to select an environment and publish. Click Publish
5. Get a 404

**Expected behavior**
The dashboard should take me to the published documentation

**Screenshots**
<img width="1214" alt="screen shot 2018-08-04 at 12 17 17" src="https://user-images.githubusercontent.com/681190/43673415-857fd37e-97e0-11e8-9aed-67c819c98f7b.png">

**App information (please complete the following information):**
 - Postman Chrome v5.5.3

**Comment by godfrzero** [comment]
@abhijitkane This should be resolved now, can you confirm so I can close?
