### ISSUE TITLE
Response pretty view is cut off when request description is toggled

### ISSUE THREAD

**Issue by nikitasius** [a85/POSTMan-Chrome-Extension#4965]
There is a visual bug:
1) open any call, open desription, send post call, get data (unformatted)
![image](https://user-images.githubusercontent.com/3670331/43678959-05d40aa4-981d-11e8-9f8e-eb2dd6a6e77b.png)
2) change to json format
![image](https://user-images.githubusercontent.com/3670331/43678962-131297d0-981d-11e8-8d93-ee823004001c.png)
3) close descrition and scroll output:
![image](https://user-images.githubusercontent.com/3670331/43678971-2764c942-981d-11e8-9726-cf3f5e44da21.png)

You will see lines (on screenshot):
* 38
* 39
* 40 - cutted

I can scroll more:
![image](https://user-images.githubusercontent.com/3670331/43678980-4cf61ab2-981d-11e8-92fa-4d2e1ca4f714.png)

**App information (please complete the following information):**
 - Native App
 - Postman v6.2.3
 - OS: 4.9.0-0.bpo.5-amd64 #1 SMP Debian 4.9.65-3+deb9u2~bpo8+1 (2017-01-05) x86_64 GNU/Linux

**Comment by kamalaknn** [comment]
Hey @nikitasius 

This should be fixed in the latest version of Postman. I'm attaching a recording of this in the latest version - 7.20.1

![Mar-18-2020 09-55-38](https://user-images.githubusercontent.com/8401064/76925216-b40db300-68fe-11ea-8aa5-18484bc437aa.gif)
