### ISSUE TITLE
Unable to send deleted file but still trying to

### ISSUE THREAD

**Issue by fuweichin** [a85/POSTMan-Chrome-Extension#4966]
When unable to send a select file(which was deleted or moved away), Postman is still trying to send, without an error dialog or something.

**To Reproduce**
1. New Tab, POST  form-data to http://192.168.199.102:8080/api/v1/file/uploadRaw with file(foo.txt), file(bar.txt),
2. Delete bar.txt on filesystem uncautiously
3. Click 'Send'
4. Server error    
  ```
  java.net.SocketTimeoutException
  	at org.apache.tomcat.util.net.AprEndpoint$AprSocketWrapper.fillReadBuffer(AprEndpoint.java:2508)
  	...
  ```
**Expected behavior**
Raising an error, if possible.  
The way Chrome handle such an exception is dispatching an error event with response status 0.

**Screenshot**
```
POST /testdrive/v1/file/uploadRaw HTTP/1.1
Cache-Control: no-cache
Postman-Token: 8f38dcd5-9efc-46c6-961a-25e961c73307
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdWQiOlsidXNlcnM6cmVhZCIsInVzZXJzOndyaXRlIiwiZmlsZXM6cmVhZCIsImZpbGVzOndyaXRlIl0sInN1YiI6InJvb3QiLCJpc3MiOiJhdXRoMCIsImV4cCI6MTUzMjk0OTE0NSwiaWF0IjoxNTMyODYyNzQ1fQ.LzDz14_aCYKepArb-GRif6gMy4W8uZ8FWY9sAZJxseY
User-Agent: PostmanRuntime/7.2.0
Accept: */*
Host: 192.168.199.102:8080
Accept-Encoding: gzip, deflate
Content-Type: multipart/form-data; boundary=--------------------------352257662785215862180657
Connection: keep-alive
Transfer-Encoding: chunked

----------------------------352257662785215862180657
Content-Disposition: form-data; name="file"; filename="foo.txt"
Content-Type: text/plain

Foo
----------------------------352257662785215862180657
Content-Disposition: form-data; name="file"; filename="bar.txt"
Content-Type: text/plain


```
The deleted file cannot be transferred but server-end is still innocently waiting until being disappointed.

**App information**
 - Postman for Windows
 - Version 6.2.2
 - win32 10.0.17134 / x64

**Comment by numaanashraf** [comment]
Thanks for reporting this @FuweiChin. I see that this is similar to #4761. Closing this as duplicate.
