### ISSUE TITLE
The key type dropdown hides behind the left-sidebar in the side-by-side layout

### ISSUE THREAD

**Issue by abhijitkane** [a85/POSTMan-Chrome-Extension#4969]
**Describe the bug**
The key type dropdown hides behind the left-sidebar in the side-by-side layout

**To Reproduce**
1. Switch to the vertical side-by-side view. Open the dropdown to select the data type for one of the rows in form mode. The dropdown hides behind the sidebar.

**Expected behavior**
The dropdown opens to the right, or over the sidebar.

**Screenshots**
<img width="697" alt="screen shot 2018-08-05 at 11 52 47" src="https://user-images.githubusercontent.com/681190/43683308-56b1a3a8-98a6-11e8-87f8-723b96c0b71a.png">

**App information (please complete the following information):**
 - Postman OSX 6.2.3

**Comment by sivcan** [comment]
This has been fixed in v6.3.
