### ISSUE TITLE
'Force Close Other Tabs' Option

### ISSUE THREAD

**Issue by junchaw** [a85/POSTMan-Chrome-Extension#4970]
#### Screenshot

![2018-08-06 2 03 44](https://user-images.githubusercontent.com/34226239/43699504-9492e688-9981-11e8-87cb-ba077814a6d5.png)

#### Suggestion

As shown in the screenshot, there are 'Close', 'Force Close', 'Close All Tabs', 'Force Close All Tab', and 'Close Other Tabs' options. But more often I was focused on current tab and simply want to **'Force Close Other Tabs'**, I don't know why it's missing, I'd be appreciate if you consider adding this option.👍

**Comment by saurabhjayant** [comment]
Hey, @wbsnail . Thanks for all the great feedback! We've been playing around with an idea that might help alleviate some of the issues that you mentioned with the tabbed experience in Postman. In the web app, you can now go to your Settings page and toggle a no-tab state, which completely removes tabs from Postman. This will allow you to use Postman with browser tabs like any other browser-based application and not have a lot of conflicts when it comes to shortcuts and browser functionality. As a part of this, we've also enabled Open in New Tab actions on most navigational items, so while by default, all pages open in the same tab, you can always explicitly open new tabs when you want to see things side by side. It'd be great if you could try this out and let us know how this works for your use case.

P.S. We're also exploring improvements for the desktop application but will use this to validate some approaches before we go ahead and do that.

**Comment by junchaw** [comment]
thanks @saurabhjayant let's close this issue
