### ISSUE TITLE
Set environment current value only via test script

### ISSUE THREAD

**Issue by danielsxiong** [a85/POSTMan-Chrome-Extension#4972]
Hello,

I want to ask if I can set only the current value of postman environment via test script.
Right now, when I call pm.environment.set() it changes both initial and current value. It's quite troublesome to have to clean the initial values after every request.

Thank you very much

**Comment by harryi3t** [comment]
@danielsxiong You can turn off the setting `Automatically persist variable values` 
After this only current values will be updated from scripts.
The setting is turned on by default for existing users that upgrade to the new version to keep the old behaviour (updaing the variable previously would sync immediately in previous versions)

![postman 2018-08-06 19-31-52](https://user-images.githubusercontent.com/5207331/43721045-68b25782-99af-11e8-9699-19a999e2e95e.png)

Does this solve your issue?

**Comment by danielsxiong** [comment]
Yes, thank you very much. It was not clear to me before
