### ISSUE TITLE
Monitoring graph tool tip is not showing correct average Response Time

### ISSUE THREAD

**Issue by Ramya-From-Postman** [a85/POSTMan-Chrome-Extension#4973]
**Describe the bug**.
For monitors running on multiple regions, the value of Average response time in the tooltip remains same as the response time of Sum upon selecting "Average" from the drop-down.

**Steps to reproduce the behavior:**
1. Create a Monitor for multiple regions
2. Go to Monitors' page & run the respective monitor

**Expected behavior**
The tooltip value of graph should change depending on the option selected from the drop-down.

**Screenshots**

For Sum:
![image](https://user-images.githubusercontent.com/40994626/43708067-2a1f9b42-9987-11e8-92ef-e6326c630fa8.png)

For Average:
![image](https://user-images.githubusercontent.com/40994626/43708623-801638de-9988-11e8-8ddd-c3c6ed85f7bf.png)

**App information (please complete the following information):**
 - App Type : Native App 
 - Postman Version: 6.2.3
 - OS: e.g. macOS High Sierra 10.13.6

**Comment by ArjunSingh-PM** [comment]
Confirmed that this issue is fixed. @Ramya-From-Postman
