### ISSUE TITLE
The Create-New-Monitor flow's last step links to monitor.getpostman.com, not the created monitor

### ISSUE THREAD

**Issue by abhijitkane** [a85/POSTMan-Chrome-Extension#4976]
**Describe the bug**

**To Reproduce**
1. Create a monitor through the 'New' flow
2. In section 3 (Next Steps), the Check monitor results link points to monitor.getpostman.com, which takes me to my workspace listing

**Expected behavior**
The link should point to the results page of the newly created monitor.

**Screenshots**
<img width="755" alt="screen shot 2018-08-06 at 17 54 49" src="https://user-images.githubusercontent.com/681190/43716552-22ef5248-99a2-11e8-8ce6-1c3ae71e73b7.png">

**Comment by sivcan** [comment]
This has been fixed in the latest version of the Postman App (6.4)
