### ISSUE TITLE
Postman Console "Something went wrong" error when opening an array

### ISSUE THREAD

**Issue by danieladougan** [a85/POSTMan-Chrome-Extension#4977]
Postman v6.2.3 in Windows x64.

I have written the following testing code:

```
if(responseCode.code === 200){

var res = JSON.parse(responseBody);

//TEST 1
if(!_.isEmpty(res.constraints.healthBenefitsScreenedForNeed.inclusion.within)){
var list1 = [];
for (i=0; i<res.constraints.healthBenefitsScreenedForNeed.inclusion.within.length; i++) {
list1.push(res.constraints.healthBenefitsScreenedForNeed.inclusion.within[i]);
console.log(typeof res.constraints.healthBenefitsScreenedForNeed.inclusion.within[i]);
}
}

console.log("formItemsList1", list1);
console.log(typeof list1);
}
```

In the console, I see this:

![image](https://user-images.githubusercontent.com/42144517/43718602-203d19fc-9959-11e8-81ce-5f0dc1638462.png)

When I click on formItemsList1 to expand the array and view the contents, I get this error:

![image](https://user-images.githubusercontent.com/42144517/43718632-369fea58-9959-11e8-93d5-7ae13a18e399.png)

Postman support was unable to replicate the issue.

**Comment by maguirpd** [comment]
I have had the same issue with the Console window when using the javascript: console.log(...) statement. I have found that if I provide 1 arg, I can expand the value in the Console window. However, when I use 2 args like console.log("myObj", myObj); then expanding the value in the Console fails for me.

**Comment by ash007-postman** [comment]
I have lots of console.log messages with detail appended (csv data)

I used to be able to click an item in console and it would expand

With the newest version, trying to expand any item crashes the console

Version check:

>> You are up to date! Postman v6.2.4 is the latest version.
![screenshot 2018-08-15 12 10 34](https://user-images.githubusercontent.com/41741228/44258195-e7bcbe80-a22b-11e8-9adf-76bee8325c5e.jpg)
![screenshot 2018-08-15 12 10 41](https://user-images.githubusercontent.com/41741228/44258197-e7bcbe80-a22b-11e8-9679-7c4da8f83649.jpg)

**Comment by numaanashraf** [comment]
![image001](https://user-images.githubusercontent.com/3295568/44402086-51133900-a56e-11e8-9bfa-00a1b3da3423.png)

**Comment by danieladougan** [comment]
So, is there an update on this?

**Comment by jdvegmond** [comment]
This bug is getting very troublesome. When will it be fixed?

**Comment by numaanashraf** [comment]
@jdvegmond @danieladougan We had shipped some fixes that would take care of some cases that leads to this. Could you update the app to the latest version and verify again? If you are still facing this issue, please share a screenshot of the DevTools of the console window.

Opening DevTools of Postman Console:
Focus the Console Window -> Top Menu -> View -> Developer -> Show DevTools (Current View). 

Send us a screenshot of the Console tab inside DevTools. This will help us triage the issue and roll out a fix faster.

**Comment by jdvegmond** [comment]
@numaanashraf For me it seems to be fixed. Thanks.

**Comment by danieladougan** [comment]
Hello there -- 
I have updated to the latest Postman version (v6.7.3), but the problem persists for me. When I open up an array in the console, I still get the "Something went wrong" error.

**Comment by numaanashraf** [comment]
@danieladougan Please share a screenshot of the DevTools of the console window after the crash happens.

Opening DevTools of Postman Console:
Focus the Console Window -> Top Menu -> View -> Developer -> Show DevTools (Current View).

Send us a screenshot of the Console tab inside DevTools. This will help us triage the issue and roll out a fix soon.

**Comment by danieladougan** [comment]
![postman dev tools](https://user-images.githubusercontent.com/42144517/52486403-07a0bf80-2b89-11e9-90a9-c466a4f0dc69.png)

**Comment by numaanashraf** [comment]
Thanks @danieladougan. Would it be possible to verify again on our nightly build? We have pushed a related fix there. https://www.getpostman.com/downloads/canary

**Comment by danieladougan** [comment]
I think that actually fixed it! Of course, now I just need to wait for you to fix it in the production version.

**Comment by numaanashraf** [comment]
@danieladougan That's great to hear. This fix would be available on the stable version this week.

**Comment by numaanashraf** [comment]
Fix is available in Postman v7.0

**Comment by silenscer** [comment]
![imagen](https://user-images.githubusercontent.com/34064900/57660460-ac7dcf00-75b4-11e9-8ac6-3467a49e93d6.png)
Having this issue with Postman for Windows
with last version 7.0.9 or *Version 7.1.1-canary01*  ^

**Comment by ssgajjar** [comment]
@numaanashraf I am on  Postman v7.1.1 the latest version. I am still able to see the same issue when I try to expand the console log with the new version.
Kindly confirm this.
![Screenshot from 2019-05-28 11-50-45](https://user-images.githubusercontent.com/29515937/58460668-2b3f4400-813f-11e9-9fc3-ed34e638d980.png)

**Comment by dhireng** [comment]
the problem still happens on 7.1.1  can this be reopened?

**Comment by phainguyen** [comment]
Same issue happens on 7.2.2
I try to using postman in https://www.getpostman.com/downloads/canary and don't face this issue anymore

**Comment by AliRehman7141** [comment]
I'm facing this on the latest version of postman

![Screenshot 2021-11-08 at 1 35 18 PM](https://user-images.githubusercontent.com/33172988/140709631-ed0828a1-2867-4341-aab0-909a3b41d341.png)
n

**Comment by lucas-nguyen-17** [comment]
@AliRehman7141 There is something wrong in your script, like access to non-existed var, compare wrong data type... please double check it.

**Comment by qRainBirdp** [comment]
I got this problem on 9.15.0. I try to export the collection and import it to another PC and no wrong message appears.
Should i reinstall postman？
![1647591826(1)](https://user-images.githubusercontent.com/68057739/158963578-7318bc24-6ecb-4fb4-995e-6236a89103ce.png)

**Comment by qRainBirdp** [comment]
> I got this problem on 9.15.0. I try to export the collection and import it to another PC and no wrong message appears. Should i reinstall postman？ ![1647591826(1)](https://user-images.githubusercontent.com/68057739/158963578-7318bc24-6ecb-4fb4-995e-6236a89103ce.png)

I found if i add more than one variable in collection variables, this wrong message will appear.
![1647592853(1)](https://user-images.githubusercontent.com/68057739/158966114-41e5ea4b-59ae-4e14-a727-bcf12de4fe66.png)
If I enter any more character in the second line, something wrong will appear.

**Comment by numaanashraf** [comment]
@qRainBirdp This was an issue in v9.15.0 which is addressed in 9.15.2. Could you update to the latest version and let us know if you are still facing this issue?

**Comment by machielvisser** [comment]
I encounter still the same problem after updating to 9.15.2.

**Comment by richardHaggioGwati** [comment]
Facing the same issue while trying to test a login path
