### ISSUE TITLE
When exporting a collection, the JSON was from a different collection

### ISSUE THREAD

**Issue by caseydoran** [a85/POSTMan-Chrome-Extension#4978]
**Describe the bug**
I have 2 collections saved - one for our staging environment, and one for our production. The only difference is the post URL. I exported the staging collection to share with a teammate, and the post URL was from the production collection.

**To Reproduce**
0. Create two collections
1. Go to the ... menu and "export" on the 2nd collection in the list
2. Click on any of the options (v1, v2, and v2.1)
3. open the json
4. notice that the calls are from the first collection in the list

**Expected behavior**
I expected JSON of the correct collection. 

**Screenshots**
![screen shot 2018-08-06 at 9 23 46 am](https://user-images.githubusercontent.com/1730755/43725693-760464e8-995a-11e8-8d30-6945873c2210.png)
![screen shot 2018-08-06 at 9 23 53 am](https://user-images.githubusercontent.com/1730755/43725694-7621cfd8-995a-11e8-8ad6-5b17bba6a5c2.png)

**App information (please complete the following information):**
 - Postman Version 6.1.3 (6.1.3)
 - OS: macOS High Sierra 10.13.6

**Additional context**
can recreate 100% of the time

**Comment by sujayvenaik** [comment]
Hey, @caseydoran  Can you update to the latest app version (v7.x) and still replicate this?

**Comment by caseydoran** [comment]
@sujayvenaik - I do still see the issue. I exported json from the 2nd collection in my list. The info section at the top of the json describes the first collection (name), but the calls are from the first collection.

**Comment by caseydoran** [comment]
Version 7.0.6 (7.0.6)

**Comment by sujayvenaik** [comment]
@caseydoran can you help us with the collections with which we can replicate this? Or any way we can reproduce?

**Comment by caseydoran** [comment]
- both collections are nearly identical, but have a different URL (one is production, one is staging).
- Each collection has a post and a get.
- The post has 4 parameters, and the get has 2

Example post for collection 1: 
https://produrl.fakeurl/v1/provisioning?clusterName=fakename&kubernetesVersion=1.9&rbacEnabled=true&orgId=11111

Example Get for collection 1: 
https://produrl.fakeurl/v1/provisioning/82/config?orgId=11111

Example post for collection 2: 
https://stagingurl.fakeurl/v1/provisioning?clusterName=fakename&kubernetesVersion=1.9&rbacEnabled=true&orgId=11111

Example Get for collection 2: 
https://stagingurl.fakeurl/v1/provisioning/82/config?orgId=11111

**Comment by sujayvenaik** [comment]
Hey @caseydoran 
I created the same setup and tried exporting still got the expected exported json. 
Here is a screen recording of what I did exactly.

![Kapture 2019-03-29 at 0 18 56](https://user-images.githubusercontent.com/11532114/55184790-0ec37180-51b9-11e9-8786-0e31395545f5.gif)

Can you tell me where am i going wrong in reproducing this?

**Comment by sujayvenaik** [comment]
Hey @caseydoran
I created the same setup and tried exporting still got the expected exported JSON.
Here is a screen recording of what I did exactly.
![clientApp-export-bug](https://user-images.githubusercontent.com/11532114/55185842-34ea1100-51bb-11e9-929e-cd667e7ab730.gif)

Can you tell me exactly where am I going wrong in reproducing this?

**Comment by caseydoran** [comment]
@sujayvenaik - after I updated and saved the calls in my collection to use those fake URLs so I could send you a video, it seems to be working as expected. Not sure if old collections could still be impacted, as I was still seeing the issue (going through your exact steps) until I updated and saved.

Cheers
