### ISSUE TITLE
Searchable workspace dropdown in share collection modal

### ISSUE THREAD

**Issue by ankit-m** [a85/POSTMan-Chrome-Extension#4980]
**Is your feature request related to a problem? Please describe.**
For a large number of workspaces, it is very difficult to find workspaces in the dropdown when you share a collection. (Collection Menu → Share → Share in another workspace)

**Describe the solution you'd like**
Make the workspace dropdown searchable

**Describe alternatives you've considered**
Manually going scrolling to find the workspace.

**Comment by a85** [comment]
This is available in the latest versions of Postman.
