### ISSUE TITLE
Not adding the certificate to a request.

### ISSUE THREAD

**Issue by kevinetore** [a85/POSTMan-Chrome-Extension#4986]
**Issue**
Postman is not adding the certificate to a outgoing request.
I'm sending a request to https://postman-echo.com, with SSL certificate verification both tested on on/off. And the certificate added under the settings/certificates section.

**To Reproduce**
1. Add certificate under the settings/certificates section.
2. Send request to https://postman-echo.com
3. Open console and validate if the certificate is added

**Expected behavior**
See the certificate in the Postman console

**Screenshots**
<img width="684" alt="screen shot 2018-08-07 at 08 36 37" src="https://user-images.githubusercontent.com/10911831/43786451-7d6f3eba-9a1d-11e8-9ba0-00a3777cd4f4.png">

<img width="747" alt="screen shot 2018-08-07 at 08 36 53" src="https://user-images.githubusercontent.com/10911831/43786452-7d89a71e-9a1d-11e8-9529-cd2c0725742f.png">

<img width="836" alt="screen shot 2018-08-07 at 08 37 12" src="https://user-images.githubusercontent.com/10911831/43786453-7da2f3ea-9a1d-11e8-9c58-1efeaec68285.png">

**App information:**
 - Native app
 - Version 6.2.3
 - macOS Sierra 10.12.6

**Related:**
https://github.com/postmanlabs/postman-app-support/issues/3136

**Comment by numaanashraf** [comment]
@kevinetore Your certificates seems to be mis-configured. Certificates are sent if the domain matches. It looks like the domain is `mydomain` while the request is sent to `postman-echo.com`.

**Comment by kevinetore** [comment]
@numaanashraf Thanks for your quick response. You are absolutely right, thanks! I'll close this issue.

**Comment by rajmandaviya** [comment]
I have same problem, host are same but still in not add client cetificate in code.
![image](https://user-images.githubusercontent.com/38173498/100705110-acc70080-33cc-11eb-9cb6-26f03569a7dc.png)
![image](https://user-images.githubusercontent.com/38173498/100705295-f9124080-33cc-11eb-93df-52d44fd46e7a.png)
