### ISSUE TITLE
Website doesn't recognise if an account has been deleted

### ISSUE THREAD

**Issue by anudeepmedicharla** [a85/POSTMan-Chrome-Extension#4989]
I signed into my dashboard and later deleted the account. But the website still recognizes as I signed in and shows the "Dashboard" button. When I click on the button, the identity service returns "No such user found". 

Steps to reproduce:
1. Sign into your postman dashboard
2. Delete that account
3. go to "getpostman.com"
4. You can see the "Dashboard" button.

Ideal behavior:
The website should show "Sign in" if the account is deleted or fall back to another signed in account.

Screenshots:
<img width="1427" alt="screen shot 2018-08-08 at 5 38 22 pm" src="https://user-images.githubusercontent.com/16399370/43836108-dfc49cda-9b31-11e8-99a0-7722f60b64cc.png">
<img width="1440" alt="screen shot 2018-08-08 at 5 38 41 pm" src="https://user-images.githubusercontent.com/16399370/43836121-eaf0ed2a-9b31-11e8-8b2b-b3702f805889.png">

**Comment by godfrzero** [comment]
There might be a ~5 minute delay in user state propagation between services. Did this state persist for more than 5 minutes?

**Comment by anudeepmedicharla** [comment]
@godfrzero Yeah, it's been a few days now.

**Comment by ankit-m** [comment]
This is issue has been fixed.
