### ISSUE TITLE
Import collections not working

### ISSUE THREAD

**Issue by baumeister** [a85/POSTMan-Chrome-Extension#499]
Postman: 0.9
Chrome: Version 32.0.1700.107 m
OS: Win7

Exporting a collection  and then importing it again does not work

After import (drag and drop, file, or url, all the same) the import window says:

'It worked. The collection has been added.' But in reality nothing got added.
Collections list still says: 'You haven't created any collection yet'

**Comment by blairg23** [comment]
This needs to be re-opened. It's still occurring in latest version with 2.1 collections.

**Comment by TheBox193** [comment]
@blairg23 Make a new issue with details and reference this one.
