### ISSUE TITLE
Adding multiple access token methods

### ISSUE THREAD

**Issue by SamuelDev** [a85/POSTMan-Chrome-Extension#4990]
## App Details:
Postman for Windows
Version 6.2.3
win32 10.0.16299 / x64

## Feature Request:
 1. Feature:  
Authorization Access tokens

 2.  Request: 
We have multiple environments that use Oauth2.0 for authentication.  Under this, we have different types of tokens depending on the environment we work in, where some may be implicit tokens, while other are client credential tokens.  On top of this, we have an example where the information required for a dev environment implicit token is different than a prod implicit token.  Having a method to save different sets of token information would greatly help, so it would not be required to keep client secrets and authority URL's stored in a word doc.

**Comment by harryi3t** [comment]
We are tracking this feature request here https://github.com/postmanlabs/postman-app-support/issues/4636
