### ISSUE TITLE
Bulk Edit Collection variables is gone

### ISSUE THREAD

**Issue by karelfavresse** [a85/POSTMan-Chrome-Extension#4991]
Starting from version 6.2.3, the option to Bulk Edit collection variables is gone.

Before that version, Bulk Edit would switch the table view to a single edit field where multiple variables could be edited as a single text block.

Very handy for copying variables between collections.

This is no longer possible.

Please reinstate this option.

**Comment by numaanashraf** [comment]
@karelfavresse Bulk Edit is deprecated and we are removing it starting v6.2. We are tracking this change at #4898 and you can find the detailed explanation of this change at https://github.com/postmanlabs/postman-app-support/issues/4898#issuecomment-408343416.

We are working on enhancing the table view to support bulk editing workflows. Currently, you can multi-select rows in the table view via click-and-drag, copy with Cmd/Ctrl+C and then paste into the destination table view with Cmd/Ctrl+V (after you focus inside a cell).

I'm closing this issue as a duplicate. Let's us know at #4898 how we can improve the table view for your workflows.
