### ISSUE TITLE
Editing environment hangs

### ISSUE THREAD

**Issue by loopDelicious** [a85/POSTMan-Chrome-Extension#4993]
**Describe the bug**
Opening the Manage Environments modal displays an empty environment which hangs for > 1 minute. During this time, the app is non-responsive. Can't close the window, view values, or edit values for this time. Once it loads it seems to take a very long time to edit values too.

**To Reproduce**
1. Go to ''Edit" link in the environment quicklook. Alternatively, go to gear icon to manage environments and open environment modal.
2. Modal hangs for > 1 minute, and I can't do anything while it hangs.

**Expected behavior**
Load more quickly. Or be able to close the modal.

**Screenshots**
This is what displays while the app is non-responsive. Can't close the modal or view the environment values while the app is non-responsive. However, I can quit the app.

![screen shot 2018-08-08 at 11 30 27 am](https://user-images.githubusercontent.com/17693714/43857473-411949c2-9b00-11e8-9116-f2a51324b712.png)

**App information:**
 - App Type Native App
 - Postman Version 6.3.2
 - OS: macOS High Sierra 10.12.4

**Additional context**
Tried rebooting the app several times. Tried switching to different workspaces. So far this issue only shows up for a specific environment in a specific workspace. However, my co-worker who is on a different Postman team experienced this issue yesterday with a different environment, workspace, team, etc.

**Comment by kamalaknn** [comment]
Hey @loopDelicious 

Can you check the size of the values in your environment? Do you have very large values like stringified libraries for BDD testing in your environment?

It is possible that very large environment values could take time some time to load.

I tested an environment with the JQuery library loaded 10 times in an environment. It took 10-20s on macbook pro. These operations can be system and hardware dependent as it involves IO.

Can you share the size of your environment and hardware configuration so we can do some benchmarks to improve our performance?

**Comment by loopDelicious** [comment]
@kamalaknn 

Makes sense. I didn't have any stringified libraries, but did indeed have a large array. Total environment size is ~ 6MB.

**Comment by numaanashraf** [comment]
Tracking this at a related issue - #5827
