### ISSUE TITLE
Get Expected & Actual Result when a test fails in PostMan test scripts

### ISSUE THREAD

**Issue by raghav19** [a85/POSTMan-Chrome-Extension#4994]
Hi,
I am trying to understand how to get the expected and actual result for each test of my test script in postman . Somethings that i tried is
1.  `pm.test("Status code is 200", function () {
      pm.response.to.have.status(200);
      console.log("TestCase: Status Code should be 200"+", 
        Expected: "+"Response code should be 200"+", Actual: "+pm.response.code);
      });`
 
2.  `pm.test(`Status code is 200 - Actual Status Code: ${pm.response.code}`, () => {
      pm.response.to.have.status(200)
      })`

But isnt there a default function somewhere in the APIs which would print the Actual values and expected values when we run tests in PostMan. I want to know the expected and actual values for the test
`pm.test("Content-Type is present", function () {
   pm.expect(pm.response).to.have.header("Content-Type");
   });`

Kindly help in understanding this better.

**Comment by sivcan** [comment]
@raghav - You can open up the **Postman Console** and write a 'console.log' anywhere in the test script and you'll be able to print every value that you want to see.
The test results displayed in the UI are for pass/fail.

Eg: 
```
// Logging the complete response
console.log(pm.response);

pm.test("Status code is 200", function () {
    console.log(pm.response.code);
    pm.response.to.have.status(200);
});
```

Postman internally uses an extended version of chai: https://github.com/postmanlabs/chai-postman
You can read more about testing using chai in the docs: http://www.chaijs.com/api/bdd/

**Comment by raghav19** [comment]
I tried doing this 
`console.log("Actual: "+pm.response.headers.hasOwnProperty("Content-Type"));` 

But its evaluating to false. The actual test is 
`pm.test("TestCase: Check Content-Type is present" , function () {
   console.log("Actual: "+pm.response.headers.hasOwnProperty("Content-Type"));
   pm.expect(pm.response).to.have.header("Content-Type");
});`

**Comment by bhargavkaranam** [comment]
Hi @raghav19,
Use `pm.response.headers.has('Content-Type'));` to check if `Content-Type` is present in the list that is returned. For reference, you can check http://www.postmanlabs.com/postman-collection/HeaderList.html

**Comment by raghav19** [comment]
Thanks.It worked
