### ISSUE TITLE
Restore not working in Postman v6.2.3

### ISSUE THREAD

**Issue by godfrzero** [a85/POSTMan-Chrome-Extension#4995]
**Describe the bug**
I click on 'Restore' in the collection sidebar, it does nothing. If I open the console, I see that the request is being made with the incorrect verb.

**To Reproduce**
1. Open any collection in the Postman App
2. Make some change, any change
3. Now open the activity feed for this collection
4. Click the 'Restore' link at a point before the change made in Step 2
5. Nothing happens

**Expected behavior**
Clicking on the 'Restore' link should restore the collection to that revision.

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version: 6.2.3
 - OS: macOS

**Comment by numaanashraf** [comment]
Fixed in v6.2.4
