### ISSUE TITLE
Request sending hangs forever for V6.2.3 on Windows 10

### ISSUE THREAD

**Issue by Anwar-Ul-Haq** [a85/POSTMan-Chrome-Extension#4997]
https://github.com/postmanlabs/postman-app-support/issues/2559#issuecomment-411693240

above issue appearing again for 

Postman version: v6.2.3
OS: Windows 10

**Comment by kamalaknn** [comment]
@TechLearner2 Hey could you try updating to the latest version v6.2.4 and testing the same?

**Comment by Anwar-Ul-Haq** [comment]
@kamalaknn updating to v 6.2.4 has fixed the issue.
All looking good.
Thank you
