### ISSUE TITLE
I've found that the recent update has caused the Postman icons to disappear - Postman v6.2.4 is the latest version

### ISSUE THREAD

**Issue by maguirpd** [a85/POSTMan-Chrome-Extension#4998]
Please read through the [guidelines](https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues) before creating a new issue.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**App information (please complete the following information):**
 - App Type [e.g. Chrome App, Native App]
 - Postman Version [e.g. 6.0.1]
 - OS: [e.g. macOS High Sierra 10.13.2]

**Additional context**

**Comment by maguirpd** [comment]
![image](https://user-images.githubusercontent.com/5106520/43910581-1d119ba6-9bf5-11e8-8e20-beaa983f1ed8.png)

**Comment by SamvelRaja** [comment]
Tracking in #4814
