### ISSUE TITLE
Collection variables not being compiled on documentation

### ISSUE THREAD

**Issue by abarnwell** [a85/POSTMan-Chrome-Extension#5000]
Collection variables are showing as {{}} on documentation. All other variables are replaced by the value of the variable but collection variables don't get compiled. This has meant that we can't use collection variables for collections we intend to use on documentation.

**Comment by ItachiSan** [comment]
I'm also affected.
My personal suggestion would be to use the initial value of the variables for the documentation and add a small section in the documentation reporting such variables.

**Comment by preethammavin** [comment]
The issue has been fixed, feel free to reopen if it is not.
