### ISSUE TITLE
Can´t set,dynamically , environment variables

### ISSUE THREAD

**Issue by carodrigues** [a85/POSTMan-Chrome-Extension#5002]
Hi,

I have issue with set environment variables.

I have the follow GET body:

    [
        {
            "id": "2448ec2e-b849-4835-9c6a-02ea7b28f298",
            "name": "test sequence for Abort",
            "description": "This a test sequence",
            "type": "Product",
            "createDate": "2018-08-09T21:01:47.3120000Z",
            "lastUpdateDate": "2018-08-09T21:01:47.3120000Z",
            "lastUpdateUser": "José Carlos",
            "variables": [
                {
                    "id": "afa2f2e1-e3be-4dff-a7ad-817b7d25be64",
                    "name": "Result1",
                    "type": "string"
                },
                {
                    "id": "a0914b11-43ff-475a-ac44-65da1fd68aea",
                    "name": "Result2",
                    "type": "string"
                },
                {
                    "id": "5a3277d3-386d-4a12-b373-af38d91a727d",
                    "name": "Result3",
                    "type": "string"
                },
                {
                    "id": "61fc107a-8929-4a33-8f26-2a0228344adc",
                    "name": "Result4",
                    "type": "string"
                },
                {
                    "id": "598a1843-12f0-42ea-819d-944c1e1d6060",
                    "name": "Result5",
                    "type": "string"
                },
                {
                    "id": "c6182b5f-df2f-4d6d-91b0-77e8679f052f",
                    "name": "Result6",
                    "type": "string"
                },
                {
                    "id": "a368b7db-3d0c-4385-9f56-ad9793072b97",
                    "name": "Result7",
                    "type": "string"
                },
                {
                    "id": "ae5db407-ce44-485c-a1a2-e0ae33353279",
                    "name": "Result8",
                    "type": "string"
                },
                {
                    "id": "760bb1f1-70f6-49e9-a9b4-9e8d7e26b14a",
                    "name": "Result9",
                    "type": "string"
                }
            ],
            "instructions": null
        },
        {
            "id": "888108a7-2101-4aeb-b1ec-6ad779b8c09d",
            "name": "test sequence for initial",
            "description": "This a test sequence",
            "type": "0",
            "createDate": "2018-08-09T21:02:24.8290000Z",
            "lastUpdateDate": "2018-08-09T21:02:24.8290000Z",
            "lastUpdateUser": "José Carlos",
            "variables": [
                {
                    "id": "afa2f2e1-e3be-4dff-a7ad-817b7d25be64",
                    "name": "Result1",
                    "type": "string"
                },
                {
                    "id": "a0914b11-43ff-475a-ac44-65da1fd68aea",
                    "name": "Result2",
                    "type": "string"
                },
                {
                    "id": "5a3277d3-386d-4a12-b373-af38d91a727d",
                    "name": "Result3",
                    "type": "string"
                },
                {
                    "id": "61fc107a-8929-4a33-8f26-2a0228344adc",
                    "name": "Result4",
                    "type": "string"
                },
                {
                    "id": "598a1843-12f0-42ea-819d-944c1e1d6060",
                    "name": "Result5",
                    "type": "string"
                },
                {
                    "id": "c6182b5f-df2f-4d6d-91b0-77e8679f052f",
                    "name": "Result6",
                    "type": "string"
                },
                {
                    "id": "a368b7db-3d0c-4385-9f56-ad9793072b97",
                    "name": "Result7",
                    "type": "string"
                },
                {
                    "id": "ae5db407-ce44-485c-a1a2-e0ae33353279",
                    "name": "Result8",
                    "type": "string"
                },
                {
                    "id": "760bb1f1-70f6-49e9-a9b4-9e8d7e26b14a",
                    "name": "Result9",
                    "type": "string"
                }
            ],
            "instructions": null
        }
    ]

I'm trying to get the value of:

    "id": "598a1843-12f0-42ea-819d-944c1e1d6060",
                    "name": "Result5",
                    "type": "string"

I managed a way to get the values.
Now, i have 9 env variables for id, name and type and i want to pass the values to them without creating a set event for each. 
The env variables are:
- varID1, ...,  to varID9,
- varName1, ..., to varName9,
- varType1, ... to varType9.

I'm trying the bellow code but the variable name created by"varID ='varId'+k", e.g varID1, isn´t used on the set. 
i can´t see why this doesn´t work.

    for ( var j = 0; j < test ; j ++ ) {
        var k = j + 1;
        var varID ='varId'+k;
        var varName ='varName'+k;
        var varType ='varType'+k;
        pm.environment.set(varID,  jsonData[key].variables[j].id); // Set fails 
        pm.environment.set(varName, jsonData[key].variables[j].name);  // Set fails 
        pm.environment.set(varType, jsonData[key].variables[j].type);   // Set fails 
        console.log(varID + " " + jsonData[key].variables[j].id );  
        console.log(varName + " " + jsonData[key].variables[j].name);
        console.log(varType + " " + jsonData[key].variables[j].type);               
    }

I this this is a bug.

**Comment by bhargavkaranam** [comment]
Hi @carodrigues,
Setting the environment variable within a loop should work. Can you open the Postman console and check if there are any errors?

**Comment by carodrigues** [comment]
Hi @bhargavkaranam 
 
I made a pm.environment.get() ... it seems it has the value. 

 console.log( "var ID1 " + " " + pm.environment.get("varID1"));
console.log( "var Name 1 " + " " + pm.environment.get("varName1"));

But at the list of env variables, all variables are empty:


![list](https://user-images.githubusercontent.com/11546961/43951038-f206d440-9c89-11e8-92bb-0936e6979e9f.png)



Do you know why?

**Comment by bhargavkaranam** [comment]
Can you `console.log(jsonData[key].variables[j].id)` in the script and see what the value in the console is?

**Comment by carodrigues** [comment]
Yes,   i can.

**Comment by bhargavkaranam** [comment]
It's not null or undefined? Please note that if the value you are trying to set is `null` or `undefined`, empty value will be set for the environment variable. 

I'm able to set the environment variables in a loop.

**Comment by carodrigues** [comment]
This is the console:

![list_console](https://user-images.githubusercontent.com/11546961/43952475-fc4c2e10-9c8d-11e8-8610-d913698e360a.png)

As i told, the variables at env variable list are empty:

![list](https://user-images.githubusercontent.com/11546961/43952699-946f4524-9c8e-11e8-91c9-ae63fbbacbe3.png)

But with a get, the variable have the value:


                   console.log( "var ID1 " + " " + pm.environment.get("varID1"));
                    console.log( "var Name 1 " + " " + pm.environment.get("varName1"));
                   console.log( "var Name 9 " + " " + pm.environment.get("varName9"));

The question is, why the lis is empty?

**Comment by bhargavkaranam** [comment]
Hi @carodrigues,
Is it possible for you to share a sample collection where this issue is reproducible? We are unable to reproduce this and want to take a closer look. You can use fake data and any endpoint.

Can you also please open Environment Quick Look and check if the values are empty or not?

**Comment by carodrigues** [comment]
Hi @bhargavkaranam 

I fixed this isue.
This was a problem on the run. I was running with selecting the correct variables group. 

Sorry and thank you for your support.
