### ISSUE TITLE
Export OAuth2 information

### ISSUE THREAD

**Issue by Postman-Gabriel** [a85/POSTMan-Chrome-Extension#5004]
When exporting an environment, the authentication key from oAuth2 doesn't get transferred over. You have to manually click the generate auth code button again. Not sure if bug or feature.
 
**To Reproduce**
1. Have a collection with auth key required for a request
2. Export it to another user computer
3. Import into new Postman instance

**Expected behavior**
Expected to receive the auth code in addition to the other information

**App information (please complete the following information):**
 - App Type: Native app
 - Postman Version: 6.1.3
 - OS: Windows 10

**Comment by numaanashraf** [comment]
@Postman-Gabriel Could you please furnish more information? Are you exporting a collection or an environment? Which key is expected to be exported?

**Comment by DannyDainton** [comment]
It's unclear what you're requesting here - I'm going to close this out but if you're still facing any issue in the latest version of the platform, we can look to reopen this providing more information is shared.
