### ISSUE TITLE
Inline request URL editor is difficult to use on smaller window sizes

### ISSUE THREAD

**Issue by Postman-Gabriel** [a85/POSTMan-Chrome-Extension#5005]
**Describe the bug**
When using postman in a smaller window, the inline editor gets cut off by the send and params buttons, meaning that you can't see as much of the request URL and its lessens usability. 

**To Reproduce**
1. Create a request
2. Shrink window
3. See error

**Expected behavior**
Expected to see the buttons shifted down a line so that the entire editor can be seen.

**Screenshots**
Way it works
<img width="472" alt="screen shot 2018-07-16 at 3 18 33 pm" src="https://user-images.githubusercontent.com/40899145/43975714-679813d2-9c93-11e8-8291-d7ae45a39316.png">
Expected
<img width="479" alt="screen shot 2018-07-16 at 3 21 54 pm" src="https://user-images.githubusercontent.com/40899145/43975713-65c87cc2-9c93-11e8-8002-665a2fb1ff5a.png">

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version: 6.1.4
 - OS: N/a (all)

**Comment by sivcan** [comment]
Can be solved with: https://github.com/postmanlabs/postman-app-support/issues/2716

We'll keep a track of tackling the request URL editor in two-pane layout and small screen sizes, in the same issue (https://github.com/postmanlabs/postman-app-support/issues/2716)

Closing this ticket.
