### ISSUE TITLE
Inline variable editing

### ISSUE THREAD

**Issue by Postman-Gabriel** [a85/POSTMan-Chrome-Extension#5006]
Please read through the [guidelines](https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues) before creating a new issue.

**Is your feature request related to a problem? Please describe.**
I always want to edit variables in the menu that you get when you try to check what the variable resolves to. That would make everything easier for us.

**Describe the solution you'd like**
Add a little ability to change variable values in the drop-down by clicking on the value

Here is a mockup of what I want

![postman_edit](https://user-images.githubusercontent.com/40899145/43978647-d5b6337c-9c9c-11e8-8396-881b7800bea4.png)

**Additional context**

**Comment by skatikia** [comment]
@Postman-Gabriel Done! 🎉

With Postman **V11.14**, we have rolled out multiple improvements to our variables interface, including **the ability to update variable values on the go**.

![edit-value](https://github.com/user-attachments/assets/655c42f9-a1a7-41d7-9509-8eaab814ad05)

[Check out the Postman V11.14 release note](https://arc.net/l/quote/vtemyulc)
