### ISSUE TITLE
Formerly working Postman instance now crashes (black screen) shortly after launch

### ISSUE THREAD

**Issue by bryangunn** [a85/POSTMan-Chrome-Extension#5008]
Postman 6.2.4 (up to date as of this writing) native app for Mac
MacOS 10.13.6 (up to date as of this writing)
Model: MacBook Pro (Retina, 15-inch, Mid 2015)
Processor: 2.8GHz
Memory 16GB
Graphics AMD Radeon R9 M370X 2048 MB/Intel Iris Pro 1536 MB

**Describe the bug**
After using Postman with no issues (other than it makes the MacBook's fan run like crazy within a few seconds of startup) for a month or so, it now crashes shortly after launch. I launch it, through the GUI or command line, it comes up for about 15 seconds, then crashes with a black screen. 

**To Reproduce**
After reading about this issue from others, I tried the GPU-disable fix. Problem still happens. Here's my terminal output:

$ export POSTMAN_DISABLE_GPU=true
$ env |grep POSTMAN
POSTMAN_DISABLE_GPU=true
$ /Applications/Postman.app/Contents/MacOS/Postman
Disabling hardware acceleration
2018-08-11 09:23:31.891 Postman[716:11491] *** WARNING: Textured window <AtomNSWindow: 0x7fdddec75910> is getting an implicitly transparent titlebar. This will break when linking against newer SDKs. Use NSWindow's -titlebarAppearsTransparent=YES instead.
ORM initialization successful
App events bus { name: 'booted', namespace: 'shared' }
App updater event { name: 'checkForElectronVersionUpdated',
  namespace: 'appUpdate' }
App events bus { name: 'booted', namespace: 'requester' }

<--- Last few GCs --->

[722:0x7fdf6d80e800]    25655 ms: Mark-sweep 1999.6 (2043.4) -> 1999.6 (2043.4) MB, 45.6 / 0.0 ms  allocation failure GC in old space requested
[722:0x7fdf6d80e800]    25777 ms: Mark-sweep 1999.6 (2043.4) -> 1999.6 (2008.9) MB, 121.2 / 65.0 ms  last resort 
[722:0x7fdf6d80e800]    25842 ms: Mark-sweep 1999.6 (2008.9) -> 1999.6 (2008.9) MB, 65.1 / 1.7 ms  last resort 

<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x1781bb74661 <String[7]: file://>
    2: filter_record [file:///Applications/Postman.app/Contents/Resources/app/js/vendor-shared.js:123769] [bytecode=0x77ad99f4499 offset=40](this=0x2b8e81088809 <IDBRequest map = 0x3b4b5b91aa91>)
    3: arguments adaptor frame: 1->0
    5: /* anonymous */ [file:///Applications/Postman.app/Contents/Resources/app/js/vendor-shared.js:119868] [bytecode=0x77ad99f4131 offset=17](this=0x2b8e81...

**Comment by numaanashraf** [comment]
@bryangunn Does the application crash while performing any particular operation?

**Comment by bryangunn** [comment]
No. I launch Postman, touch nothing, wait 10-15 seconds, app crashes. 

Assuming Postman is totally hosed, is there any way to recover any of the API calls I built in Postman?

**Comment by makahn64** [comment]
Was there ever a resolution to this? I am seeing it on my Mac as well.

**Comment by kamalaknn** [comment]
Hey @makahn64 @bryangunn 

Can you update your apps to the latest version and let us know if you are still seeing this issue?

**Comment by mccannt** [comment]
Closing this issue for the time being as there is no confirmation that this is still an issue.
Please feel free to reopen if this continues to happen with the most recent version of the application.
