### ISSUE TITLE
Save result view formatting when switching tabs

### ISSUE THREAD

**Issue by ghost** [a85/POSTMan-Chrome-Extension#5009]
I've created and saved a request and chosen the Pretty view with JSON formatting.
![before](https://user-images.githubusercontent.com/5414422/43992716-4392c000-9d37-11e8-978f-c14b2b5476c6.png)

After moving to another tab then moving back, the formatting is reset to default.
![after](https://user-images.githubusercontent.com/5414422/43992740-860d7d76-9d37-11e8-952b-ede5bb3b0811.png)

**Comment by sujayvenaik** [comment]
Hey @SolarSailor15 

We have identified this as a request from a lot of Postman Users.
Hence have taken this into account, this is in our short term road map and hence will be out soon with future releases.

**Comment by sujayvenaik** [comment]
@SolarSailor15 
Hi, we have addressed this issue as part of various improvements we have made to how tabs work in Postman. These changes are up available on our canary channel (https://www.getpostman.com/canary) today and would soon be available on the stable channel. Do try these out in the canary and let us know.

**Comment by sujayvenaik** [comment]
Hey @SolarSailor15 
This issue has been fixed and is available on the stable channel (v6.4.x).
You can update the app to the latest version.

Thanks again for writing in and reporting this issue.
