### ISSUE TITLE
UI - Postman Packaged App - Increase width of Scroll Bar in Response

### ISSUE THREAD

**Issue by alteraki** [a85/POSTMan-Chrome-Extension#501]
Increase the width of the scroll bar in postman to make it easier to handle

**Comment by scaleoutsean** [comment]
@a85 this is still (or again?) a problem. 

I'm on Win10 and find it hard (takes 5-10 tries every time I want to scroll) to pinpoint the external scroll bar which is like 1-2% of my screen width. 
In the beta mode (two side-by-side panes) the external bar disappears so I have to deal with only the internal (Responses pane) scroll bar, but in the default mode this is a constant problem for me: sometimes I can't activate the correct scroll bar, other times neither of them (sometimes it kind of helps to use the internal scroll bar, although I actually aim at the external (main window) scroll bar.

I'd like to be able to set the width in Settings if possible, and I probably want them at least twice as wide.

**Comment by sdnts** [comment]
@scaleoutsean Is the two pane layout in the app not working as expected for you? That should get rid of the outer sidebar and allow you to scroll easier within the response body. We're also working on making this layout resizable for more customizability. I'll let you know here when it is out, which should be in the next release.

**Comment by scaleoutsean** [comment]
Yes, the two pane layout is 50% better (only one "thin" scroll bar to target with mouse).
Sometimes there's no need to scroll (with short request and response combos) but I usually have responses that are longer than one screen and on a 12" notebook with non-HD resolution that happens frequently, so the two pane layout is an improvement compared to the classic layout and as you noted the ability to customize the width of scroll bars would really help in all cases and layouts where either the request or response requires scrolling.

**Comment by cjmakwana** [comment]
I am not sure whether it is resolved, but it is quite annoying to work on the laptop devices without mouse. Not sure what purpose it serves to have tiny, think scroll bars, which causes mis-clicks multiple times.
