### ISSUE TITLE
Unable to login to Postman

### ISSUE THREAD

**Issue by MeenaAdobe** [a85/POSTMan-Chrome-Extension#5011]
Please read through the [guidelines](https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues) before creating a new issue.

**Describe the bug**
Im unable to sign in to Postman. It jjust throwed me to log out. After that, if I try to login, I keep seeing the same login screen as Signing In... But, I'm not able to login. Its just showing the same screen forever. This is happening since today evening & its highly frustrating. Can you please check the same.

**To Reproduce**
1. Launch the Postman in Mac
2. Try to open the postman
3. Sign in using the username & password

**Expected behavior**
I should be able to successfully logged in nd able to see all my saved API requests in my workspace.

**Screenshots**
<img width="1354" alt="screen shot 2018-08-12 at 10 12 10 pm" src="https://user-images.githubusercontent.com/42333151/44013814-d0a35c0c-9e7c-11e8-8f4f-6de3c6fa5b66.png">

--
UPDATE: Removed sensitive information

**Comment by sujayvenaik** [comment]
Hey @MeenaAdobe 

We are experiencing some issues in our Authentication Service and are working to fix this.
Stay tuned to https://status.getpostman.com/ for updated.

**Comment by numaanashraf** [comment]
@MeenaAdobe our systems are operational and we are monitoring them. Please try logging back in.

Incident report: https://status.getpostman.com/incidents/jy7fv1qs1k4b
