### ISSUE TITLE
Keyboard Shortcuts fail to work on Windows 10 Desktop App

### ISSUE THREAD

**Issue by ash007-postman** [a85/POSTMan-Chrome-Extension#5013]
The following keyboard shortcuts fail to work on Windows 10 Desktop App:

Switch To Next Tab Ctrl + Shift + ] 
Switch To Previous Tab Ctrl + Shift + [

**Comment by sujayvenaik** [comment]
Hey @ash007-postman 

The shortcut for windows and linux platform are different for next tab and previous tab.
Switch To Next Tab Ctrl + Tab
Switch To Previous Tab Ctrl + Shift + Tab

The shortcuts you wrote above are for the mac platform.
