### ISSUE TITLE
Updating Example request is not reflected in Mock-api response

### ISSUE THREAD

**Issue by fkYr63V9aIB** [a85/POSTMan-Chrome-Extension#5014]
**Describe the bug**
When updating and saving an example response, the update is not reflected in the response from the mock API. The mock API always only returns the very first saved version of the example response.

I've logged in and out of Postman to see if the updated example is in fact saved in Postman, and it is.

**To Reproduce**
1. Save an example response to be used for the mock API. (This works fine when calling the mock API)
2. Edit the example with some new JSON data and save it.
3. Call the mock api again
4. The mock API returns the first (old) version of the example response instead of the newly updated example JSON.

**Expected behavior**
After updating an example response, I expect that change to be reflected in the following mock-API calls, instead of getting the originally saved example response.

**App information (please complete the following information):**
 - App Type: Native OS X App
 - Postman Version: 6.2.4
 - OS: macOS High Sierra 10.13.6

**Additional context**
I looked at the Shared DevTools console which didn't display any errors while updating my example response.

**Comment by fkYr63V9aIB** [comment]
Update: Looks like the changes are picked up after an hour or so, which is a bit inconvenient.

**Comment by fkYr63V9aIB** [comment]
Looks more like a caching issue on our end. Closing

**Comment by openhouseMarcela** [comment]
I had the same issue. What you need to do is "Empty Cache and Hard Reload" your browser. Go to"inspect" and then right click on the refresh button on the browser. Then click on "Empty Cache and Hard Reload"

**Comment by tarunmaini16** [comment]
I was facing same issue, while making XHL request and parsing json, solved this by adding 'Cache-Control', 'no-cache' in header. This make me feel that postman mock api is not displaying results with cache, its the way how we are consuming data.

**Comment by vishalsingh-sains** [comment]
Facing this issue on V6.7, I've updated example response for a mock api but keep getting the first response. Tried everything there is not even any admin option on workspace to work this put manually..poor

**Comment by vvs11** [comment]
@vishalsingh-sains If the request in your examples is the same, then mock server picks up one of the examples and returns it. If you want a specific response code, you can use 'x-mock-response-code' header in the mock request. More documentation here: 
https://learning.postman.com/docs/designing-and-developing-your-api/mocking-data/mocking-with-examples/#step-5-sending-a-request-using-the-mock-server-m1

**Comment by vishalsingh-sains** [comment]
> @vishalsingh-sains If the request in your examples is the same, then mock server picks up one of the examples and returns it. If you want a specific response code, you can use 'x-mock-response-code' header in the mock request. More documentation here:
> https://learning.postman.com/docs/designing-and-developing-your-api/mocking-data/mocking-with-examples/#step-5-sending-a-request-using-the-mock-server-m1

@vvs11  My problem is not the response code actually but a different response/payload in body with 200 OK. The guide suggests we can update the response in an example after running mock server and then the same request should return the updated response but it doesn't happen. I keep receiving the same old, like it has been cached. But there is no way to fix it. Thanks
