### ISSUE TITLE
Prompt "Sign In  or Sign Out" every half an hour

### ISSUE THREAD

**Issue by ghost** [a85/POSTMan-Chrome-Extension#5016]
The Postman app prompts to sign in or sign out every half an hour. After I signed in(all the caches lost), it will prompt again after half an hour. If I choose Sign out, it will quit.

**Comment by numaanashraf** [comment]
@rayl-brbio We have an ongoing outage with our authentication service that is causing this. We are working on resolving this ASAP. You can follow this incident at our status page - https://status.getpostman.com/incidents/jy7fv1qs1k4b.

**Comment by numaanashraf** [comment]
@rayl-brbio our systems are operational and we are monitoring them. Please try logging back in.

Incident report: https://status.getpostman.com/incidents/jy7fv1qs1k4b
