### ISSUE TITLE
Postman times out and ask to login again

### ISSUE THREAD

**Issue by francesco1119** [a85/POSTMan-Chrome-Extension#5017]
Please read through the [guidelines](https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues) before creating a new issue.

**Describe the bug**
When I try to retrieve this URL with Postman:

`http://overpass-api.de/api/interpreter?data=[timeout:360];area[name="France"]->.a;(node(area.a)[amenity=cinema];way(area.a)[amenity=cinema];rel(area.a)[amenity=cinema];);out;`

Postman times out and asks me to login again with my Google account

**To Reproduce**
1. Open Postman
2. set the call as GET and paste the URL:

`http://overpass-api.de/api/interpreter?data=[timeout:360];area[name="France"]->.a;(node(area.a)[amenity=cinema];way(area.a)[amenity=cinema];rel(area.a)[amenity=cinema];);out;`

3. wait for Postman to timeout

**Expected behavior**
well... it shouldn't time out

**Screenshots**

**App information (please complete the following information):**
 - Desktop app
 - Postman Version v6.2.4
 - OS: Windows 10

**Additional context**

**Comment by numaanashraf** [comment]
@francesco1119 We have an ongoing outage with our authentication service that is causing this. We are working on resolving this ASAP. You can follow this incident at our status page - https://status.getpostman.com/incidents/jy7fv1qs1k4b.

**Comment by numaanashraf** [comment]
@francesco1119 our systems are operational and we are monitoring them. Please try logging back in.

Incident report: https://status.getpostman.com/incidents/jy7fv1qs1k4b
