### ISSUE TITLE
For URLs in exported JSON, the 'raw' property duplicates the information in the 'protocol', 'host', 'path' & 'query'

### ISSUE THREAD

**Issue by BrambleRamble** [a85/POSTMan-Chrome-Extension#5019]
**The current behaviour**
When a collection is exported to JSON v2.1 from Postman v6.2.4, the information for each request's URL is duplicated across properties in the JSON file.

**The problem this poses**
This makes it tricky to make bulk changes to the collection in a text editor, e.g. if the name of an endpoint changes and all instances need to be replaced. We tried to do this using find & replace, and because we only replaced the 'raw' properties, the changes didn't persist when the file was imported/exported later.

**The solution I'd like**
I'd like the url information to be stored once in the exported JSON, to facilitate making bulk changes quickly and confidently by editing the file directly.
Ideally I'd like to be able to do this on the raw URLs since the context can make pattern-matching easier. E.g. if I wanted to replace `path1/endpointA` with `path1/endpointB` and my file also contained `path2/endpointA`, being able to identify `path1/endpointA` would be more reliable than looking for `endpointA`.

**Alternatives**
Existing options (both tedious and error-prone):
- A 'replace all' can be done on the whole file to change the raw values. Then this can be diffed and the corresponding other property(s) can be changed to match.
- The requests can be edited manually in the editor.

Alternative possibility:
- Some kind of bulk find-and-replace built into the editor, to run on a collection or folder.

**Example**
```
{
	"info": {
		"_postman_id": "46ae211f-ed55-4526-92ca-7ecc02eb32ef",
		"name": "Example",
		"schema": "https://schema.getpostman.com/json/collection/v2.1.0/collection.json"
	},
	"item": [
		{
			"name": "Example request",
			"request": {
				"method": "GET",
				"header": [],
				"body": {},
				"url": {
					"raw": "http://beginning/middle/end?myParam=aValue",
					"protocol": "http",
					"host": [
						"beginning"
					],
					"path": [
						"middle",
						"end"
					],
					"query": [
						{
							"key": "myParam",
							"value": "aValue"
						}
					]
				}
			},
			"response": []
		}
	]
}
```
The components of the raw `http://beginning/middle/end?myParam=aValue` property are duplicated in the separate properties following it.

**Comment by BrambleRamble** [comment]
I can't spot if this is indicated on the issue anywhere, but this is intended as a feature request/suggestion, rather than being a bug with a clear-cut fix.
My team has been talking about this problem quite a lot and I wanted to share it in the hope of finding a more practical alternative, although I'm not sure what the best way is.

**Comment by kunagpal** [comment]
@Al54321 The perceived duplication is intentional (to avoid any possibility of losing information), as can be observed from the schema definition here: http://schema.getpostman.com/json/collection/v2.1.0/docs/index.html. As for the editor improvements, v6.2.4 of the Postman app provides an option to perform find and replace across multiple elements, as can be seen from the screenshot below:

<img width="1281" alt="screen shot 2018-08-13 at 10 24 23 pm" src="https://user-images.githubusercontent.com/7289840/44045970-ce7cfcf0-9f47-11e8-91f0-09adbb0dd177.png">

**Comment by BrambleRamble** [comment]
Thank you for the quick reply!

I can accept keeping the JSON as it is if that's necessary, and do appreciate that the duplication is by design. I don't directly see how the schema guards against loss of information though - it would be helpful to understand this in a bit more detail please.

I have accessed the Find panel using Ctrl+Shift+F - very useful to know about, thank you!
I'm struggling to access 'find and replace' or 'replace all' functionality that would compete with making bulk changes in a text editor though. I can open individual requests using the 'Open in builder' option, but the process of editing a large number of requests this way would still be quite tedious.
Possibly this functionality is present and the discoverability could just do with a bit of improvement though?

**Comment by prashantagarwal** [comment]
@Al54321 The bulk replace option is still in its beta stage and available in canary apps. You can download our canary app from https://www.getpostman.com/canary. Thanks

**Comment by numaanashraf** [comment]
Bulk find and replace is available in the stable version of Postman now
