### ISSUE TITLE
Feature Request: Onsite/private postman cloud

### ISSUE THREAD

**Issue by zorner** [a85/POSTMan-Chrome-Extension#5020]
**Problem:
Postman collections and variables contain security data that should not leave the internal company network.

**Desired:
I want a private onsite cloud, that acts like the current public postman cloud. I understand the data on the postman cloud is encrypted, but that does not meet our security needs. We are testing internal servers, and not only the request needs to stay interval, but also Postman collections and variables needed to make that request.

**Comment by h-parekh** [comment]
@zorner ICYMI The new version of postman allows 'sessions'. This feature may alleviate some of your needs for managing sensitive data. 

See [this](https://community.getpostman.com/t/ability-to-keep-variables-private/2550) postman community discussion thread for more details.

**Comment by zorner** [comment]
The problem with that solution, is the 'share' feature is still on postman's cloud. As my company does not own Postman's cloud it is outside the companies control, thus a security violation for sensitive data. That is why we need our own internal/on-site version.

**Comment by a85** [comment]
Sorry but there are no plans for a private cloud/on-prem version yet.
