### ISSUE TITLE
Add http.use_ssl to Ruby Code Snippets

### ISSUE THREAD

**Issue by chrisdeso** [a85/POSTMan-Chrome-Extension#5021]
**Describe the bug**
Add `http.use_ssl = true` parameter to Ruby code generation.

**To Reproduce**
1. Create a collection
2. Use the `Code` generation feature and select Ruby
3. View generated snippet and notice it's missing the `http.use_ssl = true` parameter

**Expected behavior**
Because Ruby requires an SSL connection to be established, a collection's Ruby-generated code should add `http.use_ssl = true`

**Additional context**
N/A

**Comment by abhijitkane** [comment]
@chrisdeso in Postman 7.2.1, we've introduced bug-fixes, support for two new languages (JS-Fetch and Powershell), and the ability to configure certain aspects of the generated snippet with the 'Experimental Codegen Mode' flag enabled in Postman's global settings.

This particular issue has been fixed, and can be seen with the 'Experimental Codegen mode' flag set.
