### ISSUE TITLE
Documentation – URL repeats if "https://" is present in unpublished docs

### ISSUE THREAD

**Issue by chrisdeso** [a85/POSTMan-Chrome-Extension#5022]
**Describe the bug**
If `https://` is present in the URL builder, everything prior to `https://` is repeated in the cURL snippet within unpublished documentation

**To Reproduce**
1. Create a collection and add a request that has an added `https://` somewhere in the URL
2. View the private documentation
3. See the incorrect cURL request generated

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/4734306/44063812-14821c20-9f17-11e8-9714-8717e3c01627.png)
![image](https://user-images.githubusercontent.com/4734306/44063820-1b0ca33a-9f17-11e8-9a05-7f9680366c28.png)

**App information (please complete the following information):**
 - App Type: Native App

**Comment by ankit-m** [comment]
This issue has been fixed.
