### ISSUE TITLE
Text is overflowing for long variable name in environment variable popover

### ISSUE THREAD

**Issue by dhineshwiz** [a85/POSTMan-Chrome-Extension#5031]
**Describe the bug**
Text is overflowing for long variable name in environment variable popover.

**To Reproduce**
1. Create a long variable name in environment
2. Use the same in request url
3. Hover over the variable, and popover appears with text overflowing.

**Expected behavior**
The text can be ellipsis for long variable names 

**Screenshots**

<img width="658" alt="screen shot 2018-08-16 at 1 14 47 pm" src="https://user-images.githubusercontent.com/10631268/44195842-e752f380-a157-11e8-9f88-1b447a62088c.png">

**App information (please complete the following information):**
 - Native App
 - Postman v6.2.4 
 - macOS High Sierra 10.13.4

**Comment by bhargavkaranam** [comment]
This has bene fixed in 6.4.x.

**Comment by bhargavkaranam** [comment]
This issue has been fixed in the latest version (6.5.x) of the Postman app.
