### ISSUE TITLE
Generate Code inserts wrong query parameters

### ISSUE THREAD

**Issue by ash007-postman** [a85/POSTMan-Chrome-Extension#5032]
When looking at my published API documentation, or generating code in the Postman app, it sometimes inserts query parameters that shouldn't be there.

It looks as if it caches old GET URL's for the request, when it had query parameters in the URL, and when removed, it still generates them in code snippets and documentation.

The generated code snippets would even contain entire wrong URL's occurring in previous copies of the collection.

This is quite serious, as I'd like to publish the documentation for my users, but can't publish wrong URL's

**Comment by numaanashraf** [comment]
@ash007-postman Could you post more information regarding the issue? Steps to replicate, screenshots etc?

**Comment by ash007-postman** [comment]
Unable to replicate the issue hence closing.
