### ISSUE TITLE
SHA-512 based signature in the update center doesn't match with the certificate in 'update site 'default''

### ISSUE THREAD

**Issue by xlion922** [a85/POSTMan-Chrome-Extension#5033]
Please read through the [guidelines](https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues) before creating a new issue.

**Describe the bug**
when click "check now" in plugin advanced page, the error "SHA-512 based signature in the update center doesn't match with the certificate in 'update site 'default'' will show up in webpage and backend.

**To Reproduce**
1. Go to '.manage Jenkins..'->manage plugin
2. Click on 'advanced.'
3. click "check now"

**Expected behavior**

**Screenshots**

**App information (please complete the following information):**
 - App Type [e.g. Chrome App, Native App]
 - Postman Version [e.g. 6.0.1]
 - OS: [e.g. macOS High Sierra 10.13.2]

**Additional context**

![image](https://user-images.githubusercontent.com/7436531/44198136-1dea3780-a173-11e8-8159-c7807d65e60c.png)

**Comment by numaanashraf** [comment]
@xlion922 This issue does not seem related to Postman. Closing.
