### ISSUE TITLE
[Linux] Disk space used multiplies after each update

### ISSUE THREAD

**Issue by Ramya-From-Postman** [a85/POSTMan-Chrome-Extension#5034]
**Describe the bug**
 Loaded tar.gz archive from www.getpostman.com/apps and unpack it to some folder. However, after the update, the folders like Postman-1530074526612, Postman-1530079605329, Postman-1530247417029  Postman-1534402914844.tar.gz etc, are not getting auto cleared and it is resulting in increasing the postman directory size every time when the update happens 

**Expected behavior**
The above-mentioned folders should automatically get cleared/deleted

**App information (please complete the following information):**
 - App Type  Native App
 - Postman Version 6.1.3
 - OS: Linux

**Comment by akadatsky** [comment]
This issue ware requested by me, feel free to ask me if you need any additional information.

**Comment by tribals** [comment]
I'm using Postman a lot in my day-to-day work. It is great tool, after all. But I just can't remain silent.

There is such ideas flying in the air - about state of programming nowadays. No one bothers about memory usage, size of distributions, performance - there is no need, they think. Indeed, why to bother? Tomorrow there will be a CPU with even greater frequency, memory manufacturers make module or SSD with even more GB's. But I disagree. We _must_ bother. If we want to call ourselves even an experts, professional craftsmen - we must. And I want to call you, the developers of Postman - to take care with me, too. So, I want to say it clearly - it is an arrogance - for desktop app, even written using not-so-skinny technology (Elector), to consume so many disk space! This is unacceptable - for me, at least.

Today I once again found out where the disk space has gone. I'he a 256 GB SSD - it is not so small. But I steel have to do such investigations once a month, roughly. After I looked at Postman's directory, I was completely discouraged. I decided to remove it immediately. Sorry about that.

**Comment by mikatuo** [comment]
How come? It even keeps updating (and making this mess) when "Automatically download major updates" is disabled. Please fix this. Or at least provide an option to disable auto-updates!

**Comment by michaelhays** [comment]
This issue appears to be fixed for me after going to Help > Check for Updates in the Postman Linux app, and updating Postman.

**Comment by lfir** [comment]
> This issue appears to be fixed for me after going to Help > Check for Updates in the Postman Linux app, and updating Postman.

I tried this and Postman's directory size went down from 3 GiB to 450 MiB.

**Comment by unoexperto** [comment]
Well, I noticed this only today, after Postman folder hit 57GB. And guys, 253MB per build for app that just sends HTTP requests, is a shame. You know, not long ago people wrote demos in asm that were 16kb and looked better than another Marvel movie :) Cheers.

**Comment by aleksandar-ninkovic** [comment]
I've seen A LOT of idiotic stuff over the many years I've spent behind the screen (~30 years since I wrote my first line of code in Basic on a ZX Spectrum) and thought there's not much out there left that can surprise me let alone shock me, until I accidentally opened the ~/Postman directory today and saw what's going on. At first I couldn't believe this was something the app did, I thought it might've been... I honestly don't know... but something else. And then I ran into this thread after googling the "issue" (< trying to keep it civil and avoid using any number of other more insulting but also much more fitting words), and it honestly blew my mind. Unlike unoexperto's case mine "only" got to around **28GB** since August 2018., the difference is probably due to the fact that I haven't been updating as often (I also had automatic updates disabled).

In my book this is seriously irresponsible, unacceptable, and also pretty unbelievable, especially if you account for the fact that not one out of almost 40 people (and 2 dogs) involved have noticed it for at least 8 months.

The fix is included in the v7.0.6 update released on 2019-03-13, you can see it in the changelog listed as:
```
[GitHub #5034] [Linux] Fixed an issue where the app was not clearing old app updates
```

**Comment by michaelhays** [comment]
@aleksandar-ninkovic relax dude, mistakes happen.

**Comment by tribals** [comment]
@michaelhays No, it's not. There is no justification for this...

**Comment by aleksandar-ninkovic** [comment]
@michaelhays  I get it, trust me, made my fair share of mistakes, and maybe I did overreact a bit ¯\_(ツ)_/¯ but I wouldn't even care or bother to comment if I didn't appreciate the app and the effort of the team behind it, it's just a little frustrating that the issue ended up wasting 10% of my free space even though the fix must've been completely trivial yet still took 5 months to implement (the earliest report was on October 10th, noticed it after my previous comment)

**Comment by michaelhays** [comment]
@aleksandar-ninkovic It is frustrating, no doubt. I just think it was a bit much to berate these people so severely.

Though, reading "2 dogs" did make me laugh quite a bit.

**Comment by Goltergaul** [comment]
This issue is indeed a bit annoying...  Has this been fixed in v7.0.6?

**Comment by numaanashraf** [comment]
@Goltergaul Could you update to the latest version of Postman (v7.1.1) and let us know if you are still facing this issue? We've pushed few fixes in Postman v7.0.9 that should address this issue.

**Comment by Goltergaul** [comment]
@numaanashraf Hi sorry I forgot to update here... Yes works now, thanks :)

**Comment by d-silva** [comment]
> This issue appears to be fixed for me after going to Help > Check for Updates in the Postman Linux app, and updating Postman.

In my case, 94 Gb wiped out by updating the app :sweat_smile:

**Comment by kasunsiyambalapitiya** [comment]
> This issue appears to be fixed for me after going to Help > Check for Updates in the Postman Linux app, and updating Postman.

This worked for me as well, 48GB was freed upon updating postman
