### ISSUE TITLE
Allow team administrators to transfer ownership of shared environments

### ISSUE THREAD

**Issue by chrisdeso** [a85/POSTMan-Chrome-Extension#5037]
**Is your feature request related to a problem? Please describe.**
When removing a user from a team, administrators are only able to transfer ownership of any collections that a user has shared within team workspaces. 

It's not uncommon for those collections to rely on shared environment templates, and the inability to retain that information may render collections unusable.

**Describe the solution you'd like**
An easy, self-serve, way for team administrators to transfer ownership of shared environment templates from one user to another.

**Comment by a85** [comment]
Will be handled through Role Based Access Control system.
