### ISSUE TITLE
Can't access examples for requests without a name

### ISSUE THREAD

**Issue by sankalp0o** [a85/POSTMan-Chrome-Extension#5038]
**Describe the bug**
If a request doesn't have a name (empty value), the interface doesn't allow accessing the example dropdown.

**To Reproduce**
1. Click on context menu of a collection from the sidebar
2. Click on 'add a request'
3. Leave the name field empty, hit save.
4. Click on the new request in the sidebar to open it.
5. Try to find the examples dropdown.

**App information (please complete the following information):**
 - Mac OS, native app
 - Postman Version 6.2.4

**Comment by sujayvenaik** [comment]
@sankalp0o 

We have identified this and will be out in our future releases.

**Comment by sujayvenaik** [comment]
@sankalp0o Hi, we have addressed this issue as part of various improvements we have made to how tabs work in Postman. These changes are up available on our canary channel (https://www.getpostman.com/canary) today and would soon be available on the stable channel. Do try these out in the canary and let us know.

**Comment by sujayvenaik** [comment]
This issue has been fixed and is available on the stable channel (v6.4.x). Now one cannot create an example without a name.
You can update the app to the latest version.

Thanks again for writing in and reporting this issue.
