### ISSUE TITLE
Feature request: Support for streamed responses

### ISSUE THREAD

**Issue by jimonthebarn** [a85/POSTMan-Chrome-Extension#5040]
With the advent of reactive streaming API's the handling of streamed responses becomes more and more important. Therefore I would love for postman to be able to handle streamed responses when setting the accept - header to application/stream+json or text/event-stream instead of the currently displayed 'Syntax error".

The response window could probably be updated when a new chunk of data comes in just like curl or httpie (with the --stream option) does. This probably needs a lot more thinking conceptually since it greatly differs from the way how responses are currently displayed in the response pane.

For the time being postman could wait for the stream to finish and output the result all at once just like httpie does when not started with the --stream parameter.

The alternative solution is currently to use curl or httpie which works but I'd love to be able to do this in my beloved postman. 😁

**Comment by jimonthebarn** [comment]
In the meanwhile we could probably update the "code" generated when creating a Shell httpie request to also contain the --stream parameter in case of streaming responses. Othwise httpie buffers the data and will only output it once the response is completely received.

**Comment by spanitz** [comment]
👍

**Comment by zeesattarny** [comment]
Is there any update on this? I am currently facing this issue and wanted to know if there is any work around to deal with streams in Postman response.

**Comment by 5thdimensional** [comment]
I'm also looking for this capability for testing our streaming API with Postman alongside our other collections.

**Comment by galen211** [comment]
This feature would be useful for interacting with ksqlDB, which has a [REST API endpoint for streaming queries](https://docs.ksqldb.io/en/latest/developer-guide/api/)

**Comment by matthenry87** [comment]
+1

**Comment by amoswood** [comment]
+1 as it would be useful for interacting with ksqlDB.

**Comment by wuf810** [comment]
+1

**Comment by alexrosenfeld10** [comment]
+1

**Comment by zionitcorp** [comment]
+1

**Comment by OwainPrice** [comment]
+1

**Comment by imjohnking** [comment]
+1

**Comment by arramanenka** [comment]
+1

**Comment by SummerShoohaw** [comment]
+1

**Comment by gaerfield** [comment]
As workaround some scripting helps. I inserted the script of this [stackoverflow-answer](https://stackoverflow.com/a/53934401/5029667) as Pre-request Script.
Within the GET-Adress-bar I used an arbitrary page (google, health-endpoint, doesn't matter). Because I was testing publish/subscribe, I triggered additionally some URLs within Tests. The Console logged everything.

Basic setup:
![image](https://user-images.githubusercontent.com/13051868/91532013-fa375b80-e90d-11ea-8e5f-16b2ba079c1f.png)

Pre-request Script (https://stackoverflow.com/a/53934401/5029667):
```
// This timeout ensure that postman will not close the connection before completing async tasks.
//  - it must be cleared once all tasks are completed or it will hang
const interval = setTimeout(() => {}, Number.MAX_SAFE_INTEGER);

let promiseNumber = 0;

function resolvedPromise() {
    return new Promise((resolve, reject) => {
        pm.sendRequest('https://domain.tld/subscribeToUser/karl' (err, res) => {
            if (err) {
                console.log(err);
                reject();
            } else {
                console.log(`Resolved promise ${++promiseNumber}`);
                resolve();
            }
        });
    });
}

resolvedPromise()
    .then(resolvedPromise)
    .then(resolvedPromise)
    .then(() => clearTimeout(interval))
    .catch(err => {
        console.log(err);
        clearTimeout(interval);
    });
```

Optionally issue scripts in the Tests-tab:
```
pm.sendRequest("https://domain.tld/sendToUser/karl/whoopwhoop1", function (err, response) {});
pm.sendRequest("https://domain.tld/sendToUser/karl/whoopwhoop2", function (err, response) {});
pm.sendRequest("https://domain.tld/sendToUser/karl/whoopwhoop3", function (err, response) {});
```

**Comment by vladimirov001** [comment]
+1

**Comment by tyukesz** [comment]
+1

**Comment by akhill10** [comment]
+1

**Comment by Zenegrad** [comment]
+1

**Comment by nithish-knetworks** [comment]
+1

**Comment by maxceem** [comment]
+1

**Comment by jomalla123** [comment]
+1

**Comment by OmiWakode** [comment]
+1

**Comment by aquiporras** [comment]
+1

**Comment by SebaPrati** [comment]
+1

**Comment by deiansp** [comment]
+1

**Comment by felaray** [comment]
+1

**Comment by maciek1839** [comment]
+1

**Comment by onigor** [comment]
+1

**Comment by cs12b015** [comment]
+1

**Comment by marchy** [comment]
What is the team's current roadmap priority on tackling this?

**Comment by e-ilyasse** [comment]
+1

**Comment by shubham-solytics** [comment]
+1

**Comment by sronelpol** [comment]
+1

**Comment by mtache** [comment]
+1

**Comment by arekfajdek** [comment]
+1

**Comment by Murali-P** [comment]
+1

**Comment by cristinacamilolima** [comment]
+1

**Comment by neexs** [comment]
+1

**Comment by ziadsarour** [comment]
+1

**Comment by ex-tag** [comment]
+1

**Comment by ex-tag** [comment]
Recommend cURL,
to anyone that needs to test SSE, HTTP/1 chunked encoding, or HTTP/2 responses.

**Comment by nathaniel-lehrer-ib** [comment]
+1

**Comment by hetthummar** [comment]
+1

**Comment by hu70258tao** [comment]
+10086

**Comment by sarfraaz-talat** [comment]
+10087

**Comment by RipVanTesla** [comment]
+1

**Comment by krishna-cactus** [comment]
+1

**Comment by jvdhehvg** [comment]
+1

**Comment by gaston-munoz** [comment]
+1

**Comment by nonlin** [comment]
+1

**Comment by yuhongsun96** [comment]
+1

**Comment by adriano515** [comment]
+1

**Comment by fsepulveda** [comment]
+1

**Comment by 1dustycy** [comment]
+1

**Comment by diegoquezadac** [comment]
+1

**Comment by j0hannr** [comment]
+1 🏄‍♂️

**Comment by emilypyq** [comment]
+1

**Comment by bhardwaj-nakul** [comment]
+1

**Comment by sh-git-repo** [comment]
+1, definitely needed

**Comment by saket-ranjan-010** [comment]
Hi folks, happy to announce that we now support SSE in Postman! Please check out the detailed announcement blog [here](https://blog.postman.com/support-for-server-sent-events/) and let us know what you feel about the experience.

Additionally, you can check out this Youtube video by us on how to use SSE in Postman to get up and running quickly: https://youtu.be/KrE044J8jEQ.

**Comment by ShubhamRasal** [comment]
+1, definitely needed

**Comment by vinogradoff** [comment]
Now as we have Postman support for SSE (text/event-stream), can we go for JSON Streaming (application/x-ndjson) support as well?

Should a separate Feature Request be created?

**Comment by saket-ranjan-010** [comment]
Hi there @vinogradoff , it would be great if you can create another feature request for supporting JSON streaming responses in Postman. It's easier for us to track and manage the feature requests that way. Thanks!

**Comment by rebecca-kovacs** [comment]
@jimonthebarn  -  I've found Apidog's SSE debugging exceptionally helpful. Their timeline view shows each streamed chunk in real-time, which is crucial when debugging AI model responses.The auto-merge feature for AI models (OpenAI, Claude, Gemini) that combines streaming fragments into complete responses.
