### ISSUE TITLE
In Pre-request scripts, environment variables calculation doesn't replace nested variables in request body

### ISSUE THREAD

**Issue by tenghuanhe** [a85/POSTMan-Chrome-Extension#5043]
**Describe the bug**

In a request body like:
```
{
    "id": {{lastResponseId}}
}
```

And in the request header there is another variable:
```
key: "sign",
value: {{signature}}
```
where the `{{signature}}` variable is set in "Pre-request script" with:
```
postman.setEnvironmentVariable("signature", CryptoJS.enc.Hex.stringify(CryptoJS.SHA1("abcdegf" + pm.request.body.raw)))
```

It seems that in the Pre-request script, when computing and setting environment variable `{{signature}}`, the actual value of `{{lastResponseId}}` is not used but a wrong value.

**To Reproduce**

**Expected behavior**

In Pre-request script, when computing and setting environment variable `{{signature}}`, use the actual value of `{{lastResponseId}}`.

**Screenshots**

**App information (please complete the following information):**

Native App
Postman for Windows
Version 6.2.4
win32 10.0.17134 / x64

**Comment by numaanashraf** [comment]
@tenghuanhe The variables in the request are resolved *after* the pre-request script is ran. So `{{lastResponseId}}` would still be unresolved when you read the body value via `pm.request.body.raw`. 

Now, there is a way to do the resolution in the pre-request script itself via the Postman SDK. I've attached a snippet below that does it for raw request body.

```
var Property = require('postman-collection').Property;

var resolvedBody = Property.replaceSubstitutions(pm.request.body.raw, pm.variables.toObject())
```

**Comment by Martin-Suska** [comment]
Actually it was useful for me to have it without unresolved variables, see my comment [here](https://github.com/postmanlabs/postman-app-support/issues/285#issuecomment-973645358).
