### ISSUE TITLE
How to extract value from html response and pass it on to next request in postman

### ISSUE THREAD

**Issue by sumthej** [a85/POSTMan-Chrome-Extension#5044]
Example url: https://abc.xyz.com/m# 

HTML Response:
<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
.
.
</head>
<body class="abc">        
.
.
.
.             
<script>xab.start('{\"first\":\"123xyz\",\"second\":\"abc123\",\"third"..;</script>
        </div>
    </body>
     </html>

In the above mentioned response i want to extract the value of the parameter second ("second\":\"abc123\") from the response and pass it on to the next request.

It would be simpler if the response is JSON, but in the case this is HTML response.

I was able to do this on JMeter using Regex but having hard time to do it on Postman.

Thanks!

**Comment by codenirvana** [comment]
@SumukhThej You can use the [cheerio](https://cheerio.js.org/) library included in[Postman Sandbox APIs](https://www.getpostman.com/docs/v6/postman/scripts/postman_sandbox_api_reference) for parsing HTML response.

Load cheerio in your test script like this:
```javascript
const $ = cheerio.load(responseBody);
```

**Comment by numaanashraf** [comment]
@SumukhThej Thanks for writing in. As per our [guidelines](https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues), these questions need to be asked on our [Community Forum](https://community.getpostman.com/).

> Answer to questions along the lines of "How do I... in Postman" should be in our online documentation at http://getpostman.com/docs. If you are unable to find a how-to guide in our online documentation, feel free to ask your question on our [Postman Community](https://community.getpostman.com/).
