### ISSUE TITLE
Contextual Menus for Tests in Runner

### ISSUE THREAD

**Issue by chrisdeso** [a85/POSTMan-Chrome-Extension#5046]
**Describe the solution you'd like**
It would be helpful to have a contextual menu in the test results page when inspecting test results in the collection runner. A key binding (like Option + Click) would be awesome!

**Additional context**
![image](https://user-images.githubusercontent.com/4734306/44322058-610d0a80-a400-11e8-8789-69c6c62ff7ba.png)

**Comment by numaanashraf** [comment]
@chrisdeso What actions would be useful via a context menu?

**Comment by chrisdeso** [comment]
A "load test" action would be great!

**Comment by vkaegis** [comment]
@chrisdeso What would "Load Test" do? Would this bring up the builder with the test in focus?

**Comment by chrisdeso** [comment]
Closing this one out due to inactivity on my end!
