### ISSUE TITLE
Activity Feed shows the deleted(removed) user name as remover name

### ISSUE THREAD

**Issue by Ramya-From-Postman** [a85/POSTMan-Chrome-Extension#5048]
**Describe the bug**
Let us say If user **A** is removed from the team, it should Ideally show that **User A was removed from the team** under the activity feed. However, it is showing as **User A removed a member of a team**.

**Expected behavior**
If user **A** is removed from the team, It should show that **User A was removed from the team**

**Screenshots**
Here, the highlighted users are removed from the team, they didn't remove anyone from the team.
![image](https://user-images.githubusercontent.com/40994626/44338194-d3322d80-a49a-11e8-80ac-283f14f6b99a.png)

**App information (please complete the following information):**
 - App Type  Chrome App, 
 - Postman Version  4.9.2

**Comment by ankit-m** [comment]
We are working on fix and I will update this thread once it is deployed.

**Comment by ankit-m** [comment]
A fix for this has been deployed.
