### ISSUE TITLE
Usage Overage Notification

### ISSUE THREAD

**Issue by Ramya-From-Postman** [a85/POSTMan-Chrome-Extension#5049]
**Describe the bug**
Even though the usage per feature is not over on any tier, the following error message has been displayed on the billing page. 

**Expected behavior**
The error should not be displayed unless the limit is actually exceeded.

**Screenshots**
![image](https://user-images.githubusercontent.com/40994626/44338716-7172c300-a49c-11e8-87fa-134184be50bc.png)

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version: 6.0.10
 - OS: win32-x64

**Comment by ankit-m** [comment]
@Ramyasri1212 Can you please include the screenshot of the full page?

**Comment by abhijitkane** [comment]
@ankit-m This is happening for enterprise teams with >0 configured custom auths. You can check our internal team's usage page.

**Comment by ankit-m** [comment]
@abhijitkane This is being worked upon. I will update this thread once it is deployed.

**Comment by ankit-m** [comment]
A fix for this has been deployed in the latest version.
