### ISSUE TITLE
History deletes are not synced

### ISSUE THREAD

**Issue by harryi3t** [a85/POSTMan-Chrome-Extension#5050]
After deleting histories (single or multiple) they are not synced with the Postman servers.
So if I sign-out and sign-in back, those histories are still there.

**To Reproduce**
1. Send a request to create a history
2. Delete the history
3. Sign-out and sign-in
4. History is still there

**Expected behavior**
I should not see the deleted histories

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version: n/a
 - OS: n/a

**Comment by kamalaknn** [comment]
This should be fixed in the latest version of Postman.
