### ISSUE TITLE
Postman not able to access URL link with spaces in it

### ISSUE THREAD

**Issue by MillieQP** [a85/POSTMan-Chrome-Extension#5051]
Postman is not reading this url - http://localhost:8888/Custom%20Post%20Types/

Here is the screen shot below
<img width="787" alt="screen shot 2018-08-20 at 9 41 12 am" src="https://user-images.githubusercontent.com/29005195/44343963-5b91dd80-a45d-11e8-90c2-bb0dfaadd005.png">

My other sites with no spaces are working. I tried restarting the app, put quotes around the website title and left the spaces in-between the website title. I don't know what else to do. 

Thank you

**Comment by oleg-barash** [comment]
Hi guys!
Same problem with other denied ASCII symbols. 
For example i called https://www.google.ru/search?q=26ю2199 from Postman, but my Fiddler says https://www.google.ru/search?q=26N2199
'ю' should be encoded to  %D1%8E, but i got just 'N'
btw, link 'code' works fine:
```
curl -X GET \
  'https://www.google.ru/search?q=26%D1%8E2199' \
  -H 'Cache-Control: no-cache' \
  -H 'Postman-Token: cd22a3f3-323c-4595-844a-8cc7b6025adf'
```

**Comment by srsilverglobe** [comment]
Similar issue with Zoho Desk API: `curl -X GET https://desk.zoho.com/api/v1/tickets -H "orgId:XXX" -H "Authorization:Zoho-oauthtoken 1000.XXX.XXX"` works but in Postman the space (just after Zoho-oauthtoken) seems to cause issues, even after replacing it with %20. FWIW https://apitester.com/ handles the space fine.

**Comment by vikiCoder** [comment]
Hi, we have made some significant changes relates to URL handling and it is available in the latest [Postman Canary](https://www.postman.com/downloads/canary) release (version 7.20.0-canary03). Issue mentioned in this thread is fixed as part of those changes. You can see more details about the changes at #8154. Please download the [Postman Canary](https://www.postman.com/downloads/canary) and see whether your problem is solved or not.

**Comment by codenirvana** [comment]
This is fixed in the latest version of the Postman app (v7.20.0) by enabling the "Use next generation URL processing" setting as mentioned in #8154.

Feel free to leave your feedback at #8154 or reopen this thread if the issue persists.
