### ISSUE TITLE
Trigger documentation sync manually

### ISSUE THREAD

**Issue by chrisdeso** [a85/POSTMan-Chrome-Extension#5054]
**Is your feature request related to a problem? Please describe.**
Sometimes changes to a collection is inadvertently saved, and the unwanted changes propagate across my published documentation.

**Describe the solution you'd like**
An extra step needed to deploy changes to published documentation would be extremely helpful in preventing any unwanted changes being propagated to my public-facing documentation.

**Describe alternatives you've considered**
Some type of indication/warning that the collection being saved is the underlying source of truth for my public documentation

**Comment by a85** [comment]
We will solve this using versioning for Postman collections.

**Comment by vkaegis** [comment]
You can now fork collections and merge changes back between them (as of v6.7.1). 

For this exact use case, this means that the collection whose documentation is published can be maintained as a fork of the main collection, and you can merge changes back to it as and when required. 

Closing this issue for now, feel free to open another issue if you have any feedback around the implementation!
