### ISSUE TITLE
Do you have any plans for Chinese?

### ISSUE THREAD

**Issue by joesdu** [a85/POSTMan-Chrome-Extension#5055]
Do you have any plans to support the language of other countries, such as Chinese.

**Comment by numaanashraf** [comment]
@Dygood Yes we do. But we haven't taken this up yet and I don't have an ETA on when we'ld be supporting Chinese.

**Comment by a85** [comment]
Closing as duplicate of https://github.com/postmanlabs/postman-app-support/issues/3126
