### ISSUE TITLE
No way to view all published documentation

### ISSUE THREAD

**Issue by sisodiyas** [a85/POSTMan-Chrome-Extension#5056]
**Is your feature request related to a problem? Please describe.**
There's no way to get a list of all the documentation that has been published. If, for any reason I want to unpublish all documentataion - I need to know all the documentation I've published - or go through every collection in all my workspaces.

**Describe the solution you'd like**
A single page/view that lists all the documentation I've published. Or at least all the documentation published from the collections in a given workspace.

**Comment by gitThingsDone** [comment]
The [Manage Public Section](https://learning.postman.com/docs/collaborating-in-postman/manage-public-elements/) in Postman allows you to see a list of all published docs in you team.
