### ISSUE TITLE
Monitor fetch problem

### ISSUE THREAD

**Issue by ash007-postman** [a85/POSTMan-Chrome-Extension#5058]
When I go to my monitors, there an error saying that there was a problem fetching my monitors. So I cannot do anything. 

This is for the user who is part of Expired Trial team.
<img width="1134" alt="screen shot 2018-08-21 at 6 29 06 pm" src="https://user-images.githubusercontent.com/41741228/44402803-5f625480-a570-11e8-8a47-c3eeb4f96869.png">

**Comment by a85** [comment]
Closing this as we have had several issues of monitoring pushed since then. Can't seem to replicate the issue.
