### ISSUE TITLE
Packaged app not working (Could not get any response)

### ISSUE THREAD

**Issue by mihkel** [a85/POSTMan-Chrome-Extension#506]
I'm having a really weird issue that I haven't been able to figure out. Every request that I'm sending turns out as "Could not get any response". A simple GET request to date.jsontest.com resolves to "Could not get any response" in packaged app but works fine in the legacy POSTMan. The problem is not specific to one endpoint, I've tried couple of endpoints and they all fail in the packaged app while working fine in legacy.

As far as I know I'm not setting any headers, url params or anything else.

The request preview tells me:
GET / HTTP/1.1
Host: date.jsontest.com
Cache-Control: no-cache

Is there any way to see what's happening under the hood of the new packaged app (console etc)?

I'm running latest stable chrome on OS X 10.9.1 using the chrome store versions of POSTMan.

**Comment by Jonathanp-jomedia** [comment]
Has anyone figured out what the issue is? I am also getting "**Could not get any response**".

Under it writes, "_This seems to be like an error connecting to..._" and when I click the following link Google Chrome opens it and returns what I expect so I don't get why it's not working with Postman...

I don't know why @a85 closed this issue. He didn't resolve anything.
If it's a bug where it's not trimming the URL than they should fix the bug.

I am using:
- Postman 3.0.5
- Chrome 44.0.2403.125 (64-bit)
- Ubuntu 14.04

**Comment by devoto13** [comment]
If I remember correctly it's a bug in the library for parsing urls, which causes the problem. As an easy fix you can install Postman as a standalone application instead of browser extension (if it's still relevant).

**Comment by Jonathanp-jomedia** [comment]
Thanks @devoto13. I think I have the standalone version installed (how to know for sure?).
I noticed something interesting when looking at my apache access log:

`127.0.0.1 - - [30/Jul/2015:10:21:40 -0400] "GET /foo/bar HTTP/1.1" 302 277 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.125 Safari/537.36"`
`127.0.0.1 - - [30/Jul/2015:10:21:47 -0400] "GET /foo/bar HTTP/1.1" 200 447 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.125 Safari/537.36"`

The first request was made with Postman, and for some reason it gets a HTTP 302, but doesn't follow the redirect.
The second was made via Chrome and it gets a 200 OK.

The error logs has nothing usefull.

**Comment by devoto13** [comment]
If you have it inside browser tab - it's extension, otherwise - it's a standalone application. A had this issue half a year ago, so probably my solution is just outdated.

**Comment by Jonathanp-jomedia** [comment]
Sometimes all you need is for someone to listen..

I do have the standalone version.
I rebooted my workstation and restarted Postman but nothing changed (I had installed system updates without restarting).
Then when I tried the URL in Chrome I did not just click the link from Postman, I copy & pasted it into a new incognito window, and finally I was able to get the same HTTP 302 that Postman was getting and I could move forward from there...

If this is happening to anyone else:
- First have a look at your server access logs to compare the responses between Postman and your browser for clues.
- Make sure to use the correct/intended protocol (HTTP or HTTPS) with Postman.
- Finally when you test your URL in a browser make sure to clear all your cookies (or just use incognito window in Chrome).

I was developing and testing on a local Apache server with self-signed SSL certificates for my host setup on my workstation.

**Comment by kevinmeredith** [comment]
I cleared my cookies and installed Postman 3.0, i.e the standalone version.

However, I'm still getting `"Could not get any response"` when accessing an internal URL. 

But, my web server can access this internal URL. Note that I'm running Chrome and the web server from the same machine.

**Comment by kevinmeredith** [comment]
On the standalone Postman 3.0, I saw this error due to an unsafe certificate.

I visited the `domain` of the URL that I was trying to hit. I accepted the unsafe certificate, and then restarted Postman. Finally, I was able to successfully issue an HTTP request.

**Comment by akapoor47** [comment]
From postman when I Copy/Paste link to chrome or directly click I am getting below error in Chrome - 
SSL server probably obsolete.
ERR_SSL_FALLBACK_BEYOND_MINIMUM_VERSION

MAC OS Version - OS X 10.10.5
Chrome Version - Version 45.0.2454.99 (64-bit)
Postman version - 3.2.2

@abhijitkane
