### ISSUE TITLE
Better two pane view

### ISSUE THREAD

**Issue by rosostolato** [a85/POSTMan-Chrome-Extension#5060]
**Is your feature request related to a problem? Please describe.**

Yes. I'm always frustrated when I change to two pane view because it makes harder to read the url container.

**Describe the solution you'd like**

Make Url container fill window width.

**Additional context**

Take a look at this image that I edited on Photshop to illustrate the solution:

![two pane](https://user-images.githubusercontent.com/27731641/44425146-70579980-a561-11e8-9fe5-9dca168038ba.png)

**Comment by prashantagarwal** [comment]
Duplicate of #2716
