### ISSUE TITLE
Postman 6.2.5 (Windows) does not show team workspaces, Web does

### ISSUE THREAD

**Issue by samcfinan** [a85/POSTMan-Chrome-Extension#5061]
**Describe the bug**
I am unable to change to a team workspace that I have already joined. The Team pane asks me to create a team workspace.

![teamworkspaces](https://user-images.githubusercontent.com/26390295/44430999-7bfb8e00-a56a-11e8-8084-450b85838848.PNG)

I have confirmed that I've joined the workspace by visiting the web interface.

**To Reproduce**
1. Click on the workspaces dropdown
2. Click on teams

**App information (please complete the following information):**
 - Native App
 - 6.2.5
 - Windows 10 Pro (1803)

**Additional context**
On opening the Chrome inspector, I'm receiving the warnings:

1. `Could not find on WorkspaceStore. Missing or invalid parameter.`
2. `Could not find on SyncWorkspaceStore. Missing or invalid parameter.`
3. `Could not find on CollectionStore. Missing or invalid parameter.`

![devtools warnings](https://user-images.githubusercontent.com/26390295/44431128-ed3b4100-a56a-11e8-9211-f3df287920de.PNG)

**Comment by samcfinan** [comment]
I found out my company didn't pay the invoice. I'm assuming this is why.

Messages need to be more clear, in any case.

**Comment by adenvt** [comment]
Get same issue

Native App
v6.3.0
Ubuntu 16.04
