### ISSUE TITLE
 Hawk auth preview header is missing 'app' field

### ISSUE THREAD

**Issue by bmdako** [a85/POSTMan-Chrome-Extension#5063]
Hi,

When using Hawk Authentication, the app param does not get inserted into the header.
This results in my Oz server responds with an "Mismatching application id".

To reproduce:

1. Open a new Tab in Postman
2. Insert a random request URL eg. http://localhost
3. Under Authorization, chose type "Hawk Authentication"
4. Insert a Hawk Auth ID e.g. "my_ticket_id"
5. Insert a Hawk Auth Key e.g. "my_ticket_key"
6. Open ADVANCED and insert an app e.g. "my_app_id"
7. Click the orange button "Preview Request" or just "Send"
8. Open the tab "Headers"
8. Verify that the Authorization header is missing "app=my_app_id"

I'm using Postman v6.2.5 on Windows 10.

Entering the request authentication:
![image](https://user-images.githubusercontent.com/6349363/44477192-3f976300-a63a-11e8-80e8-c1c1ffe4d840.png)

Preview of the with authorization header ("_app=_" missing):
![image](https://user-images.githubusercontent.com/6349363/44477265-6e153e00-a63a-11e8-9fb1-9c803a65f561.png)

**Comment by cweinberger** [comment]
Same with **Postman 6.4.2** on **macOS 10.14**.

**Comment by bmdako** [comment]
Hi @numaanashraf it's not just in the _preview_ the 'app' field is missing. It's missing from the request as well.

**Comment by harryi3t** [comment]
@bmdako Thanks for reporting this issue.
We have reproduced this on our end and are working on the fix.
Will update the thread once the fix is out.

**Comment by harryi3t** [comment]
@bmdako The fix is available in the latest version of Postman

**Comment by bmdako** [comment]
I have tested and the issue is resolved! Thank you very much.
