### ISSUE TITLE
Feature Request: Make HTTP Method painfully obvious

### ISSUE THREAD

**Issue by scottpantall** [a85/POSTMan-Chrome-Extension#5064]
**Is your feature request related to a problem? Please describe.**
Many times when I'm using Postman, I mean to use POST when I'm actually using GET and it makes me sad about myself when I repeatedly send a request using the wrong HTTP method because I didn't change the HTTP Method dropdown.

**Describe the solution you'd like**
I'd like the HTTP Method dropdown to be different colors based on which method is selected (ie. GET is orange, POST is blue, etc.)

**Describe alternatives you've considered**
An alternative would be to change the "Send" button to show "Send GET" or "Send POST" or something like that.

**Additional context**
I'd just like it to be painfully obvious which HTTP method I'm using before I send it.

**Comment by vkaegis** [comment]
@scottpantall Thanks for writing in! We're planning to use the same request method representation as the sidebar in the tab header as well as the method dropdown, so you'll at least have a color differentiator. We'll be pushing this out in the coming releases.

**Comment by scottpantall** [comment]
Awesome! Thanks a ton @vkaegis and @kamalaknn!

**Comment by kamalaknn** [comment]
Hi @scottpantall 

Here's a sneak peek of request icons in tab headers. We'll be rolling it out to stable channel in upcoming releases.

<img width="662" alt="screen shot 2018-08-25 at 9 39 13 pm" src="https://user-images.githubusercontent.com/8401064/44620304-99ed2980-a8af-11e8-9319-57a128dfc30d.png">

Hope this solves your requirement. Would appreciate feedback on this.
