### ISSUE TITLE
Add selectable checkbox to Postman values column in key/value section

### ISSUE THREAD

**Issue by tijaune** [a85/POSTMan-Chrome-Extension#5065]
Currently, PostmanApp have checkbox for each **key** column (see attached PostmanApp.png). It would be nice to also have checkbox for **value** column to enable/disable a value. This is for PostmanWeb consistency.

![postmanapp](https://user-images.githubusercontent.com/17985627/44488535-fc7fc480-a626-11e8-85fb-e003dbd865df.png)

In my example, I'll like to show guids on PostmanWeb as 1 of the possible parameter but I do not always want to activate the value there. It is not currently possible to have a nice web documentation to show every possible parameters without activating their hard wire value (each value could be for a specific test case) ... see the 2nd attached PostmanWeb.png

![postmanwebview](https://user-images.githubusercontent.com/17985627/44488543-05709600-a627-11e8-9ab2-de87fb1565c9.png)

**Comment by vkaegis** [comment]
@tijaune Thanks for writing in! Have you considered using environment variables in place of the values? With variables, you can specify "current" values which are local to your machine, while still publishing the actual key (with a blank value if you wish) along with the documentation.

**Comment by tijaune** [comment]
@vkaegis Hello, I already used environment for Authentication settings like ClientId, ClientSecret, ApiUrl. I did considered using environment variables but I had feeling it was wrong. With multiple controllers (collections), each having their section of variables, it seems unnatural to have to dive in environment edit to modify a parameter for the query.

The easiest thing I see on development perspective is to always display all keys on web but without their values (regardless of the "active key" checkbox status). Therefore, any analysts, project managers not having access to Postman can see all parameters of that request on the web pages documentation. For us developers, we already share our collection and can just click on "active key" at will to try :)

**Comment by vkaegis** [comment]
@tijaune That makes sense. Another possible avenue to explore is to use collection variables instead, but these don't show in the documentation right now. 

Keeping this open as a feature request for now.

**Comment by tijaune** [comment]
I just notice some web changes which I think is a very elegant solution. So I think you guys can close this feature request as it doesn't need anymore:

![image](https://user-images.githubusercontent.com/17985627/49042225-82b32600-f195-11e8-9214-a2c18c56a883.png)

Well done

**Comment by vkaegis** [comment]
@tijaune I'm presuming using session values worked? Glad this worked out. Feel free to open another issue if you have more feedback around this!
