### ISSUE TITLE
Monitoring graph – Add better navigation

### ISSUE THREAD

**Issue by chrisdeso** [a85/POSTMan-Chrome-Extension#5066]
**Is your feature request related to a problem? Please describe.**
It's fairly tedious to inspect older requests within the monitoring page graph, especially if the intervals at which the monitor runs is small.

**Describe the solution you'd like**
Add the ability to traverse the graph by hour/day/month/year.

**Describe alternatives you've considered**
An API for retrieving specific monitoring run results 😄 .

**Additional context**
![image](https://user-images.githubusercontent.com/4734306/44491164-3647cf80-a615-11e8-9f66-fef88b441b5e.png)

**Comment by ArjunSingh-PM** [comment]
You can now traverse through monitor runs based on time of the run.

https://learning.postman.com/docs/postman/monitors/viewing-monitor-results/#time-traverse
