### ISSUE TITLE
Update not working in native app(Linux)

### ISSUE THREAD

**Issue by santhoshTpixler** [a85/POSTMan-Chrome-Extension#5071]
**Describe the bug**
Whenever new version of postman in released, the update fails in the app. Which forces me to manually download the updates and install them. I have to do this every week due to the shorter release cycles.

**To Reproduce**
1. Go to 'Settings'
2. Click on 'Update failed, view detatils'
3. Click on 'Retry Update'
4. Click on 'Update'
5. Update failed pops again

**Expected behavior**
When I click update, It should update the app and ask me to restart the app.

**Screenshots**
![image](https://user-images.githubusercontent.com/10362257/44505637-20431900-a6c0-11e8-8564-5b345d961f27.png)

**App information (please complete the following information):**
 - App Type [Native App]
 - Postman Version [e.g. 6.2.4]
 - OS: [linux 4.8.0-040800-lowlatency / x64]

**Additional context**
I have been facing this issue for a long time. Even postman console shows nothing during this process.

**Comment by SamvelRaja** [comment]
@santhoshTpixler  
1. Could you share the logs from View->Developer->Show Devtools(CurrentView)
2. Are you behind any proxy environment?

**Comment by santhoshTpixler** [comment]
I have installed the postman in /opt. I think this could have been a problem as it required sudo premission to update the files. After starting postman in command line with sudo fixed the issue. But postman in not opening. It is loading for hours.
![image](https://user-images.githubusercontent.com/10362257/44518770-c145ca00-a6e8-11e8-9b09-151412bad942.png)

Finally deleted the .conf/Postman and Installed in home directory fixed the issue.

**Comment by SamvelRaja** [comment]
@santhoshTpixler  I am closing this as this is not related to auto-updater.
You can subscribe to #4359  for the issue you faced.
