### ISSUE TITLE
Less number of requests when I duplicate this collection

### ISSUE THREAD

**Issue by anudeepmedicharla** [a85/POSTMan-Chrome-Extension#5074]
Was just randomly testing guys. When I duplicate this particular collection (365 requests), the resulting collection will have only 350 requests. Don't know why. Uploaded the collection here.

[test.postman_collection.json.zip](https://github.com/postmanlabs/postman-app-support/files/2313706/test.postman_collection.json.zip)

**Comment by numaanashraf** [comment]
Fixed in Postman v7.1.0
