### ISSUE TITLE
Faulty cookie headers generated

### ISSUE THREAD

**Issue by aron123** [a85/POSTMan-Chrome-Extension#5076]
**Describe the bug**
If I have saved cookies for a domain, and I send cookies too in 'Cookie' headers, Postman generates a faulty request. For example with one saved cookie, and two cookie specified in header, Postman generates a request with two cookie headers: One header contains the two cookies that I specified in header, **separated with simple comma**, and then it contains the saved cookie, separated in standard way (with semi-colon). The other contains only the second cookie that I specified as HTTP header.

**To Reproduce**
1. Open Postman Console, and then open Cookie Management window
2. Add a cookie for a domain, and close 'Manage Cookies' window
3. Set up a GET request for the specified domain:
4. Set multiple Cookie headers (I specified two: foo=bar and bar=foo)
5. Send the request
6. On Postman Console, there is the request with the faulty Cookie headers

**Expected behavior**
One of the following options:
- Postman sends only one, correctly separated (with semi-colon) Cookie header with the 3 cookie (HTTP/1.1 way)
- Postman sends multiple (in this example 3) Cookie headers (HTTP/2 way)

**Screenshots**
[Saved cookie](https://i.imgur.com/XHzgExF.jpg)
[The faulty request](https://i.imgur.com/EsHuQUk.jpg)

**App information (please complete the following information):**
 - App Type: Native
 - Postman Version: 6.2.5
 - OS: Windows 10 (build 17134.228), x64

**Comment by codenirvana** [comment]
@aron123 Thanks for reporting this issue.
It's now fixed in the latest version of the Postman App (v7.7.2).
