### ISSUE TITLE
Click position is wrong on macOS

### ISSUE THREAD

**Issue by numaanashraf** [a85/POSTMan-Chrome-Extension#5080]
**Describe the bug**
Click position is off on macOS High Sierra. Originally reported by https://twitter.com/Octane/status/1032624743210524673

**App information (please complete the following information):**
 - App Type: Native
 - Postman Version: 6.2.5
 - OS: macOS High Sierra 10.13.6 (17G65)

**Comment by musabgultekin** [comment]
It happens because of zoom error. To reproduce, double finger click on touchpad (It zooms in). It happens to me so many times. How to solve ?

**Comment by numaanashraf** [comment]
Fixed in Postman v7.1.0
