### ISSUE TITLE
pm.test() doesn't work in pre-request script

### ISSUE THREAD

**Issue by crustater** [a85/POSTMan-Chrome-Extension#5081]
**Describe the bug**
pm.test() doesn't work in pre-request script

**Comment by kamalaknn** [comment]
We've fixed an issue where assertions from pre-request scripts were not shown in the Runner.

The fix is available on the latest version of the native apps. Please update and let us know if there are any issues.

**Comment by crustater** [comment]
Thank you, I can confirm it works in 6.7.1. BTW I cannot see how to
update/close ticket

**Comment by kamalaknn** [comment]
Thanks @crustater for the confirmation. I've closed the ticket.
