### ISSUE TITLE
Sync always copies current value to initial value

### ISSUE THREAD

**Issue by codewithtyler** [a85/POSTMan-Chrome-Extension#5082]
Please read through the [guidelines](https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues) before creating a new issue.

**Describe the bug**
The Current Value is getting copied to Initial Value during sync which is causing sensitive data (i.e. user credentials) to be copied to your server.
I created a new environment variable containing a password for logging into our system. I left the initial value blank and added the 

**To Reproduce**
1. Go to Postman
2. Click on Manage Environments button (the gear icon)
3. Click on environment
4. Create new variable but leave the Initial Value blank. You should only have a value in the Current Value cell.
5. Wait for Postman to sync to or you can click the sync button at the top.
6. Go back in and look at your environment.
7. The variable will now have your value saved to both the Initial Value cell as well as the Current Value cell which means it is synced with the server.

**Expected behavior**
I expected the Initial Value cell to still be blank.

**App information (please complete the following information):**
 - Postman for Windows
 - Postman Version 6.2.5
 - Windows 10 Pro 64-bit

**Comment by harryi3t** [comment]
@tylerbhughes Could you make sure you turn off the `Automatically persist variable values` setting from the settings modal and try again?
<img width="721" alt="postman 2018-08-23 23-09-19" src="https://user-images.githubusercontent.com/5207331/44542221-cd05b080-a729-11e8-8270-4e519d7e6108.png">

Note: For existing users upgrading to newer version of Postman app, this setting is turned on by default.

Also, this is what I tried to reproduce this but wasn't able to. If I missed something, please let me know.
You can even post a gif/screen-recording if you are able to reproduce this consistenly.
![5082](https://user-images.githubusercontent.com/5207331/44542614-fa069300-a72a-11e8-8e30-090854b8894d.gif)

**Comment by codewithtyler** [comment]
@harryi3t that was it. Once I turned that setting off it quit copying to the Initial Value. I'll have to make sure the rest of my team is aware of that setting. Thanks for the help!

**Comment by newthomas** [comment]
@harryi3t Can we turn this off by default for our team account? It does not make sense to have it enabled by default, because it spreads usernames and passwords from our developers.

**Comment by roberto8080** [comment]
@harryi3t Indeed, we have identified this a security issue when using Postman in our organisation. The more secure behaviour should be off by default.

**Comment by harryi3t** [comment]
@roberto8080 @newthomas 
I agree, the only reason we chose the default value to be `on` was to avoid any surprises when users update their applications
Although, I have opened a separate feature request for suppoting team level settings 
 https://github.com/postmanlabs/postman-app-support/issues/5146

**Comment by newthomas** [comment]
Sounds good, thank you. @harryi3t
