### ISSUE TITLE
Command unescape javascript dont'n working in Tests

### ISSUE THREAD

**Issue by Guilherme-Sensedia** [a85/POSTMan-Chrome-Extension#5083]
In Tests Window, command unescape javascript not working.
![captura de tela de 2018-08-23 12-30-32](https://user-images.githubusercontent.com/40179240/44535448-656f4700-a6d0-11e8-89d6-3168a511c0ec.png)

**App information (please complete the following information):**
 - Chrome App
 - Postman Version [6.2.5]
 - OS: [e.g. Ubuntu 18.04.1 LTS]

**Comment by codenirvana** [comment]
@Guilherme-Sensedia Can you share a sample collection with this behavior?

I tried to reproduce this issue, but its working as expected.

<img width="542" alt="unescape-screen-shot" src="https://user-images.githubusercontent.com/4865836/45943547-66173800-c004-11e8-9b10-22d19cd532f4.png">

**Comment by Guilherme-Sensedia** [comment]
@codenirvana follow this example:

![captura de tela de 2018-09-24 08-34-54](https://user-images.githubusercontent.com/40179240/45950169-08b7c280-bfd5-11e8-95ec-6522d7dbe2bc.png)

**Comment by codenirvana** [comment]
@Guilherme-Sensedia That's correct, you can verify this by running the following snippets in your Node/JavaScript console:

```console
$ escape('&')
"%26"

$ unescape('%26')
"&"

$ unescape('&amp;')
"&amp;"
```

I got your issue, `&amp;` is not `unescape`d to `&`. But that's the expected output.

You need to replace the occurrence of `&amp;` with `&` by doing something like:
```javascript
str.replace(/&amp;/g, '&');
```

**Comment by Guilherme-Sensedia** [comment]
Ok, thanks!
