### ISSUE TITLE
The response search bar shows up over the find overlay

### ISSUE THREAD

**Issue by abhijitkane** [a85/POSTMan-Chrome-Extension#5084]
**Describe the bug**
The response search bar shows up over the find overlay

**To Reproduce**
1. Get a response
2. Cmd/Ctrl+F in the response section to open the editor's find box
3. Open the Find overlay
4. The search bar stays floating on top

**Expected behavior**
The search bar should stay where it's supposed to.

**Screenshots**
<img width="976" alt="screen shot 2018-08-24 at 00 13 37" src="https://user-images.githubusercontent.com/681190/44545506-e65f2a80-a732-11e8-96bf-22cecafbcef6.png">

**App information (please complete the following information):**
Postman for Mac, Version 6.2.5, OS X 17.3.0 / x64

**Comment by bhargavkaranam** [comment]
This has been fixed in the latest release 6.3.0.
