### ISSUE TITLE
Team sharing collection limits are not re-calculated correctly when data is deleted.

### ISSUE THREAD

**Issue by centur** [a85/POSTMan-Chrome-Extension#5087]
Please read through the [guidelines](https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues) before creating a new issue.

**Describe the bug**
When entire collection deleted from team shared workspace - shared requests limit is not re-calculated.
On free account there is a limit of 25 shared requests. It's quite easy to reach by exporting any existing collection from personal to team workspace. Problem is - when entire collection is deleted - shared requests limits are not re-calculated. Check the image - no collections in shared workspace but "Shared Requests" on the right shows 21

**To Reproduce**
0. Use free account.
1. Go to Manage teams on the web, switch to team workspace and export any personal collection. I've used "Postman Echo" from samples (21 requests)
2. Go back to postman client and wait till everything syncs.
3. Delete collection (Same happens when using Collection-> `...` Remove from workspace) from postman client in Team Shared workspace.
4. See (screenshot displays exact problem) that client doesn't reflect the correct number of requests in shared collection. there is no requests but limits show 21/25.

**Expected behavior**
Expected client to reflect the correct number of shared requests.

**Screenshots**
![image](https://user-images.githubusercontent.com/720822/44568116-bb1f1e80-a7b8-11e8-9f15-c056d5cbe194.png)

**App information (please complete the following information):**
 - App Type: Native app (electron based)
 - Postman Version:  v6.2.5 
 - OS: Windows 10

**Additional context**
One way to fix it ( what I found so far) is to add an empty collection to team workspace and delete it.
Another way is to do it via managing  team in web interface

**Comment by dhineshwiz** [comment]
Hey @centur thanks for reporting this issue. It looks like the call for updating the usage values are being throttled. We will look into this and keep you updated

**Comment by centur** [comment]
Hi, @preethammavin , was this issue fixed ?

**Comment by preethammavin** [comment]
@centur we throttle the calculation for about 3-5 seconds for refresh. The overall issue has been fixed, once the request/collection has been deleted and synced we recalculate immediately on our backend, the UI refreshes every 5 seconds for rate limiting purposes.
