### ISSUE TITLE
Add -L (--location) to generated cURL code

### ISSUE THREAD

**Issue by bkmeneguello** [a85/POSTMan-Chrome-Extension#5089]
When the flag "Automatically follow redirects" is checked, the generated cURL shoud add the corresponding `--location` or `-L` flag

**Comment by abhijitkane** [comment]
@bkmeneguello 

Can you try this is Postman 7.2.1, with the 'Experimental Codegen Mode' flag enabled in Postman's global settings? We've introduced bug-fixes, support for two new languages (JS-Fetch and Powershell), and the ability to configure certain aspects of the generated snippet.

For this particular use-case, there's a separate curl-level 'Follow redirects' setting, which you can control once you've selected `cURL` in the language selector.
