### ISSUE TITLE
Chosen file are not retained in the latest version windows(6.2.5)

### ISSUE THREAD

**Issue by karthiksml** [a85/POSTMan-Chrome-Extension#5094]
Chosen file are not retained in the latest version windows(6.2.5)

#4241 - refer this. we are facing the same issue now with the latest version.

**Comment by numaanashraf** [comment]
@karthiksml Could you detail the steps you took? Looks like your issue is similar to #4320.

**Comment by karthiksml** [comment]
Yes. It's the same.

will it be considered in the next release? Please let me know.


Thanks,
Karthik J

**Comment by numaanashraf** [comment]
@karthiksml We are working on this, but we do not have an ETA on this yet. We would post any updates regarding early design feedback and canary and stable releases on #4320. Closing this as duplicate.

**Comment by karthiksml** [comment]
Thanks for the update.
