### ISSUE TITLE
Postman Windows App does not save queries

### ISSUE THREAD

**Issue by jonasglass** [a85/POSTMan-Chrome-Extension#5095]
Changes in a saved request (e.g. changing URL) are shown by indicating with the orange cycle. Pressing CTRL-S or clicking Save does not affect anything. Also when closing it and on clicking save changes the changes are not saved. Adding new queries is also not possible. Issue still occurs after reinstallation and also when using admin rights. When changing a shared collection via the Chrome App the changes are being pulled in the Windows App of Postman.

Version 6.2.5
win32 6.1.7601 / x64

**Comment by kamalaknn** [comment]
Hi @runner95 

Do you see any errors in DevTools when you save? Please check the `View -> Developer -> Show DevTools(Current View)` and share any error logs you.

**Comment by numaanashraf** [comment]
@runner95 We are having trouble replicating this issue at our end and this seems to be an isolated issue. Please re-open if you are still facing this issue.
