### ISSUE TITLE
Visualisation of x-www-form-urlencoded parameters in console

### ISSUE THREAD

**Issue by slecholineas** [a85/POSTMan-Chrome-Extension#5096]
**Describe the bug**
When I click on ‘Raw’ in the console I see that my x-www-form-urlencoded parameters are not separated with the ‘&’-sign. 

**To Reproduce**
1. Create a new request
2. Add in the Body at least 2 x-www-form-urlencoded parameters
3. Open the console
4. Send the request
5. In the console open the request
6. Click on Raw: the x-www-form-urlencoded parameters are **not** separated with the '&'-sign.

**Expected behavior**
The x-www-form-urlencoded parameters must be separated with the '&'-sign.

**Screenshots**
![image](https://user-images.githubusercontent.com/42738911/44662996-8eb10f80-aa0f-11e8-9b0c-63010e36139f.png)

**App information (please complete the following information):**
 - App Type [Native App]
 - Postman Version [e.g. 6.2.4]
 - OS: [Windows 10]

**Comment by robin-dongbin** [comment]
Same bug, And I found that there is no `Content-Type: application/x-www-form-urlencoded` when Add in the Body at least 2 x-www-form-urlencoded parameters

**Comment by numaanashraf** [comment]
Fixed in Postman v7.0
