### ISSUE TITLE
是否能加入生成API文档的功能

### ISSUE THREAD

**Issue by whyzhiqiu** [a85/POSTMan-Chrome-Extension#5097]
# 是否能加入生成http接口文档的功能
现在测试完http接口还要自己手写文档，太麻烦了。

**Comment by numaanashraf** [comment]
Translation:

Can I add the ability to generate API documentation?
Can I join the function of generating http interface documents?
Now it's too much trouble to test the http interface and write the document yourself.

**Comment by numaanashraf** [comment]
API documentation is already supported - https://www.getpostman.com/docs/v6/postman/api_documentation/intro_to_api_documentation
