### ISSUE TITLE
Scrolling not working correctly on external monitor

### ISSUE THREAD

**Issue by ash007-postman** [a85/POSTMan-Chrome-Extension#5098]
I have a 4k high DPI laptop screen with a 2560 x 1440 monitor. I've tried several high DPI settings in windows, but the behavior seems to stay the same.

I've attached screenshots which show the apparent scroll boxes on my monitor. In the first screen shot, the area within the green square will scroll the left Collections pane while the red will scroll the pane with the response body, etc. Scrolling outside of these areas doesn't work at all.

![postmanscrollingscreenshot](https://user-images.githubusercontent.com/41741228/44705655-e48fc100-aabc-11e8-9ca0-37cdf8b83224.PNG)
![postmanscrollingscreenshot2](https://user-images.githubusercontent.com/41741228/44705657-e48fc100-aabc-11e8-9526-079ec6d8a283.PNG)

**Comment by SamvelRaja** [comment]
Related to https://github.com/postmanlabs/postman-app-support/issues/4849
