### ISSUE TITLE
Discrepancies in monitor summary & email notifications

### ISSUE THREAD

**Issue by ash007-postman** [a85/POSTMan-Chrome-Extension#5099]
I have been using Monitors with daily run for a few weeks, but I encounter some trouble. 
The summary of each launch tells there are errors, but all squares are green. (see first screenshot) 
In addition, the email notifications I get all tell that there is a 0% success rate.

This is very annoying since these inaccuracies make any report useless.

<img width="1117" alt="capture d ecran 2018-08-27 a 21 58 17 1" src="https://user-images.githubusercontent.com/41741228/44706460-3fc2b300-aabf-11e8-9c29-928fa09fd540.png">
<img width="488" alt="capture d ecran 2018-08-27 a 22 01 06" src="https://user-images.githubusercontent.com/41741228/44706462-3fc2b300-aabf-11e8-8365-7587e738b655.png">

**Comment by godfrzero** [comment]
The 0% success rate and failing runs are due to errors in the run. The UI states that there were *0 failed tests, 3 errors, ...*. Details about these errors can be found in the console.
