### ISSUE TITLE
Wrong state for Select all toggle in Replace feature

### ISSUE THREAD

**Issue by sumit0k** [a85/POSTMan-Chrome-Extension#5100]
**Describe the bug**
Select All toggle is shown as checked even if nothing is checked

**To Reproduce**
1. Click 'lens' icon for Find and Replace
2. Find for something
3. Type something in `Replace With` and check `Select All`
4. Click `Find` again

**Expected behavior**
`Select All` toggle should be unchecked if nothing in find results is checked
 
**Screenshots**
https://www.dropbox.com/s/ylx0qyfvpidsc5z/Screenshot%202018-08-28%2014.32.33.png?dl=0

**App information (please complete the following information):**
 - App Type [PostmanCanary Native App]
 - Postman Version [6.2.5-canary01]
 - OS: [macOS High Sierra 10.13.6]

**Additional context**
Make sure to click `Find` again after toggling `Select All`

**Comment by numaanashraf** [comment]
This issue has been fixed in Postman 7.0
