### ISSUE TITLE
Remember window position and size while switching accounts

### ISSUE THREAD

**Issue by numaanashraf** [a85/POSTMan-Chrome-Extension#5101]
Originally reported via Twitter: https://twitter.com/matthewusurp/status/1034365989612343296

**Comment by matt-usurp** [comment]
Just so there is a physical copy against the issue. 

> @postmanclient Look, I love you and we have been seeing each other for like 4 years. But when changing accounts stop resizing my window and moving it to my primary monitor. Then I have to resize all the panels in the client as its all reset to factory defaults.

Thanks for creating the bug for me 🙈
