### ISSUE TITLE
Add support to use a file as the value in a form field

### ISSUE THREAD

**Issue by tyrinslys** [a85/POSTMan-Chrome-Extension#5102]
I was trying to setup a request to use the api linter for jenkins piplines:
https://jenkins.io/doc/book/pipeline/development/#linter

and found that it is not currently possible with Postman.

Specifically it requires the text of the file to be the value part of the `jsonfile` form field key.

I would prefer to have a postman request when monkeying with the file but alas, curl it is.

**Comment by a85** [comment]
Postman supports file uploads so not sure why this is not possible.
