### ISSUE TITLE
Proxy settings not working when using System Proxy > Use automatic configuration script

### ISSUE THREAD

**Issue by tjraskin** [a85/POSTMan-Chrome-Extension#5103]
We are using the Postman for Windows v6.2.5 application to test a local RESTful service.  The Proxy setting was set to "Use System Proxy".  

The call to the RESTful service got a HTTP Error Status: 403 Forbidden - Error Reason: Forbidden port.  This occurred on a Windows 10 machine and was replicated using the same Postman for Windows client on a Windows 7 machine. 

Both machines are configured to "Use automatic configuration script" in their Proxy Settings (this is not available as an option in the Postman Proxy tab).  

We were able to test this RESTful service successfully using the Postman Chrome client and also YARC.

**Comment by dietbos** [comment]
Same here, getting a 403 message in the "new" app > while the old one using chrome works fine. 

Will this be solved?

**Comment by codenirvana** [comment]
@tjraskin @dietbos Sorry for the delayed response. Can you share more details about the Proxy (does it require Proxy Authentication) and how its configured in the Postman app?

Also, is it working by setting the global proxy configuration?

**Comment by tjraskin** [comment]
Hi codenirvana,

I have not tried the Postman client in a while, so I am not sure if this issue was fixed or not.  There are two proxy options: Global Proxy Configuration (turned off by default; this allows specification of the proxy server, etc.) and Use System Proxy (turned on by default).  "Use System Proxy" did not work. If I am correct, would this have used the same proxy settings in IE?

Thanks, Tom

**Comment by codenirvana** [comment]
@tjraskin Yes, system proxy will reuse same proxy configurations as in IE but if the proxy authentication is required then it will not work as proxy auth credentials will not be shared. In that case, you can configure global proxy with the authentication credentials.

Closing this issue as we are not able to reproduce this internally and we haven't seen other users facing the same.

Please feel free to reopen if the issue persists.
