### ISSUE TITLE
Right click not working for response headers

### ISSUE THREAD

**Issue by Leeeeeeelo** [a85/POSTMan-Chrome-Extension#5107]
**Describe the bug**
Performing a right click inside the headers tab of the response does not yield any result. It used to work fine a while ago. It is currently working fine in the body tab of the response.

**To Reproduce**
1. Perform an API request using Postman.
2. Click on on the Headers response tab.
3.1 Try to right click on any value.
3.2 Try to right click on any selected text.

**Expected behavior**
The expected behavior is to have a pop up displayed when right clicking on any value or selected text, in order to perform various actions such as cut, copy or set the value / selected text inside a variable, exactly just like it occurs inside the Body response tab.

**App information:**
 - App Type: Postman for Windows
 - Postman Version: 6.2.5 win32 10.0.17134 / x64
 - OS: Windows 10 Version 1803 (OS Build 17134.228)

**Additional context**
It used to work fine a while ago. It stopped working several weeks back.

**Comment by bhargavkaranam** [comment]
Thank you for reporting this. This issue has been fixed in the latest version (6.5.x) of the Postman app.
