### ISSUE TITLE
The collection link in the monitoring->slack integration gives a 404

### ISSUE THREAD

**Issue by abhijitkane** [a85/POSTMan-Chrome-Extension#5108]
**Describe the bug**
The collection link from the Monitoring>slack integration gives a 404

**To Reproduce**
1. Set up a monitoring->slack integration
2. Get a failure notification for a failed run:
Monitor <monitor name> on Collection <collection name> did not run successfully. 103 requests ran and 12 tests failed

Clicking on <collection name> takes me to the old URL: https://documenter.getpostman.com/collection/view/<collection-uid>, which gives a 404

Server-side bug, seen on 2018-08-29

**Comment by JP-from-Postman** [comment]
Same issue appears to be affecting the Slack integration for Team Activity.

**Comment by towerjoo** [comment]
Any update on this issue?

And also this fails even for our activity integration.

**Comment by ankitjaggi** [comment]
@abhijitkane @JP-from-Postman @towerjoo This issue has been fixed from our side. Can you confirm?

**Comment by abhijitkane** [comment]
@ankitjaggi I added an integration on a failing monitor, and ran the monitor a few times, but there's been no post to the slack channel for 2-3 minutes.
