### ISSUE TITLE
The format of etag header of response is changed by postman

### ISSUE THREAD

**Issue by JojoWu19** [a85/POSTMan-Chrome-Extension#5109]
**Describe the bug**
The format of etag header of response is changed to start with `W/` by postman.

**To Reproduce**
1. Get a URL which provides etag header.
2. Go to the "Headers" of response.
3. Check the format of etag.

**Expected behavior**
The format of etag header shall be same as the format of etag header of real response.

**Screenshots**
![postman_win_etag](https://user-images.githubusercontent.com/36840032/44769395-0d848480-ab97-11e8-8718-8ca961230ed0.jpg)

![postman_etag](https://user-images.githubusercontent.com/36840032/44768358-9e596100-ab93-11e8-96da-4657f59763df.jpg)

[curl_etag.log](https://github.com/postmanlabs/postman-app-support/files/2330894/curl_etag.log)

**App information (please complete the following information):**
 - App Type:  Postman for Windows
 - Postman Version: 6.2.5
 - App Type:  Postman for Chrome (Chrome 68.0.3440.106)
 - Postman Version: 5.5.3
 - OS: Windows 7 SP1 (win32 6.1.7601 / x64)

**Additional context**

**Comment by numaanashraf** [comment]
@JojoWu19 Are you facing the same issue in both Chrome and Native apps?

**Comment by JojoWu19** [comment]
Yes, I also have posted both screenshots in issue.

**Comment by numaanashraf** [comment]
@JojoWu19 Could you verify if the server is returning the correct etag. "W/" is an optional prefix that is valid in the spec and certain servers will add it. https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/ETag#Directives. You can debug what response Postman received by following the steps detailed here - https://www.getpostman.com/docs/v6/postman/sending_api_requests/debugging_and_logs#network-calls-with-postman-console

**Comment by JojoWu19** [comment]
Yes, I have verified the etag value.  I used curl to get the raw data and also have attached the log at issue (curl_etag.log).

**Comment by numaanashraf** [comment]
@JojoWu19 cURL logs does not guarantee that the server returned the same etag value format to Postman. Since this is a valid etag format as per spec, there is a chance that the server returned the "W/" format to Postman. Please provide the raw network logs of Postman as detailed here so that we can debug this further - https://www.getpostman.com/docs/v6/postman/sending_api_requests/debugging_and_logs#network-calls-with-postman-console

**Comment by JojoWu19** [comment]
We implement the etag of server so I know its' value but if you need the debug log. I will attach later.

**Comment by JojoWu19** [comment]
@numaanashraf,
Here is the postman console log:
[postman_console.log](https://github.com/postmanlabs/postman-app-support/files/2348422/postman_console.log)

It looks the etag value is with "W/" in the postman console but I think curl should be right because server remove the "W/" from etag.  I will need environment to check if cURL displayed "W/" when etag start with "W/" and then update to you tomorrow.

**Comment by JojoWu19** [comment]
@numaanashraf,
After checking the old environment that server provides etag always include "W/", cURL display the etag header with "W/", and cURL is correct to show the real etag value.  below is the cURL log to get the etag includes "W/".  I think even Postman console has this issue.
[curl_weekETag.log](https://github.com/postmanlabs/postman-app-support/files/2351499/curl_weekETag.log)

**Comment by JojoWu19** [comment]
This is not a bug of postman. In the nginx, when request headers include "Accept-Encoding: gzip", the etag is weak format. The reason is POSTMAN sends request with "Accept-Encoding: gzip ..." by default and doesn't display this header in the Code so using CURL without "Accept-Encoding" will get a correct etag header.
Close this.
