### ISSUE TITLE
Postman App U.I. Colors:: Light-grey on white unfriendly to people with visual challenges and impairments ...

### ISSUE THREAD

**Issue by nmvega** [a85/POSTMan-Chrome-Extension#5112]
Hello Friends:

How can one change the **light-gray lettering** on **white background** color scheme, minimally to black lettering? That color scheme is unfriendly to people with visual challenges and impairments.

Is there a style file (or something) you can give me to insert/replace into the installation directory to change that?

Thank you!

**Comment by sivcan** [comment]
@nmvega As of now we do have a dark mode built into the apps.
You can go to Settings > Theme 
Refer: https://www.getpostman.com/docs/v6/postman/launching_postman/settings

Also, there's already a feature request raised for personalizing the themes in the app: https://github.com/postmanlabs/postman-app-support/issues/4318

So I'll be closing this issue.
For any updates regarding themes in the app kindly follow the https://github.com/postmanlabs/postman-app-support/issues/4318 thread.
