### ISSUE TITLE
"Could not get any response"  Error: Invalid Protocol: localhost

### ISSUE THREAD

**Issue by GingerMoon** [a85/POSTMan-Chrome-Extension#5114]
Don't know why this error happens...
![image](https://user-images.githubusercontent.com/8342412/44838893-e8b01000-ac6f-11e8-9b80-8062fbd62d15.png)

I have already disable the mentioned configurations.
![image](https://user-images.githubusercontent.com/8342412/44838916-ffeefd80-ac6f-11e8-9fc9-dd1c08628015.png)
![image](https://user-images.githubusercontent.com/8342412/44838945-0e3d1980-ac70-11e8-9c25-116c2dc00298.png)

version: "You are up to date! Postman v6.2.5 is the latest version."
windows 10 
![image](https://user-images.githubusercontent.com/8342412/44839018-45abc600-ac70-11e8-90b5-2325ada6bc56.png)

**Comment by harryi3t** [comment]
do you have environment variables for proxy setup in your system?
To check this just echo them in your shell
```
echo http_proxy
echo https_proxy
echo HTTP_PROXY
echo HTTPS_PROXY
```

**Comment by GingerMoon** [comment]
yes。。。thank you very much！ After delete them, it works!

**Comment by harryi3t** [comment]
@GingerMoon Glad that it worked. There is no problem with keeping them, they just need to be complete with the protocol. For e.g. instead of `http_proxy=localhost:8080` you should have `http_proxy=http://localhost:8080`

**Comment by GingerMoon** [comment]
Thank you very much @harryi3t , it works. Really appreciated!

**Comment by chucklu** [comment]
@harryi3t  Encounter the same problem caused by proxy without protocol specified. Thanks for your solution.
