### ISSUE TITLE
The team/elements page doesn't show any monitors

### ISSUE THREAD

**Issue by abhijitkane** [a85/POSTMan-Chrome-Extension#5115]
**Describe the bug**
Head to https://go.postman.co/team/elements?type=monitor. I should see my team's monitors. I don't.

No errors in the console. The WebSocket network tab shows all calls having returned successfully. I see 200+ monitors returned in one of the API Responses.

**Screenshots**
![screen shot 2018-08-30 at 14 23 20](https://user-images.githubusercontent.com/681190/44841203-71bf4b00-ac60-11e8-8a72-41ce89a11a8e.png)

**App information (please complete the following information):**
- Server-side bug, seen on Aug 30

**Comment by ankit-m** [comment]
A fix for the same has been deployed. Can you please confirm?
