### ISSUE TITLE
Expose environment name in scripts

### ISSUE THREAD

**Issue by ash007-postman** [a85/POSTMan-Chrome-Extension#5116]
I am trying to create Pre-request script to change Global variable value dynamicaly based on environment. 
I cannot find environment object to get environment name or description to use in the script. 
There are 3 different environments local, dev and demo. 
Global variable subscription should be changed based on environment.

Script should work like this:

if (pm.environment.name==("local")) 
{ 
pm.globals.set("subscription", "svcloud-local"); 
} 
else if (pm.environment.name==("dev") ) 
{ 
pm.globals.set("subscription", "svcloud-dev"); 
} 
else if (pm.environment.name("demo")) 
{ 
pm.globals.set("subscription", "svcloud-demo");

**Comment by anilraut30** [comment]
@numaanashraf  any further update or workaround on this?

**Comment by kaustavdm** [comment]
@anilraut30 While this is still pending a response, a workaround specific to the use case posted above(setting a global variable depending on current environment name), can also be done by switching on a pre-defined environment variable. So, you would have a variable like `env` and give it values like `demo`, `dev` or `local`, and so on. And then in the pre-request script have something like:

```js
const currentEnv = pm.environment.get("currentEnv");
if (currentEnv === "demo") {
    pm.globals.set("subscription", "svcloud-demo");
}
// ... other conditions here
```

The benefit of doing this is you can set a common variable across all your environments, and you can also use the same environment, but change the value for local testing by editing the `Current Value` column.

**Comment by kamalaknn** [comment]
@anilraut30 @kaustavdm 

`pm.environment.name` should give you the name of the environment in the latest version of Postman.

**Comment by VicKetchup** [comment]
Even though pm.environment.name works in Postman, it doesn't work for monitor runs. It is really counter-intuitive for the monitor behave differently to the app and would really love to see that fixed.
