### ISSUE TITLE
Screenshot feature in Postman 

### ISSUE THREAD

**Issue by anjali89r** [a85/POSTMan-Chrome-Extension#5118]
Please read through the [guidelines](https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues) before creating a new issue.

**Is your feature request related to a problem? Please describe.**
I use postman for testing and while raising the defect for the issue, it is mandatory for me to attach the screenshots of postman test. It will be a great feature to include an icon within postman which can take the screenshot of the postman app window.

**Describe the solution you'd like**
It will be a nice feature to have screenshot option in Postman which can take the postman app screenshot and share option to slack or email or trello. I'm looking something similar to Fireshot chrome extension which is a great extension to take the screenshot of web pages.

**Additional context**
Fireshot extension : - https://chrome.google.com/webstore/detail/take-webpage-screenshots/mcbpblocgmgfnpjjppndjkmgjaogfceg

**Comment by sankalp0o** [comment]
Thanks for the feedback @anjali89r! We'll have to see how this could fit in the app. I'll keep you updated if and when we decide to take this up.

P.S. I personally use the macOS screenshot capabilities with auto sync to Dropbox which also copies its public url which can be directly pasted into slack etc.

**Comment by sankalp0o** [comment]
@preethammavin Can this be solved by a plugin?

**Comment by a85** [comment]
We will support extensive reporting functions separately to handle use cases like this. Building a screenshotting system in Postman is not viable.
