### ISSUE TITLE
The transfer-collection-while-removing user feature doesn't work

### ISSUE THREAD

**Issue by abhijitkane** [a85/POSTMan-Chrome-Extension#5120]
**Describe the bug**
While removing user u2 from the team, if I select u3 as the user to whom all of u2's shared collections should be transferred, I get a success message, but the collections aren't actually transferred. I need to contact support to get the collections transferred.

**App information (please complete the following information):**
- Server-side issue. Seen on 2018-08-31

**Comment by ankit-m** [comment]
A fix for the same has been deployed. Can you confirm?
