### ISSUE TITLE
pm.isMonitor()

### ISSUE THREAD

**Issue by stephanos** [a85/POSTMan-Chrome-Extension#5121]
Please read through the [guidelines](https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues) before creating a new issue.

**Is your feature request related to a problem? Please describe.**

I want my collection to be executable locally _and_ from monitors. But since some stateful setup in the app is required for the tests, I want to avoid conflicts there. By knowing whether it's running on the monitor, I can separate the two.

**Describe the solution you'd like**
I'd like to have a `pm.isMonitor()` (or something along those lines) that would tell me whether the collection is being run on the monitor or not.

**Describe alternatives you've considered**
I could create a separate environment with a custom variable, but that would mean I need to create twice as many environments and there could be issues due to not being DRY (ie duplication free).

**Comment by shamasis** [comment]
Yeah. Legitimate. Let me keep a note of this.

Ideally, we would put in an execution information section within `pm` api and that would expose the host details as well as some more info pertaining to execution.

**Comment by codenirvana** [comment]
Closing as we are tracking a similar feature request here: #2578
