### ISSUE TITLE
Scroll is very laggy using dell touchpad

### ISSUE THREAD

**Issue by avxkim** [a85/POSTMan-Chrome-Extension#5122]
Windows 10 (1803), Postman 6.2.5

Steps to reproduce:

1. Minimize Postman
2. Open Postman
3. Try to scroll using touchpad (2 fingers)
4. Scrolling would be laggy

VSCode had similar issue, but they made workaround: https://github.com/Microsoft/vscode/issues/13612. I guess, it's electron based apps suffering this scroll issue.

Minimize+Maximize works as workaround.

**Comment by harryi3t** [comment]
@webcoderkz 

We've pushed an update on our early access canary channel that should resolve this issue. Do try it out and let us know.

You can get the canary app from https://www.getpostman.com/downloads/canary

**Comment by twitharshil** [comment]
Hi @webcoderkz 
Could you try out our early access Canary build? https://www.postman.com/downloads/canary/. We are testing some improvements that should address this particular issue. You can install and use the Canary build side by side with the stable app.

**Comment by mccannt** [comment]
We have pushed Electron changes in the app over the past few months that should help with this issue. 
No confirmation on this specific issue. Closing this for now but feel free to open if this continues to be a problem.
