### ISSUE TITLE
Certificate config should allow wildcards in domain

### ISSUE THREAD

**Issue by qcastel** [a85/POSTMan-Chrome-Extension#5123]
## Current context

Today, postman offers the possibility to setup client certs for specific domains. This is handy for APIs protected by MTLS for example.
It's quite common to have multiple domains, especially in a micro-services architecture. 
Unfortunately today, if you got 4 services like:

- https://serviceA.example.com
- https://serviceB.example.com
- https://serviceC.example.com
- https://serviceD.example.com

You will need to setup 4 times your client certs for each domain.

## Suggestion of improvement

Allowing setting up a wildcard in the domain, like https://*.example.com
This will reduce the configuration setup from 4 to 1 in the previous example.

## Alternative solution

- The client certs config is a bit basic today. An edit feature would be welcome. This will help the problem above but not solve it completely. It will help changing the keys as today, you need to delete the entry and re-create it...

## Additional context

In Open Banking, we choose Postman as a way to share the usage of the financial APIs. As the standard requisite all APIs to be protected by MATLS, we have to ask our developers to setup client certs.
A concept not very well-known by our developers and the fact they need to setup multiple times makes it very error prone. I got a support tickets about a bad client certs setup once every week in average, and this is just the beginning.

The experience with Postman for them is not smooth and it's been discussed to find an alternative just because of issue above.
Open Banking is the next API transformation, mandated by PSD2. It will be a key feature for making postman a nice entry door into the Open Banking API world.

**Comment by tobypinder** [comment]
This has my strong support. To give context, open banking involves 15+ brands (and growing) each with about 2 domains protected by MATLS, across sandbox and live environments. While postman's environments are excellent for handling these different configurations, maintaining 60+ different client certificates in the current UX is more than cumbersome.

**Comment by codenirvana** [comment]
@qcastel Try using a URL match pattern, e.g, for your use-case: `*.example.com`

![Screenshot 2019-06-18 at 4 33 17 PM](https://user-images.githubusercontent.com/4865836/59677162-deeb9f00-91e6-11e9-882e-38f9582abe21.png)

**Comment by qcastel** [comment]
is that a new feature from postman @codenirvana ?

**Comment by codenirvana** [comment]
@qcastel Always supported (v6+), not documented well.
Can you verify if that works for you?

**Comment by qcastel** [comment]
indeed, it works! Thanks!

**Comment by clawfrank** [comment]
`*.example.com` works, but `service*.example.com` does not.

**Comment by admayber** [comment]
Could this issue be reopened due to the above? I have a need for a similar wildcard (service*.example.com)
