### ISSUE TITLE
Does postman support Kerberos Authentication?

### ISSUE THREAD

**Issue by DivyaKallu** [a85/POSTMan-Chrome-Extension#5124]
Does postman support Kerberos Authentication? Our Web application uses Windows authentication , where our account is authenticated against Kerberos server. When I try to run API request using No Auth in Native postman app I am getting 401 error , unauthorized error. The same is working through postman chrome browser app, but as this is going to be deprecated soon i want to work on native postman app.
Please let me know if postman supports Kerberos authentication, if so how can it be done.

**Comment by numaanashraf** [comment]
@DivyaKallu We do not support Kerberos Auth in Postman native apps yet. We are tracking this feature request at #2240. Closing this as duplicate.

**Comment by viperidae** [comment]
It would be nice if you didn't deprecate the Chrome Extension until you supported all the authentication schemes.

**Comment by DanielMGoldberg** [comment]
Any news about this ? I'm trying to use kerberos authentication from the app but its not working.
