### ISSUE TITLE
Add support for requests/responses of type application/*+json, correctly interpreting them as JSON

### ISSUE THREAD

**Issue by preslavrachev** [a85/POSTMan-Chrome-Extension#5127]
At the moment, if a request has a specific `Content-Type` header, which differs from `application/json` or any of the other supported formats, Postman will fall back to interpreting it as text. This is unpleasant, because one loses all the formatting and highlighting capabilities, which one has when the type is recognized by Postman.

I think, the support for +JSON types (e.g. `application/hal+json`) (or +type-supported-by-postman) MIME types will be very helpful, as those share the exact same syntax of the original type, and only add a specific dialect of domain specific keywords that are accepted.

See also: https://trac.tools.ietf.org/html/draft-ietf-appsawg-media-type-suffix-regs-02#section-3.1

**Comment by codenirvana** [comment]
@preslavrachev This behavior is now fixed in the latest version of the Postman app (v7.7.2).
You can update the `Content-Type` header post selecting the raw body language without losing the language selected or defaulting to text like previously.
