### ISSUE TITLE
The ampersands '(&)' being replaced with '&amp' in the the URL string of HTTP code snippet

### ISSUE THREAD

**Issue by Ramya-From-Postman** [a85/POSTMan-Chrome-Extension#5128]
**Describe the bug**
When you generate an HTTP code snippet for a request in postman app, the '&' in the request URL being encoded as '&amp'

**To Reproduce**
1. Create a request using postman app. for ex: https://postman-echo.com/get?test=keep smiling&abc=xyz
2. Click on 'Code' next to cookie at the right-hand side & generate an HTTP snippet 

**Expected behavior**
As you can see in the postman console only '&' is sent in the request URL, the code should only contain '&' instead of '&amp"

**Screenshots**
![image](https://user-images.githubusercontent.com/40994626/44986684-3b583780-afa2-11e8-9a31-c9ed6bee7d48.png)

**App information (please complete the following information):**
 - App Type : Native App]
 - Postman Version : 6.2.5]
 - OS: [e.g. macOS High Sierra 10.13.6]

**Comment by abhijitkane** [comment]
@Ramya-From-Postman 
Can you try this is Postman 7.2.1, with the 'Experimental Codegen Mode' flag enabled in Postman's global settings? We've introduced bug-fixes, support for two new languages (JS-Fetch and Powershell), and the ability to configure certain aspects of the generated snippet.
