### ISSUE TITLE
Postman v6.2.5 on Nvidia GTX 780 Ti displays a blank beige screen (GPU issue)

### ISSUE THREAD

**Issue by laurence-myers** [a85/POSTMan-Chrome-Extension#5130]
Duplicate of #4594, see that issue for details. I'm raising a new issue because the old one is closed and locked.

Setting the environment variable "POSTMAN_DISABLE_GPU=true" fixes it as a workaround for me; however, since this seems to affect multiple GPUs and app versions, it suggests there's some underlying root cause that needs to be resolved.

**Comment by numaanashraf** [comment]
@laurence-myers Reopened and unlocked the original issue till we have a long term fix for this. Closing this as duplicate.
