### ISSUE TITLE
Path variables not resolved in Example Documentation

### ISSUE THREAD

**Issue by dusty** [a85/POSTMan-Chrome-Extension#5133]
When setting a path variable using Postman it does not interpolate the variable in the Example Request.

For example, setting this Example in Postman.

<img width="1001" alt="screenshot 2018-09-04 15 11 23" src="https://user-images.githubusercontent.com/792/45060474-d14c9a80-b054-11e8-85bb-af3f58d5584f.png">

Creates this in the Documentation

<img width="1147" alt="screenshot 2018-09-04 15 14 12" src="https://user-images.githubusercontent.com/792/45060561-3607f500-b055-11e8-9e92-66a2661a06c6.png">

Notice that on the Example Request it resolves the query param, but still has the path param as :pathParam.  

The problem this creates is that you can no longer Copy to Clipboard and have a usable example.  In order to make it usable, you need to manually change :pathParam to what you want it resolved to.

To work around this one needs to change the Example and replace the path variable with a value like so:

<img width="1002" alt="screenshot 2018-09-04 15 15 24" src="https://user-images.githubusercontent.com/792/45060585-5d5ec200-b055-11e8-8916-c77cd9d103ad.png">

Which will then render a usable example:

<img width="1154" alt="screenshot 2018-09-04 15 15 49" src="https://user-images.githubusercontent.com/792/45060600-6d76a180-b055-11e8-8c4a-a4ee365826f7.png">

Summary:
If using path variables in the API definition, it would be convenient to be able to use Save Response and have it "automatically work" without having to modify the URL in the example.

**Comment by gekonwi** [comment]
I think the "Example Request" part of the generated documentation should replace all variables by their values at execution time. In any documentation I've seen so far, "examples" always have concrete values.

**Comment by Raja-Simha** [comment]
@dusty @gekonwi This issue has been fixed. Please, verify and let us know. Closing this for now.

**Comment by Raja-Simha** [comment]
This is fixed now.
