### ISSUE TITLE
Documentation hosted on the custom domain throwing 404 error

### ISSUE THREAD

**Issue by Ramya-From-Postman** [a85/POSTMan-Chrome-Extension#5134]
**Describe the bug**
The source code of a documentation page hosted on a custom domain contains the following banner. due to which the page is redirecting to 404 error. Please fix this.

![image](https://user-images.githubusercontent.com/40994626/45081410-c8230280-b114-11e8-8a37-593ba1a6277a.png)

**Expected behavior**
 The above code shouldn't be showing in the source code.

**Comment by piotr-sokolowski** [comment]
We have discovered this by looking at our Google Analytics data so even though it's hidden for me, it's definitely visible for some users

**Comment by ankit-m** [comment]
This should be fixed now. If the issue still persists, please reopen the issue.

**Comment by Ramya-From-Postman** [comment]
@ankit-m, the issue still persists. the page is still throwing 404 error.

**Comment by godfrzero** [comment]
@Ramya-From-Postman This issue refers to the `docs/creating_documentation` link embedded in the public documentation. That link has been removed. Which page is throwing a 404?
