### ISSUE TITLE
Postman doesn't update automatically or manually behind a proxy on Linux.

### ISSUE THREAD

**Issue by uvarvu** [a85/POSTMan-Chrome-Extension#5135]
EXPECTED: Postman is automatically updated.
ACTUAL (Logs from the console):

`@postman-app/updater: error { Error: getaddrinfo ENOTFOUND dl.pstmn.io dl.pstmn.io:443
at errnoException (dns.js:50:10)
at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)
code: 'ENOTFOUND',
errno: 'ENOTFOUND',
syscall: 'getaddrinfo',
hostname: 'dl.pstmn.io',
host: 'dl.pstmn.io',
port: 443 } { packageName: 'PostmanCanary',
eID: 'PostmanCanary-1536142368260',
downloadURL: 'https://dl.pstmn.io/download/version/6.3.0-canary01/linux_64',
downloadDirectory: '/home/aioannou/worktools/PostmanCanary',
downloadInfo: 
{ status: 'DOWNLOAD_ERROR',
error: 
{ Error: getaddrinfo ENOTFOUND dl.pstmn.io dl.pstmn.io:443
at errnoException (dns.js:50:10)
at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)
code: 'ENOTFOUND',
errno: 'ENOTFOUND',
syscall: 'getaddrinfo',
hostname: 'dl.pstmn.io',
host: 'dl.pstmn.io',
port: 443 },
downloadDirectory: '/home/aioannou/worktools/PostmanCanary' } }
App updater event { name: 'electronAppUpdateError',
namespace: 'appUpdate',
data: 
{ error: 
SerialisedError {
code: 'ENOTFOUND',
errno: 'ENOTFOUND',
syscall: 'getaddrinfo',
hostname: 'dl.pstmn.io',
host: 'dl.pstmn.io',
port: 443,
name: 'Error',
message: 'getaddrinfo ENOTFOUND dl.pstmn.io dl.pstmn.io:443',
stack: 'Error: getaddrinfo ENOTFOUND dl.pstmn.io dl.pstmn.io:443\n at errnoException (dns.js:50:10)\n at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)' },
updateData: 
{ packageName: 'PostmanCanary',
eID: 'PostmanCanary-1536142368260',
downloadURL: 'https://dl.pstmn.io/download/version/6.3.0-canary01/linux_64',
downloadDirectory: '/home/aioannou/worktools/PostmanCanary',
downloadInfo: [Object] } } }
`

The file downloads successfully over curl:

`aioannou@crow:~/worktools/PostmanCanary/app$ curl -O https://dl.pstmn.io/download/version/6.3.0-canary01/linux_64
% Total % Received % Xferd Average Speed Time Time Time Current
Dload Upload Total Spent Left Speed
100 61.3M 100 61.3M 0 0 5115k 0 0:00:12 0:00:12 --:--:-- 4721k
aioannou@crow:~/worktools/PostmanCanary/app$ ls linux_64
total 181740
aioannou@crow:~/worktools/PostmanCanary/app$ ls -l linux_64
-rw-rw-r-- 1 aioannou aioannou 64344406 Sep 5 11:15 linux_64`

My http_proxy, https_proxy and no_proxy environment variables are set.   localhost and 127.0.0.1 are set in no_proxy.

**Comment by jviotti** [comment]
Merging this with https://github.com/postmanlabs/postman-app-support/issues/6053
