### ISSUE TITLE
Conditional logic in test to skip rest of iteration's API calls, move on to next iteration 

### ISSUE THREAD

**Issue by kthulsidoss** [a85/POSTMan-Chrome-Extension#5136]
Hi i have a collection with 3 requests , the first two are for generating tokens . I run the whole collection 6 times my use case is to run the first two request only one time ie for counter 1 how to make this happen
tx
k.thulsi

**Comment by numaanashraf** [comment]
@kthulsidoss We recommend reaching out to the wider Postman Community (https://community.getpostman.com/) for help with this issue.

Issue Guidelines: https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues
