### ISSUE TITLE
Error while publishing documentation

### ISSUE THREAD

**Issue by ash007-postman** [a85/POSTMan-Chrome-Extension#5137]
Unable to publish collection, getting "something went wrong error"

![download](https://user-images.githubusercontent.com/41741228/45094862-33330000-b13a-11e8-81a8-2f5ede1bf38a.png)

**Comment by ankit-m** [comment]
I was unable to reproduce this issue. Can you please provide more context and screenshot of the console while this error occurs.

**Comment by ankit-m** [comment]
Closing this issue as there was no response. Please reopen if you are still facing this issue.
