### ISSUE TITLE
Postman "Get New Access Token"

### ISSUE THREAD

**Issue by RonakThakkar** [a85/POSTMan-Chrome-Extension#5138]
**Is your feature request related to a problem? Please describe.**
Ability to save and select from multiple entries of "Get New Access Token"

**Describe the solution you'd like**
I use "Get New Access Token" feature frequently.
However I have multiple applications with different flows like implict, Authorization Code etc.
So I would like to save those different paramater values for different flows. Right now there is Manage Token which shows history of tokens generated. However that is of no use, because tokens will expire.
What is needed is facility to save entries for multiple flows like implict, authorization code etc, so that I can select from Dropdown and then click Get New Access Token.
Right now I keep all those values in notepad, and then click Get New Access Token and then replace the values based  on type of flow.

**Comment by numaanashraf** [comment]
@RonakThakkar Thanks for writing in. We are tracking this feature at #3337. Closing this as duplicate.
