### ISSUE TITLE
Entering a collection link in the browser opens chrome app by default instead of native app.

### ISSUE THREAD

**Issue by anudeepmedicharla** [a85/POSTMan-Chrome-Extension#5139]
1. Click on share collection
2. Get a shareable link
3. Open the link in the browser.
4. The browser opens the collection in the chrome app.

**Expected behavior**
It should open the native app.

**Comment by numaanashraf** [comment]
@anudeepmedicharla It is not technically feasible to open native apps when a collection link is opened in a browser - only protocol links (starting with postman://) triggers native apps.

**Comment by anudeepmedicharla** [comment]
Sorry. Not a bug. This falls under different topic altogether.
