### ISSUE TITLE
Fast edit parameters

### ISSUE THREAD

**Issue by paolobiavati** [a85/POSTMan-Chrome-Extension#5140]
it could be usefull to edit the parameters with a "fast access modality".
when you hover a {{parameter}} in the url endpoint or in a parameter edit, you can see the value and some info. 

Can you please put a button to open the parameters editor or, better, add the ability to edit the value.

Thank you, good work! ;)

**Comment by skatikia** [comment]
@paolobiavati Too late to this thread, but I come with happy news!

With Postman **V11.14**, we have rolled out multiple improvements to our variables interface, including **the ability to update variable values on the go**.

![edit-value](https://github.com/user-attachments/assets/45aed08c-2982-47e2-9833-d30ddf2e1e3e)

I hope you like this change as much as we do! Update your app to start working with this change and many more, and let us know what you feel ([over a call](https://calendly.com/shobhit-katikia/meet-with-shobhit) or just drop an email to [shobhit.katikia@postman.com](mailto:shobhit.katikia@postman.com)).

[Check out the Postman V11.14 release note](https://arc.net/l/quote/vtemyulc)
