### ISSUE TITLE
What's the problem

### ISSUE THREAD

**Issue by aiLvXuan** [a85/POSTMan-Chrome-Extension#5142]
Just open the software, and waiting a long time, view nothing
![uc 20180906114320](https://user-images.githubusercontent.com/22241686/45133954-a5ebbc00-b1ca-11e8-961a-e6f35917c1ff.png)

**Comment by SamvelRaja** [comment]
We are facing an issue in rendering postman in few selected GPUs.
Kindly, try the workaround provided in this comment https://github.com/postmanlabs/postman-app-support/issues/4594#issuecomment-391601621

**Comment by m3dbedb** [comment]
With windows 7 32 bit and intel HD Graphics 2000 with latest driver (26.05.2015) postman native apps 6.0.9, 6.1.3, 6.2.5 suddenly became black and setting POSTMAN_DISABLE_GPU environment variable doesn't help.

**Comment by aiLvXuan** [comment]
@m3dbedb @SamvelRaja 
I have updated the latest version now, is ok.

**Comment by m3dbedb** [comment]
On my machine with postman 7.0.4 the issue is still present.
