### ISSUE TITLE
Run In Postman not working if macOS app is not running

### ISSUE THREAD

**Issue by numaanashraf** [a85/POSTMan-Chrome-Extension#5143]
**Describe the bug**
Click on RIP on docs page when app is closed - https://docs.api.getpostman.com/. Collection is not imported.

**Expected behavior**
The app should open and import the collection.

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version: 6.2.5
 - OS: macOS High Sierra 10.13.6

**Comment by ankurdengla** [comment]
Fixed in Postman v7.9.0
