### ISSUE TITLE
invalid curl on documentation when file is in multiform

### ISSUE THREAD

**Issue by Ramya-From-Postman** [a85/POSTMan-Chrome-Extension#5144]
**Describe the bug**
Curl command on the documentation renders as "undefined" and making it invalid curl for a post request that contains a file uploaded as a value of an attribute.

**To Reproduce**
1. Create a post request that contains a file using form-data
2. view the relevant documentation of that request

**Expected behavior**
As files are not included in the code snippet in the intention of protecting sensitive data, instead of showing a flag as "Undefined" it would be good if the error is more sensible & let the user know that they need to manually upload their file by customizing the current code.

**Screenshots**
![image](https://user-images.githubusercontent.com/40994626/45148936-10f6bc00-b1e6-11e8-95fb-bc5045d6b80f.png)

**App information (please complete the following information):**
 - App Type:  Native App
 - Postman Version:  6.2.5
 - OS: [e.g. macOS High Sierra 10.13.6

**Comment by adadouche** [comment]
Hi @Ramyasri1212 

Before upgrading to 6.4.2 (Native App), i was able to get the file paths in the cURL command along with the Authorization header. But now it's gone :-(

Is there a way to get these back in the generated code?

**Comment by prashantagarwal** [comment]
@adadouche Hey, are you referring to generated code inside app or on Postman dashboard ?

**Comment by adadouche** [comment]
> @adadouche Hey, are you referring to generated code inside app or on Postman dashboard ?

Hi @prashantagarwal, the one in the in the app. I downgraded back to 6.3.0, and now I got back the Authorization and form data files included in the cUrl code.

**Comment by kamalaknn** [comment]
Hey @adadouche 

Thanks for reporting this, we've identified a regression where file paths are not included in the generated code snippets. 

We're working on fixing this. We'll push the fix in the upcoming releases.

**Comment by adadouche** [comment]
Hi @kamalaknn. Thank you. I'll continue using 6.3.0 in the meantime.

**Comment by sujayvenaik** [comment]
Hey @adadouche 
This issue is addressed. You can update the app to the latest version.
Refer:  
1. https://github.com/postmanlabs/postman-app-support/issues/5403
2. https://github.com/postmanlabs/postman-app-support/issues/5399
