### ISSUE TITLE
Support for team level settings

### ISSUE THREAD

**Issue by harryi3t** [a85/POSTMan-Chrome-Extension#5146]
Original issue: https://github.com/postmanlabs/postman-app-support/issues/5082

**Is your feature request related to a problem? Please describe.**
In a team of multiple members, the admin wants to change the setting `automatically persist variables values` of all the members to false. So that any confidential value from any environment should not be synced outside of their organization.

**Describe the solution you'd like**
This particular setting (maybe more) can be at the team level, so that the admins can configure this which then applies to all team members.

**Describe alternatives you've considered**
Currently the admin has to ask all the team members to change their settings

**Comment by VicKetchup** [comment]
Completely agree with this approach and would like to see this option being **off** by default, as any new user in our Team has to be informed about this being the case. 
With our APIs, testers change the values quite frequently on their own machines to test different scenarios and don't want to push the change to everyone or change what monitors are using!

**Comment by kmizzi** [comment]
Isn't this a huge security breach to not have this option?  Actually it should default to off.

**Comment by preethammavin** [comment]
@kmizzi this is turned off by default now on V10, and we only persist on the user clicking on persist all.

**Comment by IchordeDionysos** [comment]
But would that still share secrets with your teammates? 🤔 

There are use cases where you want to share configuration and other variable values like prod/stage URLs but a variable should have a "this is a secret" flag that always prevents the value from being shared with teammates, maybe even from being sent to Postmans servers!
