### ISSUE TITLE
Collapse Auth and Header area

### ISSUE THREAD

**Issue by kyler-hyuna** [a85/POSTMan-Chrome-Extension#5148]
Please read through the [guidelines](https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues) before creating a new issue.

**Is your feature request related to a problem? Please describe.**
Currently the authorization and headers section is visible at all times even if a request does not use it.

**Describe the solution you'd like**
The ability to hide or collapse the authorization and eeader area.

**Describe alternatives you've considered**
Nol alternatives.

**Additional context**
Attached screenshot of the area below.

![default](https://user-images.githubusercontent.com/13733609/45176845-38965600-b1df-11e8-97af-a13a183139bf.png)

**Comment by vkaegis** [comment]
@kyler-hyuna Thanks for writing in! We're exploring some solutions around being able to collapse certain views based on how you use them. No ETA on this just yet, but watch this space for updates.

**Comment by giridharvc7** [comment]
@kyler-hyuna Thanks for writing in. I don't think this feature will fit well with the roadmap that we are going with so i'm closing this issue for now. If you find this blocking your workflows, i'd love to know more, and we can open this issue for deeper introspection.
