### ISSUE TITLE
Incorrect monitor URL after creating a monitor

### ISSUE THREAD

**Issue by ankit-m** [a85/POSTMan-Chrome-Extension#5149]
**Describe the bug**
The monitor URL after creating a monitor from the context menu does not link to the monitor and uses the old URL.

**To Reproduce**
1. Open collection context menu
2. Click on `Monitor collection`
3. Click Next
4. See old monitor URL

**Expected behavior**
It should link to the dashboard monitor details page.

**App information (please complete the following information):**
 - App Type: Native
 - Postman Version: 6.2.6
 - OS: macOS High Sierra

**Comment by prashantagarwal** [comment]
Duplicate of #4976
