### ISSUE TITLE
Pre tags shouldn't be wrapped in the documentation

### ISSUE THREAD

**Issue by Ramya-From-Postman** [a85/POSTMan-Chrome-Extension#5150]
**Describe the bug**
Upon using a large table with 10 columns in a document, it works looks in the app. However, when it is published, only 8 full columns are shown with the 9th being cut off and the rest not visible. Also, within columns, the text is wrapped which makes some column data illegible.
Changing this HTML table to an ascii table and embedding it as code using enclosing three backticks again worked fine in the desktop app but on the website, the text was wrapped hard at 115 characters and so it mostly unintelligible

**To Reproduce**
1. Create a doc using a mix of markdown and HTML that has more than 8 columns
2. publish it & view it on the browser

**Expected behavior**
Text & the table with all the columns should render correctly.

**Screenshots**
![image](https://user-images.githubusercontent.com/40994626/45204696-a903ac80-b29d-11e8-8fdf-e1e9e73ae494.png)

![image](https://user-images.githubusercontent.com/40994626/45204668-90939200-b29d-11e8-9c7a-8cf75a88fa8e.png)

**Comment by DannyDainton** [comment]
Hey @Raja-Simha - Is this still a valid issue?

We have released multiple changes with the Postman editor since this was initially created.

**Comment by kamaraj-p** [comment]
This issue is fixed. Large tables are scrollable or have a 'view more' option.
