### ISSUE TITLE
No Code Snippets For fetching the keys from response

### ISSUE THREAD

**Issue by arnabitsme** [a85/POSTMan-Chrome-Extension#5151]
I am not able to find any function or code snippets to fetch the keys (not data or value) from the response  and compare with the keys of an external json.
If I have a requirement of comparing the keys between external json and response then how should I do it.
Example : The external json has client id, Salary, age where as the repose send client id , Salary, gender and Age then the test code should be able to generate errors for Gender as this is not expected in the response

**Comment by numaanashraf** [comment]
@arnabitsme We recommend reaching out to the wider Postman Community (https://community.getpostman.com/) for help with this issue.

Issue Guidelines: https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues
