### ISSUE TITLE
Edit/delete icon on team logo should be removed for a non admin user

### ISSUE THREAD

**Issue by Ramya-From-Postman** [a85/POSTMan-Chrome-Extension#5152]
**Describe the bug**
A user who does not have the admin role is able to see the edit & delete button on the team logo under the Manage Team page. However, When tried to update or delete the log it is throwing "Something went wrong" error.

**To Reproduce**
1. Go to https://web.postman.co/team & login as a user
2. click on edit or delete button on the logo

**Expected behavior**
 As the member of a team who is designated as "User" doesn't have the permission to make changes to the team logo, these options should be removed/ disabled 

**Screenshots**
![image](https://user-images.githubusercontent.com/40994626/45221981-ca31c080-b2d0-11e8-8648-cf6341ecda5b.png)

**Comment by ankit-m** [comment]
A fix for this has been deployed.
