### ISSUE TITLE
GET instead of POST

### ISSUE THREAD

**Issue by ekhaydarov** [a85/POSTMan-Chrome-Extension#5153]
Please read through the [guidelines](https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues) before creating a new issue.

**Describe the bug**
if you dont have `https://` in front of the url the request is always a `GET`, even if you select `POST` etc

**App information (please complete the following information):**
 - App Type: Native
 - Postman Version: 6.3.0
 - OS: macOS High Sierra 10.13.6

**Comment by numaanashraf** [comment]
@ekhaydarov Could you make sure there aren't any redirects involved? Postman tried to stay consistent with browsers and changes method to `GET` while following redirects. You can check this by turning off Settings > General > Automatically follow redirects.
