### ISSUE TITLE
Changes made to a duplicated tab are reflected in the source tab

### ISSUE THREAD

**Issue by schellem** [a85/POSTMan-Chrome-Extension#5154]
**Describe the bug**
Right click a Tab and select Duplicate, edit the duplicated request and changes are also applied to the original request. 

**To Reproduce**
See above

**Expected behavior**
Changes made to the duplicated request do not affect the copied request

**App information (please complete the following information):**
Native app V 6.2.5 Windows 10

**Comment by sujayvenaik** [comment]
Hey @schellem 

Duplicating a tab actually works differently from duplicating a request. Where duplicating a tab just creates another instance pointing to the same request, duplicating a request actually creates a new request with the same contents as the previous request. So in some use cases, you might be better served by duplicating the request in the sidebar than by duplicating the tab.
We'll be working on some improvements to make this difference evident in the interface.

**Comment by sujayvenaik** [comment]
Duplicate issue : #2838
