### ISSUE TITLE
CURLOPT_FAILONERROR

### ISSUE THREAD

**Issue by Craig-IntegraPay** [a85/POSTMan-Chrome-Extension#5155]
When the postman creates PHP examples, it is not creating "CURLOPT_FAILONERROR=>true"
without this I have found the 
if ($err) {
echo "cURL Error #:" . $err;
} else {
echo $response;
clause will not work, because the variable $err is not populated.

**Comment by abhijitkane** [comment]
Can you try this is Postman 7.2.1, with the 'Experimental Codegen Mode' flag enabled in Postman's global settings? We've introduced bug-fixes, support for two new languages (JS-Fetch and Powershell), and the ability to configure certain aspects of the generated snippet.

For this issue in particular, we've removed the error handling altogether. We'll introduce this as a language-level option in a future release.

Removing the bug tag for now.
