### ISSUE TITLE
Response Cookies not showing "Expires" property properly

### ISSUE THREAD

**Issue by xingped** [a85/POSTMan-Chrome-Extension#5156]
## App Details:
```
Postman for Mac
Version 6.2.5
OS X 16.7.0 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there: Just noticed it.
 2. Expected behaviour: When a cookie has an "Expires" date, it should show in the Cookies tab of the Response window.
 3. Console logs: 
[postman.log](https://github.com/postmanlabs/postman-app-support/files/2364745/postman.log)

 4. Screenshots (if applicable): 
![screen shot 2018-09-09 at 4 07 42 pm](https://user-images.githubusercontent.com/194663/45269890-99759680-b44a-11e8-8e5b-781faef3a89d.png)
![screen shot 2018-09-09 at 4 07 55 pm](https://user-images.githubusercontent.com/194663/45269891-99759680-b44a-11e8-9c7a-d3583d9f6df4.png)

1. Create a request to an endpoint that sets a cookie and run the request.
2. Note that the response pane Cookies tab does not show the Expires date, even though if you open the "Cookies" link, it will show the Expires date.

**Comment by numaanashraf** [comment]
Fixed in Postman v7.0
