### ISSUE TITLE
Postman should automaticaly send an archive backup

### ISSUE THREAD

**Issue by shide1989** [a85/POSTMan-Chrome-Extension#5160]
Hi
i'm working on many projects, and decided to switch to the team collaboration, 
so i shared my collections/envs with my team and created an organisation.

But since Postman teams free plan is limited to 25 requests (which is a joke btw),
after a while our collections got archived.

So one day i go to work and discover that 150+ requests and some collections had disappeared from my account and where archived magicaly.

So i had to select the "download archives options"
This couldn't get me more frustrated.. i had to re-create all my collections/envs etc..

There should be a **DAMN warning** ! at least by email before your hours of work disappears...

Since now i will continue to work sharing JSON exports to my team, and will definitely NOT got back to the team feature.

**Comment by scaytrase** [comment]
Same here. I've tried the team feature and got all my collections archived. I've dropped the team workspace  in hope I can get rid of limits, but this further blocked me the event archive acccess. God bless I could recreate team, and export + import data back. No more team trials.

Btw, new team workspace show me that archive is empty, but export did well and exported all the archived stuff I've missed

**Comment by daswass** [comment]
Exact same problem. This is a ridiculous way to attempt to get people to pay for the product. Block usage of the collection from the team workspace but dont remove the collection from the personal collection of the creating user. Please fix this _BUG_.

**Comment by jasonycw** [comment]
Beside auto export, also hope there will be a feature that will auto sync with a specific local JSON file where I can batch update with text editor and Postman will auto import and update.

**Comment by a85** [comment]
We are improving the experience on collaboration continuously. However, there are no immediate plans to send backups for archiving over email.
