### ISSUE TITLE
Variables not resolved in example response

### ISSUE THREAD

**Issue by ash007-postman** [a85/POSTMan-Chrome-Extension#5162]
Creating our docs with postman we discovered that variables in the online view of a response are not resolves to their actual values. In the published documentation all seems OK. 

![schermafbeelding 2018-09-10 om 12 16 01 1](https://user-images.githubusercontent.com/41741228/45295202-7ebf2280-b51b-11e8-8538-09860f16c972.png)

**Comment by godfrzero** [comment]
Has an environment been selected from the dropdown at the top of the middle column?

**Comment by bneut** [comment]
Yes; after selecting the environment the {{url}} variable is replaced with the url in the example request. But not in the response.

**Comment by godfrzero** [comment]
Alright, looks like a bug in the private documentation. We'll work on getting this fixed in the next 2 releases.

**Comment by godfrzero** [comment]
@bneut We've pushed a release which should've fixed this issue, could you verify and let us know?
