### ISSUE TITLE
Monthly Usage Limits: Surface the reset date in the online dashboard

### ISSUE THREAD

**Issue by chrisdeso** [a85/POSTMan-Chrome-Extension#5163]
**Is your feature request related to a problem? Please describe.**
Currently, there isn't a way to know when my team's monthly usage counters will reset.

**Describe the solution you'd like**
Something like the terrible mock below :)
![image](https://user-images.githubusercontent.com/4734306/45317145-ec545a00-b4ed-11e8-9444-f951e3251914.png)

**Describe alternatives you've considered**
Notifications/Reminders – both in-app and via email would be nice. Especially if I'm currently blocked on using a feature due to hitting the usage limit.

**Comment by rishabh-hs** [comment]
This feature is needed more than ever now.. Hope to see it live soon

**Comment by ankit-m** [comment]
The usage page now shows the usage period.
