### ISSUE TITLE
Record requests and use them as mocks

### ISSUE THREAD

**Issue by mfulton26** [a85/POSTMan-Chrome-Extension#5164]
Please read through the [guidelines](https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues) before creating a new issue.

**Is your feature request related to a problem? Please describe.**
Setting up mocks can be cumbersome.

**Describe the solution you'd like**
The ability to record some proxied requests and then use them as mocks.

**Describe alternatives you've considered**
I am currently using [WireMock](http://wiremock.org/) but I would much rather have a unified solution.

**Additional context**
WireMock currently has two ways to do this:
- http://wiremock.org/docs/record-playback/
- http://wiremock.org/docs/record-playback-legacy/

Something similar in Postman would be wonderful.

Thank you.

**Comment by vvs11** [comment]
@mfulton26 You can do this in Postman too. You can go to the history tab, enable save responses, send your requests that you want to capture, then click on ... button next to the date. You can mock all the responses for that day. Let us know if that solves your use-case

**Comment by shashankawasthi88** [comment]
@mfulton26 hopefully you have been able to achieve this workflow using the method suggested by @vvs11 . In meanwhile we are also planning a way to achieve this via Postman Proxy route. It would be great if we could get onto a short call to discuss your exact use case. It would help us tailor the experience better. Could you please schedule a call with us regarding the same according to your convenience via this link - https://calendly.com/shashank-awasthi/postman-proxy

**Comment by mfulton26** [comment]
I ended up using [mountebank - over the wire test doubles](https://www.mbtest.org/) for my solution at that time but I haven't used Postman, WireMock, or Mountebank for over a year now. I would be open to a call but it has been so long and I am not currently an active user of Postman so I don't think I could provide more insights then what I can via plain text at the moment.

My best wishes.

**Comment by vvs11** [comment]
Let's set up a call. That would help us understand your use case and build better solutions in the future. 
Let us know how you'd like to do that? 
cc @shashankawasthi88

**Comment by shashankawasthi88** [comment]
@mfulton26 with the latest release (v 8.9.1) of the Postman App, you now have the ability to save the responses along with the corresponding request via Postman Proxy. This shall help you automate the process of creating a mock.
Additionally, we have added the ability for you to organize the captured traffic based on 'Domain Name' and 'End Point' in the Collection. This shall help you organize the Collection better and can help in better collaboration and documentation using that collection. Look for more information [here](https://learning.postman.com/docs/sending-requests/capturing-request-data/capturing-http-requests/)
