### ISSUE TITLE
Feature Request: Format Conversion Endpoint

### ISSUE THREAD

**Issue by chrisdeso** [a85/POSTMan-Chrome-Extension#5166]
**Describe the solution you'd like**
Expose an endpoint ([Postman API](https://docs.api.getpostman.com/)) that handles  data conversion (Swagger/YAML/WSDL to Postman schema).

**Comment by benhamill** [comment]
More specifically, I'd love to be able to upload a .tar of YAML files or something and have the endpoint go ahead and create a collection from it directly. Ideally supporting OpenAPI Spec 3.0, but OAS/Swagger 2.0 would be good for now, too.

**Comment by benhamill** [comment]
More specifically, I'd love to be able to upload a .tar of YAML files or something and have the endpoint go ahead and create a collection from it directly. Ideally supporting OpenAPI Spec 3.0, but OAS/Swagger 2.0 would be good for now, too.

**Comment by deepakpathania-zz** [comment]
Hey @benhamill, we have added support for importing Open API spec 3.0 to Postman via Postman API.
You can read the documentation [here](https://docs.api.getpostman.com/#331ec7d1-6ffd-450b-996b-022afcb692f8). 

We are constantly improving the converter that handles the translation and you can subscribe to [this](https://github.com/postmanlabs/postman-app-support/issues/3390) thread for the updates on that.

Closing this issue, feel free to open another one for a separate specification if needed.

**Comment by benhamill** [comment]
@deepakpathania This is very exciting! Thank you! We'll have a look and play with it and bring up any problems we notice. 💖
