### ISSUE TITLE
DELETE requests take more than a minute to complete on postman

### ISSUE THREAD

**Issue by abhishek-ram** [a85/POSTMan-Chrome-Extension#5167]
Please read through the [guidelines](https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues) before creating a new issue.

**Describe the bug**
We are facing a strange issue, when we send a DELETE request from postman to our server it takes more than a minute to complete on postman. The logs show that the request was responded to quickly and to prove this we ran it on curl and there was no such issue.

**To Reproduce**

**Expected behavior**
The DELETE request should not take a minute to complete

**Screenshots**
<img width="975" alt="screen shot 2018-09-12 at 1 10 53 pm" src="https://user-images.githubusercontent.com/7054720/45409613-535c4500-b68d-11e8-8489-bece33ed4ccd.png">

**App information (please complete the following information):**
 - App Type  Native App
 - Postman Version 6.3.0
 - OS: macOS High Sierra 10.13.2

**Additional context**

**Comment by numaanashraf** [comment]
@abhishek-ram Is this happening always or intermittently? Also, could you use code generation to generate a cURL snippet and try the same via cURL?

**Comment by abhishek-ram** [comment]
This is happening always and I tried with cURL and it returned quickly

**Comment by abhishek-ram** [comment]
This is also happening on the monitor which causes it to breach the 5 minute window...

**Comment by abhishek-ram** [comment]
@numaanashraf Another strange thing is that if i run postman against the local server its not causing this issues, this only happens when I run this against the server(Docker on Azure Cloud).

**Comment by numaanashraf** [comment]
@abhishek-ram That's really odd. Is this endpoint publicly accessible and would it be possible if we use this endpoint to triage this issue? You could send us the URL to `help@getpostman.com` if it is private or sensitive.

**Comment by abhishek-ram** [comment]
@numaanashraf I was able to dig some more on this issue, it looks like the issue is with the HTTP 204 returned by the delete API. Now the local server is a flask development server and this is not causing any issues; however our prod server is on nginx and I am thinking this is causing something that postman is finding difficult to digest. I am sure you will be able to replicate this by simply running on an endpoint returning 204 on nginx, let me know if you cannot do that and I will share the API

**Comment by abhishek-ram** [comment]
@numaanashraf I think you can close this issue, it was our mistake we were sending  data in the response even though we were sending a 204 which is wrong. We fixed this and now postman is behaving as expected.

**Comment by numaanashraf** [comment]
@abhishek-ram Thanks for letting us know. We are working on making these issues easier and faster to debug within Postman. I'm keeping this issue open till we fix the root issue.

**Comment by shamasis** [comment]
Tracking something along the same lines: #5818
