### ISSUE TITLE
Environment variables in url not being interpolated

### ISSUE THREAD

**Issue by wadtech** [a85/POSTMan-Chrome-Extension#5169]
Please read through the [guidelines](https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues) before creating a new issue.

**Describe the bug**
When using an environment to set the URL of an API, the variable is not replaced in the URL used to send the request. This is apparent because of the following error message: `There was an error connecting to %7B%7Burl%7D%7D.`

**To Reproduce**
1. Create an environment containing a single variable 'url' with some value and persist it
2. Select the environment from the dropdown
3. Create a request with the URL field set to `{{url}}`
4. Hover the url variable and see that Postman recognises it as a correctly-configured variable
5. Send request

**Expected behavior**
It should interpolate my URL variable and successfuly send the request

**Screenshots**
![url variable](https://user-images.githubusercontent.com/1141692/45481139-ac39e500-b742-11e8-8c6c-94b8762db939.png)

**App information (please complete the following information):**
 - Native App
 - Postman Version: 6.3.0
 - OS: Ubuntu MATE 17.10

Any help appreciated

**Comment by numaanashraf** [comment]
@wadtech This seems related to #5039. Please try the fix detailed at https://github.com/postmanlabs/postman-app-support/issues/5039#issuecomment-420258338

**Comment by wadtech** [comment]
@numaanashraf thanks! I missed that when I searched.
