### ISSUE TITLE
OAuth 1.0 and Jetpacks not changing Timestamp or Nonce

### ISSUE THREAD

**Issue by Drethic** [a85/POSTMan-Chrome-Extension#517]
When I try to run a test for a collection using OAuth 1.0 the Jetpacks system isn't changing the Timestamp or Nonce on each test causing errors to come back.  I have both "Add parameters to header" and "Auto add parameters" selected on the one call I'm making within the Collection.  Is there a way to configure Jetpacks to do this or is this considered a bug within the testing program?

**Comment by samjewell** [comment]
I believe I'm having the same issue as @ktowle described, but in the Postman native macOS app.

I'm using OAuth 1.0, with these settings:
- [x] Add params to header
- [ ] Add empty params to signature
- [ ] Encode OAuth signature
- [ ] Sebel helper data to request

When I hit Update Request, I get a new Nonce calculated. Then when I run the collection-runner, the first request succeeds, and all subsequent requests are 401 Unauthorised.

Can you help at all @abhijitkane ?
