### ISSUE TITLE
Sticky dropdown menu in documentation

### ISSUE THREAD

**Issue by chrisdeso** [a85/POSTMan-Chrome-Extension#5172]
**Is your feature request related to a problem? Please describe.**
Being able to generate code snippets for API documentation within documentation is great. If the documentation is extensive, or has a long introduction, it's a bit of a pain to have to scroll to the top of the page to get to the code generation dropdown.

**Describe the solution you'd like**
A sticky dropdown bar in documentation for the c would be great!

**Additional context**
![image](https://user-images.githubusercontent.com/4734306/45501197-64f92780-b735-11e8-97e7-f58d7c3f41d0.png)

**Comment by baileymatthewr** [comment]
For documentation that requires a lot of preface, the code is (can be) deep in the page. It would be very practical to allow this feature.

For reference see the following: https://docs.doba.com/?version=latest

**Comment by baileymatthewr** [comment]
Awesome! Thanks Raja-Simha and team!
