### ISSUE TITLE
When setting a variable from a script, "Initial Value" modified for all variables in same scope

### ISSUE THREAD

**Issue by ghost** [a85/POSTMan-Chrome-Extension#5173]
**Bug Description**
When a variable is set from a Pre-Request or Test script, the initial values for all variables within the same scope are overwritten with the current value of the variable.

**To Reproduce**
1. Create a few global variables, where the initial and current values are different
2. Add a step in a Pre-request or Test to set any globalvariable (i.e. `pm.globals.set("myvar", "newvalue");`)
3. Run the request
4. Look at current global variable values, to see that the initial values for all variables have been replaced by their current value

**Expected behavior**
Initial values should not be changed when setting a new value for a variable. They should certainly not be changed for variables other than the one being modified.

**App information (please complete the following information):**
 - App Type: Native
 - Postman Version: 6.3.0
 - OS: Windows 10

**Additional context**
The current behavior seems potentially dangerous, especially when using variables to store sensitive information, like credentials. Here are a few reasons why:
1. In a team workspace, this issue can cause sensitive information (i.e. a specific team member's credentials) to be unintentionally shared with the entire team
1. When syncing data to a Postman account, this issue can cause sensitive information to be unintentionally synced

**Comment by numaanashraf** [comment]
@jholzer-cciq Could you verify whether "Automatically persist variable values" is turned off in Settings > General? Before we introduced current value, we used to automatically persist variable values. To make sure we do not break any existing workflows, we keep this setting turned on by default for users updating from pre 6.2 versions. If you turn off this setting, Postman should behave as you expected.

**Comment by ghost** [comment]
@numaanashraf Thank you! I didn't realize the "Automatically persist..." setting was available, and it was turned on. Once I disabled that setting, then everything worked as expected.

Glad to know this isn't actually a bug.

**Comment by rkeet** [comment]
How could I force the `Automatically persist variable values` to be turned off for shared Collections though? Is that possible during the pre-request scripts?

When using shared Workspaces with multiple environments, the "Intial values" get shared among people in the workspace. This however causes a need to store the value somewhere. I'm not real keen on sharing production passwords (e.g. for administrator users) via Postman. Also, I simply do not want others modifying the "Initial values" that I've created for certain Collections (or is this last bit already caught with permissions?).
