### ISSUE TITLE
Not allowing to sign up or sign-in after deleting the user account

### ISSUE THREAD

**Issue by sri-miriyala** [a85/POSTMan-Chrome-Extension#5175]
Description:
As a Postman user, I tried deleting my account and wanted to create new account because of issues in importing files. I followed below steps.
I was able to successfully delete my account. 
I tried to create new account using signup option on Postman.
But I was using the same email ID that is associated with old account which was deleted.
Then I got a response "User already existed"
Then I tried to sign-in using that email ID
Then I got a response "User does not exist with this email ID"
I repeatedly tried for 5-6 times with in 15 min of time
I waited for 10 min and tried again and still the same error occurred for sing-up as well as sign-in
I waited for 20 min then I was able to create new account using the same email ID which was used earlier.

1. Go to "https://identity.getpostman.com/login"
2. Enter valid credentials to login
3. You must have pro or enterprise edition before you go to next steps
4. go to settings
5. Delete the account
6. It will ask you to delete workspace, first
7. Delete all work spaces 
8. Then delete the account/user
9. User will be removed.
10. Try to create new account by using 'https://identity.getpostman.com/signup'
11. Provide required information (email should be the same email that is associated with the other account deleted)
12. click on sign-up
13. ERROR saying "User already existed"
14. Then in the same window use sign-in option
15. Provide the same email ID and password which was used for the account that was deleted.
16. click on sign-in
17. ERROR saying "Email /User does not exist"

**Expected behavior**
I should be able to sign-up after deleting the user account with the same email ID that is associated with the account that was just deleted.

**App information:**
 - Postman Version [e.g. 5.3.3]
 - Mac OS: X El Capitan 10.11.6

**Comment by abhijitkane** [comment]
@sri-miriyala I'm unable to reproduce this. If you're still unable to sign up with the old email, can you email us at help@getpostman.com with the email/username you're trying to use?

**Comment by sri-miriyala** [comment]
@abhijitkane I was able to signup after 30 min. But this was the behavior I noted, when I try to delete the existing account and create new one with the same ID.
