### ISSUE TITLE
Cannot reach Generated Doc inside company firewall

### ISSUE THREAD

**Issue by ash007-postman** [a85/POSTMan-Chrome-Extension#5176]
When we try to reach our API documentation inside the firewall via Firefox and Chrome, we see an SSL certificate error:

NET::ERR_CERT_COMMON_NAME_INVALID

However, we can reach the published documentation outside of VPN. We haven't launched our product yet and are still testing in environments that are only reached by the Postman client within the company network. Please advise why our custom domain link won't work.

Please advise how to fix this issue so that our internal stakeholders can properly test and review the collection and generated documentation for accuracy. We also need to be able to test and author it on the docs team.

![postman_ssl_insidefirewall_support_issue](https://user-images.githubusercontent.com/41741228/45534831-048fe600-b81a-11e8-98af-844d9a3b5176.png)

**Comment by godfrzero** [comment]
The most likely cause is an SSL certificate being injected by your firewall. This is probably being done using a whitelist/blacklist, which should be modified accordingly to prevent this injection.

**Comment by Raja-Simha** [comment]
@ash007-postman I am closing this since we haven't received any further information to investigate.
