### ISSUE TITLE
Changing the username to something that already exists shows a 'Something went wrong' message in the UI

### ISSUE THREAD

**Issue by abhijitkane** [a85/POSTMan-Chrome-Extension#5177]
Please read through the [guidelines](https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues) before creating a new issue.

**Describe the bug**
Changing your username (at https://go.postman.co/settings/me) to something that's already taken gives a generic 'Something went wrong' message in the UI. The Websocket response correctly returns a "this username already exists" error message.

Server-side issue, seen on September 14, 2018

<img width="1294" alt="screen shot 2018-09-14 at 13 41 21" src="https://user-images.githubusercontent.com/681190/45538391-8f75de00-b824-11e8-9729-3285e014514e.png">

**Comment by abhijitkane** [comment]
The same issue exists for emails too

**Comment by ankit-m** [comment]
A fix for this has been deployed.
