### ISSUE TITLE
Published docs on custom domains break when the collection is transferred to another user

### ISSUE THREAD

**Issue by abhijitkane** [a85/POSTMan-Chrome-Extension#5179]
To Reproduce:
1. Have user u1 in team t1 publish documentation on a custom domain (api.t1.com)
2. Remove u1 from the team, transferring shared collections to u2.
3. The api.t1.com link breaks - I see a TOO_MANY_REDIRECTS

**Expected behavior**
The custom domain should never break.

Server-side bug
Seen on September 14, 2018

**Comment by preethammavin** [comment]
The issue has been fixed
