### ISSUE TITLE
The 'last modified' timestamp in the collection sidebar is incorrect

### ISSUE THREAD

**Issue by abhijitkane** [a85/POSTMan-Chrome-Extension#5183]
**Describe the bug**
Signing in to Postman fetches all my collections from the server. Opening the collection browser for these collections shows 'Last modified: Just now'. This timestamp is also 'Just now' on apps that I signed in to a few hours ago, but haven't touched since.

**To Reproduce**
1. Sign in to Postman

**Expected behavior**
The collection 'Last modified' should match the latest entry in its activity feed. (notice the scrollbar is at the very top of its range)

<img width="366" alt="screen shot 2018-09-15 at 01 31 31" src="https://user-images.githubusercontent.com/681190/45572541-1f4c7400-b887-11e8-88c5-77bfef34ac0c.png">

Seen on Postman 6.3.0 (OSX)

**Comment by harryi3t** [comment]
Since the field was removed starting from version 7.2.0, closing the issue
