### ISSUE TITLE
Add set/get functions for session variables in PM API

### ISSUE THREAD

**Issue by chrisdeso** [a85/POSTMan-Chrome-Extension#5184]
**Is your feature request related to a problem? Please describe.**
Having session variables in Postman is great – being able to programmatically set/get them within the Javascript sandbox environments (`Test` / `Pre-Request` scripts) would be even better!

**Describe the solution you'd like**
`pm.session.get("sessionVariable");`
`pm.session.set("sessionVariable", "teapot");`

**Comment by numaanashraf** [comment]
@chrisdeso Sessions are part of a variable scope (environment, global, collection etc) and setting/getting a variable through the current pm.* methods would be getting/setting the current value (aka session value) itself. Session values are not first class entities in Postman, and IMO, does not make sense to be exposed directly via a pm API.

**Comment by mattroberts297** [comment]
> setting/getting a variable through the current pm.* methods would be getting/setting the current value (aka session value) itself

On v7.0.7 I see both the initial and current value being set when `pm.environment.set` is used. I think either introducing `pm.session.set` per @chrisdeso's comment or changing the behaviour of `pm.environment.set` to match @numaanashraf's expectation would work.
