### ISSUE TITLE
[Postman API] Add an endpoint to retrieve API auth key

### ISSUE THREAD

**Issue by ghost** [a85/POSTMan-Chrome-Extension#5185]
Coming from conversation with @adamtarmstrong (feel free to add anything). Would be helpful for applications reliant on the API to directly interface without a required copy/paste step.

Create an open endpoint in the API that allows retrieval of a Postman API auth key via username/password or google auth. 

No alternative besides directing users to copy and past, disruptive user experience for any third party app.

**Comment by bpedro** [comment]
Hi @scottishkilt , thanks for getting in touch.

Would OAuth solve the challenge that you're facing? (see https://github.com/postmanlabs/postman-app-support/issues/9163)

**Comment by davidespihernandez** [comment]
As Bruno commented, the future of authentication in the Postman API will be OAuth2 (or something very similar to OAuth2). We are working in that direction.
