### ISSUE TITLE
Add setting to prevent session variables from persisting to disk

### ISSUE THREAD

**Issue by chrisdeso** [a85/POSTMan-Chrome-Extension#5186]
**Is your feature request related to a problem? Please describe.**
Sessions variables are extremely useful. It would be be great to have a toggle/setting that prevents session variables from persisting locally as well. i.e Session variables must be re-entered every time Postman is started

**Describe the solution you'd like**
A toggle/setting in the settings menu.

**Comment by a85** [comment]
Closing this as this adds another layer of meaning to variables. We'll look at alternative ways of improving the variable lifecycle.
