### ISSUE TITLE
The collection activity feed should show the year too

### ISSUE THREAD

**Issue by abhijitkane** [a85/POSTMan-Chrome-Extension#5188]
The current version of the app only shows the month and date of each collection update. Without the year, it can be misleading for old collections that haven't been updated in a while.

<img width="366" alt="screen shot 2018-09-15 at 01 31 31" src="https://user-images.githubusercontent.com/681190/45589454-52543d80-b943-11e8-8312-c2caccd012c1.png">

**Comment by numaanashraf** [comment]
Added in Postman v7.0
