### ISSUE TITLE
Autocomplete tooltip gets stuck at the left corner of the app

### ISSUE THREAD

**Issue by sivcan** [a85/POSTMan-Chrome-Extension#5192]
**Describe the bug**
The autocomplete tooltip gets stuck in the top corner of the app while sending a request.
This is one way to reproduce this, there are more ways in which this happens.

**To Reproduce**
1. In the URL bar add the following url:
```javascript
https://postman-echo.com/get?foo={{bar}}
```
2. In the pre-request script add the following script:
```javascript
pm.globals.set('bar', 'bar');
```
3. Do not send the request just yet, hover over the variable `{{bar}}` in the url bar
![image](https://user-images.githubusercontent.com/12631777/45607519-99891e00-ba6a-11e8-9592-e738ac6129a5.png)

4. Now press `Cmd + Enter` to send the request
5. Keep hovering for a few seconds after the response is received

**Expected behavior**
Tooltip should stay at it's position.

**Screenshots**
![issue](https://user-images.githubusercontent.com/12631777/45607657-87f44600-ba6b-11e8-8ee7-1bc62bcf9af5.gif)

**App information (please complete the following information):**
 - App Type - Native App
 - Postman Version - v6.3.0
 - OS: macOS High Sierra v10.13.6

**Additional context**
This issue can be reproduced in more ways and for some users this gets stuck at the top.
It reaches a state where it just can't be removed and the app needs to be quit just to get rid of it.

**Comment by bhargavkaranam** [comment]
This issue has been fixed in the latest version (6.5.x) of the Postman app.
