### ISSUE TITLE
gRPC support in Postman

### ISSUE THREAD

**Issue by vndptl** [a85/POSTMan-Chrome-Extension#5194]
**Is your feature request related to a problem? Please describe.**
I cannot find a client for gRPC based services, and I have really good experiences with Postman mostly with REST APIs. So I was wondering if it was possible to have gRPC support.

**Describe the solution you'd like**
To be able to call gRPC based services from Postman.
https://grpc.io/

**Describe alternatives you've considered**
https://github.com/troylelandshields/omgrpc
https://github.com/uw-labs/bloomrpc

**Comment by PS-StuartZahn** [comment]
+1

**Comment by xbitres** [comment]
+1

**Comment by whomakemecrazy** [comment]
+1

**Comment by archomai** [comment]
+1

**Comment by cparratto** [comment]
+1

**Comment by qa-amitsahu** [comment]
+1

**Comment by FBalazsBme** [comment]
+1

**Comment by DaviesX** [comment]
+1

**Comment by ofpiyush** [comment]
@vinod-patel  thank you for introducing me to `BloomRPC`.

Would be amazing to have that in postman itself.

**Comment by danielspk** [comment]
+1

**Comment by oswee** [comment]
Yeah... i would like to point Postman to proto file/dir location in remote or local location, so it could read all definitions... somehow... not sure how... So internally Postman could generate protobufs on the fly for its own internal language.
Pointing to already generated protobufs would mean, that Postman need to know how to read C, Go, Java etc protobufs...
Or it could be just Postman constraint that in order to test RPCs there should be generated protobufs for language X. (which i like less)

**Comment by giowe** [comment]
+1

**Comment by Ryank90** [comment]
+1

**Comment by lwaddicor** [comment]
This would be awesome for us

**Comment by pnadkar** [comment]
+1

**Comment by anthony-alekseiev** [comment]
+1

**Comment by danni-popova** [comment]
+1

**Comment by tejaslodaya** [comment]
+1

**Comment by theartyanya** [comment]
+1

**Comment by alexsandro-xpt** [comment]
+1

**Comment by raph** [comment]
+1

**Comment by yurriiy** [comment]
+1

**Comment by abhivaikar** [comment]
+1
There is so little tooling around testing gRPC APIs as well as automating their tests.
Postman would be a perfect choice to support both manual and automated testing of gRPC endpoints.

The way I look at Postman doing this is:
1. Ability to write tests that hit a gRPC endpoint and verify the response as a gRPC client
2. Run these tests as a collection using Newman

**Comment by ditrytus** [comment]
+1

**Comment by costerman** [comment]
+1 Can we expect to see this hit the Postman roadmap?

**Comment by sourabh7775** [comment]
+1

**Comment by Elverslane** [comment]
+1

**Comment by barelnir** [comment]
+1

**Comment by traturne** [comment]
Yeeeeees!

**Comment by freerider7777** [comment]
+1 :)

**Comment by yuraxdrumz** [comment]
+1

**Comment by Yinon-haver** [comment]
+1

**Comment by stangrincom** [comment]
**+ 1**

**Comment by ghost** [comment]
+1

**Comment by vinesh2011** [comment]
+1

**Comment by mkukacka** [comment]
+1

**Comment by jeffreydking** [comment]
+1

**Comment by prashantrakheja** [comment]
+1

**Comment by simion** [comment]
+1

**Comment by EvanTsiatsios** [comment]
+1

**Comment by Webonaute** [comment]
+1

**Comment by careless6666** [comment]
+1

**Comment by dkijkuit** [comment]
It's a shame this still isn't implemented yet. Anyone else looking for a gRPC GUI client: I've switched to [BloomRPC ](https://github.com/uw-labs/bloomrpc)which gets the job done.

**Comment by Webonaute** [comment]
> It's a shame this still isn't implemented yet. Anyone else looking for a gRPC GUI client: I've switched to [BloomRPC ](https://github.com/uw-labs/bloomrpc)which gets the job done.

BloomRPC is missing lots of stuff like error details, headers, chained test scenarios etc

**Comment by AAATechGuy** [comment]
this feature would have been good.

**Comment by APradyut** [comment]
Yes we need this feature for testing the GRPC services,

**Comment by pigubaoza** [comment]
+1

**Comment by zhiweipeng** [comment]
+1

**Comment by rifhanakram** [comment]
+1

**Comment by piyush2206** [comment]
+1

**Comment by gulakov** [comment]
+1

**Comment by Lengchuan** [comment]
+1

**Comment by LarsScha** [comment]
+1

**Comment by SeoJueun** [comment]
+1

**Comment by daniel-shuy** [comment]
Guys seriously stop spamming this thread with +1, just like the first comment instead, its so annoying to get useless notifications

**Comment by cuhavp** [comment]
+1

**Comment by sasinda** [comment]
+1

**Comment by mrdulin** [comment]
+1

**Comment by atkawa7** [comment]
+1

**Comment by mchenx** [comment]
+1

**Comment by daniel-shuy** [comment]
> Guys seriously stop spamming this thread with +1, just like the first comment instead, its so annoying to get useless notifications

☝️

**Comment by james-blitzm** [comment]
This feature **_really_** needs to be considered if the Postman project wants to maintain its throne as the standard tool for API interaction.

**Comment by xsoheilalizadeh** [comment]
This is a high demanding feature, please consider it at the top of your priorities, since a lot of people are engaging more in using gRPC.

**Comment by evercyan** [comment]
It's so sad....

**Comment by hunterjackson-keebo** [comment]
+1

**Comment by chengwah1** [comment]
> > Guys seriously stop spamming this thread with +1, just like the first comment instead, its so annoying to get useless notifications
> 
> ☝️

+2

**Comment by codemaster101** [comment]
@vvs11 Do you have any updates on this feature, or if you are still considering it?

**Comment by LiudmylaHabit** [comment]
+1

**Comment by tahayassine** [comment]
+1

**Comment by jasseemallybokus** [comment]
+1

**Comment by Jsoneft** [comment]
+1

**Comment by daniel-shuy** [comment]
> Guys seriously stop spamming this thread with +1, just like the first comment instead, its so annoying to get useless notifications

☝️☝️☝️

**Comment by lukasz7251** [comment]
+1

**Comment by vorishirne** [comment]
sad but true, it has been 2 years that Grpc has become the game changer. But this product just doesn't cares.
This is why I favor US products, they have a sense of responsibility, when they are owning a  domain. If something not perfect, that stays the part of beta version, sometimes for years, if they think that feature doesn't goes with the product line, but a heavy requirement.

**Comment by buehler** [comment]
As the creator of the issue listed several alternatives, here is another:
https://kreya.app/

**Comment by guptajiten** [comment]
+1

**Comment by OmThapa** [comment]
When are we getting gRPC support in Postman & Will test scripts be supported too? (Being Greedy Here)

**Comment by zeesattar** [comment]
+1

**Comment by PikaFederation** [comment]
+1

**Comment by 0xethsign** [comment]
+1

**Comment by HakunamatataLeo** [comment]
+1

**Comment by maxmiliandelemos** [comment]
I'm starting now with gRPC, here I am, looking for a solution to this problem.

**Comment by maxdelemos** [comment]
I'm starting now with gRPC, here I am, looking for a solution to this problem.

**Comment by cafenroy** [comment]
+1

**Comment by james-blitzm** [comment]
It would be nice to clarify here if we are talking about [gRPC web](https://grpc.io/blog/grpc-web-ga/) (and not gRPC). gRPC-web seems like the logical addition for the Postman suite.

**Comment by sunlintong** [comment]
+1

**Comment by Activity00** [comment]
+1

**Comment by sunxyw** [comment]
+1

**Comment by ntloi95** [comment]
+1

**Comment by venn76** [comment]
+1

**Comment by michael-volynets** [comment]
+1

**Comment by DachuanZhao** [comment]
Any progress ?

**Comment by klipach** [comment]
+1

**Comment by hlemmur** [comment]
+100

**Comment by ZhicongZheng** [comment]
+1

**Comment by cpinaBT** [comment]
+1

**Comment by azhuang321** [comment]
Any progress ?

**Comment by hasanisaeed** [comment]
+1

**Comment by appurva21** [comment]
Hello everyone 👋 

We are immensely excited to announce that with the latest release of Postman, you can now test your gRPC APIs! 🎉

### Feature Overview
- Protobuf API management
- Unary, Client streaming, Server streaming, and Bidirectional streaming RPCs
- Message authoring powered with code completion and autogeneration
- Metadata, Authentication and TLS configuration
- Templating using Postman Variables

![grpc-postman](https://user-images.githubusercontent.com/24985700/147562445-a7a62563-4df6-4e2c-a6b6-621a5889ef81.gif)

### Getting Started
1. Hit the **New** button in the left sidebar
2. Select **gRPC Request**
3. Type the address of your gRPC server into the URL bar
4. Select/upload the corresponding Protobuf definition
5. Select your desired service and method
6. Click **Invoke**
 
### What's Next?
We will be actively working towards integrating it with the rest of Postman's ecosystem to bring in every other feature like Collection integration, documentation, scripting, and more. Apart from that, we understand that managing Protobuf definition is an integral part of developing and maintaining gRPC APIs, therefore we have a few interesting things planned around that for the next year. 

gRPC support is still in beta and we will be constantly iterating and improving the experience based on your feedback.
Please feel free to file feature requests as [new issues](https://github.com/postmanlabs/postman-app-support/labels/grpc) and we will be keeping an eye on them.

Lastly, we are thankful to our Postman community for providing us with all the great suggestions here and patiently waiting for this 🙌 !

**Comment by ahmedalnuaimi** [comment]
@appurva21 can we already use Protobuf with HTTP requests?

**Comment by vini46** [comment]
@appurva21 in BloomRPC we have an option to add a path so that protos that are importing other proto files will be working fine, is there something like this available in postman? 

![Screenshot 2021-12-29 at 11 02 11 AM](https://user-images.githubusercontent.com/5517009/147630377-03e6d480-9499-4167-8c56-2a06f975b894.png)

**Comment by codenirvana** [comment]
@ahmedalnuaimi Not yet, we are tracking this feature request here: https://github.com/postmanlabs/postman-app-support/issues/2801.

---
@vini46 Not at the moment. Currently, we have some limitations around handling multiple proto files and we have a lot of improvements planned for the next year to improve this workflow.

**Comment by HakunamatataLeo** [comment]
6666666

**Comment by anhnmt** [comment]
How can I import multiple proto files into postman

**Comment by adityajoshee** [comment]
I don't see grpc option in the latest postman (version 9.11.0)

**Comment by codenirvana** [comment]
@adityajoshee gRPC is not supported in Scratch Pad right now. Please login or switch to a Workspace.

---

Locking this closed thread conversation to avoid unnoticed bug reports and feature requests.

Everyone, feel free to raise a feature request and bug report related to gRPC here: https://github.com/postmanlabs/postman-app-support/issues?q=is:open+is:issue+label:grpc
