### ISSUE TITLE
Billing/Admin user is unable to access the monitors created in the personal workspace.

### ISSUE THREAD

**Issue by Ramya-From-Postman** [a85/POSTMan-Chrome-Extension#5195]
**Describe the bug**
A user who is designated as billing or billing/admin can create monitors for the collections in their personal workspace. However, the same can't be accessed by them.  They can view the monitors created by them under https://go.postman.co/me/monitors. However, when they try to run it, it is throwing "**something went wrong error**". 
Even the monitors tab on the web dashboard is throwing "**Something went wrong error**"

**To Reproduce**
1. Login to postman app as a billing contact or billing/admin user
2. Create monitors for any collections saved in the personal workspace
3. try to run that monitor to see the error

**Expected behavior**
    Admin/Billing or Billing contact should be able to access the monitors created in their personal workspace.

**Screenshots**
![image](https://user-images.githubusercontent.com/40994626/45622752-bb9e9280-baa2-11e8-9a5e-197b0f9390fc.png)

![image](https://user-images.githubusercontent.com/40994626/45622494-cf95c480-baa1-11e8-8907-52ed089b6980.png)

![image](https://user-images.githubusercontent.com/40994626/45622527-f5bb6480-baa1-11e8-88da-e226ee23c14c.png)

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version:  6.3.0
 - OS:  macOS High Sierra 10.13.6

**Comment by kartikjain26** [comment]
@preethammavin  not able to reproduce it since we have rbac now.

**Comment by ArjunSingh-PM** [comment]
Confirmed that this issue is fixed. @godfrzero
