### ISSUE TITLE
Activity feed loads duplicate activities on clicking no more activity

### ISSUE THREAD

**Issue by SamvelRaja** [a85/POSTMan-Chrome-Extension#5197]
![1](https://user-images.githubusercontent.com/5114052/45671254-9b261500-bb42-11e8-8357-0034fbf6e822.PNG)
![2](https://user-images.githubusercontent.com/5114052/45671261-9e210580-bb42-11e8-9bce-a768b632d308.PNG)

**Comment by ankit-m** [comment]
A fix for this has been deployed.
