### ISSUE TITLE
Connectivity Feature Request for Postman & DB

### ISSUE THREAD

**Issue by BhanuDash007** [a85/POSTMan-Chrome-Extension#5199]
Hi , As part of Webservice testing and Automation we need the connectivity between DB and Services. Other tool provide that . If some thing can be done in it ASAP that make Postman more robust.

**Comment by numaanashraf** [comment]
Related to #2185

**Comment by JoaoGFarias** [comment]
I don't know if you can do it with Postman, but calling a shell script would be sufficient to leverage your favorite tool to run the DB scripts (A Python/Java script, e.g.).

**Comment by ghost** [comment]
Hi,
Any update on this?

**Comment by a85** [comment]
Closing as duplicate of other feature requests and there are no plans for Postman to support databases in the near future.
