### ISSUE TITLE
File upload not working after update

### ISSUE THREAD

**Issue by Anand10** [a85/POSTMan-Chrome-Extension#520]
Hi, I am using Postman more than 6 months, its features are awesome. But last week onwards the FILE upload not working. I think after updated the POSTMan REST client (app) this issue occurs. But its working when using POSTMan extension in chrome. Can you help me to solve this.

Thanks in advance,
Anand R

**Comment by yaswantsingh** [comment]
when i am sending any form data getting this error .. 

ActionDispatch::ParamsParser::ParseError (795: unexpected token at '------WebKitFormBoundaryqcIZwzIFhLB9ck5D
Content-Disposition: form-data; name="key_1"﻿
