### ISSUE TITLE
Add an "Output" tab for JSON/XML output from scripts

### ISSUE THREAD

**Issue by spamacon** [a85/POSTMan-Chrome-Extension#5202]
I mostly use the Postman App to test existing JSON web services, but sometimes I need to transform the output using a test script. This may involve hunting through MB of JSON data for a particular object, or just getting a list of dates from the output, ignoring all other properties, that sort of thing.

Currently, the only way to view the altered results is to write it out to the console. Sometimes I forget to open the console so I have to re-run requests, or I close the console and then need to reference the output again.

Is there any chance you could add an "Output" tab, right next to the "Test Results" tab, where I could write this data, maybe using something like output.write()? I'm hoping for basically a clone of the Body tab, but I could write to it using scripts, both Pre-request and Test scripts. I would probably only use it for JSON currently, but I can see how having the mime-type selection would be nice if someone needed to write XML.

There is a similar issue, requesting that the console be moved to a tab (#4667), but it would be nice to have the same sorts of features as the Body tab.  The console is more geared towards debugging, I'd think, then for formatted output.

**Comment by shamasis** [comment]
We have implemented the "Visualisation" feature for you to be able to do this. @kaustavdm ... we can create an example for this and close the issue?

**Comment by kaustavdm** [comment]
@spamacon Like Shamasis mentioned, we now have a visualization feature in Postman. It is currently released in Canary and will go to production soon.

Can you go through the [docs on Visualizer](https://learning.getpostman.com/docs/postman/sending_api_requests/visualizer/) and see if that answers your requirement? We are working on more content around this feature.

Till then, if you build out something useful, please publish it as a template :-)

**Comment by DannyDainton** [comment]
Closing this issue as this it's now covered with the functionality within the visualizer.
