### ISSUE TITLE
Make the scrollbars thicker

### ISSUE THREAD

**Issue by saurabhranjansingh** [a85/POSTMan-Chrome-Extension#5203]
The scrollbars are too thin in the Windows version. It becomes very annoying to precisely place the mouse pointer over the scroll bars especially when there are two scroll bars side by side.
![scrollbar](https://user-images.githubusercontent.com/10433007/45735574-f66d0b80-bc05-11e8-9fe7-8e7f30a3a42f.png)

**Comment by kntmr** [comment]
I think that the scrollbar of the main window is not necessary. It might be better to fix the response-pane in the main window.

For example:
![postman](https://user-images.githubusercontent.com/1657438/47405617-5fa7e780-d78d-11e8-8caa-e7d457fc6d5c.png)

**Comment by arlemi** [comment]
Hey! 

We've pushed changes to the layout of the app in [Postman Canary](https://www.postman.com/downloads/canary/) which removes the case where two scrollbars are next to each other. Please try it out and let us know what you think either here or [on our community forum](https://community.postman.com/t/new-layout-in-postman-canary/13450).

**Comment by kntmr** [comment]
The scrolling operations in each pane are separated, so I think this version is easier to use than older one.

**Comment by wenmin92** [comment]
Why there are two kind of scrollbars? Windows 10 + Postman 7.35.0
![image](https://user-images.githubusercontent.com/6901815/99260498-6a42e700-2856-11eb-924b-fca4a370cf81.png)

**Comment by kntmr** [comment]
@wenmin92 I think it's more convenient to have separate scrollbars in each pane.

**Comment by arlemi** [comment]
@wenmin92 Good catch! I've raised that issue with the product team.

**Comment by wenmin92** [comment]
> @wenmin92 Good catch! I've raised that issue with the product team.

@arlemi Sorry, I’m too sloppy. The scroll bar of the response panel is a multi-functional scroll bar. It also displays search results, cursor position and other functions. This may be the reason why it is thicker.

**Comment by arlemi** [comment]
@wenmin92 Indeed, the bottom scrollbar is form the Monaco editor and it doesn't look like it'd be easy for us to change it, but the team will look into it anyway!

**Comment by ghost** [comment]
This needs to be changed back to old style scroll bars, as these new scroll bars are completely useless.  It is almost impossible to click and drag these thin scrollbars, which has us looking for a new solution.  We have a huge number of environments, and our collections are huge as well.  We've also decided to skip Windows 11 because of this.  I can't think of any valid reason for changing the scrollbars to be so thin that they are unusable.

**Comment by abhinaba-ghosh** [comment]
Hi @saurabhranjansingh, 

Thank you for raising the issue. 

We have refreshed the user experience around scrolling and we hope you will like the experience. Kindly upgrade to the latest Postman app. Please re-open/create an (/the) issue if you have any more feedback around the same. 

![Screenshot 2022-04-27 at 4 32 36 PM](https://user-images.githubusercontent.com/23141842/165505058-3cad9aa4-fd03-401a-8b8a-c5f962557624.png)
