### ISSUE TITLE
Trying to deploy version 6.3.0 via SCCM

### ISSUE THREAD

**Issue by ash007-postman** [a85/POSTMan-Chrome-Extension#5205]
I am trying to deploy version 6.3.0 via SCCM, when installing the .exe it appears to be installed into the app data folder of the user and there is no uninstaller.

I have created a custom .msi, however, the users are getting the following error when attempting to open the program.

Selecting “yes” to view more information takes me to the following Microsoft support page:

https://support.microsoft.com/en-us/help/2715633/shim-errors-for-the-net-framework-version-and-platform-support

Do you have a Msi download we can get? Or any other help you may have on installing this version silently to the machine rather than the user.

![image001](https://user-images.githubusercontent.com/41741228/45743993-004d3980-bc1b-11e8-9b89-c010bece3d6c.png)

**Comment by SamvelRaja** [comment]
Related to https://github.com/postmanlabs/postman-app-support/issues/4576

**Comment by a85** [comment]
Closing as a duplicate of https://github.com/postmanlabs/postman-app-support/issues/4576
