### ISSUE TITLE
Console shows disabled body parameters

### ISSUE THREAD

**Issue by dmytro-astakhov** [a85/POSTMan-Chrome-Extension#5207]
**Describe the bug**
Postman console shows disabled body parameters

**To Reproduce**
1. Go to request builder
2. Add some body parameters
3. Disable a couple of body parameters by unchecking corresponding checkboxes
4. Open Postman console
5. Send the request
6. Observe disabled parameters in "Request body" section.

**Expected behavior**
Request body should not contain disabled parameters.

**Screenshots**
Paramters:
![image](https://user-images.githubusercontent.com/31509100/45745876-7eedab00-bc0a-11e8-8b19-d298692c26d0.png)

Console:
![image](https://user-images.githubusercontent.com/31509100/45745834-5e255580-bc0a-11e8-8729-90a3c4795e98.png)

**App information (please complete the following information):**
 - Native App
 - Postman Version 6.3.0
 - OS: Windows 10

**Additional context**
The same goes for headers.
It seems to be a console bug since disabled parameters are actually not sent.

**Comment by numaanashraf** [comment]
Fixed in Postman v7.0
