### ISSUE TITLE
Edit actions should not be allowed for workspace that user has not yet joined

### ISSUE THREAD

**Issue by kamalaknn** [a85/POSTMan-Chrome-Extension#5211]
**Describe the bug**
Actions on collections/environment that update the workspace like `Remove from workspace` or `Duplicate` should not be allowed until the user has joined the workspace.

**To Reproduce**
1. Go to a workspace you haven't yet joined
2. Click on '...' dropdown next to collection
3. See `Remove from workspace`

**Expected behavior**
Should not see `Remove from workspac`

**Screenshots**
![image](https://user-images.githubusercontent.com/8401064/45766546-7cfd0980-bc55-11e8-9b40-3c6ad2e05526.png)

**Comment by numaanashraf** [comment]
Fixed in Postman v7.0
