### ISSUE TITLE
Slack Integration doesn't populate Monitor information

### ISSUE THREAD

**Issue by chrisdeso** [a85/POSTMan-Chrome-Extension#5212]
**Describe the bug**
When adding the Slack integration to a workspace in order to receive monitoring results, the associated monitor's information doesn't populate in the web dashboard.

**To Reproduce**
1. Create a monitor
2. Navigate to the [web dashboard](https://app.getpostman.com/dashboard)
3. Add an integration to the desired workspace
4. Inspect the list of active Slack integrations and note that the associated monitor information doesn't populate

**Expected behavior**
I'd expect that the associated monitor information would populate in the event that one needs to be removed. Needing to remove all of the integrations, and re-adding them can easily yield unwanted results.

**Screenshots**

![image](https://user-images.githubusercontent.com/4734306/45777585-10f5b380-bc0b-11e8-93e0-8c6a4a665f14.png)

**Comment by godfrzero** [comment]
@ankit-m Loading indicators!

**Comment by chrisdeso** [comment]
Friendly bump!

**Comment by preethammavin** [comment]
The issue has been fixed and pushed to prod.
