### ISSUE TITLE
Monitors disappear

### ISSUE THREAD

**Issue by ash007-postman** [a85/POSTMan-Chrome-Extension#5214]
Hi, we have a paid account and we're setting up monitors to run every 15 min. But they only run while I have my browser open. When I revisit the monitors page, everything is gone. I'd like the monitors to keep running regardless of if my computer is on.

![screen shot 2018-09-19 at 11 56 17 am](https://user-images.githubusercontent.com/41741228/45814583-ab312680-bcf3-11e8-877b-fadb5f1cf54e.png)
![screen shot 2018-09-19 at 11 56 32 am](https://user-images.githubusercontent.com/41741228/45814584-ab312680-bcf3-11e8-926c-389538d22509.png)
![screen shot 2018-09-19 at 11 56 52 am](https://user-images.githubusercontent.com/41741228/45814585-ab312680-bcf3-11e8-9622-3113d60af79c.png)

**Comment by preethammavin** [comment]
Not reproducible
