### ISSUE TITLE
Allow users to clear all the cookies

### ISSUE THREAD

**Issue by harryi3t** [a85/POSTMan-Chrome-Extension#5215]
Right now Postman allows to delete cookies one by one and also per domain. 
But users can't delete all the cookies in one go. 
This is useful for cases where there are too many cookies.

**Comment by kkapell** [comment]
This would be very useful. I would add to this request the ability to clear one, multiple, or all cookies programmatically using something in the Pre-Request Script or similar.

**Comment by cniweb** [comment]
+1

**Comment by hvitis** [comment]
+1

**Comment by sarangjaiswal** [comment]
Is there an update on this issue/feature and when will this be fixed?

**Comment by ProBeta1** [comment]
How would pre-request scripts be able to delete httpOnly cookies ? Arent they not accessible from client-side ?

**Comment by ProBeta1** [comment]
@kkapell There is actually somewhat related feature - using a cookie jar to keep your cookies safe . Then you could [programmatically](https://learning.postman.com/docs/postman/sending-api-requests/cookies/#programmatic-access-of-cookies) insert and delete your favourite cookies , and if you are on diet , you can eradicate the entire jar !
@codenirvana If we can just make the entire cookie collection a part of some huge jar , the problem would be solved . What do you think ?

**Comment by yogamaha** [comment]
I am having similar issue - where cookies set by one of the request in the chain - I am not able to reset - especially when I try to run this iteratively

**Comment by giridharvc7** [comment]
Thank you for your patience, this is now fixed in v10.13. We have introduced a `Clear all cookies` option. 
Please give this a try and let us know what you think.
