### ISSUE TITLE
Mock Service Dynamic Response using environment variables

### ISSUE THREAD

**Issue by aulakhs** [a85/POSTMan-Chrome-Extension#5216]
I was wondering if I can change the values defined in the Example response dynamically, like described below. So every time I hit the mock endpoint, I get a different value for the last bit of randomName and randomCode fields.

{
    "randomName": "name-1",
    "randomCode": "code-1"
}

I've tried using the environment variable in the pre-request script and see that those are being set in the in the environment look-up. Is there a way to retrieve the environment variables in the Example response?

**Describe the solution you'd like**
Ability to set any variables (Global or environment) in the example response.

**Comment by ratpik** [comment]
@aulakhs - You can create a mock server with an environment and use variables from that environment as part of your example response. So you can have your example response like this:

```
{
"randomName": "{{name}}",
"randomCode": "{{code}}"
}
```
Every time you call the mock endpoint, this example response is returned with the environment variables resolved. To make the response dynamic, you can update the environment variables every time before you call the mock endpoint. Environment variables can be updated using pre-request scripts or tests as part of collection execution or by directly using the [Postman API ](https://docs.api.getpostman.com/#6517e0d6-3bc3-3da5-ab57-7a578a8504ce)

**Comment by aulakhs** [comment]
@ratpik - Thanks for the prompt reply. I'm doing exactly as you pointed out but that doesn't appear to be working. In this screen shot, you can see I'm setting the environment variables in Pre-request Script of the GET API call. And those are getting set as pointed out in the Environment look-up.

![mockservice dynamic set](https://user-images.githubusercontent.com/43443576/46099562-161bab00-c195-11e8-8e47-5b3b2f0b22b2.png)

In my Example Response, I have environments variables populated:
![example response](https://user-images.githubusercontent.com/43443576/46099621-3fd4d200-c195-11e8-9d55-2fdf6859cc28.png)

But, in the GET response of the APIs, these variables are not resolved. 
![results](https://user-images.githubusercontent.com/43443576/46099644-51b67500-c195-11e8-8565-777efcfd7518.png)

**Comment by ratpik** [comment]
@aulakhs - I tested this scenario and the environment variables are being dynamically resolved correctly. Can you confirm that while creating the mock you have specified the environment as `MockService Demo` in the `Use an environment` part as shown in the screenshot below?

<img width="1175" alt="screen shot 2018-09-27 at 11 45 55 pm" src="https://user-images.githubusercontent.com/210420/46165930-8ae30800-c2af-11e8-9d95-38b8647c3128.png">

**Comment by aulakhs** [comment]
@ratpik - Thanks for checking this for me. Yes, I have the right environment being used here. Infact, the values are getting set in the environment variables too, its just that those are not being returned back in the Example Response.

![mock](https://user-images.githubusercontent.com/43443576/46218760-7173a780-c313-11e8-917e-378009d5beaf.png)

Does the version has something to do with this? I'm using the Version 6.3.0 (6.3.0)

**Comment by aulakhs** [comment]
@ratpik - If you don't mind, can you send me your collection?

**Comment by ratpik** [comment]
@aulakhs - Here you go - https://documenter.getpostman.com/view/1715192/RWgja2Cg

You can click on the `Run in Postman` on the documentation which will import the collection and corresponding environment in your Postman App. Then create a mock using that collection and environment and hit `<mock_url>/getresults/` to view the response

**Comment by aulakhs** [comment]
@ratpik - Thanks! Does the Pre-request Script only runs locally on Postman? I'm able to retrieve the environment values in the Example Response however when I set those values in the Pre-request script (_example below_), the response only changes dynamically when the request is invoked using POSTMAN. When I hit the '<mock_url>/getresults/' using browser, the result doesn't change dynamically. Here's the endpoint - https://362fb606-eede-4163-8c9f-6c46dbc7e534.mock.pstmn.io/getresult/

`var number = Math.floor(Math.random() * 100);

var randomName = 'Name-' + number;
pm.environment.set("name", randomName);

var randomNumber = '' + number;
pm.environment.set("number", randomNumber);`

**Comment by ratpik** [comment]
@aulakhs - That's right. Pre-request scripts run only when a collection executes i.e when you send a request in Postman or the Postman Collection Runner or when you are using Postman Monitors or Newman to execute a collection. The pre-request script does not get executed when you call the mock server.

**Comment by aulakhs** [comment]
Thanks @ratpik 
Do you know of any workarounds on how to achieve that using Postman or if this enhancement is on the product roadmap?

**Comment by ratpik** [comment]
Allowing pre-request scripts to execute for Mock servers is not on the short term product roadmap. Depending on how you are using the Mock servers, you could possibly use the [Postman API to update the environment](https://docs.api.getpostman.com/#6517e0d6-3bc3-3da5-ab57-7a578a8504ce) variables used by your Example Responses just before you call the mock endpoint.

**Comment by ratpik** [comment]
@aulakhs - We have released a version that now supports resolution of Faker variables in your example responses. The list of variables is [here].(https://github.com/postmanlabs/postman-app-support/issues/971#issuecomment-501433055)

**Comment by rproman** [comment]
@ratpik - Hi. I came across this thread, and I just wanted to clarify if Mock Server dynamic response only works using Environment variables? Using Collection variables won't work to generate dynamic data in a sample response body?
