### ISSUE TITLE
NTLM Authentication should pull domain from username if provided

### ISSUE THREAD

**Issue by jhorbulyk** [a85/POSTMan-Chrome-Extension#5217]
**Describe the bug**
If I use NTLM to authenticate with a username of the form `SomeDomain\someUser` authentication fails.  However, if I set the domain and user separately, authentication succeeds.

**To Reproduce**
1. Create a request with authorization type NTLM.
2. Set username to `SomeDomain\someUser` with a corresponding valid password.
3. Send the request.
4. Receive a 500 code response from the server.
5. Set username to `someUser`.  Set Domain to `SomeDomain`.
6. Send the request.
7. Observe a 200 code response.

**Expected behavior**
Results of Username = `SomeDomain\someUser` should be identical to setting username and domain separately.

**App information**
 - App Type: Native App
 - Postman Version: 6.3.0
 - OS: 
```
jhorbulyk@JH-Latitude-7480:~$ cat /etc/*-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.5 LTS"
NAME="Ubuntu"
VERSION="16.04.5 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.5 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```

**Additional context**
In my particular case, the server is configured to report back a domain that is different from `SomeDomain` in the NTLM type 2 message which may be a contributing factor.

**Comment by vikiCoder** [comment]
Hi @jhorbulyk,

We have added the functionality to infer domain from username (if provided) in NTLM auth helper in the latest version of the Postman app (v7.14.0).
