### ISSUE TITLE
List Rendered Incorrectly

### ISSUE THREAD

**Issue by kszafran** [a85/POSTMan-Chrome-Extension#5223]
**Describe the bug**
List items are interspersed with empty `<p></p>` paragraphs when there is a long code block in the description. This happens with all kinds of bullet points: `-`, `+`, `*` (even with numbers `1.`, which apparently are rendered as unordered lists too).

Also, the list items `<li>` are not inside a `<ul>` tag at all. That tag is empty (`<ul></ul>`).

**To Reproduce**
1. Import the following collection into Postman:
```
{
	"info": {
		"_postman_id": "2974e1db-be66-461e-bc1e-a974a35bdfb2",
		"name": "My Buggy List",
		"description": "Something\n\n# Header\n\nSome list\n- item 1\n- item 2\n- item 3\n\n## Another Header\n\nThis is long:\n\n```\neasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfeasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfeasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfeasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfeasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfeasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdf\n```",
		"schema": "https://schema.getpostman.com/json/collection/v2.1.0/collection.json"
	},
	"item": []
}
```
2. View the documentation in web.

**Expected behavior**
There should be no extra tags between the list items.

**Screenshots**
<img width="1109" alt="screen shot 2018-09-21 at 14 27 54" src="https://user-images.githubusercontent.com/3056812/45878706-bc893a00-bdaa-11e8-9ae2-8a2fdf575fae.png">

If you only delete the triple backticks around the code block, the list renders just fine:
<img width="1111" alt="screen shot 2018-09-21 at 14 28 39" src="https://user-images.githubusercontent.com/3056812/45878711-c57a0b80-bdaa-11e8-9b77-5642ae10c992.png">

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version: 6.3.0 [e.g. 6.0.1]
 - OS: macOS High Sierra 10.13.6
 - Browser: Chrome 68.0.3440.106

**Comment by ankit-m** [comment]
This issue is fixed.
