### ISSUE TITLE
Example responses are not rendered in documentation if the first one is empty

### ISSUE THREAD

**Issue by numaanashraf** [a85/POSTMan-Chrome-Extension#5224]
If the first response is 200 and empty body
All the following example response will gone.

# Video
https://youtu.be/6CjFMiZ5Tmo

# Possible reason
All the response example is in the same `html DOM ` if the first one do not have response. The response DOM will not be created. Therefore, all the following response will not shown.

Originally posted by @AlphaWong at https://github.com/postmanlabs/postman-docs/issues/1413

**Comment by godfrzero** [comment]
@AlphaWong Thanks for reporting this, we'll get this fixed in the next release of the public documentation.

**Comment by godfrzero** [comment]
This has been fixed now. Feel free to re-open if you still see this happening.
