### ISSUE TITLE
Next/Previous in Find in Response Body

### ISSUE THREAD

**Issue by kolonuk** [a85/POSTMan-Chrome-Extension#5226]
**Describe the bug**
When using the Find in the response Body tab, the Next and Previous arrows do the opposite of what they say - Next goes to the previous occurrence, and Previous goes to the next occurrence.

(sorry if this is a duplicate, I tried my hardest to search the issues for this or something like it)

**To Reproduce**
1. Get a response in the Body tab.  Make sure that you have at least three occurrences on separate lines.
2. Click the magnifying glass icon, or press CTRL+F, and enter the text you want to find.
3. Click the "Next" arrow.

**Expected behaviour**
The Next occurrence of the text you want to find is highlighted.

**Actual behaviour**
The Previous occurrence of the text you want to find is highlighted.  (If the first occurance is highlighted, the highlight/focus will reverse wrap to the end of the Body text.)

**Screenshots**
First find: (scroll bar position indicator is hidden behind the find popup)
![image](https://user-images.githubusercontent.com/5969835/45891155-ccaa1500-bdbc-11e8-821b-6e74053b04f2.png)
"Next" button clicked: (Note the scroll bar position)
![image](https://user-images.githubusercontent.com/5969835/45891194-e0557b80-bdbc-11e8-9b4a-bf932a10d4c2.png)
"Next" button clicked again:  (Note the highlight position is the previous occurance)
![image](https://user-images.githubusercontent.com/5969835/45891217-eea39780-bdbc-11e8-9f8e-a8688ec0c03c.png)

**App information (please complete the following information):**
 - Native app
 - Postman Version 6.2.5 (auto update to 6.3 doesn't work yet...)
 - OS: Windows 10, 1803

**Comment by powelli** [comment]
Same issue present in the native Mac client too

- Native app
- Postman Version 6.6.1
- OS: MacOS High Sierra Version 10.13.4

**Comment by kolonuk** [comment]
Still an issue in 6.7.4...

**Comment by numaanashraf** [comment]
We've fixed this in Postman v7.1.0

**Comment by kolonuk** [comment]
Bit late, but yes, this is now fixed in 7.8.0.  Thanks!
