### ISSUE TITLE
Extra bottom-border for the URL input box

### ISSUE THREAD

**Issue by abhijitkane** [a85/POSTMan-Chrome-Extension#5230]
<img width="1040" alt="screen shot 2018-09-23 at 10 36 29" src="https://user-images.githubusercontent.com/681190/45924383-9daab500-bf1c-11e8-9bb2-3a400673ab57.png">

Postman for Mac
Version 6.3.0
OS X 17.3.0 / x64

**Comment by numaanashraf** [comment]
@abhijitkane does this happen only when you zoom in/out?

**Comment by abhijitkane** [comment]
@numaanashraf yep, only on zoom in

**Comment by arlemi** [comment]
Fixed in 7.17.0
