### ISSUE TITLE
Monitor summary page shows monitor in failed state when it's healthy

### ISSUE THREAD

**Issue by ash007-postman** [a85/POSTMan-Chrome-Extension#5231]
<img width="1151" alt="screen shot 2018-09-24 at 1 20 43 pm" src="https://user-images.githubusercontent.com/41741228/45941613-aecaf300-bffc-11e8-90a8-474d9a680f4c.png">

**Comment by godfrzero** [comment]
The listing view displays the state of that monitor *in the selected timeframe*, which could be within the last 24 hours, 7 days, or 30 days. If there are any failures in that time, the monitor is unhealthy in that timeframe.

**Comment by carlclark267ds** [comment]
I would be happy with a few more time frame options - example, 1 hour, 2 hours, 4 hours, 8 hours.

**Comment by godfrzero** [comment]
FYI @vkaegis

**Comment by vkaegis** [comment]
@carlclark267ds Thanks for the feedback! We'll look at adding this...

**Comment by sankalp0o** [comment]
I'm closing this in favor of #3217 which is the same feature request.
