### ISSUE TITLE
Postman Console shows the timestamps incorrectly

### ISSUE THREAD

**Issue by abhijitkane** [a85/POSTMan-Chrome-Extension#5233]
17:00 should be shown as 17:00 or 5 pm.
The console screenshot shows 05:00 as the timestamp.

Seen on Postman for Mac
Version 6.3.0
OS X 17.3.0 / x64

<img width="322" alt="screen shot 2018-09-24 at 17 08 41" src="https://user-images.githubusercontent.com/681190/45951185-28280d00-c020-11e8-97e8-8b2a68beab76.png">

**Comment by kamalaknn** [comment]
@abhijitkane Thanks for the report and the fix!

This will be rolled out in the next stable release.

**Comment by numaanashraf** [comment]
Verified that the fix is available on stable (v6.5.3)
