### ISSUE TITLE
Error: tunneling socket could not be established, statusCode=407.

### ISSUE THREAD

**Issue by jaspreetcj** [a85/POSTMan-Chrome-Extension#5235]
When trying to hit a rest URL, I get an error back
Already set the proxy in settings, general
tried both using detect system proxy and manually entering the proxy.
Error: tunneling socket could not be established, statusCode=407.

![image](https://user-images.githubusercontent.com/43545578/45960628-41d64e00-c03a-11e8-8be0-d44244c965cb.png)

App information (please complete the following information):

Native App
Postman Version 6.3.0
OS: WINDOWS 7
Additional context

same url works from browser
same url works from java client
same url works on my colleagues machine postman app

**Comment by numaanashraf** [comment]
statusCode=407 seems to be related to proxy authentication. Postman doesn't support authenticated proxies at the moment. We are tracking this issue at #3566.

**Comment by jaspreetcj** [comment]
But, how does it work in another older version of Postman on my colleagues machine, who is not setting proxy at all.

**Comment by numaanashraf** [comment]
@jaspreetcj Is your colleague using Postman's Native Apps or Chrome App? Could you also check whether your colleague has any environment variables set globally that overrides proxy? "HTTP_PROXY" or "HTTPS_PROXY".

**Comment by jaspreetcj** [comment]
its chrome app
Postman for Chrome
Version 5.5.3
win / x86-64
Chrome 65.0.3325.146  
No such env variables...

**Comment by menakaprabu** [comment]
Hi, I am getting same issue "Error: tunneling socket could not be established, statusCode=407" with proxy setup. I am using postman-windows version: 10.23.8. Please suggest
