### ISSUE TITLE
Get folder of open request

### ISSUE THREAD

**Issue by ben-eichler-abcs** [a85/POSTMan-Chrome-Extension#5236]
**Is your feature request related to a problem? Please describe.**
I have stored a large number of requests in a folder structure. When I reopen Postman, the requests I had open in the last session are open again, but I sometimes forget which folder the open request is stored in. I have similar request names at times, so the storage path would be useful to know.

**Describe the solution you'd like**
It would be great to be able to hover on the tab name, and see the path appear in a tooltip.

**Comment by vkaegis** [comment]
@ben-eichler-abcs Thanks for writing in! I can see how this can be super useful, marking it as a feature request for now. We've been working on improvements to the tab interface over the last few versions and still have some in the pipeline. Will keep you updated!

**Comment by giridharvc7** [comment]
This is now fixed, please check out our new version 8.3.0 or [Postman web](https://go.postman.co/build). We'd love to know what you think!
<img width="776" alt="Screenshot 2021-04-27 at 7 38 50 PM" src="https://user-images.githubusercontent.com/1040583/116255789-34ecde80-a790-11eb-8329-fc590bede565.png">
