### ISSUE TITLE
Losing "Get Link" state after closing and re-opening share modal

### ISSUE THREAD

**Issue by shamasis** [a85/POSTMan-Chrome-Extension#5238]
**Describe the bug**
Losing "Get Link" state after closing and re-opening share modal.

**To Reproduce**
1. Create a collection
2. Open "Share Collection" and move to "Get Link" Tab
3. Generate link
4. Close the Modal
5. Open "Share Collection" and move to "Get Link" Tab again

**Expected behavior**
The "Get Link" button should stay "Update Link"

**App information (please complete the following information):**
Postman for Mac
Version 6.3.1-beta180918-2332
OS X 17.7.0 / x64

**Comment by numaanashraf** [comment]
Not reproducible on Postman v7.0. Closing.
