### ISSUE TITLE
Move self updating mechanism to snaps on Linux

### ISSUE THREAD

**Issue by uvarvu** [a85/POSTMan-Chrome-Extension#5239]
It's really annoying updating Postman behind a proxy because it doesn't work.   I manually have to download the application from the website every time.

What should happen is that Postman is distributed as a snap package.   The snap package manager is cross platform and does work behind a proxy.   Why wasn't this considered?

**Comment by numaanashraf** [comment]
@uvarvu We are tracking this at #4576
