### ISSUE TITLE
 Codegen issue with RestSharp post request when body is passed in the format of Raw or and x-www-form-urlencoded values 

### ISSUE THREAD

**Issue by Ramya-From-Postman** [a85/POSTMan-Chrome-Extension#5240]
When we use postman app to make an API post request with the body containing **raw or x-www-form-urlencoded** values, it works fine. However, the issue arises when I try it using the c#(RestSharp) code generated from postman app as it adds "undefined" under request.AddParameter of the request body. 

**To Reproduce**

1. Create a post request by passing the body in the form of "raw or x-www-form-urlencoded"
2. Generate a code in c#(RestSharp)

**Expected behavior**
The respective **content-type** should be generated instead of undefined.

**Screenshots**
Sample code generated with Raw body:
![image](https://user-images.githubusercontent.com/40994626/46005667-65010c00-c0d3-11e8-8f5c-8d698f32c27a.png)

The expected code should look like:
![image](https://user-images.githubusercontent.com/40994626/46005736-911c8d00-c0d3-11e8-9011-d53a793f5f1b.png)

**Comment by ParrisSikorski** [comment]
I've literally looked at 12-15 articles trying to figure out why this wasn't working. Thank you so much for posting the solution!

**Comment by abhijitkane** [comment]
@Ramya-From-Postman @ParrisSikorski in Postman 7.2.1, we've introduced bug-fixes, support for two new languages (JS-Fetch and Powershell), and the ability to configure certain aspects of the generated snippet with the 'Experimental Codegen Mode' flag enabled in Postman's global settings.

This particular issue has been fixed, and can be seen with the 'Experimental Codegen mode' flag set.
