### ISSUE TITLE
postman header sign "\r\n" how to add

### ISSUE THREAD

**Issue by wuxing164** [a85/POSTMan-Chrome-Extension#5242]
use postman add header but not the corrent result respone.
use php code to run it has corrent result response
the php code is 

>   $agent = "Mozilla/5.0 (iPhone; CPU iPhone OS 11_0 like Mac OS X) AppleWebKit/604.1.38 (KHTML, like Gecko) Version/11.0 Mobile/15A372 Safari/604.1" ;

        $header = "User-Agent:{$agent}\r\n" ;
        $header .= "Referer:http://wap.bai.com/\r\n" ;

        curl_setopt_array($curl, array(
            CURLOPT_URL => "http://interface.bai.com/hls/new/get/25730312/25730312/1200?source=wapyy&callback=",
            CURLOPT_RETURNTRANSFER => true,
            CURLOPT_ENCODING => "",
            CURLOPT_MAXREDIRS => 10,
            CURLOPT_TIMEOUT => 30,
            CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
            CURLOPT_CUSTOMREQUEST => "POST",
            CURLOPT_HTTPHEADER => array($header),
        ));

the postman curl code is

>   curl_setopt_array($curl, array(
  CURLOPT_URL => "http://interface.bai.com/hls/new/get/25730312/25730312/1200?source=wapyy&callback=",
  CURLOPT_RETURNTRANSFER => true,
  CURLOPT_ENCODING => "",
  CURLOPT_MAXREDIRS => 10,
  CURLOPT_TIMEOUT => 30,
  CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
  CURLOPT_CUSTOMREQUEST => "POST",
  CURLOPT_HTTPHEADER => array(
    "cache-control: no-cache",
    "postman-token: 15054ba6-e20f-7a62-130a-6efd3fbedb0d",
    "referer: http//wap.bai.com/",
    "user-agent: Mozilla/5.0 (iPhone; CPU iPhone OS 11_0 like Mac OS X) AppleWebKit/604.1.38 (KHTML, like Gecko) Version/11.0 Mobile/15A372 Safari/604.1"
  ),
));

the header add the sign "\r\n" can fix the probelm,but how postman to add it.

**Comment by a85** [comment]
Closing this as I am not clear what exactly needs to be done here.
