### ISSUE TITLE
Missing collections locally and New Dummy Collection created

### ISSUE THREAD

**Issue by sumit0k** [a85/POSTMan-Chrome-Extension#5243]
**Describe the bug**
I am being shown only one of my collection in a workspace, which has much more. Also `Dummy Collection 1`, a new collection is being shown with a lock sign in front of it.

**Expected behavior**
All collections synced to cloud on my account should be shown

**Screenshots**
https://www.dropbox.com/s/f1i5chombbevjet/Screenshot%202018-09-25%2017.55.18.png?dl=0
https://www.dropbox.com/s/gbpweklppe8swz8/Screenshot%202018-09-25%2017.55.18%282%29.png?dl=0

**App information (please complete the following information):**
 - App Type [Native App]
 - Postman Version [6.3.0]
 - OS: [macOS Mojave 10.14]

**Comment by numaanashraf** [comment]
@sumitkumar1209 Is this still happening. Can you share steps we can use to replicate this?

**Comment by sumit0k** [comment]
I didn't signed in fresh after that, so cannot confirm re-occurence.

**Comment by numaanashraf** [comment]
Closing this issue as we are unable to reproducible this on the latest version of Postman (v7.1.0).
