### ISSUE TITLE
Leaving a private workspace in the Postman app renders the app in a locked state

### ISSUE THREAD

**Issue by abhijitkane** [a85/POSTMan-Chrome-Extension#5244]
For teams on enterprise, leaving a private workspace from the Browse mode leaves the app in an unusable state. I see a websocket error saying 'You're not part of this workspace' while trying to fetch workspace dependencies, and the client doesn't handle that error.

Seen on Postman for Mac, Version 6.3.0, OS X 17.3.0 / x64

**Comment by preethammavin** [comment]
This issue has been fixed
