### ISSUE TITLE
If I'm the last user in a team WS, leaving the WS doesn't show the server's error in the UI

### ISSUE THREAD

**Issue by abhijitkane** [a85/POSTMan-Chrome-Extension#5245]
If I'm the last user in a team workspace, and I leave the workspace (from the build or browse modes), the server error isn't handled on the client, and the app thinks I'm still in the workspace.

Seen on Postman for Mac
Version 6.3.0
OS X 17.3.0 / x64

**Comment by numaanashraf** [comment]
Fixed in Postman v7.1.0
