### ISSUE TITLE
Closing single unsaved tab attempts to close all other unsaved tabs

### ISSUE THREAD

**Issue by JP-from-Postman** [a85/POSTMan-Chrome-Extension#5247]
Please read through the [guidelines](https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues) before creating a new issue.

**Describe the bug**
After cancelling out of "Close all tabs" from the "Save request" dialogue, OSX client attempts to close **all** unsaved request tabs when the user closes a **single** tab.

**To Reproduce**
1) Create a collection with 4 saved requests
2) Open tabs for all 4 requests, and edit each one without saving
3) Delete all but one of the requests in the collection (leave all tabs open)
4) Right-click on any open tab, and select "Close All Tabs"
5) When prompted to save the request being closed, click "Save"
6) In the "SAVE REQUEST" dialogue, click "Cancel"
_Behavior (expected): no tabs are closed_
7) Close any single tab by clicking the "X" on the tab indicator
8) When prompted to save the request being closed, click "Don't save"
_Behavior (unexpected): client will continue to try and close each open tab_

**Expected behavior**
At step 8), client should close only a single tab

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version: 6.3.0
 - OS: macOS High Sierra 10.13.6

**Comment by sujayvenaik** [comment]
Hi, we have addressed this issue as part of various improvements we have made to how tabs work in Postman. These changes are up available on our canary channel (https://www.getpostman.com/canary) today and would soon be available on the stable channel. Do try these out in the canary and let us know.

**Comment by sujayvenaik** [comment]
Hey @JP-from-Postman,
This issue has been fixed and is available on the stable channel (v6.4.x).
You can update the app to the latest version.

Thanks again for writing in and reporting this issue.
