### ISSUE TITLE
Uncaught errors TypeError: Cannot read property '_variables' of undefined

### ISSUE THREAD

**Issue by seaguest** [a85/POSTMan-Chrome-Extension#5248]
Hello,

I just installaed postman from Postman-linux-x64-6.3.0.tar.gz (I am using ubuntu 16.04).
when I test with remote server, it works, however when I test with local machine(127.0.0.1),the request gets stuck with showing "Loading", and the following error log comes out in the console:

```

Uncaught errors TypeError: Cannot read property '_variables' of undefined
    at PostmanCollectionRun.<anonymous> (/opt/Postman/app/resources/app/node_modules/postman-runtime/lib/runner/extensions/event.command.js:351:78)
    at PostmanSandbox.<anonymous> (/opt/Postman/app/resources/app/node_modules/postman-sandbox/lib/index.js:102:13)
    at Object.onceWrapper (events.js:316:30)
    at emitOne (events.js:115:13)
    at PostmanSandbox.emit (events.js:210:7)
    at /opt/Postman/app/resources/app/node_modules/postman-sandbox/lib/index.js:125:18
    at /opt/Postman/app/resources/app/node_modules/lodash/lodash.js:4925:15
    at baseForOwn (/opt/Postman/app/resources/app/node_modules/lodash/lodash.js:3010:24)
    at /opt/Postman/app/resources/app/node_modules/lodash/lodash.js:4894:18
    at Function.forEach (/opt/Postman/app/resources/app/node_modules/lodash/lodash.js:9342:14)
    at PostmanSandbox.dispose (/opt/Postman/app/resources/app/node_modules/postman-sandbox/lib/index.js:117:11)
    at disposeRun (/opt/Postman/app/resources/app/services/RuntimeBridge.js:203:60)
    at EventEmitter.handleRunDispose (/opt/Postman/app/resources/app/services/RuntimeBridge.js:479:3)
    at emitTwo (events.js:125:13)
    at EventEmitter.emit (events.js:213:7)
    at WebContents.<anonymous> (/opt/Postman/app/resources/electron.asar/browser/api/web-contents.js:266:13)
    at emitTwo (events.js:125:13)
    at WebContents.emit (events.js:213:7)

```

could anyone help?

**Comment by SamvelRaja** [comment]
@seaguest  Is that a new install or did you update the app manually by downloading, extracting and then moving the files from the command line?
We have seen users having issues while moving files manually. If you did that, I would recommend you do a fresh install (after deleting old files completely). Also, we have seen users having permissions issue with `opt/Postman` directory and the auto-update also does not work here.
Please try installing Postman in the home directory or any other directory where you have write permissions. 

The above error seems like a wrong old file reference. 
@harryi3t  ☝️

**Comment by seaguest** [comment]
@SamvelRaja 

Hello, 

it seems to be a permission problem.

I started as root, then everything goes fine, and then I run as normal user, the GET request starts working, but POST still shows the same error.

I tried to install it in home folder (I just tar -xzvf the package for installation), here is result of ll -ht:

`drwxr-xr-x  3 seaguest seaguest 4.0K 9月   6 14:13 Postman/
`
but still POST doesn't work.

**Comment by SamvelRaja** [comment]
@seaguest  Can you check the permissions of the files in `~/.config/Postman`

**Comment by seaguest** [comment]
@SamvelRaja 
```

-rw-r--r--  1 seaguest seaguest  15K 9月  26 17:08 QuotaManager
-rw-r--r--  1 seaguest seaguest    0 9月  26 17:08 QuotaManager-journal
-rw-rw-r--  1 seaguest seaguest   84 9月  26 17:05 settings.json
-rw-rw-r--  1 seaguest seaguest 1.1K 9月  26 17:05 window
drwx------ 11 seaguest seaguest 4.0K 9月  26 17:05 ./
-rw-rw-r--  1 seaguest seaguest   67 9月  26 17:05 archive
lrwxrwxrwx  1 seaguest seaguest   20 9月  26 17:05 SingletonCookie -> 12860429794965421260
lrwxrwxrwx  1 seaguest seaguest    9 9月  26 17:05 SingletonLock -> DEV-15448
lrwxrwxrwx  1 seaguest seaguest   37 9月  26 17:05 SS -> /tmp/.org.chromium.Chromium.OadrfH/SS=
drwx------  2 seaguest seaguest 4.0K 9月  26 15:11 blob_storage/
-rw-rw-r--  1 seaguest seaguest   79 9月  26 14:54 requester.json
-rw-------  1 seaguest seaguest  135 9月  26 10:01 Preferences
drwx------  2 seaguest seaguest 4.0K 9月  26 10:01 GPUCache/
drwxrwxr-x  3 seaguest seaguest 4.0K 9月  26 00:18 Postman_Config/
drwx------ 38 seaguest seaguest 4.0K 9月  23 23:12 ../
drwx------  4 seaguest seaguest 4.0K 1月  31  2018 IndexedDB/
-rw-rw-r--  1 seaguest seaguest   82 12月 19  2017 runner.json
drwx------  4 seaguest seaguest 4.0K 12月 12  2017 Partitions/
-rw-r--r--  1 seaguest seaguest    0 12月 12  2017 Cookies-journal
-rw-r--r--  1 seaguest seaguest 7.0K 12月 12  2017 Cookies
drwx------  2 seaguest seaguest 4.0K 12月 12  2017 Local Storage/
drwx------  2 seaguest seaguest 4.0K 12月 12  2017 Cache/
drwx------  2 seaguest seaguest 4.0K 12月 12  2017 databases/
drwx------  4 seaguest seaguest 4.0K 12月 12  2017 File System/

```

**Comment by SamvelRaja** [comment]
@seaguest  could you open app using the debug env and send the request
`NODE_DEBUG=request /<INSTALL_DIR>/Postman/Postman`

This will help us to check whether the request sent out to the server and received from the server properly.

If you still face the issue. 
1. The Folder you installed had old postman files (If not kindly ignore this)
2. The config files created have permission issues (rm -rf ~/.config/Postman) solves it 
⚠️ This deletes existing Postman data. If you have un-synced changes, you should not do this.

**Comment by seaguest** [comment]
@SamvelRaja 

In debug mode, I still get the problem:
`
ProtocolHandler~init: Setting custom protocol handling [status: false]
ORM initialization successful
App events bus { name: 'booted', namespace: 'shared' }
App updater event { name: 'checkForElectronVersionUpdated',
  namespace: 'appUpdate' }
App events bus { name: 'booted', namespace: 'requester' }
REQUEST { headers: 
   { Authorization: 'Bearer 291|B37262B97E534D52C52D26B5CE36736D25C4F5974AB2699FFE3E21CCA0494989',
     'Content-Type': 'application/json',
     'User-Agent': 'PostmanRuntime/7.3.0',
     Accept: '*/*',
     Host: '127.0.0.1:1601' },
  url: 'http://127.0.0.1:1601/ems/cms/v1.0/user/content/favorite',
  method: 'POST',
  jar: 
   RequestJar {
     _jar: 
      CookieJar {
        rejectPublicSuffixes: false,
        enableLooseMode: true,
        store: 
         { idx: { 'uland.taobao.com': { '/': { ctoken: Cookie="ctoken=dbvhSbvH2RBIJWLGCqBJVPNm; Expires=Tue, 19 Jan 2038 03:14:07 GMT; Domain=uland.taobao.com; Path=/; hostOnly=false; aAge=26ms; cAge=26ms" } },
           'lkong.cn': { '/': { dzsbhey: Cookie="dzsbhey=zGuRkDG6; Expires=Wed, 27 Feb 2019 03:49:39 GMT; Domain=lkong.cn; Path=/; hostOnly=false; aAge=26ms; cAge=26ms" } },
           'mdetail.tmall.com': { '/': { JSESSIONID: Cookie="JSESSIONID=49BB59DCD56764AD2A110FD640DDE9B6; Expires=Tue, 19 Jan 2038 03:14:07 GMT; Domain=mdetail.tmall.com; Path=/; HttpOnly; hostOnly=false; aAge=26ms; cAge=26ms" } },
           'alimama.com': 
            { '/': 
               { v: Cookie="v=0; Expires=Tue, 19 Jan 2038 03:14:07 GMT; Domain=alimama.com; Path=/; hostOnly=false; aAge=25ms; cAge=25ms",
                 cookie2: Cookie="cookie2=16ce2e467d96267e4ce7976f862246b1; Expires=Tue, 19 Jan 2038 03:14:07 GMT; Domain=alimama.com; Path=/; HttpOnly; hostOnly=false; aAge=25ms; cAge=25ms",
                 t: Cookie="t=6e0a3a8b97016c5fec482fe26d675198; Expires=Sun, 05 Dec 2027 14:52:48 GMT; Domain=alimama.com; Path=/; hostOnly=false; aAge=25ms; cAge=25ms",
                 _tb_token_: Cookie="_tb_token_=f6e85bee76a58; Expires=Tue, 19 Jan 2038 03:14:07 GMT; Domain=alimama.com; Path=/; hostOnly=false; aAge=25ms; cAge=25ms" } },
           'media.jd.com': { '/': { ssid: Cookie="ssid="K2n79WaaScy7AM/t43YqDQ=="; Expires=Tue, 19 Jan 2038 03:14:07 GMT; Domain=media.jd.com; Path=/; hostOnly=false; aAge=25ms; cAge=25ms" } },
           'drgou.com': { '/': { __cfduid: Cookie="__cfduid=d666369952a4b48f33aa1ea929d285abc1536330016; Expires=Sat, 07 Sep 2019 14:20:16 GMT; Domain=drgou.com; Path=/; HttpOnly; hostOnly=false; aAge=32ms; cAge=32ms" } },
           '127.0.0.1': { '/': { _csrf: Cookie="_csrf=dc0a09f97a887e23e696dd0d2b694fd2245d5582fd4a618dd48fe613864ae49ea%3A2%3A%7Bi%3A0%3Bs%3A5%3A%22_csrf%22%3Bi%3A1%3Bs%3A32%3A%22y%9DG%EA%A6%AB%97%F8%B6%E9%E6p%5B%E9%2F%18%25%B5b%E7%EB%EB%1E%B1%AFc%89%7EP%D7Z%A4%22%3B%7D; Expires=Tue, 19 Jan 2038 03:14:07 GMT; Domain=127.0.0.1; Path=/; HttpOnly; hostOnly=false; aAge=32ms; cAge=32ms" } } } } } },
  gzip: true,
  useQuerystring: true,
  strictSSL: false,
  followRedirect: false,
  followAllRedirects: false,
  encoding: null,
  body: '{\n  "os_type": 1,\n  "os_version": "7.1.1",\n  "app_version": "1.0.1",\n  "device_id": "sssssss",\n  "app_key": "LQzS9Yd96ar5",\n  "action": 1,\n  "shop_id": 10000,\n  "disabled": false,\n  "content_type": 1,\n  "content_id": [1,2,3,4,5]\n}',
  agentOptions: { keepAlive: true },
  callback: [Function] }
REQUEST make request http://127.0.0.1:1601/ems/cms/v1.0/user/content/favorite
REQUEST onRequestResponse http://127.0.0.1:1601/ems/cms/v1.0/user/content/favorite 403 { 'access-control-allow-credentials': 'true',
  'access-control-allow-headers': 'Accept, Content-Type, Content-Length, Accept-Encoding, X-CSRF-Token, Authorization, X-Requested-With, AccessKey',
  'access-control-allow-methods': 'POST, GET',
  'access-control-allow-origin': '*',
  date: 'Wed, 26 Sep 2018 14:42:25 GMT',
  'content-length': '0' }
REQUEST reading response's body
REQUEST finish init function http://127.0.0.1:1601/ems/cms/v1.0/user/content/favorite
REQUEST response end http://127.0.0.1:1601/ems/cms/v1.0/user/content/favorite 403 { 'access-control-allow-credentials': 'true',
  'access-control-allow-headers': 'Accept, Content-Type, Content-Length, Accept-Encoding, X-CSRF-Token, Authorization, X-Requested-With, AccessKey',
  'access-control-allow-methods': 'POST, GET',
  'access-control-allow-origin': '*',
  date: 'Wed, 26 Sep 2018 14:42:25 GMT',
  'content-length': '0' }
REQUEST end event http://127.0.0.1:1601/ems/cms/v1.0/user/content/favorite
REQUEST emitting complete http://127.0.0.1:1601/ems/cms/v1.0/user/content/favorite
Uncaught errors TypeError: Cannot read property '_variables' of undefined
    at PostmanCollectionRun.<anonymous> (/opt/Postman/app/resources/app/node_modules/postman-runtime/lib/runner/extensions/event.command.js:351:78)
    at PostmanSandbox.<anonymous> (/opt/Postman/app/resources/app/node_modules/postman-sandbox/lib/index.js:102:13)
    at Object.onceWrapper (events.js:316:30)
    at emitOne (events.js:115:13)
    at PostmanSandbox.emit (events.js:210:7)
    at /opt/Postman/app/resources/app/node_modules/postman-sandbox/lib/index.js:125:18
    at /opt/Postman/app/resources/app/node_modules/lodash/lodash.js:4925:15
    at baseForOwn (/opt/Postman/app/resources/app/node_modules/lodash/lodash.js:3010:24)
    at /opt/Postman/app/resources/app/node_modules/lodash/lodash.js:4894:18
    at Function.forEach (/opt/Postman/app/resources/app/node_modules/lodash/lodash.js:9342:14)
    at PostmanSandbox.dispose (/opt/Postman/app/resources/app/node_modules/postman-sandbox/lib/index.js:117:11)
    at disposeRun (/opt/Postman/app/resources/app/services/RuntimeBridge.js:203:60)
    at EventEmitter.handleRunDispose (/opt/Postman/app/resources/app/services/RuntimeBridge.js:479:3)
    at emitTwo (events.js:125:13)
    at EventEmitter.emit (events.js:213:7)
    at WebContents.<anonymous> (/opt/Postman/app/resources/electron.asar/browser/api/web-contents.js:266:13)
    at emitTwo (events.js:125:13)
    at WebContents.emit (events.js:213:7)

`

Indeed the following command solves the problem.
`
rm -rf ~/.config/Postman
`
Anyway now it works, thanks.

**Comment by b1oki** [comment]
How fix this error?

```
Not disabling GPU
shm_open() failed: Permission denied
ProtocolHandler~setDefaultProtocolClient: Command failed: xdg-mime default Postman.desktop x-scheme-handler/postman
/bin/sh: 1: xdg-mime: not found

Error org.freedesktop.DBus.Error.Failed: cannot use setting "default-url-scheme-handler": not allowed
Main~createDefaultWorkingDir - Default working dir creation already attempted
1572616132571 main info "Booting Postman 7.10.0, linux-4.15.0-62-generic on x64"
1572616132578 main info "EventBus~initialize - Success"
1572616132586 main info "UpdateHandler~init - Success"
1572616132588 main info "RuntimeExecutionService~initialized: Success"
1572616132589 main info "LinuxAutoUpdater~Cleanup - Initial cleanup successful"
1572616132666 main info "Bootstrap-models~bootstrap - Success"
1572616132816 main info "window-manager~newSharedWindow: Shell loaded"
1572616133944 main info "Main~AppEvents - Received booted event for process shared"
INTERCEPTOR CONNECTIVITY: Connecting to Interceptor Bridge
InterceptorBridge: Trying to connect Native App IPC~Interceptor Bridge
1572616135195 main info "Main~AppEvents - Received booted event for process requester"
TypeError: Cannot read property '0' of undefined
    at Object.handleMenuAction (/snap/postman/96/usr/share/Postman/resources/app/services/menuManager.js:502:114)
    at click (/snap/postman/96/usr/share/Postman/resources/app/services/menuManager.js:255:78)
    at MenuItem.click (/snap/postman/96/usr/share/Postman/resources/electron.asar/browser/api/menu-item.js:56:9)
    at Function.executeCommand (/snap/postman/96/usr/share/Postman/resources/electron.asar/browser/api/menu.js:31:13)
1572616155046 main error "Main~handleUncaughtError - Uncaught errors",{"name":"TypeError","message":"Cannot read property '0' of undefined","stack":"TypeError: Cannot read property '0' of undefined\n    at Object.handleMenuAction (/snap/postman/96/usr/share/Postman/resources/app/services/menuManager.js:502:114)\n    at click (/snap/postman/96/usr/share/Postman/resources/app/services/menuManager.js:255:78)\n    at MenuItem.click (/snap/postman/96/usr/share/Postman/resources/electron.asar/browser/api/menu-item.js:56:9)\n    at Function.executeCommand (/snap/postman/96/usr/share/Postman/resources/electron.asar/browser/api/menu.js:31:13)"}
Main~handleUncaughtError - Uncaught errors TypeError: Cannot read property '0' of undefined
    at Object.handleMenuAction (/snap/postman/96/usr/share/Postman/resources/app/services/menuManager.js:502:114)
    at click (/snap/postman/96/usr/share/Postman/resources/app/services/menuManager.js:255:78)
    at MenuItem.click (/snap/postman/96/usr/share/Postman/resources/electron.asar/browser/api/menu-item.js:56:9)
    at Function.executeCommand (/snap/postman/96/usr/share/Postman/resources/electron.asar/browser/api/menu.js:31:13
```

Delete config via `rm -rf ~/.config/Postman` doesn't help.

Turned back to postman (v6/stable) 6.7.6, it's doesn't crash, but auth throw Google don't works.
Change to 7.10.0, try start without auth. It's works. How I can fix auth via Google?

Currently setup password and auth via email+psw.

**Comment by b1oki** [comment]
Turned back to postman (v6/stable) 6.7.6, it's doesn't crash, but auth throw Google don't works.
Change to 7.10.0, try start without auth. It's works. How I can fix auth via Google?
