### ISSUE TITLE
Delete cookie CTA collapses the domain

### ISSUE THREAD

**Issue by godfrzero** [a85/POSTMan-Chrome-Extension#5251]
**Describe the bug**
Within the Manage Cookies modal, when I click on the `X` CTA next to a domain, it will collapse the row before removing the cookies for that domain.

**To Reproduce**
1. Click on the `Cookies` link below the URL bar
2. Click the `X` CTA which appears when hovering on a domain
3. The row collapses
4. Then later, the row disappears as the cookies are removed.

**Expected behavior**
Clicking within the CTA should remove the cookies without collapsing the row. Click anywhere else on the row (anywhere inert), should simply collapse the row.

**App information (please complete the following information):**
Postman for Mac
Version 6.3.0
OS X 18.0.0 / x64

**Comment by codenirvana** [comment]
Fixed in the latest version of the Postman app v7.6.0.
