### ISSUE TITLE
Environments shared in team workspace do not show in team members' team workspace

### ISSUE THREAD

**Issue by paulsuen** [a85/POSTMan-Chrome-Extension#5254]
**Describe the bug**
Environments shared in teams workspace do not show in team members' team workspace

**To Reproduce**
1. sign in with team account A, share an environment with team workspace,
2. switch to another team account B and go to team workspace, can not see the shared environment.

**Expected behaviour**
environment shared to team workspace should show in team workspace between team members

**App information (please complete the following information):**
 - App Type [Native App]
 - Postman Version [6.3.0]
 - OS: [macOS Mojave 10.14]

**Comment by numaanashraf** [comment]
@paulsuen Could you check whether the environment is shared properly by visiting the Postman dashboard - https://app.getpostman.com.

**Comment by numaanashraf** [comment]
@paulsuen Closing this as this seems to be an isolated issue. Please re-open if you are still facing this issue.
