### ISSUE TITLE
Collections created before initial syncing causes them to reach a locked state / get vanished

### ISSUE THREAD

**Issue by sivcan** [a85/POSTMan-Chrome-Extension#5255]
**Describe the bug**
The bug can be seen in the two videos.
1. If the network speed is good (fast in my case ~54 Mbps), then the collection created before or during the initial sync vanishes from the app.
https://youtu.be/eg6-vTDCcSQ

2. If the network speed is throttled down to as low as EDGE (~240Kbps), the collections created during the phase when the app is connecting to sync, reach a `locked` state (Don't have the permission to modify) after the app has **started** syncing.
Also, if the app syncs again then these locked collections are removed.
https://youtu.be/CDellebsjBQ

**To Reproduce**
- The videos can be followed to reproduce the bug.
- This post can be followed incase the 'Network Link Conditioner' needs to be setup on a mac - https://blog.greggant.com/posts/2018/01/30/network-throlling-macos-osx.html

**Expected behavior**
The collections should not reach a locked state / vanish from the app.

**App information:**
 - App Type - Native App
 - Postman Version - v6.3.0
 - OS: macOS Mojave v10.14

**Comment by colorpump** [comment]
I have the same issue with locked collections now.

I signed up with my Google Account. Created collection, then a request. Could not save it in this Collection (didn't show up) - and I see the locked icon next to the collection. Then I created a collection from the Save-Request-As Pop Up ... same thing. Now I have four locked collection which I can not unlock or edit but at least delete.

Any solutions?

* App Type - Native App
* Postman v7.0.7
* OS Windows 10

## Update

**Now it works!** I guess it succesfully synced initially, after I finished writing this comment. But that really needed some time, and should be fixed or shown in the UI.
