### ISSUE TITLE
Current value overwrite Initial value for whole team

### ISSUE THREAD

**Issue by DaveLatal** [a85/POSTMan-Chrome-Extension#5258]
Hello I'd like to know, how come that If I change current value for my needs, it overwrite same value for all in our team? 

**Case:** 

**Pre-conditions:**
1) You must be logged into some project with workspace which is shared to some your colleague
2) You must have some enviroment shared to some your colleague

**Steps to reproduce:**
1) Open postman with workspace from preconditions
2) Go to Enviroments and select your enviroment from preconditions
3) Change some Current value and press update
4) Go to your colleague and check the value which has been changed

**Actual results:**
Value has been changed on colleague PC too

**Expected results:**
Value has been changed only on my PC not on colleague, according the info message:
![postmanbug](https://user-images.githubusercontent.com/17565339/46081506-effa0900-c19c-11e8-9a7c-2ec165bb30e0.png)

**Comment by harryi3t** [comment]
Hey @DaveLatal 
We only sync the initial values. 
There is a setting in the App `Auto persist variable values`, which determines whether a change to current value should auto update the initial value or not.
All the users upgrading the App have this setting turned on by default to keep the behavior backward compatible.
I think this might be the case with you. Could you try turning off this setting and try again?

You can easily turn this setting off from the settings modal
![postman](https://user-images.githubusercontent.com/5207331/46081986-863d2780-c1bb-11e8-93dc-f4e853bac823.png)

**Comment by DaveLatal** [comment]
Thank you for answer, it works for us!!

**Comment by nelsonprsousa** [comment]
> Hey @DaveLatal
> We only sync the initial values.
> There is a setting in the App `Auto persist variable values`, which determines whether a change to current value should auto update the initial value or not.
> All the users upgrading the App have this setting turned on by default to keep the behavior backward compatible.
> I think this might be the case with you. Could you try turning off this setting and try again?
> 
> You can easily turn this setting off from the settings modal
> ![postman](https://user-images.githubusercontent.com/5207331/46081986-863d2780-c1bb-11e8-93dc-f4e853bac823.png)

This option disappeared. How can we do it now? 😓

**Comment by PostIt59** [comment]
Hello @nelsonprsousa have you found any solution. @harryi3t can you provide any solution please ? 
Thx

**Comment by alzcurda** [comment]
This option was removed in version v8.0.8

https://github.com/postmanlabs/postman-app-support/issues/9887#issuecomment-828710916

You can reset manually all variables to update current values, or generate a preload script.
