### ISSUE TITLE
Postman Console: request body form-data: same keys are not rendered

### ISSUE THREAD

**Issue by MichiHC** [a85/POSTMan-Chrome-Extension#5259]
**Describe the bug**
I want to upload a file with a POST request. Aditionally I need to send two key-value pairs with the same key. When sending the request, Postman only sends one of the key-value pairs. How can I send both values?

**To Reproduce**
1. Create a POST request
2. Switch to Body
3. Select to enter form-data
4. Add a key-value pair for adding a file
5. Add a key-value pair: key "test" value "first value"
6. Add a key-value pair: key "test" value "second value"
7. Send the request
8. Only file and "second value" are sent to the server.

**Expected behavior**
All thre key-value pairs are sent to the server.

**Screenshots**
![postman_2018-09-26_16-24-57](https://user-images.githubusercontent.com/32326575/46086623-c515b200-c1a8-11e8-9a04-86fbb3146fbf.png)
![postman_2018-09-26_16-26-35](https://user-images.githubusercontent.com/32326575/46086979-9fd57380-c1a9-11e8-8b73-dfe494f6f8f5.png)

**App information (please complete the following information):**
Postman for Windows
Version 6.3.0

**Comment by numaanashraf** [comment]
@MichiHC This is a bug in Postman Console. The same key is not rendered. Are you facing any issues with the actual request that is sent to the server?

**Comment by MichiHC** [comment]
I checked it again and the request seems to be correct.

**Comment by codenirvana** [comment]
Fixed in the latest version of the Postman app v7.6.0.
