### ISSUE TITLE
Address Line Bug - Blocks body parameters

### ISSUE THREAD

**Issue by Postman-Gabriel** [a85/POSTMan-Chrome-Extension#5260]
**Describe the bug**
With an active value in the body of the request, the type of the variable is overlapping the address of the API request

**To Reproduce**
1. Create a body variable
2. Click on the address bar
See error

**Expected behavior**
Expected the address bar to cover the field type of the variable behind it, therefore making it easier to see address.

**Screenshots**
![image](https://user-images.githubusercontent.com/40899145/46088306-270af300-c17a-11e8-8695-f20f7276389a.png)

**App information (please complete the following information):**
 - App Type: Native app
 - Postman Version: 6.3.0
 - OS: Windows

**Comment by numaanashraf** [comment]
Fixed in Postman v7.0
