### ISSUE TITLE
Bearer Token value is not present in the dropdown

### ISSUE THREAD

**Issue by shravanipl** [a85/POSTMan-Chrome-Extension#5261]
I am unable to find **Bearer Token** value in **Type** dropdown present under **_Authorization tab_**

![postman](https://user-images.githubusercontent.com/38989344/46107360-c80ca480-c1a0-11e8-977e-fc8fa8c4e868.jpg)

 - App Type : Postman for Chrome 
 - Postman Version : Version 5.5.3
 - OS: win / x86-64

**Comment by bhargavkaranam** [comment]
Hi @shravanipl,
The NTLM and Bearer tokens are only available in our native apps. Please note that the Postman Chrome app is being deprecated, we strongly suggest you to switch to our native apps. You can download it from [here](https://www.getpostman.com/apps).

**Comment by tahira702** [comment]
install Postman standalone
