### ISSUE TITLE
I am getting 404 Not found in Postman but when run through newman it works but in Postman i cannot debug

### ISSUE THREAD

**Issue by Rahulcl** [a85/POSTMan-Chrome-Extension#5262]
Please read through the [guidelines](https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues) before creating a new issue.

**Describe the bug**

**To Reproduce**
1. Go to 'postman.'
2. Run {{mailosaurUrl}}/api/messages/await?server=xxx

Actual : 
getting 404 Not found in Postman but when run through newman it works but in Postman i cannot debug

**Screenshots**

**App information (please complete the following information):**
 - App Type [ Native App]
 - Postman v6.3.0 is the latest version
 -Win 10

*
![image](https://user-images.githubusercontent.com/35246823/46125192-9fe17c00-c25a-11e8-9bbc-f56685bd1dd9.png)

**Comment by SamvelRaja** [comment]
@Rahulcl  could you check the request in Postman console?
`View -> Developer -> Show Postman Console`
