### ISSUE TITLE
Single Column Layout in published Documentation

### ISSUE THREAD

**Issue by ash007-postman** [a85/POSTMan-Chrome-Extension#5263]
We would like to show our published documentation in a single column layout (as we can do as logged in authors of the documentation).

**Comment by XaWin** [comment]
Completely agree. Also reported that to the support today and was re-directed here.

**Comment by base64** [comment]
We are also looking for the feature, mainly due to our markup descriptions being quite wide, the site displays much better in single column mode.

**Comment by rcmstark** [comment]
Hi guys, any preview of when you guys will add this feature? As it is in the preview, I guess it will not be to add in the published documentation.

**Comment by rcmstark** [comment]
Do you guys have any preview of when you guys will add this feature? As it "View in Web" author area, I guess it will not be complicate to add in the published documentation.

**Comment by ahait** [comment]
yes, we are also looking for this feature!

**Comment by viko42** [comment]
Also looking for that!

**Comment by AJRDRGZ** [comment]
Also looking for that!

**Comment by dacardona** [comment]
It would be great to have one single column. It shows much better since if you haven't a request, the long black column it's not nice, also the code feels somewhat tight. Thanks!!

**Comment by mr-wakeup** [comment]
Our documentation contains a lot of text in markdown, so there are no request samples to show.
Users have to view empty big black rectangle without request/response samples.
This is really ugly, like this: https://documenter.getpostman.com/view/33232/markdown-in-api-documentation/JsGc?_ga=2.100355414.914383578.1562570440-1996123061.1561626980&version=latest

Please, add ability to show published documentation in a single column layout.

**Comment by thomasazdon** [comment]
I would also love to have a single column default.  Our reason is we have created visualizations for our training postman examples.  On each visualization we provide a link to the documentation (direct to the section in the training example.  When you view documentation in the postman response window in visualizer - there is very little space and we really only want the documentation associated with that item appearing. Instead they get the navigation menu on the left, the actual documentation in the middle and the curl information on the right - which they already have in the postman case.
