### ISSUE TITLE
How to ignore few fields validation in the response body, which is an array 

### ISSUE THREAD

**Issue by DivyaKallu** [a85/POSTMan-Chrome-Extension#5264]
I have response body which looks like the below, 

stored the response into an array
var Validate_ResponseBody = '[{"id":1,"name":"Study1"},{"id":2,"name":"Study2"},{"id":3,"name":"Study3"}]';

var Validate_PartResponse = '{"id":1,"name":"Study1"}';

using pm.response.to.have.body, I am able to validate whether name as Study1 exists with id as 1
pm.test("Body is correct", function () {
    pm.response.to.have.body(Validate_PartResponse );
});

But if i have to ignore the study name and validate only id i am getting error.
var Validate_PartResponse = '{"id":1}';
pm.test("Body is correct", function () {
    pm.response.to.have.body(Validate_PartResponse );
});

Is there a way this can be done?
This is a small response but we have bigger responses with created date and time, which changes for every execution and we want to ignore those while validating.

Using Postman Native App

**Comment by numaanashraf** [comment]
@DivyaKallu We recommend reaching out to the wider Postman Community (https://community.getpostman.com/) for help with this issue.

Issue Guidelines: https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues
