### ISSUE TITLE
Support SHA-256 for digest authentication

### ISSUE THREAD

**Issue by vanillajonathan** [a85/POSTMan-Chrome-Extension#5265]
Postman supports using the MD5 cryptographic hash function for digest access authentication but does not support the SHA-256 cryptographic hash function.

The [RFC 7616](https://tools.ietf.org/html/rfc7616) (which succeeds the [RFC 2617](https://tools.ietf.org/html/rfc2617)) adds support for the SHA-256 and SHA-512/256 algorithms.

Note, RFC 2617 is designed as a "draft standard" while RFC 7616 is designated as a "proposed standard".

**Comment by arlemi** [comment]
This was added in Postman 7.27, please update or [download the latest version of the app](https://www.postman.com/downloads/). 🙂
