### ISSUE TITLE
Postman docs markdown rendering

### ISSUE THREAD

**Issue by loopDelicious** [a85/POSTMan-Chrome-Extension#5269]
Throughout the [Postman docs](https://learning.getpostman.com/docs), kramdown needs to be scooched to markdown.

![markdown](https://user-images.githubusercontent.com/17693714/46161868-91379c80-c23b-11e8-9ae8-596819d592c8.png)

* Rendering inline code (attached screenshot)
* Rendering target blanks, and markdown hyperlinks
* Relative links are hardcoded v6, and redirects are not yet active, so relative links are 404

**Comment by numaanashraf** [comment]
Moved to https://github.com/postmanlabs/postman-docs/issues/1438
