### ISSUE TITLE
Hippa compliant

### ISSUE THREAD

**Issue by night-fury-web** [a85/POSTMan-Chrome-Extension#5270]
Is postman HIPPA compliant?

**Comment by Suhas-Gaikwad** [comment]
- Postman is not yet in compliance with the Health Insurance Portability and Accountability Act (HIPAA). 
- We already have a lot of aspects in line with HIPAA. Refer: https://www.getpostman.com/security
- When you are not signed up for an account, Postman does not store data on servers and all of that is on your local system.
- We are currently working on SOC 2 compliance.
