### ISSUE TITLE
Bug: Node.js native code snippet for form-data requests doesn't actually work

### ISSUE THREAD

**Issue by govindrai** [a85/POSTMan-Chrome-Extension#5274]
When I copy and paste a code snippet that is generated by postman for form-data requests for Node.js -> Native, I get errors when running. I would appreciate an update as I would like to test the postman requests natively as well.

**Comment by NogrTL** [comment]
Same for me.
It's because of **hostname** and **path** are sent as array,while [node documentation](https://nodejs.org/api/http.html#http_http_request_options_callback) said it should be a string

**Comment by NogrTL** [comment]
Here's the code examples

Generated
```javascript
var http = require("https");

var options = {
  "method": "POST",
  "hostname": [
    "sdc",
    "semadatacoop",
    "org"
  ],
  "path": [
    "sdcapi",
    "export",
    "digitalassets"
  ],
  "headers": {
    "token": "ADBCD",
    "brandDatasetId": "533",
    "Cache-Control": "no-cache",
    "Postman-Token": "d8e7f849-843f-4bbb-a006-bf60ac6f6332"
  }
};

var req = http.request(options, function (res) {
  var chunks = [];

  res.on("data", function (chunk) {
    chunks.push(chunk);
  });

  res.on("end", function () {
    var body = Buffer.concat(chunks);
    console.log(body.toString());
  });
});

req.end();
```


End here's corrected version

```javascript
'use strict';
const https = require('https');
const { promisify } = require('util');

const options = {
  method: 'POST',
  hostname: 'sdc.semadatacoop.org',
  path: '/sdcapi/export/digitalassets',
  headers: {
    token: 'ABCD',
    brandDatasetId: '533'
  }
};

const req = https.request(options, res => {
  const chunks = [];

  res.on('data', chunk => {
    chunks.push(chunk);
  });
console.log(res.statusCode);
  res.on('end', () => {
    console.log();
    let body = Buffer.concat(chunks);
    console.log(body.toString());
  });
});

req.end();
```

**Comment by sanusi87** [comment]
in my case, Postman v6.7.4, the query string was ignored. For example if I have this url:

```
  http://abc.com?a=1
```

Then when i generate the code for **Node.js Native**, this is what i got.

```javascript
var http = require("http");

var options = {
  "method": "POST",
  "hostname": [
    "abc",
    "com"
  ],
  "headers": {}
};

var req = http.request(options, function (res) {
  var chunks = [];

  res.on("data", function (chunk) {
    chunks.push(chunk);
  });

  res.on("end", function () {
    var body = Buffer.concat(chunks);
    console.log(body.toString());
  });
});

req.end();
```

**Request** and **Unirest** do keep the query string.

**Comment by abhijitkane** [comment]
@govindrai @NogrTL 
Can you try this is Postman 7.2.1, with the 'Experimental Codegen Mode' flag enabled in Postman's global settings? We've introduced bug-fixes, support for two new languages (JS-Fetch and Powershell), and the ability to configure certain aspects of the generated snippet.
All reported issues should be fixed with this flag enabled.

@sanusi87 - the case you mentioned is still a bug. We'll take this up in the next release.

**Comment by shlomo666** [comment]
Hey, I'm using version 7.2.2 on mac, and the flag did fix those issues, but now it doesn't have the port generated for some reason.

My API is:
GET `https://localhost:3000/getSelfBody`

And this is the outcome:
```
var https = require('https');

var options = {
	'method': 'GET',
	'hostname': 'localhost',
	'path': '/getSelfBody',
	'headers': {
	}
};

var req = https.request(options, function (res) {
	... // as usual
});

req.end();
```

**Comment by abhijitkane** [comment]
@shlomo666 Created a new bug at https://github.com/postmanlabs/postman-app-support/issues/7101

Closing this.
