### ISSUE TITLE
NTLM authentication throwing 401 error

### ISSUE THREAD

**Issue by DivyaKallu** [a85/POSTMan-Chrome-Extension#5275]
Hello,

We have NTLM authentication implemented in our application. When i try to run the API in postman by setting the username and password , its throwing 401 unauthorized error. Are there any other settings to do?

![ntlmauthentication](https://user-images.githubusercontent.com/42930624/46193185-e5fe1480-c31a-11e8-9394-55f1c83c212c.JPG)

**Comment by harryi3t** [comment]
@DivyaKallu This looks related to https://github.com/postmanlabs/postman-app-support/issues/4355

Can you share the logs (raw mode) from the Postman console? There will be more than 1 request, plase share all the logs (max 4 requests).

It would look something like this
![image](https://user-images.githubusercontent.com/5207331/45736964-26b6a900-bc0a-11e8-8a80-60a048b1a6bd.png)

**Comment by DivyaKallu** [comment]
This is the log, not sure how to reply in the thread as both the issues are closed.

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>
<title>401 - Unauthorized: Access is denied due to invalid credentials.</title>
<style type="text/css">

</style>
</head>
<body>
<div id="header"><h1>Server Error</h1></div>
<div id="content">
<div class="content-container"><fieldset>
  <h2>401 - Unauthorized: Access is denied due to invalid credentials.</h2>
  <h3>You do not have permission to view this directory or page using the credentials that you supplied.</h3>
</fieldset></div>
</div>
</body>
</html>


Thanks,
Divya.

**Comment by DivyaKallu** [comment]
Hello, any update on this please?

**Comment by DivyaKallu** [comment]
Please find the logs for the 3 URL's in the console:
1. 
![image](https://user-images.githubusercontent.com/42930624/46454142-80020900-c7c2-11e8-9f15-8b4b421e5691.png)

2. 
![image](https://user-images.githubusercontent.com/42930624/46454205-b049a780-c7c2-11e8-833e-ae0776294cf4.png)

3.
![image](https://user-images.githubusercontent.com/42930624/46454233-d2dbc080-c7c2-11e8-9332-19b808580766.png)


Please let me know if you need any other info.
ThankQ.

**Comment by harryi3t** [comment]
@DivyaKallu Looking at the logs everything looks fine. Can you make sure that by credentials you are using in Postman are correct? You can do that by just pasting the request URL in your browser, the browser should show a prompt for username and password. Type the exact same credentials as you have in Postman, and let us know if that works.

**Comment by DivyaKallu** [comment]
Hi Harendra,

As chrome browser takes cares of authentication, it will not show a prompt for username and password.  i am also checking with my team if there is anything wrong with the credentials i enter.

**Comment by harryi3t** [comment]
@DivyaKallu you can try it in an incognito window :) Also, it will confirm whether the credentials are correct.

**Comment by DivyaKallu** [comment]
hmmm... even in incognito window mode, application is not popping out window for credentials. It is automatically taken care.

**Comment by harryi3t** [comment]
@DivyaKallu I am not sure if I know how that works. Maybe it uses the windows credentials. Are the credentials you are using in Postman, same as your account credentials that you use for logging in your system (Windows password)?
If you happen to have a Linux VM, you can test out the endpoint on that.

**Comment by rathodamol** [comment]
Use this configuration as well. 

>> System Proxy should be set to ON
![image](https://user-images.githubusercontent.com/38079053/50283700-fe338a80-0456-11e9-80b1-779f52a794e0.png)
