### ISSUE TITLE
Empty collection activity feed? and Clicking Load more link

### ISSUE THREAD

**Issue by SamvelRaja** [a85/POSTMan-Chrome-Extension#5277]
Dashboard -> Collection Activity 
1. How a collection has zero activity?
2. When it has zero activity, the link shows load more. screenshot the state below

State 1:
![empty activity](https://user-images.githubusercontent.com/5114052/46204694-c75c4580-c33b-11e8-9c04-7005384d5182.PNG)

Upon clicking `Load More`  State 2 reached
![capture](https://user-images.githubusercontent.com/5114052/46204719-d80cbb80-c33b-11e8-8dd1-8414d94f25c8.PNG)

**Comment by ankit-m** [comment]
A fix for this has been pushed.
