### ISSUE TITLE
How to ensure order of two pm.sendRequest calls

### ISSUE THREAD

**Issue by kthulsidoss** [a85/POSTMan-Chrome-Extension#5282]
![auth1](https://user-images.githubusercontent.com/42998906/46252519-3e522500-c487-11e8-973e-b872c69f638b.JPG)

I have 2 requests that needs to be done to set the authentication token , this token is passed to the REST call .
Here is  the code that is there in the pre-tests
--------------------------------------------------------------------------------------------------------------------
```
const siaPostRequest = {
  url: 'https://iam.stage1.bluemix.net/identity/token',
  method: 'POST',
  header: {
        'Accept': 'application/json',
        'Content-Type': 'application/x-www-form-urlencoded'
      },
      body: {
          mode: 'urlencoded',
          urlencoded: [
            {key: "grant_type", value: "urn:ibm:params:oauth:grant-type:apikey"},
            {key: "apikey", value: "4YXfPuSZIDhGahHmClJZGFzaGai8xH9ViW4p0XLWvjVr"},
            {key: "Accept", value: "application/json"},
            {key: "Content-Type", value: "application/x-www-form-urlencoded"}
        ]
      }
};

var getToken = true;

if (!pm.environment.get('accessTokenExpiry') || 
    !pm.environment.get('currentAccessToken')) {
    console.log('Token or expiry date are missing')
} else if (pm.environment.get('accessTokenExpiry') <= (new Date()).getTime()) {
    console.log('Token is expired')
} else {
    getToken = false;
    console.log('Token and expiry date are all good');
}

if (getToken === true) {
    pm.sendRequest(siaPostRequest, function (err, res) {
    console.log(err ? err : res.json());
        if (err === null) {
            console.log('***Abt to set the sia access token *******');
            var responseJson = res.json();
            pm.environment.set("sia_access_token",responseJson.access_token);
            console.log('token from env auth1   ' + pm.environment.get("sia_access_token"));
    
            var expiryDate = new Date();
            expiryDate.setSeconds(expiryDate.getSeconds() + 55);
            pm.environment.set('accessTokenExpiry', expiryDate.getTime());
        }
    });
    
    const siaDesiredPostRequest = {
  url: 'https://iam.stage1.bluemix.net/identity/token',
  method: 'POST',
  header: {
        'Accept': 'application/json',
        'Content-Type': 'application/x-www-form-urlencoded'
        
      },
      body: {
          mode: 'urlencoded',
          urlencoded: [
            {key: "grant_type", value: "urn:ibm:params:oauth:grant-type:iam-authz"},
            {key: "desired_iam_id", value: "crn-crn:v1:bluemix:public:siapoc::a/73be9f58fe97adebbf9fe13eeea2ebe4:instance12345::"},
            {key: "Accept", value: "application/json"},
            {key: "Content-Type", value: "application/x-www-form-urlencoded"},
            {key: "access_token", value: pm.environment.get("sia_access_token")},
        ]
      }
  
};
    
  

pm.sendRequest(siaDesiredPostRequest, function (err, res) {
    console.log(err ? err : res.json());
        if (err === null) {
            console.log('******ABt to set the SIA desired token *************************');
            var responseJson1 = res.json();
            pm.environment.set("sia_desired_token",responseJson1.access_token);
            console.log('sia_desired_token' + pm.environment.get("sia_desired_token"));
            
            
        }
    });


}
```
-----------------------------------------------------------------------------------------------------------
Here is the response from the log
******ABt to set the SIA desired token *************************

then

***Abt to set the sia access token *******
******************************************************************

So it looks like the order of calling the requests are changed , it need to first then second as the first call output is fed to the second one .So the tests are failing.

**Comment by harryi3t** [comment]
Hi @kthulsidoss 
Could you share your collection (either the link or the `Run in Postman` button) with us so that we can take a look at it? Please remove any sensitive information before sharing

**Comment by kthulsidoss** [comment]
[request_order.zip](https://github.com/postmanlabs/postman-app-support/files/2431777/request_order.zip)

**Comment by kthulsidoss** [comment]
Hi @harryi3t  thx for speedy look , please see the attached zip file containing(GETMetaMarketDataUsedByISIN.postman_collection.json ,MFD_R9.postman_environment.json).
Tx
K.Thulsi Doss

**Comment by kthulsidoss** [comment]
Hi @harryi3t  please kindly note that pm.sendRequest itself is asynchronous so possibly the order is changed . There is mention of the same here https://community.getpostman.com/t/can-i-use-pm-sendrequest-to-send-requests-synchronously/225/3 @kamalaknn mentions the solution as 
pm.sendRequest(req1, function () {
  pm.sendRequest(req2, done);
});

not sure the above solution is workable ,did not find anywhere pm.sendRequest(req2,done) , i could be wrong though. Even so where is the response object obtained for that request ?.

There is mention by @kamalaknn  quote "We’ve been working on something that might help with that. We are introducing scripts and auth at collection/folder level. It is available for early access on our Canary channel 36(for linux and mac, coming out on windows soon)." may be this can help.

Please send your speedier response.
Tx
K.Thulsi Doss

**Comment by harryi3t** [comment]
Hi @kthulsidoss,

We looked at the attached zip file. You are right, since `pm.sendRequest` is asynchronous, there is no guarantee in which order they run. 
Having said that, I think the [Postman community](http://community.getpostman.com) would be a better place for this discussion.

**Comment by numaanashraf** [comment]
@kthulsidoss As mentioned by @kamalaknn, `pm.sendRequest` is an asynchronous operation and you need to make the second request in the callback of the first one. This is the standard way to serially call two callback-based async operations in JavaScript.

```
pm.sendRequest(firstRequest, function (err, firstResponse)  {
  // add your extra logic here
  pm.sendRequest(secondRequest, function (err, secondResponse)  {
    // add your extra logic here
  });
});
```
