### ISSUE TITLE
Collection variables autocomplete in edit collection and edit folder modals

### ISSUE THREAD

**Issue by numaanashraf** [a85/POSTMan-Chrome-Extension#5283]
**Describe the bug**
Collection variables do not show up while autocomplete auth fields in edit collection and edit folder modals

**Screenshots**
<img width="803" alt="screenshot 2018-10-01 at 5 26 41 pm" src="https://user-images.githubusercontent.com/3295568/46287198-5e750780-c59f-11e8-9318-b73df4646183.png">
<img width="802" alt="screenshot 2018-10-01 at 5 26 48 pm" src="https://user-images.githubusercontent.com/3295568/46287204-60d76180-c59f-11e8-8409-2bcaae744889.png">

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version: 6.3.0
 - OS: macOS Mojave 10.14

**Comment by ghost** [comment]
I think I'm having a similar issue but just to be sure: can you still use these variables even if they don't show up in autocomplete?

**Comment by numaanashraf** [comment]
@Bibz87-CG Yes you can. They are just not shown in the UI auto-complete.

**Comment by ghost** [comment]
Indeed, I just tried and it does work.

That means #5730 is a different issue, then.

Thanks!

**Comment by numaanashraf** [comment]
Fixed in Postman v7.0
