### ISSUE TITLE
Cannot create a new request in a team workspace collection

### ISSUE THREAD

**Issue by davidmpaz** [a85/POSTMan-Chrome-Extension#5284]
Hello,
I have read through docs and search on issues looking for how to solve this or find some hints that could help me with no success. So sorry if it is duplicated or lack of knowledge when using Postman app.

**Describe the bug**
During a team trial we created a collection and shared it to work. Our team is composed of two person. After limits exceed we upgrade out the team to paid one. Nor before or after the upgrade am I able to add and/or save requests to the shared collection created by my colleague.

**To Reproduce**
1. Create a new team (in trial mode e.g. free). Only one member so far.
2. Create a collection and share with an existent user.
2. Add/Invite an existing member to the team.
3. Invited member to team try to add/edit/save new requests to collection. No success doing it.

**Expected behavior**
It is expected that members of team are able to collaborate in shared collections.

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version : Version 6.3.0
 - OS: linux 4.15.0-34-generic / x64

Thanks for the postmann project and for your time in advance,
David

**Comment by numaanashraf** [comment]
@davidmpaz Are you receiving any errors while you try to change the request in the collection? This might be caused due to lack of edit permissions on the collection.

**Comment by davidmpaz** [comment]
Hi @numaanashraf thanks for answering!

I will check this and report back.

Cheers

**Comment by davidmpaz** [comment]
Confirmed. It was on our end, permissions problems as you described.

Please apologize me for taking time from you for this.

Thanks!!

**Comment by numaanashraf** [comment]
@davidmpaz Glad to know this is resolved at your end. 😃 I've passed along the feedback to the team and we'll make it clear in the UI when a particular action (like creating request) is not allowed due to permission issues.

/cc @vkaegis
