### ISSUE TITLE
Add timestamp/created-at when returning collection information from API

### ISSUE THREAD

**Issue by chrisdeso** [a85/POSTMan-Chrome-Extension#5287]
**Is your feature request related to a problem? Please describe.**
I'd love to see a date/time value when retrieving a collection via the [Postman API](https://api.getpostman.com). This would help in ensuring that I'm working with the intended collection in the event that I have collections with the same name.

**Describe the solution you'd like**
`createdAt: "2018-08-06T14:37:20Z"`

**Comment by lawrencehook** [comment]
In a similar vein, it'd be great if there were a timestamp in the Postman Runner results.

-----

Possibly next to the iteration counter?

![image](https://user-images.githubusercontent.com/6572030/62141961-77cc0a80-b2bb-11e9-8d0d-181a99a0b25a.png)

**Comment by davidespihernandez** [comment]
Now the GET collection detail allows a [model=minimal](https://www.postman.com/postman/workspace/postman-public-workspace/example/12959542-99426ead-ae67-432f-a39b-654236af296a) query parameter that returns the basic information of the collection (no requests, responses...), including the `createdAt` field.
This can be useful if your collection is big and you don't need all the information, only the IDs, to operate with them [individually](https://www.postman.com/postman/workspace/postman-public-workspace/folder/12959542-efeda219-66e1-474c-a83b-253d15723bf7).
Notice that the [list of collections](https://www.postman.com/postman/workspace/postman-public-workspace/example/12959542-b739a07a-1c07-42dd-9992-db5cfe229847) endpoint returns the createdAt field too.
