### ISSUE TITLE
"Hide Sidebar" should be persisted across restarts.

### ISSUE THREAD

**Issue by ravshansbox** [a85/POSTMan-Chrome-Extension#5289]
**Describe the bug**
"Hide Sidebar" should be persisted across restarts.

**To Reproduce**
1. Hide the sidebar
2. Restart the app

**Expected behavior**
Sidebar should be hidden.

**Comment by a85** [comment]
Not a setting that we are considering right now as the overhead of remembering the interface across multiple windows AND have settings around it is too much on the architecture.
