### ISSUE TITLE
API Documentation with nested variables

### ISSUE THREAD

**Issue by GarethJames86** [a85/POSTMan-Chrome-Extension#5291]
I've defined my environment like this

myBaseUrl = https://myurl.com/
myUrlPrefix = hello/
myRequestUrl = {{myBaseUrl}}{{myUrlPrefix}}

Then I make requests as follows

{{myRequestUrl}}howareyou to give https://myurl.com/hello/howareyou

I'm documenting my collection and when I don't use an environment it's fine.
I get {{myRequestUrl}}howareyou

However, when I use my environment I get {{myBaseUrl}}{{myUrlPrefix}}howareyou

It would be nice if the base values, in this case https://myurl.com/hello/ showed through.

**Comment by godfrzero** [comment]
Closing as this bug seems to have been resolved and I'm unable to recreate it. @GarethJames86 Feel free to re-open if this is still happening for you.
