### ISSUE TITLE
After GITHUB#4663 converting to curl still removes double slashes

### ISSUE THREAD

**Issue by tstw** [a85/POSTMan-Chrome-Extension#5293]
## App Details:

```
Postman for Mac
Version 6.3.0
OS X 16.7.0 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:
Only a bug because the default behavior is now different.
 2. Expected behaviour:
Same as default tab-based-send behavior

Create a new request like `GET wtfismyip.com//json`
Try it, see that it gives 404
Press the code button and try the cURL code in your terminal.
Be dazzled!

**Comment by abhijitkane** [comment]
@tstw 
Can you try this is Postman 7.2.1, with the 'Experimental Codegen Mode' flag enabled in Postman's global settings? We've introduced bug-fixes, support for two new languages (JS-Fetch and Powershell), and the ability to configure certain aspects of the generated snippet.

**Comment by taebox** [comment]
It appears that double slashes, and triple, etc... are preserved when using experimental codegen.

**Comment by tstw** [comment]
I tried it, and it appears fixed.

**Comment by abhijitkane** [comment]
@tstw Great - Thanks for the confirmation!
