### ISSUE TITLE
File references are not imported from cURL snippet

### ISSUE THREAD

**Issue by pkgajulapalli** [a85/POSTMan-Chrome-Extension#5299]
The following request is giving 400 error in postman but the same is working fine with curl copied from postman.

`curl -X POST \`
`  LOCALHOST_URL \`
`  -H 'Accept: */*' \`
`  -H 'Authorization: AUTH_TOKEN' \`
`  -H 'Connection: keep-alive' \`
`  -H 'Content-Type: multipart/form-data' \`
`  -H 'content-type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW' \`
`  -F file=@FILE_PATH`

**Comment by numaanashraf** [comment]
@pkgajulapalli Could you share a collection with the request you are trying to send?

**Comment by pkgajulapalli** [comment]
@numaanashraf Here is the [collection](https://www.getpostman.com/collections/5dbd9fd6916518019a95) with the request.

**Comment by numaanashraf** [comment]
@pkgajulapalli It looks like the form-data file is not setup correctly. Did you import this request from cURL or manually create via the Postman UI?

<img width="564" alt="screenshot 2019-01-09 at 6 48 01 pm" src="https://user-images.githubusercontent.com/3295568/50901789-3703c580-143f-11e9-9bef-e2227bb75463.png">

**Comment by pkgajulapalli** [comment]
Hi @numaanashraf, the problem is resolved after selecting the file through "select file option" as in the [screenshot](https://drive.google.com/open?id=0B3Ttr4V3TQI1T0tKX3Npc2FtQlVWVWVvbFotV3E0bEtqel9R).

**Comment by numaanashraf** [comment]
@pkgajulapalli Thanks for the confirmation. I've renamed this to reflect the root issue.

**Comment by DannyDainton** [comment]
Closing this as a fix was introduced in a later version. If you're still encountering these issues in the latest version of the platform, we can look to reopen this again.
