### ISSUE TITLE
order of the request issue is solved however this is not setting in the environment variables

### ISSUE THREAD

**Issue by kthulsidoss** [a85/POSTMan-Chrome-Extension#5300]
refer How to ensure order of the request using pm.sendRequest (#5298) . Now the order of request is solved how ever even though the log says the environment variables are being set , it value is not set while seeing using the 'eye' icon

<img width="960" alt="env_variables_notset" src="https://user-images.githubusercontent.com/42998906/46418521-91f39580-c749-11e8-94f2-b9c080a4f347.png">
<img width="960" alt="env_variables_notset" src="https://user-images.githubusercontent.com/42998906/46418556-a59efc00-c749-11e8-8b2e-88743a36fb63.png">

**Comment by kthulsidoss** [comment]
![setting_access_token](https://user-images.githubusercontent.com/42998906/46418784-17774580-c74a-11e8-8ccd-06b845f985be.JPG)

**Comment by numaanashraf** [comment]
@kthulsidoss Please understand that this is a public bug and feature-request tracker for the Postman product and is *not* a channel for support, Q&A, etc. This is detailed in the guidelines we have set for this issue tracker - https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues.

Based on the guidelines above, this question is best fit for our community channel - https://community.getpostman.com
