### ISSUE TITLE
Menu bar on Postman for Windows with Dark Mode

### ISSUE THREAD

**Issue by euivanw** [a85/POSTMan-Chrome-Extension#5302]
**Is your feature request related to a problem? Please describe.**
When I'm using Postman on my Windows 10 with the Dark interface and with Postman Dark Theme. I always see the menu bar, however, the menu bar is presented in white color. 

**Describe the solution you'd like**
My idea is to hide the menu bar for both light and dark themes, or, apply the theme color according to the theme that I've selected to the menu bar.

**Comment by mhadidg** [comment]
We have the same issue in Linux. Please add the option to toggle menu bar visibility in both Linux and Windows.

**Comment by jackalbyte** [comment]
It would be nice if you make a menu for Windows in the "windows" style. Like VSCode for example. ![VSCode](https://user-images.githubusercontent.com/22278399/52555630-55bcf980-2dfb-11e9-96aa-386455e64973.png)

**Comment by diegogsann** [comment]
#5294

**Comment by RikkiMasters** [comment]
+1

**Comment by samuelaguiar** [comment]
+1

**Comment by martinszeltins** [comment]
I am also looking for a way to hide the menubar (maybe with alt key?)

**Comment by ppfm** [comment]
+1

**Comment by Kozaar89** [comment]
+1

**Comment by kallangerard** [comment]
Any update on this?

**Comment by aizhimou** [comment]
> Any update on this?

No

**Comment by metacryst** [comment]
> > Any update on this?
> 
> No

actually yes! the test version has it:
https://www.getpostman.com/downloads/canary

i got it and it's exactly the same as the normal version as far as i can tell. except now it has a dark menu bar.

**Comment by aizhimou** [comment]
> > > Any update on this?
> > 
> > 
> > No
> 
> actually yes! the test version has it:
> https://www.getpostman.com/downloads/canary
> 
> i got it and it's exactly the same as the normal version as far as i can tell. except now it has a dark menu bar.

Got it ! Thanks :D

**Comment by martinszeltins** [comment]
> > > Any update on this?
> > 
> > 
> > No
> 
> actually yes! the test version has it:
> https://www.getpostman.com/downloads/canary
> 
> i got it and it's exactly the same as the normal version as far as i can tell. except now it has a dark menu bar.

Awesome! Been waiting for this for a long time.

**Comment by numaanashraf** [comment]
@martinszeltins This is available on our early access canary channel now - https://www.getpostman.com/downloads/canary and should starting out to stable soon

**Comment by manuelwaldner** [comment]
I still got problems with it. The menu bar itself is now dark, but the window bar is still white, even though windows 10 (Version 2004) is set to dark mode. As you can see on the picture, on the left there is Canary, on the right the stable version and in the mit bottom there is the Windows Explorer in dark mode.

![image](https://user-images.githubusercontent.com/43695452/83324141-6d73f780-a263-11ea-9b9b-972273be1f39.png)

**Comment by JulianChow94** [comment]
> I still got problems with it. The menu bar itself is now dark, but the window bar is still white, even though windows 10 (Version 2004) is set to dark mode. As you can see on the picture, on the left there is Canary, on the right the stable version and in the mit bottom there is the Windows Explorer in dark mode.
> 
> ![image](https://user-images.githubusercontent.com/43695452/83324141-6d73f780-a263-11ea-9b9b-972273be1f39.png)

@manuelwaldner looks like thats just a problem with your Windows OS Color config as I am unable to reproduce on 2004 with Windows dark mode.

![image](https://user-images.githubusercontent.com/5642774/83439899-fa5cb380-a411-11ea-9bbc-7fff31a22cbb.png)

**Comment by cosimochellini** [comment]
> > I still got problems with it. The menu bar itself is now dark, but the window bar is still white, even though windows 10 (Version 2004) is set to dark mode. As you can see on the picture, on the left there is Canary, on the right the stable version and in the mit bottom there is the Windows Explorer in dark mode.
> > ![image](https://user-images.githubusercontent.com/43695452/83324141-6d73f780-a263-11ea-9b9b-972273be1f39.png)
> 
> @manuelwaldner looks like thats just a problem with your Windows OS Color config as I am unable to reproduce on 2004 with Windows dark mode.
> 
> ![image](https://user-images.githubusercontent.com/5642774/83439899-fa5cb380-a411-11ea-9bbc-7fff31a22cbb.png)

same in 1909
![image](https://user-images.githubusercontent.com/24718181/83629977-57d03c00-a59b-11ea-8ae8-82ed3d1f863c.png)

**Comment by manuelwaldner** [comment]
I fixed that, but it's only the case if i use the accent-color on the title and menu bars and also set the following registry item

[HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\DWM]
"AccentColorInactive"=dword:01010100

This registry-key is making the bars black, if not focused, if focused, the color is the accent color which in my case is orange.

**Comment by arlemi** [comment]
Seeing the same as @manuelwaldner on Windows 10 Pro N, version 1903. 

![image](https://user-images.githubusercontent.com/5029719/83746488-0eddbd80-a657-11ea-96a8-e659f6c810e6.png)

Playing around with accent-colors could possibly fix it but I would expect dark mode to default to black for the title bar.

**Comment by rawvoid** [comment]
Why can't the title bar be the same as vscode? Postman is too ugly.

**Comment by prasob-crestron** [comment]
Any update? 

Though it looks like very small *feature its kind of prominent.
When working with all dark themes, switching to postman for testing is like horrible - (I'm blinded by the lights....!)

**Comment by rawvoid** [comment]
Like vscode, the menu bar and window title bar are integrated. I think it's perfect.

**Comment by davidc555** [comment]
So it looks like some time last year this was fixed, but the menu/title bar is now back to showing white in Windows 10 while using the dark theme.  Can you please fix this?  It makes Postman look a bit bright and ugly.  Thanks

**Comment by Artur2** [comment]
@prasob-cs I think they wrote postman on some sh*tty javascript framework which not supports fast migration to support that little thing

**Comment by martinszeltins** [comment]
Still not possible to hide the menu bar

**Comment by Artur2** [comment]
@martinszeltins Just use Nightingale, if you use Windows, it's faster than Postman and doesn't eat so much memory
Good alternative for Electron's sh*t
https://github.com/jenius-apps/nightingale-rest-api-client

**Comment by cosimochellini** [comment]
@Artur2 completely agree, I have been using it for months now and I am very happy with it!

**Comment by 06MasonG** [comment]
@Artur2 just downloaded 😁 pretty UI's make the world a better place 🕊

**Comment by martinszeltins** [comment]
> @martinszeltins Just use Nightingale, if you use Windows, it's faster than Postman and doesn't eat so much memory
> Good alternative for Electron's sh*t
> https://github.com/jenius-apps/nightingale-rest-api-client

@Artur2 Nightingale seems to work only on Windows but I'm using Linux.

**Comment by mehmet-erdogdu** [comment]
![image](https://user-images.githubusercontent.com/44897996/138320489-3f22be05-570c-4653-a108-27a23f417f76.png)
Windows 11

**Comment by calvo-jp** [comment]
> > @martinszeltins Just use Nightingale, if you use Windows, it's faster than Postman and doesn't eat so much memory
> > Good alternative for Electron's sh*t
> > https://github.com/jenius-apps/nightingale-rest-api-client
> 
> @Artur2 Nightingale seems to work only on Windows but I'm using Linux.

Hi, sir. Were you able to find a fix for this in linux? I am on Ubuntu 21.10. I really like postman especially now that they support websockets.  I always set everything to be dark as possible especially for my primary tools.

**Comment by clicktodev** [comment]
Any news on this feature request?
A workaround is to enable fullscreen mode using F11.

**Comment by rawvoid** [comment]
@hichemfantar  I want to know either.

**Comment by natemardini** [comment]
Yeah not sure why this is still an issue, makes Postman look ugly with the menu bar on Windows 11. Switching over to Nightingale until this is fixed.

**Comment by WilliamABradley** [comment]
This is achievable by manually applying `DWMWA_USE_IMMERSIVE_DARK_MODE` on the Window, it was originally used to make File Explorer's Titlebar dark, but is used all over, e.g. DBeaver and Windows Terminal use it: https://stackoverflow.com/a/62811758/5001796

**Comment by HasanAlyazidi** [comment]
Thank you all for the new title bar on the dark mode

**Comment by arlemi** [comment]
@HasanAlyazidi You beat us to it! 

For everyone else in the thread, with the latest version of Postman (9.25.0) the toolbar is now integrated in the app which means it now adheres to the theme you have selected. Update and embrace the darkness! 🕶️ 

![image](https://user-images.githubusercontent.com/5029719/179939489-a6cf8a3f-6ecc-4de5-a94d-d6a4938b1013.png)

**Comment by Iftakharpy** [comment]
I have installed version 9.25 through snap and still can't hide the title bar. I am using pop os.

**Comment by jviotti** [comment]
As @HasanAlyazidi and @arlemi pointed out, this is issue has been fixed given the new toolbar design, so I'll proceed to close it.

@Iftakharpy Can you open another issue tracking this problem for Linux?

**Comment by jvincent-siplay** [comment]
Is there a way to disable this new combined menu/title bar and show the native Windows title bar?  This new design provides no indication whether the window is active or inactive which is harmful for accessibility.

**Comment by planetabhi** [comment]
@jvincent-siplay I’m afraid we don’t have plans to add a switch between the new combined and window native title and menu bar. However, we’re actively working on UI considerations for windows which covers the dim state for the inactive window and a few more features. I will keep you updated.
