### ISSUE TITLE
How to use collection with Postman API to test file uploads?

### ISSUE THREAD

**Issue by vdespa** [a85/POSTMan-Chrome-Extension#5305]
Please read through the [guidelines](https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues) before creating a new issue.

**Describe the bug**
I have a collection with a request which is uploading a file. Locally, I can edit the collection, specify the src property to be a local file and run it with Newman.

How to use the same collection but by using Postman API and specifying a file or a variable placeholder?

**Comment by a85** [comment]
Related to #4320

**Comment by saswatds** [comment]
Hi @vdespa, in the postman app version `>=7.1.0` we introduced the concept of `Working Directory` more on that I have mentioned in these comments
* https://github.com/postmanlabs/postman-app-support/issues/4320#issuecomment-490749103
* https://github.com/postmanlabs/postman-app-support/issues/4320#issuecomment-494937207

You should now be able to store relative paths with respect to your working directory and use the same with newman and postman app. 

I will be closing the issue for now. Feel free to re-open this issue if you do not find the working directory solution adequate.
 
Thanks
