### ISSUE TITLE
console.log(1==2) would not print false in postman test script

### ISSUE THREAD

**Issue by dhirajmobikwik** [a85/POSTMan-Chrome-Extension#5306]
Please read through the [guidelines](https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues) before creating a new issue.

**Describe the bug**
Console.log() doesn't work for the false response

**To Reproduce**
1. Go to postman script
2. Write 'console.log(1==2)'
3. Run Test

**Expected behavior**
false

**App information (please complete the following information):**
 - Native
 - Version 6.3.0
 - Linux

**Additional context**

**Comment by numaanashraf** [comment]
Fixed in Postman v7.0
