### ISSUE TITLE
Timeout in every request

### ISSUE THREAD

**Issue by gustinoco** [a85/POSTMan-Chrome-Extension#5307]
**Describe the bug**
In every request in certain API, the timeout appears every time. This comportment appears after update new version (6.4.0)

**To Reproduce**
1. Create new request or exists 
2. Click Send
3. Waiting for eternity

**Screenshots**
![screen shot 2018-10-04 at 13 48 06](https://user-images.githubusercontent.com/8768842/46492661-33c3c280-c7dc-11e8-88c7-4f4d32f416c4.png)

**App information (please complete the following information):**
 - Postman Version [e.g. 6.4.0]
 - OS: [e.g. macOS High Sierra 10.13.6]

**Comment by kamalaknn** [comment]
Hey @gustinoco 

Can you give use more information to help us identify the issue? Do you see any errors in the Postman Console (`View -> Show Postman Console`) or DevTools (`View -> Developer -> Show DevTools(current view)`)? 

Can you verify the timeout settings in the `Settings` screen? You can go to it by clicking on the gear icon on the top right.

**Comment by gustinoco** [comment]
I'm resolve this issue.
Clean all cookies above button Send.
This problem is solved, this problem happened on three computers at same Version Postmand and Os.
Remember, this problem issue after updated Postman. 
In older version, these requests are ok, normally.
