### ISSUE TITLE
Generate valid curl command on Windows

### ISSUE THREAD

**Issue by phiferd** [a85/POSTMan-Chrome-Extension#5308]
**Is your feature request related to a problem? Please describe.**
When generating curl requests, the app uses single quotes and "\\" as the line continuation character.  This doesn't work for windows.

**Describe the solution you'd like**
A new option for generating Windows friendly curl commands.  Code generated should use double- quotes and "^" for the line continuation character.  (I don't think either is specific to cUrl).

```
curl -X GET ^
"https://google.com?q=test" ^
-H "Cache-Control: no-cache"
```

**Describe alternatives you've considered**
Manually edit each generated curl command with suggested changes.  :/

**Additional context**
There may be other differences that need to be considered.  These are just the two I noticed.  This sort of correction probably applies to any generated command-line commands.

**Comment by abhijitkane** [comment]
@phiferd 
Can you try this is Postman 7.2.1, with the 'Experimental Codegen Mode' flag enabled in Postman's global settings? We've introduced bug-fixes, support for two new languages (JS-Fetch and Powershell), and the ability to configure certain aspects of the generated snippet.

For cURL, you can switch between `\` and `^` as line-continuation characters.

**Comment by WouterVanNifterick** [comment]
This almost works under windows. 
The only issue that I found was that the % character was not escaped to %%.
