### ISSUE TITLE
HTTP Method Shown In Tab Header With No Way to Disable

### ISSUE THREAD

**Issue by txdmatthias** [a85/POSTMan-Chrome-Extension#5310]
**Describe the bug**
The HTTP method of the request is now shown on in the tab header

**Expected behavior**
It should be configurable whether or not to show the HTTP request. I would have this as a feature request but to me, this has slightly worsened my workflow as the HTTP method takes up space in the tab header area meaning the name of the tab which is more important is now obscured meaning that in some situations you have to click on the tab to see its full name.

**App information:**
Version 6.4.0

**Additional context**
While I know some need this to appear because they are seemingly blind to the gigantic dropdown on the top left which already shows the HTTP method, for those who do not need this there does not seems to be a way to disable this in the options.

I would have thought this would be a configurable setting? It's seems a bit weird to force this when it takes away space in the tab for the actual custom name of the request you're making.

**Comment by vkaegis** [comment]
@txdmatthias Thanks for writing in! We're working on some improvements on the tab size itself, so that might alleviate some of your problems. 

I'm marking this as a feature request for the configuration. Stay tuned for updates!

**Comment by chforsb** [comment]
+1

**Comment by GeoKnR** [comment]
+1

**Comment by sujayvenaik** [comment]
Hey @AppChris @txdmatthias 

We have addressed this and added a configuration using which you can enable/disable tab icons.
This can be found under the UI Section of Settings.

**Comment by chforsb** [comment]
Nice, I just updated, and now I will save a lot of time on not having to randomly tap on taps to get the one I want!

 

Best Regards,

Chris
