### ISSUE TITLE
Multi language documentation

### ISSUE THREAD

**Issue by felipeplets** [a85/POSTMan-Chrome-Extension#5311]
Hey guys, 

I have customers world wide and some are not so used to English. Mainly Spanish and Portuguese customers and I would like to have a native multi language support for documentation. 

Also another solution would be some integrations like with [localizejs.com](localizejs.com) or similar tools.

**Comment by VictorHOliveira** [comment]
Yeah, I'm from Brazil and here we use Postman a lot, and o feel miss about the translate and more support in portuguese. Can I help with this?

**Comment by arlemi** [comment]
Closing this issue since this is a duplicate of the following in the postman-docs repository: 
https://github.com/postmanlabs/postman-docs/issues/2057

We'll update on the advancement there.
