### ISSUE TITLE
Generated jQuery Ajax Code for multipart form / file upload

### ISSUE THREAD

**Issue by science695** [a85/POSTMan-Chrome-Extension#5312]
I have a request with a multipart file upload (a file upload, and a metadata field with some json).

If you click on Code -> JavaScript Jquery AJAX to get a code sample, it shows some extra headers that will break the process:

```
var form = new FormData();
form.append("file", "/path/to/uploaded/file.pdf");
form.append("metadata", "[1,3,8,20]");

var settings = {
  "async": true,
  "crossDomain": true,
  "url": "https://api.about.com/upload",
  "method": "POST",
  "headers": {
    "Accept": "application/json",
    "Content-Type": "application/x-www-form-urlencoded",
    "Cache-Control": "no-cache",
    "Postman-Token": "random-postman-token"
  },
  "processData": false,
  "contentType": false,
  "mimeType": "multipart/form-data",
  "data": form
}

$.ajax(settings).done(function (response) {
  console.log(response);
});
```

Inside the headers object, it is setting the Content Type to "application/x-www-form-urlencoded" even though mimeType below is multipart/form-data. My tests working with jQuery on this matter indicate that the settings.headers["Content-Type"] should not be set, that the settings.contentType = false is sufficient.

This is confirmed on several OS/versions of the Native App:
- 6.3 on macOS 10.13.5
- 6.2.4 on linux 4.15.0-22-generic / x64

**Comment by VShingala** [comment]
@science695 
This issue is solved in latest update. Can you check it once again and confirm?

I have followed same procedure mentioned in your issue and this is code generated in JQuery.

```
var form = new FormData();
form.append("file", "path_to_file/Screenshot_6.jpg");
form.append("json", "[1,3,8,20]");

var settings = {
  "async": true,
  "crossDomain": true,
  "url": "https://postman-echo.com/post",
  "method": "POST",
  "headers": {
    "User-Agent": "PostmanRuntime/7.11.0",
    "Accept": "*/*",
    "Cache-Control": "no-cache",
    "Postman-Token": "68b5bae4-544a-4319-9336-e1bacbb8c491,936f02a3-6b15-4620-8fca-6a32a8877d50",
    "Host": "postman-echo.com",
    "cookie": "sails.sid=s%3AUA16JmsV1YbnJsbCwBSlVgIhNYJs82VQ.p7D4Bfe%2BYGUxSb3%2Foknx8BVpmqQjDur8q4PAov3UZKM",
    "accept-encoding": "gzip, deflate",
    "content-length": "11195",
    "Connection": "keep-alive",
    "cache-control": "no-cache"
  },
  "processData": false,
  "contentType": false,
  "mimeType": "multipart/form-data",
  "data": form
}

$.ajax(settings).done(function (response) {
  console.log(response);
});
```
Confirmed on Native App:
7.0.9 on win32 10.0.17763 / x64

**Comment by science695** [comment]
Thank you, I can confirm the generated code looks better.
