### ISSUE TITLE
URLs/Resource names are not shown on import

### ISSUE THREAD

**Issue by misha-kotov** [a85/POSTMan-Chrome-Extension#5315]
Please read through the [guidelines](https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues) before creating a new issue.

**Describe the bug**
When importing a collection, the urls are not shown in the collection navigator pane. 
It works in the Chrome app version of Postman, but not the native desktop client on OS X. 

**To Reproduce**
1. Import the attached file. 
[api schema.json.zip](https://github.com/postmanlabs/postman-app-support/files/2451333/api.schema.json.zip)

**Expected behavior**
![image](https://user-images.githubusercontent.com/18131925/46548830-c96f5880-c895-11e8-8b44-f2dc45c4e27f.png)

**Actual benavior**
![image](https://user-images.githubusercontent.com/18131925/46548850-d2f8c080-c895-11e8-9aef-23031e61f8cd.png)

**Screenshots**

**App information:**
 - Native App (it works in Chrome app)
 - Postman Version: 6.3.0
 - OS: macOS High Sierra 10.13.6

**Additional context**

**Comment by abhijitkane** [comment]
@misha-kotov I'm able to import this with the operationId showing up as request names in Postman 7.2+.
