### ISSUE TITLE
In collection runner, selecting "Persist Variables" causes pm.environment.set to change initial(environment) values, leaving it unselected changes current(session) values 

### ISSUE THREAD

**Issue by ghost** [a85/POSTMan-Chrome-Extension#5317]
Please read through the [guidelines](https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues) before creating a new issue.
In collection runner, selecting "Persist Variables" causes pm.environment.set to change initial(environment) values, leaving it unselected changes current(session) values 

Runner is persisted, look at "locationList" as its values change to Robert.

https://user-images.githubusercontent.com/5994259/46555436-279d3b00-c898-11e8-911e-53d5d3b3b41f.png

https://files.slack.com/files-pri/T02G7V5JE-FD7HJBCAX/screen_shot_2018-10-04_at_3.20.43_pm.png

Unpersisted: 

https://files.slack.com/files-pri/T02G7V5JE-FD72ZA40H/screen_shot_2018-10-04_at_3.45.07_pm.png

When persisted the runner should instead only update session values.

**Comment by harryi3t** [comment]
You can turn off the setting `Auto persist variable values` which applies globally to the app (even to Runner as well)

You can find the relevant [docs here ](https://www.getpostman.com/docs/v6/postman/collection_runs/using_environments_in_collection_runs)
