### ISSUE TITLE
"Learn about tests" link directs to unreachable page

### ISSUE THREAD

**Issue by Postman-Gabriel** [a85/POSTMan-Chrome-Extension#5319]
**Describe the bug**
When clicking on the "learn about tests" link in the native postman app, it directs you to a unreachable page.

**To Reproduce**
1. Go to test page on any request
2. Click on 'learn about tests'
3. See error

**Expected behavior**
Expected to see a full page

**Screenshots**
![image](https://user-images.githubusercontent.com/40899145/46573927-e37a6b00-c969-11e8-834d-600ee26b7ec2.png)
![image](https://user-images.githubusercontent.com/40899145/46573928-e70df200-c969-11e8-9670-d8c884f86069.png)

**App information (please complete the following information):**
 - App Type Native App
 - Postman Version 6.3.0
 - OS: Windows 7

**Comment by numaanashraf** [comment]
Unable to replicate this issue. Page correctly redirected to https://www.getpostman.com/docs/v6/postman/scripts/test_scripts.

**Comment by numaanashraf** [comment]
@Postman-Gabriel Please share the browser version the link had opened in. Is this issue still happening?

**Comment by abhijitkane** [comment]
@numaanashraf https://go.pstmn.io/docs-tests-scripts is giving a 404. @Postman-Gabriel The latest version of the app doesn't have a test-docs link as indicated in the screenshot.

**Comment by numaanashraf** [comment]
Fixed in Postman v7.0
