### ISSUE TITLE
Capturing API requests, target collection shows wrong requests counts.

### ISSUE THREAD

**Issue by mechbullgt** [a85/POSTMan-Chrome-Extension#5320]
I'm trying to capture API requests but the target collection shows requests count for even an empty collection.

Please find below screenshot for the same.
![emptycollection_shows_count](https://user-images.githubusercontent.com/23336355/46585112-203d8380-ca8a-11e8-9c9b-a69290ec8d3e.png)

**Comment by numaanashraf** [comment]
@mechbullgt That's odd. Do you remember the steps you took to cause this? It'll help us triage this issue faster.

**Comment by numaanashraf** [comment]
Thank you for your issue! With only the details that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have more information that'll help us reproduce this.
