### ISSUE TITLE
Postman show the previous response 

### ISSUE THREAD

**Issue by Yarandi** [a85/POSTMan-Chrome-Extension#5321]
Hi, 
I have installed postman app on ubuntu 18.4,
I have a problem with response , After change the code in Phpstorm IDE  the  response dose not change, 
I have cleared storage cache in Devtools but the issue still exist , 
How can i solve this?

**Comment by numaanashraf** [comment]
@Yarandi Could you check the response Postman received from your server in the Postman Console - https://learning.getpostman.com/docs/postman/sending_api_requests/debugging_and_logs/#network-calls-with-postman-console.

**Comment by Yarandi** [comment]
@numaanashraf 
Postman Console is empty. 

Sometimes my response return but many times dose not return and show previous result,
And i have found that it will return updated response after about 5 minutes changing my code!!!

**Comment by numaanashraf** [comment]
@Yarandi That is odd. Could you attach a screenshot of the Postman Console? Also, it'll help if you could try the request with cURL and verify the server is returning the right response.

**Comment by Yarandi** [comment]
Now I have an error in console 
![screenshot from 2018-10-08 11-03-56](https://user-images.githubusercontent.com/1158575/46596589-003dac80-caea-11e8-9138-b5e8aa304060.png)

**Comment by Yarandi** [comment]
Also after reserve my project on Artisan console (laravel framework console) the response update, 
is it possible this problem is about my backend?

**Comment by numaanashraf** [comment]
@Yarandi There is a possibility that this might be an issue with the backend.

**Comment by numaanashraf** [comment]
@Yarandi It seems like you had provided the DevTools screenshot. Could you open the Postman Console and send us a screenshot of the responses there?

"How to open Postman Console"
Head to View in the application menu, and click on "Show Postman Console" or use the keyboard shortcut (CMD/CTRL + ALT + C). Similar to DevTools, every call along with its headers and payloads will be logged to the Postman Console.

**Comment by harryi3t** [comment]
@Yarandi 
Which version of Postman are you using?

**Comment by Yarandi** [comment]
@numaanashraf 
![screenshot from 2018-10-08 11-24-37](https://user-images.githubusercontent.com/1158575/46597391-c7eb9d80-caec-11e8-8deb-92a4a5beced6.png)

**Comment by Yarandi** [comment]
> @Yarandi
> Which version of Postman are you using?

6.3.0

**Comment by numaanashraf** [comment]
@Yarandi Please verify from the console if the response Postman received is the one you expected. If the responses are the same, then it might be an issue on the backend.

**Comment by Yarandi** [comment]
@numaanashraf unfortunately not, 
I expected this response : 
![screenshot from 2018-10-08 11-53-41](https://user-images.githubusercontent.com/1158575/46598483-1c911780-caf1-11e8-97e8-c1d45589bcac.png)

but Postman receive this in console : 

![screenshot from 2018-10-08 11-53-10](https://user-images.githubusercontent.com/1158575/46598503-2e72ba80-caf1-11e8-94a4-0c226e40d6a7.png)

**Comment by harryi3t** [comment]
@Yarandi As @numaanashraf has mentioned, it looks like an issue with your backend. Is the response that you see in Postman console is not the one that you expect, that means that the backend server is not sending the intended response.
You can verify this by generating a cURL request and then running on your terminal. If the response still is not that you expect, please contact your backend team responsible for the API.

**Comment by harryi3t** [comment]
@Yarandi As @numaanashraf has mentioned, it looks like an issue with your backend. If the response that you see in Postman console is not the one that you expect, that means that the backend server is not sending the expected response.
You can verify this by generating a cURL request and then running on your terminal. If the response still is not that you expect, please contact your backend team responsible for the API.

On the other hand, if the response you get using cURL is what you expect, then there might be some issue with Postman. Could you try this out and let us know if that works?

PS: you can generate the `cURL` code by clicking `Code` below the save button as shown in the screenshot
![postman](https://user-images.githubusercontent.com/5207331/46599625-6edc3380-cb05-11e8-8843-db63aa8d5e24.png)

**Comment by Yarandi** [comment]
@numaanashraf  and @harryi3t  I checked with curl and the result is not that i expect, as you mentioned this is probably caused by backend and framework,

**Comment by numaanashraf** [comment]
@Yarandi We are closing this issue as it does not seem to be related to Postman.

**Comment by Yarandi** [comment]
@numaanashraf  and @harryi3t 

Yes You Are Right , I found the problem , 
The issue is about php. I have enabled opcache in php 7.2 recently and I did not think it will cause this problem and after disable it problem solved.

So , Thank you for your good supports

**Comment by harryi3t** [comment]
@Yarandi Thanks for the quick clarification. 
Closing this ticket
