### ISSUE TITLE
Cookies not saving 6.3.0 Mac OS

### ISSUE THREAD

**Issue by dan-cooke** [a85/POSTMan-Chrome-Extension#5323]
**To Reproduce**
1. Open Postman
2. Create a request
3. Click the 'Cookies' button
4. Add a domain
5. Add a cookie to the domain
6. Add a new property to the cookie , e.g `AJAXTimeoutLimit=5;`
7. Click **Save**.
8. Open the Cookies modal again.

**Expected behavior**
New property of cookie `AJAXTimeoutLimit=5` should be visible in the text box, where it was entered.

**Actual Behvariour** 
Only **the default cookie properties** added by Postman are saved. This can be demonstrated more clearly by removing the default properties.

`Cookie_x=;` 
`path=/;` 
`domain=`;

Entering your own cookie, and pressing Save again.

This time when opening the Cookie modal, there isn't a cookie saved at all. i.e. no `Cookie_x` to click on.

**Screenshots**
Step 4, 5 and 6. Note the additional property added to the text box. After this I press Save.
<img width="693" alt="adding_property" src="https://user-images.githubusercontent.com/22816887/46610127-bd87ce80-cb01-11e8-9e39-62c04f6ef1ad.png">

The result of opening the Cookies modal after saving. Step 8. Note that only the pre-generated properties that Postman adds are saved to the cookie.
<img width="703" alt="result_of_save" src="https://user-images.githubusercontent.com/22816887/46610129-be206500-cb01-11e8-8559-7b8f5daa5d41.png">

**App information (please complete the following information):**
 - App Type : Native
 - Postman Version : 6.3.0
 - OS: Mac High Sierra 10.13.6

**Comment by dan-cooke** [comment]
https://github.com/postmanlabs/postman-app-support/issues/4581#issuecomment-427267786

**Comment by pineapplemachine** [comment]
I am having a similar problem. I am testing a web application that provides a login endpoint (which creates a cookie) and endpoints which require authentication (i.e. that cookie).

I am running postman on OS X 10.9.5.

This old version of postman works as expected. The cookie is saved and authentication with the server is successful.

```text
Postman for Chrome
Version 5.5.3
OS X / x86-64
Chrome 67.0.3396.87
```

This current version of postman does not work.

```text
Postman for Mac
Version 6.4.4
OS X 13.4.0 / x64
```

The desktop app version _did_ work the last time I used it, some weeks ago, but now cookie behavior is broken.

**Comment by numaanashraf** [comment]
@pineapplemachine Could you give us more information regarding the problem? Are the cookies not saved to the app after the first login call? (you can check this via Manage Cookies dialog). Or the saved cookies are not sent in the subsequent call?

**Comment by pineapplemachine** [comment]
@numaanashraf Here is a series of screenshots as I go through the process.

Initial state: No cookies.

![image](https://user-images.githubusercontent.com/7266412/47482925-93901500-d840-11e8-92a3-e48582ee5c4c.png)

Login request is successful. A cookie comes back in the response.

![image](https://user-images.githubusercontent.com/7266412/47482963-b0c4e380-d840-11e8-904b-4c4730cef78d.png)

"Manage Cookies" window shows the new cookie.

![image](https://user-images.githubusercontent.com/7266412/47482996-c9cd9480-d840-11e8-80c3-1c873f4441ac.png)

Post a request to an API endpoint that requires the client to be authenticated. The request fails in the current version of Postman. Following the same steps, it's successful in my older Chrome app version. It was successful the last time I needed to test the API with the desktop version, too, though I can't tell you specifically which version that was.

![image](https://user-images.githubusercontent.com/7266412/47483036-e1a51880-d840-11e8-99b4-4bcb3f52d5e6.png)

**Comment by numaanashraf** [comment]
@danielcooke1996 The cookie string mentioned in the original report is invalid. If you need to add a `AJAXTimeoutLimit=5` cookie, then you need to change the `Cookie_5=value` to `AJAXTimeoutLimit=5`. Check the detailed comment at https://github.com/postmanlabs/postman-app-support/issues/4581#issuecomment-431665553

**Comment by numaanashraf** [comment]
@pineapplemachine We have closed this issue as the original issue is resolved. For your issue, could you try using 127.0.0.1 instead of localhost in the cookie domain?

**Comment by dan-cooke** [comment]
@pineapplemachine yes apologies. I realise that I was inputting the cookie in the incorrect format. Thanks for your help
