### ISSUE TITLE
Typo in save dialogue: "Save these changes to avoid _loosing_ your work."

### ISSUE THREAD

**Issue by JP-from-Postman** [a85/POSTMan-Chrome-Extension#5325]
1. Have open, unsaved tab
2. Try to close tab, save prompt appears
3. Dialogue text says "Save these changes to avoid _loosing_ your work."

Should be "losing".
![capture](https://user-images.githubusercontent.com/43283131/46626781-34669c80-caed-11e8-9205-f500c6eb469e.PNG)

**Comment by sujayvenaik** [comment]
Hey @JP-from-Postman 
We have fixed this and is available on the latest v6.4.4.
You can update the app.

Thanks for writing in and reporting this issue.
