### ISSUE TITLE
Allow opting out of script inheritance for specific requests

### ISSUE THREAD

**Issue by deepakpathania-zz** [a85/POSTMan-Chrome-Extension#5328]
Currently, if you specify a collection or folder level pre-request or test script, it gets executed for each request in that entity. Authorization is something that one can override at request level so that the top level authorization doesn't take effect but something like this is not possible for pre-request and test scripts.

Here is my use case to describe things better. 
- I have a collection with multiple folders each having around 10 requests. 
- I specify some tests at the folder level, say response code 200 checks, that I would like to be executed for each request. 
- I have certain requests say 1 out of 10, for which I don't want the 200 checks since they intentionally return some other response code.
- Tests fail because of the folder level tests.

At this point, I either have to copy the folder level test to each individual request for which it is valid and remove it from folder level(cumbersome) or move the request out of that folder (not correct since they belong together application wise).

Ideally, I would like an option to opt out of inheritance from folder/collection at request level for certain things, scripts in this case. 

Bonus points if I could still inherit from collection level and skip only folder level or the other way round, meaning I can specify the levels from which I want to opt out of.

**Comment by a85** [comment]
Closing this as there are other issues in the tracker where we talk about reusability and composition. Postman will support some inheritance constructs for specific objects but we typically lean towards composability as debugging inherited models becomes progressively harder.
