### ISSUE TITLE
Data-binary at a Example Request in Postman Collection V2

### ISSUE THREAD

**Issue by ash007-postman** [a85/POSTMan-Chrome-Extension#5330]
I documented my API that has a file on Body as a Binary. 
but, I noticed it lack information like a "--data-binary @abc.txt" in curl. 
I think it is incomplete as an Example Request.

can I display --data-binary in Example Request? 
does Postman Collection have an alternative way of writing? 
I would like to know this solution.

**Comment by aditrades** [comment]
We recently bought postman for showing docs and this is a really crucial feature for us.

**Comment by aviranmoz** [comment]
This feature will very helpful

**Comment by matanos5** [comment]
Hoping this feature will be added in the near future.. Very important!

**Comment by jonchui** [comment]
Any update on this @abhijitpostman or @ash007-postman  ?

**Comment by maheshmarkapuram** [comment]
I'm still facing the same issue , any update on this ?

**Comment by victor-bts** [comment]
+1 for this request. Sanity CMS requires this flag for their HTTP API.

**Comment by aman-v-singh** [comment]
Closing this issue as it is resolved.

**Comment by aditrades** [comment]
Thanks you for the blazing fast response

**Comment by victor-bts** [comment]
> Thanks you for the blazing fast response

Lolz
