### ISSUE TITLE
Get MD5 from raw image response

### ISSUE THREAD

**Issue by snake404** [a85/POSTMan-Chrome-Extension#5331]
Hi, I'm using postman version 6.4.2 in MacOS mojave 10.14, chrome version 69.0.3497.100.

I'm migrating my test from soapUI to postman and I have an script in groovy to get the MD5 of an image and then compares that md5 with another one but in postman I'm not getting the same MD5, I followed the answer from this issue https://github.com/postmanlabs/postman-app-support/issues/2024 but I'm still not getting the right MD5. This is my Test in postman:

```javascript
pm.test("Set image url", function () {
    var jsonData = JSON.parse(responseBody);
    var iUrl = pm.globals.get("myUrl");

    for(var i = 0; i < jsonData.images_array.length; i++){
        var image = jsonData.images_array[i];            
        var url = iUrl + "/" + image.url;

        pm.sendRequest(url, function(err, res){            
            var arr = res.stream;
            var str = String.fromCharCode.apply(String, arr);            
            var md5 = CryptoJS.MD5(str);
            console.log("md5 " + md5);
        });

    }

});
```

**To Reproduce**
I send a GET request to the image and I'm getting the bytes of that image, then with my script I'm trying to get the md5 of the image but when I calculate the MD5 with the terminal, I got a different MD5, I don't know if this can be achieved with postman or I'm doing something wrong.

I followed the answer of this issue https://github.com/postmanlabs/postman-app-support/issues/2024
And I asked the same thing in stackoverflow: https://stackoverflow.com/questions/52711680/get-md5-of-raw-image-in-postman-response

**Comment by numaanashraf** [comment]
We recommend reaching out to the wider Postman Community (https://community.getpostman.com/) for help with this issue.

Issue Guidelines: https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues
