### ISSUE TITLE
[Mac Native App] Stuck "preparing your workspaces...", username has .asar in it

### ISSUE THREAD

**Issue by murtaza-asar-cox** [a85/POSTMan-Chrome-Extension#5332]
**Describe the bug**
After entering a username/password, the mac postman native app is stuck "preparing your workspaces...". 

**To Reproduce**
I believe this is because of my username on this machine, ie. "murtaza.asar"
```
Failed to get data from storage Error: Invalid package /Users/murtaza.asar
    at invalidArchiveError (ELECTRON_ASAR.js:153:19)
    at Object.fs.readFile (ELECTRON_ASAR.js:477:16)
    at /Applications/Postman.app/Contents/Resources/app/node_modules/electron-json-storage/lib/storage.js:69:10
    at fn (/Applications/Postman.app/Contents/Resources/app/node_modules/async/lib/async.js:746:34)
```

**Expected behavior**
Succesful login.

**Screenshots**
<img width="401" alt="screen shot 2018-10-09 at 5 37 26 pm" src="https://user-images.githubusercontent.com/44007218/46700230-395d4600-cbea-11e8-95cb-20720a7e6bec.png">

**App information (please complete the following information):**
 - App Type [Native App]
 - Postman Version [many, same issue with 6.4.x, 6.3.x, 6.1.x]
 - OS: [macOS High Sierra 10.13.6, same issue with mojave (cant remember version)]

**Additional context**
I cannot change my username and dont have permissions to run from a different location/user
Any workaround for this?

**Comment by murtaza-asar-cox** [comment]
I can add full logs if needed

**Comment by SamvelRaja** [comment]
@murtaza-asar-cox  We can reproduce the issue you are facing.
We are using electron internally which is having the issue (https://github.com/electron/electron/issues/1658)
We will update the thread on the alternative way soon.

**Comment by jjsty1e** [comment]
what's going on with it?

**Comment by jjsty1e** [comment]
#8255

**Comment by harryi3t** [comment]
@murtaza-asar-cox @Jaggle 

We've pushed an update on our early access canary channel that should resolve this issue. Do try it out and let us know

You can get the canary app from https://www.getpostman.com/downloads/canary

**Comment by twitharshil** [comment]
Hi @murtaza-asar-cox @Jaggle 
Could you try out our early access Canary build? https://www.getpostman.com/downloads/canary. We are testing some improvements that should address this particular issue. 
You can install and use the Canary build side by side with the stable app. Do try and let us know

**Comment by twitharshil** [comment]
Hi @murtaza-asar-cox @Jaggle 
We’ve pushed the updates in our stable app v7.25.1 that should fix this issue 🎉. 
Feel free to reopen the issue if you are still facing this problem on Postman v7.25.1 onwards.
