### ISSUE TITLE
support multiple instances on Mac.

### ISSUE THREAD

**Issue by axemaster** [a85/POSTMan-Chrome-Extension#5333]
Request is to reveal the New Window button or to remove the block on mac's native multiple instance support.

I read the issue comment regarding multiple instances on Windows, and the answer was to use the New Window button in the upper left. However I am using the native postman app for Mac and there is no such button. Or at least I can't find it.  Please support multiple instance on Mac or point me on instructions on revealing the button.  I tried 'open -n -a postman' and that did not work. It seems the postman app as purposefully disabled multiple instances.

**Comment by harryi3t** [comment]
@axemaster That button is moved as an option in the `Open New` dropdown
![postman](https://user-images.githubusercontent.com/5207331/46724486-c14d5980-cc97-11e8-9142-a9603838b6cd.png)

You can use the `Postman Window` option or the keyboard shortcut `Cmd + Shift + N`

**Comment by axemaster** [comment]
Thanks for the info! But please do realize this is not intuitive.  So this request is to simplify the UI with a single New menu or to break out the new windows option capability  in a more obvious manner.

And do unblock the native multiple instance support in OSX.  I understand that Windows users can be confused by multiple instances but as mac natively limits to a single instance without explicitly being told to do otherwise, it's not appropriate as a default on the apple platform.

**Comment by axemaster** [comment]
closing with workaround. but do make this easier to find please.
