### ISSUE TITLE
Many versions of Postman after using it a while

### ISSUE THREAD

**Issue by waahhhh** [a85/POSTMan-Chrome-Extension#5334]
Please read through the [guidelines](https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues) before creating a new issue.

**Describe the bug**
It looks like Postman clones itself many times. Everytime Postman starts it download itself and extract the new version. After a while I got many versions of Postman.
In my settings (under Update) the option "Automatically download major updates
Disabled" is disabled.

**To Reproduce**
1. Start Postman
2. See Postman exists as "Postman-\<timestamp\>" & "Postman-\<timestamp\>.tar.gz"  
(in the parent directory of the executable of Postman.)

**Expected behavior**
Postman should not download a new version, because the option is disabled.
Postman should clear old versions or work with just one version.

**Screenshots**
#### a copy of Postman as Postman-1539163046075
![image](https://user-images.githubusercontent.com/40632052/46726452-ade1c480-cc7e-11e8-8113-d61965b2998c.png)
#### My Postman update setting
![image](https://user-images.githubusercontent.com/40632052/46726521-d49ffb00-cc7e-11e8-8223-1510b3cd921f.png)

**App information (please complete the following information):**
 - App Type: Native App (Postman for Linux)
 - Version 6.1.3
 - OS: linux 4.15.0-36-generic / x64

**Additional context**
```text
$ ./Postman/Postman
ORM initialization successful
App events bus { name: 'booted', namespace: 'shared' }
App updater event { name: 'checkForElectronVersionUpdated',
  namespace: 'appUpdate' }
App events bus { name: 'booted', namespace: 'requester' }
App updater event { data: 
   { additionalParamsString: 'installationId=3b40f323-756b-47cc-acf1-c6e50b73d964&userId=0&syncEnabled=false&teamPlan=',
     appId: '3b40f323-756b-47cc-acf1-c6e50b73d964',
     arch: '64',
     channel: 'prod',
     downloadURL: 'https://dl.pstmn.io/download/version/6.4.2/linux_64',
     platform: 'LINUX',
     updateServerDomain: 'https://dl.pstmn.io/',
     userAgent: 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Postman/6.1.3 Chrome/59.0.3071.115 Electron/1.8.4 Safari/537.36',
     userId: '0',
     version: '6.1.3' },
  name: 'updateElectron',
  namespace: 'appUpdate' }
Linux updateInfo received { additionalParamsString: 'installationId=3b40f323-756b-47cc-acf1-c6e50b73d964&userId=0&syncEnabled=false&teamPlan=',
  appId: '3b40f323-756b-47cc-acf1-c6e50b73d964',
  arch: '64',
  channel: 'prod',
  downloadURL: 'https://dl.pstmn.io/download/version/6.4.2/linux_64',
  platform: 'LINUX',
  updateServerDomain: 'https://dl.pstmn.io/',
  userAgent: 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Postman/6.1.3 Chrome/59.0.3071.115 Electron/1.8.4 Safari/537.36',
  userId: '0',
  version: '6.1.3' }
```

**Comment by SamvelRaja** [comment]
Tracking in #5034
