### ISSUE TITLE
Big response are not rendered in the GUI.

### ISSUE THREAD

**Issue by DiegoSuzuki** [a85/POSTMan-Chrome-Extension#5336]
Postman for Linux
Version 6.4.2
linux 4.15.0-36-generic / x64
Ubuntu 18.04 LTS

**Describe the bug**
Big response are not rendered in the GUI.

**To Reproduce**

1. With the console open, send a request to this end-point: GET 
http://wscert.ntk.com.br/api/Domicilio/99?key=M0ZouShPjUsoQXVdATaC6irUgIwJg%2flHuY7T%2bMJwfifuAWAgHN6D206pZjsl2RwuSen5QtB538mMJugh2cYf7g%3d%3d

2.  in the GUI that there is no response, but in the console the return occurred.

**Expected behavior**
Render the response body and HTTP status code

**Comment by sujayvenaik** [comment]
Hey @DiegodeOliveira 

I tried hitting the same URL you requested above and response rendered for me.
[![kapture 2018-10-10 at 19 13 02](https://user-images.githubusercontent.com/11532114/46740542-b8bd4900-ccc0-11e8-97dc-602f167881c3.gif)](url)

Can you try once again?
Also, if you still face the issue again can you send the logs from View -> Developer -> Show DevTools(Current VIew)

**Comment by DiegoSuzuki** [comment]
Hi @sujayvenaik 

The error still persists. What is your hardware and software configuration?

Are these logs? If not, can you give me the instructions to collect this log?

[main.log](https://github.com/postmanlabs/postman-app-support/files/2465029/main.log)
[renderer-console.log](https://github.com/postmanlabs/postman-app-support/files/2465030/renderer-console.log)
[renderer-requester.log](https://github.com/postmanlabs/postman-app-support/files/2465031/renderer-requester.log)
[renderer-shared.log](https://github.com/postmanlabs/postman-app-support/files/2465032/renderer-shared.log)
[renderer-shell.log](https://github.com/postmanlabs/postman-app-support/files/2465033/renderer-shell.log)

**Comment by sujayvenaik** [comment]
Hey @DiegodeOliveira 
Thanks for these, can you also provide the logs from View -> Developer -> Show DevTools(Current VIew). Send the request once and after that get the logs.

![getlogs](https://user-images.githubusercontent.com/11532114/46743751-5ca9f300-ccc7-11e8-941a-b76fd3127e61.gif)

**Comment by DiegoSuzuki** [comment]
When I boot, it displays this:

`vendor-shared.js:111985 Initializing the global config
vendor-shared.js:52416 Could not find on WorkspaceStore. Missing or invalid parameter.
find @ vendor-shared.js:52416
requester.js:6725 App updater event Object
vendor-shared.js:52416 Could not find on WorkspaceStore. Missing or invalid parameter.
find @ vendor-shared.js:52416
2vendor-shared.js:52416 Could not find on EditorStore. Missing or invalid parameter.
find @ vendor-shared.js:52416
2vendor-shared.js:52416 Could not find on CollectionStore. Missing or invalid parameter.
find @ vendor-shared.js:52416`

It does not display new records after the request.

**Comment by DiegoSuzuki** [comment]
@sujayvenaik the same request in postman for Windows works.

**Comment by sujayvenaik** [comment]
@DiegodeOliveira 
Can you send the configuration of the system on which you were not able to receive the response?

We will look into it further then.
Thanks.

**Comment by DiegoSuzuki** [comment]
@sujayvenaik this is it?

![captura de tela de 2018-10-10 12-19-21](https://user-images.githubusercontent.com/3594572/46747166-f8673f00-cc86-11e8-9e78-7bb1c611c10b.png)

**Comment by numaanashraf** [comment]
Related to #4751
