### ISSUE TITLE
Apimatic integration doesn't convert to correct format, can't remove the integration

### ISSUE THREAD

**Issue by ash007-postman** [a85/POSTMan-Chrome-Extension#5339]
I tried converting from postman to Swagger 2.0 YAML format.  It converted to JSON format instead. 
I can't remove the integration, tried using the YAML conversion on their website and it isn't good enough for our purposes.
<img width="1314" alt="screen shot 2018-10-11 at 12 12 51 pm" src="https://user-images.githubusercontent.com/41741228/46786031-447eb600-cd51-11e8-810d-0f196f9b3719.png">

**Comment by igorsmaciel** [comment]
Same thing here

**Comment by ankit-m** [comment]
A fix for this has been pushed.
