### ISSUE TITLE
I can't run folders directly in the collection runner. Each subfolder must have a working property.

### ISSUE THREAD

**Issue by kamuranakcay** [a85/POSTMan-Chrome-Extension#5340]
**Is your feature request related to a problem? Please describe.**
Not a problem; but it will greatly facilitate my work.

**Describe the solution you'd like**
I cannot run each folder individually. Currently, I can run the Collection in the ‘Collection Runner’. But; I want to be able to run the folders directly in the collection. I should be able to run a single folder under the Collection. 

**Additional context**
![2](https://user-images.githubusercontent.com/34373724/46787697-02e60f00-cd41-11e8-81da-a5e1877a31f6.jpg)

**Comment by vkaegis** [comment]
@kamuranakcay Thanks for writing in! If you go to the collection runner, you can drill down into a selected collection and select the folder that you want to run individually. You can do the same from the collection browser as well, just select the folder you want to run and hit the Run button.

![run folder](https://user-images.githubusercontent.com/6038010/46794938-89f9ae00-cd66-11e8-9cd4-0b6dd6d54e4b.gif)

We're also working on a ton of improvements around these flows, so hopefully this will be more apparent in the coming versions.

**Comment by kamuranakcay** [comment]
Hi @vkaegis ,
Yes yes it can be operated in this way. However, there must be a run button next to each folder, as in the screenshot below. It makes it easier to use. 
In this way, I'll be able to run the folder quickly.

![screenshot_2](https://user-images.githubusercontent.com/34373724/46799939-cfb27880-cd5e-11e8-9960-1085ccc1e22f.png)

**Comment by vkaegis** [comment]
@kamuranakcay Ah, thanks for the clarification. I'm marking this as a feature request. We have a bunch of improvements around running collections in our short-term roadmap, will keep you updated!

**Comment by giridharvc7** [comment]
Please let us know if this solves your problem. 
<img width="1059" alt="Screenshot 2021-02-23 at 12 15 56 PM" src="https://user-images.githubusercontent.com/1040583/108810946-479d3880-75d2-11eb-9030-6e71552fc645.png">
