### ISSUE TITLE
Code snippets pane re-opens on every new tab even after closing once

### ISSUE THREAD

**Issue by ash007-postman** [a85/POSTMan-Chrome-Extension#5341]
Since updating to 6.4.2 I have two really annoying bugs with the code pane(s).

Firstly the code snippets panel keeps popping open on all new tabs and it's driving me nuts. This has never been a problem before, once closed it usually stays closed.

Secondly, I use a vertical pane layout as I find it more convenient. Now when I resize the code and response panes, the code doesn't wrap and is just either truncated if it's now too wide or left not filling the whole code pane properly if it's now too narrow.

These may seem like minor niggles but when you spend a whole day working on a lot of complex scripts it's really frustrating and wastes a lot of time.

**Comment by numaanashraf** [comment]
This has been fixed in Postman v6.5
