### ISSUE TITLE
I should be able to search the Manage Environment

### ISSUE THREAD

**Issue by kamuranakcay** [a85/POSTMan-Chrome-Extension#5342]
**Is your feature request related to a problem? Please describe.**
Not a problem; but it will greatly facilitate my work.

**Describe the solution you'd like**
I cannot search in the Manage Environment. I have to be able to search the variable in the vicinity environment. 

**Additional context**
![3](https://user-images.githubusercontent.com/34373724/46788295-848a6c80-cd42-11e8-8559-d8dde6042d30.jpg)

**Comment by giridharvc7** [comment]
Other duplicate issues - #8443, #8530, #9062

**Comment by danielbraeutigam** [comment]
This would be very helpful, any news on this?

**Comment by Koppo82** [comment]
It can't be that much of work to implement it. I am really looking forward for this. I have hundreds of variables and working with them is getting more and more annoying. We need a searchbar for collection and environment variables :(

**Comment by GuillaumeGuerra** [comment]
Indeed, for environments with lot of variables, scrolling through the list is painful
we can't even sort it alphabetically to help ...

plz !

**Comment by vedkribhu** [comment]
In our latest release v10.10, we have introduced filtering support in the variables list. Do let us know your feedback.
![Screenshot 2023-02-15 at 12 29 24 PM](https://user-images.githubusercontent.com/37595282/219374106-55608490-4e75-4465-9108-b7ca2fbf076a.png)

We are also working on adding sort functionality available in the manage variables table which should be out next month.
