### ISSUE TITLE
Markdown Inside Tables Rendered Incorrectly

### ISSUE THREAD

**Issue by kszafran** [a85/POSTMan-Chrome-Extension#5346]
**Describe the bug**
In some cases, markdown is not rendered inside tables.

**To Reproduce**
1. Import the following collection into Postman:
```
{
	"info": {
		"_postman_id": "f54f5fce-5f26-4203-97e9-49a0597bf99a",
		"name": "what's wrong",
		"description": "<table><tr><td>`Hello` _there_</td></tr></table>",
		"schema": "https://schema.getpostman.com/json/collection/v2.1.0/collection.json"
	},
	"item": [
		{
			"name": "with this folder",
			"item": [],
			"description": "<table><tr><td>`Hello` _there_</td></tr></table>"
		}
	]
}
```
2. View the documentation in web.

**Expected behavior**
Both tables should look the same.

**Screenshots**
<img width="664" alt="screen shot 2018-10-11 at 17 08 33" src="https://user-images.githubusercontent.com/3056812/46810174-bf0efc00-cd78-11e8-8f36-fc133040f349.png">

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version: 6.4.2
 - OS: macOS High Sierra 10.13.6
 - Browser: Chrome 69.0.3497.100

**Additional context**
I'm quite sure that this worked correctly before, so this is probably some kind of regression.

**Comment by godfrzero** [comment]
Confirmed as fixed, both markdown snippets render consistently now.

![image](https://user-images.githubusercontent.com/2700229/48669559-100ad080-eb2d-11e8-996c-e65fc61a5d3f.png)
