### ISSUE TITLE
It's not possible to browse tabs beyond currently visible ones

### ISSUE THREAD

**Issue by malafaya** [a85/POSTMan-Chrome-Extension#5350]
With new version 6.4.2, it's not possible to scroll through the open tabs. Selecting a partially visible tab does not automatically scroll all tabs left to make the selected tab separator totally visible.
By using Ctrl + 9, you indeed select the last tab, and its contents becomes visible, but the tabs do not scroll, and thus you cannot select for instance the tab before last if it's not visible. (On a side note, it seems "Ctrl + Shift + [" does not work for me using a Portuguese keyboard).
There doesn't seem to be a way to manually scroll through the tabs.

**To Reproduce**
1. Open as many tabs as necessary to fill the tabs space horizontally
2. Select the first tab (Ctrl + 1)
3. Opening new tabs will not make them visible on top space (the tabs will not scroll accordingly)

**Expected behavior**
When you create a new tab, the tab separator should be select and visible immediately.
Clicking on a partially visible tab should automatically scroll all tabs in order to make the selected tab totally visible.
Using Ctrl + 9 to select the last tab should make it visible in the tab separators.

**Screenshots**
In this image, you can see that I selected the rightmost tab but the tab separators did not scroll left in order to partially reveal the following tab.
![image](https://user-images.githubusercontent.com/11293825/46859892-f7f5b200-ce06-11e8-847d-2c8a7fc15313.png)

In this image, I opened a new tab. The new tab is not visible on tab separators; the tabs did not scroll accordingly. The selected tab separator is not visible:
![image](https://user-images.githubusercontent.com/11293825/46860034-5fabfd00-ce07-11e8-8db2-3b5c727ebec5.png)

**App information **
 - Postman Version 6.4.2
 - OS: Windows 10

**Comment by malafaya** [comment]
I found that I can use the mouse wheel to scroll through the tabs as a workaround. But still Ctrl + 9 should have the tabs scroll to the last tab separator automatically. Identical behavior would be expected when clicking on a partially visible tab, by scrolling one whole tab.

**Comment by malafaya** [comment]
@numaanashraf, feature? Ok, but in the previous version it worked fine. I would consider it a bug.

**Comment by numaanashraf** [comment]
@malafaya My bad. I've changed it to a regression.

**Comment by alorwu** [comment]
Been having the same issue for months now. Ctrl + 9 doesn't scroll the tabs. It just shows the last tab in the list of opened tabs. You other tabs before the last one are still not visible. And about the use of the mouse, not everyone uses a mouse unfortunately

**Comment by shaunc869** [comment]
Same here, not working.

**Comment by squrppi** [comment]
The same applies to browsing tabs with CTRL+TAB. Tabs get changed, but the tab bar does not scroll. The effect is the same to both directions:

1. have more tabs that fit on the tab bar
1. use mouse wheel to scroll the tab bar to middle
1. use CTRL+TAB or CTRL+SHIFT+TAB to navigate the tab bar
1. notice that tabs are changed but tab bar stays put

Just like with original reporter, "Ctrl + Shift + [" does not work with Finnish keyboard either, so I cannot test that.

**Comment by ankurdengla** [comment]
This issue is now fixed in Postman v7.7.2
Do let us know if the issue still persists.
