### ISSUE TITLE
Query parameters no longer show up in a collection's web view

### ISSUE THREAD

**Issue by abhijitkane** [a85/POSTMan-Chrome-Extension#5351]
Seen on October 12, 2018

These show up in the published docs - https://documenter.getpostman.com/view/583/spotify-playlist-generator/2MtDWP#9ed307cd-e8a2-28f3-8051-f227e36e8ec2

See screenshot:
<img width="1265" alt="screen shot 2018-10-12 at 16 37 24" src="https://user-images.githubusercontent.com/681190/46866026-5b023b80-ce3d-11e8-8ade-164a1f6aa1a6.png">

**Comment by ankit-m** [comment]
A fix for this has been deployed.
