### ISSUE TITLE
Unable to view documentation for a collection

### ISSUE THREAD

**Issue by abhijitkane** [a85/POSTMan-Chrome-Extension#5352]
The Documentation tab at https://<team_domain>.postman.co/collections/<cid>?workspace=<wid> page shows a "Something went wrong" message.

On checking the WebSocket logs, the WS request to `GET /api/documentation/<coll-uid>?` returns a 500: `body: {code: 500, message: "Oops, something went wrong. Please contact us at help@getpostman.com."}`

Seen on October 12, 2018

**Comment by godfrzero** [comment]
This should be fixed now, @abhijitkane could you verify and let me know?

**Comment by abhijitkane** [comment]
@godfrzero Yep, the end-user reports this fixed.
