### ISSUE TITLE
The response example supports comments

### ISSUE THREAD

**Issue by rbtyang** [a85/POSTMan-Chrome-Extension#5355]
Please read through the [guidelines](https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues) before creating a new issue.

**Is your feature request related to a problem? Please describe.**
- Through postman, I can easily provide response example for my colleagues .
- But telling colleagues what a field means is time consuming and easy to forget .

**Describe the solution you'd like**
- Very much expect comments can to be added to the response data  or example ! Such as:
- [Chinese API collaboration service providers provide such functionality]( https://www.easyapi.com/ )
  ![image](https://user-images.githubusercontent.com/18330446/46900205-1fb14c80-ced1-11e8-8292-d681e07b9e3d.png)

**Describe alternatives you've considered**
- So i had to use some silly methods to tell my colleagues what the field meant . Such as:
  ![silly methods](https://user-images.githubusercontent.com/18330446/46900179-ac0f3f80-ced0-11e8-9b2a-b98ed4180225.png)

**Additional context**
- None.

**Comment by akshay-kulkarni-03** [comment]
With Postman V11 version, you can now comment on the response example and provide feedback to your team mates easily.
