### ISSUE TITLE
Postman Crashes at launch (Error: Could not open Postman)

### ISSUE THREAD

**Issue by Postman-Gabriel** [a85/POSTMan-Chrome-Extension#5356]
**Describe the bug**
At Launch, the app provides an infinite loading screen on the smaller window, then offers a popup that says something went wrong and to contact Postman Support

**To Reproduce**
1. Open App
2. See error

**Expected behavior**
Expected to be able to open the app no problem

**Screenshots**
![image](https://user-images.githubusercontent.com/40899145/46907568-84c16e00-cee2-11e8-94d4-aedbd651dc66.png)

**App information (please complete the following information):**
 - App Type: Native App 
 - Postman Version: 6.4.2
 - OS: Mac OSX High Sierra 10.14.1

**Additional context**
This might be a problem with 6.4.2 and 10.14.1, as other users have reported lag when using these two in tandem.

**Comment by numaanashraf** [comment]
@Postman-Gabriel do we have any logs or additional information? Right now there isn't enough information to debug this.

**Comment by Postman-Gabriel** [comment]
Hi Numaan,

The user just followed up saying that the problem was magically resolved. I have been receiving some sparse reports that 10.14 and 6.4.2 has been having problems. At this point, more important to keep that in mind than solving this exact issue.

**Comment by numaanashraf** [comment]
Root issue is tracked at #4897. Closing as duplicate.
