### ISSUE TITLE
Console Tab Search field is not allowing users to paste copied text through mouse. 

### ISSUE THREAD

**Issue by Sainath77601** [a85/POSTMan-Chrome-Extension#5358]
Please read through the [guidelines](https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues) before creating a new issue.

**Describe the bug**
Unable to Paste Copied Text into Search Field in Console Tab through Mouse.

**To Reproduce**
1. Open the 'Console Tab'
2. Go to 'Search field'
3. Right Click through mouse
4. Click on Paste Option.

**Expected behavior**
Search field should allow users to paste copied text through mouse.

**Screenshots**
![postman bug](https://user-images.githubusercontent.com/44154544/46933426-9f761d00-d071-11e8-964c-3be0c30338ba.png)

**App information (please complete the following information):**
 - Chrome.
 - Postman Version : v6.4.2
 - OS: Windows 10.

**Additional context**
Many users does not know to paste through Keyboard shortcut,they will use mouse right click option to paste the copied text.

**Comment by numaanashraf** [comment]
Fixed in Postman v7.0
