### ISSUE TITLE
Unable to get working pdf file in v6.4.2

### ISSUE THREAD

**Issue by Witti** [a85/POSTMan-Chrome-Extension#5359]
**Describe the bug**
Getting back a application/pdf as response destroys the pdf file. (Worked with v 6.3, doesn't work with v 6.4.2)

**To Reproduce**
1. Go to Build
2. Enter URL for an endpoint responding with application/pdf
3. Check the pdf (for me it contains all pages but without content)

**Expected behavior**
A working pdf file.

**App information (please complete the following information):**
 - Native App
 - 6.4.2
 - OS: mac os 10.13.6

**Comment by sujayvenaik** [comment]
Hey @Witti 

Thanks for writing in and for reporting this issue.
This issue has been fixed in the latest version (6.5.x) release of the Postman app.
