### ISSUE TITLE
Unable to view the monitors under Monitors tab on the Web dashboard

### ISSUE THREAD

**Issue by Ramya-From-Postman** [a85/POSTMan-Chrome-Extension#5360]
**Describe the bug**
There are a couple of monitors created on the postman app which I can see them under "https://go.postman.co/team/elements?type=monitor" but they don't show up under Monitor tab on the web dashboard.

**To Reproduce**
1. Create a monitor for any collection
2. Login to the Web dashboard,
3. Navigate to monitors tab of the relevant team workspace & it says "**Looks like this workspace doesn't have any monitors**"

**Expected behavior**
Created monitors should show up under monitors tab of the relevant team workspace.

**Screenshots**
![image](https://user-images.githubusercontent.com/40994626/47007144-31a32180-d155-11e8-9980-1cadfe5c3065.png)

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version: 6.4.2

**Comment by preethammavin** [comment]
Closing it in reference to #5360
