### ISSUE TITLE
Response not rendered on preview tab of body correctly for some cases

### ISSUE THREAD

**Issue by funketyme** [a85/POSTMan-Chrome-Extension#5363]
## App Details:
```
Postman for Windows
Version 6.4.2
win32 10.0.17763 / x64
```

## Issue Report:
 1. This issue started occurring after upgrading to Postman 6.4.2.
 2. Requests returning the attached HTML (and similar HTML) would render fine in the "Preview" tab after  a request completed.  This is standard "dump" HTML returned by Adobe CF, Railo, Lucee, etc.
[dump.zip](https://github.com/postmanlabs/postman-app-support/files/2480639/dump.zip)
 3. The attached file renders fine when saved to your desktop and opened in any major browser.  It no longer renders correctly in Postman and instead says "Could not beautify."  See screenshot.  
![image](https://user-images.githubusercontent.com/2416326/46979656-ff2af300-d086-11e8-85dc-01e415566a57.png)

**Comment by sujayvenaik** [comment]
Hey @funketyme 

I created an example with the response you sent, and the correct preview was rendered.
Screenshot attached
![screen shot 2018-10-16 at 5 57 37 pm](https://user-images.githubusercontent.com/11532114/47016382-2e1b9480-d16d-11e8-834d-27cf8d8c0a0f.png)

Can you send the response headers that you are receiving with this request?

**Comment by funketyme** [comment]
The headers are below and indicate a .json response, however it will not render HTML even if I manually select HTML in the pulldown next to the pretty/raw/preview link.  It has always rendered HTML correctly even if the headers indicate .json.
![image](https://user-images.githubusercontent.com/2416326/47040783-03651800-d13c-11e8-8183-1d8e4d68ccf1.png)

I discovered something else that I think will shed some light on this.  Here is a screenshot of me clicking preview on the response and seeing the unrendered HTML (even after selecting HTML in the pulldown).
![poastmanbroken](https://user-images.githubusercontent.com/2416326/47040825-1bd53280-d13c-11e8-88c5-e8d8067c109f.png)

However, if I click on the SAVE button … 
![image](https://user-images.githubusercontent.com/2416326/47040847-28598b00-d13c-11e8-8fa0-ef924191121e.png)

… and then select HTML and click preview (before actually saving it), it renders as expected!  It appears something is slightly different between the "normal" preview and the preview that shows when saving a response.
![postmansave](https://user-images.githubusercontent.com/2416326/47040868-3ad3c480-d13c-11e8-82b1-fcbc1ddaffd4.png)

Headers and new response attached if you want them.
[response.zip](https://github.com/postmanlabs/postman-app-support/files/2484576/response.zip)
-----
Responding-Server →XPS13-Tal-Funke-Bilu
Return-Format →json
Set-Cookie →CF_CLIENT_INTUVOSERVICES_LV=1539715112142;Path=/;Expires=Mon, 14-Jan-2019 18:38:32 UTC
Set-Cookie →CF_CLIENT_INTUVOSERVICES_TC=1539715112142;Path=/;Expires=Mon, 14-Jan-2019 18:38:32 UTC
Set-Cookie →CF_CLIENT_INTUVOSERVICES_HC=2;Path=/;Expires=Mon, 14-Jan-2019 18:38:32 UTC
Content-Type →application/json;charset=UTF-8
Content-Length →19811
Date →Tue, 16 Oct 2018 18:38:32 GMT

**Comment by sujayvenaik** [comment]
Hey @funketyme 

We have identified a possible fix for this and will be rolling out in the next release.

**Comment by funketyme** [comment]
I mistakenly commented that 6.4.4 had resolved the issue.  Sorry for the confusion.  The issue is present in 6.4.4 still.

**Comment by sujayvenaik** [comment]
Hey @funketyme 

Thanks for writing in and for reporting this issue.
This issue has been fixed in the latest version (6.5.x) release of the Postman app.
