### ISSUE TITLE
Unable to beautify request body in highlight while setting content-type with “application/json;charset=UTF-8”

### ISSUE THREAD

**Issue by Holinc19** [a85/POSTMan-Chrome-Extension#5364]
Request body would chang to ‘Text’ pattern while setting content-type with “application/json;charset=UTF-8”，and it could not be beautifying in highlight.

Postman Version 6.4.2
win32 6.1.7601 / x64

![image](https://user-images.githubusercontent.com/28728567/46989773-f7278d80-d130-11e8-8eee-96d56adc81c7.png)
![image](https://user-images.githubusercontent.com/28728567/46989756-e37c2700-d130-11e8-964a-abbace7c2592.png)

**Comment by sujayvenaik** [comment]
Hey @Holinc19 
We have identified this, and would be rolling out a fix for this in the next patch release

**Comment by sujayvenaik** [comment]
Hey @Holinc19 
We have fixed this and it is available on the latest v6.4.4.

You can update the app.

Thanks for writing in and reporting this issue.
