### ISSUE TITLE
Postman unable to read the full response from self created http server.

### ISSUE THREAD

**Issue by neesonqk** [a85/POSTMan-Chrome-Extension#5365]
**Describe the bug**
Send a request via Postman to a self-created http server, got `Error: read ECONNRESET` exception from its console, however, this never happened if request from a browser, furthermore, I tested through from code snippets (Java OK HTTP) which generated by postman, it doesn't have this issue as well.

I create a [Stackoverflow ticket](https://stackoverflow.com/questions/52810480/self-created-http-server-cannot-handle-postman-request?noredirect=1#comment92539358_52810480) about more details.

**App information:**
 - App Type: Self-created Http Server [Source Code](https://github.com/neesonqk/HttpServer)
 - Postman Version: 6.4.2
 - OS: macOS Mojave 10.14

**Additional context**
The Server
```java
package com.ont.http;

import java.io.*;
import java.net.ServerSocket;
import java.net.Socket;

public class SingleThreadHttpServer implements HttpServer {

    public void run(int port) throws IOException {
        ServerSocket serverSocket = new ServerSocket(port);
        try {
            while (true) {
                Socket socket = serverSocket.accept();

                BufferedReader inBufferReader = new BufferedReader(new InputStreamReader(socket.getInputStream()));
                StringBuilder stringBuffer = new StringBuilder();

                String inputLine;
                while ((inputLine = inBufferReader.readLine()) != null && !inputLine.equals("")) {
                    stringBuffer.append(inputLine);
                    stringBuffer.append("\r\n");
                }

                System.out.println(stringBuffer.toString());

                OutputStream outStream = socket.getOutputStream();
                // Header should be ended with '\r\n' at each line
                outStream.write("HTTP/1.1 200 OK\r\n".getBytes());
                //outStream.write("Main: OneServer 0.1\r\n".getBytes());
                outStream.write("Content-Length: 22\r\n".getBytes()); // if text/plain the length is required
                outStream.write("Content-Type: text/plain\r\n".getBytes());
                //outStream.write("Connection: close\r\n".getBytes());

                // An empty line is required after the header
                outStream.write("\r\n".getBytes());

                String line;
                BufferedReader bufferedReader = new BufferedReader(new StringReader("A Message from server."));
                while ((line = bufferedReader.readLine()) != null) {
                    outStream.write(line.getBytes());
                }

                outStream.flush();
                outStream.close(); // Socket will close automatically once output stream is closed.
                bufferedReader.close();
                inBufferReader.close();
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
```
The Code Snippets from PostMan

```java
OkHttpClient client = new OkHttpClient();

Request request = new Request.Builder()
  .url("http://localhost:8080/")
  .get()
  .addHeader("Accept", "*/*")
  .addHeader("accept-encoding", "gzip, deflate")
  .addHeader("host", "localhost:8080")
  .addHeader("user-agent", "PostmanRuntime/7.3.0")
  .addHeader("cache-control", "no-cache")
  .build();

Response response = client.newCall(request).execute();
```

**Comment by abhijitkane** [comment]
@shamasis The issue is not in the codegen, but the request sending flow.

**Comment by saswatds** [comment]
Hey @neesonqk over this period of time we have been actively fixing bugs. Could you update to the latest version of postman app and confirm that this problem still persists?

**Comment by neesonqk** [comment]
Hi @saswatds tested with the latest postman and confirm that this problem still persists.

Postman version,

![image](https://user-images.githubusercontent.com/7279067/60516189-d4192a00-9d0f-11e9-8cab-69d7ebb99a5f.png)

Screenshot,

![2019-07-02 at 9 21 PM](https://user-images.githubusercontent.com/7279067/60516138-b64bc500-9d0f-11e9-8c87-a3be9006b355.gif)

**Comment by neesonqk** [comment]
If I merge the output stream into one single line, then it starts to work, examples are as bellow,

**Doesn't Work**

```java
   OutputStream outStream = socket.getOutputStream();
   // Header should be ended with '\r\n' at each line
   outStream.write("HTTP/1.1 200 OK\r\n".getBytes());
   outStream.write("Content-Length: 22\r\n".getBytes()); // if text/plain the length is required
   outStream.write("Content-Type: text/plain\r\n".getBytes());
   //outStream.write("Connection: close\r\n".getBytes());

  // An empty line is required after the header
  outStream.write("\r\n".getBytes());
```


**Work**

```java
    OutputStream outStream = socket.getOutputStream();
    outStream.write("HTTP/1.1 200 OK\r\nContent-Length: 22\r\nContent-Type: text/plain\r\nConnection: close\r\n\r\n".getBytes());
```

**Comment by saswatds** [comment]
@neesonqk Thanks for the confirmation, I will take a look at root cause for this.

**Comment by vikiCoder** [comment]
Hi @neesonqk 

I was able to reproduce the issue and identify the root cause of this. Postman connects to the server two times for all `localhost` URLs. The first connection is just to check the reachability of the server and it is closed immediately without waiting for the response from server. If the server is reachable then it will connect again and send the second request and show the response of the second request.

In case of the server you have posted, it crashes when the first connection from Postman is closed. Since Postman closes the connection without waiting for the full response for the first connection, multiple `outStream.write()` calls in your server will throw an exception (`java.net.SocketException: Broken pipe (Write failed)`) causing the server to crash. So the second request sent by Postman will not get any response.

I believe that this is a problem with Postman App and we will fix this ASAP. But on the other hand, this type of error should also be properly handled on the server-side to prevent the crash. Not only the Postman App but request sent using other tools can also crash your server if the client destroys the connection in middle of the server sending the response (i.e. make the request using any browser, send a very large response or keep a delay between subsequent `outStream.write()` calls, close the browser tab before receiving the complete response, this will crash your server). 

See the modified server code posted below which will work fine for such situations:

```java
import java.io.*;
import java.net.ServerSocket;
import java.net.Socket;

public class SingleThreadHttpServer implements HttpServer {

    public void run(int port) throws IOException {
        ServerSocket serverSocket = new ServerSocket(port);
        try {
            while (true) {
                Socket socket = serverSocket.accept();

                BufferedReader inBufferReader = new BufferedReader(new InputStreamReader(socket.getInputStream()));
                StringBuilder stringBuffer = new StringBuilder();

                String inputLine;
                while ((inputLine = inBufferReader.readLine()) != null && !inputLine.equals("")) {
                    stringBuffer.append(inputLine);
                    stringBuffer.append("\r\n");
                }

                System.out.println(stringBuffer.toString());

                OutputStream outStream = socket.getOutputStream();
                BufferedReader bufferedReader = new BufferedReader(new StringReader("A Message from server."));

                try {
                    // Header should be ended with '\r\n' at each line
                    outStream.write("HTTP/1.1 200 OK\r\n".getBytes());
                    //outStream.write("Main: OneServer 0.1\r\n".getBytes());
                    outStream.write("Content-Length: 22\r\n".getBytes()); // if text/plain the length is required
                    outStream.write("Content-Type: text/plain\r\n".getBytes());
                    //outStream.write("Connection: close\r\n".getBytes());

                    // An empty line is required after the header
                    outStream.write("\r\n".getBytes());

                    String line;
                    while ((line = bufferedReader.readLine()) != null) {
                        outStream.write(line.getBytes());
                    }

                    outStream.flush();
                    outStream.close(); // Socket will close automatically once output stream is closed.
                } catch (SocketException e) {
                    // Handle the case where client closed the connection while server was writing to it
                    socket.close();
                }

                bufferedReader.close();
                inBufferReader.close();
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
```

**Comment by neesonqk** [comment]
@vikiCoder  thanks for the explanation, now I understood why is this happening, I created that server project for practicing purpose, I will indefinably modify my code to make is more robust, thanks again for the investigation.

Feel free to close this ticket if needed.
