### ISSUE TITLE
Monitor summary email even on the days the monitors don't run

### ISSUE THREAD

**Issue by VicKetchup** [a85/POSTMan-Chrome-Extension#5366]
**Describe the bug**
Our monitors are setup to run "every weekday", meaning that no monitors are run on Saturday and Sunday, however Monitor Summary emails come for Saturday and therefore the comparison between the amount of healthy monitors and so on are not meaningful on Monday.

**To Reproduce**
Setup a monitor to run every weekday, the summary email will come on Saturday and Monday will compare itself to nothingness.

**Expected behavior**
Only send summary emails on the day that the Monitors are running and compare the status to the previous day with runs.

**Screenshots**
Saturday Run:
![image](https://user-images.githubusercontent.com/43671684/47002069-e3c1f580-d123-11e8-91b9-03603de4bbde.png)

Monday Run:
![image](https://user-images.githubusercontent.com/43671684/47002097-f805f280-d123-11e8-891f-873d8852fa57.png)

**App information (please complete the following information):**
 - N/A

**Additional context**
It's not a majour issue, however it would be nice to have these emails display meaningful data all the time, as we also have stats like these displayed on monitors all over the office.

**Comment by sankalp0o** [comment]
@VicKetchup Thanks for pointing this out. We are working on building better reporting functionality and we will take this into account.

**Comment by godfrzero** [comment]
Daily/weekly summary mailers are now only sent out if there were runs within the respective periods.
