### ISSUE TITLE
Bug with loading multiple requests in a postman collection - v6.4.2

### ISSUE THREAD

**Issue by dsouzawilbur** [a85/POSTMan-Chrome-Extension#5368]
Hi Team,
When we have multiple requests in a collection, if we trigger one request and switch to the next request quickly while the previous request is loading, the previous request output shows up in the current request

**To Reproduce**
1. Open a collection with multiple requests
2. Click on one request, request_1, and do a submit
3. while the request, request_1, is being submitted, switch to the next request, request_2 in the collection
4. The previous output of request_1, is seen in the output area of request_2

In the earlier versions i was not facing this issue, since i used to do this all the time since the API's take some time to respond, i used to submit multiple request.

 - App Type : Native App
 - Postman Version: v6.4.2
 - OS: Windows 11

Regards,
Wilbur Dsouza

**Comment by kamalaknn** [comment]
Hi @dsouzawilbur 

Thanks for reporting this. We'll take a look at this.

**Comment by kamalaknn** [comment]
Hi @dsouzawilbur 

This issue has been fixed in the latest version of Postman - `6.5.2`. Please update to the latest version of Postman and let us know if you are still seeing this.
