### ISSUE TITLE
Unable to create an environment with more than 100 variables via API

### ISSUE THREAD

**Issue by Ramya-From-Postman** [a85/POSTMan-Chrome-Extension#5369]
Currently, it is not possible to create an environment variable if it contains more than 100 variables in it.
If you take a look at the documentation in the JSON schema for POSTing environments, it says maxItems: 100 https://docs.api.getpostman.com/#152d94ab-a94d-f5fc-c8db-73c61a56f4ce

And since we can’t just PUT additional items to the list (we have to PUT the complete environment record) there’s no way to get to >100 elements.

Specifically the error that the API responds when I try to submit anyway is. Please increase the limit.

```{ error:

{ name: 'malformedRequestError',

message: 'Array is too long (101), maximum 100 at environment.values' } }```

**Comment by chrisjohnson** [comment]
This was my issue. It's problematic because you can do this in the GUI postman tool but the schema for the API is limited. Either a mechanism to PUT additional variables or removing teh 100 item restriction would work for me here

**Comment by chrisjohnson** [comment]
Still hopeful to see a resolution to this seemingly simple problem of just increasing the schema max. This is still preventing my team from properly using your tool that we are paying for.

**Comment by preethammavin** [comment]
@chrisjohnson sorry for the late reply , the issue has been fixed on our end deployed to production.

**Comment by chrisjohnson** [comment]
I haven't gotten around to testing it yet but I'm looking here: https://docs.api.getpostman.com/?_ga=2.77878484.1710975912.1559057803-1167593033.1559057803&version=latest#152d94ab-a94d-f5fc-c8db-73c61a56f4ce

And the schema still checks for maxItems: 100. Do the docs just need to be updated?

Also I'm curious why the environment schema isn't hosted at a public URL like the collection schema is. Right now I have to go look at the docs and manually copy teh code hunk out and store it in my repository if I want a CI job to check that my environment schemas are correct. Should I submit a new issue to have it hosted at a proper URL? Am I just missing the URL?

**Comment by chrisjohnson** [comment]
@preethammavin Just wondering if you saw this message ^

**Comment by chrisjohnson** [comment]
Bump

**Comment by chrisjohnson** [comment]
Bleep Bloop
