### ISSUE TITLE
Expanding environment variable doesn't work for bigger content-length recursively

### ISSUE THREAD

**Issue by xsedlak** [a85/POSTMan-Chrome-Extension#5370]
**Describe the bug**
When the content-length is greater than approximately 2000 characters then environment variables didn't expand.

**To Reproduce**
1. Select a request where are two environment substitutions, the content-length is not greater than 1900
2. Select an environment in the drop down, where are used environment variables recursively
```  TEST_ENVIRONMENT=QA
  NS_ACCOUNT=4988545
  NS_SUBSIDIARY={{TEST_ENVIRONMENT}}_{{NS_ACCOUNT}}_PILSNER
  NS_SUBSIDIARY_MAIN={{TEST_ENVIRONMENT}}_{{NS_ACCOUNT}}
  NS_SUBSIDIARY_SECONDARY={{TEST_ENVIRONMENT}}_{{NS_ACCOUNT}}_INTEL
  NS_SUBSIDIARY_TERTIARY={{TEST_ENVIRONMENT}}_{{NS_ACCOUNT}}_CHIQUITA
  etc.
````
3. Click on Postman Console icon
4. Send the request
5. (x) You can see in the attachment Postman Console, where are not expanded environment variables

**Expected behavior**
All environment variable should be expanded

**Actual behavior**
We have the problem with a bigger request. There is one WA:
```javascript
// TODO - https://github.com/postmanlabs/postman-app-support/issues/2922
var replaceVars = function(string){
    return string.replace(/\{\{.+?\}\}/g, function(match){
        var varName = match.substr(2, match.length - 4);
        var varValue = environment[varName] || globals[varName];
        return varValue ? replaceVars(varValue) : match; // recursive!
    });
}
```
I'm go crazy because each bigger request use the WA.

**Screenshots**
![image](https://user-images.githubusercontent.com/177861/47020316-65804600-d159-11e8-89f5-d9b26f35fc56.png)

**App information (please complete the following information):**
 - Postman Version 6.4.2 win32 10.0.16299 / x64, we had the same problem 10 months ago

**Additional context**

**Comment by codenirvana** [comment]
@xsedlak Probably related to #5682.
Can you check if this issue persists in the latest version of the Postman app?

**Comment by codenirvana** [comment]
Closing this issue as we can’t replicate this and we haven’t seen other users facing similar issues.
Please feel free to reopen if the issue persists.
