### ISSUE TITLE
Self-publishing more than 1 template

### ISSUE THREAD

**Issue by loopDelicious** [a85/POSTMan-Chrome-Extension#5374]
**Describe the bug**
Cannot successfully publish a second template without first re-logging in to the dashboard.

**To Reproduce**
1. Publish first template in the dashboard
2. Publish second template in the dashboard
- the description is pre-populated with the first template's description
- the categories are pre-selected with the first template's description
- updating the description and category edits the first template (even though it looks like I'm editing the second template)
- not editing the description and category does not impact the first template
- the second template shows "Published" status in the dashboard, but is not available in the Postman app

**Screenshots**
<img width="1489" alt="screen shot 2018-10-16 at 2 00 57 pm" src="https://user-images.githubusercontent.com/17693714/47047501-927a2c00-d14c-11e8-83c1-05ec58975ae3.png">
<img width="1489" alt="screen shot 2018-10-16 at 2 02 01 pm" src="https://user-images.githubusercontent.com/17693714/47047774-6612df80-d14d-11e8-84e9-85b325170aa4.png">

**App information (please complete the following information):**
 - OS: [e.g. macOS High Sierra 10.13.2]
 - Version 6.4.2

**Additional context**
- Re-opening the dashboard to publish a subsequent template does not result in any interference from previously published templates.
- Quitting the Postman app, and rebooting to see (under New > Templates) if the template has been published.

**Comment by dhineshwiz** [comment]
hey @loopDelicious thanks for reporting the issue. I could able to reproduce it, It look like the previous state is not being unset. we will fix this soon and keep you updated.

**Comment by ankit-m** [comment]
A fix for this has been pushed.
