### ISSUE TITLE
Embedded "Run in Postman" button creates duplicates

### ISSUE THREAD

**Issue by JP-from-Postman** [a85/POSTMan-Chrome-Extension#5375]
Summary: @ashawasthi reported that clicking the embedded Run in Postman buttons causes duplicate collection to be imported.

Attached zip:
[run-in-postman-dupe.zip](https://github.com/postmanlabs/postman-app-support/files/2485002/run-in-postman-dupe.zip)
Contains:
- Console_logs.log: DevTools Shared logs
- Duplicate calls.png: Console screenshot of duplicate import calls
- Postman-Bug.mp4: Screen capture of bug behavior

(From @ashawasthi) Steps to reproduce:
0. From: https://developer.yodlee.com/apidocs/index.php
1. Click on Run in Postman button from embedded html button.
2. New collection should be imported. 
3. Delete the collection and then repeat step 1. 
4. It ask that do you want to import as a copy or replace, even though I have had deleted it. 
5. If I says, that same collection already exists. And when I choose either of the option(replace or import as a copy). It creates duplicates. 
6. Delete all the copies and then repeat the steps of importing and it will have N number of copies imported this time.

Support findings:

- Issue reported on Windows client v6.4.2
- Support unable to reproduce on macOS or Windows client, in personal and team workspaces
- Duplicate import calls appear in console

**Comment by SamvelRaja** [comment]
@JP-from-Postman  Were you able to reproduce this issue in 7.x version of the app.  
It is working fine as expected from my end.

**Comment by SamvelRaja** [comment]
Closing this as it is not reproducible in 7.x version.
