### ISSUE TITLE
Navigating back to Request from Examples can land you in the wrong Request

### ISSUE THREAD

**Issue by elementlipeng** [a85/POSTMan-Chrome-Extension#5376]
**Describe the bug**
When viewing examples of a request, you can click on the name of Request on top left of the pane to navigate back to that request. Sometimes that navigates you to the wrong request.

**To Reproduce**
1. Go to any request, let's call it request1, and click on one of its examples to navigate to that example
2. Without leaving the example window, click on another request, let's call it request2
3. Navigate to an example on request2
4. Click on the "<- request2" button on the top left of the example pane, which is supposed to take you back to request2
5. It navigates you back to request1 instead. This can be very confusing when you rapidly modify a lot of examples in succession.

I'm guessing the state for navigation isn't cleared correctly when you click on another request directly from the examples window. 

**Expected behavior**
Clicking on the back to request button should always take you back to the right one.

**Screenshots**
See video:
https://streamable.com/8wq4l

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version: 6.3.0
 - OS: macOS High Sierra 10.13.6

**Comment by sivcan** [comment]
@elementlipeng Can you upgrade to the latest version of the postman app _viz._ **v6.4+** ?

We've done some major improvements to the tabs and fixes around example views too and the issue that you've pointed out.

Let us know if you're still facing this issue after upgrading.

**Comment by numaanashraf** [comment]
@elementlipeng We had fixed this as part of 6.4. Do let us know and feel free to reopen if you are still facing this issue in v6.4
