### ISSUE TITLE
Terms of Use link on account creation page is broken

### ISSUE THREAD

**Issue by Ramya-From-Postman** [a85/POSTMan-Chrome-Extension#5377]
**Describe the bug**
On the account creation page, when clicked on the "**Terms of Use**" link it is navigating to the page "https://www.getpostman.com/licenses/postman_base_app/" which is throwing 404 not found error. Please fix this.

**To Reproduce**
1. Go to the link https://identity.getpostman-beta.com/signup?addAccount=1 & click on "Terms of Use"

**Expected behavior**
When clicked on "Terms of Use" link,m it should navigate to: https://www.getpostman.com/licenses/postman_eula

**Screenshots**
![image](https://user-images.githubusercontent.com/40994626/47082239-93818b00-d22a-11e8-95a8-65f4f75ab9bd.png)

![image](https://user-images.githubusercontent.com/40994626/47082269-a5fbc480-d22a-11e8-9e98-5a6bf3b12485.png)

**Comment by a85** [comment]
This seems to be fixed now.
