### ISSUE TITLE
Monitor response time in the graph isn't rendered properly

### ISSUE THREAD

**Issue by Ramya-From-Postman** [a85/POSTMan-Chrome-Extension#5378]
Monitor response time in the graph isn't rendered properly, The response in time graph is completely flat. Also, the Y-axis reading shows zero seconds (0s). 
![image](https://user-images.githubusercontent.com/40994626/47082930-d6446280-d22c-11e8-810e-7054f7861bd5.png)

**Comment by ArjunSingh-PM** [comment]
Confirmed that this issue is fixed.
