### ISSUE TITLE
Make generated curl commands functional in bash

### ISSUE THREAD

**Issue by jaxley** [a85/POSTMan-Chrome-Extension#5380]
**Is your feature request related to a problem? Please describe.**
The ability to get a curl command to reproduce a request/response outside of Postman is an invaluable feature.  However, Postman is not currently encoding all of the necessary values in the generated command to allow it to work properly in Bash.  

I specifically had an issue (using the Jenkins API) where square brackets were not encoded and this caused the curl command to fail in bash.  It was laborious to manually encode the values.

**Describe the solution you'd like**
Any curl command can be pasted directly in to bash and works properly.

**Describe alternatives you've considered**
Manually-encoding the values as a workaround.

**Comment by rchasman** [comment]
The '\\' between each line break are what's causing the failure in bash for me.

**Comment by abhijitkane** [comment]
@jaxley 
Can you try this is Postman 7.2.1, with the 'Experimental Codegen Mode' flag enabled in Postman's global settings? We've introduced bug-fixes, support for two new languages (JS-Fetch and Powershell), and the ability to configure certain aspects of the generated snippet.

@rchasman Using the experimental mode, you can change the line continuation character to `^` (for Windows) or `\` for OSX/Linux.
