### ISSUE TITLE
(macOS) Save dialog does not expand correctly

### ISSUE THREAD

**Issue by JP-from-Postman** [a85/POSTMan-Chrome-Extension#5381]
Found on macOS High Sierra 10.13.6 (17G2307)

Steps to reproduce:

1. Right click collection, select Export
2. Leave default radio button checked for Collection v2.1, click Export
3. Click chevron to the right of file name text field
4. dialogue UI starts to bug out, unable to expand view to select directory

Attached recording shows result
[export_collection_dialogue_bug.mov.zip](https://github.com/postmanlabs/postman-app-support/files/2489507/export_collection_dialogue_bug.mov.zip)

**Comment by ankurdengla** [comment]
The fix for this issue is now available in the latest Canary app - [Postman Canary 7.3.0-canary01](https://www.getpostman.com/downloads/canary). Please check it out and let us know if the issue still persists.

**Comment by harryi3t** [comment]
This is fixed in the latest version of Postman (v7.3.4).
