### ISSUE TITLE
pm.expect(...).to.be.a('number') fails for number value

### ISSUE THREAD

**Issue by srinkumar2000** [a85/POSTMan-Chrome-Extension#5382]
I'm trying to test the value of the ssn returned in the json response is number with this code:

//ssnLast4 is a json attrib in the json response returned
pm.test("Valid SSN", function () {
   pm.expect(jsonData.ssnLast4).to.be.a('number');
   });

The above code works as expected (by failing the test) if the value returned is NOT number. But, the above code also fails if the value returned in ssnLast4 is a number.

**Expected behavior**
The Test should pass if the ssnLast4 contains Number and should fail if it does NOT contain Number.

**Screenshots**
![image](https://user-images.githubusercontent.com/40003608/47135542-8a61df80-d265-11e8-99a5-ac7f0c7eecba.png)

**App information (please complete the following information):**
 - App Type [e.g. Chrome App, Native App] Native app
 - Postman Version [e.g. 6.0.1] Version 6.4.2 (6.4.2)
 - OS: [e.g. macOS High Sierra 10.13.2] mac OS Sierra Version 10.12.6 (16G29)

**Additional context**

**Comment by sivcan** [comment]
@srinkumar2000 Looks like `jsonData.ssnLast4` is infact a string rather than a number.
You can refer the following example:
![image](https://user-images.githubusercontent.com/12631777/47136930-cbdca400-d2d2-11e8-84f8-a4d7ed335210.png)

Script used:
```javascript
let jsonData = {
    a: 1,
    b: '1'
};

pm.test('Expect number to be a number', function () {
    pm.expect(jsonData.a).to.be.a('number');
});

pm.test('Expect string to be a number', function () {
    pm.expect(jsonData.b).to.be.a('number');
});
```

Postman uses a fork of Chai and here's the repo: https://github.com/postmanlabs/chai-postman

**Comment by sunilsah-blackbook** [comment]
pm.test('Expect number to be a number', function () {
    pm.expect(parseInt(jsonData.a)).to.be.a('number');
});
