### ISSUE TITLE
Windows Postman Bulk Edit mode add spaces to form data

### ISSUE THREAD

**Issue by darkworks** [a85/POSTMan-Chrome-Extension#5383]
**Describe the bug**
when we copy form data from **bulk edit** section then postman add one space to the values , lets say i copy form data from bulk edit section and then paste it again or send to someone else who will paste the data in bulk edit section when he switch to "**Key Value Edit**" then values will have one space which effect the testing as each value have one space

**To Reproduce**
1. Open Postman
2. create Post request 
3. Add form data to that post request
4. On right side click Bulk edit  and copy the form data 
5  Paste that bulk data again and switch to Key Value edit mode you will have space in each value . that's the problem

**Screenshots**

Bulk edit mode : https://i.imgur.com/q7EvM9Q.png
Key Value Edit mode : ( spaces are added by post man ): 
![image](https://user-images.githubusercontent.com/12841788/47136757-232c4580-d2ce-11e8-8a3b-8be63b0b8a96.png)

**App information (please complete the following information):**
 - App Type  : windows desktop application , 
 - Postman Version : 6.4.4
 - OS: windows 7 

Solution : Add small function to postman that could remove spaces it start of form data value  introduced in bulk edit mode

**Comment by ghost** [comment]
@darkworks As per the information you have provided, it looks like you have added space in bulk-edit mode to the values and that's why values in the key-value form have space too. 

Remove the leading space from values in bulk-edit mode and it will be removed from values in the key-value form.

**Comment by darkworks** [comment]
ya right looks like it was caused due to space
