### ISSUE TITLE
Query parameter was converted from string to numeric value

### ISSUE THREAD

**Issue by slim-hmidi** [a85/POSTMan-Chrome-Extension#5384]
Please read through the [guidelines](https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues) before creating a new issue.

**Describe the bug**
I create an api and I'm trying to debug it using postman. My api is: 
```js
127.0.0.1:3000/api/tasks/first_id/task/second_id?linkTypeId=linkTypeId&entityTypeId=entityTypeId&collectionName=helloo
````
The parameter that I put are strings.

**Expected behavior**
collectionName should contain the value `helloo` but I got `collectionName=1`. When I tried numeric values it will be displayed successfully however alphanumeric strings are converted to value 1.

**App information (please complete the following information):**

 - Postman Version 6.4.4
 - OS: Windows 10

**Comment by numaanashraf** [comment]
@slim-hmidi I'm afraid I don't your issue. Could you explain with screenshots and sample request?

**Comment by slim-hmidi** [comment]
@numaanashraf 
<img width="795" alt="q1" src="https://user-images.githubusercontent.com/31925861/47153036-a9508800-d2de-11e8-8da5-7e41631b4c5c.PNG">

**Comment by slim-hmidi** [comment]
@numaanashraf  I write: 
```js
const { collectionName } = req.params;
console.log('collectionName: ', collectionName);

collectionName : 1
````
However when I put a numeric value in `collectionName=123245689` I got the same value that I put. The collectionName accepts numeric value and alphanumeric value will be converted to 1.

**Comment by numaanashraf** [comment]
@slim-hmidi is this at your server end?

```
const { collectionName } = req.params;
console.log('collectionName: ', collectionName);

collectionName : 1
```

**Comment by slim-hmidi** [comment]
@slim-hmidi  yes, it is.

**Comment by numaanashraf** [comment]
@slim-hmidi Looks like this might be an issue at the server side. We tried replicating this and Postman sends string values correctly.

<img width="914" alt="screenshot 2018-10-18 at 7 13 03 pm" src="https://user-images.githubusercontent.com/3295568/47158756-f26a0180-d309-11e8-8695-0bb94e130141.png">

**Comment by numaanashraf** [comment]
@slim-hmidi You could also verify the request sent by Postman via the Postman Console (Menu > View > Show Postman Console)

**Comment by TienBui1996** [comment]
I tried adding query parameter as number value and Postman sends that value as string value. How do I can add query parameter as number value?
