### ISSUE TITLE
Folders hierarchy in documentation is not consistent with title hierarchy in markdown

### ISSUE THREAD

**Issue by XaWin** [a85/POSTMan-Chrome-Extension#5386]
**Describe the bug**
When creating folders to create a hierarchy in the documentations, I noticed that all folders have the same markdown/HTML title tag, which is `<h2>`. This breaks the logical hierarchy of

- Collection name -> h1 
- Folder -> h2 
- Subfolder -> h3 (is h2 too now)

**To Reproduce**
1. Create a collection, 
2. Add several folders and nested folders and give them titles
3. Click on "View in Web" to display the documentation
4. Observe that the hierarchy of title formatting do not follow the hierarchy of folders.

**Expected behavior**
- A folders nested at level X should receive a markdown of X+1 (or #x(X+1) )
- Markdown at Level 1 (#), resp. level 2 (##), are already reserved by collection name, resp. first folder level. 
- ~As markdown do not allow for more that 6 levels of hierarchy it may be ideal to also limit the number of nested folders.~

**Screenshots**
N/A

**App information (please complete the following information):**
Not app dependant

**Additional context**
N/A

**Edit 17.12.2018** : strikethrough/remove the part on the part about levels restrictions

**Comment by godfrzero** [comment]
@XaWin Folders can be nested multiple times, and a markdown limitation doesn't seem like a good enough reasoning to limit folder nesting to 6 levels. @vkaegis Any thoughts?

**Comment by XaWin** [comment]
@godfrzero Well, limitations was not the main point. The part "A folders nested at level X should receive a markdown of X+1 (or #x(X+1) )". At the moments, the visual of the folders is imposed on h2 level by default, which is not nice to see.

**Comment by vkaegis** [comment]
@XaWin Thanks for writing in! As @godfrzero mentioned, we wouldn't want to restrict folder levels just to fit in with the markdown hierarchy. That said, I can understand the need for distinguishing levels of nested folders. Marking this as a feature request for the same.

**Comment by XaWin** [comment]
Hi @vkaegis @godfrzero,

Thanks for the feedback. I removed the part on restricting the levels of folders.

I still believe that not propagating the hierarchy of the Postman folders into a proper hierarchy in markdown is a bug and not a feature request. Otherwise, could you please elaborate on the reason for the hierarchy in your Postman interface ?

And whatever the classification, do you have an estimated time for a fix on this feature?

**Comment by XaWin** [comment]
Hi all,
You can close this issue. As a follow-up, the final decision was to move to openAPI, which offer more flexibility.
