### ISSUE TITLE
can't reasonably do a diff on a json.postman_collection that is used on different machines

### ISSUE THREAD

**Issue by ariscris** [a85/POSTMan-Chrome-Extension#539]
Hi,

We are using POSTMan as a testing platform for our API and exported the collection as a json and checked it into SVN.  Unfortunately, if another user loads the collection and then immediately exports it, the id's all change and the order of requests change, so we can't reasonably do a diff to make sure we're only checking in what we intend to check in.  Is there a way around this or a plan to fix this?   We do intend to purchase a few licenses once we're done evaluating this.

Thanks.

Aris

**Comment by konradkiss** [comment]
This issue still persists in Version 2.1.1 (packaged)

The order of requests might be deterministic now, but the diff of an exported collection from two different machines and users includes data that are not related to the collections exported. The diff is full of owner and other id conflicts if there are several people working on the tests at the same time.

**Comment by fractalawareness** [comment]
+1 here, now it's almost impossible to work with the diffs.
And the Postman Activity Feed shows only the person, date and collection name that has been changed, but not the actual changes(which would be awesome).

**Comment by rohitjoshi** [comment]
+1 It has been difficult to modify by multiple team members particularly when it is stored in the GitHub.  My team is thinking to move to different tools as we can't predict if existing test cases are overwritten.
 Any suggestion would be greatly appreciated.
