### ISSUE TITLE
Is there any way to set not to save Cookies? Saved cookies are causing issues while I am trying to run my test suite.

### ISSUE THREAD

**Issue by rajibr79** [a85/POSTMan-Chrome-Extension#5392]
## App Details:

```
Postman for Windows
Version 6.4.4
win32 10.0.17134 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:
 2. Expected behaviour:
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 4. Screenshots (if applicable)

**Comment by vvscode** [comment]
https://www.getpostman.com/docs/v6/sending_and_viewing_responses/interceptor_cookies

**Comment by numaanashraf** [comment]
@rajibr79 This is not supported yet. We are tracking this suggestion at #1228.
