### ISSUE TITLE
SSL certificate verification 

### ISSUE THREAD

**Issue by 241989himjain** [a85/POSTMan-Chrome-Extension#5395]
Please read through the [guidelines](https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues) before creating a new issue.

**Describe the bug**
Option of "SSL certificate verification" is not there in the Postman, earlier it used to have

**To Reproduce**
1. Go to settings
2. Under General section, there is no option for SSL certificate verification 

**Expected behavior**
SSL certificate verification , should be there

**Screenshots**
![image](https://user-images.githubusercontent.com/11737303/47281385-681ae980-d5f8-11e8-886b-6c0075b4c541.png)

**App information (please complete the following information):**
 - App Type [Chrome 69.0.3497.100]
 - Postman Version [5.5.3]
 - OS: [win / x86-64]

**Comment by numaanashraf** [comment]
@241989himjain `SSL certificate verification` is only available on our Desktop apps.

**Comment by numaanashraf** [comment]
@241989himjain `SSL certificate verification` is only available on our Desktop apps.
