### ISSUE TITLE
Duplicate tab warns of 'conflicts' and wont go away.

### ISSUE THREAD

**Issue by phillip-haydon** [a85/POSTMan-Chrome-Extension#5396]
**Describe the bug**
After updating for the first time in... 4 months, I have an annoying popup about conflicts in a duplicated tab that shouldn't appear.

**To Reproduce**
1. Create a request
2. Right click and duplicate tab
3. Modify either tab
4. Get annoying popup about conflicts that doesn't go away cos if you hover near the tab it pops up then disappears then pops up, unable to rename the tab as it renames all duplicated instances of the tab.

**Expected behavior**
I shouldn't be warned about 'conflicts' when I duplicated a tab and made changes to the tab.

**Screenshots**

![image](https://user-images.githubusercontent.com/895629/47282510-2434de00-d612-11e8-8d1d-39876bfc9276.png)

**App information (please complete the following information):**
 - App Type: Native app I think...
 - Postman Version: v6.4.4
 - OS: Windows 10

**Additional context**

**Comment by bpconfigit** [comment]
I have the same issue, when duplicating a tab, it seems that it still works on the same entity, and every change in different tabs, leads to changes in the original entity. 

As a workaround, I have started to duplicate from my collections, and then opening the tabs, which does work (the differences seem to be that the title gets the `Copy` appended when duplicating from the collections, but duplicating from the tabs this doesn't happen)

**Comment by sujayvenaik** [comment]
@phillip-haydon @bpconfigit 
When you duplicate a tab, it is pointing back to the same request. Hence you see conflicts.

Duplicating a tab points to the same request while duplicating a request actually creates a new request.

While debugging this we found another issue in the conflict state flow and are tracking it on a separate issue. (#5692)

Closing this, if you have other issues related to conflict flow, please update the thread of the issue number mentioned above.

**Comment by gardwired** [comment]
I have to say that making duplicate tab not really create a new independent tab seriously violates the "principle of least surprise"  it just isn't intuitive and invites confusion.  simple tabs should work simply. if there is a need to keep them linked then come up with some other name/process that doesn't sound like making a separate copy.  just my 2 cents.  postman is a joy but this makes no sense imho.

**Comment by olsonhost** [comment]
Ditto @gardwired from 2019.

**Comment by cgarrovillo** [comment]
This needs to be reopened.

**Comment by hell-racer** [comment]
This is the single reason I want to downgrade to Postman 7 (from 10).
I never duplicate tabs, never edit requests outside Postman, never use workspaces, and yet I have these Conflicts. I hate this :(.

**Comment by cgarrovillo** [comment]
@sujayvenaik

**Comment by cgarrovillo** [comment]
This issue aside, what are some good alternatives to Postman entirely?

**Comment by phillip-haydon** [comment]
Insomnia

After postman pulled that stunt with the pricing I went Insomnia and never looked back. Its much better.
