### ISSUE TITLE
variable values that are set with collection pre-request script are not replaced/overriden by csv data during iteration run

### ISSUE THREAD

**Issue by roni-magisto** [a85/POSTMan-Chrome-Extension#5397]
**Describe the bug**
I have a collection-level pre-request script that sets a variable (the bug happens even if the script is set at the request-level):

`pm.variables.set('primary_color', '#'+Math.floor(Math.random()*16777215).toString(16));`

in one of my request folders, I have a request that sends the desired variable to the server:

`{ "primary_color": "{{primary_color}}" }`

when I run the request in the editor, all is well - the color variable is set by the pre-request script, and then sent as expected.
when I run the request via the runner, using an external CSV that defines the same variable ("primary_color"), the runner does not use the data in the CSV, but rather it's using the variables set by the pre-request script.
If I comment out the pre-request script, the runner uses the CSV data as expected.

**To Reproduce**
1. Have  pre-request script that sets a variable
2. Have a request that uses that variable
3. Prepare a CSV that provides a different value for the same parameter/variable
4. Run the request using the collection runner 

**Expected behavior**
Runner uses CSV value in iterations instead of value set by pre-request script (or overrides it).

**App information (please complete the following information):**
 - Native App
 - Postman Version 6.4.4 (6.4.4)
 - OS: macOS High Sierra 10.13.6 (17G65)

**Comment by numaanashraf** [comment]
@roni-magisto This is intended. `pm.variables.set` sets variables in a local scope which has more precedence than data variables coming from csv. Ref: https://www.getpostman.com/docs/v6/postman/environments_and_globals/variables#variable-scopes
