### ISSUE TITLE
History in browse view doesn't refresh

### ISSUE THREAD

**Issue by sivcan** [a85/POSTMan-Chrome-Extension#5401]
**Describe the bug**
The history tab in browse view doesn't refresh

**To Reproduce**
1. Send a few requests so that history has some data
2. Switch to Browse View (Cmd + .) 
3. Click on History (You should be able to see the history's data)
4. Switch back to Build View and click on 'Clear All' and clear the history
5. Switch to Browse View and go to History tab
6. Click on 'Refresh'

**Expected behavior**
History should refresh

**Screenshots**
**Build View**

![image](https://user-images.githubusercontent.com/12631777/47291107-16865500-d620-11e8-8961-d5cc4cd5dfca.png)

**Browse View**
![image](https://user-images.githubusercontent.com/12631777/47291117-1ede9000-d620-11e8-9680-05c203475223.png)

**App information:**
 - App Type: Native App
 - Postman Version: v6.4.4
 - OS: macOS Mojave 10.14

**Comment by preethammavin** [comment]
This issue is fixed.
