### ISSUE TITLE
Curl code does not include Auth header

### ISSUE THREAD

**Issue by maclir** [a85/POSTMan-Chrome-Extension#5403]
**Describe the bug**
I have auth setup on my request to use the bearer token and when I want to copy the curl code, it does not include the auth header. It only includes the headers which are explicitly listed under headers.

**App information (please complete the following information):**
 - App Type: Native app
 - Postman Version: Version 6.4.4 (6.4.4)
 - OS: macOS Mojave

**Comment by sujayvenaik** [comment]
Hey @maclir 
I can confirm this as a bug, and have worked out a fix for this internally which will be rolled out with the next release.

Thanks for writing in and reporting this.

**Comment by yo-epicdavid** [comment]
It's not only curl, it's all code generated is missing the Authorization header

**Comment by sujayvenaik** [comment]
Hey @maclir @Snesi 

Thanks for writing in and for reporting this issue.
This issue has been fixed in the latest version (6.5.x) release of the Postman app.

**Comment by Geoff-Janrain** [comment]
This is still happening in version 7.0.9

**Comment by joshavant** [comment]
This is still happening in Version 7.19.1.

**Comment by dawidd6** [comment]
v7.22.1

Issue still occurs.

**Comment by pcimring** [comment]
I am using version 7.25 of Postman (for Mac) - and I do not see an Authorization header for the cURL code that Postman generates. It used to generate this in the past.

PS: My Authorization header IS explicitly listed under the Headers tab.

**Comment by shreys7** [comment]
Can you enable the `New Code Generation mode` from Postman's global settings, and see if this issue still persists? I can see the authorization header added correctly in the curl snippets
![image](https://user-images.githubusercontent.com/20665864/82984054-f47c6200-a00e-11ea-8c14-17a2de8e7a78.png)
![image](https://user-images.githubusercontent.com/20665864/82984093-0f4ed680-a00f-11ea-938a-cfb376698f15.png)

**Comment by developpef** [comment]
Hello,

I have the same issue, with same version of Postman (on Windows). With new and old code generation modes...

**Comment by shreys7** [comment]
Can you provide the detailed steps to reproduce or screenshots so that we can closely debug this?

**Comment by pcimring** [comment]
Thanks, @shreys7 

Actually, I just *disabled* `New Code Generation mode`, and it started to work for me. 

Strangely enough, after switching new mode back on, it seems to work now - but not for all endpoints. (For that matter, old mode does not seem to work all the time either.)

I can't figure out a sequence of steps for it to fail - but I'll try and post some screenshots :)

Working after I switched off the new mode:

![image](https://user-images.githubusercontent.com/6210449/83006298-aff6c380-a01a-11ea-9d77-091cdb6ab1c4.png)

Not working consistently after I switched back to new mode (although it does sometimes work):

![image](https://user-images.githubusercontent.com/6210449/83005039-04993f00-a019-11ea-969d-f995f58b25ac.png)

![image](https://user-images.githubusercontent.com/6210449/83005145-2397d100-a019-11ea-92c7-9ee00db42621.png)

But then I switch back to old mode, and it's not working for that endpoint either:

![image](https://user-images.githubusercontent.com/6210449/83005349-5cd04100-a019-11ea-9e26-5c171ec4f6b0.png)
