### ISSUE TITLE
Deleting a workspace makes associated monitors inaccessible in dashboard

### ISSUE THREAD

**Issue by JP-from-Postman** [a85/POSTMan-Chrome-Extension#5406]
When a workspace is deleted: any monitors that were associated with it still run, but are no longer accessible in the Postman dashboard (https://go.postman.co/me/monitors) and can only be deleted.

Clicking on an "orphaned" monitor in the dashboard lands on an error page specifying that the monitor is not a part of any workspace. This does not appear to be a user-recoverable state via either the Dashboard or Postman API.

**Comment by JP-from-Postman** [comment]
Same issue @Ramyasri1212 reported here: https://github.com/postmanlabs/postman-app-support/issues/5360

**Comment by preethammavin** [comment]
Deleting a workspace now deletes the monitors associated with it now.
