### ISSUE TITLE
Generated cURL uses unselected variables from environment

### ISSUE THREAD

**Issue by maclir** [a85/POSTMan-Chrome-Extension#5407]
**Describe the bug**
When you select **code** to get the curl equivalent of the request, and you are using a variable (e.g. endpoint). If you have multiple variables with the same name but have the lower indexed one unselected, it still uses the one that is positioned in the list, even if it is unselected.

**App information:**
- App Type: Native app
- Postman Version: Version 6.4.4 (6.4.4)
- OS: macOS Mojave

**Comment by numaanashraf** [comment]
This issue has been addressed in the latest version of Postman (v6.7)
