### ISSUE TITLE
Postman Console not launching after switching account

### ISSUE THREAD

**Issue by QAQblinks** [a85/POSTMan-Chrome-Extension#5409]
**Describe the bug**
If the Postman Console is opened while switching account in app, the console disappear and unable to re-open.

**To Reproduce**
1. Open Postman Console
2. Switch account
3. Postman Console disappear and neither the ui button on bottom left nor the opt+cmd+C shortcut is able to re-open it

**Expected behavior**
Postman Console should be able to be open after account switching.

**App information**
 - Native App: 6.4.4 
 - OS: macOS Mojave 10.14

**Comment by numaanashraf** [comment]
Fixed in Postman v7.0
