### ISSUE TITLE
No HTTP response status code displayed on custom error code

### ISSUE THREAD

**Issue by ohbibi-glacava** [a85/POSTMan-Chrome-Extension#5411]
**Describe the bug**

Until v6.3, all http response status code was displayed on Postman
Since 6.4.4, only succes or generic error code ( like 401,404...etc) was displayed. All other status code wasn't displayed.

**To Reproduce**
1. Create a request which return a custom error code ( like 600, 601, 602....)
2. Click on 'Send'
3. Watch de status of the response
4. Search for status information  ... but it was disappeared

**Expected behavior**
Get the HTTP status code returned on GUI

**Screenshots**
![v6 3](https://user-images.githubusercontent.com/31831214/47360254-58ba9f80-d6cf-11e8-9daf-d5aeadde7bad.png)
![v6 4 4](https://user-images.githubusercontent.com/31831214/47360263-5b1cf980-d6cf-11e8-9b13-33dcfb8239a4.png)

**App information (please complete the following information):**
 - App Type Linux x64 native app
 - Postman Version 6.4.4
 - OS: Linux 4.14.78-1-MANJARO x86_64 GNU/Linux

**Additional context**
Confirmed by JP, Product Support, from Postman Team that it seems like a bug

**Comment by sujayvenaik** [comment]
Hey @guillaumelcv 

We have fixed this in the latest v6.5.2
Thanks for writing in and reporting this issue.

**Comment by Dipankar151** [comment]
Error status is not showing in postman v7.27.1. All the error status code should get displayed if the a user fires an incorrect request. Here in the img I fired a GET request instead of POST, hence it should show the 404 ERROR code, which is not being displayed. Please help in this
![image](https://user-images.githubusercontent.com/67973385/86823933-1b689200-c0ab-11ea-8488-9a47291ea3b2.png)

**Comment by arlemi** [comment]
@Dipankar151 You'll only get 404 for endpoints/subdomains of existing domains. In your case it looks like `restapi.demoqa.com` isn't a valid domain name, hence why you're getting ENOTFOUND instead of a 404.
