### ISSUE TITLE
[HELP] Postman data are all gone due to clicking on another version of the app by mistake

### ISSUE THREAD

**Issue by amedhat3** [a85/POSTMan-Chrome-Extension#5412]
Using Mac OS Mojave, Postman Version 6.4.4, I had the application working fine, clicked on an old version of the Postman app (5.4.1) by mistake, then suddenly all of my collections and history are gone, I don't have the sync on, is there any way to get my data back?

If there is no way to retrieve my data back, can you please fix this issue?

**Comment by numaanashraf** [comment]
@amedhat3 Do you have a postman account and is all your data synced?

**Comment by amedhat3** [comment]
@numaanashraf unfortunately no

**Comment by a85** [comment]
We can't back port data any more. Please contact help@getpostman.com for solutions. Closing this for now.
