### ISSUE TITLE
POST request works from browser but not from postman

### ISSUE THREAD

**Issue by bojannyc** [a85/POSTMan-Chrome-Extension#5413]
I have post request (http://localhost:3000/api/customer/new?name=test&addressdf=test)  that works fine from the browser, but POstman returns 404 not found. Any idea?
Note: this is nodejs seneca based service to add a new customer to Mongdb

The GET request (http://localhost:3000/api/customer/list) works fine from Postman

**Comment by numaanashraf** [comment]
@bojannyc You can use the Postman Console to troubleshoot your issue - https://learning.getpostman.com/docs/postman/sending_api_requests/debugging_and_logs#network-calls-with-postman-console
