### ISSUE TITLE
6.4.4 does not load 5.3.2 backups correctly

### ISSUE THREAD

**Issue by kurtkanaskie** [a85/POSTMan-Chrome-Extension#5417]
Upgraded to 6.4.4, local data was purged because I wasn't logged in (separate issue).
Importing backup from 5.3.2 doesn't load correctly, drops collections and almost all raw data for POST requests is gone. My backup is 16 meg.
Going back to 5.3.2 un-synced, really disappointed.

**Comment by numaanashraf** [comment]
@kurtkanaskie We do not recommend going back to 5.x versions after you update to a 6.x version. The data we store locally in your system is not compatible across moving back Postman versions. Please share your backup file to help@getpostman.com and we can take a look at why the 5.x backup is not working correctly for you in 6.x apps.

**Comment by kurtkanaskie** [comment]
I'm using my Oct 1st backup which was done with 5.3.2.
I'm not able to share the file for security reasons.
I'll try to isolated the issue with a subset.
