### ISSUE TITLE
Web documentation view doesn't parse tables if bullet list comes after

### ISSUE THREAD

**Issue by JP-from-Postman** [a85/POSTMan-Chrome-Extension#5419]
User report:

> In Postman v6.4.4 I noticed that tables with bulleted list coming *after* a table are not displayed correctly when viewed in the web. You can see a screenshot attached to the ticket. If the bullets are removed and just text is used it works again. This is a new behavior, but I am not sure what version broke this.
> 
> Example: 
> ``` 
> ## Query Parameters
> 
> | Parameter | Type | Required | Options | 
> | ----------- | --------------- | -------- | -------------------------- | 
> | os | `String` | TRUE | `iOS`, `Android`, `Web` | 
> | version | `String` | TRUE | | 
> | variant | `String` | FALSE | |
> 
> ## Notes:
> 
> * This endpoint does not require an access token. 
> * All string values in the payload are case-insensitive. 
> ```

Support notes:

The above markdown table renders as shown in the attached screenshot. Removing the two bullet points trailing the table allows the table to render correctly.

![postman_wrong_parse_table](https://user-images.githubusercontent.com/43283131/47394560-37aa7c80-d6d8-11e8-9551-8c01e7557eac.jpg)

**Comment by JP-from-Postman** [comment]
Reported by: @rjpcomputing

**Comment by rjpcomputing** [comment]
Any updates on this? There have been a few releases and this is still broken. Any idea when this is going to be worked on?

Thanks.

**Comment by godfrzero** [comment]
Note: Renders correctly in public docs, confirmed as a bug in the private docs.

**Comment by ankit-m** [comment]
A fix for this has been deployed.
