### ISSUE TITLE
Team Workspace showing some of the duplicate collection of my personal workspace

### ISSUE THREAD

**Issue by Ramya-From-Postman** [a85/POSTMan-Chrome-Extension#5423]
Extra collection folders from my Personal workspace are showing up in my Team workspaces until I restart app.

Starting in the Team workspace with a single collection "Collection Before Bug" image. I then move into my personal workspace, where the bug shows some collections duplicated above my favorites. These duplicated collections then show up in every workspace until I restart the app.
I'm running 6.4.4 on windows. 
![image](https://user-images.githubusercontent.com/40994626/47428040-b58d8700-d7af-11e8-8242-312ebebcc3e4.png)

![image](https://user-images.githubusercontent.com/40994626/47428076-cccc7480-d7af-11e8-8a0f-4bdeac529cc3.png)

![image](https://user-images.githubusercontent.com/40994626/47428101-deae1780-d7af-11e8-817b-b5d3a3db1580.png)

**Comment by mattmiddlesworth** [comment]
signing out and signing in has currently fixed this issue for me.

**Comment by mattmiddlesworth** [comment]
The issue came up again since signing out and in. I've sent @Ramya-From-Postman the logs when it happened.

**Comment by abhijitkane** [comment]
@mattmiddlesworth This might be due to ID clashes in the "Postman Echo" collection - can you check if this is solved by asking your team members to remove this collection from their workspaces? This was a legacy collection that we used to insert into Postman to help showcase its capabilities, but isn't needed anymore.

**Comment by mattmiddlesworth** [comment]
@abhijitkane removing the shared collections from my personal workspace and adding them back looks to have fixed the issue. Thanks!

**Comment by numaanashraf** [comment]
@mattmiddlesworth Glad to know this is resolved at your end. We are tracking the root issue at #5494, which would be resolved in the upcoming releases.
