### ISSUE TITLE
Unable to remove card if the payment fails while upgrading to paid plan

### ISSUE THREAD

**Issue by Ramya-From-Postman** [a85/POSTMan-Chrome-Extension#5428]
Hi, 
While upgrading from a free to paid plan, after adding the card details if the payment is failed for some reason. It is not possible to go back & remove the card as it says "I don't have permission to access the billing page. Please fix this behavior.

![image](https://user-images.githubusercontent.com/40994626/47490327-22635880-d866-11e8-8cd8-d1f601c67e73.png)

**Comment by preethammavin** [comment]
Hi,
The issue should not occur now.
