### ISSUE TITLE
Existing Collection request not renaming with changed URL

### ISSUE THREAD

**Issue by chandranmarimuthu** [a85/POSTMan-Chrome-Extension#5429]
Please read through the [guidelines](https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues) before creating a new issue.

**Describe the bug**

**To Reproduce**
1. Go to 'Collection'
2. Click on 'saved request url'
3. Change request URL
4. Click save
5. Request URL changing at back-end, but collection URL need to be rename manually
6. See error

**Expected behavior** http://localhost:53265/api/production/

**Screenshots**
Collection request URL:
![image](https://user-images.githubusercontent.com/11059851/47508273-6a4ba500-d891-11e8-8b2a-300627316972.png)

Actual Saved request URL: ://localhost:53265/api/production/

**App information (please complete the following information):**
 - App Type [e.g. Chrome App, Native App]
 - Postman Version [e.g. 6.0.1]
 - OS: [e.g. macOS High Sierra 10.13.2]

**Additional context**

**Comment by numaanashraf** [comment]
@chandruprakash This is expected. Request names are not tied to request url. We recommend giving meaning names to your requests when saving to a collection.
