### ISSUE TITLE
Request text not wrapping when changing pane size

### ISSUE THREAD

**Issue by gpattersonm** [a85/POSTMan-Chrome-Extension#5430]
## App Details:
```
Postman for Windows
Version 6.4.4
win32 10.0.17134 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there: Recently
 2. Expected behaviour: Request Body tab contents should adjust when changing the Request/Response pane width (two pane view).
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 4. Screenshots (if applicable)
![image](https://user-images.githubusercontent.com/38870103/47520347-2d5dbf00-d84d-11e8-817b-8aa7e1910c8a.png)

**Comment by sivcan** [comment]
Hi @gpattersonm,
We've released a fix for this on our Canary channel: https://www.getpostman.com/canary

Please try it out in the Canary version and let us know if you continue to face the issue.
Will update the thread once we release the fix on our stable channel.

**Comment by sivcan** [comment]
We have released the fix on our stable channel, kindly update your app to the latest version.
