### ISSUE TITLE
on sending post request with json data with multiple global variable json content shown as null

### ISSUE THREAD

**Issue by ajijshaikh** [a85/POSTMan-Chrome-Extension#5432]
PFA collection url - https://www.getpostman.com/collections/e1ca0fb2894cb6390c16

**Describe the bug**
I have created 2 global variables - 1. randomId ,  2. token_name but when  I pass that in the body for  post request then it shows json : "null"

**Comment by numaanashraf** [comment]
@ajijshaikh Could you check the Settings > General > Automatically persist variable values?
