### ISSUE TITLE
Collections and environments lost after upgrate to 6.4.4

### ISSUE THREAD

**Issue by Dil-nlaycock** [a85/POSTMan-Chrome-Extension#5437]
Postman for Windows
Version 6.4.4
win32 10.0.16299 / x64

I normally take the updates quite quickly, so I assume I was upgrading from 6.4.2 - once opened I had no collections or environments. I do not sign into the cloud service.

I have another win10 PC with very similar set of collections and environments which upgraded fine.

**Comment by numaanashraf** [comment]
@Dil-nlaycock Could you open View > Developer > DevTools (Shared) and give us a screenshot of the Console tab there?

**Comment by numaanashraf** [comment]
Hi. With only the details that is currently in the issue, we don't have enough info to take action. I'm going to close this but don't hesitate to reach out if you have any info that'll help us reproduce this issue, we'll be happy to reopen the issue.
