### ISSUE TITLE
Binary file upload sends empty body when using collection runner

### ISSUE THREAD

**Issue by zootyzoot** [a85/POSTMan-Chrome-Extension#5439]
**Describe the bug**
When issuing a POST PUT request with a binary file body, the file is only uploaded when the request is performed stand-alone.
When performed in the context of the collection runner, file size sent is 0kb

1. create a POST PUT request and attach a binary file to the body.
2. save the request into a collection
3. run the collection with postman console and dev tools open --> the request will be sent with empty body.

postman console shows-
Binary file load error: invalid or missing file source

dev tools console show:
Binary file load error: invalid or missing file source runner.js:13469 

**Expected behavior**
The payload to be sent properly.

**App information (please complete the following information):**
 - App Type: Native App  
 - Postman Version: v6.4.4
 - OS: Windows 10 x64 1803

**Comment by abhijitkane** [comment]
@zootyzoot This is a known limitation. As a workaround, you can use Newman to upload files while running a collection - http://blog.getpostman.com/index.php/2014/11/15/using-newman-to-run-collections-with-file-post-requests/

**Comment by abhijitkane** [comment]
Related to https://github.com/postmanlabs/postman-app-support/issues/812

**Comment by GarryLowther** [comment]
We are having the same problem and do not want to have to use Newman as this is just another complication. If file upload functionality works when running from the workspace, it should work in the collection runner AND the monitor. Are you planning on fixing this?

**Comment by saswatds** [comment]
Hi @zootyzoot @TriSysBusinessSoftware 

We had added the support for file in the collection runner in our latest stable Postman app version v7.1.1. You should now be able to run request with form data and binary body within the collection runner.

The support for files in monitoring is something we want to tackle in the future.

Closing this issue now. Feel free to create a new issue if you happen to find any bugs

**Comment by just-jim** [comment]
It seems that this stopped working again in the latest versions of Postman. While running a collection that includes a request with a binary body the file has size 0.

Using:
Version 11.11.1
UI Version: 11.11.1-ui-240903-0426
Desktop Platform Version: 11.11.0 (11.11.0)

**Comment by harshadixit23** [comment]
Hey @just-jim!
We'll look into this! Could you please give us more information about whether the file is in postman working directory, if it has been uploaded to postman cloud?

**Comment by just-jim** [comment]
Hey @harshadixit23 , thanks for the quick reply!
it's not in the cloud, it's a file selected in the postman UI from the local system.
![Screenshot 2024-09-17 at 11 53 11](https://github.com/user-attachments/assets/874f22a7-99f7-4216-ac69-8ca7b26fed90)

**Comment by just-jim** [comment]
Update:
It was becasue the file was outside the working directoy, I selected a file from within the working directory and it worked. But it would be nice as long as the individual request works with a file outside the working directory, when running a runner containing this request to have consistancy and work through the runner as well. It's not obvious why it works when running the request by it self and why it doesn't work when running the request through runner.

**Comment by Guihgo** [comment]
Fix: https://www.youtube.com/watch?v=cE8bUBalPxk

Fix steps: 
1. Postman > Settings > Read files outside working directory : Enable 
2. Rename dir from %LOCAL_USER%/Postman Agent to => %LOCAL_USER%/Postman
