### ISSUE TITLE
Postman corrupted after Chrome upgrade

### ISSUE THREAD

**Issue by marr** [a85/POSTMan-Chrome-Extension#544]
I just upgraded to Chrome 34 stable Version 34.0.1847.116 and Postman lost all its history and collection data as well as there being no way to actually send requests or manage the environment. Is there any way to troubleshoot this? Someone else running the same version said they didnt have an issue .I tried a new profile and reinstalled both the standalone and extension and they both had the same broken behavior.

THanks,
Dave

**Comment by darkstone** [comment]
How can this be closed if the app is still broken?
