### ISSUE TITLE
 XML/SOAP schema validation

### ISSUE THREAD

**Issue by SDixit1** [a85/POSTMan-Chrome-Extension#5441]
Is there any method to validate xml/soap schema.

**Comment by Liz4v** [comment]
Still no?

**Comment by a85** [comment]
You can use custom Javascript in the test script section. We don't have first class support for SOAP.

**Comment by AdemolaAdigun** [comment]
> You can use custom Javascript in the test script section. We don't have first class support for SOAP.

How can i do that, do you have an example i can take a look at?

**Comment by abhijitkane** [comment]
We now support WSDL as an API definition format. WSDL definitions can be authored, and collections/requests validated against them. Read more at https://blog.postman.com/postman-now-supports-wsdl/.

Closing this for now, feel free to open other issues for more specific feature requests :)
