### ISSUE TITLE
DevTools: Current View vs Current Shell vs Shared vs Shared Shell

### ISSUE THREAD

**Issue by dwiyatci** [a85/POSTMan-Chrome-Extension#5442]
## App Details:

```
Postman for Linux
Version 6.4.4
linux 4.15.0-38-generic / x64
```

## Issue Report:
 View->Developer
There are:
1. Show DevTools (Current View).
2. Show DevTools (Current Shell).
3. Show DevTools (Shared).
4. Show DevTools (Shared Shell).

How do the four differ:question: :thinking:

**Comment by numaanashraf** [comment]
@dwiyatci These are debugging tools for multiple processes Postman runs and relies on. Postman runs 6 processes internally, including view processes (for UI), shell processes (for data partitioning and security) and shared (for shared services like sync).
