### ISSUE TITLE
Presets bug autocomplete [object Object]

### ISSUE THREAD

**Issue by xtevezerickx** [a85/POSTMan-Chrome-Extension#5443]
**Describe the bug**
Presets are not correctly displayed when using the autocomplete

**To Reproduce**
1. Create a preset (or use some old preset)
2. Start typing the preset and use the autocomplete (click or use the arrows)

**Expected behavior**
Display the correct preset

**Screenshots**
![01](https://user-images.githubusercontent.com/2366359/47660263-6eb7dc80-db75-11e8-87cf-8cd23559ca02.gif)

**App information (please complete the following information):**
 - Postman for Windows
 - Postman Version 6.4.4
- win32 10.0.15063 / x64
 - OS: Windows 10 Pro 1703 - 15063.1088

**Comment by sujayvenaik** [comment]
Hey @xtevezerickx 
Thanks for writing in and for reporting this issue.
This issue has been fixed in the latest version (6.5.x) release of the Postman app.
