### ISSUE TITLE
Issues with URL contain hyphen

### ISSUE THREAD

**Issue by t-pankajkumar** [a85/POSTMan-Chrome-Extension#5445]
**Describe the bug**
When we try to access an URL which contains '-' it is encoded with some special characters.

**To Reproduce**
1. Go to 'https://payout­-gamma.cashfree.com//payout/v1/authorize'
2. See error

**Expected behavior**
It should not convert the URL to some encoded format

**Screenshots**
![image](https://user-images.githubusercontent.com/8513424/47700080-2236d480-dc3b-11e8-83ac-e68e267f1db4.png)

**App information:**
 - App Type [Native App]
 - Postman Version [6.4.4]
 - OS: [Ubuntu 18.04]

**Comment by codenirvana** [comment]
@t-pankajkumar Can you update your app and confirm if that fixes your issue?
