### ISSUE TITLE
Can retrieve data from browser but not from Postman

### ISSUE THREAD

**Issue by francesco1119** [a85/POSTMan-Chrome-Extension#5446]
Please read through the [guidelines](https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues) before creating a new issue.

**Describe the bug**
If I access this URL from browser I can see the JSON:

http://overpass-api.de/api/interpreter?data=[out:json][bbox];node[amenity=cinema];out;&bbox=7.0,50.6,7.3,50.8

From Postman I receive `Could not get any response`

**To Reproduce**
1. Paste http://overpass-api.de/api/interpreter?data=[out:json][bbox];node[amenity=cinema];out;&bbox=7.0,50.6,7.3,50.8 into Postman and press "Send" --> `Could not get any response`

2. Paste http://overpass-api.de/api/interpreter?data=[out:json][bbox];node[amenity=cinema];out;&bbox=7.0,50.6,7.3,50.8 into a browser --> JSON is there

**Expected behavior**
I always can retrieve data from OSM through Postman with queries like this one: 

http://overpass-api.de/api/interpreter?data=[out:json];area[name="Bonn"]->.a;(node(area.a)[amenity="cinema"];);out;

**Screenshots**

![no response](https://user-images.githubusercontent.com/3397477/47705930-cac15480-dc8c-11e8-9bec-29bd999d02f9.png)

**App information (please complete the following information):**
 - App Type: Desktop App
 - Postman Version: Postman v6.4.4
 - OS: Windows 10 Home

**Additional context**

**Comment by numaanashraf** [comment]
@francesco1119 we are having trouble replicating this at our end. The request succeeds when we send a request to the endpoint mentioned. Could you open Postman Console (View > Show Postman Console), send the request and send us a screenshot of any errors there?

**Comment by francesco1119** [comment]
It now works @numaanashraf .
Not sure why it wasn't working before...
As you can imagine I tried multiple times before opening a ticket with you; you can close it now. Thank you

**Comment by numaanashraf** [comment]
@francesco1119 Glad to hear the issue is resolved at your end.
