### ISSUE TITLE
Docs and application/vnd.api+json

### ISSUE THREAD

**Issue by ash007-postman** [a85/POSTMan-Chrome-Extension#5447]
Currently, postman treats "application/vnd.api+json" as text and causes documentation to look pretty awful. The issue is that the mime type "application/vnd.api+json" isn't seen as JSON.

Are there any plans to map "application/vnd.api+json" to just "json"?

**Comment by hvt** [comment]
This looks like a duplicate of https://github.com/postmanlabs/postman-app-support/issues/2512.

**Comment by preethammavin** [comment]
@hvt yes this is a duplicate, closing the issue do follow the other thread please
