### ISSUE TITLE
Proxy configuration affecting Postman launch

### ISSUE THREAD

**Issue by natarajjk** [a85/POSTMan-Chrome-Extension#5449]
I have tried restarting postman after configuring the proxy settings. Now i can only see empty postman screen, with blinking cursor.

Version : 6.4.4

![postman](https://user-images.githubusercontent.com/33055966/47713545-92a41c80-dc60-11e8-90d1-e05f41ef683f.png)

Note : API which i am testing needs proxy connections.

**Comment by numaanashraf** [comment]
@natarajjk please provide more information on the proxy setting. Is this a system wide proxy config or request proxy config inside Postman?

**Comment by natarajjk** [comment]
> @natarajjk please provide more information on the proxy setting. Is this a system wide proxy config or request proxy config inside Postman?

Hi Numaan - It is system wide proxy, i have some what solved the issue-doing some regex changes, It is working now. but still loading time for post man is slow via proxy.
