### ISSUE TITLE
Github integration sync stopped working

### ISSUE THREAD

**Issue by CloudCray** [a85/POSTMan-Chrome-Extension#5454]
**Description**
Postman no longer syncs to github repo.

Last successful repo sync was Oct 5; has not synced to repo since 6.4.2 release.

Confirmed that app is still syncing correctly with web-based workspace, documentation, and other team members.

Tried with:
- Existing repo, existing collection
- New repo, added existing collection
- New repo, updated old collection
- New repo, new collection

**To Reproduce**
1. Add any collection as a github integration to `XYZ.postman.co/integrations/services/github`
2. Make a change or add request to any of those collections

**Expected behavior**
Expect to see changes to existing collections and new collections to appear in repo

**App information:**
 -  Postman v6.4.4, running native on Windows 10 64-bit

**Additional context**
Running postman in shared team workspace. 
Github repo is private. 
Github Security token is valid (can see all private repos when setting up new integrations) and has proper permissions

**Comment by taylour-k** [comment]
I'm experiencing the exact same issue. I just tried setting up our first integration today and couldn't figure out why it wasn't working.

Postman v6.4.4, running native app on macOS 10.13.6

**Update**: Sync to github began working as expected late this morning.

**Comment by ankitjaggi** [comment]
@CloudCray We found an issue with the Github integrations not working correctly from our end. We released a fix last week, which should have solved any updates not going through to Github. Are you still facing issues with this?

**Comment by CloudCray** [comment]
@ankitjaggi - It's working now; manually updating each collection seems to kick off the sync process

**Comment by maxrichardjr** [comment]
It's doing it again.... I'm updating a particular collection every day, but it's not synching. Strangely, a couple of collections that I rarely use (but did today) updated almost instantly???? Looking at the settings, they are the same except for collection and collection name on GitHub
