### ISSUE TITLE
Export Collections with Environment Configuration

### ISSUE THREAD

**Issue by avles** [a85/POSTMan-Chrome-Extension#5456]
Please read through the [guidelines](https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues) before creating a new issue.

**Is your feature request related to a problem? Please describe.**

In my postman requests, I have parameterized server and port values through Environment Values. If I have multiple environments, it is easy to select an environment and run a test on that environment. But when I need to share this collection with other users, the exported collection does not carry environment values.  Its a pain to recreate those values again in other user's environment.

**Describe the solution you'd like**
There should be an option to create environment values part of a collection.  The user should be allowed to use either Global Env (which you currently have) or collection specific environment. 

**Describe alternatives you've considered**
I don't see any other alternative

**Additional context**
This feature is required in native postman app

**Comment by kamalaknn** [comment]
Have you tried exporting the environment? Is there a particular flow that would be better solved with exporting collections with variables resolved than importing the environment?

**Comment by avles** [comment]
Thanks.  Regarding exporting the environments, the environments in my workspace may not be relevant to the BA who is testing the collection. I would rather prefer keeping the environment definition self-contained with my collection in this case.  Also variables wont help, for example,  my url is like http:{{server}}:{{port}}.   In this case, single variable cannot hold different environment addresses.

**Comment by kamalaknn** [comment]
Ah got it. 

Have you tried variables at collection level? That would contain both the declaration and the values within the collection?

**Comment by m3dbedb** [comment]
It is not said directly, that collection variables are read-only. It would be better to let user edit them.

**Comment by a85** [comment]
Collection variables are editable. Environments and Collections need to be stored separately because of credential issues. Closing this for now. Postman supports multiple export options as well as the ability to collaborate through Workspaces.

**Comment by clairestreb** [comment]
I, too, was looking for this exact same functionality as described by @avles.  I find it disheartening that Postman Support basically said No, and closed the issue.  Without this enhancement, we are forced to deal with multiple files, complicating the end user experience.  Please reopen this issue and enhance the Postman User Experience so we can continue on our Customer Journey.

**Comment by megajulez** [comment]
I too would find this feature useful. It would be great to be able to share a collection, and it could also contain environment related variables. I would like to be able to give the consumers of my APIs a collection and the environments they need would also be imported.

**Comment by josemarquesspirit** [comment]
I receive Postman collections from people that want to show me a problem. It will be very helpful not to have to import environments from all these people. I understand the reason to keep collections and environments separated, but it will be really helpful an option that "flattens" or "merges" a collection with a specific environment, just replacing the variables with the values for the selected environment and then exporting that result.

**Comment by chrisdeso** [comment]
> I receive Postman collections from people that want to show me a problem. It will be very helpful not to have to import environments from all these people. I understand the reason to keep collections and environments separated, but it will be really helpful an option that "flattens" or "merges" a collection with a specific environment, just replacing the variables with the values for the selected environment and then exporting that result.

@josemarquesspirit – Makes sense, there are a few ways to approach this but collection variables are probably the easiest to implement.

**Collection Variables:** 
- https://learning.getpostman.com/docs/postman/environments-and-globals/variables/#variable-scopes
- How-to: https://community.getpostman.com/t/how-do-i-set-a-collection-variable/5466

This will _flatten_ a collection and allow you to resolve variables without needing an environment.

![image](https://user-images.githubusercontent.com/4734306/69745308-94f8d480-1107-11ea-99f7-485afc3b8f92.png)

Here's a collection you can use to see how it works – https://explore.postman.com/templates/4509. I'm happy to augment the functionality so let me know if you have any questions!

**Comment by josemarquesspirit** [comment]
Thank you @chrisdeso for your reply. But I think I'm missing something. The people that send me the collections have several environments defined and they switch between them. When they need to send me a collection with the values of a specific environment, they export the collection and the environment and I also have to import both when I receive them.

If they replace the environment variables in their collections with collection variables, don't they lose the ability to switch between environments when they need it?

If they define 2 variables with the same name (one in an environment and another in the collection), when they export the collection, the variable in the collection will carry the value of the variable in the environment? This is something that I could test on my own, unfortunately I cannot do it right now.

**Comment by bartengine27** [comment]
to export an environment:

- click on the "eye" icon on the right of your environment drop down

- click on "edit" (top right)

- click on "Cancel"

- at the right of each environment in the "manage environments" pop-up, you will find a button on the right which allows to save your environment

**Comment by PPatel0212** [comment]
@josemarquesspirit : When I export the collection with a variable that is defined  in the collection and the environment , I  don't get environment variable value carried over in the export, it's still the collection variable value. I was looking up the option to create environment values part of a collection and came across this discussion thread

**Comment by IanKemp** [comment]
The fact that this was ever closed boggles the mind.

**Comment by acky001** [comment]
Please re-open. Imagine having a collection and 5 environments. You have to import/export the collection and every environment on every change one-by-one, which is not user-friendly and very time consuming. This option is a must in my opinion.

**Comment by ay0ussef** [comment]
I would like postman to introduce secret type along with single file export option that would export a collection with all environments variables and values except secrets.

**Comment by gorkemg** [comment]
Is this feature somehow available now? If not, why is this closed? 
There were multiple good reasons in this thread to have this feature. I have one of these reasons in this exact moment.
