### ISSUE TITLE
Archived Items in Free Team Account can't be deleted 

### ISSUE THREAD

**Issue by eyalzoref** [a85/POSTMan-Chrome-Extension#5457]
**Describe the bug**
We are working in Free Team Account.
We have a team that people have shared collections and all got archived due to usage limit.
I want to delete and leave 2 collections - it should fit the limit, but I can't.

 https://fujiteam.postman.co/usage/archive 

**To Reproduce**
1. Click on https://fujiteam.postman.co/usage/archive
2. See "MyRequests" and "DE-ALL" (duplicated collection)
3. Try to find where to delete the archived items - there is no way
4. Even from the Postman Client - I have a link "ARCHIVED COLLECTIONS" and that's it - it leads to #1

**Expected behavior**
The admin of the team should be able to reduce the stored data in order to continue using the Free Team Account in the limits boundaries.

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version [e.g. 6.4.4]
 - OS: Windows, Chrome Browser 

**Additional context**
Please contact me for assistance: eyal.zoref@amdocs.com

**Comment by a85** [comment]
Hmm. Archiving resets the collection request limit automatically so you can continue using team workspaces.

**Comment by eyalzoref** [comment]
But, it I got to the limit, ot would be helpful to able to open archive and
delete some data so I could continue working with the collected data so far.

בתאריך יום ב׳, 12 בנוב׳ 2018, 03:41, מאת Abhinav Asthana <
notifications@github.com>:

**Comment by a85** [comment]
We discussed this internally and there are no current plans to change this behavior.

**Comment by andersonllda** [comment]
I have the same issue, and this is anoying.

**Comment by fredev** [comment]
Same issue here. Imported a collection from auth0 in a workspace almost full, now all collections are archived and my team cannot use postman anymore...I have to trash my team workspace a recreate it from scratch?

This thing slows down our work today, really annoying.

**Comment by andersonllda** [comment]
> Same issue here. Imported a collection from auth0 in a workspace almost full, now all collections are archived and my team cannot use postman anymore...I have to trash my team workspace a recreate it from scratch?
> 
> This thing slows down our work today, really annoying.

I think this is a try to get more premiums accounts...

**Comment by n0v3xx** [comment]
Same issue here and 5 support tickets later. This problem is fucking annoying and if you dont change this behavior i will uninstall postman and use insomnia forever.

**Comment by n0v3xx** [comment]
https://github.com/postmanlabs/postman-app-support/issues/6054

**Comment by n0v3xx** [comment]
https://github.com/postmanlabs/postman-app-support/issues/6056

**Comment by ozkank** [comment]
I want to delete archived  collections. I see lots of people wants this feauture. So why dont you allow to delete?

**Comment by a85** [comment]
Your archived collections don’t count in your limit.

**Comment by a85** [comment]
If you don’t want to collaborate you can use personal workspaces for free. If you are not ready to upgrade to Pro then we recommend using the Free version. We are pretty clear about the distinction between Free and Pro.

**Comment by ozkank** [comment]
Let me tell about how can I delete my archived collections? There should a
way.
