### ISSUE TITLE
Unsaved Changes Warning Misspelling of "losing"

### ISSUE THREAD

**Issue by haevensk** [a85/POSTMan-Chrome-Extension#5458]
The word "losing" is misspelled as "loosing".

1. Go to a request
2. Attempt to close it out without saving
4. See misspell in the message it gives you

It should be spelled "losing".

 - Native App
 - 6.4.2
 - OS X 18.0.0 / x64

**Comment by numaanashraf** [comment]
@Haeven Thanks for reporting this. This has been fixed in v6.4.4
