### ISSUE TITLE
Save OAuth2.0 New Access Token parameters with collection

### ISSUE THREAD

**Issue by jamakal** [a85/POSTMan-Chrome-Extension#5459]
When exporting a collection, the 'Get New Access Token' headers (found by clicking "Get new access token" in the 'Authorization' tab when the type is OAuth2) are not saved in the collection. This means that a new user importing the collection is unable to generate access tokens unless they enter them manually, and I don't believe there is another way to export these headers in the UI.

![image](https://user-images.githubusercontent.com/11700960/47800223-c3995580-dd23-11e8-8f7d-bbe799b9b74f.png)

Ideally, I believe these should be exported with the collection to allow other users of the collection to request access tokens in the same way.

**Comment by abhijitkane** [comment]
@JamKage Are you referring to the 'Authorization' header that's added to the request?

The client ID/secret aren't saved with the collection - the OAuth2 flow needs user input to get the access token. We're looking at ways to auto-refresh the tokens (https://github.com/postmanlabs/postman-app-support/issues/2452), and we might be able to persist OAuth data to the collection after that.

**Comment by jamakal** [comment]
Hi @abhijitkane, apologies, 'headers' was not the correct term to use - I am referring to the values of all the fields shown in the screenshot above. These do not end up being persisted when the collection is exported.

The problem is that I would like to export all of the field values on the 'Get new access token' screen such that anyone importing my collection will be able to generate new access tokens themselves without them having to manually enter all the values shown in the screenshot.

Hopefully that makes more sense! Thanks for your reply

**Comment by jonathanlarsen** [comment]
This would be a great feature to have!

**Comment by empz** [comment]
We need this feature. Sharing a collection that works with an OAuth2.0 token that needs to be requested by every other member using their own credentials is useless if each one has to manually enter the get new access token settings...

**Comment by mmckenz** [comment]
We've even gone as far as making these values environment variables so they change appropriately as you select different environments.

Now if only 'Token Name' would allow resolving a {{}} environment variable, we could have the token names pre-populated as '{{environmentName}} Token' :)

Regardless, allowing these values to be saved with the collection would avoid requiring others to also enter the variables for each field on this dialog...

**Comment by mdobosz-isp** [comment]
On more vote to persist the parameters in the dialog to the workspace/collection. It seems completely backwards that the parameters are not persisted but the token obtain via the 'New Token' button is.

**Comment by nekator** [comment]
I would like to see this feature in Postman. Would make sharing Collections/Requests with Teams easier.

**Comment by a85** [comment]
Wondering if this can be solved by using Collection variables. Has anybody tried this?

**Comment by tjharrop** [comment]
> Wondering if this can be solved by using Collection variables. Has anybody tried this?

Just tried this and it does work. One thing to note - if you switch between the "Get new access token" screen from the "Authorization" tab and the "Variables" tab, it will appear to recognise the variables but it won't work - you need to click update to commit the variables before reopening the edit screen and trying again.

**Comment by bananaspliff** [comment]
yes but you can't export...

**Comment by tjharrop** [comment]
@bananaspliff Mine exported OK. I exported, changed the name after export to avoid any fortunate conflicts, imported and the variables came with it.

**Comment by bananaspliff** [comment]
it's not a variable problem, it's a template issue.

**Comment by cmplank** [comment]
@tjharrop It saves the variables, but it doesn't save that the variables are used in the collection's GET NEW ACCESS TOKEN dialog. So when someone imports the collection, they have to know to use all of those variables and write them into the dialog.

Ideally, they could import the collection, request a token, and start making calls.

**Comment by utsav-gupta** [comment]
It only seems natural to have this feature , why it's not there such an obvious thing. Is there any alternative to postman which we can use?

**Comment by vikiCoder** [comment]
Hi everyone,

We have made a few changes in OAuth 2.0 helper in the Postman app to address the problems discussed here. These changes are available in the [Postman Canary](https://www.postman.com/downloads/canary/). Please download the latest Postman Canary app and check it out.

See the issue #9056 to know more about the changes. Feel free to leave your feedback at #9056.

**Comment by vvs11** [comment]
@JamKage @jonathanlarsen @eparizzi @bananaspliff @tjharrop @utsav-gupta @cmplank 
Could you try out or Canary build and see if the solution meets your requirements?

**Comment by vvs11** [comment]
Closing this as this is released in App 7.36
