### ISSUE TITLE
ignore duplicate key "//" on json body request

### ISSUE THREAD

**Issue by joneldiablo** [a85/POSTMan-Chrome-Extension#5461]
I would like to be able to disable the validation of repeated keys, specifically the "//" key, to be able to comment on the data that I am sending and to continue validating the rest of the json object

![image](https://user-images.githubusercontent.com/13206502/47814601-bc6a4b80-dd13-11e8-89d9-d619b151cae8.png)

after the _Duplicated key "//"_ nothing is reviewed, for example a missing comma

![image](https://user-images.githubusercontent.com/13206502/47814807-3c90b100-dd14-11e8-9c78-5fa0e6196554.png)

**Comment by pankajk07** [comment]
@joneldiablo We did few changes in the code editor and now the duplicate keys will no longer be reported as an error but will be reported as a warning. Moreover, the complete document will be reviewed and the errors(if any) will be reported.

**Comment by pankajk07** [comment]
@joneldiablo I will be closing this feature request for now. Feel free to create a new request for new features that you would like to see in the app.
