### ISSUE TITLE
Activity Feed's "Restore" action not working

### ISSUE THREAD

**Issue by chrisdeso** [a85/POSTMan-Chrome-Extension#5464]
**Describe the bug**
The **Restore** action within the activity feed isn't working.

**To Reproduce**
1. Open a collection's activity feed
2. Click on 'Restore'
3. See nothing happen

**Expected behavior**
The collection should roll back to a previous state.

**Screenshots**
![image](https://user-images.githubusercontent.com/4734306/47824777-ac5e6600-dd2b-11e8-90b4-640c917a3bf8.png)

**App information (please complete the following information):**
 - App Type: Native
 - Postman Version: 6.5.0
 - OS: macOS High Sierra 10.13.6

**Additional context**
[filed by Postman]

**Comment by rsweis62** [comment]
Another bug i noticed is that the `Last Modified` label is stuck on `Just now` even though the last time something was changed was over an hour ago. Also before the restore button stopped working it deleted half of my requests in my collection.

**Comment by Kurmavathar** [comment]
Similar issue, Where the Restore isn't working. But particularly here **the sync goes offline when clicked upon the restore option.**

**Comment by Raj-postman** [comment]
Native App
App version: 7.0.6
OS: darwin-x64

Similar issue, Where the Restore isn't working. But particularly here **the sync goes offline when clicked upon the restore option.**

**Comment by manoj-makkuboy** [comment]
+1

**Comment by powelli** [comment]
Native App
App version: 6.7.4
OS: macOS High Sierra 10.13.6

+1 This is quite frustrating as it's really common for some of our users to accidentally hit Save when modifying requests for a transient test

**Comment by preethammavin** [comment]
@powelli we are unable to reproduce this, can you try updating to the latest version of the app and trying it?

**Comment by kevin-innorules** [comment]
+1

**Comment by cyrielle-hada** [comment]
@preethammavin this issue is happening for me, clicking on the button `Restore` seems to work only for restoring the whole collection but not the **folder**.

<img width="361" alt="Screen Shot 2019-05-23 at 15 06 28" src="https://user-images.githubusercontent.com/47351631/58259506-96b69980-7d6c-11e9-904e-e1e79700e14d.png">

I managed to reproduce it. You can see the screen recording at this link: https://www.loom.com/share/5c4e64cc4be1490ea0ba3303e9c7d812. 

I am on Version 7.1.1
Mac OS

**Comment by preethammavin** [comment]
@cyrielle-hada when you are click on restore it restores to that instance of the collection , in your case the restore button was clicked on the delete folder it went to a state where the folder was deleted. Which in a UI sense looks like it has not restored we will look at giving a better information there. And when you clicked on the restore on the created part it restored to when the collection was created. 

Activity feed restore works as such

1) change 1
2) change 2
3) change 3

when you restore change 1, then it restores to change 1 after the change 1 was made not before the change 1 was done.
