### ISSUE TITLE
Allow the Run in Postman Button to be disabled on documentation

### ISSUE THREAD

**Issue by chrisdeso** [a85/POSTMan-Chrome-Extension#5465]
**Describe the solution you'd like**
Allow users to disable the run in postman button on published documentation

**Describe alternatives you've considered**
A setting on the documentation page or on the collection level

**Additional context**
[filed by Postman]

**Comment by sankalp0o** [comment]
@chrisdeso Why would someone want to have the button disabled?

**Comment by skcin7** [comment]
I agree. There should be a configuration option somewhere to disable this button if desired.

**Comment by preethammavin** [comment]
@skcin7 any specific reason why you would want to disable the Run button?

**Comment by skcin7** [comment]
@preethammavin I just want to be able to share my API documentation with third-party developers so they can see the list of endpoints which are fully documented. The people I'm sharing this with do not necessarily have or use Postman, there's about a zillion ways to send HTTP requests that don't require Postman, it's unprofessional and bad if your company's official API documentation shows another company's logo/information at the top of it. I can understand this sort of thing for the Free service, but not the paid Postman Pro service. It seems to me like a pretty obvious, no-brainer thing to give people the freedom to turn that button off when they publish their documentation if they choose to, not really that complicated or hard of a thing. It's a pretty huge deal breaker to me if that button is required to be there with no way of turning it off. I don't want that button there. Why would anyone want that button in their official API documentation is a much better question.

**Comment by rahulhada** [comment]
Even we are looking for the same
