### ISSUE TITLE
Additional WebKitFormBoundary in JSON requests

### ISSUE THREAD

**Issue by raynaldgirard** [a85/POSTMan-Chrome-Extension#5467]
I am not able to do a simple POST with postman while it works very well with curl.

Here is my curl that works well:

curl -X POST -H "Content-Type: application / json" -d '{"value": "hi"}' https: // localhost: 44399 / api / values -k

and with postman it gives:

POST / api / HTTP / 1.1 values
Host: localhost
Content-Type: application / json
{"Value": "hello"} ------ WebKitFormBoundary7MA4YWxkTrZu0gW--

and I receive as an error:

{"": ["Unexpected character encountered while parsing value: {. Path '', line 1, position 1."]}

what is "------ WebKitFormBoundary7MA4YWxkTrZu0gW--"?

could anyone tell me why this simple POST does not work please

thank you so much
This is postman version 6.4.4.

![image](https://user-images.githubusercontent.com/5655593/47831348-90c48100-dd66-11e8-9ff5-39e8607b106e.png)

**Comment by harryi3t** [comment]
@raynaldgirard Could you also share the screenshot of the postman console? Is it where you saw the `WebKitFormBoundary7MA4YWxkTrZu0gW--`?
Also, 6.5.2 is out. Please update the App and try this again.

**Comment by raynaldgirard** [comment]
![image](https://user-images.githubusercontent.com/5655593/48349155-708f9e80-e651-11e8-9da5-767185c6080d.png)

Same thing with 6.5.2 version !
Thanks

**Comment by harryi3t** [comment]
@raynaldgirard I didn't realize that the output was from a generated snippet. But that should not affect in any way the request that is actually being sent.
You can open the "Postman Console" to see the actual request being sent out.

Also, this looks like an issue with the local server that is parsing the body. To confirm this you can try sending the same body to a different endpoint like `https://postman-echo.com/post` and see if that returns the body. Can you try this and let us know if that works?

**Comment by raynaldgirard** [comment]
@harryi3t  thanks for your reply. Again, it's working with curl but not with postman
![image](https://user-images.githubusercontent.com/5655593/48484964-92ba2580-e7e5-11e8-8f0f-3fa38f34dfa8.png)

**Comment by raynaldgirard** [comment]
![image](https://user-images.githubusercontent.com/5655593/48485311-7cf93000-e7e6-11e8-8aa4-74941f15459e.png)

**Comment by raynaldgirard** [comment]
for your echo service, it seem not able to use my Windows identity because I have error 407 on the proxy
![image](https://user-images.githubusercontent.com/5655593/48485626-55569780-e7e7-11e8-8caf-38d9c7e9ba3b.png)

**Comment by ushnr** [comment]
Same happens to me as well. One thing I've noticed is, this only happens with an https endpoint. For testing purposes, same service exposes another http endpoint and same request works fine with that. When I switched to https, Postman seems to be adding an unexpected "------WebKitFormBoundary..." line at the end of JSON body.

**Comment by ushnr** [comment]
> Same happens to me as well. One thing I've noticed is, this only happens with an https endpoint. For testing purposes, same service exposes another http endpoint and same request works fine with that. When I switched to https, Postman seems to be adding an unexpected "------WebKitFormBoundary..." line at the end of JSON body.

I have to correct one thing; it seems same line is also added to http request, too. But somehow http interface ignores that line while https responds back with 400.

**Comment by harryi3t** [comment]
@raynaldgirard Looks like you have an authenticated proxy in between which we do not support as of now.
There's an open feature request here https://github.com/postmanlabs/postman-app-support/issues/3566
Please upvote/subscribe to this issue for any future updates.

**Comment by mearns** [comment]
I'm not having any issues making requests, but I do see the same thing in the "HTTP" code snippet:

```
POST /xxx/yyy/ HTTP/1.1
Host: dev01.example.net
Content-Type: application/json
cache-control: no-cache
Postman-Token: ********-76c8-48c1-a262-************
{
	"streams": [
		{
			"streamName": "test",
			"datapoints": [
				{
					"timestamp": "2020-01-08T00:00:00Z",
					"value": 50
				}
			]
		}
	]
}------WebKitFormBoundary7MA4YWxkTrZu0gW--
```
