### ISSUE TITLE
Token Generator issue

### ISSUE THREAD

**Issue by TikunAPI** [a85/POSTMan-Chrome-Extension#5470]
I have three APIs to access to retrieve data from a platform. Before hitting these APIs, I need to generate a Token by calling another API and the same Token will be used in all API calls as Bearer Token. I too have tried OAuth 2.0; but the main problem arises when the token expires.

When I call the whole collection, I have to manually insert the new Bearer Token in each API.

Hence, I am trying to find a solution where in the token is automatically feed to all APIs.

**Comment by TikunAPI** [comment]
For Token Generator:
Auth:
Baisc Auth
Username/Passoword
Headers:
Content-Type = application/x-www-form-urlencoded
Body:
raw
grant_type=client_credentials

For API (POST) calls:
Auth: 
Type: Bearer Token 
Body:
raw
application/json

**Comment by harryi3t** [comment]
@TikunAPI You can use [variables](https://www.getpostman.com/docs/v6/postman/environments_and_globals/variables) for this purpose

Depending on the use-case, you can put the variable having the token in environment, globals, or collection variables.
After this, you just need to update the token once and then all the requests can use the same token.
