### ISSUE TITLE
Crash On Timing Out Endpoint

### ISSUE THREAD

**Issue by tparikka** [a85/POSTMan-Chrome-Extension#5471]
When connecting to a SOAP endpoint and making a request that times out on the server side, Postman crashes:

Crashing Application: C:\Users\tparikka\AppData\Local\Postman\app-6.4.4\Postman.exe

Exception: Unhandled exception at 0x00007FF6C983590B in Postman.exe: 0xC0000005: Access violation writing location 0x0000000000000000. occurred

1. Make a POST request to a SOAP 1.1 endpoint where the request times out on the server. In my environment this is a legacy ASMX-based SOAP service.
2. Wait for the request to try to process
3. Postman times out and then crashes

**Expected behavior**
I expect Postman to not crash, and possibly to return an error stating either that the endpoint timed out or Postman's internal timeout limit was reached.

**App information (please complete the following information):**
 - App Type - Native App
 - Postman Version 6.4.4
 - OS: Windows 10 x64 Version 1709

**Comment by shamasis** [comment]
@tparikka we've made some changes over the past few months. Can you check if you can reproduce this issue on latest Postman v7.x app?

**Comment by tparikka** [comment]
I'm on Postman 7.0.9 Windows 10 Build 1809 and I'm not able to reproduce the issue by holding a request captive in a proxy like Burp Suite.

**Comment by a85** [comment]
Thank you @tparikka. Closing this.
