### ISSUE TITLE
Upgraded to Postman 6.4.4 on Mac. Responses are not shown anymore

### ISSUE THREAD

**Issue by seperman** [a85/POSTMan-Chrome-Extension#5472]
**Describe the bug**
Send any JSON POST or GET request, response is not shown.

**To Reproduce**
1. Send a POST request or GET request with body type of json.
2. Doesnt show anything in return
3. This happened as soon as I upgraded to 6.4.4 a few minutes ago. Restarting the postman app didn't help.

**Expected behavior**
Show responses.

**Screenshots**
<img width="1367" alt="screen shot 2018-11-01 at 11 39 13 pm" src="https://user-images.githubusercontent.com/2314797/47897618-bff2f500-de2f-11e8-9a2c-08e15becbfab.png">

**App information (please complete the following information):**
 - App Type Native App
 - Postman Version 6.4.4
 - OS: MacOs High Sierra 10.13.6

**Additional context**

**Comment by sujayvenaik** [comment]
Hey @seperman 
This seems weird and should not happen.

Can you hit the same request with cURL and check the response?
Also, can you check in the Postman Console when you send the request for response body?

**Comment by seperman** [comment]
@sujayvenaik I just upgraded to Mac OS Mojave and it works again.
Thanks/
