### ISSUE TITLE
Window: Title Bar Style

### ISSUE THREAD

**Issue by ghost** [a85/POSTMan-Chrome-Extension#5473]
### Describe the solution you'd like
**Postman** should have a custom style title bar! This will underline application appearance. Also the app will not look like a "template electron app".

![vs-code](https://user-images.githubusercontent.com/30025319/47917713-a0e57900-deaa-11e8-9570-8dc9e3a088aa.PNG)
![github-desktop](https://user-images.githubusercontent.com/30025319/47917716-a3e06980-deaa-11e8-9c1e-b0669d6d7e9e.PNG)
![postman](https://user-images.githubusercontent.com/30025319/47917717-a642c380-deaa-11e8-9fe4-c0182edf99b2.PNG)

**Comment by rawvoid** [comment]
Hi, @jviotti @numaanashraf 

Are there new plans for this feature? I'm looking forward. Thanks

**Comment by jviotti** [comment]
Hey @aomsweet ,

Yes, there are! We have some internal designs going on and hopefully we can pick this up soon :)

**Comment by rawvoid** [comment]
> Hey @aomsweet ,
> 
> Yes, there are! We have some internal designs going on and hopefully we can pick this up soon :) 

Wow, great, I've been waiting for this for a long time. Thanks.

**Comment by vkaegis** [comment]
Hey folks, this is now available on the desktop app on MacOS and Windows.
