### ISSUE TITLE
Udeletable "My Workspace"

### ISSUE THREAD

**Issue by phramusca** [a85/POSTMan-Chrome-Extension#5477]
## App Details:

```
Postman helps you develop APIs faster
Postman for Windows
Version 6.3.0
win32 10.0.14393 / x64
```
Note that I have update notifications (6.4.4 (Latest) and 6.4.2) but when I click on Update button, I get a "You are up to date! Postman v6.3.0 is the latest version." popup.

## Issue Report:
After having created an account and logged into PC2, then PC1, on PC1, a new "My Workspace" got added with collections from PC2. 
Problem is now on PC1, I have 2 "My Workspace". Only one is synced and available in my cloud account. When I try to delete the original (local ?) workspace, I get a "Error in deleting workspace: Instance not found in the database.". I can't rename it neither. I can't delete history neither: it does not raise any error but nothing is deleted.
How can I do ?
Thanks

**Comment by preethammavin** [comment]
@phramusca can you signout of the account and sign-in again and let us know if the issue persists. Also would suggest to take a backup of the data before you do that.

**Comment by sankalp0o** [comment]
@phramusca are you still seeing this issue?

**Comment by sankalp0o** [comment]
Closing this issue in favor of #4862, looks like the same issue of duplicate "My Workspace" created during sign up.
