### ISSUE TITLE
Show response code on example requests

### ISSUE THREAD

**Issue by obayit** [a85/POSTMan-Chrome-Extension#5478]
Simply show the http response code like it is shown on normal requests.
when the request is set as an example it doesn't show

**Comment by numaanashraf** [comment]
@obayit Could you provide a screenshot to clarify your issue? Examples support response codes:
<img width="1124" alt="screenshot 2018-11-05 at 8 20 54 pm" src="https://user-images.githubusercontent.com/3295568/48024362-61cc5780-e138-11e8-9bb5-88597bebdf5f.png">

**Comment by SamvelRaja** [comment]
@obayit  We are closing this issue for now for inactivity. Feel free to re-open this.
