### ISSUE TITLE
Option to disable useragent header

### ISSUE THREAD

**Issue by cloverzrg** [a85/POSTMan-Chrome-Extension#5484]
I need post a json without useragent,but when i unset useragent,postman will add a useragent, and when i add useragent in headers, the value is "",but not null.

**Comment by appurva21** [comment]
Hey @cloverzrg, in the latest version - `v7.21.0` of the App we have improved the experience around the headers that are automatically added by Postman. So to meet your use case here,
 you can go to the Headers tab and disable the `User-Agent` header by unchecking its checkbox.

![disable-user-agent](https://user-images.githubusercontent.com/24985700/77505319-d23c5b80-6e88-11ea-9a7f-c083943fba8a.gif)

For more info, please go through [this](https://learning.postman.com/docs/postman/sending-api-requests/requests/#auto-generated-headers).
