### ISSUE TITLE
Azure AD Microsoft Graph - You can't get there from here - Windows 10 Extension Chrome 

### ISSUE THREAD

**Issue by isa56k** [a85/POSTMan-Chrome-Extension#5485]
**Describe the bug**
I am trying to read out some o365 calendar data from the Microsoft graph. It appears our domain admins have a policy in place to prevent Chrome from accessing corporate resources without the "Windows 10" extension installed.

**To Reproduce**

1. Under Authorization tab set to Type to "OAuth 2.0"
2. Select "Get Access Token"
3. Configure all parameters required for Micorsoft auth. 
4. Set Grant = Authorization Code  
5. Set Client Authentication = "Send client credentials in body"
4. Request Token, Browser window opens and prompted to enter Microsoft account details and password.

I believe there is probably some policy configuration required within AAD in order to prevent the native Chrome browser from accessing the required resources without the Windows 10 extension installed.

I can't figure a way to install the required Windows 10 extension into the postman app. I've tried installing the postman chrome app but this didn't seem to help. Windows 10 Accounts Extension for Chrome: 
https://chrome.google.com/webstore/detail/windows-10-accounts/ppnbnpeolgkicgegkbkbjmhlideopiji?hl=en

**Expected behavior**
Authentication completes, and token is received.

**Screenshots**
![youcangetthere](https://user-images.githubusercontent.com/1851812/48055585-d9859b00-e1a7-11e8-87a3-a5a5a3e9f4f2.png)

**App information (please complete the following information):**
 - App Type Chrome App
 - Postman Version 6.4.4
 - OS: Windows 10

**Additional context**
It's probably possible to adjust policies in AAD to remove this but would be good if Postman could work with the chrome extension required (Windows 10 Accounts):
https://chrome.google.com/webstore/detail/windows-10-accounts/ppnbnpeolgkicgegkbkbjmhlideopiji?hl=en

**Comment by numaanashraf** [comment]
We recommend reaching out to the wider Postman Community (https://community.getpostman.com/) for help with this issue.

Issue Guidelines: https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues
