### ISSUE TITLE
only /workspaces erroring

### ISSUE THREAD

**Issue by g0rd** [a85/POSTMan-Chrome-Extension#5488]
**Description**
/workspaces endpoint throws ESOCKETTIMEDOUT error

**Expected behavior**
Running /environments or /collections works fine with but /workspaces gives this error.

**App information (please complete the following information):**
 - Native App
 - Postman Version 6.4.4
 - OS: MS Windows 10 Pro 64 bit

**Comment by ankitjaggi** [comment]
@g0rd We found the issue which was causing this. We'll release a fix for this soon and I'll let you know once that happens.

**Comment by ankitjaggi** [comment]
@g0rd We fixed the issue on our end. Can you verify if it's working now?

**Comment by g0rd** [comment]
@ankitjaggi it works. closing the issue
