### ISSUE TITLE
Query string values missing from console entry expanded display

### ISSUE THREAD

**Issue by christopherabrooks** [a85/POSTMan-Chrome-Extension#5489]
Postman console does not include query string in expanded detail view of log entries.

For example, a request such as "https://www.google.com/search?q=postman" is represented in the expanded console Raw entry as:  "GET /search" without the query string.

**To Reproduce**
1. Start Postman
2. Start Postman Console
3. Create new request definition tab, and paste this into the request URL:
    "https://www.google.com/search?q=postman"
4. Click Send
5. Switch to console and observe the console entry for this request
6. Expand the request, switch to Raw view, and look at first row of detail displaying "GET /search" but not displaying "?q=postman"

**Expected behavior**
Expect first row of detail to include query string, i.e. "GET /search?q=postman"

 - App Type: Native App
 - Postman Version:  Postman for Windows, Version 6.4.4
 - OS: win32 10.0.17763 / x64

**Comment by numaanashraf** [comment]
Fixed in Postman v7.0
