### ISSUE TITLE
Exporting data from Workspace

### ISSUE THREAD

**Issue by Ramya-From-Postman** [a85/POSTMan-Chrome-Extension#5491]
it would be very useful to have the ability to export workspaces. Currently, you can export collections or the entire account. Seems the missing piece is being able to export a workspace.

**Comment by a85** [comment]
Workspaces have data objects that are not exportable. We recommend using invitation flows to collaborate on workspaces.

**Comment by indrajeetgour** [comment]
On the free version, we only have just one share for any workspace.

**Comment by ackvf** [comment]
Which data it is that are not exportable?

**Comment by clivecorbishley** [comment]
Even if it just did a batch of all the individual collections and excludes those non-exportable data objects, I would find this useful.

It's currently a click safari, especially if you have opted to have a lot of collections.
