### ISSUE TITLE
When switching team workspaces, collections are duplicated

### ISSUE THREAD

**Issue by pfazzino** [a85/POSTMan-Chrome-Extension#5494]
When switching team workspaces, collections are duplicated.

Postman client 6.4.4. on Ubuntu 18.04.

See video - https://www.dropbox.com/s/fbitfr4rqvw03gg/postman.mp4?dl=0

**Comment by numaanashraf** [comment]
Thanks for reporting this @pfazzino. We have identified the issue and would be rolling out the fix in the coming releases.

**Comment by kamalaknn** [comment]
This issue has been fixed in Postman 6.7.1
