### ISSUE TITLE
Make environment variable editing easier

### ISSUE THREAD

**Issue by simonvane** [a85/POSTMan-Chrome-Extension#5495]
- allow edit popup to be resized in all directions
- allow copying to another environment so that when I'm setting up a local, dev. stage etc. I don't make typos or have to open and close environments (allow value change on copy)
- allow environment variables to be grouped (e.g. by application in an environment)
- allow variables to be renamed across environments and usages i.e.. in environments, api paths, tests etc.

**Comment by vkaegis** [comment]
@simonvane Thanks for writing in! We're actively working on a bunch of improvements around working with variables, so watch out for those in the coming versions. That said, have your tried using Find and Replace to rename variables across environments? Just hit Cmd + Shift + F to try it out.

**Comment by simonvane** [comment]
Thanks, that's great to hear. I wasn't aware of the find functionality. That's looks really helpful. 

I'm using Windows. I've found the Find functionality using Ctrl + Shift + F and that finds everything. Is replace a manual process that this helps with or is there a way to replace as well. I couldn't see a way to do it.

It would be really helpful if the find was shown in the Edit menu to make it more discoverable.

**Comment by simonvane** [comment]
Ignore the replace question. I wasn't on the latest version. I've updated to v6.5.2 and the replace is there.

**Comment by vkaegis** [comment]
@simonvane Perfect! I'll keep this issue open as a feature request for the other points you raised.

**Comment by simonvane** [comment]
Just to reiterate in case it got missed, it would be really helpful if Find and Replace was shown in the Edit menu to make it more discoverable.

**Comment by giridharvc7** [comment]
Please let us know if you face the problems with the latest update of postman, v8.1
