### ISSUE TITLE
Incorrect warning being displayed when request URL & name are edited at the same time

### ISSUE THREAD

**Issue by Ramya-From-Postman** [a85/POSTMan-Chrome-Extension#5497]
**Describe the bug**
When you edit the request name & URL at the same time & hit save, it should ideally save the changes, instead, it displays a conflict warning as shown below which is irrelevant.

**To Reproduce**
1. dirty the request by editing the URL & name then click on save.

**Screenshots**
![image](https://user-images.githubusercontent.com/40994626/48137117-5a878400-e2c7-11e8-8d2e-01c1fe8038e1.png)

**Comment by sujayvenaik** [comment]
@Ramya-From-Postman  This issue is fixed in the latest v6.7.1.
