### ISSUE TITLE
GitHub integration: Delay in changes to test/pre-request scripts showing in repo

### ISSUE THREAD

**Issue by JP-from-Postman** [a85/POSTMan-Chrome-Extension#5498]
(user reported)

**Describe the bug**
When using the Postman-GitHub integration, there is a significant delay (from minutes to hours) in edits to pre-request and test scripts being reflected in the repo.

Changes to the following request properties appear to sync in more-or-less realtime:
- URL
- Headers
- Params
- Body

When changes are made to a script, and then to (e.g.) the request URL, the URL change will actually be reflected in the .JSON file prior to the script edits.

**To Reproduce**
1. Use GitHub integration to sync a Collection (ideally that already has script contents) with a GitHub repo
2. Make changes to URL, headers, params, body
-> See these reflected immediately in .JSON file in repo
3. Make changes to either test or pre-request scripts
-> See these take much longer to show in .JSON file

**Expected behavior**
All changes are synced in (more-or-less) realtime

**App information (please complete the following information):**
 - App Type: _Native App_
 - Postman Version: _6.4.4_
 - OS: _macOS High Sierra 10.13.6_

**Comment by kartikjain26** [comment]
As per the testing done for this task, changes in any of the fields in  collections where almost immediate in github. Let us know if more users report such an issue.
