### ISSUE TITLE
Pro Team: Team members report not being able to join workspaces, or publish collections

### ISSUE THREAD

**Issue by JP-from-Postman** [a85/POSTMan-Chrome-Extension#5499]
**Describe the bug**
User report:

Members of Postman Pro team encounter an error message when attempting to join team workspaces. Issue appears to affect all team members.

<img width="458" alt="edited" src="https://user-images.githubusercontent.com/43283131/48168569-93fac800-e2a4-11e8-8aee-43da1fc73aad.png">

Members also report being unable to publish collections. Unknown if this is related.

**_UPDATE: 11/9/18_**

Team now reports that after the issue disappeared temporarily, now when attempting to join a workspace the `Join` button is non-responsive:

<img width="693" alt="screen shot 2018-11-09 at 1 24 13 pm" src="https://user-images.githubusercontent.com/43283131/48290966-93d80500-e429-11e8-98f2-72805051ad19.png">

**To Reproduce**
Unknown

**App information (please complete the following information):**
 - App Type: _Native_
 - Postman Versions: Various (6.5.0 - 6.0.10)
 - OS: macOS

[filed by Postman]

**Comment by abhijitkane** [comment]
Additional details: The team has 76 members. The workspace has 46 collections, 4 envs, 2 integrations, and 37 members.

**Comment by ankitjaggi** [comment]
@JP-from-Postman The workspace join issue has been fixed from your end. Can you verify if it works now?
