### ISSUE TITLE
Updating postman appears as though it did not update

### ISSUE THREAD

**Issue by allyn-psyonix** [a85/POSTMan-Chrome-Extension#5500]
**Describe the bug**
Initial version: **6.4.4**
Latest available: **6.5.2**
When attempting to update Postman via "Help -> Check for Updates", Postman indicated that 6.5.2 was available. After choosing the option to update it appeared to not update. The app remained open and presented a popup indicating "You are up to date! Postman v6.4.4 is the latest version." This contradicted the earlier note saying 6.5.2 is the latest available. I attempted the update a few times and was presented with the same "6.4.4 is the latest" message each time (I did not restart Postman yet, nor was it auto-restarted). After restarting Postman the version shown was then 6.5.2 and it appears to have updated properly. After speaking with support it sounds like Postman is supposed to auto-restart after updating rather than presenting the popup I was presented with.

I have not attempted to downgrade to reproduce the issue, so I am not sure if this is a rare one-time bug or a common occurrence.

**To Reproduce**
1. Select "Help -> Check for Updates"
2. Select the option to update
3. Postman presents popup indicating that the pre-update version is the latest and does not appear to have updated.
4. Restart postman
5. Go to "File -> Settings -> About" to verify that Postman has indeed now been updated.

**Expected behavior**
Based on my chat with support, it sounds like the expected behavior is for Postman to auto-restart after updating, rather than displaying the misleading popup that I experienced.

**Screenshots**
Unfortunately I do not have any screenshots of the errant message.

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version: 6.4.4 (pre-update), 6.5.2 (targeted update version)
 - OS: Windows 10 Pro

**Additional context**
None

**Comment by allyn-psyonix** [comment]
Given that Postman does appear to have updated successfully this seems to be a minor issue; just the popup and lack of auto-restart are misleading.

**Comment by claudiodangelis** [comment]
The homepage link to latest release points to version 6.4.4: https://dl.pstmn.io/download/latest/linux64 
```
$ curl -s -I https://dl.pstmn.io/download/latest/linux64 | grep 'filename'
content-disposition: attachment; filename=Postman-linux-x64-6.4.4.tar.gz
```

Might be related to this issue?

**Comment by preethammavin** [comment]
@allyn-psyonix we roll out our versions in a staged manner, hence you might have found a rare time where it was switching between rollout and paused. We will look into making the experience better
