### ISSUE TITLE
Postman wont start for user in domain

### ISSUE THREAD

**Issue by rejas** [a85/POSTMan-Chrome-Extension#5501]
**Describe the bug**
Trying to install the latest (6.4.4) version of postman since the chrome app will be retired soon 

**To Reproduce**
1. Run installer on Win10

**Expected behavior**
Installer runs through and opens postman automatically. This works when I run as a local Administrator. Files are installed into the Admins AppData/Local/Postman dir though, which I cann use as user registered to a domain

**Screenshots**

**App information (please complete the following information):**
 - Native App
 - 6.4.4
 - OS: Win10 1809

**Additional context**
When running the setup as a local user the files are installed but the app wont start (not even a splash screen), no desktop icons are created. Starting the app from the console doesnt even throw a exception like in other tickets, nothing happens. 

Install log:
[SquirrelSetup.log](https://github.com/postmanlabs/postman-app-support/files/2562484/SquirrelSetup.log)

**Comment by SamvelRaja** [comment]
Could you check whether the app got installed in `C:\Users\[USER]\AppData\Local\Postman` folder?
Also, kindly check the user has access to `C:\Users\[USER]\AppData\` and `C:\Users\[USER]\AppData\` folders

**Comment by rejas** [comment]
Yes, the app got installed into that folder. User permissions are set also. Like I wrote: When I switch to a local admin account it works (installing ADN running Postman). But as my normal user I cannot start Postman.exe Are there any logs where program starts are logged that I could send you?

**Comment by rejas** [comment]
Had our IT guys re-install my laptop from the ground up due to other issues as well.
