### ISSUE TITLE
Ability to change a test script and run it again on the same response body

### ISSUE THREAD

**Issue by adeane43** [a85/POSTMan-Chrome-Extension#5504]
Many times when writing a test script, I make typos or syntax errors that cause the script to fail. Since in the current version of the application you must send an entirely new request in order to ensure your test script is error-free, this usually ends up with me sending about 5 or 6 different calls for each new test that I write. 

What I would like is the ability to rerun the test script for a request on an already received request body, preferably with a separate button, without having to resend the entire call. This way, the development of a test script would only require one request to be sent to an endpoint.

**Comment by metaclic** [comment]
Same issue. It would be great to rerun "Pre-request Scripts" and "Tests" appart from the sending. Maybe placing a button into a new bar menu, like body response does.
