### ISSUE TITLE
Toggling sidebar via keyboard doesn't change 'Show/Hide Sidebar' button state

### ISSUE THREAD

**Issue by richbowen** [a85/POSTMan-Chrome-Extension#5505]
**Describe the bug**
When the sidebar is toggled via the keyboard shortcut; `Ctrl+\`; the 'Show/Hide Sidebar' button icon doesn't change state (i.e. whatever changes the active/inactive color for the button doesn't get triggered).

**To Reproduce**
1. Click `Ctrl+\` to toggle the sidebar
2. Observe the 'Show\Hide Sidebar' button at the bottom left, it's color changes when it is clicked but not when toggled by the keyboard shortcut
3. Click the 'Show\Hide Sidebar' button and observe the icon color for the desired behavior

**Expected behavior**
When toggled via the keyboard shortcut, the button state changes as it does when it is clicked.

**Screenshots**
![screenshot_20181108_164312](https://user-images.githubusercontent.com/5672238/48229275-aa248900-e375-11e8-9132-40069401a108.png)
The screenshot shows the 'Show/Hide Sidebar' button with the 'active' color even though the sidebar is hidden. The sidebar was hidden via the keyboard shortcut.

**App information (please complete the following information):**
 - App Type: Native App (assuming you mean the Electron App)
 - Postman Version: 6.5.2
 - OS: Arch Linux 4.18.16-arch1-1-ARCH

**Comment by numaanashraf** [comment]
Fixed in Postman v7.0
