### ISSUE TITLE
Response alternates between statuses 401 and 200

### ISSUE THREAD

**Issue by JP-from-Postman** [a85/POSTMan-Chrome-Extension#5507]
(User reported)

**Summary**
Response alternates between statuses 401 and 200 every other time the request is sent, but only via the Postman client.

Same request via cURL works without issue.

[filed by Postman]

**Comment by numaanashraf** [comment]
@JP-from-Postman Do we have a sample request we can use to replicate this issue?

**Comment by a85** [comment]
No way to replicate this issue.
