### ISSUE TITLE
Left panel missing URLs for all endpoints (collection)

### ISSUE THREAD

**Issue by shadyyx** [a85/POSTMan-Chrome-Extension#5510]
**Describe the bug**
After downloading the latest version of Postman for Ubuntu 18.04 x64 and adding a collection of endpoints through importing a `swagger.yaml` file, I do not see any URL in the left panel. I tried changing the default light theme to dark, collapsing and expanding the collection, collapsing and expanding the left panel with no change.

**To Reproduce**
I am not sure if the same steps will reproduce the problem, nevertheless here the steps I did:
1. Download Postman for Ubuntu x64 and extract it to your desired destination
2. In the `Postman` folder, open the console and execute `sudo chmod +x postman`
3. I then dbl-clicked the executable which started the application
4. In the app I closed the welcome wizard and clicked on the _Import_ btn right to the _New_ btn on the top menu
5. Here I selected my `swagger.yaml` in the first _Import File_ tab
6. This created a new collection with the result as on the screenshot
7. Checking with the dev tools, there is no content generated at all where the URLs (text) should be - just empty `<div>`

**Expected behavior**
Obviously the endpoint URL should be present and readable for each endpoint and each method as is described in the `swagger.yaml` file

**Screenshots**

**App information (please complete the following information):**
 - Native App
 - Postman Version 6.5.2 (just did the update with no change)
 - OS: Ubuntu 18.04 x64 with Unity desktop

**Comment by harryi3t** [comment]
@shadyyx Thank you for reporting this bug. Could you post some screenshots showing this issue? Also, if possible, please share a sample swagger.yml file which while importing re-produces this issue consistently.

**Comment by shadyyx** [comment]
Sorry, I forgot to attach the screenshot - here it is ![screenshot](https://user-images.githubusercontent.com/1033137/48255851-2a96c880-e40e-11e8-826f-0e1ce1c3c06c.png)

A sample swagger that can be used to reproduce the problem is attached here as well.
[test-swagger.zip](https://github.com/postmanlabs/postman-app-support/files/2565459/test-swagger.zip)

**Comment by shadyyx** [comment]
I can confirm the left panel displays the URLs properly when created directly through Postman (New collection -> New Request -> giving a proper name).

I also can confirm the endpoints imported from `swagger.yaml` do not have their names filled in at all, as by editing such and endpoint and giving it a name - proper URL (which is empty in the edit modal window) displays that URL correctly in the left panel.

**Comment by harryi3t** [comment]
@shadyyx I just checked the behavior with multiple old versions of Postman.
Seems like in version 5.x, the URL was being used as the request name, which is not used after version 6.x

This is a screenshot taken on v.5.5.3 with your collection
<img width="303" alt="postman" src="https://user-images.githubusercontent.com/5207331/48313706-376e1480-e5e6-11e8-8827-d437fc8681c8.png">

Looking at the [actual code that converts a swagger file to postman collection](https://github.com/postmanlabs/swagger2-to-postman/blob/develop/convert.js#L219), looks like the correct field to use for a request name is `summary`

<img width="517" alt="swagger2-to-postman_convert_js_at_develop_ _postmanlabs_swagger2-to-postman" src="https://user-images.githubusercontent.com/5207331/48313814-8cf6f100-e5e7-11e8-9ff3-5f5e7adce122.png">

So, I would recommend updating the files with this one extra field.
Here's an example request from the same collection

```yaml
paths:
  /pets:
    get:
      summary: Returns a list of pets # This will be used as request name

      description: Returns a list of pets
      tags: [pets]
      security:
        - my_oauth: [sope.read]
      produces:
        - application/json
        - application/problem+json
      parameters:
        - $ref: "#/parameters/flow_id_in_header"
      responses:
        200:
          $ref: "#/responses/Pets"
        default:
          $ref: "#/responses/Error"
```
This is how it looks after the modification
<img width="298" alt="postman" src="https://user-images.githubusercontent.com/5207331/48313676-cf1f3300-e5e5-11e8-972b-81a4961ebcd9.png">

Let me know if this fixes your issue and if the ticket can closed.

**Comment by shadyyx** [comment]
Hi.

I was thinking about this quite a lot. I thought the request URI is what I want to see, as I was used to this from previous versions of Postman (I was using the older Chrome app before).

But the more I was thinking the more I was convincing myself the _summary_ is better. Not only it gives direct information about the request it also makes/teaches us to write better (short self-describing) summaries in our swagger definitions.

So, thank you a lot! I think this is not a bug and the issue can be closed as solved.
