### ISSUE TITLE
Add Find and Replace as a context menu option on selecting a set of characters

### ISSUE THREAD

**Issue by vkaegis** [a85/POSTMan-Chrome-Extension#5512]
**Is your feature request related to a problem? Please describe.**
As mentioned in #5495, the Find and Replace future would be more discoverable and contextual if the right click menu options on selecting a set of characters allowed users to search for that query.

**Describe alternatives you've considered**
The alternative is to open Find and Replace and manually enter the query.

**Comment by prashantagarwal** [comment]
@vkaegis We already support this.
