### ISSUE TITLE
In app link to bug tracker

### ISSUE THREAD

**Issue by InsaneDoggo** [a85/POSTMan-Chrome-Extension#5513]
Would be nice to have an option like "Report bug" which refers to Github issues page. 
P.S. I know about  "Github" item inside "Help" group, but it's unclear that Postman uses Github's tracker not the other.

**Comment by InsaneDoggo** [comment]
The same about "Request feature" case.

**Comment by a85** [comment]
We are looking at improvements for this but we have seen people reach the tracker easily enough so far. Closing this for now.
