### ISSUE TITLE
Dark Mode – Skipped Tests Text Issue

### ISSUE THREAD

**Issue by chrisdeso** [a85/POSTMan-Chrome-Extension#5515]
**Describe the bug**
`Skipped Tests` text in response section is black against dark grey background when using dark theme.

**To Reproduce**
1. Enable dark mode 
2. Submit a request with a test 
3. Go to Test Results 
4. Go to Skipped when no tests have been skipped

**Screenshots**
![image](https://user-images.githubusercontent.com/4734306/48326718-a2701900-e5ef-11e8-8e93-6058704bed56.png)

**App information (please complete the following information):**
 - App Type: Native app
 - Postman Version: `6.5.0-canary04` && `6.5.2-darwin-x64`
 - OS: Mac OS

`[filed by Postman]`

**Comment by PFaz540** [comment]
I'd also like to point out that the text in the 'skipped' button is practically impossible to read

![image](https://user-images.githubusercontent.com/44571878/48945937-036aeb80-ef24-11e8-94cf-c5a5de2a2e3c.png)

![image](https://user-images.githubusercontent.com/44571878/48945944-082f9f80-ef24-11e8-9a0d-e461db21bd12.png)

**Comment by PFaz540** [comment]
![image](https://user-images.githubusercontent.com/44571878/49792463-b449f680-fd2a-11e8-87c9-ddfb79ff5609.png)

@sujayvenaik I've confirmed this has been fixed on Windows on version v6.6.0
But the issue I mentioned above is still present. Shall I create a new ticket for the above issue?

**Comment by sujayvenaik** [comment]
Fixed in v6.7.0-canary04
Canary can be downloaded from https://www.getpostman.com/canary

Will update this thread once this gets out on the stable release.

**Comment by sujayvenaik** [comment]
This is fixed in the latest version v6.7.1
