### ISSUE TITLE
Json response formatting and visualization

### ISSUE THREAD

**Issue by RogerLiNing** [a85/POSTMan-Chrome-Extension#5516]
Please read through the [guidelines](https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues) before creating a new issue.

**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I call a resutFul API to get Json data like this:
![image](https://user-images.githubusercontent.com/18111035/48327982-c0378f80-e67c-11e8-9f66-99d5ff6e44a3.png)

**Describe the solution you'd like**
I'd like to have the features:

- [x] Auto parse/format the Json data
![image](https://user-images.githubusercontent.com/18111035/48328040-14db0a80-e67d-11e8-9c0e-a7a3f8e55521.png)

- [x] Support Json data visualization
![image](https://user-images.githubusercontent.com/18111035/48328067-2f14e880-e67d-11e8-92f0-1e9fab0c9ac1.png)

**Describe alternatives you've considered**

**Additional context**

**Comment by kamalaknn** [comment]
@RogerLiNing If you've selected `Auto` as the language, we try to detect the language based on the content type of the response. Can you check if your content type correlates to JSON? Can you send us a screenshot of the the response headers section?

Also you can manually change the language setting from `Auto` to `JSON` to force format the response in `JSON` format. You can also go to settings and select `JSON` as the default type for all requests.

Can you also give us details on the current version of your app?

**Comment by RogerLiNing** [comment]
>  Can you check if your content type correlates to JSON? Can you send us a screenshot of the the response headers section?

![image](https://user-images.githubusercontent.com/18111035/48328898-36d68c00-e681-11e8-9132-ae7a8e49cbc0.png)

> Also you can manually change the language setting from Auto to JSON to force format the response in JSON format. You can also go to settings and select JSON as the default type for all requests.

**You are right, that works! Thank you!**

> Can you also give us details on the current version of your app?

**Postman v6.5.2**

**Comment by kamalaknn** [comment]
@RogerLiNing Thanks for clarifying this.

As you can see `application/javascript` content type does not map to JSON type and that's why Postman did not auto format the response.

I'm closing this because this is not an issue with the Postman app itself. Thanks.

**Comment by RogerLiNing** [comment]
Thank you! @kamalaknn
