### ISSUE TITLE
Example title is too short in the dropdown list of examples

### ISSUE THREAD

**Issue by dannyhajj** [a85/POSTMan-Chrome-Extension#5518]
### Describe the bug
**The title of saved examples is too short in the Postman application. Can it be larger?**

However, this is not the case in the online documentation. As in the online documentation, it can fit more letters.

### To Reproduce
1. Save an example under Postman, and give it a semi-long name.
2. Click on the list of examples in the dropdown inside the Postman application
3. See the cropped title with the triple dots (`...`)

### Expected behavior
I expect the title to fit in the dropdown since there's so much space already. It would be ideal if it would fit the same amount of characters as it does in the online documentation.

### Screenshots

![Examples dropdown in the application - Examples Screen](https://user-images.githubusercontent.com/530409/48350116-83709600-e686-11e8-9395-7557207e884d.png)
<sup>Examples dropdown in the application - Examples Screen</sup>

![Examples dropdown in the application - Default Screen](https://user-images.githubusercontent.com/530409/48350739-66d55d80-e688-11e8-98d8-ed2b3129a950.png)
<sup>Examples dropdown in the application - Default Screen</sup>

![Examples dropdown in the online documentation](https://user-images.githubusercontent.com/530409/48350161-9daa7400-e686-11e8-85c2-81622efd8b48.png)
<sup>Examples dropdown in the online documentation</sup>

### App information
 - Native App
 - Postman Version 6.5.2 (6.5.2)
 - macOS High Sierra 10.13.6 (Same problem on Ubuntu)

**Comment by abhijitkane** [comment]
@SamvelRaja Can we add a tooltip to the example if the text is ellipsified?

**Comment by abhijitkane** [comment]
@vkaegis Currently marking as a bug - there's no way to see the example's name unless you click on the list item.

**Comment by numaanashraf** [comment]
This issue is fixed in Postman v7.0.9
