### ISSUE TITLE
Let us disable auto-closing of brackets and quotes

### ISSUE THREAD

**Issue by HaraldKorneliussen** [a85/POSTMan-Chrome-Extension#5519]
Postman tries to helpfully insert closing brackets and quotes, and swallows them if it thinks you didn't really mean to insert a closing bracket there (usually because it's already inserted one there itself - but not always).

I think this feature gets more in the way than it's helpful. I don't think it's even fully consistent with how automatic brace insertion works in other editors. I'd rather not have the editor try to second-guess me. But there's no option to disable it.

Could you add an option to disable it?

I'd looked for "global" ways to disable brace/quote completion in Windows, but I didn't find any.

**Comment by pankajk07** [comment]
@HaraldKorneliussen  With the new release (`v7.31`), we have added few settings to customize the editor, including the setting to disable auto-close for brackets and quotes. Please try it out. We would love to hear your feedback.
