### ISSUE TITLE
/environments endpoint sending wrong information

### ISSUE THREAD

**Issue by g0rd** [a85/POSTMan-Chrome-Extension#5520]
**Describe the bug**
/environments endpoint is not responding with correct data

**To Reproduce**
1. call /environments endpoint with correct information

**Expected behavior**
1. Should see all the environments available to you. (In my case there are 6 environments as shown in the screenshots)

**Screenshots**
![image](https://user-images.githubusercontent.com/8823811/48368054-a5ffb080-e680-11e8-8403-39d0722ca8f8.png)
![image](https://user-images.githubusercontent.com/8823811/48367887-122de480-e680-11e8-84b8-12d9599e7955.png)
![image](https://user-images.githubusercontent.com/8823811/48367981-5f11bb00-e680-11e8-9fac-197f01a150ce.png)

**App information:**
 - Native 
 - Postman Version 6.5.2
 - OS: Windows 10 Pro 64 bit

**Comment by abhijitkane** [comment]
@g0rd The API only returns environments that _belong_ to you (created by you). The environments you see on the app/web are those in your selected workspace, which may have been created by you or someone else in your team. Can you confirm this? We're looking at ways to control what the API returns, but have no ETA yet.

**Comment by g0rd** [comment]
@abhijitkane thanks for a quick reply. You are correct. I have only created 1 of 6 environments and I am only seeing that one. Usually it wouldn't matter if I can or cannot see all the environments but to set-up CI pipelines, I need the info on different environs. It would be a nice middle-of-the-road solution to see the basic info like uid, name etc for all environs.

**Comment by abhijitkane** [comment]
Understood - we'll work on getting this added to the API

**Comment by chrisdeso** [comment]
Bumpity @ankitjaggi

**Comment by jrumbinas** [comment]
+1

**Comment by giridharvc7** [comment]
@g0rd Can you please check and let us know if this problem still persists for you?
