### ISSUE TITLE
Unable to add users to workspace

### ISSUE THREAD

**Issue by abhijitkane** [a85/POSTMan-Chrome-Extension#5521]
The user is part of a 15-member Pro team, and is inviting a team member to a team workspace. There's a "There was an error updating the xyz workspace" error notification on the web dashboard. Logging out+in+retry doesn't help.

Postman trace ID: `v=1;t=c75e27f2fb0b228b`

**Comment by ankitjaggi** [comment]
@abhijitkane We have fixed this issue from our side. Can you verify if it works for you now?

**Comment by preethammavin** [comment]
@abhijitkane is this fixed now?

**Comment by abhijitkane** [comment]
@preethammavin Waiting on user confirmation

**Comment by abhijitkane** [comment]
@preethammavin Confirmed
