### ISSUE TITLE
Native App Mac No Retina Support

### ISSUE THREAD

**Issue by d0sse** [a85/POSTMan-Chrome-Extension#5523]
Hello,
In last version of Postman App (6.5.2) on a MacBook Pro, the UI not supporting Retina and all elements Images and Texts are blurry!

<img width="546" alt="screen" src="https://user-images.githubusercontent.com/16508608/48401686-fed75380-e729-11e8-9514-780cbc874940.png">

Can you help me to solve this issue please, I bother my eyes!
Thanks and regards.

**Comment by numaanashraf** [comment]
@d0sse Could you verify whether this is still happening on the latest version of Postman v7.1.0. We are unable to replicate this on our retina mac devices.

**Comment by d0sse** [comment]
Yes is still present, it's strange! I've MacBookPro 14,3 with macos 10.14.4
<img width="205" alt="Schermata 2019-05-19 alle 22 10 43" src="https://user-images.githubusercontent.com/16508608/57987558-3b8e5980-7a83-11e9-887d-2947d0cb964d.png">

**Comment by d0sse** [comment]
Sorry i solved it! i check "open on low resolution" in option dialog and for strange reason this option does not reset after delete and reinstall the app. Sorry again!
