### ISSUE TITLE
Request is not available in the root subtree

### ISSUE THREAD

**Issue by Solom00n** [a85/POSTMan-Chrome-Extension#5524]
## App Details:
```
Postman for Mac
Version 6.5.2
OS X 18.0.0 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:
I encounter this recently but it's the first time I try to duplicate a collection.

 2. Expected behaviour:
If I right-click on an entire collection and then click "duplicate", I expect my collection to be duplicated. What really happens: absolutely nothing at first sight. Same behaviour when I try to duplicate a folder, but in this case, at the next start, all my attempts are present. Unfortunately, it is now impossible to delete them.

 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):

When I try to duplicate my collection:
<img width="869" alt="schermata 2018-11-13 alle 13 54 33" src="https://user-images.githubusercontent.com/5682439/48414919-39ea7e80-e74c-11e8-81e8-2bf49bc80914.png">

When I try to remove a folder:
<img width="843" alt="schermata 2018-11-13 alle 13 57 01" src="https://user-images.githubusercontent.com/5682439/48414921-39ea7e80-e74c-11e8-9750-15ed7ec0acbe.png">

 4. Screenshots (if applicable)
<img width="1440" alt="schermata 2018-11-13 alle 13 55 47" src="https://user-images.githubusercontent.com/5682439/48414920-39ea7e80-e74c-11e8-93f4-bf26ef754dc9.png">

**Comment by numaanashraf** [comment]
We've included a fix for this issue in Postman v7.1.0.
