### ISSUE TITLE
Allow Developers with a pro license to be added to a customer's pro workspace at no extra cost.

### ISSUE THREAD

**Issue by BKnights** [a85/POSTMan-Chrome-Extension#5530]
**Use Case**
I am a developer doing a number of API projects. 
I have customers who I get to purchase a Postman Pro license for doing mocking
What ends up happening is that my customer shares their login with me (bad for security) because really they tend to be only 'looking' at the project that I am developing.

My customer doesn't object to their $8/month and as long as it's just me and the customer the shared login isn't a huge issue. 

At some point in the project we bring on another developer to implement the other side of the API. Now we should have 3 licenses but due to the fluid nature of gig based projects that number can grow and shrink and at some point the customer is just going to throw up their hands and ask me to implement a mocking system (more cost for them but they don't have to keep setting up another channel)

It would seem beneficial for Postman to look at something similar to a pro developer account. If each of the devs on the project were paying for their own account and the customer could grant access for a paid developer to a collection or workspace without any extra charge that would be ideal. 

The ownership of the project would be with the customer where it belongs and they could add developers to their project as needed without having to revisit the billing panel.

**Comment by a85** [comment]
Thank you for submitting the use case. Unfortunately, we have enough issues to deal with our current billing model that we don't see this or a variant of this getting implemented any time soon. Users can of course join multiple teams but tracking usage and paying for a license individually by different people and then bringing them together in a single construct  is not possible.
