### ISSUE TITLE
Autogen XHR code causing CORS error. 

### ISSUE THREAD

**Issue by ghost** [a85/POSTMan-Chrome-Extension#5533]
Creating a mock and autogenerating XHR for a basic GET yields:
```
 var data = null;

var xhr = new XMLHttpRequest();
xhr.withCredentials = true;

xhr.addEventListener("readystatechange", function () {
  if (this.readyState === 4) {
    console.log(this.responseText);
  }
});

xhr.open("GET", "https://adfdeadd-4a72-46a9-a588-9d12f972edc1.mock.pstmn.io/gamedata2");
xhr.setRequestHeader("cache-control", "no-cache");
xhr.setRequestHeader("Postman-Token", "b2246ba7-3c58-4c5a-b4d0-ae45423d0610");

xhr.send(data);

```

when the code is run via JS in browser (Chrome) the following error comes back:

> index.html:1 Access to XMLHttpRequest at 'https://adfdeadd-4a72-46a9-a588-9d12f972edc1.mock.pstmn.io/gamedata2' from origin 'null' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'. The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials attribute

changing `xhr.withCredentials = true;` to `xhr.withCredentials = false;` fixes the issue.

**Comment by abhijitkane** [comment]
Hm..this also depends on the server configuration. Additionally, withCredentials=true is a requirement for same-site requests if cookies need to be included.

This will eventually be added as a UI option, but for now, we can add a comment to the generated code explaining this.
