### ISSUE TITLE
Uninstall tool

### ISSUE THREAD

**Issue by chrisdeso** [a85/POSTMan-Chrome-Extension#5534]
**Is your feature request related to a problem? Please describe.**
There are instances where multiple versions of the Postman app are installed on one machine. Having a tool/setting to uninstall the app – and to remove any locally stored data – would be helpful when it comes to troubleshooting.

**Describe the solution you'd like**
An uninstall tool/script

**Additional context**
`[filed by Postman]`

**Comment by a85** [comment]
Closing as there hasn't been any demand for this feature.
