### ISSUE TITLE
Missing "method" crashes web view if uploaded via API

### ISSUE THREAD

**Issue by kszafran** [a85/POSTMan-Chrome-Extension#5540]
**Describe the bug**
When a collection with a request without the `"method"` attribute is uploaded via the API, web view crashes and does not render anything. When the collection is imported using the desktop app it works just fine.

**To Reproduce**
Upload the following collection (`Crashing.postman_collection.json`):
```json
{
  "info": {
    "name": "Crashing",
    "schema": "https://schema.getpostman.com/json/collection/v2.1.0/collection.json"
  },
  "item": [
    {
      "name": "Crashing",
      "item": [
        {
          "name": "Where Is My Method",
          "request": {
            "url": {
              "raw": "https://localhost/tests/:testId",
              "protocol": "https",
              "host": "localhost",
              "path": "/tests/:testId",
              "variable": [
                {
                  "key": "testId"
                }
              ]
            }
          }
        }
      ]
    }
  ]
}
```
using the API, e.g.:
```bash
workspace=$(
    curl "https://api.getpostman.com/workspaces?type=personal" \
        -H "X-Api-Key: $POSTMAN_API_KEY" \
        | jq -r '.workspaces[0].id')

jq '{collection: .}' Crashing.postman_collection.json | \
    curl "https://api.getpostman.com/collections?workspace=$workspace" \
    -H "X-Api-Key: $POSTMAN_API_KEY" \
    -H 'Content-Type: application/json' \
    -X POST -d @-
```
(`jq` is this utility: https://stedolan.github.io/jq/).

**Expected behavior**
Web view should render correctly. The API should handle missing `"method"` like the Postman desktop app and just use `GET` by default. **This was working correctly before.** Note also that the attribute is _not_ required according to the schema: https://schema.getpostman.com/collection/json/v2.1.0/draft-07/docs/index.html

**Screenshots**
<img width="747" alt="screen shot 2018-11-19 at 14 40 01" src="https://user-images.githubusercontent.com/3056812/48708347-0192e680-ec0b-11e8-832f-0322402cbc72.png">
<img width="552" alt="screen shot 2018-11-19 at 14 40 17" src="https://user-images.githubusercontent.com/3056812/48708358-09528b00-ec0b-11e8-91ff-ca77296c7dba.png">

**App information (please complete the following information):**
 - Browser: Chrome 70.0.3538.77 (Official Build) (64-bit)
 - Postman Version: 6.5.2
 - OS: macOS High Sierra 10.13.6

**Comment by ankit-m** [comment]
A fix for this has been deployed.
