### ISSUE TITLE
Double-click on a request should open/pin a tab instead of preview

### ISSUE THREAD

**Issue by chimit** [a85/POSTMan-Chrome-Extension#5542]
In recent versions of Postman you made tabs behaviour similar to Atom. When you click on a request in a requests list it is opened in a new tab as a preview:

![image](https://user-images.githubusercontent.com/839349/48749104-59395c80-ecb4-11e8-9c16-67b73d13875b.png)

This preview tab is not pinned, so when you click on another request it would be opened in the same tab overriding the previous. That's the way it works in Atom. But Atom also has another important detail: if you double-click on a request a tab would be opened as usual (pinned, not preview).

![image](https://user-images.githubusercontent.com/839349/48749175-a9182380-ecb4-11e8-84b6-f8bea29aca28.png)

But Postman doesn't have this feature. To normally open (not preview) a tab you should double-click on a tab itself which is not very convenient.

**Comment by sujayvenaik** [comment]
Hey @chimit 

For a quick workaround you can press command+shift+click which will always open in a new tab i.e. it will not open in the preview tab.

**Comment by ruffin--** [comment]
Whoa, why was this closed? 

Can we get a feature request for this as a setting, [similar to Sublime Text](https://stackoverflow.com/a/19940461/1028230)?
