### ISSUE TITLE
Response doesn't render \r\n

### ISSUE THREAD

**Issue by Ramya-From-Postman** [a85/POSTMan-Chrome-Extension#5543]
**Describe the bug**
When you make a Post request to an API that has the body in the text format, the response data is not rendering in the new line. See the below screenshot for your reference.

![image](https://user-images.githubusercontent.com/40994626/48772600-ea2b2a80-ecea-11e8-9cf4-e34f98337d5f.png)

**Comment by mccannt** [comment]
Closing this issue as it has now been resolved.
Please feel free to reopen with the steps to reproduce if the issue persists.
