### ISSUE TITLE
Autocomplete hard to trigger when there is surrounding text

### ISSUE THREAD

**Issue by AltarBeastiful** [a85/POSTMan-Chrome-Extension#5544]
**Describe the bug**
When trying to add a variable in a field, say an URL, the autocomplete doesn't trigger if there is text before or after. Moreover, I would expect the aucotomplete to trigger for partial input like `{{Varia`

Currently the only way to trigger autocomplete is by typing a bracket followed by a space`{ `.
This forces me to add spaces when adding a variable inside an exisiting text. Also it's not very discoverable as it differs from usual autocomplete in IDE's.
Postman could support some traditional autocomplete keyboard shortcuts like Ctrl + Space 

**To Reproduce**
Given: An existing variable "var"

1. Go to a new request
2. Type the URL "api.com/resource/id/resource/id"
3. Remove the first "id" and type "{"
=> No autocomplete

4. finish typing the variable "{var}}"
=> No autocomplete

**Expected behavior**
Autocompete for variables triggers at step 3 and is updated through step 4.

**Screenshots**
*reenactment* 
![bug_autocomplete](https://user-images.githubusercontent.com/3317699/48776152-5d26a800-eccf-11e8-8b63-1d24569bc1e3.gif)
The pauses in typing are me furiously hitting Ctrl+Space as this gives me autocomplete in all my other editors and IDE's.

**App information (please complete the following information):**
Postman for Windows
Version 6.5.2
win32 10.0.17134 / x64

**Additional context**
The workaround for this is not so hard, add a space after the bracket, but this doesn't always work and this ticket is more on inconsistent behaviour.

**Comment by numaanashraf** [comment]
We are tracking a similar issue at #5067. Closing as duplicate.
