### ISSUE TITLE
Incorrect spacing when rendering markdown

### ISSUE THREAD

**Issue by godfrzero** [a85/POSTMan-Chrome-Extension#5545]
**Describe the bug**
Markdown descriptions rendered within the Postman App has crowded spacing. For example, consider the markdown snippet:

```
## Headings need space
Paragraphs don't, necessarily.

| Heading | Row |
|--|--|
| Body | Row |

Tables should probably have margins, otherwise it looks crowded.
```

This renders like so in the Postman App:

<img width="336" alt="screenshot 2018-11-20 at 7 55 07 pm" src="https://user-images.githubusercontent.com/2700229/48779888-9c202200-ecfe-11e8-807a-ab182dd5ba48.png">

This is inconsistent with the expected spacing, and the spacing within the web documentation. The table should have margins around it, headings should have variable spacing depending on heading level, etc. In addition, there's no straightforward way to control this spacing either.

**To Reproduce**

1. Add a description to any entity (it doesn't have to be a description though, any rendered markdown is affected)
2. Save
3. View rendered description within the app

**Expected behavior**
Some sort of spacing should exist for rendered markdown. If there is no default, it should be possible to control the spacing somehow.

**Screenshots**

<img width="353" alt="screenshot 2018-11-20 at 7 57 24 pm" src="https://user-images.githubusercontent.com/2700229/48779843-86126180-ecfe-11e8-9bd2-036065ea1e12.png">
<img width="336" alt="screenshot 2018-11-20 at 7 55 07 pm" src="https://user-images.githubusercontent.com/2700229/48779888-9c202200-ecfe-11e8-807a-ab182dd5ba48.png">

**App information (please complete the following information):**
 - Postman, any platform, any version

**Additional context**
Created by Postman
This was identified as an issue relating to https://github.com/postmanlabs/postman-app-support/issues/4639

**Comment by numaanashraf** [comment]
Fixed in Postman v7.1.0
