### ISSUE TITLE
Single-pane layout doesn't save Body (raw) editor length

### ISSUE THREAD

**Issue by JP-from-Postman** [a85/POSTMan-Chrome-Extension#5547]
**Is your feature request related to a problem? Please describe.**
When in single-pane layout, resizing the length of the Body (raw) editor doesn't persist when closing and restarting the app.

See screenshots below for example.

**Describe the solution you'd like**
Body editor length persists as set by the user

**Additional context**
Before closing app:
<img width="1919" alt="before" src="https://user-images.githubusercontent.com/43283131/48804410-601e9a00-ecc9-11e8-9e0f-5cd6ddacde82.png">

After restarting app:
<img width="1920" alt="after" src="https://user-images.githubusercontent.com/43283131/48804420-66147b00-ecc9-11e8-88e6-a1eb0003414b.png">

**Comment by a85** [comment]
There are no plans for saving state across restarts. There is too much overhead to store configuration options across every tab and resetting the screen state every time.
