### ISSUE TITLE
Add support for JWT authentication

### ISSUE THREAD

**Issue by ash007-postman** [a85/POSTMan-Chrome-Extension#5548]
Would like you to provide support for JWT decoding and verification.

**Comment by oprogramador** [comment]
I hope there will be both encoding and decoding.
In the same way, I can edit the request body as JSON, I would like to edit the JWT payload as JSON.

**Comment by ratpik** [comment]
@codenirvana - Support for JWT would help us move our entire API development workflow to Postman. Is there an ETA for this feature?

**Comment by mheap** [comment]
Adding our voice here. At Nexmo we use OpenAPI to document all of our APIs and love the import to postman functionality. However, some of our APIs use JWTs for authentication. Whilst it would be possible to generate and paste in a token manually, it would expire and require a regeneration each time I came back to my collection.

Using other tools I can provide my private key and a set of claims and have a JWT generated before the request is sent. This ensures that my token is always valid and the authentication gets out of my way, allowing me to focus on the endpoint.

**Comment by ShubhamPalriwala** [comment]
Any update on this issue ?
Since as of now, a user has to enter Bearer in front of the token which the user realizes after spending some time surfing the web for this stuff !
It would be great if we could directly add the JWT Token and have a category for it !

**Comment by sandipchitale** [comment]
To decode the JWT token you can write this **Pre-request Script**
```
if (pm.request.auth.type === 'bearer') {
    const parts = JSON.parse(JSON.stringify(pm.request.auth)).bearer[0].value.split('.');
    console.log('------------');
    console.log('JWT Header: ');
    console.log(JSON.parse(atob(parts[0])));
    console.log('JWT Payload:');
    console.log(JSON.parse(atob(parts[1])));
    console.log('------------');
}
```

and with sample JWT from JWT.io

```
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
```

you will see this output in the console:

```
------------
JWT Header: 
v {alg: "HS256", typ: "JWT"}
    alg: "HS256"
    typ: "JWT"
JWT Payload:
v {sub: "1234567890", name: "John Doe", iat: 1516239022}
    sub: "1234567890"
    name: "John Doe"
    iat: 1516239022
------------
```
Or a test for a token response:

```
pm.test("Token esponse has access_token and optionally refresh_token", function () {
    const mayBeTokens = pm.response.json();
    if (mayBeTokens && mayBeTokens.access_token) {
        console.log('-- Access T ------------------------------------------');
        console.log(mayBeTokens.access_token);
        const parts = mayBeTokens.access_token.split('.');
        if (parts.length === 3) { // Likely JWT
            console.log('Header: ');
            console.log(JSON.parse(atob(parts[0])));
            console.log('Payload:');
            console.log(JSON.parse(atob(parts[1])));
            console.log('------------------------------------------------------');
        }
    }
    if (mayBeTokens && mayBeTokens.refresh_token) {
        console.log('-- Refresh T -----------------------------------------');
        console.log(mayBeTokens.refresh_token);
        const parts = mayBeTokens.refresh_token.split('.');
        if (parts.length === 3) { // Likely JWT
            console.log('Header: ');
            console.log(JSON.parse(atob(parts[0])));
            console.log('Payload:');
            console.log(JSON.parse(atob(parts[1])));
            console.log('------------------------------------------------------');
        }
    }
});
```

I guess a poor man's JWT decoder.

Ideally this is integrated into Postman.

**Comment by valn1** [comment]
any updates on this?

it would help a lot of people if we could generate a new jwt in the pre request script

i tried using an external library to do so, but postman doesnt help with that either, i tried implementing KJUR, but it returns errors and it's quite difficult to debug with postman console

**Comment by arlemi** [comment]
We've added support for JWT auth in Postman v10.10. Update your app and give it a try! 

<img width="761" alt="JWT-auth2" src="https://user-images.githubusercontent.com/5029719/219413303-be346325-3a7a-48cd-a8a4-0fe3faf32095.png">
