### ISSUE TITLE
Generating Code Snippets for objective-c or swift is not working

### ISSUE THREAD

**Issue by Ramya-From-Postman** [a85/POSTMan-Chrome-Extension#5549]
When you try generating objective-c or swift code for a request in the attached collection the system does nothing. 
However, the code generation works fine if you remove the content-type header of this request.

Below collection can be used to reproduce the issue:
https://www.getpostman.com/collections/473e58b7faaa5fe425e5

**Comment by abhijitkane** [comment]
@Ramya-From-Postman With Postman 7.2.1, we've introduced bug-fixes, support for two new languages (JS-Fetch and Powershell), and the ability to configure certain aspects of the generated snippet with the 'Experimental Codegen Mode' flag enabled in Postman's global settings.

This is fixed for Swift in the new codegen UI. We'll be adding Objective-C to this list soon.
