### ISSUE TITLE
Dashboard: show if collections have published docs or not

### ISSUE THREAD

**Issue by mfaux** [a85/POSTMan-Chrome-Extension#5550]
**Feature request**
From Postman Dashboard, I'd like a way to see which collections (in a workspace) have published documentation without having to visit them individually.

**Mockup**
For example, you could surface the **Publish** button to the **Collections** page:

![image](https://user-images.githubusercontent.com/1324114/48827212-e93add00-ed6c-11e8-9400-fa2d390ffa7c.png)

**Comment by Raja-Simha** [comment]
@ankit-m , Looks like this has been implemented. Can you close.

**Comment by jaylinski** [comment]
@mfaux @jazzyarchitects Was this feature removed in Postman 8?

We have a lot of collections, so it would be nice to have an overview of published collections. The data-export sadly doesn't contain info about published collections.

**Comment by felipeabou** [comment]
I'd like to see a list of all Postman collections I've published. This is a very urgent feature.
