### ISSUE TITLE
Using Runner data variables not working as expected - "Double quote" is getting replaced with Slash (/)

### ISSUE THREAD

**Issue by Ramya-From-Postman** [a85/POSTMan-Chrome-Extension#5551]
I have a csv file with the following content - when I preview the data from Runner I don't see the value verbatim. For my post payload I do need it to contain \" as referenced below.

skil 
Skill (\"fixmobile\") >=1 & Skill (\"en_chat\") =1 & Skill (\"ts\") =1 & Skill (\"telus\") =1 & Skill (\"wireless\") =1 
Skill (\"fixtv\") >=1 & Skill (\"en_chat\") =1 & Skill (\"ts\") =1 & Skill (\"telus\") =1 & Skill (\"wireless\") =1

Attach is the csv file along with a screenshot of what preview data interprets my dataset to be like

![image](https://user-images.githubusercontent.com/40994626/48827138-557c0780-ed92-11e8-8153-e3e8ec084170.png)

**CSV data to reproduce the issue:**

agent_group | script | en_display | fr_display
-- | -- | -- | --
eugene MOB TS   FIXMOBILE EN | Skill   (\"fixmobile\") >=1 & Skill (\"en_chat\") =1 &   Skill (\"ts\") =1 & Skill (\"eugene\") =1 & Skill   (\"wireless\") =1 | CHAT - eugene   Mobility Tech Support En | CHAT - eugene   Mobility Tech Support En
eugene MOB TS   FIXMOBILE FR | Skill   (\"fixmobile\") >=1 & Skill (\"fr_chat\") =1 &   Skill (\"ts\") =1 & Skill (\"eugene\") =1 & Skill   (\"wireless\") =1 | CHAT - eugene   Mobility Tech Support Fr | CHAT - eugene   Mobility Tech Support Fr
eugene MOB CR1   ACCTMGMT EN | Skill   (\"acctmgmt\") >=1 & Skill (\"en_chat\") =1 &   Skill (\"cr1\") =1 & Skill (\"eugene\") =1 &   Skill (\"wireless\") =1 | CHAT - eugene   Mobility Case Rep 1 En | CHAT - eugene   Mobility Case Rep 1 En
eugene MOB CR1   ACCTMGMT FR | Skill   (\"acctmgmt\") >=1 & Skill (\"fr_chat\") =1 &   Skill (\"cr1\") =1 & Skill (\"eugene\") =1 &   Skill (\"wireless\") =1 | CHAT - eugene   Mobility Case Rep 1 Fr | CHAT - eugene   Mobility Case Rep 1 Fr
eugene MOB CR2   EN | Skill   (\"acctmgmt\") >=1 & Skill (\"en_chat\") =1 &   Skill (\"cr2\") =1 & Skill (\"eugene\") =1 &   Skill (\"wireless\") =1 | CHAT - eugene   Mobility Case Rep 2 En | CHAT - eugene   Mobility Case Rep 2 En
eugene MOB CR2   FR | Skill   (\"acctmgmt\") >=1 & Skill (\"fr_chat\") =1 &   Skill (\"cr2\") =1 & Skill (\"eugene\") =1 &   Skill (\"wireless\") =1 | CHAT - eugene   Mobility Case Rep 2 Fr | CHAT - eugene   Mobility Case Rep 2 Fr
eugene WLN TS   FIX LOCAL EN | Skill   (\"fixlocal\") >=1 & Skill (\"en_chat\") =1 &   Skill (\"ts\") =1 & Skill (\"eugene\") =1 & Skill   (\"wireline\") =1 | CHAT - eugene   Wireline TS Fix Local En | CHAT - eugene   Wireline TS Fix Local En
eugene WLN TS   FIX STV EN | Skill   (\"fixstv\") >=1 & Skill (\"en_chat\") =1 &   Skill (\"ts\") =1 & Skill (\"eugene\") =1 & Skill   (\"wireline\") =1 | CHAT - eugene   Wireline TS Fix STV En | CHAT - eugene   Wireline TS Fix STV En
eugene WLN TS   FIX TV EN | Skill   (\"fixtv\") >=1 & Skill (\"en_chat\") =1 &   Skill (\"ts\") =1 & Skill (\"eugene\") =1 & Skill   (\"wireline\") =1 | CHAT - eugene   Wireline TS Fix TV  En | CHAT - eugene   Wireline TS Fix TV  En
eugene WLN TS   FIX HSIA EN | Skill   (\"fixhsia\") >=1 & Skill (\"en_chat\") =1 &   Skill (\"ts\") =1 & Skill (\"eugene\") =1 & Skill   (\"wireline\") =1 | CHAT - eugene   Wireline TS Fix HSIA En | CHAT - eugene   Wireline TS Fix HSIA En
eugene WLN CR1   EN | Skill   (\"en_chat\") =1 & Skill (\"cr1\") =1 & Skill   (\"eugene\") =1 & Skill (\"wireline\") =1 | CHAT - eugene   Wireline Case Rep 1 En | CHAT - eugene   Wireline Case Rep 1 En
eugene WLN CR2   EN | Skill   (\"en_chat\") =1 & Skill (\"cr2\") =1 & Skill   (\"eugene\") =1 & Skill (\"wireline\") =1 | CHAT - eugene   Wireline Case Rep 2 En | CHAT - eugene   Wireline Case Rep 2 En

**Comment by vikiCoder** [comment]
Hi,

You can define the values for script column as a string using double quots (`"<script>"`). And quots inside the script can be escaped by using it twice (`""`). Below is a sample CSV file which will produce desired result as you want(note the escaped quots`""` in script):

```
script_name,script_data
myScript,"console.log(""Hello World!"")"
```

**Comment by vikiCoder** [comment]
Hi @Ramya-From-Postman,

I would like to inform that we have made some changes related to CSV file parsing under the hoods in the Postman App. You can now escape the double quotes with a backslash (`\`) instead of using two double quotes(`""`) inside a string in CSV file. Below is a sample CSV file which will produce desired result as you want.
```
script_name,script_data
myScript,"console.log(\"Hello World!\")"
```

 This change is available on the [latest canary](https://www.getpostman.com/downloads/canary) version (Version 7.1.1-canary07) of the app. You can checkout [canary](https://www.getpostman.com/downloads/canary) and let us know if you are still facing this issue in it.

**Comment by vikiCoder** [comment]
The changes that I mentioned in my previous comment are out in [latest Postman App](https://www.getpostman.com/downloads/) (v7.2.1) as well.
