### ISSUE TITLE
Programatically provide x-www-form-urlencoded data

### ISSUE THREAD

**Issue by prateeksarda** [a85/POSTMan-Chrome-Extension#5553]
Please read through the [guidelines](https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues) before creating a new issue.

**Is your feature request related to a problem? Please describe.**
I am trying to create a collection with POSTing requests with x-www-form-urlencoded data.
The next request body is formed by parsing form data from previous response.
This form data has dynamic values which changes over (so key-value pair for the form data will not be static)

**Describe the solution you'd like**
A way to programatically provide the form data

**Describe alternatives you've considered**
Alternative was to send form data as value set from Global variable as screenshot below
but doesnt work as Postman is adding a {{data}} : "" as form data

**Additional context**
**POST Body**
![image](https://user-images.githubusercontent.com/34772536/48859717-c6351b00-edb6-11e8-976c-446eb1133c53.png)
**Pre-request script to set POST Body**
![image](https://user-images.githubusercontent.com/34772536/48859744-db11ae80-edb6-11e8-89de-c45f33820365.png)

**Comment by prateeksarda** [comment]
I saw a similar feature request for the change in format 
I think this would help in that case if implemented.

https://github.com/postmanlabs/postman-app-support/issues/4261

**Comment by matt-ball** [comment]
It is possible to do this by using the `raw` setting on your `Body`, setting a `Content-Type: application/x-www-form-urlencoded` header and manipulating your data appropriately:

Headers:
![image](https://user-images.githubusercontent.com/8490181/48861299-193bad80-ed78-11e8-8e87-5ae624765471.png)

Body:
![image](https://user-images.githubusercontent.com/8490181/48861322-25276f80-ed78-11e8-846b-13d7e3a18dae.png)

Pre-request Script:
![image](https://user-images.githubusercontent.com/8490181/48861348-37091280-ed78-11e8-84e0-5cefd3a8f529.png)

Code:
```js
const obj = {
    "key1": "value1",
    "key2": "value2"
};

const payload = Object.keys(obj).reduce((acc, cur) => {
    return `${acc}${cur}=${obj[cur]}&`;
}, '');

pm.globals.set('payload', payload);
```

**Comment by prateeksarda** [comment]
Thank you @matt-ball the methodology works
