### ISSUE TITLE
Sending a request quickly after it has been selected causes 'Request URL is empty' error

### ISSUE THREAD

**Issue by PFaz540** [a85/POSTMan-Chrome-Extension#5554]
**Describe the bug**
- If the user selects a request were the URL/header etc. contains env/global variables, sending that request after selecting can return 'Request URL is empty'
- After opening a request that has variables in the URL, they are red and quickly become orange to say "Yes, I know this variable exists in Postman"
- It seems the request is sent before Postman confirms that the variable exists.
- This didn't use to happen when I last used Postman (about 8 months ago)

**To Reproduce**
1. Create multiple requests where the URL is using an environment variable
2. Select the first request
3. Quickly send the request by pressing the shortcut key CTRL + Enter (on Windows)
4. Keep selecting the next request and performing step 3 again until you see the error in the bottom-right.

**Screenshots**
![image](https://user-images.githubusercontent.com/44571878/48891291-df7bad00-ee32-11e8-82b6-192eaa4cc393.png)

**App information (please complete the following information):**
 - Postman Version: Windows v6.5.2
 - OS: Windows 10 64 bit

**Additional context**
- Oddly enough, this issue doesn't occur when using the runner 😕

**Comment by kamalaknn** [comment]
This issue is no longer reproducible in the latest version of Postman. We made a few improvements in the loading lifecycle of the request which seems to have fixed this.
