### ISSUE TITLE
Native App is very slow compared to deprecated Chrome App

### ISSUE THREAD

**Issue by gabrieltaets** [a85/POSTMan-Chrome-Extension#5555]
**Describe the bug**
Running a request on the native app is very slow in comparison with the native app.
My API is returning about 2MB in data. The Chrome App makes the request and receives the response effortlessly, and the Runner runs the tests 10 times in less than 20 seconds.
Seeing the new features available on the native app I decided to give it a try, but is so slow that it's not viable to use. The same (single) request takes about 5s to display, and the Runner takes 90 seconds (!) to run the exact same tests 10 times. I have noted that the app stops responding for a while after a request has been sent, and responds normally in between requests.
I have also tried using newman cli, which happened to be also as slow as the native app -- so I'm thinking that maybe if the app makes use of the newman package, then it probably is the culprit for some reason. For what it's worth, its visible that the cli has a significant delay after receiving the response and before printing the result tests (which are really just checking the status code and response time, very simple).
The native app also takes a lot longer to start up.
The dev console shows no error whatsoever.

**To Reproduce**
1. Open Runner on Native App
2. Run a collection of request tests
3. Note down time spent since step 1
4. Open Runner on Chrome App
5. Run the same collection of request tests
6. Note down time spent since step 4
7. Confirm that the native app is about 5x slower than the Chrome App

**Expected behavior**
Similar total time spent on both Native and Chrome apps.

**Screenshots**
![newman](https://user-images.githubusercontent.com/22807067/48908650-11e8d280-ee52-11e8-94c5-d7767f6ee34f.png)
This is the newman summary. I'm not sure if there is a way to show the Chrome App total run duration but it takes between 15 and 20 seconds.

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version [6.5.2]
 - OS: Windows 7 SP1 x64

**Additional context**
I have also tried logging in/out, syncing, removing variables, using files outside of collections, all to no avail.
I am very suspicious of newman as the culprit but I don't know how to be sure of it.

**Comment by saswatds** [comment]
Relates to https://github.com/postmanlabs/postman-app-support/issues/4751

**Comment by saswatds** [comment]
Hi @gabrieltaets We have been working actively on improving the performance of the native app while handling responses. 

Can you try-out our canary build and see if you are encountering any sluggish behaviour. 
https://www.getpostman.com/downloads/canary

**Comment by saswatds** [comment]
Hi @gabrieltaets the native app is in general little bit heavy. We have been actively working on improving performance. A lot of performance fixes have landed on our production app version 7.3.x regarding response viewing experience.

I will be closing this issue as we are already tracking the performance problems in more specialised issues on both runner and requester.

**Comment by gabrieltaets** [comment]
Hi @saswatds. I'm glad to see some performance improvements. I'm no longer working at the same company I was at the time of this post so I'm afraid it's not possible for me to check for any improvements, on the matter of the reported issue. However, I am still using Postman at my current job and personal projects and I have not noticed the same sluggish behavior since then, which points either to an environmental issue or an already resolved issue.
Anyways, thanks for updating this issue, it's always good to see a great tool getting improvements.
