### ISSUE TITLE
Postman v6.5.2 Update for snapcraft

### ISSUE THREAD

**Issue by MrSquaare** [a85/POSTMan-Chrome-Extension#5556]
Hello,

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Lastest update (v6.5.2) for snapcraft

**Describe alternatives you've considered**

**Additional context**

**Comment by SamvelRaja** [comment]
Will resolve via https://github.com/postmanlabs/postman-app-support/issues/5574
