### ISSUE TITLE
Postman Linux sets itself a default application for html (Nautilus File Manager) 

### ISSUE THREAD

**Issue by ghost** [a85/POSTMan-Chrome-Extension#5558]
**Describe the bug**
On Ubuntu, when Postman starts it is set as default application to handle html files

**To Reproduce**
1. In Nautilus(filemanager), right click on any html file and in "Properties"->"Open With" check if default application is set to Firefox or change it to Firefox if needed. Close properties and with double clicking the file check its correct behavior.
2. Start Postman
3. In Nautilus(filemanager) again, right click e.g. exactly same html file and in "Properties"->"Open With" you see Default application is changed to Postman

**Expected behavior**
No change of Default application

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version: 6.5.2, 6.4.4, 7.0.6, 7.0.9, probably others
 - OS: Ubuntu 18.10

**Comment by jonathanmcmahon** [comment]
Can confirm this on Postman for Linux, Version 6.6.1 (linux 4.15.0-42-generic / x64) on Ubuntu 18.04.

Super annoying. Postman sets itself as the default app each time the app is launched, so manually changing the default app for `.html` files back to a browser or whatever only works until the next time you launch postman.

**Comment by gitanoqevaporelmundoentero** [comment]
Same problem here (Linux 4.15.0-43-generic x86_64 and Postman 6.6.1 and also Postman 6.7.1).

**Comment by ghost** [comment]
@numaanashraf: label "installation" on this issue is probably misleading. It sets itself as a default application for html on each postman start, not on postman installation

**Comment by themarquee** [comment]
Same issue on Lubuntu (Linux 4.15.0-45-generic (x86_64)) and Postman 6.7.1

**Comment by ghost** [comment]
@numaanashraf: is there any progress here? This is extremely annoying bug...

**Comment by Episodio1** [comment]
Same issue here with Ubuntu 18.

**Comment by brianstrauch** [comment]
Same on Ubuntu 19

**Comment by ousloob** [comment]
Same Ubuntu 18.04 even if we set another browser as default application for HTML
Postman sets itself as a default application after a reboot

**Comment by numaanashraf** [comment]
We've included a fix for this issue in Postman v7.1.0. Do let us know if you are still facing this issue after updating to v7.1.0. Closing this issue for now.

**Comment by wfajkowski** [comment]
@numaanashraf Postman still change a default with v7.2.2 version
