### ISSUE TITLE
Postman fails to install and launch 

### ISSUE THREAD

**Issue by mvrska** [a85/POSTMan-Chrome-Extension#5560]
**Describe the bug**
I used to use postman normally and then at some point, probably after an update, I stopped being able to do so. After several hours of googling, I wasnt able to make it work.

**To Reproduce**
1. Launch any postman installer
2. just a tiny window blinks and postman AppData/Local + AppData/Roaming folders are created and probably correctly populated.
3. Try to launch 'installed' postman.
4. nothing happens

**App information (please complete the following information):**
 - Native App
 - win64 6.5.2, win32 6.5.2, win64 6.5.3 canary
 - OS: Windows 10 64bit

- Chrome App runs successfully

**Additional context**
what I tried:
- delete `C:\Users\<user>\AppData\Roaming`
- Launching installer via CMD produces same result as reproduction step 2), no output
- Launching postman via CMD from `C:\Users\<user>\AppData\Local\Postman\app-6.5.2\Postman.exe` also produces no output
- environment variable POSTMAN_DISABLE_GPU=true

**Other notes**
`C:\Users\<user>\AppData\Roaming\Postman\logs` is empty
SquirelSetup.log contains
```
2018-11-23 11:45:13> Program: Starting Squirrel Updater: --updateSelf=C:\Users\mikev\AppData\Local\SquirrelTemp\Update.exe
2018-11-23 11:45:13> Program: About to wait for parent PID 17300
```

any help would be much appreciated, thanks in advance

**Comment by SamvelRaja** [comment]
Continuing investigation [here](https://github.com/postmanlabs/postman-app-support/issues/5575)
