### ISSUE TITLE
Application stuck on startup

### ISSUE THREAD

**Issue by matouel** [a85/POSTMan-Chrome-Extension#5561]
## App Details:

```
Postman for Windows
Version 6.5.2
Windows 7 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there: Always been there but I was able to get around it by resintalling. But for some reasons, workaround don't work anymore.
 2. Expected behaviour: Application start and workspace is loaded properly with all collections savec on the cloud.
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
```
vendor-shared.js:119189 Error in the app boot sequence TypeError: Cannot match against 'undefined' or 'null'.
    at __WEBPACK_IMPORTED_MODULE_1__CurrentUserController__.a.get.then (vendor-shared.js:175395)
    at <anonymous>
```
 4. Screenshots (if applicable)
![image](https://user-images.githubusercontent.com/8397088/48951666-6ac97100-ef0d-11e8-9f50-847db991459c.png)

Simply start the applicastion using the provided application program shortcut that uses the "update.exe". I did try using "Postman.exe" directly without success.

**Comment by SamvelRaja** [comment]
@matouel  Could you send us these informations(Redacted) to  `help[at]getpostman[dot]com`

1. logs from, `C://Users/[User]/AddData/Roaming/Postman/logs`
2. Is there any data available in `Devtools -> Application -> IndexedDb -> postman-app -> users`  table 
3. Send the infomation from `window.localStorage`

**Comment by numaanashraf** [comment]
Thank you for your issue! With only the details that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have more information for us that'll help us debug or triage this issue.
