### ISSUE TITLE
Wrong value read from response.json()

### ISSUE THREAD

**Issue by mmornati** [a85/POSTMan-Chrome-Extension#5568]
**Describe the bug**
When accessing a value from response.json() into the test script, the value is not corresponding to the one you can read on the response body into the web interface (which is the correct one).

You can see what is happening checking the following screenshots.
I tried to change the way I'm parsing the Json body (pm.response.json() or JSON.parse(responseBody) but the result is the same).
Can it be anything related to the Long value size? (which is valid in my Java API application)

**Expected behavior**
Values should be the same !!

**Screenshots**
![image](https://user-images.githubusercontent.com/139323/48984567-6368ba00-f0fd-11e8-8089-801a3ff2ebb9.png)
![image](https://user-images.githubusercontent.com/139323/48984572-724f6c80-f0fd-11e8-93bc-a6b35cbc12c5.png)
![image](https://user-images.githubusercontent.com/139323/48984577-7bd8d480-f0fd-11e8-8827-dd2edb79331b.png)

**App information (please complete the following information):**
- Native OSx APP: V. 6.5.2

**Comment by abhijitkane** [comment]
Possibly related to https://github.com/postmanlabs/postman-app-support/issues/5658 - the same bug in the console

**Comment by saswatds** [comment]
Hi @mmornati, the test scripts run in a javascript sandbox and maximum values an integer can hold in javascript is +/- 9007199254740991
Currently, BigInt support in javascript is in stage-3 https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt  so as and when javascript starts supporting such large integers the test scripts in Postman will also be able to. 

As an alternative, we can suggest, you could perform string-based comparisons with Regular Expression using `pm.response.text()`

Closing this issue now.
