### ISSUE TITLE
Automatic URL encoding (not entire URL)

### ISSUE THREAD

**Issue by allicanseenow** [a85/POSTMan-Chrome-Extension#5570]
**Describe the bug**
API is: 
[https://email@gmail.com:someChars@my-store.spotify.com/a.json](https://email@gmail.com:someChars@my-store.spotify.com/a.json)

**To Reproduce**
1. Open postman
2. Send a GET request with this URL
3. Console says this URL is sent in its expected form, but in fact, the first "@" in the email@gmail.com (not the second "@" as this one is kept intact) is encoded into %40
4. Server returns a wrong response due to a wrong request submitted by Postman

**Expected behavior**
I want an option to completely disable URL encoding. URL encoding should be totally in controlled of developers and if needed, there is a completely seperate area to encode URL **MANUALLY**. 

This runs perfectly on Chrome Browser, or on the REST Api Client Testing app on Chrome Store, where I get my expected result, but not on the latest version (6.5.2) of Postman.

**App information (please complete the following information):**
 - Postman Version: 6.5.2
 - OS: Mac OS 10.13.6

**Comment by numaanashraf** [comment]
@allicanseenow Thanks for reporting this. We are working on providing more control over the automatic encoding behavior in Postman. We'll keep you posted here when we have new updates on that.

**Comment by cooperthompson** [comment]
Any update on this?  I've also been dealing with Postman being a little too helpful with URL encoding.  Would be nice to turn that off, or at least be able to trust the postman console.

**Comment by vikiCoder** [comment]
Hi, we have added a request option to provide more controll over automatic URL encoding. This option is available in the latest [Postman Canary](https://www.postman.com/downloads/canary) release (version 7.20.0-canary03). You can see more details about the fix at #8154

![image](https://user-images.githubusercontent.com/16588032/76196985-4fbd6600-6211-11ea-836b-926ee44fc969.png)

**Comment by codenirvana** [comment]
As mentioned in https://github.com/postmanlabs/postman-app-support/issues/5570#issuecomment-596405521, the new request setting is now available in the latest version of the Postman app (v7.20.0) once you enable the "Use next generation URL processing" setting as mentioned in #8154.

Feel free to leave your feedback at #8154 or reopen this thread if the issue persists.
