### ISSUE TITLE
Snap can't upgrade

### ISSUE THREAD

**Issue by sabatesduran** [a85/POSTMan-Chrome-Extension#5574]
**Describe the bug**
Postman automatic upgrade doesn't work in v6.4.4 as a `snap`

**To Reproduce**
1. Go to 'Settings'
2. Click on 'Update available'
3. Click on 'Update'
4. See update error in the console

**Expected behavior**
Upgrade the app

**Screenshots**
![postman](https://user-images.githubusercontent.com/5699145/49016875-aff8d780-f187-11e8-9fb8-87bf232cad7e.png)

**App information (please complete the following information):**
- Postman for Linux
- Version 6.4.4
- linux 4.15.0-39-generic / x64

**Comment by edo9k** [comment]
Similar problem here.

**Comment by Deus-Rex** [comment]
Likewise, also a snap.

**Comment by kid1412621** [comment]
cannot update to latest version through snap

**Comment by harryi3t** [comment]
@kid1412621 @sabatesduran @Deus-Rex @edo9k 
This is fixed in the latest version of Postman 6.7.1
It should update automatically or you can manually refresh also.
