### ISSUE TITLE
Support vault integration for secrets management

### ISSUE THREAD

**Issue by akshah123** [a85/POSTMan-Chrome-Extension#5577]
At present, we are storing credentials for authorization in environments and sharing it with team members.  This makes it difficult to deal with management of api credentials.  It would be great if postman integrated with a service like Vault so that we can better manage access to them as devs join and leave the company.

**Describe the solution you'd like**
Support pulling credentials from vault: https://www.vaultproject.io/

**Comment by akshah123** [comment]
Node package that can be used within an electron app: https://www.npmjs.com/package/node-vault
An electron app that is operating on vault: https://github.com/jonsavage/VaultGUI

**Comment by Kiemes** [comment]
I would also love this feature. Besides Vault, LastPass would be great.

**Comment by CelesteGH** [comment]
We really need this too.

**Comment by Suhas-Gaikwad** [comment]
Thank you for your patience. We have released a feature for seamless integration with leading third-party secret vaults, including AWS Secrets Manager, Azure Key Vault, and HashiCorp Vault in the release of [Postman v11](https://blog.postman.com/announcing-postman-v11/). 1Password support is coming soon.

[Check the learning center](https://learning.postman.com/docs/sending-requests/postman-vault/postman-vault-integrations/) to learn more about the feature.
