### ISSUE TITLE
'Duplicate request' creates empty request

### ISSUE THREAD

**Issue by jdvegmond** [a85/POSTMan-Chrome-Extension#5579]
Please read through the [guidelines](https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues) before creating a new issue.

**Describe the bug**
Found in Postman 6.5.3.
When duplicating a request a new request is created with the same name + 'Copy', but none of the contents of the original request is copied to the new request.

**To Reproduce**
1. Create a request with URL, and e.g. Tests
2. Right click on the request in the side bar and click 'Duplicate'
3. Check the contents of the newly created request

**Expected behavior**
All contents of the original request has been copied to the new request.

**App information (please complete the following information):**
 - Windows App
 - Postman Version 6.5.3
 - OS: Windows 10 latest version

**Comment by jdvegmond** [comment]
Sorry, my mistake. Wasn't doing what I thought I was doing.

**Comment by feathergrass** [comment]
Just for strangers like me: Saving request before duplicating fixes the issue.
