### ISSUE TITLE
Bad response in Postman API documentation

### ISSUE THREAD

**Issue by loopDelicious** [a85/POSTMan-Chrome-Extension#5581]
In the Postman API documentation, the example response for [this request](https://docs.api.getpostman.com/#09886971-e1e2-4a62-8f59-f7abfd79ff5e) is a 400 Bad Request. Can we include an example of a successful response?

<img width="1475" alt="screen shot 2018-11-28 at 1 08 32 pm" src="https://user-images.githubusercontent.com/17693714/49182331-dbf29500-f30e-11e8-8ece-8f93c4407994.png">

**Comment by deepakpathania-zz** [comment]
Hey @loopDelicious, we do have examples for successful responses as well in the example dropdown, would you like us to show that as the default response?

**Comment by loopDelicious** [comment]
@deepakpathania I don't believe the example dropdown is available in the documentation - only in the Postman app, correct? 

In the documentation, it would be more helpful to the user to either display a successful response or multiple responses (that include at least one successful response).

**Comment by deepakpathania-zz** [comment]
@loopDelicious The example response dropdown is tied to the example request dropdown, so in your case, you're looking at the `Error: invalid params` example request, clicking on that shows the various request-response pairs, which has the success responses as well.

Please let me know if I misunderstood something and I'd be happy to correct myself.

**Comment by loopDelicious** [comment]
@deepakpathania I didn't realize there was also an examples dropdown in the documentation.

My 2 cents is to display a successful response in the documentation by default (for the Postman API), since the primary purpose of the documentation is to show someone how to use the API.

And for UX suggestion, perhaps consider displaying a successful response as a default for all documentation. Also general UX feedback, I didn't notice the dropdown icon - totally missed it! In the app the Examples section is subtle, but there's also a count of total examples. Just general feedback for @vkaegis

**Comment by deepakpathania-zz** [comment]
Valid points. Unfortunately, you can't order examples right now(afaik) and since the documentation is generated using those examples, we can't put something as a default. Is that the case or am I missing something? @vkaegis 

A possible solution to the current situation is to delete the examples and recreate them in an order which satisfies the successful response being shown as the default point.

**Comment by vkaegis** [comment]
I'm presuming what qualifies as a success is also a bit subjective since we don't have a parameter tracking that. We could parse the response code to get that, but still a bit iffy. But thanks for the feedback @loopDelicious! Adding the number of responses makes sense.. will look into that.

**Comment by davidespihernandez** [comment]
The Postman API documentation and examples have been improved in the last months. Currently, both the collection and the OpenAPI of Postman API provide examples for all the existing endpoints, and these examples are properly reflected in the documentation.

<img width="299" alt="Screenshot 2023-01-13 at 12 47 32" src="https://user-images.githubusercontent.com/2665033/212314662-4e79f794-7918-48c5-83cb-b33d46773dfd.png">
