### ISSUE TITLE
Know when my imported collection is out of date

### ISSUE THREAD

**Issue by loopDelicious** [a85/POSTMan-Chrome-Extension#5582]
**Is your feature request related to a problem? Please describe.**
When I import a collection using the Run in Postman button (or other non-auto-updating means), I am referencing that particular version of the collection. When the provider makes updates to the collection, I am unaware of these updates. 

For example, when I import a collection of the Postman API, I'm happily working with it in the Postman app. I don't know about new features that are pushed to the Postman API. When / if I find out, I need to return to the API docs and import the latest collection.

**Describe the solution you'd like**
Receive a notification, or see an indication, that there's a newer version of the collection available. I can choose to update the collection or continue working off my version.

**Describe alternatives you've considered**
I can check back with the original collection author to inquire about updates. But even if I return to the original source of the collection, I can only inspect the two versions to discern if there are any differences. There's no inbuilt API versioning or easy way to view the diffs.

**Comment by a85** [comment]
There are no plans to maintain links to imported collections. The Run in Postman button or other ways in which people collaborate and share on public collections will be part of improvements to Public Workspaces in coming months.
