### ISSUE TITLE
edit variable's current value from mouse-over popup / tooltip window

### ISSUE THREAD

**Issue by gekonwi** [a85/POSTMan-Chrome-Extension#5583]
**Is your feature request related to a problem? Please describe.**
Our requests are full of variables defined in different scopes - global, environment, and collection. Thus, wehenever we need to change a variable's current value, we need to:
1. hover over the variable
2. remember the scope
3. remember the variable name
4. remember that global and environment variables can be edited in the "environment quick look" panel but the collection variables cannot (which is a pain on its own but there is another ticket for that already)
5. navigate to the list containing the variable (yes, in the case of global / environment variables, it's just one click away, but in the case of collection variables, it's not)
6. find the variable in the list (we have a lot of variables and thus quite long lists in the variable editors)
7. set the variable
8. return back to the request to finally send it

8 steps for an action which is executed dozens of times every day?!!

**Describe the solution you'd like**
Add the same current value editing UX as you did in the "environment quick look" panel already:
1. The variable mouse-over popup would have the "pencil" button appear when hovering over the current value.
2. Clicking on this pencil button would make the current value editable.

**Describe alternatives you've considered**
Currently, we just stopped using collection variables and add global pseudo-variables like "------- Request Body" as section headers to make the variables easier to find in the "environment quick look". Thus, we end up with dozens of global variables which should really be collection variables. The biggest downside of that is the fact that we cannot share collections across workspaces because the other workspaces may not have all the dozens of global variables.

**Additional context**
I know this has been discussed in the recently closed #763 already. Since it is still a big painpoint, despite the "environment quick look", I decided to create a new ticket with more details.

**Comment by gekonwi** [comment]
@vkaegis - any updates on this?

**Comment by martijnvanschie** [comment]
UPVOTE.

Environment and Global Variables editor are not user friendly. Really hope this is picked up. Insomnia has a very nice JSON editor for variables which not only makes the editing really easy it also allows for easy textual comparisons between environments using for instance WinMerge.

**Comment by skatikia** [comment]
Hi all! A bit too late, but not never. I have good news!

With Postman **V11.14**, we have rolled out multiple improvements to our variables interface, including **the ability to update variable values on the go**.

Just hover over a variable to view its value, edit it, and hit Send!

![edit-value](https://github.com/user-attachments/assets/45aed08c-2982-47e2-9833-d30ddf2e1e3e)

I hope you like this change as much as we do! Update your app to start working with this change and many more, and let us know what you feel ([over a call](https://calendly.com/shobhit-katikia/meet-with-shobhit) or just drop an email to [shobhit.katikia@postman.com](mailto:shobhit.katikia@postman.com)).

[Check out the Postman V11.14 release note](https://arc.net/l/quote/vtemyulc)
