### ISSUE TITLE
App keeps skipping between Offline

### ISSUE THREAD

**Issue by matt-usurp** [a85/POSTMan-Chrome-Extension#5586]
**Describe the bug**
I get the "Looks like you are offline" banner appearing continuously on-and-off through out the day, usually on an interval of around every minute. Most of the time it is for a few seconds and sometimes it can persist the entire day until the app gets a restart.

This causes the banner (of which is fixed height) to make the page jump up and down all day long. This is what I would consider the crux of this bug, the UX could be better here.

**To Reproduce**
I cannot give steps to reproduce but I can confirm that our office WIFI is not the best and does drop out at random intervals. I am also based in London so not sure if this is a latency related issue to the servers.

**Expected behavior**
Better handling of reconnections or a better UX for the user.

**Screenshots**
![image](https://user-images.githubusercontent.com/1379839/49215063-d6a15300-f3bf-11e8-9068-701e2e2fd83d.png)

**App information (please complete the following information):**
 - App Type [Native App]
 - Postman Version [e.g. 6.5.3]
 - OS: [macOS Mohave 10.14]

**Additional context**
I don't think this would be such an issue if the banner wasn't fixed height. The main reason that I raise this issue is because the page jumps up and down all day trying to reconnect and the user experience isn't the best. I feel that if this was actually displayed via a red icon or a floating banner this issue would be lessened for me. At least I am working against a locally hosted API so I do not require the internet to work and this banner is taking up precious real estate on the screen.

**Comment by wspencer** [comment]
+1. This is happening to me too.  Very annoying!

**Comment by mjgabriel** [comment]
+1. This happens to me as well. Running current release 6.7.4

**Comment by thertzelle** [comment]
Please fix this UI and potentially bug. All day long the window bounces up and down as the internet apparently cuts out...Even though my network isn't losing connection.

**Comment by mccannt** [comment]
Closing this issue as it has now been resolved.
Please feel free to reopen with the steps to reproduce if the issue persists.

**Comment by wspencer** [comment]
You're leaving us with a hack?  Lame. 

Warren Spencer
