### ISSUE TITLE
Maintain collection UUID on transfer

### ISSUE THREAD

**Issue by chrisdeso** [a85/POSTMan-Chrome-Extension#5588]
**Is your feature request related to a problem? Please describe.**
When removing a user from a paid team, the administrator(s) are prompted to transfer ownership of any shared collections to another user. When the transfer is made, the UUID of the collection(s) transferred changes to reflect the new owner. If a team is leveraging Newman – and these specific collections – for continuous integration, pipelines break 💀.

**Describe the solution you'd like**
Persist UUIDs on transfer or any other solution.

**Additional context**
[filed by Postman]

**Comment by wmurphycs** [comment]
+1, it would be very useful if the UUIDs stayed constant

**Comment by a85** [comment]
Postman will be eliminating the notion of an owner. These and other issues will be handled by a role based access control system.
