### ISSUE TITLE
Customize request id on published documentation URL

### ISSUE THREAD

**Issue by aweeks17** [a85/POSTMan-Chrome-Extension#5590]
It would helpful if we were able to customize the request id's on the published documentation URLs rather than have a string of random numbers/letters for each one. This would make sharing the URLs easier. 
 
For example, instead of apidocs.example.com/#e7a7ffb0-ce3d-4a56-8f92-1b7121edf17, it could be apidocs.example.com/#numbers.

**Comment by Raja-Simha** [comment]
Duplicate of #5706
