### ISSUE TITLE
Error: "Could not open Postman" while opening the app

### ISSUE THREAD

**Issue by mariobenuzzi** [a85/POSTMan-Chrome-Extension#5591]
1. Update to 6.5.3
2. Launch App
You get this:
<img width="551" alt="screenshot 2018-11-29 20 39 34" src="https://user-images.githubusercontent.com/23181390/49249373-3cbbc380-f41c-11e8-979a-11b7f8eba013.png">

**Comment by dpritos** [comment]
Same here. Application not responding on fresh install. Tried both 6.5.2 and 6.5.3.

**Comment by mariobenuzzi** [comment]
I've solved it by deleting Postman cache. Make sure you have saved your work elsewhere or in the cloud.

This is the original message I received from postman support.


Deleting your local app cache is a good place to start, and often resolves problems like this.


________________________________
!!!! PLEASE NOTE !!!!

If you were not logged in before this issue occurred (or, had sync disabled in an earlier version of Postman, prior to upgrading), DO NOT CLEAR your local app caches, as this will permanently delete your local Postman data!

Let me know if this is the case, and we can attempt a different approach!
________________________________

Postman's local app cache can be found as follows (by default):

Windows:

(On Windows: uninstalling Postman > clearing caches (below) > reinstalling Postman > yields best results)

C:\Users\<user>\AppData\Roaming\Postman

C:\Users\<user>\AppData\Local\Postman

macOS:

~/Library/Application Support/Postman


Try deleting the Postman folder at these locations, and then relaunching the app.


________________________________

**Comment by dpritos** [comment]
Mine is a fresh install, not sure if that's still applicable.

**Comment by mateja82** [comment]
Yeap, same here... deleted the cache, installed from 0, not starting

**Comment by mmahmoodictbd** [comment]
On mac, I deleted /Users/username/Library/Application Support/Postman/ directory, solved the problem.

**Comment by 0xjorgev** [comment]
Did 2 things, did moved the postman App to ~/Applications instead of /Applications and did deleted the folder that @mmahmoodictbd did mention and got it working, this happened to me on 2 different macs

**Comment by prabhuvikas** [comment]
Deleting the directory as suggested by @mmahmoodictbd  worked for me.

**Comment by ShogunPanda** [comment]
I ran in the same issue and @jorgevmendoza fix solved it for me. Kudo man.

**Comment by 4levels** [comment]
On Linux I had to do the following, not sure what eventually fixed it:
- moved Postman folder in home
  `mv ~/Postman ~/Postman.bak`
- moved configuration folder
  `mv ~/.config/Postman ~/.config/Postman.bak`

If you have enabled sync, you can as well just delete these folders allthogether..

Note that if you do start a previous installed version again, this problem re-appears and you'll have to repeat the steps above..

**Comment by aeharake** [comment]
1) Set POSTMAN_DISABLE_GPU=true in System Environmental Variables (Computer > Properties > Advanced System Settings > Environmental Variables ... )
2) Delete the Postman Folder from %AppData% both Roaming and Local.
3) Install Postman
4) Right click on the Postman shortcut and change the path, let it point to /app-7.1.1/Postman.exe (7.1.1 in my case, for ur case it might differ) instead of /Update.exe )

You don't want it to run the update.exe everytime you launch it.

**Comment by frederic-mamath** [comment]
Applied @mmahmoodictbd 's solution and it worked for me.

Thanks.
