### ISSUE TITLE
Auto update broke start menu shortcut

### ISSUE THREAD

**Issue by Y-Less** [a85/POSTMan-Chrome-Extension#5592]
Please read through the [guidelines](https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues) before creating a new issue.

**Describe the bug**

I'm not sure how I got an update, as per #2799 I mostly ignore them.  However, it seems one did, and at the same time updated the start menu shortcut to point to the new version.  But it didn't preserve the custom flags I'd set on the shortcut to bypass #4594 (which still isn't fixed, I need the GPU disabling every time).

**To Reproduce**

1. Get an update you didn't want, but seemingly still can't disable.
2. Loose your custom shortcut bypassing another bug.
3. App stops working entirely.
4. Start searching for a replacement program that isn't so terrible!

**Expected behavior**

Not update and break things.

**Screenshots**

**App information (please complete the following information):**
 - App Type [e.g. Chrome App, Native App]
 - Postman Version [e.g. 6.0.1]
 - OS: [e.g. macOS High Sierra 10.13.2]

**Additional context**

**Comment by numaanashraf** [comment]
@Y-Less The auto-update for Windows app works by downloading the new package and replacing an internal reference. At the moment there are no plans to support custom shortcuts to the internal packages or disable feature or fix updates. Closing this issue for now.
