### ISSUE TITLE
Bug in release notes dialog in Postman desktop app

### ISSUE THREAD

**Issue by JP-from-Postman** [a85/POSTMan-Chrome-Extension#5593]
**[reported on behalf of @jaysardhara by Postman Support]**

Steps to reproduce bug: 
1. Let Postman auto-download new version 
2. Restart Postman 
3. Check Release Notes 
4. Release Notes dialog would show a link to release notes and nothing else 
5. Close dialog and click Release Notes again 
6. Now dialog would properly render all details of changelog instead of showing link

**Comment by a85** [comment]
Postman doesn't have a dialog any more and renders release notes in a tab. This should fix and other issues related to rendering release notes. More improvements on this soon.
