### ISSUE TITLE
Test filter is not working when retrying the run in collection runner

### ISSUE THREAD

**Issue by ash007-postman** [a85/POSTMan-Chrome-Extension#5594]
When you perform several tests within the runner and you press the red block to show only the failed tests. Then the red block has gray around it to indicate that it is selected. 
And you retry the set of tests. 
Then the red block is still gray to indicate that it is selected 
But the list also shows the passed tests.(x) 
And I also can’t select the failing tests again, as this is already selected.(x) 
I can only select the green block and then select the red block again.

**Comment by abhijitkane** [comment]
@ash007-postman If you can still reproduce this, can you add screenshots that better illustrate this.

Also, specifying the app version/platform would help.

**Comment by numaanashraf** [comment]
Fixed in Postman v7.0.8
