### ISSUE TITLE
All data lost

### ISSUE THREAD

**Issue by verglor** [a85/POSTMan-Chrome-Extension#5601]
Once Postman app freezes for whatever reason, the workspace is totally wiped out without any chance to recover !

If user doesn't want to send all his API passwords to postman server, he has to frequently export all collections and backup them.

This bug should be either fixed or at least there should be a big bold red warning that without sync whole workspace can vanish anytime.

**Comment by numaanashraf** [comment]
@verglor This seems like a bug. Do you remember doing any specific actions in the app when you lost your workspace?

**Comment by verglor** [comment]
Nothing special - is there any log I can provide ?

**Comment by jzabroski** [comment]
@verglor Go to View -> Developer -> View Logs in Explorer

**Comment by verglor** [comment]
I already sent whole my application data folder (including logs) by email to help@getpostman.com (Request #26137)

**Comment by numaanashraf** [comment]
We've been unable to replicate this issue and we have also put in place automatic backups to disk during updates to help recover data in case isolated events like this happen again. Closing this issue.
