### ISSUE TITLE
Variables are not being resolved in pre-request script

### ISSUE THREAD

**Issue by ivanrodjr** [a85/POSTMan-Chrome-Extension#5602]
**Description**
Global variables are not being resolved in pre-request scripts.

**Steps to reproduce the behavior:**
1.  Add a global variable in Manage Environments ex: username and password
2. Use the variables in the body of the pre-request script
`body: {
            mode: 'application/json',
            raw: JSON.stringify({
        	    grant_type:'password',
        	    identifier: pm.variables.get("username"),
        	    password: pm.variables.get("password")
       	    })
        }`
3.This is what is sent in the body
`grant_type:"password"
identifier:""
password:""`

**Expected behavior**
Vlue of the variables should be added in the body when the request is sent
`grant_type:"password"
identifier:"myUsername"
password:"myPAssword"`

**Screenshots**

**App information :**
 - Native App
 - Postman Version: 6.5.3
 - OS: macOS Mojave 10.14.1

**Comment by harryi3t** [comment]
Hey @ivanrodjr,
I tried reproducing this on my end but was unable to.
Here's my pre-request script
```js
let body = {
    mode: 'application/json', 
    raw: { 
        grant_type:'password',
        identifier: pm.variables.get("username"),
        password: pm.variables.get("password")  
    }
};

pm.variables.set('body', JSON.stringify(body));
```

And this is what my body looks like (just using a local variable set in the pre-request script)
```
"{{body}}"
```

I am getting the correct data back from the server
<img width="1061" alt="postman" src="https://user-images.githubusercontent.com/5207331/49364976-8bfb4000-f70b-11e8-8d79-69c2092dbbff.png">

Also, make sure the correct values are present in the **current value** column
<img width="691" alt="postman" src="https://user-images.githubusercontent.com/5207331/49365115-f14f3100-f70b-11e8-9fc2-e6bbedd2a3d2.png">


Here's the complete collection that you can try [![Run in Postman](https://run.pstmn.io/button.svg)](https://app.getpostman.com/run-collection/d6d33c40346e4d5c22c5)

Does this collection works fine for you?

**Comment by ivanrodjr** [comment]
Hi @harryi3t 

Indeed it's working after I added the values to the current value column, thought it was added automatically. Working good, thanks for you help.

**Comment by harryi3t** [comment]
@ivanrodjr It's added automatically the first time. If later you remove the value manually then it's not auto-filled.
Glad that it worked for you.
