### ISSUE TITLE
Typo in Attribute Space Error

### ISSUE THREAD

**Issue by JacobCarrell** [a85/POSTMan-Chrome-Extension#5604]
**Describe the bug**
There is a Typo in the error message when there is no space between XML attributes 'attribute space is acequired"attribute"!!'

**To Reproduce**
1. Remove the space between two attributes in an XML POST body.

**Expected behavior**
Expect Error message to have correct spelling and punctuation.

**App information (please complete the following information):**
 - Windows ?Native? App
 - v6.5.3
 - Microsoft Windows 7

**Comment by kamalaknn** [comment]
@JacobCarrell This should be fixed in the latest version of Postman(v7.26).
