### ISSUE TITLE
An option to automatically reset the variable values ( Sync initial values with current values automatically)

### ISSUE THREAD

**Issue by Ramya-From-Postman** [a85/POSTMan-Chrome-Extension#5607]
It would be very nice to have a feature to automatically sync the initial values with the current values of an environment variable or a toggle switch to disable the use of current values in the environment variable to overcome the below problem. 

"Suppose the current value of person A is persisted to the initial value of person A and therefore synced to the initial value of person B. 
But person B does not test with the initial value but with the current value, so he stays testing with his own current value. 
And after person B has tested with his current value, this will be persisted to the initial value of person B and therefore synced to the initial value of person A. 
But person A stays testing with his current value."

So once the current values are not the same anymore, they won't get in sync unless a person selects "reset all" in the environment variables. 
But this is a manual action that should be performed by every person in the team once a team member has updated an initial value.

**Comment by a85** [comment]
The manual action is an intended behavior.

**Comment by mennopot** [comment]
Hi Abhinac Asthana.
I do understand that the manual action is intended.
My big question is, how can I make sure we all run the same tests with the same values.
Please let me know how this is possible.
I just can't understand that I'm the only one having this desire and therefore facing this issue.

I really love Postman, but I have to say that this strange behavior of the app as well as the way tickets are handled makes me sad. I hope we can change this to prevent that I need to look for workarounds.

Thanks in advance.

Wkr, Menno Pot

**Comment by mennopot** [comment]
Hi,

As I just can't understand why it's programmed like this, could you please help me by explaining this.
There is a toggle to automatically persist your value after performing a test. 
This persisted value is synced, but not used unless you manually reset it.
So what's the use of an automated step to store values, which you can't automatically use. We're talking about a tool for test automation here. We're not in the 90's where we only do manual testing.

I do understand that some people like to have a personal current value like a username / password. But does that mean that all the others that don't use the values like this, need to be punished with manual actions?

Wkr, Menno

**Comment by a85** [comment]
@mennopot There are several issues related to collaboration, security etc. I had written about it in an RFC a while back that you can find here: https://community.getpostman.com/t/sessions-in-postman/1925

Running the same tests with the same values is possible already but we enforce a manual step so there is no magic behavior in somebody else's session in a collaborative workflow. Sessions will ultimately be shareable in real-time but for now they aren't due to technical limitations.
