### ISSUE TITLE
App unresponsive during initial sync

### ISSUE THREAD

**Issue by godfrzero** [a85/POSTMan-Chrome-Extension#5609]
**Describe the bug**
Upon launching the app, the UI is unresponsive when engaging in certain actions (opening a request, starting a collection run, etc.) until the initial sync is complete. Once syncing is complete, my actions seem to "replay" in the order that I performed them.

**To Reproduce**
1. Open the app
2. While the app is syncing, click on a request in the sidebar to open it.
3. Observe that it does not open. Click on another if the app is still syncing.
4. Observe that it does not open.
5. Wait for the app to finish syncing
6. Observe that the first request I opened and the second request I opened both open, in series.

**Expected behavior**
I should be able to interact with the app and various features regardless of the syncing state.

**App information (please complete the following information):**
Postman for Mac
Version 6.6.0 (Happens in previous versions as well, not sure which version first presented with this issue)
OS X 18.2.0 / x64

**Comment by Ghusar** [comment]
@godfrzero  Is this issue still relevant after 7.x update?

**Comment by kamalaknn** [comment]
@Ghusar With the recent improvements to the syncing process in Postman 7.x, I think the intensity and the duration of this would have reduced. But I do not think this issue would be entirely eliminated by it.
