### ISSUE TITLE
Let the user know if request failed due to missing variables

### ISSUE THREAD

**Issue by godfrzero** [a85/POSTMan-Chrome-Extension#5612]
**Is your feature request related to a problem? Please describe.**
It's common for requests to fail if there are unresolved variables. In the vast majority of cases, this is not intended by the user. The "error" state displayed when this happens isn't very helpful and can lead to journeys down rabbit holes and eventual dead ends.
This especially seems to be a problem when new users are being on-boarded onto the app, and it's a stumbling block which can be easily removed.

<img width="712" alt="screenshot 2018-12-06 at 10 31 53 am" src="https://user-images.githubusercontent.com/2700229/49562595-365ca880-f942-11e8-8874-84cc9f9335a3.png">

**Describe the solution you'd like**
* Include something like "There are unresolved variables, make sure you have an environment/the correct environment selected" or something along those lines.

**Describe alternatives you've considered**
Being very careful.

**Comment by a85** [comment]
Similar to #285. Closing as duplicate.
