### ISSUE TITLE
Inactive GET parameter is deleted on saving request

### ISSUE THREAD

**Issue by chimit** [a85/POSTMan-Chrome-Extension#5613]
**Describe the bug**
If we have two similar parameters and mark the first one inactive it is deleted on saving. But if we mark the second parameter as inactive it stays.

**To Reproduce**
1. Create two GET parameters with the same name
2. Uncheck the first one
3. Save the request
4. Parameter is deleted

**Expected behavior**
Unchecked parameters should not be deleted.

**Screenshots**

Create two similar params and save a request. It's OK:

![image](https://user-images.githubusercontent.com/839349/49570833-a1be6e80-f972-11e8-8239-65c02bd2d9ec.png)

I uncheck the second one and save. It's OK:

![image](https://user-images.githubusercontent.com/839349/49570847-aa16a980-f972-11e8-9e01-26599b5367cb.png)

I uncheck the first one and save. It's disappeared:

![image](https://user-images.githubusercontent.com/839349/49571109-5e183480-f973-11e8-98b9-9f5ae4494bc3.png)

**App information (please complete the following information):**
 - App Type Native App
 - Postman Version 6.5.3
 - OS: macOS Mojave

**Additional context**

**Comment by numaanashraf** [comment]
We've included a fix for this issue in Postman v7.1.0
