### ISSUE TITLE
Pro subscribers are being asked to upgrade to view a longer trash history

### ISSUE THREAD

**Issue by abhijitkane** [a85/POSTMan-Chrome-Extension#5617]
Please read through the [guidelines](https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues) before creating a new issue.

**Describe the bug**
I'm on a Pro team, and going to https://go.postman.co/me/trash shows a message saying:
"Find and restore your deleted resources from the Trash. Resources will be removed from the trash automatically after 30 days. Want a longer trash history? Upgrade"

**Expected behavior**
Pro teams should not be asked to upgrade - this is supposed to be a Pro offering

<img width="1362" alt="screen shot 2018-12-06 at 23 11 40" src="https://user-images.githubusercontent.com/681190/49601699-91c38080-f9ac-11e8-8b41-eeb94e13f1cb.png">

**Comment by abhijitkane** [comment]
If I'm being asked to upgrade to Enterprise, the message should indicate that, not just 'Upgrade'

**Comment by jzabroski** [comment]
"You want to pick through your garbage?!  You need to pay to do that." -- only in a SaaS context could this ever be possible way of making money

**Comment by ankit-m** [comment]
A fix for this has been deployed.
