### ISSUE TITLE
Pro users cannot view anything /me/trash page

### ISSUE THREAD

**Issue by abhijitkane** [a85/POSTMan-Chrome-Extension#5618]
Please read through the [guidelines](https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues) before creating a new issue.

**Describe the bug**
I'm on a Pro team, and going to https://go.postman.co/me/trash shows a "Something went wrong" message. The WS console shows a 500 response for the `/collection-trash?uid=true` call after 50 sec.

**Comment by a85** [comment]
@abhijitkane Can't seem to replicate this. @ankit-m @preethammavin Can we check issues like this and start closing if they are fixed or can't be replicated?
