### ISSUE TITLE
Error in Internet view 

### ISSUE THREAD

**Issue by muratatak77** [a85/POSTMan-Chrome-Extension#5619]
Page doesnt open and get this errror : 

![screen shot 2018-12-06 at 3 21 50 pm](https://user-images.githubusercontent.com/4965162/49617769-beef3f00-f96a-11e8-8da7-9c4f02bb6905.png)

**Comment by ankit-m** [comment]
We have fixed this issue and are testing it on our beta platform. Will update this thread once the fix is deployed.

**Comment by ankit-m** [comment]
A fix for this has been deployed.
