### ISSUE TITLE
Able to see file not chosen, but after sending request, Image is uploading.

### ISSUE THREAD

**Issue by Sainath77601** [a85/POSTMan-Chrome-Extension#5621]
Please read through the [guidelines](https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues) before creating a new issue.

**Describe the bug**
able to upload image with invalid message saying "No file chosen".

**To Reproduce**
1. Go to any Collection.
2. Create a request.
3. Pass parameter value with file.
4. Click on choose files.
5. Select an Image. (Ex : jpg, png)
6. Click on Send button. (Send a request).
7. Copy the request with Parameters.
8. Open new tab.
9. Paste copied request with parameter value as "No file chosen".
10. Click on send button. (Send a request).

**Expected behavior**
After Clicking on send button "Error Message should be displayed". 

**Screenshots**

**App information (please complete the following information):**
 -  Native App.
 - Postman Version 6.5.3
 - OS: Windows 10

**Additional context**
"After Copying Parameter Value with file option to the another request, It is taking previous request parameter Value file".

**Comment by numaanashraf** [comment]
Fixed in Postman v7.0
