### ISSUE TITLE
[BUG] HTTP tab of "Generate Code Snippets" view is inaccurate

### ISSUE THREAD

**Issue by PetrusKiendys** [a85/POSTMan-Chrome-Extension#5622]
**Describe the bug**
The HTTP tab of the "Generate Code Snippets" view does not encode and delimit the request body correctly, delimiters are completely omitted.

By comparison if I have a request (cURL tab):
```
curl -X POST \
  https://example.com/hello/world \
  -d 'foo=bar&baz=quux'
```
We can see that the POST request body is correctly delimiting keys and values.

However for the (HTTP tab):
```
POST /hello/world HTTP/1.1
Host: example.com
foo=barbaz=quux
```
The subsequent keys are concatenated with the previous value, there's no delimiter between the "bar" value and the "baz" key, in this case.

**To Reproduce**
1. Create a POST request with at least two key-value pairs in the Body
2. Click on 'Code' (upper-right, under the blue "Send" and grey "Save" buttons) to access the "Generate Code Snippets" view
3. View the HTTP tab and observe the incorrect presentation of the request

**Expected behavior**
A correct HTTP request should be presented in the HTTP tab.

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version: Postman for Linux Version 6.5.3; linux 4.15.0-39-generic / x64
 - OS: Linux, Xubuntu 18.04.1 LTS (Bionic Beaver)

**Additional context**
Related bug reports https://github.com/postmanlabs/postman-app-support/issues/2780.

**Comment by abhijitkane** [comment]
Not able to reproduce this anymore. Also, in Postman 7.2.1, we've introduced bug-fixes, support for two new languages (JS-Fetch and Powershell), and the ability to configure certain aspects of the generated snippet with the 'Experimental Codegen Mode' flag enabled in Postman's global settings.

@PetrusKiendys Do add a comment if you're still seeing this issue in 7.2.1.

**Comment by kkoenen** [comment]
Same problem here. In the menu, For instance, "JQuery AJAX" and "XHR" are not visible. Workaround : F11 (full screen). Version 7.2.2.

![afbeelding](https://user-images.githubusercontent.com/1116248/59781884-162c7f80-92bd-11e9-9f66-89a8c648379f.png)

**Comment by abhijitkane** [comment]
@kkoenen The original issue seems to be around encoding URL parameters in the generated snippet, not scroll issues with the dropdown.

I'm unable to reproduce the first issue anymore. Feel free to comment if you're still seeing issues with encoding.

If you're still seeing the second issue (scrolling), opening a separate issue will help us track it better.
