### ISSUE TITLE
Postmans "An update is ready to install" dialog consumes 100% CPU while logged into different MacOS User Account

### ISSUE THREAD

**Issue by konradjurk** [a85/POSTMan-Chrome-Extension#5623]
**Describe the bug**
Postman 6.3.0 is running in MacOS. When you switch to a different system-user account and the Postman instance finds an update, it consumes 100% CPU forever until you switch back and close it. I read the patch notes for the succeeding versions but couldn't find a note that this was fixed.

**Screenshots**
<img width="629" alt="bildschirmfoto 2018-12-07 um 15 59 10" src="https://user-images.githubusercontent.com/6976170/49655249-73a46180-fa3a-11e8-8320-b35840dafcc7.png">

**App information (please complete the following information):**
 - MacOS Postman
 - Postman Version 6.3.0 - 6.6.0
 - OS: macOS 10.12.5

**Comment by konradjurk** [comment]
As suspected it still occurs with version 6.6.0

**Comment by kamalaknn** [comment]
@konradjurk Are you still seeing this in the latest version of Postman?

If yes can you send the logs to help us debug this. You can find the logs in `View -> Developer -> View logs in Finder`

After removing any sensitive information in them you can send them to `help@getpostman.com`

**Comment by numaanashraf** [comment]
Thank you for your issue! With only the details that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have more information for us that'll help us debug/triage this issue.
