### ISSUE TITLE
Mark unsaved to file collection with italics font

### ISSUE THREAD

**Issue by m3dbedb** [a85/POSTMan-Chrome-Extension#5624]
**Is your feature request related to a problem? Please describe.**
Sometimes I need to open two postman instances and it's hard to understand when there are unsaved collections

**Describe the solution you'd like**
It is common practice to mark unsaved documents

**Describe alternatives you've considered**
Mark unsaved colection with arterisk

**Additional context**
If you suppose that some people doesn't need the feature, you may add it in options, if enabled, unexported collection would be marked someway.

**Comment by giridharvc7** [comment]
Unsaved entities in Postman are marked with a visual indicator now, let us know what you think @m3dbedb 
<img width="463" alt="Screenshot 2021-04-27 at 7 52 11 PM" src="https://user-images.githubusercontent.com/1040583/116257893-112a9800-a792-11eb-93d6-e41c565aec92.png">
