### ISSUE TITLE
Monitor alert emails contain text "FAILURES in run at Invalid date UTC"

### ISSUE THREAD

**Issue by JP-from-Postman** [a85/POSTMan-Chrome-Extension#5625]
[Submitted by Postman Support, on behalf of user]

**User report:**
> our alerts do not appear to contain valid timestamps any more. They simply state "Invalid date UTC".

**Comment by ankit-m** [comment]
@JP-from-Postman what alerts are being talked about here? Emails?

**Comment by godfrzero** [comment]
We've pushed out a fix for this, and this issue should not be occurring anymore.
