### ISSUE TITLE
Global proxy refuses connection

### ISSUE THREAD

**Issue by adispennette** [a85/POSTMan-Chrome-Extension#5626]
Attempting to send Postman requests through ZAP proxy fails for connection refused.

**To Reproduce**
1. Open OSWAP ZAP application
2. Open settings dialog
3. Go to Local Proxies
4. Set address to localhost and port to 9972 (this is what I was using)
5. Open Postman 
6. Set global proxy to to the same settings above
7. Attempt to execute an request to http://localhost:9072/application/controller (replace with your test app url with port)

**Expected behavior**
The request should get routed through ZAP and recorded

**Screenshots**
![screen shot 2018-12-07 at 2 40 04 pm](https://user-images.githubusercontent.com/9353714/49676311-19050880-fa2e-11e8-9883-136ad4f24b99.png)
![screen shot 2018-12-07 at 2 46 09 pm](https://user-images.githubusercontent.com/9353714/49676542-f3c4ca00-fa2e-11e8-907d-0f11fb84316d.png)

**App information:**
 - Java/Spring boot REST
 - Postman Version 6.5.3
 - macOS High Sierra 10.13.6
 - OSWAP ZAP 2.7.0

When setting Firefox to use the ZAP proxy I see the request get intercepted and recorded but this does not occur when executing the same command with the same URL in Postman.

**Comment by vikiCoder** [comment]
Hi,

This issue is fixed in the latest release of Postman App (v7.14.0). Please update your Postman app to the latest version and let us know if you are still facing any issues regarding this.
