### ISSUE TITLE
The 'Usage' column sorting on the Monitoring usage page sorts alphabetically, not numerically

### ISSUE THREAD

**Issue by abhijitkane** [a85/POSTMan-Chrome-Extension#5627]
On https://go.postman.co/usage/monitors, clicking on the 'Usage' column header sorts by the alphabetical value of usage, not the numeric value. See screenshot.

<img width="502" alt="screen shot 2018-12-08 at 17 28 15" src="https://user-images.githubusercontent.com/681190/49685732-d2d3a600-fb0e-11e8-8c2e-34c7993ebc90.png">

**Comment by ankit-m** [comment]
@dhineshwiz friendly bump.

**Comment by dhineshwiz** [comment]
hey @abhijitkane thanks for reporting the issue, It looks like the vendor library which we are using is sorting with default javascript sort `Array.prototype.sort()` which sorts by string. We will fix it by adding custom sorting method, and keep this thread updated

**Comment by ankit-m** [comment]
A fix for this has been deployed.
