### ISSUE TITLE
postman doesn't open in maximized window at start

### ISSUE THREAD

**Issue by alikrc** [a85/POSTMan-Chrome-Extension#5629]
Its a basic bug. Postman doesn't open in maximized window at start in windows 10. There is an empty space gap at outer bounds. It becomes annoyig after some time. Please fix it.

![image](https://user-images.githubusercontent.com/2185905/49722822-9ae77280-fc76-11e8-9f68-0d371d04bfa2.png)
![image](https://user-images.githubusercontent.com/2185905/49722836-a33fad80-fc76-11e8-931b-0feb53d39b78.png)

**Comment by numaanashraf** [comment]
@HasanAliKaraca We do not automatically maximize, and window position and sizes are a matter of subjective preference. You can manually maximize if you prefer that and Postman would remember your last used window position and size in further launches.

**Comment by gogis79** [comment]
Postman does not remember maximized state though. It drives me nuts. Since I use it on and off to quickly check my API calls and its neither have "minimize into tray" option it's standard routine - 1) start it 2) maximize it

**Comment by RNovachkov** [comment]
@gogis79 is write! Please fix it.
