### ISSUE TITLE
Slack integration not receiving messages

### ISSUE THREAD

**Issue by RT-TL** [a85/POSTMan-Chrome-Extension#5630]
**Describe the bug**
I installed the slack integration for my monitor. The authorization works fine and Slack is showing Postman with the proper rights. However, no results (neither success nor failure) get actually send to Slack.

**To Reproduce**
I deleted the slack integration and set it up again: Same result.

**Expected behavior**
Monitor results being displayed in slack.

**Screenshots**
![image](https://user-images.githubusercontent.com/13029793/49784057-4eef0900-fd1c-11e8-8845-761ebafb5a0a.png)

**Comment by kartikjain26** [comment]
@RT-TL Can you confirm if the collection associated with your monitor is present in the workspace and if the monitor itself ran as per the schedule.

**Comment by RT-TL** [comment]
@kartikjain26 Yes, I can confirm that. The monitors are running and I can see them in the workspace. I also do receive the notification emails, can access the log etc. Here are two screenshots from the dashboard showing a bit of configuration which looks good to me.

<img width="641" alt="screenshot 2018-12-14 at 13 04 04" src="https://user-images.githubusercontent.com/13029793/50002556-c3d27500-ffa0-11e8-9f37-8c4cec72fe6c.png">
<img width="655" alt="screenshot 2018-12-14 at 13 03 58" src="https://user-images.githubusercontent.com/13029793/50002558-c3d27500-ffa0-11e8-97c6-100c0aa8e469.png">

**Comment by VicKetchup** [comment]
Our team has 10 monitors that were setup since 6th of September 2018 and today none of them have displayed the results! Running the monitors manually has also not displayed anything.
@kartikjain26 Please tell us if there is anything we can do to investigate this issue and get it resolved.

**Comment by kartikjain26** [comment]
@VicKetchup Can you setup a new monitor-> slack integration and test if it works.

**Comment by VicKetchup** [comment]
@kartikjain26 we are also using Postman API to get monitor results and display the data in more meaningful way. Creating new monitors/integrations every time this happens is really not the solution that works for us.

**Comment by RT-TL** [comment]
@VicKetchup did setting it up again actually change something for you? We tried that, too but the monitors remain silent.

**Comment by VicKetchup** [comment]
@RT-TL Unfortunately I am not a Slack Admin, I've requested devops for integration to be added to test this and will share the results as soon as possible.

**Comment by VicKetchup** [comment]
An update on the situation, the Slack integration has worked today.

**Comment by preethammavin** [comment]
The issue has been fixed.
