### ISSUE TITLE
Variable evaluation in Example Response/Mock Body

### ISSUE THREAD

**Issue by ghost** [a85/POSTMan-Chrome-Extension#5631]
<img width="838" alt="screen shot 2018-12-11 at 9 38 02 am" src="https://user-images.githubusercontent.com/5994259/49788494-c6776500-fd29-11e8-8712-e4c192f98969.png">
This may potentially be beyond the scope of mocks, but although reading from environmental/global variables seems to function in headers and endpoints, they aren't evaluating in the bodies of example responses (like they would in request bodies). See attached screenshots!

**Comment by ratpik** [comment]
The variable `{{$timestamp}}` is a dynamic variable that is part of the Postman Sandbox which is a module used by the Postman Runtime which is responsible for resolving such special values during script execution (pre-request/test, request sending, etc). Mocks in Postman do not execute javascript. To resolve environment variables in Mock, you need to specify the environment that has the corresponding key/value pair during the creation of the Mock.
