### ISSUE TITLE
Postman 6.1.4 screen not getting loaded

### ISSUE THREAD

**Issue by soodri** [a85/POSTMan-Chrome-Extension#5633]
Everytime i try opening postman , it gets sturck and doesn't open up. Either it takes hours to open up . 
I tried uninstalling and installing the postman , but still not resolved . 

Mouse cursor keeps blinking and black screen of postman is shown.

**Comment by numaanashraf** [comment]
Duplicate of #4594. Please try the workaround detailed at https://github.com/postmanlabs/postman-app-support/issues/4594#issuecomment-391601621.
