### ISSUE TITLE
Minor. Default Start In folder and Icon folder to be paths that are NOT version-specific.

### ISSUE THREAD

**Issue by mkamoski** [a85/POSTMan-Chrome-Extension#5635]
Please read through the [guidelines](https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues) before creating a new issue.

**Is your feature request related to a problem? Please describe.**

Default the Start In folder and the Icon folder to be paths that are NOT version-specific.
Very minor, but he Icon path breaks and the Start Up folder seems to break after each update.

**Describe the solution you'd like**
Maybe use the icon from here...
C:\Users\Blah\AppData\Local\Postman\Update.exe
...and use this as startup...
C:\Users\Blah\AppData\Local\Postman\
...and that seems to work for me.

**Describe alternatives you've considered**
As above, a manual change seems to work.

**Additional context**
I am on Windows 7 (ug).

Thanks.

-- Mark Kamoski

**Comment by SamvelRaja** [comment]
This has been fixed in https://github.com/postmanlabs/postman-app-support/issues/4814

Could you verify the same.

I have also tried reproducing it, It is properly changing the icon path in the shortcut present in
```
C:\Users\User\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Postman
```
