### ISSUE TITLE
Expand-collapse long string

### ISSUE THREAD

**Issue by yagotome** [a85/POSTMan-Chrome-Extension#5637]
I have been using Postman to request some APIs that returns JSON containing some string fields too long and then I have missed a feature to collapse/expand string.

Something similar is requested in #895 . I suppose they are different features but have some common things.

**Comment by numaanashraf** [comment]
Duplicate of #5600

**Comment by yagotome** [comment]
@numaanashraf #5600 suggests collapsing all fields of an object. What I suggested was collapsing **string** fields independently of being or not in an object. They are different features, aren't they?
