### ISSUE TITLE
"Could not get any response" when invalid header

### ISSUE THREAD

**Issue by rj93** [a85/POSTMan-Chrome-Extension#5638]
Please read through the [guidelines](https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues) before creating a new issue.

**Describe the bug**
When attempting to make a request with an invalid header, for example "Content Type ", postman displays a "Could not get any response" message. This is misleading as the request wasn't actually sent, and I had to look into the logs to see that there was an error.

**To Reproduce**
1. Create any request
2. Add the header ket "Content-type "
3. add the value "application/json"
4. send the request

**Expected behavior**
An error message detailing the incorrect header visible

**Comment by shamasis** [comment]
Just to provide an update here. We have done preliminary design work to bring more response related errors in the response area.

**Comment by codenirvana** [comment]
We are tracking this here: #4485, https://github.com/postmanlabs/postman-app-support/issues/5045#issuecomment-415702793

Also, according to [RFC7230](https://tools.ietf.org/html/rfc7230#section-3.2.4):
```
No whitespace is allowed between the header field-name and colon.
```

> An error message detailing the incorrect header visible

Agree, please subscribe to the above mentioned issue for updates.
