### ISSUE TITLE
Collection getting imported multiple times when using RiP button [Windows]

### ISSUE THREAD

**Issue by sivcan** [a85/POSTMan-Chrome-Extension#5639]
**Describe the bug**
On clicking the RiP in the browser on a windows machine, the app imports the collection multiple times. If the collection already exists then the modal opens up saying 'Do you want to replace this or import as a copy', even on choosing to replace it, it imports the collection multiple times.

Other OS behaviour:
-  Mac: Not reproducible
- Linux: Needs to be tested

**To Reproduce**
(Make sure you're doing this on a windows machine)
1. Open Postman
2. Go to the following documentation: https://documenter.getpostman.com/view/3407886/RWgp1fB5
3. Click on 'Run In Postman'
4. Gives windows access to open Postman and let it launch the app
5. It might import properly / might duplicate multiple times **_(THE BUG)_**
6. Go back to the browser on the documentation url mentioned in Step 2.
7. Click on RiP again and import using the Postman App
8. App shows that this collection already exists and click on 'Replace', the modal wouldn't dismiss
9. Repeatedly click on 'Replace' / 'Import as Copy'
10. Observe the number of collections

**Expected behavior**

**Screenshots**
Reported and screen recoding by @divyang-desai (original reporter of this issue):
![bug](https://user-images.githubusercontent.com/12631777/49926504-b2766380-fee1-11e8-8ed0-2c0c1b93c0f1.gif)

**App information (please complete the following information):**
 - App Type - Native App
 - Postman Version - v6.6.1
 - OS: Windows 10 (64bit)

**Additional context**
[Filed by Postman]

Originally reported in https://stackoverflow.com/questions/53745181/import-collection-using-button-importing-same-collection-multiple-times-postma

**Comment by numaanashraf** [comment]
Fixed in Postman v7.0.8
