### ISSUE TITLE
Themes settings is only stored localy and not synced to my account

### ISSUE THREAD

**Issue by mictoln** [a85/POSTMan-Chrome-Extension#5640]
I work with postman on my work computer and at home, on my personal computer. When I do a theme setting at work it seems like it is stored localy and not synced to my account. Because when I get home I have to do the same setting again.

I think it would be a nice feature if this setting was synced to the account. What do you say? put this on your backlog :-)

**Comment by a85** [comment]
Settings for themes are currently local to the desktop installation. It's not a regular action as mostly we see people changing themes once in a while. A more general version of syncable settings will be available in the future. For now, closing this issue.
