### ISSUE TITLE
Log of function prints null in console

### ISSUE THREAD

**Issue by Alexsey** [a85/POSTMan-Chrome-Extension#5642]
**Describe the bug**
Logging of a function in Pre-Request or Test script will prints `null` in console

**To Reproduce**
1. Open any request the may be executed
2. Open `Pre-Request` section
3. Add code `console.log(() => {})`
4. Execute request
5. Look at the console

**Expected behavior**
In case of v8 it would output `[Function]`. I think would be good for Postman as well

**App information (please complete the following information):**
 - App Type [Native App]
 - Postman Version [6.6.1]
 - OS: [Windows 10]

**Comment by coditva** [comment]
@Alexsey This issue is fixed and out in the latest Postman App `v7.12.0` near you!  🎉
