### ISSUE TITLE
API Documentation Versioning

### ISSUE THREAD

**Issue by norchow** [a85/POSTMan-Chrome-Extension#5650]
I'm developing an API, and new changes are being included. I need a clear way for the users to select which version of the API they are using and get its documentation.

I would love if my users could select which version of the API they are using, maybe similar to how they choose an environment.

Locally, i cloned the collection with the previous version of the API, and modified it for the newest version. What i can't do is to publish this new collection *alongside* the previous one. Should i publish several collections?
Another option is to separate in different folders, but i think it affects heavily the UX.

I really look forward to see this feature in the (already great) Postman Documentation product.

**Comment by norchow** [comment]
I keep thinking about it, and i think it can work for us if we can publish several collections (one for each version) and make them available as subdirectories.

For example: 
https://developers.bitex.la refers to Bitex API V2.0
https://developers.bitex.la/v2.1 can refer to Bitex API V2.1 (and so on).

Maybe we can even configure the subdirectory as an attribute of the collection. 

I don't know if there is another use case for having multiple collections grouped together, but i would love to hear and collaborate for those cases.

**Comment by a85** [comment]
@norchow Thank you for submitting the feature request! We are working on something that will help enable this.
@vkaegis Let's talk about this in the context of versioning + version tags.

**Comment by Raja-Simha** [comment]
@norchow, you can now add/enable versions to your private and public documentation. Do refer to our docs here https://learning.getpostman.com/docs/postman/design_and_develop_apis/versioning_an_api/ and leave your feedback/comments.

**Comment by DLTKMonBlaza** [comment]
The current versioning Postman support only works if you're maintaining documentation for multiple versions that are not simultaneously active.

For example, I have Documentation for API 1.0 and 2.0. Both these versions are currently active, meaning there are updates made for 1.0 (like 1.0.1, 1.0.2 and so on) and also for 2.0 (2.0.1, 2.0.2, and so on). How do you go about effectively reflecting the changes for both active major versions in terms of documentation whilst sharing the same publication custom domain?

The current solution assumes that when a new doc version is available, the previous version will remain as is and will no longer change moving forward.

**Comment by arlemi** [comment]
@Mon-Blaza You should be able to update previous versions of your documentation without issue. Could you walk us through the issues you're facing when trying to update a previous version of a documentation?
