### ISSUE TITLE
Postman doesn't recognize a valid openapi 3 yaml file

### ISSUE THREAD

**Issue by damaru-inc** [a85/POSTMan-Chrome-Extension#5651]
**Describe the bug**
I created an openapi 3 file, and I'm using Swagger to generate the API code. That works fine, so I'm confident that my file is valid.

**To Reproduce**
1. Open Postman
2. Click Import
3. Select the file - I've copied it here, it's not very long
4. Postman shows the message: Error while importing: format not recognized

**Expected behavior**
I would expect the file to be imported successfully.

**App information (please complete the following information):**
 - App Type - Native OSX
 - Postman Version 6.6.1
 - OS: 

macOS High Sierra 10.12.6

**Additional context**
Here's the file:
```
openapi: 3.0.0
info:
  title: 'test'
  description: 'test'
  version: '0.1.0'

# Basic authentication
components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
security:
  - BasicAuth: []

# Describe your paths here
paths:
  /v1:
    get:
      summary: Reports status information.
      description: Reports status information.
      operationId: getV1Status
      tags:
        - Version
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Info'
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /v1/login:
    post: 
      tags:
        - login
      summary: login
      description: login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Login'
      operationId: login
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Welcome'
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          $ref: '#/components/schemas/Error'
components:
  schemas:
    Error:
      type: object
      properties:
        status:
          type: string
    Info:
      type: object
      properties:
        status:
          type: string
    Location:
      type: object
      properties:
        ssid:
          type: string
        longitude:
          type: double
        latitude:
          type: double
    Login:
      type: object
      properties:
        username:
          type: string
          description: username
        password:
          type: string
          description: password
        location:
          schema:
            $ref: '#/components/schemas/Location'
    MessageBrokerConnection:
      type: object
      properties:
        host:
          type: string
        password:
          type: string
        port:
          type: integer
        username:
          type: string
        vpn:
          type: string
    Welcome:
      type: object
      properties:
        userId:
          type: string
        room:
          type: string
        messageBrokerConnection:
           schema:
             $ref: '#/components/schemas/MessageBrokerConnection'
```

**Comment by abhijitkane** [comment]
@damaru-inc I see the root-level 'components' property is defined twice - line 8 and line 61. The spec should convert after merging the two. We'll work on showing better error messages.

**Comment by harryi3t** [comment]
@damaru-inc Thank you for reporting this issue.
Postman uses [openapi-to-postman](https://github.com/postmanlabs/openapi-to-postman) plugin for the conversion which has it's own repository. I have opened an issue there https://github.com/postmanlabs/openapi-to-postman/issues/7
Kindly subscribe to that issue for the updates.

**Comment by damaru-inc** [comment]
Thanks a lot!

Michael

**Comment by developedsoftware** [comment]
I am still having this issue..has it been fixed?

**Comment by yadigarbz** [comment]
Hi everybody, I just realize in my swagger json output; there is no version in Api Info section,
if you can check manuals and detect this kind of glitch and write as response to here it might save someones' days.

```
"info": {  // -> **Parent info section**
    "title": "Auth V2 API",
    // "version": "2.0.0" -> **I added this line**
  }
```

**Comment by gonazmul** [comment]
> Hi everybody, I just realize in my swagger json output; there is no version in Api Info section, if you can check manuals and detect this kind of glitch and write as response to here it might save someones' days.
> 
> ```
> "info": {  // -> **Parent info section**
>     "title": "Auth V2 API",
>     // "version": "2.0.0" -> **I added this line**
>   }
> ```

Lifesaver! This worked for me. Not sure why that does not automatically get generated in the OpenApi json.
