### ISSUE TITLE
Export and import of collection from file does not preserve the order of requests

### ISSUE THREAD

**Issue by hpete** [a85/POSTMan-Chrome-Extension#5653]
Export and import of collection from file does not preserve the order of requests

**To Reproduce**
1. Create a collection with multiple requests
2. Export collection to file (Collection v2.1 (recommended))
3. Import collection from file
4. Order of request in collection is not the same

**Expected behavior**
Order of requests in collection should be the same. 

**App information (please complete the following information):**
Postman 6.5.2, linux-4.15.0-42-generic on x64

**Comment by numaanashraf** [comment]
@hpete Could you share a screenshot showing the issue? We are not able to replicate this our end.

**Comment by numaanashraf** [comment]
Thank you for your issue! With only the information that is currently in the issue, we don't have enough details to take action. I'm going to close this but don't hesitate to reach out if you have more information for us that'll help us debug and triage this issue.
