### ISSUE TITLE
Environment Edit issues via Quick Look

### ISSUE THREAD

**Issue by harryi3t** [a85/POSTMan-Chrome-Extension#5654]
Originally reported by gopikrishna4595 on Postman Discourse community https://community.getpostman.com/t/environment-edit-issues-via-quick-look-6-6-0/3559

When editing the environment variable via quick look, the next successive variable value is also updated with the same. Refer to the attached gif for better understanding.

[REDACTED]

and also once the variable value updated from Quick look and to confirm when checked from Manage Environment option - the variable is still holding the OLD value . This inconsistent behavior is highly intermittent.

I observed the above mentioned abnormal behavior from 6.5.2 version Windows.

**Comment by numaanashraf** [comment]
Fixed in Postman v7.0.8
