### ISSUE TITLE
Provide an option to configure generation of code snippets in the documentations

### ISSUE THREAD

**Issue by Ramya-From-Postman** [a85/POSTMan-Chrome-Extension#5655]
It would be very nice if we have an option to configure the generation on code snippets on the postman documentation.
For example, the curl command of a request: https://postman-echo.com/get in the documentation looks like :
![image](https://user-images.githubusercontent.com/40994626/50079643-1fef0080-0210-11e9-8992-10a8aa8f9918.png)
In the above command, Why do we have to use "--request" while it can be replaced with "-X" and
 "--location" when we can use "-L". They are shorter and take less space.

**Comment by Cazaimi** [comment]
@Raja-Simha, this can be marked as closed as this operation is now possible via the code generation settings
![Screenshot 2020-02-17 at 6 47 25 PM](https://user-images.githubusercontent.com/13660453/74657348-0bace780-51b6-11ea-9c74-b253c1fdb0f0.png)
