### ISSUE TITLE
为啥 postman 更新版本后，把环境变量位置的“Bulk Edit”功能给去掉了？

### ISSUE THREAD

**Issue by shadow000902** [a85/POSTMan-Chrome-Extension#5656]
之前的历史版本，编辑环境变量的时候，也是可以使用“Bulk Edit”模式的，但是更新了版本后，就不支持这个功能了，现在整理环境变量非常的麻烦，能否把这个功能加回去？

**Comment by numaanashraf** [comment]
Duplicate of #4898
