### ISSUE TITLE
Cannot save new request

### ISSUE THREAD

**Issue by aowie1** [a85/POSTMan-Chrome-Extension#5657]
**Describe the bug**
Error occurs while attempting to save a new request.

**To Reproduce**
1. Open existing request and alter
1. Choose Save As
2. Navigate to a folder directory pane
4. Click "Save to <folder>"

**Expected behavior**
I expect it to create a new request within that folder

**App information (please complete the following information):**
 - Native App
 - v6.6.1
 - macOS High Sierra 10.13.6

**Additional context**
Console output: 
```
Code: "E_INVALID_NEW_RECORD
Invalid new record.↵Details:↵  Could not use specified `dataMode`.  Violated one or more validation rules:↵  • Value failed custom validation

console.error @ vendor-shared.js:120326
Object.then.catch.err @ RequesterModalContainer.js:21756
```

**Comment by sujayvenaik** [comment]
Hey, @aowie1  Can you update to the latest version and try this on the latest version (v7.x)?

**Comment by numaanashraf** [comment]
With only the details that is currently in the issue, we don't have enough information to reproduce this issue and take action. We're going to close this but don't hesitate to reach out if you are still facing this issue.
