### ISSUE TITLE
Beautify for JSON in raw request rounds long numeric values

### ISSUE THREAD

**Issue by wiesniak** [a85/POSTMan-Chrome-Extension#5658]
**Describe the bug**
When I use Beautify in request body text area for json, ulong value is rounded.

**To Reproduce**
1. Open new tab
2. Select POST request method
3. Select "Body" tab
4. Select "raw" radio button and "JSON (application/json)" content type
5. Paste in text area
`{"id":8741825358579525632}`
6. Click "Beautify"
7. See formatted JSON - it is
```
{
    "id": 8741825358579526000
}
```

**Expected behavior**
I expected to see
```
{
    "id": 8741825358579525632
}
```

**App information:**
 - Native App
 - Version 6.6.1
 - OS: Windows 10 Pro 10.0.17134

**Comment by awalland** [comment]
i'd like to add that also `0` decimal places are removed if they are unnecessary, which might not always be wanted.
beautifying the following payload:
```
{
  "someValue": 60.0
}
```
becomes 
```
{
    "someValue": 60
}
```

while i agree that this shouldn't make a difference, with some APIs it does and i don't like a reformatting functionality changing my requests payload values.

**Comment by armoour** [comment]
can this issue be solved this year?

**Comment by pankajk07** [comment]
We have fixed this as part of v7.26. Please try it out and let's us know if you find any other issues.

**Comment by Maheshoptiva** [comment]
@arlemi still I am facing same issue about "because javascript numbers are 64 bit, with 53 bits reserved for the integer part." 
it is round off the id.

**Comment by arlemi** [comment]
@Maheshoptiva Which version of Postman are you using? Can you share an example of id that gets rounded out?

**Comment by Maheshoptiva** [comment]
Hi @arlemi , I am using win64-8.0.7,
**Response**: 
{
    "networkQuery": {
        "oTid": 2021112411030200034,
        "channel": "ABC",

**Script**:
bodyData = JSON.parse(responseBody);
value = bodyData.networkQuery.oTid;
console.log("Value of oTid: ", value);
pm.environment.set("oTid", value);

Variable value store: 
2021112411030200000

Thanks,
MB. 

Hi @arlemi ,
Thanks for support, it is resolve now with another way.
