### ISSUE TITLE
Postman sorts data in JSON Pretty mode without being told to

### ISSUE THREAD

**Issue by jonathancbarros** [a85/POSTMan-Chrome-Extension#5659]
## App Details:

```
Postman for Linux
Version 6.5.3
linux 4.15.0-42-generic / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there: Recently.
 2. Expected behaviour: The data is showed in the order I defined in my backend processing.
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 4. Screenshots (if applicable)
![screenshot from 2018-12-18 09-18-05](https://user-images.githubusercontent.com/15067898/50150905-8b83ad00-02a6-11e9-9324-f2a55ecb93f1.png)
![screenshot from 2018-12-18 09-18-16](https://user-images.githubusercontent.com/15067898/50150906-8b83ad00-02a6-11e9-9f85-a210741ed7d1.png)
![screenshot from 2018-12-18 09-18-36](https://user-images.githubusercontent.com/15067898/50150908-8b83ad00-02a6-11e9-93a6-3c6769dfa173.png)
![screenshot from 2018-12-18 09-18-25](https://user-images.githubusercontent.com/15067898/50150907-8b83ad00-02a6-11e9-9650-49929eba4aba.png)

I'm not sure, but you may try creating an array/json with keys of numeric value (e.g 1 or "1") and one of the keys of non-numeric value (e.g "NHG"). That's the case I am dealing with. Just to be clear, I'm working with PHP 7.1.

As you can see in the screenshots, Postman is weirdly sorting already sorted data. If you look at the Preview mode, you can see the correct order, then in the Pretty mode the data is sorted making the developer's life a bit harder.

**Comment by saswatds** [comment]
Hi @jonathancbarros this issue is now fixed in our latest app version v7.3.4

Closing this issue now. Feel free to re-open if the issue still persists.
