### ISSUE TITLE
Mock server is returning example responses for the wrong request in the collection when `x-mock-response-name` is used

### ISSUE THREAD

**Issue by martijnvdwoude** [a85/POSTMan-Chrome-Extension#5660]
**Describe the bug**
Mock server is returning example responses for the wrong request in the collection when `x-mock-response-name` is used.

**To Reproduce**
I have two requests in my collection.
`GET /callOne`
`GET /callTwo`

For both requests I have added two example responses to test. These examples have names "200" and "201", with matching status codes and the following response bodies:

`/callOne`:
```
{
     "call": "callOne",
     "statusCode": "200"
}
```

```
{
     "call": "callOne",
     "statusCode": "201"
}
```

`/callTwo`:
```
{
     "call": "callTwo",
     "statusCode": "200"
}
```

```
{
     "call": "callTwo",
     "statusCode": "201"
}
```

When I make requests to `https://mymockserver.mock.pstmn.io/callTwo` without the `x-mock-response-name` header the mock server returns the correct example response, for statuscode 200, so:

```
{
     "call": "callTwo",
     "statusCode": "200"
}
```

But when I add the `x-mock-response-name` header with value `200` the same call to `https://mymockserver.mock.pstmn.io/callTwo` now returns the example response for `/callOne`:

```
{
     "call": "callOne",
     "statusCode": "200"
}
```

Same goes for `https://mymockserver.mock.pstmn.io/callTwo` with header `x-mock-response-name` value `201`:
```
{
     "call": "callOne",
     "statusCode": "201"
}
```

**Expected behavior**
I expect the mock server to return example responses for the correct request.

The only workaround I have found is to give the examples unique names (unique in the whole collection, not just unique in the specific request). So instead of both `/callOne` and `/callTwo` having examples with names `200` and `201`, they should have names with for example `Call One 200`, `Call One 201`, `Call Two 200` and `Call Two 201`.

**Screenshots**

**Additional context**
The mock server feature was something that my team was excited to start working with as it seems like a great fit for our needs. However, using it these past few days I have found this feature to be buggy and highly unpredictable unfortunately.

**App information (please complete the following information):**
 - Mac App
 - Postman Version 6.6.1
 - macOS High Sierra 10.13.6

**Comment by ratpik** [comment]
@martijnvdwoude - If you are using `x-mock-response-name` header to match and you happen to have multiple example responses with the same name stored within your collection then mock server cannot deterministically determine which one of them you want it to return. You can use the `x-mock-response-id` header instead which is unique for every request. To get the id of an example response, you need to use the [Postman API](https://docs.api.getpostman.com/#647806d5-492a-eded-1df6-6529b5dc685c) to fetch your collection.
