### ISSUE TITLE
Postman Pre-req Function for future timestamp assign

### ISSUE THREAD

**Issue by karthik-cc** [a85/POSTMan-Chrome-Extension#5664]
I am trying to  assign future timestamp on some date fields in my pre-request. to solve the start (current time of the date ) and end time ( future time of the date).

Pre-request script :
postman.setGlobalVariable("timestampUtcstart", new Date().format('{yyyy}-{MM}-{dd} {HH}:{mm}'));

// Is it possible to add delay within the pre-request function call  ?

postman.setGlobalVariable("timestampUtcend", new Date().format('{yyyy}-{MM}-{dd} {HH}:{mm}'));

Body :
{
"provider": "<<>>",
"Id": "<<>>",
"startTime": "{{current time of the date}}",
"endTime": "{{future time of the date}}"
}

**Comment by numaanashraf** [comment]
@karthik-cc We do not recommend adding delay in the JS code to achieve this. Postman Sandbox has built-in modules that'll help you do this. For time related computations, we recommend `moment`. Here's the link to an article from the Postman community detailing how to use moment in your scripts - https://dannydainton.com/2018/05/21/hold-on-wait-a-moment/

**Comment by karthik-cc** [comment]
@numaanashraf Thank you. I will apply moment as in article and let you know the results
