### ISSUE TITLE
"Run in Postman" button does not pull any collection data or configuration to the native app [LINUX]

### ISSUE THREAD

**Issue by M1TR** [a85/POSTMan-Chrome-Extension#5665]
I have a Postman collection that is hosted in documenter.getpostman.com and I want to import it to my native app. Clicking on "Run in Postman" button just opens up the native Postman app but does not import the collection.

There is no option to "Download" the collection from the website, so it is not possible to import a file. Neither is there any import URL that can be used from inside the native app.

Is this a known issue? Or is the result of some configuration faults?

## App Details:

```
Postman for Linux
Version 6.6.1
linux 4.14.20-041420-generic / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there: Can't say
 2. Expected behaviour: Collection gets imported into Postman
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app): Empty (basically clicking on "Run in Postman" switches me from the browser to the native app)
 4. Screenshots (if applicable)

**Comment by SamvelRaja** [comment]
@M1TR 
Could you check the desktop entry is equivalent to the instruction specified here
https://learning.getpostman.com/docs/postman/launching_postman/installation_and_updates/#linux-installation

**Comment by M1TR** [comment]
@SamvelRaja 
The .desktop file is configured correctly. Like I said, clicking on "Run in Postman" does launch Postman. But it just doesn't do anything after the app loads. I've waited for a few minutes after the app loads in case it is doing something in the background, but nothing really happens.

**Comment by SamvelRaja** [comment]
@M1TR 

Clicking the button opens the app means Desktop entry working correctly.
Now we should verify whether the collection is getting imported.

To verify that.
1. Through Logs
   i. View -> Developer -> View Logs in File Explorer
   ii. Forward us Main.log file here
   iii. It shoudl have handleOpenUrl with the url to open

2. Verify in live
 i. Keep the app opened.
 ii. Click View -> Developer -> Show DevTools (CurrentView)
 iii. Click View -> Developer -> Show DevTools (Shared) 
 Above will open the devtools for you, keep the network tab opened in both the devtools and then click run-in-postman button again.
 It should make the network call.

Also, Kindly double check your desktop entry to have 

Exec=`<PATHTOEXEC> %U`   - %U is the environment variable through which OS handovers the url to the application.

**Comment by M1TR** [comment]
@SamvelRaja 
Hey. Reconfigured the .desktop file with the %U solved the issue. Run in Postman works perfectly now.
Thanks so much for your help!
