### ISSUE TITLE
Not able to read postman cookie

### ISSUE THREAD

**Issue by venkatesuluM** [a85/POSTMan-Chrome-Extension#5667]
Issue:
Not able to read postman cookies using below function:
postman.getResponseCookie(cookieName) not working in 6.6.1 version Windows desktop application.

Please look into this issue.

**Comment by abhijitkane** [comment]
@venkatesuluM Can you elaborate? I tried a console.log(postman.getResponseCookie('cookie-name')), and it printed the cookie object in the console. Are you getting a syntax error in the script, or is nothing being printed in the console? A dump of the logs (View > Developer > Show logs) will help

**Comment by venkatesuluM** [comment]
@abhijitkane 

It was displaying as Null value and also attached screenshots.
console.log(postman.getResponseCookie("avs_cookie"));

Note: No errors on show dev tools console. 

Screenshots:
![postman cookie](https://user-images.githubusercontent.com/45995990/50442722-25da9500-0926-11e9-87be-b1a3ebc9f308.png)
![show postman console](https://user-images.githubusercontent.com/45995990/50442723-25da9500-0926-11e9-8ef7-788a80f7e448.png)

**Comment by venkatesuluM** [comment]
@numaanashraf ,

Is it resolved?

@numaanashraf ,

Any updates?

**Comment by venkatesuluM** [comment]
@numaanashraf ,

Working fine now.

Thanks,
Venkatesh
