### ISSUE TITLE
The WS browse view empty state doesn't disappear after creating a collection

### ISSUE THREAD

**Issue by abhijitkane** [a85/POSTMan-Chrome-Extension#5669]
1. Start with a new Postman installation (signed-in to a free account).
2. Switch to the browse view for 'My Workspace'
3. Click the 'or create a collection' link in the empty state.
4. Create a collection
5. The empty state still says 'you don't have any collections'.
6. Moving to the build view and back shows the collection

Also, once the collection name shows up in the Browse view, deleting it doesn't update the UI till I move to the build view and back.

Seen on Postman v6.6, Mac native app

**Comment by a85** [comment]
Not sure if this is still valid.
