### ISSUE TITLE
Workspace activity feed (browse view) is always empty

### ISSUE THREAD

**Issue by abhijitkane** [a85/POSTMan-Chrome-Extension#5670]
1. Start with a new Postman installation (signed-in to a free account).
2. Create a few collections in 'My workspace', add folders, delete folders, add requests etc.
3. Switch to the 'Browse view' > Activity feed
4. Notice the lack of activity history.

The text says 'collaborate with your teammates to see activity', but this is a personal workspace.

Seen on Postman v6.6, Mac native app

**Comment by preethammavin** [comment]
This has been fixed.
