### ISSUE TITLE
Browse view History items are unclickable

### ISSUE THREAD

**Issue by abhijitkane** [a85/POSTMan-Chrome-Extension#5671]
1. Start with a new Postman installation (signed-in to a free account).
2. Send a few requests in 'My workspace'
3. The requests should show up in the Build view (History tab)
4. Switch to the browse view's history tab.
5. Hovering over the history items shows a pointer cursor, but clicking on them does nothing.

Seen on Postman 6.6, Mac native app

**Comment by saswatds** [comment]
Closing this as its no longer an issue in the latest postman app.
