### ISSUE TITLE
Wrong/no empty state in the collection runner's workspace switcher

### ISSUE THREAD

**Issue by abhijitkane** [a85/POSTMan-Chrome-Extension#5672]
The team tab empty state for the collection runner's workspace switcher doesn't work like the one in the main Postman window:

1. If I'm signed in to a non-team account, the 'Team' tab in the collection runner's workspace switcher doesn't have an empty state.

2.  If I'm not signed in, the team tab tells me that I don't have an active internet connection. (I know I do)

**Comment by sankalp0o** [comment]
This was fixed in the v7.7 version of the Postman app.
