### ISSUE TITLE
Error AND success message while trying to publish a template

### ISSUE THREAD

**Issue by abhijitkane** [a85/POSTMan-Chrome-Extension#5674]
1. Start with a new Postman installation (signed-in to a free account).
2. Create a collection - My first template
3. Collection context menu -> Publish docs
4. Check the 'Collection discovery' checkbox
5. Select the 'Postman templates' option
6. Notice how the categories input has all categories selected. (It doesn't - you need to click on each of them to actually 'select' them)

Problem 1: The publish button is disabled, but there's no clear indication why. There's nothing that tells me that the summary and description are required

7. Publish

Problem 2: I see a failure message (at least one category is required) AND a success message (my collection was published). Which one is it? The client shouldn't let me proceed until I've selected one category.

<img width="676" alt="screen shot 2018-12-20 at 11 28 51" src="https://user-images.githubusercontent.com/681190/50266704-a68f2200-044a-11e9-9a03-58000253f921.png">

**Comment by dhineshwiz** [comment]
@abhijitkane This issue is fixed, and categories are made optional for both API network and templates, please free to re-open, if u find any other issue in this
