### ISSUE TITLE
No description/explanation in Settings > Certificates

### ISSUE THREAD

**Issue by abhijitkane** [a85/POSTMan-Chrome-Extension#5676]
There's no explanation of what `Client certificates` are. An empty state, description, or link to documentation would help here.

![screen shot 2018-12-20 at 11 36 43](https://user-images.githubusercontent.com/681190/50266955-a5122980-044b-11e9-88fa-c0685496f1cb.png)

**Comment by numaanashraf** [comment]
Fixed in Postman v7.0
