### ISSUE TITLE
Add a 'copy link' button when the published URL is shown

### ISSUE THREAD

**Issue by abhijitkane** [a85/POSTMan-Chrome-Extension#5677]
A button to copy the generated URL would be super-helpful here.

<img width="825" alt="screen shot 2018-12-20 at 11 39 10" src="https://user-images.githubusercontent.com/681190/50267057-f02c3c80-044b-11e9-9735-34124cb97342.png">

**Comment by abhinaba-ghosh** [comment]
Hey @abhijitkane , 

We have added the copy button for the published documentation in the latest Postman app. 
![Screenshot 2022-04-27 at 4 51 43 PM](https://user-images.githubusercontent.com/23141842/165507682-e8cb2d9a-e054-496d-9000-a9ebf83ebe46.png)
