### ISSUE TITLE
Postman fails to launch on Fedora 29

### ISSUE THREAD

**Issue by qortex** [a85/POSTMan-Chrome-Extension#5680]
**Describe the bug**
Starting fails with (from terminal output) :

> 
> A JavaScript error occurred in the main process
> Uncaught Exception:
> Error: Cannot find module './services/electronProxy'
>     at Module._resolveFilename (module.js:485:15)
>     at Function.Module._resolveFilename (/home/mic/dev/Postman/app/resources/electron.asar/common/reset-search-paths.js:35:12)
>     at Function.Module._load (module.js:437:25)
>     at Module.require (module.js:513:17)
>     at require (internal/module.js:11:18)
>     at Object.<anonymous> (/home/mic/dev/Postman/app/resources/app/main.js:11:21)
>     at Object.<anonymous> (/home/mic/dev/Postman/app/resources/app/main.js:549:3)
>     at Module._compile (module.js:569:30)
>     at Object.Module._extensions..js (module.js:580:10)
>     at Module.load (module.js:503:32)

**To Reproduce**
Fresh Fedora 29 install.
Download latest Postman archive from the website.
Unpack, launch, fails.

**Expected behavior**
Should launch without error.

**Comment by ppuskar** [comment]
problem still persist

**Comment by qortex** [comment]
now working for me, but don't really know what I changed in the configuration of my fedora in the meantime :(

**Comment by numaanashraf** [comment]
Thank you for your issue! With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have more information that'll help us reproduce and fix this issue - we'll be happy to reopen the issue.

**Comment by mmelnik** [comment]
Confirm this problem. Bug still appears on fresh Fedora 29 installation and latest Postman version. @numaanashraf what info can help you to fix this?

**Comment by mmelnik** [comment]
Here is solution that worked for me:
https://github.com/postmanlabs/postman-app-support/issues/5093#issuecomment-450737208

**Comment by Arkemlar** [comment]
+1 from NEON KDE (based on ubuntu)
![image](https://user-images.githubusercontent.com/19671202/57704241-2fad2c80-766a-11e9-8569-967836fa8950.png)

**Comment by batjko** [comment]
> Here is solution that worked for me:
> [#5093 (comment)](https://github.com/postmanlabs/postman-app-support/issues/5093#issuecomment-450737208)

Worked for me as well. Just using the GUI extractor (in Ubuntu 18.04) seems to have messed some stuff up.

**Comment by chiro-hiro** [comment]
Use GUI to extract not working, extract `tar.gz` file in cli, worked!.
