### ISSUE TITLE
Remove referer header on redirects

### ISSUE THREAD

**Issue by sujayvenaik** [a85/POSTMan-Chrome-Extension#5683]
**Is your feature request related to a problem? Please describe.**
When there are multiple redirects, on subsequent requests I don't want the referer header to be forwarded

**Describe the solution you'd like**
The referer header to be ignored/dropped

**Describe alternatives you've considered**
Works on postman chrome app

**Additional context**

![capture-01](https://user-images.githubusercontent.com/11532114/50347135-9c5c4900-055a-11e9-9822-daf4dcdfbd33.gif)

**Comment by codenirvana** [comment]
We've added support for Request Level Configurations in the latest version of the Postman App (v7.7.2).

You can turn `Remove referer header on redirect` configuration ON to remove the referer header when a redirect happens.
