### ISSUE TITLE
How to send a base64 image to Postman?

### ISSUE THREAD

**Issue by AndriiHavrylyak** [a85/POSTMan-Chrome-Extension#5685]
You need to request an API with an image encoded in base64. I would like to assign the "Фото1
![1](https://user-images.githubusercontent.com/38010614/50276766-6c725000-044b-11e9-9c6b-5abdc97622b0.jpg)
" time to base64 via the Get-request, but there is an error!

**Comment by numaanashraf** [comment]
@AndriiHavrylyak Please provide detailed steps to replicate this issue.

**Comment by numaanashraf** [comment]
Based on the nature of your query, we recommend reaching out to the wider Postman Community (https://community.getpostman.com/) for help with this issue.

Issue Guidelines: https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues
