### ISSUE TITLE
Not showing the icons properly & not showing the pop up menu properly at pop up menu of collection at postman.

### ISSUE THREAD

**Issue by imranbangladeshi** [a85/POSTMan-Chrome-Extension#5686]
**Describe the bug**
Not showing the icons properly at clicking pop up menu icon of collection at postman.
& not showing the pop up menu properly at clicking pop up menu icon of collection at postman.

**To Reproduce**
Steps to reproduce the behaviour:
1. Open the Postman App.
2. Make it window size.
3. Create multiple collections at collections tab.
4. Create multiple folders under the collection.
5. Do some api testing work.
6. Click on pop up menu of that collection.
7. See at the left corner of that pop up menu.
8. Not showing the icons properly & Not showing the pop up menu properly.

**Expected behaviour**
Pop up menu should show properly and the icons should show properly.

**Screenshots**
check this screenshots.

![postman bug1](https://user-images.githubusercontent.com/46083393/50382593-90dd5f00-06cd-11e9-85d3-02e49fbab94e.png)
![postman bug2](https://user-images.githubusercontent.com/46083393/50382594-90dd5f00-06cd-11e9-916d-e8c4d4fc4772.png)
![screen shot 2018-12-23 at 4 37 05 pm](https://user-images.githubusercontent.com/46083393/50383028-41e7f780-06d6-11e9-864f-a1e66086990c.png)
![screen shot 2018-12-23 at 4 37 22 pm](https://user-images.githubusercontent.com/46083393/50383029-42808e00-06d6-11e9-9d3b-111d474a7c5c.png)

**App information (please complete the following information):**
 - Postman Version 6.6.1 (6.6.1)
 - OS: [e.g. macOS High Sierra 10.13.6 (17G3025)]

**Comment by vkaegis** [comment]
@numaanashraf This issue is fixed, yes? Can we close this ticket?

**Comment by imranbangladeshi** [comment]
ok, I will check & If fixed then will close this issue.
