### ISSUE TITLE
[FR] Open in Postman button, when in browser

### ISSUE THREAD

**Issue by sumit0k** [a85/POSTMan-Chrome-Extension#5687]
**Is your feature request related to a problem? Please describe.**
I cannot find easier way to share a link of collection, which my colleague can use and directly navigate to collection in specific workspace. 
`Run in Postman` is very risky, as `Replace` word is dreadful, if you just want to look at test scripts, unsure on what it could do.

**Describe the solution you'd like**
A link which opens directly in Postman app, either in build mode or in browse mode by automatically switching to corresponding workspace

**Describe alternatives you've considered**
Only way I could find is 
1. Do a `View in web`, 
2. Grab the link from address bar
3. Send to colleague
5. Colleague gets the collection name and workspace name from link
6. Opens postman app and navigate manually to that area

**Additional context**
If this feature is already there then 
1. Either I am naive to be not able to find it
2. It is kept in highly secured vault.

OR if possible a feature could be added in documenter to show tests and pre-request script as well.

**Comment by DannyDainton** [comment]
In the later versions of the platform, each of the entities has links that can be shared with members of the team. This will open this specific entity in the Workspace.

<img width="1080" alt="image" src="https://user-images.githubusercontent.com/17089546/177334310-3f058581-903c-4be3-98d7-5e7cdd55da18.png">

Closing this feature request for now but if this is not what you were hoping to see, we can reopen and amend the description based on the current functionality of the platform.
