### ISSUE TITLE
Postman lost all collections?

### ISSUE THREAD

**Issue by polds** [a85/POSTMan-Chrome-Extension#569]
Opened up Postman today and all of my collections were gone, I've checked both the compiled version and in browser version. Any advice?

**Comment by Miniguide** [comment]
This just happened to me. I opened up Chrome and Postman is corrupted / gone. I can fix the Postman extension in settings but my collections are gone.

So I closed Chrome and restored this folder using Time Machine:
~/Library/Application Support/Chrome

After I opened Chrome (which said it hadn't been shut down correctly) and restored tabs, Postman is back with my collections. Yay.

Using:
Mac OS X 10.10.2
Chrome 40.0.2214.115 (64-bit)
Postman 0.8.4.13

**Comment by waaronking** [comment]
@Miniguide Thanks for that. Your solution worked for me as well.

**Comment by bitdozer** [comment]
Similar thing happened to me a few days ago when I disabled all Chrome extension temporarily.  After that, no more collections or history in POSTMAN packaged app.  

In Windows the solution was to restore the entire 

C:\Users\%username%\AppData\Local\Google\Chrome 

folder from a backup.  

And then of course do an export and turn on POSTMAN sync!

**Comment by umasenthil** [comment]
I lost the collections in my POSTMAN too.
Could you please let me know how get the backup in mac?
Thank you!

**Comment by umasenthil** [comment]
Ignore my previous comment. But if anyone this issue in MAC, a simple solution which might randomly work... Close the postman and open it. I did it couple of times and I see the collections the second time.

**Comment by mplungjan** [comment]
Lost all collections and history Chrome 50 Win7.
Created a new collection, closed Postman, opened it; collection and history gone

**Comment by abhijitkane** [comment]
@mplungjan Did you have sync enabled? If yes, can you check https://app.getpostman.com/dashboard and https://app.getpostman.com/dashboard/collections/private?expand=1? These links should show you your sync activity and the current state of your data.

**Comment by mplungjan** [comment]
1: How to enable sync
2: Are we even talking about the same extension? My issue was with "Postman REST client" v 0.8
3: I installed YOUR Postman v4 from Chrome store - there are also no sync there. When I click on it in the app screen, it does not run - it crashes the tab instead

PS: I see "Error: QUOTA_EXCEEDED_ERR" in requester.js

**Comment by abhijitkane** [comment]
@mplungjan 
Postman Rest Client 0.8 was deprecated a long time ago. This does not have Sync. Collections added in 0.8 will not be available anywhere else.

You can try to locate the database file - You can try to recover the IndexedDB database which Postman uses. The IndexedDB files can be found in a location like this: ~/Library/Application\ Support/Google/Chrome/Profile\ 1/IndexedDB/chrome-extension_fdmmgilgnpjigdojojpjoooidkmcomcm_0.indexeddb.leveldb (I'm on OS X) The app ID of the extension is fdmmgilgnpjigdojojpjoooidkmcomcm. " (The location for your machine can be found at chrome://indexeddb-internals/).

For the issue with Postman v4, can you send a screenshot of what you see when you open the app?

**Comment by mplungjan** [comment]
I see nothing. The tab closes

**Comment by lagane** [comment]
Folks,
I have similar issue after a chrome upgrade today. It is very critical for me to restore all my collections.

OS: Windows
Postman - Postman rest client
Snapshot of POSTMAN after chrome upgrade -
![image](https://cloud.githubusercontent.com/assets/19694273/15721040/2b93e514-2805-11e6-9c98-24c6163c1a3a.png)

Also looking at my indexeddb.leveldb . What can i do with this ?

Any help is truly appreciate

**Comment by lagane** [comment]
My version of Chrome is Version 51.0.2704.63 m (64-bit)

**Comment by lagane** [comment]
Postman rest client version -  0.8.4.8

**Comment by sankotm** [comment]
Oh crap, same thing happened to me today :(( lost all collections.
Chrome 51.0.2704.103 m, Win 8, Postman Rest client 0.8.4.8

**Comment by razventures** [comment]
i also lost all my collections on version .8.xx.     to recover i had to go to the location of the database mentioned in this thread (for me, on my mac, it was /library/application support/google/chrome/default/indexeddb/chrome-extension_fdmmgilgnpjigdojojpjoooidkmcomcm_0.indexeddb.leveldb)    and then go into time machine and go back to when i had a .ldb file in there.  then restore all files in that folder. i replaced everything with what was in that past backup point.  

after restore, and reopening postman the collections were back.   i then exported the data into a newer version of postman to sync to the cloud.

**Comment by abhijitkane** [comment]
@sankotm @lagane 

Which Postman Extension do you have - https://chrome.google.com/webstore/detail/postman-rest-client-short/mkhojklkhkdaghjjfdnphfphiaiohkef/reviews?hl=en or https://chrome.google.com/webstore/detail/postman-rest-client/fdmmgilgnpjigdojojpjoooidkmcomcm?hl=en?
The first one is an unauthorized clone of Postman, and we cannot provide support for that. If you're on the second one, head to chrome://extensions, enable 'Developer Mode', and click 'Update Extensions now'. This will update you to 0.8.4.17, and you will be able to access your data.

A recent Chrome update broke v0.8.4.8. We'd pushed a patch for this some time back, but this clone app did not.
The new Postman app is available at https://chrome.google.com/webstore/detail/postman-rest-client-packa/fhbjgbiflinjbdggehcddcbncdddomop?hl=en.
