### ISSUE TITLE
Environment dropdown on applying a filter has empty spaces/rows

### ISSUE THREAD

**Issue by sujayvenaik** [a85/POSTMan-Chrome-Extension#5690]
**Describe the bug**
On filtering through the environment drop-down menu, has certain empty spaces

**To Reproduce**
1. Go to Environment drop down
2. Create a number of environments
3. apply a filter

**Expected behaviour**
No empty added space/rows

**Screenshots**
![kapture 2018-12-26 at 14 57 26](https://user-images.githubusercontent.com/11532114/50441066-fe33fe80-091e-11e9-86cb-a5afe4298ca4.gif)

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version: v6.6.1
 - OS: macOS

**Comment by numaanashraf** [comment]
This is fixed in Postman v7.0.8
