### ISSUE TITLE
Resolve nested variables when using pm.variables.get

### ISSUE THREAD

**Issue by m3dbedb** [a85/POSTMan-Chrome-Extension#5691]
**Describe the bug**
When I use environment variable in pre-request script, it does not being resolved if nested.

**To Reproduce**
Step 1. Set environment variables:

**pre-request script**

    pm.environment.set('base_ip','192.168.1.1');
    pm.environment.set('port',8089);
    pm.environment.set('ip','{{base_ip}}');
    pm.environment.set('protocol','http');
    pm.environment.set('url','{{protocol}}://{{ip}}:{{port}}/api/v1'

**Request:**
GET {{url}}/systemparam

**tests:**

    var jsonData = JSON.parse(responseBody);
    pm.globals.set('service_parameter',jsonData.data.parameter);

2. In pre-request script of step 2 I need to print {{url}} value:
    if(tests["Connection test with service "+pm.environment.get('url')] = pm.globals.has('service_parameter')===false) {
    postman.setNextRequest(null);}

3. See error

> Connection test with service {{protocol}}://{{ip}}:{{port}}/api/v1

**log**: ReferenceError | url is not defined

**Expected behavior**
Variable is printed in test tring

**App information (please complete the following information):**
 - App Type Native App
 - Postman Version [6.6.1]
 - OS: WIndows 7 32
 - bug type: recently appeared

**Comment by m3dbedb** [comment]
Same happens in test section.

**Comment by numaanashraf** [comment]
@m3dbedb Thanks for writing in. `pm.environment.get` & `pm.globals.get` are not designed to auto-resolve values when used. They are simple getter/setter APIs exposed to set or get values to and from environment / globals.

**Comment by numaanashraf** [comment]
@m3dbedb I've converted this to a feature request instead

**Comment by a1dutch** [comment]
I would like to see this feature too.

There are a couple of easy work arounds but would like support for variable expansion out of the box

**Comment by codenirvana** [comment]
Refer https://github.com/postmanlabs/postman-app-support/issues/2922#issuecomment-527101679 for `pm.variables.replaceIn`.
