### ISSUE TITLE
Tab goes in conflicted state on update of name and description when same requests are open on multiple tabs

### ISSUE THREAD

**Issue by sujayvenaik** [a85/POSTMan-Chrome-Extension#5692]
**Describe the bug**
When same requests are open in multiple tabs and we edit the name and description the tab goes in conflicted mode 

**To Reproduce**
Open request r1 in two different tabs, make tabs dirty and edit name and description

**Expected behavior**
Tab doesn't become conflicted

**Comment by sujayvenaik** [comment]
Fixed in v6.7.0-canary04
Canary can be downloaded from https://www.getpostman.com/canary

Will update this thread once this gets out on the stable release.

**Comment by sujayvenaik** [comment]
This is fixed in the latest version v6.7.1

**Comment by rohanahata** [comment]
This issue keeps coming back.

**Comment by thilanka** [comment]
Still the issue is there. v 9.1.3

**Comment by THammond9** [comment]
I have this issue as well.

**Comment by mortezaataiy** [comment]
I have this issue in v10.13.0

Fix this please

@sujayvenaik
