### ISSUE TITLE
Unhandled defer error in golang code snippet

### ISSUE THREAD

**Issue by r21gh** [a85/POSTMan-Chrome-Extension#5693]
**Feature description**
in "generate code snippets" part, for generating Golang code, Postman always create a simple 
`defer res.Body.Close()`
but it does not handle any errors, and it is good to atleast handle defer error.

**Describe the solution you'd like**
we can replace the the defer part with this snippet:
```

defer func() {
		err := res.Body.Close()
		if err != nil {
			fmt.Println(err)
			return
		}
	}()
```

**Comment by r21gh** [comment]
@numaanashraf I have sent a pull request for this feature.

**Comment by umeshp7** [comment]
@rezaghanbari  We have done a bunch of improvements and updates to the code generation feature. And we have also fixed various issues for golang including this one. Please update your Postman app and generate snippets. 

Closing this for now, please let us know if you still face any issues with the generated snippets.
Open source repository for feedback and updates: https://github.com/postmanlabs/postman-code-generators
