### ISSUE TITLE
Wrapping pm.expect with pm.sendRequest doesn't work

### ISSUE THREAD

**Issue by m3dbedb** [a85/POSTMan-Chrome-Extension#5695]
**Describe the bug**
I have an assertion inside send request and test gives an error. When I have changed wrap order, assertion fails as it should

**Steps to reproduce the behavior:**

1. Call some method with listed assertion inside tests tab:

    pm.test("Array is empty", function () {
       pm.sendRequest(str, function (err, res) {
         if (res) {
            pm.expect(res.json().data.length).to.equal(0);
         }
       });
    });

AssertionError | expected 1 to equal 0

**Expected behavior**
If an assertion fails it should only became red without postman error. In fact it fails, but stay green and  gives postman app error. If the assertion passes, it shows green without error.

**App information:**
 - App Type: Native App
 - Postman Version: 6.6.1
 - OS: win 7 32

**Additional context**

When I wrap assertion by sendRequest method, the assertion works good:

    pm.sendRequest(str, function (err, res) {
      if (res) {
        pm.test("Statuscodeis200", function () {
        pm.expect(res.json().data.length).to.not.equal(0);});
        b=res.json().data.length;
        console.log('l '+res.json().data.length);
     }
    });

**Comment by numaanashraf** [comment]
@m3dbedb We discussed this internally, and there are no plans to implement this at the moment. `pm.test` & `pm.expect` are designed to work at an immediate nesting level, and adding support for async calls like `pm.sendRequest` between them would unjustifiably increase complexity for the sandbox API. For now, the recommended way to use `pm.expect` inside the `pm.sendRequest` is to add additional `pm.test` inside `pm.sendRequest`

```js
pm.sendRequest(..., () => {
  pm.test(..., () => {
    pm.expect(...);
  });
});
```

**Comment by dmenne** [comment]
The example below should fail, but it always passes.

```
pm.sendRequest({
    url: 'http://localhost:8000/valuesbyparameters/Endoskopie',
    method: 'delete'   
}, function (err, response) {
    if (err) {
      console.log(err);
    } else {
        console.log('delete response' + response.text()); // Gives expected return
        pm.test('response of delete should be 7'), () =>{
           pm.expect(res).to.equal('asdf'); // Should always faile
        };
    }}); 
```

**Comment by Vizionz** [comment]
Any update on @dmenne's issue? I'm also interested to a solution.
