### ISSUE TITLE
response should be okay to process fails in scheduled monitor

### ISSUE THREAD

**Issue by julweng** [a85/POSTMan-Chrome-Extension#5696]
**Describe the bug**
The following test used to work in our scheduled monitor runs:

```
if (responseCode.code === 200) {
    pm.test("response should be okay to process",  () => { 
        pm.response.to.not.be.error; 
        pm.response.to.have.jsonBody(""); 
        pm.response.to.not.have.jsonBody("error"); 
    });
...
```

Today, we ran this monitor twice in postman cloud. Status code for every request is 200, but every request response fails this test.

We then ran a collection runner locally, and every test passed.

**To Reproduce**
- run a request with this test locally
- run a request with this test in postman cloud

**Expected behavior**
The test should show up as "passed" in both the local collection runner and the postman cloud

**App information (please complete the following information):**
 - Version 6.6.1 (6.6.1)
 - OS

**Comment by numaanashraf** [comment]
@julweng Could you give us a sample response we can use to test this?

**Comment by julweng** [comment]
@numaanashraf 

example response:
```
[ 
    { 
         id: 1,
         topic: { 
             id: 2,
             name: 'new years',
             inserted_datetime: 'Mon Dec 31 2018 07:17:11 GMT-0800 (Pacific Standard Time)',
             updated_datetime: 'Mon Dec 31 2018 07:17:11 GMT-0800 (Pacific Standard Time)'
         },
         user: { 
             id: 1,
             name: 'peter',
             avatar_url: 'abc.jpeg',
             inserted_datetime: 'Mon Dec 31 2018 07:17:11 GMT-0800 (Pacific Standard Time)',
             updated_datetime: 'Mon Dec 31 2018 07:17:11 GMT-0800 (Pacific Standard Time)' 
          },
          text: 'test',
          inserted_datetime: 'Mon Dec 31 2018 07:17:11 GMT-0800 (Pacific Standard Time)',
          updated_datetime: 'Mon Dec 31 2018 07:17:11 GMT-0800 (Pacific Standard Time)' 
     }
]
```
Last Friday when I clicked the console log tab, it crashed. Today I was able to view the console log
<img width="431" alt="screen shot 2018-12-31 at 7 22 08 am" src="https://user-images.githubusercontent.com/32506699/50562882-f41e5100-0ccc-11e9-934e-6007741d4bc2.png">

The above console error `expect X in response to contain property ''` appeared for every `"response should be okay to process"` test (attached code block in opening post) in every request last Friday. However, this used to be a passed test before, and locally, this error does not occur. The rest of our tests ran fine.
<img width="1055" alt="screen shot 2018-12-31 at 7 05 54 am" src="https://user-images.githubusercontent.com/32506699/50562937-7f97e200-0ccd-11e9-8ab2-7aa230381779.png">

**Comment by abhijitkane** [comment]
@julweng This is a bug with the current version of the app. The following assertions should work (moving the assertions with .not to the end, and removing the empty string arg from .to.have.jsonBody):

```
pm.response.to.have.jsonBody(); 
pm.response.to.not.be.error; 
pm.response.to.not.have.jsonBody("error"); 
```

The root bug being tracked here - https://github.com/postmanlabs/postman-app-support/issues/3592

Closing this for now
