### ISSUE TITLE
Postman doesn't start - Shared window is not available

### ISSUE THREAD

**Issue by pies** [a85/POSTMan-Chrome-Extension#5697]
**Describe the bug**
Application doesn't start. Presents with errors: 

```
1546010280894 main info ["Booting Postman 6.5.3, linux-4.17.9-041709-generic on x64"]
1546010280897 main info ["EventBus~initialize - Success"]
1546010280902 main info ["UpdateHandler~init - Success"]
1546010280904 main info ["RuntimeExecutionService~initialized: Success"]
1546010280929 main info ["ProtocolHandler~init - Success with status: false]"]
1546010280973 main error ["WindowManager~getSharedWindow: Shared window is not available"]
```

```
1546010577251 main info ["Booting Postman 6.6.1, linux-4.17.9-041709-generic on x64"]
1546010577254 main info ["EventBus\\x7einitialize - Success"]
1546010577260 main info ["UpdateHandler\\x7einit - Success"]
1546010577263 main info ["RuntimeExecutionService\\x7einitialized: Success"]
1546010577386 main info ["ProtocolHandler\\x7einit - Success with status: false]"]
1546010577458 main error ["WindowManager\\x7egetSharedWindow: Shared window is not available"]
```

**To Reproduce**
1. Start app

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/37940/50519946-a4b60600-0abd-11e9-8ba2-a19a86188229.png)

**App information (please complete the following information):**
 - Native App
 - version 6.6.1 and 6.5.3
 - OS: Ubuntu 18.04

**Additional context**
It used to work (earlier today) in an earlier version of the 6.5 line, but that one seems to have been broken by auto-update to 6.5.3. Fresh 6.6.1 doesn't run.

**Comment by pies** [comment]
Nevermind, machine restart fixed it.

**Comment by DerekSansom** [comment]
This is happening to me, a couple of times now, and I realy don't want to reboot each time Postman decides to become unresponsive
