### ISSUE TITLE
Collection with context of own environment

### ISSUE THREAD

**Issue by moleksyuk** [a85/POSTMan-Chrome-Extension#5698]
**Is your feature request related to a problem? Please describe.**

My setup:
**Project_1**
- has postman collection - `Collection_1`
- has envs: `env1_local`, `env1_stage`

**Project_2**
- has postman collection - `Collection_2`
- has envs: `env2_local`, `env2_prod`

Actual:
I'm working in parallel on both projects (because it's integration between them).
Both of them is up and running, so I execute some calls from `Project_1` or from `Project_2`.
1. I open call from `Collection_1`, then select env `env1_local`. And perform call.
2. Then I select call from `Collection_2` _and here I forget very often to switch env_ to `env2_local`. And perform call. In this step 99% of first execution is failed due to wrong env variables.
It makes me dispirited.
 
**Describe the solution you'd like**
I propose to add a relation between collections and environment variables.
For each collection, you can assign a list of environments. And one of this list could be set as deafult one.
So, when you open the first call from a collection and it will open a new tab - default environment will be populated automatically. For all other calls - the last used env will be used.
If you come back to a previously opened call from collection - then the last used environment will be used.

Example:
`Collection_1` has envs: `env1_local`(as default), `env1_stage`.  
`Collection_2` has envs: `env2_local`(as default), `env2_prod`.

1. I open a call from `Collection_1` for the first time - it will open it and populate env dropdown with `env1_local`.
2. I change env for this call to `env1_stage`.
3. Then I decide to open a new call from `Collection_2`. It will open it and populate env dropdown with `env2_local`.
4. Then I switch back to call from `Collection_1` (which is already opened tab) and in this case env will be changed to `env1_stage`(the last used).
5. Then I open the second call from `Collection_1` - it will open it and populate env dropdown with `env1_stage` (as the last used).

So, each collection will have its own context of envs.

**Comment by a85** [comment]
@moleksyuk Have you tried using collection variables or workspaces?

**Comment by moleksyuk** [comment]
HI @a85 
Let me try to show my problem by this screen:
![Screen Shot 2019-03-11 at 17 27 11](https://user-images.githubusercontent.com/793472/54136289-27dfca80-4424-11e9-9342-44985ed419fd.png)

As an example: `{{server}}/api/login` this url is completely different in scope of one collection and definately in scope of both of them:
BILLING:
 - local: `{{server}} = http://localhost:8080`
 - stage: `{{server}} = https://billing.stage.mycompany.com`
 - prod: `{{server}} = https://billing.mycompany.com`

CAPI:
 - local: `{{server}} = http://localhost:7777`
 - stage: `{{server}} = https://capi.stage.mycompany.com`
 - prod: `{{server}} = https://capi.mycompany.com`

So, 
1. I open a request from `CAPI` collection.
2. Select `[CAPI]: Stage` environment.
3. Do a request.
4. Open a new request from `BILLING` collection.
5. And here in 99% automatically do a request again: which is not correct, becaue currently `{{server}} = https://capi.stage.mycompany.com` but I want to call `{{server}} = https://billing.stage.mycompany.com` for example, or even `{{server}} = http://localhost:8080`.

>> Have you tried using collection variables or workspaces?

I don't use collection variables, almost environments. But I know about them and don't see how they could solve my problem.

The same for workspaces, I have 3 different collections. Here I can partially resolve issue with 
worspaces - one collection per workspace, but it sounds strange and not user friendly. Switch between workspaces each time?

Hope you will get my explanation. Thanks.

**Comment by a85** [comment]
We recommend using Collection level variables for these workflows:

<img width="1552" alt="Screenshot 2019-05-05 11 44 59" src="https://user-images.githubusercontent.com/653409/57198739-3c73a700-6f2b-11e9-8a5c-64f8bcdbce06.png">
