### ISSUE TITLE
[Console] Raw log body for multipart/form-data post fails to log form boundary and content-disposition in payload

### ISSUE THREAD

**Issue by aev-mambro2** [a85/POSTMan-Chrome-Extension#5699]
**Describe the bug**
Raw log body for multipart/form-data post fails to log form boundary and content-disposition in payload. 
The raw log shows the form boundary in the Content-Type header, but the payload lacks both the content-disposition and the form boundary. Postman does generate and send them. They just don't show up in the raw console view. What does get shown in the console does NOT comply with the Multipart RFC. What gets sent by Postman DOES comply. 

**To Reproduce**
1. Set up a POST request with a form-data body. 
2. Create a single nameless form field (leave the key blank) and place the word "Payload" raw into the value.
3. Address it to any HTTP web address without encryption, to allow a packet sniffer like Fiddler and Wireshark to see the real communication. 
4. Open the Postman Console. 
5. Send the POST request.
6. Using the console, navigate to the tested POST request, and request the Raw view. 
6. The view will show the headers followed by the payload. But instead of the content-disposition and the form boundary prefix, the payload is prefixed by an equals (=) sign. For instance: 
  
Content-Type: multipart/form-data; boundary=--------------------------730684452617986894354104 
User-Agent: PostmanRuntime/7.4.0 

=Payload

**Expected behavior**
The raw console log should show exactly the data that got sent. Wireshark shows that Postman does generate the content-disposition and the form boundary, and does prefix them to the payload. For instance: 
  
Content-Type: multipart/form-data; boundary=--------------------------730684452617986894354104 
User-Agent: PostmanRuntime/7.4.0 

----------------------------730684452617986894354104 
Content-Disposition: form-data; name="" 

Payload

**App information (please complete the following information):**
 - Postman for Windows
 - Version 6.6.1
 - OS: win32 10.0.16299 / x64

**Additional context**
For the described POST request, the Code view that pretends to generate the HTTP request also gets the payload wrong: it places the form boundary AFTER the payload instead of BEFORE it.

**Comment by arlemi** [comment]
Fixed in 7.16.0.
