### ISSUE TITLE
Slack integration setup fails

### ISSUE THREAD

**Issue by JP-from-Postman** [a85/POSTMan-Chrome-Extension#5701]
[From Postman Support]

When adding the Slack integration to a workspace (for a monitor), a notice of the integration appears in the target Slack channel, but no prompt is show during setup to select a monitor, and the integration does not appear in the dashboard integrations for the workspace.

Steps to reproduce:

1. From Dashboard, go to integrations view for a workspace
2. Select Slack > Monitor Run Results
3. Enter Slack domain, authorize, select target channel
    _(Notice of integration appears in target channel)_
5. Dashboard returns to a workspace integrations page, but _it is not the workspace originally selected_.
6. The page hangs with a loading spinner graphic, but doesn't populate anything

**Comment by ankit-m** [comment]
A fix for this has been deployed.
