### ISSUE TITLE
API Documentation copy to clipboard incomplete

### ISSUE THREAD

**Issue by sijiton** [a85/POSTMan-Chrome-Extension#5703]
**Describe the bug**
In the automatically generated web page of my API documentation, the code examples cannot be fully copied to clipboard unless they are expanded.

**To Reproduce**
1. Go to https://<your_project>.postman.co/collections/<collectionID>?workspace=<workspaceID>
2. Click on Copy to Clipboard button for any example request that can be expanded.
3. You clipboard will only contain the contents that are not expanded.

**Expected behavior**
The clipboard should contain all the code even if it's not expanded.

**App information (please complete the following information):**
 - Generated API documentation
 - Chrome 71
 - OS: macOS 10.14

**Additional context**
It's in the generated API documentation web page.

**Comment by dhineshwiz** [comment]
Hey @sijiton I couldn't reproduce this issue, as for i checked, it was copying the entire content. 
Can u recheck once, and let us know
