### ISSUE TITLE
Undefined and null variables treated similarly in console.log

### ISSUE THREAD

**Issue by rishabhgpt** [a85/POSTMan-Chrome-Extension#5705]
Please read through the [guidelines](https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues) before creating a new issue.

**Describe the bug**
Ideally in test scripts `pm.variables.get` API should return 'undefined' on `console.log`  if an undefined variable is passed to it, instead we get null on console which can create confusion in differentiating if a variable is actually null or simply does not exists.

**To Reproduce**
`pm.variables.set("k1",null)`
`console.log(pm.variables.get("k1"))`
`if (pm.variables.get("k1") === null) {`
`    console.log("k1 is definitely null")`
`}`
`pm.variables.unset("k1")`
`console.log(pm.variables.get("k1"))`

**Expected behavior**
Ideally last console statement should print undefined instead of null.

**App information (please complete the following information):**
 - Native App
 - Postman Version  6.6.1
 - Microsoft Windows 10

**Additional context**

**Comment by pooja098** [comment]
This behavior comes from runtime. Both `console.log(undefined)` and `console.info(undefined)` prints `null` on console. This happens in postman app as well as newman. Hence it's a runtime bug.

**Comment by coditva** [comment]
@rishabhgpt This issue is fixed and out in the latest Postman App `v7.12.0` near you!  🎉
