### ISSUE TITLE
SSL verification broken for wrong host errors

### ISSUE THREAD

**Issue by strongoose** [a85/POSTMan-Chrome-Extension#5709]
**Describe the bug**
Calling a server with an incorrect SSL host setup will fail the first time they are called after starting postman, but subsequent requests will succeed.

**To Reproduce**
1. Enable SSL verification
1. Restart postman
2. Send a GET request to https://wrong.host.badssl.com/
3. Postman will display a connection error
4. Send the GET request again
5. Postman will not display an error and the request succeeds with 200 OK

**Expected behavior**
The same connection error from step 3 is expected in step 5.

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version 6.6.1
 - OS: macOS Mojave 10.14 (18A391)

**Comment by numaanashraf** [comment]
Fixed in Postman v6.7
