### ISSUE TITLE
Add API description which support markdown

### ISSUE THREAD

**Issue by LoveFishSoup** [a85/POSTMan-Chrome-Extension#5710]
> PROBLEM

I am always troubled with colleagues who hardly review API documents during the cooperated project. 

> FEATURE SUGGESTION

I strongly suggest your team could develop the feature named API description(at the same level of [Params], [Headers], [body] and so on, next to [Tests]) which aims to describe the API descriptions and support markdown grammar is the best.

The advantages of this feature show as below:
       
 - The developer could cooperate with other group members via share postman test sets only.

 - The developer could share test sets with other colleagues who might not very similar to this test sets in advance when they far away from the Internet (especially during some important festivals).

Thanks for your time.

**Comment by numaanashraf** [comment]
@LoveFishSoup Markdown supported description are already available in Postman. You can add a description to a saved request via the add description button beside the request name in the tab, or going to the edit option on the sidebar and filling description in the modal.

<img width="964" alt="screenshot 2019-01-05 at 7 40 08 pm" src="https://user-images.githubusercontent.com/3295568/50725318-014e9c00-1122-11e9-8ef1-31bb97b2f26d.png">
<img width="963" alt="screenshot 2019-01-05 at 7 40 17 pm" src="https://user-images.githubusercontent.com/3295568/50725320-04498c80-1122-11e9-96f6-df93e1ac6b75.png">
<img width="301" alt="screenshot 2019-01-05 at 7 40 36 pm" src="https://user-images.githubusercontent.com/3295568/50725321-06abe680-1122-11e9-8010-dc773dea6a48.png">
<img width="487" alt="screenshot 2019-01-05 at 7 40 40 pm" src="https://user-images.githubusercontent.com/3295568/50725322-0875aa00-1122-11e9-99ab-9184b8727298.png">

**Comment by LoveFishSoup** [comment]
> @LoveFishSoup Markdown supported description are already available in Postman. You can add a description to a saved request via the add description button beside the request name in the tab, or going to the edit option on the sidebar and filling description in the modal.
> 
> <img alt="screenshot 2019-01-05 at 7 40 08 pm" width="964" src="https://user-images.githubusercontent.com/3295568/50725318-014e9c00-1122-11e9-8ef1-31bb97b2f26d.png">
> 
> <img alt="screenshot 2019-01-05 at 7 40 17 pm" width="963" src="https://user-images.githubusercontent.com/3295568/50725320-04498c80-1122-11e9-96f6-df93e1ac6b75.png">
> 
> <img alt="screenshot 2019-01-05 at 7 40 36 pm" width="301" src="https://user-images.githubusercontent.com/3295568/50725321-06abe680-1122-11e9-8010-dc773dea6a48.png">
> 
> <img alt="screenshot 2019-01-05 at 7 40 40 pm" width="487" src="https://user-images.githubusercontent.com/3295568/50725322-0875aa00-1122-11e9-99ab-9184b8727298.png">

Thanks a lot!!!! I am too careless~~~~
