### ISSUE TITLE
Browse mode shows no environments for workspace, after duplicating an environment

### ISSUE THREAD

**Issue by JP-from-Postman** [a85/POSTMan-Chrome-Extension#5711]
**Describe the bug**
In Browse mode for the native app, selecting Duplicate for an environment reloads the Environments view showing no environments for the current workspace.

Switching to a different view, and then switching back to Environments, shows the environments for the workspace again, as well the copy that was created.

**To Reproduce**
1. Switch to Browse in native app, and click Environments
2. For any environment in the workspace, click **`...`** menu, and select _Duplicate_
3. View will show "Looks like this workspace doesn't have any environments"
4. Switch to any other view (e.g. Colletions), and switch back to Environments
5. View will now show the existing and duplicated environments

**Expected behavior**
After duplicating environment, view shows all environments.

**Screenshots**

For 2.
<img width="1065" alt="screen shot 2019-01-03 at 11 10 39 am" src="https://user-images.githubusercontent.com/43283131/50656795-305de580-0f49-11e9-832d-08903235159d.png">

For 3.
<img width="1065" alt="screen shot 2019-01-03 at 11 10 46 am" src="https://user-images.githubusercontent.com/43283131/50656810-3eac0180-0f49-11e9-8234-ac093079b19e.png">

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version: 6.6.1
 - OS: macOS High Sierra 10.13.6

**Comment by sankalp0o** [comment]
Looks like this has been fixed for a while, hence closing this. Please let us know if this issue comes up again.
