### ISSUE TITLE
JSON Pretty Response Displays Even When JSON is Invalid

### ISSUE THREAD

**Issue by hadidotj** [a85/POSTMan-Chrome-Extension#5712]
## App Details:
```
Postman for Mac
Version 6.6.1 (6.6.1)
OS X 10.13.6 (17G3025) x64
```

### Did you encounter this recently, or has this bug always been there:
Recent

### Expected behaviour:
When "Pretty Printing" JSON, if there is a parse error in the JSON response, the "Pretty" view should report that error. However, if the response contains invalid JSON (i.e. pesky PHP notices before the JSON) then the Pretty view still shows the "JSON" fine with no indication of an error when I would expect it would give a "Parser" error telling me the JSON is invalid!

### Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
Nothing relevant here from what I could tell. Just a few startup log messages. No errors.

### Screenshots (if applicable):
![image](https://user-images.githubusercontent.com/5050953/50659215-ec2f0d00-0f69-11e9-81d6-1941570d934a.png)
![image](https://user-images.githubusercontent.com/5050953/50659230-f51fde80-0f69-11e9-8e74-696de4227cc2.png)

### Steps to reproduce the problem:
1. Create a JSON file with the following contents:
```JSON
<br/>
<strong>Notice:</strong> a php notice error
<br/>{"this": "is invalid"}
```

2. Make a GET request for the file (i.e. http://localhost/test.json)

3. Notice the "Pretty" view displays the valid portion of the JSON response with no indication there is an error or extraneous data.

4. Notice the "Raw" view displays the extraneous data that should be an error with the JSON parser.

**Comment by kamalaknn** [comment]
This looks like a remnant of special parsing for JSONP responses. However this should not be affecting all responses.

Quick search tells me there is no particular content-type header that we can use to identify JSONP responses. Will have to dig deep.

**Comment by hadidotj** [comment]
Hi @kamalaknn,

I believe **if** the Content-Type header is "application/json", it should be safe to assume the response is **not** JSONP and the *entire response* should try to be parsed as JSON, as [RFC 4627 - The application/json Media Type for JavaScript Object Notation (JSON)](https://www.ietf.org/rfc/rfc4627.txt) outlines that "application/json" should be used strictly for JSON notation, which JSONP is not valid JSON. Since JSONP is fundamentally JavaScript (i.e. execute a callback with JSON as argument), it should use "application/javascript" (aka [RFC 4329](https://www.ietf.org/rfc/rfc4329.txt)), though I know some APIs used "application/json".

Additionally, I would argue that with the introduction of the HTTP Cross Origin Resource Sharing (CORS) headers, JSONP is not as widely used.

Would it be possible to try and "detect" a JSONP response? For example, something that matches:

```/[A-Za-z$_][A-Za-z0-9$_]*\s*\(.*?\)\s*;?/```

Thanks,
Tyler

**Comment by kamalaknn** [comment]
@hadidotj This is fixed on the Postman Canary channel now. We'll push it out to the stable channel soon.

**Comment by hadidotj** [comment]
Hi @kamalaknn. Thanks for the update. I can confirm this is fixed in the latest Postman Canary!
