### ISSUE TITLE
Permissions for a new team collection - Need to have a global setting or ability to set during creation

### ISSUE THREAD

**Issue by thetreythomas** [a85/POSTMan-Chrome-Extension#5713]
**Environment**
Windows 10
Postman v6.6.1

**Is your feature request related to a problem? Please describe.**
By default, when you create a new collection on a team, the permissions are set by default to "Can view". As a team, we are constantly adding collections based on a feature we might be testing individually, but will be used by the entire team later. It's cumbersome to have to go in and modify each collection to "Can Edit" every time you create a new collection.

**Describe the solution you'd like**
Maybe two options:

1. When creating a new collection for a team, there is another tab at the top to allow the choice to be made.
2. A more global setting for the team workspace, that would allow the default behavior of certain things, with the collection permission to be one of them. This would be specific to the workspace, so if you created another workspace, you would have the ability to have different default settings. A working scenario would be one workspace would be for internal dev and QA testing, and the other would be a customer facing where you only want them to view, and not edit.

**Describe alternatives you've considered**
There doesn't appear to be an alternative.

Thanks!

**Comment by bobdesaunois** [comment]
+1, need this!

**Comment by a85** [comment]
Thanks for submitting this. This will be possible with role-based access control system that we are launching soon. We have some basic roles out but more advanced roles will be available as well soon.

**Comment by GianlucaE** [comment]
+1, need this! Is this still a planned feature and is there a time frame when it will be implemented?

**Comment by thetreythomas** [comment]
@a85 - This is still an issue. Our QA team has grown, so we now have new people using Postman (some also new to Postman altogether), so I'm running into this again.

Regardless of the Role, when a new collection is created, the person who created the collection is an Editor, and everyone else is a Viewer. The collection creator/editor still must take that extra step and right click the collection, edit Roles, and then set accordingly (Either "Everyone in Team" or user specific).

There is still a need for the two options I described above, and now with your roles-based changes, there might be a third choice that ties into your roles. For example,  If someone is a developer, you can also assign/link  a collection editor to devs. That way, people un-familiar with this caveat to the way you have collections working, it can be handled at a higher level and just let people work in collections like they expect to be.

**Comment by a85** [comment]
@thetreythomas We are working on improvements to the role based system that will let you map roles to specific groups in specific workspaces automatically. Eventually expectations of who should be assigned which role and the right level of access will have to be mandated by the team admin and some level of manual intervention will exist. However, with a combination of roles + groups + workspaces we expect that this will be a relatively painless process.

**Comment by bjsullivan-speedway** [comment]
I cannot wait for this feature

**Comment by johnny-longo-cko** [comment]
What's the expected ETA on this please @a85 ? Looks like it's been in development for almost a year 😉

**Comment by ghost** [comment]
+1 from someone who has had to just move 20+ members over from Postman Pro to Postman Business with ~100 collections to 6 different workspaces. I can personally vouch for the pain (and RSI) here.

Even after all of that I had to go back and do the same for ~20 environment variables too. :(

**Comment by jfnault-seedbox** [comment]
+1, need this!

**Comment by fp-jcorriveau** [comment]
+1 Would be nice to assign a Role Type as default in a workspace

**Comment by PovilasAtPoq** [comment]
+1. Now 2,5 years has passed :( This is a big struggle, because no one remembers to change the role from Viewer to Editor. Then you need to request access all the time. And it's not like we live in sync world. It's async, so you might need wait for for an approval a few hours (and imagine if the other person is on holiday!). This wastes too much time.

There must be an option that by default collections are created with Editor role for the whole team.

**Comment by andrewchen5678** [comment]
is this solved yet?

**Comment by emmaLP** [comment]
Any update on this please?

Ideally I would like collections to inherit the workspace permissions by default and only set custom permission per collection if necessary. So if I create a new collection, then they default behaviour is to give the access someone who has editor access as workspace level to have that same access at collection level unless there is a custom roles configured on the workspace.

The current functionality is incredibly annoying and as previous said this is wasting time because of permissions. The use of postman is mean to speed us up not slow us down.

**Comment by preethammavin** [comment]
Hey we released new version of worksapces, when you assign the team or an individual to have an editor at the workspace level. All collections, environments, and other elements are elevated to editor role for them. 

The workspace still supports viewer roles, where users can assign view-only permission for the workspace as well. For more details we have a blogpost for the same
https://blog.postman.com/collaborating-postman-workspace-roles/
