### ISSUE TITLE
AssertionError: expected false to be truthy

### ISSUE THREAD

**Issue by Kiholm** [a85/POSTMan-Chrome-Extension#5714]
**Describe the bug**
I use the "Runner" function. I have a Collection and start the runner with default values (except I use Delay 10 ms). After running the collection some of the Requests end in Failed with: 
"AssertionError: expected false to be truthy". 
If I thereafter run the request manual it ens in Passed.
A collection can have about 690 request and some of them have a test like:
"tests["Status code is 201"] = responseCode.code === 201;"

**To Reproduce**
1. Start a runner
2. See error

**Expected behavior**
There is not problem when I run it manual

**Screenshots**

**App information (please complete the following information):**
 - App Type: Desktop app
 - Postman Version 6.6.1
 - OS: Windows 10 Enterprice

**Additional context**

**Comment by numaanashraf** [comment]
@Kiholm Please provide a sample collection we can use to understand your issue better.

**Comment by Kiholm** [comment]
[Test.postman_collection.zip](https://github.com/postmanlabs/postman-app-support/files/2735690/Test.postman_collection.zip)
![2019-01-08 08_38_19-collection runner](https://user-images.githubusercontent.com/14884974/50817773-36770c00-1325-11e9-9d03-79e16cccd442.png)

**Comment by Kiholm** [comment]
any news on this issue?

**Comment by numaanashraf** [comment]
@Kiholm It looks like your tests expect your API to return a 201, but while running the collection, it returned a 200 instead and that lead to the failure of the test and the run. We recommend you use the Postman Console (View > Show Postman Console) to debug the actual request that is sent out and the response received.
