### ISSUE TITLE
Postman Native always returning 404 error on post request

### ISSUE THREAD

**Issue by mjlaz38** [a85/POSTMan-Chrome-Extension#5717]
I am attempting to take a nodejs course and am stuck on the part where we test a post request on Postman. It is a simple example of a node/express app. I can run the GET request without an issue, but the POST is always a 404 error. Can anyone run the code that I list below?

const express = require('express');
const app = express();

app.use(express.json());

const courses = [
    {id:1,name:'course1'},
    {id:2,name:'course2'},
    {id:3,name:'course3'}
]

app.get('/api/courses',(req,res) => {
  res.send(courses);
});

/*Handle POST*/
app.post('api/courses/',(req,res) => {
    const course = {
        id: courses.length + 1,
        name: req.body.name
    };
    courses.push(course);
    res.send(course);
});
  
const port = process.env.PORT || 3000;
app.listen(port,() => {
    console.log(`Listening on port ${port}...`);
})

**Comment by codenirvana** [comment]
@mjlaz38 Typo in `post` path. Try changing it to `app.post('/api/courses/'`.

Also, please read through the [guidelines](https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues) before creating a new issue. This issue tracker is only for Postman App related issues.
