### ISSUE TITLE
Team members not able to edit Collection, despite permissions being set correctly

### ISSUE THREAD

**Issue by JP-from-Postman** [a85/POSTMan-Chrome-Extension#5720]
[Reported on behalf of user, by Postman Support]

**Describe the bug**
Team members are not able to edit a Collection, and it still shows the locked icon, despite permissions being set correctly and team members being a part of the workspace it is shared to.

Both individual (and team default) permissions are set to can edit.

_UPDATE 1:_
User was able to resolve this issue by duplicating the affected Collection, and sharing that one instead.

_UPDATE 2:_
User reports that the affected collection was archived prior to upgrading to Postman Pro.

**To Reproduce**
_Unknown_

**Expected behavior**
Team members should be able to edit the collection.

**Screenshots**
![permissions](https://user-images.githubusercontent.com/43283131/50711666-ca925c00-1023-11e9-9f9c-72548e66ef35.png)

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version: 6.6.1
 - OS: Windows 10

**Comment by numaanashraf** [comment]
Fixed in Postman v7.0
