### ISSUE TITLE
The space occupied by the application multiplies

### ISSUE THREAD

**Issue by ygModesto** [a85/POSTMan-Chrome-Extension#5721]
**Describe the bug**
Every time I open a postman, I create a Postman-timestampt folder (~ 214MB) and a tar.gz file (~ 70MB) and they never get deleted, it has gotten to occupy 8GB

**To Reproduce**
Launch Postman App

**Expected behavior**
Have a version of the application

**Screenshots**
![captura de pantalla de 2019-01-05 11-36-43](https://user-images.githubusercontent.com/9286546/50723498-ed357b00-10de-11e9-8dbe-21abe24bdf11.png)

**App information:**
 - App Type:  Native App
 - Postman Version 6.6.1
 - OS: Ubuntu 18.04 amd64

**Comment by lvillal** [comment]
I have the same issue
![screenshot from 2019-01-24 22 59 38](https://user-images.githubusercontent.com/2653583/51720293-c8705b80-202b-11e9-9722-128c4a214caf.png)

**Comment by numaanashraf** [comment]
Thanks for reporting this @ygModesto @lvillal. We are tracking this at #5034. Closing this as duplicate.
