### ISSUE TITLE
run in postman linux ubuntu 18.04 fails loading collection

### ISSUE THREAD

**Issue by pg07codes** [a85/POSTMan-Chrome-Extension#5723]
**Describe the bug**
when i click the RUN IN POSTMAN button on apidocs.imgur website, the postman opens up but with no collections. It opens like a new window having not request collections.

**To Reproduce**
1. Go to 'apidocs.imgur.com'
2. Click on 'RUN IN POSTMAN'

**Expected behavior**
all request collection for imgur docs should load

**App information (please complete the following information):**
 - App Type [Linux APP ]
 - Postman Version [e.g. 6.3.0]
 - OS: ubuntu 18.04 bionic beaver

**Comment by SamvelRaja** [comment]
@pg07codes  Could you follow the steps here and also verify whether you have configured the .desktop file correctly as mentioned in https://github.com/postmanlabs/postman-app-support/issues/5665#issuecomment-448871412

**Comment by SamvelRaja** [comment]
@pg07codes  Did you get the chance to look into it?
Closing this for now.
Feel free to re-open this in-case you face the issue still.
