### ISSUE TITLE
Support google geolocations to get latitude and longitude

### ISSUE THREAD

**Issue by shashankmishra091** [a85/POSTMan-Chrome-Extension#5724]
Please read through the [guidelines](https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues) before creating a new issue.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by numaanashraf** [comment]
@shashankmishra091 Please provide more details about your use case. You can follow the issue template detailed above to provide this info.
