### ISSUE TITLE
Cannot update to latest version by snap

### ISSUE THREAD

**Issue by kid1412621** [a85/POSTMan-Chrome-Extension#5725]
Please read through the [guidelines](https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues) before creating a new issue.

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
provide the latest snap release.

**Describe alternatives you've considered**

**Additional context**

**Comment by harryi3t** [comment]
This is being tracked here https://github.com/postmanlabs/postman-app-support/issues/5574
