### ISSUE TITLE
Errors in async functions in scripts are not reported in the UI

### ISSUE THREAD

**Issue by pomeh** [a85/POSTMan-Chrome-Extension#5727]
**Describe the bug**
Adding `async` keyword adds side-effects on JavaScript parser

**To Reproduce**
1. Test following snippet in Tests tab:

```
function test() {
    pm.test('test before', function () {
         pm.response.to.be.ok;
    });

    console.log(myVar);

    pm.test('test after', function () {
         pm.response.to.be.ok;
    });
}

test();

pm.test('sample', function () {
     pm.response.to.be.ok;
});
```

2. Test the same snippet, only adding `async` keyword before the function:

```
async function test() {
    pm.test('test before', function () {
         pm.response.to.be.ok;
    });

    console.log(myVar);

    pm.test('test after', function () {
         pm.response.to.be.ok;
    });
}

test();

pm.test('sample', function () {
     pm.response.to.be.ok;
});
```

**Expected behavior**
Both snippets should behave the same, and should throw an error like 'ReferenceError | myVar is not defined'.

Snippet 1 is OK:
- an errror message is displayed in the UI: `Something went wrong while running your scripts. Check Postman Console for more info.`
- an error message is visible in Tests Results tab: `There was an error in evaluating the test script:  ReferenceError: myVar is not defined`
- an error is logged into Postman console: `ReferenceError | myVar is not defined`

![postman-error](https://user-images.githubusercontent.com/285534/50782144-844d2f00-12a7-11e9-8b97-f8de3102cd3c.png)

Snippet 2 is KO:
- no error is visible when running this snippet.
- Tests Results tab show 2 passed tests, and no failed test (while the snippet contains 3 `pm.test` calls)

![postman-error-async](https://user-images.githubusercontent.com/285534/50782145-844d2f00-12a7-11e9-9fa7-1c3087cbaaa2.png)

**App information (please complete the following information):**
 - App Type: Postman for Windows / Version 6.0.10 / win32 6.1.7601 / x64
 - Postman Version 6.0.10
 - OS: Windows 7

I was surprised that some code was not working, then I dig and ended with this simple snippet to reproduce the bug.

Of course, you could ask me not to write typo in my test code, but you know how it works, bugs are everywhere !

I've just updated my Postman version to Version 6.6.1, and while the UI is different, I have the exact same behavior.

**Comment by numaanashraf** [comment]
@pomeh This is the expected behavior with async functions. They return an implicit promise and errors are silent unless you explicitly "catch" the error. 

<img width="724" alt="screenshot 2019-01-17 at 9 00 30 pm" src="https://user-images.githubusercontent.com/3295568/51329232-18cf4280-1a9b-11e9-968c-8d848d2b8ee9.png">

**Comment by pomeh** [comment]
oh ok ! Thanks @numaanashraf for this info and answer :+1: 
And sorry for the invalid ticket created ! :-1:

**Comment by numaanashraf** [comment]
@pomeh Glad I could help. I have updated the PR title to make it easier to find for other users.
