### ISSUE TITLE
Collection variables not resolving in Collection's "Get New Access Token" window

### ISSUE THREAD

**Issue by ghost** [a85/POSTMan-Chrome-Extension#5730]
**Describe the bug**
Variables declared in Collection aren't resolving in Collection's _Get New Access Token_ window.

**To Reproduce**
1. Edit a Collection
2. Add a new variable to Collection
3. Open the _Get New Access Token_ window
4. Attempt to use variable created in step 2
5. See that variable isn't resolved

**Expected behavior**
Variables declared in Collection should resolve in Collection's _Get New Access Token_ window.

**Screenshots**
![image](https://user-images.githubusercontent.com/45204505/50795635-d8064b00-129c-11e9-9585-201ed01d9411.png)
![image](https://user-images.githubusercontent.com/45204505/50795878-ad68c200-129d-11e9-8594-69f857acb575.png)

**App information:**
 - Postman for Windows
 - Version 6.7.0-canary06 (also tested in Version 6.6.1)
 - win32 6.1.7601 / x64

**Additional context**
Using the same variable within a request's _Get New Access Token_ window does work:
![image](https://user-images.githubusercontent.com/45204505/50795811-75617f00-129d-11e9-868d-9e6e073e8cb8.png)

**Comment by ghost** [comment]
This seems to be fixed as of Version 7.0.9.

Can anyone confirm?

**Comment by vikiCoder** [comment]
Yes, you are correct @Bibz87-CG. I checked in the latest version of Postman app (v7.3.4) and it is working fine.
