### ISSUE TITLE
How can I get different responses 200 and 404 for the same request to mock server?

### ISSUE THREAD

**Issue by gummie2** [a85/POSTMan-Chrome-Extension#5731]
## App Details:

```
Postman for Mac
Version 4.11.0
OS X 16.4.0 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:
 2. Expected behaviour:
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 4. Screenshots (if applicable)

**Comment by gummie2** [comment]
I have setup mock server with endpoint containing two examples (same request, different response one with status 200 OK and one with status 404). The request is basically the same, together with endpoint. How can I get different responses 200 and 404 for the same request to mock server?

Thanks

**Comment by numaanashraf** [comment]
@gummie2 You can use the `x-mock-response-code` header to get these different responses. Detailed documentation is at https://learning.getpostman.com/docs/postman/mock_servers/matching_algorithm/
