### ISSUE TITLE
Need Specific Requests

### ISSUE THREAD

**Issue by gummie2** [a85/POSTMan-Chrome-Extension#5732]
## App Details:

```
Postman for Mac
Version 4.11.0
OS X 16.4.0 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:
 2. Expected behaviour:
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 4. Screenshots (if applicable)

**Comment by gummie2** [comment]
I have a collection with multiple folders/requests. When running the collection on a monitor, all of the requests are sent but I only need specific requests to be sent depending on the response to the initial request (first request in the collection). Is this possible? If so, how do I do this?

**Comment by numaanashraf** [comment]
We recommend reaching out to the wider Postman Community (https://community.getpostman.com/) for help with this issue.

Issue Guidelines: https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues
