### ISSUE TITLE
Unrelated GET request body appears despite set to none

### ISSUE THREAD

**Issue by mickael-palma-argus** [a85/POSTMan-Chrome-Extension#5739]
**Describe the bug**
This request: https://developer.largus.fr/#dd21e319-cd52-a164-844b-a174bbf034b1
had unrelated body despite being set to `none`.
I had to set to `raw` and save it.
When I switched back to `none` and save it, I had the proper behaviour.

**To Reproduce**
I did not reproduce it since then.

**Expected behavior**
When set to `none` I expect no body on the online documentation.

**Screenshots**
![screenshot 2019-01-08 at 10 12 30](https://user-images.githubusercontent.com/26302382/50834012-3db50e80-1353-11e9-8a3e-21fdadb3196b.png)

**App information (please complete the following information):**
 - Native App
 - Postman Version 6.7.0
 - OS: Mac OS 10.14.2

**Additional context**
none

**Comment by numaanashraf** [comment]
@mickael-palma-argus Is any other teammate working on the same collection or request?

**Comment by mickael-palma-argus** [comment]
Write rights are just for me.
But the collection is shared with the team.

**Comment by numaanashraf** [comment]
@mickael-palma-argus Thanks for clarifying. Do you remember when you had created this request? Was this created before Postman added support for request bodies in GET request?

**Comment by mickael-palma-argus** [comment]
I created this collection in may 2017.
I don't know when you added the request bodies in GET request.

**Comment by numaanashraf** [comment]
@mickael-palma-argus Thanks for clarifying. This might be a one-off migration issue when we rolled out GET requests with body. We'll take a deeper look why this might have happened. Have you noticed any other requests that had the same issue?

**Comment by mickael-palma-argus** [comment]
I switched back and forth on every affected requests so they are all good now.
