### ISSUE TITLE
GitHub Enterprise Integration Not Syncing behind firewall

### ISSUE THREAD

**Issue by JP-from-Postman** [a85/POSTMan-Chrome-Extension#5741]
[Filed by Postman Support, on behalf of user]

**Describe the bug**
GitHub Enterprise integration (on-prem) is not syncing anything to the designated repo. All configuration appears to be valid, including a valid repo/branch being selected.

Updates to Collection in question appears to be syncing to Postman servers.

**To Reproduce**
_Unknown_

**Expected behavior**
Collection contents are pushed to repo.

**Screenshots**

**App information (please complete the following information):**
 - App Type: Native app
 - Postman Version: 6.6.1
 - OS: Windows

**Comment by JP-from-Postman** [comment]
Update: issue turned out to be caused by host firewall. Feel free to either close, or maybe there's room for a feature request of some kind about logging failures/alerts?

**Comment by jamie-lloyd** [comment]
I believe we're having the same issue. Just got the postman enterprise setup for my team and am unable to sync postman collections with a custom domain. All configuration seems normal, and am able to select the collection / repo as described here. No visible errors with the configuration. Once the integration is added the collection is not synced. Making changes to the collection also does not get synced with github.

**Comment by a85** [comment]
Closing this as this looks like an issue with the host's firewall.
