### ISSUE TITLE
Support for crowd-funding service(s) as billing method

### ISSUE THREAD

**Issue by JP-from-Postman** [a85/POSTMan-Chrome-Extension#5742]
Add integration with Patreon (or other crowd-funding services) as a billing method, to support indie/open source/decentralized dev teams. This way:

- No one has to use their own credit card
- Subscription payments can be donation-based
- Independent co-developers can each chip in for a team subscription, instead of needing to have one person pay up front and be reimbursed (etc)

**Comment by a85** [comment]
Too much of an edge case for us to consider. Probably better for buyers like this to raise funds independently and then buy.
