### ISSUE TITLE
Postman console is removing extra whitespace

### ISSUE THREAD

**Issue by thetreythomas** [a85/POSTMan-Chrome-Extension#5743]
**Describe the bug**
I don't think this is the same as this one - https://github.com/postmanlabs/postman-app-support/issues/2905...

I'm trying to console.log a table, and when I add extra whitespace, the Postman console is always removing it.

**To Reproduce**
1. Create a Test with a console.log() that contains multiple spaces
Ex. console.log("|     Row 1     |     Row 2     |     Row 3     |")
2. Send the request so the test will run
3. View the console in disbelief that it took out your whitespace
4. It gets changed to this "| Row 1 | Row 2 | Row 3|"

**Expected behavior**
I would expect that I can somehow, make it take the format I want. I even tried using _.pad, and the whitespace is removed from that. Tried using "&nbsp" and it will just print that out in the output.

I want to be able to make a nice looking table that is all aligned. This specific call is looking at hard drive and the information about it. Serial numbers, model numbers, etc. are all real long strings, and if I can't pad my table header, it looks off.

**App information (please complete the following information):**
 - Windows Native App
 - Postman Version 6.6.1
 - OS: Windows 10

**Additional context**
Maybe there is an alternative somewhere in Postman that I am missing, but I have exhausted my googling on finding a solution.

**Comment by thetreythomas** [comment]
Ha, the added whitespace was removed on my example on Step 1.

**Comment by thetreythomas** [comment]
Ok, just found something that works. '\xa0'

https://stackoverflow.com/questions/33539797/how-to-create-string-with-multiple-spaces-in-javascript

I guess this is the only way to get this to work?

![image](https://user-images.githubusercontent.com/15376624/50870102-4706a100-137c-11e9-86e1-d24ffe4cb25c.png)

**Comment by numaanashraf** [comment]
Fixed in Postman v7.0
