### ISSUE TITLE
Authorization OAuth 1.0 can't disable encode OAuth signature

### ISSUE THREAD

**Issue by zjh-coder** [a85/POSTMan-Chrome-Extension#5744]
I used to use Postman for Chrome(Version 5.5.4) and it works fine,.
Recently I upgrade to use the native app, but I can't disable encode OAuth signature in Authorization -> OAuth1.0. 
I have to go back to use the chrome version, can you have this feature back or is there any other solutions?

**Comment by codenirvana** [comment]
@zjh-coder Sorry for the delayed response. We are not able to reproduce this issue internally, can you share a scaled-down collection which we can use to reproduce this issue?

**Comment by codenirvana** [comment]
Closing this issue as we are not able to reproduce this internally and we haven't seen other users facing the same.

Please feel free to reopen if the issue persists or you can help us with the steps to reproduce this issue.
