### ISSUE TITLE
Unable to invite users to a personal workspace

### ISSUE THREAD

**Issue by abhijitkane** [a85/POSTMan-Chrome-Extension#5747]
While sharing a personal workspace, the workspace is converted to a team workspace, but I don't see the invited users.

Discovered internally - see linked JIRA issue for details.

**Comment by DannyDainton** [comment]
@abhijitkane Is this something that we can close out now?

**Comment by DannyDainton** [comment]
Closing this issue out, for now, we can open again if it's still an issue.
