### ISSUE TITLE
Failures in user session verification while trying to sign up via team invitation.

### ISSUE THREAD

**Issue by debjeetsarkar** [a85/POSTMan-Chrome-Extension#5751]
This flow affects signup via invitations to a Postman team, where a user's session couldn't be verified and the user is not able to proceed with the signup process.

Discovered internally. See linked JIRA issue for details.

**Comment by preethammavin** [comment]
@debjeetsarkar not able to replicate it, also no information on the issue linked. Do provide the information required to triage this

**Comment by debjeetsarkar** [comment]
This issue was intermittent and has been fixed via an infrastructure upgrade. Closing this.
