### ISSUE TITLE
Chrome interceptor ext opens Chrome Postman app instead of native app

### ISSUE THREAD

**Issue by shershen08** [a85/POSTMan-Chrome-Extension#5754]
**Describe the bug**
How to make Chrome interceptor ext to open a native Postman app instead of outdated Chrome app?

**To Reproduce**
1. Go to Chrome interceptor extension dropdown
2. Click on 'Postman Chrome App'
3. See opening a older chrome app instead of native installed one

**Screenshots**
clicking this
![screen shot 2019-01-09 at 17 40 19](https://user-images.githubusercontent.com/1363772/50913901-b7252d80-1435-11e9-99d2-9bc95bff034e.png)

goes to:
![screen shot 2019-01-09 at 17 37 29](https://user-images.githubusercontent.com/1363772/50913800-77f6dc80-1435-11e9-862f-cf65058bb684.png)

and then:
![screen shot 2019-01-09 at 17 37 39](https://user-images.githubusercontent.com/1363772/50913799-77f6dc80-1435-11e9-9221-d84bda16b4ea.png)

I still have both installed
<img width="211" alt="screen shot 2019-01-09 at 17 37 58" src="https://user-images.githubusercontent.com/1363772/50913798-77f6dc80-1435-11e9-9bf1-59cfea9c7b36.png">

**App information (please complete the following information):**
 - App Type Chrome App, Native App
 - Postman Version Version 6.7.0 (6.7.0)
 - OS: HighSierra 10.13.6

**Comment by numaanashraf** [comment]
This is related to #1667. We are working on Interceptor support for native apps.
