### ISSUE TITLE
PATCH Truncated in documentation

### ISSUE THREAD

**Issue by chrisdeso** [a85/POSTMan-Chrome-Extension#5757]
**Describe the bug**
`PATCH` Requests are being truncated to `PATC` in published documentation

**To Reproduce**
1. Create a collection with a `PATCH` request
2. Publish documentation
3. Navigate to published documentation

**Expected behavior**
`PATCH` requests should render as `PATCH`

**Screenshots**
<img width="264" alt="image" src="https://user-images.githubusercontent.com/4734306/50918897-056f0800-1407-11e9-9904-16393eac7ff3.png">

**Additional context**
[Filed by Postman]

**Comment by numaanashraf** [comment]
@vkaegis Why is this a bug? We explicitly do this for methods with more than 4 characters.
