### ISSUE TITLE
Resource area for URL loses focus when using backspace for removing text

### ISSUE THREAD

**Issue by ghost** [a85/POSTMan-Chrome-Extension#5758]
**Describe the bug**
Resource area for URL loses focus when using backspace for removing text. 

For instance if I have typed a resource URL for a GET request and I execute the request, and I need to switch the servername.
If I hit backspace until the http:// part and start typing the server name, it will only let me type the first letter. 

Example. This is the URL for an example service

http://service:3134/name/?value=f8

If I then want to change the 'service' part of the url because I want to test it on another server I point the cursor just before the colon and
start erasing until http:// it looks like http://:3134/name/?value=f8

Now I want to type something else, but I get no further than the first letter. I have to click in the address bar once again to start typing. The area loses focus.

If it's intentional, it's quite annoying.

**To Reproduce**
1. Go to address bar (resource Url)
2. Type a resource URL for instance here is an example
http://service:3134/name/?value=f8 and execute your request.  
3. Now you want to change some text, for instance the "service" part in the URL. Maybe because you want to test the same stuff
deployed on another server.
4. I point the cursor just before the colon and start erasing until http:// it looks like http://:3134/name/?value=f8
5. The bug is it will only let me type the first letter, then the area loses focus and I have to type again

**Expected behavior**
I expect I am able to type anything I want even when using backspace to erase some text in the address bar

**App information**
 - App Type Native App
 - Postman Version 6.2.4
 - OS:Debian GNU/Linux 9 (stretch) 64-bit

**Comment by numaanashraf** [comment]
@gustaph2016 Thanks for reporting this. Would it be possible to share a screen recording of this?

**Comment by ghost** [comment]
Hi. Sorry for late reply. My screen recording is 26 mb and too large for attaching. 
Actually I managed to upload the compressed movie to my website http://www.hjemliebe.dk/postman.zip please do allow some minutes before downloading since I am hosting my website on Heroku free solution where my page goes idle after 24 hours of no requests. Thanks

**Comment by numaanashraf** [comment]
This issue has been fixed in Postman v7.0.9
