### ISSUE TITLE
Feature Request: It'd be nice to see all collections' fork labels when saving a request

### ISSUE THREAD

**Issue by sdnts** [a85/POSTMan-Chrome-Extension#5760]
👋 Hello! 

App: Postman @ 6.7.1

**Is your feature request related to a problem? Please describe.**
I find it difficult to differentiate between forked collections when saving a request

**Describe the solution you'd like**
An indicator for forked collections in the collection explorer in the Save Request modal (maybe the fork label?)

**Describe alternatives you've considered**
Currently, I can rely on the order of the collections, or even rename the forked collection temporarily.

**Additional context**
Here's a screenshot of the modal in question:
<img width="1536" alt="screenshot 2019-01-10 at 11 44 01" src="https://user-images.githubusercontent.com/7689783/50963455-0e2a1180-14cd-11e9-89f9-b1e6fd655008.png">

The second collection is the forked collection, but since they have the same name, it is difficult to differentiate between the two.

**Comment by vkaegis** [comment]
Thanks for writing in @madebysid! 😄 This is definitely on the cards in terms of short term improvements to the forking and merging flows. Stay tuned for updates!

**Comment by ankit-m** [comment]
The UI has been updated to show collection fork name while saving a request.
