### ISSUE TITLE
Collection variables not working with newman

### ISSUE THREAD

**Issue by dbkaynor** [a85/POSTMan-Chrome-Extension#5761]
I have a collection that works fine in runner but will not run with Newman. The issue is that the collection level variables do not seem to be exported so Newman cannot find them. I see there is a way to import an environment (-e, --environment [file|URL]) but I do not know how to export the environment.

**Comment by kamalaknn** [comment]
Hey @dbkaynor 

The collection variables are stored and exported as part of the collection itself. Can you verify the collection JSON for `variable` or `variables` property?

**Comment by akshitkrnagpal** [comment]
@dbkaynor 
I think you are confusing Collection Variables with Environment Variables. 

Collection Variables are found in a Tab named `Variables` when you are editing the collection. These values (*initial value not current value*) are exported with the collection. They will be accessible when you run a collection with Newman.
See [Defining collection Variables](https://learning.getpostman.com/docs/postman/environments_and_globals/variables/#defining-collection-variables)

Environment Variables are different are found in `Manage Environments` popup. You can `Download` an Environment and use it while running a collection using Newman using `-e`.
See [Sharing an Environment](https://learning.getpostman.com/docs/postman/environments_and_globals/manage_environments/#sharing-an-environment).
