### ISSUE TITLE
"Bad string" error when trying to use variable in JSON example response

### ISSUE THREAD

**Issue by tmdoit-zz** [a85/POSTMan-Chrome-Extension#5762]
Value is integer, I don't want to put it inside double quotes. Error doesn't affect test, which runs properly.
![screenshot 2019-01-10 at 22 57 46](https://user-images.githubusercontent.com/26081817/50999960-f9c93180-152b-11e9-8623-fc5b479f4de6.png)

Postman Version 6.6.1 (6.6.1)

**Comment by saswatds** [comment]
Hi @tmdoit We have been able to reproduce this, the fix will be on the way soon.

**Comment by codenirvana** [comment]
Fixed in the latest version of the Postman app (v7.6.0).
