### ISSUE TITLE
Allow the ability to transfer collection ownership while revoking user role permission for any member of team

### ISSUE THREAD

**Issue by Ramya-From-Postman** [a85/POSTMan-Chrome-Extension#5766]
Currently, if you revoke the user role for any member of a team, the other users in the team workspace will lose access to the shared collections created by that user. 
It would be great if there is an option to given to transfer the ownership of the collections owned by the user to a different user before revoking the user access.

**Note**: Deleting the user is not an appropriate solution as the requirement is to retain the member in the team as either billing or an admin user.

**Comment by jakubfijalkowski** [comment]
It might also be good to make collections without owner so that they always belong to a workspace even if the user leaves it.

**Comment by sankalp0o** [comment]
@Ramya-From-Postman @jakubfijalkowski Sorry for replying so late. This is not expected and we will look into this.

**Comment by mohitranka** [comment]
This issue has been fixed with the release of Environment RBAC.
