### ISSUE TITLE
Add a function to interpolate a string, injecting variables from the environment

### ISSUE THREAD

**Issue by JohnArrowwood** [a85/POSTMan-Chrome-Extension#5767]
Suggest adding a function that will take in a string, and interpolate environment variables exactly the way they are in other parts of the application, such as the url, request parameters, etc.

For example: compare the way we have to do it today:

    let url = pm.variables.get("PROTOCOL") + "://" + pm.variables.get("ADMIN-SERVER") + pm.variables.get("TOKEN-SERVICE");

To what it might look like with the new function:

    let url = pm.interpolate("{{PROTOCOL}}://{{ADMIN-SERVER}}{{TOKEN-SERVICE}}");

**Comment by pomeh** [comment]
Very nice idea @JohnArrowwood !

I've written my own simple function to do that:

```javascript
function interpolate (str) {
    return str.replace(/{{([^}]+)}}/g, function (match, $1) {
        return pm.variables.get($1);
    });
}
```

Right now, it doesn't handle unexisting variables, regex is over-simplified etc. but it works for simple cases.

[pm.variables.get](https://learning.getpostman.com/docs/postman/scripts/postman_sandbox_api_reference/#pmvariables) will read variables from Iteration Data, Environnement or Global scope (the one that defines the value first). Very handy !

**Comment by shamasis** [comment]
We have gotten around to opening up variable substitution within scripts. That would solve this. Tracking this in master issue: https://github.com/postmanlabs/postman-app-support/issues/2922

**Comment by codenirvana** [comment]
We've added support for the new `pm.variables.replaceIn` method in v7.6.0.
Know more: https://github.com/postmanlabs/postman-app-support/issues/2922#issuecomment-527101679
