### ISSUE TITLE
When the only tab open is the default untitled request, opening a call should replace that tab

### ISSUE THREAD

**Issue by chrisron95** [a85/POSTMan-Chrome-Extension#5773]
Please read through the [guidelines](https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues) before creating a new issue.

**Describe the bug**

When no tabs are open, the default `Untitled Request` tab opens. That's fine, but when I open a call, it should replace that default tab if nothing has been done in it. The option for `Always open requests in new tab` is turned on because I need that in my workflow, but the default `Untitled Request` shouldn't apply to that. It's not a big deal, but when I'm very often closing all tabs and then opening a bunch of new tabs, that one empty call at the beginning of the tab list gets annoying.

**To Reproduce**
1. Make sure the `Always open requests in new tab` setting is turned on
2. Close all tabs
3. Try to open a new call from your collections

**Expected behavior**

Opening a call should replace the `Untitled Request` tab if nothing has been changed in it.

**Screenshots**

**App information (please complete the following information):**
Postman for Mac
Version 6.7.1
OS X 18.2.0 / x64

**Additional context**

This only started happening within the past couple months, before that it always replaced the new unused tab, even with the `Always open requests in new tab` setting turned on.

**Comment by sujayvenaik** [comment]
Hey @chrisron95 
This behaviour has been up since the time we made a refactor to our tabs layer.

For the Untitled Requests, we are working on a no tab state which is on our roadmap and will eventually help to get rid of this problem. cc: @vkaegis

**Comment by kamalaknn** [comment]
Hey @chrisdeso 

We made some improvements to certain actions on tabs. Closing all tabs does not automatically open an `Untitled Request` tab now. I hope this makes it easier for you to work with tabs in Postman 😄
