### ISSUE TITLE
Unable to update from within the application

### ISSUE THREAD

**Issue by Achilles1515** [a85/POSTMan-Chrome-Extension#5774]
Sorry if this has been posted before, but I couldn't find a similar issue.

If I click on "Help" --> "Check for Updates", or check for updates through the settings, the application correctly identifies that I am not on the latest version (I am currently on 6.6.1 for Windows).

![image](https://user-images.githubusercontent.com/23387905/51135130-50be5780-1807-11e9-9887-b050266fc734.png)

I then click the "Update" selection in that dialog, and then the "Downloading Update" screen appears for a brief moment and then the following screen appears:

![image](https://user-images.githubusercontent.com/23387905/51135236-7fd4c900-1807-11e9-9901-8cc03e587b31.png)

Postman for Windows
Version 6.6.1
win32 6.1.7601 / x64

**Comment by numaanashraf** [comment]
@Achilles1515  We are having trouble reproducing this issue at our end. Please update to the latest version of the app and let us know if you are still facing this issue.

**Comment by numaanashraf** [comment]
Thank you for your issue! With only the details that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you are still facing this issue.

**Comment by Achilles1515** [comment]
@numaanashraf 

This issue needs to be reopened - I am experiencing the same behavior with trying to update the native app from 7.1.0 to 7.1.1.

See below gif.

![GIF](https://user-images.githubusercontent.com/23387905/58660789-40a99f00-82f4-11e9-87af-1373fb0a68f2.gif)

Let me know if you need anymore info.
