### ISSUE TITLE
API – Team management endpoints

### ISSUE THREAD

**Issue by chrisdeso** [a85/POSTMan-Chrome-Extension#5778]
**Describe the solution you'd like**
Exposing endpoints in the Postman API for team management. More specifically, automating user management.

i.e. `/users` might return a list of user email addresses, their respective roles/permissions, last login, auth types used, etc

**Additional context**
[Filed by Postman]

**Comment by JP-from-Postman** [comment]
Adding on to this: Add RBAC support to endpoints for all relevant entities.

Example: include roles when getting, updating, or creating Collections

**Comment by dwagon** [comment]
Adding to this: we would like to programatically know which users are registered (and consuming a license) so we can reconcile them against our internal user databases.

**Comment by dwagon** [comment]
We would also like to know how many licenses we are consuming, programatically, so we organise more as required

**Comment by davidespihernandez** [comment]
Postman API supports [SCIM](https://en.wikipedia.org/wiki/System_for_Cross-domain_Identity_Management) (System for Cross-domain Identity Management), which allows you to automate the provisioning of your team. You can deploy Postman at scale across your organization and control access to it with your identity provider.

https://www.postman.com/postman/workspace/postman-public-workspace/folder/12959542-842bb61b-7d6f-4ed0-832b-921e1d08fb43?ctx=documentation

Note:

* You must be a [Postman Team admin](http://learning.getpostman.com/docs/collaborating-in-postman/roles-and-permissions/#team-roles) to enable SCIM.
* SCIM provisioning is only available with a Postman Enterprise [pricing plan](https://www.postman.com/pricing).
