### ISSUE TITLE
Variables containing `#` in URL are cut off

### ISSUE THREAD

**Issue by chrisdeso** [a85/POSTMan-Chrome-Extension#5779]
**Describe the bug**
Variables (Environment) that contain `#` are cut off upon saving – both in the UI and the payload.

**To Reproduce**
1. Create an environment variable that contains `#` i.e. `userID#2`
2. Create a request and pass the variable in the request (query param / header / etc)
3. Save
4. Notice that the variable placeholder – i.e. {{userID#2}} – is trimmed before `#`

**Screenshots**

**Before Saving (dirty tab)**
![image](https://user-images.githubusercontent.com/4734306/51224284-c5c68580-190a-11e9-9c83-aab9ae849c53.png)

**After Saving**
![image](https://user-images.githubusercontent.com/4734306/51224290-ceb75700-190a-11e9-9c1d-f784a6512689.png)

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version: Canary 6.7.0
 - OS: mac OS 10.14

**Additional context**
[Filed by Postman]

**Comment by shamasis** [comment]
Hello all,

We put considerable time and effort into this and arrived at an opinion. Postman has specific challenges to URL parsing that is unlike most other url parsers:
- we need to best parse malformed URLs to allow debugging
- we also need to process variables within all parts of URL
- we do not have the complete luxury to be opinionated in our URL parser

The main challenge here is that the variable names itself do not confirm to any rule or character-set restrictions. This means that the only way we can safely parse variable names with URL reserved or URL unsafe characters is by pre-inspecting the entire string. This is significantly slow. You can check out two separate solutions that we attempted at https://github.com/postmanlabs/postman-collection/pull/799 and https://github.com/postmanlabs/postman-collection/pull/801 .

As such, we are considering not resolving this as of now and instead imposing a recommended safe variable name character set, which excludes URL unsafe characters. This would also help down the line when we build more integration features with variables.

As of now, avoid `#`, `:`, `?`, `&` and `=` in variable names.

PS: We will constantly stay on the lookout to improve the URL parser. Especially in line with when JavaScript supports (and we can upgrade) proper lookaround regular expression parsing.

**Comment by shamasis** [comment]
This should not be resolved. More details at https://github.com/postmanlabs/postman-app-support/issues/8154 ... @chrisdeso 😛
