### ISSUE TITLE
UI breaks when response header values are long

### ISSUE THREAD

**Issue by gecimli** [a85/POSTMan-Chrome-Extension#5780]
**Describe the bug**
After calling any service, it does not fit on the screen when there is a long sequence of characters in the result field.
Screnrecord attached
![header section problem](https://user-images.githubusercontent.com/1707525/51233239-6ef89480-197a-11e9-94de-53411697bbf5.gif)

**To Reproduce**
1. Create a New Service Call
2. Click on Send
3. Look at the Result field
4. Click on Header section in result field
5. Header area does not fit when long sequence of characters in the result field

**Expected behavior**
A dimension limitation is required for the corresponding area and the like.

**App information
 - Native App
 - Postman v6.7.1 
 - OS: Windows 10 Pro (Version 10.0.14393 Build 14393)

**Comment by numaanashraf** [comment]
@gecimli Thanks for reporting this. We would address this in the coming releases.

**Comment by numaanashraf** [comment]
Fixed in Postman 7.0
