### ISSUE TITLE
Automatic Save of Requests for Collection Runner

### ISSUE THREAD

**Issue by komape** [a85/POSTMan-Chrome-Extension#5781]
**Is your feature request related to a problem? Please describe.**
If I create a collection and requests for that, I have to use the save button before I can run the collection runner. Intuitively I expect the request to be saved automatically before I run the collection runner. Took me some time to find out the requests were just not saved.

**Describe the solution you'd like**
An automatic save before the collection runner is executed.

**Describe alternatives you've considered**
Add an error message in the collection runner which tells the user the requests have not been saved.

**Comment by komape** [comment]
Postman App Version: 6.7.1
OS: Windows 10 Pro 64-bit

**Comment by a85** [comment]
There are no plans currently for doing that and it is tricky for us to determine when something will be auto-saved. We will look at this when we move the collection runner back to the main window process.

**Comment by komape** [comment]
A dirty flag if the request differs from the last saved request could be a solution. Maybe it would be possible to give an option if it should be autosaved or not.

Why do you closed it instead of putting it on hold?
