### ISSUE TITLE
Remove NTLM password and user on collection export

### ISSUE THREAD

**Issue by szarykott** [a85/POSTMan-Chrome-Extension#5783]
**Describe the bug**
When a collection in Postman is created on Windows 10 Native App and it has NTLM authorization configuration set up, during exporting it to a file, username and password are exported along with. Other people are then able to read it.

**To Reproduce**
1. Create new collection
2. Configure NTLM authorization for it (pass in username and password)
3. Export collection
4. Import previously exported collection (on another machine or as a copy etc.)
5. Username and password can be read as plain text in the application (after `Show password` is clicked)

**Expected behavior**
Two options:

1. Password is not stored at all during export
2. User is asked explicitly if username/password should be preserved in exported collection

**App information:**
 - App Type [Native App]
 - Postman Version [6.7.1]
 - OS: [Windows 10]

**Additional context**
It has the potential to reveal passwords to unwanted people. My work colleague found it in a collection I exported and shared with all the team. I just forgot to remove it from the collection before exporting to .json and didn't think about it at all, truth to be told.

**Comment by numaanashraf** [comment]
Thanks for writing in @SzaryKot. The recommended way to store and use sensitive information in collections and shared resources is via Environments (Docs: https://learning.getpostman.com/docs/postman/environments_and_globals/intro_to_environments_and_globals/). There are no plans to support redacting specific fields while exporting a collection at the moment.
