### ISSUE TITLE
Occurred is misspelt in message "An error occured while running this request" 

### ISSUE THREAD

**Issue by jonathansocol** [a85/POSTMan-Chrome-Extension#5788]
1. Create a new request to a nonexistent end-point (for example: http://localhost/api/whatever)
2. Open the Runner module
3. Execute the collection containing the previously created request
4. The following message is displayed in the results view: _An error occured while running this request. Open DevTools for more info._

**Expected behavior**
The following message is displayed:
An error **occurred** while running this request. Open DevTools for more info.

**Screenshots**
![image](https://user-images.githubusercontent.com/20245064/51312851-84d68a00-1a4c-11e9-8d78-91869973540f.png)

**App information:**
 - Native App
 - v6.7.1
 - OS: Windows 10 (1803 Build 17134.523)

**Comment by numaanashraf** [comment]
@jonathansocol Thanks for pointing this out. We'll get this fixed.

**Comment by numaanashraf** [comment]
Fixed in Postman v7.0
