### ISSUE TITLE
Disable "Click to Expand" on Postman Documentation 

### ISSUE THREAD

**Issue by Kalyse** [a85/POSTMan-Chrome-Extension#5789]
**Is your feature request related to a problem? Please describe.**

My documentation is frequently miss-read by internal and external developers because Postman auto hides content in a "Click to Expand" table and there is no option to turn this off. 

For example:

![vr4_0969](https://user-images.githubusercontent.com/199760/51318375-1399d580-1a52-11e9-8299-fe706ec8352d.png)

**Describe the solution you'd like**
When creating a table, such as the following, I would like to be able to toggle off the "Click to Expand"

![vr4_0670](https://user-images.githubusercontent.com/199760/51318447-480d9180-1a52-11e9-82e3-4e0977a5abcf.png)

It just doesn't make sense to have this when I'm describing values in our documentation. 

```
| Type  | Enum | Description |
| ------------- | ------------- | ------------- |
| CancellationTypes | `SUPER_STRICT_EXTENDED` | <ul><li>Bookings cancelled at least 60 days prior to arrival will receive 50% refund, except fees. </li></ul>|
| CancellationTypes | `SUPER_STRICT` | <ul><li>Bookings cancelled at least 30 days prior to arrival will receive 50% refund, except fees </li></ul>|
| CancellationTypes | `STRICT`  | <ul><li>Bookings cancelled within 48 hours of initial booking will receive a full 100% refund if before 14 days of arrival.</li><li> ..After, 50% refund up until 1 week prior to arrival</li></ul>|
| CancellationTypes | `FIRM`  | <ul><li>Bookings cancelled at least 60 days before the start of stay will receive 100% refund</li><li> Bookings cancelled at least 30 days before the start of stay will receive a 50% refund</li></ul>|
| CancellationTypes | `FLEXIBLE`  |<ul><li>Bookings cancelled at least 7 days prior to arrival will receive 100% full refund, except fees</li></ul>|
| CancellationTypes | `MODERATE`  |<ul><li>Bookings cancelled at least 30 days before the start of stay will receive 100% refund</li><li> Bookings cancelled at least 14 days before the start of stay will receive a 50% refund</li></ul>|
| CancellationTypes | `RELAXED`  |<ul><li>Bookings cancelled at least 14 days before the start of stay will receive 100% refund</li><li>  Bookings cancelled at least 7 days before the start of stay will receive a 50% refund</li></ul>|
| CancellationTypes | `NO_REFUND`  |<ul><li>No refund offered for any reason or timeframe.</li></ul>|
```

**Describe alternatives you've considered**

I've had to resort to adding a custom icon underneath all my tables:

![vr4_0680](https://user-images.githubusercontent.com/199760/51318506-71c6b880-1a52-11e9-9035-f9d543287e33.png)

**Additional context**
None supplied however you can view the active issue: https://docs.lycan.rentivo.com/

**Comment by bt-dd** [comment]
This also related to #5180. Honestly I think that just displaying entire table would fix both, no need for the hover/click action then.

**Comment by ghost** [comment]
this "feature"="bug" actually disables the html anchor tag capability. 

if i hover on an anchor tag in a table, the anchor highlights and underlines as it should. 

![image 1](https://user-images.githubusercontent.com/11749682/58875369-2e2abf00-8680-11e9-9b44-fa4ed70dfb4a.png)

however, when i click on the anchor, a new page opens showing the expanded view of the table, not the destination id of the anchor. the anchor on the expanded table page has also turned color from orange to blue. 

![image 2](https://user-images.githubusercontent.com/11749682/58875413-55818c00-8680-11e9-8a3b-a62c059c2ed4.png)

if i then click on the blue anchor, nothing happens, because the anchor is pointing to an id on the main postman doc page and the expanded table page does not contain that id.

how confusing is that for my clients?  **VERY!**

**easy solution: 
kill the "click to expand" feature or at least provide an option to disable it. 
it doesn't work and even if it did, i wouldn't want it on my pages.**

**Comment by Kalyse** [comment]
@Raja-Simha  

If the issue isn't clear enough, here is a 30 second video narratted video: 

https://www.loom.com/share/ae7a5ff4106b47cb86fd254b25de0c75

I'm planning on migrating our documentation away from Postman because of this problem end of September~ I don't expect any movement, but I trust this advise will hopefully help you improve the documentation product over time for future Postman users.

**Comment by Raja-Simha** [comment]
@Kalyse thanks a lot for the video. Yes, we are aware of this issue and are in the midst of fixing this and other reported issues around 'click to expand'. You will soon see us push out a fix for this. Appreciate you patience and feedback.

**Comment by shashankaholic** [comment]
@vkaegis @Raja-Simha Do we have any ETA on this fix ? Is there a out-of-box workaround to show `click to expand` meanwhile ?

**Comment by Raja-Simha** [comment]
We have fixed the issues around 'click to expand'. Do use this thread to report any feedback.

**Comment by 180Dev** [comment]
Hi, I have the same problem 

![postman](https://user-images.githubusercontent.com/76972654/112208859-35251780-8bef-11eb-8247-11e02ad8109b.png)
