### ISSUE TITLE
'Parse Error' while sending request

### ISSUE THREAD

**Issue by iskandarovBakshi** [a85/POSTMan-Chrome-Extension#5792]
**Describe the bug**
Postman shows only smaller json responses, my api works fine with postman chrome app

I'm running laravel app with docker on localhost:8000

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/15240881/51349050-bb98b880-1abd-11e9-9beb-4647c8b54252.png)
small responses works fine
![image](https://user-images.githubusercontent.com/15240881/51349189-17fbd800-1abe-11e9-8f3c-cf306b5395e0.png)

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version: 6.7.1
 - OS: Ubuntu 18

**Additional context**

**Comment by shamasis** [comment]
There are a few reasons why this error may occur. With the details in the issue it is hard for me to reproduce.

```
1. Content-Length is less than actual response body
2. Invalid HTTP payload
    1. Completely wrong
    2. Missing LF
3. `Transfer-Encoding: chunked` with `Content-Length`
4. Multiple Content-Length
5. Invalid Content-Length
```
Can you check?

**Comment by iskandarovBakshi** [comment]
@shamasis never mind i solved problem

**Comment by saswatds** [comment]
Closing this issue. Feel free to re-open if the issue persists.

**Comment by Yusadolat** [comment]
@iskandarovBakshi Mind if you share how you solved this problem?
