### ISSUE TITLE
Add "Delete all run results" in collection runner window.

### ISSUE THREAD

**Issue by Anakin-Hao** [a85/POSTMan-Chrome-Extension#5793]
Please read through the [guidelines](https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues) before creating a new issue.

**Is your feature request related to a problem? Please describe.**
I have a lot postman collection run results. There's no way to purge all results.

**Describe the solution you'd like**
In the collection runner, it wold be nice to have a "Clear results" button, and if it is clicked, deletes all run results.

**Describe alternatives you've considered**
I can manually click through hundreds, if not thousands of runs' delete button ... not good. 

**Additional context**
None

**Comment by numaanashraf** [comment]
@Anakin-Hao We now support 'Delete all' in the Collection Runner window. 😃

**Comment by doraemonxxx** [comment]
where?

**Comment by sam-gab** [comment]
Same question here... Lol
> where?
