### ISSUE TITLE
Postman automatically appends three dots while values on Body

### ISSUE THREAD

**Issue by anta40** [a85/POSTMan-Chrome-Extension#5795]
**Bug description**
While inputing values on Body, Postman automatically appends three dots (...) at the end of them, after clicking on any other cells. API consuming these values will give different response.

email **steve@gmail.com** and password **hello123** returns OK, but Postman appends three dots, which means values sent to API is **steve@gmail.com...** and **hello123...** which gives not OK result.

**Steps To Reproduce**
1. Input the required URL and headers (if any).
2. Click on 'Body' tab
3. Input a key called 'email'. Now click on the next cell. Input a value, say 'dangrido@ymail.com'. Now click on the next cell, and Postman automatically appends "..." on that email.

**Expected behavior**
After inputing values and clicking the next cell, Postman won't append three dots.

**Screenshots**
![postm](https://user-images.githubusercontent.com/16976/51390960-61523300-1b63-11e9-9450-7946684eb9b5.jpg)

**App information (please complete the following information):**
 - App Type: native app
 - Postman Version: 6.7.1
 - OS: Windows 10 version 1803

**Comment by SamvelRaja** [comment]
@anta40  Could you open postman console to cross verify the same.

You can open the console by the console icon in the bottom left.

![screenshot 14](https://user-images.githubusercontent.com/5114052/51404328-f58eac80-1b07-11e9-9a08-872d2b61a168.png)


This will show you what goes out off postman under the hood.

**Comment by anta40** [comment]
> @anta40 Could you open postman console to cross verify the same.
> 
> You can open the console by the console icon in the bottom left.
> 
> ![screenshot 14](https://user-images.githubusercontent.com/5114052/51404328-f58eac80-1b07-11e9-9a08-872d2b61a168.png)
> 
> This will show you what goes out off postman under the hood.

As I typed some values, the Postman Console didn't display anything.
Is it supposed to display some kind of debugging log?

**Comment by anta40** [comment]
I just noticed that this bug is not that easy to be replicated concistently.
Input some keys and values in Body.
No extra three dots? Good. Erase some values and input again.
Eventually, after some typing, the bug will happen.

**Comment by SamvelRaja** [comment]
@anta40  
Postman console will display the request sent along with response received in more verbose manner.

1. Open the console window
2. Type the request you want to send
3. Click send button.
4. You can see the request and response in the console window.

Take a screenshot of the request you typed in UI and the request sent out in the console window.
Kindly redact any sensitive information.

**Comment by numaanashraf** [comment]
Postman shows a `...` in UI when you have a multi-line value. Please click on the value and make sure there are no multi-line or new-line characters in the value. This `...` is purely in the UI and the full multi-line text is sent while is request is sent (which might cause the error in your case)

![screenshot 2019-01-22 at 2 51 39 pm](https://user-images.githubusercontent.com/3295568/51524976-48909880-1e55-11e9-8661-232e3f7f05d6.png)
![screenshot 2019-01-22 at 2 51 45 pm](https://user-images.githubusercontent.com/3295568/51524981-4af2f280-1e55-11e9-9760-145c9025808a.png)
