### ISSUE TITLE
Impossible to remove the 'user' role from a team member on the team listing page

### ISSUE THREAD

**Issue by abhijitkane** [a85/POSTMan-Chrome-Extension#5797]
On the `/team` page, when I click `Manage Roles`, I'm able to unselect admin and billing, but not user.

There's nothing printed in the console, and no calls go over the websocket when I click "user".

**Comment by ankit-m** [comment]
Can you check if the team already has two support accounts? Removing a `user` role is equivalent to adding a support user and we limit that in the UI to 2.

There is no feedback given and we can improve that.

**Comment by abhijitkane** [comment]
Yep - that seems to be it. This also means that if my user slots are full, there's no way I can re-assign the user role without upgrading my plan. To move the user role from u1 to s1, I first need to add the user role to one of the support members (s1), save, and then remove the user role from u1. This means exceeding my user slots temporarily, which is also not allowed.

**Comment by preethammavin** [comment]
@abhijitkane is this issue fixed?

**Comment by preethammavin** [comment]
The issue has been fixed and pushed, do feel free to reopen the ticket if reoccurs again.
