### ISSUE TITLE
Postman not launching / crashes when NODE_OPTIONS are set

### ISSUE THREAD

**Issue by flash-me** [a85/POSTMan-Chrome-Extension#5798]
**Describe the bug**
When NODE_OPTIONS environment variables are set, the process of Postman immediately stops without any errors. 
This is really annoying, because we are making heavy usage of them and in order to avoid typing the flag down to every task in the project, we are using the environment variables for it.

**To Reproduce**
[Screen Recording](https://user-images.githubusercontent.com/5240450/51428952-de37e800-1c09-11e9-8f18-351b3c8029e7.gif)

**Expected behavior**

Postman should launch when NODE_OPTIONS are set.

This [issue](https://github.com/electron/electron/issues/12695) is known from electron. However, they already have a [workaround ](https://github.com/electron/electron/issues/13402) for it.

**Screenshots**
Recording added.

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version: win64-6.7.1
 - OS: Windows 10 x64

**Comment by SamvelRaja** [comment]
@kqadem  Thanks for bringing this out notice. Yes we do need to upgrade electron to achieve it.
We will update this thread once we does it.

Related to https://github.com/electron/electron/issues/12695
