### ISSUE TITLE
Postman desktop app (Version 6.7.1) crashes upon using "Cancel Request" button when the request contains timeout in Pre-request Script

### ISSUE THREAD

**Issue by ddeshpande** [a85/POSTMan-Chrome-Extension#5799]
Please read through the [guidelines](https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues) before creating a new issue.

**Describe the bug**
Postman desktop app (Version 6.7.1) crashes upon using "Cancel Request" button when the request contains timeout in Pre-request Script

**To Reproduce**
1. Open a request in Postman which contains timeout in Pre-request Script > setTimeout(function() {}, 60000);
2. Click on "Send" button
3. While the request is being sent, click on "Cancel Request" button
4. Postman app crashes

**Expected behavior**
Postman app should not crash upon using Cancel Request button

**Screenshots**
![bandicam20190121114717110](https://user-images.githubusercontent.com/25217651/51456640-7b169480-1d74-11e9-9ad5-9979e46a6594.gif)

**App information (please complete the following information):**
 - App Type: Postman for Windows desktop app
 - Postman Version: 6.7.1
 - OS: Windows(win32 10.0.17134 / x64)

**Comment by sujayvenaik** [comment]
@ddeshpande 
We were able to reproduce this and looking into it.
Thanks for reporting.



Logs for reference: 
[logsGH5799.txt](https://github.com/postmanlabs/postman-app-support/files/2777827/logsGH5799.txt)

**Comment by codenirvana** [comment]
@ddeshpande We've released a fix for this on our Canary (`version: 7.1.0-canary01`) channel https://www.getpostman.com/canary

Will update the thread once we release the fix on our stable channel.

**Comment by codenirvana** [comment]
This has been fixed in the latest Postman app.
