### ISSUE TITLE
The generated code snipped for HTTP produces an incorrect result

### ISSUE THREAD

**Issue by mojo2012** [a85/POSTMan-Chrome-Extension#5800]
**Describe the bug**
The generated code snipped for HTTP produces an incorrect result. The output for an form `POST` looks like this:
```
POST /post HTTP/1.1
Host: postman-echo.com
Content-Type: application/x-www-form-urlencoded
cache-control: no-cache
Postman-Token: 075f666b-b402-4488-bfe7-182eaf1e07e4
bmVerbose=truebmRecipientId=test%40test.atbmEncoding=iso-8859-1Frequenz=allePreference1=UhrenPreference2=Preference3=Preference4=Preference5=Preference6=undefined=undefined
```

The param values are just concatenated without and `&` in between. Also null-values are rendered incorrectly.

**To Reproduce**
1. Open postman and create a new request
2. Set it to `POST`
3. Set any url, eg. `https://postman-echo.com/post`
4. Add some form params like in this screenshot:
![bildschirmfoto 2019-01-21 um 13 39 26](https://user-images.githubusercontent.com/1330361/51475257-21b56200-1d82-11e9-98b9-7dea3cf09912.png)
5. click on `code`

**Expected behavior**
The resulting HTTP code (especially the request body) is valid

**Additional information**
The POSTman echo result ist:
```json
{
    "args": {},
    "data": "",
    "files": {},
    "form": {
        "bmVerbose": "true",
        "bmRecipientId": "test@test.at",
        "bmEncoding": "iso-8859-1",
        "Frequenz": "alle",
        "Preference1": "Uhren",
        "Preference2": "",
        "Preference3": "",
        "Preference4": "",
        "Preference5": "",
        "Preference6": ""
    },
    "headers": {
        "x-forwarded-proto": "https",
        "host": "postman-echo.com",
        "content-length": "172",
        "accept": "*/*",
        "accept-encoding": "gzip, deflate",
        "cache-control": "no-cache",
        "content-type": "application/x-www-form-urlencoded",
        "cookie": "sails.sid=s%3ASCbgIvd-6f_XnnGuwNl7IHjaAF-dziA1.dYXAjsKomwAzXVgbroaCZwmfoQy92BwS%2BPkVuTdVfmc",
        "postman-token": "88191247-896b-4a58-9a6e-b317e5dfb291",
        "user-agent": "PostmanRuntime/7.6.0",
        "x-forwarded-port": "443"
    },
    "json": {
        "bmVerbose": "true",
        "bmRecipientId": "test@test.at",
        "bmEncoding": "iso-8859-1",
        "Frequenz": "alle",
        "Preference1": "Uhren",
        "Preference2": "",
        "Preference3": "",
        "Preference4": "",
        "Preference5": "",
        "Preference6": ""
    },
    "url": "https://postman-echo.com/post"
}
```

**App information (please complete the following information):**
 - Native
 - Postman Version [e.g. 6.0.1]
 - macOS 10.12.6 (16G1710)

**Comment by abhijitkane** [comment]
@mojo2012 
Not able to reproduce this anymore. Also, in Postman 7.2.1, we've introduced bug-fixes, support for two new languages (JS-Fetch and Powershell), and the ability to configure certain aspects of the generated snippet with the 'Experimental Codegen Mode' flag enabled in Postman's global settings.
