### ISSUE TITLE
Error 404 on SSO authentification

### ISSUE THREAD

**Issue by Ramya-From-Postman** [a85/POSTMan-Chrome-Extension#5802]
I've made some configuration to use OKTA's authentification. I've got an error 404 when connecting throw Okta
![image](https://user-images.githubusercontent.com/40994626/51522495-7e328300-1e4f-11e9-80a7-6f51504e3026.png)

**Comment by abhijitkane** [comment]
@Ramya-From-Postman the dependencies for this are solved. For internally discovered issues, we should add more details on the linked JIRA. Not sure if you'd remember what user ticket this issue was originally for.
