### ISSUE TITLE
Enable Javascript in Response Preview

### ISSUE THREAD

**Issue by arunkal1** [a85/POSTMan-Chrome-Extension#5803]
## Issue Report:
 1. Sending a request to some pages, keep getting the error 'Javascript is disabled on your browser. Please enable Javascript and refresh this page'. The page works on the browser but on Postman it comes up with that error. Initially thought it was the page so tried another and still keep getting the error. Tried on other machines but they keep getting the error also.
 
![image](https://user-images.githubusercontent.com/42513943/51523620-00a54d80-1e24-11e9-8910-1dbc05f7ade5.png)

Another site:
![image](https://user-images.githubusercontent.com/42513943/51523742-39ddbd80-1e24-11e9-95dc-acfaba9b77ab.png)

The screenshot above shows the error in Preview mode but this error shows in Pretty or Raw mode also.

I can see a similar issue was open prior but got no resolution. (Error on POST request: "JavaScript is required. This web browser does not support JavaScript..." #3344)

Thanks in advance

**Comment by numaanashraf** [comment]
Duplicate of #2646

**Comment by arunkal1** [comment]
Hi, does not resolve my issue !!!

**Comment by numaanashraf** [comment]
@arunkal1 This is not supported at the moment and we are tracking this as a feature request at #2646

**Comment by lubainaz** [comment]
Hi,

I am facing the same problem. I want to send an an autheticated call on LinkedIn. It was working perfectly fine till few days back. Now it says 'You need to enable JavaScript to run this app.'

Can someone guide me what might be wrong?

Thanks
<img width="1028" alt="postman-3" src="https://user-images.githubusercontent.com/42442764/51673019-42bdc300-1fcd-11e9-8433-ac68d07140b8.png">


<img width="1150" alt="postman-1" src="https://user-images.githubusercontent.com/42442764/51672840-c7f4a800-1fcc-11e9-9698-7b2ff7290939.png">

**Comment by askaaqib** [comment]
@lubainaz did u managed to solve the issue?

**Comment by arunkal1** [comment]
No, unfortunately not

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by nikandlv** [comment]
checkout https://github.com/nikandlv/postman-patcher @lubainaz @askaaqib @arunkal1

**Comment by swissarmychainsaw** [comment]
Why is this closed?

**Comment by nikandlv** [comment]
> Why is this closed?

@swissarmychainsaw they dont want to allow it because of security concerns

**Comment by abccbaandy** [comment]
they should at least give an option to enable that feature, it's very inconvenient to manual copy&paste to some html online editor like this:
https://www.w3schools.com/tryit/tryit.asp?filename=tryhtml_default

**Comment by billhung** [comment]
I have this problem too, looking for a solution. This issue should be re-opened.

**Comment by wuyazibest** [comment]
我遇到了该问题，最后我发现是我的请求格式问题，发送的请求应该是json，但是我在最后面多了以个"  ,  "  ，导致json格式错误

**Comment by WinstonJake** [comment]
@nikandlv thank you very much for your solution. however, i am unable to use it as i use Windows. 
Is there any ETA by which you are planning to release your solution for Windows?
again, thank you!

**Comment by lubainaz** [comment]
B

**Comment by stefanJ-hub** [comment]
Hi,
we use Postman a lot, especially the integrated feature to get an Oauth Token via the Auth Code Flow.
Now our IDS changed and the login form is submitted via javascript. 
This - similar to the topics mentioned above - does not work anymore now. Not able to complete the auth code flow with postman.

The deprecated Postman Chromeapp seems to do still do the job, but comes with its own drawbacks.. and: is deprecated.

The patch from @nikandlv only works for linux/mac versions.
I understand security concerns, but couldn't this be made toggleable (as above mentioned patch is doing) - with disabled just being the default?

Would appreciate the ability to be able to have javascript enabled in the Oauth Login pages rendered by Postman.

If I am just missing a setting, or if you know a workaround / patch for windows - please give me a hint.

Thanks
Stefan

I am on Windows / v7.21.1

**Comment by ghost** [comment]
Yes, same opinion as @stefanJ-hub. Please provide such a setting. 
Thanks,
Patrizia

**Comment by superior57** [comment]
Same here

**Comment by Schnielz** [comment]
Same here.

**Comment by pquy1008** [comment]
Same here.
I need to test an ajax function

**Comment by arlemi** [comment]
This is a duplicate of #2646, please subscribe there to get updates when there is any.

**Comment by Vipisanan** [comment]
> checkout https://github.com/nikandlv/postman-patcher @lubainaz @askaaqib @arunkal1

that option is not available for version 6.7.6. so what I do?

**Comment by arlemi** [comment]
@Vipisanan I'd highly recommend updating Postman to the latest version. 🙂

**Comment by Vipisanan** [comment]
> @Vipisanan I'd highly recommend updating Postman to the latest version.

yeah, I'm using the latest version. still same error :(

**Comment by Messhias** [comment]
Why this is closed? Independent of security concerns or whatever you think of you're protecting me I guess it would be nice to have a way to simulate by enabling something in the configurations with proper warnings and etc... Now me (some people here in the thread).

**Comment by arlemi** [comment]
@Messhias https://github.com/postmanlabs/postman-app-support/issues/5803#issuecomment-638089127

**Comment by Srinivasn0103** [comment]
I had the same issue while calling authorization code with ID Token in postman while calling Okta API, I have resolved the issue by making changes in the postman environment url by removing -admin in the url and it has given the response. 
Try your luck

**Comment by YurySemakov28** [comment]
I deleted the old cookies and copied them from the browser where it works
thanks to this guide https://www.youtube.com/watch?v=WcRHYRaqAnk
