### ISSUE TITLE
Dragging a folder from a collection to a 1st-level folder results in a cyclicImportError on the websocket

### ISSUE THREAD

**Issue by abhijitkane** [a85/POSTMan-Chrome-Extension#5804]
Steps to reproduce:
1. The user signed in to Postman - v6.7.1 for Mac.
2. Waited till the Sync icon turned orange.
3. Expanded a collection in the sidebar - c1.
4. Tried to move a root-level folder (c1.f2) to another root-level folder (c1.f1) (to get c1.f1.f2).
5. The app UI reflected the correct state, but on inspecting the app's websocket connection found that the `/folder/transfer/f2` call made by the app returned a cyclicImportError from the sync server.

Reliably reproducible on signing in.

(Discovered internally at Postman - see attached JIRA for details)

**Comment by mccannt** [comment]
Closing this issue as it has now been resolved.
Please feel free to reopen with the steps to reproduce if the issue persists.
