### ISSUE TITLE
Feature request: add a switch to turn off sending body through GET requests

### ISSUE THREAD

**Issue by jijiechen** [a85/POSTMan-Chrome-Extension#5810]
Please read through the [guidelines](https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues) before creating a new issue.

**Is your feature request related to a problem? Please describe.**
No, not related to a problem, but related to a recently added feature #2729 
The feature of allowing GET requests to send body confused me a lot. 
People send payload through GET requests by mistake sometimes (they just change URL on a past POST tab) and get 417 or 400 responses from servers. It costs us an hour starting to question the Postman could be the source of the issue.

**Describe the solution you'd like**
A switch can be added to allow users to turn this feature off.
Ideally, this feature should be default to off, since it's not following typical HTTP practice.
I believe this scenario should be kind of exception in comparison to normal HTTP requests.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by vkaegis** [comment]
@jijiechen Thanks for writing in! Flagging this as a possible configuration for the app. No ETA on this just yet, but we'll assess it along with other configurations that have been requested by the community.

**Comment by a85** [comment]
There are no plans to turn this feature off. We recommend using the "none" setting.
