### ISSUE TITLE
Unable to leave the team

### ISSUE THREAD

**Issue by Ramya-From-Postman** [a85/POSTMan-Chrome-Extension#5812]
Hi,

**Describe the bug**
I cannot delete myself/ other members from the team, I get the message "**Something went wrong.  An error occurred while removing the user. Please try again**." 

**Steps to reproduce the behavior:**
1. Go to https://go.postman.co/team
2. Try delete your email address or any users email address remove them from the team
4. You see the error "Something went wrong" as shown in the below image. Unfortunately, there are no clues in the console to indicate what went wrong 

**Expected behavior**
Upon clicking on the delete button, the system should let us delete the user in question

**Screenshots**
![image](https://user-images.githubusercontent.com/40994626/53822212-4a419600-3f95-11e9-8602-923d5aa8f3c5.png)

![image](https://user-images.githubusercontent.com/40994626/51600079-30894980-1f27-11e9-94b1-c07a2e83fa53.png)

**App information (please complete the following information):**
 - App Type:  Native App
 - Postman Version: 6.7.1]
 - OS: Windows 8.1

**Comment by fcheadle** [comment]
I commented in the forums, but I think it worth pointing out some more information here - I used to be a member of a paid team, but we decided not to renew our subscription several years ago. There is only one other member of the team, and it allowed me to transfer admin permissions to him, but failed to delete myself after. I am still listed as a team administrator on the postman website

**Comment by preethammavin** [comment]
@fcheadle we have pushed fix for the same, can you confirm if the issue has been resolved at your end?

**Comment by DannyDainton** [comment]
Closing this issue as there was no response for the user to say that this didn't fix the issue. We can open again if this is not the case.

**Comment by fcheadle** [comment]
Hello hello! Sorry for being absent so long. I can confirm that I am no longer in the team. Thanks, guys!
