### ISSUE TITLE
Search: not working :: version 6.7.1

### ISSUE THREAD

**Issue by shahp00ja** [a85/POSTMan-Chrome-Extension#5813]
**App information:**
 - App Type: Native App 
 - Postman Version:  6.7.1
 - OS: macOS 10.13 high sierra 

**Update:** On canary, it started working by itself on 3-4 close and re-open app however the 6.7.1 version, it doesn't work for any search now.

Initial **Description**
Observe the screenshots, the search feature is not able to find the global variables (though works for environment variables). Though I believe the search works on string search rather than variable types.
It used to work earlier (not sure in same versions or different)

**Expected behavior**
Search should work for any character inside the context

**Screenshots**

![image](https://user-images.githubusercontent.com/12966925/51599759-6843c180-1f26-11e9-9c5b-fa16ea273b64.png)
<img width="1221" alt="screen shot 2019-01-23 at 3 46 08 pm" src="https://user-images.githubusercontent.com/12966925/51599611-0d11cf00-1f26-11e9-86ce-97a4e40380b2.png">

**To Reproduce**
1. Open any postman app
2. set something in global variable with a js function ```postman.setGlobalVariable("myGlobalVar", ()=>{}); stle
3. cmd+shift+f  search **myGlobalVar** with or without ticking ignore case
4. Observe error

**Comment by prashantagarwal** [comment]
@shahp00ja Looks like there is some whitespace in the string while you are searching for it.

**Comment by shahp00ja** [comment]
No definitely not, that's the first thing checked for whitespaces, newline characters.  For reconfirmation, retried with typing again freshly, no help.

**Comment by sujayvenaik** [comment]
@shahp00ja 
At the time you are searching, can you check once on the quick look (eye icon) that you have these global variables?

Maybe a case where you are creating the global variable from your script when they do not exist from before.

**Comment by shahp00ja** [comment]
@sujayvenaik that's not the case, the global variable exists and even if that wasn't, still the variable should be found in the pre-request (Open tabs or collections)

**Comment by numaanashraf** [comment]
@shahp00ja These results would show up under open tabs / collections. One factor that might impact the results not showing up is the FILTER. Could you verify that pre-request script / tests are enabled in the filter?

<img width="561" alt="screenshot 2019-01-25 at 6 03 26 pm" src="https://user-images.githubusercontent.com/3295568/51746350-da094000-20cb-11e9-8c49-9c5a628edd4b.png">

**Comment by shahp00ja** [comment]
@numaanashraf yes, everything is selected, the problem persist irrespective of anything [Updated to 6.7.2 and still the same]
(even after shutting down machine and fresh launch, the problem persists)  
Strange that how it gradually stopped working for everything (it used to work, then it stopped working only for global variables and now for none -> suspected if the settings have gone wrong somewhere in the build and I need to delete it completely from everywhere as removing from Application folder and installing new also didn't help. However if that theory is correct than how is it working for Canary on the same machine? is it to with two versions on the same machine, just a wild guess (though have checked launching only one at a time, and it's working perfectly on canary) 


![image](https://user-images.githubusercontent.com/12966925/51836622-e63d0980-2326-11e9-8260-c3960ff383e6.png)
![image](https://user-images.githubusercontent.com/12966925/51836648-fc4aca00-2326-11e9-9114-4d9b517403e7.png)

Please observe the screenshots, tried with everything ticked. 

Is there anywhere I can enable logs behind the functionality (on hit of search button)? the stacktrace can lead to the reason.

**Comment by prashantagarwal** [comment]
@shahp00ja Looks like these screenshots are of just before clicking on Find. Can you add a screenshot after you have clicked on the Find button?

**Comment by shahp00ja** [comment]
:) 100% these are after "find" click, the exact same screen gets rendered after find click as no results are found. Scrolling in results area (if somehow UI issue) was the guess not useful too.
gif for your reference:
![postmansearchbug](https://user-images.githubusercontent.com/12966925/51910339-ec99b700-23f4-11e9-8015-963fd22364da.gif)

**Comment by numaanashraf** [comment]
@shahp00ja Thanks for screenshots. This indeed looks like a bug.

**Comment by aviray48** [comment]
I am running Postman Version 7.0.5 on Windows 7, and I am running into what seems to be the same issue. Nothing that I search for comes back in the results, even things that I am sure are present.

**Comment by phrederick** [comment]
> I am running Postman Version 7.0.5 on Windows 7, and I am running into what seems to be the same issue. Nothing that I search for comes back in the results, even things that I am sure are present.

I'm on v7.18.0 and this is a problem for me too. My colleague does not have the issue so every time I want to find where a variable is referenced in my collections I have to get him to search for me. A real pain :<

**Comment by DannyDainton** [comment]
Hey @phrederick 

Are you able to show the details of the issue that you're facing and is this happening in the latest version of the app?

**Comment by phrederick** [comment]
Hey @DannyDainton,
It's been a while but IIRC, I was able to resolve the issue with a reinstall of Postman. It's not a a feature that I use very often and I'm unable to reproduce it now either. As a side note, I know it's totally unrelated to this ticket but I've noticed some funky behaviour with the request and response panes not resizing properly when maximising a restored window in your latest updates. Maybe you can mess around with trying to replicate that. Here's a screeny:

![image](https://user-images.githubusercontent.com/19385331/91542228-d9e4bc80-e960-11ea-9b27-7e9ee60a344e.png)

**Comment by DannyDainton** [comment]
Awesome - Thanks for the information regarding the original issue.

I'm unable to create the issue your seeing on my side but if you could get some reliable steps to reproduce that one, we can open a new ticket and take a look.

I'm going to close the main issue now but we can reopen if others are still seeing the problem in the new version.
