### ISSUE TITLE
Order of requests inside folders changes after collection merge

### ISSUE THREAD

**Issue by lhyla** [a85/POSTMan-Chrome-Extension#5814]
To Reproduce:
1. Create a 'base' collection with some requests (I had ~180 requests)
2. Fork the base collection
3. Do some changes on fork
4. Merge the fork into base collection
5. Check the order of requests inside folders

I expected that order of requests inside a specific folder will not change after merge (there were any changes in orders of requests in changes). But the order of some requests has been changed randomly (only in the context of a single folder. Order of folders left ok).

It`s problematic when the order of requests make difference in the tests results.
Postman desktop version: v6.7.1
OS: Windows 10 (but merge has been done using postman web app)

Additional info:
There is a way to fix the issue by merging the fork 2 times. But after 1 merge you mustn`t remove your collection. After the second merge of the same fork to the base collection, the order issue is fixed.

The problem exists also with pull, but I was not able to do pull twice. So after first pull, the requests have been re-ordered, but the second pull is not possible. So finally the merge to the base collection would change the order permanently.

**Comment by PFaz540** [comment]
+1

This is incredibly annoying...

**Comment by alexandrelorencini** [comment]
+1

**Comment by lucasmathioni** [comment]
+1

**Comment by dcbasso** [comment]
+1

**Comment by franciones** [comment]
+1

**Comment by dpeliser** [comment]
+1

**Comment by Ghusar** [comment]
Hey guys, we just deployed a fix for this issue, can you verify if it's working as expected?

**Comment by WilliamCesarSantos** [comment]
+1

**Comment by PFaz540** [comment]
> Hey guys, we just deployed a fix for this issue, can you verify if it's working as expected?

@Ghusar Which version is the fix on? Or is this in Postman Canary?

**Comment by preethammavin** [comment]
The fix has been pushed and should be fixed for all existing clients. Closing the issue for now, feel free to reopen it if it is not.

**Comment by Diaidis** [comment]
We are experiencing exactly this issue with Postman v7.0.7 when working with different workspaces. 

Order changes when merging fork back to master. Newly added tests don't keep their order but end up at the end of the folder.

**Comment by preethammavin** [comment]
Hi @Diaidis ,
Can you write to us help@getpostman.com and mention the github issue in the same, lets get this sorted out
Reopeing the thread till we can confirm the issue.

**Comment by preethammavin** [comment]
@Diaidis we have zeroed in on a possible cause for the issue, will update the thread once the fix has been deployed.

**Comment by Diaidis** [comment]
Hi!
Thank you, guys! Appreciate a lot!

**Comment by alot1** [comment]
+1
Looking forward for the resolution. Very annoying issue.

**Comment by preethammavin** [comment]
@Diaidis @alot1  we have fixed the underlying issue which was causing this, it should not happen going forward. Feel free to reopen the issue if it is not fixed.

**Comment by JP-from-Postman** [comment]
@ankitjaggi @Ghusar just received another report of this on 7.20.1. Let me know where you'd like logs, etc, shared.

**Comment by Rafnafnaf** [comment]
+1 happens to me a lot, is very time consuming to fix

**Comment by alot1** [comment]
+1

**Comment by efiark** [comment]
+1 - happened to me a few days ago.  I'm on v7.28.0

**Comment by DannyDainton** [comment]
Is this still an issue for folks using the latest version?

**Comment by mccannt** [comment]
This should now be resolved. Closing this out as there are no current issues confirmed. 
Please reopen if this is still an issue for any users with the latest version of the app.

**Comment by mightymob** [comment]
Hello,

I have Postman v7.35.0.
I still see the issue where at random the order of the requests change drastically.
Please re-open the issue.

Thank you!

**Comment by DannyDainton** [comment]
We have this open issue that we're tracking from the recent 7.35.0 version.

https://github.com/postmanlabs/postman-app-support/issues/9232
