### ISSUE TITLE
Linux arm64 Support

### ISSUE THREAD

**Issue by nathanchilton** [a85/POSTMan-Chrome-Extension#5816]
I am using Postman on an arm64 Chromebook, running Linux using the Crouton method.  The Chrome app works, but there isn't a native version for arm64 linux.  Would you please consider making an arm64 linux native version before you completely kill the Chrome version?

Thank you for your consideration.

**Comment by niikoo** [comment]
Still using the deprecated Chrome app because of this. Would like to run the new linux app on my chromebook (aarch64)

**Comment by christianprim** [comment]
I understand, that you drop Chrome app for native apps on pc/linux/mac. But on a chromebook the Chrome app is the best solution. So please reconsider your decision. I think, you can test the client os, and only allow the install of chrome app on a chromebook, if you want to push native app on pc/linux/mac. Has support for Chrome app not dropped on these platforms?

**Comment by CPC-Dison** [comment]
Why does Postman think x86 (and x86_64) is the only CPU architecture for Linux?

Doesn't Postman know there have been a flood of announcements of new Arm laptops, now that Apple has announced Arm (aka Apple Silicon) for Macs?  

The lack of support for Arm CPU by Postman makes no sense.  I use Chromebook with Arm CPU (and Linux enabled) and prefer this over x86 Chromebook. It is archaic that Postman only supports x86 Linux.

**Comment by koenbeek** [comment]
any ETA ?

**Comment by abrowne2** [comment]
Would be good to know if there is an upgrade path for Apple Silicon now. 

Specifically:
https://www.electronjs.org/blog/apple-silicon

**Comment by brucebrophy** [comment]
Can we expect Postman to support Apple Silicon?

**Comment by vasani-arpit** [comment]
have the same issue. I have a chrome book and arm64 is not supported. 🤷. from the downloads page I found out that there is a web version of the postman which is same as the latest desktop app. I have been using that. so far it works. for people who want to check the local requests, they might need to setup ngrock for that. It's a long way but it is what it is.

**Comment by andrewchen5678** [comment]
just came across this issue when trying to run postman on raspberry pi

**Comment by aymenfurter** [comment]
I was really surprised this is not supported yet. Most developer tools run on arm64 Linux (e.g. IntellIJ, VSCode, terraform, etc). The browser version is also not fully compatible since the InterceptorBridge binary is only available in x64.

**Comment by vasani-arpit** [comment]
I think it is based on electron, so there might be limitation from that. I switched to web version for remote requests on my chromebook and curl for local requests. 🤷‍♂️

**Comment by ConductorPete** [comment]
This is pretty much the only tool that I can't use on my Arch Linux ARM daily driver now. I've had to move to Hoppscotch in the meantime.

**Comment by jokaorgua** [comment]
is there a decision for making this feature or not? any ETA?

**Comment by jviotti** [comment]
Hello everybody, we are doing some evaluation of whether we want to properly support ARM. What devices, specific architectures and Linux distros are you guys running?

**Comment by jokaorgua** [comment]
I'm running Linux Ubuntu 20.04 ARM in parallels VM on mac os Monterey 12.1

**Comment by jviotti** [comment]
After reading this thread again, looks like many users are on Chromebooks. How would you feel about a true native ChromeOS app vs a Linux ARM app?

**Comment by vasani-arpit** [comment]
> After reading this thread again, looks like many users are on Chromebook's. How would you feel about a true native ChromeOS app vs a Linux ARM app?

Native ChromeOS for me because I can barely run VScode on Linux Arm. I don't know why but it is something about crostini which  is affecting the performance or something. Can't be bothered to go deeper into the issue so I changed ARM vscode to vscode.dev and used postman's web version. but native app will help a lot.

**Comment by ConductorPete** [comment]
My vote is for Linux ARM app, and I dare say you'll be seeing an influx of Linux ARM users once Asahi Linux becomes usable as a daily driver on M1 Macbooks. Seems like that timeline is about 3-6 months.

OS: Arch Linux ARM aarch64
Host: Parallels ARM Virtual Machine 0.1
Kernel: 5.16.1-1-aarch64-ARCH

**Comment by aymenfurter** [comment]
Linux ARM App

**Comment by jeffrey-anderson** [comment]
++ On aarch64 support. I am running Ubuntu in a VM on my Mac M1 and it's a dream --- except when I want to have Postman invoke APIs on my local host.

```
$ uname -a
Linux ubum1vm01 5.4.0-99-generic #112-Ubuntu SMP Wed Feb 2 17:13:12 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux
```

**Comment by jokaorgua** [comment]
@jviotti just wondering for how long this poll will last? have you already tried to compile the Postman for linux arm? maybe everything that is needed just to compile and upload deb file for arm? :)

**Comment by jokaorgua** [comment]
@jviotti any updates ?

**Comment by marekmasek** [comment]
Any update on this? I would like to use Postman on Kali ARM on my M1 mac...

**Comment by jviotti** [comment]
Hi everybody, we are actively working on Linux for ARM64 support! We have internal builds and we hope to start rolling this out as soon as it is stable.

**Comment by karlos152** [comment]
hello @jviotti would it be possible to share an alpha/beta version for linux arm64?

**Comment by blake256** [comment]
any update @jviotti ?

**Comment by jviotti** [comment]
We have internal builds going-on. The main blocker we are hitting at the moment is that these builds do not work when running Linux on Apple Silicon. That said, we have a way forward and we'll be resuming the RC preview of this feature soon!

**Comment by jeff-anderson-cscc** [comment]
Nothing would make me happier than being able to use Postman on Ubuntu 22.04 ARM under Parallels on my M1 Mac. Thanks for working on it and please let us know if you need beta testers.

**Comment by robertgzr** [comment]
The good news first: we have a preview build we can share today:
https://drive.google.com/file/d/1Ufvpra2td1ViKZf0PKz4AN_BrGheRTRa/view?usp=sharing

Please check it out and let us know if you're facing any issues with it!

The caveat is, that this still doesn't work when running Linux on bare-metal Apple Silicon (via Asahi Linux). We know what the issue there is though and are working on this in a separate iteration from landing baseline Linux ARM64 support now.

**Comment by jviotti** [comment]
To provide some back story: the Postman application is based on Chromium. While Chromium supports Linux for ARM for a long time, Apple Silicon is not just arm, and it ships with some slight differences around memory page sizes that make some software like Chromium break. See https://chromium.googlesource.com/chromium/src/+/a704c3a94179e6f3abb28f090d096ced72657d7c for more details.

While we have back ported that patch to our custom Chromium build, it doesn't seem to fully work. Based on our experiments, the app may crash when running Linux natively on Apple Silicon at the `execve` system call without much explanation. However, it does appear to work when doing ARM64 virtualization on Apple Silicon running macOS.

We are currently experimenting with ways in which i.e. Asahi Linux is building Chromium (which seems to use custom flags to bypass Chromium's custom allocators), but in the mean-time we would love to know whether this works on your existing Apple Silicon machines, or you are experiencing the same type of seg faults that we experienced in our range of Apple Silicon test equipment.

**Comment by jeff-anderson-cscc** [comment]
I downloaded the beta release and tried to run it on Ubuntu 22.04 arm64 under Parallels on my Mac M1 and I got a core dump:
```
$ PostmanBeta/app/PostmanBeta
[3674:0905/225337.690931:ERROR:power_monitor_device_source_stub.cc(11)] Not implemented reached in virtual bool base::PowerMonitorDeviceSource::IsOnBatteryPower()
The disableGPU setting is set to undefined
Not disabling GPU
[3674:0905/225339.316344:FATAL:xinput.cc(6453)] Check failed: buf.offset < 32 ? 0 : buf.offset - 32 == 4 * length (4212 vs. 4220)
#0 0xaaaacd09c814 base::debug::CollectStackTrace()
#1 0xaaaacce4c894 base::debug::StackTrace::StackTrace()
#2 0xaaaacce4c83c base::debug::StackTrace::StackTrace()
#3 0xaaaacce8a340 logging::LogMessage::~LogMessage()
#4 0xaaaacce8aa0c logging::LogMessage::~LogMessage()
#5 0xaaaacce2aabc logging::CheckError::~CheckError()
#6 0xaaaac3068b14 x11::detail::ReadReply<>()
#7 0xaaaacf913258 x11::Future<>::Sync()
#8 0xaaaacf912d48 ui::DeviceListCacheX11::UpdateDeviceList()
#9 0xaaaacf912dd8 ui::DeviceListCacheX11::GetXDeviceList()
#10 0xaaaacf905ef4 ui::DeviceDataManagerX11::UpdateDeviceList()
#11 0xaaaacf905808 ui::DeviceDataManagerX11::DeviceDataManagerX11()
#12 0xaaaacf9055a0 ui::DeviceDataManagerX11::CreateInstance()
#13 0xaaaacfad6878 ui::X11EventSource::X11EventSource()
#14 0xaaaac3372aec std::__1::make_unique<>()
#15 0xaaaac336ef80 ui::(anonymous namespace)::OzonePlatformX11::CreatePlatformEventSource()
#16 0xaaaac336eb9c ui::(anonymous namespace)::OzonePlatformX11::InitializeUI()
#17 0xaaaac3145b80 ui::OzonePlatform::InitializeForUI()
#18 0xaaaad088f838 aura::Env::Init()
#19 0xaaaad088f730 aura::Env::CreateInstance()
#20 0xaaaac93e2070 content::BrowserMainLoop::InitializeToolkit()
#21 0xaaaac93ed4cc content::BrowserMainRunnerImpl::Initialize()
#22 0xaaaac93dd248 content::BrowserMain()
#23 0xaaaac18d4f80 content::RunBrowserProcessMain()
#24 0xaaaac18d6a2c content::ContentMainRunnerImpl::RunBrowser()
#25 0xaaaac18d6338 content::ContentMainRunnerImpl::Run()
#26 0xaaaac18d1e30 content::RunContentProcess()
#27 0xaaaac18d2754 content::ContentMain()
#28 0xaaaac0c59734 main
#29 0xffffa09873fc (/usr/lib/aarch64-linux-gnu/libc.so.6+0x273fb)
#30 0xffffa09874cc __libc_start_main
#31 0xaaaac0c2d274 (/home/jeff/Downloads/PostmanBeta/app/postmanbeta+0xaaa8273)
Crash keys:
  "osarch" = "aarch64"
  "pid" = "3674"
  "ptype" = "browser"
  "io_scheduler_async_stack" = "0xAAAAC5AB44A4 0x0"
  "platform" = "linux"
  "process_type" = "browser"

Aborted (core dumped)

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.1 LTS
Release:	22.04
Codename:	jammy

$ cat /proc/version
Linux version 5.15.0-47-generic (buildd@bos02-arm64-010) (gcc (Ubuntu 11.2.0-19ubuntu1) 11.2.0, GNU ld (GNU Binutils for Ubuntu) 2.38) #51-Ubuntu SMP Fri Aug 12 08:18:32 UTC 2022

```

**Comment by RaisinTen** [comment]
That crash seems to be coming from https://source.chromium.org/chromium/chromium/src/+/refs/tags/100.0.4896.160:ui/gfx/x/generated_protos/xinput.cc;l=6453 which would only happen if we are using a debug build. @robertgzr could you share a release build instead? That would probably be less crashy.

**Comment by AhmadFazliIsmail** [comment]
> The good news first: we have a preview build we can share today: https://drive.google.com/file/d/1Ufvpra2td1ViKZf0PKz4AN_BrGheRTRa/view?usp=sharing
> 
> Please check it out and let us know if you're facing any issues with it!
> 
> The caveat is, that this still doesn't work when running Linux on bare-metal Apple Silicon (via Asahi Linux). We know what the issue there is though and are working on this in a separate iteration from landing baseline Linux ARM64 support now.

Thank you. Working fine for my Fedora 36 in Macbook Pro M1

![Screenshot_20220913_152914](https://user-images.githubusercontent.com/8059696/189839171-12274bd3-92f3-427e-aa44-f5a15514998a.png)

**Comment by brad** [comment]
> The good news first: we have a preview build we can share today: https://drive.google.com/file/d/1Ufvpra2td1ViKZf0PKz4AN_BrGheRTRa/view?usp=sharing

Holy cow, that's a big file! I can confirm it is not working in Asahi (just segfaults), I assume due to the whole page size shenanigans? I'm subscribed to the thread now and happy to test again when needed

**Comment by RaisinTen** [comment]
> it is not working in Asahi

we did land a fix for that recently :) we'll share something that works on asahi shortly

**Comment by chiappone** [comment]
I get the same stacktrace as @jeff-anderson-cscc for Ubuntu in Parallels M1

**Comment by niklasmato** [comment]
Can't get it to work on Kali on m1 max. 
Is there a newer version/update?

**Comment by jeffrey-anderson** [comment]
I'm also interested to hear an update. All the cool engineers have Mac M1 and we love our Linux!

**Comment by daniel-torrecillas-dsg** [comment]
Any update @RaisinTen ? I'm using Arch Linux in a VM using UTM on an Apple Mac M1 Pro.

**Comment by daniel-torrecillas-dsg** [comment]
The app at https://drive.google.com/file/d/1Ufvpra2td1ViKZf0PKz4AN_BrGheRTRa/view?usp=sharing is crashing when its window is switched back and forth from:

```
[1768:1218/163008.319183:FATAL:render_widget_host_view_aura.cc(557)] Check failed: host_->is_hidden() || visibility_ == Visibility::VISIBLE.
#0 0xaaaad77c1814 base::debug::CollectStackTrace()
#1 0xaaaad7571894 base::debug::StackTrace::StackTrace()
#2 0xaaaad757183c base::debug::StackTrace::StackTrace()
#3 0xaaaad75af340 logging::LogMessage::~LogMessage()
#4 0xaaaad75afa0c logging::LogMessage::~LogMessage()
#5 0xaaaad754fabc logging::CheckError::~CheckError()
#6 0xaaaad4a5b7b4 content::RenderWidgetHostViewAura::ShowImpl()
#7 0xaaaad4a5cdcc content::RenderWidgetHostViewAura::ShowWithVisibility()
#8 0xaaaad4e04574 content::WebContentsImpl::UpdateVisibilityAndNotifyPageAndView()
#9 0xaaaad4e2eeec content::WebContentsImpl::UpdateWebContentsVisibility()
#10 0xaaaad4e86e60 content::WebContentsViewAura::UpdateWebContentsVisibility()
#11 0xaaaad4e88690 content::WebContentsViewAura::OnWindowOcclusionChanged()
#12 0xaaaadafd3390 aura::Window::SetOcclusionInfo()
#13 0xaaaadb419550 aura::DefaultWindowOcclusionChangeBuilder::~DefaultWindowOcclusionChangeBuilder()
#14 0xaaaadb4195b0 aura::DefaultWindowOcclusionChangeBuilder::~DefaultWindowOcclusionChangeBuilder()
#15 0xaaaadb41247c std::__1::default_delete<>::operator()()
#16 0xaaaadb4123f0 std::__1::unique_ptr<>::reset()
#17 0xaaaadb40be3c std::__1::unique_ptr<>::~unique_ptr()
#18 0xaaaadb4072d8 aura::WindowOcclusionTracker::MaybeComputeOcclusion()
#19 0xaaaadb40accc aura::WindowOcclusionTracker::OnOcclusionStateChanged()
#20 0xaaaadb4212cc aura::WindowTreeHost::SetNativeWindowOcclusionState()
#21 0xaaaadb42de6c aura::WindowTreeHostPlatform::OnOcclusionStateChanged()
#22 0xaaaacdaaab04 ui::X11Window::MaybeUpdateOcclusionState()
#23 0xaaaacdaa85e4 ui::X11Window::HandleEvent()
#24 0xaaaacdaa7d58 ui::X11Window::OnEvent()
#25 0xaaaacd654a78 x11::Connection::DispatchEvent()
#26 0xaaaacd6548dc x11::Connection::ProcessNextEvent()
#27 0xaaaacd6544b0 x11::Connection::Dispatch()
#28 0xaaaada208958 ui::(anonymous namespace)::XSourceDispatch()
#29 0xffffbe5c3b58 g_main_context_dispatch
#30 0xffffbe5c4130 (/usr/lib/libglib-2.0.so.0.7400.3+0x6412f)
#31 0xffffbe5c4214 g_main_context_iteration
#32 0xaaaad75ce078 base::MessagePumpGlib::Run()
#33 0xaaaad7712b78 base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::Run()
#34 0xaaaad765eeac base::RunLoop::Run()
#35 0xaaaad3b05ad0 content::BrowserMainLoop::RunMainMessageLoop()
#36 0xaaaad3b12a34 content::BrowserMainRunnerImpl::Run()
#37 0xaaaad3b02298 content::BrowserMain()
#38 0xaaaacbff9f80 content::RunBrowserProcessMain()
#39 0xaaaacbffba2c content::ContentMainRunnerImpl::RunBrowser()
#40 0xaaaacbffb338 content::ContentMainRunnerImpl::Run()
#41 0xaaaacbff6e30 content::RunContentProcess()
#42 0xaaaacbff7754 content::ContentMain()
#43 0xaaaacb37e734 main
#44 0xffffbccb7b80 (/usr/lib/libc.so.6+0x27b7f)
#45 0xffffbccb7c60 __libc_start_main
#46 0xaaaacb352274 (/opt/PostmanBeta/app/postmanbeta+0xaaa8273)
Crash keys:
  "ui_scheduler_async_stack" = "0xAAAACB80B58C 0x0"
  "osarch" = "aarch64"
  "pid" = "1768"
  "ptype" = "browser"
  "io_scheduler_async_stack" = "0xAAAAD7E73E64 0x0"
  "platform" = "linux"
  "process_type" = "browser"
  ```


```
                   -`                    
                  .o+`                   
                 `ooo/                   OS: Arch Linux ARM aarch64
                `+oooo:                  Host: QEMU Virtual Machine virt-7.0
               `+oooooo:                 Kernel: 5.19.8-1-aarch64-ARCH
               -+oooooo+:                Uptime: 15 mins
             `/:-:++oooo+:               Packages: 432 (pacman)
            `/++++/+++++++:              Shell: bash 5.1.16
           `/++++++++++++++:             Resolution: 2056x1286
          `/+++ooooooooooooo/`           WM: i3
         ./ooosssso++osssssso+`          Theme: Adwaita [GTK3]
        .oossssso-````/ossssss+`         Icons: Adwaita [GTK3]
       -osssssso.      :ssssssso.        Terminal: alacritty
      :osssssss/        osssso+++.       Terminal Font: black: '
     /ossssssss/        +ssssooo/-       CPU: (8)
   `/ossssso+/:-        -:/+osssso+-     GPU: 00:02.0 Red Hat, Inc. Virtio GPU
  `+sso+:-`                 `.-/+oso:    Memory: 891MiB / 9927MiB
 `++:.                           `-/+/
 .`                                 `/
```

**Comment by RaisinTen** [comment]
The linux arm64 related changes have already landed in our internal tooling, so we are currently working on incorporating this into the postman app and getting things prepared for releases, etc.

**Comment by malewars** [comment]
Any new on support for arm64 on linux? I don't see any downloads yet.
Linux ubuntuserver 5.15.0-56-generic #62-Ubuntu SMP Tue Nov 22 19:56:13 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux

**Comment by Jocasmen94** [comment]
Hi, I would like to know if there is any updates related to this? thank you

**Comment by brad** [comment]
@Jocasmen94 There is a button on the right to subscribe to updates for this issue. I'm sure they will let us know when they have an update to share 😄

**Comment by RaisinTen** [comment]
We were facing some issues because of other changes that had landed previously in the "internal tooling" I was referring to but I can say that we are making good progress because that problem has been solved. Now we are trying to make the necessary changes in the postman app code and other places to move this forward.

**Comment by bu5h-d** [comment]
Will be looking forward to see it work on kali  on m1

**Comment by twitharshil** [comment]
Hey everyone !!

Postman desktop application that runs natively on a Linux arm64 machine is now available for direct download via the Postman website download [page](https://www.postman.com/downloads/). You can also download it via [this url](https://dl.pstmn.io/download/latest/linux_arm64). This build has auto-updates enabled and new versions of Postman will be pushed via auto-updates.

You can also download it via snap using ```snap install postman```

Please let us know your thoughts and report any issues on this thread.

**Comment by brad** [comment]
Wow, this is great news! @twitharshil I've installed it, imported my collections/environments and tested a few APIs. Working perfectly so far, so thank you thank you thank you!

EDIT: The tests I mention above are in Asahi

**Comment by Jocasmen94** [comment]
Thank you for your great effort, i am.using It right now

Enviado desde mi Samsung Mobile de Claro
Obtener Outlook para Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by bengiddins** [comment]
Surprised to find that the Postman CLI doesn't support ARM64 architecture - installing on Amazon Linux 2023, and got "Only x64 is supported at this time". Nothing in the System Requirements is clear about this for the CLI.

Is there source to build from?
