### ISSUE TITLE
Using variables inside Tests

### ISSUE THREAD

**Issue by jpumph** [a85/POSTMan-Chrome-Extension#582]
Can you use variables inside of tests? I can't get them to work, and from this note on the blog maybe it isn't supported?

"Variables can be used almost everywhere inside Postman. They are available inside:
1. URL
2. URL params
3. Header values
4. form-data/url-encoded values
5. Raw body content
6. Helper fields"

I'm trying to dump fields from a DB table to a CSV, then make an api call against that table and compare to make sure the API is returning exactly what is in the DB table. To do this I need to compare the results from the API call to a variable from a file or environment inside the Test. This should be a pretty common test scenario, but I can't get it to work. 

My CSV has this:
user_uuid,userid,firstnamedb,lastname,address1,city
fc64a589-ca2b-4be6-b645-1afe8a054ac3,jpumph@am.com,Jeremy,Purey,"2805 Londonderry Lane",Conway

The API returns:
{user_uuid: null
firstName: "Jeremy",....

I'm trying to do this in my test:
tests["Returned 200"] = responseCode.code === 200;
var data = JSON.parse(responseBody);
tests["API First Name matches DB"] = data.firstName === "{{firstnamedb}}";
tests["First Name matches"] = data.firstName === "Jeremy";

The first and last tests pass, the middle test trying to use an element in the test fail, even though firstnamedb = "Jeremy". Am I doing something wrong?

**Comment by Abhinay12** [comment]
I want to check whether the  data return after calling api is true or not and i want to compare it with my db

**Comment by Abhinay12** [comment]
how to compare this in db means i want to see whether the data return  in response body is matching with the data available in db or not

can u give me your mail Id sir.........................
