### ISSUE TITLE
Application folder copied (and zipped)

### ISSUE THREAD

**Issue by ccarcaci** [a85/POSTMan-Chrome-Extension#5820]
## App Details:

```
Postman for Linux
Version 6.6.1
linux 4.15.0-43-generic / x64
```

## Issue Report:
I always had this bug.
Every time I run Postman it creates a copy of the application folder (and a zip file too) with trailing timestamp in the name (see the screenshot).

* Open Postman
* Call someone
* Voilà you have won a new folder and zip file!

![screenshot from 2019-01-24 12-55-29](https://user-images.githubusercontent.com/7973726/51676902-4e62b700-1fd8-11e9-8e72-217850608f48.png)

**Comment by numaanashraf** [comment]
Thanks for reporting this @claudiocarcaci. We are tracking this at #5034. Closing this as duplicate.
