### ISSUE TITLE
"Use Token" in "Manage Access Token" always skips current tab token, other tabs ok

### ISSUE THREAD

**Issue by tijaune** [a85/POSTMan-Chrome-Extension#5823]
**Description**
`Use Token` apply the new obtained token to all tabs except the current one.

**To Reproduce**
1. I have 2 tabs with the same `Access Token` xxx.
2. `Access Token` xxx expired, so I used `Get New Access Token`, `Request Token`.
3. A new `Access Token` yyy is received, so we can click on `Use Token`.
4. The new `Access Token` yyy only update other tabs, not the current one.

![snap 2019-01-24 at 10 50 43](https://user-images.githubusercontent.com/17985627/51690097-033fa880-1fc6-11e9-80f1-f86dad0b7a03.png)
**App information**
- App Type [e.g. Chrome App, Native App]
- Postman v6.7.1
- OS: Windows 10, 1809 (17763.253)

**Comment by numaanashraf** [comment]
@tijaune We are having trouble replicating this at our end. Would it be possible to share a screen recording of this?

**Comment by tijaune** [comment]
Hi, attach here is a small mp4 zipped of 01:47 length, hope it will help.

[2019-02-18_13-10-50.zip](https://github.com/postmanlabs/postman-app-support/files/2876946/2019-02-18_13-10-50.zip)

Please note that in order to be able to reproduce, both tabs must have ran a previous request with the same token before. I noticed this behavior because my company expire token setting is 3600 seconds so I see it couple of time daily when I used "Get New Access Token".

**Comment by numaanashraf** [comment]
Thanks @tijaune. We are tracking this as a bug and will update here when the fix is available.

**Comment by dsidirop** [comment]
/bump

I can verify this bug. It made my head in for many hours till I figured out what was wrong with the token I was using. Thought the problem was in our own backend somewhere XD

**Comment by sujayvenaik** [comment]
Hey, @dsidirop  Which version of the app are you on?

**Comment by vikiCoder** [comment]
The token is updating in the current tab as expected in the latest version of the Postman app (v7.3.4). I have attached a GIF showing the same:

![recording2](https://user-images.githubusercontent.com/16588032/62189812-98649500-b38d-11e9-903d-45e2a7331d60.gif)
