### ISSUE TITLE
Allow monitor failure threshold for notifications to be configured

### ISSUE THREAD

**Issue by JP-from-Postman** [a85/POSTMan-Chrome-Extension#5826]
[From Postman Support, on behalf of user]

Please read through the [guidelines](https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues) before creating a new issue.

**Is your feature request related to a problem? Please describe.**
If a monitor is expected (by Collection design/the systems it monitors/the test assertions used) to fail more than 3 times in succession, the current behavior of no longer sending email alerts after the third failure is problematic.

**Possible solutions**
_User requests:_
- Allow user to decide whether to notify for all failures, or until a threshold is reached.
- If the user decides to notify until a threshold is reached, allow the user to determine what the threshold is.

**Comment by Advlaam** [comment]
I took me several hours to figure out why I didn't receive the e-mails of the monitor failures. Just make it configurable for the user and everybody is happy.

**Comment by ArjunSingh-PM** [comment]
@Advlaam, we have introduced an option for you to choose the number of consecutive failures after which you would like your monitor to stop sending failure notifications. Thanks for your patience on this and I hope this helps.

<img width="483" alt="Stop failure notification for consecutive failures" src="https://user-images.githubusercontent.com/53265429/80147778-a4eee480-85d1-11ea-9dd0-6f1ddbdccd93.png">

Documentation reference: https://learning.postman.com/docs/postman/monitors/setting-up-monitor/#the-basics-when-creating-a-monitor
