### ISSUE TITLE
Spawn new tabs when selecting new requests

### ISSUE THREAD

**Issue by chrisdeso** [a85/POSTMan-Chrome-Extension#5828]
**Is your feature request related to a problem? Please describe.**
Currently, opening a new request will only spawn a new tab if the current tab/request has unsaved changes.

**Describe the solution you'd like**
Spawning new tabs whenever a request is selected.

**Additional context**
[Filed by Postman]

**Comment by sujayvenaik** [comment]
Hey @chrisdeso 

There is a setting `Always open requests in new tabs` which will solve your use case.

<img width="706" alt="screen shot 2019-01-25 at 10 42 32 am" src="https://user-images.githubusercontent.com/11532114/51726541-fc7c6880-208d-11e9-8688-1cbe87a41688.png">
