### ISSUE TITLE
Cannot modify permission on forked collection

### ISSUE THREAD

**Issue by Ramya-From-Postman** [a85/POSTMan-Chrome-Extension#5829]
Hi,

When you fork a collection from its original workspace to a Team Workspace, there is no way to set "Modify Permissions" on the new forked collection. 
It only works when you instead fork to the original workspace, then share to the Team Workspace.

**Comment by kaustavkarmakar2** [comment]
Server Setup Wizard runs automatically when you visit
Team Workspace Server in your browser the first time Server is started.
The Setup  guides you to:
Specify the default language for Server.
Connect Workspace Server to an external database (the internal HSQL
database is great for evaluating Workspace Server, but is not
recommended for production installations). You'll need to have
created the external database before running the Setup. For
MySQL, you'll need to have installed the JDBC driver too.

**Comment by numaanashraf** [comment]
Fixed in Postman v7.0
