### ISSUE TITLE
Cannot backup and restore environment from API

### ISSUE THREAD

**Issue by benjefferies** [a85/POSTMan-Chrome-Extension#5831]
**Describe the bug**
Cannot backup and restore environment via the postman API due to 100 item limit

```
{"error":{"name":"malformedRequestError","message":"Found 5 errors with the supplied environment.\nshould NOT have more than 100 items\nshould be string\nshould be string\nshould be string\nshould be string"}}
```

**To Reproduce**
1. Export environment with more than 100 variables
1. Update environment `curl -XPUT https://api.getpostman.com/environments/$ENVIRONMENT -H "X-Api-Key: $TOKEN" -H "Content-Type: application/json" -d "@postman.json"`

**Expected behavior**
HTTP 200 and updated environment

**Comment by numaanashraf** [comment]
Thanks for reporting this @benjefferies. We are tracking this at #5369. Closing this one as a duplicate.
