### ISSUE TITLE
What mock server return is not expected

### ISSUE THREAD

**Issue by tvvbbb** [a85/POSTMan-Chrome-Extension#5835]
I am excited about postman to provide mock server, but I am very disappointed after a few days' uses. What mock server return is not what I expect. For example:
I write 2 examples:
First, no query params then return a,b,c.
Second, with query params 1, then return d,e,f.
But, when I post no query params, mock server return d,e,f, not a,b,c. This is I can't accept.

**Comment by ratpik** [comment]
@tvvbbb - We have identified the bug and will push out a fix out in a couple of days.

**Comment by tvvbbb** [comment]
Thank you. But I hope mock server develope to more powerful. Now just a beta version.

**Comment by ratpik** [comment]
@tvvbbb - This has been fixed now. Do let us know if you have any suggestions for us.

**Comment by tvvbbb** [comment]
No more suggestions. Thank you.
