### ISSUE TITLE
Commas showing up in python3 code generation

### ISSUE THREAD

**Issue by jsaya01** [a85/POSTMan-Chrome-Extension#5837]
This issue occurs whenever trying to produce code from the Postman application. 

To reproduce:
Create a request
go to code
choose python -> python3 http
*this will show commas where there are suppose to be slashes in the request

App information:
Postman Desktop App
Version 6.6.1 (6.6.1)
MacOs mojave

**Comment by abhijitkane** [comment]
@jsaya01 
In the latest Postman version (7.6+), we've introduced bug-fixes around the Python http.client code generation.

The updated code-generation can be seen with the `Global Settings > Experimental Codegen mode` flag set.
