### ISSUE TITLE
Tests: nextRequest: the current script's execution to stop on encountering nextRequest

### ISSUE THREAD

**Issue by p00j4** [a85/POSTMan-Chrome-Extension#5838]
Postman flow’s scope as mentioned:
```
postman.setNextRequest() is always executed at the end of the current script. If you put this function before other code blocks, these blocks will still execute.
```

Does this also mean that for the request, even if the nextRequest is called in a **pre-request**, it will still execute "Tests" section before moving to the next request?

I’m having postman.setNextRequest() in pre-request, still for the last run, the current request’s test script is executed i.e. the task i’m doing in the “test” section, **repeats 1 more additional time**
Shouldn’t only the pre-request be executed till end and move to the next request?
Am I missing something or is it a bug/not supported?

Originally had posted [here](https://community.getpostman.com/t/workflow-how-to-run-another-test-in-loop/2126/4?u=p00j)

**Steps**
1. Have 4 requests
2. loop second and third request 4 times
3. pre-request of second should take to 3rd request and "test" section modify a evrionment list variable  let's say just keep adding the loop counter
4. in request 4, print the list variable
5. run them in runner 

Observe the list variable will be **[0, 1, 2, 3, 3]** instead of **[0, 1, 2, 3]** because the test section still got executed even when pre-request had pointed to the next request to the step 4 after the last counter.
Though, this particular case can be worked around, however, the cases in which the script should not be executed at all because any workaround will make it more reliable, it's better to keep scope only within that script either pre-request or tests but not both.

**Comment by numaanashraf** [comment]
> Does this also mean that for the request, even if the nextRequest is called in a pre-request, it will still execute "Tests" section before moving to the next request?

Yes, Postman will execute the request to completion (pre-request script -> request sent -> response received -> test script) even if you call setNextRequest in the pre-request script.

**Comment by codenirvana** [comment]
@p00j4 Closing this as its expected behavior.
For your use-case, I would suggest using `setNextRequest` in the previous request's test script.
