### ISSUE TITLE
Mock dynamic response based on authorization/headers

### ISSUE THREAD

**Issue by TomasAndersen** [a85/POSTMan-Chrome-Extension#5839]
**Is your feature request related to a problem? Please describe.**
We would like to be able to send calls towards the postman MOCK to simulate a OK/UNAUTH response based on the correct Basic Auth username/password set in the header to test that the client in development has remembered to add authorization. 

**Describe the solution you'd like**
We would like to be able to add examples for a mock request to not only choose the response based on the URL and the params, but also the HTTP headers in the request or the chosen authorization method and username/password.

**Describe alternatives you've considered**
I have tried to look through all documentation for postman, run some google searches and tried it myself in postman without any luck.

Could you please point me in the correct direction if this is already a working feature or could you consider adding this feature? It would be very helpful. Sometimes we would like to force the clients to add the proper header key/values, or choose a correct authorization method to be able to use postman even more advanced than we are doing today.

**Comment by vvs11** [comment]
@TomasAndersen Thanks for writing in
Could you go through this thread and see if it solves your problem?
https://community.getpostman.com/t/mocked-responses-where-the-url-is-identical/7953
Let us know if you need any more info

**Comment by sony-mathew** [comment]
Hey @TomasAndersen , 

We understand your concerns and challenges with your use case. We've been working on improving Mock and have introduced header matching for mock responses. This feature allows you to match mock responses based on specific headers.

You can learn more about this feature and its updates here: [check-for-header-and-body-matching](https://learning.postman.com/docs/designing-and-developing-your-api/mocking-data/matching-algorithm/#6-check-for-header-and-body-matching). 

To access this feature, go to your Mock Server configuration and look for the header matching option: [Match request body and headers](https://learning.postman.com/docs/designing-and-developing-your-api/mocking-data/setting-up-mock/#match-request-body-and-headers).

We hope this resolves your issue. If you have any further concerns or questions, please feel free to reopen this discussion. We're here to help and support you
