### ISSUE TITLE
JSON response not beautified

### ISSUE THREAD

**Issue by thdoan** [a85/POSTMan-Chrome-Extension#5843]
Please read through the [guidelines](https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues) before creating a new issue.

**Describe the bug**
I got an alert saying "Could not beautify" for a JSON response with `Content-Type: application/json` (see screenshot below).

**To Reproduce**
This is an internal server, so you would not be able to reproduce it.

**Expected behavior**
I expect the JSON to be formatted nicely (line breaks and indentation added).

**Screenshots**
![image](https://user-images.githubusercontent.com/4110567/51860861-9262fe00-22ef-11e9-93f1-0e488c4ba545.png)

**App information (please complete the following information):**
 - App Type: Windows desktop app
 - Postman Version: 6.7.2
 - OS: Windows 10

**Comment by sujayvenaik** [comment]
Hey @thdoan
Can you send a screenshot with the response headers as well?

**Comment by numaanashraf** [comment]
@thdoan Thank you for your issue! With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have more information for us to help reproduce this issue, we'll be happy to reopen the issue.

**Comment by Nia-STN** [comment]
Hello, I have the same issue. Not the whole JSON response is beautified, no matter if it is a larger or a short response. 


![Response_not beautified](https://user-images.githubusercontent.com/58035396/69339043-2cc07380-0c6d-11ea-9f2d-03a06e8daa38.png)
