### ISSUE TITLE
Suppressing auto-added request headers

### ISSUE THREAD

**Issue by Balagii** [a85/POSTMan-Chrome-Extension#5844]
**Is your feature request related to a problem? Please describe.**
Postman (native app v6.7.2 on Win 10) emits "Accept: \*/\*" request header every time unless the "Accept" header value is explicitly overridden. I would like to be able to suppress this header completely - not to be sent at all. Right now there doesn't seem to be a way to do this.

Better control of exact request headers sent to the server is important when testing how an API server will respond to a not-so-well-formed request, one that might be missing a few headers that are normally present.

**Describe the solution you'd like**
Ideally, I would like to be able to fully control what headers Postman is sending, not just the ones I explicitly specify in request builder. Alternatively, Postman could expose ALL request headers pre-flight in the "Pre-request Script" tab so I can manually manipulate them before they leave Postman.

**Describe alternatives you've considered**
I tried to manually manipulate the request headers before they leave Postman in the "Pre-request Script" tab. The headers collection only contains a fraction of actual headers emitted - I wish all of them were there. But more importantly, this collection is read-only (documentedly so), so this snippet will add the header and display said header added in console, but then the actual request will not contain the custom header.
<pre>
pm.request.headers.add({
    key: 'X-Foo',
    value: 'bar'
});
console.log(pm.request.headers);
</pre>

somewhat related to #4413 but not the part about complete suppression of certain request headers

**Comment by codenirvana** [comment]
We've added support for request mutations via `pre-request` scripts, Refer: https://github.com/postmanlabs/postman-app-support/issues/4631#issuecomment-477766260

We are tracking a similar feature request to disable all auto-generated request headers here: #2689
