### ISSUE TITLE
xml2Json() does not properly convert XML NIL to JSON null

### ISSUE THREAD

**Issue by jhardin-aptos** [a85/POSTMan-Chrome-Extension#5847]
We're working on developing a framework for doing data-driven Postman tests, and one of the approaches we're exploring is to dump the results from the reference query into an Environment variable in XML format, then in the tests convert that to a JSON object for easier handling.

One problem is that `xml2Json()` isn't properly handling the XML NIL attribute that's used when the data returned by the query for a column is NULL.

`xml2Json()` should detect this and generate a proper JSON null value entry.

Example MS SQL query to generate XML data (the table needs nullable columns with NULLs to exhibit the problem):
`SELECT ( SELECT * FROM email_type FOR XML AUTO, ELEMENTS XSINIL, ROOT ) AS xml;`

The XML generated by such a query:
`<root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"><email_type><email_type_code>HOME</email_type_code><email_type_description>Home Email Address</email_type_description><sort_order>1</sort_order><is_unique>1</is_unique><timestamp>AAAAAAAAWMM=</timestamp></email_type><email_type><email_type_code>VACA</email_type_code><email_type_description>Vacation address</email_type_description><sort_order xsi:nil="true"/><is_unique>0</is_unique><timestamp>AAAAAAAADgw=</timestamp></email_type><email_type><email_type_code>WORK</email_type_code><email_type_description>Work Email Address</email_type_description><sort_order xsi:nil="true"/><is_unique>0</is_unique><timestamp>AAAAAAAAC5Q=</timestamp></email_type></root>`

Note the `<sort_order xsi:nil="true"/>` for a column with a NULL.

Here's the converted JSON associated with one element in that result set having a NIL/null (as dumped directly to the postman console):
```
Object:{}
  email_type_code:"VACA"
  email_type_description:"Vacation address"
  is_unique:"0"
  sort_order:{}
    $:{}
      xsi:nil:"true"
  timestamp:"AAAAAAAADgw="
```
I'd expect to see `sort_order: null` in there instead.

(I won't complain about the quotes around a numeric, that's understandable...  :)  )

I am reluctant to just work directly with the XML natively, as comparing a JSON reference object to the JSON response body will be simpler for the QA test developers to deal with.

**To Reproduce**
1. Generate XML output containing XML NIL and save in a variable
2. Convert that to a JSON object using `xml2Json()`
3. Inspect the results

**Expected behavior**
The XML "xsi:nil = true" should be converted to a native JSON null.

**App information:**
Native PostMan 6.7.2 on Windows 10

**Comment by vikiCoder** [comment]
@jhardin-aptos `xml2Json()` simply parses given XML to JavaScrip object. It is not namespace aware. In other words it does not make any interpretation of element's attributes or modify it in any way. For usage details, refer`xml2js` [documentation](https://github.com/Leonidas-from-XIV/node-xml2js#usage). `xml2Json` is just a wrapper around `xml2js`.

**Comment by codenirvana** [comment]
Closing this issue as we can’t replicate this and we haven’t seen other users facing similar issues.

**Comment by mbhurke** [comment]
While validating xml response, i am converting it in json and then adding validations in postman. But it is giving not converting Nil="true" to null . We are not able to understand how to add validations for this field.
