### ISSUE TITLE
Multiple Windows

### ISSUE THREAD

**Issue by alteraki** [a85/POSTMan-Chrome-Extension#585]
Previously the user was able to open multiple Postman windows (packaged app), however this feature seems to have been disabled or broken.

**Comment by cvmocanu** [comment]
Hello,

Is this still available? With the new theme, I don't see the logo anymore to open a new window.

If you removed this, please add it back.

The tabs are not a replacement:
- I can't move different tabs to different monitors
- I can't have different environments for different tabs

Thanks.

**Comment by cvmocanu** [comment]
This is fixed in the latest version (3.0.0.9). There is a button "New Window" at the top of the page.

I think we can close this.

**Comment by shez1983** [comment]
Hi
I downloaded it recently and Although there is a new window button, when i press it a new window opens with all those funny texts "distorting.." blah blah but the window actually doesnt 'open' ie interactable

**Comment by vegetableman** [comment]
@shez1983 Could you share the screenshot of the devtools window ? (Checkout https://www.getpostman.com/docs/errors). 

Also, would be great if you could create a new issue following the guidelines mentioned in the `Readme` or checkout the format followed in this issue:- https://github.com/postmanlabs/postman-app-support/issues/2352. 

More the details, the quicker we will be able to debug.
