### ISSUE TITLE
New owner of transferred Collection unable to modify permissions to new users

### ISSUE THREAD

**Issue by wsfuller** [a85/POSTMan-Chrome-Extension#5851]
Please read through the [guidelines](https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues) before creating a new issue.

**Describe the bug**
There was a developer that created and owned collection. The developer left the company transferring ownership to another user. The new owner of the collection inherited the collection and was able to View & Edit. The issue we found was that when the new owner went to modify permissions to new developers added to the collection they were only able to Read. After several attempts to modify permissions through the app it was decided to Duplicate the collection. Upon duplication we were able to Modify permissions for new users.

**To Reproduce**
1. Create a collection
2. Transfer ownership
3. Leave company
4. Open collection in Postman App
5. Modify new users from View to Edit
6. Nothing seems to change

**Expected behavior**
We are expecting to be able to transfer ownership of a collection and the new owner to be able to modify permissions seamlessly

**Screenshots**

**App information (please complete the following information):**
Postman for Mac
Version 6.7.2
OS X 18.2.0 / x64
macOS: 10.14.2

**Additional context**

**Comment by abhijitkane** [comment]
@wsfuller This has been marked solved internally. Can you verify?

**Comment by abhijitkane** [comment]
@wsfuller This has been marked solved internally. Can you verify?

**Comment by numaanashraf** [comment]
Fixed in Postman v7.0
