### ISSUE TITLE
Cannot merge fork

### ISSUE THREAD

**Issue by Ramya-From-Postman** [a85/POSTMan-Chrome-Extension#5852]
Unable to merge the forked collection a the page is getting timed out.  

![image](https://user-images.githubusercontent.com/40994626/51964255-ff12ff80-248b-11e9-9167-9e50ac71305e.png)

14 replies

**Comment by ryanshores** [comment]
I was having this issue, but things have gone back to normal for me.

**Comment by numaanashraf** [comment]
Thanks for letting us know @ryanshores. We are closing this issue.
