### ISSUE TITLE
cURL raw POST request with double quoted body not imported properly

### ISSUE THREAD

**Issue by TopHatCroat** [a85/POSTMan-Chrome-Extension#5853]
Using Firefox 64.0.2 developer tools to copy a request on Windows will use a double quote as an escape character, this does not get parsed by Postman properly and produces invalid JSON in POST body.
Example cURL request generated by Firefox when you select 'Copy' > 'Copy as cURL' on a request in developer tools:
```
curl "https://example.com/something" -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:64.0) Gecko/20100101 Firefox/64.0" -H "Accept: application/json" -H "Accept-Language: en-US,en;q=0.5" --compressed -H "content-type: application/json" -H "authorization: Bearer 123" -H "origin: null" -H "DNT: 1" -H "Connection: keep-alive" --data "{""data"":{""type"":""example.something"",""attributes"":{""name"":""the man""}}}"
```
This produces invalid JSON body as seen here:
![image](https://user-images.githubusercontent.com/9058532/51971276-0bda2800-2479-11e9-8f7b-91188225adc2.png)

**To Reproduce**
1. Make a POST request with a body using Firefox on windows 
2. Select it in developer tools under 'Network' tab
3. Right click > Copy > Copy as cURL
4. In Postman go to Import > Paste Raw Text > [Copy the generated request into the box ] > Press 'Import'

**Expected behavior**
Valid JSON body imported

**App information (please complete the following information):**
 - Native App
 - Postman Version v6.7.2
 - Firefox Version v64.0.2
 - OS: Windows 10 Pro 17134.523

**Comment by lazb** [comment]
I have the same issue. 

Using Chrome to copy the curl and using postman version 7.0.7.

Quickest workaround is to copy the curl to notepad++ and replace "" with ", but I would be happy to skip that step :)

**Comment by JochemKlingeler** [comment]
I also experience this problem, but instead of manually replacing the quotes you can also simply copy the POST body using the context menu in the developer tools.

I would also like to see a fix.

**Comment by Dhroov7** [comment]
Thanks @TopHatCroat for reporting but unfortunately we are blocked to solve this issue as shell-quote isn't aware of using double quote as an escape character.
We have raised the issue on their Github repo. https://github.com/substack/node-shell-quote/issues/38.
We'll resolve this issue as soon as they update this feature.

**Comment by DannyDainton** [comment]
Closing this issue as it has now been resolved.
Please feel free to reopen with the steps to reproduce if the issue persists.
