### ISSUE TITLE
Monitors page error

### ISSUE THREAD

**Issue by abhijitkane** [a85/POSTMan-Chrome-Extension#5854]
Discovered internally at Postman - see attached JIRA for details.

A free user is trying to access their personal workspace's monitors, and sees a 'something went wrong' page.

The WS call to /api/metrics is returning a 403. 

The collections tab of the same workspace works properly, and the collection the monitor is on is also visible to the user.

**Comment by ArjunSingh-PM** [comment]
This issue is resolved. Closing the same.
