### ISSUE TITLE
Postman missing collection menu items

### ISSUE THREAD

**Issue by eaglesvr** [a85/POSTMan-Chrome-Extension#5855]
## App Details:
Postman for Windows
Version 6.7.0-canary06
win32 6.1.7601 / x64

## Issue Report:
Collection/Folder menu missing these items:
- Share Collection
- Modify Permissions
- Export
- Monitor Collection
- Publish Docs
- Remove from workspace

The only available items are:
-Rename
-Edit
-Add Request
-Add Folder
-Duplicate
-Delete
The app is signed in, 
The same issue with the old Chrome App
I remember having an ability to Export collection some time before, but can't do this anymore.

**Comment by sujayvenaik** [comment]
@eaglesvr 
Can you provide screenshots for the view where you faced this?

**Comment by eaglesvr** [comment]
My fault- I copied collection to a folder and was looking at the wrong menu item. Closing
