### ISSUE TITLE
Able to copy text outside of modal in Documentation example body

### ISSUE THREAD

**Issue by ghost** [a85/POSTMan-Chrome-Extension#5857]
In published documentation, clicking on a JSON example brings it out into a modal body. If you click into the modal and ctrl+A ctrl+c, you end up grabbing the whole webpage, not just the contents of the modal

**Comment by Cazaimi** [comment]
The copy-all functionality can be achieved by clicking the "Copy to Clipboard" button. @Raja-Simha please mark this as a feature request.

**Comment by akshaydeo** [comment]
Hello @scottishkilt, apologies for the delayed update; this issue is fixed on our latest apps. Feel free to reopen the ticket if you are still facing the issue 🙇‍♂️
