### ISSUE TITLE
expected false to be truthy at assertion:1 in test-script Issue

### ISSUE THREAD

**Issue by abhishek-kandala** [a85/POSTMan-Chrome-Extension#5859]
I am having old assertions in my postman collections:
tests["Service Status is 100"] = responseBody.has("<serviceStatusCode>100</serviceStatusCode>");
While integrating with jenkins and running the test scripts its failing with following error:
expected false to be truthy at assertion:1 in test-script 

Can you please let me know what parameters I need to pass in NewmanRun command.

## Issue Report:
1. Expected behaviour: The test case should pass

**Comment by numaanashraf** [comment]
@abhishek-kandala This seems to be an issue with the assertions in your script. We recommend reaching out to the wider Postman Community (https://community.getpostman.com/) for help with this issue.

Issue Guidelines: https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues
