### ISSUE TITLE
Cookie is not saved when connecting to an IPv6 address

### ISSUE THREAD

**Issue by boddens** [a85/POSTMan-Chrome-Extension#5860]
**Describe the bug**
When connecting to an IPv6 endpoint, the cookie is not saved while it is send from the server, so it will not be used in subsequent requests. If connecting using IPv4 to the same endpoint (and getting the same cookie header), then the cookie is saved and used.

**To Reproduce**
1. Connect to an IPv6 host (used the format https://[2a00:aaaa:aaaa:aaaa::aaa]:8443
2. Check the response header for Set-Cookie; it does exist and is valid
3. Check the cookie tab in postman; no cookie has been set

If I follow the steps but replace the IPv6 address for an IPv4 address, then the set-cookie header is also valid, but the cookie is saved.

**Expected behavior**
Cookie is saved and used in subsequent requests.

**Screenshots**

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version: v6.7.2
 - OS: Windows 10.0.15063

**Additional context**

**Comment by shamasis** [comment]
Hey... wanted to update here that the issue has been fixed and will be bundled along with upcoming release (and possibly earlier in Canary.)

**Comment by codenirvana** [comment]
This is fixed in the latest Postman App (v7.1.0).
