### ISSUE TITLE
Allow automated save for responses and publishing docs 

### ISSUE THREAD

**Issue by pralhadgoggi** [a85/POSTMan-Chrome-Extension#5866]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when...
To publish samples of my API, I currently manually save responses and then click “Publish Docs” for every collection I have in my project.

**Describe the solution you'd like**
Provide some way either through Newman or Runner to save all requests/responses during an automated run and publish them.

**Describe alternatives you've considered**
No alternatives exist, I have to do this manually.

**Additional context**
None.

**Comment by ParasVarshney** [comment]
Is there any option in postman to show optional and mandatory fields in body with json response????

**Comment by DannyDainton** [comment]
Closing this due to a lack of information. If you still require this feature, can you please update the description and provide more relevant context.
