### ISSUE TITLE
Monitoring is failing in postman pro 

### ISSUE THREAD

**Issue by vmarkova** [a85/POSTMan-Chrome-Extension#5868]
**Describe the bug**
Monitors keep failing. Have exactly same issue described in ticket #3128, but that ticket is closed and I'm not sure if I could get any other response there. Tried advised there disabling of SSL - didn't help :(
All tests are successful in Postman API Runner, monitor keeps being failed thou (Console logs in monitor aare actually saying that monitor gets correct and successful status code, but it is still failing for some reason) . Exact same errors in console log, but all advices above don't help (tried disabling SSL, checked url, checked enviroment).

**To Reproduce**
1. Go to Postman API (Mac), create collection, try with runner - all tests pass. 
2. Create Monitor, disable SSL, go check it in Postman Chrome - all monitors fail. 

**Expected behavior**
If Collection tests are successfully passing in runner - monitor have to be successful as well. 

**Screenshots**
Attached with covered company information for security reasons.
<img width="1190" alt="screen shot 2019-01-29 at 1 54 27 pm" src="https://user-images.githubusercontent.com/42750244/52079477-82932600-254a-11e9-9184-bd1485a02dd6.png">
<img width="1712" alt="screen shot 2019-01-29 at 1 53 53 pm" src="https://user-images.githubusercontent.com/42750244/52079478-82932600-254a-11e9-869b-fb9bf2c298b1.png">

Thank you in advance, looking for your help!

**Comment by godfrzero** [comment]
@vmarkova Two things you could check:

1. Is the URL in question publicly accessible?
2. Are the correct environment variables present in the "Initial value" column?

To help you debug further, have you tried adding console logs within the monitor run to verify that environment values are being populated correctly? The errors in the console seem to imply that a non-JSON response is being parsed as JSON, which is throwing an exception.

**Comment by vmarkova** [comment]
I cannot share URL due to confidentiality of company, but it is working well. When you run same collection with same environment in Postman Runner - it works without any exceptions (please see screenshot above attached), but when you create monitor (without modification) - monitor fails.

**Comment by vmarkova** [comment]
Hello, could somebody give an update on this issue? It's been a month so far.. 
Thank you!

**Comment by DarrylGwinnett** [comment]
You're getting ECONNREFUSED. Doesn't like like a Postman problem really. when you run them in your app, presumably you're on a company network which can access your confidential URL. When it runs as a monitor the URL needs to be accessible from Postman's servers. You might need to change your firewall settings.

**Comment by godfrzero** [comment]
@vmarkova It looks like you're trying to connect to a URL which cannot be reached publicly. Because monitors run on the Postman Cloud, any URL to be contacted should resolve to a publicly accessible IP. Again, you don't have to disclose the actual URL, but unless the address is publicly accessible this is not a bug.

**Comment by Thor07** [comment]
I have a publicly available URL and global variable doesn't substitute the value on monitor ,works fine on app.

**Comment by godfrzero** [comment]
@Thor07 Globals aren't supported within monitors. Only variables that are present in the collection + environment can be used.

**Comment by twelve-cgn** [comment]
Hello, this issue should not be closed. Same problem here. The collection passed in the app. But the monitor fails. The url is public (tested with mobile). But i think the "disable ssl verification" option in monitor is not be considered.

**Comment by godfrzero** [comment]
Hey @moellerbj, what's the error you're seeing here? If you can open up a ticket via our support center, we can probably get to the root of the problem faster.

**Comment by twelve-cgn** [comment]
hallo @godfrzero , sorry  false alarm (**embarrassing**). My mobile was configured in the firewall.

**Comment by godfrzero** [comment]
No problem, happens to all of us. 👍
