### ISSUE TITLE
Authorization header not being sent

### ISSUE THREAD

**Issue by dakujem** [a85/POSTMan-Chrome-Extension#5872]
**Describe the bug**
Authorization header is not being sent to the server.

**To Reproduce**
1. either set the authorization to bearer token and add a token
2. or use the headers section and fill in anything and set the authentication to none

Neither works, no matter how i try to set the header.

**Expected behavior**
I would expect the `Authorization` header to be sent.

**Screenshots**
If I try `x-authorization`, this header gets to the server.
![image](https://user-images.githubusercontent.com/443067/52093122-52836b80-25ba-11e9-9abe-541035d10632.png)

**App information:**
 - App Type Native App
 - Postman Version [e.g. 6.7.2]
 - OS: Windows 10 x64
- PHP , Apache 2, mod_fcgid

```php
// dump(getallheaders());
array(7) {
   "Connection" => string(5) "close"
   "Accept-Encoding" => string(13) "gzip, deflate"
   "Host" => string(11) "crm.qlis.lo"
   "Accept" => string(3) "*/*"
   "User-Agent" => string(20) "PostmanRuntime/7.6.0"
   "Cache-Control" => string(8) "no-cache"
   "X-Authorization" => string(158) "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE1NDg5Nzg5MDEsImlhdCI6MTU0ODk3NzEwMSwiYXVkIjoidmlhYXVyZWEifQ.5FRmodEoDuFsDq_DL0lr68QRFQL9-9m6t4H ... "
}
```

**Comment by dakujem** [comment]
BTW: is there any way to analyze network traffic inside Postman (except for network sniffers like wireshark)? The network tab in the devtools shows nothing.

**I have to appologize for this report.**

I tried manually sending the request using cURL and found out that it is actually Apache eating away the header!!

**The solution** was adding
```
# Allow Authorization header to be passed to PHP
CGIPassAuth on
```
to the `.htaccess` file.

Sorry, it did not occur to me that the server might be eating the header.

**Comment by boctulus** [comment]
I've tried [dakujem](https://github.com/dakujem) solution but not working for Windows 11 (my case)

**Comment by Danroyal001** [comment]
@dakujem your solution worked for me too, thanks :-)
