### ISSUE TITLE
AWS Authentication: The request signature we calculated does not match the signature you provided

### ISSUE THREAD

**Issue by vghetau** [a85/POSTMan-Chrome-Extension#5873]
**Bug**
When computing the AWS authentication token, AWS responds with a message along these lines:

```
{"message":"The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.\n\nThe Canonical String for this request should have been\n'POST\n/endpoints/neural-screen/invocations\n\nbucket:a\ncontent-type:multipart/form-data; boundary=--------------------------921743138980933173257080\ncustomer:b\nhost:runtime.sagemaker.us-east-1.amazonaws.com\nsession:d\ntagcode:c\nx-amz-date:20190201T111442Z\n\nbucket;content-type;customer;host;session;tagcode;x-amz-date\na3968e0f66e7ba962b4ddea1896f16b18cd6131dfab56**********'\n\nThe String-to-Sign should have been\n'AWS4-HMAC-SHA256\n20190201T111442Z\n20190201/us-east-1/sagemaker/aws4_request\n31b7051414bda7da1ded34c133eff528e9103****************'\n"}
```

**To Reproduce**
1. Go to Authorization, select AWS Signature
2. Click on Body tab, add a file upload, key='file' value=some file on local machine

It works without this file and by disabling the `Content-type=application/x-www-form-urlencoded` header, but if this header is there and the file attachment is present, it will trigger the error.

**Expected behavior**
I'd expect it would authenticate.

**App information:**
 - App Type Native App
 - Postman Version 6.4.3
 - OS: Ubuntu

**Additional context**
So, the request works when we don't have `Content-Type: application/x-www-form-urlencoded` and the file attachment, but it doesn't work if we include them.

**Comment by codenirvana** [comment]
We've released a fix for this on our Canary (`version: 7.1.0-canary01`) channel https://www.getpostman.com/canary

@vghetau Please try it out in the Canary version and let us know if you continue to face the issue.
Will update the thread once we release the fix on our stable channel.

**Comment by topus** [comment]
I had a comparable issue with postman when sending a POST request for the ‘Action’ with value ‘SendMessage’.
See also https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-making-api-requests.html#structure-post-request

With the canary release ‘PostmanCanary-win64-7.1.0-canary02-Setup.exe’, I now can successful POST a send message on SQS queue. I’m not bother anymore with the signature validation error.

Looking forward for new release, so that I can upgrade my current version 7.0.7

**Comment by codenirvana** [comment]
This has been fixed in the latest Postman app.

**Comment by sanudatta11** [comment]
Faced the issue again today! Get is working fine but post with form-data and adding a File Fails the request with same response

**Comment by mansidoshi** [comment]
Im facing the same issue too. Any solutions?

**Comment by zhaoyi0113** [comment]
I am facing the same issue with the latest version 10.0.42. Any solutions?

**Comment by tohidspeakap** [comment]
same issue here version  12.13.3
