### ISSUE TITLE
Monitoring Blocks shown as Overage Charge in dashboard and Receipt

### ISSUE THREAD

**Issue by chrisdeso** [a85/POSTMan-Chrome-Extension#5875]
**Describe the bug**
Monitoring blocks that are purchased/billed appear as `Overage Charge` in the billing dashboard and in the generated receipt.

**To Reproduce**
1. Purchase monitoring blocks
2. Navigate to billing page – https://go.postman.co/billing
3. See monitoring blocks listed as overages

**Expected behavior**
Monitoring blocks should be billed as `Monitoring Blocks` on receipts and the billing dashboard

**Screenshots**
![image](https://user-images.githubusercontent.com/4734306/52156803-169ae580-2650-11e9-8d3a-468a2988bc3f.png)
![image](https://user-images.githubusercontent.com/4734306/52156832-3e8a4900-2650-11e9-8b0a-816481bb0ff9.png)

**Additional context**
[Filed by Postman]

**Comment by abhijitkane** [comment]
@chrisdeso This should be fixed for charges made from now on.
