### ISSUE TITLE
results in Test Results overlapping each other if doing tests [...] in a loop

### ISSUE THREAD

**Issue by JinJoes** [a85/POSTMan-Chrome-Extension#5876]
Hi, 
I am trying this simple in my test body to eliminating any other issues: (so basically the loop should run 3 times no matter what)

let counter = 3;
for (i=0 ; i < counter; i++)
{
   console.log("input = : " + i);       //this is outputting 3 times which is correct

   tests[" input is < 2"] = i < 2;                 // this will only give me FAIL - seems only gives me the 
                                                                      // output of my last test

   tests[" input: " + i + " is < 2"]   = i < 2;   // this will output 3 times too

}

is it a Postman feature? so I will always have to put a variable in my tests[] to cause it to output in the Test Results tab without overlapping each other??

**Comment by numaanashraf** [comment]
@JinJoes `tests['...'] = ` syntax is deprecated. Please use the recommended `pm.test` method to generate tests like these within a loop. 

Reference: https://learning.getpostman.com/docs/postman/scripts/test_examples/
