### ISSUE TITLE
Wrong name in continue learning - manual testing  - vairables 

### ISSUE THREAD

**Issue by SuzanneBrok** [a85/POSTMan-Chrome-Extension#5881]
1. Go to Learning Center
2. Click on Debugging and manual testing
3. Click on global variables (or Environment variables because the typing mistake is also there).
4. Click on learn
5. Check the message 

Expected result is that there is stated: Variables.
Result is: there is stated vairables

**Comment by prashantagarwal** [comment]
@SuzanneBrok Thanks for catching this. We will get this fixed. Apart from this, we would definitely like to have your feedback about our Learning Center. Was there something that we could have done better or are there any new lessons that you would like to see in future.

**Comment by SuzanneBrok** [comment]
@prashantagarwal There are I am a tester and perfectionist for ;)

The Learning Center is helping me very well. I am just a beginner with postman and following the learning parts of manual and automated testing.
The steps are very clear and helping me to get use of Postman.

**Comment by prashantagarwal** [comment]
@SuzanneBrok We have fixed this.
