### ISSUE TITLE
Add support for XML autocomplete for application/(.*)+xml and application/(.*)+yang media types

### ISSUE THREAD

**Issue by fredrik-jansson-se** [a85/POSTMan-Chrome-Extension#5882]
When Content-Type or Accept equals "application/(.*)+xml" "application/(.*)+yang", syntax highlighting stops working.

1. Create an XML Body
2. Set Content-Type=application/yang-data+xml

XML highlight should still work

**Screenshots**
<img width="947" alt="image" src="https://user-images.githubusercontent.com/2181940/52299554-88b64780-293a-11e9-96fc-5cea5c0ba33e.png">

**App information (please complete the following information):**
 - App Type Native App
 - Postman Version 6.7.3
 - OS: macOS Mojave 10.14.3

**Comment by numaanashraf** [comment]
@fredrik-jansson-se I've modified the title of this issue to better reflect the issue. We do not currently support this and we are tracking this as a feature request.

**Comment by saswatds** [comment]
Hi @fredrik-jansson-se 
Starting app version 7.20 content-type header in the form application/*+xml are now automatically detected as XML language.

Closing this issue now.
