### ISSUE TITLE
Can't Log In with SSO (ADFS)

### ISSUE THREAD

**Issue by Ramya-From-Postman** [a85/POSTMan-Chrome-Extension#5884]
Hi,

After upgrading the app to the latest version, unable to login to the app through SSO via ADFS. It shows the following error.

![image](https://user-images.githubusercontent.com/40994626/52326076-64776b00-2a0d-11e9-85e1-874373360643.png)

App version: 6.7.2
OS: Mac

**Comment by numaanashraf** [comment]
@Ramya-From-Postman Please provide logs (Developer > View Logs) and earlier known version where this has worked.

**Comment by Ramya-From-Postman** [comment]
The issue has been resolved.  Have updated the ADFS certificate since it was expired.
