### ISSUE TITLE
wrong response size displayed 

### ISSUE THREAD

**Issue by experimentalqa** [a85/POSTMan-Chrome-Extension#5885]
1. execute API.  Check the response size displayed 
![image](https://user-images.githubusercontent.com/33400732/52341111-b92fdb80-2a37-11e9-832e-18e05c966b53.png)

2. Download and save the response. Check properties to display it's size 
![image](https://user-images.githubusercontent.com/33400732/52341133-cc42ab80-2a37-11e9-900d-34998e768576.png)

e.g. 
response size displayed on postman : **1.26KB**
response size displayed after saving file locally: **10.2KB** 
There is difference between response size. Looks like decimal value calculations are incorrect

**Comment by shamasis** [comment]
@experimentalqa - can you send me an API that has this exact behaviour? Also, try the same with a larger response size.

This might not be a Postman issue after all. You see, response size is an approximate value and post receiving response the stream may be unpacked (gzip) and then while saving encoding related factors can add more bytes to the file.

**Comment by experimentalqa** [comment]
I observed it while testing client APIs. So will not be able to provide response. 

But you are right, I have observed that, **Accept-Encoding : gzip, deflate, br** in response header 
So i am assuming that after unzip I can observe increased size of response and Postman shows response size before unzip.

**Comment by codenirvana** [comment]
@experimentalqa Response body consists of two parts i.e, HTTP header payload size and response body size(bytes size over the wire). You can check this breakdown on hovering over the response body text. If your receive response with `Content-Encoding`(say gzip) header, this means the response body we show is for the compressed payload.

Note: for now we rely upon the `Content-Length`(if present, else stream size) for this calculation but later we may add support for both compressed and uncompressed body size.
