### ISSUE TITLE
Getting gibberish/non readable fonts while retrieving images through GET API

### ISSUE THREAD

**Issue by Dharmendrabisht** [a85/POSTMan-Chrome-Extension#5886]
**To Reproduce**
1. Try to retrieve an image through GET URL
2. It downloads some gibberish fonts however the response status is 200 OK, which means there is something downloaded. 

**Expected behavior**
It should have the downloaded the requested image 

**Screenshots**
Attached

**App information (please complete the following information):**
 - App Type [ Native App]
 - Postman Version [Postman v6.7.3]
 - OS: [e.g. Windows 7 Pro]

**Additional context**
I am not able to retrieve the actual image instead it downloads some gibberish/non readable fonts( screen shot attached). I looked on internet, someone said its issue with the postman add-on (interceptor) but I am using Postman Native app and I do not see any interceptor option there. 
JFYI, it works fine on browser app (which is being deprecated now), please suggest.

**Comment by Dharmendrabisht** [comment]
Can someone look into this please.

**Comment by shamasis** [comment]
Can you attach a screenshot? Can this API be externally called by us to reproduce this locally? If not, can you send more details as to entire response headers section?

**Comment by a85** [comment]
Not enough data to reproduce.
