### ISSUE TITLE
Environment copied to new Workspace is being written to when using old Workspace

### ISSUE THREAD

**Issue by thetreythomas** [a85/POSTMan-Chrome-Extension#5890]
**Describe the bug**
I have an old Workspace, call it Software v1.0. There are collections and environments in this Workspace. Software v1.0 is now GA. A new Workspace is created for Software v2.0. A few collections along with an environment is copied over to Software v2.0 using the WebUI +Add to workspace.

The environment is copied over to the new workspace successfully. I added some new variables to this environment for testing of v2.0. Needed to then verify something in v1.0, so switched back to that workspace and went to the environment. I noticed all my new variables from v2.0 were now in v1.0. Any changes made in any workspace will effect the environment.

It seems like both Workspaces point to one, the same, instance of this environment.

*This Workspace is a Team Workspace*. I have not tried this yet on a non-team Workspace.

This might be the expected behavior, but I was thinking when adding something to a Workspace from another Workspace, it was copying it, not pointing to the same single object.

**Expected behavior**
For it to be a true copy, and changes made to the environment in that workspace stay in that workspace.

**App information (please complete the following information):**
 - Native App
 - 6.7.3
 - Windows 10

**Comment by numaanashraf** [comment]
@thetreythomas The same environment is available in multiple workspaces when you 'share' them. They are not copied when you share them to another workspace. We'll work on making this behavior more clear. 

/cc @vkaegis @sankalp0o
