### ISSUE TITLE
Monitor run results not visible without a page refresh

### ISSUE THREAD

**Issue by godfrzero** [a85/POSTMan-Chrome-Extension#5892]
## Issue Report:
 1. Did you encounter this recently, or has this bug always been there: Has been there for a while now, I think.
 2. Expected behavior: Run results should be visible after clicking the "Refresh" button

![image](https://user-images.githubusercontent.com/2700229/52387300-a953de00-2aaf-11e9-9564-4eecca46b111.png)

1. Navigate to a monitor
2. Click the "Run" button to start a new run
3. Wait for the run to complete
4. Click the "Refresh" button to load the results
5. Wait and be greeted by emptiness

**Comment by preethammavin** [comment]
This issue is fixed from our end, @godfrzero feel free to reopen it if it reoccurs again
