### ISSUE TITLE
In the /team page on the web dashboard, the search functionality doesn't work for emails/usernames in uppercase

### ISSUE THREAD

**Issue by abhijitkane** [a85/POSTMan-Chrome-Extension#5893]
**To Reproduce**
1. Go to go.postman.co/team
2. Search for an email with uppercase chars (which a member of the team has)
3. No results

**Expected behavior**
Search should:
1. work for uppercase, and
2. be case insensitive

**Comment by ankit-m** [comment]
This has been fixed.
