### ISSUE TITLE
Collection Request order is wrong after importing

### ISSUE THREAD

**Issue by Leo0731** [a85/POSTMan-Chrome-Extension#5895]

**Comment by Leo0731** [comment]
Hi, Dear support team,

When I import the collection I committed to the SVN, then the order of some request is changed immediately. 
I know people asked this issue before, but it is happening and this affects our production regression tests.  The folder issue is always stable, but the requests within a folder keep changing,  Please create at least 10 requests, (2 is not a good test) and see.

As most my tests are like:  GET>POST>GET>PATCH>GET>DELETE>GET;  each request with a different name, but it keeps changing, (I have 1k + requests). This caused so much false negative and frustration, can you please help? 

Running on windows, Postman version 6.7.3

Thanks!!!

**Comment by numaanashraf** [comment]
@Leo0731 would it be possible to share a small sample collection to help us replicate this issue at our end?

**Comment by a85** [comment]
Not enough data to reproduce.
