### ISSUE TITLE
Better handling for redirects on non safe requests

### ISSUE THREAD

**Issue by ddunlop** [a85/POSTMan-Chrome-Extension#5897]
App version: 6.7.3 (6.7.3)

**Is your feature request related to a problem? Please describe.**
Currently with redirects enabled postman redirects a PUT request following the 301 to the new location and turns it into a GET. It would be great if postman warned about this.

I had been making a PUT request over http and the server wanted me to use https, but it took me a while to figure out why all my requests were coming through as GET requests.

**Describe the solution you'd like**
There are two possibilities here:
1. Don't allow non safe methods to follow redirects
2. Pop up a warning prior to following the redirect

**Describe alternatives you've considered**
For my case I switched to using https so that there was no redirect and disabled redirects in the preferences.

**Comment by shamasis** [comment]
Next release will remove all "Authorisation" headers in case the underlying host changes during redirection. There will be in future releases an ability to also turn off this behaviour.

**Comment by vkaegis** [comment]
@ddunlop Thanks for writing in, and apologies for the long delay in getting back. Redirects in general need a better representation in the Postman app, and we have a slew of features planned around tacking this. No ETA just yet, but we'll keep you updated here.

**Comment by Wotuu** [comment]
This issue gave us some headache. We made the protocol configurable (http/https) in our back end and added 301 redirects from http -> https on some environments. This issue caused all our PUT/POST/DELETE requests to turn into GET requests. Solution was to avoid the redirect by explicitly setting the protocol but this bug shouldn't exist in the first place.

**Comment by vkaegis** [comment]
@ddunlop @Wotuu We've recently added the ability to view redirects in the console. This will give you better visibility into which requests are being redirected. We have a few more improvements planned to surface this in the Builder itself, but no ETA on that just yet.

Closing this issue for now, let me know if there are any other issues around this.

**Comment by ddunlop** [comment]
Thanks! I appreciate it!
