### ISSUE TITLE
Collection variables can not be set

### ISSUE THREAD

**Issue by nestorvanz** [a85/POSTMan-Chrome-Extension#5899]
I have the next issue for collection variables:

1. Send request for generate token.
2. Read response from request and save token into `token`. (To be used in other request)
3. Send request using `token` generated in the past request into Authorization header as Bearer {{token}}. (Not working, the value is missing)

```javascript
pm.variables.set("token", pm.response.json().token);
console.log(pm.variables.get("token"));
```
**Note**: In postman console the value is printed, but when is used in other request the value is gone.

**Comment by m3dbedb** [comment]
Collection variables could not be set. You only may define them manually. 

> Defining collection variables
Collection variables can be defined by editing the collection details. Click on the ellipsis (...) next to the collection name, and select “Edit” to open the EDIT COLLECTION modal. Select the Variables tab to add and edit collection variables. You can also define collection variables when creating the collection.

https://learning.getpostman.com/docs/postman/environments_and_globals/variables/
My decision is to use global variables to store temporary data and environment to store fixed values. Also you may define variables as global or environment scope at first test step and clear them at last step.

**Comment by shamasis** [comment]
Editing collection variables from script compromises the source of truth and also results in the confusion as to what to do with the changes once the script is run - that is, do we mutate the collection itself? That is not something that is good to do.
