### ISSUE TITLE
Share a request with team members

### ISSUE THREAD

**Issue by anthonywebb** [a85/POSTMan-Chrome-Extension#59]
Sometimes I have the need to have a team member take a look at a request/response with me.  Currently I have to give him all of the request details to duplicate what I am seeing, would be nice to have some sort of a hyperlink to share my request with him (assuming he is a POSTMan user too)

This could also be accomplished by being able to share or subscribe to a list of collections?

Overall this is about the only thing I can think of that I'd want, you pretty much nailed the rest!  Nice tool!

**Comment by econno11ee** [comment]
Any plans to enable sharing a request as a link?
