### ISSUE TITLE
Monitors: Option to disable / control automatic retry on failures

### ISSUE THREAD

**Issue by Ramya-From-Postman** [a85/POSTMan-Chrome-Extension#5900]
If a monitor which has been running successfully fails for any reason, then the system will re-run it automatically, It would be great if this can be disabled or given an option to choose weather do we need the monitor to retry if it fails for any reason.

**Comment by bt-dd** [comment]
We would also benefit from this, in cases where there is a performance hiccup, we would rather be notified than to hit the (already slower than normal) server again.

Maybe a general "retry up to x times" setting?

This behavior today is not very transparent, and we didn't even realize it was occurring until we dug into console results on some monitors.

**Comment by SMSteve** [comment]
I'd also like to request this feature, and to echo [bt-dd](https://github.com/bt-dd).  We did not see the errors until we dug into our server logs.  Everything looked fine from Postman (until we matched up the times of the server errors with the Postman console logs).

It causes confusion and should be selectable behaviour.

**Comment by ArjunSingh-PM** [comment]
Hi @bt-dd, @SMSteve

We have introduced an option to disable automatic retry on a run failure or to configure the number of times you would like your monitor to automatically retry on a run failure. Thanks for your patience and we hope this helps.

<img width="455" alt="Retry if run fails" src="https://user-images.githubusercontent.com/53265429/80148662-06fc1980-85d3-11ea-9304-ca78712d9b46.png">

Documentation reference: https://learning.postman.com/docs/postman/monitors/setting-up-monitor/#the-basics-when-creating-a-monitor

**Comment by bt-dd** [comment]
Thanks very much @ArjunSingh-PM, this is exactly what we needed!
