### ISSUE TITLE
Enable Wildcard Parameter Use When Creating Mock Example Requests

### ISSUE THREAD

**Issue by dadams89** [a85/POSTMan-Chrome-Extension#5901]
Please read through the [guidelines](https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues) before creating a new issue.

**Is your feature request related to a problem? Please describe.**
Yes, when using the Mock Server to create mock request/responses for a service API, we have created examples for each endpoint, but url parameters must be hard-coded into the example request. In a typical scenario for mocking out an API, there are many different values that can be passed as url parameters that will not match the hard-coded value.

Example:
endpoint = `{{productService}}/product/getdiscountpercentage/:itemNumber/`

If we hard code a value of LAN3016 as itemNumber in our example and submit a request with GAD4041, we will get an error response for no matching request.

**Describe the solution you'd like**
Understanding that this is the current functionality, I believe the ability to use wildcard parameters in example requests would be very helpful, I have included an example below:

![image](https://user-images.githubusercontent.com/37699985/52490084-f0b29b00-2b91-11e9-9553-44ba592a7ae9.png)

**Describe alternatives you've considered**
Another alternative could be a feature allowing "Default" responses to be set per endpoint.

**Comment by fstani** [comment]
So this would be something that would be really good to have

**Comment by kashmadze** [comment]
Must-have feature in Mocking, Please add it 
Currently we have to remove some dynamic parameters from our Rest Requests in case of Mocking, and add them again in case of Live Services.

For that reason developers are complaining because CodeBase gets dirtier .....

**Comment by vvs11** [comment]
Could you check the documentation for wildcard matching in mocks and see if it solves your problem?
https://learning.getpostman.com/docs/postman/mock-servers/matching-algorithm/

Please let us know if you have more queries

**Comment by fabianboerner** [comment]
will such a feature be released soon this is as kashmadze said a must have feature since we cannot just have static data in some cases

**Comment by sony-mathew** [comment]
Hey @dadams89 and @fabianboerner , Our team has been actively working on improving the feature over time, and we've added new capabilities to make it even more powerful and user-friendly. This is now possible with the wildcard matching support that we have on mocks.

More specific example on this is documented here: https://learning.postman.com/docs/designing-and-developing-your-api/mocking-data/matching-algorithm/#using-wildcard-variables

You can read more about creating dynamic responses with mock severs here: https://learning.postman.com/docs/designing-and-developing-your-api/mocking-data/creating-dynamic-responses/

More specific details on how to use use dynamic variables to return randomly generated data is documented here: https://learning.postman.com/docs/tests-and-scripts/write-scripts/variables-list/


Attaching some screenshots on how to achieve this for a sample user object dynamically.

Here is how you configure the request and response object:
<img width="1132" alt="Screenshot 2024-09-01 at 10 26 07 PM" src="https://github.com/user-attachments/assets/99e8b183-943a-4cb9-a660-b9fc86c9a222">

Here is how you hit the mock server url and the response you get. Here after the `user/` you can provide any random id or string and get a valid mocked user response.
<img width="683" alt="Screenshot 2024-09-01 at 10 26 29 PM" src="https://github.com/user-attachments/assets/0c93d710-8a97-4159-8e1e-180ba42f585f">


I believe that our documentation and the new capabilities should help address your concerns and provide a better experience for you. If there's anything else we can do to assist you, please let us know. If you have any further questions or concerns, please feel to reopen this ticket.

**Comment by dja557** [comment]
Awesome, thank you!!

**Comment by fabianboerner** [comment]
> Hey @dadams89 and @fabianboerner , Our team has been actively working on improving the feature over time, and we've added new capabilities to make it even more powerful and user-friendly. This is now possible with the wildcard matching support that we have on mocks.
> 
> More specific example on this is documented here: https://learning.postman.com/docs/designing-and-developing-your-api/mocking-data/matching-algorithm/#using-wildcard-variables
> 
> You can read more about creating dynamic responses with mock severs here: https://learning.postman.com/docs/designing-and-developing-your-api/mocking-data/creating-dynamic-responses/
> 
> More specific details on how to use use dynamic variables to return randomly generated data is documented here: https://learning.postman.com/docs/tests-and-scripts/write-scripts/variables-list/
> 
> Attaching some screenshots on how to achieve this for a sample user object dynamically.
> 
> Here is how you configure the request and response object: <img alt="Screenshot 2024-09-01 at 10 26 07 PM" width="1132" src="https://private-user-images.githubusercontent.com/2040199/363506873-99e8b183-943a-4cb9-a660-b9fc86c9a222.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUyNzc5NjIsIm5iZiI6MTcyNTI3NzY2MiwicGF0aCI6Ii8yMDQwMTk5LzM2MzUwNjg3My05OWU4YjE4My05NDNhLTRjYjktYTY2MC1iOWZjODZjOWEyMjIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MDJUMTE0NzQyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjgwMzdiNzU3ZGQ1YTJiOTkzYTYzNjM2NzVhNDhkNmRmNWEyYjU1NjNjMWIyYmY5MmYwMGQ3M2I4NjFkNDJkYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.bw11PWlNICJzYEsw1xMUqWrfhU-oN2CQnBFXuKRWbKI">
> 
> Here is how you hit the mock server url and the response you get. Here after the `user/` you can provide any random id or string and get a valid mocked user response. <img alt="Screenshot 2024-09-01 at 10 26 29 PM" width="683" src="https://private-user-images.githubusercontent.com/2040199/363506878-0c93d710-8a97-4159-8e1e-180ba42f585f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUyNzc5NjIsIm5iZiI6MTcyNTI3NzY2MiwicGF0aCI6Ii8yMDQwMTk5LzM2MzUwNjg3OC0wYzkzZDcxMC04YTk3LTQxNTktOGUxZS0xODBiYTQyZjU4NWYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MDJUMTE0NzQyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzQ0OWU5NjZhNmZkOGE3ZDgxYzExZDFhODc1NTZlNzZhMzk4N2EzZDRkMzM0YWVkMTYzZjY4NTFhYWY0NjdlMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.klp2EVqlmit8A-zDM12XM8FsmPtoqHG56f8ojRmYP6w">
> 
> I believe that our documentation and the new capabilities should help address your concerns and provide a better experience for you. If there's anything else we can do to assist you, please let us know. If you have any further questions or concerns, please feel to reopen this ticket.

The issue was not the return value but wild card parameters to match an incomming request.
