### ISSUE TITLE
Multipart with utf8 filename is not being transmitted correctly.

### ISSUE THREAD

**Issue by trajano** [a85/POSTMan-Chrome-Extension#5912]
**Describe the bug**

According to the spec https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Disposition specifically `filename*` utf8 encoded filenames has to be sent with the encoding information in the `filename*` field.  In addition. `filename` alone is expected to be in US-ASCII format.

As such I cannot upload a file with non-ASCII characters

**To Reproduce**
1. Create a request with `form-data`
2. Upload a file with a filename that contains non-ASCII e.g. `フェニックス.jpg`
3. Click on *Code* on the upper right
4. The content disposition says

```
Content-Disposition: form-data; name="uploadFile"; filename="D:\dh\resources\フェニックス.jpg
```

Note no path as well just the file name but that's in the *Code* view.  In Fiddler it looks like

```
Content-Disposition: form-data; name="uploadFile"; filename="ãã§ããã¯ã¹.jpg"
```

**Expected behavior**

```
Content-Disposition: form-data; name="uploadFile"; filename*=UTF-8''%E3%83%95%E3%82%A7%E3%83%8B%E3%83%83%E3%82%AF%E3%82%B9.jpg
```

**Comment by codenirvana** [comment]
@trajano Are you facing this issue on sending the request or just in the generated code?

I tried to reproduce this locally using an echo server and its working fine for me.
<img width="768" alt="screenshot 2019-02-21 at 11 36 38 am" src="https://user-images.githubusercontent.com/4865836/53147285-19dd1d80-35cd-11e9-91da-121f08661452.png">

**Comment by trajano** [comment]
The content disposition is still in an improper format because it is sending UTF-8 in the header.   As noted I was expecting the following to come out

```
Content-Disposition: form-data; name="uploadFile"; filename*=UTF-8''%E3%83%95%E3%82%A7%E3%83%8B%E3%83%83%E3%82%AF%E3%82%B9.jpg
```
As that is what is noted in the RFC6266 https://tools.ietf.org/html/rfc6266#section-4.1

**Comment by trajano** [comment]
My workaround for now for RestEasy was to fork MIME4J and make it assume the header contains UTF-8 text.  Jersey has the same issue the work around is more or less the same.  https://github.com/trajano/james-mime4j/pull/1/files

RESTEASY correctly assumes US-ASCII  
Jersey on the other hand incorrectly assumes Latin-1

I don't think you can easily change it as Chrome itself does the UTF8 header.

**Comment by codenirvana** [comment]
@trajano We haven't implemented changes from RFC6266 yet (and I think most web browsers as well).
I understood your problem and we will definitely fix this behavior, no ETA just yet because its a very low-level change in our form-data parsing library.

I hope your workaround solved the problem for now. We might also think of allow configuring the `Content-Disposition` header or just the `filename` for each part in the multipart body.


> Note to self:
Either % URL encode non-ASCII filename or add support for both filename and filename* e.g,
```
Content-Disposition: form-data; name="file"; filename="foo-%c3%a4.html"; filename*=UTF-8''foo-%c3%a4.html
```

**Comment by arlemi** [comment]
@trajano We've added support for filename* in form data as per RFC 6266 in 7.16.0, please let us know if you're still having problems!

**Comment by AmazingCaddy** [comment]
> @trajano We've added support for filename* in form data as per RFC 6266 in 7.16.0, please let us know if you're still having problems!

I also meet this issue recently, and found the discussion under this issue when search answer by Google. now I am using Postman v7.20.0, it seems still have this issue. See below pictures for detail

Is there anything I missed to enable filename* ?

![image](https://user-images.githubusercontent.com/2764744/76634139-d27f5180-6580-11ea-9efb-e3d6837fe172.png)

![image](https://user-images.githubusercontent.com/2764744/76633157-3ef95100-657f-11ea-9733-e68c860a6779.png)

![image](https://user-images.githubusercontent.com/2764744/76633337-85e74680-657f-11ea-89a3-c6793ba4902f.png)

**Comment by coditva** [comment]
@AmazingCaddy this seems to be a problem with the generated code for the request. Can you send the request and see the logs in the Postman Console (raw view)?

**Comment by AmazingCaddy** [comment]
> @AmazingCaddy this seems to be a problem with the generated code for the request. Can you send the request and see the logs in the Postman Console (raw view)?

@coditva Sure, see below picture. so, the raw data shows that the filename* has been enabled. thanks a lot.

but now I still have another issue on the server side, the filename is decoded to some digital gibberish. so I think there is something wrong on my server side.

![image](https://user-images.githubusercontent.com/2764744/76685848-c7e0bd00-6651-11ea-8e7f-7e2429d46662.png)

![image](https://user-images.githubusercontent.com/2764744/76685704-c236a780-6650-11ea-82dd-61fe7e2ead1b.png)

**Comment by trajano** [comment]
@AmazingCaddy you're probably hitting the same problem as I did.  Are you using JAMES or something that relies on it?  I had to patch it https://github.com/postmanlabs/postman-app-support/issues/5912#issuecomment-465876826 because even if Postman does things correctly (which I think it does now) you're still going to hit the issue on the server side.

**Comment by AmazingCaddy** [comment]
@trajano my server side is developed on [eggjs](https://github.com/eggjs), and this framework has a plugin named [egg-multipart](https://github.com/eggjs/egg-multipart) to handle `multipart/form-data` data. I did some test for my server.

* Case 1,  `Content-Disposition: form-data; name="file"; filename="居住证申请人信息.json"`, server prints the filename with correct Chinese characters. 
* Case 2, `Content-Disposition: form-data; name="file"; filename*="UTF-8''%E5%B1%85%E4%BD%8F%E8%AF%81%E7%94%B3%E8%AF%B7%E4%BA%BA%E4%BF%A1%E6%81%AF.json"`, server prints incorrect file name.

below is my guess, I don't verify it.
Based on the testing result, I guess that egg-multipart decodes the stream data with encoding ISO-8859-1. So on the client sider, postman sent the filename with UTF-8 encoded, but on the server side it's decoded with ISO-8859-1, I guess that's why I got the incorrect file name. but in case 1, filename is encoded with ISO-8859-1 on the client side and server side decode the stream with the same encoding.

**Comment by trajano** [comment]
@AmazingCaddy so exactly the same issue as I have on the server side.  Per spec the header data should be sent as US-ASCII or ISO-8859-1.

>    Historically, HTTP has allowed field content with text in the
>   ISO-8859-1 charset [ISO-8859-1], supporting other charsets only
>   through use of [RFC2047] encoding.  In practice, most HTTP header
>   field values use only a subset of the US-ASCII charset [USASCII].
>   Newly defined header fields SHOULD limit their field values to
>   US-ASCII octets.  A recipient SHOULD treat other octets in field
>   content (obs-text) as opaque data.

https://tools.ietf.org/html/rfc7230#section-3.2.4

**Comment by soloturn** [comment]
the relevant spec used in rfc6266 is rfc8187: https://datatracker.ietf.org/doc/html/rfc8187 
```
   Use of characters outside the US-ASCII coded character set
   ([RFC0020]) in HTTP header fields ([RFC7230]) is non-trivial:

   o  The HTTP specification discourages use of non-US-ASCII characters
      in field values, placing them into the "obs-text" Augmented
      Backus-Naur Form (ABNF) production ([RFC7230], Section 3.2).

   o  Furthermore, it stays silent about default character encoding
      schemes for field values, so any use of non-US-ASCII characters
      would need to be specific to the field definition or would require
      some other kind of out-of-band information.

   o  Finally, some APIs assume a default character encoding scheme in
      order to map from the octet sequences (obtained from the HTTP
      message) to character sequences: for instance, the XMLHttpRequest
      API ([XMLHttpRequest]) uses the Interface Definition Language type
      "ByteString", effectively resulting in the ISO-8859-1 character
      encoding scheme ([ISO-8859-1]) being used.

   On the other hand, RFC 2231 defines an encoding mechanism for
   parameters inside MIME header fields ([RFC2231]), which, as opposed
   to HTTP messages, do need to be sent over non-binary transports.
   This document specifies an encoding suitable for use in HTTP header
   fields that is compatible with a simplified profile of the encoding
   defined in RFC 2231.  It can be applied to any HTTP header field that
   uses the common "parameter" ("name=value") syntax.

      Note: This encoding does not apply to message payloads transmitted
      over HTTP, such as when using the media type "multipart/form-data"
      ([RFC7578]).

```

**Comment by baszero** [comment]
So what's the solution to this?
