### ISSUE TITLE
Category "Warning" in test assertions

### ISSUE THREAD

**Issue by Ramya-From-Postman** [a85/POSTMan-Chrome-Extension#5915]
We currently show only Pass or Fail for response assertions. It will be good if we have a category to display the "Warnings" in test assertions. For example: if the response time for some endpoints is more than 200 ms, rather than failing the test, return "Warning" in the response assertion. And the runner then classify and display these warnings only.

**Comment by Jendrasi** [comment]
This is a feature I've been hoping for.

**Comment by shamasis** [comment]
@Ramya-From-Postman Great feature request. But adding another test state would violate the principle of test states for majority of toolchain. The three recognised states that Postman has and so does major toolchain is pass, fail and skipped. Also, tests pass and fail based on assertion being error or not as such configuring a "warning" there would result in a very strange API.

Closing this as wont-fix. However, one solution is to correlate console.log / console.warn that were done from test scripts and show it close to the test results. This is already tracked as part of console improvements.

**Comment by asdf23** [comment]
wont-fix rest-assured
