### ISSUE TITLE
allow_redirects is added twice in example POST request in Postman Echo docs/ POST Raw Text section

### ISSUE THREAD

**Issue by karinakozarova** [a85/POSTMan-Chrome-Extension#5919]
**Describe the bug**
allow_redirects is added twice in example POST request in Postman Echo docs/ POST Raw Text section

**To Reproduce**
1. Go to https://docs.postman-echo.com/, 
2. Scroll to the POST Raw Text section
3. look at the example, the parameter allow_redirects is added twice

**Expected behavior**
`response = requests.request('POST', url, headers = headers, data = payload, allow_redirects=False, timeout=undefined, allow_redirects=false)` should become `response = requests.request('POST', url, headers = headers, data = payload, allow_redirects=False, timeout=undefined)`

**App information (please complete the following information):**
Postman Echo docs hosted at https://docs.postman-echo.com/

**Comment by Cazaimi** [comment]
Beginning investigation.

**Comment by seelaman** [comment]
duplicate of #6152

**Comment by Cazaimi** [comment]
@Raja-Simha , this is solved and can be marked as closed.
