### ISSUE TITLE
UI Color Tagging for items in the Collections folders 

### ISSUE THREAD

**Issue by InfraRedApple** [a85/POSTMan-Chrome-Extension#5922]
It would be nice to have color tags or some sort of color identification for the many items that are in our collections folder. Very similar to the MacOS's tagging system.

[Here is a mock up to show how a system might look.](https://imgur.com/a/BZLeqQk)

**Comment by RuggeriLuca** [comment]
+1 also for folder level

**Comment by a85** [comment]
I am not sure whether we'll be able to implement custom item level theming due to the complexities of rendering across themes or docs. We'll take this up later if time permits.

**Comment by eaglebush** [comment]
For my case, I have been wishing I could mark a certain collection as `Done` or a green dot after a series of tests. A mark down to the request level would also be great.
