### ISSUE TITLE
Slack integration: Success run reported as a failure

### ISSUE THREAD

**Issue by petrheckoHims** [a85/POSTMan-Chrome-Extension#5931]
**Describe the bug**

We have Postman / Slack integrations in place. One is for `Notify on all completed monitor runs` and it's reporting to Slack channel A and second integration for the same monitor, but with the option: `Notify for 3 failures and then first success` and that one is reporting to higher priority Slack channel B. The problem is that even though there are no failures, the Slack channel B receives sometimes messages - the message is not about failure, but it's reporting a successful monitor run. If we then check the monitor run history, there are never any failures. We also have PagerDuty integration for the same monitor, but PagerDuty got never triggered either, so another proof there were no failures, therefore channel B should not receive any messages.  

**To Reproduce**
1. Go to your Postman Slack integration
2. Create new integration for `Monitor Run Results`
3. Authorize Slack and select your channel where to post
4. Choose monitor and in Advanced Options, select `Notify for 3 failures and then first success`

**Expected behavior**
Only if monitor is failing, this integration should be triggered and message to Slack posted (In our case, `#datadog_alerts` channel. The low priority channel, `#postman_monitors` receives all monitor runs as expected. 

**Screenshots**
Current integrations:
![image](https://user-images.githubusercontent.com/42681448/52846077-a312d100-3143-11e9-862e-3840f4379956.png)

Channel which should receive only failures - success messages received at random times:
![image](https://user-images.githubusercontent.com/42681448/52846164-db1a1400-3143-11e9-829d-bb3c51189c5c.png)

Channel receiving all monitor run results:
![image](https://user-images.githubusercontent.com/42681448/52846219-0a308580-3144-11e9-8db5-046fe1e122de.png)

**Additional context**
The `Prod` monitor runs every 5 minutes. The `#postman_monitors` channels is notified every 5 minutes about the results, but the `#datadog_alerts` channel was notified only at randome times. Also, this integration is in place for a couple of weeks, and we never saw the messages in the `#datadog_alerts` channel. It started just today, so we had to remove the integration as it was creating a noise in our high priority channel.

**Comment by chughmayank** [comment]
Hi @petrheckoHims ! 
Could you please confirm if you are still facing this issue?

**Comment by chughmayank** [comment]
Closing this since there is not much traction here. Please feel free to reach out in case you face any issue
Cheers!
