### ISSUE TITLE
Import > Paste Raw Text: Mouse right click for paste is not working (CTRL+V works fine)

### ISSUE THREAD

**Issue by tobenary** [a85/POSTMan-Chrome-Extension#5932]
**Describe the bug**
Import > Paste Raw Text: Mouse right click for paste is not working (CTRL+V works fine)

**To Reproduce**
0. Have a text copied to your clipboard
1. Go to 'Import'
2. Click on 'Paste Raw Text'
3. Mouse right click is not working (for pasting)

**Expected behavior**
Mouse menu with the paste option ( or just pastes the text as putty does.

**App information (please complete the following information):**
 - App Type [ Native App]
 - Postman Version [You are up to date! Postman v6.7.3 is the latest version.]
 - OS: [Win10_64bit]

**Comment by numaanashraf** [comment]
Fixed in Postman v7.0.8
