### ISSUE TITLE
Importing variables to Collection from Environment/Global/File/etc

### ISSUE THREAD

**Issue by ShohruxYusupov** [a85/POSTMan-Chrome-Extension#5934]
For now, it's hard to add variables to collection, cause a user can't migrate all existing variables from evironment to collection.

It would be better to have the "Import" button, like when we add variables to the environment.

(sorry for my english ;))

**Comment by numaanashraf** [comment]
@ShohruxYusupov Thanks for the feedback. You can do this by multi-selecting the variables in the environment screen, copy-ing via the shortcut (Cmd/Ctrl+C) and then pasting onto the collection variables. We are looking into how to make this interaction more discoverable.

**Comment by a85** [comment]
We won't be adding explicit import options here as this is a rare scenario and doesn't require a new feature. We'll continue improving support for copy/paste and other interactions for variables across the app.
