### ISSUE TITLE
Slack notifications are sometimes being sent for consecutive successful runs of a monitor

### ISSUE THREAD

**Issue by abhijitkane** [a85/POSTMan-Chrome-Extension#5935]
Happening occasionally. Notifs should only be sent on:
1. the first 3 failures after a success
2. the first success after 1 or more failures

Slack notifications are sometimes being sent for consecutive successful runs of a monitor (1st AND 2nd success after 1 or more failures)

[Discovered internally at Postman. See JIRA for more]

**Comment by Jeevareesha** [comment]
_redacted personal information_

**Comment by godfrzero** [comment]
We had pushed out a fix for this issue around the 21st. Slack notifications will no longer be sent on consecutive successful runs.

**Comment by Jeevareesha** [comment]
Jeevajee851@gmail.com
