### ISSUE TITLE
Getting an error after launching the Postman 6.5.3 64 bit

### ISSUE THREAD

**Issue by ajayreddy222** [a85/POSTMan-Chrome-Extension#5938]
We have created the Postman 6.5.3 application as thinapp and it worked fine for few days then later when we are launching the application the application launched but it going to black screen within in seconds an showing below error "The instruction at 0x000000000 referenced memory at 0x00000000. The memory could not be written". When clicked on ok the application was closing. Could you let us know why we will get this issue and how to resolve it.

**To Reproduce**
1. Go to 'Start All Program or on the desktop which the entry icon was deployed in the VDI as thinapp'
2. Click on 'Postman.exe'
3. Once clicked the application was launched within few seconds it is going to black screen and showing  error "The instruction at 0x000000000 referenced memory at 0x00000000. The memory could not be written"
4. See error: Please find the attachment

**Expected behavior**
I am thinking due to new version available.

**Screenshots**
Attached the screen shots

**App information (please complete the following information):**
 - App Type : Native App
 - Postman Version: 6.5.3
 - OS: Windows7 64bit
![photo-2019-02-13-11-07-07](https://user-images.githubusercontent.com/47754486/52968569-a45a2d00-33d3-11e9-8e63-2448a0640e9a.jpg)

**Additional context**

**Comment by numaanashraf** [comment]
@ajayreddy222 Thinapp versions are not officially supported yet. We are tracking a feature request for the same at #5975.
