### ISSUE TITLE
Need to Disable pop-up about automatic updates for the 6.5.3

### ISSUE THREAD

**Issue by ajayreddy222** [a85/POSTMan-Chrome-Extension#5939]
**Describe the bug**
I have one more doubt here could you let me know how to stop postman application to update automatically to new version when we installed older Version. Please find the below scenario that I faced the issue:
When I installed the 6.5.3 version it was installed and when it launched and when we go to settings tab the postman application looking for the updates automatically.
Here I need it should look for that automatic updates when go to the settings tab. Could you provide what should need to be done for that.

**To Reproduce**
1. Go to 'Downloads were i have downloaded 6.5.3'
2. Click on 'Postman64bit.exe'
3. Once after installed it was launching fine,but when i got to the settings options it was directly checking for updates.
**Expected behavior**
Here I need it should look for that automatic updates when go to the settings tab. Could you provide what should need to be done for that.

**Screenshots**

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version: 6.5.3
 - OS: Windows7 64 Bit
**Additional context**

**Comment by numaanashraf** [comment]
@ajayreddy222 Postman automatically downloads minor updates and bug fixes and we do not support disabling minor/patch updates. You can disable `Automatically download major updates` in Settings to prevent Postman from automatically updating to a major version.

**Comment by dpease123** [comment]
This is not a great feature. Some people work in corporate environments where they have software to monitor .exe files for familiarity to prevent malicious software from installing.. If the .exe bytes have changed the program is prevented from running b/c it's not recognized or approved  then can't install update. Postman won't launch and your dead in the water until IT approves the file.
