### ISSUE TITLE
In my computer this app is not open even one time. it continuously  showing a black screen.

### ISSUE THREAD

**Issue by SorbAggarwal** [a85/POSTMan-Chrome-Extension#5940]

**Comment by numaanashraf** [comment]
@SorbAggarwal Could you verify whether you are impacted by the related issue #4594 and try the workaround detailed at https://github.com/postmanlabs/postman-app-support/issues/4594#issuecomment-391601621?

**Comment by SorbAggarwal** [comment]
yeah it's the same situation I'm dealing with

**Comment by numaanashraf** [comment]
@SorbAggarwal Did the workaround work for you?

**Comment by SorbAggarwal** [comment]
what are they?

**Comment by SorbAggarwal** [comment]
Okay,
it starts working now when I follow the instruction given by you.

Thanks, man for your support.

**Comment by numaanashraf** [comment]
@SorbAggarwal Glad to hear that. I'm closing this as a duplicate of the related issue.

Duplicate of #4594
