### ISSUE TITLE
Monitors not running 

### ISSUE THREAD

**Issue by ash007-postman** [a85/POSTMan-Chrome-Extension#5941]
We seem to be having a number of issues with monitors not running today. We have a monitor which should be running on a 5-minute interval, but it's clearly not. We've also got a scheduled task to check the last run that forces it to run through the API if it did not run in the last 10 minutes, but even that seems to be having an issue getting it to run. Please check why the collection is not running on the interval that we're expecting.

**Comment by godfrzero** [comment]
This should be fixed now.
