### ISSUE TITLE
How to use console.log() in eval function?

### ISSUE THREAD

**Issue by JFRabbit** [a85/POSTMan-Chrome-Extension#5942]
Postman for Mac
Version 6.7.1
OS X 10.14 / x64

- Pre-request Script:

`console.log("1");`
`function foo () {
    console.log("2");
}`
`foo();`
`pm.globals.set('foo', foo.toString());`

- Tests
`var e = eval;`
`e(pm.globals.get('foo'));`
`console.log(foo());`

Run and Postman Console show error : "ReferenceError | console is not defined".
So how to use console.log() in eval function.

**Comment by codenirvana** [comment]
@JFRabbit Scripts in Postman are executed within Node VM module and that is sandboxed to not have the `console`.  So, required libraries and `eval` don't have direct access to the console.
But, you can still pass the reference of the external `console` as an argument to your eval function to make this work.

Example:
```javascript
// pre-request
console.log("1");
function foo (console) { console.log("2"); }
foo(console);
pm.globals.set('foo', foo.toString());

// test
var e = eval;
e(pm.globals.get('foo'));
console.log(foo(console));
```
