### ISSUE TITLE
Add option to lock request to prevent editing

### ISSUE THREAD

**Issue by muuvmuuv** [a85/POSTMan-Chrome-Extension#5943]
**Is your feature request related to a problem? Please describe.**

Yes. I want to prevent people/employees from editing or accidentally editing a request that should not be edited or just by people who know what they are doing.

**Describe the solution you'd like**

An option on each request to Lock it, so it is not allowed to change anything within that request but sending it. This lock feature would integrate with permission levels so people on a specific permission level are not allowed to lock/unlock a request or maybe just by sending a request to do so.

**Describe alternatives you've considered**

None

**Additional context**

Lock complete folder would also be nice.

**Comment by numaanashraf** [comment]
@muuvmuuv This is currently possible with team workspaces and permissions. Please refer the documentation for more details - https://learning.getpostman.com/docs/postman/collections/sharing_collections/#modifying-team-permissions

**Comment by ranjit-singh-eva-bbsr** [comment]
It's very difficult when you added something that has been edited by someone else and you are just left with no option but to go back. Please give the option to have multi versions on each change or allow it to execute for example.
