### ISSUE TITLE
Unable to delete a workspace

### ISSUE THREAD

**Issue by Ramya-From-Postman** [a85/POSTMan-Chrome-Extension#5944]
Hi, 

There is an issue while deleting a team workspace wherein, the delete button is grayed out. Neither am I able to leave the workspace as it is throwing an error "Something went wrong" Could you help me solve this issue?

![image](https://user-images.githubusercontent.com/40994626/53013462-e3d45800-346b-11e9-955f-7602a186ec89.png)
![image](https://user-images.githubusercontent.com/40994626/53013577-2302a900-346c-11e9-8ead-ce73b0345b53.png)
![image](https://user-images.githubusercontent.com/40994626/53013619-3877d300-346c-11e9-9c4c-d4017172dd61.png)
![image](https://user-images.githubusercontent.com/40994626/53013710-6fe67f80-346c-11e9-8f13-84da70018dca.png)

**Comment by bhargavkaranam** [comment]
@Ramya-From-Postman This seems to be the default team workspace. Default team workspace cannot be deleted. Can you confirm once?

**Comment by numaanashraf** [comment]
Closing this as this is the default team workspace that was renamed. Deleting team workspaces is not supported in Postman 6.x.
