### ISSUE TITLE
Send and Download Hangs on archlinux

### ISSUE THREAD

**Issue by TTcheng** [a85/POSTMan-Chrome-Extension#5945]
**Describe the bug**
I am trying to download a file using the HTTP Get and the Send and Download option on archlinux,then app blocked without any response,the only operation I can doing now is force close postman .The same thing occurs when click Download on response panel.

**To Reproduce**
1. Open postman
2. create a get http request.
3. click Sending and Download button.
4. App blocked

**Expected behavior**
Download a file.

**Screenshots**
![image](https://user-images.githubusercontent.com/19683420/53014201-bd6de700-3482-11e9-9718-401888dfc3f9.png)

**App information (please complete the following information):**
 - App Type [Native App]
 - Postman Version [6.7.3]
 - OS: [Arch rolling]
 - Linux Kernel : [4.20.7]

**Additional context**
I tried several links that response size in KB level,It performs as the same.it seems like that it is unrelated to response size.

**Comment by sujayvenaik** [comment]
Hey @TTcheng 

Could you tell us the size of the response that you are expecting from this endpoint?

**Comment by TTcheng** [comment]
@sujayvenaik I tried several links that response size in KB level,It performs as the same.it seems like that it is unrelated to response size.

**Comment by sujayvenaik** [comment]
@TTcheng Can you help us with a public endpoint where you faced this?
I cannot reproduce this from my end.

**Comment by TTcheng** [comment]
@sujayvenaik I'd like to give you a remote-control on my home laptop via teamviewer. The available period is from 12:00 (UTC) to 15:00 on weekends.If you agree, please contact me at that time.

**Comment by codenirvana** [comment]
@TTcheng Are you still facing this issue in the latest version of the Postman App.
If so, can you please provide more information about the issue you are facing?

**Comment by TTcheng** [comment]
> 
> 
> @TTcheng Are you still facing this issue in the latest version of the Postman App.
> If so, can you please provide more information about the issue you are facing?

I don't known,Im now using manjaro,but this problem doesn't appear on manjaro(Arch-based, Kernel: 5.18，with DDE).
