### ISSUE TITLE
Unable to sync environments using Postman API

### ISSUE THREAD

**Issue by yossarian123** [a85/POSTMan-Chrome-Extension#5947]
Please read through the [guidelines](https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues) before creating a new issue.

**Describe the bug**
My team currently works on their postman collections & environments stored in an Azure DevOps git repo.  The plan is to eventually migrate to a Team Workspace and have everything auto sync but for now I'm currently working on a project to automatically sync the collections stored in the repo with a postman team workspace.

The idea is basically this:

1. grab all collections & environments in git
1. grab all collections & environments in postman workspace (using the Postman GET /workspace API)
1. match collection in git to a collection in the team workspace
1. update collection in the team workspace with git collection
1. Sync environments in the same way (pull from git, sync up via Postman PUT /environment API)

I have steps 1-4 working fine, but environments are not working for some reason. I’m always getting a 400 bad request with the following error body:
```
        "error": {
            "name": "invalidParamsError",
            "message": "The request had invalid parameters",
            "details": {
                "param": "key"
            }
        }
    }
```

Due to corporate policy I can’t send the entire environment JSON over so I've stripped out some more sensitive values, but the data I’m sending to Postman in the PUT request seems to be valid according to the API reference. Has anyone seen this before?

```
{
  "environment": {
"name":"E2E-ENV-Dev0","values":
[
{"key":"testAgency","value":"subsystem","enabled":true},
{"key":"completeFw","value":"amp_sdm660_64_IL01_AMP_R01.00.45","enabled":true},
{"key":"badFw","value":"","enabled":true},
{"key":"incompleteFw","value":"amp_sdm660_64_IL01_AMP_R1.00.24_IL01_AMP_R1.00.00","enabled"
:true},
{"key":"nonExistFw","value":"somefwpackage","enabled":true},
{"key":"postedFw","value":"","enabled":true},
{"key":"testName","value":"10.3-POST-FwRefAgency-BadInputs - Status Code 400","enabled":true},{"key":"version","value":"v1","enabled":true},
{"key":"keyid","value":"0","enabled":true},
{"key":"currentTestAgency","value":"subsystem","enabled":true},
{"key":"deviceName","value":"amp_sdm660_64","enabled":true},
{"key":"azureAgencyFwTable","value":"agencyFirmware","enabled":true},
{"key":"testAgencyName","value":"TestAgency1","enabled":true},
{"key":"deviceName","value":"amp_sdm660_64","enabled":true},
{"key":"newAgencyId","value":"","enabled":true},
{"key":"testAgencyName2","value":"TestAgency2","enabled":true},
{"key":"azureAgencyFwTable","value":"agencyFirmware","enabled":true},
{"key":"flow10AgencyName","value":"subsystem","enabled":true},
{"key":"rmApiTestAgency","value":"subsystem","enabled":true}
]}
```

**To Reproduce**
1. take JSON body with environment variables in it
2. call PUT https://api.getpostman.com/environments/{{currentEnvironmentUid}} with JSON body

**Expected behavior**
Environments would sync.

**Screenshots**

**App information (please complete the following information):**
 - App Type : Native
 - Postman Version [6.7.3]
 - OS: [e.g. macOS 10.14.1]

**Additional context**

**Comment by AzaraPostman** [comment]
it's interesting because when adding the git integrations for each collection there really is no option to synchronize environments with GIT

**Comment by hiqqs** [comment]
+1 also interesting because when adding the git integrations for each collection there really is no option to synchronize environments with GIT

**Comment by a85** [comment]
I am not sure if this is still happening for you?

**Comment by ankitjaggi** [comment]
@yossarian123 This error is returned when you are trying to send duplicate keys in the environment. Based on the JSON you shared, `deviceName` seems to be a duplicate key. Can you try making this call after removing the duplicate one?
