### ISSUE TITLE
No longer receiving daily/weekly monitor summary emails

### ISSUE THREAD

**Issue by VicKetchup** [a85/POSTMan-Chrome-Extension#5952]
**Describe the bug**
Since 11th of Feb our team is no longer receiving daily/weekly monitor summary emails. All the notifications are enabled for each user.

**Expected behavior**
Daily/Weekly summary emails should be send when the monitors are run during that period.

**Screenshots**
<img width="344" alt="postman summary emails" src="https://user-images.githubusercontent.com/43671684/53102390-6ec45980-3523-11e9-8ebe-9ad8ac277fd1.png">
![postman summary nitifications](https://user-images.githubusercontent.com/43671684/53102817-5d2f8180-3524-11e9-9628-92493bd974eb.png)

**App information (please complete the following information):**
 - N/A (Monitors)

**Additional context**
This was first observed on 10th of Feb on my machine, however my colleague has received them so assumed it was an issue with some setting on my account. Starting 11th of Feb neither me or my colleague had any more summaries and both of us have notifications on.

On 11th of Feb we also had an issue with Slack integration no longer working, however that has restored itself on 14th. Commented on this issue during the period: https://github.com/postmanlabs/postman-app-support/issues/5630

Not sure if it is related, however 6 days since that has happened (on the day that slack integration has fixed itself), this issue that aims to prevent emails during the days that monitors are not run was closed: https://github.com/postmanlabs/postman-app-support/issues/5366.

**Comment by godfrzero** [comment]
@VicKetchup Is this still a problem?

**Comment by VicKetchup** [comment]
@godfrzero Yes, still getting empty array back :(

**Comment by godfrzero** [comment]
@VicKetchup Are you still not receiving summary mailers, is what I meant. The Postman API issue is being worked on.

**Comment by VicKetchup** [comment]
@godfrzero Sorry, it's been a long day, thought this was the monitor issue, this is now working fine as far as I can tell :)

**Comment by godfrzero** [comment]
Awesome, closing this ticket then. I'm pushing to get the Postman API issue resolved as fast as we can, I'll update the other ticket when it's out.
