### ISSUE TITLE
SEO meta description for documentation links

### ISSUE THREAD

**Issue by labifrancis** [a85/POSTMan-Chrome-Extension#5953]
**Is your feature request related to a problem? Please describe.**
Users want to edit the meta description for documentation links to render a specific preview.

**Describe the solution you'd like**
Custom fields to add meta description on documentation links

**Additional context**
SEO meta description for links is automatically generated and it will be nice to have control over this description.

**Comment by Raja-Simha** [comment]
@labifrancis, thanks for reporting this.

**Comment by jyeros** [comment]
Using OpenAPI if is added to the schema definition text in `info.description`, it is used as a meta description for the documentation link generated. It works for me.

For example, if add
```
info:
  description: Test description
```
When generate documentation collection and publish it, the link contain
```
<html>
  <head>
    <meta name="description" content="Test description">
```

**Comment by sony-mathew** [comment]
Hey @labifrancis 

We've been continuously improving our documentation to better serve you. Regarding your issue, this is no longer there with the latest versions of the app.

We have introduce a separate section for SEO related tags in the publishing flow. You can read about it here: [SEO](https://learning.postman.com/docs/publishing-your-api/publishing-your-docs/#seo).

We hope this resolves your issue. If you have any further concerns or questions, please feel free to reopen this discussion. We're here to help and support you.
