### ISSUE TITLE
Mac installer v6.7.3 doesn't install on macOS Sierra 10.12.6

### ISSUE THREAD

**Issue by hznut** [a85/POSTMan-Chrome-Extension#5954]
The installation of Mac installer v6.7.3 on macOS Sierra 10.12.6 fails.

**Comment by numaanashraf** [comment]
@hznut Please provide screenshots or logs so that we can triage this further. You can find logs at '~/Library/Application Support/Postman/logs`

**Comment by a85** [comment]
Not enough data to reproduce.
