### ISSUE TITLE
Variable in header is empty

### ISSUE THREAD

**Issue by pupboss** [a85/POSTMan-Chrome-Extension#5957]
**Describe the bug**

Variable in header is empty

**To Reproduce**

1. Set a variable in a collection
2. Use it in request header, send request
3. Open console

<img width="446" alt="screenshot_20190221134701" src="https://user-images.githubusercontent.com/8395112/53146632-ea83dc00-35df-11e9-9ad5-84772028a160.png">

**App information (please complete the following information):**
 - Native App
 - Version 6.7.3
 - Windows 10

**Comment by pupboss** [comment]
Use environment variables instead.

**Comment by numaanashraf** [comment]
@pupboss Postman uses current values to resolve the variable. Please add a current value for this variable.

**Comment by pupboss** [comment]
@numaanashraf Actually I have tried to set a current value...It still did not work, now I refactored the structure of my project to use environment variables, it works fine, thanks sir
