### ISSUE TITLE
Generate Code Snippets for Dart

### ISSUE THREAD

**Issue by robisaks** [a85/POSTMan-Chrome-Extension#5960]
It would be awesome if "Generate Code Snippets" could provide an option for generating Dart code.

**Comment by Aman-Malhotra** [comment]
This would be really really good if we could get snippets of dart code from postman as flutter is being used more and more for app building in the market right now and bcoz of its hybrid nature of building for web, mac, desktop and ios makes it even more demanding in the future. So it would be great if postman generated dart code for api integration in flutter apps.

**Comment by AlexPestre** [comment]
I need this too. Please it will be great full.

**Comment by preetshah21699** [comment]
Yup. It would be awesome.

**Comment by loudsun1997** [comment]
Needed. Now

**Comment by WaleedAlrashed** [comment]
Considering that Flutter now supports IOS/Android + Web (beta) and Desktop Platforms in the future. this added feature would be very helpful to a lot of developers.

**Comment by rafahead** [comment]
Please!!!!

**Comment by goharsahi** [comment]
How many up votes you guys need to go ahead with this feature. desperately need it.

**Comment by TheDevelolper** [comment]
Really need this.

**Comment by Husseinhj** [comment]
https://github.com/postmanlabs/postman-code-generators/pull/401

**Comment by JtheSaw** [comment]
Seems to be fixed now. I am using version 7.36.0 on macOS and it's possible to generate Dart code there 🚀

**Comment by umeshp7** [comment]
Yes! We have support for `Dart` language now. 

<img width="868" alt="Screenshot 2020-12-19 at 6 25 46 PM" src="https://user-images.githubusercontent.com/31915995/102689882-9ff93800-4227-11eb-8973-f101ac7161ef.png">

Open source project for updates/feedback - [here](https://github.com/postmanlabs/postman-code-generators) 

cc. @robisaks @ISimplifyComplexity @goharsahi @rafahead @WaleedAlrashed @loudsun1997 @preetshah21699 @Aman-Malhotra
