### ISSUE TITLE
xml2Json() trim()s XML contents, potentially leading to test failures from spurious mismatches

### ISSUE THREAD

**Issue by jhardin-aptos** [a85/POSTMan-Chrome-Extension#5961]
We're developing a query-driven test environment that feeds expected data into the requests and validation tests via a block of XML data saved in an environment file.

We've just run across an apparent issue in `xml2Json()` where it apparently does a `trim()` of the individual XML data elements before saving them in the JSON structure. This came to light when testing against a freeform user-entered comment field that had trailing spaces - the webservice is returning the correct value (including the trailing spaces), and the backing database query is returning the correct value (the trailing spaces are present in the XML), but the comparison fails with a mismatch, and when the test is instrumented with `console.log(expectedJSONData);` the trailing spaces on that element are gone.

While it's totally valid to ignore whitespace _outside_ a `<tag></tag>` pair that is a leaf node (i.e. it contains a data element rather than further nested structure), any whitespace _within_ a leaf node should not be altered.

**To Reproduce**
1. Define a variable containing some simple XML data that has a trailing whitespace, e.g.:
`<whatever>This is some data with trailing whitespace            </whatever>`
(_note:_ the trailing whitespace in the above example is being collapsed due to HTML semantics, and I don't see any way to suppress that in a code block... there are actually multiple spaces there)
2. Write some javascript to convert that XML collection variable to a javascript JSON variable using `xml2Json()`:
`var testJSON = xml2Json(pm.variables.get("testXML"));`
3. Emit the resulting JSON to the console:
`console.log(testJSON);`
4. The data logged to the console has the trailing spaces removed:
`whatever:  "This is some data with trailing whitespace"`

**Expected behavior**
The JSON data nodes are an accurate representation of the original XML data nodes.

**App information:**
 - Postman 6.7.3 native app on Win 10
 - Newman 4.3.1 CLI

**Comment by codenirvana** [comment]
@jhardin-aptos `xml2Json` is just a [wrapper](https://github.com/postmanlabs/postman-sandbox/blob/4257a2674f09f1fdf6301d87212c841364ded389/lib/sandbox/xml2Json.js) around `xml2js`.

You can configure this by creating your own parser. An example of `xml2Json` with `trim: false`:
```javascript
const xml2js = require('xml2js');

function customXML2JSON(string) {
    var JSON = {},
        options = {
            explicitArray: false,
            async: false,
            trim: false, // true in xml2Json
            mergeAttrs: false
        };

    xml2js.parseString(string, options, function(err, result) {
        JSON = result;
    });

    return JSON;
}
```

Hope this fixes your issue, here's xml2js usage documentation: https://github.com/Leonidas-from-XIV/node-xml2js#usage

**Comment by jhardin-aptos** [comment]
That works great, thank you!
