### ISSUE TITLE
Import curl request via embed button

### ISSUE THREAD

**Issue by ognjenmarcheta** [a85/POSTMan-Chrome-Extension#5962]
Hello to everyone,

Is it possible to create postman embed button to import curl as raw text using embedded button. Like we do for collections but instead of collection url we just pass curl text?

I'm creating tool for web developers and it would be awesome if i could just open postman from web browser and pass him curl so he can import it automatically

postman://app/collections/import/CURL/......

**Comment by numaanashraf** [comment]
@ognjenmarcheta Thanks for the suggestion. This is a great feature request. We'll update here when we take this up.

**Comment by a85** [comment]
@ognjenmarcheta After more discussions here we have decided to not do this as this introduces additional complexities of data serialization while interpolating curl commands into URLs. We recommend using the Postman collection format for embedding and exporting.
