### ISSUE TITLE
Request to add OpsGenie integration with postman

### ISSUE THREAD

**Issue by Ramya-From-Postman** [a85/POSTMan-Chrome-Extension#5963]
It would be great to have an integration available for OpsGenie to trigger monitoring failure notification.

**Comment by dave-pollock** [comment]
This is the only thing preventing us from using Postman Monitoring.

**Comment by clarkritchie** [comment]
Are there any workarounds to this?  Without the ability to specify an API key in a Postman webhook, seems like you'd have to make your own Lambda or something to sit in-between.

**Comment by jotsarup** [comment]
@dave-pollock @clarkritchie @ashish235 @loringelato @timothyclifford @antonik @fsanzdev @viartemev @Holayn @Ramya-From-Postman @arnoutaertgeerts 

We have added Opsgenie integration. Please check it out here https://go.postman.co/integrations/browse?category=all 
Users should now be able to send monitor run failures as alerts to Opsgenie. 
The Opsgenie API key to be used can be created here https://docs.opsgenie.com/docs/api-integration 

Do let us know about any feedback or improvements
