### ISSUE TITLE
Git integration request to commit but not push right away

### ISSUE THREAD

**Issue by hiqqs** [a85/POSTMan-Chrome-Extension#5964]
Basically when using the GIT integration on a tracked collection every little thing you save instantly synch's (commits & push) to source control.  This can make for a mess of commits

It would be really nice if every save could just do commits and then give you the option of when to push along with your own comment so you don't have a bunch of commits in the branch for every little thing

**Comment by shashankawasthi88** [comment]
@johnhiggs this feature is now available with the latest Postman release. Please check out this [blog post](https://blog.postman.com/announcing-new-postman-api-platform/) to know in depth how the Integration works. We would also love to have feedback on the release and see how well we cater to your use cases. Feel free to schedule a call with us using this link - https://calendly.com/shashank-awasthi/api-platform-feedback

**Comment by hiqqs** [comment]
> @johnhiggs this feature is now available with the latest Postman release. Please check out this [blog post](https://blog.postman.com/announcing-new-postman-api-platform/) to know in depth how the Integration works. We would also love to have feedback on the release and see how well we cater to your use cases. Feel free to schedule a call with us using this link - https://calendly.com/shashank-awasthi/api-platform-feedback

thanks!!!!!!!
