### ISSUE TITLE
The ability to reset environment variables from the modal

### ISSUE THREAD

**Issue by djlazz3** [a85/POSTMan-Chrome-Extension#5966]
Please read through the [guidelines](https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues) before creating a new issue.

**Is your feature request related to a problem? Please describe.**
It would be nice to be able to be able to reset the environment from this screen
<img width="622" alt="screen shot 2019-02-22 at 3 59 21 pm" src="https://user-images.githubusercontent.com/7474267/53270971-188a1e80-36bb-11e9-96af-f800f6f4c53a.png">

**Describe the solution you'd like**
Maybe to add a reset button next to the edit button or to add a reset button per variable, or both

**Describe alternatives you've considered**
Technically the alternative is to do it the current way which is pressing the edit button, opening the modal and then resetting it from there

**Additional context**
this is how one currently resets environment variables

<img width="612" alt="screen shot 2019-02-22 at 4 03 08 pm" src="https://user-images.githubusercontent.com/7474267/53271085-5e46e700-36bb-11e9-9b6c-f6818d913beb.png">

**Comment by giridharvc7** [comment]
Environments are now available in a separate window, and you can reset the values in a click. Let us know if this solves your problem @djlazz3 
<img width="1057" alt="Screenshot 2021-04-14 at 1 44 34 PM" src="https://user-images.githubusercontent.com/1040583/114677059-8d9b9080-9d27-11eb-9324-5388b7eed3d9.png">
