### ISSUE TITLE
Postman Freezes 

### ISSUE THREAD

**Issue by gnajerap** [a85/POSTMan-Chrome-Extension#5967]
Please read through the [guidelines](https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues) before creating a new issue.

**Describe the bug**
Postman App for windows Freezes i can´t do anything.

**To Reproduce**
I am using v 6.7.3

**Expected behavior**
When I am trying to use it, it always freezes and is imposible to work.

**Screenshots**

**App information (please complete the following information):**
 - App Type  Native App
 - Postman Version 6.7.3
 - OS: Windows 10

**Comment by numaanashraf** [comment]
@gnajerap Does this happen when you are trying to perform any specific actions?

**Comment by gnajerap** [comment]
In any action. No matter I am trying to do Postman App freezes. I can´t use
it.

**Comment by a85** [comment]
Closing this issue as non-descriptive.
