### ISSUE TITLE
Current Value not set for Variable after entering Initial Value

### ISSUE THREAD

**Issue by nm88** [a85/POSTMan-Chrome-Extension#5970]
**Description**
When creating a variable, if only the Variable name is entered but not an initial value, when I come back later to add the initial value, the Current Value is not automatically populated after clicking Update.
This causes the request to fail as it seems the Current Value is required. If however, I enter the initial value during the creation of the Variable (i.e. immediately after entering the Variable name), the Current Value is automatically populated with the Initial Value.

**Steps**
1. Go to 'Manage Environments' screen
2. Click on 'Add' (or select an existing environment)
3. Enter 'Environment Name' (if adding a new environment)
4. Enter 'Variable Name'
5. Click 'Add' (or 'Update')
6. Click the Environment to access it again
7. Enter the 'Initial Value'
8. Click 'Update'
The 'Current Value' is not automatically updated.
If this variable is now used in a request (e.g. in the endpoint), it would return a 'Could not get response error'

**Expected behavior**
The behaviour (i.e. the population of the Current Value) should ideally be consistent whether the Initial Value is entered during creation of the Variable or modifying the Variable

**Screenshots**
![issue](https://user-images.githubusercontent.com/16080156/53299868-008bd980-3838-11e9-9719-4d2428ad0d02.png)

**App information:**
 - App Type: Native App
 - Postman Version: v6.7.3

**Comment by numaanashraf** [comment]
@nm88 This is intentional. Current values can be empty even when initial values are present and auto populating current value with initial value automatically while updating initial values can lead to unclear and confusing behavior in a collaborate workflow. 

However, we copy initial value to current value while creating a new variable from the UI, to aid new users of this feature and help with common misconfiguration of leaving current value blank - leading to requests failing.

**Comment by nm88** [comment]
Ok, fair point.

**Comment by ibalashov** [comment]
@numaanashraf Somehow the help tooltip suggests that current values ARE taken from initial values if "not touched" (which I read as empty).

![image](https://user-images.githubusercontent.com/2815653/76315899-45b76800-62e2-11ea-88af-89ca28008c00.png)

**Comment by Sygyzmundovych** [comment]
> @numaanashraf Somehow the help tooltip suggests that current values ARE taken from initial values if "not touched" (which I read as empty).
> 
> ![image](https://user-images.githubusercontent.com/2815653/76315899-45b76800-62e2-11ea-88af-89ca28008c00.png)

Same here. It suggests initial value is used when the current is empty. I do not see this happening either.

**Comment by adrian-arg** [comment]
> > @numaanashraf Somehow the help tooltip suggests that current values ARE taken from initial values if "not touched" (which I read as empty).
> > ![image](https://user-images.githubusercontent.com/2815653/76315899-45b76800-62e2-11ea-88af-89ca28008c00.png)
> 
> Same here. It suggests initial value is used when the current is empty. I do not see this happening either.

Same, I spent an hour moving and changing things around, reading the documentation only to find out that when I put it manually in the current value it worked.

![image](https://user-images.githubusercontent.com/32654123/80633417-2067f000-8a2f-11ea-9ed0-ae825b7ba47b.png)

Either the functionality should be changed or make the tooltip text more clear and specific

**Comment by trietbui85** [comment]
@adrian-arg I face this issue too. After reading the tooltip, I think it's okay to just input the initial value and let current value to empty. However, I get 404 when run the request. I must use the "Pre-request" and print the environment variables to console (`console.log(pm.environment);`) and see all these current values is empty.

Postman for Windows v7.23.0

**Comment by thebedroomprogrammer** [comment]
The language is quite misleading. Also, if the current values are not synced to the server then when some other dev has to send the request he/she has to copy the initial value as their current value, which is quite cumbersome

**Comment by astroanu** [comment]
This was working before, was there a change done to remove this recently

**Comment by vlad0337187** [comment]
As I understand we should just specify 2 variables instead of one.
Why not 3 or 4 ?

**Comment by mohammed-atif** [comment]
Current value used to sync perfectly whenever initial value was changed. This feature seems to be broken in past few releases and apparently the devs messed up. So instead of fixing the bug, bug became feature. Slightly disappointed with this.

**Comment by akakani2631** [comment]
It is actually working for me. Make sure your path to get the environment variable is correct depending on tag your json field is under.
For example: Instead of directly using response.id , if your field is under Data section we will need to provide
pm.environment.set(“testid”, response.data.id)

**Comment by jaytavares** [comment]
@numaanashraf Any response to this? See [the tooltip comment above](https://github.com/postmanlabs/postman-app-support/issues/5970#issuecomment-621388197). This is broken functionality.

**Comment by hamzaabbasminhas** [comment]
@numaanashraf The tooltip issue still exists. On leaving my current value empty it does not assume the initial value. This has become very cumbersome for us to manage our variables across teams. Can you please let me know when will this be fixed?

**Comment by giridharvc7** [comment]
@hamzaabbasminhas Do you mind sharing a screen recording of how you assign the initial value? This should automatically assign the current value if the field is left untouched. 
Trying to understand if this is a regression

**Comment by megaromb** [comment]
Guys, please fix the bug. Asking users to duplicate values Isn't user-friendly. Looks like an intended handicap for a free version.
Version: "You are up to date! Postman v9.22.2 is the latest version".
Thank you.

**Comment by wisphill** [comment]
Why it's won't fix :)) absolutely a bug
