### ISSUE TITLE
Add custom authorization

### ISSUE THREAD

**Issue by imclint21** [a85/POSTMan-Chrome-Extension#5971]
Hi,

I think you need to add a custom type for authorization by example discord use a custom token and it's not possible to put it in authorization I need to add an Header

Thanks

**Comment by codenirvana** [comment]
@clintnetwork We have started working towards adding support for a similar authorization method where you can specify the header/query key name and its value.

**Comment by imclint21** [comment]
ha yes okay

**Comment by saswatds** [comment]
Hi @clintnetwork, As part of the latest Postman app we have added support for custom API key authorization that can be used to add custom authorization with headers and query-params
<img width="1128" alt="Screenshot 2019-06-18 at 1 06 42 PM" src="https://user-images.githubusercontent.com/8796447/59662137-f1a3ab00-91c9-11e9-8c33-736c120faaf4.png">

**Comment by imclint21** [comment]
Very nice!
