### ISSUE TITLE
Cancel and take me to signed in account in login window crashes the app sometimes

### ISSUE THREAD

**Issue by SamvelRaja** [a85/POSTMan-Chrome-Extension#5972]
**App version:**  6.7.3
**OS**: MacOS/Windows/(not tested in Linux)

1. Open the app as a signed-out user
2. Click sign-in
3. Sign-in as one user say U1
4. Click add account
5. Now click `Cancel and take me to signed in account` button.

This will crash the app 2/5 times I tried.

**Comment by DannyDainton** [comment]
Closing this issue as it has now been resolved.

Please feel free to reopen with the steps to reproduce if the issue persists.
