### ISSUE TITLE
Multi HTTP Get aggregated into single environment array 

### ISSUE THREAD

**Issue by ronenneumark** [a85/POSTMan-Chrome-Extension#5973]
there is no way to create an environment array which contains an answer from different http get response API call. there is also no way to call multiple get in one call

**Comment by codenirvana** [comment]
@ronenneumark Can you provide more information to understand your use-case?

**Comment by DannyDainton** [comment]
Hey @ronenneumark 

I'm going to close out the issue for now but we can look to reopen this if more details to reproduce the issue are received.
