### ISSUE TITLE
Request to support ThinApp.

### ISSUE THREAD

**Issue by Ramya-From-Postman** [a85/POSTMan-Chrome-Extension#5975]
Upon installing the postman app as a ThinApp, it worked fine for few days then later when we are launching the application the application launched and goes to a black screen within seconds and showing below error, When clicked on ok the application was closing. 

**Error**: **"The instruction at 0x000000000 referenced memory at 0x00000000. The memory could not be written".** 

![image](https://user-images.githubusercontent.com/40994626/53334832-ecbba280-391f-11e9-8b8c-404e3ef165d7.png)

**Comment by a85** [comment]
This does not seem to be officially supported and we don't have any more plans around it.
