### ISSUE TITLE
Activate simple javascript scripting

### ISSUE THREAD

**Issue by deadmann** [a85/POSTMan-Chrome-Extension#5978]
Please read through the [guidelines](https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues) before creating a new issue.
there are many time i receive a very complex nested model that are beyond just a simple regex, i wished i could receive the result in text, and manipulate the data with simple scripting language such as javascript or typescript, even something like lua will suffice, yeah, it's not globally known that's the issue, otherwise, every where there is scripting, lua exists too. well i'm wonder how it should be introduced within an application, but i hope to see scripting with something like js or others within the post man... even sometime generating data become complicated, in those case it would be nice too, to manipulate the inputs in a intermediate coding section.

**Is your feature request related to a problem? Please describe.**
please add scripting section to manipulate the script, and print some data within it's console

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by numaanashraf** [comment]
@deadmann Scripting with JS is already available in Postman - https://learning.getpostman-beta.com/docs/postman/scripts/intro_to_scripts
