### ISSUE TITLE
"Could not get any response" on every request

### ISSUE THREAD

**Issue by mariah123** [a85/POSTMan-Chrome-Extension#5979]
I have just installed Postman and getting "Couldn't get any response" on testing any Api …. I have followed all tutorials and guidelines but em unable to resolve it. I have no proxy setting in my system.

## App Details:
Postman for Windows
Version 6.7.3
win32 10.0.17134 / x64

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there: always
 2. Expected behaviour: get response of the testing Api
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 4. Screenshots (if applicable)

**Comment by numaanashraf** [comment]
@mariah123 Could you please open the Postman Console (View > Show Postman Console), resend the request and send us a screenshot of any errors there?

**Comment by mariah123** [comment]
> @mariah123 Could you please open the Postman Console (View > Show Postman Console), resend the request and send us a screenshot of any errors there?

![postman](https://user-images.githubusercontent.com/11345007/53438540-04665a00-39f8-11e9-99cd-7b0a6508827d.png)

**Comment by mariah123** [comment]
@numaanashraf …. kindly have a look

**Comment by numaanashraf** [comment]
@mariah123 Request seems to have timed out. Please verify request time-out value under Settings > General > Request timeout

**Comment by mariah123** [comment]
its 10

**Comment by numaanashraf** [comment]
@mariah123 That might be why all your requests are timing out. please change that to `0` to set it to infinity.

**Comment by mariah123** [comment]
@numaanashraf Thanks it was resolved!
