### ISSUE TITLE
Postman having issues POSTing large JSON bodies

### ISSUE THREAD

**Issue by ninjavan1sh** [a85/POSTMan-Chrome-Extension#5984]
**Describe the bug**
I seem to run into issues when trying to POST large JSON payloads via postman.  It is an endpoint that allows us to import .csv files.  Files with 200-500 rows run just fine, but when we get to 500k records, Postman seems to have issues

**To Reproduce**
1 - create payload with high character limits

**Expected behavior**
Should send data over with success

**Screenshots**

**App information (please complete the following information):**
 - App Type - Native App
 - Postman Version - latest - 6.7.3
 - OS: win10

**Additional context**

**Comment by numaanashraf** [comment]
@ninjavan1sh We are tracking this at a related issue #4230. Closing this as a duplicate.
