### ISSUE TITLE
Cannot Select a File using multipart/form-data request 

### ISSUE THREAD

**Issue by Sjain01** [a85/POSTMan-Chrome-Extension#5988]
**Bug Description**
When I click on Select File , I expect it to open a window to browse and select a file but nothing happens when I click on this button

**To Reproduce**
1. Try to browse and select a file on form-data

**Expected behavior**
I expect a pop-up to open to browse and select a file

**Screenshots**
![image](https://user-images.githubusercontent.com/28809161/53414469-1bdd1d00-39cf-11e9-8e1d-eec0972c5b5a.png)

**App information (please complete the following information):**
Postman for Windows
Version 6.7.4
win32 10.0.17134 / x64

**Comment by grg-akshay** [comment]
Hey @Sjain01 
We tried reproducing the issue and we were not able to reproduce the issue. 
Can you please provide screenshot of devtools (View -> Developer -> Show Devtools(current view))
Can you please provide logs (View -> Developer -> View logs in Explorer), 
Also is the issue reproducible every time you try to select a file or happens only in particular cases?

**Comment by Sjain01** [comment]
@grg-akshay 

Yes it was occurring every time , to make it work , I removed the parameter and added it again and now it works surprisingly. Since it is working for now , closing this issue.

**Comment by MaslovD** [comment]
same issue started happening today, Version 8.9.1 (8.9.1)
