### ISSUE TITLE
Feature Request, Option to make iteration count be based on the lines of the input CSV

### ISSUE THREAD

**Issue by jpumph** [a85/POSTMan-Chrome-Extension#599]
Rather than manually setting an iteration count, it would be much better if you could chose to make the count be however many lines are in the CSV file (minus the header). Then you could truly automate a flow of dumping data from the DB to a file, then running api calls agains all items returned. As it is, you have to set a value that could be too high or too low if you're scheduling it to run, like with cron.

**Comment by ToshioMagic** [comment]
is this also available for JSON? I don't see it in collection runner.
