### ISSUE TITLE
Postman Desktop App incredible slow when typing request url

### ISSUE THREAD

**Issue by 1-alex98** [a85/POSTMan-Chrome-Extension#5990]
**Describe the bug**
When I type stuff it only shows ages(up to 20 seconds) later. After I delted all my collections and History it worked again. I had 3 Collection with up to 800 entries. (Auto generated from https://api.faforever.com)

**To Reproduce**
Get yourself lots of Colelctions and History.

**Expected behavior**
Smooth typing

**App information (please complete the following information):**
 - Windows 10 64 bit native app

**Comment by pwaterz** [comment]
Same here on linux

**Comment by irfanbaigse** [comment]
same on mac

**Comment by preethamsridhar** [comment]
Same here. Does anybody care to reply here.??

**Comment by numaanashraf** [comment]
@preethamsridhar We are working on a ton of performance improvements at the moment. We'll post updates here once these improvements are available on our early access builds.

**Comment by sudhirkhanger** [comment]
Is there anything in the settings which would improve the performance? I have a whole year's worth of endpoints opened in Postman and maybe loading them is taking up so much time and slowing up the whole app.

**Comment by jeremos** [comment]
I have dramatic performance issues with postman 7.10.0 and canary. A 169ms localhost request is displayed with 6 to 8 seconds delay on a macpro ;( Please... update needed !

**Comment by freddymu** [comment]
> I have dramatic performance issues with postman 7.10.0 and canary. A 169ms localhost request is displayed with 6 to 8 seconds delay on a macpro ;( Please... update needed !

Agreed, very annoying,

**Comment by jeremos** [comment]
up !
Postman is unusable on mac os catalina ! I don't know where the trouble is but when I start a very simple get request on a local virtualbox server, the spin indicator never disapears. I tried the same request with macpaw or curl and all works fine.
I really need the js capabilities and team sharing of postman, do you have a workaround  or a quick fix ?

**Comment by pwaterz** [comment]
@jeremos Your issue is unrelated to this one. Open a new ticket and provide more thorough details please. Also remember this is an open source project, be polite, you are getting the software for free.

**Comment by jeremos** [comment]
yes sorry; i'll do it and I don't want to be unpolite. Postman is a amazing tool and when it freezes, it's like an earthquake in my digital life ;(
For me, Postman is a commercial product with a $576/year cost. It should be cool to have a commercial support also.

**Comment by swastikmu** [comment]
Hi , I read all comments however the issue not yet fixed. it helps me a lot in API testing but it is very slow sometimes. Canary is much more slower than previous ones.

**Comment by surajmrana** [comment]
we are facing dead slow performance issue in postman. Pls rollback the version to 13v. or older. if we download old version then also it automatically update to 14v. Once everything is tested then you can roll out to latest. 

How to stop updating automatically. pls help. @numaanashraf @Postman Team.

**Comment by saswatds** [comment]
@surajmrana Can you provide us with a small screen-recording clip showing the slow behavior. Just to confirm you are experiencing this behavior in app v7.14.0?

**Comment by cloud9tn** [comment]
Same issue here - latest version, win10, shit tons of RAM. Wasnt an issue until I got the latest update. FWIW, I'd have a look at the auto complete code for the url.....

**Comment by noorfathima11** [comment]
Same issue here as well. Dead slow. Was working fine until I updated to the latest version. Had to delete all my collections.

**Comment by linker-err0r** [comment]
I'm experiencing this as well. Reinstalling or updating didn't help. This app used to be pretty dope, but I don't think I'm gonna use it anymore b/c it's gotten progressively more difficult to use over the years.

**Comment by JadinAndrews** [comment]
Postman extremely slow for me as well, please let us know if there is a beta build available or something, it is extremely annoying at work. It's a great tool otherwise

**Comment by th-m** [comment]
Same. I am on a mac.

**Comment by silvertear** [comment]
Me and the other people I work with are also experiencing exceptionally slow performance with the current version of postman (v7.20.1).  Is there a way to use older versions that aren't as slow as the current one?

**Comment by gpeal** [comment]
Same here. It is so slow that I really can't even use it on Catalina.

**Comment by numaanashraf** [comment]
Hey everyone! We've been working on a lot of performance optimisations lately, including responsiveness while typing URLs. We have a patch ready that we believe makes URL typing better for folks with a lot of history and saved collection requests in their workspace and this is available on our early access Canary build now - https://www.postman.com/downloads/canary. It'll help us a lot, if you folks can try this build out and let us know if there is a noticeable improvement, while we work towards making this ready on our stable build.

@axel1200 Thanks a ton for sharing the reference collection. We ran some internal tests with this collection, and URL typing should be much better in Canary build now (and soon in stable too).

cc @gpeal @silvertear @th-m @JadinAndrews @deathgaze @noorfathima11 @cloud9tn @surajmrana @swastikmu @jeremos @pwaterz @freddymu @sudhirkhanger @preethamsridhar @irfanbaigse

**Comment by sudhirkhanger** [comment]
@numaanashraf the canary build is much much faster than the stable build. Thanks for looking into it.

**Comment by cod3r-dev** [comment]
> Hey everyone! We've been working on a lot of performance optimisations lately, including responsiveness while typing URLs. We have a patch ready that we believe makes URL typing better for folks with a lot of history and saved collection requests in their workspace and this is available on our early access Canary build now - https://www.postman.com/downloads/canary. It'll help us a lot, if you folks can try this build out and let us know if there is a noticeable improvement, while we work towards making this ready on our stable build.
> 
> @axel1200 Thanks a ton for sharing the reference collection. We ran some internal tests with this collection, and URL typing should be much better in Canary build now (and soon in stable too).
> 
> cc @gpeal @silvertear @th-m @JadinAndrews @deathgaze @noorfathima11 @cloud9tn @surajmrana @swastikmu @jeremos @pwaterz @freddymu @sudhirkhanger @preethamsridhar @irfanbaigse

Perfect on Macos with last update!!!!  Much faster than ever!!!!!!!!!!!!

**Comment by arlemi** [comment]
This patch is now in the production app as well (from version 7.22)! 🚀

**Comment by linker-err0r** [comment]
Huge improvement! :3 well done!

**Comment by shpeedle** [comment]
postman extremely slow

**Comment by ahmedmagdy11** [comment]
postman is super slow, my idea is to stop pushing new features that consume so much CPU and memory,

**Comment by leidong-xiy** [comment]
Guys, was it due to the `Sync your API requests across devices`?

**Comment by wadeem** [comment]
one day Postman started to lag, especially when typing the url. Seems to get worse. Laptop is quite powerful - Xeon with lots of ram, so probably the issue is within postman doing some heavy stuff or as leidong-xiy assumed, too many synchronizations?
