### ISSUE TITLE
Send a GET request in the default browser

### ISSUE THREAD

**Issue by beatrichartz** [a85/POSTMan-Chrome-Extension#5991]
**Is your feature request related to a problem? Please describe.**
When sending GET requests that need user interaction, there is no way to just open this request in the browser. Preview mode does not support Javascript, so I can't use that either. The current workflow is to send the request with an open console, then copy and paste the url into the browser since it has all values interpolated.

**Describe the solution you'd like**
In the dropdown menu for "Send", have an option to "Send in default browser". This will open the browser with the interpolated URL.

**Comment by a85** [comment]
I am not sure whether an additional option is needed. Why not copy/paste the URL in the browser and hit send?

**Comment by beatrichartz** [comment]
@a85 When the URL contains interpolations / is a GET, there is currently no way to see / copy the constructed URL easily and open it in a browser.
