### ISSUE TITLE
Keep the request name when save as a request to another collection 

### ISSUE THREAD

**Issue by chucklu** [a85/POSTMan-Chrome-Extension#5992]
**Is your feature request related to a problem? Please describe.**  
I save as a request from one collection to another, however the  name of new request was the url instead of  keeping the original request name.

**Describe the solution you'd like**
Keep the original request name as the name of new request

**Comment by numaanashraf** [comment]
This is available from Postman v7.2.0 onwards.

**Comment by chucklu** [comment]
@numaanashraf  Thanks a lot.
