### ISSUE TITLE
Cannot select multiple files per field in form-data body

### ISSUE THREAD

**Issue by khanhtd36** [a85/POSTMan-Chrome-Extension#5995]
```
Postman for Windows
Version 6.7.4
Windows 10 1803 / x64
```

## Issue Report:
 1. Issue occurs after update postman to version 6.7.4
 2. Expected behaviour: choose multiple files per field in form-data body
 4. Screenshots
- before update, I can choose multiple files per field in form-data body:
https://1drv.ms/u/s!Ame6j3sAT4939CXsPPuwNUMdMtqq

- after update, I can choose only one file per field:
https://1drv.ms/u/s!Ame6j3sAT4939CZAYC4ZDfGBqyJe

**Comment by NicolaPicoli** [comment]
having same here...

**Comment by alkasingla94** [comment]
Facing same issue

**Comment by macynbaker** [comment]
I got around this by titling multiple keys "files". Our POST endpoint accepts a RequestPart in the form of a List of MultipartFiles. The POST was accepted without issue. 

![image](https://user-images.githubusercontent.com/47578240/53776408-f5821a80-3ec3-11e9-9353-f0939ffa1d26.png)

**Comment by khanhtd36** [comment]
Bug fixed on new update.

**Comment by lucianozablocki** [comment]
still can't do it on 9.15.2 linux x64 version. had to do it by sending multiple keys as above answer suggested
