### ISSUE TITLE
Update on macOS fails due to permission access denied

### ISSUE THREAD

**Issue by MonkeyTonk** [a85/POSTMan-Chrome-Extension#5998]
**Describe the bug**
Cannot update postman via postman app.

**To Reproduce**
1. Go to my machine
2. Open Postman.app
3. Hit shortcut Alt+Cmd+I to show DevTools and switch back to Postman
4. Click on the wrench after the red dot appears on it
5. Click on 'Update failed, view details'
6. In the following dialog click 'Retry update'
7. In the following dialog see changelog for 6.7.4 and 6.7.3
8. Click on 'Update'
9. See following dialog titled 'UPDATE FAILED' with message 'Something went wrong [...]'
10. Switch to DevTools
11. See error in console
`vendor-shared.js:125255 Error in update flow: {"code":13,"domain":"NSPOSIXErrorDomain","message":"Could not create temporary directory: Zugriff verweigert","name":"Error","stack":"Error: Could not create temporary directory: Zugriff verweigert"}`

**Expected behavior**
It should update Postman automatically without error.

**Screenshots**
_none_

**App information (please complete the following information):**
 - Native macos app
 - Postman Version v6.7.2
 - OS: macOS Mojave 10.14.3

**Additional context**
I am aware that there has to be an permission issue. As stated in the [FAQ article](https://support.getpostman.com/hc/en-us/articles/115005903329-I-m-not-able-to-update-my-Mac-app-) I moved Postman.app bundle to my `~/Applications/` but this didn't help. Even not with the information found in the github issue that were noted there.
I tried to figure out what folder postman wants to create or where but with no luck. That would've helped me getting deeper into the reason of this error.

**Comment by numaanashraf** [comment]
@MonkeyTonk This seems to be related to `com.apple.quarantine` being set recursively and Gatekeeper masking the absolute paths. Please try the following steps and let us know if the issue persists.

```
sudo chown -R $USER ~/Library/Caches/com.postmanlabs.mac.ShipIt
xattr -dr com.apple.quarantine /Applications/Postman.app
```

Reference: https://github.com/Microsoft/vscode/issues/7426#issuecomment-277737150
