### ISSUE TITLE
Additional "WebKitFormBoundary" shown in request body of HTTP code snippet

### ISSUE THREAD

**Issue by mearns** [a85/POSTMan-Chrome-Extension#5999]
**Describe the bug**
When I have a request with a request body, click the "Code" button to get a code snippet of the request, and choose "HTTP" as the format from the drop down, it generates an HTTP request with extra text added to the end of the request body, beginning with "------WebKitFormBoundary".

This only seems to happen for "raw" and "form-data" body types.

**To Reproduce**
1. Create a request to any URL, with any HTTP method (have verified with GET, POST, PUT, DELETE, HEAD, COPY, and OPTIONS)
2. Click on the "Body" tab to configure the request body.
3. Choose either the "form-data" or "raw" radio button from the top of the Body tab. (For "raw" bodies, the type doesn't seem to matter; I have verified with "Text" and "JSON (application/json)").
4. Enter any thing for the contents of the request body.
5. Click on the "Code" button in the upper right corner of the request panel.
6. In the "GENERATE CODE SNIPPETS" modal dialog, choose "HTTP" from the dropdown menu in the upper left corner.

**Expected behavior**
Expected the request body to only include the data specified in the request, e.g:

```
GET /any/path HTTP/1.1
Host: example.com
Content-Type: application/json
cache-control: no-cache
Postman-Token: f7a52796-32a8-4a0c-8c51-d0e19db0b754
Any request body.
```

**Actual behavior**
Go the following HTTP request snippet (note the "-----WebKit[...]" at the end of the request):
```
GET /any/path HTTP/1.1
Host: example.com
Content-Type: application/json
cache-control: no-cache
Postman-Token: f7a52796-32a8-4a0c-8c51-d0e19db0b754
Any request body.------WebKitFormBoundary7MA4YWxkTrZu0gW--
```

**Screenshots**

An example request configuration:
<img width="614" alt="request-configuration" src="https://user-images.githubusercontent.com/5140254/53582220-11489200-3b4d-11e9-9173-e2780a98f9b2.png">

Which incorrectly generates the following HTTP code snippet (incorrect additions to request body highlighted):
<img width="711" alt="incorrectly-generated-http-code-snippet" src="https://user-images.githubusercontent.com/5140254/53582289-2c1b0680-3b4d-11e9-93fc-0ccdb1e6aed4.png">

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version: 6.7.3
 - OS: macOS High Sierra 10.13.6

**Additional context**
A similar issue #5467 seems to have incorrectly identified this as the reason requests were failing, but this appeared to be a red herring for another issue they were having with an authenticated proxy. That issue was closed as a result, so I've created this in its place. This does NOT appear to affect the behavior of postman in actually issuing the request, only the HTTP code snippet.

**Comment by abhijitkane** [comment]
@mearns I'm unable to reproduce this with version 7.0.9 (screenshot attached). Can you confirm?

<img width="757" alt="Screen Shot 2019-04-29 at 15 53 11" src="https://user-images.githubusercontent.com/681190/56890401-f637c700-6a96-11e9-9a4b-40c604251a75.png">

**Comment by mearns** [comment]
Confirmed @abhijitkane, I cannot reproduce in 7.0.9 either.
