### ISSUE TITLE
Keyboard shortcuts

### ISSUE THREAD

**Issue by a85** [a85/POSTMan-Chrome-Extension#6]
- Send request
- New request
- Clear history
- Show history tab
- Show collection tab
- Maximize/minimize response
- Edit request URL params

**Comment by blowsie** [comment]
- edit globals

**Comment by carlospliego** [comment]
From what I understand there is no postman documentation explaining this.

**Comment by sdnts** [comment]
@carlospliego You can check out available shortcuts from the App's settings (Wrench icon on the right > Settings > Shortcuts tab)
