### ISSUE TITLE
Add option to give a download link for the response instead of displaying it

### ISSUE THREAD

**Issue by ryanhaugh** [a85/POSTMan-Chrome-Extension#60]
I have a service that generates PDFs on the fly and returns them as the response.  Since these files are binary, displaying the result in the Body tab doesn't make sense.  Also, these files can be quite large so it slows down the page as it is being loaded onto the page.

**Comment by Brisboy** [comment]
Any idea how do i view the pdfs if i executed the testcases using the runner.

**Comment by sdnts** [comment]
@Brisboy Currently, there isn't a way to view your PDFs from within the runner. I'll go ahead and add this as a feature request though.

**Comment by jakobmillah** [comment]
Any plans for adding download option for images as well?

**Comment by baba216** [comment]
What about this feature:

`how about endoints that deliver other binary files such as .zip?`

when I tried I am getting something as rather the download link:
PK�����I������������(���72b94c01-6b6b-434
