### ISSUE TITLE
Curl: the code snipped generated by Postman does not work as expected

### ISSUE THREAD

**Issue by hugochibougamau** [a85/POSTMan-Chrome-Extension#6000]
**Description**
Testing a simple application. The developer provided a curl command example and the expected response. However, when using Postman, the response that I get from the API is different. The curl code snippet generated by Postman is different from the curl request provided by the developer.

**To Reproduce**
Testing the simple application located at https://github.com/crochcunill/consultants-api

- After installing, issuing the following Curl command
`curl -X POST -H "Content-Type: application/json" -d '{ "consultantCode": "AQWERTY", "firstName": "Asdf", "lastName": "Qwerty" }' 'http://localhost:8080/api/consultants'`

returns 
`{"consultantCode":"AQWERTY","firstName":"Asdf","lastName":"Qwerty","id":"44"}`

as indicated in the documentation.

- Using Postman, build a POST request with no pre-request scripts, no Authorization. The Parameters are:

![image](https://user-images.githubusercontent.com/46409451/53594185-29b9ac00-3b4f-11e9-9ffb-e599deccf45c.png)
(Note: {BaseURL} translates to localhost:8080)

and the Header is 

![image](https://user-images.githubusercontent.com/46409451/53594402-a6e52100-3b4f-11e9-9fde-2827a532264e.png)

it returns

![image](https://user-images.githubusercontent.com/46409451/53594233-4655e400-3b4f-11e9-87f8-00c67795d3b3.png)

- Generating the curl code snipped (using the 'Code' button in the Postman interface) I get back the following snippet

`curl -X POST \
  'http://localhost:8080/api/consultants?consultantCode=CC22&firstName=FN22&lastName=LN22' \
  -H 'Content-Type: application/json' \
  -H 'Postman-Token: e0f47155-11f4-4223-a593-7d1086b45e3a' \
  -H 'cache-control: no-cache'`

executing the snipped returns, as expected,  the same information as using the Postman interface

`{"id":"2s"}`

**Expected behavior**
I would expect the curl command generated by Postman would be identical to the one suggested by the developer or at least would return the same results

**App information (please complete the following information):**
 - curl 7.54.0 (x86_64-apple-darwin18.0) libcurl/7.54.0 LibreSSL/2.6.4 zlib/1.2.11 nghttp2/1.24.1
 - Postman Version 6.7.3
 - macOS Mojave 10.14.3

**Comment by shreys7** [comment]
Hey @hugochibougamau , according to the Curl command they provided, it seems that the data should be added in body->raw->application/json, not in the parameters as you did. After entering the data in body->raw->application/json , the code generated by Curl in postman matches with the command they provided.
<img width="963" alt="Screenshot 2019-04-02 at 4 26 06 PM" src="https://user-images.githubusercontent.com/20665864/55397579-2eb1b700-5564-11e9-8e9a-54b78ebe1a2c.png">
<img width="718" alt="Screenshot 2019-04-02 at 4 26 29 PM" src="https://user-images.githubusercontent.com/20665864/55397794-a1bb2d80-5564-11e9-8d5f-5b33d142a684.png">
