### ISSUE TITLE
Can't delete Monitor: "Something went wrong"

### ISSUE THREAD

**Issue by JP-from-Postman** [a85/POSTMan-Chrome-Extension#6002]
[Reported by Postman Support, on behalf of user]

**Describe the bug**
When attempting to delete a monitor from the web dashboard (or app), the following error is displayed:
<img width="470" alt="screen shot 2019-02-28 at 3 08 50 pm" src="https://user-images.githubusercontent.com/43283131/53604965-dfdebf00-3b6a-11e9-9c7b-034483549bff.png">
The Monitor and Collection both exist in the same Workspace.

**To Reproduce**
Unknown

**Expected behavior**
Monitor is deleted

**App information (please complete the following information):**
 - App Type: Native App, Web Dashboard
 - Postman Version: 6.7.3
 - OS: Windows (app), Chrome for Windows

**Comment by Satak** [comment]
Have the same problem. ```Something went wrong
The requested monitors could not be found on the Monitoring Service.```

When trying to edit the monitor: ```Something went wrong
An error has occurred on the server.```

**Comment by godfrzero** [comment]
@Satak Are you still unable to edit the monitor? If so, could you let me know if you've upgraded to Postman v7 yet?

**Comment by Satak** [comment]
@godfrzero I still can't edit or delete the monitor. For monitoring I'm using Postman SaaS so I don't know what version they are running. My Postman client says: `You are up to date! Postman v6.7.4 is the latest version.`

**Comment by Satak** [comment]
We are also going over our request quota because of this monitor and we are forced to pay more and I can't edit the monitor. So because of Postman's bug we have to pay more. This is becoming a legal issue now... Is there a way to handle this in private via email or phone? We need to find a solution to this ASAP.

**Comment by godfrzero** [comment]
@Satak Please email us at help@getpostman.com with the ID(s) of the monitor and we'll get this sorted.

**Comment by Satak** [comment]
Thanks. I just tried to delete my monitor once again and now it deleted it.

**Comment by godfrzero** [comment]
We've pushed out a fix for this and monitor deletes should now be functioning as expected for everyone.
