### ISSUE TITLE
Prompt on escape key-press in Collection/Folder edit pop-up

### ISSUE THREAD

**Issue by jooleeanh** [a85/POSTMan-Chrome-Extension#6004]
This is an extension of [#3998](https://github.com/postmanlabs/postman-app-support/issues/3998).
Part of the issue was resolved (escape key dismisses the autocompletion dialog), but the rest wasn't treated:  

# App details
Postman for Mac
Mac: 10.14.3 (18D109)
Postman: Version 6.7.4 (6.7.4)

# Feature request

**Is your feature request related to a problem? Please describe.**
If there are modifications in the Collection pop-up (description, pre-request scripts, tests), and we press escape, the pop-up closes without prompt, thus losing all changes.

**Describe the solution you'd like**
I would like that:
- If there are NO modifications, ESC closes the pop-up
- If there ARE modifications in any of the tabs with a TextArea field, and the escape key is pressed, it opens a prompt (`cancel`, `save`)
  - Pressing enter on the prompt will save
  - Pressing escape on the prompt will close the prompt and return to the pop-up with the modifications still present
  - Pressing tab on the prompt move the focus between `cancel` and `save`

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by sorenhansen-dk** [comment]
#810 is about the same issue.

**Comment by vkaegis** [comment]
@jooleeanh This should be fixed in Version 7.13.0. Closing this issue for now, feel free to open another if you have any feedback on this.
