### ISSUE TITLE
History deletion takes too much time

### ISSUE THREAD

**Issue by m3dbedb** [a85/POSTMan-Chrome-Extension#6005]
**bug description **
trashbox button for day history and "clear all" commands react like they does not work

**To Reproduce**
1. Make several requests
2. Click on trashbox button for day history or "clear all" history
3. It looks like the commands does not work, but in several seconds history bacame empty

**Expected behavior**
It would be good if the buttons to bacame gray during deletion to show it is executing command

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version 6.7.4
 - OS: windows 7 32

**Comment by mccannt** [comment]
@m3dbedb We have made improvements to the application since the time this was logged.
Can you confirm that this is still an issue for you on the most recent version of the application?

**Comment by m3dbedb** [comment]
Yes now it works good!

**Comment by sseenivasan89** [comment]
Hi @m3dbedb

I still could see there is an issue with clearing all history, it take while to clear all the history even though it has very few
