### ISSUE TITLE
Get path variable value in the pre-request script

### ISSUE THREAD

**Issue by skechboy** [a85/POSTMan-Chrome-Extension#6006]
Let's assume that we have a path variable :call that is predefined from the postman interface, how can we get it's value in pre-request script?

![path_variables](https://user-images.githubusercontent.com/399599/53656677-4986c800-3c54-11e9-91ba-b705bc2c5e3d.PNG)

**Comment by codenirvana** [comment]
@skechboy Here you go
```javascript
pm.request.url.variables.get('call');
```
