### ISSUE TITLE
Postman does not pass a variable to cheerio expression

### ISSUE THREAD

**Issue by m3dbedb** [a85/POSTMan-Chrome-Extension#6011]
**Bug description**
I need to find a string on a page, but postman does not get parameter, provided as variable

**To Reproduce**
1. Execute the test code
```
const a = cheerio.load("<h2>Processed applications</h2><table><tbody>    <tr> <th>№</th> <th>date</th> <th>post code</th> <th>name</th> <th>phone</th> <th>adress</th> <th>MAC</th>    </tr> <tr> <td>1</td> <td>03.03.2019</td> <td>832222</td> <td>Evgeniya</td> <td>+7(000) 000-0000</td> <td>Salehard, ulitsa Lenina, dom 3</td> <td>01:01:02:03:04:15</td>    </tr>    <tr> <td>2</td>\n\t\t <td>03.03.2019</td> <td>432222</td> <td>Aleksander</td> <td>+7777) 777-7777</td> <td>Samara, prospekt Mira, dom 21</td> <td>01:01:02:03:04:16</td>    </tr>    </tbody></table>");
var b='01:01:02:03:04:16';
tests["Application "+b+" processed"] = a('td:contains(b)').html() !== null;
```
4. Postman does not pass variable content to cheerio expression. Test fails with "Application 01:01:02:03:04:16 processed | AssertionError: expected false to be truthy"

**Expected behavior**
If I execute this way 
tests["Application "+b+" processed"] = a('td:contains("01:01:02:03:04:16")').html() !== null; Test gives success

**App information:**
 - App Type: Native
 - Postman Version 6.7.4
 - OS: Windows 7 32 bit

**Comment by vikiCoder** [comment]
Hi @m3dbedb,

You can use JavaScript [template literal](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals) as shown below to get the desired result.

```
tests["Application "+b+" processed"] = a(`td:contains(${b})`).html() !== null;
```

**Comment by m3dbedb** [comment]
also works `tests["Application "+b+" processed"] = a(`td:contains(${pm.globals.get("b")})`).html() !== null;`

**Comment by m3dbedb** [comment]
Note that newman 4.3.1 does not support template literal, use 4.4.0 and newer versions.
