### ISSUE TITLE
Unable to execute string as a function

### ISSUE THREAD

**Issue by m3dbedb** [a85/POSTMan-Chrome-Extension#6012]
**Bug description**
Postman can't execute code stored in variable as a function

**To Reproduce**
1. Run string as a functions
```
var s="console.log('nihao');";
var F=new Function (s);
return(F());
```
2. ReferenceError | console is not defined

**Expected behavior**
Run string as a function to work as a string inside eval operator
```
var s="console.log('privet');";
eval(s);
```
**App information:**
 - App Type: Native
 - Postman Version: 6.7.4
 - OS: Windows 7 32 bit

**Comment by m3dbedb** [comment]
It was a typo, it works!
```
var s="console.log('fgh')";
eval(s);
```

**Comment by codenirvana** [comment]
Duplicate of #5942

@m3dbedb As mentioned in https://github.com/postmanlabs/postman-app-support/issues/5942#issuecomment-466961626, you have to pass the reference of the external console as an argument.

Example:
```javascript
var s = "console.log('nihao');";
var f = new Function('console', s);

f(console);
```
