### ISSUE TITLE
Synchronize Github repo into APIMatic

### ISSUE THREAD

**Issue by labifrancis** [a85/POSTMan-Chrome-Extension#6014]
**Is your feature request related to a problem? Please describe.**
APIMatic syncs into Github repo using integrations but a user wants to have it the other way round 

**Describe the solution you'd like**
A user should be able to have a Github repo sync into APIMatic. For instance, APIs are documented by developers into swagger and being pushed into a GitHub repo. The Github repo should serve as the Master.

**Comment by a85** [comment]
I am not sure what Postman would be doing here - this is something that Github and APIMatic can support independently of Postman.
