### ISSUE TITLE
Request to enable static IP region for the monitors in the native app.

### ISSUE THREAD

**Issue by Ramya-From-Postman** [a85/POSTMan-Chrome-Extension#6016]
Currently, the static IP region for the enterprise team won't show-up while creating a monitor via the app. 
![image](https://user-images.githubusercontent.com/40994626/53791578-c74a1c80-3f4f-11e9-8dd7-2cfd6af75859.png)

However, the static IP region is available on the web dashboard. It would be great if this option is made available on the app well.

![image](https://user-images.githubusercontent.com/40994626/53791787-3c1d5680-3f50-11e9-8182-45596253d98a.png)

**Comment by ArjunSingh-PM** [comment]
This issue is resolved. Static IP regions are visible via the app.
