### ISSUE TITLE
How to get elements of an array in postman

### ISSUE THREAD

**Issue by tonycantony0007** [a85/POSTMan-Chrome-Extension#6020]
I have 2 request .The output of 1st request is a string of the form ["abc","afgy","sfgh","dfg"].I Need to iterate the 2nd request with these values as input to the request. Thanks in advance.

## App Details:

```
Postman for Mac
Version 4.11.0
OS X 16.4.0 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:
 2. Expected behaviour:
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 4. Screenshots (if applicable)

**Comment by numaanashraf** [comment]
We recommend reaching out to the wider Postman Community (https://community.getpostman.com/) for help with this issue.

Issue Guidelines: https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues
