### ISSUE TITLE
Postman strips everything following a hash symbol from query parameters

### ISSUE THREAD

**Issue by coccoinomane** [a85/POSTMan-Chrome-Extension#6023]
**Describe the bug**
Whenever I hit "Save" in a request, Postman strips from query parameters everything following a hash symbol (#) including the symbol itself.

**To Reproduce**
Create a new request, write in the data editor a query parameter with a hash symbol followed by some text, and then click on "Save".

**Expected behavior**
Postman should not strip the hash symbol from the query string when clicking on "Save".
Either that, or it should url-encode `#` to `%23` when clicking "Save".
If this is not possible, an alert would be useful to avoid losing the text that was typed in the data editor.

**Screenshots**
GIF => http://link.idearia.it/hB82mZ

**App information (please complete the following information):**
 - App Type Native
 - Postman Version v6.7.4
 - OS: macOS Mojave 10.14.3

**Comment by cec** [comment]
Hi, are there any updates on this? I have # in JSON strings that I'm sending as query params and this bug is preventing me from using Postman collections for this

**Comment by paunovic** [comment]
Hey guys, are there any updates on this? I'm trying to send hashtag as a query value and this bug is preventing me to do so.

**Comment by CreepyGnome** [comment]
This is still an issue in the latest version of Postman.

**Comment by raphaelmsr** [comment]
Hi all, this is a very concerning issue .. Please communicate on this, I can't use body for the request

**Comment by cec** [comment]
@raphaelmsr use `%23` in place of `#`

It sucks, but it's a workaround

**Comment by kevinswiber** [comment]
Hi there.

Postman doesn't automatically URI-encode values in Params.  You can highlight what you want to encode, right-click, and select `EncodeURIComponent` to do this manually.  Reference: https://learning.postman.com/docs/postman/sending-api-requests/requests/#sending-parameters

![image](https://user-images.githubusercontent.com/78582/74978186-f10a8680-53e0-11ea-8365-795c35194b82.png)


Additional Background:

[URI Syntax][rfc-2396] and HTTP implementations treat anything after a crosshatch (`#`) as a fragment identifier intended only for the User-Agent, so anything after the crosshatch won't actually make its way to the server.  If the `#` character isn't intended as a URI fragment identifier, it *must* be URI-encoded (`%23`).

[rfc-2396]: https://learning.postman.com/docs/postman/sending-api-requests/requests/#sending-parameters

**Comment by vikiCoder** [comment]
Hi, this is fixed in the latest [Postman Canary](https://www.postman.com/downloads/canary) release (version 7.20.0-canary03). You can see more details about the fix at #8154

**Comment by codenirvana** [comment]
As mentioned in https://github.com/postmanlabs/postman-app-support/issues/6023#issuecomment-589308322, you can either manually encode the `#` if entered directly in the URL bar or Postman will automatically encode the `#` and `&` characters if entered in the query param editor (key-value editor) as they come in the way of query param parsing.

Check https://github.com/postmanlabs/postman-app-support/issues/8106#issuecomment-597244210 for more details.
