### ISSUE TITLE
Path variables not working any more

### ISSUE THREAD

**Issue by hstaugaard** [a85/POSTMan-Chrome-Extension#603]
In my current version (0.9.9.7 (packaged)) path variables (colon prefixed) are not working any more. Input fields not showing:

![image](https://cloud.githubusercontent.com/assets/863764/3228198/71593af0-f084-11e3-9012-014a56dd8bb6.png)

**Comment by aromanet42** [comment]
I still have this problem with Version 3.0.4 (packaged) (chrome extension)

![screenshot-20150721-181927](https://cloud.githubusercontent.com/assets/7204715/8806070/2bb95db8-2fd5-11e5-8819-0b83e1b72d09.png)

when I edit the URL, the path variable appears, but not when I reopen the request

![screenshot-20150721-182059](https://cloud.githubusercontent.com/assets/7204715/8806139/7eaf51f8-2fd5-11e5-8c19-a5d48bf4e4ca.png)
