### ISSUE TITLE
Cannot choose a monitor to integrate

### ISSUE THREAD

**Issue by Raj-postman** [a85/POSTMan-Chrome-Extension#6030]
**Describe the bug:**
When you try to setup an integration for a monitor, the existing monitors cannot be seen in the UI.

**Steps to reproduce the behavior:**
1. Navigate to team's workspace integrations page.
2. Choose an 'Application' eg: Slack and then click add new Monitor.
3. Authorize postman
4. Choose a monitor to be integrated here. There is no monitor to choose from.

**Expected behaviour:** 
Should be able to select one of the monitors > Add Integration

Screenshot:
![configure integration](https://user-images.githubusercontent.com/47771757/53942794-b6c9ab80-40e1-11e9-8b29-3ecd619c7aa0.png)

**Comment by MeanderingCode** [comment]
This issue is blocking my integration of Postman monitors with our alert channels.
Thanks for taking a look at it!

**Comment by preethammavin** [comment]
@MeanderingCode @Kurmavathar do you have the monitor in the workspace you are trying to create the integration in?

**Comment by MeanderingCode** [comment]
@preethammavin Yes, I do.

**Comment by preethammavin** [comment]
@MeanderingCode Thanks for letting me know, triaging the bug internally. Will give an update soon.

**Comment by januh** [comment]
FYI: it seems to be fixed now.

**Comment by godfrzero** [comment]
The listing API itself is fixed, but we're holding off on closing this issue until a clear loading state is also added. I should've provided an update on this ticket after pushing out the first fix though, sorry about that. 😞

**Comment by MeanderingCode** [comment]
Any update on this? It doesn't appear to be fixed for me.

**Comment by preethammavin** [comment]
@MeanderingCode we have pushed a fix on the API and pushed an update on the UI to load monitors before we let the user add them to the said integration. This issue should not be occurring, can you write to us at help@getpostman.com so that we can gather more details regarding this?

**Comment by preethammavin** [comment]
Hi,
We have pushed a fix for the same and the UI will load the monitors so that there is no confusion created on the user end

**Comment by JP-from-Postman** [comment]
@preethammavin Another report of this (post-fix) has been added to the JIRA

**Comment by preethammavin** [comment]
@JP-from-Postman we have pushed a fix for the same, can you verify if it has been fixed.

**Comment by godfrzero** [comment]
Closing this since the new issue has also been fixed and the fix has been verified.
