### ISSUE TITLE
V7 Linux Client

### ISSUE THREAD

**Issue by simonireilly** [a85/POSTMan-Chrome-Extension#6032]
Hi, when is Linux support coming for the v7 desktop client?

If it's out where can I download it - v6.7.4 is the latest on the downloads page.

Thanks for your time :+1:

**Comment by simonireilly** [comment]
Just tried the Canary build and it is also still v6 for Linux :+1:

**Comment by SamvelRaja** [comment]
@simonireilly  Thanks for being an early adopter of 7.0
Since, 7.0 is a major release. We are rolling it out in a very controlled way for our production channel users.

But, you can get the latest 7.0 in our canary channel now itself. 
https://www.getpostman.com/downloads/canary

**Comment by SamvelRaja** [comment]
Also, @simonireilly  You will be getting the updates automatically. I wonder why you didn't get inside your linux app itself as an update option.

**Comment by simonireilly** [comment]
Not sure - expected to see the update option, but it isn't present in the settings panel:

![image](https://user-images.githubusercontent.com/30017294/53955846-f8525a80-40d1-11e9-9553-81f1303c0355.png)

Running Ubuntu 18.04 with the snapcraft version installed.

Snap hasn't been updated since January 16th 2019 :+1: 

![image](https://user-images.githubusercontent.com/30017294/53955932-2c2d8000-40d2-11e9-9c29-5fec2b4787f2.png)

**Comment by simonireilly** [comment]
Also thanks for your response. Running on Canary now :+1:

**Comment by numaanashraf** [comment]
@simonireilly It seems like you have installed Postman from Snapstore or Ubuntu Software Center. Postman 7.0 is currently on candidate channel on Snap. Please try the following commands to switch your release channel line to candidate.

```
sudo snap switch --channel=candidate postman
sudo snap refresh postman
```
