### ISSUE TITLE
Unable to submit a Support Ticket, when Name field in user account is empty

### ISSUE THREAD

**Issue by JP-from-Postman** [a85/POSTMan-Chrome-Extension#6034]
Please read through the [guidelines](https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues) before creating a new issue.

**Describe the bug**
For a user account with an empty **Name**, or **Username**, field, attempting to log in and submit a support ticket via the Support page (getpostman.com/support), lands on the following URL, with the message shown below:
https://identity.getpostman.com/logout?kind=error&message=Invalid+data+from+remote+sign-in+mechanism.+Missing+name+or+email.
<img width="464" alt="screen shot 2019-03-07 at 10 42 23 am" src="https://user-images.githubusercontent.com/43283131/53981863-5d08b780-40c8-11e9-9cf7-b1af2ac3a02c.png">
Note, that the above happens when starting from a non-logged in state

**To Reproduce**
1. For any user account, navigate to account settings in Web Dashboard (https://go.postman.co/settings/me)
2. Delete contents of Name field, save
3. Navigate to getpostman.com/support, click Submit a Ticket
4. On following page (https://support.getpostman.com/hc/en-us/requests/new) click **Sign in to submit a ticket**
5. Sign in using account from step 1.
6. Land at the following URL:
https://identity.getpostman.com/logout?kind=error&message=Invalid+data+from+remote+sign-in+mechanism.+Missing+name+or+email.
7. Clicking either **Cancel** or **Sign Out** goes back to login page. Logging in again goes to go.postman.co

**Expected behavior**
Name is not a required field for logging in, and to submit a ticket. If it must be required, this should be handled outside of the login flow (e.g. disallow saving profile when Name field is blank).

**Screenshots**

**Additional context**
Just tested signing up for a new account with email + password: currently populates the Name field with username specified during signup. Not sure about Google or other SSO.

**Comment by abhijitkane** [comment]
@JP-from-Postman I see a different flow (where the user is taken to the workspace page instead of the support center). Does the flow you see change when the email is verified? 

EDIT: Nvm - reproduced the flow you reported by verifying the email.

**Comment by abhijitkane** [comment]
@JP-from-Postman This has been fixed. Can you confirm?
