### ISSUE TITLE
Could not open Postman, Please contact help@getpostman.com

### ISSUE THREAD

**Issue by zafaque** [a85/POSTMan-Chrome-Extension#6041]
Please read through the [guidelines](https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues) before creating a new issue.

**Describe the bug**
After updation to 6.7.4 version when try to open i am getting this error "Could not open Postman, Please contact help@getpostman.com"

**To Reproduce**
1. Have installed older version 6.0
2. Download new version
3. Extract the same
4. Click to open will ask to move to application
5. Move to application and open

**Expected behavior**
New version postman app should open
**Screenshots**
<img width="506" alt="screenshot 2019-03-07 at 3 41 14 pm" src="https://user-images.githubusercontent.com/16201892/54019887-5eaeaa00-41b2-11e9-9c80-819bc61a88db.png">

**App information (please complete the following information):**
 - App Type [Native App]
 - Postman Version [e.g. 6.0.1]
 - OS: [e.g. macOS High Sierra 10.13.2]

**Additional context**

**Comment by numaanashraf** [comment]
@zafaque Could you write to us at `help@getpostman.com`? We'll help you get this sorted.
