### ISSUE TITLE
Upgrading to V7 on win 10 blocks me from loading collection from my account. i can import new though

### ISSUE THREAD

**Issue by ionutale** [a85/POSTMan-Chrome-Extension#6042]
Like i said in the title, after updating from 6.7 to 7.0 it blocks me from loading: workspaces and collection from my account.
I can import new ones from  json files.

i did the upgrade on an MBP and is working fine. Only on windows it creates me problems

my account in the app and on the site is the same.
the collections and workspaces are mine, i am the admin

** i have tried
reinstaling the app
downgrading the app
creating a new account and assign as admin to the new account.

**To Reproduce**
upgrade to v7 , on a win 10

**Expected behavior**
i can see and browse the collections from other workspaces within the app, but can't load them into the "build" tab

**Screenshots**
workspace and collections available in the browse
note te join button
![image](https://user-images.githubusercontent.com/2562455/54024432-12567080-4198-11e9-9d41-e0b4c86ae899.png)

and this is the build screenshot
![image](https://user-images.githubusercontent.com/2562455/54024770-ed163200-4198-11e9-8e00-6068335dae9d.png)

**App information (please complete the following information):**
 - Win 10 native app
 - Postman Version 7.0
 - OS: WIN 10

**Comment by kamalaknn** [comment]
@jhonyourangel Do you see any errors in the devtools? `View -> Developer -> Show DevTools (Shared)`

Also could you check if your team is migrated to v7. You can check by visiting https://go.postman.co/settings/team/roles. Postman v7 apps work only for teams that have migrated.

**Comment by ionutale** [comment]
i manage to fig the issue by going to `C:\Users\<username>\AppData\Roaming\Postman` and delete everything.
reopen the application, log back to my account and all collections and workspaces automatically sync with my pc.

**Comment by ionutale** [comment]
i think this can be closed
