### ISSUE TITLE
DELETE request omits environment variable

### ISSUE THREAD

**Issue by weekian** [a85/POSTMan-Chrome-Extension#6043]
## App Details

```
Version 7.0.4 (7.0.4)
MacOS 10.14.1
```

## Issue

After setting the environment variable delete_id which is verified to exist by the quick peek button, 

Sending a DELETE request http://localhost:8090/user/:delete_id omits the variable entirely. The server receives a http://localhost:8090/user/ request coming in only.

Using :delete_id works for a POST request but not for a DELETE request

Using {{delete_id}} in the URL does not append / to the URL but does so for a POST request

**Comment by codenirvana** [comment]
@weekian Looks like you are using path variable notation to access environment variable.
[Variables](https://learning.getpostman.com/docs/postman/environments_and_globals/variables/) are only resolved using the curly braces notation.

Also, there's no restriction based on the request method. Can you provide more information(sample collection or local server) which can be used to reproduce this issue?
