### ISSUE TITLE
Crashes every time a collection with more than 2 requests runs

### ISSUE THREAD

**Issue by elie-g** [a85/POSTMan-Chrome-Extension#6044]
**Describe the bug**
Postman crashes every time a collection containing more than 2 requests is run in the collection runner.

**To Reproduce**
1. Create a collection
2. Create at least 3 requests in the collection
3. Run the collection in the collection runner

**Expected behavior**
Postman should run all the tests/requests without crashing.

**Screenshots**
![CRASH](https://i.imgur.com/aoIKYom.png)

**App information:**
 - App Type: `Desktop application`
 - Postman Version : `v7.0.5-canary01`
 - OS: `Windows 7 x64`

**Additional context**
I tried to change the order of the requests or skipping requests but it always crash after running the second requests no matter which one it is. I also checked the logs but I couldn't find anything abnormal.<br/>
I just updated postman to the latest version and I don't think it was crashing before.

**Comment by a85** [comment]
This is not a common behavior. We'll need more information to debug this if there are things specific to your collection, your requests or your API.

**Comment by vikiCoder** [comment]
@DrunkenPoney Please provide logs from Postman Console too.

**Comment by elie-g** [comment]
In the console, there is only my log from the test script of the last request executed. After that there is nothing and there is no error at all.

**Comment by codenirvana** [comment]
@DrunkenPoney Can you share a sample collection (minus sensitive details) with this behavior?

**Comment by shamasis** [comment]
We did try to replicate this issue at our end. We tried all innovative methods to do so, but couldn't come up with anything generic that can cause this. Closing this issue and waiting till we get to a scaled down collection that we can run at our end and reproduce it.
