### ISSUE TITLE
Your team updated to Postman v7.0. but no update present in settings. Will not sync

### ISSUE THREAD

**Issue by jean-husa** [a85/POSTMan-Chrome-Extension#6045]
Please read through the [guidelines](https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues) before creating a new issue.

**Describe the bug**
Upgraded one linux box at office to 7.0. When I open Postman on laptop at home I see banner: 
Your team updated to Postman v7.0. To keep your collections and workspaces in sync with your team, you must also update to v7.0 by going to  > Settings > Update. 
But when accessing settings>update there are no updates available. Syncing does not finish.

**To Reproduce**

Use Postman on two different linux boxes. Upgrade one to 7.0. Open old version (6.7.4) on other box and you will see message:

Your team updated to Postman v7.0. To keep your collections and workspaces in sync with your team, you must also update to v7.0 by going to  > Settings > Update

But there will be no update available and syncing will fail to occur.

**Expected behavior**
There should be an update available for 7.0. Syncing should occur after update.

**Screenshots**
![Screenshot from 2019-03-08 15-05-21](https://user-images.githubusercontent.com/48368684/54060980-b39ef000-41b3-11e9-84cf-f8123afb27ee.png)

**App information (please complete the following information):**
 64 bit Postman 7.0 and 6.7.4
Ubuntu 18.04.2 LTS

**Additional context**

**Comment by felamaslen** [comment]
Can confirm this issue on Ubuntu 18.04.1.

**Comment by numaanashraf** [comment]
@felamaslen @jean-husa
It seems like you have installed Postman from Snapstore or Ubuntu Software Center. Postman 7.0 is currently on `candidate` channel on Snap. Please try the following commands to switch your release channel line to `candidate`.

```
sudo snap switch --channel=candidate postman
sudo snap refresh postman
```

**Comment by orgmatileg** [comment]
cause this issues my collection are gone 40%

i thought collection is synced and i try to logut then re login but after that request that i writed is gone..

can i recover request that not synced?

Please help..

**Comment by drichardson-uk** [comment]
I have 7.0.4 on one of my machines and I didn't do anything special to install it other than auto updating.  My other box will not auto update beyond 6.7.4

Did version 7 get pushed out to some users and then pulled from auto updates?

**Comment by svishal** [comment]
I am facing still this issue, I have tried most of the solution suggestion over network.
But still not able to fix the sync issue.
I have attempted to upgrade the v7.0 but did not get success using following command.
`sudo snap switch --channel=candidate postman
sudo snap refresh postman`
and getting following response
`snap "postman" has no updates available`
I am using ubunut 16.04 LTS(64 bit)
Please suggest.

**Comment by er-pkumar** [comment]
I am facing still this issue, I have tried most of the solution suggestion over network.
But still not able to fix the sync issue.
I have attempted to upgrade the v7.0 but did not get success using following command.
`sudo snap switch --channel=candidate postman 
sudo snap refresh postman`
and getting following response
snap "postman" has no updates available
I am using ubunut 16.04 LTS(64 bit)
Please suggest.

**Comment by numaanashraf** [comment]
@pintukumar-ucreate We need more information of the postman version installed on your system. Could you send us a screenshot of the result of this command?
```
snap list postman
```

**Comment by jean-husa** [comment]
> @felamaslen @jean-husa
> It seems like you have installed Postman from Snapstore or Ubuntu Software Center. Postman 7.0 is currently on `candidate` channel on Snap. Please try the following commands to switch your release channel line to `candidate`.
> 
> ```
> sudo snap switch --channel=candidate postman
> sudo snap refresh postman
> ```

**Comment by jean-husa** [comment]
> @felamaslen @jean-husa
> It seems like you have installed Postman from Snapstore or Ubuntu Software Center. Postman 7.0 is currently on `candidate` channel on Snap. Please try the following commands to switch your release channel line to `candidate`.
> 
> ```
> sudo snap switch --channel=candidate postman
> sudo snap refresh postman
> ```

Which box do I do this on. The one with 7.0 or 6.7.4?

**Comment by jean-husa** [comment]
Also, could you explain what this will accomplish? Will it allow me to upgrade my other box to 7.0 or will it just allow me to sync between the two boxes?

**Comment by numaanashraf** [comment]
@jean-husa You should update the 6.7.4 app to v7.0 via the steps above. It'll help you update the app to v7.0 and as a result of that your collaboration features will start working.

**Comment by jean-husa** [comment]
will this:
sudo snap switch --channel=candidate postman
sudo snap refresh postman
update my 6.7.4 to 7.0?

**Comment by er-pkumar** [comment]
@numaanashraf: Here is output. Quick response will be much appreciated.
> snap list postman
`Name     Version  Rev  Tracking   Publisher     Notes`
`postman  7.0.4    82   candidate  postman-inc*  -`

> postman -v
`1552368660225 main info ["Booting Postman 6.7.4, linux-4.4.0-142-generic on x64"]
1552368660227 main info ["EventBus\\x7einitialize - Success"]
1552368660238 main info ["UpdateHandler\\x7einit - Success"]
1552368660239 main info ["RuntimeExecutionService\\x7einitialized: Success"]
1552368660246 main info ["ProtocolHandler\\x7einit - Success with status: false]"]
1552368660271 main info ["PluginHost - Booted for 1th time"]
1552368661685 main info ["Bootstrap-models\\x7ebootstrap - Success"]
1552368662442 pluginHost info ["Booting Plugin Host for Postman 6.7.4, linux-4.4.0-142-generic on x64"]
1552368662447 pluginHost info ["PluginsHost - Host: Booted"]
1552368662495 pluginHost info ["PluginInstallationService-_shouldReInstallPlugin",{"installedVersion":"0.0.9","currentVersion":"0.0.9"}]
1552368662495 pluginHost info ["PluginsHost: Synced all plugins",[{"pluginId":"postman.openApi","version":"0.0.9","status":"skipped"}]]
1552368664356 main info ["Main\\x7eAppEvents - Received booted event for process shared"]
1552368666101 main info ["UpdateHandler\\x7eapp-update-events - Received event",{"name":"checkForElectronVersionUpdated","namespace":"appUpdate"}]
1552368666103 main info ["Main\\x7eAppEvents - Received booted event for process requester"]
^C1552368675399 main info ["Qitting app"]
1552368675405 main info [null]
1552368675509 main error [{"extra":[],"name":"Error","message":"PluginHost exited with code null","stack":"Error: PluginHost exited with code null\n    at PluginHost.onHostExit (/opt/Postman/app/resources/app/node_modules/@postman/app-plugins-host/index.js:100:21)\n    at emitTwo (events.js:125:13)\n    at ChildProcess.emit (events.js:213:7)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)"}]
1552368675521 main error [{"extra":[],"name":"Error","message":"Trying to boot plugin host for 2th time","stack":"Error: Trying to boot plugin host for 2th time\n    at PluginHost.bootHost (/opt/Postman/app/resources/app/node_modules/@postman/app-plugins-host/index.js:23:23)\n    at PluginHost.onHostExit (/opt/Postman/app/resources/app/node_modules/@postman/app-plugins-host/index.js:101:10)\n    at emitTwo (events.js:125:13)\n    at ChildProcess.emit (events.js:213:7)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)"}]`

**Comment by numaanashraf** [comment]
@pintukumar-ucreate looks like you are already on Postman v7.0
> Name Version Rev Tracking Publisher Notes
postman 7.0.4 82 candidate postman-inc* -

**Comment by numaanashraf** [comment]
@jean-husa yes, those commands will help update your 6.7.4 postman snap to 7.0.4

**Comment by er-pkumar** [comment]
> @pintukumar-ucreate looks like you are already on Postman v7.0
> 
> > Name Version Rev Tracking Publisher Notes
> > postman 7.0.4 82 candidate postman-inc* -

yes @numaanashraf but native app still showing me v6.7.4 and sync issue with [collection.[](url)](url)
![postman](https://user-images.githubusercontent.com/22446034/54198919-a48aab80-44ed-11e9-9473-25cfd17ad206.jpg)

**Comment by jean-husa** [comment]
I did not need to run those commands. When I opened postman yesterday the settings menu had an update for v7. I updated and am syncing again. Thanks for your help.

**Comment by shashi0802** [comment]
![Screenshot from 2019-04-26 10-32-26](https://user-images.githubusercontent.com/38715772/56784560-b1016400-680e-11e9-9c4c-a280b149f411.png)
I also get same update banner but didn't get update option.

**Comment by jean-husa** [comment]
shashi0802 - I suggest you report this yourself. If you follow the thread, you'll see that I did nothing to fix this. I just opened postman the next day and the update was there.

**Comment by aabolfazl** [comment]
> @felamaslen @jean-husa
> It seems like you have installed Postman from Snapstore or Ubuntu Software Center. Postman 7.0 is currently on `candidate` channel on Snap. Please try the following commands to switch your release channel line to `candidate`.
> 
> ```
> sudo snap switch --channel=candidate postman
> sudo snap refresh postman
> ```

thank you is worked!

**Comment by SladeThe** [comment]
It is unacceptable, that you can't use the stable branch, because the latest stable version simply doesn't work.
Postman team, shame on you.

**Comment by kenji-1996** [comment]
@SladeThe lets relax, this application is insanely useful and these devs have done an incredibly good job of this. While its not the best an (easily to apply) solution is available, dont go attacking devs
Youre free to try and create something so polished and easy to use

**Comment by piyushagarwal62** [comment]
Tried using the above-given commands. But it is not working. Still on 6.74v.
Kindly help with valid commands.
