### ISSUE TITLE
Persist environment variables from the collection runner

### ISSUE THREAD

**Issue by brock** [a85/POSTMan-Chrome-Extension#6046]
I love the collection runner because it identifies issues and I can easily address failing tests. My collection runner also sets up authentication tokens that are saved to my environment and persisted throughout the runner. However, when I exit the runner, the environment variables saved _inside the runner_ are not saved in my environment _outside_ the collection runner.

If I'm using an environment when I use the collection runner, any environment variables set should be available in the main desktop app for that environment.

**Comment by numaanashraf** [comment]
@brock Have you tried using `Keep variable values` option while starting the run? Dependencing on your use-case, you need to use `Keep variable values` & `Setting > General > Automatically persist variable values` options. The reference for the same is at https://learning.getpostman.com/docs/postman/collection_runs/using_environments_in_collection_runs#configuring-the-collection-runner. Do let us know if you are still facing issues.

**Comment by brock** [comment]
Ah - I had not seen those settings. Those did exactly what I needed! Thanks!

**Comment by danielPKI** [comment]
Useful for me. Thanks!
