### ISSUE TITLE
Something went wrong upon sign in to Canary `net::err_name_not_resolved`

### ISSUE THREAD

**Issue by cyrielle-hada** [a85/POSTMan-Chrome-Extension#6050]
**Describe the bug**
_Something went wrong_ error message upon sign in to Postman Canary. 

**To Reproduce**
1. Go to https://www.getpostman.com/downloads/canary and download Postman Canary for Mac 
2. Once installed, open the app and sign in. 
3. See below error message

![image](https://user-images.githubusercontent.com/47351631/54129771-e68cf200-4406-11e9-86a5-ae5f43a60ddd.png)

Errors in View > Developer > Show DevTools (Shared)
![image (1)](https://user-images.githubusercontent.com/47351631/54129861-1b994480-4407-11e9-9212-55df920c85a9.png)

No error in View > Developer > Show DevTools (Current View)

**Expected behavior**
Open the app, sign in and retrieve sync collections. 

**App information (please complete the following information):**
 - Canary build 
 - 7.0.5-canary01
 - macOS

**Additional context**
The goal is to install Canary in order to pull the synced collections to remove the Postman directory and do a fresh install.

**Comment by numaanashraf** [comment]
@cyrielle-hada Would it be possible to zip the logs and send us at help@getpostman.com? You can find the logs at View > Developer > View Logs in Finder. Please mention this GitHub issue number (GH#6050) in the email when you write to us.

**Comment by cyrielle-hada** [comment]
The error is likely due to a networking issue as the error in the DevTools indicates that a domain name can’t be resolved.

Whitelist the following domains on the network firewall to allow WebSocket connections for Postman should solve the issue. 

*.getpostman.com
*.postman.co
*.pstmn.io
*postman.com
