### ISSUE TITLE
Invert I beam cursor color in dark mode

### ISSUE THREAD

**Issue by loomisdf** [a85/POSTMan-Chrome-Extension#6051]
Please read through the [guidelines](https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues) before creating a new issue.

**Describe the bug**
The I beam cursor (shape of cursor when editing text) is very hard to see while using the dark theme. It's enough of a problem that I'm forced use the light theme instead.

**To Reproduce**
1. Enable Dark theme
2. Move cursor over an area with editable text (ie json body)

**Expected behavior**
The I beam should change to a white color when using the dark theme.

**Screenshots**
Here's a comparison of what happens to the cursor in IntelliJ's Darcula theme vs. Postman
What it looks like in IntelliJ (v2018.3.5):
![cursor_extracted_intellij](https://user-images.githubusercontent.com/6811138/54141124-1205e180-43f3-11e9-8683-fe32fc6f105f.png)

What it looks like in Postman (v7.0.5):
![cursor_extracted_postman](https://user-images.githubusercontent.com/6811138/54141143-19c58600-43f3-11e9-935e-2ba45900454e.png)

**App information:**
 - App Type Native App
 - Postman Version 7.0.5
 - OS: MacOs High Sierra v10.13.6

**Additional context**
The cursor is serviceable but not great on my external display and is nearly impossible to see on my MacBook's retina display.

**Comment by numaanashraf** [comment]
@loomisdf I tried replicating this on a MacBook with retina display and I'm unable to simulate this case. Any more information you can provide that'll help us understand why this is happening at your end? I did some digging around to check whether we would be able to control the cursor - I'm afraid this is not possible with the technology Postman is currently built on. I-beam cursors are controlled via the OS and we do not have any programmatic access to set these on the OS.

**Comment by loomisdf** [comment]
Interesting, I'm not sure why this appears to be happening to my laptop then. It's issued by the company I work for and uses a custom image that could be messing with the cursor.

**Comment by loomisdf** [comment]
I was able to update MacOs to Mojave (v10.14.3) and the problem seems to have disappeared. Cursor now looks like this in postman:
![cursor_extracted_mojave](https://user-images.githubusercontent.com/6811138/54212181-8b173e80-44b0-11e9-8208-22df018e9d31.png)
Issue is solved for me, but I was never able to figure out why it didn't work on MacOs 10.13.6.
