### ISSUE TITLE
Full screen environment variables editor

### ISSUE THREAD

**Issue by jiimaho** [a85/POSTMan-Chrome-Extension#6052]
Please read through the [guidelines](https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues) before creating a new issue.

**Is your feature request related to a problem? Please describe.**
It's hard to see all environment variables and edit them

**Describe the solution you'd like**
Full screen environment variables editor

**Describe alternatives you've considered**
Nothing really. Maybe an option to at least make the editor slightly bigger would be good.

**Additional context**
![image](https://user-images.githubusercontent.com/5954936/54154528-5f5d6f80-4442-11e9-9066-33e51ce0e84c.png)

**Comment by martijnvanschie** [comment]
UPVOTED.
I really think this is an underestimated feature request. I see a lot of these issues reported.
The editor is not user friendly at the moment.

**Comment by DannyDainton** [comment]
Hey @jiimaho / @martijnvanschie 

We have just updated the Canary Channel to V8 which brings in a whole host of new and improved items, including a change to the way you can manage your environment variables. The environment will now open in a full tab view, much the same as the way requests do.

![image](https://user-images.githubusercontent.com/17089546/104316923-1874b100-54d5-11eb-9b6d-e0d23dd60b50.png)

You can download the V8 Canary version from here: https://www.postman.com/downloads/

This view has been part of the [Postman Web Version](https://web.postman.co/) for a while now but will be heading to the desktop app very soon.  ❤️

**Comment by martijnvanschie** [comment]
The new V8 release is very nice. The editor is much better now. UI is also more user friendly.
Keep the good updates coming :)
