### ISSUE TITLE
Add proxy support for Postman/Agent app updates

### ISSUE THREAD

**Issue by girtsn** [a85/POSTMan-Chrome-Extension#6053]
Please read through the [guidelines](https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues) before creating a new issue.

**Describe the bug**
I have set a globall proxy (cntlm) and see all requests passing even when made from postman. However when clicking on check updates or signin, see no requests arriving at proxy.

**To Reproduce**
1. set up a local proxy
2. set the proxy and port in global settings
3. see successful test requests
4. check for updates / sign in do not seem to try to use the proxy

**Expected behavior**

**Screenshots**

**App information (please complete the following information):**
 - App Type Windows Native App
 - Postman Version [e.g. 7.0.5]
 - OS: [e.g. Windows 7]

**Additional context**

**Comment by numaanashraf** [comment]
Proxy setting affect only requests sent by the user. Proxy config is not supported for requests made during update check and sign-in at the moment. Tracking this as a feature request.

**Comment by girtsn** [comment]
It must be clear that for corporate environments, this behavior is pretty useless- as proxy is the only way to access the internet. And even worse it is breaking here as the new version check and showing login screen on startup seems to hang due to trying to connect and failing. Is there at least a workaround until a proper fix to disable those 2 at startup?

**Comment by cokeby190** [comment]
I agree with @girtsn, in a corporate environment, all the network traffic would have to go through the proxy, and its misleading if there is a proxy setting within the application but features like login and updates are not going through that said proxy. Currently I am not logging in in order to avoid the login proxy issue, but it can only be a short term thing, it's really not an elegant solution for now (:

**Comment by girtsn** [comment]
Hello, any updates on this issue? It is preventing anyone in a corporate environment where proxy is needed to get to internet to use Postman native application...

**Comment by apolloniusoftyana** [comment]
@numaanashraf Just to understand... Sign-in, update, sync etc... does not use the proxy settings in preferences(macOS)? Does the app respect the system settings at all for these operations? My testing indicates that it is not using native macOS settings or the defined settings in Postman.

**Comment by ioneyed** [comment]
We currently use Postman in an enterprise setting that requires the use of a corporate proxy. This corporate proxy is an authenticated proxy, to date the only way we have been able to make signin/update/sync work (sometimes) is via a SOCKS local proxy that is unauthenticated which chains to our corporate proxy. This is only working on our Mac/Linux developer machines as they are able to install these types of solutions. That being said we are missing out on the ability for our Windows based developers/Product Managers access to the solution without first using the guest WiFi to sync then flip back over.

If Postman Sync/Update/Signin would auto-detect proxy settings and prompt for authentication if it is missing like most other applications that would, albeit not ideal, a solution as well. Without the windows users having a better experience we will not be able to gain the mass adoption that we are hoping to achieve in the coming year.

**Comment by ankurdengla** [comment]
Hey @girtsn @cokeby190 @apolloniusoftyana @ioneyed ! 

We’ve released authentication support for proxy servers in the latest canary version (v7.18.0-canary02) of the app. The app will use the system proxy settings by default and show a window to enter credentials if the proxy server requires authentication. Please give it a try and share any feedback that you might have with us.

The canary app can be downloaded from here - https://www.postman.com/downloads/canary.

**Note that the request sending feature will still rely on the proxy settings available in `Settings`.**

**Comment by apolloniusoftyana** [comment]
@ankurdengla So far testing has show this to be working as advertised. App passes through proxy for App updates, login and sync. Is the app using the "Use System Proxy" in Settings or is it just observing the OS System and the options in Settings are simply for request sending?

**Comment by ankurdengla** [comment]
@apolloniusoftyana The app is just observing the OS proxy settings and using those for features like updates, login, syncing, etc. 
The `Proxy` option in `Settings` just applies to the request sending flow.

**Comment by girtsn** [comment]
Excellent, seems to be working as advertised, when is this going to be released via the normal release channel? Our organization does not allow to use canary builds officially.

**Comment by ankurdengla** [comment]
Hey @girtsn @cokeby190 @apolloniusoftyana @ioneyed !

Proxy authentication support has been released as part of Postman v7.21.0. You should now be able to use Postman's sign-in flows from behind a proxy server.

**Comment by jviotti** [comment]
Merging this ticket with https://github.com/postmanlabs/postman-app-support/issues/7240, as that's pointing out the bigger problem: that Postman does not obey system proxy settings, either on the app nor on the updates.
