### ISSUE TITLE
White space in encoded URL not shown in Postman Console

### ISSUE THREAD

**Issue by Consth** [a85/POSTMan-Chrome-Extension#6055]
The Postman App does not visibly convert white spaces in the URL with %20 as it should. Therefore when using the request and code from Postman, the URL is wrong and this causes a lot of time loss when you are not using HTTP requests everyday.

## App Details:
Postman for Mac
Version 6.7.3
OS X 18.2.0 / x64

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there: Not Sure, I just started using the app
 2. Expected behaviour: automatically replace white spaces with %20 (same for unsupported characters in URL)
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
 4. Screenshots (if applicable)

**Comment by vikiCoder** [comment]
Hi @Consth 

I checked for the issue in the latest version of Postan App(v7.6.0), it looks like the latest Postman App is encoding white space characters to `%20` properly. In below GIF, I send a request with a white space character in URL to my local echo server and send the raw request back as a response. You can see the white character being properly encoded to `%20` in the response.

![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/16588032/64684435-c10a9f00-d4a2-11e9-9e2f-49174772622c.gif)

However, it looks like a bug with Postman Console which is not showing the request with actually sent URL(with encoded characters). Rather it is showing the original URL that is entered while sending requests.

**Comment by coditva** [comment]
Yes, the problem here seems to be that the space is not shown as encoded in the console itself. However, if you send a request to `/foo%20bar` (not `/foo bar`), the space is shown.

The issue here seems to be that the console shows the url that was typed by the user rather than the url to which the request was sent. Updating the title to reflect this issue.

**Comment by ritwijsinha** [comment]
Hello, @Consth.

This has been fixed in the new Postman Console. Kindly update to Postman v7.10 for this.

![image](https://user-images.githubusercontent.com/19693841/68191664-085e6900-ffd6-11e9-8e25-1ba674859aff.png)

Cheers! 🎉

**Comment by shivamManswalia** [comment]
UPDATE the application.

**Comment by robross0606** [comment]
This also seems to be a problem in code snippet generation.  Things like `curl` command lines do not show properly encoded parameters.
