### ISSUE TITLE
Postman 6.7.4 does not start on Mac OS X Mojave 10.14.1

### ISSUE THREAD

**Issue by zafaque** [a85/POSTMan-Chrome-Extension#6057]
Please read through the [guidelines](https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues) before creating a new issue.

**Describe the bug**
After deleting postman when tried to open to version 6.7.4, its not opening its throwing error ""

**To Reproduce**
1. Was having older version
2. Deleted the old version
3. Open new version app

**Expected behavior**
App should open
**Screenshots**
If applicable, add screenshots to help
<img width="397" alt="Screenshot 2019-03-12 at 8 54 30 PM" src="https://user-images.githubusercontent.com/16201892/54212523-17ede680-4509-11e9-9a0d-26170f9c79c7.png">
 explain your problem.
it is throwing error message "Could not open Postman"

**App information (please complete the following information):**
 - App Type [e.g. Chrome App, Native App]
 - Postman Version [e.g. 6.0.1]
 - OS: [e.g. macOS High Sierra 10.13.2]

**Additional context**

**Comment by numaanashraf** [comment]
@zafaque Please write to us at `help@getpostman.com`. We can help you get this sorted.
