### ISSUE TITLE
Bootcamp/Learning courses not working

### ISSUE THREAD

**Issue by chrisdeso** [a85/POSTMan-Chrome-Extension#6062]
Bootcamp/Learning tab not working

**Describe the bug**

**To Reproduce**
1. Open app (7.0+)
2. Click on `Bootcamp`
3. Attempt to access `Monitoring`, `Automated testing`, `Designing and mocking APIs`
4. Notice that nothing happens

**Expected behavior**
Relevant in-app learning module should begin.

**App information (please complete the following information):**
 - Native App
 - Postman Version 7.0.5
 - OS: MacOS & Windows

**Additional context**
[Filed by Postman]

**Comment by prashantagarwal** [comment]
@chrisdeso Can you add a screen recording of this issue.

**Comment by preethammavin** [comment]
@chrisdeso I am able to start all the lessons 

Can you confirm that when you try to start the lesson, your sync icon is orange?

Would be great if you could write to us at help@getpostman.com with the email-id you are using in the Postman account.

**Comment by chrisdeso** [comment]
@prashantagarwal @preethammavin 

![Gif](https://i.imgur.com/FLnJsoM.gif)

@preethammavin Sync is working and this was user-reported but I was able to reproduce locally too.

**Comment by donovan-middleton** [comment]
I was the one that sent the issue in. I just downloaded Postman and installed it a couple of days ago. I also have the orange sync icon.  Just stumbled across this when trying to learn more about the product! Pretty easy to just pick up basic things though.

**Comment by prashantagarwal** [comment]
@donovan-middleton @chrisdeso We have fixed this issue and released it as part of Postman v7.0.6. After updating the app you should now be able to start the lesson irrespective of the fact whether the sidebar is visible or not.

Sorry for the inconvenience.
