### ISSUE TITLE
Add 'Add and open in new tab' option while adding new request to the collection

### ISSUE THREAD

**Issue by singhravi1** [a85/POSTMan-Chrome-Extension#6067]
Hi,

It would be a nice option to have the new request open in the new tab while adding to the collection.
Else, we have to go at the and of the collection and then open the newly added request.

**Comment by giridharvc7** [comment]
Does this fix your problem?
![image](https://user-images.githubusercontent.com/1040583/109607324-15e61d80-7b4e-11eb-89ae-dca2c2134e76.png)

**Comment by singhravi1** [comment]
Yup, checked on the latest postman version and intended feature is there.
Thanks a lot EVERYONE!
