### ISSUE TITLE
App shows enable sync button when sync is disabled for teams

### ISSUE THREAD

**Issue by kerak19** [a85/POSTMan-Chrome-Extension#6069]
**Describe the bug**
After logging in into Postman, Sync is stuck. After looking into dev tools, every click on `Enable Sync` is giving `Uncaught (in promise) SyntaxError: Unexpected end of JSON input`

**To Reproduce**
1. Log out and delete all local data.
2. Login into Postman
3. `Sync your API requests across devices` is stuck - animation with 2 white arrows on blue background plays, but that's it.
![image](https://user-images.githubusercontent.com/17686157/54284498-5387bf80-45a0-11e9-94f6-8aedef7ab938.png)
4. When trying to show `Team` workspaces app shows the `Enable Sync to create a workspace` window, but after clicking on `Enable Sync` dev tools shows `Uncaught (in promise) SyntaxError: Unexpected end of JSON input`:
![image](https://user-images.githubusercontent.com/17686157/54284669-a95c6780-45a0-11e9-91bb-cc842c8a69c5.png)
![image](https://user-images.githubusercontent.com/17686157/54285118-a01fca80-45a1-11e9-82bd-1f7aa12bfb9c.png)

**Expected behavior**
Postman finishing sync and showing me all my workspaces.

**App information (please complete the following information):**
 - Postman for Linux
 - Version ~~7.0.5~~ 7.0.6
 - Linux 5.0.0-arch1-1-ARCH / x64

**Comment by kerak19** [comment]
Update: Upgrading Postman to version 7.0.6 didn't help.

**Comment by afsmeira** [comment]
Any update or ETA for this? Right now I've updated the team dashboards to 7.x and they can't be synced and can't be reverted to a previous version, so we are kind of locked out of our own Postman.

**Comment by abhijitkane** [comment]
@afsmeira @kerak19 Can you write in to help@getpostman.com from your registered email? There might be something specific to your accounts that's causing this.

**Comment by kerak19** [comment]
@abhijitkane I'll try this soon

@edit looks like our bill wasn't paid yet and it caused the problem with sync. After fixing billing problem, sync started working again.

**Comment by Kemikal17** [comment]
I don't know if this helps, but I started getting the same error after having updated to the 7.x version of the app on my personal PC, while the work PC app is still on 6.x. On the work PC, the application informs me that "my team has upgraded to the 7.x version of the application. press the tools button > update to upgrade", while the sync icon is in continuous animation. Maybe this piece of information could help in fixing the issue, who knows? :) Kind regards!

**Comment by DannyDainton** [comment]
Closing this issue as it has now been resolved.

Please feel free to reopen with the steps to reproduce if the issue persists.
