### ISSUE TITLE
7.0.6 Missing Requests within collection

### ISSUE THREAD

**Issue by Kspen** [a85/POSTMan-Chrome-Extension#6070]
**DESCRIPTION**

Recently upgraded to 7.0.6.

Prior to update, I had cleaned out everything and created a new collection with 8 requests.  I then created some folders in which to move existing requests into.  After creating new folders, I noticed that I could no longer see all my requests.  Soon thereafter, I was requested to update the app.  I am now on 7.0.6 but still only see 4 of my 8 requests within the collection.

I also noticed that I cannot move (drag/drop) a test out of a folder that I recently created. "Something went wrong while moving this request".

I cannot delete the collection.

Additionally, when I export to JSON, the dump only contains the 4 requests I can see. 

**WORKAROUND**

1. Fork Request
2. Export
3. Edit JSON, change info.name
4. Import

When I forked my collection, the forked version displays all 8 requests, none of which are in folder, whereas the original collection has 3 in root folder and 1 request in a folder (which I can't move request out of).

**Comment by kamalaknn** [comment]
Hey @Kspen 

Are you still seeing issues related to syncing? If yes, can you send your logs from `View -> Developer -> View logs in Finder` to help@getpostman.com

We will take a closer look at it.

**Comment by Kspen** [comment]
Thanks for the reply.  I haven't encountered it since applying the
workaround I mentioned previously.  I will keep you posted, if I am able to
recreate the issue on the newer version of the app.

**Comment by kamalaknn** [comment]
@Kspen Thanks for the update.

I'm closing this issue now. Feel free to write back to us if you are seeing this issue again.
