### ISSUE TITLE
Microsoft Surface Pen won't work on Postman Native App

### ISSUE THREAD

**Issue by LordRafa** [a85/POSTMan-Chrome-Extension#6071]
**Describe the bug**
Postman App UI ignores Surface Pro Pen taps, which prevent you to use this device to work with postman.

**To Reproduce**
1. Tap any button or controller with the Surface Pro Pen, it will not work.

**Expected behavior**
I would expect to being able to control Postman native app, as I do with the mouse or the touch screen.

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version: 6.7.4
 - OS: Windows 10

**Additional context**
Using a Microsoft Surface Pro 2018 with the Surface Pen

**Comment by numaanashraf** [comment]
@LordRafa A fix for this issue is available on our early access 'Canary' channel - https://www.postman.com/downloads/canary. Could you try out this build and let us know?

**Comment by LordRafa** [comment]
Unfortunately I don't have my Surface any more...
