### ISSUE TITLE
Delete GitHub integration not working

### ISSUE THREAD

**Issue by cyrielle-hada** [a85/POSTMan-Chrome-Extension#6072]
**Describe the bug**
The GitHub integrations can't be deleted. 
![image001](https://user-images.githubusercontent.com/47351631/54299240-66a38b00-45b2-11e9-9819-912fd2764f15.jpg)

**To Reproduce**
1. Go to the web dashboard > configured integrations 
2. Click on the bin icon
3. See error

**Comment by preethammavin** [comment]
A fix for the same has been pushed.
