### ISSUE TITLE
Post-RBAC, support-only accounts cannot be invited, if user slots are at capacity

### ISSUE THREAD

**Issue by JP-from-Postman** [a85/POSTMan-Chrome-Extension#6075]
Please read through the [guidelines](https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues) before creating a new issue.

**Describe the bug**
For a team that has been migrated to RBAC:

Inviting support-only accounts (admin/billing only) via the web dashboard, **when the team still has free user slots**, can be done via the new invite dialogue:
<img width="543" alt="dashboard,manage-team,invite-dialogue" src="https://user-images.githubusercontent.com/43283131/54320076-fb08f000-45a8-11e9-8e0d-1271e2108adb.png">

However, if the team in question has **no available user slots**, clicking **Invite** on the team management page shows the following message instead:
<img width="503" alt="Screen Shot 2019-03-13 at 3 54 55 PM" src="https://user-images.githubusercontent.com/43283131/54319955-abc2bf80-45a8-11e9-8832-34bc32f08424.png">

The old invite dialogue had separate "views" for inviting users and support accounts. Related?

**To Reproduce**
1. For a paid team that is not at full user capacity, invite a support-only account from the web dashboard
2. See that this succeeds
3. Remove this support-only account, and add enough users to the team that the capacity is filled
4. Try inviting a support-only account from the web dashboard
5. See alert that team is full, and more slots need to be added

**Expected behavior**
The full team message should instead be shown after an admin tries to invite more **paid users** than supported by the current plan. This way, if an admin is trying to add a support-only account, they will still be able to access the invite dialogue and do so.

**App information (please complete the following information):**
 - App Type: Web dashboard
 - Postman Version: 7.x (post team migration)
 - OS: N/A

**Additional context**

**Comment by preethammavin** [comment]
This issue has been fixed, do feel free to reopen if it occurs again.
