### ISSUE TITLE
Delete action for history group delete is always disabled  though the user has permission to do

### ISSUE THREAD

**Issue by SamvelRaja** [a85/POSTMan-Chrome-Extension#6076]
**Describe the bug**
In the history sidebar, when user tries to delete the history as a bulk.
The option is disabled always, referring it as not allowed to perform action as he/she doesn't have permission even he/she has permission to do.

**Expected behavior**
It should be disabled / enabled based on the permission 

**Screenshots**
![Capture](https://user-images.githubusercontent.com/5114052/54329484-dad44200-4637-11e9-81c7-d4edd2b220ff.PNG)

**App information (please complete the following information):**
 - App Type [Native App]
 - Postman Version [e.g. 7.x]
 - OS: [All]

**Comment by numaanashraf** [comment]
Fixed in v7.0.x
