### ISSUE TITLE
Failed to Integrate and was unable to build connection between two applications using OAuth 2.0

### ISSUE THREAD

**Issue by Raj-postman** [a85/POSTMan-Chrome-Extension#6077]
When using postman to authenticate the user to build a connection between Postman and the other application was unable to do so from a valid token using OAuth 2.0.

1. Using oAuth2.0, Generate new access token.
2. Values filled are callback url, auth url, client id, and client secret, grant type was "Authentication code". 3. The generated token was put in headers and url.
4. The headers used are **A.** Authorization: Bearer AccessToken **B.** Content-Type: application/json 
5. After attaching access token in POST at the end of the url as **access_token=accesstoken**
6. Received error : 
                                 "message": "Session expired or invalid"
                                 "errorCode": "INVALID_SESSION_ID" 

Expected behavior:
Be able to build a connection between Postman and the other application and Integrate it.

 - App Type - Native App
 - App version: 6.7.3

This error is specific to version v6.7.3 and the same worked perfectly fine in v4.7.2

**Comment by abhijitkane** [comment]
@Kurmavathar You'll need to work with the OAuth provider to debug the INVALID_SESISON_ID error. Postman's OAuth2 helper is limited to generating the access token. If a freshly obtained access token is throwing an error from the provider, you'll need to take it up with them.

Feel free to reopen if you're unable to obtain the access token.
