### ISSUE TITLE
Google Sign-in throwing 500 error

### ISSUE THREAD

**Issue by chrisdeso** [a85/POSTMan-Chrome-Extension#6081]
**Describe the bug**
When attempting to log in using Google, a `500 – Internal Service Error` is thrown.

**To Reproduce**
1. Open the Postman app or Web interface – [go.postman.co](https://go.postman.co)
2. Sign in using Google
3. See error

**Expected behavior**
Successful sign-in and/or a non 500 error

**Screenshots**
![image](https://user-images.githubusercontent.com/4734306/54390043-877de600-466f-11e9-82d0-dd6cc88e6fd7.png)

**Additional context**
[Filed by Postman]

Request Trace: `v=1;t=78449e0cfb885602`

**Comment by iBotPeaches** [comment]
How are we supposed to sign in now if we only use Google sign in? Blocked from signing into our Postman Teams account due to this 500 error.

**Comment by T1l3** [comment]
Had the same issue, magicaly resolved this afternoon

**Comment by elssar** [comment]
@iBotPeaches apologies for the delay in getting this resolved. We released a fix for this bug yesterday. Can you please try logging in via google and let me know if the problem still persists.

**Comment by iBotPeaches** [comment]
@elssar All good now. Thanks for the fix!

**Comment by adardesign** [comment]
Having the same issue, 500 after logging in via google
