### ISSUE TITLE
Local variables continue to exist between requests or iterations

### ISSUE THREAD

**Issue by vdespa** [a85/POSTMan-Chrome-Extension#6082]
**Describe the bug**
My previous understanding was that local variables are local to the request, meaning they can only be used to pass data within the request (for example between the pre-request script and the request itself or the tests).

It seems that local variables continue to exist when using the Collection Runner or Newman. 

**To Reproduce**
1. Import the following collection (for inspection)
`https://www.getpostman.com/collections/2ea0a939bbf4cf195291`
2. Run the collection with Newman or the collection runner
`newman run https://www.getpostman.com/collections/2ea0a939bbf4cf195291 --iteration-count 2`
3. It seems that the **second request** can also read the local variable that the first request has set
4. It seems that also the **second iteration** has access to local variables that the first iteration has set.

**Expected behavior**
I would have expected for local variables to be destroyed after the request that has set them is done.

**Screenshots**
<img width="328" alt="Screen Shot 2019-03-15 at 12 37 20" src="https://user-images.githubusercontent.com/1197635/54409000-6f659f80-471f-11e9-98bd-b436bb646b32.png">

**App information (please complete the following information):**
 - App Type Native App
 - Postman Version 6.7.4
 - OS: macOS

**Comment by codenirvana** [comment]
@vdespa That's expected behavior. Local variables are persisted for the entire run (including iterations).

**Comment by vdespa** [comment]
This was not what I had understood from what @sivcan previously explained in #4052

"Local : Variables that you'll be defining in the scripts and using them will be local to those requests."

**Comment by vdespa** [comment]
How are we supposed to use these variables if their behavior is so different between Postmand and the Collection Runner / Newman. What is their purpose / use-case?

**Comment by codenirvana** [comment]
@vdespa Just checked #4052 and https://github.com/postmanlabs/postman-docs/issues/1442.
Clearly, the existing documentation and the previous thread caused lots of confusion regarding the scope of local variables.

Actually, local scope is much more complex than what's discussed so far. It works similar to `prototype` in JavaScript. Example:
```javascript:
// pm.variables.get('foo') will be looked up like this:
{
  state: [state from previous runs], // return `foo` from local scope
  // otherwise, lookup all the layers until `foo` is found
  layers: [
   "VariableScope:data",  // return `foo` from data scope else keep searching
   "VariableScope:environment", // return `foo` from data scope else keep searching
   "VariableScope:collection",  // return `foo` from collection scope else keep searching
   "VariableScope:global",  // return `foo` from global scope else undefined
  ]
} 
```

Now this local state it holds is persisted across the collection execution.

I know this is not the explanation you are looking for but this is how its implemented. I will write proper technical documentation in our postman-sandbox repository regarding variable scope resolution and the same can be referred to update the existing variable's documentation.

**Comment by vdespa** [comment]
@codenirvana Thank you for clarifying.

What still remains a mistery is when does it make sense to use local variables. Maybe you can share some insights?

**Comment by abhinaba-ghosh** [comment]
Hi @vdespa , thanks for raising this issue. 
We have recently refreshed the contents to add more insights regarding the scope of the variables. Let us know if you have any feedback on the same. 
https://learning.postman.com/docs/sending-requests/variables/
