### ISSUE TITLE
Environments in workspace do not show up in all environments view in profile

### ISSUE THREAD

**Issue by kamalaknn** [a85/POSTMan-Chrome-Extension#6084]
**Describe the bug**
Environments present in "My Workspace" are not shown in the "Environments" section in profile page.

**To Reproduce**
1. Create few environments in My Workspace
2. Click on "Profile" on user dropdown
3. Environments are missing

**Expected behavior**
All environments should show up in the env section.

**Screenshots**
![Screenshot 2019-03-15 at 10 23 32 AM](https://user-images.githubusercontent.com/8401064/54409585-91562680-470d-11e9-9825-8e0d74ff59a7.png)
![Screenshot 2019-03-15 at 10 23 39 AM](https://user-images.githubusercontent.com/8401064/54409586-91562680-470d-11e9-856b-c14ecdd3ff17.png)

**App information (please complete the following information):**
 - N/A

**Comment by preethammavin** [comment]
The fix for this issue has been deployed.
