### ISSUE TITLE
Merging the collections should trigger Slack alert

### ISSUE THREAD

**Issue by Raj-postman** [a85/POSTMan-Chrome-Extension#6086]
Slack integration mentions "Get alert for all activity on your workspace" but currently not receiving any slack alert on Merges.

**Steps:**
1) To enable the main collection to be consistent across the team, take a fork of the collection from Team workspace to Personal Workspace
2) After having a certain number of updates, Select **Merge** the collection to Personal workspace
3) Personal collections to get auto-updated, Select Merge and Update

App - Native App
Version - '6.7.3-darwin-x64'

**Expected solution:**
To receive slack alerts when a collection is merged on the workspace.

Currently, we get alerts on Slack if someone by mistake is updating the team collection and not forking it in personal workspace.

**Comment by ankit-m** [comment]
Issue fixed.
