### ISSUE TITLE
Could you create  a proper shortcut for Postman on Linux?

### ISSUE THREAD

**Issue by caiodev** [a85/POSTMan-Chrome-Extension#6089]
I think Postman for Linux should be turned into a snap package so we could have an auto updated application and also a proper shortcut. Today if one wants to have a shortcut, one has to create their own. It could be much easier if when Postman is installed, a shortcut is already added to the system

**Comment by numaanashraf** [comment]
@caiodev Official snap package for Postman is available on the Snap Store (https://snapcraft.io/postman)

If you are on Postman v7.0, you need to install the `candidate` channel from the snap.

```
sudo snap install postman --candidate
```

**Comment by caiodev** [comment]
Thanks @numaanashraf. It's not as updated as the one i'm using now but in the long run it'll be easier to maintain
