### ISSUE TITLE
Double click selecting on text can place cursor at start or end of word

### ISSUE THREAD

**Issue by valtism** [a85/POSTMan-Chrome-Extension#6091]
**Describe the bug**
Double clicking selects the word, but also adds a cursor to either the start of end of the word, depending on which half of the word you double click. This means that the cursor is often accidentally placed at the start of the word, and when shift clicking to select more on the line, the originally selected word becomes unselected.

I would much prefer the selection to work as it does in the browser / an IDE, where the text is selected and shift clicking either side will increase the selection while retaining the originally selected word.

**To Reproduce**
1. Double click the first half of a word in a text box or result panel
2. The cursor should be at the start of the word, with the word highlighted.
3. Select more text to the right using shift click.
4. The extra text should be selected, while the original word is no longer selected.

**Expected behavior**
Both the original word and the extra text should be selected. 

**App information (please complete the following information):**
Postman for Windows
Version 7.0.6
win32 10.0.17134 / x64
Windows 10 Version 1803

**Additional context**
Vice versa should also work with selecting the right side of a word and then selecting more text behind.

**Comment by pankajk07** [comment]
Fixed as part of v7.24
