### ISSUE TITLE
500 error received when accessing the API documentation

### ISSUE THREAD

**Issue by cyrielle-hada** [a85/POSTMan-Chrome-Extension#6092]
**Describe the bug**
The API documentation (https://docs.api.getpostman.com/) throws a 500 error, only when logged in via the web dashboard. The issue is not happening in private mode or logged out. 

**To Reproduce**
1. Log into the web dashboard http://app.postman.co
2. Access https://docs.api.getpostman.com/
3. See error (screenshot below)

**Expected behavior**
See the API documentation. 

**App information**
Postman application version: 6.7.4 (windows 7 64bit)

**Screenshot**
![lalfdljnnlmmaach](https://user-images.githubusercontent.com/47351631/54523261-fe182d80-4966-11e9-875d-6fca988fb589.png)

**Comment by ankitjaggi** [comment]
@cyrielle-hada This issue has been fixed. Could you verify once?

**Comment by dhineshwiz** [comment]
@cyrielle-hada The fix has been deployed from our end, feel free to re-open, if you find any issues
