### ISSUE TITLE
Unable to pin Postman on Chromebook with Unix app

### ISSUE THREAD

**Issue by Raj-postman** [a85/POSTMan-Chrome-Extension#6094]
Description:
I am using Chromebook with Unix app and currently unable to pin Postman application and has no logo when in taskbar.

1. Install the Postman app.
2. Right click on the App when in Taskbar
3. The app doesn't display the logo. also "Pin to Taskbar" option is missing.

Expected behavior:
It would be helpful if I could pin it to the taskbar so that the app could be used frequently

Screenshots:
![app](https://user-images.githubusercontent.com/47771757/54527899-4eac7c80-49a1-11e9-9405-4c22f17e6e89.png)

![can-not-pin](https://user-images.githubusercontent.com/47771757/54527908-5409c700-49a1-11e9-8a3e-892a81e348e3.png)

App information:
 - App Type - Native App
 - Postman Version - 7.0.6
 - OS:  Chromebook (Pixel Slate) - Ubuntu - 64bit

**Comment by numaanashraf** [comment]
@Kurmavathar Official support for ChromeOS is still in the works. We'll look into this when we officially support ChromeOS (#5316)

**Comment by ttfreeman** [comment]
At least you are able to install. For me, the installation fails due to some mounting error.
