### ISSUE TITLE
timeout setting is failing requests

### ISSUE THREAD

**Issue by wilcsomanh** [a85/POSTMan-Chrome-Extension#6095]
On the Postman desktop app when the timeout in setting->general tab is set to a value > 0 then request are getting error:
***
Could not get any response
There was an error connecting to https://postman-echo.com/time/now.
Why this might have happened:
The server couldn't send a response:
Ensure that the backend is working properly
Self-signed SSL certificates are being blocked:
Fix this by turning off 'SSL certificate verification' in Settings > General
Proxy configured incorrectly
Ensure that proxy is configured correctly in Settings > Proxy
Request timeout:
Change request timeout in Settings > General
***

Posting the same request in a browser works fine.
When the timeout is set to 0 it works fine.

This used to work in previous version. Just updated to V7.0.6.
running windows 10 enterprise 1703 OS build 15063.1631

**Comment by codenirvana** [comment]
@wilcsomanh Are you getting `ESOCKETTIMEDOUT` error? Is the server taking longer than the specified timeout?

I tried to reproduce this issue by setting the timeout to `2000` and enabled local proxy and its working fine for me.

**Comment by wilcsomanh** [comment]
is the timeout setting changed from sec to ms? I have changed the setting from 20 to 20000 and it works now ! the ticket can be closed
