### ISSUE TITLE
Postman App doesn't open on Windows when Run in Postman button is clicked.

### ISSUE THREAD

**Issue by kuceram** [a85/POSTMan-Chrome-Extension#6096]
Please read through the [guidelines](https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues) before creating a new issue.

**Describe the bug**
Having a Run button in Postman (see [our documentation](https://docs.amio.io/docs/postman)) doesn't work properly on Windows. It opens a new tab but when you click on "Open with Postman for Mac" it doesn't launch the app. See following video: https://www.useloom.com/share/f51dcd74d556464b83c45fd7cc118169

**To Reproduce**
1. Go to https://docs.amio.io/docs/postman
2. Click on Run in Postman
3. Click on Postman for Windows
4. See that Postman is not opened even if it's installed.

**Expected behavior**
It should launch the app and import the collection.

**Screenshots**
https://www.useloom.com/share/f51dcd74d556464b83c45fd7cc118169

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version:  6.4.4 
 - OS: Windows 10
- Browser: Chrome 72.0.3626.121

**Additional context**
N/a

**Comment by Raja-Simha** [comment]
Hi @kuceram, thanks for reporting the issue.

I can launch the app but I see an error message saying collection does not exist. Please give us some time to investigate and we will get back to you.

Thanks,

**Comment by mjang** [comment]
I have the same issue in Linux, Ubuntu 18.04. (I also confirm this issue in Windows 10)

**Comment by arunwac** [comment]
Still experiencing the issue. I'm on Windows 10, Postman v7.12.0, tested on Chrome, Firefox, Edge and IE, After hitting Run in Postman, the Open with dialog appeared, clicked Postman for Windows and then Open Postman in the alert dialog, but nothing happened.

Had these 3 messages in console

```
button.js:1 stats.g.doubleclick.net/r/collect?v=1&aip=1&t=dc&_r=3&tid=UA-43979731-4&cid=1574622906.1566793902&jid=1476810413&_gid=908439954.1575027014&gjid=543225548&_v=j79&z=1623051988:1 GET https://stats.g.doubleclick.net/r/collect?v=1&aip=1&t=dc&_r=3&tid=UA-43979731-4&cid=1574622906.1566793902&jid=1476810413&_gid=908439954.1575027014&gjid=543225548&_v=j79&z=1623051988 net::ERR_BLOCKED_BY_CLIENT
Image (async)
ta @ analytics.js:16
wc @ analytics.js:25
ba @ analytics.js:25
Sa @ analytics.js:30
Ha.D @ analytics.js:28
pc.send @ analytics.js:64
X.b.<computed> @ analytics.js:40
Z.v @ analytics.js:72
Z.D @ analytics.js:71
N.N @ analytics.js:74
rc @ analytics.js:64
z @ analytics.js:64
(anonymous) @ analytics.js:74
(anonymous) @ analytics.js:74

```



```
button.js:1 Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'self' *.getpostman.com *.pstmn.io fonts.gstatic.com fonts.googleapis.com". Either the 'unsafe-inline' keyword, a hash ('sha256-9eGDHkgnSES6yRik/ys4Fsm7sdWV3CSR3YEr1e1CPVo='), or a nonce ('nonce-...') is required to enable inline execution.

injectCriticalStyles @ button.js:1
(anonymous) @ button.js:1
(anonymous) @ button.js:1

```



```
button.js:1 Uncaught Postman Run Button: Cannot create duplicate environment, my_environment_name, using env.create. Use env.replace instead.

(anonymous) @ button.js:1
setTimeout (async)
throwSafeException @ button.js:1
addUniqueEnv @ button.js:1
env.create @ button.js:1
M._pm @ button.js:1
(anonymous) @ button.js:1
(anonymous) @ button.js:1
(anonymous) @ button.js:1
```
![screensnip](https://user-images.githubusercontent.com/55536030/69868384-8fe68180-12cf-11ea-84b5-9a1964ef6960.png)

**Comment by av1m** [comment]
One solution is to use the site https://explore.postman.com/ in order to press the button "Run in Postman" which has worked from this site.

**Comment by gitThingsDone** [comment]
Hi @kuceram, I see you are using github to share your collection and environments now, 
Why don't you try publishing your collection using [postman documentation](https://learning.postman.com/docs/postman-for-publishers/public-api-docs/) 
you can also look into adding your API to the [postman API Network](https://learning.postman.com/docs/postman-for-publishers/api-network/add-api-network/) for more visibility

**Comment by DannyDainton** [comment]
Hey @kuceram 

Is this still an issue that you're facing? If not can we look to close this out now?

**Comment by DannyDainton** [comment]
Closing this one out, we can look to reopen if the issue persists.

**Comment by TooManyDots** [comment]
Issue persists.

**Comment by gitThingsDone** [comment]
@TooManyDots could you please share a link to the documentation this issue still persists for, I am unable to access the one linked on the original issue.
