### ISSUE TITLE
Variables not substituted in Collection Runner for nested objects

### ISSUE THREAD

**Issue by texaskiwi** [a85/POSTMan-Chrome-Extension#6098]
When populating a request body with variables from a CSV file in Collection Runner, the variables are not resolved when they are nested inside a property/object and enclosed in double quotes. The variables works when there are no quotes.

I'm seeing this issue in 7.0.6 desktop.   

It appears to happen when the object is nested

**Without quotes**
{"customerAccount":{"test": {{postcode}}  }}    ->    {"customerAccount":{"test": 77079  }}

**With quotes**
{"customerAccount":{"test": "{{postcode}}"  }}   ->   {"customerAccount":{"test": "{{postcode}}"  }}

**Not a nested object**
{"postcode":"{{postcode}}"}  ->  "postcode":"77079"

**Comment by vikiCoder** [comment]
Hi @texaskiwi 

I tried to reproduce this problem in the latest version(v7.1.1) of postman app, it is working as expected in it. Let us know if it still happens to you in the latest version otherwise we can close this issue.
