### ISSUE TITLE
[Bug][Markdown] Links won't open on same window

### ISSUE THREAD

**Issue by aeoris** [a85/POSTMan-Chrome-Extension#610]
When clicking on a method's doc markdown link, nothing happens. There's a console error, though:

```
Can't open same-window link to "https://www.google.com"; try target="_blank".      requester.html:1
```

**Comment by zhonghuasheng** [comment]
while, when we use `[Hello](url)`, this will go to the url in current tab, but I want to open in anther tab, how can i do this? i research that some one said using `[Hello](url){:target="_blank"}`，but it will render to text in Github
