### ISSUE TITLE
No Workspace Admin Privileges Post-Upgrade to RBAC

### ISSUE THREAD

**Issue by chrisdeso** [a85/POSTMan-Chrome-Extension#6101]
**Describe the bug**
After upgrading to version `7.0+` and migrating to RBAC – no one on the team has workspace admin rights.

**To Reproduce**
1. Migrate to version 7 of the app
2. Access default team workspace
3. Notice that no one has admin rights.

**Expected behavior**
After migrating to version 7 of the app, admin rights should retain previous settings. 

**Screenshots**
![image](https://user-images.githubusercontent.com/4734306/54639685-fab29e00-4a5b-11e9-929c-8944edabc0f5.png)

**App information (please complete the following information):**
 - App Type: Native app
 - Postman Version 7.0.6

**Additional context**
[Filed by Postman]

**Comment by preethammavin** [comment]
This issue has been fixed.
