### ISSUE TITLE
Response pane: search bar partially covers scroll bar

### ISSUE THREAD

**Issue by JP-from-Postman** [a85/POSTMan-Chrome-Extension#6103]
**Issue**
Opening the search bar in the response pane covers up the top of the scroll bar. For long responses (where the draggable part of the bar shrinks in size), this can make using the scroll bar difficult near to the top of the response.

**To Reproduce**
1. Send any request (preferably with a lengthy response body)
2. Open the search bar in the response pane
3. Observe search bar masking scroll bar
<img width="937" alt="Screen Shot 2019-03-19 at 3 39 54 PM" src="https://user-images.githubusercontent.com/43283131/54647249-02277680-4a5f-11e9-9425-f2aed55bf3cf.png">

**Expected behavior**
Search bar in response pane doesn't cover the scroll bar when opened

Mock example:
<img width="937" alt="mock" src="https://user-images.githubusercontent.com/43283131/54647328-43b82180-4a5f-11e9-876d-663b228c467f.png">

**App information (please complete the following information):**
 - App Type: Native app
 - Postman Version: v7.0.6
 - OS: macOS High Sierra 10.13.6

**Comment by kamalaknn** [comment]
@JP-from-Postman We made some improvements to the response viewer section in one of our past releases. The search bar does not overlap the scroll bar now.

Here's a screenshot of how it looks now 😄 
<img width="1051" alt="Screenshot 2020-05-17 at 9 09 21 AM" src="https://user-images.githubusercontent.com/8401064/82135246-1f500480-981e-11ea-8682-eca0700ca2b8.png">
