### ISSUE TITLE
Fail to sync and now won't enable sync

### ISSUE THREAD

**Issue by SteveHight** [a85/POSTMan-Chrome-Extension#6104]
## App Details:

```
Postman for Mac
Version 4.11.0
OS X 16.4.0 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there: Only noticed when I started using Postman on a separate machine and wanted to use a sync'd collection
 2. Expected behaviour: sync will say syncing and I can use collections anywhere I have logged into postman
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):

Console snippet:
8:56:56.50 - All data exported
requester.js:213963 Failure to sync._handleNewSyncResponse @ requester.js:213963
requester.js:208921 8:56:56.142 - Sync operation returned malformed message (no message.own): {"error":{"name":"rateLimited","message":"Rate Limit exceeded.","details":{"retryAfter":604800}}}error @ requester.js:208921
https://app.getsentry.com/api/60584/store/?sentry_version=7&sentry_client=r…0.0-beta.4%22%2C%22event_id%22%3A%22bc1ac7703ffe4255aa1309a4fa17adca%22%7D Failed to load resource: the server responded with a status of 429 (TOO MANY REQUESTS)
requester.js:212691 9:6:6.765 - All data exported
requester.js:213963 Failure to sync._handleNewSyncResponse @ requester.js:213963
requester.js:208921 9:6:6.194 - Sync operation returned malformed message (no message.own): {"error":{"name":"rateLimited","message":"Rate Limit exceeded.","details":{"retryAfter":604800}}}error @ requester.js:208921
https://app.getsentry.com/api/60584/store/?sentry_version=7&sentry_client=r…0.0-beta.4%22%2C%22event_id%22%3A%221ddef83a37c541449fd1a6633211dc2d%22%7D Failed to load resource: the server responded with a status of 429 (TOO MANY REQUESTS)
 
4. Screenshots (if applicable) ... in link - how do I attach here?

**Comment by SteveHight** [comment]
Just checked, logging out then logging back in results in the sync error and all my collections gone

I get the same sync problems in the office and at home.

**Comment by numaanashraf** [comment]
@SteveHight Are you running the same app version on both the devices? Please share these app versions. You can find them under Settings > About

**Comment by SteveHight** [comment]
@numaanashraf 
The master Postman is on my MAC and is Version 4.0.0-beta.4 (4.0.0-beta.4) (MAC version 10.14.3)  This where I have created the collections and where postman that fails to sync.

The other Postman is on a windows 10 PC the Postman version is 7.0.6 win32 10.0.17134 / x64

On the PC the sync button is orange, under collections I see my collection names, but I do not have any API details

**Comment by SteveHight** [comment]
Please close this case.

Despite version 4.0.0-Beta.4 thinking that there was no upgrade beyond that, deleting that version I found that MAC had a version 7.0.6
Downloading that - sync seems to be working now.

If anyone reads this make sure you save your data before deleting Postman, else your collections will be gone forever.  See Spanner > settings > Data > download.
Once re-installed you can import the file you saved (downloaded)

**Comment by SteveHight** [comment]
Done (solved)
