### ISSUE TITLE
GitHub integration not syncing data

### ISSUE THREAD

**Issue by cyrielle-hada** [a85/POSTMan-Chrome-Extension#6105]
**Describe the bug**

- Although the GitHub integration was set up correctly without any errors, the collections aren’t synchronized to the GitHub repository. 
- Some changes to some endpoints have been saved, but it didn’t trigger anything.

**To Reproduce**
1. Set Up the integration in the web dashboard following the guidelines https://learning.getpostman.com/docs/postman_pro/integrations/github/
2. Open GitHub repository
3. Not seeing any `Postman Collections` folder and commits.

**Expected behavior**
See an initial commit come into GitHub as soon as the integration is set up. 

**App information (please complete the following information):**
 - App Type: Native App 
 - Postman Version 6

**Additional context**
- No directory has been specified in the configuration (a default directory called Postman Collections should be created).
- Removing the integration and add it again didn’t help.
- The team is not using on-prem or self-hosted GitHub.
- The content that needs to be pushed to GitHub comes from a Team Workspace.

**Comment by a85** [comment]
@cyrielle-hada Can we add more details to this please?

**Comment by dmboucher** [comment]
Please let me know whatever details you need.  Some additional info:
Repo:  https://github.com/ssbcode/postman-ssb-team-workspace
This is a private repo.  @a85, I added you as a reader on the repo so you should be able to see it.
Here are some screen shots of the integration configuration settings.
![screen_shot](https://user-images.githubusercontent.com/9728334/54705250-f93bb100-4b01-11e9-90e0-86bff6479696.png)
![configured_properly](https://user-images.githubusercontent.com/9728334/54705289-12446200-4b02-11e9-9b9c-30646874c619.png)

**Comment by dmboucher** [comment]
@ankitjaggi & @kartikjain26 - I added you as readers on our private GitHub repo (https://github.com/ssbcode/postman-ssb-team-workspace) to better assist with troubleshooting.  Thank you for your help!

**Comment by dmboucher** [comment]
Also... if there were an option to sync all collections within a shared team workspace, that would be awesome.  It would be great to **not** have to add specific integrations for each collection.  Just a thought (but out of scope for this issue).

**Comment by emeryowa** [comment]
I have a similar problem. When I fork a collection, apply changes and then merge the changes to the original collection the changes do not get synced with the Github repository. I have to make an additional change in the collection itself, save and then all changes will get synced.

The syncing works fine when applying changes in the collection itself but not when merged.

**Comment by hammbino** [comment]
I am also experiencing this bug. I am syncing to a custom GitHub repo.

**Comment by lorna-bevingtongrant** [comment]
Also having this same issue. Does not sync when we merge any changes form our team workspace in to Github repository.
Very frustrating and something that I thought would be easy thing!

**Comment by lorna-bevingtongrant** [comment]
Hi, Is there an update on when this may get fixed?
Thanks

**Comment by cyrielle-hada** [comment]
Below are the potential causes that need to be verified and actions to take if the integration doesn't sync the content to the GitHub repository. 

1. The GitHub integration is added to the same workspace as the content that needs to be pushed to the GitHub repo.
2. The right option has been chosen between `Backup your Postman Collections to GitHub` and `Backup your Postman Collections to GitHub on a custom domain` when setting up the integration. 
3. Initialize the repo with a `Readme.md`. Check the box `Initialize this repository with a README` and then configure a new integration on it.
4. The scopes `user` and `repo` are selected when creating the access token on GitHub. 
5. The branch specified in the setup is existing on Github. Note: the integration doesn't create one if the branch doesn't exist.
6. The enterprise version of GitHub is on-prem / self-hosted > can be a firewall issue ([GitHub issue #5741](https://github.com/postmanlabs/postman-app-support/issues/5741)) 
7. The user has enough permissions to push to that branch.
8. The integration was reinstalled several times.

Any other potential reasons that can be causing this issue @ankitjaggi, @kartikjain26 ?

**Comment by dmboucher** [comment]
I've done all of the above:
1. Yes.  `SSB Team Workspace`
2. I'm using `Backup your Postman Collections to GitHub` (our url is:  https://github.com/ssbcode/postman-ssb-team-workspace) - no custom domain
3. Yes. I tried regenerating the access token.  Same behavior.
4. Yes.  `master` branch.
5. No.  We do not have on-prem / self-hosted.  We're just using a private GitHub repo.
6. Yes.  My user created the repo and has full `Admin` privileges to the repo.
7. Yes.  I've deleted everything and retried everything several times at this point.

:(

**Comment by a85** [comment]
@dmboucher We were in the midst of a big release. Sorry about the delay on this. The team is looking into it. We need to figure out through service logs why this is not working for you.

**Comment by kartikjain26** [comment]
@dmboucher Can you also just try one more step -> while creating a new repo, could you initialise the repository with a Readme.md by checking this box in screenshot and then configure a new integration on it.

![Screenshot 2019-05-16 at 3 03 11 PM](https://user-images.githubusercontent.com/26088676/57843406-da992400-77eb-11e9-86ea-355a9ae659b0.png)

**Comment by dmboucher** [comment]
That is how I initialized this repo. That's part of our process for all new
repo's. Do you want me to do that again?

**Comment by JP-from-Postman** [comment]
Another occurrence of this has been reported via Support.

**Comment by dmboucher** [comment]
Excellent.

Well... not excellent... but I'm glad I'm not the only one!  :)

I haven't had time to try to redo everything.  Please let me know if you
find out anything or if you need any elevated permissions to our repo.

Thanks.

-- Dave

**Comment by JP-from-Postman** [comment]
@ankitjaggi @kartikjain26 

One of the users who reported this via support followed up with some findings:

In the workspace failing to sync via the integration, one of their Collections contained saved examples. When exported, the Collection's file size was 82MB. Removing the saved examples allowed the integration to resume syncing it.

**Comment by stcalica** [comment]
Another occurrence of this has been reported via Support.

**Comment by davidh-zoosk** [comment]
I am experiencing the same issue while trying to sync to a custom github domain. The integration is created without any errors, but no data is synced.
Created a new repo from scratch, attempted the integrations, same result.
Then attempted the integration on github.com (non-custom domain) and the sync occurred instantly without issue.

**Comment by cyrielle-hada** [comment]
_Filed on the behalf of a user reporting via the Support_

**Describe the bug**
The collection is not synced to the GitHub repository. 

**To Reproduce**
1. The GitHub integration used to be working.
2. Some changes for the key and Collection location were done.
3. The old integration was deleted.
4. New integration was added. 
5. The collection is not synced to the repo. 
Steps to reproduce the behavior:

**Troubleshooting** - all points listed [here](https://github.com/postmanlabs/postman-app-support/issues/6105#issuecomment-490432796) were verified.
- The team is using the Github cloud, nothing on-premise.  
- The user has full access to push in the repo.
- The token generated has access to user and repo. 
- SSO enabled on the token to give an enterprise access. 
- The repo and branch are already created with readme.md inside it.

**Comment by ecournane** [comment]
I have the same issue, my collections are only being saved if I modify them.  Otherwise they are not synchronized.  Should they be synchronized and this is a defect I am experiencing?  Or is this a feature that needs to be added?

**Comment by TurboFry3** [comment]
Am I missing something..  I do not see an option to backup Collections.  only the sync API.  
![image](https://user-images.githubusercontent.com/55706035/78606463-5d273980-782b-11ea-9add-42bb022fef74.png)

**Comment by krgaurav29** [comment]
Is this integration option Disabled now?
as the only option i can see for github is "Back up collections and sync API schemas to your GitHub repositories"
![image](https://user-images.githubusercontent.com/60217997/79725867-7f2eba80-8307-11ea-979a-b433e5c372ca.png)

**Comment by TurboFry3** [comment]
> Is this integration option Disabled now?
> as the only option i can see for github is "Back up collections and sync API schemas to your GitHub repositories"
> ![image](https://user-images.githubusercontent.com/60217997/79725867-7f2eba80-8307-11ea-979a-b433e5c372ca.png)

I ran into the same thing.  Apparently this is now only available with a paid subscription

**Comment by preethammavin** [comment]
@TurboFry3 @krgaurav29 Hey you should be able to click on view details to be able to sync you API schemas from Github to Postman.

**Comment by TurboFry3** [comment]
> @TurboFry3 @krgaurav29 Hey you should be able to click on view details to be able to sync you API schemas from Github to Postman.

I am not looking to sync API schemas.  I am looking to backup my postman collections/tests which used to be available free, but now is only supported with paid accounts (team or better)

https://learning.postman.com/docs/integrations/github/

"Syncing API Schemas on GitHub is available with a free Postman account. You can back up your collections to GitHub on Postman Team, Business, and Enterprise plans."

**Comment by abhijitkane** [comment]
Everyone - we've updated the user-experience to include the run log for the last few executions of the integration. This can be accessed by clicking the status (Created / Active) in your integration listing.
<img width="1208" alt="Screenshot 2020-07-01 at 12 34 54 PM" src="https://user-images.githubusercontent.com/681190/86213389-4593ee80-bb97-11ea-907e-0cf7d6f4dc45.png">

This should bubble up any problems with the integration or its configuration.

**Comment by abhijitkane** [comment]
Closing this issue for now. Feel free to reopen if further issues are seen during syncing.

**Comment by shulst** [comment]
Still having this issue. When you add a new request to the api it syncs, but if you just add tests it does not sync.

**Comment by ghost** [comment]
Same is happening for us, it syncs the first time then never does again.
I don't really trust sync on Postman at all, our experience is terrible.

**Comment by 5thdimensional** [comment]
In September, a new bi-directional git integration solution was released that supersedes the previous git integration for syncing APIs and collections associated with APIs. We highly encourage switching over to that integration since it resolves this particular issue. For more info, check out this help article: https://learning.postman.com/docs/designing-and-developing-your-api/versioning-an-api/#using-an-external-git-repository

**Comment by dcstamps** [comment]
All my collections stopped syncing since early this year.  No matter how many times I remove and then re-add the integration, it still won't sync.  Not useful to our organization at all now, we plan to look for another test tool.
