### ISSUE TITLE
Allow to modify pm.info.iteration and possibly other pm.info variables

### ISSUE THREAD

**Issue by LegendForHire** [a85/POSTMan-Chrome-Extension#6107]
I'm having an issue with organizing my test flow within a collection. the issue is that every test does not need to run for every iteration. setNextRequest() fixes a majority of this and allows me to loop through a particular solution, but instead of having to write my own data reader for the csv I am using, I would instead like to be able to manually update the current iteration, and us
postman's own csv reader. pm.info.iteration is currently read only, and creating a way to write to that variable would give me total control of test flow in a really elegant way. Currently, I am having to break up a lot of related tests into multiple collections in order to not run tests multiple times unnecessarily, and I would like to be able to run one collection for all related tests.

**Comment by abhijitkane** [comment]
@LegendForHire A quick workaround would be to add a bit of code in the collection-level script. You can read from pm.info.iteration and set whatever environment variables you need. These will then be available in the request.

Since collection-level scripts are run before every request, you only need to write your code in once place.

**Comment by LegendForHire** [comment]
Yeah, that wont really solve the issue. that involves code running before EVERY script. i want to be able to hop around using sendNextRequest and using the iteration modification to keep track of where i am and what data i'm using, so that no piece of code gets run redundantly while staying in the same collection. currently the only way for me to be able to do something like this, is to write my own csv reader.

**Comment by shamasis** [comment]
A “goto” like behaviour around iteration would not be feasible to work on. postman.setNextRequest itself hasn’t been ported to pm.* APIs for this reason. 

I too suggest that, for now, use what @abhijitkane suggested.

The good news though is that we are working on a more flexible collection running mechanism that achieves the concept of iteration using a sort of map-reduce feature on data files. That would eventually be the solution. But this is supposed to be available to test drive in mid term.

Closing the issue. Will update this issue when we have something to discuss around the new collection runner

**Comment by LegendForHire** [comment]
Thanks for the heads up on the new feature. I'll probably just have a setup script, that functions by reading through all the iterations and creates my own data map. Thanks for the info!
