### ISSUE TITLE
Add "open all" to Collections.Folders context menu

### ISSUE THREAD

**Issue by rosponda57** [a85/POSTMan-Chrome-Extension#6108]
When You have over a dozen requests stored in a collections folder, to open all of them You have to double-click on each one.

It would be great o have an "open all"  position in then Collection Folders context menu :)

![image](https://user-images.githubusercontent.com/41154552/54690399-98bc6c00-4b21-11e9-8217-7244f8d6c254.png)

**Comment by TonyTrupp** [comment]
I was looking for this feature today too

**Comment by giridharvc7** [comment]
Thank you for your patience, We've introduced this feature in v10.13. You can now use `Option+Click` to expand and collapse all children of an element. This work for collections and folders. 

https://user-images.githubusercontent.com/1040583/232968843-ecd9e63c-3d65-4bee-ae12-fba2dd55107e.mov


Please give this a try and let us know what you think
