### ISSUE TITLE
The .localhost TLD doesn't resolve unless explicitly defined in hosts file

### ISSUE THREAD

**Issue by theNailz** [a85/POSTMan-Chrome-Extension#6109]
**Describe the bug**
The .localhost TLD doesn't resolve unless explicitly defined in hosts file.

**To Reproduce**
1. Run a local webserver
2. Execute a request in Posman to http://mydev.localhost/ (ERROR)
3. Add `127.0.0.1 mydev.localhost` to your hosts file (C:\windows\system32\drivers\etc\hosts)
4. Retry step 2

**Expected behavior**
Any domain ending in .localhost should resolve to 127.0.0.1, like Google Chrome does, without being explicitly defined in the hosts file.

**App information (please complete the following information):**
 - Native App
 - Postman Version 7.0.6
 - OS: win32 10.0.17763 / x64

**Comment by sixcorners** [comment]
Here is an IETF proposal that describes the behavior: https://tools.ietf.org/html/draft-west-let-localhost-be-localhost-06

**Comment by codenirvana** [comment]
Duplicate of #2638
