### ISSUE TITLE
Cannot export results from collection runner

### ISSUE THREAD

**Issue by sujayvenaik** [a85/POSTMan-Chrome-Extension#6110]
**Describe the bug**
Cannot export results from the collection runner

**To Reproduce**
Steps to reproduce the behaviour:
Select any collection
Press Run
Go to collection runner 
Try to export results.
See the error in the terminal

**Expected behaviour**
Should have exported the results

**Screenshots**
![Kapture 2019-03-20 at 20 59 09](https://user-images.githubusercontent.com/11532114/54697377-73e0ec80-4b53-11e9-8855-f867a7ddbcd9.gif)

**App information (please complete the following information):**
 - App Type Native App
 - Postman Version 7.0.6
 - OS: macOS High Sierra 10.13.6

[Reported Internally]

**Comment by codenirvana** [comment]
Fixed in the latest version of the Postman app (v7.6.0).
