### ISSUE TITLE
Zoom not working in Postman Console

### ISSUE THREAD

**Issue by numaanashraf** [a85/POSTMan-Chrome-Extension#6111]
**Describe the bug**
Zoom in/out is not working on Postman Console window

**To Reproduce**
1. Open Postman Console
2. Try zooming via keyboard shortcut or menu actions under (View) [Cmd +/-]
3. Notice that view does not zoom

**Expected behavior**
View should zoom in/out as expected

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version [e.g. 7.0.6]
 - OS: macOS

**Comment by shamasis** [comment]
This has been fixed in production.
