### ISSUE TITLE
Better token management

### ISSUE THREAD

**Issue by rotorboy** [a85/POSTMan-Chrome-Extension#6115]
Currently, each access token must be removed individually, There should be a "select all / delete all" capability to remove at once.

Even better: have an auto-remove feature that will set a timeout to remove expired token based on their validity duration as contained in "expires_in" field returned with the token.

Better still: have an "auto-renew" feature that both deletes old token upon expiry and requests new one based on current values in token request block, and "sets" that token.

**Comment by abhijitkane** [comment]
@rotorboy What screen of the web dashboard/app are you referring to? https://go.postman.co/settings/me/sessions has a Revoke All Sessions button.

**Comment by rotorboy** [comment]
I'm referring to the “manage access tokens” panel, under the “authorization” tab, in the edit feature for editing a collection. 

Token “management” is greatly exaggerating what this panel does. It enables getting one token at a time, and removing one at a time. Hardly comprehensive “token management"

There is no way to remove all old tokens at once. Each token must have its garbage can clicked individually. There should at LEAST be a “select all” “delete selected” capability so all old tokens could be removed. But, ideally there would an “auto-remove / auto-renew” capability that would track when a token expires, remove it, then get a new one, and set “use”, ALL without the user having to manually refresh token after each expiration and then having to remove each token individually.

Also, related, this is the feature where “token name” field does not properly support variable substitution… e.g. having the token name be:  dev {{$timestamp}}

**Comment by balane** [comment]
I wish there was a way to upvote this. Token management is a real pain currently.

**Comment by rotorboy** [comment]
I’m not the first to have an issue here. Postman has been promising better token management for over a year now and so far nothing has changed so I’m not sanguine that it is prioritized on dev feature list. 

-Avi

**Comment by stacey-sloth** [comment]
+1

**Comment by mccannt** [comment]
Closing this issue as it has now been resolved.
Please feel free to reopen with the steps to reproduce if the issue persists.
