### ISSUE TITLE
Monitor name isn't visible in the integration listing

### ISSUE THREAD

**Issue by ash007-postman** [a85/POSTMan-Chrome-Extension#6116]
**Describe the bug**
Don't see Monitor in Configured Integrations"

**To Reproduce**
1.  Navigate to the Postman Integrations Tab
2. Click on Configured Integration
3. Showing a blank list under Monitor column

**Expected behavior**
Monitor name should be visible in the integration listing

<img width="535" alt="Screenshot 2019-03-21 at 12 05 41 PM" src="https://user-images.githubusercontent.com/41741228/54736559-b2b58780-4bd1-11e9-98bb-cc1b4b1d2b95.png">

**App information:**
- App Type - Native App
- Postman Version - 6.7.4
- OS: macOS

**Comment by abhijitkane** [comment]
Reported fixed
