### ISSUE TITLE
Issue duplicating collections in Postman app

### ISSUE THREAD

**Issue by Raj-postman** [a85/POSTMan-Chrome-Extension#6117]
**Describe the bug**
When I try to duplicate the collections using the ellipses next to the collection name, there is no duplicate of the collection that I see.

**Steps to reproduce the behavior:**
1. Open the Postman App
2. Click on ellipses next to the collection name, or either after expanding the collection
3. There is no duplicate of the selected collection

**Expected behavior**
Be able to create the duplicate of any selected collection.

**Screenshots**
![duplicate](https://user-images.githubusercontent.com/47771757/54605705-de206100-4a6f-11e9-92fb-12377e9e3fd5.png)

**App information:**
 - App Type - Native App
 - Postman Version - 7.04
 - OS: macOS

**Comment by abhijitkane** [comment]
@Kurmavathar Can you check the logs (View > Developer > Current View) for any errors when you try this?

**Comment by Raj-postman** [comment]
@abhijitkane This is one of the error among similar fields as listed in following .logs file:
1) In the file **renderer-shared.log** - 

[34746][1551947691768][shared][error]["BaseSyncTimeline: Error in environment:5569996-9dde6f1d-d532-42c8-8d5f-0b460895c65a /sync response"]

2) In the file **pluginHost.log** - 
open '/Users/vignesh-4641/Library/Application Support/Postman/plugins/postman.openApi/version.json'","stack":"Error: ENOENT: no such file or directory

3) in the file **main.log**-
{"name":"Error","message":"Setting cookie failed","stack":"Error: Setting cookie failed"}]
[29243][1539165946335][main][error]["CookieManager~pushCookies - Error storing cookies in Electron store"

**Comment by numaanashraf** [comment]
@Kurmavathar Please share any errors you see in `renderer-requester.log` and also under Console in (View > Developer > Current View)?

**Comment by Raj-postman** [comment]
@numaanashraf There are no errors seen in the  `renderer-requester.log`

**Comment by numaanashraf** [comment]
@Kurmavathar would it be possible to send us a screenshot of Console in (View > Developer > Current View) after you try duplicating a collection?

**Comment by svkaizoku** [comment]
The same error occurred to me also . i have attached a zip with the log files
[logs (1).zip](https://github.com/postmanlabs/postman-app-support/files/3022068/logs.1.zip)

**Comment by harryi3t** [comment]
@Kurmavathar @svkaizoku 
Could you share us the screenshot showing any error from the DevTools Console using (View > Developer > Current View) after you try duplicating a collection?

![image](https://user-images.githubusercontent.com/5207331/55533772-021aae00-56d0-11e9-84a6-dfdb8b344c40.png)

**Comment by numaanashraf** [comment]
Thank you for your issue! @Kurmavathar @svkaizoku With only the details that is currently in the issue, we don't have enough information to reproduce, debug and fix this issue. We are going to close this 
now but don't hesitate to reach out if you have more information for us, we'll be happy to reopen the issue.
