### ISSUE TITLE
Importing a backup file on the Chrome app shows all the collections while the native app shows only one

### ISSUE THREAD

**Issue by labifrancis** [a85/POSTMan-Chrome-Extension#6118]
**Describe the bug**
Importing the backup file on the Chrome app shows all the collections while the native app shows only one

**To Reproduce**
1. Go to the Native app and import the backup file
2. Go to the Chrome app and import the same file

**Expected behavior**
The number of collections in the Native app and Chrome app should be the same

**Comment by preethammavin** [comment]
@labifrancis is it possible to share the backup file to further investigate this?

**Comment by labifrancis** [comment]
@preethammavin I provided it internally on JIRA

**Comment by SamvelRaja** [comment]
@labifrancis  Could you provide us from which app this data has been backedup?
Native or chrome app?

**Comment by labifrancis** [comment]
Chrome app.

**Comment by DannyDainton** [comment]
Closing this issue as it has now been resolved.

Please feel free to reopen with the steps to reproduce if the issue persists.
