### ISSUE TITLE
ADFS SSO integration not working with the encryption key.

### ISSUE THREAD

**Issue by harsh-reality** [a85/POSTMan-Chrome-Extension#6119]
**Describe the bug**
The ADFS SSO integration does not work when the encryption key is put in alongside other configuration settings. The SSO integration works fine otherwise.

**To Reproduce**
Follow the steps mentioned in the documentation here- https://learning.getpostman.com/docs/postman_enterprise/sso/microsoft_adfs/ and the integration does not work with the encryption key but when it's not entered, it works.

**Expected behavior**
The integration should work even with the encryption key.

**Additional context**
@elssar is trying to reproduce this behaviour and investigating further to find out if it's a configuration error or something more!

**Comment by preethammavin** [comment]
@harshachelle , we were not able to reproduce the issue.
