### ISSUE TITLE
Published documentation for a deleted collection should be available after restoring the collection from trash

### ISSUE THREAD

**Issue by labifrancis** [a85/POSTMan-Chrome-Extension#6124]
**Is your feature request related to a problem? Please describe.**
When a collection with a published documentation is deleted and restored back, the link to the published documentation becomes unavailable

**Describe the solution you'd like**

The link to the documentation for a deleted collection should be available together with the content after the collection is restored.

**Comment by preethammavin** [comment]
I understand the use case, but deletion of a collection would mean deleting an entity and its relation. 

To restore the link back to all the elements would nearly be impossible as a product behaviour with the complexity it could unload on to the user. This is said keeping in mind elements (Documentation, Monitor and Mocks & in future more) are built on collection.

We will revisit it as a feature in the future.
