### ISSUE TITLE
Single Quotes Converted to ASCII on Desktop Postman 

### ISSUE THREAD

**Issue by piercena** [a85/POSTMan-Chrome-Extension#6126]
**Describe the bug**
When including single quotes in a URL, the single quotes are replaced with the ASCII value of %27. This issue is the same for double quotes which are replaced with %22. Postman for Chrome does not experience this issue. 

**To Reproduce**
1. Go to Postman for Desktop
2. Make a request to a URL and include single quotes
3. Observe server logs which output the request/response and note the conversion to ascii characters.

**Expected behavior**
When single quotes are used in the url, the server receives single quotes. 
When double quotes are used in the url, the server receives double quotes.

**App information (please complete the following information):**
 - App Type: Desktop App
 - Postman Version: 7.0.6 
 - OS: Mac 10.14.3

**Additional context**
The same issue can not be reproduced in Postman Chrome App, Version 5.5.4. With the chrome app being deprecated it would be helpful to have parody in behavior with that so the desktop version does not experience this issue. Worth noting is that escaping the single or double quotes does not solve the problem either.

**Comment by snsakib** [comment]
having the same issue on windows desktop app v7.9.0

**Comment by codenirvana** [comment]
The single quote in the URL **path** is converted to `%27` in Postman.
However, double quotes are converted to it's encoded value `%22` in both Postman as well as browser (not in curl 😕).

**Comment by vikiCoder** [comment]
Hi, we have added a request option to turn off automatic URL encoding. You can turn that option off to stop encoding all characters (including single and double quotes). This option is available in the latest [Postman Canary](https://www.postman.com/downloads/canary) release (version 7.20.0-canary03). You can see more details about the fix at #8154

![image](https://user-images.githubusercontent.com/16588032/76196985-4fbd6600-6211-11ea-836b-926ee44fc969.png)

**Comment by codenirvana** [comment]
As mentioned in https://github.com/postmanlabs/postman-app-support/issues/6126#issuecomment-596403407, the new request setting is now available in the latest version of the Postman app (v7.20.0) once you enable the "Use next generation URL processing" setting as mentioned in #8154.

Feel free to leave your feedback at #8154 or reopen this thread if the issue persists.
