### ISSUE TITLE
Mock server: regular response times up to 30 seconds

### ISSUE THREAD

**Issue by JP-from-Postman** [a85/POSTMan-Chrome-Extension#6127]
Please read through the [guidelines](https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues) before creating a new issue.

**Describe the bug**
Response times for two Mock Servers are frequently in excess of 10 - 30 seconds.

Both mock servers only contain a single example response. Requests being sent to mock server have only a very small JSON body as the payload.

**App information (please complete the following information):**
 - App Type: Native app
 - Postman Version: v7.0.6
 - OS: MacOS

**Additional context**
See internal notes

**Comment by JP-from-Postman** [comment]
@ratpik @preethammavin Do we have a current status / timeline for this issue?

**Comment by ratpik** [comment]
@JP-from-Postman - We have pushed out a fix which should reduce the frequency of this issue. We are working on a fix that will resolve this issue. We plan to resolve this before the end of this week.

**Comment by preethammavin** [comment]
@JP-from-Postman the issue has been resolved, closing the thread for now. Feel free to reopen it if it occurs again.
