### ISSUE TITLE
Error running scripts: SyntaxError | Unexpected token :

### ISSUE THREAD

**Issue by chitti-cc** [a85/POSTMan-Chrome-Extension#6128]
I am getting the  **SyntaxError | Unexpected token:** all the time for the GET request. But the response of the service is valid JSON. I did not add any test scripts for this still it is giving me the error.  

Here is the JSON response
`{
  "code" : 0,
  "requestId" : "sdfafafsaf",
  "timestamp" : 1553212129471,
  "values" : [ "xxx", "yyyy", "zzzz" ]
}`

![Screen Shot 2019-03-21 at 5 47 05 PM](https://user-images.githubusercontent.com/12688339/54792646-2bc9d480-4bfc-11e9-9bce-0a32e209a26b.png)

![Screen Shot 2019-03-21 at 5 53 51 PM](https://user-images.githubusercontent.com/12688339/54792821-fd98c480-4bfc-11e9-9735-2da138613189.png)

**Comment by abhijitkane** [comment]
@chitti-cc Can you check if:
1. There are any folder- or collection- level test scripts that might be doing a JSON.parse?
2. The "raw" mode in the response has the same JSON response. (Certain strings like `while(1);` are stripped in the pretty mode)

**Comment by chitti-cc** [comment]
Thanks, @abhijitkane ..I did not realise there are some tests are in collection level.
