### ISSUE TITLE
Unable to perform team-level actions (inviting etc.) after accepting an invitation to join the team

### ISSUE THREAD

**Issue by abhijitkane** [a85/POSTMan-Chrome-Extension#6129]
Discovered internally at Postman. See linked JIRA for details.

**Comment by a85** [comment]
@abhijitkane Can we have more details on this ticket itself?

**Comment by abhijitkane** [comment]
The user in question was part of a team before, then left the team, then joined it again. After re-joining, the user is unable to send invites, change billing details for the team even though the invitation used had these roles.

**Comment by a85** [comment]
Ok. I'd like bug reports to be filed in a way in this tracker that it can be replicated or at least can be tracked. If I were reviewing this as a developer, I'd just close this issue right away purely looking at this ticket.
