### ISSUE TITLE
A hyphen at the beginning of token causes a "Could not get any response"

### ISSUE THREAD

**Issue by tanoojoy** [a85/POSTMan-Chrome-Extension#6130]
Please read through the [guidelines](https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues) before creating a new issue.

**Describe the bug**
When authenticating using a Bearer + token, everything worked fine until today one of the tokens started with a "-". I got a "no response" from postman even after checking spellings/parameters/syntax. I tried the same API on swagger and it worked. So, I knew the issue was from Postman. I realised exactly what it was after the token expired and I had to use the new one.

**To Reproduce**
1. Trying testing any API that requires Authentication (preferably Bearer + token)
2. Have that token to start with a "-"
3. Get a response from that API
4. It won't even say there's an error in the syntax, or 401 unauthorised. It just says no response.

**Expected behavior**
Having a "-" at the beginning of a token is normal, so it should have properly accepted it and given a response

**App information (please complete the following information):**
 - Sandbox marketplace on www.arcadier.com
 - Postman Version [e.g. 6.7.4]
 - OS: Windows 10

**Comment by codenirvana** [comment]
@tanoojoy It's working fine (attached screenshot).

Can you share more information to reproduce this issue? Is there any error message in the Postman Console?

<img width="902" alt="Screenshot 2019-03-22 at 2 12 01 PM" src="https://user-images.githubusercontent.com/4865836/54810818-0e087800-4cad-11e9-81ea-5466bf61295b.png">

**Comment by tanoojoy** [comment]
@codenirvana I realised the mistake was a "next line" at the end of my token, which got on postman when I  copied my token from a text editor and pasted on postman. Sorry for the trouble.
