### ISSUE TITLE
7.0.6 SSL Handshake failure with verification turned OFF

### ISSUE THREAD

**Issue by RB-Develop** [a85/POSTMan-Chrome-Extension#6131]
**Describe the bug**
A secure HTTPS API I'm working on requires a client certificate to be presented. On my development environment I'm using a self-signed certificate both for the server certificate as for the client certificate. With SSL verification turned off this did not seem to be an issue until today. Currently I'm running into an SSL handshake issue, preventing the API call from being made and a result to be produced. The console shows the following:

```
Error: write EPROTO 4708750784:error:14094412:SSL routines:ssl3_read_bytes:sslv3 alert bad certificate:../../vendor/node/deps/openssl/openssl/ssl/s3_pkt.c:1494:SSL alert number 42 4708750784:error:1409E0E5:SSL routines:ssl3_write_bytes:ssl handshake failure:../../vendor/node/deps/openssl/openssl/ssl/s3_pkt.c:659:
```

**To Reproduce**
1. Use a HTTPS API that serves a self-signed certificate and that requires a client certificate.
2. Use a self-signed client certificate.
3. Turn SSL verification OFF.
4. See if you get a response. I do not and I see a handshake error in the Postman console.

**Expected behavior**
It should ignore the invalidity of the certificates and produce a response.

**App information (please complete the following information):**
 - Native app
 - Postman Version 7.0.6
 - OS: Mac OSX Mojave 10.14.3

**Comment by RB-Develop** [comment]
Seems like I jumped the gun. Turns out the issue went away when I also provided a .key file. I cannot remember having to do this in the past, but there we go. Closing the issue.

**Comment by griddyphillip** [comment]
This doesn't seem like the issue is actually fixed. You still had to provide a .key file even though your SSL verification is OFF
