### ISSUE TITLE
Can’t restore deleted sources from Trash

### ISSUE THREAD

**Issue by cyrielle-hada** [a85/POSTMan-Chrome-Extension#6135]
**Describe the bug**
Unable to restore a collection from the trash https://app.postman.co/me/trash
Upon clicking on restore, an error message appears says “Something went wrong”

**To Reproduce**
1. In the Web Dashboard, go to the trash https://app.postman.co/me/trash
2. Hover on the collection to be restored and click restore
3. Select the workspace and click restore

![Screenshot from 2019-03-22 11-27-14](https://user-images.githubusercontent.com/47351631/54840211-6434e580-4cc4-11e9-8805-b2a587ea6b7c.png)

**Expected behavior**
See successful message saying: collection restored. 
<img width="532" alt="Screen Shot 2019-03-22 at 16 53 50" src="https://user-images.githubusercontent.com/47351631/54840176-4bc4cb00-4cc4-11e9-8121-2bbd93bbcadc.png">

**App information (please complete the following information):** 
 - Linux, Chrome, Postman Version 7.0.6

**Comment by abhijitkane** [comment]
@cyrielle-hada All dependent issues for this are closed.

**Comment by cjlotz** [comment]
How is this fixed?  We have the same issue?  How do we go about restoring the deleted collection

**Comment by cjlotz** [comment]
@abhijitkane Can you please confirm whether this issue has been addressed.  We are running the latest version of Postman.  One of the team members accidentally deleted the Team Collection and he is unable to restore the Collection.  As soon as another Team Member opens Postman, the collection gets deleted from their Workspace as well.  How do we fix this?

**Comment by preethammavin** [comment]
@cjlotz can you write to us at help@getpostman.com, would need further details to look at it. It has been fixed for root cause we saw. Would be good have more details to debug your issue.

**Comment by cjlotz** [comment]
@preethammavin  Done.  While you are investigating, is there anyway to get a backup copy of the collection?

**Comment by preethammavin** [comment]
if the collection is deleted, the only was is through the restore process. we will look at getting this done ASAP.

**Comment by cjlotz** [comment]
@preethammavin Thanks for the reply.   

We managed to get a developer who had an up to date version of the collection as of this morning.  He disconnected from the internet so that the sync does not remove the collection from his work space.  He then imported the collection into the Team WorkSpace.  The collection is now again visible to the Team, but ii is however locked for everybody.  How do we go about getting it unlocked?

**Comment by preethammavin** [comment]
@cjlotz since you have the json, can you import it into the personal workspace and share it to the team workspace? or Duplicate the collection in the same workspace should give you edit role.

**Comment by preethammavin** [comment]
@cjlotz we dont see any discrepancy in error logs on our side , can you ask the developer to assign the team/ specific users the editor role so that rest of the team can contribute it to.
