### ISSUE TITLE
Local data lost/inaccessible after upgrading to v7

### ISSUE THREAD

**Issue by JP-from-Postman** [a85/POSTMan-Chrome-Extension#6137]
Please read through the [guidelines](https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues) before creating a new issue.

**Describe the bug**
Some users not signed in prior to upgrading to v7.x are losing their local data after migrating. For some users, this seems to occur after migrating, then creating a new Postman account and signing in for the first time.

For some users that were logged in before upgrading, content stored by sync still exists in the cloud, but doesn't populate in the Postman app.

**App information (please complete the following information):**
 - App Type: Native app
 - Postman Version: 7.x
 - OS: MacOS, Linux, Windows

**Additional context**
See internal notes

**Comment by a85** [comment]
What exactly are they migrating? This should just be a simple app upgrade. Migration as a thing only exists for user accounts.

**Comment by JP-from-Postman** [comment]
@a85 There's a prompt shown to migrate teams to RBAC, along with the upgrade to v7, no?

**Comment by a85** [comment]
If there are not signed in, they should not be getting a migration prompt as they don't have a team - nor an account.

**Comment by JP-from-Postman** [comment]
Understood, I could have clarified that better in my initial comment. It's a mix of both scenarios. Some affected users are on teams or signed in, some are not. In that sense, I guess the upgrade process is the commonality, not necessarily the migration.

**Comment by JP-from-Postman** [comment]
Looking at this again, most (possibly all) reports involve one of two scenarios:

a) User logs out at migration prompt (users who are not admins cannot migrate a team, so sign-out is the only other option presented), and then logs back in. Existing content is then missing from the Postman app.

b) User logs in for the first time after upgrading to v7. In some instances, content _is_ successfully synced to the cloud, but doesn't populate in app.

For either scenario, installing/logging in to Postman Canary to verify no content is missing, and then clearing local cache for the stable Postman app seems to resolve this issue. For users whose content did _not_ sync successfully, manual recovery attempt by support is required before clearing cache, but may not be successful.

**Comment by DannyDainton** [comment]
Closing this issue as it has now been resolved.
Please feel free to reopen with the steps to reproduce if the issue persists.
