### ISSUE TITLE
cannot read INIT value of global variable

### ISSUE THREAD

**Issue by amado-saladino** [a85/POSTMan-Chrome-Extension#6139]
**What I get**
I always get empty value for INIT global variable

**To Reproduce**
1. Create a global variable with the name ***randomBetween***
2. Assign this value to the variable
```
(min, max) => { min = Math.ceil(min); max = Math.floor(max); return Math.floor(Math.random() * (max - min)) + min; }
```
3. In section ***Pre-request Script***
```
let fn = pm.globals.get('randomBetween')
console.log(fn)
```
4. Click **Send** button to run the request

**Expected behavior**
I expected to have the value of the variable **fn** as what I initiated the variable

**Screenshots**
console snapshot:
<img width="705" alt="postman" src="https://user-images.githubusercontent.com/20227574/54865090-ae6fa280-4d68-11e9-8c8f-4610e13d4828.PNG">

Globals snapshot:
<img width="720" alt="postmanglobals" src="https://user-images.githubusercontent.com/20227574/54865106-145c2a00-4d69-11e9-9884-d31667a74bb6.png">

**App information (please complete the following information):**
 - App Type [Native App]
 - Postman Version [ v7.0.6]
 - OS: [windows 8.1]

**Comment by codenirvana** [comment]
@amado-saladino `pm.globals.get` always uses the value set in the `Current Value` and as I can see from the screenshot its set to empty.
Setting the `Current Value` correctly will fix your issue.

Know more about Variable Sessions: https://blog.getpostman.com/2018/08/09/sessions-faq/
