### ISSUE TITLE
Logging a cheerio selector makes the app unresponsive

### ISSUE THREAD

**Issue by ankit-m** [a85/POSTMan-Chrome-Extension#6141]
**Describe the bug**
Logging a cheerio selector like `console.log($('div'))` in the test scripts makes the app unresponsive

**To Reproduce**
1. Make a request to https://www.google.com
2. Add the following snippet in the test script
```
var cheerio = require('cheerio');

var $ = cheerio.load(pm.response.text())

console.log($('header'))
```

**Expected behavior**
App should not crash

**App information (please complete the following information):**
 - App Type: Native
 - Postman Version: 7.0.6
 - OS: macOS Mojave

**Comment by coditva** [comment]
This issue is fixed and out in the latest Postman App (`v7.12.0`).
