### ISSUE TITLE
Access cookie options using Postman sandbox API

### ISSUE THREAD

**Issue by ankit-m** [a85/POSTMan-Chrome-Extension#6142]
**Is your feature request related to a problem? Please describe.**
Obtain cookie options like domain, path, etc using the `pm.cookies.get(<name>)` method

**Describe the solution you'd like**
Apart from returning the cookie value, it should also return options. Maybe by passing an additional flag like `pm.cookies.get(<name>, true)`

**Describe alternatives you've considered**
Iterate over the list `pm.response.headers` and search for `set-cookie` headers with appropriate name.

**Comment by shamasis** [comment]
Tracking at: https://github.com/postmanlabs/postman-app-support/issues/1228
