### ISSUE TITLE
Can't delete slack integration

### ISSUE THREAD

**Issue by cyrielle-hada** [a85/POSTMan-Chrome-Extension#6146]
**Describe the bug**
It's not possible to delete the Slack integration - monitoring run results. Upon clicking on the trash icon a modal window says "Something went wrong - An error while deleting the integration"

![Slack integration bug](https://user-images.githubusercontent.com/47351631/54913107-f8cc5d00-4ee9-11e9-8d89-fe5a455dc758.gif)

**To Reproduce**
1. Add the Slack integration - Monitor Run Results and set it up following guidelines explained here (https://learning.getpostman.com/docs/postman_pro/integrations/slack/#send-your-monitor-run-results-to-slack)
2. Go to the Slack Configured Integrations page in the web dashboard 
3. Click the trash icon
4. See error message

**Expected behavior**
Be able to remove the integration from the configured integrations list. 

**App information (please complete the following information):**
 - App Type: Native App 
 - Postman Version 7.0.6
 - OS: OS X 10.13.6
 - Browser: Chrome 72

**Comment by Thor07** [comment]
Thanks guys! Works fine now,if recurs,shall reopen.

Cheers!
