### ISSUE TITLE
Allow a request name to have maximum of 256 characters as only 256 characters are synced and rest are dropped

### ISSUE THREAD

**Issue by sujayvenaik** [a85/POSTMan-Chrome-Extension#6149]
**Describe the bug**
The app allows a request name to be on any length, but only the first 256 characters are synced.

**To Reproduce**
Create a request
Set a name greater than 256 characters
Logout and then login
When the request syncs back you will have the first 256 characters of the name only

**Expected behaviour**
Allow a user to only enter 256 characters, not more than that

**Screenshots**

**App information (please complete the following information):**
 - App Type Native App
 - Postman Version 7.0.6
 - OS: macOS High Sierra 10.13.2

**Comment by preethammavin** [comment]
Closing this as a duplicate issue
#5073
