### ISSUE TITLE
Adding 100+ cookies makes app slower

### ISSUE THREAD

**Issue by vinitshahdeo** [a85/POSTMan-Chrome-Extension#6153]
**The app can't handle 100+ cookies smoothly for a domain.** 

I'm trying to add 100+ cookies for a domain and it's crashing. 

- The UI options stop working and becomes unresponsive. 
- The `click` and `scroll` doesn't work
- The app gets slow and starts lagging

Check these screenshots!

<img width="722" alt="Screenshot 2019-03-26 at 11 18 39 AM" src="https://user-images.githubusercontent.com/20594326/54977328-f1c54d80-4fc2-11e9-9420-7f2fe7a93de1.png">

<img width="1404" alt="Screenshot 2019-03-26 at 11 19 01 AM" src="https://user-images.githubusercontent.com/20594326/54977355-0a356800-4fc3-11e9-9e5d-e671352c96e8.png">

**Is there any limit for number of cookies that we can add to cookie store of the app?**

**Comment by arlemi** [comment]
@vinitshahdeo This was fixed in 7.15.0, let us know if you're still experiencing unresponsiveness when adding cookies in bulk.
