### ISSUE TITLE
I need to clear only"initial value" & "current value" of the environment variables after each data iteration.

### ISSUE THREAD

**Issue by LalithVigneshS** [a85/POSTMan-Chrome-Extension#6156]
1.Could see blogs for unset/clear the environment variables completely. 
2.Myself required with clearing the values only.
3.My project requires same variables with different values for each iterations.
Kindly provide me with a workaround.

**Comment by numaanashraf** [comment]
We recommend reaching out to the wider Postman Community (https://community.getpostman.com/) for help with this issue.

Issue Guidelines: https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues
