### ISSUE TITLE
wsHttpbinding is not working

### ISSUE THREAD

**Issue by parthiban-arthanari** [a85/POSTMan-Chrome-Extension#6157]
## App Details:

```
Postman for Windows
Version 47.0.6
win32 10.0.16299 / x64
```

## Issue Report:
I want to know how to connect wsHttpBinding WCF endpoint. Below is my generated xml from wcf client. i waned to know to configure headers and security authorization in post man app.

<s:Envelope xmlns:a="http://www.w3.org/2005/08/addressing" xmlns:s="http://www.w3.org/2003/05/soap-envelope">
<s:Header>
<a:Action s:mustUnderstand="1">http://aditi.com/hrs/authentication/2014/06/02/IAuthorization/GetToken></a:Action>
<a:MessageId>urn:uuid:f2a223ff-6fd3-400d-a943-189fb081142d</a:MessageID>
<a:ReplyTo>
<a:Address>http://www.w3.org/2005/08/addressing/anonymous</a:Address>
</a:ReplyTo>
<s:Header>
<s:Body>
<GetToken xmlns="http://aditi.com/hrs/authentication/2014/06/02">
<TokenRequest xmlns:d4="http://aditi.com/hrs/authentication/request/2014/06/02" xmlns:i="http://www.w3.org/2001/XMLSchema-instance">
<d4;ApplicationId>CoreroSoft</d4:ApplicationId>
</TokenRequest>
</GetToken>
</s:Body>
</s:Envelope>

**Comment by numaanashraf** [comment]
We recommend reaching out to the wider Postman Community (https://community.getpostman.com/) for help with this issue.

Issue Guidelines: https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues
