### ISSUE TITLE
Erroneous "?" Appended to GET Parameter

### ISSUE THREAD

**Issue by Krasiph** [a85/POSTMan-Chrome-Extension#6159]
**Describe the bug**
When issuing a GET request with a single parameter, an extra "?" character is appended and parsed by the receiving app (Django 1.11 using Rest Framework, endpoint is using @api_view(['GET']) ).

**To Reproduce**
1. Send a GET request to a Django 1.11 rest API with a single parameter: http://myexample.com/test?value=test_value
2. Print or return the value of `value` to observe it as `test_value?`

**Expected behavior**
The parameter should not have a '?' at the end

**App information (please complete the following information):**
 - Native App
 - Postman Version 6.3.0
 - OS: Ubuntu 18.04.2 LTS

**Comment by numaanashraf** [comment]
@Krasiph We are unable to replicate this issue with the steps provided. Could you try resending the same request via cURL to rule out a server-side issue?

**Comment by Krasiph** [comment]
@numaanashraf I have made a simpler Django app and deployed it locally to confirm your results. The erroneous "?" must be coming from somewhere else in our app's deployment stack.

Thank you for your time!
