### ISSUE TITLE
Postman has no icon in start menu after typing in the name.

### ISSUE THREAD

**Issue by ghost** [a85/POSTMan-Chrome-Extension#6161]
Please read through the [guidelines](https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues) before creating a new issue.

**Describe the bug**
Postman has no icon in the Windows start menu when you search for it (not in recently added apps, you have to actually try to search for it.)

**To Reproduce**
1. Go to Windows start menu by pressing the Windows key or Ctrl + Esc.
2. Type Postman.
4. See error.

**Expected behavior**
The Postman icon is supposed to be there.

**Screenshots**
![image](https://user-images.githubusercontent.com/45378025/55040509-0cb5b300-4fff-11e9-9aa3-75663bea0a1d.png)

**App information (please complete the following information):**
 - App Type [Native App]
 - Postman Version [7.0.6]
 - OS: [Windows 10 Pro 1809 (OS Build 17763.379)]

**Additional context**
I have tried Indexing Options and deleting the icons database in %localappdata% and it didn't work.

**Comment by harryi3t** [comment]
@Pyknus Thanks for reporting this issue.
Are you still facing this after updating to the latest version of Postman `v7.5.0`?

If yes, could you share the following information:
  - Click on `Open file location` 
  - It should open the location with the Postman shortcut
  - right-click on the shortcut, click on `properties`. Let us know the value in `Target` and `Start in`
  - Click on `Change Icon`. If there is a warning saying `windows cannot find file` take a screenshot of the warning showing the complete path and share that with us
  - If there is no warning then a modal with open `change icon`. Let us know the path in the modal.

Here's a screen recording of the same
![sample](https://user-images.githubusercontent.com/5207331/63261057-28687100-c2a0-11e9-9bef-1b15c1bb0c62.gif)

**Comment by numaanashraf** [comment]
With only the information that is currently in the issue, we don't have enough information to reproduce and take action on this issue. We are going to close this but don't hesitate to reach out if you are still facing this issue on our latest versions, we'll be happy to reopen the issue..
