### ISSUE TITLE
Native app is not open ,it takes too much time

### ISSUE THREAD

**Issue by ilaxopavan** [a85/POSTMan-Chrome-Extension#6162]
native is is too much slow,really get irritated, it takes too much time in opening

try latest version and downgraded version in windows 10 64 bit, nothing works

**Comment by numaanashraf** [comment]
@ilaxopavan Could you try disabling GPU support within Postman via the steps detailed at https://github.com/postmanlabs/postman-app-support/issues/4594#issuecomment-391601621? We've had reports of degraded performance on Windows with certain GPUs/Drivers.

**Comment by ilaxopavan** [comment]
thanks it works

**Comment by numaanashraf** [comment]
Thanks for letting us know @ilaxopavan.

Duplicate of #4262
