### ISSUE TITLE
System Headers are not showing up in headers tab

### ISSUE THREAD

**Issue by saswatds** [a85/POSTMan-Chrome-Extension#6164]
**Describe the bug**
System Headers are not showing up in headers tab when `Inherit from parent` is selected in authentication selection dropdown

**To Reproduce**
0. Open Echo colllection -> Request Methods -> Get Request
1. Make a call to postman-echo.com/get
2. Observe the request headers tab to not have been populated with system headers
3. Go to auth tab and set "no auth" or any other auth
4. Send request again
5. Observe header tab being populated by system headers

**App information (please complete the following information):**
 - Native App
 - 7.1.0-canary.1
 - OS: macOs 18.0.0 / x64

**Additional context**
- this does not happen when request is not saved in a collection.
- happens in 7.0.6 too but is not apparent since system header syncing has issues in runtime bridge

**Comment by shamasis** [comment]
This has been fixed in latest release.
