### ISSUE TITLE
Error ‘something went wrong’ when updating user role 

### ISSUE THREAD

**Issue by cyrielle-hada** [a85/POSTMan-Chrome-Extension#6165]
**Describe the bug**
When trying to update user role in https://app.postman.co/team, an error message says `an error occurred while updating roles.`
  
**To Reproduce**
1. Go to https://app.postman.co/team
2. Click on Manage Roles and update the role
3. Click Done

![Update User role error ](https://user-images.githubusercontent.com/47351631/55101348-d25e1b80-50bb-11e9-8b91-c1c2ce048e45.gif)

**Expected behavior**
Role updated upon clicking on ‘done’ 

**App information (please complete the following information):**
 - Web dashboard
 - Postman Version 7.0.6
- OS: Mac Mojave
- Chrome 73 - Firefox 

**Additional context**
No errors populating from the JavaScript console

**Comment by JP-from-Postman** [comment]
It looks like the team management page is allowing duplicate invites for the same account, and also maybe not checking developer invites against the number of open slots currently on the team. Each pending invite reserves space on the team (either a paid slot or support-only), so I'm guessing the error has to do with the team being actually _over_ the total capacity for paid slots.

**Comment by ankit-m** [comment]
A fix for this has been deployed.

**Comment by cyrielle-hada** [comment]
> A fix for this has been deployed.

@ankit-m I have tested it, it works. Thank you!

**Comment by JP-from-Postman** [comment]
Thanks @ankit-m !
