### ISSUE TITLE
Timeout - content not syncing to Postman app

### ISSUE THREAD

**Issue by JP-from-Postman** [a85/POSTMan-Chrome-Extension#6166]
[From Postman Support, on behalf of user]

**Describe the bug**
Synced user content doesn't immediately appear in the Postman app despite being logged in, though after some time (up to 30 minutes) it does sync successfully. Logs supplied by user show a repeat of the following error:

```
shared.js:16277 Skipping force reconnect as still preparing and no attempt of connection has been made yet.
webpackJsonp.2903.SailsSocket.forceReconnect @ shared.js:16277
vendor-shared.js:132948 timeout
console.error @ vendor-shared.js:132948
vendor-shared.js:132948 timeout
console.error @ vendor-shared.js:132948
vendor-shared.js:132948 timeout
console.error @ vendor-shared.js:132948
vendor-shared.js:132948 timeout
console.error @ vendor-shared.js:132948
vendor-shared.js:132948 timeout
```

**To Reproduce**
Unknown

**App information (please complete the following information):**
App Type: Native
Postman Version: 7.0.6
OS: Windows 7

**Additional context**
See internal context

**Comment by kamalaknn** [comment]
@JP-from-Postman Can you get complete logs from `View -> Developer -> View logs in Finder`?

**Comment by JP-from-Postman** [comment]
@kamalaknn Added to internal tracking

**Comment by sujayvenaik** [comment]
Hey @JP-from-Postman 
Is it still happening? Might be a case where some maintenance or update task might be in progress so there might have been disconnections.

**Comment by JP-from-Postman** [comment]
@sujayvenaik checking with user who reported this....will follow-up with any response.

**Comment by SanthoshGunaShekar** [comment]
@kamalaknn @JP-from-Postman  I have a similiar issue. Myself and my teammate share a workspace and once I create a collection and share the collection to him, the list of api's are not showing the latest one. They always show the old and not updated one, beacuse of this issue we are not able to sync our work and it is affecting us a lot. Could you please let me know how this can be solved or is there any work around to fix this?

Thanks for your help.

**Comment by DannyDainton** [comment]
Hey @JP-from-Postman 

Are we able to close this issue now?

**Comment by JP-from-Postman** [comment]
@DannyDainton I haven't seen this since filing this issue, so probably safe to close.
