### ISSUE TITLE
New Request Tab is not working on Windows after updating to v7.0.6

### ISSUE THREAD

**Issue by yeaserkhan** [a85/POSTMan-Chrome-Extension#6169]
Please read through the [guidelines](https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues) before creating a new issue.

**Description of the bug**
New Request Tab is not working on Windows after updating to v7.0.6

**To Reproduce**
1. Open Postman Native App v7.0.6 in Windows 10
2. Click on '+ button'

**Current Observation**
New tab is not opening. 

**Expected behaviour**
New tab should open. Even clicking on requests are not opening on a tab.

**Screenshots**
Snapshot attached for further clarification. Video can also be provided upon request. However, cannot attach videos here as its file type is not supported in GitHub.
![2019-03-28_11-23-30](https://user-images.githubusercontent.com/30042692/55132335-39c3ac00-514c-11e9-8d56-8dc1339995c6.png)

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version 7.0.6
 - OS: Windows 10

**Comment by sujayvenaik** [comment]
Hey @yeaserkhan 
Can you send us the logs? You can find the logs from View->Developer->View logs option.

Also to recover from this state you can `Open in new tab` option from the request menu.

**Comment by unexpand** [comment]
Tab won't open on OSX as well, upgraded to 7 and now 7.0.7. Doesn't help.
[main.log](https://github.com/postmanlabs/postman-app-support/files/3049664/main.log)

**Comment by sujayvenaik** [comment]
Hey @unexpand 
Can you share the complete logs folder? And also View->Developer->ShowDevTools(Current View)?

**Comment by yeaserkhan** [comment]
Hi @sujayvenaik - I am so so sorry for the delayed response. I have been super duper busy with some prod issues. Anyways, this issue seems to have resolved after following these steps:

1) Sign out from the native app
2) Then click add tab button (tab opens after signing out)
3) Then re-sign in

I don't know the root cause but this worked out for me. Thank you for your response @sujayvenaik. 

Since the issue have been resolved, hence, I'm closing this issue.
