### ISSUE TITLE
Alignment issues in the Documentation page

### ISSUE THREAD

**Issue by ash007-postman** [a85/POSTMan-Chrome-Extension#6170]
**Describe the bug**
In the documentation page, the => symbols and locations of each field do not line up vertically down the page and instead bounce back and forth. Additionally, the smaller image how it wraps the words in the payload section incorrectly and literally takes the last letter of a word and moves it to the next line by itself. This is literally the ONLY part of Postman that I absolutely hate and always have. Attached are the screenshots for your ready reference for both the issues.

**To Reproduce**
1. Go to the documentation page
2. Click on any request
3.  => symbols and locations of each field do not line up

**Expected behavior**
=> symbols should be aligned

**App information (please complete the following information):**
 - App Type -Native app
 - Postman Version App version: 6.7.3

![Screenshot 2019-03-28 at 12 01 40 PM](https://user-images.githubusercontent.com/41741228/55135362-7e057b00-5151-11e9-86a0-9b57a1fa1405.png)
![word wrap](https://user-images.githubusercontent.com/41741228/55146628-f62c6a80-516a-11e9-993d-a2aa65ae39af.jpg)

**Comment by Cazaimi** [comment]
Thanks for reporting @ash007-postman . 

This issue occurs if description text is vertically aligned using tabs (`\t`). It does work if spaces (` `) are used instead. 

Looking into it.

**Comment by Cazaimi** [comment]
Solved. 

@Raja-Simha  can be marked as closed.
