### ISSUE TITLE
Upload file from public URL

### ISSUE THREAD

**Issue by vishnusaikia** [a85/POSTMan-Chrome-Extension#6172]
I am new to Postman. while testing an API, I can able to select a file from local system, but not able to select a file URL from my server. How can I upload a file from a link or URL in key field to get it done?

Please suggest.

**Comment by numaanashraf** [comment]
We recommend reaching out to the wider Postman Community (https://community.getpostman.com/) for help with this issue.

Issue Guidelines: https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues
