### ISSUE TITLE
Git integration 

### ISSUE THREAD

**Issue by siddharthpharate** [a85/POSTMan-Chrome-Extension#6173]
Hello,

We would like to have git integration in postman.
Where in all our test collections will be saved in a json in our test repository.

Using this we can pull the latest json files(Collections), add or edit the collections and again push to the repository.

With this the test collections will become more maintainable.

Thanks,
Siddharth

**Comment by preethammavin** [comment]
@siddharthpharate We do have an integration already, for reference https://learning.getpostman.com/docs/postman_pro/integrations/github/
