### ISSUE TITLE
Unable to invite user from native app - ‘something went wrong’ doesn't convey the root cause of the problem

### ISSUE THREAD

**Issue by cyrielle-hada** [a85/POSTMan-Chrome-Extension#6174]
**Describe the bug**
Unable to invite a user to join a personal workspace from the native app. Upon clicking send invitations, an error message says `“something went wrong while inviting.”`
  
**To Reproduce**
1. Open the app 
2. Select Personal Workspace
3. Click on `Invite`
4. Enter user email and click Add 
5. Click `Invite to team` 

6. See error 

<img width="968" alt="Screen Shot 2019-03-28 at 11 59 31 AM (1)" src="https://user-images.githubusercontent.com/47351631/55150408-00873e00-5144-11e9-88e5-538f11cc2b00.png">

**Expected behavior**
Able to invite users from the native app successfully. 

**App information (please complete the following information):**
 - Postman native app version 7.0.6
- OS: Mac

**Comment by preethammavin** [comment]
Hi,
As I checked the reason why the user is not able to add a member to the workspace is that the team does not have any user slots left to add a member to the workspace. 

If the user wants to add the billing user we would suggest going to the Manage Team Page in the web dashboard and invite the Billing user from there. 

For reference: go.postman.co/team/invite?type=support

**Comment by abhijitkane** [comment]
@preethammavin The non-informative error message is still a bug. @sivcan Can you investigate?

**Comment by sivcan** [comment]
@abhijitkane Yes, this is still a bug. We're making the change to make sure all the errors are properly conveyed now.

**Comment by bhargavkaranam** [comment]
This should be fixed in the latest version of the app (v7.0.9).
