### ISSUE TITLE
Team blocked from adding slots: needed billing user can't join, account still associated w/ disabled team

### ISSUE THREAD

**Issue by JP-from-Postman** [a85/POSTMan-Chrome-Extension#6176]
Please read through the [guidelines](https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues) before creating a new issue.

**Describe the bug**
Postman Pro team has no billing user and needs to change subscription, but intended billing user can’t be added due to unknown bug.

Sequence of events:

1. **Billing User** leaves _Team A_
2. _Team A_ is disabled
3. Support deletes duplicate pending invites for _Team B_, apparently affected by https://github.com/postmanlabs/postman-app-support/issues/6165
4. Support generates and sends fresh invite to **Billing User** to join _Team B_ with billing,admin roles
5. **Billing User** clicks invite, is shown a status 500 error page
![image](https://user-images.githubusercontent.com/43283131/55198270-9f2a9380-5172-11e9-9943-889349b3a616.png)
6. **Billing User** navigates to the Billing Overview page, which is for the already disabled _Team A_. Message is shown indicating that they don't have access to the page.
![image (1)](https://user-images.githubusercontent.com/43283131/55198262-95a12b80-5172-11e9-8c23-6bd3517e803f.png)
7. Internal logs reflect that **Billing User** is not currently a member of any team, nor have they joined any other team after leaving _Team A_

**To Reproduce**
See internal notes

**Expected behavior**
User should be able to join team without above errors, account should not still be associated with disabled team they have left.

**App information (please complete the following information):**
Web Dashboard

**Additional context**
See internal notes

**Comment by preethammavin** [comment]
The issue has been marked as resolved, closing the thread for now.
We'll be happy to provide you with more assistance if you wish to re-open it in future.
