### ISSUE TITLE
Can't select open tabs in the find and replace section

### ISSUE THREAD

**Issue by sujayvenaik** [a85/POSTMan-Chrome-Extension#6178]
Please read through the [guidelines](https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues) before creating a new issue.

**Describe the bug**
Can't select the open tabs in the find to replace a section

**To Reproduce**
Steps to reproduce the behaviour:
Open a new tab
enter a URL
Use the find and replace section to search for the tab
The tab appears in open tabs section but cannot select the tab

**Expected behavior**
Can select and then replace contents in the tab

**Screenshots**
![findReplace-bug](https://user-images.githubusercontent.com/11532114/55211719-4101bd00-5213-11e9-9ce8-39e10924c226.gif)

**App information (please complete the following information):**
 - App Type Native App
 - Postman Version v7.0.6

**Comment by numaanashraf** [comment]
Fixed in Postman v7.0.8
