### ISSUE TITLE
Postman Runner doesn't show Pre-request script assertion results

### ISSUE THREAD

**Issue by ghost** [a85/POSTMan-Chrome-Extension#6179]
**Describe the bug**
Pre-request script assertion results are not showing in Postman Runner. 
If there are only pre-request tests, when running request in Postman Runner it shows 0 (zero) assertions in the request.

**To Reproduce**
1. Create a new request
2. Add any number of pre-request script tests and save
3. Run collection in Postman Runner
4. You will see **This request does not have any tests.** message.

**Expected behavior**
The pre-request assertions results should show in Postman Runner. 

**Screenshots**
![image](https://user-images.githubusercontent.com/48474184/55159102-60063d80-5186-11e9-933b-a9e38a06a316.png)

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version 7.0.6
 - OS: macOS Mojave 10.14.3

**Additional context**
Add a post-request test to the request than Postman Runner will show both the PRE and POST request assertions results.

**Comment by numaanashraf** [comment]
This is fixed in Postman v7.0.9
