### ISSUE TITLE
Postman crashing when using invalid script

### ISSUE THREAD

**Issue by harryi3t** [a85/POSTMan-Chrome-Extension#6180]
**Describe the bug**
Postman crashes when I use an invalid script (See below for the exact script)

**To Reproduce**
1. Send a request with following pre-script
```js
var x = {
    key: 'a',
    value: {}
};

pm.sendRequest({
    url: 'postman-echo.com/put',
    method: 'PUT',
    body: {
        mode: {
            toString: function() {
                return 'formdata';
            }
        },
        formdata: [x]
    }
}, function(err, response) {
    console.log(err)
});
```

**Expected behavior**
Postman should warn me about the error instead of crashing. This is what usually happens when a script is invalid but not in this particular case.

Sample error message and toast when script is not valid
<img width="466" alt="Postman" src="https://user-images.githubusercontent.com/5207331/55215472-ed49a080-521f-11e9-945d-4e11ebd47c7b.png">

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version: 7.0.6
 - OS: macOS High Sierra 10.13.2

**Comment by codenirvana** [comment]
This issue is fixed in the latest version of the Postman app `v7.10.0`.
