### ISSUE TITLE
Moving a request to another collection doesn't preserve request comments

### ISSUE THREAD

**Issue by udginvr** [a85/POSTMan-Chrome-Extension#6181]
When I move a saved request from one collection to another, all comments written for that request are gone for good.

1. Create two collections.
2. Create a request in one of them.
3. Write and save a comment to the request.
4. Move the request in question to another collection.
5. Comment is lost.

Expected behavior: comments are preserved.

 - App Type: Native App
 - Postman Version: 7.0.6
 - OS: Windows 10 Pro

![1](https://user-images.githubusercontent.com/49057505/55218169-56c2b280-5212-11e9-992a-ac96f5079368.gif)

**Comment by akshay-kulkarni-03** [comment]
Hi @udginvr , with the most recent release this should be fixed. As of today you can't move requests specifically but if you move your collection the comments also get moved! 

Feel free to re-open this issue if you face it again.
