### ISSUE TITLE
Collection runner not showing correct test results

### ISSUE THREAD

**Issue by Thor07** [a85/POSTMan-Chrome-Extension#6183]
Please read through the [guidelines](https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues) before creating a new issue.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**App information (please complete the following information):**
 - App Type [e.g. Chrome App, Native App]
 - Postman Version [e.g. 6.0.1]
 - OS: [e.g. macOS High Sierra 10.13.2]

**Additional context**

**Comment by shamasis** [comment]
Looks like a technical issue while reporting this issue. Actual issue is at https://github.com/postmanlabs/postman-app-support/issues/6184
