### ISSUE TITLE
Import multiple curls

### ISSUE THREAD

**Issue by Lolek1978** [a85/POSTMan-Chrome-Extension#6185]
Hi, I have a little problem :(. 
As a user I want to import multiple curls to postman.
For example i have a list
curl -X GET https://hostname:20001/ping1 -H 'cache-control: no-cache'
curl -X GET https://hostname:20001/ping2 -H 'cache-control: no-cache'
curl -X GET https://hostname:20001/pings1 -H 'cache-control: no-cache'
curl -X GET https://hostname:20001/pings12 -H 'cache-control: no-cache'
etc. 

This is a typical flat list which has a over 50 curls - and im wondering does postman gui  has a such feature which allows me import all curls at once?

**Comment by a85** [comment]
Thank you for filling the feature request! Postman does not support this right now. We recommend using curl commands individually. We are tracking curl import support separately and as there is no standardised format for a list of curl imports - we won’t do this natively. We will introduce plugins soon to let the community build plugins for importers to serve these use cases.
