### ISSUE TITLE
Collections are created as read only if user profile is not email verified

### ISSUE THREAD

**Issue by jongio** [a85/POSTMan-Chrome-Extension#6187]
Please read through the [guidelines](https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues) before creating a new issue.

**Describe the bug**

**To Reproduce**
Create collection with non-email verified user account.

Collection is created as read only and doesn't tell user why.

**Expected behavior**

When you hover over the collection it tells you why it is read-only.

**Screenshots**

**App information (please complete the following information):**
 - App Type [e.g. Chrome App, Native App]
 - Postman Version [e.g. 6.0.1]
 - OS: [e.g. macOS High Sierra 10.13.2]

**Additional context**

**Comment by numaanashraf** [comment]
@jongio Could you help us understand what you mean by non-activated user?

**Comment by jongio** [comment]
@numaanashraf  - I updated to say "non email verified" instead of non-activated.  State=account created, but email is not verified.

**Comment by numaanashraf** [comment]
Thanks @jongio. Accounts with unverified email shouldn't lead to creating read-only collections. If this is still happening for you, it might be a bug. Could you share the logs from (View > Developer > Show Logs) to help@getpostman.com with the email title as "Logs for GH#6187"? It'll help us understand what's happening at your end.

**Comment by harryi3t** [comment]
@jongio Could you update the `App information` section in the issue description? The App type, the version, and the OS. That will help us narrow down the issue.
Also, try restarting the App and try again.

**Comment by jongio** [comment]
I could not repro with a new account. Closing and will re-open if I see it again.

**Comment by adammarr** [comment]
Had the same issue. Switched to the desktop version finally, logged in with Google, and I can only create read-only Collections. There doesn't seem to be a way around or out of it. Windows 7, 64bit, Postman v7.0.7. Tried restarting the app. Finally waited a bit, and restarted again, and it worked, and loaded the data from my chrome app. But there was no indication of any error in the UI the first 2 times, just locked collections when created. Sent logs in email. Not a big deal now, that it started working, but kind of a pain at the get-go. Did not have the chrome app open. Maybe his issue was similar, and the time it took him to verify his email was enough to allow the problem to remedy.

**Comment by siddisking** [comment]
I had a similar issue but my email ID was verified.

Downgrading to 7.0.7 solved my issue.

OS ubuntu 18.04

**Comment by themsheeps** [comment]
I solved my issue by: 

1. Closing my Desktop Postman instance,
2. Opening my Google Apps Postman Instance and logging out from it,
3. Reopened my Desktop Postman instance it was working as expected.

Kind regards,
Johan

**Comment by hoangleitvn** [comment]
We are facing this issue now, still not figure out the root cause

**Comment by JoseFMP** [comment]
2021 still happening.

Cheers.

**Comment by HoomanDevp** [comment]
Same problem in Web Application

![Screenshot (3)](https://user-images.githubusercontent.com/67341187/144744931-5366a280-f8d9-44f5-bc11-536b12776b52.png)
n

**Comment by m3dbedb** [comment]
I have found the same issue in native windows postman app v10.14.2. I am working in scratch pad without authorizarion. When I have made search via "find and replace" option I have noticed all collections are marked with lock sign as listed in previous screen samples. By in my case it does not make any sense.
