### ISSUE TITLE
Script reusing

### ISSUE THREAD

**Issue by LannyYao** [a85/POSTMan-Chrome-Extension#6190]
Just a suggestion from my side.

If I write a pre script or test script,  I want to save it as a special item and I can import it  in the other tabs instead of duplicating the whole request tab. 
And also I want t o save such script under my account by itself for reusing.

So why not add a script collections feature and under each request tab can the user import the script he wants or make it default when adding tabs.

From my side, it will be great helpful for my daily work. : )

**Comment by shamasis** [comment]
For now, can you hit edit of collection and / or folder and add common script that you want to run across all items using collection / folder level scripts?

**Comment by postfrzero** [comment]
Postman v11 rolled out a few weeks ago with support for the new Package Library, which enables you to reuse code by creating and requiring packages within your scripts. Learn more about the Package Library [here](https://blog.postman.com/postman-v11-plans-packaging-updates-2024/#what-is-the-package-library-for-reusable-scripts) or [here](https://learning.postman.com/docs/tests-and-scripts/write-scripts/package-library/).
