### ISSUE TITLE
No response from localhost

### ISSUE THREAD

**Issue by LazukinPavel** [a85/POSTMan-Chrome-Extension#6194]
I've got some trouble with getting response from localhost. 

When I try to send get-request to localhost I've got a "Could not get any response" from postman. My server send 301 response code. Postman console send me - Error: socket hang up. Tried to change ports, it didn't help. Also tried to turn off SSL certificate verification, same result.
Example of request: 
http://localhost:8001/api/leads?integration_id=169&platform_id=dev&date_from=2019-03-29&date_to=2019-04-01

When I use python requests lib, it works fine.
P.S. I'm on Ubuntu, if it matters.

**Comment by shamasis** [comment]
Hmm. That’s odd. Can you access localhost using curl or wget?

**Comment by LazukinPavel** [comment]
Curl works fine.

**Comment by kasim** [comment]
I have the same issue in MacOS with Postman v7.0.7 but in a different way.

I could do GET request with my local server but I can't do POST to http://localhost

I have already turned off SSL, Proxy and the timeout set to 0.

And yes, Curl is working fine.

**Comment by shamasis** [comment]
@LazukinPavel - if curl works, it implies Postman needs to have "System Proxy" setting turned on and Global Proxy turned off. This is assuming that your system has a Proxy configured.

If there is no proxy configured in OS, can you check if Postman works fine when you make normal calls such as `https://httpbin.org/anything`, if that works fine, then the last debugging step is to export this call as a collection and then run using `newman` from CLI. If newman can run it and Postman cannot, then we really need to do a screen-share or something to dig deeper.

**Comment by codenirvana** [comment]
@LazukinPavel @kasim As mentioned in https://github.com/postmanlabs/postman-app-support/issues/6194#issuecomment-485444191, can you confirm if your issue is resolved?

**Comment by LazukinPavel** [comment]
> @LazukinPavel @kasim As mentioned in [#6194 (comment)](https://github.com/postmanlabs/postman-app-support/issues/6194#issuecomment-485444191), can you confirm if your issue is resolved?

I'm sorry, I've lost a track of issue. Using Insomnia now.
