### ISSUE TITLE
Billing user unable to access Billing overview 

### ISSUE THREAD

**Issue by cyrielle-hada** [a85/POSTMan-Chrome-Extension#6195]
**Describe the bug**
Unable to access anything under the billing overview http://app.postman.co/team/overview while being granted with the Billing role. 

**To Reproduce**
1 - Go to http://app.postman.co/team/overview
2 - See message saying `You don't have access`

**Screenshot**

<img width="814" alt="Screen Shot 2019-03-29 at 11 08 55 AM" src="https://user-images.githubusercontent.com/47351631/55318767-743e8900-546b-11e9-9bf2-ceadccbfd59c.png">

**App information** 

- Browser: Chrome 

**Additional context**
- Another team member with the billing role is able to access the billing overview. 
- Sign out / Log back in and clear the cache doesn't help
- The same behavior happens on other browsers

**Comment by preethammavin** [comment]
Hi,
The issue has been fixed. Closing the issue for now, do feel free to reopen it if it is not resolved.
