### ISSUE TITLE
Postman replicating source folder under name Postman-{timestamp}

### ISSUE THREAD

**Issue by yasser-mas** [a85/POSTMan-Chrome-Extension#6196]
postman replicating source folder under name Postman-{timestamp} 

OS info : 

NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"

currently postman folder size is 33 GB !

Can I remove it manually ? and how to prevent this issue happening again ?

![image](https://user-images.githubusercontent.com/18216451/55323228-ca68f780-547e-11e9-997b-f3dde7d8df32.png)

**Comment by numaanashraf** [comment]
@yasser-mas Could you verify you are on the latest version of Postman (v7.0.7 as of today)?. We've included the fix for this issue on v7.0.7 and the app should auto-cleanup the previous update downloads automatically.

**Comment by yasser-mas** [comment]
Thanks, 

the folders deleted automatically after updating app
