### ISSUE TITLE
After update, lost the syntax highlighting 6.7.4

### ISSUE THREAD

**Issue by canabina** [a85/POSTMan-Chrome-Extension#6198]
**Describe the bug**
After the updated app, lost the syntax highlighting 6.7.4

**To Reproduce**
1. Go to app
2. Click on response or request panel

**Expected behavior**
Should be syntax highlighting 

**Screenshots**
<img width="1085" alt="Снимок экрана 2019-04-01 в 16 40 18" src="https://user-images.githubusercontent.com/12137279/55332025-2cd0f080-549d-11e9-8c6d-48fef80af14a.png">
<img width="797" alt="Снимок экрана 2019-04-01 в 16 40 45" src="https://user-images.githubusercontent.com/12137279/55332034-30fd0e00-549d-11e9-9b8d-a2597c34f947.png">

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version: 6.7.4
 - OS: macOS Mojave

**Additional context**
After update to the latest version

**Comment by numaanashraf** [comment]
@canabina Could you check whether there are any errors in (View > Developer > Show DevTools (Current View) > Console)?

**Comment by yanicakj** [comment]
@numaanashraf getting the same issue, but only in response bodies. Could there be a specific reason?

**Comment by numaanashraf** [comment]
We are closing this as this issue is no longer reproducible on the latest versions of Postman (v8.0.10 as of this post). Please update to the latest version of the app and let us know if you are still facing this issue.
