### ISSUE TITLE
Enterprise users need more than 5 Custom Domains

### ISSUE THREAD

**Issue by ash007-postman** [a85/POSTMan-Chrome-Extension#6199]
**Is your feature request related to a problem? Please describe.**
Enterprise users need more than 5 Custom Domains for different projects

**Describe the solution you'd like**
Add more than 5 domains

**Comment by abhijitkane** [comment]
@preethammavin Why is this a feature / assigned to ops?

**Comment by JP-from-Postman** [comment]
It might be interesting to look at this from the same perspective as monitoring calls --- a baseline amount per plan, with the option of adding on additional domain "blocks"

**Comment by sgrazvan** [comment]
Would be awesome to buy extra domains on the Team plan. Or any plan.

**Comment by sony-mathew** [comment]
Hey @ash007-postman @JP-from-Postman @sgrazvan 

We have revamped our plans over time. Currently this is how the plans look like:
![Screenshot 2024-09-03 at 1 42 14 AM](https://github.com/user-attachments/assets/206b5ec1-5c8c-4e1c-af26-11fb17683d7b)

Also we have introduced custom domains as an addon that you can buy in any plan. 
![Screenshot 2024-09-03 at 1 43 42 AM](https://github.com/user-attachments/assets/2da50e9a-7c72-48c6-aa61-afd2730d29cc)

We hope this resolves your issue. If you have any further concerns or questions, please feel free to reopen this discussion. We're here to help and support you.
