### ISSUE TITLE
Chrome crash resulted in complete loss of all data

### ISSUE THREAD

**Issue by patimen** [a85/POSTMan-Chrome-Extension#620]
I was doing unrelated work in Chrome, and the browser crashed. It has crashed before without incident. This time, when I started the packaged app, ALL data had been lost! I had some backups to file from a while back, but I have lost some significant work! I'm sorry I can't offer more info on how to repro, it was a random crash of Chrome while opening a web page. I'll be sure to backup more often, but this is very disturbing.

**Comment by a85** [comment]
This issue has been fixed by Google. We now also offer a backup Sync service. Email us at help@getpostman.com to get on it!
