### ISSUE TITLE
Allow copying of URL with resolved variables

### ISSUE THREAD

**Issue by f-ewald** [a85/POSTMan-Chrome-Extension#6200]
**Is your feature request related to a problem? Please describe.**

I use variables in my request, for example `https://{{host}}/x/y/z`. I would like to share those resolved variables with other members of my team . Currently I have to click on "Code" and then select for example curl to get an URL which takes some time.

**Describe the solution you'd like**
I would like to have a button under "Send" or "Save" which allows copying the resolved URL to clipboard.

**Describe alternatives you've considered**
Described above it took me some time to figure out that I can click on code. This field could be labeled more clearly.

**Additional context**
None

**Comment by a85** [comment]
We recommend logging things to the console or using a shared workspace for sharing these values.
