### ISSUE TITLE
i need help!?  Can i use {{xxx}} in Tests?

### ISSUE THREAD

**Issue by tester1234562020** [a85/POSTMan-Chrome-Extension#6204]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

![image](https://user-images.githubusercontent.com/44419851/55381405-adebbe80-5555-11e9-9d13-5db7801bf45a.png)
![image](https://user-images.githubusercontent.com/44419851/55381420-b6dc9000-5555-11e9-95c2-f262b02ac3d8.png)

It looks like this.

**Comment by numaanashraf** [comment]
We recommend reaching out to the wider Postman Community (https://community.getpostman.com/) for help with this issue.

Issue Guidelines: https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues

**Comment by tester1234562020** [comment]
hello,i dont know how to search?
