### ISSUE TITLE
Could not get any response - Error: connect ECONNREFUSED

### ISSUE THREAD

**Issue by camohub** [a85/POSTMan-Chrome-Extension#6205]
Hi, 3 days ago everything worked fine. Now I am getting an error Could not get any response like the screenshots show. Here are the error and settings screenshots. 
![Screenshot (143)](https://user-images.githubusercontent.com/8393426/55384384-e4601400-552a-11e9-8037-e8d6eb99e22e.png)
![Screenshot (145)](https://user-images.githubusercontent.com/8393426/55384392-e924c800-552a-11e9-9966-e8358d09ea18.png)
Any public url is not able to connect. Only localhost works. I reinstalled the Postman to latest version but nothing happened. 
Thank you for any help.

**Comment by shamasis** [comment]
Can you check your OS proxy settings or proxy settings in Postman?

**Comment by baibhavtripathi** [comment]
I was having the same issue on Mac Postman, Version 7.0.7 (7.0.7)

Just add a extra slash, that trailing slash is important.

i.e try         "node4:9200/search/_search/ "

Happy coding :)

**Comment by camohub** [comment]
@shamasis Postman proxy settings are off
![Screenshot (148)](https://user-images.githubusercontent.com/8393426/55541852-1a85cb00-56c6-11e9-8af5-73d166f23ddf.png)

@baibhavtripathi Trailing slash does not work.

**Comment by shamasis** [comment]
@camohub can you try making the same call using `curl` and check? (Use `--verbose` mode in curl so that we get more details.)

**Comment by shamasis** [comment]
@camohub did you manage to recheck using curl? Another thing that interests me is that can you try enabling “use system proxy”? If your network has a proxy and is defined in OS, then this setting will enable postman to use the same. I’m stressing on proxy because the symptoms you mentioned gives me the feeling that localhost is excluded from proxy and hence is the only endpoint that’s working.

**Comment by camohub** [comment]
I made a request in PHP. It works. It is curl request. Postman still does not work. Any suggestions? I am not familiar with proxy. Why I need it?

PS: URL of the request looks like node4:9200/search/_search Is it correct?  Its the same url as before when it worked.

**Comment by camohub** [comment]
Still no solution. Any suggestions?

**Comment by Westernwells** [comment]
am also having this same issue

**Comment by camohub** [comment]
As I found out I am behind the proxy server. Is it related to this problem?

**Comment by shamasis** [comment]
@camohub Like I was guessing, proxy seems to be the likely culprit. But you never know! :-p In your proxy setting in Postman App, can you enable using system proxy and then in your system proxy, exclude the domain `node` (I'm guessing that you will see that `localhost` is already marked as excluded there and that's why that is working.)

**Comment by shamasis** [comment]
> am also having this same issue

@Westernwells - is it "same" issue... by that I mean, "http://localhost/" works but nothing else on local works? If there is a major variation from that then please file a separate issue.

**Comment by camohub** [comment]
What means exclude domain node? Proxy settings looks like:
![Screenshot (158)](https://user-images.githubusercontent.com/8393426/56438157-3e5e2900-62e2-11e9-834e-80f2f8638bcd.png)

**Comment by Apostolos-Daniel** [comment]
I'm running into the same issue. Even if I try getting all my collections using the Postman API key (https://community.getpostman.com/t/where-do-you-see-your-own-uid-for-collection/3537) I generated I get a 'connection refused' response.

Request: 

curl  https://api.getpostman.com/collections?apikey=XXXXXXXXXXXXXXX/ -v

Response:
Failed to connect to api.getpostman.com port 443: Connection refused

It may be a proxy issue - I did try specifying the proxy IP address and port in Settings and all tried with and without 'Use System Proxy
Enable this option to allow Postman to use the system's default proxy configurations'. 

I also tried to make the request outside the firewall - I get  a more explicit error there:

'AuthenticationError'. 

I've copied the API key directly from the Postman Integrations, Existing API Keys page. It currently has  a status of 'Enabled' and 'Last Accessed' of 'Never Used'. 'Date Created' is June 7, 2019. 

I've ran out of ideas for now. Any thoughts or suggestions are more than welcome!

Thanks for your time :)

**Comment by deep1803** [comment]
![0CAC2F21-8023-4048-A08C-79E129468284](https://user-images.githubusercontent.com/52865528/61175364-b54a4b80-a5cb-11e9-9ab7-2ca2f48fc7bd.jpeg)
Proble :could not get any response in postman 
Help me!

**Comment by mustela** [comment]
Same happens where. Totally random. Sometime it works sometimes it doesn't. When it fails if I use curl, it just works.

**Comment by ghost** [comment]
Same here - getting ECONNREFUSED from a server that otherwise works (another app is able to connect to the same endpoint). A Postman developer should address this issue!

Edit: SSL verification and proxies are disabled in my Postman settings.

**Comment by gaurav3588** [comment]
Same issue is coming to to me it was working fine but currently it is not even in the local host.
![1](https://user-images.githubusercontent.com/55969324/65849671-226ab300-e369-11e9-8de9-b81148180b58.JPG)
![2](https://user-images.githubusercontent.com/55969324/65849677-28f92a80-e369-11e9-98ae-b3b7df2fd215.JPG)

**Comment by saifeiLee** [comment]
I had the same issue. And I found a solution:
1. Clear DNS cache.
```bash
# Mac OS X 12 (Sierra) and later:
sudo killall -HUP mDNSResponder
sudo killall mDNSResponderHelper
sudo dscacheutil -flushcache
```
2. Trun Off Postman system proxy

**Comment by mustela** [comment]
It's true that running that fixes the issue, but I have to do it over and over :/

**Comment by marwin1991** [comment]
same issue here

**Comment by dfmmalaw** [comment]
Having same issue when trying to connect to localhost only. Can hit it from Swagger and curl but not Postman
![Screenshot_1](https://user-images.githubusercontent.com/13461445/74448550-2e06d400-4e49-11ea-9cd4-c3c2ac1f6c3e.png)

**Comment by ebuojr** [comment]
Having same issues when icall localdb

**Comment by mohitranka** [comment]
Hi All, we have addressed it in v7.25.0 of the application, and now give better messages to help you debug the issue. Please verify the same and reach out to us if the issue persists.

**Comment by ghost** [comment]
i was testing Nest JS ,APIs on postman and i had the same problem,but you either check the proxy settings on postman or start:dev

**Comment by JVDOG** [comment]
I tried ipconfig / flushdns and helped me

**Comment by Nura21** [comment]
Error: connect ECONNREFUSED 127.0.0.1:443
Found this, I've seen the console, and......well some scratch, but its just the name for the host
<img width="1440" alt="Screen Shot 2022-02-25 at 10 16 17" src="https://user-images.githubusercontent.com/70548701/155647668-7bd10ec9-a3d1-46f2-88b6-1f8a491899a2.png">

**Comment by ibhawna** [comment]
> Error: connect ECONNREFUSED 127.0.0.1:443 Found this, I've seen the console, and......well some scratch, but its just the name for the host <img alt="Screen Shot 2022-02-25 at 10 16 17" width="1440" src="https://user-images.githubusercontent.com/70548701/155647668-7bd10ec9-a3d1-46f2-88b6-1f8a491899a2.png">

i am also getting same error

**Comment by ibhawna** [comment]
> Error: connect ECONNREFUSED 127.0.0.1:443 Found this, I've seen the console, and......well some scratch, but its just the name for the host <img alt="Screen Shot 2022-02-25 at 10 16 17" width="1440" src="https://user-images.githubusercontent.com/70548701/155647668-7bd10ec9-a3d1-46f2-88b6-1f8a491899a2.png">

i am getting same error how did you resolve it

**Comment by Nura21** [comment]
Because I use https not http, you can use http to resolve it

Pada tanggal Sen, 13 Jun 2022 16.19, bhawna ***@***.***>
menulis:

**Comment by abhaypsamrat** [comment]
I have face issue, when I try to send response
![Screenshot (3)](https://user-images.githubusercontent.com/60846174/180456754-8dd950c0-b86e-4836-9168-cf098f54f203.png)
