### ISSUE TITLE
[Postman Console]: Some headers are not shown if the request is cancelled

### ISSUE THREAD

**Issue by harryi3t** [a85/POSTMan-Chrome-Extension#6206]
Originally reported here https://github.com/postmanlabs/postman-app-support/issues/4867

Few headers are not shown if the request failed

![pasted_image_23_07_18__6_04_pm](https://user-images.githubusercontent.com/5207331/43076769-e84a7dd4-8ea2-11e8-897a-e203ea307ad6.png)

**App information (please complete the following information):**
 - App Type: native
 - Postman Version: 7.0.6
 - OS: All

**Comment by shamasis** [comment]
Looks like the system/temporary headers were not added. But from the error, I can see that this request did not go through at all and as such no error header would be generated anyway @harryi3t. 

This failed at request parsing. Should this be closed instead?

**Comment by coditva** [comment]
Temporary headers are not shown when:
- There was `ERROR: getaddrinfo ENOTFOUND` (i.e. incorrect hostname).
- There was an error parsing request headers (e.g. setting header `aaa:: "val"`).

Headers are logged when:
- The request failed with `404`, etc.
- The request was successful.

**Comment by arlemi** [comment]
Fixed in 7.16.0 - console displays a warning message about headers not being logged when the request fails. 

<img width="727" alt="Screenshot 2020-02-05 at 22 01 17" src="https://user-images.githubusercontent.com/5029719/73887249-1638ba00-4863-11ea-944c-7aa1a498de51.png">
