### ISSUE TITLE
update time when working on the same collection

### ISSUE THREAD

**Issue by JensGr-1985** [a85/POSTMan-Chrome-Extension#6207]
**Describe the bug**
Currently when working with someone on the same collection getting the changes with a shared collection takes about 10 minutes even when refreshing by hand. 

**To Reproduce**
1. User 1 Change a Test in a request
2. Save Request 
3. User 2 Refresh by hand nothing has changed
4. Wait ~10 min 
5. Refresh again hope it has changed 

**Expected behavior**
The changes of others should be reflected when refreshing the Collection / Postman 

**App information (please complete the following information):**
 - App Type [Native App]
 - Postman Version [e.g. v7.0.7]
 - OS: [Win10]

**Comment by kamalaknn** [comment]
Hi @JensGr-1985 

Could you send extract logs from `View -> Developer -> View logs in Finder` and send them to `help@getpostman.com`. Please include the link to the github issue with it.

**Comment by JensGr-1985** [comment]
After Testing it a couple of times the last days - it can not be reproduced consitently -> Close
