### ISSUE TITLE
Pages related to custom domain not opening 

### ISSUE THREAD

**Issue by labifrancis** [a85/POSTMan-Chrome-Extension#6209]
**Describe the bug**
When a user with an admin role tries to open the custom domain page for a team, the page doesn't open and keeps loading forever.

**To Reproduce**
1. Go to the web dashboard
2. Click on  Team settings
3. Click on Custom domains

**Expected behavior**
This page should load with an option to add a custom domain 

**App information (please complete the following information):**
 - App Type Native App
 - Postman Version 7

**Comment by abhijitkane** [comment]
@labifrancis Can you ask for relevant logs and add to the JIRA ticket?

**Comment by abhijitkane** [comment]
Closing this. The user reported this fixed.
