### ISSUE TITLE
Cannot clean Recent Runs history on Postman Collection Runner

### ISSUE THREAD

**Issue by vfedorin** [a85/POSTMan-Chrome-Extension#6210]
**Precondition:**
Several hundred completed runs in Postman Collection.

**My problem is:**
When I open Collection Runner I have to wait several seconds while the Recent Runs list is being loaded.
Once finished I starting to create new run but the app works slowly. That does not reproduces on other workspaces where the Recent Runs list is not so huge.

**Question/Proposal:**
How can I clean Recent Runs list completely? Would be good if you guys add some UI option to do that.

**Note:**
Sometimes if I keep Collection Runner window opened my CPU becomes overload up to 100+%. Once I close runner window overload stops.
![Screen Shot 2019-04-02 at 13 56 52](https://user-images.githubusercontent.com/14997994/55397570-361a9580-554f-11e9-83d9-2c74d2e54968.png)

Thanks in advance!

**Comment by codenirvana** [comment]
Fixed in the latest version of the Postman app (v7.6.0).
