### ISSUE TITLE
Notification as to why the default team workspace cannot be deleted

### ISSUE THREAD

**Issue by cyrielle-hada** [a85/POSTMan-Chrome-Extension#6213]
**Is your feature request related to a problem? Please describe.**
When deleting a workspace, nothing tells if it's the `Default team workspace`. Plus, an error message says "Something went wrong".

<img width="272" alt="Screen Shot 2019-04-02 at 18 31 52" src="https://user-images.githubusercontent.com/47351631/55423355-a2a88b00-5575-11e9-920b-05152de5285a.png">

You can only tell it's the default workspace by first, the inability to delete it and the generic workspace description. A more reliable tell would be to go to the native app > Select your workspace > Click the ...

<img width="895" alt="delete default workspace" src="https://user-images.githubusercontent.com/47351631/55423117-26ae4300-5575-11e9-945b-d90269d4b84f.png">
 
**Describe the solution you'd like**
It would be great to have a clear notification as to why the workspace cannot be deleted. 

**Describe alternatives you've considered**
Having written somewhere under the workspace 'default team workspace'

**Comment by preethammavin** [comment]
@cyrielle-hada  the issue has been fixed.
