### ISSUE TITLE
Dashboard: "Or create a collection in the Postman app" doesn't do anything if Postman isn't already installed

### ISSUE THREAD

**Issue by JP-from-Postman** [a85/POSTMan-Chrome-Extension#6214]
**Is your feature request related to a problem? Please describe.**
When looking at an empty Workspace in the web dashboard, the link: **Or create a collection in the Postman app** (postman://) appears at the bottom of the page. Clicking this link with the Postman app already installed will launch open the app.

However, if the Postman app _isn't_ already installed, clicking the link doesn't do anything or provide any messaging as to why nothing happened.

**Describe the solution you'd like**
If possible, detect whether or not the user has the Postman app installed when they click the link:
1. Postman _is_ installed: launch Postman app (as it does currently)
2. Postman _is not_ installed: provide messaging to use, such as: "It looks like you haven't installed Postman yet. **Download** it now?"

**Describe alternatives you've considered**
1. Postman _is_ installed: launch Postman app (as it does currently)
2. Postman _is not_ installed: redirect immediately to downloads page without prompting the user. This seems problematic, because it obscures the behavior of clicking the link the app already installed.

**Comment by DannyDainton** [comment]
The web dashboard is no longer a feature on the Postman platform. Closing this feature request.
