### ISSUE TITLE
Documentation Publishing Flow: Required field not throwing error when empty

### ISSUE THREAD

**Issue by chrisdeso** [a85/POSTMan-Chrome-Extension#6216]
**Describe the bug**
The **API Description** field that's surfaced in the API Network publishing flow is required for publishing but doesn't throw an error when empty.

**To Reproduce**
1. Select a collection to publish
2. Check the **Collection discovery** option
3. Fill out the API Name and API Summary
4. Note that the **Publish** action is disabled
5. Fill out the API Description
6. Notice that the **Publish** action is enabled

**Expected behavior**
When empty, required fields should throw an error.

**Screenshots**
Without API Description
![image](https://user-images.githubusercontent.com/4734306/55448129-29686280-558c-11e9-9cee-61386a4dc50a.png)

With API Description
![image](https://user-images.githubusercontent.com/4734306/55448142-384f1500-558c-11e9-8274-2a7978fe733a.png)

**Additional context**
[Filed by Postman]

**Comment by Raja-Simha** [comment]
@chrisdeso thanks for reporting this. I want to understand you better. 

From what I understand, users cannot publish without an API Name, API summary, and API description as the 'publish' option is disabled when at least one of these is empty.

When exactly do you want the error to be thrown? Do you mean to say API description widget should have a message - 'API description cannot be empty' when the description is empty?

**Comment by chrisdeso** [comment]
@Raja-Simha Yes – I guess the screenshot didn't highlight the missing error message that should populate to indicate that the **API Description** field is required for submitting collections/documentation to the API Network. Here's a better one :).

![image](https://user-images.githubusercontent.com/4734306/55454424-89b7ce00-55a5-11e9-981e-14f88cd0155b.png)

**Comment by Raja-Simha** [comment]
Got it. Thanks,

**Comment by DannyDainton** [comment]
Hey @sankalp0o,

Do you know if this something that was picked up in some recent changes?

**Comment by gitThingsDone** [comment]
Closing this ticket as we have removed the collection discovery option from the publish flow.
