### ISSUE TITLE
Postman 7.0.7 not working in Ubuntu 16.04

### ISSUE THREAD

**Issue by isurunix** [a85/POSTMan-Chrome-Extension#6217]
**Describe the bug**
Postman v7.0.7 fails to start in Ubuntu 16.04

**To Reproduce**
1. Go to 'https://www.getpostman.com/downloads/'
2. Download Postman 64bit for Linux
3. Extract the downloaded Postman-linux-x64-7.0.7.tar.gz
4. Run Postman from the terminal.

**Expected behavior**
Postman should start.

**Screenshots**
None

**App information (please complete the following information):**
 - App Type : Native App
 - Postman Version : 7.0.7
 - OS: Ubuntu 16.04

**Additional context**
This is the error shown in the terminal.

`isuru@nix:/opt/postman$ ./Postman 
1554268582936 main info "Booting Postman 7.0.7, linux-4.15.0-45-generic on x64"
1554268582938 main info "EventBus~initialize - Success"
1554268582961 main info "UpdateHandler~init - Success"
1554268582963 main info "RuntimeExecutionService~initialized: Success"
1554268582965 main info "LinuxAutoUpdater~Cleanup - Initial cleanup successful"
1554268583006 main info "ProtocolHandler~init - Success with status: false]"
1554268583023 main info "PluginHost~bootHost: Booted - 1"
1554268583054 main info "Quitting app"
1554268583059 main error "WindowManager~getSharedWindow: Shared window is not available"
1554268583060 main info null
1554268583071 main error {"extra":[],"name":"Error","message":"PluginHost~hostErrorOrExit: Exited with code null with signal SIGINT","stack":"Error: PluginHost~hostErrorOrExit: Exited with code null with signal SIGINT\n    at ChildProcess.host.on (/opt/postman/app/resources/app/node_modules/@postman/app-plugins-host/index.js:63:25)\n    at emitTwo (events.js:125:13)\n    at ChildProcess.emit (events.js:213:7)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)"}
1554268583072 main error {"extra":[],"name":"Error","message":"PluginHost~bootHost: Disabling boot since it has exceeded the maximum allowed boot count 2","stack":"Error: PluginHost~bootHost: Disabling boot since it has exceeded the maximum allowed boot count 2\n    at PluginHost.bootHost (/opt/postman/app/resources/app/node_modules/@postman/app-plugins-host/index.js:26:9)\n    at <anonymous>\n    at process._tickDomainCallback (internal/process/next_tick.js:228:7)"}`

**Comment by numaanashraf** [comment]
@isurunix Do you see any windows or screens open up?

**Comment by isurunix** [comment]
@numaanashraf No. No windows or any screens. It just gives that error on the terminal. Having the same issue with 7.0.6 too.

**Comment by isurunix** [comment]
@numaanashraf Upon inspection, I noticed that the Update process has failed to stop the previous Postman process. Once I stopped it Postman started as usual.

**Comment by numaanashraf** [comment]
@isurunix Thanks for letting us know.

**Comment by SamvelRaja** [comment]
@isurunix  Could you share us the logs from `log.txt` file available in `[PATH_TO_POSTMAN]/Postman/` folder where the app is extracted to verify the issue.
