### ISSUE TITLE
ubuntu still be 6.7.1 and windows is 7.0 for a long time

### ISSUE THREAD

**Issue by seelikes** [a85/POSTMan-Chrome-Extension#6218]
i have upgrade my workspace to 7.0.
but ubuntu with snap is still 6.7.1, which caused my ubuntu computer can not load team collections. everyday is a long day waiting for snap to upgrade.
the app on ubuntu says you can configure the upgrade in Settings > Update, but the truth is there is no Update tag bellow Settings or anywhere else.

**Comment by sujayvenaik** [comment]
@seelikes Please follow the instructions at https://learning.getpostman.com/docs/postman_pro/managing_postman_pro/migrating_to_v7/#updating-app-to-postman-v7-after-migration to update your snap to Postman v7.0.

**Comment by seelikes** [comment]
@sujayvenaik thanks very much
for me, snap switch is very aggressive and making me concerned. so i did a little research and found an optional command: **sudo snap refresh postman --candidate**, this changes nothing about snap, very clear.
