### ISSUE TITLE
Use global variable inside environment variable

### ISSUE THREAD

**Issue by henhal** [a85/POSTMan-Chrome-Extension#6219]
**Is your feature request related to a problem? Please describe.**

I have several environments, each containing several service hosts. When developing, I usually run a local setup, but the host used in this local setup may vary from e.g. localhost or another server in my local network. Currently I need to duplicate the entire environment per host, since it's not possible to define environment variables that in turn use other variables (in particular, that use global variables).

**Describe the solution you'd like**

I want to be able to define global variables, and then use these inside environment variables.
For example, I might have the environments "Local", "Dev" and "Prod". These all define, say, 5 different base URL:s for my services. However, within the "Local" environment, I'd like to define these variables to use another, global, variable so that I can remain using one single "Local" environment, but still reassign the host from e.g. `http://localhost` to `http://my-local-test-server`.
But If I define a global variable `LOCAL_SERVICE_HOST=http://localhost` and then within my environment define `SERVICE_HOST_FOO = {{LOCAL_SERVICE_HOST}}/api/foo`, then the `{{LOCAL_SERVICE_HOST}}` variable is not resolved.

**Describe alternatives you've considered**
I need to duplicate my entire environment and search & replace every variable value instead of referencing a shared global variable.

**Additional context**

**Comment by harryi3t** [comment]
> since it's not possible to define environment variables that in turn use other variables (in particular, that use global variables).

@henhal This is supported, I just tried it out on my end. Seems to be working fine.

<img width="535" alt="Postman" src="https://user-images.githubusercontent.com/5207331/55468448-00de7800-5621-11e9-8015-e5ef1b05525e.png">

**Comment by henhal** [comment]
@harryi3t That's interesting. I tried it several times, but now when I tried again, I realized I had probably erased the "current value" for the SERVICE_HOST_FOO variable (which, unrelated as it is to this issue, is also somewhat confusing - IMO clearing the current value should mean that the initial value is used, but that's only the case if you press _Reset_, which actually _copies_ the value to the current value).

So, thanks a lot for this, it was my mistake. I will close the issue.

**Comment by Gabrz** [comment]
I'm also experimenting with variables inside variables.

The API call indeed works fine.

But when I hover over the variable would it be possible to resolve the complete/total value of the variable?

**So It would show this:**
![image](https://user-images.githubusercontent.com/37636455/61302748-98d62b00-a7e6-11e9-9a91-6f179c973296.png)

**instead of**
![image](https://user-images.githubusercontent.com/37636455/61302626-69272300-a7e6-11e9-94b6-ba3c8e5586ee.png)

**Comment by Ghazgkull** [comment]
Reporting back from the future... this appears to be broken again in v9.0.5. Configuring an environment variable as the value of a global variable doesn't work. `pm.variables.get('SERVICE_HOST_FOO')` just resolves to the string literal `{{SERVICE_HOST_FOO}}` now.

**Comment by DannyDainton** [comment]
@Ghazgkull you would need to use `pm.variables.replaceIn('{{SERVICE_HOST_FOO}}')` for it to resolve that value.

**Comment by TheInvoker** [comment]
So is this possible to do? I want to make a global variable, and then in the environment variables tab, I want to set the default value as a variable pointing to a global variable.

**Comment by DannyDainton** [comment]
You would need to provide more context and examples, for us to understand your usecase @TheInvoker

As this is a closed issue, can you create a new thread, with that information, on the Postman community fourm please.

https://community.postman.com

**Comment by TheInvoker** [comment]
Ok done https://community.postman.com/t/how-to-create-reference-to-global-variables-from-environment-variables/35261
