### ISSUE TITLE
Can't update Windows app from v7.0.4 to v7.0.7

### ISSUE THREAD

**Issue by feathergrass** [a85/POSTMan-Chrome-Extension#6221]
**Describe the bug**
Can't update Windows app from v7.0.4 to v7.0.7.

**To Reproduce**
1. Open the app v7.0.4.
2. Go to 'Help' → 'Check for Updates'
3. There are 7.0.6 and 7.0.7 (Latest) versions available. 
4. Click on 'Update' button.

**Actual behavior:**
There is "UP TO DATE" pop up: "You are up to date! Postman v7.0.4 is the latest version."

**Expected behavior**
The v7.0.7 downloaded and installed.

**Screenshots**
![image](https://user-images.githubusercontent.com/29942318/55464214-a4bd2900-560b-11e9-8072-541c2ee25d9e.png)

![image](https://user-images.githubusercontent.com/29942318/55464202-9bcc5780-560b-11e9-8acc-e33cbd0a2cf5.png)

**App information:**
 - App Type: Native App
 - Postman Version: 7.0.4
 - OS: Windows 7

**Additional context**
v7.0.6 contains a lot of changes, I'd really like to update my app to this version.

**Comment by harryi3t** [comment]
@feathergrass Could you send us the logs? You can find them by clicking `View -> Developer -> View logs in Explorer`. You can share them at help@getpostman.com. Please mention the issue ID in the mail.

Also, can you try restarting the App and try this again.

**Comment by feathergrass** [comment]
@harryi3t After restarting I got the message that the version is v7.0.7. 
So it seems like the version was updated but maybe app had not re-initialized with it or just old value was shown.
The logs have been sent.
