### ISSUE TITLE
Deleted collections doesn't appear in Trash

### ISSUE THREAD

**Issue by Raj-postman** [a85/POSTMan-Chrome-Extension#6224]
**Description**
1) After deleting a collection, Trash is empty.
2) Sharing the collection from [https://go.postman.co/team/elements?type=collection](https://go.postman.co/team/elements?type=collection) receives an authorization error.

**Steps to reproduce the behavior:**
1. Create a workspace
2. Create a collection in the workspace
3. Delete the workspace
4. Check the trash for deleted collections (It’s Empty)
5. Attempt to access / share the collection that was in the recently deleted workspace via [https://go.postman.co/team/elements?type=collection](https://go.postman.co/team/elements?type=collection)

**Expected behavior:**

Trash is populated with recently deleted collections (Up to 1 day) & collections are able to be shared to other workspaces.

**App information:**
 - App Type - Native App
 - Postman Version - 7.0.7

**Additional context**
1) The collection can be seen in the web UI at the url: [https://go.postman.co/team/elements?type=collection](https://go.postman.co/team/elements?type=collection)

2) **Error message when sharing the collection:**
`              key: "render",

                value: function render() {
                    var e = this;
                    return this.props.loading ? r.a.createElement("div", {
                        className: "comments"
                    }, r.a.createElement(c.Loader, {
                        className: "pm-absolute-center",
                        pmStyle: "secondary",
                        size: "xl"
                    })) : this.props.loadError ? r.a.createElement("div", {
                        className: "comments"
                    }, r.a.createElement(p.n, {
                        body: "There was an error while fetching comments. Please try again.",
                        className: "push-double",
                        imageSrc: "/prodash/img/warning.svg",
                        title: "Something went wrong"`

**Comment by abhijitkane** [comment]
@Kurmavathar Two parts here:
1. Deleting the workspace is not the same as deleting the collection. Collections that can't be found in any workspace can be found in https://go.postman.co/me/collections (personal) or https://go.postman.co/team/elements?type=collection (shared). This part works as intended.

2. The comments don't load. This is a bug.

**Comment by preethammavin** [comment]
The issue which led to user not being able to share from me/collections has been fixed.
Will be tracking comments dont load on restore separately

**Comment by diaztech** [comment]
> @Kurmavathar Two parts here:
> 
> 1. Deleting the workspace is not the same as deleting the collection. Collections that can't be found in any workspace can be found in https://go.postman.co/me/collections (personal) or https://go.postman.co/team/elements?type=collection (shared). This part works as intended.
> 2. The comments don't load. This is a bug.

Worked for me. Solved my panic attack
