### ISSUE TITLE
pm.cookie.has tests success when cookie does not exist

### ISSUE THREAD

**Issue by krisavi** [a85/POSTMan-Chrome-Extension#6225]
**Describe the bug**
Making a test with `pm.cookie.has` will result always successful test. It might not fail tests due to #4340.

[API Reference](https://learning.getpostman.com/docs/postman/scripts/postman_sandbox_api_reference/#pmcookies)
`pm.cookies.has(cookieName:String):Function → Boolean`

In v6.5.2 it resulted in either true or blank.

**To Reproduce**
Create a test using `pm.cookies.has` with invalid cookie
Code I used:
```
console.log(responseCookies);
console.log(pm.cookies.has("COOKIEIDONOTHAVE"));
console.log(pm.cookies.has("ASP.NET_SessionId"));
pm.test("response is ok", function () {
    pm.cookies.has("COOKIEIDONOTHAVE");
});
```

**Expected behavior**
I would expect test to fail.

**Screenshots**
v7.0.7
[Code and cookies](http://prntscr.com/n706c4)
[Code and test result](http://prntscr.com/n705zt)
[Console](http://prntscr.com/n708cb)
[Cookies](http://prntscr.com/n705o5)

v6.5.2
![image](https://user-images.githubusercontent.com/1912568/55495027-507e6d00-563c-11e9-9b81-fc680dd4fa2b.png)
![image](https://user-images.githubusercontent.com/1912568/55494947-1dd47480-563c-11e9-89f9-45c162f69c6b.png)
![image](https://user-images.githubusercontent.com/1912568/55495058-612ee300-563c-11e9-8762-6a1bc77a060d.png)
![image](https://user-images.githubusercontent.com/1912568/55494967-275ddc80-563c-11e9-8241-29abe9c7a7b6.png)

**App information (please complete the following information):**
- Postman for Windows
- Version 6.5.2 initially, upgraded to 7.0.7 (latest at the moment)
- win32 10.0.17134 / x64

**Comment by codenirvana** [comment]
@krisavi There are no assertions in this test. Try this out:

```javascript
pm.test("Cookie exists", function () {
    pm.expect(pm.cookies.has("COOKIE")).to.be.true;
});
```
