### ISSUE TITLE
proxy authentication not works with some characters

### ISSUE THREAD

**Issue by perfectacle** [a85/POSTMan-Chrome-Extension#6227]
**App information (please complete the following information):**
 - Native App
 - 7.1.0-canary01
 - macOS Mojave 10.14.4

**Describe the bug**
It can find proxy server with plain password authentication
<img width="702" alt="Screen Shot 2019-04-04 at 3 49 01 PM" src="https://user-images.githubusercontent.com/15857795/55535294-bb3db000-56f1-11e9-80cd-0dac6c6b1b51.png">
![Screen Shot 2019-04-04 at 3 50 27 PM](https://user-images.githubusercontent.com/15857795/55535300-c09afa80-56f1-11e9-893c-4839a618445a.png)

http status code is 407(Proxy Authentication Required)

But It can't find proxy server with some characters in password (especially sharp(**#**))
<img width="718" alt="Screen Shot 2019-04-04 at 3 51 41 PM" src="https://user-images.githubusercontent.com/15857795/55535349-ede7a880-56f1-11e9-9620-b690c5db4d75.png">
![Screen Shot 2019-04-04 at 3 52 05 PM](https://user-images.githubusercontent.com/15857795/55535354-f3dd8980-56f1-11e9-85dd-5671b4782a83.png)

The same happens when '#' is inserted in the username.
escape sequence(**\\#**) not works too.

**Comment by codenirvana** [comment]
@perfectacle I am able to reproduce the issue.

For now, a workaround for this is to use the encoded variant of these characters.
Example: `%23` for `#`

**Comment by vikiCoder** [comment]
Hi @perfectacle,

This issue is fixed in the latest release of Postman App (v7.14.0). Please update your Postman app to the latest version and let us know if you are still facing any issues regarding this.
