### ISSUE TITLE
Could not get any response

### ISSUE THREAD

**Issue by BIGMONK** [a85/POSTMan-Chrome-Extension#6228]
**Describe the bug**
Windows 10 with APP Postman v7.0.7 .

I could do GET request  but I can't do POST,which  could not get any response.

It's all right when I do that in google extension postman.

**Comment by shamasis** [comment]
@BIGMONK - I don't think we have enough information from what you've posted to conclude what could be causing this.

- what error are you seeing in Postman Native app?
- Can you open Postman Console and check if any error is logged there?
- Can you try calling a generic URL such as https://postman-echo.com/get and https://postman-echo.com/post to see if that works?

**Comment by preethammavin** [comment]
Closing the issue has with the current information , we are not able to deduce the issue. Please feel free to reopen the issue with the required information so that we can get it resolved.
