### ISSUE TITLE
Unauthorized to share collection

### ISSUE THREAD

**Issue by Raj-postman** [a85/POSTMan-Chrome-Extension#6229]
**Description:**
Unable to share the collections to my personal workspace.

**To Reproduce**
1. Navigate to [https://go.postman.co/team/elements?type=collection](https://go.postman.co/team/elements?type=collection)
2. Click on **Share** on one of the collection
3. Select Personal workspace to add them to
4. Error seen - "You are not permitted to perform this action"

**Expected behavior**
Be able to share the collections to workspace or Collections are added to personal workspace.

**Screenshots**
![Unauthorized](https://user-images.githubusercontent.com/47771757/55545658-4b2c2b80-56eb-11e9-80c7-d891db722315.jpg)

**App information (please complete the following information):**
 - App Type - Native App
 - Postman Version - 7.0.7
 - OS: macOS

**Additional context**
Issue seen after joining another team

**Comment by preethammavin** [comment]
We are tracking the issue for the same #6224 
We will update it there once we have pushed a fix
