### ISSUE TITLE
[Feature] Remember docs collapsing

### ISSUE THREAD

**Issue by aeoris** [a85/POSTMan-Chrome-Extension#623]
The markdown docs for the services is a pretty neat feature, but it's kind of annoying to have the docs expanded every single time I open a service definition, even though I collapse it every time (since I already know how it works!).

My suggestion is to remember the collapse status on a per-service basis, with an indication (ie: an icon, whatever) to show that there's documentation in there.

Thanks!

**Comment by a85** [comment]
Fixed in v3.0! Coming soon in a couple of weeks.
