### ISSUE TITLE
Prevent or warn collection import if they would be archived after importing

### ISSUE THREAD

**Issue by ash007-postman** [a85/POSTMan-Chrome-Extension#6230]
**Describe the bug**
Import option doesn't let you import a larger number of requests than subscription supports into a shared workspace.

**To Reproduce**
1. Click on Import button
2. Select a file you would want to Import
3. Import succeeds and everything appears in the app.
4.  Sometime later, they all disappear into the archive.

**Expected behavior**
The application is working as expected, but it would be a good option to have a pop-up/ warning that mentions "Import data is larger than the subscription the user is already in"

**Screenshots**

**App information (please complete the following information):**
- App Type - Native App
- Postman Version - 7.0.7

**Additional context**
Without this feature, it becomes tedious to filter out the required archives as all of them populate there.

**Comment by benfletcher** [comment]
Alternatively, I would suggest that *all* imports default to a local non-shared workspace and then allow the user to manually add to a shared workspace. I think this would make the workflow more intuitive and prevent user foot-gunning. 

This is especially important when dealing with imports from the [Postman API Network](https://www.getpostman.com/api-network/).

The other point with the auto-archiving is that it's unexpected that the app allows too many requests to be created and then auto-archives *every single* request. Some other ways to deal with this:
- prevent adding too many requests (disable the 'save' button)
- disable newest requests that put you over the limit (gray them out allowing only the 'delete' button to work)
- require reducing the total before any requests from the collection can be executed (like prior option, but applied to entire workspace)

The pain and frustration of auto-archiving a team's work without any warning is hard to convey until you experience it yourself.

**Comment by a85** [comment]
I agree that archiving automatically can be frustrating. Auto archiving should not happen directly on import any more. We start archiving only after a certain period and after repeated warnings. Let me know if this is still happening! Closing this for now.
