### ISSUE TITLE
Collection runner slows down dramatically when user not interacting with window

### ISSUE THREAD

**Issue by jimm-porch** [a85/POSTMan-Chrome-Extension#6233]
I love Postman and occasionally use the Collection Runner to reprocess large batches of API calls.

It seems like the runner will slow down when mouse click/scroll events are not happening in the runner window.  I'm using the native Mac client 7.0.7.

For example I'm processing a file of 20,000 records and noticed in downstream services that the throughput to the API drops when I'm not mousing around in the runner.  Here's an example:

![image](https://user-images.githubusercontent.com/8631234/55584234-a3a5fd80-56d8-11e9-95ac-f5c275aaa5d7.png)

I started the runner at 12:25 in that chart, walked away for a bit, and when I came back the progress had not changed.  When I clicked on the UI the progress moved again and I saw the throughput on my remote service endpoint pick back up again.

Additionally there is a UI quirk at the bottom of the runner where it shows the status, like "Running Tests", "Sending request", etc.  That status doesn't update unless I am clicking in the UI or scrolling with the mouse wheel.  It never updates if the window doesn't have focus, or if I'm just moving the mouse - I have to click or send scroll events.

As a tool for batch processing this really reduces the usefulness of the runner, since you have to manually keep it alive while it's working.

Steps to reproduce:

1. Create a service which allows you to measure incoming requests.
2. Use the collection runner to hit that service 10,000 times.
3. Walk away for a while, stop interacting with it, etc.
4. Observe the throughput drop on the service when the runner is not being stroked.

**Comment by jimm-porch** [comment]
Further, if the screen saver comes on, the runner seems to completely halt.

![image](https://user-images.githubusercontent.com/8631234/55585675-0ea50380-56dc-11e9-84c3-3e6ea013b3f2.png)

The huge drop at 1:05 in the chart is when I walked away and the screensaver came on.  My computer is powered on, the screen saver was running, so it's not like the machine went to sleep.

The traffic goes back up after I got back because I resumed interacting with the runner.

**Comment by jimm-porch** [comment]
Just to pile on - I observed the same kind of near-total drop in activity while I was using the machine for other apps.  I had simply not come back to Postman in a few minutes to touch it.  It definitely seems to require constant love and attention or it gets depressed.

**Comment by jimm-porch** [comment]
Final observation - the actual API endpoint calls had stopped but the progress circle would still increment gradually as long as I interacted with the runner UI.

![image](https://user-images.githubusercontent.com/8631234/55588292-3f883700-56e2-11e9-88aa-aba1c0610018.png)

It had stopped making API calls at 1:35pm but the progress meter kept functioning (when I touched the UI).

**Comment by DannyDainton** [comment]
Hey @jimm-porch 

Is this something that you're still having an issue with on the latest version?

**Comment by jimm-porch** [comment]
@DannyDainton thanks for following up. Unfortunately I don't really have any new information on this since I stopped using Postman for these kinds of batch processes after all that trouble back in 2019.  (I still use it on a daily basis for ad-hoc requests.)  Feel free to close the ticket if nobody else is experiencing this anymore.

**Comment by mccannt** [comment]
Closing this issue out. 
If others experience the same issue, please let us know.

**Comment by ahtavan** [comment]
@mccannt 
I am still facing this issue in latest postman v10.20.0
Can this be looked into & do the needful to fix this issue.

**Comment by ahtavan** [comment]
> Closing this issue out. If others experience the same issue, please let us know.
@mccannt
I am still facing this issue in latest postman v10.20.0
Can this be looked into & do the needful to fix this issue.

**Comment by naresh-ale** [comment]
> Closing this issue out. If others experience the same issue, please let us know.

@mccannt
I am still facing this issue in latest postman v10.20.0
Can this be looked into & do the needful to fix this issue.

**Comment by mccannt** [comment]
@DannyDainton Flagging this. Maybe you can help out here?
