### ISSUE TITLE
App launch blocked after Ubuntu update

### ISSUE THREAD

**Issue by kmuret-scr** [a85/POSTMan-Chrome-Extension#6237]
After updating Ubuntu 18

I can't launch the application here the terminal output when tying to start from command line :+1: 

`Gtk-Message: 08:41:28.119: Failed to load module "canberra-gtk-module"`
`1554446489888 main info ["Booting Postman 6.6.1, linux-4.15.0-47-generic on x64"]`
`1554446489890 main info ["EventBus\\x7einitialize - Success"]`
`1554446489893 main info ["UpdateHandler\\x7einit - Success"]`
`1554446489894 main info ["RuntimeExecutionService\\x7einitialized: Success"]`
`1554446489958 main info ["ProtocolHandler\\x7einit - Success with status: true]"]`
`1554446489983 main error ["WindowManager\\x7egetSharedWindow: Shared window is not available"]`

**Comment by SamvelRaja** [comment]
@kmuret-scr  Could you verify it is regarding https://github.com/postmanlabs/postman-app-support/issues/6217#issuecomment-479354791.

If so, can you share logs from `PATH_TO_POSTMAN/Postman/log.txt` ?

**Comment by preethammavin** [comment]
Closing the issue has with the current information , we are not able to deduce the issue. Please feel free to reopen the issue with the required information so that we can get it resolved.
