### ISSUE TITLE
Javascript language version support

### ISSUE THREAD

**Issue by benfletcher** [a85/POSTMan-Chrome-Extension#6240]
**Describe the bug**
No reference to which Javascript language features are supported. Trial and error required to determine JS spec feature support.

**To Reproduce**
1. Put `console.log("Hello world!".padStart(25, ' ');` in any script block.
1. Send request.
1. See error

**Expected behavior**
A reference to which javascript engine / version is used so that users can know which newer language features are available without trial and error.

[The specific `padStart()` method in caniuse.com](https://caniuse.com/#search=padstart) shows that support was added some time ago in most browser engines. 

**Screenshots**
n/a

**App information (please complete the following information):**
 - Native app
 - Postman Version 7.1.0-canary01
 - OS: MacOs 10.14.4

**Additional context**
I've searched everywhere I can think of for this info. Perhaps the Postman Console itself could have a link to the info so that documentation, if it does exist, is easy to find.

**Comment by shamasis** [comment]
Agreed. We will document this in upcoming iterations.

cc @ArifPMan

**Comment by DannyDainton** [comment]
Hey @benfletcher 

The error you described is no longer part of the latest version of the native desktop app.

<img width="722" alt="Screenshot 2020-08-15 at 10 29 45" src="https://user-images.githubusercontent.com/17089546/90309669-62377c00-dee2-11ea-8c97-b35a56ed809a.png">

I'm going to close this issue and open up one on our docs repo to add this information..
