### ISSUE TITLE
Documenter – cURL / Go / jQuery Example requests not populating

### ISSUE THREAD

**Issue by chrisdeso** [a85/POSTMan-Chrome-Extension#6241]
**Describe the bug**
For newly-published documentation – example requests in cURL, Go and jQuery aren't populating.

**To Reproduce**
1. Publish a collection
2. Toggle the `Language` on the published documentation between cURL, Go and jQuery
3. See that no example requests populate

Alternatively:
1. Navigate to my recently-published copy of Postman Echo – [https://documenter.getpostman.com/view/1907870/S1EJXM9y](https://documenter.getpostman.com/view/1907870/S1EJXM9y)
2. Toggle the `Language` on the published documentation between cURL, Go and jQuery
3. See that no example requests populate

All other languages are populating as expected.

**Expected behavior**
Example requests to populate

**Screenshots**
cURL
![image](https://user-images.githubusercontent.com/4734306/55650520-89891f80-57ab-11e9-8ccf-132e28d8b2ab.png)

Go
![image](https://user-images.githubusercontent.com/4734306/55650542-99a0ff00-57ab-11e9-96f4-2a148d6d56a9.png)

jQuery
![image](https://user-images.githubusercontent.com/4734306/55650560-a58cc100-57ab-11e9-8a57-939d9835ad19.png)

**App information (please complete the following information):**
Browsers tested:
- Chrome Version 73.0.3683.86
- FIrefox Version 65.0

**Additional context**
[Filed by Postman]

**Comment by dhineshwiz** [comment]
@chrisdeso This issue is fixed from our end
