### ISSUE TITLE
set collection default host

### ISSUE THREAD

**Issue by ghost** [a85/POSTMan-Chrome-Extension#6243]
**Is your feature request related to a problem? Please describe.**
my host will change, I don't want to reset all URL
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by shamasis** [comment]
@cn-js-git - have you tried using `{{variable}}` for the host part of your URLs? I define my requests in a form of `{{base_url}}/my/endpoint`. Then keep the `https://mydomain.com` as an environment variable.
