### ISSUE TITLE
Collections disappear when trying to save

### ISSUE THREAD

**Issue by crummy** [a85/POSTMan-Chrome-Extension#6244]
When I try to save a request, none of my collections appear. When I create a collection from this screen, it disappears quickly from the list and I cannot save to it.

**To Reproduce**
1. Create a collection
2. Click Save on a request
3. Observe no collections have appeared in the "Select a collection..." list
4. Click Create Collection, and press enter
5. The collection briefly appears, then a second later disappears (though I can see it in the list of collections in the main UI in the dimmed out background)
6. Click Save
7. "Could not create request" pops up

**Expected behavior**
* In step 3, my collections should be present in the Save Request dialog.
* In step 5, the collection should not disappear.
* Step 7 should be success.

**Screenshots**
![image](https://user-images.githubusercontent.com/690626/55700871-5bf2df00-5a14-11e9-9a21-b971488eb34b.png)
![image](https://user-images.githubusercontent.com/690626/55700879-63b28380-5a14-11e9-9e98-a1d464029351.png)

**App information (please complete the following information):**
 - App Type: Native
 - Postman Version: 7.0.1
 - OS: macOS Mojave 10.14.4 (18E226)

**Additional context**
* I tried blowing away my ~/Library/Application Support/Postman folder. No change.

**Comment by harryi3t** [comment]
@crummy Could you send us the logs at help@getpostman.com with the subject line "Logs for GitHub #6244"?
Open the logs directory from "View -> Developer -> View logs in Finder"

**Comment by crummy** [comment]
Logs have been submitted, but in the mean time, the issue seems to have disappeared. Simultaneously, a few collections from years ago when I last used Postman appeared, as if my account just synced after a long delay.

**Comment by harryi3t** [comment]
@crummy Sorry, I had forgotten to update the thread.
We had found an internal glitch with your account (Your workspace wasn't synced properly) due to which this was happening and had fixed it on Tuesday. As you have mentioned this is fixed for you, I will be closing this ticket.
