### ISSUE TITLE
How to transmit global variables from pre-request script to a raw body in Postman?

### ISSUE THREAD

**Issue by Michal-Kolomanski** [a85/POSTMan-Chrome-Extension#6245]
Hello,
I am generating a random login and a password in pre-request script in postman like this:

![pre-req](https://user-images.githubusercontent.com/47147210/55711279-ac564680-59ec-11e9-9d99-731c4a632ac3.png)

and I want to transmit this random login and password to a raw body (json):

![body](https://user-images.githubusercontent.com/47147210/55711588-41593f80-59ed-11e9-8b50-010be8351217.png)

How can I do this?  

## App Details:

```
Postman for Windows 10
Version 7.0.7
```

**Comment by codenirvana** [comment]
@michal19256 You can use `{{variableName}}` which will be replaced with its current value when Postman resolves the variable. In your case:
```javascript
{
    "login": "{{login}}",
    "password": "{{password}}"
}
```

Refer: https://learning.getpostman.com/docs/postman/environments_and_globals/variables/#accessing-variables-in-the-request-builder

**Comment by Michal-Kolomanski** [comment]
> @michal19256 You can use `{{variableName}}` which will be replaced with its current value when Postman resolves the variable. In your case:
> 
> ```js
> {
>     "login": "{{login}}",
>     "password": "{{password}}"
> }
> ```
> 
> Refer: https://learning.getpostman.com/docs/postman/environments_and_globals/variables/#accessing-variables-in-the-request-builder

This solution doesn't work. The "login" and  the "password" are recognizing as a string {{login}}, {{password}} (not my global random variables) :(

**Comment by codenirvana** [comment]
@michal19256 Make sure your global variables are set correctly.
The issue is, you are assigning the return value from `console.log` to the global variable.

It should be: `pm.globals.set('login', getRandomWord(6));`

<img width="1017" alt="Screenshot 2019-04-08 at 3 37 21 PM" src="https://user-images.githubusercontent.com/4865836/55716353-6319ed00-5a14-11e9-8ba1-305bee5a13be.png">
