### ISSUE TITLE
Digital Signature of Postman win64-setup.exe is not valid

### ISSUE THREAD

**Issue by DaHoert-sO** [a85/POSTMan-Chrome-Extension#6246]
**Describe the bug**
The digital signature which the windows install binaries are signed with ran out on 28.03.2019 and our company doesn't allow installations of applications without valid signature.

**Screenshots**
![2019-04-08 11_36_25-Downloads](https://user-images.githubusercontent.com/46928502/55714243-99467500-59f2-11e9-8c1e-fe88674034ab.png)

**Comment by SamvelRaja** [comment]
@DaHoert-sO  The timestamp you are seeing is the date on which the app is code-signed.
Our certificate has validity more than that 👍

**Comment by DaHoert-sO** [comment]
@SamvelRaja I'm sorry, ofcourse you're right and my install issue lies somewhere else and I have to investigate further
