### ISSUE TITLE
Unable to create monitor - Something went wrong while creating this monitor

### ISSUE THREAD

**Issue by cyrielle-hada** [a85/POSTMan-Chrome-Extension#6247]
**Describe the bug**
After deleting a collection from my workspace and re-added it, I am unable to create a monitor for it. 
An error message says `Something went wrong while creating this monitor`

**To Reproduce**
1. Go to the native app 
2. Add a monitor to a collection - click on **Create a monitor** 
3. Set up the configuration 
4. Under 3.Next steps see error below
![Screenshot 2019-04-08 at 11 42 38](https://user-images.githubusercontent.com/47351631/55717129-934f9480-59f0-11e9-8c01-9b122ae8bfd2.png)

**Expected behavior**
Get the monitor created for the collection. 

**App information (please complete the following information):**
 - Postman Version 7.0.7
 - OS MacOS 

**Additional context**
Developer Tools console
![Screenshot 2019-04-08 at 11 45 26](https://user-images.githubusercontent.com/47351631/55717328-fb05df80-59f0-11e9-9637-431fa454f104.png)

**Comment by RomanKoziolek** [comment]
Dear Postman Team,
in addition to this problem, when I finally managed to re-add the updated collection to be monitored, the collection that was added was the original, not the updated one.

**Comment by preethammavin** [comment]
@RomanKoziolek are you still facing the error on your side for the monitor? can you signout & sign in and try again for the same collection and let me know if the error persists.

**Comment by godfrzero** [comment]
@RomanKoziolek A couple of questions:

1. Which workspace is this collection in?
2. Is this happening for other collections as well, or only for this one?
3. Are you configuring this monitor to use an environment as well?

**Comment by cyrielle-hada** [comment]
@godfrzero @preethammavin Roman's issue seems to be fixed after recreating the collection that has been initially removed.
