### ISSUE TITLE
No Example requests in documentation

### ISSUE THREAD

**Issue by Raj-postman** [a85/POSTMan-Chrome-Extension#6248]
**Describe the bug:**
In Documentation, the "Example requests" are missing.

**To Reproduce**
1. Expand your collection
2. Click on 'View in web'
3. "Example requests" are missing

**Expected behavior**
Example requests should be visible in Documentation

**Screenshots**
![No Example request](https://user-images.githubusercontent.com/47771757/55725216-d890b800-5a2a-11e9-8793-4a0bf3105441.png)

**App information (please complete the following information):**
 - App Type - Native App
 - Postman Version - 7.0.7

**Additional context**
Issue is seen both in Published and Unpublished documentation.

**Comment by abhisekp** [comment]
Looks like this has been fixed :+1: :smile:

**Comment by Raja-Simha** [comment]
Yes!! Closing this issue.
