### ISSUE TITLE
Segfault on ubuntu 19.04

### ISSUE THREAD

**Issue by j0r0** [a85/POSTMan-Chrome-Extension#6249]
Hello,
Just upgraded to Ubuntu 19.04 x.
Downloaded the latest Postman 7.0.7

Getting a segfault when starting postman

08.04.19 15:18	kernel	Postman[19419]: segfault at fffffffffffff777 ip 000000000111e1fb sp 00007ffc92e06e10 error 5 in Postman[400000+466e000]

`uname -a`

`Linux georgi-M92p 5.0.0-8-generic #9-Ubuntu SMP Tue Mar 12 21:58:11 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by bherrmann7** [comment]
In Ubuntu 19.04,

```
$ sudo snap install postman
postman 6.7.1 from Postman, Inc. (postman-inc✓) installed
bob@togo:~$ postman 
Gtk-Message: Failed to load module "gail"
Gtk-Message: Failed to load module "atk-bridge"
Gtk-Message: Failed to load module "canberra-gtk-module"
Segmentation fault (core dumped)
```

downloading from the web site,
```
$ tar xfz Postman-linux-x64-7.2.2.tar.gz 
$ cd Postman
$  ./Postman 
./Postman: error while loading shared libraries: libgconf-2.so.4: cannot open shared object file: No such file or directory
```
Boo I say.  I say BOO!

**Comment by twitharshil** [comment]
Hi @j0r0 

Could you try out our early access Canary build? https://www.postman.com/downloads/canary/. We are testing some improvements that should address this particular issue. Do try and let us know.

**Comment by j0r0** [comment]
I think this is not valid anymore. I remember that the problem disappeared after some package updates.
