### ISSUE TITLE
Feature Request: Make it easier to search for monitors

### ISSUE THREAD

**Issue by chrisdeso** [a85/POSTMan-Chrome-Extension#6250]
**Is your feature request related to a problem? Please describe.**
With the addition of workspaces, not having one place to see all monitors that are running for a team makes it difficult to manage usage.

**Describe the solution you'd like**
An endpoint on the web dashboard that'll populate any/all monitors that are running.

**Describe alternatives you've considered**
Something similar to the above but in-app.

**Additional context**
[Filed by Postman]

**Comment by sankalp0o** [comment]
@chrisdeso the team admin (and billing too if i'm not wrong) can look at all the monitors at /usage/monitors.
We don't have short term plans to introduce a similar view for the app as for most people (specially admins and billing users), having this view on the web suffices. I'm closing this issue but feel free to reopen this in case this didn't answer the user's requirement in some way.
