### ISSUE TITLE
Dashboard: error when merging

### ISSUE THREAD

**Issue by JP-from-Postman** [a85/POSTMan-Chrome-Extension#6251]
[Reported on behalf of user -- see internal notes]
**Describe the bug**
After resolving all conflicts, clicking **Merge all changes,** then selecting Merge, the following error is shown:
```
**Something went wrong**
You can't merge with active conflicts in the diff
```
The **Merge all changes** button is greyed out until all conflicts have been resolved, so this error seems erroneous.

**To Reproduce**
Unknown (see internal notes)

**Expected behavior**
Changes are merged

**Screenshots**
![mergeerror](https://user-images.githubusercontent.com/43283131/55763151-ac6d3b00-5a1a-11e9-8684-b7a95cf99c60.png)

**App information (please complete the following information):**
 - App Type: Native app
 - Postman Version: 7.0.7
 - OS: Windows

**Additional context**

**Comment by JP-from-Postman** [comment]
Issue is still ongoing. User was able to find a workaround for now:

`I've worked around this (duplicating the forked branch creates a copy that's no longer considered a fork, allowing me to clean up the old collections)`

**Comment by RuggeriLuca** [comment]
Hello, 
i have the same error. is it a know issues ?

**Comment by preethammavin** [comment]
@RuggeriLuca we have deployed a fix for the same can you verify if you are still seeing any errors on your side.

**Comment by yogirc** [comment]
@preethammavin 
i have the same error now.

**Comment by preethammavin** [comment]
@yogirc can you write to us at help@getpostman.com with the github issue id as reference so that we can take a look at it.

**Comment by Raj-postman** [comment]
App Version: v7.1.1
Os: Windows
Same issue. The Merge all changes button is greyed out until all conflicts have been resolved.

**Comment by JP-from-Postman** [comment]
One user has been able to workaround this issue by manually resolving conflicts directly in the requests themselves, although this is obviously not ideal.

**Comment by ankit-m** [comment]
Issue fixed.

**Comment by cre8value** [comment]
Still seeing this issue in Feb 2020, FYI.

**Comment by smartlearner1520** [comment]
> Still seeing this issue in Feb 2020, FYI.

same, got the same issue even when there is not any diff. it shows me pull request and cannot pull/merge....

**Comment by LarryFish92** [comment]
I think I'm getting the same issue two years later. As you can see I have chosen one option for each of my merge conflicts. I cannot see any further options for this so I would think that means I have resolved them. But no matter what combination of resolutions I choose for the conflicts I still get this error. I've tried everything to get it to work it is infuriating. I just do not understand what I'm doing wrong.
<img width="1028" alt="Screen Shot 2021-05-27 at 11 24 20 AM" src="https://user-images.githubusercontent.com/84923030/119855077-9ca55f00-bedf-11eb-9841-35cdf1d9eb12.png">
<img width="1043" alt="Screen Shot 2021-05-27 at 11 22 36 AM" src="https://user-images.githubusercontent.com/84923030/119855186-b2b31f80-bedf-11eb-86c5-a46f3fbf2938.png">
<img width="340" alt="Screen Shot 2021-05-27 at 11 19 17 AM" src="https://user-images.githubusercontent.com/84923030/119855262-c2326880-bedf-11eb-96c6-87db1c854511.png">
