### ISSUE TITLE
Native Wayland Support

### ISSUE THREAD

**Issue by ambasta** [a85/POSTMan-Chrome-Extension#6252]
**Is your feature request related to a problem? Please describe.**
Postman fails to launch in pure wayland environment. Currently postman can be launched via X running on wayland via Xwayland, but native support is missing.  Launching postman in a wayland native environment complains of missing libgtk-x11-2.0.so.0

**Describe the solution you'd like**
Implement native wayland support for postman

**Describe alternatives you've considered**
N/A

**Additional context**
Platform: Linux
Compositing Server: Wayland
Postman Version: 7.0.7

**Comment by shamasis** [comment]
Our views on this is reflected at: https://github.com/electron/electron/issues/9056

We will update to latest Electron soon and hopefully this would get addressed.

**Comment by harryi3t** [comment]
Putting the workaround as suggested by a user [here](https://github.com/postmanlabs/postman-app-support/issues/7534#issuecomment-577670535)
> Working command: DISABLE_WAYLAND=1 snap run postman

> I have just edited .desktop file (/var/lib/snapd/desktop/applications/postman_postman.desktop) - added that env variable and now it is OK.

**Comment by jsebrech** [comment]
> Putting the workaround as suggested by a user [here](https://github.com/postmanlabs/postman-app-support/issues/7534#issuecomment-577670535)
> 
> > Working command: DISABLE_WAYLAND=1 snap run postman
> 
> > I have just edited .desktop file (/var/lib/snapd/desktop/applications/postman_postman.desktop) - added that env variable and now it is OK.

I made that change but it reverted automatically. Perhaps as a temporary measure the DISABLE_WAYLAND=1 could be added in the default desktop file provided by the snap?

**Comment by ambasta** [comment]
> Putting the workaround as suggested by a user [here](https://github.com/postmanlabs/postman-app-support/issues/7534#issuecomment-577670535)
> 
> > Working command: DISABLE_WAYLAND=1 snap run postman
> 
> > I have just edited .desktop file (/var/lib/snapd/desktop/applications/postman_postman.desktop) - added that env variable and now it is OK.

This does nothing for native wayland support and is rather offtopic

**Comment by vegabook** [comment]
bump

**Comment by mccannt** [comment]
Closing this issue as it has now been resolved.
Please feel free to reopen with the steps to reproduce if the issue persists.
