### ISSUE TITLE
DELETE requests behaving like GET requests

### ISSUE THREAD

**Issue by justjess678** [a85/POSTMan-Chrome-Extension#6253]
## App Details:
```
Postman for Linux
Version 7.0.7
linux 4.9.0-8-amd64 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there:
I believe this bug has always been there, certainly on my current version

 2. Expected behaviour:
When sending a `DELETE` request to my site, Postman behaves as if it was a `GET` request, and does not delete the item

 3. Console logs:
```
DELETE
http://127.0.0.1:6942/devices/787022c7-cff7-4c5e-9206-b71283002f2f
11:32:45.450

Request Headers:
cache-control:"no-cache"
Postman-Token:"533df8e4-66b3-488c-a90a-683fa74b9620"
User-Agent:"PostmanRuntime/7.6.1"
Accept:"*/*"
accept-encoding:"gzip, deflate"
referer:"http://127.0.0.1:6942/devices/787022c7-cff7-4c5e-9206-b71283002f2f"
Response Headers:
Server:"gunicorn/19.9.0"
Date:"Tue, 09 Apr 2019 09:32:45 GMT"
Connection:"close"
Content-Type:"application/json"
Vary:"Accept, Cookie"
Allow:"GET, PUT, PATCH, DELETE, HEAD, OPTIONS"
Content-Length:"345"
X-Frame-Options:"SAMEORIGIN"
Response Body:
id:"787022c7-cff7-4c5e-9206-b71283002f2f"
number:2
name:"Device 2"
last_received_battery_percentage:42
last_received_position_latitude:-33
last_received_position_longitude:151
last_received_position_radius:1000
last_received_position_is_from_atlas:true
last_received_city_name:"Whittingham"
last_received_temperature:21
```
Also note my test failure:
`Status code is 204 | AssertionError: expected response to have status code 204 but got 200`

 4. Screenshots:
List of devices *BEFORE* `DELETE` request
![Before running DELETE request - Imgur](https://user-images.githubusercontent.com/17336608/55790296-57820100-5abc-11e9-9767-157e8e68f790.png)

`DELETE` request output
![Screenshot from 2019-04-09 11-36-09](https://user-images.githubusercontent.com/17336608/55790338-6cf72b00-5abc-11e9-8856-72af64b21970.png)

List of devices *AFTER* `DELETE` request
![Screenshot from 2019-04-09 11-35-56](https://user-images.githubusercontent.com/17336608/55790363-797b8380-5abc-11e9-830d-d1a62071a31c.png)

To reproduce the problem simply call a `DELETE` request and verify whether the item has been deleted.
 The bug does not come from my API as it behaves as expected when sending requests via curl

**Comment by shamasis** [comment]
Just sent a request from my app to https://postman-echo.com/delete (https://docs.postman-echo.com/#1f0fad16-6bff-5130-2056-7f4af6b18912) and it works fine. 

I can think of only one scenario where a request method can change and that’s when server issues a 3XX redirection. Maybe you could go to settings, turn off the feature to follow redirects, and see if that’s the case? If that’s not the case then I’m afraid that at my end I’m unable to reproduce this and then maybe a public example endpoint will help me debug this.

**Comment by justjess678** [comment]
@shamasis I tried turning off the redirect, the only difference was that the device was not listed on the `DELETE` request, but was still not actually deleted. I will ask my colleagues if they can provide a public endpoint for you to try

**Comment by justjess678** [comment]
@shamasis ok so if you want to test it on our case:
create a workspace here: http://dev.iot-rocket.space and create a workspace and account.
Once you're in your workspace, click the "populate" button (bottom left) then go to the alerts section (left sidebar, bell icon). From here you can experiment with creating and deleting alerts: use the access token from here to run the tests in Postman

**Comment by shamasis** [comment]
@justjess678 ok. Before I do that, I need more information from your end to validate a few stuff. Can you make a DELETE call from your postman app to https://postman-echo.com/delete and tell me what’s the response you’re getting?

**Comment by justjess678** [comment]
Sure thing, I get this output:
```
{
    "args": {},
    "data": {},
    "files": {},
    "form": {},
    "headers": {
        "x-forwarded-proto": "https",
        "host": "postman-echo.com",
        "accept": "*/*",
        "accept-encoding": "gzip, deflate",
        "cache-control": "no-cache",
        "cookie": "sails.sid=s%3A8YPbr28_BB1JtlaYJrsay4U_GOVflxtj.pPVnIHt8zkSEMw8XtT3utxXo92Csq4QASpgb8ve0QOI",
        "postman-token": "9cb31b3e-2ed9-437c-b994-f638a379564b",
        "user-agent": "PostmanRuntime/7.6.1",
        "x-forwarded-port": "443"
    },
    "json": null,
    "url": "https://postman-echo.com/delete"
}
```
and in the console I have:
```
DELETE
https://postman-echo.com/delete
13:44:35.796

Request Headers:
cache-control:"no-cache"
Postman-Token:"9cb31b3e-2ed9-437c-b994-f638a379564b"
User-Agent:"PostmanRuntime/7.6.1"
Accept:"*/*"
Host:"postman-echo.com"
cookie:"sails.sid=s%3A8YPbr28_BB1JtlaYJrsay4U_GOVflxtj.pPVnIHt8zkSEMw8XtT3utxXo92Csq4QASpgb8ve0QOI"
accept-encoding:"gzip, deflate"
content-length:""
Response Headers:
Content-Encoding:"gzip"
Content-Type:"application/json; charset=utf-8"
Date:"Thu, 11 Apr 2019 11:44:35 GMT"
ETag:"W/"1c6-26IRTbXUcjpABswIJyHqMiM9rA0""
Server:"nginx"
set-cookie:"sails.sid=s%3ACqqY9kvbmOk426328nqcVx2bEahPSldF.vu9NY81Jr%2FD2Z8Ny7rJiDacOqAFRAYgUUVM%2FyWtKYRs; Path=/; HttpOnly"
Vary:"Accept-Encoding"
Content-Length:"339"
Connection:"keep-alive"
Response Body:
args:
data:
files:
form:
headers:
json:null
url:"https://postman-echo.com/delete"
```
Does this help?

**Comment by shamasis** [comment]
Yes. This means that postman is sending out DELETE request just fine. We need to now specifically see if there’s something in your application code that’s causing this. I’m afraid, that’s something only you can do best since you have the maximum context.

Having said that - you should post this thread in our community and you may encounter someone who has worked on a situation similar to yours. community.getpostman.com

On that note, I’m closing this issue here. And if you do happen to find the cause, please let me know.

**Comment by codenirvana** [comment]
@justjess678 From console logs I see `referer` header was sent while making the request, which means the request does go through a redirect. Now, as you mentioned the request is behaving like `GET` which means that redirect happened with either 301 or 302 status code.

This is happening because as per RFC: https://tools.ietf.org/html/rfc7231#section-6.4.2
```
For historical reasons, a user agent MAY change the request method from POST to GET
for the subsequent request. If this behavior is undesired, the 307 (Temporary Redirect)
status code can be used instead.
```

So, to preserve the HTTP method on redirect, the ideal status code should be 307 or 308.

For your use case, I would suggest you try making the request with a `/` at the end. Because I have seen similar issues in the past where server redirects to the same URL but with a `/` at the end.

In Postman App try making a request to:
`http://127.0.0.1:6942/devices/787022c7-cff7-4c5e-9206-b71283002f2f/` instead.

Note: Our underlying request sending library does support an option which toggles this behavior and redirects with the original HTTP method. We will expose this option in the request settings soon.

**Comment by AminShahidi98** [comment]
> @justjess678 From console logs I see `referer` header was sent while making the request, which means the request does go through a redirect. Now, as you mentioned the request is behaving like `GET` which means that redirect happened with either 301 or 302 status code.
> 
> This is happening because as per RFC: https://tools.ietf.org/html/rfc7231#section-6.4.2
> 
> ```
> For historical reasons, a user agent MAY change the request method from POST to GET
> for the subsequent request. If this behavior is undesired, the 307 (Temporary Redirect)
> status code can be used instead.
> ```
> 
> So, to preserve the HTTP method on redirect, the ideal status code should be 307 or 308.
> 
> For your use case, I would suggest you try making the request with a `/` at the end. Because I have seen similar issues in the past where server redirects to the same URL but with a `/` at the end.
> 
> In Postman App try making a request to:
> `http://127.0.0.1:6942/devices/787022c7-cff7-4c5e-9206-b71283002f2f/` instead.
> 
> Note: Our underlying request sending library does support an option which toggles this behavior and redirects with the original HTTP method. We will expose this option in the request settings soon.

it worked for me with adding a /!! tnx
