### ISSUE TITLE
Postman shows wrong request details

### ISSUE THREAD

**Issue by m3dbedb** [a85/POSTMan-Chrome-Extension#6257]
**bug description**
I have a collection with several requests. I execute a collection step by step using keyboard keys "down" and "ctrl+enter". Since version 7.0.6 I have notised when I select 11-th request of collection Postman shows request body from previous request, and the issue have stable reproductivity

**To Reproduce**
1. Open collection with more than 10 requests
2. Click on 1st request
3. hit ctrl+enter
4. go to step 2 with "down" button
5. repeately select and run requests untill you see a body from previous request

**Expected behavior**
Postman older than 7.0.6 does not produce the bug

**App information:**
 - App Type: Native
 - Postman Version 7.0.7
 - OS: Windows 7 32

**Comment by sujayvenaik** [comment]
Hey @m3dbedb 
Wanted to confirm one thing, when you select one request and press send, then the next request should open in a new tab. Is it happening so?

Also, are you doing rapidly, as in press down send and then again?

**Comment by m3dbedb** [comment]
The error happens on a new tab (when I jump between tabs, postman duplicates previous tab and replace it contents, sometimes some data remain same as on parent tab). I execute one step with ctrl+enter, wait for reply (not less than a second), hit down, and wait postman to render new tab (again i takes of about 1-2 seconds). To run 10 steps it takes of about 30 seconds. Usually the bug happens after 10-th step.

**Comment by m3dbedb** [comment]
currently i don't see the issue in version 8.0.3 for windows
