### ISSUE TITLE
Feature Request: Export results in Junit format

### ISSUE THREAD

**Issue by DarrylGwinnett** [a85/POSTMan-Chrome-Extension#6258]
I'm aware that Newman can do this, but having to export our tests and run them in Newman really doesn't fit our workflow.

When A collection is run and we can export results,provide the user with the choice of either exporting it in JSON, or in Junit XML, this will allow us to import our results to update tests in Jira.

**Comment by malvikach** [comment]
Hi @DarrylGwinnett 👋 

Collection Runner results can be exported in JSON format. 

I know it's been a while, but if this is a workflow you still use, I am keen to know why you update these tests on Jira and how they are used from there on. 

I am closing this issue, but feel free to provide your feedback here or drop me a note at malvika.chaudhary@postman.com. 

Regards!
Malvika
