### ISSUE TITLE
Active theme indicator does not change for other Postman windows

### ISSUE THREAD

**Issue by ritwijsinha** [a85/POSTMan-Chrome-Extension#6262]
**Describe the bug**
Active theme indicator does not change for other Postman windows upon changing the theme. 

**To Reproduce**
1. Open multiple Postman windows.
2. Change the theme in one of them.

**Expected behavior**
All the windows should indicate the correct active theme.

**Screenshots**

![image](https://user-images.githubusercontent.com/19693841/55870542-6f35b400-5ba6-11e9-9bf0-06667d354edc.png)

**App information (please complete the following information):**
Postman for Mac
Version 7.0.7
OS X 18.2.0 / x64

**Comment by numaanashraf** [comment]
This is resolved in v7.23
