### ISSUE TITLE
Cannot share collections

### ISSUE THREAD

**Issue by Ramya-From-Postman** [a85/POSTMan-Chrome-Extension#6263]
**Describe the bug**
When trying to "Share a collection" it is throwing an error "**You do not have permission to share this collection**" This happens with existing collections and with newly created ones. I can neither do this with my own personal workspace nor in the team workspace.

**Steps to reproduce the behavior:**
1. Go to any workspace (personal or team)
2. Click on 3dots (...) next to any collection & choose share collection 
3. See error

**Expected behavior**
Collections should get shared without any errors

**Screenshots**
![image](https://user-images.githubusercontent.com/40994626/55875603-13bdf300-5bb3-11e9-9168-8abde1e4109e.png)

**App information (please complete the following information):**
 - App Type:  Native App
 - Postman Version: v7.0.7 
 - OS: Windows

**Additional context**
Logs are shared at help@getpostman.com

**Comment by numaanashraf** [comment]
The fix for this issue has been released in v7.0.8.

**Comment by bruha** [comment]
Same issue in Postman v7.21.1
