### ISSUE TITLE
Update microcopy (and possibly the icon) on top menu bar

### ISSUE THREAD

**Issue by BrandonGordon126** [a85/POSTMan-Chrome-Extension#6267]
**Describe the bug**

The tooltip for the "heart" icon on the top menu bar says "Tweet about us," though when you click the icon it takes you to the Medium Engineering blog 

**To Reproduce**
Open the app, 
Hover over the heart icon on the top menu bar
Click the heart icon 

**Expected behavior**
I would expect this to take me to twitter or allow me to post over social media 

**Screenshots**
![Screenshot 2019-04-10 09 43 26](https://user-images.githubusercontent.com/48736195/55897818-249c4380-5b76-11e9-93e8-ca9229a6b903.png)

**App information (please complete the following information):**
Native App, v. 7.0.7, macOS
 - Postman Version [e.g. 6.0.1]
 - OS: [e.g. macOS High Sierra 10.13.2]

**Additional context**

**Comment by DannyDainton** [comment]
A fixed for this issue will be going out to production in the next app version. The icon will remain the same but the tooltip has been removed.

**Comment by numaanashraf** [comment]
Closing this as the icon has been removed.
