### ISSUE TITLE
My collections have all disappeared!

### ISSUE THREAD

**Issue by zany2dmax** [a85/POSTMan-Chrome-Extension#6271]
## App Details:

6.7.4 for Mac

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there: All my collections have disappeared!  They used to be on the left of my screen and now they are gone and I can't see how to get that back.  I can go over to my Collecitons witht he Build/Browse and it will open a web page on them but not let me pick anf choose the APIs i need
 

What has happened????

Postman Pro user jleggett@qualys.com

**Comment by preethammavin** [comment]
@zany2dmax do you see all your collections in the Web Dashboard Workspaces (go.postman.co/workspaces)? 

Also the image shared by you was a personal image, I have gone ahead and removed it for security purposes.

**Comment by kamalaknn** [comment]
hey @zany2dmax 

Can you share your current app version you are on, you can find it on `Settings -> About`?

Can you send any screenshots from `View -> Developer -> Show DevTools(Shared)` and `View -> Developer -> Show DevTools (Current View)`?

Also to unblock yourself, you can try signing out and and signing in again. Please export/backup any unsycned changes before you signout.

**Comment by zany2dmax** [comment]
I deleted and reinstalled and got my collections to show back up onthe left side.  That was weird though.

**Comment by tmrdurgun** [comment]
Mine was Wiew > toggle sidebar :/

**Comment by preethammavin** [comment]
@tmrdurgun do you mean to say that when you clicked toggle of the sidebar the collections disappeared? Clicking on the toggle should get it back let us know if its not there.

**Comment by vacekj** [comment]
Also have this issue, toggling the sidebar does nothing. Reinstalling doesn't work.

**Comment by tmrdurgun** [comment]
@preethammavin  After I restarted my computer, my collections was hidden first and after i clicked toggle, it showed.
