### ISSUE TITLE
Echo "Learn More" link echos a blank file for download

### ISSUE THREAD

**Issue by Vivalldi** [a85/POSTMan-Chrome-Extension#6272]
**Describe the bug**
When on https://www.getpostman.com/integrations/ clicking the `Learn More` button in the Echo section (under integrations) the browser downloads a file with the following content -
```
This service has moved to https://postman-echo.com
```

**To Reproduce**
1. Go to 'https://www.getpostman.com/integrations/'
2. Scroll down to 'Postman Tools'
3. Click on `Learn More` under 'Postman Tools - Echo'
4. See file get downloaded

**Expected behavior**
To open browser tab in the correct location

**Screenshots**
Will add if requested

**App information (please complete the following information):**
 - App Type: N/A
 - Postman Version: N/A
 - OS: macOS High Sierra 10.14.4

**Comment by tristandenyer** [comment]
@Vivalldi Thank you for taking the time to send this our way! I really appreciate it.

Internal ticket created and prioritized. Will update this ticket when fixed.

**Comment by DannyDainton** [comment]
Closing this issue as it has now been resolved.

Please feel free to reopen with the steps to reproduce if the issue persists.
