### ISSUE TITLE
Incorrect syntax with pm.environment.set() causes bug in environment variable list

### ISSUE THREAD

**Issue by stephclleung** [a85/POSTMan-Chrome-Extension#6276]
**Describe the bug**
`pm.environment.set("envVarName", "newvalue")` sets a new value to the corresponding envVarName. During one of my requests, I was writing a test where I made the mistake of `pm.environment.set("envVarName" === "newvalue") `instead of the comma. The compiler does not pick up the syntax error, and instead inserts a new variable call "false" to the environment variable list.

**To Reproduce**
Steps to reproduce the behavior
1. Set up any request to an api. (In my case, I was sending a request to GitHub's API) 
2. Set a new environment variable , for example envVarName.
3. In Test script panel,  `pm.environment.set("envVarName" === "newvalue") `
3. Send. Request should go through fine. 
4. Click on "Environment Quick Look"

**Expected behavior**
A new variable "false" is added to the environment variable list. It does not hold any value.
Repeating the above steps can generate many more variables onto the list.

**Screenshots**
![image](https://user-images.githubusercontent.com/35399643/55954089-5a354f80-5c90-11e9-9fd2-092b52dd6dfd.png)

**App information (please complete the following information):**
 - App Type : Native App 
 - Postman Version : Version 7.0.7
 - OS: Windows 10

**Additional context**
It's not really a problem if you have correctly typed the line of code.
I'm not even entirely sure if this can be [called](url) a bug. I'm a newbie when it comes to coding, but since I can't find a related bug on the list, I thought you guys might find it useful to know about this.
Veteran coders probably won't experience this as they are less likely to make typos like I did 🤣

**Comment by shamasis** [comment]
Aah. Seems like something that must have been pretty tricky to debug. However, this is how JavaScript works. 

The only way to fix this would be having a section that shows where the variable “false” came from. That’s being tracked in some other issue IMHO. Will hunt down that issue soon and refer this issue in that one. Closing this for now.
