### ISSUE TITLE
"Pretty" tab fails to indent div content properly after emoji content

### ISSUE THREAD

**Issue by mcandre** [a85/POSTMan-Chrome-Extension#6277]
When I use an emoji literal in my HTML response, then Postman's prettifier no longer indents the surrounding HTML tags properly.

**Comment by numaanashraf** [comment]
@mcandre Could you share a publicly assessable endpoint that'll help us understand this issue better? Screenshots will help too.

**Comment by preethammavin** [comment]
Closing the issue has with the current information , we are not able to deduce the issue. Please feel free to reopen the issue with the required information so that we can get it resolved.
