### ISSUE TITLE
Templates with no config options displays Configuration Options page

### ISSUE THREAD

**Issue by loopDelicious** [a85/POSTMan-Chrome-Extension#6278]
New+ button > Templates tab > Select a template > Use the Template button

When I click Use the Template, there's a page that displays Configuration options (blank when there are no config options). I assume it's just loading, but it's just blank, then I click Next.

<img width="1273" alt="Screen Shot 2019-04-10 at 2 09 56 PM" src="https://user-images.githubusercontent.com/17693714/55991196-87690a00-5c5e-11e9-8ebb-507a91f5b5f4.png">

Consider not showing the Configuration options page when there are no config options.

**Comment by Raja-Simha** [comment]
Not a bug but should be rectified in the next release with inputs from design.

**Comment by preethammavin** [comment]
this issue has been resolved
