### ISSUE TITLE
API Network descriptions are not displaying in the app

### ISSUE THREAD

**Issue by loopDelicious** [a85/POSTMan-Chrome-Extension#6279]
New+ button > API Network tab 

Descriptions are no longer displaying in the API Network modal in the Postman app.

<img width="1392" alt="Screen Shot 2019-04-11 at 1 32 10 PM" src="https://user-images.githubusercontent.com/17693714/55991643-97cdb480-5c5f-11e9-8527-cf42de947f21.png">

<img width="1532" alt="Screen Shot 2019-04-11 at 1 31 24 PM" src="https://user-images.githubusercontent.com/17693714/55991769-e1b69a80-5c5f-11e9-8a5d-58f98b96416c.png">

**Comment by Raja-Simha** [comment]
Those empty states are supposed to be team descriptions which are populated from dashboard/team settings. Not a bug but we need better design the flow so that team descriptions are populated.
