### ISSUE TITLE
Request adding cache and token headers when set to off in settings

### ISSUE THREAD

**Issue by Joshuamay79** [a85/POSTMan-Chrome-Extension#6283]
**Describe the bug**
Temporary headers are being added to the request when settings are set to off.

**To Reproduce**
1. Go to settings
2. Toggle Send no-cache header to off
3. Toggle Send Postman Token header to false
4. Create request
5. Notice the automatic headers added to the request.

**Expected behavior**
Not adding these temporary headers when toggled to off.

**Screenshots**
![image](https://user-images.githubusercontent.com/1290574/56046881-da4bcb80-5d09-11e9-9923-27929feba337.png)
![image](https://user-images.githubusercontent.com/1290574/56046891-e20b7000-5d09-11e9-9991-b5ced8e56f40.png)

 - App Type Native Windows App
 - Postman Version 7.0.8
 - OS: Windows 10 version 1709

**Additional context**
This was not happening in 7.0.7. After updating this morning it started adding these headers.

Also is there a way to toggle viewing/adding temporary headers in the request? In 7.0.8 it started adding all of these temporary headers. it's quite distracting. 
![image](https://user-images.githubusercontent.com/1290574/56047282-b3da6000-5d0a-11e9-89a8-47c467e83706.png)

**Comment by shamasis** [comment]
The fix for this is in v7.0.9 for app... let us know if this works now.
