### ISSUE TITLE
Collection without any editor role

### ISSUE THREAD

**Issue by cyrielle-hada** [a85/POSTMan-Chrome-Extension#6284]
**Describe the bug**

With RBAC in v7 some collections appear to have no editor assigned.
The collection owner (creator) sees a padlock which doesn’t give him the permissions to edit the collection or to manage the roles. 

![CollectionPermission (1)](https://user-images.githubusercontent.com/47351631/56055579-b01dfc00-5d51-11e9-9cf1-9299af945a19.jpg)

As nobody else in the team has the permission to edit that collection in question, the entire team is completely locked out. 

**Expected behavior**
The owner (creator) of the collection should by default has the editor role on the collection.  

**Additional context**

- Collections that were owned by team members in the previous version, now can’t be accessed after migrating to version 7.  

- The workspace admin removed the collection from the workspace and then re-added them.

**Comment by preethammavin** [comment]
@cyrielle-hada  we have pushed a fix out to production for the same, this should not occur again. Closing the issue for now, do let us know if it is not solved.
