### ISSUE TITLE
Error Logging In: "...difficulties connecting to our authentication service"

### ISSUE THREAD

**Issue by JP-from-Postman** [a85/POSTMan-Chrome-Extension#6288]
**Describe the bug**
When signing in to the Postman app, user reports sporadic reoccurrences of the following error:

<img width="310" alt="Screen Shot 2019-04-12 at 3 31 42 PM" src="https://user-images.githubusercontent.com/43283131/56069575-873d3d00-5d38-11e9-89db-192c3840c5e8.png">

**To Reproduce**
1. Login to the Postman app
2. See error noted above
3. After a variable period of time, attempting to login will succeed

**Expected behavior**
Login is successful.

**Screenshots**

**App information (please complete the following information):**
 - App Type: Native app
 - Postman Version: 7.0.8
 - OS: Windows

**Additional context**

**Comment by hadimansouri** [comment]
Please change your authentication service. So many users have difficulty login by this service. It seems terrible!!
The more terrible issue is that the message does not give any useful information. It says simply "Something went wrong! We have some difficulty...!"
