### ISSUE TITLE
Cannot reset my password due to recaptcha

### ISSUE THREAD

**Issue by iensu** [a85/POSTMan-Chrome-Extension#6290]
**Describe the bug**

I am trying to reset my password but I can't get past the recaptcha step. I was clicking around on cars, bicycles, crossings... for about 2 minutes each time to no avail. Could you please remove recaptcha and use something else for verification? This is extremely frustrating. In the end I had to create a new account just to be able to use Postman. 

**To Reproduce**
1. Open the Postman app
1. Click 'trouble signing in'
1. Click 'I am not a robot'
1. Click and click and click and click the recaptcha images... 

**Expected behavior**
I expect to click the 'I'm not a robot button', then maybe click 2-3 times on a recaptcha image and then be able to send a reset account email.

**Screenshots**

**App information (please complete the following information):**
 - App Type: Native
 - Postman Version 7.0.7 (7.0.7)
 - OS: macOS High Sierra 10.13.2

**Additional context**

**Comment by preethammavin** [comment]
@iensu captcha is not something we control, it would be dependent on the client for verification.
