### ISSUE TITLE
Postman update on Linux

### ISSUE THREAD

**Issue by neilveil** [a85/POSTMan-Chrome-Extension#6295]
With every new update it never asks to update the software instead it downloads it without permission and the worst part is, it never uses the new downloaded version but downloads it again. This also results in the delayed start of the application as it starts only after downloading the latest update.

> How hard it is to make a software update feature, even a beginner software developer can make it. This kind of work is not expected from Postman team.

**Comment by a85** [comment]
Please file a bug report using the issue guidelines outlined while filing an issue.
