### ISSUE TITLE
Sharing an environment within Work spaces

### ISSUE THREAD

**Issue by richatyagi8** [a85/POSTMan-Chrome-Extension#6298]
I have my work spaces which I have shared with one of my team member. I have also shared the environment which has the base URL. Now the base URL IP address he is seeing is my Ip address where as the environment i created us different ip
**Expected behavior**
I was expecting to see My team mate the same base URI as I am seeing

**Screenshots**

**App information (please complete the following information):**
 - App Type -Native App
 - Postman Version  v7.0.7
 - OS: Windows 7

**Comment by numaanashraf** [comment]
@richatyagi8 This is intended. Current values are local and never automatically synced or shared with other teammates. Only initial values of the variables are synchronised with other members of the workspaces. You can find more details at https://learning.getpostman.com/docs/postman/environments_and_globals/sessions
