### ISSUE TITLE
Know who to contact to request permissions

### ISSUE THREAD

**Issue by loopDelicious** [a85/POSTMan-Chrome-Extension#6299]
I'm on Postman for Mac Version 7.0.7

When I try to share or edit a collection for which I do not have edit access, I see this message letting me know I don't have permission to do this.

<img width="1392" alt="Screen Shot 2019-04-15 at 11 02 13 AM" src="https://user-images.githubusercontent.com/17693714/56155463-cd301600-5f6f-11e9-897e-56344b6d6732.png">

It would be nice to see an option here that allows me to “Request Permissions”, see who can grant me this permission, or a way to request permissions in-app. 

Currently, I have to view the documentation or listing to see who the author is to request edit access (outside of the app). In this case, if I don’t know who the author is by their alias, then I don’t have a clear way to request permissions offline either.

**Comment by ArjunSingh-PM** [comment]
The user can request access if they do not have edit access to the collection. The option is presented when the user tries to move or manage roles on a collection.
![image](https://user-images.githubusercontent.com/53265429/195308470-a6f2baf4-71e6-40ba-a625-e25d1f532030.png)
