### ISSUE TITLE
Feature Request: Support for multiple CA certificates

### ISSUE THREAD

**Issue by chrisdeso** [a85/POSTMan-Chrome-Extension#6300]
**Is your feature request related to a problem? Please describe.**
With the addition of support for CA certificates, it would be great to add support for multiple CA certificates.

**Describe the solution you'd like**
The ability to add multiple CA certificates via the app's UI.

**Describe alternatives you've considered**
A programmatic way to access certificates stored locally.

**Additional context**
[Filed by Postman]

**Comment by codenirvana** [comment]
The single CA file should consist of one or more trusted certificates.

**Comment by shamasis** [comment]
You can append as many trusted certificates as you want to the single file.

**Comment by chrisdeso** [comment]
Thanks for clarifying @codenirvana && @shamasis!

FR Closed 😄.
