### ISSUE TITLE
Postman didn't show the default window in Mac OS

### ISSUE THREAD

**Issue by detectiveHLH** [a85/POSTMan-Chrome-Extension#6304]
**Describe the bug**
Postman didn't show the default window in Mac OS. I can see the UI window only if I add a new postman window.

**To Reproduce**
1. Open your postman.
2. Close this window.
3. Quit postman in Dock.
4. Open postman again.

**Expected behavior**
There is no window in sight

**Screenshots**

**App information (please complete the following information):**
 - Native App
 - Postman Version [7.0.7]
 - OS: [macOS Mojava 10.14.4]

**Comment by numaanashraf** [comment]
@detectiveHLH Thanks for reporting this. We're having trouble reproducing this issue at our end. Would it be possible to send us the logs from View > Developer > View Logs in Finder to help@getpostman.com? Please mention this issue number in the email subject, eg., "Logs for GH#6304".

**Comment by detectiveHLH** [comment]
@numaanashraf Of course. I have already sent an email to help@getpostman.com
Thanks a lot.

**Comment by kamalaknn** [comment]
Hey @detectiveHLH 

It looks like you have a window that is unreachable or too small. When you restart the app this default window is getting restored. 

To unblock yourself immediately you can forcefully remove all windows by doing
1. Quit the app
2. Run `rm ~/Library/Application\ Support/Postman/window`
3. Restart the app.

We will also look into how we can improve the experience when restoring the app with such cases.

**Comment by detectiveHLH** [comment]
@kamalaknn Thanks a lot. I did exactly you said. Now it's working. Thanks.

**Comment by jacky0915** [comment]
Same issue here, after doing 

> rm ~/Library/Application\ Support/Postman/window

the issues still remain
The folder didn't created also

**Comment by detectiveHLH** [comment]
> Same issue here, after doing
> 
> > rm ~/Library/Application\ Support/Postman/window
> 
> the issues still remain
> The folder didn't created also

Do you quit the app?

**Comment by jacky0915** [comment]
@detectiveHLH 
Yes sir,
I did follow all the steps mentioned above.
Still not showing any thing.
Even the about postman on the top menu also disabled.

**Comment by jacky0915** [comment]
@detectiveHLH 
I solved my problem by downloaded PostmanCanary
https://www.getpostman.com/downloads/canary

**Comment by detectiveHLH** [comment]
> @detectiveHLH
> I solved my problem by downloaded PostmanCanary
> https://www.getpostman.com/downloads/canary

Cool

**Comment by kamalaknn** [comment]
Hey @jacky0915 The suggested path was for macOS. Can you share the operating system configuration and the app version?

**Comment by jacky0915** [comment]
@kamalaknn Yes, I am using Mac OS High Sierra 10.13.6
the folder has been removed but after restart postman, it didn't create it back.

**Comment by detectiveHLH** [comment]
> @kamalaknn Yes, I am using Mac OS High Sierra 10.13.6
> the folder has been removed but after restart postman, it didn't create it back.

Or Maybe you should clean the cache and try again.

**Comment by detectiveHLH** [comment]
@jacky0915 
Delete the Postman folder at the following location on macOS. Open the finder `cmd + space` , paste `~/Library/Application Support/Postman` and hit return. And delete the cache folder.

**Comment by jacky0915** [comment]
@detectiveHLH 
I delete the cache file also the postman window didn't show up.
But is ok since i using PostmanCanary right now.

**Comment by detectiveHLH** [comment]
👍Cool. I will try it if the window goes wrong again.

**Comment by kamalaknn** [comment]
@jacky0915 Can you download latest version of stable channel of Postman from https://www.getpostman.com/downloads/ and verify this?

If you are still seeing this could you send logs from `~/Library/Application\ Support/Postman/logs` and send to `help@getpostman.com`. Please include the GitHub issue number (6304) in the email.

**Comment by sanjaybahrani** [comment]
> Hey @detectiveHLH
> 
> It looks like you have a window that is unreachable or too small. When you restart the app this default window is getting restored.
> 
> To unblock yourself immediately you can forcefully remove all windows by doing
> 
> 1. Quit the app
> 2. Run `rm ~/Library/Application\ Support/Postman/window`
> 3. Restart the app.
> 
> We will also look into how we can improve the experience when restoring the app with such cases.

**Comment by twitharshil** [comment]
@detectiveHLH We have fixed this issue in Postman v7.19, if you are still facing it please let us know.
