### ISSUE TITLE
'We can't seem to find the workspace' message upon launching the app 

### ISSUE THREAD

**Issue by cyrielle-hada** [a85/POSTMan-Chrome-Extension#6305]
**Describe the bug**

After updating Postman, the below message appears upon launching the app.

![Postman](https://user-images.githubusercontent.com/47351631/56196935-70a72680-6055-11e9-84b8-5e9517f2dc85.png)

**To Reproduce**

1. Update the latest version of the app (7.0.7)
2. Open the app
3. See error

**Expected behavior**
The app renders correctly and shows all synced collections. 

**App information (please complete the following information):**
 - Native App
 - Postman Version 7.0.7

**Additional context**

Other inconsistent states on the account
- After upgrading all collections were gone in the app (while they show up in the web dashboard)  
- When attempting to access a collection via the web dashboard, an error stating You don't have access is thrown. Related GitHub issue [6151](https://github.com/postmanlabs/postman-app-support/issues/6151)

Dev tools current view and shared view and logs are shared in the associated ticket.

**Comment by preethammavin** [comment]
The issue has been resolved.
