### ISSUE TITLE
Envronment Variable Values removed after exporting

### ISSUE THREAD

**Issue by Moegamad** [a85/POSTMan-Chrome-Extension#6310]
I am having a strange issue when exporting my environment to json file. All the environment variable values are empty. 

		{
			"key": "userName",
			"value": "",
			"description": "",
			"enabled": true
		},
		{
			"key": "passWord",
			"value": "",
			"description": "",
			"enabled": true
		},

**Comment by numaanashraf** [comment]
@Moegamad Could you verify that you have initial values in the environment? Only initial values are exported.

**Comment by preethammavin** [comment]
Closing the issue has with the current information , we are not able to deduce the issue. Please feel free to reopen the issue with the required information so that we can get it resolved.
