### ISSUE TITLE
Performance testing

### ISSUE THREAD

**Issue by richatyagi8** [a85/POSTMan-Chrome-Extension#6312]
Is it possible to do performance testing using postman . In the past I have used postman for functional testing of rest API but have to use Jmeter for performance testing

**Comment by yeikel** [comment]
Not really. Maybe using newman

**Comment by numaanashraf** [comment]
We recommend reaching out to the wider Postman Community (https://community.getpostman.com/) for help with this issue.

Issue Guidelines: https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues
