### ISSUE TITLE
Some users get logged out due to multiple active sessions even though they don't have any active session

### ISSUE THREAD

**Issue by labifrancis** [a85/POSTMan-Chrome-Extension#6313]
**Describe the bug**

Some users get logged out from their account because according to the error message they get, they have multiple active sessions even though they do not have an active session.

**Error**

One of more of your active Postman Application sessions have been logged out because you signed in. You are allowed to have no more than 3 simultaneously active Postman Application sessions.

**Additional context**

Another user will want to be able to see all their active sessions and delete them without contacting support for some cases.

**Comment by preethammavin** [comment]
@labifrancis we pushed a fix for the same, we are keeping an eye out for such behaviours. Do let us know if the issue persists.

**Comment by labifrancis** [comment]
Thanks @preethammavin 
I'll let you know if the issue persists.

**Comment by preethammavin** [comment]
@labifrancis closing the issue for now, do let us know if it occurs again
