### ISSUE TITLE
Template Tab and API Network Tab not loading data

### ISSUE THREAD

**Issue by Cloudbala** [a85/POSTMan-Chrome-Extension#6314]
**Describe the bug**
The Template Tab and Api Network Tab are empty , it shows it is continously loading but never displays the data

**To Reproduce**
1. Go to 'top left corner of postman canary app '
2. Click on 'Red colour New Button ', A popup screen is opened .
3. Click on 'Templates Tab or API Network Tab '
4. See it shows nothing 

**Expected behavior**
Templates Tab supposed to load all template data and API Network Tab supposed to display all network data

**Screenshots**

![image](https://user-images.githubusercontent.com/25430223/56293283-60796f00-615b-11e9-8443-921ec655d13b.png)

see the Templates tab and Api network Tab shows loading symbol, but not actually loading and displaying the default data

**App information (please complete the following information):**
 - App Type: Postman Canary [Native App]
 - Postman Version [Version 7.1.0-canary02 (7.1.0-canary02)]
 - OS: [e.g. macOS Mojave]

**Additional context**

**Comment by Cloudbala** [comment]
The same is tested in Postman app- latest release 7.x, even then  still the same issue prevails , please share a solution to get  data in Templates Tab and API Network Tab 
![templates](https://user-images.githubusercontent.com/25430223/56294125-ff529b00-615c-11e9-916e-8200e7357c0d.gif)

**Comment by bhargavkaranam** [comment]
Hi @Cloudbala,
We're unable to reproduce this. Could you open DevTools from View > Developer > Show DevTools (Current View) and let us know if you see any errors in the console?

**Comment by sivcan** [comment]
@Cloudbala as I can see from the gif, you're signed out.
We'll look into the app getting stuck in this loading state and not showing up the error, but any way to use API Network / Templates you need to be logged in to an account, so you'll have to basically sign up / login to access templates or API network in the app.

**Comment by preethammavin** [comment]
This issue has been fixed.
