### ISSUE TITLE
SAML provisioning support (SAML 2.0/WS-Fed) for SSO

### ISSUE THREAD

**Issue by shamasis** [a85/POSTMan-Chrome-Extension#6317]
This would help teams auto provision users using their existing identity / directory systems.

**Comment by ArjunSingh-PM** [comment]
We support SAML 2.0 and just-in-time provisioning.

Please refer to the following documentation for more details: 
- https://learning.postman.com/docs/administration/sso/intro-sso/
- https://learning.postman.com/docs/administration/sso/admin-sso/#creating-end-user-accounts
