### ISSUE TITLE
file类型每次都要重新上传

### ISSUE THREAD

**Issue by ghost** [a85/POSTMan-Chrome-Extension#6318]
**Describe the bug**
request中body数据类型为file时，每次重新打开postman都需要重新选择文件，在Runner中使用时，flie类型的参数没有被选择

**To Reproduce**
1、新建一个requset请求
2、在body中设置一个file类型的数据
3、本地选择一个图片文件
4、请求成功后关闭request
5、重新打开后查看body参数是否需要重新选择

**Expected behavior**
5、希望file类型的数据能保存，不用每次调试时需要选择。

**Screenshots**
![image](https://user-images.githubusercontent.com/32347059/56334121-a66d1c00-61c9-11e9-91e5-8dd7b405176b.png)
![image](https://user-images.githubusercontent.com/32347059/56334152-cdc3e900-61c9-11e9-9d44-7efcc0851d3f.png)

**App information (please complete the following information):**
 - App Type [web]
 - Postman Version [6.7.4]
 - OS: [e.g. macOS Mojave 10.14.2]

**Comment by shamasis** [comment]
Translating using Google Translator:

```
File type must be re-uploaded each time

Describe the bug
When the body data type of the request is file, the file needs to be re-selected each time the postman is reopened. When used in the Runner, the parameters of the flie type are not selected.

To Reproduce
Steps to reproduce the behavior:
1, create a new requset request
2, set a file type data in the body
3, local selection of an image file
4, close the request after the request is successful
5, re-open to see if the body parameter needs to be re-selected

Expected behavior
5, I hope that the file type data can be saved, you do not need to select each time you debug.
```

**Comment by shamasis** [comment]
@liuneng613 This is not yet supported in Postman. We are working on this and will update in PostmanCanary release very soon.

**Comment by shamasis** [comment]
@liuneng613 - this feature has now been added to Postman Canary channel and would be our in production soon. More details at https://github.com/postmanlabs/postman-app-support/issues/4320#issuecomment-490749103

Closing this issue since we are at final stages of release tracking on a duplicate thread.
