### ISSUE TITLE
Web dashboard - Unable to access Workspace 'Something went wrong'

### ISSUE THREAD

**Issue by cyrielle-hada** [a85/POSTMan-Chrome-Extension#6321]
**Describe the bug**

Unable to access the workspace section in the dashboard. The following error is thrown

![1112223333](https://user-images.githubusercontent.com/47351631/56338177-a3bcf780-61c6-11e9-99c3-11523a558eaa.JPG)

**To Reproduce**
1. Go to https://app.postman.co/workspaces
2. See error

**Expected behavior**
Be able to view personal workspaces.

**App information (please complete the following information):**
 - Chrome
 - Not using the Postman native app

**Additional context**

- The issue can be reproduced in incognito mode. 
- No error populates form the JavaScript console 
- Logging out and signing back in doesn't resolve the issue
- The user has a support-only account (billing role)

**Comment by abhijitkane** [comment]
@cyrielle-hada This should have been fixed after yesterday. Can you check with the end-user[s]?

**Comment by cyrielle-hada** [comment]
@abhijitkane all reports indicate that it's been fixed.

**Comment by abhijitkane** [comment]
@cyrielle-hada Great! Closing this.
