### ISSUE TITLE
Temporary headers being erratically visible in UI

### ISSUE THREAD

**Issue by thetreythomas** [a85/POSTMan-Chrome-Extension#6322]
**Describe the bug**
There are now a multitude of extra items that show up on the **Header** tab.

**To Reproduce**
Not sure what started it.

If I make a change on the **Authorization** tab, it will reset the number back to what I expect. When I send the API request, it then adds those extra headers.

**Expected behavior**
To not see all this extra header information. Previous versions did not show this.

Is this some setting I enabled by accident? I couldn't find anything in Settings to Enable/Disable this.

**Screenshots**
![Postman Extra Header](https://user-images.githubusercontent.com/15376624/56338361-58c3c580-616f-11e9-9016-a89339637623.png)

**App information (please complete the following information):**
 - Native Application
 - Postman Version 7.0.8
 - OS: Windows 10

**Comment by thetreythomas** [comment]
So I tried this on my Mac, it was one of the last version of 6.x you had before 7.x came out. I ran a call on that, no issues. I then updated it to 7.0.7, which was the latest available to update through the app. Ran a call, no issues.

I don't remember seeing an update show up on this machine.

I closed Postman and re-opened it, and I am no longer seeing those extra headers.
![it_crowd](https://user-images.githubusercontent.com/15376624/56338811-3df25080-6171-11e9-92e6-60e82322bc66.gif)

What I was doing before this happened...
1. I was in a Team Workspace
2. Created a new Personal Workspace
3. Added a team collection to the personal workspace
4. Created a new folder in that personal workspace
5. Copied an API from the imported collection into the newly created folder
6. Tested the copied API, worked fine
7. Changed over to a different Team Workspace
8. Ran an API from this current workspace and encountered the issue

**Comment by shamasis** [comment]
These are the actual set of headers that are sent out. Next release we are making it look better in UI by grouping it in a collapsible section. There, however, is a bug around this list not showing up based on certain selection of the authorisation list and that will be addressed in the process.

**Comment by ashleymiller-kcom** [comment]
These headers are a a result of installing v7.0.8.
I'm not exactly sure about the status of v7.0.8, but when it is apparently installed, there are no Release Notes available, only for v7.0.7.
I have now rolled back to v7.0.7 and when I check for updates in the UI, it says:
**You are up to date! Postman v7.0.7 is the latest version.**
So, I'm not sure whether v7.0.8 was released too early and has now disappeared, but v7.0.7 seems more robust right now... and it has some Release Notes.

**Comment by thetreythomas** [comment]
Looking at the date in Programs and Features, 7.0.8 was installed on 4/12/2019.

This was the 64-bit of Postman for Windows.

I removed 7.0.8 and reinstalled 7.07, and not seeing the extra headers.

**Comment by shamasis** [comment]
7.0.9 is coming out in days and that will neatly show the headers and also resolve the issue around cache control and postman-token header related issue: https://github.com/postmanlabs/postman-app-support/issues/6283 

I will ping here when that’s out. We can then check if everything works the way it did. 😊

**Comment by shamasis** [comment]
The fix for this is in v7.0.9 for app... let us know if this works now.

**Comment by thetreythomas** [comment]
@shamasis 

Updated to 7.0.9 today. So far so good.

When I make calls, it shows the Temporary Headers at the bottom of the Headers window.

I like how you all decided to put it at the bottom, and display the collapsible list closed by default. If you're not looking for this, you might not see it.

**Comment by Navstati** [comment]
I'm using 7.0.9 and I'm getting 500 error when I post the cURL with these temp headers in terminal where as able to post successfully with eliminating these temp headers.. 

Is there a way to select / de-select these temp headers from the request?

**Comment by shamasis** [comment]
@Navstati these headers were always sent - it’s not new. Your issue might be unrelated. Could you file a separate issue with a sample collection having the request and it’s associated code generated?

**Comment by sharq88** [comment]
Can you please also give an option to disable temporary headers in code generation? This is very annoying that it produces this now: :(

curl -X GET \
  'http://myaddress.com/api/v1.0/test' \
  -H 'Accept: */*' \
  -H 'Authorization: Bearer xyz' \
  -H 'Cache-Control: no-cache' \
  -H 'Connection: keep-alive' \
  -H 'Content-Type: application/x-www-form-urlencoded' \
  -H 'Host: myaddress.com' \
  -H 'Postman-Token: 890a2742-5359-41d9-8589-d440a4332dd0' \
  -H 'User-Agent: PostmanRuntime/7.11.0' \
  -H 'accept-encoding: gzip, deflate'

**Comment by atjason** [comment]
Can't understand why there's such a feature to keep temporary headers and don't allow users to remove or disable or edit or overwrite it.

**Comment by saswatds** [comment]
Hi @atjason I have tried to explain what these temporary headers are why they are visible here https://community.getpostman.com/t/temporary-headers/5243/15?u=saswatds

@sharq88 I can understand that code-generation has started to add these additional headers. The intention here was to give the end-user the exact header that postman was sending so that debugging could get easier.

It a valid feature request to allow users to disable the addition of temporary. It will be really helpful if you could create a new issue asking for the same. i.e to disable the addition of temporary headers while generating code. This will help is track and prioritize better, as this issue is primarily around the UI showing these headers, which is intended.

**Comment by atjason** [comment]
@saswatds Already has such issue to disable temporary headers: https://github.com/postmanlabs/postman-app-support/issues/2689

**Comment by saswatds** [comment]
@sharq88 I have created an issue on behalf of everyone for an option to disable the headers in code-generators. If this could solve your issue, feel free to give a 👍 
https://github.com/postmanlabs/postman-app-support/issues/6680

**Comment by sharq88** [comment]
Awesome! Thank you! @saswatds
