### ISSUE TITLE
Estimated time of completion when running tests through Newman

### ISSUE THREAD

**Issue by sneela787** [a85/POSTMan-Chrome-Extension#6325]
**Is your feature request related to a problem? Please describe.**
We run lot of postman collections in the company and sometimes it takes lot of time when a data file is big. We are using newman through library and I hate to keep the user waiting for all that time. Sometimes the test takes 40minutes to complete.

**Describe the solution you'd like**
It would be really great if there is a way of getting the estimated time of completion of postman collection through newman library. That way we can keep the user notified of how long its going to take.

**Comment by shamasis** [comment]
It’s a nice idea. But there’s no way to estimate the time without actually running a few requests. Even then that will not be accurate. Trying to put that in the main CLI reporter will simply cause misinformation for small and medium collection runs. 

Try using `--reporters=progress` and it will turn off the CLI reporter and show a progress bar instead. This is not a documented feature. This reporter tries to estimate a time which is best guess based on how long the initial few requests take and then tracks a moving average. Let me know if this works.
