### ISSUE TITLE
Oath2 client_credentials in Query Param

### ISSUE THREAD

**Issue by akac** [a85/POSTMan-Chrome-Extension#6326]
**Is your feature request related to a problem? Please describe.**
We are using Apigee as our API proxy platform and it requires OAuth2 grant types to be a query parameter, not a post param

**Describe the solution you'd like**
Allow an option to have the grant type in the query param

**Describe alternatives you've considered**
Currently we are using a separate request that puts the data into a token that must be run first and passed to the next request

**Comment by vvs11** [comment]
@akac We are working on improving oAuth. Could you provide us with more details about what you are expecting as a solution?

**Comment by abhijeetborole** [comment]
Hey @akac! Thank you for the patience! We’ve added the ability to customise your OAuth2,0 requests with Postman v10.13.
This is available under the `Advanced` section under OAuth2.0. With these changes, you can now add params to the headers, body and URL for token and refresh requests. You can also add query params to the auth request.

You can override the `grant_type` in this `Advanced` section and attach it in the query params of the token request.

![CustomOauthLow](https://user-images.githubusercontent.com/9638586/232849656-63e0297a-7bc3-4472-8ff3-04cf2f5df95e.gif)

If you have any Audience and Resource parameters, you can move them to the new editors with the Move Audience and Resource button.

![MoveAudAndResFlow](https://user-images.githubusercontent.com/9638586/232850201-59d30590-d7c7-41c1-94c7-9a1c77f1757b.gif)


Do let us know if you have any issues.

P.S. - For refresh parameters, these will be stored with the token and any changes will only be considered when you generate a new token

Postman app v10.13 is being rolled out will be available for everyone in couple of days
