### ISSUE TITLE
Enable/disable content in docs page

### ISSUE THREAD

**Issue by JP-from-Postman** [a85/POSTMan-Chrome-Extension#6327]
**Is your feature request related to a problem? Please describe.**
Allow specific requests, folders, and other entities to be enabled or disabled from appearing in a docs page. This way a single comprehensive Collection can be maintained with only needed/finished requests being published.

**Describe the solution you'd like**
- Allow folders to be enabled / disabled from appearing on docs page

**Describe alternatives you've considered**
- Only current alternative is to have multiple separate Collections

**Additional context**

**Comment by preethammavin** [comment]
@JP-from-Postman Can you add more context

If there are sections of your documentation which are yet to be finalised, we suggest you fork the collection then merge it when you are ready. 
We are working on giving more control to the user for specifying the collection version which has to be published , but hiding something for specific folder or request is not something we would want to build towards as it introduces a lot more complexity on the user and becomes unmaintainable.

**Comment by JP-from-Postman** [comment]
@preethammavin Sorry for the delay: please see linked ticket where FR originates from
