### ISSUE TITLE
Bootcamp Walkthrough Not Proceeding Further

### ISSUE THREAD

**Issue by Redhunt2013** [a85/POSTMan-Chrome-Extension#6328]
**Describe the bug**
Imported Bootcamp collection in Postman.  Click on one of the 2 courses. A pop-up walks me through where to click next.  After a certain point, pop-up is just frozen even though I've done what it describes.

For example, I designed a Status Checker API using the course.  In the list of requests under the collection, pop-up is asking to open a request in a tab.  Pop up is stuck there even after I open a request in a separate tab.

**To Reproduce**

1. Click on Bootcamp.
2. Click on Design an API in a minute.
3. Create a request model.
4. Import collection.
5. Select environment.
6. Expand Status Checker.
7. Click on one of the requests.

**Expected behavior**
Pop-up should drive to next point.  It simply is stuck at asking me to open the request in a tab.

**Screenshots**
![Screen Shot 2019-04-19 at 4 07 32 PM](https://user-images.githubusercontent.com/5237704/56447624-50c66b80-62be-11e9-9cac-fae237918668.png)

**App information (please complete the following information):**
 - App Type [Native App]
 - Postman Version [7.0.7]
 - OS: [macOS Mojave]

**Additional context**

**Comment by sivcan** [comment]
@Redhunt2013 Thanks for reporting this. We're unable to reproduce this issue at our end. Would it be possible to send us the logs from View > Developer > View Logs in Finder to help@getpostman.com? Please mention this issue number in the email subject, eg., "Logs for GH#6328".

Also, can you try out the canary build - https://www.getpostman.com/downloads/canary and check if it's still happening for you?

Thanks

**Comment by preethammavin** [comment]
@Redhunt2013 any information to triage this issue would be appreciated, we are unable to reproduce it.

**Comment by Redhunt2013** [comment]
Folks, I cannot reproduce the same issue as of today.  I've emailed the logs from the day it happened first. This ticket shall be closed if not relevant anymore.

**Comment by preethammavin** [comment]
@Redhunt2013 thanks, will close the thread for now, do let us know if you face similar issue again,

**Comment by cyrielle-hada** [comment]
@preethammavin similar issue is happening for the `collaboration skill`. 
Here's the current behavior: https://www.loom.com/share/1b58dc82e7554c5fb031e29f27e32649.
