### ISSUE TITLE
How to use a wild card variable in example request?

### ISSUE THREAD

**Issue by jpschutte** [a85/POSTMan-Chrome-Extension#6329]
I have an endpoint that I'm trying to create and example request for. I don't have control over the endpoints myself on the actual development server but I want to create mock requests.

Example: {{url}}/user/{{userId}}/posts

This call doesn't work and returns We were unable to find any matching requests for this method type and the mock path. I'm new to Postman so maybe I'm doing something wrong? I've tried searching for this on Google and in the Postman documentation but can't seem to find anything.

If I set the example request url to a very specific url then I get a response:

{{url}}/user/1/posts

This is based on an example and not on the actual endpoints I'm developing for.

Thanks for your time.

**Comment by vvs11** [comment]
Could you go through this link and see if it solves your problem?

https://learning.getpostman.com/docs/postman/mock-servers/mocking-with-examples/

I am not sure how do you want to use wildcard matching. Could you elaborate on this further?

**Comment by vvs11** [comment]
@jpschutte Please go through the matching algorithm uses by Postman Mock Servers
https://learning.postman.com/docs/postman/mock-servers/matching-algorithm/
There is a section around wildcard matching. Hope this satisfies your use-case.
For more information regarding topics around Postman, Please visit our community:

https://community.getpostman.com/
