### ISSUE TITLE
Workspace data disappears after toggling default workspace permissions to Admin

### ISSUE THREAD

**Issue by chrisdeso** [a85/POSTMan-Chrome-Extension#6330]
**Describe the bug**
After changing the default workspace permissions to `Admin` from `Collaborator`, collections vanish from a workspace.

**To Reproduce**
1. Open a workspace in-app
2. Toggle the default permissions to `Admin` from `Collaborator`
3. Se collections disappear

**Expected behavior**
Collections should remain associated with the workspace but with updated permissions for workspace members.

**Screenshots**

**Before toggling default workspace permission**
![image](https://user-images.githubusercontent.com/4734306/56459750-21127480-634d-11e9-938e-20bb27627275.png)

![image](https://user-images.githubusercontent.com/4734306/56459752-2a034600-634d-11e9-8034-f0621068736b.png)

![image](https://user-images.githubusercontent.com/4734306/56459755-2d96cd00-634d-11e9-8747-c826f289394a.png)

**After toggling default permission**
![image](https://user-images.githubusercontent.com/4734306/56459758-325b8100-634d-11e9-84bd-e9bba400d5e2.png)

**App information (please complete the following information):**
 - App Type: Native
 - Postman Version: 7.0+
 - OS: MacOS

**Additional context**
[Filed by Postman]

**Comment by abhijitkane** [comment]
@preethammavin Can you also mention what additional info is required?

**Comment by preethammavin** [comment]
@abhijitkane this is situation where the collections were never synced to the in such cases do ask for app logs

**Comment by preethammavin** [comment]
@chrisdeso can you share the name of one of the collections to check for errors as I am unable to find any errors on our end.

**Comment by chrisdeso** [comment]
@preethammavin – here's a collection & workspace!

Collection – `CKAN`
Workspace – `Correcthosting`

**Comment by DannyDainton** [comment]
@chrisdeso Is this is an issue in the latest app?

**Comment by DannyDainton** [comment]
I'm going to close this issue as it looks like there's no active work happening - We can open it back up if it's still an issue for the user.
