### ISSUE TITLE
Response area full screen toggle

### ISSUE THREAD

**Issue by hupo376787** [a85/POSTMan-Chrome-Extension#6333]
Hi, how to toggle the response data area to full screen? I can't find a shortcut key.
I mean the red area in the below image.
Thx.

![image](https://user-images.githubusercontent.com/14960168/56479928-75069000-64ea-11e9-9326-e8967a78b89f.png)

**Comment by sujayvenaik** [comment]
Hey @hupo376787 
You can make use of the two-pane view.
![image](https://user-images.githubusercontent.com/11532114/56484067-5228ab80-64eb-11e9-851b-2503441d3115.png)

**Comment by hupo376787** [comment]
But this action still can't maximize the response area. I want the red area full screen view. So it seems this feature may not exist in current version.

**Comment by topicomha** [comment]
I agree I think a full-screen view of either the Request Area or the Response Area would be very useful. Maybe even a pop-out of some sort to just show that area in its own window. 

The side by side helps some but a lot of the time it would help more to have a full-screen view for long responses or big raw requests without all the wrapping of lines.

**Comment by hupo376787** [comment]
Totally agree!

**Comment by rahuldange09** [comment]
Any updates on this feature. Can't see large response properly in small window. It's better if they add a toggle to see response in full screen with Json Viewer features (Expand- Collapse JSONArray)

**Comment by vinayak-b** [comment]
Or at-least like a "Postman Console (⌥⌘C)"  for response which opens in new modal window. It will will be helpful to view the response in fullscreen.

**Comment by dev6james** [comment]
Postman needs this feature. It's a no-brainer.

**Comment by kyunussov** [comment]
You can view the response body in full screen by 
- first, open the Console in a new window 
![image](https://user-images.githubusercontent.com/4325422/101586534-23a56000-39b0-11eb-9426-7001c39ba366.png)
- then, expand the request/response info, and click the same icon for the "response body"
![image](https://user-images.githubusercontent.com/4325422/101586612-4899d300-39b0-11eb-92ee-eb3a3a72427e.png)

**Comment by hupo376787** [comment]
Hi, team. Any updates?

**Comment by irving-dealerclick** [comment]
This would be a great feature.

**Comment by kr15hna** [comment]
missing this :frowning_face:

**Comment by giridharvc7** [comment]
@kr15hna the response pane is resizeable and you can do something like so
<img width="1097" alt="image" src="https://user-images.githubusercontent.com/1040583/224906136-ff69bf97-28d1-4e40-8e08-8436d3ac1b87.png">

Let us know if this works

**Comment by kr15hna** [comment]
@giridharvc7 thanks for the tip.

**Comment by aderchox** [comment]
@giridharvc7 I guess that doesn't work, most users probably need a solution where they can reverse the fullscreen easily. Not a resize. Something like an expand/unexpand toggleable button.
