### ISSUE TITLE
Request get removed when collection is forked

### ISSUE THREAD

**Issue by cyrielle-hada** [a85/POSTMan-Chrome-Extension#6334]
**Describe the bug**
Every time a collection is forked, one of the GET requests disappears from the forked collection. 

**App information (please complete the following information):**
 - Running Postman v7.0.7

**Additional context**

- The logs can be found in the associated ticket but they don’t seem to contain any errors
- I have 28 requests in the collection

**Comment by preethammavin** [comment]
@cyrielle-hada is there a particular request which is not being forked every time? if yes would be great if the id of the said request be shared with us for us to triage the bug.

**Comment by cyrielle-hada** [comment]
@preethammavin yes it's just a particular GET request that gets removed every time the collection is forked.

**Comment by cyrielle-hada** [comment]
@preethammavin the request in question that was removed every time the collection was forked was not to be synced. Duplicating the collection did the trick as it sent the collection payload with all the requests.

**Comment by sujayvenaik** [comment]
@preethammavin I triaged this issue, and there was a request which did not get synced mostly.
So duplicating the collection created a collection with all the requests similar to its local state and then fork could be done which would result in the correct state.

**Comment by preethammavin** [comment]
@sujayvenaik do we know why the request was not be synced ?

**Comment by sujayvenaik** [comment]
@preethammavin The logs that were attached did not have any info in the ticket. This could happen in two cases. And one of them was this. I'll still look into if we find anything else.
