### ISSUE TITLE
Can't create new team, sync never finishes [version compatibilty]

### ISSUE THREAD

**Issue by p00j4** [a85/POSTMan-Chrome-Extension#6335]
With the push to "move to version 7" noticed several problems:

1. For one of my team member (version 6), no collections were showing up within the app, the sync loader is never finishing and no re-opening etc. things helped until installed latest version 
2. I'm on Canary and I face the issue of loader never finishing too with side effects like, **can't see my newly created team**. Retried several times with app reopen.
And for me moving to 7 does leads to another can't live with [known issue](https://github.com/postmanlabs/postman-app-support/issues/5813)

```Your team updated to Postman v7.0. To keep your collections and workspaces in sync with your team, you must also update to v7.0 by going to  > Settings > Update.```

What's best work around I can go for for now? Any update on #5813 so that I can easily move to latest versions and not stuck with any backward compatibility issues like this in future.
Shared video in [support request](https://support.getpostman.com).

**Comment by sujayvenaik** [comment]
Hey @p00j4 
Which version of canary are you currently on? And when you are facing this issue what is the postman icon color?
Also, can you send the logs from View -> Developer -> View Logs in Finder?

**Comment by p00j4** [comment]
**Update:** It started working after updating Canary to 7.1 


**The bug found on:** Version: 6.6.0-canary03 (6.6.0-canary03)
Logs for
[main.log](https://github.com/postmanlabs/postman-app-support/files/3102896/main.log)
[pluginHost.log](https://github.com/postmanlabs/postman-app-support/files/3102897/pluginHost.log)
[renderer-requester.log](https://github.com/postmanlabs/postman-app-support/files/3102898/renderer-requester.log)
[renderer-shared.log](https://github.com/postmanlabs/postman-app-support/files/3102899/renderer-shared.log)
[renderer-shell.log](https://github.com/postmanlabs/postman-app-support/files/3102900/renderer-shell.log)


But still, having concern that anyone joins the team (mostly will start with latest postman app) and hence everyone else in the team would face this and forceably have to update. 
The update from app if it works should be ok but it never really works, one has to download fresh and install and remove previous (move to application folder also doesn't work by default so manually need to move) 
-- **so many steps to do before getting into real work** when any single team mate updates. 
Can this flow for force update be considered once again? I can try sharing all logs for auto update failure sometime again, because now after downloading 7.1. older 6 canary doesn't open.

<img width="423" alt="image" src="https://user-images.githubusercontent.com/6470509/56494599-64691080-6510-11e9-940e-8d182ce2d9be.png">

**Comment by sujayvenaik** [comment]
Hey, once your team migrated it is intended for you to move to v7 version.
Also, we are constantly trying to improve the experience for the users hence really don't want users to downgrade to a lower version.

**Comment by p00j4** [comment]
I understand it @sujayvenaik however please have a look at the number of steps involved as mentioned above. It's tedious. Really needs User Experience improvement else most time goes in finding work around to get the App working.

Closing this issue, but can raise separately about the pain points of upgrading app if it's not yet on priority.

**Comment by sujayvenaik** [comment]
Closing this issue, can you create a separate issue for the issues that you face while updating the app?
We will pick it up from there.
