### ISSUE TITLE
postman: failed to extract installer

### ISSUE THREAD

**Issue by veeranagouda87** [a85/POSTMan-Chrome-Extension#6336]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**App information (please complete the following information):**
 - App Type [e.g. Chrome App, Native App]
 - Postman Version [e.g. 6.0.1]
 - OS: [e.g. macOS High Sierra 10.13.2]

**Additional context**

**Comment by numaanashraf** [comment]
Please fill the details in the issue template.

**Comment by veeranagouda87** [comment]
[postman screenshot.pdf](https://github.com/postmanlabs/postman-app-support/files/3106161/postman.screenshot.pdf)

**Comment by preethammavin** [comment]
Closing the issue has with the current information , we are not able to deduce the issue. Please feel free to reopen the issue with the required information so that we can get it resolved.
