### ISSUE TITLE
Collection Delete - Confirm name of collection on delete.

### ISSUE THREAD

**Issue by iriseufall** [a85/POSTMan-Chrome-Extension#6337]
Accidently deleted wrong collection.

Suggestion: Confirm the "NAME" of the collection in the confirmation dialog.

**Comment by sujayvenaik** [comment]
Hey @iriseufall 
Collection in which delete was performed from the submenu is only getting deleted. Can you confirm which app version you are on? Also which OS?

Can you share a screen recording as well, if possible?

Showing the name in the delete confirmation modal can be added as a feature request which we can pick up.

**Comment by iriseufall** [comment]
You are right. Collection is getting deleted where delete is performed.
But adding Name in delete confirm dialog would reduce unexpected result.

**Comment by sujayvenaik** [comment]
@iriseufall Sure, marking this as a feature request. 👍

**Comment by apoorvgupta03** [comment]
hey @iriseufall, this has been fixed in our earlier releases 

https://user-images.githubusercontent.com/110587492/224352130-c4402a34-dfa6-4a05-92df-36aab7d26c24.mov
