### ISSUE TITLE
Long delay loading docs page

### ISSUE THREAD

**Issue by JP-from-Postman** [a85/POSTMan-Chrome-Extension#6339]
Please read through the [guidelines](https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues
**Describe the bug**
The following docs page (lots of content) takes up to 20 seconds:
https://eshop.envia.com/

**To Reproduce**
1. Open: https://eshop.envia.com/
2. Observe delay

**Screenshots**

**Additional context**) before creating a new issue.
-

**Comment by dhineshwiz** [comment]
@JP-from-Postman the published document is not available

**Comment by JP-from-Postman** [comment]
@dhineshwiz User who owns it may have taken it down / unpublished it. I've seen this issue before with very large docs pages. I've linked the original request to this issue, and added a link in JIRA.

**Comment by JP-from-Postman** [comment]
@dhineshwiz Added additional example in JIRA

**Comment by mccannt** [comment]
@JP-from-Postman Can this be closed out?

**Comment by DannyDainton** [comment]
Closing the issue due to inactivity.
