### ISSUE TITLE
Saving binary responses as a file results in base64

### ISSUE THREAD

**Issue by CMircea** [a85/POSTMan-Chrome-Extension#634]
If I make a request to a server and the server replies with binary content (such as application/pdf), Postman asks me to save it as a file. If I do that, the file doesn't contain the actual bytes, but a base64 string. This only happens if the interceptor extension is enabled.

**Comment by igauravsehrawat** [comment]
How does "Send and download" works? can anyone help me with internal details?

Cheers

**Comment by abhijitkane** [comment]
'Send and download' makes the XHR request with responseType set to "arraybuffer", which returns the data as binary.

**Comment by igauravsehrawat** [comment]
@abhijitkane thanks for the elegant solution. Used blob further to complete the function.

**Comment by gautamwa** [comment]
Thanks, Postman is too cool. Save me tons of time

**Comment by swapnilpatne** [comment]
How to handle file download request from Newman? Can someone please answer? 

Postman's 'Send and download' doesn't handle it quite gracefully as I can see filename returned in response header along with file type whereas Postman simply opens up save as window without providing the actual file name returned from server as if Postman doesn't know what file was returned from server.

**Comment by manishagr83** [comment]
How can we find out what is internally done in Send and Download and replicate the same in JAVA code. Send and Download is working perfectly for me but when run from JAVA it is writing JUNK to the file in local

**Comment by daniel2xo** [comment]
Any shortcut for "send and download" in the GUI ?

**Comment by sdnts** [comment]
@daniel2xo As of now, no. But we're working on a release that has buffed shortcuts. I'll add it there. Will let you know here when it is out.

**Comment by daniel2xo** [comment]
Thanks @madebysid for reply, actually i dont know how to create a java file to call an api and get save the respond repeatedly, so wish to have a shortcut for that.

**Comment by jguziejka** [comment]
this is still an issue, had to turn off Interceptor for the PDF to be created correctly...

**Comment by shsowmya** [comment]
Hi,
 I have the same need to save the response body as zip file while running in the collection runner. How can I achieve it using script?
