### ISSUE TITLE
Could not open Postman after update

### ISSUE THREAD

**Issue by sujayvenaik** [a85/POSTMan-Chrome-Extension#6340]
**Describe the bug**
Could not update the app using the auto-update flow

**To Reproduce**
1. Update the app using the auto-update flow

**Expected behavior**
App boots up normally on the new version

**Screenshots**
![image](https://user-images.githubusercontent.com/11532114/56557942-9df65600-65ba-11e9-8561-37c9ab523189.png)
[main.log](https://github.com/postmanlabs/postman-app-support/files/3106031/main.log)
[renderer-shared.log](https://github.com/postmanlabs/postman-app-support/files/3106032/renderer-shared.log)
[renderer-requester.log](https://github.com/postmanlabs/postman-app-support/files/3106035/renderer-requester.log)
[pluginHost.log](https://github.com/postmanlabs/postman-app-support/files/3106052/pluginHost.log)
[renderer-shell.log](https://github.com/postmanlabs/postman-app-support/files/3106053/renderer-shell.log)

**App information (please complete the following information):**
 - App Type: Native App

reported by @p00j4

**Comment by adrianmhe** [comment]
I had a simliar issue, but manually installed the latest version of postman without deleting the original, then I had to go to the dashboard and update my team to a 7.0 specification before this worked.

**Comment by numaanashraf** [comment]
With only the information that is currently in the issue, we don't have enough information to take action. We are closing this as we are tracking the 'Could not open Postman' related issues at #5591.
