### ISSUE TITLE
Template download error

### ISSUE THREAD

**Issue by loopDelicious** [a85/POSTMan-Chrome-Extension#6343]
New+ button > Templates tab > Typeform > Use this template

Postman for Mac
Version 7.0.9

Trying to import the Typeform template results in this error:

<img width="1392" alt="Screen Shot 2019-04-17 at 11 28 49 AM" src="https://user-images.githubusercontent.com/17693714/56604048-f37c3400-65b5-11e9-8bb2-8c40b7be2359.png">

**Comment by loopDelicious** [comment]
Same error occurs when trying to import template "Slack Weather Bot" or "Trending News".

**Comment by dhineshwiz** [comment]
hey @loopDelicious thanks for reporting this, we will fix it soon

**Comment by preethammavin** [comment]
This issue has been fixed
