### ISSUE TITLE
Mask client certificates passphrase by default

### ISSUE THREAD

**Issue by cpend** [a85/POSTMan-Chrome-Extension#6344]
**Is your feature request related to a problem? Please describe.**
Currently when I view the Settings -> Certificates page the "Passphrase" of the Client Certificates that I have setup are visible.

**Describe the solution you'd like**
 I would like to request that these are Masked permanently or have an icon next to masked passphrase that will allow to to view the unmasked passphrase.

**Additional context**
If I am showing another developer how I have setup my client certificates by screen shot or by viewing over my shoulder I would rather not share my personal passphrase with them.

**Comment by cpend** [comment]
Currently when I view the Settings -> Certificates page the "Passphrase" of the Client Certificates that I have setup are visible.  I would like to request that these are Masked permanently or have an icon next to masked passphrase that will allow to to view the unmasked passphrase.  If I am showing another developer how I have setup my client certificates by screen shot or by viewing over my shoulder I would rather not share my personal passphrase with them.

**Comment by codenirvana** [comment]
Fixed in Postman v7.2.0
