### ISSUE TITLE
Cannot sync or publish documentation

### ISSUE THREAD

**Issue by adrianmhe** [a85/POSTMan-Chrome-Extension#6346]
**Describe the bug**
The sync button is solid red and does not sync changes to the server.  This has been going on for the past 6 hours.  Clicking the publish documentation button brings me to an error page that says: 

"401
The request has expried. Please try again"
"Request Trace: v=1;t=6bf4a5ce275ec1f8"
With the picture of a dog.

**To Reproduce**
1. Login to the desktop application
2.Make a change to any collection
3. Attempt to sync or publish documentation

**Expected behavior**
The documentation should be updated on sync or publish.

**Screenshots**
![image (9)](https://user-images.githubusercontent.com/29382764/56621908-1bce5780-65e3-11e9-84da-fc84b84d02f4.png)

**App information (please complete the following information):**
 - App Type Native OSX app
 - Postman Version 7.09
 - OS: macOS High Sierra 10.14

**Additional context**
Program was working fine until last osx update

**Comment by adrianmhe** [comment]
reinstalling the application and restarting the operating system seems to have fixed this

**Comment by AhmedAlAhmed** [comment]
I have Ubuntu 20.04 and downloaded the latest version of Postman, the same issue, but I have figured out a simple trick to solve this problem.

The solution, simply login to the postman website and find your collection, you will see every request with every saved response had been saved and synced, just publish it from the website.
![image](https://user-images.githubusercontent.com/12294231/88453386-13606e80-ce6f-11ea-8f65-f1f9c414ff2a.png)
