### ISSUE TITLE
Postman does not remember the non-maximized window size if closed while maximized

### ISSUE THREAD

**Issue by johnpedersen-freightways** [a85/POSTMan-Chrome-Extension#6347]
When Postman is launched maximized it does not remember the window size when switching to non-maximized.

**To Reproduce**
1. Launch Postman
2. Ensure the Postman window is not maximized
3. Resize the window
4. Maximize Postman
5. Close Postman
6. Launch Postman again (Postman should start with a maximized window)
7. Un-maximize the window
8. The window doesn't have the same dimensions as when it was resized in step 3

**Expected behavior**
Postman should remember window state and dimensions between restarts

**App information**
 - Native Postman v7.0.9
 - OS: Windows 10

**Comment by DannyDainton** [comment]
Hey @johnendev,

Are you able to confirm that you're still seeing this issue? There have been several changes to the app since the issue was reported. 

I'm unable to see the issue using version 7.27.0.

**Comment by johnpedersen-freightways** [comment]
@DannyDainton Yes, still seeing the same issue on the latest version:
![image](https://user-images.githubusercontent.com/20271944/85799575-8fde2f80-b793-11ea-8b95-0263f7a9be58.png)

**Comment by DannyDainton** [comment]
😔

Are you able to do a screen recording of what you're seeing please?

**Comment by johnpedersen-freightways** [comment]
@DannyDainton 
![screen](https://user-images.githubusercontent.com/20271944/85818940-21669500-b7c6-11ea-871f-e67c2ee4c12b.gif)

**Comment by DannyDainton** [comment]
@johnendev Thank you for providing the additional context and the video. Appreciated. 👍

**Comment by mattlogic** [comment]
This issue still occurs on Windows app v8.12.0.

A more correct description of the behaviour would be:
Postman resets the non-maximized window size/position (to just less than full-screen) if closed while maximized, and opens in the non-maximized state (aka "restored") on the primary display.

I generally want Postman to open full-screen, or exactly where I placed it last time. I have two monitors side-by-side with extended desktop, and Postman seems to remember which monitor and location I place the non-maximized window, but if I close it when it's maximized on either display, then it always opens in the the primary display in the non-maximized state, and sized to nearly fill the desktop.

**Comment by Zabuzard** [comment]
I can still consistently reproduce it as of today. Windows app `v9.14.4`.

**Comment by msmigiel** [comment]
This was fixed in 9.15.0 but is no longer working in 9.15.3. This issue looks related and it's also reported there that it has regressed. https://github.com/postmanlabs/postman-app-support/issues/10340

**Comment by RaisinTen** [comment]
Hey folks, could y'all please test out the latest Postman version (v9.16.x) and let us know if this is still an outstanding issue?

**Comment by Zabuzard** [comment]
Works now, thanks :)

**Comment by RaisinTen** [comment]
Thanks for the confirmation, closing! :)
