### ISSUE TITLE
Pre-request Script ignored in code feature

### ISSUE THREAD

**Issue by xavier-b** [a85/POSTMan-Chrome-Extension#6349]
Pre-request Script ignored in code feature

When I modify request with `Pre-request Script` tab (in collection or in request), my script is ignored when I use `code` feature.

For exemple in `Pre-request Script` tab I add : 

```javscript
pm.request.headers.add({
    key: 'x-ibm-client-id',
    value: 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx'
});
```

But when I use `code` feature (cUrl version), I can't see x-ibm-client-id header :
```bash
curl -X GET \
  http://localhost:8444/articles \
  -H 'Accept: application/json' \
  -H 'Connection: keep-alive' \
  -H 'Host: localhost:8444' \
  -H 'User-Agent: PostmanRuntime/7.11.0' \
  -H 'accept-encoding: gzip, deflate'
 ```
 Postman v7.0.9

**Comment by a85** [comment]
We don't support code generation for dynamically created or modified requests right now.

**Comment by valuetodays** [comment]
The headers added in Pre-request Script does not appear in `code` feature. So, I have to append the  headers to the generated snippet manually. 
Hope suport this feature. Thx.
My app version: v7.11.0

**Comment by a85** [comment]
Closing this as this is not going to be mostly impossible to map. To generate code, you will need to use the UI and bake in all request elements in the UI.
