### ISSUE TITLE
"Feature" request : Better font on packaged app

### ISSUE THREAD

**Issue by beNjiox** [a85/POSTMan-Chrome-Extension#635]
Here's how the font face looks like on the regular extension:
http://cl.ly/image/1Z3C3C3l3G3e

Here's how it looks like on the packaged app:
http://cl.ly/image/473n3V041V3t

I find the packaged app not really readable (I would even say ugly)
Is that something fixable ?

Version 0.9.10.1 (packaged)
OS: mac (Mavericks)
Architecture: x86-32
Native client architecture: x86-32

**Comment by brendler** [comment]
Any update on this? Also found this font rather annoying.

**Comment by abhijitkane** [comment]
In the current version of the packaged app, the JSON, HTML, and XML preview modes use fixed-width fonts. Are you still seeing proportional fonts anywhere?
