### ISSUE TITLE
Postman Console: implement search

### ISSUE THREAD

**Issue by klemens-u** [a85/POSTMan-Chrome-Extension#6350]
Currently there is a "Filter Messages" field. The filter is not helpful in cases where you need context. Example: console.log() output

Additionally it would be nice to have a fulltext search. This would allow to search for example in console.log() output.

**Comment by ritwijsinha** [comment]
Hello @klemens-u.

This feature has been added in the new Postman Console. Please update to Postman v7.10 for this.

Cheers! 🎉
