### ISSUE TITLE
Postman Requests Sidebar: expand/collapse all option

### ISSUE THREAD

**Issue by klemens-u** [a85/POSTMan-Chrome-Extension#6355]
It would be helpful to have an option to collapse or expand all folders and subfolders in the sidebar (the list of request).

How it could work:
* right click on a collection or folder, or click the menu icon (3 dots)
* select option "collapse all" -> all subfolders get collapsed, all memory of expanded folders gets deleted
* select option "expand all" -> alls subfolders get expanded

**Comment by anishkny** [comment]
Workaround for anyone stumbling on this:

1. Click on filter text box (top left)
1. Enter some character (e.g. "a")
1. Delete it.
<img width="1202" alt="Screen Shot 2020-01-29 at 12 28 18 PM" src="https://user-images.githubusercontent.com/357499/73394706-f0c01500-4292-11ea-96c3-1841a9355376.png">

This collapses all folders. Checked on Postman Version 7.16.0 (7.16.0)

**Comment by jcald1** [comment]
The workaround to collapse is nice, but we would really like an Expand All option as well.

**Comment by rohitkrishna094** [comment]
That workaround seems like a bug lol, but in this case, its a feature :P

**Comment by roblappcoupa** [comment]
I really want this feature!

**Comment by aaronvancuren** [comment]
This would be nice. I have a collection with hundreds of folders.

**Comment by thevirajshelke** [comment]
This feature was requested in 2019 wow! I am sure the Postman team is busy doing some really cool stuffs and features but is this small feature (small yet useful) on the list of any subsequent releases?

Do we have any ETA or update on this feature? @numaanashraf

**Comment by Brilbroeder** [comment]
+1 for this feature

**Comment by giridharvc7** [comment]
Thank you for your patience, We've introduced this feature in v10.13. You can now use `Option+Click` to expand and collapse all children of an element. This work for collections and folders. 

https://user-images.githubusercontent.com/1040583/232968843-ecd9e63c-3d65-4bee-ae12-fba2dd55107e.mov


Please give this a try and let us know what you think

**Comment by cmann90** [comment]
For Windows the combination is `[Alt] + [Left Mouse Click] `

**Comment by StewartRyanSony** [comment]
[Alt] + [Left Mouse Click] isn't working on Windows, however Alt + Left Arrow does work. 
It collapses the entire folder, but when you reopen it, all the sub folders are closed. 
Also note: Alt + Right expands all folders and subfolders
