### ISSUE TITLE
how to use x-mock-match-request-body header

### ISSUE THREAD

**Issue by minoseah629** [a85/POSTMan-Chrome-Extension#6356]
@ratpik 

**Describe the bug**
After updating to 7.0.9, I am trying to use x-mock-match-request-body header. But I am not sure if I am using it properly. 

**To Reproduce**
* Created a Request for SOAP
* Created example for said request with a null SOAP response
* Created a second example for said request with a valid SOAP response
1. Added x-mock-match-request-body header to request
2. Invoked mock service with valid body request for valid response

**Expected behavior**
I expect to see my valid soap response

**Actual Behavior**
I get the null soap response. 

* I tried putting x-mock-match-request-body header on request, example request, and example response.

When I added to request, I got mock request not found error.

**Screenshots**
https://github.com/postmanlabs/postman-app-support/issues/3602#issuecomment-482129178

**App information (please complete the following information):**
 - App Type - Native App
 - Postman Version - 7.0.9
 - OS: Window 10 v1809

**Additional context**
#3602

**Comment by minoseah629** [comment]
For some reason, this seems to be working properly on a different soap project.  

https://www.getpostman.com/collections/2203ad46c26ad9452361

Not sure why I cannot reproduce same result on my actual project

**Comment by ratpik** [comment]
@minoseah629 - If you have two saved examples with the exact same path and request body, both the saved examples are possible responses to your input and we end up returning the first one.

I have slightly modified the request part of your saved examples from the collection link that you have provided. Here is the updated collection -> https://www.getpostman.com/collections/2c99d545d59280736f2f

Now if you create a mock on the above collection you can make the below request to get the non-empty response:
```
curl -X POST \
  <your_mock_url>/def \
  -H 'Content-Type: text/xml' \
  -H 'x-mock-match-request-body: true' \
  -d '<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:hol="http://www.holidaywebservice.com/HolidayService_v2/">
   <soapenv:Header/>
   <soapenv:Body>
      <hol:GetCountriesAvailable/>
   </soapenv:Body>
</soapenv:Envelope>'
```

Response:
```
<?xml version="1.0" encoding="utf-8"?>
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <soap:Body>
        <GetCountriesAvailableResponse xmlns="http://www.holidaywebservice.com/HolidayService_v2/">
            <GetCountriesAvailableResult>
                <CountryCode>
                    <Code>Canada</Code>
                    <Description>Canada</Description>
                </CountryCode>
                <CountryCode>
                    <Code>GreatBritain</Code>
                    <Description>Great Britain and Wales</Description>
                </CountryCode>
            </GetCountriesAvailableResult>
        </GetCountriesAvailableResponse>
    </soap:Body>
</soap:Envelope>
```

To get the empty response send this request:
```
curl -X POST \
  <your_mock_url>/abc \
  -H 'Content-Type: text/xml' \
  -H 'x-mock-match-request-body: true' \
  -d '<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:hol="http://www.holidaywebservice.com/HolidayService_v2/">
   <soapenv:Header/>
   <soapenv:Body>
      <hol:GetCountriesAvailable/>
   </soapenv:Body>
</soapenv:Envelope>'
```

and the corresponding response will be
```
<?xml version="1.0" encoding="utf-8"?>
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <soap:Body>
        <GetCountriesAvailableResponse xmlns="http://www.holidaywebservice.com/HolidayService_v2/">
            <GetCountriesAvailableResult>
                
            </GetCountriesAvailableResult>
        </GetCountriesAvailableResponse>
    </soap:Body>
</soap:Envelope>
```

**Comment by minoseah629** [comment]
Thank you @ratpik. 

But I am confused by your response.  

In my collection, there is a request called Mock Service.  

When I use UnitedStates as the country code in the body request, I get Matching Response example from working soap request Copy GetHolidays as expected.

When I use Scotland as the country code, I get a No Holidays example as expected.  

I am going to submit a request via Postman center because the SOAP assets are sensitive. 

https://support.getpostman.com/hc/en-us/requests/31571

**Comment by minoseah629** [comment]
Here is my last Postman Support response. 
I think I figured out my issue.

As one of my headers of my Example and my actual request is the Content-Type, but I need to make it application/soap+xml.

But when I go over to my Body for either example or request, the body format was selected as text but is actual xml. I specifically need my body to be application/soap+xml for my mock service to communicate with my true SOAP client application.

When I select any item, it changes the Content-Type in my headers.

Can the dropdown allow application/soap+xml? or know that application/xml includes application/soap+xml as its a subset of application/xml?

I was told by Postman Support to make a request for this, but i couldnt find the issue with this type of request

**Comment by ratpik** [comment]
@minoseah629 - We are working on improving the body matching logic to allow similar `content-type`'s like `application/soap+xml` and `application/xml` to be treated in a similar fashion while performing the body matching operation.

**Comment by ratpik** [comment]
@minoseah629 - We have pushed a fix for this. You should be able to mock examples that use `application/soap+xml`.

**Comment by hqinfosystem** [comment]
> @minoseah629 - We have pushed a fix for this. You should be able to mock examples that use `application/soap+xml`.

is postman support application/json content-type to match request body parameter? i'm creating a mock server with example and tried content-type application/json in request body parameter but mock server response failed when i pass x-mock-request-body as true

**Comment by ratpik** [comment]
@hqinfosystem - `application/json` is supported while matching request body. Can you verify that this header is set in the request headers section of your saved example?

**Comment by hyp530** [comment]
> > @minoseah629 - We have pushed a fix for this. You should be able to mock examples that use `application/soap+xml`.
> 
> is postman support application/json content-type to match request body parameter? i'm creating a mock server with example and tried content-type application/json in request body parameter but mock server response failed when i pass x-mock-request-body as true

Hi. Have you fixed this issue? I have the same issue on x-mock-request-body for application/json. 
It works fine on Postman, but it failed when the request was sent from my web app. I already checked for several times that the body is matched. Not easy to identify the reason.

**Comment by akokov** [comment]
issue still present and no example how to solve it

**Comment by minoseah629** [comment]
@akoko, I haven’t tried. But it was 3 years ago.
