### ISSUE TITLE
Dashboard: Invite people to your workspace by sharing a link with them.

### ISSUE THREAD

**Issue by JP-from-Postman** [a85/POSTMan-Chrome-Extension#6358]
**Describe the bug**
When creating a multi-use invite link, the text describing it mentions:

"Invite people to your **workspace** by sharing a link with them."

Since this link is for joining a team, not a specific workspace, this is a little confusing.

**To Reproduce**
1. Go to https://go.postman.co/team/invite
2. See: the text under **Via link**

**Expected behavior**
"Invite people to your **team** by sharing a link with them."

**Screenshots**
<img width="499" alt="Screen Shot 2019-04-24 at 4 12 38 PM" src="https://user-images.githubusercontent.com/43283131/56699803-ec375200-66ab-11e9-9f63-961c9787401c.png">

**App information (please complete the following information):**
 - App Type [e.g. Chrome App, Native App]
 - Postman Version [e.g. 6.0.1]
 - OS: [e.g. macOS High Sierra 10.13.2]

**Additional context**

**Comment by preethammavin** [comment]
The issue has been fixed with an updated copy
