### ISSUE TITLE
I lost my folder while sharing

### ISSUE THREAD

**Issue by e8-ChenKaipeng** [a85/POSTMan-Chrome-Extension#6361]
**Describe the bug**

**To Reproduce**
Account chen950103@qq.com

Have a folder NewEChat

When I manipulated sharing to others, it disappeared.

I can't see this folder anymore. There are many APIs in it.

When I looked at my historical operation, I found it and clicked on it. It reminds me that I have no authority.

Hope to help me find my folder.

I checked the garbage bin immediately after the problem occurred and there was no record in it.

The operation using web pages. Then I lost this folder after local synchronization.

I tried to capture the unique identity of this folder

5809215-45198d6c-c27a-6dfb-4888-235fe4427b9c

Hope to help me find it.

I guess the authority of this file is no longer mine.

I don't know who he was transferred to.

**Comment by sujayvenaik** [comment]
Hey @chen950103 
Can you whether you can still see that entity (collection) in the dashboard?
You can access the dashboard by pressing the user icon -> profile.

Also, if I understand it correctly you can no longer access your collection after you shared?

**Comment by preethammavin** [comment]
Closing the issue has with the current information , we are not able to deduce the issue. Please feel free to reopen the issue with the required information so that we can get it resolved.
