### ISSUE TITLE
Environment fields are moved in the quick edit if one is deactivated

### ISSUE THREAD

**Issue by eloyucu** [a85/POSTMan-Chrome-Extension#6362]
I deactivated one of the env vars (the one in the third place), and then when I edit one of the variables under this deactivated one, the new value doesn´t go to the correct one, instead of that it goes to the bellow var: if I edit the 4th, the value goes to the 5th (and so on...).

How to reproduce:
==

1) Deactivate one of the vars:
![image](https://user-images.githubusercontent.com/2331045/56733045-54933b80-675f-11e9-9f31-5d4dea8262b9.png)

2) Edit one the variables in the quick edit area:
![image](https://user-images.githubusercontent.com/2331045/56733211-c8cddf00-675f-11e9-93cf-679a7703bf6f.png)

3) The values seems that goes to both variables the good one and the next:
![image](https://user-images.githubusercontent.com/2331045/56733289-fe72c800-675f-11e9-9ef2-3a7f0b8f3f91.png)

4) But the Manage Environment area only the second one is modified:
![image](https://user-images.githubusercontent.com/2331045/56733364-2feb9380-6760-11e9-97f5-ca16b014d092.png)

Thanks.

PS: My version: _You are up to date! Postman v7.0.9 is the latest version._

**Comment by YounixM** [comment]
@eloyucu Thanks for bringing this to our notice. We were able to reproduce it. We are working on the fix and will update the thread when the fix released.

**Comment by Ekusu1** [comment]
+1

This also affects scripts (pre for sure, post not entirely sure),
My pre-script is supposed to build an URL and save it into a variable but the they stay the same.
It works sometimes thought and im not sure if it has anything to do with the variables or something else.

PS: This error is not reproducable in v7.0.7

**Comment by harryi3t** [comment]
@Ekusu1 @eloyucu @chrisdeso @piniacat @antonrabe @tiaraju
The fix is out in our [canary](https://www.getpostman.com/downloads/canary) build and will be available in our next production release.

**Comment by numaanashraf** [comment]
The fix is available in Postman v7.1.0.
