### ISSUE TITLE
Collection published to custom domain has "been moved or deleted"

### ISSUE THREAD

**Issue by JP-from-Postman** [a85/POSTMan-Chrome-Extension#6365]
**Describe the bug**
User reported that they unpublished a Collection from a custom domain, and are now unable to publish to the same custom domain again. The domain appears to be linked to a Collection, but accessing either the custom domain or direct docs link results in a 404, with the message:

"We couldn't locate the collection you're looking for. It may have been moved or deleted."

See internal notes for more info.

**To Reproduce**
1. Try loading custom domain page (404)
2. Try loading direct docs page URL (404)

**Expected behavior**
Un-publishing a Collection un-links the docs page from the custom domain. Republishing the Collection to the custom domain is successful.

**Screenshots**

**App information (please complete the following information):**
 - App Type [e.g. Chrome App, Native App]
 - Postman Version [e.g. 6.0.1]
 - OS: [e.g. macOS High Sierra 10.13.2]

**Additional context**

**Comment by dhineshwiz** [comment]
Hey @JP-from-Postman thanks for reporting the issue, are you not able to publish to same domain, or after publishing u are seeing 404 on that custom domain ? If it was the second case, its because domain caching which is pointing old published data, you can see the updated published data after ~10 mins. Ideally this cache should be invalidated. We are working on that fix, we will update soon.

**Comment by JP-from-Postman** [comment]
Hey @dhineshwiz, I reported this on behalf of the user who encountered it. I'll add details to JIRA.

**Comment by JP-from-Postman** [comment]
@dhineshwiz Another occurrence of this was just reported via Support, except with a status 403 error instead of 404:
<img width="797" alt="Screen Shot 2019-06-25 at 3 30 30 PM" src="https://user-images.githubusercontent.com/43283131/60138281-a0159600-975e-11e9-8ae1-958861099fdc.png">
Flagging it here just in case it's relevant.

**Comment by ranchanarajasekaran** [comment]
The issue has been fixed.
Please feel free to reopen the issue to report any feedback on the same.
