### ISSUE TITLE
Is it possible to export the postman collection as csv.

### ISSUE THREAD

**Issue by srajkavithaa** [a85/POSTMan-Chrome-Extension#6369]
Any idea about exporting the collections/requests with all sub folder details as a csv file.
Thanks

**Comment by shamasis** [comment]
No. But you can export a run using https://www.npmjs.com/package/newman-reporter-csv

You can try exporting to JSON and then try using documentation from schema.getpostman.com to convert to a CSV. You can use https://schema.getpostman.com to write your converter. You can also try posting this request on community.getpostman.com and see if anyone from the community has anything already built along these lines.
