### ISSUE TITLE
Extracting data from responses in postman

### ISSUE THREAD

**Issue by Michal-Kolomanski** [a85/POSTMan-Chrome-Extension#6373]
Hello,
I have a problem with extracting data from response in Postman.
My response from the server:
![image](https://user-images.githubusercontent.com/47147210/56807113-29c3e880-682e-11e9-85a9-8606badb74fa.png)

I want to extract a variable called "row_order".

I wrote some code, but this doesnt work. 

![image](https://user-images.githubusercontent.com/47147210/56807221-7c9da000-682e-11e9-9f08-345f4c0b59ad.png)

I think that my code is correct but unfortunately additional brackets [ ] in response makes my solution wrong.

 - Native Postman

**Comment by shamasis** [comment]
Hi. This is an issue with incorrect usage of Javascript. An array in response has to always be used using its index [] sign. Maybe you could post this question in https://community.getpostman.com/ to get help around how to write this code. 

From the looks of it, it seems that you’ll need to iterate on the rows using a loop and then set variables.

**Comment by DannyDainton** [comment]
I've written this post on our community site that might help with this question. 

https://community.getpostman.com/t/sharing-tips-and-tricks-with-others-in-the-postman-community/5123/5

This issue can be closed now.
