### ISSUE TITLE
Team unable to edit Collection, or manage permissions

### ISSUE THREAD

**Issue by JP-from-Postman** [a85/POSTMan-Chrome-Extension#6374]
[Submitted by Postman Support, on behalf of user]

**Describe the bug**
Two Collections that were transferred to a new owner can't be edited. The new owner also can't see the Modify Permissions option in ellipsis menu for the Collection, or change its permissions otherwise.

**To Reproduce**
1. Team member who owned Collections removed from team
2. Collections transferred to new owner
3. New owner unable to edit Collection, or change permissions. Same for other team members.

**Expected behavior**
Collection is transferred to new owner when team member is removed, new owner is able to manage permissions.

**Screenshots**
<img width="217" alt="PastedGraphic-1" src="https://user-images.githubusercontent.com/43283131/56834611-bd91b680-6826-11e9-9e13-5a6d1c01abd9.png">

**App information (please complete the following information):**
 - App Type: Native app
 - Postman Version: 6.7.4
 - OS: macOS

**Additional context**

**Comment by JP-from-Postman** [comment]
Any updates here?

**Comment by a85** [comment]
@JP-from-Postman Is it possible to duplicate or export the collection and give people new access?

**Comment by JP-from-Postman** [comment]
@a85 yep, at least one of the users who reported this ended up using that workaround successfully.

**Comment by DannyDainton** [comment]
Hey @JP-from-Postman - Is this still an active issue for the user?

**Comment by JP-from-Postman** [comment]
@DannyDainton I haven't seen this pop up again since, I think we're good.

**Comment by DannyDainton** [comment]
I'll close this for now but we can always open it up again if more cases come in.
