### ISSUE TITLE
Exclude domains for proxy 

### ISSUE THREAD

**Issue by akhilnambiar29** [a85/POSTMan-Chrome-Extension#6380]
**Is your feature request related to a problem? Please describe.**
The proxy setting on the postman app doesn't have an option to exclude domains . For eg . I need a proxy for connecting to APIs to outside my office network but for APIs hosted in the internal network , I don't need a proxy . 

**Describe the solution you'd like**
Add an option to exclude domains for proxy . 

**Describe alternatives you've considered**
Found this feature in all the IDEs I have been using but not in postman . 

**Additional context**
Attached a screenshot of Intellij providing the same feature . 
![Screenshot 2019-04-29 at 10 24 17](https://user-images.githubusercontent.com/17107367/56884151-2cf6e880-6a69-11e9-9c6e-35d6b892912d.png)

**Comment by codenirvana** [comment]
@aqeelsmith Thanks for the feature request.
As a workaround, you can set `NO_PROXY` environment variable to unblock your workflow.
Refer: https://github.com/postmanlabs/postman-app-support/issues/3942#issuecomment-355333474

**Comment by codenirvana** [comment]
@aqeelsmith @naclma @teunis90 Postman v7.9.0 added support for bypassing global proxy settings on a per-host basis.

![Screenshot 2019-10-16 at 12 39 18 PM](https://user-images.githubusercontent.com/4865836/66896236-0d04b280-f012-11e9-8793-6087d829a8de.png)

Try it out and share the feedback.
