### ISSUE TITLE
Wrong Monitoring Alert Emails sent to Enterprise team users

### ISSUE THREAD

**Issue by harsh-reality** [a85/POSTMan-Chrome-Extension#6382]
**Describe the bug**
The monitoring alert email sent to a Postman Enterprise user has the content and messaging that of a Postman Pro team.

Even the numbers like # of requests are related to the Pro team and not the Enterprise team.

PFA the screenshot
![Screenshot 2019-04-29 at 3 44 07 PM](https://user-images.githubusercontent.com/12132423/56891484-3c425a00-6a9a-11e9-90bf-a180bb9751ca.png)

**Expected behavior**
A clear description of the # of requests included in the Enterprise plan and other relevant information.

**Comment by debjeetsarkar** [comment]
This has been addressed.
