### ISSUE TITLE
Add instructions or call to action to contribute to templates

### ISSUE THREAD

**Issue by loopDelicious** [a85/POSTMan-Chrome-Extension#6385]
**Is your feature request related to a problem? Please describe.**
Currently, when I navigate to the Templates tab of the New+ modal, I am not aware what these "Templates" are, how it's different from the other "API Network" tab, and that I can also contribute a template of my own. 

**Describe the solution you'd like**
Include copy that explains that these are community contributions, and hyperlink to docs to learn more about 1) consuming Templates and 2) sharing Templates.

**Comment by preethammavin** [comment]
@loopDelicious thanks for reporting this. We have included a link to documentation from the app where users can know more about how they can publish and contribute to Postman Templates.
