### ISSUE TITLE
Windows: app shortcut refers to AppData for different Windows user.

### ISSUE THREAD

**Issue by JP-from-Postman** [a85/POSTMan-Chrome-Extension#6386]
[Submitted by Postman Support, on behalf of user]

**Describe the bug**

_(Note: Postman native app is installed on a terminal server / RDS Host, running Windows Server 2012, in this example)_

When Postman app is installed, it writes into AppData for the active Windows user:
`C:\Users\<user1>\AppData\Local\Postman\app-7.0.7 `
When logging in as a different Windows user, the app shortcut refers to:
`C:\Users\<user2>\AppData\Local\Postman\Update.exe --processStart "Postman.exe"`
But, the "Start in" for the shortcut still points to <user1>'s AppData directory:
`C:\Users\<user1>\AppData\Local\Postman\app-7.0.9`

**To Reproduce**
(Unknown if installing on VM is required to reproduce)
1. Install Windows Native App under a user account
2. Login to separate Windows User Account
3. Attempt to click Postman App shortcut
4. See error:
"Problem with Shortcut. 
The item 'Update.exe' that this shortcut refers to has been changed or moved, so this shortcut will no longer work properly." 

**Expected behavior**
App shortcut doesn't point to AppData under a different user directory. App shortcut under different Windows users works for that user account.

**Screenshots**

**App information (please complete the following information):**
 - App Type: Native app
 - Postman Version: v7.0.7
 - OS: Windows Server 2012

**Additional context**

**Comment by DannyDainton** [comment]
Hey @JP-from-Postman / @kamalaknn 

Is this still an issue with the latest versions?

**Comment by DannyDainton** [comment]
I'm going to close this issue but we can open this up again if this is still a problem that people are facing.
