### ISSUE TITLE
Getting error after clicking on teams (view team settings) from dashboard

### ISSUE THREAD

**Issue by ash007-postman** [a85/POSTMan-Chrome-Extension#6387]
**Describe the bug**
Getting error after clicking on "your team/team settings " from the dashboard.
**To Reproduce**
1. Login to web dashboard
2. Click on "your team"->"team settings"
3. See error as attached below 

**Expected behavior**
Clicking on "team settings" should show the team info. 

**App information (please complete the following information):**
 - App Type Native
 - Postman Version  7.0.9

![Screenshot 2019-04-30 at 6 28 06 AM](https://user-images.githubusercontent.com/41741228/56936062-d9d97000-6b12-11e9-921d-65c9a203d86d.png)
<img width="335" alt="Screenshot 2019-04-30 at 6 28 33 AM" src="https://user-images.githubusercontent.com/41741228/56936063-d9d97000-6b12-11e9-9446-47a3558e8599.png">
<img width="481" alt="Screenshot 2019-04-30 at 6 47 32 AM" src="https://user-images.githubusercontent.com/41741228/56936234-df838580-6b13-11e9-9dbb-77190f2267ff.png">

**Comment by preethammavin** [comment]
The issue has been fixed, feel free to reopen the issue if it reoccurs again
