### ISSUE TITLE
i am not geeting update option

### ISSUE THREAD

**Issue by ankurkumarnodejs** [a85/POSTMan-Chrome-Extension#6388]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**App information (please complete the following information):**
 - App Type [e.g. Chrome App, Native App]
 - Postman Version [e.g. 6.0.1]
 - OS: [e.g. macOS High Sierra 10.13.2]

**Additional context**

**Comment by preethammavin** [comment]
@ankurkumarnodejs could you provide more details of the bug , and use the templates suggested above so that we can debug it.

**Comment by preethammavin** [comment]
Closing the issue, as the information provided do not provide steps to identify or solve the issue
