### ISSUE TITLE
Unable to access billing section in the dashboard - 'Something went wrong' error

### ISSUE THREAD

**Issue by cyrielle-hada** [a85/POSTMan-Chrome-Extension#6390]
**Describe the bug**
Unable to access https://app.postman.co/billing. The page is loading forever and then throws the below error. 
<img width="782" alt="Screen Shot 2019-04-30 at 3 00 21 PM" src="https://user-images.githubusercontent.com/47351631/56953637-eb337400-6b34-11e9-9f37-ef9829d63eb3.png">

**To Reproduce**
1. Go to https://app.postman.co/billing
2. See page loading
3. See error

**Expected behavior**
Be able to see the billing section and perform billing actions. 

**App information (please complete the following information):**

- App version 4.11.0-chrome
- MacOS Mojave
- Chrome

**Additional context**
- The issue was replicated in incognito mode and Safari. 
- See error JS console in the associated ticket.

**Comment by abhijitkane** [comment]
@cyrielle-hada This should be addressed for all users now. Feel free to add a comment if this is seen again.

**Comment by JP-from-Postman** [comment]
@abhijitkane Just received another report of this behavior. Billing user reports that they receive this error for any page on the web dashboard, not just the billing sections. Adding report to internal notes.
