### ISSUE TITLE
Chrome app displays "update to v7.0" for a non team user

### ISSUE THREAD

**Issue by Raj-postman** [a85/POSTMan-Chrome-Extension#6391]
**Describe the bug**
When using the Chrome app, non-team user receives message "Your team updated to Postman v7.0. To access your team workspaces and collections, you must also update to v7.0".

**To Reproduce**
Open the Chrome App and you see the message

**Expected behavior**
The message shouldn't be displayed in the Chrome App, or for users who are not part of the upgraded team

**Screenshots**
![Message](https://user-images.githubusercontent.com/47771757/56955415-ef748700-6b5e-11e9-8478-e0b90837d951.png)

**App information (please complete the following information):**
 - App Type - Chrome app
 - Postman Version - v5.5.4
 - OS: OSX

**Comment by preethammavin** [comment]
The issue has been resolved
