### ISSUE TITLE
Error when updating Environment variables through quick look

### ISSUE THREAD

**Issue by tiaraju** [a85/POSTMan-Chrome-Extension#6395]
**Describe the bug**
Whenever I'm trying to update an environment variable through the quick look option, the variable below the one I'm trying to update is actually updated.

**To Reproduce**
1. Create two variables in your environment (var1, var2)
2. Try to update var1 using the quick look edit option
3. Check that the value you wanted to update is now in var2, not in var1 as you tried to update.

**Expected behavior**
It's expected that whenver you try to update a variable, the one you want to update is actually updated.

**Screenshots**

**App information (please complete the following information):**
`You are up to date! Postman v7.0.9 is the latest version.`
Desktop Version

**Additional context**
NA

**Comment by harryi3t** [comment]
@tiaraju Thank you for raising this issue.
Do you have any variables that are disabled? We are already tracking [an issue](https://github.com/postmanlabs/postman-app-support/issues/6362) where this happens.

**Comment by tiaraju** [comment]
Hey @harryi3t 

Sorry I didn't check it before. I don't actually have a disabled variable, but I do have an empty slot. So yeah, it's related to the issue you linked.
Sorry for the duplicate.

regards.
