### ISSUE TITLE
Feature Request: List Headers added in pre-request scripts in UI as Temporary headers

### ISSUE THREAD

**Issue by E1337Kat** [a85/POSTMan-Chrome-Extension#6396]
**Is your feature request related to a problem? Please describe.**
Thanks to the wonderful and amazing new feature to add and update headers at a collection level, I have started moving towards using that. I noticed however, that now I don't know what all my request headers are. 

**Describe the solution you'd like**
I believe the best route to solve this would be to include the generated request headers in the UI as Temporary Headers (as they kinda are). At the time of the request, we know what headers are being sent, so this can just be pulled from the request.

**Describe alternatives you've considered**
Alternatively, the response area could have a new tab added "Request Headers" or something of the sort. When you make a request with the postman console open, the object includes Request Body, Request headers, Response Headers, and Response Body; All the data is there after each request.

**Additional context**
Postman with temp headers showing:
![postman_temp_headers](https://user-images.githubusercontent.com/2062516/56968706-a823d180-6b31-11e9-9676-9299c99cdf18.png)

Console opened showing request details:
![postman_console](https://user-images.githubusercontent.com/2062516/56968705-a823d180-6b31-11e9-9495-71a5f6c9c764.png)

**Comment by shamasis** [comment]
Agreed. @postmanlabs/runtime we might need to start doing mutation tracking on HeaderList

**Comment by arlemi** [comment]
Hey @E1337Kat!

We've just released a new feature called [Live Preview](https://community.postman.com/t/live-preview-is-out/11497) in the latest version of the app (7.21.0) which adds authorization headers at the collection level to the auto-generated headers of the requests. 

![collectionheader](https://user-images.githubusercontent.com/5029719/77418785-4dd1d600-6dbf-11ea-9b8c-a959936dbba6.gif)

Hope this resolves your feature request, let us know if not!
