### ISSUE TITLE
Don't list deleted collections in Postman templates

### ISSUE THREAD

**Issue by loopDelicious** [a85/POSTMan-Chrome-Extension#6398]
Currently if I try to import a template (that has been deleted) from the New+ button, I receive this error.

<img width="1482" alt="Screen Shot 2019-04-29 at 12 03 16 PM" src="https://user-images.githubusercontent.com/17693714/56974475-ca165780-6b23-11e9-9c31-7dd3391681e6.png">

Suggestion: don't list deleted collections in Postman templates

**Comment by preethammavin** [comment]
@loopDelicious thanks for reporting this. Right now we remove templates once they are deleted once they are interacted once by any user. But keeping this open till we get a better solution in place
