### ISSUE TITLE
FEATURE REQUEST : Basic Authentication with variables

### ISSUE THREAD

**Issue by ymeunier** [a85/POSTMan-Chrome-Extension#6399]
Hi DevTeam
I wish I could perform an authentication from my variables (environment / global / collection).
do you think that is possible?

Best regards,
Yann

**Comment by chrisdeso** [comment]
Hey @ymeunier, it's definitely possible. You can leverage the double curly brace notation i.e. `{{authToken}}` within the request builder's Headers/Parameters section to pass in any authentication information that's stored as a variable.

Here's an example:
![image](https://user-images.githubusercontent.com/4734306/57027752-de7d5180-6c02-11e9-96cf-5798c57509ba.png)

Here's some relevant documentation:

- [Variables](https://learning.getpostman.com/docs/postman/environments_and_globals/variables)
- [Managing Environments](https://learning.getpostman.com/docs/postman/environments_and_globals/manage_environments)

---

Adding to this – you can do the same with the authentication helper:
![image](https://user-images.githubusercontent.com/4734306/57056364-ad833800-6c67-11e9-8980-9eb660a7e405.png)

**Comment by ymeunier** [comment]
Thanks ! 
During my fisrt test, it did'nt work :)
