### ISSUE TITLE
 ReferenceError | console is not defined when using console.log

### ISSUE THREAD

**Issue by VinceBarresi** [a85/POSTMan-Chrome-Extension#6400]
**Describe the bug**
I'm trying to write a schema validation test using `ajv` and then doing a simple `console.log` and keep seeing `ReferenceError | console is not defined`. 

**To Reproduce**
1. create a new collection
2. add a schema object as a prescript step `schema = { ${schema} }`
3. add the following code to the test

```
var Ajv = require('ajv');
const ajv = new Ajv({ allErrors: true });

pm.test("Status code is 200", function() {
    pm.response.to.have.status(200);
});

pm.test("Homepage Schema Validation", function() {
    valid = ajv.validate(schema, data);
    if (!valid) console.log(validate.errors);
    pm.expect(valid).to.be.true;
    
});
```
4. Add the url `https://www.msg.com/wp-json/msg/v1/pages?slug=homepage` to send request to
5. run the test

**Expected behavior**
`console.log(validate.errors);` prints the schema errors to the console

**Screenshots**
<img width="997" alt="Screen Shot 2019-04-30 at 9 00 03 PM" src="https://user-images.githubusercontent.com/5244883/57002112-f7e2b700-6b8a-11e9-9c22-9e179a0f6956.png">

**App information (please complete the following information):**
 - Postman Version 7.0.9 (7.0.9)
 - macOS High Sierra 10.14.4

**Additional context**

**Comment by shamasis** [comment]
@VinceBarresi - there is a small quirk while using AJV. Can you try initialising AJV like the following?

```
var Ajv = require('ajv'),
    ajv = new Ajv({logger: console}); // note how you're sending logger forcefully.
```

**Comment by shamasis** [comment]
@postmanlabs/runtime - Let's create a small wrapper on AJV, which does this implicitly?

**Comment by VinceBarresi** [comment]
@shamasis Ok I added new initializing code```var Ajv = require('ajv'),
    ajv = new Ajv({logger: console}); // note how you're sending logger forcefully.``` to my test and am able to see logs without reference errors being thrown. Curious to know what the quirk is you're referencing and why this ajv needs to be initialized this way. Thanks for the help by the way. I was stuck on this for a while yesterday.

**Comment by shamasis** [comment]
@VinceBarresi - The issue is outlined here https://github.com/epoberezkin/ajv/issues/950

But I am glad your issue was finally resolved. We will work on something that ensures this is better handled.

**Comment by VinceBarresi** [comment]
@shamasis Thanks for the info and thanks again for the help. Really appreciate it!
