### ISSUE TITLE
Authentication - Enable a default authentication method when all others are turned off

### ISSUE THREAD

**Issue by chrisdeso** [a85/POSTMan-Chrome-Extension#6401]
**Is your feature request related to a problem? Please describe.**
In the event that all authentication methods are turned off (SSO, Email/Password, Google Sign-in), teams are unable to sign in.

**Describe the solution you'd like**
Require that one authentication method be enabled (and working if SSO) by default.

Other ideas – Magic Link login!

**Additional context**
![image](https://user-images.githubusercontent.com/4734306/57004120-dfc26600-6b91-11e9-8f0c-2b01450a058f.png)

[Filed by Postman]

**Comment by shamasis** [comment]
That may be a security risk. We could look into login using email address -> "magic link" login.

**Comment by chrisdeso** [comment]
The magic link idea is great @shamasis – updated the original post to reflect it.

**Comment by ArjunSingh-PM** [comment]
A fix is now in place to ensure that one authentication method is enabled at all time.
