### ISSUE TITLE
The request response without IP is inconvenient 

### ISSUE THREAD

**Issue by Zjmainstay** [a85/POSTMan-Chrome-Extension#6402]
**Is your feature request related to a problem? Please describe.**
When I change my host for a new IP , I can't sure whether postman changed or not.

**Describe the solution you'd like**
I hope the header for response can tell me which IP response my request now, just like the `Remote Address: xxx.xxx.xxx.xxx:80` in Chrome network headers show me.

**Additional context**
Just like this
```
Request URL: https://github.com/
Request Method: GET
Status Code: 200 OK
Remote Address: 13.250.177.223:443
```

**Comment by shamasis** [comment]
Agree. We are working on this... not that far away. :-)

**Comment by codenirvana** [comment]
Low-level network details are now accessible in the Postman Console (Postman v7.10).

<img width="643" alt="Screenshot 2019-11-04 at 1 17 18 PM" src="https://user-images.githubusercontent.com/4865836/68105760-89016480-ff05-11e9-8a19-39d882a67de2.png">
