### ISSUE TITLE
Unable to join multiple teams

### ISSUE THREAD

**Issue by abhisekp** [a85/POSTMan-Chrome-Extension#6403]
**Describe the bug**
One of my team member is currently in another team and they're unable to join my team.  Please look into it. Also the other team's name has changed but in the error it is showing the old team name.

*Error:*
```text
400
You are already part of a Pro team called "<Other Old Team Name>". Please leave the old team before accepting this invite. Leave your existing team
```

**To Reproduce**
1. Join team A
2. Invitation from team B
3. Error is shown

**Expected behavior**

**App information (please complete the following information):**
 - App Type [e.g. Chrome App, Native App]: Chrome
 - OS: [e.g. macOS High Sierra 10.13.2]: Windows 10

**Comment by abhijitkane** [comment]
@abhisekp Joining multiple teams is currently not supported in Postman.

The user involved will need to leave the old team (https://go.postman.co/team) as indicated in the error message, or create a new user account to join your team.

We'll look into the old name being shown in the error message.
