### ISSUE TITLE
Responses with "image/jpeg" render image extremely slow (but download fast)

### ISSUE THREAD

**Issue by mostwired** [a85/POSTMan-Chrome-Extension#6404]
I have an API that returns an image. It renders fast (< 2 sec), if I test URL in-browser. Postman shows the same Time taken for the request (e.g. Time: 1600ms) - however, it takes a while before it renders the response image (I'm talking 14-16 second delay). I'd expect Postman to render the image close to browser speed. See the images below (GIF animations are on replay). Note that the browser cache was cleared, API server restarted and a new, unused previously image selected - to avoid caching in-browser, when taking below videos. 

Browser:
![browser_render](https://user-images.githubusercontent.com/9535192/57023125-3a45db80-6bff-11e9-955b-ca922ddc7135.gif)

Postman:
![postman_render](https://user-images.githubusercontent.com/9535192/57023127-3e71f900-6bff-11e9-9111-3a41fde6b2ab.gif)

App information:
 - Image size: ~4-5 MB, type "image/jpeg"
 - App Type: Native App
 - Postman Version: 7.0.9 (latest as of this post)
 - OS: Windows 10 Pro x64
 - API: Web API, .Net 4.7.2

**Comment by shamasis** [comment]
Yes, it is a limitation as of now. We do a lot of processing to move data around through various parts of Postman App to enable a number of scripting and debugging that a browser is not designed to do. Also, we do not render until full response is received (that is we do not stream response to the UI as it arrives and instead get it as a whole and then render.)

This is something we are aware and would start work on this in mid term. We are tracking this under the master feature here: https://github.com/postmanlabs/postman-app-support/issues/6404 - hence closing this as duplicate.
