### ISSUE TITLE
[Feature Request] Ability to merge teams easily

### ISSUE THREAD

**Issue by carolin-postman** [a85/POSTMan-Chrome-Extension#6405]
**Is your feature request related to a problem? Please describe.**
Looking for an easier way to merge 2 large teams (>50 each). Collaboration has been quite tricky when 2 teams are merging from different companies. 

**Describe the solution you'd like**
Would like to see a seamless/automated way of doing so. 

**Describe alternatives you've considered**
The existing workaround to this is to export data from team A, leave team A, join team B, then import into team B. Or, if needing to access workspaces from team A, developer from team B would need another email address alias for team A and then export data into team B.

**Comment by ArjunSingh-PM** [comment]
Now, we support copying users and data from one Postman team to another. Please contact Postman support if you would like to merge multiple teams to one.
