### ISSUE TITLE
Unable to view the description of an unpaid invoice.

### ISSUE THREAD

**Issue by debjeetsarkar** [a85/POSTMan-Chrome-Extension#6407]
**Describe the bug**
The description for an unpaid invoice is shown as "0" instead of showing the actual description for the invoice.

<img width="1310" alt="Screenshot 2019-04-28 at 12 55 12 PM" src="https://user-images.githubusercontent.com/6427574/57063802-127b7400-6ce2-11e9-8d93-c52f258dc3a2.png">

**Expected behavior**
The unpaid invoice should clearly show the description of it.

**Comment by DannyDainton** [comment]
Closing this as this UI has been updated in the later versions of the platform.
