### ISSUE TITLE
Issue with case sensitivity of request headers (system headers)

### ISSUE THREAD

**Issue by kilitary** [a85/POSTMan-Chrome-Extension#6414]
**Describe the bug**
Some headers sent with smaller first letter, this reveal using Postman. For example [accept-encoding, content-length]

**To Reproduce**
1. Use runner on any collection

**Expected behavior**
All headers start with big letter.

**Screenshots**
![postman_error](https://user-images.githubusercontent.com/1662737/57177643-beea6100-6e6e-11e9-9fca-672291443e0e.png)

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version  v7.0.9 
 - OS: Windows 10

**Comment by shamasis** [comment]
Is this causing any issue? As far as standards go, header capitalisation does not matter for the headers in question unless using a seriously strict and niche server.

**Comment by kilitary** [comment]
yes, causing to stop replying to my requests. Please do capital letters.

**Comment by shamasis** [comment]
Can you point me out to the server that is causing this? An open endpoint or perhaps the name of the server application (apache / node / etc)?

**Comment by codenirvana** [comment]
This is fixed in the latest version of Postman app (v7.3.4).
