### ISSUE TITLE
Team admin not being able to approve a pending invitation request for team.

### ISSUE THREAD

**Issue by debjeetsarkar** [a85/POSTMan-Chrome-Extension#6416]
**Describe the bug**
Team admin is not being able to approve pending invitation request for a team. On attempting to approve a pending invitation gets an error saying "No such invite exists"

**Expected behavior**
The admin should either
 - Not see a pending invitation request if the invitation doesn't exist
  or
 - Get proper reasoning why they can't approve a pending invite.

**Additional context**
DIscovered internally.

**Comment by JP-from-Postman** [comment]
@debjeetsarkar same error occurs for rejecting invite as well. This then becomes a blocker, because the email in question can't be re-invited while there is a pending invite.

**Comment by debjeetsarkar** [comment]
This should be fixed now.
