### ISSUE TITLE
Unable to delete slack Integration

### ISSUE THREAD

**Issue by Ramya-From-Postman** [a85/POSTMan-Chrome-Extension#6417]
**Describe the bug**
When trying to delete a slack integration, it throws an error saying "_Something went wrong(you are not permitted to perform the action. you do not have appropriate permissions to perform this action)_" 

**To Reproduce**
1. Navigate to the [web dashboard](https://go.postman.co)
2. Go to Integrations tab & then slack
3. Try deleting the "**Postman Serch**" 

**Expected behavior**
The integration should get deleted.

**Screenshots**
![image](https://user-images.githubusercontent.com/40994626/57207967-95584380-6fee-11e9-835a-d48b3cfff0f1.png)

![image](https://user-images.githubusercontent.com/40994626/57220754-1bd64a80-701a-11e9-91dc-8b73a75b940e.png)

**App information (please complete the following information):**
 - App Type:  Native App
 - Postman Version [e.g. 6.0.1]
 - OS: [e.g. macOS High Sierra 10.13.2]

**Additional context**

**Comment by kartikjain26** [comment]
@ankitjaggi  can we close this ?
