### ISSUE TITLE
Environmental Variabale values are not updated while running collection through runner

### ISSUE THREAD

**Issue by venkatesuluM** [a85/POSTMan-Chrome-Extension#6418]
Hi @abhijitkane,

We find out the  issue,  environmental variables values were not updated while running collection on Runner. Please have a look into issue.

**Note:** If we invoke request individually, It was updated value on environmental variable file.
**Postman Version:**  Postman v7.0.9

Thanks,
Venkatesh

**Comment by shamasis** [comment]
I think I need more information to be able to debug this. On latest Mac app, I selected a collection that updates environment variables, clicked on persist variables option and started the run. Once the run completed, I could see the environment current values get updated in builder.

**Comment by mukeshknoldus** [comment]
Environment variable values not getting updated while running through the runner and when I export the environment json file, it is still showing values as initial values not current values. 
postman for linux, version 7.1.1

@shamasis

**Comment by venkatesuluM** [comment]
@shamasis , @codenirvana 

We found issue on windows standalone desktop application.
Please find the below screenshots.
[Screenshot.docx](https://github.com/postmanlabs/postman-app-support/files/3344065/Screenshot.docx)

**Comment by codenirvana** [comment]
@venkatesuluM Please share what's the issue. Also, looks like the screenshot is broken.

@mukeshknoldus Exported environment always have initial values, that's the expected behavior. Know more about [sessions in Postman](https://blog.getpostman.com/2018/08/09/sessions-faq/).

**Comment by codenirvana** [comment]
Closing this issue as we are not able to reproduce this internally and we haven't seen other users facing the same.

Please feel free to reopen if the issue persists or you can help us with the steps to reproduce this issue.

**Comment by unisev** [comment]
I'm experiencing this also !
How to re-open ?

**Comment by SolidSnake-Drive** [comment]
I experience this as well. 
To be precise, the environment variables seem to be updated only when the collection runner is successfully *completed*. 
So if you use the collection runner to loop a request infinitely until you manually press stop, it will never be updated.

However it seems the runner has its own local environment during the run, as my loop requires the response from a starting request to run, and grabs it from that virtual version of the environment (despite the env. not being updated on the UI). But when pressing stop, this version of the environment disappears.
