### ISSUE TITLE
Testing if a date sorting is correct in Postman

### ISSUE THREAD

**Issue by Michal-Kolomanski** [a85/POSTMan-Chrome-Extension#6419]
Hello,
I use native Postman and Newman. I am sending a request which has a random date.

In pre-request Script: 

pm.globals.set('hours', _.random(10,23));
pm.globals.set('minutes', _.random(10,59));
pm.globals.set('seconds', _.random(10,59));
pm.globals.set('day', _.random(10,30));
pm.globals.set('month', _.random(10,12));
pm.globals.set('year', _.random(2010,2019));

in body:

{
    "eventtype": "{{eventtype}}",
    "severity" : "{{severity}}",
    "description" : "{{event_description}}",
    "settingtime":  "{{year}}-{{month}}-{{day}}T{{hours}}:{{minutes}}:{{seconds}}"
}

Example output:

{
    "eventtype": "manual",
    "severity": "warning",
    "description": "fwquovfwwu",
    "settingtime": "2018-12-27T11:30:53"
}

That request generate an event for me. After generating plenty of that kind of events I send another request with a TimeBegin parameter  which should get every event for me which has a parameter "settingtime" greater than my parameter TimeBegin.   

For example:
![image](https://user-images.githubusercontent.com/47147210/57217287-7d82be80-6ff2-11e9-9564-7c4ef52cd459.png)

TimeBegin = 2016-11-18T11:41:51 and request should return every event which has a "newer" setting_time parameter than this. 

I want to write a test which automatically checks if every generated event which had parameter setting_time greater than TimeBegin was returned by the response of the server. Moreover, checks if response is sorted correctly (in rising mode).

I would be very grateful for any kind of help.

**Comment by sivcan** [comment]
Solved on community post -  https://community.getpostman.com/t/testing-if-a-date-sorting-is-correct-in-postman/5293/2

Closing this ticket.
