### ISSUE TITLE
Editing Environment Variable through Eye icon modifies more than one variable

### ISSUE THREAD

**Issue by rawkartoffel** [a85/POSTMan-Chrome-Extension#6420]
**Behavior**
Editing an Environment Variable through the "Eye" icon next to the Environment dropdown menu, will modify the selected Variable and the one that is placed two spaces below.

**How To Reproduce**
1. Click on "Eye" icon next to Environment dropdown menu
2. Click on "pen" icon to edit the selected variable
3. Press Enter key or outside of the textbox to modify the selected variable

**Expected behavior**
Only selected Variable is modified.

**Actual behavior**
Selected variable and the one two spaces below is modified with the same value.

**Screenshots**

![image](https://user-images.githubusercontent.com/32609688/57218134-d8b5b080-6ff4-11e9-8c66-037b23c91620.png)

**App information (please complete the following information):**
 - Desktop App
 - Postman 7.0.9

**EXTRA INFORMATION**
After this bug is reproduced/triggered, scripts in Tests like "pm.environment.set" or similar won't work (like, if Status = 200, put this value of the JSON on an Environment Variable).

**Comment by shamasis** [comment]
Yep. I think we are tracking a similar issue and we are fixing it in the ongoing work set. Thanks for reporting it 😊

@numaanashraf cc.

**Comment by shamasis** [comment]
Closing this issue. Please follow updates at: https://github.com/postmanlabs/postman-app-support/issues/6362

**Comment by harryi3t** [comment]
@piniacat The fix is available in Postman v7.1.0

**Comment by rawkartoffel** [comment]
@harryi3t I saw this when it updated on Friday, thanks for informing me!
