### ISSUE TITLE
Dragging tab also drags other UI elements

### ISSUE THREAD

**Issue by ritwijsinha** [a85/POSTMan-Chrome-Extension#6422]
**Describe the bug**
Dragging tab also drags other UI elements

**To Reproduce**
1. Have a really long Request Name
2. Drag the tab 

**Expected behavior**
Only the tab should be dragged

**Screenshots**
![TabDragBugCrop](https://user-images.githubusercontent.com/19693841/57229624-32899b00-7034-11e9-987f-9b1aeeeedbae.gif)

**App information (please complete the following information):**
Postman for Mac
Version 7.0.9
OS X 18.2.0 / x64

**Comment by numaanashraf** [comment]
Fixed in Postman v7.2.0
