### ISSUE TITLE
When creating a variable from a response, it is not keeping the order of the response

### ISSUE THREAD

**Issue by thetreythomas** [a85/POSTMan-Chrome-Extension#6424]
**Describe the bug**
I'm setting up a workspace specifically to test API responses from a global variable. I have created a global variable with the below command:
`pm.globals.set("host_agentinfo", pm.response.json());`

I then tried to do a simple compare and my test failed, with the below:
```
pm.test("/host/agentinfo - Response Verification", () => 
    pm.expect(pm.response.json()).to.deep.equal(a));
```

I expected this to fail as there are key::value pairs based on time that would not match. But I noticed that in the Test Results, it was not showing the correct order. I then printed the variable to the console and noticed that this response had been sorted by ASCII value.

What I was expecting:
```
{
    "ptagentversion": "1.9.1-59",
    "uptime": "201712 seconds ( 2 days 8 hours 1 minute 52 seconds )",
    "process_id": "763222",
    "ism_version": "3.4.0.ESXi6-1471",
    "system_uuid": "5cc7d023-9c53-aa74-43a2-246e966d9fb8",
    "host_epoch_time": "1557124038.809586 (secs.usecs)",
    "model": "VxRail P570",
    "name": "p570host2",
    "mfr": "",
    "domain": "",
    "servicetag": "",
    "os": "VMWare ESXi",
    "os_version": "6.5.0 build-10884925",
    "rest_endpoints": "https://100.80.152.211:8086",
    "locked_down_mode": "false",
    "TPM Present": "false",
    "MarvellLibraryVersion": "5.0.13.1099",
    "libstorelib.so": "07.07",
    "libstorelibir-3.so": "15.03-0",
    "idrac_pass_thru_ip": "169.254.0.1",
    "idrac_ethernet_ip": "100.80.101.84",
    "status": {
        "idraccache": "OK",
        "agent": "OK"
    }
}
```

What it sorted to:
```
Object:{}
MarvellLibraryVersion:"5.0.13.1099"
TPM Present:"false"
domain:""
host_epoch_time:"1557117857.869421 (secs.usecs)"
idrac_ethernet_ip:"100.80.101.84"
idrac_pass_thru_ip:"169.254.0.1"
ism_version:"3.4.0.ESXi6-1471"
libstorelib.so:"07.07"
libstorelibir-3.so:"15.03-0"
locked_down_mode:"false"
mfr:""
model:"VxRail P570"
name:"p570host2"
os:"VMWare ESXi"
os_version:"6.5.0 build-10884925"
process_id:"763222"
ptagentversion:"1.9.1-59"
rest_endpoints:"https://100.80.152.211:8086"
servicetag:""
status:{}
agent:"OK"
idraccache:"OK"
system_uuid:"5cc7d023-9c53-aa74-43a2-246e966d9fb8"
uptime:"195531 seconds ( 2 days 6 hours 18 minutes 51 seconds )"
```

**To Reproduce**
1. Create a global variable from an API response
2. Print the variable to console

**Expected behavior**
I searched to see if there was some default sort applied to variables, but couldn't find anything.

So I was expecting it to not sort, and keep my original order.

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version: 7.0.9
 - OS: Windows 10

**Comment by mccannt** [comment]
@thetreythomas Is this still an issue for you in the most recent version of our app? 
I just checked and it appears to be working as expected.
Please let us know.

**Comment by thetreythomas** [comment]
@mccannt I tried verifying this just now, and ran into issues with Global Variables. I created a bug report, #8992.

**Comment by mccannt** [comment]
@thetreythomas Can you try doing something like the following and let me know what you get back?

`curl --location --request GET 'https://postman-echo.com/get?foo1=bar1&foo2=bar2' \
--header 'Cookie: sails.sid=s%3Aooi3TEbsQhpn6Gw7xTMRx9mFdtc6RO6C.jo7tn7GxY3iYX%2ByeZGMhNLsU8O7HRztvqqG2sWcmIDA'`

Add the following to the `Test` tab:
`
pm.globals.set("global_variable", pm.response.json());
console.log(pm.globals.get("global_variable"))
`

Then compare what you get in the response body to what is output in the console.
I am seeing them being the same on my end.

**Comment by mccannt** [comment]
Closing this out for now as this specific issue appears to be resolved. 
If it is still an issue, please let us know with the results and we can investigate further.
