### ISSUE TITLE
When a team is disabled, release its domain

### ISSUE THREAD

**Issue by JP-from-Postman** [a85/POSTMan-Chrome-Extension#6425]
**Is your feature request related to a problem? Please describe.**
Right now, when a team is disabled its team domain is kept, and active teams are unable to use it.

**Describe the solution you'd like**
When a team is disabled, release the team domain it previously had.

**Describe alternatives you've considered**
None

**Additional context**

**Comment by Cazaimi** [comment]
@JP-from-Postman, If I understand correctly, there are more than one teams that are trying to register and then use, the same domain that was owned by a now disabled team? Could you clarify further?

**Comment by JP-from-Postman** [comment]
@Cazaimi In the original ticket this came from:

- User U1 creates team T1, which has domain D1
- U1 leaves T1, and it is disabled
- Domain D1 is still associated with team T1, even though it is disabled
- U1 creates new team T2, and tries to give it domain D1, but can't because it is still "in use" by team T1

**Comment by Cazaimi** [comment]
@JP-from-Postman , thanks for the clarification. Will look into it.

**Comment by Cazaimi** [comment]
@JP-from-Postman , we're working on solving this right now. @Raja-Simha , please add this to "Now" in the Project board?

**Comment by ranchanarajasekaran** [comment]
The issue has been fixed.
Please feel free to reopen the issue to report any feedback on the same.
