### ISSUE TITLE
Postman v7.0.9 freeze when I put large base64 text encode image to a API REST request.

### ISSUE THREAD

**Issue by mastro83** [a85/POSTMan-Chrome-Extension#6429]
In a POST request I want to insert 3MB of a Base64 encoded image text.

When I put the large text into Body key Postman begin to go at 100%CPU and freeze.

**Comment by shamasis** [comment]
We have released a fix for this (partially) in latest production and some more fixes are in Postman Canary and is scheduled to go out soon.

Tracking the issue as a part of: https://github.com/postmanlabs/postman-app-support/issues/4751
