### ISSUE TITLE
User unable to access monitors

### ISSUE THREAD

**Issue by labifrancis** [a85/POSTMan-Chrome-Extension#6432]
**Describe the bug**
A user gets this error when trying to access a monitor 
"Something went wrong 
There was an error while fetching your monitors. Please try again after some time."

**App information (please complete the following information):**
 - App Type Native App
 - Postman Version 7.09 for Windows

**Comment by ash007-postman** [comment]
Another user getting the same error while trying to create the Monitor.

**Comment by godfrzero** [comment]
We've pushed out a fix for users seeing errors while listing/accessing monitors.
