### ISSUE TITLE
Error: callback timed out on monitor with requests less than 5 min

### ISSUE THREAD

**Issue by t0nimas** [a85/POSTMan-Chrome-Extension#6433]
**Describe the bug**
I've problems with timeout request in the service of Monitor (with free account).
I have the monitor configured with: Request Timeout : 300000 ms
But when I see the log the request fails (for timeout) before 5 min (see image)
![image](https://user-images.githubusercontent.com/6563285/57309775-ef3d3400-70e8-11e9-801d-57075023c8b2.png)  
In fact, the timeout is triggered at 5 min since the first request, not since the current request.
I consider that this behaviour is a bug because I understand that the delay of 300000 ms is per request not per collection.  
I reproduced in the postman runner and the request no exceed never of 5 min:
![image](https://user-images.githubusercontent.com/6563285/57309987-522ecb00-70e9-11e9-8b34-28ff67c0fe30.png)  

**To Reproduce**
1. Go to Monitor (with a collection with various requests that together are grater than 300000 ms of response time)
2. Click on 'Run'
3. Wait 5 minutes and then refresh (check that the job is not still running)
4. Review console log of the monitor process (see image):
![image](https://user-images.githubusercontent.com/6563285/57309775-ef3d3400-70e8-11e9-801d-57075023c8b2.png)  

**Expected behavior**
No error timeout if there is no request greater than 300 seconds.

**Screenshots**
The screenshots are included in the description for better comprehension.

**App information (please complete the following information):**
 - Chrome Browser
 - Postman Version  7.0.9

**Comment by godfrzero** [comment]
There is a 5 minute execution time cap on all monitor runs. This is not configurable or adjustable, and is a platform limitation as of now. While the timeout and delay for and between each request is configurable, if your total monitor run time exceeds 5 minute, the monitor will be terminated at that point.

**Comment by godfrzero** [comment]
We're tracking a feature request to increase this limit, or to allow it to configurable in some manner here: https://github.com/postmanlabs/postman-app-support/issues/4834
