### ISSUE TITLE
Know when a published collection has been updated

### ISSUE THREAD

**Issue by loopDelicious** [a85/POSTMan-Chrome-Extension#6434]
Issue: From the New+ button, when I use a template or import a collection from the API Network, I am importing a static version of the collection. If the imported collection is updated at the origin, I am unaware of these changes.

**Documentation**: I can view the documentation with the View in Web button. I am viewing my own private version of the collection since I imported the template. Unless the publisher has included a link to their documentation in a description, I can't view their updated documentation or see that their documentation / collection has been updated. Consider allowing users to view the latest collection documentation.

**Notification**: If the publisher has updated their collection, I am unaware of this change. Consider showing users if the publisher has updated their collection, or notify them of the actual changes.

**Comment by gitThingsDone** [comment]
You can now watch a collection [while forking ](https://learning.postman.com/docs/collaborating-in-postman/version-control/#creating-a-fork)and stay notified about changes.
