### ISSUE TITLE
Name of a template is different upon importing

### ISSUE THREAD

**Issue by loopDelicious** [a85/POSTMan-Chrome-Extension#6435]
It's confusing when I import a collection that's called one thing (like `Express haiku`) and then the imported collection name is different (like `Postman Requests`). I assume this is happening because someone edited the name after publishing the template. 

Can / should we update the collection name when that happens, so that the name of the template is the same as the collection that is imported?

**Comment by sankalp0o** [comment]
@loopDelicious This happens because we allow users to name the template separately from the collection name. This allows users to have a name their collections however they want without affecting the template.

I agree that this might confuse consumers when they see a different name after they import the template.

**Comment by loopDelicious** [comment]
Another use case to consider @sankalp0o: importing an API Network collection and environment 

This happened to me during a demo. I saw the confirmation toast that the imports were successful. This message includes the name of the collection and environment. However, I missed reading them before they faded away. 

In this case, the name of both the coll and env were different from each other, and neither included the name of the company. Since I was looking for the name of the company, I couldn't find either entity. Out of 40+ people attending the meetup, only 1 person saw and remembered the name of 1 of the entity.

Perhaps something else (in addition to the toast) that points out what was recently imported? Like a highlight or unread designation in an email inbox.

**Comment by gitThingsDone** [comment]
This is fixed in the new [Public API network ](https://learning.postman.com/docs/getting-started/exploring-public-api-network/)
