### ISSUE TITLE
Feature Request: Webhooks

### ISSUE THREAD

**Issue by claireriley** [a85/POSTMan-Chrome-Extension#6436]
**Is your feature request related to a problem? Please describe.**
Currently Postman doesn't support configurable webhooks.

**Describe the solution you'd like**
An API that supports the automatic creation of webhook configurations.

**Additional context**
Filed by Postman
Relevant Documentation: [Webhooks Coming Soon](https://learning.getpostman.com/docs/postman/monitors/integrations_for_alerts/#webhooks-coming-soon)

**Comment by davidespihernandez** [comment]
We currently have a Public endpoint in the Public Postman API that allows the creation of a webhook. The documentation can be found here: https://www.postman.com/postman/workspace/postman-public-workspace/request/12959542-7552368b-7fc3-4f9b-a3e2-e229c3f6d299
