### ISSUE TITLE
Feature Request: Populate Request Information in Mock Server Response

### ISSUE THREAD

**Issue by claireriley** [a85/POSTMan-Chrome-Extension#6437]
**Is your feature request related to a problem? Please describe.**
Team would like to have request parameters (query and path segments) included in the response body to make their lives easier.

**Describe the solution you'd like**
It would be ideal if the mock response could contain some values passed from incoming requests (either query parameters or matched path segments). We'd like to return actual {resource-id} in the response body of requests to /resources/{resource-id}/items, for any {resource-id} passed as parameter. 

**Describe alternatives you've considered**
Currently we would need to mock each {resource-id} separately and manage all of them afterwards, and use only predefined set of resource-ids in development.

**Additional context**
Filed by Postman

**Comment by Dhembla** [comment]
As per our latest app release(v10.7), we have added support for template helpers that can be used while authoring examples and helps you access request data(headers, body, query params and path segments) in mock responses. You can read more about the feature [here](https://blog.postman.com/introducing-support-for-templating-in-postman-mock-servers/).
