### ISSUE TITLE
Template Description form copy overlaps 

### ISSUE THREAD

**Issue by loopDelicious** [a85/POSTMan-Chrome-Extension#6438]
In the web dashboard, when updating the Template Description and resizing the input box, the form description copy overlaps with the input copy.

<img width="941" alt="Screen Shot 2019-05-07 at 2 14 00 PM" src="https://user-images.githubusercontent.com/17693714/57340695-a24e6300-70d2-11e9-9fc6-e8bd9056a048.png">

**Comment by Raja-Simha** [comment]
We already fixed this. This will be out in the upcoming release

**Comment by ranchanarajasekaran** [comment]
This issue has been fixed. Closing this card. 
Please reply to this thread to report any feedback.
