### ISSUE TITLE
Ctrl-Shift-W should close all the tabs but not the application

### ISSUE THREAD

**Issue by trajano** [a85/POSTMan-Chrome-Extension#6439]
**Describe the bug**

Ctrl-Shift-W should close tabs not the entire app

**To Reproduce**

Ctrl-Shift-W

**Expected behavior**

All the open tabs are closed and untitled request is left

**Screenshots**

**App information (please complete the following information):**
 - App Type [e.g. Chrome App, Native App]
 - Postman Version [e.g. 6.0.1]
 - OS: [e.g. macOS High Sierra 10.13.2]

**Additional context**

**Comment by numaanashraf** [comment]
Thanks for your feedback @trajano. We are working on a way to let you customize these shortcuts and we are tracking this issue  at #2096. Closing this as a duplicate.
