### ISSUE TITLE
Ajax call within pre-request script doesn't complete before request is made.

### ISSUE THREAD

**Issue by duepayer** [a85/POSTMan-Chrome-Extension#644]
Pardon my ignorance here as I am far from an expert on ajax calls. I have a pre-request script that makes an ajax call to a local Flask app to generate and retrieve header information for each request. The problem is that the ajax call doesn't complete before the request is made. I figured this was due to its asynchronous nature so I set the ajax async value to false but the call fails to be executed altogether in that instance. Here's the ajax call I'm making to the Flask app:

```
$.ajax({
  url: base_url,
  dataType: "json",
  async: false,
  success: function(headers) {
    postman.setEnvironmentVariable("access_key", headers["X-Access-Key"]);
    postman.setEnvironmentVariable("auth_sig", headers["X-Auth-Sig"]);
    postman.setEnvironmentVariable("timestamp", headers["X-Timestamp"]);
    postman.setEnvironmentVariable("nonce", headers["X-Nonce"]);
    }
});
```

Is there anything that I can do to make this work?

**Comment by michaelajr** [comment]
This is a bummer. I need to get a token from our Authentication Server before my runs (OAuth2 client credentials flow - without login - just getting a token via a JWT POST . Any ideas? Thanks!

**Comment by abhijitkane** [comment]
You can add another request before this one, a POST request to your server. When the token is returned, use the test script to save it in an environment variable, and you'll be able to access it in the second request.

Relevant docs - https://www.getpostman.com/docs/jetpacks_sandbox, http://blog.getpostman.com/2014/01/27/extracting-data-from-responses-and-chaining-requests/

**Comment by michaelajr** [comment]
UUG. I as thinking in a vacuum. Yes. That makes perfect sense. Make the JWT token in the pre-request JS and save it to an env var. Then make a POST to the authn server. Then parse the response to get the authn token - and save it to an env var, and use it in subsequent requests. THANK YOU. (can't believe I did not see that.)

**Comment by michaelajr** [comment]
and of course that worked great. Took 2 mins. Thanks again.
