### ISSUE TITLE
Dark Mode on the Website / Portal

### ISSUE THREAD

**Issue by fvilches17** [a85/POSTMan-Chrome-Extension#6442]
**Is your feature request related to a problem? Please describe.**
No, no problem.

**Describe the solution you'd like**
Similar to how the Microsoft docs website let's you chose themes, it would be great if the Postman website and/or the dashboard (when logged in) could do the same.
E.g. https://docs.microsoft.com/en-us/dotnet/standard/

**Describe alternatives you've considered**
N/A

**Additional context**
![image](https://user-images.githubusercontent.com/13502806/57371569-28f46480-71e7-11e9-94d2-2d7c1042189b.png)

**Comment by ProBeta1** [comment]
This issue should be closed now .

**Comment by fvilches17** [comment]
Feature implemented? or feature no-go?

**Comment by ProBeta1** [comment]
![Screenshot from 2020-03-25 13-17-37](https://user-images.githubusercontent.com/33081197/77513485-22241e00-6e9b-11ea-95e1-9dfce8033e09.png)

**Comment by fvilches17** [comment]
Right, this is the desktop app. This feature request is meant for the web portal.

**Comment by chrisdeso** [comment]
@fvilches17 This is available on Postman on the web now too!

* go.postman.co
* `Settings > Themes`

<img width="1020" alt="Screen Shot 2021-09-24 at 4 36 23 PM" src="https://user-images.githubusercontent.com/4734306/134742326-dace5e53-0df3-42f5-af8f-b08150a81afc.png">

Closing this out but feel free to reopen if needed :)
