### ISSUE TITLE
Missing minimize/maximize buttons on Windows app

### ISSUE THREAD

**Issue by labifrancis** [a85/POSTMan-Chrome-Extension#6443]
**Describe the bug**
This user is unable to see the minimize/maximize buttons when the windows app is open but can see the same buttons on the [canary build.](https://www.getpostman.com/downloads/canary)

The main app not showing the minimize/maximize buttons
![Postman_Issue_Close_max_Min_Missing](https://user-images.githubusercontent.com/10200603/57378495-cd04ee00-719c-11e9-91f7-d0645a2cd707.png)

Canary build showing the buttons
![Postman_Issue_Close_max_Min (1)](https://user-images.githubusercontent.com/10200603/57378456-b65e9700-719c-11e9-91c9-2cfeee72632d.png)

**App information (please complete the following information):**
 - App Type [Native App]
 - Postman Version 7.09
 - Windwos

**Comment by numaanashraf** [comment]
@labifrancis This issue is not reproducible with the details currently in the issue. Please add reproduction steps.

**Comment by labifrancis** [comment]
Questions I asked: 

1. When you installed the app initially, did you ever see the minimize/maximize buttons?
2. Did you manually resize or use multiple monitors?
3. Is the window bar hidden outside the display area?
4. We'll like to know how you arrived at that state. Did you make any changes or did it start all of a sudden? 

User's response:

1. Actually I was using previously some older version of main app of Google postman. But as soon as I installed this build, i am not able to see minimise/maximize button.

2) i am not able to minimise/maximize by any means. So i used window+D to go desktop and open other applications.

3. It is difficult to answer  me to tell,
window bar is hidden or  outside the display area.I am not able to figure out this.

4. As soon as installed this build version, i am getting this issue from the beginning. 
User is on version 7.09

**Comment by lokendraujjwal** [comment]
[main.log](https://github.com/postmanlabs/postman-app-support/files/3186605/main.log)

[renderer-console.log](https://github.com/postmanlabs/postman-app-support/files/3186607/renderer-console.log)

[renderer-runner.log](https://github.com/postmanlabs/postman-app-support/files/3186609/renderer-runner.log)

**Comment by lokendraujjwal** [comment]
[pluginHost.log](https://github.com/postmanlabs/postman-app-support/files/3186617/pluginHost.log)

**Comment by lokendraujjwal** [comment]
[renderer-requester.log](https://github.com/postmanlabs/postman-app-support/files/3186622/renderer-requester.log)
[renderer-shared.log](https://github.com/postmanlabs/postman-app-support/files/3186624/renderer-shared.log)
[renderer-shell.log](https://github.com/postmanlabs/postman-app-support/files/3186625/renderer-shell.log)

**Comment by lokendraujjwal** [comment]
I have added all the file .. hope these may help to reproduce the same issue.

**Comment by mikkelkn** [comment]
FYI: I had the same problem. Turns out the app was just displayed in fullscreen :-)

**Comment by talln6e** [comment]
Press F11 to change to the usual window states, as recommended in https://github.com/postmanlabs/postman-app-support/issues/6811

**Comment by omoomoniyi** [comment]
> Press F11 to change to the usual window states, as recommended in #6811

I have been experiencing same issue as the topic stated. The F11 key did the magic

**Comment by kamalaknn** [comment]
@lokendraujjwal I'm closing this issue since it is similar to the fullscreen behavior confirmed by others here.

That said we are tracking a separate issue [here](https://github.com/postmanlabs/postman-app-support/issues/6811) to add feedback that the app is on fullscreen mode.

Do let us know if that does not solve your issue.

**Comment by aladyno** [comment]
I don't know why they removed it. Damn!

**Comment by vkaegis** [comment]
@davidjs2 Are you still seeing this issue? If so, which version of the desktop application are you on?

**Comment by aladyno** [comment]
I have been using F11 and it has displayed. Thanks.

**Comment by rfalanga** [comment]
I know this issue is closed, but I still have this problem.

**Comment by mirfaisal-sw** [comment]
F11 key really did wonder.
