### ISSUE TITLE
Ability to share an individual request and response

### ISSUE THREAD

**Issue by nagarjun** [a85/POSTMan-Chrome-Extension#6445]
**Is your feature request related to a problem? Please describe.**
I often consume APIs from other companies. A lot of times, these APIs don't work as per the developer's documentation and I end up having to contact the company's developer support channel by email / helpdesk. I am required to share my exact request and response with them so they can support me and resolve the problem.

Right now, I manually export the request using the "Code" generation feature in Postman and also export the response by copying it into a .json folder. I then share these request.txt and response.json files with the support team so they can help me. This is a very time-consuming and error-prone process.

**Describe the solution you'd like**
It would be great if there was a way to share individual requests in Postman. Imagine there was a "Share request" button. When you click it, Postman generates a unique URL (ideally with an expiry or an option to include a password to protect sensitive information like API keys). When the receiver opens the unique link, they can see the exact request I made and the response I received. Additionally, there could be a "Run in Postman" button in that page so the receiver can test the request themselves.

**Describe alternatives you've considered**
At the moment, I copy my request into a .txt file and my response into a .json file (if the response is in JSON format) and share them.

**Comment by anudeepmedicharla** [comment]
Hey @nagarjun, thank you for sharing your request! Will update the status here once we take this task up :)

**Comment by knoxxs** [comment]
Also, its really tough to copy response headers.

**Comment by sankalp0o** [comment]
Thanks @nagarjun! I get why this can be a problem. We have plans on allowing sharing of history requests in this year, I'll keep you updated when that gets picked up.

**Comment by akshay-kulkarni-03** [comment]
Hi @nagarjun , you can copy the link from the request tab in the left hand side bar! Let us know if you face any issue.
