### ISSUE TITLE
Postman does not correctly show API capturing status on crash

### ISSUE THREAD

**Issue by m3dbedb** [a85/POSTMan-Chrome-Extension#6446]
**Describe the bug**
When postman crashes on history deletion with turned on API capture option, on restart Api capture option is shown disabled and cpture butten marked "capture". Alltrough apis are captured and proxy is on. Then I press on "capture" button postman crashes again.

**To Reproduce**
1. Turn on api capture
2. Send some requests
3. Press delete todays history
4. Postman shows "something went wrong" message ![deletetodayhistory](https://user-images.githubusercontent.com/25632818/57598807-4b76dc80-755d-11e9-89c9-e1d3a4e08aad.jpg)
5. Close postman window
6. Restart postman
7. Make some request in browser and see it captured in postman history
8. Open Api capture window
9. See "cature" button (allthrogh it should be active already)
10. Hit the "capture" button
11. Postman crashes again

**Expected behavior**
API capture windows should show actual status of capture feature

**App information (please complete the following information):**
 - App Type: Native
 - Postman Version: 7.0.9
 - OS: windows 7 32 bit

**Comment by abhijitkane** [comment]
@m3dbedb Can you attach screenshots of the 'something went wrong' message in the app? Also, 
you can access the log files from `View > Developer > Show Logs in Explorer`. Could you send us these files at help@getpostman.com?

The crash during history deletion and capturing could be two separate issues.

**Comment by m3dbedb** [comment]
"Something went wrong" attached to original post, the issue is already created here https://github.com/postmanlabs/postman-app-support/issues/6378 .  I have send the logs to help@getpostman.com

**Comment by numaanashraf** [comment]
Crash on delete history group issue is fixed in Postman v7.1.0 (#6378). Keeping this issue open to track issue with capturing requests.

**Comment by m3dbedb** [comment]
History deletion does not breaks postman anymore. I would see if an issue with API capture appear when Postman crashes in other situation. Easiest way to crash Postman is to make mistake in cherio expression like console.log some complex object

**Comment by m3dbedb** [comment]
Today in Postman 7.2.0 for windws 7 32 bit I turn on API capture option, and it crashed when I have pushed API capture button again.

**Comment by DannyDainton** [comment]
Hey @m3dbedb 

Is this still an issue that you're facing in the latest native app version?

**Comment by mccannt** [comment]
Closing this. 
If it is still an issue on the latest version, please feel free to reopen
