### ISSUE TITLE
Update tab missing from app settings (6.7.1)

### ISSUE THREAD

**Issue by JP-from-Postman** [a85/POSTMan-Chrome-Extension#6449]
**Describe the bug**
User is being prompted to update to 7.x (team has already migrated to RBAC), but the Update tab is missing from the app settings:

<img width="497" alt="Screen Shot 2019-05-08 at 11 44 54 AM" src="https://user-images.githubusercontent.com/43283131/57399758-c4092200-7186-11e9-92e5-341eb905e089.png">

**To Reproduce**
Unknown

**Expected behavior**
Update tab is shown to allow upgrading to 7.x from 6.7.4.

**App information (please complete the following information):**
 - App Type: Native app
 - Postman Version: 6.7.1
 - OS: Linux

**Additional context**

**Comment by numaanashraf** [comment]
@JP-from-Postman This looks like a snap variant of Postman that doesn't support auto-updates controlled via Postman. We'll look into adding the Update tab back and make this differentiation clearer.

**Comment by gitriley** [comment]
For anyone else unable to update due to this issue, this solution worked for me (from the migration docs):

https://learning.getpostman.com/docs/postman_pro/managing_postman_pro/migrating_to_v7/

> 
> Note: If you are using Postman for Linux, and had installed the app via 'Ubuntu Software Center' or 'Snap Store', you will not be able to update the app via the steps explained above. Please use the following commands to update your app via the terminal:
> 
> sudo snap switch --channel=candidate postman
> sudo snap refresh postman

**Comment by Anakin-Hao** [comment]
I m also hitting this issue.

**Comment by Kira-PH** [comment]
The Snap package is still 6.7.1.

**Comment by arlemi** [comment]
Fixed in 7.10.0.
