### ISSUE TITLE
Can't signin to Windows app via SSO

### ISSUE THREAD

**Issue by Ramya-From-Postman** [a85/POSTMan-Chrome-Extension#6453]
**Describe the bug**
There is an issue while logging into the app via SSO. Wherein, the app freezes and keeps showing the spinning circles. However, When tried to sign-in using the postman credentials it works perfectly fine. 

**To Reproduce**
1. Click Sign in button top right in the app
2. Click Enterprise user Sign in link 
3. Enter team domain, click Continue 
4. Select an authentication method. I see IDP name and Sign in with Postman. 
5. choose to log in via IDP and enter an associated email address
It says "Taking you to your organization's sign-in page..." and then I see the Postman logo of three orbiting planets. It hangs there. 

**Expected behavior**
Should let sign-in to the app without any issues

**Screenshots**
![image](https://user-images.githubusercontent.com/40994626/57430635-ef0a7900-724d-11e9-8c8b-22486aded617.png)

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version [e.g. 7.9.0]
 - OS: Windows 10

**Comment by abhijitkane** [comment]
Additional context: Seeing a `[20300][1557376010006][auth][warn]["Authentication~Window Failed to load",{"errorCode":-105,"errorDescription":"ERR_NAME_NOT_RESOLVED","isTrusted":false,"isMainFrame":true}]
` in the auth window log.

@Ramya-From-Postman Is SSO working from the web dashboard?

**Comment by Ramya-From-Postman** [comment]
@abhijitkane Yes, log-in to Postman via SSO in the web browser works fine.

**Comment by mattfrear** [comment]
FYI I am the customer who raised the issue if you have any questions.

**Comment by Ramya-From-Postman** [comment]
@mattfrear May I know if the issue still persists? If yes, could you try reproducing the issue by connecting your computer/laptop to a different network(maybe hotspot) and let us know if that works?

**Comment by Ramya-From-Postman** [comment]
The customer wrote an email to help@getpostman.com confirming this issue is resolved. Hence, marking this thread as closed.
