### ISSUE TITLE
Creating multiple workspaces when using the app without being signed in

### ISSUE THREAD

**Issue by cyrielle-h** [a85/POSTMan-Chrome-Extension#6454]
**Is your feature request related to a problem? Please describe.**
I can't have my data synced due to policies that prevent it. 

**Describe the solution you'd like**
As I am using Postman for several apps, I would need to create multiple workspaces.

**Comment by preethammavin** [comment]
@cyrielle-h Workspace is one of cloud feature, though the use case seems valid enough it would be a mammoth task shift our technical architecture for this. This also opens up postman for handling users transition into a signed in state, and we would be opening our users to bugs which are hard to debug. Hence dont think we will be implementing this feature in near future.
