### ISSUE TITLE
Postman all requests fails with "Could not get any response" version 7.0.9

### ISSUE THREAD

**Issue by bartosz546** [a85/POSTMan-Chrome-Extension#6455]
Any request I'm trying to do fails with postman 7.0.9.
Everything works as intended, if I use postman chrome extension version.

I get following error (if trying to make get to google.com):

> 
> Could not get any response
> There was an error connecting to https://google.com.
> Why this might have happened:
> The server couldn't send a response:
> Ensure that the backend is working properly
> Self-signed SSL certificates are being blocked:
> Fix this by turning off 'SSL certificate verification' in Settings > General
> Proxy configured incorrectly
> Ensure that proxy is configured correctly in Settings > Proxy
> Request timeout:
> Change request timeout in Settings > General

I've tried do request to many popular addresses just to check it and each one fails.

**Comment by shamasis** [comment]
Can we do a quick check before we deep dive:
1. Can you check whether your proxy settings are correct?
2. Does making request via curl work?

**Comment by bartosz546** [comment]
1. Proxy settings are the default ones,, I tried to change them in a few ways and none help.
2. Request via curl works. 

My proxy settigns:
![Przechwytywanie](https://user-images.githubusercontent.com/26720699/57510573-77992000-7307-11e9-9bd6-83e9d25c395e.PNG)

**Comment by shamasis** [comment]
This is very odd and would be hard to debug. So, let’s deep dive…

1. The first thing we would check if there are any useful errors logged in Postman Console. These would escalate errors that we anticipated and logged 

2. Then we would look into Postman internal dev tools to check if any bug is causing this. 

Follow instructions here to open Postman Console https://learning.getpostman.com/docs/postman/sending_api_requests/debugging_and_logs/

You can open dev tools from the View menu. 

Send a GET request to `https://postman-echo.com/get` and if you spot anything relevant happening in any of the consoles, can you post the same here?

**Comment by bartosz546** [comment]
Error: tunneling socket could not be established, cause=getaddrinfo ENOTFOUND 8888 8888:80

![Przechwytywanie](https://user-images.githubusercontent.com/26720699/58480128-f55b8900-8159-11e9-8383-30e9e03a9b15.PNG)

**Comment by codenirvana** [comment]
@BartolomeoItaliano This looks like an issue with proxy, either system or global proxy is set in Postman or, following OS environment variables are set:
- `HTTP_PROXY` / `http_proxy`
- `HTTPS_PROXY` / `https_proxy`

**Comment by shamasis** [comment]
@BartolomeoItaliano - were you able to fix this?

**Comment by bartosz546** [comment]
Yes, that was strange problem. I reset my windows account and remove all user settings.

**Comment by deep1803** [comment]
I am getting error in postman :could not get any response 
Help me!
![7D3094F8-35D9-4175-82FA-87C837E64472](https://user-images.githubusercontent.com/52865528/61175345-4a991000-a5cb-11e9-86f2-d450056eebfc.jpeg)

**Comment by Kijacode** [comment]
issue ressolved here 👍 [stackoverflow answ](https://stackoverflow.com/questions/47806876/could-not-get-any-response-response-when-using-postman-with-subdomain)

**Comment by sitetester** [comment]
Also check that you are generating a valid HTTP response.
CURL cli is ignoring such requirements, but the backend link in browsers should tell if they are loading correctly.

**Comment by gouravkr** [comment]
> Yes, that was strange problem. I reset my windows account and remove all user settings.

I faced a similar issue. After hunting for hours and not finding a solution, I unistalled Postman from Windows, removed its old settings and configurations, then reinstalled and imported my collection. It started working. 
It was weird, never gave an error which could help me solve whatever issue was there, but reinstalling worked.

**Comment by cinnarr** [comment]
I am getting this error whenI am making GET request... can anyone please check and let me know what is going wrong here:
GET https://postman-echo.com/get
Error: ETIMEDOUT
Request Headers
User-Agent: PostmanRuntime/7.26.1
Accept: */*
Cache-Control: no-cache
Postman-Token: 957c34e6-d296-40b9-bf1a-08e250396c39
Host: postman-echo.com
Accept-Encoding: gzip, deflate, br

**Comment by Smssyed8** [comment]
This looks like some issue with postman, initially I was getting connection issue, then updated postman , now can see this issue in console. requesting postman to fix it, after switching to insomnia it worked for me, M kind of attached to postman with its features and ui.

**Comment by Smssyed8** [comment]
POST https://localhost:5000/users/add
Error: write EPROTO 1742741496:error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER:../../third_party/boringssl/src/ssl/tls_record.cc:242:
Request Headers
Content-Type: application/json
User-Agent: PostmanRuntime/7.26.5
Accept: */*
Cache-Control: no-cache
Postman-Token: ce1aacc3-fa70-4dfc-82c2-6a11a05c5bdc
Host: localhost:5000
Accept-Encoding: gzip, deflate, br
Connection: keep-alive

**Comment by AlexeyPlodenko** [comment]
The bug is still there with the latest version 8.
I have replaced the hostname in the URL with an SSLed one and after the restart both tabs were "lost".

![image](https://user-images.githubusercontent.com/32414715/110700994-e50e8400-81f0-11eb-950b-b53fef9dba5d.png)

@shamasis You might want to re-open the issue.
