### ISSUE TITLE
Docker instructions incorrect on learning.getpostman.com

### ISSUE THREAD

**Issue by jaredhanks** [a85/POSTMan-Chrome-Extension#6457]
**Describe the bug**
The Docker instructions for _4. Run Newman commands on the image._ is incorrect.  It's missing a `run` between `ubuntu` and `"https:"`

**To Reproduce**
1. Go to https://learning.getpostman.com/docs/postman/collection_runs/newman_with_docker/
2. Scroll down to '4. Run Newman commands on the image.'
3. Run `docker run -t postman/newman:ubuntu "https://www.getpostman.com/collections/8a0c9bc08f062d12dcda"`

**Expected behavior**
Correct Newman output, not invalid command error.

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version: 6.7.4
 - OS: macOS Mojave 10.14.4

**Additional context**
This is the error when running it:
> $ docker run -t postman/newman:ubuntu https://www.getpostman.com/collections/8a0c9bc08f062d12dcda 
error: invalid command `https://www.getpostman.com/collections/8a0c9bc08f062d12dcda`
Usage: newman [options] [command]
Options:
  -v, --version               output the version number
  -h, --help                  output usage information
Commands:
  run [options] <collection>  URL or path to a Postman Collection.
To get available options for a command:
  newman [command] -h

**Comment by codenirvana** [comment]
@jaredhanks Thanks for pointing this out. We'll fix the documentation as soon as possible.

The following command will work:
```
docker run -t postman/newman:ubuntu run https://www.getpostman.com/collections/8a0c9bc08f062d12dcda
```

Find the updated docs here: https://github.com/postmanlabs/newman/tree/develop/docker/#using-the-docker-image

**Comment by codenirvana** [comment]
Updated doc with the correct Newman command.
