### ISSUE TITLE
support response to body attribute like insomina

### ISSUE THREAD

**Issue by parasuram-tanguturu** [a85/POSTMan-Chrome-Extension#6459]
please check added images.

[
![post man r1](https://user-images.githubusercontent.com/22343548/57505088-a10c7880-7314-11e9-9e9c-cb224eda73e8.PNG)
![post man r2](https://user-images.githubusercontent.com/22343548/57505090-a10c7880-7314-11e9-88c1-4d3ce697da52.PNG)

]

**Comment by shamasis** [comment]
What does this feature do? From a quick look it seems that it uses a part of the response and allows to use the same as variable in next request. Am I seeing this right? If not, then help me understand it and also elaborate on what you’re using this for. 

If my interpretation is correct, then the same can be done on Postman by setting a variable in test script and using the same as part of next request. Here’s a blog post (albeit an old one) that elaborates on this - https://blog.getpostman.com/2014/01/27/extracting-data-from-responses-and-chaining-requests/
