### ISSUE TITLE
Collection response not syncing in cases where response body is large (greater than 10Mb)

### ISSUE THREAD

**Issue by Raj-postman** [a85/POSTMan-Chrome-Extension#6463]
**Describe the bug**
The data from the native app isn't synced to the Web Dashboard, it works fine when the application is restarted for a brief time. Also, the recent activity from the dashboard no longer displays the latest changes. The activity feed displays older made changes and recent activity changes are deleted.

**To Reproduce**
1. Create a new Collection/ Request
2. Go to Web Dashboard
3. Click on Activity Tab
The Collection/ Request isn't synced, the activity tab doesn't reflect recent changes.

**Expected behavior**
The data should sync between the application and the Web Dashboard. Activity Tab should display recently made changes.

**App information:**
 - App Type - Native App
 - Postman Version -  v7.0.9
 - OS: macOS

**Additional context**
Earlier there was a message stating that Postman is unable to sync, but the collections synced sporadically between application and Web Dashboard. Currently, there is no error message.

**Comment by jackson-david** [comment]
This issue is based off of my Postman ticket. Please let me know if there is any additional information I can provide to help.

**Comment by abhijitkane** [comment]
@numaanashraf Logs etc. have been attached to the linked JIRA ticket.

**Comment by numaanashraf** [comment]
@jackson-david Thanks for reporting this. Is the sync icon on the top right always showing the `blue-rotating` icon when this happens?

**Comment by sujayvenaik** [comment]
Hey @jackson-david 
We found performance issues while syncing large responses that you mentioned earlier that they were around 15Mb and 20Mb. We generally recommend not to have examples above 5Mb.

Will update this thread with further progress.

**Comment by jackson-david** [comment]
@numaanashraf Almost always it's the blue rotating icon. Once in a while it's just grayed out, but not often.

**Comment by jackson-david** [comment]
@sujayvenaik Yeah, it may be coincidence, but after removing the large items to reduce the collections' sizes, it seems to be working again. But, I had those collections in my account for at least a couple months and never had a problem with the sync. I am also using the canary build, so maybe there's something in it that was changed and helped correct this issue?

**Comment by sujayvenaik** [comment]
Hey @jackson-david, you will not face syncing issues till the time you don't interact with these examples. When some changes are made to these and are tried to sync then you might face issues.

Canary and Stable build interact with the same environment so I guess that will not cause any issues.
Thanks for helping to debug. Like I said I'll keep this thread updated with further progress.

**Comment by sujayvenaik** [comment]
Hey,
We have put out a fix for this in the latest app release v7.6.0. We do not allow syncing of large example body i.e. body which is greater than 5Mb and hence block that from both saving and syncing.

**Comment by sankalp0o** [comment]
@jackson-david We've put a hard limit on syncing of examples with a large request body(5MB) so that the rest of the syncing experience isn't affected. 

Please check it on the latest app and let us know if this fixes your issues. I'm closing this issue but feel free to reopen it if there's any feedback or the fix doesn't work for you.
