### ISSUE TITLE
Why do I automatically update when I turn off automatic updates?

### ISSUE THREAD

**Issue by CLannadZSY** [a85/POSTMan-Chrome-Extension#6465]
"Automatically download major updates"
The status of this tag is "Disabled"

**Comment by numaanashraf** [comment]
This option would only disable auto-updates for major breaking versions. At the moment, there is no way to turn off improvements, bug fixes and security patches.

**Comment by CLannadZSY** [comment]
Ok, thank you for your reply.

Numaan Ashraf <notifications@github.com> 于2019年5月11日周六 上午12:02写道：

**Comment by pearlberry** [comment]
@numaanashraf I have auto-updates disabled and keep getting updated from 7.2.x to 7.3.0. You're saying that 7.3.0 isn't a major breaking version?

**Comment by Golgo1** [comment]
Agreed,  Last month I was updated to 7.3.3, when the latest release was only 7.2.2
It broke MANY features.
It has just auto updated again, breaking key features I need for work.  (Submitting bugs separately for those)
I am going to waste at least a hour getting re-set to a previous version, hopefully for long enough to perform my work tasks

**Comment by CLannadZSY** [comment]
> Agreed, Last month I was updated to 7.3.3, when the latest release was only 7.2.2
> It broke MANY features.
> It has just auto updated again, breaking key features I need for work. (Submitting bugs separately for those)
> I am going to waste at least a hour getting re-set to a previous version, hopefully for long enough to perform my work tasks

yes, Why are they not turning off automatic updates?
I do not understand
But why provide the ability to turn off automatic updates? This is contradictory.
Can't fix this bug?
I believe they can fix this bug easily

**Comment by millejano** [comment]
Same here, can't understand why disabling updates is so difficult.

**Comment by rilex037** [comment]
i guess nobody cares

**Comment by acmarsnik** [comment]
This has to be changed, I just got automatically updated to 7.21.1 which then was completely broken.  Even after uninstalling and reinstalling/restarting computer I just got a message "Can't open Postman app" 

Now what, my solution is just to leave Postman open and never shut down my computer so I don't get updated to the broken new version again?

**Comment by rilex037** [comment]
@acmarsnik  or just block their ip inside host file

**Comment by glnemeth** [comment]
So there is still no solution for this? Postman 7.26 freezes for me if I output larger debug data. I downloaded a version 7.23 which works perfectly, but it auto updates itself to the buggy 7.26 version instantly. So next time I have to get 7.23 again to use it until I restart it.
This is very annoying.

**Comment by CLannadZSY** [comment]
> So there is still no solution for this? Postman 7.26 freezes for me if I output larger debug data. I downloaded a version 7.23 which works perfectly, but it auto updates itself to the buggy 7.26 version instantly. So next time I have to get 7.23 again to use it until I restart it.
> This is very annoying.

Yes, it will still be updated automatically.
Maybe you can open a new issue and hope to attract the attention of the development team to fix it

**Comment by arlemi** [comment]
We're already tracking this as a feature request here https://github.com/postmanlabs/postman-app-support/issues/6999

**Comment by stefanluchian** [comment]
@ Postman guys: Why are you insisting to force us to update, even on minor updates?
This is no way to win new users! And you might lose existing ones.
We simply don't want automatically minor updates! Is it so hard to understand it?
We are not some mobile-app-freaks who just want to have the latest thing.
Just let us decide if and when we want minor updates!
This is really annoying!
Stop forcing us to update! Should be our decision!
