### ISSUE TITLE
Checking for update in version 6.7.4 says you're up to date  

### ISSUE THREAD

**Issue by cyrielle-h** [a85/POSTMan-Chrome-Extension#6466]
**Describe the bug**
When checking for updates from native app version 6.5.4, it says you're up to date. 

![image (1)](https://user-images.githubusercontent.com/39134277/57522919-635f1e00-731b-11e9-826f-717dbfc58fad.png)

**Comment by numaanashraf** [comment]
@cyrielle-h If the user is part of a team (free/paid) and they have not migrated the team to Postman 7.0, they wouldn't receive Postman 7.0 via auto-updates.

**Comment by numaanashraf** [comment]
We'll take this as an improvement to communicate this better during the update check.
