### ISSUE TITLE
variable value in pm.sendRequest

### ISSUE THREAD

**Issue by richatyagi8** [a85/POSTMan-Chrome-Extension#6467]
If I am giving the variable in pm.sendRequest, The prescript doesn't work. It is not recognizing the baseURL variable

pm.sendRequest("{{baseUrI}}/xyz/3.0/sites", function (err, response) {
    console.log(response.json());
});

**Comment by codenirvana** [comment]
@richatyagi8 That's the expected behavior.

To access resolved variable value in scripts use `pm.variables.get()`.
Refer: https://learning.getpostman.com/docs/postman/environments_and_globals/variables/#accessing-variables-through-scripts

So, for your usecase:
```javascript
pm.sendRequest(pm.variables.get("baseUrI") + "/xyz/3.0/sites", function (err, response) {
    console.log(response.json());
});
```
