### ISSUE TITLE
postman stops responding on deleting history

### ISSUE THREAD

**Issue by bhavayAnand9** [a85/POSTMan-Chrome-Extension#6470]
**Describe the bug**

On deleting history of a particular date the postman encounters an error with outputs this error screen.

Nothing happens after that screen, the only way is to close the application and restart it again.

But on restarting the history gets deleted successfully. 

**To Reproduce**
1. Go to history section
2. Click on delete icon on right side of date section
3. See error

![Screenshot 2019-05-10 at 19 31 01](https://user-images.githubusercontent.com/34943807/57533228-df2c8b00-735a-11e9-9377-91107e485688.png)

**Expected behavior**
Just that date block history should be deleted from history section.

**Screenshots**
attached above.

**App information (please complete the following information):**
 - App Type [Postman]
 - Postman Version [Version 7.0.9 (7.0.9)]
 - OS: [macOS Mojave v 10.14.2]

**Comment by bhavayAnand9** [comment]
I'm just curious, Is postman a native mac app or is it built using electron ?

**Comment by cyrielle-h** [comment]
Duplicate of [6378](https://github.com/postmanlabs/postman-app-support/issues/6378)

**Comment by bhavayAnand9** [comment]
Oh sorry, I didn't searched the issue before and just directly reported it, my bad. I'll close it now.
