### ISSUE TITLE
How can I turn off the temporary header added in code generation 

### ISSUE THREAD

**Issue by liguoqinjim** [a85/POSTMan-Chrome-Extension#6472]
How can I turn off the temporary header?
I just when to test the api response when the cookie is not sent in the request.But in the new version,I can't do this because of the temporary header.

And the function also has bug.

To reproduce the bug:
1.Make a new request without any header
2.Send the request
3.After response,the temporary header will be shown.(eg. Host)
4.And now,and header manually,just add a Host
5.Use the `Code` function.The Host header has both tow values.
![image](https://user-images.githubusercontent.com/2113954/57540351-1d3ba600-737f-11e9-89b6-f969b0350eb9.png)

And send the request another time,after response,the host value in the temporary header will disappear.

At last,want postman has a setting to turn off the temporary header.

**Comment by shamasis** [comment]
@liguoqinjim I’ve tweaked your issue title to prevent confusion.

**Comment by shreys7** [comment]
@liguoqinjim  In Postman 7.2.1, we've introduced bug-fixes, support for two new languages (JS-Fetch and Powershell), and the ability to configure certain aspects of the generated snippet with the 'Experimental Codegen Mode' flag enabled in Postman's global settings. You can switch off the include temporary headers option in configurations of the snippet generated.

The options can be seen with the 'Experimental Codegen mode' flag set.
![image](https://user-images.githubusercontent.com/20665864/59862375-48fb7400-93a0-11e9-90b6-d5a878a7067b.png)
![image](https://user-images.githubusercontent.com/20665864/59862386-4c8efb00-93a0-11e9-8d3e-3eb113ec509f.png)
