### ISSUE TITLE
Changes in merged fork don't reflect in destination Collection

### ISSUE THREAD

**Issue by JP-from-Postman** [a85/POSTMan-Chrome-Extension#6475]
**Describe the bug**
User report:
```
GIVEN a developer with an Postman Pro account
AND the developer uses Postman App for Mac Version 7.0.9 (7.0.9)
AND there are two workspace A and B
AND in workspace A is a collection C
AND the developer forked the collection C to the workspace B (collection D)
AND the developer created a new request E in a folder of collection D
WHEN the developer merges the changes to collection C in workspace A

actual behavior:
THEN the developer *can't * see the new request E in collection C in the Postman App
AND the developer can see the new request E in collection C in the web version (via View in web)

expected behavior:
THEN the developer can see the new request E in collection C in the Postman App
AND the developer can see the new request E in collection C in the web version (via View in web)

Workaround so far: Logout and login again.
```

**To Reproduce**
See above

**Expected behavior**
Changes are merged, and reflect in the destination collection without logout + login.

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version: 7.0.9
 - OS: macOS

**Comment by cyrielle-hada** [comment]
@preethammavin @JP-from-Postman Initial report shows that sign-out/sign back in fixed the issue.  The changes appear to be merged successfully.

**Comment by zgirod** [comment]
Just adding that this happens on a windows machine as well as macOS.

**Comment by JP-from-Postman** [comment]
@preethammavin Note that the workaround requires logging in + logging out each time to see merged changes reflected (definitely not ideal)

**Comment by cyrielle-hada** [comment]
@ankitjaggi - it looks like the issue persists.

Here are the steps to reproduce 
1 - Create a fork on an original collection A, 
2 - Click `merge changes` (without making any changes). 
3 - This takes the user to the web interface 
4 - It shows that there are changes to merge, and changes to pull. 
![Screen_Shot_2019-07-16_at_3_58_51_PM](https://user-images.githubusercontent.com/47351631/61362948-0338ab00-a87b-11e9-9931-8b5a90df1252.png)
5 - Click `Pull Changes`
6 - It says "Nothing to merge. This fork has no changes from the destination collection"
<img width="1667" alt="Screen Shot 2019-07-17 at 09 57 25" src="https://user-images.githubusercontent.com/47351631/61363009-22373d00-a87b-11e9-8602-95ff3d6a5585.png">

Result: multiple duplicates of some folders have made their way into the original collection but these duplicates appear differently depending on whether the user is looking at the Postman App or the documentation in the web UI.

It seems like the web UI and the app are using 2 different sources of truth. 
- When a new fork is created > the merge uses the data from the app
- When changes from the fork are tried to be merged > it uses the data from the web UI.

The user tried
- Logging out and back into both the web UI > same result 
- Viewing the web UI in incognito mode > same result

**Comment by travisnguyen20** [comment]
Is there any update? Still experience the isssue

**Comment by cyrielle-hada** [comment]
@travisnguyen20 initial reports indicate that the issue has been fixed. 

Would it be possible [to file a support ticket](https://go.pstmn.io/help-center-signin-newrequest) and send your logs as well as a screen record that shows how to replicate the behavior?

**Comment by travisnguyen20** [comment]
> @travisnguyen20 initial reports indicate that the issue has been fixed.
> 
> Would it be possible [to file a support ticket](https://go.pstmn.io/help-center-signin-newrequest) and send your logs as well as a screen record that shows how to replicate the behavior?

Created support ticket with ID #55146

**Comment by DannyDainton** [comment]
Hey @cyrielle-hada,

Has the original issue been resolved now? I see that @travisnguyen20 had raised a support request but not sure if it's the same issue or a different one.

**Comment by cyrielle-hada** [comment]
@DannyDainton I wasn't able to reproduce the issue reported by @travisnguyen20 (it is the same one reported in this thread). 

If this happens, the workaround, for now, is to duplicate the master collection and then create a fork from this duplicated collection to another workspace (not ideal).

I would keep this open a bit longer, wait, and see if we get any other reports.

**Comment by DannyDainton** [comment]
Awesome, thanks for taking a look @cyrielle-hada 🏆

**Comment by DannyDainton** [comment]
Closing this one as there have been no further users reporting the issue.

**Comment by jamie6bly** [comment]
Seeing this today, signing out and back in again rectified but not ideal. Whats the latest?

steps to recreate
- fork collection to a private workspace
- make PR, approve and merge (this was super laggy)
- navigate to source location
Expected = source location updated with merged changes
Actual = source location **NOT updated** with merged changes


Using mac (M2)
