### ISSUE TITLE
How to skip Json array in Json object in request body??

### ISSUE THREAD

**Issue by pramodgulla** [a85/POSTMan-Chrome-Extension#6476]
Hi Team,

I am running one request with 3 iterations using json data file and these 3 iterations have different API_KEY that means 3 users.So when ever I want to run first iteration , i would like to skip the model1 in the Json request body.Similarly, when the iteration becomes 2 , i would like to skip the model2 while running the POSTMAN collection runner.

I know the code has to be written in the "Pre-request-scripts". Any help??

i have request body like this : 
{
	"app_id": "{{app_id}}",
	"models": {
		"model1": [{
			"project_id": {{project_id}},
			"version": 1
		}],
		"model2": [{
			"project_id": {{project_id}},
			"version": 1
		}],
		"model3": [{
			"project_id": {{project_id}},
			"version": 1
		}]
	},
	"tag": "Hello"
}

**Comment by sivcan** [comment]
If I understood you correctly,
When it's the first iteration then only model2 and model3 should be sent as request body.
When it's the second iteration then only model1 and model3 should be sent as request body and so on..

Well, you can get the current iteration count using the `pm.info.iteration` API which will exactly give you the current iteration count.
Also, if you need the total count i.e. what is the total number of iterations that will be ran then `pm.info.iterationCount` will help you with that.

Now, you can actually build the complete request body in the Pre-request script itself.
For an example on how to do that, [this thread on StackOverflow will help you](https://stackoverflow.com/questions/55649051/how-do-i-block-undefined-variables-from-being-sent-on-postman/55651273#55651273)

Also, using the `pm.info.iteration` you can write the logic to skip the models accordingly and build your request body then as the answer on StackOverflow tells you, you can store that as on `requestBody` variable and use it up.

Something like this would help you: 
```javascript
const TOTAL_MODELS = 3;

let currentIteration = pm.info.iteration;
    requestBody = {
        "app_id": "{{app_id}}",
        "tag": "Hello"
    },
    models = [];

_.times(TOTAL_MODELS, (index) => {
    if (index === currentIteration) {
        return;
    }

    let modelName = `model${index + 1}`;

    models.push({
        [modelName]: [{
                "project_id": "{{project_id}}",
                "version": 1
        }]
    });
});

requestBody.models = models;

pm.variables.set('requestBody', JSON.stringify(requestBody));
```

Result:
![image](https://user-images.githubusercontent.com/12631777/57573570-69521d80-7447-11e9-9e04-7949f7e1317f.png)

**Comment by numaanashraf** [comment]
We recommend reaching out to the wider Postman Community (https://community.getpostman.com/) for help with this issue.

Issue Guidelines: https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues

**Comment by pramodgulla** [comment]
@sivcan  Thanks for the Answer. But, I am not expecting the Json Body that it is returning.
PFA document. Thanks!!
![collage](https://user-images.githubusercontent.com/39747459/57648298-1a190380-7593-11e9-9bc1-e2d8a692cd18.png)
