### ISSUE TITLE
Cannot recover the collections

### ISSUE THREAD

**Issue by mkamrani** [a85/POSTMan-Chrome-Extension#6477]
**Describe the bug**
I was using Postman on an account on my machine until I had to move to a new account on that machine (AD stuff, I have the user folders but that account doesn't exist anymore).
As suggested I have copied the folder Postman from AppData/Raoming to the same location for the new account (I've installed same version of Postman on the new account) but now the Postman just shows the loading sign and none of the menus seem to work.
Also I tested and the problem is just because of using the old Postman folder, otherwise it works.

Please help as I'm losing a big collection.

**Expected behavior**
Postman should load up my old collections.

**App information (please complete the following information):**
 - App Type [Native App]
 - Postman Version [6.1.4]
 - OS: [Windows 10]
.

**Comment by numaanashraf** [comment]
@mkamrani Data folders contain account specific information and copying data folders between account might not always work. Could you please write to us at help@getpostman.com? We'll try our best to help you recover your data from the previous account files.
