### ISSUE TITLE
Getting message as Error and   and responseDetail as nothing

### ISSUE THREAD

**Issue by rajib18mca** [a85/POSTMan-Chrome-Extension#6480]
Hi,

please help as per subject line, getting response as below
![image](https://user-images.githubusercontent.com/50546152/57581929-605f5b80-74dc-11e9-8ccc-7d80fa2a52cf.png)

Thanks

@numaanashraf please help

**Comment by numaanashraf** [comment]
This seems to be related to your specific API and I'm afraid we don't provide support with issues for your specific APIs here. 

We recommend reaching out to the wider Postman Community (https://community.getpostman.com/) for help with this issue.

Issue Guidelines: https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues
