### ISSUE TITLE
Environment variables dont change correctly or not at all

### ISSUE THREAD

**Issue by NadavOs90** [a85/POSTMan-Chrome-Extension#6481]
i changed the current value of the variable called port to 9669 it changed another variable as well and when i hover over the port i get an unrelated value

![image](https://user-images.githubusercontent.com/37407298/57584266-c5698000-74e1-11e9-99f0-a3d2dd664883.png)

**Comment by numaanashraf** [comment]
@NadavOs90 Thanks for reporting this. We are tracking a similar issue that is caused when there are multiple variables with the same key in the environment. Would it be possible to verify whether you have multiple `port` keys in the environment?

**Comment by NadavOs90** [comment]
i checked and no

**Comment by barnarock** [comment]
I have the same issue. The variables does not change its value and they have unique names.

**Comment by numaanashraf** [comment]
@NadavOs90 @barnarock We've pushed a fix for this in Postman v7.1.0. Let us know if you are still facing this issue after updating.
