### ISSUE TITLE
[Windows Desktop] Postman setting to not install minor updates

### ISSUE THREAD

**Issue by Kapcash** [a85/POSTMan-Chrome-Extension#6483]
I want to use v7.0.7 of the desktop app on Windows 10. Each time I close the app, it automatically updates to v7.0.9.
The settings "Update" tab says that Postman will automatically updates for minor updates, so this is the expected behavior.

Nevertheless, I'd like to be able to disable this feature, as well as for major updates, because I'm facing a blocking issue for me (@see #6341).

I expect something like this setting:
![postman_disable_minor_updates](https://user-images.githubusercontent.com/10612835/57620855-454b2500-758a-11e9-84de-93295463f830.jpg)

**Comment by Kapcash** [comment]
I've found a workaround for this.
Even if the next version is downloaded in background while running postman, the current (not latest) version folder still exists. I just run the .exe from this old version folder (_%LOCALAPPDATA%/Postman/{version}/Postman.exe_) instead of the shortcut created by postman (which is surely edited when updating to point to the new version folder).

**Comment by numaanashraf** [comment]
There are currently no plans to disable auto-update for regular/minor releases at the moment. Only major version updates can be disabled.
