### ISSUE TITLE
File-picker on Postman for Mac does not respect os-wide dark mode setting

### ISSUE THREAD

**Issue by arpitbatra123** [a85/POSTMan-Chrome-Extension#6485]
While trying to select a file while sending a `form-data POST` request, the file-picker that opens up on the mac app does not open in dark mode:
![image](https://user-images.githubusercontent.com/21967563/57624124-e946c780-75ae-11e9-9f2a-568736b58001.png)

While other apps such as chrome respect the dark-mode setting and open the file-picker in dark mode:
![image](https://user-images.githubusercontent.com/21967563/57624237-27dc8200-75af-11e9-93b9-6e30149ba596.png)

In my opinion, It would be less distracting if the file-picker respected the dark-mode setting.

**Comment by harryi3t** [comment]
@arpitbatra123 

We've pushed an update on our early access canary channel that should resolve this issue. Do try it out and let us know
You can get the canary app from https://www.getpostman.com/downloads/canary

**Comment by arpitbatra123** [comment]
@harryi3t File Picker on Postman Canary is respecting the systemwide dark mode theme setting now. Thanks for the fix!

**Comment by twitharshil** [comment]
Duplicate of https://github.com/postmanlabs/postman-app-support/issues/5302
