### ISSUE TITLE
random generated values in variable

### ISSUE THREAD

**Issue by richatyagi8** [a85/POSTMan-Chrome-Extension#6486]
I have a randomly generated variable which i want to use in all the test cases without having to write this for every test case . Is there a way ? Right now if I am calling name128 in some other testcase , the value remains the same and doesn't change.

let r128 = Math.random().toString(36).substring(2, 15) + Math.random().toString(36).substring(2, 15);
console.log("random128", r128);
pm.environment.set("name128", r128);

**Comment by abhijitkane** [comment]
@richatyagi8 There are two approaches you can use here:
1. If your requests are in a collection, you can use the [collection-level pre-request script](https://learning.getpostman.com/docs/postman/scripts/pre_request_scripts/). This will be executed before each request in the collection, and give you a different value for `name128` in each request.
2. If not in a collection, you can save a piece of code as a JS function in your environment, and use `eval(pm.environment.get('randomCodeVariable`);` in each request.

**Comment by richatyagi8** [comment]
@abhijitkane -thanks for your response. Could you please redirect me to a documentation on using JS function in the environment for postman?
