### ISSUE TITLE
Postman Console Crashes on expanding a log with pm.sendRequest

### ISSUE THREAD

**Issue by Raj-postman** [a85/POSTMan-Chrome-Extension#6488]
**Describe the bug**
When you make pm.sendRequest in your test scripts, expanding the Postman console throws an error.

**To Reproduce**
1. Go to Pre-Request scripts
2. Make use of _pm.sendRequest_
3. Click on Send
4. Click on Postman console, and expand the previously sent request
5. Displays the error: _Something went wrong_

**Expected behavior**
To check Postman console for responses

**Screenshots**
![PostmanConsole](https://user-images.githubusercontent.com/47771757/57644273-638c4180-75d9-11e9-9b1c-78eab0af6b09.png)

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version: v7.09
 - OS: macOS

**Additional context**
Regarding the issue: https://github.com/postmanlabs/postman-app-support/issues/6306#issuecomment-491778283

**Comment by harryi3t** [comment]
Closing this in favor of https://github.com/postmanlabs/postman-app-support/issues/6306
Please subscribe to the original issue for further updates
