### ISSUE TITLE
Environment Quicklook: Changes made to session variables don't always persist

### ISSUE THREAD

**Issue by chrisdeso** [a85/POSTMan-Chrome-Extension#6489]
**Describe the bug**
When using the environment quicklook to edit session variables, the changes don't always persist.

**To Reproduce**
1. Open the Postman app
2. Click on the environment quicklook
3. Navigate to a session variable and make edits
4. Hit enter || Click outside of the text field
5. See that changes don't persist.

**Expected behavior**
Changes made to session variables using the environment quicklook 

**Screenshots**
![image](https://user-images.githubusercontent.com/4734306/57649094-f05cde00-758c-11e9-977d-f8fc44acabab.png)

**App information (please complete the following information):**
 - App Type: Native
 - Postman Version: 7.0.9+
 - OS: Mac OS Mojave 14.14.4

**Additional context**
The behavior isn't always reproducible.

[Filed by Postman]

**Comment by harryi3t** [comment]
Thanks for opening the issue. We are tracking this here https://github.com/postmanlabs/postman-app-support/issues/6362 
Kindly subscribe to that issue for the updates.
