### ISSUE TITLE
Environment quicklook: Edits to one session variable propagates to others

### ISSUE THREAD

**Issue by chrisdeso** [a85/POSTMan-Chrome-Extension#6490]
**Describe the bug**
Edits made to session variables using the environment quicklook propagates to other variables

**To Reproduce**

1. Open the Postman app
2. Click on the environment quicklook
3. Navigate to a session variable and make edits
4. See changes propagate to other variables

**Expected behavior**
Edits should only be made to selected environment variables

**Screenshots**
[GIF](https://i.imgur.com/2kHpz3Y.gifv)

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version: 7.0.9+
 - OS: macOS

**Additional context**

**Comment by harryi3t** [comment]
Thanks for opening the issue. We are tracking this here https://github.com/postmanlabs/postman-app-support/issues/6362 
Kindly subscribe to that issue for the updates.
