### ISSUE TITLE
Environment Quicklook: Can't unfocus sometimes

### ISSUE THREAD

**Issue by chrisdeso** [a85/POSTMan-Chrome-Extension#6491]
**Describe the bug**
Sometimes it isn't possible to unfocus from the session variable's text field

**To Reproduce**

1. Open the Postman app
2. Click on the environment quicklook
3. Navigate to a session variable and make edits
4. See that clicking out of the text field doesn't reset focus

**Expected behavior**
Clicking outside of the session variable's text field while using quicklook should reset focus

**Screenshots**
[GIF of behavior](https://i.imgur.com/7YudVsA.gifv)

**App information (please complete the following information):**
 - App Type: Native app
 - Postman Version: 7.0.9+
 - OS: macOS

**Additional context**
[Filed by Postman] – not always reproducible

**Comment by harryi3t** [comment]
Thanks for opening the issue. We are tracking this here https://github.com/postmanlabs/postman-app-support/issues/6362 
Kindly subscribe to that issue for the updates.
