### ISSUE TITLE
Could not open Postman --- not resolved by clearing cache

### ISSUE THREAD

**Issue by JP-from-Postman** [a85/POSTMan-Chrome-Extension#6492]
**Describe the bug**
User encountered **Could not open Postman** error after installing v7.x and trying to start app. Clearing local cache and removing all existing Postman installs has not resolved the issue.

**To Reproduce**
Unknown

**Expected behavior**
App is able to start successfully

**Screenshots**

**App information (please complete the following information):**
 - App Type: Native app
 - Postman Version: 7.0.9
 - OS: Windows

**Additional context**

**Comment by groggi** [comment]
Might be related to #6296?

**Comment by numaanashraf** [comment]
Closing this issue as it was verified that the local cache was cleared properly.
