### ISSUE TITLE
Right-to-left scripts in the Body field aren't selected correctly

### ISSUE THREAD

**Issue by allanrodriguez** [a85/POSTMan-Chrome-Extension#6493]
**Description**
When portions of text in a right-to-left script (e.g. Arabic or Hebrew) in the Body field are selected, text from the opposite side is returned instead. Copying and pasting the text somewhere else shows that the intended selected text is not returned. Right-clicking on the selected text in the Body field will show a `Find: <text>` where <text> is a set of characters from the opposite side of the string.

**To reproduce**
1. Issue a GET request to any API that returns text in a right-to-left script (e.g. Arabic or Hebrew).
2. Select the first five or so characters on the left side of the text.
3. Right-click on the selected text.
4. Notice that the last five or so characters show up instead in the `Find: <selected text>` option.

**Expected behavior**
The selected text should be returned.

**Screenshots**
![postman](https://user-images.githubusercontent.com/28719059/57681157-05b12700-75e4-11e9-9960-d83ad096fb31.png)

**App information:**
 - App Type: Native App
 - Postman Version: 7.0.9
 - OS: Windows 10

**Comment by pankajk07** [comment]
@allanrodriguez , this has been fixed as part of `v7.26`. Please update the app and try it out.
