### ISSUE TITLE
Workspace delete modal doesn't show thumbnail in collection runner 

### ISSUE THREAD

**Issue by sivcan** [a85/POSTMan-Chrome-Extension#6494]
**Describe the bug**
The workspace delete modal which tells the user that the active workspace has been deleted and that the user has been switched to another workspace doesn't show the thumbnail icon.
Whereas, when the same modal shows up in the requester, it does show the thumbnail icon.

**To Reproduce**
1. Open collection runner and switch to some personal / team workspace (do not choose a default workspace because it cannot be deleted)
2. Go to the requester window and delete this workspace which was active in the runner
3. The workspace delete modal shows up

**Expected behavior**
The thumbnail is correctly rendered

**Screenshots**
![image](https://user-images.githubusercontent.com/12631777/57682243-fa471580-764e-11e9-8f32-c795f94b8c4c.png)

**App information (please complete the following information):**
 - App Type - Native App
 - Postman Version - v7.0.9
 - OS: macOS Mojave

**Additional context**
Filed by Postman

**Comment by numaanashraf** [comment]
Fixed in Postman v7.2.0
