### ISSUE TITLE
Sync is not working in v6.7.1

### ISSUE THREAD

**Issue by abi2810** [a85/POSTMan-Chrome-Extension#6495]
Postman v6.7.1 in ubuntu, sync is not working. When I open postman it automatically rotating but still, it is not synced. This is kept on rotating, but nothing happened. What is the issue with syncing, people from my team is waiting for my documentation I couldn't sync my collections.

**Comment by sujayvenaik** [comment]
@abi2810 Do you have an update in your app?
Can you check if your team is migrated to the latest v7 version of the app? If yes, you will also have to move to that version. 
Refer: https://blog.getpostman.com/2019/03/11/get-postmans-latest-features-by-migrating-to-version-7-0/

**Comment by abi2810** [comment]
Yes, it is showing like this
![Screenshot from 2019-05-14 15-44-08](https://user-images.githubusercontent.com/28435288/57690442-4a2dd880-765f-11e9-9187-f3103b377562.png)
And I'm trying to update but I couldn't. As the update instructed I went to the settings page and I don't see any update there. What should I do now?

**Comment by abi2810** [comment]
This is my settings page,
![Screenshot from 2019-05-14 15-48-22](https://user-images.githubusercontent.com/28435288/57690663-c45e5d00-765f-11e9-858d-854a8ecb38b5.png)

**Comment by sujayvenaik** [comment]
Are you using a snap version of the app?
If yes, can you refer https://github.com/postmanlabs/postman-app-support/issues/6045#issuecomment-471177118

**Comment by abi2810** [comment]
Oh my goodness, this works. Now the collection are in sync. Thank you so much for helping me out @sujayvenaik

**Comment by sujayvenaik** [comment]
Cool, I'll go ahead and close this issue.
