### ISSUE TITLE
Navigating directly to custom domain redirects to path

### ISSUE THREAD

**Issue by godfrzero** [a85/POSTMan-Chrome-Extension#6496]
**Describe the bug**
When navigating directly to a custom domain, the user is redirected to a new location including the path.

**To Reproduce**
1. Navigate directly to a custom domain, without the version parameter
2. Get redirected to the same domain with path & version parameter attached

**Expected behavior**
Redirection should be to the custom domain without a path, but with the version parameter.

**Comment by godfrzero** [comment]
A fix for this in on the way to production, and should be out within the next 24 hours. The fix will remove the extraneous path which gets attached. The version query parameter will remain in place, but removing that as well when there is only one version published or when navigating to the latest is up for discussion.

**Comment by dhineshwiz** [comment]
Fix for removing extraneous path in the custom domains is deployed
