### ISSUE TITLE
Pretty Printing doesn't always seem to work

### ISSUE THREAD

**Issue by kamranayub** [a85/POSTMan-Chrome-Extension#65]
I've been working with the GiantBomb API and I noticed several instances where pretty printing either outright doesn't work or is broken:
## 1. Pretty Print doesn't work

With this JSON result, I am not getting pretty printing:

```
{"number_of_page_results": 1, "status_code": 1, "error": "OK", "results": {"image": {"icon_url": "http://media.giantbomb.com/uploads/8/87209/2141562-box_ac3_icon.png", "medium_url": "http://media.giantbomb.com/uploads/8/87209/2141562-box_ac3_small.png", "tiny_url": "http://media.giantbomb.com/uploads/8/87209/2141562-box_ac3_tiny.png", "small_url": "http://media.giantbomb.com/uploads/8/87209/2141562-box_ac3_small.png", "thumb_url": "http://media.giantbomb.com/uploads/8/87209/2141562-box_ac3_thumb.png", "screen_url": "http://media.giantbomb.com/uploads/8/87209/2141562-box_ac3_screen.png", "super_url": "http://media.giantbomb.com/uploads/8/87209/2141562-box_ac3_super.png"}}, "limit": 1, "offset": 0, "number_of_total_results": 1}
```
## 2. Pretty Print breaks

Pretty Print does not seem to handle the not-unusual case of escaped quotes, the following breaks pretty printing:

```
{"number_of_page_results": 1, "status_code": 1, "error": "OK", "results": {"description": "<h2>Overview</h2><p>Assassin's Creed III, the first <a href=\"/assassins-creed/62-38/\">Assassin's Creed</a> title to not feature either <a href=\"/altair-ibn-laahad/94-48/\">Altair Ibn la-Ahad</a> ..."}, "limit": 1, "offset": 0, "number_of_total_results": 1}
```

I trimmed the HTML to showcase the issue.

I noticed you're using an external library for pretty printing. I am not sure if they need to fix this or if you would patch it in.

https://github.com/vkiryukhin/vkBeautify

**Comment by barajasss** [comment]
> I am seeing the Content-Type as `text/javascript` rather than the typical application/json. Maybe that's why?

thank you bro... i also had the same issue and forgot to put
header("Content-Type: application/json; charset=UTF-8");
