### ISSUE TITLE
Postman API: file upload for Import external API validating against Collection schema

### ISSUE THREAD

**Issue by JP-from-Postman** [a85/POSTMan-Chrome-Extension#6500]
**Describe the bug**
When attempting to import a OpenAPI .yaml file using [POST Import external API specification](https://docs.api.getpostman.com/view/631643/JsLs/?version=latest#09886971-e1e2-4a62-8f59-f7abfd79ff5e), the response returns status 400 with the error message:
```
{
    "error": {
        "name": "malformedRequestError",
        "message": "The request body does not conform to v2.1.0 format. Check https://schema.getpostman.com for more information."
    }
}
```

**To Reproduce**
1. POST an openapi .yaml file to https://api.getpostman.com/import/openapi
2. See response error mention: `The request body does not conform to v2.1.0 format`

**Expected behavior**
- File is uploaded successfully
- Validation and error messages pertain to specification used (in this case openapi)

**Screenshots**
<img width="1258" alt="Screen Shot 2019-05-14 at 4 17 58 PM" src="https://user-images.githubusercontent.com/43283131/57738545-d262ac80-7664-11e9-8534-c26b428684e6.png">

**App information (please complete the following information):**
 - App Type: Native app
 - Postman Version: 7.0.9
 - OS: macOS 10.13.6

**Comment by abhijitkane** [comment]
Happening due to a bug in the SDK that generates malformed collections. Pushing a workaround in the OpenAPI importer - https://github.com/postmanlabs/openapi-to-postman/pull/63

**Comment by JP-from-Postman** [comment]
@abhijitkane Did this get released? Just received another user report that appears to be the same issue importing via API.

**Comment by DannyDainton** [comment]
@abhijitkane / @JP-from-Postman 

Can this be closed out now?

**Comment by abhijitkane** [comment]
Should be. @JP-from-Postman Feel free to reopen is this is seen/reported again :)
