### ISSUE TITLE
More than one items selected in Environment dropdown

### ISSUE THREAD

**Issue by grgakshay** [a85/POSTMan-Chrome-Extension#6501]
**Describe the bug**
More than one item is selected in Environment dropdown

**To Reproduce**
1. Add a few environments in Postman
2. Click on environment dropdown button in top-right
3. Select one environment
4. Again click on the environment dropdown button
5. Hover on some items in the dropdown list
6. Observe three items being selected

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/50197377/57750712-e8be4600-7700-11e9-87d6-18c0e279cfef.png)

**App information (please complete the following information):**
 - Native App
 - Postman v7.0.9
 - macOS High Sierra 10.13.2

**Comment by Mechanicalkeyboard** [comment]
Unable to reproduce this in the current version of the app (7.31.1). Please feel free to reopen if this is still an issue.

**Comment by shubhbhargav** [comment]
@grgakshay I am unable to reproduce it on the latest version (9.12.2). Do let us know if you are still facing the issue.

**Comment by shubhbhargav** [comment]
Closing it off due to inactivity.
