### ISSUE TITLE
My data display area is not fully displayed, using Google postman

### ISSUE THREAD

**Issue by xzyk** [a85/POSTMan-Chrome-Extension#6502]
![image](https://user-images.githubusercontent.com/29298677/57753805-a2c4aa80-771f-11e9-85db-136b775607d2.png)
As shown in the figure, I asked for an interface. The data returned by the interface can not be fully displayed here. Is that what I set up? This problem has been bothering me for a long time.

It uses the latest plug-ins from the Google App Store.

Please help me. Thank you.

**Comment by numaanashraf** [comment]
@xzyk The preview section has its own scrolling - could you check whether you can scroll within the preview? It seems like the preview scroll is auto-hiding.

**Comment by xzyk** [comment]
@numaanashraf Thank you very much for your answer!
Where can I see if auto-hide is turned off?
I can scroll here, but I can only scroll a little bit and the data is not fully displayed.
Drawings:
![image](https://user-images.githubusercontent.com/29298677/57898470-c73d9580-788b-11e9-8c44-ba276d55989e.png)
![image](https://user-images.githubusercontent.com/29298677/57898504-f6ec9d80-788b-11e9-803f-25994007570a.png)
Can't scroll down

**Comment by numaanashraf** [comment]
@xzyk The scroll you had highlighted in the previous screenshot is the scroll-bar for the entire tab. The preview section has its own scrolling. Could you try scrolling via your trackpad/mouse-wheel _within_ the preview section? The auto-hide behavior is decided by your OS settings, and at the moment, there is no way to toggle this on/off within the Postman app.

**Comment by xzyk** [comment]
@numaanashraf 
![image](https://user-images.githubusercontent.com/29298677/57900050-f48d4200-7891-11e9-85bd-bb93299ce881.png)
![image](https://user-images.githubusercontent.com/29298677/57900066-0373f480-7892-11e9-85b6-0c266656fdea.png)
Thank you for your answer!
as the picture shows:
My Pretty page does have its own scrollbar, but my Preview page doesn't have its own scrollbar. What is the reason for this?
I used to have it. But I don't know what to do, no more!
Oh my God

**Comment by numaanashraf** [comment]
@xzyk Could you send us a screenshot of the "About" tab in settings?

**Comment by xzyk** [comment]
@numaanashraf 
Hello, as shown
![image](https://user-images.githubusercontent.com/29298677/57901467-e8a47e80-7897-11e9-91e6-abe53883d9fa.png)

**Comment by xzyk** [comment]
> @xzyk您能否在设置中向我们发送“关于”标签的屏幕截图？

https://github.com/postmanlabs/postman-app-support/issues/6502#issuecomment-493304260

**Comment by xzyk** [comment]
I accidentally closed it.

**Comment by numaanashraf** [comment]
@xzyk Looks like you are using Postman for Chrome, which has been deprecated since 2017 - https://blog.getpostman.com/2017/11/01/goodbye-postman-chrome-app/

Could you try whether you are facing similar issues with our Desktop Apps? https://www.getpostman.com/downloads/

**Comment by xzyk** [comment]
@numaanashraf 
 Yes, I have been using this!
Because Interceptor feature is supported only in our Postman Chrome Apps and is not available in Postman Desktop Apps at the moment。
[https://learning.getpostman.com/docs/postman/sending_api_requests/interceptor_extension/](url)

Desktop Apps 
This problem does not occur in Desktop Apps, the data display is correct and complete.

**Comment by a85** [comment]
The Interceptor is available on the native apps now. Closing this issue now as the Chrome apps are deprecated.
