### ISSUE TITLE
Wrong icon sizes in API actions bar

### ISSUE THREAD

**Issue by sivcan** [a85/POSTMan-Chrome-Extension#6504]
**Describe the bug**
The alignment seems to be off for the actions for APIs. The issue is that the Reports and Comments icon are actually 16 x 16px, whereas the refresh icon is that of 12 x 12px.
Which would make a user feel that the alignment is off but it's, in fact, the issue with the icon size.

**Expected behavior**
All icons are of 16 x 16px.

**Screenshots**
![image (3)](https://user-images.githubusercontent.com/12631777/57758538-8754a200-7715-11e9-98d8-8690cf5c3d6a.png)
This shows how the icons feel misaligned with the baseline because of the size issue.

**App information (please complete the following information):**
 - App Type - Native App
 - Postman Version - v7.1.0
 - OS: macOS Mojave

**Additional context**
Filed by Postman

**Comment by sankalp0o** [comment]
@sivcan this was fixed some time back! I'm closing this issue but please let us know if the icons still look off.
