### ISSUE TITLE
Unable to login to Postman app

### ISSUE THREAD

**Issue by Raj-postman** [a85/POSTMan-Chrome-Extension#6506]
**Describe the bug**
Unable to sign in to the application, throws an error

**To Reproduce**
1. Try logging into the application
2. See error: Something went wrong

**Expected behavior**
To be able to sign into the application

**Screenshots**
![Something went wrong](https://user-images.githubusercontent.com/47771757/57669623-5139f400-7629-11e9-9302-1b32a68d7a5c.png)

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version: v6.7
 - OS: macOS

**Additional context**
Also saw similar issue reported here: https://github.com/postmanlabs/postman-app-support/issues/1763#issuecomment-492053355

**Comment by alysonYan** [comment]
App Type: Native App
Postman Version: v7.9.0
OS: windows10
my account cannot login

**Comment by elssar** [comment]
@alysonYan can you give us a bit more detail on what exactly is happening? If you're seeing the same error from the screenshot above, then can you once check if there is some proxy or firewall that might be blocking Postman from connecting to its auth servers?
