### ISSUE TITLE
Empty response

### ISSUE THREAD

**Issue by akrz** [a85/POSTMan-Chrome-Extension#6507]
**Describe the bug**
When I send the request sometimes I get an empty response. It seems that it happens when the response is somewhat large (it's happening with 700~ lines, json format)

**To Reproduce**
1. Build the request
2. Click on 'Send'
3. Scroll down to the response body
4. See empty body

**Expected behavior**
Json Body is displayed

**Screenshots**
![image](https://user-images.githubusercontent.com/1325627/57776227-4b114980-76f5-11e9-98d9-d6429ce5f525.png)

If I click on 'Code', copy the generated code and run it on a terminal, I get the body content:
![image](https://user-images.githubusercontent.com/1325627/57776339-93c90280-76f5-11e9-934d-a99d874cd2dd.png)
![image](https://user-images.githubusercontent.com/1325627/57776440-e2769c80-76f5-11e9-9bf1-ced549d36c3c.png)

Or even another http client:
![image](https://user-images.githubusercontent.com/1325627/57776498-00dc9800-76f6-11e9-8ed4-7cae8abcfb06.png)

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version v7.1.0
 - OS: Ubuntu 18.04

**Additional context**
This started happening a couple of versions ago, today I updated to v7.1.0 but the issue is still present. From my observations, this happens when the response has several lines (json format), like greater than 500 or so.

**Comment by saswatds** [comment]
Hi @akrz we have pushed some performance updates to the latest Postman app version 7.2.1. Can you test if your issue still persists in the latest version?

**Comment by akrz** [comment]
@saswatds Seems like the update fixed the issue. Thanks!
