### ISSUE TITLE
Unable to activate account - verification link throws error 404

### ISSUE THREAD

**Issue by cyrielle-hada** [a85/POSTMan-Chrome-Extension#6508]
**Describe the bug**
Clicking the account activation link throws an error 404 on the browser and redirects to the URL https://www.getpostman.com/validate-email/. 

![image001](https://user-images.githubusercontent.com/47351631/57777807-03091b80-7723-11e9-9ab7-4d90cc0b7480.png)

**Additional context**

- The user never received the activation email although we can see on our end that it has successfully been sent. 
- The DevTools console doesn't show any error (see internally). 
- Tied to generate manually an invite link twice
- The user can reproduce the error in a different browser/incognito window

**Comment by abhijitkane** [comment]
@cyrielle-hada This will be fixed this week.
