### ISSUE TITLE
PATCH request label misspelled

### ISSUE THREAD

**Issue by IvanDyankovYoti** [a85/POSTMan-Chrome-Extension#6509]
**Describe the bug**
Patch HTTP method is misspelled in the user interface.

**To Reproduce**
0. Using the native app for MAC
1. Create a new PATCH request
2. Add it to a collection
3. Observe the side panel of the app where your methods are shown that PATCH is missing the `H`

**Expected behavior**
PATCH is spelled correctly

**Screenshots**
![image](https://user-images.githubusercontent.com/50199560/57783946-f5559500-7726-11e9-99cb-744b26a79962.png)

**App information (please complete the following information):**
 - Native App
 - Postman Version 7.1.0 (7.1.0)
 - OS: macOS Mojave 10.14.4

**Comment by vkaegis** [comment]
@IvanDyankovYoti Thanks for writing in. This was unfortunately an intended side effect of us introducing custom methods, which meant we had to truncate methods over a particular character limit (4). We can probably increase this limit to 5, but this doesn't ensure correct representations for all methods. Will keep you updated.

**Comment by vikiCoder** [comment]
This issue is fixed in the [latest Postman App](https://www.getpostman.com/downloads/) release (v7.2.1).
