### ISSUE TITLE
Getting blank page while postman starting

### ISSUE THREAD

**Issue by varazerotolerance** [a85/POSTMan-Chrome-Extension#6510]
**Describe the bug**
Getting blank page while postman starting

**To Reproduce**
1. download postman for 64 windows 8.1
2. start postman
3.getting blank page

**Expected behavior**
Postman should work properly

**Screenshots**
https://www.screencast.com/t/RA47rDld6

**App information (please complete the following information):**
 - Postman Version Postman-win64-7.1.0
 - OS: 64bit windows 8.1

**Additional context**
Thank you guys in advance. But i can't start to work with it.

**Comment by sujayvenaik** [comment]
@varazerotolerance 
Can you follow the steps mentioned in this[ comment](https://github.com/postmanlabs/postman-app-support/issues/4594#issuecomment-391601621) and check whether it helps to get it fixed.

**Comment by varazerotolerance** [comment]
@sujayvenaik thank you! now working fine for me.
