### ISSUE TITLE
Postman pro environment values not sharing.

### ISSUE THREAD

**Issue by iFreeon** [a85/POSTMan-Chrome-Extension#6512]
My team all has pro accounts and we're on a shared workspace.  The problem is when I add new key/value pair to a shared environment me team members don't get the changes.

**To Reproduce**
1. Preconditions (have a team on pro, have a shared workspace, have a shared postman environment.
2. From Windows postman prod - add a new key/initial/current to the a shared postman environment I own.
3. Team members cannot see the new value even after a refresh
4. Even when I look on the website... I don't see it "value" save consistently.  I suspect the problem is with bad sync logic around initial and current values.
5. Also to confuse things more the website only shows key/value.  No clue if that is the current or initial value.

**Expected behavior**
I expect postman environment changes to be shared with my team. 

**Screenshots**

**App information (please complete the following information):**
 - Native App
 - Postman Version 6.7.4
 - OS: Windows 10

**Additional context**
The idea of having initial and current values (per key) is confusing and just because of the training issues it creates **reduces** the value of having postman pro.

Ideally I would love just one value because that would remove training issues as well.

**Comment by sujayvenaik** [comment]
Hey @iFreeon Only the initial values in case of environments are synced.
For other thing when the data isn't syncing: Do you have an update available in your app?
Can you check if your team is migrated to the latest v7 version of the app? If yes, you will also have to move to that version.
Refer: https://blog.getpostman.com/2019/03/11/get-postmans-latest-features-by-migrating-to-version-7-0/

**Comment by iFreeon** [comment]
The subscription has not been upgraded to version 7.  If you think that is the issue, I'll get the admin to upgrade it and see if that helps.

Also you mentioned only the initial values are synced.  I'm not sure that makes a lot of sense.  What is the purpose of current values?

**Comment by harryi3t** [comment]
@iFreeon As @sujayvenaik has mentioned, the current values are not synced with our servers. 
This allows people to keep sensitive information in these variables.

For more details please check our docs
https://learning.getpostman.com/docs/postman/environments_and_globals/sessions
