### ISSUE TITLE
Pre request script at folder level isnt working but, prescript inside a request works

### ISSUE THREAD

**Issue by richatyagi8** [a85/POSTMan-Chrome-Extension#6514]
I am running the exact same script inside the folder and inside of a request , but I am getting undefined on the folder one and the request inside request works fine. 

**Request inside request** 

pm.sendRequest({
    url: pm.variables.get("baseUrI") + "/sample/3.0/contacts",
    method: 'GET',
    header: {
        'Accept': 'application/json',
        'Content-Type': 'application/json'
      },
       
}, function (err, rescontacts1) {
    const datagetcontacts =rescontacts1.json();
    pm.globals.set("xyz2",datagetcontacts.contacts[0].uid);
  
});

**Inside folder:** 

pm.sendRequest({
    url: pm.variables.get("baseUrI") + "/sample/3.0/contacts",
    method: 'GET',
    header: {
        'Accept': 'application/json',
        'Content-Type': 'application/json'
      },
       
}, function (err, rescontacts2) {
    const datagetcontacts1 =rescontacts2.json();
    pm.globals.set("xyz3",datagetcontacts.contacts[0].uid);
  
});

console output shows - ReferenceError | xyz3 is not defined

**Comment by codenirvana** [comment]
@richatyagi8 Looks like you are trying to access variable `xyz3` in another script (test maybe), you might have to assign the variable using `var xyz3 = pm.globals.get('xyz3');`. I don't see any issue with this script.

Also, we recommend reaching out to the wider Postman Community (https://community.getpostman.com/) for help with issues like these.

Issue Guidelines: https://github.com/postmanlabs/postman-app-support#guidelines-for-reporting-issues
