### ISSUE TITLE
Web Dashboard: Unable to publish Collection, 'Something went wrong'

### ISSUE THREAD

**Issue by JP-from-Postman** [a85/POSTMan-Chrome-Extension#6515]
[Reported by Postman Support, on behalf of original user]

**Describe the bug**
When clicking Publish on the private documentation view for any Collection, the web dashboard shows the loading spinner, but never loads and the Collection is not published. Browser console shows a status 403 error, "...something went wrong", but this is never displayed on the actual page.

User has already attempted this with different browsers, clearing cache + cookies, and signing out + signing back in to the dashboard, with no change.

**To Reproduce**
Unknown (see internal notes)

**Expected behavior**
- Collection is published
- Error message is displayed on the browser page, instead of only in the console.

**Screenshots**
![dashboard](https://user-images.githubusercontent.com/43283131/57807875-eebf2180-7716-11e9-9307-466ae0987e45.png)

<img width="652" alt="Screen Shot 2019-05-15 at 1 36 21 PM" src="https://user-images.githubusercontent.com/43283131/57808325-f4693700-7717-11e9-81f5-465314d74186.png">

**App information (please complete the following information):**
 - App Type: Native app
 - Postman Version: 6.5.3
 - OS: Ubuntu

**Additional context**
See JIRA

**Comment by eugene0928** [comment]
only "something went wrong" warning comes when try to view documentation before publish it. What is should be done?
