### ISSUE TITLE
Template got deleted after receiving an error while importing  it.

### ISSUE THREAD

**Issue by prashantagarwal** [a85/POSTMan-Chrome-Extension#6518]
**Describe the bug**
Template got deleted after receiving an error while importing it.e
API errors out with the following error message "This template has been deleted because public documentation no longer exists." and after this, the template got deleted.

Both collection and published documentation exist.

**To Reproduce**
1. Choose a template to import
2. Try to import the template, it will error out.
3. Now this template also gets removed from the template list.

**Expected behavior**
Template should not be deleted

**Screenshots**

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version: 7.1.0

**Comment by bhargavkaranam** [comment]
This issue has been fixed.
