### ISSUE TITLE
Incorrect user count 

### ISSUE THREAD

**Issue by Ramya-From-Postman** [a85/POSTMan-Chrome-Extension#6519]
**Describe the bug**
I have a postman team with the team size equal to 5 and had 3 active users. However, upon deleting a user from the team it shows (4/5) users instead of (2/5) users on the team page. 

**Note**: Refreshing the page fixes the problem.

**To Reproduce**
1. Go to http://go.postman.co/team/ 
2. Delete a user
3. See the incorrect count

**Expected behavior**
The system should show an accurate user count when addition/deletion has happened.

**Screenshots**
![image](https://user-images.githubusercontent.com/40994626/57845378-855f1180-77ef-11e9-96d5-663b30d16fd6.png)

I**App information (please complete the following information):**
 - App Type: Native App]
 - Postman Version: 7.0.9
 - OS: macOS High Sierra 10.14

**Comment by kartikjain26** [comment]
@Ramya-From-Postman  fix is under review
