### ISSUE TITLE
Native app - Black screen on Windows after updating to v7.1.0

### ISSUE THREAD

**Issue by cyrielle-hada** [a85/POSTMan-Chrome-Extension#6521]
**Describe the bug**
Black screen of the content frame after updating the app to v7.1.0 Postman on Windows 10.
The menu bar is still available and responsive.
The view and controls in the main view are blocked from interacting. 

**View of the app when launched** 
![before](https://user-images.githubusercontent.com/47351631/57861487-fbb34200-77f6-11e9-85cb-913608be8497.png)

**15-30 seconds after the launch has completed** 
![after](https://user-images.githubusercontent.com/47351631/57861594-2604ff80-77f7-11e9-9a67-8535026fb29f.png)

**To Reproduce**
1. Update the app to v7.1.0
2. Open the app 
3. Wait 15-30 seconds 
4. See black screen

**App information**
 - App Type - Native App
 - Postman Version 7.1.0
 - OS: Windows 10 Win 10 Enterprise v1709
- i7-8650U CPU 
- 32 GB RAM 

**Additional context**

- Disable GPU didn't work. 
- Increasing memory usage even in idle of about 150-350 MB per second and at about 2.6 - 3.1 GB the view blacks out and the usage is down to around 430-450 MB.

**Comment by lemaireo** [comment]
I solved the probleme by deleting the AppData\Roaming\Postman repository

**Comment by m3dbedb** [comment]
Same issue under windows 7 32 bit with Postman 7.1.1

**Comment by cyrielle-hada** [comment]
The problem here was fixed by removing the local data. 
To remove the Postman directory
Open `File Explorer` and paste in the Path field
`C:\Users\<user>\AppData\Roaming\Postman`​ and
`​C:\Users\<user>\AppData\Local\Postman`

**Comment by labifrancis** [comment]
A user is still experiencing this issue on version 7.8. 

After working with the app for a while, the user gets the black screen.

**Comment by HBR86** [comment]
I had this issue on windows with postman version 7.10.0 and the workaround suggested by @cyrielle-hada works fine, thanks.

**Comment by m3dbedb** [comment]
the issue is present in postman 7.11.0

**Comment by labifrancis** [comment]
Another user fixed this issue by opening the app with a different compatibility. 
![image](https://user-images.githubusercontent.com/10200603/71361621-d4460400-2593-11ea-8759-cbaac45c2b36.png)

**Comment by Julian1Le9Cuero** [comment]
Trying a different compatibility worked for me, thank you @labifrancis!

**Comment by ghost** [comment]
Same problem as above - tried suggestion from @labifrancis - worked fine by telling Windows to make compatible with XP Service pack 3 and to run as Admin

**Comment by m3dbedb** [comment]
same issue under windows 7 32 bits and postman 7.18.1

**Comment by pigubaoza** [comment]
same issue under Ubuntu 16.04, Postman v7.22.1

**Comment by cyrielle-hada** [comment]
@m3dbedb @pigubaoza did the workaround suggested in this thread help?  
- [Removing the local data](https://github.com/postmanlabs/postman-app-support/issues/6521#issuecomment-494890917)
- [Opening the app with different compatibility](https://github.com/postmanlabs/postman-app-support/issues/6521#issuecomment-568481304)

**Comment by mccannt** [comment]
We have made some improvements in regards to performance and stability in recent months. Is this still an issue for anyone here on the latest version?

**Comment by mccannt** [comment]
Closing this issue for now. We are always making improvements to the application, please reach out if you are still experiencing this issue.
