### ISSUE TITLE
Settings - Working Directory information link is incorrect

### ISSUE THREAD

**Issue by DannyDainton** [a85/POSTMan-Chrome-Extension#6522]
**Describe the bug**

A new section was added to the app setting which displays the location of the working directory - This section has a link out to an external page on the Learning Center.

This link is currently going to the `Requests` section:
https://learning.getpostman.com/docs/postman/sending_api_requests/requests

There doesn't appear to be anything in this section that references the `Working Directory`.

**Steps To Reproduce**

1. Go to the **Settings** menu
2. Under the `General` Tab, select the _Learn more about the working directory_ link in the `Working Directory` section

A new browser window is opened at the link referenced in the bug description.

**Expected behavior**

The external link opens up a new browser window in the correct page/section of the Learning Center.

**Screenshots**

<img width="755" alt="Screenshot 2019-05-16 at 15 00 41" src="https://user-images.githubusercontent.com/17089546/57860279-86427400-77ec-11e9-92d6-becdfe50294c.png">

**App information**
 - App Type: Native App
 - Postman Version 7.1.0
 - OS: macOS Mojave 10.14.5

**Comment by a85** [comment]
The link should be updated to: https://learning.getpostman.com/docs/postman/launching_postman/settings/

**Comment by saswatds** [comment]
This has been fixed
