### ISSUE TITLE
Irrelevant collection search results after 7.1.0 native app update

### ISSUE THREAD

**Issue by filfreire** [a85/POSTMan-Chrome-Extension#6524]
**Describe the bug**
Search feature in postman app,  that is on top of "History/Collections" tab seems broken in terms of search results after `Version 7.1.0 (7.1.0)` update.

Previously when I started searching for a request name across collections - it filtered out the requests that strongly matched the search term I used. Now it's displaying completely unrelated requests.

**Screenshots**
<img width="333" alt="pm_search" src="https://user-images.githubusercontent.com/11976836/57872077-31622600-780b-11e9-856a-bf1b8d0e3d98.png">

**App information (please complete the following information):**
 - App Type `Native App`
 - Postman Version `7.1.0`
 - OS: `macOS High Sierra 10.13.6`

**Comment by filfreire** [comment]
Btw, similar behaviour seems to be happening also in latest canary version I downloaded - `7.1.1-canary02`

/cc @numaanashraf @abhijitkane @priyalviroja

**Comment by numaanashraf** [comment]
@filfreire We were able to reproduce this at our end and a fix for this is coming out in a patch release early next week. Thanks for reporting this.

**Comment by gopikrishna4595** [comment]
Checked in Windows Platform, issue is fixed in v7.1.1 .

**Comment by filfreire** [comment]
@numaanashraf on Mac seems the issue was fixed in version `v7.1.1`

**Comment by kamalaknn** [comment]
We have pushed a fix for this in v7.1.1. Closing this now.
