### ISSUE TITLE
Unable to open new tab with short or by clicking on plus sign

### ISSUE THREAD

**Issue by samsonyuwono** [a85/POSTMan-Chrome-Extension#6527]
**Describe the bug**
Using the shortcut for new tab 'Cmd + T' or clicking on the plus sign for a new tab doesn't work. This renders Postman unusable.

**To Reproduce**
1. Go to Postman app
2. Click on plus sign to open new tab or 'Cmd + T'

**Expected behavior**
A new tab is supposed to open up

**Screenshots**
http://www.giphy.com/gifs/MeD9gY99W2km0G2jBJ

**App information (please complete the following information):**
 - App Type: Native App
 - Postman: Version 7.1.0
 - OS: . macOS High Sierra 10.13.6

**Comment by kamalaknn** [comment]
Hey @samsonyuwono

Can you write to us at `help@getpostman.com` with screenshots of any errors from `View -> Developer -> Show DevTools (Current View)` and log files from `View -> Developer -> View logs in Finder`?

We will investigate further.

Can you try opening a new window and see if that helps?

**Comment by kamalaknn** [comment]
We have pushed a fix for this v7.1.1.

Closing this now. Please update and let us know if the issue still persists.
