### ISSUE TITLE
Monitor silently failing: run finished without results

### ISSUE THREAD

**Issue by JP-from-Postman** [a85/POSTMan-Chrome-Extension#6531]
[Reported by Postman Support, on behalf of user]

**Describe the bug**
User reports that all team monitors started silently failing about 30 days ago. Test results in dashboard shows only: "This run finished without results; check the console log for details."

Console log shows only (note start and end timestamps are identical):
<img width="597" alt="Screen Shot 2019-05-16 at 4 29 29 PM" src="https://user-images.githubusercontent.com/43283131/57893448-ceb35f00-77f7-11e9-91cd-ee32ad31dc26.png">

**To Reproduce**
Unknown

**Expected behavior**
Monitor runs successfully
Alerts for run failures / errors are sent

**App information (please complete the following information):**
 - App Type: Dashboard, Native App
 - Postman Version: 7.0.9
 - OS: macOS

**Additional context**
See internal notes

**Comment by godfrzero** [comment]
We've investigated and isolated the problem, and also issued a temporary fix for these affected monitors.

There are two problems here:
1. When the team member who created the monitor is removed, the monitoring platform was still attempting to load the collection on behalf of the removed member.
2. When a specific error is encountered while running the job, the error was treated as an empty collection. This is what led to the run apparently completing successfully with an empty log.

Permanent fixes are in the works for both of these cases.

**Comment by JP-from-Postman** [comment]
Thanks @godfrzero. Monitors are running again, _but_ it looks like the environment ownership is off as well. Because of this, the app is not resolving the URL correctly.

Example:

URL in app:
`{{api_url}}/endpoint?parameter={{param_value}}`
URL in request sent by monitor:
`%7B%7Bapi_url%7D%7D%2Fendpoint%3Fparameter%3D%7B%7Bparam_value%7D%7D`

**Comment by kgjelsten** [comment]
Hi, we have just upgraded our team today to the latest version of Postman, and when I now run our collections in Monitor they also encounters the same issue as mentioned in this ticket. I removed one of our team members also, but these collections that we are monitoring was created by my user. Please advise on what to do on this? I would not like to have to set these up again since we then will loose our latest history of our runs.

**Comment by godfrzero** [comment]
@kgjelsten The root issue here has already been addressed and migration to v7 shouldn't break anything.  Removing a user from the team will no longer cause any problems with monitor execution. To get to the bottom of what's going wrong in your case, could you shoot us an email at help@getpostman.com with additional details? This will include monitor ID, collection ID, and environment ID for starters.

**Comment by godfrzero** [comment]
Closing this ticket since the root issue has been fixed already. As for the environment resolution bug, please refer to https://github.com/postmanlabs/postman-app-support/issues/7238.

**Comment by kgjelsten** [comment]
@godfrzero Thanks. It seems to run OK again now when I tested again today. I will post ticket in an email if it returns back :)
