### ISSUE TITLE
Postman crashes with specific URL

### ISSUE THREAD

**Issue by jonavh** [a85/POSTMan-Chrome-Extension#6533]
**Describe the bug**
I was testing things with Postman, I did a POST, and it headers you get the URL where you need to do a GET from. I copied this, and Postman stops and closes.

Afterwards I noticed I copied too much and Postman crashes every time you do this.

**To Reproduce**
1. Go to a new request
2. Paste this: "Location →https://google.be" (without quotes obviously)
3. Click on Send
4. Watch Postman close (Windows v7.1.0)

**Expected behavior**
Not Closing Postman

**Screenshots**
No

**App information (please complete the following information):**
 - App Type Native App
 - Postman Version  v7.1.0
 - OS: Windows 10 version 1803

**Additional context**
No

**Comment by sujayvenaik** [comment]
For reference:  main.log
![image](https://user-images.githubusercontent.com/11532114/57912655-7a1bec80-78a8-11e9-8106-a16d56155b09.png)

**Comment by GaraYaka** [comment]
I have the same issue. When a malformed URL is set and Send, the app crashes.

Malformed URL eg:  https'://service.com
' is the malformed character

Version: v7.1.1
OS: Windows 10 1803 Build 17134.765

**Comment by TSalvin** [comment]
Same issue here

**Comment by jacktang** [comment]
I have the same error on v7.1.1!
And I downgrade to v7.1.0, the request is not send any more.

**Comment by BorntraegerMarc** [comment]
I work with env variables like so and get the exact same error:
![Screenshot 2019-06-12 at 08 55 05](https://user-images.githubusercontent.com/7549295/59329693-cb749b80-8cef-11e9-9155-3c7512764541.png)

**Comment by BorntraegerMarc** [comment]
My mistake: Turns out env variables need to be accessed without the `$` -> after removing that char postman doesn't crash anymore.

Although I believe postman should defenitly not crash in this scenario

**Comment by codenirvana** [comment]
This is fixed in the latest version of the Postman App (`v7.2.0`).
