### ISSUE TITLE
Monitor name overflowing in collection browser

### ISSUE THREAD

**Issue by sivcan** [a85/POSTMan-Chrome-Extension#6535]
**Describe the bug**
Monitor name overflowing in collection browser.

**To Reproduce**
1. Create a monitor with a very long name
2. Open collection browser and change to 'Monitor' tab

**Expected behavior**
Text overflow should be fixed (replaced with an ellipsis) 

**Screenshots**
![image](https://user-images.githubusercontent.com/12631777/57917278-fd8e0b80-78b1-11e9-8e35-4155f29c8d6a.png)

**App information (please complete the following information):**
 - App Type - Native App
 - Postman Version - v7.1.0
 - OS: macOS Mojave

**Additional context**
Filed by Postman

**Comment by DannyDainton** [comment]
Hey @sivcan 👋🏻

With the monitors now being part of the left sidebar in V8, is this still an issue?

**Comment by Hayk-S** [comment]
Closing as with the new UI changes this issue no more exists.
