### ISSUE TITLE
User unable to access a synced collection

### ISSUE THREAD

**Issue by labifrancis** [a85/POSTMan-Chrome-Extension#6541]
**Describe the bug**

A user has a collection that is synced to Postman servers but the user can't see the collection on their web dashboard and also get an access error when trying to retrieve the collection using [Postman API](https://support.getpostman.com/hc/en-us/articles/360022272553-How-to-recover-my-collections-using-the-Postman-API-).

**To Reproduce**
1. Create a [Postman collection](https://learning.getpostman.com/docs/postman/launching_postman/creating_the_first_collection)
2. Try to retrieve the collection using this [guide](https://support.getpostman.com/hc/en-us/articles/360022272553-How-to-recover-my-collections-using-the-Postman-API-)
```
{
    "error": {
        "name": "forbiddenError",
        "message": "You are not permitted to perform the action."
    }
}

```

**Expected behavior**

The user should be able to see their collection on the web dashboard and also retrieve the collection using Postman API. 

**App information (please complete the following information):**
 - App Type [Native App]
 - Postman Version [7.1]

**Comment by tanvir4web** [comment]
Is It Recovered Yet ?

**Comment by preethammavin** [comment]
@Tanvir4x can you check in go.postman.co/me/collections and let me know if you see the collection there?

**Comment by preethammavin** [comment]
We have pushed a fix for the same, closing the issue for now. Do feel free to reopen it if it isn't so
