### ISSUE TITLE
Old Logo on Postman App Support Readme.md

### ISSUE THREAD

**Issue by fullpoint** [a85/POSTMan-Chrome-Extension#6542]
**Describe the bug**
Old Postman Logo in Postman App Support readme.md

**Expected behavior**
Current logo expected

**Screenshots**
Actual
<img width="420" alt="Screenshot 2019-05-17 11 12 51" src="https://user-images.githubusercontent.com/18669142/57947857-e7258700-7894-11e9-8500-8958a7821905.png">

Expected 
<img width="924" alt="Screenshot 2019-05-17 11 13 33" src="https://user-images.githubusercontent.com/18669142/57947837-dbd25b80-7894-11e9-992d-225e476f760b.png">

**Comment by tristandenyer** [comment]
@shamasis @fullpoint The new logo is here: https://assets.getpostman.com/common-share/postman-logo-horizontal-320x132.png

**Comment by shamasis** [comment]
Updated. Also copied over the new tagline from website. Repeated on newman: https://github.com/postmanlabs/newman/blob/develop/README.md
