### ISSUE TITLE
trouble signing in success, no verifying of e-mail if registered or not.

### ISSUE THREAD

**Issue by nbdcruz** [a85/POSTMan-Chrome-Extension#6546]
So I forgot my password and I'm not sure what e-mail I used 
In your current forgot password process, there's no checking if the e-mail was been registered or not and I think it should have.
And even the e-mail is not registered I still redirected to this link
-> https://identity.getpostman.com/trouble-signing-in-success

**Comment by preethammavin** [comment]
@itsloudc there are couple of reasons why we do not show if the email is registered or not, one of the primary reason is security. 
But you could go ahead and check you email inbox where you have confirmation email , or when you reset your password you would receive a mail
