### ISSUE TITLE
Postman native app didn't show any interface on linux

### ISSUE THREAD

**Issue by dwadp** [a85/POSTMan-Chrome-Extension#6547]
**Describe the bug**
Postman native app is running correctly, but after the loading screen, the app shows nothing to the screen, there are no interface showing, only the icon of the app shows on my dock menus. But there are no errors, i have followed the guidlines on installing postman on the official documentation.

**To Reproduce**
1. Start the app by double clicking the binary file
2. Nothing show on the screen, just blank transparent and no ui interface

**Expected behavior**
It should show me the ui interface of an app.

**Screenshots**
This is the screenshot, as we could see, im pointing on postman icon which is running, but nothing to show, just transparent, blank, and no ui.
![image](https://user-images.githubusercontent.com/11770425/58014595-cc207480-7b2b-11e9-9f43-f02ee30d418d.png)

**App information:**
 - App Type [Native App]
 - Postman Version [Postman-linux-x64-7.0.9.tar.gz]
 - OS: [elementary OS 5.0 Juno 64bit]

**Comment by numaanashraf** [comment]
@dewaadiperdana Could you send us the application logs to help@getpostman.com? You can find them as `~/.config/Postman/logs`. Please mention this issue in the email subject - "Logs for GitHub #6547"

**Comment by dwadp** [comment]
Ok i will

**Comment by numaanashraf** [comment]
@dewaadiperdana Thanks for sending the logs. We were not able to pick up any anomalies from the logs. We'll try to replicate on "elementary OS 5.0 Juno 64bit" and get back.
