### ISSUE TITLE
Ability to duplicate an example

### ISSUE THREAD

**Issue by zgirod** [a85/POSTMan-Chrome-Extension#6548]
**Is your feature request related to a problem? Please describe.**
It is frustrating that you can duplicate requests to quickly copy/paste/modify however you cannot duplicate examples to quickly copy/paste/modify examples.

**Describe the solution you'd like**
I would like the ability to duplicate examples.

**Describe alternatives you've considered**
Manually create each example from scratch each time.

**Comment by turnspike** [comment]
This functionality is not available on Postman 6.7.4 and macOS 10.14.5 for locked collections. I'm trying to duplicate a request from [an example Okta collection](https://developer.okta.com/reference/postman_collections/) into my project collection. Dragging and dropping does nothing, the request's (⋯) hamburgler menu only shows "Open in New Tab", selecting the request and Edit → Copy then Edit → Pasting into the collection does nothing.

I'm trying to clone an API example from their collection into my project collection so I can edit it. I can't find an intuitive UX path to this goal.

The workaround is to duplicate the locked collection, I can then unlock it and duplicate the individual requests. I should be able to drag-and-drop requests from a locked collection into my project collection as this is a non-destructive action.

Reference issue: #1390

**Comment by vkaegis** [comment]
@zgirod @turnspike Thanks for writing in! This is quite an obvious miss from us, definitely have plans to allow duplication of examples and a more consistent UX when it comes to working with lists of things in general. Will keep you posted.

**Comment by rlcurrall** [comment]
This would definitely be beneficial to my workflow! :crossed_fingers:

**Comment by alianos-** [comment]
This doesn't seem to be getting much love, but I would also appreciate this. Especially if you are trying to work with Mocks this is a must.

**Comment by umnex** [comment]
Please implement this feature. It will save a lot of time. I have to duplicate the error responses using examples.

**Comment by umnex** [comment]
Ability to clone examples is a must. Right now i am creating API specs for my team and have to do a lot of manual work to create same types of examples. Please implement this ASAP. Thanks!

**Comment by Hipatija2904** [comment]
This would be an amazing feature, I am surprised this is not already a feature and it is not getting more buzz. Pleeeease make this happen

**Comment by Hipatija2904** [comment]
Just realized it is possible to duplicate examples if we access from browser... Only desktop app is the problem, so it's something \o/

**Comment by giridharvc7** [comment]
You can now duplicate examples, both on the browser and the app. Can you please check and let us know if you face any problems?

**Comment by umnex** [comment]
Thanks. Yes it is working now.





Umer Nawab
Chief Technology Officer
Intelligenes
***@***.***D71C1E.99862160]
+1 647 846 3006<tel:+1%20647%20846%203006>
***@***.***D71C1E.99862160]
***@***.******@***.***>
***@***.***D71C1E.99862160]
www.intelligenes.com<https://www.intelligenes.com/>
***@***.***D71C1E.99862160]
120 Adelaide Street West, Suite 2500, Toronto, Ontario
***@***.***D71C1E.99862160]
[facebook]<https://www.facebook.com/intelligenes>
[twitter]<https://twitter.com/intelligenes>
[linkedin]<https://www.linkedin.com/company/intelligenes/>
