### ISSUE TITLE
Team size on free accounts is capped at 5? 

### ISSUE THREAD

**Issue by carolin-postman** [a85/POSTMan-Chrome-Extension#6549]
**Describe the bug**
A tooltip in the team management page states that I can only have a max of 5 users on my team but in the [documentation on collaboration](https://learning.getpostman.com/docs/postman/launching_postman/collaboration/#usage-limit-for-free-users), it says free teams "However, note that Postman does not impose any limit on the number of people you can invite." Which one is accurate? 

<img width="787" alt="Screen Shot 2019-05-18 at 11 43 44 AM" src="https://user-images.githubusercontent.com/44679818/58032527-a36e8f80-7ad7-11e9-96e1-27507a980d85.png">

<img width="770" alt="Screen Shot 2019-05-20 at 8 19 01 AM" src="https://user-images.githubusercontent.com/44679818/58032722-137d1580-7ad8-11e9-850a-2a7150f43d83.png">

**To Reproduce**
1. Go to "Team management page" - https://go.postman.co/team
2. Hover over the tooltip

**Expected behavior**
Congruent messaging in the app and the documentation

**Comment by preethammavin** [comment]
@carolin-postman the initial free team is started at 5 slots when less than 5 users are added in the team. As and when more users are added we expand the slots .
