### ISSUE TITLE
Version 7.1.1 Hawk Payload Hashing Difference

### ISSUE THREAD

**Issue by ThePatrickMartin** [a85/POSTMan-Chrome-Extension#6550]
Since 7.1.1, the payload calculated by Postman for POST request is differing from that calculated by Hawk.net.

**Comment by vikiCoder** [comment]
Hi @serpien73 

I tried to reproduce it with [hawk authentication endpoint](https://docs.postman-echo.com/?version=latest#843acf02-a33c-c4bb-d742-c07b9212e4b0) of [postman-echo.com](https://docs.postman-echo.com) but it seems to be working fine for me. Can you provide following details for us to debug the problem

1. Which version of Postman app you were using before 7.1.1? Was the same request working find with that version of app?
2. Which body type you are using in the request?
4. What headers are being sent in the request (you can see this in postman console)
5. Are you using file in body? If yes then is the file inside the postman working directory or outside?
6. Can you share a scaled-down collection with the problem? (If you are using private endpoint then you can use [hawk authentication endpoint](https://docs.postman-echo.com/?version=latest#843acf02-a33c-c4bb-d742-c07b9212e4b0) of [postman-echo.com](https://docs.postman-echo.com))

**Comment by serpien73** [comment]
It was either 7.0.9 or 7.1.0. Here is the raw request/response:

POST /api/emailgroups/SETDLR_01013_Inventory_Manager/AddGroupMember
Accept: application/json
Content-Type: application/json
Authorization: Hawk id="MKxXFY6pYzaL", ts="1558380038", nonce="5IlSLo", hash="gXL14rn+O1BBehHip/qJ2tADXO7sIKmYsWgL3wSC1gI=", mac="wVn+vi9emEjr93jDJWfHWiSdbAxraX4gACgc8SzUnnw="
User-Agent: PostmanRuntime/7.13.0
Cache-Control: no-cache
Postman-Token: 325adc1a-9895-42f9-a97c-67f6e20e38be
Host: dp2svc-emailgroup.corpstg1.jmfamily.com
cookie: dtCookie=3$F8E2599306D93A2636B4B6DB7B50618F
accept-encoding: gzip, deflate
content-length: 112
Connection: keep-alive
{ "ContactEmail": "setcarrierbols@jmfamily.com", "AllowCorporateEmail": "true", "AddToDealerGroup": "false" }
------------------------
HTTP/1.1 401
status: 401
Cache-Control: no-cache
Pragma: no-cache
Content-Length: 16
Content-Type: text/plain; charset=utf-8
Expires: -1
Server: Microsoft-IIS/7.5
X-AspNet-Version: 4.0.30319
X-Powered-By: ASP.NET
Date: Mon, 20 May 2019 19:20:41 GMT
Bad payload hash

**Comment by serpien73** [comment]
I'm not sure which version but it had to have been either 7.0.9 or 7.1.0. Here are the results from posting some JSON to our internal endpoint, along with the Hawk log error from our side, plus the Hawk authentication header calculated by Hawk on the postman echo side when we posted the exact same JSON:

From Postman Console
====================
POST /api/emailgroups/SETDLR_01013_Inventory_Manager/AddGroupMember
Accept: application/json
Content-Type: application/json
Authorization: Hawk id="MKxXFY6pYzaL", ts="1558381426", nonce="avxMBV", hash="gXL14rn+O1BBehHip/qJ2tADXO7sIKmYsWgL3wSC1gI=", mac="dWhM0P1bynwfxB9ObnlrXrwyO/vbiYT96Ezn3dPrQGU="
User-Agent: PostmanRuntime/7.13.0
Cache-Control: no-cache
Postman-Token: a5dc7d69-b2fe-4b55-a988-505494fe5912
Host: dp2svc-emailgroup.corpstg1.jmfamily.com
cookie: dtCookie=3$F8E2599306D93A2636B4B6DB7B50618F
accept-encoding: gzip, deflate
content-length: 112
Connection: keep-alive
{ "ContactEmail": "setcarrierbols@jmfamily.com", "AllowCorporateEmail": "true", "AddToDealerGroup": "false" }

From Our Hawk Log
=================
HawkNet Information: 0 : 2f40625f-d368-4755-bb48-6880d756c482 - Received Auth header: id="MKxXFY6pYzaL", ts="1558381426", nonce="avxMBV", hash="gXL14rn+O1BBehHip/qJ2tADXO7sIKmYsWgL3wSC1gI=", mac="dWhM0P1bynwfxB9ObnlrXrwyO/vbiYT96Ezn3dPrQGU="
HawkNet Warning: 0 : 2f40625f-d368-4755-bb48-6880d756c482 - Bad payload hash. Received hash gXL14rn+O1BBehHip/qJ2tADXO7sIKmYsWgL3wSC1gI=. Calculated hash X8Zlrg5EDYwn25dAq/JuQ7mWE/j2/vH33Tnj1dbey5g=
HawkNet Error: 0 : System.Security.SecurityException: Bad payload hash
   at HawkNet.Hawk.ValidatePayload(HawkCredential credential, String receivedHash, Func`1 requestPayload)
   at HawkNet.Hawk.Authenticate(String authorization, String host, String method, Uri uri, Func`2 credentials, Int32 timestampSkewSec, Func`1 requestPayload)
   at HawkNet.HttpRequestMessageExtensions.Authenticate(HttpRequestMessage request, Func`2 credentials, Int32 timestampSkewSec)
   at HawkNet.WebApi.RequiresHawkAttribute.OnAuthorization(HttpActionContext actionContext)
The Zone of the assembly that failed was:
MyComputer

Auth Header from Postman Echo Response
======================================
"authorization": "Hawk id=\"dh37fgj492je\", ts=\"1558381582\", nonce=\"r6NM6a\", hash=\"gXL14rn+O1BBehHip/qJ2tADXO7sIKmYsWgL3wSC1gI=\", mac=\"LB3Qd1HaoRflU2Ody3EMyReuPP0BlGw3KQg02Wo81Rs=\""

**Comment by ThePatrickMartin** [comment]
We are using [Hawk.net](https://github.com/pcibraro/hawknet/blob/master/HawkNet/Hawk.cs) by Pablo Cibrero. It appears that our library is calculating the hash differently than postman's Hawk implementation.

It would be ideal to simply have an option in postman to not pass the hash in the Hawk header.

**Comment by ThePatrickMartin** [comment]
Any update on this issue? Since the update we are no longer able to utilize Postman to test our Hawk-authenticated APIs.

**Comment by vikiCoder** [comment]
Hi @serpien73,

I believe that the issue is because of the `Content-Type` header in the request. If you are not setting `Content-Type` header manually from the Postman App UI then the App will add it automatically for you which is causing the problem.

We are working on making payload hash verification optional in Hawk Authentication and will be releasing that soon, stay tuned for that. Until then, you can add `Content-Type` header manually from the App UI and it should work.

Please let us know whether suggested hack worked for you or not so that we can investigate further if required.

**Comment by donald-jackson** [comment]
The last working version is 7.0.9. Postman is now using the POST body when computing the Hawk payload, which isn't strictly incorrect, it just breaks everything for people who have been using Hawk without this for the past few years.

We are not in a position to change our API's to cater for this change as it would break many integrations so I propose(d) just adding it as a configuration option so it doesn't break backward compatibility for users like us.

PS: Postman also auto updates itself even if you ask it not to, which makes this more annoying :)

**Comment by vikiCoder** [comment]
Hi @donald-jackson 

We understand your issue and we have added an option to add payload hash in Hawk authentication and turn it off if needed. We will be releasing this option in our next release. Below is a screenshot showing this option.

![image](https://user-images.githubusercontent.com/16588032/60089399-04842580-975e-11e9-8397-47146c0b7293.png)

**Comment by donald-jackson** [comment]
@vikiCoder Thanks for this! Much appreciated by me and I'm sure many others :)

**Comment by vikiCoder** [comment]
We've added this option in the latest version of the Postman app (v7.3.4).
