### ISSUE TITLE
Bootcamp Collaboration skill walkthrough doesn't take the user further

### ISSUE THREAD

**Issue by cyrielle-hada** [a85/POSTMan-Chrome-Extension#6551]
**Describe the bug**
The walkthrough for the Collaboration skill stops at 30% completed and doesn't indicate that the lesson is over. 
See screencast to understand the current behavior: https://www.loom.com/share/1b58dc82e7554c5fb031e29f27e32649.

**To Reproduce**
1 - Click on Bootcamp.
2 - Click on the Collaboration lesson
3 - Click on Learn
4 - Stat the walkthrough - Click on Invite 0% > Enter an email ID 10% completed > Click on 'Add' 20% completed > Click here to invite 30% completed
5 - Lesson is ended and shows as 0% completed.

<img width="571" alt="Screen Shot 2019-05-20 at 18 34 17" src="https://user-images.githubusercontent.com/47351631/58040688-f07d5080-7b2d-11e9-94a5-bf8f7a4f3bc3.png">

**Comment by cyrielle-hada** [comment]
The issue appears to be fixed.

**Comment by cyrielle-hada** [comment]
Reopening this as the issue seems to be reoccurring @preethammavin

**Comment by cyrielle-hada** [comment]
Reopening this as the issue seems to be reoccurring @preethammavin

**Comment by prashantagarwal** [comment]
@cyrielle-hada We haven't fixed this issue yet. I'll update this ticket once we have a fix for this issue.

**Comment by anudeepmedicharla** [comment]
@prashantagarwal Did we fix this issue?

**Comment by RobinSmithTHR** [comment]
Still happening for me - Version 7.6.0 (7.6.0)

**Comment by prashantagarwal** [comment]
@RobinSmithTHR @cyrielle-hada This should be fixed now.
