### ISSUE TITLE
Postman App Icon Not Visible In Windows

### ISSUE THREAD

**Issue by tparikka** [a85/POSTMan-Chrome-Extension#6552]
**Describe the bug**
On Windows 10 x64 Build 1809 with Postman x64 7.1.1, the app icon does not display in the Start Menu or in the Taskbar when the app is running.

**To Reproduce**
1. Install Postman 7.1.1 on Windows 10 Build 1809
2. Launch the app, or check the Start menu

**Expected behavior**
The Postman icon should be registered in the shell and visible in Explorer, Taskbar, etc.

**Screenshots**
![image](https://user-images.githubusercontent.com/7715790/58043437-c82c2c80-7b02-11e9-89b5-8a2445989691.png)

**App information (please complete the following information):**
 - App Type Native App
 - Postman Version 7.1.1
 - OS: Win10x64 Build 1809

**Comment by pranoy10** [comment]
Had the same issue after an update.  Fixed it using #3107

**Comment by mccannt** [comment]
@tparikka @pranoy10 Is this still happening to you on the most current version of the app?

**Comment by tparikka** [comment]
This issue seems to be resolved for me in win32 10.0.18363 / x64.

**Comment by mccannt** [comment]
Great, thank you for following up with us on this @tparikka
