### ISSUE TITLE
Favicon Upload (< 1kb) Throws Error

### ISSUE THREAD

**Issue by chrisdeso** [a85/POSTMan-Chrome-Extension#6554]
**Is your feature request related to a problem? Please describe.**
Uploading a favicon that's less than 1kb throws an ambiguous error.

**Describe the solutions/alternatives you'd like**
- Documentation on the requirements for a favicon upload
- Error messages that indicate whether or not the size/file-type isn't supported

**Additional context**
[Filed by Postman]

![Screen_Shot_2019-05-20_at_7_18_53_PM](https://user-images.githubusercontent.com/4734306/58060217-ec553100-7b35-11e9-8820-2262ebca6734.png)

**Comment by Cazaimi** [comment]
@Raja-Simha , I do not think this is an issue related to [product/documentation](https://github.com/postmanlabs/postman-app-support/labels/product%2Fdocumentation), but rather [product/dashboard](https://github.com/postmanlabs/postman-app-support/issues?q=is%3Aopen+label%3Aproduct%2Fdocumentation+label%3Aproduct%2Fdashboard).

**Comment by mccannt** [comment]
@chrisdeso Is this still an issue?

**Comment by chrisdeso** [comment]
Hey Folks!

Closing this out as it is no longer an issue 😬
