### ISSUE TITLE
 Usage of "Shared History" not getting updated after clearing history

### ISSUE THREAD

**Issue by ash007-postman** [a85/POSTMan-Chrome-Extension#6555]
**Describe the bug**
Usage of "Shared History" not getting updated after clearing history

**To Reproduce**
1. Go to ' History'
2. Click on 'Clear all.'

**Expected behavior**
Once you clear the History, the usage for "Shared History" should get updated. 

**App information (please complete the following information):**
 - App Type-Native App
 - Postman Version - 7.0.9

**Additional context**
User is trying to do so since he is getting a warning that the team collections will be archived because they've exceeded the "Shared history" limit.

![Screenshot 2019-05-21 at 6 14 42 AM](https://user-images.githubusercontent.com/41741228/58060648-f6a41900-7b8f-11e9-88e9-2e272329dada.png)

**Comment by vladdeSV** [comment]
*I originally submitted this issue via mail*

I am using the OSX version of Postman.
Currently using 7.1.0, but I noticed the issue in 7.0.9.

We have two shared workspaces, the default "Team Workspace" and a project specific project. None of them have any stored history.

Using the online Dashboard I also see the same number of Shared History, so I do not believe this is only related to the application.

And also, the number keeps going up and down. Currently, if I remove all history I am stuck at 6 "ghost" requests

**Comment by vladdeSV** [comment]
I used the "Clear all" button in the history tab today, and my usage now properly shows the correct amount `0` of Shared History.

This was done with Postman v7.1.1 on macOS.

*Previously this had no effect, and got stuck at 6 requests.*

**Comment by drakunov** [comment]
This is still exists in Postman for Windows Version 8.4.0 win32 10.0.17763 / x64
