### ISSUE TITLE
Need to clear the cookies

### ISSUE THREAD

**Issue by kthulsidoss** [a85/POSTMan-Chrome-Extension#6557]
Please provide a snippet for clearing the cookies .. mostly i believe that this needs to be placed top of the script.

because of this newman is caching the responses and reporting false positives.

**Comment by shamasis** [comment]
Cookies cannot be manipulated using scripts yet. It’s a limitation that we are addressing in the near term. Closing as duplicate of https://github.com/postmanlabs/postman-app-support/issues/5215
