### ISSUE TITLE
mac v7.1.1 crash 

### ISSUE THREAD

**Issue by hvritual** [a85/POSTMan-Chrome-Extension#6558]
after auto update v7.1.1,  run app is normal, but post api request eg.(https://www.baidu.com) ,it's crash and not any output log(maybe I can't find), 
normal api before update also can't request, dut to crash.

runtime environment: mac mojave 10.14.4

**Comment by numaanashraf** [comment]
@hvritual We are having trouble reproducing this at our end. It'll help a lot if you could send us the application logs found in `View > Developer > View logs`. Please send these logs to `help@getpostman.com` with the subject "Logs for GH#6558"

**Comment by numaanashraf** [comment]
Thanks for the logs @hvritual. I've added a screenshot of the crash I noticed in the logs here. We'll get this addressed in upcoming releases.

<img width="803" alt="Screenshot 2019-05-22 at 3 53 58 PM" src="https://user-images.githubusercontent.com/3295568/58167565-d8324080-7ca9-11e9-889c-23cf4eb6bf72.png">

**Comment by hvritual** [comment]
This problem should be related to request url escape ,like http://www.baidu.com escape %20http://www.baidu.com, and application will crash

**Comment by tanistra** [comment]
the same problem but with ` or ' character before url

**Comment by codenirvana** [comment]
Duplicate of #6533
