### ISSUE TITLE
Can not select language under code section

### ISSUE THREAD

**Issue by ravibhagat** [a85/POSTMan-Chrome-Extension#6559]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**App information (please complete the following information):**
 - App Type [ Native App]
 - Postman Version [7.1.1]
 - OS: [ window 10]

**Additional context**

Step to regenerate issue:
1. open any api 
2. Click on code
3. click on HTTP
now try to select any other language which has drop down arrow, example Java, nodejs etc
It will not select that language.

Thanks,
Ravi 
![Capture](https://user-images.githubusercontent.com/17745162/58070915-7219c080-7bb8-11e9-9cb2-25e65457347f.PNG)

**Comment by abhijitkane** [comment]
@ravibhagat Can you try hovering your cursor over the Java/Javascript entries? This should open a second-level menu. They support multiple variations, so they aren't selectable by themselves.

**Comment by ravibhagat** [comment]
@abhijitkane I have tried both ways neither click nor hover works! But if I want to select any language which do not have multiple variation then it works fine.

**Comment by numaanashraf** [comment]
@ravibhagat This looks like its a user interface bug. The horizontal scroll inside the dropdown looks like the second-level menu is opening within the scroll. Could you try scrolling right inside the dropdown to access the second-level menu?

<img width="725" alt="Screenshot 2019-05-21 at 11 48 12 AM" src="https://user-images.githubusercontent.com/3295568/58072800-7517af80-7bbe-11e9-99fe-f972ca77df73.png">

**Comment by numaanashraf** [comment]
@ravibhagat We are tracking this as a bug internally and we'll fix this in the upcoming releases.

**Comment by ravibhagat** [comment]
Yes its visible after scrolling horizontally, but in that case main language itself is not visible :)


![Capture](https://user-images.githubusercontent.com/17745162/58086240-e44fcc80-7bdb-11e9-9ab4-17cea28c9c93.PNG)

**Comment by DannyDainton** [comment]
Closing this issue and it has been fixed in a later version.
