### ISSUE TITLE
Postman crashes after sending part of a runner

### ISSUE THREAD

**Issue by Tenaciousrm** [a85/POSTMan-Chrome-Extension#6560]
Hi

We are experiencing problems since Postman updated to version 7.1.1 on Friday. The runner starts off pretty fast through iterations but as it progresses it gets slower and slower until Postman eventually crashes. 

We have been forced to divide our data to a maximum of 300 iterations which is not great considering that we need to run 50,000 iterations per file. This results in working through the night when there are deadlines instead of having the confidence of letting it run on its own through the night.

We are running two fairly simple requests per iteration. One to get token and the other to create an IoT Thing.

There are a number of other runners that we run too that we experience the same problem with but this one is the largest in number of iterations.

We tried downgrading to the previous version and setting Postman to not automatically upgrade, but it upgrades anyway as soon as we restart it.

We are running Windows 10 machines over a 20Mbps fiber connection.

**Comment by vdespa** [comment]
I have tried a similar scenario on a macOS machine and experienced a considerable lag between the requests. The Collection Runner interface was unresponsive.

**Comment by saswatds** [comment]
I am closing this issue in favor of https://github.com/postmanlabs/postman-app-support/issues/6824 which also speaking of this issue.
