### ISSUE TITLE
upload  multiple images

### ISSUE THREAD

**Issue by KJohn2q** [a85/POSTMan-Chrome-Extension#6561]
**Describe the bug**
recept one image while upload multiple images

**To Reproduce**
1. input the  url
2. select two images as  params 
3. click send

**Screenshots**
![image](https://user-images.githubusercontent.com/20499046/58083805-49abb980-7bec-11e9-952f-73b3f56bd6d5.png)

**App information (please complete the following information):**
 - App Type [php web application ]
 - Postman Version [7.1.1]
 - OS: [win 10]

**Comment by saswatds** [comment]
@KJohn2q We were facing an issue with file references detailed in this issue https://github.com/postmanlabs/postman-app-support/issues/6516#issuecomment-492930576

We have applied a fix in 7.1.1 but it's possible that certain file reference already synced before could be malformed. Can you try reselecting the file are try again? If the issue still persists can you send us what you are seeing in the postman console? 

Do you see something like this?
<img width="816" alt="Screenshot 2019-05-16 08 51 06" src="https://user-images.githubusercontent.com/8796447/58125100-6ddbba80-7c2d-11e9-8fff-8d98cba394f2.png">

**Comment by KJohn2q** [comment]
I solved the problem by modification `Working Directory` and revocation,but still can't understand why new file cover the file selected previous while select a new file.

**Comment by KJohn2q** [comment]
Sorry, I reply you before read the issue #6516 seriously .I know the cause of the problem now and solved the problem after update the latest version. Sorry again and Thank you.

**Comment by saswatds** [comment]
That's great to hear. Thanks for reaching out to us. I will be closing this issue for now.

If you find any issue in the future, feel free to reach back.
Thanks
