### ISSUE TITLE
Search the variable in Environment quick look

### ISSUE THREAD

**Issue by rathodamol** [a85/POSTMan-Chrome-Extension#6562]
Current situation: 

My environment quick look screen has got lots of variables and at times I have to scroll too much to go to the exact variable. 

Expected: A small search input box to search the variable name which will populate the results (Like Typaheads or something). It can increase the usability.

**Comment by m3dbedb** [comment]
Also it would be good to be able to mark environment/global variables favourite to move them to top

**Comment by rathodamol** [comment]
Hello @sujayvenaik  

Are you planning to do something on the above mentioned improvement?

**Comment by DannyDainton** [comment]
Duplicate of #8530
