### ISSUE TITLE
Postman continues to run a runner in the background when paused

### ISSUE THREAD

**Issue by Tenaciousrm** [a85/POSTMan-Chrome-Extension#6563]
Hi

When I execute a runner using Postman v7.1.1 on a Windows 10 machine and then pause it to check the console log that it executed correctly, it continues to run despite being paused. The runner window shows that it has been paused but the console log shows that it is continuing to run. 

As a result, when I then press the pause button a second time to release the pause and continue the run I get errors in the console log indicating that the objects my create script are creating already exist.

**Comment by saswatds** [comment]
Hi @Tenaciousrm can you give a size estimation and iteration count of the collection that you are running?

**Comment by shamasis** [comment]
Closing this issue from inactivity.
PS: We are tracking runner memory consumption related delays and a `setInterval` timer stop failure, but nothing reproducible to indicate it is continuing to work background post window closure.
