### ISSUE TITLE
Postman insists on upgrading even when set to not update automatically

### ISSUE THREAD

**Issue by Tenaciousrm** [a85/POSTMan-Chrome-Extension#6564]
Hi

I am using Postman v7.1.1 on a Windows 10 machine. 

This version is giving problems per a recent post so we tried downgrading to an earlier version and using that. We could downgrade and that version works fine. 

The problem is that when we set Postman to not automatically upgrade, it does anyway and then when Postman is restarted, we have to do this all over again.

**Comment by numaanashraf** [comment]
@Tenaciousrm The update setting controls only major releases, and Postman auto-updates to the latest minor/patch release automatically when it is opened. Could you point us to the problems you are facing with this specific version?

**Comment by Tenaciousrm** [comment]
Hi

I created tickets #6560 and #6563 regarding these problems.

Warm regards

Randell
082 741 6360

**Comment by arlemi** [comment]
#6560 and #6563 were resolved, we're tracking a feature request for being able to disable minor updates in #6999. Closing this one. 🙂

**Comment by stefanluchian** [comment]
@ Postman guys: Why are you insisting to force us to update, even on minor updates?
This is no way to win new users! And you might lose existing ones.
We simply don't want automatically minor updates! Is it so hard to understand it?
We are not some mobile-app-freaks who just want to have the latest thing.
Just let us decide if and when we want minor updates!
This is really annoying!
Stop forcing us to update! Should be our decision!
