### ISSUE TITLE
Allow deleted requests to be restored

### ISSUE THREAD

**Issue by labifrancis** [a85/POSTMan-Chrome-Extension#6565]
**Is your feature request related to a problem? Please describe.**

For now, only deleted **collections** can be restored from the trash but deleted **requests** can't be restored. When a user creates a request and deletes the same request, it can't be recovered.

**Describe the solution you'd like**
When a request is deleted, it should be moved to the trash so that the user can recover it later if they need to do so.

**Comment by preethammavin** [comment]
@labifrancis we support restore functionality on collections to an earlier version for Pro and Enterprise customers. So in case the request was deleted the user can restore to an earlier version of the collection from the changelog.

**Comment by phaseOne** [comment]
I'd like to reopen this, as I share the need to restore an accidentally deleted request in the history that I captured using Postman Interceptor.

**Comment by yarfik** [comment]
+1
It will be nice to have this feature

**Comment by NandoZee** [comment]
Restoring collections is a feature, how is this not?

**Comment by mnabe** [comment]
@preethammavin @postman-support I would also like to add my voice in support for reopening this. I would assume that you at least as often (if not more often) accidentially delete a single request, rather than a whole collection. 

So it would be nice to have requests available in the trash-folder for a day or something like that, just like is the case for collections.

This issue is still gaining a bit of traction years after it was closed.

Is it possible to review this and give an update?

**Comment by gregpboon** [comment]
As @NandoZee said "Restoring collections is a feature, how is this not?". 
There is a restore in history but it does NOTHING.

**Comment by shaunfischmann** [comment]
Also needed here!

**Comment by AnmolSaxenaVodafone** [comment]
> **Is your feature request related to a problem? Please describe.**
> 
> For now, only deleted **collections** can be restored from the trash but deleted **requests** can't be restored. When a user creates a request and deletes the same request, it can't be recovered.
> 
> **Describe the solution you'd like** When a request is deleted, it should be moved to the trash so that the user can recover it later if they need to do so.

Is this feature still not available?

**Comment by itsMGA** [comment]
Apparently, these guys really listen to the community :)

**Comment by johndiii** [comment]
Really would like to have this feature (after deleting a complex request by mistake when trying to delete an example).

**Comment by asairaghu** [comment]
So why there is no way implemeted to restore a request. I selected one request to delete, but accidentally deleted the most important one. I realized with in a minute, still use less.

**Comment by DatBrute** [comment]
Undo delete is such a powerful and common feature, I'm shocked to see this program doesn't have it

**Comment by DivineShara** [comment]
Yoooo guys... Can we have this feature already? How on earth can I not restore a deleted request???

Please its important to add this. Thank you

**Comment by daniel-ach-26** [comment]
Any update ?

**Comment by TanimSk** [comment]
+1

**Comment by claudiocruzfd** [comment]
Bump ☝️

**Comment by kurror** [comment]
2027 bump
