### ISSUE TITLE
App: enable sync to view your team (v7.1.1)

### ISSUE THREAD

**Issue by JP-from-Postman** [a85/POSTMan-Chrome-Extension#6570]
[Reported by Postman Support, on behalf of user]

**Describe the bug**
User is asked to enable sync to view teams, and no content is syncing to web dashboard. User is on v7.1.1, and enabling sync is no longer an option in app settings.

**To Reproduce**
See internal notes

**Screenshots**
![Screenshot 2019-05-21 at 09 59 35](https://user-images.githubusercontent.com/43283131/58136185-15cb9680-7be2-11e9-9d3a-cb954c359f3b.png)
![Screenshot 2019-05-21 at 09 59 26](https://user-images.githubusercontent.com/43283131/58136192-1c5a0e00-7be2-11e9-877d-1069d657d8c6.png)

**App information (please complete the following information):**
App Type: Native app
Postman Version: 7.1.1
OS: macOS

**Additional context**

**Comment by JP-from-Postman** [comment]
@preethammavin I thought this was a bug, since we removed the option to disable syncing some time ago. Should it be labeled bug instead of feature?

**Comment by benperiton** [comment]
From my point of view (I raised the issue with JP) it is a bug - I don't have any way to re-enable syncing after it was removed, so regression/bug

**Comment by DannyDainton** [comment]
Hey @benperiton / @JP-from-Postman 

Is this still an issue on the latest version for you?

**Comment by DannyDainton** [comment]
I'm going to close this issue but we can open this up again if this is still a problem that people are facing.
