### ISSUE TITLE
Support `application/jose`

### ISSUE THREAD

**Issue by karuna** [a85/POSTMan-Chrome-Extension#6572]
**Is your feature request related to a problem? Please describe.**
I cannot use `application/jose` as content-type 

**Describe the solution you'd like**
There's a radio button `application/jose` when I entered something in post body

**Describe alternatives you've considered**
Not possible since there's no option for this

**Additional context**
`application/jose` is valid and has rfc: https://tools.ietf.org/html/rfc7515#section-9.2

**Comment by abhijitkane** [comment]
@karuna Are you talking about the options in dropdown when you select raw? 
<img width="365" alt="Screen Shot 2019-05-23 at 19 38 45" src="https://user-images.githubusercontent.com/681190/58259626-89aca100-7d92-11e9-81eb-613338f3f897.png">

If `jose+json` is a subset of json, the Content-Type header can manually be modified from the headers tab.  The radio buttons modify the UI for body input.

**Comment by karuna** [comment]
ah ok, I'll just override that from headers tab. it seems that those radio buttons are very counter intuitive then.
