### ISSUE TITLE
Add possibility to point to a openapi endpoint of an existing api in APIs Beta

### ISSUE THREAD

**Issue by tehho** [a85/POSTMan-Chrome-Extension#6574]
**Is your feature request related to a problem? Please describe.**
Yes. Would like to instead of open and copy an openapi definition just point to the definition url and be loaded directly

**Describe the solution you'd like**
Add an option in the dropdown to point to an endpoint

**Describe alternatives you've considered**
No alternatives are acceptable :P

**Additional context**
Great feature for distributing collections 👍 
10/10 would GET again

**Comment by a85** [comment]
@tehho Curious. Where do these OpenAPI definitions live? Source code repo? Deployed server?

**Comment by tehho** [comment]
Deployed server. We expose the swagger endpoint of swashbuckle in our aspnetcore and would be nice to point to the index.json deffinition.

But any open json file would be appreciated as a target

**Comment by a85** [comment]
We are looking at a 2-way sync between source code repos and Postman. Would that work for you?

**Comment by andreassiegel** [comment]
This would be awesome!

I'm currently looking for a convenient/easy to use way to update Postman collections whenever we update our API specification in OpenAPI YAML files that are located in (private) GitHub repositories.

Right now, they're not edited using Postman. Some use the Swagger Editor, others use any arbitrary text editors. I'm pretty sure that would change once there is at least a nice preview UI available, maybe related to https://github.com/postmanlabs/postman-app-support/issues/6678.

**Comment by abhijitkane** [comment]
With Postman v9, you can connect your APIs to repositories and maintain 2-way connectivity between the two. Changes made on the repository can be pulled into Postman - this will update your API definition to match the updated state of the repo.
Docs are available at https://learning.postman.com/docs/designing-and-developing-your-api/versioning-an-api/using-external-git-repo/. Feel free to open a new issue if you feel your use-case is unaddressed, or if the new flow doesn't work for you.
