### ISSUE TITLE
Timestamp generating bug

### ISSUE THREAD

**Issue by IgorNesterenko** [a85/POSTMan-Chrome-Extension#6575]
**Describe the bug**
Generating {{$timestamp}} doesn't work

**To Reproduce**
Send request with body 
{  
  "name": "Name{{$timestamp}}"
}

**Expected behavior**
Name65656756767

**Screenshots**
http://joxi.ru/bmoVQj6f3l83gr

**Comment by numaanashraf** [comment]
We are having trouble replicating this at our end. Could you send us the app version you are facing this in?

`Postman v7.1.1`
<img width="907" alt="Screenshot 2019-05-28 at 11 31 36 AM" src="https://user-images.githubusercontent.com/3295568/58454472-2fb62d80-813c-11e9-8856-a668059f64ad.png">

**Comment by Kastamat** [comment]
Current Version: v6.0.9
![f8c7ce2b3a](https://user-images.githubusercontent.com/50945611/58455974-a8f95480-812b-11e9-9738-8cbacb3f797d.jpg)

**Comment by numaanashraf** [comment]
@Kastamat Thanks. `v6.0.9` is a really old version and this issue might have been resolved in the latest versions of Postman. Could you update to latest Postman and verify?

**Comment by Kastamat** [comment]
I just upgraded to version 7.1.1
![aa476a8168](https://user-images.githubusercontent.com/50945611/58465445-68f09c80-8140-11e9-8d47-8621ed438e88.jpg)
But the result is the same.
![309693d4c8](https://user-images.githubusercontent.com/50945611/58465565-a6edc080-8140-11e9-9cbe-32ca82cd9ea9.jpg)

**Comment by kamalaknn** [comment]
Hey @Kastamat from the screenshots you have attached it looks like the variable `{{$timestamp}}` is actually resolved as empty. Could you verify if you have an environment or a global variable with the same name as `$timestamp` that might be causing this issue?

**Comment by Kastamat** [comment]
Sorry. This is my mistake
