### ISSUE TITLE
Change default setting during the installation

### ISSUE THREAD

**Issue by wetzesa** [a85/POSTMan-Chrome-Extension#6576]
We install postman on developer clients in a bigger company behind a proxy and with an automated software delivery service to the developers.

Because of this two reasons we have the problem that we would like to give different default parameters during the installation.
It means that we would like to disable the automated update of postman and setup the proxy settings. For other settings it would be nice if we can change them also.

Is there currently a solution to do this during the installation? If not, this is a new feature request ;-)

**Comment by jviotti** [comment]
Closing this ticket as we now offer customized MSI installations for enterprises as part of our Enterprise offering (https://learning.postman.com/docs/administration/managing-enterprise-deployment/). The Enterprise flavor of the app already disables auto-updates and there will be more settings added over time.
