### ISSUE TITLE
'Something went wrong' being thrown in web dashboard

### ISSUE THREAD

**Issue by chrisdeso** [a85/POSTMan-Chrome-Extension#6578]
[Submitted by Postman Support, on behalf of user]

**Describe the bug**
When in the web dashboard interface, clicking on any action throws the error in the screenshot below and a `429 (Too many requests)` can be seen in the browser's console.

**To Reproduce**
1. Navigate to [the web dashboard](go.postman.co) 
2. Log in / wait for redirect
3. Click on any link/button

**Expected behavior**
Navigating within the web dashboard should work as expected and/or errors should be more informational

**Screenshots**
![image](https://user-images.githubusercontent.com/4734306/58200985-a618e280-7c99-11e9-8ef0-ba0216a6285a.png)

![image](https://user-images.githubusercontent.com/4734306/58201270-4838ca80-7c9a-11e9-8235-a65d09322954.png)

**Comment by abhijitkane** [comment]
@chrisdeso Are there any other errors/messages in the console? The 429 is from sentry, an error-reporting service that we use, and is unrelated to the `Something went wrong` message.

**Comment by preethammavin** [comment]
Closing as there isnt enough information to move forward, and as it is not reproducible on our end. Feel free to reopen it if the issue persists.
