### ISSUE TITLE
Ability to mark collection as read-only or unsaved

### ISSUE THREAD

**Issue by m3dbedb** [a85/POSTMan-Chrome-Extension#6582]
**Feature description.**
I use two instances of Postman (portable and regular) for ease of copying snippets from one request to another. It's tiome to time happens that the same collection is opened in two postman windows and I don't remember, in whicj Postman the collection is newer.

**Describe the solution you'd like**
I offer to add checkbox or a lock icon to collection name. If the collection is modified, the lock is drawn opened, and user may click to mark it locked, which means the collection is old or stored to disk.

**Describe alternatives you've considered**
As alternatives I offer:
1. To add user ability to modify favorite collection sign (star) to lock sign in settings and option not to move starred collection to top of the list.
2. Another decision is an option to automatically mark changed collections names (with asterisk * or with italic font as in text editors) as modified until they are not exported to disk.
3. Mark collections, exported to disk with diskette icon. If the collection has been changed, remove diskette sign.

I understand that Postman stores collections on disk, but it's unclear where the file is located, it's uncomfortable that all collection data is stored in one file and there is no verion control.

**Comment by preethammavin** [comment]
@m3dbedb I would like to understand why would want to edit the same collection in two windows. Do you want to copy snippets of code from one request to another of the same collection? If that would be the case, we have introduced forking and merging. 

Internally when we want to evolve the collection we fork the collection and modify it and merge it back. 
If I were to copy snippets of code from same collection. I would fork the collection, make edits to the collection including copying the code snippets from the parent collection , test the forked collection and then merge it back when I am satisfied with the changes.

Let me know if this workflow helps you out.

**Comment by m3dbedb** [comment]
I have two Postman enitities open. I work in one of them and sometimes I copy some code from old collection to new one. Time to time I need to have the 1st collection opened in first instance of Postman, to see some code snippets to copy it to new collection in second instance of Postman. Other time I work on another new collection in first instance of postman and need to see some snippet in old collection opened in second instance of Postman. So old collection is like a library, and it is useful to have it it both instances of Postman. Note that I don't need two versions, the issue is offered to prevent unwanted forks. If I would suddently find some mistake in old collection and fix It, I can forget in which instance of Postman the new version of my collection.

**Comment by preethammavin** [comment]
When you copy the snippets from on window to another, I am assuming you copy over request data? if you are editing the request, the tab is rendered dirty. Would that not indicate which request you were working on?

**Comment by m3dbedb** [comment]
I have two opened Postmans: regular and portable. They keep data separately. If I change some collection request, then save it and close tab, how to find out which Posman have newer version of some collection?

**Comment by preethammavin** [comment]
@m3dbedb we dont officially support Portable, and have little idea of the data management there. 
What I could suggest is opening up a new window of the Postman instance and working side by side, to use the tab feature for requests. You will always have an idea on what request you are working on when the tab is dirty. If you would still want to look at how to organise you workflow better, I personally use workspace. 

I have a personal workspace which is meant for editing, when I am editing I share it to that workspace, when I am done store it in a Team workspace for others to consume. So I keep a workspace for editing collections only, so I know these are being worked upon. 

I understand the use case but the solution which is on the feature request is not something we would implementing , but will keep account of the idea
