### ISSUE TITLE
Increased test execution time

### ISSUE THREAD

**Issue by Nmirontsev** [a85/POSTMan-Chrome-Extension#6584]
I am running Postman native app version 7.1.1. on Windows 10 with 16 GB of RAM.

Our test scenario includes running collections with 300-800 requests for 9 iterations (9 different types of user). Run is done through Runner UI (not in common line). 
After upgrading to 7.1.1. I noticed that when running starting from 3rd iteration Postman started to add delays between requests. On 8th-9th iteration delays can be up to 7 second. 
It goes hand in hand that Postman takes around 5 gb of RAM during such execution and sometimes crashes when using it along with other apps.
Before update running the same collection took 10 minutes. Now - 20-25. 
![PostmanIterations](https://user-images.githubusercontent.com/7813663/58291989-37b14e80-7d85-11e9-92dd-15096521e3d3.png)

**Comment by saswatds** [comment]
We have pushed all of our performance fixed to the stable version 7.18.0. The runner should be snappier and not crash. Can you update to the latest version and check if this issue is fixed for you?

**Comment by saswatds** [comment]
Closing this issue now. Feel free to reopen if the issue persists for you.
