### ISSUE TITLE
Version tags "Learn More" redirects to installation and updates documentation

### ISSUE THREAD

**Issue by deepakpathania-zz** [a85/POSTMan-Chrome-Extension#6586]
**Describe the bug**
The Learn More link for version tag (https://go.pstmn.io/version-tags) redirects to installation and updates documentation.
 
![Screenshot 2019-05-24 at 2 52 39 PM](https://user-images.githubusercontent.com/15071438/58317565-a6e57c00-7e33-11e9-87ca-3ba06f5c5920.png)

**Expected behavior**
The Learn More link should point to the appropriate documentation

**App information (please complete the following information):**
- Native app
- Postman Version Version 7.1.1
- OS: macOS Mojave

**Comment by preethammavin** [comment]
@deepakpathania  the issue has been resolved , thanks for reporting it
