### ISSUE TITLE
postman.setNextRequest not working properly after some requests

### ISSUE THREAD

**Issue by andreagubellini** [a85/POSTMan-Chrome-Extension#6587]
**Description**
I have a collection which runs from GitLab CI and before deploying it I'll usually try it in pm collection runner.

The collection has different calls with the same structure based on the same code with different datasets. Something like the following example:
`call 1
call 2 
call 3
call 4
call 1 
call 5
call 6
call 7
call 1
etc...`
based on "call 1" conditions, the postman.setNextRequest() decides whether to run call 2, 3 or 4 and so on.

The code works fine but the last "loop" (meaning something like: call 1, call 8, call 9, call 10) doesn't work and the postman.setNextRequest() does nothing.

On Newman/Gitlab CI I get the following string: Attempting to set next request to $[collection_name] but the request is not going to be set while on Collection runner I get no errors.

Putting some console logs on the if statements where the code goes returns the logs which means it's working properly but seems that only for the last conditional loop of requests doesn't work.

the code is the SAME for all the requests.

Here's the code snippet that works for all previous scenarios and not for the last one. The only things I change are "checkJobName()" "if strings" and "postman.setNextRequest" requests.
Note that I can clearly see from the log that the script runs into `if (job.status === "idle" && job.validation === "manual" && job.execution === "manual")` code portion, as I get the console log, but skips the postman.setNextRequest function.

`const   jsonData = JSON.parse(responseBody),
        json_identifier = jsonData.stages;

json_identifier.forEach(function cicla(arr) {
    arr.jobs.forEach(function cicla(job) {

    function checkJobName() {
        if (job.name === "premio_manuale") {
            return true;
        }
    }

    if (checkJobName() === true) {
        pm.environment.set("id_job", job.id);
        pm.environment.set("jobName", job.name);
        pm.environment.set("jobStatus", job.status);
        pm.environment.set("jobValidation", job.validation);
        JobStatusPerformer();
    }

    //// check functions 

    function JobStatusPerformer(){
        if (job.status === "success" ) {
                console.log("il job " + job.id + " " + job.label + " è in stato " + job.status + ", vado in idle ");
                postman.setNextRequest("1111");
            } 
            if (job.status === "pending" && job.validation === "manual") {
               console.log("il job " + job.id + " " + job.label + " è in stato " + job.status + " e in modalità " + job.execution + " , avvio il Job Resolve");
               postman.setNextRequest("Resolve_pm");
            }
            if (job.status === "idle" && job.validation === "manual" && job.execution === "manual") {
               console.log("il job " + job.id + " " + job.label + " è in stato " + job.status + " e in modalità " + job.execution + " , avvio il Job Run");
               postman.setNextRequest("Run_pm");
            }
            else if (job.status === "idle" && job.validation === "auto" && job.execution === "auto") {
                console.log("il job " + job.id + " " + job.label + " è in stato " + job.status + " e in modalità " + job.execution + " , attendere l'avvio e risoluzione automatica.");
                postman.setNextRequest("222");
            }
            else if (job.status === "idle" && job.validation === "manual" && job.execution === "auto") {
                console.log("il job " + job.id + " " + job.label + " è in stato " + job.status + " e in modalità " + job.execution + " , il job è in idle, attendere la risoluzione del job precedente. Se già in stato 'success' visualizzare il log errori");
                postman.setNextRequest("333");
            }
            if (job.status === "running" && job.validation === "manual" && job.execution === "manual") {
                console.log("il job " + job.id + " " + job.label + " è in stato " + job.status + " e in modalità " + job.execution + " , avvio il Job resolve");
                postman.setNextRequest("Resolve_pm");
            }
            else if (job.status === "running" && job.validation === "auto" && job.execution === "auto") {
                console.log("il job " + job.id + " " + job.label + " è in stato " + job.status + " e in modalità " + job.execution + " , attendere la risoluzione automatica.");
                postman.setNextRequest("444");
            }
            else if (job.status === "running" && job.validation === "manual" && job.execution === "auto") {
                console.log("il job " + job.id + " " + job.label + " è in stato " + job.status + " e in modalità " + job.execution + " , avvio il Job resolve");
                postman.setNextRequest("Resolve_pm");
            }
            if (job.status === "failed") {
               console.log("lo stato del job " + job.id + " è " + job.status + ". Verificare i log.");
               postman.setNextRequest("555");
            }
            else {
                postman.setNextRequest("666");
            }
    }

    });
});

**App information (please complete the following information):**
 - Native App
 - Version 7.0.7
 - linux 4.15.0-30deepin-generic / x64

**Comment by andreagubellini** [comment]
any update on this one?

**Comment by shamasis** [comment]
@andreagubellini ... we missed triaging this. will post an update asap. @postmanlabs/runtime can you have a look as to what is causing this?

**Comment by codenirvana** [comment]
@andreagubellini Is possible to share a sample collection (without sensitive data) which we can use to reproduce this issue?

**Comment by andreagubellini** [comment]
I'm working on a few mocked requests to let you work on it.
Thanks

**Comment by codenirvana** [comment]
@andreagubellini Closing this issue as we are not able to reproduce this internally and we haven't seen other users facing the same.

Please feel free to reopen if the issue persists or you can help us with the steps to reproduce this issue.

**Comment by saiudayakella** [comment]
@codenirvana  @saswatds @a85 - I'm experiencing this issue with `postman.setNextRequest` when I run the collection (in which order of requests is set) using newman. When I run the same collection using the runner, it works.
Here is the snapshot of the issue with newman:
![image](https://user-images.githubusercontent.com/19469293/91676546-8900de00-eb83-11ea-81ea-0f6de28bf4b4.png)

@andreagubellini  Could you re-open the issue?
