### ISSUE TITLE
Starting download into directory without write permissions appears to be successful

### ISSUE THREAD

**Issue by krichter722** [a85/POSTMan-Chrome-Extension#6592]
**Describe the bug**
Downloading a request response to a directory where the user running postman doesn't have write permissions causes a dialog "Download response" to be displayed. It's green bar on the side makes the saving appear successful, but nothing happens. In some scenario, like write permissions of `snap` packages the search for the file can become a time consuming issue.

**To Reproduce**
1. Open postman as non-root user and request `https://google.de` with GET
2. Click on 'Download'
3. Select `/` as save location or another location in case you have write access to `/` as non-root user
4. A toast "Download response" with a green bar on the side appears

**Expected behavior**
In case the toast label is supposed to indicate that the download started it should be colored neither green (indicating success) nor red (indicating failure), but for example yellow. In case it's supposed to indicate that the download request has been handled its color and label should indicate the outcome success or failure with a comprehensive message.

**Screenshots**
![Bildschirmfoto vom 2019-05-26 13-58-05](https://user-images.githubusercontent.com/4369372/58381534-50587900-7fbe-11e9-9652-2ec72a058fd7.png)

**App information (please complete the following information):**
 - App Type: snap
 - Postman Version: 7.1.1 (84)
 - OS: Ubuntu 19.04

**Additional context**
./.

**Comment by shamasis** [comment]
What is being implied is ... during failure of file write, the toast isn’t showing error.

**Comment by krichter722** [comment]
> What is being implied is ... during failure of file write, the toast isn’t showing error.

@shamasis Is this a question about the behaviour of the program? Or an addition to my proposal how to fix it?

**Comment by shamasis** [comment]
Oops. The latter @krichter722. We need to make the error more visible instead of silently failing.

**Comment by vikiCoder** [comment]
Hi @krichter722,

This issue is fixed in the [latest Postman App](https://www.getpostman.com/downloads/) release (v7.2.1). The app will now show the error message as shown in below screenshot instead of success message while downloading the response in a directory without write access.

<img width="394" alt="Screenshot 2019-06-19 at 11 08 14 AM" src="https://user-images.githubusercontent.com/16588032/59739490-b31df700-9282-11e9-829f-69b672157dd1.png">
