### ISSUE TITLE
Method pm.variables.has wanted

### ISSUE THREAD

**Issue by m3dbedb** [a85/POSTMan-Chrome-Extension#6595]
**Feature description.**
It would be useful to be able to check over all variables scopes if variable exist.

**The solution description**
I offer to add new method pm.variables.has
Like variables  access in the request builder do, it is ggod to have such a method to check if variable exist. Example: test checks if variable passed through data set, and if not, we create global variable and Postman automatically process it with {{variable_name}} keyword.

**Comment by m3dbedb** [comment]
Note that currently (in Postman 7.2.0) there is no warning if you use pm.variables.has to get user know the method is missing.

**Comment by codenirvana** [comment]
@m3dbedb Support for this is already added in our [Canary channel](https://www.getpostman.com/downloads/canary) and will be available in our next stable channel release (v7.3.0) very soon.

**Comment by codenirvana** [comment]
We've added support for this in the latest version of the Postman app (v7.3.4).
