### ISSUE TITLE
"Initial Value" in Shared Environments should be editable only by the team members with "Edit" permissions

### ISSUE THREAD

**Issue by pitersO2** [a85/POSTMan-Chrome-Extension#6596]
Nowadays there is possibility to override initial values by all team members. Wouldn't be better to have some permission system adopted to environment scope? 
Example: Owner of the environment can give Edit/View permissions to column "Initial Value". But team members can still editing "Current Value" what is ok. Therefore all team members have initial value managed by let's say by an admin of environments. It prevents mistakenly changing sensitive data used by the whole team in workspace.

**Comment by vkaegis** [comment]
@pitersO2 Thanks for writing in! Introducing roles on environments is something we're actively working on. No ETA just yet, but will keep you updated.

**Comment by Millais** [comment]
Hey @vkaegis is there any update available for this one?

We're looking for read-only 'initial values' for our enterprise team at PayPal – this feature would really help.

Thanks,
Patrick

**Comment by sankalp0o** [comment]
Just wanted to post an update that we're looking at introducing Roles on environments in our short-term roadmap. There have been some decisions that we have to take to ensure that everyone will be able to adopt this smoothly, and we could use inputs from you!

Should Environment Viewers be able to add new variables to environment?

**Comment by Millais** [comment]
@sankalp0o For our use case we have ~25 environments. Each has a basic set of core variables to start with. As a user progresses through various API requests, transactional/ephemeral variables get added to the environment by pre/post scripts.

Technically for this use case we would therefore expect an environment viewer to be able to add new variables to an environment.

If this was not possible, a workaround would be to simply add the transactional variables to the environment to begin with. (With the role of 'viewer' you probably wouldn't expect the user to be able to modify the environment anyway – beyond adding local current values)

**Comment by pitersO2** [comment]
I think the easiest way to start from is to block initialValues editing for "Viewiers". They can add new variables to environments but can edit only "Current Value" which is not shared across the whole team.

**Comment by sankalp0o** [comment]
Thanks for the feedback guys, will keep you updated about this! Please feel free to reach out with any additional context if it can be helpful to how the feature is designed.

**Comment by vvs11** [comment]
We have released role-based access control on environments with app v7.25. This will give you more control over how you use environments in a team. Please upgrade your app and try it out. Here's the documentation
https://learning.postman.com/docs/postman/variables-and-environments/managing-environments/#working-with-environments-as-a-team

Do let us know your feedback :D
