### ISSUE TITLE
Team workspace : invitation system failing

### ISSUE THREAD

**Issue by skoope** [a85/POSTMan-Chrome-Extension#6600]
**Describe the bug**
Invitation for team workspace not received by collaborators.
1) When inviting a collaborator to workspace, nothing happens, no invitation is received by collaborator.
2) When trying to send a joining link to workspace A, the collaborator is redirected to joing a workspace B

**To Reproduce**
1. Go to 'Workspace A'
2. Click on 'Invite'
3. Click on 'Get link'
4. Copy link and send it to a collaborator/friend
5. The collaborator clicks on the link, he is redirected to a web page for joining a wrong workspace

**App information (please complete the following information):**
 - App Type Native App
 - Postman Version [e.g. 7.0.1]
 - OS: [e.g. Ubuntu 18]

**Comment by bhargavkaranam** [comment]
Hi @skoope,
Could you confirm a few things - 
1. When you try to invite someone to the workspace, after adding the user, on clicking Send Invitations button, do you see any error (as a toast message)?
2. The user you are trying to add, is he/she already a part of the team? If that's the case, the invitation will not be sent to the user, they will be joined to the workspace instead. They will receive a notification in the app that they are added to this particular workspace.

The invite link joining the user to a wrong workspace is something we need to investigate. Could you write to help@getpostman.com about this so that we can investigate further?

**Comment by skoope** [comment]
Hi @bhargavkaranam,
1) After clicking on "Send invitations button", the modal closes and nothing else happens, no errors or toast message.
2) When i invite them to join the team, i have the same behavior (no errors, but nothing happens, they don't receive notification

PS : i tried the same flow with many other accounts, and laptop systems still have the same issue :/

**Comment by bhargavkaranam** [comment]
@skoope, could you also confirm that you're not trying to invite a user who's already part of the team? If the user's already part of the team and you're trying to add him to a workspace, an in-app notification will be sent and not an email.

**Comment by skoope** [comment]
@bhargavkaranam , no the user is not already part of the team.

**Comment by bhargavkaranam** [comment]
@skoope Could you please write to help@getpostman.com from your registered email address so that we can investigate what is going wrong here?

**Comment by bhargavkaranam** [comment]
@skoope 
Could you also please let us know if you're able to invite the user to the workspace from the web dashboard? (https://go.postman.co)

**Comment by bhargavkaranam** [comment]
@skoope,
Since we can't reproduce this on our end, we want to make sure that the issue you're facing is not a bug and would want to sort the issue out for you. Do you mind getting on a quick call so that it'll be faster for us to debug what's going wrong here? Whatever time is convenient for you.

**Comment by skoope** [comment]
@bhargavkaranam yes with pleasure, here's mail email adress so wen can set up the call :
ska@latech.io
Thank you.

**Comment by skoope** [comment]
After the call, i added a collaborator to the team, then invited him into my workspace successfully. Thank you for your reactivity and time.

It was not a bug, but the team workspace system UX is a little confusing. Problem solved.
