### ISSUE TITLE
Please do not redefine industry standard terms

### ISSUE THREAD

**Issue by philmagr** [a85/POSTMan-Chrome-Extension#6605]
Please don't tell me that I have to "sign in to create APIs" because I don't.
I've been developing APIs in postman forever.

Whatever new feature you created, is definitely related to APIs, and definitely should not be called APIs.

Yes. It's marketing. Don't further fragment the discipline of software development just to sell your product. Pretty please?

**Comment by preethammavin** [comment]
@philmagr we are not doing either. We have recently enabled to build out API schemas in Postman, which requires a signed in account as all of the feature the new abstraction of an API in postman enables require online actions. 

On the other hand we do not restrict our users from creating collections and sending requests without being signed-in
