### ISSUE TITLE
Editing the API Publishing flow

### ISSUE THREAD

**Issue by cyrielle-hada** [a85/POSTMan-Chrome-Extension#6606]
**Is your feature request related to a problem? Please describe.**
Users might be confused with the `Add to API Network flow` as it doesn't list the `team description`. Teams may not know that the description shown in the API network listing in the app is the `team description` and not the `API description`.

<img width="1328" alt="Screen Shot 2019-05-28 at 14 35 26" src="https://user-images.githubusercontent.com/47351631/58487078-ec20eb00-815e-11e9-819d-41015ba19d36.png">

Currently, the description displayed under the `API Name` is the `team description` that is set in the [team settings page](https://app.postman.co/settings/team/general). 

<img width="1172" alt="Screen Shot 2019-05-10 at 12 34 54" src="https://user-images.githubusercontent.com/47351631/58487332-5043af00-815f-11e9-8f8b-e8267a973789.png">

**Describe the solution you'd like**
Adding a field called `Team Description` - pre-filled with the description set up in team settings with the option to edit it.

**Comment by preethammavin** [comment]
The issue has been solved, as users and teams publish their public profiles. Which has the description.
