### ISSUE TITLE
Account validation emails sent to users who never sign up for Postman

### ISSUE THREAD

**Issue by Raj-postman** [a85/POSTMan-Chrome-Extension#6609]
**Describe the bug**
Validation emails received by users who haven't created the account.

**Additional context**
We are currently working on this issue and will update users accordingly
Reported by Postman

**Comment by abhijitkane** [comment]
cc @Suhas-Gaikwad

**Comment by postman-kenji** [comment]
@abhijitkane @Suhas-Gaikwad can we close this out with the resolution?

**Comment by ArjunSingh-PM** [comment]
Closing this as this issue has been resolved.
