### ISSUE TITLE
Collection variables do not persist, but globals do

### ISSUE THREAD

**Issue by NeroVanbiervliet** [a85/POSTMan-Chrome-Extension#6610]
**Describe the bug**
Collection variables are not persisted  between requests (when running requests standalone, not running the whole collection) .
This can be the intended behaviour, but it is confusing, as changes to global variables are persistent. 

**To Reproduce**
1. Create a collection and add a request.
2. Add the code below as in 'tests'
3. Open the console (Ctrl+Alt+C)
4. Run the request
5. Run the request again

test code
```js
console.log('collection var = ' + pm.variables.get('token'));
pm.variables.set("token", "1234");
console.log('collection var = ' + pm.variables.get('token'));

console.log('global var = ' + pm.globals.get("token"));
pm.globals.set("token", "1234");
console.log('global var = ' + pm.globals.get("token"));
```

console output of first run
```
GET localhost:4000/login?username=nero
collection var = 
collection var = 1234
global var = 
global var = 1234
```

console output of second run
```
GET localhost:4000/login?username=nero
collection var =        <------ PROBLEM
collection var = 1234
global var = 1234       <------ GLOBALS DO PERSIST
global var = 1234
```

**Expected behavior**
It is not consistent that persistence works differently for collection and global variables.

**App information (please complete the following information):**
 - App Type = flatpak
 - Postman Version = 7.1.0
 - OS = Ubuntu 19.04

**Comment by shamasis** [comment]
Yes. Collection variables are not designed to persist across runs or two separate requests in builder. However within one collection run, updates to pm.variables should be forwarded.

**Comment by NeroVanbiervliet** [comment]
Out of curiosity, what is the advantage of this lack of persistence?

**Comment by shamasis** [comment]
> Out of curiosity, what is the advantage of this lack of persistence?
Prevents accidental mutation of the variables across teams.

@vkaegis if we introduce sessions for collection variables, that would address this. I guess. :-/

**Comment by codenirvana** [comment]
Closing as duplicate of #5053

**Comment by william-wallace-simplisafe** [comment]
The description of a collection variable doesn't jive with the behavior in this bug.
```
Collection variables are available throughout the requests in a collection and are independent of environments. Collection variables don't change based on the selected environment. Collection variables are suitable if you're using a single environment, for example for auth or URL details.
```
