### ISSUE TITLE
GitLab integration - return only 20 projects 

### ISSUE THREAD

**Issue by cyrielle-hada** [a85/POSTMan-Chrome-Extension#6612]
**Describe the bug**
When setting up the GitLab integration on a custom domain, the list of repositories available would return only 20 while the GitLab account contains 100. 

**To Reproduce**
Requirements
-  Have an on-premise instance of GitLab.
-  Have more than 20 projects on GitLab (here ~100)

1. Install the GitLab integration from the Enterprise Postman dashboard
2. Select `Backup your Postman Collections to GitLab on a custom domain`
3. Enter GitLab Personal Token and Gitlab Custom Domain 
4. In the `Backup your Postman Collections` page, **be able to see only 20 GitLab Projects** in the list (out of the 100 existing). 

**Expected behavior**
Be able to view all the GitLab projects in the list. 

**Additional context**
It may be that this problem is due to the GitLab API limitation - returning only 20 projects by default.
If that so, is there any workaround to select a project that is not returned in the 20?

**Comment by cyrielle-hada** [comment]
@preethammavin do you have any updates on this?

**Comment by kartikjain26** [comment]
@cyrielle-hada  The fix is under review. Should be out in next release.

**Comment by harishbarma** [comment]
@kartikjain26 :Thanks for the fix,  Now I'm able to populate all the projects in the dropdown.
@cyrielle-hada you can close the issue.
