### ISSUE TITLE
Update Authorization header token value

### ISSUE THREAD

**Issue by robtown** [a85/POSTMan-Chrome-Extension#6616]
I'm using oauth 2.0 and have no issues getting my token.
My issue is this:
The appended header Authorization value, when using the postman "Get New Access Token", is "Bearer xxxxxxxxxxxxxxxxxx....".
I need that value to be "Zoho-oauthtoken xxxxxxxxxxxxxxxxxxxx..."

I don't see any way to change that value. I've tried Pre-request Scripts to replace the "Bearer" with "Zoho-oauthtoken" but I don't seem to be able to actually update the header.

**Comment by shamasis** [comment]
That field isn’t configurable yet. We have plans to add more configurations down the line.

**Comment by ghost** [comment]
Cant you CHANGE or rather SOLVE this on other ways? 

Adding a pre-script, changing environment varible ? 

?

**Comment by mohitranka** [comment]
This has been released in the lastest Postman app V7.27. Please upgrade and give it a go!
