### ISSUE TITLE
Not able to getResponseCookie value for XSRF-TOKEN

### ISSUE THREAD

**Issue by ggpai** [a85/POSTMan-Chrome-Extension#6617]
**Describe the bug**
I am trying to get the value of XSRF-TOKEN in Tests (Post Request). Postman in returning Null Value.
console.log(postman.getResponseCookie("XSRF-TOKEN").value);
Its working fine in GET Request when i try to get the same value.

**App information (please complete the following information):**
 - Native App]
 - Postman Version Postman v7.1.1 
 - OS: WIndows 10

**Comment by ggpai** [comment]
postman.setGlobalVariable('Xtoken', postman.getResponseCookie("XSRF-TOKEN").value); --> Working fine in Get Request 

When i try to use the same code in Test (Post Request) i am getting below error:
There was an error in evaluating the test script:  TypeError: Cannot read property 'value' of undefined

**Comment by cyrielle-hada** [comment]
Hi @ggpai! You should be able to log cookie values within the app, but you need the interceptor for it to work. We go in further details in our community post on [how to enable the interceptor with the Canary app](https://community.getpostman.com/t/interceptor-integration-for-postman-native-apps/5290).

**Comment by SabriH10** [comment]
Hi @ggpai,

Seeing as it has been a while here, I just wanted to let you know I'll go ahead and close this if that's alright with you. If you still need help, please feel free to re-open this issue, and we'll be happy to help!
