### ISSUE TITLE
Enforce CAN-SPAM Guidelines

### ISSUE THREAD

**Issue by chrisdeso** [a85/POSTMan-Chrome-Extension#6618]
**Is your feature request related to a problem? Please describe.**
With the ability to designate up to five (5) recipients for monitoring summaries, ensuring that emails/templates are in compliance with the CAN-SPAM guidelines is important.

**Describe the solution you'd like**
Enforcing CAN-SPAM guidelines on all Postman-related emails.

i.e. Clear instructions on how to unsubscribe from notifications.

**Additional context**
- CAN-SPAM Guidelines - https://www.ftc.gov/tips-advice/business-center/guidance/can-spam-act-compliance-guide-business

**[Filed by Postman]**

**Comment by godfrzero** [comment]
Both the daily & weekly monitoring summary emails now include a direct link to the notification preferences page, where the user can choose to unsubscribe from one or both of the emails.

**Comment by JP-from-Postman** [comment]
Additional thought: allow users to opt out of individual monitor notifications they are subscribed to, beyond weekly summaries. This should be accessible from the email itself.

Currently, if a user is set to receive notifications for a monitor, the only means of opting out is to remove them in the monitor configuration. Actual example of why this can be problematic:
- User A, on Team A, creates a monitor in their personal workspace
- User B is set to be notified for monitor
- User A leaves Team A
- User B still receives notifications for monitor, but has no control over receiving notifications.

**Comment by chrisdeso** [comment]
Thanks @godfrzero – closing this out!
