### ISSUE TITLE
Switching to build view lags in team workspaces

### ISSUE THREAD

**Issue by deepakpathania-zz** [a85/POSTMan-Chrome-Extension#6621]
**Describe the bug**
Switching from browse view to build view lags a little in team workspaces, lag increases with more collections in the workspace, works smoothly in personal workspaces.

**To Reproduce**
1. Go to browse view of a team workspace.
2. Click on Build toggle to switch to build views. 
3. Notice there is a lag in switching.

**Expected behavior**
Switching should be smooth.

**Screenshots**
![Kapture 2019-05-30 at 13 13 31](https://user-images.githubusercontent.com/15071438/58617049-c1f53780-82dc-11e9-946b-22777084e814.gif)

**App information (please complete the following information):**
 - App Type - Native
 - Postman Version - v7.1.1
 - OS: macOs Mojave 10.14.3

**Comment by mccannt** [comment]
@deepakpathania-zz Are you still experiencing this on the most recent version of the application?
We have made some performance improvements since this was opened and I am not seeing this issue, myself.

**Comment by mccannt** [comment]
Closing this issue out. 
If you are still experiencing this issue, please let us know.
