### ISSUE TITLE
Renaming a request re-triggers filtering in sidebar

### ISSUE THREAD

**Issue by numaanashraf** [a85/POSTMan-Chrome-Extension#6624]
**Describe the bug**
Renaming a request via the tab seems to re-trigger the filter on the sidebar, leading to folders and collections toggling based on the active search filter.

**Expected behavior**
Sidebar folders should not be toggled when renaming.

**Screenshots**
![open_folders](https://user-images.githubusercontent.com/3295568/58637019-3052ed80-830f-11e9-9881-fb554332e24a.gif)

**Comment by arlemi** [comment]
This was fixed in 7.17.0.
