### ISSUE TITLE
APIMatic integration not working

### ISSUE THREAD

**Issue by harsh-reality** [a85/POSTMan-Chrome-Extension#6625]
**Describe the bug**
- The Postman- APIMatic integration does not push anything to the authorized Github account
- The integration has not been working since the last week of April 

**To Reproduce**
- One of the tested use-cases here is: Use APIMatic integration to convert postman collection(s) into an OPI API format. 
- After the integration is added, nothing gets pushed to the Github repo. 

**Expected behavior**
The integration works and saves the resulting file into the designated GitHub repository

**Comment by kartikjain26** [comment]
@harshachelle  @preethammavin This is found to be working in production. Let me know if there is a specific case where it fails consistently.

**Comment by mccannt** [comment]
Issue resolved.
