### ISSUE TITLE
In-app and email notifications for comments in APIs

### ISSUE THREAD

**Issue by cyrielle-hada** [a85/POSTMan-Chrome-Extension#6626]
**Is your feature request related to a problem? Please describe.**
Currently, real-time notifications do not work for comments in APIs. 

**Describe the solution you'd like**
Be notified in-app when being tagged by a team member **in the API Comments sections** (similarly to Collections).

**Comment by sankalp0o** [comment]
Hey Cyrielle, thanks for reporting. Realtime notifications are available now for comments on APIs as well, both in app and emai.
