### ISSUE TITLE
Allow mock servers to be edited after creation

### ISSUE THREAD

**Issue by JP-from-Postman** [a85/POSTMan-Chrome-Extension#6627]
**Is your feature request related to a problem? Please describe.**
Once a mock server has been created, its name cannot be changed. Modifying this requires deleting the mock server, and creating a new one with the desired settings.

**Describe the solution you'd like**
Allow mock server name to be modified after creation.

(if possible) Allow environment and version tag to be modified after creation.

**Describe alternatives you've considered**
None

**Additional context**

**Comment by vvs11** [comment]
We have released this with App version 7.7. You can now edit mock servers after they are created.
