### ISSUE TITLE
Sort order in collection is wrong after sync

### ISSUE THREAD

**Issue by trevor-black** [a85/POSTMan-Chrome-Extension#6631]
**Describe the bug**
The sort order of a collection is incorrect on one machine. We upgraded all to 7 hoping it would fix the issue. It did not.

**To Reproduce**
Not sure why this happens but some items in a collection are out of order. Since the Collection Runner executes in order, tests will fail on one machine and work on another.

If we manually go into Postman using the owner account and move things around it will sync correctly. This is without clicking sync.

**Expected behavior**
We expect that sync should keep the collection in the order designed for all users assigned to that collection.

**Screenshots**
A screenshot showing the issue follows with user collection on the left and owner collection on the right.

![image](https://user-images.githubusercontent.com/22139004/58671806-cfb8b600-82f8-11e9-957f-3b184293194a.png)

**Comparing to the online version**

![image](https://user-images.githubusercontent.com/22139004/58723272-82872380-838e-11e9-8904-ead2a1e68dde.png)

Left = online docs
Right = local Postman

**App information (please complete the following information):**
 - App Type : Native App
 - Postman Version [7.1.1]
 - OS: [Windows 10 Enterprise]

**Additional context**
Hard to recreate an environment where the collection is out of sync for troubleshooting. Painful to have things out of sync in the exact same collection as sort order impacts pass/fail on many tests. Clicking sync in Postman alone does not solve it. The items in the collection need to be moved by the owner in order to fix it.

**Comment by sankalp0o** [comment]
@trevor-black do you (or your teammates) remember doing anything that caused this? We're trying to reproduce this but are unable to do so.

**Comment by trevor-black** [comment]
Only that one person is the owner of a collection. On another machine that
collection has the wrong sorted order. This is stil happening even after a
sync:

[image: image.png]

Left: Team member's machine using Postman 7.5.0
Right: Soure member's machine using Postman 7.5.0

If the owner goes in and changes the sort the new order of the items in the
collection will be picked up.

Thanks,

Trevor

**Comment by pss-miracle** [comment]
We're having a similar issue: 
owner of a collection deletes a request and paste two new requests in a folder. The new request end up in a bottom, but are rearranged to lay at the top of execution within the folder. 
Issue: other team members still see these two at the bottom, restarting their client or syncing doesn't help.

Impact: introducing errors in test as someone might start working on a collection without proper sync and exporting it to source control without noticing it.

**Comment by ankit-m** [comment]
I tried a lot of cases to reproduce this issue (including the steps mentioned by @pss-miracle ). However, I was unable to get the request order out of sync across multiple users.

Can you confirm the following things?
1. The sync icon on top right is orange for both user when you are checking the collection order
2. Signing out and signing back in the app does not resolve the issue.

Also it would be amazing if you could provide a screen recording demonstrating the bug.

**Comment by ankit-m** [comment]
If you are not comfortable posting the information here, please send us an email at help@getpostman.com and we can look into this further.

**Comment by ankit-m** [comment]
Closing this issue due to 7 days of inactivity. Please reopen this issue if you are able to reproduce this consistently.
