### ISSUE TITLE
Environment variables are not loaded on app startup

### ISSUE THREAD

**Issue by shajanjp** [a85/POSTMan-Chrome-Extension#6633]
**Describe the bug**
Environment variables are not loaded on app startup

**To Reproduce**
1. Restart postman
2. Try using any variable

**Expected behavior**
Postman should load environment variables on startup.

**App information (please complete the following information):**
 - App Type : Native App
 - Postman Version : 6.1.4
 - OS: Ubuntu 16.04

**Comment by shamasis** [comment]
Umm 😐... I opened my app and I see the following ... environment drop down with environment and icons to preview and edit - and I can then interact with them. What is happening in your case?

**Comment by shajanjp** [comment]
Yeah same here, my last used environment selected as active by default.
But the values in the environments are empty when I try to use.
![Screenshot from 2019-05-31 14-02-16](https://user-images.githubusercontent.com/2943609/58692710-d143b600-83ac-11e9-974c-763152f9cc45.png)

**Comment by numaanashraf** [comment]
@shajanjp We are having trouble replicating this at our end. Is this happening every time you open the app?

**Comment by shajanjp** [comment]
@numaanashraf 
Not always, only when starting postman after OS restart I believe.
