### ISSUE TITLE
Support colored emojis on all platforms

### ISSUE THREAD

**Issue by javiergarval** [a85/POSTMan-Chrome-Extension#6634]
**Describe the bug**
Using Linux is not possible to show colored emojis in the environment title name. Instead, it shows b/w emojis.

In Mac it properly shows colored emojis in the environment title name.

**To Reproduce**
Just create a environment and add a colored emoji to the title name.

**Expected behavior**
Show environment title names with colored emojis.

**Screenshots**
![image](https://user-images.githubusercontent.com/4655537/58686193-6aa7a380-837e-11e9-8969-67cb49c205fe.png)

**App information (please complete the following information):**
 - Native App
 - v7.1.1
 - Operating System: Manjaro Linux 
KDE Plasma Version: 5.15.5
KDE Frameworks Version: 5.58.0
Qt Version: 5.12.3
Kernel Version: 4.19.45-1-MANJARO
OS Type: 64-bit
Processors: 4 × Intel® Core™ i7-7600U CPU @ 2.80GHz
Memory: 15,5 GiB of RAM

**Additional context**

**Comment by ritwijsinha** [comment]
Hello @javiergarval,

Emojis are just characters that use the standard system font. This means, that depending on what OS the Postman app is running, the look and color of the emoji will be impacted.

Some apps, such as Facebook and WhatsApp, have built in their own variations of emoji that are different from the system font. 

This is not a bug, but something implemented by other apps.

However, try checking out https://emojipedia.org/ on your Linux system. If you see everything colored over there but black and white on Postman app, then it's a bug.

**Comment by DannyDainton** [comment]
Hey @javiergarval 

I'm going to close out this issue for now, if this continues to be a problem for you or other users we can look to open it up again.
