### ISSUE TITLE
Feature Request: Secure variable option

### ISSUE THREAD

**Issue by CReich02** [a85/POSTMan-Chrome-Extension#6639]
### Is your feature request related to a problem? Please describe.
Variable values are suggested to be used for passwords and api keys but when the editor is open anyone can look over your shoulder and view these values that are suppose to be secure.

### Describe the solution you'd like
In the postman variable editor have an option on the variable to mark it as Secure.

#### When a variable is marked as Secure.
1. The 'Initial Value' box could be set to some static placeholder value like 'SECURE', since this is the value that gets synced to the cloud and can be shared with a team it should require an action to set this value.
2. The 'Current Value' box should be like a password box and show ******** for any over the shoulder lookers.  There should also, 1. Be a button available to be clicked that will make the value visible until focus changes, or 2. Make the value visible and editable when you click into the value box.
3. Values for secure variables should should not be able to be exported to plain text files.
4. Secure variables should always be stored encrypted, on the local machine.

### Related posts
Variables stored at rest - https://community.getpostman.com/t/variables-stored-at-rest/5645
Feature Request: Encrypt local variables - https://github.com/postmanlabs/postman-app-support/issues/6638

### Similar requests that are closed
Feature Request: Hidden environment variables for passwords - https://github.com/postmanlabs/postman-app-support/issues/824
Feature Request: Secure environment variables - https://github.com/postmanlabs/postman-app-support/issues/4777

**Comment by vkaegis** [comment]
@CReich02 Thanks for writing in! Adding this to a large list of issues/features around variables we're hoping to tackle soon. No ETA just yet, but we'll keep you updated.

**Comment by dellagustin** [comment]
This is really important.
It should apply to variables in all scopes (Collection, Environment, Global).
Given that one of the recommended use cases of variables is for secrets, I struggle to understand how this was not considered from the beginning.

**Comment by phillijw** [comment]
For us, it would be nice to hide secrets that end up in newman test logs and are outputted to our CI which people can fairly easily see

**Comment by caot** [comment]
A user should be able to hide or set it as hidden stars or something else. If the data is exported, it should be a hash-code, or some encrypted data, or just ignore it. That should be up to user's option. It should be easily implemented. One more column with a checkbox, and some back-end encryption. The issue has been around about 6 years!

**Comment by MyEidos** [comment]
Any updates? A really important feature, I am surprised it is still not implemented...

**Comment by neo00** [comment]
This is definitely a critical feature for those of us who work in enterprises that have strict security requirements. I hope this gets a higher priority than what it is at right now.

**Comment by spencerhuang-oracle** [comment]
I understand that this feature request does not constitute real security. However, sometimes we need to use Postman while recording zoom demo, and not having the ***** on the UI could create accidental leak of password values. It's a low-hanging fruit imho.

**Comment by spencerhuang** [comment]
I understand that this feature request does not constitute real security. However, sometimes we need to use Postman while recording zoom demo, and not having the ***** on the UI could create accidental leak of password values. It's a low-hanging fruit imho.

**Comment by pkarny** [comment]
@postman-support I really love your work and I see that you are quickly implementing new features. 

We adopted postman to our workflows pretty quickly but I was really surprised that the only way of keeping the value of keys/passwords/variables secure is to **remember** that you can **only** fill the "current value" field in variables.

You may think the solution is good enough, but **no**! Please remember that most our your community starts using the product  first and then reads the whole documentation to get something done. This makes collaboration HARD at the beginning because there must be someone trusted who tells the others that they cannot fill the "initial" value for keys/passwords. But this is not all... this person must also keep track on their setting because there is the flag that automatically persists all variables ... which basically means that all passwords are automatically send to you.

It may be a little salty post, but for the 7th year in a row (ref eg. #824), the community is trying to tell you that this is an important issue. Looking at the roadmap... you are thinking differently... it's sad. We don't need things like "Better visibility of sync status" we just want to sleep well with our secrets kept safe and not synchronized with the rest of the world.

**Comment by loopDelicious** [comment]
Lots of people use Postman to demo their own tech in conference talks and customer conversations. I have leaked so many secrets unintentionally on livestreams. It would be helpful to have a Hide / Show toggle where the default is hidden.

**Comment by wvteijlingen** [comment]
This is a very important request imho. The current recommended way of dealing with secrets is just too easy to mess up.

In additional to the original request: it would be very nice if these "secure" variables would be excluded from the "Persist all" button. Postman now suggests using the 'current value' of an env var to store secrets, but it's just to easy to accidentally persist them

**Comment by ghost** [comment]
+1, I make a ton of video tutorials which showcase a set of 4 API credentials for my employer. Scrolling through Environment Variables shows them, even if I moved those variables all the way to the bottom. If there was an option to hide these and show ******, it would make my life (and those who work at my company) a lot easier.

**Comment by k4lli** [comment]
+1, i can't believe this is still a problem. Have to record a quick guide and have to edit the entire video to obfuscate my passwords. and not only that - I am demo-ing a tool that shows passwords in cleartext in the UI - I'm very uncomfortable recommending this to anyone. no other software does that. I wasted a couple of hours looking for the option as I believed I must have done it wrong and now I have to look for alternative (curl if needs be)

**Comment by louagej** [comment]
Yes, please provide masking variables in the postman UI

Maybe the same way as in the collection:
![image](https://user-images.githubusercontent.com/7229592/125073768-bc25cf00-e0bc-11eb-9618-4774f119970c.png)

Can end up like:
![image](https://user-images.githubusercontent.com/7229592/125074429-8fbe8280-e0bd-11eb-8bbc-ce67089b1a9d.png)

**Comment by rob-vandenberg** [comment]
Every time I take a screenshot, I need to photoshop the image to blur the password before sending.
Every time I do a screenshare in Zoom or Meet I have to remember not to show the environment.
Every time a collegue comes to my desk I have to remember to close that window.

Why is this so difficult to do? Just a checkbox or an 'eye' icon or something to show/hide the value. 
It cannot possibly be so difficult that it needs 8 years to implement...

**Comment by malvikach** [comment]
@rob-vandenberg I am sorry to hear about your experience. This ask has been on our radar and we are starting the work on this.

We should be able to make this feature available to you soon(early next year). 

We appreciate you writing to us about it.

**Comment by malvikach** [comment]
We are excited to announce that, with this release (9.7.0) we have shipped the masking feature. 

You can now mark variable type on environment and globals. We support types `default` and `secret` with this release. 

- Type default will appear as plaintext on the screen, while type secret will enable masking of initial and current values of the variables. Variable type secret can be used to store sensitive information such as passwords, keys, tokens and secrets. 

<img width="1350" alt="screenshot_for_git_ticket" src="https://user-images.githubusercontent.com/89449769/147692368-191a2d38-c37b-408d-ba25-49cdae781cc5.png">

- Postman will automatically mark type default for any new variable that is created and for the existing variables. Editors can change the types on existing variables or create new variables with secret types

- You can use the toggle feature to temporarily view the masked values at various touchpoints on app/web (quick look, edit view, set as variable, pop-ups etc)

![masking_video](https://user-images.githubusercontent.com/89449769/147692381-87780880-5aab-4349-a411-7ec31bd8d95d.gif)


We hope this helps increase your productivity and enables you with better security.

**Comment by DannyDainton** [comment]
With V11 of Postman, we have introduced the Postman Vault (https://learning.postman.com/docs/sending-requests/postman-vault/postman-vault-secrets/), which allows you to store your sensitive data in an encrypted local vault that is not synced with the Postman Cloud. Also, we have added multiple security features to help prevent accidental exposure of your API credentials.

**Comment by spektro37** [comment]
Great news! Sadly, to me this long-awaited feature seems to be too late as decision to disable local scratchpad/collections made me migrate to a different API client.
