### ISSUE TITLE
Postman not rendering "Pretty" responses, or showing test results

### ISSUE THREAD

**Issue by akaczinski** [a85/POSTMan-Chrome-Extension#6643]
**Describe the bug**
After sending a request, Postman does not display the response JSON in the normal "Pretty" format. It is only viewable if the "Raw" or "Preview" option is selected. In additon, the "Test Results" page does not show tests, rather just an empty page. It does, however, show the success/failure counts in the tab.

**To Reproduce**
1. Generate a request with an expected JSON response, including tests
2. View the response body
3. View the tests page

**Expected behavior**
The response body should display in the "Pretty" format.

**Screenshots**
![image](https://user-images.githubusercontent.com/42845652/58821014-f290e600-85e8-11e9-9b79-e1aa43203e65.png)
![image](https://user-images.githubusercontent.com/42845652/58821025-fae92100-85e8-11e9-83f4-6d41585fba91.png)
![image](https://user-images.githubusercontent.com/42845652/58821041-04728900-85e9-11e9-81eb-63822f0e1846.png)

**App information (please complete the following information):**
 - PostmanCanary
 - Version 7.1.1-canary05
 - Windows 10

**Comment by shamasis** [comment]
@akaczinski - thanks for reporting. Is this happening for all responses? Can you send us a copy of your logs so that we can check what’s erring?

@saswatds

**Comment by akaczinski** [comment]
Yes, it's occurring across all previously functioning requests/tests.

Which logs would you like? I'm not really sure what data is contained in there so I'm weary about dumping them all at once.

Thanks!

**Comment by saswatds** [comment]
@akaczinski Thanks for reporting this. I have been able to reproduce this and have applied a patch internally to fix this. This should be fixed in the next build.

**Comment by shamasis** [comment]
Thanks @saswatds - you prevent a full conversation round trip between @akaczinski and me! Hoping to release a patch at the earliest.

**Comment by saswatds** [comment]
Hi @akaczinski the single pane view does not seem to have this issue. While we get this fix out, you should be able to use the Single pane view without any issue. 

Really sorry for the inconvenience.

**Comment by saswatds** [comment]
Hi @akaczinski , we have released `7.1.1-canary06` with the fix. Will close the issue after confirmation from your end.

**Comment by akaczinski** [comment]
@saswatds Can confirm the response is displaying, as are the test results. Thank you very much for the quick fix!

**Comment by oliviervanbulck** [comment]
I believe I have the same problem now in Postman v7.20.0. The pretty result isn't updating after a new call when the result is json code.

**Comment by oliviervanbulck** [comment]
NVM, used the version from ubuntu software. Now the latest version and it works!

**Comment by gorkem2020** [comment]
Hello,

issue is still there. tried couple of different browsers. pretty json not working. and it does not refresh the results automatically. I have to switch tabs to force it to refresh

**Comment by abradshaw22** [comment]
Also having the same issue today. Maybe the issue was re-introduced with an update?

**Comment by printergobrrr** [comment]
Unfortunately i am as well having the same issue right now.

**Comment by MicahCG** [comment]
Hi, I am experiencing the same issues.

**Comment by jayudey** [comment]
I am seeing this as well after updating to 7.34.0

**Comment by klmttolax** [comment]
I am now seeing this issue on version  8.0.6 (8.0.6)

**Comment by ronssij** [comment]
same on Version 8.0.7 (8.0.7)

**Comment by emilh91** [comment]
Issue still exists on version 8.0.8. I tried restarting and the issue still exists.

**Comment by alokaroramca** [comment]
Issue still exists on Version 8.0.10 (8.0.10). 

Steps:
Got Update alert,
I did update and it restarted app. And I found Pretty thing stopped working
I restarted again and then saw version update banner and pretty thing started working fine

Seems earlier restart did not do the job right..

**Comment by Tostau** [comment]
I confirm that turning it off and on solved this issue as well

**Comment by jcocca** [comment]
Same issue after upgrading to v8.11

**Comment by AhmedAliHassanElsetouhy** [comment]
@saswatds 
Postman not rendering "Pretty" responses to json when select JSON #6643
issue appear with me at Version 10.13.4

**Comment by TomMunyiri** [comment]
Experiencing the same issue on Mac Postman Version 10.21.14
UI Version: 10.21.14-ui-240108-0708
Desktop Platform Version: 10.21.0 (10.21.0)

**Comment by stodolos** [comment]
I am experiencing the same issue even after an upgrade. If I toggle to Raw, and then back to Pretty, then it works most of the time.

Windows Postman x86_64 10.22.0

**Comment by samarthgulati** [comment]
We have successfully addressed the issue of pretty response not rendering correctly, and it's set to be included in our upcoming release. We will post an update in this thread as soon as the update becomes available.

**Comment by jhon-andrew** [comment]
I am using Postman on VSCode and I'm still experiencing the same issue. Even using it in single-pane didn't solve the issue.

**Comment by rohithrajbingi** [comment]
I face the same issue, @jhon-andrew. I too use the Postman extension on VScode. I checked with 1.2.1 version but the issue persists. I also noticed that request body Beautify also doesn't work.

Please fix this!

**Comment by pankajk07** [comment]
@jhon-andrew @rohithrajbingi The issue seems to be in the underlying Chrome of VSCode (`v1.95.1`). Please have a look at this [issue](https://github.com/postmanlabs/postman-app-support/issues/13230#issuecomment-2458788661) for more details.

**Comment by apinkhasov101** [comment]
<img width="44" alt="Screenshot 2024-12-12 at 3 50 50 PM" src="https://github.com/user-attachments/assets/e42605c3-b3ee-40f5-9505-3c4c7c2232a2" />
I had the same issue. I just clicked this button (that's next to the "Visualize" button) and it seemed to have made it work somehow. Still not sure what this button does though, tbh. Render code, perhaps?
