### ISSUE TITLE
String length problem while using variables in POST request.

### ISSUE THREAD

**Issue by parthpatwala** [a85/POSTMan-Chrome-Extension#6644]
**Describe the bug**
Getting (+1) than actual string length while using a variable in POSTMAN request.
Ex. 
{{host}}/message 
```
{
  "phone": "11111"
}
```
I'm using node js. So by this, I'll get phone.length = 6 instead of 5. 
If I use a full string then I'll get the right result. 
Ex. 
localhost:3000/message 
```
{
  "phone": "11111"
}
```
I'll get string length 5 by this. Which is very weird. I don't know if this is a bug or need to do some setting on my side.

**Expected behavior**
Should get correct string length.

**App information (please complete the following information):**
 - App Type [ Native App]
 - Postman Version [7.1.1]
 - OS: [Windows 10]

**Comment by shamasis** [comment]
This is very odd. Can you double check that the {{host}} variable is actually the same URL as localhost:3000? There’s nothing in Postman that I can think of that can cause this sort of a basic issue.

You may try opening the Postman Console, make one request with variable and one without that and then compare it the two has any difference.

**Comment by parthpatwala** [comment]
I tried with different scenarios and found that when we copy and paste the value from different source instead of manually typing, this happens. 
Closing this issue since it's not a problem with the Postman.
