### ISSUE TITLE
App Closes after Feed Upload Sent

### ISSUE THREAD

**Issue by scottcollins17** [a85/POSTMan-Chrome-Extension#6646]
**Describe the bug**
Application is closing after feed upload is sent; feed is not refreshed.

**To Reproduce**

**Expected behavior**
CVS UAT environment should be refreshed.

**Screenshots**

**App information (please complete the following information):**
 - App Type [e.g. Chrome App, Native App]
 - Postman Version [e.g. 6.0.1]
 - OS: [e.g. macOS High Sierra 10.13.2]

**Additional context**

**Comment by numaanashraf** [comment]
@scottcollins17 Please fill all the details in the template below. Right now, there is not enough information in this issue for us to understand and take action.

**Comment by preethammavin** [comment]
Closing the issue has with the current information , we are not able to deduce the issue. Please feel free to reopen the issue with the required information so that we can get it resolved.
