### ISSUE TITLE
Toggle for configured Postman API keys not visible on mobile

### ISSUE THREAD

**Issue by chrisdeso** [a85/POSTMan-Chrome-Extension#6648]
**Describe the bug**
When viewing the Postman API Integration on mobile, the `Active/Inactive` toggle for API keys isn't visible

**To Reproduce**
1. Go to https://go.postman.co on mobile (or mobile view)
2. Select a workspace
3. Open the Integrations tab
4. Notice that the toggle for existing API keys isn't visible

**Expected behavior**
The toggle should be visible in the mobile view

**Screenshots**

**Mobile View**
![image](https://user-images.githubusercontent.com/4734306/58831348-203e5500-8612-11e9-8c6b-181f4f31e7b7.png)

**Desktop View**
![image](https://user-images.githubusercontent.com/4734306/58831359-27fdf980-8612-11e9-8886-1006ef5f3e93.png)

**App information (please complete the following information):**
 - Browser: Chrome (Mobile & Desktop)

**Additional context**
[Filed by Postman]

**Comment by ArjunSingh-PM** [comment]
@chrisdeso Could you please confirm that the issue is resolved for you. Thanks!
