### ISSUE TITLE
Postman schedule issue

### ISSUE THREAD

**Issue by kafai828** [a85/POSTMan-Chrome-Extension#6649]
Dear all,

I would run the script in the postman client, but when I run the script in schedule.
It will have below error

1 0:03:05 Clear database Cache1 started
2 0:03:05 Login Manager Server copy
3 0:03:05 POST http://localhost:9123/mgmtrestservice/authenticate
4 0:03:05 Error: getaddrinfo ENOTFOUND localhost:9123
5 0:03:05 Get Server group List copy
6 0:03:05 GET http://localhost:9123/mgmtrestservice/servergroupinfo
7 0:03:05 Error: getaddrinfo ENOTFOUND localhost:9123
8 0:03:05 show data cache
9 0:03:05 GET http://localhost:9123/mgmtrestservice/jdbjdatabasecaches?instanceName=DVWEB
10 0:03:05 Error: getaddrinfo ENOTFOUND localhost:9123
11 0:03:05 Clear  DV Database cache
12 0:03:05 DELETE http://localhost:9123/mgmtrestservice/clearjdbjdatabasecaches
13 0:03:05 Error: getaddrinfo ENOTFOUND localhost:9123
14 0:03:05 Clear database Cache1 finished

Would any one would me some information.

Regards
Fai

**Comment by shamasis** [comment]
Hello Fai. From your issue description I am unable to conclude what you’re trying to do and what isn’t working. Can you elaborate?

**Comment by preethammavin** [comment]
Description does not provide enough information for us to look into the issue. Closing the issue for now, feel free to reopen it with the appropriate description so that we can look into the it
