### ISSUE TITLE
Postman crashes when try to run tests in Runner (MacOS)

### ISSUE THREAD

**Issue by WallEnd** [a85/POSTMan-Chrome-Extension#6652]
When i try to run Tests in Runner, application die with log:

`(com.postmanlabs.mac.11408[27546]): Service exited with abnormal code: 1`

I have no idea what happens. I have nothing about this problem in my logs.

**Comment by shamasis** [comment]
Can you provide more info? Running tests on my computer is working fine - so to reproduce this specific case, I would need more information:

1. Which app version and OS version
2. Is it crashing whenever you open runner
3. Is it crashing for all collections or specific ones
4. Can you send the error log files? 

@numaanashraf can you assist in providing info / docs on how and what log files can be sent?

**Comment by WallEnd** [comment]
1. macOS Mojave 10.14.5 (18F203) | Postman 7.1.1
2.It crashing when i'm press "Run"
3. It crashing for any collection i've run
4.I'm so sorry but i don't know where i can find postman crash-log? I need you to help me with it.

**Comment by WallEnd** [comment]
I see this logs when run from terminal
`./Postman
Not disabling GPU
(node:31210) [DEP0061] DeprecationWarning: fs.SyncWriteStream is deprecated.
Main~createDefaultWorkingDir - Default working dir creation already attempted
1559734802265 main info "Booting Postman 7.1.1, darwin-18.6.0 on x64"
1559734802266 main info "EventBus~initialize - Success"
1559734802268 main info "UpdateHandler~init - Success"
1559734802269 main info "RuntimeExecutionService~initialized: Success"
1559734802271 main info "ProtocolHandler~init - Success with status: true]"
1559734802280 main info "PluginHost~bootHost: Booted - 1"
1559734802301 main info "Quitting app"
1559734802306 main error "WindowManager~getSharedWindow: Shared window is not available"
1559734802307 main info null
1559734802315 main error {"name":"Error","message":"PluginHost~hostErrorOrExit: Exited with code null with signal SIGINT","stack":"Error: PluginHost~hostErrorOrExit: Exited with code null with signal SIGINT\n    at ChildProcess.host.on (/Applications/Postman.app/Contents/Resources/app/node_modules/@postman/app-plugins-host/index.js:63:25)\n    at emitTwo (events.js:125:13)\n    at ChildProcess.emit (events.js:213:7)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)"}
1559734802317 main error {"name":"Error","message":"PluginHost~bootHost: Disabling boot since it has exceeded the maximum allowed boot count 2","stack":"Error: PluginHost~bootHost: Disabling boot since it has exceeded the maximum allowed boot count 2\n    at PluginHost.bootHost (/Applications/Postman.app/Contents/Resources/app/node_modules/@postman/app-plugins-host/index.js:26:9)\n    at <anonymous>\n    at process._tickDomainCallback (internal/process/next_tick.js:228:7)"}`

**Comment by WallEnd** [comment]
And i found, that it crashing only when i have JS code in my tests collection

**Comment by saswatds** [comment]
Hi @WallEnd Is it possible that your issue is related to https://github.com/postmanlabs/postman-app-support/issues/4721 ?

If that's the case then we would like to close this issue and keep issue #4721 open as the master issue

Thanks

**Comment by WallEnd** [comment]
> Hi @WallEnd Is it possible that your issue is related to #4721 ?
> 
> If that's the case then we would like to close this issue and keep issue #4721 open as the master issue
> 
> Thanks

It seems that it is!
