### ISSUE TITLE
Unable to set up Slack integration to Monitor a collection

### ISSUE THREAD

**Issue by cyrielle-hada** [a85/POSTMan-Chrome-Extension#6653]
**Describe the bug**
Setting up Slack integration to Monitor a collection throws the error message `The monitor is not shared with your team`. 

**To Reproduce**
1. Select a team workspace you've joined
2. Set up Slack integration `Monitor Run Results` and choose the monitor you want to see the results on Slack  
3. Confirm

![Slack integration Error](https://user-images.githubusercontent.com/47351631/58896412-db87ec00-86ed-11e9-95e8-7773d735dfd1.gif)

**Expected behavior**
Integration created successfully as follows
![Slack integration works](https://user-images.githubusercontent.com/47351631/58895950-f4dc6880-86ec-11e9-9004-02fe0f8ffee2.gif)

**App information (please complete the following information):**
- Web Dashboard
- Postman Version 7.1.1
 - OS: macOS 

**Additional context**
The collection is in team workspace / I am not the collection owner / I have the editor role for the creation in question.

**Comment by JulienSteel** [comment]
Is there any update on this issue? Thank you in advance

**Comment by JulienSteel** [comment]
Any update on this issue?

**Comment by cyrielle-hada** [comment]
@godfrzero @kartikjain26 would you be able to provide some heads-up on this issue? I did reproduce it on my end and it still throws the error.

**Comment by kartikjain26** [comment]
@cyrielle-hada  Let me test this out. Can you make sure the monitor exist in the workspace that you're creating the integration in ?

**Comment by cyrielle-hada** [comment]
> @cyrielle-hada Let me test this out. Can you make sure the monitor exists in the workspace that you're creating the integration in?

I confirm that the monitor exists in the team workspace I have joined. 
However, the collection is owned by another team member (who belongs to the team - so not an access delegation issue) and I do have the editor access on this collection.

**Comment by ankitjaggi** [comment]
@cyrielle-hada We have found the bug causing this issue. We'll release a fix for this soon, and keep you updated.

**Comment by cyrielle-hada** [comment]
@ankitjaggi @kartikjain26 initial reports indicate that it's been fixed! 🎉Thank you!
Closing this issue.
