### ISSUE TITLE
Collection owner unable to recover a deleted collection from a team's workspace

### ISSUE THREAD

**Issue by labifrancis** [a85/POSTMan-Chrome-Extension#6654]
**Describe the bug**

When a collection is deleted from a team workspace by another team member who isn't the owner of the collection, the collection gets missing and the owner of the collection can't find it in the trash.   

**To Reproduce**
1. Create a collection in a team workspace
2. Another team member with an editor role should delete the collection

**Expected behavior**
The collection should be in the trash with an option to restore.

**App information (please complete the following information):**
 - App Type Native App
 - Postman Version 7.1.1

**Comment by preethammavin** [comment]
The issue has been fixed so closing the issue, feel free to reopen it if it isn't so
