### ISSUE TITLE
Custom Webhook for Monitor Run Results incorrectly shows no available monitors

### ISSUE THREAD

**Issue by matt-ball** [a85/POSTMan-Chrome-Extension#6655]
**Describe the bug**
No monitors are visible in the "Select" drop down box when creating a Custom Webhook for monitoring results, despite there being monitors within the workspace.

**To Reproduce**
Go to create a new webhook - see that the drop down list is empty.

**Expected behavior**
Drop down populates with all monitors available in the workspace.

**App information (please complete the following information):**
Monitor:
1e9716c9-8f3c-4530-aae5-f98f2a601c32?job=1e986210-aadd-4d00-b99d-bbce7b0c6657

Workspace:
3f180650-0a31-475a-a765-f00a19b8f906

**Additional context**
Also tried recreating the monitor from scratch, but this didn't show up in the list either.

Zendesk 32798

**Comment by godfrzero** [comment]
We've isolated the issue and are working on a fix. I'll post here once we've pushed it out.

**Comment by godfrzero** [comment]
A fix for this was pushed out around June 23rd and we've been monitoring the system. Closing this ticket as the issue has been resolved now.
