### ISSUE TITLE
Generate code snippets for examples

### ISSUE THREAD

**Issue by zgirod** [a85/POSTMan-Chrome-Extension#6656]
**Describe the solution you'd like**
I would like the ability to generate code snippets for examples.  It is cool that I can generate code snippets for my requests however if I have a particular example I want to generate a code snippet for I cannot do that.

**Describe alternatives you've considered**
There isn't a good workaround.  I guess you could copy the request and modify to conform to the example but that is annoying to have to do that each time.

**Comment by DannyDainton** [comment]
You can create code snippets from examples in the latest version of the platform.

<img width="2621" alt="image" src="https://user-images.githubusercontent.com/17089546/177342488-24648c5e-9ce3-4c0d-b8ab-4d8017ee072a.png">
