### ISSUE TITLE
Add ability to fork & merge environments

### ISSUE THREAD

**Issue by yossarian123** [a85/POSTMan-Chrome-Extension#6657]
There is currently no ability to fork or branch environments.  This is pretty critical for our workflow.  
We use our collection runs in our CI/CD pipelines as a quality gate.  These runs are using the collections on "master".  This allows us to prevent regression - whenever we deploy a new or modified microservice we run the postman collections to make sure we didn't break anything.  Having the ability to fork a request allows our developers to make changes to a collection without impacting those CI/CD pipelines.  Forks are merged only when all of the changes have been verified not to break things.  

There is currently not the same functionality for environments - this means that environments can be modified by any collection or any fork.  This allows breaking changes to be easily introduced into the regression test executions.  

The way I'd imagine this would work:

- environments would have roles & permissions (the same as collections & workspaces).  So we could set team members to have read-only access on environments with the ability to create forks.
- in the app, if a change was needed in an environment file a fork could be created and this could be reviewed and tested in isolation.  Another option would be to automatically create a forked environment whenever the collection is forked so that when a merge takes place both collection & env are merged simultaneously as a unit. 
- once tested, the environment could be merged by somebody with the correct permissions.

**Comment by yossarian123** [comment]
I'm wondering if the following would be a better approach, I mentioned it in passing in my original issue.  
When user creates a collection fork, all environments in that workspace are automatically branched along with the collection.  Then when edits can be made to both env & collection - when the changes are ready to be merged they're merged as a single transaction.

**Comment by sankalp0o** [comment]
@yossarian123 Thanks for reaching out! 
Environment permissions are something we're already looking at. One direction it might take is for "Viewers" to only have the ability to change the Current (local) value of a variable and only "Editors" to be able to change the Initial (cloud) value. While we haven't decided if this is how it'll work, it sounds like it will solve some of your use case.
We don't have an ETA for this as there are some other changes to environments that we're considering (which will make your workflow even easier). I'll notify you when there are any updates.

**Comment by sankalp0o** [comment]
@vkaegis @preethammavin Forking/merging for environments might be worth looking into. I recall some older issues about people duplicating environments and wanting to see a diff between two environments.

**Comment by simonireilly** [comment]
I think this would be a great feature for people developing multi-tenanted applications.

The idea of having a base environment where I can store my access tokens etc. then forking that for two Tenants, so I can perform requests for a specific Tenant would be ideal.

Currently, I have to duplicate my environments and then try and keep them in sync, so :+1: for a feature like those described above.

**Comment by danielkohatwork** [comment]
@sankalp0o: The [approach you commented](https://github.com/postmanlabs/postman-app-support/issues/6657#issuecomment-499597696) appears to not be applicable to running things locally?

**Comment by sankalp0o** [comment]
@danielkohatwork the approach I suggested would allow you to use the environment locally without being allowed to make changes to the shared environment. Is there a particular use case that you have in mind? @vvs11 is looking at tackling this behaviour right now and it would be useful to have some more  validation.

**Comment by Kcorb95** [comment]
Is there any updates on this feature? It's still being mentioned by users in the community. 😓
https://community.postman.com/t/what-happened-to-sharing-a-collection-environment-across-workspaces/29088

**Comment by ankitjaggi** [comment]
We released the ability to fork and merge environments with support of Pull Requests in the latest update.
https://blog.postman.com/introducing-environment-forking-and-pull-requests/

We would love to hear your feedback if this solves the problem you were facing.
