### ISSUE TITLE
User receiving status 400 error when clicking Leave your existing team

### ISSUE THREAD

**Issue by JP-from-Postman** [a85/POSTMan-Chrome-Extension#6658]
[Reported by Postman Support, on behalf of original user]

**Describe the bug**
1. User is already on team A 
2. User receives an invite to join team B.
3. User clicks on the invite link, and gets the following message:
`You are already part of a Pro team called “Team A”.`
4. User clicks on the ‘Leave your existing team’ link, receives a status 400 error page.

At least one affected user is on a team that hasn't yet migrated to RBAC, and is attempting to join another team that _has_ migrated to RBAC.

Tested this using direct invite links (both teams already migrated to RBAC), and I haven't been able to duplicate the behavior. In fact, using an invite link to join one team while still a member of another doesn't present any prompt about an existing team at all.

**To Reproduce**
- Unknown

**Expected behavior**
- Clicking "Leave existing team" link is successful
- Joining new team is successful

**Screenshots**
N/A

**App information (please complete the following information):**
 - App Type: Native app
 - Postman Version: 7.1.1
 - OS: macOS, Windows

**Additional context**
See internal notes

**Comment by godfrzero** [comment]
@JP-from-Postman The issue name and description don't match, one is about custom domains and the other is about switching teams. 🤔

**Comment by JP-from-Postman** [comment]
@godfrzero Updated. Was writing another bug previously and left the title. :P

**Comment by chrisdeso** [comment]
Adding a relevant screenshot here – the link that is throwing `400` error is being thrown when a user is rerouted to the web dashboard from an invitation, is currently part of a different team and clicks on the `Leave your existing team` link.

![image](https://user-images.githubusercontent.com/4734306/59458351-dad31200-8ddf-11e9-8c82-ec02701eb8de.png)

![image](https://user-images.githubusercontent.com/4734306/59458436-0eae3780-8de0-11e9-8e4f-dcb1d90705a3.png)

**Comment by chrisdeso** [comment]
@ankit-m Closing this out as we've pushed a fix for the redirect!
