### ISSUE TITLE
my collections view is not visible in the app.

### ISSUE THREAD

**Issue by yaeldonner** [a85/POSTMan-Chrome-Extension#6660]
**Describe the bug**
while launching postman in my computer when i logged in, i cannot see and work with my collections through the app(side bar is missing) when i press "show sidebar" nothing happen. the collection view is not visible. i cannot add requests. 

**To Reproduce**
1. open postman 
2.see that the sidebar is not visible
3.try to add request, not working

**Expected behavior**
every time i open postman via my computer, i will be able to see the collection in my sidebar collection view, add new requests. and do basic postman stuffs.

**Screenshots**
![image](https://user-images.githubusercontent.com/48644909/58968499-d34bb180-87be-11e9-88f7-a08b24196001.png)

**App information (please complete the following information):**
 - App Type [Native App]
 - Postman Version [7.1.7 (latest)]
 - OS: [ Windows 10]

**Additional context**
please help me solve that. it limit all my daily work

**Comment by saswatds** [comment]
@yaeldonner You are currently in the `Browse` mode. You need to switch to the `Build` mode. 
You should be able to see the toggle button the Bottom-Right corner of the screen.
