### ISSUE TITLE
File reference is lost in form-data upon saving a new request into a collection

### ISSUE THREAD

**Issue by saswatds** [a85/POSTMan-Chrome-Extension#6662]
**Describe the bug**
When saving a request into a collection, if the request has a file-reference as form-data then the file reference gets lost. This does not happen if the request already exists as part of a collection

**To Reproduce**
1. Open a new tab
2. Author a new request with form-data type body
3. Select a file using the file-selector
4. Save the request into a collection
5. See file reference being lost

**Expected behavior**
The file reference should be persisted after saving the request

**Screenshots**
![form-data-file](https://user-images.githubusercontent.com/8796447/58975771-63035700-87e3-11e9-9e12-279d8b3d29c3.gif)

**App information (please complete the following information):**
 - App Type:  Native App
 - Postman Version- 7.1.1
 - OS: macOS Mojave 10.14.5

**Additional context**
*Filed By Postman*

**Comment by codenirvana** [comment]
Fixed in the latest version of the Postman app (v7.6.0).
