### ISSUE TITLE
Unable to access environment variable in Request Body. 

### ISSUE THREAD

**Issue by SivaPrasad186** [a85/POSTMan-Chrome-Extension#6665]
I have set an environment variable in one of my API's. The variable is accessible in sub sequent API URL's but not in their body content. In the screenshot, this is clearly visible. Could you please let me know why this is happening? 
<img width="675" alt="Screenshot 2019-06-06 at 12 01 38 PM" src="https://user-images.githubusercontent.com/48505922/59011692-1fe0cc80-8853-11e9-893b-9b038320cb62.png">

**Comment by numaanashraf** [comment]
@SivaPrasad186 Is the value not resolved while sending the request?

**Comment by SivaPrasad186** [comment]
@numaanashraf Nope. It is not resolving. Getting this error. 

{
    "message": "Invalid request body"
}

To add to it, the request body type (raw) I am using is **Text** for my API.

**Comment by numaanashraf** [comment]
@SivaPrasad186 We are having trouble replicating this at our end. Did you type in that raw body or copy paste it from any other location? 

Postman v7.1.1
<img width="670" alt="Screenshot 2019-06-11 at 5 59 46 PM" src="https://user-images.githubusercontent.com/3295568/59272087-d76e4800-8c72-11e9-8b95-342b82aed2eb.png">

**Comment by SivaPrasad186** [comment]
@numaanashraf  Were you able to use the environment variable in your body content? When the body is of type "Text" ?  Instead of JSON(application/json)

**Comment by numaanashraf** [comment]
@SivaPrasad186 IF you use type 'Text', the environment variable will not be highlighted, but it will still be replaced with the variable value when the request is sent out. Could you verify whether the request that is sent from Postman has the variable replaced? You can check this via the Postman Console (View > Show Postman Console)
