### ISSUE TITLE
Request body not generated from API that has schema defined

### ISSUE THREAD

**Issue by wonboyn** [a85/POSTMan-Chrome-Extension#6666]
**Describe the bug**
A collection generated from an API that uses Swagger/OpenAPI v2 that has request body schema definitions does not generate requests with a matching request body

**To Reproduce**
1. Create an API
2. Import the schema from a file using OpenAPI v2 that has a request with a request body schema definition such as:

...
      "post" : {
        "tags" : [ "Payee" ],
        "summary" : "",
        "operationId" : "createPayee",
        "consumes" : [ "application/json" ],
        "produces" : [ "application/json" ],
        "parameters" : [ {
          "name" : "X-Fred-Authorization",
          "in" : "header",
          "description" : "This service invocation requires authentication.",
          "required" : true,
          "type" : "string"
        }, {
          "in" : "body",
          "name" : "body",
          "required" : true,
          "schema" : {
            "$ref" : "#/definitions/Payee"
          }
        } ],
        "responses" : {
          "200" : {
            "schema" : {
              "$ref" : "#/definitions/Response_Payee"
            }
          }
        }
      },
...

3. Save the definition
4. Generate the collection
5. Check the request for Payee POST & the request body is not populated in any way.

**Expected behavior**
Request payload to be populated with environment variables matching the required request payload based off the schema.

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version: 7.1.1
 - OS: macOS 10.14.5

**Comment by abhijitkane** [comment]
@wonboyn We'll be releasing an update to the Swagger2 importer soon. For now, you can check out our open-source converter (https://github.com/postmanlabs/swagger2-postman2) - this should generate a Postman Collection with examples.

You'll need to add a description to each response, though - that's a required property.

**Comment by abhijitkane** [comment]
@wonboyn This has been updated in Postman 7.2.1. For the Petstore Swagger2 spec (https://petstore.swagger.io/v2/swagger.json), you should see the request body generated from the schema. Closing this for now.

Feel free to add a comment if you're still seeing issues.
