### ISSUE TITLE
Sync doesn't update public documentation

### ISSUE THREAD

**Issue by JaanusR** [a85/POSTMan-Chrome-Extension#6668]
After i merged collection changes to team collection some of the request and folders were missing from published documentation. Whats wierd is that desktop postman shows everything correct with all of the requests and folders but web documentation is messed up. 

I feel like that syncing broke after i made changes to exsisting request. It was easier for me to just delete request and create new one with the same name. Merge process ends up with two requests with the same name after i pull changes from team collection and merged new stuff into it. 
After that if tried to merge something then merge page doesn't finish loading and nothing happened. 

My solution for the missing request and folder issue was to create just dummy folder to the team collection then all the missing folders synced to public documentation, then i used same method for the missing request inside the folder where i put them in.

**Comment by preethammavin** [comment]
@JaanusR this is weird, can you give me a steps that you took to reach this state so that I can try to reproduce this.

**Comment by JaanusR** [comment]
1. Create fork from team collection
2. Removed one of the request and added similar with the same name
3. Added multiple new folders with multiple requests
4. Start merging changes
5. Pulled changes from team. Had conflicts chose my changes on top of team changes
6. Cancelled merging, made more changes. Then i found out that i have two request with the same name under folder(same request i deleted in 2. step). I delete one of them again.
7. Reordered folders, moved some request around
8. Start merging again
9. Because of this deleted request portman offered pull again, so i did the same way like in step 5.
10. After successful pull finished merging

**Result**: everything looks OK in desktop version of postman but there are many things missing from public documentation.

I haven't tried to reproduce it again, maybe im missing something else i did...

**Comment by preethammavin** [comment]
@JaanusR everything looks on on the team collection in the app? but not in the public documentation? 
 
That is definitely weird, can you write to us at help@getpostman.com with the collection name from your registered email id so that we can take a closer look?

**Comment by preethammavin** [comment]
Closing the issue as with the current information we are unable to triage this, feel free to reopen the issue with the information so that we can get it sorted.
