### ISSUE TITLE
Ability to log runner requests to postman history

### ISSUE THREAD

**Issue by m3dbedb** [a85/POSTMan-Chrome-Extension#6670]
**Feature request description.**
It is hard to work with request data in text mode in console after collection run

**Describe the solution you'd like**
I propose to add ability to store runner requests to Postman history

**Comment by vkaegis** [comment]
@m3dbedb Thanks for writing in! We're looking at better ways to integrate request and run history, definitely something on our roadmap. No ETA just yet, but stay tuned for updates.

**Comment by m3dbedb** [comment]
it looks like the feature is implemented
