### ISSUE TITLE
API-Network in-app and on the website are out of sync

### ISSUE THREAD

**Issue by juliatetrud** [a85/POSTMan-Chrome-Extension#6672]
**Describe the bug**
The in-app API Network and web-based API Network are not in sync. The APIs should be listed in the same order and render the same information, but this is not happening. 

**To Reproduce**
1. Go to https://www.getpostman.com/api-network/
2. Click on "Business Solutions"
3. Open the app and press the "New" button
4. Select "API Network"
5. Click on "Business Solutions"
6. Compare

**Expected behavior**
The app and website for API Network should render the same information in the same order. 

**Screenshots**
Website API Network - 
<img width="1494" alt="Screenshot 2019-06-06 11 58 15" src="https://user-images.githubusercontent.com/34220625/59063341-bcf43300-885c-11e9-99ae-88971ac27c13.png">

App API Network - 
<img width="1533" alt="Screenshot 2019-06-06 11 58 30" src="https://user-images.githubusercontent.com/34220625/59063367-cc737c00-885c-11e9-8720-14be5370d0ad.png">

This is how the API Network in-app is supposed to look according to the [docs](https://www.dropbox.com/s/gk4khttkk3d52pz/Screenshot%202019-06-06%2013.13.21.png?dl=0) - 
<img width="670" alt="Screenshot 2019-06-06 13 13 21" src="https://user-images.githubusercontent.com/34220625/59063459-00e73800-885d-11e9-9db3-885d1066374e.png">

**App information (please complete the following information):**
 - App Type - Native 
 - Postman Version - 7.1
 - OS: macOS

**Comment by preethammavin** [comment]
@juliatetrud  we are working on getting the API network to be more extensible, we will be unifying the experience both in app and dashboard. Closing the thread for now.
