### ISSUE TITLE
Postman not syncing

### ISSUE THREAD

**Issue by ebabel-eu** [a85/POSTMan-Chrome-Extension#6674]
Postman is not syncing.

1. Go to Postman desktop app
2. Click on 'Sync
3. See error in DevTools console:

![Screenshot 2019-06-07 at 06 55 57](https://user-images.githubusercontent.com/4309770/59082083-97653900-88f1-11e9-9286-2653b18eae04.png)

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version 4.4.1
 - OS: macOS Mojave 10.14.5

**Comment by sujayvenaik** [comment]
Hey @ebabel-eu 
We recommend updating to the latest version i.e. [v7.1.1](https://www.getpostman.com/downloads/) and try again.

**Comment by ebabel-eu** [comment]
It worked, thanks!
