### ISSUE TITLE
Dropdown not accessible when no tabs open

### ISSUE THREAD

**Issue by sarthak-sehgal** [a85/POSTMan-Chrome-Extension#6676]
**Describe the bug**
Dropdown menu is not accessible when no tabs are open and the left sidebar is closed.

**To Reproduce**
1. Close all the open tabs
2. Close the left sidebar (Cmd+\)
3. In the tabs section, click on the ellipsis (...) to open the dropdown.

**Expected behavior**
The dropdown should not overflow from the window.

**Screenshots**
<img width="1440" alt="Screenshot 2019-06-07 at 1 37 53 PM" src="https://user-images.githubusercontent.com/29003134/59090135-889a7880-8929-11e9-8888-3c4766f5a8d3.png">

**App information (please complete the following information):**
Postman for Mac
Version 7.1.1
OS X 18.2.0 / x64

**Comment by ankurdengla** [comment]
This issue has been fixed in Postman v7.8.0.
