### ISSUE TITLE
Cannot scroll workspace dropdown using mousepad

### ISSUE THREAD

**Issue by vkaegis** [a85/POSTMan-Chrome-Extension#6677]
**Describe the bug**
I can't seem to scroll through the workspace dropdown list using gestures on the mousepad. It scrolls the tab in the background instead.

**To Reproduce**
1. Open the Workspace dropdown
2. Try to scroll the workspace list

**Expected behavior**
The workspace list should scroll.

**App information (please complete the following information):**
 - App Type [Native App]
 - Postman Version [7.1.1-canary05]
 - OS: [Windows 10]

**Comment by numaanashraf** [comment]
@vkaegis Could you provide a screen recording? Not able to replicate this on 7.1.1-canary07 windows build.

**Comment by numaanashraf** [comment]
@vkaegis Is this still happening?

**Comment by vkaegis** [comment]
This is not reproducible in recent versions
