### ISSUE TITLE
Something Went Wrong Vendor-Shared Library

### ISSUE THREAD

**Issue by nardoguy14** [a85/POSTMan-Chrome-Extension#6679]
**Describe the bug**
fails to open, displays something went wrong

**Screenshots**
<img width="1081" alt="Screen Shot 2019-06-07 at 2 15 53 PM" src="https://user-images.githubusercontent.com/4164460/59134041-c3eb7600-892e-11e9-908c-7c22cae50dcb.png">

**App information (please complete the following information):**
 - native app
 - Postman Version 7.1.1
 - OS: Mac OS Mojave

**Comment by preethammavin** [comment]
hey @nardoguy14 can you write us the steps which led to this state?

**Comment by preethammavin** [comment]
Closing the issue has with the current information , we are not able to deduce the issue. Please feel free to reopen the issue with the required information so that we can get it resolved.
