### ISSUE TITLE
Server Sent event testing

### ISSUE THREAD

**Issue by shankyty** [a85/POSTMan-Chrome-Extension#6682]
Hi,
How to handle server side events, in postman/newman.
Handling and verifying all events(including data close).
Regards,
shanky_ty

**Comment by vikt0rs** [comment]
@tegomass it sounds really tricky. Could you please show any example of this approach?

**Comment by ClaudetteShepherd** [comment]
+1

**Comment by milos-savic** [comment]
+1

**Comment by Bradeskojest** [comment]
+1

**Comment by discrete-projects** [comment]
<details>
  <summary>
  off topic
  </summary>
I was having a very similar problem in regard to Postman support for other protocols. A few friends and I went ahead and created an API development tool called Swell. It's an electron application that enables developers to test API endpoints served over modern networking technologies including Server-Sent Events (SSE), WebSocket, and HTTP2. We're looking for beta-testers and contributors (it's an open source project).

The repo is here: https://github.com/getswell/getswell.
The project website is: http://www.getswell.io/
</details>

**Comment by ritman-us** [comment]
will this feature this be implemented in the near future ?

**Comment by nixuewei** [comment]
It really helps if postman support SSE function. waiting for good news in the near future.

**Comment by GSamuel** [comment]
We use postman a lot and recently started using SSE. It would be really helpfull if postman supports SSE.

**Comment by fabiohbarbosa** [comment]
+1 for SSE support

**Comment by akaskj** [comment]
+1

**Comment by BrianARice** [comment]
+1 I agree this would be super useful!

**Comment by larsduelfer** [comment]
+1 We are also looking for a solution to test SSE requests

**Comment by asdirc** [comment]
I am interested too, let me know if you need any help with the implementation.

**Comment by dhiralpandya** [comment]
+1

**Comment by dhiralpandya** [comment]
Hi Team 

Any plan to add this feature  ?

**Comment by devdilson** [comment]
+1 looking foward this feature.

**Comment by Caromeen** [comment]
+1

**Comment by ckw142** [comment]
+1

**Comment by ghost** [comment]
+1

**Comment by davy-vr** [comment]
+1

**Comment by mkbg8** [comment]
+1

**Comment by zoraida** [comment]
will this feature this be implemented in the near future ?

**Comment by llioor** [comment]
+1

**Comment by alizahid4004** [comment]
+1

**Comment by mcgreevyd** [comment]
+1

**Comment by vdantuluri** [comment]
+1

**Comment by manelme** [comment]
+1

**Comment by mohit-sentieo** [comment]
+1

**Comment by Toerktumlare** [comment]
2 years later, this has still not been implemented
+1

**Comment by mohit-sentieo** [comment]
Can anyone from the Postman Team provide some steps on how to implement this ? Maybe somebody can contribute this feature.

**Comment by Michael-List** [comment]
+1

**Comment by bparthu** [comment]
+1

**Comment by Holly-Marie** [comment]
+1

**Comment by mathudak** [comment]
+1

**Comment by Gosunet** [comment]
+1

**Comment by anadollu** [comment]
+1

**Comment by ottonagy** [comment]
+1

**Comment by badgolim** [comment]
+1

**Comment by lfgcampos** [comment]
+1

**Comment by discernment** [comment]
+1

**Comment by badrdami** [comment]
+1

**Comment by lefeudelavie** [comment]
+1

**Comment by irenemp-tel** [comment]
+1

**Comment by bparthu** [comment]
> This can be done using newman as node module plus the [ws](https://www.npmjs.com/package/ws) module. The goal is to open a websocket as a subprocess then use newman to send request/event, then capture and write the event sent into a file or whatever and finally modify the output report to add this information helped by the newman [triggers](https://www.npmjs.com/package/newman#newmanrunevents).
> It's a bit tricky but at least it works. 😃

@Tegomass
I guess the WS uses different protocol and [SSE](https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events) uses HTTP protocol with "text/event-stream" response header to keep the connection open and streams data from server. Unlike WS, after establishing the connection, data flow is uni-directional (always from server to client)

I would love to see a sample using WS and newman to achieve the same. :)

**Comment by dinbtechit** [comment]
👍👍👍👍👍👍

**Comment by dinbtechit** [comment]
**For example** here is how you test ServerSent events using curl.

**Sender :** (In most cases this would be a server)
```
curl -v -X POST http://localhost:8080/sampleApp/server-sent-events --data "custom-message: Hello World!" -H "Content-Type: text/event-stream"
```

**Receiver** (In most cases this would be a client)
```
curl -v -X GET http://localhost:8080/sampleApp/server-sent-events -H "Content-Type: text/event-stream"
```

**Comment by gerardo-cauich** [comment]
+1

**Comment by pdebuitlear** [comment]
+1

**Comment by TheSalarKhan** [comment]
+1

**Comment by bendeitch** [comment]
+1

**Comment by tuxtor** [comment]
+1

**Comment by renearias** [comment]
+1

**Comment by dkirrane** [comment]
related OpenAPI spec issue https://github.com/OAI/OpenAPI-Specification/issues/396

**Comment by hsargsyan** [comment]
Any updates on this?

**Comment by billy93** [comment]
Any updates on this?

**Comment by burketyler** [comment]
+1

**Comment by mr-agrwal** [comment]
+1

**Comment by valeriu33** [comment]
+1

**Comment by lucaskatayama-mb** [comment]
+1

**Comment by lucaskatayama** [comment]
+1

**Comment by ThaDaVos** [comment]
Any progress on this?

**Comment by MichaelLiss** [comment]
any progress?

**Comment by vishnukantraman** [comment]
+1

**Comment by mkapiczy** [comment]
+1

**Comment by thiagotrentin** [comment]
+1

**Comment by alexh2o17** [comment]
+1

**Comment by shankyty** [comment]
@kunagpal, It have been 3 year ... probably you should close it.

**Comment by BrianARice** [comment]
I would prefer they fix it, rather than close this issue.

**Comment by rodrigopavan** [comment]
+1

**Comment by ewhipp** [comment]
+1

**Comment by spyro2000** [comment]
+1

**Comment by minsk-kot** [comment]
+1 please

**Comment by pavel-luhin** [comment]
+1 please

**Comment by tboily** [comment]
+1

**Comment by Freeed21** [comment]
+1

**Comment by shankyty** [comment]
+1

**Comment by ThaDaVos** [comment]
Please stop with the +1 comments... - if you're also interested please add a thumbs up to the main issue comment above...

**Comment by stock-dd** [comment]
Well... are there any plans to add this in Postman? 179 upvotes would trigger some reaction yesno?

**Comment by FedorOvchinnikov** [comment]
Any progress?

**Comment by estiventhneira** [comment]
Nothing here?

**Comment by seanquijote** [comment]
Any update?

**Comment by RuhulxD** [comment]
Anyone responsible for open issues?

**Comment by lorenzoserranti** [comment]
+1

**Comment by mchandschuh** [comment]
Hmmm... seems like the community overwhelmingly wants this. What's the cause for not providing this feature? Is there a technical limitation? I think if the core contributors lay out their concerns the hive mind would be able to come up with a solution.

Go go gadget hive mind!

**Comment by ManeeshaSenarath** [comment]
+1 on this

**Comment by RaviTejaKomma** [comment]
+1

**Comment by enhsaihan-d** [comment]
+1

**Comment by MBetters** [comment]
+1

**Comment by mforastier** [comment]
+1

**Comment by diogojpb** [comment]
+1

**Comment by abhieshekumar** [comment]
Much needed.

**Comment by Jacek-Korniak** [comment]
+1

**Comment by parzival418** [comment]
+1

**Comment by cy-lhe** [comment]
+1

**Comment by entropylost** [comment]
What is the reason why people aren't working on this?

**Comment by danieledevincenti** [comment]
4 years without a response, this must be a record. Also I'll add myself to the list of people interested in this feature

**Comment by shamasis** [comment]
Don't loose hope @Napan0s

We are making this happen. We just released beta support for WebSockets. See #4009. Once we settle in on the UX of the same and figure out how to overlay it on HTTP/2 without making things complex, we will do SSE. 

Please "upvote" on the issue to express interest and comment around your use case and how you'd like to use SSE support - that's what you will actually help us speed this up. (And more feedback when we release beta, is what helps most.)

**Comment by mseankelly** [comment]
+1

**Comment by awangku92** [comment]
+1

**Comment by fidesachates** [comment]
+1

**Comment by jnsw** [comment]
+1

**Comment by ART515** [comment]
+1

**Comment by shyboylpf** [comment]
+1 pls.

**Comment by max-abclabs** [comment]
+1

**Comment by chrisjaimon2012** [comment]
+1

**Comment by philipc-dat** [comment]
+1

**Comment by trip-dat** [comment]
+1

**Comment by amitw-vmware** [comment]
+1

**Comment by bFanatic** [comment]
+1

**Comment by arcziby** [comment]
+1

**Comment by fengjian1993** [comment]
emmmmm.... still in developing?

**Comment by ghost** [comment]
Still waiting for the feature.. +1

**Comment by alexbernotas** [comment]
Waiting for this feature

**Comment by EoinFalconer** [comment]
+1

**Comment by danielpce** [comment]
+1

**Comment by LadghemSaid** [comment]
+1

**Comment by pablohaedo** [comment]
+1

**Comment by janioxavier** [comment]
+1

**Comment by ax-golubev** [comment]
+1

**Comment by walterdumba** [comment]
+1

**Comment by berkayclk** [comment]
+1

**Comment by mehdi-wb** [comment]
+1

**Comment by springADAM** [comment]
+1

**Comment by Boyen86** [comment]
+1 This is a must have for us

**Comment by Gragx** [comment]
+1 this would be incredibly helpful with some SSE trouble I am currently facing.
Am trying to determine why the client is not receiving events and all I get in e.g. Chrome dev tools is a pending connection and eventuelly an error stating that the MIME type was wrong. With no avenue of accessing the response with the invalid MIME type.

**Comment by ahsf** [comment]
+1

**Comment by ThaDaVos** [comment]
I just unsubscribed because of all the `+1` spams and no longer using Postman

**Comment by Korgys** [comment]
+1 looking for this feature

**Comment by luisjimenez6245** [comment]
+1

**Comment by Boufahja** [comment]
+1

**Comment by dberchtold** [comment]
+1

**Comment by ed0001tt** [comment]
+1

**Comment by emrivero** [comment]
+1

**Comment by ljfh** [comment]
+1

**Comment by jimp100** [comment]
+1

**Comment by doraemonxxx** [comment]
**+1**

**Comment by venkata-mi** [comment]
+1

**Comment by ghostebony** [comment]
+1

**Comment by rymesaint** [comment]
+1

**Comment by iranbrg** [comment]
+1

**Comment by GrinOleksandr** [comment]
+1

**Comment by Basuliic** [comment]
+1

**Comment by IKQR** [comment]
+1

**Comment by shadow-cs** [comment]
It would be cool if Postman showed any data as they are being received from the server. It doesn't need to format them just show plaintext value (formatting can be done as soon as the request completes).

Right now when testing SSE I either have to make the server terminate the connection (in which case I see the data) or click Cancel which usually just shows an error without any data (even though plenty of data has been received).

This would give us basic support for SSE and first-class support (tabular output + formatting of `data` nodes) could be added later 😉.

**Comment by Efim27** [comment]
+1

**Comment by mihir-epifi** [comment]
+1

**Comment by maradanasai** [comment]
++1

**Comment by ye-fujin** [comment]
+1 ;)

**Comment by IrynaStep** [comment]
+1

**Comment by david-idelji** [comment]
I'm wondering why this feature is still not implemented.. After 5 years!!

**Comment by alibenmessaoud** [comment]
+1

**Comment by fabriciormartins** [comment]
+1

**Comment by YaozhongZhang** [comment]
＋1

**Comment by Muzammil98** [comment]
Wow, i graduated from my university and this is still not resolved. 😅

**Comment by shankyty** [comment]
> Wow, i graduated from my university and this is still not resolved. 😅

Hehe, even I was wondering same. It have been so long I created this bug.

**Comment by wrd0** [comment]
+1

**Comment by Danushka96** [comment]
+1

**Comment by danipenaperez** [comment]
+1

**Comment by streunerlein** [comment]
+1

**Comment by ollio** [comment]
+2

**Comment by SaadKaleem** [comment]
+1

**Comment by huydinh210299** [comment]
+1

**Comment by cianoid** [comment]
+1 to SSE support

**Comment by balajisa09** [comment]
+1

**Comment by herisn23** [comment]
+1

**Comment by FranckL01** [comment]
+1

**Comment by marcusalexandre** [comment]
+1

**Comment by sephh** [comment]
+1

**Comment by sergei-durkin** [comment]
+1

**Comment by george-hutanu** [comment]
(prev) => prev++

**Comment by ygricks** [comment]
+1

**Comment by ilesar** [comment]
+1

**Comment by yinan-symphony** [comment]
+1

**Comment by moravcik94** [comment]
+2

**Comment by BrandonEscamilla** [comment]
+3

**Comment by johnkhansrc** [comment]
+1

**Comment by cotontigeh** [comment]
+1

**Comment by Mohamad-Kamar** [comment]
+1

**Comment by FranckL01** [comment]
+1

**Comment by quriaakash** [comment]
+1

**Comment by howarddsouzaw** [comment]
+1

**Comment by HadurIII** [comment]
+++++++++++++++++++++++++++++++++++++1

**Comment by grostirolla1** [comment]
+1

**Comment by OmairLiaquatAli** [comment]
+1

**Comment by jarnsida** [comment]
+1

**Comment by appurva21** [comment]
Hey everyone! 👋🏼 

We know it's been a while since the request for Server-Sent Events support came up, but the wait is finally over!

In the last few years, Postman has enabled support for debugging and testing various new protocols, such as [WebSocket](https://blog.postman.com/postman-supports-websocket-apis/) and [gRPC](https://blog.postman.com/postman-now-supports-grpc/), which helped us create a solid foundation for Postman to be a multi-protocol API client.

And now, in the next few weeks, we'll start rolling out the support for debugging SSE. Here is a sneak peek of the same:

![server sent events](https://user-images.githubusercontent.com/24985700/216517795-a31150fe-b700-4295-9774-6c0d9d7d17e5.gif)

Stay tuned for further updates!

**Comment by arlemi** [comment]
Hey there! 

The experience shared by @appurva21 above is now available to everyone. Update Postman (should be at least v10.10) and try it yourself. 😀

**Comment by hburrichter** [comment]
Thank you Postman-Team!

It works great for some SSE endpoints I found online!

However, I tried to implement a Server-Sent Events endpoint using FastAPI/Starlette with the built-in [Starlette StreamingResponse](https://www.starlette.io/responses/#streamingresponse) and the [SSE-Startlette GitHub repo](https://github.com/sysid/sse-starlette) and neither of them produced the new streaming UI in Postman.

Any Idea on what might be the reason or how I can fix/debug this?

Thanks in advance!

**Comment by freesme** [comment]
> Hey there!
> 
> The experience shared by @appurva21 above is now available to everyone. Update Postman (should be at least v10.10) and try it yourself. 😀

Hi! is there any difference between the Windows and the macOS version？I get this effect on mac, but it doesn't work as expected on Windows.
Do I need to adjust some settings on my version of Windows? 👀
-Windows11,postman v10.12 @arlemi

**Comment by appurva21** [comment]
Hey @freesme! It seems to be working fine on Windows.

![image](https://user-images.githubusercontent.com/24985700/231446718-ba88507f-eaf5-445c-a2de-b6dec633b8e4.png)

Are you in the scratch pad on your Windows machine? Support for testing server-sent events is only available for signed-in workspaces as of now.

**Comment by freesme** [comment]
@appurva21 Thanks ，it's working after signed💡

**Comment by vvyushmanov** [comment]
Hi!
My apologies for repluing to a closed issue, but I could not find any info.
Is there any way to automate some scripts triggering based on the received events?

The simplest example - my server is sending a ping every n seconds, awaiting a pong in response.
Therefore, I need a way to implement such logic (i.e. if (pm.receivedEvent.contains("ping")) {pm.send...} )
![image](https://github.com/postmanlabs/postman-app-support/assets/111231219/515df2e3-f6c1-4c16-8e6a-411dff8415be)
