### ISSUE TITLE
Workspace / Collections disappear when the owner/creator is removed from team

### ISSUE THREAD

**Issue by chrisdeso** [a85/POSTMan-Chrome-Extension#6685]
**Describe the bug**
Upon removing a user from a team – the workspaces they had created (and the associated collections) are reported to be going missing. 

More specifically – a collection that's associated with a team is shown as being synced/shared but is nowhere to be found by the users of the team in question.

**To Reproduce**
I haven't been able to reproduce the behavior and the information provided may not be _entirely_ accurate with regards to what actually happened.

1. Remove a user
2. See that the shared workspace(s) they had created – and any collections associated with the workspace – are no longer accessible to the team.

**Expected behavior**
Upon removing a user from a team, their content (collections, workspaces) should remain accessible to the wider team as some of the content may be needed for day-to-day work.

**App information (please complete the following information):**
 - API Version: 1
 - Postman Version: 7.1+

**Additional context**
[Filed by Postman] – Additional content within associated ticket(s)

**Comment by preethammavin** [comment]
We have pushed fixes for the same, closing the issue for now, feel free to reopen it if it isn't so.
