### ISSUE TITLE
Unable to remove members from Team

### ISSUE THREAD

**Issue by chrisdeso** [a85/POSTMan-Chrome-Extension#6690]
**Describe the bug**
Large team administrators are seeing an error message when attempting to remove users from a team, leaving them unable to manage their own teams. 

**To Reproduce**
1. Go to `https://go.postman.co/team`
2. Hover over the user you'd like to remove
3. See a generic error message – `Failed to remove the user from the team. Our engineers have been notified and are working on this.`

**Expected behavior**
The user should be removed and/or a more informative message should be rendered indicating the steps/options users have to accomplish what they're looking to do.

**Screenshots**
![image](https://user-images.githubusercontent.com/4734306/59229480-239c8800-8ba0-11e9-9f74-d764c116ba9d.png)

**App information (please complete the following information):**
 - Postman API: 1
 - Browsers: Chrome / Edge / Firefox

**Additional context**
 [Filed by Postman]

**Comment by preethammavin** [comment]
@chrisdeso we have pushed a fix which optimises this flow, should not be happening anymore. Closing the issue for now, do feel free to reopen it if it occurs again.
