### ISSUE TITLE
Unable to delete Postman account

### ISSUE THREAD

**Issue by ash007-postman** [a85/POSTMan-Chrome-Extension#6691]
**Describe the bug**
Unable to delete Postman account via settings from the web dashboard

**To Reproduce**
1. Go to Settings
2. Click on "Delete Account"
4. Comes back to the login page

**Expected behavior**
The account should get deleted after clicking on "delete account"

**App information (please complete the following information):**
 - App Type [e.g. Chrome App, Native App]
 - Postman Version [e.g. 6.0.1]
 - OS: [macOS ]

**Additional context**
Get the same behavior on Chrome (75.0.3770.80), Firefox (66.0.2) and Safari (12.1.1). 

<img width="1194" alt="Screenshot 2019-06-11 at 6 17 26 AM" src="https://user-images.githubusercontent.com/41741228/59235768-a2310e00-8c10-11e9-947a-0bdbd6723992.png">

**Comment by preethammavin** [comment]
@ash007-postman the account is deleted and later he is taken to that screen. We will work on the messaging to inform the user with a confirmation.

**Comment by ruescar** [comment]
Hi. I was the one who originally reported the bug. Just FYI, the account does not get deleted. So it is not just about the way this action gets confirmed.

**Comment by preethammavin** [comment]
@ruescar I am able to delete the account, just dont see the confirmation email. Can you try deleting the account again and try signing in. 

Note: if you sign-in via google, it creates an account for you if you dont have any. We can also check if your account has been deleted on our end once you confirm the action

**Comment by ruescar** [comment]
@preethammavin Ok. I think we have solved the mystery, which is my misinterpretation on how the sign up/cancel account workflow works. Signing in via google happens so quick and smooth without any confirmation, that you don't realise that a new account is created under the hood. To prove my account was deleted I created a new Postman workspace, then I deleted the account, then I signed in again via google and the new workspace wasn't there. I guess a delete account confirmation email would be nice from the user experience point of view. I guess this issue can be closed. Thanks!

**Comment by preethammavin** [comment]
We will be looking into why the confirmation is not shown to the user.

**Comment by deemhristov** [comment]
Heyall, I am currently having this issue where, after sign in, I get back to the Delete account page, and nothing seems to have happened. My data is still there (at least my profile pic, as I manually deleted everything else before that), I can sign out and then in, etc. Should this ticket be re-opened or a new one created?
