### ISSUE TITLE
Restore button doesn't appear under Activity feed

### ISSUE THREAD

**Issue by Raj-postman** [a85/POSTMan-Chrome-Extension#6692]
**Describe the bug**
Unable to see the Restore button under the Changelog from Application

**To Reproduce**
1. Expand the collection
2. Click on ChangeLog Tab
3. Scroll down to restore any changes made earlier
4. Restore button is missing

**Expected behavior**
Be able to restore the changes made earlier

**Screenshots**

![Capture](https://user-images.githubusercontent.com/47771757/59248080-010d7c00-8c3f-11e9-9a5f-118d6db297b4.png)

**App information (please complete the following information):**
 - App Type - Native App
 - Postman Version - v7.1.1

**Comment by sankalp0o** [comment]
@Kurmavathar thanks for reporting this! 
I suspect that the user might not have edit permissions on the collection, hence she/he is not seeing the "Restore" option. Can you ask them to check if this is the case? One way to check would be to look for a "lock" icon next to the collection name in the sidebar.

**Comment by Raj-postman** [comment]
@sankalp0o Yes, the issue was with the permissions
