### ISSUE TITLE
Postman Web dashboard does not load up in Internet Explorer 11

### ISSUE THREAD

**Issue by Cazaimi** [a85/POSTMan-Chrome-Extension#6693]
**Describe the bug**
After singing into the Postman dashboard, a blank screen is all there is. On opening the browser console, an error is displayed. (Can be found below in the screenshots section).

**To Reproduce**
1. Go to the Postman Web dashboard 
2. Sign in/Sign up
3. Blank screen is displayed

**Expected behavior**
The postman web dashboard should be displayed after the sign in.

**Screenshots**
#### Blank-screen
![Screenshot 2019-06-11 at 1 19 13 PM](https://user-images.githubusercontent.com/13660453/59253310-88f98300-8c4b-11e9-942a-699c5465aeda.png)

#### Errors
![Screenshot 2019-06-11 at 1 12 05 PM](https://user-images.githubusercontent.com/13660453/59253224-5e0f2f00-8c4b-11e9-8f5c-3e1a9f6c2641.png)
![Screenshot 2019-06-11 at 1 11 40 PM](https://user-images.githubusercontent.com/13660453/59253225-5e0f2f00-8c4b-11e9-9aab-5dd0a05234f2.png)

**App information (please complete the following information):**
 - Internet Explorer `11.1715.14393.0`
    - Update Version `11.0.46 (KB4036586)`
 - OS: Windows Server 2016 Datacenter

**Comment by dhineshwiz** [comment]
hey @Cazaimi thanks for reporting the issue, will fix it soon

**Comment by dhineshwiz** [comment]
The issue has been fixed
