### ISSUE TITLE
Mock Server Support For Path Variables 

### ISSUE THREAD

**Issue by workabyte** [a85/POSTMan-Chrome-Extension#6695]
**Describe the bug**
when creating a Mock server using a collection that leverages path var the route is not able to be determined when making calls to the mock instance

**To Reproduce**
1. create collection leveraging path variables. example: {{url}}/users/:userId/favorites  
2. publish mock server
3. post to mock server with value provided for the :userId path var
4. mock server can not determine the route to use

**Expected behavior**
path variables should be treated as part of the rout so that you do not need to maintain 2 separate collections

https://stackoverflow.com/questions/56510540/postman-mock-with-path-variables?noredirect=1#comment99609687_56510540

**App information (please complete the following information):**
 - App Type Postman for Windows
 - Postman Version Version 7.1.1
 - OS: win32 10.0.17134 / x64

**Comment by vvs11** [comment]
Hi @workabyte , thanks for reaching out. 
As per the functionality of mocks, you have to make a collection and create an example of the API which you want to mock. The mock server will mock the example as it is. In your case, you'll have to create an example and provide a value for the variable for which you want a response. For instance, in the example API , put a value '1234' against the variable :userId. Now, when you call the API '{{url}}/users/1234/favorites' you'll get a 200OK response from the mock server.
You have to set the values of variables in example to use mocks.
Please let us know if you need more info on this.

**Comment by workabyte** [comment]
I see so the :var will get expanded when creating the mock server as long as there is a sample value in the collection?

**Comment by vvs11** [comment]
@workabyte :var will work as long as there is an example in the collection with a specific value assigned to :var
