### ISSUE TITLE
Allow pop-out of Environment Quick Look view

### ISSUE THREAD

**Issue by philmagr** [a85/POSTMan-Chrome-Extension#6696]
**Is your feature request related to a problem? Please describe.**
I like to look at my variables, but they're hidden all the time and require a click to display, a scroll to bring into view, and then some human-eyeball-based filtering to find my variable.

This is inefficient, and my eyeballs hurt enough already. The computer should be doing this job.

**Describe the solution you'd like**
Allow the Environment Quick Look view to be opened in a new window.

BONUS POINTS: Allow me to hide most of my variables from this new view since only 1-2 really need to be copied on a regular basis.

Technically filtering isn't needed if I can have all of my variables on a screen without scrolling, as I could rely on muscle memory to retrieve the variable.

**Describe alternatives you've considered**
Putting it on the UI somewhere? Not enough space for anything, really.

A function that sets a value into the user's clipboard would also satisfy my requirements to copy variables & paste them into other tools.

**Comment by vkaegis** [comment]
@philmagr Thanks for the feedback! We've been working on a couple of features around variables to better solve this problem. No ETA just yet, but stay tuned for updates.

**Comment by tomservo3428** [comment]
I would also love to see this GUI update in a future release. Opening the Environment Quick Look window each time I'd like to view/update a variable only adds one click to the process, but it's an extra click that I wish I didn't have to make. 

Having the ability to add the Quick Look window somewhere in the GUI or, similar to the Postman console, have it as a separate window would make viewing and/or managing just a bit more user-friendly.

The quick look improvement aside, I love the app. Whenever we bring in interns or new employees, this is one of the first tools I recommend they get. Keep up the good work! :]

**Comment by giridharvc7** [comment]
Environments can now be opened in a fullscreen view. Please let us know if this solves your issue.
