### ISSUE TITLE
Sometimes can't save variable value

### ISSUE THREAD

**Issue by philmagr** [a85/POSTMan-Chrome-Extension#6697]
**Describe the bug**
When the current value is null, you cannot save a new value in the environment quick look screen without pressing the enter key.

**To Reproduce**
1. Click on Environment Quick Look
3. Scroll down to a variable that already exists but has a current value that is null
4. Click pencil to edit
5. Put a value there
6. Click elsewhere on the screen

**Expected behavior**
Value persists.

**Additional context**
This works if there is already a value there.

**Comment by vkaegis** [comment]
@philmagr Thanks for writing in. Could you let us know the version of the Postman app you're using, as well as the operating system you're running it on? 

Would be swell if you could add a short GIF showing us what exactly is happening.

**Comment by philmagr** [comment]
I'm running on Windows, and this seems to be somewhat intermittent - this happens way way more often than the one case above. Current postman version is 7.2.0 and it still happens there, though I reported this in 7.1.1 or something like that.

In every scenario when the value doesn't get saved, there's a red border-box around the variable value as if it's failing some sort of validation. If I can mouse around until the box is no longer highlighted it saves fine.

Do you have a recommendation of a tool I should use to record video?

**Comment by DannyDainton** [comment]
Hey @philmagr 

I'm unable to reproduce this issue in the latest version of the platform. If this is still an issue for you we can look to reopen it, if you provide a short recording. For now, I'm going to close it out.
