### ISSUE TITLE
Put request works with duplicate key at the json body

### ISSUE THREAD

**Issue by Sirine-LBC** [a85/POSTMan-Chrome-Extension#6698]
**Describe the bug**

POSTMAN sends put request with duplicate key in json body
**To Reproduce**
1. Create a PUT request using JSON body containing duplicate key
2. See error
3. Send the request
4. The response is 201 Created

**Expected behavior**
POSTMAN doesn't send put request with duplicate key in json body

**Screenshots**
![image](https://user-images.githubusercontent.com/51717483/59294052-d2b09080-8c80-11e9-9a06-50fb3480f337.png)

**App information (please complete the following information):**
  - Postman Version [Version 7.1.1]
 - OS: [win32 10.0.17134 / x64]

**Additional context**

**Comment by shamasis** [comment]
Postman is a debugging tool. It allows all forms of request and even malformed ones so that developers can identify issues with client or server. Postman would try highlight the problem but is designed to not stop you from sending it.
