### ISSUE TITLE
Postman response header UI does not preserve whitespace.

### ISSUE THREAD

**Issue by rwdennis** [a85/POSTMan-Chrome-Extension#6699]
We have an API that is attempting to return a custom HTTP header with data similar to the following:

{"dynamicTicket":"#DynmSysTckt-Ovrd-Edit-Strc                03023520874000000554      023520874000007678      023520874000745419      "}   (note - this doesn't post correctly in the issue either - there should be multiple spaces between each component of the string)

I have confirmed that this is what is being returned correctly from the API, but Postman is stripping all of the extra whitespace and this is what we end up getting:

{"dynamicTicket":"#DynmSysTckt-Ovrd-Edit-Strc 03023520874000000554 023520874000007678 023520874000745419 "} 

This value is a fixed position string and because Postman is stripping the extra whitespace, subsequent attempts to parse it are failing.  Postman should either NOT modify the contents of header fields or it should provide an option to turn it off.

**Comment by shamasis** [comment]
To clarify, this data is returned as a value of a header field? Also can you use the three backtick markdown formatting to post your original data?
```
notice    How spaces   Are preserves here.
```

Meanwhile, I’m assuming you have a data like above in header and the white spaces in them are stripped. With this assumption, I will do some tests to replicate the issue and get back to you.

**Comment by shamasis** [comment]
Found the issue! It is in UI alone. Will fix it.

**Comment by vikiCoder** [comment]
We have updated response headers UI and made it identical to request headers editor UI (but with read-only mode) in the latest version of the Postman app (v7.3.4). The new UI will show multiple spaces in headers as it is without stripping it. Below is a screenshot of the same.

<img width="1179" alt="Screenshot 2019-07-23 at 6 50 47 PM" src="https://user-images.githubusercontent.com/16588032/61715554-fc2e0300-ad7a-11e9-918e-51fc618f3a0b.png">
