### ISSUE TITLE
Clean up environment variables after used for multiple routes

### ISSUE THREAD

**Issue by ericknguyen** [a85/POSTMan-Chrome-Extension#670]
It would be nice to have a way to clean up environment variables, and to have a new fresh run every time with a complicated scenario on multiple routes.

**Comment by dipeshoffice** [comment]
Hi All,

I have a requirement of getting the value from the Header request and using it in a variable in POSTMAN.

Ex: when we perform oauth 2.0, we get the Authorization token.
That authorization token we can either use at URL or at Header.
If we are using the Authorization Token at the Header, i want to get that value and automatically set it in the environment variable.

So basically i want in my code:
 1. Auth_token= Postman.GetRequestheader("Authorization')
 2. Postman.setEnvironmentVariable("Authorization",Auth_token).

However, i am not able to figure out how can i get my code 1 corrected.

Please help.
