### ISSUE TITLE
Option to filter out some field in body that could freeze the Postman (Base 64)

### ISSUE THREAD

**Issue by GTHell** [a85/POSTMan-Chrome-Extension#6700]
The Postman freeze out whenever there's a field contain large or multiple data like Base64.

**To Reproduce**
1. Just do a request for any large Base64 or multiple Base64.

** OS **
Macbook Pro 2017

**App information: **
 - Postman Latest Version

**Comment by numaanashraf** [comment]
@GTHell Could you send us a sample request or collection we use to replicate this case?

**Comment by preethammavin** [comment]
Closing the issue has with the current information , we are not able to deduce the issue. Please feel free to reopen the issue with the required information so that we can get it resolved.
