### ISSUE TITLE
Matching collection example depending on request body parameters doesn't work

### ISSUE THREAD

**Issue by Graveheart** [a85/POSTMan-Chrome-Extension#6702]
**Describe the bug**
Setting up the `x-mock-match-request-body` header returns "We were unable to find any matching requests for this method type and the mock path, '/api/authenticate', in your collection."

**To Reproduce**
1. Add an example to a mocked collection request with POST method and body parameters
![Screenshot 2019-06-12 at 09 47 19](https://user-images.githubusercontent.com/6318562/59332853-7c326900-8cf7-11e9-9874-e39a9f3aa135.png)

2. Make a request to your mock API with the exact same body parameters and  `x-mock-match-request-body` header with value `true`
![Screenshot 2019-06-12 at 09 47 42](https://user-images.githubusercontent.com/6318562/59333021-d4696b00-8cf7-11e9-9e0f-86afe382fb83.png)
![Screenshot 2019-06-12 at 09 48 00](https://user-images.githubusercontent.com/6318562/59333034-d6cbc500-8cf7-11e9-98c2-4b8ebaeddfa0.png)

3. You get `mockRequestNotFound` error every time

**Expected behavior**
Get matching response to your example

**App information (please complete the following information):**
 - App Type Native App
 - Postman Version 7.1.1
 - OS: OS X 18.6.0 / x64

**Comment by Graveheart** [comment]
The same thing works now for some reason

**Comment by vvs11** [comment]
Hi @Graveheart , Thanks for reaching out.
We don't have support for form-data in body matching for mocks. All the other body parameters are supported

**Comment by Graveheart** [comment]
Thanks for the reply @vvs11. I just found this header mentioned another Github issue but I didn't see it documented anywhere. Are you planning to implement something like that in the future?

**Comment by vvs11** [comment]
@Graveheart we don't have a plan to support form-data right now. You can use the other body paramaters

**Comment by Dhembla** [comment]
Hey @Graveheart 👋
We have added support for body matching on text fields for form/data content type. Please give it a try and let us know if that works for you. 🙇
