### ISSUE TITLE
Removing User breaks Public Documentation

### ISSUE THREAD

**Issue by aamir-ahmed** [a85/POSTMan-Chrome-Extension#6703]
**Describe the bug**
1. User A belonging to Team A publishes Documentation A for a collection in Workspace A
2. Admin for Team A removes User A from Team
3. You get a 403 error when you navigate to the published Documentation A link.

**To Reproduce**
1. Admin creates a Team A and adds User A
2. Admin creates a Team Workspace A and add User A
3. User A creates a collection and publishes Documentation A for the collection
4. Admin for Team A removes User A from Team A
5. You get a 403 error when you navigate to the published documentation link

**Expected behavior**
The Documentation published by a user should be visible even after the user has been removed from the Team

**App information (please complete the following information):**
 - Native App
 - 7.1.1
 - Windows

**Comment by godfrzero** [comment]
We've pushed out a fix for this and verified that it works.
