### ISSUE TITLE
Web Dashboard throwing permission error and forever-loading 

### ISSUE THREAD

**Issue by chrisdeso** [a85/POSTMan-Chrome-Extension#6704]
**Describe the bug**
When accessing the team dashboard, the interface won't load (spinning wheel) and a permission error is thrown in the browser's Javascript console.

`You do not have access to this workspace`

**To Reproduce**
1. Go to https://go.postman.co/
2. Sign in
3. See spinning wheel – open Javascript to see permission error

**Expected behavior**
- The loading animation should end and the page should render – with or without permission errors as needed.

- Account-specific pages should render, i.e. https://go.postman.co/settings/me

**Screenshots**
![image](https://user-images.githubusercontent.com/4734306/59401143-635d9e00-8d5f-11e9-891e-e69d61f89e65.png)

**App information (please complete the following information):**
 - Browsers: Chrome & Safari

**Additional context**
[Filed by Postman] – Not reproducible locally

**Comment by sankalp0o** [comment]
Hi @chrisdeso , we've fixed this issue. Can you confirm? If the user is still facing this, please reopen the issue and let us know.
