### ISSUE TITLE
GraphQL body doesn't sync across devices

### ISSUE THREAD

**Issue by sirio3mil** [a85/POSTMan-Chrome-Extension#6705]
**Describe the bug**
I have a project in one Windows device with some GraphQL requests, all with body, requests are sync with other Mac devices but all without body

**To Reproduce**
1. Create a GraphQL request
2. Fill the body
3. Wait to sync with other device

**Expected behavior**
I was expecting having the body filled

**App information (please complete the following information):**
 - App Type Desktop
 - Postman Version 7.2.0
 - OS: MacOs Mojave 10.14.5 & Windows 10

**Comment by sujayvenaik** [comment]
Hey, @sirio3mil  I tried but the data seems to sync across devices.

Can you help us with logs? (View -> Developer -> View logs in Finder)
Also steps to reproduce this behavior.

**Comment by sirio3mil** [comment]
I don't have access right now to Windows 10 device, send you meantime MacOs's logs (here I don't have the requests bodies)
[logs mac os.zip](https://github.com/postmanlabs/postman-app-support/files/3284918/logs.mac.os.zip)

**Comment by kamalaknn** [comment]
@sirio3mil It is possible that the graphql body you created on your windows machine were synced to your mac machine on an older version that did not support graphql. The update that supports graphql might have been applied after the changes were synced.

Can you try logging out and logging in on your mac machine?

**Comment by sirio3mil** [comment]
@kamalaknn it works! regards!
