### ISSUE TITLE
Settings > Update.

### ISSUE THREAD

**Issue by zamankul74** [a85/POSTMan-Chrome-Extension#6706]
In ubuntu version 6.7.1 got message:

"Your team updated to Postman v7.0. To keep your collections and workspaces in sync with your team, you must also update to v7.0 by going to  > Settings > Update."

But i have not update there in settings !!!!

**Comment by sujayvenaik** [comment]
Are you using a snap version of the app?
If yes, can you refer [here](https://github.com/postmanlabs/postman-app-support/issues/6045#issuecomment-471177118).
