### ISSUE TITLE
Body(none) treated differently than Body(raw) with no input

### ISSUE THREAD

**Issue by ryanshores** [a85/POSTMan-Chrome-Extension#6710]
**Describe the bug**
Postman monitors treat "Body(none)" differently than "Body(raw/application/json)" with no value in it when reading the value from a pre-request script. The pre-request script functions correctly on a local test, but the cloud monitor requires that the body be set to raw to match the required values.

**To Reproduce**
Console.log(request.body) with none and raw to see differences. 

**Expected behavior**
Expecting the function of the code to be the same on local and also in the cloud.

**App information (please complete the following information):**
 - App Type [Native App, Cloud Monitor]
 - Postman Version [lastest]
 - OS: [Mac & Windows]

**Additional context**
The body gets put through a SHA256 so my assumption is empty string is treated differently than null

**Comment by godfrzero** [comment]
We've pushed out a fix to address this problem, @ryanshores Could you let us know if this is still happening?

**Comment by godfrzero** [comment]
Closing this ticket for now as we've verified this fix from our end. If you're still seeing this problem, feel free to reopen this ticket.
