### ISSUE TITLE
GraphQL: Autocompletion not working

### ISSUE THREAD

**Issue by shasti421** [a85/POSTMan-Chrome-Extension#6712]
In Version 7.2.0 (7.2.0), unable to use graphql support with my application and also other sample apps.  Generate collection throws error "Error while generating collection: format not recognized". Auto-completion also not working.

Here is a sample schema that fails.. https://www.graphqlbin.com/v2/6RQ6TM

Here are some more schema's that are generating errors
   https://github.com/gjtorikian/graphql-docs/tree/master/test/graphql-docs/fixtures

**Comment by chrisdeso** [comment]
Dropping in to say that I was able to reproduce the error when using the `Generate Collection` action with the schema.graphql file.

**Gif**
![](https://i.imgur.com/0UUyJGw.gif)

**Screenshot**
![image](https://user-images.githubusercontent.com/4734306/59472195-437fb600-8e03-11e9-998a-bbaa99c697fa.png)

---

Autocomplete does seem to work though – @shasti421 Is the schema selected in the request builder?

![image](https://user-images.githubusercontent.com/4734306/59472430-07008a00-8e04-11e9-8f3e-7abd5b1ec6e5.png)

**Comment by a85** [comment]
Collection generation is not currently supported.

**Comment by preethammavin** [comment]
@shasti421 collection generation is not supported for GraphQL as of now, but can you elaborate on the autocompletion not working issue.

**Comment by glenp01** [comment]
Similar issue with autocomplete. I imported a GraphQL schema and when sending a request I selected the schema. But autocomplete works only for the GraphQL keywords like `query` or `mutation`

**Comment by sankalp0o** [comment]
Created a separate issue for tracking the feature request for collection generation from graphQL schema at https://github.com/postmanlabs/postman-app-support/issues/7024

@shasti421 and anyone else who wants to pitch in:
Can you tell us the structure of collection you'd find useful which can be generated from a graphQL schema? Please add your thoughts on the aforementioned issue.

**Comment by WellspringCS** [comment]
I am also not seeing autocomplete for 7.5.0 version

**Comment by batjko** [comment]
No autocomplete for me (v7.9.0), and selecting a schema does not work: There's none to select for some reason?

![image](https://user-images.githubusercontent.com/7287076/66580066-b4e33180-eb75-11e9-8aef-6fd9628a982d.png)

**Comment by techmunk** [comment]
I was having this issue as well. I then noticed postman was showing errors in my GraphQL API syntax. All of these errors were around the old implements syntax
```graphql
type GenericProductType implements ContentInterface, ProductInterface {
```
Changing this to the new syntax
```graphql
type GenericProductType implements ContentInterface & ProductInterface {
```
and then checking for other errors and correcting those, made the auto-completion work. So check for syntax errors and/or old or deprecated syntax.

**Comment by theholiday** [comment]
How is still not addressed yet?

**Comment by hmoule** [comment]
Autocompletion seems to work for me after updating to the latest version of postman (7.12.0).

**Comment by nik-lampe** [comment]
@hmoule 
How did you set it up? I just tried it and can't get it to work.

**Comment by hmoule** [comment]
@nik-lampe first I went to the APIs tab and added my graphql schema (making sure to select graphql in the dropdown) then I went back to my graphql query selected where it says "No schema" next to the graphql radio button and selected the api draft I just created and then it seemed to work however after further testing it seems a bit broken.

**Comment by batjko** [comment]
So the schema still has to be added manually, if I understand correctly? I was under the impression that the introspection schema gets automatically retrieved (like Insomnia does it, which is pretty seamless).

**Comment by sebastienbarre** [comment]
Me too. The Reload button next to "No Schema" spins and results in a "Schema refresh" toast, but the menu is still "No Schema", and no auto-completion occurs (7.13.0).

**Comment by carltondickson** [comment]
Autocomplete only works in the sense that I have to start typing a value to see it displayed.
Insomnia works by ctrl + space and I see all type properties which is what I would expect personally...unless I'm pressing the wrong key for autocomplete 🤷‍♂

**Comment by alphadever** [comment]
is there any update on this. I am still not able to get it to work, tried all the suggestions above.

**Comment by marionzr** [comment]
Autocompletion not working on version v7.25.1

**Comment by kamalaknn** [comment]
Hey @marionzr 

Could you check if you have the schema selected and the schema is valid?

**Comment by marionzr** [comment]
Hi @kamalaknn 
Yes. I checked the schema (refresh 2x to make sure) and the schema was exported via Graphql Playground. 

The autocomple works only to Query type and Mutation Type but not to the nested/child types

**Comment by kamalaknn** [comment]
Hey @marionzr 

Could you share a screen-recording of the issue you are seeing? If you could share a sample schema where you are seeing this issue that would be great too. 

Here's a screenshot of autocompletion for a property at second level on the latest Postman app, where it starts listing properties after I type the first character.

![Screenshot 2020-06-08 at 2 06 51 PM](https://user-images.githubusercontent.com/8401064/84010058-bf1e2f80-a991-11ea-835a-d4d0efebdd20.png)

We have also been working on some improvements to the GraphQL editor. On the latest [Postman Canary](https://www.postman.com/downloads/canary/) you could trigger the list of suggestions to show up without typing the first character by pressing `Ctrl + Space`(for mac).

![Screenshot 2020-06-08 at 2 08 35 PM](https://user-images.githubusercontent.com/8401064/84010168-e96fed00-a991-11ea-8898-28d69c03eb05.png)

Were you referring to the ability to look at suggestions before typing any characters?

**Comment by DannyDainton** [comment]
Hey folks,

Is anyone still having issues with the Auto-completion in the latest version?

If you are, could you please provide details (including screenshot/recording) of what you're currently seeing in the app.

**Comment by adiachenko** [comment]
I don't even understand how GraphQL schema or importing schema in Postman is supposed to work.

Try https://graphql.anilist.co for example. Both Insomnia and Paw generation show documentation for it after typing the link. On the other hand, Postman just says "No schema". I am pretty new to GraphQL so maybe I am an idiot here but when virtually any other client handles this seamlessly for me something is gotta be wrong at least from the UX perspective.

**Comment by marcelonp** [comment]
Hey, I'm still having problems with auto-completion:
![image](https://user-images.githubusercontent.com/28743936/109509037-3eebad00-7a7f-11eb-9e28-368fd7d48644.png)
If I mouse over the alert it says: "Incorrect Schema, Autocomplete options to related schema will not work".

I imported a JSON schema for this on v8.0.6. 
How can I make the schema valid? Is there an specification for the accepted JSON format?

**Comment by ghost** [comment]
Same issue.

**Comment by bwu-chwy** [comment]
I am observing that GraphQL SDL works while the JSON format does not.

Both are generated from `apollo client:download-schema` 

```
$ apollo --version
apollo/2.32.1 darwin-x64 node-v10.6.0
```

Postman: Version 8.0.7 (8.0.7)

Unfortunately I cannot share the schema I use, but here's one based on an example api I found from https://github.com/APIs-guru/graphql-apis#demonstration-only-apis (The Planets one)


---- 
# Reproduction
Download the schemas
```
apollo client:download-schema --endpoint=https://pristine-gadget-267405.appspot.com/graphql/ planets.json
apollo client:download-schema --endpoint=https://pristine-gadget-267405.appspot.com/graphql/ planets.graphql
```
Load them into the Postman APIs section.

Select them under a Request > Body > GraphQL

Observe the following and expect them both to work properly:
### JSON fails to load 
<img width="351" alt="Screen Shot 2021-03-23 at 5 32 23 PM" src="https://user-images.githubusercontent.com/64489280/112221525-ecc12600-8bfd-11eb-92ea-7c2e28786eee.png">

<img width="515" alt="Screen Shot 2021-03-23 at 5 34 05 PM" src="https://user-images.githubusercontent.com/64489280/112221573-fe0a3280-8bfd-11eb-8b22-d7875250cfe7.png">

----
### GQL loads
<img width="207" alt="Screen Shot 2021-03-23 at 5 32 28 PM" src="https://user-images.githubusercontent.com/64489280/112221524-ecc12600-8bfd-11eb-829e-bc395ded7afe.png">

<img width="552" alt="Screen Shot 2021-03-23 at 5 34 08 PM" src="https://user-images.githubusercontent.com/64489280/112221577-fe0a3280-8bfd-11eb-8c3c-2c412c262787.png">


cc @DannyDainton

**Comment by marcin-zajac** [comment]
When I change json schema to SDL autocomplete works fine :)

**Comment by mbaev** [comment]
Hey @kamalaknn 
You're [referring](https://github.com/postmanlabs/postman-app-support/issues/6712#issuecomment-640459637) to an ability to trigger list of suggestions without start typing. Though, on my mac `Ctrl+Space` is system shortcut to change language. I haven't found shortcuts in settings to change it.
So is there a way to trigger it still?

I'm thinking if it would be possible to change it to `option + space` to make it consistent with other apps. I know it works that way in GraphQL Playground and JetBrains products.

Thank you
