### ISSUE TITLE
Sharing collection - all URLs and Bodies empty!

### ISSUE THREAD

**Issue by johnkwaters** [a85/POSTMan-Chrome-Extension#6718]
When sharing a collection, either by link or team space, or exporting it, most of the data is lost. No URLS, headers or bodies - just the request names. See example file

[Montage.postman_collection.txt](https://github.com/postmanlabs/postman-app-support/files/3294347/Montage.postman_collection.txt)
![2019-06-16_13-02-20](https://user-images.githubusercontent.com/3422637/59567100-187da800-9037-11e9-9338-27643c110d9f.jpg)

**Comment by preethammavin** [comment]
@johnkwaters I see all the request tabs being dirty, can you confirm all the changes made on the request were saved and when you try to export it exports empty? 

Steps to check: 
Click on collection
Open a request
Make changes 
Save the request 
Try exporting/sharing via the team and check if it is visible.

**Comment by johnkwaters** [comment]
Thanks, that was it!

**Comment by preethammavin** [comment]
@johnkwaters thanks for confirming, closing the issue for now
