### ISSUE TITLE
Postman app unable to launch and getting stuck on "Preparing your workspaces..." step

### ISSUE THREAD

**Issue by mandrije** [a85/POSTMan-Chrome-Extension#6723]
**Postman 7.2.0 x64 gets stuck on Win10 machine in "Preparing your workspaces..." step**

**To Reproduce**
1. Install Postman 7.2.0 for Windows x64 from Postman website on Windows 10 RS4 machine (possibly RS4 version is not critical, but I can't test on other Win10 versions like RS5 or 19H1).
2. Launch Postman from Windows start menu (in case in doesn't auto-launch)
3. Choose either to skip authentication or authenticate with your user account (I was trying with Google auth)

**Observed behavior**
Postman gets stuck indefinitely with a splash screen saying "Preparing your workspaces..."

**Expected behavior**
Postman should open its default view, with collections, requests etc.

**Screenshots**
![postman_stuck](https://user-images.githubusercontent.com/16869789/59595920-08c59880-90f7-11e9-9da7-927f608c609a.png)

**App information**
 - App Type: Native App
 - Postman Version: 7.2.0
 - OS: Windows 10 RedStone4 (ver. 1803)

**Additional context**
I encountered this issue when Postman (desktop app) automatically update on my Win10 RS4 machine to version 7.2.0. I tried downloading an older 7.x version (e.g. 7.0.7) but when I launched it Postman auto-updated to 7.2.0 again so the issue continued happening. I tried to kill Postman processes, delete/rename all Postman related folders on my file system (%AppData% and %LocalAppData%) and re-run installation of Postman 7.2.0 but the issue was still there. Logs inspection didn't give me much info either. Also, I tried both to run Postman as non-authenticated user and as an authenticated user (using Google auth) but in both cases issue is there. My colleagues see the same issue on their machines. However, on my other Win10 machine, I still have Postman 7.1.1 and somehow I can still dismiss 7.2.0 upgrade offer, so Postman works fine on it.

**Comment by sujayvenaik** [comment]
Hey @mandrije 
Can you help us with the logs (View -> Developer -> View Logs in Explorer)? and email them to help@getpostman.com. 
We will take a look and get back. Also, mention the Github issue number in the subject.

**Comment by mandrije** [comment]
Hi Sujay,

Thanks for fast response! I can't get to Postman UI beyond the splash
screen, so I can't follow the path specified in your email (assuming it's a
navigation within Postman). Therefore I'm sending all the .log files
related with Postman on my file system. Please let me know if anything else
is needed for investigation. Btw, Postman has also updated on my last
machine that was running the older version (mentioned in my bug
description), so I'm now stuck with 7.2.0 on all my machines. Logs I'm
sending are exactly from this machine that just updated to 7.2.0.

Thanks,
Marko

**Comment by ericvdkh** [comment]
Same here for 7.3.1. 7.0.7 runs just fine, but anything later than 7.0.7 blocks during startup.

**Comment by zihotki** [comment]
Just installed it on a new machine end encountered the same issue. Cleaning up C:\Users\user\AppData\Roaming\Postman and C:\Users\puchkov\AppData\Local\Postman have no effect. Tried both 32 and 64 bit apps. After I delete both folders and install Postman anew, I can see login screen. After login it's stuck.

This is what is in the pluginHost.log:
```
[2100][1568983640903][pluginHost][info]["Booting Plugin Host for Postman 7.7.3, win32-10.0.18362 on x64"]
[2100][1568983640908][pluginHost][info]["PluginsHost: Booted"]
[2100][1568983640911][pluginHost][info]["not exist",{"errno":-4058,"code":"ENOENT","syscall":"open","path":"C:\\Users\\user\\AppData\\Roaming\\Postman\\plugins\\postman.openApi\\version.json","name":"Error","message":"ENOENT: no such file or directory, open 'C:\\Users\\user\\AppData\\Roaming\\Postman\\plugins\\postman.openApi\\version.json'","stack":"Error: ENOENT: no such file or directory, open 'C:\\Users\\user\\AppData\\Roaming\\Postman\\plugins\\postman.openApi\\version.json'"}]
[2100][1568983640911][pluginHost][info]["PluginInstallationService~installOrUpdatePlugins Installing plugin",{"version":"0.0.10","pluginId":"postman.openApi","isInstalled":false}]
[2100][1568983640912][pluginHost][info]["PluginInstallationService~installFromLocal",{"pluginZipPath":"C:\\Users\\user\\AppData\\Local\\Postman\\app-7.7.3\\resources\\app.asar\\plugins\\postman.openApi.zip","pluginsDir":"C:\\Users\\user\\AppData\\Roaming\\Postman\\plugins","currVersionDirPath":"C:\\Users\\user\\AppData\\Roaming\\Postman\\plugins\\postman.openApi\\0.0.10","tempDir":"C:\\Users\\user\\AppData\\Local\\Temp","result":{"pluginId":"postman.openApi","version":"0.0.10","status":null}}]
[2100][1568983640912][pluginHost][info]["PluginInstallationService~installFromLocal extracting"]
[2100][1568983640913][pluginHost][info]["not exist",{"errno":-4058,"code":"ENOENT","syscall":"open","path":"C:\\Users\\user\\AppData\\Roaming\\Postman\\plugins\\postman.sample\\version.json","name":"Error","message":"ENOENT: no such file or directory, open 'C:\\Users\\user\\AppData\\Roaming\\Postman\\plugins\\postman.sample\\version.json'","stack":"Error: ENOENT: no such file or directory, open 'C:\\Users\\user\\AppData\\Roaming\\Postman\\plugins\\postman.sample\\version.json'"}]
[2100][1568983640913][pluginHost][info]["PluginInstallationService~installOrUpdatePlugins Installing plugin",{"version":"0.0.1","pluginId":"postman.sample","isInstalled":false}]
[2100][1568983640913][pluginHost][info]["PluginInstallationService~installFromLocal",{"pluginZipPath":"C:\\Users\\user\\AppData\\Local\\Postman\\app-7.7.3\\resources\\app.asar\\plugins\\postman.sample.zip","pluginsDir":"C:\\Users\\user\\AppData\\Roaming\\Postman\\plugins","currVersionDirPath":"C:\\Users\\user\\AppData\\Roaming\\Postman\\plugins\\postman.sample\\0.0.1","tempDir":"C:\\Users\\user\\AppData\\Local\\Temp","result":{"pluginId":"postman.sample","version":"0.0.1","status":null}}]
[2100][1568983640913][pluginHost][info]["PluginInstallationService~installFromLocal extracting"]
[2100][1568983640919][pluginHost][warn]["PluginInstallationService~installFromLocal: Error while extracting plugin",{"name":"Error","message":"end of central directory record signature not found","stack":"Error: end of central directory record signature not found\n    at C:\\Users\\user\\AppData\\Local\\Postman\\app-7.7.3\\resources\\app.asar\\node_modules\\yauzl\\index.js:187:14\n    at C:\\Users\\user\\AppData\\Local\\Postman\\app-7.7.3\\resources\\app.asar\\node_modules\\yauzl\\index.js:631:5\n    at C:\\Users\\user\\AppData\\Local\\Postman\\app-7.7.3\\resources\\app.asar\\node_modules\\fd-slicer\\index.js:32:7\n    at FSReqWrap.wrapper [as oncomplete] (fs.js:601:17)"}]
[2100][1568983640919][pluginHost][info]["PluginInstallationService~installFromLocal Completed installing plugin",{"pluginId":"postman.openApi","version":"0.0.10","status":"failed","error":{}}]
[2100][1568983640920][pluginHost][warn]["PluginInstallationService~installFromLocal: Error while extracting plugin",{"name":"Error","message":"end of central directory record signature not found","stack":"Error: end of central directory record signature not found\n    at C:\\Users\\user\\AppData\\Local\\Postman\\app-7.7.3\\resources\\app.asar\\node_modules\\yauzl\\index.js:187:14\n    at C:\\Users\\user\\AppData\\Local\\Postman\\app-7.7.3\\resources\\app.asar\\node_modules\\yauzl\\index.js:631:5\n    at C:\\Users\\user\\AppData\\Local\\Postman\\app-7.7.3\\resources\\app.asar\\node_modules\\fd-slicer\\index.js:32:7\n    at FSReqWrap.wrapper [as oncomplete] (fs.js:601:17)"}]
[2100][1568983640920][pluginHost][info]["PluginInstallationService~installFromLocal Completed installing plugin",{"pluginId":"postman.sample","version":"0.0.1","status":"failed","error":{}}]
[2100][1568983640920][pluginHost][info]["PluginsHost~installOrUpdatePlugins: Synced all plugins",[{"pluginId":"postman.openApi","version":"0.0.10","status":"failed","error":{}},{"pluginId":"postman.sample","version":"0.0.1","status":"failed","error":{}}]]

```

All other log files are without any error and completely normal, all operations mentioned there marked as successful.

**Comment by ericvdkh** [comment]
Same here.
Cleaned the Postman folders in AppData\Roaming and in AppData\Local.
Installed a fresh latest and greatest Postman-win64-7.7.3-Setup
Got a logon screen, then it's stuck "Preparing your workspaces..."
There are 4 Postman processes on my system, one is consuming 3% cpu running the spinner in the preparing your workspace screen, the rest do nothing.
After killing these processes the pluginHost.log file looks exactly like the one above.

Sighhhh

**Comment by mandrije** [comment]
I'm  still hitting this issue on all machines... I got a hint from the support engineer long time ago to try adding a key in System Registry in order to disable GPU usage by the Postman, but that didn't help. I gave up retesting any new releases 2 months ago.

**Comment by kamalaknn** [comment]
Hey @ericvdkh 

Can you send the logs from `View -> Developer -> Show logs in Explorer` to `help@getpostman.com`? We would like to take a closer look at this issue to find the root cause.

Please include this issue title or number on the email subject.

**Comment by kamalaknn** [comment]
If you are not able to find the menu bar, you can also reach the logs from Explorer in one of the following directories

```
C:\Users\<user>\AppData\Roaming\Postman
C:\Users\<user>\AppData\Local\Postman
```

**Comment by sadomovalex** [comment]
I have the same problem when installing latest 7.8.0. Sent the logs by email.

**Comment by vaclavpfeifer** [comment]
Same here

**Comment by sadomovalex** [comment]
Found temporary solution: downloaded postman v.6 from here: https://learning.getpostman.com/docs/postman_pro/managing_postman_pro/migrating_to_v7/#download-latest-postman-v6-app. And it worked.

Hope that issue in the latest version will be fixed soon.

**Comment by zihotki** [comment]
It's sad that version 7 and onwards creating so many blocking issues. I wish they paid more attention to the quality control.

**Comment by eddielovelace** [comment]
Any fix for this yet? It's happened to me today in Linux.

**Comment by zihotki** [comment]
> Any fix for this yet? It's happened to me today in Linux.

Only to fallback to v6. I didn't manage to find the cause or other workarounds.

**Comment by KamilPacanek** [comment]
Unfortunately still not fixed - could not found v6 version easily as the links for older versions have been removed.
I'm gonna watch this issue for the updates, but right now I'm gonna switch to alternative tools.

**Comment by alexandrendb** [comment]
Any updates? I am still having the same issue. I've tried Postman and Postman Canary, but it is stuck when I try to log in. And I have to login as I share a collection with my team. So I don't have a choice here. I have to make it work somehow. I would appreciate any help. Thanks

**Comment by Ali-Meddioui** [comment]
It works for me. Just you need to delete configuration files in AppData. search %appdata% in windows search bar and it will work.[https://support.getpostman.com/hc/en-us/articles/360025359014-How-to-resolve-the-Could-not-open-Postman-error-](url)

**Comment by waaromikniet** [comment]
I have the same issue. I use a corporate managed dev environment without an internet connection. It seems V7 can not be used without internet. The only thing that works is going back to V6.7.4.

[https://dl.pstmn.io/download/version/6.7.4/win64](https://dl.pstmn.io/download/version/6.7.4/win64)

**Comment by wizofaus** [comment]
Just upgraded to latest (7.18) and get both "Cannot open Postman" on startup then stuck on 'Preparing workspace'. Killing postman tasks doesn't help. Can't see anything in %USERPROFILE%\AppData\Roaming\Postman to delete.

**Comment by mslauson** [comment]
FYI, I am now experiencing the same issue on a Mac after upgrading to 7.19.x.  I am not able to go back to 6.x.x, as my collections are saved in the cloud.  Does anyone have any other suggestions to make this usable at the moment?

**Comment by sadomovalex** [comment]
I suggest everyone who face with this issue send request to Postman support via https://support.getpostman.com/hc/en-us/requests/new page or by email help@getpostman.com. Probably if there will be enough tickets they will finally pay needed attention to this issue.

**Comment by Ali-Meddioui** [comment]
> Just upgraded to latest (7.18) and get both "Cannot open Postman" on startup then stuck on 'Preparing workspace'. Killing postman tasks doesn't help. Can't see anything in %USERPROFILE%\AppData\Roaming\Postman to delete.

 Just you need to delete configuration files in AppData. search %appdata% in windows search bar and it will work.https://support.getpostman.com/hc/en-us/articles/360025359014-How-to-resolve-the-Could-not-open-Postman-error-

**Comment by sadomovalex** [comment]
It doesn't always help. E.g. for me it didn't help

**Comment by bluetoothfx** [comment]
@Ali4Dev Thanks for your tips, it works. 

**For windows user** 
1. Make sure your postman is already closed
2. Go to Run
3. Paste  %appdata%  and hit enter
4. Find Postman folder
5. Delete everything inside it
6. Run postman now or Reinstall if you already uninstalled.

**Comment by mvhk** [comment]
Go through the following link, It worked for me

https://community.postman.com/t/postman-not-starting-up-stuck-in-preparing-workspace/10132

**Comment by harryi3t** [comment]
Can you share with us the logs from `%USERPROFILE%\AppData\Roaming\Postman\logs` or `%USERPROFILE%\AppData\Roaming\PostmanCanary\logs` at help@getpostman.com?
Please mention the GitHub issue ID (6723) in the subject line.

**Comment by maxgrohs** [comment]
@bluetoothfx thanks for your solution.

But I did not delete it. I moved all data from %appdata% postman directory to another directory (on desktop). Than postman started again. Than I moved the old data back into the %appdata% postman directory and than postman works again with the old data.

**Comment by mjarosie** [comment]
What happened in my case after removing the content of `%appdata%/Postman` (as @bluetoothfx  suggested) was the app successfully started, but only once. When I restarted the app - the same issue reappears.

Postman version: 7.22.1

**Comment by kamalaknn** [comment]
Hey @mjarosie 

Can you forward the logs from `%appdata%/Postman` when you see this issue to `help@postman.com` so we can take a deeper look at this?

**Comment by ash007-postman** [comment]
@kamalaknn Logs has been shared with you.  Ref ticket- 49333

**Comment by mjarosie** [comment]
I got it working after backing up the `%appdata%/Postman` directory, uninstalling the current v7.22.1, installing v7.21.2 and replacing files in `%appdata%/Postman` with my backup.

**Comment by grimsa** [comment]
I encountered the same issue after upgrading to v7.23.0.
Sent logs to `help@postman.com` (Ref ticket ID: 49870).

**Comment by Kesantielu** [comment]
7.24.0
It's the same issue, logs were sended to email.

**Comment by krushnachulet512** [comment]
I faced same issue.
Then I tried Uninstalling Postman.
Also Delete Postman Folder from below locations:
C:\Users\<user>\AppData\Local
C:\Users\<user>\AppData\Roaming
Then ReInstall Latest version.

**Comment by mccannt** [comment]
Thanks, everyone for keeping us up to date on when you experience these issues. We are grateful for this information as this is not a common error.

Please keep up on the latest version of the application as we are continuing to make improvements all the time.

**Comment by nagendra-UTM** [comment]
Any update on this issue. I am getting the same error on xfce 20.04

**Comment by mccannt** [comment]
@nagendra-UTM Sorry to hear that you are experiencing this. 
Have you tried the steps outlined in this support document? - https://support.postman.com/hc/en-us/articles/360025359014

We are still investigating this issue but can be challenging as its not easily reproducible. 
Please let us know if this did not help.

**Comment by vijayvt2016** [comment]
I was able to solve this same issue with steps outlined in your document @mccannt - thank you!

**Comment by mccannt** [comment]
Is anyone else stuck on this any longer?

**Comment by waaromikniet** [comment]
I still have the issue. The only version that works for me is V6.7.4.
I have a corporate dev server without internet connection.
When I start the app it hangs on preparing workspaces

**Comment by mccannt** [comment]
@waaromikniet Can you grab the logs from the app and send them to help@postman.com ? This will help us troubleshoot the issue for you better. 
You can get the logs by going to `View -> Developer -> View Logs`

**Comment by nagendra-UTM** [comment]
@mccannt 
I resolved the issue by using Postman executable inside app folder(Ubuntu OS). Thanks for the link :+1:

**Comment by waaromikniet** [comment]
@mccannt 
I am not able to get the logs, because I never get past the preparing workspaces window.
I do see a log folder in my roaming folder. There I see this error in main.log

[2276][1599726802920][main][warn]["CloudProxyManager~init: Error while reading proxy configuration from user data - ",{"errno":-4058,"code":"ENOENT","syscall":"open","path"

This mentions a proxy but I am not behind any proxy.

Also starting the exe in the app folder directly has no effect for me.
This also doesn't work "start /affinity 1 %LocalAppData%\Postman\app-7.3.4\Postman.exe"

Again I have no internet connection, Do I need that to run?

**Comment by mccannt** [comment]
@waaromikniet You don't need any internet connection to be able to launch the application, so you should be fine.
You can manually navigate to the directory where the logs are, for example, `C:\Users\trent\AppData\Roaming\Postman\logs` zip these up and send them over to help@postman.com and we should be able to dig in a bit more and give you some suggestions.

**Comment by alxtr1bal** [comment]
Same behavior, with all electron apps it seems... (i e  gitkraken stuck at splash screen) 

same proxy error, not sure if it's relevant.

**Comment by waaromikniet** [comment]
> @waaromikniet You don't need any internet connection to be able to launch the application, so you should be fine.
> You can manually navigate to the directory where the logs are, for example, `C:\Users\trent\AppData\Roaming\Postman\logs` zip these up and send them over to [help@postman.com](mailto:help@postman.com) and we should be able to dig in a bit more and give you some suggestions.

I have sent the logs. The log files do not contain very much information. The application is now already several hours stuck on preparing workspaces.

**Comment by alxtr1bal** [comment]
Just uninstalled a recent windows KB (about .net i think), and now works again. (gitkraken as well) ...

**Comment by waaromikniet** [comment]
My development box is a managed system so I can't uninstall patches . But this problem is already occurring since last year with previous versions also.

**Comment by mccannt** [comment]
Thanks for sending the logs in @waaromikniet 
We will be in touch with any further information we may need.

**Comment by ibrahimkholil6210** [comment]
Close all instances of Postman from the task manager. Then rename Postman folder located in USER>YOURPC>AppData>Roaming>Postman to Postman.old. Open Postman again. It worked for me. Copy IndexDB data from Postman.old IndexDB folder to new Postman file then you are good to go.

**Comment by KamilPacanek** [comment]
> Close all instances of Postman from the task manager. Then rename Postman folder located in USER>YOURPC>AppData>Roaming>Postman to Postman.old. Open Postman again. It worked for me. Copy IndexDB data from Postman.old IndexDB folder to new Postman file then you are good to go.

Are you doing that each time the error occurs?

**Comment by Shisuki** [comment]
> Close all instances of Postman from the task manager. Then rename Postman folder located in USER>YOURPC>AppData>Roaming>Postman to Postman.old. Open Postman again. It worked for me. Copy IndexDB data from Postman.old IndexDB folder to new Postman file then you are good to go.

Works on v8.0.7 thanks!

**Comment by nsmcan** [comment]
Tried to follow all solutions. Nothing helped, but the Canary version works fine.
Postman 6.7.4 works fine too.

I have noticed, that if Postman 6.7.4 is upgraded to v7.36.5 from inside of it, **after restart, new version works**. Until I closed it. Next time - it doesn't start hanging on "Preparing your workspaces..."

Also this chain _Postman 6.7.4 -> upgrade to 7.36.5 -> restart -> upgrade to 8.2.1 -> restart_ - works too, I can use v8.2.1 no problems. Until I closed it. Next time - it doesn't start exactly the same as v7

**Comment by jose1574** [comment]
hola, tenia este mismo problema con la versión 8, desinstalé e instale la versión 7 y funciono.

**Comment by nacholibre** [comment]
To fix the issue on Mac OS (mac users) you need to delete your `Application Support` Postman folder which is located here:

`~/Library/Application Support/Postman`

**Comment by 2shrestha22** [comment]
Any solution for Linux?

**Comment by jviotti** [comment]
Merging this ticket with https://github.com/postmanlabs/postman-app-support/issues/8205,

**Comment by CrisAlejo26** [comment]
**Windows 11**

Hola, encontre otra solucion para aquellos que tienen el problema, mi solucion fue desinstalar postman, eliminar la carpeta de Postman en Local, y en roaming, luego eliminar archivos temporales:

1. Tecla windows + R
2. Escribir 'temp'  eliminar todo
3. Escribir '%temp%' eliminar todo
4. Instalar nuevamente postman y funciona.
