### ISSUE TITLE
BUG: Could not export the data. Please check the DevTools.

### ISSUE THREAD

**Issue by sffej** [a85/POSTMan-Chrome-Extension#6730]
**Describe the bug**
When trying to export Postman data getting the error: "Could not export the data. Please check the DevTools."

This has already been experienced by another user but event was just closed
without followup: https://github.com/postmanlabs/postman-app-support/issues/6721

Update: 6/19 - Additional related issue filed by another user under: https://github.com/postmanlabs/postman-app-support/issues/6744

**To Reproduce**
1. Go to File > Settings > Data Tab
2. Click on Export data Download button

**Expected behavior**
Dialog opens to save data file.

**Screenshots**
Attached images showing error and DevTools console.

<img width="739" alt="Postman-error-2019-06-17_10-51-28" src="https://user-images.githubusercontent.com/534105/59625724-e3cd2780-90ee-11e9-85ef-2662024fd6ae.png">

<img width="768" alt="DevTools-current-2019-06-17_10-57-41" src="https://user-images.githubusercontent.com/534105/59625732-ecbdf900-90ee-11e9-93b7-dee843b47c8b.png">

**App information (please complete the following information):**
Here are my settings:
- Postman Version 7.2.0
- OS Version win32 10.0.17134 / x64
- Google Chrome Version 75.0.3770.90 (Official Build) (64-bit)

**Additional context**
System has been restarted and all updates are current.

**Comment by kamalaknn** [comment]
This has been fixed in PostmanCanary 7.3.0-canary03 now.

**Comment by jeremyml** [comment]
Thanks for working on a fix!  This bug is affecting me also.

**Comment by gcaccia** [comment]
Ditto here.  Hitting same bug.  Can't download data.

**Comment by cnx-brunomelo** [comment]
I was having the same problem. I was able to export to a folder with full permission(777).

**Comment by zedbahn** [comment]
Thx for fixing - looking forward to update to 7.3.

**Comment by davidmpeace** [comment]
When will this update go out?  I'm blocked, and cannot export Collections either.  Same error "Could not export the data. Please check the DevTools." after attempting to export a collection with version 7.2.2 on mac

![image](https://user-images.githubusercontent.com/2800023/60527906-13ac2b80-9ca8-11e9-862e-4b1693d52db5.png)

**Comment by JP-from-Postman** [comment]
You can download Postman Canary to try out the fix right now:
https://www.getpostman.com/downloads/canary

You can also use the Postman API to grab the contents of the request:
https://docs.api.getpostman.com/?version=latest#647806d5-492a-eded-1df6-6529b5dc685c

**Comment by tannenbe** [comment]
Upgrading fixed issue.. thanks!

**Comment by kamalaknn** [comment]
We have pushed the fix for this issue to the stable channel now. Please update to the latest version and give it a try.

**Comment by zedbahn** [comment]
Upgrading fixed the issue - thanks.

**Comment by shubham-dota** [comment]
Just change the permission of the folder to 777 and then export.

**Comment by SurajHashedin** [comment]
i was facing same issue, i just login through browser and exported all collection.

**Comment by surajsoni** [comment]
I was facing same issue, login using browser and exported it

**Comment by berni-mad** [comment]
March 2023 issue still happening .

**Comment by bagusk99** [comment]
> I was facing same issue, login using browser and exported it

thank you this work for me, i just share my collectoin, make it public, open it on chrome and export it

**Comment by vikas027** [comment]
This is still happening on the latest Postman (Version 10.22.13) as of date on Mac. The workaround is to create a public link and then copy the json.

**Comment by chunfengmei** [comment]
It's working after I updated to the latest version
