### ISSUE TITLE
Wrong example returned when the same mock path is used for different examples/requests

### ISSUE THREAD

**Issue by chrisdeso** [a85/POSTMan-Chrome-Extension#6732]
**Is your feature request related to a problem? Please describe.**
When different responses are mocked but have the same path, the mock service only picks up one of the examples and not the other.

i.e. The paths below would return the same example even though they have different examples associated with them

`(in progress) /api/users` – Request 1
`(200) /api/users` – Request 2

In the example above, one endpoint is being designed `(in progress)` while the other already exists `(200)`.

**Describe the solution you'd like**
The ability to use the same path for examples that are associated with different requests to allow for teams/users to iterate/re-design an existing endpoint.

**Additional context**
[Filed by Postman]

**Comment by tmdoit-zz** [comment]
You can choose example response to return by mock server by setting x- mock-respnse-name or x-mock-response-code in request header.

**Comment by ratpik** [comment]
Closing this. The only way to choose between two saved examples which have the same request is to use the `x-mock-response-name` or `x-mock-response-id` to specify the example name or id while sending the mock request as mentioned by @tmdoit.
