### ISSUE TITLE
Bulk operations on collections in workspaces

### ISSUE THREAD

**Issue by chrisdeso** [a85/POSTMan-Chrome-Extension#6733]
**Is your feature request related to a problem? Please describe.**
Currently, there isn't a way to move entire workspaces or to toggle them from `personal` to `team` after they're created.

**Describe the solution you'd like**
The ability to make a shared/team workspace personal

![image](https://user-images.githubusercontent.com/4734306/59631046-79c37b00-910c-11e9-848a-49f372fa02b3.png)

**Describe alternatives you've considered**
An option to share collections in bulk to a different workspace.

**Additional context**
[Filed by Postman] – https://community.getpostman.com/t/i-accidentally-moved-a-personal-workspace-to-me-team-how-can-i-move-it-back-to-personal/5943

**Comment by preethammavin** [comment]
@chrisdeso converting the team workspace to personal workspace is not something we will look into as the users who have built their work flows on the team workspace would be blocked if one user converts a Team Workspace into a personal Workspace, bulk action is something we can look at enabling as that would enhance the current flow.

**Comment by ThreeSevenths** [comment]
@chrisdeso I would like you and the team to reconsider this crazy position. There should be a way to do this even if it breaks things since I have done this by mistake in the past. Having to export everything and then import it again in a personal workspace is a very poor experience.

**Comment by PureKrome** [comment]
@preethammavin (and maybe @chrisdeso from Postman support) any chance we could please have an update here? 

This feels/looks to be a blatant abuse of upselling the product. Please give us (the consumer) the benefit of the doubt that we actually do want to drop back to the 'free' tier. As I was experimenting with POSTMAN (this morning) to see how I can start a team and bring some team members into a team, how many I can have, costs, etc .. i noticed i've now screwed up my _personal_ Postman account. So naturally, I want to revert. Alas, I cannot. And if feels like this restriction is based on the 'upsell' scenario.

Yes, I can make _personal_ workspaces now.

But it looks like my _account_ is made for a team, which it shouldn't be.

If POSTMAN would like to respect it's users and want us to make teams and purchase team licenses, then you would allow us to revert back to personal accounts, disclaimers and all (e.g. you'll loose this-workflow and that-workflow, if what you say, will happen). 

Please - give us the choice if you want us to embrace and pay for your product.

**Comment by jasonycw** [comment]
Any update on how to convert a Team workspace back to Personal one?

I think the most common use case is when people accidentally convert a personal one to a team one through some mis clicking in setting and share menu, not what @preethammavin mentioned. 

If a workspace is highly integrated already, just make a big red warning of what it will break, instead of stopping everyone from rolling back the workspace setting and make this personal to team one way change.

**Comment by sony-mathew** [comment]
Hey @chrisdeso @ThreeSevenths @PureKrome @jasonycw 

We've addressed the pain points you mentioned regarding workspace visibility. You can now convert team workspaces to personal workspaces. Make sure you're running the latest version of the Postman app. 

This is related to #9806 issue.

If this resolves your issue, great! If not, please feel free to reopen this discussion and we'll be happy to help and support you.
