### ISSUE TITLE
Cannot Update Postman on Ubuntu 18.04

### ISSUE THREAD

**Issue by edwardselby** [a85/POSTMan-Chrome-Extension#6738]
**Describe the bug**
Cannot update 6.7.1 -> 7.x.x

**To Reproduce**
Steps to reproduce the behaviour:
1. `snap refresh postman` yields `snap "postman" has no available updates`
2.  `[spanner] > Settings > Update` does not exist!
3. `snap remove postman` && `snap install postman` installs 6.7.1

**Expected behaviour**
To be able to update the app

**Screenshots**
Screenshot show non-existent "Update" tab

**App information (please complete the following information):**
 - App Type [Native App]
 - Postman Version [6.7.1]
 - OS: [Ubuntu 18.04]

**Additional context**

![Screenshot from 2019-06-18 12-05-03](https://user-images.githubusercontent.com/33552215/59677629-36c3df00-91c2-11e9-8fae-09263f140ed2.png)
]

**Comment by numaanashraf** [comment]
@edwardselby Postman v7 is on the candidate channel on the snap distribution for now. Please switch to channel to update - https://learning.getpostman.com/docs/postman_pro/managing_postman_pro/migrating_to_v7/#updating-app-to-postman-v7-after-migration
