### ISSUE TITLE
Error merging forked collection

### ISSUE THREAD

**Issue by Raj-postman** [a85/POSTMan-Chrome-Extension#6741]
**Describe the bug**
When the owner of the collection tries to merge the forked collection to the original collection, receives an error "You are not permitted to perform the action".

**To Reproduce**
1) Create a fork on an original collection
2) Apply changes to the fork collection
3) Merge changes from Forked to the original collection
4) Error "You are not permitted to perform the action"

**Expected behavior**
To be able to merge the changes from the forked collection.

**Screenshots**
![merge](https://user-images.githubusercontent.com/47771757/59691663-fc2d6700-9200-11e9-9a11-a0cfb453ecbb.png)

**App information:**
 - App Type- Native App
 - Postman Version - v7.2
 - OS: MacOS

**Comment by preethammavin** [comment]
@Kurmavathar have addressed the issue internally.

**Comment by arsieorgano** [comment]
I just upgraded to Pro thinking that it might also resolve the issue "You are not permitted to perform the action." we are facing right now. Unfortunately, not.

![Snap 2019-11-07 at 11 57 00](https://user-images.githubusercontent.com/11016504/68359309-6d40cd00-0156-11ea-8605-1691ec83590d.png)


Can someone help?

**Comment by preethammavin** [comment]
@arsieorgano do you have an editor role on both the collections? The parent and the forked one?
This error would occur when you don't have roles on either of the collection as you are trying to update both the parent and the fork. If you have an editor role on the collection you are trying to merge to can you select the merge changes and merge it? 

If you still see the issue please write to us at help@getpostman.com so that we can take a closer look and solve it.

**Comment by arsieorgano** [comment]
> @arsieorgano do you have an editor role on both the collections? The parent and the forked one?
> This error would occur when you don't have roles on either of the collection as you are trying to update both the parent and the fork. If you have an editor role on the collection you are trying to merge to can you select the merge changes and merge it?
> 
> If you still see the issue please write to us at [help@getpostman.com](mailto:help@getpostman.com) so that we can take a closer look and solve it.

Hi,

I think I may have resolved it already. Let me try how it goes.
