### ISSUE TITLE
Teams without an active billing user cannot manage billing, or re-assign billing role.

### ISSUE THREAD

**Issue by JP-from-Postman** [a85/POSTMan-Chrome-Extension#6742]
**Is your feature request related to a problem? Please describe.**

Scenario:
- Team has 1 billing user, who is no longer at the company. This user needs to be removed, and billing rights transferred to someone else.
- Team admin (who doesn't have the billing role) cannot remove them, because they're the only member of the team with the billing role.
- Team admin cannot grant the billing role to someone, because they do not have it themselves.

**Describe the solution you'd like**
Allow team admins to grant the billing role (they already have the ability to revoke it).

**Describe alternatives you've considered**
Allow team admin's to transfer billing rights to another user when removing the last member of a team with the billing role. This seems messier and more complicated.

**Additional context**

**Comment by JP-from-Postman** [comment]
Additional scenario:

New team is started, but invited billing user doesn't join.

This may be because a billing contact email is entered for the designated billing user, and this email is not ultimately used to register for an account.

Thoughts on what might help:
a) Provide instructions for registering for a user account, with invitation email
b) Provide additional messaging on ordering screen or elsewhere, clarifying the nature of the billing role and the need to register for an account
c) Add "grant any role" capabilities to super admin account, as being explored in:
https://github.com/postmanlabs/postman-app-support/issues/6102
d) Other self-serve recovery option for teams without a billing user.

**Comment by cyrielle-hada** [comment]
**Here is a slightly different scenario.** 
1) The team Admin removed the only member who had a Billing role. 
2) The team is left with only User/Admin roles
3) The Admin is not able to assign Billing permissions to other user accounts. 

**What happens** 
When trying to add Billing permissions to another user, the following error message is thrown.
![image GH issue](https://user-images.githubusercontent.com/47351631/64325050-5ac3df00-cfbf-11e9-883f-a56fd0ef0846.png)

**Describe the solution you'd like**
- Super Admin type of role that has overall permissions - https://github.com/postmanlabs/postman-app-support/issues/6102 

@preethammavin

**Comment by cyrielle-hada** [comment]
An Admin now has permission to give Billing permissions to another team member.
