### ISSUE TITLE
Error when exporting Collection: "Cannot read property 'dataMode' of null at _sanitizeRequestBody"

### ISSUE THREAD

**Issue by JP-from-Postman** [a85/POSTMan-Chrome-Extension#6744]
[Reported by Postman Support, on behalf of original User]

**Describe the bug**
User has a certain Collection that throws an error when being exported. Other Collections appear to be unaffected.

Error:
```
vendor-shared.js:608126 Error while exporting an entity

1. Object {id: "<collection_id>"}

1. Object {type: "collection", inputVersion: "1.0.0", outputVersion: "2.1.0"}

TypeError: Cannot read property 'dataMode' of null at _sanitizeRequestBody (file:///C:/Users/<user>/AppData/Local/Postman/app-7.2.0/resources/app.asar/js/vendor-shared.js:427886:14) at requests.(anonymous function).responses._.map.response (file:///C:/Users/<user>/AppData/Local/Postman/app-7.2.0/resources/app.asar/js/vendor-shared.js:427961:11) at arrayMap (file:///C:/Users/<user>/AppData/Local/Postman/app-7.2.0/resources/app.asar/js/vendor-shared.js:792:23) at Function.map (file:///C:/Users/<user>/AppData/Local/Postman/app-7.2.0/resources/app.asar/js/vendor-shared.js:9707:14) at _transformToV1 (file:///C:/Users/<user>/AppData/Local/Postman/app-7.2.0/resources/app.asar/js/vendor-shared.js:427959:33) at Object.transform (file:///C:/Users/<user>/AppData/Local/Postman/app-7.2.0/resources/app.asar/js/vendor-shared.js:428014:18) at __webpack_exports__.a.Promise.resolve.then.then.then.then.then.then.sanitizedEntity (file:///C:/Users/<user>/AppData/Local/Postman/app-7.2.0/resources/app.asar/js/vendor-shared.js:303105:24) at <anonymous>
```

**To Reproduce**
1. User attempts to export a specific Collection affected by issue above
2. User receives error noted
3. Collection is not exported

**Expected behavior**
Collection is exported successfully.

**Screenshots**

**App information (please complete the following information):**
 - App Type: Native app
 - Postman Version: 7.2.0-win32-x64
 - OS: Windows

**Additional context**
See internal notes

**Comment by beaver71** [comment]
same issue with a collection having 180 requests

**Comment by mikewolfen** [comment]
same issue with a collection of 23 requests, it works for a collection of few requests (eg. 1, 4 and 5)

**Comment by thubble** [comment]
We are also experiencing this issue, with the exact same stack trace. 2 different Windows 10 workstations, one with version 7.2.0 and one with 7.2.2.

This looks similar to #6730 and #6721 .

**Comment by sffej** [comment]
Also experiencing same problem. Submitted issue a couple of days ago at:

https://github.com/postmanlabs/postman-app-support/issues/6730

**Comment by mikewolfen** [comment]
I imported and older Postman collection file that has been modified and then successfully exported!

**Comment by kamalaknn** [comment]
We've updated PostmanCanary 7.3.0-canary03 with a fix for this.

**Comment by genius00xp** [comment]
Having the exact issue. When will this fix will be roll out to public user?

**Comment by JP-from-Postman** [comment]
@genius00xp You can download Postman Canary to try out the fix right now:
https://www.getpostman.com/downloads/canary

You can also use the Postman API to grab the contents of the request:
https://docs.api.getpostman.com/?version=latest#647806d5-492a-eded-1df6-6529b5dc685c

**Comment by kamalaknn** [comment]
The fix has been released to the stable channel now. Please update to the latest version and give it a try.
