### ISSUE TITLE
"mockRequestNotFoundError - This collection does not have any Examples" when using collections with versions

### ISSUE THREAD

**Issue by vdespa** [a85/POSTMan-Chrome-Extension#6748]
**Describe the bug**
It seems that mocks are the respective collection version are not properly linked. The error is not very clear that the issue is. 

**To Reproduce**

I cannot constantly reproduce this but it does occur often.

![postman-issue](https://user-images.githubusercontent.com/1197635/59755036-d31cdd00-92b9-11e9-9785-f03e96ad162e.gif)

1. Generate a collection
2. Add examples
3. Tag collection
4. Create a mock server with the same tag as the collection
5. Call the mock server URL and you get the response:

```
{
    "error": {
        "name": "mockRequestNotFoundError",
        "message": "This collection does not have any Examples. Please add examples to the requests in this collection to enable mocking."
    }
}
```

**Expected behavior**
Regardless if this is a bug or not, even if I have misconfigured something, it is not clear what I need to do. So the user experience is bad. 

**Screenshots**

The collection has examples:

<img width="356" alt="Screenshot 2019-06-19 at 16 59 23" src="https://user-images.githubusercontent.com/1197635/59751754-a82f8a80-92b3-11e9-9170-7f3dead1ef12.png">

The collection is properly tagged:

<img width="365" alt="Screenshot 2019-06-19 at 17 02 18" src="https://user-images.githubusercontent.com/1197635/59751972-0e1c1200-92b4-11e9-8dbb-0b4589602494.png">

The mock server was created with the same tag:

<img width="463" alt="Screenshot 2019-06-19 at 16 52 29" src="https://user-images.githubusercontent.com/1197635/59751832-d01eee00-92b3-11e9-93d3-26e8d8b975ef.png">

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version [e.g. 6.0.1]
 - OS: macOS

**Additional context**
I have seen a similar issue being reported here:

https://community.getpostman.com/t/im-getting-an-error-mockrequestnotfounderror-when-doing-mock-request/5903/3

**Comment by AmanDhembla** [comment]
Hey, @vdespa tried reproducing it but was not able to do it. Are you still facing this issue?

![mock test](https://user-images.githubusercontent.com/16691579/62125729-95b16380-b2eb-11e9-8bd5-be4aec94c89c.gif)

**Comment by vdespa** [comment]
@AmanDhembla I will try again and let you know. Thanks.

**Comment by RomanPurishy** [comment]
For me, it is only working with **current** version tag.

**Comment by AmanDhembla** [comment]
Hey @RomanPurishy, can you add a gif or video of the steps you are following to create mock.

**Comment by vdespa** [comment]
I am still having this problem in Postman 7.6. Current works but mocking with a version does not work. 

Here is a schema that I am using to generate the collection:

```
openapi: 3.0.0
info:
  description: This is a simple API
  version: "1.0.0"
  title: Cars API

paths:
  /cars:
    get:
      summary: searches cars
      parameters:
        - in: query
          name: searchString
          description: pass an optional search string
          required: false
          schema:
            type: string
      responses:
        '200':
          description: search results matching criteria
```

**Comment by AmanDhembla** [comment]
@vdespa we are tracking this issue and the solution is being worked upon. Will keep you updated on this.

**Comment by vvs11** [comment]
Hi @vdespa , This is now fixed in the latest version of Postman app
Free users of Postman can add a version tag only to the latest change in a collection's changelog. Pro and Enterprise users can add version tags to older items in the changelog.

**Comment by vdespa** [comment]
Okay... interesting fix. Thank you for looking into it.
