### ISSUE TITLE
i want delete team, but have a bug

### ISSUE THREAD

**Issue by 1013461195** [a85/POSTMan-Chrome-Extension#6749]
![未命名 3](https://user-images.githubusercontent.com/23392657/59756481-60613100-92bc-11e9-9be6-10f8426742be.png)
i want delete team but have a problem. alert need team people add to other workspaces, but this team only me. later i click Leave workspac, alert You can't remove all members from a workspace
![未命名 4](https://user-images.githubusercontent.com/23392657/59756748-f301d000-92bc-11e9-8e0b-8baab9a9d0c0.png)

**Comment by preethammavin** [comment]
@1013461195 hey we have fixed this issue, do let us know if this still persists.
