### ISSUE TITLE
Edit Modal when Leaving Team to avoid Lost Collections issues

### ISSUE THREAD

**Issue by cyrielle-hada** [a85/POSTMan-Chrome-Extension#6751]
**Is your feature request related to a problem? Please describe.**
Currently, nothing warns a user that any collection shared with a team becomes a team owned collection (in terms of RBAC) and is no longer accessible once they leave it. 

AND, if a single user of a team leaves, our warning message only says that the team gets deleted.
<img width="565" alt="Screen Shot 2019-06-19 at 13 41 51" src="https://user-images.githubusercontent.com/47351631/59766722-bae89600-9298-11e9-8ea4-6bb8ccb63047.png">

**Describe the solution you'd like**
Edit the warning message and give a clear explanation of what will happen to shared collections when leaving the team. 

**Suggestions**

- The selected default button for the above action should say `Cancel`, instead of `Proceed`.
- Say explicitly that all Data associated with the team in both Personal and Team workspaces will be deleted and not recoverable.
- Upon clicking on Proceed, ask for a second confirmation that says `Delete My Team and All the Data in Personal and Team Workspaces`.
- Include a link in the above description to “Export Postman Data”
- After clicking on `Leave Team`, show a modal listing the collections originally created by the user (but shared with the team workspace - so no longer belonging to the user) and give the user the option to export them to the personal workspace before leaving the team.

**Comment by sankalp0o** [comment]
Thanks for reporting Cyrielle.

@abhijitkane If the last person is leaving the team, we should probably let him transfer shared collections and environments, instead of letting them be lost with the defunct team.

**Comment by cyrielle-hada** [comment]
A fix has been applied to avoid the described scenario.
When the last member tries to leave the team he will now be asked to select a personal workspace. 
<img width="537" alt="Screen Shot 2019-09-12 at 10 15 21" src="https://user-images.githubusercontent.com/47351631/64770266-21eeb180-d54d-11e9-82f9-1f884ae692f3.png">

In the event the user doesn't select any personal workspace, a default workspace will be chosen instead based on alphabetical order.

Once the user leaves the team, all of the team data (API, Collection and Environments) will be transferred into his personal workspace.
