### ISSUE TITLE
Form-data with files upload is crashing the app in certain cases

### ISSUE THREAD

**Issue by labifrancis** [a85/POSTMan-Chrome-Extension#6752]
**Describe the bug**
When sending a request that has a file attached, this user gets an error "Something went wrong" 

**Screenshots**
![image](https://user-images.githubusercontent.com/10200603/59768983-2d5b7500-929d-11e9-9dee-50859c295fe4.png)

**App information (please complete the following information):**
 - App Type - Native App
 - Postman Version 7.2.0
 - OS: Windows

**Comment by saswatds** [comment]
@labifrancis I have been able to replicate this issue. Will apply the fix ASAP

**Comment by saswatds** [comment]
@labifrancis The fix for this has been applied on `7.3.0-canary04`. Can you confirm if the issue is resolved in canary?

**Comment by labifrancis** [comment]
@saswat The user is getting this error "could not get any response"

**Comment by saswatds** [comment]
`Could not get any response` error occurs usually when the server fails to respond. Can you confirm that `Something Went Wrong` crash is no longer happening?

**Comment by labifrancis** [comment]
The user is not getting this error again `Something Went Wrong`

**Comment by saswatds** [comment]
The latest version of app v7.3.4 has the fix for this. Closing issue
