### ISSUE TITLE
After update my switch is not working?? why?

### ISSUE THREAD

**Issue by ariezs** [a85/POSTMan-Chrome-Extension#6753]
console.log(pm.response.json());
let role = pm.environment.get("role");    **//role has the value "admin"**

switch(role) {
  case "admin":  **// i expected it to jump to this case** 
    pm.test("response is created", function () {
    pm.response.to.have.status(201);
    });
    console.log("User is " + role); 
    break;
  default:
    console.log("The role '" + role + "' is not allowed for this endpoint.");
    pm.test("response is: unauthorized", function () {
    pm.response.to.have.status(401);
    });

Before the update my collection was working fine in postman and newman.. but after it automatically updated postman my switch is not working correctly! So annoying.

**Comment by shamasis** [comment]
Umm ... I would need more info to interpret what’s going on. What’s not working correctly? What is the correct behaviour for your use case? What error do you see? Which version of app are we talking about? How do we recreate it locally?

Also ... do console log your response.text() to see what are you getting in the body?

**Comment by ariezs** [comment]
What you see in my example is a simple switch.. where the role has the value "admin".
Instead of jumping to case admin.. it jumps down to the default case.. 

BEFORE the new postman update it worked perfectly.. but after it updated my postman my simple switch no longer works.. i hope this makes sense :)

**Comment by vikiCoder** [comment]
Can you show the output from Postman console for the script you've posted?

**Comment by SabriH10** [comment]
Hi @ariezs,

If it's alright with you, considering there hasn't been any update here following the request for more information, I'll go ahead and close this issue for now. 

If you still need help, please feel free to re-open this and comment with the information requested above, and we'll be happy to investigate further. 

Otherwise, feel free to reach out if you have any questions or concerns.
