### ISSUE TITLE
Account creation error message username already exists 

### ISSUE THREAD

**Issue by cyrielle-hada** [a85/POSTMan-Chrome-Extension#6755]
**Is your feature request related to a problem? Please describe.**
When the Username already exists an error message appears on top of the form instead of being on top of the field. 

![1a526478-9205-4c54-8575-8ef80871a287](https://user-images.githubusercontent.com/47351631/83893191-8d198d00-a747-11ea-96c9-1991d6a9928a.png)

Every so often the user thinks to own an account with the email address registered in the form and doesn't realize the message is targeted to the Username typed in the field.

As the user believes owing a Postman account > user tries resetting the password. Nothing lands to their email as they don't have any Postman account and end up raising a ticket. 

**Describe the solution you'd like**
Have a validate forms in-line as below. 
<img width="517" alt="Screen Shot 2019-06-19 at 18 01 40" src="https://user-images.githubusercontent.com/47351631/59785283-50e1e800-92bc-11e9-8344-b71f9a77e99d.png">

**Comment by ArjunSingh-PM** [comment]
We have improved the messaging for authentication flows to resolve this issue.
