### ISSUE TITLE
Environment preview in-line editor shows weird behaviour 

### ISSUE THREAD

**Issue by shamasis** [a85/POSTMan-Chrome-Extension#6756]
**Describe the bug**
There are two ways to edit environment variables in Postman - in-line within preview and the full fledged data editor. 

1. They exhibit different input behaviour
2. They have issues in expressing intent to save the change.

**To Reproduce**
Preview in-line editor:

- edit values 
- unless keyboard enter is pressed, even focussing out does not save the value
- preview in-line editor does not accept enter (newline) while the data editor does
- in data editor changing value has no effect until save button is clicked and it’s very easy to miss that step

**Comment by Mechanicalkeyboard** [comment]
Duplicate of https://github.com/postmanlabs/postman-app-support/issues/5220
