### ISSUE TITLE
Ability to disable automatic minor updates

### ISSUE THREAD

**Issue by yaredw** [a85/POSTMan-Chrome-Extension#6757]
**Is your feature request related to a problem? Please describe.**
With v7.2.2, I got this error when trying to input my CSV into Collection Runner:
```Error while parsing data file: Error: Invalid Closing Quote: got """ at line 2 instead of delimiter, row delimiter, trimable character (if activated) or comment```
Rather than try to figure out why my CSV (which was seamlessly accepted yesterday and before then) wasn't being accepted (given a tight deadline), I reinstalled an old version (v7.2.0) and was able to run my collection with the CSV successfully. Later in the day, I restarted Postman and reran the collection with the same CSV. To my horror, I received the same error and in settings>about I saw that the client had downloaded the v7.2.2 minor update and installed it when I restarted the client.

**Describe the solution you'd like**
Similar to how downloading major updates can be disabled, I would like downloading minor updates to be disabled.

**Describe alternatives you've considered**
Alternatively, we could still have the minor update downloaded, but just not automatically installed upon restart. It's a pain to have to reinstall an old version after Postman restarts.

**Additional context**

**Comment by preethammavin** [comment]
@yaredw we have disabled control on minor and patch releases to ensure that all fixes are reflected to the major versions of the app (including security and bug fixes). This is done keeping in mind we do not want to break users workflow and the team continuously works to ensure there is no regression bugs. Please do file a bug with the issue, we will take on priority and fix it if it is a bug.

Thanks

**Comment by azndoodle** [comment]
what version has this fix been applied to?

**Comment by jyeros** [comment]
@preethammavin I agree that it is useful to have all bug and security fixes but if I am using an metered connection I think it should not be downloaded automatically, the updates aren't so big but sometimes there are a few of them and have an impact when use this type of connection.

**Comment by benpingilley** [comment]
This is my issue too. I have a limited amount of data while I'm on my hotspot. Auto-updates run through my data.

**Comment by lucasmaffazioli** [comment]
Also, regression or bug fixes that create more bugs are still prone to happen. No system is perfect. Today Postman updated itself and voila, #8565 happens.

**Comment by hossam-96** [comment]
Please consider that the user can decide if he wants the latest security and bug fixes now or just when he can connect to a WIFI !

**Comment by ZooDoo4U** [comment]
What version has the auto updated disabled?  Seems wrong to go into the setting  and check "Disable automatic updates" only to have updates still apply.   Did "Disabled" change it's meaning recently?

**Comment by arlemi** [comment]
@ZooDoo4U The text does mention you can only disable major updates (i.e. v6, v7) and that minor updates will still be downloaded.
![image](https://user-images.githubusercontent.com/5029719/88793748-3eabcc00-d195-11ea-9d9f-6211d967bd0a.png)

We have an open issue around the same here #6999, and if you'd like to avoid downloading the new versions you can start having a look at [Postman for the Web (still in beta for now)](https://community.postman.com/t/announcing-postman-for-the-web-now-in-open-beta/14192?u=arlemi) which will update itself without any download needed on your side. :)

**Comment by ZooDoo4U** [comment]
Thanks, but it doesn't fix the problem just makes it worse.   The reason the updates are a pain and don't want them,  getting older sucks  and so i've been using a tool to decompress the resources file in order to fix up the fonts so i'm able to simply us postman.  Now with it on the web this option is gone.  So this solution is not useful at all...

**Comment by arlemi** [comment]
@ZooDoo4U That's an interesting use case, I've actually been playing around with editing the theme on-the-go through the browser, it's actually much easier since some browser add-ons allow you to override the page's CSS. 

For example, using [Amino: Live CSS editor](https://chrome.google.com/webstore/detail/amino-live-css-editor/pbcpfbcibpcbfbmddogfhcijfpboeaaf?hl=en-GB), you can override the font (change font-family, family-size) throughout the app with the following code:
```css
* {
    font-family: "Times New Roman";
    font-size: 20px;
}
```

![0-update-font](https://user-images.githubusercontent.com/5029719/88907807-fb169800-d250-11ea-960d-6d9be8c99ec0.gif)

I can actually see some bits not getting updated but I'd be happy to look into it more thoroughly, if you'd like you can create a topic on the [community forum](https://community.getpostman.com/) and we can take it from there.

**Comment by FireByTrial** [comment]
this would be lovely as I have had Postman brick/corrupt itself on three separate systems (two windows 10 and an ubuntu system, usually hits one of the machines each year seemingly at random), requiring a complete uninstall and deletion of all data after doing it's update which just makes it either: spin the wheel forever or present a blank window

**Comment by arlemi** [comment]
@FireByTrial Have you given a try to [Postman on the web](https://blog.postman.com/announcing-postman-for-the-web-now-in-open-beta/)? It requires to install an agent locally (for now) which doesn't require many updates and the rest is done in your browser.

**Comment by FireByTrial** [comment]
I have not, I will give that a try. 
Now that I think about it, those problem apps may have been the old chrome based version of postman

**Comment by arlemi** [comment]
@FireByTrial Ouh yeah, you don't want to use that anymore, we have stopped pushing updates to it a while ago! Get either the latest desktop app or use the online one. https://www.postman.com/downloads/

**Comment by jkewley** [comment]
I'd like to see this, too. My corporate firewall sees the call to the Postman update check domain as a malicious request and locks me out. Makes it difficult to use Postman when I have to unlock my account every few minutes.

I guess I could add a hosts file entry for go.pstmn.io, but I'd rather Postman give me the option to disable all phone home calls.

**Comment by arlemi** [comment]
@jkewley We're tracking this in #6999, you can subscribe their to be updated when there will be something new. 🙂

**Comment by stefanluchian** [comment]
@Postman guys: Why are you insisting to do force us to update, even on minor updates?
This is no way to win new users! And you might lose existing ones.
We simply don't want automatically minor updates! Is it so hard to understand it?
We are not some mobile-app-freaks who just want to have the latest thing.
Just let us decide if and when we want minor updates!
This is really annoying!
Stop forcing us to update! Should be our decision!
