### ISSUE TITLE
SSL Certificate: Request fails on Windows Server 2016, succeeds on 2008

### ISSUE THREAD

**Issue by JP-from-Postman** [a85/POSTMan-Chrome-Extension#6758]
**Describe the bug**
User has a POST request that succeeds when sent from the Postman app on Windows Server 2008. However, when sending the same request from the Postman app on Windows Server 2016, the request fails to get a response. Both machines are running the same version of Postman (7.2.0).

The service targeted by the request uses a certificate. Turning off `SSL certificate verification` resolves the issue on Windows Server 2016, but this isn't required for 2008, and the cause of the discrepancy is unclear.

**To Reproduce**
Unknown

**Expected behavior**
Request is successful on Windows Server 2016, as on Windows Server 2008, with SSL Certificate Verification enabled.

**Screenshots**

**App information (please complete the following information):**
 - App Type: Native app
 - Postman Version: 7.2.0
 - OS: Windows Server 2008, Windows Server 2016

**Additional context**

**Comment by shamasis** [comment]
Hmm... there is not enough info in this. But I can try shooting in the dark. :-p

Could the two servers have different root certificates involved? My hunch is that the server 2008 has older certificates and hence working. The server 2016 does not have this APIs SSL certificate in its trusted list. Maybe this doc could help? http://woshub.com/updating-trusted-root-certificates-in-windows-10/ or https://www.cs.virginia.edu/~gsw2c/GridToolsDir/Documentation/ImportTrustedCertificates.htm

Also, in cases where cert is failing, if you lookup Postman Console, it may have the error listed if there is one available.

**Comment by shamasis** [comment]
Closing this owing to inactivity. Feel free to reopen.
