### ISSUE TITLE
Response body not displayed

### ISSUE THREAD

**Issue by santhoshTpixler** [a85/POSTMan-Chrome-Extension#6761]
**Describe the bug**
After there update v7.2.2 response body is not displayed. But the console the response body.

**To Reproduce**
1. Send a request to an end point which responds with "application/json;charset=UTF-16"

**Expected behavior**
The response body displayed in the postman console should be displayed in the response body section of the app

**Screenshots**
![image](https://user-images.githubusercontent.com/10362257/59838630-e2109780-936c-11e9-865b-815ae51bbde2.png)
![image](https://user-images.githubusercontent.com/10362257/59838688-fce30c00-936c-11e9-9098-b7f7df63a4b4.png)

**App information (please complete the following information):**
 - Native App
 - 7.2.2
 - OS: Ubuntu 16.04

**Additional context**
Before the last update it was working fine. Issue is present only after upgrading to 7.2.2

**Comment by saswatds** [comment]
Hi @santhoshTpixler Can you provide us with a sample test endpoint that you use which returns `application/json;charset=UTF-16`. It will really help us in debugging this issue ASAP. 

> Note: The endpoint should be a test endpoint and should not expose any of your data.

Thanks

**Comment by saswatds** [comment]
@santhoshTpixler Thanks for reporting this, we have been able to reproduce this issue. Will keep this thread posted after completing the RCA for the issue

**Comment by saswatds** [comment]
Hi @santhoshTpixler, we have fixed this issue on our latest canary release `7.3.0-canary04`.
https://www.getpostman.com/downloads/canary

Can you confirm if the issue is resolved for you?

**Comment by santhoshTpixler** [comment]
Hi @saswatds , I have tested the mentioned canary release. **The issue is fixed.** 
Thank you for your valuable support.

**Comment by saswatds** [comment]
The fix is now available in the stable app version 7.3.4. Closing the issue

**Comment by rachnash** [comment]
i upgraded the version to 7.6.0 this morning - since then i am seeing this issue again. my response object is correctly being sent by backend but not getting displayed in postman. it says response status 200, OK

**Comment by ronarbel** [comment]
@saswatds I'm currently on version 7.8.0 and having the same problem. Receiving a `200 OK` status but no response body. 
![image](https://user-images.githubusercontent.com/7448754/68337688-e3c9c600-0095-11ea-9e72-72545a13ddfb.png)

**Comment by jsebas85** [comment]
Same problem here with version 7.10.0 for Mac

**Comment by kamalaknn** [comment]
@jsebas85 Could you let us know if you're seeing any errors in devtools? You can find it by clicking `View -> Developer -> Show DevTools (Current View)`?

**Comment by DhaSur** [comment]
I am facing the same issue as mentioned by **jsebas85** for version 7.10.0 on Mac.
Here is the screenshot from devtools

<img width="915" alt="Postman_7 10" src="https://user-images.githubusercontent.com/57692046/68723688-66f69900-060d-11ea-9257-a1e86315453d.png">

**Comment by kamalaknn** [comment]
Thanks for the report @DhaSur 

I'm re-opening this issue.

**Comment by kamalaknn** [comment]
@DhaSur Can you give us the complete logs from `Right Click -> Save As` on the devtools?

Can you try restarting the app in the meantime to see if the issue still persists?

**Comment by DhaSur** [comment]
@kamalaknn,

After restarting it this time, I am able to see the response but this was not the case earlier as I restarted a couple of times before posting here.

For the logs, it still shows some warnings.
Attached herewith for your reference.

[Console.log](https://github.com/postmanlabs/postman-app-support/files/3839587/Console.log)

**Comment by kamalaknn** [comment]
Thanks @DhaSur

**Comment by liudas-stonys** [comment]
Hello, I'm having same issues with Postman not showing responses. I don't get any response, when I'm sending form-data, as a request body. When I send raw, I get response status as response body.
I've tried to reinstall Postman and deleted all files, bu no help.
![Postman](https://user-images.githubusercontent.com/38351121/69522754-db64fc80-0f6a-11ea-94a5-2fa0a4b2fcc6.png)

**Comment by SomeoneElseOSM** [comment]
I'm seeing much the same effect as above (no response displayed for POST requests) with both Postman-win64-7.13.0-Setup.exe and PostmanCanary-win64-7.14.0-canary01-Setup.exe .

Responses for GET and DELETE come back OK.  Last console log message was "Could not find on CollectionStore. Missing or invalid parameter."  For more detail see:

[postman_example_console.log](https://github.com/postmanlabs/postman-app-support/files/3970334/postman_example_console.log)

**Comment by vomc** [comment]
I am finding this too. I suppose its similar to what I am seeing which is that when my API (in express) returns `res.status(400).send('Some message');` then I would expect Postman (console) to show also the message not just the 400 code. Right now all I see is the HTTP response (i.e. `Bad Request` )

**Comment by ntloi95** [comment]
Same issue, too in 7.7.2 MacOS

**Comment by saurabhChaubey** [comment]
same issue with collection runner.

**Comment by JoyShafer** [comment]
Restarting Postman fixed this issue for me.

**Comment by DannyDainton** [comment]
Hey @ntloi95 / @saurabhChaubey / @vomc 

As you are the most recent users to post about this issue, would you be able to confirm if this is still the case, please?

If it's been resolved we can go a close this out.

**Comment by rajeevpmr** [comment]
I am facing the same issue in my Mac Postman app (Version 7.27.0 (7.27.0)). A restart fixed for one instance and the same issue for the next request

**Comment by kamalaknn** [comment]
@rajeevpmr Could you share a screenshot of any errors you are seeing on Devtools?

**Comment by JohnattanIsrael** [comment]
Hi, I have the same issue and just downloaded postman yesterday 16 07 2020
![postman_error](https://user-images.githubusercontent.com/24196760/87844293-735c8100-c881-11ea-8b05-0bd235bb9c65.PNG)
WIndows 10 64bits

**Comment by arushiprasad** [comment]
Hi, I'm facing the same issue where its not showing the response for a post request. Rstarting did not fix the issue.

It just seems to show the previous response from the GET query in the body.

**Comment by samratde** [comment]
Hello, I am using Postman on windows and facing this issue while sending post request. The JSON response body is not displayed.
![image](https://user-images.githubusercontent.com/32265336/88528210-eef5c500-d01b-11ea-968b-be3efdcd676a.png)

**Comment by rlfriedrichs** [comment]
I am facing the same issue for a couple of APIs.  I'm also using  v7.29.1.  I went so far as to uninstall and do a fresh installation, but I still cannot see the response body.

**Comment by ntloi95** [comment]
> Hey @ntloi95 / @saurabhChaubey / @vomc
> 
> As you are the most recent users to post about this issue, would you be able to confirm if this is still the case, please?
> 
> If it's been resolved we can go a close this out.

The latest update fixed the issue.

**Comment by mccannt** [comment]
@arushiprasad Can you tell us the version of the app and OS you are running? Also, is this happening for any endpoint you are hitting?

@rlfriedrichs @SamratDe Same question, what app version and OS as well as is this impacting all endpoints you are hitting?

**Comment by saurabhChaubey** [comment]
> Hey @ntloi95 / @saurabhChaubey / @vomc
> 
> As you are the most recent users to post about this issue, would you be able to confirm if this is still the case, please?
> 
> If it's been resolved we can go a close this out.

update has resolved the issue . Successfully updated to version 7.32.0-canary01

**Comment by rlfriedrichs** [comment]
I am using v7.31.1 on a Windows 10 Pro machine.
It is only happening for a couple of endpoints, but others in my organization are able to connect to those endpoints with no issues.

Rob Friedrichs
Technical Solutions Architect
(800) 441-0380 ext. 2763

**Comment by samratde** [comment]
@mccannt the issue is resolved for me.

**Comment by mccannt** [comment]
Thanks for the response @saurabhChaubey and @SamratDe glad to hear things are working for you. 

@rlfriedrichs The other members in your org that can hit these same endpoints, are they using the same version of Postman and OS as you?

**Comment by mccannt** [comment]
Closing this issue until we get further information. 
Please feel free to reopen if this is an issue still, with the required information.

**Comment by ghost** [comment]
Hi, I'm facing the same issue where it's NOT showing the response for a POST request. Response body showing empty. 
Restarting did not fix the issue. I'm using Postman Version 7.36.1. This is really annoying 

<img width="1166" alt="Screen Shot 2020-12-23 at 8 42 41 PM" src="https://user-images.githubusercontent.com/8402648/103008508-70b43500-455f-11eb-884b-05e279db63ae.png">

**Comment by DannyDainton** [comment]
Hey @tareqmamun 

You have a mix-match of `Content-Type` headers in your request. You may have had a `text/plain` one in there and then by adding the JSON body it would have applied a `application/json` header.

Could you check that's set to the correct type and let me know if that shows a different response, please?

**Comment by ghost** [comment]
hey @DannyDainton , 
is the what you're looking for? do you have any solution for this brother?

<img width="900" alt="Screen Shot 2020-12-23 at 10 49 23 PM" src="https://user-images.githubusercontent.com/8402648/103019498-1d4ae280-4571-11eb-9dac-da624839891f.png">

**Comment by DannyDainton** [comment]
Without knowing more context about the request - It's not really as straightforward as asking you to do that or that :( 

- Has this ever worked or returned a response?
- Is the request returning a response when make using something like curl?
- Does the Postman Console show the response?
- Have you tried to completely recreate the request in a new tab to see if that does anything?
- Can you try causing a failure to see a change in the status code response (Change the method maybe)?

I'm at a disadvantage as I don't have the request in front of me to check certain things so you're going to need to elaborate more on what you can see and what happens when you change certain things.

**Comment by nndevstudio** [comment]
In my case response body was not displayed until I changed the request to do  GET to the simplest "return OK() only API method".
After that, a "problematic" response is shown.
Tried restarting, uninstalling... maybe luck, maybe something else :-)

**Comment by Kingsconsult** [comment]
I am having this same issue, this is an endpoint that I use everyday in the last 4 months, except this morning, I discovered that my postman just updated to v9.4.1 (the latest)
![image](https://user-images.githubusercontent.com/46958081/145795081-117ba1b6-0004-415a-bd8d-cf7d781cab53.png)


This is the error message I am getting when I check **view/Developer/Show Devtools(Current View)**
![image](https://user-images.githubusercontent.com/46958081/145795605-3c1a6231-9a54-4425-877a-56b7e4128ded.png)

**Comment by walinaqvi110** [comment]
> Hi @santhoshTpixler, we have fixed this issue on our latest canary release `7.3.0-canary04`. https://www.getpostman.com/downloads/canary
> 
> Can you confirm if the issue is resolved for you?

I'm still facing the issue, data not shown at status:200 OK
![Screenshot (84)](https://user-images.githubusercontent.com/70809868/163730752-39d9a09b-91ae-410d-803d-78376e07657b.png)

**Comment by RubenMoronDeveloper** [comment]
Same issue tying to POST, downloaded canary version but still not work
