### ISSUE TITLE
Importing a json file throws an error

### ISSUE THREAD

**Issue by stephen-farmer-avalara** [a85/POSTMan-Chrome-Extension#6762]
**Describe the bug**
Attempting to import a json file (or json raw text) taken from a Swagger page will throw an error and not import.
`Error while importing Swagger 2.0: (Patchable) response.description is mandatory`

**To Reproduce**
1. Select Import button or File > Import
2. Select json file 
3. Observe error is immediately thrown
4. Observe same behavior when user selects paste raw text option

**Expected behavior**
Import should be successful

**App information (please complete the following information):**
 - App Type: Postman for Windows
 - Postman Version 7.2.2
 - OS: Windows 10

**Comment by alfkonee** [comment]
Same issue here

**Comment by abhijitkane** [comment]
@stephen-farmer-avalara @alfkonee Can you link to the file which you're not able to import? Importing https://petstore.swagger.io/v2/swagger.json works for me in 7.2.2.

**Comment by stephen-farmer** [comment]
@abhijitkane This is the one I am trying to import:
https://complianceservice-dev.returns.avalara.net/swagger/v1/swagger.json

**Comment by stephen-farmer-avalara** [comment]
@abhijitkane This is the one I am trying to import:
https://complianceservice-dev.returns.avalara.net/swagger/v1/swagger.json

**Comment by dmitriy-panasiuk** [comment]
Same problem here. Here is a file i am trying to import
[swagger.json.zip](https://github.com/postmanlabs/postman-app-support/files/3377128/swagger.json.zip)

**Comment by mattmenna** [comment]
Seeing this issue as well, not sure where to get additional information on the error either, I don't see anything in the DevConsole created by the import process.

**Comment by spazm** [comment]
I see this behavior in the currently available linux64 `postman` as well as the current `postmanCanary`.

**Comment by spazm** [comment]
I can see the JSON_OBJECT_VALIDATION_FAILED errors using the javascript validator at https://apidevtools.org/swagger-parser/online/ .   This exception could be captured and displayed more clearly.

1. For my swagger.json, I had a responses section that was missing (mandatory?) description fields for my stubbed exceptions

```
    "responses": {
        "ParseError": {
            "description": "When a mask can't be parsed"
        },
        "MaskError": {
            "description": "When any error occurs on mask"
        },
        "NoAuthorizationError": {},
```
->
```
Swagger schema validation failed. 
  Missing required property: description at #/responses/UserClaimsVerificationError
 
JSON_OBJECT_VALIDATION_FAILED
```

2. For @dmitriy-panasiuk 's swagger.json I see missing required fields.

```
Swagger schema validation failed. 
  Data does not match any schemas from 'oneOf' at #/paths//api/v1/roles/{role_id}/permissions/get/responses/200
    Missing required property: description at #/paths//api/v1/roles/{role_id}/permissions/get/responses/200
    Missing required property: $ref at #/paths//api/v1/roles/{role_id}/permissions/get/responses/200
 
JSON_OBJECT_VALIDATION_FAILED
```

**Comment by yogeshkshirsagar-avalara** [comment]
> @abhijitkane This is the one I am trying to import:
> https://complianceservice-dev.returns.avalara.net/swagger/v1/swagger.json

Do we have any resolution on this?

**Comment by abhijitkane** [comment]
@yogeshkshirsagar-avalara https://complianceservice-dev.returns.avalara.net/swagger/v1/swagger.json is an internal URL. Can you create a public link or attach the file here?

**Comment by piero-b** [comment]
This is still an issue, I rolled back to version 6.7.2 and I am able to import from swagger.json again. The later versions of Postman (inc 7.8) do not work even from apis that I was able to previously import from.
API is developed in .net Core 2.2 / Swashbuckle.

**Comment by erwanlr** [comment]
I had the same issue with Postman 7.19.0, swagger file was generated by [Apipie](https://github.com/Apipie/apipie-rails), and I noticed some ```"description": null``` which made the import fail apparently:

```json
"responses": {
  "400": {
    "description": null
  }
},
"description": ""
```

So I replaced all ```"description": null``` by ```"description": ""``` and the import was successful.

Below is a sample which will fail (with the error `Error while importing Swagger 2.0: (Patchable) response.description is mandatory`) when imported:

```json
{
  "swagger": "2.0",
  "info": {
    "title": "API (params in:formData)",
    "description": "\n<p>Another API description</p>\n",
    "version": "v2",
    "x-copyright": null
  },
  "basePath": "/api",
  "consumes": [
    "application/x-www-form-urlencoded",
    "multipart/form-data"
  ],
  "definitions": {},
  "host": "localhost:3000",
  "paths": {
    "/v2/users/{user_id}/recent_posts": {
      "get": {
        "tags": [
          "recent_posts"
        ],
        "consumes": [
          "application/x-www-form-urlencoded",
          "multipart/form-data"
        ],
        "operationId": "get_v2_users_user_id_recent_posts",
        "summary": "Retrieve a list of recent posts by an user",
        "parameters": [
          {
            "name": "user_id",
            "type": "number",
            "in": "path",
            "required": true
          },
          {
            "name": "asset_type",
            "type": "array",
            "items": {
              "type": "string"
            },
            "in": [
              "image",
              "video"
            ]
          },
          {
            "name": "limit",
            "type": "number",
            "in": "query"
          }
        ],
        "responses": {
          "404": {
            "description": null
          }
        },
        "description": ""
      }
    }
  }
}
```

**Comment by piero-b** [comment]
Seems it now errors on the responses missing the description property for the defaults

`"default": {
                        "schema": {
                            "$ref": "#/definitions/ProblemDetails"
                        }
                    }`

Adding in an empty description fixes the import but I shouldn't have to do this...
`"default": {
					"description": "",
                        "schema": {
                            "$ref": "#/definitions/ProblemDetails"
                        }
                    }`

**Comment by mccannt** [comment]
This issue should now be resolved. Please let us know if this is still an issue and reopen.
