### ISSUE TITLE
Incorrect cursor on hovering over History items

### ISSUE THREAD

**Issue by vkaegis** [a85/POSTMan-Chrome-Extension#6767]
**Describe the bug**
The History section of the sidebar doesn't show a hand cursor when hovering over titles, indicating that it's not interactive when in actuality, it is.

**To Reproduce**
1. Go to History section of the sidebar
2. Hover over an item

**Expected behavior**
A hand cursor to show on hover, indicating interactivity.

**App information (please complete the following information):**
 - App Type: Native
 - Postman Version 7.2.2
 - OS: Windows, Mac

**Comment by a85** [comment]
Fixed in the latest version.
