### ISSUE TITLE
Javascript Error when trying to Merge a fork

### ISSUE THREAD

**Issue by JP-from-Postman** [a85/POSTMan-Chrome-Extension#6768]
[Reported by Postman Support, on behalf of user]

**User report:**
_I am trying to merge some changes from a forked branch of my collection to the "master" and it loads a page with a spinning circle, and just sits there doing nothing. Checking the Console log in Chrome it appears to be throwing a Javascript error_

Error is:
`uncaught at fetchCollectionDiff TypeError: cannot read property 'find' of null`

See internal notes

**Comment by Ghusar** [comment]
@JP-from-Postman we have identified the issue related this bug. I will keep the thread updated till the fix goes to production

**Comment by preethammavin** [comment]
@JP-from-Postman the fix has been deployed to production.
