### ISSUE TITLE
Improve messaging around the need for a unique username during account creation

### ISSUE THREAD

**Issue by chrisdeso** [a85/POSTMan-Chrome-Extension#6769]
**Is your feature request related to a problem? Please describe.**
When creating a new account, Postman requires that both username and email address be _unique_. 

When a username is already in use, the error message does indicate that the username is in use but that leads to some folks believing that they already have an account with Postman.

* [Learning Center documentation](https://learning.getpostman.com/docs/postman/launching_postman/postman_account)

![image](https://user-images.githubusercontent.com/4734306/59947666-75140500-9433-11e9-97ec-32e5d45d11b0.png)

**Describe the solution you'd like**
* Messaging on the account creation screen that points the potential user to use a different username.
* Documentation on the learning center & help center indicating that both the email address and username must be unique.

**Additional context**
[Filed by Postman]

**Comment by ArjunSingh-PM** [comment]
We have made changes to the messaging around the authentication flows to address this issue
