### ISSUE TITLE
Cannot import collection with GraphQL requests

### ISSUE THREAD

**Issue by loopDelicious** [a85/POSTMan-Chrome-Extension#6770]
**Describe the bug**
Importing a template with GraphQL requests fails.

**To Reproduce**
1. Go to New+ button
2. Import Template called `Working with GraphQL`
3. See "something has gone wrong" error

**Screenshots**
<img width="1461" alt="Screen Shot 2019-06-18 at 4 15 46 PM" src="https://user-images.githubusercontent.com/17693714/59948675-b9000d80-9425-11e9-91e7-71ac96166be9.png">

**App information (please complete the following information):**
 - macOS
 - postman v7.2.1

**Comment by ratpik** [comment]
The underlying issue was related to an outdated schema of the collection being used. The version of the schema has now been updated.
