### ISSUE TITLE
Have Postman keep collections in the native filesystem and detect changes

### ISSUE THREAD

**Issue by pdemello** [a85/POSTMan-Chrome-Extension#6771]
**Is your feature request related to a problem? Please describe.**
It happens a lot where I:
1. Import a collection.  Open some tabs.  Run requests and do stuff.
2. Pull from github.
3. Forget to re-import the collection.
4. I run an existing tab again.
5. Oops it was from before I pulled.
6. Feeling of frustration.

**Describe the solution you'd like**
Not sure how easy this is, but it would be great if Postman would tell me something like "Hey, your collection changed.  Now what?"

**Describe alternatives you've considered**
Presumably Postman is storing copies of the collections, rather than referencing the original path of collections, so perhaps this is not even possible unless you change where you store the collections. 😅

**Comment by preethammavin** [comment]
@pdemello I understand the workflow, but I do not think we will taking this up anytime soon. Thanks for the feedback and suggestion.
