### ISSUE TITLE
Implementation of JMESPath in Postman to apply query filters on JSON response

### ISSUE THREAD

**Issue by DawnImpulse** [a85/POSTMan-Chrome-Extension#6773]
Issue : 
Most of the times the JSON returned by the backend has large no of lines & usually, we need to see one or two things in that entirely long JSON.

Solution:
Implementation of JMESPath query language baked inside postman to easily sort/filter the JSON.

Alternative:
Usually, I copy/paste the JSON at http://jmespath.org/ and then apply query filters.

**Comment by shamasis** [comment]
@DawnImpulse - having any query mechanism is the first part. We need a way to present that information elegantly. We are working on features that would make this possible.

**Comment by codenirvana** [comment]
@DawnImpulse You can achieve this by using the new **Visualizers** feature added in the lastest Postman app v7.7.

Example:
```js
pm.visualizer.set(`
<div id="jmespath"/>

<script src="https://cdnjs.cloudflare.com/ajax/libs/jmespath/0.15.0/jmespath.min.js"></script>

<script>
pm.getData((err, data) => {
    var jsonData = data.response.json;
    var query = "locations[?state == 'WA'].name | sort(@) | {WashingtonCities: join(', ', @)}";
    var result = jmespath.search(jsonData, query);

    document.getElementById("jmespath").innerHTML = JSON.stringify(result) 
});
</script>

`, {
    response: pm.response.json()
});
```

<img width="1032" alt="Screenshot 2019-09-17 at 5 25 19 PM" src="https://user-images.githubusercontent.com/4865836/65039753-98861780-d970-11e9-8ce2-dc5cd892d208.png">

Learn more about visualizers: https://learning.getpostman.com/docs/postman/sending_api_requests/visualizer/

Let me know if that fixes your issue! 😄

**Comment by DawnImpulse** [comment]
@codenirvana Yeah it is a way to do that but again it increases no of steps and even increases hassles a lot. I am looking for a solution somewhat like jsonformatter.org where you simply press filter button & very easily apply sort/filters on the JSON ... For now, I believe copy/pasting on jsonformatter.org is much better than the method provided. No offense it is in a way a good approach although jsonformatter.org is lot better at this point of time.
