### ISSUE TITLE
Request body editor options overflows

### ISSUE THREAD

**Issue by ghost** [a85/POSTMan-Chrome-Extension#6776]
**Describe the bug**
Request body editor UI is broken.
Look at the screenshot below 

**To Reproduce**
1. Make the app window size (width of 1024px ~ 1137px) as done in the screenshot below
2. Open a request
3. Go to request body editor
4. Select content-type (should have a lengthy name like `JSON (application/json)` or `Javascript (application/javascript)`)
5. See request body editor option overflows a bit which breaks the UI.

**Expected behavior**
Request body editor options should not overflow/content should be visible fully and the horizontal scroll bar should not come on the requester tab.

**Screenshots**
**v7.2.2** 👇 
![image](https://user-images.githubusercontent.com/22131975/60016273-603da880-96a3-11e9-9e9e-1e2659e042e8.png)
**v7.3.0-canary03** 👇 
![image](https://user-images.githubusercontent.com/22131975/60075357-bf9ec580-9742-11e9-8d07-e88d9e381036.png)

**App information:**
 - App Type: Native App
 - Postman Version: v7.2.2 / v7.3.0-canary03
 - OS: macOS mojave 10.14.5

**Additional Information**
Note: The issue in v7.3.0-canary03 is the same (overflows) but there is no horizontal scroll bar on the requester tab and the content not fully visible. As you can see the Beautify button overflows but the not fully visible.

**Comment by saswatds** [comment]
The issue in `7.2.2` is an issue with older chrome version in electron `1.8` because of which UI breaks. It has been fixed in canary which has the newer version of electron. 

The issue in canary is with the addition `GraphQL` section resulting in the language selector getting cramped. A possible fix is to update the collapse sidebar logic to account for the new options.

@vkaegis how do we go about this?

**Comment by vkaegis** [comment]
@saswatds In the two pane view, the Body options collapse into a dropdown to accomodate the minimum width of the pane. If we can set a breakpoint beyond which the options collapse into a dropdown, it would work here as well.

**Comment by coditva** [comment]
Fixed in Postman `v7.21.0` 🎉
