### ISSUE TITLE
Import RAML Folder not working

### ISSUE THREAD

**Issue by osya** [a85/POSTMan-Chrome-Extension#6782]
**Describe the bug**
I tried to import RAML folder according to the doc https://blog.getpostman.com/2015/11/04/supporting-raml-folders-in-postman/. 

**To Reproduce**
1. Clone repository `git clone https://github.com/raml-apis/GitHub.git`
2. In Postman press "Import" button
3. Choose "Import Folder" tab
4. Choose GitHub folder
5. And nothing happens. 

**Expected behavior**
I expected *.raml file with dependend *.json files wil be imported. And Collection will be created

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version 7.2.2
 - OS: Windows 10

**Comment by abhijitkane** [comment]
@osya 

We have added support for importing RAML 1.0 definitions in v7.16 of the Postman app. You can head over to Import in top left corner of App and select appropriate flow for importing.

This also includes support for importing API definition with multiple files having external file references using `!include` tags under the Import Folder flow.

**Comment by venkib** [comment]
Hi abhijitkane, 
 I was trying to import  Mule RAML console directly in to postman via link , it is working but associated schema and example folders not importing . If example folder not import for the POST and PUT request we have to keep manually body. Can you suggest is there a way to do that entire `RAML + schema/example`(which contains mock payloads) 
 
 Thanks,
Venkat.

**Comment by Kingy14** [comment]
Also having trouble importing a RAML file which references mock payloads in schema/example folders. Be great if this could be resolved. Looking at using Postman for our API testing.

**Comment by tahaiqbalkhan9** [comment]
Hey folks,
Any updates on the issue? I am facing  same error. My postman version is: v9.21.2
