### ISSUE TITLE
Console Raw view omits essential details when HTTP headername contains space

### ISSUE THREAD

**Issue by janv8000** [a85/POSTMan-Chrome-Extension#6783]
**Describe the bug**
Console Raw view omits essential details when HTTP headername contains space

**To Reproduce**
1. Create a request with a custom header
2. add a trailing space in the key

**Expected behavior**
Console Raw view mentions no error, the pretty view however points to the exact cause

**Screenshots**
> Header with space
![image](https://user-images.githubusercontent.com/1412705/60084023-0981ae80-9737-11e9-8110-ce7fc157699d.png)

> Raw
![image](https://user-images.githubusercontent.com/1412705/60084197-5cf3fc80-9737-11e9-81ee-1fb4c6650102.png)

> Pretty
![image](https://user-images.githubusercontent.com/1412705/60084321-9462a900-9737-11e9-901a-c3cc4b137f03.png)

**App information (please complete the following information):**
Postman for Windows
Version 7.2.0
win32 10.0.17763 / x64

**Comment by codenirvana** [comment]
Fixed in the latest version of the Postman app v7.6.0.
