### ISSUE TITLE
Update fail and app hangs when Automatic update is disabled 

### ISSUE THREAD

**Issue by cyrielle-hada** [a85/POSTMan-Chrome-Extension#6786]
**Describe the bug**
When using the app from a computer with no public network access and having turned off the auto update in settings, the app tries to connect and update, which fails. It takes a lot of time for the app to start up and to be usable (~30 minutes). 

**To Reproduce**
1 - Download the previous version 7.2.0.
2 - Go to the Settings and disabled `Automatically download major updates`
<img width="712" alt="Screen Shot 2019-06-24 at 11 45 37" src="https://user-images.githubusercontent.com/47351631/60113374-8cbbf800-9769-11e9-9232-60ac43db9950.png">

3 - An error message says `Update failed, view details`
<img width="230" alt="Screen Shot 2019-06-24 at 11 41 50" src="https://user-images.githubusercontent.com/47351631/60113395-96ddf680-9769-11e9-9189-0423825ddf69.png">

4 - The takes a long time to start (~30 minutes) and is not usable. 

**App information (please complete the following information):**
 - Native App 
 - Postman Version 7.2.0
 - OS: Windows Server 2012 R2

**Additional context**
Logs in DevTool console 
![Console](https://user-images.githubusercontent.com/47351631/60113823-782c2f80-976a-11e9-91cc-510d0eb08570.png)

See main logs internally.

**Comment by harryi3t** [comment]
@cyrielle-hada 
I see two issues mentioned here:
 > Even after having turned off the auto update in settings and having no public network access, the app is still trying to update
  
Turning this setting off only disables the app to auto-update to major versions. To know whether there is any minor/major update available or not, the app has to make a network call.
Also, before making that network call, the app checks whether it has any connectivity. Being connected to a private network also fall into the same category of having some connectivity.

 > It takes a lot of time for the app to start up and to be usable (~30 minutes)

Would need some more information on this. A screen recording would greatly help. Also, please share the logs (View -> Developer -> View logs in Finder) to help@getpostman.com

**Comment by preethammavin** [comment]
@cyrielle-hada any chance you got to get the information required?

**Comment by cyrielle-hada** [comment]
@preethammavin @harryi3t  Yes, I have the logs (shared internally).

**Comment by arlemi** [comment]
This issue was resolved with the user through the support desk, closing.
