### ISSUE TITLE
Feature Request: Remove the red 0 failed runner icon when all tests pass

### ISSUE THREAD

**Issue by alilland** [a85/POSTMan-Chrome-Extension#6787]
**Describe the solution you'd like**
I don't know about anyone else, but I get a subconscious "oh crap something failed" on the inside every time I run my test runner, even though every test passed.

<img width="384" alt="Screen Shot 2019-06-25 at 11 21 02 AM" src="https://user-images.githubusercontent.com/14061357/60123275-ec9baa00-973b-11e9-8431-48204cde16cb.png">

**Describe alternatives you've considered**
if all the tests pass, there should be no visible red colors on the screen, if the icon has to stay there make it gray 👍 - red has an alarming effect, which is why its used on stop lights 😄

**Comment by vkaegis** [comment]
@alilland Thanks for writing in! You're spot on, this could definitely do with a face lift. Marking this a to-do, will keep you updated on progress.

**Comment by giridharvc7** [comment]
Runner now has a new UI in v8.0 and it should solve this issue, please let us know what you think about it.
