### ISSUE TITLE
Can't edit monitor, error: Unrecognized field "versionTag".

### ISSUE THREAD

**Issue by JP-from-Postman** [a85/POSTMan-Chrome-Extension#6791]
**Describe the bug**
When editing a monitor from the web dashboard, and clicking "Save Changes", the following error is displayed (regardless of whether or not any changes have been made):

<img width="406" alt="Screen Shot 2019-06-26 at 9 58 04 AM" src="https://user-images.githubusercontent.com/43283131/60199610-2da5c400-97f9-11e9-9555-fd72be177e37.png">

Any changes made are not saved.

**To Reproduce**
1. For any Collection, add a monitor via the app:
2. Click the Edit Monitor icon in-app, which opens the editing page on the web dashboard.
3. (Optional) Make some changes to the monitor (error will still show, even if no changes are made)
3. Click Save Changes

**Expected behavior**
Save Changes works without error.

**Screenshots**
<img width="370" alt="Screen Shot 2019-06-26 at 10 02 54 AM" src="https://user-images.githubusercontent.com/43283131/60200199-7d38bf80-97fa-11e9-98c4-25487548a23e.png">

<img width="447" alt="Screen Shot 2019-06-26 at 10 02 13 AM" src="https://user-images.githubusercontent.com/43283131/60200235-89bd1800-97fa-11e9-82d6-08122ff9d6fb.png">

**App information (please complete the following information):**
 - App Type: Native app, Web Dashboard (Chrome)
 - Postman Version: 7.2.2
 - OS: macOS, Windows

**Additional context**

**Comment by godfrzero** [comment]
We've pushed out a fix for this and all monitor edits should now be working normally.
