### ISSUE TITLE
Make the Manage Accounts icon more intuitive in-app

### ISSUE THREAD

**Issue by chrisdeso** [a85/POSTMan-Chrome-Extension#6792]
**Is your feature request related to a problem? Please describe.**
It isn't always clear to folks where the account/profile dropdown is in-app. The icon is a lovely balloon but doesn't necessarily call out `Profile`. With the ability to add multiple accounts to a single instance of the app, this would be a great addition.

**Describe the solution you'd like**
An icon (or text) that's a bit more intuitive to people who are using the app.

**Additional context**
[Filed by Postman]

* **Discourse post** – https://community.getpostman.com/t/where-is-the-logout-button/1763

![Screen Shot 2019-06-27 at 12 01 56 AM](https://user-images.githubusercontent.com/4734306/60235946-24573e80-986f-11e9-949b-1664ac4ab8b9.png)

**Comment by a85** [comment]
As there is limited space in the app header, we don't have immediate plans to change this but we will consider improvements on making things more legible periodically.
