### ISSUE TITLE
Save button In example saving get blurred out it looks like there is a process still happening.

### ISSUE THREAD

**Issue by pawanbana** [a85/POSTMan-Chrome-Extension#6794]
Save button In example saving get blurred out it looks like there is a process still happening.

![save button issue](https://user-images.githubusercontent.com/31897605/60261891-8d37c880-98fa-11e9-98f3-042d5bfd0a0a.PNG)

Also there are two save button  Inside a tab for example saving it should say something descriptive like "save as example". it looks confusing for now.

![tempsnip](https://user-images.githubusercontent.com/31897605/60262190-34b4fb00-98fb-11e9-8052-d4e0669f493d.jpg)

**Comment by sujayvenaik** [comment]
@pawanbana In the example view it basically means that you haven't made any changes since the last time, hence there are no unsaved changes. Therefore the button is disabled.

**Comment by pawanbana** [comment]
But after making changes it looks like process is happening

kind of confusing

**Comment by sankalp0o** [comment]
@vkaegis Should we hide the button instead of disabling it? As a tab, this behaviour is slightly inconsistent.

**Comment by giridharvc7** [comment]
We've fixed this in the v8 of the app and web. Please let us know 
![Screenshot 2021-03-19 at 6 37 53 PM](https://user-images.githubusercontent.com/1040583/111785187-49f96680-88e2-11eb-8616-950692dbd6d2.png)
