### ISSUE TITLE
Schema validation in API define tab

### ISSUE THREAD

**Issue by ankit-m** [a85/POSTMan-Chrome-Extension#6799]
**Is your feature request related to a problem? Please describe.**
The API define tab does not validate schema based on the type selected. Ex. OAS 3.0.0 validation

**Describe the solution you'd like**
Add inline schema validation which shows errors in the code editor if schema rules are violated.

**Describe alternatives you've considered**
Using other online schema validation tools.

**Comment by vvs11** [comment]
This is released in app 7.29
