### ISSUE TITLE
Wrong view opened with "Manage Environments" keyboard shortcut in latest Canary release

### ISSUE THREAD

**Issue by filfreire** [a85/POSTMan-Chrome-Extension#6801]
I've noticed that in the latest canary release I have installed, version `7.3.0-canary04`, when I do the keyboard shortcut `Option+Command+E` to open the "Manage Environments" menu, it opens the dialog to "Add environment", instead of the "Manage Environments" one. In version `7.2.2` this doesn't happen.

**Screenshots**
![Screenshot_2019-06-28_at_11_06_54](https://user-images.githubusercontent.com/11976836/60336461-b317a880-99a0-11e9-89d9-8d769cd89e04.png)

<img width="818" alt="Screenshot_2019-06-28_at_11_06_46" src="https://user-images.githubusercontent.com/11976836/60336462-b317a880-99a0-11e9-8b41-28e67a9cc891.png">

**App information (please complete the following information):**
 - App Type `Native App`
 - Postman Version `7.3.0-canary04`
 - OS: `macOS Mojave 10.14.4`

/cc @numaanashraf @abhijitkane @priyalviroja @kamalaknn

**Comment by sujayvenaik** [comment]
Hey @filfreire 
I was able to reproduce this, will fix this and push out ASAP.

Thanks for reporting.

**Comment by filfreire** [comment]
Thank you @sujayvenaik! :

**Comment by sujayvenaik** [comment]
Hey @filfreire  We have fixed this in the latest canary (v7.3.0-canary06).
Thanks for reporting :)
