### ISSUE TITLE
Toast message for linking entity to api shows entity name as undefined

### ISSUE THREAD

**Issue by Ghusar** [a85/POSTMan-Chrome-Extension#6803]
**Describe the bug**
Try linking documentation to an API from postman web, success toast for that contains undefined instead of entity name

**Screenshots**
![image](https://user-images.githubusercontent.com/15612246/60341743-2c2cf500-99cd-11e9-833d-c0f088e7e006.png)

**Comment by preethammavin** [comment]
This issue has been fixed
