### ISSUE TITLE
Update "Licence" to "License" on About screen 

### ISSUE THREAD

**Issue by BrandonGordon126** [a85/POSTMan-Chrome-Extension#6805]
**Describe the bug**
On the "About" screen in "Settings," the "Licences" link is misspelled. It should be changed to "Licenses." 

**To Reproduce**
1. Go to Settings
2. Click on About
3.. See error

**Expected behavior**
Should say "Licenses" 
<img width="1461" alt="Screen Shot 2019-06-27 at 3 20 10 PM" src="https://user-images.githubusercontent.com/48736195/60359139-f700b280-998c-11e9-91f1-6d546bf46864.png">

**Comment by kamalaknn** [comment]
@BrandonGordon126 This should be fixed in Postman 7.6.0
