### ISSUE TITLE
Error: "request has the following fields missing or wrongly provided: collectionId"

### ISSUE THREAD

**Issue by JP-from-Postman** [a85/POSTMan-Chrome-Extension#6806]
**Describe the bug**
_Reported by support, on behalf of original user._

User is attempting to publish a Collection, and receiving the following error:

![image001](https://user-images.githubusercontent.com/43283131/60369794-a3509200-99a9-11e9-9f9b-c360bcabda16.png)

**To Reproduce**
1. Attempt to publish Collections
2. Receive error

**Expected behavior**
Collection is published successfully

**App information (please complete the following information):**
 - App Type: Native app
 - Postman Version: 7.2.2
 - OS: macOS

**Additional context**
See internal notes

**Comment by Cazaimi** [comment]
@JP-from-Postman, could you send more details on this issue in the form of browser logs and steps required to get them.

**Comment by JP-from-Postman** [comment]
@Cazaimi Added internal notes

**Comment by Cazaimi** [comment]
@JP-from-Postman unable to reproduce this. It can be marked as closed as it seems like a rare case. Also, this issue can be reopened if the frequency increases in the future. cc @Raja-Simha

**Comment by VitorBrangioni** [comment]
Same issue.

**Comment by JP-from-Postman** [comment]
@Raja-Simha can we re-open this? Have a new user report.

**Comment by asadmalik3** [comment]
@JP-from-Postman I think this is happening when your local postman environment is not yet synced with cloud environment.
