### ISSUE TITLE
Error in postman bootcamp tooltip message

### ISSUE THREAD

**Issue by Ramya-From-Postman** [a85/POSTMan-Chrome-Extension#6809]
**Describe the bug**
The mock path in the tooltip message while creating a mock for a post request in Bootcamp is incorrectly shown as **Get** and this needs to revised.

**To Reproduce**
1. Go to Bootcamp
2. Take the course of creating mock for a POST request

**Expected behavior**
The tooltip message should display the right path which is POST

**Screenshots**
![image](https://user-images.githubusercontent.com/40994626/60418243-13585580-9c00-11e9-8430-7d5bce85eb23.png)

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version: 7.2.2
 - OS: e.g. macOS High Sierra 10.14

**Comment by prashantagarwal** [comment]
@Ramya-From-Postman We have updated the message accordingly.
