### ISSUE TITLE
Missing "accountID" header

### ISSUE THREAD

**Issue by F3sterski** [a85/POSTMan-Chrome-Extension#6813]
**Describe the bug**
missing header during request

**To Reproduce**
In main screen during sending request all my headers works fine but "accountID" is missing.

**Expected behavior**
header "accountID" should appear on server side

**Screenshots**
![image](https://user-images.githubusercontent.com/9092317/60427686-7db8c800-9bf7-11e9-8119-a08d376cc41d.png)

**App information (please complete the following information):**
 - Native app 
 - Postman v7.2.2 
 - Windows 10

**Additional context**
I see this strange issue only with this one particular header. On previous version (5xxx) works fine.

**Comment by shamasis** [comment]
Can you change the url in url bar to `https://postman-echo.com/headers` and post what response you’re getting?

**Comment by F3sterski** [comment]
{
    "headers": {
        "x-forwarded-proto": "https",
        "host": "postman-echo.com",
        "accept": "application/json",
        "accept-encoding": "gzip, deflate",
        "authorization": "x",
        "cache-control": "no-cache",
        "correlationid": "1",
        "legal-mandate": "tax",
        "partyid": "10046444480",
        "postman-token": "c72c21f1-0d49-4164-b084-5883c922c2ab",
        "user-agent": "PostmanRuntime/7.15.0",
        "x-bluecoat-via": "89d7f2ada733bffb",
        "x-forwarded-port": "80"
    }
}
![image](https://user-images.githubusercontent.com/9092317/60511334-f7bd7f80-9cd1-11e9-8513-e9cc491857c6.png)

**Comment by codenirvana** [comment]
@F3sterski Is there any `pre-request` script setup in your folder or collection level?
Can you try the same request in a new tab (unsaved request)?

**Comment by F3sterski** [comment]
I don't have any pre-request scripts but in new tabs works fine :) in all previous tabs doesn't. I restarted app and checked again in new tab and old, and nothing changes in new works and in old not. 

I got it! It stops work when I load request from History.
