### ISSUE TITLE
postman require('fs') is not returning FileSystem object in version 7.2.2

### ISSUE THREAD

**Issue by gajendra-chandrakar** [a85/POSTMan-Chrome-Extension#6815]
**Bug Description:**
postman require('fs') is not returning FileSystem object in version 7.2.2 
when used in scripts in "Tests" tab .
giving error ** TypeError: fs.writeFileSync is not a function**

**To Reproduce**

    Go to ' Tests' tab and write below code
    pm.test("response is ok", function () {
        outFilePath = 'out_file.txt';
        fileContent = 'Hello World';
       fs = require('fs');
       console.log(fs);
       fs.writeFileSync( outFilePath, fileContent);  
    });

**Error**: TypeError: fs.writeFileSync is not a function

**Expected behavior**
It should write fileContent in outFilePath.

**App information (please complete the following information):**
    App Type : Native App
    Postman Version : 7.2.2
    OS: Windows 10

**Comment by gajendra-chandrakar** [comment]
Describe the bug
postman require('fs') is not returning FileSystem object in version 7.2.2 
when used in scripts in "Tests" tab .

To Reproduce
Steps to reproduce the behavior:

    Go to ' Tests' tab and write below code
    pm.test("response is ok", function () {
        outFilePath = 'out_file.txt';
        fileContent = 'Hello World';
       fs = require('fs');
       console.log(fs);
       fs.writeFileSync( outFilePath, fileContent);  
    });

Error: TypeError: fs.writeFileSync is not a function

Expected behavior
It should write fileContent in outFilePath.

App information (please complete the following information):

    App Type : Native App
    Postman Version : 7.2.2
    OS: Windows 10

**Comment by saswatds** [comment]
Hi @gajendra-chandrakar Postman does not support performing a file-system operation inside the test-script sandbox as of now. 

To know about all the supported libraries that you can include checkout out the learning centre
https://learning.getpostman.com/docs/postman/scripts/postman_sandbox_api_reference/#___gatsby

**Comment by saswatds** [comment]
We are already tracking such a feature request to allow access to file-system using our new working directory concept as stated in Issue https://github.com/postmanlabs/postman-app-support/issues/6370 
In efforts to keep issues properly tracked, I am closing this issue as a duplicate. 
Feel free to thumbs up in the above issue.

**Comment by pragun-sharma** [comment]
Hi, I am new to postman and I was looking for a library that allows to work with files in javascript. And got to know about 'fs'. Why has the postman removed 'fs' and introduced a more complex mechanism of writing to a file. Currently, you have to run a local server in the background, and then send data to this server by sending a post request.
