### ISSUE TITLE
Delete team

### ISSUE THREAD

**Issue by Kastamat** [a85/POSTMan-Chrome-Extension#6817]
Hi. I have a problem
I created a team to share requests as much as possible.But this function was useless for my purposes.
I decided to delete the team, but with it all my collections were deleted. Is there any way to restore the collections?

**Comment by sankalp0o** [comment]
Thanks for reporting this @Kastamat. We are tracking this issue and will soon fix this flow. @cyrielle-hada can you assist with recovering the collections?

I'm closing this issue since we're already tracking this on #6751 but feel free to continue the conversation for recovering your collection.

**Comment by cyrielle-hada** [comment]
@Kastamat, any collection originally created by a user, that is shared in a team workspace becomes a team owned collection. When a collection is shared with a team workspace, it doesn’t belong to your personal workspace anymore, although it co-exists inside your personal workspace. When you leave that team, the team collection remains with the team and you no longer have access to it.

Although we cannot guarantee it will work - we can try to recover the missing collections from the local data located in the IndexDB file. Would you try looking for the IndexDB at the below location and send a .zip file over at `help@getpostman.com`? 

Windows | `C:\Users\<user>\AppData\Roaming\Postman\IndexedDB`
Mac | `~/[user]/Library/Application Support/Postman/IndexedDB`

**Comment by Kastamat** [comment]
Just sent
