### ISSUE TITLE
An example for Pre-request script includes described bellow error

### ISSUE THREAD

**Issue by Artemy22** [a85/POSTMan-Chrome-Extension#6818]
**Describe the bug**
An example for Pre-request script includes described bellow error

**To Reproduce**
- go to https://learning.getpostman.com/docs/postman/scripts/pre_request_scripts

**Expected behavior**
Instead of `pm.environment.set("timestampHeader"); new Date());`
Should be `pm.environment.set("timestampHeader", new Date());`
**Screenshots**
![Selection_317](https://user-images.githubusercontent.com/13822848/60448575-9395af80-9c2e-11e9-9441-acd061a03925.png)

**Comment by DannyDainton** [comment]
Hey @Artemy22,

This image has now been replaced on the Learning Center.

**Comment by Artemy22** [comment]
Thanks
