### ISSUE TITLE
Don't make the request result panel scrollable

### ISSUE THREAD

**Issue by jameslaneconkling** [a85/POSTMan-Chrome-Extension#6819]
Enhancement: When viewing a sufficiently large result in the single pane view, both the app body and result panel are scrollable.

![Screenshot 2019-07-01 13 32 05](https://user-images.githubusercontent.com/4389360/60455557-a4313000-9c04-11e9-8814-1988a08ec407.png)

_(for context, in the above example, I'm referring to the inner panel containing the json as the result panel, and outer element containing the url input field, query params, and result panel as app panel)_

Embedding a scrollable element within an outer scrolling element like this makes for some wonky UX, including:

- if the act of scrolling the outer app panel causes the cursor to enter the inner results panel, scrolling unexpectedly switches from the outer panel to the inner.  

- if the entire results panel is not visible w/i the outer app panel, then scrolling to the bottom of the results panel truncates those results unless you also scroll the outer app panel to the bottom.

Some of the above behavior might be system dependent, but nonetheless is inconsistent and unexpected.  None of this is super unintuitive nor even that hard to work around, it's just annoying and gets in the way of something that should be super simple and super fast: quickly scrolling through long content.

Removing the result panel max height should solve the above annoyances, and I don't think it would prevent any useful interaction that the current layout supports.

**Comment by vkaegis** [comment]
@jameslaneconkling Thanks for writing in. We're tracking this issue here: https://github.com/postmanlabs/postman-app-support/issues/5903

Closing this one as a duplicate.
