### ISSUE TITLE
Update button label on purchase flow

### ISSUE THREAD

**Issue by BrandonGordon126** [a85/POSTMan-Chrome-Extension#6822]
**Describe the bug**
The button label on the purchase flow for adding slots needs to be updated from "Pay $XXX" to "Complete Purchase." 

**To Reproduce**
1. Go to Add Slots page on the Manage Team page
2. Select number of user slots 
3. Click proceed

**Expected behavior**
The button label should more clearly describe the action that the user is taking, e.g. completing their purchase/upgrade, rather than focusing on the money they're going to pay. 

**Screenshots**

![Screenshot 2019-07-01 13 44 09](https://user-images.githubusercontent.com/48736195/60466242-fcb5fc80-9c07-11e9-8604-68e6056a9385.png)

**Comment by DannyDainton** [comment]
Hey @BrandonGordon126 👋🏻 

This area of the platform has been updated in the latest versions and no longer shows this on the button. 

I'm going to close this out.
