### ISSUE TITLE
Unable to login to Postman App

### ISSUE THREAD

**Issue by npaul23** [a85/POSTMan-Chrome-Extension#6827]
**Describe the bug**
I'm accessing postman through proxy. I am able to access it and sign in successfully through browser. But I'm unable to sign in through Postman App. We've whitelisted both *getpostman.com and *postman.co. We've tried with both custom proxy & system proxy. Its still the same issue. Is there any other URL we need to whitelist specific to the App?

![Screenshot1](https://user-images.githubusercontent.com/52439439/60484209-0315a880-9cdc-11e9-9f77-c66cf7d72f80.png)
![Screenshot2](https://user-images.githubusercontent.com/52439439/60484210-0315a880-9cdc-11e9-9f2a-e7f838a5b6c2.png)

**To Reproduce**

**Expected behavior**

**Screenshots**

**App information (please complete the following information):**
 - App Type [e.g. Chrome App, Native App]
 - Postman Version [e.g. 6.0.1]
 - OS: [e.g. macOS High Sierra 10.13.2]

**Additional context**

**Comment by elssar** [comment]
Hi @npaul23,

That does sound like a network issue, most likely related to the proxy you're using.
It would be helpful if you could send the application logs from when this error happens to help@getpostman.com

How to get the logs -

1. Console logs
  1.1 View --> Developer --> Show DevTools(Shared)
  1.2 View --> Developer --> SHow DevTools(Current View)

2. Log files
  2.1 All log files from View --> Developer --> View logs

**Comment by elssar** [comment]
@npaul23 are you still facing issues while logging into the Postman app?

**Comment by elssar** [comment]
Closing the issue due to inactivity.
