### ISSUE TITLE
Show branch name for collection in the Runner

### ISSUE THREAD

**Issue by ghost** [a85/POSTMan-Chrome-Extension#6828]
It would be nice if branch names for collections was shown in the runner, so we don't have to do a count to ensure we select the proper branch.

**Comment by Ghusar** [comment]
@ChristianMP Thanks for reporting this issue. 

May I know which version of postman app, you are currently using?

**Comment by ghost** [comment]
> May I know which version of postman app, you are currently using?

Postman for Linux
Version 7.2.0
linux 5.0.0-16-generic / x64

**Comment by Ghusar** [comment]
@ChristianMP  we have included this feature in version 7.2.2 of postman app. Can you try upgrading the app version and confirm it?

**Comment by ghost** [comment]
@Ghusar I was running Postman of Snap, I've now done a manual update to 7.2.2 and can confirm that it works. Thank you very much.
