### ISSUE TITLE
All requests are shown as GET, regardless of the actual method specified for the request

### ISSUE THREAD

**Issue by pulkitsharma07** [a85/POSTMan-Chrome-Extension#6829]
The tabs show the correct method (`POST`), whereas the sidepanel displays these requests as `GET`
![Screen Shot 2019-07-02 at 3 09 19 PM](https://user-images.githubusercontent.com/4774658/60502476-88e52400-9cdb-11e9-8305-d1c280a60369.png)

**To Reproduce**
1. Create a new request in a collection
2. Change the request method to something other than `GET`

**App information (please complete the following information):**
 - Native App
 - Postman Version: 7.2.2 (7.2.2)
 - OS: macOS Sierra

**Comment by pulkitsharma07** [comment]
I have tried restarting the application, that didn't help.

**Comment by sujayvenaik** [comment]
Hey @pulkitsharma07 
I see that you haven't saved the request yet.
The sidebar reflects the saved state of the request and I can see unsaved changes in your tab. Maybe you changed the method but did not save it.

Can you save it once and try if it's working as expected?

**Comment by pulkitsharma07** [comment]
Oh, it displays the correct method now ! 

Seems like a bit counterintuitive to me to be honest. The side panel should also show the yellow/orange dots to signify that there are unsaved changes (and update its state according to current request's state).
