### ISSUE TITLE
Relative links in response are no longer hyperlinked after v7.3.0 update

### ISSUE THREAD

**Issue by pearlberry** [a85/POSTMan-Chrome-Extension#6832]
**Describe the bug**
Attempting to click a link/URI in the response body and it is no longer a hyperlink. Version 7.3.0. I have reverted back to 7.2.2 and they are hyperlinked as expected.

**To Reproduce**
1. Make a call to any service that will return a URI in the response
2. Attempt to click on the URI in the response

**Expected behavior**
New tab should open with the URI appended to the base URL of the previous tab

**App information (please complete the following information):**
 - App Type [Windows App]
 - Postman Version [7.3.0]
 - OS: [Windows 7 Enterprise]

**Additional context**
This was working fine in 7.2.2, my Postman was automatically updated to 7.3.0, and now the links are no longer hyperlinked. It looks like this may have happened in the past (Github issues #1195 #185 #1267 #1268)

**Comment by kamalaknn** [comment]
Hi @pearlberry 

Thanks for reporting this. Absolute links in responses should work. I am assuming you are referring to relative links since you have mentioned appending to base URL. I'm updating the issue title as well.

We will look into this and share updates on this thread.

**Comment by pearlberry** [comment]
@kamalaknn yes I am referring to relative links. Thank you.

**Comment by pearlberry** [comment]
@kamalaknn is there any ETA on when this will be resolved?

**Comment by robross0606** [comment]
This is driving me NUTS.  Not only is this problem not fixed, but Postman continues to auto-update itself to the broken version even if I disable Updates in the settings.  And reinstalling the older version wipes out all my settings and I have to start over.  

How can I a) fix this problem, or b) continue using the older version that works without you pushing a broken version automatically?

**Comment by pearlberry** [comment]
@robross0606 same here, my auto-updates are disabled as well but I still get them pushed. didn't really care about that until this issue started.

@kamalaknn can we get an ETA on when this will be fixed?

**Comment by pearlberry** [comment]
@chrisdeso you responded to my tweet about this issue. any idea when this might be fixed?

**Comment by kived** [comment]
This bug aggravates me each and every time I open Postman. I sure hope this is actually being worked on and the devs/community managers are just being silent for the last month.

**Comment by petertom51** [comment]
Is there any update for this? We really hope the bad UX can be solved.

**Comment by FizzingWhizbee** [comment]
For my purposes PostMan is next to useless If I have to continue manually copying relative links to construct URLs for opening new requests.  Please fix this soon.

In the meantime I'm searching to see what alternatives to Postman exist that support opening new requests from relative links in a HATEOAS response.

**Comment by robross0606** [comment]
This issue, coupled with the fact that Postman keeps upgrading itself to the latest (broken) release is maddening.  The complete silence from developers on both issues is deafening.  I too have started looking at other tools like Insomnia.

**Comment by mccannt** [comment]
Everyone. 
We hear you on this issue and it is being looked at currently. I can not comment on an ETA for the fix but I wanted to reassure you that this is not being ignored and will be resolved.

**Comment by robross0606** [comment]
@mccannt is there any way to stop Postman from updating to this broken version automatically?  Any secret setting or mechanism?

**Comment by mccannt** [comment]
@robross0606 There are ways that can help with this, one way would be to disable to automatic update downloads. This can be found in the Preferences -> Update -> Automatically download major updates

If this is a major issue you can roll back to a previous version if it does not block you on any other features and functionality. I understand this is not ideal but hopefully can help address the frustrations until this issue is resolved.

**Comment by robross0606** [comment]
@mccannt , unfortunately, that first suggestion doesn't help.  The last working version was 7.2.2 which apparently isn't considered a "major upgrade".  Even with this toggled off, it still updates from 7.2.2 to 7.3.6 which I guess is only considered a "minor upgrade".  That's the core problem here.  There's no actual way to FULLY turn off auto-updating.  Either that's a separate bug or it is working as intended and missing an important feature.

**Comment by JosephDHenry** [comment]
This definitely needs to be fixed.

This makes postman completely almost useless for anything our organization does. I can keep installing 7.2.2 but it keeps getting upgraded.

**Comment by mccannt** [comment]
@robross0606 @datacart 

I am looking into this to see if there is a way we can work around it. I will get back to you once I get more information.

**Comment by mccannt** [comment]
@robross0606 and @datacart 
Just following up on this item. There is no way that we can stop these updates but we are looking into this fix as well as future improvements surrounding this functionality.

**Comment by robross0606** [comment]
@mccannt, then updates are a pretty big hole in your design that also needs to be addressed.  Updates need to be able to be shut off COMPLETELY.  Frankly, no one cares what you classify as "minor" vs "major" upgrade.  People turn off updates because they need consistent repeatable behavior, want to limit network usage, and more.  Many people need a tool that's not going to change out from underneath them at any time, regardless of whether the developer thinks (incorrectly if this bug is any indication) that this is a "minor" change.  This is also a red flag security risk for places where version control is critical and software is tracked.  I see that this is already being tracked in #6999.

**Comment by robross0606** [comment]
@mccannt, might there be a way to restrict auto-updating with a firewall rule?  Hopefully without affecting API syncing, but I'd be willing to sacrifice API syncing to get a Postman install that was, ya know, functional.

**Comment by JosephDHenry** [comment]
ok, so I really got tired of having to install the old version that worked just to have it automatically updated to the new version, so I added this entry to my hosts file:

127.0.0.1 dl.pstmn.io

The update will now fail since it tries to go to localhost.

This is not ideal, but at least I can stay at a version that works until this bug is fixed.

**Comment by robross0606** [comment]
@datacart, I thought about doing something like that or creating a firewall rule, but worried that it would also prevent syncing across devices (history, collections, API, etc.).  I asked @mccannt  this earlier but never got a response.

**Comment by JosephDHenry** [comment]
@robross0606, Well I am not 100% sure, but it seems that syncing still works and that only updates are blocked by this. It was either this or continually installing an old version.

**Comment by robross0606** [comment]
The problem with this approach is that you can't even download the app from a browser at that point.  I was hoping to be more specific with a firewall rule but I'm not sure that's possible either.  What a PITA...

**Comment by robross0606** [comment]
Crap, now they removed the download links for the older versions?!  Is the Postman team actively TRYING to alienate users?!

**Comment by kamalaknn** [comment]
Hi everyone,

We have pushed a fix for this now on our Canary channel now. You can find the latest Canary app here https://www.getpostman.com/downloads/canary

We will keep this thread updated when this fix is released on the stable channel.

**Comment by pearlberry** [comment]
It is shocking that this took over 2 months to fix and be available BUT I am now on Version 7.6.0 and this is, in fact, fixed. A true miracle.

**Comment by robross0606** [comment]
Oddly enough, neither Github ticket (#7255 and #6832) is mentioned in any of the release notes.
https://www.getpostman.com/downloads/release-notes

**Comment by kamalaknn** [comment]
@robross0606 Thanks for pointing it out. I've updated the release notes now.

**Comment by kenuw** [comment]
@kamalaknn @mccannt Just wondering if this problem has resurfaced. I'm having problems clicking on relative links on v8.3.0. First time launching postman and clicking on links in response work but subsequent clicks on links do not work. Resorting to copy/paste in new tab which is time consuming.  Thx

**Comment by mccannt** [comment]
@m365ken We are sorry you are experiencing this issue. I have just tried this locally on v8.3.0 in macOS and it's working for me as expected. 

Are you able to give us more detail or an example?

**Comment by kenuw** [comment]
Problem occurs on Win10 v2004 and on Windows Server 2019. The problem appears to be isolated to links in the response body from an Azure Durable function. Other links are working for me. Thx

**Comment by dmwatan** [comment]
I'm seeing this issue on a Mac too. Currently Postman v8.5.1. It seems to happen if you actually do something with the new tab that's opened from clicking on a link. If you don't click "Send" on the new tab (i.e. just close it), links continue to work from the originating tab. So like this:
- Orig tab: click on link, opens new tab
- New tab: close this tab
- Orig tab: click on same link as before (or any other link), opens new tab
- New tab: click send, optionally close this tab
- Orig tab: click on any link, none open new tabs anymore

I don't recall which version this started happening in, but it was in the past few months. Previously links always worked from all tabs regardless of subsequent actions.

As an example, use the github jobs api: https://jobs.github.com/positions.json?description=api
Click on any "url" value and do a get in the new tab to retrieve details about the position. Clicking on any links in the first tab no longer works for me.

**Comment by and-za** [comment]
I can confirm that I have the same issue as @dmwatan. Postman version 8.6.1 running on Lubuntu 20.04.

What seems to help is to close the original tab and open it again. But it helps only temporarily - till you open link from response in new tab and hit the send button.
