### ISSUE TITLE
Manage multiple auth servers

### ISSUE THREAD

**Issue by mcandre** [a85/POSTMan-Chrome-Extension#6833]
**Is your feature request related to a problem? Please describe.**

When developing against multiple authentication servers, I often have to edit the Get New Access Token form to switch the server address and client credentials back and forth.

**Describe the solution you'd like**

Offer an authentication server management list, similar to the token management list, so that I can rapidly select between multiple authentication server profiles.

**Describe alternatives you've considered**

cURL

**Comment by shamasis** [comment]
Neat idea. I’ve added appropriate tags to the issue to ensure we pick it up when we next address authentication feature improvements.

**Comment by balane** [comment]
+1

**Comment by KoffeeToKode** [comment]
+1

**Comment by giridharvc7** [comment]
This feature is now built into our OAuth2 Authorization, please let us know if this solves your problem. 
<img width="547" alt="Screenshot 2021-04-14 at 3 31 14 PM" src="https://user-images.githubusercontent.com/1040583/114692686-7617d400-9d36-11eb-8e02-2b58d475bff0.png">
