### ISSUE TITLE
Proxy settings not working on Mac 

### ISSUE THREAD

**Issue by bcheerla4509** [a85/POSTMan-Chrome-Extension#6836]
**Describe the bug**
We have downloaded postman app for mac and were trying to use proxy settings for postman with various options. The end URL is accessible only through a proxy server so we wanted to use proxy before hitting end URL.
From Mac, we tried curl command to reach end URL via proxy and it worked. We also were able to SSH to proxy server with same credentials used for CURL.
Option 1:
So we have tried setting global proxy through settings in postman but didn't work
Option 2:
Created a script to export http_proxy and https_proxy then started postman but didn't work.
Option 3: 
Had setup proxy at MAC system level and launched postman but didn't work.

**To Reproduce**
1. Go to the path where postman was downloaded
2. Click on Click on Postman
3. Open settings and setup global proxy settings
4. Send a GET request and get server can't be reached.

**Expected behavior**
GET should be resulted to 200 OK and give expected result

**Screenshots**
If applicable, add screenshots to help explain your problem. Please make sure the screenshot does not contain any sensitive information such as API keys or access tokens. 

**App information (please complete the following information):**
 - App Type :  Native App
 - Postman Version: 7.2.2
 - OS: macOS 

**Additional context**

**Comment by codenirvana** [comment]
@bcheerla4509 Please share more details about the proxy.
Does it require authentication? If yes, what's the type of auth (Basic or NTLM)?

**Comment by codenirvana** [comment]
Closing this issue as we are not able to reproduce this internally and we haven't seen other users facing the same.

Please feel free to reopen if the issue persists or you can help us with the steps to reproduce this issue.

**Comment by HarshadKulkarni** [comment]
i am facing same issue, Does it require authentication? Yes,  what's the type of auth (Basic or NTLM)? Basic (username/password)
