### ISSUE TITLE
Collection Runner Preview display for json data file is not showing Object Values in postman version 7.2.2 desktop app

### ISSUE THREAD

**Issue by spdkb** [a85/POSTMan-Chrome-Extension#6837]
![image](https://user-images.githubusercontent.com/26374040/60566929-4cd2b300-9d1d-11e9-803b-7ee684b991cb.png)
![image](https://user-images.githubusercontent.com/26374040/60566933-522ffd80-9d1d-11e9-8ee9-bbfb3e3d8472.png)

**Comment by codenirvana** [comment]
@spoloju We've pushed a fix for this on `v7.6.0`. Can you update your app and confirm if this fixes your issue?
