### ISSUE TITLE
Postman Runner is slow when the collection consists of more than 150+ requests. 

### ISSUE THREAD

**Issue by spdkb** [a85/POSTMan-Chrome-Extension#6838]
1. Create Collection with more than 150+ Request with approx 20  Main Folder & 20 Subfolders  (ex - 150 is divided across 20 Main & 20 Subfolders)
2. Launch Runner & select collection
3. Select JSON Data file  
4.  Select Run Button
5. Collection requests will be executed successfully
6. On Collection Runner > Select Button (ex-New, Retry buttons, etc) 

Issue - You will Observe Slowness. 
 
- App Type - Native App
 - Postman Version - 7.2.2 
 - OS: Windows 10

**Comment by shamasis** [comment]
😱 oh no! We were tracking a performance issue - but for a much unreasonable size. https://github.com/postmanlabs/postman-app-support/issues/6525

150 request slowing runner down isn’t acceptable. Can you check if you’re unchecking the option that retains responses? Having said that, we will re evaluate the runner performance benchmark and can definitely disk buffer some aspects to avoid slowdown. 

I’m closing this issue as a duplicate and tracking this in main thread.

**Comment by shamasis** [comment]
On a second thought, I’m keeping this opened until we append some insights to this thread.

**Comment by saswatds** [comment]
We have pushed all of our performance fixed to the stable version 7.18.0. The runner should be snappier and not crash.
I am closing this issue and tracking all the performance issue on #6525 as master issue
