### ISSUE TITLE
GitLab integration not working with new Merge feature

### ISSUE THREAD

**Issue by ghent12345** [a85/POSTMan-Chrome-Extension#6840]
**Describe the bug**

Hi this is not a major issue but an issue I thought was worth mentioning nonetheless.

I have recently started using GitLab integration for backing up my collections to a repository, which has been great.

However I have also been using the new fork/merge feature that Postman has introduced recently.

The issue is when you fork a collection, make changes and then merge it in, the GitLab integration is not triggered, therefore the newly merged changes are not backed up.

A current work around I have identified is once you have merged your changes, go in to the collection and make the tiniest of changes, then save and the GitLab integration will pick this change up AS WELL as all the earlier merge related changes.

**To Reproduce**
1. Create a GitLab integration to back up collections to a repository
2. Fork the collection from above
3. Make some changes
4. Merge the changes in to the collection

**Expected behavior**

An update to the collection in the GitLab repository

**Screenshots**

Not really applicable

**App information (please complete the following information):**
 - App Type Native App
 - Postman Version v7.2.2
 - OS: Windows

**Comment by ankit-m** [comment]
This issue has been fixed. If it persists, please reopen this ticket.
