### ISSUE TITLE
Feature request: Sort globals in alphabetical order

### ISSUE THREAD

**Issue by VicKetchup** [a85/POSTMan-Chrome-Extension#6841]
**Is your feature request related to a problem? Please describe.**
We use a ton of global variables for our Automation, however when testing manually sometimes it makes more sense to change the global, which becomes quite difficult with large amount of them. You end up going up and down a list a few times before you can spot the right one.

**Describe the solution you'd like**
At the moment globals seem to be sorted in order of their creation, this should either be changed or an option should be provided to sort them in alphabetical order, which will make it much simpler to look through.

**Comment by VicKetchup** [comment]
Possible other solution, allow to search through variables and their values within the Environment quick look and Manage Environments windows with ability to edit.

**Comment by ryanbu-zillowgroup** [comment]
Please do this

**Comment by byrdman** [comment]
This would be quite useful, our automation also utilizes a sizeable number.  I've been manually sorting them but that's a pain.

**Comment by giridharvc7** [comment]
Hello folks, we have released sorting & filtering on variables in our latest update to Postman (10.12) - the update is being rolled out, you will get it in the next couple of days if you haven't already.

You can read about the latest updates we have on variables and its management [here](https://blog.postman.com/faster-and-easier-variable-management-in-postman/). We hope you like these updates. Thank you for your patience and your feedback, we really appreciate it. 

![Sort](https://user-images.githubusercontent.com/1040583/225613544-6b3754c2-7550-41f5-b00e-57c287ded079.gif)
