### ISSUE TITLE
Feature request: Use this for all when resolving conflicts in merge

### ISSUE THREAD

**Issue by VicKetchup** [a85/POSTMan-Chrome-Extension#6842]
**Is your feature request related to a problem? Please describe.**
We have created forks for each of the environments we have for our API and in some cases changes happen only in one of the environments causing Merge Conflicts. Currently you have to go to each conflict and select the source and since there is no ability to jump to next conflict and you have to scroll, it takes quite a bit of time.

**Describe the solution you'd like**
When there are conflicts it would be great to have a buttons to "Use all from Destination" or "Use all from Origin".

**Describe alternatives you've considered**
Using search (Ctrl + F) to look for "Use this", however in the case of many conflicts, this still is a tedious task

**Comment by ankitjaggi** [comment]
This is now available in the latest version of the app.
