### ISSUE TITLE
Changelog for environments

### ISSUE THREAD

**Issue by VicKetchup** [a85/POSTMan-Chrome-Extension#6843]
**Is your feature request related to a problem? Please describe.**
Sometimes team members may accidentally save a request that removes dynamic variables after doing some manual testing and not even realise they've done so. 
Also if any member deletes a global or environment variable, this affects everyone, but no safe-guards are in place.

**Describe the solution you'd like**
Any changes that get reflect for everyone should have a confirmation pop-up.

**Comment by preethammavin** [comment]
@VicKetchup It would be a hard step if each save were to ask for a confirmation, as many collections are being worked upon in a collaborative environment. For Collection I would suggest that you only give edit permission to the users who would want to edit the collection, rest can still use variables for collection runs and edit request and send if they want to send it manually

We are also looking at give role based access control to the rest of the elements such as environments and globals etc.

**Comment by VicKetchup** [comment]
@preethammavin I think there was a bit of misunderstanding in what I am asking for :) 
We already restrict who can edit the collections, however a lot of the users who can edit are also manual testers, who may by accident Save the changes they've done.
What I am asking is confirmation on the screen of the person who is saving the changes/persisting variables etc., so just a little safe-guard to ensure that the change is intentional.

**Comment by sankalp0o** [comment]
Hi @VicKetchup prevention of accidents and data loss is very important to us. Like Preetham said, we do want to look into more control over editing environments. However for collections, it is a fine line between providing control (through confirmation etc) and frustrating people who are just going about their routine. We'll relook at collection editing experience to allow control wherever possible.

By the way, Collections maintain a changelog and allow you to revert back. Is this something that's not working for you?

**Comment by VicKetchup** [comment]
@sankalp0o It may be that I am missing something, however the option to revert is not present for us, assuming this is because we don't do API Versioning, please refer to: 
https://github.com/postmanlabs/postman-app-support/issues/6845
https://github.com/postmanlabs/postman-app-support/issues/6844

**Comment by VicKetchup** [comment]
Just wanted to update the status, as per discussion in https://github.com/postmanlabs/postman-app-support/issues/6845, I've managed to find the "Revert" option, so that definitely will help with some of the headache.
However recently it's been the changes to the environment variables that is causing us some issues, as someone is changing the booking data to the ones that don't have all the info to properly run our collections, causing a lot of failures. There is no way to identify who may be doing it and again, there are no safe-guards to warn the user that they changed something for everyone.

**Comment by sankalp0o** [comment]
Right now, I think the following 2 features should help you achieve the control you want
1. Roles on environments so that some people are not allowed to change values for the whole team, but only for themselves. We are tracking this in #6596 
2. A changelog for environments, which will help you revert if someone accidentally made changes.

I'm renaming the issue accordingly. I will update you when we have progress on this, thanks for helping us understand the problem!

**Comment by ankit-m** [comment]
Marking this as duplicate and tracking #5552
