### ISSUE TITLE
Feature request: Ability to revert changes in "Activity"

### ISSUE THREAD

**Issue by VicKetchup** [a85/POSTMan-Chrome-Extension#6844]
**Is your feature request related to a problem? Please describe.**
Sometimes a change is saved that was unwanted and there is no way to revert it. This is mainly cause by accidental saves as per this issue: https://github.com/postmanlabs/postman-app-support/issues/6843

**Describe the solution you'd like**
In the Postman app you can view Activity for the workspace, with any changes that were done to the requests. An option should be added to revert those changes.

**Describe alternatives you've considered**
Manually reverting any of the reported changes in the Activity, which may not be clear in some cases.

**Comment by preethammavin** [comment]
@VicKetchup for changes in the collection which are saved the collection can be reverted to an earlier version by going to the Collection Change-log and selecting which revision of the collection you want to restore and clicking on restore. Can you confirm if this resolves your case.

**Comment by VicKetchup** [comment]
@preethammavin with our workflow we do not create a whole new version of the APIs, many of the changes are just related to content changes, while the actual response contract stays the same. We are also creating a lot new endpoints for new features, which again, doesn't fit with API revisions strategy. We therefore don't use the API versioning functionality and need a way to be able to revert a specific single change.

**Comment by preethammavin** [comment]
Sorry I should have worded it better, we give change-log for collections in the collection browser. This can be found by hovering on the collection and clinking on the right arrow mark to see the collection browser and under change-log you would see how your collection has evolved through revisions and restore to a chosen revisions to revert changes

For more information you can refer to the doc below
https://learning.getpostman.com/docs/postman/workspaces/activity_feed_and_restoring_collections/#restoring-collections
