### ISSUE TITLE
Feature request: Ability to revert merges

### ISSUE THREAD

**Issue by VicKetchup** [a85/POSTMan-Chrome-Extension#6845]
**Is your feature request related to a problem? Please describe.**
This is more of an edge case, however we had to do a revert of our Production environment after couple of days, meaning we should revert the merge from Pre-Prod branch. Unfortunately there was no way to view the history and revert to any of the previous states.

**Describe the solution you'd like**
Collections should have merge history with ability to roll back to a specific version (maybe make that time restricted if storage is a concern).

**Comment by preethammavin** [comment]
@VicKetchup we do let users to restore the collection to an earlier version by looking at the collection change-log. Which reflects the changes which has occurred on the parent collection due to the merge activity, but we will work to see if we show a merge as an activity itself. 

@vkaegis

**Comment by VicKetchup** [comment]
@preethammavin Maybe I am missing something, however without API versioning (that we don't do for our workflow) there doesn't seem to be an option to revert any changes. As per your comment here (https://github.com/postmanlabs/postman-app-support/issues/6844#event-2462945077) 

> under change-log you would see how your collection has evolved through revisions and restore to a chosen revisions to revert changes

We do not have "revisions" and no "Restore" option is shown anywhere, I've looked through activities in the app as well as web interface.

**Comment by preethammavin** [comment]
@VicKetchup this is something which is available to our Pro and Enterprise users , for reference I have attached the collection change-log in the screenshot below 
<img width="909" alt="Screenshot 2019-07-08 at 12 03 06 PM" src="https://user-images.githubusercontent.com/34742239/60835688-a4877900-a178-11e9-975d-fa1639e3b53a.png">

**Comment by VicKetchup** [comment]
@preethammavin SO I was missing something :) I found the option now and will use it to see if it resolves some of our issues. Thank you very much.

**Comment by VicKetchup** [comment]
The suggested solution is working fine for us, closing the ticket.
