### ISSUE TITLE
Postman native Mac app forces focus on itself twice during startup

### ISSUE THREAD

**Issue by verheyenkoen** [a85/POSTMan-Chrome-Extension#6849]
**Describe the bug**
Whenever I start the Postman app, during loading, Postman takes the focus to itself twice. Usually what I do is start up Postman, switch to another space to continue working (cause who needs to see splash screens?). Then all-of-a-sudden my screen switches back to the space where Postman is loading. And if I switch to another space again, Postman does that a second time. That is very annoying. I know Postman needs some time to load, that's ok, I'll come back when I'm ready to use it. No need to interrupt me twice.

**To Reproduce**
1. Start Postman
2. Swipe to another space
3. Postman takes control back
4. Swipe to another space again,
5. Postman takes back control a second time

**Expected behavior**
Postman should just load and leave the focus alone.

**App information (please complete the following information):**
 - Native App
 - Postman Version: v7.2.2
 - OS: macOS Mojave v10.14.5

**Comment by CodePint** [comment]
+1

This still causes me daily annoyances on ubuntu 20.04 LTS
Any ideas or timelines for a fix? Is there any way I can help or contribute to a fix?

**Comment by verheyenkoen** [comment]
@CodePint I switched to using [Insomnia](https://insomnia.rest/).

**Comment by jviotti** [comment]
Merging this with https://github.com/postmanlabs/postman-app-support/issues/8935
