### ISSUE TITLE
Monitor Console log shows wrong URL for the request

### ISSUE THREAD

**Issue by VicKetchup** [a85/POSTMan-Chrome-Extension#6850]
**Describe the bug**
In our collection we have a test to validate the response against swagger. In order to load a correct for the endpoint version swagger, in collection level test we send a request to grab it. When I looked at the monitor logs I saw that for a few requests the URL was set to our swagger rather than the actual request.

**To Reproduce**
1. In collection level test create a pm.sendRequest.
2. Run a monitor on the collection with some requests.
3. Some of the requests will have URL set to the one for pm.sendRequest.

**Expected behavior**
URL of the actual request should be displayed in the log.

**Screenshots**
Can't show screenshots for security reasons

**Comment by AnkitMasand** [comment]
@VicKetchup Is it possible to share a sample collection (without sensitive data) which we can use to reproduce this issue?

**Comment by VicKetchup** [comment]
@AnkitMasand Will give it a shot and give you an update asap.

**Comment by VicKetchup** [comment]
Was able to reproduce it, please see the attached collection and here are screenshots from monitor showing wrong URL:
![image](https://user-images.githubusercontent.com/43671684/60824556-758df900-a1b2-11e9-972f-18d8db5ae6ca.png)
![image](https://user-images.githubusercontent.com/43671684/60824681-af5eff80-a1b2-11e9-9430-d209d3994521.png)

[Wrong URL in Console Log (Monitors).postman_collection.json.zip](https://github.com/postmanlabs/postman-app-support/files/3369232/Wrong.URL.in.Console.Log.Monitors.postman_collection.json.zip)

**Comment by AnkitMasand** [comment]
@VicKetchup Thanks for reporting this. We have identified the bug that is causing the wrong information to get displayed. We will be pushing out the release soon and will inform you once it's done. Kindly acknowledge once after that.

**Comment by VicKetchup** [comment]
Using current version of Postman (7.10.0) the issue seems to be resolved and haven't spotted it in the logs since your comment :) 
![image](https://user-images.githubusercontent.com/43671684/67576832-3d95cc00-f737-11e9-97a0-b8e1c41abd6d.png)

**Comment by VicKetchup** [comment]
The issue is unfortunately back, can be seen in Native app and on Monitors.

**Comment by shivam-postman** [comment]
Hey @VicKetchup, are you still facing the issue? I tried reproducing it with the collection you provided earlier and one of my own, but the URL seems correct on the monitoring logs.

**Comment by VicKetchup** [comment]
Hi @shivam-postman it is still an issue on our Monitors, will check if I can reproduce on the one previously provided.
![image](https://user-images.githubusercontent.com/43671684/77069030-92d0c380-69df-11ea-8503-f7b8f42b91e1.png)

**Comment by VicKetchup** [comment]
Just ran the previously shared collection Monitor and got the issue:
![image](https://user-images.githubusercontent.com/43671684/77069454-5c477880-69e0-11ea-86d2-3ea7253c0484.png)

**Comment by shivam-postman** [comment]
Ah, the URL is wrong in the test results for me too. I was checking the console log earlier. We'll look into it and get back soon 👍

**Comment by shivam-postman** [comment]
Hey @VicKetchup, can you check whether the correct URLs are being displayed now?

**Comment by ArjunSingh-PM** [comment]
Hi @VicKetchup, this issue has been resolved. Please reopen this issue if you continue to see this issue.
