### ISSUE TITLE
Doing a search (Ctrl/Command + F) with Console Log open freezes the page in Chrome

### ISSUE THREAD

**Issue by VicKetchup** [a85/POSTMan-Chrome-Extension#6851]
**Describe the bug**
When using the page search functionality in Chrome on Monitor results page with Console Log open, the page freezes. Usually nothing can be done and trying to refresh it will just keep it as it is, a new tab needs to be open, however sometimes Chrome will report the tab as unresponsive.

**To Reproduce**
1. Go to Monitor page
2. Select one of the runs
3. Select Console Log
4. Search for something
5. The tab will freeze

**Expected behavior**
Tab should not freeze.

**Screenshots**
![image](https://user-images.githubusercontent.com/43671684/60594896-9e774e00-9dae-11e9-9083-f0debcb2cfb8.png)
 

**App information (please complete the following information):**
 - App Type: Monitors/Chrome
 - Postman Version: N/A
 - OS: N/A

**Comment by preethammavin** [comment]
@VicKetchup I am unable to reproduce this. Does this happen on every monitors console log?

**Comment by VicKetchup** [comment]
@preethammavin on all of hours as far as I've tested, it maybe be due to amount of info we log (the response (original and the one without non-mandatory fields that were returned as null), relevant swagger (original and the one edited for x-nullbale support), the actual cURL and some other small bits.

**Comment by shivam-postman** [comment]
Hey @VicKetchup, we carried out some tests. Turns out that searching through large data sets is slow in general for all the websites and often freezes the page. It looks like a browser level optimisation.
Can you specify how much data were you dealing with, during the search? Thanks.

**Comment by VicKetchup** [comment]
@shivam-postman Had a look at our logs and at the maximum 4413 lines of console log.

**Comment by godfrzero** [comment]
@VicKetchup More than lines, it's the number of characters (actually the size of search data in memory) that affects this performance. Based on all of our testing, the only case where we could find a situation where the browser performance degrades is with large data sets, which affects the browser regardless of the webpage. One thing we can do is refrain from rendering all of the logs at once, but this will also have two other effects:
- The in-built browser search will not work directly
- We'll have to build a custom search functionality into the console log section of the monitoring Dashboard UI

**Comment by VicKetchup** [comment]
@godfrzero I guess we can close this issue unless you are ok with making custom search into console log :)

**Comment by VicKetchup** [comment]
@godfrzero @shivam-postman @preethammavin Feel free to close this or convert to a Feature request for custom search.
