### ISSUE TITLE
Automatically persist variable values should be OFF by default

### ISSUE THREAD

**Issue by VicKetchup** [a85/POSTMan-Chrome-Extension#6852]
**Is your feature request related to a problem? Please describe.**
We have a lot of data that manual testers may use, however that data may not be the wanted for monitor runs as it wouldn't cover all of the endpoints and scenarios. With this option being ON by default, any new members or for any new installations of Postman App could cause the data to be overwritten which is really undesirable behaviour. 

**Describe the solution you'd like**
This option should be OFF by default to prevent issues especially for the workflows where this is dangerous.

**Describe alternatives you've considered**
We have Postman documentation for our company that specifically tells people to turn this off, however people may forget to do this, especially when they reinstall the app or get a new machine to work on.

**Comment by shamasis** [comment]
Yep. We had this turned on to ease transition from original behaviour. We will set the default to be turned off very soon in future.

**Comment by powelli** [comment]
Given that session variables are currently suggested as a Postman best practice for storing sensitive environment values (API keys, passwords etc.) this seems like a bit of security risk. New team members may easily leave this setting enabled and therefore share sensitive values with the entire team when they update their "current" session variables.

Also related is the suggestion to manage this setting at a team level - https://github.com/postmanlabs/postman-app-support/issues/5146

**Comment by VicKetchup** [comment]
> Yep. We had this turned on to ease transition from original behaviour. We will set the default to be turned off very soon in future.

It's been quite a while now and multiple new versions have been released, however this setting is still ON by default, when can we expect to see that change, surely it's not hard to do.

**Comment by appurva21** [comment]
Hey @VicKetchup !!
We have turned off this setting by default for all the new installs (and new logins) starting from app version `7.20.0`.
We will be keeping this setting as it is for all the existing installs of the app prior to version `7.20.0`.

I am closing this issue, but feel free to reopen it in case the issue still persists.

Thanks
