### ISSUE TITLE
Pulling changes to fork before updating throws error

### ISSUE THREAD

**Issue by JP-from-Postman** [a85/POSTMan-Chrome-Extension#6853]
**Describe the bug**
[Reported by Postman Support, on behalf of original user]
User has a fork of a Collection, and is trying to pull changes from the parent Collection before merging changes.

Clicking Pull Changes results in a blank page, with the following errors in the browser console:

`raven.js:51 TypeError: e.split is not a function`

`raven.js:51 uncaught at fetchCollectionDiff TypeError: e.split is not a function`

**To Reproduce**
Unknown

**Expected behavior**
Changes are pulled successfully

**Screenshots**

**App information (please complete the following information):**
 - App Type: Native app, Dashboard
 - Postman Version: 7.2.2
 - OS: Windows

**Additional context**
See internal notes for complete logs

**Comment by Ghusar** [comment]
@JP-from-Postman We have pushed a change where this issue is fixed. can we confirm with user?

**Comment by JP-from-Postman** [comment]
@Ghusar reached out to user to confirm. Will update with response.

**Comment by ankit-m** [comment]
@JP-from-Postman closing this issue as the last update was over a month ago. If the issue still exists, feel free to reopen.
