### ISSUE TITLE
eval(pm.globals.get("commonTests"): not working in folder tests

### ISSUE THREAD

**Issue by jonathan3087** [a85/POSTMan-Chrome-Extension#6854]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. Please make sure the screenshot does not contain any sensitive information such as API keys or access tokens. 

**App information (please complete the following information):**
 - App Type [e.g. Chrome App, Native App]
macOS Native App
 - Postman Version [e.g. 6.0.1]
Version 7.2.2
 - OS: [e.g. macOS High Sierra 10.13.2]
macOS Mojave 10.14.5
[Test APIs.postman_collection.json.zip](https://github.com/postmanlabs/postman-app-support/files/3356671/Test.APIs.postman_collection.json.zip)

**Additional context**
When I run the collection all the tests run for the Status Requests folder, but when the Register Requests folder runs, it doesn't re-perform the common tests for that folder.

**Comment by coditva** [comment]
Hi @jonathan3087, I went through the collection you shared and I think you might have missed a few things in the test scripts.

Firstly, you must serialise a function when putting it in a variable like this:
```js
pm.globals.set("commonTests", commonTests.toString())
```

Secondly, in the code you shared, `commonTests` is a reference for an anonymous function (arrow function) and when you use `pm.globals.set("commonTests", commonTests.toString())`, the value that gets stored in the global variable is: `() => { ... }` and not `function commonTests() { ... }`. So the correct code might look something like this:
```js
function commonTests() {
	...
}
pm.globals.set("commonTests", commonTests.toString());
```

Thirdly, when you execute `eval(pm.globals.get("commonTests")`, the code that is executed is `function commonTests() { ... }`. You must call the function after this to run it, like this:
```js
eval(pm.globals.get("commonTests");
commonTests();
```

You can even ensure that the function gets called in a single line IFFE like this:
```js
eval("(" + pm.globals.get("commonTests") + "())");
```
_NOTE: You can also use arrow functions with IFFE._

**Comment by jonathan3087** [comment]
Those changes worked perfectly.  Thanks so much.
