### ISSUE TITLE
unable to sign in

### ISSUE THREAD

**Issue by pravat-sahoo** [a85/POSTMan-Chrome-Extension#6856]
![error](https://user-images.githubusercontent.com/26546426/60644134-c9b37900-9e52-11e9-8c2f-07d6a6d66736.PNG)

unable to login.

pravat@nalashaa.com

**Comment by elssar** [comment]
@pravat-sahoo can you login to the Postman dashboard via the browser, or to the Postman app from another network? If you can then this is likely a firewall or proxy preventing the Postman app from connecting to our authentication service. If you have a firewall or proxy configured, could you update the rules to allow the app to connect to our authentication service.
In case the issue persists, you can email us at help@getpostman.com with the app logs and we'd be happy to help you.

How to get the logs -

Console logs
1.1 View --> Developer --> Show DevTools(Shared)
1.2 View --> Developer --> SHow DevTools(Current View)

Log files
2.1 All log files from View --> Developer --> View logs

**Comment by pravat-sahoo** [comment]
it's now working
