### ISSUE TITLE
Autocomplete doesn't appear in GraphQL for JSON type

### ISSUE THREAD

**Issue by Raj-postman** [a85/POSTMan-Chrome-Extension#6858]
**Describe the bug**
When type [JSON] is used, the query autocomplete isn't working on GraphQL.

**To Reproduce**
1. Create new API under APIs Tab
2. Select Schema as GraphQL
3. For type [JSON] query doesn't autocomplete

**Expected behavior**
Autocomplete be working the same for all types

**Screenshots:**
If image type [JSON] not working:
![image](https://user-images.githubusercontent.com/47771757/60665582-7822e280-9e82-11e9-8912-e174f778e251.png)

**App information:**
 - App Type - Native App
 - Postman Version - v7.2

**Additional context**
 If type [String] the query autocomplete is working. By changing datatype in GraphQL type from [String] to [JSON] and back to the collection and type something, query autocomplete isn't working anymore.

**Comment by kamalaknn** [comment]
@Kurmavathar GraphQL spec only lists Int, Float, Boolean, String, ID as predefined scalar types, see - https://graphql.github.io/graphql-spec/June2018/#sec-Scalars JSON is not defined as a predefined scalar. Although defining it as a custom scalar would still be valid. Are you using JSON type without defining it as a custom scalar?

Am I missing something?
