### ISSUE TITLE
Opening and URL in the browser changing characters to hex code

### ISSUE THREAD

**Issue by agataciesielska** [a85/POSTMan-Chrome-Extension#6860]
**Describe the bug**
While opening the link received in the response, postman sends incorrect url to the browser.

**To Reproduce**
1. Go to postman.
2. Send some request, considering it return any url with parameters.
3. Press ctrl on your keybord and click on the link in the response.
4. Browser doesn't recognize the url: https://secure.payu.com/info/?orderId%3DP22FF8HWJR190705GUEST000P01%26token%3DeyJhbGciO...

**Expected behavior**
Postman should send unconverted url to the browser, eg. https://secure.payu.com/info/?orderId=P22FF8HWJR190705GUEST000P01&token=eyJhbGciO...

**App information (please complete the following information):**
 - Chrome 75.0.3770.100 x64
 - Postman Version 7.3.1
 - OS: Windows 10 Pro x64

**Comment by shamasis** [comment]
Ah. We did some improvements to the parsing of response and it’s subsequent linking. Maybe we broke something unintentionally. We will have a look and get back asap.

**Comment by kamalaknn** [comment]
Thanks @agataciesielska for reporting this.

This seems to have come up from the decoding handlers for the new link detectors in response view. We'll get this fixed and update this thread.

**Comment by kamalaknn** [comment]
@agataciesielska This is fixed on the latest version of the canary channel now. 

You can download the canary version from here - https://www.getpostman.com/downloads/canary

**Comment by agataciesielska** [comment]
@kamalaknn great! Thanks for the fix.

**Comment by kamalaknn** [comment]
This fix should be available on the stable channel now. Please update your app to the latest version and let us know if the issue still exists.
