### ISSUE TITLE
Deep link to enterprise domain login

### ISSUE THREAD

**Issue by JP-from-Postman** [a85/POSTMan-Chrome-Extension#6865]
**Is your feature request related to a problem? Please describe.**
For Enterprise teams, clicking `Enterprise user? Sign in here` requires a domain to be manually entered.

**Describe the solution you'd like**
Provide enterprise teams with a deep link directly to a login page for their domain. Example:

https://identity.getpostman.com/enterprise/<domain>/login

**Describe alternatives you've considered**
None

**Additional context**

**Comment by anudeepmedicharla** [comment]
@JP-from-Postman Thanks for raising the feature request! Was thinking of having something similar for enterprise accounts. @preethammavin We can use the default team domain URL (team-name.postman.co) too for logging in.

**Comment by ArjunSingh-PM** [comment]
Now, use any URL for your team for the form https://<team_domain>.postman.co/ to log into your team. For example, the URL https://postman.postman.co/ allows users to log in to the Postman team from an authentication page specific to that team. 

In addition, one can use the following URL to navigate to a specific Postman team directly:

URL: https://identity.getpostman.com/enterprise/login/authchooser?target_team=<team_domain>

For example, for the Postman team, the URL is https://identity.getpostman.com/enterprise/login/authchooser?target_team=postman
