### ISSUE TITLE
Account switch was not successful 

### ISSUE THREAD

**Issue by Raj-postman** [a85/POSTMan-Chrome-Extension#6867]
**Describe the bug**
Accidentally deleted workspace because of a bug that didn't switch the account

**To Reproduce**
1) Navigate to Account A
2) Export and import collection into Account B
3) Switch to Account A and Delete Workspace
But accounts did not switch, it signed in with Account B and workspace of Account B was deleted instead of A

**Expected behavior**
Be able to delete the required workspace, switch accounts properly.

**App information (please complete the following information):**
 - App Type - Native App
 - Postman Version - v7.2.2

**Additional context**
Reported by Postman

**Comment by preethammavin** [comment]
@Kurmavathar I am unable to reproduce this, have renamed the issue appropriate to the issue reported. Are there any steps to reproduce the issue where the account did not switch? or Did the UI have workspaces of the older account after switching?

**Comment by Raj-postman** [comment]
@preethammavin Couldn't replicate this from my end, but this is in connection to the data loss issue reported by a user and raised this for tracking issues on the same line.

**Comment by sankalp0o** [comment]
@Kurmavathar Looking at the original ticket, I see the user mentioning exporting and importing workspaces between multiple accounts, which is not something that we support. Can we dig deeper into this and figure out the root cause for the confusion between workspaces/accounts?
