### ISSUE TITLE
Problem with cache memory 

### ISSUE THREAD

**Issue by Michal-Kolomanski** [a85/POSTMan-Chrome-Extension#6869]
Hello,

I have a problem with overfilling cache memory, using long newman runs. I run collection which adds some data to my database in live mode. It shouldnt stop but when its working about 2 hours, cache memory is filled and my computer stops working properly.

My computer has 8 GB RAM but its not enough.
![image](https://user-images.githubusercontent.com/47147210/60802517-5b83f480-a179-11e9-8058-06dbb30a13b6.png)
Durning run, free cache memory is dropping. Old data (which is useless for me) is kept and released too slow which cause overfilling cache memory.

Moreover, I have “send no-cache header” option on but this dont do anything for me.
I pulled a issue on postman community too: 
https://community.getpostman.com/t/problem-with-cache-memory/6369
Feel free to close this one if somewhere my problem will be resolved.

Have can I cope with this?
Thanks for any kind of help.

**Comment by codenirvana** [comment]
@michal19256 Thanks for reporting this issue.
We are tracking similar issues in Newman:
https://github.com/postmanlabs/newman/issues/935
https://github.com/postmanlabs/newman/issues/941

Closing as duplicate.
