### ISSUE TITLE
Error "Something went wrong" when running a collection

### ISSUE THREAD

**Issue by labifrancis** [a85/POSTMan-Chrome-Extension#6871]
**Describe the bug**
A user gets this error "Something went wrong" when trying to run a collection

**Expected behavior**
The collection should run without an error

**Screenshots**
![image](https://user-images.githubusercontent.com/10200603/60813784-52505300-a18c-11e9-9c4b-832d73eb6d41.png)

**App information (please complete the following information):**
 - App Type - Native App 
 - Postman Version 7.2.2
 - Windows

**Comment by saswatds** [comment]
Closing this issue as we are not sure how to replicate this issue. Feel free to reopen if your have more information. 

Thanks
