### ISSUE TITLE
Collection lost on changing accounts of a user

### ISSUE THREAD

**Issue by Raj-postman** [a85/POSTMan-Chrome-Extension#6872]
**Describe the bug**
The collection shared with the team by the user is lost on removing the user

**To Reproduce**
1. User A creates a collection and shares it with Team
2. User A is removed from the Team
3. User B joins the Team
The shared collection is lost.

**Expected behavior**
Even if the user is removed/ updated the shared collections should stay intact

**App information (please complete the following information):**
 - App Type - Native App
 - Postman Version - v7.2.2
 - OS - macOS

**Additional context**
The collection wasn't deleted nor removed

**Comment by sankalp0o** [comment]
@Kurmavathar This behaviour isn't expected and we'd look into it.
@ankitjaggi @abhijitkane what can we to debug this issue?

**Comment by Raj-postman** [comment]
The collection here was previously deleted by another user that caused this issue
