### ISSUE TITLE
Copy web URL from postman app examples 

### ISSUE THREAD

**Issue by pho3nixf1re** [a85/POSTMan-Chrome-Extension#6873]
**Is your feature request related to a problem? Please describe.**
I regularly want to quickly share saved examples in the Postman app with team members. Currently there does not seem to be a way to get the web URL through the app. I have to navigate through the web Dashboard, dig into the docs (we have a single super-collection to group our micro-services), then manually copy/paste the URL from my browser.

**Describe the solution you'd like**
Ideally there should be a ‘copy web URL’ option somewhere in the menus or UI (maybe next to the copy response button). An important detail here is that we cannot publicly publish our docs as everything is internal and private.

**Describe alternatives you've considered**
There were some workarounds mentioned in https://community.getpostman.com/t/copy-web-url-from-postman-app-examples/6383/2 which don't actually apply to my issue here. Specifically I want a 'copy online link' button or menu item. Making a comment with an @ mention over and over just to share a documentation link is a bit noisy and excessive. Other than describing the folder structure and telling another user the route name to look for in a not-always-alphabetical list is also laborious.

**Additional context**
My specific use-case is for non-public documentation but this could easily apply to both public and non-public docs. The people I am sharing with are in our team and already have private access using the Postman app.

**Comment by jpSimkins** [comment]
+1mil for this one. Seriously.. why this isn't there makes me sad inside...

On a side note, to get the URL for now, click on `Code` (under the Send button) and select `cURL`. You will be able to get the URL from the output but honestly, this seems like a hack to get the URL. I want to simply copy the URL as a URL with all the proper variables being set. 

This is important when working with third-parties that are sharing credentials for development and needing to send them an example of their "issue" working from my end. Numerous other reasons this is desired too. 

If I may make a suggestion, I think this fits best in the sub-menu of the `Send` button. `Copy URL` would be fitting.

**Comment by ankitjaggi** [comment]
@pho3nixf1re We do provide a way to copy the link to an element by hovering over the name in the tab header. Clicking on the link icon will allow you to grab the URL and then share it with your team members.

![image](https://user-images.githubusercontent.com/6972850/227464587-5fba2d65-fde1-4859-9338-a169c33d59d7.png)

**Comment by pho3nixf1re** [comment]
lol, this was a long time ago. Pretty sure it wasn't present back then. Thanks for replying even if it was years later 🤣
