### ISSUE TITLE
Hitting backspace while renaming a collection will prompt the user to delete the collection

### ISSUE THREAD

**Issue by akaczinski** [a85/POSTMan-Chrome-Extension#6874]
**Describe the bug**
In the left hand "Collections" column, if the user right clicks a collection, clicks on Rename, and hits Backspace, Postman will ask the user if they wish to delete the collection. 

**To Reproduce**
1. Right click a collection in the collections column on the left
2. Click rename
3. Press backspace

**Expected behavior**
Text should be deleted before where the cursor is. User should not be prompted to delete the collection while renaming it.

**App information (please complete the following information):**
 - Native App
 - Postman v7.3.2-canary01
 - Windows 10

**Comment by numaanashraf** [comment]
@akaczinski This issue is addressed in the latest version of Postman Canary (v7.3.5-canary01)
