### ISSUE TITLE
No Inclusion of GraphQL Body in Documentation

### ISSUE THREAD

**Issue by Raj-postman** [a85/POSTMan-Chrome-Extension#6877]
**Describe the bug**
In the auto-generated documentation, the body shows as blank and there's no inclusion of the GraphQL query.

**To Reproduce**
1. Expand your collection
2. Click on 'View in web'
3. GraphQL query is missing in Documentation body

**Expected behavior**
Be able to see the Body just as raw/form-data

**Screenshots**

In-App -

<img width="733" alt="Screen Shot 2019-07-09 at 8 15 22 AM" src="https://user-images.githubusercontent.com/47771757/60855550-c5f06f80-a221-11e9-94a4-67896e746567.png">

In Documentation -

![GraphQLNoBody](https://user-images.githubusercontent.com/47771757/60855566-d9033f80-a221-11e9-8c51-7a549f6e9c64.png)

**App information (please complete the following information):**
 - App Type - Native App
 - Postman Version - v7.2.2

**Comment by hellopandaxx** [comment]
Guys, do we have any updates on it? We currently have the same issue on the web version. Generated collection appears with missing body for some GraphQL requests...

**Comment by DannyDainton** [comment]
In the latest version of the platform I can see the GraphQL body in the documentation:

<img width="1545" alt="image" src="https://user-images.githubusercontent.com/17089546/165951883-069168b8-0586-41c8-931d-dcc33e4817e8.png">

This has been extracted from this Collection https://www.postman.com/devrel/workspace/graphql-examples/documentation/13191452-8892708a-95d0-40d2-902f-c3f22b7d4af0

I'm going to close this issue but I this relates to a different set of documentation, we can look to reopen the issue.
