### ISSUE TITLE
Logging in using the native app via SSO leads to a spinning circle

### ISSUE THREAD

**Issue by carolin-postman** [a85/POSTMan-Chrome-Extension#6884]
**Describe the bug**
When an enterprise user logs-in via SSO through the desktop app, the loading circle spins indefinitely. 

**To Reproduce**
1. Open desktop client  7.2.2 (7.2.2)
2. Click on Enterprise user? Sign in here
3. Entered domain name
4. Select SSO option

**Expected behavior**
Be able to login successfully and access the application

**App information :**
 -  Native Postman App
 - Postman Version - 7.2.2
 - MacOS (latest version)

**Additional context**
logging in through the Web works fine.

**Comment by elssar** [comment]
This looks like a case of a firewall or a proxy blocking the app from connecting to the IdP.
