### ISSUE TITLE
Wrong visualization of response in pretty response

### ISSUE THREAD

**Issue by ardennext99** [a85/POSTMan-Chrome-Extension#6887]
Yesterday i've update Postman to the 7.3.2 version on my Win7 Pro OS.
I've tryed to send request to some service that response with json content (with wrong Content-Type = text/html; charset=UTF-8).
in the previous versions I usually chose the json option in the combobox, and the pretty output show me the content with the right indentation, but with the last update this not work properly.
The content is an array on object with many properties.

**To Reproduce**
1. Call a web service that return json but, with Content-Type = text/html; charset=UTF-8
2. Click on 'Send' and wait until the response show
3. Switch the combobox from HTML to JSON
4. the pretty body is not correctly indented

**Expected behavior**
the pretty body should be indented correctly

**Screenshots**

![image](https://user-images.githubusercontent.com/15669149/60949149-dde4f380-a2f4-11e9-845a-6c6c16bfd9e0.png)
![image](https://user-images.githubusercontent.com/15669149/60948997-8a72a580-a2f4-11e9-9104-9f485d80f518.png)

**App information (please complete the following information):**
 - App Type: Windows Desktop App
 - Postman Version: 7.3.2
 - OS: Windows 7 Pro

**Comment by codenirvana** [comment]
@ardennext99 Thanks for reporting this. We are able to reproduce this.

We did some improvements in the response body viewer, that has caused this. We will push a fix for this in the next release.

**Comment by credencie1** [comment]
Same problem here, but I found a temporal workaround. After switching from HTML to JSON, you can select Preview or Raw and then return to Pretty. The "pretty body" will be working again. Besides, if you send another request, the pretty option will be rendering the body correctly, but you need to be in Pretty tab when sending the request, or you will have the same problem (selecting Raw or Preview and sending again the request will reproduce the error, while sending the request with Pretty tab selected will preserve the correct visualization).

**Comment by kamalaknn** [comment]
We have pushed a fix for this on our canary channel - [download link](https://www.getpostman.com/downloads/canary)

We'll push this to the stable channel as part of the next release.

**Comment by kamalaknn** [comment]
This should be fixed in Postman 7.3.4. Please update to the latest version and let us know if the issue still exists.
