### ISSUE TITLE
Query Parameters not present in the Collection are present in the Documentation

### ISSUE THREAD

**Issue by aes1228** [a85/POSTMan-Chrome-Extension#6893]
**Describe the bug**
Query Parameters not present in the Collection are present in the Documentation

**Expected behavior**
Records Parameter should not be present in the public documentation

**Screenshots**
Collection:
![image](https://user-images.githubusercontent.com/46380635/60976417-a62d7a00-a2fb-11e9-8112-2fda61d460d5.png)

Published Docs:
![image](https://user-images.githubusercontent.com/46380635/60976472-be04fe00-a2fb-11e9-851f-84ad29a813b9.png)

**App information (please complete the following information):**
Postman for Windows
Version 7.2.2
win32 10.0.17763 / x64

**Comment by shamasis** [comment]
Can you try modifying parts of the collection and saving the request again? Want to double check if this is an issue with syncing changes

**Comment by aes1228** [comment]
I’ve made several changes to the collection since this parameter was removed from our code back in January of this year. Updates are almost instantaneous.

Anna

**Comment by aes1228** [comment]
Hello,
Just checking in. 

I made an update to the collection last Friday, changes were reflected in the published documentation, the Record parameter is still there.

**Comment by YounixM** [comment]
Hi @aes1228, We are unable to replicate the issue. Can you please share the link for the published documentation for the collection?

**Comment by aes1228** [comment]
Each endpoint was stale. I had to go through and touch each one to get the parameter to delete from the docs. Took about an hour. Not fun.
