### ISSUE TITLE
Cannot Disable Sync

### ISSUE THREAD

**Issue by asharma-gh** [a85/POSTMan-Chrome-Extension#6894]
This glorified front-end GUI for cURL cannot have it's always online sync feature disabled.

Many people would not like another organization to possess things like Access Tokens and API Keys used in requests, but appreciate the conveniences that Postman offers such as performing signed AWS requests.

**Comment by a85** [comment]
You don't need a user account to use Postman. User accounts are needed *for* syncing and Cloud features.
