### ISSUE TITLE
Test v. PM.test

### ISSUE THREAD

**Issue by audreyjbanks** [a85/POSTMan-Chrome-Extension#6896]
I recognize that `tests[]` is being deprecated and so I wanted to change to `pm.test()`. However, when I use the same function that worked before in passing and failing with `test[]`, I get false positives with `pm.test()`. The example pictured below. 

![image](https://user-images.githubusercontent.com/23407905/60990756-1c8ba580-a317-11e9-853f-d2faf3a0adef.png)

I am using an API that is returning an object that looks like this:

```
[
    {
        "id": 0,
        "heading": "",
        "title": "Title name",
        "images": {
            "phone": {
                "type": "IMAGE",
                "width": 828,
                "height": 1159
            },
            "tablet": {
                "type": "IMAGE",
                "width": 1170,
                "height": 602
            }
        },
        "menu_order": 6
    },
...
``` 

And I am testing to make sure the fields are empty.

Addtional intel:
![image](https://user-images.githubusercontent.com/23407905/60989264-7f7b3d80-a313-11e9-9657-b23eb88cb2b8.png)

macOS Mojave 10.14.5

**Comment by DannyDainton** [comment]
Hey @somebodie,

It might be worth closing this issue and raising a question over on our community.getpostman.com site. 

These 2 things work slightly differently and it would be easier to explain with examples on that platform. 

It also gives our community members a chance to pitch in and help with the question. 😁

**Comment by audreyjbanks** [comment]
Thanks @DannyDainton !

Just put the question in the help.

https://community.getpostman.com/t/test-to-pm-test-https-github-com-postmanlabs-postman-app-support-issues-6896/6456
