### ISSUE TITLE
Plans and Pricing web page mobile version issue

### ISSUE THREAD

**Issue by di118** [a85/POSTMan-Chrome-Extension#6898]
**Describe the bug**
The mobile version of the Plans and Pricing page is not displayed properly. User needs to scroll to the right to read the complete information about Postman Enterprise

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'https://www.getpostman.com/pricing'
2. Press F12 to activate Chrome's Developer Tools - Select any device such as iPhone X or use a mobile to access the website 
3. See error by scrolling down to the Pricing table and then scrolling to the right

**Expected behaviour**
In my opinion, the folding line shouldn't be there. I think this may be caused by either the list element or the Intercom widget button. 

![2c0ruZM](https://user-images.githubusercontent.com/22803107/60999870-123bcc80-a354-11e9-8b82-8bd2d9304ec3.png)

**App information (please complete the following information):**
 - Chrome browser
 - Postman | Plans & Pricing page
 

**Additional context**
This may not be considered a bug and I apologies in advance if I reported it in the wrong  section

**Comment by tristandenyer** [comment]
Thanks for sending notifying us of this. Prioritized to be fixed very soon.
