### ISSUE TITLE
Session Expired window on native app (v7.2.2).

### ISSUE THREAD

**Issue by Swapnil-getpostman** [a85/POSTMan-Chrome-Extension#6901]
**Describe the bug**
Unable to access the postman app as the session got expired on the native app (v7.2.2), and when tried sign in, Postman tries to load an embedded browser (which is v59 chrome). As this version is being blocked by company policy, It is throwing an error message "**Not allowed to use the browser. (Sorry this web browser is not approved to use at your company)**" 

Is there any way for the app to pick up the latest version of chrome?

**To Reproduce**
1. Open the app. It gets to session expired. There will be data loss if, choose to logout.
2. After clicking on sign in, chrome application v59 is not allowing to sing-in to the postman account and see the error

**Expected behavior**
The app should pick up the latest version of chrome for the actions that need to access the browser.

**Screenshots**
Added screenshot to describe the problem. 
<img width="433" alt="Screenshot 2019-07-11 at 2 19 34 PM" src="https://user-images.githubusercontent.com/52168965/61037057-f6820600-a3e7-11e9-8b1f-00e8f45e8ec5.png">
<img width="455" alt="Screenshot 2019-07-11 at 2 20 00 PM" src="https://user-images.githubusercontent.com/52168965/61037060-f71a9c80-a3e7-11e9-8a89-b511eb43d67d.png">
<img width="506" alt="Screenshot 2019-07-11 at 2 20 18 PM" src="https://user-images.githubusercontent.com/52168965/61037061-f71a9c80-a3e7-11e9-9d1d-d4a4ae5641a5.png">

**App information (please complete the following information):**
 - App Type - Native App]
 - Postman Version - v7.2.2
 - OS: Win10 64bit

**Comment by preethammavin** [comment]
@Swapnil-getpostman can you update the app and try again?

**Comment by Swapnil-getpostman** [comment]
@preethammavin the user cannot login from the app to update the latest version due to the chrome version.

**Comment by preethammavin** [comment]
@Swapnil-getpostman we have updated electron, which should update V8 engine to 6.9 and chrome 69. Can you check with the user if using our latest canary he can work with that, while we rollout the app for all users?

**Comment by Swapnil-getpostman** [comment]
@preethammavin User didn't used canary application. But responded that the standard postman application has started working fine now.
