### ISSUE TITLE
Unable to drag and drop requests(folders) to other folders(collections)

### ISSUE THREAD

**Issue by mika-kami** [a85/POSTMan-Chrome-Extension#6902]
**Describe the bug**
Unable to drag and drop requests(folders) to other folders(collections)

**To Reproduce**
1. Go to 'Collections'
2. Right click on any folder/request
3. Drag anв drop the request to another folder

**Expected behavior**
Drag and drop works 

**App information (please complete the following information):**
 - Native App
 - 7.3.2
 - OS: Win 10

**Comment by preethammavin** [comment]
@asthun I am unable to reproduce this, what is the error that you see? when you perform the action?

**Comment by mika-kami** [comment]
> @asthun I am unable to reproduce this, what is the error that you see? when you perform the action?

@preethammavin me too. Reloading of postman resolved that issue. Maybe it is was an issue with my PC
