### ISSUE TITLE
Add C# to the Published Documentation Code Generation

### ISSUE THREAD

**Issue by ghost** [a85/POSTMan-Chrome-Extension#6903]
**Is your feature request related to a problem? Please describe.**
Not a problem, but it does feel like a gap

**Describe the solution you'd like**
Include the C# code gen in the published documentation page. It already exists in the app.

**Describe alternatives you've considered**
I've tried to see if I can contribute to that page, but I am not able to. The community page suggested that I open up a feature request here.

**Comment by ishan-ks** [comment]
@ghost We have `C# RestSharp` as one of the languages in published documentation. Hopefully, that resolves your issue.

**Comment by sony-mathew** [comment]
Hey @ghost,

We hope this resolves your issue. If you have any further concerns or questions, please feel free to reopen this discussion. We're here to help and support you.
