### ISSUE TITLE
Postman Console - OAuth2 Token Request not captured

### ISSUE THREAD

**Issue by medjai** [a85/POSTMan-Chrome-Extension#6904]
**Describe the bug**
When using OAuth2 for authentication with grant type client_credentials to make a token request this is not properly captured in the console

Console displays request header and body as undefined and the response header as well

**To Reproduce**
1. Make a OAuth2 Token Request

**Expected behavior**
Headers and body for requests and responses should always be captured within the console.

**Screenshots**

![image](https://user-images.githubusercontent.com/16169426/61054485-89597b00-a3bd-11e9-955b-33b854aaa754.png)

**Comment by coditva** [comment]
@medjai Thanks for reporting this! This indeed is a bug. We'll ping here when we have a fix. Stay tuned!

**Comment by coditva** [comment]
@medjai This issue is fixed and out in the latest Postman App `v7.12.0` near you!  🎉
