### ISSUE TITLE
Dashboard - Something went wrong error when Billing user tries to access Billing overview

### ISSUE THREAD

**Issue by cyrielle-hada** [a85/POSTMan-Chrome-Extension#6905]
**Describe the bug**
User with billing role heads to https://app.postman.co/team/overview and see the below SWW error. 

<img width="772" alt="Screen Shot 2019-07-10 at 6 32 33 PM" src="https://user-images.githubusercontent.com/47351631/61063336-b62a8400-a3f7-11e9-8084-9a493eafa5b9.png">

**Comment by abhijitkane** [comment]
This error was coinciding with Stripe's downtime.
