### ISSUE TITLE
postman 7.2.2 not working on windows 8.1

### ISSUE THREAD

**Issue by kanuos** [a85/POSTMan-Chrome-Extension#6906]
**Describe the bug**
Postman doesn't even start on clicking. I installed the app for windows 64bit. upon installing a blank pop up box popped out. There was no text or buttons or anything,
I had to force close it. Every time i tried to open the app, a blank screen used to appear. I tried to open several times ( more than 10) and everytime it failed to open.

**Expected behavior**
Expected to open. At least the sign up/ sign in page.

**App information (please complete the following information):**
 - App Type [Native App]
 - Postman Version [7.2.2]
 - OS: [windows 8.1]
- RAM [12 GB]

**Additional context**
I had to uninstall the app. Please fix this bug so I can use it

**Comment by Mystigan** [comment]
I am facing the same issue: Postman v7.2.2 on Windows 8.1. Tried both 32 and 64 bit versions. Results are the same. Please fix it soon.

**Comment by harryi3t** [comment]
@Mystigan @kanuos 
This looks similar to the https://github.com/postmanlabs/postman-app-support/issues/4594 issue.
Could you try out our latest canary build and let us know if that works? You can download it from https://www.getpostman.com/downloads/canary

**Comment by harryi3t** [comment]
@Mystigan @kanuos 
The same fix is also available now on the stable channel (Postman v7.3.4). Could you update your app and give it a try?

**Comment by Mystigan** [comment]
@harryi3t ,
I installed Postman v7.3.4 on my windows 8.1 machine. It is working fine now. Thank you for the fix.

**Comment by sahilrajput03** [comment]
Great!!!!!!!!!!
I have been thinking from past 2-3 months that postman isn't supported by windows 8.1, its just amazing that you guys roll out the canary versions, now it works just amazing!
Earlied my problem was on loading postman, a ballon used to get up in system tray, saying Graphical Driver stopped responding, etc., like that!! I installed graphics card driver but it didn't help, now I just saw this issue and installed the canry version, and boom, its just SUPER GOOD. No bug at all.
Thanks guys, a lot!!!

**Comment by sahilrajput03** [comment]
Cool.

**Comment by sahilrajput03** [comment]
> @Mystigan @kanuos
> The same fix is also available now on the stable channel (Postman v7.3.4). Could you update your app and give it a try?

Only canary vesion seems to work on my maching with windows 8.1, now I'm happy though.
Just to let you guys know, stable version isn't bug proof, it was just saying graphics card stooped responding in system tray when I tried to install last month.
Thanks.
