### ISSUE TITLE
Tests do not run if responseBody is large (ish) 

### ISSUE THREAD

**Issue by HarkinsDave** [a85/POSTMan-Chrome-Extension#6907]
**Describe the bug**
Tests do not run if Response Body is large(ish) even if the only thing in the Tests tab is:   console.log('This is a test');
Even though the Tests do not run the Response Body is returned inside Postman (not in the console).
Through more testing of the exact same call and changing the limit of how many records are returned (using $top=<number> in the call) in the JSON object it is appearing to be more random than initially thought and is acting more and more like a possible memory leak, though I don't see the normal indicators of a memory leak.  The issue originally occurred with a response object 15.58 MB in size, however by starting lower where the error doesn't occur and building up I have managed to get it to work properly for response objects of 16.23 MB in size.  Once you get to a point where it will not run the code in the Tests tab any more and try to work your way down it will then at times not work on response object sizes that it previously did work for.  Basically when Postman works correctly and runs the Tests tab it will tend to continue to work, however when it fails to run the Tests tab it will tend to continue to fail on subsequent attempts.

It is possible that it is not really a response object size issue but a node issue... not node the language but how many nodes are in the response object.

**To Reproduce**
Steps to reproduce the behavior are not set in stone as you can see from the Screenshot#1 of the console since with the exact same call and dataset a call that worked or failed to process the Tests tab prior may or may not have the same result when ran later.  That being said the following is the jist of how to reproduce.

1. Create an API Endpoint "A" that returns a Response Body of 17.42 MB
2. Create an API Endpoint "B" that returns a Response Body of 15.68 MB
3. Create a Postman Call to call Endpoint "A"
3. Create a Postman Call to call Endpoint "B"
4. In the test tab of each Postman call put:    console.log('This is a test');
5. Run both Postman Calls.
6. Endpoint "A" will succeed but will not run the   console.log command
7. Endpoint "B" will succeed and will run the   console.log command

**Expected behavior**

Tests tab code should always run.

**Screenshots**
Screenshot#1
![image](https://user-images.githubusercontent.com/34103624/61074731-3982b000-a3cd-11e9-81c2-7a75c191ec4d.png)

Screenshot#2
![image](https://user-images.githubusercontent.com/34103624/61075006-ec530e00-a3cd-11e9-8815-802ef8496f4a.png)

Screenshot#3
![image](https://user-images.githubusercontent.com/34103624/61074797-646d0400-a3cd-11e9-8c02-3cbb4e5cd708.png)

Screenshot#4
![image](https://user-images.githubusercontent.com/34103624/61074820-6d5dd580-a3cd-11e9-8763-a8b6a583dfce.png)

**App information (please complete the following information):**
 - Native App
 - Postman Version 7.3.2   **Edit** fixed Postman Version
 - OS: Windows 10 Pro Version 1809 OS build 17763.475
 - Dell XPS 15 9570, i7-8750H CPU @ 2.20GHz, 32GB RAM, 1TB PM981 NVMe Samsung

**Additional context**
Screenshot#2 lines up with the last call on Screenshot#1

SessionAttributesNames can have a varying amount of data depending on the Auditorium which can change the total number of child nodes in the response object.  All result sets are returned in the same order due to the orderby param.

**Comment by saswatds** [comment]
Hi @HarkinsDave you are right. There is a limitation on the amount of data that can be passed on the sandbox scripts and pre-request script. The current limit is around ~15mb.  The data that is passed is the sum of the response data, environments and globals. 

If and when the total data payload exceeds this limit then the sandbox cashes and therefore the tests do not get executed. 

Marking this a performance issue for now.

**Comment by HarkinsDave** [comment]
@saswatds Thank you for the confirmation.  I will try to work around this for now.

**Comment by kamalaknn** [comment]
@HarkinsDave Can you try this on the latest version of Postman and let us know if you're still facing the issue?

**Comment by postman-kenji** [comment]
Closing out given updates and time since response. @HarkinsDave please reopen this issue if you are still experiencing the same on the latest version of Postman. Thanks!
