### ISSUE TITLE
Dark mode link color makes the link difficult to read.

### ISSUE THREAD

**Issue by markodelgadillo** [a85/POSTMan-Chrome-Extension#6909]
While using dark mode, links use the same blue color which on the dark gray background is hard to read.

Add a lighter background to the links or use a lighter shade of blue for the text color.

**Example of the issue**
<img width="312" alt="Screen Shot 2019-07-11 at 11 03 56 PM" src="https://user-images.githubusercontent.com/13569476/61106047-b4c97d80-a430-11e9-9b02-cdd258662a56.png">

**Comment by preethammavin** [comment]
@markodelgadillo can you let us know which version of the App are you on, we fixed it in our latest release. Can you update your app to the latest version ?

**Comment by markodelgadillo** [comment]
@preethammavin Hi. Thank you for the response. You are correct! Sorry for the inconvenience! I have since updated Postman and the orange links work MUCH better :)
