### ISSUE TITLE
Public documentation links expiring without user unpublishing

### ISSUE THREAD

**Issue by nikhil-thomas90** [a85/POSTMan-Chrome-Extension#6910]
I am using Postman's public documentation feature to send client-facing documentation to third parties. However, despite never unpublishing the collections, the documenter links expire. This is against the expected behaviour of persistent links, and is causing issues to my client-facing processes.

**Comment by godfrzero** [comment]
@nikhil-thomas90 Public documentation will be unavailable if the underlying collection is deleted. The docs themselves have no "expiry". Are you seeing this issue with any docs where the collection hasn't been deleted?

**Comment by godfrzero** [comment]
Closing this for now since this doesn't look like an actual bug. If you run into a doc where the collection exists but the public documentation was unpublished, feel free to reopen this.
