### ISSUE TITLE
Workspace activity feed needs recovery options for environments, collections etc

### ISSUE THREAD

**Issue by jpSimkins** [a85/POSTMan-Chrome-Extension#6912]
**Is your feature request related to a problem? Please describe.**

Wanted to leave this on the forums but too restricted for a new paying user... cannot even leave a feature request or report anything other than coming here. So hopefully this is the place to be...

First, environments are pretty cool and once you learn how they work with workspaces they are very powerful. My issue is that they are not very intuitive in the workflow of sharing them and lack recovery as they are easy to mess up due to confusion between different behaviors between collections and environments.

Last night I moved (shared) a collection to a new workspace and did the same for the environments. So far, great! Now I deleted the collection from the original workspace and it's still in the new workspace. Perfect, that's what I wanted although share would imply something else (deleted because it's shared, not given). So it being late and I'm tired, I assumed the same would happen to environments... nope. All my environment were deleted. Not cool... not cool at all but expected because... `share`.

Ok, so there has to be some activity that can undo this right? None... (if there is I would love to find it because I will be spending a lot of time today rebuilding these environments)

So I setup one environment last night because I needed it for today. I came into the office and wanted to let my team know of this problem as it's very easy to mess up hours of work. I realized that I created the new environment on my personal workspace, I shared it with the team workspace and then deleted from mine as I no longer needed it.. totally forgetting what just happened the night before... Well team... there you go...

Now I just checked the docs and I see that sharing is not actually how you recommend to share the environment

>It's best practice to create a duplicate, remove any sensitive values (such as passwords), and access tokens before downloading the copy to share with others.

Not really sure how duplicate is any better of a solution. It's even more confusing. I duplicate the environment when I want to make a new environment that is similar. Not to give it to a workspace. Even selecting `duplicate` only creates another in my workspace... so how does it get into the team's? Oh, I am expected to download and share? That seems a bit out of date because environments have `initial` and `current` values which solve the problem mentioned in the quoted text.

My issue is this: rarely do people read the docs before they use a product. I would even argue the docs seem out-of-date on this subject. You expect the UI to be intuitive and make sense. This behavior with `share` is expected as this was shared. My issue is that with Collections, this did not work the same way. I was able to delete my collection in my personal workspace and it still exists in the team. It's not consistent  I would not think of duplicate to be how I move an environment to a new workspace. 

The overall process of this should be reassessed and improved. This is too important to the product to have it be so easily destroyed with no ability to recover.

**Describe the solution you'd like**

I propose a new menu item that is to `move` the environment.  

This would still obey the `initial` and `current` values so only the `initial` will be moved to the workspace as expected. I would expect the same option for the collection as this is clear on what the action is. 

The behavior of `share` is actually the correct behavior so nothing but updating the docs to inform the user they will lose their data from all shared environments when deleted from any workspace. (although only the original should do this. When removing a share from a workspace it was shared to should only remove it from there.. haven't tested this part yet to know workflow).

I would also recommend environment actions like this be logged in the activity log and allow them to be undone by the admin. This would save me so much work... my fault but still. 

**Describe alternatives you've considered**

There isn't any alternatives I can consider here. 
- Share means share, when you delete the source it should delete it from all. 
- Move is clear on what it is doing. 
- Duplicate is only necessary when creating a new environment based off a previous or if you want to download and share it with someone manually.

Activity logging is missing to my surprise and recover does not exist...

**Additional context**

I think once you get used to working in this setup, it seems fine. As a new user (to these features, been using since it was a browser add-on) it was clearly easy to mess up my environments. All I was trying to do was move environments to the team workspace or move from one workspace to another. Not wanting to have it left behind but actually moved to the workspace I wanted. Something so simple became a nightmare that will cost me half the day to recover.

**Comment by sankalp0o** [comment]
@jpSimkins I appreciate the detailed explanation, it helps us come up with better solutions than one line feature requests!


> Last night I moved (shared) a collection to a new workspace and did the same for the environments. So far, great! Now I deleted the collection from the original workspace and it's still in the new workspace. 

This shouldn't have happened, your understanding of `Delete` is correct and the collection should've been deleted from all workspaces. If you're able to reproduce it, I'd look into this as a possible bug. There is a possible explanation though, which will become clear in the next part.

The `Move` option that you are looking for is totally valid and we will look into it. Meanwhile, let me offer you an alternative workflow.

### Removing collections and environments
Instead of doing `Delete` after sharing an environment, you can `Remove` it. `Remove` only affects the current workspace while `Delete` affects all workspaces. If you do this, your workflow would look something like - 
Step 1. Create environment in private workspace W1
Step 2. Share environment with team in team workspace W2
Step 3. Remove environment from W1

Step 2+3 together make up the `Move` action that you were talking about.

We are also tracking better access control and changelog for environments. We also do want to make the workspace activity feed contain options such as restore, to offer a safegaurd against accidental removals and deletions.

**Comment by ramji367** [comment]
You can now move environments, collections and other elements between workspaces. You can also fork and merge these elements from one workspace to others. Hence closing this issue.
