### ISSUE TITLE
Version Control – Programmatic Merging

### ISSUE THREAD

**Issue by chrisdeso** [a85/POSTMan-Chrome-Extension#6913]
**Describe the solution you'd like**
The ability to programmatically merge forks would allow the feature to be leveraged within numerous workflows – e.g. integration pipelines!

**Describe alternatives you've considered**
Exposing API endpoints that would allow programmatic usage.

**Additional context**
[Filed by Postman]

**Comment by ankit-m** [comment]
Postman API now supports merging forks.
