### ISSUE TITLE
Can't merge for or pull changes: "The imported resource's graph is cyclic"

### ISSUE THREAD

**Issue by JP-from-Postman** [a85/POSTMan-Chrome-Extension#6915]
**Describe the bug**
[Report by Postman support, on behalf of original user]
User report:
```
I can't merge from my fork collection to the master branch. I also can't do a pull request to get the latest updates. 
I get the below error:
"Something went wrong. The imported resource's graph is cyclic"
```

**To Reproduce**
(Not reproduceable by support)
1. Attempt to pull changes from master to fork, or merge fork
2. See error

**Expected behavior**
- Collection is merged successfully
- Error message more clearly defines issue (if correctable by user)

**App information (please complete the following information):**
 - App Type: Native app, Web Dashboard (Chrome)
 - Postman Version: 7.2.2
 - OS: Windows

**Additional context**
See internal notes for details

**Comment by DannyDainton** [comment]
Hey @JP-from-Postman 

Is this still a valid issue in the latest version?

**Comment by DannyDainton** [comment]
I'm going to close this issue but we can open this up again if this is still a problem that people are facing.
