### ISSUE TITLE
Can't install on Windows Server 2012

### ISSUE THREAD

**Issue by jpanatti** [a85/POSTMan-Chrome-Extension#6917]
Hello, I'm trying to install Postman 64 bits on Windows Server 2012, but is not working.
Is it possible to install on that O.S. ?
Thank you.

**Comment by cyrielle-hada** [comment]
@jpanatti system requirements can be found here: https://support.getpostman.com/hc/en-us/articles/360026135674-What-are-the-system-requirements-for-using-Postman-. I hope that helps!

**Comment by jpanatti** [comment]
Thank's for your answer Cyrielle-hada.
Regards.
