### ISSUE TITLE
Cannot use certificates stored in OneDrive (recurrence of Bug #3834)

### ISSUE THREAD

**Issue by shrey-d** [a85/POSTMan-Chrome-Extension#6918]
**Description**
This is a recurrence of Bug #3834. When Client Certificates are located within folders backed up by OneDrive, Postman is unable to load them. The error received on the console is:

`certificate "cert" load error:  EINVAL: invalid argument, fstat`

The workaround is simple - place the certificates in a folder that is not backed by OneDrive. However, until one actually looks into the Postman console, identifies the error and stumbles upon this workaround, one assumes that there is something wrong with the certificates or the API server and wastes time troubleshooting the wrong end of the request-response cycle.

**To Reproduce**
1. Identify an API server that requires Client Certificates
2. Place the Client authentication crt and key files under a folder backed by OneDrive
3. Enable Postman console (Alt+Ctrl+c)
4. Add the server hostname, port, client certificate and key from File > Settings > Certificates > Client Certificates. Notice that there are no errors when saving the configuration.
5. Add an API call to the server. The console shows the error "certificate "cert" load error:  EINVAL: invalid argument, fstat"

**Expected behavior**
One of the following:
1. Work seamlessly with Client Certificates stored in folders backed up by OneDrive
2. An helpful pop up when saving the Client Certificates indicating that the user must move the files to a non-OneDrive backed up folder

**App information:**
 - Native App for Windows
 - Postman Version 7.2.2. (win32 10.0.16299 / x64)
 - Windows 10 - 10.0.16299

**Comment by shamasis** [comment]
At first glance, it looks like an issue bubbled up from our underlying layer of NodeJS and electron runtime https://github.com/electron/electron/issues/11570

Can you try using the Postman Canary variant and let us know if that solves your issue? https://www.getpostman.com/downloads/canary

We will move the changes to stable channel asap.

**Comment by shrey-d** [comment]
Thanks for the quick response. I checked up Postman Canary (Version 7.3.2-canary01, win32 10.0.16299 / x64) and am glad to report that the Client Certificate on OneDrive does work seamlessly there.

**Comment by codenirvana** [comment]
@shrey-d We've pushed a fix for this on `v7.3.4`. Can you update your app and confirm if this fixes your issue?

**Comment by shrey-d** [comment]
I've updated my version to v7.3.4 and confirm that the issue is resolved. Thanks a ton!
