### ISSUE TITLE
Error: tunneling socket could not be established, statusCode=302

### ISSUE THREAD

**Issue by MRSAIHAIK** [a85/POSTMan-Chrome-Extension#6921]
Hi i am facing an issue on postman request.

In my window app i can't request any url.. 
it is showing error of "Error: tunneling socket could not be established, statusCode=302"

i also try with turn off Automatically follow redirects.
Use System Proxy

any solution for its thanks

**Comment by shamasis** [comment]
Can you post screenshots of where you’re seeing the error? Also what version of app are you using?

**Comment by MRSAIHAIK** [comment]
i got this error from console  

![20190716092751](https://user-images.githubusercontent.com/29477008/61259277-103a9900-a7ac-11e9-91ac-5a97223f2aeb.png)

and i have use version 7.2.2

![20190716092801](https://user-images.githubusercontent.com/29477008/61259299-29dbe080-a7ac-11e9-91c3-953549c0a49b.png)

**Comment by shamasis** [comment]
Can you make a GET request to `https://postman-echo.com/get` and see if that succeeds?

If yes, then it seems like you are connecting to a local server using https. Most probably your SSL will be self-signed. Can you go to Postman settings and turn off SSL validation and try? Remember to turn it back on after you are done sending local requests.

**Comment by shamasis** [comment]
We will, some time in future, auto disable SSL verification for localhost. Tracking that at https://github.com/postmanlabs/postman-app-support/issues/4726

**Comment by MRSAIHAIK** [comment]
Hi i had trun off SSL and make a GET request to https://postman-echo.com/get but still not work.
Below r screenshot.

![20190717092706](https://user-images.githubusercontent.com/29477008/61340500-26605c00-a875-11e9-84ee-94e80ecfbe67.png)
![20190717092816](https://user-images.githubusercontent.com/29477008/61340517-3c6e1c80-a875-11e9-833f-f205759e8999.png)

FYI
in my collage PC it is working. but it not only work for mine. As we use same network & setting

**Comment by codenirvana** [comment]
@MRSAIHAIK This looks like an issue with proxy.

Can you check if both global and system proxy configurations are turned off?

**Comment by MRSAIHAIK** [comment]
i had trun off for both proxy
