### ISSUE TITLE
Monitor not sending to distribution group

### ISSUE THREAD

**Issue by TinaBasinger** [a85/POSTMan-Chrome-Extension#6924]
**Describe the bug**
I am very new to monitors in PostMan, but found it quickly served a unique need we had last week to monitor that our site is up and running at the most basic level. The email alerts work fine for me when I put in specific email addresses. However, when I try to send the notification to a distribution group, the distribution group never gets the notification. As far as we can see, the notification to the distribution group does not even reach our exchange server. We’ve tested that the distribution group works from outside of our network, so at this point we feel there is something unique going on with the monitor.

**To Reproduce**
1. Create a monitor and add both a distribution group and a normal email address to the notifications. 
2. Make the monitor fail.  
3. The normal email address will receive the notification directly, but the distribution group never does.  

**Expected behavior**
I would expect the distribution group to receive the notification in the same way since it can be interacted with in the same manner as an email address.

**Comment by aman-postman** [comment]
Hey @TinaBasinger , are you still facing the issue? We tried to reproduce it for a distribution group and were successfully notified of failure both via the normal email address as well as the distribution group.

**Comment by ArjunSingh-PM** [comment]
Hi @TinaBasinger, please reopen this ticket in case you are still experiencing this issue. We tested setting a distribution group for monitoring failure notifications and were successfully notified for the same.
