### ISSUE TITLE
Renaming tokens

### ISSUE THREAD

**Issue by mcandre** [a85/POSTMan-Chrome-Extension#6930]
**Is your feature request related to a problem? Please describe.**

When managing several dozen tokens, a typo in a recently created authentication token name is difficult to recover from.

**Describe the solution you'd like**

Allow users to rename our tokens.

**Describe alternatives you've considered**

Using cURL.

**Comment by vikiCoder** [comment]
Hi @mcandre 

We've added functionality to rename stored token from token manager in the latest version of Postman App (v7.7.2). Here is a screenshot from where you can rename the token:

<img width="803" alt="Screenshot 2019-09-17 at 1 27 17 PM" src="https://user-images.githubusercontent.com/16588032/65022762-2c46ec00-d94f-11e9-97bd-78a3a2367c67.png">
