### ISSUE TITLE
problem of cookie

### ISSUE THREAD

**Issue by errorCreate** [a85/POSTMan-Chrome-Extension#6931]
I can‘t add cookie if i add a domain like '127.0.0.1:8080'

**Comment by codenirvana** [comment]
@errorCreate Please share the Postman app version?

**Comment by errorCreate** [comment]
> @errorCreate Please share the Postman app version?

Version 7.3.3

**Comment by errorCreate** [comment]
> > @errorCreate Please share the Postman app version?
> 
> Version 7.3.3

win32 10.0.18362 / x64

**Comment by codenirvana** [comment]
Cookie scope is limited to the hostname and not bound to port or protocol information.
RFC: https://tools.ietf.org/html/rfc6265#section-8.5

Using just `127.0.0.1` will fix your issue.
