### ISSUE TITLE
Postman not launching when tried to open again by clicking on "Run in Postman" button

### ISSUE THREAD

**Issue by harryi3t** [a85/POSTMan-Chrome-Extension#6932]
**Describe the bug**
Postman app opens only once from the "Run in Postman" button. After that, it stops working.
This happens only on windows.
Also, after opening the app normally (from menu, taskbar or shortcut) it would again work the next time (again only once) from the "Run in Postman" button.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'https://docs.postman-echo.com' (On a windows system)
2. Click on 'Run In Postman'
3. Click on 'Postman for Windows'
4. [App will open] Quit the app
5. Again click on 'Postman for Windows'
6. [App will not open this time]

**Expected behavior**
"Run in Postman" button should continue to work

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version: 7.3.1-canary01-7.3.4-canary01, 7.3.1-7.3.3
 - OS: Windows 10

**Comment by harryi3t** [comment]
The fix is available on the canary channel on version 7.3.4-canary02
https://www.getpostman.com/downloads/canary

The same will be available in the next production release (7.3.4)

**Comment by harryi3t** [comment]
This is fixed in the latest version of Postman (v7.3.4).

**Comment by ConstantineSF** [comment]
It don't work, in Canary in Usual Postman, has version 7.18.1, it simple can't open the app.
And I don't know do I need to provide a path in windows, do I need reinstall all again.
Honestly it opened once, but no sense after this nothing happend.

**Comment by SayefReyadh** [comment]
Similar Issue resolved after deleting the Postman AppData from `C:\Users\<username>\AppData\Roaming\Postman`
