### ISSUE TITLE
Update mock server matching to support query string params (and maybe even post body)

### ISSUE THREAD

**Issue by zgirod** [a85/POSTMan-Chrome-Extension#6934]
**Is your feature request related to a problem? Please describe.**
Upon reading the matching algorithm documentation is appears that the matching does not take the query string params into affect.  This is a big limitation on the mock server.  In many cases you are building a front end application and using the mock server to, well; mock out the backend.  It is very common to have api requests for list views and then api requests for detail views.  You cannot do this without the ability to match on query string params.*

* I realize that you can do this if you specify the example headers however the purpose of the mock should be that the front end doesn't care if it is calling the real api or the mock.  Doing this header approach there needs to be custom code just for the mock server which kinda defeats one of the main selling points of the mock server.  There should be no custom code needed for mocking from the front end perspective. 

**Describe the solution you'd like**
Update the matching alghorith to support query string params as a step in the matching process.  It would be nice to support matching on anything in the Body as well.

**Describe alternatives you've considered**
Need to write custom code to handle sending optional headers.

**Comment by vvs11** [comment]
Hi @zgirod, Thanks for writing in
We do support query string params matching in the request. It'll work if you have added an example with the params that you want to be matched. Also, currently we support request body matching via headers only.

**Comment by zgirod** [comment]
Hello @vvs11 

It isn't working for me; at least not now I would expect it to work.   I have attached an example below and will detail my example here:

- I have a GET with 5 examples
- {{domain}}/v2/testing?accountId=1&date=2019-07-29
- {{domain}}/v2/testing?accountId=1&date=2019-07-30
- {{domain}}/v2/testing?accountId=2&date=2019-07-29
- {{domain}}/v2/testing?accountId=2
- {{domain}}/v2/testing?accountId=3
- The response body is simply the input.  So for the top example the response is: accountId=1&date=2019-07-29

Now here are test case:

---------------------------------------------------------------------
Request: {{domain}}/v2/testing?accountId=1&date=2019-07-29
Response: accountId=1&date=2019-07-29
Status: Success
---------------------------------------------------------------------
---------------------------------------------------------------------
Request: {{domain}}/v2/testing?accountId=1&date=2019-07-30
Response: accountId=1&date=2019-07-30
Status: Success
---------------------------------------------------------------------
---------------------------------------------------------------------
Request: {{domain}}/v2/testing?accountId=1&date=2019-07-31
Response: accountId=1&date=2019-07-30
Status: Not sure what the expected result should be here
---------------------------------------------------------------------
---------------------------------------------------------------------
Request: {{domain}}/v2/testing?accountId=2&date=2019-07-29
Response: accountId=2&date=2019-07-29
Status: Success
---------------------------------------------------------------------
---------------------------------------------------------------------
Request: {{domain}}/v2/testing?accountId=2&date=2019-07-30
Response: accountId=1&date=2019-07-30
Status: Fail.  This is returning account: 1.  There is an example the matches on account: 2 but not the date.  I would expect this to return accountId=2.
---------------------------------------------------------------------

For the last request, I would expect the matching algorithm to say: for this request I match on accountId for 2 of the 5 examples.  Of those two the date parameter matches on one and doesn't existing for the other.  So the matching percent is higher on request that is only accountId and I will return that.   As it stands now it is returning accountId: 1 which doesn't make any sense to me.

When you pass in date: 2019-07-29 and accountId: 2 both accountId: 2 examples have 100% matching but one of them has more parameters so I would show that one. 

Also, just an fyi.  I don't think the documentation page talks about how query string parameters are matched: https://learning.getpostman.com/docs/postman/mock_servers/matching_algorithm/  It talks about input path matching but not query string parameters.

Postman export: [Testing.postman_collection.json.zip](https://github.com/postmanlabs/postman-app-support/files/3441860/Testing.postman_collection.json.zip)
