### ISSUE TITLE
Request throws ECONNRESET error

### ISSUE THREAD

**Issue by cyrielle-hada** [a85/POSTMan-Chrome-Extension#6935]
**Describe the bug**
The GET request doesn't go through, the result is `Could not get any response`.

![postman_app](https://user-images.githubusercontent.com/47351631/61383557-d5695b80-a8a6-11e9-8a52-40b483732797.png)

The Postman console throws `Error: read ECONNRESET`

![Blocked](https://user-images.githubusercontent.com/47351631/61383521-cc788a00-a8a6-11e9-9a9c-2a3853c3bcd8.png)

Turning off System Proxy settings makes the request go through.

Results seem to differ depending on the server and whether or not the system proxy is on/off.
<img width="1108" alt="Screen Shot 2019-07-17 at 15 16 18" src="https://user-images.githubusercontent.com/47351631/61383362-6db31080-a8a6-11e9-88c2-cc32afb9886b.png">

**App information (please complete the following information):**
 - App Type: Native App
 - OS: Windows

--- Opened by Postman on the behalf of the user ---

**Comment by shamasis** [comment]
What version of app and is ssl verification disabled for self signed certificate?

**Comment by cyrielle-hada** [comment]
@shamasis version is 7.1.1 and the self-signed certificate is disabled.
![image002](https://user-images.githubusercontent.com/47351631/61518203-eded8900-aa00-11e9-9caa-022cbce45fe6.png)

**Comment by vladyslovestepanov** [comment]
@codenirvana @shamasis I faced with the same issue
![image](https://user-images.githubusercontent.com/52454096/79215576-6e3c0000-7e54-11ea-9e92-497f7156dec8.png)




1. Postman for Windows
Version 7.22.1
win32 10.0.18362 / x64

2. Bug reproducible every time
![image](https://user-images.githubusercontent.com/52454096/79215851-e5719400-7e54-11ea-8f66-1edba665029c.png)

3. Yesterday (13.04.2020) it was the same just type of the error differed: it was: "Error: socket hang up"

**Comment by awebdeveloper** [comment]
where you able to resolve this

**Comment by arlemi** [comment]
@awebdeveloper If you're facing the same issue please open a new issue or reach out directly to the support team on help@postman.com. 🙂
