### ISSUE TITLE
runner should follow iterations as it goes

### ISSUE THREAD

**Issue by sixcorners** [a85/POSTMan-Chrome-Extension#6937]
**Is your feature request related to a problem? Please describe.**
When running a bunch of iterations it would be nice to see them as they are going.
**Describe the solution you'd like**
I want the window to scroll with and follow the iterations when they are running. When I scroll myself I don't want the scroll bar to move until I move it to the bottom again.
**Describe alternatives you've considered**
curl
**Additional context**

**Comment by saswatds** [comment]
This issue has been addressed in the latest version of the app `7.18.0`. Closing this issue now, feel free to file a bug if you find things not working as expected.
