### ISSUE TITLE
collection runner should show and filter pass/fail stats during run

### ISSUE THREAD

**Issue by sixcorners** [a85/POSTMan-Chrome-Extension#6938]
**Is your feature request related to a problem? Please describe.**
When I'm running a collection it would be nice to be able to filter out failed or passed runs while it is running. It would also be helpful to have those statistics shown during the run too.
**Describe the solution you'd like**
I want to see the number of pass and fail as the runs are going. I also want the pass and fail filters on the left side to show up when the runs are happening.
**Describe alternatives you've considered**

**Additional context**
![image](https://user-images.githubusercontent.com/585501/61406569-b916f000-a8a1-11e9-8f38-100fbe1b102c.png)
![image](https://user-images.githubusercontent.com/585501/61406606-cb912980-a8a1-11e9-99ce-e0f2dded7bb9.png)

**Comment by m3dbedb** [comment]
@sixcorners  note that the runner is already slow. If Postmanlabs would add the feature, it wold be better to be disabled by default as it may couse stability issues.

**Comment by giridharvc7** [comment]
![Screenshot 2021-03-23 at 1 13 54 PM](https://user-images.githubusercontent.com/1040583/112111005-a22db280-8bd9-11eb-9136-19a6913496ec.png)
Does this solve your problem?
