### ISSUE TITLE
Add the ability to have more than five (5) Custom Domains 

### ISSUE THREAD

**Issue by chrisdeso** [a85/POSTMan-Chrome-Extension#6940]
**Is your feature request related to a problem? Please describe.**
Custom domains make it easy to publish API documentation but some organizations need the ability to publish more than five (5) pieces of documentation.

**Describe the solution you'd like**
A self-serve option for purchasing/adding more custom domains.

**Additional context**
[Filed by Postman]

**Comment by Raja-Simha** [comment]
thanks @chrisdeso. I will look into this.

**Comment by Cazaimi** [comment]
For posterity: The new plans allow enterprise teams to publish documentations on domains up to 25 domains: https://blog.postman.com/2020/01/06/announcing-updated-postman-plans-and-pricing/

**Comment by chrisdeso** [comment]
Thanks @Cazaimi – closing this for now!
