### ISSUE TITLE
UI lagged resolved by deleting request history in workspaces

### ISSUE THREAD

**Issue by JP-from-Postman** [a85/POSTMan-Chrome-Extension#6941]
**Describe the bug**
[Reported by Postman Support, on behalf of original user]

Multiple users on team report lag in app UI, especially when switching workspaces, and during app startup. Workspaces have only ~10 Collections each, and requests in these Collections do not have notably large payloads or response sizes.

Deleting saved history for all workspaces resolved the UI lag.

**To Reproduce**
Unknown

**Expected behavior**
Workspace history does not cause UI lag

**App information (please complete the following information):**
 - App Type: Native app
 - Postman Version: 7.3.2
 - OS: Linux

**Additional context**

**Comment by kamalaknn** [comment]
We've made several improvements to how Postman loads history and collections in workspaces. This should improve the UI experience during app startup and switching workspaces, even for large workspaces.
