### ISSUE TITLE
"Close" button for [deleted] tabs is missed 

### ISSUE THREAD

**Issue by mika-kami** [a85/POSTMan-Chrome-Extension#6944]
**Describe the bug**
"Close" button for [deleted] tabs is missed (actual for compressed tabs )

**To Reproduce**
_Preconditions:_
1. Open some tabs 

1. Go to 'Collections'
2. Click on any request
3. Remove the request to other collections
4. Tab name changes to [DELETED] 
5. Hover the tab

**Expected behavior**
"Close" button appears

**Screenshots**
![image](https://user-images.githubusercontent.com/20613297/61458340-f303f700-a972-11e9-8fe5-b850d099f460.png)

**App information (please complete the following information):**
 - Native App
 - Postman Version 7.3.2
 - OS: Win 10

**Comment by m3dbedb** [comment]
As far as the issue is present, use ctrl+w. Current Postman version is 7.2.2

**Comment by mccannt** [comment]
This issue should now be resolved. Please feel free to reopen if this issue persists.
