### ISSUE TITLE
After user resatarts Postman, selecting requests in sidebar does nothing

### ISSUE THREAD

**Issue by m3dbedb** [a85/POSTMan-Chrome-Extension#6946]
**The bug description**
Clicking and selecting requests in sidebar makes no result.

**To Reproduce**
1. Click on several requests in side bar one after another to make postman window became black.
2. As postman menu is available when postman windows goes black, press file > new postman window
3. Click on some request in side bar
4. Pressed request got selected, but no tab is shown. If you click on another request, it would be selected as it shult, but tab are still clear. If you press plus button, Postman opens new empty tab, but clicking on side bar still gives to result.

**Expected behavior**
Usually clicking on requests in side bar makes Postman open request tab.

**Screenshots**
Applied
![1807](https://user-images.githubusercontent.com/25632818/61467500-63674400-a984-11e9-83ee-b4df56f5796e.jpg)

**App information (please complete the following information):**
 - Native App
 - Version  7.2.0 and 7.2.2
 - OS: Windows 7 32 bit

**additional note**
Recently after meeting with the issue in Postman 7.2.0 I have updated Postman to 7.2.2, and just at first run I opened first selected request, but clicking on another one makes no result. Other actions like setting Postman to open each request in new tab and right click on a request and selecting 'open in a new tab' works. If I disable 'open requests in a new tab', the issue appear again.

**Comment by numaanashraf** [comment]
@m3dbedb Could you send us a screenshot of any errors in the DevTools console? You can open the devtools like View > Developer > Show DevTools (Current View) > Console.

**Comment by m3dbedb** [comment]
Currently the issue is not appear since I have updated to 7.3.5. If it appear I would send a screenshot.

**Comment by numaanashraf** [comment]
@m3dbedb Thanks for letting us know. We are closing this for now, let us know if you face this again - we can re-open this then.

**Comment by m3dbedb** [comment]
The issue is back in Postman 7.8.0
