### ISSUE TITLE
Certificate implementation is not working

### ISSUE THREAD

**Issue by Brunofreedom** [a85/POSTMan-Chrome-Extension#6949]
Certificate implementation is not working on Postman Canary, the same certificate I use in the standard version of Postman (works) does not work when you add it to Postman Canary.

**Comment by shamasis** [comment]
Which version of Canary? Also, we would push a new version in a day or two, can you recheck using that?

**Comment by codenirvana** [comment]
@Brunofreedom Can you update the Canary app to the latest version and check if that fixes your issue?

**Comment by Brunofreedom** [comment]
Ok

**Comment by Brunofreedom** [comment]
now it's working ! Thank you
