### ISSUE TITLE
Dashboard: changelog containing emoji crashes UI

### ISSUE THREAD

**Issue by JP-from-Postman** [a85/POSTMan-Chrome-Extension#6952]
**Describe the bug**
[Reported by Postman Support, on behalf of original user]

From the web dashboard, clicking "load more" in the changelog for a specific Collection crashes the page, and the console logs the following error:

![postman-error](https://user-images.githubusercontent.com/43283131/61500323-8e02ce00-a97f-11e9-8c33-5e65e14d49b9.jpg)

User noted that this "page" of the changelog contains an emoji in (_I think_) the request payload, which may be the source of the crash.

**To Reproduce**
1. View changelog for this Collection in Web Dashboard
2. Scroll down page, and click "load more" twice to load 3rd "page" of changelog
3. Page UI goes blank, error is logged in console

**Expected behavior**
- UI doesn't crash

**App information (please complete the following information):**
 - App Type: Dashboard (Chrome), Native app
 - Postman Version: 7.0.7
 - OS: Linux

**Additional context**
See internal notes for additional details

**Comment by kartikjain26** [comment]
@JP-from-Postman  This is fixed in production.
