### ISSUE TITLE
How to set default format in "Body"->"Pretty", for example "JSON"

### ISSUE THREAD

**Issue by wxb2dyj** [a85/POSTMan-Chrome-Extension#6953]
I want to set default format to "JSON" in "Body"->"Pretty" when I view request result. Does anyone know how to make it? Thanks.

**Comment by shamasis** [comment]
I’m afraid that’s not possible. Maybe you could elaborate on this?

@vkaegis we could provide a simple way to change syntax highlighting language in the response view.

**Comment by vkaegis** [comment]
Hey @wxb2dyj, thanks for writing in. Though we don't support setting which body format you want to set as a default yet, we do support setting it to just JSON, so this might solve your immediate use case. Just go into Settings (wrench icon in the header) and you should see an option for setting language detection.

<img width="751" alt="Screenshot 2019-07-26 at 1 24 26 PM" src="https://user-images.githubusercontent.com/6038010/61945229-1a834100-afbd-11e9-9492-c6722465111c.png">

**Comment by sergiosolorzano** [comment]
didn't work for me
![nojson](https://user-images.githubusercontent.com/24430655/76680733-05f2c800-65e3-11ea-805e-326308aca35b.png)

**Comment by chintansureliya** [comment]
@vkaegis thanks it worked for me.

**Comment by memark** [comment]
That worked for me, thanks!

I'm kinda curious though, what this "language detection" actually is supposed to do? It seems even the simplest JSON is never detected, it always ends up as HTML.

**Comment by mindaugasw** [comment]
Hello, is it possible to change view format (Pretty/Preview) using script? 

It would be very useful when working both with JSON and HTML responses. I'd like to write a simple script ("test"?) to automatically switch view depending on response Content-Type, but can't find any way to do so from script.
