### ISSUE TITLE
Allow users to request roles for Collections, workspaces, and team

### ISSUE THREAD

**Issue by JP-from-Postman** [a85/POSTMan-Chrome-Extension#6954]
**Is your feature request related to a problem? Please describe.**
If a user needs the Editor role for a Collection, and don't inherit it from the team default, an existing Editor on the Collection needs to grant it. However, the Manage Roles dialogue is not viewable without the Editor role, meaning a user may not know which team member to ask.

Existing roles on workspaces and teams are viewable without admin for either respectively, but acquiring the admin role still requires manually looking up who can grant it, and reaching out to them separately.

**Describe the solution you'd like**
Allow users to request roles for Collections, Workspaces, and Team. Notify anyone who can approve the request, and grant the role to the requester once they do.

**Describe alternatives you've considered**
None

**Comment by JP-from-Postman** [comment]
Alternative (short term): allow users with Viewer role to see the Manage Roles dialogue, but not make changes. This was they can at least see who has the Editor role, and can grant it to them.

**Comment by sankalp0o** [comment]
Thanks for reporting JP, this is something that we are working upon. I'll update here when it goes out.

**Comment by sankalp0o** [comment]
@JP-from-Postman we've recently release Request for Access for Collections. Users can go to the "Manage Roles" dialogue and can request permissions from team-members who can grant them.

We'll slowly roll this for workspaces (probably teams as well, though that is a separate discussion). I'm keeping the ticket open to track updates and also listen to any feedback anyone might have with regards to Requesting Access.

**Comment by akshay-kulkarni-03** [comment]
@JP-from-Postman we have this feature called `Request for Access` which the users can use to request edit access on collections. Here's the [learning center](https://learning.postman.com/docs/collaborating-in-postman/requesting-access-to-collections/) doc for the same. Free free to re-open this issue if its not address users request.
