### ISSUE TITLE
Search not working :: version 7.2.2

### ISSUE THREAD

**Issue by azgo** [a85/POSTMan-Chrome-Extension#6957]
Using Search (ctrl-shift-f) brings up the search tool but searching for anything does not bring up any results.
Pressing the Find or enter seemingly does nothing, no animation of searching, refreshing window or any visual changes.

**To Reproduce**
1. Press Ctrl-Shift-F
2. Type any word and then Search
3. Play with the checkboxes and then Search

**Expected behavior**
Visual changes, search results appearing or error message

**App information (please complete the following information):**
 - Native App
 - Postman Version 7.2.2
 - OS: Windows 10 x64 v1903

**Comment by numaanashraf** [comment]
@azgo Would it be possible to provide a screen recording of this issue? We are having trouble replicating this issue at our end.

**Comment by azgo** [comment]
Sure, there you go: https://youtu.be/2eEbnfAbuxw

Brgds,

**Comment by jperucello** [comment]
Still happening in v7.36.0
Not reproducible all the time but seems to be after doing some searches and replaces on one collection, if I select another collection to search the response is still the previous collection. 
Some other times, the response is the previous search, and then after there is no response at all.
Recording: https://drive.google.com/file/d/1TCvx5s2yKFvrtdqEq3p4IxqPRVnphBip/view

**Comment by DannyDainton** [comment]
Hey @azgo 

I'm not able to reproduce this in the latest version (9.16.0) and I'm going to close this issue. If this is still a problem for you we can look to open it again.

**Comment by azgo** [comment]
Hey @DannyDainton ,
Sorry I've long forgotten this. You are right the search is working for some time now. Thanks!
Brgds,
