### ISSUE TITLE
Importing JSON file with nested objects

### ISSUE THREAD

**Issue by SaerAlyasso** [a85/POSTMan-Chrome-Extension#6958]
Is it possible to import a JSON file into Postman? I cannot find a way to do it so probably it is not supported. I have a JSON file that consists of an object that contains other objects and its not possible to import it. 

Can you please give me a clue about that topic?

**Comment by preethammavin** [comment]
@SaerAlyasso can you give us a bit more detail around this, what are you trying to import and what would be the expected behaviour in such a case.

**Comment by preethammavin** [comment]
Closing the issue for now, as we do not have enough information to help you. Feel free to reopen the issue with the required information so that we can get it sorted for you.
