### ISSUE TITLE
Path parameters are percent-encoded when clicking a link

### ISSUE THREAD

**Issue by kuehlmeyer** [a85/POSTMan-Chrome-Extension#6959]
**Describe the bug**
Let's say a call returns a JSON with links that use path parameters like this: 
https://somehost/abc;version=42/something
(here: version=42). When you click that link, a new tab opens, but the semicolon and the equal sign are percent-encoded (and of course don't work anymore):
https://somehost/abc%3Bversion%3D42/something

**Expected behavior**
The URL should be opened as it is, without extra encoding.

**Example**
Open this URL in Postman and click on the link in it http://www.mocky.io/v2/5d31b59e3300006b007ba3a7

**App information:**
 - App Type: Native App
 - Postman Version: 7.3.1
 - OS: Windows 10

**Comment by kuehlmeyer** [comment]
I just stumbled over version 7.3.4-canary02. That doesn't have that issue. So, it's probably fixed already in newer versions.

**Comment by shamasis** [comment]
Yeah. @kamalaknn can you confirm and close?

**Comment by kamalaknn** [comment]
@kuehlmeyer Yes, this has been fixed on the Canary channel and on the latest version of Postman 7.3.3 and above.

We are currently rolling this version out in a staged manner. This version will soon be available to everyone.

Also, this has been reported in #6860. So I'm closing this as a duplicate. You can follow the original for updates.
