### ISSUE TITLE
Runner shows error when you try to reload collections

### ISSUE THREAD

**Issue by m3dbedb** [a85/POSTMan-Chrome-Extension#6961]
**The bug description**
Usually when postman windows goes black due to electron bug, runner windows either does black untill you don't restart it (cobsole stay working). Sinse postman 7.2.2 runner may start witth already black and empty window.

**To Reproduce**
1. Open Postman
2. Open Runner
3. Delete some collection
4. Import another collection
5. Runner says you have to reload collection data
6. Press reload button in Runner
2. See error

**Expected behavior**
Runner is expected to reload collections.

**Screenshots**
![1907-2](https://user-images.githubusercontent.com/25632818/61537607-38dac100-aa40-11e9-9a18-ad18d4b27030.png)

**App information:**
 - Native App
 - Postman 7.2.2
 - OS: windows 7 32 bit

**Comment by m3dbedb** [comment]
The issue happens if you delete in postman collection, opened in Runner

**Comment by saswatds** [comment]
Hi @m3dbedb it will be really helpful if you can share your logs with us by sending it to help@getpostman.com

You can find the logs in `View -> Developer -> View Logs`
Thanks.

**Comment by saswatds** [comment]
Hi @m3dbedb we were able to reproduce this on our end. A fix will be on the way soon.

**Comment by codenirvana** [comment]
Fixed in the latest version of the Postman app (v7.6.0).
