### ISSUE TITLE
Comparing non-trivial JSON data from one request to another, to test persistence

### ISSUE THREAD

**Issue by BrambleRamble** [a85/POSTMan-Chrome-Extension#6962]
### The problem
I'm currently trying to implement this sort of test to check persistence of JSON data, but can't find an effective method for step 3:
1. Make a request with JSON as the body
1. Make a second request to retrieve this same data, expecting it to have undergone light or moderate processing
1. Confirm that the response body from (2) extends or adapts the request body from (1) in the expected way, _and confirm that the original data has been persisted_.

### Why it matters
This is a fairly common pattern. In cases where the data only contains a couple of things, they can be checked individually, but this approach does not scale.

Sometimes I'd want to check that the returned JSON has the uploaded JSON as a subset of it.
Potentially I might want to also check that some fields have been added or modified in a particular way.

### What I've tried
I can capture the original request body as an environment variable using `request.data`, and get it back later using `JSON.parse`. Then I can extend/modify it to reflect my expectations of the processing, and after that I'd like to compare the two JSON objects. That's the tricky bit.

I haven't found a way to compare JSON objects meaningfully & in a scalable way in Postman. I've found recommendations on StackOverflow of `chai-shallow-deep-equal` and `chai-subset`, but can't import them to use them in Postman.

Importantly, it's _not_ the schema I want to check as much as the persistence of the original data, so I don't think that ajv or tv4 are the solution. 

### The questions
Is there an existing way to test the persistence of non-trivial JSON data that I just haven't discovered please?
If so, could this be documented/broadcast more? 🙂 
If not, please could we consider adding this functionality?

**Comment by shamasis** [comment]
Indeed. @BrambleRamble I see your point. But I have a few questions... when you say compare, do you mean programmatic comparison or visual comparison? If visual, maybe we could have a way to show the “diff” between a response and saved examples?

**Comment by BrambleRamble** [comment]
@shamasis Interesting question.
The ability to automate this as a test is much more valuable to me, because it's a kind of check that I potentially want to run dozens or hundreds of times a day.
Relatively speaking, I would only need to do visual comparisons very rarely, so I'm quite happy to copy and paste the relevant data into another diffing tool in that scenario.

**Comment by shamasis** [comment]
Then something useful is leveraging external diffing tools like many VCS do.

**Comment by BrambleRamble** [comment]
Could that be incorporated so that it could be used in this kind of syntax?
```
pm.test("Returns JSON matching expected JSON", function() {
   pm.expect(pm.response.json()).to.be.an.equivalent.json.object.to(my_other_json);
});
```
This is the kind of automatobility that would be most valuable to me. Obviously I'm open to suggestions of better syntax :-)

I'd want this to identify these two JSON objects as equivalent:
```
{
  "colour": "red",
  "height": 17
}
```
```
{
  "height": 17,
  "colour": "red"
}
```

**Comment by shamasis** [comment]
Hmm. I think for your particular solution, there might be something already. 

Try 

```
pm.test("match json - but not strictly", function () {
  pm.expect(pm.response.json()).to.deep.equal(other_json_object);
}
```
There are more tricks that you can do from the docs here: https://www.chaijs.com/api/bdd/

**Comment by BrambleRamble** [comment]
`chai-shallow-deep-equal` was one of the options I looked at originally, but I wasn't able to import it to use in Postman. If there's a way to import it then that would be ideal.

**Comment by arnitkun** [comment]
Hi!

<img width="725" alt="Screenshot 2019-08-21 at 5 44 05 PM" src="https://user-images.githubusercontent.com/15148735/63431128-d0667180-c43b-11e9-9f35-a5025be956c5.png">

The test passes.

You can use chai's deep equal as is in the scripts. You do not need to import it for this.

**Comment by shamasis** [comment]
@BrambleRamble ... let me know if your use case is met and then will close the issue. Meanwhile, I have conveyed to test of our team to add more documentation around Postman test assertions.

**Comment by BrambleRamble** [comment]
Ah! Yes, this is exactly the kind of comparison I was looking for. How frustrating that I couldn't get it working before, I was so close! Thank you for the working example.

In case anyone else is looking to compare data across requests, here's how I've got it working.
In test script for the request that POSTs the data:
```
pm.environment.set("input_body", request.data);
```
In test script for the request that GETs the data back:
```
let original_body = JSON.parse(pm.environment.get("input_body"));
// optionally add/set values in original_body to represent expected processing
let response_body = pm.response.json();

pm.test("Response body is equivalent to original body", function() {
   pm.expect(response_body).to.deep.equal(original_body); 
});
```

Adding more documentation/examples to show what expectations can be used would be really helpful please, I think that would have helped me work out the solution myself more easily. Perhaps the key thing I was missing was the way that Chai syntax from their documentation can be converted to work in Postman. In hindsight this is obvious, but evidently it hadn't clicked for me before.

Could you update this issue once the documentation has been updated please? It can be closed now 🙂

**Comment by kaustavdm** [comment]
@BrambleRamble We addressed much of these in postmanlabs/postman-docs#1774. You can see the docs here: https://learning.getpostman.com/docs/postman/scripts/test_examples/#assertion-library-examples

Do you think this is good enough for now? (I know there are a few formatting issues 😞)

**Comment by BrambleRamble** [comment]
@kaustavdm Thanks for your patience! Yes, I think that looks good. The only suggestion I'd have would be to show the setting of `data1` and `data2` before they're compared, a bit like how @arnitkun set them out in their comment above. That would be helpful context, and would make the example a bit more tangible.

**Comment by kaustavdm** [comment]
Thanks @BrambleRamble! Those changes were in fact made by @arnitkun :-) I'll add your feedback as a note to improve the docs.

I'll close this issue now. Do write back if there is something new you spot.
