### ISSUE TITLE
When editing graphql variables, cursor jumps to query pane on every keystroke

### ISSUE THREAD

**Issue by jtbennett** [a85/POSTMan-Chrome-Extension#6963]
**Describe the bug**
When editing a graphql request, the cursor jumps to the end of the Query pane after every keystroke.

**To Reproduce**
1. Create a POST request.
2. Under the Body tab, select GraphQL.
3. Enter a query in the Query pane.
4. Place the cursor in the Variables pane.
5. Type any character - the cursor is now at the end of the Query pane.

Each keystroke correctly enters the typed character at the cursor location, but then the cursor jumps to the end of the Query pane. Typing more than one character at a time requires clicking back to the Variables pane after every keystroke.

**Expected behavior**
I should be able to enter text or edit pasted content more than one character at a time in the Variables pane.

**App information (please complete the following information):**
 - Native app
 - Postman Version 7.2.2
 - OS: macOS 10.14.4

**Comment by appurva21** [comment]
@jtbennett I followed the exact steps as mentioned by you but was not able to reproduce the issue. It would be very helpful if you could share some more insights about how you reached that state by sharing some GIFs or screenshots.

**Comment by jtbennett** [comment]
This happened consistently for about a day, but I haven't been able to replicate since. Closing.
