### ISSUE TITLE
400 error in Newman for 4 tests out of 46, all pass in Postman

### ISSUE THREAD

**Issue by TimEganGitHub** [a85/POSTMan-Chrome-Extension#6964]
**Describe the bug**
Test works in Postman but not in Newman.  Getting a 400 error.  Only 4 tests fail out of 46.  All 46 passed before June 26th.

**To Reproduce**
1. Tests runs in Postman but fails when running CICD in Newman
The bug is reproducible every time in Newman, passes in Postman every time.
 First noticed the issue around June 26  2019.  Worked for many months before.
 

Authorization:  Inherit auth from parent  (same as all the other tests)
Header:
Content-Type Application/json

Body:
{
      "name": "{{chNameAr}}" ,
      "financialBusinessSegmentId": 2,
       "sortKey": 10
      
    }
Pre-request script:
var randomNumber = (Math.floor(Math.random() * 100 + 1).toString());
var text = "NewArea" +  randomNumber;
console.log (text);

pm.globals.set("chNameAr",text);
pm.globals.set("Num",randomNumber);

Tests:

pm.test("Successful POST request", function () {
    pm.expect(pm.response.code).to.be.oneOf([201,202]);
});

pm.globals.unset("idFinAr");

if( pm.response.code===201) {
    
    var jsonData= JSON.parse(responseBody);
    id=jsonData.id;
   
    console.log(id);
    pm.globals.set("idFinAr", id);
  
 }

Similar issue found at:
https://github.com/postmanlabs/newman/issues/398

**Expected behavior**
Expected Newman tests to pass as in the past.

**Screenshots**
![image](https://user-images.githubusercontent.com/32934359/61552557-fe0b6580-aa0c-11e9-982c-5f9e1009e93c.png)

**App information (please complete the following information):**
Using the Postman App v6.7.4, Newman 3.9.0

**Additional context**
Similar issue found at:
https://github.com/postmanlabs/newman/issues/398

**Comment by shamasis** [comment]
Hey. We would need more details to debug this. I suspect this could be an issue with cookies or auth. 

Can you reproduce this issue using a small subset of requests? Say 2 requests, with both passing in Postman and one failing in Newman. With this setup, if you can send me the exact request and response details from Postman Console and then verbose logs from Newman.

**Comment by TimEganGitHub** [comment]
Hi Shamasis,  I’m working on getting a smaller test together.  Hopefully I will have that done today.

I’m not sure how to get the Verbose logs from Newman.  Can you help?

Thanks

Tim

**Comment by TimEganGitHub** [comment]
Hi Shamasis,  Please see the attached file.  It’s the smaller version that you requested.
 The test that fails in Newman but Passes in Postman is Post “Financial Area”
I also asked our Release manger to clear the Cookies but that might not happen until later today.

Thanks

Tim



From: Tim Egan
Sent: Monday, July 22, 2019 10:19 AM
To: postmanlabs/postman-app-support <reply@reply.github.com>; postmanlabs/postman-app-support <postman-app-support@noreply.github.com>
Cc: Author <author@noreply.github.com>
Subject: RE: [postmanlabs/postman-app-support] 400 error in Newman for 4 tests out of 46, all pass in Postman (#6964)

Hi Shamasis,  I’m working on getting a smaller test together.  Hopefully I will have that done today.

I’m not sure how to get the Verbose logs from Newman.  Can you help?

Thanks

Tim

**Comment by shamasis** [comment]
@TimEganGitHub ... it seems like that the attachment did not get through. Can you share the link to the collection by hitting “share” from the menu in Postman sidebar? And to run newman in verbose mode, I think there’s a `--verbose` option.

**Comment by TimEganGitHub** [comment]
I’m sending the json file again here.

I tried clicking Share in Postman but it only allowed me to share with my other teams.  I might be missing something as I haven’t shared with Postman before.  Please send me instructions of what you want me to do.

Thanks

Tim

**Comment by vikiCoder** [comment]
Hi @TimEganGitHub 

Please share the collection link as previously suggested by @shamasis so that we can reproduce your issue at our end. If you don't know how to get a shareable link of the collection, please refer to [this link](https://learning.getpostman.com/docs/postman/collections/sharing_collections/#sharing-collections-with-a-link) from Postman Learning Center.

**Comment by TimEganGitHub** [comment]
Hello Premang,

  Please see the collection link https://www.getpostman.com/collections/2004ec7762da19644209.
The error occurs on Post Financial Area.

The tests pass when run from Postman or from the Command prompt.  Just a few tests including Financial Area fail when executed in our pipeline.  The tests have worked in the past.

Thanks

Tim

**Comment by TimEganGitHub** [comment]
Hi Premang,

  It turns out that the developers moved our pipeline tests from VSTS to Git Hub without my knowledge.  The updates I was adding in VSTS weren’t getting to the script.
This ticket can be closed.

Thanks so much for helping.

Tim


From: Tim Egan
Sent: Thursday, August 1, 2019 10:31 AM
To: postmanlabs/postman-app-support <reply@reply.github.com>; postmanlabs/postman-app-support <postman-app-support@noreply.github.com>
Cc: Mention <mention@noreply.github.com>
Subject: RE: [postmanlabs/postman-app-support] 400 error in Newman for 4 tests out of 46, all pass in Postman (#6964)

Hello Premang,

  Please see the collection link https://www.getpostman.com/collections/2004ec7762da19644209.
The error occurs on Post Financial Area.

The tests pass when run from Postman or from the Command prompt.  Just a few tests including Financial Area fail when executed in our pipeline.  The tests have worked in the past.

Thanks

Tim
