### ISSUE TITLE
Support for Akamai's API Authorization (Edgegrid)

### ISSUE THREAD

**Issue by javiergarza** [a85/POSTMan-Chrome-Extension#6966]
Akamai is the largest Content Delivery Network in the world, and is used for delivering API traffic at scale by a lot of companies (for example as of June 2019, some of Akamai customers leverage their Edge Platform to deliver 5+ **trillion** of API calls/month).

Akamai has around 100 APIs that allow their customers to manage all the different cloud services, however the API authentication model -called Edgegrid- is not currently supported by Postman, making it relatively time consuming to setup Postman to consume Akamai APIs (see https://developer.akamai.com/blog/2018/01/10/using-postman-test-akamai-apis to learn what is required to use postman to explore Akamai APIs)

It would be great to include an "Akamai Edgegrid" Authorization type within Postman that would make easier for Akamai customers to use Postman (see screenshot below)

<img width="706" alt="Postman Akamai authorization" src="https://user-images.githubusercontent.com/7927364/61567171-7c7afe00-aa33-11e9-821d-9636be97d192.png">

Apart from the link above, you can find all of Akamai's open source code (including Edgegrid authorization modules for the most popular programming languages on https://github.com/akamai). 

Feel free to reach out if you have any questions, we heard many of Akamai customers love Postman, and it would be great to lower the barriers of adoption.

**Comment by shamasis** [comment]
I’m tracking this as a feature request. We are working to make auth system have plugin ability. But that’s a while away. Meanwhile, if anyone is interested, can send a PR to postman-runtime and test using Newman. 

Currently all auths are coded here https://github.com/postmanlabs/postman-runtime/tree/develop/lib/authorizer

**Comment by javiergarza** [comment]
@shamasis Can you please take a look at @joaquin-gimenez code? I put his code inside /Applications/Postman.app/Contents/Resources/app/node_modules/postman-runtime/lib/authorizer/noauth.js, and set up the 4 headers below and put the secrets on environment variables and was able to make API calls to Akamai APIs fine. 
![akamai-edgegrid-auth-postman](https://user-images.githubusercontent.com/7927364/62800577-8fb04500-ba98-11e9-8819-333d9e6d485b.png)
![akamai-edgegrid-auth-postman2](https://user-images.githubusercontent.com/7927364/62800714-e6b61a00-ba98-11e9-8c5f-47961658fdd7.png)

**Comment by shamasis** [comment]
@javiergarza @joaquin-gimenez ... thanks for this. Let me begin by saying that the love and involvement from community members, such as in this case, has always been the greatest motivation for us to build Postman. So, here is what we will do:

1. Understand the Akamai Edgegrid auth spec carefully
2. Absorb the code changes from the PR sent
3. If we find no other blockers (I am almost sure that we wont)
4. Will queue adding this to our auth list in upcoming releases.

I would love if you both can reach out to me (Shamasis Bhattacharya) via help@getpostman.com so that I can introduce you to the team, in case we need quick communication line.

cc @postmanlabs/runtime

**Comment by vikiCoder** [comment]
Hi @javiergarza 

Are there any public endpoints or local environment setup to test the auth implementation in the Postman app?

**Comment by javiergarza** [comment]
We don't have any public endpoints. I sent Matt Ball API credentials for our [contracts API](https://developer.akamai.com/api/core_features/contract/v1.html) a while back. Please send me an email at javierATakamai.com and I will resend API credentials you can use for testing

**Comment by vikiCoder** [comment]
Hi,

We have added Akamai's EdgeGrid authentication method in the latest version of the Postman App (v7.10.0). You can [update your Postman App](https://learning.getpostman.com/docs/postman/launching_postman/installation_and_updates/#updating-postman) and try it out. We would love to hear feedback about it from you.

<img width="1138" alt="Screenshot 2019-11-25 at 12 54 59 PM" src="https://user-images.githubusercontent.com/16588032/69520582-0fe4b280-0f83-11ea-9cff-4a8a294074c7.png">

**Comment by zhengyuhe01** [comment]
the api so bad,
Authorization header missing
Authorization header missing

**Comment by zhengyuhe01** [comment]
Authorization header missing
Authorization header missing

**Comment by zhengyuhe01** [comment]
the api so bad,
Authorization header missing
Authorization header missing

can you tell me why??????????

curl -H "access_token:akab-"
-H "client_secret:LQmdxgG3"
-H "client_token:akab-"
-H "Content-Type:application/json"
-H "host:akab-"
-d '{"objects": [******]}'
-X POST
https://akab-******/ccu/v3/invalidate/cpcode/staging
