### ISSUE TITLE
how can i auto save my request in postman after i test the request?

### ISSUE THREAD

**Issue by honkkki** [a85/POSTMan-Chrome-Extension#6967]
always forget to ctrl+s and next time the request url will missing.

**Comment by idevtech** [comment]
Agreed, Add "auto save" option like Google Docs w/ option to disable it.

**Comment by Amyth07** [comment]
+1

**Comment by laviua** [comment]
+1

**Comment by lucastruong** [comment]
+1

**Comment by DeeplyDiligent** [comment]
+1

**Comment by hoangdinhini** [comment]
+1

**Comment by dzulliet** [comment]
+1

**Comment by a85** [comment]
We are tracking auto save functionality elsewhere in the tracker. It will be integrated with other version control features inside the app.

**Comment by mahmoudahmed2222** [comment]
+1

**Comment by Ragnoroct** [comment]
@a85 Can you tell us where that is being tracked?

**Comment by wiwwo** [comment]
Any news on this? :-)

**Comment by arlemi** [comment]
@wiwwo We're tracking this in #8195

**Comment by nrshapiro** [comment]
+1

**Comment by ccyeh0901** [comment]
please....

**Comment by arlemi** [comment]
We're already tracking this in #8195, locking this issue. 🙂
