### ISSUE TITLE
Postman 7.2.2 black screen on MacOS 10.14.5

### ISSUE THREAD

**Issue by remyaradha** [a85/POSTMan-Chrome-Extension#6969]
**Describe the bug**
After updating to 7.2.2 version, Post man screen turns black in few minutes once the app is started

**To Reproduce**
1. Open the post man app
2. Keep for a minute
3. Full screen of the app turns black and nothing can be done

**Expected behavior**
Post man screen should show the menu items and work as normal

**Screenshots**
If applicable, add screenshots to help explain your problem. Please make sure the screenshot does not contain any sensitive information such as API keys or access tokens. 

**App information (please complete the following information):**
 - App Type : Chrome App,
 - Postman Version : 7.2.2
 - OS:  macOS Mojave
            Vwesion 10.14.5

**Additional context**
Tried disabling the GPU as mentioned in https://github.com/postmanlabs/postman-app-support/issues/4634, but it didn't work.
It is working fine in the latest Canary version- 7.3.4

Postman console log: 
![image](https://user-images.githubusercontent.com/40347468/61605473-f9eb7c00-ac88-11e9-8057-ea805899ccad.png)

**Comment by cyrielle-hada** [comment]
Hi @remyaradha, would you please send over a .zip file of your your app logs to help@getpostman.com? To find them, navigate to `View > Developer > View Logs in Finder`.  Please mention this GitHub issue in your message. 

<img width="500" alt="Screen Shot 2019-07-24 at 15 33 12" src="https://user-images.githubusercontent.com/47351631/61803488-238fd900-ae2a-11e9-80d0-b26f48aee321.png">

To get you unblocked, let's try to remove the local data. Please note that this action will permanently delete your local Postman data and logs. Make sure that your data are synced before deleting them. 

To remove your local data, let's proceed as follows:
1 - Go to Finder (`CMD + OPTION + Space`)
2 - Go to folder (`SHIFT + CMD + G`)
3 - Paste `~/Library/Application Support/Postman` and hit return
4 - Delete the folder.

If you have multiple versions of the app installed, please make sure to remove them before reinstalling the app.

**Comment by preethammavin** [comment]
@remyaradha we have released 7.3.4 to the stable channel as well, can you try updating the app and checking if that solves the issue? Closing the issue for now, feel free to reopen the issue if it is not solved.

**Comment by preethammavin** [comment]
A

**Comment by remyaradha** [comment]
Version 7.3.4 was auto updated and issue still persists. It works fine with Postman canary 7.3.5

**Comment by blairjanis** [comment]
I'm having this issue as well.  macOS Mojave (10.14.6).  Version 7.3.6 of postman.

**Comment by daniel-dia** [comment]
Still happens on 7.5.0

**Comment by pz2147** [comment]
Postman Version : 7.12.0
OS: macOS Catalina
Version 10.15.1

I'm having this issue as well.

**Comment by vikjdk7** [comment]
I am also facing this issue since I updated my OS to catalina. Postman version - 7.20.1
Do we have any fix for this ?

**Comment by shydefoo** [comment]
Also facing this issue for Postman version 7.20.1 on Catalina 10.15.3

**Comment by dustytrinkets** [comment]
I logged out and in again and it stopped happening
