### ISSUE TITLE
Web dashboard not loading for Workspaces.

### ISSUE THREAD

**Issue by suraj-purohit** [a85/POSTMan-Chrome-Extension#6972]
**Describe the bug**
The web dashboard does not load while opening workspaces url. (Infinite loop)

**To Reproduce**
1. Go to 'https://go.postman.co/workspaces'
4. See error - The web dashboard does not load - Infinite loading icon loop.

**Expected behavior**
When you go to "https://go.postman.co/workspaces"  - Web dashboard should open and "All Workspaces" should be displayed.

**Screenshots**
![image](https://user-images.githubusercontent.com/51916047/61616615-8ea0aa80-ac86-11e9-9b46-d750bd53aa4c.png)

**Additional Context**
This issue is present across different browsers - Google Chrome and IE

**Comment by sankalp0o** [comment]
Hi @suraj-purohit, we've fixed this issue. Can you confirm? If the user is still facing this, please reopen the issue and let us know.

**Comment by suraj-purohit** [comment]
@sankalp0o Ok will do that.
