### ISSUE TITLE
Environment id does not have userId in browse view in app

### ISSUE THREAD

**Issue by kartikjain26** [a85/POSTMan-Chrome-Extension#6973]
**Describe the bug**
Incorrect environment id sent from app browse view

**To Reproduce**
1. Go to  browse view in app
2. Click on environments tab
3. Select an environment to go to dashboard view

**Expected behavior**
Environment view should open

**App information (please complete the following information):**
 - Postman Version [7.3.3]
 - OS X 18.0.0 / x64

**Comment by sankalp0o** [comment]
@kartikjain26 The fix for this is out in the latest version for the app (v7.6). I'm closing the issue, but feel free to reopen this in case the problem persists.
