### ISSUE TITLE
Add Annotation support in Body

### ISSUE THREAD

**Issue by wahedzaman** [a85/POSTMan-Chrome-Extension#6974]
Hi, Using Postman for a long time for my development. And thanks for this awesome product and continuous development.

It would be highly appreciated if we can have an annotation tool support for the response body. 

For example, when a request is made and response is shown in the body area (considering json response, but can be done for the html response as well), we can select a particular word or a line and add annotation (custom remarks or identifier) in a popup window. So, later it will be easier for us to review the response.

When there is an annotation, it can show a highlight on the line or the word and clicking on it can display the annotated remarks in the pop up window.

**Comment by shamasis** [comment]
Indeed this is a fine idea. I’m sure our design team would love to include your thoughts when we work at further improving our collaboration features.

**Comment by sankalp0o** [comment]
Hi @durbin-studio! We have the ability to annotate request body and it works very similar to what you suggested. Please give it a try and let us know how we can improve the experience! I'm closing the ticket, but looking forward to your feedback.
