### ISSUE TITLE
post collection runner ,how to save the responses of multiple iteration to a file.

### ISSUE THREAD

**Issue by m-samantha** [a85/POSTMan-Chrome-Extension#6976]
I am testing an API using the collection runner and  I am getting the test data from the file that has 1000 records . the collection test ran successfully for all the 1000 iterations . when importing the test results it is saving the data for only a selected iterations and not all the 1000 iterations. Is there a way to save the results of all the 1000 iterations to a file. 

**App information (please complete the following information):**
  App Type - Native
  Postman Version - 7.2.2
  OS: win32 6.1.7601 / x64

**Comment by saswatds** [comment]
Hi @m-samantha, Thanks for reporting in. There is a bug in our import/export flow in collection-runner that is preventing you from exporting the entire collection run summary.

We have already taken up this issue in high priority and will be fixing this issue very soon. 
Until then you can try out our cli runner Newman https://github.com/postmanlabs/newman
which has an inbuilt json reporter which generates a consumable file

Thanks

**Comment by andreamoro** [comment]
Do we have any update on when a fix will be ready here?

**Comment by malvikach** [comment]
The bug is resolved now.  Apologies for the inconvenience caused due to this. 
Please Refer [this issue](https://github.com/postmanlabs/postman-app-support/issues/11528#issuecomment-1418899977) for more details.
