### ISSUE TITLE
Allow for users to download v 7.0.9

### ISSUE THREAD

**Issue by th-m** [a85/POSTMan-Chrome-Extension#6977]
Lots of my stuff doesn't work in latest versions of postman... but did in 7.0.9 is there a way to revert. Thanks

**Comment by preethammavin** [comment]
@th-m can you let us know what is not working on the latest version, we work actively and treat regression bugs on the product as top priority. Would want to address them asap.

**Comment by preethammavin** [comment]
@th-m closing this thread for now, feel free to open issues which you feel are hindering your workflow so that we can get it sorted for you
