### ISSUE TITLE
postman fails to resolve .local addresses resolved with mdns

### ISSUE THREAD

**Issue by ran-berenfeld** [a85/POSTMan-Chrome-Extension#6979]
We have installed a network endpoint that resolves via mdns addreeses such as api.t.local
however postman fails to resolve such requests.
for example curl works :
curl http://api.t.local/provider/v1/providers
{"items":[]}
while postman fails to resolve the host (see screenshot attached):

![postman-fails](https://user-images.githubusercontent.com/47638959/61692556-928c0580-ad36-11e9-9e66-ecf0abc51890.png)

**To Reproduce**
1. install on the network an mdns server that will resolve multicast dns queries
2. update 
in /etc/nsswitch.conf 
hosts:          files mdns4 [NOTFOUND=return] dns
in /etc/mdns.allow
.local
.local.
3. open postman and try to retrieve a url with host .local

**Expected behavior**
postman returns the same result as curl

**App information (please complete the following information):**
 - App Type 
 - Postman Version 6.7.1
 - OS: Ubuntu 18.10

**Additional context**

**Comment by dellgreen** [comment]
experiencing the same problem on 18.04.3

**Comment by codenirvana** [comment]
@ran-berenfeld @dellgreen is this issue still persists in the latest version of the Postman app?

**Comment by dellgreen** [comment]
> @ran-berenfeld @dellgreen is this issue still persists in the latest version of the Postman app?

@codenirvana this appears to be fixed in the latest canary Postman v7.21.0-canary01 that I tested on linux x64 :)

**Comment by codenirvana** [comment]
@dellgreen Thanks for the confirmation 👍 
The same changes are available in the latest version of the Postman app.

Please feel free to reopen if the issue persists or you can help us with the steps to reproduce this issue.

**Comment by mavaa** [comment]
Hello, I'm having this issue on Ubuntu 20.04 beta, with Postman 7.22.1 from the Snap store. Given the app all permissions/connections. Using a .local domain doesn't work, but using the ip address directly does.
I've also tested that the domain name works in curl and my web browser without issue. Could you reopen this issue, or should I create a new one?
