### ISSUE TITLE
Unclosed xml CDATA tag crashes UI (black screen)

### ISSUE THREAD

**Issue by StephenOsborne0** [a85/POSTMan-Chrome-Extension#6982]
**Describe the bug**
UI crashes to black screen when unclosed CDATA tag loaded in request body (text/xml)

**To Reproduce**
1. Create a new request.
2. Go to the "Body" tab
3. Select "raw" and "XML (text/xml)"
4. Paste (or type) the following into the body editor window:

![image](https://user-images.githubusercontent.com/45471959/61729687-ab64dd00-ad6f-11e9-96fe-1cd606014092.png)

5. Wait approx 10 seconds and the parser will fail and black screen the UI.

**Expected behavior**
Parser should not crash / black screen the UI.

**Screenshots**
![image](https://user-images.githubusercontent.com/45471959/61729430-17931100-ad6f-11e9-9129-43a2b4f76b74.png)
![image](https://user-images.githubusercontent.com/45471959/61729322-d7339300-ad6e-11e9-92d1-4edd5cbb79b1.png)

**App information (please complete the following information):**
 - App Type: Windows Desktop App
 - Postman Version 7.2.2
 - OS: Windows

**Additional context**
Issue will not occur until the request body tab is opened. It also has a delay before the black screen, which gives you enough time to go in and remove the offending xml.

**Comment by numaanashraf** [comment]
@StephenOsborne0 We were able to replicate this and will get this resolved in upcoming releases. Thanks for pointing this out.

**Comment by kamalaknn** [comment]
This should be fixed in the latest version of Postman
