### ISSUE TITLE
Web Dashboard – Accessing Environments Throws Invariant Violation Error

### ISSUE THREAD

**Issue by chrisdeso** [a85/POSTMan-Chrome-Extension#6985]
**Describe the bug**
When accessing an environment via the web dashboard – e.g. https://go.postman.co/dashboard – the page doesn't render and an `Invariant Violation` error is thrown in the browser console.

**To Reproduce**
1. Navigate to web dashboard – https://go.postman.com
2. Select a workspace
3. Open environments associated with the workspace and select one
4. See error in browser console

**Expected behavior**
Environment information should render

**Screenshots**
![image](https://user-images.githubusercontent.com/4734306/61743206-684c3f00-ad5a-11e9-9ee4-9448edb0dcd3.png)

**App information (please complete the following information):**
 - Browsers: Chrome

**Additional context**
[Filed by Postman]

**Comment by kartikjain26** [comment]
@chrisdeso  The fix is under review. Should be out in next release.

**Comment by chrisdeso** [comment]
Thanks for the update @kartikjain26

**Comment by kartikjain26** [comment]
@chrisdeso  This has been resolved in production

**Comment by mccannt** [comment]
Issue has been resolved.
