### ISSUE TITLE
Feature to automatic results/response body export option to desired local folder, as we have requirement to validate other stuff based on response msg. Please suggest code/features exist otherwise please add

### ISSUE THREAD

**Issue by varaveet** [a85/POSTMan-Chrome-Extension#6986]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by preethammavin** [comment]
@varaveet if you are talking about sending a request , there is a feature for send and download for the requested response. 

We could understand the workflow a bit better, if you can explain with the above mentioned format or elaborate the feature.

**Comment by varaveet** [comment]
Like if i provide some path prior, responses should be stored in that location. This will reduce manual intervention of going and clicking send and download option everytime

**Comment by preethammavin** [comment]
@varaveet that would be something which would introduce complexity in the product where we have no control over so for now this is not something we would be picking up, would suggest to use collection runner and generate the history response from there and export it at bulk. Or use Newman + Postman API to generate the response and store it locally

Both of these should enable your workflow.
