### ISSUE TITLE
API Platform - Importing a schema from a file is not auto selecting the File Type

### ISSUE THREAD

**Issue by DannyDainton** [a85/POSTMan-Chrome-Extension#6988]
**Describe the bug**

When importing a new API from a file, the correct `file type` is not being auto-selected and it defaults to JSON. This causes the user to manually go and select the file type from the dropdown list in the UI, in order to fix the JSON validation issues and see the correct syntax highlighting.

**To Reproduce**

1. Go to the `APIs` Tab in the main app
2. Click on the `Create an API` button if it's your first API or use the `+ New API` button if it's not
3. Import a new `non-JSON` schema using either of the import flows (browse for the file/drag and drop)

**Expected behaviour**

When a file is either Imported, the file type should be auto-selected from the list of options (If the file type is supported/content is valid). 

**Screenshots/gifs**

The gif below shows the current in-app behaviour: 

![File_Type](https://user-images.githubusercontent.com/17089546/61793129-49ab7e00-ae16-11e9-9621-9c617327d94d.gif)

**App information:**
- App Type Native App
- Postman Version 7.3.4
- OS: macOS Mojave 10.14.5

**Additional context**

This code can be saved as a `.yml` file to test the issue:

```yml
openapi: 3.0.0
info:
  title: Sample API
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.1.9
servers:
  - url: http://api.example.com/v1
    description: Optional server description, e.g. Main (production) server
  - url: http://staging-api.example.com
    description: Optional server description, e.g. Internal staging server for testing
paths:
  /users:
    get:
      summary: Returns a list of users.
      description: Optional extended description in CommonMark or HTML.
      responses:
        '200':    # status code
          description: A JSON array of user names
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string
```

**Comment by DannyDainton** [comment]
@sankalp0o I need to reconfirm that this is still an issue as there has been a lot of work down with the import flow recently. Do you know if this was picked up as part of the work?

**Comment by sankalp0o** [comment]
No, this wasn't picked up. @vvs11 can you take a look, please?

**Comment by DannyDainton** [comment]
No longer seeing this in Version 8. Closing out.
