### ISSUE TITLE
Tab Options dropdown layout breaking with Windows shortcut labels

### ISSUE THREAD

**Issue by vkaegis** [a85/POSTMan-Chrome-Extension#6989]
**Describe the bug**
The Tab Options dropdown menu layout is breaking in Windows, with the `Force Close Current Tab` option splitting into two lines without appropriate top/bottom padding.

**To Reproduce**
1. Go to the tab header
2. Click on Options icon '....'
4. See broken layout

**Expected behavior**
The menu should accomodate for the longer shortcut labels in windows (Ctrl instead of Cmd) or provide appropriate padding in multi-line scenarios.

**Screenshots**
![image](https://user-images.githubusercontent.com/6038010/61801970-526b7680-ae4d-11e9-8c3a-c1d482c61e79.png)

**App information (please complete the following information):**
 - App Type: Native
 - Version: 7.2.2
 - OS: win32 10.0.17134 / x64

**Comment by kamalaknn** [comment]
A fix for this has been released on Postman 7.6.0
