### ISSUE TITLE
Newline ( \u000a ) breaks Pretty view in 7.3.4

### ISSUE THREAD

**Issue by COB-SM** [a85/POSTMan-Chrome-Extension#6991]
In 7.3.4, if a response contains an newline, Pretty view seems to stop parsing/indenting:

Raw:
![RawJSON](https://user-images.githubusercontent.com/39503632/61822889-ec183100-ae17-11e9-8907-648ce5fe0ac5.png)

Pretty:
![PrettyJSON](https://user-images.githubusercontent.com/39503632/61822906-f6d2c600-ae17-11e9-8706-d11f0d925b6b.png)

This does not happen in 7.2.2

**Comment by ankurdengla** [comment]
Hey @COB-SM ! Thanks for bringing this issue to our notice. We were able to reproduce the issue and are working on a fix for this. Please monitor this thread for updates.

**Comment by dave-johnson-netcel** [comment]
Heya. I am seeing similar behaviour with an encoded double quote character (\u0022) breaking the pretty print view:

![image](https://user-images.githubusercontent.com/19838981/61882662-d75b9c00-aef0-11e9-886b-58f26bb47804.png)

**Comment by ankurdengla** [comment]
@COB-SM @dave-johnson-netcel The fix for this issue is out on our Canary build (PostmanCanary 7.3.5-canary04) which can be downloaded here - https://www.getpostman.com/downloads/canary .
Do let us know if the issue persists.

**Comment by dave-johnson-netcel** [comment]
Thanks, that's resolved the issue.

**Comment by COB-SM** [comment]
Resolved for me as well. It also resolved a secondary issue with escaped slashes suddenly appearing. Thanks!

**Comment by kamalaknn** [comment]
This fix is now available on the stable channel as well from Postman 7.3.6. Please update your app to the latest version and give it a try.
