### ISSUE TITLE
Fired request getting replaced by another request while waiting for a response

### ISSUE THREAD

**Issue by kratigya** [a85/POSTMan-Chrome-Extension#6992]
**Describe the bug**
When I open a tab and send a request but the response is loading then if I open another request then the tab for the previous request is replaced by the new request tab and the response displayed is of the previous request.

**To Reproduce**
1. Open a request which takes a longer time to respond. Request Tab is in preview state.
2. Send the request and response is in loading state.
3. In the meanwhile, before the response is displayed open another request.
4. The new tab (tab for 2nd request) replaces the older one.

**Expected behavior**
The new tab should not replace the older tab and response should be displayed for the request that it was sent.

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version: Postman v7.3.5-canary01
 - OS: macOS Mojave 10.14.5

**Comment by saswatds** [comment]
Hi @kratigya0705 can you help us with GIF to understand the problem better. Not been able to reproduce based on the steps provided.

**Comment by mccannt** [comment]
Resolved in v7.29.0
