### ISSUE TITLE
Can't open postman

### ISSUE THREAD

**Issue by ghost** [a85/POSTMan-Chrome-Extension#6995]
**Describe the bug**
I cleared the cache from the dev tools, and now postman does not open. I tried to uninstall and install it again but it won't start. I downloaded the newest version, but an  error shows saying that the app can't not start.

**App information (please complete the following information):**
 - App Type: Windows App
 - Postman Version 7.3.4
 - OS: Windows 10

**Comment by mccannt** [comment]
@Sam-Black-0013 
Is this still happening? 

If so, are you able to elaborate a bit more on the error message you are seeing? Maybe add a screen shot if you are able to.

**Comment by Endorel** [comment]
I have the same issue. Here is a screenshot:
<img width="425" alt="Screenshot 2019-08-05 at 17 13 03" src="https://user-images.githubusercontent.com/16289839/62474977-5d56cd00-b7a4-11e9-8895-31524670af96.png">

I'm on a MacBook Pro running macOs Mojave version 10.14.5 and postman version 7.3.6

I have tried re-installing with a download from the postman site, but no luck.

**Comment by mccannt** [comment]
Thx for the update @Endorel we will look into this.

**Comment by ghost** [comment]
@mccannt any update on this? I'm running into the same issue.

Postman v7.12.0 
Mac OS Mojave v10.14.6 

Have tried uninstalling, reinstalling, clearing things, etc. No dice.

UPDATE: 
Disregard, I just noticed there was a newer version (7.14.0) that I didn't have. I've installed that and all boots up fine now. :-)

**Comment by twitharshil** [comment]
Hey @Sam-Black-0013 @Endorel 

Following the steps mentioned in this [link](https://support.postman.com/hc/en-us/articles/360025359014-How-to-resolve-the-Could-not-open-Postman-error-) should unblock you. Closing the ticket, feel free to re-open if you still face the issue.
