### ISSUE TITLE
Can postman unescape slashes in JSON response ?

### ISSUE THREAD

**Issue by hheedat** [a85/POSTMan-Chrome-Extension#6996]
https://bugs.php.net/bug.php?id=49366

In many PHP service,  response will be escaped slashes by default.(always not your service)

When URL in JSON be escaped slashes default. It is difficult to read, and can not be use direct by copy-paste . Some tools can unescape slashes in JSON, it is very convenience.

I suggest postman can also provide some option to unescape slashes in JSON.

Thanks!

**Comment by kamalaknn** [comment]
Hi @hheedat 

Thanks for reporting this. We are tracking this in #6899.

I'm closing this issue as a duplicate, please follow the original issue for updates.
