### ISSUE TITLE
Inconsistent spacing around descriptions in web documentation viewer

### ISSUE THREAD

**Issue by abitgone** [a85/POSTMan-Chrome-Extension#6997]
When viewing  the collection documentation in the browser, there's some curious spacing around the comments in the form data and querystring parameters collections, which doesn't appear in the path variables collection:

![Screenshot 2019-07-25 at 14 22 36](https://user-images.githubusercontent.com/62781/61879614-47ffba00-aeeb-11e9-93c0-98b254cef324.png)

**To Reproduce**
1. Open a Postman collection.
2. Make sure the collection has a method with body formdata, query parameters and  path variables.
2. Click on the right arrow on the collection.
3. Click on "View in web"
4. See the extra spacing around the description text.

**Expected behavior**
I'd expect there to be consistency between the three types. 

**Screenshots**
If applicable, add screenshots to help explain your problem. Please make sure the screenshot does not contain any sensitive information such as API keys or access tokens. 

**App information (please complete the following information):**
 - App Type: Documentation Viewer (Web)
 - Postman Version: 7.7.2
 - OS: macOs Mojave 10.14.5

**Additional context**
It looks like there's a paragraph tag surrounding the description in the Body section, but not in the path variables section:

Body (formdata) and Querystring Params:

```html
<table class="pm-table docs-request-table"><tbody><tr class=""><td class="weight--medium">email</td><td>test%2bmailbox%40example.org<div class="pm-markdown docs-request-table__desc"><p>An email address that has been URL encoded.</p>
</div></td></tr></tbody></table>
```

Path Variables:
```html
<table class="pm-table docs-request-table"><tbody><tr class=""><td class="weight--medium">email</td><td>test%2bmailbox%40example.org<div class="pm-markdown docs-request-table__desc">An email address that has been URL encoded.</div></td></tr></tbody></table>
```

The extra `<p>` is causing the additional spacing.

**Comment by Cazaimi** [comment]
@abitgone , thanks for reporting this issue, the comprehensive context and probable root cause. We'll look into this. @Raja-Simha , could you mark this as a bug in `product/documentation`?

**Comment by Raja-Simha** [comment]
Issue has been fixed
