### ISSUE TITLE
After throwing an Error in a callback of a sendRequest in a pre-request script, the main request is still being performed

### ISSUE THREAD

**Issue by juanmbellini** [a85/POSTMan-Chrome-Extension#6998]
#### Bug description
If the code throws an `Error` in the callback of the `pm.sendRequest` function in the pre-request script, the main request is still being performed. However, if the `Error` is thrown outside the callback, the main request is not performed.
The code can be seen below:

```js
console.log("Token is expired or will expire in the next minute. Trying refresh");
var refreshToken = pm.variables.get("refresh-jwt");
var refreshTokenBody = JSON.parse(atob(refreshToken.split(".")[1]));
if (refreshTokenBody.exp - ((Date.now() / 1000) >> 0) < 1) {
    console.log("Refresh token has expired");
    throw new Error("Refresh token has expired");
}


var baseUrl = pm.variables.get("schema") + '://' + pm.variables.get("host") + ':' + pm.variables.get("port");
var url = baseUrl + '/tokens/' + refreshTokenBody.jti + '/refresh';

pm.sendRequest(
    {
        url: url,
        method: "PUT",
        header: {
            "Authorization": "Bearer " + refreshToken + "ASDaaaaaaavvasdasDFadsfasdfasdf"
        }
    }, 
    (err, res) => {
        if (err) {
            console.log("An error has occurred. Error object:");
            console.log(err);
            throw new Error("An error has occurred. Check logs.");
        }
        switch (res.code) {
            case 200: {
                var jsonResponse = res.json();
                pm.environment.set("jwt", jsonResponse.accessToken);
                pm.environment.set("refresh-jwt", jsonResponse.refreshToken);
                return;
            }
            case 401: {
                throw new Error("Invalid refresh token");
            }
            case 403: {
                throw new Error("Blacklisted token");
            }
            default: {
                throw new Error("Unexpected error code: " + code);
            }
        }
    }
);
```

#### To Reproduce
This code tries to refresh the access token by accessing a URL. The refresh token operation is successful only if the request has a 200 status code. Any other code should stop the main request being performed. However, Postman seems to ignore the error when it is thrown inside the callback.

#### Expected behavior
Postman should not perform the main request if the pre-request script throws an `Error`, even if it is thrown inside a callback.

#### App information
 - App Type: Native App
 - Postman Version: 7.2.2
 - OS: macOS Mojave 10.14.5

**Comment by codenirvana** [comment]
@juanmbellini This is fixed in the latest version of the Postman App (v7.7.2).
Can you update your app and confirm if that fixes your issue?
