### ISSUE TITLE
Sync of environments with current values

### ISSUE THREAD

**Issue by nereliz** [a85/POSTMan-Chrome-Extension#7003]
Hi,

**Is your feature request related to a problem? Please describe.**
We do have a lot off different environments. End they are shared in a group. We have domain and auth key in each environment. So domain is in initial variable and auth_key is in current variable fields. Then I have 3 different working spots and I don't see a way to share current variable only by copying to the USB key or something and then copying back. Reinstalling OS would also drop current values. For big amount of environments that does not scale.

**Describe the solution you'd like**
Then you do a data export you should offer an option to include current variables. By default you never include those.

**Describe alternatives you've considered**
As mention above store those in some storage space and do copy paste  a lot of times.

**Additional context**
There is nothing to add here.

Thanks!

**Comment by fsilva3** [comment]
+1

**Comment by shamasis** [comment]
I’m afraid this is by design and in line with the security aspects of having parts of it that can never sync. We will address this use case using other mechanisms. Stay tuned. 😊

**Comment by fsilva3** [comment]
Currently me and my team, we're working with "Persist All" and "Reset All" features... it's not very practical, but works...
![image](https://user-images.githubusercontent.com/1984980/62395390-74987f00-b546-11e9-9e33-6e7a4aaa8738.png)

Initial Value by default is synced, so if you want to update some value, we just update `current value` and click "Persist All", it'll put `current value` on `initial value` column, and then your co-worker can sync and click "Reset All", it'll put `initial value` on `current value` column.
