### ISSUE TITLE
Allow customizing text colors

### ISSUE THREAD

**Issue by philmagr** [a85/POSTMan-Chrome-Extension#7006]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when app developers move my cheese.

**Describe the solution you'd like**
I'd like to be able to keep my cheese where it was when I left it.

**Describe alternatives you've considered**
I've considered using something other than postman.

**Comment by shamasis** [comment]
We have asked Sniff and Scurry to work on this. They’re presently stuck deciding between what is a text and what is not! Any help here would be appreciated.

**Comment by shamasis** [comment]
Hi there @philmagr. Could you please elaborate on what set of text colours are you interested in having customisability for?

**Comment by preethammavin** [comment]
@philmagr closing the issue for now, feel free to reopen it with the information that . @shamasis requested sot that we can address it.
