### ISSUE TITLE
Collection runner does not identify the CSV format when selecting Data file

### ISSUE THREAD

**Issue by j-fbriere** [a85/POSTMan-Chrome-Extension#7008]
**Describe the bug**
When selecting a CSV file as "Data" for the collection runner, it does not recognize the format, neither autodetects the number of records.

**To Reproduce**
1. Click Run to any collection to go to the Collection Runner.
2. Click on the "Select File" button of the "Data" element and select a CSV file with multiple records like this toto.csv sample file:
[toto.csv.txt](https://github.com/postmanlabs/postman-app-support/files/3437463/toto.csv.txt) (the .txt extension must be removed after downloading the file)
3. Observe as the "Data File Type" element says "Undetermined", and the iterations remain at "1".

**Expected behavior**
When selecting a valid CSV file, the "Data File Type" element is modified to "text/csv" and the "Iterations" element is modified to the appropriate number of records automatically.
With the sample CSV file provided it should be 2 iterations.

**Screenshots**
![postman_run_coll_select_csv_data_file](https://user-images.githubusercontent.com/49044668/61983107-0f381180-afcd-11e9-9a31-e011ff219f31.jpg)

**App information (please complete the following information):**
 - App Type: Native App
 - Postman for Windows
    Version 7.3.5
    win32 10.0.18362 / x64
 - OS: Windows 10 Pro English version 1903 build 18362.239

**Additional context**
Notes: 
- The provided CSV file has the Unix-style LF end of lines (and not the usual Windows-style CRLF end of lines), in accordance with the Postman documented limitation of CSV files parser.
- The provided CSV file encoding is: UTF-8.
- The relevant locale Windows settings for the numbers format are: 
-- Decimal symbol: '.' (period)
-- Digit grouping symbol: ' ' (space)
-- List separator: ',' (comma)

**Comment by DannyDainton** [comment]
Hey @j-fbriere,

If you change the file extension to `.csv` rather than `.csv.txt` it will work.

I used your file to take a look at this locally:

<img width="508" alt="Screenshot 2019-07-27 at 07 42 34" src="https://user-images.githubusercontent.com/17089546/61991010-3846b980-b042-11e9-95c6-5e65409f7af5.png">

This is running against the macOS version of the app so their _might_ still be some weirdness going on in the windows app.

**Comment by j-fbriere** [comment]
Hey @DannyDainton,

I added the .txt extension only to be able to attach the toto.csv file to the ticket, as it would not accept the .csv extension for attachment.

As you can see in the screenshot I provided, I selected a file named toto.csv when using Postman.

I think it might be related to Postman on Windows because my colleague used the same toto.csv file with Postman (same version) on macOS and it worked as espected.

**Comment by codenirvana** [comment]
Fixed in the latest version of the Postman app (v7.6.0).
