### ISSUE TITLE
GitHub integration: no Collections selectable

### ISSUE THREAD

**Issue by JP-from-Postman** [a85/POSTMan-Chrome-Extension#7009]
**Describe the bug**
[Reported by Postman Support, on behalf of original user]

User has a team workspace containing a number of Collections, and is attempting to add our GitHub integration.

However, when selecting a Collection as a target for the integration, the dropdown menu is blank. The number of blank items in the dropdown menu, however, does appear to reflect the number of Collections in the workspace:

![Integration](https://user-images.githubusercontent.com/43283131/61986154-0ee64900-afc2-11e9-88ff-285e4f07262c.png)

Selecting one of the blank rows doesn't work, as the "Add Integration" button is still disabled.

**To Reproduce**
_Support unable to reproduce_

**Expected behavior**
Dropdown menu allows selection of Collection.

**Screenshots**
See above

**App information (please complete the following information):**
 - App Type: Native app
 - Postman Version: 7.3.4
 - OS: Linux

**Additional context**
See internal notes

**Comment by kartikjain26** [comment]
@JP-from-Postman  this behaviour is not reproducible consistently. Can you ask the user to try and refresh the page to see if it occurs repeatedly ?

**Comment by davidh-zoosk** [comment]
> @JP-from-Postman this behaviour is not reproducible consistently. Can you ask the user to try and refresh the page to see if it occurs repeatedly ?

I've tried refreshing countless times. I've tried in Chrome, Safari, FF, and IE. Incognito modes for each as well.
Are there any restrictions on who can implement the integration? I have the developer role on our team.

**Comment by davidh-zoosk** [comment]
Here is a video so you can see how the drop-down doesn't get set to any value:
https://www.youtube.com/watch?v=KmuWnsMURuQ

**Comment by davidh-zoosk** [comment]
Just had our admin attempt the integration as well. Same result.
So that means it has been attempted on 3 accounts, 4 machines, and 7 browsers. Safe to say it is an issue with our account.

**Comment by JP-from-Postman** [comment]
@kartikjain26 I agree that this looks team specific. Please see internal notes.

**Comment by davidh-zoosk** [comment]
Hi guys, any updates on this?

**Comment by kartikjain26** [comment]
@davidh-zoosk  We are looking into this issue. Will keep you update about the fix.

**Comment by chrisdeso** [comment]
@kartikjain26 Any updates on this?

**Comment by kartikjain26** [comment]
@chrisdeso  Have update internal jira ticket for this issue.

**Comment by ash007-postman** [comment]
@kartikjain26 Another user facing a similar issue, I have linked the ticket.

**Comment by kartikjain26** [comment]
@ash007-postman  Have identified the issue. Will post updates development.

**Comment by ash007-postman** [comment]
@kartikjain26 Thank you!

**Comment by kartikjain26** [comment]
@davidh-zoosk  @ash007-postman  The issue has been fixed in beta. This will be out in production next week.

**Comment by davidh-zoosk** [comment]
Thank you @kartikjain26 ! Any update on when this will be released? The week is coming to a close.

**Comment by kartikjain26** [comment]
@davidh-zoosk  Its going to be released pretty soon (in a day or two). Will update this thread as soon as it is out on production.

**Comment by kartikjain26** [comment]
@davidh-zoosk  @ash007-postman  This has been released on production today. Can you verify this ?

**Comment by davidh-zoosk** [comment]
@kartikjain26 I am able to see all our collections now, thank you!

I am however running into an issue where the collection is not being pushed to git even after the integration is in place. But I will reach out to CS if that continues to be an issue.

**Comment by mccannt** [comment]
Issue has been resolved. Closing this issue, if it is still a problem, feel free to reopen.

**Comment by RadwaSaleh** [comment]
I still have this issue, not all collections are displayed, only few of them

**Comment by mccannt** [comment]
@RadwaSaleh Can you give us more information on your exact issue? Steps to recreate. App information and anything else that may be related. 
Thanks
