### ISSUE TITLE
postman cann't sign in with google

### ISSUE THREAD

**Issue by codingbyai** [a85/POSTMan-Chrome-Extension#7010]
Postman native app cann't sign in with Google

App Type: Native App
Postman Version: 7.3.4
OS: macOS Mojave 10.14.5

<img width="1238" alt="屏幕快照 2019-07-28 10 16 38" src="https://user-images.githubusercontent.com/1461476/62001372-91394f00-b121-11e9-86f5-e19a8ce0da5a.png">
<img width="1238" alt="屏幕快照 2019-07-28 10 14 15" src="https://user-images.githubusercontent.com/1461476/62001371-90a0b880-b121-11e9-82c5-df225359d6b0.png">

**Comment by preethammavin** [comment]
@huangxin813 are you consistently seeing this?

**Comment by godfrzero** [comment]
@huangxin813 In addition to what @preethammavin asked, could you let us know where you're trying to sign in from? Geographic location, network type (home, office, office w/ network policies).

**Comment by codingbyai** [comment]
> @huangxin813 In addition to what @preethammavin asked, could you let us know where you're trying to sign in from? Geographic location, network type (home, office, office w/ network policies).



@godfrzero  Last time I tried several times, it always show this, but minutes ago I got a different fail message: 
<img width="1245" alt="屏幕快照 2019-08-07 21 46 52" src="https://user-images.githubusercontent.com/1461476/62628639-3e039f80-b95e-11e9-8112-1cd1f5731102.png">

location: Beijing China,  
network: home wifi (I also tried phone hotspot with 4G, got the same result).

I can sign in on my office computer.

**Comment by godfrzero** [comment]
@huangxin813 Do you happen to have any other electron apps? If so, can you try to sign in using Google within those apps?

Our working theory right now is that Google starts throwing up security blankets under certain conditions, one of them being that the auth flow is happening within a separate contained context. Since we're unable to recreate the issue, we're unable to test this directly.

**Comment by codingbyai** [comment]
> @huangxin813 Do you happen to have any other electron apps? If so, can you try to sign in using Google within those apps?
> 
> Our working theory right now is that Google starts throwing up security blankets under certain conditions, one of them being that the auth flow is happening within a separate contained context. Since we're unable to recreate the issue, we're unable to test this directly.

I logout Notion app and retry to login with Google, but failed with the same error msg. Sad...

**Comment by luerer** [comment]
> > @huangxin813 Do you happen to have any other electron apps? If so, can you try to sign in using Google within those apps?
> > Our working theory right now is that Google starts throwing up security blankets under certain conditions, one of them being that the auth flow is happening within a separate contained context. Since we're unable to recreate the issue, we're unable to test this directly.
> 
> I logout Notion app and retry to login with Google, but failed with the same error msg. Sad...

get the same problem, has it been solved yet?

**Comment by a85** [comment]
Closing as we don't see widely reported problems around Google sign in and this might be situational depending on network/environmental conditions.

**Comment by pedronveloso** [comment]
I'm seeing this issue as well. Using latest MacOS (Catalina)

**Comment by minotaurrr** [comment]
Same issue here macOS Catalina

**Comment by ejazazim** [comment]
Same issue here. After installing recent update to postman, I can no longer sign in through app. getpostman.com sign in is working though.
![image](https://user-images.githubusercontent.com/6695631/70412259-695dde80-1a65-11ea-84b9-882ec5d0687c.png)

**Comment by jesseemus** [comment]
I have the same problem

**Comment by peterbb148** [comment]
Same for me - latest Catalina on MBP16. Brand new install of Postman. Have tried switching to Safari as standard borwser and get same issue. Have tried with ExpressVPN and get same issue.

**Comment by Sunils86** [comment]
Same here on Windows

**Comment by MABottiglieri** [comment]
same here on windows
![image](https://user-images.githubusercontent.com/10948030/70423183-4d5e3b00-1a6d-11ea-8c01-5c5e8247871b.png)

**Comment by godfrzero** [comment]
Everyone, we’re looking into this. We’ll post here once we have updates.

**Comment by trennas** [comment]
Same issue for me just now, first time i've seen it. Tried multiple times, couldn't login due to unrecognized browser. However there is a workaround. After clicking sign in, click the Blocked from signing in? option at the bottom, which allows you to sign in from an external browser, in my case Chrome. That worked fine.

**Comment by godfrzero** [comment]
We’ve enabled a new auth option which will allow you to sign in via your browser. Could you try this out and let us know if it works for you?

![C970D8EB-82CD-46F2-A85B-A9BEAD7AE1C0](https://user-images.githubusercontent.com/2700229/70425240-e5244f00-1a96-11ea-84d5-e7fc166caeed.jpeg)

**Comment by Sunils86** [comment]
Works for me now.
Will there be a new release with a fix?

**Comment by trennas** [comment]
Yep as mentioned, working for me with 'Try on a web broswer'

**Comment by godfrzero** [comment]
@ArjunSingh-PM I'm thinking we can use https://github.com/postmanlabs/postman-app-support/issues/7762 as the main issue since that's more specific to the problem we're experiencing. The original issue on this ticket had similar symptoms but was unrelated.

**Comment by itanex** [comment]
Confirmed Workaround from @SoaScape. I could not log into Postman yesterday and today. I attempted to login through the web and it worked. While not a solution it does unblock me.

OS: Windows 10
Location: Seattle
VPN: No
Office Network: Yes

**Comment by sternam** [comment]
> We’ve enabled a new auth option which will allow you to sign in via your browser. Could you try this out and let us know if it works for you?
> 
> ![C970D8EB-82CD-46F2-A85B-A9BEAD7AE1C0](https://user-images.githubusercontent.com/2700229/70425240-e5244f00-1a96-11ea-84d5-e7fc166caeed.jpeg)

This workaround helped me get going and finally sign on using Ubuntu 18.04 native Postman app. Thanks!

**Comment by jarrydkeir** [comment]
> We’ve enabled a new auth option which will allow you to sign in via your browser. Could you try this out and let us know if it works for you?
> 
> ![C970D8EB-82CD-46F2-A85B-A9BEAD7AE1C0](https://user-images.githubusercontent.com/2700229/70425240-e5244f00-1a96-11ea-84d5-e7fc166caeed.jpeg)

Using this method presents a 403 error 
![image](https://user-images.githubusercontent.com/20943739/71786749-3fe3a300-3063-11ea-8a71-750b3f8c927a.png)

OS: KDE Neon

**Comment by ghost** [comment]
@jarrydkeir Are you behind some proxy in browser? This happens when your browser is behind some proxy, try disabling any extension of your related to this and see if that works for you.

**Comment by godfrzero** [comment]
We're tracking issues related to browser-based login and proxies here: https://github.com/postmanlabs/postman-app-support/issues/7839

**Comment by ArjunSingh-PM** [comment]
To resolve this issue, the "Sign in with Google" button directs the users to the web browser for signing in. 

Also, the app has an option for users to sign-in via the browser directly using the "Try on a web browser" option.

**Comment by jstutson** [comment]
Getting the exact same issue as @jarrydkeir 

I'm not sure what you mean by "try disabling any extension of your related to this" 

I haven't done anything explicitly to setup a proxy.  I'm VPN'd onto my office machine from home.  The office machine will be using whatever our default proxy is if there is one.

Is there any way to sign in with google without using the browser?

**Comment by payneWeave** [comment]
I am getting the same issue as @jarrydkeir as well. I turned off my work's vpn and have the same issue. I don't have any other proxies set up. I can sign into getpostman.com but if I try to do the oauth flow for the app I get the 403 error. I am unable to use the postman app at the moment.

**Comment by ghost** [comment]
@payneWeave @jstutson To normally login without google, you can follow these steps.

Go to identity.getpostman.com
Click trouble signing in
Enter your email
On your mail password reset link will come
Click it and set your password
Login without google using that password

This error is caused when IP address of your browser is different from that of your app. If you are using some VPN extension in your browser, that might have changed your IP causing this error, can you disable all your extension and verify you are not behind any proxy in browser and try again.

Meanwhile can you check the IP address used in app by sending GET request to https://postman-echo.com/ip using postman and on browser you can search for `What is my IP`.

**Comment by jarrydkeir** [comment]
> @jarrydkeir Are you behind some proxy in browser? This happens when your browser is behind some proxy, try disabling any extension of your related to this and see if that works for you.

Yes - I am behind a proxy, unable to turn it off though. 

> @payneWeave @jstutson To normally login without google, you can follow these steps.
> 
> Go to identity.getpostman.com
> Click trouble signing in
> Enter your email
> On your mail password reset link will come
> Click it and set your password
> Login without google using that password
> 
> This error is caused when IP address of your browser is different from that of your app. If you are using some VPN extension in your browser, that might have changed your IP causing this error, can you disable all your extension and verify you are not behind any proxy in browser and try again.
> 
> Meanwhile can you check the IP address used in app by sending GET request to https://postman-echo.com/ip using postman and on browser you can search for `What is my IP`.

I will give this a try as well.

**Comment by Hack-N-Coded** [comment]
> > @jarrydkeir Are you behind some proxy in browser? This happens when your browser is behind some proxy, try disabling any extension of your related to this and see if that works for you.
> 
> Yes - I am behind a proxy, unable to turn it off though.
> 
> > @payneWeave @jstutson To normally login without google, you can follow these steps.
> > Go to identity.getpostman.com
> > Click trouble signing in
> > Enter your email
> > On your mail password reset link will come
> > Click it and set your password
> > Login without google using that password
> > This error is caused when IP address of your browser is different from that of your app. If you are using some VPN extension in your browser, that might have changed your IP causing this error, can you disable all your extension and verify you are not behind any proxy in browser and try again.
> > Meanwhile can you check the IP address used in app by sending GET request to https://postman-echo.com/ip using postman and on browser you can search for `What is my IP`.
> 
> I will give this a try as well.

I will try too

**Comment by ghost** [comment]
@Hack-N-Coded Are you behind some proxy too, what error message did you see when you try to login?

**Comment by ouksal** [comment]
Goodbye postman. Sign in sucks

**Comment by ghost** [comment]
@ouksal, we appreciate your feedback on your sign-in experience. Could you please share more details on the issue you experienced.
