### ISSUE TITLE
Feature request - expose settings so that can be changed programmatically

### ISSUE THREAD

**Issue by sk33wiff** [a85/POSTMan-Chrome-Extension#7011]
It would be great to be able to change settings values programmatically, specially environment variables.

I have an environment variable, used as an auth token header value for all my project  requests. Currently, whenever it gets expired, I have to reset it using the GUI interface, which gets quite cumbersome overtime. It would be much faster if I could set it programmatically, specially using a bash script, as I already have one for getting a new valid token for accessing my API.

I tried accessing postman's IndexedDB with some of the free available tools for managing such DB kind, but had no success due to implementation differences.

**Comment by a85** [comment]
We have multiple ways in environment values can be changed. Scripts and the Postman API already allow you to do this. For specific use cases like Auth, we have separate efforts that are going on to solve.

**Comment by sk33wiff** [comment]
Can you please point out any examples of those scripts?

**Comment by davidespihernandez** [comment]
The Public Postman API can be used to change environment variables. See https://www.postman.com/postman/workspace/postman-public-workspace/folder/12959542-74aa54b5-9f5f-4ba5-923f-a6c805c14774?ctx=documentation for examples.
