### ISSUE TITLE
Error message for Throttling limit reached and mock usage limit reached is the same

### ISSUE THREAD

**Issue by vvs11** [a85/POSTMan-Chrome-Extension#7013]
**Describe the bug**
Error message for Throttling limit reached and mock usage limit reached is the same.
The error message should be different.
Please look at the bug tagged below for more information:

**Additional context**

https://github.com/postmanlabs/postman-app-support/issues/6511

**Comment by ratpik** [comment]
@vvs11 - We are unable to reproduce this. 

The error message for `usageLimitError` is:

`{
  "error": {
    "name": "usageLimitError",
    "message": "Usage limit reached. Contact your team admin."
  }
}`

The error message for `rateLimit` is

`{ 
  "error": {
     "name":"rateLimitError"
     "message":"Rate limit exceeded. Retry after 1564747675"
   }
}
`
