### ISSUE TITLE
Close pop-up modals (e.g. Manage Environments) by clicking outside modal

### ISSUE THREAD

**Issue by steveland83** [a85/POSTMan-Chrome-Extension#7014]
**Is your feature request related to a problem? Please describe.**
A very common task for our team is updating environment variables - especially API client Ids (regenerated every day) and secret keys (only stored as session variables). We work with a /lot/ of APIs so on any given day we probably update variables for around 5 different clients. Its a lot of clicking, copying & pasting, and it can be quite tiresome - particularly once you have updated the variables needed and have to then click the small X at the top right to close the window. This is a small but nagging annoyance when using a mouse, but it becomes irksome when using a laptop track pad. (I know that there is a keyboard shortcut, but this isnt always convenient)

**Describe the solution you'd like**
Following the fairly common pattern of closing focused modals when the user clicks anywhere outside of that modal would be a lovely user experience.

**Describe alternatives you've considered**
I'm aware that there is a keyboard shortcut (Esc in windows), but often if I'm copying & pasting values its handy to keep my left hand on ctrl c/v at that point and I'm naturally averse to pressing Escape when I have made changes that I want to keep. An additional right handed close command would be useful if the mouse click option isnt possible (Ctrl + Enter?).

**Additional context**
![image](https://user-images.githubusercontent.com/11134895/62046545-185cf480-b200-11e9-9e28-e922c12fa97d.png)

**Comment by vmoloko** [comment]
+1
"Share environment menu" doesn't respond to Esc too.

**Comment by DannyDainton** [comment]
Hey @steveland83,

This is a modal, like many others, that no longer exists in the latest version of the platform. These all open as tabs.

There are a few modals that remain for Sharing, Moving, Invites etc that respond to ESC, to close the modal.
