### ISSUE TITLE
Auto-update disable feature not working in Version 7.2.2

### ISSUE THREAD

**Issue by andutta** [a85/POSTMan-Chrome-Extension#7018]
On postman version 7.2.2, even after turning off auto-update feature, Postman application is updating the App. This is needed because we are noticing a bug in the App that presents a blank white page when OAuth2 authentication is configured for calling APIs. OAuth2 login page works perfectly with the older version of Postman. It will be great if this issue is addressed as soon as possible.

**Comment by harryi3t** [comment]
@andutta 
Thanks for reaching out.
The feature to disable the automatic updates only applies to the `major updates`

We are tracking the issue with OAuth2 flow here https://github.com/postmanlabs/postman-app-support/issues/7032
