### ISSUE TITLE
Not Able to Merge Changes - 500 Internal Server Error

### ISSUE THREAD

**Issue by KatyaRomanova14** [a85/POSTMan-Chrome-Extension#7019]
Not Able to Merge Changes - 500 Internal Server Error

**To Reproduce**
1. Create Fork
2. Merge Changes
![Error](https://user-images.githubusercontent.com/53446939/62072549-bf875f00-b1f3-11e9-9135-e989207fe762.PNG)

**Expected behavior**
Changes will be merged. 
There is Error 500.

Postman for Windows
Version 7.3.4
win32 10.0.17763 / x64

**Comment by Ghusar** [comment]
@KatyaRomanova14 Is this issue consistently reproducible?

**Comment by KatyaRomanova14** [comment]
Yes, it is 100 % reproducible.
I am not able to merge my changes.

Katya

**Comment by abhanshgiri21** [comment]
@KatyaRomanova14  Can you try viewing the collection on web and see if that works, or does that also error out? Go to your Postman App, hover on any collection, click on the small arrow and then click on `View in web` button. See image for reference.



![image](https://user-images.githubusercontent.com/20536298/62275963-a2a39380-b460-11e9-8cb1-71884bce37b8.png)

**Comment by ankit-m** [comment]
This issue was fixed. Please reopen if you are still facing this issue.
