### ISSUE TITLE
Something went wrong while fetching API *

### ISSUE THREAD

**Issue by chrisdeso** [a85/POSTMan-Chrome-Extension#7021]
**Describe the bug**
Attempting to access content associated with API schemas is throwing 500 errors – both in-app and in the web dashboard.

**To Reproduce**
1. Go to App or Web UI
2. Select a Workspace
3. Open APIs section within workspace

**Expected behavior**
The UI should return the relevant APIs

**Screenshots**
```
[requester][error]["APIDevService~getTeamForAllAPIs: apiIds are mandatory"]
[requester][warn]["Failed to get team",{"name":"Error","message":"Something went wrong while getting team for the APIs.","stack":"Error: Something went wrong while getting team for the APIs.\n    at Object.getTeamForAllAPIs (file:///Applications/Postman.app/Contents/Resources/app/js/vendor-shared.js:91302:29)\n    at APIListStore.getTeam (file:///Applications/Postman.app/Contents/Resources/app/js/vendor-shared.js:683466:85)\n    at __WEBPACK_IMPORTED_MODULE_3__services_APIDevService__.a.getAPIs.then.apis (file:///Applications/Postman.app/Contents/Resources/app/js/vendor-shared.js:683311:14)"}]
[requester][error]["APIDevService~fetchPermissions: permissionQueryObject is a mandatory property"]
[33449][1564427687816][requester][warn]["Failed to get permissions",{"name":"Error","message":"Something went wrong while fetching the API permissions.","stack":"Error: Something went wrong while fetching the API permissions.\n    at Object.fetchPermissions (file:///Applications/Postman.app/Contents/Resources/app/js/vendor-shared.js:91241:29)\n    at __WEBPACK_IMPORTED_MODULE_7__js_modules_controllers_CurrentUserController__.a.get.then.user (file:///Applications/Postman.app/Contents/Resources/app/js/vendor-shared.js:683443:89)"}]
```
```
["APIDevService~getSchema: Failed to get schema.",{"error":{"message":"SyncRequestService\\x7erequest: Undefined response returned"},"headers":{"Access-Control-Allow-Credentials":"","Access-Control-Allow-Headers":"","Access-Control-Allow-Methods":"","Access-Control-Allow-Origin":"","Access-Control-Expose-Headers":""},"status":500}]
```

**App information (please complete the following information):**
 - App Type [e.g. Chrome App, Native App]
 - Postman Version [e.g. 6.0.1]
 - OS: [e.g. macOS High Sierra 10.13.2]

**Additional context**
[Filed by Postman]

**Comment by preethammavin** [comment]
This issue has been resolved , this was caused by partial degradation of the service for few hours.

**Comment by samirotiv** [comment]
Seems to be happening again!

**Comment by ashish425** [comment]
yes it seems to be happening again

**Comment by ManeStepanyan** [comment]
Same issue here

**Comment by tomhuy** [comment]
the same issue

**Comment by nakulBageja** [comment]
Working now 👍

**Comment by mohammedsawsaq** [comment]
it's happened again now to me

**Comment by MDAsifurRahmanBS** [comment]
Happened to me now too !!

**Comment by barankaplan** [comment]
i am struggling with the same problem

**Comment by yii6** [comment]
same problem , all my collections are gone

**Comment by MKermanipoor** [comment]
It seems the issue has been resolved.

Just reopen your Postman.

**Comment by Swapnil-getpostman** [comment]
We are experiencing some downtime and our Engineering team is working quickly to get everything back up and running. I will keep you posted on any updates I get from engineering. Also, our status page has been updated to track this here: https://status.postman.com/

I appreciate your patience while we get this sorted! Thank you!
