### ISSUE TITLE
Http DELETE method not working with Postman version 7.3.4 windows 10.0.17134 / x64

### ISSUE THREAD

**Issue by jagadeeshnv** [a85/POSTMan-Chrome-Extension#7023]
**Describe the bug**
Http DELETE not working in postman app in windows

**Expected behavior**
Should work and return 204, but returning 200 OK behaving like GET

**App information (please complete the following information):**
 - Native App
 - 7.3.4
 - win32 10.0.17134 / x64

**Comment by chrisdeso** [comment]
Hey @jagadeeshnv – Generally speaking, Postman will serve up whatever response is being returned by the server.

Is there a difference in behavior when you send similar requests using cURL (or any other HTTP tool/library)? You can use in-app code generation to generate a request in cURL to give it a go.

![image](https://user-images.githubusercontent.com/4734306/62168970-8252c800-b2ec-11e9-8e94-df5df7c94ca4.png)

**Comment by jagadeeshnv** [comment]
Hi @chrisdeso 
DELETE is working as expected in previous versions of Postman(tried 5.5.4 and 7.0.4)
DELETE happening with curl cmd (from my machine)
![curl_cmd_postman_cropped](https://user-images.githubusercontent.com/39791839/62187139-0e64fe00-b386-11e9-8d06-1a2e4b061eec.jpg)

GET working as expected
![get_tmplt_postman_cropped](https://user-images.githubusercontent.com/39791839/62187137-0e64fe00-b386-11e9-9785-50f0d2c8f448.jpg)

DELETE not working in this Postman version(7.3.4)
![delete_tmpl_postman_crped](https://user-images.githubusercontent.com/39791839/62187140-0efd9480-b386-11e9-9d80-17e8c77a8c10.jpg)

**Comment by jagadeeshnv** [comment]
isssue not reproducable, sorry
