### ISSUE TITLE
Cannot download version 7.3.4 for 32-bit Linux

### ISSUE THREAD

**Issue by ghisvail** [a85/POSTMan-Chrome-Extension#7025]
See: https://dl.pstmn.io/download/version/7.3.4/linux32

**Comment by chrisdeso** [comment]
@ghisvail Would you be able to confirm whee you pulled the link from?

The following link (from our downloads page) appears to be working for me – would you give it a try?

- https://dl.pstmn.io/download/latest/linux32

**Comment by ghisvail** [comment]
https://dl.pstmn.io/download/version/7.3.4/linux64 works, so I'd expect https://dl.pstmn.io/download/version/7.3.4/linux32 to work as well.

https://dl.pstmn.io/download/latest/linux32 does work, but I need a versioned URI for the flatpak builds.

Cheers,

**Comment by numaanashraf** [comment]
@ghisvail We are discontinuing 32-bit linux from Postman 7.3.x onwards.

**Comment by ghisvail** [comment]
That's an information worth adding to the change log then.

Le jeu. 1 août 2019 à 08:09, Numaan Ashraf <notifications@github.com> a
écrit :

**Comment by numaanashraf** [comment]
Completely agree with you @ghisvail. We are adding that now.
