### ISSUE TITLE
Adding Chrome extension support for the desktop app

### ISSUE THREAD

**Issue by TechWithHazem** [a85/POSTMan-Chrome-Extension#7031]
I'm always frustrated when I need to copy requests from chrome devtools to postman desktop app - too much work that can be automated.

While using the chrome app and then exporting the requests works, it is a pain still. So please add support for the desktop app in the chrome extension

Thank you Postman team :)

**Comment by a85** [comment]
You can use the Interceptor extension now to transfer requests.

**Comment by a85** [comment]
https://learning.getpostman.com/docs/postman/sending-api-requests/interceptor-extension/
