### ISSUE TITLE
Postman with a file and json object in same request as multipart

### ISSUE THREAD

**Issue by istef94** [a85/POSTMan-Chrome-Extension#7033]
Dear team,

How can i send a multipart postman request containing a file and a json object like this?

Content-Type: multipart/form-data; boundary="----=_Part_2dfwfwerwe"
Content-Transfer-Encoding: binary
Content-Disposition: form-data; name="metadata"
Authorization: Bearer XXXXXXXXXXXXXXXXXXXXX
Transfer-Encoding: chunked

------=_Part_2dfwfwerwe
Content-Type: multipart/form-data
Content-Transfer-Encoding: 8bit

{
"documentko": {
  "userId": "XXXXXXXX",
  "imageko": {
   "fileFormat": "PDF"
  }
}
}

------=_Part_2dfwfwerwe
Content-Type: application/octet-stream; name=
Content-Transfer-Encoding: binary
Content-Disposition: form-data; name="document"; filename=""

%PDF-1.3
%âãÏÓ
14 0 obj
<</Linearized 1/L 11984/O 16/E 5003/N 2/T 11672/H [ 446 157]>>
endobj

20 0 obj
<</DecodeParms<</Columns 3/Predictor 12>>/Filter/FlateDecode/ID[<HNLIHJBKILN879y9uy98uiuHHBHJB78yu><(HNLIHJBKILN879y9uy98uiuHHBHJB78yu>]/Index[14 9]/Info 13 0 R/Length 44/Prev 11673/Root 15 0 R/Size 23/Type/XRef/W[1 2 0]>>stream
hÞbbd`b`òfb`ðcb`l[1]Ò?@z& ÃŸx&F†yLÿ×

When I trying I receive a message like this:
   "RESTFaultCode" : "rest:Server" ,
   "Reason" : "WebService Processing Exception" ,
   "detail" : "Invalid request"

Thanks you!

**Comment by saswatds** [comment]
Hi @istef94 I would suggest you ask this question on our vibrant community forum https://community.getpostman.com 

This issues board is primarily of tracking bugs and features requests. Will be closing this issue now. Feel free to reopen this issue if you find a bug with form-data in the app.

Thanks
