### ISSUE TITLE
Unable to import API Network Collection

### ISSUE THREAD

**Issue by bhargavkaranam** [a85/POSTMan-Chrome-Extension#7034]
**Describe the bug**
Trying to import Imgur collection from the API Network throws a 403

**To Reproduce**
1. Click on New -> API Network
2. Click on Imgur 
3. Click on Run in Postman

**Expected behavior**
If the collection is visible publicly, this should never happen. If there's a permission issue, the collection should never show up.

**Screenshots**
<img width="1130" alt="Screenshot 2019-08-01 at 12 55 08 PM" src="https://user-images.githubusercontent.com/8963298/62273665-b698c680-b45b-11e9-92be-812f6d1ce260.png">
![apinetwork](https://user-images.githubusercontent.com/8963298/62273689-c44e4c00-b45b-11e9-818a-851cc47b0141.gif)

**App information (please complete the following information):**
 - Postman 7.3.5 on Mac

**Comment by preethammavin** [comment]
The issue has been fixed
