### ISSUE TITLE
Scrolling in Single-Pane view is Horrible

### ISSUE THREAD

**Issue by Montago** [a85/POSTMan-Chrome-Extension#7035]
All you need to do to fix this issue (which has been reported SEVERAL TIMES) is to expand the reponse-view to the same height as the content. That way you would only have ONE scrollbar !!

Alternatively set the height of the "response editor/viewer" to the available height minus all the header stuff ... if <0 then hide ... DONE...

the current Scrollview in Scrollview is HORRIBLE !

Especially because the response-view bottom is beyond the content height AT ALL TIMES -- why the heck don't you simply make sure that its IN VIEW ? .. 

and no - Two-Pane view is NOT A SOLUTION.

**Comment by Camios** [comment]
+1

**Comment by arlemi** [comment]
Hey @Montago 

We've pushed layout updates on [Postman Canary](https://www.postman.com/downloads/canary) that should make it easier to navigate between different sections of the app builder.

You can read more about it (and provide feedback 🙏) on our community forum: https://community.postman.com/t/new-layout-in-postman-canary/13450

**Comment by Montago** [comment]
> Hey @Montago
> 
> We've pushed layout updates on [Postman Canary](https://www.postman.com/downloads/canary) that should make it easier to navigate between different sections of the app builder.
> 
> You can read more about it (and provide feedback 🙏) on our community forum: https://community.postman.com/t/new-layout-in-postman-canary/13450

THANKS - I LOVE IT !
