### ISSUE TITLE
v7.3.5 error while launching - Library not loaded: @rpath/Electron Framework.framework/Electron Framework

### ISSUE THREAD

**Issue by MarcelSchober** [a85/POSTMan-Chrome-Extension#7039]
Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: @rpath/Electron Framework.framework/Electron Framework
  Referenced from: /Applications/Postman.app/Contents/MacOS/Postman
  Reason: no suitable image found.  Did find:
	/Applications/Postman.app/Contents/MacOS/../Frameworks/Electron Framework.framework/Electron Framework: file too short
	/Applications/Postman.app/Contents/MacOS/../Frameworks/Electron Framework.framework/Electron Framework: stat() failed with errno=1

Binary Images:
       0x10698f000 -        0x10698fff3 +com.postmanlabs.mac (7.3.5 - 7.3.5) <4FAD2A7B-B418-358C-949F-1104B0620579> /Applications/Postman.app/Contents/MacOS/Postman
       0x111ec4000 -        0x111f2e6ef  dyld (655.1.1) <CE635DB2-D47E-3C05-A0A3-6BD982E7E750> /usr/lib/dyld

Model: MacBookPro15,2, BootROM 220.260.170.0.0 (iBridge: 16.16.5125.0.0,0), 4 processors, Intel Core i7, 2,7 GHz, 16 GB, SMC 

![image](https://user-images.githubusercontent.com/34745733/62290774-696c2300-b462-11e9-986a-57255d71bbeb.png)

**Comment by numaanashraf** [comment]
@MarcelSchober Are you facing similar issue with our canary apps? - https://www.getpostman.com/downloads/canary

**Comment by MarcelSchober** [comment]
> @MarcelSchober Are you facing similar issue with our canary apps? - https://www.getpostman.com/downloads/canary

Yes, absolutely the same problem with Canary

**Comment by numaanashraf** [comment]
@MarcelSchober Thanks. Could you run the following command via the terminal and send us the output?
```
ll /Applications/Postman.app/Contents/Frameworks/Electron\ Framework.framework/
```

please change `/Applications/Postman.app` to where the app is on your system.

**Comment by numaanashraf** [comment]
@MarcelSchober Also please share how you had unarchived the zip that was downloaded from Postman. If you are using any third party extractors like 'The Unarchiver', could you try extracting via the built-in 'Archive Utility' instead and let us know if the issues persists?

**Comment by MarcelSchober** [comment]
Using the build-in 'Archive Utility' solved the problem! Thanks for your hint and your fast response!

I used "iZip" before.

**Comment by numaanashraf** [comment]
Glad to hear that @MarcelSchober :)

**Comment by ghost** [comment]
You should put a note on your Mac version download page - "Unzip with Archive Utility".  I nearly abandoned trying Postman until I found this page because i-zip is my default utility for opening zip files and it failed when Archive Utility worked...
