### ISSUE TITLE
Get New Access Token intermittently responds HTTP status 400

### ISSUE THREAD

**Issue by mcandre** [a85/POSTMan-Chrome-Extension#7042]
**Describe the bug**

Over the past few months, I have been integrating and testing Okta OpenID (OIDC) with my web application, using Postman to automate test HTTP calls. This has largely worked so far, and my web app continues to login with OpenID in Google Chrome.

However, when I try to obtain access tokens with Postman, that no longer works. I started getting intermittent HTTP status 400's last week, complaining about invalid / expired authorization codes. Strange that this only happens with Postman, not with Chrome. Any idea what is going on?

Test OpenID servers are available at https://developer.okta.com

**To Reproduce**

1. Use the Get New Access Token form.

**Expected behavior**

A JWT is returned.

**App information (please complete the following information):**

 - Postman Version 7.3.4
 - OS: macOS 10.12

**Comment by harryi3t** [comment]
@mcandre 
Thanks for reaching out.
We are currently tracking this Oauth2 issue here https://github.com/postmanlabs/postman-app-support/issues/7032

Please try out the custom build we have shared as mentioned here https://github.com/postmanlabs/postman-app-support/issues/7032#issuecomment-517239942
