### ISSUE TITLE
Unable to add APIMatic-Github integration

### ISSUE THREAD

**Issue by esonti** [a85/POSTMan-Chrome-Extension#7043]
**Describe the bug**
Tried to add a simple APIMatic integrations to push the collection from postman to github in swagger 2.0 yaml format. 

**To Reproduce**
1. Go to "Integrations" --> APIMatic --> Github
2. Enter all the necessary details. (Screenshot attached)
3. Click on "Add Integration"
4. Observe the error message "Something went wrong
An error occurred while creating the integration. Try again after some time."

**Expected behavior**
Integration to succeed and yaml specification to be pushed to the github repository.

**Screenshots**
![image](https://user-images.githubusercontent.com/341724/62322573-59107400-b473-11e9-965c-e78bbcad4b04.png)

**App information (please complete the following information):**
 - Integrations in the postman web page.

**Additional context**

**Comment by PetraRouvoet** [comment]
Same problem. Is there any other way to do this else?

**Comment by mccannt** [comment]
This issue should be resolved. Please reach out and reopen if this is still an issue.

**Comment by RadwaSaleh** [comment]
This issue still exists with latest version Postman v7.31.1

**Comment by mccannt** [comment]
@RadwaSaleh I am not able to replicate this issue. Can you give us a bit more information on how you are reproducing this issue?

**Comment by PetraRouvoet** [comment]
Beste postmanlabs/postman-app-support,

Bedankt voor je e-mail. We nemen je vraag zo snel mogelijk in behandeling,
maar vragen in verband met grote drukte daarbij wel om enig geduld. We
willen daarom vriendelijk vragen om even te wachten voordat je telefonisch
contact opneemt.

*Voor vragen over een lopende of nieuwe klusaanvraag raden we je aan om
eerst onze veelgestelde vragen te raadplegen
<https://zoofy.nl/veelgestelde-vragen/> en ons daarna eventueel te
bellen: 085 047 1277* (op werkdagen tussen 08:00 en 18:00 uur en in het
weekend tussen 09:00 en 17:00 uur.

Wij streven er naar om je e-mail binnen drie werkdagen te beantwoorden.


Met vriendelijke groet,

Team Zoofy
