### ISSUE TITLE
could you please provide the source code of postman app chrome version?

### ISSUE THREAD

**Issue by EstherLacan** [a85/POSTMan-Chrome-Extension#7045]
hello :
   I am learning postman Technology [(postman chrome app)](https://chrome.google.com/webstore/detail/postman/fhbjgbiflinjbdggehcddcbncdddomop) ,but i just debug the source that has been compiled by webpack.

could you provide the source code of this project, thank you very much.
:mailbox:

**Comment by numaanashraf** [comment]
Thanks for reaching out @EstherLacan. Postman's chrome & desktop apps are closed-source as of date and I'm afraid we cannot share this at the moment. But the team would be happy to answer any questions on how the apps are built and the technology behind it. I recommend interacting with the team via Postman's community forum - https://community.getpostman.com/

**Comment by EstherLacan** [comment]
@numaanashraf ,I have a technology question about the postman :
How the postman app complete the login authentication and send the http Request  via get the cookie information from the web page，can you please point out the code in the code file( requester.js).
