### ISSUE TITLE
Request data export fails from dashboard - /api/export <unavailable>

### ISSUE THREAD

**Issue by cyrielle-hada** [a85/POSTMan-Chrome-Extension#7046]
**Describe the bug**
When trying to download archived collections from https://app.postman.co/me/export, the requested export seems frozen. The file can't be downloaded.

JavaScript console says: `Unhandled promise rejection <unavailable>`
 
**To Reproduce**
1. Go to https://app.postman.co/me/export
2. Click on Request data export
3. Click Submit
4. See status says zipped 4 days after the request data export - the file has never been available.
5. See Something went wrong error "A previous export is already in progress"

![screenshot2](https://user-images.githubusercontent.com/47351631/62363208-bf9a9e00-b516-11e9-8d10-5f29079257f9.png)

**Expected behavior**
Successful Request data export and see the status: Download. 
![Screen Shot 2019-08-02 at 11 12 28](https://user-images.githubusercontent.com/47351631/62363162-9843d100-b516-11e9-948e-cdaa78216721.png)

**App information (please complete the following information):**
 - Postman Version 7.3.5
 - OS: Windows

**Additional context**
Filed by Postman on the behalf of the user.

**Comment by cyrielle-hada** [comment]
Workaround for this issue: realize [a data dump](https://learning.getpostman.com/docs/postman/collections/data_formats/#data-dumps).

**Comment by cyrielle-hada** [comment]
@himanshu226 Another occurrence of this has been reported via Support. Would it be possible to re-prioritize this? Or is there a way we can access the data export request that has the .zipped status?

**Comment by saswatds** [comment]
Hi. This issue has now been fixed.

**Comment by leson238** [comment]
Hi, I get the same issue - now it's freeze on zipping forever.

**Comment by extragornax** [comment]
> zipping

Same issue

**Comment by gomesdigital** [comment]
I have this problem too! it's been a couple weeks since I tried to export my collection and its status is still stuck on zipping...

For anyone else, @cyrielle-hada 's mention above did what I needed.
