### ISSUE TITLE
Deleted Collections are not being deleted

### ISSUE THREAD

**Issue by rizzorc** [a85/POSTMan-Chrome-Extension#7048]
**Bug Description**
There are several Collections that I deleted from postman (and emptied from Trash) which still appear in my account. As illustrated in screen shots (Below)

When I click on the deleted collection from postman's site, I get an error- 

> We can't seem to find this collection in any workspace
> This collection might have been removed by another user in your team
> 

Here is one such deleted collection
- [Deleted Collection Named "Analytics"](https://sdt-manh.postman.co/workspaces/switch?model=collection&id=2541502-6b18a7e2-ee9b-496a-86df-18a02483d0df)

Using the Postman API, These collections still appear in my Collections List and I can still download them.  

**How to Reproduce?**
Not sure how "recreatable" this is, but I had imported these collections from a file and <months later> deleted them

**Expected behavior**
These collections should be gone.

**Screenshots**
If applicable, add screenshots to help explain your problem. Please make sure the screenshot does not contain any sensitive information such as API keys or access tokens. 
![Postman Collections that have been Deleted](https://user-images.githubusercontent.com/40202787/62366319-88b39080-b4f4-11e9-82e0-133bafc26e5f.png)
![Sample Collection that was deleted](https://user-images.githubusercontent.com/40202787/62366370-a84ab900-b4f4-11e9-9ae2-a6415928d6e4.png)

**App information (please complete the following information):**
 - App Type : _Native App_
 - Postman Version: _6.7.4_
 - OS: _Windows 10_

**Additional context**
I have made several practice runs with using private / team workspaces to pilot their use.  I'm not sure how many of the deleted collections may have been shared, but I know I've hit the sharing limit a few times with these collections and I've had to re-download them and import them back.

**Comment by preethammavin** [comment]
@rizzorc can you confirm the steps you took to delete the collections ? 
Did you delete the collection or do remove from workspace? If you do remove from workspace it would remove from that workspace and not delete the collection. The collection would still appear in the collection list. Try deleting by selecting delete and check again.

**Comment by rizzorc** [comment]
Hello @preethammavin I remember specifically deleting these collections because there were quite a few and I had to do it one by one!

**Comment by preethammavin** [comment]
@rizzorc can you write to us at help@getpostman.com with reference to the github issue so that we can take a closer look. 

Would be great if you can try to delete one of those collections again,
Steps 
Share one of the collection from here to a workspace 
click on ellipses and  select delete collection 

If you can share the app logs if you are using Postman (view->developer-> view logs) or Web console logs incase you are trying from Postman Dashboard. 
Do share this on help@getpostman.com.

**Comment by rizzorc** [comment]
@preethammavin I have sent the debug information via email as requested.  

Please note that the steps that you provided appears to have deleted the collection (I deleted 2 collections with the name "AssignCashDrawer."  

I will hold off on deleting any more of these collections so that further troubleshooting / root cause analysis may be performed.

**Comment by preethammavin** [comment]
@rizzorc by any chance did you delete the workspace? Deleting a workspace does not delete collections and environments as they can exist across multiple workspaces and we do put a hard 1:1 mapping on them.

Workspace delete would delete the monitors, mocks and integrations in them but not Collection and environments. To delete the collection they will have to deleted manually.

**Comment by rizzorc** [comment]
@preethammavin - I had several private and shared workspaces that I had been moving collections between in order to test the various features of postman.  I'm sorry but I don't have an exact sequence of events for the activity before I deleted the collections.  I am pretty sure that I deleted all of these collections from "My Workspace" in the postman application and then emptied them from the trash.  

Maybe they were also "Shared" to a workspace that I had deleted???  Is there anyway to tell what workspace these collections last pointed to?

**Comment by preethammavin** [comment]
@rizzorc that is not something I can see, but on inspection I see that the collections were not purely in My Workspace, as we cannot delete the My Workspace. The case could be that these collections were present in a Team / Other Workspace and when the workspace was deleted, they were removed from the workspace and were visible in the profile.

**Comment by preethammavin** [comment]
@rizzorc thanks for your help in looking into this, you can delete the collections by the steps I mentioned above. Let me know if that still has any unexpected behaviour, closing the issue for now.
