### ISSUE TITLE
(Re)Drawing issue

### ISSUE THREAD

**Issue by stevejalim** [a85/POSTMan-Chrome-Extension#705]
TLDR: after a while, Postman seems to stop rendering the UI properly

Hard to pin this down, but it seems that when the packaged Postman has been running for while, it is less and less likely to properly redraw the interface, usually requiring a manual window resize to show elements. This may or may not be related to the fact it's running in the ultra-crazy max Retina res on my Mac.

Here endeth the world's most useless bug report.

**Comment by a85** [comment]
Sorry for the inconvenience caused people. We are as frustrated as everyone else. 

Posted updates on Chromium's bug tracker: 
https://code.google.com/p/chromium/issues/detail?id=412414
https://code.google.com/p/chromium/issues/detail?id=412299

We'll try to change the DOM structure and see if that helps in going around this problem.

**Comment by abhijitkane** [comment]
We've made a few CSS changes on the staging version - https://chrome.google.com/webstore/detail/postman-rest-client-packa/mgicbpdmnpnfckafakeoiomkjcplfcld/

It appears to have reduced the problem to a great extent. @Quagh @Aidenir @pbellchambers can you check it out and see if the problem has improved?

**Comment by pbellchambers** [comment]
Still happening for me, frequency seems about the same (it is intermittent however, but was always that way).

Chrome:
> Version 39.0.2171.95 m

POSTMan:
>Version 1.0.5 (packaged)
>OS: win
>Architecture: x86-32
>Native client architecture: x86-64

![untitled](https://cloud.githubusercontent.com/assets/6773269/5755553/c46d9338-9c9d-11e4-9644-e88a2f7ccdfd.png)

**Comment by a85** [comment]
@pbellchambers Is that after using Postman for some time or almost instantly after sending a request?

**Comment by pbellchambers** [comment]
After sending a request and then switching to another request. I can reproduce it right after opening postman.

**Comment by a85** [comment]
Weird. I don't see it that often on my Retina machine even at the highest resolution. We suspect it might be something to do with the scrollbar code that we are using. Will push another version on the staging app soon.

**Comment by Quagh** [comment]
I can also reproduce when sending a request and switching views.

Just had a weird thing though. So I'm on a MacBook Pro retina and tried reproducing the bug. The bug occurred, and the view was glitched as expected. Suddenly my graphics card switched from the more powerful nVidia one, to the integrated Intel graphics card… and the view reset itself, showing everything again. Maybe something to look into, check if it's related?

**Comment by shamasis** [comment]
We made some more changes to combat this issue. It appears to us as something to do with the overflow characteristics of scrollable elements.

:shipit: The beta is now available:
> https://chrome.google.com/webstore/detail/postman-rest-client-packa/mgicbpdmnpnfckafakeoiomkjcplfcld (version: 1.0.6.3)

Your inputs pushed us in a direction to force better buffered 3D acceleration on erring elements. Following that, we are not seeing the issue anymore (at least in the last 8 hours.)

Thanks to everybody for helping. @Quagh @Aidenir @pbellchambers and others, could you share your experience with this release? We will keep on trying until we see this through.

**Comment by Zajn** [comment]
I had been encountering this issue as well, but so far using Postman 1.0.6.3, I have not seen it occur yet.

OS: OSX 10.10
Postman: 1.0.6.3
Chromium: 38.0.2125.122 (290379)

**Comment by rtuin** [comment]
Thanks for your efforts, i will give it a try and let you know!

**Comment by skuppa** [comment]
It works great so far and I was not able reproduce the issue.  Great work.

-Sridharan

**Comment by Quagh** [comment]
Seems to work :)

**Comment by rtuin** [comment]
Amazing, work. Been working with the beta for a over an hour without having the redraw problem! :+1:

**Comment by fherrerac** [comment]
This beta seems to fix the issue, but doesn't allow to sign in and thus test fully using jetpacks. When do you expect to release it so can be tested signing in w/jetpacks ?

**Comment by a85** [comment]
Thank you everyone for the confirmation. We'll be pushing an update on the production channel today.

**Comment by mikemwalsh** [comment]
YES!  I finally got off my butt to see if this was a common issue, read the entire issue log and made it to the end saying a fix is heading to production!  Thanks - cant wait to update to it!

**Comment by shamasis** [comment]
We are truly happy that we could finally get to the bottom this issue. I'm closing this issue with a postmortem of it on our blog - [Chrome Repaint Issue](http://blog.getpostman.com/index.php/2015/01/23/ui-repaint-issue-on-chrome/).

> :shipit: The changes have been merged with our [production app](https://chrome.google.com/webstore/detail/postman-rest-client-packa/fhbjgbiflinjbdggehcddcbncdddomop) version `1.0.6`.

Thanks to all for helping. In the unlikely event that you are still facing this issue, let us know on this thread.
