### ISSUE TITLE
Billing dashboard: invoice shows due date in 1970

### ISSUE THREAD

**Issue by JP-from-Postman** [a85/POSTMan-Chrome-Extension#7050]
**Describe the bug**
Team's account is disabled for lack of payment, and billing dashboard shows due date as:

<img width="455" alt="Screen Shot 2019-08-02 at 11 05 47 AM" src="https://user-images.githubusercontent.com/43283131/62389857-c70d7780-b515-11e9-954b-d7cf5162e9bd.png">

**To Reproduce**
(For this specific team)
1. Go to: https://go.postman.co/billing/overview
2. See due date as 18 Jan, 1970

**Expected behavior**
Invoice shows valid due date

**App information (please complete the following information):**
 - App Type: web dashboard
 - Postman Version: N/A
 - OS: N/A

**Additional context**
See internal notes

**Comment by debjeetsarkar** [comment]
This should be fixed now.
