### ISSUE TITLE
Unable to access shared environments in public documentation

### ISSUE THREAD

**Issue by preethammavin** [a85/POSTMan-Chrome-Extension#7054]
**Describe the bug**
I am trying to select a shared environment on the public documenter, and the page renders to give a 403, and I have access to the environment and can view in my workspace 

**To Reproduce**
1. Go to https://docs.api.getpostman.com
2. Click on environments list
3. select a shared environment 

**Expected behavior**
should try to resolve with the environment and 4xx out

**Comment by Cazaimi** [comment]
@preethammavin , this issue has been solved. Tested manually too, and I'm able to access shared environments on Public Documentation. 

@Raja-Simha , please mark this as closed.
