### ISSUE TITLE
Postman is not starting

### ISSUE THREAD

**Issue by Acelator** [a85/POSTMan-Chrome-Extension#7055]
I installed postman, and when I try to open it, nothing happens. I tried opening it from terminal and I get 
```Could not get the lock, quitting```
I reinstall the program twice but it still doesn't work. I deleted all the related data from my hard disk, but it don't work. A few month ago it works, but I didn't use Postman for four months and today I were trying to use it to test and API and I discovered that Postman doesn't want to start

 - App Type [Native App]
 - Postman Version [7.3.5]
 - OS: [Ubuntu 19.04]

**Comment by harryi3t** [comment]
@Acelator The error `Could not get the lock, quitting` happens when there is already an instance of Postman running.
Can you try to kill all instances of Postman first and try restarting the Postman app?
To kill all instances either you can use `killall Postman` or just reboot the system.

**Comment by Acelator** [comment]
Yes, I noticed that Postman start when I turn on my Computer, but I don't know why it doesn't appeared. I remove Postman from the Apps that are loaded when I boot my system and It works good now. Thanks

**Comment by jebrage** [comment]
If you don't want to reboot, running `pkill -fl Postman` and then trying to start also works.

**Comment by MarkJeronimus** [comment]
I'm hit by the same problem. It appeared after I saw an in-app upgrade notification, upgraded, restarting and killed it because the splash screen with the planetary spinner was stuck forever.

```
mark@mark:~/Progs/Postman$ killall -9 Postman
Postman: no process found
mark@mark:~/Progs/Postman$ ./Postman 
Could not get the lock, quitting
mark@mark:~/Progs/Postman$ pkill -fl Postman 
pkill: invalid option -- 'l'

```

**Comment by MarkJeronimus** [comment]
inb4 Please give us the log?

```
2019/10/04 11:13:12:423 Postman-1570175593433 Swapping the old app with new one
2019/10/04 11:13:12:493 Postman-1570175593433 Swapping done
2019/10/04 11:13:12:517 Postman-1570175593433 Parent process is alive, killing it now
2019/10/04 11:13:12:520 Postman-1570175593433 Launching app with command /home/mark/Progs/Postman/app/Postman --updated --eID=Postman-1570175593433
```

**Comment by MarkJeronimus** [comment]
I'm hit by the same problem. It appeared after I saw an in-app upgrade notification, upgraded, restarting and killed it because the splash screen with the planetary spinner was stuck forever.

```
mark@mark:~/Progs/Postman$ killall -9 Postman
Postman: no process found
mark@mark:~/Progs/Postman$ ./Postman 
Could not get the lock, quitting
mark@mark:~/Progs/Postman$ pkill -fl Postman 
pkill: invalid option -- 'l'

``` 
Contents of log file:

```
2019/10/04 11:13:12:423 Postman-1570175593433 Swapping the old app with new one
2019/10/04 11:13:12:493 Postman-1570175593433 Swapping done
2019/10/04 11:13:12:517 Postman-1570175593433 Parent process is alive, killing it now
2019/10/04 11:13:12:520 Postman-1570175593433 Launching app with command /home/mark/Progs/Postman/app/Postman --updated --eID=Postman-1570175593433
```

[Edit] Fixed with deleting ~/.config/Postman. This is a **bug** since this should not get corrupt.

**Comment by sudeeshr** [comment]
`pkill -fi Postman`
This works for me

**Comment by stloc** [comment]
`killall _Postman`

**Comment by aslamanver** [comment]
`pkill -9 Postman`

It works

**Comment by anandSug** [comment]
> `pkill -fi Postman`
> This works for me

the `i` threw an error for me

`pkill -f Postman`
This worked.
UBUNTU 16.04

**Comment by jeygeethan** [comment]
Asking a dev to reboot their system is absurd. Just use 

`pkill -f Postman`

**Comment by qburst-hasna** [comment]
I got following error.

`(electron) 'getName function' is deprecated and will be removed. Please use 'name property' instead.
Could not get the lock, quitting
`
Solution:

Delete file in ~/.config/Postman

**Comment by absognety** [comment]
> > `pkill -fi Postman`
> > This works for me
> 
> the `i` threw an error for me
> 
> `pkill -f Postman`
> This worked.
> UBUNTU 16.04

worked for Ubuntu 20.04 also Thanks!!!!

**Comment by annapurnaTechmojo** [comment]
pkill -9 Postman - worked for me.  thanks
ubuntu 18version

**Comment by madipietro** [comment]
Best way to solve this `ps -ef | grep -i postman | awk {'print $2'} | xargs kill -9; postman`, tested on ArchLinux with Postman 8.10.0.

**Comment by mmassenzio** [comment]
```└─( rm -rf ~/.config/Postman```
did it for me
not great though - there should be an option to just remove the lock (the process was clearly NOT running)

curious as to why this was closed - this is a bug in Postman, it should (a) not fail "silently" (unless you run it from the command line, you'll never figure out it's locks left behind) and (b) should allow the user to do something about it (trivially, kill the running instance if any is present, then remove the left-behind locks, if any).

The way this works now, is extremely clumsy.

**Comment by rajpra808** [comment]
Another solution 
remove `SingletonLock` and `SingletonLockCache` file from `~/.config/Postman`

```
rm ~/.config/Postman/SingletonCookie
rm ~/.config/Postman/SingletonLock
```
