### ISSUE TITLE
Postman download keeps failing

### ISSUE THREAD

**Issue by TomGranot** [a85/POSTMan-Chrome-Extension#7056]
**Describe the bug**
The Linux 64-bit version of Postman keeps failing to download - even when testing with different connections, both wired and wireless.

**To Reproduce**
1. Go to https://www.getpostman.com/downloads/
2. Click on 'Linux 64-bit' ([link](https://dl.pstmn.io/download/latest/linux64))

**Expected behavior**
Download will not fail.

**App information (please complete the following information):**
 - Kubuntu 19.04, running Chrome Version 75.0.3770.142 (Official Build) (64-bit)

**Additional context**
Located in Israel.

**Comment by harryi3t** [comment]
Was able to reproduce the issue (using a VPN connection of Israel)
Getting `dns_probe_finished_nxdomain` error

![image](https://user-images.githubusercontent.com/5207331/62427283-62693d00-b70e-11e9-9ad1-a6aa86ddb4aa.png)

cc @kunagpal

**Comment by mccannt** [comment]
This does not appear to be an issue any longer. 
I was able to download the `Linux 64-bit` version when VPN'ed into Isreal with no issues.

If this happens to still be an issue, please reopen and we can investigate.

**Comment by TomGranot** [comment]
@mccannt Thanks!
