### ISSUE TITLE
CNAME field is empty when instructing user to setup a custom domain

### ISSUE THREAD

**Issue by xk0der** [a85/POSTMan-Chrome-Extension#7058]
**Describe the bug**
When a user is adding the custom domain the CNAME field value should be populated with 

**To Reproduce**
Steps to reproduce the behaviour:
Follow steps listed here: https://learning.getpostman.com/docs/postman/api_documentation/adding_and_verifying_custom_domains/
For step "[Get verification tokens](https://learning.getpostman.com/docs/postman/api_documentation/adding_and_verifying_custom_domains/#get-verification-tokens)" - the CNAME field should list `phs.getpostman.com` as the value

**Expected behavior**
correct CNAME value should be listed instead for the field being blank.

**Comment by chrisdeso** [comment]
Adding a screenshot here:

![image](https://user-images.githubusercontent.com/4734306/62655335-5c9a7400-b927-11e9-8fff-e8eb6679ab1c.png)

**Comment by Raja-Simha** [comment]
The issue has been fixed.
