### ISSUE TITLE
Clean up previous updates

### ISSUE THREAD

**Issue by robvdl** [a85/POSTMan-Chrome-Extension#7060]
When Postman autoupdates it fails to do any house cleaning of the older updates, over time this just builds up in the app folder and becomes huge.

My Postman app folder is now over 5gb in size, this is crazy. Can we please do something about this, auto clean updates that are a few versions old perhaps.

```
Postman-1543879734129
Postman-1543879734129.tar.gz
Postman-1548730887872
Postman-1548730887872.tar.gz
Postman-1552943192302
Postman-1552943192302.tar.gz
Postman-1552963724716
Postman-1552963724716.tar.gz
Postman-1553099529309
Postman-1553099529309.tar.gz
Postman-1553114481905
Postman-1553114481905.tar.gz
Postman-1554161191306
Postman-1554161191306.tar.gz
Postman-1562629582017
Postman-1562629582017.tar.gz
Postman-1562668520061
Postman-1562668520061.tar.gz
Postman-1562799677370
Postman-1562799677370.tar.gz
Postman-1562827304907
Postman-1562827304907.tar.gz
Postman-1562899797404
Postman-1562899797404.tar.gz
Postman-1563770028906
Postman-1563770028906.tar.gz
Postman-1563792174567
Postman-1563792174567.tar.gz
Postman-1564051319714
Postman-1564051319714.tar.gz
Postman-1564370335961
Postman-1564370335961.tar.gz
Postman-1564462813329
Postman-1564462813329.tar.gz
Postman-1564552622327
Postman-1564552622327.tar.gz                                                                                                                                                                      
Postman-1564554268305                                                                                                                                                                             
Postman-1564554268305.tar.gz                                                                                                                                                                      
Postman-1564961501193                                                                                                                                                                             
Postman-1564961501193.tar.gz  
```

I'm not entirely sure if this is related to updates because I deleted all these files and started Postman several times. Each time it starts it creates a new folder and a tar file, whether it updates or not.

**Comment by preethammavin** [comment]
@robvdl can you let us know the OS that you are using?

**Comment by robvdl** [comment]
Ubuntu 18.04 LTS

**Comment by harryi3t** [comment]
@robvdl Are you on the latest version of Postman (v7.3.x)?
Also, it would really help if you could share the logs with us at help@getpostman.com. Please put the subject `Logs for GitHub 7060`.
You can find the logs at `View -> Developer -> View logs in File Manager`

**Comment by robvdl** [comment]
I'm updating it now, I'm not sure what version it was on before because help->about menu entry is missing. It's kinda where people tend to publish version in desktop apps :) Might be a nice addition at some point.

I thought it updated itself, as I thought that is what the folders were coming from. Apparently that isn't the case.

Anyway, I'm not 7.3.5 now. Issue has gone away, thanks.
