### ISSUE TITLE
Wrong response pretty

### ISSUE THREAD

**Issue by abcdefz** [a85/POSTMan-Chrome-Extension#7062]
**Describe the bug**
response.raw  is 
{"url": "https:\/\/xxx.com\/icons\/xxx.jpeg"}

then response.pretty is
"https:\/\/xxx.com\/icons\/xxx.jpeg"

but I expect 
"https://xxx.com/icons/xxx.jpeg"

when I use python shell
it's what i expect
when I use postman Chrome APP
it's what I expect

**App information (please complete the following information):**
 - App Type [Native App]
 - Postman Version [7.3.5]
 - OS: [macOS High Sierra 10.14.4]

**Additional context**
Native App
![image](https://user-images.githubusercontent.com/11614358/62438648-f53fc100-b77a-11e9-9771-eee7afc6eeac.png)

Chrome App
![image](https://user-images.githubusercontent.com/11614358/62438674-10aacc00-b77b-11e9-94ed-97aaca837375.png)

**Comment by saswatds** [comment]
Hi @abcdefz It seems that your issue is related to https://github.com/postmanlabs/postman-app-support/issues/7049 

Can you confirm if your server is sending the URL will escape character?

**Comment by abcdefz** [comment]
> Hi @abcdefz It seems that your issue is related to #7049
> 
> Can you confirm if your server is sending the URL will escape character?

server return 'http:\/\/xxx.com\/xxx'
it should return 'http://xxx.com/xxx'   right?

**Comment by saswatds** [comment]
@abcdefz You are right, in the previous versions of the app we were not able to detect the existence of escape characters.
But in the new version ie. 7.3.x and later, we have stopped parsing the response hence we are able to show exactly what the server responds. 

Can we close this issue?

**Comment by saswatds** [comment]
Hey @abcdefz after an internal retrospection we have added back this feature in the pretty view. It now ignores the escape characters as you have previously experienced. Check it out on the lastest app version 7.3.6. 
Closing this issue now. Feel free to reopen if it does not work for you.
