### ISSUE TITLE
Cache-control header added twice to generated request

### ISSUE THREAD

**Issue by BobClaerhout** [a85/POSTMan-Chrome-Extension#7063]
**Describe the bug**
When generating code from postman, the generated code contains the "Cache-control" header twice. E.g.: generated curl command:
```
curl -X GET \
  <host>.com \
  -H 'Accept: */*' \
  -H 'Accept-Encoding: gzip, deflate' \
  -H 'Authorization: Bearer <token>' \
  -H 'Cache-Control: no-cache' \
  -H 'Connection: keep-alive' \
  -H 'Cookie: session=<session>' \
  -H 'Host: <host>' \
  -H 'Postman-Token: <token>' \
  -H 'User-Agent: PostmanRuntime/7.15.2' \
  -H 'cache-control: no-cache'
```
Other code generators also have the duplicate header key. So it seems to be an error in the source array presented to the code generators.

**To Reproduce**
1. Just generate code using postman.

**Expected behavior**
The header should only be once in the generated code.

**App information (please complete the following information):**
 - App Type: Postman for Linux
 - Postman Version 7.3.4
 - OS: linux 4.18.0-25-generic / x64

**Additional context**

My request contains a pre-request script similar to the one described [here](https://gist.github.com/bcnzer/073f0fc0b959928b0ca2b173230c0669).  
In the "temporary headers" section of the request, I only see 1 "cache-control" header:
![image](https://user-images.githubusercontent.com/3315222/62462738-6d60b380-b788-11e9-9149-7ee616c87863.png)
The body of my request is empty.

**Comment by shreys7** [comment]
Hey @BobClaerhout 
In Postman 7.2.1, we've introduced bug-fixes, support for two new languages (JS-Fetch and Powershell), and the ability to configure certain aspects of the generated snippet with the 'Experimental Codegen Mode' flag enabled in Postman's global settings. 
This particular problem has been solved in the experimental codegen mode.
```
curl -L -X GET "https://postman-echo.com/get" \
    -H "User-Agent: PostmanRuntime/7.15.2" \
    -H "Accept: */*" \
    -H "Cache-Control: no-cache" \
    -H "Host: postman-echo.com" \
    -H "Accept-Encoding: gzip, deflate" \
    -H "Connection: keep-alive"
```

**Comment by BobClaerhout** [comment]
Perfect! Thanks for the quick response!
