### ISSUE TITLE
postman 7.3.6 mac版本 import => paste raw text ====>BUG

### ISSUE THREAD

**Issue by wajncn** [a85/POSTMan-Chrome-Extension#7064]
curl 'https://*****/find' -H 'Accept: application/json, text/plain, */*' -H 'Referer: https://admin.ezbtest.top/' -H 'Origin: https://admin.ezbtest.top' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36' -H 'Content-Type: application/x-www-form-urlencoded' --data 'coinSymbol=&orderDirection=&type=&checkFlag=&orderId=&memberId=&baseSymbol=&minPrice=&maxPrice=&status=&pageNo=1&pageSize=10&completed=0' --compressed

该请求是post 但是import进去后是get请求

**Comment by Hayk-S** [comment]
Hi @wajncn , could you please inform if you are still able to reproduce the issue ?

**Comment by Hayk-S** [comment]
Closing this issue. Please feel free to reopen if there are any issues with this.
