### ISSUE TITLE
Email notifications after 3 successive failures

### ISSUE THREAD

**Issue by dilleswarmandala-tudip** [a85/POSTMan-Chrome-Extension#7067]
I am using postman pro. I had set up a monitor and added the email to get the notifications on failure. I am not receiving the email alerts after three consecutive failures. Is there any to receive email alerts on every failure. Currently, notifications are supporting only for three consecutive failures.

**Comment by preethammavin** [comment]
@dilleswarmandala-tudip can you please elaborate

**Comment by dilleswarmandala-tudip** [comment]
Postman monitor stops sending the notifications for the failures after three consecutive failures. I want to receive notification for every failure.

**Comment by ArjunSingh-PM** [comment]
Hi @dilleswarmandala-tudip! We have introduced an option for you to choose the number of consecutive failures after which you would like your monitor to stop sending failure notifications.

<img width="483" alt="Stop failure notification for consecutive failures" src="https://user-images.githubusercontent.com/53265429/80147055-83412d80-85d0-11ea-9f0e-bfb43041e4d5.png">

Documentation reference: https://learning.postman.com/docs/postman/monitors/setting-up-monitor/#the-basics-when-creating-a-monitor
