### ISSUE TITLE
Collection runner removing decimals points from CSV

### ISSUE THREAD

**Issue by g86m** [a85/POSTMan-Chrome-Extension#7069]
**Describe the bug**
Postman is failing to preserve decimal points from the attached csv during a collection run.

**To Reproduce**
1. Download CSV and remove .txt extension (this was only used to upload it to github)
2. Run any collection using the attached CSV
3. If you preview the CSV in postman collection screen, the decimals have been removed. This not a UI thing. The RAW reponse (not pretty) is also incorrect.

**Expected behavior**
"0.10" should be sent to the endpoint as "0.10" . Instead it is sent as "0.1" and so on.

**Screenshots**
![image](https://user-images.githubusercontent.com/40778675/62603565-88265a00-b939-11e9-9b64-ee26fba6283c.png)
[example.csv.txt](https://github.com/postmanlabs/postman-app-support/files/3475774/example.csv.txt)

**App information (please complete the following information):**
 - App Type [Native App]
 - Postman Version [Version 7.3.6, win32 6.1.7601 / x64]
 - OS: [Windows 7]

**Additional context**
The correct decimal points are visible when viewing the CSV in notepad. I have appended .txt to the .csv so I could upload it. 

So for whatever reason, postman seems to be dropping these decimal points. The result is that I cannot post the correct string. Possible bug?

Thanks!

**Comment by vikiCoder** [comment]
Hi @g86m 

This is a known issue. We convert numbers without quotes in CSV file into JavaScript Number while parsing the CSV file in the Postman App. As a result, information regarding trailing zeros after the decimal point is lost.

If you want to keep such numbers as it is, you can specify them as a string in CSV file by wrapping the number in double quotes like below:
```
index,specialNumber
1,"000001"
2,"0123.45600000"
```

However, for the users who don't want this behavior or want to have more control over parsing, we are planning to provide options related to CSV file parsing behavior in our long term roadmap. We will consider adding an option to parse specified columns as string by default. Other suggestions are always welcome regarding what options you would like to have when we add them.

**Comment by vikiCoder** [comment]
Closing this in favour of https://github.com/postmanlabs/postman-app-support/issues/6746

**Comment by g86m** [comment]
hi @vikiCoder 

Modifying the CSV via text editor has allowed me to upload the correct values.

Thanks
