### ISSUE TITLE
FormData Request Content-Types are neither logged to the Postman Console nor exported to the code tab

### ISSUE THREAD

**Issue by SchleichAlex** [a85/POSTMan-Chrome-Extension#7070]
**Describe the bug**
FormData Request Content-Types are neither logged to the postman console nor exported to the code tab

**To Reproduce**
1. Create a request similar to the following screenshot: 

![two](https://user-images.githubusercontent.com/11562819/62614937-a45fd200-b90c-11e9-9f15-9f5eb4dd7c58.png)

2. Execute the request and check the Postman Console

**Expected behavior**
The following screenshot of the Postman Console Log should contain the Content-Type "application/json"

![image](https://user-images.githubusercontent.com/11562819/62615153-0b7d8680-b90d-11e9-95ad-829289602324.png)

**Screenshots**
If applicable, add screenshots to help explain your problem. Please make sure the screenshot does not contain any sensitive information such as API keys or access tokens. 

**App information (please complete the following information):**
 - App Type [Native App]
 - Postman Version [v7.3.6 ]
 - OS: [Windows 7]

**Additional context**
I compared the log with the same request but this time without a Content-Type:

![image](https://user-images.githubusercontent.com/11562819/62615255-38319e00-b90d-11e9-98e1-30317f227db1.png)

The only difference seems to be the Content-Length
176 vs 208.
Most likely this difference of 32 resembles  Content-Type: "application/json" which is exactly 32 chars.

**Comment by coditva** [comment]
Hey @SchleichAlex, the `content-type` for form-data items are not shown in the pretty view. But you can always use the raw view for this:
![image](https://user-images.githubusercontent.com/8445768/76389378-10b61e80-6391-11ea-8f4c-55a0d6c7f1e9.png)
