### ISSUE TITLE
Crash during start up by EXC_BAD_INSTRUCTION (SIGILL) On Native Postman 7.3.6 

### ISSUE THREAD

**Issue by gokceng** [a85/POSTMan-Chrome-Extension#7071]
**Describe the bug**
Postman crashes when Collection Runner started.

**To Reproduce**
1. Start Postman
2. Start collection runner
2. Crash

**Expected behavior**
collection runner starts

**Screenshots**
![Screenshot 2019-08-07 at 14 17 51](https://user-images.githubusercontent.com/3234929/62626056-67044000-b91e-11e9-88a6-90ecaaed35b0.png)

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version: 7.3.6
 - OS: macOS Mojave, 10.14.6 (18G87)

**Additional context**
- When I try to start Postman again, it opens Collection Runner on the startup and if I'm quick enough to close Collection Runner window, the application starts without and issue.
- If I don't close Collection Runner window on the start up, it keeps crashing.
- Attaching crash logs.

[Postman_2019-08-07-141523_C02R61GJFVH6.crash.zip](https://github.com/postmanlabs/postman-app-support/files/3477157/Postman_2019-08-07-141523_C02R61GJFVH6.crash.zip)

**Comment by gokceng** [comment]
The situation persists on Version 7.5.0 (7.5.0).

**Comment by numaanashraf** [comment]
@gokceng This is an out of memory related error and we have made a lot of memory & performance improvements on the Runner in Postman v7.16.0. Do update and let us know if you are still facing this issue.

**Comment by saswatds** [comment]
I am closing this issue as this issue seems fixed. Feel free to re-open this issue if you are still facing problems.
