### ISSUE TITLE
Find Filter Not Displaying Fork Name of Collection 

### ISSUE THREAD

**Issue by labossieresr** [a85/POSTMan-Chrome-Extension#7073]
When you edit a request and try to find a string (i.e. right-click on a word and select find:...) the FIND frame is displayed.  There are 2 areas of concern here that show themselves when a forked collection is involved.  

First, in the FIND pane you can select within the WHERE section the desired collections to search within. There is no way to distinguish the original collection from any of the forked collections. You just have the name of the collection listed multiple times, once for the original and once for each fork. So I can't focus the scope of my FIND effectively.

Second, the RESULTS pane, when you are on the Collections tab, you once again have all the collections of the same name listed (both original and forked ones) and cannot tell which one is for which.

My recommendation for both situations is that you also include the forked description with each collection name. If you can't include it like you do within the Collections view (i.e. Line 1 = collection name, Line 2= number of requests followed by forked symbol and fork description), consider displaying the collection name and in parenthesis the fork description. For example: **MyCollectionName (my fork description)**. 

**Additional context**

**Comment by ankit-m** [comment]
We are working on this. It will be released soon.

**Comment by ankitjaggi** [comment]
@labossieresr This should be resolved in the latest version of the Postman App.
