### ISSUE TITLE
As an experienced user I want to have FULL and REAL control over automatic updates

### ISSUE THREAD

**Issue by UncleBravado** [a85/POSTMan-Chrome-Extension#7074]
As many users commenting related tickets I am totally frustrated because you force automatic updates. You claim that it is only for minor updates and patches but this is not true - my latest example is with the complete change of the component rendering the response. This broke many futures I use on a daily basis and I have no possibility to revert other than blocking your app from connecting to the update server. Did you really mean that? Do you want to treat your app not as a professional tool but nagging, uncontrollable application? 

**Describe the solution you'd like**
I would like to have a setting that REALLY controls the behaviour.

**Describe alternatives you've considered**
I do not think there is an alternative that makes sense.

**Additional context**
I do not want the app that I cannot revert to a working version in case regression happens!

**Comment by UncleBravado** [comment]
Duplicate of #6999.

**Comment by stefanluchian** [comment]
@ Postman guys: Why are you insisting to force us to update, even on minor updates?
This is no way to win new users! And you might lose existing ones.
We simply don't want automatically minor updates! Is it so hard to understand it?
We are not some mobile-app-freaks who just want to have the latest thing.
Just let us decide if and when we want minor updates!
This is really annoying!
Stop forcing us to update! Should be our decision!
