### ISSUE TITLE
Manually Updating Postman Gives Incorrect Status Message

### ISSUE THREAD

**Issue by mist83** [a85/POSTMan-Chrome-Extension#7076]
**Describe the bug**
Manually updating postman (when an update is available) claims that the current (out of date) version is the latest version.

**To Reproduce**
1. Verify version in settings (I used an installed version of 7.0.7 for this bug):
![image](https://user-images.githubusercontent.com/51882127/62649073-55686b80-b911-11e9-9696-203d29e59d84.png)
2. Go to 'Help -> Check for Updates'
![image](https://user-images.githubusercontent.com/51882127/62650002-19cea100-b913-11e9-8ce5-85ba539c6206.png)
3. Click on 'Update' on the bottom right (not shown in screenshot above)
4. View update message:
![image](https://user-images.githubusercontent.com/51882127/62650103-57cbc500-b913-11e9-9712-7baa62c8fdb2.png)
(This is incorrect, per the screenshots above 7.3.6 is the newest version and the changes don't take effect until the software is restarted)

**Expected behavior**
A prompt to restart Postman to update to the newest version? (It's your software/choice - I just explicitly _don't_ expect a message claiming I'm currently on the latest version when it's not true until the app restarts).

**App information (please complete the following information):**
 - Native App
 - Postman Version 7.0.7
 - OS: Windows 10

**Comment by preethammavin** [comment]
@mist83 this should not be happening, can you write to us at help@getpostman.com so that we can take a closer look.

**Comment by harryi3t** [comment]
@mist83 Thanks for reporting the issue. We have seen this issue when an old version of Postman is started when a newer version was already downloaded.

To confirm this, could you share screenshots of the `C:\Users<username>\AppData\Local\Postman` and `C:\Users<username>\AppData\Local\Postman\packages` directory? Also, if you have a `RELEASES` file in the packages directory, could you share that too?

**Comment by numaanashraf** [comment]
Thank you for your issue!

With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have more information for us that'll help us reproduce this issue; we'll be happy to reopen the issue.
