### ISSUE TITLE
Https becames http duplicating a request 

### ISSUE THREAD

**Issue by dmnized** [a85/POSTMan-Chrome-Extension#7081]
I'm using 
Postman v6.7.4

**Describe the bug**
Duplicating a Request https in the url becames http

**To Reproduce**
1. Consider a request with an https
2. Right click on it, Duplicate
3. The duplicated request url has http

**Comment by preethammavin** [comment]
@dmnized can you update to the latest version and verify if it fixes the issue?

**Comment by dmnized** [comment]
Yes, updating to the 7.5.0 fixes the issue. Thank you.
