### ISSUE TITLE
Error when opening valid json file

### ISSUE THREAD

**Issue by m3dbedb** [a85/POSTMan-Chrome-Extension#7082]
**The bug description**
Postman and newman 4.5.3 accidentally rejects valid json data set

Errors are unexpectedly appears in valid data files and unexpectedly goes away. One may replace integer with sting and issue disappears, or one may change email from john@mail.com to john@mail.ru and the issue goes away.

**To Reproduce**
1. Make some 1-iteration json data set with both text and value fields
2. Duplicate first iteration data to make your set to be 2 items long
4. Edit some data for second iteration (i.e. replace one string to another without changing data type)
4. See error "unexpected token in json at position 1234". Sometimes Postman say **unexpected number filed**

**Expected behavior**
One expect Postman to accept valid json data files. If there is a typo, please show wrong string or string number. It is very hard to find absolute symbol position in multi-row text file.

**App information:**
 - Native App
 - Postman 7.3.6
 - OS: windows 7 64 bit and windows 7 32 bit

**Additional context**
I apply a sample **fizdata_tip-19-5.json** with 'error' and similar **fizdata_tip-19-6.json** with number replaced by string, and it is accepted. The issue is present in previous versions of Postman and Newman. Provided data are ramdomly generated and have to relation to real people.

[fizdata_tip-19-6.json.txt](https://github.com/postmanlabs/postman-app-support/files/3482024/fizdata_tip-19-6.json.txt)
[fizdata_tip-19-5.json.txt](https://github.com/postmanlabs/postman-app-support/files/3482025/fizdata_tip-19-5.json.txt)

**Comment by vikiCoder** [comment]
Hi @m3dbedb,

It looks like the content in file `fizdata_tip-5.json.txt` is not a valid JSON data. There is a missing closing quote on `Line No: 52`.

`Line No: 52` in the given file is: `"login": "login23,` while it should be `"login": "login23",` to make it a valid JSON.

Since this is not a problem with Postman App, I am closing this issue. If this comment doesn't solve your query, please feel free to reopen the issue.
