### ISSUE TITLE
Unable to get json particular value if it has some special character in json key

### ISSUE THREAD

**Issue by bilalk88** [a85/POSTMan-Chrome-Extension#7089]
**Describe the bug**
Unable to get json particular value if it has some special character in json key

**To Reproduce**
1. I've below json content from response
`{
    "swagger": "2.0",
    "info": {
        "version": "v1",
        "title": "Demo Swagger"
    },
    "basePath": "/Demo Swagger",
    "paths": {
        "/ping": {
            "get": {
                "tags": [
                    "Health"
                ],
                "operationId": "PingGet",
                "consumes": [],
                "produces": [],
                "parameters": [
                    {
                        "name": "debug",
                        "in": "query",
                        "description": "Optional Debug parameter. If true, add additional error details if applicable.",
                        "required": false,
                        "type": "boolean",
                        "default": false
                    },
                    {
                        "name": "dmeo-test",
                        "in": "header",
                        "required": false,
                        "type": "string",
                        "default": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success"
                    }
                }
            }
        }
            }
}`
2. Now I've wrote below code on postman test box
`var jsonData = JSON.parse(responseBody);
postman.setEnvironmentVariable("awsToken", js.paths./ping.get.parameters[1].default);
`
3. Now I'm not able to get the value from specific key which "/ping" from json

**App information (please complete the following information):**
 - App Type : Native App
 - Postman Version : Version 7.3.6
 - OS: Windows 10

Can someone please help me with some which script can be used to get the json key value if it has special chars.

**Comment by shamasis** [comment]
Change your script to `js.paths["/ping"].get`

**Comment by bilalk88** [comment]
Thanks. I got this..
