### ISSUE TITLE
Run specific request N times

### ISSUE THREAD

**Issue by omkar-dsd** [a85/POSTMan-Chrome-Extension#7092]
**Problem**

Many times there's a need for running and testing one specific request repeatedly. As of now what needs to be done is, for that single request new collection needs to be created and then need to specify runner, which is a lot of effort taking job.

**Solution**

Need a quick runner option for running a specific request N number of times using the currently selected environment.

**Comment by DannyDainton** [comment]
The runner on the latest version allows you to run a single request within a collection.

You shouldn't need to create a new collection just to do this action. 😁

**Comment by omkar-dsd** [comment]
@DannyDainton Can you please specify in version this feature is available? So we can close this issue.

**Comment by DannyDainton** [comment]
It's been in there since 7.2.0 which was released on the 12th June. 

https://www.getpostman.com/downloads/release-notes

Which version are you currently using?

**Comment by omkar-dsd** [comment]
I was on **6.7.4** . @DannyDainton Thanks.

**Comment by omkar-dsd** [comment]
**6.7.4**
