### ISSUE TITLE
pm.variables not working correctly

### ISSUE THREAD

**Issue by Maxeh** [a85/POSTMan-Chrome-Extension#7093]
When using pm.variables.set(...) the variable is only accessible by the request itself. So I can use pm.variables.get(..) in the same test of the request or access the variable with {{var1}} in the body. However, in the next request of the collection, the variable is not available anymore. The strange thing is that the variable is available in the following requests if the collection is run by the collection runner or by newman. The bug only occurs when the requests are executed manually one after another. 

I now switched to environment variables, but I don't like that the environment variables have influence on other collections. So it would be nice if this bug could be fixed.

**Expected behavior**
pm.variables should be accessible in all requests of the collection

**App information:**
 - Windows App
 - Postman Version 7.3.6
 - OS: Windows 7

**Comment by codenirvana** [comment]
@Maxeh That's the expected behavior.
Local variables created using  `pm.variables` are persisted until the execution stops.
Only the environment and global variables are persisted across executions.

Also, to know more about how `pm.variables` works: https://github.com/postmanlabs/postman-app-support/issues/6082#issuecomment-473221190

**Comment by codenirvana** [comment]
On second thought, while understanding your problem with environments:
> I now switched to environment variables, but I don't like that the environment variables have influence on other collections. So it would be nice if this bug could be fixed.

We are adding support for tab specific environment soon which will solve your issue/confusion with environment variables.

**Comment by Maxeh** [comment]
@codenirvana thanks for the information. However, why does the pm.variables work across requests then if I run them with the collection runner or from the cli with newman? 

So in our case everything worked fine, because we run the postman scripts automatically with our deployment. At some point I wanted to run the tests manually and run into the error. I then changed everything to pm.environment.

**Comment by vdespa** [comment]
@Maxeh because of this behavior, it is really hard to work with local variables both in Postman as well as in collection runs. For that reason, the use-case for local variables is very limited.
