### ISSUE TITLE
Need Basic Analytics of "Average Response Time" in Runner as shown in Newman

### ISSUE THREAD

**Issue by omkar-dsd** [a85/POSTMan-Chrome-Extension#7095]
![Newman](https://raw.githubusercontent.com/postmanlabs/postmanlabs.github.io/develop/global-artefacts/newman-terminal.gif)

Need something like this in UI.

**Comment by malvikach** [comment]
@omkar-dsd 

We are happy to inform you that with Postman v10 you will be able to check the average response times for every run and a lot more!

Giving you a sneak peek into how Postman version 10 would solve the problem mentioned on the thread:
<img width="1052" alt="Screenshot 2022-09-21 at 7 37 06 PM" src="https://user-images.githubusercontent.com/89449769/191526824-aa13cf2f-91b9-48c8-8b7b-49b9b847e117.png">

We have also introduced a 'Runs' tab for collections that will contain all your Collection Runs and some useful statistics about them!!

<img width="1005" alt="Screenshot 2022-09-21 at 7 37 40 PM" src="https://user-images.githubusercontent.com/89449769/191526928-307c3d9f-b683-4604-9c56-0623073e04af.png">

The latest Postman v10 is not Generally Available(GA) right now, but we are giving early access to teams who might be keen on some of the features. If you are interested to give this a spin, please comment on this thread!

[This](https://blog.postman.com/introducing-the-postman-cli-to-automate-your-api-testing/) is our blog that talks about the other Collection Run features we are offering along with the new Postman CLI.
You can also set up some time with me to discuss further using [this](https://calendly.com/malvika-chaudhary/v10-feedback).
