### ISSUE TITLE
Add application/jose+json support in "Content-Type" list

### ISSUE THREAD

**Issue by savinthiba** [a85/POSTMan-Chrome-Extension#7096]
**Hi Postam team,**

I'm currently using an HTTPS server which requires to use a JWS body. I've noticed that the ***"application/jose+json"*** value is not part of the available list of value of the "Content-Type" header field.

Could you add it ?
Have a great day :-)

**Comment by saswatds** [comment]
Hi @savinthiba, the list shown when `Content-Type` header does not limit setting header to `application/jose+json`. The list currently present is just a small subset of very common content-type header we have identified from the community and is present to help new user get started quickly.

<img width="917" alt="Screenshot 2019-09-20 at 11 47 34 PM" src="https://user-images.githubusercontent.com/8796447/65349495-237d4100-dc01-11e9-8ec0-398d9f131e10.png">

Closing this issue for now. Feel free to re-open this issue if you are facing problem send the header you wish to.
