### ISSUE TITLE
Cannot search in Documentation web view

### ISSUE THREAD

**Issue by adropofilm** [a85/POSTMan-Chrome-Extension#7097]
**Describe the bug**
Cannot use documentation search feature in any browser. When I type in a keyword that exists, a message saying "Nothing here, Houston! We couldn’t find anything matching that." is returned.

**To Reproduce**
1. Go to published documentation.
2. Click on search bar in top right corner to search docs.
3. Search for a keyword that exists within the documentation.

**Expected behavior**
An error message with "Nothing here, Houston! We couldn’t find anything matching that."

**Comment by Raja-Simha** [comment]
Duplicate of #3747
