### ISSUE TITLE
API Network is missing URL to published documentation

### ISSUE THREAD

**Issue by stcalica** [a85/POSTMan-Chrome-Extension#7098]
**Describe the bug**
In API Network, tile card is missing link even though docs and collection are published. 

**To Reproduce**
1. Go to https://www.getpostman.com/api-network/
2. Find tile card of API Network directory
3. Find tile card with a missing URL link 
4. Check for published API and published docs existence, yet still missing link

**Expected behavior**
I would expect to see a link in the tile card to their API documentation

**Screenshots**

<img width="345" alt="Screen Shot 2019-08-12 at 3 16 40 PM" src="https://user-images.githubusercontent.com/5624835/62904149-10ca3f00-bd1a-11e9-9836-7b4c450e3dec.png">

**Comment by Raja-Simha** [comment]
Not a product issue
