### ISSUE TITLE
Feature Request: Show/Reveal active tab request in sidebar

### ISSUE THREAD

**Issue by cristiammercado** [a85/POSTMan-Chrome-Extension#7099]
**Is your feature request related to a problem? Please describe.**
Currently, there is no way to show in the sidebar of saved collections the currently active tab.

**Describe the solution you'd like**
Allow the user with some type of button or right click on the currently active tab to display it in the sidebar, expanding the folders and collections that are necessary.

**Additional context**
There are several IDEs like IntelliJ, VS Code, NetBeans, etc... that use this action to quickly search in the list of files (collections in the case of Postman) in the sidebar the current active tab. It is a quick and easy way to search for content related to what is currently being used.

**Comment by piero-b** [comment]
I would also like this as this becomes very confusing to deal with very large collections.

**Comment by arlemi** [comment]
We've started gathering similar feedback in #8486, will close this one and keep posting updates if we have any there.
