### ISSUE TITLE
Wrong HTTP method after redirect

### ISSUE THREAD

**Issue by fschindler** [a85/POSTMan-Chrome-Extension#710]
Sending a POST request which get answered with a 301 Moved Permanently results in GET request on the new resource.
Postman is processing the redirect initialized by the 301 Moved Permanently response correctly. It sends a new request to the new resource. But it is using the GET instead of the expected POST method.

**Comment by filipw** [comment]
FWIW, the HTTP specification explicitly mentions this behavior as **wrong** (RFC2616, 10.3.2)

```
If the 301 status code is received in response to a request other than GET or HEAD, 
the user agent MUST NOT automatically redirect the request unless it can be 
confirmed by the user, since this might change the conditions under which the 
request was issued. 
```

**Comment by gaohuia** [comment]
I think the redirection should be reflected in the PostMan Console like Chrome Network Panel, so it can be discovered easily. It shows only one rather two for now.
