### ISSUE TITLE
Font and font sizes seems different in request and response windows

### ISSUE THREAD

**Issue by sudhirkhanger** [a85/POSTMan-Chrome-Extension#7107]
**Describe the bug**
Font family and size seems to be different between the request and response window and possibly the UI.

**To Reproduce**
1. Run any API in the postman which has some body like json to upload and returns some response

**Expected behavior**
Font and size should be consistent in the request and response window.

**Screenshots**
![Screenshot_20190813_205452](https://user-images.githubusercontent.com/841656/62955255-5a945180-be0e-11e9-9915-bb43f7747d04.png)

**App information (please complete the following information):**
 - App Type - Native App
 - Postman Version - 7.3.5
 - OS: Fedora 30 running Plasma 5.15.5
 - Installed via Flathub.

**Comment by saswatds** [comment]
@sudhirkhanger you are right, the response viewer has been update to use a different editor stack ie. monaco editor for gaining performance benefits and lower memory foot-print. The side effect of the change in stack is the newer looking font.
This will not be for long, we will be updating the rest of the editors in the app soon. So stay tuned.
