### ISSUE TITLE
Ability to mask "Sensitive Data" in Environment Variables and request

### ISSUE THREAD

**Issue by xk0der** [a85/POSTMan-Chrome-Extension#7108]
**Is your feature request related to a problem? Please describe.**
In certain scenarios and organizations, strict compliance measures need to be followed.
The user wants the ability to be able to have sensitive data masked and only viewable and editable by the user who added/created the data.

For all other users, this sensitive data should be always masked, in Environment variables (or in API requests?)

**Describe the solution you'd like**
_Example:_
1) User-A adds a password to an environment variable.
If the variable is marked as "Sensitive Data" - The value field should behave like a password field and "dots" to be used to mask the data (Plus a toggle field to view it when required).
2) Other users who have access to this environment should not be able to view this "Sensitive Data"
3) Requests that use these values should be masked as well (only toggleable to "view" for the user-A that had added this data)

**Additional notes**
Maybe have controls to have a list of users with "Allow" "deny" roles to access the variables marked as "Sensitive Data".

**Describe alternatives you've considered**
None available.

**Additional context**
Filed by Postman on behalf of a user

**Comment by xk0der** [comment]
Use of "[Sessions](https://learning.postman.com/docs/postman/variables-and-environments/variables/#sessions-in-postman)" solves the use-case in question.
The initial value may be set to empty and users can use the "Current" value (with persist disabled) to keep secrets local only.

Private workspaces may be used to limit access to workspaces containing the collection/environment where secrets need to be shared.

Closing this feature-request.

**References:**
- [Sessions in postman](https://learning.postman.com/docs/postman/variables-and-environments/variables/#sessions-in-postman)
- [Private Workspaces](https://learning.postman.com/docs/postman/workspaces/intro-to-workspaces/#private-workspaces)

**Comment by chirag-patel-sp** [comment]
I see the "Ready" state, is this going to be available soon?
