### ISSUE TITLE
Postman crashes when invoking a certain PayPal API

### ISSUE THREAD

**Issue by xk0der** [a85/POSTMan-Chrome-Extension#7109]
**Describe the bug**
User is calling a PayPal API that results in Postman crashing.

**To Reproduce**
Have not got details of the PayPal API causing this from the user.

_But looking at the logs I see the following_
See my internal notes for more details that I found
```[2076][1564784029245][main][error]["Main~handleUncaughtError - Uncaught errors",{"generatedMessage":true,"name":"AssertionError [ERR_ASSERTION]","code":"ERR_ASSERTION","actual":9091,"expected":0,"operator":"==","message":"9091 == 0","stack":"AssertionError [ERR_ASSERTION]: 9091 == 0\n    at ClientRequest.onConnect (C:\\Users\\jurod\\AppData\\Local\\Postman\\app-7.3.5\\resources\\app.asar\\node_modules\\@postman\\tunnel-agent\\index.js:165:14)\n    at Object.onceWrapper (events.js:273:13)\n    at ClientRequest.emit (events.js:182:13)\n    at ClientRequest.EventEmitter.emit (domain.js:442:20)\n    at Socket.socketOnData (_http_client.js:465:11)\n    at Socket.emit (events.js:182:13)\n    at Socket.EventEmitter.emit (domain.js:442:20)\n    at addChunk (_stream_readable.js:279:12)\n    at readableAddChunk (_stream_readable.js:264:11)\n    at Socket.Readable.push (_stream_readable.js:219:10)\n    at TCP.onread (net.js:636:20)"}]```

There is an assertion that fails and likely is the cause of the crash.

_And then a re-launch of the client (very likely done manually)_
```[5584][1564784043342][main][info]["Booting Postman 7.3.5, win32-10.0.17763 on x64"]```

**Expected behavior**
Postman should not crash!

**Screenshots**
Logs available internally.

**App information (please complete the following information):**
 - App Type : Native App
 - Postman Version: 7.3.6
 - OS: Windows 10

**Additional context**
Filed on behalf of a user.

**Comment by coditva** [comment]
@xk0der This issue is fixed and out in the latest Postman App `v7.12.0` near you!  🎉
