### ISSUE TITLE
freezes / hangs on large responses

### ISSUE THREAD

**Issue by markstos** [a85/POSTMan-Chrome-Extension#711]
I'm testing a response that returns a JSON array with 10,000 members. Each member is not that big-- about 10 lines of modest length. But Postman uses 100% CPU for 10 minutes or so. It will eventually return a response, but the app is essentially frozen. Attempting to scroll in the output is unresponsive. 

I suspect the issue is not that so much the /size/ of the data but how it's being handled and formatted once it arrives. Perhaps CPU spent formatting the response could be limited to a submit that was in view, or nearly in view.  Or even more simply: Check the size of the response and if it's huge, don't attempt to format it all, just dump the raw text into the browser. 

Currently I have to completely kill Chrome and start each time I run this query, because Postman is locked up. (Even "Cancel request" is unresponsive).

**Comment by FractalizeR** [comment]
Is this fixed?

**Comment by mmoreira2000** [comment]
Nope.
