### ISSUE TITLE
Space should not be a valid fork label

### ISSUE THREAD

**Issue by arpitbatra123** [a85/POSTMan-Chrome-Extension#7111]
When I'm forking a collection, The UI asks me for a fork label and without entering one, I am unable to press the `Fork Collection` button. However, Space characters are accepted as a valid fork label, which shouldn't be allowed as then the fork label will then be empty.

Reference:

![fork_empty_label](https://user-images.githubusercontent.com/21967563/63012654-3ab16c00-bea8-11e9-99ac-4bf9994c96a2.gif)

**Comment by ankit-m** [comment]
Issue fixed
