### ISSUE TITLE
Hosted Gitlab firewall IP help

### ISSUE THREAD

**Issue by useful-things** [a85/POSTMan-Chrome-Extension#7115]
I have recently setup a hosted Gitlab integration, and after a firewall rule was updated the integration was successfully created. But no syncing of our collections has happened. I have tried to be thorough in working through the advice provided here on various tickets to ensure that my target repository is open and ready for commits, but still no commits happen.

I now believe that further firewall rules must be added to allow Postman servers to access our hosted Gitlab, and I have been advised by our team to request details on which domains/ips must be added to allow through the api requests. 

Would it be possible to obtain this?

Many thanks,

Paul

**Comment by stcalica** [comment]
Have you tried whitelisting these domains: 
```
*.getpostman.com
*.postman.co
*.pstmn.io
```

**Comment by preethammavin** [comment]
@useful-things did you have a chance to get this above mentioned domains whitelisted and try again?

**Comment by useful-things** [comment]
I'm waiting for our support team to pick up this task. I'm sorry for the wait.

**Comment by useful-things** [comment]
Would it be possible to have IP ranges for the domains listed? We can't whitelist domain names.

Thanks!

**Comment by stcalica** [comment]
@useful-things 
Our domains are all dynamic so we don't have IP ranges to give.

**Comment by useful-things** [comment]
Would it be possible to check with your network team for IP ranges?

In this case i'm interested in the hosted gitlab integration, which for most companies will be behind a firewall. Utilising ranges is standard practise when white-listing services. 

Many thanks!

**Comment by useful-things** [comment]
If my last request is problematic for a public forum would it be possible for me to put one of our team in touch with one of yours?

**Comment by stcalica** [comment]
@useful-things I'm trying to follow up on this request. 

I'm asking for the range or if we can get one. 

Most companies usually just whitelist our domains in their firewall. I understand you are not able to do that so I'm trying to figure out what the range would be.

**Comment by lu3ke** [comment]
> Most companies usually just whitelist our domains in their firewall. I understand you are not able to do that so I'm trying to figure out what the range would be.

Heya, @stcalica -- I'm curious as to how others are doing that, because it is not possible to whitelist based on a domain name on ordinary network firewalls.  Network firewalls work on an entirely different level than DNS does, network firewalls don't even "know about" domain names and instead operate on the IP level.  So in order to open up access from Postman to an internal hosted Gitlab instance behind a network firewall, there definitely needs to be an IP range that can be added to an ALLOW rule, it cannot be done via domain-name.  

   - Luke

**Comment by stcalica** [comment]
Did not know that. I think I'm very used to just software on my own laptop or home that lets me blacklist and whitelist domains. 

I am talking with what is acceptable information to give out. Thank you for patience guys!

**Comment by stcalica** [comment]
https://ip-ranges.amazonaws.com/ip-ranges.json

We run out of the US-EAST regions, might be 1 and 2.

**Comment by shashankawasthi88** [comment]
@useful-things @lu3ke - With the latest release we are running the GitLab, GitHub, and Webhook Integrations through a static IP. The IP addressed can be whitelisted in your network's firewall. Once whitelisted the Integration should run as expected. Please follow the link to know the details of the IP address - https://learning.postman.com/docs/integrations/intro-integrations/     https://learning.postman.com/docs/integrations/available-integrations/gitlab/#backup-your-postman-collections-to-gitlab-on-a-custom-domain . Closing this ticket for now. Please reopen/ reach out if the Integration is still not working fine.
