### ISSUE TITLE
Swagger Import Issue

### ISSUE THREAD

**Issue by Raj-postman** [a85/POSTMan-Chrome-Extension#7116]
**Describe the bug**
When you try to import a Swagger API definition file, receives an error message. This works fine in Postman Chrome and Windows version.

**To Reproduce**
1) Click on the 'Import' button
2) Click on the 'Paste Raw Text' tab
3) Paste the JSON format in the text area and click import
Receives the error importing

**Expected behavior**
Be able to import the swagger file without issues

**Screenshots**
<img width="316" alt="Screen Shot 2019-08-14 at 7 07 30 PM" src="https://user-images.githubusercontent.com/47771757/63025440-d94cc580-bec6-11e9-8bf2-166da9b49987.png">

**App information (please complete the following information):**
 - App Type - Native App
 - Postman Version - 7.3.4
 - OS: Mac Mojave 10.14.6

**Additional context**
Works fine with the same file in Chrome app or Postman version 7.2.0. Also tried the manual edit on the field to True
```
API Call > GET /api/3/asset_group/{id}
Field > "required":true
```

**Comment by nomadme** [comment]
Experiencing a same issue on Version 7.5.0 (7.5.0)

**Comment by DannyDainton** [comment]
Hey @Raj-postman 

Is this still an issue in the latest version?

**Comment by Raj-postman** [comment]
Hi @DannyDainton - this works fine for me. 

@nomadme are you still able to replicate this issue on v.7.30.1?

**Comment by DannyDainton** [comment]
Closing this one out as we haven't heard from the user, we can open this up again if this is still an issue.
