### ISSUE TITLE
No way to edit/view collection variables if user is only a viewer

### ISSUE THREAD

**Issue by Joshuamay79** [a85/POSTMan-Chrome-Extension#7117]
**Describe the bug**
We have several shared collections with collection level variables in them. When a user is set as a viewer, there is no way for them to view the variables. With that, their current values for them are blank, instead of being populated with the initial values from the collection. I understand they can  override them at the environment level, but they still can't see what the variable names are.

**To Reproduce**
1. Click New Collection
2. Go to the Variables section
3. Add a variable with an initial value
4. Click create
5. Click menu on that collection and select Manage Roles
6. Add a user as a viewer on that collection
7. As the other user, click the menu for the collection
8. See there is no way to edit/view the collection variables. Also the variables only have empty values set for current values. 

**Expected behavior**
I would like a way to set the collection variable current values for viewer users
OR
I would like a way to view the variable names so they can be over written at an environmental level.

**Screenshots**
If applicable, add screenshots to help explain your problem. Please make sure the screenshot does not contain any sensitive information such as API keys or access tokens. 
![image](https://user-images.githubusercontent.com/1290574/63036572-e5af2f00-be82-11e9-8fec-df61a9f9dccf.png)
![image](https://user-images.githubusercontent.com/1290574/63036625-011a3a00-be83-11e9-91a9-c1c9e3262856.png)

**App information (please complete the following information):**
Postman for Windows
Version 7.5.0
win32 10.0.16299 / x64

**Comment by shamasis** [comment]
Yeah. This is a bummer. @vkaegis
