### ISSUE TITLE
New folder/requests not synced to the client

### ISSUE THREAD

**Issue by VicKetchup** [a85/POSTMan-Chrome-Extension#7119]
**Describe the bug**
We got a branch of a collection that the owner has modified to add new folder and more requests, however nobody else in the team is able to see those changes. Looking through web UI, the changes are there for everyone, however no matter what we do, the client doesn't show the new folder and requests.

**To Reproduce**
1. Create a branch of the collection
2. Add new folder and some new requests
3. Changes are only visible on the client of the user who made the changes

**Expected behavior**
The client should display the changes that have been made to the collection.

**Screenshots**
Client: 
![image](https://user-images.githubusercontent.com/43671684/63088863-0b553a80-bf4e-11e9-82fd-ba9b5c393101.png)
Web:
![image](https://user-images.githubusercontent.com/43671684/63088964-53745d00-bf4e-11e9-9dae-b244d4e38108.png)

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version: 7.5.0; 7.2.2;
 - OS: macOS High Mojave 10.14.5

**Additional context**
Changes to the URLs, descriptions etc. do work as expected, however tried adding another folder with requests on a different machine and again, while the web UI saw the changes, no other clients displayed it.

**Comment by ivliskot** [comment]
Nice one! this is really annoying!!!

**Comment by preethammavin** [comment]
@VicKetchup wanted to understand the issue better, you have a collection C1 which has a requests and folders. And when a user adds a folder to C1 that is not reflected on the same collection C1 on other clients? 

Or when you say branch do you mean you have a fork of collection C1 and when you merge it back it is not reflecting to other users?

**Comment by VicKetchup** [comment]
@preethammavin The first scenario. 
I mentioned branch in case it made any difference, as the collection that this is happening on is a branch.

**Comment by preethammavin** [comment]
@VicKetchup I am not able to replicate this, as I tried creating a fork and added requests, folders renamed them and everything syncs across clients. This is clearly not expected, it shows on web means that the data is synced to the cloud, would be great to look at the logs for the users/clients which did not get the information (view->developers->view logs in finder) and send it across to help@getpostman.com (with the github issue id as reference )so that we can have a closer look. 


I am assuming everyone is on the same team.

**Comment by VicKetchup** [comment]
@preethammavin email sent :)

**Comment by preethammavin** [comment]
@VicKetchup would be great if you can mail the collection id, which is not getting synced. That would help us debug faster :)

**Comment by ankit-m** [comment]
Issue closed after email conversation.
