### ISSUE TITLE
Request with an accent in url doesn't works like browsers

### ISSUE THREAD

**Issue by 0ddlyoko** [a85/POSTMan-Chrome-Extension#7123]
**Describe the bug**
When you request a url with an accent in the path, it doesn't works like browsers

**To Reproduce**
1. Create a .htaccess file like [here](https://pastebin.com/9TT9HWfP)
2. Create an index.php file like [here](https://pastebin.com/RFmsDUYR)
3. Open Chrome, Firefox, Opera or Edge and browse to "localhost/test/é"
4. Now open PostMan and send a request to "localhost/test/é"

**Expected behavior**
/test/%C3%A9

**Actual behavior**
/test/�

**Screenshots**
Opera: http://prntscr.com/ot85ne
Postman: http://prntscr.com/ot85t6

**App information (please complete the following information):**
 - App Type Native app
 - Postman Version 7.5.0
 - OS: Windows 10 version 10.0.18362

**Additional context**
Redirect doesn't works if you remove the "test/" path (localhost/é) (Tested with WampServer on Windows)

**Comment by codenirvana** [comment]
Closing it as a duplicate in master issue: #4555

**Comment by vikiCoder** [comment]
Hi, this is fixed in the latest [Postman Canary](https://www.postman.com/downloads/canary) release (version 7.20.0-canary03). You can see more details about the fix at #8154

**Comment by codenirvana** [comment]
This is fixed in the latest version of the Postman app (v7.20.0) by enabling the "Use next generation URL processing" setting as mentioned in #8154.
