### ISSUE TITLE
Monitor result graphY-Axis values do not match with "response time" values

### ISSUE THREAD

**Issue by xk0der** [a85/POSTMan-Chrome-Extension#7124]
**Describe the bug**

Monitor result graph's Y-Axis labels do not match the value shown in "Response time".
Y-Axis labels seem to repeat as well (see the second screenshot with .2s repeated) (likely because of rounding of two 0.2X 0.2X values?)

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a Monitor with a couple of requests
2. Run the monitor couple of times
3. Observe that the response time values do not match with Y-Axis labels.

**Expected behaviour**
Y-Axis label values should align with response time values in the graph.

**Screenshots**
_Example 1 via user:_
![image](https://user-images.githubusercontent.com/21366/63127694-17e99980-c007-11e9-9e18-f957bfa8eec0.png)

_Example 2 from my test monitor:_
![image](https://user-images.githubusercontent.com/21366/63127705-220b9800-c007-11e9-98e0-b02403bf6886.png)

**App information (please complete the following information):**
Monitor Web Dashboard

**Additional context**
Logged by Postman on behalf of a user.

**Comment by ArjunSingh-PM** [comment]
@xk0der Changes to correct this issue are already on Beta. Could you please test the same and confirm this is resolved for you.

**Comment by ArjunSingh-PM** [comment]
Confirmed that this issue is fixed.
