### ISSUE TITLE
Native postman app doesn't find locally hosted ASP.NET web API using IIS Express

### ISSUE THREAD

**Issue by stahlechris** [a85/POSTMan-Chrome-Extension#7125]
**Describe the bug**
osx native postman app doesn't find locally hosted ASP.NET Web Api using IIS Express, returns status 400 on GET requests. When compared to Postman for Chrome, the chrome app works as intended.

**To Reproduce**
0. Download and install 2.2 .NET core sdk. https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-2.2&tabs=visual-studio-mac
1. Open VS and create a new project via -> ASP.NET core -> API 
(Make some dummy data if you'd like)
2. Run the VS solution. 
3. Copy the url from the browser window that opens. Paste it into Postman
4. Click send on a GET 

**Expected behavior**
Native app should display the same data as the chrome app. Native app should be able to find localhost.

**Screenshots**
First shot shows localhost data in chrome next to GET request data on Postman for Chrome.
<img width="1440" alt="Screen Shot 2019-08-15 at 4 03 20 PM" src="https://user-images.githubusercontent.com/20776877/63127288-94349c00-bf77-11e9-9833-8b30a43c7e07.png">

Second shot shows Native Postman w/ error next to Postman for Chrome.

<img width="1440" alt="Screen Shot 2019-08-15 at 4 34 21 PM" src="https://user-images.githubusercontent.com/20776877/63128453-9a784780-bf7a-11e9-9189-170e3d855596.png">

**App information (please complete the following information):**
 - App Type OSX 
 - Postman Version 7.5.0
 - OS: Mojave 10.14.5
- Chrome version Version 76.0.3809.100 (Official Build) (64-bit)

**Additional context**
Disabling proxy's doesn't this behavior go away. 
Disabling SSL cert verification doesn't make this behavior go away. 
Adding global proxy of localhost with matching port number doesn't make this behavior go away.

**Comment by shamasis** [comment]
Quoting from another issue to possibly state that this is happening for both windows and mac OS. Thanks @RichardJFoster

> While the initial bug report is somewhat lacking, I'm seeing the same thing when running Postman 7.5.0 on Windows 10 attempting to access a url available on a local IIS instance.
> 
> The URL I am attempting to access is http://[LocalMachineName]/[VirtualFolder]/api/endpoint.
> 
> I can access the URL successfully using a web browser (specifically Chrome, but I imagine it'll work in the other browsers too). From Fiddler, I'm getting a 406 response, but I think that error is misleading.
> 
> According to Teltronic Fiddler (v5.0.20192.25091), the request actually being made by Fiddler is http://[LocalMachineName]/. The request headers appear to be correct, however and the user agent identifies itself as PostmanRuntime/7.15.2
> 
> Attempting to use http://localhost/.... instead of the local machine name results in the same problem.
> 
> Requests to non-local hosts appear to be operating correctly.

https://github.com/postmanlabs/postman-app-support/issues/7149#issuecomment-523961957

**Comment by tsasioglu** [comment]
I was able to solve this by going File -> Settings -> SSL certificate verification -> OFF

**Comment by systemdice** [comment]
Thank you so much @tsasioglu . It worked for me. You saved my time.

**Comment by TCROC** [comment]
@tsasioglu Not saying you are "the man"... but if there were to theoretically be "a man", he might look something like you 😉

**Comment by DannyDainton** [comment]
Closing this issue out as the issue has been resolved.

If users are still facing issues, we can look to open this again.

**Comment by Rikudouensof** [comment]
> I was able to solve this by going File -> Settings -> SSL certificate verification -> OFF

This is done on the postman, not on Visual studio. don't get lost
