### ISSUE TITLE
Disable Click to Open Links option

### ISSUE THREAD

**Issue by acblksun** [a85/POSTMan-Chrome-Extension#7126]
**Feature.**
Previously links returned in the text of an `application/json` results would not navigate. 

Now, if when we click the mouse into the property, PostMan will automatically open a new postman tab. However because postman doesn't render html (and we don't want it to), I'm now stuck with either
- copying the property with `"`'s and removing them manually, or going through some contortions to get the url out without triggering the link
- closing the PostMan tab that just opened.
- or resorting to `Preview Mode` because both `Raw` and `Pretty` will auto-navigate links.

**Describe the solution you'd like**
- Minimally, an option to disable navigation (like we can disable automatic 302). Honestly never needed to open a standard link in PostMan
- some IDE's use `Ctrl-Click` to open, and `Copy Link` to clipboard would also be ideal
- Some people might want open in browser - open in incognito tab, etc

**Screenshots**
Auto-linking json content
![image](https://user-images.githubusercontent.com/2180613/63135513-4cb71a00-c022-11e9-9ebc-f01e495e1895.png)

Always having to close the opened tab
![image](https://user-images.githubusercontent.com/2180613/63135536-68222500-c022-11e9-9aa8-43462b614c72.png)

**Comment by kamalaknn** [comment]
@acblksun Thanks for reporting this. We appreciate your suggestions.

We are tracking this issue as part of #6984. I'm closing this issue as a duplicate. Please follow the original issue for updates related to this.
