### ISSUE TITLE
Error in the editor Unexpected '@' when trying to access field in a test script

### ISSUE THREAD

**Issue by timatanu** [a85/POSTMan-Chrome-Extension#7127]
So I'm trying to write a test to validate the content in the **@EMAIL** and @EMPLID fields in the response message.

The response message contains fields with the @(at sign) in them
{
  "@EMAIL": "U7841698@some.outfit.com",
  "@EMPLID": "7841698"
}

And the editor is giving the error "Unexpected '@'"
 pm.test("@EMAIL Check", function () {
     pm.expect(jsData.**@EMAIL**).to.eql("U" + userId + "@anu.edu.au);
 });

**Comment by xk0der** [comment]
Can you try accessing the property like this?

```jsData["@EMAIL"]```

**Comment by timatanu** [comment]
Hello Amit,


Thanks for the super quick response.

It works.


I tried doing something like that after seeing a similar problem on StackOverflow and was still getting an error. I must have had a secondary syntax error of some kind which meant I was still seeing the red X mark.


Anyway all good now.


Thanks

Tim Armstrong


________________________________

**Comment by xk0der** [comment]
No worries! 

Glad to know the issue was resolved!

Cheers
