### ISSUE TITLE
Non-payment of invoices warning despite no unpaid invoices are listed

### ISSUE THREAD

**Issue by foxbunny** [a85/POSTMan-Chrome-Extension#7128]
**Describe the bug**

Postman app shows a warning about unpaid invoices.

![image](https://user-images.githubusercontent.com/65413/63157119-81bd6f80-c016-11e9-8372-665ef9a61103.png)

I contacted our billing contact, and what they see is:

![image](https://user-images.githubusercontent.com/65413/63157157-969a0300-c016-11e9-93e1-c229b33da7c4.png)

**Expected behavior**

No warning about unpaid invoices is shown.

**App information (please complete the following information):**
 - App Type Native App
 - Postman Version v7.5.0
 - OS: Windows 10

**Comment by debjeetsarkar** [comment]
This should be fixed now.

Contact help@getpostman.com for further assistance.

**Comment by msharma-dev** [comment]
@debjeetsarkar started getting the same error today and not able to login to my account to even see bills if any, which I am sure there are none.

**Comment by bsljth** [comment]
I am seeing something similar on the Desktop App, and we are on the free plan with no outstanding invoices (we were on a paid plan earlier).

Error:

> Sorry, your access is blocked
> Postman services have been suspended due to overdue invoices. Payment can be completed from your billing dashboard. Contact us at sales@getpostman.com for assistance.

App: Desktop

OS: Debian 12 (Bookworm)

<img width="1176" height="790" alt="Image" src="https://github.com/user-attachments/assets/bdf419fe-4302-481a-bb47-4320068fbb8a" />

<img width="1920" height="909" alt="Image" src="https://github.com/user-attachments/assets/d6348ade-4361-439e-8d2f-16f6b5f1e8b5" />

**Comment by abhijitkane** [comment]
@bsljth Can you reach out on help@postman.com or sales@postman.com from your registered email, citing this Github URL? We should be able to sort this out.

**Comment by bsljth** [comment]
@abhijitkane Done.
