### ISSUE TITLE
Duplicate history

### ISSUE THREAD

**Issue by Fjnova** [a85/POSTMan-Chrome-Extension#713]
Please don't set duplicate history or add new feature for saving request.

thanks!

**Comment by bpinney** [comment]
It seems like duplicate GET requests are omitted from the history, but duplicate POST requests are added even if headers, parameters, auth, and body data are the same.

Postman Version 4.5.1 (4.5.1)

**Comment by abhijitkane** [comment]
@bpinney This is intentional - PUT/POST requests generally update the server each time, even if the request is the same. The same GET request sent multiple times will usually have the same effect as one.

**Comment by bpinney** [comment]
@abhijitkane Thank you for the quick response. As the utility of recording each PUT/POST request is diminished  without an accompanying recorded server response, perhaps some day this intentional feature may be optional.

**Comment by IceMimosa** [comment]
Is there any feature to remove duplicate history? thanks @abhijitkane

**Comment by magnusburton** [comment]
This is still an issue.
