### ISSUE TITLE
Enable javascript in response solution

### ISSUE THREAD

**Issue by nikandlv** [a85/POSTMan-Chrome-Extension#7131]
Hey postman team!

With this patcher people can enable or disable sandbox mode in postman

i think its a necessary feature since people build their pages and even error pages in `react`, `vue` and other frameworks

heres my proposal, theres a setting in Settings that can enable or disable this

https://github.com/nikandlv/postman-patcher

**Comment by shamasis** [comment]
Hey there. I appreciate the effort you’ve put in. There are still security implications we haven’t run through in order to implement this. Meanwhile, we have added the new “visualiser” feature to combat some of the use cases.

**Comment by nikandlv** [comment]
@shamasis i appreciate the new visualizer however this does not solve the main issue
i think it should be optional for user to enable this with proper warning
insomnia is doing it and its great. i been using postman for a long time but this is kinda a deal breaker

**Comment by shamasis** [comment]
@nikandlv the issue is that we render preview in iframe. We haven’t found an effective way to sandbox the iframe and not allow any code to break out to outer window. Any suggestion?

Also, we cannot do webview because our window is already a webview and nested webviews don’t work well in the version of electron we are running.

**Comment by shamasis** [comment]
@nikandlv - for visualiser we could achieve the result since the outer HTML is in our control and we harden the window from inside. If you’ve got ideas, we can chat. 🎉🎉

**Comment by nikandlv** [comment]
@shamasis Well i think there are some ways that we can achieve this since its using electron. if your electron version is up to date there are some workarounds to approach this securely. of course its not going to be easy but its worth it. if postman was oss i would gladly implement this and send a PR

**Comment by nikandlv** [comment]
@shamasis sure! im gonna do a bit more research on this then ill let you know

**Comment by shamasis** [comment]
Can you email me at shamasis@g\*tp\*stm\*n.com and we can find a way to chat around this.
