### ISSUE TITLE
console.log always outputs null

### ISSUE THREAD

**Issue by xUrko** [a85/POSTMan-Chrome-Extension#7133]
Postman v7.5.0

Console log action always prints null instead of the variable value. 

**Code example**

postman.setEnvironmentVariable("UserID", data.result.id);
console.log("UserID is set to:", + data.result.id);

**Comment by shamasis** [comment]
Can you expand the output by clicking the arrow beside the console row and check if the data is actually being sent to console?

Also, I’m assuming the code you’re using is `console.log("UserID is set to:" + data.result.id);` or `console.log("UserID is set to:", data.result.id);` ... notice that I’ve removed the misplaced comma in once case and a misplaced plus sign in the other.

**Comment by xUrko** [comment]
OK, if I removed the plus sign it's working e.g. console.log("UserID is set to:", data.result.id);

But the code with the plus sign worked till this version.
