### ISSUE TITLE
Unable to navigate to the iDP Login Page from the Postman Mac application within a company's specific network

### ISSUE THREAD

**Issue by aamir-ahmed** [a85/POSTMan-Chrome-Extension#7135]
**Describe the bug**
User observes a loading image after they select the iDP on the Postman Mac application. This issue is seen only within the company's specific network. SSO login works as expected outside the company's network

**To Reproduce**
Steps to reproduce the behaviour:
Within the company's network
1. Click on "Sign in here" next to "Enterprise user?" on the main login page
2. Enter the Team Domain and submit
3. Select the iDP Provider
4. You see the loading image

Expected behaviour:

When you select the iDP provider, you should be redirected to the iDP Login URL within the embedded browser for you to enter the iDP credentials.

App information (please complete the following information):

Native App
Postman 7.3.6
OS: Mac

Additional Context: iDP used is ADFS

**Comment by elssar** [comment]
This is not something we can do anything about as it is related to your internal network configuration/setup. You can run the following collection to check whether there is a network level block on the Postman app's user agent - https://documenter.getpostman.com/view/6314135/SVfJTB7J
