### ISSUE TITLE
Unable to SSO Login into the Postman Mac Application using iDP credentials within the company's specific network

### ISSUE THREAD

**Issue by aamir-ahmed** [a85/POSTMan-Chrome-Extension#7136]
**Describe the bug**
User observes a loading image after they select one click signin on the iDP Login page. A 401 UnAuthorized response is received from the iDP and the redirect to the Identity Service callback endpoint does not happen.

**To Reproduce**
Steps to reproduce the behaviour:
1. Click on "Sign in here" next to "Enterprise user?" on the main login page
2. Enter the Team Domain and submit
3. Select the iDP Provider and you are redirected to the iDP Sign in page
4. Select one-click-signin and submit
5. Loading image page observed

**Expected behavior**
After entering the iDP credentials, you would be redirected to the Postman Mac application as a user that has signed in.

**Screenshots**
If applicable, add screenshots to help explain your problem. Please make sure the screenshot does not contain any sensitive information such as API keys or access tokens. 

**App information (please complete the following information):**
Native App
Postman 7.x.x
OS: Mac

**Comment by elssar** [comment]
This is not something we can do anything about as it is related to your internal network configuration/setup. You can run the following collection to check whether there is a network level block on the Postman app's user agent - https://documenter.getpostman.com/view/6314135/SVfJTB7J
