### ISSUE TITLE
Monitor Creation Flow - Truncated option names causing rendering issue

### ISSUE THREAD

**Issue by DannyDainton** [a85/POSTMan-Chrome-Extension#7140]
**Summary**

The checkboxes for the options in the `Monitor` creation are incorrectly sized and spaced due to the text label truncating.

**To Reproduce**

Steps to reproduce the behaviour:

1. Press the `+New` button
1. Select the `Monitor` option from the modal
1. Open the options menu by selecting the `...` icon

**Expected Behaviour**

The labels should be displayed on the same line and the boxes should be evenly spaced with a consistent gap between them.

**Screenshots**

<img width="420" alt="Screenshot 2019-08-19 at 12 18 56" src="https://user-images.githubusercontent.com/17089546/63262068-ef6ad500-c27c-11e9-8d0e-5821ad1a5194.png">

**Environment Information:**

 - App Type: Native App
 - Postman Version: 7.5.0
 - OS: macOS Mojave 10.14.6

**Additional Information**

A quick solution could be to increase the `width` of the dropdown to `175px`/ The width of the longest label - This would allow all the labels to be shown on one line and fix the checkbox size and spacings.

<img width="898" alt="Screenshot 2019-08-19 at 12 22 06" src="https://user-images.githubusercontent.com/17089546/63262195-407ac900-c27d-11e9-85ad-b635c4c05f9a.png">

**Comment by ArjunSingh-PM** [comment]
This issue is resolved.
