### ISSUE TITLE
Can't Sign Up or Sign In with Google

### ISSUE THREAD

**Issue by stevenmchoi** [a85/POSTMan-Chrome-Extension#7141]
**Describe the bug**
500 error when trying to sign up or sign in to Postman

**To Reproduce**
1. Go to 'https://identity.getpostman.com/signup' or 'https://identity.getpostman.com/login'
2. Click on 'Sign up with Google'
3. Click through Google Auth flow
4. See "500. That’s an error. There was an error. Please try again later. That’s all we know."

**Expected behavior**
I expected to be signed in or to create an account on Postman.

**Screenshots**
![Screen Shot 2019-08-19 at 11 55 49 AM](https://user-images.githubusercontent.com/7029300/63291494-7d908c80-c278-11e9-9c22-202cb549aaaa.png)

**App information:**
 - Chrome App, webapp, macOS app
 - Postman Version 7.5.0
 - OS: macOS High Sierra 10.13.6

**Comment by jeanfrancoislarente** [comment]
Same issue / version here except Windows.

**Comment by mccannt** [comment]
@stevenmchoi @jeanfrancoislarente 
It appears that Google is having some outages right now that are impacting many that rely on their services - https://www.google.com/appsstatus#hl=en&v=status

Hang tight!

**Comment by jeanfrancoislarente** [comment]
Awesome thanks for the quick response. Tried logging into GSuite and lo and behold - not working!

**Comment by jeanfrancoislarente** [comment]
All working again now...
