### ISSUE TITLE
Manipulating global environment via sandbox messes up session

### ISSUE THREAD

**Issue by JohnArrowwood** [a85/POSTMan-Chrome-Extension#7142]
**Describe the bug**
When you manipulate the value of a global variable via `pm.globals.set(...)`, it causes all "current value" to be persisted over the "initial value" - at lease as far as can be seen when looking at the UI.

Since the whole purpose of Sessions and the Initial vs. Current value is to enable you to keep things private and/or unchanging, this is a major violation.

**To Reproduce**
1. Define a global variable that is intended to contain sensitive information, `my-private-var`
2. Set the initial value to "NOT-SET"
3. Set the current value to something that you don't want the world to see when you save the collection
4. Create a request, e.g. GET "http://www.example.com/"
5. In the pre-request script, call `pm.globals.set("some-other-variable","some-value");`
6. Execute the request
7. Inspect the global variables - `my-private-var` initial value has been changed to the current value!

**Expected behavior**
Changing variable A should never cause a change to the initial value of variable B.  Or variable A, for that matter.  Only if A does not exist should programmatically setting it cause the initial value to be modified.

**App information (please complete the following information):**
 - App Type - Native App
 - Postman Version - 7.5
 - OS - Windows 10

**Comment by codenirvana** [comment]
@JohnArrowwood Can you share a scaled-down collection/screen recording which we can use to reproduce this issue?

Not able to reproduce this issue using the steps you mentioned above.

**Comment by JohnArrowwood** [comment]
Discovered that the "Automatically persist variable values" setting was turned on.  Therefore, this is as-designed.
