### ISSUE TITLE
Feature request: User-defined script libraries

### ISSUE THREAD

**Issue by sgarshol** [a85/POSTMan-Chrome-Extension#7144]
I have some scripts that I have written myself that perform parsing and assertions on responses and I reuse these in multiple requests. 

It would be nice to have the functions declared in a central library so I don’t have to manually update each collection/folder/request where they are declared.

Currently I am copying and pasting each of these scripts into each test. 

-S

**Comment by codenirvana** [comment]
Duplicate of #1180
