### ISSUE TITLE
SSO SP-Initiated Login fails because iDP requires SP signing certificate

### ISSUE THREAD

**Issue by aamir-ahmed** [a85/POSTMan-Chrome-Extension#7146]
**Is your feature request related to a problem? Please describe.**
For SP-Initiated Login, IDP expects AuthN requests to be signed when received via the POST or Redirect binding. We do not currently support this.

This setting is currently optional in the SAML protocol and the signature policy can be disabled at the iDP , although it seems that for some organizations It is a mandatory policy that the setting is enabled.

**Describe the solution you'd like**
Ideally, we should be providing a SP signing certificate for the organizations to upload it onto their iDP configuration

**Describe alternatives you've considered**
We requested the organization to disable the signature policy on their iDP settings but the request was declined since its a mandatory policy for the presence of a SP signing certificate for all SP-initiated logins.

**Comment by anudeepmedicharla** [comment]
@ArjunSingh-PM I guess we can close this issue now.

**Comment by ArjunSingh-PM** [comment]
This feature has been implemented. Therefore, closing this request. @aamir-ahmed
