### ISSUE TITLE
Unable to select a collection from drop down to create a monitor via dashboard 

### ISSUE THREAD

**Issue by ArjunSingh-PM** [a85/POSTMan-Chrome-Extension#7148]
**Describe the bug**
Unable to select a collection from drop down to create a monitor via dashboard 

**To Reproduce**
1. Go to your Workspace -> Monitors
2. Click on 'Monitor a collection in this workspace'
3. Click on 'Select a collection to monitor'
4. Error - you will not be able to select a collection from the list

**Expected behavior**
Should be able to select a collection from the list

**Screenshots**
<img width="670" alt="Create Monitor" src="https://user-images.githubusercontent.com/53265429/63343621-118f5080-c36c-11e9-87f8-4a27b8f430d5.png">

**App information (please complete the following information):**
 - App Type : Native App
 - Postman Version 7.5.0
 - OS: X 18.6.0 / x64

**Comment by roidudev** [comment]
same problem here

**Comment by jukkariik** [comment]
also same issue found.

**Comment by ArjunSingh-PM** [comment]
I am able to create a monitor on any collections from the Postman app as a workaround.

**Comment by jukkariik** [comment]
Worked also here when using postman app as a workaround.

**Comment by ArjunSingh-PM** [comment]
This issue is fixed now.
