### ISSUE TITLE
Native App Update throws 403 & Routes to Payment Page

### ISSUE THREAD

**Issue by chrisdeso** [a85/POSTMan-Chrome-Extension#7152]
**Describe the bug**
When updating the native application, a `403 EACCESS` error is being thrown and users are reportedly routed to the payment page.

**To Reproduce**
1. Open app
2. Click on `update` prompt
3. See update failure
4. Retry Update
5. See payment/upgrade page

**Expected behavior**
The app should update without routing to the payment page

**Screenshots**
![image](https://user-images.githubusercontent.com/4734306/63359870-171c7480-c333-11e9-855b-30a65fb01f3d.png)
![image](https://user-images.githubusercontent.com/4734306/63359883-1aaffb80-c333-11e9-8a17-3082baf0ea27.png)

**App information (please complete the following information):**
 - App Type: Native
 - Postman Version: 
 - OS: 

**Additional context**
Filed by Postman
- https://twitter.com/CrabLabuk/status/1163485176447586304

**Comment by harryi3t** [comment]
@chrisdeso Do we know which button is taking to the payment page?
I tried clicking both the `lear more... ` link and the `manually download` button.

**Comment by numaanashraf** [comment]
This issue doesn't have enough information for us to reproduce and take action. We are closing this for now.
