### ISSUE TITLE
An error occurred while deleting the integration. Try again after some time.

### ISSUE THREAD

**Issue by JP-from-Postman** [a85/POSTMan-Chrome-Extension#7157]
**Describe the bug**
When trying to delete the APIMatic integration from a workspace, user is receiving following error message:

`An error occurred while deleting the integration. Try again after some time.`

User has tried:
- Hard-refreshing browser page (Chrome)
- Attempting to remove integration using a different browser (Safari)
- Waiting 2 hours, and attempting to remove the integration again

However, the same error is shown.

**To Reproduce**
(User specific)
1. Attempt to delete integration via Dashboard
2. Receive error message

**Expected behavior**
Integration is able to be deleted

**Screenshots**
<img width="820" alt="Configured Integrations 2019-08-20 14-14-52" src="https://user-images.githubusercontent.com/43283131/63393458-1524d680-c370-11e9-864f-e6b517ee1c99.png">

**App information (please complete the following information):**
 - App Type: Web Dashboard (Chrome, Safari)
 - Postman Version: 7.3.5
 - OS: MacOS

**Additional context**

**Comment by Raj-postman** [comment]
@JP-from-Postman The team has identified the cause of the issue and is currently fixed. Feel free to reopen if the issue persists.
