### ISSUE TITLE
Postman App as a Server - Coder.com does with VSCode

### ISSUE THREAD

**Issue by JockDaRock** [a85/POSTMan-Chrome-Extension#7158]
**Is your feature request related to a problem? Please describe.**
Postman is accessible on the desktop but not accessible remotely from multiple places and not accessible served as a web application. This is more of an issue of portability and scaling of Postman.

**Describe the solution you'd like**
I would like to access Postman from a browser window/tab with access to remote environments that have access to APIs in those environments but without having it installed on a specific desktop.  I would also like to run it in a Docker container from a cloud service or container orchestrator in a private environment.  Basically, I am asking for a conversion of the Postman Electron App into an actual web app that runs as a server.

The Coder-Com project that has converted the VSCode IDE (Electron App) into a server that can be accessed via a browser https://github.com/cdr/code-server is what I am basing this concept off of.  You can even run VSCode, from a docker container, i.e. `docker run -it -p 127.0.0.1:8443:8443 -v "${PWD}:/home/coder/project" codercom/code-server --allow-http --no-auth`. 

It would be cool to have the same functionality for Postman.

It would also be good to have the ability to preload collections and have users use postman collections from their web browser/tab, further enhancing the developer experience.

**Comment by preethammavin** [comment]
@JockDaRock for now you could use our Newman which can be deployed for you to run the collection, but taking this as feature request for our Postman App as well.

**Comment by JockDaRock** [comment]
@preethammavin Thank you for your response.  I am familiar with Newman and use that as well ;) .

Thank you for taking this on as a feature request.  Will be super excited to see it in the future.  I believe one of my colleagues from DevNet Stéve from France will be at PostCon this month.  Wish I was going as well.

**Comment by JockDaRock** [comment]
Hey @preethammavin I hope you are well.

Quick question, do you think this will get added to the RoadMap for Postman, and when do you think  it will?

Not trying to be pushy, just wanted to feel out a possible time frame.

Kind Regards

**Comment by preethammavin** [comment]
@JockDaRock we are looking at how we can solve the base use case of sending requests from collection in cloud rather than have an electron app for it, This has been part of our long term roadmap. Will definitely reach-out and get your feedback when we have more concrete approach to the problem :) . Keeping this issue open so that we understand all the issues and workflows that our users have to build out  the right experience :)

**Comment by numaanashraf** [comment]
@JockDaRock Postman is on the Web now - https://go.postman.co. Do check it out and we'd love to hear your feedback and thoughts on how this helps with your remote workflows.

https://blog.postman.com/announcing-postman-for-the-web-now-in-open-beta/

**Comment by shashankawasthi88** [comment]
Closing this issue as we have Postman on the web (https://go.postman.co) and cloud agent running API calls from the web.
