### ISSUE TITLE
Disallow trailing newlines in environment variable names

### ISSUE THREAD

**Issue by elicoten** [a85/POSTMan-Chrome-Extension#7162]
Postman could display a warning if there are trailing newlines in an environment variable name.

**Is your feature request related to a problem? Please describe.**
I copied and pasted a few environment variables from outside postman and I pasted them into the "name" box in the Environment variables dialog, and then highlighted each name and value within that cell separately and cut/pasted it into the appropriate 'cell' to set up several environment variables.

Then I found that one of them (the one that remained in the cell I'd originally pasted everything into) still wasn't working. Eventually I discovered that there were trailing newlines and that was why the variable name wasn't matching the {{name}} used in a request.

**Describe the solution you'd like**
A warning that trailing newlines in a variable name will cause it not to match (unless the same newlines appear inside the {{}} - not sure if you can put newlines inside {{name}} syntax, but it doesn't seem like a good idea to allow)

Don't disallow newlines entirely inside the Environment Variables editor dialog because then I wouldn't have been able to paste in the variables in the first place.

**Describe alternatives you've considered**
Re-typing all the variables manually

Not a big or serious issue just a minor convenience feature

**Comment by TheClassic** [comment]
This seems at least slightly related to https://github.com/postmanlabs/postman-app-support/issues/7882

**Comment by ritwijsinha** [comment]
Hey @elicoten 

We've introduced the feature for visualizing whitespaces and highlighting invalid characters.

To use this, please update to Postman 7.21.0 😄

For more info, go through this: https://learning.postman.com/docs/postman/sending-api-requests/requests/#troubleshooting-your-requests

Cheers! 🎉
