### ISSUE TITLE
Unable to download node js code from generate code snippet section

### ISSUE THREAD

**Issue by prasanna08cs** [a85/POSTMan-Chrome-Extension#7164]
**Describe the bug**
Unable to download node js code from **generate code snippet section**

**To Reproduce**
1. Go to  **CODE**
2. Click on **'select nodejs from dropdown'**
3.  after selecting the **node js nothing is happening**

**Expected behavior**
When i click on nodejs section i should be able to copy the code from  **generate code snippet section**

**Screenshots**
![postmna_err](https://user-images.githubusercontent.com/5313854/63435180-158ea180-c444-11e9-8d6d-f63419445c83.PNG)

![postman2](https://user-images.githubusercontent.com/5313854/63435446-8930ae80-c444-11e9-8b9a-08843064f3c2.PNG)

**App information (please complete the following information):**
 - App Type  Native App 
 - Postman Version Postman v7.5.0
 - OS: Windows 10

**Additional context**
Please fix the issue asap

**Comment by preethammavin** [comment]
@prasanna08cs on hovering on the nodejs listing you should see a nested list of options show up, can you check if they are showing up as clicking on one of them is what generates the code

**Comment by prasanna08cs** [comment]
Hi,

Thanks for the response.

I tried to hover/click on nodejs listing but the nested list is not
displayed.
if any  doc or video is available to do the same  will be helpful



Prasanna Kumar K G

**Comment by shreys7** [comment]
@prasanna08cs The list is present there but it has become x-scrollable. You need to scroll on the x-axis to get the nested list for the nodejs snippets.
We are working on fixing this. Meanwhile an alternative solution can be to switch the App to full screen mode, and then the nested list would be displayed on hovering.

**Comment by prasanna08cs** [comment]
Hi,

Thanks for the update.

Your suggestion is working fine.


Prasanna Kumar K G
