### ISSUE TITLE
"Something Went Wrong" on user removal

### ISSUE THREAD

**Issue by chrisdeso** [a85/POSTMan-Chrome-Extension#7165]
**Describe the bug**
When removing a user from a team, an error is thrown stating that `Something went wrong`.

**To Reproduce**
1. Navigate to team management page
2. Click on the removal icon next to a user's info
3. Confirm removal on next page

**Expected behavior**
Users are expected to be removed, or more informational messaging should be surfaced.

**Screenshots**
![image](https://user-images.githubusercontent.com/4734306/63451998-e27bec00-c40a-11e9-9fd8-cfc3d91d8a6c.png)

**App information (please complete the following information):**
 - App Type: Native
 - Postman Version: 7.4+
 - OS:

**Additional context**
Filed by Postman

**Comment by DannyDainton** [comment]
Hey @chrisdeso 

Is this one still valid?

**Comment by chrisdeso** [comment]
@DannyDainton Nope – closing it out, thanks!
