### ISSUE TITLE
Invoice Emails being sent to incorrect users

### ISSUE THREAD

**Issue by robinbastien** [a85/POSTMan-Chrome-Extension#7168]
**Describe the bug**
I am receiving Postman Pro invoices for the company I work for, when I shouldn't be.

**To Reproduce**
1. Create a postman account
2. Sign up to Pro
3. Add a new user, set them as admin
4. Have your initial user's role changed from owner/admin down to viewer
5. Turn off billing emails on your initial user account

**Expected behavior**
Invoices are dispatched to the new account holder / admins with billing notifications turned on, and not sent to people under a non-administrative role.

**Screenshots**
I no longer have access to the admin account, but these screenshots correspond to one another. Despite not having access to billing, I still receive the email. I can also successfully download the invoice.
<img width="959" alt="Screen Shot 2019-08-21 at 5 05 00 PM" src="https://user-images.githubusercontent.com/2096859/63468451-eec96e80-c435-11e9-8366-d9376bd32c8e.png">
<img width="1088" alt="Screen Shot 2019-08-21 at 5 03 45 PM" src="https://user-images.githubusercontent.com/2096859/63468452-eec96e80-c435-11e9-8930-c3807dfd316b.png">

**App information (please complete the following information):**
 - Firefox / Web

**Comment by chrisdeso** [comment]
@robinbastien It looks like you're listed as the `Billing Contact` for the team – would you be able to open a ticket via our support center so that we can confirm the email address(es) / team in question?

- Support page – https://www.getpostman.com/support

A billing admin should be able to update the billing contact (email address) via the billing details page.

- https://go.postman.co/settings/team/billing-details

**Comment by cyrielle-hada** [comment]
_Reporting the same issue on behalf of a user._ 

The billing email registered is a different email. 
However, the user continues to receive the invoice as if his email was registered as the billing email.

**Comment by chrisdeso** [comment]
@robinbastien It looks like you're still listed as the billing contact for your Postman team – if you'd like to have that changed, please reach out to us via our support page or make the updates via the team's dashboard.

* **Support Page** – https://www.getpostman.com/support
* **Updating Billing Details** – https://learning.getpostman.com/docs/postman_pro/managing_postman_pro/team_settings/#billing-details

@cyrielle-hada The underlying issue you reported has been fixed. Closing this issue out.
