### ISSUE TITLE
Postman's not working 

### ISSUE THREAD

**Issue by fullm3tal** [a85/POSTMan-Chrome-Extension#7171]
**Describe the bug**
Unable to get any response whenever I make any request from Postman:
Error Message: 

Could not get any response
There was an error connecting to .
Why this might have happened:
The server couldn't send a response:
Ensure that the backend is working properly
Self-signed SSL certificates are being blocked:
Fix this by turning off 'SSL certificate verification' in Settings > General
Proxy configured incorrectly
Ensure that proxy is configured correctly in Settings > Proxy
Request timeout:
Change request timeout in Settings > General 

I'm unable to uninstall Postman app from my system.

I logged myself out of the Postman App and then tried relogging, but I get the error message :

Something went wrong!
We're having some difficulties connecting to our authentication service. Try again after some time. 
And Now I cant login to Postman.

**App information:**
 - Native App
 - Postman Version 7.3.4
 - OS: Windows 64

**Comment by preethammavin** [comment]
@fullm3tal can you check if the issue persists on other networks and if your current network is behind a proxy? can you update to our lates application as well? 
If you continue to be blocked can you write to us at help@getpostman.com with logs so that we can take a closer look?

**Comment by preethammavin** [comment]
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Comment by shaibaz02** [comment]
From yesterday onwards I'm also facing the same issue unable to login to postman account when click on sign in.
![image](https://user-images.githubusercontent.com/79316992/125190077-fdeb7c80-e258-11eb-8bbe-363677cddfe1.png)

**Comment by enchhuang** [comment]
me too, same issue

**Comment by faramarzaf** [comment]
Also getting the same problem on Windows10 64-bit
Postman Version 8.7.0

**Comment by Webby28** [comment]
Same issue here.

**Comment by mjasimuddin** [comment]
![image](https://user-images.githubusercontent.com/35954711/195503895-ba86b3aa-b8ed-46de-bee9-882138df9a95.png)
I was facing authentication issues from last one week

**Comment by preethammavin** [comment]
@mjasimuddin hey, can you write to us at hel@postman.com , so that we can take a deeper look
