### ISSUE TITLE
Unable to login even after resetting the password.

### ISSUE THREAD

**Issue by ashwini0529** [a85/POSTMan-Chrome-Extension#7172]

**Comment by preethammavin** [comment]
@ashwini0529 can you provide details regarding the issue so that we can take a look at it? are you trying to login via the App/Browser, if its the app which version and platform of the App is it.

**Comment by numaanashraf** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
