### ISSUE TITLE
Running a mock service locally

### ISSUE THREAD

**Issue by Fleuv** [a85/POSTMan-Chrome-Extension#7174]
**Is your feature request related to a problem? Please describe.**
Not really although, running the mock service locally would help me a lot. Because I'm one of those developers who is on the road a lot. Thus my internet connection is not always that up beat. Therefor running my whole development environment locally would be the preferred way.

**Describe the solution you'd like**
Well I could build a software solution to this problem myself. By using the collection export to generate a mock API and launch it in some kind of environment. However I would rather make use of the current version of the collection like how the mock service currently does it. So every time you save the collection it also updates the Mock API.

**Comment by a85** [comment]
We don't have any plans for providing local support for running mocks. They will continue to be a hosted cloud service. There are multiple solutions out there for running local mocks and I'd recommend using those.

**Comment by windymindy** [comment]
> We don't have any plans for providing local support for running mocks. They will continue to be a hosted cloud service. There are multiple solutions out there for running local mocks and I'd recommend using those.

Would it require having a separate API description for a mocking tool?
Is there a way to develop a pluging for postman to hadle this specific need?
