### ISSUE TITLE
Team logo not updated on docs page

### ISSUE THREAD

**Issue by JP-from-Postman** [a85/POSTMan-Chrome-Extension#7175]
**Describe the bug**
User updated their team logo, and waited overnight, but the logo reflected on their documentation page still shows the default Postman logo.

**To Reproduce**
1. Go to docs page (see internal notes for link)
2. See default logo still present

**Expected behavior**
Updating logo reflects on published documentation pages within a short time

**Screenshots**

**App information (please complete the following information):**
 - App Type: Web dashboard
 - Postman Version: N/A
 - OS: N/A

**Additional context**
See internal notes for link

**Comment by JP-from-Postman** [comment]
Update: Collection is owned by someone no longer on the team

**Comment by Cazaimi** [comment]
@JP-from-Postman , investigating this. Will post updates on this thread.

**Comment by Cazaimi** [comment]
We’ve found the root cause for this and the fix should be out soon. Stay tuned!

**Comment by Cazaimi** [comment]
@Raja-Simha, this issue has been solved and can be marked as closed.
