### ISSUE TITLE
Can't sign in

### ISSUE THREAD

**Issue by JP-from-Postman** [a85/POSTMan-Chrome-Extension#7177]
**Describe the bug**
User report:

_Using the latest Postman for Windows 64-bit, I signed out, but cannot sign in, using Google email account results in the following error message. Also, unable to sign in using Postman account as some unknown account is showing._

![image (1)](https://user-images.githubusercontent.com/43283131/63555042-50501280-c4f4-11e9-920f-eb32243955a7.png)

Email address on login screen appears to be different than user's account email. 

Clearing local files allowed the user to login successfully.

**To Reproduce**
Unknown

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. Please make sure the screenshot does not contain any sensitive information such as API keys or access tokens. 

**App information (please complete the following information):**
 - App Type: Native app
 - Postman Version: 7.5.0
 - OS: Windows (64-bit)

**Additional context**

**Comment by preethammavin** [comment]
@JP-from-Postman the user tried to login with a different email than the one he was currently working with hence the info, check the ticket again he does confirm two email ids when he was login in.
