### ISSUE TITLE
Min 5 char limit not respected when naming team URL (workspace creation)

### ISSUE THREAD

**Issue by SmoothwallTester** [a85/POSTMan-Chrome-Extension#7178]
**Describe the bug**
When a user is creating a new team workspace they are informed it is a min of 5 characters.  However, a 5 character string is not accepted.

**To Reproduce**
1. Go to create new workspaces
2. Enter a 5 character team URL (e.g. crmgt)
3. Attempt to save

**Expected behavior**
After speaking with Danny Dainton over twitter, neither of us are sure why this 5 character boundary exists.  My preferred fix would be to extend this limit and amend the copy accordingly - however, if a 4 character min limit is indeed valid the copy should be updated.

**Screenshots**
![image](https://user-images.githubusercontent.com/54438403/63586673-d07c8380-c599-11e9-98a4-e32c8eb3575c.png)

**App information (please complete the following information):**
 - Native App
 - Postman Version 7.5.0
 - OS: Windows 10

**Additional context**

**Comment by abhijitkane** [comment]
The min. length limit exists to ensure some common words are not taken up by teams. We'll be updating the messaging to be consistent - "must have a minimum of 6 characters".

**Comment by DannyDainton** [comment]
Closing this issue as it has now been resolved.
Please feel free to reopen with the steps to reproduce if the issue persists.
