### ISSUE TITLE
Importing Swagger yaml without host field from URL should set API host name to that used in the URL

### ISSUE THREAD

**Issue by rimas-kudelis** [a85/POSTMan-Chrome-Extension#7180]
**Describe the bug**
According to [Swagger documentation](https://swagger.io/docs/specification/2-0/api-host-and-base-path/), the `host` field is not mandatory and if "...not specified, it is assumed to be the same host where the API documentation is being served."

However, when Postman imports Swagger JSON definition from a URL, it doesn't set the hostname if it isn't explicitly specified in the JSON file. I think this is a bug.

**To Reproduce**
1. Open Postman
2. Click **Import**
3. Select **Import From Link**
4. Paste a link to a swagger JSON file without a host field. (e.g. https://demo.sylius.com/api/v2/docs.json)
5. Click **Import**

**Expected behavior**
The imported API should automatically use same host as the one the file was imported from.

**Actual behavior**
All calls point to _http:///something_. Note the three consecutive slashes indicating missing host name.

**App information**
 - App Type: Native App
 - Postman Version: 6.7.1
 - OS: Ubuntu Linux 18.04

**Comment by postman-kenji** [comment]
@rimas-kudelis can you please try to reproduce the same in the latest version of Postman, and reopen this issue if it continues to be a broken experience? Thanks! cc: @abhijitkane

**Comment by rimas-kudelis** [comment]
This is not fixed, although the fact that a `{{baseUrl}}` variable is now added automatically makes the problem much less severe: I only have to edit the URL once per collection instead of once per request as before (presumably).

I've added a link  to a demo swagger file, which exhibits this problem. I hope you can test with that link yourselves next time.

Note: I imported this file as a Collection, not as an API. Not sure if this makes any difference.

P.S. I can't reopen issues here.
