### ISSUE TITLE
Client certificate rejected

### ISSUE THREAD

**Issue by hzlpsd2** [a85/POSTMan-Chrome-Extension#7181]
**Describe the bug**
Client certificate is rejected because ca md is supposedly too weak. The certificate used employs SHA-256 however. The problem crept in with Postman version 7.3.4.

**To Reproduce**
1. Go to Settings -> Certificates
2. Add certificate
3. Open Postman Console
4. Send request using the certificate
5. See error in Postman Console: Error: error:140AB18E:SSL routines:SSL_CTX_use_certificate:ca md too weak

**Expected behavior**
Client certificate should be usable to establish a TLS-secured connection.

**Screenshots**
![Screen](https://user-images.githubusercontent.com/54443026/63597633-3c70e300-c5be-11e9-9892-e3e0a99adf57.PNG)

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version 7.5.0
 - OS: Windows 7

**Comment by codenirvana** [comment]
@hzlpsd2 looks like the certificate you are using is signed with an md5 hash which is no longer supported with OpenSSL 1.1.0.

Is it possible for you to regenerate the certificate and use a stronger hash to sign?
Alternatively, I suppose turning OFF `SSL certificate verification` setting will fix this issue.

![Screenshot 2019-09-19 at 12 02 07 AM](https://user-images.githubusercontent.com/4865836/65175670-eda95280-da70-11e9-9ca2-5a064a65c95f.png)

**Comment by hzlpsd2** [comment]
[CRT.zip](https://github.com/postmanlabs/postman-app-support/files/3630040/CRT.zip)
Attached the certificate in question. As already pointed out, the signature hash algorithm used is SHA-256. Also, turning SSL certificate verification off does not fix the issue.
