### ISSUE TITLE
Logo upload throws 401 error

### ISSUE THREAD

**Issue by chrisdeso** [a85/POSTMan-Chrome-Extension#7182]
**Describe the bug**
Uploading a logo to a team page throws a `Something Went Wrong` error with a `401 - Unauthorized` in the console.

**To Reproduce**
1. Go to `https://go.postman.co/settings/team/general`
2. Click on `General`
3. Scroll down to `Logo
4. Use the `Edit` icon to upload a new logo
5. See errors

**Expected behavior**
Logos should be uploaded and/or meaningful error messages should populate (size, file type, etc)

**Screenshots**
![image](https://user-images.githubusercontent.com/4734306/63614069-c82b4500-c5a7-11e9-9cfe-4ff3cd742aff.png)

**App information (please complete the following information):**
 - Component: Web Dashboard

**Additional context**
Filed by Postman

**Comment by DannyDainton** [comment]
Hey @chrisdeso - Is this still an issue on the latest version? Would you mind verifying, please?

**Comment by chrisdeso** [comment]
The issue was resolved – closing :)
