### ISSUE TITLE
Can't login using Google SSO

### ISSUE THREAD

**Issue by JP-from-Postman** [a85/POSTMan-Chrome-Extension#7183]
**Describe the bug**
User unable to login using Google SSO. After logging in, the startup loading spinner shows indefinitely, but the app never loads the actual UI.

Reseting password via dashboard allows login via email + password (instead of Google SSO), but doesn't resolve the Google login issue. When trying to reset password from app window, no captcha is shown, meaning password reset request cannot be completed.

Clearing local files did not resolve the issue.

**To Reproduce**
(Support unable to reproduce)
1. Attempt to sign-in using Google SSO
2. Loading spinner shows, but main app UI never loads

**Expected behavior**
Sign-in via Google SSO is successful.

**Screenshots**
![1](https://user-images.githubusercontent.com/43283131/63614803-c1e19c80-c598-11e9-8f89-298b2851f78e.PNG)
![2](https://user-images.githubusercontent.com/43283131/63614807-c4dc8d00-c598-11e9-90aa-554724af193c.PNG)

**App information (please complete the following information):**
 - App Type : Native app
 - Postman Version: 7.5.0
 - OS: Windows 7, 64-bit

**Additional context**
Internal tracking for details.

**Comment by Qiqia** [comment]
我遇到了同意的情况

**Comment by Qiqia** [comment]
![TIM图片20190826110446](https://user-images.githubusercontent.com/8153699/63662530-5f370d80-c7f1-11e9-8fa2-50b0015802b0.png)

**Comment by preethammavin** [comment]
@Qiqia can you check if you are able to login via the browser at http://go.postman.co. This looks like your network might be blocking our services. Also do let me know if the issue also happens on other internet network.

**Comment by Qiqia** [comment]
> @Qiqia can you check if you are able to login via the browser at http://go.postman.co. This looks like your network might be blocking our services. Also do let me know if the issue also happens on other internet network.

![image](https://user-images.githubusercontent.com/8153699/63664212-38300a00-c7f8-11e9-8a29-ea417f227990.png)
I can login var via the browser plugin

**Comment by preethammavin** [comment]
@Qiqia can you run this collection in the native app and let me know of the results ? https://documenter.getpostman.com/view/6314135/SVfJTB7J?version=latest

**Comment by Qiqia** [comment]
> @Qiqia can you run this collection in the native app and let me know of the results ? https://documenter.getpostman.com/view/6314135/SVfJTB7J?version=latest

![image](https://user-images.githubusercontent.com/8153699/63667501-9f54bb00-c806-11e9-85f4-c2ff8d2e0bd8.png)
var browser plugin
![image](https://user-images.githubusercontent.com/8153699/63667524-b5fb1200-c806-11e9-8a66-ff9696787835.png)

var app

![image](https://user-images.githubusercontent.com/8153699/63667537-c57a5b00-c806-11e9-9b27-16a65211181b.png)

var browser

**Comment by Qiqia** [comment]
> @Qiqia can you run this collection in the native app and let me know of the results ? https://documenter.getpostman.com/view/6314135/SVfJTB7J?version=latest

![image](https://user-images.githubusercontent.com/8153699/63667667-3d488580-c807-11e9-8f6f-2732f6e76180.png)
![image](https://user-images.githubusercontent.com/8153699/63667701-57826380-c807-11e9-9fd3-0c76c685e7ab.png)

var app without proxy

**Comment by preethammavin** [comment]
@Qiqia the when you go to the url on the web you should get a collection which you import and run in your app. Sorry for not being clear earlier.

**Comment by Qiqia** [comment]
> @Qiqia the when you go to the url on the web you should get a collection which you import and run in your app. Sorry for not being clear earlier.

It cause by my proxy

**Comment by preethammavin** [comment]
Thanks for confirming closing the issue for now
