### ISSUE TITLE
How to import Swagger with transformed Postman Variable names

### ISSUE THREAD

**Issue by davidjgonzalez** [a85/POSTMan-Chrome-Extension#7184]
I have a set of Swagger file that define the parameters in the usual manner. For instance..

```
  parameters:
        - $ref: '#/parameters/authorization'
...
parameters:  
  authorization:
    name: Authorization
    description: ''
    required: true
    type: string
    in: header
```
Upon importing these file into Postman, the Postman collection is correctly created, however I'd like the Postman variable for the "Authorization" parameter to be "AUTH_TOKEN" instead of "Authorization" (for instance). 

Effectively, I want to declare a field (ideally in the swagger file?) that says "when exported to Postman, used the value AUTH_TOKEN as the variable name, instead of the default 'name' of "Authorization").

It seemed like `x-postman-meta` in the swagger might help with, but didn't find any info on this property outside of the GH issue on here saying it might help.

Anyhow - how can I achieve this?

Thanks!

**Comment by edargelies** [comment]
I've found a way to do this, although it doesn't feel good from a OpenAPI/Swagger perspective.  What I found is you can add a "default" property with your variable name e.g.

        {
          "in": "header",
          "name": "Authorization",
          "description": "The bearer token in the format: Bearer {token}",
          "required": true,
          "type": "string",
          "default": "Bearer {{token}}"
        }

This feels bad because what the default property actually is for:
> Use the default keyword in the parameter schema to specify the default value for
> an optional parameter. The default value is the one that the server uses if the
> client does not supply the parameter value in the request. The value type must
> be the same as the parameter’s data type.

So this wouldn't work if you had a integer type that you wanted to fill with a variable.  Additionally, from a documentation standpoint it's plain wrong, the server requires this parameter to be provided by the client, it can't also have a default value, that's contradictory.  Would be interested in a more "feel-good" solution.

Reference:
https://swagger.io/docs/specification/describing-parameters/

**Comment by postman-kenji** [comment]
@abhijitkane any updates on this, or will this be considered as won't fix?

**Comment by VShingala** [comment]
@davidjgonzalez You can use `example` value in API definition to define the value to be used for Authorization header. Below is sample definition that I'm importing.

```
openapi: "3.0.0"
info:
  version: 1.0.0
  title: Swagger Petstore
  license:
    name: MIT
servers:
  - url: http://petstore.swagger.io/v1
paths:
  /pets:
    get:
      summary: List all pets
      operationId: listPets
      tags:
        - pets
      parameters:
        - $ref: '#/components/parameters/authorization'
      responses:
        '200':
          description: An paged array of pets
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:    
              schema:
                $ref: "#/components/schemas/Pets"
components:
  parameters:  
    authorization:
      name: Authorization
      description: 'Auth value'
      required: true
      in: header
      schema:
        type: string
      example: 'AUTH_TOKEN'
  schemas:
    Pet:
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        tag:
          type: string
    Pets:
      type: array
      items:
        $ref: "#/components/schemas/Pet"
```

To configure this behaviour, you have to update options used for generating collection. You can do so by going to `View Import settings` button after selecting your files.

![Image](https://github.com/postmanlabs/postman-app-support/assets/16756296/5c3b1382-974c-4bb2-bff4-1fc483265509)

 Under these settinga, make sure `Parameter generation` option is set to `Example` and `Keep implicit headers` option is enabled.

![Image](https://github.com/postmanlabs/postman-app-support/assets/16756296/bd24eb76-5aa0-456b-a0e2-3e572156345c)

With above settings, here's what will be generated for corresponding request.

![Image](https://github.com/postmanlabs/postman-app-support/assets/16756296/55cd95ba-5685-41cb-8cad-e273774e3706)
