### ISSUE TITLE
Mark archived collection when downloading data from app

### ISSUE THREAD

**Issue by xk0der** [a85/POSTMan-Chrome-Extension#7190]
**Is your feature request related to a problem? Please describe.**
When downloading data from the Postman client, if there are archived collections and some new collection were created with the same name, it becomes difficult to find out which collection was archived and which are the new ones.

The only way it to manually go over the collections and determine which were archived.

**Describe the solution you'd like**
Mark the collections with a field saying whether it was an active collection or archived.
Maybe having the creation date might help too?

**Describe alternatives you've considered**
None available.

**Additional context**
Filed on behalf of a user.

**Comment by DannyDainton** [comment]
Collections are no longer archived in the Postman platform. I'm going to close this for now but if this is something that you see happening in the latest version, we can look at reopening it.
