### ISSUE TITLE
"Run in Postman" button doesn't import environment

### ISSUE THREAD

**Issue by zatziky** [a85/POSTMan-Chrome-Extension#7192]
**Describe the bug**
I'm able to import a collection but the environment is missing. 

**To Reproduce**
1. Click the button from FireFox (in Chrome it won't open Postman app at all):
[![Run in Postman](https://run.pstmn.io/button.svg)](https://app.getpostman.com/run-collection/319f51422f4252097c0e#?env%5Bamio%5D=W3sia2V5Ijoic2VydmVyX3VybCIsInZhbHVlIjoiaHR0cHM6Ly9hcGkuYW1pby5pbyIsImVuYWJsZWQiOnRydWV9LHsia2V5IjoiYXBpX3ZlcnNpb24iLCJ2YWx1ZSI6Ii92MSIsImVuYWJsZWQiOnRydWV9LHsia2V5IjoiYWNjZXNzX3Rva2VuIiwidmFsdWUiOiJ7e1RPX0JFX1NFVH19IiwiZW5hYmxlZCI6dHJ1ZX0seyJrZXkiOiJhbWlvX2NoYXQuY2hhbm5lbC5pZCIsInZhbHVlIjoie3tUT19CRV9TRVR9fSIsImVuYWJsZWQiOnRydWV9LHsia2V5IjoiYW1pb19jaGF0LmNvbnRhY3QuaWQiLCJ2YWx1ZSI6Int7VE9fQkVfU0VUfX0iLCJlbmFibGVkIjp0cnVlfSx7ImtleSI6ImZiLmNoYW5uZWwuaWQiLCJ2YWx1ZSI6Int7VE9fQkVfU0VUfX0iLCJlbmFibGVkIjp0cnVlfSx7ImtleSI6ImZiLmNvbnRhY3QuaWQiLCJ2YWx1ZSI6Int7VE9fQkVfU0VUfX0iLCJlbmFibGVkIjp0cnVlfSx7ImtleSI6ImZiLmNvbnRhY3QucGhvbmVfbnVtYmVyIiwidmFsdWUiOiJ7e1RPX0JFX1NFVH19IiwiZW5hYmxlZCI6dHJ1ZX0seyJrZXkiOiJmYi5jb250YWN0LmZpcnN0X25hbWUiLCJ2YWx1ZSI6Int7VE9fQkVfU0VUfX0iLCJlbmFibGVkIjp0cnVlfSx7ImtleSI6ImZiLmNvbnRhY3QubGFzdF9uYW1lIiwidmFsdWUiOiJ7e1RPX0JFX1NFVH19IiwiZW5hYmxlZCI6dHJ1ZX0seyJrZXkiOiJmYi5jb250YWN0LnVzZXJfcmVmIiwidmFsdWUiOiJ7e1RPX0JFX1NFVH19IiwiZW5hYmxlZCI6dHJ1ZX0seyJrZXkiOiJmYi5hY2Nlc3NfdG9rZW4iLCJ2YWx1ZSI6Int7VE9fQkVfU0VUfX0iLCJlbmFibGVkIjp0cnVlfSx7ImtleSI6Im1vYmlsZS5jaGFubmVsLmlkIiwidmFsdWUiOiJ7e1RPX0JFX1NFVH19IiwiZW5hYmxlZCI6dHJ1ZX0seyJrZXkiOiJtb2JpbGUuY29udGFjdC5pZCIsInZhbHVlIjoie3tUT19CRV9TRVR9fSIsImVuYWJsZWQiOnRydWV9LHsia2V5IjoibW9iaWxlLmNvbnRhY3QucGhvbmVfbnVtYmVyIiwidmFsdWUiOiJ7e1RPX0JFX1NFVH19IiwiZW5hYmxlZCI6dHJ1ZX0seyJrZXkiOiJyYm0uY2hhbm5lbC5pZCIsInZhbHVlIjoie3tUT19CRV9TRVR9fSIsImVuYWJsZWQiOnRydWV9LHsia2V5IjoicmJtLmNvbnRhY3QucGhvbmVfbnVtYmVyIiwidmFsdWUiOiJ7e1RPX0JFX1NFVH19IiwiZW5hYmxlZCI6dHJ1ZX0seyJrZXkiOiJ0ZWxlZ3JhbS5jb250YWN0LmlkIiwidmFsdWUiOiJ7e1RPX0JFX1NFVH19IiwiZW5hYmxlZCI6dHJ1ZX0seyJrZXkiOiJ0ZWxlZ3JhbS5jaGFubmVsLmlkIiwidmFsdWUiOiJ7e1RPX0JFX1NFVH19IiwiZW5hYmxlZCI6dHJ1ZX0seyJrZXkiOiJ2aWJlcl9ib3QuY2hhbm5lbC5pZCIsInZhbHVlIjoie3tUT19CRV9TRVR9fSIsImVuYWJsZWQiOnRydWV9LHsia2V5IjoidmliZXJfYm90LmNvbnRhY3QuaWQiLCJ2YWx1ZSI6Int7VE9fQkVfU0VUfX0iLCJlbmFibGVkIjp0cnVlfSx7ImtleSI6InZpYmVyX2JvdC5hY2Nlc3NfdG9rZW4iLCJ2YWx1ZSI6Int7VE9fQkVfU0VUfX0iLCJlbmFibGVkIjp0cnVlfSx7ImtleSI6InZpYmVyLmNoYW5uZWwuaWQiLCJ2YWx1ZSI6Int7VE9fQkVfU0VUfX0iLCJlbmFibGVkIjp0cnVlfSx7ImtleSI6InZpYmVyLmNvbnRhY3QucGhvbmVfbnVtYmVyIiwidmFsdWUiOiJ7e1RPX0JFX1NFVH19IiwiZW5hYmxlZCI6dHJ1ZX0seyJrZXkiOiJ2aWJlci5jb250YWN0LmlkIiwidmFsdWUiOiJ7e1RPX0JFX1NFVH19IiwiZW5hYmxlZCI6dHJ1ZX1d)
4. Postman opens, the collection is imported but the environment is not imported.

**Expected behavior**
The collection and environment are imported

**Screenshots**
If applicable, add screenshots to help explain your problem. Please make sure the screenshot does not contain any sensitive information such as API keys or access tokens. 
![image](https://user-images.githubusercontent.com/2794365/63679202-10897380-c7f1-11e9-9d55-bd9ad5f14f06.png)

**App information (please complete the following information):**
 - App Type - FireFox 68.0.2 (64-bit)
 - Postman Version - v7.5.0
 - OS: Windows 10 Pro

**Comment by godfrzero** [comment]
@zatziky What's the size of the environment here?

**Comment by zatziky** [comment]
@godfrzero I don't understand your question. How can I measure the size of it? All the items look this way:
![image](https://user-images.githubusercontent.com/2794365/63951674-79395000-ca7e-11e9-8b69-4e3311d1adae.png)
![image](https://user-images.githubusercontent.com/2794365/63951677-79d1e680-ca7e-11e9-9839-335c17db2c22.png)

**Comment by godfrzero** [comment]
Could you try exporting the environment? The filesize should give us a handle on the ballpark figure.

The reason I ask is because of https://github.com/postmanlabs/postman-app-support/issues/5209, which has to do with URL length limitations and the way we encode environment variable values. A fix for this has yet to be shipped out, and this affects environments with > N characters, where N depends on the browser handling the link click.

**Comment by zatziky** [comment]
The length of the encoded part behind `?` in the URL address is **2283 chars**. It indeed looks like we have exceeded the URL address length limitations. What workaround do you suggest? I'd suggest that you use some kind of compression on the already encoded string. 

@godfrzero Github doesn't allow me to share the file. The file size is:
![image](https://user-images.githubusercontent.com/2794365/63953242-46448b80-ca81-11e9-8b32-e1ef99610db9.png)

This is the content:

```json
{
	"id": "f9a29c3a-c568-474e-953e-b7a2011c2d2c",
	"name": "amio",
	"values": [
		{
			"key": "server_url",
			"value": "https://api.amio.io",
			"enabled": true
		},
		{
			"key": "api_version",
			"value": "/v1",
			"enabled": true
		},
		{
			"key": "access_token",
			"value": "{{TO_BE_SET}}",
			"enabled": true
		},
		{
			"key": "amio_chat.channel.id",
			"value": "{{TO_BE_SET}}",
			"enabled": true
		},
		{
			"key": "amio_chat.contact.id",
			"value": "{{TO_BE_SET}}",
			"enabled": true
		},
		{
			"key": "fb.channel.id",
			"value": "{{TO_BE_SET}}",
			"enabled": true
		},
		{
			"key": "fb.contact.id",
			"value": "{{TO_BE_SET}}",
			"enabled": true
		},
		{
			"key": "fb.contact.phone_number",
			"value": "{{TO_BE_SET}}",
			"enabled": true
		},
		{
			"key": "fb.contact.first_name",
			"value": "{{TO_BE_SET}}",
			"enabled": true
		},
		{
			"key": "fb.contact.last_name",
			"value": "{{TO_BE_SET}}",
			"enabled": true
		},
		{
			"key": "fb.contact.user_ref",
			"value": "{{TO_BE_SET}}",
			"enabled": true
		},
		{
			"key": "fb.access_token",
			"value": "{{TO_BE_SET}}",
			"enabled": true
		},
		{
			"key": "mobile.channel.id",
			"value": "{{TO_BE_SET}}",
			"enabled": true
		},
		{
			"key": "mobile.contact.id",
			"value": "{{TO_BE_SET}}",
			"enabled": true
		},
		{
			"key": "mobile.contact.phone_number",
			"value": "{{TO_BE_SET}}",
			"enabled": true
		},
		{
			"key": "rbm.channel.id",
			"value": "{{TO_BE_SET}}",
			"enabled": true
		},
		{
			"key": "rbm.contact.phone_number",
			"value": "{{TO_BE_SET}}",
			"enabled": true
		},
		{
			"key": "telegram.contact.id",
			"value": "{{TO_BE_SET}}",
			"enabled": true
		},
		{
			"key": "telegram.channel.id",
			"value": "{{TO_BE_SET}}",
			"enabled": true
		},
		{
			"key": "viber_bot.channel.id",
			"value": "{{TO_BE_SET}}",
			"enabled": true
		},
		{
			"key": "viber_bot.contact.id",
			"value": "{{TO_BE_SET}}",
			"enabled": true
		},
		{
			"key": "viber_bot.access_token",
			"value": "{{TO_BE_SET}}",
			"enabled": true
		},
		{
			"key": "viber.channel.id",
			"value": "{{TO_BE_SET}}",
			"enabled": true
		},
		{
			"key": "viber.contact.phone_number",
			"value": "{{TO_BE_SET}}",
			"enabled": true
		},
		{
			"key": "viber.contact.id",
			"value": "{{TO_BE_SET}}",
			"enabled": true
		}
	],
	"_postman_variable_scope": "environment",
	"_postman_exported_at": "2019-08-29T15:17:26.725Z",
	"_postman_exported_using": "Postman/7.5.0"
}
```

**Comment by preethammavin** [comment]
@zatziky the length of the environment which is created in the HTML page is trickier to handle. We have made changes into our documentation Run in Postman if the environment is published, in which case this limitation is lifted off. 

As I see from the variable names, some of them seem to fit better for collection variables than environment variables. Would suggest that as a workaround or publish the collection+environment as documentation which again would solve the problem.
