### ISSUE TITLE
Sync - Collections don't sync after session expires

### ISSUE THREAD

**Issue by cyrielle-hada** [a85/POSTMan-Chrome-Extension#7193]
**Describe the bug**
No data populate to the app after the session expiration. 

**To Reproduce**
1. Session expires > automatic log out of the account
2. Reset password for that account
3. Log back into the app for that account
4. The workspace looks empty and collections don't sync. 
5. The Sync icon is Red 

**Expected behavior**
All synced collections and environments should populate after signing into the app. 

**Screenshots**
![Sync issue](https://user-images.githubusercontent.com/47351631/63682984-1ed78f80-c7f1-11e9-9b7b-19348e193599.png)

**App information (please complete the following information):**
 - Mac OS
 - Postman Version 7.5.0

**Additional context**
- Collections can be located on the dashboard - https://go.postman.co/me/collections
- Sign out / Sign back in doesn't help
- Issue filed by Postman - See main logs inside the ticket.

**Comment by preethammavin** [comment]
@cyrielle-hada going through the issue, it looks like the collection that the user was waiting on syncing was still in progress. When a session re-authentication occurs if the users authenticates the session the sync will continue to work as expected, if the user signs-out and signs-in again then his/her collection will be re-synced to the Postman Client and might not be instantaneous.
