### ISSUE TITLE
Collection Import: query parameter and header description object is rendered as [object Object]

### ISSUE THREAD

**Issue by jGleitz** [a85/POSTMan-Chrome-Extension#7194]
**Describe the bug**
Even though it is documented as valid in the JSON schema, a description object in a query parameter or header is displayed incorrectly when importing a Postman collection. Instead of the actual description, the description reads `[object Object]`.

**To Reproduce**
<details>
<summary>Test Postman Collection JSON</summary>
<pre>
<code>
{
  "info": {
    "name": "Description Test API",
    "description": "Showcases a bug with descriptions on collection import",
    "schema": "https://schema.getpostman.com/json/collection/v2.1.0/collection.json"
  },
  "item": [
    {
      "id": "testrequest",
      "name": "Test Request",
      "description": {
        "content": "Where does this description even show up?",
        "type": "text/markdown"
      },
      "request": {
        "description": {
          "content": "A description object works fine _here_!",
          "type": "text/markdown"
        },
        "url": {
          "host": "{{baseUrl}}",
          "path": [
            "",
            "some",
            ":specific",
            "path"
          ],
          "query": [
            {
              "key": "queryWithDescriptionObject",
              "value": "",
              "disabled": false,
              "description": {
                "content": "This description is *not* displayed!",
                "type": "text/markdown"
              }
            },
            {
              "key": "queryWithDescriptionString",
              "value": "",
              "disabled": false,
              "description": "Description works if it is a `string`"
            }
          ],
          "variable": [
            {
              "key": "specific",
              "value": "",
              "type": "any",
              "description": {
                "content": "A description objects works _here_, too.",
                "type": "text/markdown"
              },
              "system": false,
              "disabled": false
            }
          ]
        },
        "method": "get",
        "header": [
          {
            "key": "HeaderWithDescriptionObject",
            "value": "",
            "disabled": false,
            "description": {
              "content": "This description is *not* displayed!",
              "type": "text/markdown"
            }
          },
          {
            "key": "HeaderWithDescriptionString",
            "value": "",
            "disabled": false,
            "description": "Description works if it is a `string`"
          }
        ]
      },
      "response": []
    }
  ]
}

</code>
</pre>
</details>

1. In Postman, click on “Import”, go to the “Paste Raw Text” tab.
2. Paste the Test Postman Collection JSON (see above)
3. Select the imported “Description Test API” and inspect the “Test Request”

**Expected behavior**
 * The description of `queryWithDescriptionObject` reads `This description is *not* displayed!`.
 * The description of `HeaderWithDescriptionObject` reads `This description is *not* displayed!`.

**Actual behavior**
 * The description of `queryWithDescriptionObject` reads `[object Object]`. 
 * The description of `HeaderWithDescriptionObject` reads `[object Object]`.

**Screenshots**
![query-parameter-wrong](https://user-images.githubusercontent.com/4305652/63689147-7c77d600-c809-11e9-9479-9f2342fde806.png)
![header-wrong](https://user-images.githubusercontent.com/4305652/63689882-797de500-c80b-11e9-9a20-de3ee6c2a91e.png)

Screenshots from https://schema.getpostman.com/collection/json/v2.1.0/draft-07/docs/index.html, which documents that a description object is allowed in a `QueryParam` and `Header`:
![queryparam](https://user-images.githubusercontent.com/4305652/63689231-b21cbf00-c809-11e9-9cf0-e08b06597750.png)
![header](https://user-images.githubusercontent.com/4305652/63689905-84d11080-c80b-11e9-87cd-af4e8936b140.png)

**App information:**
 - App Type: Native App
 - Postman Version: 7.5.0
 - OS: Ubuntu 19.04

**Comment by jGleitz** [comment]
I updated this issue because the bug affects not only query parameters, but also headers.

**Comment by Qix-** [comment]
Can be reproduced using the [pet store example OpenAPI specification](https://github.com/OAI/OpenAPI-Specification/blob/master/examples/v3.0/petstore.yaml).

![image](https://user-images.githubusercontent.com/885648/66682079-67012300-ec74-11e9-9062-d494aaf60e86.png)
