### ISSUE TITLE
Synced collection throwing 400 Bad Request when signed in as different network credentials 

### ISSUE THREAD

**Issue by stcalica** [a85/POSTMan-Chrome-Extension#7195]
**Describe the bug**
A user's synced collection is able to complete a collection run on a machine in the same network with different credentials than the user's local machine. 

> So, the issue is that specific to that users login on my local machine... weird!
>  
> Is there anything you're aware of that would cause this issue to happen? 
>  
> I ran netstat -a -b from cmd prompt and found that there appears to be more ports in which are "Listening" between the user credentials that do work vs the credential that does not. This gives some insight, but I do not know where to take it. 

**To Reproduce**
1. Login into a local machine and run the collection which returns a 400 bad request 
2. Login into other machines on the same network and run the same collection as the same Postman user as above. 

**Expected behavior**
A collection on the same Postman account should run on both machines on the same network

What we have tried: 

- Export collection from working machine and import into the local machine

- clear cache in local machine

- checked Proxy settings (there's no proxy) 

![Z36693-400-request](https://user-images.githubusercontent.com/5624835/63707792-97d1e980-c7e7-11e9-908f-d20a558ba497.png)

![Z36693-window-screenshot](https://user-images.githubusercontent.com/5624835/63707732-7b35b180-c7e7-11e9-992b-eeacb4ea4ad0.png)

![Z36693-headers-screenshot](https://user-images.githubusercontent.com/5624835/63707745-8092fc00-c7e7-11e9-8d8f-d62356c3ef8c.png)

**App information (please complete the following information):**
 - Postman v7.5 
 - Windows

**Comment by saswatds** [comment]
Hi. Can we confirm is the user is able to reach to your server with other tools like curl? This looks more like a networking issue rather than issue within postman. Still want to confirm.

**Comment by vvs11** [comment]
@stcalica closing this issue as there has been no response. Please feel free to reopen it in case you're facing it again
