### ISSUE TITLE
Inviting team members deleted personal collections

### ISSUE THREAD

**Issue by andremvb** [a85/POSTMan-Chrome-Extension#7196]
**Describe the bug**
I was trying to add members to add members to my workspace team; and suddently appears a notification that someone removed me from a team (that a I did not be part of ), and then my 3 collections has been removed,
**Screenshots**
My requests history
![image](https://user-images.githubusercontent.com/12978746/63711371-e3dd5800-c800-11e9-9ee6-d69e1cfa94d2.png)

My empty collections...
![image](https://user-images.githubusercontent.com/12978746/63711634-80075f00-c801-11e9-8f77-6c4528841927.png)

**App information (please complete the following information):**
 - Native App
 - Postman Version: 7.5.0
 - OS: Mojave, 10.14

**Comment by sankalp0o** [comment]
Hi @andremvb 
Workspaces are different from teams. There can be multiple workspaces in a team. Workspaces can also be personal.
Can you check if you're looking in the same workspace that your collections were in?

**Comment by andremvb** [comment]
Yep. I made that collections in my personal workspace. And testing that, I noticed that "History" are also related with the Workspace (I searched other workspaces, and I have only History in my Personal Workspace).
The same day that I reported the bug, I searched in the Trash also, and didn't found my collections.

![image](https://user-images.githubusercontent.com/12978746/63865435-3476c180-c977-11e9-89f3-84c3774f4cf0.png)
![image](https://user-images.githubusercontent.com/12978746/63865447-3a6ca280-c977-11e9-8ff5-a54485e3adb9.png)

**Comment by sankalp0o** [comment]
Thanks for the response @andremvb. This isn't supposed to happen and we will check this out.

**Comment by abhijitkane** [comment]
@andremvb Can you contact us at help@getpostman.com (from your registered email) referencing this issue ID (https://github.com/postmanlabs/postman-app-support/issues/7196)? We'll look through our logs and check what went wrong here.

**Comment by abhijitkane** [comment]
@andremvb Feel free to add a comment if you're unable to retrieve your collections.
