### ISSUE TITLE
Find/Search Functionality Stopped Working

### ISSUE THREAD

**Issue by labossieresr** [a85/POSTMan-Chrome-Extension#7198]
**Describe the bug**
Within Postman I can no longer find (search) on strings regardless of the scope (i.e. Everything, Open tabs). The search results don't seem to initiate and clicking Find does nothing.

**To Reproduce**
1. Open any request that has text in one of the tabs (i.e. Tests).
2. Select any word present (i.e. for the string var boolABC=true; select boolABC).
3. Either right-click and select Find _xxx_ (where _xxx_ is the text you just selected) or select the find/search icon (magnifying glass in bottom right) and type in for FIND the value boolABC to initiate the find process.
4.  No search results are returned.
This stopped working for me about 2-3 weeks ago.

**Expected behavior**
At this point I would have expected it to find every occurrence of the string I selected. I should be able to further filter on the WHERE clause, including selecting "Everything" or even "Open tabs" but it can't even find the string I just highlighted to find.

**Screenshots**
Included screenshot, which includes my version of Postman too.

**App information (please complete the following information):**
 - Native App
 - Postman Version: 7.5.0
 - OS: Windows 10

**Additional context**
None
![Annotation 2019-08-26 155133](https://user-images.githubusercontent.com/21041321/63718853-902b3880-c819-11e9-9471-6155e570ca5d.png)

**Comment by preethammavin** [comment]
@labossieresr can you update to the latest version of the app and try it again? I am unable to reproduce the issue on my end.

**Comment by labossieresr** [comment]
I am on 7.6.0 and I am still encountering the same issue. I did have
another team member check it out and it was working fine for them. They
checked their version and it said they needed to update to 7.6.0 though. So
the shut down the app and fired it back up. They are now on 7.6.0 and they
are still working fine. So it appears to be something with me at this point
in time. Suggestions?

**Comment by efiark** [comment]
I am having the same issue.  I can do a search in some of my Workspaces but not in one particular Workspace.   But others on my team can search in that Workspace.
Also if I search in one of the other Workspace, then try to search in the problem Workspace, I get the same information returned as I did for the previous search. (see below)

I have tried uninstalling and re-installing the app, but that didn't help.

- OS: Windows 7
- PM Version:  7.12.0
- Native App

I searched 'GoGreener' in one of the Workspaces where I can search.
Then returned to the problem Workspace, and tried searching for 'OWP Automation', the search returned with the results for 'GoGreener' again.
![image](https://user-images.githubusercontent.com/58056686/69391157-baf52380-0c86-11ea-8f54-682469244269.png)

Collections
![image](https://user-images.githubusercontent.com/58056686/69391320-54bcd080-0c87-11ea-97e8-00f670b4eed1.png)

**Comment by allyn-psyonix** [comment]
I'm having a sort of similar problem. Not sure if it's the same thing or if I should submit a new issue. Searching using the text box above the collections/history/api area on the left is not working properly. It lags HARD as soon as I start typing text. I've tried restarting the app and verified I am on the latest right now (7.18.0). ~5 seconds later, my input appears, but results are not filtered. Instead, results are expanded in the tree structure and the matching text is colored orange. It almost looks like this is intentional, but for the life of me I cannot figure out a compelling reason not to filter the list, so I believe this must be a bug. In my case the matching result was below the visible region so at first I thought the search did nothing at all.

**Comment by coditva** [comment]
@allyn-psyonix We're aware of the issue and are tracking this issue here: https://github.com/postmanlabs/postman-app-support/issues/8045

**Comment by 466725** [comment]
Surprisingly! I am using Postman v9.12.0 which is the latest version.

And I can reproduce this issue. My os is Windows 10

**Comment by kool79** [comment]
Same for me. But it does not work in 2nd postman window

**Comment by DannyDainton** [comment]
Hey @kool79 / @466725 

Could you provide a short recording of the issue, in the latest version of the platform?
