### ISSUE TITLE
Postman app is not syncing; the connection drops and app tries to reconnect repeatedly

### ISSUE THREAD

**Issue by harryi3t** [a85/POSTMan-Chrome-Extension#7200]
**Describe the bug**
The sync icon is always blue, no collections/environments are being synced. Tried switching to multiple team workspaces.
There are no errors in the console.

Also, tried the Canary app with the same account, but it didn't sync either.

**To Reproduce**
1. Try switching to any team workspace
2. Wait for it to sync
3. The sync goes into offline mode and then into syncing mode (repeats indefinitely)

**Expected behavior**
Any team Workspace should be able to sync.

**Screenshots**
![image](https://user-images.githubusercontent.com/5207331/63756546-3177c480-c8d6-11e9-8828-c4aef2dbbbe0.png)

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version: 7.5.0 
 - OS: macOS Mojave

**Comment by ankitjaggi** [comment]
@harryi3t This should be fixed now. Closing the issue.
