### ISSUE TITLE
Ability to define an environment locally

### ISSUE THREAD

**Issue by schrepfler** [a85/POSTMan-Chrome-Extension#7205]
**Is your feature request related to a problem? Please describe.**
I'd like to prevent a collection environment to be shared

**Describe the solution you'd like**
When managing an environment, a checkbox would mark an environment as local, this should prevent it from being shared server side.

**Describe alternatives you've considered**

**Additional context**

**Comment by shamasis** [comment]
Hey. I was wondering whether you have tried setting the “current value” of environment to store your data. The current value is never synced.

**Comment by schrepfler** [comment]
I haven't, good tip!
