### ISSUE TITLE
Not able to see the Code -v7.5.0

### ISSUE THREAD

**Issue by sri-miriyala** [a85/POSTMan-Chrome-Extension#7206]
**Describe the bug**
Am unable to see the code to send the request to others.

**To Reproduce**
1. Go to a specific request from your collection
2. click on send to execute the result
3. After that click on code to see the code that has been executed to see.
<img width="804" alt="Screen Shot 2019-08-27 at 12 59 21 PM" src="https://user-images.githubusercontent.com/38143240/63792021-b230c380-c8ca-11e9-9a9d-87982c585a1a.png">

4. It is empty.
<img width="721" alt="Screen Shot 2019-08-27 at 1 01 09 PM" src="https://user-images.githubusercontent.com/38143240/63792069-c7a5ed80-c8ca-11e9-8492-37fc7a2e1788.png">
5. Am unable to choose the request type from drop down. The default is HTTP.
**Expected behavior**
I should be able to see the code that got executed in different modes (HTTP/curl/ etc) when I click on code in the request tab.

**Screenshots**
If applicable, add screenshots to help explain your problem. Please make sure the screenshot does not contain any sensitive information such as API keys or access tokens. 

**App information (please complete the following information):**
 - MAC OS 
 - Postman Version -7.5.0
 

**Additional context**

**Comment by tonitagd** [comment]
I am also experiencing the same issue since the last version update of Postman.

**App information:**

- Windows 10 Enterprise
- Postman Version 7.6.0

**Comment by abhijitkane** [comment]
@sri-miriyala @tonitagd Can you check the app's console logs for any errors? These should be visible in View > Developer > Show DevTools (current view)

**Comment by mccannt** [comment]
Closing out this issue as there has been no response on additional information and it is not reproducible. 
Please feel free to reopen if you can reproduce this and provide us with additional information.
