### ISSUE TITLE
Reading Cookies: Fictional Documentation

### ISSUE THREAD

**Issue by mhornbacher** [a85/POSTMan-Chrome-Extension#7208]
**Describe the bug**
Documentation does not accurately reflect exposed API, leading to complex issues that are hard to resolve.

**To Reproduce**
1. Go to https://learning.getpostman.com/docs/postman/sending_api_requests/cookies/
2. Read the article
3. Attempt to implement

**Expected behavior**
Object returned from `pm.cookies.jar();` should contain `get` and `set` functions as documentation describes (for example "Creating a Cookie": https://learning.getpostman.com/docs/postman/sending_api_requests/cookies/#creating-a-cookie)

**Screenshots**
![image](https://user-images.githubusercontent.com/12478828/63807247-562a6700-c8eb-11e9-94ef-9334cc7b5850.png)

![image](https://user-images.githubusercontent.com/12478828/63807313-6e01eb00-c8eb-11e9-90c3-59a0e33a0ba4.png)

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version 7.5.0 (fresh install
 - OS: Windows 10 1903

**Comment by codenirvana** [comment]
@mhornbacher Programmatic cookie access APIs are available in the latest version of the Postman app (v7.6.0).
Looks like the documentation got  updated with the canary release last month, Know more: https://github.com/postmanlabs/postman-app-support/issues/3312#issuecomment-516965288

I understand your concern and we will make sure to document the availability (stable or canary app version) of the new features as well.

**Comment by mhornbacher** [comment]
@codenirvana cool! It seems the documentation is a portal to the future. I guess it is written while driving at 88mph 👍
