### ISSUE TITLE
Pressing the shortcut key to use "Two-pane view", does not update the toggle value in the Settings menu

### ISSUE THREAD

**Issue by Faz540** [a85/POSTMan-Chrome-Extension#7212]
**Video of Issue:**
https://www.loom.com/share/63e7191407484eee8f7049024d6656e2

**Bug Summary:**
If I press the shortcut key to toggle "Two-pane view" (Command + Option + V), the toggle value in the Settings menu is not updated.

This means the "Two-pane view" toggle in the Settings window can always be shown as "OFF", even though the user can activate this view by using the shortcut key.

**Postman Version:**
I'm currently using the Mac version of Postman version 6.7.4
I'm unable to confirm this issue on a Windows machine or the latest version of Postman

**Comment by nik72619c** [comment]
This bug is resolved in the new release `7.22` of the postman app.
