### ISSUE TITLE
Character "#" in collection variable xxxx breaks rendering {{xxxx}} in request

### ISSUE THREAD

**Issue by fpierrat** [a85/POSTMan-Chrome-Extension#7215]
Hi,
I'm new to Postman, maybe I just missed something?

I created a collection.
In this collection, variables, within which the "key" variable having initial value="ldkfj@22_7#".

In this collection, a request:
xyz.com/apitest/index.php?key={{key}}&lang={{lang}}

The sent request should be:
xyz.com/apitest/index.php?key=ldkfj@22_7#&lang=FR
but Postman actually sends:
xyz.com/apitest/index.php?key=ldkfj@22_7

Do I have to manually escape the "#" character in the "variables" list of the collection?
How?
Do I the have to explicitely unescape it if I use it in a script?

Thanks in advance

**Comment by codenirvana** [comment]
@fpierrat Yes you have to manually escape the `#` character to `%23`.

The problem with `#` is, anything after it is considered as URL's [fragment identifier](https://en.wikipedia.org/wiki/Fragment_identifier) which has special meaning for clients but not supposed to be sent or work similarly on servers.

To unescape in scripts, you can use the `unescape` function like this:
```js
var escaped = pm.variables.get('path');
var unescaped = unescape(escaped);
```
