### ISSUE TITLE
User receiving status 400 when clicking 

### ISSUE THREAD

**Issue by JP-from-Postman** [a85/POSTMan-Chrome-Extension#7219]
**Describe the bug**
[Reported by Postman Support, on behalf of original user]

**User report:**

_I am trying to view documentation for my collection. When I click the "View in web" button it brings up a "web.postman.co/collection" link that shows the loading icon and spits out the following error continuously in the console:_

_app.8bcaa064ef385673ce2b.js:21 WebSocket connection to 'wss://web.postman.co/socket.io/?fp=2019-08-28T15%3A10%3A14.047Z-913&__sails_io_sdk_version=1.2.1&__sails_io_sdk_platform=browser&__sails_io_sdk_language=javascript&EIO=3&transport=websocket' failed: Error during WebSocket handshake: Unexpected response code: 400 
CIKq.WS.doOpen @ app.8bcaa064ef385673ce2b.js:21 
app.8bcaa064ef385673ce2b.js:10 Error: websocket error 
at WS.Gbct.Transport.onError (app.8bcaa064ef385673ce2b.js:26) 
at WebSocket.ws.onerror (app.8bcaa064ef385673ce2b.js:21)_

_The same error happens if I try to access anything in the "https://web.postman.co/workspaces" environment. Tried with multiple browsers, same issue._

_I cannot log out of the web dashboard because I cannot access the web dashboard. As a workaround I cleared all postman cookies in my browser and tried again but no luck. I cannot access the web dashboard at all._

**To Reproduce**
1. Click `View in web` on a Collection in the Postman app
2. See web page load: web.postman.co/collection
3. Open browser console, see error
5. Postman Support Team Attempted to Reproduce (Yes)
6. Reproducible (No)

**Expected behavior**
- Collection's documentation page is displayed successfully
- Workspaces page loads successfully 

**App information (please complete the following information):**
 - App Type: Native app, Web dashboard (Chrome)
 - Postman Version: 7.5.0
 - OS: Windows

**Additional context**
See internal notes

**Comment by ankit-m** [comment]
Postman web dashboard requires a websocket connection to be established between the client (your browser) and our servers. Based on the console logs, it looks like the connection was not established. 

This can happen due corporate firewall restrictions, proxy settings or any network issue which disallows websocket connections. Please try switching to a home/mobile internet connection and check your proxy settings (if any).
