### ISSUE TITLE
getting "unrecognized network " code:error 400 in POSTMAN request Post

### ISSUE THREAD

**Issue by mirza-shazif** [a85/POSTMan-Chrome-Extension#7222]
**Describe the bug**
i just using Request POST in POSTMAN and sending xml code to test Staples API but i did not get any response i search lot of but did not get solution of problem(Attachment)

![Annotation 2019-08-28 192821](https://user-images.githubusercontent.com/41999877/63916987-fea70b00-ca52-11e9-890a-f46aa4fe135d.png)

**Comment by himanshu226** [comment]
@mirza-shazif Could you please provide more details of the request and the endpoint you are trying to hit? 
I checked for the Staples API, but it looks like their API docs page is not opening.
http://developer.staples.com/apis

**Comment by vvs11** [comment]
@mirza-shazif could you let us know if you're still facing the issue?

**Comment by SabriH10** [comment]
Hi @mirza-shazif,

I'll go ahead and close this for now. It doesn't look like http://developer.staples.com/apis is accessible. If you still require some assistance, please feel free to re-open and comment with additional information accessed above, and we'll be happy to help.
