### ISSUE TITLE
Code generated for curl (and HTTP) is wrong (v7.5.0)

### ISSUE THREAD

**Issue by nitram509** [a85/POSTMan-Chrome-Extension#7223]
**Describe the bug**
The code generated for Curl is wrong and contains incorrect Cookie header values. Hence it is not usable to copy&paste or to share with others. The code is broken.

Also, the code generated for "HTTP" is affected. That said, the procedure to reproduce only focusses on the curl code generation.

**To Reproduce**
1. Go to a new tab (starting from scratch)
2. Makes sure, you cleared all cookies before continuing next steps
3. Define the request:
    * GET: https://www.google.de
    * Headers: Cookie: test=1
4. Press {SEND} button ==> The result should look like this first screenshot "curl_code_generated_is_wrong__1_setup"
5. Press {CODE} button and select 'curl' ==> The ERROR is visible: the value for the cookie contains twice the text "test=1", but should only be once there. See the second screenshot "curl_code_generated_is_wrong__2_wrong_code.png"
6. Alter the cookie value to "test=2" (see the third screenshot "curl_code_generated_is_wrong__3_alter_cookie_value.png")
7. Press again {CODE} button ==> The ERROR is even worse, now both values (test=1 and test=2 are shown), see the fourth screenshot "curl_code_generated_is_wrong__4_even_more_wrong_code.png"

**Expected behavior**
The generated code for Curl should be correct, means only containing 1 cookie value - not the two visible.

**Screenshots**
"curl_code_generated_is_wrong__1_setup"
<img width="1375" alt="curl_code_generated_is_wrong__1_setup" src="https://user-images.githubusercontent.com/1189394/63924954-825bfa00-ca49-11e9-9408-27f1ddae49d4.png">

"curl_code_generated_is_wrong__2_wrong_code.png"
<img width="795" alt="curl_code_generated_is_wrong__2_wrong_code" src="https://user-images.githubusercontent.com/1189394/63925261-07dfaa00-ca4a-11e9-9c51-2ae0ffc4fd86.png">

"curl_code_generated_is_wrong__3_alter_cookie_value.png"
<img width="1376" alt="curl_code_generated_is_wrong__3_alter_cookie_value" src="https://user-images.githubusercontent.com/1189394/63925336-3198d100-ca4a-11e9-911f-782b026853db.png">

"curl_code_generated_is_wrong__4_even_more_wrong_code.png"
<img width="792" alt="curl_code_generated_is_wrong__4_even_more_wrong_code" src="https://user-images.githubusercontent.com/1189394/63925404-60af4280-ca4a-11e9-9b12-91ebb00f95cc.png">

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version: 7.5.0
 - OS: macOS High Sierra 10.13.6

**Additional context**
n/a

**Comment by shreys7** [comment]
Hey @nitram509  In Postman 7.2.1, we've introduced bug-fixes, support for two new languages (JS-Fetch and Powershell), and the ability to configure certain aspects of the generated snippet with the 'Experimental Codegen Mode' flag enabled in Postman's global settings.
This particular problem has been solved in the experimental codegen mode. Click on the Settings icon on top right -> Settings -> Experimental Codegen mode.

<img width="790" alt="Screenshot 2019-08-30 at 4 08 45 PM" src="https://user-images.githubusercontent.com/20665864/64014751-8c145900-cb40-11e9-816c-1becd97f8542.png">

**Comment by nitram509** [comment]
Hi,
thank you for that information - I will give it a try.

May I allowed giving some feedback?
I do propose to rethink the release strategy.
Letting people wait for bug fixes over 3 minor releases (7.3.x , 7.4.x and 7.5.x) causes frustration, IMHO. I understand though, that when you have a feature in beta-test, you want to wait with releasing bug fixes, because you might run into merge issues of your feature branches.
Anyway, my expectation is that bugs are fixed - or listed somewhere as known bugs - for transparency and reduce the chance of frustration.

That said. Thank you very much for all your effort in providing Postman - it's a great tool.
