### ISSUE TITLE
Improper redirection after verifying email

### ISSUE THREAD

**Issue by anudeepmedicharla** [a85/POSTMan-Chrome-Extension#7227]
**Describe the bug**
If I click on "head to your profile" once I verified my email, I am taken to "web.postman.co" instead of my team domain. Then I get "you don't have access" error because I am part of a team.

**To Reproduce**
Steps to reproduce the behaviour:
1. Verify your email which is part of a team
2. Click on "Head to your profile"
3. You can see that you are redirected to "web.postman.co" instead of your team.

**Expected behaviour**
I must be redirected to my currently signed in account regardless of whether I am part of a team or not.

**Screenshots**
If applicable, add screenshots to help explain your problem. Please make sure the screenshot does not contain any sensitive information such as API keys or access tokens. 

![Screenshot 2019-08-30 at 12 58 14 PM](https://user-images.githubusercontent.com/16399370/64003679-5f554700-cb2a-11e9-9279-17606eb94b35.png)
![Screenshot 2019-08-30 at 12 59 10 PM](https://user-images.githubusercontent.com/16399370/64003683-611f0a80-cb2a-11e9-83b2-e8965545e639.png)

**Comment by anudeepmedicharla** [comment]
@ankit-m What squad should this come under?

**Comment by DannyDainton** [comment]
Closing as I'm unable to recreate this issue on the latest version of the platform.
