### ISSUE TITLE
Build a Bulk upload requests in Postman

### ISSUE THREAD

**Issue by Poovendranavs** [a85/POSTMan-Chrome-Extension#7229]
In Postman, how to Built a Bulk upload requests and get output according to that request?

any one please guide me....

**Comment by preethammavin** [comment]
@Poovendranavs what is the workflow that you are looking to achieve? 

Also we have a pretty active community at `https://community.getpostman.com/` , feel free to post any future questions there so that it helps the community as well :)

**Comment by preethammavin** [comment]
@Poovendranavs closing the issue for now and feel free to reopen, let us know if our community was not able to address it.
