### ISSUE TITLE
Postman crashes while running GET in collection runner (large response)

### ISSUE THREAD

**Issue by mariefoltynova** [a85/POSTMan-Chrome-Extension#7232]
**Describe the bug**
The application crashes when running a GET request that has large response (34.42 MB, 518039 lines) in collection runner (there is no other request in the collection).

**To Reproduce**
1. In Collection runner, call a request that is expected to receive a large response
* environment is set
* 1 iteration
* 0 dealy
* no data file
* do not log response

**Expected behavior**
The app does not crash, the response is received

**Screenshots**
* Runner settings: https://share.getcloudapp.com/P8uWNnkb
* Postman stopped working: https://share.getcloudapp.com/geu0O6bk

**App information (please complete the following information):**
- App Type: Native App
- Postman v7.6.0
- OS: Windows 10

**Additional info**

- It didn't crash when I was using the older version (7.3.6)
- The response is received without any issue if the request is sent within the request builder (outside of the runner)
- If I send the request via Collection runner expecting a much smaller response, it does not crash

**Comment by mariefoltynova** [comment]
Hi, is it going to be fixed soon, please? It's really a big issue for us. The same happens on Linux.

**Comment by saswatds** [comment]
We have pushed all of our performance fixed to the stable version 7.18.0. The runner should be snappier and not crash. Can you update to the latest version and check if this issue is fixed for you?

**Comment by saswatds** [comment]
Closing this issue now as other users have reported that this issue is fixed for them.
