### ISSUE TITLE
Request tab shows [CONFLICT] for the deleted request on reopening the app

### ISSUE THREAD

**Issue by shivangibajpai12** [a85/POSTMan-Chrome-Extension#7233]
**Describe the bug**

- Delete the request opened in tab
- Close and reopen the app
- The request tab will show [CONFLICT] instead of [DELETED]

**To Reproduce**
1. Open a request in tab
![Screenshot 2019-08-30 at 6 48 09 PM](https://user-images.githubusercontent.com/14205640/64023807-bcff8880-cb56-11e9-9c96-0ab41cad5745.png)

2. Delete the request
![Screenshot 2019-08-30 at 6 49 07 PM](https://user-images.githubusercontent.com/14205640/64023904-def90b00-cb56-11e9-9692-f6c31d10902e.png)

3. Close the App
4. Open app again
5. The deleted tab shows [CONFLICT]
![Screenshot 2019-08-30 at 6 50 13 PM](https://user-images.githubusercontent.com/14205640/64023975-07810500-cb57-11e9-8843-eeb81df3613e.png)

**Expected behavior**
The deleted request tab should show [DELETED] even when reopening the app.

**App information (please complete the following information):**
 - Native app, Mac
 -  Postman version 7.6.0

**Comment by mccannt** [comment]
Closing this issue as it has now been resolved.
Please feel free to reopen with the steps to reproduce if the issue persists.
