### ISSUE TITLE
Change close tab keyboard shortcut to CTRL-W to match common usage

### ISSUE THREAD

**Issue by idevtech** [a85/POSTMan-Chrome-Extension#7234]
It would be helpful, and more consistent, w/ many other programs, e.g., browsers, if CTRL+W closed a tab.

**Comment by chris-torruella** [comment]
Hi @idevtech, thanks for your patience with this issue.
We recently implemented the capability to [customize your keyboard shortcuts](https://blog.postman.com/postman-customizable-keyboard-shortcuts/).
So, while it is not in our plans to change the defaults, you can tailor these to the best of your use cases.
Hope this helps.
