### ISSUE TITLE
A set of static IPs to allow for whitelisting for secured APIs

### ISSUE THREAD

**Issue by craigbertf** [a85/POSTMan-Chrome-Extension#7237]
**Is your feature request related to a problem? Please describe.**
Our APIs are IP whitelisted in order to reduce risk and be more secure.  We would very much like to use the Postman Monitors, but since we can't effectively whitelist the IPs from which the monitors work we can't use them.

**Describe the solution you'd like**
The Monitors should have static IPs so that they can be whitelisted.

**Comment by asi-postman** [comment]
@craigbertf This is Anthony from Product Support. We do have this feature available for Enterprise Plans. I have reopened our existing ticket for further discussion regarding the static IP. I also included a link below that highlights differences between each Postman Plan.

https://www.getpostman.com/pricing

**Comment by ArjunSingh-PM** [comment]
This feature is available for Enterprise and Business plans.

Plan information - https://www.postman.com/pricing/
Info on Static IP - https://learning.postman.com/docs/postman/monitors/using-static-IPs-to-monitor/
