### ISSUE TITLE
Issue with Postman Monitor

### ISSUE THREAD

**Issue by Raj-postman** [a85/POSTMan-Chrome-Extension#7238]
**Describe the bug**
Monitor tests keep failing as the variables aren't being resolved. After creating a brand new monitor with the same collection and environment of the failed monitor, it runs as expected.

**To Reproduce**
1. Create a Monitor for the collection
2. Check test results
3. Environment variables do not resolve which cause monitors to fail
4. Error: Invalid URI "http:///%7B%7Bpos-url%7D%7D"

**Expected behavior**
Be able to check the monitor results

**Screenshots**
![MonitorIssue](https://user-images.githubusercontent.com/47771757/63998890-d3d6b880-cb1f-11e9-8472-b2c1bdeddaf2.png)

**App information (please complete the following information):**
 - App Type : Native App
 - Postman Version: v7.5
 - OS: macOS

**Additional context**
 The newly created monitor which works has been recreated with the same collection and environment, observed the same behaviour few times now. It looks like the data of the original monitor became corrupted or the schema was changed(E.g.- Noticed a new field called Version)

**Comment by shivam-postman** [comment]
The exact behaviour is that whenever there is a toggle in the state of the monitor (paused/resumed), it leads to the environment being unresolved for the subsequent _manual_ runs. The scheduled runs are successful, and after a successful scheduled run, the subsequent manual runs are successful too, until there is a state toggle. Resetting the environment to some other environment/no environment, and then setting it back also leads the subsequent manual runs to be successful. We're working on the issue and the fix will be out soon.

**Comment by godfrzero** [comment]
Could you let us know if the original monitor gets fixed if you run through the following steps?

1. Edit the monitor and switch to a different environment, then save
2. Edit the monitor again, switch back to the original environment, then save
3. Try running the monitor, or let it run on schedule

**Comment by MartinIvison** [comment]
Yep, that worked.

**Comment by suntoshakula** [comment]
![github-issue](https://user-images.githubusercontent.com/76269239/173460602-54b28690-a52d-4eca-8ff1-66ddb8864525.JPG)
