### ISSUE TITLE
Feature request: Replace variables in URL with URL parameters

### ISSUE THREAD

**Issue by avesse** [a85/POSTMan-Chrome-Extension#724]
When creating a URL such as http://{{host}}/api/resource/{{resourceId}}/etc, it will replace the {{host}} part with the environment variable, but I would like to replace {{resourceId}} with a URL parameter. Currently, when adding URL parameters, it appends it as a query string rather than replacing variables. It should only append as a query string parameter if there is not a variable with the same name in the URL.

**Comment by intonarumori** [comment]
I'm looking for the exact same thing (it's a very common scenario).
Has this been solved? For such a basic feature I cannot find clear instructions using Google.

**Comment by bchecketts** [comment]
Same. I can't include parameters in the URL. It always want to add them as query string arguments.  Requiring a pre-request script for a simple variable substitution that I want to vary often seems like a pretty poor way to do it.

**Comment by GonzaloTorreras** [comment]
Totally agree,
In my case using the Hubspot API I need to have in the URL some different variables to manage different elements like:
https://api.hubspot.com/content/api/v4/custom-widgets/{{moduleID}}/?portalId={{hsportal}}

Using the pre_scripts means that I need a different request for each different block instead using the same because I can't add a variable there :(

**Comment by StevenSchlotterbeck** [comment]
+1, this would be a very useful feature (and like intonarumori mentions, quite common of a scenario in API design).

**Comment by prashanth-nani** [comment]
+1, Agreed! It is very common to have resource ids in the URI.

**Comment by canales** [comment]
Looking for a simple way to do this as well! + 1

**Comment by intonarumori** [comment]
Finally came up with the following.

By putting `{{url}}/users/:user_id/` into the URL where `{{url}}` is the API base URL coming from an environment variable, I can set `:userid` as a path parameter by clicking on the `Params` button at the end of the URL field.
