### ISSUE TITLE
Lines highlighting in result

### ISSUE THREAD

**Issue by camohub** [a85/POSTMan-Chrome-Extension#7244]
It would be handy if is possible to highlight the lines in result. Also in query string.... If user click on the line number this line will have some colored background. Like in Github diffs... 
Thank you.

PS: There is something like line highlighting. But when I click somewhere it disappears.

**Comment by numaanashraf** [comment]
@camohub Could you give us some screenshots to help us understand this better?

**Comment by camohub** [comment]
Here is the screenshot. There is line highlighted but it disappears if I click somewhere else.
![Screenshot (3)](https://user-images.githubusercontent.com/8393426/64234917-998e6200-cef7-11e9-9caf-2effde8fcbda.png)

**Comment by numaanashraf** [comment]
@camohub This is supported in the response pretty view now. You can click on a line number to highlight a line, or click and drag in the line numbers to select multiple.
