### ISSUE TITLE
Local Development Environment, "Watch Mode"

### ISSUE THREAD

**Issue by captain-kark** [a85/POSTMan-Chrome-Extension#7247]
**Is your feature request related to a problem? Please describe.**

I'd like to be able to write more of my collection's postman resources in the editor I'm most comfortable with.

**Describe the solution you'd like**

I'd like to clone a postman collection and have more of my resources split out into dedicated files for:

  - request bodies
  - prerequest scripts
  - test scripts

A local development `watch` server could take my current file's source code, stringify it, split it on newlines, and insert it into the current collection -> folder(s) -> request's `item` object.

The destination of the current file would be driven by convention. The top-level directory name would need to match the collection, and each following directory would map to the folder in that collection. The request name would be the name of the terminating directory, which would contain a file for each component of the request.

  - request.js
  - prerequest.js
  - test.js

**Describe alternatives you've considered**

Writing all of the above myself using webpack or something. This would over-ride all interactions in the postman editor since bi-directional updates would be extremely painful.

**Additional context**

This is an opinionated feature request. In it, I assume that the user is only using a very small percentage of the feature set of postman. Using workspaces, environments, importing the `pm` object, etc., are all actively preventing me from solving this in an npm module that would work for anyone but myself.

**Comment by a85** [comment]
This is not going to be a first-class Postman feature but it is achievable through the Postman API and the Postman Collection SDK. One of our Solution Engineers demonstrated this internally and we'll post a how-to on our blog soon.

**Comment by a85** [comment]
@preethammavin Can you please tag Matt here?

**Comment by vvs11** [comment]
@matt-ball can you take this forward?

**Comment by matt-ball** [comment]
Hey @captain-kark ,

I've been working on a CLI very similar to what you are describing. It's in the very early stages but would appreciate if you could give it a go and raise any feedback via an issue over there:

https://github.com/matt-ball/postman-cli

Thanks,
Matt

**Comment by captain-kark** [comment]
I'll redirect any updates on this issue to that repository until there's enough momentum to justify making a first-class feature inside of Postman proper.

The readme appears to hit every bullet point of my issue! I'm excited to try it out sometime.
