### ISSUE TITLE
Weird duplicate request and I can't delete it.

### ISSUE THREAD

**Issue by oozman** [a85/POSTMan-Chrome-Extension#7249]
**Describe the bug**
I have a collection in Postman App (Mac) and tried to publish docs. But when I look at the published docs url... I see this weird `forgot password (Copy)` which doesn't exist in my mac app.

**To Reproduce**
I can't reproduce it :( 

**Expected behavior**
There should be no duplicate request when publishing it as a doc.

**Screenshots**
![Image](https://narrow-blade.surge.sh/ss.png)

**App information (please complete the following information):**
 - Native App
 - Postman Version  7.6.0
 - OS:  macOS Mojave 10.14.5

**Comment by preethammavin** [comment]
@omarusman can you logout and login to the app once and see if it corrects the bug?

**Comment by oozman** [comment]
@preethammavin logout and login doesn't correct the issue. :(

**Comment by preethammavin** [comment]
@omarusman can you write to us at help@getpostman.com with the collection id and request id of the collection where you see the weird behaviour so that we can take a closer look ? 

Also just so that I am conveying it correctly, you logged out and login into Postman App and not the dashboard?
