### ISSUE TITLE
Postman App loader is not positioned in the center of primary screen

### ISSUE THREAD

**Issue by oswee** [a85/POSTMan-Chrome-Extension#7251]
**Describe the bug**
Dual-screen (monitor) setup on Fedora 30 Workstation.
When launching the Postman Linux app, loader (pre-loader) is placed almost on booth monitor bezels and not in the center of primary screen or last used screen.

**To Reproduce**
Just launch the app

**Expected behavior**
Loader should be placed in the center of primary screen at least. Ideally, if app would remember last used screen and opens on that screen.

**Screenshots**
![Screenshot from 2019-09-03 10-17-31](https://user-images.githubusercontent.com/20469200/64152038-62a34800-ce34-11e9-84dc-834302de3542.png)

**App information (please complete the following information):**
 - App Type [Native App]
 - Postman Version [v7.6.0 ]
 - OS: [Fedora 30 Workstation]

**Comment by twitharshil** [comment]
Hi,
We've pushed an update on our early access canary. It has updated the underlying platform (Electron) on which Postman is built. Do try it out and let us know

You can get the canary app from https://www.getpostman.com/downloads/canary

**Comment by DannyDainton** [comment]
As this user account has been deleted and an update has been pushed in May, I'm going to closed this issue.
