### ISSUE TITLE
Postman crashes when a new token is requested

### ISSUE THREAD

**Issue by turri87** [a85/POSTMan-Chrome-Extension#7252]
**Describe the bug**
The app crashes after requesting a new token

**To Reproduce**
1. New Request
2. Click on 'Authorization'
3. Type: OAuth 2.0
4. Add authorization data to: Request URL
5. Click on 'Get New Access Token'
6. Fill the gaps as it shows on the screenshot below
7. Click on 'Request Token'
8. App crashed

**Expected behavior**
Able to create a new token

**Screenshots**
Configuration to get a new token:
![config](https://user-images.githubusercontent.com/47180296/64160094-3d620a00-ce33-11e9-931f-88084491eb92.PNG)

Error:
![error1](https://user-images.githubusercontent.com/47180296/64160102-4521ae80-ce33-11e9-9587-5402fae3781b.PNG)

**App information (please complete the following information):**
 - App Type: native app
 - Postman Version: 7.6.0
 - OS: Windows 10 Enterprise

**Comment by josteitv** [comment]
I bumped into the same problem, but managed to work around it by turning off SSL certificate verification. So I suspect the crash is related to Postman not being able to verify the certificate chain.

![image](https://user-images.githubusercontent.com/952413/64173361-6399a100-ce57-11e9-98db-66ef76afffc1.png)

**Comment by bscnarola** [comment]
I have same issue, I turn off the SSL certification verification still, the postman is crashing on Request Token. Any other solution?

**Comment by boajer** [comment]
Same issue for me, workaround doesn't helped
Standalone Version 7.6.0 (7.6.0)
Macos 10.14.6

**Comment by coditva** [comment]
@turri87 @josteitv @bscnarola @boajer 

Thanks for reporting! This indeed is an issue and the fix will be out asap! I'll comment here if there are any updates.

**Comment by asincole** [comment]
Hi, I am having the same exact issue, please is there a workaround or something else I can use temporarily as I need to test something urgently?

**Comment by boajer** [comment]
@asincole I believe with Postman you can compose proper request for a auth token manually. Then manually apply that token to request you need to sign, at bearer header or whatever is suitable in your case; So you would avoid  using that nice, but currently broken features.

**Comment by asincole** [comment]
@boajer I'm trying to get the token from auth0 though. Is the manual method possible for this too?

**Comment by coditva** [comment]
@asincole Hi,

If you're trying to send request to, for instance, `DOMAIN.com/auth`, try changing that to `http://DOMAIN.com/auth` or `https://DOMAIN.com/auth`.

We're already working on the fix and it will be out soon.

**Comment by turri87** [comment]
Hey @coditva , any update on this?

**Comment by coditva** [comment]
@turri87 the fix is already in Staging! Will be released in the next couple of days...

**Comment by turri87** [comment]
@coditva thanks for the update

**Comment by ebinsynup** [comment]
@coditva is this issue fixed?
Postman is still crashing

**Comment by coditva** [comment]
This issue is now fixed. Update to the latest Postman app (version 7.7) 🎉

**Comment by samuelAle** [comment]
I'm currently experiencing this issue, but I'm able to use the work around it by turning off SSL certificate verification.

Postman for Mac
Version 7.18.1
OS X 19.2.0 / x64

**Comment by coditva** [comment]
Hey @samuelAle, can you provide some more information about the problem you're facing?
1. Does the App simply closes or does the authentication fail?
2. Is there any public endpoint we can use to test this out?
3. Can you send logs for this crash to us at help@postman.com (mention the issue ID in the email)? Here's how to find logs: https://support.getpostman.com/hc/en-us/articles/360033270134-Where-can-I-find-logs-for-the-Postman-app-

Might be similar to https://github.com/postmanlabs/postman-app-support/issues/8054

**Comment by RavenHursT** [comment]
@coditva it's 2024 and now I'm experiencing this issue. Sigh...
