### ISSUE TITLE
System error - reset password system did not respond

### ISSUE THREAD

**Issue by yizeruier1** [a85/POSTMan-Chrome-Extension#7253]
I forgot my login password, but when I sent an email to retrieve it, the system did not respond and the console reported an error

**Comment by preethammavin** [comment]
@yizeruier1 can you write to us at help@getpostman.com from your registered email id so that we can get it sorted for you

**Comment by ArjunSingh-PM** [comment]
Hi @yizeruier1! I hope you have not faced this issue again. Could you please confirm that your account is accessible now.

**Comment by ArjunSingh-PM** [comment]
Closing this issue as this was a transient issue. The reset password flow is working correctly.
