### ISSUE TITLE
Can no longer click href links without scheme

### ISSUE THREAD

**Issue by henhal** [a85/POSTMan-Chrome-Extension#7255]
**Describe the bug**

When getting back a response body containing HATEOAS links, I used to be able to click links such as "href": "/some/other/endpoint". Been doing this for years, and it's a crucial part of using postman for API testing or exploration. When starting postman today, it updated (didn't use it for a couple of months) and this ability is gone - only http* schemed links become clickable.

**To Reproduce**

Call an API returning JSON with a "href": "/foo/bar" link.
Attempt to click the link.
/foo/bar is not recognized as a hyperlink.

**Expected behavior**

As postman always used to do, I expect links-like strings to be clickable so that I can click a HATEOAS link to invoke another endpoint.

**Screenshots**

![image](https://user-images.githubusercontent.com/9608258/64169280-bbcba580-ce4d-11e9-87dc-36b6ef5964a9.png)

**App information (please complete the following information):**

  - Postman native v7.5
  - Windows 10

**Additional context**

**Comment by kamalaknn** [comment]
Hi @henhal 

Thanks for reporting the issue. We are tracking this as part of #6832

I'm closing this as a duplicate. Please follow the original issue for updates.
