### ISSUE TITLE
Session has Expired Error - Failure to Authenticate

### ISSUE THREAD

**Issue by kriggo15** [a85/POSTMan-Chrome-Extension#7256]
**Describe the bug**
When trying to sign into the desktop app, I'm receiving an error around connecting to the authentication service. When clicking on Retry, I receive the same error. I am able to log into the web portal and see all of my information.

**To Reproduce**
1. Click on Sign In
2. Postman tries to authenticate and fails.
3. See error

**Expected behavior**
When clicking Sign In, I expect to be prompted for my credentials and to be able to log in.

**Screenshots**
![Postman 2](https://user-images.githubusercontent.com/54848612/64176342-3fc06600-ce2b-11e9-9263-f961e59403f0.png)
![Postman 1](https://user-images.githubusercontent.com/54848612/64176343-3fc06600-ce2b-11e9-8eb5-1631b5d7629c.png)

**App information**
 - Postman Version: 7.0.6
 - OS: Win 10

**Comment by preethammavin** [comment]
@kriggo15 can you check if it occurs on any other network? We usually see this when the network access is blocked for our client to connect to or servers.

**Comment by preethammavin** [comment]
@kriggo15 with the current information provided we would be unable to help, closing the issue for now please feel free to reopen the issue with the necessary information so that we can get it sorted for you.
