### ISSUE TITLE
504 error when Importing exported data via the Postman API into a workspace

### ISSUE THREAD

**Issue by labifrancis** [a85/POSTMan-Chrome-Extension#7257]
**Describe the bug**
When a user tries to import an exported data(i.e. collection) using Postman API to a workspace, it gives a 504 error.

**To Reproduce**
1. Export any collection and save as a zip file
2. Navigate to any workspace and create a request as described below:
 Method: POST
 Endpoint: https://api.getpostman.com/import/exported

**HEADERS**
```
x-api-key          {{postman_api_key}}
Content-Type       application/json
```

**BODY** formdata
```
type           file
input          File containing the exported collections or environments

```
Reference: https://docs.api.getpostman.com/?version=latest scroll to "POST Import exported data"
 
![image](https://user-images.githubusercontent.com/10200603/64175865-267fdf80-ce54-11e9-87c4-9458b1758dba.png)

**Expected behavior**
The request should go through without any error. 

**App information (please complete the following information):**
 - App Type [e.g. Native App]
 - Postman Version [e.g. 7.3.6]

**Comment by Hayk-S** [comment]
Closing this @labifrancis.
