### ISSUE TITLE
Windows - Installation Has Failed

### ISSUE THREAD

**Issue by mccannt** [a85/POSTMan-Chrome-Extension#7258]
**Describe the bug**
Some Windows users are experiencing install issues of the v7.6 release of the application. 
This is impacting some users on Windows 7 and 10 (32 and 64 bit).

**To Reproduce**
1. Download the lates Windows release
2. Click on the EXE to install.

**Expected behavior**
Application will install successfully. 

**App information (please complete the following information):**
 - Native App v7.6
 - Postman Version v7.6
 - Windows 7 and 10 (32/64 bit)

**Additional context**

[SquirrelSetup (3).log](https://github.com/postmanlabs/postman-app-support/files/3569970/SquirrelSetup.3.log)
[Postman_log_failed_to_install.txt](https://github.com/postmanlabs/postman-app-support/files/3569971/Postman_log_failed_to_install.txt)
[SquirrelSetup (2).log](https://github.com/postmanlabs/postman-app-support/files/3569972/SquirrelSetup.2.log)
[SquirrelSetup (1).log](https://github.com/postmanlabs/postman-app-support/files/3569973/SquirrelSetup.1.log)
[SquirrelSetup.log](https://github.com/postmanlabs/postman-app-support/files/3569974/SquirrelSetup.log)
[log.txt](https://github.com/postmanlabs/postman-app-support/files/3569975/log.txt)
[SquirrelSetup_.log](https://github.com/postmanlabs/postman-app-support/files/3569976/SquirrelSetup_.log)

**Comment by danieldogeanu** [comment]
This is also an issue with v7.7.2. I've experienced this same problem on v7.6.0 and it's still not fixed. 

I'm running Windows 10 Pro x64 v1903, OS build 18362.356 (latest).

Here's my [SquirrelSetup.log](https://github.com/postmanlabs/postman-app-support/files/3621365/SquirrelSetup.log)

Any ideas on how to make it work?

**Comment by mccannt** [comment]
@danieldogeanu Thx for reaching out and providing the logs.
I am curious if this is any help https://support.getpostman.com/hc/en-us/articles/360008601954-Postman-App-doesn-t-start-Postman-App-not-working

**Comment by danieldogeanu** [comment]
@mccannt It doesn't help. I deleted the folders, I get the same thing. However, I discovered that this is not an issue only with Postman, but with Electron itself. I tried to install Atom as well and I get the exact same error. Even worse, Electron is flagged as infected with BScope.Adware.NSIS.ConvertAd. Maybe this is the real issue.

**Comment by mccannt** [comment]
@danieldogeanu Thanks for trying this. I have added this information to our issue and we will investigate further.

**Comment by danieldogeanu** [comment]
@mccannt Thanks! Also, here's the log from Atom install: [Squirrel-Install.log](https://github.com/postmanlabs/postman-app-support/files/3626300/Squirrel-Install.log)

**Comment by harryi3t** [comment]
This issue is being tracked here https://github.com/postmanlabs/postman-app-support/issues/5681
