### ISSUE TITLE
Windows DLL - Login point not found

### ISSUE THREAD

**Issue by mccannt** [a85/POSTMan-Chrome-Extension#7259]
Describe the bug:
Windows DLL issues for some users on v7.6 install. The error message "Login point not found" is displayed. 
This is impacting some users on Windows 7 and 10 (32 and 64 bit).

To Reproduce
1. Download the lates Windows release
2. Click on the EXE to install.

Expected behavior
1. Application will install successfully.

App information (please complete the following information):

- Native App v7.6
- Postman Version v7.6
- Windows 7 and 10 (32/64 bit)

Additional context
![08-29-2019_2](https://user-images.githubusercontent.com/14275144/64183115-bbc4a900-ce3f-11e9-91cf-76e9fb10583e.png)
![2019-08-28_06h25_16](https://user-images.githubusercontent.com/14275144/64183123-bd8e6c80-ce3f-11e9-8bb3-3252f92a808b.png)

**Comment by harryi3t** [comment]
@mccannt This looks like a device-specific issue which is not related to Postman.
Other people facing the same issues seemed to have resolved it by installing the missing update file from Microsoft: https://support.microsoft.com/en-us/help/2533623/microsoft-security-advisory-insecure-library-loading-could-allow-remot

References:
https://www.reddit.com/r/discordapp/comments/6sny2w/the_procedure_entry_point_not_located/
https://talk.sonymobile.com/t5/PC-Mac-Software/Cannot-Install-Xperia-Companion/td-p/1166647#gref
