### ISSUE TITLE
Line break should be CRLF, not LF.

### ISSUE THREAD

**Issue by ivanovevgeny** [a85/POSTMan-Chrome-Extension#726]
When requesting with 'form-data' PostMan send LF as linebreak and error happen:
"Unexpected end of MIME multipart stream. MIME multipart message is not complete" exception while parsing multipart form.

**Comment by dertz** [comment]
I am looking at a response that I know has CRLF in it yet when displayed under the raw response I am not seeing them.  This is confusing and leads one to believe that they are missing in the response. When I go to other tools that display the raw response I see them shown as line separators.  

I tried  the Response (formatted) tab but it is not displaying anything, the display area is blank.  The response media type is text/csv. The link address for the formatted response tab is chrome-extension://ecjfcmddigpdlehfhdnnnhfgihkmejin/index.html#tabs-formatted.  Not sure if it is looking for tabs and that is why it is not displaying anything.  If the line separators showed up in the under formatted tab that would be helpful and acceptable.

**Comment by abotalov** [comment]
From https://tools.ietf.org/html/rfc7231 ("Hypertext Transfer Protocol (HTTP/1.1): Semantics and Content")
> An HTTP sender MAY generate, and a recipient MUST be able to parse, line breaks in text media that consist of CRLF, bare CR, or bare LF.... This flexibility regarding line breaks applies only to text within a representation that has been assigned a "text" media type; it does not apply to "multipart" types or HTTP elements outside the payload body (e.g., header fields).

> The message body is itself a protocol element; a sender MUST generate only CRLF to represent line breaks between body parts.

**Comment by JAnderson1122** [comment]
@abotalov I believe the section you quoted goes on to say:

> This flexibility
>    regarding line breaks applies only to text within a representation
>    that has been assigned a "text" media type; it does not apply to
>    "multipart" types or HTTP elements outside the payload body (e.g.,
>    header fields).

The following section goes on to say:

> 3.1.1.4.  Multipart Types
> 
>    MIME provides for a number of "multipart" types -- encapsulations of
>    one or more representations within a single message body.  All
>    multipart types share a common syntax, as defined in Section 5.1.1 of
>    [RFC2046], and include a boundary parameter as part of the media type
>    value.  **The message body is itself a protocol element; a sender MUST
>    generate only CRLF to represent line breaks between body parts.** 

I believe what Postman should do is to convert all LF to CRLF, at least when using the 'raw' option for the request body.

**Comment by madmax911** [comment]
Cool program!  I have a soft of similar issue though.  I'm running the linux client and looking to intentionally put a CRLF into a raw post body but just because of OS differences I have no way to type/paste in exact text into the window.  It seems to auto-change intentional CRLF's into just LF's.  I think it would be convenient if they could be escaped in some way -- eg. \r\n - like a sort of 3rd option raw-escapable that would allow all the escape codes you would expect of a string in JS.  Or maybe some way to set rules like to treat enter as CRLF vs LF.

This might satisfy some other people's concerns mentioned above.

**Comment by madmax911** [comment]
> Cool program! I have a soft of similar issue though. I'm running the linux client and looking to intentionally put a CRLF into a raw post body but just because of OS differences I have no way to type/paste in exact text into the window. It seems to auto-change intentional CRLF's into just LF's. I think it would be convenient if they could be escaped in some way -- eg. \r\n - like a sort of 3rd option raw-escapable that would allow all the escape codes you would expect of a string in JS. Or maybe some way to set rules like to treat enter as CRLF vs LF.
> 
> This might satisfy some other people's concerns mentioned above.

Ok, I think I just solved my own issue -- in this post:
https://github.com/postmanlabs/postman-app-support/issues/4808#issuecomment-446708870
