### ISSUE TITLE
Selecting Header Preset in Example Response header inserts [object Object]

### ISSUE THREAD

**Issue by kaustavdm** [a85/POSTMan-Chrome-Extension#7260]
**Describe the bug**
Selecting a header preset from the editor in Example response inserts `[object Object]`. Looks like #5443, but for Example response.

**To Reproduce**
1. Add a new header preset, if you don't have one
2. Create a new Example or choose an existing Example for a request
2. Under Response -> Headers, type in the `Key` field
3. Select a suggestion
4. The header list gets `[object Object]` added in the Key field.

**Expected behavior**
The headers list should add the headers added in the selected header preset.

**Screenshots**
![Bug screencapture](https://user-images.githubusercontent.com/364832/64186870-34058b80-ce8d-11e9-9294-06f9378ad3d1.gif)

**App information (please complete the following information):**
 - App Type: Native app
 - Postman Version :7.6.0
 - OS: macOS Mojave 10.14.6

**Comment by DannyDainton** [comment]
Hey @kaustavdm 👋🏻 

I'm unable to recreate this issue in the latest version of the platform. Looks like the linked issue has also been closed too 🎉 

I'm going to close this issue out.
