### ISSUE TITLE
Comments should be exported with the Collection

### ISSUE THREAD

**Issue by tolgabalci** [a85/POSTMan-Chrome-Extension#7261]
When I export a collection, the comments I have added do not appear inside the collection Json. (Needless to say, after importing my exported collections on a different machine, all my request comments are lost)

1. Add a Comment to your request
2. From the Collection Menu, select export
3. Click the Import button (perhaps on a different machine)
4. The request which a Comment was added to now shows Comments (0)

**App information
 - Native App: Postman for Windows
 - 7.6.0
 - OS: Windows 10 (10.0.17134)

**Comment by sankalp0o** [comment]
@tolgabalci This is the expected behaviour. Comments are not part of the collection schema.

I'm marking this issue as a feature request. This is not really something that we anticipated people needing, hence could you help us understand the use case better? For example, what kind of information do you put in comments? How often do you export and import collections and why?

**Comment by rajnisingla** [comment]
This would be a really useful feature to have. We can use Postman Collection as a way to document and release our APIs if we have this. For example: We can put in comments the information about what exactly was changed in the Request as per API specification and if expected response was received or not.

**Comment by mpasquini** [comment]
Another point about how is useful this feature would be, my case.
I've collection runners that need to used data to iterate tests over a set of data. 
I need to be consistent with:  
- tester that apply "run"
- developers that update the tests
- developers that apply for newman

**Comment by superhawk610** [comment]
Comments are a great place to list valid values for enums, expected response format (useful for API endpoints that are still actively being built and may not yet be available), and any invariants the caller should uphold (max of N elements per request, allow N seconds between requests, may not be available until N seconds are another request was made, etc).
