### ISSUE TITLE
Native app not rendering properly on windows 10

### ISSUE THREAD

**Issue by tapanp** [a85/POSTMan-Chrome-Extension#7262]
**Describe the bug**
Postman native application covers entire screen on windows 10 with no resizing controls on top right corner (min, max, close). 

**To Reproduce**
1. Open postman application on windows 10
2. After loading/ splash screen is complete app opens in main window.
3. Now the app covers entire screen with no min, max and close controls on top right.
4. It also covers entire taskbar making it harder to navigate to other applications.
5. Cannot drag and move Postman to other screen

**Expected behavior**
Postman should render properly with windows resizing controls and shouldn't cover taskbar.

**Screenshots**
![postman_native_snippet](https://user-images.githubusercontent.com/48896658/64218958-f9d8d000-cf06-11e9-9e4f-1a65be861a28.PNG)

**App information (please complete the following information):**
 - App Type [Native App]
 - Postman Version [7.6.0]
 - OS: [Microsoft Windows 10 Education]

**Additional context**

**Comment by numaanashraf** [comment]
@tapanpDoe Looks like you might have accidently made the app window fullscreen. Could you toggle it back via "Top-left menu > View > Full Screen"?

**Comment by tapanp** [comment]
thanks @numaanashraf. It's working normally after toggling full screen mode.
