### ISSUE TITLE
Can't delete Monitor: "Something went wrong"

### ISSUE THREAD

**Issue by suraj-purohit** [a85/POSTMan-Chrome-Extension#7263]
**Describe the bug**
When attempting to delete a monitor from the web dashboard the following error is displayed:
![Screen Shot 2019-08-14 at 9 05 41 PM](https://user-images.githubusercontent.com/51916047/64240332-5a740700-cf1f-11e9-9b66-eaa4a7af91fa.png)

**To Reproduce**
Unknown

**Expected behavior**
Monitor is deleted

**App information (please complete the following information):**
- App Type: Native App, Web Dashboard
- Postman Version: 7.5

**Comment by godfrzero** [comment]
As of now, this only affects admins attempting to delete a monitor which they do not have access to otherwise. A fix is in the works.

**Comment by cyrielle-hada** [comment]
@godfrzero Another report of this behavior. 

Trying to delete a monitor results in a `something went wrong error.` 
Note that the collection doesn’t exist anymore. 

I tried to replicate the issue but getting a different behavior
1. I deleted a collection in my personal workspace for which I had a monitor. 
2. Upon deleting the collection - I am still able to see the monitor in the dashboard
3. Clicked on … > Delete > Confirm
4. The monitor is successfully deleted 

However, I have other monitors listed in my workspace that are deleted (from the trash as well), those ones are greyed out and I am unable to delete them.
 
![Nov-07-2019 15-03-55](https://user-images.githubusercontent.com/47351631/68400408-e7318000-016f-11ea-9e53-ac5c55d4890f.gif)

**Comment by godfrzero** [comment]
@cyrielle-hada Is the user in question an admin on the team, and attempting to delete a monitor belonging to another user?

**Comment by cyrielle-hada** [comment]
@godfrzero The user's role is Admin, Billing, Developer. He's attempting to delete a monitor created on a collection he owned (the collection is now deleted).

**Comment by cyrielle-hada** [comment]
@godfrzero is there any further information that would help in understanding the underlying issue?

**Comment by stephan-procore** [comment]
I am experiencing the same issue.  My user account has admin and developer roles.  The monitors I am trying to delete are causing errors that are reported via slack integration, creating undesired noise.   The slack integration, however, are not showing in the web console.  Please advise.

**Comment by Raj-postman** [comment]
Found the same issue, where the admin is unable to delete/pause the monitor from Web as well as from the application. The user who was able to update the collection could delete the monitor in this case.

**Comment by amelia24** [comment]
I have the same issue. I did create a monitor in My Workspace, after I deleted the collection for this monitor.  I'm not able to delete the monitor please help me. It almost consume all our requests.

**Comment by cyrielle-hada** [comment]
@amelia24 Would it be possible [to raise a support ticket](https://go.pstmn.io/help-center-signin-newrequest) and provide the name of the collection associated with the monitor you're trying to delete?

**Comment by DannyDainton** [comment]
Hey @cyrielle-hada,

Do you know if we have received anymore reports for this particular issue in the latest version?

**Comment by cyrielle-hada** [comment]
@DannyDainton I'm not sure it is entirely resolved. We are now able to delete them for the users if the issue happens though.

**Comment by godfrzero** [comment]
Closing due to age + lack of activity.
