### ISSUE TITLE
Response preview print HTML Codes when shouldn't

### ISSUE THREAD

**Issue by ZangeTsune** [a85/POSTMan-Chrome-Extension#7264]
The Preview of the response are printing HTML Codes when a string contain some substring equal to an HTML Code but without `;`.

![Selection_080](https://user-images.githubusercontent.com/11486015/64243002-e2014c00-cf06-11e9-8c04-77ad4d7576a9.png)
![Selection_079](https://user-images.githubusercontent.com/11486015/64243008-e594d300-cf06-11e9-821b-6d1973057305.png)

![Selection_081](https://user-images.githubusercontent.com/11486015/64243019-e9285a00-cf06-11e9-82b2-378e99c29a65.png)

**Comment by shamasis** [comment]
The preview tab emulates browser rendering and that is how browser behaves. Try creating an HTML with same content and open it in any browser and you should see same output.

Any reason why you're expecting this to work differently?
