### ISSUE TITLE
Dashboard - improve UX flow when looking for individual synced data 

### ISSUE THREAD

**Issue by cyrielle-hada** [a85/POSTMan-Chrome-Extension#7265]
_Filed by Product Support._ 

**Is your feature request related to a problem? Please describe.**
Collections/Environments/APIs may happen to be missing in the event that it is removed from a workspace.

**Problem 1**
Heading to the page https://go.postman.co/me/collection when a collection is missing _should_ be the first action to take to manage the collection(s) and verify it is synced and not lost. 

You need to go to Avatar > Profile > Collections for reaching that page which may cause confusion around Data Loss. 

<img width="336" alt="Screen Shot 2019-09-03 at 16 50 50" src="https://user-images.githubusercontent.com/47351631/64253381-1b40b880-cf15-11e9-90a4-6704ac9d3fc2.png">

**Problem 2**
If an API has been removed from all workspaces by accident, a team may want to delete it. The 'me' section is underneath the user profile. Users are not expecting to find in their profile 'a subset of their workspace'. (see related GitHub issue https://github.com/postmanlabs/postman-app-support/issues/7329)

**Describe the solution you'd like**
Make this page easier to find/be able to access this from the workspaces menu.
Make a button the landing page saying `View all your personal collections`.

**Comment by sankalp0o** [comment]
Comment from another user "The 'me' section is underneath your user profile (top right link) I was not expecting to find in my profile basically a sub set of my workspace. I would have expected to be able to access this from the workspaces menu, or something of the sort." when talking about orphan APIs.

**Comment by akshay-kulkarni-03** [comment]
@cyrielle-hada a user can view all of their personal workspaces by going to Workspace Switcher -> View all Workspaces -> Filter by visibility (Personal).

Is this issue still present?

**Comment by cyrielle-hada** [comment]
@akshay-kulkarni-03 the UX has changed completely since I logged this issue. Also, it's not relevant anymore since we have removed the "remove entity" feature. Closing this! :)
