### ISSUE TITLE
Dashboard - Update UI when workspace ownership is transferred over to other users

### ISSUE THREAD

**Issue by cyrielle-hada** [a85/POSTMan-Chrome-Extension#7266]
**Describe the bug**
With RBAC - when we remove a user from the team who is the Workspace Owner - the team workspace continues to exist in the team and **the ownership is transferred to the other members of that workspace.** 

The app reflects that change properly. When we go to View Details from my Team Workspace in the Postman app.

![image](https://user-images.githubusercontent.com/47351631/64269848-83ea5e00-cf32-11e9-8696-820f97f07648.png)

Here is how the UI should look like 

<img width="627" alt="Screen Shot 2019-09-04 at 16 39 22" src="https://user-images.githubusercontent.com/47351631/64269956-ada38500-cf32-11e9-939d-f3e9928e3ecb.png">

That ownership transfer is not updated in the dashboard. 

<img width="751" alt="Screen_Shot_2019-09-04_at_16_42_19" src="https://user-images.githubusercontent.com/47351631/64270250-26a2dc80-cf33-11e9-8567-54b5a0e4159f.png">

**To Reproduce**
1. Remove a team member from your team who is a team workspace owner
2. Notice the ownership transfer - as well in terms of UI when you go to the app > team workspace > View details. 
3. Go to the dashboard > Select the team workspace > View details > See that the removed team member is still the owner of that workspace.

**Expected behavior**
The UI should reflect the same way as it does in the app. 
<img width="627" alt="Screen Shot 2019-09-04 at 16 39 22" src="https://user-images.githubusercontent.com/47351631/64269956-ada38500-cf32-11e9-939d-f3e9928e3ecb.png">

**Comment by sankalp0o** [comment]
Thanks for reporting @cyrielle-hada , we'll take a look at why this is happening.

**Comment by sankalp0o** [comment]
We pushed out a fix to better communicate this state. Closing the ticket but feel free to reopen if this does not work!
