### ISSUE TITLE
Lesson CTA text overflows in empty state in two pane view

### ISSUE THREAD

**Issue by deepakpathania-zz** [a85/POSTMan-Chrome-Extension#7267]
**Describe the bug**
The lesson CTA that appears in the empty state has its text overflowing in the 2 pane view.

**To Reproduce**
1. Open the app and see the lesson recommendation in the empty state.
2. Switch to 2 pane view in the same state.
3. CTA text will overflow.

**Expected behavior**
CTA text shouldn't overflow.

**Screenshots**
<img width="1042" alt="Screenshot 2019-09-05 at 11 09 22 AM" src="https://user-images.githubusercontent.com/15071438/64315099-b184e500-cfce-11e9-8ae7-f223901807ee.png">

**App information (please complete the following information):**
 - App Type - Native
 - Postman Version - 7.6.0 
 - OS: macOS Mojave v10.14.3

**Comment by prashantagarwal** [comment]
@deepakpathania This is fixed now. Thanks for reporting.
