### ISSUE TITLE
How can I disabled minor version auto update? V7.5.0 always update to V7.6.0

### ISSUE THREAD

**Issue by physicsLoveJava** [a85/POSTMan-Chrome-Extension#7269]
How can I disabled minor version auto update?
V7.5.0 is ok for me, but the postman client is auto update to V7.6.0, which just crash for some unknown reason!

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. Please make sure the screenshot does not contain any sensitive information such as API keys or access tokens. 

**App information (please complete the following information):**
 - App Type [e.g. Chrome App, Native App]
 - Postman Version [e.g. 6.0.1]
 - OS: [e.g. macOS High Sierra 10.13.2]

**Additional context**

**Comment by numaanashraf** [comment]
> V7.5.0 is ok for me, but the postman client is auto update to V7.6.0, which just crash for some unknown reason!

Could you give us more information regarding this crash? Is the Postman v7.6.0 app crashing while opening or while performing any actions in the app?

**Comment by preethammavin** [comment]
Closing the issue for now, let us know if the crash was fixed in lates updates as we pushed large number of stability improvements and bug fixes.  Please feel free to reopen the issue if it was not fixed.
