### ISSUE TITLE
Colored environments

### ISSUE THREAD

**Issue by unmultimedio** [a85/POSTMan-Chrome-Extension#7271]
**Is your feature request related to a problem? Please describe.**
Mostly an UX improvement. Sometimes requests are not what you're expecting because you haven't realized which environment you're using. Or even so, it can get confusing if you switch a lot among environments. The idea is that you clearly know which environment you're on.

**Describe the solution you'd like**
Having a colored environment allow users to me more aware which environment they're doing requests in. Environments are mostly used to change variables for local/dev/stage/prod environments, so differentiate them with colors would be very nice

**Describe alternatives you've considered**
Having those in colors or even a pallete of predefined white/black/gray/green/yellow/orange/red colors (similar to github labels), and have that **really visible** (color as background, high contrast text), that'd be awesome.

**Additional context**
<img width="475" alt="Postman" src="https://user-images.githubusercontent.com/4431392/64358879-e132ed80-cfcc-11e9-97cd-35d1ce31b1f1.png">

So it looks something like this, but prettier haha:
<img width="373" alt="Postman" src="https://user-images.githubusercontent.com/4431392/64359373-cd3bbb80-cfcd-11e9-8877-cca6cfdece5b.png">

**Comment by Chealer** [comment]
This is a duplicate of issue #903.

**Comment by unmultimedio** [comment]
Closed in favor of #903
