### ISSUE TITLE
form-data POST requests get empty body when viewing raw log in Postman Console

### ISSUE THREAD

**Issue by Chealer** [a85/POSTMan-Chrome-Extension#7272]
The entry for a POST request in Postman Console shows no body when it is built with form-data. This only occurs in the Raw view, not in Pretty.

1. Set up a POST request with a form-data body.
2. Create a field with key "foo" and value "bar".
3. Address it to - for instance - https://github.com/postmanlabs/postman-app-support/issues/5699.
4. Open the Postman Console.
5. Send the POST request.
6. Using the console, navigate to the tested POST request, and request the Raw view.

This will show the request headers, the response headers and the response body, but not the request body.

**Expected behavior**
The request body should show between the request headers and response headers.

**App information**
 - Native
 - Postman Version 7.6.0
 - OS: Windows

**Comment by arlemi** [comment]
This was fixed in 7.16.0 :)

**Comment by Chealer** [comment]
I confirm that I cannot reproduce in 7.17.

**Comment by jdgregson** [comment]
@Chealer Is this the same issue you were experiencing? If so I'm still seeing it in 7.18.
![2020-02-10_09-51-27](https://user-images.githubusercontent.com/3778841/74175660-1c27f580-4beb-11ea-996f-f16f27a3c46b.gif)

**Comment by Chealer** [comment]
No @jdgregson the problem was with form-data (not raw)
