### ISSUE TITLE
nodejs jar.clear is not a function 

### ISSUE THREAD

**Issue by bagrip** [a85/POSTMan-Chrome-Extension#7274]
I have tried new feature to clear all cookies and works fine in Postman and in Newman and throwing error when I run it using Nodejs. Error Message below
**jar.clear is not a function**

Please let us know how it can work using Nodejs.

**To Reproduce**
1. Create Collection using Postman, add below code under test tab
 **const jar = pm.cookies.jar();

jar.clear(pm.request.url, function (error) {
  // error - <Error>
});**
 
2. Whitelist domain
3. Export collection and run using Newman, should work fine
4. Now try to run same script using node **.js

**ERROR**
jar.clear is not a function

**Package.json**

 	"dependencies": {
		"async": "2.1.2",
		"handlebars": "^4.1.1",
		"inline-css": "^2.4.1",
		"moment": "^2.22.2",
		"newman": "^4.5.3",
		"newman-reporter-html": "^1.0.2",
		"nodemailer": "2.7.0",
		"request": "^2.88.0"
}

**Comment by bagrip** [comment]
@codenirvana @shamasis Please let me know if I need to update any package or change any syntax under Test tab

**Comment by codenirvana** [comment]
@bagrip How are you executing the collection using Node.js? Using Newman as a library?

**Comment by bagrip** [comment]
@codenirvana Yes, I am using Newman as library. 

```
const newman = require('newman'); // require newman in your project
 
// call newman.run to pass `options` object and wait for callback
newman.run({
    collection: require('./sample-collection.json'),
    reporters: 'cli'
}, function (err) {
    if (err) { throw err; }
    console.log('collection run complete!');
});

```

**Comment by bagrip** [comment]
@codenirvana Please let me know if there is any solution to this. Currently it is a blocker for me and I am using JMeter as workaround where I need to disable cookies in each request

**Comment by codenirvana** [comment]
@bagrip That's odd. Can you try executing `npm list newman` (within the same repository) and share the Newman version you are using locally?

**Comment by bagrip** [comment]
@codenirvana it is 4.5.4

```
`-- newman@4.5.4--

```

**Comment by codenirvana** [comment]
@bagrip That's odd. I am not able to reproduce this issue locally.
Is it possible to share the script with a scaled-down collection (without any sensitive data) which I can use to reproduce this issue?

**Comment by bagrip** [comment]
@codenirvana Actually this issue is not reproducible anymore

**Comment by bagrip** [comment]
@codenirvana Actually this issue is not reproducible anymore
