### ISSUE TITLE
Import collection overrides existing collection ( version problem )

### ISSUE THREAD

**Issue by barelnir** [a85/POSTMan-Chrome-Extension#728]
Hi,

First thank for lovely tool!

I use collections to share APIs with other developers
when I work on existing collection and add some new API's another developer already release newer collection version with new name. than when I import it overrides my collection change the collection name and delete my changes.

we change the collection name every time that we release new version and I want to be able to keep both in my postman

As I remember it worked in previous versions like that.

**Comment by stephandesouza** [comment]
Hi there, the overwrite feature is dead?

Tried this but only appears to make full replacement (Replace) , or a new collection copy (Import as copy).

Using Postman for Windows 7.0.9

**Comment by stephandesouza** [comment]
Nevermind, there is a newer issue: #5641
