### ISSUE TITLE
Override existing environment on import

### ISSUE THREAD

**Issue by bradwilder** [a85/POSTMan-Chrome-Extension#7280]
**Is your feature request related to a problem? Please describe.**
When I import a set of collections and environments, the collections will override existing collections by the same name. However, the environments do not do this. You end up with duplicate environments with the same name, making it difficult to navigate and remember which one is the "current" one. I end up having to remember to go in and delete all but the last one with a given name.

**Describe the solution you'd like**
It would be nice if importing an environment would override the existing environment with the same name.

**Describe alternatives you've considered**
The alternative, it seems, is just to manually delete the old environment after importing the new one.

**Comment by pleasedontbelong** [comment]
+1 on this....

**Comment by guillermocb** [comment]
+1, I would at least let the users multiselect to delete all at once

**Comment by akshaydeo** [comment]
We are working on a fix for this that will allow you to replace the existing environment 🙇‍♂ 

Related #9561

**Comment by dhwaneetbhatt** [comment]
This is fixed in the latest version. Closing this issue, feel free to reopen it if the issue persists.
