### ISSUE TITLE
Postman Pro - Lost all request bodies in my shared collection!

### ISSUE THREAD

**Issue by iFreeon** [a85/POSTMan-Chrome-Extension#7282]
**Describe the bug**
A bug in Postman Pro for Windows deleted all request bodies from my shared test collection containing 427 test cases.

**To Reproduce**
1. Wednesday 9/4 my Postman Pro was stuck in an all-day loop syncing
2. The morning of 9/5 I realized after rebooting Postman Pro was not able to recover and logged out. 
3. I was forced to agree to delete all local data as there was no other option
4. When I logged back in, everything synced and looked fine, this was about 10am on 9/5
5. Per the changelog, over multiple hours a Postman Pro bug deleted all the body entries of my shared collection.  This occurred while my machine was on and I was in meetings.
6. About 1pm the dev team noticed something was wrong with Postman Pro. 

**Expected behavior**
I expect:
1. Postman Pro sync to be reliable
2. Postman Pro support to be able to restore collections when software bugs cause issues
3. Postman Pro to have phone support for paying customers
4. Postman Pro changelog to not repeatedly crash when investigating issues
4. Postman Pro to NOT delete the body from all my requests!

**Screenshots**
NA

**App information (please complete the following information):**
 - App Type Native
 - Postman Version 7.6.0
 - OS: Windows 10

**Additional context**
Quality in Postman Pro has steadily declined over the past 2 years with the addition of un-necessary features.  This is our first critical issue and the lack of phone/email support raises serious questions if Postman Pro can support a 45-person team.

**Comment by cyrielle-hada** [comment]
@iFreeon sorry to hear about this issue - feel free [to submit a ticket](https://support.getpostman.com/hc/en-us/requests/new?_ga=2.99161561.69164091.1568014662-1387803517.1563368009) or email help@getpostman.com. We'll do our best to help.

**Comment by preethammavin** [comment]
@iFreeon were you able to get this sorted out, if not please write to us at help@getpostman.com so that we take a closer look.

**Comment by iFreeon** [comment]
I had a recent save of the data locally so we manually restored some of it to keep the team going.  I did lose another environment today (meaning it's gone from the shared envs) .. and I don't see a reason why.  Nothing in the audit trail.  I'll email for more help.  Thks.

**Comment by preethammavin** [comment]
@iFreeon while we look into the bug and get about fixing it, if you still see an issue in your production collection you can go to 
Collection-> Click on the arrow -> Click on changelog , you would see a set of revisions there you should be able to locate a version of the collection which was there before the body was deleted and restore it.

**Comment by asi-postman** [comment]
Hi @preethammavin, the customer @iFreeon created a support ticket (linked) mentioning that they couldn't locate any revisions in the changelog related to their *1.0 Local environment*. I wanted to relay the info from the Product Support side.

**Comment by preethammavin** [comment]
We have fixed the underlying issue and pushed an update, Kindly use the latest version of the Application.
