### ISSUE TITLE
Allow Saving as Example/File Even When Response Body is Empty

### ISSUE THREAD

**Issue by dennis-thomas-o** [a85/POSTMan-Chrome-Extension#7283]
**Describe the issue**
When the response body is empty, the Save Response button is grayed out. Many APIs return an empty response body but there is still important information in the response headers which is useful to save. Even in cases where the headers don’t have useful information, it would still be useful to save the HTTP status code and the request that lead to it.

**To Reproduce**
1. Create a new HEAD request with the request URL set to https://google.com.
2. Click Send.

**Expected behavior**
Save Response button is clickable and functions normally.

**Screenshots**
![image](https://user-images.githubusercontent.com/36053409/64479863-3fa5ca80-d18b-11e9-845c-5808b809494f.png)

**App information**
 - App Type: Native App
 - Postman Version: 7.6.0
 - OS: Windows 10 Enterprise

**Additional context**
*None*

**Comment by sujayvenaik** [comment]
Hey,
We do allow this. From the screenshot what I can see it's an unsaved request hence not allowing to save response. 
Once if you save this request to any collection, then you can go ahead and save responses for this.

**Comment by dennis-thomas-o** [comment]
See below, the button is grayed out even after saving.

![image](https://user-images.githubusercontent.com/36053409/64480258-4421b180-d192-11e9-939a-965c7f8a61b4.png)

**Comment by saswatds** [comment]
Hi @dennis-thomas-o, Thanks for reporting this.
I can confirm that this is a bug from our end. We will get it fixed ASAP.

**Comment by saswatds** [comment]
Hi this issue has been fixed in the latest version of the app v7.9.0. 
Closing this issue now. Feel free to re-open incase you find otherwise.
