### ISSUE TITLE
Body are missing for the POST method

### ISSUE THREAD

**Issue by jyothihotkar** [a85/POSTMan-Chrome-Extension#7284]
I am not sure why this is happening.
But have created new Workspace recently.
When ever i migrate from one to another the Body of the POST method requests are missing.
PFA the screenshots.

![image](https://user-images.githubusercontent.com/55076157/64505870-1011d200-d2f3-11e9-850a-a69d6f8971c4.png)
![image](https://user-images.githubusercontent.com/55076157/64505839-e5c01480-d2f2-11e9-80ad-5502c5f010f2.png)
![image](https://user-images.githubusercontent.com/55076157/64505847-ed7fb900-d2f2-11e9-8d87-6a95f9aed0ac.png)
![image](https://user-images.githubusercontent.com/55076157/64505859-fec8c580-d2f2-11e9-9575-e8e5c417130c.png)

Can you please help me with this?

**Comment by shamasis** [comment]
@jyothihotkar ... which version of app is this? I tried using app 7.6.0 by saving a tiny JSON post body in a collection and shared the same with another personal workspace of mine ... the body moved along with it. Can you do a "view in web" of the collection to see if everything is synced all right.

**Comment by jyothihotkar** [comment]
@shamasis Even I have the Version 7.6.0 , but the issue was before it got updated. And not sure if the issue still persists .
And everytime I create an automation suite I do sync all my data.
Is there any way to get back my data which is lost?

**Comment by preethammavin** [comment]
@jyothihotkar can you check with the view in web for the collection you mentioned and see if the body was synced to the cloud? 

Also please write to us at help@getpostman.com with the github id so that we can take a closer look

**Comment by ntbrierly** [comment]
What was the resolution for this?  I'm running into this issue as well, I lost several days worth of work.  I tried to turn off syncing but apparently you can't do that without signing out. I'm using the latest version of Postman 7.11

**Comment by jsmnfaye** [comment]
I see this was originally opened in 2019 but I'm still facing this issue now in version 9.14.11 for Mac. I just moved some requests from a different folder to another.
