### ISSUE TITLE
I cannot reset my password

### ISSUE THREAD

**Issue by 254289211** [a85/POSTMan-Chrome-Extension#7287]
when I click the button which name is "Trouble signing in?" , I get a page which have a input of Email。after this  ,the page do nothing,  I can't reset my password .   Is it because I am in China?

**Comment by cyrielle-hada** [comment]
@254289211 when you go the [trouble sign-in page](https://identity.getpostman.com/trouble-signing-in) - are you able to hit submit and get the below confirmation message? 

<img width="414" alt="Screen_Shot_2019-09-09_at_17_35_35" src="https://user-images.githubusercontent.com/47351631/64545066-63eade00-d328-11e9-8aba-3d403301c2f4.png">

Feel free to contact the support and [submit a ticket](https://support.getpostman.com/hc/en-us/requests/new?_ga=2.97925592.69164091.1568014662-1387803517.1563368009) or email help@getpostman.com for this issue.

**Comment by preethammavin** [comment]
Closing the issue for now, please feel free to reopen it or reach out to help@getpostman.com so that we can get it resolved for you.
