### ISSUE TITLE
Published documentation broken and throws an error 403  

### ISSUE THREAD

**Issue by cyrielle-hada** [a85/POSTMan-Chrome-Extension#7289]
_Filed by Product Support_

**Describe the bug**
Accessing the published documentation under the custom domain https://docs.dayuse.io throws an error 403. 

- The collection published under the domain is owned by the Admin of the team. 
- The collection belongs to a Team workspace.

**Screenshots**
<img width="1407" alt="Screen_Shot_2019-09-09_at_15_57_54" src="https://user-images.githubusercontent.com/47351631/64537839-dd300400-d31b-11e9-8f4e-45a5156ba8cd.png">

**App information**
- Team has not migrated to version 7
- The issue has been noticed on September 6th, 2019

**Comment by Cazaimi** [comment]
@Raja-Simha , investigating.

**Comment by hhamon** [comment]
Hi!

Do you have any news to provide please? It's a little complicated for us to experience this problem for a week now...

**Comment by Cazaimi** [comment]
Hi @hhamon , sorry to hear that. 

We've identified that this documentation was published by a user who's now left your Postman team. As a result, you're getting the error above.

Un-publishing -> republishing the collection should solve this issue. Please feel free to respond to this thread for any further queries.

**Comment by hhamon** [comment]
Hi @Cazaimi,

It's back using this trick! Thank you very much ;)

**Comment by Cazaimi** [comment]
@hhamon, Happy to help :)

@Raja-Simha please mark this as closed.
