### ISSUE TITLE
Lost all settings due to being logged out

### ISSUE THREAD

**Issue by TomFaulkner** [a85/POSTMan-Chrome-Extension#7290]
I had not used the app for some time and was forced to login, when I chose to log out instead everything was deleted on me. Then in frustration I logged in and my settings were still gone. I realize you are trying to make money, but your insistence on the accounts and the consequences of using them removing all local data is ridiculous. I would rather use shell scripts and curl at this point, at least then I know my data is safe.

**Comment by preethammavin** [comment]
@TomFaulkner Wanted to know if you are talking about the synced collection and environments or app settings?

We ask the signed-in users to re-authenticate to ensure safety of the users data, on which you can re-authenticate/choose to logout.
On Logout all the saved data is still synced to the cloud and will available once you login, the only thing that is not available or synced will app settings (example theme,pane layout setting, etc) which only stored locally.

We do not insist on everyone signing up, only encourage to ensure that users data is backed up and available for him/her to use and also to provide features which require the user to be signed-in.

**Comment by TomFaulkner** [comment]
App settings were lost, even after logging back in.

"We ask the signed-in users to re-authenticate to ensure safety of the users data, on which you can re-authenticate/choose to logout."

Presumably if I am able to launch the program I already have access to the filesystem and all locally stored data anyway, this isn't protecting much.

Is there a way to logout without losing anything, so I can go back to not using your cloud service, and relying on it being up and such?

**Comment by preethammavin** [comment]
@TomFaulkner The raw format of the data can ge found in the file system, but there are certain variables which would not be found in the local system and are are held in the session. 

The app settings are not synced to the cloud yet, this is something we are working on enabling. While we do encourage you to keep the data backed up into the cloud, as this ensures that there is always a backup of your work on Postman in could for you to retrieve anytime you can use the app in a logged out state which keeps everything local.

If you want to transition, login into the app export all data and can logout. You can import the data and continue to work in the logged out state.
