### ISSUE TITLE
Logs missing from console unless console is opened before HTTP requests sent

### ISSUE THREAD

**Issue by mcandre** [a85/POSTMan-Chrome-Extension#7291]
**Describe the bug**

The Postman developer console does not contain any information about errors that were just triggered, unless the console had already been open. Please make sure all errors, such as those triggered by the Get New Access Token form, populate the console, whether it was open or not at the time.

**To Reproduce**
1. Enter an invalid access token configuration.
2. Open the console.

**Expected behavior**

The console shows all HTTP responses for the current Postman graphical session, regardless of whether the console was open at the time or now.

**Comment by ritwijsinha** [comment]
Hello, @mcandre. We have added this feature in the new Postman Console. Kindly update to Postman v7.10 for the same.
