### ISSUE TITLE
Remove option to select Static IP for Free and Pro plans

### ISSUE THREAD

**Issue by cyrielle-hada** [a85/POSTMan-Chrome-Extension#7293]
**Describe the bug**

When setting up a monitor **from the native app** - free and pro users are able to select US east and west regions, Static IP while this option is available on the Enterprise plan only. 

Learning Center article - [Running Postman monitors using static IPs](https://learning.getpostman.com/docs/postman_enterprise/using_static_IPs_to_monitor/?_ga=2.102694342.69164091.1568014662-1387803517.1563368009)

<img width="1328" alt="Screen Shot 2019-09-10 at 10 14 24" src="https://user-images.githubusercontent.com/47351631/64596404-1ddb5c00-d3b4-11e9-98a2-a1362c6e953d.png">

When selecting them and hitting the button Create it results in a Something went wrong error. 

<img width="1333" alt="Screen Shot 2019-09-10 at 10 16 35" src="https://user-images.githubusercontent.com/47351631/64596398-1b790200-d3b4-11e9-892b-cd1fc7cf0a7d.png">

**To Reproduce**
1. Go to the native app
3. Select a collection > Create a monitor 
4. Select US (East, Static IP) and/or US (West, Static IP)
5. Click Create
6. See Something Went Wrong error. 

**Expected behavior**
Not being able to select those regions if a user is under the Free plan or Pro plan.

**Comment by ArjunSingh-PM** [comment]
@cyrielle-hada, This issue is fixed. Can you please confirm that this works correctly for you now.

**Comment by cyrielle-hada** [comment]
Yep, this works. 👍

**Comment by cyrielle-hada** [comment]
@ArjunSingh-PM not sure if the fix applied here affected the following issue but now Enterprise users, when they want to select static IP are seeing a wrong message. 

![Unbenannt](https://user-images.githubusercontent.com/47351631/69067532-1fac4600-0a1b-11ea-8ab0-83b1c681463b.png)

I believe it should say something different like "Enterprise users can request the static IP option from our Enterprise [support team](https://www.getpostman.com/support)"

Please let me know if you want me to open a separate GitHub issue.
