### ISSUE TITLE
not getting API validation message from docker on postman

### ISSUE THREAD

**Issue by ghost** [a85/POSTMan-Chrome-Extension#7295]
i have created API using plumber.R and  i have added json schema to validate the input request,incase validation fails ,in plumber.R file function json:validator throw the error and error message (eg: 'data.ModelInputData.0.AP_STUS_CD must be an enum value') .

Same i tested locally using RStudio and postman and it worked,but when same code i deployed in docker using dockerfile and when i pushed the message from postman i am getting 500 error but it is not throwing validation message or error message(why validation failed).attaching the dockerfile and plumber.R files.
[files.zip](https://github.com/postmanlabs/postman-app-support/files/3595384/files.zip)

<img width="611" alt="local_test_Rstudio" src="https://user-images.githubusercontent.com/55128114/64609806-5c403d80-d3eb-11e9-9ebd-b8dcfc3ba66b.PNG">
<img width="370" alt="tested_from_docker" src="https://user-images.githubusercontent.com/55128114/64609815-619d8800-d3eb-11e9-8636-af75dbc99e09.PNG">

**Comment by codenirvana** [comment]
@shrads14 Thanks for reporting this but looks like the issue is not related to Postman.
We recommend reaching out to the wider Postman Community (https://community.getpostman.com/) for help with issues like these.
