### ISSUE TITLE
postman crash on any command send

### ISSUE THREAD

**Issue by d199** [a85/POSTMan-Chrome-Extension#7298]
**Describe the bug**
Postman app crashes upon send of any request

**To Reproduce**
1. Start the App
2. Pick any request
3. Hit Send
4. The App crashes within a second or two.

**Expected behavior**
A response is expected

**Screenshots**
If applicable, add screenshots to help explain your problem. Please make sure the screenshot does not contain any sensitive information such as API keys or access tokens. 

**App information (please complete the following information):**
 - App Type [Win64 Native App]
 - Postman Version [e.g. 7.6.0]
 - OS: [Win64]

**Additional context**

**Comment by codenirvana** [comment]
@d199 Please share more detail about the request.
App version, is it using pre-request or test scripts, etc? 

Is it crashing on sending a new request to `postman-echo.com/get` as well?

**Comment by d199** [comment]
@codenirvana , postman collections work fine. Postman is the latest version - 7.6.0
To isolate, I did some test and found out, just using the provided in the example below, crashed the app:
https://knowledgecenter.2checkout.com/API-Integration/REST_5.0_Reference#/reference/product/retrieve-product-info-by-code/working-example:-retrieve-product-info-by-code

No pre-script, no test script, no environment, no headers, no params - just cut-n-paste the URL and 'Send' - the app crashes.

No issues in accessing other services. May be this service is sending something funny ? However, my other friends, have no issues in accessing the service.

Any logs etc. I can get ?

**Comment by d199** [comment]
Recreated environments, which stopped the crash. Not sure what it was.
