### ISSUE TITLE
Collection runner uses disabled (unchecked) collection variables

### ISSUE THREAD

**Issue by adaniels85** [a85/POSTMan-Chrome-Extension#7299]
**Describe the bug**
Disabled collection variables are not ignored by the Collection Runner. However, they are ignored when sending the same request from the main Postman window.

**To Reproduce**
1. Create a new collection
2. Add a collection variable and disable it by unchecking it.
3. Create a new request
3. In the pre-request script of that request, print the variable out with console.log
4. Open Postman console
5. Send request from main window by clicking send button.
6. 'null' should be printed.
7. Now open the Collection Runner and execute the same request. In Postman console, the disabled variable value should be printed this time.

**Expected behavior**
I would expect null to be printed in the console when the request is run from the collection runner, just as it is when the request is run from the main window. The main reason this is a problem for me is that I often define multiple values for a collection variable with the same name, but only check the one I want for a particular run. As it is currently, the variable defined last in the list with that name is used in the script, whether or not it's disabled.

**App information (please complete the following information):**
 - Native App
 - Postman v7.6.0
 - Windows 10 Enterprise Version 10.0.18362 Build 18362

**Comment by codenirvana** [comment]
@adaniels85 Thanks for reporting this issue. I can confirm its happening with only collection runner.
Will update once the fix is available in our canary or production channel.

**Comment by codenirvana** [comment]
Fixed in Postman v7.10.0.
