### ISSUE TITLE
404 Error when GET request has accent

### ISSUE THREAD

**Issue by yjhidalgoh** [a85/POSTMan-Chrome-Extension#7300]
**Describe the bug**
GET Requests using accent (á, é, í, etc...) fails with 404 - Not found error.

**To Reproduce**
I'm using IBM OpenPages GRC Platform REST API request to grc/api/security/groups/AccéntTestGroup

The same request using the number ID instead of the name ID works successfully and using other REST API tools like Advance REST Client works successfully using both; number and name ID.

I suppose you can reproduce using any other application.

**Expected behavior**
It's obviously an issue with PostMan because you can get the object information in the body using other REST API Clients.

**App information:**
 - App Type Native App
 - Postman Version 7.6.0
 - OS: macOS Mojave 10.14.6

**Comment by codenirvana** [comment]
@yjhidalgoh That's because currently, we are not automatically encoding the accent character in URL pathname. Check if changing the path to `/Acc%C3%A9ntTestGroup` fixes the issue.

Closing this issue as we are tracking this and similar URL encoding related issues here: #4555

**Comment by vikiCoder** [comment]
Hi, this is fixed in the latest [Postman Canary](https://www.postman.com/downloads/canary) release (version 7.20.0-canary03). You can see more details about the fix at #8154
