### ISSUE TITLE
 My Postman Profile Has Been hacked

### ISSUE THREAD

**Issue by GitOffice** [a85/POSTMan-Chrome-Extension#7302]
I have received this email. It means whether my postman profile has been injected by hackers. Please verify it. Thanks.
-------
Dear Postman User,

This message is to confirm that the Postman profile belonging to 加QQ号359640790领88沅链接982095com, was recently updated.

If you need additional assistance, or you did not make this change, please contact help@getpostman.com.

**Comment by preethammavin** [comment]
@GitOffice can you write to us at help@getpostman.com from the registered email id, so that we can take a closer look?
