### ISSUE TITLE
field 'status' in responseBody impossible to focus

### ISSUE THREAD

**Issue by Galand-V** [a85/POSTMan-Chrome-Extension#7303]
**Describe the bug**

I want to check the result in a field that is named 'status'. The issue is that 'status' is considered as a method in Postman so I cannot target it

## Test : 

```
var response = JSON.parse(responseBody);

//Test 
pm.test("There is a String Status", function(){
    pm.expect(pm.response.status).to.eql('PARTIALY_RECEIVED');
});


```

 ## ResponseBody
```
{
    "order_id": "1190900076098",
    "status": "PARTIALY_RECEIVED",
    "name": "TNR_POSTMAN",
    "currency": "EUR",
    "creation_date": "2019-09-11T07:13:30.781+0000",
    "delivery_date": "2019-09-11T00:00:00.000+0000",
    "comment": "TNR_POSTMAN_Comment",
    "list_order_line": [
        {
            "supplier_number": "222222",
            "item_code": 767767,
            "unit_price_ht": 1,
            "unit_price_ttc": 1.2,
            "unit_price__supplier_ht": 1,
            "quantity": 10,
            "item_supplier_name": null
        }
    ]
}
```

### Expected

pm.response.status => Does focus the field 'status'

Or add a syntax to override the 'status' as in SQL

### Current
As http returnCode is 200, the test does not focus the responseBody

![image](https://user-images.githubusercontent.com/29098010/64682647-1b473800-d482-11e9-9c7c-a21bfb6c829f.png)

`There is a String Status | AssertionError: expected 'OK' to deeply equal 'PARTIALY_RECEIVED'`

**App information (please complete the following information):**

 - Postman Version 6.7.4
 - OS: Windows 10

**Comment by vdespa** [comment]
@Galand-V 

Try the following:

```
const response = pm.response.json();

//Test 
pm.test("There is a String Status", function(){
    pm.expect(response.status).to.eql('PARTIALY_RECEIVED');
});
```

**Comment by Galand-V** [comment]
Arg, I did not saw that...

That works, thank you !
