### ISSUE TITLE
Basic Auth inherited from collection is not refreshed when switching to forked workspacece

### ISSUE THREAD

**Issue by wiepretini** [a85/POSTMan-Chrome-Extension#7304]
**Describe the bug**
When creating a Workspace with requests all inherit Basic Auth a single collection and then forking this collection to different workspace and then switching between the 2 workspaces, postman sometimes tries to use the variable values from the previous workspace.

**To Reproduce**
1. Create Workspace 1
2. Create Environment 
3. Create Varibale "user" in environment
4. Create Variable "password" in environment
5. Create Collection 1 
6. Choose Collection authentication type Basic Auth and enter {{user}} and {{password}} 
7. Create Request 1 and choose inherit Authorization from parent
8. Create Workspace 2
9. Create a Fork of the Collection 1 as Collection 2 into Workspace 2 and ensure to create a new environment but with the same variables but different values as in Workspace 1.
10. Start triggering request in Workspace 1 
11. Start triggering request in Workspace 2
12. Review Postman console: user and password of Workspace 1 are used in Workspace 2

**Expected behavior**
Pull variable values from the selected Workspace and environment and do not use variable values from previously used workspace and environment.

**Screenshots**
![image](https://user-images.githubusercontent.com/40268445/64706625-18643b80-d4b2-11e9-9d05-7e9a81d45fc5.png)

**App information (please complete the following information):**
 - App Type Native App
 - Postman  Version 7.6.0
 - OS: Windows 10 win32 10.0.17763 / x64

**Comment by vikiCoder** [comment]
Hi @steffenwieprecht,

I tried to follow the steps you provided to reproduce the issue. It is working as expected for me in the latest Postman app (v7.20.0). Please update to the latest Postman app and see if you are still facing the same issue. Below is a screen recording that shows that the credentials are sent according to the workspace and its environment values as expected.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/16588032/76729062-50f51280-677e-11ea-8e01-7aeb9cbe2e8f.gif)

**Comment by vvs11** [comment]
Hi @steffenwieprecht, Please let us know if you're still facing this issue by trying it out on the latest version

**Comment by vvs11** [comment]
@steffenwieprecht closing this for now. Feel free to re-open if you're still facing this
