### ISSUE TITLE
Unable to invite user to workspace - Something went wrong

### ISSUE THREAD

**Issue by cyrielle-hada** [a85/POSTMan-Chrome-Extension#7312]
_Filed by Product Support on the behalf of the user_

**Describe the bug**

The admin of the team workspace tries to invite another user.

After hitting the button `Save Changes` - it throws the below `Something went wrong` error.  

![image](https://user-images.githubusercontent.com/47351631/64795396-5038b500-d57e-11e9-99bb-8fbead12a296.png)

The user used to be on Enterprise plan and downgraded to Pro. 
Supposition: the workspace used to be a private workspace - which is a feature that is not available in Pro. 

**Expected behavior**
Invite the user to join the workspace successfully. 

**App information (please complete the following information):**
 - All users have migrated to version 7.

**Comment by sankalp0o** [comment]
This issue has been solved! Closing this for now but please let us know if you encounter this again.
