### ISSUE TITLE
Ability to exclude XML Response Headers from XML Response Body in files returned from services

### ISSUE THREAD

**Issue by DallasAnderson** [a85/POSTMan-Chrome-Extension#7313]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
I'd like the ability to exclude the XML response headers from xml response body in files that are returned. 

I have a SOAP/WCF service that returns TIFF and TXT files as attachments. Those files become unreadable when the response header is included in the files, opposed to only the content of the body. 

**Describe alternatives you've considered**
We use Postman extensively for our documentation of services, both REST and WCF/SOAP. I've not explored other alternatives. 

**Additional context**

**Comment by DallasAnderson** [comment]
Do you all need anything from me on this?

**Comment by codenirvana** [comment]
@DallasAnderson I am a little confused about your use case.
If you want to modify the response body (or represent in different forms), I suggest exploring the new [Visualizer](https://learning.getpostman.com/docs/postman/sending_api_requests/visualizer/) feature.

**Comment by vvs11** [comment]
@DallasAnderson closing this for now. Please feel free to reopen if you need anything else around this issue
