### ISSUE TITLE
PUT /collections/{{collection_uid}} returns "This collection already exists in the database."

### ISSUE THREAD

**Issue by skplunkerin** [a85/POSTMan-Chrome-Extension#7315]
**Bug:**
a Postman API endpoint returning an undocumented error. There's no info as to what/how to fix this.

**Endpoint:**
`PUT /collections/{{collection_uid}}`

**JSON file:**
the file is too large to add here and has some sensitive data I'll need to scrub. Let me know if the file is needed to identify the problem and I'll scrub it and share where you need it

**Info:**
Our team uses Swagger and Postman. We use `swagger-parser` and `openapi-to-postmanv2` to create a bundled/dereferenced swagger file that we then convert to Postman format used for updating our Postman collection.

Hitting `PUT /collections/{{collection_uid}}` with the `openapi-to-postmanv2` file works (as expected), but occasionally we'll get a `400` error that shouldn't be one of the `PUT` responses (according to your docs):

```
{
    "error": {
        "name": "instanceFoundError",
        "message": "This collection already exists in the database."
    }
}
```

**@ShiftDevUser** had the same problem with this `PUT` endpoint _([community question here](https://community.getpostman.com/t/publishing-documentation-to-custom-urls-for-each-environment/7088/4))_. We tried replacing `"id"`, `"_postman_id"`, and other found data but it didn't fix this.

Our converted Postman file is too large (33,000+ lines) to try to understand where/what is causing this unknown error. We would love help as to what/where we should look for that would cause this error?

**Expected Behavior**
We're not creating new data, or patching data ontop of what's currently there. This error would make sense from a `POST` endpoint (and maybe from a `PATCH` endpoint?), but not from a `PUT` endpoint. I believe `PUT` should overwrite the whole JSON object. To my knowledge,  this endpoint isn't creating anything new that would cause a conflict like this.

**Additional context**
So far re-running the `openapi-to-postmanv2` converter (which creates new `SchemaFaker` data even though no changes to the docs were made) will fix the issue, allowing us to `PUT` again. This is ok, but doesn't let us know where or what the issue is. We would like to fix this, instead of re-running the converter over-and-over until the output works.

I've confirmed this happens when I hit this endpoint via our Rails app, and from the Postman UI.

**Comment by preethammavin** [comment]
@skplunkerin please write to us at help@getpostman.com with the collection id, and the scrubbed collection so that we can get to the bottom of this.

**Comment by skplunkerin** [comment]
Thanks @preethammavin & @ankitjaggi , I just tried the JSON collection that was failing with this error and it no longer fails, it updates as expected. I'm not sure if anything change on your side, but everything seems to be working fine now. I'll let you know if this happens again, thanks!

**Comment by VicKetchup** [comment]
@preethammavin  @ankitjaggi I am currently facing this issue with a collection that I am trying to pull changes into. Shall I message help@getpostman.com as well or are you able to recommend some steps to fix this?

**Comment by preethammavin** [comment]
@VicKetchup are you facing an issue with pulling changes into a forked collection? 
It would be great if you can message on help@getpostman.com, with the collection id and the exact error you saw. We will try to get to the bottom of this asap.

**Comment by pf-lkobbe** [comment]
I've also had this issue. It was apparently caused by trying to put items into a new collection when this item already existed in another collection. I solved it by deleting the id property in each item, as well as each item.response and item.event prior to updating the collection.
