### ISSUE TITLE
Lates update of postman client updated  all post request Body to Text

### ISSUE THREAD

**Issue by ypatel26** [a85/POSTMan-Chrome-Extension#7318]
All my post requests post body format  is updated to Text. It was Json.

I have to upated all my tests manually now.

I'm non pro version.

Postman for Windows
Version 7.7.0
win32 10.0.17134 / x64

**Comment by shamasis** [comment]
@ypatel26 ... thanks for reaching out. We are looking into it. Our team would get in touch for more information.

**Comment by prlofty** [comment]
Similar story for me.
Updated to V7.7.2 (Win64) this morning. 
I have several SOAP requests, which were working fine when the body was set to 'raw' and 'XML'
After the update, these requests will only generate a proper response if I use any language choice except XML.

I'm happy to assist further.

**Comment by codenirvana** [comment]
@ypatel26 This issue is fixed in the latest version of the Postman app.

@prlofty can you check what's the `Content-Type` request header sent when the request fails or works?

**Comment by ypatel26** [comment]
@codenirvana  Thanks.  Yep it's fixed in V7.7.2 for me.  Appreciate the quick turnaround.

**Comment by prlofty** [comment]
@codenirvana  - I have run the five language types using the same message:

Type - Language - Response Content Type - Success/Fail

raw - Text - text/xml; charset=UTF-8 - SUCCESS
raw - JavaScript - text/xml; charset=UTF-8 - SUCCESS
raw - JSON - text/xml; charset=UTF-8 - SUCCESS
raw - HTML - text/xml; charset=UTF-8 - SUCCESS
raw - XML - application/xml; charset=UTF-8 - FAIL

**Comment by codenirvana** [comment]
@prlofty Selecting `XML` by default adds `Content-Type` as `application/xml` but you can update the `Content-Type` header manually to `text/xml` which I suppose is required in this case.

**Comment by prlofty** [comment]
@codenirvana - Thanks. Forgive my ignorance, I'm a big fan of Postman but only a beginner.
I had made no changes to the messages since the update. The languages cannot be specified in the same way as before. I will set the content type manually as advised.

**Comment by gonzalojorge** [comment]
I also noticed that since the latest release 7.7.2 the `XML` header defaults to `application/xml` where previously the default option was `text/xml`. Now this option is no longer even available in the drop-down menu and we need to manually change all of our headers from `application/xml` to `text/xml` to make our SOAP requests work.
Not sure if there are plans to re-enable this form the drop down view? (similar to what is visible in the UI version available previously: https://blog.getpostman.com/2017/11/18/postman-makes-soap-requests-too/)
Thanks

**Comment by SebaPrati** [comment]
I am having THE SAME problem and started with version 7.7.2. This [GitHub #2366] - Disabled automatic addition of content-type header... is assuming that ALL applications will accept application/xml. ALL my requests were working fine as text/xml. 
PLEASE FIX ASAP. It is affecting multiple users. Thanks

**Comment by saswatds** [comment]
@SebaPrati @gonzalojorge the issue you are facing is related to this issue https://github.com/postmanlabs/postman-app-support/issues/7346. We are on top of this and will be releasing the fix soon.

**Comment by codenirvana** [comment]
@ypatel26 @prlofty @gonzalojorge This issue is fixed in the latest Postman app `v7.7.3`.
Can you update your app and confirm if that fixes your issue?

**Comment by SebaPrati** [comment]
Not sure what is the use case that Postman team think is right. If I have a previous Content-type value, and then I go and select THE SAME type in the dropdown (Text, Javascript, JSON, HTML or XML) then my value is overwritten by your default value.
The fix is not breaking old collections anymore, but not sure if this current behavior is exactly the same in the previous versions.
My 2 cents: bring back all the Content-types as in previous releases...it was ok back then. Thanks

**Comment by codenirvana** [comment]
> The fix is not breaking old collections anymore

@SebaPrati Thanks for the confirmation.

> my value is overwritten by your default value.

I understand your frustration and in the upcoming release, we'll remove the authoritative override of the `Content-Type` header and will respect your custom header value (if set else defaults to language default on runtime).

> not sure if this current behavior is exactly the same in the previous versions.

Yes, It is.

> bring back all the Content-types as in previous releases

Right, but this change allowed us to fix other issues like #5127, #6615, etc.
Also, the selection of raw body language can't be tied with the `Content-Type` header as it caused other issues in the past (#2366).

Our intention with this change (once we remove the authoritative override of the header) is:
- Always respect user-provided headers in UI
- Remove all UI auto-manipulation of content-type headers
- Add sensible defaults if no content-type is provided (during runtime)

I would like to know what's your use-case (content-type, is it XML?)

**Comment by SebaPrati** [comment]
Hello @codenirvana , thanks for your reply.
Essentially we have 3 use cases:
SOAP/XML:
Body: raw/XML
Content-type: text/xml
REST/JSON number 1: 
Body: raw/Text
Content-type: application/x-www-form-urlencoded
REST/JSON number 2: 
Body: raw/JSON
Content-type: application/json

Thanks!

**Comment by prlofty** [comment]
Hi @codenirvana 

I am also using:
SOAP/XML:
Body: raw/XML
Content-type: text/xml

I have updated to 7.7.3. When I create a new request, and select raw/XML the content-type defaults to application/xml.
I still have to manually update the content-type in the Headers tab for my request to work.

Postman has not converted my existing requests. They have remained as set yesterday to text/xml.

**Comment by scriptwriter76** [comment]
Has this issue been resolved? I have the latest version of Postman, but I can still not update my content-type from application/xml to text/xml

**Comment by LoloIrie** [comment]
Hi,
@shamasis Any chance to see the option for content type "text/xml" back in the dropdown menu ?
it would be really helpful
Thanks anyway.

**Comment by shamasis** [comment]
> Hi,
> @shamasis Any chance to see the option for content type "text/xml" back in the dropdown menu ?
> it would be really helpful
> Thanks anyway.

@LoloIrie the drop-down is an indicative helper alone. It will prevent you from making a failed request if you missed adding the right header your API needs. If I recall correctly, sometime mid last year, we added feature that shows what headers were being overridden when you add what your API actually needs.

Here is a screenshot below showing the same in action
<img width="1008" alt="Screenshot 2021-02-17 at 1 15 45 PM" src="https://user-images.githubusercontent.com/232373/108172366-c4d43380-7122-11eb-9f96-7f8cc0207a03.png">

**Comment by LoloIrie** [comment]
Thanks for the answer, really appreciated !!!
I know about this option to overwerite the Content-Type Parameter and use it, but earlier there was both options for XML  (application/XML and text/XML) in the dropdown menu and it was really easier/faster to use/switch. No way to get this feature back ?
