### ISSUE TITLE
multipart/form-data with Monitor does not set the boundary tag

### ISSUE THREAD

**Issue by xk0der** [a85/POSTMan-Chrome-Extension#7320]
**Describe the bug**
When passing POST payload as `multipart/form-data` Postman App correctly adds the `boundary` tag and formats the body payload to use the `boundary` tag to demarcate the data.

Whereas the same request run from Monitor does not add the `boundary` tag, thus the endpoint servers fail to process the requests. (Most likely you would get a HTTP 400)

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a Collection with a request
2. Add a `Content-Type` header with `multipart/form-data` value.
3. Add some data under **body** tab by selecting`form-data` 
4. Send the request and verify it works fine.
6. Add a monitor to this Collection.
7. Run the monitor and see that it fails with HTTP 400 
8. If you log the `pm.request` object in *Pre-request scripts* and *Test scripts* you will see that a boundary tag is added when run from the Postman client, and not when run from Monitor.

**Expected behaviour**
The monitor should correctly add the boundary tag when multipart/form-data type is selected, as well as properly format the payload.

**Screenshots**
If applicable, add screenshots to help explain your problem. Please make sure the screenshot does not contain any sensitive information such as API keys or access tokens. 

**App information (please complete the following information):**
 - App Type: Native + Web Monitor
 - Postman Version : 7.6
 - OS: Mac OSX

**Additional context**
Logged by Postman on behalf of a user.
More details provided internally.

**Comment by godfrzero** [comment]
Closing as this should be fixed now. Feel free to reopen it if the issue recurs.
