### ISSUE TITLE
Merging a collection back to parent collection results in an error

### ISSUE THREAD

**Issue by xk0der** [a85/POSTMan-Chrome-Extension#7321]
**Describe the bug**
Merging a collection back to original/parent collection thrown an error straight-away once you land on the web-dashboard.

**To Reproduce**
I was unable to replicate using my own setup but at the User's following always throws the error.
Steps to reproduce the behaviour:
1. Select the Forked collection
2. Click "merge changes" either from the app or from Web-dashboard
2. You get the error stating "Cannot merge changes"

User tries using different browsers, and same result.

**Expected behaviour**
A diff should be displayed and the user should be able to merge changes.

**Screenshots**
Following error is seen as soon the user lands on the webpage after clicking merge changes
![image](https://user-images.githubusercontent.com/21366/64931114-75813800-d88a-11e9-922d-37312973c484.png)

**App information (please complete the following information):**
 - App Type : Postman Native
 - Postman Version: 7.6
 - OS: macOS

**Additional context**
Logged by Postman on behalf of a user.
More details available internally.

This issue is similar to the one posted here: https://github.com/postmanlabs/postman-app-support/issues/6397
Since I had more details available for this user, logging it as a separate item for tracking.
Merge and close with #6397, if required.

**Comment by DannyDainton** [comment]
Hey @xk0der,

Is this still an issue in the latest version?

**Comment by xk0der** [comment]
I was unable to reproduce this issue - closing, next!
