### ISSUE TITLE
UI cutoff in two-pane layout

### ISSUE THREAD

**Issue by numaanashraf** [a85/POSTMan-Chrome-Extension#7324]
**Describe the bug**
While using two pane layout, resizing the pane to the lowest width allowed breaks the tabs and comments UI.

**Screenshots**
<img width="586" alt="Screenshot 2019-09-16 at 1 41 01 PM" src="https://user-images.githubusercontent.com/3295568/64950272-93ee3000-d898-11e9-9721-322837760dcc.png">

**App information (please complete the following information):**
 - App Type: Postman for Mac
 - Postman Version 7.7.1
 - OS: macOS 10.14.4

**Comment by coditva** [comment]
Fixed in Postman `v7.21.0` 🎉
