### ISSUE TITLE
[Linux] Not able to open Postman after v7.7.1 update

### ISSUE THREAD

**Issue by harryi3t** [a85/POSTMan-Chrome-Extension#7326]
We've identified an issue in Postman for Linux versions 7.7.0 and 7.7.1 that impacts Postman's in-built updating functionality. Postman users on this version would notice that, after updating the app from one of these affected versions, the directory that should contain the Postman executable would no longer exist.

*Note: This affects users on Linux who has downloaded the app from the Postman website and are on 7.7.0 or 7.7.1. This does not affect the users who installed Postman from [snap](https://snapcraft.io/postman) or are on Windows or Mac.* 

We've identified the root cause of the issue to a change we introduced in 7.7.0. Postman performs a cleanup activity after an update to remove previously installed versions and in v7.7.0, this activity is being run for the new version as well, leading to the directory getting removed completely.

We have fixed this in v7.7.2, but this does not automatically resolve the issue for our users who have already updated to version v7.7.0 & v7.7.1.

If you are impacted by this issue we suggest the following workaround:
1. Delete the directory that contains the Postman app
2. Re-install the app from [here](http://dl.pstmn.io/download/version/7.7.2/linux).

*Note: This issue does not affect your local saved data in any way as Postman stores your data in a directory that is different from where the app is installed. Once you re-install Postman all your local data will be available.*

**Comment by jviotti** [comment]
Closing this notice issue, now that most users are on v8 or v9
