### ISSUE TITLE
Unable to Delete API's removed from a workspace

### ISSUE THREAD

**Issue by fafnirbcrow** [a85/POSTMan-Chrome-Extension#7329]
**Describe the bug**
If an API has been removed from all workspaces by accident, there is no way to delete it.

**To Reproduce**
1. Go to the API's menu section
2. Create a new API
3. Go to API's options, and click Remove from workspace.

**Expected behavior**
There should be a place to see API's that belong to an account, and be able to delete them from that space

**App information (please complete the following information):**
 - App Type Native App
 - Postman Version 7.6.0
 - OS: Mac 10.14.4

**Comment by cyrielle-hada** [comment]
@fafnirbcrow the user who removes the API from the workspace should be able to delete it at this page: https://app.postman.co/me/apis 

<img width="1217" alt="Screen Shot 2019-09-17 at 16 30 14" src="https://user-images.githubusercontent.com/47351631/65050959-886a3a00-d968-11e9-9c84-0411bcdc2ecc.png">

**Comment by preethammavin** [comment]
@fafnirbcrow thanks for the feedback, will look at enabling this. In the meanwhile to unblock yourself can you share the API to a workspace and delete from there?

**Comment by fafnirbcrow** [comment]
Found the link you specified! Thank you!

I would suggest that the ux flow to find this is a bit unclear. 
The 'me' section is underneath your user profile (top right link) I was not expecting to find in my profile basically a sub set of my workspace. I would have expected to be able to access this from the workspaces menu, or something of the sort. 

Just some feedback, I really appreciate the help.

**Comment by cyrielle-hada** [comment]
@fafnirbcrow thanks for the feedback! We actually reported this UX flow here: https://github.com/postmanlabs/postman-app-support/issues/7265 - feel free to add a +1 to this issue!

**Comment by sankalp0o** [comment]
Thanks @fafnirbcrow for your suggestion! We'll improve upon this UX. For now, I'm closing this issue, but feel free to leave comments here or in the other issue if you have more feedback on this.
