### ISSUE TITLE
how do I download the archived collections?

### ISSUE THREAD

**Issue by nadiaadhami** [a85/POSTMan-Chrome-Extension#7330]
**Describe the bug**
I get a message saying a collection is archived because of too much usage.
I like to be able to revert to an older version where there is no sharing. or
download the archived collection.
**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. Please make sure the screenshot does not contain any sensitive information such as API keys or access tokens. 

**App information (please complete the following information):**
 - App Type [e.g. Chrome App, Native App]
 - Postman Version [e.g. 6.0.1]
 - OS: [e.g. macOS High Sierra 10.13.2]

**Additional context**

**Comment by chrisdeso** [comment]
@nadiaadhami – Would you try the link below?

* https://go.postman.co/usage/archive
* [How Archiving Works](https://learning.getpostman.com/docs/postman/launching_postman/collaboration/#how-archiving-works)

**Comment by SabriH10** [comment]
Hi @nadiaadhami,

If it's alright with you, I'll go ahead and close this issue following the suggestion provided. Hopefully, it helped. 

If you're still observing issues, feel free to re-open this issue. Otherwise, feel free to reach out if you have any questions or concerns.
