### ISSUE TITLE
Clicking at the "Body" tab makes request modified

### ISSUE THREAD

**Issue by emperorofkicker** [a85/POSTMan-Chrome-Extension#7331]
Postman has been updated to v7.7.2, then I noticed that bug:

1. Open existing request
2. Click at the body tab

Request becomes modified but really it is not.

**App information**
 - Postman native app v7.7.2

**Comment by emperorofkicker** [comment]
upd: it seems to be only for old requests (which had been exist before update to v7.7.2).

**Comment by saswatds** [comment]
Hi @emperorofkicker,
Prior to app version 7.7 the language selected for the raw body was not being stored in the app. The language was being ephemerally predicted from the `Content-Type` header.

In the newer version of app, we are now storing the language selection as well. In the upcoming app versions we will also enable to sync the language as well.

So in older request that do not have any language saved for the raw body, we infer the header from the `Content-Type` and update the language. For this particular reason you are seeing the tab as modified. 

You can safely save the request and continue working. We will be closing this issue now. Feel free to reach back to us.
Thanks.

**Comment by ghost** [comment]
Hi @saswatds,

What does this mean "In the upcoming app versions we will also enable to sync the language as well."? Does this imply that you will automatically sync older request in an upcoming app version? And can you please inform us, when this will be released?

Or are you suggesting that we manually update each single request in all collections that we have?

**Comment by saswatds** [comment]
@Wim-Kok you do not need to manually update any or all request. We have already handled all flows internally. You can expect a fix in the next minor version of the app.

**Comment by ghost** [comment]
Hi @saswatds,
Okay, thank you!
