### ISSUE TITLE
Not logged in

### ISSUE THREAD

**Issue by Aviasita** [a85/POSTMan-Chrome-Extension#7333]
Mailbox and password are correct, that is to say, the prompt password is incorrect, the password is retrieved and entered into the mailbox click submit without any response.

**Comment by ash007-postman** [comment]
@chore7 Can you please send an email to "help@getpostman.com" from your registered email id so that we can check on this further.

**Comment by ash007-postman** [comment]
@chore7 I hope that we were able to resolve the reported issue. I will be closing this thread. Feel free to revert for any further assistance.
