### ISSUE TITLE
VirusTotal Flags Postman as Infected

### ISSUE THREAD

**Issue by danieldogeanu** [a85/POSTMan-Chrome-Extension#7334]
Hey guys, so I've scanned your Windows installer with VirusTotal, as I do with all my apps before installing, and it says that your app is infected with _BScope.Adware.NSIS.ConvertAd_. Is this a false positive or should I worry?

Here's the [details of the scan](https://www.virustotal.com/gui/file/b1622317712f87ac87d6cfc3a1e5110c6832541a3c88282c1d72b86cd77a811f/details), if it's of any use.

I do mention that I also can't install the app on my system. I get the same problem specified [here](https://github.com/postmanlabs/postman-app-support/issues/7258).

PS: I've reported the issue here because it's not a vulnerability.

**Comment by Suhas-Gaikwad** [comment]
@danieldogeanu Thank you for reporting this issue. We have contacted the Antivirus vendor and  they confirmed that this finding is a false positive. Antivirus vendor is going to remove this false positive in the next update.

**Comment by iainbrydeninnovar** [comment]
Trapmine is showing postman portable as infected [Malicious.moderate.ml.score]. It's the only scanner of the 21.
