### ISSUE TITLE
Using beautify button in request body implies changing Content-Type header

### ISSUE THREAD

**Issue by leofrances-extflowbird** [a85/POSTMan-Chrome-Extension#7340]
**Describe the bug**
When I have Content-Type header equal to 'application/ld+json' or 'application/json-patch+json', my request header is well formated in JSON. But when I beautify (with the button) my request header, my Content-Type change to 'application/json'. And I would not like this behaviour.

**To Reproduce**
1. Create a request with JSON body
2. Set the Contant-Type header to 'application/ld+json'
3. Use beautify button in request body

**Expected behavior**
When the Content-Type contains 'json' and I use beautify, the Content-Type should not change automatically.

**App information:**
 - App Type: Native App
 - Postman Version: v7.7.2
 - OS: Windows 10

**Comment by codenirvana** [comment]
@leofrances-extflowbird Thanks for reporting this issue. We are tracking this with a similar issue here: https://github.com/postmanlabs/postman-app-support/issues/7346

The fix will be available soon!

**Comment by codenirvana** [comment]
@leofrances-extflowbird This issue is fixed in the latest Postman app `v7.7.3`.
Can you update your app and confirm if that fixes your issue?

**Comment by leofrances-extflowbird** [comment]
@codenirvana it works for me. Thanks a lot
