### ISSUE TITLE
Blank window, can't see anything

### ISSUE THREAD

**Issue by lvyahui8** [a85/POSTMan-Chrome-Extension#7342]
**Describe the bug**

Window blank, can't see anything, 

**To Reproduce**
1. Startup application
2.Can't see anything

**Expected behavior**

Function available

**Screenshots**

![image](https://user-images.githubusercontent.com/9465195/65133943-1a8c4400-da36-11e9-8b21-968b91c4a897.png)

**App information (please complete the following information):**
 - App Type:  Native App
 - Postman Version : Postman-osx-7.7.2
 - OS:  MacOS Mojave 10.14.5(18F132) 

**Additional context**

**Comment by preethammavin** [comment]
@lvyahui8 did you perform a new install or was it an update?

**Comment by kamalaknn** [comment]
Hey @lvyahui8 are you still seeing this issue? If yes, can you send the logs from `View -> Developer -> Show logs in Finder` to `help@getpostman.com` so we can take a closer look at this issue?

**Comment by nkjackzhang** [comment]
I have same problem on windows,when i use the old version,the problem disppears

**Comment by kamalaknn** [comment]
@nkjackzhang Could you share the logs with us?

**Comment by numaanashraf** [comment]
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
