### ISSUE TITLE
improve selected item contrast in the left tree

### ISSUE THREAD

**Issue by SegarJJ** [a85/POSTMan-Chrome-Extension#7343]
it is difficult to see the selected item in the left tree, it does not have enough visual difference to quickly identify.  what can help ?

**Comment by DannyDainton** [comment]
Hey @SegarJJ 

It's difficult to know which area you're explaining from this information and the platform has changed a lot recently. 

I'm going to close this now but if you're still having issues in the latest version we can look to reopen this again.
