### ISSUE TITLE
Clicked the body button the tab considered as edited all fields if the method used is POST, PATCH, PUT, or DELETE

### ISSUE THREAD

**Issue by darceal12** [a85/POSTMan-Chrome-Extension#7346]
**Describe the bug**
User clicked the body button the tab considered value was changed but user didn't changed the values. Applicable only for JSON and the methods are POST, PUT, PATCH, and DELETE.

**To Reproduce**
1. Open your postman
2. Click the collection wherein the method indicated is POST, PATCH, PUT, or DELETE
3. Click the body and looked the selected collection tab.

**Expected behavior**
Tab must not display the circle icon without edit JSON parameters and values.

**Actual response**
Postman tab was considered as user edited fields but user didn't edit.
**App information (please complete the following information):**
 - Native App
 - Postman Version 7.7.2
 - OS: Windows 10 Pro (10.0, Build 17134)
![postman - bug 1](https://user-images.githubusercontent.com/34103120/65139817-dd2cb400-da3f-11e9-9d57-6acdd700ef05.png)
![postman - bug](https://user-images.githubusercontent.com/34103120/65139828-df8f0e00-da3f-11e9-95e9-c3148c809927.png)

**Comment by ghost** [comment]
This is really annoying and time-wasting behavior. I hope the Postman team will fix this asap.

**Comment by codenirvana** [comment]
@darceal12 @Wim-Kok You can find more details about why it's happening here: https://github.com/postmanlabs/postman-app-support/issues/7331#issuecomment-532106183

We are working on fixing this behavior of updating older requests.

**Comment by SebaPrati** [comment]
Thanks for referencing.

**Comment by codenirvana** [comment]
@darceal12 @Wim-Kok @SebaPrati 
We've pushed a fix for this on `v7.7.3`. Can you update your app and confirm if that fixes your issue?

**Comment by ghost** [comment]
> 
> 
> @darceal12 @Wim-Kok @SebaPrati
> We've pushed a fix for this on `v7.7.3`. Can you update your app and confirm if that fixes your issue?

Hi @codenirvana 
It works fine for me now, thank you !

**Comment by darceal12** [comment]
Hello @codenirvana issue was resolved. Thanks for the help.
