### ISSUE TITLE
Unshared collection got archived

### ISSUE THREAD

**Issue by chrisdeso** [a85/POSTMan-Chrome-Extension#7347]
**Describe the bug**
Unshared collections in personal workspaces are reportedly being archived. 

**To Reproduce**
1. Join a free-tier team
2. Go over shared collection limit
3. See archived collection appear in personal workspace

**Expected behavior**
The expected behavior is for only shared collections to be archived once the collaboration limit is reached.

**Screenshots**
![image](https://user-images.githubusercontent.com/4734306/65187853-88367100-da32-11e9-92c0-21568d0ee92c.png)

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version: 7.7.2
 - OS: macOS

**Additional context**
[Filed by Postman]

**Note:** We were not able to reproduce the unexpected behavior of seeing unshared collections be archived. Logs that indicate an unshared collection was archived are attached internally.

**Comment by dmeilinger** [comment]
Thanks Chris !

**Comment by sankalp0o** [comment]
Hey @chrisdeso, @dmeilinger thanks for reporting!
When you hit the limit, only some of Shared collections get archived, irrespective of the workspace. Unshared collections are not supposed to be archived. We'll investigate and look into this.

**Comment by cyrielle-hada** [comment]
Closing the issue - while the collection appears to be in the personal workspace, it is actually shared with a team workspace. 
In terms of RBAC 
- Any collection originally created by a user, that is shared in a team workspace becomes a team owned collection (i.e shared collection).
- Although the shared collection coexists inside your personal workspace, it doesn’t longer belong to the personal workspace.
