### ISSUE TITLE
Monitor folders within a collection (similar to folder selection in Collection Runner)

### ISSUE THREAD

**Issue by xk0der** [a85/POSTMan-Chrome-Extension#7348]
**Is your feature request related to a problem? Please describe.**
Collection runner within Postman allows you to select only a single folder to run. In Monitor, you have to run the entire collection and cannot select only a folder to monitor.

**Describe the solution you'd like**
Provide the ability to select a folder when creating a Monitor, similar to how Collection runner does.

**Additional context**
Logged by Postman on behalf of a user.

**Comment by thoraj** [comment]
+1

We have integrated newman running tests from folders into our AzureDevops pipeline to make sure API are OK in the staging environment before deploying to production.

We would like to run those same folders as Monitors (in the production environment) to ensure we get notifications if the APIs for some reason become unresponsive.

Without this requested addition, we end up with a lot of copy-pasting requests between collections.

**Comment by ghost** [comment]
It would be nice, if I could choose not only request within the collection, but also folders. For instance, I would create folder "Tests" containing folders "Ping - every hour" and "Full integration - every day" to achieve goals:
1. ping all services or methods inside every hour
2. run integration tests with my logic every day to be sure that logic works as it should be.
And then I might create 2 monitors with different Period and Request (or Folders) parameters.

**Comment by gabibrant** [comment]
+1

We have the same need. Having the possibility to run per folder inside a collection on the Monitors would be much easier and avoid a lot of copy-pasting. At the moment, it's necessary to have many duplicated collections and it gets very disorganized.

**Comment by jpatel-api** [comment]
+1

This would be a great addition

**Comment by SofianeBenmila** [comment]
+1
Any news about this feature in the Monitoring?
I am forced to split my collection into many collections in order to do this right now.

**Comment by pisten** [comment]
Great feature, I hope it will be implemented 'soon' :)

**Comment by wyskens** [comment]
Any news on this?

**Comment by RoyalSix** [comment]
Just pinging this, as I would also like to see this get implemented

**Comment by dinuvld** [comment]
Hi, any update on this feature? Monitors for large apis can become rather cumbersome without this feature

**Comment by jiang-gao** [comment]
+1
This feature will help a lot while some requests are ready for lower environments but not higher environments because we can exclude them from the monitors for the higher environments.

**Comment by KuNman** [comment]
Can't wait for that!

**Comment by mborrus** [comment]
+1

This functionality would cut down on making redundant collections for testing

**Comment by rsmets** [comment]
This would be such a welcomed monitoring upgrade. Please prioritize @godfrzero @charlie-postman.

**Comment by malvikach** [comment]
Hi @rsmets  

Glad to update that you can set up scheduled collection runs on the cloud on individual **folders** using 'Scheduled Collection Runs'. 

The following video describes the steps:

https://user-images.githubusercontent.com/89449769/216952036-78b6dfa8-15d4-4f7d-b3c3-e287cc36f89e.mov



You can read more about this on our blog post [here](https://blog.postman.com/automate-your-api-testing-by-scheduling-your-collection-runs-on-postman/). Please let us know if this helps you!

**Comment by sonirico** [comment]
> Hi @rsmets
> 
> Glad to update that you can set up scheduled collection runs on the cloud on individual **folders** using 'Scheduled Collection Runs'.
> 
> The following video describes the steps:
> Screen.Recording.2023-02-06.at.4.13.46.PM.mov
> 
> You can read more about this on our blog post [here](https://blog.postman.com/automate-your-api-testing-by-scheduling-your-collection-runs-on-postman/). Please let us know if this helps you!

Hi, is there a way to link the results of scheduled runs with integrations like slack? Currently, monitors seem to be the only manner to send slack notifications.
