### ISSUE TITLE
Stability issues with sync sessions

### ISSUE THREAD

**Issue by wiggisser** [a85/POSTMan-Chrome-Extension#7352]
**Describe the bug**
Every now and then (much less than the appointed 30 days in the signin screen) I get a popup "Your session has expired ..." and I have to re-signin. Often at re-signin I get the message "something went wrong" eventhough I entered the correct password from my password vault. Today I chose to completely sign out and signin from scratch. 

First time I entered my username and password, I had to wait for quit a long time, before anything happend, and then I got a 401 error. (username and password are definitively correct)

Second time I entered my username and password, it got accepted immediately, but the sync did not work (sync icon was red) and all my collections and requests seemed to be gone. I also got the message about a session being terminated, because I was signed in on more than three devices. I have postman installed on only two machines ... 

I signed out again. On the next sign in, the sync took about 3 minutes until all my collections and requests showed up again. I have about 20 collections and all together about 160 requests.

**Expected behavior**

Correct password should be accepted every time. Sync should not take that long.

**App information (please complete the following information):**
 - App Type Native App
 - Postman Version 7.7.2
 - OS: Win 8.1
 
Network connection was fine on my side during this issues.

**Comment by preethammavin** [comment]
@wiggisser can you write to us help@getpostman.com so that we take a closer look. Session being terminated so early is definitely not what we expect.

**Comment by wiggisser** [comment]
@preethammavin As for your request I sent an email 

Please note, my prior concern is not the session being endend -- I don' really care if I have to enter my password once a day or once a month -- but the sync problems that happend afterwards.

Currently all works fine and I don't really know how I would provoke such a situation again. I tried signout and signin. Sync went through in a few seconds

**Comment by preethammavin** [comment]
@wiggisser verified it internally against the error that you saw, you seemed to have hit when the authentication service was under heavy load. It should not occur again, we are also bettering product experience around when there are service outages or under heavy load so that we do not block any user actions.

**Comment by wisteso** [comment]
For the past month, Postman has been logging itself out of the sessions way too quickly.  I typically have to re-log in several times a week now (which is a hassle when using Google + 2FA).

This is a webservice client, not a banking website.  It doesn't need to be that aggressive on security.

**Comment by preethammavin** [comment]
@wisteso can you write to us at help@getpostman.com so that we can take a closer look at why your sessions are expiring so quickly. At the time of signin if the remember me check box is checked we keep the session active for 30 days, would help us get to the bottom of it quickly if we check there are any weird behaviours around it.

**Comment by ArjunSingh-PM** [comment]
@wiggisser @wisteso Are you still experiencing this issue?

**Comment by wiggisser** [comment]
No. Did not occur since ...

**Comment by ArjunSingh-PM** [comment]
Thanks for the confirmation.
