### ISSUE TITLE
Label workspace/collection does not match HTTP method

### ISSUE THREAD

**Issue by scharf** [a85/POSTMan-Chrome-Extension#7353]
**Describe the bug**
Label in collection does not match the HTTP  Method

**To Reproduce**
1. Duplicate a `GET` re quest in a collection
2. Change the Method to `PUT`

**Expected behavior**
It schould show `PUT` as Method

**Screenshots**

![Postman-Wrong-Label](https://user-images.githubusercontent.com/3731059/65240619-fa19c380-dae1-11e9-956f-028c43db777d.jpg)

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version: 7.7.2 (7.7.2)
 - OS: macOS 10.14.6

**Comment by appurva21** [comment]
Hey @scharf, thanks for reaching out!
Is there a chance you didn't save the duplicated request after changing the HTTP method? 
If that was the case, please try saving the request after changing the HTTP method. This would update the label accordingly.

**Comment by scharf** [comment]
@appurva21 indeed, when I save, it updates correctly. 

However, it is confusing that the `Save` button does not change state when the request is not saved.

From a UX perspective, it would be good to show the `unsaved` state somewhere.

What's even more confusing is that you can have many requests in an unsaved state without noticing it and switch between unsaved requests.

**Comment by scharf** [comment]
Is there a **Save All** action?

**Comment by appurva21** [comment]
@scharf you can track whether a request is in `saved` or `unsaved` state by following the red dot present beside the request name in the tab.

![dirty](https://user-images.githubusercontent.com/24985700/65245201-c6eb2a80-db09-11e9-835d-6fcd0c459265.gif)

Once you make some changes to a saved request, the tab becomes dirty (the red dot appears) indicating the `unsaved` state of the request. After you save the changes, the red dot disappears, indicating the `saved` state.

Please feel free to revert with any further questions.

**Comment by scharf** [comment]
I think this issue can be closed. 

However, it would be nice to also show the unsaved state in the workspace/collection to reduce confusion...

It would also be nice to have a `Save All` button.

**Comment by appurva21** [comment]
@scharf Thanks for the feedback!

We are tracking this feature request at a related issue - #3466. You can follow the thread there to get more updates.

**Comment by tadasajon** [comment]
I also found this super-confusing.  I'm not even sure yet what the point of the save button is, lol.  If there was no save button because everything was automatically saved on every keystroke, wouldn't that be better?
