### ISSUE TITLE
Clicking on Add tests in monitoring test results redirects to page with 404 response

### ISSUE THREAD

**Issue by shivam-postman** [a85/POSTMan-Chrome-Extension#7354]
**Description:**

When viewing the test results for a monitor, selecting the failed tests tab shows a message with a link to `Add tests`, if no tests failed. The link redirects to a page returning 404. Similar behaviour is seen when no tests are present in the monitor's collection and we click `Add tests`.

**To Reproduce:**

1. Go to the monitor's page.
2. Select a run for which all the tests passed.
3. Go to the test results and select the failed tests tab (red square).
4. Click on `Add tests`.
5. The page opens with 404.

**Expected behaviour:**

A 'how to add tests' page should open up.

**Screenshots:**

![Screenshot 2019-09-19 at 13 32 46](https://user-images.githubusercontent.com/53427068/65241646-b1720280-db01-11e9-8a90-d7cec29c10f1.png)

<img width="1399" alt="Screenshot 2019-09-19 at 17 24 00" src="https://user-images.githubusercontent.com/53427068/65241864-4d037300-db02-11e9-877e-f2624d3c38d4.png">

**Comment by ch264** [comment]
I believe the doc ‘writing_tests’ in the folder ‘api_testing_and_collection_runner’ is in the v5 folder in GitHub Docs and therefore a vestigial doc and no longer being published directly on Learning Center. I could not find a direct copy of this doc replaced in v6, which is the published cleaned up folder of the LC. @kaustavdm @loopDelicious can you please help to clarify which doc has the right content to replace the URL?

**Comment by ArjunSingh-PM** [comment]
This issue is resolved. Closing the same.
