### ISSUE TITLE
Json Data returned is not formatted

### ISSUE THREAD

**Issue by elise-lcdb** [a85/POSTMan-Chrome-Extension#7355]
**Describe the bug**
I just updated Postman, and now when I receive JSON data it no longer does the indentations like before... 

I have it set to Pretty mode, and specified that the data is Json. However, it stills returns everything on one line instead of separating the data to an easy to read format.

Is anyone there a way to fix this?

**Expected behavior**
{
   data: {
     //information here
    }
}

**Actual behavoir**
{data:{//information here}}

**App information:**
 - App Type Native App
 - Postman Version 7.7.3
 - OS: Mac OS Mojave

**Comment by preethammavin** [comment]
@elise-lcdb I am able to see the pretty version of the response. Can you try posting a JSON body response to `https://postman-echo.com/post?` and let me know if the pretty mode works for it?

**Comment by elise-lcdb** [comment]
@preethammavin This is what I get
![Screenshot 2019-09-23 at 14 43 28](https://user-images.githubusercontent.com/31904512/65426548-b4763700-de10-11e9-9db9-24c7d38b94c0.png)

**Comment by kamalaknn** [comment]
Hey @elise-lcdb 

Thanks for reporting the issue. I'm not able to reproduce this issue from my side on Postman 7.7.3. Can you give us more information to help us identify the root cause?

1. Do you see any errors in the DevTolls (View -> Developer -> Show DevTools(Current View))? If yes, please attach the error screenshot.
2. Are you able to see a formatted response for other requests, for e.g. a simple GET request to `postman-echo.com/get`?
3. Can you share a simple collection with the requests that are not formatting correctly?

**Comment by elise-lcdb** [comment]
I just restarted Postman and I no longer get the issue. Sorry about that. I don't know why it was doing that earlier, but I am now able to get the data properly formatted in Pretty.

Thank you for your help though

**Comment by kamalaknn** [comment]
@elise-lcdb Thanks for clarifying this. It is possible that one of the language parsers for the response view was not loaded the time you faced the issue. A restart could have fixed it.

If you face this issue again, please let us know.

**Comment by xtr33me** [comment]
I am seeing this same issue. I have tried restarting and still getting it. Everything seems to work fine outside of my response not being "prettified".  I am going through the Postman Desktop agent if that makes any difference and I have the following showing in dev tools under chrome when I hit send on the above post you shared.

This is my response:
![image](https://user-images.githubusercontent.com/1653419/97498964-73b9ed00-1943-11eb-9984-638db24a6662.png)

And this is dev tools.
![image](https://user-images.githubusercontent.com/1653419/97498787-2b9aca80-1943-11eb-9481-548724773785.png)

**Comment by NathanFrank285** [comment]
Hey, I am having this exact same issue

**Comment by scott-lehrbaum** [comment]
FWIW, I was having exactly the same problem using the Chrome desktop agent. However when I installed the Windows native Postman app, it worked fine with the "pretty" formatting.

Postman team: This appears to still be an issue in the Chrome desktop agent.

**Comment by xtr33me** [comment]
Thanks @scott-lehrbaum for the info.  I just downloaded the actual Windows Postman app and you are correct. It works as expected.  Again thank you so much!

**Comment by NathanFrank285** [comment]
Thanks Scott, Downloaded the mac app and it works great

**Comment by patrickweaver** [comment]
If you're here and haven't double checked that you have JSON set as the response format instead of HTML (maybe you are on a new computer), that was my issue.

**Comment by greygatch** [comment]
Restarting the Mac application worked for me.

**Comment by digandhi-clgx** [comment]
Happens on the latest  v8.2.3 as well. Restarting the Mac app fixes it.

**Comment by Vedan** [comment]
Version 10.23.1 . Has not formatted json in answer requests . Stay same as RAW. Please fixe..
![postman_format](https://github.com/postmanlabs/postman-app-support/assets/2162478/42ab0e81-db9d-48c3-b992-88c374c10797)

**Comment by samarthgulati** [comment]
Hello @Vedan, I tried replicating with the data in the screenshot using postman echo command, but was unable to reproduce. 

We released a fix for this issue in 10.23.1, just to make sure you have the latest code in the tab running this request, can you please try again after restarting the application to clear any cache. Let me know if it still doesn't work.
