### ISSUE TITLE
Accessing a documentation results in an error showing HTTP 403 code

### ISSUE THREAD

**Issue by xk0der** [a85/POSTMan-Chrome-Extension#7361]
**Describe the bug**
Accessing a documentation link shows an error in the UI stating 
   
    403
    Oops, something went wrong. Please contact us at help@getpostman.com."

*Checking the JS Consoles show the following errors:*
![image](https://user-images.githubusercontent.com/21366/65285506-c8ac0100-db90-11e9-92c4-f6ebbbef6d4d.png)

![image](https://user-images.githubusercontent.com/21366/65285559-f133fb00-db90-11e9-8e26-dc32ee010379.png)

That seems to indicate that the environment is not accessible. But when I clicked the "Run in Postman" button all the collections plus the environment were imported!

**To Reproduce**
I was unable to replicate this.
I also tried to publish the imported collections + environment, and it worked fine.
Accessing the user's doc URL always throws an error.
Details provided internally.

**Expected behaviour**
Since the environment got imported when clicking on "Run in Postman" button it should be accessible when viewing the documentation.

Documentation should thus load fine without throwing the HTTP 403 error.

**Screenshots**
![image](https://user-images.githubusercontent.com/21366/65287785-7bcc2880-db98-11e9-82bb-6aed4001586a.png)

**App information (please complete the following information):**
I tested on the following:
 - App Type Native App
 - Postman Version 7.6
 - OS: macOS High Sierra 

**Additional context**
Logged by Postman on behalf of a user.

**Comment by Cazaimi** [comment]
Investigating.
