### ISSUE TITLE
need a long login feature

### ISSUE THREAD

**Issue by wzdbsss** [a85/POSTMan-Chrome-Extension#7362]
did you guys to be force login postman twice  a day? every time appears session expire.

In my opinion, a freq use of post man let me always keep it open, so can you add a long login feature to postman client?

**Comment by preethammavin** [comment]
@wzdbsss we do re-authenticate every 30 days if the check box for remember is checked-in, if its still holding context can you please write to us at help@getpostman.com from the email id that you use in Postman so that we can take a closer look.

**Comment by ArjunSingh-PM** [comment]
@wzdbsss Did checking the "Keep me signed in" checkbox while signing in solve the issue for you?

**Comment by wzdbsss** [comment]
> @wzdbsss Did checking the "Keep me signed in" checkbox while signing in solve the issue for you?

yeah, it works after updating my postman version. everything goes well right now, thanks very much.
