### ISSUE TITLE
Postman can't encode '%' in request param to '%25' when Chrome can

### ISSUE THREAD

**Issue by JaedongLee** [a85/POSTMan-Chrome-Extension#7365]
Wnen use Chrome, the situation is like this:

Before encode:
![postman_bug1](https://user-images.githubusercontent.com/25265598/65309930-b4332d00-dbbf-11e9-8e37-c6371532cf3a.png)

After encode:
![postman_bug2](https://user-images.githubusercontent.com/25265598/65310122-24da4980-dbc0-11e9-9ecf-d833f2c11f66.png)

When use Postman, the situation is like this:

Before encode: 
![postman_bug3](https://user-images.githubusercontent.com/25265598/65310325-aa5df980-dbc0-11e9-8b01-40f8c59b86ab.png)

After encode:
![postman_bug4](https://user-images.githubusercontent.com/25265598/65310346-b3e76180-dbc0-11e9-9d24-8a7e726c1992.png)

It shows that postman don't encode '%' when chrome encode

I want to know the reason chrome choose to encode '%' but postman don't choose

**Comment by codenirvana** [comment]
@JaedongLee Thanks for reporting this issue, we are currently tracking all the encoding related issues here: https://github.com/postmanlabs/postman-app-support/issues/4555

As a workaround, you can select text in any input field and secondary click (right-click) menu will allow you to encode-decode the selected text.
<img width="487" alt="Screenshot 2019-09-24 at 9 27 43 AM" src="https://user-images.githubusercontent.com/4865836/65480115-e689a680-dead-11e9-9dc2-64de8e791429.png">
