### ISSUE TITLE
support more protocols such as websocket or mqtt?

### ISSUE THREAD

**Issue by Txiaozhe** [a85/POSTMan-Chrome-Extension#7366]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

Is there any plan to support more protocols in postman such as websocket or mqtt or anymore?

**Comment by codenirvana** [comment]
Duplicate of #4009

**Comment by shamasis** [comment]
Postman v8.5 onwards have added support to connect to WebSocket APIs and send/receive messages https://github.com/postmanlabs/postman-app-support/issues/4009#issuecomment-845136513

**Comment by philCryoport** [comment]
The request for MQTT support is apparently covered by https://github.com/postmanlabs/postman-app-support/issues/9490

Please vote for it!

**Comment by Txiaozhe** [comment]
Thanks:)
