### ISSUE TITLE
Excluded from own team

### ISSUE THREAD

**Issue by vdusauto** [a85/POSTMan-Chrome-Extension#7367]
**Describe the bug**
It appears I have been removed from my own team, loosing collections within

**To Reproduce**
I just joined another team (both Postman free)

**Expected behavior**
Being able to join several teams

**App information (please complete the following information):**
Native APP
Latest

Team name: https://vdusautois-apizr.postman.co/team

**Comment by abhijitkane** [comment]
@vdusauto Postman doesn't support a user joining multiple teams yet. When you share collections with a team, you lose "ownership" of said collections. You can send an email to help@getpostman.com for further assistance on your collections / team membership.

**Comment by abhijitkane** [comment]
@vdusauto Postman doesn't support a user joining multiple teams yet. When you share collections with a team, you lose "ownership" of said collections. You can send an email to help@getpostman.com for further assistance on your collections / team membership.
