### ISSUE TITLE
Allow empty URL parameter

### ISSUE THREAD

**Issue by egyptianbman** [a85/POSTMan-Chrome-Extension#737]
Currently, if I try to add a query parameter with no value, it gets auto removed.  The app should allow an empty parameter to be passed, ie:

```
http://my-api.com/?param1=&param2=true
```

gets converted to:

```
http://my-api.com/?param2=true
```

**Comment by ghost** [comment]
Hello guys, 

This issue is not fixed 100%. Now if you leave a query param with no value, POSTMAN will not remove it but will remove the = sign from it. So would like something like: 

http://my-api.com/?param1&param2=true

**Comment by NicIonCam** [comment]
is there a fix for 

> ghost

 problem ?. I have the same issue. Multiple possible params are added to link and brokes down the request
