### ISSUE TITLE
CPU usage way too high

### ISSUE THREAD

**Issue by mtchdev** [a85/POSTMan-Chrome-Extension#7370]
**Describe the bug**
CPU usage is through the roof when idle. Was doing nothing and left it in the background for a couple hours, it spawned 3 more individual processes and did this. Note I only opened the app once.

**To Reproduce**
1. Open Postman
2. Wait

**Expected behavior**
All processes should not collectively be taking up to 90% peak usage in the background.

**Screenshots**
![image](https://user-images.githubusercontent.com/9291464/65386646-15e6c900-dd71-11e9-9613-297efc6d182a.png)

**App information (please complete the following information):**
 - App Type: Electron
 - Postman Version 7.7.3
 - OS: Windows 10 1903

**Comment by kamalaknn** [comment]
Hey @spliitzx 

Thanks for reporting this issue. This looks like a duplicate of #7294 

I'm closing this. Please follow the original issue for updates.

**Comment by salihkaragoz** [comment]
CPU usage too high,  +1 ,ubuntu 18.04

**Comment by Reechee88** [comment]
CPU usage too high, +1 ,ubuntu 19.10.

Any workaround? It is lagging so much, our team cannot use it anymore since last update to v7. Please give us a workaround.

**Comment by numaanashraf** [comment]
@Reechee88 If you have all your data synced to your account, could you try signing out and in again?

**Comment by Reechee88** [comment]
> @Reechee88 If you have all your data synced to your account, could you try signing out and in again?

![Képernyőkép erről: 2020-05-06 08-44-14](https://user-images.githubusercontent.com/2429402/81145079-d2467580-8f75-11ea-8919-e6dd43cb79a8.png)

It is signing out, it's been 5 minutes so far.

**Comment by Reechee88** [comment]
Now it is okay! Thanks for quick response!

**Comment by OlegGlushko** [comment]
Happens half the time, whole computer lags, only for me to find out "POSTMAN" decides to eat 100% of the CPU doing what exactly? Very annoying

**Comment by numaanashraf** [comment]
@OlegGlushko If you have all your data synced to your account, could you try signing out and in again and let us know if the CPU usage has come down?

We are currently working on a set of performance improvements that should improve Postman's resource usages across the board.

**Comment by jimmy0699** [comment]
on recent macos as well

![Zrzut ekranu 2020-06-3 o 14 22 24](https://user-images.githubusercontent.com/3270903/83636134-bac6d080-a5a5-11ea-8b21-f018ba0c4320.png)

**Comment by arlemi** [comment]
@jimmy0699 Please post in #7294 . 🙂

**Comment by salihkaragoz** [comment]
It's okay if you're doing any mining in the background, just let us know.  : D

**Comment by topil** [comment]
logout/login works for me.

**Comment by AntonGrekov** [comment]
> > @Reechee88 If you have all your data synced to your account, could you try signing out and in again?
> 
> ![Képernyőkép erről: 2020-05-06 08-44-14](https://user-images.githubusercontent.com/2429402/81145079-d2467580-8f75-11ea-8919-e6dd43cb79a8.png)
> 
> It is signing out, it's been 5 minutes so far.

that worked in my case. after openning postman it was using 20-30% of cpu and lagged hard, while that it was syncing data non-stop. After i signed out/signed in back sync process stopped and cpu usage dropped to 0-0.5%

**Comment by vinischeidegger** [comment]
Signing out/signing in did not work for me... Postman still has 60% of my CPU

**Comment by Diluka** [comment]
CPU usage too high, +1 ,macos 12.4
<img width="1202" alt="image" src="https://user-images.githubusercontent.com/3766084/176346463-f2fda302-1399-40a2-8a49-b1efea346718.png">

**Comment by ppowierza** [comment]
70% CPU usage on 10.0.42 version

**Comment by kamalaknn** [comment]
@ppowierza Could you record a performance profile when you are experiencing high CPU usage?

**Comment by ppowierza** [comment]
> @ppowierza Could you record a performance profile when you are experiencing high CPU usage?

Thanks for your interest. I managed to fix it by **turning OFF hardware acceleration**. It is right now using 0% CPU when idle. Before it used 80-90% on idle. 
I wanted to send you performance profile, but it was pretty empty.

**Comment by kamalaknn** [comment]
Ah, thanks @ppowierza for the update. 

Can you share your system information? What is the GPU on your system?

**Comment by madshox** [comment]
![image](https://user-images.githubusercontent.com/63535913/200531310-a4614e26-b1a3-43f1-b4b0-5a917c271462.png)
I noticed that the mac is warm because of the postman, even though it is standing idle. 
macbook pro m1 pro

**Comment by Azbola** [comment]
> > @ppowierza Could you record a performance profile when you are experiencing high CPU usage?
> 
> Thanks for your interest. I managed to fix it by **turning OFF hardware acceleration**. It is right now using 0% CPU when idle. Before it used 80-90% on idle. I wanted to send you performance profile, but it was pretty empty.

@kamalaknn  I had the exact same problem.  As soon as I made the first request in postman my CPU would be over 50% constantly.  Disabling hardware acceleration fixed the problem straight away.

This is on a Lenovo Thinkpad Gen1 with Intel UHD graphics

**Comment by weimengxi** [comment]
> 

2023-02-28
I've met the same problem

**Comment by callumpoole** [comment]
Same issue :(

**Comment by GergelyLakatos** [comment]
Same Here..

**Comment by cch99** [comment]
I have the same issue on a Macbook pro I7.  It sounds like a jet taking off from the fans spinning with postman sitting idle.

**Comment by michaeldyl520** [comment]
Maybe it is downloading an upgrade, try shielding the upgrade link in ```/etc/hosts```
```
0.0.0.0 dl.pstmn.io
```

**Comment by marcus-behrendt** [comment]
Same issue. Running postman on Linux. 

Disabling hardware acceleration had no effect.
Modifying `/etc/hosts` as described above had also no effect.

![grafik](https://user-images.githubusercontent.com/108674180/235681169-674577b4-11fa-497e-ada3-a4e0736e183d.png)

**Comment by mog28** [comment]
same i

> I have the same issue on a Macbook pro I7. It sounds like a jet taking off from the fans spinning with postman sitting idle.

exact same phenomenon on my windows laptop

**Comment by in-fke** [comment]
Same here  20 % - is their a download for postman.exe with debug symbols? One could try to do JIT debugging in such cases.

**Comment by arnoudsietsema** [comment]
I've got the same problem. CPU was idle(ish) and starts using 30% when Postman is showing the overview-tab and not doing anything else.

![image](https://github.com/postmanlabs/postman-app-support/assets/3726020/1e508e0b-54f3-4736-bac8-7f3f43200f26)

**Comment by kamalaknn** [comment]
@arnoudsietsema @in-fke Hey, this could be related to an issue with acquiring locks on storage files managed by Postman, discovered on this [thread](https://github.com/postmanlabs/postman-app-support/issues/7294#issuecomment-1669001260). Could you try confirm if you have a lock file in `C:\Users\<name>\AppData\Roaming\Postman\storage\<filename>.lock`?

We are working on a fix for this from our side. In the meantime as a workaround, you can close the app(confirm all the processes have quit) and delete the lock file within Postman storage folder.

**Comment by arnoudsietsema** [comment]
Hi @kamalaknn,

This folder does indeed contain lock files, while postman is not running (nor any postman background process).
![image](https://github.com/postmanlabs/postman-app-support/assets/3726020/b011fa11-1231-46d5-b536-288f90b41a99)

The workaround did do it's job! 
After starting Postman the file "userPartitionData.json.lock.STALE" was created again, but "requester.json.lock" wasn't.
CPU usage is back to normal levels.

Thanks!

**Comment by kamalaknn** [comment]
@arnoudsietsema Thanks for confirming. 

We have a fix for this that'll be released in the next version of Postman in case it happens again for you or others encountering the same issue.

**Comment by Akronae** [comment]
Same issue idling Postman (v10.17.4) is using 15-20% of my i9-13900HX CPU which is a lot

![image](https://github.com/postmanlabs/postman-app-support/assets/17302866/ccd742ee-e919-4073-973c-bc93d3cad219)

**EDIT:** Deleting `C:\Users\<name>\AppData\Roaming\Postman\storage\settings.json.lock` worked, thanks!

**Comment by alphamarket** [comment]
> **EDIT:** Deleting `C:\Users\<name>\AppData\Roaming\Postman\storage\settings.json.lock` worked, thanks!

I am suffering the same issue in my system;150% of 12 CPU cores (Gen. 11) are occupied by just running the postman (v10.17.6) without doing anything and removing the `~/snap/postman/current/.config/Postman/storage/requester.json` quite the CPU usage for now!

Postman needs a hotfix and update on this issue.

**Comment by kamalaknn** [comment]
Hey @alphamarket, we will be rolling out a fix for this in the coming week.

**Comment by kamalaknn** [comment]
Hey folks, the fix is now out in 10.18. Do update and let us know if you are still facing any issues

**Comment by alphamarket** [comment]
@kamalaknn I have installed postman from `snap` in my ubuntu 22.04; There is no update in my snap for postman now; I am still in `v10.17`

**Comment by kamalaknn** [comment]
Hey @alphamarket, we have enabled 10.18 on `snap` as well now.

**Comment by LucaNerlich** [comment]
> > @ppowierza Could you record a performance profile when you are experiencing high CPU usage?
> 
> Thanks for your interest. I managed to fix it by **turning OFF hardware acceleration**. It is right now using 0% CPU when idle. Before it used 80-90% on idle. I wanted to send you performance profile, but it was pretty empty.

For anyone stumbling over this, as of today (october 2023) postman was still consuming around 5% cpu in idle - disabling hardware acceleration (title bar -> help -> disable xx) fixed this problem.

**Comment by vibonacci** [comment]
@LucaNerlich Thank you. Disabling hardware acceleration did reduce the idle CPU usage by A LOT.
@postman-staff, please look into the hardware acceleration issue. Also, hardware acceleration feature should be a toggle in the settings, and not hidden unexpected sneakily under the help menu.

**Comment by ManalLiaquat** [comment]
I tried 2 work-arounds:
1. I don't have `requestor.json.lock` file, so I created one with `{}` content in it.
2. Disabled `Hardware Accelaration` (from title bar -> help -> disable).
3. Restart Windows

**Comment by marius-oloeru** [comment]
In my case disabling hardware acceleration fixed the problem.
