### ISSUE TITLE
Keyboard Shortcut to Delete Cookies

### ISSUE THREAD

**Issue by MarcusKJ323** [a85/POSTMan-Chrome-Extension#7372]
This feature request is not related to any specific problem. 

To speed up workflow, having a shortcut to delete cookies relating to the last call or all cookies would be extremely helpful.  

Cheers

**Comment by codenirvana** [comment]
@MarcusKJ323 You can delete cookies programmatically using scripts.
Refer: https://github.com/postmanlabs/postman-app-support/issues/3312#issuecomment-516965288
