### ISSUE TITLE
Visualize (Beta) > table view>  Unable to see text when dark theme is enabled

### ISSUE THREAD

**Issue by still-breathing** [a85/POSTMan-Chrome-Extension#7375]
**Describe the bug**
Unable to see text in Visualize 

**To Reproduce**
1. Go to 'preferences'
2. Change the Theme to Dark mode
3. Now set your template for Visualize API responses
4. See the text in the table
5. Change the Theme to Light mode and see the text in the table.

**Expected behavior**
Data Text should be readable when Dark Theme is enabled.

**Screenshots**
See: 
<img width="1127" alt="postamanDark" src="https://user-images.githubusercontent.com/8476404/65488792-aa653e80-decb-11e9-85dd-603cd2d7608c.png">
<img width="1111" alt="postmanLight" src="https://user-images.githubusercontent.com/8476404/65488793-aa653e80-decb-11e9-9ab1-3f72111f5ae2.png">

**App information (please complete the following information):**
 - App Type Native App (for Mac)
 - Postman Version [7.7.3]
 - OS: macOS Mojave [10.14.6]

**Comment by codenirvana** [comment]
@still-breathing Thanks for reporting this issue. As a workaround, you can add custom CSS style to fix this.

Example:
```js
pm.visualizer.set(`
<style>
html { background: #fff; }
</style>

// your visualizer template
`);
```

**Comment by still-breathing** [comment]
Thanks will try it out. 
Cheers.

**Comment by DannyDainton** [comment]
Hey @still-breathing, 

This has been fixed in the latest versions of the platform.

**Comment by still-breathing** [comment]
Great
