### ISSUE TITLE
Workspace name shown as `Loading..` in top bar

### ISSUE THREAD

**Issue by ankit-m** [a85/POSTMan-Chrome-Extension#7376]
**Describe the bug**
When switching to a workspace the workspace name shows up as `Loading..`. 

**To Reproduce**
1. Create a team workspace X
2. Create a new request A and edit the URL
3. Do NOT save the request
4. Switch to any other workspace Y
5. Leave workspace X from the workspace switcher
6. Switch to workspace X

Observe `Loading..`

**Expected behavior**
1. Show workspace name
2. Before leaving a workspace, check if there are unsaved changes and show a warning

**Screenshots**
<img width="397" alt="image" src="https://user-images.githubusercontent.com/9019878/65497199-7263f880-ded7-11e9-93ad-cfeada81fb81.png">

**App information (please complete the following information):**
 - App Type: Native
 - Postman Version: 7.7.3
 - OS: macOS Mojave

**Comment by sankalp0o** [comment]
This has been fixed in the latest release of Postman app v7.10. Closing the issue but feel free to report back if this doesn't work!
