### ISSUE TITLE
Copy/Paste does not work, at all.

### ISSUE THREAD

**Issue by johncmolyneux** [a85/POSTMan-Chrome-Extension#7379]
**Describe the bug**
Copy and paste is unavailable.

**To Reproduce**
Enter a Url.
Highlight the Url.
Use your favourite method to copy text (Ctrl + C, right-click and select Copy - anything else).
Open Notepad
Try and paste the Url.

**Expected behavior**
The text that was copied from Postman should be pasted into Notepad.

**Additional context**
Literally a show-stopper that makes Postman 0% useful for the whole team.

**Comment by numaanashraf** [comment]
@johncmolyneux Thanks for writing in. I've been trying to reproduce this issue on our Windows App (v7.7.3) and it appears to work here (both Ctrl-C method and right-click-copy method). Could you help us understand your setup better? Please share your Postman version and OS version.

Screen recording of the steps we tried:
https://www.loom.com/share/c8fe63eb41a448dc8482d5d1b519731b

**Comment by numaanashraf** [comment]
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
