### ISSUE TITLE
Unable to import sandbox module

### ISSUE THREAD

**Issue by JamieKeeling** [a85/POSTMan-Chrome-Extension#7380]
**Describe the bug**
Following the documentation provided in the [Postman Sandbox API](https://learning.getpostman.com/docs/postman/scripts/postman_sandbox_api_reference/) I have tried to import the **_url_** module, however when accessing the functionality I receive the following message logged to the Postman Console:

> ReferenceError | URL is not defined

**To Reproduce**
1. Create a new request
2. Add the following to your 'pre-request scripts' section

```
const url = require('url').URL;
const myURL = new URL('https://user:pass@sub.example.com:8080/p/a/t/h?query=string#hash');
console.log(myURL.host);
```

3. Open the Postman Console
4. Execute the test
5. See the error within the Postman Console

**Expected behavior**
The reference to URL is successful and is logged to the console.

**Screenshots**

Example script:

![image](https://user-images.githubusercontent.com/7165035/65527607-d5ab5600-deea-11e9-8148-d71a1579f992.png)

Console output:

![image](https://user-images.githubusercontent.com/7165035/65527645-e52a9f00-deea-11e9-80f3-81a62ff4eede.png)

**App information:**
 - Native App
 - Postman Version v7.7.3
 - OS: Windows 10 Enterprise

**Additional context**

I'm doing this to alter an existing query string parameter that is retrieved from a previous query.

It would be nice to see this added as a top level feature in a similar manner to headers such as the issue raised in https://github.com/postmanlabs/postman-app-support/issues/4631

**Comment by codenirvana** [comment]
@JamieKeeling Modules available in Postman scripts might have slightly different API from the one documented in Node.js.

`.URL` is the new Node.js API, you can use `require('url').Url` to fix this issue.
