### ISSUE TITLE
Add variable feature in domain part

### ISSUE THREAD

**Issue by onacit** [a85/POSTMan-Chrome-Extension#7384]
**Is your feature request related to a problem? Please describe.**
I need to change some part of domain, not in sub path.
Note that this seems not related collection variables.
Say my api-gateway coordinated some sub-domain with API-KEYs.
```
https://{{apiKey}}.some-api.some-domain/v1/some
```

**Describe the solution you'd like**
I would like to love when I can do this
```
https://:apiKey.some-api.some-domain/v1/som
```

**Describe alternatives you've considered**

**Additional context**

**Comment by codenirvana** [comment]
@onacit Path variables (prefixed with `:`) can't be used in the hostname.
You can still use regular variables (like `{{apiKey}}`) and set up as an environment or global variable.
