### ISSUE TITLE
Array type not supported error when sending POST request to Elasticsearch using sql query 

### ISSUE THREAD

**Issue by freesinger** [a85/POSTMan-Chrome-Extension#7385]
**Describe the bug**
I store my JSON file in Elasticsearch which index name is `tmdb`, when I tried to send POST request using sql query to get information from `tmdb`, it came across a `sql_illegal_argument_exception` error, which is not occurred in my Elasticsearch native search.
I assume whether postman has no support for array in JSON file or any other reason?

**Expected behavior**
POST response should return sql query result.

**Screenshots**
Request details and response information are shown below.
`POST`:`http://localhost:9200/_sql?`
`Body`:
```json
{
    "query": "SELECT * FROM tmdb",
    "fetch_size": 5
 }
```
`Response body`:
```json
 {
    "error": {
        "root_cause": [
            {
                "type": "sql_illegal_argument_exception",
                "reason": "Arrays (returned by [cast.cast_id]) are not supported"
            }
        ],
        "type": "sql_illegal_argument_exception",
        "reason": "Arrays (returned by [cast.cast_id]) are not supported"
    },
    "status": 500
}
```

**App information:**
 - App Type [Native App]
 - Postman Version [7.7.3]
 - OS: [macOS High Sierra 10.14.5]

**Additional Notes**
1. `tmdb` file can be found [here](https://github.com/o19s/relevant-search-book/blob/master/ipython/tmdb.json)
2. Elasticsearch version: `7.3.0`
3. `cast` is an array store multiple dictionaries

**Comment by codenirvana** [comment]
@freesinger Thanks for reporting this issue but looks like it's happening because of some internal server error and not related to how request is sent using Postman.

I am not exactly sure about your use case but this problem looks similar to https://github.com/elastic/elasticsearch/issues/34359

**Comment by freesinger** [comment]
@codenirvana Thanks for your help.
This issue reffered here [elasticsearch/issues/33204](https://github.com/elastic/elasticsearch/issues/33204#issuecomment-416642992) detailed explained why array type is not supported in ESsql search, hope it will help :)
