### ISSUE TITLE
Create Unresolved variable shorcut

### ISSUE THREAD

**Issue by a1dutch** [a85/POSTMan-Chrome-Extension#7386]
Hi,

It would be super handy if there was an option to create unresolved variables.

Maybe an option to right click on the unresolved variable, there could be two options

* Create: {current collection}
* Create: Global

Andy

**Comment by saswatds** [comment]
Hey @a1dutch 
This look's like a duplicate of https://github.com/postmanlabs/postman-app-support/issues/285 
I am closing this issue in favour of the master issue. Feel free to give you 👍 on the master issue

**Comment by a1dutch** [comment]
Hi @saswatds, 

This is a little different #285 is more about prompting for variables, this is more about setting the variables when they havent been set in the environent.

Quite often im writing new requests and i put the placeholders in for the variables i know i am going to need.

This just gives you an easy way to set them permernently rather than prompting for them everytime.
