### ISSUE TITLE
"Open in Postman" Button

### ISSUE THREAD

**Issue by just1689** [a85/POSTMan-Chrome-Extension#7387]
It would be great to have a button that I could put in my API documentation that would allow the user to pull my apis as a collection into their Postman.

Kind of like this:

<img src="https://img.shields.io/badge/Open%20with-Postman-eeee22">

**Comment by Raja-Simha** [comment]
Hi @just1689, we already have a Run in Postman button which does the same. You can read about it here - https://learning.getpostman.com/docs/postman_for_publishers/run_button/creating_run_button/

Let me know if there is something else with 'Run in Postman' that you want. Closing this for now.
