### ISSUE TITLE
Extra characters in documenter URL cause page to not work properly

### ISSUE THREAD

**Issue by xk0der** [a85/POSTMan-Chrome-Extension#7389]
**Describe the bug**
If for whatever reasons, you visit the documenter page with a link to a request within the document, which has some extra characters at the end, it causes failure in the Javascript.

This results in many of the JS handlers not being able to attach to buttons etc, and thus those functionalities do not work.
Example: Copy to clipboard, click to expand do not function.

_Example link_
Notice the three dots at the end
https://documenter.getpostman.com/view/8202676/SVmr1ML8?version=latest#094a69cf-2247-46e3-9b28-ea8385a8c0a3...

**Workarounds are available**
* This is not a high-impact issue, as visiting the correct URL will work.
* Also, clicking on any items within the page which fixes the URL and then re-loading it will work too.
* But it sure is an annoyance if you aren't sure what is going wrong! 

**To Reproduce**
Steps to reproduce the behaviour:
1. Visit a doc URL to a request with extra chars at the end: https://documenter.getpostman.com/view/8202676/SVmr1ML8?version=latest#094a69cf-2247-46e3-9b28-ea8385a8c0a3...
2. Click on "Copy to clipboard" on the right-hand side, code panel.
3. The button won't turn to "copied" and the code won't copy
4. You should see a "Syntax Error" in JS Console

**Expected behaviour**
Failure to parse the request's UUID anchor should not result in the entire script stopping. Ideally, rest of the JS should continue as-is, attaching handlers to UI elements.

**Screenshots**
Error seen in JS Console
![image](https://user-images.githubusercontent.com/21366/65643662-664a7900-e046-11e9-8013-c7a6a48d6f0a.png)

**Additional context**
Logged by Postman on behalf of a user.

**Comment by ishan-ks** [comment]
This issue seems to be resolved now. We don't see the page getting stuck or unresponsive behavior in the page. See attached screen recording for reference.

https://user-images.githubusercontent.com/98811858/199911632-cdfd9bcd-254d-48e3-ae11-1226355e0d5f.mov
