### ISSUE TITLE
Wrong curl import

### ISSUE THREAD

**Issue by m3dbedb** [a85/POSTMan-Chrome-Extension#7390]
**Describe the bug**
Postman parses culr body imported as raw text to URL

**To Reproduce**
1. Press import button
2. Click on Raw text tab
3. paste text 
curl -i http://192.168.0.1:8084/api/v1/crontab -d '{
    "name": "test10",
    "description": "тестовое расписание",
    "start": "2 * * * *",
    "enable": true,
    "command":"startTariff",
    "param":"[123]"
}'
4. See error. URL is lost, body goes to request URL

**Expected behavior**
In previous version 7.x.x Postman imported curl commands correctly, URL `-i http://192.168.0.1:8084/api/v1/crontab` appears in Request URL, `-d '{
    "name": "test10",
    "description": "тестовое расписание",
    "start": "2 * * * *",
    "enable": true,
    "command":"startTariff",
    "param":"[123]"
}'` was moved to Request body.

**Screenshots**
applied
![curl](https://user-images.githubusercontent.com/25632818/65682088-e8e13180-e062-11e9-88f2-ddd72227e647.jpg)

**App information**
 - Native App
 - Postman 7.8.0
 - OS: win7 32 bit

**Comment by abhijitkane** [comment]
Thanks @m3dbedb - we'll aim to get a fix out soon.

**Comment by m3dbedb** [comment]
the issue in present in postman 7.11

**Comment by m3dbedb** [comment]
In postman 7.18.1 for windows 7 32 bit curl body imports to x-www-form-urlencoded key, and recipient does not understand it

    curl -i http://localhost:8084/api/v1/a -d '{
    "name":"test1",
    "description":"тест 1"
    }'

result

    curl -L -X POST 'http://localhost:8084/api/v1/a' -H 'Content-Type: application/x- www-form-urlencoded' --data-urlencode '{
    "name":"test1",
    "description":"тест 1"
    }='

I suppose curl body should be imported as raw text:

    curl -L -X POST 'http://localhost:8084/api/v1/a' --data-raw '{
    "name":"test1",
    "description":"тест 1"
    }'

**Comment by abhijitkane** [comment]
@m3dbedb The default interpretation of `-d` is the urlencoded mode.
Sending this:
```
curl -i http://postman-echo.com/post -d '{
"name":"test1",
"description":"тест 1"
}'
```
through the command line will send the JSON as the urlencoded key.

As you suggested, specifying --data-raw and the json content type works:
```
curl 'https://postman-echo.com/post' --data-raw '{"name":"test1","description":"тест 1"}' --header 'Content-Type: application/json'
```

Closing this issue - Postman's behavior is at par with the curl CLI.
