### ISSUE TITLE
Postman takes too long to become usable

### ISSUE THREAD

**Issue by kumar-nitish** [a85/POSTMan-Chrome-Extension#7391]
**Describe the bug**
Postman is taking too long ( more than few minutes) to become usable and till that time main window is shown as blank, also  most of the time it gets stuck on blank window itself.

It takes multiple app restart attempts to get it in a usable stage.

**To Reproduce**
1.  Close all running postman instances ( `pkill  Postman` ) 
2. Open Postman

**Expected behavior**
It should open immediately or within few seconds

**Screenshots**
If applicable, add screenshots to help explain your problem. Please make sure the screenshot does not contain any sensitive information such as API keys or access tokens. 

**App information (please complete the following information):**
 - App Type : Native App
 - Postman Version : Version 7.8.0 (7.8.0)
 - OS: MacOS Mojave [ 10.14.6 (18G95)]

**Additional context**
* I have very few API's in my collection ( around `10-15` API in `4 ` collections )
* I have disable workspace sync
* I get `Failed to subscribe to workspace for all APIs` warn in logs
* I have tried re-installing postman by cleaning up existing resources using "AppCleaner" and manually too
* Postman Canary ( Version 7.8.0-canary02 (7.8.0-canary02)) also behaves the same

**Postman Logs** 
[postman.log](https://github.com/postmanlabs/postman-app-support/files/3657463/postman.log)

**Snapshot**
![Initial Screen](https://user-images.githubusercontent.com/3117614/65684394-23f05e80-e07d-11e9-8630-5d6ab1ba6722.png)

![After multiple app restart attempts it reaches](https://user-images.githubusercontent.com/3117614/65684236-c0fec780-e07c-11e9-8541-88b5de3b7338.png)

**Comment by kamalaknn** [comment]
@kumar-nitish Can you send the logs from `View -> Developer -> Show logs in Finder` to `help@getpostman.com` to help us identify the root cause of this issue?

**Comment by kumar-nitish** [comment]
I had already shared logs @ https://github.com/postmanlabs/postman-app-support/files/3657463/postman.log. 

Recently I have updated to a new version **Version 7.10.0 (7.10.0)** and this issue seems to be resolved.

**Comment by kamalaknn** [comment]
@kumar-nitish Thanks for letting us know. The log file appears to be edited and does not have the full trace. Please let us know if you face this issue again.
