### ISSUE TITLE
Documentation of an archived collection is not archived/still accessible publicly 

### ISSUE THREAD

**Issue by Ramya-From-Postman** [a85/POSTMan-Chrome-Extension#7392]
**Describe the bug**
Upon reaching the shared request limit in the team workspace, the collections are getting archived but the published docs aren't.

**To Reproduce**
1. Publish a collection in a team workspace
2. Once the shared request limits are reached, the collection will get archived
3. You can still access the published documentation 

**Expected behavior**
Documentation should get deleted/unpublished when the associated collection gets archived.

**Screenshots**
![image](https://user-images.githubusercontent.com/40994626/65686797-bac01980-e083-11e9-8f1a-cf24b97a6216.png)

![image](https://user-images.githubusercontent.com/40994626/65686717-6452db00-e083-11e9-88d0-ba519e72c021.png)

**App information (please complete the following information):**
 - App Type Native App
 - Postman Version [e.g. 7.7.3
 - OS: macOS High Sierra 10.14

**Comment by Ramya-From-Postman** [comment]
**Describe the bug**
Upon reaching the shared request limit in the team workspace, the collections are getting archived but the published docs aren't.

**To Reproduce**
1. Publish a collection in a team workspace
2. Once the shared request limits are reached, the collection will get archived
3. You can still access the published documentation 

**Expected behavior**
Documentation should get deleted/unpublished when the associated collection gets archived.

**Screenshots**
![image](https://user-images.githubusercontent.com/40994626/65686797-bac01980-e083-11e9-8f1a-cf24b97a6216.png)

![image](https://user-images.githubusercontent.com/40994626/65686717-6452db00-e083-11e9-88d0-ba519e72c021.png)

**App information (please complete the following information):**
 - App Type Native App
 - Postman Version [e.g. 7.7.3
 - OS: macOS High Sierra 10.14

**Comment by ClementRoyer** [comment]
Up !
I have the same issue, and I would like to unpublish this archived documentation.

**Comment by sankalp0o** [comment]
@Ramya-From-Postman Sorry for the delay in getting back. Shared collections get archived because of the sharing limits for free teams. Public documentation views have a separate limit and therefore it's not archived.

That being said, we are working on making this flow better so users can unpublish the documentation for archived collections if they want. cc @Raja-Simha

**Comment by akshay-kulkarni-03** [comment]
@Ramya-From-Postman the request limit as feature was removed. Closing this issue. Feel free to re-open if issue persists.
