### ISSUE TITLE
Postman crashes Linux on AMD "Picasso" APU 

### ISSUE THREAD

**Issue by Redsandro** [a85/POSTMan-Chrome-Extension#7393]
**Describe the bug**

Any Electron 3.1.x app will crash the new AMD Picasso APU.
This is fixed in Electron 4.2.7.

**To Reproduce**

1. use AMD "Picasso" APU hardware
1. click on some saved requests
1. after a couple of seconds, observe freeze

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version 6.x - 7.x
 - OS: Linux Mint 19.1 Cinnamon x64
 - Linux 5.2.0-050200rc7-generic
 - AMD Ryzen 5 3400G with Radeon Vega Graphics
 - AMD RAVEN (DRM 3.32.0, 5.2.0-050200rc7-generic, LLVM 8.0.0) (0x15d8) 19.0.2
 - OpenGL 4.5 (Compatibility Profile) Mesa 19.0.2
 - OpenGL shading language 4.50
 - OpenGL ES 3.2 Mesa 19.0.2
 - OpenGL ES GLSL ES 3.20

**Additional context**

This hardware is relatively new. It's the latest in the AMD APU series.

The same problem exists in other apps using Electron 3.x, such as https://github.com/BoostIO/Boostnote/issues/3122 but not Atom because they skipped Electron 3.

**Please note** that this doesn't just crash the Postman app. This freezes the _entire computer_. You will lose _all your work_.

**Comment by numaanashraf** [comment]
@Redsandro Thanks for the detailed report. We have plans to update to Electron 4.x and above soon and will post updates here when it hits our early access builds.

**Comment by Redsandro** [comment]
I've become emotionally attached due to my long relationship with Postman, but I can't wait 2+ months for it to work again.

I'll be moving to [Advanced REST Client](https://install.advancedrestclient.com/install) temporarily, which uses Electron 6, and will be upgrading to Electron 7 for their next version. I'll be checking Postman from time to time.

I wish Postman and ARC would merge. The usability of Postman and the development speed of ARC.

**Comment by Redsandro** [comment]
Just checked Postman 7.14. It is still using the old unsupported Electron.

**Comment by Redsandro** [comment]
Boostnote [upgraded from Electron 3 to Electron 4](https://github.com/BoostIO/Boostnote/pull/3322/commits/7fef070dfdd39647a21ca12e0023a377761062d2), and it fixed the critical issue of crashing on AMD Picasso hardware that Postman also suffers from.

All they did is increase a version number. Can we fix this issue with Postman now? This is not some feature request. This is - for certain hardware - a critical bug.  :pray:

**Comment by Redsandro** [comment]
Installed Postman 7.17.0 in 2020, 7 months after Picasso APU was launched, 5 months after bug reported.

Clicked on help -> computer frozen.  :rage: 
Apparently, Postman still uses Electron 3. :angry: Otherwise it wouldn't crash Picasso machines.

---

@numaanashraf @codenirvana @abhijitkane @SueSmith @coditva Please read this as if you can hear slight despair and genuine disbelief in my voice:

Why are we still using the outdated **Electron 3** when it's known to have **serious problems** like instantly **freezing certain computers** which has been **fixed long ago** in Electron 4.2.7 and up, but **not backported** to 3 because **Electron 3 is no longer supported and will not receive further bugfixes or security fixes**?

I can understand that jumping from Electron 3 to Electron 8 would be scary as it involves 5 layers of uncertainty, but upgrading to Electron 3 to 4 is rather painless.

Please look at this.

**Comment by erikbaan** [comment]
@Redsandro does this issue occur on OSX as well?

**Comment by Redsandro** [comment]
@numaanashraf any update on this?

@numaanashraf commented:
> We have plans to update to Electron 4.x and above soon

**Comment by numaanashraf** [comment]
@Redsandro  Our early access 'Canary' channel - https://www.postman.com/downloads/canary has been upgraded to use Electron v7.2.x. Could you try out this build and let us know?

**Comment by Redsandro** [comment]
Good to hear! :+1: I'll get back to you.

**Comment by twitharshil** [comment]
Hi @Redsandro 
Could you try out our early access Canary build? https://www.postman.com/downloads/canary/. You can install and use the Canary build side by side with the stable app. Do try this out and let us know if the issue is fixed for you :)

**Comment by Redsandro** [comment]
@twitharshil this works without crashing! :confetti_ball: :fireworks: :tada: 

I'm 97% sure this will work fine since it didn't crash in the first 5 minutes. But I'll use it for a bit longer and see what happens.

@numaanashraf I had not forgotten about this. The affected computer is at the office, and today is the first day I'm back at the office since the announcement.

Let me know when this will be merged with mainline and I will update the other machines!

**Comment by twitharshil** [comment]
Hey @Redsandro 
We’ve pushed the updates in our stable app v7.25.1 that has upgraded Electron v7.2.x 🎉. 
Feel free to reopen the issue if you are still facing this problem on Postman v7.25.1 onwards.

**Comment by Redsandro** [comment]
It took the better part of a year, but I am glad that we can finally switch back to Postman on our Picasso machines! :muscle:
