### ISSUE TITLE
Postman requests hanging forever

### ISSUE THREAD

**Issue by townofdon** [a85/POSTMan-Chrome-Extension#7394]
> Which Postman App, Chrome and Operating System version you are using. You can check this out in Settings -> About section.

Postman app for Mac, Version 7.8.0 (7.8.0)

Chrome Version 77.0.3865.90 (Official Build) (64-bit)

Mac OS Mojave V 10.14.6

> Is the bug reproducible every time, or do you see it occasionally?

Every time.

> Did you first encounter it recently, or has it always been there?

Issue started yesterday; seemed to coincide with latest update to Postman v. 7.8.0

> If it is a UI issue, a screenshot or GIF will help tremendously. (Tip: For quick gifs, check out http://www.cockos.com/licecap/)

> Do you have the Postman Interceptor switched on? (applicable for the Chrome app)

No

> If the request/response flow is not working, be sure to check and include details from the DevTools window (More on this at https://www.getpostman.com/docs/errors).

DevTools seems to have issue syncing when Postman first loads, based on the following screenshot.

![image](https://user-images.githubusercontent.com/5880655/65692834-4bc1d100-e041-11e9-92b9-85f4f75a3862.png)

> **Describe the bug**
> A clear and concise description of what the bug is.

Every request to http://localhost:8000 hangs forever. At first I thought it was an issue with our API codebase, but I spun up an entirely different server (that hasn't been touched recently and was working previously) and Postman has the same issue.

> **To Reproduce**
> Steps to reproduce the behavior:
1. Spin up any server listening on porty 8000
2. Open Postman
3. Make any request
4. Request hangs forever and eventually ends with the following err:

```
Could not get any response
```

> **Expected behavior**
> A clear and concise description of what you expected to happen.

Requests to localhost work, or have some meaningful error response, instead of hanging.

> **Screenshots**
> If applicable, add screenshots to help explain your problem. Please make sure the screenshot does not contain any sensitive information such as API keys or access tokens.

![image](https://user-images.githubusercontent.com/5880655/65693214-ede1b900-e041-11e9-9d74-bf5c20548ca6.png)

> **App information (please complete the following information):**

- **App Type:** Postman app for Mac, Version 7.8.0 (7.8.0)
- **OS:** Mac OS Mojave V 10.14.6

> **Additional context**
> Add any other context about the problem here.

Issue first started yesterday afternoon - checked the release notes and latest version (7.8.0) was indeed released yesterday, though unsure of the time.

I also tried reverting to a previous version of Postman, but that did not seem to resolve the issue. It could be that the prev version automatically updated when the app was opened. Since 7.8.0 was considered a minor update there's no way to disable automatic updates.

**Comment by townofdon** [comment]
Update: external requests work just fine (e.g. http://google.com), but local requests do not (http://localhost:8000)

**Comment by codenirvana** [comment]
@townofdon we need additional information to reproduce this internally.
Can you check if clearing cookies (if set) or removing test script fixies this issue?

Also, can share a sample server (without sensitive details) which we can use to reproduce this issue?

**Comment by townofdon** [comment]
> @townofdon we need additional information to reproduce this internally.
> Can you check if clearing cookies (if set) or removing test script fixies this issue?
> 
> Also, can share a sample server (without sensitive details) which we can use to reproduce this issue?

@codenirvana Clearing cookies seems to resolve the issue. Thanks!
