### ISSUE TITLE
Error installing postman using flatpak on fedora.

### ISSUE THREAD

**Issue by g5becks** [a85/POSTMan-Chrome-Extension#7395]
**Describe the bug**
Unable to install Postman on fedora silverblue

**To Reproduce**
1. On fedora silverblue 30
2. Open software center
3. Search for postman
4. Click install

Expected postman to install.

Instead I get the following error,

>  error: Failed to install com.getpostman.Postman: Wrong size for extra data https://dl.pstmn.io/download/version/7.8.0/linux64

**Comment by numaanashraf** [comment]
@G5Becks Flatpak is not an officially supported distribution at the moment and is community maintained. Please file an issue at https://github.com/flathub/com.getpostman.Postman. I see that there are been a fix recently that addressed the "wrong size of extra data" issue, so maybe try installing again?
