### ISSUE TITLE
When generating test requests from a schema, use the example values, not data type

### ISSUE THREAD

**Issue by rpbarbati** [a85/POSTMan-Chrome-Extension#7397]
**Is your feature request related to a problem? Please describe.**
In order for me to generate a postman collection from a schema, I must first copy the example values from swagger editor and paste them into my schema so that the POSTMAN generate collection feature will use them.   Swagger editor builds the example request objects using the example values from the schema for all child elements of the request.  POSTMAN should do the same.

**Describe the solution you'd like**
When generating a test collection from a schema (swagger, openAPI, etc.) the current implementation generates the request bodies in two different ways.   

1) If the top level request objects in the schema have an example value, then your generator uses that value, which is fine.  

2) If the top level request objects do not have an example value, then your generator builds a request using the type value associated with each child element.  This is not fine as in almost all cases the type value is not a valid value.

This request is specifically targeted at modifying the second behavior above as follows - if the top level request object does not have an example value, the generator should build a request object utilizing the example value from each child element.  This is good because in most  cases, the example values for each child element will be valid values.

Consider a child element named dueDate with a type string and example of "2019-10-01T11:00:00".  Generating a request with dueDate: "<string>" requires manual editing.  Generating a request with dueDate:  "2019-10-01T11:00:00" does not require any editing.

**Describe alternatives you've considered**
I am currently having to copy the example values for each request out of the swagger editor, then paste them back into the schema prior to generating the postman collection.  This must be repeated for every change to any child element.

**Additional context**

**Comment by jehrlich** [comment]
I think @rpbarbati is describing what I just ran into. Given this snippet from an openAPI.yaml schema:
```
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: user1
                password:
                  type: string
                  example: password1
            example: {"username": "user2","password": "password2"}  
```
The collection generator creates a request for `user2`, or if the `user2` example is removed, then the request has placeholder data. The generator should generate a request for `user1` with the above snippet.

**Comment by ttop** [comment]
Postman used to use the examples that were defined with the OpenAPI request schema, my team started seeing them _not_ appear correctly in 7.14.0 (7.13.0 worked as expected).

**Comment by mccannt** [comment]
This issue should now be resolved. 
If this is still an issue, please let us know or reopen this issue.
