### ISSUE TITLE
Postman console reports "null" but the value is actually "undefined"

### ISSUE THREAD

**Issue by vdespa** [a85/POSTMan-Chrome-Extension#7398]
**Describe the bug**

**To Reproduce**
1. Try logging a value that is undefined, like `console.log(undefined);`
2. Open the console and you will see null

**Expected behavior**
null and undefined are two different things.

console.log(undefined); should show undefined in the console

**Screenshots**

![image](https://user-images.githubusercontent.com/1197635/65730647-58611c00-e077-11e9-9fa8-919b8402b03e.png)

![image](https://user-images.githubusercontent.com/1197635/65730632-4c755a00-e077-11e9-938e-ea15bc3be493.png)

**App information (please complete the following information):**
 - App Type: Native App
 - Postman Version:  7.6.0
 - OS: macOS High Sierra

**Comment by saswatds** [comment]
Hi @vdespa, we are tracking this bug in a previously open issue https://github.com/postmanlabs/postman-app-support/issues/5705

Plans to fix to issue are already on the way. I will be closing this issue for now as Duplicate. 

Thanks for reporting.
