### ISSUE TITLE
Generate Code Snippets - Showing different data content

### ISSUE THREAD

**Issue by Aaron-Browne** [a85/POSTMan-Chrome-Extension#7403]
**Describe the bug**
After creating a multi-part form-data POST request the "Generate Code Snippets" option  produces different header output for the type 'HTTP' vs JavaScript->XHR:

**To Reproduce**
1. Create a form-data POST request that has multi-part elements e.g. A text element and a file element:
![image](https://user-images.githubusercontent.com/35369020/65764330-49cd4000-e11d-11e9-9754-7431fe70d564.png)

2. Click on "Code" and select the HTTP type: 
![image](https://user-images.githubusercontent.com/35369020/65765378-00322480-e120-11e9-9cda-a0d26e08a576.png)

3. Now select the type JAVASCRIPT->XHR:
![image](https://user-images.githubusercontent.com/35369020/65765170-68343b00-e11f-11e9-82d3-92266495085a.png)

**Note that the content-type is different.**

Expected behaviour is for the JavaScript->XHR option to produce code that is equivalent to the HTTP request option, so that it can be copy pasted, without modification, into the user's code and behave in the same manner as clicking Send in Postman.  

**App information (please complete the following information):**
 - App Type: JavaScript
 - Postman Version: v7.2.2 (Upgraded to v7.7.3 and got the same issue)
 - OS: Windows 10

**Additional context**

**Comment by shreys7** [comment]
Hey @Aaron-Browne can you switch over to the new code generation mode and let us know if this problem still persists. Click the Settings icon on the top right -> Settings -> General and then enable `New Code Generation Mode`

**Comment by mccannt** [comment]
@Aaron-Browne Any update on this when using the new feature as outlined by @shreys7 above?

**Comment by mccannt** [comment]
Closing this issue out. 
If this is still happening, please let us know.
