### ISSUE TITLE
Postman is soooo slow on 16gb ram and ssd hard drive and cpu core i5!!!!

### ISSUE THREAD

**Issue by sinahosseini76** [a85/POSTMan-Chrome-Extension#7404]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**App information (please complete the following information):**
 - App Type [e.g. Chrome App, Native App]
 - Postman Version [e.g. 7.0.0]
 - OS: [e.g. macOS High Sierra 10.13.2]

**Additional context**

**Comment by kamalaknn** [comment]
Hey @sinahosseini76 

I'm closing this as a duplicate of # 7294. Please follow the original thread for updates.

**Comment by sinahosseini76** [comment]
thanks
