### ISSUE TITLE
issue while opening postman, not opening

### ISSUE THREAD

**Issue by Chandrashreej** [a85/POSTMan-Chrome-Extension#7405]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**App information (please complete the following information):**
 - App Type [e.g. Chrome App, Native App]
 - Postman Version [e.g. 7.0.0]
 - OS: [e.g. macOS High Sierra 10.13.2]

**Additional context**

**Comment by cyrielle-hada** [comment]
@Chandrashreej would you be able to follow the instructions outlined in the below help center article? 
- https://support.getpostman.com/hc/en-us/articles/360025359014-How-to-resolve-the-Could-not-open-Postman-error-

If this doesn't work, please file a ticket to our Support team from [this page](https://support.getpostman.com/hc/en-us/requests/new?_ga=2.83206293.280658567.1569832625-1387803517.1563368009).
