### ISSUE TITLE
unable to fetch the data in postman response 

### ISSUE THREAD

**Issue by teja5** [a85/POSTMan-Chrome-Extension#7408]
the Api call which i was making is working in deprecated chrome app but not in desktop app

![Capture](https://user-images.githubusercontent.com/26085314/65885120-ae0b3080-e3b7-11e9-84e5-cc9914bbd08e.PNG)
<img width="728" alt="isseue" src="https://user-images.githubusercontent.com/26085314/65885146-bcf1e300-e3b7-11e9-8e23-cba9584457c7.PNG">

**Comment by codenirvana** [comment]
@teja5 Looks like there's som application logic which rejects request based on `User-Agent` request header (maybe trying to allow only browser requests).

Check if adding a browser user-agent (like `Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; Trident/5.0; Trident/5.0)`) fixes this issue.
