### ISSUE TITLE
[MacOS] Postman crashes when starting capture proxy if port is already taken

### ISSUE THREAD

**Issue by volaruQQ** [a85/POSTMan-Chrome-Extension#7409]
[Mac] Postman crashes when starting capture proxy if port is already taken

1. Use Charles to make a proxy and capture requests on the 8888 port
2. Open postman
3. Click on "Capture requests and cookies with postman" icon 
4. Select Proxy and toggle it to On

**Expected behavior**
User should see a message that selected port can't be used or at least not crash with a generic error. 
 
**Actual behaviour**
Postman crashes. Before crashing you can see the toast message showing "Proxy Connected"

 - App Type Native App
 - Postman Version 7.8.0
 - OS: MacOS Mojavi 10.14.5

**Additional context**
I haven't tested other things but i believe the crash is caused by the fact that the port is in use by another app or blocked. In my case Charles was using the port

**Comment by castroalves** [comment]
Same as #5905. I run into this problem today and I can't use this feature.

My setup:
- Native App
- Postman Version 7.10.0
- MacOS Mojavi 10.14.6 (18G103)

**Comment by denizoztreves** [comment]
Same here : 
 - MacOS Native app
 - Postman Version 7.19.1 (7.19.1)
 - OS: macOS Catalina 10.15.3

**Comment by chughmayank** [comment]
Hey guys! the issue has been resolved with upgrade v7.33.0. Feel free to try it and reach out if you still face some issue.
cheers!
