### ISSUE TITLE
Cookies not showing

### ISSUE THREAD

**Issue by mhamzaee** [a85/POSTMan-Chrome-Extension#7410]
**Describe the bug**
The cookies hyperlink is not visible next to the 'Code' hyperlink so I'm unable to update my cookies.
How do I get the Cookies hyperlink to show up?

**Screenshots**
![image](https://user-images.githubusercontent.com/55989935/65889083-7bc8e700-e355-11e9-9205-f9f078f466d1.png)

**App information (please complete the following information):**
Postman for Chrome
Version 5.5.4
OS X / x86-64
Chrome 77.0.3865.90

**Comment by codenirvana** [comment]
@mhamzaee You are using the deprecated Chrome app.
Download the latest Postman Native app here: https://www.getpostman.com/downloads/
