### ISSUE TITLE
Automatically add Content-Length header with value set to number of bytes in payload.

### ISSUE THREAD

**Issue by chainhead** [a85/POSTMan-Chrome-Extension#7413]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
My APIs need the `Content-Length` header to be sent whose value could be zero or greater. Can you please provide a flag to enable the addition of this header automatically with its value set to number of bytes of body?

**Describe alternatives you've considered**
Add `Content-Length` header manually.

**Additional context**
None.

**Comment by saswatds** [comment]
@chainhead I am closing this issue in favour of the issue already open, we can discuss the issue there instead.
