### ISSUE TITLE
Variables in URL not replaced with environment values.

### ISSUE THREAD

**Issue by chainhead** [a85/POSTMan-Chrome-Extension#7414]
**Describe the bug**
Variables for `https` and `http` URLs for production and development environments are not replaced.

**To Reproduce**
1. Set-up an environment named **Production**.
2. Set variables as:
   1. `scheme` = `https`
   2. `host` = `api.prod.com`
   3. Enter URL in Postman as `{{scheme}}://{{host}}/resource`
4. The URL is never invoked.
5. Set-up an environment named **Development**.
6. Set variables as:
   1. `scheme` = `http`
   2. `host` = `localhost`
   3. Enter URL in Postman as `{{scheme}}://{{host}}/resource`
3. The URL is never invoked.

**Expected behavior**
The URL should be resolved with correct values and invoked.

**Screenshots**
None

**App information (please complete the following information):**
 - App Type **Chrome**
 - Postman Version **7.8.0**
 - OS: **macOS Mojave 10.14.6**

**Additional context**
None

**Comment by saswatds** [comment]
Hi @chainhead, I am not able to reproduce this issue. The request goes through just fine

<img width="877" alt="Screenshot 2019-10-02 at 12 57 09 AM" src="https://user-images.githubusercontent.com/8796447/65993836-9d3de600-e4af-11e9-8328-a26b0f6837e7.png">

**Comment by chainhead** [comment]
Is there a way to see what the URL resolves into before actually making the invocation?

**Comment by chainhead** [comment]
Hmm...I had to manually enter the value `host` under current value column to get this working. This is not very intuitive. ;)

**Comment by KoenZomers** [comment]
> Hmm...I had to manually enter the value `host` under current value column to get this working. This is not very intuitive. ;)

Stumbled upon the same here. Some of the variables do seem to be copied over to current value automatically and some don't. The URL variables fall into the don't category which also left me to scratch my head. Thanks for sharing your finding here. It helped me as well :)

**Comment by DeanHristov** [comment]
I still have the problem with **v8.0.5**. I couldn't find reason why this issue is closed? 
<img width="1556" alt="Screenshot 2021-02-11 at 19 41 32" src="https://user-images.githubusercontent.com/3283991/107675875-3171ad00-6ca1-11eb-9076-8fbbdab3a44b.png">

**Comment by aleksandar-trajkov** [comment]
> I still have the problem with **v8.0.5**. I couldn't find reason why this issue is closed?

Copy the value from initial, and paste it in current value column, it will start working. If you just put it in initial, it auto-populates it, but it doesn't work.

**Comment by dumim** [comment]
> > I still have the problem with **v8.0.5**. I couldn't find reason why this issue is closed?
> 
> Copy the value from initial, and paste it in current value column, it will start working. If you just put it in initial, it auto-populates it, but it doesn't work.

This fixed it for me

**Comment by CaptainAgilek** [comment]
> > I still have the problem with **v8.0.5**. I couldn't find reason why this issue is closed?
> 
> Copy the value from initial, and paste it in current value column, it will start working. If you just put it in initial, it auto-populates it, but it doesn't work.

true
it autofills the current value, but actsx as it is not filled and u have to do it manually
version 8.5.1
