### ISSUE TITLE
I am able to log in and do requests, but not able to sync

### ISSUE THREAD

**Issue by KalleVuorjoki** [a85/POSTMan-Chrome-Extension#7415]
**Describe the bug**
I cannot access the team workspace or collections, it says "You need to have an active internet connection to be able to switch to or create a workspace.". If I login via browser I'm able to see my personal teams collections. I'm able to log in and create successful requests on Postman. 

**To Reproduce**
1. Start the app
2. Log in to your account
3. Go Team workspace
4. See the error

**Expected behavior**
I would see my and teams collections.

**Screenshots**
<img width="357" alt="Screen Shot 2019-10-01 at 10 49 56" src="https://user-images.githubusercontent.com/3080364/65943989-63ca9380-e439-11e9-9a4b-f8581f9fd179.png">

**App information:**
 - App Type [Native App]
 - Postman Version [7.8.0]
 - OS: [macOS High Sierra 10.13.6]
 - Postman Pro plan

**Additional context**
This started over week ago, was running ~7.6.0 version and thought updating to latest would help. Update didn't fix the issue.

**Comment by Ghusar** [comment]
@KalleVuorjoki can you write to us help@getpostman.com so that we take a closer look.

**Comment by KalleVuorjoki** [comment]
So it seems the issue is with the ISP (Telia Finland) blocks the ports that App uses. Everything works fine with VPN.

**Comment by Ghusar** [comment]
Closing this issue for now, feel free to reopen it if the problem still exists in any other way

**Comment by ashishraman** [comment]
Can someone tell me which port is being used so I can request my ISP to unblock it.
