### ISSUE TITLE
Curl imoprt bug

### ISSUE THREAD

**Issue by madhu131313** [a85/POSTMan-Chrome-Extension#7416]
**App information (please complete the following information):**
 - App Type [e.g. Chrome App, Native App] native app
 - Postman Version [e.g. 6.0.1] 7.8.0
 - OS: [e.g. macOS High Sierra 10.13.2] macOS High Sierra

Import this following curl results in invalid body string

curl 'http://env2.abc.com:3015/execution/api/v1/executions/5d7357ba8658504790a0058b/project_roles/5d61141e8658501d85e951ea/leads/5d7f612486585050f208b90a' -X PATCH -H 'access-token: lXgvOPSlfhUEy-nO00nEKg' -H 'client: 0GVCptAVGAPgoxcQm2yk5g' -H 'uid: ss-demo@abc.com' -H 'x_client_id: intern_android' -H 'X-Request-Id: android-intern-ca8d4b92ce2fce1d-1569918141701' -H 'Content-Type: application/json; charset=UTF-8' -H 'Connection: Keep-Alive' -H 'Accept-Encoding: gzip' -H 'User-Agent: okhttp/3.10.0' --data-binary $'{"lead":{"image":"https://abc-mobile-app.s3.amazonaws.com/project/5d57e53086585009c1731a04/lead/5d7f612486585050f208b90a/IMG-20190922-195211-jpg","geo_location":"[12.9099413, 77.65207389999999]","time_question":"08:02:AM","city":"delhi","multiple_select":["Option 2","Option 1","Option 4"],"date_time_question":"2019-08-25 08:02:AM","phone_number_question":"9738083817","email_address_question":"harsha2010.v1@gmail.com","float_value_question":"12.9","number":"33996993","file":"https://abc-mobile-app.s3.amazonaws.com/project/5d57e53086585009c1731a04/lead/5d7f612486585050f208b90a/IMG-20190922-195211-jpg","date_question":"2019-08-25","name":"Tesq","long_text_question":"Text 2vdjxjdn hi\\njjjkm njkkn ddndmnnnnn I\'d","single_select":"Option 3","email":"harsha2010.v1@gmail.com","current_location":"[12.910147, 77.6522729]"},"version":0}' --compressed

Here is the body string. 
{"lead":{"image":"https://abc-mobile-app.s3.amazonaws.com/project/5d57e53086585009c1731a04/lead/5d7f612486585050f208b90a/IMG-20190922-195211-jpg","geo_location":"[12.9099413, 77.65207389999999]","time_question":"08:02:AM","city":"delhi","multiple_select":["Option 2","Option 1","Option 4"],"date_time_question":"2019-08-25 08:02:AM","phone_number_question":"9738083817","email_address_question":"harsha2010.v1@gmail.com","float_value_question":"12.9","number":"33996993","file":"https://abc-mobile-app.s3.amazonaws.com/project/5d57e53086585009c1731a04/lead/5d7f612486585050f208b90a/IMG-20190922-195211-jpg","date_question":"2019-08-25","name":"Tesq","long_text_question":"Text 2vdjxjdn hi\\njjjkm njkkn ddndmnnnnn I\d,single_select:Option 3,email:harsha2010.v1@gmail.com,current_location:[12.910147, 77.6522729]},version:0}'

**Comment by abhijitkane** [comment]
@madhu131313 This is an invalid cURL command - I'm not able to execute it on the terminal either.

You'll need to escape the `I'd` to `I\'d` to run it in curl or import into Postman.
