### ISSUE TITLE
[Windows] Borderless window

### ISSUE THREAD

**Issue by hwooo** [a85/POSTMan-Chrome-Extension#7417]
**Describe the solution you'd like**
![border](https://user-images.githubusercontent.com/46282492/65979037-9f07a980-e4af-11e9-80c9-40c7b2cb8785.PNG)

Currently, color of the title bar is always white on Windows so I feel it doesn't match with dark theme. I would like color of the title bar to be integrated into dark theme, like following screenshot.

![ijwindow](https://user-images.githubusercontent.com/46282492/65980449-27874980-e4b2-11e9-8936-77be1d220ce9.PNG)

**Comment by rawvoid** [comment]
Is there any news?

**Comment by jviotti** [comment]
Merging this feature request with https://github.com/postmanlabs/postman-app-support/issues/5473
