### ISSUE TITLE
Feature Request: improved Collection reordering

### ISSUE THREAD

**Issue by grinderX19** [a85/POSTMan-Chrome-Extension#742]
Clicking on Collection item is sometimes considered as drag'n'drop. This is quite unusual as I don't get such behavior in any other software.

Can you please add some "dead zone" so drag'n'drop for less than 5 pixel or something will be considered as a click?

**Comment by abhijitkane** [comment]
The sorting/dropping behavior has been updated in v1.0.4

**Comment by jaredmcateer** [comment]
Verified that this is working *much* better now. Thanks!

**Comment by grinderX19** [comment]
Agreed, the issue is gone.
Closing the issue.
