### ISSUE TITLE
Add support for Linux CentOS 7

### ISSUE THREAD

**Issue by abhinavgurung** [a85/POSTMan-Chrome-Extension#7421]
**Describe the bug**
Not able to run the postman despite fresh install
enviornment: linux, centos 7

**To Reproduce**
1. downloaded postman for linux 64 bit from https://www.getpostman.com/downloads/
2. extracted the folder
3. on my cmd  (cd to that folder) typing postman
4. error in screenshot. clicking on postman executable does not respond
**Expected behavior**

**Screenshots**
After typing: postman
![image](https://user-images.githubusercontent.com/12020147/66066868-e5a1e600-e539-11e9-9c9c-22fd97a26433.png)

**App information (please complete the following information):**
 - App Type [Desktop application]
 - Postman Version [7.8.0]
 - OS: [linux, centos 7]

**Comment by harryi3t** [comment]
@abhinavgurung What is the exact version of CentOS that you are using? If you are on or above CentOS 7.6, you can install Postman using Snap - https://snapcraft.io/postman
Reference - https://snapcraft.io/docs/installing-snap-on-centos

**Comment by numaanashraf** [comment]
@abhinavgurung We do not officially support CentOS at the moment. Keeping this as a feature request and we will pick this up if more users are interested in this. 

Current supported Linux platforms: https://learning.getpostman.com/docs/postman/launching-postman/installation-and-updates/#linux

**Comment by numaanashraf** [comment]
Closing issue for now. We will reopen if more users are interested in this.
