### ISSUE TITLE
POST X-www-form-urlencoded array of objects

### ISSUE THREAD

**Issue by robskrob** [a85/POSTMan-Chrome-Extension#7423]
I am trying to make a POST request with `X-www-form-urlencoded` that contains an array of objects. I am able to do it with a `curl` request like this one:
```
curl https://a.klaviyo.com/api/v1/email-template/dqQnNW/send \
  -X POST \
  -d api_key=API_KEY \
  -d from_email=george.washington@example.com \
  -d from_name='George Washington' \
  -d subject='Your Weekly Summary' \
  -d to='[{ "email" : "recipient@example.com", "name" : "Recipient Name" }]' \
  -d context='{ "name" : "Recipient", "notifcation_count" : 8 }'
```

This is the tricky part ` -d to='[{ "email" : "recipient@example.com", "name" : "Recipient Name" }]' \`

As you can see in the screenshot:
<img width="1007" alt="Screen Shot 2019-10-02 at 5 26 05 PM" src="https://user-images.githubusercontent.com/4349424/66083837-30702d80-e53b-11e9-972c-d689ae295128.png">

I am attempting to send the array but the server is telling me that it cannot find the `to` key in the body.

Am I making an incorrect postman request? What is wrong with my postman request?

**App information (please complete the following information):**
 - App Type Native App
 - Postman Version 7.3.6
 - OS:  macOS Mojave 10.14.5

**Comment by DannyDainton** [comment]
Hey @robskrob / Anyone else who reacted to the issue

Is this something that you're still having issues with?

**Comment by robjewell-ibotta** [comment]
Hi, @DannyDainton thank you for your message. This was some time ago, and I am not too sure if I can presently recreate the issue, seeing as the use case is pretty old for me.

**Comment by DannyDainton** [comment]
I appreciate the response and apologies that this has been around for so long.

I'm going to close this for now but I we can look to reopen it again if others respond.

Thanks again.
