### ISSUE TITLE
Close tab button is on the wrong side for Mac users

### ISSUE THREAD

**Issue by Kwadz** [a85/POSTMan-Chrome-Extension#7426]
### Summary

Close tab button is on the wrong side for Mac users

### Expected behavior

With an ergonomic approach, the close tab button should be on the same side as the OS, therefore on the left.

### Actual behavior

The close tab button is on the right. It should be at least configurable or by default on the left like every close button in the OS.

**Comment by sidnt** [comment]
@Kwadz it's subjective. On Mac, in Vivaldi & Opera browsers, the close tab button is on the left side of the tab while in Firefox, Chrome, Chromium the close tab button is on the right.

**Comment by Kwadz** [comment]
@sidnt, it's not subjective with an ergonomic approach. Firefox, Chrome, Chromium just break UX consistency. It's not because they are a lot to be wrong that means they're right.

**Comment by a85** [comment]
There are no plans to change this as the behavior of panes within an application is up to the app. Browsers and code editors on the Mac platform largely stick to close button on the right.

**Comment by Kwadz** [comment]
@a85, I think it's a mistake to close this issue. That should at least be kept in low priority like Sublime does.

Anyway, how come for you it's acceptable to do things the wrong way and break UX consistency?
Do you have a valid reason for that (sorry but what you mentioned is not valid, please read again my previous message)?
Don't you want to help making the world better instead of following ones who content themselves with mediocrity? Let's follow the good not the bad.

Where is the part of code managing this button? I'm gonna try to do it. **Please re-open the issue and let's improve things together**.

**Comment by intenser** [comment]
> Browsers and code editors on the Mac platform largely stick to close button on the right.

Not always. The popular Visual Studio Code has a configurable option.

I agree to Kwadz that **the issue has to be re-opened**

**Comment by AbhishekPathania** [comment]
This issue should be reopened, as intenser has said, VS Code gives you the open to configure cross button.
Please provide a configuration at least.

For my workflow it's only postman that breaks the UX Consistency.

**Comment by aitizazsyed02** [comment]
Hey Postman Team,

Why this issue is overlooked and closed?
