### ISSUE TITLE
Only one security function is added with Swagger/OpenAPI import

### ISSUE THREAD

**Issue by Lyra2108** [a85/POSTMan-Chrome-Extension#7427]
**Describe the bug**
Unlike other open bugs e.g. #1470 the schemes are not completly ignored, but like only mentioned in the comments of the other bug, only the first is effectiv. This does apply to all Open API versions.

**To Reproduce**
Below you find examples to test the import with, in the v2.0 example the 2nd added without a `-` to indicate that both are needed. In the v3.0 the 2nd is added with a `-` to indicate that one of them is needed. 
Both ways do not work at the moment.
For the v2.0 only the API-Key will be picked and for the v3.0 only the basic auth will be effectiv.

For the v2.0 import:
```
swagger: "2.0"
info:
  title: API Title
  version: "1.0"
host: test.invalid
basePath: /
schemes:
  - https
paths:
  /test:
    get:
      responses:
        "200":
          description: OK

security:
  - API-Key: []
    basic: []

securityDefinitions:
  API-Key:
    type: apiKey
    name: x-rest-key
    in: header
  basic:
    type: basic
```

For the v3.0 import:
```
openapi: '3.0.2'
info:
  title: API Title
  version: '1.0'
servers:
  - url: https://api.server.test/v1

components:
  securitySchemes:
    API-Key:
      type: apiKey
      name: x-api_key
      in: header
    basic:
      type: http
      scheme: basic

security:
  - basic: []
  - API-Key: []
      
paths:
  /test:
    get:
      responses:
        '200':
          description: OK
```

**Expected behavior**
All defined security methods should be added to an imported request and not only the first.

**Comment by shanecp** [comment]
Can confirm this is a bug. Example to reproduce the issue is below. Both AccessToken and APIToken should be added, but it doesn't.

Also the root level security components are not added to the internal routes as required by the spec.

```
openapi: 3.0.2
info:
    title: 'Open API v3'
    version: 1.0.0.20200712
servers:
    -
        url: 'http://example.com'
        description: desc
components:
    securitySchemes:
        SecurityApiKey:
            type: apiKey
            description: 'Application API Key'
            name: x-api-key
            in: header
            schema:
                type: string
                example: '{{x-api-key}}'
        SecurityAccessToken:
            type: apiKey
            description: 'User access token'
            name: x-access-token
            in: header
            schema:
                type: string
                example: '{{x-access-token}}'
paths:
    /api/v1/guests:
        get:
            responses:
                '200':
                    description: Success
            security:
                - SecurityAccessToken: []
                - SecurityApiKey: []
security:
    - SecurityApiKey: []
```

**Comment by chughmayank** [comment]
This is being tracked at #6833 . Closing this ticket. Please feel free to reopen the ticket if you feel your request/issue is different from the parent issue

**Comment by Lyra2108** [comment]
I do not have the permissions to reopen this request.

I would say that this are different features. The one you mentioned is not about OpenAPI, it seems to me that there the goal is to switch between different authentication methods for a request, where all methods are valid.

With this I dont want any switching of auth methods, because in my main use case I need both at the same time.

From the v2.0 example above :

```
security:
  - API-Key: []
    basic: []
```

With that the end goal would be to have an API-Key header AND a Basic Auth header after the import of the OpenAPI because both of this are needed for a request to work. I do not want to switch between the two methods.
