### ISSUE TITLE
'protocolProfileBehavior' is not set to true in extracted Json collection while the same is set to true in postman app

### ISSUE THREAD

**Issue by supriya121061** [a85/POSTMan-Chrome-Extension#7429]
**Describe the bug**
'protocolProfileBehavior' is not set to true in extracted Json collection while the same is set to true in postman app

**To Reproduce**
1. Create any 2 get and post request
2. For both of them 'Automatically follow redirects' is On.
![image](https://user-images.githubusercontent.com/56124432/66137851-9d47fe00-e5f5-11e9-866e-125b6f7aaa8c.png)

3. Export the collection
4. Open the exported Json collection in notepad ++
5. Below set of snippet is missing in file, where we can see the one when setting for the same is turned off.
"protocolProfileBehavior": {
				"followRedirects": true
			},

**Expected behavior**
'protocolProfileBehavior' should be set to true

**Screenshots**

![image](https://user-images.githubusercontent.com/56124432/66138521-adaca880-e5f6-11e9-9274-bc98a6bfd78b.png)

**App information (please complete the following information):**
 - Postman
 - Postman Version [v7.8.0]
 - OS: Windows, newman 4.4.0

**Comment by codenirvana** [comment]
@supriya121061 `protocolProfileBehavior` changes are not persisted if the setting is getting inherited from global (in this case `followRedirects`).

Check if turning this `off` and `on` again persists the option in the exported collection?
