### ISSUE TITLE
Lower case "Content-Type" not recognized

### ISSUE THREAD

**Issue by nicolashenry** [a85/POSTMan-Chrome-Extension#743]
My server returns headers like :
content-type: application/json; charset=utf-8
But Postman does not recognize it.

**Comment by sumit1317** [comment]
Hi,
An api call from postman is working perfectly fine, but when I take the code from postman and run it as part of nodejs, it is giving me an error. Code generated by postman is - 
  var options = { method: 'POST',
              url: 'https://uat.nlis.mla.com.au/soap/upload.aspx',
              headers:
               { 'postman-token': '52cdfc42-4f0f-fd7c-0e94-3301a3c0e520',
                 'cache-control': 'no-cache',
                 'content-type': 'multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW' },
              formData:
               { '':
                  { value: fs.createReadStream(__dirname + 'nlisMovement.xml'),
                    options: { filename: 'nlisMovement.xml', contentType: null } } } };
            request(options, function (error, response, body) {
              if (error) throw new Error(error);
              console.log(body);
              resolve(body);
            });

Attachment file named nlisMovement.xml is - 
<?xml version="1.0" encoding="utf-8" ?>
<SOAP-ENV:Envelope
  xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/"
  xmlns:nlis="http://www.nlis.com.au/soap/ver2.0/nlis-soap.xsd">
<SOAP-ENV:Header>
<nlis:originator-grp>
<nlis:user>xxxxxx</nlis:user>
<nlis:password>xxxxxxx</nlis:password>
<nlis:email>xxxxxx@xxxxxx.com</nlis:email>
</nlis:originator-grp>
<nlis:create-date>20171201</nlis:create-date>
<nlis:create-time>135203</nlis:create-time>
</SOAP-ENV:Header>
<SOAP-ENV:Body>
<nlis:P2PTransfer>
<nlis:transaction-name>My P2P Transfer</nlis:transaction-name>
<nlis:transfer-date>20171201</nlis:transfer-date>
<nlis:buyer-pic>3MRDG099</nlis:buyer-pic>
<nlis:free-text>2004 Weaners</nlis:free-text>
<nlis:nvd-grp>
<nlis:event-time>13:30:00</nlis:event-time>
<nlis:nvd-serial-no>1009675</nlis:nvd-serial-no>
<nlis:pic>3WERT546</nlis:pic> <nlis:tag-list-grp>
<nlis:rfid>982 123525464162</nlis:rfid><nlis:rfid>940 110000856447</nlis:rfid></nlis:tag-list-grp>
</nlis:nvd-grp>
</nlis:P2PTransfer>
</SOAP-ENV:Body>
</SOAP-ENV:Envelope>

I am receiving following error from server.
<SOAP-ENV:Envelope xmlns:SOAP-ENV='http://schemas.xmlsoap.org/soap/envelope/'><SOAP-ENV:Body><SOAP-ENV:Fault><faultcode>SOAP-ENV:Client</faultcode><faultstring>Content-Type should be set to text/xml</faultstring><detail></detail></SOAP-ENV:Fault></SOAP-ENV:Body></SOAP-ENV:Envelope>

I have tried setting text/xml inside both header and formData respective locations, but no success. Any guidance and pointers will be highly appreciated.
