### ISSUE TITLE
feature: encodeUri flag on path param

### ISSUE THREAD

**Issue by Eomm** [a85/POSTMan-Chrome-Extension#7432]
**Is your feature request related to a problem? Please describe.**
I'm using a path param with chars that need to be escaped with `encodeURI`.
I read the [docs](https://learning.getpostman.com/docs/postman/sending_api_requests/requests/#url) that say to update the value, but I'm using a test suite that set an environment variable.

**Describe the solution you'd like**

It would be great to have a flag in the path parameter setup that does the `encodeURI` before the request. So the developer can focus on business domain value instead...

**Describe alternatives you've considered**

..instead of adding a pre-request script that apply the encode uri to a `{{encoded var}}` and then clean it in the test with `pm.environment.unset("encoded var");`

**Additional context**

Add a flag here:

![image](https://user-images.githubusercontent.com/11404065/66193696-72ac8280-e693-11e9-83ce-663936fed82b.png)

**Comment by vikiCoder** [comment]
@Eomm, this is fixed in the latest [Postman Canary](https://www.postman.com/downloads/canary) release (version 7.20.0-canary03). We now automatically encode path variables in a URL. You can see more details about the fix at #8154

**Comment by codenirvana** [comment]
This is fixed in the latest version of the Postman app (v7.20.0) by enabling the "Use next generation URL processing" setting as mentioned in #8154.

Feel free to leave your feedback at #8154 or reopen this thread if the issue persists.
