### ISSUE TITLE
Beautify button is gone in version 7.8.0

### ISSUE THREAD

**Issue by zackfinix** [a85/POSTMan-Chrome-Extension#7437]
**Describe the bug**
The button for Beautify is no longer available in version 7.8.0

**Screenshots**
<img width="1152" alt="Screen Shot 2019-10-04 at 6 31 28 PM" src="https://user-images.githubusercontent.com/44376351/66247736-339f2100-e6d5-11e9-9ef5-f59783c415fc.png">

**App information (please complete the following information):**
 - App Type [Native App]
 - Postman Version 7.8.0
 - OS: [e.g. macOS Mojave 10.14.6]

**Comment by zackfinix** [comment]
Looks like if I switch to text and then back to json the button will reappear. But it's not showing on any of my saved requests

**Comment by saswatds** [comment]
@zackfinix Just re-clicking on JSON language should get the beautify button back. This is in-fact a bug and we will fixing it ASAP.

Thanks for reporting

**Comment by codenirvana** [comment]
@zackfinix This issue is fixed in the latest version of the Postman app `v7.10.0`.
