### ISSUE TITLE
The `Origin` header should not be blocked.

### ISSUE THREAD

**Issue by Redsandro** [a85/POSTMan-Chrome-Extension#744]
I need to send an `origin` header in a get request but it is blocked.

Please remove  origin` from the blocklist, so I don't have to use [DHC](https://chrome.google.com/webstore/detail/dhc-rest-http-api-client/aejoelaoggembcahagimdiliamlcdmfm) in stead of Postman:

https://github.com/a85/POSTMan-Chrome-Extension/blob/468756a04423411a8e3c60df66f00eb2f11164fd/chrome/js/modules/base.js#L99

**Comment by bvanders** [comment]
Is sending an Origin header still supported using Postman with Interceptor?  I haven't been able to get it to work with Postman 4.1.2 and Interceptor 0.2.18.
