### ISSUE TITLE
Console cannot handle large numbers

### ISSUE THREAD

**Issue by vdespa** [a85/POSTMan-Chrome-Extension#7440]
**To Reproduce**
1. Log the following: `console.log(749617470581443931);`
2. Check the Postman console
3. You will see: `749617470581444000 `
4. Notice that the last 3 digits are now 0. 

**Expected behavior**
The Postman console should be able to log this properly.

**App information (please complete the following information):**
 - App Type  Native App
 - Postman Version 7.8.0
 - OS:  macOS Mojave

**Comment by saswatds** [comment]
Hi @vdespa, as you may be aware `749617470581443931` is a value beyond integer range. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number 
This is a limitation of javascript as the language (As javascript is being used to script the pre-post request events). 
You can even try this in the chrome devtools and find the same result.  The ideal way to represent such big numbers in by using https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt but its fairly a new implementation and not all platforms support it yet and Postman does not either at this point. We are in the process of adding support for new javascript features and will support this in future. 

Thanks.

**Comment by vdespa** [comment]
I understand that. I would have expected for at least a warning to be issued in the Postman console.
