### ISSUE TITLE
Add support for "window -> zoom" menu item

### ISSUE THREAD

**Issue by andrewliles** [a85/POSTMan-Chrome-Extension#7442]
**Describe the bug**
If you regularly add/remove a secondary screen, in some conditions, a Postman window can end up out of view and then there is no way to move it into view.

**To Reproduce**
I do not know what I need to do to cause the problem; generally display switching works normally, but sometimes I find the OS itself seems to re-position all app windows (not just Postman) which is what I think leads to the problem.   

**Expected behavior**
Please fix Postman to detect when windows are out of view to move them into view.

When this happen with other applications, the fix is to invoke the Zoom function (which can be activated using the Window > Zoom menu option).  However, you do not provide the normal Window > Zoom menu option.  This would be an acceptable workaround.

Another workaround is to remove the secondary display and then generally the Postman windows are moved into the native display viewport, but when the secondary display is re-added, the windows resume to their previous off-view port position.

**App information (please complete the following information):**
 - App Type : Native MacOSX application
 - Postman Version : 7.8.0
 - OS: macOS High Sierra 10.13.6

**Configuration files**
I am happy to provide any configuration files you think necessary

**Comment by harryi3t** [comment]
@andrewliles There are two parts to this. The first one is the bug that Postman window should not open in such a low dimension even on adding secondary displays. 
That is being tracked here https://github.com/postmanlabs/postman-app-support/issues/6304

The other is adding that extra menu item for `zoom`. I am marking that as a feature request for that case.

**Comment by arlemi** [comment]
We've added a zoom menu item in Postman 7.27, please update or [download the latest version of the app](https://www.postman.com/downloads/). 🙂
