### ISSUE TITLE
Postman API support for the new APIs Tab

### ISSUE THREAD

**Issue by SimoTod** [a85/POSTMan-Chrome-Extension#7446]
**Is your feature request related to a problem? Please describe.**
At the moment, we can't use Postman API (https://docs.api.getpostman.com/?version=latest) to interact with the new APIs tab (https://learning.getpostman.com/docs/postman/design_and_develop_apis/introduction_to_apis) therefore it's not possible to keep the api definition up to date between postman and a project stored in Github.

**Describe the solution you'd like**
I would like to see a set of endpoints similar to the ones we have for collections.
GET All APIs
GET Single APIs
POST Create APIs
PUT Update APIs 
DELETE Delete APIs
plus
POST Create APIs version

**Describe alternatives you've considered**
Supporting sync integration between postman and github (it only works for collection at the moment).

**Comment by sankalp0o** [comment]
Thanks for writing to us @SimoTod! 

Postman API will soon let you work with APIs, this is already part of our short term roadmap. We're also considering syncing the API definition between Postman and code repos, will let you know as soon as we make progress on it. 

Just curious, do you want to sync from Postman to GitHub or from GitHub to Postman? How are you using your API definition in Postman? It's always exciting to hear how someone is using a new feature and it helps us design a better experience.

**Comment by SimoTod** [comment]
Hi @sankalp0o
That's great news. My team has started a new project and we decided to use the new postman tab to define our APIs and regression tests. We also need the definition file (openapi schema) to be in our project so we can validate incoming requests against the schema and we would like them to sync automatically when the schema changes. 
The direction of the sync (and our dev process) will mostly depend on the tools Postman is going to offer.
At the moment, we sync them manually. 
We defined an initial version in Postman and copied the openapi file inside our project. I'm looking forward to the feature. Thank you very much.

**Comment by sankalp0o** [comment]
@SimoTod We released support for endpoints around APIs, API versions, Schemas and Relating other entities with the API. Please check the documentation here - https://docs.api.getpostman.com/?version=latest#1d08c63e-6d79-4dc7-9e87-ee15de1d74a0

Let me know if this does not help solve your use case.

**Comment by SimoTod** [comment]
Thanks @sankalp0o, it looks perfect. I'll give it a go. Thanks again.

**Comment by SimoTod** [comment]
@sankalp0o Sorry, it may be a silly question but how can I get the schemaId to call getSchema ({{url}}/apis/{{apiId}}/versions/{{apiVersionId}}/schemas/{{schemaId}}).

I was expecting to have a getAllSchemas ({{url}}/apis/{{apiId}}/versions/{{apiVersionId}}/schemas}). Would it be possible to add it?

**Comment by SimoTod** [comment]
Sorry for the noise, I think I found the answer to my question and a small bug. The documentation says that the ApiVersion object should include a list of schemas (https://docs.api.getpostman.com/?version=latest#e7e1d153-a66c-4ecc-b541-864543d14198) but, at the moment, it doesn't.

**Comment by jazzyarchitects** [comment]
Hi @SimoTod 
Thanks for pointing out this issue. We have added this bug fix to our next release which should happen before end of this month.

Since an APIVersion supports only a single schema, we would be providing the list of schema ids in the `APIVersion findOne` request as stated in the documentation instead of providing a `getAllSchemas` .

**Comment by jazzyarchitects** [comment]
Hi @SimoTod 
We have fixed the issue. Now you should be able to get schema ids in the APIVersion object (https://docs.api.getpostman.com/?version=latest#e7e1d153-a66c-4ecc-b541-864543d14198).

Let us know if you face any other issue

**Comment by SimoTod** [comment]
Thank you, I'll give it a go tomorrow. 👍

**Comment by sankalp0o** [comment]
Closing the issue for now. Happy to hear more thoughts on the API!
