### ISSUE TITLE
Header suggestion does not get hightlighted

### ISSUE THREAD

**Issue by singhravi1** [a85/POSTMan-Chrome-Extension#7447]
When you type something, for example, "auth", and press down button once, it should highlight the first suggestion which is "Authorization". If you'd press enter it would select it but *it is not highlighted*

To reproduce:
- Type "auth" in headers key field.
- You'd see two suggestions, "Authorization" and "Proxy-Authorization"
- Press down button once.
- Now, "Authorization" option should get highlighted, but it doesn't (Its selected though. If you'd press down again, you can see "Proxy-Authorization" gets highlighted)

Expected: It should get highlighted.

Native postman App , Version: 7.8.0, Ubuntu 18.04

**Comment by numaanashraf** [comment]
Thanks again for reporting this @singhravi1. We've resolved this issue in Postman v7.16.0.
