### ISSUE TITLE
Cannot set Postman variable with large numbers #7440

### ISSUE THREAD

**Issue by vdespa** [a85/POSTMan-Chrome-Extension#7448]
**To Reproduce**

- Run the following code `pm.globals.set("id", 749617470231784573);`
- Check the global variables
- You will notice that the value that was saved is: `749617470581444000`
- Notice that the last 3 digits are now 0.

**Expected behavior**
Postman variables should be able to handle large numbers.

**App information (please complete the following information):**

App Type Native App
Postman Version 7.8.0
OS: macOS Mojave

Related to: #7440

**Comment by koreyba** [comment]
Actually for me setting of variables just doesn't work at all with latest update (7.8.0)
This doesn't work:
pm.environment.set("variable_key", "variable_value");
pm.globals.set("variable_key", "variable_value");});

**Comment by saswatds** [comment]
Referring back to https://github.com/postmanlabs/postman-app-support/issues/7440#issuecomment-549239543
Javascript as a language truncates the number. BigInt support is still experimental.

**Comment by saswatds** [comment]
Closing this issue for now. You can create a feature request for BigInt support in variables.
