### ISSUE TITLE
Wrong user slots availability in Team management  [Web Dashboard]

### ISSUE THREAD

**Issue by cyrielle-hada** [a85/POSTMan-Chrome-Extension#7449]
_Filed by Product Support_

**Describe the bug**

The web dashboard shows that there are no available slots for his 2 slots team while there is only one User (`Developer` role) in the team. 

![Team management issue](https://user-images.githubusercontent.com/47351631/66401105-81b86b00-e9da-11e9-9d93-7580a55f2ad2.png)

**To Reproduce**

1.  Purchaser bought 2 Enterprise licenses for an Enterprise team and gave a **User A** the `Billing` role.
2. **User A** (`Billing` role) tries to invite the Purchaser - **User B** to the team.
3. On our end, there are 2 pending invites sent to **User B** - one (1) to join the team as a `Billing` and `Admin` user and another separate one (2) to join as `Developer` which might _would_ explain the that 2 slots are already taken. The **user A** you _should_ be able to see the second pending invite but doesn't.
4. All Pending invites were disabled internally
5. The dashboard says that the team has 0 slots available.
![Team management issue 2](https://user-images.githubusercontent.com/47351631/66400771-0060d880-e9da-11e9-8ae6-ff999186cd67.png)

**Expected behavior**
**User A** should be able to invite another user to the team with a Developer role.
The slot availability should be **1/2**. 

**Additional context**
I don't know if it is relevant but before the issue, I manually updated the role of user A internally.

**Comment by debjeetsarkar** [comment]
This should be fixed now.
