### ISSUE TITLE
Lost my collections

### ISSUE THREAD

**Issue by mnbao1975** [a85/POSTMan-Chrome-Extension#745]
Hi all,

Yesterday when I opened Postmen extension, all collection and environment settings are disappeared.

Any help please.

Thanks,
Bao

**Comment by billga3** [comment]
The path to the indexDb is somewhat different for different OSs.  But it's easy to find using this service URL : chrome://indexeddb-internals/

In Win7 I had pretty good success restoring my collections after an inadvertent uninstall by using the "Restore previous version" command from right click on the emptied folder, then doing copy to new folder location.   Note: I think I was a bit lucky in that I used a different profile for the reinstall...

**Comment by a85** [comment]
This issue has been fixed by Google in the latest version of Chrome. We now provide a backup service for free to individual users: http://blog.getpostman.com/2015/03/03/postman-2-0-with-sync-is-here/
