### ISSUE TITLE
Variable is not resolving for all objects when value is missing in one Json object

### ISSUE THREAD

**Issue by ronenneumark** [a85/POSTMan-Chrome-Extension#7450]
**Describe the bug**
Variable is not resolving for all objects when a value is missing in one JSON object.
i would like to use JSON as reference for the collection runner, however some of the objects are not containing specific param, and I saw that runner ignore this param even if it exists in other objects in the JSON file. in the example below the following elements are missing from the first object: Actor1,Actor2,Actor3.
`[
	{
		"StartTimeInEpoch": "1570062600",
		"endtimeInEpoc": "1570064400",
		"LinearAssetID": "990149",
		"epg_title": "Just for Laughs: Gags",
		"epg_desc": "Hidden cameras record responses to practical jokes.",
		"Summary_short": "Hidden cameras record responses to practical jokes.",
		"Genraname": "Comedy",
		"ParentalRating": "14+",
		"SeriesID": "185761",
		"broadcast_date": "20010422",
		"channel_id": "CBXT",
		"ProgramID": "12396",
		"image_url": "http://tmsimg.com/assets/p185761_b_h5_ao.jpg",
		"crid": "SH004142520000",
		"Run_Time": "1800"
	}, {
		"StartTimeInEpoch": "1570064400",
		"endtimeInEpoc": "1570066200",
		"LinearAssetID": "990149",
		"epg_title": "Still Standing",
		"epg_desc": "Once known as the Wheat Capital of Canada, the people of Vulcan get creative so they can live long and prosper.",
		"Summary_short": "Once known as the Wheat Capital of Canada, the people of Vulcan get creative.",
		"Genraname": "Reality",
		**"Actorname1": "Drew Barrymore",
		"Actorname2": "Beau Bridges",
		"Actorname3": "Jonny Harris",
		"ParentalRating": "14+",**
		"SeriesID": "11810367",
		"broadcast_date": "20170829",
		"channel_id": "CBXT",
		"ProgramID": "1214747",
		"image_url": "http://tmsimg.com/assets/p11810367_b_h5_ae.jpg",
		"crid": "EP021920000037",
		"SeasonID": "14397409",
		"Run_Time": "1800"
	}
]`

**To Reproduce**

**Expected behavior**
The runner identify that the first object has no params and will insert a null or empty string without impacting all other objects
**Screenshots**
If applicable, add screenshots to help explain your problem. Please make sure the screenshot does not contain any sensitive information such as API keys or access tokens. 

**App information (please complete the following information):**
 - App Type [e.g. Chrome App, Native App]
 - Postman Version [e.g. 6.0.1]
 - OS: [e.g. macOS High Sierra 10.13.2]

**Additional context**

**Comment by coditva** [comment]
Hey @ronenneumark, thanks for writing in!

This is the expected behaviour. Runner expects every element in the data array to have the same keys. The first element is used to set the expectations. **If there is any key that is not present in the first element, it is not imported.**

To do this, you must edit your data file and add the missing keys in the first element:
```json
[
    {
        "Actorname1": "",
        "Actorname2": "",
        "Actorname3": "",
        "Genraname": "Comedy",
        "LinearAssetID": "990149",
        "ParentalRating": "14+",
        "ProgramID": "12396",
        "Run_Time": "1800",
        "SeasonID": "",
        "SeriesID": "185761",
        "StartTimeInEpoch": "1570062600",
        "Summary_short": "Hidden cameras record responses to practical jokes.",
        "broadcast_date": "20010422",
        "channel_id": "CBXT",
        "crid": "SH004142520000",
        "endtimeInEpoc": "1570064400",
        "epg_desc": "Hidden cameras record responses to practical jokes.",
        "epg_title": "Just for Laughs: Gags",
        "image_url": "http://tmsimg.com/assets/p185761_b_h5_ao.jpg"
    },
    {
        "Actorname1": "Drew Barrymore",
        "Actorname2": "Beau Bridges",
        "Actorname3": "Jonny Harris",
        "Genraname": "Reality",
        "LinearAssetID": "990149",
        "ParentalRating": "14+",
        "ProgramID": "1214747",
        "Run_Time": "1800",
        "SeasonID": "14397409",
        "SeriesID": "11810367",
        "StartTimeInEpoch": "1570064400",
        "Summary_short": "Once known as the Wheat Capital of Canada, the people of Vulcan get creative.",
        "broadcast_date": "20170829",
        "channel_id": "CBXT",
        "crid": "EP021920000037",
        "endtimeInEpoc": "1570066200",
        "epg_desc": "Once known as the Wheat Capital of Canada, the people of Vulcan get creative so they can live long and prosper.",
        "epg_title": "Still Standing",
        "image_url": "http://tmsimg.com/assets/p11810367_b_h5_ae.jpg"
    }
]
```

Hope that helps! Closing this issue; do revert if any queries. :)
