### ISSUE TITLE
Add support for Swagger 2.0 Path Parameters

### ISSUE THREAD

**Issue by chrisdeso** [a85/POSTMan-Chrome-Extension#7451]
**Is your feature request related to a problem? Please describe.**
Currently, importing a Swagger 2.0 file that contains path parameters throws an error – `Error while importing Swagger 2.0: Could not import”`.

i.e. 
```
"paths": {
        "/someApi/json?{PATH PARAMETER}": {
            "get": {
                "summary": "GET some things",
                "description": "Does a thing",
                "parameters": [
                    {
                        "name": "David",
                        "in": "query",
                        "description": "Your first name",
                        "required": true,
                        "type": "string"
                    },
                    {
                        "name": "Byrne",
                        "in": "query",
                        "description": "Your last name",
                        "required": true,
                        "type": "string"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        }
```
* [Swagger 2.0 Path Parameters](https://swagger.io/docs/specification/describing-parameters/#path-parameters)

**Describe the solution you'd like**
Support for path parameters for Swagger 2.0 spec files.

**Describe alternatives you've considered**
If mapping the parameters to something similar in Postman (Environment, collection, script vars), ignoring the path parameters entirely or surfacing an error message indicating which portion of the file isn't supported.

**Additional context**
[Filed by Postman]

**Comment by abhijitkane** [comment]
@chrisdeso We're working on the issue that's preventing importing this sort of schema. However, on the Swagger Editor, this schema shows an error - 
```
Semantic error at paths./pet/{petId}?{qp}
Query strings in paths are not allowed.
```

**Comment by preethammavin** [comment]
Closing the issue for now as the schema was not valid and the user was unblocked by editing the schema
