### ISSUE TITLE
Feature Request: Access raw API definition file

### ISSUE THREAD

**Issue by tomsowerby** [a85/POSTMan-Chrome-Extension#7452]
The new API definition section is great, and it generates good documentation. We’d like to use it as the “source of truth” for our API specification, but to do that, we would need a way to access a particular version of the raw file so that it can be used during the validation stages of our build process. 
I can’t see a way to do this.

Ideally, an export endpoint would be available on the API to retrieve a given API definition and optional version. This would return the raw OpenAPI3 file for use elsewhere.

Thanks.

**Comment by tomsowerby** [comment]
Perhaps could be solved by https://github.com/postmanlabs/postman-app-support/issues/7446 actually. I'll consider this related.

**Comment by sankalp0o** [comment]
@tomsowerby Just released endpoints for working with schemas, please check it out - https://docs.api.getpostman.com/?version=latest#1d08c63e-6d79-4dc7-9e87-ee15de1d74a0

Let me know on  #7446 if there's anything we can do to improve it!
