### ISSUE TITLE
json key including char '-' not referenced correctly

### ISSUE THREAD

**Issue by Cugar15** [a85/POSTMan-Chrome-Extension#7454]
Following json is returned by the website:

`
{
    "x-access-token": "some_stuff"
}
`

In Tests, the following code is executed:

`
var data = pm.response.json();
console.log(data.x-access-token);
`

The following error is created in the console:

`
ReferenceError | access is not defined
`

Looks like the key is cut after the '-'

Any comments/help?

Thanks

**Comment by vvs11** [comment]
Hi @Cugar15 , Thanks for writing in
can you try using `console.log(data['x-access-token'])`?
let us know how it works out 😄

**Comment by Cugar15** [comment]
yes, this works...

Thanks!
