### ISSUE TITLE
Improve Invite member flow in Team Management 

### ISSUE THREAD

**Issue by cyrielle-hada** [a85/POSTMan-Chrome-Extension#7457]
_Reported by Product Support_

**Is your feature request related to a problem? Please describe.**

The flow to add support-only accounts on [https://go.postman.co/team/invite](https://go.postman.co/team/invite) may be confusing as the action of adding Via Email automatically attributes the Developer role and you cannot untick the box for Developer while there is no slot available for the team.

![Invite user](https://user-images.githubusercontent.com/47351631/66495836-d67ae500-eab1-11e9-920e-337e8958de9b.gif)

The user goes ahead and the web dashboard throws an error.
<img width="640" alt="PastedGraphic-11" src="https://user-images.githubusercontent.com/47351631/66495937-fe6a4880-eab1-11e9-9d60-5d216ae30a83.png">

**Describe the solution you'd like**
- Grey out the Developer role option when there is no more slot available in the team.
- Bring the count down of the user slot available below and make it more obvious.

<img width="576" alt="Screen Shot 2019-10-09 at 16 31 07" src="https://user-images.githubusercontent.com/47351631/66496296-9f590380-eab2-11e9-9f0c-d2edb51e5b9a.png">

**Comment by mccannt** [comment]
@cyrielle-hada We have made improvements to this flow. Can you review and close this out if you are satisfied with the solution?

**Comment by cyrielle-hada** [comment]
@mccannt way better like this! 💯 
<img width="573" alt="Screenshot 2020-08-28 at 10 56 26" src="https://user-images.githubusercontent.com/47351631/91541769-c01d8800-e914-11ea-8312-04c67fe1cc83.png">
I'm closing this issue.
