### ISSUE TITLE
Session has Expired Error - Failure to Authenticate

### ISSUE THREAD

**Issue by kriggo15** [a85/POSTMan-Chrome-Extension#7459]
Note that my previous issue was closed as my IT department worked on a solution but the issue still persists. [https://github.com/postmanlabs/postman-app-support/issues/7256](url)

**Describe the bug:**
When trying to sign into the desktop app, I'm receiving an error around connecting to the authentication service. When clicking on Retry, I receive the same error. I am able to log into the web portal and see all of my information. Colleagues are running the same application version utilizing the same connection and are not experiencing the same issue.

**To Reproduce**
1. Click on Sign In
2. Postman tries to authenticate and fails.
3. See error

**Expected behavior**
When clicking Sign In, I expect to be prompted for my credentials and to be able to log in.

**Screenshots**
![Postman 1](https://user-images.githubusercontent.com/54848612/66582785-4fc91500-eb50-11e9-82a2-32561aac076d.png)
![Postman 2](https://user-images.githubusercontent.com/54848612/66582795-53f53280-eb50-11e9-85d1-2c303a1e9c31.png)

**Comment by preethammavin** [comment]
@kriggo15 that shouldnt happen, can you verify if it occurs on other networks as well? 

Can you try running the collection in this documentation so that we know if we are able to connect to our service, https://documenter.getpostman.com/view/6314135/SVfJTB7J?version=latest. Thanks

**Comment by BigMing8** [comment]
I also have this situation, I entered the correct username and password, but the prompt "Incorrect credentials provided." I am a Chinese user. Do I need a VPN?

**Comment by preethammavin** [comment]
@BigMing8 if you are getting incorrect credentials, can you reset the password and try again?

**Comment by BigMing8** [comment]
Yes，I tried，but I couldn't get the mail!------------------ 原始邮件 ------------------
发件人: "Preetham"<notifications@github.com>
发送时间: 2019年10月13日(星期天) 凌晨0:18
收件人: "postmanlabs/postman-app-support"<postman-app-support@noreply.github.com>;
抄送: "BigMing8"<1059848654@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [postmanlabs/postman-app-support] Session has Expired Error -Failure to Authenticate (#7459)



@BigMing8 if you are getting incorrect credentials, can you reset the password and try again?
 
&mdash;

**Comment by BigMing8** [comment]
Yes，I tried，but I couldn't get the mail！

**Comment by preethammavin** [comment]
@BigMing8 can you write to us at help@getpostman, we will help sort it out.

**Comment by kriggo15** [comment]
I was able to connect on a different network. Appears to be a issue on my company's side on the connection.

**Comment by preethammavin** [comment]
@kriggo15 got it, if you are stuck the next time, do run the collection the logs are quite informative to understand if the issue is with the network. :)
