### ISSUE TITLE
Environment sync not working anymore

### ISSUE THREAD

**Issue by fglazemakers** [a85/POSTMan-Chrome-Extension#7465]
**Describe the bug**
We work in teams and when a user adds/changes environment variables theyre values are not synced anymore to the other team members which worked previously without issues. Even when syncing explicitly. Noticed issue since 10/10/2019. We see the variable key appearing but not the values.

**To Reproduce**
1. Go to environments and add variable with values
2. Click on update
3. login with other team member account and view environment variable
4. No values are filled in 

**Expected behavior**
We expect both keys and values to be shared

**App information (please complete the following information):**
 - App Type Native app 
 - Postman Version 7.9
 - OS: Windows 10

**Additional context**

**Comment by preethammavin** [comment]
@fglazemakers as you mentioned that the variable_keys are present but not the values, most likely the users are updating the current value which is only kept locally and not synced. This is done in case you want to keep API-keys or access tokens in environment variables and do not accidentally sync them across.

For the values that you want to sync please keep them in initial value as these are synced, if you want no difference between the current and initial value you can set the automatically persist variable values  to true which will always sync current and initial value .


For more information please look at the documentation `https://learning.getpostman.com/docs/postman/environments_and_globals/Sessions/` 

I would suggest moving to using the initial and current values to keep the parity between onboarding a user to a request and keep secret values safe.
