### ISSUE TITLE
OpeanAPI import Error Message Not Helpful

### ISSUE THREAD

**Issue by lordrhodos** [a85/POSTMan-Chrome-Extension#7468]
**Describe the bug**
Can not import a valid OpenAPI speficication from a local file and can not get any further information what the error is. The only information I get is:

> Error while importing Open API 3.0: Could not import

**To Reproduce**
Checkout the repository here:

https://github.com/rodacker/members-openapi-specification

and try to import the specification here
https://github.com/rodacker/members-openapi-specification/blob/postman-error-while-importing/reference/members/openapi.json

**Expected behavior**
successful import 

**Additional context**
specification is in json

Postman 
Version 7.9.0 (7.9.0)

**Comment by kneufeld-pbp** [comment]
I am having a similar issue with 
Postman Version: 7.9.0
os: macOS 10.14.6

### To Reproduce:
Importing TeamCity Swagger:
https://gist.githubusercontent.com/kneufeld-pbp/cd4db727e63f3f8ba2da9b3b16202e79/raw/6fdb0590ba98415b3222581189c9189f2ce70de9/TeamCity_2018_swagger.json

ON Import from link OR from file Postman hangs with a blank black window which has to be forced quit and restarted.

**Comment by cyrielle-hada** [comment]
@lordrhodos @kneufeld-pbp while we're investigating the underlying issue. You might want to try this workaround. 

1 - Create a new API 
<img width="286" alt="Screen Shot 2019-12-17 at 11 15 33" src="https://user-images.githubusercontent.com/47351631/70991001-955d0d80-20be-11ea-90ba-624750c14ac6.png">
2 - Import your file
<img width="259" alt="Screen Shot 2019-12-17 at 11 16 00" src="https://user-images.githubusercontent.com/47351631/70991038-a3129300-20be-11ea-94cb-ca457958c032.png">
3 - Save your Schema 
<img width="1367" alt="Screen Shot 2019-12-17 at 11 16 48" src="https://user-images.githubusercontent.com/47351631/70991145-d2c19b00-20be-11ea-9631-357e1d2e7d6e.png">
4 - Generate the collection
<img width="1371" alt="Screen Shot 2019-12-17 at 11 17 57" src="https://user-images.githubusercontent.com/47351631/70991238-fbe22b80-20be-11ea-9968-ee91f1995da9.png">

**Comment by umeshp7** [comment]
@lordrhodos We can confirm that the schema provided by you imports successfully in v7.19.1. I request you to update Postman app and try again. 

@kneufeld-pbp 
We are tracking the issues with App freezing here. https://github.com/postmanlabs/postman-app-support/issues/7844.
