### ISSUE TITLE
App opens in browse view after update to 7.9.0

### ISSUE THREAD

**Issue by lordrhodos** [a85/POSTMan-Chrome-Extension#7469]
**Describe the bug**
After the update to `7.9.0` all links from existing collections open in a new browser tab instead of the app ... maybe MacOS related (MacOS High Sierra 10.13.6)

**To Reproduce**
click on an exisiting collection 

**Expected behavior**
click should open the colelction in side the already opened app

**App information (please complete the following information):**
- mac os native app
 - Postman Version [e.g. 7.9.0]
 - OS: [e.g. macOS High Sierra 10.13.6]

**Comment by sankalp0o** [comment]
@lordrhodos I'm not completely sure what's happening, but I have a hunch that you are in the "Browse" view of the app. Look for a toggle on the bottom of the screen and go to the "Build" view to continue your work.

Please let us know if this does or does not solve your problem, and maybe add some screenshots if this does not.

**Comment by lordrhodos** [comment]
@sankalp0o thx for your feedback. You are right, it was the `Browse` view and after I restarted the app yesterday it was back to "Build" view. I had never use the browse view before therefore I have been confused. Not sure if the update mechanism changes this though or if I managed to change it by accident 🤔 

Anyway, why would links in the "Browse" view inside the local app link to the web app and not the local one?

**Comment by sankalp0o** [comment]
Glad this worked @lordrhodos!
Do you use multiple workspaces? Sometime when you switch to another workspace which you haven't joined (through the dropdown on the header in the middle), you end up in Browse view by default.

Regarding your question, the links open in the web app for the time being but we are making efforts towards changing this behaviour. There are a couple of design as well as engineering problems we have to solve before that's possible. Happy to hear more thoughts about your short experience with the Browse view! 😄 

I'm keeping this ticket open to investigate further and also to keep this discussion going, so feel free to respond!

**Comment by sankalp0o** [comment]
Closing this ticket as we didn't notice more incidents of the same. We're also working on making sure users who land up in browse view (accidentally or not) know how to switch back.
